### ISSUE TITLE
Mixer EL should support < and > operators

### ISSUE THREAD

**Issue by robertpanzer** [istio/istio#10012]
**Describe the feature request**
Currently the Mixer EL only supports operators that check for equality (or inequality).
It would be good if there were also operators to compare two values for greater than and less than, i.e. `<` and `>`.
Maybe even `<=` and `>=`.

**Describe alternatives you've considered**
There are no alternatives to my knowledge.

**Additional context**
{{ Add any other context about the feature request here }}

**Comment by robertpanzer** [comment]
Created #10086 to add this.

**Comment by douglas-reid** [comment]
https://github.com/istio/istio/pull/10678 was merged. I'm marking this as CLOSED for 1.1.
