### ISSUE TITLE
Mixer EL should support string length function

### ISSUE THREAD

**Issue by robertpanzer** [istio/istio#10011]
**Describe the feature request**
The Mixer EL has some functions for strings to match them with a regex, and methods to check for prefixes, suffixes etc.
It would be nice if there would be a method to get the length of a string.
I.e. a match condition in a Rule like `"abc".length() == 3` should evaluate to true.

**Describe alternatives you've considered**
An alternative could be to match against a regex like `^.{3}$`, which is very bad performance-wise and not readable.

**Comment by kyessenov** [comment]
FWIW, CEL supports `size` function: https://github.com/google/cel-spec/blob/master/doc/langdef.md#functions.

**Comment by robertpanzer** [comment]
Hm... both `size("foo")` and `"foo".size()` give me `unknown function: size.
Is there anything that I am doing wrong? 
From the document I would assume that the first example should work.

**Comment by kyessenov** [comment]
Sorry, I didn't mean we support them! Thank you for making the contribution to add it. We do want some alignment between our IL and CEL. It's not on any short-term road map. Picking the same function names might just help in the longer term if we decide to extend IL to full CEL.

**Comment by robertpanzer** [comment]
Ah ok, thanks for the clarification :-) 
I was already on the way providing a PR for `.length()`.
But I'll adapt it then to `size(arg)`.

**Comment by robertpanzer** [comment]
Looks like it is not that easy to add polymorphic functions.
I will need some more time to find out how that would work and to understand the whole architecture of that thing.

**Comment by kyessenov** [comment]
@robertpanzer are you working on this?

**Comment by robertpanzer** [comment]
No, I am not working on this right now.
I was thinking about adding this to my other PR that extends the EL, but then decided to not let it grow too big.
