### ISSUE TITLE
Mixer: invalid attributes: duplicate attribute

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#10014]
This is only seen when 1.1 proxy communicates with 1.0 Mixer.

Ostensibly, this is not supported, but It is very helpful for testing.
If this is easy to fix, we should fix it in 1.1

```
2018-11-16T18:17:43.920654Z    error    api    Report failed:1 error occurred:

* request could not be processed due to invalid attributes: duplicate attribute  (type string, was string)
```

**Comment by kyessenov** [comment]
This is because the lookup fails for a global attribute (the list grew once again).
Words 203 and 205 are not present in 1.0. The code leniently falls back to an empty string, which later leads to a collision.

What should mixer do in general with regards to unknown words from the global dictionary?

/cc @geeknoid @douglas-reid

**Comment by douglas-reid** [comment]
Which version of the attribute manifest is in use in a 1.1 proxy -> 1.0 mixer scenario ?

**Comment by kyessenov** [comment]
I think it's the proxy error code and the query parameter attributes that @bianpengyuan added in between 1.0 and 1.1. We don't really version the manifest itself.

**Comment by douglas-reid** [comment]
Yeah, I wondering though if the manifest contains those attributes... and what the meaning of the manifest is in such a scenario.

Maybe we should appropriately version the manifests?  That might help with any error responses and/or graceful degradation issues.

**Comment by geeknoid** [comment]
The expected protocol here is that Mixer must always be >= to the proxy's
version.

**Comment by kyessenov** [comment]
@mandarjog Per Martins' comment, closing the issue as the requested scenario is not supported.
There's nothing Mixer can do if it doesn't know extra global words.
