### ISSUE TITLE
FR: Namespace isolation

### ISSUE THREAD

**Issue by castlemilk** [istio/istio#10039]
**Describe the feature request**
Currently Istio violates namespace isolation by applying configuration to all sidecars/gateways. This can lead to undesired behaviour when establishing a multi-tenanted or mirrored environment. Some of these issues include:
* overlapping hosts for ingress/egress use-cases (mitigated if pilot/galley did some validation against already existing host entries in the mesh)
* allowing undesired egress to north/south services, external to the mesh (mitigated by `Authorization` CRD, but this is additional configuration that could be avoided)
* Manipulating routing via `VirtualService` resources across namespaces
* large number of policies defined in one namespace and used in that namespace, impacting others sidecars in other namespaces that aren't using defined policies, by "impact" i mean increase resource consumption of sidecars as LDS/RDS/EDS configuration grows. Additionally, creation noise and potentially instabilities in sidecar functionality via config rejection such as described in [#8541](https://github.com/istio/istio/issues/8541), [#9659](https://github.com/istio/istio/issues/9659).

Overall it would insulate different environments more effectively if unnecessary configuration is not pushed to ALL sidecars/gateways.
I imagine this could be made possible by applying the required namespace filtering in Pilot/Galley before pushing the required configuration out to mesh components?

**Comment by Stono** [comment]
https://github.com/istio/istio/issues/11664#issuecomment-467153211

**Comment by howardjohn** [comment]
This should be handled by the [Sidecar](https://istio.io/docs/reference/config/networking/v1alpha3/sidecar/) now in 1.1. If there are issues with this please open an issue, currently everything should follow namespace isolation (as specified in the Sidecar, not out of the box)
