### ISSUE TITLE
Have no permission to re-run CircleCI

### ISSUE THREAD

**Issue by supereagle** [istio/istio#10040]
Sometime CI failures are flakes, not related with the PRs. We need to re-run them to pass CI. 
There is commands to re-run Prow CI, but none for CircleCI. I find a useful wiki [Working with CircleCI](https://github.com/istio/istio/wiki/Working-with-CircleCI) , but still have no permission to re-run CircleCI.

![image](https://user-images.githubusercontent.com/3390333/48668078-98827480-eb1f-11e8-81bf-aa73cead4197.png)

![image](https://user-images.githubusercontent.com/3390333/48668079-9c15fb80-eb1f-11e8-801b-385c093168eb.png)

How to get the permission to re-run CircleCI? 

/cc @rshriram  @geeknoid

**Comment by loewenstein** [comment]
This is still a problem.

**Comment by kevinsimper** [comment]
You can retrigger builds with a command like this:
```
$ type trigger
trigger is a function
trigger ()
{
    git commit --amend --no-edit && git push -f
}
```

**Comment by loewenstein** [comment]
Well, this would remove any kind of approval, lgtm and the like.

**Comment by supereagle** [comment]
Want to re-run CircleCI test cases just like re-running prow test cases though commands.
