### ISSUE TITLE
Configurable AcessLogFormat

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#10056]
At present, Istio is unable to configure accessLog format per evnoy's access [Log definition](https://www.envoyproxy.io/docs/envoy/latest/configuration/access_log#configuration).

1. Add `AccessLogFormat` to mesh config
2. Add `AccessLogEncoding`   (text, json ...)

Ensure that those two settings interoperate correctly.

At present `AccessLogFormat` is hardcoded

**Comment by linsun** [comment]
discussed with @GregHanson - he thinks all the items merged should have covered this WI.

**Comment by duderino** [comment]
Related bug:  https://github.com/istio/istio/issues/11394
