### ISSUE TITLE
remove mandatory dependency on udp statsd

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#1005]
We shouldn't have 2 conduits sending similar information between envoy and the mixer pod(s), half through grpc report calls and half through udp statsd

or at least the udp statsd part needs to be easy to turn off
(eg `istioctl kube-inject --statsdAddress=none ...`)

We need also to offer the option to switch to tcp (but again, we should really not have 2 different conduits from envoy to mixer pod, mixer client should probably carry that information instead)

This came up in part in https://github.com/istio/issues/issues/84

**Comment by sakshigoel12** [comment]
@geeknoid  please assign this issue if it is still considered P0.

**Comment by ldemailly** [comment]
is this covered now in helm ? @linsun do you know ? (turning off udp statsd easily and/or switching to tcp)

**Comment by douglas-reid** [comment]
There is another open issue that is related to configuring envoy metrics output: https://github.com/istio/issues/issues/295

until we have mixer direct api support, there is no path for eliminating the gathering of envoy metrics in a manner distinct from mixer-generated metrics.

**Comment by douglas-reid** [comment]
@cmluciano i believe those logs are harmless (or, at least they were).

**Comment by ldemailly** [comment]
this came up again today in Perf WG: having a single channel of telemetry data flowing from envoy container instead of 2 would be good.

**Comment by douglas-reid** [comment]
Yup. And work is still scheduled for that, it is just slightly lower priority than all the other P0s ;p.

**Comment by cmluciano** [comment]
I think this is still relevant cc @douglas-reid @mandarjog

**Comment by douglas-reid** [comment]
@cmluciano a PR went in a few days ago that removes the dep on udp statsd. there is some more work to be done to refine the initial patch, but I'd say it is probably ok to close this issue for now.
