### ISSUE TITLE
Propose to support MeshConfig CRD 

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#10082]
Currently the meshConfig is deferred from configmap `istio`. 

```bash
root@szvp000201060:/mnt/go/src/istio.io/istio# kubectl get configmap -n istio-system istio -oyaml
apiVersion: v1
data:
  mesh: "# Set the following variable to true to disable policy checks by the Mixer.\n#
    Note that metrics will still be reported to the Mixer.\ndisablePolicyChecks: false\n\n#
    Set enableTracing to false to disable request tracing.\nenableTracing: true\n\n#
    Set accessLogFile to empty string to disable access log.\naccessLogFile: \"/dev/stdout\"\n#\n#
    Deprecated: mixer is using EDS\nmixerCheckServer: istio-policy.istio-system.svc.cluster.local:9091\nmixerReportServer:
    istio-telemetry.istio-system.svc.cluster.local:9091\n\n# Unix Domain Socket through
    which envoy communicates with NodeAgent SDS to get\n# key/cert for mTLS. Use secret-mount
    files instead of SDS if set to empty. \nsdsUdsPath: \"\"\n\n#\ndefaultConfig:\n
   .....
```

By which the config is difficult to read and update. If change it to a CRD like other apis, it will be easy to maintain by administrators.

**Comment by rshriram** [comment]
What else will break? Keep in mind that the mesh config is needed in order for Pilot to know where Galley servers are. So, if Galley is the only one that can read CRDs in future, then we have a problem. So at minimum we need some mesh config map that can be supplied to pilot and mixer to bootstrap themselves. Everything else in mesh config should definitely move to CRD as you suggest. 

I am open to the idea for sure.

**Comment by ozevren** [comment]
Agree with @rshriram & @ayj. It would be nice to have a rationalized proposal that outlines the shape of the CRD, as well as what would be the new shape of the Mesh config that contains streamlined bootstrapping options.

**Comment by howardjohn** [comment]
The readability argument is not a reason to do this anymore, it has been fixed in https://github.com/istio/istio/pull/16820. Still other reasons to do this though

**Comment by ayj** [comment]
The original issue is no longer relevant. The CRD vs. ConfigMap argument has been considered as part of the general improvements to the mesh runtime config.
