### ISSUE TITLE
mixer codegen uses old gogo

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#10092]
It turns out that mixer codegen uses gogo inside the image gcr.io/istio-testing/protoc:2018-06-12. This image contains an old version of gogo, which is inconsistent with the istio vendored gogo.

**Comment by douglas-reid** [comment]
first step is generating a new `protoc` image. iirc, the script lives in istio/api in the tools/protoc dir. I can try running it from my desktop later today.

**Comment by kyessenov** [comment]
using `protoc` inside `mixgen` makes the whole go generate slower than running protoc binary.
perhaps, we could try running protoc directly with locally built plugins.

**Comment by douglas-reid** [comment]
we switched away from that so that people wouldn't be required to install protoc on their own machines, nor manage versions (which were issues in early istio days).

`gcr.io/istio-testing/protoc:2018-11-26` is available for testing now.

**Comment by kyessenov** [comment]
@douglas-reid This doesn't prevent out-of-sync issues. The plugins (gogo, protodoc) are in this source tree. If we want to use vendored sources, then we need to build them, and run them as part of a native protoc. Or we can build them in docker, but then someone needs to make sure docker versions are same as vendored versions.

**Comment by kyessenov** [comment]
not stale

**Comment by douglas-reid** [comment]
As with all things Mixer, I don't forsee any work going into improving the state of things here. Closing.
