### ISSUE TITLE
getting lots of "upstream connect error or disconnect/reset before headers"

### ISSUE THREAD

**Issue by sokoow** [istio/istio#1010]
Hi All,

I'm getting lots of ```upstream connect error or disconnect/reset before headers``` when running the helloworld example, is this a stability issue ?

**Comment by linsun** [comment]
Hi, thanks for reporting this.  Could you check if your helloworld pod is running when you hit this?  BTW, which version of Istio are you using?

**Comment by sokoow** [comment]
Hey, you were right, it was one of the versions of helloworld that wasn't running
