### ISSUE TITLE
Handling envoy protocol errors with routes

### ISSUE THREAD

**Issue by knrc** [istio/istio#10105]
**Describe the bug**
While running tests on 1.0 we discovered a race between pilot's push and envoy's processing of the resources, if routes are sent before envoy is prepared to respond to them then envoy will log the following error

> Ignoring unwatched type URL type.googleapis.com/envoy.api.v2.RouteConfiguration

and responds with a DiscoveryRequest containing the correct nonce but the previous version.  When envoy eventually asks for the routing information pilot refuses to provide it, resulting in the sidecar (in our case ingressgateway) having no routes and therefore unable to communicate to services.

**Expected behavior**
Pilot should handle the protocol error response and continue to serve routes to the sidecar

**Steps to reproduce the bug**
This is hard to describe since it is a race, I do have a unit test as part of the PR which mimics the issue and fails with the current implementation.

**Version**
We have seen this on Istio 1.0.2, 1.0.3 and 1.0.4

**Installation**
We first discovered it using the Red Hat Maistra distribution of Istio and have reproduced it using upstream community versions

**Environment**
OpenShift plus Maistra

**Comment by knrc** [comment]
I've included two configurations, one is from a working run showing the expected configuration and the second from a run when the race occurs.  The major differences between the two are

- The working configuration contains the dynamic_route_configs section
- The working configuration contains dynamic_active_listeners whereas the broken configuration contains dynamic_warming_listeners

[ig.config.working.txt](https://github.com/istio/istio/files/2608896/ig.config.working.txt)
[ig.config.broken.txt](https://github.com/istio/istio/files/2608895/ig.config.broken.txt)

These are generated from 1.0.3 community images

**Comment by knrc** [comment]
PR for master: https://github.com/istio/istio/pull/10107
PR for branch 1.1: https://github.com/istio/istio/pull/10108
PR for branch 1.0: https://github.com/istio/istio/pull/10109

**Comment by hzxuzhonghu** [comment]
> While running tests on 1.0 we discovered a race between pilot's push and envoy's processing of the resources, if routes are sent before envoy is prepared to respond to them then envoy will log the following error

>>Ignoring unwatched type URL type.googleapis.com/envoy.api.v2.RouteConfiguration

>and responds with a DiscoveryRequest containing the correct nonce but the previous version.

Why envoy does not respond with DiscoveryRequest containing not nil ErrorDetail.

I see from here https://github.com/envoyproxy/data-plane-api/blob/master/XDS_PROTOCOL.md it should be `If Envoy had instead rejected configuration update X, it would reply with error_detail populated and its previous version, which in this case was the empty initial version. `

**Comment by knrc** [comment]
@hzxuzhonghu I agree this case is not included in the XDS_PROTOCOL documentation.

The response is created in the lower level mux code within the envoy server and occurs when a request arrives for a resource which currently has no handler, in our particular case this was the RouteConfiguration.  It will always return no resources irrespective of whether resources have been sent previously.

**Comment by knrc** [comment]
... and does not include an error message which may be something to address on the envoy side.  In the meantime the consequence is that the routes are never delivered to the proxy and listeners remain in "dynamic_warming_listeners" so cannot handle any requests.

**Comment by knrc** [comment]
@hzxuzhonghu I went through the history and it looks as if I can only find two failures, neither of the PRs related to this area.  From the error message being returned it would appear that the connection from the test to the pilot code has been disconnected for some reason, the EOF is being returned when the code is expecting a response.

https://github.com/istio/istio/blob/release-1.1/pilot/pkg/proxy/envoy/v2/ads_test.go#L275-L277

The line with the failure is actually before where we test for the protocol error and it's trying to ensure we have the correct initial routes setup.

**Comment by ramaraochavali** [comment]
@knrc If you think Envoy, should have populated error message and did not, can you please create an issue in Envoy github with reproducible steps?
