### ISSUE TITLE
The pilot and policy pods kept restarting 

### ISSUE THREAD

**Issue by mailzyok** [istio/istio#10110]
**Describe the bug**
The pilot and policy pods kept restarting. the critical error log

"Error initializing configuration '/etc/istio/proxy/envoy.yaml': Didn't find a registered implementation for name: 'mixer'"

**Expected behavior**
The pilot and policy pods are running

**Steps to reproduce the bug**
1. git checkout istio 1.0.3
2. change the base image from ubuntu to redhat for istio/pilot/docker/Dockerfile.proxyv2  
3. make docker, the new image for proxyv2 is built successfully.
4. using helm package under install/kubernetes/helm/istio to deploy it on minikube.
The pod cannot start due to "glibc_2.18" is required by envoy.
After searching in internet, found glibc_2.18 is not ready for rhel and centos.
5. git clone envoy 1.8.0, and build envoy using centos docker image
6. use envoy binary from step 5, and re-build the proxyv2 in step2.
7. helm upgrade the exsiting istio release, there is no glibc_2.18 error anymore, but met a new error

"Error initializing configuration '/etc/istio/proxy/envoy.yaml': Didn't find a registered implementation for name: 'mixer'"

The interesting thing is that the envoy binary(release) built by myself on step5, is very large than what istio download from https://storage.googleapis.com/istio-build/proxy/envoy-alpha-${ISTIO_ENVOY_VERSION}.tar.gz

**Version**
istio 1.0.3
envoy 1.8.0
minikube v0.30.0

**Installation**
using helm to install, no additional flag is set

**Environment**
k8s

**Cluster state**

**Comment by mailzyok** [comment]
Close it.
i should clone the istio/proxy code, not enovy. And in istio/proxy, using centos docker image to build. Then copy the envoy binary out to build a new docker image based on centos/rhel. Now all the pods starts running.

Thanks for your patience

**Comment by lurenjia528** [comment]
so,in the image proxyv2,the binary envoy should use 'istio/proxy' to build ?
