### ISSUE TITLE
istio-proxy stop before my containers

### ISSUE THREAD

**Issue by liutanrong** [istio/istio#10112]
**Describe the bug**
When I stopped a pod, I found that istio-proxt was stopped immediately, but my own container could not be stopped immediately because it was still processing transactions within the thread.This caused my own container to be unable to make network requests and was unable to transfer the container's stop signal to other services.

**Expected behavior**
I expect to be able to provide a way for the istio-proxy to stop after my own container has completely stopped.

**Steps to reproduce the bug**
1. Establish a service that takes a long time to process
2. deploy it with istio
3.stop the pod in k8s

**Version**

 istioctl version
Version: 1.0.3
GitRevision: a44d4c8bcb427db16ca4a439adfbd8d9361b8ed3
User: root@0ead81bba27d
Hub: docker.io/istio
GolangVersion: go1.10.4
BuildStatus: Clean

 kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**Installation**
with 
kubectl apply -f install/kubernetes/istio-demo.yaml

**Environment**
ubuntu 16.04

**Cluster state**

![image](https://user-images.githubusercontent.com/9637509/48934116-cf9cbf80-ef3d-11e8-87c5-b73ef48a81d2.png)

![image](https://user-images.githubusercontent.com/9637509/48934152-ee02bb00-ef3d-11e8-94dd-80617c97cf9b.png)

**Comment by hzxuzhonghu** [comment]
That's the current behavior: when SIGTERM sent to sidecar, pilot-agent got it, and then agent send SIGKILL to envoy process.

So the sequencing signal is like:   SIGTERM -->pilot-agent-->SIGKILL-->envoy. 

And currently envoy does not support graceful shutdown. xref: https://github.com/envoyproxy/envoy/issues/2920 Once envoy implements this, we can support it in sidecar.

**Comment by liutanrong** [comment]
> That's the current behavior: when SIGTERM sent to sidecar, pilot-agent got it, and then agent send SIGKILL to envoy process.
> 
> So the sequencing signal is like: SIGTERM -->pilot-agent-->SIGKILL-->envoy.
> 
> And currently envoy does not support graceful shutdown. xref: [envoyproxy/envoy#2920](https://github.com/envoyproxy/envoy/issues/2920) Once envoy implements this, we can support it in sidecar.

thanks

**Comment by liamawhite** [comment]
closing in favour of #7136
