### ISSUE TITLE
Missing entry in Grafana dashboard on Istio 1.11

### ISSUE THREAD

**Issue by nixgadget** [istio/istio#10117]
**Describe the bug**
Noticing an odd entry in the Grafana dashboard as shown in the screenshot for a given workload.
<img width="1877" alt="grafana" src="https://user-images.githubusercontent.com/2648624/48973322-b9a80f80-f0a1-11e8-9fcf-369b08a2b53b.png">

**Expected behavior**
The corresponding service for the workload

**Steps to reproduce the bug**
NA

**Version**
release-1.1-20181101-09-15

**Installation**
Helm 2.11.0

**Environment**
GKE, 1.11.2

If you require more details please let me know. Theres some sensitive stuff in the cluster so a bit hesitant to extract a dump.

**Comment by douglas-reid** [comment]
A few questions:

- what service is associated with that workload?
- what happens when that service receives traffic?
- what does the instance config look like for `requestcount` in your install?

**Comment by nixgadget** [comment]
@douglas-reid 
- To answer your first two questions its a webhook service that publishes an event to kafka.
   Traffic flows from istio ingress -> yodlee webhook service
- How do you go about checking the `requestcount` ? Some guidance is appreciated.
- Also just for my lack of understanding how is the service different from the workload ? i.e. the difference between the two columns
