### ISSUE TITLE
allow disabling installation of crds

### ISSUE THREAD

**Issue by ilackarms** [istio/istio#10122]
**Describe the feature request**
i'd like to be able to install istio without (re) installing CRDs. disabling `global.crds` has no effect because of the `or` here:
```yaml
# {{ if or .Values.global.crds (semverCompare ">=2.10.0-0" .Capabilities.TillerVersion.SemVer) }}
```

i'm not sure if this `or` needs to be here, or we can make it an `and`, because i'd like to disable installing CRDs period

**Comment by mabushey** [comment]
Use Helm template, then you have configurable yaml. Just delete the CRD's from the yaml, or move them to a separate file. Helm goes from unusable garbage to tolerable by only using template.

**Comment by booninite** [comment]
Or the maintainers of this project could make the Helm Chart template honor the description of `global.crds`?  Or remove it?  Nothing instills confidence in a production quality service mesh like the fact you can't even get it out of the garage before it breaks down on you
