### ISSUE TITLE
Jaeger traces are not kept for more than an hour

### ISSUE THREAD

**Issue by chunheisiu** [istio/istio#10124]
**Describe the bug**
Retention time of Jaeger traces is less than an hour. There are no obvious settings to configure a longer time.

**Expected behavior**
Ability to extend the retention time for traces captured by Jaeger.

**Steps to reproduce the bug**
N/A

**Version**
Istio 1.0.2, Kubernetes 1.12.1

**Installation**
Istio was installed via `helm`.

**Environment**
Ubuntu Server 18.04

**Comment by objectiser** [comment]
Jaeger installed with the helm chart is the `all-in-one` server with `in-memory` storage. To prevent the server from running out of memory, it is [configured to only retain 50000 traces](https://github.com/istio/istio/blob/master/install/kubernetes/helm/subcharts/tracing/values.yaml#L12).

Does the same Jaeger pod run for more than an hour? If it is restarting regularly it would loose previous traces.

Do you generate more than 50000 traces in an hour? If so, that would explain why the traces are no longer available after the hour.

Other option would be to use a production configuration of Jaeger, using a persistent storage (Elasticsearch or Cassandra). There is a PR #9508 to update the tracing helm chart to use the Jaeger operator, to enable the persistent storage options to be easily selected. Would be good if you could try this out and provide feedback on that PR.

**Comment by objectiser** [comment]
Jaeger installed with the helm chart is the `all-in-one` server with `in-memory` storage. To prevent the server from running out of memory, it is [configured to only retain 50000 traces](https://github.com/istio/istio/blob/master/install/kubernetes/helm/subcharts/tracing/values.yaml#L12).

Does the same Jaeger pod run for more than an hour? If it is restarting regularly it would loose previous traces.

Do you generate more than 50000 traces in an hour? If so, that would explain why the traces are no longer available after the hour.

Other option would be to use a production configuration of Jaeger, using a persistent storage (Elasticsearch or Cassandra). There is a PR #9508 to update the tracing helm chart to use the Jaeger operator, to enable the persistent storage options to be easily selected. Would be good if you could try this out and provide feedback on that PR.

**Comment by chunheisiu** [comment]
Thanks @objectiser for your advice.

I've checked the status and it seems to me that the Jaeger pod does run for more than an hour, so I believe the problem isn't caused by the pod restarting itself from time to time.

On the other hand, I am uncertain about the actual number of traces being generated. Apart from the traces between our microservices, there were other traces such as `istio-policy: Check` and `istio-telemetry: Report`, which I believe were generated by Istio itself. It would be great if there is an option to not capture those traces so that the 50,000 cap won't reach that easily.

I am currently experimenting with a production Jaeger and an existing Elasticsearch backend to mitigate the issue.

**Comment by objectiser** [comment]
@chunheisiu I was focusing on causes related to the backend - but missed the potentially obvious one - do you change the `Lookback` value on the search page in the UI? By default this is set to 1 hour.

If not changed - then can you change this to 1 day and confirm whether you see data for more than an hour.

**Comment by chunheisiu** [comment]
@objectiser Per your suggestion, I set the `Lookback` value to *Last 2 Days* and `Limit Results` to *500* but the results seem to be the same. Querying the `istio-telemetry` service did return 500 traces that I have specified, with each trace being a few seconds apart from one another. The fact that it is generating 500 `istio-telemetry` traces between 4:11:57 pm and 5:07:26 pm could explain why the cap is reached so soon.

**Comment by chunheisiu** [comment]
I have maxed out the limit to 1500 but it is still showing results within the hour. I tried setting `Min Duration` to *10ms*, but now it is showing me 1304 traces, still within the past hour.

I understand why a `50000` limit is set in the first place. Hence, I would like to experiment with an alternative approach rather than blindly raising the limit to an arbitrary larger number.

**Comment by objectiser** [comment]
For future reference, Jaeger may provide a [local storage option](https://github.com/jaegertracing/jaeger/pull/760) in the near future which could be used as an alternative to the current default in-memory approach.

**Comment by mkjoerg** [comment]
Is there any documentation available for connecting a standalone jaeger instance instead using the default one in the chart? As far as I have understood, Pilot is emitting the traces, but I couldn't find out how to configure the target jaeger instance. Does anyone know, how to configure the trace target or are there any issues with a standalone instance?

**Comment by chunheisiu** [comment]
@mkjoerg Take a look at #8893 and see if it helps.
