### ISSUE TITLE
Prod outage:  Multiple services affected (upstream connect error or disconnect/reset before headers)

### ISSUE THREAD

**Issue by Stono** [istio/istio#10126]
Hi, 
We had a production outage this morning which was resolved by restarting pilot.

We run two pilots (1.0.4, k8 1.10.7) in production and whilst trying to capture debug logs for you I noticed one of them was not responding to `127.0.0.1:8080/debug/adsz`.  I was also unable to run `istioctl proxy-status`.

I have captured:

  - discovery logs from both pilots from before, and after the restart
  - /configz /adsz and /endpointz from both pilots before and after
  - endpoints nodes pods and services for the clusters

I don't want to share these things on Github so can one of you please reach out to me on slack and I will send you a tar.gz containing the files.

**Comment by Stono** [comment]
As a temporary mitigation to this issue I'm going to add a healthcheck to pilot which curls each `debug` endpoint with a `--max-time`, and restarts pilot.  However this will then bump all connections over to the other pilot and we'll hit https://github.com/istio/istio/issues/7878, but at least it'll be "up".

**Comment by Stono** [comment]
This has just happened again on a different cluster.  One istio-pilot was failing to respond to the /adsz query.

Restarting the pilots has resolved the problem.  The infrastructure stats (cpu/ram) in this case for the bad pod in question (istio-pilot-688dc4995d-8tf9b) are quite interesting.  Basically no CPU usage at all and an ever increasing RAM count.

<img width="1591" alt="screen shot 2018-11-26 at 12 29 42" src="https://user-images.githubusercontent.com/1486729/49014215-5092cb80-f177-11e8-8e7a-ec7cb72ec9b6.png">

**Comment by Stono** [comment]
Also:
<img width="1618" alt="screen shot 2018-11-26 at 13 00 41" src="https://user-images.githubusercontent.com/1486729/49015545-4e327080-f17b-11e8-8d8b-3ba51fb5cfe6.png">

**Comment by Stono** [comment]
Hey guys, it's happened again now. 
We've had four production outages caused by this today.

<img width="1619" alt="screen shot 2018-11-26 at 16 41 56" src="https://user-images.githubusercontent.com/1486729/49028416-42a27200-f19a-11e8-981f-8bae266fdfbc.png">

**Comment by Stono** [comment]
We've had to add this to istio-pilot as a temporary mitigation:
```
        livenessProbe:
          exec:
            command:
            - curl
            - --output 
            - /dev/null 
            - --silent
            - http://127.0.0.1:8080/debug/adsz
```

**Comment by Stono** [comment]
It's worth nothing that this was not a problem with 1.0.2, and only seems to have started since 1.0.3 and incremental EDS

**Comment by Stono** [comment]
@costinm @mandarjog could you advise if it is safe to just revert pilot to `1.0.2` without any other changes? (eg leave all sidecars/mixer etc on `1.0.4`)

**Comment by costinm** [comment]
Yes, the sidecars are backward compatible, so is mixer, etc.
Technically we can also disable just incremental EDS - but safer to just move pilot back to 1.0.2

**Comment by Stono** [comment]
For others reading this, `PILOT_DIRECT_EDS=0` on the istio-pilot pod also disables the EDS incremental update (this issue)

**Comment by Stono** [comment]
OK this doesn't appear to be just an EDS issue.
With `PILOT_DIRECT_EDS=0`, it just happened again:

<img width="471" alt="screen shot 2018-11-27 at 13 30 59" src="https://user-images.githubusercontent.com/1486729/49084947-c9158d00-f248-11e8-90ba-f087355212e3.png">

**Comment by costinm** [comment]
That's very interesting - also the logs seem to suggest incremental EDS is sending data as expected.
To be clear: the env variable should bypass the incremental sending and updates, so it's unlikely the leak is related to actual incremental part. 

Looking at the goroutines graph - and the number of sidecars I'm more and more suspecting something related with the close connections or reconnect. It appears every 5 minutes you add ~400 goroutines, 
and we happen to use 2 per connection (plus 1 for grpc layer). It would be really great to get logs from istio-proxy in front of pilot and in front of a sidecar, and maybe a "netstat -a" in the pilot container. And of course a /debug/pprof.

**Comment by Stono** [comment]
Here are some stats from this cluster:
```
# HELP ipe_pilot_push_duration Full push duration
# TYPE ipe_pilot_push_duration gauge
ipe_pilot_push_duration{pilot="istio-pilot-7bc767db9-g7jc2",start="1543356826160",end="1543356837972"} 11812
ipe_pilot_push_duration{pilot="istio-pilot-7bc767db9-ndkfg",start="1543356826160",end="1543356838944"} 12784

# HELP ipe_pilot_proxy_imbalanced A gauge which represents if the proxies to pilots ratio is imbalanced
# TYPE ipe_pilot_proxy_imbalanced gauge
ipe_pilot_proxy_imbalanced{pilot="istio-pilot-7bc767db9-ndkfg",proxies_connected="122",percentage_target="50",percentage_connected="55.96330275229357"} 0
ipe_pilot_proxy_imbalanced{pilot="istio-pilot-7bc767db9-g7jc2",proxies_connected="96",percentage_target="50",percentage_connected="44.03669724770643"} 0
```

So 218ish proxies

**Comment by costinm** [comment]
I looked at the close and connect (`grep terminated discovery.stdout.log` and `grep ADS:CDS discovery.stdout.log`) - both show similar and expected numbers, and the close seems to happen. 

Only strange thing is that the 127.0.0.1:PORT seems to be used by multiple concurrent ADS connections - it appears 12 TCP connections are used for ~80 sidecars, but doesn't seem to leak.
It may not be a close/connections-related goroutine.

**Comment by hzxuzhonghu** [comment]
@costinm Whatever I think first should add keepalive for grpc server.

**Comment by Stono** [comment]
OK good news it happened again and I've captured logs *including* thread dumps, at 1 minute intervals for 3 minutes.

istio-pilot-cc5d77d79-6hbhr is the bad proxy in these logs.  PM me on slack and I'll send them over.

**Comment by Stono** [comment]
Seeing some really weird errors as well today:

istioctl proxy-status showing:
```
vds-dvla-importer-9767b7d96-w9tqx.vds-dvla-importer                                              SYNCED     SYNCED     SYNCED (100%)     SYNCED     istio-pilot-7985bbc97c-wptgh     1.0.2
vds-dvla-importer-9767b7d96-xl6dc.vds-dvla-importer                                              STALE      STALE      STALE (100%)      STALE      istio-pilot-7985bbc97c-wptgh     1.0.2
```

So a stale pod that actually no longer even exists in the cluster?
```❯ k -n vds-dvla-importer get pods
NAME                                READY     STATUS    RESTARTS   AGE
vds-dvla-importer-9767b7d96-w9tqx   2/2       Running   0          10m
```

**Comment by costinm** [comment]
https://github.com/istio/istio/pull/10177

**Comment by costinm** [comment]
Workaround: don't use istioctl proxy-status in 1.0.4

**Comment by Stono** [comment]
I'm gonna close this as 1.0.5 is out now which contains the fix!
