### ISSUE TITLE
Unable to finalize the release 0.2.7

### ISSUE THREAD

**Issue by linsun** [istio/istio#1015]
Onto the last step:

TAR=gtar CP=gcp  githubctl --token_file=/Users/linsun/.git/istio-token \
    --op=uploadArtifacts --base_branch=master --next_release=0.2.7

i've got gtar and gcp installed, failed at this error, even tho the release archives are created in /tmp/release/archives dir.  But it seems to fail at uploading to git.

  ```adding: istio-0.2.7/samples/sleep/README.md (deflated 47%)
  adding: istio-0.2.7/samples/sleep/sleep.yaml (deflated 54%)
~/go/src/istio.io/test-infra/istio
Archives are available in /tmp/release/archives
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x133147b]

goroutine 1 [running]:
istio.io/test-infra/toolbox/util.GithubClient.CreateReleaseUploadArchives(0xc4200a2900, 0x141660f, 0x5, 0xc4200190e0, 0x28, 0x141660f, 0x5, 0xc420186370, 0x5, 0x141c5c4, ...)
	toolbox/util/githubClient.go:338 +0x10b
main.CreateIstioReleaseUploadArtifacts.func1(0xc400000010, 0x142a978)
	toolbox/githubctl/main.go:206 +0xea
main.cloneIstioMakePR(0xc42013c500, 0x15, 0xc4201a65d0, 0x2e, 0xc42013c540, 0x1f, 0xc42013c560, 0x0, 0x0)
	toolbox/githubctl/main.go:154 +0x19f
main.CreateIstioReleaseUploadArtifacts(0x7fff5fbff3d8, 0xf)
	toolbox/githubctl/main.go:220 +0x261
main.main()
	toolbox/githubctl/main.go:248 +0x124```

I'm on Mac OS 10.12.4 (Sierra).

**Comment by linsun** [comment]
i think we are getting nil on this:

	release := github.RepositoryRelease{TagName: &releaseTag}

**Comment by chxchx** [comment]
https://github.com/istio/test-infra/blob/master/toolbox/util/githubClient.go#L338

Line 338 of `githubClient.go` is a comment. Perhaps try again using the latest master?

**Comment by sebastienvas** [comment]
Which sha of test infra did you run that from ? For some reason the line number don't match.

**Comment by sebastienvas** [comment]
I was not able to reproduce this on linux, @chxchx could you try to reproduce this on mac, in your repo ?

**Comment by sebastienvas** [comment]
--next_release=0.2.7 is wrong, you shuld have used  --next_release=0.2.8

**Comment by linsun** [comment]
yes, that must be it, even tho i can't validate it as you already run that step @sebastienvas

**Comment by jasminejaksic** [comment]
Lin, can we close this issue now? If not, what's still pending?

**Comment by linsun** [comment]
Added more clarification steps for this in the release engineer doc page.  closing it for now.
