### ISSUE TITLE
Unable to set per-request timeout override

### ISSUE THREAD

**Issue by Stono** [istio/istio#10153]
As per https://istio.io/docs/tasks/traffic-management/request-timeouts/ - I should be able to override the request timeout by specifying `x-envoy-upstream-rq-timeout-ms`, however as you can see that doesn't seem to work:

```
time ./test.sh
* About to connect() to app.search-one port 80 (#0)
*   Trying 10.192.75.41...
* Connected to app.search-one (10.192.75.41) port 80 (#0)
> PUT /forge/v1/copy-data HTTP/1.1
> User-Agent: curl/7.29.0
> Host: app.search-one
> Accept: */*
> x-envoy-upstream-rq-timeout-ms: 0
> Content-Type: Application/json
> Content-Length: 224
>
* upload completely sent off: 224 out of 224 bytes
* The requested URL returned error: 504 Gateway Timeout
* Closing connection 0
curl: (22) The requested URL returned error: 504 Gateway Timeout

real    0m10.012s
user    0m0.003s
sys     0m0.006s
```

The virtualservice is:
```
❯ k get virtualservice -o yaml
apiVersion: v1
items:
- apiVersion: networking.istio.io/v1alpha3
  kind: VirtualService
  metadata:
    name: search-one
    namespace: search-one
  spec:
    hosts:
    - app
    http:
    - route:
      - destination:
          host: app
        weight: 100
      timeout: 10s
```

**Comment by frankbu** [comment]
I'm wondering if the timeout in the VirtualService is taking precedence over the header. Have you tried only setting the header without also having a timeout in the VirtualService?

**Comment by Stono** [comment]
@frankbu aye that works, we've used `x-envoy-upstream-rq-timeout-ms` before to override the default envoy timeout so your hypothesis could be correct.

**Comment by frankbu** [comment]
So I guess it's working as designed. It makes sense that the VirtualService config takes precedence since that's what Istio is all about: operator control of traffic flow without touching the application code. I think we just need to document this better, since the current doc seems to imply that the header will override.

**Comment by Stono** [comment]
Working as designed but completely contradictory to the documentation?  I think having the ability to override some things on a per request basis makes absolute sense.

This particular service serves user request which we do want to time out without a reasonable time frame, but we have some internal service requests which are long running by design.  Enforcing a one size fits all doesn't really work.

An operator only design would need the ability to specify traffic flow options based on the source workload too.

**Comment by frankbu** [comment]
Yes, I agree that the documentation is wrong and needs to be fixed.

Operators do have the ability to specify traffic flow options based on the source workload. You could do the above experiment with both timeouts in the VirtualService:

```
  spec:
    hosts:
    - app
    http:
    - match:
      sourceLabels:
        app: sourceApp
      route:
      - destination:
          host: app
      timeout: 0
    - route:
      - destination:
          host: app
      timeout: 10s
```

That said, if you feel strongly that the headers should be able to override, you need to start a design discussion.

**Comment by Stono** [comment]
I was not aware of that, will give it a go. Thanks

I do still think per request overrides would allow further flexibility but not enough to start a design doc about it considering there is source workload support.

**Comment by Stono** [comment]
@frankbu it doesn't work with VirtualServices either:

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  clusterName: ""
  creationTimestamp: 2018-11-27T11:41:26Z
  generation: 1
  labels:
    app: search-one
    group: delivery-platform
    heritage: Tiller
    release: search-one
  name: search-one
  namespace: search-one
  resourceVersion: "67025636"
  selfLink: /apis/networking.istio.io/v1alpha3/namespaces/search-one/virtualservices/search-one
  uid: 5fa17f46-f239-11e8-98e9-42010aa401b8
spec:
  hosts:
  - app
  - app.search-one.dev.k8.atcloud.io
  - admin.search-one.dev.k8.atcloud.io
  http:
  - appendHeaders:
      x-envoy-max-retries: "10"
      x-envoy-retry-on: gateway-error,connect-failure,refused-stream
    route:
    - destination:
        host: app
      weight: 100
    timeout: 20s
  - appendHeaders:
      x-envoy-max-retries: "10"
      x-envoy-retry-on: gateway-error,connect-failure,refused-stream
    match:
    - sourceLabels:
        app: helm-search-solr-jobs
    route:
    - destination:
        host: app
      weight: 100
    timeout: 600s
```

Here is the pod definition:
```
❯ k get pod import-data-88rcp -o yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    sidecar.istio.io/inject: "true"
    sidecar.istio.io/status: '{"version":"1c567af41923bd774a628fc5bb49432f662388eeb7f18e0f45863b24c6584f20","initContainers":["istio-init"],"containers":["istio-proxy"],"volumes":["istio-envoy","istio-certs"],"imagePullSecrets":null}'
  creationTimestamp: 2018-11-30T10:36:52Z
  generateName: import-data-
  labels:
    app: helm-search-solr-jobs
.... etc
```

Here it is timing out at 10s again:
```
* About to connect() to app.search-one port 80 (#0)
*   Trying 10.192.75.41...
* Connected to app.search-one (10.192.75.41) port 80 (#0)
* Server auth using Basic with user 'backup'
> PUT /forge/v1/copy-data HTTP/1.1
> User-Agent: curl/7.29.0
> Host: app.search-one
> Accept: */*
> x-envoy-upstream-rq-timeout-ms: 0
> x-envoy-upstream-rq-per-try-timeout-ms: 0
> Content-Type: Application/json
> Content-Length: 194
>
* upload completely sent off: 194 out of 194 bytes
< HTTP/1.1 504 Gateway Timeout
< content-length: 24
< content-type: text/plain
< date: Fri, 30 Nov 2018 10:39:57 GMT
< server: envoy
<
* Connection #0 to host app.search-one left intact
upstream request timeout
real	0m10.011s
user	0m0.000s
sys	0m0.007s
```

Could this be because sourceLabels is read from a service definition, and in this case this a `Job` which is running, which is ultimately not represented by a service/workload?

In that case; we'd really need per request overrides (for non-workload related stuff).

**Comment by frankbu** [comment]
One problem is that rules in the VirtualService are order dependent, so you need to put the one with the sourceLabels first.

https://istio.io/docs/concepts/traffic-management/#precedence

That said, I would have expected the timeout to be 20s (since that's what the timeout is in the VirtualSevice rule, but you are just getting 10s in your experiment, which implies the VirtualService isn't coming into play at all. So the question is why is the VirtualService not being invoked for your call. What host name are you calling?

Also, I notice you are trying to append an `x-envoy-max-retries` header. That seems dubious to me too, since you are asking to append a header to the outgoing request, but the header you are appending is one that is supposed to affect the outgoing request. I may be wrong, but I think it's unlikely that it will affect that request.

**Comment by Stono** [comment]
@frankbu The 20s did kick in eventually, I didn't wait long enough for my change to be propagated to proxies.  So you can ignore that as a red herring.

However, I believe arrays in yaml/json like this aren't ordered lists, so probably shouldn't be considered as such?  I have been burned before, by several golang projects ([helmfile as an example](https://github.com/roboll/helmfile/issues/137)) which do not honour the order of yaml arrays when loaded.

The usual approach is to have a weighting or similar, to have an explicit precedence.  I took the view that it would be on a "most matched" approach, eg the rule which matched the label would be used as it's more specific in its match criteria.   Obviously that didn't work, so then I did try the reverse order to and also that did not work.

Can you confirm how istio interrogates `sourceLables`?  I would presumed they're labels associated to a cluster rather than pod label annotations, and as this `Job` is not part of a service or a cluster, it doesn't have any labels (even though it is annotated with them?).

**Comment by frankbu** [comment]
It's based on pod labels, so as far as I can tell, your rule should work.

Btw, you could try putting the timeout in a rule with a `match: headers:` instead, if you can't figure out the source labels problem. That way you give the control to the request code, independent of source pod.

https://istio.io/docs/concepts/traffic-management/#conditional-rules

**Comment by jaygorrell** [comment]
I'm seeing similar to this, but without any timeouts defined in my `VirutalService`. Here's the relevant cluster config that does show a timeout of 0:
![image](https://user-images.githubusercontent.com/12174604/59624089-dff7d000-9103-11e9-8b37-c731f1febc08.png)

I do have `VirtualService`s defined, which just have the following:
```
spec:
  hosts:
  - route-happy-service
  http:
  - retries:
      attempts: 3
      retryOn: gateway-error
    route:
    - destination:
        host: route-happy-service
```

However, when making a call to this service using `--header 'x-envoy-expected-rq-timeout-ms: 100'`, I'm getting responses that take multiple seconds back. Similarly putting even lower values have no impact... it always goes as long as needed.

Seems like a similar issue as this one.

**Comment by jaygorrell** [comment]
New issue for the above: https://github.com/istio/istio/issues/14923
