### ISSUE TITLE
Refactor Endpoints

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#10160]
We have `IstioEndpoint` `NetworkEndpoint`,and this makes a mess in control plane. In the long run, this can lead to misuse for developers.  So we should get rid of one type.  
AFAIK,  `IstioEndpoint` is designed to replace `NetworkEndpoint`, so we can remove `NetworkEndpoint` totally.

**Comment by costinm** [comment]
Yes, NetworkEndpoint needs to be removed - but can wait until 1.2, we can't afford more instability, only critical fixes in 1.1.

**Comment by costinm** [comment]
Also: doing changes in master now will make it harder to merge, so I think this or similar refactor changes should wait until 1.1 is firmly out - and people should focus on 1.1, no need to get distracted.

**Comment by hzxuzhonghu** [comment]
It's 1.2 now

**Comment by fpesce** [comment]
@costinm any update on this? Is this about refactoring/renaming NetworkEndpoint in the code? It seems like IstioEndpoint is the easiest to remove (from a quick grep), should we consider that bug to Nebulous future instead of 1.2 (freeze is coming soon).

**Comment by howardjohn** [comment]
We should probably still do some refactoring, but we need to be aware of ServiceEntry, EndpointSlice as well -- there will soon be at least 5 representations of an Endpoint

**Comment by howardjohn** [comment]
https://github.com/istio/istio/pull/19497
