### ISSUE TITLE
Missing v1.0.4 release notes

### ISSUE THREAD

**Issue by chrisob** [istio/istio#10172]
**Describe the bug**
Release notes at https://istio.io/about/notes/1.0.4.html are missing, even though there is [a (broken) link to them on istio's GH releases page](https://github.com/istio/istio/releases/tag/1.0.4).  

Previous releases have notes with the expected URL format:
- https://istio.io/about/notes/1.0.3.html
- https://istio.io/about/notes/1.0.2.html
- https://istio.io/about/notes/1.0.1.html
- https://istio.io/about/notes/1.0.html

**Expected behavior**
https://istio.io/about/notes/1.0.4.html exists and contains notable changes/fixes since `v1.0.3`.

**Steps to reproduce the bug**
Visit https://istio.io/about/notes/1.0.4.html.

**Comment by geeknoid** [comment]
Mandar's been working on these in https://github.com/istio/istio.io/pull/2910

**Comment by chrisob** [comment]
Cool, looks like it's up now, thanks!
