### ISSUE TITLE
telemetry for ServiceEntry requests has wrong destination_service_namespace

### ISSUE THREAD

**Issue by jmazzitelli** [istio/istio#10174]
**Describe the feature request**

Access to a ServiceEntry endpoint results in telemetry stored in Prometheus where the destination_service_namespace is (apparently) hardcoded to "default".

"default" is a real namespace - in fact, it's the name of the most commonly used namespace in k8s - but obviously is not where the Service Entry endpoint really lives. So this telemetry is actually providing incorrect data.

It seems wrong (and in fact will produce wrong visualizations) to say a request to a destination of a Service Entry (either MESH_EXTERNAL or MESH_INTERNAL) was in the namespace of "default".

Instead, I would like to see all telemetry timeseries for requests to a Service Entry endpoint to have destination_service_namespace set to some string that represents a "non-namespace". So, for example, real namespaces can't have underscores in them, so perhaps set destination_service_namespace to "\_\_serviceentry\_\_" or "\_external" or something like that.

I am not even sure setting it to "unknown" is correct - it's not that it's in some unknown namespace - it is in NO namespace. But, that said, "unknown" is better than "default" - anything but "default" is better.

**Describe alternatives you've considered**

There is no alternative - the destination_service_namespace defines where a service is - it is wrong to say a Service Entry service is in the mesh's "default" namespace - it is not. The telemetry is just wrong in this case. It quite possibly is external to the cluster itself, let alone inside a namespace found in the mesh.

**Additional context**

Kiali is going to visualize these destinations in its graphs - to say a "destination_service" (whose name is a Service Entry host) is in the "destination_service_namespace" of "default" (as seen in the telemetry stored in Prometheus) is incorrect and confusing.

**Comment by jmazzitelli** [comment]
Just quickly looking, I *think* this could be a single line change - changing the value of this constant from "default" to something else like "\_\_external\_\_":

https://github.com/istio/istio/blob/1.1.0-snapshot.3/pilot/pkg/model/service.go#L110

Otherwise, I think the places where this default string is used when creating Service objects for a Service Entry are here (again, not 100% sure - I think more spots might be needed to change):

3 instances here: https://github.com/istio/istio/blob/1.1.0-snapshot.3/pilot/pkg/serviceregistry/external/conversion.go#L71-L99

and 2 instances here: 
https://github.com/istio/istio/blob/1.1.0-snapshot.3/pilot/pkg/serviceregistry/consul/conversion.go#L99
https://github.com/istio/istio/blob/1.1.0-snapshot.3/pilot/pkg/serviceregistry/consul/conversion.go#L139

**Comment by kyessenov** [comment]
Agree, that unsetting the value of namespace to "" is reasonable. The entries are cluster-scoped if I understand it correctly. So assigning them to a namespace seems to not be consistent with read/write access to service entries.

**Comment by douglas-reid** [comment]
Added this as a topic for the next P&T WG meeting.

**Comment by jmazzitelli** [comment]
as an example of where this comes into play, see this KIALI JIRA issue: https://issues.jboss.org/browse/KIALI-2026

**Comment by howardjohn** [comment]
In telemetry v2 this is now "unknown" which seems intentional - is there anything to do here?

**Comment by douglas-reid** [comment]
@bianpengyuan do you recall if the `"unknown"` here was an intentional change, or a result of the logic in `stats` that sets `""` to `"unknown"` ?

**Comment by bianpengyuan** [comment]
@douglas-reid the latter. I cannot remember if there was any conclusion on this from meeting, but IMHO `unknown` should be good enough. Otherwise we will need to denote cluster generated from service entry and fill destination namespace based on that.

**Comment by howardjohn** [comment]
Based on the above I think this is now working as intended
