### ISSUE TITLE
TestTcpMetrics fails after merging release-1.1 to master

### ISSUE THREAD

**Issue by hklai** [istio/istio#10216]
TestTcpMetrics started failing after merging release-1.1 to master. See https://github.com/istio/istio/pull/10186

Circle:
https://circleci.com/gh/istio/istio/259212?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Prow:
https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/10186/e2e-mixer-no_auth/8869

**Comment by douglas-reid** [comment]
PR #10218 hopefully fixes.

**Comment by douglas-reid** [comment]
Marking as fixed.
