### ISSUE TITLE
istio-proxy AccessLog bad format - missing space

### ISSUE THREAD

**Issue by jsw** [istio/istio#10214]
**Describe the bug**
istio-proxy AccessLog format missing a space

`GET /k8sHTTP/1.1`

**Expected behavior**
`GET /k8s HTTP/1.1`

**Steps to reproduce the bug**
view istio-proxy stdout

**Version**
1.0.3
1.0.4

**Installation**
helm

**Environment**
GKE 1.11

**Comment by douglas-reid** [comment]
This was reported in a different context, iirc. @qiwzhang any thoughts on the formatting here?  iirc, this may be being set via Pilot too...
