### ISSUE TITLE
Configure EnvoyFilter on istio ingress-gateway

### ISSUE THREAD

**Issue by adityats2020** [istio/istio#10223]
**Describe the feature request**
The docs (https://istio.io/docs/reference/config/istio.networking.v1alpha3/#EnvoyFilter) are not clear if the envoy filter can be configured for istio ingress gateway, which are also envoy instances. The configuration seems to be applied on side car proxies only by the docs provided. I would like to avoid the extra hop if possible to have istio ingress gateway call the filter, instead of routing request to sidecar and then calling the filter. Is there a way to configure this?

**Describe alternatives you've considered**
I am able to configure EnvoyFilter using the doc provided, but only at the sidecar.

**Comment by hzxuzhonghu** [comment]
Why do you think so? No doc saying that.

**Comment by adityats2020** [comment]
Yes, the Doc doesn't say that. However, the filter doesn't get invoked unless I remove the app label.
If I change, `listenerType: SIDECAR_INBOUND` to `listenerType: GATEWAY` the filter does not get invoked unless I remove the workloadLabels that I had for SIDECAR_INBOUND listenerType filter.
```
  workloadLabels:
    app: httpbin-tls
```
