### ISSUE TITLE
Two many TIME_WAIT sockets caused by Pilot Consul registry

### ISSUE THREAD

**Issue by zhaohuabing** [istio/istio#10227]
**Describe the bug**
Consul registry is pulling services and service instances from consul server everytime receiving a discovery request, without any cache.

The pulling is using Consul Rest API, in my test environment (about 300 services),  this behaviour causes a lot of short-lived TCP connections and many TIME_WAIT sockets. The server can't accept incoming requests after a short while.

**Expected behavior**
We should cache services and service instances in Pilot and watch consul for update.

**Steps to reproduce the bug**
Install Istio with consul, register about 300 services in consul. 

**Version**
1.0.0
the latest master branch has the same issue.

**Installation**
Consul

**Environment**
Ubuntu 16.04

**Cluster state**
Not running on kubernetes.

**Comment by GregHanson** [comment]
@zhaohuabing how does this perform with release-1.1 branch? Or the latest release snapshot `1.1.0-snapshot.3`?  Master does not the latest code.  I wonder how much of the incremental EDS work done for 1.1 will impact/improve this.

**Comment by zhaohuabing** [comment]
@GregHanson I haven't tried 1.1.0 yet. I went through the codes, the TIME_WAIT sockets are mostly due to the implementation of the consul registry.
1. No cache, so consul controller have to call Consul REST API to get the Services and Service instances every time for an xDS request.
2. Pilot call  Consul REST API to get all the  Services and Service instances and compare them with the previous result every 2 seconds, which also cause high CPU use.
