### ISSUE TITLE
Use alpine for BookInfo images where possible

### ISSUE THREAD

**Issue by ijsnellf** [istio/istio#1023]
The BookInfo images could be a smaller (base image size ~20mb vs ~80mb) if we used alpine where possible.

**Comment by ijsnellf** [comment]
Follow on to https://github.com/istio/istio/issues/1002

**Comment by sakshigoel12** [comment]
@ijsnellf can this be closed now?

**Comment by ijsnellf** [comment]
Yep, it isn't important and it sounds like it would not actually help unless we have an Alpine build of Envoy + Istio Pilot. Closing...
