### ISSUE TITLE
the http is changed to https when the url reuqest is forwarded by istio ingressgateway envoy proxy 

### ISSUE THREAD

**Issue by SundayCloud** [istio/istio#10235]
**Describe the bug**

1) when I send a http request On the browser，and  istio ingressgateway forward the request , but the service receive a https request by checking the log, the request protocol has been changed

2) And the strange thing is that，when I send a https request On the browser，and  istio ingressgateway forward the request , but the service receive a http request by checking the log, the request protocol has been changed

3) if I send a request ,and the request arrive the target service by not the istio envoy proxy, I find that the request protocol won't be changed 

4) so I suspect that the url protocol is changed when the request is forwarded by the istio envoy proxy

**Expected behavior**
when I send a http request, I expcet to  receive the http request ,not the https

**Version**
{{ What version of Istio and Kubernetes are you using? Use `istioctl version` and `kubectl version` }}
[root]# istioctl version
Version: 1.0.2
GitRevision: d639408fded355fb906ef2a1f9e8ffddc24c3d64
User: root@66ce69d4a51e
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean

**Installation**
install by helm 

**Environment**
[root]# cat /etc/centos-release
CentOS Linux release 7.5.1804 (Core)

[root]# kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by hzxuzhonghu** [comment]
Check if you deploy istio with mTLS enabled.

**Comment by SundayCloud** [comment]
> Check if you deploy istio with mTLS enabled.

I have removed the https gateway 443 port, and and the strange thing is that，when I send a https request On the browser，and istio ingressgateway forward the request , but the service receive a http request by checking the log, the request protocol has been changed

**Comment by hzxuzhonghu** [comment]
Would you mind pasting your configs?

**Comment by SundayCloud** [comment]
> Would you mind pasting your configs?
I check the ingressgateway envoy config and I haven't found the point that the envoy  change the the protocol of request header.
I have a test, if the url request route won't pass by the istio envoy, and the service receive the correct protocol

this is the config info ,please check  it ,thanks.
[config.zip](https://github.com/istio/istio/files/2638517/config.zip)

**Comment by vadimeisenbergibm** [comment]
The solution and the problem are probably described in https://github.com/istio/istio/issues/10062#issuecomment-441575769
