### ISSUE TITLE
Pilot wrongly reports endpoint_no_pod after 1.0.4 upgrade

### ISSUE THREAD

**Issue by arnecls** [istio/istio#10244]
**Describe the bug**
After an update from istio 1.0.2 to 1.0.4 pilot (`curl http://istio-pilot.istio-system:8080/debug/push_status`) reported a lot of `endpoint_no_pod` errors.
However the reported services were definitely having pods attached that were healthy and ready.
Using `istioctl deregister` did not help as it was reporting `Could not find ip %s in svc %s endpoints [...]`.

- Restarting pilot did not clear the errors (is there a persistent cache somewhere?).
- Redeploying the affected services and pods did not clear the errors
- removing istio via `kubectl delete` and installing it again via `kubectl apply` cleared all errors

**Expected behavior**

- An upgrade should not break service connectivity
- If there is a cache there should be a way to clear it

**Steps to reproduce the bug**

Install istio 1.0.2 via `kubectl apply`
Upgrade to istio 1.0.4, by applying the CRDs first, followed by another `kubectl apply`.
Sidecars were not updated at first.

We saw a number of issues happen after this, i.e. a lot of services being reported as not ready and returning 503s. We used `istioctl proxy-status` (before we saw that it causes deadlocks), which reported a sync-status of 98% for all pods still having the 1.0.2 sidcar. After restarting pilot, sync got up to a 100% again. We then redeployed all pods to upgrade the sidecar.
As this did still not resolve all problems we checked `curl http://istio-pilot.istio-system:8080/debug/push_status` which lead us to this issue.

**Version**
istio 1.0.4
kubernetes 1.11.2-gke.18

**Installation**
Via rendered helm manifest and `kubectl apply`

**Environment**
GKE

**Comment by hzxuzhonghu** [comment]
duplicate with #10116
