### ISSUE TITLE
Config consistency for MCP client 

### ISSUE THREAD

**Issue by costinm** [istio/istio#10253]
Pretty much all istio components load certificates from /etc/certs, and don't require an explicit flag to configure this.

pkg/mcp/creds/watcher.go uses /etc/istio/certs and the templates have explicit flags.

Can we simplify this ? If there is some cases to not use normal certs it's fine to keep the flag in the code, but not in the helm templates.

**Comment by costinm** [comment]
Ping.

**Comment by costinm** [comment]
No other Istio config has those flags - why special needs do you have in Galley ? Long term I would expect we'll need to integrate with SDS and CNI auth, etc - and the behavior should be to detect the cert source. 

And of course using a different location and config is also bad - I filed a separate bug for the ACL config which is also galley-only.

**Comment by ozevren** [comment]
I'd rather have the flag with the default.  Running the component locally is a pain otherwise.

**Comment by costinm** [comment]
Yes, flag with default is all good - but please don't have the flag with the same default value in the helm installer. 

And if we go with a flag for the certs - I would rather have a consistent solution. Maybe customize the base directory only ( instead of /etc/certs ) and add this to values.global. 
It'll be great to also include this for injector and all other components.

Well - if value is not /etc/certs it should end up in an ISTIO_META env, and pilot should use it to adjust the generated config.

**Comment by costinm** [comment]
Actually - the common problem for running locally, or in custom environments ( mesh expansion in particular) is to have a way to customize all istio hardcoded paths, maybe an ISTIO_BASE  ( I think we have an env variable set on /var/lib/istio/sidecar.env in mesh expansion and in some scripts ?).

We have files all over the place ( etc, var ) - the mess might be ok in k8s, but it's pretty bad on local machine /mesh expansion.

**Comment by ozevren** [comment]
I am not sure how much we need to care about backward compatibility, but a common set of flags (or env variables) makes a lot of sense to me.

If there was no backward compat problem, I'd much rather have a single flag, such as -istioBase or other, and have everything else there explicitly laid out. (i.e. <istioBase>/meshconfig.yaml, <istioBase>/certs etc.)

**Comment by ozevren** [comment]
Fix is in checkin queue.
