### ISSUE TITLE
High istio-proxy CPU 

### ISSUE THREAD

**Issue by Stono** [istio/istio#10279]
Hi, 
I'm seeing quite high istio-proxy CPU on one of our applications when under load.  As you can see here, istio-proxy floats around 0.5 cores with the app using 1.5cores, this is under a load of approx 125-150 ops/sec.

<img width="805" alt="screenshot 2018-12-04 at 21 31 47" src="https://user-images.githubusercontent.com/1486729/49474246-1d51db80-f80c-11e8-98b4-425546e8d1fc.png">

This particular application is receiving small PUT requests, then making larger JSON PUT requests to another service (which does not have istio-proxy, is not in the mesh - just a normal k8s service), so:

`[ service a | proxy a ] - PUT -> [ service b | proxy b ] - PUT -> [ service c ]`

`proxy a` -> `proxy b` is mTLS.  
`proxy-a` is showing about 1/4 the cpu usage of b.

I'm not really sure how to go about debugging high proxy CPU usage under these scenarios (as we don't see it cluster wide) to help give you more debug information.  Any pointers would be welcome as I appreciate getting to a resolution from this issue's current information is near on impossible.

Does `istio-proxy` have any timings that can be exposed?

Istio 1.0.4, btw.

**Comment by Stono** [comment]
Would still love a bit of support with this one, at times on one particular service istio proxy uses more cpu than the app!

**Comment by Stono** [comment]
Not stale!  Still have this with 1.1.0 and would love understand why the high CPU usage.  Seems to defiantly correlate to the size of the requests/responses so i'm still thinking this is encryption overhead/mtls perhaps?

**Comment by Stono** [comment]
Is there anyone in perf/scalability that can comment?

**Comment by Stono** [comment]
You can see here on nginx, istio-proxy uses more CPU than nginx itself?
<img width="802" alt="Screenshot 2019-04-04 at 12 08 13" src="https://user-images.githubusercontent.com/1486729/55551283-5de63680-56d2-11e9-8db5-c3a128a7fb05.png">

**Comment by howardjohn** [comment]
@Stono sorry it looks like this one went under the radar, what is the state of this? Are you still seeing this problem or did you ever find the cause?

**Comment by Stono** [comment]
@howardjohn - still seeing it, here's nginx a couple of hours ago (1.1.7):

<img width="792" alt="Screenshot 2019-06-04 at 18 13 09" src="https://user-images.githubusercontent.com/1486729/58899280-708de380-86f4-11e9-9333-b17e277cadd5.png">

Here's another one where istio-proxy is about 1/3rd the cpu usage:
<img width="796" alt="Screenshot 2019-06-04 at 18 13 40" src="https://user-images.githubusercontent.com/1486729/58899316-86030d80-86f4-11e9-99c3-0dc529bf0074.png">

Another where it's about half:
<img width="786" alt="Screenshot 2019-06-04 at 18 14 17" src="https://user-images.githubusercontent.com/1486729/58899347-96b38380-86f4-11e9-9b51-523bde880dc0.png">

Another:
<img width="786" alt="Screenshot 2019-06-04 at 18 14 17" src="https://user-images.githubusercontent.com/1486729/58899361-a632cc80-86f4-11e9-8437-5b0ff48eb89b.png">

It just seems a bit __too high__? and it's quite an overhead/tax so I'd really like to understand why.

**Comment by harshal-shah** [comment]
We are also seeing something similar where for 250RPS, There are 6-7 pods of which only 2-3 are such that their envoy proxy consumes 1CPU while others have CPU consumption of about 350m

Following is the example of a pod with istio-proxy consuming high CPU: 

![image](https://user-images.githubusercontent.com/16479600/65635991-ad525300-dfe1-11e9-810d-754fdfb935e0.png)

Whereas below is the normal scenario. Both pods belong to the same deployment so it is confusing as to why this happens on some pods of a deployment and not all. 
![image](https://user-images.githubusercontent.com/16479600/65636112-f5717580-dfe1-11e9-9e5b-cebfb0b5b67b.png)

We have seen this happen over past few days with multiple updates being done to the deployments so this is not a one-off case.

**Comment by hzxuzhonghu** [comment]
Are the load well balanced?

**Comment by harshal-shah** [comment]
Yes the load is well balanced

**Comment by Stono** [comment]
That looks like a different issue to my original one, so I would perhaps suggest a separate issue?
Mine have even load, i'm purely wanting to understand how to profile the proxy cpu as it's consistently high across all my pods.

**Comment by harshal-shah** [comment]
I would like to learn more about profiling proxy CPU as well. Our problem mentioned above was mitigated by changing the proxy version from 1.3.0 to 1.2.5

**Comment by Stono** [comment]
Hmm, that's slightly worrying as we're about to go to `1.3.0` in production.  

@duderino - have you had any other reports of imbalanced load on 1.3.0, could this be in relation to locality aware routing that's on by default in 1.3.0?

@harshal-shah - I'd suggest raising a separate issue to discuss your load balancing in 1.3.x+

**Comment by howardjohn** [comment]
@harshal-shah interesting that you have the same problem in https://github.com/istio/istio/issues/17383, but the solution in that issue was turning off a pilot feature, while your solution was rolling back just the proxy..

**Comment by joncak** [comment]
This issue could be related to https://discuss.istio.io/t/istio-sidecar-consuming-high-cpu/3894/21
