### ISSUE TITLE
Support Gateways as 'whitebox' sidecars

### ISSUE THREAD

**Issue by louiscryan** [istio/istio#10288]
**Describe the feature request**
Describe how to co-locate an Envoy proxy with a workload that is not using iptables as blackbox traffic capture. Instead enable the configuration of that sidecar to be configured using the Gateway resource to allow it to act like a 'whitebox' sidecar that application code explicitly uses.

This mechanism should work with mTLS when sending traffic to or receiving traffic from other similarly configured Envoys in the mesh.

**Describe alternatives you've considered**
None  - no viable alternative other than using blackbox auto-injection

**Additional context**
Initially documentation for how to enable this behavior for testing would be sufficient. Over time this capability feels like it should be part of the platform

**Comment by costinm** [comment]
https://github.com/istio/istio/tree/master/pilot/docker has few examples for envoy used as a non-iptables sidecar. 

Note that both examples have special restrictions - they are used in front of Pilot and Mixer, and for bootstraping reasons they don't use ADS and are focused on inbound.  We'll need to tweak them a bit and test with pilot. 

For outbound - we support HTTP PROXY , by setting ProxyHttpPort in the mesh config map.
It is also possible to use dedicated ports for TCP proxy, i.e. app pointing to localhost:1234, and a manually configured listener and cluster in envoy ( until the new Gateway extensions are finalized )

**Comment by smawson** [comment]
What is the status here? This is a P0 for 1.1 but last update was Dec 21st.

**Comment by costinm** [comment]
PR merged - few fields in the API are not implemented and will need to be hidden,  but it should be usable. 

e2e and stress test seem to be ok, performance is almost same with non-whitebox ( under 1000 qps - didn't push it to the max yet)

**Comment by loewenstein** [comment]
@costinm care to link the merged PR?

**Comment by loewenstein** [comment]
@costinm @louiscryan Could we please have the mentioned PR linked here, so I can read up on what happens and how this works?

**Comment by louiscryan** [comment]
We don't really use the Gateway resource to do this, we introduced the Sidecar CRD to cover this case for which the implementation is

https://github.com/istio/istio/pull/10717

**Comment by louiscryan** [comment]
some samples here

https://github.com/istio/istio/blob/master/tests/testdata/config/none.yaml
