### ISSUE TITLE
Istio-telemetry generating a lot of traces

### ISSUE THREAD

**Issue by Stono** [istio/istio#10297]
This is an issue just to track what I have discussed on slack with @douglas-reid and @mandarjog 

Istio-telemetry is generating a **lot** of traces in Jaeger, see:

![image](https://user-images.githubusercontent.com/1486729/49522526-c4cc1e00-f89f-11e8-9c58-69d8153c4586.png)

Under high load, this is effectively DDOSing our Jaeger instance with Junk.

I believe this is being addressed in 1.0.5 and 1.1.x (would be nice if someone could link an issue or PR?)

@mandarjog suggested removing the `--trace_zipkin_url` setting from the istio-telemetry deployment to stop some spans, however @douglas-reid said "that will stop mixer-proper generated traces. unfortunately, it won't stop the envoy in front of mixer from generating... and that is hard-coded (not controlled by Pilot)"

**Comment by mandarjog** [comment]
resolved by #10281

**Comment by douglas-reid** [comment]
Dupe of https://github.com/istio/istio/issues/4227 ?  Should we close this now?  Or wait until verified with 1.0.5 ?

**Comment by Stono** [comment]
Happy to close in favour of 4227!

**Comment by JackGzj** [comment]
> Happy to close in favour of 4227!

Hello, I am facing the similar problem you meet, I delete the `--trace_zipkin_url` arg in istio-demo.yaml and the mixer stop sending spans. However, I receive many `istio-telemetry` span appearing single in zipkin. Did you meet this problem?

**Comment by douglas-reid** [comment]
@JackGzj which version of Istio?  This is what https://github.com/istio/istio/pull/10281 is meant to address.
