### ISSUE TITLE
Ingress-Gateway does not restart when TLS certs are changed

### ISSUE THREAD

**Issue by howels** [istio/istio#10300]
**Describe the bug**
When adding/updating a TLS cert, the ingress-gateway pod must be deleted as the proxy process doesn't react to the new certificate. Creating issue under advice from @liamawhite 

**Expected behavior**
Proxy SDS service spots the filesystem change and restarts the proxy automatically.

**Steps to reproduce the bug**
Replace cert in ingress-gateway, cert is not used.

**Version**
Istio 1.0.2 and proxyv2:1.0.2

**Installation**
Helm template in Istio 1.0.2, with tag set to 1.0.2

**Environment**
Kubernetes 1.11 and 1.12, self hosted and deployed via KubeSpray.

**Comment by quanjielin** [comment]
SDS work E2E is WIP

**Comment by quanjielin** [comment]
this is done, https://preliminary.istio.io/docs/tasks/traffic-management/secure-ingress/sds/
