### ISSUE TITLE
Most/all addons do not implement https

### ISSUE THREAD

**Issue by sdake** [istio/istio#10317]
**Describe the bug**
The addons do not currently implement https.  The addons can be exposed via ingress gateway to the external world (over http) which is a security problem.

**Expected behavior**
Addons use https by default.

**Steps to reproduce the bug**
I don't have alot of details other than @jmazzitelli has taken the action of implementing https for Kiali.  Jaeger, Grafana, and Promethus remain.

**Version**
release-1.1 prerelease series

**Installation**
I don't have time at this time to dig into the installation options for ingressgateway, but reading the charts should be straightforward for whoever takes this on.

**Environment**
Kubernetes

**Comment by sdake** [comment]
Kiali implementation for HTTPS: https://github.com/istio/istio/pull/10305

**Comment by objectiser** [comment]
@douglas-reid I assume we need to get the istio-ingressgateway to use https? I had a quick go, but didn't work - possibly don't understand enough about how it works.

Assuming this is the approach you are going to take with Prometheus and Grafana, then once you have a PR, I can do the tracing one.

**Comment by jmazzitelli** [comment]
> stio-ingressgateway to use https? I had a quick go, but didn't work - possibly don't understand enough about how it works.

I'm investigating the gateway/ingress stuff now. I thought the helm charts included Gateway definitions for these things, but I don't see them when I installed 1.1.snapshot3. Does anyone know if the Gateways are installed anymore? They may have been removed.

But the helm values files still have settings for these... see:

https://github.com/istio/istio/blob/master/install/kubernetes/helm/subcharts/gateways/values.yaml#L48-L59

**Comment by douglas-reid** [comment]
I was understanding the scope of this issue to not only focus on gateway/ingress exposure, but also on within cluster, as I think ultimately we need both.

With Prom, putting a proxy in front requires a little bit of customization (requires inbound only). I'm gonna focus on that first and eagerly wait @jmazzitelli gateway magic :).

**Comment by jmazzitelli** [comment]
I'm slowly making my way through the jungle. I have two PRs that are foundations for the gateway work:

* https://github.com/istio/istio/pull/10349 this provides gateway.enabled flags for all addons (and by "all" I mean prometheus, jaeger, kiali, grafana). This is basically refactoring some charts and I took most of the work from another PR that was old - this new PR fixes conflicts, adds kiali, and is based on release-1.1 branch. 

* https://github.com/istio/istio/pull/10340 - this puts Citadel generated certificates to use in kiali's http server so it is supporting https. This PR however won't work with istio gateways (it only works with k8s ingress).

I am now trying to figure out gateway magic - I'm hoping the Citadel generated certificates can be used via the gateways (it makes sense to me that it should, anyway).

**Comment by sdake** [comment]
@jmazzitelli this should help get you going for gateway/vs/dr's for the various services.  AFAIK these are already implemented.  What we want, as @douglas-reid stated, is for the internal network to be protected via https.

See this documentation: https://docs.google.com/document/d/1c_dLTBTszNeUGXpE9fzPINw7wo6s8bVRHRBeIbjBAtA/edit#heading=h.yefzcqwzncom

This allowed me to use ingressgateway as a passthrough and ultimately let the application itself handle HTTPS (the application in the above doc was pilot...).

The main reason ingressgateway can be used as a passthrough for this port is a result of:
https://github.com/istio/istio/blob/master/install/kubernetes/helm/subcharts/pilot/templates/meshexpansion.yaml#L86-L87

YMMV - the doc is incomplete and I've (personally) abandoned the VPN approach to multicluster.

Cheers
-steve

**Comment by jmazzitelli** [comment]
@sdake I'm currently waffling back and forth wondering what is easiest to do. Kiali, as you've seen, is able to handle HTTPS itself (I can give Kiali its citadel certs and so it can handle https) so we could passthrough and let kiali handle it. However, IIRC, Prometheus does not provide this capability (i.e. they do not have a way to directly configure or "turn on" https for its front end). In that case, we can't passthrough and let the application (prom) handle https - we'd need the gateway to do it.

I do not know jaeger or grafana enough yet to know if they can directly handle https.

**Comment by jmazzitelli** [comment]
I have a quick implementation that puts https in front of all add-ons (prometheus, grafana, jaeger,kiali): https://github.com/istio/istio/pull/10363

**Comment by jmazzitelli** [comment]
> I was understanding the scope of this issue to not only focus on gateway/ingress exposure, but also on within cluster, as I think ultimately we need both.

This will be addressed with issue #10587 

This current issue will be for putting https on the edge only.

**Comment by jmazzitelli** [comment]
https://github.com/istio/istio/pull/10363 has been merged. I don't know if we want to close this issue and move to issue #10587 for the future work or if we want to keep this open for other reasons.

**Comment by sdake** [comment]
@jmazzitelli sounds good.  I'll close this issue.

Thanks for the work!
