### ISSUE TITLE
istio-1.1.0-snapshot.3 gives error on helm install as charts/ directory

### ISSUE THREAD

**Issue by mmshaikh88** [istio/istio#10326]
**Describe the bug**
I am trying to install istio using helm tiller option with zipkin as: helm install install/kubernetes/helm/istio --name istio --namespace istio-system --set tracing.enabled=true --set tracing.provider=zipkin

**Expected behavior**
Expect the istio installed with zipkin 

**Steps to reproduce the bug**
$ helm install install/kubernetes/helm/istio --name istio --namespace istio-system --set tracing.enabled=true --set tracing.provider=zipkin
Error: found in requirements.yaml, but missing in charts/ directory: sidecarInjectorWebhook, security, ingress, gateways, mixer, nodeagent, pilot, grafana, prometheus, servicegraph, tracing, galley, kiali, istiocoredns, certmanager, istio-cni
**Version**

{{ What version of Istio and Kubernetes are you using? Use `istioctl version` and `kubectl version` }}
istio-1.1.0-snapshot.3
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**Installation**
{{ Please describe how Istio was installed }}
using the tar file istio-1.1.0-snapshot.3-linux.tar.gz
**Environment**
{{ Which environment, cloud vendor, OS, etc are you using? }}
Ubuntu 16.04

**Cluster state**
{{ If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue. }}

**Comment by objectiser** [comment]
Have confirmed the issue, but just wanted to clarify that this is not related to tracing/zipkin provider, as same occurs with:
```
helm install install/kubernetes/helm/istio --name istio --namespace istio-system
```

**Comment by vhosakot** [comment]
I saw the same error too when installing istio `1.1.0-snapshot.3` in https://github.com/istio/istio/releases/tag/1.1.0-snapshot.3:

```
wget https://github.com/istio/istio/archive/1.1.0-snapshot.3.tar.gz
gunzip 1.1.0-snapshot.3.tar.gz
tar -xvf 1.1.0-snapshot.3.tar
cd istio-1.1.0-snapshot.3

$ helm upgrade --install istio --namespace istio-system install/kubernetes/helm/istio/
Release "istio" does not exist. Installing it now.
Error: found in requirements.yaml, but missing in charts/ directory: sidecarInjectorWebhook, security, ingress, gateways, mixer, nodeagent, pilot, grafana, prometheus, servicegraph, tracing, galley, kiali, istiocoredns, certmanager

$ helm dep update install/kubernetes/helm/istio/
Error: no repository definition for @istio.io. Please add them via 'helm repo add'
```

The following steps in https://github.com/istio/istio.io/issues/2787#issuecomment-443688642 resolved these errors for me:

```
helm repo add istio.io https://storage.googleapis.com/istio-release/releases/1.1.0-snapshot.3/charts
helm dep update install/kubernetes/helm/istio/
helm upgrade --install istio --namespace istio-system install/kubernetes/helm/istio/

$ helm repo list | grep istio.io
istio.io	https://storage.googleapis.com/istio-release/releases/1.1.0-snapshot.3/charts

$ helm list istio
NAME 	REVISION	UPDATED                 	STATUS  	CHART      	APP VERSION	NAMESPACE   
istio	1       	Wed Dec 19 19:44:20 2018	DEPLOYED	istio-1.1.0	1.1.0      	istio-system
```
