### ISSUE TITLE
Istio allows traffic to any external IP if there are no listeners for the destination port

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio#10330]
The following code https://github.com/istio/istio/blob/1e31675e9641c0180c96648b7379b562edfd0738/pilot/pkg/networking/core/v1alpha3/listener.go#L167 allows traffic to any external IP, if there are no listeners for the destination port:

 ```
kubectl exec -it $SOURCE_POD -c sleep -- curl http://portquiz.net:1
Port 1 test successful!
```

Here the traffic to port 1 of http://portquiz.net is allowed. Note that for any port for which listeners are defined, for example for ports which some services use, e.g. 80, 8080, the traffic is blocked by default:

```
kubectl exec -it $SOURCE_POD -c sleep -- curl -v http://portquiz.net:80
* Rebuilt URL to: http://portquiz.net:80/
*   Trying 5.196.70.86...
* TCP_NODELAY set
* Connected to portquiz.net (5.196.70.86) port 80 (#0)
> GET / HTTP/1.1
> Host: portquiz.net
> User-Agent: curl/7.60.0
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< date: Fri, 07 Dec 2018 06:33:53 GMT
< server: envoy
< content-length: 0
< 
* Connection #0 to host portquiz.net left intact
```

The current behavior is as follows - if no ServiceEntries are defined for some port, all the traffic to that port is allowed. Once any ServiceEntry is defined for some port, traffic to all other hosts with this port is blocked.

I propose to add a flag to make such behavior optional or even remove this feature.

**Comment by vadimeisenbergibm** [comment]
A discussion at the Istio users group https://groups.google.com/forum/#!topic/istio-users/J_Ad-wTLjmY

**Comment by vadimeisenbergibm** [comment]
@rshriram What do you think? Do we want this behavior:
 > if no ServiceEntries are defined for some port, all the traffic to that port is allowed. Once any ServiceEntry is defined for some port, traffic to all other hosts with this port is blocked.

Do we want a flag?

See https://groups.google.com/forum/#!topic/istio-users/J_Ad-wTLjmY

**Comment by rshriram** [comment]
we added this feature because another set of users complained that default istio install broke everything.. So we can't remove this. 

we need a flag from the global mesh config. Something like allow_traffic_to_unknown_ports

**Comment by vadimeisenbergibm** [comment]
@rshriram, OK, let me add the flag.

**Comment by costinm** [comment]
Please make sure when Sidecar is implemented, this is preserved - i.e. if user adds a '*' to the Sidecar
egress, that namespace has the equivalent 'allow_traffic_to_unknown_ports'.

Most users I know require egress to work as before installing Istio, i.e. 'allow_traffic'  - but they configure this using the other option, the CIDR range. It would be good to cross-link the docs. The CIDR range doesn't have the problem mentioned in this bug ( if a ServiceEntry is defined on same port - it'll have no negative effect ), however it has the limitation that Istio can't control egress outside of the mess at all.

**Comment by vadimeisenbergibm** [comment]
@costinm Will do. Note that currently, by default the traffic to unknown ports is not controlled - it does not have the mixer filter. @rshriram Should I add the mixer chain before the filter below? (the filter itself will be added conditioned on `ALLOW_ANY`)

```json
"filterChains": [
            {
                "filters": [
                    {
                        "name": "envoy.tcp_proxy",
                        "config": {
                            "cluster": "PassthroughCluster",
                            "stat_prefix": "PassthroughCluster"
                        }
                    }
                ]
            }
        ],
```

**Comment by linsun** [comment]
@vadimeisenbergibm can this be closed now?

**Comment by vadimeisenbergibm** [comment]
@linsun I still have to document it, and also fix https://github.com/istio/istio/issues/10933, since now Egress control is broken altogether.

**Comment by klausenbusk** [comment]
> @linsun I still have to document it, and also fix #10933, since now Egress control is broken altogether.

Is the traffic routed through the egress gateway? If yes, does that mean I can route all cluster traffic through a specific node (so the ip is static regardless of autoscaling)?

**Comment by vadimeisenbergibm** [comment]
@klausenbusk If you want the traffic to be routed through the egress gateway, you have to configure it explicitly, see https://preliminary.istio.io/docs/examples/advanced-gateways/egress-gateway/.

You can route all cluster egress traffic through a specific Kubernetes service. You then can deploy all the pods that provide that service to some specific node, I guess using https://kubernetes.io/docs/concepts/configuration/assign-pod-node/ .

**Comment by duderino** [comment]
@rshriram @vadimeisenbergibm is anything left to be done here?  

What are the implications of not merging https://github.com/istio/istio/issues/6146 into 1.1?

**Comment by esnible** [comment]
Should we add the `area/security` tag to this Issue?

**Comment by vadimeisenbergibm** [comment]
@esnible No, I think it is networking only. Closing the issue, it is already implemented.
