### ISSUE TITLE
can't initialize ip6tables table `filter'

### ISSUE THREAD

**Issue by LzyRapx** [istio/istio#10335]
**Describe the bug**
+ ip6tables -F INPUT
ip6tables v1.6.0: can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)
Perhaps ip6tables or your kernel needs to be upgraded.
+ true
+ ip6tables -A INPUT -m state --state ESTABLISHED -j ACCEPT
ip6tables v1.6.0: can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)
Perhaps ip6tables or your kernel needs to be upgraded.
+ true
+ ip6tables -A INPUT -j REJECT
ip6tables v1.6.0: can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)
Perhaps ip6tables or your kernel needs to be upgraded.

**Steps to reproduce the bug**
```
> kubectl logs xxxxxxxx istio-init
```
and then `can't initialize ip6tables table `filter':`

**Version**
```
> kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
**Installation**
Install istio (from Library) on rancher2.0. catalog Apps.
**Environment**
Linux cpu-s-107 4.15.0-36-generic #39~16.04.1-Ubuntu SMP Tue Sep 25 08:59:23 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by LzyRapx** [comment]
How to fix it? Thx

**Comment by lnogol** [comment]
currently having the same problem

**Comment by LzyRapx** [comment]
### **update. solved.**

**Comment by divramod** [comment]
hey, i am having the same issue with kubernetes. 
how did you solved it?

**Comment by vlcty** [comment]
> ### **update. solved.**

I hate people like you. Please post your solution!

**Comment by vlcty** [comment]
I post my solution: I've done a kernel update before and wanted to reboot. But I also wanted to check if the ip6tables were dumped into the filesystem.
After a reboot everything was fine.

**Comment by LzyRapx** [comment]
> > ### **update. solved.**
> 
> I hate people like you. Please post your solution!

???

**Comment by LzyRapx** [comment]
Because Ip6tables is operated in the kernel state of Linux. The istio-init needs to call the host kernel. The istio-init must have root privileges. It must have a corresponding adminssion and a privileged mode for the pod.
So there must be `MutatingAdmissionWebhook` and 'ValidatingAdmissionWebhook' in the admission-control or --enable-admission-plugins in kube-apiserver, which are added in strict order. Here you need to modify the K8S apiserver. And add '--allow-privileged=true' to k8s apiserver.

**Comment by howardjohn** [comment]
Seems the issue is resolved, and I believe this requirement is documented already in https://istio.io/docs/setup/kubernetes/additional-setup/sidecar-injection/#automatic-sidecar-injection.

if there are other docs that would be useful a PR in https://github.com/istio/istio.io would be greatly appreciated
