### ISSUE TITLE
Allow to hand down mTLS settings from Mesh/Namespace policy

### ISSUE THREAD

**Issue by pilhuhn** [istio/istio#10341]
**Describe the feature request**

When you enable mesh wide (or namespace wide) mTLS, there is a DestinationRule (DR) that says for *.local or the namespace send traffic via mTLS.
Now when you write a DR for other stuff and forget to also put the trafficPolicy for mTLS, this is basically disable, but the receiver still expects TLS traffic and thus the connection fails.

The idea here is to add an attribute to the https://istio.io/docs/reference/config/istio.networking.v1alpha3/#TLSSettings to say "hand down". If that is set, local DRs do not need to repeat the TLS settings as they are used from the global/namespace one. If the user (explicitly) specifies any TLS setting, then this is taken and the global/namespace one is ignored

My passing the global settings down it is possible to use the same local DRs both in an environment with or without mTLS (and the users need to type less)

**Describe alternatives you've considered**

The local DR could get an attribute `mode: INHERIT`, but this still implies that the user provide the full trafficPolicy  entry in each DR.

See also https://medium.com/@pilhuhn/musings-about-istio-with-mtls-c64b551fe104

**Comment by incfly** [comment]
Thanks for the feedback. We have been thinking about supporting `DR` inheritance in general. There has been some similar FR like this. I think there's some existing proposal to define the inheritance semantics for istio api. maybe @ozevren can gave some pointer. 

/cc @diemtvu @costinm @wenchenglu

**Comment by pilhuhn** [comment]
Ping @ozevren

**Comment by pilhuhn** [comment]
Ping again

Am 9. Juni 2019 17:27:38 schrieb "stale[bot]" <notifications@github.com>:

**Comment by wenchenglu** [comment]
@diemtvu  fyi
