### ISSUE TITLE
Bookinfo is not displaying ratings unavailable message

### ISSUE THREAD

**Issue by frankbu** [istio/istio#1034]
The new version of bookinfo doesn't display the message "ratings are currently unavailable" when you run the rate limiting task, like it used to. Now it just stops displaying ratings, so it looks like it's switched back to `reviews:v1`, instead of what is actually happening: `reviews:v3` is being used, but its calls to the `ratings` service are blocked.

This is a regression caused by https://github.com/istio/istio/pull/693.

**Comment by jasonwzm** [comment]
made a PR https://github.com/istio/istio/pull/2354 to fix this

**Comment by jasonwzm** [comment]
this is now fixed
