### ISSUE TITLE
Searches within istio.io site yields 0.1 docs as top results

### ISSUE THREAD

**Issue by jasminejaksic** [istio/istio#1035]
As an example: this search -> https://istio.io/search/?q=4%20standard%20GKE%20nodes results in https://istio.io/v-0.1/docs/samples/bookinfo.html as the top link instead of https://istio.io/docs/guides/bookinfo.html#running-on-kubernetes

**Comment by ldemailly** [comment]
this should be in the website repo, but anyway...

martin I think there is a way either in sitemap or robots.txt to tell google to not index v-0.1 ?

**Comment by geeknoid** [comment]
This is puzzling. We generate an explicit sitemap.xml to tell web crawlers about our site and it doesn't include the v-0.1 directory (you can see the file by going to istio.io/sitemap.xml)

**Comment by ldemailly** [comment]
guessing then the crawler is doing it the old way, but following the link to v-0.1 in the docs/ index
(that or firebase sites are auto indexed)

maybe we can explicitly forbid https://istio.io/v-0.1/ in the robots.txt ?
(and while at it skip any *.old )

**Comment by geeknoid** [comment]
The robots.txt file has been updated to exclude the v-0.1 directory, so this problem should fix itself shortly.

**Comment by sakshigoel12** [comment]
@jasminejaksic @geeknoid this is not fixed but as Martin said it should fix itself with time. Lets keep an eye but remove it from launch blocking it

**Comment by geeknoid** [comment]
I just requested Google to reindex the site, so hopefully that'll clear
things up.

**Comment by geeknoid** [comment]
This finally seems to be working properly. Please let me know if this happens again.

@ldemailly, anytime you add a new versioned branch of the docs, we need to update robots.txt to reflect that in order avoid this issue happening again.

**Comment by ldemailly** [comment]
Ok,
Would
Disallow: /v-*
Work ?

**Comment by geeknoid** [comment]
​Possibly. Worth trying.​
