### ISSUE TITLE
Evaluate the risk and benefits of liveness probe rewrite on by default

### ISSUE THREAD

**Issue by incfly** [istio/istio#10357]
**Describe the feature request**
Istio currently supports to rewrite the kubernetes liveness probe rewrite during `kube-inject` time. This improves user experience who used have to rewrite their PodSpec with `curl` for liveness probe under mTLS. We currently disable this feature by default for risk consideration.

**Describe alternatives you've considered**
Turn on by default when we believe the benefits are larger than risks. This needs user feedback. Please consider answering following questions

- If you have tried this feature, how long and how large deployments you enabled the feature? In terms of number of the pods and different readiness/liveness probers?
- The feature is not needed if you can use other options, `curl cmd` probe in app container or use different ports for the health check, and configure authentication policy differently for different ports. Can you explain why you can't use those two approach?

**Additional context**
https://github.com/istio/istio/issues/9150

**Comment by wattli** [comment]
The design is [here](https://docs.google.com/document/d/1RxO3IBT8z68XNmM8tGWxrUcSbrRneiBWlL1A4qZf3CU/edit#heading=h.x9snb54sjlu9)

**Comment by liminw** [comment]
@incfly @wattli What is the plan to move forward?

**Comment by wattli** [comment]
The doc is under review: https://github.com/istio/istio.io/pull/2961

And we will keep this feature disabled by default in the beginning and encourage customers to try out this feature. Later on we will enable it by default if the feedback is positive or we can fix potential issues reported by them.

**Comment by liminw** [comment]
@wattli thanks, sounds good.

**Comment by aaronhnatiw** [comment]
Having this enabled by default sounds like a sane default to me. It would have saved me the need to spend time debugging why my liveness probes weren't working with Istio. I enabled it in my environment with no problems. 

(I was sent here from [the documentation](https://istio.io/help/ops/setup/app-health-check/#mutual-tls-is-enabled), asking for feedback on this particular issue)

**Comment by incfly** [comment]
@aaronhnatiw Thanks for the feedback. Just updated the description in issue.

> If you have tried this feature, how long and how large deployments you enabled the feature? In terms of number of the pods and different readiness/liveness probers?

> The feature is not needed if you can use other options, curl cmd probe in app container or use different ports for the health check, and configure authentication policy differently for different ports. Can you explain why you can't use those two approach and prefer rewrite approach is used instead?

**Comment by aaronhnatiw** [comment]
@incfly Thanks, here is my answers to those questions:

My deployment is not a large deployment, only one liveness probe across a single-node cluster (a dev deployment).

I chose to use the `httpGet` liveness probe because it was the same type of probe that I used from a loadbalancer, and it mirrors what I'm using in my unit tests. This method feels like a much better engineering choice than the other two, as it allows me to keep my application functioning the same (the liveness probe is against an HTTP service), without adding much additional functionality just for liveness probes. Because liveness probes (at least in this deployment) are specific to Kubernetes, it also allows me to continue to have portability in my codebase/containers by using the liveness probe rewrite.

**Comment by dweidenfeld** [comment]
I think it should be on by default, since `exec` liveness/readiness checks may add up a delay on the readiness. I've had the case several times, that my app launched in 5 - 10 seconds, but the `exec` check delayed the health check by 30 seconds, so my app was ready after 40 seconds instead of 5 - 10.

On the other hand I can get rid of installing curl everywhere in my Docker containers :+1:

**Comment by incfly** [comment]
I want to enable this by default in next release, 1.5.

It's just another thing we should do to make Istio works for your application out of the box.

The prerequisite is that we now have a positive/negative integration test to ensure the feature is working. Also given we have ways to disable the rewrite, so the UX benefits seem trump over the manageable risks.

Please call out if this does not seem right to anyone.

**Comment by incfly** [comment]
https://github.com/istio/istio/issues/16785 One more data point

**Comment by planetf1** [comment]
Enabling by default seems correct for me given the many cases of issues with it not working, (albeit with docs for why one might disable)

**Comment by xUnholy** [comment]
Out of each of the options, `sidecarInjectorWebhook.rewriteAppHTTPProbe=true` feels like the best approach to make default if there was a need for one. 

Recommending to write liveness and readiness probes with commands is not always a feasible option, considering some images don't have any curl or equivalent CLI, additionally, it becomes cumbersome when you're consuming upstream helm charts that don't have these fields parameterised and then need to run something like kustomize to do some YAML stitching is just a real pain.

Again the 3rd option to use different ports is not ideal if this is 3rd party software and it's not feasible for me to request and wait for months for them to implement and ship a new version of their product.

Although, even having `sidecarInjectorWebhook.rewriteAppHTTPProbe=true` now puts an immense of extra load on the Pilot and I'd be interested to see if any benchmarking has been done to show how the Pilot will handle the additional load of all requests within a cluster for each given liveness and readiness probe.

**Comment by incfly** [comment]
Thanks for the feedback. We do plan to enable this on by default, maybe in 1.5. Currently the last pending issue we found is the timeout specification is not respected. @johnma14 is working on that and once it's done, we can attempt to enable it by default.

> Although, even having sidecarInjectorWebhook.rewriteAppHTTPProbe=true now puts an immense of extra load on the Pilot and I'd be interested to see if any benchmarking has been done to show how the Pilot will handle the additional load of all requests within a cluster for each given liveness and readiness probe.

By Pilot do you actually mean Pilot agent? To clarify, pilot is not involved in the health check request at all. It's the pilot agent which runs as part of the sidecar container taking over the health check req.

I can't see any reason why pilot agent can't handle the request, basically it's one more hop of the http req. kubelet -> app becomes kubelet -> pilot agent -> app.

**Comment by xUnholy** [comment]
@incfly Thanks for that clarification, I must have misinterpreted the documentation to think it was Pilot, however, the Pilot agent makes a lot more sense once reading through the documentation. In that case, my concern is void.

**Comment by howardjohn** [comment]
@incfly whats blocking us from switching this to default?

**Comment by Stono** [comment]
As someone who has like, 1000 curl based probes - I wish this was available when we took up istio.  It does feel like something that should be enabled from the offset to help new adopters.

Downside is you're mutating code which effectively doesn't belong to the "istio" domain, eg my developers check one thing into git, and something else gets deployed.  I typically like to minimise runtime mutations like this.  So please extensively test it and code extremely defensively! :)

**Comment by esnible** [comment]
Will this be the default in 1.5?

**Comment by incfly** [comment]
No because I didn't see the issue about original timeout duration will be
addressed. I see a community PR recently though.

**Comment by howardjohn** [comment]
Tip for future debuggers: if you get into an infinite loop of readiness probe, somehow your pod got injected twice

**Comment by pc-rshetty** [comment]
My 2 cents after using Istio on production for more than a year is don't mix control plane and data plane. If liveliness probe relies on pilot to be always up and running then it is an issue. We upgrade our istio control plane without affecting the data plane.

**Comment by howardjohn** [comment]
This doesn't go through control plane at all

**Comment by pc-rshetty** [comment]
@howardjohn pilot is the part of istio control plane ?

**Comment by howardjohn** [comment]
Yes, it doesn't rely on pilot though, it's all done locally in the sidecar

**Comment by pc-rshetty** [comment]
Very nice the @howardjohn good to know when pilot is down still the liveliness probes will work
