### ISSUE TITLE
Integrate Istio Citadel agent and Vault

### ISSUE THREAD

**Issue by myidpt** [istio/istio#10356]
**Describe the feature request**
Enable the Citadel agent to call the Vault server to provision X.509 certificates. The authentication and authorization (based on K8s JWT) are conducted on Vault (assume the customer maintains a syncer from K8s service account to Vault roles).

**Describe alternatives you've considered**
Delegate the authn and authz to Citadel, and hook up Citadel with Vault.

**Comment by myidpt** [comment]
Breakdown the task:

- [ ] Implement Vault client adaptor on node agent to call to Vault
- [ ] Implement end-to-end test
- [ ] Implement syncer as reference implementation to synchronize K8s apiserver to Vault

**Comment by jasminejaksic** [comment]
Only pending task is user instructions, so moving this to P1. Oliver is working on it, ETA EoM

**Comment by lei-tang** [comment]
The issue #10968 has been created to track the task of user instructions and is assigned to @lei-tang.
