### ISSUE TITLE
servicegraph api d3graph query label source_namespace no data

### ISSUE THREAD

**Issue by lincolnzhou** [istio/istio#10375]
**Describe the bug**
api url
http://localhost:8088/d3graph?source_namespace=default&source_workload=productpage-v1

it returns no data

```
{
"nodes": [],
"links": []
}
```

**Expected behavior**
it should return nodes about productpage

**Steps to reproduce the bug**
{{ Minimal steps to reproduce the behavior }}

**Version**
➜  src kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

➜  src istioctl version
Version: 1.0.4
GitRevision: d5cb99f479ad9da88eebb8bb3637b17c323bc50b
User: root@8c2feba0b568
Hub: docker.io/istio
GolangVersion: go1.10.4
BuildStatus: Clean

**Installation**
{{ Please describe how Istio was installed }}

**Environment**

**Cluster state**
{{ If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue. }}

Prometheus data
```
istio_requests_total{connection_security_policy="none",destination_app="details",destination_principal="unknown",destination_service="details.default.svc.cluster.local",destination_service_name="details",destination_service_namespace="default",destination_version="v1",destination_workload="details-v1",destination_workload_namespace="default",instance="172.17.0.19:42422",job="istio-mesh",reporter="destination",request_protocol="http",response_code="200",source_app="productpage",source_principal="unknown",source_version="v1",source_workload="productpage-v1",source_workload_namespace="default"}
```

I find that label is source_workload_namespace, not source_namespace. So the api parameter source_namespace needs to be changed to source_workload_namespace

**Comment by jmazzitelli** [comment]
FYI: servicegraph has been deprecated in lieu of Kiali and most likely hasn't been updated to work with the latest telemetry data. 

See: https://preliminary.istio.io/docs/tasks/telemetry/kiali/ 

(kiali can work with 1.0.4 in addition to 1.1).

**Comment by lincolnzhou** [comment]
ok，thanks 😄
