### ISSUE TITLE
e2e_dashboard test is flaky

### ISSUE THREAD

**Issue by hklai** [istio/istio#10384]
Test failures:
https://gubernator.k8s.io/build/istio-prow/logs/e2e-dashboard/8825

Init failure:
https://gubernator.k8s.io/build/istio-prow/logs/e2e-dashboard/8785
(which failed at https://github.com/istio/istio/blob/df0d817c5ecf6f3fab94cb599ddd90c363c4d533/tests/e2e/tests/dashboard/dashboard_test.go#L216)

Circle shows somewhat similar result.
https://testgrid.k8s.io/istio-postsubmits#circleci-e2e-dashboard

**Comment by douglas-reid** [comment]
@hklai the TCP dash failure linked is from the period between the switch to MCP tests and @ayj 's PR's to convert the tests back to using the proper install artifacts.

The init failure is a bit odd. I can look into it.

What I don't understand is why, with the switch to MCP, tests that were solid for a long time have started to flake a bunch. This doesn't inspire a lot of confidence in the stability of the system with MCP.

**Comment by douglas-reid** [comment]
Note to self: I've seen `2018-12-10T21:04:02.473619Z	error	adapters	Prometheus handler error: error encoding and sending metric family: write tcp 10.8.0.9:42422->10.8.0.12:47190: write: broken pipe` in logs. I think this means that Mixer is crashing while something is attempting to read its metrics. This is not a good situation.

**Comment by douglas-reid** [comment]
Everything looks green on the release-1.1 pre/post-submits.  Thanks to @ayj for tracking down the install artifacts issue!

I'm going to close for now. Hopefully, when the release-1.1 changes are merged to master, we see similar benefits on that branch.  Feel free to reopen if my assessment is incorrect.
