### ISSUE TITLE
Remove the hardcoded sidecar template for `istioctl kube-inject`

### ISSUE THREAD

**Issue by incfly** [istio/istio#10380]
Currently `istioctl` has the option to use a local hard coded template for kube-inject [1]. This is only for backward comparability when we switch to configmap stored injector configmap. Now it becomes a maintaining overhead to modify two sidecar templates, we need to remove the hardcoded one and only rely on the configmap.

This might need to update some test to read input from sidecar template from `install/kubernetes/helm`. 

[1] https://github.com/istio/istio/blob/master/pilot/pkg/kube/inject/mesh.go#L22

**Comment by mathspanda** [comment]
Is there anyone working on this? If not, i am happy to work on it as my first issue.

**Comment by mandarjog** [comment]
Please pick it up.

**Comment by incfly** [comment]
@mathspanda Welcome for help! Please feel free to ask me for more details if needed.

**Comment by mathspanda** [comment]
not stale
