### ISSUE TITLE
mixer memory was rising when I applyed kubernetesenv adapter

### ISSUE THREAD

**Issue by zhu0516123** [istio/istio#10393]
**Describe the bug**
After I installed istio and my application, I accessed my application, and then the memory of mixer-policy and mixer-telemetry were rising all the time until crashed. But when I remove the rules (kubeattrgenrulerule and tcp kubeattrgenrulerule) which were in istio-demo-auth.yaml, the mixer memory was normal. The two rules were applied to kubernetesenv adapter which pulled kubernetes cluster info every 5 minuties. When the adapter were pulling info from kubernetes from api-server, the receiving rate of mixer were 1MB/s, and the memory were rising fast. After several times of pulling info, the mixer crashed out of memory.

**Version**
kubernetes: 1.11.0
istio: 1.0.3
openshift: 3.11.43

**Installation**
kubectl apply -f crd.yaml
kubectl apply -f istio-demo-auth.yaml
Mixer request and limit memory is 1600Mi, and cpu is 1000m

**Environment**
openshift

**Comment by douglas-reid** [comment]
@mandarjog how does this match with our numbers and experience on our large scale testing clusters?

**Comment by mandarjog** [comment]
This is a new observation. Can you
1. Increase the limit or remove limits and see if the memory stabilizes at some point 
2. Export mixer grafana dashboard and share it via raintank.

The amount of memory needed by kubeenv adapter scales by the size of the deployment. How large is your deployment ?

**Comment by zhu0516123** [comment]
@mandarjog 
Because of some security restrictions, I can not export the grafana dashboard. Here are some pictures of mixer grafana dashboard and logs from mixer-policy. 

Mixer request and limit memory is 1600Mi, and cpu is 1000m.
The size of deloyment in openshift:
pod: 1600
service: 700
namespace: 200
But only 10 applications use istio.

**mixer grafana dashboard:**
![grafana1](https://user-images.githubusercontent.com/20107856/49842396-597dd100-fdf6-11e8-977d-8d7e194aee9f.jpg)
![grafana2](https://user-images.githubusercontent.com/20107856/49842818-fc831a80-fdf7-11e8-944a-290c07062d1d.jpg)
![grafana3](https://user-images.githubusercontent.com/20107856/49842843-13c20800-fdf8-11e8-9f5e-4d191e5ea08d.jpg)
![grafana4](https://user-images.githubusercontent.com/20107856/49842846-16bcf880-fdf8-11e8-948a-83f9fbbf86eb.jpg)
![grafana5](https://user-images.githubusercontent.com/20107856/49842852-19b7e900-fdf8-11e8-9874-0d5b8391c4fa.jpg)
![grafana6](https://user-images.githubusercontent.com/20107856/49842855-1d4b7000-fdf8-11e8-95f7-d1bfa3d4e94b.jpg)

**logs from mixer-policy:**
![log1](https://user-images.githubusercontent.com/20107856/49843102-f7729b00-fdf8-11e8-9def-064fb36bb199.jpg)
![log2](https://user-images.githubusercontent.com/20107856/49843104-f9d4f500-fdf8-11e8-9421-365b7b84fe2e.jpg)
![log3](https://user-images.githubusercontent.com/20107856/49843111-fc374f00-fdf8-11e8-884c-421a1403dd98.jpg)
![log4](https://user-images.githubusercontent.com/20107856/49843115-fe011280-fdf8-11e8-947e-7f65b652a77e.jpg)
![log5](https://user-images.githubusercontent.com/20107856/49843118-ff323f80-fdf8-11e8-9f01-2b28bc00cba9.jpg)

I will increase limit of memory to 10Gi for mixer. And show the result later.

**Comment by zhu0516123** [comment]
I increased limit of memory to 10Gi for mixer. After runing 6 hours, mixer restarted because the memory  ran out.

**Comment by zhu0516123** [comment]
@mandarjog @douglas-reid 
there are a lot of following error messages in the mixer log.
`error adapters adapter did not close all the scheduled daemons {"adapter": "handler.kubernetesenv.istio-system"}`
Does this cause a memory leak which leads to mixer memory growth all the time?

**Comment by mandarjog** [comment]
Yes, it can cause memory leak. Can you send us istio-policy logs?
Are you making frequent changes to istio /mixer configuration? If `kubernetesenv` adapter is reloaded without these changes, then it is also an issue.

**Comment by zhu0516123** [comment]
@mandarjog
The log I post above really looks like a memory leak. Does mixer really have this problem in  OpenShift Container Platform?

**Comment by mandarjog** [comment]
I am not sure yet if this is OpenShift specific. We have to investigate this. I have marked it as a p0 for 1.1

**Comment by mandarjog** [comment]
Can you get me a goroutine and heap dump of mixer in this state?

**Comment by zhu0516123** [comment]
@mandarjog 
I can not get into the mixer container, so I can only give you mixer memory and metric info in mixer controlz web page. There are some goroutine and heap info in it. And what I find in controlz is that there are thousands of config IDs in many metrics. This must not be normal.
![memory](https://user-images.githubusercontent.com/20107856/50139514-efc16380-02dc-11e9-8448-07023e64e2f8.jpg)
![metric1](https://user-images.githubusercontent.com/20107856/50139629-2ac39700-02dd-11e9-8a22-475b67a4adca.jpg)
![metric2](https://user-images.githubusercontent.com/20107856/50139630-2ac39700-02dd-11e9-80ea-fcc93749456d.jpg)
![metric3](https://user-images.githubusercontent.com/20107856/50139631-2b5c2d80-02dd-11e9-8a78-c6caa3c179dd.jpg)
![metric4](https://user-images.githubusercontent.com/20107856/50139632-2b5c2d80-02dd-11e9-893b-cd179ca8baa7.jpg)
![metric5](https://user-images.githubusercontent.com/20107856/50139633-2bf4c400-02dd-11e9-959d-101aaa7ff003.jpg)
![metric6](https://user-images.githubusercontent.com/20107856/50139634-2bf4c400-02dd-11e9-9059-fcadc959aeea.jpg)
![metric7](https://user-images.githubusercontent.com/20107856/50139636-2c8d5a80-02dd-11e9-8273-0af8dd92e196.jpg)
![processinfo](https://user-images.githubusercontent.com/20107856/50139637-2d25f100-02dd-11e9-910c-1929e09f30aa.jpg)

**Comment by mandarjog** [comment]
You can get thread dump as follows
```
kubectl -n istio-system port-forward ${istio-policy-pod} 9093 &

curl localhost:9093/debug/pprof/goroutine?debug=2 -o ${istio-policy-pod}.txt

go tool pprof -svg localhost:9093/debug/pprof/heap
 
```

**Comment by zhu0516123** [comment]
@mandarjog 
I have already sent  goroutine and heap dump of mixer-policy to your gmail, please check it.

**Comment by zhu0516123** [comment]
@mandarjog
By the way, do you know how to set the interval of periodical report which generated by proxy when tcp connection is alive. The default interval for periodical report is 10s. But I do not find where to set the period in istio-demo.yaml.

**Comment by mandarjog** [comment]
Thanks for sending the data. Re reporting period, it is not configurable at present.
Do you need it to be configurable?

**Comment by mandarjog** [comment]
regarding the memory leak, we found an issue with kubeenv adapter, as seen in the log messages. It is not relinquishing the state even after close. This causes the k8s client cache to live forever.

We will fix it soon. I would like to fix it in 1.1 . If you can use 1.1 pre-release builds. 
If you need the fix in 1.0, please let us know.

**Comment by zhu0516123** [comment]
@mandarjog 
Thank you. Please fix it in 1.0 because we have deployed istio in prod env.
And I find another issue that the default interval for periodical report is 1s not 10s as the mixer-telemetry log shows. Should I open another issue?

**Comment by douglas-reid** [comment]
I've sent a provisional fix for what I believe the underlying issue was. Please take a chance to review, if possible.

**Comment by jasminejaksic** [comment]
What's the fix (PR#)? And who is going to verify this?

**Comment by douglas-reid** [comment]
There are two PRs that address this issue: #10880 (1.0.X) and #10839 (1.1). I've manually verified that the PRs do what we would expect, but having @mandarjog or even @zhu0516123 verify the fixes would be great.

**Comment by zhu0516123** [comment]
@mandarjog @douglas-reid 
Will this issue be fixed in 1.0.6 or 1.1 release?

**Comment by douglas-reid** [comment]
@zhu0516123 as soon as the PRs are approved, they can be merged.

**Comment by clyang82** [comment]
@zhu0516123 I saw #10839 was merged so that release-1.1 will have this fix.

**Comment by duderino** [comment]
@douglas-reid is anything left to be done here?

**Comment by douglas-reid** [comment]
@duderino not that I know of at this time. we can always re-open if the issue persists.

**Comment by zhu0516123** [comment]
@douglas-reid @mandarjog 
Thank you. The mixer memory is not leaked in release-1.0.6.
