### ISSUE TITLE
Provide external client TLS certificate to services

### ISSUE THREAD

**Issue by somcsel** [istio/istio#10395]
**Describe the feature request**
Confgure the Ingress Gateway to set the data of the whole client TLS certificate in the `X-Forwarded-Client-Cert` (XFCC) HTTP header.

This feature can be achieved through [Envoy configuration](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/network/http_connection_manager/v2/http_connection_manager.proto#envoy-api-msg-config-filter-network-http-connection-manager-v2-httpconnectionmanager-setcurrentclientcertdetails).  #8263 previously enabled the Subject, together with the URI and/or DNS SubjectAlternativeName to be set in the XFCC header by both the ingress gateway and the sidecar inbound listener.

The amount of data added to each HTTP request is a consideration.  Envoy adds the certificate data to the header in percent-encoded PEM format.  This results in around a 2KB increase in request size for certificates using 2048 bit pubilc key with a SHA256 signature.  If this feature is accepted we should consider whether to make it configurable.

**Describe alternatives you've considered**
I wondered whether this might be possible to do via an EnvoyFilter, but I have not found a way.  If it is possible then that would be a good alternative.

**Additional context**
The rationale for this request is that our applications require access to the client certificate in order to extract data from the extensions.

**Comment by yangminzhu** [comment]
/cc @yangminzhu @diemtvu @rshriram 
Hi Steve, Is this issue suggesting to add a flag to make this feature configurable? Or is there anything you want to achieve through this issue? Thank you.

**Comment by somcsel** [comment]
Hi Yangmin, I would to extend the existing feature, so that the Ingress gateway adds the `Cert` field to the XFCC header.

If we take the below as an example of how it appears today:
```
X-Forwarded-Client-Cert: "Hash=aefe3f9f8006d07bb5fb273ee2e63994ad6dabeba4810034ca129abc6ffe527f;Subject=\"CN=httpbin.example.com,O=Dis,L=Springfield,ST=Denial,C=US\";URI=,By=spiffe://cluster.local/ns/default/sa/default;Hash=b35d1bdcd12cf52b0608eb4128f6d33cca7fca809b15e357dbc9de76e28d77a2"
```

I would like the whole of the external client's certificate to be present, such as:
```
X-Forwarded-Client-Cert: "Hash=aefe3f9f8006d07bb5fb273ee2e63994ad6dabeba4810034ca129abc6ffe527f;Cert=\"-----BEGIN%20CERTIFICATE-----%0AMIIE7TCCAtWgAwIBAgIDEAITMA0GCSqGSIb3DQEBCwUAMEoxCzAJBgNVBAYTAlVT%0AMQ8wDQYDVQQIDAZEZW5pYWwxDDAKBgNVBAoMA0RpczEcMBoGA1UEAwwTaHR0cGJp%0Abi5leGFtcGxlLmNvbTAeFw0xODEyMTIxMzMxMzhaFw0xOTEyMjIxMzMxMzhaMGAx%0ACzAJBgNVBAYTAlVTMQ8wDQYDVQQIDAZEZW5pYWwxFDASBgNVBAcMC1NwcmluZ2Zp%0AZWxkMQwwCgYDVQQKDANEaXMxHDAaBgNVBAMME2h0dHBiaW4uZXhhbXBsZS5jb20w%0AggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC5IHnUSVk0S8pGPsx7CsKZ%0AgT580NCVe5ePlIoe%2Bg%2FTxvxuFNJ3XX8kmiTSJLldchVjTEOKJ2WLJ6Qkkv8wHAee%0AwbcwK4m7biAsyEMps0hNinYOJkTWD920%2FkD7hQvNu%2FBPQt7FXJoYJQTLQsIDoIFa%0ApZrrDNV3x1%2FtYmu8ow%2B6tPova8OacbYjA6vIpA4iBCQMjhW5rRHEfntAoIOZ1VPo%0Ahok0LXxzKy6QkONDfgqBB%2FEiygIooHQc6n6UUpbEwUN1A9JcJ6OgP5MlHLXEnJT8%0AWzbWh2LmAkSv1egVCEzaT8scWeSXi9yHW09wsDhbhk1Nn7ZKJuAVtqN1uUWPKGNF%0AAgMBAAGjgcUwgcIwCQYDVR0TBAIwADARBglghkgBhvhCAQEEBAMCBaAwMwYJYIZI%0AAYb4QgENBCYWJE9wZW5TU0wgR2VuZXJhdGVkIENsaWVudCBDZXJ0aWZpY2F0ZTAd%0ABgNVHQ4EFgQUqQHjqejBH6200YHvLXiTZeM5IuMwHwYDVR0jBBgwFoAUQJVbtTkU%0A%2F6uibGPBcTFjyFC%2Fv%2B4wDgYDVR0PAQH%2FBAQDAgXgMB0GA1UdJQQWMBQGCCsGAQUF%0ABwMCBggrBgEFBQcDBDANBgkqhkiG9w0BAQsFAAOCAgEAZHU4n4z5gzlskO%2BXv5ci%0A5GFPKy%2BvVm1mtcThBqu7GTZUsD3hsRc%2FWxizLBskuuLz37C0XgwCTlA6hhi8SUWj%0ATL3JEt2MBVKXyXSSDjiJiS5Op28PoPkZwiKEka1Fv0z62m7jhljDgKFql1WpfkLp%0A2Fy5fjuSULEwOqZ5VEaORURwI5yta26duKljTFbIU72bA2qRWMWUffNuCPM1DP5k%0AFPe7oVafHxnZrPeB7fVZh1kfWhsEX0AONFdLhMJ%2BvmpAQFU9Qja3iaSWqdBiOO%2BS%0A6yfPdXuSC2KIwIT85jgEuTgIp%2FNSrC4a%2BkSdelEyqSTxG0b%2Fl5JnQlqrcQMHii42%0Aun8nZv5edPWZYXSFviCgHLez9PogJ0VMZd05pHxpFXgZ9xzqgQsoWQ%2FdbjhbbR4q%0A6i1HIyfzBcrxY9YHrtG%2FeOjcpw96PjWX%2BQxeyYMg1YaNTkgfMtHySrM%2B8PCLrYYm%0A3t6bWN%2FTYyaLuEy8RhuPopQUhPi2mKLUTuiHcPmq%2FMDSr%2FVwzap1sPDRhmTfI5Ma%0AxNf5TCS3kFEmdDvRJbxDrsEP19FeO3dlhRaFUwVIkwe0%2B%2FRV8q4lfwVzjAY1WLFO%0AKK8NqlB8PNAdm64ZlzncRtHVeNyUfoKM8EuAHCJ8pMGUleoPj0bvd8dxgQQ%2F2pFA%0AhXvn%2FqjFxT8VdD83IrUE7T4%3D%0A-----END%20CERTIFICATE-----%0A\";Subject=\"CN=httpbin.example.com,O=Dis,L=Springfield,ST=Denial,C=US\";URI=,By=spiffe://cluster.local/ns/default/sa/default;Hash=b35d1bdcd12cf52b0608eb4128f6d33cca7fca809b15e357dbc9de76e28d77a2"
```

I queried whether to make this addition configurable because it adds an overhead to each request received from external clients using mTLS.  The percent-encoded PEM certificate can be large, around 2kB.

I created PR https://github.com/istio/istio/pull/10394 to add the `Cert` field.
