### ISSUE TITLE
Istio yaml structure

### ISSUE THREAD

**Issue by absc6** [istio/istio#10429]
**Documentation for yaml structure configuration**
For new users, it can be useful to have a yaml structure definition available. This will claritify about each attribute(option/mandatory/functionality/restriction etc).

**Comment by hzxuzhonghu** [comment]
I am not sure if `istio.io/api/networking/v1alpha3` is what you want.

**Comment by absc6** [comment]
Thanks @hzxuzhonghu for the information, I am using [doc](https://istio.io/docs/reference/config/istio.networking.v1alpha3/)
However, I was interested, if we had schema-validator for the yaml file to automate/validate configuration before execution.

**Comment by esnible** [comment]
The code to validate Istio CRDs is present in `istioctl` but it is only executed as part of `istioctl create`.  (There is an `istioctl validate` but it does something different).

It should be straightforward to add a `--dry-run=true` flag to allow `kubectl create` to be used to validate .yaml.

**Comment by ayj** [comment]
[istioctl validate](https://preliminary.istio.io/docs/reference/commands/istioctl/#istioctl-validate) does what you want here. This runs the same code that `istioctl create` (deprecated) does. 

`--dry-run` for admission webhooks is already supported in k8s 1.12+ (see https://github.com/kubernetes/kubernetes/pull/66936).

**Comment by absc6** [comment]
Is it version dependent, I am using **1.0.3** and getting below error.
```
Error: unknown command "validate" for "istioctl"
Run 'istioctl --help' for usage.
```

Also, istioctl create --dry-run is giving error:
```
$istioctl create -f sample.yaml --dry-run=true
Error: unknown flag: --dry-run
```
