### ISSUE TITLE
zipkin delays uninstall (low)

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#1042]
if I install in a namespace and then delete the namespace

```
ldemailly-macbookpro:istio ldemailly$ kubectl get -n e2e all
NAME                         READY     STATUS        RESTARTS   AGE
po/zipkin-2051103938-d8xgz   1/1       Terminating   0          41d
```

zipkin shows up as the last pod for a long time (minutes compared to the others going away almost immediately)

**Comment by ayj** [comment]
This seems to be fairly reproduceable (see steps below). I see `Killing container with id docker://zipkin:Need to kill Pod` in the pod description after termination. Possibly an issue with the zipkin image itself being unkillable which forces kubernetes to delete after some timeout?

```bash
kubectl create namespace istio-system
kubectl  -n istio-system create -f install/kubernetes/addons/zipkin.yaml
kubectl delete namespace istio-system
kubectl -n istio-system get pods
```

**Comment by douglas-reid** [comment]
I'm not sure what the action is here. the zipkin image is `docker.io/openzipkin/zipkin:latest`. @ldemailly, what is your suggestion for resolution?

**Comment by ldemailly** [comment]
I guess we can report it to them or check if there is a flag we're supposed to pass and we aren't ?

or switch to jaeger for that part too ?

**Comment by douglas-reid** [comment]
Can we close this now? I believe we are on jaeger now.

**Comment by ldemailly** [comment]
sure, I haven’t verified it is better with jaeger but let’s assume it is and open an issue if not
