### ISSUE TITLE
Mixer client: mixc should send valid attribute encodings when attribute vocabulary is available

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#10434]
The contract between Mixer client and Mixer is they agree on a vocabulary and the client will always send correctly encoded attributes across the wire. 

At present `mixc` makes the user specify attribute types on the command line. There is an auto detect feature that detects type based on attribute value.

Proposal: When `--attribute-manifest` is specified, mixc must encode attribute based on the declared types.

This protects the user inadvertently sending incorrectly encoded attributes via mixc.

**Comment by kyessenov** [comment]
Alternative proposal:
mixs should expose a reflection API that allows mixc to query manifests from mixs. That would eliminate a dependency on the config from mixc.
