### ISSUE TITLE
Istio as a Front proxy for an external service

### ISSUE THREAD

**Issue by rayepudi** [istio/istio#10441]
We have a requirement where the istio acts as a front proxy to connect to an external service. And the same front proxy should act as the entry point for istio service mesh.

**Comment by hzxuzhonghu** [comment]
You can do that using egress gateway. ref: https://istio.io/docs/examples/advanced-egress/egress-gateway/#define-an-egress-gateway-and-direct-http-traffic-through-it

**Comment by rayepudi** [comment]
can we monitor the health checks and failover for the external service

**Comment by rayepudi** [comment]
@hzxuzhonghu we're not able to connect to the external service using the  egress gateway mentioned above. while executing the service entry through sleep.yaml config, It's throwing the error "command terminated with exit code 6".  Can you please help

**Comment by hzxuzhonghu** [comment]
can  you show your config here?

**Comment by rayepudi** [comment]
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: cnn
spec:
  hosts:
  - myserver_hostname
  ports:
  - number: 10080
    name: http-port
    protocol: HTTP

kubectl exec -it $SOURCE_POD -c sleep -- curl -sL -o /dev/null -D - http://myserver_hostname/resource

**Comment by rayepudi** [comment]
`apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: cnn
spec:
  hosts:
  - myserver_hostname
  ports:
  - number: 80
    name: http-port
    protocol: HTTP`

kubectl exec -it $SOURCE_POD -c sleep -- curl -sL -o /dev/null -D - http://myserver_hostname/resource

**Comment by vadimeisenbergibm** [comment]
Can you provide the log and the Envoy's configuration:
```
kubectl logs $SOURCE_POD -c istio-proxy
bin/istioctl proxy-config listeners $SOURCE_POD -o json > listeners.json
bin/istioctl proxy-config routes $SOURCE_POD -o json > routes.json
bin/istioctl proxy-config clusters $SOURCE_POD -o json > clusters.json
bin/istioctl proxy-config endpoints $SOURCE_POD -o json > endpoints.json
```

**Comment by rayepudi** [comment]
can you please share me the configuration to configure the istio as front proxy for a external service present in another server. and the commands to connect to the external service. Thanks

**Comment by vadimeisenbergibm** [comment]
@rayepudi I have added a PR with an example: https://github.com/istio/istio.io/pull/3180

**Comment by vadimeisenbergibm** [comment]
@rayepudi Note that the external services will become available from the pods in the mesh as well. If you need to disable access from the pods in the mesh to the external services, add a section to the VirtualServices with the gateway `mesh`, that will route traffic to `127.0.0.1`. This will make the ingress gateway route the traffic to the external services correctly, while the sidecar proxies in the mesh will route to the local host, effectively blocking the traffic from the sidecar proxies.

**Comment by vadimeisenbergibm** [comment]
@rayepudi I have updated the PR to block the access to external services from inside the mesh, only access from the ingress gateway is allowed.

**Comment by salla2** [comment]
> #10537
@vadimeisenbergibm @rayepudi i'm looking for external service health check . My external service is subset of ip's  and when we hit external service it should route to those ip's which passed health check alone. Is this functionality can be configurable when we have service entry in istio? Any idea or suggestions please

**Comment by howardjohn** [comment]
It doesn't look like this is any work to be done here, as mentioned this is supported with egressgateway which is documented on istio.io. 

If there are still any problems please feel free to open another issue, but there hasn't been any activity on this and doesn't seem like there are any action items

**Comment by desek** [comment]
For those stumbling into this in future. This works with Istio 1.12.1 and only an ingress gateway.

https://gist.github.com/desek/afa916488ba0d6ee52da9d7687b11992
