### ISSUE TITLE
Pilot complaints outbound listeners conflicts and drop the traffics

### ISSUE THREAD

**Issue by zhaohuabing** [istio/istio#10456]
**Describe the bug**
Pilot complaints outbound listeners conflicts when there're HTTP and headless TCP services listen on the same port or multiple headless TCP services on the same port. And the conflicted TCP traffics are dropped by envoy, resulting in application errors.

The current assumption is that TCP service should have a unique VIP, otherwise service ports must be deliberately allocated to avoid conflicting with each other, which is not always practical in production. 

In fact, most of the services in my application are HTTP/REST,  I don't really need to manage the TCP service within Istio,  even I want to, the default TCP services behaviour of Istio/Envoy may have problems. For example, the LB for some TCP services need to be handled by the code in the application layer(client lib) rather than the mesh layer because multiple instances have their own state so they can't be randomly assigned to clients.  So it's best just to pass through the TCP request to its original destination in this situation, but right now conflicted TCP requests are simply dropped by Envoy.

Pilot log:

```
        "pilot_conflict_outbound_listener_http_over_current_tcp": {
            "0.0.0.0:80": {
                "proxy": "172.168.20.2.service.consul",
                "message": "Listener=0.0.0.0:80 AcceptedHTTP=apistore-api.service.consul,oki-ui.service.consul,apiconsole-api.service.consul,apiconsole.service.consul,vcp-vba-iui.service.consul,apiconsole-north.service.consul,apiconsole-backup.service.consul,apistore.service.consul,ssm.service.consul RejectedTCP=op-proxy.service.consul HTTPServices=9"
            },
            "0.0.0.0:9099": {
                "proxy": "172.168.20.2.service.consul",
                "message": "Listener=0.0.0.0:9099 AcceptedHTTP=cslogstash-manager-opcs.service.consul,cskafka-manager-opcs-service.consul,cses-manager-opcs.service.consul RejectedTCP=zookeeper-broker-opcs.service.consul HTTPServices=3"
            }
        },
```

**Expected behaviour**
Pilot should develop a mechanism to allow multiple headless TCP services and HTTP services listening on the same port, and pass through the TCP services to its original destinations.

We can add a filter listener to split the HTTP and TCP traffics which are sent to the same envoy listening port, and let TCP traffics handled by a passthrough cluster. By this means, the TCP traffic can be sent to its original destination instead of being dropped. In order to accomplish this, we also need to create an Envoy filter listener to inspect the protocol of the request (HTTP or plain TCP/Other application protocols Istio don‘t understand).

We have already implemented a similar mechanism when integrating Istio with our product, and would love to see it become an official feature of Istio.

Below envoy configuration is what we are using now, it demonstrates the proposed solution for the conflicting TCP services. 
```
{
      "listener": {
      "name": "0.0.0.0_1102",
      "address": {
       "socket_address": {
        "address": "0.0.0.0",
        "port_value": 1102
       }
      },
	  "listener_filters": [
       {
       // A http_inspector filter listener is used to tell 
       // wether the request is HTTP  or not
        "name": "envoy.listener.http_inspector" 
       }
      ]
      "filter_chains": [
       {
        "filter_chain_match": {
         // Right now we reuse server_name to convey the Protocol, 
         // it should be changed to a more appropriate property (need envoy suppport)
         "server_names": [
          "HTTP-REQUEST"
         ]
        },
        "filters": [
         {
          "name": "envoy.http_connection_manager",
	      ......
           //HTTP request is sent to router for futhur processing
           "route_config_name": "1102", 
         }
         ]
       },
       {
        "filter_chain_match": {
         // Right now we reuse server_name to convey the Protocol, 
         // it should be changed to a more appropriate property (need envoy suppport)
         "server_names": [ 
          "PLAIN-TCP-REQUEST"
         ]
        },
        "filters": [
         {
          "name": "envoy.tcp_proxy",
          "config": {    
           // We can't do much to TCP request, 
           //pass it to its original destination should be good enough now 
           "stat_prefix": "PassthroughCluster",
           "cluster": "PassthroughCluster"
          }
         }
        ]
       }
      ],
```

**Steps to reproduce the bug**
Install Istio with Consul.
Register HTTP and multiple headless TCP services which are listening on the same port.

**Version**
Istio 1.0.0

**Installation**
Consul

**Environment**
Ubuntu 16.04

**Cluster state**
Application deployed and managed in kubernetes but using Consul as the service registry.

**Comment by rajusharma** [comment]
I am also facing similar kind of issue
**Scenario1**
- There is headless serviceB exposing port 10000 using grpc protocol
- ServiceA is calling serviceB using client-side loadbalancing over grpc
- Envoy config in serviceA pod looks like below (will list only outbound listener )
```
{
     "version_info": "2019-06-18T07:57:06Z/2458",
     "listener": {
      "name": "0.0.0.0_10000",
      "address": {
       "socket_address": {
        "address": "0.0.0.0",
        "port_value": 10000
       }
      },
      "filter_chains": [
       {
        "filters": [
         {
          "name": "envoy.http_connection_manager",
          "config": {
           "access_log": [],
           "http_filters": [
            {
             "name": "envoy.cors"
            },
            {
           ........
           ..........
```
**Scenario2**
- Scenario1 services are already existing
- Now i create a serviceC exposing same port 10000 using https protocol (Or just name the service port with random string)
- Envoy config in serviceA pod is changed like below (will list only outbound listener )
```
{
     "version_info": "2019-06-18T07:38:55Z/2453",
     "listener": {
      "name": "0.0.0.0_10000",
      "address": {
       "socket_address": {
        "address": "0.0.0.0",
        "port_value": 10000
       }
      },
      "filter_chains": [
       {
        "filter_chain_match": {
         "server_names": [
          "xxxx-xxxx.xxx"
         ]
        },
        "filters": [
         {
          "name": "envoy.tcp_proxy",
          "config": {
           "stat_prefix": "outbound|10000||xxx-hs.xxx.svc.cluster.local",
           "cluster": "outbound|10000||xxx-hs.xxx.svc.cluster.local"
          }
         }
        ]
       },
       {
        "filter_chain_match": {},
        "filters": [
         {
          "name": "envoy.tcp_proxy",
          "config": {
           "stat_prefix": "PassthroughCluster",
           "cluster": "PassthroughCluster"
          }
         }
        ]
       }
      ],
```

**Expected behavior**
Filter chain with filter "envoy.http_connection_manager" should exist in scenario2, basically there should be 3 filter chains(1 which is scenario1 and 2 from scenario2)
