### ISSUE TITLE
Consider adding polling mode to istio.io/pkg/filewatcher

### ISSUE THREAD

**Issue by ayj** [istio/istio#10469]
istio.io/pkg/filewatcher uses ionotify to watch for local filesystem changes. This works fine under normal conditions. However, there might be cases where OS ionotify limits are reached, e.g. local development, pod on large nodes. This leads to errors of the variety: "unable to watch ..., no space left on device". 

One mitigation is to add a fallback polling mode to istio.io/pkg/filewatcher when ionotify fails. 

We should also ensure all Istio code is using istio.io/pkg/filewatcher and not rolling their own ad-hoc file watching code.

**Comment by qinqon** [comment]
Will try to help here, what's the most straightforward way to reproduce this?
