### ISSUE TITLE
Listentry should be extended to accept also values of type IP_ADDRESS

### ISSUE THREAD

**Issue by dimakow** [istio/istio#10468]
**Describe the feature request**
In https://istio.io/docs/tasks/policy-enforcement/denial-and-list/ it is described how mixers listchecker is used in combination with listentry to do simple string based checks against a white/blacklist. I think that logic is aiming primarily for envoy requests setup with HTTP filter (and i.e. request.header keys).

If i've setup envoy with Network filter and i want to do white/blacklist with i.e. sourceIps i could not do that because listentry explicitly expects the Value to be of type STRING (https://github.com/istio/istio/blob/master/mixer/template/template.gen.go#L3949) whereas source.ip is currently always of type IP_ADDRESS.

**Describe alternatives you've considered**
I think either listentry can be extended or a new template can be implemented that would process IP_ADDRESS and transform it to STRING for listchecker to check against.

This would also give istio users, who are using envoy network filters a possibility to enforce whitelist/blacklists on their requests.
 
Please let me know what you think.

**Comment by douglas-reid** [comment]
I think this has been done now and is working on `release-1.1` (thanks, @gargnupur !). Marking as closed.

**Comment by craigske** [comment]
Just in case others end up here looking for the enum IP_ADDRESS to work, it's actually IP_ADDRESSES

See: https://github.com/istio/istio/blob/master/mixer/adapter/list/config/config.pb.go#L74
