### ISSUE TITLE
v1.1.0: TCP weighting does not allow for a 0-100 split - "positive weight is required".

### ISSUE THREAD

**Issue by darrencraig** [istio/istio#10467]
I will require TCP weighting in the near future, a feature which has been added to the upcoming 1.1 release. (https://github.com/istio/istio/commit/aaaf0a3addfbdbc9022b13a002225910e82874d4) - (Thanks for the work so far @venilnoronha!)

I have been testing v1.1.0 locally and noticed that you cannot use '0' as a valid weighting value and therefore cannot split the traffic 100/0.

![100 Percent Weighting](https://user-images.githubusercontent.com/1321892/49938290-5b689280-fed1-11e8-94bc-1dd5894835a8.png)

This results in:

`Error from server: error when applying patch:
admission webhook "pilot.validation.istio.io" denied the request: configuration is invalid: 1 error occurred:
positive weight is required`

Istio version 1.1.0 (daily build - release-1.1-20181202-09-15)
Minikube version: v0.30.0
Kubectl version: v1.10

I would try to help myself, but I know nothing about Go! Sorry!

Thanks in advance!

**Comment by venilnoronha** [comment]
Can you just drop the `destination` with `subset: canary`?

**Comment by darrencraig** [comment]
Yes, but I wasn't sure if that was consistent with the way that the http weighting worked (you can balance 100/0 on http) and it might be more awkward for updating in automated pipelines?

Happy to take your advice - I'm still getting to grips with the system and in the midst of updating our own workflow, so I'm certainly not the authority on this!

Thanks!

**Comment by venilnoronha** [comment]
Agree that that behavior needs to be more consistent. The difference between HTTP and TCP routing currently is that the weights in HTTP need to sum up to 100, while TCP doesn't have such a restriction.

**Comment by hzxuzhonghu** [comment]
opened #10479 to fix
