### ISSUE TITLE
Allow prometheus scraper to fetch port outside of sidecar umbrella

### ISSUE THREAD

**Issue by jotak** [istio/istio#10487]
**Describe the bug**

Following discussion here: https://groups.google.com/forum/#!topic/istio-dev/rG2Y7wjfTIg

If a pod exposes prometheus metrics on non-secure port where permissive mode isn't active (for instance, because the port isn't declared as `containerPort`... or any other reason), then the current prometheus scraping configuration will fail to collect that data.

A reason to have such a configuration is to prevent telemetry of the service mesh being impacted by prometheus itself scraping pod metrics.

**Expected behavior**

Allow scraper to collect metrics from ports that are not under the sidecar umbrella. Ex: we could have the common annotation "prometheus.io/scheme" being read here to determine if we want to force usage of non-secure job "kubernetes-pods"

**Steps to reproduce the bug**

- Setup a deployment that exposes prometheus metrics on a port X that is *not* declared as `containerPort`, and without ssl.
- Setup annotations `prometheus.io/scrape: "true"` and `prometheus.io/port: "X"` on pod/template Spec
- Deploy with istio sidecar
- Check `$prom_url/targets` => pod appears under job `kubernetes-pods-istio-secure`, and fails to provide metrics

**Version**

Istio 1.0.4, Kube 1.13.0
Issue appeared with PR #8760

**Comment by jotak** [comment]
@mandarjog I will submit a PR about that

**Comment by douglas-reid** [comment]
Did the issue here end up being that we needed to reboot prometheus, as the certs weren't ready at startup time and prom never rechecks?  @mandarjog @bianpengyuan

**Comment by jotak** [comment]
@douglas-reid not sure if I'm answering your question, but I rebooted prometheus several times (while I was trying different things in the config map) and it didn't fix anything, I think it's really caused by the new config map relabeling as pointed in my PR
