### ISSUE TITLE
Restrict RBAC permission to the needed ones

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#1048]
Reported in istio/issues#89.

Affects pilot, it should not use *, only required permission (get, list, watch) for pods etc. Separate CRDs, if create is needed.

Need to check all components.

**Comment by ldemailly** [comment]
see also #1375 for not needing crd create perma

**Comment by andraxylia** [comment]
istio/pilot#1375 is for changes in code, if they need to be done.

This is about cleaning up RBAC and separating the CRDs from the rest.

**Comment by sbezverk** [comment]
@andraxylia since I do not know  the code structure yet, appreciate if you could give me some pointers in the code it will save a bit of time. I want to look into it, if nobody else is actively working on it.

**Comment by andraxylia** [comment]
@sbezverk thanks for helping.

In general, this PR is about not giving * permissions to a role, but explicitly state them (similar to what Android does when installing an app ).

For pilot, one of the offending line is here, it gives * permissions on pods, endpoints, services, where in fact it only needs get, watch, list:
https://github.com/istio/istio/blob/master/install/kubernetes/templates/istio-rbac-beta.yaml.tmpl#L28

I see the CRDs are already on a separate section, pilot does need to create them, we should use create, update, delere, get, watch, list.

Unclear if pilot still needs to get, list, watch secrets, I do not see usages in the code  @kyessenov.

Sidecar permissions need to be highly scrutinized, since it is more vulnerable than control plane components.

One way to go is to change them and check the logs there are no permission complains. Another one is to find usages of an k8s client Interface, for instance SecretInterface.Watch(): 

https://github.com/istio/istio/blob/master/security/pkg/pki/ca/controller/secret.go#L104

Any incremental change is good.

**Comment by andraxylia** [comment]
Had a look the RBAC template and is cleaner after several commits. I will close this issue.
