### ISSUE TITLE
Provide istioctl via homebrew

### ISSUE THREAD

**Issue by VeitSanner** [istio/istio#10484]
**Describe the feature request**
It would be good to have a homebrew formula available for istioctl which takes care of installing, updating the istioctl binaries.

**Describe alternatives you've considered**
Currently, the only way to install istioctl on macOS is to download the binary and copy it to a directory which is available via the PATH variable.

**Additional context**
N/A

**Comment by linsun** [comment]
seems a good feature to have it handy :). @esnible / @mbanikazemi could you look into this?

**Comment by esnible** [comment]
To contribute to Homebrew we will need to follow the instructions at https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md#add-a-new-formula-for-foo-version-234-from-url .  This means getting a PR approved for https://github.com/Homebrew/homebrew-core .

**Comment by murarisumit** [comment]
@linsun can I try it out, I recently made brew packages for https://github.com/StackExchange/dnscontrol.

**Comment by linsun** [comment]
Awesome, thanks @murarisumit pls keep us posted.

**Comment by igas** [comment]
I can help here from brew side, I made an attempt before, but we need to build it not in docker using something like `go build`.

**Comment by esnible** [comment]
@igas It is easy to build the command line.  Just clone and `make istioctl`.  The tests also get run.  I can help with any questions about how to build or where to get pre-built binaries.

**Comment by murarisumit** [comment]
istioctl is available via homebrew now.

**Comment by rvennam** [comment]
I tried brew install/reinstall/uninstall istioctl and it all appears to work well.  

FYI - there was a discussion in the past regarding brew packaging, and pulling down of the yaml files required to install istio into your cluster using istioctl:
https://groups.google.com/forum/#!topic/istio-dev/fnlk9G37auU

**Comment by VeitSanner** [comment]
Works on my end as well. Thanks for the fast solution.

**Comment by murarisumit** [comment]
@rvennam I see that version issue is there, as it is on discussion page.

Will try and look how to populate that info during build, meanwhile if anyone has pointers about how to do that, it would be really helpful.

**Comment by esnible** [comment]
@murarisumit _istioctl_ version is baked into the binary.  The script _bin/get_workspace_status.sh_ uses the environment variables `VERSION` and `BUILD_GIT_REVISION` to create some flags, then _bin/gobuild.sh_ uses the `-ldflags` to bake them in.

The recipe should set BUILD_GIT_REVISION to the GIT revision of https://github.com/istio/istio .  I don't know if the VERSION appears in the source code.  If not perhaps use the branch -- if Homebrew is using the _release-1.0.5_ branch, then set VERSION to `1.0.5` or `release-1.0.5`.

**Comment by murarisumit** [comment]
@esnible thanks for help, really helpful pointers. H

omebrew generally discourages to build from git repo or they prefer from source archive. As I see here https://github.com/istio/istio/blob/master/bin/get_workspace_status.sh#L17, it doesn't check for environment variables and directly gets it from git repo. Pardon me for naive-ness, if I have missed something here.

Thanks to your reference, found `ISTIO_VERSION` variable which is read from environment and directly updates the version file. Got this putting `ISTIO_VERSION` variable in environment

```
 $ > istioctl version
Version: 1.0.5
GitRevision: unknown
User: sumit@Sumits-MacBook-Pro-2.local
Hub: docker.io/istio
GolangVersion: go1.11.4
BuildStatus: Modified
```
