### ISSUE TITLE
ISTIO mesh expansion:  Failed to connect to productpage.default.svc.cluster.local port 9080: Connection timed out on External VM

### ISSUE THREAD

**Issue by SrinivReddy** [istio/istio#10488]
I have implemented ISTIO mesh expansion, and I am trying to access bookinfo app from External  VM,
On External VM

curl -v -w "\n" http://productpage.default.svc.cluster.local:9080/api/v1/products/0/ratings
*   Trying xx.xx.xx.25...
* connect to xx.xx.xx.25 port 9080 failed: Connection timed out
* Failed to connect to productpage.default.svc.cluster.local port 9080: Connection timed out
* Closing connection 0

curl: (7) Failed to connect to productpage.default.svc.cluster.local port 9080: Connection timed out

On K8s(ISTIO)
NAME          TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
productpage   ClusterIP   xx.xx.xx.25    <none>        9080/TCP   27h

**Comment by morvencao** [comment]
Can your VM access pod IP and service IP in the cluster?

**Comment by devops083** [comment]
HI @morvencao , yes app pod ip is not able access from External VM.

**Comment by morvencao** [comment]
Since you are calling pods and services in cluster from external VM, you should setup connection from external VM to pods and services.

**Comment by devops083** [comment]
I am uable to connect pod endpoints

**Comment by morvencao** [comment]
@devops083 Depends on your case, if you just call service on external VM from cluster, you don't need to network connect pods from External VM.

**Comment by devops083** [comment]
@morvencao I want to access application which is running on pod from external VM,    seems like pod endpoints are not acceesible from VM.

**Comment by devops083** [comment]
I have implememted this in AWS, In AWS , UDP loadbalancer is not supporting, Is there any other way to expose kube-dns.
