### ISSUE TITLE
Pilot support for incremental MCP and ServiceEntries

### ISSUE THREAD

**Issue by costinm** [istio/istio#10497]
As discussed in #10220, MCP and ADS protocols allow endpoints ( and the equivalent ServiceEntry) to be sent incrementally, with the server sending updates with only the clusters(services) that have changed.

The pilot side changes are relatively small - I can take care of them ( unless Nino is willing to do them to get rid of the diff for CF ).

The main gap is having MCP server ( galley, CF or a small standalone/dedicated server dealing with endpoints only ) that sends only the ServiceEntries that changed - and a lot of testing and product-ionization.   If the tests go well we can even use this for the primary cluster - but I think it's safer to have it as an alternative for MC.

Let's try to sync up - I think this is doable in the 1.1 timeframe.

**Comment by Nino-K** [comment]
Just going to throw the related PRs in here: https://github.com/istio/api/pull/741 and https://github.com/istio/istio/pull/10635

**Comment by jasminejaksic** [comment]
What's the ETA? And is this a blocker for launching 1.1?

**Comment by nmittler** [comment]
Closing this as a dup of #10589
