### ISSUE TITLE
Integrate consul as config registry

### ISSUE THREAD

**Issue by andrewshan** [istio/istio#10503]
**Describe the feature request**
Istio version: 1.0.3
currently we are using consul kv as our central config registry. Hence the istio pilot 1.0.3 only support file, kubernetes crd, kubernetes configmap as config registry. 
So we want to add consul as config registry as it has been service registry in pilot.

**Describe alternatives you've considered**
NA. 

**Additional context**
NA.

**Comment by andrewshan** [comment]
@ayj hello, ayj. I have the code for consul registry, if you don't mind, you can assign the issue to me ^_^

**Comment by yangdihangN** [comment]
Where can I get more public information about mcp? We want to use eureka as one of the istio's registry to be compatible with spring-cloud based microservices. 
Or can you give me enough permission to view "Pilot Decomposition"? @ayj

**Comment by ayj** [comment]
See https://goo.gl/EJu5hg for a high-level overview of MCP. You can get access to that doc and the pilot decomposition doc by joining the istio-team-drive-access account per the instructions at https://istio.io/about/community.

**Comment by Nino-K** [comment]
@yangdihangN you can build your own MCP server using the [mcp pkg](https://github.com/istio/istio/tree/master/pkg/mcp) if your requirements are outside K8s and Cloudfoundry.

**Comment by ozevren** [comment]
andrewshan@, yangdihangN@, as Nino and Jason mentioned, we are moving towards an MCP based solution for our Istio components. I am closing this issue. Feel free to reopen if you think there is actionable work that can be done within the context of Istio.
