### ISSUE TITLE
Getting installation error with isito on Kubernetes with Docker for Windows

### ISSUE THREAD

**Issue by VenkateshSrini** [istio/istio#10502]
**Describe the bug**
I'm trying to install Istio on kubernetes that comes with Docker for Windows. I find that I'm getting the following error

> no matches for kind "Gateway" in version "networking.istio.io/v1alpha3"

**Expected behavior**
Istio should get installed with out any issues

**Steps to reproduce the bug**
1) Install latest version of docker for windows
2) Download Istio and then install istio-demo-auth.yaml using kubectl app -f
**Version**
Istio 1.0.4

**Installation**
{{ Please describe how Istio was installed }}

**Environment**
Windows 10

**Comment by rvennam** [comment]
Can you share the steps you used to install Istio? Did you install the CRD's first and then run apply the istio-demo-auth.yaml ? 
https://istio.io/docs/setup/kubernetes/quick-start/#installation-steps
Any errors during the two install steps?

**Comment by linsun** [comment]
The error means CRD is missing.  Pls ensure it is cleaned properly then reinstall it.

**Comment by VenkateshSrini** [comment]
Thanks Guys. Let me try it once please. will reply you by EOD IST

**Comment by VenkateshSrini** [comment]
Thanks it worked
