### ISSUE TITLE
How to expose kube-dns in k8s

### ISSUE THREAD

**Issue by devops083** [istio/istio#10511]
Hello,

I am implemeting ISTIO-mesh expansion in kubernetes (AWS)
as part of this I need to expose Kube-dns service.

so I tried to created a kube-dns service with type: LoadBalancer but an unable to get external IP its in pending state.

apiVersion: v1
kind: Service
metadata:
name: dns-ilb
namespace: kube-system
labels:
k8s-app: kube-dns
spec:
type: LoadBalancer
ports:

port: 53
protocol: UDP
selector:
k8s-app: kube-dns
kubectl get svc -n kube-system
NAME TYPE CLUSTER-IP EXTERNAL-IP PORT(S) AGE
dns-ilb LoadBalancer xx.xx.xx.xx pending 53:30749/UDP 28m

so why dont we expose kube-dns with type: LoadBalancer????

**Comment by morvencao** [comment]
Your cluster don't support `LoadBalancer` type service.
Maybe you can try [metalLB](https://metallb.universe.tf/) if you're in test env.

**Comment by devops083** [comment]
@morvencao , I am using AWS servers with loadbalancer enabled. for other services like istio-ingressgateway i have got loadbalancer for kube-dns only i am not able to get external IP.

**Comment by morvencao** [comment]
@morvencao LoadBalancer annotation depends on your cloud provider. Not very clear with AWS.

**Comment by devops083** [comment]
@morvencao , Protocol UDP not supporting for Loadbalancer in AWS.
