### ISSUE TITLE
go test -v ./tests/integration2/examples/pilot does not work

### ISSUE THREAD

**Issue by incfly** [istio/istio#10524]
**Describe the bug**
`go test -v ./tests/integration2/examples/pilot` does not work

2018-12-17T19:22:19.597334Z     info    CI      Test Framework runtime settings:
Environment: native
TestID:      pilot_test
RunID:       pilot-test-b9cc580e350b49afbb0e
NoCleanup:   false
WorkDir:     /tmp/pilot-test-b9cc580e350b49afbb0e

=== RUN   TestHTTP
2018-12-17T19:22:23.931363Z     info    Awaiting for config store sync...
2018-12-17T19:22:23.931444Z     info    Starting runtime config watch...
2018-12-17T19:22:23.931526Z     info    Built new config.Snapshot: id='0'
2018-12-17T19:22:23.931578Z     info    Cleaning up handler table, with config ID:-1
2018-12-17T19:22:23.931663Z     info    Built new config.Snapshot: id='1'
2018-12-17T19:22:23.931708Z     info    Cleaning up handler table, with config ID:0
2018-12-17T19:22:23.931809Z     info    Starting monitor server...
2018-12-17T19:22:23.933816Z     info    parsed scheme: ""
2018-12-17T19:22:23.933832Z     info    scheme "" not registered, fallback to default scheme
2018-12-17T19:22:23.933921Z     info    mesh networks configuration not provided
--- FAIL: TestHTTP (4.34s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x18fb7f6]

goroutine 86 [running]:
testing.tRunner.func1(0xc00033e600)
        /usr/lib/google-golang/src/testing/testing.go:792 +0x387
panic(0x21348a0, 0x3e25f70)
        /usr/lib/google-golang/src/runtime/panic.go:513 +0x1b9
istio.io/istio/pilot/pkg/bootstrap.(*Server).grpcServerOptions(0xc002d40640, 0x0, 0xc002c22030, 0xc003195620, 0xc00059de60)
        /usr/local/google/home/jianfeih/workspace/golang/src/istio.io/istio/pilot/pkg/bootstrap/server.go:1159 +0xc6
istio.io/istio/pilot/pkg/bootstrap.(*Server).initGrpcServer(0xc002d40640, 0x0)
        /usr/local/google/home/jianfeih/workspace/golang/src/istio.io/istio/pilot/pkg/bootstrap/server.go:1055 +0x35
istio.io/istio/pilot/pkg/bootstrap.(*Server).initDiscoveryService(0xc002d40640, 0xc002c2e000, 0x0, 0x0)
        /usr/local/google/home/jianfeih/workspace/golang/src/istio.io/istio/pilot/pkg/bootstrap/server.go:950 +0x249
istio.io/istio/pilot/pkg/bootstrap.NewServer(0x24847e2, 0x2, 0x24847e2, 0x2, 0x24847e2, 0x2, 0x24847e2, 0x2, 0x0, 0x2492e7b, ...)
        /usr/local/google/home/jianfeih/workspace/golang/src/istio.io/istio/pilot/pkg/bootstrap/server.go:254 +0x256
istio.io/istio/pkg/test/framework/runtime/components/pilot.(*nativeComponent).Start(0xc000faf600, 0x2805220, 0xc0001f8400, 0x2487bf2, 0x6, 0x0, 0x0)
        /usr/local/google/home/jianfeih/workspace/golang/src/istio.io/istio/pkg/test/framework/runtime/components/pilot/native.go:112 +0x2fd
istio.io/istio/pkg/test/framework/runtime/dependency.(*Manager).requireComponent(0xc0002054a0, 0x2486fb5, 0x5, 0x1, 0x0, 0x0, 0x3e2bfc0, 0x2, 0x2, 0x2485836, ...)
        /usr/local/google/home/jianfeih/workspace/golang/src/istio.io/istio/pkg/test/framework/runtime/dependency/manager.go:183 +0x9ca
istio.io/istio/pkg/test/framework/runtime/dependency.(*Manager).Require(0xc0002054a0, 0x2485836, 0x4, 0x3e2c000, 0x2, 0x2, 0x2, 0x2)
        /usr/local/google/home/jianfeih/workspace/golang/src/istio.io/istio/pkg/test/framework/runtime/dependency/manager.go:95 +0x440
istio.io/istio/pkg/test/framework/runtime/dependency.(*Manager).requireComponent(0xc0002054a0, 0x248596a, 0x4, 0x0, 0x0, 0x0, 0x3e2c000, 0x2, 0x2, 0x2485836, ...)
        /usr/local/google/home/jianfeih/workspace/golang/src/istio.io/istio/pkg/test/framework/runtime/dependency/manager.go:165 +0x7cc
istio.io/istio/pkg/test/framework/runtime/dependency.(*Manager).Require(0xc0002054a0, 0x2485836, 0x4, 0xc0000e3c90, 0x1, 0x1, 0xc0005ad230, 0x3d34630)
        /usr/local/google/home/jianfeih/workspace/golang/src/istio.io/istio/pkg/test/framework/runtime/dependency/manager.go:95 +0x440
istio.io/istio/pkg/test/framework/runtime.(*contextImpl).Require(0xc0001f8400, 0x2485836, 0x4, 0xc0000e3c90, 0x1, 0x1, 0x524168, 0x10)
        /usr/local/google/home/jianfeih/workspace/golang/src/istio.io/istio/pkg/test/framework/runtime/context.go:130 +0x6b
istio.io/istio/pkg/test/framework/runtime.(*contextImpl).RequireOrSkip(0xc0001f8400, 0x2800280, 0xc00033e600, 0x2485836, 0x4, 0xc0000e3c90, 0x1, 0x1)
        /usr/local/google/home/jianfeih/workspace/golang/src/istio.io/istio/pkg/test/framework/runtime/context.go:146 +0x84
istio.io/istio/tests/integration2/examples/pilot.TestHTTP(0xc00033e600)
        /usr/local/google/home/jianfeih/workspace/golang/src/istio.io/istio/tests/integration2/examples/pilot/pilot_test.go:61 +0xdf
testing.tRunner(0xc00033e600, 0x2575288)
        /usr/lib/google-golang/src/testing/testing.go:827 +0xbf
created by testing.(*T).Run
        /usr/lib/google-golang/src/testing/testing.go:878 +0x353
FAIL    istio.io/istio/tests/integration2/examples/pilot        4.683s

**Expected behavior**
The test should succeed.

**Version**
Head of <release-1.1> branch.

**Context**
I want to write an integration2 test, able to configure some security authentication policy, to configure two apps. Then send some tls/mtls/plaintext traffic between apps to see if it works. Pilot is a needed component in this case.

I think this might due to some recent integration test framework refactoring?  Also the `README` doc is outdated. `-istio.test.env=local` will skip all the test, since we rename it to 'native'.

**Comment by incfly** [comment]
@ozevren @nmittler  @hklai 

I need to look into what changes cause that failure. But if you have something in mind already, that'll be great.

**Comment by incfly** [comment]
Blocking writing test for  #6384

**Comment by hklai** [comment]
the tests under example are not included in presubmit run, as they had been flaky. Might be something else happened.

**Comment by incfly** [comment]
@hklai Hmm, I want test that I'm working on will be turned on by default. How can I make it happen?

Is it possible to distinguish the flaky ones and non-flaky ones? Are the flakiness due to the testing environment or specif test cases themselves? `go test -run <testname> -count 100` is this sufficient to reproduce the flakiness?

@nmittler The null is about `PilogArgs.KeepAliveOptions`, which we have a default value in pilot-agent/main.go but not for the testing framework/native.go implementation. I'll send a fix. BTW, what's the golang debug command line to include line number symbols? I googled a bit but didn't find anything relevant.

**Comment by nmittler** [comment]
sgtm thanks.  Yeah, sounds like something changed that broke this test.  

> BTW, what's the golang debug command line trick to include line number symbols? I googled a bit but didn't find anything relevant.

I'm confused ... the trace you showed in the description shows line numbers.
