### ISSUE TITLE
mixer: inconsistent treatment of errors in expressions

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#10538]
Mixer rules may sometimes evaluate to an error (due to undefined attribute, for example). This leads to the following behavior:
1. if the error happens in a match condition, then the rule is effectively ALLOW
2. if the error happens in an instance field, then the rule is effectively DENY

What is concerning is (1), as a typical policy language would treat an error in a condition as a DENY. For example, a Mixer rule with a match clause `source.name = "x"` can be easily bypassed by not supplying `source.name` in the context . 

I believe the best course of action is two-fold:
1. Minimize the source of errors, by defining semantics for a large class of expressions. Errors are hard to reason about, and not something we need to burden the user.
2. Correct the rules application to treat ill-defined match condition as a DENY.

/assign @ozevren 
/assign @mandarjog

**Comment by douglas-reid** [comment]
Unless there are objections, I think we should acknowledge this issue but realize that it is not going to be addressed. Mixer is deprecated -- and with it the configuration language and behaviors. I'm going to close this issue.

If/when CEL tooling emerges for the future Istio extensions architecture, this would be important to keep in mind.
