### ISSUE TITLE
Setting up Active-Hotstandby loadbalancing 

### ISSUE THREAD

**Issue by sendilkumarn** [istio/istio#10545]
**Describe the feature request**

A way to handle (load balance?) Active-Passive or Active-hot standby configuration

**Describe alternatives you've considered**

With `precedence` in `RouteRule`, it may be easier to achieve by giving higher precedence to active pod and lower ones for standby (while it is not foolproof and I am not 100% sure about this setup). 

Since `RouteRule` was removed in the recent version. How we can achieve it via `VirtualService`? 

**Additional context**

Envoy proxy very briefly talks about "Passive" connection [here](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/health_checking#passive-health-checking)

With HAProxy, it is possible to add some annotation and make the switch happen in the gateway itself.
Check [here](https://github.com/jcmoraisjr/haproxy-ingress#configuration-snippet)

**Comment by ecojuntak** [comment]
hi @sendilkumarn, how did you set the active-passive configuration in HAProxy Ingress? I already read the docs, but still not find it. Where did you put the configurations?

**Comment by sendilkumarn** [comment]
@ecojuntak We had used `RouteRule` with `precedence` but it is deprecated in the recent releases.
