### ISSUE TITLE
Bookinfo with virtualservice subset not work

### ISSUE THREAD

**Issue by dozer47528** [istio/istio#10548]
**Describe the bug**
I followed the Traffic Shifting task in istio docs, it works in my local cluster, but not works in my AWS cluster (Created by kops).

**Expected behavior**
After applying `samples/bookinfo/networking/virtual-service-all-v1.yaml`, the `productpage` should only render V1 reviews

**Steps to reproduce the bug**
```shell
kubectl label namespace default istio-injection=enabled
kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml
kubectl apply -f samples/bookinfo/networking/destination-rule-all.yaml
kubectl apply -f samples/bookinfo/networking/virtual-service-all-v1.yaml
```
Nothing happened, I can see other versions of reviews with black stars and red stars.

**Version**
Version: 1.0.5
GitRevision: c1707e45e71c75d74bf3a5dec8c7086f32f32fad
User: root@6f6ea1061f2b
Hub: docker.io/istio
GolangVersion: go1.10.4
BuildStatus: Clean

Have the same problem in istio 1.0.4

Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T19:44:19Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Installation**
The `global.proxy.includeIPRanges` is our VPC ip ranges, in order to access other resources like mysql, redis.

```shell
helm install install/kubernetes/helm/istio --name istio --namespace istio-system \
--set global.proxy.includeIPRanges="10.0.2.0/24\,10.0.12.0/24" \
--set telemetry-gateway.grafanaEnabled="true" \
--set telemetry-gateway.prometheusEnabled="true" \
--set grafana.enabled="true" \
--set tracing.enabled="true" \
--set kiali.enabled="true" \
--set servicegraph.enabled="true" \
--set pilot.traceSampling="100"
```

**Environment**
AWS with KOPS

**Cluster state**

I checked proxy and it will change after apply the config file, that's weird!

```shell
istioctl proxy-config clusters productpage-v1-f8c8fb8-pj2l7 --fqdn reviews.default.svc.cluster.local -o json > clusters.json
istioctl proxy-config routes productpage-v1-f8c8fb8-pj2l7 --name 9080 -o json > routes.json
```

[clusters.txt](https://github.com/istio/istio/files/2690310/clusters.txt)
[routes.txt](https://github.com/istio/istio/files/2690311/routes.txt)

**Comment by linsun** [comment]
it does seem only v1 is referred in routes.txt.  Did you wait up to 30 secs to try again to ensure all config have been pushed to sidecar then access bookinfo?

**Comment by dozer47528** [comment]
@linsun 
I think that was I expected, I applied this file for shifting all the trafic to V1.
`kubectl apply -f samples/bookinfo/networking/virtual-service-all-v1.yaml`

But actually it is no.

**Comment by dozer47528** [comment]
Find the problem, `--set global.proxy.includeIPRanges="10.0.2.0/24\,10.0.12.0/24"`
This ip range was wrong, that's why the router info looks fine, but not work.
