### ISSUE TITLE
Adding monitoring properties results in the inability to obtain telemetry data

### ISSUE THREAD

**Issue by li1191863273** [istio/istio#10540]
Describe the bug

I want to collect the request path in Mixer, so I added the following attribute in the dimensions named requirementsduration

destination_request_url_path: request.url_path | "unknown"

Add destination_request_url_path to the prometheus named handler

The monitoring data of duration cannot be obtained in grafana. Can not get the above changes can be obtained

The configuration file is as follows

	apiVersion: config.istio.io/v1alpha2
	kind: metric
	metadata:
	  clusterName: ""
	  creationTimestamp: 2018-12-18T03:24:18Z
	  generation: 0
	  name: requestduration
	  namespace: istio-system
	  resourceVersion: "119836302"
	  selfLink: /apis/config.istio.io/v1alpha2/namespaces/istio-system/metrics/requestduration
	  uid: 6742e379-0274-11e9-bf86-00163e0d9de0
	spec:
	  dimensions:
	    connection_security_policy: conditional((context.reporter.kind | "inbound") ==
	      "outbound", "unknown", conditional(connection.mtls | false, "mutual_tls", "none"))
	    destination_app: destination.labels["app"] | "unknown"
	    destination_principal: destination.principal | "unknown"
	    destination_request_url_path: request.url_path | "unknown"
	    destination_service: destination.service.host | "unknown"
	    destination_service_name: destination.service.name | "unknown"
	    destination_service_namespace: destination.service.namespace | "unknown"
	    destination_version: destination.labels["version"] | "unknown"
	    destination_workload: destination.workload.name | "unknown"
	    destination_workload_namespace: destination.workload.namespace | "unknown"
	    reporter: conditional((context.reporter.kind | "inbound") == "outbound", "source",
	      "destination")
	    request_protocol: api.protocol | context.protocol | "unknown"
	    response_code: response.code | 200
	    source_app: source.labels["app"] | "unknown"
	    source_principal: source.principal | "unknown"
	    source_version: source.labels["version"] | "unknown"
	    source_workload: source.workload.name | "unknown"
	    source_workload_namespace: source.workload.namespace | "unknown"
	  monitored_resource_type: '"UNSPECIFIED"'

	apiVersion: config.istio.io/v1alpha2
	kind: prometheus
	metadata:
	  clusterName: ""
	  name: handler
	  namespace: istio-system
	  selfLink: /apis/config.istio.io/v1alpha2/namespaces/istio-system/prometheuses/handler
	spec:
	  metrics:
	  - instance_name: requestcount.metric.istio-system
	    kind: COUNTER
	    label_names:
	    - reporter
	    - source_app
	    - source_principal
	    - source_workload
	    - source_workload_namespace
	    - source_version
	    - destination_app
	    - destination_principal
	    - destination_workload
	    - destination_workload_namespace
	    - destination_version
	    - destination_service
	    - destination_service_name
	    - destination_service_namespace
	    - request_protocol
	    - response_code
	    - connection_security_policy
	    name: requests_total
	  - buckets:
	      explicit_buckets:
	        bounds:
	        - 0.005
	        - 0.01
	        - 0.025
	        - 0.05
	        - 0.1
	        - 0.25
	        - 0.5
	        - 1
	        - 2.5
	        - 5
	        - 10
	    instance_name: requestduration.metric.istio-system
	    kind: DISTRIBUTION
	    label_names:
	    - reporter
	    - source_app
	    - source_principal
	    - source_workload
	    - source_workload_namespace
	    - source_version
	    - destination_app
	    - destination_principal
	    - destination_workload
	    - destination_workload_namespace
	    - destination_version
	    - destination_service
	    - destination_service_name
	    - destination_service_namespace
	    - request_protocol
	    - response_code
	    - connection_security_policy
	    - destination_request_url_path
	    name: request_duration_seconds
	    ...

Version

k8s

	Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

istio

	1.0.3

**Comment by bianpengyuan** [comment]
request.url_path is not available in 1.0.x release. It will be available in 1.1 release. If you check mixer log, you should be able to see statement like "unknown attributes: request.url_path".

**Comment by li1191863273** [comment]
> request.url_path is not available in 1.0.x release. It will be available in 1.1 release. If you check mixer log, you should be able to see statement like "unknown attributes: request.url_path".

very Thanks， would you like tell me how to  check mixer log, and, If I want to monitor the request URL, the 1.0.3 version is not a way

**Comment by bianpengyuan** [comment]
With istio-telemetry pod id you can use `kubectl logs -n istio-system -c mixer telemetry-pod-id` to check mixer's log.

Const string value needs to be quoted with ' '. So instead of "unknown", it should be '"unknown"'.

**Comment by li1191863273** [comment]
very nice for you, I use kubectl get  metric requestduration -n istio-system, It all use  XXX | "unknown",
Use constants directly to add '

**Comment by li1191863273** [comment]
hi, I use this

	destination_service_namespace: destination.service.namespace | "unknown"
	or
	destination_service_namespace: destination.service.namespace | '"unknown"'

An error occurred

	failed to evaluate expression for field 'Dimensions[destination_request_url_path]'; failed to parse expression 'request.path | '"unknown"'': unable to parse expression 'request.path | '"unknown"'': 1:16: illegal rune literal

I see the request.path property on the 1.0 document.

**Comment by li1191863273** [comment]
in this document https://istio.io/docs/reference/config/policy-and-telemetry/attribute-vocabulary/

**Comment by li1191863273** [comment]
OK , work. use destination_request_url_path: request.url_path | "unknown",
and config Add destination_request_url_path to the prometheus named handler

**Comment by li1191863273** [comment]
this issue can be closed, very thanks
