### ISSUE TITLE
'nodeagent' name confusing

### ISSUE THREAD

**Issue by costinm** [istio/istio#10555]
The nodeagent template is badly named - we have another node agent implementing CNI, and there is no indication this is a citadel or security component. 

Please rename to 'sds-agent' or simply 'isitio-sds', since that's what it does.

We need this before we launch 1.1, since after it's far harder to rename.

**Comment by wattli** [comment]
@quanjielin , can we rename it to citadel-agent please? Thanks.

**Comment by wattli** [comment]
Will the new agent called cni-agent?

**Comment by wattli** [comment]
@myidpt  citadel-agent sounds good to me.

**Comment by myidpt** [comment]
If we change this naming after 1.1, it won't require migration effort (the name is not used to refer to the node agent component). So maybe we can make this P1?

**Comment by jasminejaksic** [comment]
After brief discussion with Oliver and Costin, this is a 1 line fix and should happen before 1.1. Costin or Tao could work on this.
