### ISSUE TITLE
Update bookinfo sample images

### ISSUE THREAD

**Issue by linsun** [istio/istio#10552]
per discussion #10527

**Comment by linsun** [comment]
@frankbu can you confirm users are using the same sample version for 1.0.x and 1.1?  it looks so to me from yaml file.

**Comment by linsun** [comment]
https://github.com/istio/istio/pull/9642

**Comment by linsun** [comment]
would also require change in the yaml to use the newer image.

**Comment by frankbu** [comment]
Need to do the following:
1. Rebuild bookinfo sample images
2. Version tag new images as 1.10.0
3. Push images to dockerhub
4. Update all of the yaml files to use the new version (s/1.9.0/1.10.0)

**Comment by rvennam** [comment]
The `build_push_update_images.sh <version>` script does what you outlined @frankbu 
https://github.com/istio/istio/tree/release-1.1/samples/bookinfo

**Comment by rvennam** [comment]
That script needs a couple of tweaks. Working on that now

**Comment by rvennam** [comment]
New 1.10.0 images have been built, tagged with 1.10.0 & latest, pushed to dockerhub and yaml files have been updated.

**Comment by linsun** [comment]
closing this, thank you @rvennam and @frankbu !!
