### ISSUE TITLE
Improve grafana dashboard visibility for low traffic situations

### ISSUE THREAD

**Issue by jonathan-lo** [istio/istio#10565]
**Describe the feature request**
Our deployment is fairly low traffic at the moment. This is tricky In terms of monitoring on the grafana dashboards in that there are sparsely populated data points, but they are not contiguous time periods so would not show up on the dashboard without mousing over the data point.

One way this could be solved is to enable the "points" draw mode on the relevant charts. We can PR if this change is acceptable.

**Comment by jonathan-lo** [comment]
As an example:

![image](https://user-images.githubusercontent.com/3763897/50191384-c1499400-0381-11e9-9f60-999e919d0390.png)

**Comment by douglas-reid** [comment]
I'm not sure we want to switch exclusively to "points". "Points" + "Lines" may work (with a small points radius). Can you may be work on a draft PR with the dashboards snapshots exported, and we can discuss in the P&T WG ?

**Comment by jonathan-lo** [comment]
Yep, what I meant was "Points" + "Lines".

Will draft up a PR, thanks.

**Comment by Stono** [comment]
A couple of things we've done to our dashboards to improve things:

  - If you change the graph to "connected" it'll join the gaps where there is no data available
  - Where we're calculating success rate percentile, we have modified the query to have an `or` returning a result when no data is present:

```
1 - 
(
  (
    sum(increase(istio_requests_total{reporter="destination", destination_app!="unknown", response_code=~"5.*"}[$__range])) by (destination_app) 
    or
    (count(count(istio_requests_total{reporter="destination", destination_app!="unknown"}) by (destination_app) > 0) by (destination_app) -1)
  )
  /
  (sum(increase(istio_requests_total{reporter="destination", destination_app!="unknown"}[$__range])) by (destination_app) > 0)
)
```

**Comment by fredmtyro** [comment]
Some initial proposed changes for moving to points + lines are here: https://github.com/fredmtyro/istio/tree/make_dashboards_with_nulls_clearer

![screen shot 2019-02-05 at 1 12 01 pm](https://user-images.githubusercontent.com/40345281/52249542-ce2d4180-2947-11e9-9fa7-1c1542c45c8d.png)

**Comment by fredmtyro** [comment]
Newer Grafana versions draw disconnected null points as dots by default, so this can be resolved by updating Grafana to 5.4.3 or 6.0

**Comment by douglas-reid** [comment]
We've bumped up to 6.0 in `master` already.

**Comment by douglas-reid** [comment]
@jonathan-lo did moving to a more recent version of Grafana fix your issue here?

**Comment by jonathan-lo** [comment]
@douglas-reid yes thanks. We bumped to 6+
