### ISSUE TITLE
Istio Consul : bookinfo.sidecars.yaml file missing

### ISSUE THREAD

**Issue by absc6** [istio/istio#10564]
**bookinfo.sidecars.yaml missing**
file mentioned in the command is not present in github.

`docker-compose -f samples/bookinfo/platform/consul/bookinfo.sidecars.yaml up -d`  

Can you please review and update it.
Also, can you please share clarify the following:

1. Creating independent gateway for consul/docker based service
2. Adding side-car for application to integrate with custom application. 
3. Most documentation and example for istio uses Kubernetes, is there any plan to increase support/how-to tutorials for istio with consul/docker.

**Comment by l10xbin** [comment]
@absc6  This "samples/bookinfo/platform/consul/bookinfo.sidecars.yaml" can be find in release folder.  I checked it exist in 1.0.5 and istio-release-1.1-20181202-09-15.
I think this file was generated during the build process.  As you can see there is a template file here [https://github.com/istio/istio/tree/master/samples/bookinfo/platform/consul/templates](https://github.com/istio/istio/tree/master/samples/bookinfo/platform/consul/templates)
