### ISSUE TITLE
unable to access the service via virtual service in Istio 1.0.5

### ISSUE THREAD

**Issue by VenkateshSrini** [istio/istio#10568]
Hi,
I'm new to istio and I have my the entire code in http://github.com/VenkateshSrini/IstioTest. I have created the service needed for hosting the Kubernetes service (istio-test-deployment.yaml in the repo). I tested it on docker for windows (Kubernetes enabled) and I got the same working correctly. I had exposed my service via port 5000. In docker for windows the external Ip is always localhost. 

Now using istoctl I created a created a side car deployment. That can be seen from istio-test-dep-injected.yaml. I executed this and service was created with Sidecar. _Now the same service is not accessible via http://localHost:5000, which I think is correct_

Then I went ahead and created the Virtual Gateway. The definition of the same can be seen at virtual-gateway.yaml. Then I created a virtual service as per virtualservice.yaml. In that I have provided the host and the name of Kubernetes service name and the port as 5000. 

Even after all this I'm unable to access the Service using the url http://localHost/api/version

can someone help me, because I do not find much help working with Istio with Docker for Windows

**Comment by VenkateshSrini** [comment]
Hi Any help on this please. I'm unable to proceed

**Comment by VenkateshSrini** [comment]
any suggestion?

**Comment by VenkateshSrini** [comment]
any suggestion

**Comment by VenkateshSrini** [comment]
any help. This is still a problem for me

**Comment by esnible** [comment]
I have not used Docker for Windows.  When you say "I had exposed my service via port 5000." I assume you are exposing your service as a NodePort.  I am not sure how this will work in Docker for Windows.

Istio is mostly about service-to-service, or IngressGateway to service.  You might try following the https://github.com/istio/istio/tree/master/samples/sleep example to see if you can create another service and `curl` your service from within the cluster.

When getting logs, once Istio is applied Kubernetes doesn't know if you want the app logs or the sidecar logs.  Append `-c istio-test` or `-c istio-proxy` to the `kubectl logs` command.

**Comment by VenkateshSrini** [comment]
@esnible,
Thanks for your suggestion. If you could see the Sevice yaml file definition, you can see that I have used LoadBalancer. Before injecting the envoy side car (the yaml file generated by Istioctl) I'm able to access the service without any issues. But after creating the side car + service deployment the service became inaccessible, which I think is because the virtual gateway and virtual services are not present.

That is when I started creating the Virtual gateway and virtual service. That is when it started failing

**Comment by VenkateshSrini** [comment]
> I have not used Docker for Windows.  When you say "I had exposed my service via port 5000." I assume you are exposing your service as a NodePort.  I am not sure how this will work in Docker for Windows.
> Istio is mostly about service-to-service, or IngressGateway to service.  You might try following the https://github.com/istio/istio/tree/master/samples/sleep example to see if you can create another service and curl your service from within the cluster.
> When getting logs, once Istio is applied Kubernetes doesn't know if you want the app logs or the sidecar logs.  Append -c istio-test or -c istio-proxy to the kubectl logs command.

Hi If you could see the yaml file that I have generated and put above is a result of Kube-inject only. I need help in correcting the Gateway and or Virtual service orelse I would like to what else is missed in my deployment

**Comment by esnible** [comment]
@VenkateshSrini I am not familiar with the annotation `kompose.service.type` and I do not use Windows so I may not be able to help but I will try.

For Istio, traffic flows through the "IngressGateway" into your cluster.  It is the IngressGateway that applies the Gateway rules and sends traffic to instances according to your VirtualService and Service.

Your Service "istio-test" has a port named "5000".  This will cause Istio to treat it as TCP, not HTTP.  Try naming the Port "http".

You test using http://localHost/api/version .  This means you are talking to port 80.  For this to work the IstioIngress service must be exposed on port 80.  Do

```
kubectl -n istio-system get services istio-ingressgateway
```

The output will include a PORT(S) column showing the ports that Istio believes the Ingress is on.  For my cluster, I see 80:31380/TCP as one of the ports.  This means the Ingress is listening on port 31380, not 80.  Perhaps your setup has something similar.  If so, try testing using http://localhost:31380.

Make these changes, report back here with what happens.

**Comment by VenkateshSrini** [comment]
> @VenkateshSrini I am not familiar with the annotation kompose.service.type and I do not use Windows so I may not be able to help but I will try.
> For Istio, traffic flows through the "IngressGateway" into your cluster.  It is the IngressGateway that applies the Gateway rules and sends traffic to instances according to your VirtualService and Service.
> Your Service "istio-test" has a port named "5000".  This will cause Istio to treat it as TCP, not HTTP.  Try naming the Port "http".
> You test using http://localHost/api/version .  This means you are talking to port 80.  For this to work the IstioIngress service must be exposed on port 80.  Do
> kubectl -n istio-system get services istio-ingressgateway
> 
> The output will include a PORT(S) column showing the ports that Istio believes the Ingress is on.  For my cluster, I see 80:31380/TCP as one of the ports.  This means the Ingress is listening on port 31380, not 80.  Perhaps your setup has something similar.  If so, try testing using http://localhost:31380.
> Make these changes, report back here with what happens.
@esnible,
Thanks for  your reply. Kompose service type is not something specific to windows. We use the tool Kompose (http://kompose.io/) to generate the Service.Yaml and deployment.yaml from docker-compose file. If I deploy the service without side car injection  then using the url http://localHost:5000/api/version works fine. So I do not think if that is the issue. Do you think that is adding those annotation is not allowing Kubernets to select the Virtual gate and Virtual service not possible ?
I have also removed the port 5000 as per your suggestion and have also checked the code. Can you please if this Virtualservice.Yaml is correct now?
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-test-virtualservice
  namespace: istio-apps
spec:
  hosts:
  - "*"
  gateways:
  - istio-test-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: istio-test       
```
Also as suggested by you I have executed the command `kubectl -n istio-system get services istio-ingressgateway`. The output I see is as bleow
`istio-ingressgateway     LoadBalancer   10.101.11.124    localhost     80:31380/TCP,443:31390/TCP,31400:31400/TCP,15011:31560/TCP,8060:31022/TCP,853:31871/TCP,15030:32173/TCP,15031:30471/TCP   19d`

I accessed the app using the URL http://localHost:31380/api/version but still it failed

**Comment by esnible** [comment]
@ VenkateshSrini what URL do I use to test your system?  I brought it up, did `kubectl exec istio-test-7bb957c5c8-rvbhl -- curl -v localhost:80/v1/api/` to make sure it is running, but I get a 404.

**Comment by VenkateshSrini** [comment]
@esnible,
Thank you very much. You need to access http://localHost:<<Port>>/api/version. You would receive "ding <version number>" if the everything works fine.

Can you please try accessing the same from browser also and confirm it is working ?

 In windows we do not have curl.  So should I run Kubectl exec <Isttio test pod> and do the http access from browser?

**Comment by esnible** [comment]
From my Mac I can't access localHost, because I am running your pods on IBM Container Service.

_curl_ is a Linux command.  When you run `kubectl exec` it runs the command on the container.  The command I gave you runs on the container itself.  I fat-fingered the previous one, I should have typed `kubectl exec istio-test-7bb957c5c8-rvbhl -- curl -v localhost:80/api/version`

I found two problems with your setup.

First, your VirtualService and Gateway have `namespace: istio-apps` but your `istio-test-deployment.yaml` did not.  It is best if they all match.  I created an _istio-apps_ namespace.  I have the auto-injector turned on, so I did `kubectl apply -n istio-apps -f istio-test-deployment.yaml` to deploy in a namespace matching your Gateway and VirtualService.

Second your Service describes a service on port 5000 but your VirtualService didn't so the traffic was going to port 80.  I changed your VirtualService to include, like this:

```
    - destination:
        host: istio-test
        port:
          number: 5000
```

I believe those are the only changes needed.  I wasn't able to verify that everything worked together because I am in the middle of checking some mTLS settings, but try those two things.

**Comment by VenkateshSrini** [comment]
Now my side car injected yaml looks like below 
`apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: C:\Program Files\KomposeTool\kompose.exe convert -o istio-test-deployment.yaml
      kompose.service.type: loadbalancer
      kompose.version: 1.4.0 (c7964e7)
    creationTimestamp: null
    labels:
      app: istio-test
      io.kompose.service: istio-test
    name: istio-test
    namespace: istio-apps
  spec:
    ports:
    - name: "5000"
      port: 5000
      targetPort: 80
    selector:
      app: istio-test
      io.kompose.service: istio-test
    type: LoadBalancer
  status:
    loadBalancer: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: C:\Program Files\KomposeTool\kompose.exe convert -o istio-test-deployment.yaml
      kompose.service.type: loadbalancer
      kompose.version: 1.4.0 (c7964e7)
    creationTimestamp: null
    labels:
      app: istio-test
      io.kompose.service: istio-test
      version: v1
    name: istio-test
    namespace: istio-apps
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        annotations:
          sidecar.istio.io/status: '{"version":"50128f63e7b050c58e1cdce95b577358054109ad2aff4bc4995158c06924a43b","initContainers":["istio-init"],"containers":["istio-proxy"],"volumes":["istio-envoy","istio-certs"],"imagePullSecrets":null}'
        creationTimestamp: null
        labels:
          app: istio-test
          io.kompose.service: istio-test
          version: v1
      spec:
        containers:
        - image: venkateshsrini3/istiotest
          name: istio-test
          ports:
          - containerPort: 80
          resources: {}
        - args:
          - proxy
          - sidecar
          - --configPath
          - /etc/istio/proxy
          - --binaryPath
          - /usr/local/bin/envoy
          - --serviceCluster
          - istio-test
          - --drainDuration
          - 45s
          - --parentShutdownDuration
          - 1m0s
          - --discoveryAddress
          - istio-pilot.istio-system:15005
          - --discoveryRefreshDelay
          - 1s
          - --zipkinAddress
          - zipkin.istio-system:9411
          - --connectTimeout
          - 10s
          - --proxyAdminPort
          - "15000"
          - --controlPlaneAuthPolicy
          - MUTUAL_TLS
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: INSTANCE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: ISTIO_META_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: ISTIO_META_INTERCEPTION_MODE
            value: REDIRECT
          - name: ISTIO_METAJSON_LABELS
            value: |
              {"app":"istio-test","io.kompose.service":"istio-test","version":"v1"}
          image: docker.io/istio/proxyv2:1.0.5
          imagePullPolicy: IfNotPresent
          name: istio-proxy
          ports:
          - containerPort: 15090
            name: http-envoy-prom
            protocol: TCP
          resources:
            requests:
              cpu: 10m
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 1337
          volumeMounts:
          - mountPath: /etc/istio/proxy
            name: istio-envoy
          - mountPath: /etc/certs/
            name: istio-certs
            readOnly: true
        initContainers:
        - args:
          - -p
          - "15001"
          - -u
          - "1337"
          - -m
          - REDIRECT
          - -i
          - '*'
          - -x
          - ""
          - -b
          - "80"
          - -d
          - ""
          image: docker.io/istio/proxy_init:1.0.5
          imagePullPolicy: IfNotPresent
          name: istio-init
          resources: {}
          securityContext:
            capabilities:
              add:
              - NET_ADMIN
            privileged: true
        restartPolicy: Always
        volumes:
        - emptyDir:
            medium: Memory
          name: istio-envoy
        - name: istio-certs
          secret:
            optional: true
            secretName: istio.default
  status: {}
kind: List
metadata: {}
---
`
It can be seen that the name space is added. Also my virtual service looks like below
`apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  annotations:
    kompose.cmd: C:\Program Files\KomposeTool\kompose.exe convert -o istio-test-deployment.yaml
    kompose.service.type: loadbalancer
    kompose.version: 1.4.0 (c7964e7)
  name: istio-test-virtualservice
  namespace: istio-apps
spec:
  hosts:
  - "*"
  gateways:
  - istio-test-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: istio-test
        port:
          number: 5000
`
It can be seen that the port number is added. But still no luck when accessing using the URL http://localHost:31380/api/version. It still gives the error 

> There was a temporary DNS error. Try refreshing the page.                                    
 Error Code: INET_E_RESOURCE_NOT_FOUND
--
I have checked the code also I the same repository. Could you please check now

**Comment by esnible** [comment]
It worked for me.  I had to do one more thing

```
kubectl label ns istio-apps istio-injection=enabled
```

This is because mTLS is on by default, but not for the namespace you are using.

**Comment by VenkateshSrini** [comment]
Oh. Could you please if I have done all the changes that you have said the above repository. For some reason it https://github.com/VenkateshSrini/IstioTest. Also what is the environment that you are using. I use Kubernetes with Docker for windows. Minikube on windows is also Highly unstable. If you don't mind can you please share what you have modified and did from your git hub.

Another question is where you able to access the same from browser?

**Comment by esnible** [comment]
I can't push to your Github.  Here is what I would have pushed:

```
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   VirtualService.yaml
	modified:   istio-test-deployment.yaml
	deleted:    istio-test-deployment_injected.yaml

no changes added to commit (use "git add" and/or "git commit -a")
/tmp/IstioTest/istio-test$ git diff
diff --git a/istio-test/VirtualService.yaml b/istio-test/VirtualService.yaml
index 37808f9..3dd636a 100644
--- a/istio-test/VirtualService.yaml
+++ b/istio-test/VirtualService.yaml
@@ -19,3 +19,5 @@ spec:
     route:
     - destination:
         host: istio-test       
+        port:
+          number: 5000
diff --git a/istio-test/istio-test-deployment.yaml b/istio-test/istio-test-deployment.yaml
index b417d50..636466d 100644
--- a/istio-test/istio-test-deployment.yaml
+++ b/istio-test/istio-test-deployment.yaml
@@ -12,6 +12,7 @@ items:
       io.kompose.service: istio-test
       app: istio-test
     name: istio-test
+    namespace: istio-apps
   spec:
     ports:
     - name: "5000"
```

I was able to access from a browser.

I used IBM Container Service.

When I test locally I use a Vagrant box that a colleague made for me, running Linux with Docker and Kubernetes on that Docker.  I am not sure how it works.  I didn't try that environment with your repo.

**Comment by VenkateshSrini** [comment]
Would it be possible to just attach the virtual service.yaml and istio deployment to this thread atleast. Or you could send me by email at venkateshsrini3@gmail.com

**Comment by esnible** [comment]
Uploaded with .txt extension because Github wouldn't accept as .yaml.

[istio-test-deployment.yaml.txt](https://github.com/istio/istio/files/2861221/istio-test-deployment.yaml.txt)
[VirtualService.yaml.txt](https://github.com/istio/istio/files/2861222/VirtualService.yaml.txt)

**Comment by VenkateshSrini** [comment]
@esnible ,
Thanks for your inputs. We tried the same in Docker Desktop for windows and Mac. But still we are not able to get the same working.  Could you please tell what port number you used to get the same working via browser. Did you use 80 or 31380.

**Comment by esnible** [comment]
I used port 31380, and I was using IBM Container Service.

Remember, it is the Ingress Gateway that routes traffic and enforces your Istio policies.  So all traffic entering the mesh should go through the IP:port for the Ingress Gateway.

**Comment by VenkateshSrini** [comment]
We also used the same but for some reason it is failing. May be we will try with some managed cluster and I will revert

**Comment by VenkateshSrini** [comment]
@esnible ,
I wanted to ask one more thing, when you installed the istio cluster.. What version did you choose? I have istio 1.0.5. Also when you installed the same on kubernetes cluster did you install the cluster using istio-demo.yaml or istio-demo-auth.yaml? I had used istio-demo-auth.yaml.

**Comment by esnible** [comment]
I cannot recall which versions of Istio I tested your app with.  I have been using 1.0.5, 1.1 snapshot 6, and 1.1 daily builds as well.

I install using `helm template` according to the instructions at https://istio.io/docs/setup/kubernetes/helm-install/#option-1-install-with-helm-via-helm-template

**Comment by VenkateshSrini** [comment]
I tried exact same things. But it is not working. Is there some service that I can put the logs to see what is happening internally ?

**Comment by VenkateshSrini** [comment]
HI,
commenting to avoid issue become stale. Still the issue is open and none of the above solution worked for me

**Comment by maeri** [comment]
Hi @VenkateshSrini, 

I don't think it's the Istio issue unless you point me to your VirtualService config that routes to you api part. Came today across same issue. After ingressgateway I do have Docker Nginx with React app. On the /api route application is requesting api data. So http://<ip> returns React to browser while calls from React to http://<ip>/api/... goes directly to backend.

**Comment by VenkateshSrini** [comment]
Please see my code at https://github.com/VenkateshSrini/IstioTest. There is a file called VirtualService.yaml in this that contains the yaml definition for virtual service. Please provide me with some insights

**Comment by maeri** [comment]
@VenkateshSrini  

Please take a look at repo https://github.com/maeri/istio-apps

Enjoy your day !

**Comment by VenkateshSrini** [comment]
@maeri,
Have you found the issue? Where you able to get this working? What version of Istio you had used? What was the mistake in my yamls?

**Comment by maeri** [comment]
Yes - my repo works. I had like 'ding' in response. Please compare carefully my repo yaml files and yours. There were problems with configurations from gateway through service to pod's. Basically, mismatch in labels between k8s objects. To run it correctly objects needs to be properly connected through labels/names etc. You have instructions in my repo README. 

Have a nice day!

**Comment by howardjohn** [comment]
Seems like the issue has been resolved per above

**Comment by VenkateshSrini** [comment]
I'm yet to verify the same
