### ISSUE TITLE
unable to access pod endpoint on ExternalVM after service mesh expansion....

### ISSUE THREAD

**Issue by devops083** [istio/istio#10576]
Hi, I have implemented mesh expansion in AWS, after implementing, i am able to resolve services and I tried to access POD endpoint in external VM but unable to telnet and ping.

**Comment by l10xbin** [comment]
I think you need to use egress to visit outside: 
Check this [](https://preliminary.istio.io/docs/tasks/traffic-management/egress/)

**Comment by devops083** [comment]
@l10xbin thnx for your response, I got a solution for above one but not sure  with Egress, In GCP GKE and AWS EKS by default we can access pod ips from outside cluster with in VPC.
