### ISSUE TITLE
Get multi-cluster discovery working (galley + pilot) with a galley and a pilot in each cluster

### ISSUE THREAD

**Issue by wattli** [istio/istio#10589]

**Comment by irisdingbj** [comment]
@wattli  I am interested in this scenario. But as of now galley can not provide services info to pilot. So what is the detailed expection for this scenario?

**Comment by incfly** [comment]
FYI I have a PR on `istio.io` to explain how to setup gateway/sni based multi cluster.
https://github.com/istio/istio.io/pull/2907

**Comment by jasminejaksic** [comment]
Did istio/istio.io#2907 fix this? if not, @nmittler what's still pending and what's the ETA?

**Comment by ozevren** [comment]
@nmittler and I working on this (Mostly @nmittler writing code, I am reviewing). The next PR should be going in soon (today) that enables reading of the appropriate resources from K8s. The next one will be for synthesizing the endpoints.

**Comment by ymesika** [comment]
@wattli In a multi-cluster (single control plane) setup, do you actually need remote (Pilot+Galley) or just Galley?
Going through the upcoming changes by @nmittler seems like a remote Galley can watch the k8s types and serve the service entries to the central pilot.

**Comment by sdake** [comment]
@ymesika good question - information on the design needed for deployment and docs.

Cheers
-steve

**Comment by duderino** [comment]
@nmittler update please

**Comment by nmittler** [comment]
Sure ... so most of the work has landed in the 1.1 branch (including incremental MCP). There are 2 PRs that are outstanding to piece things together:

- #11293: this is the main Galley work to add ServiceEntry synthesis and adds a new collection that can be observed by Pilot
- #10994 (by @Nino-K) this is a WIP that contains the Pilot-side changes to use the new collection.

Once those two land, everything should be in place for multicluster service discovery.

cc @ayj @ozevren @Nino-K @costinm @rshriram

**Comment by howardjohn** [comment]
Is this fixed by Nino's SSE PR?

**Comment by nmittler** [comment]
@howardjohn I think so ... the description of the success criteria here is not very clear. Probably better to just close it for now ... I'm sure we'll have any number of more specific issues related to multi-cluster.
