### ISSUE TITLE
 Implement a Vault adaptor for Citadel Agent to call Vault

### ISSUE THREAD

**Issue by lei-tang** [istio/istio#10599]
**Describe the feature request** 
 Implement a Vault adaptor for Citadel Agent to call Vault.

**Describe alternatives you've considered**
Citadel Agent -> Citadel -> Vault

**Additional context**
{{ Add any other context about the feature request here }}

**Comment by smawson** [comment]
Why is this a P0? Can this be moved to 1.2 or at least P1?

**Comment by lei-tang** [comment]
It is a P0 because it is required by Datadog.

**Comment by lei-tang** [comment]
The Vault adapter for Node Agent has been implemented. Thus, this issue is closed.
