### ISSUE TITLE
Nodeagent base image

### ISSUE THREAD

**Issue by costinm** [istio/istio#10592]
Proxy, pilot and other images all share a common base image.
Please move nodeagent to the same base - both build speed and ability to use a different base are affected. 

We had several discussions and users who want deb_lite or a more recent version of ubuntu - this can be done today by building the base image with a different config (and labeling it istionightly/base_debug - this can be a local label on the build machine, doesn't need to be a real dockerhub image).

In general we should not hardcode 'xenial' in our docker files, and try to keep a common base image, both speed and consistency reasons.

**Comment by costinm** [comment]
node_agent is not using scratch - but ubuntu, with its own 'apt-get update'.

The goal is to be able to have a single base image, so we can have the base moved to deb_slim or 
different version of ubuntu.

**Comment by munrodg** [comment]
@wattli can this issue be closed?

**Comment by fpesce** [comment]
@wattli it looks like the merged PR  #10949 changed and reverted the image used, eventually just updating some dependency (ca-certificates), can you confirm this ( #10592 )  is *not* fixed?

**Comment by wattli** [comment]
This is not fixed yet. @myidpt do you have time to pick it up?

**Comment by myidpt** [comment]
@wattli Sure. Could you tell me why this can't be fixed by a simple image change PR / is there any dependency specifically on xenial?
@quanjielin

**Comment by wattli** [comment]
I think building from the base image should work, but i may not have the full context.

**Comment by quanjielin** [comment]
this is done.

**Comment by fpesce** [comment]
Thanks.
