### ISSUE TITLE
Slicer support?

### ISSUE THREAD

**Issue by therc** [istio/istio#106]
Since the service mesh takes care of load balancing, would autosharding along the lines of the Slicer paper be in scope, too? I assume that it would require Stubby's support for it be ported into gRPC first.

https://www.usenix.org/system/files/conference/osdi16/osdi16-adya.pdf

I tried asking on the list, but it seems to be invite-only. Let me know if there's a more appropriate place.

**Comment by hq6** [comment]
I'm confused by the commits that appear to reference this.
Is there Slicer support in Istio currently?
