### ISSUE TITLE
Pod with Istio-proxy cannot communicate with service in a different namespace

### ISSUE THREAD

**Issue by jgrossmac** [istio/istio#10606]
**Describe the bug**
Pod in namespace "A" with istio sidecar injection turned **ON** cannot reach cockroachdb service in namespace "B".

Pod in namespace "A" with istio sidecar injection turned **OFF** is able to reach cockroachdb service in namespace "B".

Cockroachdb service in namespace "B" does **NOT** have an istio proxy sidecar.

DNS resolves properly in both cases.

I checked the service logs on cockroachdb in namespace "B" and it seems to not be getting that far.
 
Istio-policy logs do not indicate a problem, nor do the istio-proxy logs for the test pods in namespace "A".

**Expected behavior**
I expect the pod in namespace "A" to be able to reach the cockroachdb service in namespace "B" with or without sidecar injection turned on.

**Steps to reproduce the bug**
Create 1 test pod in namespace "A" with sidecar injection turned on and another one with injection turned off.  Create a database service in namespace "B" and try connecting via psql or pg_isready.

**Version**
Istio Version: 1.1.0 Snapshot 1
Kube Version: 1.10.6 (Azure CNI)

**Installation**
Helm Charts

**Environment**
Azure (ACS-Engine)

**Comment by sweetib** [comment]
I am facing same issue. How can check routes for a given pod that doesn't belong to the cluster where Pilot is running? I am getting POD not found error all the time. Everything works in default namespace.

**Comment by hzxuzhonghu** [comment]
specify namesapce with `-n xxx`

**Comment by sweetib** [comment]
I tried that but no luck

**Comment by vadimeisenbergibm** [comment]
The fix is:
cat <<EOF | kubectl apply -f -
apiVersion: "networking.istio.io/v1alpha3" 
kind: "DestinationRule" 
metadata: 
  name: external 
  namespace: default 
spec: 
  host: "*.B.svc.cluster.local" 
  trafficPolicy: 
    tls: 
      mode: DISABLE 
EOF

See https://istio.io/docs/tasks/security/mutual-tls/#verify-mutual-tls-configuration

**Comment by Bessonov** [comment]
unstale
