### ISSUE TITLE
Modify the sidecar listening port

### ISSUE THREAD

**Issue by li1191863273** [istio/istio#10616]
I want to modify the istmap whose name is isti-sidecar-injector. The port that sidecar reads by default is

     - "-b"
     - "[[ annotation .ObjectMeta `traffic.sidecar.istio.io/includeInboundPorts` (includeInboundPorts .Spec.Containers) ]]"

I want to read this value first. If it exists, use this value. If it does not exist, use port 8080. How should I modify it? I don't know how to write this grammar. What is the grammar?

**Comment by vadimeisenbergibm** [comment]
You can set `global.proxy.includeInboundPorts` during helm installation. https://preliminary.istio.io/docs/reference/config/installation-options/#global-options

Note that this option means the ports which Istio sidecar will handle (it will ignore other ports).

Documentation: https://github.com/istio/istio/blob/df0d817c5ecf6f3fab94cb599ddd90c363c4d533/pilot/pkg/kube/inject/inject.go#L206

> Comma separated list of inbound ports for which traffic is to be redirected to Envoy. All ports can be redirected with the wildcard character "*". Defaults to "*".
