### ISSUE TITLE
Mixer should make adapter responses available as attributes

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#10629]
When an adapter rejects a request, Mixer sends back this information to the Proxy.
However this information is not available as an attribute.

This information should be available as an attribute so that it can be used in reports or logs.

This attribute can be a `stringmap` or something else that is structured.

**Comment by mandarjog** [comment]
@liminw @douglas-reid

**Comment by kyessenov** [comment]
There are two attributes populated by the proxy on error response (https://github.com/istio/proxy/blob/4cfa354bbeb42ae67c3c634e19ad01a54339cb3a/src/istio/control/http/attributes_builder.cc#L225):
- `check.error_code` is the gRPC error code
- `check.error_message` is the error string from Mixer that includes the failing rule

Can you clarify what other information we need?

**Comment by liminw** [comment]
@robertpanzer

**Comment by robertpanzer** [comment]
It would be nice though to also see at least a flag in the access log of the proxy that initiated the istio mixer check that the request was rejected because of a failed mixer check.

**Comment by kyessenov** [comment]
@robertpanzer UAEX is the Envoy's error code for Mixer's failed check request. See https://www.envoyproxy.io/docs/envoy/latest/configuration/access_log. Mixer is technically an external authorization service here.

**Comment by robertpanzer** [comment]
I think this is ok.
You'll see that the request was rejected due to a rejected authorization, to find the root of the problem you can check the logs generated by istio-policy (if configured) using the requestId that is also part of the access log.

**Comment by douglas-reid** [comment]
@munrodg can we keep this open, but with a different milestone?  we still don't have attributes that carry information on policy adapter response *per* policy adapter.

@mandarjog @kyessenov: comments?
