### ISSUE TITLE
Helm fails when following docs

### ISSUE THREAD

**Issue by thockin** [istio/istio#10633]
**Describe the bug**
Following the helm docs I get to `helm template install/kubernetes/helm/istio --name istio --namespace istio-system --set global.mtls.enabled=true` whereupon I am told "Error: found in requirements.yaml, but missing in charts/ directory: sidecarInjectorWebhook, security, ingress, gateways, mixer, nodeagent, pilot, grafana, prometheus, servicegraph, tracing, galley, kiali, istiocoredns, certmanager, telemetry-gateway"

**Expected behavior**
For it to work.

**Comment by jmazzitelli** [comment]
@thockin you didn't say what version of Istio (1.0.x? 1.1.snapshot?) or version of Helm you are using or which page in which set of docs you are referring to (istio.io? preliminary.istio.io? a README?)  - three important pieces of info that would be needed to help you. However, please see https://github.com/istio/istio.io/issues/2787 - i think it will provide an answer.

**Comment by sdake** [comment]
@thockin apologies for long delay - holiday season.

If you are using a released version of Istio (1.0.z series) this issue cannot occur.  This would indicate you are using Istio 1.1 or master.  If you are giving Istio an eval, may I recommend using the release-1.1 branch rather than master.

For preliminary instructions for 1.1, see:
https://github.com/istio/istio.io/issues/2787#issuecomment-443688642

This is partially documented in our preliminary website:
https://preliminary.istio.io/docs/setup/kubernetes/helm-install/#option-2-install-with-helm-and-tiller-via-helm-install

Cheers
-steve

**Comment by linsun** [comment]
@thockin yes, what @sdake said.  Since this file is generated, it is only in the released version right now, not head.

**Comment by vadimeisenbergibm** [comment]
@sdake How about putting the dependencies in the released tar? What is the point of letting the users update dependencies?

**Comment by sdake** [comment]
@vadimeisenbergibm I have said time and again in multiple issue trackers that the released tarball should be generated using `helm package -u`.  This will generate a tarball with all dependencies packaged and ready to be deployable from a helm repo add operation.

Further `helm fetch` can be used with `helm template` from a `helm package -u` packaged tarball.  Also `helm install` can also be used with a `helm package -u` packaged file.

However, for developers, this model doesn't work as they must run `helm dep update` or `helm package -u` on their own.  We do provide nightly builds of the manifests.

In most cases, I'd just run:
`make generate_yaml` and move on to the next problem as a dev :)

Cheers
-steve

**Comment by esnible** [comment]
Should we revise the docs to explain what should be done when encountering this error installing from a local fork or daily?

When I get this error I know to run `helm dependency update install/kubernetes/helm/istio` but I am not sure why I do this.  I have just always done it.

**Comment by sdake** [comment]
@esnible We could, although our istio.io website is user-facing, not developer facing.  We have a developer wiki for this type of content though.

I still recommend *not* running `helm dep update install/kubernetes/helm/istio` but instead using `helm package -u`.

Cheers
-steve

**Comment by linsun** [comment]
@esnible that is a good idea, probably worthy a warning in our doc as quite a few folks reported this.

**Comment by linsun** [comment]
I think this is no longer relevant and doesn't exist in 1.1
