### ISSUE TITLE
API load testing has better success rate without sidecars. Is this normal?

### ISSUE THREAD

**Issue by popaaaandrei** [istio/istio#10641]
**Describe the bug**
I have a service that exposes a simple API. I want to perform API load testing and I have tried it with and without the Envoy sidecar (thus managed by Istio or not). The service is exposed either through the Istio Ingress Gateway or behind Ambassador API Gateway. The issue happens with both.

What happens is that when I don't have the sidecars deployed I get almost everytime 100% success ratio (all requests hit Ambassador). With the sidecars I get something between 80-99% but never 100% (Ambassador / Istio ingress gateway). What could be the cause of these drops?

Vegeta also reports `dial tcp 0.0.0.0:0->XXX.XXX.XXX.XXX:80: socket: too many open files` when the errors occur.

**Expected behavior**
100.00% success ratio.

**Steps to reproduce the bug**
I am using Vegeta as load testing tool: `echo 'GET http://XXX.XXX.XXX.XXX/hello' | vegeta attack -rate 500 -duration 10s | tee results.bin | vegeta report`. This is just a simple "hello world" route.

**Version**
Istio 1.0.5
Kubernetes v1.11.2-gke.25

**Installation**
Istio 1.0.5 was installed via Helm templates, as instructed in the installation instructions.

**Environment**
Google Kubernetes Engine cluster with Istio 1.0.5

**Comment by popaaaandrei** [comment]
Second test, disabled automatic sidecar injection and added Envoy manually with istioctl inject. Works like a charm. 100% every time :)

**Comment by sdake** [comment]
@ayj seems like an odd behavior with injection?

**Comment by popaaaandrei** [comment]
It appears so, yes. I will test some more.
