### ISSUE TITLE
User Agent Information is getting ignored in traffic routing in BookInfo

### ISSUE THREAD

**Issue by BanerjeeDeb** [istio/istio#10666]
Even if one creates VirtualService as
...
  http:
  - match:
    - headers:
        user-agent:
          regex: ".*Chrome.*"
    route:
...

the Http header gets ignored and the intended route is not taken.

Long (llcao@cn.ibm.com) located the issue in the code -- the Productpage micro-service is dropping the header. Long already has a fix for the code 
 **Describe the bug**
See above.

**Expected behavior**
Red stars in the review -- going to version 3 of the review microservice.

**Steps to reproduce the bug**
{{ Minimal steps to reproduce the behavior }}
Use the following VirtualService and access BookInfo Productpage from chrome

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews
spec:
  hosts:
    - reviews
  http:
  - match:
    - headers:
        user-agent:
          regex: ".*Chrome.*"
    route:
    - destination:
        host: reviews
        subset: v3
  - route:
    - destination:
        host: reviews
        subset: v2
**Version**
{{ What version of Istio and Kubernetes are you using? Use `istioctl version` and `kubectl version` }}
Istio 1.0.4 and 
**Installation**
{{ Please describe how Istio was installed }}
From Helm Chart
**Environment**
{{ Which environment, cloud vendor, OS, etc are you using? }}
IBM Cloud Private
**Cluster state**
{{ If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue. }}

**Comment by pilhuhn** [comment]
Ha, wanted to open a similar one for quite a while. Thanks for doing this and thanks @morvencao for fixing that in the code.
