### ISSUE TITLE
Envoy security destination rule policy not working as expected

### ISSUE THREAD

**Issue by ervikrant06** [istio/istio#10673]
**Describe the bug**
namespace define in destinationrule is not honored by Istio policy. 

**Expected behavior**
Services in other namespace which is not allowed in destinationrule shouldn't be able to contact the service for which the policy is implemented. 

**Steps to reproduce the bug**

- Create policy and destination rule. 

~~~
cat <<EOF | kubectl apply -f -
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "default"
  namespace: "helloworld"
spec:
  peers:
  - mtls: {}
EOF


cat <<EOF | kubectl delete -f -
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "helloworld-tls"
  namespace: "curlworld"
spec:
  host: "helloworld.helloworld.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
EOF
~~~

- Create new namespace `curlworld1`, deploy new POD in this NS with sidecar, it's able to reach helloworld service running in helloworld namespace. As per destination rule, ideally on services from `curlworld` should be able to contact helloworld service. 

**Version**
~~~
kubectl version --short
Client Version: v1.10.0
Server Version: v1.13.0

istioctl version
Version: 1.0.5
GitRevision: c1707e45e71c75d74bf3a5dec8c7086f32f32fad
User: root@6f6ea1061f2b
Hub: docker.io/istio
GolangVersion: go1.10.4
BuildStatus: Clean
~~~
**Installation**
Using istio minimal install following the official guide. 

**Environment**
minikube setup

**Cluster state**
{{ If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue. }}

**Comment by diemtvu** [comment]
This is working by design. DestinationRule applied to host (destination) are the same, regardless of namespace.

Add @costinm to comment on upcoming changes.

**Comment by liminw** [comment]
Authentication policy uses "namespace" as access control boundary. DestinationRule does not. I agree this is a bit confusing. 

There are a few proposals on controling networking policies (including DestinationRules) scopes. I think the latest proposal is https://docs.google.com/document/d/1x8LI3T7SHW-yDrrt3ryEr6iSs9ewMCt4kXtJpIaSSlI/edit?pli=1#heading=h.o9naebk7osi6 

cc @louiscryan
