### ISSUE TITLE
Allow external Mixer plugins to edit request headers

### ISSUE THREAD

**Issue by robertpanzer** [istio/istio#10679]
Mixer adapters are able to edit request and response headers via the `istio.io/istio/mixer/pkg/adapter/CheckResult.RouteDirective`.
However this property is not available in the API type `istio.io/api/mixer/adapter/model/v1beta1/CheckResult`.
Therefore external Mixer plugins are not able to edit request and response headers.

It would be nice to have this as well.

**Comment by robertpanzer** [comment]
Ideally there should be only one type to transport a CheckResult independent of if the adapter is internal or external to the mixer.

**Comment by kyessenov** [comment]
Both in-process and out-of-process support the route directive. There are integration tests in the code base that include samples, but please make sure to look at the developer guide: https://github.com/istio/istio/wiki/Route-directive-adapter-development-guide

The API for out-of-process adapters does not use CheckResult directly. Instead, it uses a generic output proto-type, from which the operations are constructed using the policy rules. 

I generally agree that there could be work done to refactor the code to eliminate the dual proto-based CheckResult and gostruct-based CheckResult, but we're moving away from in-process adapters to out-of-process adapters in general, and have pushed back on the clean-up efforts for in-process adapters.

**Comment by robertpanzer** [comment]
Thanks for the pointer.
Now I also found the docs for the config in the preliminary Istio docs.
That means though that I would have to build a second version of the adapter that is not compatible with 1.0, right?
