### ISSUE TITLE
Expose watch functionality for Istio CRDs

### ISSUE THREAD

**Issue by mdhume** [istio/istio#10688]
**Describe the feature request**
Expose watch functionality for Istio CRDs. 
Currently the Istio CRD client only exposes Get, List, Create, Update, Delete functions - https://github.com/istio/istio/blob/master/pilot/pkg/config/kube/crd/client.go#L331-L495
However these are not sufficient to set up a watch on any of the Istio CRDs. 
Existing pilot controller code does create an Informer however most of the data structures and functions are private.
I would like to propose adding 2 new functions ListFunc and Watch which can be used to create a ListWatch struct.
I can also submit a pull request for the same

cc: @mandarjog

**Comment by sdake** [comment]
@mdhume the project direction is to use Galley to watch CRDs.  Galley consolidates CRD watching and then exposes that information via MCP.  The main rationale is the ListWatch API is very expensive for kubeapi to handle, and we want to minimize the impact there as much as possible.

If you plan to implement gaps that exist in MCP in galley, why not just submit a PR that does that work?

See this readme for more detail:
https://github.com/istio/istio/blob/master/galley/README.md

**Comment by mdhume** [comment]
@sdake Seems like the mcp client code is not present in Istio 1.0.x - only present in istio-1.1.snapshot -https://github.com/istio/istio/blob/1.1.0.snapshot.1/pilot/pkg/config/coredatamodel/controller.go 

Since Istio 1.1 is not released yet, could we temporarily add support for the functions I mentioned in the client code and then switch over to using galley subsequently. We are blocked on upgrading to Istio 1.0.x until this support is added.

**Comment by ayj** [comment]
Galley w/MCP is available in Istio 1.1+. We don't have any plans to backport to 1.0.x. 

@mdhume, it looks like you might be using pilot/pkg/config/kube/crd/client.go as a client library for accessing Istio CRDs from 3rd party code? If so, you might be to track https://github.com/istio/istio/issues/8772 which would solve this problem for _all_ Istio CRDs. This won't decrease load on the k8s apiserver, but since you're implementing an k8s admission controller out-of-tree, it might be better to integrate at the k8s level rather than ingest via MCP.

**Comment by sdake** [comment]
@mdhume I don't believe there is another planned release of the 1.0 series.  I think @mandarjog leads the maintenance branch, but I'm not certain.  We don't typically add features to stable releases, however.

Cheers
-steve

**Comment by sdake** [comment]
> @sdake Our use-case is that we have an admission controller for ingress resources which ensures that no 2 ingresses claim the same host names. We want to extend that controller to support gateways in the case of Istio. Hence we needed a watch on gateway resources so that we have a current view of the gateways in the K8s cluster at all times.
> If I understood you correctly, you are suggesting that since galley already does the work of placing a watch on Istio CRDs, we should add support for a client of MCP protocol in our admission controller to fetch the required data for gateways from galley when an admission request comes in. Please correct me if I am wrong. Do you have an example of an Istio component which has an embedded galley/MCP client?
> Also we are currently upgrading to Istio 1.0.4, does galley already implement a complete MCP server in that version?

This is almost spot on, but as you have found MCP is not available until 1.1.  I am also not clear if MCP supports distribution to third party applications, but I suspect it would be possible.
