### ISSUE TITLE
Trace sample probability in Stackdriver vs. Istio Pilot

### ISSUE THREAD

**Issue by MrSaints** [istio/istio#10687]
Question. In several configurations for Stackdriver, I noticed there is either `sample_probability: 0.1` or `sampleProbability: 0.1` defined (a separate issue, but I am also quite curious what is the _correct way_ here). From my understanding, this configures the sampling probability on the side of Stackdriver.

There is also a configuration for Pilot, `PILOT_TRACE_SAMPLING`.

I am curious what is the interaction between the two if say the latter (Pilot) was set to 0.5, and the former to 0.1 (Stackdriver)? Will the true sample probability then be 0.05?

At the moment, it does not seem like the Stackdriver sampling probability is being used. It seems like all requests are being traced, and ingested by Stackdriver.

**Comment by bianpengyuan** [comment]
There are two data paths to collect trace spans: 1) envoy directly reports to zipkin/jeager. 2) envoy reports to various backends through mixer and its backend adapters (Stackdriver adapter is one of them). Pilot config is for envoy tracing sample rate, which affects data path 1). Stackdriver trace sample rate config takes effect when stackdriver adapter processes data, which happens in data path 2). These two data paths are independent and could coexist. The configs you mentioned would not interfere each other.

**Comment by MrSaints** [comment]
I see, if that is the case, I am quite uncertain as to why it seems to be sampling quite possibly 100% of traces to Stackdriver.
