### ISSUE TITLE
fortio.istio.io down

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#10685]
Something happened ? https://fortio.istio.io/ isn't responding anymore (it serves the perf results)

cc @geeknoid who asked recently about the admin sites config, @ayj who may know how to check/fix it, @mandarjog for perf WG, @rkpagadala (https://fortio-daily.istio.io/ somehow is still up)

**Comment by geeknoid** [comment]
The DNS entry for fortio.istio.io points to 35.197.102.163. I can ping that address. But trying to access the web site there fails with ERR_CONNECTION_REFUSED. Both for http: and https:.

**Comment by ayj** [comment]
```
$ dig +short fortio.istio.io 
35.197.102.16

$ curl https://fortio.istio.io
curl: (7) Failed to connect to fortio.istio.io port 443: Connection refused
```

**Comment by ayj** [comment]
Ingress can't get configuration from Pilot. 

```
[2019-01-02 21:06:30.803][10][info][upstream] external/envoy/source/server/lds_subscription.cc:70] lds: fetch failure: network error
[2019-01-02 21:06:32.763][10][info][upstream] external/envoy/source/server/lds_subscription.cc:70] lds: fetch failure: network 
```

Possibly related to https://github.com/istio/istio/issues/3757. It looks like we may still be running Istio 0.7.x. cc @mandarjog for upgrading Istio/fortio perf cluster.

**Comment by ldemailly** [comment]
maybe the cluster k8s autoupgrade caused problems and it just needs a
restart.

don’t blindly upgrade from 0.7 as it won’t work with the ingress spec and
certmanager setup

assuming you can first restore fortio.istio.io (maybe a simple restart of
pilot?) I would test a 1.x setup on fortio-stage first (which also runs
fortio-daily.istio.io which somehow still works so maybe check what has
become different between  the 2 clusters that only 1 stopped working)

**Comment by ayj** [comment]
fortio.istio.io seems to be working again after I restarted Pilot, Ingress, and CA. I'll defer to @mandarjog on upgrading the control plane.

**Comment by ldemailly** [comment]
thanks jason!

**Comment by ldemailly** [comment]
@mandarjog try the same for fortio-daily (fortio-stage is the name in gcloud console) which is down this time ?

**Comment by mandarjog** [comment]
Yes I just restarted everything and no change. Need to debug more, I would prefer just getting a fresh 1.1 now and starting from there.
