### ISSUE TITLE
LetsEncrypt very hard to setup 

### ISSUE THREAD

**Issue by nigel-dewar** [istio/istio#10697]
**Describe the feature request**
Whilst researching istio to use (first time) I found the whole setup around letsencrypt completely missing!

The istio doco goes over creating a self signed cert, and using that, who does that?  thats crazy these days when you have letsEncrypt

Istio's only loading up 1 secret for the entire stack, is really quite poor. There needs to be a decent way of managing this

**Describe alternatives you've considered**
Consul seem to have a good system for this. Nginx, works well with cert-manager, so does traefik. Please have a look at these systems and see if something similar can be achieved.

**Additional context**
Make it easy for people and they will use it. For me, looking at it with fresh eyes, I see Istio completely lacking in this area.

**Comment by sdake** [comment]
Istio does have an implementation of certmanage (Reference: r, but from what I can tell (which isn't exhaustive) - there is no documentation for certmanager's integration with Istio.

I agree with your assessment that the documentation could be improved in this area to point out how certmanager could be used.  Can you file an issue here to track the documentation ssue?

https://github.com/istio/istio.io/issues/new

If your willing to contribute documentation for certmanager integration, that would be even better!

I'd do it myself, but unfortunately, I don't know how to use certmanager with Istio...

Cheers
-steve

**Comment by sdake** [comment]
https://github.com/istio/istio/issues/6486

**Comment by nigel-dewar** [comment]
Thanks @sdake , unfortunately I only have a few days off in break and then going back to work, so I cant spend the time. I'll watch and wait till something happens, Im sure somebody in 2019 will sort it out. hopefully.
