### ISSUE TITLE
app access  on external VM after mesh expansion

### ISSUE THREAD

**Issue by SrinivReddy** [istio/istio#10691]
Hi, I am unable to access k8s app on external VM with ROOT user after implementing mesh expansion, I am able to access the application with all other users. what may be the reason any idea???

I have implemented mesh expansion in AWS, 
In AWS, UDP protocol LoadBalancer is not supporting so I took NodePOrt for exposing Kube-DNS.
'
And, Used weave overlay for acceesing app from external VM.

**Comment by devops083** [comment]
Today, I tried to configure mesh expansion in GKE, after configuring mesh expansion on GKE, there also I am not able to access k8s services with ROOT user.
