### ISSUE TITLE
Zero downtime Deployments and HPA with services using Istio

### ISSUE THREAD

**Issue by jaygorrell** [istio/istio#10703]
**Describe the feature request**
When rolling out new pods in Kubernetes, it's a common solution to add a `preStop` lifecycle hook to wait before cleaning up the pod so that the application can handle the sigterm. In Istio, this doesn't work because the cause is different -- it's based on local caching.

Details for these are written up very well by @sdaschner here:
https://blog.sebastian-daschner.com/entries/zero-downtime-updates-kubernetes
https://blog.sebastian-daschner.com/entries/zero-downtime-updates-istio

The solution for Istio, then, is to use blue/green deployments -- which also works for native Kubernetes. This solves deployments, but then we're stuck without using HPA. I'd like to see something more native to Istio that solves this problem for both Deployments as well as HPA.

**Describe alternatives you've considered**
As mentioned above, blue/green was considered but it only solves the issue for actual deployments and not HPA. Using Istio retries was also considered but it feels more like a band-aid.

**Comment by dozer47528** [comment]
Have the same problem for high traffic service.

**Comment by jaygorrell** [comment]
Not stale.

**Comment by howardjohn** [comment]
@jaygorrell we introduced a new feature to do a graceful termination of Envoy. So when a sigterm is received, envoy will stay alive for 5s (by default) and stop accepting new connections before shutting down.

This seems to solve the problem you are having, and from my testing it seems to pretty reliably allow zero-downtime deployments. I have tested with deploying a server repeatedly while sending requests and seeing no 503s.

Is this sufficient for this or are there other changes required as well?

**Comment by jaygorrell** [comment]
@howardjohn What version is that in? 

It's typical to add a `preStop` hook with a sleep on k8s deployments so the service changes can propagate (removing the pod from the pool) before the pod is actually told to shut down. Then the pod receives the usual termination handler. With that change, it would replace this preStop hook, right?

Aside from that, I'm not sure if this really solves this issue, at least conceptually - I haven't tested the new changes. It sounds like there would still be the eventual consistency problem that's sorta' the focus of this issue that requires 5xx retries.

This sounds like it would be more of a fix for allowing a pod to continue with outbound requests after the sigterm is received. I'll check it out though.

**Comment by howardjohn** [comment]
It should be in 1.1

**Comment by howardjohn** [comment]
Please try out the new feature and open an issue if that isn't working. Thanks!
