### ISSUE TITLE
 Integrate Istio Citadel agent and Vault on VM

### ISSUE THREAD

**Issue by myidpt** [istio/istio#10712]
**Describe the feature request**
The Citadel Agents running on VMs should be able to request certificates from Vault.

**Additional context**
This work is related to https://github.com/istio/istio/issues/10356.

**Comment by esnible** [comment]
Also related to #10599 .

**Comment by pitlv2109** [comment]
@lei-tang I have this PR here https://github.com/istio/istio/pull/13410  that supports GoogleCA for VM. You may find it helpful.

**Comment by lei-tang** [comment]
@pitlv2109 Thanks!
