### ISSUE TITLE
Configuration of rate-limiting doesn't work on grpc service

### ISSUE THREAD

**Issue by denglouping** [istio/istio#10719]
I have a pod that provide both http and grpc api at different ports

I wrote a configuration of rate limiting, and when I test the http port, I witness the qutota is exhausted error, but when it comes to the grpc port, it just worked as usual. I wonder if I missed some special parameters in the configuration when you want to limit a grpc port or does istio just not support rate-limiting for grpc?

**Comment by klustria** [comment]
Can you please provide a sample of your configuration and your test case scenario?
