### ISSUE TITLE
istio-tracing Readiness probe failed

### ISSUE THREAD

**Issue by wql6** [istio/istio#10722]
**Describe the bug**
When I was installing the istio software, I encountered the following problem "Readiness probe failed" when executing statements " kubectl istio-1.0.apply -f istio-1.0.0/install/kubernetes/istio-demo.yaml"

**Expected behavior**
`
# istioctl version
```
Version: 1.0.5
GitRevision: c1707e45e71c75d74bf3a5dec8c7086f32f32fad
User: root@6f6ea1061f2b
Hub: docker.io/istio
GolangVersion: go1.10.4
BuildStatus: Clean
```

#kubectl get pods -n istio-system
```
NAME                                        READY   STATUS             RESTARTS   AGE
grafana-9fffc4c5-mqch8                      1/1     Running            0          147m
istio-citadel-7d7645c94f-9m9ld              1/1     Running            0          147m
istio-cleanup-secrets-q52mg                 0/1     Completed          0          147m
istio-egressgateway-5cbdfb649-5qjqs         0/1     CrashLoopBackOff   19         147m
istio-galley-6488668994-rcs8h               1/1     Running            0          147m
istio-grafana-post-install-7v2lc            0/1     Completed          0          147m
istio-ingressgateway-9549f988d-wm25x        0/1     CrashLoopBackOff   19         147m
istio-pilot-6c54b59bc7-hrjsq                2/2     Running            0          147m
istio-policy-787bc8cc69-mcpck               2/2     Running            0          147m
istio-sidecar-injector-677c9d8549-zpr9d     1/1     Running            0          147m
istio-statsd-prom-bridge-67bbcc746c-q2987   1/1     Running            0          147m
istio-telemetry-6d68c5cc6-d5mql             2/2     Running            0          147m
istio-tracing-6445d6dbbf-jjblq              0/1     CrashLoopBackOff   45         147m
prometheus-6967c997cf-b6h5h                 1/1     Running            0          147m
servicegraph-657b46dd78-hxpcl               0/1     Running            52         147m
```

# kubectl describe pod istio-tracing-6445d6dbbf-jjblq -n istio-system
```
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  default-token-k2jvq:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-k2jvq
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     <none>
Events:
  Type     Reason     Age                     From                Message
  ----     ------     ----                    ----                -------
  Warning  BackOff    5m24s (x470 over 139m)  kubelet, k8s-node1  Back-off restarting failed container
  Warning  Unhealthy  19s (x182 over 145m)    kubelet, k8s-node1  Readiness probe failed: Get http://10.254.86.11:16686/: dial tcp 10.254.86.11:16686: connect: connection refused
```

How can I get istio running？

**Comment by esnible** [comment]
We must determine why istio-tracing, istio-ingressgateway, and istio-egressgateway are crashing for you.  Can you do `kubectl logs -n istio-system <pod>` to see if there are error messages?

**Comment by sdake** [comment]
@wql6 you mentioned that the readiness probe failed in 1.0.0, but your istioctl indicates you have a 1.0.5 binary.  Can you clarify if you installed the 1.0.5 demo yaml?

I believe readiness probes in 1.0.0 were a little flakey, but YMMV.

Cheers
-steve

**Comment by objectiser** [comment]
@douglas-reid Have tested with 1.0.5 and worked for me - as @sdake has indicated, it looks like a version mismatch, but waiting for @wql6 to confirm.

**Comment by piyushkumar13** [comment]
Sharing my experience, it might help someone else. I was facing the same issue in minikube. I was having istioctl and controlplane both with version`1.3.0`. For me when I initially installed, it was working fine however after few **minikube start and stop** `istio-tracing` was giving status `CrashLoopBackOff` with error `Readiness probe and Liveliness failed with connection refused`. As mentioned in this post : https://discuss.istio.io/t/istio-galley-istio-telemetry-istio-policy-pods-are-in-crashloopbackoff-state/1181/4, I changed the istio-tracing yaml manifest to have imagePullPolicy to `Always`, it started working.
