### ISSUE TITLE
Enable 128 bit x-b3-traceid istio-proxy/Envoy headers

### ISSUE THREAD

**Issue by kbhattac** [istio/istio#10732]
**GCP Stackdriver Trace/Logging correlation requires 128 bit traceid**

Istio traces don't have log correlation as traceids are not properly filled up:

`
timestamp>="2019-01-04T05:31:34.408000Z" timestamp<="2019-01-04T05:31:54.411000Z" (trace="projects/coolretailer/traces/00000000000000000c627e0ffa7588b3" OR labels."appengine.googleapis.com/trace_id"="00000000000000000c627e0ffa7588b3")
`

Envoy is default configured to provide 64bit x-b3-traceid headers but can be configured for 128 bit in `envoy_bootstrap_tmpl.json` [example](https://storage.googleapis.com/share-it/envoy_bootstrap_tmpl.json) of the sidecar [istio-proxy](https://hub.docker.com/r/istio/proxyv2) container:
```
  "tracing": {
    "http": {
      "name": "envoy.zipkin",
      "config": {
        "collector_cluster": "zipkin",
	"trace_id_128bit": true
      }
    }
  }
```
Thoughts?

**Comment by objectiser** [comment]
Agree we should switch to 128bit.

**Comment by douglas-reid** [comment]
This should be the default in 1.1 now. Closing, pending indications that more work is needed.
