### ISSUE TITLE
Deprecate config.istio.io/v1alpha2 CRD group

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#10746]
This is technical debt from the times of too-many CRDs per each adapter in mixer. The work is to align Mixer's configs by placing them in policy.istio.io/v1alpha3 group-version and the supported kinds:
- attributemanifest
- rule
- instance
- handler

This is also a chance to re-evaluate the config protos.

/cc @ozevren 
/cc @geeknoid

**Comment by kyessenov** [comment]
@ozevren I've started looking into this issue. Can you clarify the expectations how things should look like in the end? Do we want to support the legacy k8s and "fs" config backends in mixer for policy.istio.io/v1beta1 group? Does MCP provide an auto-conversion mechanism, to avoid subscribing to both config.istio.io/v1alpha2 and policy.istio.io/v1beta1 groups?

**Comment by ozevren** [comment]
The plan for Galley is to enable it by default in 1.1, and retire the K8s based code (in favor of MCP) in Pilot & Mixer in the next release, when Galley stabilizes.

Separately, the legacy CRDs are subject to the standard deprecation policies. So we will need to first deprecate them and remove them after a set period.

In Galley, we can do the legacy => standard config conversion. Currently it is not setup that way, but it should be pretty straightforward to do, as long as someone is willing to do it. :)

**Comment by kyessenov** [comment]
Sounds good to me. I'll focus on MCP version only, and rely on Mixer to subscribe to both for now.
On an unrelated note, it'd be good to document how to run MCP server locally. I run mixs locally, and without k8s backend, mcps becomes a necessity.

**Comment by douglas-reid** [comment]
@kyessenov any updates here? are we able to close this yet?

**Comment by kyessenov** [comment]
There was no progress to move away from config.istio.io/v1alpha2 CRD API group AFAIK.

I think this would become easier once Mixer k8s dependency is entirely eliminated, since the support for two API groups would only need to be implemented in Galley

I'm not sure about the status of Galley API group conversion. Technically, Galley can listen to two different CRDs, but I don't know if auto-conversion from one to another is supported.

Before we graduate policy&telemetry configs, we should also consider whether the current config protos are what we want in the future. Technically, these are already v1beta1 in istio/api but they appear as v1alpha2 in k8s.

**Comment by markmssd** [comment]
Is it possible that v1alpha2 is remove in Istio 1.3.0? Installing it with the K8S Helm Chart throws an error on this `config.istio.io/v1alpha2`, saying it's not available. Disabling `policy` and `telemetry` (to skip yaml files that use this version) makes the installation succeed.

**Comment by douglas-reid** [comment]
I think it is safe to close this issue now.
