### ISSUE TITLE
CRDs should be removed with Istio Helm charts

### ISSUE THREAD

**Issue by arun-gupta** [istio/istio#10749]
**Describe the bug**

CRDs are not deleted during Istio Helm chart deletion

**Expected behavior**

Deleted Istio as:

`helm del --purge istio`

Tried installing Istio again using the Helm chart. It reported:

```
Error: customresourcedefinitions.apiextensions.k8s.io "gateways.networking.istio.io" already exists
```

CRDs should have been removed for a clean removal of Istio.

**Steps to reproduce the bug**

Install Istio: 

```
helm install \
		--wait \
		--name istio \
		--namespace istio-system \
		install/kubernetes/helm/istio
```
Delete istio: `helm del --purge istio`

Install again

**Version**

```
Version: 1.0.5
GitRevision: c1707e45e71c75d74bf3a5dec8c7086f32f32fad
User: root@6f6ea1061f2b
Hub: docker.io/istio
GolangVersion: go1.10.4
BuildStatus: Clean
```

**Installation**

Helm charts

**Comment by rvennam** [comment]
This is expected. Please see https://github.com/istio/istio/issues/7688

**Comment by arun-gupta** [comment]
Helm version:

```
helm version
Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
```

This is a freshly installed k8s cluster.

What else should be done?

**Comment by sdake** [comment]
@arun-gupta for Istio 1.0.z you can manually delete the crds that have been registered using
`kubectl delete -f install/kubernetes/helm/templates/crds.yaml`.  In 1.1, we are resolving this by adding an initializaiton chart.  You can follow that work here:

https://github.com/istio/istio/pull/10562

**Comment by arun-gupta** [comment]
@sdake yep, I've been deleting it manually for now, will close the issue.

**Comment by ajaychebbi** [comment]
> @arun-gupta for Istio 1.0.z you can manually delete the crds that have been registered using
> `kubectl delete -f install/kubernetes/helm/templates/crds.yaml`. In 1.1, we are resolving this by adding an initializaiton chart. You can follow that work here:
> 
> #10562

I had to use ``` kubectl delete -f install/kubernetes/helm/istio-init/files/crd-10.yaml ``` to delete the crds manually
