### ISSUE TITLE
istio-mesh state is Down

### ISSUE THREAD

**Issue by neweyes** [istio/istio#10759]
Hi，all. This problem has been bothering me for a few days. I have no idea about it now, How can I get it running？

![2019-01-06 14 58 33](https://user-images.githubusercontent.com/8642098/50733169-9e154600-11c3-11e9-9449-b37a79cf8c9b.png)
![2019-01-06 14 58 43](https://user-images.githubusercontent.com/8642098/50733173-a53c5400-11c3-11e9-8fd2-54e1b917587c.png)

**Comment by douglas-reid** [comment]
Have you tried going through any of the operations guide: https://istio.io/help/ops/telemetry/missing-metrics/ ?

I'm going to close this issue, as the istio-users mailing-list is a better channel for support and discussion of this nature.

If you feel that this is a novel issue, please feel free to reopen.

**Comment by alexanderbuhler** [comment]
As a possible solution for anyone having the same problem and possibly myself in the future. 🤣 

For some reason, although I've seen those values already set in the chart default, the corresponding handlers were not installed initially, leading to the missing adapter on port 42422.

After I've explicitly set them in my custom provided values, handlers were installed.

```yaml
      adapters:
        prometheus:
          enabled: true
```
