### ISSUE TITLE
Feature: Service aliases

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1076]

**Comment by ldemailly** [comment]
Andra has started a doc: https://docs.google.com/document/d/1XVigTQ1pZZIdfm94MyQChexh8BFTMjZSiCbVtMtT-7I/edit#heading=h.x9snb54sjlu9

**Comment by andraxylia** [comment]
Is this issue about Bring your Own Service Name? There is nothing in the description.

**Comment by costinm** [comment]
Yes, 'service alias' is part of 'bring your own service name' - but the
current design covers a bit more than aliases.

**Comment by rshriram** [comment]
Given that a doc exists and the feature is tracked elsewhere, closing this cryptic issue.

**Comment by ldemailly** [comment]
where is it tracked?

**Comment by costinm** [comment]
This has been implemented - alpha3 API supports this first class. I think
there is even a test :-)
