### ISSUE TITLE
Galley: Add support for outgoing connections.

### ISSUE THREAD

**Issue by jeffmendoza** [istio/istio#10785]
As seen in MCP enhancements (https://goo.gl/RTKMwF). MCP can be initiated from Galley out to a "ConfigSink" service. This issue is to track adding support to Galley for it to be able to initiate these connections.

I am working on a doc with details on an implementation that I will share soon.

**Comment by Nino-K** [comment]
Just going to throw the corresponding PR's in here so it's easier to keep track of this. 
Proto updates: https://github.com/istio/api/pull/741 and Pilot changes: https://github.com/istio/istio/pull/10635

**Comment by jeffmendoza** [comment]
>Just going to throw the corresponding PR's in here so it's easier to keep track of this.

In addition to those, #10834 will be used for config.

**Comment by jeffmendoza** [comment]
Things we need:

* #10834 So callout config can be specified
* #11068 Auth to be used for callout
* #11040 Actual MCP source client code.

Then we can have code to do the actual callout.

**Comment by ozevren** [comment]
I believe this is done, right? Can we close?

**Comment by jeffmendoza** [comment]
Yep
