### ISSUE TITLE
Update in envoy breaks route directive for some headers.

### ISSUE THREAD

**Issue by GregHanson** [istio/istio#10783]
**Describe the bug**
As discovered here:
https://github.com/istio/istio/pull/10737

**Comment by kyessenov** [comment]
@rshriram @duderino : A quick investigation makes me think there is some transient bug in envoy that make it set `content-length` header even if filters explicitly remove it. Proving this would require building a new filter in envoy and validating it with a custom build. I noticed that we picked a random SHA in envoy (2525...). Was there a logic behind which SHA we picked for 1.1 release? Should we pick a released and a qualified SHA of envoy instead?

**Comment by kyessenov** [comment]
After looking at the code and experimenting, it seems that envoy auto-inserts content length = 0 header for requests with empty bodies. So this issue is restricted to requests with no bodies and directives that want to remove the content length header.

**Comment by munrodg** [comment]
Closed

**Comment by sameerbhadouria** [comment]
I am seeing "content-length: 0" header in the response (status code is 101 Switching protocols)  to our Websocket connection upgrade request. 

We have Istio version 1.6.3 which uses Envoy version 1.4.1
I believe this should have been fixed - at least based on https://github.com/envoyproxy/envoy/issues/5554 

Do I need to enable any flags for this to work?
