### ISSUE TITLE
Incomplete tests: Run istio control plane (at least mixer) on Specific VMs (ubuntu and debian)

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1079]
Context: [production readiness proposal and plan](https://goo.gl/pmjuYg)

The feature “_Run istio control plane (at least mixer) on Specific VMs (ubuntu and debian)_” is identified as incomplete test coverage. As a measure to reach Istio production quality in 0.3, this issue is opened to track the progress of providing sufficient test coverage for the feature in question.

This issue is initially assigned to the working group leads.

**Recommendations**:
- Come up with a test plan for how the feature should be tested. Identify and document (in this issue, or a separate document this issue will link to) test cases and whether each will be covered by an integration test (with some level of mocking and/or starting up selected components in test environment), or end to end test (aka system test, which brings up the whole Istio to exercise the feature; currently live in the istio/istio repo).
- If you expect the test plan is complex and controversial, consider having it formally reviewed.
- State an ETA in the issue, and assign this to a developer who will execute the test plan.
- Execute the test plan as the highest priority for 0.3.
- For any bug or defect identified by the new test cases, file a new issue and link it from this one.
- Close this issue only when the test plan is completely executed, and all additional issues identified in step 3 are fixed.

If you see a risk of not fixing this issue by end of 0.3, please contact istio-production-quality@googlegroups.com as soon as possible. We will also periodically ping the issue for update.

**Comment by costinm** [comment]
No longer planned for 0.3 or 0.4.

There are still efforts to make it work - but will not be considered production ready.
