### ISSUE TITLE
gateway/virtualservice  404 access url when using chrome

### ISSUE THREAD

**Issue by liyongxian** [istio/istio#10794]
**Describe the bug**
 I configure ingress gateway/virturalservice,when using chrome access the url,happen 404.However,Using Nginx-ingress is OK. The DNS "istio-designer.hiacloud.net.cn" is OK.(ping by CMD is OK)
**URL: http://istio-designer.hiacloud.net.cn**

**Expected behavior**
  exactly access the url by chrome.
**Steps to reproduce the bug**
    ### ----gateway
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: designer-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
         number: 80
         name: http
         protocol: HTTP
      hosts:
       - "istio-designer.hiacloud.net.cn"
### -----virtualService
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: designer
spec:
  hosts:
    - "istio-designer.hiacloud.net.cn"
    gateways:
    - designer-gateway
    http:
     - match:
      - uri:
          exact: /
      route:
      - destination:
            host: designer.test.svc.cluster.local
            port:
               number: 6888

**Version**
Version: 1.0.5
GitRevision: c1707e45e71c75d74bf3a5dec8c7086f32f32fad
User: root@6f6ea1061f2b
Hub: docker.io/istio
GolangVersion: go1.10.4
BuildStatus: Clean

**Installation**
helm template install/kubernetes/helm/istio --name istio --namespace istio-system > $HOME/istio.yam

**Environment**
### 1.OS
Ubuntu 16.04.5 LTS
### 2.Kubernetes
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**Cluster state**
**1.istioctl pc listener**
ADDRESS         PORT     TYPE
10.42.2.188     6888     HTTP
0.0.0.0         6888     HTTP

**2.istioctl pc route**
 6888                                                                                     1
inbound|6888||designer.test.svc.cluster.local     1

**Thanks.**

**Comment by wstrater** [comment]
I am getting 30% to %70 success rate when I go through a Gateway and VirtualService using `curl`. Deleting a reapplying sometimes helps but not always.

I have a long write up with lots of output that I can submit if that will help. If not I will spare you.

Versions kops: 1.11.0, istioctl: 1.0.5, kubectl Client: v1.13.0, Server: v1.11.6

Thanks, Wes.

**Comment by liyongxian** [comment]
@wstrater Thanks.It happens to me sometimes,I don't know why.
I am trying to test Istio-inggress for replacing Nginx-ingress,especially in L4 routers.

**Comment by wstrater** [comment]
I didn't see a DestinationRule in your post. I have not gone back but I don't think my test had one either. My latest works does and I am not experiencing the same issues. 

Wes.

**Comment by nparfait** [comment]
Did you resolve this issue? I'm having a similar problem. I have an istio cluster (1.0.5) on GKE (1.11.5-gke.5). I have 2 namespaces which are running 2 versions of my application.
ie. ns1 - console.dev.domain.com 
and ns2 - console.demo.domain.com
I have gateway/virtualsvc/destinationrule in each ns

using chrome/firefox if i access 1 domain the other will then 404, I can them open an incognito tab and do the reverse (which ever 1 I access first seems to work) and have the opposite.  Seems to work with Safari, though I don't think its browser related

This is the log entry from the ingressgateway pod in istio-system
**Request which doesn't work**
[2019-01-29T06:08:11.332Z] "GET /HTTP/2" 404 NR 0 0 2 - "10.152.0.6" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36" "9871dbe4-fdc9-40d0-999f-8797b2778d20" "customer-console.dev.mydomain" "-" - - 10.0.7.91:443 10.152.0.6:54168

**Request which works**
[2019-01-29T06:09:13.602Z] "GET /HTTP/2" 200 - 0 2490 11 7 "10.152.0.6" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36" "864f3622-c46b-411b-97b9-0a59e9823058" "customer-console.dev.mydomain" "10.0.7.89:80" outbound|80||eightdpay-dev-customer-console.eightdpay-dev.svc.cluster.local - 10.0.7.91:443 10.152.0.6:54467

I've checked the headers from chrome and both requests are identical.

It appears like istio is caching something which then causes the request to the 2nd url to fail once the 1st url has been access. Closing and reopening the browser then allows this to work in reverse, but never both working at the same time

**Comment by IrfanAnsari** [comment]
Hi All,

I am having the similar issue and wonder if anyone got a permanent solution?

Regards,
Irfan

**Comment by IrfanAnsari** [comment]
This is to just let you all know that we have sorted out this issue. We had multiple Istio Gateway configured identical and most probably confusing Istio. Now we have one Istio Gateway (443 HTTPS) and it's being used by our Istio Virtual services deployed in different name space. VS matches on the basis of the hosts.
