### ISSUE TITLE
SidecarInjection should use one common label

### ISSUE THREAD

**Issue by thomschke** [istio/istio#10796]
**Describe the feature request**
There are two different labels to control the sidecar injection:
- `sidecar.istio.io/inject` on pod level.
- `istio-injection` on namespace level.

**Describe alternatives you've considered**
I would prefer only `sidecar.istio.io/inject`. 
For backward compatibility I would check both labels for a transitional period.

**Comment by thomschke** [comment]
see #10724

**Comment by esnible** [comment]
See also https://github.com/istio/istio.io/issues/3191
