### ISSUE TITLE
Upgrade tests are failing due to helm problems

### ISSUE THREAD

**Issue by hklai** [istio/istio#10806]
Upgrade tests in release qualification started to fail in December, possibly due to helm install problem.

Sample log
https://storage.googleapis.com/istio-prow/pr-logs/pull/istio-releases_pipeline/171/release-upgrade-tests-1.0.1/167/build-log.txt

Error:
Error: found in requirements.yaml, but missing in charts/ directory: sidecarInjectorWebhook, security, ingress, gateways, mixer, nodeagent, pilot, grafana, prometheus, servicegraph, tracing, galley, kiali, istiocoredns, certmanager, istio-cni, telemetry-gateway
helm template failed

**Comment by linsun** [comment]
@ostromart are you looking at this?  if not, I can look at it tmr.  cc @hklai

**Comment by ostromart** [comment]
Yes, I plan to take a look today. Thanks for the offer though @linsun.

**Comment by linsun** [comment]
looks like the test is trying helm from master instead of release -1.1

```+ /home/prow/go/src/istio.io/istio/tests/upgrade/test_crossgrade.sh --from_hub=gcr.io/istio-release --from_tag=1.0.1 --from_path=istio-1.0.1 --to_hub=gcr.io/istio-release --to_tag=master-20190107-09-15 --to_path=istio-master-20190107-09-15```

**Comment by linsun** [comment]
@hklai can you show us how to find the latest test result upgrade test for release-1.1?   should I make this upgrade test in presubmit for easier debugging (e.g. istio release pipeline 1.1 yaml file)?

I also own https://github.com/istio/istio/issues/9185 which is blocked by this issue.

**Comment by linsun** [comment]
I don't think this is still a prob in looking at the latest upgrade test that @hklai (thank you!) pointed to me.  The helm install of 1.1 runs fine.

https://storage.googleapis.com/istio-prow/pr-logs/pull/istio-releases_pipeline/209/release-upgrade-tests-1.0.2/223/build-log.txt

**Comment by hklai** [comment]
These tests are actually failling for release-1.1 too.

See https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio-releases_pipeline/209/release-upgrade-tests-1.0.1/220

See more of these tests at https://prow.istio.io/?repo=istio-releases%2Fpipeline&type=presubmit

**Comment by linsun** [comment]
yes they failed but was a different error and at roll back of control plane thus I opened https://github.com/istio/istio/issues/11054

**Comment by hklai** [comment]
Arh ok. Let's use the new one then.
