### ISSUE TITLE
External adapters should be allowed to set response status and body

### ISSUE THREAD

**Issue by robertpanzer** [istio/istio#10802]
**Describe the feature request**
This feature request is a follow up to #10679.
While it is apparently possible to set request and response headers from an external adapter, it is not possible to set the response status code or response body.
External adapters should be allowed to do everything that an internal, builtin adapter is allowed to do as well.

Builtin adapters can set a response status and body in the RouteDirective: https://github.com/istio/api/blob/73238e149e64663df5651833d16715c3b43caea2/mixer/v1/mixer.proto#L215-L219
This should be supported for external adapters as well.

**Comment by kyessenov** [comment]
@robertpanzer (cc @geeknoid )

The linked proto definition is for the interface between Mixer and the proxy. I don't think we have exposed the capability to modify the response body/code for either internal or external adapters. 

Can you provide more details about your use case? There is some complexity in combining multiple adapters that would like to perform response code/body operations, and we have omitted this capability from the initial implementation due to this complexity.

**Comment by robertpanzer** [comment]
Ah, I see.
An internal adapter could set these fields, but they are eventually ignored here: https://github.com/istio/istio/blob/69d8588ccd743dd1f540d14a494e1b36b6e4506e/mixer/pkg/runtime/dispatcher/session.go#L242-L246
And adding support for this would also require additions to the Rules to apply setting status codes or response bodies.

The motivation for this is that currently istio-proxy will always return HTTP 403 in case of a denied CheckRequest.
There are cases though where other status codes are better suited.
If you look at Github for example, they will return 404 if you're not authorized to access a certain resource, thus giving you no hint that you hit something private that you are not authorized to access.

**Comment by kyessenov** [comment]
Have you tried returning a different Status in the check result? The dispatcher should return the error status back to the proxy, where it is translated to an HTTP code according to gRPC rules: https://github.com/grpc/grpc/blob/master/doc/http-grpc-status-mapping.md

**Comment by robertpanzer** [comment]
Thanks for the pointer! I'll try that and report back.

**Comment by robertpanzer** [comment]
Setting the status code via the grpc status code indeed seems to work, thanks!
The linked document is not complete and not correct though, the full mapping is available here: https://github.com/gogo/googleapis/blob/master/google/rpc/code.proto

I would like to keep this issue open, as I would still like to define the response body.
And setting the status code to other values than the ones given by GRPC would be nice as well, in particular as envoy supports this via its own external authorization protocol: https://www.envoyproxy.io/docs/envoy/v1.9.0/api-v2/service/auth/v2alpha/external_auth.proto#service-auth-v2alpha-deniedhttpresponse

**Comment by kyessenov** [comment]
OK, can you please elaborate on the use case for setting explicit HTTP code and body? Is this for redirect?

If this is something that is needed, then we can extend our config model to support it. I think this amounts to adding direct response next to header operations in a rule.

**Comment by robertpanzer** [comment]
With moving to a Service Mesh we want to move certain tasks like policy enforcement etc to the infrastructure, i.e. Istio.
Existing applications that dealt with these tasks previously created payloads even in case of rejected requests corresponding to the requested content type.
E.g. if an application would reject a request because it has a bad signature, it would respond with a JSON or XML response that could be interpreted by the client.

Now Istio always responds with a plain text response that doesn't follow the defined schema.

Think you have a Swagger description of a service that defines a certain payload in case of some error response.
Now if you want Istio to execute these checks you will never be able to build a response that complies with this description.

**Comment by kyessenov** [comment]
Thanks for clarifying the question. I'm a bit concerned about the necessary API changes to support this. In particular, I'm not sure whether the expressions are a good fit for the request response. One would expect some form of template for the body text. And another issue, is how to combine the results from multiple adapters that want a direct response. We've punted on this combinator issue before (see https://docs.google.com/document/d/1-coh6cK4Tk0_Yw1Vv1JxBUs2aP5miaqo4zCPSFgLiaA/edit?userstoinvite=fabian@simpletechs.net&ts=5bfcf935&actionButton=1 for some discussion). 

Does gRPC fit your needs for now, or should we prioritize the HTTP response code extension?

**Comment by kyessenov** [comment]
@robertpanzer

Both out-of-process and in-process adapter use [grpc.Status](https://github.com/grpc/grpc/blob/master/src/proto/grpc/status/status.proto) as a result. Status has a message string field. This message is then propagated as part of proxy response, for example:
```
handler.adapter.istio-system: <error message from your adapter gRPC status>
```

Does this functionality cover your use case?

**Comment by robertpanzer** [comment]
Not completely.

Apparently there is a selection of a response status and an error message.
It would be great if I could alternatively create a full response payload that is returned to the client instead of a message that is assembled from 3 different parts (Status code, handler name and Status message).

**Comment by kyessenov** [comment]
API proposal: https://github.com/istio/api/pull/765
