### ISSUE TITLE
istio-iptables.sh got exit status 4 occasionally

### ISSUE THREAD

**Issue by andrewshan** [istio/istio#10818]
**Describe the bug**
We try to start proxy_init image, it fail in some time, we got the stdout error as "exit status 4" when executing the istio-iptables.sh. 

**Expected behavior**
Run  istio-iptables.sh return no error eternally

**Steps to reproduce the bug**
This bug can not be reproduced each time, it may occurs when the hosting machine was running iptables same time as the container  

**Version**
istio 1.0.3

**Installation**
{{ Please describe how Istio was installed }}

**Environment**
OS: Linux TENCENT64.site 3.10.104-1-tlinux2_kvm_guest-0022.tl2 #1 SMP Wed Dec 14 10:21:52 CST 2016 x86_64 x86_64 x86_64 GNU/Linux

**Cluster state**
{{ If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue. }}

**Comment by andrewshan** [comment]
it may occur by the iptables fail to get the file lock. As it's mentioned: https://github.com/moby/moby/issues/30379

**Comment by ymesika** [comment]
Just to make sure it is indeed a lock issue, can you add a `-w` flag to the `iptables` commands in the script? Assuming you have iptables v1.6+ on your distro, this should cause the command for the lock to be released.

**Comment by andrewshan** [comment]
> Just to make sure it is indeed a lock issue, can you add a `-w` flag to the `iptables` commands in the script? Assuming you have iptables v1.6+ on your distro, this should cause the command to wait for the lock to be released.

Indeed we are using iptables v1.4.12, it's already supported `-w` flag to retry the flock, now we resolve the problem by `-w 5` to retry 5 times when it fail to be RESOURCE_PROBLEM

**Comment by andrewshan** [comment]
> What's the effect ?
> I know in k8s `If an Init Container fails for a Pod, Kubernetes restarts the Pod repeatedly until the Init Container succeeds.` That is to say if iptables init fails, then pod will be restarted. It ca recover in k8s.

customers will doubt about the unexpected restart.

**Comment by hzxuzhonghu** [comment]
OK, so this is a improvement.
