### ISSUE TITLE
Pilot fetches jwksUri in a cluster without direct internet access.

### ISSUE THREAD

**Issue by dicarlo2** [istio/istio#10819]
**Describe the feature request**
Pilot is responsible for fetching and caching the jwt public keys via the specified jwksUri. This does not work if the cluster does not have direct internet access (e.g. no public IPs) and the jwksUri requires entering the public internet. However, the cluster could have access to the internet through a different mechanism, e.g. a dedicated internet egress cluster which contains an egress gateway. Ideally there'd be a way to configure pilot's envoy proxy to use this alternative mechanism, preferably by simply using existing crds, e.g. service entry + gateway + virtual service + destination rule.

**Describe alternatives you've considered**
Create a pod injected with an istio proxy. Accept http connections on a port where mtls is disabled and forward them to the desired internet address, which allows istio's service mesh to kick in and route the request appropriately.

**Additional context**
FWIW - the documentation could probably use a section on debugging authn policies, took a bit of searching to discover that pilot was fetching the jwt public keys.

**Comment by dicarlo2** [comment]
I got this working by instead sending a request to a local cluster gateway which then routed it to the remote cluster gateway.

However, the connection from pilot to the local cluster gateway is unencrypted. AFAICT there's no way to configure the CAs for pilot to trust (aside from changing the system settings), so it's not possible to secure the connection to the local cluster gateway. I'm not a security expert, but this seems like a flaw since an attacker could MITM the connection, provide their own jwks and then impersonate anyone they want.

**Comment by wailua** [comment]
I have a similar issue. My **jwksUri** for **jwks.json** is located within the cluster for example at 
`http://<service>.<namespace>/api/jwks.json`. With mTLS enabled, istio-proxy is currently not able to fetch this file. Using mTLS permissive mode for the service hosting **jwks.json** is working, but as @dicarlo2 noted not a secure solution.
