### ISSUE TITLE
Mixer: Report original client IP

### ISSUE THREAD

**Issue by ksemba** [istio/istio#10827]
Hi all,

I'm writing an istio Mixer telemetry adapter and need to know the original client IP that initiated the http request towards the istio ingress gateway. The first mixer report I receive is the one that shows 
 - RequestHost: public IP of my app (I'm using the example bookstore app)
 - SourceIP: IP of the ingress gateway as it is sending a request towards the first microservice (productpage in this case)

Is there a way to report on the IP of the client that initiated the request towards the istio environment (the source IP that the ingress gateway receives its request from)? Otherwise istio is a closed system without any knowledge of who / what is interacting with it. 

I found this issue / discussion [https://github.com/istio/istio/issues/7679](url) but forwarding the original client IP using an HTTP header doesn't help in my situation as my Mixer adapter only gets its data through Mixer metric reports and I cannot see how to add the original client IP to those metrics.

Thanks

**Comment by douglas-reid** [comment]
If you desire to have additional information reach your adapter, one option would be to use a custom template for your adapter that has a field for `source_ip` that you can derive from an attribute expression of `request.headers["X-Forwarded-For"]` for example.

**Comment by kyessenov** [comment]
I believe there is `origin.ip` that would be the downstream IP, especially, in the context of the ingress gateway. Note that ultimately this depends on the cloud provider. You would also need to disable k8s load balancing for the ingress service, per https://github.com/istio/istio/issues/7328.

**Comment by ksemba** [comment]
I'm running the bookinfo example app on GKE. I added both suggestions to my instance metric definition like:

`origin_ip: origin.ip` and `xff_header: request.headers["X-Forwarded-For"]`

This did not provide any values for those metrics. Then I patched my GKE k8s cluster like this:
`kubectl patch svc istio-ingressgateway -p '{"spec":{"externalTrafficPolicy":"Local"}}' -n istio-system`

but since that change my app doesn't work anymore (the product page doesn't load in my browser anymore). As far as I understand the bookinfo example app is setup to use service type `LoadBalancer` and I found this patch at [https://kubernetes.io/docs/tutorials/services/source-ip/](url). 

Not sure how to disable load balancing suggested by @kyessenov

**Comment by ksemba** [comment]
@kyessenov thanks for the clarification. But as soon as I set the `externalTrafficPolicy `to `Local `on my `istio-ingressgateway` service, that service is no longer available (web page doesn't load anymore). Do you know why and how to fix this? Thanks again for you support.

**Comment by kyessenov** [comment]
I don't know why it would stop working. @PiotrSikora has tried this awhile ago, or maybe @rshriram might know about any recent changes. Which version are you on?

**Comment by ksemba** [comment]
The hint regarding my cluster version lead me to upgrade my cluster from some v.1.9 to the latest v1.10.9-gke.5. This has fixed the issue and I can now see the real client IP within the `origin.ip` metric --> very nice! 

@douglas-reid although my issue is solved, I still wanted to mention that for me, the `request.headers["X-Forwarded-For"]` metric is not getting populated with any value (always shows `nil`). Not sure whether this is a bug, my misconfiguration or simply an issue with my cluster / k8s config.

**Comment by dweidenfeld** [comment]
> The hint regarding my cluster version lead me to upgrade my cluster from some v.1.9 to the latest v1.10.9-gke.5. This has fixed the issue and I can now see the real client IP within the `origin.ip` metric --

Do you still need to set the `externalTrafficPolicy` to `Local`?

**Comment by ksemba** [comment]
@dweidenfeld to be honest, I can't remember :( been working on other projects for quite a while now... sorry for not being helpful

**Comment by dweidenfeld** [comment]
@ksemba no problem, thanks for the fast answer ;)

**Comment by eddiewang** [comment]
@dweidenfeld were you ever able to figure out a solution for this? I tried setting the `externalTrafficPolicy` to `Local` to no avail :(

**Comment by dweidenfeld** [comment]
@eddiewang unfortunately not. We live with the fact that we cannot use the client IP for now, but hopefully this will change with Anthos / Istio 2 / 1.x...

**Comment by Arpeet-gupta** [comment]
https://blog.opstree.com/2020/04/07/preserve-source-ip-in-aws-classic-load-balancer-and-istios-envoy-using-proxy-protocol/
