### ISSUE TITLE
Configure the open/close mixer policy at pod level 

### ISSUE THREAD

**Issue by costinm** [istio/istio#10845]
We need to be able to configure a pod to use mixer with fail open / fail close, overriding the default.
Some pods require policy checks for security, others don't need any policy check.

Envoy metadata is passing annotations/labels to Pilot, and we can use this to fine tune settings for pods.
We may eventually express this in the Sidecar API, but we can start with using just an annotation.

We had a PR to also turn off policy check based on an annotation - not sure what happened to it.

**Comment by kyessenov** [comment]
Are annotations considered secure enough for administrative control over policy opt-out?
Shouldn't the controls be outside of hands of the pod service account?

Longer term, a partial evaluation of match conditions in rules could statically determine whether policy checks are necessary.

**Comment by costinm** [comment]
Long term we may refine it - but short term we need a way to solve the customer issue. 

They could simply bypass injection ( which we support ) - without admin control.

@mandarjog  - do you remember what happened with the annotation to not call mixer policy at all that we used during 1.0 testing ?

**Comment by douglas-reid** [comment]
So, as I understand it, this request is: enable override the policy enforcement defaults (fail open vs. closed and/or don't call mixer at all) for workloads.

@geeknoid is this something that could be addressed longer term via application-level config artifacts (in galley) or similar?  Or do we feel like annotations on deployment specs / pod specs is the right mechanism for this behavior ?

**Comment by kyessenov** [comment]
@costinm We need clarification of what sort of toggles are requested. In addition to workload instance, what else needs to be part of the decision? Client vs server-side checks? HTTP vs TCP? Route-level? Unless we restrict the dimensions, we need to have a full configuration API for this.

**Comment by kyessenov** [comment]
Please take a look at the linked PR and let me know if it is sufficient.
The PR provides three controls using policy.istio.io/check annotation:
- disable all checks
- enable all checks but fail open
- enable all checks

**Comment by kyessenov** [comment]
Fixed by https://github.com/istio/istio/pull/10886
