### ISSUE TITLE
Allow Istio Multicluster to work without all pod CIDRs in every cluster to be routable to each other

### ISSUE THREAD

**Issue by djannot** [istio/istio#10876]
**Describe the feature request**
Having Kubernetes private nodes communicating on one cluster communicating with private nodes on another cluster doesn't seem to be a nice thing.
Kubernete public nodes should be used for external services to reach Kubernetes services.
Why not leveraging Ingress Controllers to expose the different Istio pods (pilot, policy, ...) so that the other Kubernetes cluster can communicate with them.

**Describe alternatives you've considered**
The current workaround is to create static routes between the 2 Kubernetes clusters and to maintain the routes when the state changes in one cluster. It's not realistic in my opinion.

**Comment by ymesika** [comment]
I believe this is exactly the scenario of the [Split Horizon EDS introduced in v1.1](https://preliminary.istio.io/docs/examples/multicluster/split-horizon-eds/).
It allows clusters on different networks to route traffic through the ingress gateway.
