### ISSUE TITLE
tag istio-system with istio-injection: disabled when enableNamespacesByDefault: true

### ISSUE THREAD

**Issue by stephen-dahl** [istio/istio#10884]
**Describe the bug**
if istio is installed with `sidecarInjectorWebhook.enableNamespacesByDefault=true` then it can fail trying to inject sidecars on itself. We need to ensure the `istio-injection: disabled` label is applied to the istio namespace.

**Expected behavior**
namespace should have label to prevent it trying to inject itself

**Steps to reproduce the bug**
install istio using `sidecarInjectorWebhook.enableNamespacesByDefault=true` without adding `istio-injection: disabled` to namespace

**Version**
istio: 1.0.5
k8s: 1.11

**Comment by sjanota** [comment]
I'd say this label can be added regardless of sidecar injector configuration. It doesn't break anything, and is simpler.
