### ISSUE TITLE
Enable SDS for Istio control plane

### ISSUE THREAD

**Issue by myidpt** [istio/istio#10916]
**Describe the feature request**
Currently Istio workloads are able to retrieve key and cert from Citadel agent. But Istio control plane still uses the legacy secret volume mount to retrieve key and cert. The Istio control plane should have the option to get the key and cert from node agent.

**Describe alternatives you've considered**
No.

**Additional context**
This work involves multiple parts:

Pilot and Mixer:
On these components, sidecar Envoy now uses secret volume mount to obtain the key and certificate. The sidecar Envoy can obtain the key and cert via SDS from node agent.

Galley and Prometheus:
Currently, they directly use secret volume mount to obtain the key and certificate. The Istio component can 1) obtain the key and cert via SDS from node agent; or 2) obtain the key and cert from pod volume mount, which is provided by node agent.

Ingress and egress gateways:
As Envoy, they are using the SDS to obtain the key and certificate for workload-to-workload communications. So no change is needed.

**Comment by cyx** [comment]
We're currently highly interested in this and would be open to doing some development ourselves. Is there an effort we can follow to ensure there's no duplication of work?

**Comment by myidpt** [comment]
@cyx Great to hear! We haven't started this work yet.
I think you can start with Pilot and Mixer, which use Envoy. It is easier to enable SDS for them, for which I think we only need to modify their yaml files.
For Galley and Prometheus, this requires modifying their code to support SDS, which is hard. We can discuss the options.
@quanjielin @ayj

**Comment by ayj** [comment]
See https://github.com/istio/istio/issues/11787 for the Galley specific tracking issue for enabling SDS.

Galley can be configured to open an insecure port for MCP and a sidecar proxy could handle mTLS using SDS for credentials. Galley also provides validation via k8s webhook. This also requires a cert/key with DNS name. Additionally, this cert/key could not depend on the presence of Citadel. As such, we may need a model where Galley uses self-signed cert for webhook (and shared with other Galley replicas via k8s secret) and a spiffie identity via SDS. The sidecar would need to pass through traffic on port 443.

**Comment by duderino** [comment]
pulled into 1.2.  not sure if this is correct, but it will force us to look at it during 1.2 planning

**Comment by myidpt** [comment]
It makes sense to me to pull this into 1.2.

**Comment by cyx** [comment]
Cool. Is there a design doc somewhere outlining how this might be accomplished? Would also be open to chatting online or something if that's useful.

**Comment by quanjielin** [comment]
@cyx I had started this and have few PRs out,

**Comment by cyx** [comment]
@quanjielin cool thanks! Looking at all your PRs.

**Comment by myidpt** [comment]
Thanks @quanjielin

**Comment by cyx** [comment]
@quanjielin are there instructions for testing this out? Would be happy to try it out in some of our test clusters and see it play out. Thanks!

**Comment by quanjielin** [comment]
I have anther pending PR to be sent out, after all three PRs get merged; we could flip ``` controlPlaneSecurityEnabled```  in ``` install/kubernetes/helm/istio/values-istio-sds-auth.yaml```to true and follow https://preliminary.istio.io/docs/tasks/security/auth-sds/ to try it out; for now you could still follow that link to play

**Comment by cyx** [comment]
@quanjielin was trying to get this all working but got blocked on the helm install step. It's probably related to me trying it on master instead of a released version?

I haven't seen in the PRs how the new interaction comes into play. Is it still the same that we'd store secrets via the kube API as a regular secret, and things will get picked up and threaded through automatically to SDS (but without all the volume mounting)?

**Comment by quanjielin** [comment]
@cyx try 1.1 build https://github.com/istio/istio/releases/tag/1.1.0-rc.1.
secret mount is disabled when sds is enabled see https://github.com/istio/istio/pull/10684
