### ISSUE TITLE
Performance issue of ingress gateway

### ISSUE THREAD

**Issue by gyliu513** [istio/istio#10924]
I deployed an application with istio enabled, and found that with istio, when I access the services via ingress gateway, the mixer report the response time is 2+s as `"responseTime":"2.067324415s"`, but with `NodePort`, the response time is ms level.

I also checked the log of `istio-proxy` in ingress gateway and does not found any clue why using ingress gateway is very slow,  any comments for where I should check more to debug this issue?

@rshriram any insight for this?

FYI @morvencao @clyang82

**Comment by hzxuzhonghu** [comment]
I remember we tested this on Huawei cloud, and the latency is about 100+ms in average.

**Comment by morvencao** [comment]
@gyliu513 I think this is where open tracing(jaeger or zipkin) can really help. We can find how much time each span takes and overall response duration for the whole trace.

/cc @clyang82
