### ISSUE TITLE
Create performance/stress/load tests

### ISSUE THREAD

**Issue by hklai** [istio/istio#1093]
As identified in https://docs.google.com/document/d/1-b9K5HfW3WRD7LLadlp4MsJtT5zq0b6pdzGt-0hBEtE/edit#heading=h.c484n21lk0lz
we need to design and implement performance, scalability, and stress test framework, and corresponding test cases.

Here are the sub tasks:
[P0] Define the critical metric to capture and acceptance criteria. E.g. e2e request latency, proxy latency, mixer latency, mTLS overhead, QPS per core, etc.
[P0] A framework to facilitate performance, scalability, and stress testing, possibly based on the existing e2e test framework.
[P0] Find baseline performance numbers

**Comment by ldemailly** [comment]
Ack

**Comment by ldemailly** [comment]
done, manually (see perf wg details), now need integration with continuous build and release
