### ISSUE TITLE
bug: Mixer Dashboard - Individual adapter metrics shows "No Data Points" for OOP adapter

### ISSUE THREAD

**Issue by PhilipGough** [istio/istio#10932]
**Describe the bug**
While working on an out of process adapter I noticed that the "Dispatch Count By Handler" and "Dispatch Duration By Handler" graphs were producing graphs with "No Data Points" text. Screenshot added.

I took a look at the query and was able to obtain those data points directly from Prometheus. It appears the get request to obtain the data from Grafana has added escaped characters to a handler name with the format x.y.z. These in turn are being URL encoded meaning the query is incorrect.

![51044077-288ce980-15b8-11e9-9bb4-47070258072e](https://user-images.githubusercontent.com/5781491/51116693-c3c5cf00-1803-11e9-8ae3-b4eaadc5c336.png)

**Expected behavior**
Expected the OOP adapter graphs to be populated

**Steps to reproduce the bug**
Deploy OOP adapter. Generate some traffic. Check Grafana "Mixer Dashboard"

**Version**
1.0.x - but I believe it is on later version also. Both master and 1.1.x

Fixed in #10903

**Comment by PhilipGough** [comment]
@mandarjog @douglas-reid pinging you guys as the only two contributors to the file in question. I've added a fix which I will happily port over to other branches if approved. Thanks

**Comment by munrodg** [comment]
@douglas-reid can you take a look at this issue?

**Comment by PhilipGough** [comment]
@munrodg @douglas-reid fixed for 1.1 in #10934

**Comment by douglas-reid** [comment]
If this is fixed, let's close the issue.

**Comment by douglas-reid** [comment]
Whoops. I thought that PR had been merged.

**Comment by douglas-reid** [comment]
Issue has been fixed in master.
