### ISSUE TITLE
Routes config is not updated randomly

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio#10933]
Follow the steps in https://preliminary.istio.io/docs/tasks/traffic-management/egress/#configuring-an-external-http-service, access to httpbin.org is not enabled. The cluster is added, but there is no route to it. 

Version release-1.1-20190108-09-15.

**Comment by vadimeisenbergibm** [comment]
I do not see the problem in release-1.1-20190115-09-15, closing the issue.

**Comment by vadimeisenbergibm** [comment]
The issue happens with istio-release-1.1-20190117-09-15 as well.

**Comment by vadimeisenbergibm** [comment]
```
[vadime@vadime-mac istio-release-1.1-20190117-09-15]$ kubectl apply -f - <<EOF
> apiVersion: networking.istio.io/v1alpha3
> kind: ServiceEntry
> metadata:
>   name: httpbin-ext
> spec:
>   hosts:
>   - httpbin.org
>   ports:
>   - number: 80
>     name: http
>     protocol: HTTP
>   resolution: DNS
>   location: MESH_EXTERNAL
> EOF
serviceentry "httpbin-ext" created
[vadime@vadime-mac istio-release-1.1-20190117-09-15]$ bin/istioctl proxy-config clusters $SOURCE_POD -o json | grep httpbin
        "name": "outbound|80||httpbin.org",
            "clusterName": "outbound|80||httpbin.org",
                                        "address": "httpbin.org",
[vadime@vadime-mac istio-release-1.1-20190117-09-15]$ bin/istioctl proxy-config routes $SOURCE_POD -o json | grep httpbin
```

**Comment by GregHanson** [comment]
Tried with latest in release-1.1 branch:

```
$ istioctl proxy-config clusters $SOURCE_POD -o json | grep httpbin
        "name": "outbound|80||httpbin.org",
            "clusterName": "outbound|80||httpbin.org",
                                        "address": "httpbin.org",
$ istioctl proxy-config routes $SOURCE_POD -o json | grep httpbin
                "name": "httpbin.org:80",
                    "httpbin.org",
                    "httpbin.org:80"
                            "cluster": "outbound|80||httpbin.org",
                            "operation": "httpbin.org:80/*"
                                            "string_value": "httpbin.org"
                                            "string_value": "httpbin.org"
                                            "string_value": "httpbin.org"
                                            "string_value": "httpbin.org"
$ kubectl get serviceentry httpbin-ext -o yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.istio.io/v1alpha3","kind":"ServiceEntry","metadata":{"annotations":{},"name":"httpbin-ext","namespace":"default"},"spec":{"hosts":["httpbin.org"],"location":"MESH_EXTERNAL","ports":[{"name":"http","number":80,"protocol":"HTTP"}],"resolution":"DNS"}}
  creationTimestamp: 2019-01-21T20:53:43Z
  generation: 1
  name: httpbin-ext
  namespace: default
  resourceVersion: "34588"
  selfLink: /apis/networking.istio.io/v1alpha3/namespaces/default/serviceentries/httpbin-ext
  uid: a365b1bb-1dbe-11e9-87f5-5e79212187d6
spec:
  hosts:
  - httpbin.org
  location: MESH_EXTERNAL
  ports:
  - name: http
    number: 80
    protocol: HTTP
  resolution: DNS
```

**Comment by vadimeisenbergibm** [comment]
The problem is related to routes in general, they are not updated randomly. Appears in  istio-release-1.1-20190121-09-16.

```
kubectl apply -f samples/httpbin/httpbin.yaml
service "httpbin" created
deployment "httpbin" created
[vadime@vadime-mac istio-release-1.1-20190121-09-16]$ bin/istioctl proxy-config routes $SOURCE_POD -o json | grep httpbin
[vadime@vadime-mac istio-release-1.1-20190121-09-16]$ bin/istioctl proxy-config routes $SOURCE_POD -o json | grep httpbin
[vadime@vadime-mac istio-release-1.1-20190121-09-16]$ bin/istioctl proxy-config clusters $SOURCE_POD -o json | grep httpbin
        "name": "outbound|8000||httpbin.default.svc.cluster.local",
            "serviceName": "outbound|8000||httpbin.default.svc.cluster.local"
            "sni": "outbound_.8000_._.httpbin.default.svc.cluster.local"
```

**Comment by kyessenov** [comment]
I'm not sure what changed lately in pilot recently to cause this. Perhaps, @rshriram can diagnose it better?

**Comment by vadimeisenbergibm** [comment]
Probably related to https://github.com/istio/istio/issues/11170

**Comment by GregHanson** [comment]
@rshriram @kyessenov may also be related to https://github.com/istio/istio/issues/10904
Seems to be something odd going on with RDS sync's.  In the 10904, an occasional ingressgateway won't receive RDS configs from pilot
```
 istioctl proxy-status
NAME                                                   CDS        LDS        EDS               RDS          PILOT                           VERSION
httpbin-5fc7cf895d-2xj84.default                       SYNCED     SYNCED     SYNCED (50%)      SYNCED       istio-pilot-b4cb95f87-lncdd     1.1.0
istio-egressgateway-6b75bc6464-fp9fl.istio-system      SYNCED     SYNCED     SYNCED (100%)     NOT SENT     istio-pilot-b4cb95f87-lncdd     1.1.0
istio-ingressgateway-6b94f94567-hw7c8.istio-system     SYNCED     SYNCED     SYNCED (100%)     NOT SENT     istio-pilot-b4cb95f87-lncdd     1.1.0
istio-ingressgateway-6b94f94567-jdfhr.istio-system     SYNCED     SYNCED     SYNCED (100%)     SYNCED       istio-pilot-b4cb95f87-lncdd     1.1.0
istio-ingressgateway-6b94f94567-kx5jx.istio-system     SYNCED     SYNCED     SYNCED (100%)     SYNCED       istio-pilot-b4cb95f87-lncdd     1.1.0
istio-ingressgateway-6b94f94567-r72pj.istio-system     SYNCED     SYNCED     SYNCED (100%)     SYNCED       istio-pilot-b4cb95f87-lncdd     1.1.0
istio-ingressgateway-6b94f94567-rp4c7.istio-system     SYNCED     SYNCED     SYNCED (100%)     SYNCED       istio-pilot-b4cb95f87-lncdd     1.1.0
```

**Comment by vadimeisenbergibm** [comment]
With istio-release-1.1-20190124-09-17, all the pods except for gateways have RDS synced.

**Comment by hzxuzhonghu** [comment]
I think it is expected. For gateways, rds will be pushed only when virtualservice selected .

**Comment by vadimeisenbergibm** [comment]
@hzxuzhonghu I see. So it seems everything works as expected now, even after deleting pilot pods. Once I define a VirtualService on egress gateway, it is synced too:

istioctl proxy-status
2019-01-25T03:58:31.489235Z	info	Channelz: socket options are not supported on non-linux os and appengine.
Warning! error execing into istio-pilot-54b8685584-qqvz9/istio-system discovery container: gc 1 @0.015s 9%: 0.012+1.8+1.3 ms clock, 0.050+0.26/1.4/0.86+5.3 ms cpu, 4->4->2 MB, 5 MB goal, 4 P
gc 2 @0.026s 11%: 0.009+8.5+1.8 ms clock, 0.038+2.1/0.39/0.57+7.2 ms cpu, 4->4->3 MB, 5 MB goal, 4 P

```
istioctl proxy-status 
NAME                                                   CDS        LDS        EDS              RDS          PILOT                            VERSION
istio-egressgateway-55987854c8-c4dzj.istio-system      SYNCED     SYNCED     SYNCED (96%)     SYNCED       istio-pilot-54b8685584-qqvz9     1.1.0
istio-ingressgateway-66b85ddf7f-rv2js.istio-system     SYNCED     SYNCED     SYNCED (96%)     NOT SENT     istio-pilot-54b8685584-qqvz9     1.1.0
my-nginx-wvhcj.default                                 SYNCED     SYNCED     SYNCED (51%)     SYNCED       istio-pilot-54b8685584-qqvz9     1.1.0
sleep-88ddbcfdd-lfrms.default                          SYNCED     SYNCED     SYNCED (51%)     SYNCED       istio-pilot-54b8685584-qqvz9     1.1.0
```

The issue was probably fixed by https://github.com/istio/istio/pull/11177, closing it.

**Comment by iftachsc** [comment]
this is occurs in 1.1 official

**Comment by cyrus-mc** [comment]
Not sure if this is related to my issue but, output of proxy-status

> › istioctl proxy-status
NAME                                                   CDS        LDS        EDS               RDS          PILOT                           VERSION
awscli2-7f759d4446-59cmd.matt                          SYNCED     SYNCED     SYNCED (50%)      SYNCED       istio-pilot-f4c98cfbf-9hz8q     1.1.0
istio-ingressgateway-668676fbdb-252tp.istio-system     SYNCED     SYNCED     SYNCED (100%)     NOT SENT     istio-pilot-f4c98cfbf-9hz8q     1.1.0

That fact that the single proxy I have is only 50% sync for EDS.

> › istioctl proxy-status awscli2-7f759d4446-59cmd.matt
--- Pilot Clusters
+++ Envoy Clusters
@@ -1,28 +1,26 @@
 {
    "dynamicActiveClusters": [
       {
          "cluster": {
             "name": "BlackHoleCluster",
-            "type": "STATIC",
             "connectTimeout": "1s"
          }
       },
       {
          "cluster": {
             "name": "PassthroughCluster",
             "type": "ORIGINAL_DST",
             "connectTimeout": "1s",
             "lbPolicy": "ORIGINAL_DST_LB"
          }
       },
       {
          "cluster": {
             "name": "inbound|15020|mgmt-15020|mgmtCluster",
-            "type": "STATIC",
             "connectTimeout": "1s",
             "loadAssignment": {
                "clusterName": "inbound|15020|mgmt-15020|mgmtCluster",
                "endpoints": [
                   {
                      "lbEndpoints": [
                         {
@@ -47,15 +45,14 @@
                ]
             }
          }
       },
       {
          "cluster": {
             "name": "inbound|443|http|istio-test.matt.svc.cluster.local",
-            "type": "STATIC",
             "connectTimeout": "1s",
             "loadAssignment": {
                "clusterName": "inbound|443|http|istio-test.matt.svc.cluster.local",
                "endpoints": [
                   {
                      "lbEndpoints": [
                         {

Listeners Match
Routes Match (RDS last loaded at Mon, 25 Mar 2019 10:08:18 PDT)

Shows there are differences between pilot and the proxy. So assuming this is an issue.

**Comment by alunsford** [comment]
We've been struggling with 1.1.1 for the past few days in an attempt to upgrade from 1.0.2. In 1.0.2 we had sync statuses of 100% for our services and istio-proxy handled our in-cluster GRPC traffic without issue. In 1.1.1 they are all 50%, with the diff showing that Pilot knows about them and Envoy does not (same output as https://github.com/istio/istio/issues/10933#issuecomment-476296801).

Istio is installed via helm chart. We have tried a clean install, an upgrade from a 1.0.2 installation, trying the cni addon (since we run on GKE), renaming ports, regenerating CDRs and clusterrole bindings...everything we can think of.

All we have is a single GRPC service running. No gateways, no virtualservices...just a single service with a port named `grpc`. In 1.1.1, istio-proxy will not intercept in-cluster GRPC traffic. In 1.0.2 it handles it and obeys destination rules.

This seems like a pretty serious regression for a minor version upgrade.
