### ISSUE TITLE
Add an e2e test to verify mesh policy is propagated with Galley/MCP enabled

### ISSUE THREAD

**Issue by wattli** [istio/istio#10942]
When galley is enabled, mesh policy is not automatically propagated. Users have to manually restart pilot to see the mesh policy take effect.

**Comment by ozevren** [comment]
Can you give more context? Is there a test that is capturing the problem?

**Comment by wattli** [comment]
Copied from #10941 for more context: 

1. istioctl authn tls-check
2. Disable meshpolicy
3. istioctl authn tls-check to see if it gets updated

With MCP enabled step (3) shows incorrect results (mesh policy is still present?). The same problem does not occur with MCP disabled.

**Comment by ozevren** [comment]
Are there customer logs for this? We were chatting with @ayj about this, and restarting Pilot seems to have fixed the issue apparently. Did they also restart Galley? If not, the problem maybe scoped to the mcp client and/or Pilot code handling the demuxing.

**Comment by irisdingbj** [comment]
Reproduced, working on a fix..

**Comment by irisdingbj** [comment]
@ozevren  , you are correct. The problem is caused by the demux logic in pilot when dealing with mesh-policy and policy. Both of them have the same typeURl: "authentication.istio.io/v1alpha1""

I have not found the fix @ayj is working on.  Where is the fix I can try to see whether it fixed the problem or not?

**Comment by ayj** [comment]
https://github.com/istio/istio/pull/10963 added collections and removed the demux logic.

**Comment by ozevren** [comment]
@irisdingbj, when @ayj was looking at this, he wasn't able to repro. Do you have concrete repro steps? You mentioned something about sequencing of changes in Slack.

His changes in the PR he mentioned simplifies the code path both in Galley and also in Pilot, making it the same as every other resource. So I'd expect this to be fixed at this point by his change.

**Comment by ozevren** [comment]
This should be fixed right now, but I'd very much prefer if we have a regression test for this.
@irisdingbj, can you add a test to cover this? If you don't have time, it would be wonderful to detail the precise repro steps, so that we can capture in a bug to add a test.

**Comment by irisdingbj** [comment]
@ozevren sure, will add a test

**Comment by ozevren** [comment]
Ok. I think we can move this issue out of 1.1 and use it to track the addition of the test.

**Comment by ozevren** [comment]
@irisdingbj Can you prioritize adding this test?
Thanks

**Comment by ozevren** [comment]
Recent set of tests should cover this.
