### ISSUE TITLE
Galley integration test failures

### ISSUE THREAD

**Issue by hklai** [istio/istio#10947]
Error log
https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/10888/istio-integ-local-tests/3370

Note that due to bugs in the test job, tests were NOT run, so it is not easy to figure out if any PR broke this or if the test really ran correctly before.

https://github.com/istio/istio/pull/10888 has uncovered this.

**Comment by ozevren** [comment]
Just had a chat with @nmittler, he is working on a change to fix this.

**Comment by nmittler** [comment]
Just sent out #10953 to fix.
