### ISSUE TITLE
MTLS strict/permissive mode doesn't work with helm 

### ISSUE THREAD

**Issue by ostromart** [istio/istio#10946]
Steps to repro:
1. Create a cluster without auth per quick start: https://istio.io/docs/setup/kubernetes/quick-start/
2. Now change to auth by applying the auth manifest. 

Expected behavior:
MeshPolicy and DestinationRules CRs should be updated from permissive to strict.

Actual behavior:
CRs are not updated.

This creates a problem for Istio on GKE, in that the Istio cluster auth config doesn't work for gcloud cluster update.

**Comment by ostromart** [comment]
Root cause is that the CR's above come from a ConfigMap that is consumed by a job. The job does not re-run if the ConfigMap is changed, so the update is not triggered unless the cluster is upgraded to a different version.
Fix is to move the CRs out of the ConfigMap and into the crd manifest. The job was originally created because of a race between the CRDs and CRs, but CRDs are now created as a separate step before CR's are applied. 
In the Istio on GKE case, the same fix will work with a single manifest, since it is continually applied by the addon manager in the k8s master.

**Comment by ostromart** [comment]
Per offline discussion, we can live without this in 1.0 but it definitely should go into 1.1 sooner rather than later.

**Comment by munrodg** [comment]
@ostromart Is there anything else needed for this issue?

**Comment by ostromart** [comment]
I saw that it did not get merged, but afaik we still need it. Can you comment @diemtvu ?

**Comment by diemtvu** [comment]
I replace that with the cherry pick https://github.com/istio/istio/pull/11418. Forgot to link with the issue. This should be good.
