### ISSUE TITLE
YAMLException: duplicated mapping key name:  port

### ISSUE THREAD

**Issue by kramvan1** [istio/istio#10955]
**Describe the bug**
https://github.com/istio/istio/blob/1.0.5/install/kubernetes/helm/istio/charts/mixer/templates/deployment.yaml#L63 is a dup of the above port line

**Expected behavior**
no dup keys

**Steps to reproduce the bug**
see description

**Version**
1.0.5

**Installation**
n/a

**Environment**
n/a

**Cluster state**
n/a

**Comment by linsun** [comment]
believe this is fixed in 1.1.

**Comment by linsun** [comment]
close it since it is fixed in 1.1
