### ISSUE TITLE
YAMLException: duplicated mapping key name: http-kiali

### ISSUE THREAD

**Issue by kramvan1** [istio/istio#10954]
**Describe the bug**
YAMLException: duplicated mapping key name: http-kiali in https://github.com/istio/istio/blob/1.0.5/install/kubernetes/helm/istio/charts/kiali/templates/service.yaml#L10-L13

**Expected behavior**
No dup key error for this yaml template

**Steps to reproduce the bug**
Just the line describe above

**Version**
1.0.5

**Installation**
n/a

**Environment**
n/a

**Cluster state**
n/a

**Comment by linsun** [comment]
@kramvan1 can you pls describe how to recreate this?  I don't see a dup key name in the file.

**Comment by linsun** [comment]
this is also fixed in 1.1

**Comment by linsun** [comment]
mark as closed as it is fixed in 1.1
