### ISSUE TITLE
Retry request against fallback clusters

### ISSUE THREAD

**Issue by liminw** [istio/istio#10967]
For a failed request, Envoy needs to retry the request multiple times. If all retries fail, it needs to fallback to the specific clusters (e.g., in a different location).

**Comment by liminw** [comment]
cc @duderino @costinm

**Comment by duderino** [comment]
This would be a P1 for 1.1, P0 for 1.2

**Comment by liamawhite** [comment]
@liminw Not fully aware of the context for this but it seems like this solved by locality prioritized load balancing. Just requires users to set outlier detection and retries?

**Comment by howardjohn** [comment]
This is solved by locality LB added in 1.1
