### ISSUE TITLE
User guide for Istio Vault integration

### ISSUE THREAD

**Issue by lei-tang** [istio/istio#10968]
**Describe the feature request**
User guide for Istio Vault integration. This user guide will be placed under https://preliminary.istio.io/docs/tasks/security/.

**Describe alternatives you've considered**
None.

**Additional context**

**Comment by lei-tang** [comment]
#10356

**Comment by aerotog** [comment]
@lei-tang since [PR 3098 ](https://github.com/istio/istio.io/pull/3098)was merged, can this issue be resolved?

**Comment by lei-tang** [comment]
@aerotog Yes, the issue is resolved.
