### ISSUE TITLE
pilot-agent proxy command line not compatible with  envoy command line regarding arguments

### ISSUE THREAD

**Issue by hehailong5** [istio/istio#10973]
**Describe the bug**
Can not modify the --log-path of Envoy via "pilot-agent proxy" command line
The argument "--log_target" is for pilot-agent proxy, not for the Envoy.
**Expected behavior**

All the arguments for Envoy can be feed in via pilot-agent proxy command line

**Steps to reproduce the bug**
{{ Minimal steps to reproduce the behavior }}

**Version**
$ ./pilot-agent version
Version: c9254163685035f0587f97c3703d34c050fce443
GitRevision: c9254163685035f0587f97c3703d34c050fce443
User: root@host-192-168-111-146
Hub: docker.io/istio
GolangVersion: go1.11.2
BuildStatus: Clean

**Installation**
{{ Please describe how Istio was installed }}

**Environment**
{{ Which environment, cloud vendor, OS, etc are you using? }}

**Cluster state**
{{ If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue. }}

**Comment by GregHanson** [comment]
The `--log_target` flag can take an array of log files:
https://github.com/istio/istio/blob/release-1.1/pkg/log/options.go#L329

Envoy access log is currently configured through the mesh config:
https://github.com/istio/api/blob/release-1.1/mesh/v1alpha1/config.pb.go#L210

Envoy apparently does support multiple access log files per listener:
https://github.com/envoyproxy/go-control-plane/blob/master/envoy/config/filter/network/http_connection_manager/v2/http_connection_manager.pb.go#L238

However `log_target` seems specific to istio control plane whereas the mesh config field is specifically for sidecars.  So I'm not sure if the two fields should be synched

**Comment by GregHanson** [comment]
cc @rshriram @costinm any thoughts?

**Comment by GregHanson** [comment]
@hehailong5 closing under the assumption that my previous comments satisfied your use case.
