### ISSUE TITLE
Prometheus export errors in Galley logs

### ISSUE THREAD

**Issue by robertpanzer** [istio/istio#10975]
**Describe the bug**
I installed a recent Istio 1.1 release. (48caa5300d4552a31ec7700a64b1640bf1c7f705)
Galley emits log messages every few seconds complaining about an error during the export of Prometheus metrics:
```
2019-01-15T06:53:23.238319Z     info    Failed to export to Prometheus: inconsistent label cardinality: expected 3 label values but got 2 in []string{"v1", "Pod"}
```

It looks like Galley emits metrics about the pods in the Kubernetes cluster and tries to created labelled metrics containing the apiVersion, kind and group.
For Pods the group seems to be empty.

**Expected behavior**
No Failure messages in the logs.

**Steps to reproduce the bug**
Install Istio 1.1.
Not much more that I have done.

**Version**
Current Istio 1.1 running on Kubernetes 1.10.3 as delivered by Docker for Mac.

**Installation**
```
helm template ~/go/src/istio.io/istio/install/kubernetes/helm/istio --name istio --namespace istio-system -f values-istio-auth.yaml  --set global.mtls.enabled=true --set global.tracing.enabled=true --set pilot.traceSampling=100.0 --set global.hub=istio --set global.tag=48caa5300d4552a31ec7700a64b1640bf1c7f705 --set tracing.enabled=true|k create -f -
```

**Environment**
Running on my local Mac.

**Comment by duderino** [comment]
@douglas-reid can you review the PR?

**Comment by ayj** [comment]
fixed by https://github.com/istio/istio/pull/10976
