### ISSUE TITLE
Istio Gateway Multicluster DNS resolution doesn't work properly

### ISSUE THREAD

**Issue by sdake** [istio/istio#10971]
**Describe the bug**
Istio multicluster should resolve namespace.global and .global in search order via dnsConfig, however, dnsConfig is not applied by the automatic sidecar injector.

**Expected behavior**
Istio multicluster resolution works cross-cloud without modification of applications.

**Steps to reproduce the bug**
Follow guide: https://preliminary.istio.io/docs/setup/kubernetes/multicluster-install/gateways/ (note coredns configuration is needed - which is not yet documented).

**Version**
istio-release-1.1-20190111-09-15

**Installation**
See above for installation instructions

**Environment**
Any Kubernetes environment results in the problem.  The root cause is related to missing implementation in the sidecar injector code path.

**Comment by sdake** [comment]
WIP: https://github.com/istio/istio/pull/10972

**Comment by sdake** [comment]
Thanks @esnible.  I am aware of this limitation with Kuberentes.  I am not sure what can be done about it, other than documenting that the host may only have at most 4 domains in it's /etc/resolv.conf file.  I can submit the documentation change to the istio.io repository.  Can you file an issue with upstream Kubernetes such that Kubernetes doesn't silently ignore the podSpec or alternatively provide a mechanism to override the limit?  This limit seems arbitrary..

Currently the sidecar doesn't inject the podSpec at all, which is the bug this problem is meant to fix.  In addition routing doesn't properly consider the DNSDomains.  IOW the original podSpec implementation is incomplete in release-1.1.

**Comment by sdake** [comment]
Quick update.  2 pilot `OWNERS` (@ymesika @hzxuzhonghu) have provided preliminary lgtms once I fix up two nits.  @rshriram has given the work a review, and pointied out a couple of problems in addition which are nearly resolved.  This work is very close to mergeable and has undergone pretty intense scrutiny compared to other reviews I've submitted for work (alot of people want this bug fixed).

The work took much longer then expected because a secondary problem (with routing) was found and there was a request to consolidate two variables into one which had several call paths.

Cheers
-steve

**Comment by sdake** [comment]
@rshriram asked me to split the PR for this defect into two discrete pieces of work.  The first (injection) is in PR: https://github.com/istio/istio/pull/11512  The second is in PR:

**Comment by sdake** [comment]
11512 introduced a problem mentioned here:  https://github.com/istio/istio/pull/11512#discussion_r253608538 - will follow up with a PR today to resolve.

For those that don't want to click through, if a pod has dnsConfig specified already, the dnsConfig in the sidecar injector is not appended to the existing dnsConfig.

Cheers
-steve

**Comment by adrienjt** [comment]
@sdake thanks for the fixes so far!

What's the current status of Istio Gateway Multicluster? I ran the full example this morning: https://preliminary.istio.io/docs/examples/multicluster/gateways/

1) from the master branch

As expected, the last step,
```
kubectl exec --context=$CTX_CLUSTER1 $SLEEP_POD -n foo -c sleep -- curl 
httpbin.bar.global:8000/headers
```
errored with
```
Could not resolve host: httpbin.bar.global
```

2) from the release-1.1 branch

That's where the PRs referenced in this issue have been merged, so I expected a 200, but instead I got:
```
upstream connect error or disconnect/reset before headers
```

**Comment by sdake** [comment]
@adrienjt which cloud provider are you on?  I have only seen this problem on AWS classic load balancers.

Cheers
-steve

**Comment by sdake** [comment]
@geoand - note current release 1.1 worked for me as of a few days ago on GCE.  What does your SE look like?

Cheers
-steve

**Comment by adrienjt** [comment]
@sdake I wasn't sure about the Helm install, and, indeed, the problem was that I was still using the master sub charts, as explained better by you in #11705. I implemented the fixes locally (as they aren't merged yet), and now it works! Thank you!

**Comment by sdake** [comment]
Closing this - barring further problems looks like things work reasonably well.  I have opened a new bug to permit applications with dnsConfig to merge with our override dnsConfig here: https://github.com/istio/istio/issues/11870

**Comment by osswangxining** [comment]
I met the same issue for multcluster mesh using multiple control planes. I am using 1.1-snapshot6 version,  expected a 200, but instead I got: upstream connect error or disconnect/reset before headers .  Any suggestions?
> 
> ```
> upstream connect error or disconnect/reset before headers
> ```

**Comment by towens** [comment]
We stood up a multi-cluster install of the replicated control plane variety. It worked for a moment with both clusters on `1.4.4`. I've since upgraded to `1.4.5` and not seen it work. Then reverted back down to `1.4.4` and continues to not work. Not sure if it's the limited number of k8s domain searches.
```
AWS
K8s 1.15.7
```

All from the replicated control plane info [here](https://istio.io/docs/setup/install/multicluster/gateways/#configure-the-example-services)
```
kubectl exec sleep-hash -n foo -c sleep -- curl -I httpbin.bar.global:8000/headers
**0curl: (6) Could not resolve host: httpbin.bar.global**

kubectl exec sleep-hash -n foo -c sleep -- cat /etc/resolv.conf
nameserver 100.64.0.10
**search foo.svc.cluster.local svc.cluster.local cluster.local ec2.internal**
options ndots:5

kubectl -n foo get se
NAME          HOSTS                  LOCATION        RESOLUTION   AGE
httpbin-bar   [httpbin.bar.global]   MESH_INTERNAL   DNS          32m
```
If I replace the sleep pod, global is present.
```
nameserver 100.64.0.10
search foo.svc.cluster.local svc.cluster.local cluster.local ec2.internal global foo.global
options ndots:5
```
Still does not resolve the host. 

```
itl proxy-config cluster -n istio-system istio-ingressgateway-hash|grep global
httpbin.bar.global                                                              8000      -          outbound      STRICT_DNS
outbound_.8000_._.httpbin.bar.global
``` 

Are we missing something obvious?

**Comment by tamipangadil** [comment]
Hi @towens,

I think we have similar problem.  And I realized that there is actually no issue. 

If you are using AWS EKS, you are probably using CoreDNS instead of KubeDNS. And based on your K8s version, you probably using CoreDNS version 1.6.

If yes, then you need to change the config map using the CoreDNS (>=1.4.0) manifest described in their tutorials.

Let me know if it works.

**Comment by towens** [comment]
Thanks @tamipangadil 

We're using KubeDNS with Kops on AWS. So we used the KubeDNS global stub out of the docs. As an aside. Looks like k8s recommends switching to CoreDNS.
