### ISSUE TITLE
Nice to have `kubectl logs productpage` output

### ISSUE THREAD

**Issue by kramvan1** [istio/istio#10985]
**Describe the feature request**
Would be great to be able to use `kubectl logs productpage-v1 -c productpage`

Looks like the sample dumps it's output to a file called microservice.log in the root dir.  Would be great to have that tailed out to stdout to allow logs to pick it up.

**Describe alternatives you've considered**

**Additional context**

**Comment by linsun** [comment]
I think we have logs for product page, but I will test.

In your case, it is possible you aren't seeing it because no traffic is routed to it.

**Comment by kramvan1** [comment]
@linsun the logs are inside the container in the `microservice.log`, but it's a hassle to have to exec into the container just to see them, hence this issue.

**Comment by linsun** [comment]
@johnma14 - could you check if there is anything we can provide in product page to make this troubleshooting easier for our user like @kramvan1 ?

**Comment by linsun** [comment]
you can deploy book info sample to recreate what he hits...

**Comment by johnma14** [comment]
@linsun I will look at it and update this with what I find.

**Comment by esnible** [comment]
@johnma14 Did you have a chance to look at this?  I suspect it would be as easy as modifying _samples/bookinfo/src/productpage/Dockerfile_ and replace `CMD python productpage.py 9080` with something similar to `CMD python productpage.py 9080`touch /opt/microservices/microservice.log && tail -f /opt/microservices/microservice.log && python productpage.py 9080`

**Comment by frankbu** [comment]
Is this only an issue for productpage? Do all the other bookinfo services (reviews, ratings, details) output log messages?

**Comment by esnible** [comment]
@frankbu I verified this is only an issue for Productpage.  Checked Feb 1 and verified today.
