### ISSUE TITLE
Telemetry is using more CPU in recent builds

### ISSUE THREAD

**Issue by jnativio** [istio/istio#10988]
**Describe the bug**
Telemetry pods have been using more CPU for the same workload in recent builds of master branch. 
build master-20190109-09-15:
![image](https://user-images.githubusercontent.com/18554027/51212000-20e58180-18e5-11e9-87c0-35d910aab4ef.png)
telemetry flame graph: https://ibmcloud-perf.istio.io/regpatrol/master-20190109-09-15/istio_full//flamegraphs/flame.telemetry.svg

The next build started showing the problem:
build  master-20190110-09-15:
![image](https://user-images.githubusercontent.com/18554027/51209885-538c7b80-18df-11e9-9cd8-6be64dabad0b.png)
telemetry flame graph: https://ibmcloud-perf.istio.io/regpatrol/master-20190110-09-15/istio_full//flamegraphs/flame.telemetry.svg

Note in the flame graphs that the stacks for runtime.gcBgMarkWorker and runtime.mcal are using more CPU time in the second one.

The builds of 1.1 branch also have this issue, but it started before. See regpatrol data:
before: https://ibmcloud-perf.istio.io/regpatrol/pre-1.0.5_results/release-1.1-20181208-09-15/istio_full//
after: https://ibmcloud-perf.istio.io/regpatrol/pre-1.0.5_results/release-1.1-20181215-08-31/istio_full//

**Expected behavior**
No CPU usage regression.

**Steps to reproduce the bug**
Compare telemetry cpu usage under load of master builds before and after 01/09.

**Version**
Istio Version:"master-20190110-09-15"
K8s version: 1.10.11_1538

**Installation**
Helm chart

**Environment**
IKS

@mandarjog

**Comment by douglas-reid** [comment]
@mandarjog @jnativio what is required to close this issue?

**Comment by douglas-reid** [comment]
I'm going to close this issue, as we don't seem to have anything to do here, and are actively choosing to pursue a different architecture.

Changes in 1.1 pushed CPU from the proxy over to the mixer services (removed attribute compression), so some uptick in CPU was inevitable.
