### ISSUE TITLE
Envoy deprecation: Use Any instead of Struct

### ISSUE THREAD

**Issue by costinm** [istio/istio#10993]
https://github.com/envoyproxy/envoy/pull/5435  deprecates 'struct' and enables 'any' for passing 
config. 

We need to update Pilot code to use Any - this was identified as a major overhead in flamegraphs, 
and the change is relatively small and safe.

Not blocking - but would have big impact on performance in the default case ( with isolation disabled )

@mandarjog

**Comment by andraxylia** [comment]
We have approx ~3 months to address this deprecation:
https://github.com/envoyproxy/envoy/blob/master/DEPRECATED.md#version-1100-pending

cc @duderino

**Comment by kyessenov** [comment]
Fixed by #11419

**Comment by andraxylia** [comment]
thanks @kyessenov
