### ISSUE TITLE
Istio Gateway does not have readiness/liveness enabled

### ISSUE THREAD

**Issue by iandyh** [istio/istio#11001]
**Describe the bug**
We rely on Istio Gateway to point the traffic into the cluster. Through our testing, we found out unready Envoy process can be added to the fleet to receive the traffic. This will result to `Connection Refused` at the client side. 

More alarmingly, we also found out that sometimes Envoy process fail to establish a connection with the pilot, please see the log from the gateway pod below:

![image](https://user-images.githubusercontent.com/431658/51224552-d36f2000-1989-11e9-9469-dc232e3431bd.png)

**Expected behavior**
Only healthy gateway should be added to the fleet to receive traffic.

**Steps to reproduce the bug**
Deploy the istio gateway and expose it as a NodePort service. Scale up the gateway multiple times while sending some traffic to the gateway, you should be able to reproduce the bug.

I added the `readinessProbe` manually and it reduced the `ConnectionRefuse` errors but sometimes as the above error log showed, Envoy proxy fails to start and still result `ConnectionRefuse`.

**Version**
Kubernetes: 1.12
Istio: 1.1-snapshot-4

**Installation**
Using Helm

**Environment**
4.14.67-coreos

**Comment by hzxuzhonghu** [comment]
should add readiness probe as sidecar.

**Comment by hzxuzhonghu** [comment]
of course,  pilot-agent can listen on a statusPort 15020 if configured.  Which serves a healthcheck endpoint.

**Comment by iandyh** [comment]
@hzxuzhonghu Then my guess is that we need to add this healthcheck to `istio-ingressgateway` deployment?

**Comment by iandyh** [comment]
@hzxuzhonghu I think a more  alarmingly issue here is that sometimes I notice that `ingressgateway` fail to start.

**Comment by hzxuzhonghu** [comment]
@iandyh Can you provide some more logs when it  fails to start? I think there maybe some clues.

**Comment by iandyh** [comment]
@hzxuzhonghu I've pasted the logs in the description. Let me paste again here:
This is from the `ingressgateway` pod.

```
2019-01-18T06:46:01.376742Z     info    Envoy command: [-c /etc/istio/proxy/envoy-rev0.json --restart-epoch 0 --drain-time-s 45 --parent-shutdown-time-s 60 --service-cluster istio-ingressgateway --service-node router~192.168.22.23~istio-ingressgateway-578d6645c7-4w5qr.istio-system~istio-system.svc.cluster.local --max-obj-name-len 189 --allow-unknown-fields -l warning --v2-config-only]
[2019-01-18 06:46:01.398][000018][warning][upstream] [external/envoy/source/common/config/grpc_mux_impl.cc:268] gRPC config stream closed: 14, no healthy upstream
[2019-01-18 06:46:01.398][000018][warning][upstream] [external/envoy/source/common/config/grpc_mux_impl.cc:51] Unable to establish new stream
```
If need more info, please instruct me. I really want to fix the issue.

Please also look at the issue above that is referencing this one. We are facing similar problems.

**Comment by hzxuzhonghu** [comment]
Is the pilot service healthy?

grpc error shows that no healthy pilot.

**Comment by iandyh** [comment]
@hzxuzhonghu pilot was healthy. With 1.1 snapshot 4, I think you can easily reproduce the issue. Just sending the traffic continuously and scale up the ingress gateway.

**Comment by tcnghia** [comment]
We also run into this issue.  Without some readiness probes, new gateway pods are added into the Endpoints as soon as they are up and running and not necessarily ready to receive requests.

/cc @andraxylia

**Comment by iandyh** [comment]
@tcnghia Are you using ipvs or iptables mode in kubeproxy?

**Comment by iandyh** [comment]
@hzxuzhonghu One thing needs to be noted: The proxy is running != The proxy is ready to accept the traffic. So I am wondering if port 15020 on pilot-agent can verify it. 

IMO, the readiness port should be the ones that are being defined by the `gateway` resources. Since they are dynamic it seems pretty difficult to define at pre-installing state.

**Comment by hzxuzhonghu** [comment]
As Istio is eventual consistent, so it is unsure when xDS will be pushed when rules are created. But I believe currently we have perf and scale test @mandarjog   to monitor the latency.

**Comment by iandyh** [comment]
@hzxuzhonghu The safest approach will be create another deployment with some sort of consistency check to ensure all the Enovys have the right configuration and then point the traffic to this deployment.

**Comment by berstend** [comment]
@iandyh 
> I added the readinessProbe manually and it reduced the ConnectionRefuse errors

Could you share your readinessProbe implementation? I'm also encountering refused connections and some improvement seems better than nothing. 😄

**Comment by tcnghia** [comment]
@hzxuzhonghu @mandarjog is it possible to allow customization of readinessProbe on helm chart? 
 Users know what ports their Gateway will expose so they can specify TCP probes to connect to those ports.

@berstend In our case we manually edit the `istio-ingressgateway` and add a TCP probe for port 80 (or 443) and also saw no refused connection after.

**Comment by iandyh** [comment]
@berstend Hi. As @tcnghia said, we just add the probe manually. But please read my comments in this thread, adding `readinessProbe` does not address the problem entirely. You will still have the risk when just scaling up the gateway deployments for example. Because there is no guarantee which will be faster, the configuration streaming from pilot or the actual production requests.

My suggestion is prepare a new deployment and use `istioctl proxy-status` to do a sync check. Once all the tests are passed, then update the gateway service manifest.

Hopefully it helps.

**Comment by mandarjog** [comment]
Readiness probe checks if envoy has listeners on all expected ports, when this is added to the gateway it should help the problem. 
@natemittler did you finish testing with LB liveness to the gateway?

**Comment by iftachsc** [comment]
+1!
