### ISSUE TITLE
Missing metadata name for List in chart template

### ISSUE THREAD

**Issue by kramvan1** [istio/istio#11015]
**Describe the bug**
Version tag 1.0.5 
These 2 templates
https://github.com/istio/istio/blob/c3012ce4021f20cb4c39cbb2b302af5d71a8d006/install/kubernetes/helm/subcharts/tracing/templates/service.yaml
https://github.com/istio/istio/blob/9c8ca47b64fa2d152f6a1d3027f25d38246210c5/install/kubernetes/helm/subcharts/tracing/templates/service-jaeger.yaml
don't have a list metadata section 

**Expected behavior**
No errors while processing the List resource object.

**Steps to reproduce the bug**
Use tool like kustomize to verify the chart output yaml.

**Version**
1.0.5

**Installation**

**Environment**

**Cluster state**

**Comment by kramvan1** [comment]
Wrong links above: 
https://github.com/istio/istio/blob/1.0.5/install/kubernetes/helm/istio/charts/tracing/templates/service-jaeger.yaml#L4
https://github.com/istio/istio/blob/1.0.5/install/kubernetes/helm/istio/charts/tracing/templates/service.yaml#L2

**Comment by kramvan1** [comment]
@linsun  cc

**Comment by linsun** [comment]
@jmazzitelli I checked we still have this prob in 1.1, would you be the right person from red hat to fix this?  any reason we need the list kind?  if not, i'd remove it.

**Comment by kramvan1** [comment]
+1 to remove the unneeded lists here.

**Comment by linsun** [comment]
ping @jmazzitelli thoughts?  ^^

**Comment by objectiser** [comment]
@linsun This is fixed in master and 1.1 branches. Will there be another release from branch 1.0?

**Comment by linsun** [comment]
@jmazzitelli can you confirm this is fixed in 1.1 and close it?

**Comment by howardjohn** [comment]
Fixed
