### ISSUE TITLE
How can you define SMTP server used by Grafana?

### ISSUE THREAD

**Issue by paolosalvatori** [istio/istio#11010]
How can I customize Grafana.ini and in particular add SMTP server and credentials as explained at https://github.com/helm/charts/issues/6222 when deploying Istio using helm to Kubernetes?

**Comment by iahmad-khan** [comment]
why is this closed?

**Comment by lck0129** [comment]
kubectl edit cm -n istio-system istio-grafana  

data:
  dashboardproviders.yaml: |
    apiVersion: 1
    providers:
    - disableDeletion: false
      folder: istio
      name: istio
      options:
        path: /var/lib/grafana/dashboards/istio
      orgId: 1
      type: file
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - access: proxy
      editable: true
      isDefault: true
      jsonData:
        timeInterval: 5s
      name: Prometheus
      orgId: 1
      type: prometheus
      url: http://prometheus:9090
  grafana.ini: |
    [server]
    root_url = http://localhost:3000
    [smtp]
    enabled = true
    host = smtphost:465
    user = user@email.com
    password = *****
    skip_verify = true
    from_address = user@email.com
    [alerting]
    enabled = true
    execute_alerts = true

kubectl edit deploy -n istio-system grafana
        - mountPath: /etc/grafana/grafana.ini
          name: config
          subPath: grafana.ini
