### ISSUE TITLE
circleci e2e test infra problems

### ISSUE THREAD

**Issue by hklai** [istio/istio#11029]
e2e tests are occasionally failing on circleci for a few different reasons:

* Image pulling problem
https://circleci.com/gh/istio/istio/293876
https://circleci.com/gh/istio/istio/292034
```
xenial: Pulling from library/ubuntu
error pulling image configuration
```

* external http access problem
https://circleci.com/gh/istio/istio/290151
https://circleci.com/gh/istio/istio/290150

```
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-updates/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-backports/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/xenial-security/InRelease  Temporary failure resolving 'security.ubuntu.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

* local file access problem
https://circleci.com/gh/istio/istio/291031
`chown: cannot access ‘/go/out/minikube.conf’: No such file or directory
`

**Comment by linsun** [comment]
@esnible is this similar issue you are tracking related to network connectivity from circle ci?

**Comment by linsun** [comment]
@mbanikazemi cc

**Comment by esnible** [comment]
@linsun It is identical.  My fix was applied to release-1.1.  These failures are for release-1.0.  I will create a fix for release-1.0.

**Comment by hklai** [comment]
@esnible errors like https://circleci.com/gh/istio/istio/293876 is from release-1.1.

**Comment by esnible** [comment]
@hklai Yes, this particular problem does sometimes affect release-1.1.

The offending line is `FROM ubuntu:xenial` when building _proxy_init_.  Every other Istio build is based *indirectly* on _ubuntu:xenial_ via _istionightly/base_debug_.  If we based _proxy_init_ on _base_debug_ we could eliminate the extra attempt to contact docker.io.  In this case the error message was

```
error pulling image configuration: Get https://registry-1.docker.io/v2/library/ubuntu/blobs/sha256:b0ef3016420a4052400d0a36f5144ebdee5d358ef6942afee072517b5a94168c: EOF
```

The only difference between _pilot/docker/Dockerfile.proxy_init_ and _docker/Dockerfile.xenial_debug_ is a slightly different list of packages installed after the `apt-get update`.  If might improve Docker image cache to base proxy_init on the same base image as everything else.

If not, perhaps we could modify the build to attempt `docker pull ubuntu:xenial`  several times before the build to make sure docker.io is reachable.  Thoughts?

**Comment by louiscryan** [comment]
@esnible please add priority to this

**Comment by linsun** [comment]
@esnible that sounds reason, re retry several times.

**Comment by linsun** [comment]
close this due to #11277 merged.
