### ISSUE TITLE
pilot/pkg/serviceregistry/kube tests are flaky

### ISSUE THREAD

**Issue by hklai** [istio/istio#11021]
Example: https://gubernator.k8s.io/build/istio-prow/logs/istio-postsubmit/4173

Failures:
pilot/pkg/serviceregistry/kube.TestController_GetIstioServiceAccounts
pilot/pkg/serviceregistry/kube.TestController_getPodAZ
pilot/pkg/serviceregistry/kube.TestServices

/assign @irisdingbj who closed https://github.com/istio/istio/issues/10312

**Comment by duderino** [comment]
@linsun will find someone to cover for Iris

**Comment by linsun** [comment]
@ericvn is this still an issue?

**Comment by ozevren** [comment]
This seems to be stable in post submits.
https://testgrid.k8s.io/istio-postsubmits-master#unit-tests&include-filter-by-regex=pilot%2Fpkg%2Fserviceregistry
