### ISSUE TITLE
istio-cni race condition with autoscaling clusters and calico

### ISSUE THREAD

**Issue by dicarlo2** [istio/istio#11037]
**Describe the bug**
istio-cni frequently has the following problems in clusters with autoscaling nodes:

1. istio-cni runs __before__ calico -> configuration appears to be overwritten entirely by calico.
2. istio-cni runs __after__ calico and __after__ another pod starts on the new node -> iptable configuration does not kick in and the pod is typically stuck in a blackhole state because mtls traffic is not redirected to the proxy.

**Expected behavior**
I'm not sure there's really a solution here, but it makes istio-cni practically unusable on clusters that frequently up and down-scale since it almost always requires manual intervention to resolve issues where pods have started with the wrong network sandbox. Perhaps istio-cni should be watching the node it started on and periodically verify that the configuration has been set correctly. Additionally, istio-cni could delete all pods that started before the configuration was applied.

**Steps to reproduce the bug**
See description, but roughly
1. Start a GKE cluster with calico + cluster autoscaling
2. Install istio with istio-cni
3. Trigger cluster scaling by creating a deployment (or otherwise) that doesn't fit in the current cluster size.
4. Observe that either 1/ or 2/ above occurs.

**Version**
istio: release-1.1-20190110-09-15
kubectl: v1.11.5-gke.5

**Installation**
Semi-custom based on the helm chart. Modifications were to make istio conform to our pod security policy.

**Environment**
GKE

**Cluster state**
Let me know if this would be helpful.

**Comment by dicarlo2** [comment]
@tiswanso looks like you did most of the istio-cni implementation, can you take a look at this issue and give your thoughts? FWIW - I might be totally off-base here, but afaict this is a valid problem.

**Comment by dicarlo2** [comment]
https://github.com/sabre1041/istio-pod-network-controller solves issue 2/ by running an init container that waits for the pod to be annotated that it's ready to start by the cni plugin.

**Comment by tiswanso** [comment]
@dicarlo2 -- Thanks for the analysis.  Which container runtime is your setup using?  Also, is any k8s or calico network policy being applied to these pods as well?

The container runtime should be invoking each CNI plugin binary in the order it appears in the configuration and the istio-cni install script (run by the istio-cni daemonset) should be applying the istio-cni plugin configuration at the end of the configured plugin list.  

That being said, Calico's implementation is not just the binary configured in the CNI plugin config and executed by the container runtime when pods are created.  The felix daemonset performs additional actions based on the events in the calico control-plane.  Perhaps it is doing additional iptables actions in the pod network namespaces which corrupts/overwrites/flushes the istio-cni chains.  

@spikecurtis  -- would you have any guidance or pointers here?

**Comment by tiswanso** [comment]
@dicarlo2   -- In my previous comment, I think I may have misunderstood the issue.  Looking at https://github.com/istio/cni/issues/82, the issue is that the CNI plugin configuration is not applied properly to the nodes, right?  I read this issue as you seeing an issue where calico and istio-cni are incompatible when both are trying to network the same Istio user pods.

Will take my follow-ups to the istio/cni issue.

**Comment by spikecurtis** [comment]
Felix does some follow up actions to make sure pod virtual interfaces are configured correctly, but it doesn't  modify anything inside the pod's network namespace.

What we need is a reliable mechanism to keep Kubernetes from scheduling pods on the newly created node until all the CNI plug-ins are installed and ready.  I think Kubernetes knows it can't schedule pods until a CNI plug in is available, but presumably thinks everything is dandy as soon as any plug in is installed.  Perhaps the use of taints?

**Comment by dicarlo2** [comment]
I'm going to go ahead and close this issue so we can keep the discussion in one place. Will respond to above comments in https://github.com/istio/cni/issues/82

**Comment by philandstuff** [comment]
Since istio/cni issues have been seemingly deleted, for context:

> As cni issues are not accessible anymore: istio/cni#83 is the PR that should have fixed https://github.com/istio/cni/issues/82

Source: https://github.com/istio/istio/issues/14327#issuecomment-495108999
