### ISSUE TITLE
Mixer adapter build/test problems on circleci

### ISSUE THREAD

**Issue by hklai** [istio/istio#11032]
See https://testgrid.k8s.io/istio-postsubmits#circleci-test

There are a lot of recent build and test failures in

istio.io/istio/mixer/adapter/circonus.[build failed]
istio.io/istio/mixer/adapter/denier.[build failed]
istio.io/istio/mixer/adapter/stackdriver.[build failed]
istio.io/istio/mixer/adapter/statsd.[build failed]
istio.io/istio/mixer/adapter/prometheus.TestMetricExpiration
istio.io/istio/mixer/adapter/prometheus.TestMetricExpiration/Preserve_non-stale_metrics
istio.io/istio/mixer/adapter/stackdriver/trace.[build failed]
istio.io/istio/mixer/adapter/signalfx.[build failed]
istio.io/istio/mixer/adapter/prometheus.[build failed]
istio.io/istio/mixer/adapter/fluentd.[build failed]
istio.io/istio/mixer/adapter/stackdriver/log.[build failed]

Examples:
https://circleci.com/gh/istio/istio/295104
https://circleci.com/gh/istio/istio/295037
https://circleci.com/gh/istio/istio/294749

**Comment by kyessenov** [comment]
Can we increase memory capacity of CI worker?
https://discuss.circleci.com/t/go-build-receives-sigkill/12213/2

**Comment by hklai** [comment]
Perhaps, but I am not a circle admin.

cc @rshriram @costinm @louiscryan

**Comment by kyessenov** [comment]
You can try to build a test binary first with `go test -c ...`. This might help if some test allocates a lot of memory. If the build just fails with OOM then we need more memory. Given that prow does not exhibit this issue, we should just give both same amount of memory.

**Comment by louiscryan** [comment]
ping @douglas-reid - can you provide an update ?

**Comment by louiscryan** [comment]
@wenchenglu please track

**Comment by linsun** [comment]
might be covered by https://github.com/istio/istio/pull/11116, cc @douglas-reid @ymesika

**Comment by wenchenglu** [comment]
@duderino fyi

**Comment by duderino** [comment]
@hklai is this still an issue?   assigning to you for an answer

**Comment by hklai** [comment]
These are "fixed" by reducing parallelism to 1 by #11116.
