### ISSUE TITLE
istioctl: Create a convenience mesh check command

### ISSUE THREAD

**Issue by linsun** [istio/istio#11044]
**Describe the feature request**
Check: istioctl check

**Describe details**
We don’t currently have a check cmd, except istioctl experimental verify-install

Ideally, this cmd should contain options to check the following:
Check if the env meets prerequisites of install
Check if the install is success
Check if the control plane is healthy.  
It should have a verbose mode to print out details of what has been checked.
It should also have a data plane check option. 
Optionally, check can be performed per namespace.
User should be able to use this cmd to check what is wrong with a given microservice.
Possibly: The control plane is on a recent Istio released version

**Comment by linsun** [comment]
@esnible thoughts?

**Comment by linsun** [comment]
@ibm-jason cc

**Comment by esnible** [comment]
Galley, the sidecar injector, Core DNS, and Prometheus all have health endpoints (described in their deployments) that can be checked.  Each instance can be checked for health.

Most Istio pods are fronted by services in the istio-system namespace that can be checked to make sure the services are responsive.

We should check that all pods in istio-system running Envoy are offering the admin interface on port 15000.  If not, their Envoy may have crashed.

The job pods in istio-system, especially istio-security-post-install-release, must be checked.  (If security-post-install has failed it can lead to things seeming to work but mTLS being off).

There are a few other things that should be checked such as Istio-generated certs not being expired.  That is part of the mesh status.

**Comment by ayj** [comment]
This is something an operator could manage and expose via Istio "install profile" CRD status. That could limit the need to port-forward into the cluster to query individual components.

cc @ostromart

**Comment by esnible** [comment]
FYI we have `istioctl experimental verify-install -f ~/istio.yaml` which will be enhanced by a `--verbose` flag through https://github.com/istio/istio/pull/12174 to tell us the status of the control plane pods.

**Comment by linsun** [comment]
@esnible @irisdingbj nice!

**Comment by esnible** [comment]
Linkerd2 has a mesh status command, `linkderd check`.  It would be worthwhile to include some of its features.  Their version can check control plane version (as _istioctl_ could in 0.1, but no longer).  We should bring back version checking to _istioctl_.

**Comment by linsun** [comment]
Agreed, we should have our check command too. I'll update the desp.

**Comment by linsun** [comment]
@irisdingbj pls move it to P0 when you start working on this. :)

**Comment by irisdingbj** [comment]
This has been done via ```istioctl verify-install```  it will perform pre-check and let you know whether your cluster is ready for istio installation.

**Comment by irisdingbj** [comment]
```istioctl verify-install -f istio.demo.yaml ``` can be used to check whether your installation is succeeds

**Comment by esnible** [comment]
@irisdingbj We need to understand if `istioctl verify-install` is compatible with the work in https://github.com/istio/installer

**Comment by esnible** [comment]
Closed because we have `istioctl verify-install`.
