### ISSUE TITLE
Mixer adapter metric "source.port" not working

### ISSUE THREAD

**Issue by ksemba** [istio/istio#11055]
My custom Mixer adapter defines a custom instance metric using the corresponding yaml file. This allows me to choose which of the metric data I want to forward to my adapter. Most of the metrics work fine except for this one:
 
`source_port: source.port | 0`

As soon as I add this config line to the yaml (within the `params --> dimensions` section - this is where I have all my metrics listed and they all work fine) and apply it, my adapter stops receiving metric data from Mixer. When I remove it, I get new metrics delivered.

Any ideas on what I'm doing wrong? 
Thanks

**Comment by bianpengyuan** [comment]
source.port is not in mixer attributes vocabulary: https://istio.io/docs/reference/config/policy-and-telemetry/attribute-vocabulary/

**Comment by ksemba** [comment]
thanks for the hint @bianpengyuan. Any idea why mixer is not providing the source port? Can this be added?

**Comment by bianpengyuan** [comment]
We used to have source.port attributes, but its value is random and useless, so we removed it. How do you 
plane to use source.port?

**Comment by ksemba** [comment]
I agree that in between the microservices the source port is useless. But when the request enters the environment (through the ingress gateway) it could be interesting to get the original source port (next to the original source IP which already exists). Requests can originate on customer's on-prem, internal networks but then get NAT-ed by their firewall before they leave towards the cloud. Most firewalls use dynamic NAT where each client flow gets assigned a dynamic source port from the firewalls external interface. If you knew the source port of the incoming flow and the NAT table of the firewall you would be able to map a request to a client.

**Comment by ksemba** [comment]
@kyessenov your suggestion sounds good to me. Would be great to get the implemented. Do I need to create a CR (if yes: how?)?

**Comment by kyessenov** [comment]
You are welcome to make a contribution to istio/proxy. Seems like a couple of lines of changes. 
Take a look at https://github.com/istio/community/blob/master/CONTRIBUTING.md

cc @duderino for visibility

**Comment by douglas-reid** [comment]
As work appears to be stalled on this issue and pending future architectural changes will render this issue moot, I'm going to close this issue.
