### ISSUE TITLE
Istio 1.1 multicluster breaks if remote services also accessed from their own non-mTLS cluster

### ISSUE THREAD

**Issue by esnible** [istio/istio#11059]
I installed two clusters, 'test-multizone' and 'istio-test-paid' and configured them with kube-dns ConfigMap directing to Istio DNS.  I put a reviews server on _istio-test-paid2_ and a 'curl' client on both.

Neither had mTLS enabled.

I created a Service Entry on the cluster called `test-multizone`.

`kubectl --context test-multizone exec -it curl-8449cd8d96-g775r -- curl -v reviews.default.global:9080/reviews/0` works.
`kubectl --context istio-test-paid2 exec curl-8449cd8d96-g775r -- curl reviews:9080/reviews/0` also works.
`kubectl --context test-multizone exec -it curl-8449cd8d96-g775r -- curl -v reviews.default.global:9080/reviews/0` NO LONGER WORKS.

I suspect the "Permissive" feature of Istio/Envoy is permissive at first, but the plain HTTP non-TLS request causes it to lock into a mode where it is no longer permissive.

**Comment by liminw** [comment]
@incfly @myidpt Could one of you take a look?

**Comment by incfly** [comment]
What's the error code/message you see when the second time request is not going through?

If your theory is correct, if
1. Default single cluster installment.
1. PERMISSIVE mode for a service.
1. Install two clients, one with envoy injected, one without.
1. A request from client without sidecar, **Should succeed**
1. Turn on client side mTLS using `DestinationRule` first. && send a request from client with envoy to the service. **Should succeed**
1. Second request from client without sidecar, **Should Failed**

Is that something you can quickly verify? I want to isolate the factor from multi cluster.

**Comment by incfly** [comment]
Without further looking at it, my inclination is this more likely due to a secure naming and certificate problem, not about permissive mode.

**Comment by duderino** [comment]
@incfly are you planning on working on this?

**Comment by incfly** [comment]
I can help with investigation with @esnible  and will try to identify the root cause first.

**Comment by esnible** [comment]
@incfly unexpected results when testing.

I first installed Istio using _helm_ and `--set global.mtls.enabled=true`.  I then installed Bookinfo.

Before I turned on permissive for reviews I needed TLS, which I verified with _curl_:

```
kubectl exec -it $(kubectl get pod --selector app=reviews,version=v1 --output jsonpath='{.items[0].metadata.name}') -c istio-proxy -- curl https://ratings:9080/ratings/0 --key /etc/certs/key.pem --cert /etc/certs/cert-chain.pem --cacert /etc/certs/root-cert.pem -k
// the next line fails with connection reset by peer
kubectl exec -it $(kubectl get pod --selector app=reviews,version=v1 --output jsonpath='{.items[0].metadata.name}') -c istio-proxy -- curl -v http://ratings:9080/ratings/0
```

I then attempted to make the service permissive:

```
cat <<EOF | kubectl apply -f -
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "ratings-permissive"
spec:
  targets:
  - name: ratings
  peers:
  - mtls:
      mode: PERMISSIVE
EOF
```

After that, I found the service only worked with plaintext.  I repeated the above kubectl exec / curls, and got the opposite results.  I had expected both curls would work due to permissive settings, or that the first few curls would work because of this issue, but that is not what I observed using daily build from today of 1.1

**Comment by esnible** [comment]
If this is the intended behavior I will close the issue.
