### ISSUE TITLE
autoscaleEnabled: true  does not require replicas: 1

### ISSUE THREAD

**Issue by kramvan1** [istio/istio#11071]
**Describe the bug**
When using `autoscaleEnabled: true` the `replicas: 1` is not needed and can cause harm for a managed environment.

**Expected behavior**
When `autoscaleEnabled: true`, don't include the unneeded `replicas: 1` for deployments.
Add templating logic around the deployment template replica definition: 
```
{{- if not $spec.autoscaleEnabled }}
      replicas: {{ .Values.replicaCount }}
{{- end }}
```

**Steps to reproduce the bug**
Set `autoscaleEnabled: true` and when HPA kicks in and changes the replicas, this can cause confusion for managed environments as the deployment definition is now different from what was initially specified. 

**Version**
1.0.5, 1.1

**Installation**

**Environment**

**Cluster state**

**Comment by kramvan1** [comment]
@linsun fyi

**Comment by linsun** [comment]
confirmed this is good practice:  https://github.com/kubernetes/kubernetes/issues/25238#issuecomment-217928835
