### ISSUE TITLE
springboot jar app on istio can't be accessed by https

### ISSUE THREAD

**Issue by xianke9** [istio/istio#11075]
After I deploy a springboot app with command "java -jar xxx.jar" on istio/kubernetes, I can't access it with https. Once I remove the istio and only deploy this app into kubernetes, it is working fine, and I can access it with https.

The error as the following:
root@m-1:~/sso# curl https://10.0.0.167/login.html -k -tls1_2 -v

Trying 10.0.0.167...
Connected to 10.0.0.167 (10.0.0.167) port 443 (#0)
found 148 certificates in /etc/ssl/certs/ca-certificates.crt
found 592 certificates in /etc/ssl/certs
ALPN, offering http/1.1
gnutls_handshake() failed: An unexpected TLS packet was received.
Closing connection 0
curl: (35) gnutls_handshake() failed: An unexpected TLS packet was received.
root@m-1:~/sso# openssl s_client -connect 10.0.0.167:443 -debug
CONNECTED(00000003)
write to 0x1b715d0 [0x1b71650] (305 bytes => 305 (0x131))
0000 - 16 03 01 01 2c 01 00 01-28 03 03 20 10 60 95 ff ....,...(.. .`..
0010 - d7 61 d5 0a e7 7f 28 9d-66 0e 77 98 09 1c 67 b6 .a....(.f.w...g.
0020 - 8a 92 94 f2 36 50 70 68-ba 61 05 00 00 aa c0 30 ....6Pph.a.....0
0030 - c0 2c c0 28 c0 24 c0 14-c0 0a 00 a5 00 a3 00 a1 .,.(.$..........
0040 - 00 9f 00 6b 00 6a 00 69-00 68 00 39 00 38 00 37 ...k.j.i.h.9.8.7
0050 - 00 36 00 88 00 87 00 86-00 85 c0 32 c0 2e c0 2a .6.........2...*
0060 - c0 26 c0 0f c0 05 00 9d-00 3d 00 35 00 84 c0 2f .&.......=.5.../
0070 - c0 2b c0 27 c0 23 c0 13-c0 09 00 a4 00 a2 00 a0 .+.'.#..........
0080 - 00 9e 00 67 00 40 00 3f-00 3e 00 33 00 32 00 31 ...g.@.?.>.3.2.1
0090 - 00 30 00 9a 00 99 00 98-00 97 00 45 00 44 00 43 .0.........E.D.C
00a0 - 00 42 c0 31 c0 2d c0 29-c0 25 c0 0e c0 04 00 9c .B.1.-.).%......
00b0 - 00 3c 00 2f 00 96 00 41-c0 11 c0 07 c0 0c c0 02 .<./...A........
00c0 - 00 05 00 04 c0 12 c0 08-00 16 00 13 00 10 00 0d ................
00d0 - c0 0d c0 03 00 0a 00 ff-01 00 00 55 00 0b 00 04 ...........U....
00e0 - 03 00 01 02 00 0a 00 1c-00 1a 00 17 00 19 00 1c ................
00f0 - 00 1b 00 18 00 1a 00 16-00 0e 00 0d 00 0b 00 0c ................
0100 - 00 09 00 0a 00 23 00 00-00 0d 00 20 00 1e 06 01 .....#..... ....
0110 - 06 02 06 03 05 01 05 02-05 03 04 01 04 02 04 03 ................
0120 - 03 01 03 02 03 03 02 01-02 02 02 03 00 0f 00 01 ................
0130 - 01 .
read from 0x1b715d0 [0x1b76bb0] (7 bytes => 7 (0x7))
0000 - 48 54 54 50 2f 31 2e HTTP/1.
139842484536984:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:794:
no peer certificate available
No client certificate CA names sent
SSL handshake has read 7 bytes and written 305 bytes
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
Protocol : TLSv1.2
Cipher : 0000
Session-ID:
Session-ID-ctx:
Master-Key:
Key-Arg : None
PSK identity: None
PSK identity hint: None
SRP username: None
Start Time: 1547780283
Timeout : 300 (sec)
Verify return code: 0 (ok)
root@m-1:~/sso#

============================
the following is the log for OK without istio:
root@m-1:/sso# openssl s_client -connect 10.0.0.128:443 -debug
CONNECTED(00000003)
write to 0x1c175d0 [0x1c17650] (305 bytes => 305 (0x131))
0000 - 16 03 01 01 2c 01 00 01-28 03 03 44 ab d2 d1 e9 ....,...(..D....
0010 - bd 1b 26 1d 68 e0 19 a6-6b 66 f2 88 8c 86 91 a1 ..&.h...kf......
0020 - 6a f1 f9 dd 57 14 b3 4e-27 61 c2 00 00 aa c0 30 j...W..N'a.....0
0030 - c0 2c c0 28 c0 24 c0 14-c0 0a 00 a5 00 a3 00 a1 .,.(.$..........
0040 - 00 9f 00 6b 00 6a 00 69-00 68 00 39 00 38 00 37 ...k.j.i.h.9.8.7
0050 - 00 36 00 88 00 87 00 86-00 85 c0 32 c0 2e c0 2a .6.........2...*
0060 - c0 26 c0 0f c0 05 00 9d-00 3d 00 35 00 84 c0 2f .&.......=.5.../
0070 - c0 2b c0 27 c0 23 c0 13-c0 09 00 a4 00 a2 00 a0 .+.'.#..........
0080 - 00 9e 00 67 00 40 00 3f-00 3e 00 33 00 32 00 31 ...g.@.?.>.3.2.1
0090 - 00 30 00 9a 00 99 00 98-00 97 00 45 00 44 00 43 .0.........E.D.C
00a0 - 00 42 c0 31 c0 2d c0 29-c0 25 c0 0e c0 04 00 9c .B.1.-.).%......
00b0 - 00 3c 00 2f 00 96 00 41-c0 11 c0 07 c0 0c c0 02 .<./...A........
00c0 - 00 05 00 04 c0 12 c0 08-00 16 00 13 00 10 00 0d ................
00d0 - c0 0d c0 03 00 0a 00 ff-01 00 00 55 00 0b 00 04 ...........U....
00e0 - 03 00 01 02 00 0a 00 1c-00 1a 00 17 00 19 00 1c ................
00f0 - 00 1b 00 18 00 1a 00 16-00 0e 00 0d 00 0b 00 0c ................
0100 - 00 09 00 0a 00 23 00 00-00 0d 00 20 00 1e 06 01 .....#..... ....
0110 - 06 02 06 03 05 01 05 02-05 03 04 01 04 02 04 03 ................
0120 - 03 01 03 02 03 03 02 01-02 02 02 03 00 0f 00 01 ................
0130 - 01 .
read from 0x1c175d0 [0x1c1cbb0] (7 bytes => 7 (0x7))
0000 - 16 03 03 05 01 02 ......
0007 - <SPACES/NULS>
read from 0x1c175d0 [0x1c1cbba] (1279 bytes => 1279 (0x4FF))
0000 - 00 4d 03 03 5c 41 41 b5-c1 55 cd 96 7b 90 51 79 .M..\AA..U..{.Qy
0010 - 6d 58 95 24 72 5e 74 1c-94 d3 b0 c3 20 43 bc 0d mX.$r^t..... C..
0020 - 35 22 58 5a 20 5c 41 41-b5 b4 5a 4b 74 ba 2b fa 5"XZ \AA..ZKt.+.
0030 - 9d ef 67 a7 6d 5a d2 27-3f 9b 8d 6f 50 6c 2c 52 ..g.mZ.'?..oPl,R
0040 - 1e bd cc 1c 65 c0 30 00-00 05 ff 01 00 01 00 0b ....e.0.........
0050 - 00 03 5b 00 03 58 00 03-55 30 82 03 51 30 82 02 ..[..X..U0..Q0..
0060 - 39 a0 03 02 01 02 02 04-62 96 27 d6 30 0d 06 09 9.......b.'.0...
0070 - 2a 86 48 86 f7 0d 01 01-0b 05 00 30 59 31 0b 30 .H........0Y1.0
0080 - 09 06 03 55 04 06 13 02-63 6e 31 0b 30 09 06 03 ...U....cn1.0...
0090 - 55 04 08 13 02 62 6a 31-0b 30 09 06 03 55 04 07 U....bj1.0...U..
00a0 - 13 02 62 6a 31 0e 30 0c-06 03 55 04 0a 13 05 69 ..bj1.0...U....i
00b0 - 74 61 61 73 31 0c 30 0a-06 03 55 04 0b 13 03 69 taas1.0...U....i
00c0 - 62 6d 31 12 30 10 06 03-55 04 03 13 09 6c 6f 63 bm1.0...U....loc
00d0 - 61 6c 68 6f 73 74 30 1e-17 0d 31 38 31 32 32 30 alhost0...181220
00e0 - 30 36 31 39 35 30 5a 17-0d 31 39 30 33 32 30 30 061950Z..1903200
00f0 - 36 31 39 35 30 5a 30 59-31 0b 30 09 06 03 55 04 61950Z0Y1.0...U.
0100 - 06 13 02 63 6e 31 0b 30-09 06 03 55 04 08 13 02 ...cn1.0...U....
0110 - 62 6a 31 0b 30 09 06 03-55 04 07 13 02 62 6a 31 bj1.0...U....bj1
0120 - 0e 30 0c 06 03 55 04 0a-13 05 69 74 61 61 73 31 .0...U....itaas1
0130 - 0c 30 0a 06 03 55 04 0b-13 03 69 62 6d 31 12 30 .0...U....test1.0
0140 - 10 06 03 55 04 03 13 09-6c 6f 63 61 6c 68 6f 73 ...U....localhos
0150 - 74 30 82 01 22 30 0d 06-09 2a 86 48 86 f7 0d 01 t0.."0....H....
0160 - 01 01 05 00 03 82 01 0f-00 30 82 01 0a 02 82 01 .........0......
0170 - 01 00 90 84 97 70 49 10-32 40 e3 ce d1 48 a7 53 .....pI.2@...H.S
0180 - 66 df 5d 19 8c 4d fb 01-e2 4a 09 ff 55 d8 79 6d f.]..M...J..U.ym
0190 - 57 ba 34 54 ee 5b 6d f6-ae 7e 73 d7 b4 a8 d7 21 W.4T.[m..s....!
01a0 - 70 e9 50 d7 13 a5 a7 73-f7 38 58 b5 35 c1 e1 2b p.P....s.8X.5..+
01b0 - db 81 9b 23 2a 3a a6 34-af eb 4b 01 cb 76 1e fc ...#*:.4..K..v..
01c0 - ea 7b 51 e2 5d 25 f0 6c-79 92 35 54 80 d7 f4 63 .{Q.]%.ly.5T...c
01d0 - 5c 7f 25 cc dd 80 73 df-b8 3b 99 a0 a1 85 1b 71 .%...s..;.....q
01e0 - 34 7f 5c 1d 25 3d be 87-7e f6 c3 3a 01 e9 3d f7 4..%=....:..=.
01f0 - 1f ea bd fe cf 78 86 2a-c6 10 b6 2b 21 4d 97 65 .....x....+!M.e
0200 - 8c 70 1c d3 ce cb 28 10-8f 33 cd b7 b0 35 5c d3 .p....(..3...5.
0210 - 9c a3 f1 9d 00 4f 87 f9-54 b2 ea c9 a0 1c e4 da .....O..T.......
0220 - 24 20 ac 9f 99 c4 e5 a5-62 d9 e5 d2 09 9f 6e 3b $ ......b.....n;
0230 - 93 ba 76 4d 2c 8e 50 65-19 1e d7 43 5d 55 da dd ..vM,.Pe...C]U..
0240 - 00 3b 34 5f b7 f7 ef 1b-f8 49 ba 53 79 0a 99 8a .;4_.....I.Sy...
0250 - 83 5b 2a dd 9b ed db 08-09 4b 28 02 f6 64 fc 85 .[......K(..d..
0260 - 94 21 f3 63 1d d9 48 17-2a 1b 08 3f 14 67 82 29 .!.c..H.*..?.g.)
0270 - b1 03 02 03 01 00 01 a3-21 30 1f 30 1d 06 03 55 ........!0.0...U
0280 - 1d 0e 04 16 04 14 e5 f8-54 d7 70 1c ec d8 17 87 ........T.p.....
0290 - 16 92 7e 06 e9 e8 9b d6-62 82 30 0d 06 09 2a 86 .......b.0....
02a0 - 48 86 f7 0d 01 01 0b 05-00 03 82 01 01 00 8f 20 H..............
02b0 - 30 89 0d c1 ce f7 ad 1f-cf b0 43 d5 1a 97 1a 85 0.........C.....
02c0 - 02 d7 6d 41 99 da d6 89-28 77 04 03 2e 95 ff c0 ..mA....(w......
02d0 - 95 21 8d ec 5d 9e 04 54-43 94 b6 15 52 8a 96 46 .!..]..TC...R..F
02e0 - b7 c7 0d 29 38 ff fc 94-b6 47 38 22 42 69 59 25 ...)8....G8"BiY%
02f0 - 3d 5e 52 5b d5 ed 8a 9b-b9 f4 d3 3b a1 ec 83 1b =^R[.......;....
0300 - 0f 75 b4 ae f8 8c 04 54-15 5f 9a ee c5 16 52 33 .u.....T.....R3
0310 - 7f e4 58 c3 c0 8e 66 5e-fc 75 75 49 ce 1c 82 85 ..X...f^.uuI....
0320 - 8b a7 ad 83 84 77 3b 1b-c6 62 15 c0 ef f7 66 ad .....w;..b....f.
0330 - 1b 23 e1 0e e9 4a 23 21-2c c4 57 91 ac 8e b7 13 .#...J#!,.W.....
0340 - 8f 6f 11 df f8 b4 6f 88-51 5b a5 f4 15 1e 3f 30 .o....o.Q[....?0
0350 - 6e 21 8f ed 88 dc 08 d9-8d 90 c6 61 5d ea c5 b7 n!.........a]...
0360 - f0 af e2 38 4e e5 7e 39-ce be 5f f8 c7 61 df 26 ...8N.~9....a.&
0370 - 97 e4 b5 48 f5 28 f2 87-59 3a f3 4a 23 27 04 80 ...H.(..Y:.J#'..
0380 - 95 b9 d4 6b ab c0 c0 ed-66 96 c9 c6 3c d7 c9 73 ...k....f...<..s
0390 - 5e c7 a0 85 aa 72 d0 f0-9f d9 a1 7b c8 46 30 8a ^....r.....{.F0.
03a0 - 67 73 35 8c 5b d4 24 ce-10 2a b3 25 8f ed 0c 00 gs5.[.$...%....
03b0 - 01 49 03 00 17 41 04 f1-af 57 64 ae 77 72 d9 8b .I...A...Wd.wr..
03c0 - 61 31 73 54 a8 25 75 27-b0 30 3e 98 d3 b3 66 fb a1sT.%u'.0>...f.
03d0 - 14 c5 d5 89 5d db b4 d6-fd 9b d9 4a 9f 08 49 eb ....]......J..I.
03e0 - ed 12 d3 ac 6f 1c 35 2f-5b e2 27 32 1e 94 f7 d4 ....o.5/[.'2....
03f0 - d3 e1 1e ac dd 1d 45 06-01 01 00 3f 6f 45 59 41 ......E....?oEYA
0400 - b7 dd bb 67 9c 54 4f 8d-95 d0 44 12 d3 3b 4b 26 ...g.TO...D..;K&
0410 - c1 78 5a 5c 50 df 7b 16-40 81 1d 8b e5 c6 47 38 .xZ\P.{.@.....G8
0420 - 0b b2 e7 bb 14 86 c2 07-61 78 59 10 4d 0b c6 2d ........axY.M..-
0430 - 0a ba 88 cb 19 a3 ea a7-04 f7 bd e8 4c 56 72 34 ............LVr4
0440 - ab 49 83 d5 1b b1 50 06-fa 1f 65 52 49 08 68 b9 .I....P...eRI.h.
0450 - 86 21 39 52 47 07 30 fe-90 b1 1c 75 70 c6 ec 16 .!9RG.0....up...
0460 - 12 cd df 54 0c d6 1b cc-3b 1c f8 0d d5 3d 8e ad ...T....;....=..
0470 - 58 f9 16 8e 22 bc a4 60-a2 4a 74 60 b8 47 6f ca X..."...Jt.Go.
0480 - 57 06 11 3e f6 36 bf 92-87 1c 8b c8 67 82 00 3c W..>.6......g..<
0490 - 8e d6 3e bc 20 09 77 7a-0d 7a a5 e7 52 ed 67 09 ..>. .wz.z..R.g.
04a0 - a7 9a a6 d7 18 c7 9d 86-f5 f1 18 d6 b0 97 66 d1 ..............f.
04b0 - bd fe ec 9e 85 a3 bf e4-b7 f2 d4 01 fb cb f6 2b ...............+
04c0 - 87 9f e8 fe b6 ab df f1-2f f6 69 c0 05 37 66 3e ......../.i..7f>
04d0 - dd 75 a9 94 36 14 ff 62-db 88 2b aa 21 ef 24 8b .u..6..b..+.!.$.
04e0 - 68 32 80 1c 00 d4 3c b4-a4 f7 29 06 59 58 c4 14 h2....<...).YX..
04f0 - 40 da bb 35 2b ba 9b 79-91 76 17 0e @..5+..y.v..
04ff - <SPACES/NULS>
depth=0 C = cn, ST = bj, L = bj, O = itaas, OU = test, CN = localhost
verify error:num=18:self signed certificate
verify return:1
depth=0 C = cn, ST = bj, L = bj, O = itaas, OU = test, CN = localhost
verify return:1
write to 0x1c175d0 [0x1c26b00] (75 bytes => 75 (0x4B))
0000 - 16 03 03 00 46 10 00 00-42 41 04 a5 96 bc a2 0e ....F...BA......
0010 - 85 3d f5 48 a6 44 35 ba-79 e2 a8 db 85 27 6d f1 .=.H.D5.y....'m.
0020 - 0f f4 d0 d0 5e 23 ef 93-25 34 cc 23 38 a1 38 8a ....^#..%4.#8.8.
0030 - 7d 49 e6 e6 5c 73 b1 5c-d8 b3 7e 89 c0 01 a5 66 }I..\s...~....f
0040 - 6d 57 34 f1 62 11 3b c1-40 5e dc mW4.b.;.@^.
write to 0x1c175d0 [0x1c26b00] (6 bytes => 6 (0x6))
0000 - 14 03 03 00 01 01 ......
write to 0x1c175d0 [0x1c26b00] (45 bytes => 45 (0x2D))
0000 - 16 03 03 00 28 47 b4 38-8d d7 a7 f6 07 8f 52 4e ....(G.8......RN
0010 - 4b c6 b7 8d 53 4a 54 2e-fc f0 6d fc 97 50 e3 f0 K...SJT...m..P..
0020 - e7 ab e1 2b 40 9f b8 4c-38 3e 1e 75 1e ...+@..L8>.u.
read from 0x1c175d0 [0x1c1cbb3] (5 bytes => 5 (0x5))
0000 - 14 03 03 00 01 .....
read from 0x1c175d0 [0x1c1cbb8] (1 bytes => 1 (0x1))
0000 - 01 .
read from 0x1c175d0 [0x1c1cbb3] (5 bytes => 5 (0x5))
0000 - 16 03 03 00 28 ....(
read from 0x1c175d0 [0x1c1cbb8] (40 bytes => 40 (0x28))
0000 - 00 00 00 00 00 00 00 00-6a 2c 28 53 3f 4e ac 76 ........j,(S?N.v
0010 - a9 79 2e 9b 6e 83 c0 f7-08 34 03 db f6 82 f2 e0 .y..n....4......
0020 - 9f 71 be 00 87 6a b5 d9- .q...j..
Certificate chain
0 s:/C=cn/ST=bj/L=bj/O=itaas/OU=test/CN=localhost
i:/C=cn/ST=bj/L=bj/O=itaas/OU=test/CN=localhost
Server certificate
-----BEGIN CERTIFICATE-----
MIIDUTCCAjmgAwIBAgIEYpYn1jANBgkqhkiG9w0BAQsFADBZMQswCQYDVQQGEwJj
bjELMAkGA1UECBMCYmoxCzAJBgNVBAcTAmJqMQ4wDAYDVQQKEwVpdGFhczEMMAoG
A1UECxMDaWJtMRIwEAYDVQQDEwlsb2NhbGhvc3QwHhcNMTgxMjIwMDYxOTUwWhcN
MTkwMzIwMDYxOTUwWjBZMQswCQYDVQQGEwJjbjELMAkGA1UECBMCYmoxCzAJBgNV
BAcTAmJqMQ4wDAYDVQQKEwVpdGFhczEMMAoGA1UECxMDaWJtMRIwEAYDVQQDEwls
b2NhbGhvc3QwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCQhJdwSRAy
QOPO0UinU2bfXRmMTfsB4koJ/1XYeW1XujRU7ltt9q5+c9e0qNchcOlQ1xOlp3P3
OFi1NcHhK9uBmyMqOqY0r+tLAct2Hvzqe1HiXSXwbHmSNVSA1/RjXH8lzN2Ac9+4
O5mgoYUbcTR/XB0lPb6HfvbDOgHpPfcf6r3+z3iGKsYQtishTZdljHAc087LKBCP
M823sDVc05yj8Z0AT4f5VLLqyaAc5NokIKyfmcTlpWLZ5dIJn247k7p2TSyOUGUZ
HtdDXVXa3QA7NF+39+8b+Em6U3kKmYqDWyrdm+3bCAlLKAL2ZPyFlCHzYx3ZSBcq
Gwg/FGeCKbEDAgMBAAGjITAfMB0GA1UdDgQWBBTl+FTXcBzs2BeHFpJ+Bunom9Zi
gjANBgkqhkiG9w0BAQsFAAOCAQEAjyAwiQ3BzvetH8+wQ9UalxqFAtdtQZna1oko
dwQDLpX/wJUhjexdngRUQ5S2FVKKlka3xw0pOP/8lLZHOCJCaVklPV5SW9Xtipu5
9NM7oeyDGw91tK74jARUFV+a7sUWUjN/5FjDwI5mXvx1dUnOHIKFi6etg4R3OxvG
YhXA7/dmrRsj4Q7pSiMhLMRXkayOtxOPbxHf+LRviFFbpfQVHj8wbiGP7YjcCNmN
kMZhXerFt/Cv4jhO5X45zr5f+Mdh3yaX5LVI9Sjyh1k680ojJwSAlbnUa6vAwO1m
lsnGPNfJc17HoIWqctDwn9mhe8hGMIpnczWMW9QkzhAqsyWP7Q==
-----END CERTIFICATE-----
subject=/C=cn/ST=bj/L=bj/O=itaas/OU=test/CN=localhost
issuer=/C=cn/ST=bj/L=bj/O=itaas/OU=test/CN=localhost
No client certificate CA names sent
Peer signing digest: SHA512
Server Temp Key: ECDH, P-256, 256 bits
SSL handshake has read 1337 bytes and written 431 bytes
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
Protocol : TLSv1.2
Cipher : ECDHE-RSA-AES256-GCM-SHA384
Session-ID: 5C4141B5B45A4B74BA2BFA9DEF67A76D5AD2273F9B8D6F506C2C521EBDCC1C65
Session-ID-ctx:
Master-Key: C27A159A1EA6A0FC2141B191BD95906F2C129919CC7143A7E17EA1554FCD0686530B07B75DD4EFA8FA60BF30028FCBC3
Key-Arg : None
PSK identity: None
PSK identity hint: None
SRP username: None
Start Time: 1547780533
Timeout : 300 (sec)
Verify return code: 18 (self signed certificate)
ENV info:
root@m-1:~/sso# istioctl version
Version: 1.0.0
GitRevision: 3a136c90ec5e308f236e0d7ebb5c4c5e405217f4
User: root@71a9470ea93c
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean

**Comment by esnible** [comment]
Istio seems happiest when applications do plain HTTP and the Envoy sidecar exposes the plain HTTP as HTTPS.  That strategy allows the sidecar to inspect the HTTP traffic and apply Istio's rules and policies for things like weights.

If a container implements HTTPS itself then Envoy must be told not to look into the traffic.  To do that, in the Service, for the Port, give it a name `tcp`, like this:

```
apiVersion: v1
kind: Service
metadata:
  name: tcp-echo
  labels:
    app: tcp-echo
spec:
  ports:
  - name: tcp
    port: 9000
  selector:
    app: tcp-echo
```

(the above is from the Istio _samples/tcp-echo/tcp-echo-services.yaml_  example).

You can also try

```
  - port: 443
    name: https
```

(the above is from _samples/https/nginx-app.yaml_.  Don't use 'http' for the name unless the container app does unencrypted HTTP/1.1.

**Comment by linsun** [comment]
close this as no response from reporter in 30 days, pls reopen if needed.
