### ISSUE TITLE
Citadel should re-issue secrets immediately when it starts if the certificate should change

### ISSUE THREAD

**Issue by esnible** [istio/istio#11085]
Step 3 of https://istio.io/docs/tasks/security/plugin-ca-cert/#plugging-in-the-existing-certificate-and-key says "To make sure the workloads obtain the new certificates promptly, delete the secrets generated by Citadel (named as istio.*). In this example, istio.default. Citadel will issue new certificates for the workloads."

This request is for Citadel to check the secrets on start-up and patch them if needed.  The user expects Citadel to keep the secrets in sync.  It should not be necessary to restart Citadel and delete secrets when cacerts changes.

It would also be ideal if Citadel watched cacerts on the file system for changes and did this work without needing to be redeployed.

**Comment by linsun** [comment]
cc @wattli @liminw for thoughts
