### ISSUE TITLE
Restrict the paths Pilot agent can forward for health checks

### ISSUE THREAD

**Issue by myidpt** [istio/istio#11088]
**Describe the bug**
To enable health check bypassing Envoy, the Pilot agent can open a port to forward the requests to the the workload for health check, in which the path is specified in the request header. But there's no restrictions on which path the pilot agent can call. This leaves a backdoor for callers to bypass Envoy to call the workload for services other than health check.

**Expected behavior**
Pilot agent should be restrictive on which path it can call.

**Version**
1.1

**Comment by awly** [comment]
Consider also restricting methods (only GET), body (no body) and headers.
IMO ideally only path and port are taken from incoming request, with restrictions.

**Comment by incfly** [comment]
I've add a comment in https://github.com/istio/istio/issues/9150#issuecomment-455346955. I'll continue working to use pilot agent to pass original app prober config.
