### ISSUE TITLE
Switch over to the new MCP protos

### ISSUE THREAD

**Issue by ozevren** [istio/istio#11094]
We have made changes to the MCP API surface, to accommodate some upcoming needs (incremental and reverse MCP). We'd like to switch over to using these protos to avoid unnecessary backward compatibility issues and having to support the old protocol protos.

The majority of changes to the protocol is structural refactoring, switching over to the new protos.

**Comment by ayj** [comment]
addressed by https://github.com/istio/istio/pull/11292
