### ISSUE TITLE
Add custom PersistentVolumeClaim support for Prometheus

### ISSUE THREAD

**Issue by dozer47528** [istio/istio#11107]
**Describe the feature request**

When Prometheus restarted, it will lose all the data.

**Describe alternatives you've considered**
Can istio support custom PersistentVolumeClaim for Prometheus and jaeger?

**Comment by hzxuzhonghu** [comment]
Isn't this a k8s issue? `PersistentVolumeClaim ` is for users to store persistent data.

**Comment by rokerkony** [comment]
Hey guys, we have the same issue that all the data are lost after restart... We are using istio's chart, but maybe would be good to migrate here smth from the "default chart"?
https://github.com/helm/charts/tree/master/stable/prometheus

**Comment by douglas-reid** [comment]
I believe there is PVC support via the prom operator with the new installer. I'm going to mark this as resolved given that forward path. Please re-open if you feel more is needed here.
