### ISSUE TITLE
sample needed for websockets with socket.io

### ISSUE THREAD

**Issue by musicformellons** [istio/istio#11121]
I am trying to setup a node.js socket.io server (express) on GKE but can not get it working. Might be since the sample code here for websockets (which did work on GKE) is python based it does not need a handshake / sticky session. Anyway, would be great to have an example with nodejs & socket.io as I run into problems. 

See details on my issue are [here](https://stackoverflow.com/questions/53987459/websockets-on-gke-with-istio-gives-no-healthy-upstream-and-crashloopbackoff).

**Comment by musicformellons** [comment]
Thanks, I solved this a couple of hours ago... I had a dependency, uws, which need an older node version. It all works great now!!

**Comment by skalinets** [comment]
@musicformellons does it work for you when there is more than one replica in the replicaset? For me it works out of the box when replicas:1, but does not, when that number is higher.

**Comment by musicformellons** [comment]
Not tried yet... I have one replica...

**Comment by smellytoufu** [comment]
> 
> 
> @musicformellons does it work for you when there are more than one replica in the replicaset? For me it works out of the box when replicas:1, but does not, when that number is higher.

Same for me. once I have 2 replicas it doesn't work

**Comment by smellytoufu** [comment]
> 
> 
> @musicformellons does it work for you when there are more than one replica in the replicaset? For me it works out of the box when replicas:1, but does not, when that number is higher.

Same for me. once I have 2 replicas it doesn't work

**Comment by skalinets** [comment]
I asked this question on https://discuss.istio.io/t/istio-setup-for-socket-io/2383
