### ISSUE TITLE
change default monitoring port

### ISSUE THREAD

**Issue by linsun** [istio/istio#11125]
In our global helm configuration, we are currently using port 9093 as default. This has caused port conflict issues for a number of users, especially who uses Kafka which also often uses port 9093. (And it is not easy to debug this prob, can take days.)

-----------//--------------

monitoring port used by mixer, pilot, galley
monitoringPort: 9093
-----------//--------------

**Comment by linsun** [comment]
@ericvn can you take a look at this and see if we can pass all testing with the change?

@GregHanson do we have a list of reserved ports documented somewhere?

**Comment by GregHanson** [comment]
@linsun I know this list has made appearances in PRs/issues in the past but I can't find any links.  The best bet is to check the helm charts for service ports.  Can create a httpbin ServiceEntry with TCP port definition for any of the ports in question.  Will see errors in XDS pushes in pilot-discovery from sidecars rejecting configs with duplicate listeners

**Comment by linsun** [comment]
@GregHanson thank you!  Agreed that helm files (values.yaml, deployment, service yaml etc) would be good starting point to capture a list of ports used currently.

**Comment by linsun** [comment]
@duderino  FYI

**Comment by linsun** [comment]
@ericvn this is discussed in release call today with @costinm @mandarjog and google users also run into this issue and they also agreed with the port change.  In fact they want to change all other 90xx ports but for 1.1, let's change the port 9093 first due to conflict with kafka.

they recommended to use port range from 15000 and use that range for all control plane ports down the road.

cc @wenchenglu

**Comment by linsun** [comment]
a potential release note item cc @geeknoid

**Comment by esnible** [comment]
@linsun if it takes days to find the port conflict we should probably reference https://github.com/istio/istio/issues/9273 which is an issue discussing port conflicts.

**Comment by esnible** [comment]
Port 9093 isn't just used by mixer, pilot, and galley.

The services using it are istio-system/istio-citadel, istio-system/istio-galley, istio-system/istio-pilot, istio-system/istio-policy, and istio-system/istio-telemetry

**Comment by duderino** [comment]
@linsun https://github.com/istio/istio/pull/11421 has been merged.  is anything else needed here?

**Comment by duderino** [comment]
@costinm @sdake ^^^

**Comment by linsun** [comment]
I think the issue can be closed, pending @ericvn approval when he returns tomorrow. :).

**Comment by linsun** [comment]
https://github.com/istio/istio.io/pull/3183

**Comment by ericvn** [comment]
Two documentation PRs were merged:
- https://github.com/istio/istio.io/pull/3183
- https://github.com/istio/istio.io/pull/3184

**Comment by GregHanson** [comment]
closing since all related PR's have merged
