### ISSUE TITLE
There shouldn't be "." inside the tar files of the release packages.

### ISSUE THREAD

**Issue by costinm** [istio/istio#1112]
@fleeto commented on [Thu Oct 12 2017](https://github.com/istio/issues/issues/96)

**Is this a BUG or FEATURE REQUEST?:**

**Did you review existing epics or issues to identify if this already being worked on?** (please try to add the correct labels and epics):

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version
kubectl version
```

**Is Istio Auth enabled or not ?**
Did you install istio.yaml, istio-auth.yaml....

**What happened**:

It will  change current folder's owner if current user has the permission.

**What you expected to happen:**

**How to reproduce it:**

~~~bash
mkdir abc
cd abc
tar -xvf ~/istio-0.2.7-linux.tar.gz`
ls -la ..
...

We will see:
...
drwxr-xr-x.  3 195408 5000      25 Oct  4 04:44 abc
...
~~~

**Feature Request:**
N

**Describe the feature:**

---

@costinm commented on [Thu Oct 12 2017](https://github.com/istio/issues/issues/96#issuecomment-336212890)

I can't reproduce it - and not sure how it could happen, tar will create a new directory but it is not supposed to change anything in the current directory. Can you double check and provide the permissions of the 
parent dir before/after ? 

---

@costinm commented on [Thu Oct 12 2017](https://github.com/istio/issues/issues/96#issuecomment-336213346)

Laurent checked - and indeed there is a "." entry in the tar, it's a valid bug.

**Comment by ldemailly** [comment]
```
$ tar tvfz istio-0.2.7-linux.tar.gz 
drwxr-xr-x  0 releng releng      0 Oct  3 13:44 ./
drwxr-xr-x  0 releng releng      0 Oct  3 13:44 ./istio-0.2.7/
-rw-r--r--  0 releng releng   5775 Oct  3 15:11 ./istio-0.2.7/README.md
-rw-r--r--  0 releng releng    863 Oct  3 15:11 ./istio-0.2.7/istio.VERSION
[...]
```
the first line `./` should not be there
