### ISSUE TITLE
Injecting sidecar behaves differently for different containers - Missing envoy filters on listener

### ISSUE THREAD

**Issue by adityats2020** [istio/istio#11132]
I am seeing inconsistent behavior on injecting sidecar. Primarily, I am not seeing ingress access logs in envoy for my container. The same mode (commands) of injection for httpbin however does not face this issue.

Command used: istioctl kube-inject

**Expected behavior**
Envoy sidecar should have Http Connection Manager filter added to the corresponding listeners. Http Connection manager is responsible for logs. I am not seeing it for the container I built, but seeing it for httpbin. There is no diff in the deployment specs except name and port.

**Version**
$kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-28T15:19:47Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.11-eks", GitCommit:"6bf27214b7e3e1e47dce27dcbd73ee1b27adadd0", GitTreeState:"clean", BuildDate:"2018-12-04T13:33:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

$ istioctl version
Version: 1.0.5
GitRevision: c1707e45e71c75d74bf3a5dec8c7086f32f32fad-dirty
GolangVersion: go1.11.4

**Installation**
Using Helm

**Environment**
Kubernetes

**Cluster state**
Attaching the istio config map as I think that is the related dump here.
[istio-cm.txt](https://github.com/istio/istio/files/2780699/istio-cm.txt)

Attaching the listeners for httpbin and my container(named authorizer).
[httpbin-listener w: conn_manager.txt](https://github.com/istio/istio/files/2780712/httpbin-listener.w.conn_manager.txt)
[authorizer-listener w: conn_manager.txt](https://github.com/istio/istio/files/2780711/authorizer-listener.w.conn_manager.txt)

**Comment by esnible** [comment]
_samples/httpbin/httpbin.yaml_ includes a Service with the following port definition:

```
  - name: http
    port: 8000
    targetPort: 80
```

In Istio, the _name_ of the port is meaningful.  If the name is `http`, or `http-*`, Istio will treat the traffic as HTTP.  Without the special name, it may treat the traffic as TCP.  Can you check your Service definition and see if changing the name affects your deployment?

**Comment by adityats2020** [comment]
Yes. That was it. I was renaming the port to something else in my config and that was making envoy treat it as tcp like you mentioned. You can close this.

The port name has to be http to get http_connection_manager added to envoy.
