### ISSUE TITLE
Gateway and virtual service in different namespaces not working

### ISSUE THREAD

**Issue by linsun** [istio/istio#11131]
**Describe the bug**
One of our users report that he has to put gateway resource and virtual service that bound to the gateway in the same namespace to get it working.  Is this a limitation (or a bug) we have?  I don't find it documented as a limitation in istio.io (https://istio.io/docs/concepts/traffic-management/#gateways) or api (https://github.com/istio/api/blob/master/networking/v1alpha3/gateway.proto)

This is not desired because he expect infra admin to control gateway resource definition and each team in its own namespace to control its own virtual services.

**Version**
1.0.x 

**Environment**
k8s IKS

**Comment by linsun** [comment]
@frankbu @rshriram could you comment if this is a limitation that is purposely done or a bug we should fix?

**Comment by frankbu** [comment]
The virtual service needs to qualify the gateway name with the namespace. I think it was something like `mygateway.somenamespace` in 1.0, but as part of the sidecar model and gateway cleanup, the syntax is like this now: https://github.com/istio/api/blob/6286ff0e63603c77cf7ec30510c39e5cebae65b2/networking/v1alpha3/gateway.proto#L104

**Comment by linsun** [comment]
Thank you @frankbu, so this is a supported scenario where VS and Gateway are in different namespaces.

I will try it in a 1.1 build.

**Comment by linsun** [comment]
https://github.com/istio/istio/pull/11127

**Comment by eperdeme** [comment]
Did this work for you in the end ?

**Comment by frankbu** [comment]
I just tried on istio 1.1.3 to put the bookinfo gateway into the `istio-system` namespace and kept the virtual service in `default` with `istio-system/` in front of the gateway name. It works fine, but Kiali does report an error. Kiali doesn't seem to have been updated to understand the `namespace/` syntax.

**Comment by frankbu** [comment]
Add `area/policies and telemetry` label since it's a Kiali bug.

**Comment by jmazzitelli** [comment]
cc @lucasponce

**Comment by douglas-reid** [comment]
@jmazzitelli I'm closing this issue, as the final comment is that this is a Kiali issue. It should be tracked on the Kiali repo.

**Comment by lucasponce** [comment]
It sounds a bug in the Kiali validation editor.
@frankbu thanks for reporting this.
Could you confirm which version of Kiali are you using ? Just to confirm that is not already addressed in upstream.

**Comment by frankbu** [comment]
@lucasponce I used the version of Kiali in the Istio 1.1.3 release.

**Comment by jmazzitelli** [comment]
> @lucasponce I used the version of Kiali in the Istio 1.1.3 release.

There is an "About" box in Kiali that can retrieve a bunch of version strings to ensure you know what you really are running... but the Kiali that is in 1.1.3 is v0.14. I'm still waiting for the PR to be merged that gets the next 1.1.x release up to a more recent version of v0.16 - see https://github.com/istio/istio/pull/13312

**Comment by lucasponce** [comment]
Hello @frankbu, 
I think this issue is addressed in upstream as gateway validations support multiple namespaces
https://github.com/kiali/kiali/blob/master/business/checkers/gateway_checker.go#L18

This commit is included from Kiali version v0.16.

I think that should cover the scenario you propose.

**Comment by jmazzitelli** [comment]
> This commit is included from Kiali version v0.16.

istio will get this version of kiali as soon as someone merges this PR: https://github.com/istio/istio/pull/13312

it is hit-or-miss when these PRs get merged... I don't know what the criteria is to get things merged into the 1.1 branch. I just create the PRs, I don't merge them :)

**Comment by argeualcantara** [comment]
@lucasponce @frankbu @douglas-reid This information about gateways needing to have <namespace>/my-gateway should be updated in this doc here: https://istio.io/docs/reference/config/networking/v1alpha3/virtual-service/#HTTPMatchRequest

**Comment by tariq1890** [comment]
Hello @linsun @frankbu I am able to get the `bookinfo` application to work if the pods, gateways and virtualservices aree deployed in the same namespace as that of `istio-ingressgateway`.

But If I move `bookinfo` resources to another namespace, it doesn't work. I've even tried the approach suggested by @frankbu where I create the gateway of `bookinfo` in the same namespace as `istio-ingressgateway` and have the virtualservice point to the `bookinfo-gateway` through `istio-system/bookinfo` in the gateways field of the `bookinfo` virtualservice.

Requesting some pointers in debugging this.

**Comment by tariq1890** [comment]
By "getting it to work", I mean access the `productpage` from external traffic through the `istio-ingressgateway` load balancer.

**Comment by frankbu** [comment]
@tariq1890 Maybe this will help you: https://istio.io/docs/ops/best-practices/traffic-management/#cross-namespace-configuration

**Comment by tariq1890** [comment]
@frankbu Thanks for your response. That did not help unfortunately. I have raised the issue here. Requesting your inputs on that:
https://github.com/istio/istio/issues/23347
