### ISSUE TITLE
Pilot supports to watch multiple specified namespaces

### ISSUE THREAD

**Issue by morvencao** [istio/istio#11146]
**Describe the feature request**
Current, if we specify `oneNamespace` to be true when deploying istio, pilot will  watch resources in `istio-system` namespace by default, and we have to deploy applications and traffic rules in `istio-system` namespace.

If we use the default value(`false`) of `oneNamespace`, pilot will watch resources in all namespace. If there are large amount of services existing in the cluster, resulting that pilot will generate envoy configuration will huge size(will lots of upstream clusters). 

@andraxylia @ayj 
Is it possible that pilot watch resources in namespace list specified by end-user, so that envoy configuration will not flood the sidecar container? and also decrease the time of configuration propagation?

/cc @gyliu513 @clyang82

**Comment by ayj** [comment]
cc @costinm @rshriram @louiscryan - I believe the sidecar API resource is intended to address this problem.

**Comment by morvencao** [comment]
@ayj @rshriram @louiscryan  I wonder if this is getting any focus in Istio v1.1. Some users intent to take Istio into production ending up with a very overloaded pilot, they really want the multi-tenant support to accomplish resources isolation.

**Comment by morvencao** [comment]
Great! That really helps a lot.

**Comment by knrc** [comment]
We have been working on something similar to this but are taking a different approach to the configuration, we're working on a more dynamic solution through a custom resource that the control plane can react to.  We're integrating this with our operator so the appropriate roles etc. can be updated.

**Comment by knrc** [comment]
BTW the work we are doing is specifically focussing on soft multi-tenancy so not related to the issue addressed by sidecar but rather to ensuring we have appropriate segregation between the multiple control planes.  Moving away from ClusterRoles is another part of our change.
