### ISSUE TITLE
Telemetry resulting from injected faults is wrong.

### ISSUE THREAD

**Issue by jmazzitelli** [istio/istio#11151]
**Describe the bug**
Telemetry resulting from injected faults is wrong.

I have Istio 1.1-snapshot.4 installed, with bookinfo. I then added my own fault injection rule using this yaml:

```yaml
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: details-abort-vs
spec:
  hosts:
  - details
  http:
  - fault:
      abort:
        httpStatus: 555
        percent: 100
    route:
    - destination:
        host: details
        subset: details-abort-dr-subset-v1
  - route:
    - destination:
        host: details
        subset: details-abort-dr-subset-v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: details-abort-dr
spec:
  host: details
  subsets:
  - name: details-abort-dr-subset-v1
    labels:
      version: v1
```

When I view this traffic in Kiali, I see some really odd connectivity:

![bad-telemetry-graph](https://user-images.githubusercontent.com/2029470/51552145-f7c17580-1e3d-11e9-8488-3d4570a3ebfe.png)

That red edge from "productpage" node to "details" node is correct - that is the client-side injected fault. However, there should not be red edges from the "details" node to the "reviews" node - for one thing, bookinfo's "details" never go to reviews in the first place, but secondly, these are client-side injected faults, so the request should never have made it to any workload or app node.

Looking at the telemetry in Prometheus, I see that Kiali is indeed graphing the telemetry correctly. However, the telemetry itself is incorrect. Here's the Prometheus query results:

![bad-telemetry-prom](https://user-images.githubusercontent.com/2029470/51552205-132c8080-1e3e-11e9-8cab-70020ec0d670.png)

Look at the timeseries - how is it possible that "productpage" (source_app) is sending to a destination service of "details" but that request is going to a destination_workload of "reviews-v[123]"? Those three timeseries with destination_workload of "reviews-v[123]" should not be there - they are wrong.

Here is the full telemetry for those four timeseries - using prom query `istio_requests_total{source_app="productpage",response_code="555"}`

```
istio_requests_total{connection_security_policy="unknown",destination_app="reviews",destination_principal="unknown",destination_service="details.bookinfo.svc.cluster.local",destination_service_name="details",destination_service_namespace="bookinfo",destination_version="v1",destination_workload="reviews-v1",destination_workload_namespace="bookinfo",instance="172.17.0.9:42422",job="istio-mesh",permissive_response_code="none",permissive_response_policyid="none",reporter="source",request_protocol="http",response_code="555",source_app="productpage",source_principal="unknown",source_version="v1",source_workload="productpage-v1",source_workload_namespace="bookinfo"}

istio_requests_total{connection_security_policy="unknown",destination_app="reviews",destination_principal="unknown",destination_service="details.bookinfo.svc.cluster.local",destination_service_name="details",destination_service_namespace="bookinfo",destination_version="v2",destination_workload="reviews-v2",destination_workload_namespace="bookinfo",instance="172.17.0.9:42422",job="istio-mesh",permissive_response_code="none",permissive_response_policyid="none",reporter="source",request_protocol="http",response_code="555",source_app="productpage",source_principal="unknown",source_version="v1",source_workload="productpage-v1",source_workload_namespace="bookinfo"}

istio_requests_total{connection_security_policy="unknown",destination_app="reviews",destination_principal="unknown",destination_service="details.bookinfo.svc.cluster.local",destination_service_name="details",destination_service_namespace="bookinfo",destination_version="v3",destination_workload="reviews-v3",destination_workload_namespace="bookinfo",instance="172.17.0.9:42422",job="istio-mesh",permissive_response_code="none",permissive_response_policyid="none",reporter="source",request_protocol="http",response_code="555",source_app="productpage",source_principal="unknown",source_version="v1",source_workload="productpage-v1",source_workload_namespace="bookinfo"}

istio_requests_total{connection_security_policy="unknown",destination_app="unknown",destination_principal="unknown",destination_service="details.bookinfo.svc.cluster.local",destination_service_name="details",destination_service_namespace="bookinfo",destination_version="unknown",destination_workload="unknown",destination_workload_namespace="unknown",instance="172.17.0.9:42422",job="istio-mesh",permissive_response_code="none",permissive_response_policyid="none",reporter="source",request_protocol="http",response_code="555",source_app="productpage",source_principal="unknown",source_version="v1",source_workload="productpage-v1",source_workload_namespace="bookinfo"}
```

**Expected behavior**
The telemetry should only have the "unknown" timeseries that you see above in the Prometheus screenshot:

```
{destination_app="unknown",destination_service_name="details",destination_workload="unknown",reporter="source"}
```

The other three that show a destination_service of "details" but destination_workload of "reviews-v[123]" are incorrect and should not be there at all.

**Steps to reproduce the bug**
1. Install Istio 1.1-snapshot.4
2. Install bookinfo demo
3. `kubectl create -f` the yaml file I show above. It is called [bookinfo-details-abort.yaml](https://raw.githubusercontent.com/kiali/kiali/f7973066a80b64cd23d9281e882b2fd5ed70f9d3/hack/istio/bookinfo-details-abort.yaml)

**Version**

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:46:06Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-01-16T18:55:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

$ istioctl version
version.BuildInfo{Version:"1.1.0-snapshot.4", GitRevision:"e661de08e04e78e60f7fbec067e4357974fa27c3", User:"root", Host:"b44b0137-027e-11e9-a4d9-0a580a2c0c84", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean"}

**Installation**

Using Helm

**Environment**

RHEL 7, OpenShift 3.11

**Comment by jmazzitelli** [comment]
@douglas-reid does this sound familiar to you? I'm curious if it's a known issue. It's easily detected in the Kiali graph, but not sure how many are using Kiali to visualize 1.1 telemetry yet.

**Comment by douglas-reid** [comment]
@jmazzitelli I haven't fully digested this yet, but there was another (possibly related ?) issue with the calculation of attributes in the proxy. @mandarjog and @kyessenov have looked at that issue -- perhaps they can help here. I'll dig in more in a bit.

**Comment by douglas-reid** [comment]
@jmazzitelli I can duplicate your issue. Looking through logs now...

**Comment by douglas-reid** [comment]
Got some attribute logs:

```
connection.mtls               : false
context.protocol              : http
context.proxy_error_code      : FI
context.reporter.kind         : outbound
context.reporter.uid          : kubernetes://productpage-v1-8fcdcb496-nbv5b.default
destination.ip                : [10 24 0 12]
destination.port              : 9080
destination.service.host      : details.default.svc.cluster.local
destination.service.name      : details
destination.service.namespace : default
destination.service.uid       : istio://default/services/details
destination.uid               : kubernetes://reviews-v3-654d6f5b95-vtqgn.default
origin.ip                     : [10 24 2 16]
request.headers               : stringmap[x-request-id:5b995643-a3ef-4996-83d7-2659cbbee21b x-envoy-decorator-operation:details.default.svc.cluster.local:9080/* user-agent:python-requests/2.20.0 x-b3-spanid:39ffd4c3c711b48f :path:/details/0 accept-encoding:gzip, deflate :authority:details:9080 x-forwarded-proto:http x-b3-traceid:ece946731ed3b48919b804ac42e73b5a x-b3-parentspanid:19b804ac42e73b5a :method:GET x-b3-sampled:0 accept:*/*]
request.host                  : details:9080
request.method                : GET
request.path                  : /details/0
request.scheme                : http
request.size                  : 0
request.time                  : 2019-01-22 20:36:30.806570993 +0000 UTC
request.total_size            : 369
request.url_path              : /details/0
request.useragent             : python-requests/2.20.0
response.code                 : 555
response.duration             : 124.908µs
response.headers              : stringmap[content-length:18 server:envoy content-type:text/plain :status:555 date:Tue, 22 Jan 2019 20:36:30 GMT]
response.size                 : 18
response.time                 : 2019-01-22 20:36:30.806585048 +0000 UTC
response.total_size           : 110
source.namespace              : default
source.uid                    : kubernetes://productpage-v1-8fcdcb496-nbv5b.default
---
destination.container.name    : reviews
destination.labels            : stringmap[app:reviews pod-template-hash:2108291651 version:v3]
destination.name              : reviews-v3-654d6f5b95-vtqgn
destination.namespace         : default
destination.owner             : kubernetes://apis/apps/v1/namespaces/default/deployments/reviews-v3
destination.serviceAccount    : default
destination.workload.name     : reviews-v3
destination.workload.namespace: default
destination.workload.uid      : istio://default/workloads/reviews-v3
source.ip                     : [0 0 0 0 0 0 0 0 0 0 255 255 10 24 2 16]
source.labels                 : stringmap[app:productpage pod-template-hash:497876052 version:v1]
source.name                   : productpage-v1-8fcdcb496-nbv5b
source.owner                  : kubernetes://apis/apps/v1/namespaces/default/deployments/productpage-v1
source.serviceAccount         : default
source.workload.name          : productpage-v1
source.workload.namespace     : default
source.workload.uid           : istio://default/workloads/productpage-v1
```

Looks like `destination.workload.uid` is wrong.

**Comment by jmazzitelli** [comment]
looks like a bunch of  destination attribs are wrong:

```
destination.container.name    : reviews
destination.labels            : stringmap[app:reviews pod-template-hash:2108291651 version:v3]
destination.name              : reviews-v3-654d6f5b95-vtqgn
destination.owner             : kubernetes://apis/apps/v1/namespaces/default/deployments/reviews-v3
destination.workload.name     : reviews-v3
```

If these are from the result of the fault injection, anything related to a destination workload should be unknown, right?. Secondly, I'm not sure how these even got references to "reviews" because all requests with a destination.service of "details" should never have telemetry with destination.workload of "reviews". All those requests only ever go to the "details" workload.

**Comment by mandarjog** [comment]
I am looking at another destination.uid issue, I wonder if this is related? If uid is wrong then all metadata will also be wrong.

**Comment by kyessenov** [comment]
In case of FI there should not be destination.uid sent by envoy. Normally, it's set through EDS, but in FI case EDS is not utilized.

**Comment by douglas-reid** [comment]
It appears that `destination.uid` is not being set on the wire:

```
2019-01-22T20:36:31.030280Z	debug	attributes	Updating bag from wire attributes:
  setting string attributes:
    destination.service.name -> 'details'
    destination.service.host -> 'details.default.svc.cluster.local'
    source.uid -> 'kubernetes://productpage-v1-8fcdcb496-nbv5b.default'
    context.protocol -> 'http'
    context.proxy_error_code -> 'FI'
    request.host -> 'details:9080'
    request.method -> 'GET'
    request.path -> '/details/0'
    source.namespace -> 'default'
    request.url_path -> '/details/0'
    request.scheme -> 'http'
    destination.service.uid -> 'istio://default/services/details'
    destination.service.namespace -> 'default'
    context.reporter.uid -> 'kubernetes://productpage-v1-8fcdcb496-nbv5b.default'
    context.reporter.kind -> 'outbound'
    request.useragent -> 'python-requests/2.20.0'
  setting int64 attributes:
    response.code -> '555'
    request.size -> '0'
    request.total_size -> '369'
    response.total_size -> '110'
    response.size -> '18'
  setting double attributes:
  setting bool attributes:
    connection.mtls -> 'false'
  setting timestamp attributes:
    response.time -> '2019-01-22 20:36:30.795301022 +0000 UTC'
    request.time -> '2019-01-22 20:36:30.79528693 +0000 UTC'
  setting duration attributes:
    response.duration -> '184.689µs'
  setting bytes attributes:
    origin.ip -> '[10 24 2 16]'
  setting string map attributes:
    request.headers -> 'stringmap[:method:GET x-request-id:dae93d3e-7c1b-475d-8db7-a45934ecbd71 user-agent:python-requests/2.20.0 x-b3-sampled:0 :authority:details:9080 x-b3-spanid:1a025c7eb9d2b788 accept:*/* x-b3-parentspanid:f3d39b82492faaf8 :path:/details/0 x-envoy-decorator-operation:details.default.svc.cluster.local:9080/* x-b3-traceid:cd8674b6405c4356f3d39b82492faaf8 x-forwarded-proto:http accept-encoding:gzip, deflate]'
    response.headers -> 'stringmap[server:envoy content-type:text/plain :status:555 date:Tue, 22 Jan 2019 20:36:30 GMT content-length:18]'
```

**Comment by douglas-reid** [comment]
So, I think the bag logic is faulty...

**Comment by jmazzitelli** [comment]
Let me ask this question - and I only bring it up because I came across a similar "weird telemetry" issue about the same time when I found this bug - is issue #11093 related to this one we are discussing? Notice mirrored traffic has wrong reporter="source" telemetry in that case, too (only this time the telemetry is actually missing).

**Comment by douglas-reid** [comment]
We have identified the issue as a protocol issue. We are attempting to determine when the semantics changed in the client so that we can assess the right approach to fix on server side.

**Comment by douglas-reid** [comment]
@jmazzitelli possibly. I haven't looked closely at that issue, but I would like to re-validate once this gets patched.

**Comment by mandarjog** [comment]
Mixer client (prior to 1.1-pre) uses batch compression protocol to compress multiple bags into a single report request sent to Mixer. The protocol *does not* support *deletions*.
When an attribute like `destination.uid` is not present in a bag, it incorrectly assumes value from the previous bag.

At present 1.1-pre snapshots (Post Oct 2018) , the client does not send batch compressed data. This change was made as part of a performance change in Mixer client.  1.1-pre mixer however treats incoming data as batch compressed.  This change also fixes the above problem. The proposed change
1. Updates API to signal if the `CompressedAttributes` are batch compressed or not
2. Update Serverside Mixer to forgo decompression logic if batch compression is not done.

We need this change to be present in 1.1 @geeknoid as the existing behaviour is broken.

**Comment by geeknoid** [comment]
What's the motivation to turn off batching completely?

The design intent was always to break up a batch on the client if deletion were necessary. This would seem to me as the lowest impact change, rather than messing with the wire-protocol and potentially introduce some upgrade challenges (when a V1.1 proxy sends stuff to a V1.0 Mixer during an upgrade cycle).

**Comment by douglas-reid** [comment]
@geeknoid the issues that may arise are that the ordering of the reporting could have a large impact on number of requests sent to Mixer and there may be a fair amount of additional logic that has to be added to detect and handle batch segregation client-side. If the compression logic was removed for perf reasons, we may end up regressing with the intro of new batch separation logic (and return to compression). 

I guess it comes down to a choice of where to dedicate resources for 1.1. My familiarity (and hence preference) would be to do that work server-side -- and leave the client (mostly) alone. But that definitely reflects my bias.

**Comment by douglas-reid** [comment]
@jmazzitelli OK. I think all the pieces are there to have fixed this issue. Do you mind helping to verify that they do what we think?  I'm gonna try testing it out now.

**Comment by douglas-reid** [comment]
@jmazzitelli with a test from tip using your supplied config, I see the following:

query: `istio_requests_total{response_code="555"}`

result:
```
istio_requests_total{connection_security_policy="unknown",destination_app="unknown",destination_principal="unknown",destination_service="details.default.svc.cluster.local",destination_service_name="details",destination_service_namespace="default",destination_version="unknown",destination_workload="unknown",destination_workload_namespace="unknown",instance="10.56.1.9:42422",job="istio-mesh",permissive_response_code="none",permissive_response_policyid="none",reporter="source",request_protocol="http",response_code="555",response_flags="FI",source_app="productpage",source_principal="unknown",source_version="v1",source_workload="productpage-v1",source_workload_namespace="default"}


```

**Comment by douglas-reid** [comment]
I'm going to mark this as closed. If you see it recur, please re-open.

**Comment by jmazzitelli** [comment]
@douglas-reid yes, I will confirm. I've been on vaca the past 2 weeks - I'll look at by next week.

**Comment by jmazzitelli** [comment]
Looks good running on Istio 1.1 Snapshot 6

![image](https://user-images.githubusercontent.com/2029470/52969318-e6f11a80-337d-11e9-8198-fa97a9bfe873.png)

**Comment by kcatstack** [comment]
> Got some attribute logs:
> 
> ```
> connection.mtls               : false
> context.protocol              : http
> context.proxy_error_code      : FI
> context.reporter.kind         : outbound
> context.reporter.uid          : kubernetes://productpage-v1-8fcdcb496-nbv5b.default
> destination.ip                : [10 24 0 12]
> destination.port              : 9080
> destination.service.host      : details.default.svc.cluster.local
> destination.service.name      : details
> destination.service.namespace : default
> destination.service.uid       : istio://default/services/details
> destination.uid               : kubernetes://reviews-v3-654d6f5b95-vtqgn.default
> origin.ip                     : [10 24 2 16]
> request.headers               : stringmap[x-request-id:5b995643-a3ef-4996-83d7-2659cbbee21b x-envoy-decorator-operation:details.default.svc.cluster.local:9080/* user-agent:python-requests/2.20.0 x-b3-spanid:39ffd4c3c711b48f :path:/details/0 accept-encoding:gzip, deflate :authority:details:9080 x-forwarded-proto:http x-b3-traceid:ece946731ed3b48919b804ac42e73b5a x-b3-parentspanid:19b804ac42e73b5a :method:GET x-b3-sampled:0 accept:*/*]
> request.host                  : details:9080
> request.method                : GET
> request.path                  : /details/0
> request.scheme                : http
> request.size                  : 0
> request.time                  : 2019-01-22 20:36:30.806570993 +0000 UTC
> request.total_size            : 369
> request.url_path              : /details/0
> request.useragent             : python-requests/2.20.0
> response.code                 : 555
> response.duration             : 124.908µs
> response.headers              : stringmap[content-length:18 server:envoy content-type:text/plain :status:555 date:Tue, 22 Jan 2019 20:36:30 GMT]
> response.size                 : 18
> response.time                 : 2019-01-22 20:36:30.806585048 +0000 UTC
> response.total_size           : 110
> source.namespace              : default
> source.uid                    : kubernetes://productpage-v1-8fcdcb496-nbv5b.default
> ---
> destination.container.name    : reviews
> destination.labels            : stringmap[app:reviews pod-template-hash:2108291651 version:v3]
> destination.name              : reviews-v3-654d6f5b95-vtqgn
> destination.namespace         : default
> destination.owner             : kubernetes://apis/apps/v1/namespaces/default/deployments/reviews-v3
> destination.serviceAccount    : default
> destination.workload.name     : reviews-v3
> destination.workload.namespace: default
> destination.workload.uid      : istio://default/workloads/reviews-v3
> source.ip                     : [0 0 0 0 0 0 0 0 0 0 255 255 10 24 2 16]
> source.labels                 : stringmap[app:productpage pod-template-hash:497876052 version:v1]
> source.name                   : productpage-v1-8fcdcb496-nbv5b
> source.owner                  : kubernetes://apis/apps/v1/namespaces/default/deployments/productpage-v1
> source.serviceAccount         : default
> source.workload.name          : productpage-v1
> source.workload.namespace     : default
> source.workload.uid           : istio://default/workloads/productpage-v1
> ```
> 
> Looks like `destination.uid` is wrong.

Might be a dumb question but @douglas-reid where do you view this log?
Also, my source.ip get some different encoding : `"source_ip"=>"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xFF\xFF\nA\x05\xA0"`
You might have any idea how can I extract value from this? Thanks

**Comment by douglas-reid** [comment]
@kcatstack you have to turn on debug logging for the right scopes in Mixer to see that log. I believe the scope is `api`, but it may be `attributes`.

the `source.ip` encoding issue was fixed. I don't know which release that fix was in, but it should be fixed.
