### ISSUE TITLE
Restore integration tests in codecov (disabled due to port conflict)

### ISSUE THREAD

**Issue by hklai** [istio/istio#11172]
The new integration tests and/or test framework seem to rely on a fixed port 9901 (see https://github.com/istio/istio/search?utf8=%E2%9C%93&q=9901&type=))

These tests had been disabled in the codecov job previously, but upon restoring these tests, codecov fails with errors like
`Error starting Galley: unable to listen: listen tcp 0.0.0.0:9901: bind: address already in use
`
See https://circleci.com/gh/istio/istio/300584

At first I thought it was due to parallelism (codecov runs per package tests in parallel), but disabling parallelism results in the same error.

The problem can be reproduced by removing https://github.com/istio/istio/blob/master/codecov.skip#L17

**Comment by duderino** [comment]
@ozevren @nmittler @gargnupur could one of you accept this and unassign the other owners?

**Comment by duderino** [comment]
nevermind.  thank you Oz

**Comment by ozevren** [comment]
This should be fixed now. Closing.
