### ISSUE TITLE
Envoy RDS doesn't update when Pilot restarts

### ISSUE THREAD

**Issue by christianang** [istio/istio#11170]
**Describe the bug**
When Pilot is restarted, any existing Envoy connected to Pilot will no longer receive their Route Configuration through RDS. Looking at Pilot logs it is still pushing EDS/CDS/LDS configuration to Envoy; so Envoy appears to have reconnected to Pilot, but there is an issue with how Pilot is handling RDS responses. Envoy must be restarted for Pilot to start pushing RDS again.

**Expected behavior**
I expect Pilot to continue pushing RDS to Envoy after Pilot is restarted without having to restart Envoy.

**Steps to reproduce the bug**
0. Setup a healthy environment with Pilot and Envoy communicating with each other. Envoy has configuration populated from Pilot.
1. Restart Pilot.
2. Push a new route to Pilot.
3. Observe Envoy doesn't populate the route configuration with the new route, but clusters and endpoints have been populated.

After some investigation, it appears that this is [the commit](https://github.com/istio/istio/commit/2ceb718fe) that breaks this functionality. When running through the above steps with the commit just before, Envoy does populate the route configuration after Pilot restarts.

It seems to me that [this code](https://github.com/istio/istio/blob/release-1.1/pilot/pkg/proxy/envoy/v2/ads.go#L480-L485) is causing the issue. What appears to be happening is Envoy will send a nonce that the Pilot doesn't know about, because it has been restarted. Can't say what the desired behavior should be though.

**Version**
Istio release-1.1 branch.

**Environment**
Cloud Foundry

@bruce-ricard and I

**Comment by christianang** [comment]
After some reading up on the XDS protocol and looking at what the code is doing. I think this would be solved by considering no sent nonce to be a case where it just accepts the `Discovery Request` from Envoy. Right now it would consider it to be a stale nonce because the nonce that was sent by Envoy doesn't match Pilot's "sent" nonce, which is blank.

It seems it would be as straight forward as doing an additional check here for that: https://github.com/istio/istio/blob/release-1.1/pilot/pkg/proxy/envoy/v2/ads.go#L480.

**Comment by hzxuzhonghu** [comment]
good catch
