### ISSUE TITLE
Pilot memory leak risk

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#11180]
There is a potential risk of memory leak in pilot.  

Because the `EndpointShardsByService` is a map keyyed by hostname. But there is no delete when service and its endpoint deleted

**Comment by hzxuzhonghu** [comment]
Both 1.0 and 1.1 have this problem.

**Comment by costinm** [comment]
Relatively easy/safe to fix when we do a full re-computation. Doesn't seem to be critical.

**Comment by howardjohn** [comment]
Fixed in #11183
