### ISSUE TITLE
debian files should use same name for build and release

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#1118]
right now we have:

https://storage.googleapis.com/istio-artifacts/auth/fd08656b83caa6f96fd11bb13a266bad04b468e1/artifacts/debs/istio-auth-node-agent.deb

for non release and we manually have

https://storage.googleapis.com/istio-release/releases/0.2.7/deb/istio-agent-release.deb

when we make a release

export AUTH_DEBIAN_URL="https://storage.googleapis.com/istio-artifacts/auth/c433a20e495ec312ef702a6950893af67c7ebe9c/artifacts/debs"

is in istio.VERSION

We need to align all those and use the same name at the end and use the version number instead of a sha inside istio.VERSION when we make a release
(and just switch the 'hub' equivalent - eg the prefix from istio-artifacts to istio-release)

**Comment by sebastienvas** [comment]
I propose to remove the dev one as you cannot have 2 targets with same name

**Comment by ldemailly** [comment]
can we have only 1 target but not add "-release" to it,
where it gets copied and if using a sha or a 0.x.y should be independent of the file name no ?

I forgot what the magic / issue was with the 2 target so I may be glossing over an important point

**Comment by kyessenov** [comment]
You can also move them to different directories to create two packages.

**Comment by mattdelco** [comment]
From looking at the rules the only difference I see is that the dev pkg_deb uses:
   version = "0.3-dev",
while the -release uses:
   tags = ["manual"],
   version_file = "version",

I know hardly anything about bazel (or istio for that matter) so I'm not clear on the tag option, but offhand the best approach I can come up with for version is to add a rule like the following to istio/BUILD:

genrule(
    name = "deb_version",
    srcs = [],
    outs = ["deb_version.txt"],
    cmd = "echo $${ISTIO_VERSION:-\"0.3.0-dev\"} > \"$@\"",
    visibility = ["//visibility:public"],
)

then replace the contents of the non-release pkg_deb() rules to be the same as -release (and delete the -release rules) and then change the version_file line to:
   version_file = "//:deb_version",

Bazel apparently requires opt-in on environment variables so the various push-debian.sh scripts would change from:

if [[ -n "${ISTIO_VERSION}" ]]; then
  BAZEL_TARGET+='-release'
  BAZEL_BINARY+='-release'
  echo "${ISTIO_VERSION}" > "${VERSION_FILE}"
  trap 'rm "${VERSION_FILE}"' EXIT
fi

to

if [[ -n "${ISTIO_VERSION}" ]]; then
  BAZEL_ARGS+=("--action_env=ISTIO_VERSION")
fi

does that seem reasonable?  I figure the most subjective thing is where to stick the deb_version rule and what to call it.

**Comment by mattdelco** [comment]
Behavior was addressed in:
https://github.com/istio/istio/pull/1972
https://github.com/istio/proxy/pull/704
