### ISSUE TITLE
pilot-agent processes Envoy bootstrap template passed via templateFile differently than the default one

### ISSUE THREAD

**Issue by alexburnos** [istio/istio#11198]
**Describe the bug**
When templateFile is provided to the pilot-agent, it does some processing and writes out a custom config file for Envoy (https://github.com/istio/istio/blob/247e36f89c4fc08433cd67c54cb19dd3f98a09fc/pilot/cmd/pilot-agent/main.go#L268).

This effectively stops further processing of the template by bootstrap_config module and customConfigFile is being treated "as is". Which is inconsistent with how standard default envoy bootstrap template is being processed.

**Expected behavior**
Envoy bootstrap templateFile passed as an argument to pilot-agent should be handled exactly the same as default bootstrap template, effectively substituting the default template.

**Steps to reproduce the bug**
Pass default Envoy boostrap template as an argument of --templateFile to see that substitution of many parameters will not happen and resulting Envoy config will be stored under different name than config generated from the default template (/etc/istio/proxy/envoy.yaml vs /etc/proxy/proxy/envoy-rev0.yaml)

**Version**
Istio current / 1.0.5

**Installation**
Via helm

**Environment**
GCP

**Comment by kyessenov** [comment]
FYI this flag was added to support internal istio sidecars (pilot and mixer envoy sidecars).
I agree that the app-specific template and control-plane specific templates should in theory be merged but they serve different purpose.

**Comment by alexburnos** [comment]
As a simple, non-intrusive workaround, proposing PR #11211. Whether we want to implement more scaleable solution - I'll leave to Istio maintainers to comment.

**Comment by costinm** [comment]
I don't see any reason mixer sidecar wouldn't work if full template is supported - or needs a special case in agent. Pilot sidecar is on its way out, galley is not using a sidecar either. 

Let's not add more complexity and ifs...

**Comment by kyessenov** [comment]
@alexburnos The internal envoy does not use pilot. So there's a significant difference between bootstraps. It only needs certificates (using file rotation or SDS), and also wires telemetry differently for telemetry sidecar. I wouldn't worry about merging the internal bootstrap with the app bootstrap, and leave the internal one as a special case. There are plans to replace it with direct gRPC library, but that's not ready yet.
