### ISSUE TITLE
Mesh networks config modifications don't propagate

### ISSUE THREAD

**Issue by ymesika** [istio/istio#11221]
Having a setup of Multi-cluster with Mesh networks configured in the Istio config map.
Modify the address/port of the network gateway within the deployed config map and examine updated pushed EDS configuration in one of sidecars.

While Pilot's log shows that the changes were detected and configmap reloaded, the initial network gateway values are still being pushed while expecting the new values to take affect.

Workaround: Kill the pilot pod after modifying the configmap.

**Comment by jasminejaksic** [comment]
What's still pending? Can we close this?
