### ISSUE TITLE
Tracing issue | spans are not correlated as expected

### ISSUE THREAD

**Issue by jacob-koren-zooz** [istio/istio#11233]
**Describe the bug**
Spans in a trace are not correlated as expected

**Expected behavior**
We installed istio 1.0.5 on k8s cluster with tracing enabled, and deployed the bookInfo example from the samples folder. 
We exposed "productpage" service on the ingress-gw and made requests.
On jaeger UI we see the following hierarchy: 
![image](https://user-images.githubusercontent.com/16208244/51695354-89caa900-200b-11e9-8f0e-47b5d90cd0e4.png)

This contradicts the documentation around the bookInfo sample. 

![image](https://user-images.githubusercontent.com/16208244/51696165-78829c00-200d-11e9-8163-2a3d6a6beaa0.png)
 
Also with our own services we see a similar situation. Only if we set the parent-spanID to be the last spanID, and generating new spanID we see the expected context. But then again, docs are saying that we should only propagate.

**Version**
**istioctl version**
Version: 1.0.5
GitRevision: c1707e45e71c75d74bf3a5dec8c7086f32f32fad
User: root@6f6ea1061f2b
Hub: docker.io/istio
GolangVersion: go1.10.4
BuildStatus: Clean
**kubectl version:**
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T17:05:32Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-eks-6bad6d", GitCommit:"6bad6d9c768dc0864dab48a11653aa53b5a47043", GitTreeState:"clean", BuildDate:"2018-12-06T23:13:14Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**Installation**
helm install install/kubernetes/helm/istio --name istio --namespace istio-system --set global.configValidation=false --set tracing.enabled=true --set sidecarInjectorWebhook.enabled=false --set grafana.enabled=true --set servicegraph.enabled=true

**Comment by objectiser** [comment]
I don't think it can be done currently through configuration - hence my PR to try to get it disabled by default. If that PR is accepted, we can look at getting it applied to the 1.0 branch.

Are you able to build the master version, or the 1.0 branch, with the same fix from #11232 to see if it fixes your problem?

**Comment by objectiser** [comment]
Actually, just checked the 1.0.5 distribution, and found `./tools/deb/envoy_bootstrap_v2.json` - so might be possible to manually add the `trace_id_128bit` and `shared_span_context` values. However I will need to check and see whether the `shared_span_context` flag is supported in the envoy proxy version used by 1.0.5.

I'll give it a try tomorrow - but feel free to try it out and let me know.

**Comment by objectiser** [comment]
Unfortunately the `shared_span_context` is not supported in the version of envoy being used in `1.0.5`.

**Comment by douglas-reid** [comment]
Closing, as I believe this was resolved in 1.1.
