### ISSUE TITLE
Istio value defaults should be performant

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#11247]
Many potential istio users test istio with default configuration for performance.

The default configuration must have a reasonable performance.
1. request enough cpu for control plane
2. disable access logs on Mixer
3. disable access logging on istio-proxy
4. perhaps disable istio-policy ?

**Comment by mandarjog** [comment]
cc @jnativio @suryadu

**Comment by duderino** [comment]
Related to https://github.com/istio/istio/issues/11280 and https://github.com/istio/istio/issues/8938

**Comment by duderino** [comment]
@knrc please review

**Comment by duderino** [comment]
See also https://github.com/istio/istio/issues/11736 which will be done as part of this

**Comment by duderino** [comment]
See also https://github.com/istio/istio/issues/11964 which will fix the demo config broken by these changes

**Comment by mandarjog** [comment]
Closing since https://github.com/istio/istio/pull/12114 is merged.

**Comment by duderino** [comment]
yay
