### ISSUE TITLE
Allow Root CA and Citadel on same cluster

### ISSUE THREAD

**Issue by esnible** [istio/istio#11241]
In Multimesh Istio it is not possible to run the Root CA and regular Citadel in the same cluster.

This is because _/usr/local/bin/istio_ca_ always watches and attempts to create secrets for ServiceAccounts.  If the Root CA and Citadel are both attempting to create and renew secrets then there will be a race.  Only the non-Root CA should renew secrets.

I propose the Citadel image should not call controller.NewSecretController() if it is acting as root CA.  Citadel is acting as root CA if started with arguments similar to `--self-signed-ca=true --self-signed-ca-org=test-org --self-signed-ca-cert-ttl=2400h --sign-ca-certs=true`

**Comment by sdake** [comment]
@esnible - can you share your workflow for creating intermediate certificates?  My understanding is that an operator creates root certificates - then generates intermediate certificates- then registers via --self-signed=false in all cases.  There is no need for a "root ca" - instead the root CA is simply the certificate that is used to create new intermediate certificates for new clusters.

Is this incorrect?  (I haven't explored this aspect of multimesh, but would like to hear what you have to say on the topic).

Cheers
-steve

**Comment by elevran** [comment]
@sdake the use case above works with long lived certificates. Long lived certificates could be a security risk. It may be preferred to run Citadel with certificates that are short and renewed, much as done for sidecar proxies. I believe @snible is trying to run with Citadel's using short term certificates. We would require a way to renew certificates periodically.
