### ISSUE TITLE
istio 1.1 Egress / Ingress gateway use excessive memory

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#11254]
version: release-1.1-20190123-09-16
In a large setup (400 services) with no egress configuration defined, egress proxy uses `200MB` memory.

```
istio-egressgateway-68bf7d65cc-2xprb      istio-proxy                18m          193Mi
istio-egressgateway-68bf7d65cc-9mqhr      istio-proxy                17m          200Mi
istio-egressgateway-68bf7d65cc-9w9z2      istio-proxy                17m          217Mi
istio-egressgateway-68bf7d65cc-bsw9t      istio-proxy                20m          189Mi
istio-egressgateway-68bf7d65cc-gz84j      istio-proxy                22m          191Mi
istio-ilbgateway-79c88598c8-zfdtr         istio-proxy                14m          120Mi
istio-ingressgateway-5f858dd48c-2dbmj     istio-proxy                1280m        223Mi
istio-ingressgateway-5f858dd48c-cs94j     istio-proxy                31m          214Mi
istio-ingressgateway-5f858dd48c-qkh54     istio-proxy                1206m        221Mi
```
The configuration at egress gateway contained only 1 listener, (2 static routes) and 1077 clusters.
When nothing is bound to the egressgateway, it should use minimal memory.

As seen from the `kubectl top` report, ingressgateway faces the same issue.

**Comment by mandarjog** [comment]
cc @louiscryan @rshriram @costinm

**Comment by kyessenov** [comment]
Envoy requests CDS in aggregate. This is probably an issue in pilot to filter clusters by use.

**Comment by mandarjog** [comment]
I don’t think pilot is filtering any clusters.

**Comment by rshriram** [comment]
You need to apply the Sidecar config to filter the clusters that the gateway is supposed to see. Secondly, not sure if you are using the bootstrap template that @douglas-reid wrote that drops cluster level stats to cut down memory

**Comment by mandarjog** [comment]
@rshriram This is a build from a few days ago. It *does* include the stats exclusion. Doesn't gateway implicitly know what clusters it needs?  However if  `sidecar` is the only way to get there it is probably ok.

**Comment by rshriram** [comment]
Sorry this wont work for gateways. And no gateway doesn't know what clusters it needs unless you process the entire set of virtual services to compute CDS output. Currently, we share the CDS out with every proxy in the system. However, with the introduction of global flags for export, you should be able to constrain the set of services that the gateway would see.

**Comment by munrodg** [comment]
@mandarjog Does anything need to be done for this in 1.1?
