### ISSUE TITLE
Sidecar should support configure the number of worker threads to run

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#11268]
We guys from Huawei have tested how the [--concurrency](https://www.envoyproxy.io/docs/envoy/latest/operations/cli.html?highlight=concurrency#cmdoption-concurrency) flag influence Envoy performance.

And the result shows that when we configure concurrency the number of cpu cores, it supports the maximum qps and takes up less cpu.

>--concurrency <integer> The number of worker threads to run. If not specified defaults to the number of hardware threads on the machine.

But as we know Envoy in a container can see all cores in host  machine https://github.com/moby/moby/issues/20770

So one thought come to mind is we can infer the number of cores from container cpu request, and pass this value to sidecar, so that pilot-agent can start envoy with this legitimate value.

**Comment by ymesika** [comment]
According to the internal doc by default the concurrency value is 0 and in this case it will use the number of cores on the machine.
How is it different from what you suggest?

**Comment by hzxuzhonghu** [comment]
But as we know Envoy in a container can see all cores in host machine moby/moby#20770

This value is not accurate in a docker container.

**Comment by wenchenglu** [comment]
@mandarjog should this be marked for 1.1. Sounds a reasonable change to go into 1.1 for performance improvement.

@duderino fyi

**Comment by hzxuzhonghu** [comment]
Thanks @wenchenglu

**Comment by knrc** [comment]
FYI this was already under discussion through https://github.com/istio/istio/issues/8938, already in the 1.1 bucket
