### ISSUE TITLE
mixer: enforce type discipline for attribute values cause panic Unknown map type [] 

### ISSUE THREAD

**Issue by piaoyu** [istio/istio#11260]
**Describe the bug**
```
mixer: enforce type discipline for attribute values cause panic Unknown map type [] 
```
#10260

**Expected behavior**
panic: Unknown map type []uint8
goroutine 2342 [running]:
istio.io/istio/mixer/pkg/il.MapGet(0x1a9c220, 0xc420dbf720, 0xc421aadad7, 0x7, 0xc420dbf720, 0x1, 0xc4227c3800)
	/home/root/gopath/src/istio.io/istio/mixer/pkg/il/types.go:99 +0x149
istio.io/istio/mixer/pkg/il/interpreter.(*Interpreter).run(0xc421b2ac20, 0xc420d52810, 0x20a33e0, 0xc420dbea20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/root/gopath/src/istio.io/istio/mixer/pkg/il/interpreter/interpreterRun.go:1036 +0x47a7
istio.io/istio/mixer/pkg/il/interpreter.(*Interpreter).EvalFnID(0xc421b2ac20, 0x102, 0x20a33e0, 0xc420dbea20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/root/gopath/src/istio.io/istio/mixer/pkg/il/interpreter/interpreter.go:77 +0xd4
istio.io/istio/mixer/pkg/lang/compiled.expression.Evaluate(0xc421b2ac20, 0xc400000102, 0x20a33e0, 0xc420dbea20, 0xc420d52270, 0x2df8ad0, 0xc421bf9680, 0xc4228d4ec8)
	/home/root/gopath/src/istio.io/istio/mixer/pkg/lang/compiled/expressionbuilder.go:68 +0x80
istio.io/istio/mixer/template.(*builder_metric_Template).build(0xc420d52120, 0x20a33e0, 0xc420dbea20, 0xc4228d4f01, 0x0, 0x0, 0xc421aa8120, 0xaf2743ede3de6a12)
	/home/root/gopath/src/istio.io/istio/mixer/template/template.gen.go:4314 +0x184
istio.io/istio/mixer/template.glob..func54.2(0x20a33e0, 0xc420dbea20, 0xc420dbea20, 0xc421aa8101, 0xc420bdfe60, 0x1e88bf7)
	/home/root/gopath/src/istio.io/istio/mixer/template/template.gen.go:1824 +0x54
**Steps to reproduce the bug**
{{ Minimal steps to reproduce the behavior }}

**Version**
```
#istioctl version
Version: c0b32ff8af87909b3b5b0f75a921a53a142ddf5a-dirty
GitRevision: c0b32ff8af87909b3b5b0f75a921a53a142ddf5a-dirty
```
```
#kubectl version
Client Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.3-dirty-20180614", GitCommit:"c5cea03d940024108c9fe2a780080e6ef4011383", GitTreeState:"dirty", BuildDate:"2018-06-21T18:36:34Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.6-dirty-20181227", GitCommit:"8d05e39f557f7bac1816d80f5f79e6e5c0ca3e8e", GitTreeState:"dirty", BuildDate:"2019-01-15T10:59:40Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Installation**
```
helm 
```

**Environment**
```
#uname -r
3.10.0-327.ali2010.7.x86_64
```

**Comment by kyessenov** [comment]
Can you provide more context? Which attribute is causing this and what
value is used? Looks like an array of IP addresses.

**Comment by piaoyu** [comment]
```
2019-01-25T03:40:03.790533Z	error	evaluation failed at [accesslog.logentry.istio-system]'Variables[sourceName]': 'error converting value to string: '[49 50 55 46 48 46 48 46 49]''
2019-01-25T03:40:03.790576Z	error	error creating instance: destination='logentry:stdio.istio-system(stdio)', error='evaluation failed at [accesslog.logentry.istio-system]'Variables[sourceName]': 'error converting value to string: '[49 50 55 46 48 46 48 46 49]'''
2019-01-25T03:40:03.790842Z	error	api	Report failed:1 error occurred:

* evaluation failed at [accesslog.logentry.istio-system]'Variables[sourceName]': 'error converting value to string: '[49 50 55 46 48 46 48 46 49]''
{"level":"info","time":"2019-01-25T03:40:04.581809Z","instance":"accesslog.logentry.istio-system","apiClaims":"","apiKey":"","clientTraceId":"","connection_security_policy":"none","destinationApp":"","destinationIp":10000,"destinationName":"unknown","destinationNamespace":"default","destinationOwner":"unknown","destinationPrincipal":"","destinationServiceHost":"source.port","destinationWorkload":"unknown","grpcMessage":"","grpcStatus":"","httpAuthority":"","latency":"13.060272ms","method":"","permissiveResponseCode":"none","permissiveResponsePolicyID":"none","protocol":"http","receivedBytes":228,"referer":"","reporter":"destination","requestId":"","requestSize":0,"requestedServerName":"","responseCode":200,"responseSize":17,"responseTimestamp":"2019-01-25T03:40:04.581815Z","sentBytes":365,"sourceApp":"","sourceIp":"AAAAAAAAAAAAAP//AAAAAA==","sourceName":"unknown","sourceNamespace":"source.labels","sourceOwner":"unknown","sourcePrincipal":"","sourceWorkload":"unknown","url":"","userAgent":"","xForwardedFor":"0.0.0.0"}
{"level":"info","time":"2019-01-25T03:40:03.791174Z","instance":"accesslog.logentry.istio-system","apiClaims":"","apiKey":"","clientTraceId":"","connection_security_policy":"none","destinationApp":"telemetry","destinationIp":"AAAAAAAAAAAAAP//rBEAJA==","destinationName":"istio-telemetry-66ff969d49-cvhbc","destinationNamespace":"istio-system","destinationOwner":"kubernetes://apis/extensions/v1beta1/namespaces/istio-system/deployments/istio-telemetry","destinationPrincipal":"","destinationServiceHost":"istio-telemetry.istio-system.svc.cluster.local","destinationWorkload":"istio-telemetry","grpcMessage":"1 error occurred:%0A%0A* evaluation failed at [accesslog.logentry.istio-system]'Variables[sourceName]': 'error converting value to string: '[49 50 55 46 48 46 48 46 49]''","grpcStatus":"2","httpAuthority":"172.17.0.36:9091","latency":"1.705086ms","method":"POST","permissiveResponseCode":"none","permissiveResponsePolicyID":"none","protocol":"http","receivedBytes":548,"referer":"","reporter":"destination","requestId":"726c0bd3-ff15-4574-b467-65ba3f29121a","requestSize":316,"requestedServerName":"","responseCode":200,"responseSize":0,"responseTimestamp":"2019-01-25T03:40:03.791200Z","sentBytes":306,"sourceApp":"","sourceIp":"AAAAAAAAAAAAAP//AAAAAA==","sourceName":"unknown","sourceNamespace":"default","sourceOwner":"unknown","sourcePrincipal":"","sourceWorkload":"unknown","url":"/istio.mixer.v1.Mixer/Report","userAgent":"grpc-go/1.17.0","xForwardedFor":"0.0.0.0"}
```

**Comment by kyessenov** [comment]
The first error seems to be caused by:
`sourceName: source.name | ""`
with `source.name = []uint8{49 50 55 46 48 46 48 46 49}`. This is string "127.0.0.1" in bytes.

The second error seems to be caused by `[]uint8` placed into a string map attribute. Since this is accesslog, there is only `source.labels` and `destination.labels` there.

**Comment by kyessenov** [comment]
I believe there is leakage between attribute values. An IP address is assigned to `source.name` and either `source.labels` or `destination.labels`. Looking further...

**Comment by kyessenov** [comment]
@piaoyu Can you give more details if you made change to istio config? Is this a default install? Does this happen randomly?

**Comment by kyessenov** [comment]
@piaoyu We need steps to reproduce this bug. Please provide more details on version/config you used.

**Comment by piaoyu** [comment]
It seem like  config error .  I close the issues first
