### ISSUE TITLE
Mixer Report failed with: UNAVAILABLE:upstream request timeout

### ISSUE THREAD

**Issue by rajdhandus** [istio/istio#11273]
**Describe the bug**
We are seeing the below message in our logs... its happening very frequently.. almost every second..

[libprotobuf ERROR src/istio/mixerclient/report_batch.cc:83] Mixer Report failed with: UNAVAILABLE:upstream request timeout
[libprotobuf ERROR src/istio/mixerclient/report_batch.cc:83] Mixer Report failed with: UNAVAILABLE:upstream request timeout

**Expected behavior**
No such entry should be in the logs..

**Steps to reproduce the bug**
No known steps to reproduce. The error started appearing all of a sudden. Not able to correlated with any changes to the environment.

**Version**

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T10:09:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.11-gke.1", GitCommit:"5c4fddf874319c9825581cc9ab1d0f0cf51e1dc9", GitTreeState:"clean", BuildDate:"2018-11-30T16:18:58Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}

Version: 1.0.0
GitRevision: 3a136c90ec5e308f236e0d7ebb5c4c5e405217f4
User: root@71a9470ea93c
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean

**Installation**
{{ Please describe how Istio was installed }}

**Environment**
GCP

**Comment by douglas-reid** [comment]
Are you still seeing information you expect (metrics, logs, etc.) ?  What is the status of your `istio-telemetry` pods?

**Comment by kamboyer** [comment]
Hey Doug, appreciate your curiosity. 
We haven't lost any metric or log information.
We've bounced istio-telemtry which no affect. We're in the midst of switching mixer to debug logging.

We've been able to pin point the exact time this started to occur, but have failed to correlate any change to the environment any other event which would seem to relate.

**Comment by douglas-reid** [comment]
@mandarjog @kyessenov @qiwzhang any ideas here?

**Comment by mandarjog** [comment]
`istio-telemetry` was overloaded/slow and did not respond in time.  How much traffic are you sending, is mixer overloaded ?

**Comment by douglas-reid** [comment]
Do you have the logs from the mixer container of `istio-telemetry` for that same time period, by chance?

**Comment by douglas-reid** [comment]
The same behavior has similarly been reported here: https://discuss.istio.io/t/istio-mixer-error/498/3. There it is also claimed that there is no impact on telemetry reported through Mixer.

**Comment by ajayakumar1983** [comment]
@douglas-reid here is the logs from Mixer container on telemetry .

I  {"level":"info","receivedBytes":347,"destinationServiceHost":"istio-telemetry.istio-system.svc.cluster.local","instance":"accesslog.logentry.istio-system","destinationNamespace":"default","destinationApp":"","destinationPrincipal":"","sentBytes":110,"sourceApp":"istio-ingressgateway","sourceNamespac… 
I  {"sourceIp":"10.0.2.68","requestId":"95809d1a-697c-95f6-8ad6-f4172d2376ff","sourceWorkload":"istio-ingressgateway","clientTraceId":"","reporter":"destination","destinationIp":"10.0.1.93","httpAuthority":"mixer","apiClaims":"","latency":"4.999562252s","level":"info","receivedBytes":1285,"destinationN… 
I  {"connection_security_policy":"unknown","apiKey":"","responseSize":18,"protocol":"http","requestSize":0,"sourceName":"istio-ingressgateway-54986f4cdf-6lm6k","destinationWorkload":"unknown","sourceIp":"10.0.1.91","requestId":"cbbb5987-0887-4405-8e97-58d6106676cb","sourceWorkload":"istio-ingressgatewa… 
I  {"apiKey":"","requestSize":817,"protocol":"https","responseSize":0,"sourceName":"istio-ingressgateway-54986f4cdf-6lm6k","destinationWorkload":"istio-telemetry","sourceIp":"10.0.1.91","requestId":"64f9e888-98d7-9842-9edc-e87d38e92233","sourceWorkload":"istio-ingressgateway","clientTraceId":"","report… 
I  2019-01-30T15:29:04.851903Z	debug	adapters	Nothing to send this tick	{"adapter": "handler.stackdriver.istio-system"}
 
I  istio.io/istio/pkg/log.(*Scope).emit
 
I  	/workspace/go/src/istio.io/istio/pkg/log/scope.go:251
 
I  istio.io/istio/pkg/log.(*Scope).Debug
 
I  	/workspace/go/src/istio.io/istio/pkg/log/scope.go:199
 
I  istio.io/istio/mixer/pkg/runtime/handler.logger.Debugf
 
I  	/workspace/go/src/istio.io/istio/mixer/pkg/runtime/handler/logger.go:66
 
I  istio.io/istio/mixer/adapter/stackdriver/contextgraph.(*handler).send
 
I  	/workspace/go/src/istio.io/istio/mixer/adapter/stackdriver/contextgraph/send.go:89
 
I  istio.io/istio/mixer/adapter/stackdriver/contextgraph.(*handler).cacheAndSend
 
I  	/workspace/go/src/istio.io/istio/mixer/adapter/stackdriver/contextgraph/send.go:50
 
I  istio.io/istio/mixer/adapter/stackdriver/contextgraph.(*builder).Build.func1
 
I  	/workspace/go/src/istio.io/istio/mixer/adapter/stackdriver/contextgraph/contextgraph.go:100
 
I  istio.io/istio/mixer/pkg/runtime/handler.env.ScheduleDaemon.func1
 
I  	/workspace/go/src/istio.io/istio/mixer/pkg/runtime/handler/env.go:93
 
I  2019-01-30T15:29:04.905852Z	debug	adapters	Successfully sent data to Stackdriver.	{"adapter": "handler.stackdriver.istio-system"}
 
I  istio.io/istio/pkg/log.(*Scope).emit
 
I  	/workspace/go/src/istio.io/istio/pkg/log/scope.go:251
 
I  istio.io/istio/pkg/log.(*Scope).Debug
 
I  	/workspace/go/src/istio.io/istio/pkg/log/scope.go:199
 
I  istio.io/istio/mixer/pkg/runtime/handler.logger.Debugf
 
I  	/workspace/go/src/istio.io/istio/mixer/pkg/runtime/handler/logger.go:66
 
I  istio.io/istio/mixer/adapter/stackdriver/metric.(*buffered).Send
 
I  	/workspace/go/src/istio.io/istio/mixer/adapter/stackdriver/metric/bufferedClient.go:104
 
I  istio.io/istio/mixer/adapter/stackdriver/metric.(*buffered).start.func1
 
I  	/workspace/go/src/istio.io/istio/mixer/adapter/stackdriver/metric/bufferedClient.go:65
 
I  istio.io/istio/mixer/pkg/runtime/handler.env.ScheduleDaemon.func1
 
I  	/workspace/go/src/istio.io/istio/mixer/pkg/runtime/handler/env.go:93

**Comment by kamboyer** [comment]
Thus far, we’ve observed a relationship of this error and DestinationRules...this has yet to be confirmed technically...but observed

**Comment by adityats2020** [comment]
I have observed this error when I enabled Mutual TLS manually. I had to update `controlPlaneAuthPolicy` after I updated `TLS.Mode` in `DestinationRule`.

**Comment by liguobao** [comment]
that will make rate-limit not work?

**Comment by douglas-reid** [comment]
@liguobao this is about mixer REPORT, which is strictly for telemetry collection (not policy enforcement).

**Comment by douglas-reid** [comment]
With 1.0 support ending, and a lack of next steps in hunting down this issue, I think that the only action left, unfortunately, is to close this issue. Please re-open if you feel that there is more that should be done here.

**Comment by fduarte3** [comment]
Any news on this issue?
I had same error with 1.0, now I've just upgraded to 1,1 and still facing this issue.
