### ISSUE TITLE
Helm chart not exposing all necessary ports in istio-pilot service

### ISSUE THREAD

**Issue by johngmyers** [istio/istio#11284]
**Describe the bug**
The "istio-pilot" Service in the "pilot" Helm subchart does not expose all necessary ports.

**Expected behavior**
Per operations guide, running `curl http://istio-pilot:15003/v1/registration` from within an istio-ingressgateway pod should return a response. It instead gets a connection timeout.

**Steps to reproduce the bug**
Install Istio using Helm into a Kubernetes cluster with a network model that does not forward service ports that are not declared in the service resource definition.

**Version**
Istio 1.0.5
Kubernetes 1.10.12 with Weave CNI

**Installation**
Helm

**Environment**
AWS

**Cluster state**
[istio-dump.tar.gz](https://github.com/istio/istio/files/2798002/istio-dump.tar.gz)

**Comment by johngmyers** [comment]
Manually adding port 15003 to the "istio-pilot" Service in the "istio-system" namespace causes the curl command to return a response.

**Comment by johngmyers** [comment]
@GregHanson Port 15003 is what is documented at https://istio.io/help/ops/misc/ . If that port is no longer supported, then the documentation should be corrected.

**Comment by GregHanson** [comment]
@johngmyers sorry for closing prematurely, appears to be a few possible docs issues in this one.
- /v1/registration API is remnant of envoy V1 XDS API's so the V2 debug API's should be used instead: 
https://github.com/istio/istio/blob/master/pilot/pkg/proxy/envoy/v2/debug.go#L54
- 15003 port is deprecated so it should not be in the docs

**Comment by johngmyers** [comment]
Another issue is that if global.controlPlaneSecurityEnabled is true, various things are configured to talk to istio-pilot:15005. Port 15005 is not exposed by the istio-pilot Service.

**Comment by GregHanson** [comment]
@costinm I see you added the `global.controlPlaneSecurityEnabled` value in this PR here:
https://github.com/istio/istio/pull/3949/files#diff-7dad29cba9d2ca3e8570c8f65f4b7e86

is the istio-pilot:15005 port still used for this and should it be exposed in the helm charts?
