### ISSUE TITLE
Helm chart : User specified namespace + Grafana with persistency enabled => rendered PVC lacking namespace declaration

### ISSUE THREAD

**Issue by jfaixo** [istio/istio#11303]
**Describe the bug**
When using the Helm chart with a user specified namespace and the Grafana persistency enabled, the generated PersistentVolumeClaim does not have the namespace declaration, leading in Grafana to be stuck in the Pending state.

**Expected behavior**
Everything to start up and running well 😸 

**Steps to reproduce the bug**
Render the helm chart and try to deploy it :
`helm template install/kubernetes/helm/istio --name istio --namespace istio-system --set grafana.enabled=true --set grafana.persist=true`

**Version**
Istio 1.0.5release from github

Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-12-06T01:33:57Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-eks-6bad6d", GitCommit:"6bad6d9c768dc0864dab48a11653aa53b5a47043", GitTreeState:"clean", BuildDate:"2018-12-06T23:13:14Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**Installation**
Rendering the chart through `helm template` and applying it `kubectl apply -f -`

**Environment**
AWS EKS cluster

**Cluster state**
[istio-dump.tar.gz](https://github.com/istio/istio/files/2799891/istio-dump.tar.gz)

**Comment by jfaixo** [comment]
I am in the process of making a PR to correct this.

**Comment by munrodg** [comment]
@douglas-reid to review so confirm this can be merged into 1.1

**Comment by douglas-reid** [comment]
Merged. Marking as Fixed.

**Comment by Kansuler** [comment]
Thanks! Just came across this problem
