### ISSUE TITLE
Istio injection is not working for modified Deployments.

### ISSUE THREAD

**Issue by emaildanwilson** [istio/istio#1130]
With istio injection running with a setting of `disabled` I'm experiencing an issue where Deployments which are modified to contain `annotations:
    sidecar.istio.io/inject: "true"` do not get injected with envoy. If they are deleted and recreated then the injection works.

The log shows `I1013 20:53:45.569177       1 initializer.go:202] ObjectMeta initializer info extensions/v1beta1, Kind=ReplicaSet central-architecture/mydeployment-62
8804509 policy:"true" status:"" nil`

Is this expected?

**Comment by ayj** [comment]
Issue moved to [istio/pilot #1477](https://github.com/istio/pilot/issues/1477) via [**ZenHub**](https://www.zenhub.com/)

**Comment by ayj** [comment]
Are you modifying the `sidecar.istio.io/inject` annotation _after_ the deployment is created? k8s initializers only run when deployments are created.
