### ISSUE TITLE
Make istio-remote an Istio Helm values installation

### ISSUE THREAD

**Issue by ymesika** [istio/istio#11306]
Currently `istio-remote` (for VPN connectivity and Split Horizon EDS) is a separated Helm chart/release.
We can achieve the same goal with having another values within the Istio chart tailored for the remote clusters installations.

What we gain:
* Better user experience
* Simpler and less confusing docs
* Easier to maintain and avoids (templates) duplications
* Get rid of the need to create the charts packages (`helm dep update`) by moving the subcharts back to the Istio release

We can remove the `istio-remote` chart and move subcharts back to `istio` __or__ we can keep the `istio-remote` and mark it _deprecated_. Current PR removes it.

**Comment by ymesika** [comment]
Docs updated by https://github.com/istio/istio.io/pull/3144

**Comment by linsun** [comment]
per @ymesika MC istio-remote chart is currently broken as it is missing some of the latest update from istio chart, thus it is critical for us to get this fixes in 1.1

cc @wenchenglu @duderino

**Comment by sdake** [comment]
Pending PR: https://github.com/istio/istio/pull/11307

**Comment by rvennam** [comment]
@ymesika when this is done, please update the `Setup the remote cluster` section in https://preliminary.istio.io/docs/examples/multicluster/split-horizon-eds/  It currently references the `istio-remote` folder
