### ISSUE TITLE
Multimesh SHOULD NOT require a name ending in .global

### ISSUE THREAD

**Issue by esnible** [istio/istio#11324]
When Istio is configured for multi-mesh it should be possible for unchanged applications to invoke webservices and be unaware if the service is local.

Yet in the current implementation, I have success with curl ratings.default.global but not with curl ratings.default. Even though the client has been configured with DNS and resolves both addresses to the same value.

To get the client configuration out of the picture I reproduced the problem without a client. After obtaining certs and setting $IIP to the Ingress public IP, from my laptop I perform

curl https://outbound_.9080_._.reviews.default.global:15443/reviews/0 --resolve "outbound_.9080_._.reviews.default.global:15443:$IIP" --key /tmp/key.pem --cert /tmp/cert-chain.pem --insecure
``` and it works, but any other name fails.  Even `outbound_.9080_._.reviews.default.svc.cluster.local` fails, and that is the cluster name that the Envoy rewrite creates.

At the Ingress there is a `filter_chain_match` for `*.global`.  If we need this match then we must ensure that the outbound Envoy applies `.global` to the server name.  If the outbound Envoy does not make the name follow a well-known pattern then the Ingress will need a more flexible server_names value with many aliases resembling the `domains` key with values like reviews.default.svc.cluster.local, reviews.default.svc.cluster, reviews.default.svc, etc.

**Version**
release-1.1 daily builds

**Comment by ymesika** [comment]
> Yet in the current implementation, I have success with curl ratings.default.global but not with curl ratings.default. Even though the client has been configured with DNS and resolves both addresses to the same value.

I believe #10972 is targeting the issue implied by this sentence.

**Comment by dwradcliffe** [comment]
I got this working by adding a custom rewrite on the destination cluster to map a custom domain back to the expected cluster name. It does require significant orchestration to get the rewrite filters in place though.

**Comment by howardjohn** [comment]
@sdake was this fixed in https://github.com/istio/istio/pull/11522 and https://github.com/istio/istio/pull/11512 or is there more work to be done?

**Comment by howardjohn** [comment]
Presumed fixed and abandoned
