### ISSUE TITLE
add cert rotation e2e test into presubmit prow/e2e_pilotv2_auth_sds

### ISSUE THREAD

**Issue by quanjielin** [istio/istio#11328]
https://github.com/istio/istio/pull/10887 enabled all existing pilot e2e test(including service to service mtls) in  release 1.1/master presubmit prow/e2e_pilotv2_auth_sds.sh, with sds/nodeagent enabled/secret mount disabled.
we need to add key rotation case for sds e2e flow (which existing pilot test don't have)

**Comment by myidpt** [comment]
Jimmy, please feel free to re-prioritize.

**Comment by JimmyCYJ** [comment]
@myidpt Please correct me if I am wrong, the cert rotation e2e tests need to be added into new test framework, not e2e_pilotv2_auth_sds, which is using the old framework that is going to be deprecated.

**Comment by howardjohn** [comment]
@JimmyCYJ I think you did this?
