### ISSUE TITLE
Zipkin address inconsistently used through Helm charts

### ISSUE THREAD

**Issue by tillig** [istio/istio#11334]
**Describe the bug**
Some Helm charts currently in `master` make use of a `.Values.global.tracer.zipkin.address` value to point to an external Zipkin instance but this doesn't happen in all the charts.

**Expected behavior**
If the external Jaeger/Zipkin is specified, the address should be used consistently throughout.

**Steps to reproduce the bug**
A correct implementation is seen in the [`gateways/templates/deployent.yaml`](https://github.com/istio/istio/blob/b8e30e07ec7b36cf1ba1b445b78c81fdf0d417b9/install/kubernetes/helm/subcharts/gateways/templates/deployment.yaml#L113) where it starts with an explicitly specified Zipkin endpoint, falls back to a namespace-qualified endpoint, and finally ends with a default endpoint.

- [`ingress/templates/deployment.yaml`](https://github.com/istio/istio/blob/3b8093d1635f9ccab4114d5bca3cfdfe7c6968ee/install/kubernetes/helm/subcharts/ingress/templates/deployment.yaml#L55) uses only the fixed default endpoint.
- [`mixer/templates/deployment.yaml`](https://github.com/istio/istio/blob/3b8093d1635f9ccab4114d5bca3cfdfe7c6968ee/install/kubernetes/helm/subcharts/mixer/templates/deployment.yaml#L46) uses the specific endpoint or the default, but not the namespace-qualified endpoint.
- [`templates/configmap.yaml`](https://github.com/istio/istio/blob/3b8093d1635f9ccab4114d5bca3cfdfe7c6968ee/install/kubernetes/helm/istio/templates/configmap.yaml#L142) uses the specific endpoint and the release namespace qualified endpoint, but no default and ignores the value for `global.istioNamespace`.

**Version**
Whatever's in `master` as of January 28, 2019. I'm trying to get a separate Jaeger install working in 1.0.5 so I'm manually grabbing things like this out of `master` and finding it's not easy to get it all lined up with the various inconsistencies.

**Comment by douglas-reid** [comment]
@bianpengyuan can you fix this in master?

**Comment by mdgreenfield** [comment]
It would also be great if one could disable tracing support altogether.

We're interested in integrating with [Datadog tracing APM](https://github.com/istio/istio/issues/6314) but until that is done we have no plans to run zipkin/lightstep and as a result we get unnecessary logging related to zipkin.
