### ISSUE TITLE
Support of an Envoy bootstrap config for custom Pilot implementation

### ISSUE THREAD

**Issue by alexburnos** [istio/istio#11336]
**Describe the feature request**
To allow integration with custom Pilot implementation that, for example, requires gRPC authz for discovery requests, Istio need to be distributed with an Envoy bootstrap template that supports/configured for these features.

This is an overall bug to track support of:
- Custom template config generation by pillot-agent (Issue#11198)
- Addition of Envoy bootstrap template for custom Pilot implementation to the Istio docker image

**Describe alternatives you've considered**
Alternatively pilot-agent could have generated different versions of configuration for different Pilot implementations based on the same bootstrap template. This would couple bootstrap changes needed with pilot-agent implementation and wouldn't scale well.

**Comment by wenchenglu** [comment]
@duderino 
marked as 1.1, fyi

**Comment by esnible** [comment]
Issue https://github.com/istio/istio/issues/11322 and https://github.com/istio/istio/issues/11458 seem related.

**Comment by esnible** [comment]
Is there a design proposal for these features?

In https://github.com/istio/istio/pull/11398 I added a new annotation, `sidecar.istio.io/v1alpha1/statsPatterns`, which lets me control the stats inclusions.  We could continue adding custom annotations for particular Envoy configurations.  We could also go extremely generic and allow custom annotation that would apply a JSON Patch to the generated bootstrap.

**Comment by howardjohn** [comment]
https://github.com/istio/istio/pull/11559 makes the changes to allow a JSON patch to the generated bootstrap with a custom annotation

**Comment by munrodg** [comment]
@howardjohn please confirm this is fixed?

**Comment by howardjohn** [comment]
I think so but not 100% sure. @alexburnos?

**Comment by alexburnos** [comment]
Sorry, was away. Yes, I think we can close it for current implementation to keep issues hygiene high.
