### ISSUE TITLE
Mixer incorrectly logs error 'Report failed:1 error occurred: * internal: no instances sent' with external adapter                                    

### ISSUE THREAD

**Issue by mhamrah** [istio/istio#11344]
**Describe the bug**
Mixer will output an error log message when it tries to invoke a [dynamic handler with no instances passed as an argument, as defined on this line of code](https://github.com/istio/istio/blob/b8e30e07ec7b36cf1ba1b445b78c81fdf0d417b9/mixer/pkg/protobuf/yaml/dynamic/handler.go#L162). However, the dispatcher will periodically [send report dispatches with nothing to encode, as set here on this line of code](
https://github.com/istio/istio/blob/b8e30e07ec7b36cf1ba1b445b78c81fdf0d417b9/mixer/pkg/runtime/dispatcher/dispatchstate.go#L157). There is either a bug in that the handler should not log an error if there is nothing to encode, and simply return, or the dispatcher should always send something to dispatch.

We found this error when using an external reporting adapter, specifically the [SignalFX Istio Adapter](https://github.com/signalfx/signalfx-istio-adapter), to send traces to SignalFX. This adapter leverages the dynamic handler feature of mixer. We aren't losing any traces, it's just that mixer, via the dispatch state function, will invoke this handler if there is nothing to be sent, and the dynamic handler errors if it is passed nothing to encode.

**Expected behavior**
Either the dispatcher doesn't dispatch a report request with no payload, or the handler doesn't log an error.

**Steps to reproduce the bug**
Simply create any adapter that uses the TEMPLATE_VARIETY_REPORT. The line of code in dispatchstate will be hit with nothing to encode, and the error will be returned in the dynamic handler.  

**Version**
Istio 1.0.5 with Kubernetes 1.10

**Installation**
Helm Chart

**Environment**
AWS. Occurs both on EKS and via kube-aws.

**Comment by keitwb** [comment]
I did some experimenting with this and I think it has something to do with the `match`ing in the Istio `rule` resources for tracing/metrics.  When I use the standard match rule for tracing of `(context.protocol == "http" || context.protocol == "grpc") && request.host != "mixer"`, I regularly get the `no instances sent` error, but if I set it to `"true"`, I don't get the error.  Based on [the session.dispatchBufferedReports method](https://github.com/istio/istio/blob/1.0.5/mixer/pkg/runtime/dispatcher/session.go#L220), I'm guessing that it [sets up a Report](https://github.com/istio/istio/blob/1.0.5/mixer/pkg/runtime/dispatcher/session.go#L140) before considering whether [any instances matched](https://github.com/istio/istio/blob/1.0.5/mixer/pkg/runtime/dispatcher/session.go#L166), and then if all instances get filtered out, it triggers the error when it actually goes to dispatch to the handler.  

We return the same thing from our adapter regardless of the number of instances actually received, and given that the error for no instances is returned before the gRPC call is invoked to the adapter, I don't think the adapter has any effect on it.
