### ISSUE TITLE
Document how to use a centrally-deployed Jaeger installation

### ISSUE THREAD

**Issue by tillig** [istio/istio#11340]
**Describe the feature request**
We have a central deployment of Jaeger for handling tracing across teams and services. We did not deploy the Istio-specific Jaeger. I'm struggling to get traces pushed to our central Jaeger.

Challenges include:

- Inconsistency in the Helm charts with respect to a specified Zipkin location (#11334)
- Using the Jaeger Operator [jaeger-agent sidecar](https://github.com/jaegertracing/jaeger-operator#auto-injection-of-jaeger-agent-sidecars) along with the Istio Envoy sidecar is difficult. The Envoy sidecar intercepts the tchannel requests to the Jaeger Collector on port 14267. I've tried [adding an egress for the centrally-deployed Jaeger Collector sort of how you have to do that for Google APIs. ](#5288) That doesn't seem to work. I'm still trying to figure it out.
- It looks like [Mixer may need to know about the Jaeger URL](https://istio.io/docs/reference/commands/mixc/) but I'm not sure where to configure that in the Helm charts. Maybe I don't need to?

**Describe alternatives you've considered**
I've tried...
- Removing the Envoy sidecar from my service - the Jaeger agent is able to connect to the collector but then my service isn't in the Istio mesh.
- Adding a `ServiceEntry` for my service `jaeger-collector.monitoring.svc.cluster.local` with a location `MESH_EXTERNAL` and the ports 9411 (HTTP) , 14267 (TCP), 14268 (HTTP). This doesn't seem to have any effect - the agent won't connect to the connector.

**Additional context**
The error I'm currently fighting to get the agent sidecar connected to the collector is:

`{"level":"error","ts":1548718019.8056602,"caller":"peerlistmgr/peer_list_mgr.go:171","msg":"Unable to connect","host:port":"jaeger-collector.monitoring.svc.cluster.local:14267","connCheckTimeout":60,"error":"tchannel error ErrCodeNetwork: read tcp 10.244.0.80:39884->10.244.4.11:14267: read: connection reset by peer","stacktrace":"github.com/jaegertracing/jaeger/pkg/discovery/peerlistmgr.(*PeerListManager).ensureConnections\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/pkg/discovery/peerlistmgr/peer_list_mgr.go:171\ngithub.com/jaegertracing/jaeger/pkg/discovery/peerlistmgr.(*PeerListManager).maintainConnections\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/pkg/discovery/peerlistmgr/peer_list_mgr.go:101"}`

I am assuming this indicates the connection is not properly flowing through the Envoy proxy.

Possibly related issues:

- #3395 - Envoy to forward application level spans to Tracing: If Envoy is going to forward anything on its own to the agent/collector it'd potentially need to work with a local sidecar agent.
- #10201 - why the sidecar can not process trace span: This is an FAQ; the ability to use a central Jaeger may also fall into FAQ territory.
- #11334  - Zipkin address inconsistently used through Helm charts: If the location of Jaeger is configurable, it'll need to be consistent through the Helm charts.

**Comment by objectiser** [comment]
> It looks like Mixer may need to know about the Jaeger URL but I'm not sure where to configure that in the Helm charts. Maybe I don't need to?

The easiest approach is to just use the zipkin address, but setup a service that maps onto the jaeger collector. See the `zipkin` service in [this PR](https://github.com/istio/istio/blob/ae61e4ab5795e88e2c3c1230563300f1b53b9cb3/install/kubernetes/helm/subcharts/tracing/templates/service.yaml), which is aiming to add the jaeger-operator to the istio helm chart.

Regarding the jaeger agent as a sidecar - is this to collect spans from just the envoy proxy, or to also collect additional span data from the service?

May be better to use jaeger agent as a daemonset configuration to avoid conflicts between the sidecars. You will need to provide configuration for the [agent host](https://github.com/jaegertracing/jaeger-operator#agent-as-daemonset), to ensure the Jaeger Tracer within your service can connect to the local node's agent.

**Comment by tillig** [comment]
The point of the Jaeger agent as a sidecar is to collect data from the application beyond just begin/end request info. It has nothing to do with collecting anything from the Envoy proxy. Also, [as noted in this blog article](https://medium.com/jaegertracing/deployment-strategies-for-the-jaeger-agent-1d6f91796d09) there's a certain amount of endpoint security provided by using a sidecar rather than having it as a DaemonSet.

 [Jaeger Operator can inject the agent as a sidecar](https://github.com/jaegertracing/jaeger-operator#auto-injection-of-jaeger-agent-sidecars) and we were hoping to use that functionality. However, as a sidecar I find the Envoy proxy is intercepting and breaking the Thrift connection between the agent and the collector. Short term I'm trying to figure out a way to exclude traffic _by port_ from the Envoy proxy interception; longer term, for the benefit of the community, more robust documentation on how to get an external Jaeger properly working including agent sidecars would be really good.

**Comment by objectiser** [comment]
Although not a solution to your agent problem, the other approach would be to configure the Jaeger tracer to directly send to the collector.

**Comment by objectiser** [comment]
No sorry, don't know.

Might be worth trying to get the service's Jaeger tracer to use the `HTTPSender` (or via [JAEGER_ENDPOINT](https://github.com/jaegertracing/jaeger-client-java/tree/master/jaeger-core#configuration-via-environment) env var) to talk directly to the jaeger collector - as if that works, then the sidecar agent should also be able to connect to the collector. Would be useful information to find out.

**Comment by mwieczorek** [comment]
Adding comment just to make it not stale (I also would like to run jaeger agent as a sidecar)

**Comment by objectiser** [comment]
This has already been documented: https://istio.io/docs/tasks/telemetry/distributed-tracing/jaeger/#before-you-begin (see option b).

This approach uses the Jaeger operator, which also provides the ability to inject the agent as a sidecar.

I'll close this issue, if further information is required in the docs then please reopen.

**Comment by pujunYang** [comment]
@tillig , i have the same problem, do you have solve it?
