### ISSUE TITLE
When will HPA be fixed? <unknown>/80%

### ISSUE THREAD

**Issue by mabushey** [istio/istio#11350]
**Describe the bug**
HPA has been broke since I started working with Istio (Istio 0.8)

**Expected behavior**
Working HPA

**Steps to reproduce the bug**
```
✗ kubectl get hpa -n istio-system
NAME                   REFERENCE                         TARGETS         MINPODS   MAXPODS   REPLICAS   AGE
istio-egressgateway    Deployment/istio-egressgateway    <unknown>/80%   1         5         0          41m
istio-ingressgateway   Deployment/istio-ingressgateway   <unknown>/80%   1         5         0          41m
istio-pilot            Deployment/istio-pilot            <unknown>/80%   1         5         0          41m
istio-policy           Deployment/istio-policy           <unknown>/80%   1         5         1          41m
istio-telemetry        Deployment/istio-telemetry        <unknown>/80%   1         5         0          41m
```

**Version**
Istio 1.0.5, k8s 1.10 and 1.11

**Installation**
kubectl apply -f istio.yaml

**Environment**
AWS/kops

Heapster is deprecated, and metric-server is defective. Is Istio setting up the HPA's in the hope that in the future it will work? Is there any way it can be made to work currently?

**Comment by linsun** [comment]
I think this is related to a few other issues out there due to not setting memory resources.

see https://github.com/istio/istio/issues/11280 #10755

**Comment by jnativio** [comment]
The problem described does not have to do with not defining memory requests as Istio default HPAs are based on CPU utilization, and it has been working fine in other platforms. It seems the metrics are not available in your cluster. Heapster is deprecated in k8s 1.11, but still works. Does the command `kubectl top nodes/pods` work for you?

**Comment by linsun** [comment]
Good point @jnativio! 

yes, I ran the cmd it works okay for IBM Kubernetes services:

```
$ kubectl get hpa -n istio-system
NAME                   REFERENCE                         TARGETS   MINPODS   MAXPODS   REPLICAS   AGE
istio-egressgateway    Deployment/istio-egressgateway    20%/80%   1         5         1          4d19h
istio-ingressgateway   Deployment/istio-ingressgateway   20%/80%   1         5         1          4d19h
istio-pilot            Deployment/istio-pilot            0%/80%    1         5         1          4d19h
istio-policy           Deployment/istio-policy           25%/80%   1         5         1          4d19h
istio-telemetry        Deployment/istio-telemetry        25%/80%   1         5         1          4d19h
```

**Comment by mabushey** [comment]
@jnativio

Correct, top does not work:
```
➜  1.8+  git:(master) ✗ kubectl top nodes                                             
error: metrics not available yet
➜  1.8+  git:(master) ✗ kubectl top pods 
➜  1.8+  git:(master) ✗ 
```

That's kind of my whole point is Istio is relying on a broken tool; Metrics Server does not work.

`git diff metrics-server-deployment.yaml`
```
       containers:
       - name: metrics-server
         image: k8s.gcr.io/metrics-server-amd64:v0.3.1
+        command:
+          - /metrics-server
+          - --kubelet-insecure-tls
+          - --kubelet-preferred-address-types=InternalIP
         imagePullPolicy: Always
```

I'm adding some of the recommended "fixes". While this reduces some errors it still does not make Metrics Server actually work.

I've seen some fixes to heapster to make it function on a newer k8s version, I'll follow your advice and try to get heapster patched up and running.

**Comment by mabushey** [comment]
I managed to get metrics server to work. I had to add `authenticationTokenWebhook` and `authorizationMode` to the kublet spec:
`kops edit cluster $NAME --state= $STATE`
```
  kubelet:
    authenticationTokenWebhook: true
    authorizationMode: Webhook
```

This broke `kubectl logs` which was fixed via:
```
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:kubelet-api-admin
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
subjects:
- kind: User
  name: kubelet-api
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: system:kubelet-api-admin
  apiGroup: rbac.authorization.k8s.io
```

**Comment by mabushey** [comment]
The updated change to `metrics-server-deployment.yaml`:
```
       containers:
       - name: metrics-server
         image: k8s.gcr.io/metrics-server-amd64:v0.3.1
+        command:
+            - /metrics-server
+            - --kubelet-insecure-tls
+            - --kubelet-preferred-address-types=InternalIP,Hostname,ExternalIP
         imagePullPolicy: Always
```
