### ISSUE TITLE
mixer: enable CEL runtime as an option

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#11351]
Per agreement, we want to allow CEL expessions over CEXL using custom annotations on rules and instances, without changing the defaults. Additionally, add tooling for conversion to assist migration.

/cc @mandarjog

**Comment by kyessenov** [comment]
ref #10630

**Comment by douglas-reid** [comment]
#12145 was merged. I think we can close this issue. Please re-open if you feel like I've jumped the gun.
