### ISSUE TITLE
deleting the Istio-system namespace results in  leaked configuration for the sidecar injector

### ISSUE THREAD

**Issue by sdake** [istio/istio#11362]
**Describe the bug**
If the istio-system namespace is deleted (to remove Istio quickly), and a namespace is labeled for sidecar injectoin (such as default), the annotations documented for sidecar injection ignore are not honored.  Worse, the app itself attempts to in some way contact the sidecar injector (which has been deleted).

**Expected behavior**
When deleting the istio-system namespace, the admission controller registration is revoked such that no automatic injection is attempted.

**Steps to reproduce the bug**
```
kubectl create ns istio-system
kubectl apply -f $HOME/istio-init.yaml - manually deleting the certmanager job
kubectl apply -f $HOME/istio.ayml
label the default namespace
kubectl delete ns istio-ssytem
Wait for the namespace deletion to complete (as in kubectl get ns shows no entries for istio-system)
kubectl apply -f $HOME/istio-init.yaml (one that has certmanager job present)
```

This will result in a certmanager CRD pod being created in the  default namespace with the proxy injected (!) and either readiness failing, or the sideecar call failing, depending on how the test case was executed.

**Version**
master/release-1.1

**Installation**
see reproducer.

**Environment**
K8S 1.13.2

**Cluster state**
none.

**Comment by sdake** [comment]
I'm not sure this use case is a priority - but I thought I'd report it just in case folks wanted to take a look at this for 1.2 or later.  Seems to me like a Kubernetes proper problem.

Cheers
-steve

**Comment by sdake** [comment]
cc / @ayj

**Comment by ayj** [comment]
It's not clear why the proxy would be successfully injected into a pod when the sidecar injector itself isn't present (when istio-system namespace is removed) to do the injection. Instead, I would expect pod creation to block unless you also removed the webhook config. 

Unlike other namespace'd resources in istio-system, the _cluster-scoped_ mutatingwebhookconfiguration isn't deleted when the istio-system namespace is removed. The user either needs to explicitly delete it (via kubectl delete -f <whatever-yaml-file-contains-the-webhook-config>, or the sidecar injector needs to be updated to set the config's ownerRef to itself so that k8s itself removes the cluster-scoped resource when the injector deployment is removed.

**Comment by ostromart** [comment]
This is probably not a common enough case to spend a ton of effort on, unless there's a simple fix. We could try throwing it over the fence to someone in k8s to take a look.

**Comment by ostromart** [comment]
How easy is this to repro @sdake ? I tried once but I don't think I'm following exactly your steps, since I tried rendering istio-init and istio from a nightly release. 
Could you provide instruction how you generated those?

**Comment by sdake** [comment]
@ostromart I'd think a kubernetes bug would be more appropriate here.  Unfortunately I filed this a week ago, and can't remember what happened 12 hours ago :)

The steps I recorded in the issue tracker were from memory - not an actual reproduction.  I thought that was better than no steps at all.

To reproduce will probably require varying the steps a bit or adding new ones to get it to reproduce.  Clearly a step was left out.

Lets just keep this open for now in case anyone else runs into it or I have an opportunity to spend time producing a reliable reproducer.

It sort of seemed to me that the admission controller was still registered even after the namespace was deleted (and then recreated).

@ayj fwiw I do recall the pod creation failing (waiting for the injector webhook to respond, but it could do so as the injector pod at port 443 was not running in the system.

cheers
-steve

**Comment by sdake** [comment]
Additional information: this problem was discovered while running with this PR (iirc): https://github.com/istio/istio/issues/11316

It is entirely possible I manually injected istio-init manifest, but frankly I don't remember.

**Comment by dkrieger** [comment]
Unstale

**Comment by howardjohn** [comment]
I think we need https://github.com/istio/istio/pull/16857 for the injector as well @ayj

**Comment by ayj** [comment]
cc @lei-tang who is working on istioctl commands to manage webhook life cycle.
