### ISSUE TITLE
Add a graph "Outgoing requests by source principal and destination" to Workload dashboard in Istio installation

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio#11373]
Since this is the most meaningful graph for the egress traffic. Also, a graph: "Outgoing requests by source principal, destination and response code", which is the most meaningful graph for the HTTP egress traffic with TLS origination (response code is known)".

**Comment by munrodg** [comment]
Moving to 1.2.

**Comment by douglas-reid** [comment]
@vadimeisenbergibm i took a look at this briefly this morning, and then realized the following: the outgoing charts are based on client-side metrics (`reporter="source"`). For those metrics, `source.principal` is always `"unknown"`.  As a result, there is no value add to create that chart for HTTP egress.  In-mesh, we could support that -- but it won't help the issue being raised here.

/cc @mandarjog @kyessenov 

I'm going to close this issue as a result. I think there is probably an action item here to improve proxy-awareness of its own principal however.
