### ISSUE TITLE
Add connection and request rate limiting tests to Galley

### ISSUE THREAD

**Issue by ayj** [istio/istio#11379]
As part of hardening Galley w/MCP for production we should add additional tests for connection and request rate limiting. Today we rate limit on the client side but the server does not explicit rate limit new connections beyond what the grpc/networking stack provides.

**Comment by Nino-K** [comment]
Going to close this issue since the PR is merged, @ayj feel free to re-open if needed.

**Comment by Nino-K** [comment]
https://github.com/istio/istio/pull/11994
