### ISSUE TITLE
Helm updrade from 1.0.4 to 1.1.snapshot.5 fails

### ISSUE THREAD

**Issue by iandyh** [istio/istio#11402]
**Describe the bug**
When upgrading from 1.0.4 to 1.1.0.snapshot 5, we encountered this error:

```
Error: UPGRADE FAILED: Service "istio-egressgateway" is invalid: [spec.ports[0].nodePort: Forbidden: may not be used when `type` is 'ClusterIP', spec.ports[1].nodePort: Forbidden: may not be used when `type` is 'ClusterIP']
```
This is the helm history:

```
REVISION        UPDATED                         STATUS          CHART           DESCRIPTION
1               Wed Jan 30 04:55:52 2019        DEPLOYED        istio-1.0.4     Install complete
2               Wed Jan 30 04:57:46 2019        FAILED          istio-1.1.0     Upgrade "istio" failed: Service "istio-egressgateway" is ...
```

**Expected behavior**
The upgrade should be successful

**Steps to reproduce the bug**
Install istio 1.0.4 using Helm and Tiller. And then run 

`helm upgrade istio istio-1.1.0-snapshot.5/install/kubernetes/helm/istio --namespace istio-system`

**Version**
k8s version:
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Installation**
Using Helm and Tiller

**Environment**
Baremetal, kernel: 4.4.110-1.el7.elrepo.x86_64

**Comment by duderino** [comment]
@ostromart can you take a stab at this?  or failfast and tell me to find someone else?

**Comment by ostromart** [comment]
Yes, I'll take it.

**Comment by ostromart** [comment]
I tried to repro but it works for me when starting from a clean slate. 
I need some more info to see what's happening in your case:
helm repo list
kc get deployment istio-egressgateway -o yaml
kc get service istio-egressgateway -o yaml
What options do you pass to helm install (if any)?

**Comment by liminw** [comment]
These are two similar issues. 
https://github.com/istio/istio/issues/11865
https://github.com/istio/istio/issues/11868

**Comment by ostromart** [comment]
Since there's no update, I'm going to make a guess that this was due to a missing helm repo.
I verified that 1.0.4->1.1.0-rc.0 works.
@iandyh if you want to try it again, could you try with rc0 and the new & improved upgrade instructions on preliminary.istio.io? Make sure you have the correct helm repo installed. 
If you hit a problem, please open a new bug.

**Comment by iandyh** [comment]
@ostromart Sorry for the inactivity. Was busy with checking other issues...

I believe this is due to a invalid configuration in my local and I'll keep an eye on this.
