### ISSUE TITLE
Support Watch and List with specified the namespaces in citadel

### ISSUE THREAD

**Issue by clyang82** [istio/istio#11415]
I met one case for citadel. We have a K8s environment which already have some namespaces. I want to have istio mesh capability in this environment. After installed the istio, I found that the citadel will watch and list `serviceaccount` in all namespaces and create the secret with name `istio.<sa>` automatically. Can we have the function to specify the namespaces which are planned to involve into service mesh? Do you think this requirement is valid? @diemtvu @incfly @myidpt @wattli

if this case is valid, I would like to have a PR for this case. Thanks.

**Comment by clyang82** [comment]
another case is in my understand citadel only need to:
1. create secret for sa `istio-galley-service-account` which is used by `validatingwebhookconfiguration`
2. create secret for sa `istio-sidecar-injector-service-account` which is used by `MutatingWebhookConfiguration`
3. create secret for sa `default` in required namespace.
but now, we watched all sa and create secret for all sa. is my understanding right?

**Comment by myidpt** [comment]
Now Citadel can watch all namespaces or a single namespace:
https://github.com/istio/istio/blob/master/security/cmd/istio_ca/main.go#L143
That's a limitation. Please feel free to create a PR for watching multiple specified namespaces.

**Comment by incfly** [comment]
I'd like to understand the problem as a big picture a little bit more.

Are you saying your k8s cluster has some deployments in other namespaces that you don't want to managed by Istio? Is that the reason of not generating secrets?

If you want isolation to make Istio only affect a subset of namespaces in a cluster, don't you also need Pilot/Mixer/Galley to narrow down their namespaces as well?

Or there's something special about your cluster where in those namespaces you don't want Istio, they have tons of k8s service account and being recreated, which cause overload to Citadel?

**Comment by clyang82** [comment]
@incfly Yes. I just want to limit some namespaces to be managed by Istio instead of all namespaces in my k8s cluster. That is true do not need Pilot/Mixer/Galley to narrow down non-istio managed namespaces.

**Comment by gyliu513** [comment]
Also some related requirement at https://github.com/istio/istio/issues/6312#issue-332622356

FYI @clyang82

**Comment by linsun** [comment]
curious why we can't achieve this by not injecting sidecars to the pods in the namespaces you don't want istio to manage?

**Comment by clyang82** [comment]
@linsun Yes. if you don't want istio to manage, you can achieve it by not injecting sidecar to the pod. the current issue is `citadel` watch/list all namespace or a namespace sa to create secret for it. cannot support multiple namespaces.

**Comment by linsun** [comment]
@clyang82 sorry the user impact isn't clear to me.  Please explain how the limitation of citadel watch list serviecaccount in all namespaces or a namespace will impact a user.   And if user can work around this limitation by not injecting sidecars to pods they don't want to be managed by istio.

**Comment by clyang82** [comment]
The real case is there are some existing resources/apps in some namespaces, we do not want to touch the existing ones. now we want to use istio to manage the new apps/services in new namespaces. I think that is a typical case to adopt istio for service mesh. right now, we cannot specify multiple namespaces to be managed by citadel, because citadel only handles all namespaces or just a namespace. so if use citadel for all namespaces, then the existing namespaces will be modified by create secreting based on the existing serviceaccount in those namespace.

**Comment by linsun** [comment]
@clyang82 are you saying we would change existing namespaces by creating service accounts there which can cause the apps behavior changes within the existing namespaces?  (if user chooses to use citadel for all namespaces).

**Comment by myidpt** [comment]
@linsun The only thing Citadel modifies the existing namespaces is that it creates secrets for all the serviceaccounts in the namespace. It doesn't cause app behavior change, as long as the apps don't rely on the Citadel-created secrets (which shouldn't). But supporting multi-namespace still offers some benefits VS. all-namespace:
1. Better security. Citadel signing key is less used.
2. Citadel manages less serviceaccounts, therefore, the load on Citadel can be reduced.
3. Less confusion to the users. Citadel won't write secrets to non-Istio namespaces.
With that said, I think this feature is non-critical (P1) for 1.1, unless this really blocks our customers.

**Comment by clyang82** [comment]
@myidpt Thanks for your explanation.
@linsun  @myidpt I agree with this feature is non-blocking issue. but it is a big user experience improvement. Otherwise, it makes big noise for our customers.

**Comment by linsun** [comment]
I agree writing secrets to non-istio-managed namespaces is a huge surprise to our users.  Conceptually it doesn't cause app behavior changes when app doesn't use the secrets, however it can be huge concern for banking customers.

**Comment by incfly** [comment]
What if we just set rbac to disallow citadel to write to certain NS, will
citadel still work for the rest?

Just brainstorming alternative. I do think add native support in citadel is
better option.

**Comment by myidpt** [comment]
@incfly I have a naive question: so it seems there's a way to specify Kube RBAC for a service account to access resources in a specific set of namespaces? I'd like to learn how to do that if it's possible.

**Comment by elevran** [comment]
@myidpt AFAIK, RBAC is specified on cluster (i.e., all namespaces) or namespace scope, so you need a binding per NS where Citadel needs to create secrets. Also [permissions are purely additive (there are no “deny” rules)](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#role-and-clusterrole), so you can't create RBAC for **not accessing** the existing namespaces.

Does it make sense to extend Citadel to obey the same logic as the auto-injector? There is a global mesh policy (enable/disable) which can be overridden per namespace (with a label), or per pod (with an annotation). If we follow the same heuristics in Citadel (applying the annotation to a service account), we could get the desired behavior using the existing configuration mechanisms.
So for a migration, keep the mesh config on `disable` and label new namespace (or default to `enable` and label existing namespaces).

Thoughts? @clyang82 would that help with your issue?

**Comment by monkeymorgan** [comment]
I imagine that the new plural option (https://github.com/istio/istio/pull/11932) and [--listened-namespaces in citadel] could be used in the citadel chart to generate a more minimal (ie. Role based) RBAC config more suited to multi tenant clusters. 

It's a blocking issue for adoption where I work as we need a 1 istio:many (but not all) NS deployment model, and part of it issue relates to trust and risk - Having zero or near zero ClusterRoles is the clearest way to convince cluster operators that there will be no effect on non participants. Conversely, creating secrets in out of bounds namespaces creates distrust so I'm incredibly happy to see so much recent movement on the various soft multi-tenancy issues.

**Comment by elevran** [comment]
@monkeymorgan:
Are you looking to enable gradual adoption or is it fixed at installation time?
I would imagine that RBAC roles can't be fixed at helm chart deployment, if you'd like to add new namespaces to Istio's control over time.

**Comment by elevran** [comment]
@monkeymorgan:
Are you looking to enable gradual adoption or is it fixed at installation time?
I would imagine that RBAC roles can't be fixed at helm chart deployment, if you'd like to add new namespaces to Istio's control over time.

**Comment by clyang82** [comment]
@elevran & @monkeymorgan this PR #11667 was merged to release 1.1. so the `--listened-namespaces` is available for `citadel` right now.

**Comment by clyang82** [comment]
I think another point for this issue is how to allow adding a new namespace without restart the citadel. currently, only adding this capability from the command line. that means add a new namespace requires to restart the citadel. that is a problem in real production. Consider that add a new namespace is a frequent operation in a real production. so hot load is a required feature. @elevran 's point can resolve this problem. Thanks.

**Comment by monkeymorgan** [comment]
@elevran 
We're looking for gradual adoption. It could be years before istio becomes a cluster wide service owned and operated by a central team, if that ever even happens. In the interim the key is there is safe controls over the reach and impact of istio on non tenants. In our case, each time we accept a new NS we'd be happy to both label that NS to opt-in and to generate RBAC config to allow istio access to that NS. We already have an `istio-tenant` chart including a gateway and some network policies so adding RBAC there would cost noting in terms of operational overhead. 

On the idea of using labels instead of CLI parameters - that's fine by us as long as we get similar guarantees on the reach of istio and the labels are opt-in. The one difference here is that if you choose to use a single label for all components you can't configure a different set of namespaces for EDS than those watched by the sidecar injector for example. It would also be useful to support running parallel istio control planes so perhaps the control plane NS should be included in the label. This also allows us to circumvent the central ownership problem for a longer period by allowing teams own their own control plane. Once the tech is generally seen to be stable in our clusters and a central team are happy to support it we could consolidate into a single cluster wide mesh.
