### ISSUE TITLE
Pilot is picking DestinationRule randomly but not the most specific one

### ISSUE THREAD

**Issue by yangminzhu** [istio/istio#11425]
**Describe the bug**
The [PushContext.DestinationRule()](https://github.com/istio/istio/blob/eb3cc2fff2be6670e613975cd6679c80e9182bf4/pilot/pkg/model/push_context.go#L491) returns the DestinationRule for a given service. However it's returning a random destination rule.

The function returns early in [line 493](https://github.com/istio/istio/blob/eb3cc2fff2be6670e613975cd6679c80e9182bf4/pilot/pkg/model/push_context.go#L493) when it find a matching host from the list `processedDestRulesForNamespace`. But that might not be the most specific host that it should return.

For example, suppose we're getting destination rule for service `"httpbin.foo.svc.cluster.local"` with the following `processedDestRulesForNamespace`

```
processedDestRulesForNamespace: {
  "foo": [httpbin.foo.svc.cluster.local],
  "istio-system": [istio-telemetry.istio-system.svc.cluster.local istio-policy.istio-system.svc.cluster.local kubernetes.default.svc.cluster.local *.local]
}
```

The [PushContext.DestinationRule()](https://github.com/istio/istio/blob/eb3cc2fff2be6670e613975cd6679c80e9182bf4/pilot/pkg/model/push_context.go) could either return `*.local` or `httpbin.foo.svc.cluster.local` randomly. (It should always return `httpbin.foo.svc.cluster.local`)

**Expected behavior**
`PushContext.DestinationRule()` returns the most specific destination rule for a given service.

**Steps to reproduce the bug**
https://github.com/istio/istio/issues/11315#issuecomment-458781731

**Version**
1.1

/cc @diemtvu

**Comment by yangminzhu** [comment]
Note, this is caused as the `DestinationRule()` is called with a nil `Proxy` from [istio.debug.go](https://github.com/istio/istio/blob/4b7b13aef4afe31fb193bb99e3d375efb82d69e8/pilot/pkg/proxy/envoy/v2/debug.go#L352).

**Comment by costinm** [comment]
@rshriram

**Comment by diemtvu** [comment]
This mostly affects the `istioctl authn tls-check` tool, as it try to check the DR and authN policy consistency by service, without getting into proxy instance level.

On the other hand, we have other issue related to the recent change in the way picking up DR (https://github.com/istio/istio/issues/11545)
