### ISSUE TITLE
Eliminate spurious port 15020 warnings from pilot logs

### ISSUE THREAD

**Issue by esnible** [istio/istio#11427]
Pilot frequently logs warnings about port 15020 conflicts.  The logs look like:

```
warn	Omitting listener for management address 172.30.172.147_15020 (socket_address:<address:"172.30.172.147" port_value:15020 > ) due to collision with service listener 172.30.172.147_15020 (socket_address:<address:"172.30.172.147" port_value:15020 > )
```

These are the only warnings coming from Pilot and there are a lot of them.  About 1000/day on my tiny cluster.  It makes it difficult to notice any real warnings.

To reproduce (see the warnings), deploy Istio and bookinfo and do

`kubectl -n istio-system logs $(kubectl -n istio-system get pod --selector istio=pilot --output jsonpath='{.items[0].metadata.name}') -c discovery | grep warn`

**Comment by mbanikazemi** [comment]
Not occurring anymore. Please reopen if observed again.
