### ISSUE TITLE
Mixer integration test TestTcpMetric is flaky

### ISSUE THREAD

**Issue by hklai** [istio/istio#11430]
https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/11423/istio-integ-k8s-tests/2757/

https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/11423/istio-integ-k8s-tests/2768/

```
scenarios_test.go:137: prometheus values for istio_tcp_sent_bytes_total:
scenarios_test.go:137: Could not find metric value: value not found for map[string]string(nil)
```

**Comment by duderino** [comment]
@gargnupur can you work on this?

**Comment by gargnupur** [comment]
@duderino : Yes, I will take a look at this one...

**Comment by gargnupur** [comment]
This PR fixed this: https://github.com/istio/istio/pull/13247

Closing it for now..
