### ISSUE TITLE
Fix k8s integration test

### ISSUE THREAD

**Issue by hklai** [istio/istio#11436]
For some reason, the integration test jobs using k8s environment keep failing with image pull backoff problem.

Example:
https://k8s-gubernator.appspot.com/build/istio-prow/logs/istio-integ-k8s-tests/2778

And it stays that way even after we increased deployment timeout. (see https://github.com/istio/istio/commit/ce038fe2d60367f10c26a0da1be9e843934182c9)

There are similar problems in presubmit for the test, but the failures are not consistently. 
Example: https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/11423/istio-integ-k8s-tests/2772

Theatrically, presubmit jobs and post submit jobs just run with similar Prow config. The only material difference is that presubmit jobs use [build-pool](https://github.com/istio/test-infra/blob/master/prow/cluster/jobs/istio/istio/istio.istio.release-1.1.yaml#L64), where postsubmit jobs use [test-pool](https://github.com/istio/test-infra/blob/master/prow/cluster/jobs/istio/istio/istio.istio.release-1.1.yaml#L262).

**Comment by duderino** [comment]
@nmittler @ozevren @gargnupur please can one person pick this up and unassign the others?

**Comment by nmittler** [comment]
@gargnupur would you mind taking a look?

**Comment by esnible** [comment]
I had a similar failure this morning.

https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/11508/istio-integ-k8s-tests/3369

1 failed / 6 succeeded after 24m52s.

```
--- FAIL: TestValidation (603.79s)
	validation_test.go:65: 1 error occurred:
		
		* timeout while waiting (last error: 2 errors occurred:
		
		* istio-system/istio-egressgateway-77f9cc88dc-zwg75: container not ready: 'istio-proxy'
		* istio-system/istio-ingressgateway-f88b89574-nrggb: container not ready: 'istio-proxy')
```

Although the complain is that the container isn't ready the dump in the log shows that it is ready:

```
        "name": "istio-proxy",
        "state": {
          "running": {
            "startedAt": "2019-02-10T13:47:44Z"
          }
        },
```

The error message is `2019-02-10T13:50:03.136896Z	error	CI	Wait for Istio pods failed: timeout while waiting (last error: 2 errors occurred:`  It is possible the containers were almost ready -- just needed a bit more time -- and they finally became ready before the cluster state was dumped.

**Comment by utka** [comment]
@esnible 
Test started 2019-02-10T13:41:53.733776Z 
istio-proxy started  2019-02-10T13:47:42Z
Test failed 2019-02-10T13:50:03.136945Z
It was polling the state of the containers every second, it had 3 second to get ready state from istio-proxy. something is not add up.

**Comment by esnible** [comment]
Had a failure this morning on a PR that does not touch the integration.

https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/11592/istio-integ-k8s-tests/3414

```
--- FAIL: TestValidation (647.35s)
	validation_test.go:65: 1 error occurred:
		
		* timeout while waiting (last error: 1 error occurred:
		
		* istio-system/prometheus-587d65f679-f52f5: Pending)
```

caused by, most likely,

```
        "name": "prom-init",
        "state": {
          "waiting": {
            "reason": "CrashLoopBackOff",
            "message": "Back-off 2m40s restarting failed container=prom-init pod=prometheus-587d65f679-f52f5_istio-system(cb8c3940-2e27-11e9-8a1e-42010af00092)"
```

“prom-init” is just a busy-box running `"counter=0; until [ \"$counter\" -ge 30 ]; do if [ -f /etc/istio-certs/key.pem ]; then exit 0; else echo waiting for istio certs \u0026\u0026 sleep 1 \u0026\u0026 counter=$((counter+1)); fi; done; exit 1;”`

I suspect that the key is not being injected within 30 seconds leading to the crash.  Not sure why not.

**Comment by esnible** [comment]
Prometheus is *pending*.  Does this mean not enough resources?

```
--- FAIL: TestValidation (578.61s)
	validation_test.go:65: 1 error occurred:
		
		* timeout while waiting (last error: 3 errors occurred:
		
		* istio-system/istio-cleanup-secrets-84621bfdce12d62fdf2ce10f748792b5-kmmtc: Pending
		* istio-system/istio-security-post-install-84621bfdce12d62fdf2ce10f748792vlsvf: Pending
		* istio-system/prometheus-57bc88776-flc9v: Pending)
```

https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/12353/istio-integ-k8s-tests/4737/build-log.txt

The PR is a change to a sample.  It should not cause 3 pods to fail to start.  https://github.com/istio/istio/pull/12353

**Comment by ozevren** [comment]
It looks like there is a job ordering problem: https://github.com/istio/istio/issues/12606

See: https://github.com/istio/test-infra/pull/1188

**Comment by ozevren** [comment]
This particular problem (image pull) seems to be fixed at this point. There are other flakes that make the job less stable. I'll track those separately.
