### ISSUE TITLE
Prometheus running higher cpu and memory than request.

### ISSUE THREAD

**Issue by mmosttler** [istio/istio#11454]
**Describe the bug**
We are running istio 1.0.5 in gke 1.11.5-gke.5.  We are seeing prometheus running higher cpu and memory than requested.  

Should we increase the replicaCount from 1? I don't see any value in the helm template for adjusting requested cpu for just prometheus pod.

**Expected behavior**
cpu and memory within requested size

**Steps to reproduce the bug**
running load of 140 ops for 30min.  During that load it is running between 2x to 9x the requested cpu.

**Version**
istio 1.0.5 on gke 1.11.5-gke.5 cluster with 7 x 2cpu nodes.

**Installation**
helm template with customization values to generate istio yaml.
default cpu was set to 40m from 10m.

**Environment**
we are running in GCP and seeing the behavior in our load test environment and production environment.

**Comment by ymesika** [comment]
Each Istio component can have it's own requested resources in its values file or, if not specified, we take the default which is just 10m CPU.

I think that based on your experience we should specify a higher requested resources for prometheus.
Do you think this will be sufficient:

```yaml
resources:
  requests:
    cpu: 50m
    memory: 128Mi
```
