### ISSUE TITLE
Istio telemetry to get service to service latency

### ISSUE THREAD

**Issue by ananthunair** [istio/istio#11470]
**Describe the feature request**
A telemetry which shows the latency of requests between two services. A request can reach a service(A) from two different services(B and C). A way to show the latency from B to A and C to A.

**Describe alternatives you've considered**
I haven't figured out how to do this in Istio. But we have done it using envoy in current prod setup. The telemetry we is statsd where we have prefixed the the source and target services via envoy sidecar and in grafana using query we are getting service to service metrics.

**Additional context**
Current istio service dashboard provides metrics of "a service" but in a service mesh scenario the insight on specific service to service is really useful.

If there already a way please point me to that. I have done fair amount spikes to bring it up, but none of the telemetry currently available helped me.

**Comment by jmazzitelli** [comment]
@ananthunair have you looked at Kiali and how it visualizes edges? Perhaps that gets you what you want?

**Comment by jmazzitelli** [comment]
Here's the different edge labels that Kiali shows (using bookinfo as example) in its "versioned app" graph:

![screenshot from 2019-02-01 08-37-15](https://user-images.githubusercontent.com/2029470/52126359-1cb3a680-25fd-11e9-9248-713378c51436.png)

![screenshot from 2019-02-01 08-38-15](https://user-images.githubusercontent.com/2029470/52126360-1cb3a680-25fd-11e9-85b2-be6035fca4b8.png)

![screenshot from 2019-02-01 08-38-25](https://user-images.githubusercontent.com/2029470/52126361-1cb3a680-25fd-11e9-91c0-fc2dd829deaf.png)

**Comment by douglas-reid** [comment]
@ananthunair communications in a mesh are actually from workload instance (think: pod) to workload instance. it is possible for a workload instance to provide N services -- with the key bit being that a workload may provide more than 1 service.

In cases where a workload instance provides more than one service, it can be impossible to determine a connection between the service that was called and the call leaving the service. There is also the potentially trouble of workloads that provide 0 services.

We've had a number of discussions around this issue in the Policy and Telemetry WG -- and ultimately decided to drop any `source.service` attribute -- and instead focus on `source.workload.*` attributes.

I don't know what your prod setup is -- perhaps all of your workloads only provide a single service.  If that is the case, then Istio is providing exactly what you want... only using different nomenclature.

/cc @geeknoid

**Comment by ananthunair** [comment]
@douglas-reid  Our workloads provide different services not one.
In our current envoy proxy setup(prod).
We have say 3 service a, b and c with default 10 pods each(theoritically). Each pods envoy sidecar config(statsd component)is customized with 
```
    stats_sinks:
      -
        name: "envoy.statsd"
        config:
          tcp_cluster_name: "statsd-cluster"
          prefix : "serviceA"
```
(prefix differs from workload to workload depending on service)

And when we get the metrics from service a to b `eg:- upstream_rq_2xx` it will look like `serviceA_cluster_serviceB_upstream_rq_2xx`.

Then we query out what ever is required and make our service to service dashboard.

Sample dashbaord
<img width="1666" alt="sample_dashboard" src="https://user-images.githubusercontent.com/10118208/52192189-85ee2080-286e-11e9-91b7-4ae3d4e01ea7.png">

Variables in grafana
<img width="1048" alt="variables" src="https://user-images.githubusercontent.com/10118208/52192292-23495480-286f-11e9-9e81-2a627edffc1b.png">

Query of a particular graph
<img width="1610" alt="query" src="https://user-images.githubusercontent.com/10118208/52192323-51c72f80-286f-11e9-8a8e-51c68f3eca60.png">


Hope this provides a rudimentary idea on our setup and what i am looking for.

@jmazzitelli i did skim through `Kiali` but not extensively  I am seeing if i can reuse the existing chart by tweaking the queries.

**Comment by ananthunair** [comment]
@ jmazzitelli  just an update, kiali does show the metric, but grafana we can set alerts and thresholds which is something that is required. But kiali is a bit helpful. Thanks for pointing it out.

**Comment by douglas-reid** [comment]
@ananthunair are you manually configuring your proxies now?  are all of your services that run on a single workload running a different port?  how are you identifying the service of the source in traffic?
