### ISSUE TITLE
e2e-simple istio-security-test timeout

### ISSUE THREAD

**Issue by hklai** [istio/istio#11480]
Examples:
https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/11468/e2e-simpleTests/16937
https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/11468/e2e-simpleTests/16941

```
2019-02-01T14:36:25.630784Z	info	All deployments are ready
2019-02-01T14:36:25.630796Z	info	Running command helm test istio
2019-02-01T14:41:42.397618Z	info	Command output: 
RUNNING: istio-security-test
ERROR: timed out waiting for the condition
```

**Comment by lei-tang** [comment]
Based on https://testgrid.k8s.io/istio-release#e2e-simpleTests, all e2e-simpleTests tests passed consistently in the last 7 days from 5-10-2019 to today 5-16-2019. Hence, the issue is closed; if the problem occurs again, the issue can be reopened.

**Comment by myidpt** [comment]
Thanks, Lei.
