### ISSUE TITLE
Test istio.io/istio/galley/pkg/server TestServer_Basic is flaky

### ISSUE THREAD

**Issue by JimmyCYJ** [istio/istio#11482]
**Describe the bug**
Test istio.io/istio/galley/pkg/server TestServer_Basic consistently fail.
For example,
https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/11481/istio-unit-tests/20385
https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/11479/istio-unit-tests/20383

**Comment by JimmyCYJ** [comment]
cc @hklai

**Comment by kyessenov** [comment]
Yeap, more flakes:
https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/11469/istio-unit-tests/20388

**Comment by hklai** [comment]
Another example
https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/11481/istio-unit-tests/20392

**Comment by kyessenov** [comment]
This test fails consistently. We need to either fix it or disable it, or nothing will get merged.

**Comment by ozevren** [comment]
Should be fixed now.
