### ISSUE TITLE
Can't open Kiali Dashboard. Too many redirects

### ISSUE THREAD

**Issue by ichasco** [istio/istio#11491]
**Describe the bug**
Can't connect to kiali web dashboard. With Istio 1.0.5 I have no problem. 

The error is: too many redirects. 

kiali/
kiali
kiali/
kiali
kiali/
kiali

**Expected behavior**
Exec: `kubectl -n istio-system port-forward $(kubectl -n istio-system get pod -l app=kiali -o jsonpath='{.items[0].metadata.name}') 20001:20001`
And connect to: http://127.0.0.1/kiali

**Steps to reproduce the bug**
Deploy Istio with kiali enabled

**Version**

Kubectl:

> Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.6-gke.3", GitCommit:"04ad69a117f331df6272a343b5d8f9e2aee5ab0c", GitTreeState:"clean", BuildDate:"2019-01-10T00:39:15Z", GoVersion:"go1.10.3b4", Compiler:"gc", Platform:"linux/amd64"}

Istioctl:

> version.BuildInfo{Version:"1.1.0-snapshot.5", GitRevision:"f1eab0a25dd6f37be03951698be0e84b120ec18f", User:"root", Host:"79518220-20ee-11e9-86e9-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-snapshot.4-242-gf1eab0a"}

**Installation**

`cat install/kubernetes/namespace.yaml >istio.yaml`
`helm template install/kubernetes/helm/istio --name istio --namespace istio-system >>istio.yaml`

**Environment**
GCP

**Comment by linsun** [comment]
Try without /kiali just the 127.0.0.1:20001

I hit this too think it is just a doc issue.

**Comment by jmazzitelli** [comment]
Yes, this was a known issue and has been fixed in later versions. See:

https://github.com/kiali/kiali/pull/774
https://issues.jboss.org/browse/KIALI-2188 (though JIRA seems to be down at the moment I am writing this)

Workaround for older Kiali releases - just go to `/kiali/console` directly and it will work.
