### ISSUE TITLE
Sidecars in PERMISSIVE mode should use mTLS within Istio cluster.

### ISSUE THREAD

**Issue by PiotrSikora** [istio/istio#11494]
The intention behind the `PERMISSIVE` mode was to allow legacy clients to connect to an otherwise mutually-authenticated Istio cluster. Basically, a `STRICT` mode that also accepts clients without mTLS during transition from the legacy infrastructure.

However, it seems that the current implementation of the `PERMISSIVE` mode implements only the first part (accepting both: legacy and mTLS traffic for inbound connections), but doesn't deploy mutually-authenticated Istio cluster, and the communication between sidecars is happening over plaintext.

Note: This above is based on the assumption that using `install/kubernetes/istio-demo.yaml` or `global.mtls.enabled=false` results in the `PERMISSIVE` mode being enabled for all services, per comments in the templates, though, I'm not sure how to verify that this is really happening.

cc @incfly @wattli @wenchenglu @louiscryan @duderino

**Comment by wattli** [comment]
We do have a design https://docs.google.com/document/d/1yEMDRO2FZCyZnDK1AzNmjQtbtQqE7wN8YoM65FAH7uA/edit#, but this got deprioritized.

**Comment by wattli** [comment]
> The intention behind the `PERMISSIVE` mode was to allow legacy clients to connect to an otherwise mutually-authenticated Istio cluster. Basically, a `STRICT` mode that also accepts clients without mTLS during transition from the legacy infrastructure.
> 

We had discussions with @louiscryan on this last quarter. And the conclusion is as follows: 
sidecars are NOT suppose to always communicate with each other using mTLS in PERMISSIVE mode. A service with PERMISSIVE mode only means it can take both http and mTLS (that's why it is called 'PERMISSIVE'). We use it not only for legacy clients, but also for sidecar-enabled clients migration from http to mTLS (not all customers want to enable mTLS at the first place)

> However, it seems that the current implementation of the `PERMISSIVE` mode implements only the first part (accepting both: legacy and mTLS traffic for inbound connections), but doesn't deploy mutually-authenticated Istio cluster, and the communication between sidecars is happening over plaintext.
> 
> Note: This above is based on the assumption that using `install/kubernetes/istio-demo.yaml` or `global.mtls.enabled=false` results in the `PERMISSIVE` mode being enabled for all services, per comments in the templates, though, I'm not sure how to verify that this is really happening.
> 
> cc @incfly @wattli @wenchenglu @louiscryan @duderino
