### ISSUE TITLE
[Authz v2] Support basic fields update in ServiceRole/ServiceRoleBinding

### ISSUE THREAD

**Issue by yangminzhu** [istio/istio#11516]
**Describe the feature request**
- Support notPaths, notMethods, notPorts, hosts/notHosts in ServiceRole
- Support notUsers, groups/notGroups (Deprecate the current group field), namespaces/notNamespaces, notIps in ServiceRoleBinding

@pitlv2109 will work on this. I cannot assign this to Phillip as he is not in the Istio group yet, so assign to myself as a placeholder.

**Additional context**
[Istio Authorization v2 design](https://docs.google.com/document/d/1diwa9oYVwmLtarXb-kfWPq-Ul3O2Ic3b8Y21Z3R8DzQ/edit#heading=h.x9snb54sjlu9)

**Comment by pitlv2109** [comment]
Thanks Yangmin!

**Comment by ymesika** [comment]
Close?

**Comment by pitlv2109** [comment]
@ymesika Not yet. Some PRs are not merged yet and there are some PRs coming in for this issue.

**Comment by pitlv2109** [comment]
Also Ports in ServiceRole and Ips in ServiceRoleBinding?

**Comment by yangminzhu** [comment]
@pitlv2109 Right

**Comment by pitlv2109** [comment]
All necessary PRs have been checked in to the `authz-v2` branch. Close issue.
