### ISSUE TITLE
Separate download site or cmd for istioctl

### ISSUE THREAD

**Issue by kramvan1** [istio/istio#11527]
**Describe the feature request**
Just like kubectl has, it would be great to have a simple curl to get the istioctl binar]y and not have to dig thru the installation files to get it.

For example, kubectl has this type of curl:
```
curl -o /usr/local/bin/kubectl --create-dirs --retry 5 -LO https://storage.googleapis.com/kubernetes-release/release/v${kubectl_version}/bin/linux/amd64/kubectl \
 && chmod +x /usr/local/bin/kubectl
```
which is very handy to use in Jobs and Dockerfiles....

**Describe alternatives you've considered**

**Additional context**

**Comment by kramvan1** [comment]
@linsun cc

**Comment by ymesika** [comment]
Would be great to have it homebrewed on Mac ;-)

**Comment by linsun** [comment]
@kramvan1 good point!

@ibm-jason can you look into this to see if we can host istioctl for 1.1 somewhere in our GitHub?

pre daily release: https://gcsweb.istio.io/gcs/istio-prerelease/daily-build/release-1.1-20190203-09-16/
released binary:   e.g.
https://github.com/istio/istio/releases/download/1.1.0-snapshot.5/istio-1.1.0-snapshot.5-linux.tar.gz

**Comment by ibm-jason** [comment]
@linsun Yes, I'll have a look. 👍

**Comment by ibm-jason** [comment]
@linsun here is something that we could try:

Using the `RAW` URL link to the file as it is hosted on GitHub, we can create subfolders to host the binary files right inside the repository itself. For example, https://raw.githubusercontent.com/istio/istio/master/istioctl/OWNERS is the download link to retrieve the `OWNERS` file from istio/istio. If we create a `releases/` subfolder in the `istio/istioctl` directory, and give Istio users the `RAW` URL link to the file, the binary could be accessed via `curl`.

Let me know if this approach is feasible, and I can prepare a PR for it.

**Comment by linsun** [comment]
@ibm-jason are you proposing to check in the binary to github?  If so, I would prefer not to do it.  It should be created as part of the release archive process imho but serve it as an individual item for downloading.

**Comment by ymesika** [comment]
Apparently we do have `istioctl` homebrew (currently v1.0.5).
Contributed by @murarisumit

**Comment by linsun** [comment]
Thank you @ymesika!

@ibm-jason could you ensure the istioctl homebrew is properly doced in istio.io?

**Comment by ibm-jason** [comment]
@linsun great idea, and yes, I'll make sure that it is properly documented.

**Comment by ymesika** [comment]
@ibm-jason ^^^

It's time to become an Istio member..

**Comment by ibm-jason** [comment]
@ymesika Perhaps you are right! :-)

**Comment by kramvan1** [comment]
@ibm-jason @linsun @ymesika I see this ISTIOCTL_URL floating around git hub, and it's also in the 
https://github.com/istio/istio/blob/master/tests/e2e_istio_preinstalled.sh (which I'm trying to make work)


`curl https://storage.googleapis.com/istio-artifacts/pilot/$TAG/artifacts/istioctl/istioctl-osx -o istioctl`

and similar for `istioctl-linux` and `istioctl-win.exe`

So, it appears to already be there.    I don't know what other TAGs are out there besides `latest`.  would this be good enough for this issue, just doc how to use this URL

**Comment by ibm-jason** [comment]
@linsun Circling back around on this issue. At this point, we're just finding a place to document how to separately download `istioctl`, including the brew install process?

**Comment by rvennam** [comment]
Right - is there a reliable URL we can use to download the istioctl binary for any release? If so, let's create a istio.io issue to doc it, and close this one

**Comment by linsun** [comment]
There isn't as far as i know as part of the release.  Can we do something simply like what is being discussed in https://github.com/istio/istio/pull/11710#issuecomment-479108038 where we append an option in our download istio script to download istioctl only?

We need 1 single cmd to download this thing regardless of platform.

**Comment by ibm-jason** [comment]
@linsun, @rvennam 

I talked with @utka about the following approach:

1. We can use the curl command to download istioctl separately, but it requires knowing the commit SHA for the release that you want to download: 
`curl https://storage.googleapis.com/istio-artifacts/pilot/$TAG/artifacts/istioctl/istioctl-osx -o istioctl`

`$TAG` in this case references a commit SHA, and from a UX perspective, having to know what SHA you need to download the version you want isn't user friendly.

2. Came up with the idea of using the same mechanism that publishes the artifacts to also publish a version where $TAG can be equal to the release version.  For example:

https://storage.googleapis.com/istio-artifacts/0961ac4a24d7bb0cd85612099a347e3b2d616946/artifacts/istioctl/istioctl-osx

This URL will give us the version of istioctl that was pushed when `0961ac4` was the HEAD commit (I'm guessing). What I'm proposing is the following:

https://storage.googleapis.com/istio-artifacts/1.1.2/artifacts/istioctl/istioctl-osx

3. We found where this is happening in the Makefile:

https://github.com/istio/istio/blob/fd96ebf6b28b707b825edbc60f992b1c720e3b60/Makefile#L613

We have the option of adding a new make target or adding a step in the `gcs.push.istioctl-all: istioctl-all` target that (in addition to the commit SHA version) pushes a version that simply has the release number in it.

I'll go with whichever approach is best, but @utka agrees that this could work.

**Comment by linsun** [comment]
Thanks @ibm-jason !  can we please not expose platform for users?  I'd rather we handle it automatically, like `curl -L https://git.io/getLatestIstio` does.

Can we have something like `curl -L https://git.io/getLatestIstioctl` to allow users to download istioctl, with the ability to optionally specify the version, e.g. ISTIO_VERSION=1.1.2?

**Comment by ibm-jason** [comment]
@linsun Yes, it makes sense not to directly expose the commit SHAs and platform to the user for this solution.

To answer your question, I think we can follow the same pattern as the `/getLatestIstio` URL. IIUC, `/getLatestistio` basically points to https://github.com/istio/istio/blob/master/release/downloadIstioCandidate.sh, which takes care of figuring out the platform and the appropriate version to download. I still think what we've proposed above is a good addition, we simply wrap it around a download script like the downloadIstioCandidate.sh script to *somewhat* obfuscate the logic.

**Comment by linsun** [comment]
SG thanks @ibm-jason !

**Comment by linsun** [comment]
Think this is mostly done however we need cmd and script to download istioctl, and update doc as needed.  Re-assign to @irisdingbj to pick it up from @ibm-jason.

**Comment by howardjohn** [comment]
Done #16922
