### ISSUE TITLE
mtls on default namespace fails with 503

### ISSUE THREAD

**Issue by quanjielin** [istio/istio#11536]
**Describe the bug**
Regression: serivce to service mtls fails with 503, only in default namespace, with sds enabled 

1. This problem didn't repro in https://gcsweb.istio.io/gcs/istio-prerelease/daily-build/release-1.1-20190130-09-16/; so it's a regression bug
2. This problem didn't repro https://github.com/istio/istio/commit/ce038fe2d60367f10c26a0da1be9e843934182c9, start in https://github.com/istio/istio/commit/f922392931b78b67fed4114f0d06f0727880eaea

**Steps to reproduce the bug**
[in dev env]
1. $ git reset --hard ce038fe2d60367f10c26a0da1be9e843934182c9
2. $ make build
3. $ make docker
4. $ make push
5. add below in makefile 
```
	cat install/kubernetes/namespace.yaml > install/kubernetes/istio-auth-sds.yaml
	cat install/kubernetes/helm/istio-init/files/crd-* >> install/kubernetes/istio-auth-sds.yaml
	$(HELM) template --set global.tag=${TAG} \
		--name=istio \
		--namespace=istio-system \
		--set global.hub=${HUB} \
		--set global.proxy.enableCoreDump=${ENABLE_COREDUMP} \
		--set istio_cni.enabled=${ENABLE_ISTIO_CNI} \
		${EXTRA_HELM_SETTINGS} \
		--values install/kubernetes/helm/istio/values-istio-sds-auth.yaml \
		install/kubernetes/helm/istio >> install/kubernetes/istio-auth-sds.yaml
```
6. $ make generate_yaml
7. $ kubectl create -f install/kubernetes/istio-auth-sds.yaml
8. $ kubectl apply -f <(~/go/out/linux_amd64/release/istioctl kube-inject -f samples/httpbin/httpbin.yaml)
9. $ kubectl apply -f <(~/go/out/linux_amd64/release/istioctl kube-inject -f samples/sleep/sleep.yaml)
10. $ for from in "default"; do for to in "default"; do kubectl exec $(kubectl get pod -l app=sleep -n ${from} -o jsonpath={.items..metadata.name}) -c sleep -n ${from} -- curl http://httpbin.${to}:8000/ip -s -o /dev/null -w "sleep.${from} to httpbin.${to}: %{http_code}\n"; done; done
sleep.default to httpbin.default: 200

11. repeat above steps in https://github.com/istio/istio/commit/f922392931b78b67fed4114f0d06f0727880eaea
for from in "default"; do for to in "default"; do kubectl exec $(kubectl get pod -l app=sleep -n ${from} -o jsonpath={.items..metadata.name}) -c sleep -n ${from} -- curl http://httpbin.${to}:8000/ip -s -o /dev/null -w "sleep.${from} to httpbin.${to}: %{http_code}\n"; done; done
```
sleep.default to httpbin.default: 503
```

12. however with https://github.com/istio/istio/commit/f922392931b78b67fed4114f0d06f0727880eaea, if creating httpbin/sleep in foo/bar ns, 
for from in "foo" "bar"; do for to in "foo" "bar"; do kubectl exec $(kubectl get pod -l app=sleep -n ${from} -o jsonpath={.items..metadata.name}) -c sleep -n ${from} -- curl http://httpbin.${to}:8000/ip -s -o /dev/null -w "sleep.${from} to httpbin.${to}: %{http_code}\n"; done; done
```
sleep.foo to httpbin.foo: 200
sleep.foo to httpbin.bar: 200
sleep.bar to httpbin.foo: 200
sleep.bar to httpbin.bar: 200
```

**Comment by quanjielin** [comment]
@diemtvu

**Comment by diemtvu** [comment]
The helm command enable global mTLS but not `global.controlPlaneSecurityEnabled`. I fixed the doc for this (https://github.com/istio/istio.io/pull/3198).

You can fix your setup by editing the `istio-policy` (and `istio-telemetry`) and adding this block under trafficPolicy

```
  trafficPolicy:
    connectionPool:
      http:
        http2MaxRequests: 10000
        maxRequestsPerConnection: 10000
    portLevelSettings:
    - port:
        number: 15004
      tls:
        mode: ISTIO_MUTUAL
```
You can also rerun the helm command and apply the new yaml
```
helm template install/kubernetes/helm/istio --name istio --namespace istio-system --set global.mtls.enabled=true --set global.controlPlaneSecurityEnabled=true >> $HOME/istio.yaml
```

In the long run, we need to deprecate this controlPlaneSecurityEnabled.

**Comment by diemtvu** [comment]
Digging deeper, the problem is related to the change https://github.com/istio/istio/pull/11153. That PR give the destination rule in the same namespace as the caller higher precedence. 

In the past, we have a 'global' DR (which `host=*.local`) under default namespace, that will be used for a service only when there is no other rule with *longer* name that also match to the service. Thus, if you define a rule specifically for mixer (`host=istio-policy.istio-system.svc.cluster.local`), that policy will be used for connecting to mixer.

After the PR above, DR in the same namespace as the caller will be picked first. Which mean if caller under `default` namespace, it will use the wild-card DR (that is defined in `default`). It cause the 503 as you see for client in `default`, as the TLS settings in the global DR is not the one expected.

**Comment by yangminzhu** [comment]
It looks like we should have some e2e tests to prevent such regression.

**Comment by quanjielin** [comment]
this issue goes away with https://github.com/istio/istio/pull/11546
