### ISSUE TITLE
Default limits values for initContainer caused regression on pod startup time

### ISSUE THREAD

**Issue by jnativio** [istio/istio#11534]
**Describe the bug**
The startup time for pods with injected sidecars had a big regression on 1.1. A single pod (no other app pods in the cluster) used to take around 4.8 sec to start on 1.0 but with a 1.1 or master build it is taking around 12 sec. The reason is that resources limits were introduced for the initContainer by PR #8409, and the hard coded default values seem to be very restrictive. 
The chart below shows the startup times using different values of `limits` for the proxy initContainer:

![image](https://user-images.githubusercontent.com/18554027/52300419-c4aad600-2955-11e9-95d2-ff9b11a51d5d.png)

It is not clear if the initContainer really needs limits defined (https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#resources), but if that is the case the default values should be changed to something like:
         ` limits:`
              `cpu: 100m`
              `memory: 50Mi`

**Expected behavior**
The startup of pod+sidecar should be as fast possible (knative requirement).

**Steps to reproduce the bug**
Measure the startup time of an injected pod with 1.1 build and compare with 1.0 build.

**Version**
Istio: release-1.1.snapshot.5
K8s: 1.10.11_1538

**Environment**
IKS, 4-node cluster.

**Comment by mandarjog** [comment]
Jose, this is a great find. Please submit a PR to 1.1 branch.  It seems that limit of 100m/50Mi as you suggest are good and they are backed by data.

**Comment by mandarjog** [comment]
@munrodg this is a regression with a simple fix, should go into 1.1
