### ISSUE TITLE
TestEds v2 is flaky

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#11542]
https://circleci.com/gh/istio/istio/317418?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

/cc @duderino

**Comment by ozevren** [comment]
https://circleci.com/gh/istio/istio/323089?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by ozevren** [comment]
costinm@, it looks like you have the most edits in the file.

**Comment by duderino** [comment]
@howardjohn note the P1

**Comment by howardjohn** [comment]
Haven't seen any issues with this one in a long time: https://testgrid.k8s.io/istio-postsubmits#unit-tests&width=5

I think it is safe to close.
