### ISSUE TITLE
New destination rule selection model break the assumption for 'global' destination rule.

### ISSUE THREAD

**Issue by diemtvu** [istio/istio#11545]
**Describe the bug**

For global mTLS enablement, we used to insert a *global* destination rule to enable mTLS on client side globally. This rule basically have the host match to any service (`*.local`), and used to have the lowest precedence (due to the logic based on the length of the host)

```
spec:
  host: '*.local'
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
```

[PR 1153](https://github.com/istio/istio/pull/11153) change the precedence based on namespace. So if caller in the same namespace of this destination rule (i.e `default`), that rule will be used regardless. In other words, [mixer specific policy](https://github.com/istio/istio/blob/release-1.1/install/kubernetes/helm/subcharts/mixer/templates/config.yaml#L972) will be ignored. If user use different TLS settings for control plane vs data plane, this could cause call to mixer fails, which in turn cause 503 on the service.

**Expected behavior**

The 'global' destination rule should have the least precedence.

**Steps to reproduce the bug**
{{ Minimal steps to reproduce the behavior }}

**Version**

Any build that have #/11153

**Installation**
Using helm template command with `global.mtls.enabled` set but not `global.controlPlaneSecurityEnabled`
```
helm template install/kubernetes/helm/istio --name istio --namespace istio-system --set global.mtls.enabled=true >> $HOME/istio.yaml
```

**Environment**
GKE

**Cluster state**
New.

**Comment by diemtvu** [comment]
One quick fix option (without rolling back) is moving the *global* DR to a non-default namespace. It's best to be a reserved namespace, which we asked user not running jobs in there, and/or add logic to consider policy in that namespace last.

**Comment by kyessenov** [comment]
FWIW, there is prior art in overriding pilot config specifically for mixer upstreams: https://github.com/istio/istio/blob/master/pilot/pkg/networking/plugin/mixer/mixer.go#L141

Something to consider if a workaround is needed.

**Comment by rshriram** [comment]
cc @louiscryan 
@diemtvu the istio-system is the right place for these mixer specific dest rules. That said, if someone overrides that rule in their local namespace with a *.local, then yes that rule will have precedence and things will break. However, its to be noted that such a *.local is not a common thing. People typically write dest rules for individual services. Or *.ns.svc.cluster.local . If someone explicitly creates such a wildcard rule, then its explicit intent to override.

Also, https://github.com/istio/istio/pull/11387 we do have a global istio-config namespace thats the root namespace.

The order of precedence is
 1. calling proxy's local namespace first - within this namespace, pick longest matching dest rule
 2. the destination service's namespace next - within this namespace, only pick rules that have exportTo set to *, and pick longest matching dest rule
 3. The root namespace next - same as 2.

**Comment by duderino** [comment]
@diemtvu @rshriram @costinm 

Can we live with this bug for 1.1?  Should it be documented in the release notes?
