### ISSUE TITLE
Replacement for deprecated istioctl get custom columns

### ISSUE THREAD

**Issue by esnible** [istio/istio#11552]
`istioctl get` provides information not provided by `kubectl get`.  Examples:

```
istioctl get gateways
GATEWAY NAME       HOSTS     NAMESPACE   AGE
bookinfo-gateway   *         default     11d
```
vs
```
kubectl get gateways
NAME               CREATED AT
bookinfo-gateway   11d
```

```
istioctl get virtualservices
VIRTUAL-SERVICE NAME   GATEWAYS           HOSTS     #HTTP     #TCP      NAMESPACE   AGE
bookinfo               bookinfo-gateway   *             1        0      default     11d
```
vs
```
kubectl get virtualservices
NAME       CREATED AT
bookinfo   11d
```

```
istioctl get destinationrule
DESTINATION-RULE NAME   HOST                                   SUBSETS   NAMESPACE   AGE
api-server              kubernetes.default.svc.cluster.local             default     1d
default                 *.local                                          default     1d
```
vs
```
kubectl get destinationrule
NAME         CREATED AT
api-server   1d
default      1d
```

```
istioctl get serviceentry make-aptget-work
SERVICE-ENTRY NAME   HOSTS                                                                                                 PORTS     NAMESPACE   AGE
make-aptget-work     deb.debian.org,cdn-fastly.deb.debian.org,security.debian.org,archive.ubuntu.com,security.ubuntu.com   HTTP/80   default     15d
```
vs
```
kubectl get serviceentry make-aptget-work
NAME               CREATED AT
make-aptget-work   15d
```

This work item is to bring as much of the useful columns provided by istioctl into kubectl using https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#additional-printer-columns feature of Kubernetes.

**Comment by esnible** [comment]
I did an initial sizing of this effort and ran into a problem.  Most of our CRD fields displayed in _istioctl_ are arrays not simple strings.

Although additionalPrinterColumns takes a JSONPath, it ignores anything beyond the first value.  For example, for ServiceEntries I added

```
  additionalPrinterColumns:
  - name: Hosts
    type: string
    description: Destination Hosts
    JSONPath: .spec.hosts[*]
```

But _kubectl_ only displayed the first value:

```
$ kubectl get serviceentry
NAME               HOSTS            PORTS     AGE
make-aptget-work   deb.debian.org   80        21m
kubectl get serviceentry make-aptget-work -o jsonpath='{.spec.hosts[*]}'
deb.debian.org cdn-fastly.deb.debian.org security.debian.org archive.ubuntu.com security.ubuntu.com
```
(missing 

@ayj @fisherxu I have not been able to find a way to show lists using additionalPrinterColumns.  One idea is to have Pilot generate .status on the custom resources.  For example Pilot could create `.status.hosts` which would just be `.spec.hosts.join(",")`.  I could print that.  Otherwise I am stuck.  Any ideas?

**Comment by ayj** [comment]
> But _kubectl_ only displayed the first value:

This is a known issue with server-side custom columns. See https://github.com/kubernetes/kubectl/issues/517 and the proposed [fix](https://github.com/kubernetes/kubernetes/pull/67079).

cc @seans3

**Comment by esnible** [comment]
@ayj For 1.1 does it make sense to add additionalPrinterColumns even though the output will only show the first entry?  90% or more of Istio Yaml only refers to one host, one tag, etc.

(An Istio 1.2+ implementation can attempt to show all of the values of the array fields using the Kubernetes fix or using the status hack I proposed.)

**Comment by ayj** [comment]
Per our offline discussion, @esnible's suggestion to create columns only for things we can show accurately SGTM. For example, DestinationRule shows the list of hosts in array notation, but VirtualService does not. The intent would be to adjust the custom columns as upstream k8s support improves.

**Comment by esnible** [comment]
Background: custom columns require no code, just additional fields in the CRD.
I have a demo of custom columns.  Please try it out.  If the CRDs you use have too much or two little data please attach your feedback.

To set up:
```
kubectl patch crd virtualservices.networking.istio.io \
 -p '{"spec":{"additionalPrinterColumns":[
    {"name": "Gateways", "type": "string", "description": "TODO", "JSONPath": ".spec.gateways"},
    {"name": "Hosts", "type": "string", "description": "TODO", "JSONPath": ".spec.hosts"},
    {"name": "Age", "type": "date", "description": "TODO", "JSONPath": ".metadata.creationTimestamp" }
 ]}}'
kubectl patch crd serviceentries.networking.istio.io \
 -p '{"spec":{"additionalPrinterColumns":[
     {"name": "Hosts", "type": "string", "description": "TODO", "JSONPath": ".spec.hosts"},
     {"name": "Location", "type": "string", "description": "TODO", "JSONPath": ".spec.location"},
     {"name": "Resolution", "type": "string", "description": "TODO", "JSONPath": ".spec.resolution"},
     {"name": "Age", "type": "date", "description": "TODO", "JSONPath": ".metadata.creationTimestamp" }
 ]}}'
kubectl patch crd destinationrules.networking.istio.io \
 -p '{"spec":{"additionalPrinterColumns":[
    {"name": "Host", "type": "string", "description": "TODO", "JSONPath": ".spec.host"},
     {"name": "Age", "type": "date", "description": "TODO", "JSONPath": ".metadata.creationTimestamp" }
 ]}}'
kubectl patch crd servicerolebindings.rbac.istio.io \
 -p '{"spec":{"additionalPrinterColumns":[
    {"name": "Mode", "type": "string", "description": "TODO", "JSONPath": ".spec.mode"},
    {"name": "Reference", "type": "string", "description": "TODO", "JSONPath": ".spec.roleRef.name"},
     {"name": "Age", "type": "date", "description": "TODO", "JSONPath": ".metadata.creationTimestamp" }
 ]}}'
kubectl patch crd clusterrbacconfigs.rbac.istio.io \
 -p '{"spec":{"additionalPrinterColumns":[
    {"name": "Mode", "type": "string", "description": "TODO", "JSONPath": ".spec.mode"},
    {"name": "Enforcement", "type": "string", "description": "TODO", "JSONPath": ".spec.enforcement_mode"},
    {"name": "Namespaces", "type": "string", "description": "TODO", "JSONPath": ".spec.inclusion.namespaces"},
     {"name": "Age", "type": "date", "description": "TODO", "JSONPath": ".metadata.creationTimestamp" }
 ]}}'
kubectl patch crd logentries.config.istio.io \
 -p '{"spec":{"additionalPrinterColumns":[
    {"name": "Severity", "type": "string", "description": "TODO", "JSONPath": ".spec.severity"},
    {"name": "Timestamp", "type": "string", "description": "TODO", "JSONPath": ".spec.timestamp"},
    {"name": "Res Type", "type": "string", "description": "TODO", "JSONPath": ".spec.monitored_resource_type"},
     {"name": "Age", "type": "date", "description": "TODO", "JSONPath": ".metadata.creationTimestamp" }
 ]}}'
```

To run the demo:

```
kubectl apply -f samples/bookinfo/platform/kube/rbac/productpage-policy.yaml
kubectl apply -f samples/bookinfo/platform/kube/rbac/rbac-config-on-permissive.yaml
kubectl apply -f samples/bookinfo/networking/bookinfo-gateway.yaml
kubectl apply -f samples/bookinfo/networking/virtual-service-all-v1.yaml
kubectl apply -f samples/bookinfo/platform/kube/rbac/rbac-permissive-telemetry.yaml

kubectl get gateways,virtualservices,destinationrules,serviceentries,servicerolebindings,clusterrbacconfigs
kubectl -n istio-system get logentries
```

**Comment by linsun** [comment]
@esnible getting this error when applying the CRDs.

`Error from server (NotFound): customresourcedefinitions.apiextensions.k8s.io "clusterrbacconfigs.rbac.istio.io" not found`

think this one is already deprecated.... to rbacconfig?   Or perhaps because my env is using 1.0.... let me switch to 1.1

**Comment by esnible** [comment]
@linsun clusterrbacconfigs is defined in _install/kubernetes/helm/istio-init/files/crd-10.yaml_.  It was added to 1.0 back in September.  It is used in _samples/bookinfo/platform/kube/rbac/rbac-config-on-mongodb.yaml_ in the 1.1 release.

I created https://github.com/istio/istio.io/issues/3214 to discuss the lack of documentation for it on preliminary.istio.io.  We need to either document it, or get it out of samples.

Horror.  There is also a rbacconfigs.rbac.istio.io defined, with neither docs nor samples.

**Comment by linsun** [comment]
cc @liminw ^^

**Comment by esnible** [comment]
@linsun You are free to ignore any error messages from the patch, especially from resource types you never used.

If we like the `kubectl` output the patches demonstrate then it is easy to just add the JSON from the patch to _/install/kubernetes/helm/istio-init/files/crd-10.yaml_.  No code needs to be written.  It would be a nice feature to have in 1.1.0 or 1.1.1.

**Comment by liminw** [comment]
ClusterRbacConfig is documented in https://preliminary.istio.io/docs/concepts/security/#enabling-authorization. 

ClusterRbacConfig replaces RbacConfig (which has the wrong scope). There is a migration guide https://preliminary.istio.io/docs/setup/kubernetes/upgrading-istio#migrating-the-rbacconfig-to-clusterrbacconfig. 

@esnible Is there other documentation you refer to?

/cc @yangminzhu

**Comment by esnible** [comment]
@liminw I missed ClusterRbacConfig in the documentation because I looked for it with the Search feature.  It is not searchable.

**Comment by linsun** [comment]
@liminw thanks.  yes unfortunately our 1.1 doc isn't searchable right now which makes it very hard to find anything.  

We probably should note this as the release note:  ClusterRbacConfig replaces RbacConfig

cc @geeknoid

**Comment by yangminzhu** [comment]
@linsun We have added it here: https://preliminary.istio.io/about/notes/1.1/#security

**Comment by linsun** [comment]
@esnible I ran the scripts, the output is way much better improved in kubectl.  This will help user a lot especially we are trying to ask users to use kubectl in most if not all cases.

**Comment by munrodg** [comment]
@esnible can this be closed?
