### ISSUE TITLE
Test failure: Upgrade test is failing due to validation of ExportTo by the Admission Webhook

### ISSUE THREAD

**Issue by ozevren** [istio/istio#11555]
https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio-releases_pipeline/287/release-upgrade-tests-1.0.1/314
```
Error from server: error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"networking.istio.io/v1alpha3\",\"kind\":\"DestinationRule\",\"metadata\":{\"annotations\":{},\"labels\":{\"app\":\"mixer\",\"chart\":\"mixer\",\"heritage\":\"Tiller\",\"release\":\"istio\"},\"name\":\"istio-policy\",\"namespace\":\"istio-system\"},\"spec\":{\"exportTo\":[\"*\"],\"host\":\"istio-policy.istio-system.svc.cluster.local\",\"trafficPolicy\":{\"connectionPool\":{\"http\":{\"http2MaxRequests\":10000,\"maxRequestsPerConnection\":10000}}}}}\n"},"labels":{"app":"mixer","chart":"mixer","heritage":"Tiller","release":"istio"}},"spec":{"exportTo":["*"]}}
to:
&{0xc42051a6c0 0xc420536e70 istio-system istio-policy /home/prow/go/src/istio.io/istio/istio.yaml 0xc42000c0e0 42070 false}
for: "/home/prow/go/src/istio.io/istio/istio.yaml": admission webhook "pilot.validation.istio.io" denied the request: error decoding configuration: YAML decoding error: exportTo:
- '*'
host: istio-policy.istio-system.svc.cluster.local
trafficPolicy:
  connectionPool:
    http:
      http2MaxRequests: 10000
      maxRequestsPerConnection: 10000
 unknown field "exportTo" in v1alpha3.DestinationRule
Error from server: error when applying patch
```

There are 503s that might be related in the same run as well:
```
10:23:16 E http_client.go:542> Unable to connect to 35.245.152.251:80 : dial tcp 35.245.152.251:80: connect: no route to host
10:23:16 E http_client.go:542> Unable to connect to 35.245.152.251:80 : dial tcp 35.245.152.251:80: connect: no route to host
10:23:18 W http_client.go:679> Parsed non ok code 503 (HTTP/1.1 503)
10:23:18 W http_client.go:679> Parsed non ok code 503 (HTTP/1.1 503)
10:23:18 W http_client.go:679> Parsed non ok code 503 (HTTP/1.1 503)
10:23:18 W http_client.go:679> Parsed non ok code 503 (HTTP/1.1 503)
10:23:19 W http_client.go:679> Parsed non ok code 503 (HTTP/1.1 503)
10:23:19 W http_client.go:679> Parsed non ok code 503 (HTTP/1.1 503)
10:23:19 W http_client.go:679> Parsed non ok code 503 (HTTP/1.1 503)
10:23:19 W http_client.go:679> Parsed non ok code 503 (HTTP/1.1 503)
10:23:19 W http_client.go:679> Parsed non ok code 503 (HTTP/1.1 503)
10:23:19 W http_client.go:679> Parsed non ok code 503 (HTTP/1.1 503)
10:23:19 W http_client.go:679> Parsed non ok code 503 (HTTP/1.1 503)
10:23:19 W http_client.go:679> Parsed non ok code 503 (HTTP/1.1 503)
10:23:19 W http_client.go:679> Parsed non ok code 503 (HTTP/1.1 503)
10:23:19 W http_client.go:679> Parsed non ok code 503 (HTTP/1.1 503)
10:23:19 W http_client.go:679> Parsed non ok code 503 (HTTP/1.1 503)
```

**Comment by ozevren** [comment]
It looks like this could be due to older version of Galley handling the validation call.

**Comment by ozevren** [comment]
There is another instance here:
https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio-releases_pipeline/287/release-upgrade-tests-1.0.1/313

**Comment by ayj** [comment]
https://github.com/istio/istio/pull/11507 added explicit `exportTo: '*'` to the DestinationRules in the default Istio control plane configuration. This configuration is updated at the same time as the control plane itself. At the same time, our validation rejects unknown fields. This leads to combinations where the new configuration is sent to the old validation webhook which rejects it. 

Some possible solutions:

1) relax validation to ignore unknown fields.
2) remove `exportTo: "*'` from the CP config. If unspecified, this field defaults to "export to all namespaces" anyway.
3) improve sequencing of install (e.g. update control plane and then upgrade config).

(1) increases the chance of operator error in the normal case. e.g. a misspelled field in auth policy leads results in an insecure service.

(2) would address the immediate problem. It's also probably the right advise to follow in the future.

(3) would be nice but probably not achievable for 1.1. This level of control would also help orchestrating upgrades between Galley and Pilot.

**Comment by ayj** [comment]
cc @rshriram  - re: option (2) above

**Comment by rshriram** [comment]
I added that explicitly because we now have a global export option that could be set to . or *. If someone sets the global export option to ., then dest rules for policy and telemetry wont be visible to anyone.. all sidecars start calling mixer with plain text and calls fail.

Put another way, you will have this problem if someone changes the global exportTo to . and tries to upgrade. That said, changing the global exportTo to . (local namespace only) is a serious change by end user who is aware that things in his infrastructure might break badly. But its not a bad thing for someone starting a "fresh" istio install.

For now, we could do the following:
 guard the exportTo in CP using a condition like "if globalExportTo is *, skip the local exportTo" else add the local exportTo. This should work for people upgrading..

I wish we had a isUpgrade flag in helm. sigh..

**Comment by sdake** [comment]
3 is not achievable in 1.1 timeframe without serious risk to the delivery.  I did consider breaking the config into a third chart back when istio-init was broken into a separate chart, but decided not to, as was already getting pushback about the number of steps.  Guess I should have done it anyway :)

For this particular DR, we could add a special case that applies it "later" by adding a DR application job.  This is pretty straightforward.  This would make the DR an unmanaged helm object, which has implications for future removal.  If we can confirm this DR isn't going anywhere, then it doesn't matter.

**Comment by rshriram** [comment]
The DRs for istio-policy and istio-telemetry are not going anywhere.

**Comment by sdake** [comment]
if the DRs are not present immediately after installation, do bad things happen?

There are two scenarios:

- install: everything gets installed, then the DRs are appied 3-10 seconds later
- upgrade: everything IS installed, an upgrade occurs, then the new DRs get applied 3-10 seconds later

Is this solution viable for the use case?  I am not sure precisely how these DRs are used so asking the experts :)

Cheers
-steve

**Comment by sdake** [comment]
@ayj @douglas-reid any idea on the above approach?

**Comment by dwradcliffe** [comment]
I attempted to upgrade snapshot.5 to snapshot.6 on a test cluster and came across this as well.

**Comment by sdake** [comment]
@dwradcliffe ya we will solve this problem - upgrade breakers are no good.

**Comment by sdake** [comment]
@duderino I moved this to new issues as I believe this should be a blocker (P0) for the release.  Depending on the speed of people's gear and timing factors, upgrades will sometimes fail.

**Comment by ayj** [comment]
AFAICT, DR are used for 3 purposes: 

1) all traffic to *.global uses mTLS
2) access to policy/telemetry uses mTLS
3) access to k8s apiserver _doesn't_ use mTLS

(1) seems to be used by multi-cluster / gateways cc @costinm 

(2) would cause policy checks to fail and telemetry to be delayed/dropped cc @douglas-reid 

(3) would temporarily break k8s client that is trying to access the k8s apiserver. One would hope app code would be resilient to this type of "transient" failure, but it could be fairly disruptive for the initial install.

I think (1), (2), and (3) are mostly an issue during install. Upgrade would be an issue if the user changed the default export/visibility option (see @rshriram's concerns with my original suggestion above). 

> For now, we could do the following:
guard the exportTo in CP using a condition like "if globalExportTo is *, skip the local exportTo" else add the local exportTo. This should work for people upgrading.

I think `globalExportTo` is referring to `defaultConfigVisibilitySettings` in values.yaml. This _might_ work for cases where users treat helm as the only Istio install/upgrade API. There may still be time gaps where config is mismatched between the global and DR specific rules.

**Comment by duderino** [comment]
@sdake doing the work.  @costinm will advise

**Comment by linsun** [comment]
@costinm @sdake with the new backwards compatible flag we just discussed in env WG, can we guard @rshriram 's change in the PR with the flag to fix this?

https://github.com/istio/istio/pull/11507/files

**Comment by duderino** [comment]
nevermind, @costinm is going to do all the work

**Comment by costinm** [comment]
I think new alpha features should be off by default and not used if it prevents upgrade/downgrade - we can enable them for fresh installs if we have time to add that, but in this case it may be safe to just not set it.
