### ISSUE TITLE
[Authz v2] Add e2e test for Authz v2

### ISSUE THREAD

**Issue by yangminzhu** [istio/istio#11564]
**Describe the feature request**
E2E test is very important to prevent any regressions, we will need to update the current ones for the upcoming Authz v2 support.

/cc @pitlv2109 

**Additional context**
[Istio Authorization v2 design](https://docs.google.com/document/d/1diwa9oYVwmLtarXb-kfWPq-Ul3O2Ic3b8Y21Z3R8DzQ/edit#heading=h.x9snb54sjlu9)

**Comment by pitlv2109** [comment]
Close this one. Tracker for Authz v2 is here https://github.com/istio/istio/issues/12394
