### ISSUE TITLE
[Authz v2] Support AuthorizationPolicy

### ISSUE THREAD

**Issue by yangminzhu** [istio/istio#11569]
**Describe the feature request**
We'll need to add a new CRD `AuthorizationPolicy` that is used to grant permissions to users.

Note it's risky to start to work on the `master` branch right now as the potential change will affect a lot of parts in Pilot and Galley. The `master` is still quite diverged from the 1.1 branch and there is a possibility that 1.2 will be based off 1.1 and not master.

**Additional context**
[Istio Authorization v2 design](https://docs.google.com/document/d/1diwa9oYVwmLtarXb-kfWPq-Ul3O2Ic3b8Y21Z3R8DzQ/edit#heading=h.x9snb54sjlu9)

**Comment by pitlv2109** [comment]
Checked in PR #12050. 
@yangminzhu Should we close or wait until the Galley part is done?

**Comment by yangminzhu** [comment]
Closing this one for now, will reopen after the API is ready.
