### ISSUE TITLE
Newly added RecordComponentBuildTag breaks make in mac os

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#11573]
This is only defined for Linux.

pilot/pkg/bootstrap/monitoring.go:82:14: "istio.io/istio/pkg/version".Info.RecordComponentBuildTag undefined (type "istio.io/istio/pkg/version".BuildInfo has no field or method RecordComponentBuildTag)

**Comment by douglas-reid** [comment]
This was already fixed by a PR: #11327.

And was tracked by a prior bug: #10725 .  Do we need another bug?

**Comment by andraxylia** [comment]
Nope. The title of that fix did not ring a bell, hence the new issue.
