### ISSUE TITLE
Pilot is using a static generated cacert to fetch JWT public key

### ISSUE THREAD

**Issue by yangminzhu** [istio/istio#11577]
**Describe the bug**
When JWT policy is used, Pilot is responsible to fetch the public key and distribute to Envoy. When fetching the public key, the public key is usually fetched from a HTTPS endpoint which means Pilot needs to verify the certificate of this HTTPS endpoint.

Currently Pilot is using a manually generated static CA bundle to do the verification:
https://github.com/istio/istio/blob/392be6637545b7df6c8a6c04ac29685c7aba615d/pilot/pkg/model/jwks_resolver.go#L65

https://github.com/istio/istio/blob/35ec73eff13fcc93decee31fabe80a7f5aacd743/tests/testdata/certs/cacert.pem#L2

**Expected behavior**
I'm not sure what's the best option here, but we should avoid using a static CA bundle as it doesn't scale well:
- It doesn't handle well if a root certificate is revoked, or if there is a new root certificate added
- The cacert.perm is placed under the testdata which seems indicating it's only for test purpose, but actually it's used in production

**Version**
1.1

/cc @quanjielin @liminw @diemtvu @kyessenov I'm wondering is it a temporary workaround to use the static ca bundle? or is it something standard to follow? Thank you.

**Comment by quanjielin** [comment]
today we baked Ubuntu CA bundle into pilot docker image, ideally we should put something below in pilot docker file get fetch it dynamically(see [nodeagent example](https://github.com/istio/istio/blob/release-1.1/security/docker/Dockerfile.node-agent-k8s#L3))

```
RUN apt-get update && apt-get install -y ca-certificates
```

**Comment by yangminzhu** [comment]
@quanjielin Are there any problems blocking us to do it now?

**Comment by quanjielin** [comment]
No, should be a small change.

**Comment by kyessenov** [comment]
Sounds fine, but put the docker command into the daily base image. apt-get will cause build flakiness if you run it on every PR.
