### ISSUE TITLE
Disabling Observability data generation for specific micro-services in the Mesh

### ISSUE THREAD

**Issue by nadundesilva** [istio/istio#11582]
**Describe the feature request**
Currently Istio pushes the same Telemetry and Tracing configurations to the Envoy Sidecars and we can only control the Telemetry and Tracing configuration as a whole.

However, in a real world scenario, there could be micro-services with different perf requirements (including the data flow through the sidecars as they have an impact on the actual round-trip time) in the same Mesh. Therefore, there is a requirement to disable Telemetry and Tracing (and possibly other functionality) for specific micro-services.

In the current project I am working on, we have a mix of micro-services in the same cluster, where some of them have tight Perf Requirements (I would prefer to disable some of the unwanted functionality in these micro-service sidecars while having mTLS and some other features) while the majority of micro-services require most of the awesome benefits provided by Istio.

I do understand that this might complicate the design of Istio. However, I would like to explore the possibility of introducing such a capability.

**Describe alternatives you've considered**
- Discarding Telemetry at Mixer level could be a solution to reducing the collected data. However it would not address switching off the Observability data generation as per the micro-service level Perf Requirements.

**Comment by kyessenov** [comment]
/cc @mandarjog 
/cc @douglas-reid 

I can imagine a knob on _services_ that can control mixerfilter telemetry collection at the proxy. This works better than pod-bound knobs due to client-side telemetry cost spread across many pods for a service. We can attach the control to a virtual service / service.

**Comment by esnible** [comment]
See https://github.com/istio/istio/pull/11398 for a PR that includes a knob for controlling the performance stats collection by Envoy.  This is not related to the mixer telemetry; it is an additional knob for observability vs performance.

**Comment by kyessenov** [comment]
I'd like to add that istio policy has a pod-level annotations for control. Since we generally do not enable client-side policy checks, that is probably sufficient. Gateways run as separate pods, and also accept the policy control annotation.
