### ISSUE TITLE
Auto sidecar injection 

### ISSUE THREAD

**Issue by daparthi001** [istio/istio#11611]
Unable to inject auto sidecar injection ,can some can suggest what is causing auto inject fail .

 systemctl status kube-apiserver -l
● kube-apiserver.service - Kubernetes API Server
   Loaded: loaded (/etc/systemd/system/kube-apiserver.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2019-02-07 18:13:20 EST; 3h 56min ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
 Main PID: 11845 (kube-apiserver)
   CGroup: /system.slice/kube-apiserver.service
           └─11845 /usr/local/bin/kube-apiserver --admission-control=DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,Initializers,LimitRanger,NamespaceExists,NamespaceLifecycle,NodeRestriction,PodPreset,ResourceQuota,ServiceAccount --advertise-address=10.74.80.163 --allow-privileged=true --apiserver-count=3 --audit-log-maxage=30 --audit-log-maxbackup=3 --audit-log-maxsize=100 --audit-log-path=/var/log/k8s-audit/audit.log --audit-policy-file=/etc/kubernetes/audit-policy.yaml --authorization-mode=Node,RBAC --client-ca-file=/etc/pki/ca-trust/source/anchors/kubernetes-ca.pem --enable-swagger-ui=true --etcd-cafile=/etc/pki/ca-trust/source/anchors/kubernetes-ca.pem --etcd-certfile=/etc/kubernetes/kube-master.pem --etcd-keyfile=/etc/kubernetes/kube-master-key.pem --etcd-servers=https://istio.aws-us-east-1c-green.kube-dev.com:2379 --experimental-encryption-provider-config=/etc/kubernetes/etcd-encryption-config.yaml --feature-gates=SupportPodPidsLimit=true --kubelet-certificate-authority=/etc/pki/ca-trust/source/anchors/kubernetes-ca.pem --kubelet-client-certificate=/etc/kubernetes/kube-master.pem --kubelet-client-key=/etc/kubernetes/kube-master-key.pem --runtime-config=api/all,settings.k8s.io/v1alpha1=true --secure-port=443 --service-account-key-file=/etc/kubernetes/kube-master-sa.pem --service-cluster-ip-range=192.168.0.0/16 --service-node-port-range=30000-32767 --tls-ca-file=/etc/pki/ca-trust/source/anchors/kubernetes-ca.pem --tls-cert-file=/etc/kubernetes/kube-master.pem --tls-private-key-file=/etc/kubernetes/kube-master-key.pem

[11845]: Trace[1888485769]: [30.000599484s] [30.000554727s] END
[11845]: W0207 22:10:09.059333   11845 admission.go:248] Failed calling webhook, failing closed sidecar-injector.istio.io: failed calling admission webhook "sidecar-injector.istio.io": Post https://istio-sidecar-injector.istio-system.svc:443/inject?timeout=30s: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
[11845]: I0207 22:10:09.059525   11845 trace.go:76] Trace[19227134]: "Create /api/v1/namespaces/default/pods" (started: 2019-02-07 22:09:39.058991548 -0500 EST m=+14178.351684797) (total time: 30.000516271s):
[11845]: Trace[19227134]: [30.000516271s] [30.000471988s] END
[11845]: W0207 22:10:09.062887   11845 admission.go:248] Failed calling webhook, failing closed sidecar-injector.istio.io: failed calling admission webhook "sidecar-injector.istio.io": Post https://istio-sidecar-injector.istio-system.svc:443/inject?timeout=30s: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
[11845]: I0207 22:10:09.063061   11845 trace.go:76] Trace[1868180010]: "Create /api/v1/namespaces/default/pods" (started: 2019-02-07 22:09:39.062348849 -0500 EST m=+14178.355042095) (total time: 30.00069612s):
[11845]: Trace[1868180010]: [30.00069612s] [30.000615712s] END
[11845]: W0207 22:10:09.076249   11845 admission.go:248] Failed calling webhook, failing closed sidecar-injector.istio.io: failed calling admission webhook "sidecar-injector.istio.io": Post https://istio-sidecar-injector.istio-system.svc:443/inject?timeout=30s: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
[11845]: I0207 22:10:09.076421   11845 trace.go:76] Trace[657312675]: "Create /api/v1/namespaces/default/pods" (started: 2019-02-07 22:09:39.075870947 -0500 EST m=+14178.368564190) (total time: 30.000535584s):
[11845]: Trace[657312675]: [30.000535584s] [30.000502175s] END

kubectl get deployment
NAME             DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
details-v1       1         0         0            0           8m
productpage-v1   1         0         0            0           8m
ratings-v1       1         0         0            0           8m
reviews-v1       1         0         0            0           8m
reviews-v2       1         0         0            0           8m
reviews-v3       1         0         0            0           8m

kubectl get svc
NAME          TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
details       ClusterIP   192.168.67.58    <none>        9080/TCP   8m
kubernetes    ClusterIP   192.168.0.1      <none>        443/TCP    3d
productpage   ClusterIP   192.168.100.20   <none>        9080/TCP   8m
ratings       ClusterIP   192.168.218.9    <none>        9080/TCP   8m
reviews       ClusterIP   192.168.231.77   <none>        9080/TCP   8m

ubectl describe deployment details-v1
Name:                   details-v1
Namespace:              default
CreationTimestamp:      Thu, 07 Feb 2019 22:07:08 -0500
Labels:                 app=details
                        version=v1
Annotations:            deployment.kubernetes.io/revision=1
                        kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"name":"details-v1","namespace":"default"},"spec":{"replicas":1,"te...
Selector:               app=details,version=v1
Replicas:               1 desired | 0 updated | 0 total | 0 available | 1 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  1 max unavailable, 1 max surge
Pod Template:
  Labels:  app=details
           version=v1
  Containers:
   details:
    Image:        istio/examples-bookinfo-details-v1:1.8.0
    Port:         9080/TCP
    Host Port:    0/TCP
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Conditions:
  Type             Status  Reason
  ----             ------  ------
  Progressing      True    NewReplicaSetCreated
  Available        True    MinimumReplicasAvailable
  ReplicaFailure   True    FailedCreate
OldReplicaSets:    <none>
NewReplicaSet:     details-v1-6865b9b99d (0/1 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  9m    deployment-controller  Scaled up replica set details-v1-6865b9b99d to 1

kubectl get namespace -L istio-injection
NAME               STATUS    AGE       ISTIO-INJECTION
default            Active    3d        enabled
istio-system       Active    20m       disabled
kube-ops           Active    3d
kube-public        Active    3d
kube-system        Active    3d

**Comment by esnible** [comment]
Is your Sidecar Injector running?  `kubectl -n istio-system get pods | grep sidecar-injector` to check.

**Comment by daparthi001** [comment]
# kubectl -n istio-system get pods | grep sidecar-injector
istio-sidecar-injector-7f4c7db98c-b44lj   1/1       Running     3          12h
 # kubectl logs istio-sidecar-injector-7f4c7db98c-b44lj -n istio-system
2019-02-08T15:56:20.025773Z     info    version root@6f6ea1061f2b-docker.io/istio-1.0.5-c1707e45e71c75d74bf3a5dec8c7086f32f32fad-Clean
2019-02-08T15:56:20.029051Z     info    New configuration: sha256sum b495ef307da0812876d8b2e252a58f7116737bd143b4b85276486e26a233039c
2019-02-08T15:56:20.029073Z     info    Policy: enabled
2019-02-08T15:56:20.029103Z     info    Template: |
  initContainers:
  - name: istio-init
    image: "docker.io/istio/proxy_init:1.0.5"
    args:
    - "-p"
    - [[ .MeshConfig.ProxyListenPort ]]
    - "-u"
    - 1337
    - "-m"
    - [[ annotation .ObjectMeta `sidecar.istio.io/interceptionMode` .ProxyConfig.InterceptionMode ]]
    - "-i"
    - "[[ annotation .ObjectMeta `traffic.sidecar.istio.io/includeOutboundIPRanges`  "*"  ]]"
    - "-x"
    - "[[ annotation .ObjectMeta `traffic.sidecar.istio.io/excludeOutboundIPRanges`  ""  ]]"
    - "-b"
    - "[[ annotation .ObjectMeta `traffic.sidecar.istio.io/includeInboundPorts` (includeInboundPorts .Spec.Containers) ]]"
    - "-d"
    - "[[ excludeInboundPort (annotation .ObjectMeta `status.sidecar.istio.io/port`  0 ) (annotation .ObjectMeta `traffic.sidecar.istio.io/excludeInboundPorts`  "" ) ]]"
    imagePullPolicy: IfNotPresent
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
      privileged: true
    restartPolicy: Always
  containers:
  - name: istio-proxy
    image: [[ annotation .ObjectMeta `sidecar.istio.io/proxyImage`  "docker.io/istio/proxyv2:1.0.5"  ]]

    ports:
    - containerPort: 15090
      protocol: TCP
      name: http-envoy-prom

    args:
    - proxy
    - sidecar
    - --configPath
    - [[ .ProxyConfig.ConfigPath ]]
    - --binaryPath
    - [[ .ProxyConfig.BinaryPath ]]
    - --serviceCluster
    [[ if ne "" (index .ObjectMeta.Labels "app") -]]
    - [[ index .ObjectMeta.Labels "app" ]]
    [[ else -]]
    - "istio-proxy"
    [[ end -]]
    - --drainDuration
    - [[ formatDuration .ProxyConfig.DrainDuration ]]
    - --parentShutdownDuration
    - [[ formatDuration .ProxyConfig.ParentShutdownDuration ]]
    - --discoveryAddress
    - [[ annotation .ObjectMeta `sidecar.istio.io/discoveryAddress` .ProxyConfig.DiscoveryAddress ]]
    - --discoveryRefreshDelay
    - [[ formatDuration .ProxyConfig.DiscoveryRefreshDelay ]]
    - --zipkinAddress
    - [[ .ProxyConfig.ZipkinAddress ]]
    - --connectTimeout
    - [[ formatDuration .ProxyConfig.ConnectTimeout ]]
    - --proxyAdminPort
    - [[ .ProxyConfig.ProxyAdminPort ]]
    [[ if gt .ProxyConfig.Concurrency 0 -]]
    - --concurrency
    - [[ .ProxyConfig.Concurrency ]]
    [[ end -]]
    - --controlPlaneAuthPolicy
    - [[ annotation .ObjectMeta `sidecar.istio.io/controlPlaneAuthPolicy` .ProxyConfig.ControlPlaneAuthPolicy ]]
  [[- if (ne (annotation .ObjectMeta `status.sidecar.istio.io/port`  0 ) "0") ]]
    - --statusPort
    - [[ annotation .ObjectMeta `status.sidecar.istio.io/port`  0  ]]
    - --applicationPorts
    - "[[ annotation .ObjectMeta `readiness.status.sidecar.istio.io/applicationPorts` (applicationPorts .Spec.Containers) ]]"
  [[- end ]]
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: INSTANCE_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: ISTIO_META_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: ISTIO_META_INTERCEPTION_MODE
      value: [[ or (index .ObjectMeta.Annotations "sidecar.istio.io/interceptionMode") .ProxyConfig.InterceptionMode.String ]]
    [[ if .ObjectMeta.Annotations ]]
    - name: ISTIO_METAJSON_ANNOTATIONS
      value: |
             [[ toJson .ObjectMeta.Annotations ]]
    [[ end ]]
    [[ if .ObjectMeta.Labels ]]
    - name: ISTIO_METAJSON_LABELS
      value: |
             [[ toJson .ObjectMeta.Labels ]]
    [[ end ]]
    imagePullPolicy: IfNotPresent
    [[ if (ne (annotation .ObjectMeta `status.sidecar.istio.io/port`  0 ) "0") ]]
    readinessProbe:
      httpGet:
        path: /healthz/ready
        port: [[ annotation .ObjectMeta `status.sidecar.istio.io/port`  0  ]]
      initialDelaySeconds: [[ annotation .ObjectMeta `readiness.status.sidecar.istio.io/initialDelaySeconds`  1  ]]
      periodSeconds: [[ annotation .ObjectMeta `readiness.status.sidecar.istio.io/periodSeconds`  2  ]]
      failureThreshold: [[ annotation .ObjectMeta `readiness.status.sidecar.istio.io/failureThreshold`  30  ]]
    [[ end -]]securityContext:

      readOnlyRootFilesystem: true
      [[ if eq (annotation .ObjectMeta `sidecar.istio.io/interceptionMode` .ProxyConfig.InterceptionMode) "TPROXY" -]]
      capabilities:
        add:
        - NET_ADMIN
      runAsGroup: 1337
      [[ else -]]
      runAsUser: 1337
      [[ end -]]
    restartPolicy: Always
    resources:
      [[ if (isset .ObjectMeta.Annotations `sidecar.istio.io/proxyCPU`) -]]
      requests:
        cpu: "[[ index .ObjectMeta.Annotations `sidecar.istio.io/proxyCPU` ]]"
        memory: "[[ index .ObjectMeta.Annotations `sidecar.istio.io/proxyMemory` ]]"
    [[ else -]]
      requests:
        cpu: 10m

    [[ end -]]
    volumeMounts:
    - mountPath: /etc/istio/proxy
      name: istio-envoy
    - mountPath: /etc/certs/
      name: istio-certs
      readOnly: true
  volumes:
  - emptyDir:
      medium: Memory
    name: istio-envoy
  - name: istio-certs
    secret:
      optional: true
      [[ if eq .Spec.ServiceAccountName "" -]]
      secretName: istio.default
      [[ else -]]
      secretName: [[ printf "istio.%s" .Spec.ServiceAccountName ]]
      [[ end -]]

**Comment by ostromart** [comment]
I assume your cluster is working normally otherwise? If so, it suggests a narrow networking problem where API server cannot reach 443 port on injector.
It looks like you're running on EKS, if so did you follow:
https://aws.amazon.com/blogs/opensource/getting-started-istio-eks/
EKS webhook support is somewhat new and requires platform specific config, which may also be EKS version dependent, see this old bug:
https://github.com/istio/old_issues_repo/issues/271

**Comment by daparthi001** [comment]
We are not using eks ,we are just deploying k8's cluster on ec2 .
my api server is complaining about Failed calling webhook, failing closed sidecar-injector.istio.io: failed calling admission webhook "sidecar-injector.istio.io": Post https://istio-sidecar-injector.istio-system.svc:443/inject?timeout=30s: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
 systemctl status kube-apiserver -l
● kube-apiserver.service - Kubernetes API Server
   Loaded: loaded (/etc/systemd/system/kube-apiserver.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2019-02-12 11:22:47 EST; 2min 26s ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
 Main PID: 4010 (kube-apiserver)
   CGroup: /system.slice/kube-apiserver.service
           └─4010 /usr/local/bin/kube-apiserver --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota --advertise-address=<ip> --allow-privileged=true --apiserver-count=3 --audit-log-maxage=30 --audit-log-maxbackup=3 --audit-log-maxsize=100 --audit-log-path=/var/log/k8s-audit/audit.log --audit-policy-file=/etc/kubernetes/audit-policy.yaml --authorization-mode=Node,RBAC --client-ca-file=/etc/pki/ca-trust/source/anchors/kubernetes-ca.pem --enable-swagger-ui=true --etcd-cafile=/etc/pki/ca-trust/source/anchors/kubernetes-ca.pem --etcd-certfile=/etc/kubernetes/kube-master.pem --etcd-keyfile=/etc/kubernetes/kube-master-key.pem --etcd-servers=https://<url>:2379 --experimental-encryption-provider-config=/etc/kubernetes/etcd-encryption-config.yaml --feature-gates=SupportPodPidsLimit=true --kubelet-certificate-authority=/etc/pki/ca-trust/source/anchors/kubernetes-ca.pem --kubelet-client-certificate=/etc/kubernetes/kube-master.pem --kubelet-client-key=/etc/kubernetes/kube-master-key.pem --runtime-config=api/all,settings.k8s.io/v1alpha1=true --secure-port=6443 --service-account-key-file=/etc/kubernetes/kube-master-sa.pem --service-cluster-ip-range=192.168.0.0/16 --service-node-port-range=1-60000 --tls-ca-file=/etc/pki/ca-trust/source/anchors/kubernetes-ca.pem --tls-cert-file=/etc/kubernetes/kube-master.pem --tls-private-key-file=/etc/kubernetes/kube-master-key.pem

Feb 12 11:25:05 kube-apiserver[4010]: Trace[1751593910]: [30.000813635s] [30.000711989s] END
Feb 12 11:25:05 kube-apiserver[4010]: W0212 11:25:05.319841    4010 admission.go:248] Failed calling webhook, failing closed sidecar-injector.istio.io: failed calling admission webhook "sidecar-injector.istio.io": Post https://istio-sidecar-injector.istio-system.svc:443/inject?timeout=30s: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Feb 12 11:25:05 kube-apiserver[4010]: I0212 11:25:05.320092    4010 trace.go:76] Trace[442358387]: "Create /api/v1/namespaces/default/pods" (started: 2019-02-12 11:24:35.319233125 -0500 EST m=+104.717297606) (total time: 30.000835849s):
Feb 12 11:25:05 kube-apiserver[4010]: Trace[442358387]: [30.000835849s] [30.000736035s] END
Feb 12 11:25:05 kube-apiserver[4010]: W0212 11:25:05.369939    4010 admission.go:248] Failed calling webhook, failing closed sidecar-injector.istio.io: failed calling admission webhook "sidecar-injector.istio.io": Post https://istio-sidecar-injector.istio-system.svc:443/inject?timeout=30s: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Feb 12 11:25:05 kube-apiserver[4010]: I0212 11:25:05.370168    4010 trace.go:76] Trace[1233094340]: "Create /api/v1/namespaces/default/pods" (started: 2019-02-12 11:24:35.369353119 -0500 EST m=+104.767417621) (total time: 30.000793728s):
Feb 12 11:25:05 kube-apiserver[4010]: Trace[1233094340]: [30.000793728s] [30.000714284s] END
Feb 12 11:25:05 kube-apiserver[4010]: W0212 11:25:05.420119    4010 admission.go:248] Failed calling webhook, failing closed sidecar-injector.istio.io: failed calling admission webhook "sidecar-injector.istio.io": Post https://istio-sidecar-injector.istio-system.svc:443/inject?timeout=30s: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Feb 12 11:25:05 kube-apiserver[4010]: I0212 11:25:05.420378    4010 trace.go:76] Trace[1649095205]: "Create /api/v1/namespaces/default/pods" (started: 2019-02-12 11:24:35.419522939 -0500 EST m=+104.817587429) (total time: 30.000832707s):
Feb 12 11:25:05 kube-apiserver[4010]: Trace[1649095205]: [30.000832707s] [30.00075009s] END

**Comment by ostromart** [comment]
I see - regardless, the problem is that API server cannot reach the sidecar injector in your setup. Pod is running (health probe would fail otherwise) and shows no errors. 
Could you verify with AWS that k8s webhook is supported on EC2? Your issue looks very similar to what happened with EKS. It is quite likely network policy related. 
Alternatively if you want to debug further yourself, try deploying the simple webhook app here: https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/
This will isolate the problem down to just API server -> user node connectivity for 443. It will be easier to debug this simple example without other moving parts in the picture.

**Comment by daparthi001** [comment]
curl https://istio-sidecar-injector.istio-system.svc:443/inject?timeout=30s
curl: (56) Received HTTP code 503 from proxy after CONNECT

**Comment by ostromart** [comment]
Where are you curling from?

**Comment by daparthi001** [comment]
i am curling from the master node of the cluster

**Comment by ostromart** [comment]
There are no Istio proxies between API server and sidecar injector. I assume this is from kube-proxy, can you do curl -v? 
Are you using ClusterIP or NodePort? 
How is your cluster set up, i.e. which recipe on istio.io did you follow, or describe your own steps.

**Comment by daparthi001** [comment]
istio-sidecar-injector   ClusterIP      192.168.88.191    <none>        443/TCP                                                                                                                  3h
curl -v 192.168.88.191:443
* About to connect() to proxy  port 80 (#0)
*   Trying 153.114.217.9...
* Connected to () port 80 (#0)
> GET HTTP://192.168.88.191:443/ HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 192.168.88.191:443
> Accept: */*
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 503 Service Unavailable
< Cache-Control: no-cache
< Pragma: no-cache
< Content-Type: text/html; charset=utf-8
< Proxy-Connection: Keep-Alive
< Connection: Keep-Alive
< Content-Length: 1114
<
<HTML><HEAD>
  <TITLE>Network Error</TITLE>
  </HEAD>
  <BODY>
  <FONT face="Helvetica">
  <big><strong></strong></big><BR>
  </FONT>
  <blockquote>
  <TABLE border=0 cellPadding=1 width="80%">
  <TR><TD>
  <FONT face="Helvetica">
  <big>Network Error (tcp_error)</big>
  <BR>
  <BR>
  </FONT>
  </TD></TR>
  <TR><TD>
  <FONT face="Helvetica">
  A communication error occurred: "Operation timed out"
  </FONT>
  </TD></TR>
  <TR><TD>
  <FONT face="Helvetica">
  The Web Server may be down, too busy, or experiencing other problems preventing it from responding to requests. You may wish to try again at a later time.
  </FONT>
  </TD></TR>
  <TR><TD>
  <FONT face="Helvetica" SIZE=2>
  <BR>


Removed config from the kube-proxy
# cat /etc/systemd/system/kube-proxy.service
[Unit]
Description=Kubernetes Kube Proxy
Documentation=https://github.com/GoogleCloudPlatform/kubernetes

[Service]
ExecStart=/usr/local/bin/kube-proxy \
  --kubeconfig=/etc/kubernetes/kube-proxy.config

Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
old config 
# cat /etc/systemd/system/kube-proxy.service_backup
[Unit]
Description=Kubernetes Kube Proxy
Documentation=https://github.com/GoogleCloudPlatform/kubernetes

[Service]
ExecStart=/usr/local/bin/kube-proxy \
  --cluster-cidr=172.20.0.0/14 \
  --kubeconfig=/etc/kubernetes/kube-proxy.config

Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target



systemctl status -l kube-proxy.service
● kube-proxy.service - Kubernetes Kube Proxy
   Loaded: loaded (/etc/systemd/system/kube-proxy.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2019-02-12 16:52:38 EST; 6min ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
 Main PID: 4103 (kube-proxy)
    Tasks: 0
   Memory: 56.0M
   CGroup: /system.slice/kube-proxy.service
           ‣ 4103 /usr/local/bin/kube-proxy --kubeconfig=/etc/kubernetes/kube-proxy.config

Feb 12 16:53:15  kube-proxy[4103]: E0212 16:53:15.009629    4103 event.go:209] Unable to write event: 'Post https://<url>:6443/api/v1/namespaces/default/events: dial tcp <masternode>:6443: i/o timeout' (may retry after sleeping)
Feb 12 16:53:36  kube-proxy[4103]: E0212 16:53:36.772309    4103 reflector.go:205] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:86: Failed to list *core.Endpoints: endpoints is forbidden: User "system:kube-proxy" cannot list endpoints at the cluster scope
Feb 12 16:53:36  kube-proxy[4103]: E0212 16:53:36.772309    4103 reflector.go:205] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:86: Failed to list *core.Service: services is forbidden: User "system:kube-proxy" cannot list services at the cluster scope
Feb 12 16:53:36  kube-proxy[4103]: E0212 16:53:36.772348    4103 event.go:200] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:".1582bc641ad82022", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"", UID:"", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"Starting", Message:"Starting kube-proxy.", Source:v1.EventSource{Component:"kube-proxy", Host:""}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xbf10ede9f5c35a22, ext:551403704, loc:(*time.Location)(0x237e260)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xbf10ede9f5c35a22, ext:551403704, loc:(*time.Location)(0x237e260)}}, Count:1, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events is forbidden: User "system:kube-proxy" cannot create events in the namespace "default"' (will not retry!)
Feb 12 16:53:37  kube-proxy[4103]: I0212 16:53:37.802278    4103 controller_utils.go:1026] Caches are synced for service config controller
Feb 12 16:53:37  kube-proxy[4103]: I0212 16:53:37.802293    4103 controller_utils.go:1026] Caches are synced for endpoints config controller
Feb 12 16:53:37  kube-proxy[4103]: E0212 16:53:37.860381    4103 proxier.go:1319] Failed to delete stale service IP 192.168.0.10 connections, error: error deleting connection tracking state for UDP service IP: 192.168.0.10, error: error looking for path of conntrack: exec: "conntrack": executable file not found in $PATH
Feb 12 16:53:56  kube-proxy[4103]: E0212 16:53:56.528274    4103 proxier.go:603] Failed to delete kube-system/kube-dns:dns endpoint connections, error: error deleting conntrack entries for UDP peer {192.168.0.10, 172.20.0.3}, error: error looking for path of conntrack: exec: "conntrack": executable file not found in $PATH
Feb 12 16:53:56  kube-proxy[4103]: E0212 16:53:56.528308    4103 proxier.go:603] Failed to delete kube-system/kube-dns:dns endpoint connections, error: error deleting conntrack entries for UDP peer {192.168.0.10, 172.20.0.4}, error: error looking for path of conntrack: exec: "conntrack": executable file not found in $PATH
Feb 12 16:54:19  kube-proxy[4103]: E0212 16:54:19.258971    4103 proxier.go:1319] Failed to delete stale service IP 192.168.0.10 connections, error: error deleting connection tracking state for UDP service IP: 192.168.0.10, error: error looking for path of conntrack: exec: "conntrack": executable file not found

**Comment by daparthi001** [comment]
> There are no Istio proxies between API server and sidecar injector. I assume this is from kube-proxy, can you do curl -v?
yes done posted .
> Are you using ClusterIP or NodePort?
cluster ip 
> How is your cluster set up, i.e. which recipe on istio.io did you follow, or describe your own steps.
i just used istio.demo.yaml file

**Comment by ostromart** [comment]
I mean, how did you create your cluster. e.g. 
https://istio.io/docs/setup/kubernetes/platform-setup/aws/

**Comment by daparthi001** [comment]
We used internal devleoped scripts for setting up cluster

**Comment by ostromart** [comment]
Based on what you've told me so far it looks like the cluster needs some additional setup to enable webhooks. Next thing to try would be to deploy the simple webhook (link above) and ensure that works. 
You can use the AWS platform setup link above to get some clues for steps you might be missing.

**Comment by daparthi001** [comment]
One final question i want to decide on the network cidr
kube-controll-manager 
--cluster-cidr=172.20.0.0/14
--service-cluster-ip-range=192.168.0.0/16
kube-apiservice
--service-cluster-ip-range=192.168.0.0/16
kubelet service
 --pod-cidr=172.20.0.0/14
Dns
--cluster-dns=192.168.0.10

weave:
cidr range :  value: 172.20.0.0/14

Some network conflict is happening do you think this ranges work what if i keep just keep 192.168.0.0/16 range for both cluster/server cidr ?

**Comment by ostromart** [comment]
No, these cannot overlap. You can find more info and examples on how to set things up if you google around e.g. https://github.com/CiscoCloud/k8sclass/tree/master/Networking
Also check out the AWS setup link since your install is going to be similar.
