### ISSUE TITLE
Multiple tests doesn't work using Test scope

### ISSUE THREAD

**Issue by diemtvu** [istio/istio#11628]
**Describe the bug**

The integration2 test framework fails with `item already exists` error, when there is more than one test cases that define a test context like this.

```
ctx.RequireOrSkip(t, lifecycle.Test, &descriptors.NativeEnvironment, &ids.Apps, &ids.PolicyBackend, &ids.Mixer)
```

**Expected behavior**

Tests should be able to run.

**Steps to reproduce the bug**

Create 2 tests like this.
```
func TestFoo(t *testing.T) {
	ctx := framework.GetContext(t)
	ctx.RequireOrSkip(t, lifecycle.Suite, &descriptors.NativeEnvironment, &ids.Apps, &ids.PolicyBackend, &ids.Mixer)
        // Do something.
}
func TestBar(t *testing.T) {
	ctx := framework.GetContext(t)
	ctx.RequireOrSkip(t, lifecycle.Suite, &descriptors.NativeEnvironment, &ids.Apps, &ids.PolicyBackend, &ids.Mixer)
        // Do something.
}
```

**Version**
1.1

**Installation**
N/A

**Environment**
N/A

**Cluster state**
N/A

**Comment by ozevren** [comment]
I've landed a new refactoring of the test framework in master. The namespace handling should be much finer grained and help with isolation of tests. I am closing this bug. Let me know/reopen the bug if you're seeing further issues.
