### ISSUE TITLE
No metrics in grafana with CNI enabled in istio 1.1.0-snapshot.5

### ISSUE THREAD

**Issue by MBauer83** [istio/istio#11638]
I have installed istio as per the [prelim install instructions](https://preliminary.istio.io/docs/setup/kubernetes/helm-install/#option-2-install-with-helm-and-tiller-via-helm-install) with the following settings during the actual installtion of istio (not istio-init): `--set grafana.enabled=true --set tracing.enabled=true --set kiali.enabled=true --set servicegraph.enabled=true --set istio_cni.enabled=true`

In two namespaces, I installed various services like elasticsearch, consul, mysql etc., usually via their respective helm-charts. One of those namespaces (the default namespace) has sidecar auto-injection enabled. The service-configuration and istio-configuration allows for traffic between the services. I can verify that traffic exists and is handled correctly through sidecars.

In Grafana, only Mixer, Performance and Pilot Dashboard show any data - but nothing from any actual service is tracked. Not just specifically configured service metrics, but general traffic handled by istio doesn't seem to make it into metrics&monitoring. Explicitly, Mesh and Service Dashboards are entirely empty. How can I debug or fix this issue - are alternative configurations needed somewhere?

**Comment by douglas-reid** [comment]
Have you tried troubleshooting with https://preliminary.istio.io/help/ops/telemetry/missing-metrics/?

**Comment by MBauer83** [comment]
Thank you for pointing me at that help page. Here are my results:

**Verify Mixer is receiving Report calls**
This fails - when I forward port 9093 for the telemetry container, I get a 404 response in the browser, so I was unable to complete any "search for" instructions. Or is there some other way I ought to access the endpoint. Here are my exact steps:

```
kubectl get pods -n istio-system

NAME                                      READY   STATUS      RESTARTS   AGE
grafana-f8467cc6-6bfpf                    1/1     Running     0          5d
istio-citadel-676c58584b-wcqgk            1/1     Running     0          5d
istio-cni-node-dwqnd                      1/1     Running     0          5d
istio-cni-node-vtwpf                      1/1     Running     0          5d
istio-cni-node-wllhj                      1/1     Running     0          5d
istio-egressgateway-54477c6569-vzkhf      1/1     Running     0          5d
istio-galley-58b7c6b6bb-rz7px             1/1     Running     0          5d
istio-ingressgateway-f6c4b779b-scfcn      1/1     Running     0          5d
istio-init-crd-10-mgbs6                   0/1     Completed   0          5d
istio-init-crd-11-67l7d                   0/1     Completed   0          5d
istio-init-crd-certmanager-10-x9k8z       0/1     Completed   0          5d
istio-pilot-7d586bdf7d-rcbwh              2/2     Running     0          5d
istio-policy-755cf49c4f-6rgxf             2/2     Running     3          5d
istio-sidecar-injector-6d7586f8cd-n5tqz   1/1     Running     0          5d
istio-telemetry-7c7ff645cf-xngx4          2/2     Running     3          5d
istio-tracing-6849759bc8-xhwt9            1/1     Running     0          5d
kiali-7766b75767-4twxk                    1/1     Running     0          5d
prometheus-849b9cddff-5gn7n               1/1     Running     0          5d
servicegraph-655755f6c9-dttq8             1/1     Running     0          5d

/some/directory/
❯ kubectl -n istio-system port-forward istio-telemetry-7c7ff645cf-xngx4 9093
Forwarding from 127.0.0.1:9093 -> 9093
Forwarding from [::1]:9093 -> 9093
Handling connection for 9093
```

In a parallel window, after forwarding the port, I executed `curl http://localhost:9093` and got `404 page not found` (and the "Handling connection"-line in the other window)

**Verify the Mixer rules exist**
I can verify that the required rules exist:

```
kubectl get rules --all-namespaces
NAMESPACE      NAME                      CREATED AT
istio-system   kubeattrgenrulerule       5d
istio-system   promhttp                  5d
istio-system   promtcp                   5d
istio-system   promtcpconnectionclosed   5d
istio-system   promtcpconnectionopen     5d
istio-system   stdio                     5d
istio-system   stdiotcp                  5d
istio-system   tcpkubeattrgenrulerule    5d
```

**Verify the Prometheus handler configuration exists**
This configuration did not exist. Is there no default handler configuration during istio install with helm, oder is an alternative one needed? I looked at the helm template and found that various resources from that template were in fact created. What's more, various `.Values`-flags regarding telemetry are per default set to true, so shouldn't hinder creation of the required resources. I'm probably missing something basic here, but could you help me out with how to supply the missing configuration given that helm template?

**Verify Mixer metrics instances configuration exists**
The required configurations exist:
```
kubectl get metrics.config.istio.io --all-namespaces
NAMESPACE      NAME                   CREATED AT
istio-system   requestcount           5d
istio-system   requestduration        5d
istio-system   requestsize            5d
istio-system   responsesize           5d
istio-system   tcpbytereceived        5d
istio-system   tcpbytesent            5d
istio-system   tcpconnectionsclosed   5d
istio-system   tcpconnectionsopened   5d
```

**Verify Mixer is sending metric instances to the Prometheus adapter**
Impossible/unclear due to `404` mentioned above.


**Verify Prometheus configuration**
Istio-mesh shows as up. However, I noticed "kubernetes-apiservers" seemed to be down - could this be due to the nonstandard kube-api addresses in Azure AKS? In any case - other components use the kube-api successfully, so I suspect the problem doesn't originally lie there.

```
kubernetes-apiservers (0/1 up)
Endpoint 	State 	Labels 	Last Scrape 	Error
https://172.31.0.195:443/metrics
	down 	instance="172.31.0.195:443" 	11.747s ago 	context deadline exceeded
```

Additionally, the jaeger pod shows as down:
```
kubernetes-pods (2/3 up)
Endpoint 	State 	Labels 	Last Scrape 	Error
http://10.244.3.5:10055/metrics
	up 	instance="10.244.3.5:10055" k8s_app="kube-dns" kubernetes_io_cluster_service="true" namespace="kube-system" pod_name="kube-dns-v20-55b6db5d44-dxts2" pod_template_hash="1162861800" version="v20" 	10.404s ago 	
http://10.244.4.110:16686/metrics
	down 	app="jaeger" chart="tracing" heritage="Tiller" instance="10.244.4.110:16686" namespace="istio-system" pod_name="istio-tracing-6849759bc8-xhwt9" pod_template_hash="2405315674" release="istio" 	13.222s ago 	no token found
http://10.244.4.6:10055/metrics
	up 	instance="10.244.4.6:10055" k8s_app="kube-dns" kubernetes_io_cluster_service="true" namespace="kube-system" pod_name="kube-dns-v20-55b6db5d44-hngt9" pod_template_hash="1162861800" version="v20" 	4.872s ago 	
```

**Comment by MBauer83** [comment]
Looking into the prometheus-container log, I find this warning is consistently issued: `level=warn ts=2019-02-11T20:15:16.139090873Z caller=scrape.go:713 component="scrape manager" scrape_pool=kubernetes-pods target=http://10.244.4.110:16686/metrics msg="append failed" err="no token found"`. Always with the same url - could this be relevant? Should this happen with a helm install given the values specified?

Additionally, I `grep`d the logs of the mixer container in the telemetry pod for `error`s and found these kinds of entries from a couple of days ago, directly after the istio-installation, but not appearing since (potentially unrelated, but in case it might provide valuable info, I thought I'd include it:)

First, there were four errors of the following kind within a few milliseconds:
`Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=1689, ErrCode=NO_ERROR, debug=""`

Then, over the next minutes, there were a couple of these errors:
`istio.io/istio/mixer/adapter/kubernetesenv/cache.go:101: Failed to list *v1.Pod: Get https://[Azure Kube-API Address]:443/api/v1/pods?limit=500&resourceVersion=0: net/http: TLS handshake timeout`

A current `--tail 10` gives:
```
scvg2997: inuse: 14, idle: 3, sys: 17, released: 1, consumed: 16 (MB)
GC forced
gc 3754 @449803.856s 0%: 0.010+3.2+3.9 ms clock, 0.042+0/3.1/9.2+15 ms cpu, 12->12->7 MB, 15 MB goal, 4 P
scvg2998: 0 MB released
scvg2998: inuse: 15, idle: 2, sys: 17, released: 1, consumed: 16 (MB)
GC forced
gc 3755 @449923.891s 0%: 0.46+5.3+4.3 ms clock, 1.8+0.38/5.3/13+17 ms cpu, 12->12->7 MB, 15 MB goal, 4 P
GC forced
gc 3756 @450043.956s 0%: 0.050+7.1+4.9 ms clock, 0.20+0/6.4/6.0+19 ms cpu, 12->12->7 MB, 15 MB goal, 4 P
scvg2999: inuse: 12, idle: 5, sys: 17, released: 1, consumed: 16 (MB)
```

Furthermore, this is the entire log for the `istio-tracing` container:
```
{"level":"info","ts":1549465823.0935159,"caller":"healthcheck/handler.go:99","msg":"Health Check server started","http-port":14269,"status":"unavailable"}
{"level":"info","ts":1549465823.093701,"caller":"memory/factory.go:55","msg":"Memory storage configuration","configuration":{"MaxTraces":50000}}
{"level":"info","ts":1549465823.0956464,"caller":"tchannel/builder.go:97","msg":"Enabling service discovery","service":"jaeger-collector"}
{"level":"info","ts":1549465823.0957007,"caller":"peerlistmgr/peer_list_mgr.go:111","msg":"Registering active peer","peer":"127.0.0.1:14267"}
{"level":"info","ts":1549465823.0964649,"caller":"all-in-one/main.go:209","msg":"Starting agent"}
{"level":"info","ts":1549465823.096726,"caller":"app/agent.go:68","msg":"Starting jaeger-agent HTTP server","http-port":5778}
{"level":"info","ts":1549465823.0974338,"caller":"all-in-one/main.go:271","msg":"Starting jaeger-collector TChannel server","port":14267}
{"level":"info","ts":1549465823.0975099,"caller":"grpcserver/grpc_server.go:64","msg":"Starting jaeger-collector gRPC server","grpc-port":"14250"}
{"level":"info","ts":1549465823.0975766,"caller":"all-in-one/main.go:289","msg":"Starting jaeger-collector HTTP server","http-port":14268}
{"level":"info","ts":1549465823.0975957,"caller":"all-in-one/main.go:417","msg":"Archive storage not created","reason":"Archive storage not supported"}
{"level":"info","ts":1549465823.1312747,"caller":"all-in-one/main.go:327","msg":"Listening for Zipkin HTTP traffic","zipkin.http-port":9411}
{"level":"info","ts":1549465823.2891572,"caller":"all-in-one/main.go:378","msg":"Registering metrics handler with jaeger-query HTTP server","route":"/metrics"}
{"level":"info","ts":1549465823.2892213,"caller":"all-in-one/main.go:384","msg":"Starting jaeger-query HTTP server","port":16686}
{"level":"info","ts":1549465823.2892416,"caller":"healthcheck/handler.go:133","msg":"Health Check state change","status":"ready"}
{"level":"info","ts":1549465824.095914,"caller":"peerlistmgr/peer_list_mgr.go:157","msg":"Not enough connected peers","connected":0,"required":1}
{"level":"info","ts":1549465824.096002,"caller":"peerlistmgr/peer_list_mgr.go:166","msg":"Trying to connect to peer","host:port":"127.0.0.1:14267"}
{"level":"info","ts":1549465824.0963626,"caller":"peerlistmgr/peer_list_mgr.go:176","msg":"Connected to peer","host:port":"[::]:14267"}
```

**Comment by douglas-reid** [comment]
So, in a GKE cluster, I was able to enable NetworkPolicy, install istio with cni, generate traffic and see the traffic in prometheus. I forgot to install grafana, but being able to see these metrics via prometheus means that everything should work.

The jaeger metrics path was incorrect and since corrected in a PR for 1.1.

@MBauer83 the port in the (now updated) docs is `15014`. It was moved from `9093` for reasons without the docs being updated originally.

**Comment by douglas-reid** [comment]
Update: I'm actually only seeing traffic *from* `source_workload_namespace=istio-system`.

**Comment by douglas-reid** [comment]
@MBauer83 you said that you can confirm that traffic is flowing through your proxies. May I ask how?

I just tried a fresh install of 1.1 on a GKE cluster with Network Policy (1.12.5-gke.5) enabled and `istio_cni` enabled. I can see traffic flowing to each of the sample pods, but it does *NOT* go through the proxies.

Install:

```bash
helm template $HOME/istio-fetch/istio --name istio --namespace istio-system --set istio_cni.enabled=true --set global.proxy.accessLogFile="/dev/stdout" --set istio-cni.cniBinDir=/home/kubernetes/bin --set tracing.enabled=true --set tracing.gateway.enabled=true | kubectl apply -f -
```

Counters from the productpage envoy proxy after sending several requests:

```
inbound|9080|http|productpage.default.svc.cluster.local::127.0.0.1:9080::cx_active::0
inbound|9080|http|productpage.default.svc.cluster.local::127.0.0.1:9080::cx_connect_fail::0
inbound|9080|http|productpage.default.svc.cluster.local::127.0.0.1:9080::cx_total::0
inbound|9080|http|productpage.default.svc.cluster.local::127.0.0.1:9080::rq_active::0
inbound|9080|http|productpage.default.svc.cluster.local::127.0.0.1:9080::rq_error::0
inbound|9080|http|productpage.default.svc.cluster.local::127.0.0.1:9080::rq_success::0
inbound|9080|http|productpage.default.svc.cluster.local::127.0.0.1:9080::rq_timeout::0
inbound|9080|http|productpage.default.svc.cluster.local::127.0.0.1:9080::rq_total::0
```

**Comment by tiswanso** [comment]
@douglas-reid  -- with your new install of 1.1 on GKE do you see the istio-cni-node daemonset present?  In newer release-1.1 versions the istio and istio/cni helm charts are separate and the install of the CNI is a separate step helm template/install operation.

**Comment by MBauer83** [comment]
@douglas-reid : I was misreading the diagnostics - and probably assuming that successful traffic would have to go through the proxy-container if it works at all, because I've had connection problems when the proxy wasn't working before - but the `cx_` and `rq_` values are all zero.

I attempted to upgrade to 1.1.0-rc2, but even after manually applying the crd-files, the `helm upgrade` command (with the correct namespace, of course) surprisingly gives `Error: UPGRADE FAILED: no ServiceAccount with the name "istio-multi" found`  while `kubectl get sa/istio-multi -n istio-system` confirms its existence.

Best to throw away the  cluster and build a new one on rc2, or can this be salvaged?

**Comment by john-a-joyce** [comment]
@MBauer83 I created a WIP PR to check if the e2e tests will pass in a prow environment with CNI enabled.   If not I will try to trouble shoot the issue more in that environment or recreate locally.  The PR is: https://github.com/istio/istio/pull/12331

**Comment by john-a-joyce** [comment]
@MBauer83 The mixer e2e tests all seem to pass with the cni enabled.  I am not sure what is the best way to debug this in your local environment.  Is it still occurring?  Have you tried it with the latest 1.1 images. Can you confirm you followed the CNI install instructions as described here:  https://deploy-preview-3537--preliminary-istio.netlify.com/docs/setup/kubernetes/install/cni/
When you  initially saw teh issue was around the time the Istio and CNI helm charts were being decoupled.   It's entirely possible things were working properly on the install at that point

**Comment by huisebug** [comment]
> @douglas-reid -- with your new install of 1.1 on GKE do you see the istio-cni-node daemonset present? In newer release-1.1 versions the istio and istio/cni helm charts are separate and the install of the CNI is a separate step helm template/install operation.

Where is the installation address of a separate CNI template?

**Comment by howardjohn** [comment]
I have CNI running on 1.1.2 and it is working fine: http://grafana.v112-cni.qualistio.org.

@MBauer83 is this still an issue in latest releases? I suspect @john-a-joyce is right, that the CNI daemonset is not installed. Make sure you follow the docs here: https://istio.io/docs/setup/kubernetes/additional-setup/cni/

In particular, the `helm install install/kubernetes/helm/istio-cni --name=istio-cni --namespace=istio-system` step.

**Comment by howardjohn** [comment]
I think this is just a docs error that has since been resolved. If you are still seeing this please reopen (or you can open a new issue)
