### ISSUE TITLE
Integration framework flag --istio.test.noCleanup doesn't work.

### ISSUE THREAD

**Issue by diemtvu** [istio/istio#11643]
**Describe the bug**
This flag doesn't have any effect.

**Expected behavior**
Test environment won't be destroyed if this flag is set.

**Steps to reproduce the bug**
Run test with `--istio.test.noCleanup`

**Version**
n/a
**Installation**
n/a
**Environment**
n/a
**Cluster state**
n/a

**Comment by ozevren** [comment]
Hey @diemtvu, I've just landed a big refactoring of tests framework in master. The nocleanup flag should be working now. I am closing this bug. Please feel free to reopen it if you see any further cleanup related issues.
