### ISSUE TITLE
The excludeInboundPorts option is broken: it never takes any effect.

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio#11660]
The `excludeInboundPorts` option cannot have any effect. The reason:

According to https://github.com/istio/istio/blob/release-1.1/tools/deb/istio-iptables.sh#L39:

>  -d: Comma separated list of inbound ports to be excluded from redirection to Envoy (optional). Only applies when all inbound traffic (i.e. "*") is being redirected

The script: https://github.com/istio/istio/blob/release-1.1/tools/deb/istio-iptables.sh#L252 :

```bash
if [ "${INBOUND_PORTS_INCLUDE}" == "*" ]; then
...
  if [ -n "${INBOUND_PORTS_EXCLUDE}" ]; then
```

However, since `INBOUND_PORTS_INCLUDE` is set according to `(includeInboundPorts .Spec.Containers)` in https://github.com/istio/istio/blob/release-1.1/install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml#L40, once you have a container port defined, `INBOUND_PORTS_INCLUDE` will never be `*`.

**Comment by nmittler** [comment]
I assume the use case is that you want to exclude some of the ports that are being automatically included?

FYI, you can override the default port inclusion behavior with the annotation `traffic.sidecar.istio.io/includeInboundPorts` (e.g. "*"). So you can still include everything and then exclude as you'd like.

**Comment by vadimeisenbergibm** [comment]
Following https://github.com/istio/istio/issues/11660#issuecomment-462512103.

> I assume the use case is that you want to exclude some of the ports that are being automatically included?

Right.

>  you can override the default port inclusion behavior with the annotation `traffic.sidecar.istio.io/includeInboundPorts` (e.g. "*")

@nmittler Could you please let me know how can I add this annotation? I tried to use helm:
```bash
helm template install/kubernetes/helm/istio --name istio --namespace istio-system --set global.mtls.enabled=true --set global.controlPlaneSecurityEnabled=true --set global.proxy.includeInboundPorts="*" --set global.proxy.excludeInboundPorts="8000" >> $HOME/istio.yaml
```

Got this yaml generated:

```
        - "-b"
        - "[[ annotation .ObjectMeta `traffic.sidecar.istio.io/includeInboundPorts` (includeInboundPorts .Spec.Containers) ]]"
        - "-d"
        - "[[ excludeInboundPort (annotation .ObjectMeta `status.sidecar.istio.io/port`  15020 ) (annotation .ObjectMeta `traffic.sidecar.istio.io/excludeInboundPorts`  "8000" ) ]]"
```

The `includeInboundPorts .Spec.Containers`.

**Comment by nmittler** [comment]
@mandarjog @costinm are you aware of a way to pass in annotations for a deployment via helm?

I suppose you can manually modify the subcharts.

**Comment by dimpavloff** [comment]
Hi, this is still an issue. As per the original post, `INBOUND_PORTS_INCLUDE` is never `*` which means the `excludeInboundPorts` annotation is always ignored. Could we remove the stale annotation please?

**Comment by howardjohn** [comment]
I believe this is working as intended. INBOUND_PORTS_INCLUDE is not always `*`, you can configure it with `traffic.sidecar.istio.io/includeInboundPorts`.

@silentdai is working on related topics if any more questions

**Comment by silentdai** [comment]
I suggest you can either
- set `traffic.sidecar.istio.io/includeInboundPorts` and istio would set `INBOUND_PORTS_INCLUDE` to "*" and activate `excludeInboundPorts`, or
- leave `traffic.sidecar.istio.io/includeInboundPorts` empty and istio would set  `INBOUND_PORTS_INCLUDE` to containerPort and don't use `excludeInboundPorts` in this case.

**Comment by 1hanymhajna** [comment]
I tried to use this annotation but it it seems like istio ignore this annotation 
my global istio configuration is:
```
    includeInboundPorts: "*"
    excludeInboundPorts: ""
```
And want to exclude specific port in specific pod ,
as the documentation i can use this annotation in deployment level:
```
 traffic.sidecar.istio.io/includeInboundPorts: "80,8000"
```
but it seems like istio ignoring it, maybe i miss understand how i have to configure it ..
anyone can help with that?

**Comment by anastasiagrinman** [comment]
I can confirm that istiod helm chart (1.12.1 version) have by default  includeInboundPorts: "*" in values.yaml.
But overriding the parameters doesn't take place since files/injection-template.yaml has this args: 
- "{{ annotation .ObjectMeta `traffic.sidecar.istio.io/includeInboundPorts` `*` }}"

That's why the sidecar is added with default and doesn't takes the override value
INBOUND_PORTS_INCLUDE=*
