### ISSUE TITLE
Reduce load on Pilot by ignoring services

### ISSUE THREAD

**Issue by Stono** [istio/istio#11664]
Hi, 
I'm trying to think of ways to reduce the load on pilot and one of those is having the ability to exclude certain services from EDS, so that if the pods for these services change the updates just aren't propogated.  These are services that will never receive an incoming connection from my applications.

For example:

  - calico-typha.kube-system.svc.cluster.local
  - heapster.kube-system.svc.cluster.local
  - metrics-server.kube-system.svc.cluster.local
  - prom-snmp-exporter.kube-system.svc.cluster.local 
  - tiller-deploy.kube-system.svc.cluster.local

etc etc... 

can anyone think of a way to exclude a kubernetes service from the mesh?

**Comment by rshriram** [comment]
With 1.2, you can add an annotation to these services `networking.istio.io/exportTo` with value set to '.' . This would cause the service to become visible only in the kube-system namespace. Other sidecars wont see this service. If they dont see this service, there wont be an EDS update.

**Comment by Stono** [comment]
@rshriram that sounds awesome, shame it's two major releases away haha :D

**Comment by murarisumit** [comment]
Not sure, if it is right to point out. Learning by making mistakes here :sweat_smile:

Should we mark this issue close ?

**Comment by rshriram** [comment]
Oh sorry I meant 1.1 thats gonna be out in a few days

**Comment by Stono** [comment]
Aweeeesoommmeeee

**Comment by Stono** [comment]
OK for anyone else following this issue, this feature is only part implemented in 1.1, you won't be able to select namespaces, only `.` (current namespace) and `*` (all namespaces).

**Comment by Stono** [comment]
OK this is following on from a conversation with @rshriram regarding our real life use case for exportTo.  I didn't really know where else to post it but hopefully it will explain why the concept of "import" on a `Sidecar` resource doesn't really fit our CI/CD process or organisational model.  This is all born out of a conversation where I discovered `exportTo` is not going to be fully complete for 1.1, thus not addressing the OP.

Take the following simplistic service architecture where a service and a namespace correlate one to one:

![app](https://user-images.githubusercontent.com/1486729/53362673-9c017500-3932-11e9-8a7c-f1293a882919.png)

Each application is owned by a different product team within the organisation, they are effectively the gatekeepers as to who can talk to their service.  They do that in their applications configuration file with the `allowIngressFrom` block.  **note** they are abstracted from underlying kubernetes/istio concerns, they don't care about NetworkPolicy, Gateways, Sidecars, VirtualServices or anything like that.

This then goes on, when deployed, to generate `NetworkPolicy`, with ingress rules for the given namespaces.

![teams 1](https://user-images.githubusercontent.com/1486729/53362737-c18e7e80-3932-11e9-83ce-003c745e275f.png)

When a new service comes along, that wants to talk to one of these services, they send the team a pull request adding their new service to the `allowIngressFrom` block.  This then updates the NetworkPolicy to in turn allow that ingress.

What we effectively want to do is marry the new `exportTo` feature, to this already pre-defined list of services, because they are always going to be equal.  So in the case of Service A, as well as a `NetworkPolicy` allowing ingress from `service-b` and `service-c`, we would also generate the `VirtualService` to have `exportTo: [service-b, service-c]`.

Unfortunately this feature is not going to make it to 1.1, which I am pretty disappointed about, because we've been talking about network isolation for some time and I've explained our use case quite a lot!  However, what is going to make it to 1.1 is the ability to specify on a `Sidecar` resource, `import`, which allows you to tell a sidecar which services it will talk to, thus controlling what config it will pull in. 

However, as you can see however from the above diagram, the only way to know what the values for `Sidecar` should be for say, `service B`, would be to infer it from the fact it is in the `allowIngressFrom` blocks of `service A` and `service C`, however they're deployed in complete isolation.  We simply can't do it.

Another workaround would be to maintain an `egress` list in `App B`, but then we're asking teams to do two get their apps communicating.  And those two things will undoubtedly get out of sync.  It's also a leaky concern for us, we're asking the teams to over complicate their config to work around a platform problem.

On top of that, we have 160 applications deployed in this fashion, and wanted to seamlessly implement namespace isolation as the data for what we need is already there, if you're taking it from the perspective of the ingress service.

So I guess in summary, I'd really like to know:

- Is this completion of this feature being prioritized, considering it isn't working as per the prelim doco (https://preliminary.istio.io/docs/reference/config/istio.networking.v1alpha3#ServiceEntry) 
- What an ETA for this work would be?  Due to our ongoing issues with scaling and namespace isolation?  I'm a little frustrated because I've been telling people at AutoTrader that this is coming in 1.1, and now it's not :( 

cc. @nmittler

**Comment by nmittler** [comment]
cc @louiscryan

**Comment by frankbu** [comment]
@Stono Thanks for describing the scenario so clearly. I think your namespace-per-service use case is pretty common, so the priority to support exportTo namespaces other than current or all, should be pretty high. As you can see, it is certainly covered by the api, just not implemented in the first release. I'll let @rshriram confirm, but I would say this is definitely a 1.1 feature, just not 1.1.0. Maybe it could be in 1.1.1, which should be pretty soon too.

**Comment by costinm** [comment]
The priority for 1.1 is to control what services are visible in a given namespace - which is defined by Sidecar.egress.  

Ingress control is expressed and enforced with Istio RBAC - we plan for 'exportTo' to feed into and generate equivalent RBAC config, but this is not ready, as I mentioned the focus was on visibility.
In practice - until exportTo or "egress" are fed into RBAC, you MUST maintain 2 configs, one for visibility and one for access.  Visibility is not enforceable and easily bypassed. 

We also found many apps using custom ACL ( built-in, custom, etc ) - and apps with large number of
 users ( auth, databases, shared infra ) where managing the visibility on the caller side is not practical.

But if you have configs defining "A allows ingress from B" - I think it should be possible to generate the reverse, "B is making egress calls to A".  I'm not entirely sure I understand the problem - any code that generates 'A exportsTo: B,C' can also generate the opposite. 

The reason we think 'egress (importsFrom)' is important: a team maintaining a service should be able 
to control what dependencies it uses. Using 'exportTo' will mean that a random other team can accidentally impact the behavior of the app. In general - both sides must declare trust in each other, and 
the server must have enforcing checks.  

I can't think of any good way to declare this only once - maybe in some cases there is a source of truth, but in the general case the client can't be forced to use a particular service just because the server exports to it.

**Comment by costinm** [comment]
To be clear: exportTo is planned and eventually can be used to configure RBAC, so you don't have do do this twice ( unless you have advanced configs that really need full RBAC ). 

But we need consent from both sides - and we need to support '*' ( i.e. services that are exposed to everyone in the mesh and do their own ACL, as well as clients that import all services that allow that, like prometheus ). 

The RBAC and exportTo is under control of the service, the egress under control of the client which might pick a specific implementation/version of the server or might not actually need to use a service even it is exported. 

RBAC and exportTo are also defined in terms of service accounts ( which are equivalent to namespaces), while egress can be specified on a service and port level. 
"exportTo"/RBAC pointing to anything except service account is not really enforceable with the current 
Siffee model, since the access is based on the identity of the caller.

**Comment by Stono** [comment]
Hey everyone!
Thanks for your detailed responses.

I do just want to clarify something however, I don't consider exportTo to be an RBAC concern?  I only gave the association to NetworkPolicy to explain how our organisation puts the responsibility with the owning squad to populate that list and how that list will always actually need to be identical to the NetworkPolicy ingress rules.

@costinm you said "is important: a team maintaining a service should be able
to control what dependencies it uses" - I agree, and that's what we have.  It can declare what dependencies it uses, but it shouldn't be allowed to use them without the dependency agreeing.  Which is why we have gone down the route of having the listening side the arbiter of that config, not the sending side.  So Team B "declares" it uses service-a from Team A by sending a pull request to their config to allow the NetworkPolicy ingress.  Asking them to then add to `service-b` "egress" config to service-a is nothing more than duplication as from an organisational perspective, they've already declared that dependency.

**Comment by Stono** [comment]
PS I'm at GCP Next SF if anyone wants to whiteboard this in person haha

**Comment by castlemilk** [comment]
I kinda feel ExportTo wont help here. I wonder if scoping/sharding the number of sidecars/mesh components that Pilot needs to synchronise configuration would help. For example if all of the network policy could be scoped based of namespace/label and this can be used by Pilot to resolve the mesh components that need synchronising. An example is how `NetworkPolicy` is able to be applied based of namespace/PodLabels. 

@Stono I'm also pretty sad to not see namespace isolation prioritised as it still a big issue for multi-tenant environments and creates a massive blast radius when erroneous configuration is applied to the mesh.

**Comment by Stono** [comment]
Yeah, I've been pushing for it since mid last year @castlemilk :-( as our cluster grows the risk increases

**Comment by dwradcliffe** [comment]
This is very important for us too. We have many services (potentially hundreds) on each cluster and not only do we need namespace isolation but the config bloat on each sidecar is a real problem. We might be able to make it work with `exportTo: .` and duplicating resources for each namespace, but that seems like the wrong way to do it.

**Comment by frankbu** [comment]
@dwradcliffe The new [Sidecar resource](https://preliminary.istio.io/docs/reference/config/networking/v1alpha3/sidecar/) is supposed to address the config bloat problem.

**Comment by louiscryan** [comment]
As Frank mentioned refining exportTo to handle explicit namespaces as well
as 'same namespace' & 'all namespaces' is something we'll be looking to do
in a 1.1.x release. The APIs have been explicitly designed to handle the
'publisher controls visibility' case in addition to the 'consumer controls
visibility' case which is handled by the new Sidecar resource.

We prioritized dealing with the config bloat problem from the consumer
perspective first as it ultimately provides the most control and should
provide some value to everyone if they are having footprint issues.

@Stono - I really appreciate the detailed feedback, in particular
validation of the 'producer oriented' model. This is how Google works
internally and it's something I believe many organizations should adopt as
it generally scales better from a management perspective, i.e it aligns
with the microservices philosophy.

**Comment by costinm** [comment]
@Stono I would expect once exportTo is fully implemented, at least on visibility side  ( and we're not that far away ) to support exactly your model. The client can do 'import */*' - which will generate only the list of services/namespaces that exportTo the client. So no need to duplicate if you have a consistent policy
of having 'producer declare deps'. 

There are few reasons we focused on 'import' first - the 'exportTo' is effective only if all producers 
follow this rule and strictly export to allowed clients ( which should also be fed into RBAC/enforced). 
In practice most users don't have this - and getting the RBAC/enforcement is more complicated. 

As I mentioned, a problem many people had was a service 'exporting' some resource accidentally.
I think you reported few bugs around this :-) If you chose to go with exportTo only, and import * it is 
hard to avoid this problem. DestinationRules can be exported - and multiple namespaces may export rules for same host. 
Explicit import avoids this problem and has a stricter isolation - keep in mind that on the server side
you need to rely on enforcement/RBAC, visibility is not doing much. 

I hope we'll have some tools to simplify keeping them in sync - and of course there are options to use
only exportTo or only import, but long term I think most users should have isolation on both ends.

**Comment by Stono** [comment]
Hey @costinm - I completely understand what you're saying and definitely agree that being explicit on both sides is best, however I have to balance that with a pragmatic implementation and minimal impact on the users of our platform.

The only other thing I can think of doing is writing a controller that watches for our ingress policies and manages sidecar resources outside of ci/cd.  Just feels wrong though, I prefer explicit IaC.

**Comment by Stono** [comment]
The other reason we *really* need this, average istio-proxy usage for memory is 128m, across 500 proxies, that's a fair whack.

<img width="1620" alt="screenshot 2019-03-07 at 11 07 54" src="https://user-images.githubusercontent.com/1486729/53952655-49118580-40c9-11e9-8991-0aaaae0c070c.png">

**Comment by Stono** [comment]
Closing this, Sidecar isolation has all but solved this for us: https://twitter.com/karlstoney/status/1110255431644049409
