### ISSUE TITLE
Zero downtime rollouts with Istio 

### ISSUE THREAD

**Issue by ayushpateria** [istio/istio#11682]
When doing a rolling update using Kubernetes deployments for our gateway service (not Istio's gateway) there are many failed requests (503 responses). I dug in deeper to find out the cause of this, and found out it has to do with the nature of Kubernetes being eventually consistent. After a pod is deleted, it takes some time to propagate this information to the kube-proxy agents running on nodes, and the load balancer continues to send new requests to the deleted pod. (Refer [#43576](https://github.com/kubernetes/kubernetes/issues/43576))
The solution to above when just using Kubernetes is to add a preStop hook with a sleep duration enough to allow the above propagation. But, this solution doesn't work when using Istio. The reason is that as soon as Istio pilot determines that the pod was deleted, it removes the inbound listener for the service in the pod's envoy sidecar before Kubernetes is finished propagating the removal to the kube proxies (I verified this by logs), and envoy rejects the new requests right away. 
I believe Istio should have something like preStop configuration to delay the removal of inbound listener from the envoy sidecar of the pod being deleted.

**Version**
1.0.0

**Comment by howardjohn** [comment]
This might be fixed by https://github.com/istio/istio/pull/11485

**Comment by ayushpateria** [comment]
if "Envoy starts rejecting any new connections" right after it gets SIGTERM, then I don't think it would fix the above problem. The way to fix this would be to delay this operation by some period (and also keep the listener active), so that the new requests which are coming to the terminating pod because of the sync delay gets served. @liamawhite any thoughts?

**Comment by liamawhite** [comment]
This is designed to be used along with retries and an aggressive circuit breaking policy. Are these gateways accessed by things within the mesh?

**Comment by ayushpateria** [comment]
No, this gateway service is at the front and accessed directly by Google Load Balancers.

**Comment by liamawhite** [comment]
This will be fixed when we move to CNI or Kube implements the sidecar proposal. In the meantime, would [this](https://github.com/istio/istio/issues/7136#issuecomment-441769401) work?

**Comment by ayushpateria** [comment]
We tried that already. There's a problem with that approach - it does keep the envoy proxy from shutting down immediately at SIGTERM, but even if envoy is alive, the inbound listener is removed as soon as the pod endpoint is deleted from the service. And all the subsequent connections are rejected.  There's a push from pilot to the istio-proxy to delete the inbound listener when that pod is deleted, which is irrespective of the preStop hook.

**Comment by liamawhite** [comment]
@rshriram are we able to leave inbound listeners in place on pod shutdown?

**Comment by iandyh** [comment]
@ayushpateria Hi. With istio 1.1-RC and adding`preStop` hook, I no longer see 503s. Can you also verify?

**Comment by Bessonov** [comment]
Activity!

**Comment by Bessonov** [comment]
Bot fight: stale bot vs. istio-policy-bot

**Comment by Bessonov** [comment]
@howardjohn @liamawhite istio-policy-bot is the new way of disrespecting community.

**Comment by sdake** [comment]
@Bessonov regarding disrespecting community and bot fight, the automation in place is imperfect. I am semi-aware that @clarketm is working to improve the automation for the reasons stated.

Cheers
-steve

**Comment by howardjohn** [comment]
This is assumed fixed by https://github.com/istio/istio/pull/11485 and future further fix tracked in https://github.com/istio/istio/issues/11130. If you have specific 503 issues please open an issue with info + access logs. Thanks
