### ISSUE TITLE
Disabling only istio-policy does not work

### ISSUE THREAD

**Issue by clyang82** [istio/istio#11699]
I cannot make the bookinfo works when disable the policy only by using `--set mixer.policy.enabled=false`. but use `--set mixer.policy.enabled=false --set global.disablePolicyChecks=true` is working. Suggest to just have 1 flag to control mixer policy is used or not.

here are my steps:
1. install the latest 0211 release-1.1 build from https://gcsweb.istio.io/gcs/istio-prerelease/daily-build/release-1.1-latest-daily/
```
helm install install/kubernetes/helm/istio-init --name istio-init --tls
helm install install/kubernetes/helm/istio --name istio --namespace istio-system --set mixer.policy.enabled=false --tls
```
2. install bookinfo with auth-injection=true for `default` namespace
```
kubectl apply -f samples/bookinfo/networking/bookinfo-gateway.yaml  -n default
kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml -n default
```
3. access the bookinfo -  http://xxxxx:31380/productpage
the output is `UNAVAILABLE:Cluster not available`

the bookinfo pods cannot start successfully in this case:
```
root@icpmaster-cyang:~/istio-release-1.1-20190211-09-16# kubectl get pod -n default
NAME                             READY     STATUS    RESTARTS   AGE
details-v1-756886897d-dgbgn      1/2       Running   0          13m
productpage-v1-8fcdcb496-hgs8t   1/2       Running   0          13m
ratings-v1-7fc6ccbbbb-5r7db      1/2       Running   0          13m
reviews-v1-59ff68c6cf-kpw4q      1/2       Running   0          13m
reviews-v2-58f7dbbf8c-725kh      1/2       Running   0          13m
reviews-v3-654d6f5b95-sff8k      1/2       Running   0          13m
```

the logs of sidecar is
```
* failed checking application ports. listeners="0.0.0.0:15090","10.0.0.165:443","10.0.0.165:15030","10.0.0.205:5601","10.0.0.138:42422","10.0.0.204:9200","10.0.0.1:443","10.0.0.206:443","10.0.0.165:15031","10.0.0.165:15443","10.0.0.4:443","10.0.0.165:15032","10.0.0.165:31400","10.0.0.165:15029","10.0.0.131:24224","10.0.0.4:15443","10.0.0.243:443","10.0.0.177:15011","0.0.0.0:9090","0.0.0.0:8060","0.0.0.0:80","0.0.0.0:9901","0.0.0.0:9080","0.0.0.0:15010","0.0.0.0:9091","0.0.0.0:15004","0.0.0.0:8080","0.0.0.0:15014","10.1.90.213:3333","10.1.90.213:9999","0.0.0.0:15001"
* envoy missing listener for inbound application port: 0
* envoy missing listener for inbound application port: 9080
2019-02-12T10:19:41.006474Z	info	Envoy proxy is NOT ready: 3 errors occurred:
```

I can execute `kubectl exec -it -n default productpage-v1-8fcdcb496-hgs8t bash -c istio-proxy` to access the container and then run `curl htttp://127.0.0.1:9080/productpage`, it works well.

any thoughts? Thanks.

FYI @linsun @ymesika @esnible

**Comment by clyang82** [comment]
It seems we need to modify the configmap to make it works according to @ymesika 's suggestion
https://github.com/istio/istio/blob/release-1.1/install/kubernetes/helm/istio/templates/configmap.yaml#L54:L70

**Comment by douglas-reid** [comment]
I'm looking into this now.

**Comment by douglas-reid** [comment]
So, I think what we actually want here is to use the `global.disablePolicyCheck` flag, setting it to false.

**Comment by douglas-reid** [comment]
`mixer.policy.enabled` is rather confusing, but only serves to disable the *deployment* of the policy pods.

**Comment by linsun** [comment]
yes mixer.policy.enabled is intended to not install policy at all... I assume when that is disabled, we would want policy check to be disabled automatically since policy is not even there.

**Comment by linsun** [comment]
just realized you have mtls enabled... I believe we test non-mtls enabled as part of daily build now with the minimal istio profile.

**Comment by douglas-reid** [comment]
@clyang82 can we close this now ?

**Comment by clyang82** [comment]
sure. Thanks @douglas-reid
