### ISSUE TITLE
Missing metrics when deployed in another namespace

### ISSUE THREAD

**Issue by hugree** [istio/istio#11693]
**Describe the bug**
I did all the demos and I'm not sure I'm missing something in the concepts of Istio, but after applying very simple routing options to my own application, but in a different namespace, I can't get all the metrics to work accordingly. 
Deploy any hello world service in default namespace:
- service metrics in Grafana appear correctly: both Client workloads and Service Workloads are present
Deploy the same service in another namespace. The metrics are missing. 

**Expected behavior**
- Grafana and Prometheus metrics work find in selected namespaces too 

**Steps to reproduce the bug**
- install istio in the default istio-system namespace
- install your application in another namespace let's say "prod"
- visit Istio Service Dashboard in Grafana
- select your service
- check for missing metrics (empty Client and Service workloads). Only Client Request Volume, Rate and Duration are working in this case.

**Version**
ISTIO:
Version: 1.0.5
GitRevision: c1707e45e71c75d74bf3a5dec8c7086f32f32fad
User: root@6f6ea1061f2b
Hub: docker.io/istio
GolangVersion: go1.10.4
BuildStatus: Clean

HELM:
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}

KUBECTL:
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-28T15:20:58Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T06:59:37Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

**Installation**
Using helm with standard values.yaml and my settings as follows:
grafana:
  enabled: true
servicegraph:
  enabled: true
kiali:
  enabled: true
tracing:
  enabled: true

Also I enabled:
kubectl label namespace prod istio-injection=enabled

**Environment**
AKS on Azure with Kubernetes API 1.12.4 with RBAC

UPDATE: The same goes for Kiali and Jaeger... 
- in Kiali I can see metrics reported in the source (ingressgateway) but not the destination. 
- in Jaeger I can't do tracing for the "helloworld" app that's in the "prod" namespace.
Both problems do not concern the default namespace. The other helloworld app works fine and everything from routes, metrics to tracing is OK.

**Comment by marcfong** [comment]
@hugree - What was the issue? I am also facing this problem with Istio metrics for a specific namespace not showing up.

**Comment by levilugato** [comment]
any update about that ? I'm facing the same problem when deploying a service to another namespace with istio injected

**Comment by hugree** [comment]
@marcfong @levilugato 

If I remember correctly the problem was that I first deployed all services to my namespace and then configured the auto inject feature of Istio.

When I did things in the correct order... first deploy istio -> configure namespace -> deploy services... everything worked.
