### ISSUE TITLE
We need a release-1.1 charts repo

### ISSUE THREAD

**Issue by sdake** [istio/istio#11705]
**Describe the bug**
Currently, we have a dailies repo for master which is here:

```helm repo add istio.io https://storage.googleapis.com/istio-prerelease/daily-build/master-latest-daily/charts"```

We need a release-1.1 repo on storage.googleapis.com for the helm charts.  I don't know who has permissions to create such a thing - probably T&R.

A secondary problem is there is no daily for istio 1.1, so people are using master charts and expecting 1.1 results.

One relevant file in the repo that does the job of pushing these charts is here:
https://github.com/hklai/istio/blob/da335d6e12b12cc4db2bd8cf9fc7dbd986e13750/release/gcb/helm_charts.sh

I don't know how any of this works, nor who has the credentials, I'd work on it myself :)

Cheers
-steve

**Comment by sdake** [comment]
cc / @munrodg @duderino

**Comment by sdake** [comment]
cc @douglas-reid

**Comment by sdake** [comment]
Looks like @hklai has already resolved this - we just didn't know abow about it.  I have pushed a docs pr here: https://github.com/istio/istio.io/pull/3249

After this merges, we will be mostly resolved with this issue.

We can then change to the release-1.1 chart (rather than the dailies) once istio 1.1 is tagged.

**Comment by sdake** [comment]
This uses the release-1.1 daily images in the release-1.1 branch:
https://github.com/istio/istio/pull/11725

**Comment by sdake** [comment]
@munrodg both PRs need a merge to solve some many of the problems people are struggling with when installing the 1.1 branch.

**Comment by sdake** [comment]
note to T&R, we will need a PR similar to this prior to the release of 1.1 to change release-1.1-dailies to wherever the new images are located.  @hklai was able to help get the information needed to implement this very small change.

**Comment by sdake** [comment]
We got a release-1.1 charts repo - but it looks like the master charts repo was broken in the process.

I am not sure how to reenable the daily master builds of the helm charts.

**Comment by duderino** [comment]
Cowardly demoting to a P1 since the 1.1 needs have been met.  @sdake / @utka please reset to P0 if I got this wrong.

**Comment by sdake** [comment]
Related request: https://github.com/istio/istio/issues/7505
Related request: https://github.com/istio/istio/issues/12974

**Comment by howardjohn** [comment]
We have a chart now and making the chart idiomatic is being tracked in #12974. I think we can close this?
