### ISSUE TITLE
Istio control plane performance problems

### ISSUE THREAD

**Issue by HWPeiyao** [istio/istio#11724]
**Describe the bug**
We do some performance tests on istio-1.0.0 control plane recently. The result indicate some of the problems:
1.	When we have a large scale of services and pods, the pilot will consume a very large Memory **(2500 pods need at least 30GB).**
2.	Mixer CPU will cost **over 40 cores when under 100,000 QPS**. With the rapid increase of the cost, the process will soon use up the VM Memory, and the pod will be killed by kubelet. 
3.	When we use multiple mixer pods. The share of **CPU is not balanced**.

Any one meet with the same issue or have any ideas on solving those problems?

**Steps to reproduce the bug**
All the resources of data and control plane are enough, the test application is tomcat.

**Version**
kubernetes-1.11.3, istio-1.0.0

**Comment by douglas-reid** [comment]
@HWPeiyao I think you'll likely get more feedback on the discussion forum.  Can you open a thread on discuss.istio.io. The perf WG is the right place to raise these questions.

I'm going to close this issue for now.
