### ISSUE TITLE
Our gateway enablement flag is not working

### ISSUE THREAD

**Issue by linsun** [istio/istio#11733]
@shriram I don’t think we can use istio-ingressgateway with a dash in values.yaml, helm doesn’t allow it when you use it in if condition like .Values.gateways.istio-ingressgateway.enabled, it creates error when I run helm template.  (found this when working on https://github.com/istio/istio/pull/11732/files)

**Comment by shriram** [comment]
Please don't use my @ name here. I'm not part of this project.

**Comment by linsun** [comment]
sorry meant for @rshriram :)

**Comment by linsun** [comment]
update: wait for new installer to check this

**Comment by howardjohn** [comment]
This is "fixed" in the new installer with a bit of a hack. See https://github.com/istio/installer/blob/master/gateways/istio-ingress/templates/autoscale.yaml#L1

I researched a bit and that was the only real workaround I could find

**Comment by howardjohn** [comment]
Fixed in installer
