### ISSUE TITLE
2nd Service Entry causes both dns entries to route to 1st ServiceEntry

### ISSUE THREAD

**Issue by bradenwright** [istio/istio#11741]
**Describe the bug**
I have 2 Service Entries in 2 separate charts for CloudSQL.  CloudSQL is using private ip and I can connect to both of them if I turn off my Istio side cars.

Also each ServiceEntry / CloudSQL works if the other is not deployed.  If both are deployed then the 2 separate charts/deployments/pods both try to route to which ever was setup first.  I'll post some output below.

**Expected behavior**
I expect both ServiceEntries to function even if both charts are deployed

**Steps to reproduce the bug**
Not sure if it works with other external resources, but setup 2 cloudsql instances on private networks.  Then create 2 charts with deployments and serviceentries.  I can try things or share code if need.  Also need Istio installed with Egress

**Version**
Istio: 1.10
K8s: v1.10.12-gke.1

**Installation**
Helm Chart with Egress enabled

**Environment**
GKE

**Cluster state**
If request I'll gladly do it.

**Comment by bradenwright** [comment]
```
$ kc logs -f -n prod-app stats-586f47647d-4gh8v php

 // Clearing the cache for the prod environment with debug                      
 // false                                                                       

 [OK] Cache for the "prod" environment (debug=false) was successfully cleared.  

                                                              
                    Application Migrations                    
                                                              

No migrations to execute.
[13-Feb-2019 21:52:52] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
[13-Feb-2019 21:52:52] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
[13-Feb-2019 21:52:52] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
[13-Feb-2019 21:52:52] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
[13-Feb-2019 21:52:52] NOTICE: fpm is running, pid 1
[13-Feb-2019 21:52:52] NOTICE: ready to handle connections
```
```
$ kc describe serviceentry -n prod-app stats-cloudsql
Name:         stats-cloudsql
Namespace:    prod-app
Labels:       <none>
Annotations:  <none>
API Version:  networking.istio.io/v1alpha3
Kind:         ServiceEntry
Metadata:
  Cluster Name:        
  Creation Timestamp:  2019-02-13T21:52:26Z
  Generation:          1
  Resource Version:    293057
  Self Link:           /apis/networking.istio.io/v1alpha3/namespaces/prod-app/serviceentries/stats-cloudsql
  UID:                 a7172a6e-2fd9-11e9-b4c4-42010a84012e
Spec:
  Hosts:
    stats-cloudsql.private.example.com
  Location:  MESH_EXTERNAL
  Ports:
    Name:      tcp
    Number:    3306
    Protocol:  tcp
  Resolution:  DNS
Events:        <none>
```
NOTE: I changed the dns entry to example.com, but the dns entry I'm using does resolve

```
$ kc logs -f -n prod-app auth-84756978db-n4zgm php

 // Clearing the cache for the prod environment with debug                      
 // false                                                                       

 [OK] Cache for the "prod" environment (debug=false) was successfully cleared.  

                                                              
                    Application Migrations                    
                                                              

2019-02-13T22:11:09+00:00 [error] Error thrown while running command "doctrine:migrations:migrate --query-time --no-interaction --allow-no-migration". Message: "An exception occurred in driver: SQLSTATE[HY000] [1049] Unknown database 'auth'"

In AbstractMySQLDriver.php line 113:
                                                                               
  An exception occurred in driver: SQLSTATE[HY000] [1049] Unknown database 'a  
  uth'                                                                         
                                                                               

In PDOConnection.php line 50:
                                                  
  SQLSTATE[HY000] [1049] Unknown database 'auth'  
                                                  

In PDOConnection.php line 46:
                                                  
  SQLSTATE[HY000] [1049] Unknown database 'auth'  
                                                  

doctrine:migrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [--allow-no-migration] [--configuration [CONFIGURATION]] [--db-configuration [DB-CONFIGURATION]] [--db DB] [--em EM] [--shard SHARD] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<version>]
```

Error is b/c the database auth only exists on auth cloudsql and the database stats only exists on the stats database.

```
$ kc describe serviceentry auth-cloudsql -n prod-app
Name:         auth-cloudsql
Namespace:    prod-app
Labels:       <none>
Annotations:  <none>
API Version:  networking.istio.io/v1alpha3
Kind:         ServiceEntry
Metadata:
  Cluster Name:        
  Creation Timestamp:  2019-02-13T22:10:03Z
  Generation:          1
  Resource Version:    296017
  Self Link:           /apis/networking.istio.io/v1alpha3/namespaces/prod-app/serviceentries/auth-cloudsql
  UID:                 1cb596e5-2fdc-11e9-b4c4-42010a84012e
Spec:
  Hosts:
    auth-cloudsql.private.example.com
  Location:  MESH_EXTERNAL
  Ports:
    Name:      tcp
    Number:    3306
    Protocol:  tcp
  Resolution:  DNS
Events:        <none>
```

***************************************************************

If I delete the first chart, then it starts working

```
$ helm del --purge stats
release "stats" deleted

$ kc logs -f -n prod-app auth-84756978db-vxf6b php

 // Clearing the cache for the prod environment with debug                      
 // false                                                                       

 [OK] Cache for the "prod" environment (debug=false) was successfully cleared.  

                                                              
                    Application Migrations                    
                                                              

No migrations to execute.
[13-Feb-2019 22:16:45] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
[13-Feb-2019 22:16:45] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
[13-Feb-2019 22:16:45] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
[13-Feb-2019 22:16:45] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
[13-Feb-2019 22:16:45] NOTICE: fpm is running, pid 1
[13-Feb-2019 22:16:45] NOTICE: ready to handle connections
```

If I redeploy `stats` then `auth` keeps working and I can get `stats` working again by `helm del --purge auth`, so either one works fine but when both are deployed things break.

I've been reading over:

https://github.com/istio/istio/issues/6593
https://istio.io/docs/reference/config/istio.networking.v1alpha3/#ServiceEntry
https://istio.io/docs/reference/config/istio.networking.v1alpha3/#ServiceEntry-Endpoint
https://istio.io/docs/reference/config/istio.networking.v1alpha3/#ServiceEntry-Location
https://istio.io/docs/reference/config/istio.networking.v1alpha3/#ServiceEntry-Resolution
https://istio.io/blog/2018/egress-tcp/
https://istio.io/docs/tasks/traffic-management/egress/
https://preliminary.istio.io/docs/examples/advanced-gateways/wildcard-egress-hosts/

From what I can tell what I'm doing should work fine, but I don't know where to go from here, I don't think the last link is applicable but I maybe wrong.  Right now just trying without SSL, I was implement SSL as a 2nd iteration via CLoudSQL Proxy.

Any advice or things to try would be great, for now I turned off the istio sidecar on auth so I can deploy both but this is not desired.

**Comment by bradenwright** [comment]
Anyone have ideas?  This feels like its a pretty legit issue and I am currently blocked.  I've had to disable the istio sidecar for the time being.

**Comment by rshriram** [comment]
if there is no vip for a tcp service, we listen on 0.0.0.0:3306 .. so if you have two service entries with tcp 3306, no vips, only one of them will win unfortunately.

If you could make your app send traffic to some dummy VIP (eg 1.1.1.1), and you update the service entry to use that VIP in the `address` field, then things should work.

**Comment by bradenwright** [comment]
So I was able to get both working with the virtual ip, like follows:

```
$ kc describe serviceentry -n prod-app stats-cloudsql
Name:         stats-cloudsql
Namespace:    prod-app
Labels:       <none>
Annotations:  <none>
API Version:  networking.istio.io/v1alpha3
Kind:         ServiceEntry
Metadata:
  Cluster Name:        
  Creation Timestamp:  2019-02-13T21:52:26Z
  Generation:          1
  Resource Version:    293057
  Self Link:           /apis/networking.istio.io/v1alpha3/namespaces/prod-app/serviceentries/stats-cloudsql
  UID:                 a7172a6e-2fd9-11e9-b4c4-42010a84012e
Spec:
  Addresses:
    1.1.1.1
  Endpoints:
    Address:  stats-cloudsql.private.example.com
  Hosts:
    stats-cloudsql.private.example.com
  Location:  MESH_EXTERNAL
  Ports:
    Name:      tcp
    Number:    3306
    Protocol:  tcp
  Resolution:  DNS
Events:        <none>
```
```
$ kc describe serviceentry auth-cloudsql -n prod-app
Name:         auth-cloudsql
Namespace:    prod-app
Labels:       <none>
Annotations:  <none>
API Version:  networking.istio.io/v1alpha3
Kind:         ServiceEntry
Metadata:
  Cluster Name:        
  Creation Timestamp:  2019-02-13T22:10:03Z
  Generation:          1
  Resource Version:    296017
  Self Link:           /apis/networking.istio.io/v1alpha3/namespaces/prod-app/serviceentries/auth-cloudsql
  UID:                 1cb596e5-2fdc-11e9-b4c4-42010a84012e
Spec:
  Addresses:
    1.1.2.1
  Endpoints:
    Address: auth-cloudsql.private.example.com 
  Hosts:
    auth-cloudsql.private.example.com
  Location:  MESH_EXTERNAL
  Ports:
    Name:      tcp
    Number:    3306
    Protocol:  tcp
  Resolution:  DNS
Events:        <none>
```

This definitely lets me move forward, but I'd like to keep the ticket open.  Reason being it really makes it a pain to automate.  I'll explain, right now we create sql dbs, and other external resources via automation.  We install more the helm chart we've built for the 2 services more than once in every cluster.  This means that we can't hardcode an ip in the ServiceEntry, further we basically have to implement our own little dhcp type thing in our build pipelines, we deploy when PRs are open.  This is definitely not a clean option, I appreciate the help it does keep me moving forward.  Ok, for PRs specifically I'm gonna use a helm chart so I won't need the ServiceEntry but I still want to be able to build other envs which use CloudSQL without having to implement something like dhcp in the CI/CD pipeline or manually assigning a virtual ip that's not used in the cluster currently.  Also I'm deploying more and more services that are using the same data layers/ports so doing this manually for now is fine, but its gonna grow into a mess / problem in the near future.

Thanks again for the help, this got me unblocked!

**Comment by rshriram** [comment]
Do you need the service entry to use DNS?
If you set the resolution to NONE, then envoy will forward the traffic to the IP that the application requested.. In that case you could literally have just one service entry like this:

```
hosts:
- *.private.example.com
ports:
- name: tcp
   protocol: TCP
   port: 3306
resolution: NONE
```

Note that in the case above, any traffic for port 3306 will be forwarded to the intended destination. If you know that all your applications are using TLS to talk to *.private.example.com, then I suggest you set the protocol to TLS, to restrict the traffic to just *.private.example.com domains. [if you are using the latest 1.10, then simply setting the protocol to TLS is sufficient].

OTOH, if this is not TLS, i.e plain mySQL, then set the resolution to NONE (its a bit more permissive)

**Comment by bradenwright** [comment]
@rshriram Ok so this is working as explained, and I was able to get multiple dns entries working via wildcard.  A little weird that specific hostnames aren't supported but I'm working and it DRY'd out my above code so many thanks!

Can you explain what will collide and won't won't, specific reason I'm asking is that this got me working for multiple CloudSQL instances.  I also need the same cluster to connect to RDS which uses the same port(s) for mysql 3306.  The domain is completely different though, for eg:

```
examplerds-cluster.cluster-gjmcdget9c1o.eu-central-1.rds.amazonaws.com
```
My though is I can just create another hosts entry to the array of ServiceEntry like:
```
hosts:
- *.private.example.com
- *.rds.amazonaws.com
ports:
- name: tcp
   protocol: TCP
   port: 3306
resolution: NONE
```

I'll be testing soon, but I'd love a further explanation so I actually know how it works.  But being able to get it working is the most important steps so  again thanks so much for helping me move forward!

**Comment by bradenwright** [comment]
I'll make sure to close the ticket I just want to document a little more here in case anyone else runs into this

**Comment by vngzs** [comment]
Related underlying issue: #9784

**Comment by howardjohn** [comment]
not stale
