### ISSUE TITLE
Galley nil pointer dereference

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#11748]
**Describe the bug**

When Galley fails to initialize, it causes a nil pointer dereference.

```
2019-02-13T23:03:26.651593Z     fatal   Unable to initialize Galley Server: timed out waiting for the condition: the following resource type(s) were not found: [servicecontrols servicecontrolreports]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1a79942]

goroutine 43 [running]:
istio.io/istio/galley/pkg/server.(*Server).Run(0x0)
        /workspace/go/src/istio.io/istio/galley/pkg/server/server.go:217 +0x22
istio.io/istio/galley/pkg/server.RunServer(0xc4204b6f00, 0x21fac60, 0xc42002eeb0, 0x21fac60, 0xc42002ef00)
        /workspace/go/src/istio.io/istio/galley/pkg/server/server.go:277 +0x1b3
created by istio.io/istio/galley/cmd/galley/cmd.GetRootCmd.func2
        /workspace/go/src/istio.io/istio/galley/cmd/galley/cmd/root.go:88 +0x3c8
```

**Expected behavior**
It seems like it should exit gracefully - it is clearly detected that Galley doesn't initialize, as it is logged, so we should probably just exit if so.

**Version**
Istio 1.1 snapshot 6

**Comment by ozevren** [comment]
Hi @howardjohn, Could you double check that this is with snapshot 6 binaries?
We fixed an issue in this area some time ago, which should be included in snapshot 6. I double checked the stack in this bug and it doesn't align with the code that snapshot 6 is cut from.

**Comment by howardjohn** [comment]
You are right it doesn't. Maybe I wasn't running snapshot 6. 

Still seems like it should be an issue from looking at the code though:
https://github.com/istio/istio/blob/6113e155ac85e2485e30dfea2b80fd97afd3130a/galley/pkg/server/server.go#L323-L328

We detect that it failed to initialize (`s` is nil), then we call `s.Run()`

**Comment by ozevren** [comment]
Fatalf kills the process

**Comment by howardjohn** [comment]
Oops, definitely must have been running an old version then. Thanks.
