### ISSUE TITLE
HPA for galley

### ISSUE THREAD

**Issue by clyang82** [istio/istio#11754]
Galley acts as MCP server which is connected by pilot and mixer. if there are many pilot and mixer instances running in the environment, does Galley have the performance issue? do we need to consider to support galley auto-scaling?

@ayj @ozevren any thoughts?

**Comment by ozevren** [comment]
Our latest tests show there is no performance issue. Copy pasting from some of the investigation that @ayj did:
```
v11mcp test cluster has been running the release-1.1-20190207-09-16 daily for the last 5 days. 
Galley resource usage has been stable at ~105mb virtual memory and CPU never bursting above 180m cpu (.18 vCPU). 
15 telemetry pods, 1 policy, 1 pilot, and 20 mcpc agents for additional load testing.

Also, increasing the number of mcpc agents to 100 increased memory use by about 30mb across the board (virtual, heap, etc). CPU went up to 300m vCPU while new clients were connected and then dropped back down to 150m vCPU. In practice, we probably won't see that number of Mixer/Pilot connected to Galley, but it does show that we can keep up with a sudden increase in load.
```

**Comment by ozevren** [comment]
Serving path of Galley is pretty efficient. The config snapshots are already pre-calculated. Per client additional cost is currently relatively low. CRD count and config size is the main impactors (and I suspect endpoints support will be as well, once it lands). Those will not be helped by HPA.

**Comment by clyang82** [comment]
@ozevren Good to know that. That means 1 galley replica can meet the requirements. right?

**Comment by ayj** [comment]
One replica should be okay in the default / demo install. We'll need to revisit when endpoints support is on-by-default. 

Administrators of larger production clusters might also consider increasing the replica count as an insurance policy given the relatively low resource overhead (vs. pilot / mixer).
