### ISSUE TITLE
Upgrade issues: options renamed can cause major upgrade problem

### ISSUE THREAD

**Issue by costinm** [istio/istio#11759]
For tracking/reverting the changes in 1.1 - a separate issue already exists for 1.0.6.

This is critical/blocker IMO, at least for grafana pass and policy -> istio-policy and similar changes.
Initial review shows about 5 risky changes, and dozens of changes in tracing that may be P2.

**Comment by duderino** [comment]
It'd be nice to know which commit(s) need to be reverted

**Comment by munrodg** [comment]
Working as intended.  Will document behavior.
