### ISSUE TITLE
Confusing error message from istioctl validate

### ISSUE THREAD

**Issue by esnible** [istio/istio#11760]
`istioctl validate -f samples/httpbin/httpbin.yaml`

yields

Error: error validating resource (/v1, Kind=Service Name=httpbin Namespace=): mixer API validation is not supported

and errorlevel 255.  (error codes > 127 are reserved for serious errors; using 255 messes up interop with tools like xargs).

**Comment by esnible** [comment]
The error message is because of https://github.com/istio/istio/issues/4887

@ayj Should `istioctl` consider validating Istio Annotations on non-Istio objects?  For example, if I had a Deployment with

```
    metadata:
      annotations:
        sidecar.istio.io/inject: "flase"
```

... (mispelled `false`) I would expect `istioctl validate` to say "invalid annotation value for sidecar.istio.inject in deployment httpbin".  Currently only Istio non-Mixer CRDs are validated.

**Comment by ayj** [comment]
`istioctl validate` was originally intended to provide limited client-side configuration validation, similar to what the server-side webhook provides. Checking non-istio objects may be more appropriate for something like https://github.com/aspenmesh/istio-vet.
