### ISSUE TITLE
Race condition getting pod IP and sending listeners list

### ISSUE THREAD

**Issue by rvansa** [istio/istio#11779]
**Describe the bug**
When I start many nodes concurrently some nodes get stuck, the sidecar never boots. This is happening because pod's IP:port is not among the listeners list; `pilot/pkg/serviceregistry/kube/controller.go:GetProxyServiceInstances()` tries to get pod info from PodCache on the controller, but gets `nil` at that point. Adding some debug logs I've found that `pilot/pkg/serviceregistry/kube/pod.go:event(...)` that updates the ip - pod mapping arrives to late. It seems that the list of listeners is not generated again (not sure if that is the problem).

**Expected behavior**
All sidecars boot.

**Steps to reproduce the bug**
Create 20 deployment configurations that will spawn 20 pods... usually at least one of them gets stuck.

**Version**
Istio master as of 2019-2-14

**Installation**
Helm charts.

**Environment**
Openshift 3.10

**Comment by rvansa** [comment]
It seems I can fix this by calling `pc.c.XDSUpdater.ConfigUpdate(true)` instead of `pc.c.XDSUpdater.WorkloadUpdate(...)` in `pod.go:event(...)`; I doubt this is a correct fix as it could result in excessive pushes, though. I could limit it the full push to cases when the IP is set in PodCache for the first time; would that be acceptable?

**Comment by andraxylia** [comment]
This is a known timing issues, Pods and Endpoints event can be received in any order.

I thought this was taken care of. cc @costinm who can comment more on the XDSUpdater.

Please keep in mind we will move to synthetic service entries generated in Galley, see PR #11293 , and we will ultimately get rid of this code in pilot.

**Comment by rvansa** [comment]
@andraxylia Thanks for the response. IIUC, even when you let Pilot listen to updates from Galley rather than directly from Kubernetes, the timing issue will be there, wouldn't it?
The fix is pretty simple: https://github.com/rvansa/istio/commit/2fdcf5824110372e928a643b9eff0dde050e3fa7 - should I file this as PR or just wait after #11293 gets integrated (and test then)?
