### ISSUE TITLE
Cleanup StatsD support in helms

### ISSUE THREAD

**Issue by incfly** [istio/istio#11789]
**Describe the bug**
https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/values.yaml#L198
states that the statsd support is deprecated, however, we still have lots of helms value files, binary flags reference `statsd` if we do a grep in istio/istio

**Expected behavior**

- Remove the helm references
- Deprecate the flag.

**Comment by howardjohn** [comment]
Possibly related: I suspect, but haven't verified, that `statsd` will never be set here:

https://github.com/istio/istio/blob/ee867e932bd5be1fc33da583233448bc58a59b93/tools/deb/envoy_bootstrap_v2.json#L288-L300

**Comment by mandarjog** [comment]
It is still deprecated, but possible.
