### ISSUE TITLE
Attach a sidecar to Galley

### ISSUE THREAD

**Issue by geeknoid** [istio/istio#11787]
We should be using a sidecar on Galley to enable full support for mutual TLS and OAuth over inbound and outbound MCP channels, along with SDS-based provisioning.

We need to eliminate custom auth solutions in the platform and capitalize on Envoy where possible.

The challenge with applying a sidecar to Galley is around bootstrapping, given that Galley is responsible for delivering config.

@wenchenglu @costinm

**Comment by kyessenov** [comment]
Is this for both inbound and outbound connections? We could generalize the existing static bootstraps for pilot and mixer to cover galley deployments. There is not much "dynamism" in these config files, so they can be created at install/customization time avoiding runtime dependency on pilot/galley. We'll automatically get internal telemetry as well.

**Comment by ozevren** [comment]
Per @costinm, this should be 1.1.x. Set the milestone 1.1.

**Comment by geeknoid** [comment]
Why do we need this before 1.2?

We need to resist the temptation to do feature work in patch releases.

**Comment by kyessenov** [comment]
May I suggest to consolidate the existing bootstraps for mixer and pilot with future galley one? We have a config proliferation problem.

**Comment by ayj** [comment]
(from @costinm in other thread)
>I think this should be prioritized for 1.1.1 - I did some initial config/testing with
https://github.com/istio-ecosystem/istio-installer/tree/master/istio-control/istio-config/templates/....
( still need to put the proper cert)

> The goal is to make Galley MCP consistent with Mixer and Pilot - use Spiffe certs ( so it doesn't behave differently or have problems in multicluster), and eventually can use SDS. Using Galley in MC is needed by few users, and switching to SDS (to remove the use of k8s secrets in such environments) is required as well.

We still need DNS compatible certs for the k8s validating webhook. In the near term (1.1x) those DNS certs are provided by Citadel (via ???). Longer term (1.2+) we'd like to remove that dependency have have Galley (or an operator) provision a self-signed cert.

**Comment by geeknoid** [comment]
So there doesn't appear to be any emergency to get this into 1.1.x. We
should wait until 1.2 unless there is a security concern.

**Comment by duderino** [comment]
Apologies for the poor organization here.

If 1.1 it should be milestone 1.1 with P0
else if 1.1.x, it should be milestone 1.1 with P1
else if 1.2 it can have any priority you want

**Comment by costinm** [comment]
It is a priority because it prevents adoption of SDS (secret discovery secret) and removal of K8S secret.
And it's currently broken for multicluster - due to the hardcoded DNS cert. 

Both are bugs in features we expect to be working in 1.1.

**Comment by costinm** [comment]
(using SDS is also required for integration with other identity providers )

**Comment by costinm** [comment]
BTW - it may not have to be tied to 1.1.x - I already added it to the istio-ecosystem/installer, which is version independent - so uses who need SDS or multicluster can use the new installer with 1.1.0 if they 
want, or with master or any other version of Istio that the installer supports.

**Comment by wattli** [comment]
> It is a priority because it prevents adoption of SDS (secret discovery secret) and removal of K8S secret.
> And it's currently broken for multicluster - due to the hardcoded DNS cert.

It's fixed in https://github.com/istio/istio/pull/11986

> 
> Both are bugs in features we expect to be working in 1.1.

**Comment by costinm** [comment]
#11986 allows arbitrary DNS names - adding sidecar is using SPIFFE identity for MCP instead of DNS.

MCP needs DNS cert for kubeapi server, on the http port - but there is no need for it on the GRPC port.

Short term - it's fine to use the DNS, with the additional fix - but long/medium term and with the new installer I would rather have Galley consistent with Pilot/Mixer and all other mesh services.

**Comment by myidpt** [comment]
This feature makes sense to me. Two questions:
1. Do we plan to add the sidecars to webhooks as well?
2. Have we started working on this? Is 1.2 the target for this feature?

**Comment by ozevren** [comment]
There already is a sidecar in the installer repo. Closing this.
