### ISSUE TITLE
Officially recommended way to install?

### ISSUE THREAD

**Issue by MarcMielke** [istio/istio#11783]
What is the officially recommended installation procedure via `helm` for any given LTS (K8S v1.13.2 on AWS, if that matters) ?

- checkout the repo, then `helm install...` from master
- OR checkout the repo, then `git checkout release-1.0` (how do I know which LTS I would be on?), then run `helm install...` 
- OR checkout the repo, then `git checkout tags/1.0.6 -b branch2InstallFrom`, then run `helm install...` 
- OR download the release source for any LTS, then `helm install...`
- OR some other way I missed

Can't get any deterministic, idempotent behaviour. What am I getting wrong?

Also: Out of curiosity.. why is there no istio helm chart in https://github.com/kubernetes/charts stable/incubator channels?

**Comment by 4c74356b41** [comment]
whats wrong with official docs on this: https://istio.io/docs/setup/kubernetes/quick-start/ ?

**Comment by MarcMielke** [comment]
nothing wrong, figured that out in the meantime, thx! closing this.
