### ISSUE TITLE
[Minimal Install] Rendering core components to kubernetes manifest fails

### ISSUE THREAD

**Issue by vishal-yadav** [istio/istio#11781]
**Describe the bug**
When installing with [helm template](https://preliminary.istio.io/docs/setup/kubernetes/minimal-install/#option-1) option following error is encountered while rendering core components to k8s manifest:
```
$ helm template install/kubernetes/helm/istio --name istio --namespace istio-system \
   --values install/kubernetes/helm/istio/values-istio-minimal.yaml >> $HOME/istio-minimal.yaml
Error: found in requirements.yaml, but missing in charts/ directory: sidecarInjectorWebhook, security, ingress, gateways, mixer, nodeagent, pilot, grafana, prometheus, servicegraph, tracing, galley, kiali, istiocoredns, certmanager, istio-cni
``` 

**Expected behavior**
Rendering to k8s manifest should finish successfully.

**Steps to reproduce the bug**
1. Download istio 1.1 snapshot 
```
$ export export ISTIO_VERSION=1.1.0-snapshot.6
$ curl -L https://git.io/getLatestIstio | sh -
```
2. Install all the Istio’s Custom Resource Definitions or CRDs for short via kubectl apply, and wait a few seconds for the CRDs to be committed in the Kube api-server:
`$ for i in install/kubernetes/helm/istio-init/files/crd*yaml; do kubectl apply -f $i; done`
3. Render Istio’s core components to a Kubernetes manifest called istio-minimal.yaml:
```
$ cat install/kubernetes/namespace.yaml > $HOME/istio-minimal.yaml
$ helm template install/kubernetes/helm/istio --name istio --namespace istio-system \
  --values install/kubernetes/helm/istio/values-istio-minimal.yaml >> $HOME/istio-minimal.yaml
```

**Version**
$ istioctl version
version.BuildInfo{Version:"1.1.0-snapshot.6", GitRevision:"14777199b85ba56ebca2a4516afff33c97199eb4", User:"root", Host:"f0f1db73-2fb5-11e9-86e9-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-snapshot.5-156-g1477719"}

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T10:09:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.6-gke.6", GitCommit:"a2fae0aa5d813f814d667711324501312b76e64f", GitTreeState:"clean", BuildDate:"2019-01-18T19:40:57Z", GoVersion:"go1.10.3b4", Compiler:"gc", Platform:"linux/amd64"}

**Installation**
Minimal install via helm template

**Environment**
Google Kubernetes Engine

**Cluster state**
NA

**Comment by vishal-yadav** [comment]
Step 5: Install the istio chart [using tiller (helm install)](https://preliminary.istio.io/docs/setup/kubernetes/minimal-install/#option-2) also fails with above error.

**Comment by vishal-yadav** [comment]
Okay so [Minimal Install](https://preliminary.istio.io/docs/setup/kubernetes/minimal-install/#installation-steps) should also explicitly mention to **update helm dependencies** before installation as mentioned in general helm installation [Installation with Helm](https://preliminary.istio.io/docs/setup/kubernetes/helm-install/#installation-steps) section.

After updating helm dependencies installation is successful.

**Comment by ymesika** [comment]
The need to call `helm dep update` has been removed very recently so in the next daily build or RC there won't be a need for it.
