### ISSUE TITLE
Adjust rate intervals on dashboard queries to support large scale clusters (and traffic)

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio#11799]
**Describe the feature request**
At scale, we have observed issues (grafana fails to render data) with queries that rely on `irate` calculations using `30s` intervals. Experimentally, changing these intervals to `5m` allows the queries to return in grafana and render data.

**Describe alternatives you've considered**
Provide recording rules in prometheus config that will precompute the data to ease load on prometheus. We should consider this as well.

**Additional context**

**Comment by howardjohn** [comment]
@douglas-reid sounds like this is done?

**Comment by douglas-reid** [comment]
@howardjohn indeed. thanks.
