### ISSUE TITLE
Fault injection support for HTTP2/gRPC

### ISSUE THREAD

**Issue by kbhattac** [istio/istio#11815]
[Fault injection](https://istio.io/docs/reference/config/istio.networking.v1alpha3/#HTTPFaultInjection) is right now only supported for HTTP/1.1
A lot of microservices use gRPC/HTTP2 for intercommunication and Envoy can't be consistently configured in the same way to simulate faults in such use cases.

**Comment by dansiviter** [comment]
This would be useful for testing the usage of GCP APIs which often rely on gRPC.

**Comment by ckcd** [comment]
I have confirmed that `delay` in Fault injection can support gRPC/HTTP2.

And the `abort` in Fault injection can NOT support gRPC/HTTP2 which is represented in source code:

```
            switch a := in.Abort.ErrorType.(type) {
		case *networking.HTTPFaultInjection_Abort_HttpStatus:
			out.Abort.ErrorType = &xdshttpfault.FaultAbort_HttpStatus{
				HttpStatus: uint32(a.HttpStatus),
			}
		default:
			log.Warnf("Non-HTTP type abort faults are not yet supported")
			out.Abort = nil
		}
            }
```
