### ISSUE TITLE
https://github.com/istiPreliminary 1.1 Security documentation for verifying no mesh policy is incorrect

### ISSUE THREAD

**Issue by bdecoste** [istio/istio#11821]
**Describe the bug:**
{{
https://preliminary.istio.io/docs/tasks/security/authn-policy/

$ kubectl get policies.authentication.istio.io --all-namespaces
No resources found.

$ kubectl get meshpolicies.authentication.istio.io
No resources found.

**Actual behavior:**
$ kubectl get meshpolicies.authentication.istio.io
NAME      AGE
default   1m
$ kubectl get policies.authentication.istio.io --all-namespaces
NAMESPACE      NAME                          AGE
istio-system   grafana-ports-mtls-disabled   1m

}}

**Expected behavior**
{{
See description
}}

**Steps to reproduce the bug**
{{
Follow "Before you begin" steps
}}

**Version**
{{
istio-1.1.0-snapshot.6
}}

**Installation**
{{
From "Before you begin"
$ kubectl apply -f install/kubernetes/istio-demo.yaml
}}

**Environment**
{{
OpenShift Container Platform 3.11
}}

**Cluster state**
{{ N/A }}

**Comment by wattli** [comment]
https://github.com/istio/istio.io/pull/3376 is the fix
