### ISSUE TITLE
gen-jwt.py referenced in preliminary 1.1 doc is missing

### ISSUE THREAD

**Issue by bdecoste** [istio/istio#11826]
**Describe the bug**
{{
https://preliminary.istio.io/docs/tasks/security/authn-policy/

security/tools/jwt/samples/gen-jwt.py is missing from release distro but available and working properly in Istio source. Referenced in "End user authentication" section of doc. 
}}

**Expected behavior**
{{
See description
}}

**Steps to reproduce the bug**
{{
Follow  "End user authentication" steps
}}

**Version**
{{
istio-1.1.0-snapshot.6
}}

**Installation**
{{
From "Before you begin"
$ kubectl apply -f install/kubernetes/istio-demo.yaml
}}

**Environment**
{{
OpenShift Container Platform 3.11
}}

**Cluster state**
{{ N/A }}

**Comment by munrodg** [comment]
@esnible Can you pick this one up?

**Comment by frankbu** [comment]
This seems to be a problem in 1.0.x too. The reference to the `.py` file from the doc seems to go back to this PR: https://github.com/istio/istio.io/pull/1945

@diemtvu can you fix the doc, or arrange for the jwt sample files to be included in the distribution.
