### ISSUE TITLE
Update 1.1 preliminary doc for multiple default-token secrets

### ISSUE THREAD

**Issue by bdecoste** [istio/istio#11825]
**Describe the bug**
{{
https://preliminary.istio.io/docs/tasks/security/authn-policy/

Doc has:
TOKEN=$(kubectl describe secret $(kubectl get secrets | grep default | cut -f1 -d ' ') | grep -E '^token' | cut -f2 -d':' | tr -d '\t')

To support multiple default-token secrets:
TOKEN=$(kubectl describe secret $(kubectl get secrets | grep default-token | cut -f1 -d ' ' | head -1) | grep -E '^token' | cut -f2 -d':' | tr -d '\t')

}}

**Expected behavior**
{{
See description
}}

**Steps to reproduce the bug**
{{
Follow "Request from Istio services to Kubernetes API server" steps
}}

**Version**
{{
istio-1.1.0-snapshot.6
}}

**Installation**
{{
From "Before you begin"
$ kubectl apply -f install/kubernetes/istio-demo.yaml
}}

**Environment**
{{
OpenShift Container Platform 3.11
minikube version: v0.34.1 
}}

**Cluster state**
{{ N/A }}

**Comment by wattli** [comment]
It's a dup of #11908
