### ISSUE TITLE
ServiceEntry - create an external service and load balance on endpoints 

### ISSUE THREAD

**Issue by iftachsc** [istio/istio#11824]
Hello,

I have 3 external vms
Running redis as part of a cluster. There is no loadbalancer or a vip. I want to somehow register inside the mesh a service with fictional hostname that will translate to loadbalancing on these 3 redis vms. These vms has resolvable hostnames.I tried to create a combination of a Kubernetes service(without selector) with manually created endpoints  and a service entry so pods inside the mesh can address the host (service name and host in serviceentry) and to be able to be loadbalancer on these 3 endpoints. Couldn’t make it work and also this make me register the ips. . I expected to be able to do this only with servicenetry with endpoints set in its spec with DNS as the resolution. but cannot make this work. Is this possible? Thanks!

**Comment by mabushey** [comment]
You could run haproxy in your cluster configured to do this. I'm not aware of egress load balancing in either k8s or Istio.

**Comment by iftachsc** [comment]
In Kubernetes you can create a service and then creates the endpoints it’s loadbalancing on manually with the iOS of the actrual external vms and it will do load balancing on them as long as they match its labels just like regular pods. I could do that but then I would have to set the serviceentry with something like serviceName.namespace which is ok but I mean use a dns and I choose. Dns record for round robin dns is not good because then envoy woudnt count the endpoints as something it can eject or do circuit breaking on so it can try connect every few minutes to a faulty vm.
