### ISSUE TITLE
Error with CRD's on 1.1 sn6

### ISSUE THREAD

**Issue by ekarlso** [istio/istio#11827]
Error installing 1.1 snapshot 6

**Expected behavior**
helm install working fine

**Steps to reproduce the bug**
Install using helm chart for the 1.1 sn6 release from github

**Version**
kube 1.12.x, kubectl 1.12.x

**Installation**
helm chart from the sn6 release tarball

**Environment**
Azure AKS vanilla

Not working.

**Comment by esnible** [comment]
You didn't report the actual problem but the instructions for installing Istio CRDs with Helm have changed.  See the instructions at

https://preliminary.istio.io/docs/setup/kubernetes/helm-install/

Try the options there, let us know if that solves your problem.
