### ISSUE TITLE
[Support] Updating Envoy SHA in 1.0 to patch a bug in Envoy

### ISSUE THREAD

**Issue by adityats2020** [istio/istio#11830]
I am looking to pull this fix from Envoy into istio-proxy (release 1.0) and had some questions about it: https://github.com/envoyproxy/envoy/commit/d646949e0534557084196dea850c26599e53f1b8

1. Is it sufficient to run Circle CI builds for `istio-proxy`? Or is there any integration test that involves `istio` repo that includes mixer and pilot?
2. `linux_asan` and `linux_tsan` builds are failing with missing libraries. I searched for similar issue and looks like this could be due to insufficient resources in Circle CI for the free plan. Can you confirm if I will need un upgraded plan to run these tests?
`clang++-7: error: unable to execute command: Killed`
3. How do I build a docker image of istio-proxy? I think` make docker` is only applicable for the main `istio/istio` repository.

**Comment by esnible** [comment]
When I build custom sidecar issues for testing I do something like this:

```
GOOS=linux make pilot-agent
HUB=esnible TAG=issue11322 GOOS=linux make docker.proxyv2
docker push esnible/proxyv2:issue11322
```

"HUB" is my Docker account, and TAG is some tag I am using so that I can keep track of which bug I am attempting to fix.  Replace those with your own values.

After I have pushed a personal test build to Docker hub I do `kubectl -n istio-system edit cm istio-sidecar-injector` and replace `gcr.io/istio-release/proxyv2:<tag>` with my private image.

**Comment by adityats2020** [comment]
Thanks @esnible I am able to build using the steps you provided. Although, I am not sure how to build using the modified istio-proxy instead of the default one.
I have created a clone repo with the patch I need at https://github.com/adityats2020/proxy. The `make docker.proxyv2` build step seems to obtain the built artifacts from a specific location that is defined in `bin/init.sh`. I am not sure how to generate these artifacts from my repository, and how to link them in this script. Any tips for doing that?

**Comment by adityats2020** [comment]
Digging into the build files a bit, it looks like pre-built istio proxy binaries are required for building the docker image.
https://github.com/istio/istio/blob/master/bin/init.sh#L93-L97

[This script](https://github.com/istio/proxy/blob/master/script/release-binary) seems to be the place where the binary is built. I don't understand the context behind having to build this binary in Ubuntu as seen in [code here](https://github.com/istio/proxy/blob/master/script/release-binary#L46-L48). There didn't seem to be any actual dependency on Ubuntu in the script after that. I commented those lines out and was able to build a binary.
Corresponding docker image does not start up. The built binary is definitely not the binary for building docker image. The size of this binary compared to a valid binary in google repo is way too small. 

I am very likely doing things I don't have to. Would appreciate if someone can help me build this docker image.
