### ISSUE TITLE
Log levels for Istio are not easily configurable and missing documentation

### ISSUE THREAD

**Issue by GregHanson** [istio/istio#11847]
**Describe the bug**
Istio control plane and sidecars have options for configuring log verbosity level but are not exposed as something configurable via helm.  Also control plane log level requires `scope:level` and some references in the charts still refer to just a `level` format.

Gateways include incorrect `--log_output_level info` example in helm charts:
https://github.com/istio/istio/blob/release-1.1/install/kubernetes/helm/istio/charts/gateways/templates/deployment.yaml#L105

**Expected behavior**
To be able to configure istio control plane and sidecar proxy log levels via helm.
Envoy proxy instances have `--proxyLogLevel trace|debug|info|warning|error|critical|off`
Control plane components have different scopes depending on component, but expect to at least be able to configure default log level, i.e. `--log_output_level default:warn`

**Comment by jaredeis** [comment]
This is an issue for us as we ship logs to Sumologic and istio is very noisy at info level.

**Comment by GregHanson** [comment]
@jaredeis is the log level issue a problem at the istio control plane, i.e. pilot/mixer/citadel?  Or is this a problem at the sidecar log level? Or both?  We are working on having an optimized set of helm defaults optimized for performance in 1.1.  For example: https://github.com/istio/istio/pull/11476

**Comment by jaredeis** [comment]
It's mixer that's too noisy for us.

**Comment by esnible** [comment]
Is the basic idea to modify the istio-sidecar-injector ConfigMap through Helm allowing choices made in Helm to become `--proxyLogLevel` args on the sidecar?

Envoy lets the log level be configured dynamically.  I use `kubectl exec $(kubectl get pod --selector app=httpbin --output jsonpath='{.items[0].metadata.name}') -c istio-proxy -- curl -X POST http://localhost:15000/logging?level=info` but  would it help users to put this into a CLI command lke `istioctl proxy-logging` that would perhaps be easier to find and could possibly affect >1 pod in a single invocation?

Envoy exposes loggers: admin,  assert, backtrace, client, config, connection, dubbo, file, filter, , grpc, hc, health_checker, http, http2, hystrix, lua, main, misc, mongo, quic, pool, rbac, redis, router, runtime, stats, secret, tap, testing, thrift, tracing,  upstream.  Do we want an option to customize that?

**Comment by GregHanson** [comment]
@esnible I like the idea of adding the `proxy-logging` command to istioctl.  I don't think there needs to be logger type granularity though - it seems like something specific for advanced users whereas configuring all loggers to the same log level would cover the majority of use cases.

To address @jaredeis issue with istio control plane logging verbosity, that needs to be configured via helm.  See https://github.com/istio/istio/pull/12639
