### ISSUE TITLE
packaging or documentation error for JWT authentication

### ISSUE THREAD

**Issue by murarisumit** [istio/istio#11843]
**Describe the bug**

Got the error while testing https://preliminary.istio.io/docs/tasks/security/authn-policy/#end-user-authentication section.

For getting jwt token snippet gives: 

```bash
TOKEN=$(security/tools/jwt/samples/gen-jwt.py security/tools/jwt/samples/key.pem --expire 5)
for i in `seq 1 10`; do curl --header "Authorization: Bearer $TOKEN" $INGRESS_HOST/headers -s -o /dev/null -w "%{http_code}\n"; sleep 1; done
```

but these files `security/tools/jwt/samples/gen-jwt.py`, `security/tools/jwt/samples/key.pem` are not there in https://github.com/istio/istio/releases/download/1.1.0-snapshot.6/istio-1.1.0-snapshot.6-osx.tar.gz.

**Expected behavior**
Either the above files/folder should be in tar or some snippet should be there from where user and easily download them.

**Steps to reproduce the bug**
Download: https://github.com/istio/istio/releases/download/1.1.0-snapshot.6/istio-1.1.0-snapshot.6-osx.tar.gz
Extract tar files.
`security` folder doesn't exist.

**Version**
1.1.0-snapshot.6

**Installation**
Followed instruction in: https://preliminary.istio.io/docs/setup/kubernetes/minimal-install/

**Environment**
OS=mac

**Comment by esnible** [comment]
May we close this as a duplicate of https://github.com/istio/istio/issues/11826 ?

**Comment by duderino** [comment]
closing as duplicate of https://github.com/istio/istio/issues/11826
