### ISSUE TITLE
preliminary 1.1 rbac-groups doc has inconsistent namespace

### ISSUE THREAD

**Issue by bdecoste** [istio/istio#11848]
**Describe the bug**
{{
https://preliminary.istio.io/docs/tasks/security/rbac-groups/

Step 1 identifies the namespace as "rbac-listclaim-test-ns" but the command uses "rbac-groups-test-ns"
}}

**Expected behavior**
{{
Consistent namespace
}}

**Steps to reproduce the bug**
{{
Follow "Before you begin" steps
}}

**Version**
{{
istio-1.1.0-snapshot.6
}}

**Installation**
{{
From "Before you begin"
$ kubectl apply -f install/kubernetes/istio-demo-auth.yaml
}}

**Environment**
{{
OpenShift Container Platform 3.11
}}

**Cluster state**
{{ N/A }}

**Comment by lei-tang** [comment]
The PR fixes this issue is at: https://github.com/istio/istio.io/pull/3364
