### ISSUE TITLE
CircleCI integration tests broken - master-latest-daily charts not found

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#11853]
CircleCI integration tests are failing with error:

```
Error: Looks like "https://storage.googleapis.com/istio-prerelease/daily-build/master-latest-daily/charts" is not a valid chart repository or cannot be reached: Failed to fetch https://storage.googleapis.com/istio-prerelease/daily-build/master-latest-daily/charts/index.yaml : 404 Not Found
```

Example: https://circleci.com/gh/istio/istio/330161?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by ymesika** [comment]
I guess the easiest path to fixing it is to merge `release-1.1` into `master`.
Otherwise do some cherry-picking (#11805 specifically with all of @sdake helm changes).

**Comment by louiscryan** [comment]
Hey Yossi - I tried this but am still getting issues

**Comment by sdake** [comment]
The release-1.1 charts are here:
helm repo add istio.io "https://gcsweb.istio.io/gcs/istio-prerelease/daily-build/release-1.1-latest-daily/charts/

**Comment by sdake** [comment]
As far as I can tell, the master daily charts release process is busted and is not being automatically pushed by the infrastructure.  It looks like the bucket has been removed.  They were previously at this address:

https://storage.googleapis.com/istio-prerelease/daily-build/master-latest-daily/charts

See:
https://github.com/istio/istio.io/pull/3249/files

To get things unblocked, I'd recommend just using the release-1.1 chart address in https://github.com/istio/istio/issues/11853#issuecomment-465376834 and hunt down the change that broke the gate.

One of the problems with our process of merging in release-1.1 without a postsubmit gate is software isn't gated, and I suspect not built nor pushed automatically - but I am not certain.

@linsun any ideas?

**Comment by pitlv2109** [comment]
Is anyone working on fixing this issue? Individual PR or branch can add a workaround by using a working charts repo, e.g. `release-1.1-latest-daily/charts/`, but I think an official fix would be ideal. Thanks!

**Comment by irisdingbj** [comment]
I believe @louiscryan is working on a fix for the problem

**Comment by utka** [comment]
The reason is we can not build master since 17 Feb, and the  master-latest-build was deleted  for latest available build 16th. I think it is deleted by script before pushing new version, but because new version does not exist, it fails.
https://storage.googleapis.com/istio-prow/logs/release-daily/216/build-log.txt

**Comment by utka** [comment]
I am triggering daily build manually now

**Comment by utka** [comment]
I manually triggered 
gsutil -q cp -r 'gs://istio-prerelease/daily-build/master-20190216-09-16/*' gs://istio-prerelease/daily-build/master-latest-daily/

So master-latest-daily exists now, still going to trigger new daily release

**Comment by ozevren** [comment]
Can we close this?
