### ISSUE TITLE
sidecar.istio.io/inject does not work

### ISSUE THREAD

**Issue by incfly** [istio/istio#11854]
**Describe the bug**
- Deploy Istio, label default namespace `sidecar-inject=enabled`.
- Annotate the Deployment with `sidecar.istio.io/inject: false`
- Deploy workload.
- Sidecar is still injected.

I scanning the code, grepping the "sidecar.istio.io/inject", there's no go code reading this annotation and make decisions based on the value of the annotation. https://github.com/istio/istio/search?l=Go&q=%22sidecar.istio.io%2Finject%22

Only this one, https://github.com/istio/istio/blob/master/pilot/pkg/kube/inject/inject.go#L58, but it's just a validation function... So the implementation explains the behavior as well.

**Expected behavior**
When the annotation is specified as `false`, according to the [documentation](https://istio.io/help/ops/setup/injection/),  that particular deployment should have auto-injection disabled.

**Steps to reproduce the bug**
Install istio, label default namespace with autoinject enabled. Deploy a workload.

**Version**
release-1.1 snapshot6.

**Environment**
GKE

**Comment by incfly** [comment]
@nmittler @ayj can any of you confirm this is a bug and the expected behavior?

**Comment by ayj** [comment]
https://istio.io/help/ops/setup/injection/#the-result-of-sidecar-injection-was-not-what-i-expected

Verify that the annotation is added to the pod template spec’s metadata.

**Comment by incfly** [comment]
The injection template
```
kubectl get mutatingwebhookconfiguration istio-sidecar-injector -o yaml | grep "namespaceSelector:" -A5
  namespaceSelector:
    matchLabels:
      istio-injection: enabled
  rules:
  - apiGroups:
    - ""
```

The per deployment annotation is there.
```
$ kubectl -n istio-system get configmap istio-sidecar-injector -o jsonpath='{.data.config}' | head
policy: enabled
template: |-
  rewriteAppHTTPProbe: false
  initContainers:
  [[ if ne (annotation .ObjectMeta `sidecar.istio.io/interceptionMode` .ProxyConfig.InterceptionMode) "NONE" ]]
  - name: istio-init
    image: "docker.io/istio/proxy_init:1.1.0-snapshot.6"
    args:
    - "-p"
    - [[ .MeshConfig.ProxyListenPort ]]
```

**Comment by ayj** [comment]
The annotation needs to be made to the pod template spec's metadata and not the deployment's metadata (e.g. see https://github.com/istio/istio/blob/5f61fbdceeb6321e2f757926cabe715166f685c8/install/kubernetes/helm/subcharts/sidecarInjectorWebhook/templates/deployment.yaml#L27). It's hard to decipher from the last snippet but it looks like the 'inject' annotation is aligned with last-applied-configuration which includes "kind: Deployment".

**Comment by incfly** [comment]
@ayj correct, changing to pod level annotation solves the problem. I mis-read the document. Closing, thanks!
