### ISSUE TITLE
Having some difficulty with webSockets

### ISSUE THREAD

**Issue by Stono** [istio/istio#11856]
Hi, 
I'm having some problems with an app that uses webSockets when we put istio-proxy on it.  I'm not convinced it's an istio problem per-se, but it'd be good if someone can help me debug these proxy logs to understand what's going on.

What we seem to be seeing is the app recursively trying to connect to itself, indefinitely.

I've attached the full log but the general highlights are:

1. Client connects to https://app.sourcing-web-gateway.preprod.k8.atcloud.io/ws/info?t=1550611225966 **OK 200**
2. Client connects to https://app.sourcing-web-gateway.preprod.k8.atcloud.io/ws/398/dd1b5h3v/websocket **OK 101**

Then as you can see from the logs it just seems to go round and round trying to connect to itself, it's odd.  We then see things like this.

```
[2019-02-19 21:20:26.960][27][debug][connection] external/envoy/source/common/ssl/ssl_socket.cc:113] [C30] handshake error: 2
[2019-02-19 21:20:26.960][27][debug][connection] external/envoy/source/common/ssl/ssl_socket.cc:113] [C30] handshake error: 2
[2019-02-19 21:20:26.962][27][debug][connection] external/envoy/source/common/ssl/ssl_socket.cc:113] [C29] handshake error: 2
[2019-02-19 21:20:26.962][27][debug][connection] external/envoy/source/common/ssl/ssl_socket.cc:113] [C29] handshake error: 2
```

I can only assume that's because it's trying to connect to itself (10.198.4.25:8080) and that connection isn't being handled by istio (because it's being intercepted by the iptables rules because it's coming from localhost).  Although i'm kind of guessing.

[log.tar.gz](https://github.com/istio/istio/files/2882045/log.tar.gz)

Any help would be appreciated.  

To help with debugging:
```
❯ k get pods,svc,ep -o wide
NAME                                        READY     STATUS    RESTARTS   AGE       IP            NODE
pod/sourcing-web-gateway-57f44d98c8-sr4gd   2/2       Running   0          7m        10.198.4.25   gke-delivery-platform-normal-20190114-44b42c3d-n8z3

NAME            TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE       SELECTOR
service/admin   ClusterIP   10.192.35.130   <none>        9080/TCP   1h        app=sourcing-web-gateway
service/app     ClusterIP   10.192.36.44    <none>        80/TCP     1h        app=sourcing-web-gateway

NAME              ENDPOINTS          AGE
endpoints/admin   10.198.4.25:9080   1h
endpoints/app     10.198.4.25:8080   1h
```

**Comment by Stono** [comment]
@rshriram as the envoy master guru god of all things envoy, any ideas?

**Comment by rshriram** [comment]
my hunch looking at the logs

```
[2019-02-19 21:20:26.855][27][debug][router] external/envoy/source/common/router/router.cc:252] [C16][S6821576537471900282] cluster 'outbound|80||app.sourcing-web-gateway.svc.cluster.local' match for URL '/ws/398/dd1b5h3v/websocket'
[2019-02-19 21:20:26.855][27][debug][router] external/envoy/source/common/router/router.cc:303] [C16][S6821576537471900282] router decoding headers:
':authority', 'app.sourcing-web-gateway.preprod.k8.atcloud.io'
':path', '/ws/398/dd1b5h3v/websocket'
':method', 'GET'
':scheme', 'https'
```

is that the app is doing a HTTP to HTTPS redirect wherein it seems to call itself https://app.sourcing-web.gateway... when the incoming call is http://app.sourcing-web....

If this call is coming from outside and transiting through a gateway, you could setup the gateway to do TLS redirect (i.e. redirect from 80 to 443). and then forward only the websocket upgrade on 443 to the backend..

**Comment by Stono** [comment]
So got to the bottom of it.  The app was proxying to another app but
setting an invalid host header (of the gateway rather than the upstream)
thus it was just recursively trying to connect to itself.

Will close the issue when I'm home later!
Ta
