### ISSUE TITLE
Ingress Gateway - Decrypt then send to a POD listening on https

### ISSUE THREAD

**Issue by nictrix** [istio/istio#11866]
**Describe the feature request**

Hi all, I was setting up an ingress gateway and VirtualService to send traffic to a pod and received this error: tls: first record does not look like a TLS handshake

After some troubleshooting and finding that log message I figured out the pod was listening on https; so I switched it to http and everything went fine.

But I wanted to know if there are any configurations options to allow Istio to terminate https then send traffic to a pod that is listening on https? I couldn’t find anything in the docs, tried a bunch of different methods also…

**Describe alternatives you've considered**

I don't believe there are alternatives for this feature..

**Additional context**

I posted it first here: https://discuss.istio.io/t/ingress-gateway-decrypt-then-send-to-a-pod-listening-on-https

**Comment by nictrix** [comment]
Bump, has anyone taken a look at this? I saw updates that allowed SNI routing with PASSTHROUGH, but nothing that would cover this situation.

**Comment by hzxuzhonghu** [comment]
@diemtvu @incfly @myidpt @quanjielin @JimmyCYJ Do we currently support this?

**Comment by yangminzhu** [comment]
Closing this issue as it's a question and not a bug according to the [Istio Bug Scrub](https://docs.google.com/document/d/19cQynIfmLwmcw9ujJkiOxY0D0pyuXNLOKpPTvmkWvIQ/edit#). The question is opened at  https://discuss.istio.io/t/ingress-gateway-decrypt-then-send-to-a-pod-listening-on-https
