### ISSUE TITLE
Should use `MeshConfig.ConfigSources` instead of `mcpServerAddrs`

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#11873]
pilot flag `--mcpServerAddrs` has been deprecated, and we added a new ConfigSources in MeshConfig https://github.com/istio/api/blob/master/mesh/v1alpha1/config.proto#L196

But https://github.com/istio/istio/pull/10222 enabled MCP by default and still using deprecated `mcpServerAddrs`.  So Ｉ　 think better  change to `ConfigSources ` .  And we plan to remove `--mcpServerAddrs` in 1.2.

/cc @ayj

**Comment by rshriram** [comment]
fixed by #11875
