### ISSUE TITLE
Applying istio.yaml file times out sometimes

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#1187]
Is it because the file is too big, or server too busy? Need to follow up with k8s team about what we can do to prevent this.
One way might be to split everything in smaller files under a directory called istio. kubectl apply -f istio will still work.

**Comment by andraxylia** [comment]
cc @ZackButcher

**Comment by andraxylia** [comment]
Related to #1113

**Comment by ldemailly** [comment]
How is a directory different from a file with sections (---), what makes you say it will work ?

**Comment by andraxylia** [comment]
I am not saying it will work, since I do not know yet how kubectl works. Merely brainstorming, edited the initial.

**Comment by linsun** [comment]
subscribe

**Comment by costinm** [comment]
Please reopen if it still happens, I haven't seen any case.
