### ISSUE TITLE
How to programmatically delete a Istio Object using client-go

### ISSUE THREAD

**Issue by rajdhandus** [istio/istio#11874]
**Describe the feature request**
I need a way to programmatically delete a istio crd object like virtual service using client-go

**Describe alternatives you've considered**
running kubectl commands from go program

**Additional context**
since the istio objects are CRDs there is not a lot of documentation around programmatically dealing with Istio objects.

**Comment by hzxuzhonghu** [comment]
You should use k8s  dynamic client, ref: pilot/pkg/config/kube/crd/client.go

**Comment by ozevren** [comment]
As @hzxuzhonghu mentioned, you can use the dynamic client to delete CRDs (not just Istio).
