### ISSUE TITLE
X-Istio-Attributes header is not added by istio sidecar proxy when controlled access to external HTTP service

### ISSUE THREAD

**Issue by vishal-yadav** [istio/istio#11881]
**Describe the bug**
As per step2 of [Controlled Access to external HTTP service](https://preliminary.istio.io/docs/tasks/traffic-management/egress/#access-an-external-http-service) the sidecar proxy should add header for _X-Istio-Attributes_ but the request does not include it though it includes _X-Envoy-Decorator-Operation_ header.
```
$ kubectl exec -it $SOURCE_POD -c sleep -- curl http://httpbin.org/headers
{
  "headers": {
    "Accept": "*/*",
    "Host": "httpbin.org",
    "User-Agent": "curl/7.60.0",
    "X-B3-Sampled": "0",
    "X-B3-Spanid": "0d55897df438df69",
    "X-B3-Traceid": "e62b8d888fe4ca710d55897df438df69",
    "X-Envoy-Decorator-Operation": "httpbin.org:80/*"
  }
}
```

**Expected behavior**
Either sidecar proxy should include _X-Istio-Attributes_ header or documentation should be fixed as per below comment [here](https://github.com/istio/istio/blob/master/mixer/test/client/env/attributes.go) line 62 
```
// HTTP header "x-istio-attributes" is used to forward attributes between
// proxy. It should be removed before calling mixer and backend.
```

**Steps to reproduce the bug**
Follow steps listed [here](https://preliminary.istio.io/docs/tasks/traffic-management/egress/#access-an-external-http-service)

**Version**
$ istioctl version
version.BuildInfo{Version:"1.1.0-snapshot.6", GitRevision:"14777199b85ba56ebca2a4516afff33c97199eb4", User:"root", Host:"f0f1db73-2fb5-11e9-86e9-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-snapshot.5-156-g1477719"}

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:57:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

**Installation**
Following [Minimal Install](https://preliminary.istio.io/docs/setup/kubernetes/minimal-install/) along with 
istio-egressgateway, istio-ingress, istio-ingressgateway and istio-policy components.

```
$ kubectl get pod,svc -n istio-system
NAME                                        READY   STATUS    RESTARTS   AGE
pod/istio-egressgateway-d9f69d6c8-94t7b     1/1     Running   0          2d1h
pod/istio-ingress-7795875fdd-l7ftc          1/1     Running   0          2d
pod/istio-ingressgateway-598c7757bc-cql2d   1/1     Running   0          2d1h
pod/istio-pilot-5b49dc5f77-7kmpq            1/1     Running   0          2d1h
pod/istio-policy-7d55f4994b-z7wh5           2/2     Running   0          2d1h

NAME                           TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                                                                                                      AGE
service/istio-egressgateway    NodePort    10.98.17.101     <none>        80:32740/TCP,443:30704/TCP,15443:31079/TCP                                                                                   2d1h
service/istio-ingress          NodePort    10.106.171.154   <none>        80:32000/TCP,443:32221/TCP                                                                                                   2d
service/istio-ingressgateway   NodePort    10.101.243.210   <none>        80:31380/TCP,443:31390/TCP,31400:31400/TCP,15029:30021/TCP,15030:31091/TCP,15031:31673/TCP,15032:30405/TCP,15443:31667/TCP   2d1h
service/istio-pilot            ClusterIP   10.109.52.67     <none>        15010/TCP,15011/TCP,8080/TCP,15014/TCP                                                                                       2d1h
service/istio-policy           ClusterIP   10.107.207.108   <none>        9091/TCP,15004/TCP,15014/TCP                                                                                                 2d1h
```

**Environment**
Local Kubernetes Cluster on Ubuntu (not minikube)

**Cluster state**
NA

**Comment by duderino** [comment]
@silentdai here is another one, but please note the P1.  Your P0s take precedence over this one.

**Comment by silentdai** [comment]
Combining the description of this header at envoy and the implementation of envoy. Envoy should determine the request as egress and the router config should have the `X-Envoy-Decorator-Operation` in `internalOnlyHeaders` collection. Will investigate.

**Comment by silentdai** [comment]
A deeper thought on this: Currently I don't think [Controlled Access to external HTTP service](https://preliminary.istio.io/docs/tasks/traffic-management/egress/#access-an-external-http-service) describes the correct behavior. _X-Istio-Attributes_ should be stripped in the request to httpbin.org

I am updating the document.

**Comment by duderino** [comment]
Thank you @silentdai
