### ISSUE TITLE
Test failure in presubmit:security.TestAuthnPermissive

### ISSUE THREAD

**Issue by irisdingbj** [istio/istio#11882]
https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/11850/istio-integ-local-tests/5621

**Comment by irisdingbj** [comment]
https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/11823/istio-integ-local-tests/5546

**Comment by utka** [comment]
@ozevren Is it something you fixed recently in https://github.com/istio/istio/pull/12574 ?

**Comment by ozevren** [comment]
It is hard to tell what is going on from the logs, but I'd say this is
fixed with my changes. TestAuthnPermissive has been working fine in
CI/local tests.

**Comment by ozevren** [comment]
https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/12676/istio-integ-local-tests/7036
Reopening. It looks like we still have a flake.

**Comment by ozevren** [comment]
@incfly I am assigning this to you. I believe you're the original author of the test?

**Comment by incfly** [comment]
Yes. I'll take a look on that.

**Comment by kyessenov** [comment]
Flakes https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/12689/istio-integ-local-tests/7142

**Comment by kyessenov** [comment]
Still flaky as of today https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/13624/istio-integ-local-tests/9384

**Comment by incfly** [comment]
The error seems to be deep in the native environment testing framework, not related to this test per se.

```
authn_permissive_test.go:113: apps.NewOrFail: failed to configure apps: service c missing config for outbound listener 127.0.0.1_36407. Dumping Envoy configurations:
```

I know @nmittler is working on some improvements. Not sure if that can help this particular case though.

**Comment by ozevren** [comment]
@nmittler any thoughts? This is the only flake plaguing the presubmit/local tests at this point.

**Comment by nmittler** [comment]
Let's get #13824 in ... I suspect this may resolve the issue.

**Comment by incfly** [comment]
From https://testgrid.k8s.io/istio-presubmits-master#integ-security-local-presubmit-tests this now seems to be pretty stable. took a glance, red ones are false alarm of the testing infra or other reasons. @nmittler pr makes a difference I think. 

closing for now. feel free to reopen.
