### ISSUE TITLE
preliminary 1.1 doc for "Istio Vault CA Integration" fails with missing mounted cert secret

### ISSUE THREAD

**Issue by bdecoste** [istio/istio#11899]
**Describe the bug**
{{
https://preliminary.istio.io/docs/tasks/security/vault-ca/

httpbin pod fails health check and fails with restarts due to missing mount of istio.default secret. From istio-proxy logs:

[2019-02-20 17:24:29.053][66][critical][main] [external/envoy/source/server/server.cc:86] error initializing configuration '/etc/istio/proxy/envoy-rev0.json': Invalid path: /etc/certs/cert-chain.pem

The following corrects the problem in httpbin-injected.yaml

       volumeMounts:
        - mountPath: /etc/istio/proxy
          name: istio-envoy
        - mountPath: /var/run/sds
          name: sds-uds-path
        **- mountPath: /etc/certs
          name: istio-default**

   volumes:
      - emptyDir:
          medium: Memory
        name: istio-envoy
      - hostPath:
          path: /var/run/sds
        name: sds-uds-path
      **- secret:
          secretName: istio.default
        name: istio-default**

}}

**Expected behavior**
{{
Health check succeeds, httpbin pod does not fail and restart
}}

**Steps to reproduce the bug**
{{
Follow "Before you begin" steps
}}

**Version**
{{
istio-1.1.0-snapshot.6
}}

**Installation**
{{
Follow "Before you begin"
}}

**Environment**
{{
minikube version: v0.34.1
}}

**Cluster state**
{{ N/A }}

**Comment by lei-tang** [comment]
The fix for this issue is at: https://github.com/istio/istio.io/pull/3316
