### ISSUE TITLE
Link for information on istioctl command

### ISSUE THREAD

**Issue by objectiser** [istio/istio#119]
This page https://github.com/istio/istio/blob/master/kubernetes/README.md#deploy-your-apps has a link to a missing doc for information on `istioctl`.

I've been trying to locate information on how to install this command?

> NOTE: Kubernetes admission controller for transparent proxy is not implemented yet

Does this statement mean that eventually use of the proxy will be transparent to the user deploying the app?

**Comment by objectiser** [comment]
Thanks for fixing the link so quickly in https://github.com/istio/istio/pull/120. I've also found the answer to my last question - it is short term workaround.

However I still can't find installation instructions for `istioctl` - any reference appreciated.

**Comment by kyessenov** [comment]
Yes, we are missing links to download the binary. The directory with images for all OSes can be found here: https://github.com/istio/istio/blob/master/istio.VERSION#L5

The link for linux is https://storage.googleapis.com/istio-artifacts/9a73dd7feb916a7af889b94558b579ccee261a26/artifacts/istioctl/istioctl-linux, mac https://storage.googleapis.com/istio-artifacts/9a73dd7feb916a7af889b94558b579ccee261a26/artifacts/istioctl/istioctl-osx

**Comment by objectiser** [comment]
Ok thanks - I'll close this issue as it was primarily about the bad link.
