### ISSUE TITLE
Citadel issue cert without SAN field for VM in mesh expansion

### ISSUE THREAD

**Issue by wattli** [istio/istio#11915]
When the node agent on the VM has been running for a while, it is starting to output errors to the log file. Turns out that the node_agent will occasionally write out a certificate with a missing SAN field! (This must be coming from the Citadel server.) And once that broken certificate is written out, node_agent is unable to get certificate updates

**Comment by justinburke** [comment]
Possibly same issue as #11078 .

**Comment by wattli** [comment]
Yes, it's a dup of #11078, closing this one.

**Comment by myidpt** [comment]
I will work on this issue. Closing this one and use #11078 to track.
