### ISSUE TITLE
preliminary 1.1 doc "Plugging in External CA Key and Certificate" has incorrect command for deleting secret

### ISSUE THREAD

**Issue by bdecoste** [istio/istio#11917]
Describe the bug
{{
https://preliminary.istio.io/docs/tasks/security/plugin-ca-cert/

The following command does not delete the secret since it lives in the istio-system namespace
kubectl delete secret istio.default
}}

Expected behavior
{{
secret is deleted
correct command is:
kubectl -n istio-system delete secret istio.default
}}

Steps to reproduce the bug
{{
Follow "Before you begin" steps
kubectl apply -f install/kubernetes/istio-demo-auth.yaml
}}

Version
{{
istio-1.1.0-snapshot.6
}}

Installation
{{
Follow doc steps
kubectl apply -f install/kubernetes/istio-demo-auth.yaml
}}

Environment
{{
OpenShift Container Platform 3.11
}}

Cluster state
{{ N/A }}

**Comment by myidpt** [comment]
In this task, I'm actually showing how to delete the secret in the *default* namespace. But I can improve the doc to make sure it doesn't confuse readers.
Only need to improve the docs, no need to fix code. Downgrade to P1.
