### ISSUE TITLE
preliminary 1.1 doc "Mutual TLS Deep-Dive" has incorrect command to cause CONFLICT

### ISSUE THREAD

**Issue by bdecoste** [istio/istio#11913]
**Describe the bug**
{{
https://preliminary.istio.io/docs/tasks/security/mutual-tls/

The doc has the following command to cause a destinationrule conflict. This documented command does not cause a conflict. 
}}

**Expected behavior**
{{
The documented command (see below) should cause a conflict:
kubectl -n istio-system apply -f - <<EOF
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "bad-rule"
spec:
  host: "httpbin.foo.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: DISABLE
EOF

}}

**Steps to reproduce the bug**
{{
Follow "Before you begin" steps
kubectl apply -f install/kubernetes/istio-demo-auth.yaml
}}

**Version**
{{
istio-1.1.0-snapshot.6
}}

**Installation**
{{
Follow doc steps
}}

**Environment**
{{
minikube version: v0.34.1
}}

**Cluster state**
{{ N/A }}

**Comment by wattli** [comment]
dup of #11908
