### ISSUE TITLE
preliminary 1.1 doc "Citadel Health Checking" fails when deploying citadel health checking

### ISSUE THREAD

**Issue by bdecoste** [istio/istio#11920]
**Describe the bug**
{{
https://preliminary.istio.io/docs/tasks/security/health-check/

$kubectl apply -f install/kubernetes/istio-citadel-with-health-check.yaml
serviceaccount/istio-citadel-service-account configured
service/istio-citadel configured
The Deployment "istio-citadel" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"istio":"citadel"}: `selector` does not match template `labels`

Looks like the Deployment in install/kubernetes/istio-citadel-with-health-check.yaml needs to be:

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: istio-citadel
  namespace: istio-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: security
        chart: security
        heritage: Tiller
        release: istio
        istio: citadel

}}

**Expected behavior**
{{
kubectl apply -f install/kubernetes/istio-citadel-with-health-check.yaml
succeeds

}}

**Steps to reproduce the bug**
{{
Follow steps
kubectl apply -f install/kubernetes/istio-demo-auth.yaml
}}

**Version**
{{
istio-1.1.0-snapshot.6
}}

**Installation**
{{
Follow doc steps
}}

**Environment**
{{
minikube version: v0.34.1
}}

**Cluster state**
{{ N/A }}

**Comment by myidpt** [comment]
I will try to fix if the health check. If the feature is broken and hard to fix, we may remove this feature for now.

**Comment by myidpt** [comment]
Now only the user guide needs to be improved.
