### ISSUE TITLE
(1.1 rc0) BookInfo traffic Request Routing does not work when using istio-demo-auth.yaml

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#11926]
**Describe the bug**
Bookinfo is failing to route appropriately when installed using the demo.yaml files.

This script was ran:
```bash
set -ex
export CLUSTER="howardjohn-istio-clean"
gcloud container clusters create $CLUSTER \
  --cluster-version=1.11.6-gke.2 \
  --machine-type "n1-standard-1" \
  --num-nodes 4 \
  --region us-central1 \
  --project howardjohn-istio

sleep 10

gcloud container clusters get-credentials $CLUSTER \
  --region us-central1 \
  --project howardjohn-istio

kubectl create clusterrolebinding cluster-admin-binding \
    --clusterrole=cluster-admin \
    --user=$(gcloud config get-value core/account)

cd ~/istio/latest

for i in install/kubernetes/helm/istio-init/files/crd*yaml; do kubectl apply -f $i; done

sleep 5

kubectl apply -f install/kubernetes/istio-demo-auth.yaml
kubectl label namespace default istio-injection=enabled
kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml
kubectl apply -f samples/bookinfo/networking/bookinfo-gateway.yaml

sleep 30
export INGRESS_HOST=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
export INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="http2")].port}')
export SECURE_INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="https")].port}')
export GATEWAY_URL=$INGRESS_HOST:$INGRESS_PORT
kubectl apply -f samples/bookinfo/networking/destination-rule-all-mtls.yaml

sleep 5

curl -s http://${GATEWAY_URL}/productpage | grep -o "<title>.*</title>"

kubectl apply -f samples/bookinfo/networking/virtual-service-all-v1.yaml
```

Then opened `http://${GATEWAY_URL}/productpage`. Page shows different versions of reviews every time.

**Expected behavior**
The page should show the v1 review page every time.

**Steps to reproduce the bug**
Run script above (replace with your project though). It also failed on a cluster I had previously installed Istio on, I repeated on a fresh cluster to ensure it wasn't some weird interaction

**Version**
1.1 snapshot 6, running on GKE 1.11

**Installation**
`kubectl apply -f install/kubernetes/istio-demo-auth.yaml` as per instructions on https://istio.io/docs/setup/kubernetes/quick-start/

**Environment**
GKE

**Comment by howardjohn** [comment]
Reproduced on 1.1 rc0

**Comment by howardjohn** [comment]
Ran again without auth and it worked as expected, so looks like this is isolated to `istio-demo-auth.yaml`

**Comment by howardjohn** [comment]
Also confirmed this happens when installed with helm and `--set global.mtls.enabled=true`

**Comment by yangminzhu** [comment]
Maybe related to #12000

**Comment by howardjohn** [comment]
Closing in favor of #12000, has much more info and is the same problem
