### ISSUE TITLE
Make 'sidecar'  works for ingress/egress gateway

### ISSUE THREAD

**Issue by morvencao** [istio/istio#11936]
**Describe the feature request**
In Istio 1.1, we have a new API called `sidecar` which provides a way to restrict the set of services that the proxy can reach when forwarding outbound traffic from the workload, thus much less envoy configuration for each sidecar if there are lots of services in the cluster.

However, sidecar will not restrict set of inbound/outbound services for the ingress/egress gateway. In some deployment, customers install dedicated ingress/egress gateway for their applications in app namespace, they want the `sidecar` also work for these ingress/egress gateway to provide resources isolation.

**Comment by dwradcliffe** [comment]
Yes, we need this also. Our ingress gateways can't keep up with the full mesh config being delivered. We're seeing constant cpu throttling.

**Comment by skydoctor** [comment]
Would be great to have this.

**Comment by RoeeShlomo** [comment]
The change in https://github.com/istio/istio/pull/15569#pullrequestreview-263329493 sets a */* sidecar scoping to gateways. However, now that all proxies have sidecar scopes it is possible to support make Sidecar resources apply to gateways as well. That is, make */* the default but allow the user to configure it differently if desired. Can this be supported? @howardjohn

**Comment by howardjohn** [comment]
Sidecar will be pretty poorly named if it applies to gateway as well  and has more aspects than just what resources to restrict to. I agree limiting the scope of gateways is useful but I think it is more likely we will do it based on the Gateway resource. There was a PR at one point to limit config based on which Gateways applied to a gateway but there were some problems with it

**Comment by rshriram** [comment]
closing and lets track this in #17753
