### ISSUE TITLE
preliminary 1.1 doc "Distributed Tracing Overview" has incorrect/old productpage.py 

### ISSUE THREAD

**Issue by bdecoste** [istio/istio#11943]
**Describe the bug**
{{
https://preliminary.istio.io/docs/tasks/telemetry/distributed-tracing/overview/

Doc references incorrect/old productpage.py source:

def getForwardHeaders(request):
    headers = {}

    if 'user' in session:
        headers['end-user'] = session['user']

    incoming_headers = [ 'x-request-id',
                         'x-b3-traceid',
                         'x-b3-spanid',
                         'x-b3-parentspanid',
                         'x-b3-sampled',
                         'x-b3-flags',
                         'x-ot-span-context'
    ]

    for ihdr in incoming_headers:
        val = request.headers.get(ihdr)
        if val is not None:
            headers[ihdr] = val
            #print "incoming: "+ihdr+":"+val

    return headers

release-1.1 source is:

def getForwardHeaders(request):
    headers = {}

    # x-b3-*** headers can be populated using the opentracing span
    span = get_current_span()
    carrier = {}
    tracer.inject(
        span_context=span.context,
        format=Format.HTTP_HEADERS,
        carrier=carrier)

    headers.update(carrier)

    # We handle other (non x-b3-***) headers manually
    if 'user' in session:
        headers['end-user'] = session['user']

    incoming_headers = ['x-request-id']

    # Add user-agent to headers manually
    if 'user-agent' in request.headers:
        headers['user-agent'] = request.headers.get('user-agent')

    for ihdr in incoming_headers:
        val = request.headers.get(ihdr)
        if val is not None:
            headers[ihdr] = val
            #print "incoming: "+ihdr+":"+val

    return headers
}}

**Expected behavior**
{{
Doc matches productpage.py source
}}

**Steps to reproduce the bug**
{{
Compare productpage.py source to doc
}}

**Version**
{{
N/A
}

**Installation**
{{
N/A
 }}

**Environment**
{{
N/A
}}

**Cluster state**
{{
N/A
}}

**Comment by howardjohn** [comment]
Fixed https://preliminary.istio.io/docs/tasks/telemetry/distributed-tracing/overview/
