### ISSUE TITLE
Upgrade fails from 1.0.6 to 1.1RC0 - pilot validation of exportTo

### ISSUE THREAD

**Issue by louiscryan** [istio/istio#11957]
**Describe the bug**
Failure in upgrade from 1.0.6 to 1.1 RC0

**Expected behavior**
Component upgrade works

**Steps to reproduce the bug**
Follow 1.0.6 installation steps
Install 1.0.6 BookInfo sample
Follow upgrade instruction (non-Tiller) for auth-enabled

**Version**
1.1RC0

**Installation**
See above

**Environment**
Kubernetes-In-Docker

**Cluster state**

See the following error message running
 kubectl apply -f $HOME/istio-auth.yaml

Error from server: error when creating "/Users/lryan/istio-auth.yaml": admission webhook "pilot.validation.istio.io" denied the request: error decoding configuration: YAML decoding error: exportTo:
- '*'
host: '*.local'
trafficPolicy:
  tls:
    mode: ISTIO_MUTUAL
 unknown field "exportTo" in v1alpha3.DestinationRule
Error from server: error when creating "/Users/lryan/istio-auth.yaml": admission webhook "pilot.validation.istio.io" denied the request: error decoding configuration: YAML decoding error: exportTo:
- '*'
host: kubernetes.default.svc.cluster.local
trafficPolicy:
  tls:
    mode: DISABLE
 unknown field "exportTo" in v1alpha3.DestinationRule
Error from server: error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"networking.istio.io/v1alpha3\",\"kind\":\"DestinationRule\",\"metadata\":{\"annotations\":{},\"labels\":{\"app\":\"mixer\",\"chart\":\"mixer\",\"heritage\":\"Tiller\",\"release\":\"istio\"},\"name\":\"istio-policy\",\"namespace\":\"istio-system\"},\"spec\":{\"exportTo\":[\"*\"],\"host\":\"istio-policy.istio-system.svc.cluster.local\",\"trafficPolicy\":{\"connectionPool\":{\"http\":{\"http2MaxRequests\":10000,\"maxRequestsPerConnection\":10000}},\"portLevelSettings\":[{\"port\":{\"number\":15004},\"tls\":{\"mode\":\"ISTIO_MUTUAL\"}}]}}}\n"},"labels":{"app":"mixer","chart":"mixer","heritage":"Tiller","release":"istio"}},"spec":{"exportTo":["*"],"trafficPolicy":{"portLevelSettings":[{"port":{"number":15004},"tls":{"mode":"ISTIO_MUTUAL"}}]}}}
to:
Resource: "networking.istio.io/v1alpha3, Resource=destinationrules", GroupVersionKind: "networking.istio.io/v1alpha3, Kind=DestinationRule"
Name: "istio-policy", Namespace: "istio-system"
Object: &{map["apiVersion":"networking.istio.io/v1alpha3" "kind":"DestinationRule" "metadata":map["resourceVersion":"1214" "selfLink":"/apis/networking.istio.io/v1alpha3/namespaces/istio-system/destinationrules/istio-policy" "uid":"6179c043-3610-11e9-a7a4-0242b4fe287f" "annotations":map["kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"networking.istio.io/v1alpha3\",\"kind\":\"DestinationRule\",\"metadata\":{\"annotations\":{},\"name\":\"istio-policy\",\"namespace\":\"istio-system\"},\"spec\":{\"host\":\"istio-policy.istio-system.svc.cluster.local\",\"trafficPolicy\":{\"connectionPool\":{\"http\":{\"http2MaxRequests\":10000,\"maxRequestsPerConnection\":10000}}}}}\n"] "creationTimestamp":"2019-02-21T19:39:19Z" "generation":'\x01' "name":"istio-policy" "namespace":"istio-system"] "spec":map["host":"istio-policy.istio-system.svc.cluster.local" "trafficPolicy":map["connectionPool":map["http":map["http2MaxRequests":'\u2710' "maxRequestsPerConnection":'\u2710']]]]]}
for: "/Users/lryan/istio-auth.yaml": admission webhook "pilot.validation.istio.io" denied the request: error decoding configuration: YAML decoding error: exportTo:
- '*'
host: istio-policy.istio-system.svc.cluster.local
trafficPolicy:
  connectionPool:
    http:
      http2MaxRequests: 10000
      maxRequestsPerConnection: 10000
  portLevelSettings:
  - port:
      number: 15004
    tls:
      mode: ISTIO_MUTUAL
 unknown field "exportTo" in v1alpha3.DestinationRule
Error from server: error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"networking.istio.io/v1alpha3\",\"kind\":\"DestinationRule\",\"metadata\":{\"annotations\":{},\"labels\":{\"app\":\"mixer\",\"chart\":\"mixer\",\"heritage\":\"Tiller\",\"release\":\"istio\"},\"name\":\"istio-telemetry\",\"namespace\":\"istio-system\"},\"spec\":{\"exportTo\":[\"*\"],\"host\":\"istio-telemetry.istio-system.svc.cluster.local\",\"trafficPolicy\":{\"connectionPool\":{\"http\":{\"http2MaxRequests\":10000,\"maxRequestsPerConnection\":10000}},\"portLevelSettings\":[{\"port\":{\"number\":15004},\"tls\":{\"mode\":\"ISTIO_MUTUAL\"}}]}}}\n"},"labels":{"app":"mixer","chart":"mixer","heritage":"Tiller","release":"istio"}},"spec":{"exportTo":["*"],"trafficPolicy":{"portLevelSettings":[{"port":{"number":15004},"tls":{"mode":"ISTIO_MUTUAL"}}]}}}
to:
Resource: "networking.istio.io/v1alpha3, Resource=destinationrules", GroupVersionKind: "networking.istio.io/v1alpha3, Kind=DestinationRule"
Name: "istio-telemetry", Namespace: "istio-system"
Object: &{map["kind":"DestinationRule" "metadata":map["uid":"61856100-3610-11e9-a7a4-0242b4fe287f" "annotations":map["kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"networking.istio.io/v1alpha3\",\"kind\":\"DestinationRule\",\"metadata\":{\"annotations\":{},\"name\":\"istio-telemetry\",\"namespace\":\"istio-system\"},\"spec\":{\"host\":\"istio-telemetry.istio-system.svc.cluster.local\",\"trafficPolicy\":{\"connectionPool\":{\"http\":{\"http2MaxRequests\":10000,\"maxRequestsPerConnection\":10000}}}}}\n"] "creationTimestamp":"2019-02-21T19:39:19Z" "generation":'\x01' "name":"istio-telemetry" "namespace":"istio-system" "resourceVersion":"1215" "selfLink":"/apis/networking.istio.io/v1alpha3/namespaces/istio-system/destinationrules/istio-telemetry"] "spec":map["host":"istio-telemetry.istio-system.svc.cluster.local" "trafficPolicy":map["connectionPool":map["http":map["http2MaxRequests":'\u2710' "maxRequestsPerConnection":'\u2710']]]] "apiVersion":"networking.istio.io/v1alpha3"]}
for: "/Users/lryan/istio-auth.yaml": admission webhook "pilot.validation.istio.io" denied the request: error decoding configuration: YAML decoding error: exportTo:
- '*'
host: istio-telemetry.istio-system.svc.cluster.local
trafficPolicy:
  connectionPool:
    http:
      http2MaxRequests: 10000
      maxRequestsPerConnection: 10000
  portLevelSettings:
  - port:
      number: 15004
    tls:
      mode: ISTIO_MUTUAL
 unknown field "exportTo" in v1alpha3.DestinationRule
lryan-macbookpro:istio-1.1.0-rc.0 lryan$

**Comment by ayj** [comment]
dup of https://github.com/istio/istio/issues/11555?

**Comment by ostromart** [comment]
Yes it's the same issue, this is a transient condition, the solution is now to wait a bit longer for the old galley to go away :-P

**Comment by ayj** [comment]
If at first you don't succeed ...

```bash
until kubectl apply -f $HOME/istio-auth.yaml
do
    echo "try again"
    sleep 1
done
```

**Comment by ostromart** [comment]
eventual consistency!

**Comment by kyessenov** [comment]
Just like our CI ;) If you keep trying, it will eventually work.
