### ISSUE TITLE
istio-policy tracespans show up without root spans

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio#11954]
**Describe the bug**
Running through the Rate Limit task on istio.io, I went to check the tracespan data in Jaeger. I discovered that the `istio-mixer` spans show up as disconnected from their parent spans, and the traces are labeled as `trace-without-root-span`.

![jaeger-mixer-check](https://user-images.githubusercontent.com/21148125/53194424-2743d900-35c8-11e9-938b-af7d3a8bbee6.png)

Meanwhile, the parent traces show the UAEX codes that we would expect, but don't have the Mixer traces.

![expected-jaeger-trace-parent](https://user-images.githubusercontent.com/21148125/53194643-b5b85a80-35c8-11e9-913b-066d00979415.png)

**Expected behavior**
Mixer traces to be part of the distributed traces for the parent requests.

**Steps to reproduce the bug**
Rate limit task w/ tracing enabled + fortio to generate traffic.

**Version**
1.1-rc0

**Installation**
helm init

**Environment**
gke

**Cluster state**

**Comment by robertpanzer** [comment]
Just experienced the same running on local Docker for Mac with 1.1.0-rc.0.

**Comment by objectiser** [comment]
Will try to take a look when back 1st week of March.

**Comment by douglas-reid** [comment]
@robertpanzer i need to verify if the dependency patch we pushed recently made into rc0. it may be the solution.

**Comment by douglas-reid** [comment]
Digging a bit, it appears Mixer is sending data with 64bit traceids vs. the 128bits being used elsewhere.

**Comment by douglas-reid** [comment]
Example trace of a request:
- traceid for full request: `c494993019fe102aa8135e5b0c0fdf4c`
- traceid of suspect Mixer `Check` calls: `a8135e5b0c0fdf4c` (the lower 64bits from the request)
- headers recorded by `istio-policy`: `x-b3-spanid:cfeceaae372fb255 x-b3-sampled:1 x-b3-parentspanid:644b7ad4ef9f57d1 x-b3-traceid:c494993019fe102aa8135e5b0c0fdf4c`

**Comment by douglas-reid** [comment]
The jaeger zipkin http transport still hardcodes traceid() low values:

`TraceID:           int64(span.context.traceID.Low), // TODO upgrade zipkin thrift and use TraceIdHigh`

**Comment by douglas-reid** [comment]
so, that will need to be addressed in the client library.

**Comment by douglas-reid** [comment]
I have a fix for the underlying client library that results in the following:

![joint-trace](https://user-images.githubusercontent.com/21148125/53278679-846e8600-36bf-11e9-9cf3-92a1e93d6d64.png)

**Comment by duderino** [comment]
@douglas-reid close this?

**Comment by douglas-reid** [comment]
@duderino as soon as I verify with the next RC, if that's ok.

**Comment by duderino** [comment]
@utka second reason for rc2

**Comment by douglas-reid** [comment]
This appears fixed rc2.
