### ISSUE TITLE
Cannot run bookinfo on a full installation of istio

### ISSUE THREAD

**Issue by dmitri-d** [istio/istio#11964]
**Describe the bug**
When running full istio install (per https://preliminary.istio.io/docs/setup/kubernetes/helm-install/#option-1-install-with-helm-via-helm-template) on minikube with suggested config settings (--memory=8192 --cpus=4 --kubernetes-version=v1.13.0), bookinfo fails to deploy with "0/1 nodes are available: 1 Insufficient cpu." error. 

**Expected behavior**

**Steps to reproduce the bug**
- Install minikube 0.34, virtualbox or kvm2 driver. Start minikube with "--memory=8192 --cpus=4 --kubernetes-version=v1.13.0"
- Install full istio (not a demo install)
- install bookinfo

**Version**
istio-1.1.0-rc.0,
kubernetes 1.13

**Installation**
Per https://preliminary.istio.io/docs/setup/kubernetes/helm-install/#option-1-install-with-helm-via-helm-template

**Environment**
Fedora 29, minikube 0.34 and 0.33

**Comment by dmitri-d** [comment]
This is due to cpu limits on sidecar containers. Increasing the number of cpus available to minikube to 6 resolves the issue.

**Comment by howardjohn** [comment]
We recently bumped up the CPU requests, so we probably just need to update the docs to indicate more cpus. Maybe also add a note that you can use the demo file to use much less resources, as needing such a big cluster could be off putting if they don't know about the demo files

**Comment by dmitri-d** [comment]
Yet another thing we could do would be to add another istio config -- full install, but with reduced cpu limits. As you pointed out 6 cpu limit is starting to push the requirements too high, but there's a value in being able to demo the "full" install (if someone wants to try tracing, telemetry, etc).

**Comment by sdake** [comment]
@dmitri-d we discussed this topic in the env WG on wednesday.  I believe the proposals were to use the profiles for this work.

Cheers
-steve

**Comment by howardjohn** [comment]
Related: 
* https://github.com/istio/istio/issues/12051
* https://github.com/istio/istio/issues/12043

I don't think its reasonable to just change the minimum limits to 6+ CPUs. I think we need the default case to require a small cluster -- anyone that requires good performance won't mind making minimal config changes, but someone trying Istio for the first time might. @mandarjog what do you think?

**Comment by duderino** [comment]
@howardjohn @costinm @mandarjog @sdake @linsun 

I think this is the demo config vs. production config issue.  Unless that's captured elsewhere, I think this bug can be satisfied by splitting the two configs and picking a low overhead demo config

This is currently assigned to @howardjohn  but it'd be really good if one of you could work with him over slack, etc to give him a second pair of eyes and the benefit of your years of Istio experience

**Comment by dmitri-d** [comment]
> I think this is the demo config vs. production config issue. Unless that's captured elsewhere, I think this bug can be satisfied by splitting the two configs and picking a low overhead demo config

+1

**Comment by linsun** [comment]
Sorry we probably forget to update the minikube instruction... only demo profile can work with minikube or the istio-demo.yaml files or the minimal istio install.

**Comment by duderino** [comment]
See also https://github.com/istio/istio/pull/11476  This effectively turned the default config into the production config and broke the demo use case in the process.

**Comment by andraxylia** [comment]
I will try to get it to work with this flag -f install/kubernetes/helm/istio/values-istio-demo.yaml and update the docs accordingly.

**Comment by duderino** [comment]
@mandarjog says he is actively working on this

**Comment by andraxylia** [comment]
I confirm it works with the --values install/kubernetes/helm/istio/values-istio-demo.yaml and updates the helm installation doc.

**Comment by trevorlinton** [comment]
@howardjohn @duderino Just to be clear. The new production configuration requires every pod to take up an additional 2 CPU cores, and from what I'm testing it requires at a minimum a 3 servers each with at least 8 cores available each dedicated to run istio?  We have a production cluster with 700 pods running, it would require us to double our bill from 100k to 200k in order **JUST** to run istio. Does at least the sidecar's limits/requests seem unreasonable?

**Comment by howardjohn** [comment]
I just ran `minikube --cpus 2`, then ran 10 replicas of a pod with:

```yaml
        resources:
          requests:
            cpu: "10m"
          limits:
            cpu: "1000m"
```

All pods created successfully, even though though the total limits was 10 CPUs and I had 2 CPUs available. The 2 CPU cores/sidecar is the limit, not the requests, which does not [not affect the scheduler](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#how-pods-with-resource-requests-are-scheduled).

If the limit (or `100m` request) is too much for your case, it should be pretty simple to change.

**Comment by trevorlinton** [comment]
Yeah, @howardjohn  I'm going to go ahead and apologize profusely, this was my misunderstanding as when I went back and looked closer the node went un-scheduable for a completely unrelated reason.  Sorry. Sorry. Sorry.  Ignore this issue.

**Comment by wenchenglu** [comment]
@mandarjog
any update on this issue?

**Comment by mandarjog** [comment]
https://github.com/istio/istio/blob/release-1.1/install/kubernetes/helm/istio/values-istio-demo-common.yaml  is the demo profile. It has reduced cpu and memory requirements. That should satisfy this.

**Comment by duderino** [comment]
@dmitri-d we think this is fixed.  do you have the bandwidth to try again with 1.1rc2 or should we find another vict^H^H^Holunteer?

**Comment by dmitri-d** [comment]
@duderino: Yep, will give it a try.

**Comment by dmitri-d** [comment]
@duderino: bookinfo deployed ok on a full install of istio 1.1.0-rc2

**Comment by mandarjog** [comment]
Thanks @dmitri-d , closing.
