### ISSUE TITLE
Cluster-wide e2e test failed in master

### ISSUE THREAD

**Issue by yutongz** [istio/istio#1196]
Example here:
https://github.com/istio/istio/pull/1195
https://github.com/istio/istio/pull/1191

Robot merged them since this is not a required check and should we make it required for merged?

**Comment by costinm** [comment]
I think the agreement is for pre-submit (and anything that is blocking the merging) to be:
- fast ( few minutes )
- stable / non flaky.

We can't block everything until someone fixes a flaky test  - we can still run it and have bugs 
assigned to fix whatever is broken (including the tests that are flaky).
