### ISSUE TITLE
Jaeger deployment needs annotation for prometheus path

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio#11962]
**Describe the bug**
Prom collection of jaeger metrics fails, as no path is specified in annotations. The default path is `/metrics`, but because we specify `QUERY_BASE_PATH=/jaeger`, this fails.  It should be `"prometheus.io/path": "/jaeger/metrics"`.

**Expected behavior**
metrics collected for jaeger process.

**Steps to reproduce the bug**
deploy istio 1.1-rc0

**Version**
istio 1.1-rc0

**Installation**
helm init

**Environment**
gke

**Cluster state**

**Comment by duderino** [comment]
Please close this out unless there's more work to be done here
