### ISSUE TITLE
JWT test failures in Istio

### ISSUE THREAD

**Issue by chakravarthy392** [istio/istio#11975]
I have built Proxy and Istio from source on a big endian system.
While running tests, I am facing below failures:
**Proxy:**

> //src/envoy/http/authn:authenticator_base_test  
> //src/envoy/http/authn:authn_utils_test 
> //src/envoy/http/authn:http_filter_integration_test

**Istio:**

> mixer/test/client/istio_authn_origin_jwt_bound_origin
> mixer/test/client/istio_authn_origin_jwt_bound_peer
> mixer/test/client/istio_authn_peer_jwt_bound_peer

Already an issue has been raised regarding Proxy TC failures https://github.com/istio/proxy/issues/1841 , got a reply that the failures are not critical https://github.com/istio/proxy/issues/1841#issuecomment-403924482. These proxy TCs can be ignored as long as we do not use JWT for istio end-user authentication, Just want to make sure that same applicable for JWT TC failures on Istio.

Can some one please comment about the significance of these TCS, any critical functionality would be affected if these are neglected?
Is mTLS reliable for authentication if we do not use JWT? 

**Version**
proxy version: 1.0.5
istioctl version: 1.0.5
kubectl version: 1.11.5

**Comment by yangminzhu** [comment]
mTLS should be reliable enough, (JWT provides more flexibility though)

Do you know why these test fail? Is it related to the big endian system?

/cc @diemtvu

**Comment by chakravarthy392** [comment]
@yangminzhu Thanks for the info.

we could fix `//src/istio/mixerclient/referenced.cc` TC by making endianness related changes, 
debugging is in progress for remaining TC faiures.

**Comment by yangminzhu** [comment]
Closing as I think @chakravarthy392 has found the way to fix it. Feel free to reopen if necessary.
