### ISSUE TITLE
Mixer runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by gbaufake** [istio/istio#11972]
**Describe the bug**

- Mixer blocks connections on service mesh. On Mixer log (attached) there is a recurrent message: error	panic during handler dispatch: runtime error: invalid memory address or nil pointer dereference
goroutine 378 [running]:

**Expected behavior**
 - Mixer should not reference a nil address memory

**Steps to reproduce the bug**

- Deploy Istio

- Deploy any operator which has a complex workflow with istio-sidecar (eg: https://github.com/gbaufake/kiali-test-mesh/tree/ansible-to-operator/operator/kiali-test-mesh-operator - make operator-k8s-deployment would do the work)

- The mixer will block connections on the mesh and answers with 500

**Logs**

- [mixer.log](https://github.com/istio/istio/files/2893228/mixer.log)

- [kiali-traffic-generator.log](https://github.com/istio/istio/files/2893235/kiali-traffic-generator.log)

**Version**

- Istio.1.1.0-Snapshot.6

**Installation**

- On-Premise and on AWS

**Environment**

- Openshift (Kubernetes 1.12.4) 
- Openshift (Kubernetes 1.11.0)

**Comment by bianpengyuan** [comment]
Looks like ref.Controller could be nil here https://github.com/istio/istio/blob/master/mixer/adapter/kubernetesenv/cache.go#L147

**Comment by gbaufake** [comment]
@douglas-reid @bianpengyuan   I thought it was related to traffic generator, but I retested my operator by removing the traffic generator and it presented the same issue, now I noticed the problem is when I deploy the operator with sidecar.

Maybe the number of the operations on operator is overflowing the mixer somehow.

**Comment by bianpengyuan** [comment]
I think your operator does not run with any types of controller? Could you run `kubectl get pods your-operator-pod -o jsonpath={.metadata.ownerReferences}` to check that?

**Comment by bianpengyuan** [comment]
@gbaufake Any updates?

**Comment by gbaufake** [comment]
[map[controller:true blockOwnerDeletion:true apiVersion:apps/v1 kind:ReplicaSet name:kiali-test-mesh-operator-5ddf9d5c5d uid:496c6946-3f4e-11e9-807f-069b57c43aec]]%

**Comment by bianpengyuan** [comment]
@gbaufake The metadata looks good and should not cause any panic. 

By not working do you mean your operator would not work with sidecar injected, or do you mean traffic generator always returns 500 when it has sidecar injected? Could you provide more details about your set up?

**Comment by gbaufake** [comment]
@bianpengyuan  by not working. I mean all the connections that go to istio-policy pod returns 503. I will retest this on Istio 1.1.0-rc2 because I was told it could be a race issue on the mixer.

**Comment by gbaufake** [comment]
I tested again rc.4 and it didn't to appear to be an issue anymore

**Comment by bianpengyuan** [comment]
Ok, thanks. I will close this issue then.
