### ISSUE TITLE
1.1 Soft multi-tenancy support

### ISSUE THREAD

**Issue by monkeymorgan** [istio/istio#11977]
**Describe the feature request**

As noted in https://github.com/istio/istio/issues/7608 the blog post on https://istio.io/blog/2018/soft-multitenancy/ is a little out of date however with some effort you can configure istio to constrain many components to act within a single namespace and thus support a limited from of multi tenancy. 

My suggestion is that istio supports these three deployment models out of the box using global options that are used in all charts : 

1. A cluster wide mesh - the current default (istio assuming ClusterRoles and omnipotence)
2. Single tenant per control plane (currently possible with work on user's side modifying the charts) 
3. A control plane with a namespace opt-in mechanism which uses minimal ClusterRoles and is suitable to roll out onto production K8s clusters using soft multi-tenancy. 

Option 3 of course would solve for the second use case, however there is already an option named 'global.oneNamespace' used by pilot which could solve for 2.

To solve for option 2 alone - the 'global.oneNamespace' option could be used to 
a) create Roles instead of ClusterRoles for all Components
b) add restrictions to deployments such as [Citadel listened-namespace](https://github.com/istio/istio/blob/master/security/cmd/istio_ca/main.go#L143)   
c) possibly set the Kiali blacklist (api.namespaces.exclude) 
d) update prometheus config to only inspect a single NS for 'kubernetes-service-endpoints' 'kubernetes-pods*' and 'envoy-stats' 

While that would be useful, it would be even more ideal to support a one to many relationship from control plane to tenants. This could either be achieved by 
a) introducing a whitelist of namespaces such as globals.tenants 
b) discovering the whitelisted namespaces by using a namespace selector 

There are some advantages to 'a' since it can be determined pre-deploy (i.e. while rendering the charts) which allows for the option of only generating the minimum number of ClusterRoles by generating a Role per NS in the list per component.  Other charts such as prometheus and kiali can restrict their domain using the same list. I've use this approach in prometheus config which works well. 

For example updating the prometheus configmap to only consider the tenants namespaces : 

```
      kubernetes_sd_configs:
      - role: pod
{{- if .Values.global.tenants }}
        namespaces:
          names:
    {{- range .Values.global.tenants }}
          - {{ . | quote }}
    {{- end }}
{{- end }}
```
This makes the memory requirements of prometheus more predictable / less likely to be effected by the scale of the cluster. 

A good starting point would be to re-organise the RBAC configs to ensure a separation of concerns - separate access to tenant resources from truly cluster wide resources (e.g. nodes) and those in the istio-system (or istio ctrl-plane) NS.  I understand there maybe code changes required to support this and that there's probably an optimal way to implement this in code, probably using namespace selectors instead of explicit lists. 

In my experiment I added an additional label to each tenant NS - the `istio-control-plane` label : 

```
istio-control-plane: istio-system
istio-injection: enabled  
```  

Having both the label selector and explicit list duplication may seem likely to introduce a potential for human error, however in our case at least, we've an opt-in target in Make which handles the labelling / manifest generation to our satisfaction.  We are however restricted to the single NS scenario without code changes to support the one to many scenario which is our ideal deployment. 
 
**Describe alternatives you've considered**

Alternative solution is to deploy cluster wide istio's and use the side car injector config alone to ensure tenants use the correct NS.

We're not in a position to install a cluster wide istio on large production clusters due to the inability to guarantee zero risk to the existing tenants.  

**Additional context**

This would help istio adoption by making it less of an all-or-nothing option for those with mixed workloads and tenants on their clusters.

**Comment by sdake** [comment]
There is a new feature in 1.1 called the sidecar custom resource.  In addition to Istio's netowrking rbac, I think its possible to implement soft multitenancy, but this requires R&D.

The blog post doesn't actually isolate network traffic, which would be required to meet my definition of soft mulitenancy.

Cheers
-steve

**Comment by monkeymorgan** [comment]
I can't find any information on sidecar custom resource @sdake although I suspect it's not exactly what I'm looking for. My main goal is to support a one control plane to many tenant namespaces with as few clusterroles as possible and as little risk of impact to non mesh tenants on the same cluster.

For network traffic isolation I used a simple network policy on the control plane : 

```
{{ $Release := .Release }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: allow-tenants-in
spec:
  podSelector: {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          istio-injection: enabled
  policyTypes:
  - Ingress
```

To allow for multi control planes the matchLabels could be expanded however.

**Comment by ozevren** [comment]
Putting this into 1.1 milestone for triaging purposes.

**Comment by Stono** [comment]
Crosslinking my comment on https://github.com/istio/istio/issues/11664#issuecomment-467153211

**Comment by monkeymorgan** [comment]
Update: I found the [sidecar custom resource](https://preliminary.istio.io/docs/reference/config/networking/v1alpha3/sidecar/) doc that @sdake alluded to. `Sidecar` allows istio tenants to limit the inbound/outbound traffic through their proxies on a per-namespace or per-workload basis. This seems complimentary to what I'm looking for, but it doesn't solve our use-case. 

To be clear, my primary focus is to respect the namespaces of users in our cluster that do not wish to be part of any istio mesh. 
e.g. if the following is the list of namespaces  on the cluster: 

```
ns1
ns2
ns3 
istio-system
kube-system
```

and only ns2 and ns3 wish to opt in to the mesh, I want to setup istio in such a way that it doesn't either read from or write to namespaces outside it's jurisdiction. This means, for example, restricting citadel from creating secrets in ns1 and kube-system, and restricting pilot from querying the API server for EDS in non mesh namespaces. 

Restricting the reach of pilot EDS may well help with the original issue referenced by @Stono which was firstly proposed as [Reduce load on Pilot by ignoring services](https://github.com/istio/istio/issues/11664) Note: I can't use an opt-out mechanism in our case - to avoid interference with ns1 and kube-system the mechanism needs to be opt-in. 

In the pilot case, an option for us would be to update the [pilot api watchers](https://github.com/istio/istio/blob/master/pilot/pkg/config/kube/crd/controller.go#L73) to either restrict by a list of namespaces or via label-selectors.  As expressed previously, reducing the ClusterRoles to Roles is also desirable so perhaps a list of namespaces is the most suitable solution. 

At a chart level, this could be introduced as a new cmd line list in pilot which limits EDS in pilot to those namespaces. It would avoid changing existing options to be backwards compatible. This would allow for multiple configurations where for example pilot can discover ns2 and ns3. It doesn't nec. mean that both ns are in the mesh. ns3 for example may just need to be reachable from the mesh but may not have sidecars. Inclusion in the mesh would still use the namespace labels: 

```
istio-control-plane: istio-system
istio-injection: enabled
```

At this point, I wanted to gauge the interest in our use case and understand the other efforts in this area, and see if adding options to control plane components is an anti-pattern or likely to be accepted. From what I see so far, other efforts are not focussing on this exact goal but there's a lot in flux, so perhaps I've missed something.

**Comment by monkeymorgan** [comment]
I see there is work underway to add [--appNamespaces param to pilot](https://github.com/istio/istio/pull/11932) and [--listened-namespaces to citadel](https://github.com/istio/istio/pull/11667/files) which would mean all that is then required to complete this issue would be to update the RBAC generation in the charts to use Roles for tenant resources and a RoleBinding pre tenant based on the new comma separated list options.

**Comment by elevran** [comment]
Left a comment on #11146 - not sure command line is a good option when we want to allow gradual adoption. Adding new namespace would require restart of Pilot, Citadel, etc.
With respect to multi-tenancy, I suspect Istio admins (access to `istio-system`) are different than namespace admins and ns admin would not have access to restart Istio control plane components.
A possible flow would be to allow namespaces to opt-in into the mesh by using a namespace label.

**Comment by elevran** [comment]
I'd like to propose we support this using the following logic, across all control plane components.
Mesh global can be overridden by namespace which can be overridden per object (e.g., Pod for injector and/or Pilot, service account for Citadel).
This means that control plane need to access the global config map and  watch/query namespaces as well. This can be encapsulated at the `pkg/kube` level for all components (e.g., `IsIstioEnabledFor(object)`).

A label makes more sense, IMHO, since it allows filtering/selection and the k8s level.

**Comment by monkeymorgan** [comment]
I left a comment on the [citadel ns list issue](https://github.com/istio/istio/issues/11415#issuecomment-469237803) which in retrospect I should have posted to this thread.  The summary was: for gradual adoption we're ok with NS labels but it would be useful if
1. the control plane was also specified so that multiple could exist per cluster e.g. : 
```
istio-control-plane: istio-system
istio-injection: enabled
```
2. The RBAC was still required per NS to opt-in (i.e. we could use Roles per NS instead of ClusterRoles as an option)
3. Ideally we could set the 'reachability' of istio beyond the mesh itself (a nice to have - I wonder if it's useful to include dependent NS's within EDS even if they are outside of the mesh for direct routing) - This may require a different NS label for pilot than the other components. I'm less sure about this point, just thinking through the limits of a single NS label.

**Comment by elevran** [comment]
a single label would indeed be insufficient to address your requirements, specifically for associating namespaces with control plane instances.
I'm not quite sure how RBAC would work unless Istio runs an additional controller to generate RBAC rules and roles on the fly.

**Comment by daparthi001** [comment]
Is there any work around for multi tenancy to be working , i tried the discover with "--appNamespace", "ns-1",its not detecting , the reason we are looking at multi tenancy is to support the clusters blue/green deployments during the istio upgrades .

**Comment by daparthi001** [comment]
> I see there is work underway to add [--appNamespaces param to pilot](https://github.com/istio/istio/pull/11932) and [--listened-namespaces to citadel](https://github.com/istio/istio/pull/11667/files) which would mean all that is then required to complete this issue would be to update the RBAC generation in the charts to use Roles for tenant resources and a RoleBinding pre tenant based on the new comma separated list options.

**Comment by monkeymorgan** [comment]
@daparthi001 I verified the pilot parameter "--appNamespace" works (even with limited pilot RBAC) by using a single NS for istio and the app. 

ie. --appNamespace istio-system would work if you install your apps into istio-system

**Comment by monkeymorgan** [comment]
True @elevran We're certainly fine with generating RBAC per tenant at the point of onboarding, and I expect that adding a controller may not be beneficial for others. If a company are happy to give an rbac controller clusterroles then they may as well give pilot clusterroles instead.  I imagine that if the istio docs / code can give us assurances that components do not over-reach beyond namespaces under their jurisdiction (e.g. using selectors) then the policy of insisting on no clusterroles could be bypassed. We'd be able to proceed just with the code changes I expect, as long as we understood the boundaries.

**Comment by daparthi001** [comment]
> @daparthi001 I verified the pilot parameter "--appNamespace" works (even with limited pilot RBAC) by using a single NS for istio and the app.
> 
> ie. --appNamespace istio-system would work if you install your apps into istio-system1 ,its complaining about the istio-ingressgateway ?

i deployed the app and istio to the same namespacee istio-system1
2019-03-08T19:08:22.130794Z     info    successfully acquired lease istio-system1/istio-ingress-controller-leader-istio
2019-03-08T19:08:22.130835Z     info    New leader elected: istio-pilot-67b48cb5c6-hv495
2019-03-08T19:08:22.130852Z     info    I am the new status update leader
gc 7 @33.448s 0%: 0.021+8.3+8.9 ms clock, 0.042+6.4/2.1/5.1+17 ms cpu, 10->11->6 MB, 12 MB goal, 2 P
2019-03-08T19:09:22.139769Z     info    Work item handle failed (services "istio-ingressgateway" not found), retry after delay 1s
2019-03-08T19:09:23.143475Z     info    Work item handle failed (services "istio-ingressgateway" not found), retry after delay 1s
2019-03-08T19:09:24.146848Z     info    Work item handle failed (services "istio-ingressgateway" not found), retry after delay 1s
2019-03-08T19:09:25.151308Z     info    Work item handle failed (services "istio-ingressgateway" not found), retry after delay 1s
2019-03-08T19:09:26.154558Z     info    Work item handle failed (services "istio-ingressgateway" not found), retry after delay 1s
2019-03-08T19:09:27.159672Z     info    Work item handle failed (services "istio-ingressgateway" not found), retry after delay 1s
2019-03-08T19:09:28.163131Z     info    Work item handle failed (services "istio-ingressgateway" not found), retry after delay 1s
2019-03-08T19:09:29.170281Z     info    Work item handle failed (services "istio-ingressgateway" not found), retry after delay 1s
gc 8 @101.036s 0%: 0.008+4.2+3.7 ms clock, 0.016+0.38/0.32/7.1+7.5 ms cpu, 12->12->6 MB, 13 MB goal, 2 P

**Comment by daparthi001** [comment]
After deploying the istio-system and istio-system1 on the same cluster ,second istio-system is not  able to start proxy ,is there way we can have ingress and egress gateways working properly ?

**Comment by monkeymorgan** [comment]
Hi @daparthi001 - I've removed my multitenancy experiment so can't offer any debugging advice beyond that the ingress/egress gateways work fine restricted to a single NS and you can indeed run 2 control planes - start with configuring the sidecar injector to target the correct control plane. I'm not sure it's a good idea to use this issue to debug your setup though as we could end up getting away from the original request to support NS scoping throughout the various components.

**Comment by mojsha** [comment]
Is there any work being done on this? Our particular usecase is that our entire OpenShift cluster is multi-tenant  and we would like to have a service-mesh per project.

**Comment by brian-avery** [comment]
Hi @mojsha Have you looked at OpenShift Service Mesh? We have soft multi-tenancy support. That allows you to have multiple Istio control planes in a cluster with multiple projects being members of that control plane. 

If you're talking about a single control plane that manages multiple service meshes, then that's hard multitenancy, which I don't believe is in the plans for Istio right now.

**Comment by mojsha** [comment]
@brian-avery I had, but last I checked it was in a Tech preview state and not production ready. Has that changed? Also, how is this setup? Does it have a controller with associated CRDs or is it manual installation etc.?

**Comment by knrc** [comment]
@mojsha The changes we've been making are to remove the need for elevated privileges and cluster wide resources/role bindings etc. as well as being able to restrict the control plane components to a dynamically changing subset of namespaces associated with each control plane.  Our installation is via an operator and a CRD, one to define the control plane and a second to define the namespaces within the mesh.  It's still TP for the next month or two.  If you are interested in using this in production then contact me directly, let's leave this issue for the discussions related to multi tenancy.

**Comment by sdake** [comment]
@Monkeyanator I understand your desire for this feature, and think Istio is headed there.  The timeline is unclear, so I am marking the milestone as Nebulous future.

Cheers
-steve
