### ISSUE TITLE
[Helm chart - Prometheus]Cannot support --storage.tsdb.path customization and its persistence using persistentVolumeClaim

### ISSUE THREAD

**Issue by osswangxining** [istio/istio#11974]
Currently Prometheus Helm chart does not include the storage.tsdb.path parameter (only includes --storage.tsdb.retention and --config.file), so it cannot support customization, and also cannot use PV/PVC to persist the data.
-------------------------
- name: prometheus
          image: "{{ .Values.hub }}/prometheus:{{ .Values.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          args:
            - '--storage.tsdb.retention={{ .Values.retention }}'
            - '--config.file=/etc/prometheus/prometheus.yml'

**Expected behavior**
1.Add one more parameter: storage.tsdb.path parameter
2.Support the PV/PVC persistence

**Comment by ozevren** [comment]
Hi @osswangxining,
Which release/branch are you looking at? 1.1, master?

**Comment by osswangxining** [comment]
> Hi @osswangxining,
> Which release/branch are you looking at? 1.1, master?

Both for 1.1 & master. Currently only 2 parameters are defined: 
* --storage.tsdb.retention & --config.file

**Comment by peter-c-larsson** [comment]
Created a PR for this here: https://github.com/istio/istio/pull/13698

**Comment by sdake** [comment]
latest update: https://github.com/istio/istio/pull/13698#issuecomment-498079063

**Comment by howardjohn** [comment]
Closing as this is something we don't plan on doing -- see https://github.com/istio/istio/pull/13698#issuecomment-498079063. This can be handled by the new installer or operator
