### ISSUE TITLE
Connecting to external HTTP service returns 404 - Egress Rules

### ISSUE THREAD

**Issue by thesandlord** [istio/istio#1197]
I'm was running into a strange problem where trying to connect to external HTTP services always returns a 404. I finally figured out that by default Istio blocks all Egress HTTP traffic and created the appropriate Egress rules.

The only place I can find where this is documented is here: https://istio.io/docs/tasks/traffic-management/egress.html

None of the getting started guides really mention this. Would it be a good idea to incorporate connecting to an external service in the book review guide or at least creating a section in the troubleshooting guide? I feel this will be a common pain point for a lot of people.

**Comment by mandarjog** [comment]
@vadimeisenbergibm I think this has been addressed in the docs and by blog posts you have published.

**Comment by vadimeisenbergibm** [comment]
@mandarjog yes, I wrote it in this blog post: [Consuming External Web Services](https://istio.io/blog/2018/egress-https.html).

> So what might have gone wrong? Ah… The answer is that I forgot to enable traffic from inside the mesh to an external service... By default, the Istio sidecar proxies (Envoy proxies) block all the traffic to destinations outside the cluster. To enable such traffic, we must define an egress rule.
