### ISSUE TITLE
Established TCP connection destroyed when Envoy receives configuration from Pilot

### ISSUE THREAD

**Issue by zhaohuabing** [istio/istio#11971]
**Describe the bug**
Pilot is periodically pushing the xDS configuration to Envoy even there is no change, causing established TCP connections in Envoy broken.

Client side gets a lot of  " unexpected end of stream on Connection".

Example: java.io.IOException: unexpected end of stream on Connection{172.168.40.61:12282, proxy=DIRECT hostAddress=/172.168.40.61:12282 cipherSuite=none protocol=http/1.1}

**Expected behavior**

* Pilot shouldn't push xDS configuration to Envoy if no changes
* Established downstream connections shouldn't be destroyed by Envoy unless the upstream service closes the connection itself.

**Steps to reproduce the bug**
No special steps to reproduce the bug, just run the application with istio and check the application log.

**Version**
Istio 1.0.0

**Installation**
Microservices are deployed and managed by Kubernetes, but use Consul as the service registry

**Environment**
Ubuntu 16.04

**Cluster state**
Microservices are deployed and managed by Kubernetes, but use Consul as the service registry

**Comment by christian-posta** [comment]
Looks similar? https://github.com/istio/istio/issues/7045

Are you on 1.0? Can you try one of the newer point releases and see whether that helps?

**Comment by zhaohuabing** [comment]
This issue occurred also in the latest 1.1 branch. I built pilot binary
from 1.1 branch commit
93f74d7

**Comment by Stocco** [comment]
Are you running istio with mtls? 

> If istio-citadel is deployed, Envoy is restarted every 15 minutes to refresh certificates. This causes the disconnection of TCP streams or long-running connections between services.

>You should build resilience into your application for this type of disconnect, but if you still want to prevent the disconnects from happening, you will need to disable mutual TLS and the istio-citadel deployment.

from the guidelines: https://istio.io/help/ops/traffic-management/deploy-guidelines/

**Comment by zhaohuabing** [comment]
It turned out that this issue is caused by consul service registry service
update event.  I'm trying to find out why consul service registry is
constantly updated.

**Comment by zhaohuabing** [comment]
- Pilot shouldn't push xDS configuration to Envoy if no changes
  This has been fixed by https://github.com/istio/istio/pull/12148
- Established downstream connections shouldn't be destroyed by Envoy unless the upstream service closes the connection itself.
  This issue still exists, is it possible to keep the opened connection while Envoy configuration changed by xDS?

**Comment by plumenator** [comment]
I'm seeing this issue on version 1.3 and we're not using consul.

Described here:
https://discuss.istio.io/t/tcp-connections-terminate-periodically/3979
