### ISSUE TITLE
Tracing stopped working overnight

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio#11985]
**Describe the bug**
Started cluster with tracing enabled. Left it running over night. ~24h later, i sent 10000+ requests through the cluster. Somehow, this resulted in no traces being generated.

Jaeger's own monitoring reports:

```
# HELP jaeger_collector_spans_dropped_total spans.dropped
# TYPE jaeger_collector_spans_dropped_total counter
jaeger_collector_spans_dropped_total{host="a8d32ba532ef"} 0
# HELP jaeger_collector_spans_received_total received
# TYPE jaeger_collector_spans_received_total counter
jaeger_collector_spans_received_total{debug="false",format="jaeger",svc="jaeger-query"} 344
jaeger_collector_spans_received_total{debug="false",format="jaeger",svc="other-services"} 0
jaeger_collector_spans_received_total{debug="false",format="unknown",svc="other-services"} 0
jaeger_collector_spans_received_total{debug="false",format="zipkin",svc="other-services"} 0
jaeger_collector_spans_received_total{debug="true",format="jaeger",svc="other-services"} 0
jaeger_collector_spans_received_total{debug="true",format="unknown",svc="other-services"} 0
jaeger_collector_spans_received_total{debug="true",format="zipkin",svc="other-services"} 0
```

This shows the only spans being collected were from the jaeger app itself, with no dropped spans and none received via `zipkin` format.

**Expected behavior**
Traces to be generated and available via tracing UI.

**Steps to reproduce the bug**
Leave cluster with tracing enabled up for 24 hours. Send traffic.

**Version**
1.1-rc0

**Installation**
helm init

**Environment**
gke

**Cluster state**

**Comment by vaastav** [comment]
Hi, do you know what the issue behind this was? Was it just a configuration issue?
(I am only asking because I am doing a survey on distributed tracing in real systems.)

**Comment by douglas-reid** [comment]
@vaastav i don't know any more, but given the timing on the issue, I suspect something else went wrong with the cluster.
