### ISSUE TITLE
istioctl authn tls-check documentation doesn't match implementation

### ISSUE THREAD

**Issue by esnible** [istio/istio#11982]
https://preliminary.istio.io/docs/reference/commands/istioctl/#istioctl-authn-tls-check documentation doesn't match command.

The documentation says the syntax is `istioctl authn tls-check <pod-name[.namespace]> [<service>] [flags]`  If I actually give it two arguments it reports a syntax error:

```
istioctl authn tls-check reviews-v1-69dcdb544-mpsz5 reviews
Error: accepts at most 1 arg(s), received 2
```

The actual command says the syntax is `istioctl authn tls-check [<service>] [flags]`

The documentation should include a paragraph on how to remediate if a service is flagged as CONFLICT.

**Comment by ozevren** [comment]
Issue moved to [istio/istio.io #3360](https://github.com/istio/istio.io/issues/3360) via [**ZenHub**](https://www.zenhub.com/)
