### ISSUE TITLE
istioctl authn tls-check does not function

### ISSUE THREAD

**Issue by esnible** [istio/istio#11983]
To reproduce, install Bookinfo, then `istioctl authn tls-check reviews`

I get an error:
```
Warning! error execing into istio-pilot-66d5468759-hw7vs/istio-system discovery container: gc 1 @0.019s 6%: 0.055+1.5+1.2 ms clock, 0.44+0/1.8/1.9+9.8 ms cpu, 4->4->1 MB, 5 MB goal, 8 P
gc 2 @0.033s 9%: 0.012+1.8+1.6 ms clock, 0.10+0.20/2.3/2.0+13 ms cpu, 4->4->2 MB, 5 MB goal, 8 P

HOST:PORT     STATUS     SERVER     CLIENT     AUTHN POLICY     DESTINATION RULE
```

The error does not occur if no service is entered.

I am also not clear what a valid value for `<service>` would be.  The example when supplying `--help` is fully qualified.  I tried a bunch of examples, nothing reported anything different.

**Comment by irisdingbj** [comment]
We need to use FQDN for the service: 

‘’‘
istioctl authn tls-check details.default.svc.cluster.local
HOST:PORT                                  STATUS     SERVER        CLIENT     AUTHN POLICY     DESTINATION RULE
details.default.svc.cluster.local:9080     OK         HTTP/mTLS     HTTP       default/ 
’‘’

**Comment by irisdingbj** [comment]
@esnible Will add error info  in the command to improve user experience

**Comment by irisdingbj** [comment]
Latest istioctl authn tls-check need to specify podName.ns. But this does not work in /debug/authenticationz?proxyID=

**Comment by howardjohn** [comment]
I have a service, testserver in namespace foo. 
```
istioctl authn tls-check testserver.foo

Error: nothing to output
```
Same output for `testserver`, `testserver.foo.svc.cluster.local` as well.

**Comment by diemtvu** [comment]
Which version do you use? For 1.1, the new document is [updated](https://preliminary.istio.io/docs/tasks/security/mutual-tls/#verify-mutual-tls-configuration) . Basically, you need to include client pod in your command. eg:
```
istioctl authn tls-check $POD_ID testserver.foo.svc.cluster.local
```

There was error on version before 1.0.3 too, so you will need to try with 1.0.4 or 1.0.5

Thanks.

**Comment by howardjohn** [comment]
Thanks, I was using 1.1 snapshot 5, updating to rc1 fixed this. @esnible if you are using 1.1 it sounds like you need to provide the pod name, not `reviews`.

**Comment by esnible** [comment]
https://github.com/istio/istio/pull/11924 and https://github.com/istio/istio.io/issues/3360 and https://github.com/istio/istio.io/pull/3343 fix the problem.

**Comment by ajitchahal** [comment]
Does not work, still empty results:
`
istioctl version
client version: 1.2.1

echo $SLEEP_POD                                                                                                                                                    
nginx-5d78c7bb9b-9hxrc.argonauts

istioctl authn tls-check ${SLEEP_POD} nginx2.argonauts.svc.cluster.local                                                                                             
HOST:PORT     STATUS     SERVER     CLIENT     AUTHN POLICY     DESTINATION RULE
`

**Comment by blkwtch** [comment]
Hello

I am facing the same issues with istio-1.1.9

istioctl  -c kc.yaml -n bookinfo authn tls-check details-v1-5df567f4f6-7p48x.bookinfo details.bookinfo.svc.cluster.local
> Error: nothing to output

**Comment by engmsaleh** [comment]
Same here with `Istio 1.2`
```$ istioctl authn tls-check identity-service-6f5b8fb9c4-8dg8t identity-service.services.svc.cluster.local

Error: nothing to output
```

**Comment by WxFang** [comment]
I did many tests and the following command works for me:
```
istioctl -n istio-system authn tls-check istio-ingressgateway-8b784445c-g2hcp istio-pilot.istio-system.svc.cluster.local
```
the command needs the namespace of client pod and full name of test service.

**Comment by esnible** [comment]
For those getting this error, how many Pilot instances are running in istio-system namespace?

Can anyone having this problem run with `--log_output_level debug` and paste the output here?

**Comment by denniseffing** [comment]
>[...] the following command works for me:
> 
> ```
> istioctl -n istio-system authn tls-check istio-ingressgateway-8b784445c-g2hcp istio-pilot.istio-system.svc.cluster.local
> ```

Even this command is not working for me.
```
Error: nothing to output
```

**Comment by esnible** [comment]
@denniseffing Which version of istioctl are you using?  Can you try with `--log_output_level debug`?

Recent versions are supposed to say "Error: checked 1 pilot instances and found no authentication info for <pod>.<namespace>", not "nothing to output".

As WxFang reported, the command needs the full name of the service -- but you are using that.  If the user does not give the full name the output seems to be the header but no details lines.  That output could be made clearer.

**Comment by denniseffing** [comment]
I am using Istio 1.2.4.

**Comment by esnible** [comment]
Works for me.  The message output is 

```
Error: checked 1 pilot instances and found no authentication info for istio-ingressgateway-8b784445c-g2hcp.istio-system, check proxy status
```
