### ISSUE TITLE
Make cert location watched by pilot agent configurable

### ISSUE THREAD

**Issue by pnambiarsf** [istio/istio#11984]
**Describe the feature request**
Make cert location used by pilot-agent configurable such that pilot-agent can watch for cert changes on bare metal hosts where we don't have control over /etc and therefore certs cant be delivered to the default location - /etc/certs/

**Describe alternatives you've considered**
There is no alternative for bare metal hosts.

**Additional context**

**Comment by drichelson** [comment]
I'm working on the same project as @pnambiarsf and would like to start work on this issue. Any additional input is welcome. 

Assuming it gets merged in time is it possible to include this in the 1.1.0 release?

**Comment by rshriram** [comment]
if you could get this done in the next couple of days, then there is a good chance of this making it into 1.1 .. The fix should be very straightforward.

Also please note that the pilot-agent watching thing is going to be deprecated or out of fashion very soon. We are getting support for Envoy SDS. the (badly named) node agent is going to be serving SDS to envoys. You might want to check the SDS related PRs in the queue.. and test drive that code 

cc @JimmyCYJ / @myidpt etc..

**Comment by pnambiarsf** [comment]
We don't use Citadel for cert management (company requirement). We integrate Istio with our own cert management solution and therefore can't try out node agent as is. We will need to integrate that with our cert management. Moving to SDS is on our roadmap.

**Comment by rshriram** [comment]
Ah cool.. 
this is where you need to change: https://github.com/istio/istio/blob/master/pilot/cmd/pilot-agent/main.go#L244
(model.AuthCertsPath).. You need a CLI option in pilot agent. It would also be good if you created a field in the helm template (not mandatory) under pilot, with something like mTLSCertsLocation with value set to /etc/certs or whatever the current default is. This variable should ideally control the value of the cli option to pilot agent, in the sidecar injection template.

**Comment by drichelson** [comment]
Thanks @rshriram for the guidance. Unfortunately our cert paths + filenames don't conform to the existing convention, so I'm considering refactoring the watcher to take a slice of absolute paths to watch, then we can configure it with any number of client/server certs/keys. All defaults shall remain in place.

**Comment by rshriram** [comment]
I just realized that this isn't sufficient.. Its not enough to modify the agent to watch the new cert path. What about envoy? the inbound listeners in Envoy are still using TLS contexts that have the /etc/certs/.. as the location of the cert. dont you need a CLI option in pilot (or in the global mesh config) to tell pilot to generate TLS contexts with these custom paths?

**Comment by myidpt** [comment]
@rshriram good point. I think you will need a global mesh config to instruct both Pilot and Pilot-agent.

**Comment by drichelson** [comment]
@rshriram @myidpt Good points. The initial PR only addresses the pilot-agent file watchers. This issue won't be fully resolved until further work is done to enable more configurability elsewhere as you mention.

**Comment by rshriram** [comment]
from that point of view, do you want to move this work to master branch instead of release-1.1 ?

**Comment by drichelson** [comment]
Based on feedback here and in the intial PRs I propose moving forward as follows:

1. Closing existing PRs as they target release-1.1
1. Open new PR in api repo that contains:
 - In ProxyConfig: a new `repeated string` field allowing configuration of certs to watch (see closed api PR)
 - In MeshConfig either 3 new string fields or one new struct containing cert locations for mesh traffic to be used [here](https://github.com/istio/istio/blob/3b075ce3ae60587f0706215c2808bbf0330c1acf/pilot/pkg/networking/plugin/authn/authentication.go#L114-130) 
1. New PR in istio making use of the 2 new fields in api

Outside the scope of this Issue:
1. mTLS connection between envoy and Pilot-Discovery config is unchanged. 
1. mTLS connection between Pilot-Discovery and Mesh Configuration Protocol Server (MCP) us unchanged

How does this sound @rshriram ?

**Comment by drichelson** [comment]
@myidpt I like the idea of a shared config struct used by PIlot and Pilot-agent, but I'm not seeing one. It looks like Pilot uses MeshConfig and PIlot-agent uses ProxyConfig. Additionally, there is a bit of a mismatch between what those 2 configs might look like: For PIlot we want to specify server certs for mesh traffic only, as we specify client certs in the DestinationRules. For Pilot-agent's watcher we only care about a list of files to watch.

**Comment by linsun** [comment]
should we close this as PR is merged?  This is mentioned in release note 1.0.5, better to be closed

cc @duderino @geeknoid

**Comment by valarauca** [comment]
Could the official documentation be updated to state how the configuration path can be changed? 

`pilot-agent proxy` doesn't list flags related to this feature: https://istio.io/docs/reference/commands/pilot-agent/#pilot-agent-proxy

Also I'm not aware if it is related but the configuration template that `pilot-agent proxy` passes to `envoy`: https://github.com/istio/istio/blob/76b2c8cd1f5f5bdd93dab74e1b28d618786a132d/tools/packaging/common/envoy_bootstrap_v2.json appears to still have its certificate locations hardcoded

**Comment by howardjohn** [comment]
Since it has been a month since Lin asked if this should be closed, I think this is safe to close

**Comment by drichelson** [comment]
This new feature is implemented via env vars following the existing convention for adding envoy node metadata fields. The cert files get watched for changes by pilot-agent and are used to connect to pilot-discovery. They are also used in mutual TLS mesh traffic. 

Here are the env vars:
```
ISTIO_META_TLS_CLIENT_ROOT_CERT
ISTIO_META_TLS_CLIENT_CERT_CHAIN
ISTIO_META_TLS_CLIENT_KEY
ISTIO_META_TLS_SERVER_ROOT_CERT
ISTIO_META_TLS_SERVER_CERT_CHAIN
ISTIO_META_TLS_SERVER_KEY
```
