### ISSUE TITLE
In-cluster applications cannot access kube-apiserver

### ISSUE THREAD

**Issue by sdake** [istio/istio#12005]
**Describe the bug**
An in-cluster application cannot access kube-apiserver.

**Expected behavior**
An in-cluster application can access kube-apiserver.

**Steps to reproduce the bug**
Following the instructions here:
https://preliminary.istio.io/docs/tasks/security/authn-policy/#request-from-istio-services-to-kubernetes-api-server

```
Stevens-MacBook-Pro:istio-1.1.0-rc.0 sdake$ kubectl create ns foo
namespace "foo" created
Stevens-MacBook-Pro:istio-1.1.0-rc.0 sdake$ kubectl apply -f <(istioctl kube-inject -f samples/httpbin/httpbin.yaml) -n foo
service "httpbin" created
deployment.extensions "httpbin" created
Stevens-MacBook-Pro:istio-1.1.0-rc.0 sdake$ kubectl apply -f <(istioctl kube-inject -f samples/sleep/sleep.yaml) -n foo
serviceaccount "sleep" created
service "sleep" created
deployment.extensions "sleep" created
Stevens-MacBook-Pro:istio-1.1.0-rc.0 sdake$ kubectl create ns bar
namespace "bar" created
Stevens-MacBook-Pro:istio-1.1.0-rc.0 sdake$ kubectl apply -f <(istioctl kube-inject -f samples/httpbin/httpbin.yaml) -n bar
service "httpbin" created
deployment.extensions "httpbin" created
Stevens-MacBook-Pro:istio-1.1.0-rc.0 sdake$ kubectl apply -f <(istioctl kube-inject -f samples/sleep/sleep.yaml) -n bar
serviceaccount "sleep" created
service "sleep" created
deployment.extensions "sleep" created
Stevens-MacBook-Pro:istio-1.1.0-rc.0 sdake$ kubectl create ns legacy
namespace "legacy" created
Stevens-MacBook-Pro:istio-1.1.0-rc.0 sdake$ kubectl apply -f samples/httpbin/httpbin.yaml -n legacy
service "httpbin" created
deployment.extensions "httpbin" created
Stevens-MacBook-Pro:istio-1.1.0-rc.0 sdake$ kubectl apply -f samples/sleep/sleep.yaml -n legacy
serviceaccount "sleep" created
service "sleep" created
deployment.extensions "sleep" created
Stevens-MacBook-Pro:istio-1.1.0-rc.0 sdake$ kubectl apply -f - <<EOF
> apiVersion: networking.istio.io/v1alpha3
> kind: DestinationRule
> metadata:
>  name: "api-server"
> spec:
>  host: "kubernetes.default.svc.cluster.local"
>  trafficPolicy:
>    tls:
>      mode: DISABLE
> EOF
destinationrule.networking.istio.io "api-server" configured
Stevens-MacBook-Pro:istio-1.1.0-rc.0 sdake$ TOKEN=$(kubectl describe secret $(kubectl get secrets | grep default | cut -f1 -d ' ') | grep -E '^token' | cut -f2 -d':' | tr -d '\t')
Stevens-MacBook-Pro:istio-1.1.0-rc.0 sdake$ kubectl exec $(kubectl get pod -l app=sleep -n foo -o jsonpath={.items..metadata.name}) -c sleep -n foo -- curl https://kubernetes.default/api --header "Authorization: Bearer $TOKEN" --insecure -s -o /dev/null -w "%{http_code}\n"
000
command terminated with exit code 35
```

I would expect a code 200 here, not a code 35...

**Version**
istio-1.1.0-rc0

**Installation**
helm install istio --namespace istio-system --name istio

**Environment**
Azure with Kubernetes deployed on VMs rrather then using Microsoft's hosted platform.

**Comment by sdake** [comment]
I'd imagine this is a complete blocker for the adoption of Istio 1.1.  Many folks have in-cluster software that runs - and that wouldn't work with sidecars.  Unfortunately, I don't know how to fix this problem.

I have a cluster from a few weeks ago that doesn't suffer this problem based on a release-1.1, so I am going to bisect the repo to help provide a rough pointer at where the problem was introduced.

I will bisect Monday but may not be able to actually resolve the problem - just identify the offending patch.

cc / @duderino

**Comment by sdake** [comment]
Note I don't think the environment is relevant here but will rule it out by running rc0 on bare metal.

Cheers
-steve

**Comment by sdake** [comment]
Running rc0 on bare metal doesn't exhibit this problem.

Seems like an environmental issue.  I had 4 cpus with a total of 7gb of ram available, and startup was timing out (out of memory errors).   Will report more tomorrow.

Cheers
-steve

**Comment by sdake** [comment]
Well, this is environmental of some sort.  It isn't azure specific - possibly related to how the kubeapi certs are created in the deployment tooling I am using.  I am removing this from the 1.1 release since it is likely a problem with deployment.

**Comment by costinm** [comment]
the IP of the api servier is from an env variable, set by kubelet - $KUBERNETES_SERVICE_HOST
Normally it is the ClusterIP of the apiserver
And if you dump the config, you should see a listener on that IP and 443, with a TCP proxy to outbound|443||kubernetes.default.svc.cluster.local
From slack: 
If a vendor ( for whatever reasons ) sets the KUBERNETES_SERVICE_HOST to anything else but the ClusterIP - it would break
It would be treated as egress, and blocked unless a DR is configured.  Unless Lin's change to allow outbound traffic by default is enabled.

**Comment by sdake** [comment]
duplicate of https://github.com/istio/istio/issues/12121.  Verified the solution and closing.
