### ISSUE TITLE
Istio Not Setting 'x-b3-sampled: 1' when sampling

### ISSUE THREAD

**Issue by dansiviter** [istio/istio#12019]
**Describe the bug**
When Istio performs a trace sample, based on `sampleProbability` it always informs the receiver to not trace via `x-b3-sampled: 0`. This leads to incomplete traces as the receiver is never informed to perform trace.

**Expected behavior**
Client sends:
* `x-b3-sampled: 0`: Istio and underlying receiver **do not** trace,
* `x-b3-samples: 1`: Istio and underlying receiver **do** trace, ⚠️ Istio ignores the flag, although it should potentially override it to avoid resource over-utilisation.
* `x-b3-sampled` not set, Istio `sampleProbability` returns `false`: Istio and underlying receiver **do not** trace, ⚠️ `x-b3-sampled: 0` is sent regardless which is potentially an issue,
* `x-b3-sampled` not set, Istio `sampleProbability` returns `true`: Istio and underlying receiver **do** trace, ❗️ This is the case that is failing causing incomplete traces as `x-b3-sampled: 0` is always sent.

Therefore, unless `x-b3-sampled` is specified by the client, if Istio decides to sample the trace it should inform the receiver to also sample.

**Steps to reproduce the bug**
GKE with Istio and Stackdriver `tracespan` configured (based on [stackdriver.yaml](https://github.com/istio/istio/blob/1.1.0-snapshot.6/mixer/adapter/stackdriver/operatorconfig/stackdriver.yaml)) and underlying receiver using OpenCensus B3 Propagation.

**Version**
1.1.0-snapshot.6 (although this appears to be in 1.0.6 also)

**Installation**
Helm installation on GKE using Stackdriver tracing

**Environment**
GKE 1.11.7-gke.6

**Cluster state**
N/A

**Comment by dansiviter** [comment]
BTW, I understand that it's not good practice to allow the client to dictate the span behaviour as that could lead to increasing costs on the back-end and potentially hampering performance. However, Istio should be trusted to make a span sample decision which propagates.

**Comment by douglas-reid** [comment]
Is there confusion here between tracing w/ the Stackdriver adapter, which has its own sampling impl, and the Envoy-generation of sampling headers?

The Stackdriver adapter handling should not impact the header propagation throughout the system.

**Comment by douglas-reid** [comment]
@kyessenov would it be possible to use the route directive work to add headers based on adapter sampling decisions?  this probably isn't ideal, but might help in the case when envoy sampling and mixer adapter-based sampling diverge.

**Comment by dansiviter** [comment]
Not sure if it's related, but `X-Request-Id` also appears to not be propagated from the client and a new one created and overriding (#10875). This superficially looks like `X-B3-Sampled: 1` from the client also being overridden.

Therefore, I'm wondering there are two issues here: the Stackdriver adaptor not setting the value when it samples and Envoy overriding it further down the chain.

**Comment by dansiviter** [comment]
Apologies, I think I've conflated with the `X-Request-Id` thing. It appears that `X-B3-Sampled` is always passed down to the underlying service via Envoy.

So, back on topic... I tried disabling all other tracers, except Stackdriver. I set:
* Stackdriver `trace.sampleProbablity: 0` - 0%
* `pilot.traceSampling: 10` - 10%
Now the `X-B3-Sampled` is correctly being set 10% of the time, but no data is now going into Stackdriver (expected for Istio, but not expected for underlying OpenCensus unless Stackdriver is not finding a valid `x-parent-trace-id` and throwing it away?!).

I also tried setting the default values:
* Stackdriver `trace.sampleProbablity: 0.1` - 10%
* `pilot.traceSampling: 1` - 1%

Now the app level tracing appears, stackdriver appears at 10% and `X-B3-Sampled` is set at 1% inline with the pilot config. However, the traces are still somewhat disjointed.

Therefore, I feel @douglas-reid is right that the Stackdriver adaptor should be setting the `X-B3-Sampled` header when it decides to sample, Pilot/Envoy and everything downstream will then just honour that.

At this time, I feel the only way we can get reliable traces is to set: 100% on `trace.sampleProbablity`, `pilot.traceSampling` and underlying service which won't scale well.

**Comment by douglas-reid** [comment]
@dansiviter i think the correct "fix" involves a code change to enable the stackdriver adapter to respect sampling decisions made by the proxy -- and to control sampling via `pilot.traceSampling`. Mixer telemetry adapters don't have a way to set headers in requests -- and adding a sampling policy adapter just to sets headers doesn't seem like the best approach.

I'm gonna take a look at how to modify the Stackdriver adapter code / config now.

**Comment by dansiviter** [comment]
@douglas-reid I wasn't sure if that was possible but if sampling configuration is in one place then that's even better. I see there is some chatter around integration of OpenCensus into Envoy (envoyproxy/envoy#2456) which may help cover differed sampling types in the future too.

**Comment by douglas-reid** [comment]
@dansiviter another possible workaround. hoping you can maybe test it out for me:

1. Set the handler config for the Stackdriver adapter to have a sampling rate of `1` (always sample).
1. Update the match condition on the handler to be:

`(context.protocol == "http" || context.protocol == "grpc") && request.headers["x-b3-sampled"] == "1"`

**Comment by kyessenov** [comment]
IMHO it sounds to me that the sampling decision needs to be made at the proxy if it were to propagate. Telemetry adapters run out of sync, and it's too late to force tracing from them. Therefore, we should probably recommend sampling rate is 100%, and let the proxy control sampling.

In the future, sampling could be made first-class config, so that this config can be acted upon at the proxy.

**Comment by douglas-reid** [comment]
@dansiviter I tested the config in my own istio-on-gke cluster and it seemed to do the trick. I think that is what we should recommend moving forward.

**Comment by dansiviter** [comment]
@douglas-reid Yea, workaround does the trick for me too. Thanks

**Comment by douglas-reid** [comment]
@dansiviter I think this issue has become one of documentation. I'm going to close this for now. Please feel free to re-open if you feel that is more appropriate.

**Comment by bnerDY** [comment]
> @dansiviter another possible workaround. hoping you can maybe test it out for me:
> 
> 1. Set the handler config for the Stackdriver adapter to have a sampling rate of `1` (always sample).
> 2. Update the match condition on the handler to be:
> 
> `(context.protocol == "http" || context.protocol == "grpc") && request.headers["x-b3-sampled"] == "1"`

please make sure it is using string ***"1"*** for the workaround .....
