### ISSUE TITLE
Example 'Cluster-Aware Service Routing' fails due to timing

### ISSUE THREAD

**Issue by c0d1ngm0nk3y** [istio/istio#12018]
**Describe the bug**
When installing cluster 2 as described [here](https://preliminary.istio.io/docs/examples/multicluster/split-horizon-eds/#setup-cluster-2), step 3 mentions:

```
$ kubectl create --context=$CTX_CLUSTER2 ns istio-system
$ kubectl create --context=$CTX_CLUSTER2 secret generic cacerts -n istio-system --from-file=samples/certs/ca-cert.pem --from-file=samples/certs/ca-key.pem --from-file=samples/certs/root-cert.pem --from-file=samples/certs/cert-chain.pem
$ kubectl create --context=$CTX_CLUSTER2 -f istio-remote-auth.yaml
``` 

This results in the egress-gateway to fail with an error about missing certs. After restarting the pod, it works.

Reason: The secret is generated in the same step as the egress-gateway that mounts it as optional mount.

**Expected behavior**
To either works smoothly or at least mention that the egress-gateway has to be restarted. Seperating it into 2 steps should be enough.

**Steps to reproduce the bug**
Follow the example description until [2.2](https://preliminary.istio.io/docs/examples/multicluster/split-horizon-eds/#setup-cluster-2).

**Version**
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-04T04:49:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

Istio 1.1.0-rc.0

**Installation**
As described in the example.

**Environment**
AWS cluster.

**Comment by c0d1ngm0nk3y** [comment]
This came up during community testing for 1.1, unfortunately I am not able to set the milestone.

**Comment by linsun** [comment]
@c0d1ngm0nk3y seems sufficient doc would help in this case... cc @ymesika

**Comment by ymesika** [comment]
@c0d1ngm0nk3y with the next RC (or final) release of 1.1 the egress won't be installed by default.
Because the steps in the Cluster-aware doc are based on the default Istio values there won't be egress on both primary and secondary clusters. Which kind of indirectly solves this issue.

**Comment by c0d1ngm0nk3y** [comment]
@ymesika Thanks for the information, but the ingress has the same problem. So this this is probably not solved by this alone. But @linsun is of course right, better documentation should be enough. We will push a PR.

**Comment by ymesika** [comment]
@c0d1ngm0nk3y It finally catches up with the generated secrets/certs. It just takes time until the proxy is picking the newly created secrets from the volume. You can tail the logs from the ingress and see that after 30-60sec it loads the certs and connect to pilot with those.

Or, as you suggested just kill the pod but this will appear a little hacky if we ask the user to do this in the doc.

**Comment by c0d1ngm0nk3y** [comment]
@ymesika You are right. It was somehow hidden by issue #12021. So I will close this one.
