### ISSUE TITLE
Istio sidecar injection is not concurrent with k8s pod creation

### ISSUE THREAD

**Issue by Hongwei-Wang** [istio/istio#12027]
**Describe the bug**
Istio sidecar injection is usually slower than k8s pod creation, which causes the pod in the `CrashLoopBackOff` status for the first seconds.
As I measured, pod creation takes about less than 5 seconds, while istio side injection takes over 10 seconds.

**Expected behavior**
Istio sidecar injection should be concurrent with k8s pod creation

**Steps to reproduce the bug**
1. Create a k8s cluster and install istio
2. Deploy a Flask app to an istio-enabled namespace
3. Force delete the pod and the new one will be in `CrashLoopBackOff` status for the first seconds

**Version**

$ istioctl version
Version: 1.0.5
GitRevision: c1707e45e71c75d74bf3a5dec8c7086f32f32fad
User: root@xxxxxxx
Hub: docker.io/istio
GolangVersion: go1.10.4
BuildStatus: Clean

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.11-eks", GitCommit:"6bf27214b7e3e1e47dce27dcbd73ee1b27adadd0", GitTreeState:"clean", BuildDate:"2018-12-04T13:33:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Installation**
1. Generate `istio` manifest using `helm template`
2. Apply the manifest to k8s cluster

**Environment**
Run k8s cluster on EKS

**Comment by ostromart** [comment]
Can you explain what you measured exactly? Mutating webhooks are in line with the pod creation request i.e. master controller calls out to sidecar injector which adds the sidecar to the manifest, then the controller creates the resulting pod. Concurrency shouldn't come into it - most likely something else is going on.
Could you include the pod logs and kubectl describe for the crashlooping pods?

**Comment by Hongwei-Wang** [comment]
I can not reproduce this issue on the same cluster anymore. The sidecar is concurrently injected w/ pod. It's so weird.

**Comment by ostromart** [comment]
@Hongwei-Wang if you see this again, please include logs from crashlooping pods.

**Comment by Hongwei-Wang** [comment]
@ostromart Yeah, thanks for helping!
