### ISSUE TITLE
preliminary 1.1 doc "Jaeger" results in jaeger instance that does not detect zipkin services

### ISSUE THREAD

**Issue by bdecoste** [istio/istio#12025]
Describe the bug
{{
https://preliminary.istio.io/docs/tasks/telemetry/distributed-tracing/zipkin/

Similar to https://github.com/istio/istio/issues/11976

Should add "--set pilot.traceSampling=100" to doc
}}

Expected behavior
{{
Zipkin console detects and displays bookinfo services
}}

Steps to reproduce the bug
{{
Follow doc steps. Install Istio using Step 2 from here: https://preliminary.istio.io/docs/setup/kubernetes/helm-install/#option-2-install-with-helm-and-tiller-via-helm-install
}}

Version
{{
istio-1.1.0-snapshot.6

Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
}}

Installation
{{
Follow doc steps
}}

Environment
{{
Openshift Container Platform 3.11
minikube version: v0.34.1
}}

Cluster state
{{
N/A
}}

**Comment by douglas-reid** [comment]
I believe this has been addressed. Closing.
