### ISSUE TITLE
istio.io/istio/tests/e2e/tests/simple TestAuth 0.72s

### ISSUE THREAD

**Issue by duderino** [istio/istio#12037]
**Describe the bug**

https://k8s-gubernator.appspot.com/builds/istio-prow/pr-logs/directory/e2e-simpleTests-cni fails every time due either to env issue or this error.  The error suggests something is insecure when it's supposed to be secure so definitely needs some scrutiny.   

If the problem is only in the test and not the code itself then a lower priority could be more appropriate.

```
raw-cli-deployement-58d58f675b-dqw78
HTTP/1.1 200 OK
Content-Type: text/plain; charset=UTF-8
Date: Mon, 25 Feb 2019 11:50:38 GMT
Content-Length: 307

Φορτίο version 1.3.1 2019-02-02 22:18 fd8f4a7177e9ea509f27105ae4e55e6c68ece6f7 go1.11 echo debug server up for 2m10.1s on echosrv-deployment-1-79fdd8b765-xwjzs - request from 10.40.2.13:48504

GET /debug HTTP/1.1

headers:

Host: echosrv.istio-system:8080
User-Agent: fortio.org/fortio-1.3.1

body:


a_simple_1_test.go:193: Running with auth on yet able to connect from non istio to istio (insecure): HTTP/1.1 200 OK
	Content-Type: text/plain; charset=UTF-8
	Date: Mon, 25 Feb 2019 11:50:38 GMT
	Content-Length: 307
	
	Φορτίο version 1.3.1 2019-02-02 22:18 fd8f4a7177e9ea509f27105ae4e55e6c68ece6f7 go1.11 echo debug server up for 2m10.1s on echosrv-deployment-1-79fdd8b765-xwjzs - request from 10.40.2.13:48504
	
	GET /debug HTTP/1.1
	
	headers:
	
	Host: echosrv.istio-system:8080
	User-Agent: fortio.org/fortio-1.3.1
	
	body:
```

**Comment by liminw** [comment]
The same [test](https://github.com/istio/istio/blob/master/tests/e2e/tests/simple/a_simple_1_test.go#L193) passed if cni is not enabled. https://k8s-gubernator.appspot.com/builds/istio-prow/pr-logs/directory/e2e-simpleTests

My guess is It is likely that the failure due to Envoy sidecar is not injected properly in CNI deployment. @duderino Can someone from networking team take a look at the sidecar injection for CNI deployment?

**Comment by liminw** [comment]
The test started failing from 2/19 (https://k8s-gubernator.appspot.com/builds/istio-prow/pr-logs/directory/e2e-simpleTests-cni?before=766). Looking at the PR history, it seems that the PR that is related to sidecar injection is https://github.com/istio/istio/pull/11321. @rshriram @SchSeba Could you check if this is related to the failure here?

**Comment by SchSeba** [comment]
Hi @liminw I can't find anything related to my [PR](https://github.com/istio/istio/pull/11321).

I try to check the istio/cni repo and the iptable.sh script don't contains my change there (I need to open one for the cni). But again I am not sure how the fails are related to my PR.

There is a test that pass "2019-02-23 00:38 IST" https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/11823/e2e-simpleTests-cni/950/

**Comment by duderino** [comment]
I think @tiswanso fixed this

**Comment by duderino** [comment]
err, perhaps not.  @tiswanso any advice?

**Comment by tiswanso** [comment]
The PR #11877 is needed for the fixes to the istio-cni prow test to work with the new helm install scheme (istio helm chart removed all the istio-cni dependency).

**Comment by wenchenglu** [comment]
@tiswanso 
looks like https://github.com/istio/istio/pull/11877 has been merged. Can this issue be closed now or still some pending work?

**Comment by duderino** [comment]
@tiswanso can this be closed?

**Comment by tiswanso** [comment]
Closing this issue now that #11877 merged
