### ISSUE TITLE
Galley should have option to only watch installed CRDs

### ISSUE THREAD

**Issue by ayj** [istio/istio#12033]
Galley creates k8s watchers for all enabled k8s source resources. Resources can be explicitly excluded with the `--excludedResourceKinds` command line option. It would be useful for Galley to have an option to only create k8s watchers for k8s resources that are available in the k8s apiserver. This auto-detect mechanism should be guarded by a flag to preserve the more explicit behavior today. This could be guarded by the `--disableResourceReadyCheck` flag where `false` is the current default and `true` which enable the proposed auto-detect behavior.

**Comment by ozevren** [comment]
The new config processing pipeline in Galley (currently off by default) can detect changes to the CRDs and adapt. It can also startup with a limited set of CRDs.

**Comment by ozevren** [comment]
The new pipeline is active now. Closing.
