### ISSUE TITLE
Istio 1.1 helm Installation instructions don't verify

### ISSUE THREAD

**Issue by qfel** [istio/istio#12046]
**Describe the bug**
Following the instructions at https://preliminary.istio.io/docs/setup/kubernetes/helm-install/ option 1.5. "Verify that all 58 Istio CRDs were committed to the Kubernetes api-server using the following command:" prints 56.

**Expected behavior**
Per instructions, 58 should be printed

**Steps to reproduce the bug**
Follow https://preliminary.istio.io/docs/setup/kubernetes/helm-install/ choosing option 1, till "Verify that all 58 Istio CRDs were committed to the Kubernetes api-server using the following command:".

**Version**
```shell
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.7-gke.6", GitCommit:"144b681e3870074abfdaaf176e48b1b13360d7e5", GitTreeState:"clean", BuildDate:"2019-02-09T00:08:19Z", GoVersion:"go1.10.7b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Installation**
https://preliminary.istio.io/docs/setup/kubernetes/helm-install/

**Environment**
GKE

**Cluster state**
[istio-dump.tar.gz](https://github.com/istio/istio/files/2903094/istio-dump.tar.gz)

**Comment by qfel** [comment]
Not the instructions say 56, but I get 58..

**Comment by duderino** [comment]
Closing in favor of https://github.com/istio/istio/issues/11951 which as more state.  Still an open bug
