### ISSUE TITLE
Using literals for metric dimensions doesn't work as expected

### ISSUE THREAD

**Issue by kramerul** [istio/istio#12059]
**Describe the bug**

Using literals for metric dimensions breaks the reporting of the metric.

**Expected behavior**

Metrics are reported

**Steps to reproduce the bug**

Use the [telemetry example](https://istio.io/docs/tasks/telemetry/metrics-logs/) and replace

```
    reporter: conditional((context.reporter.kind | "inbound") == "outbound", "client", "server")
```

by 

```
    reporter: "test"
```

or by 

```
    reporter: '"test"'
```

After this change, the [query in Prometheus](http://localhost:9090/graph#%5B%7B%22range_input%22%3A%221h%22%2C%22expr%22%3A%22istio_double_request_count%22%2C%22tab%22%3A1%7D%5D) doesn't return any new results.

**Version**

istio-1.1.0-rc.0

**Installation**

```
wget https://github.com/istio/istio/releases/download/1.1.0-rc.0/istio-1.1.0-rc.0-linux.tar.gz
tar xzfv istio-1.1.0-rc.0-linux.tar.gz 
cd istio-1.1.0-rc.0/
for i in install/kubernetes/helm/istio-init/files/crd*yaml; do kubectl apply -f $i; done
kubectl apply -f install/kubernetes/istio-demo.yaml
```

**Environment**

Google

**Cluster state**

**Comment by douglas-reid** [comment]
@kramerul i believe that you are confusing a few issues. You can indeed replace `reporter` with `'"test"'` and have it work.

I just tested this and was able to execute the following promQL query: `sum(istio_requests_total) by (reporter)`.

I got the following results:

```
{reporter="test"} | 81
```

Where I think you may be getting tripped up is trying to redefine `requestcount` metrics without also updating the prometheus handler config -- leading to cardinality issues with collected metrics.

Closing this issue.
