### ISSUE TITLE
Galley server mode command-line flags are global

### ISSUE THREAD

**Issue by ozevren** [istio/istio#12068]
Galley has three top level commands:
- probe
- version
- root (i.e. server mode)

Since server mode is the root command, all of its flags appear global. The right fix is to create a server command and move its commands there (keeping only logging flags as global.

**Comment by ozevren** [comment]
sidecar injector also suffers from the same thing: https://preliminary.istio.io/docs/reference/commands/sidecar-injector/

**Comment by costinm** [comment]
Is this something we need to fix for 1.1 ? Not user visible, no negative impact.
