### ISSUE TITLE
multiple timeseries are generated in telemetry when going to istio-ingressgateway from inside mesh

### ISSUE THREAD

**Issue by jmazzitelli** [istio/istio#12063]
**Describe the bug**

Sending a request to istio-ingressgateway from a pod that has a sidecar results in two timeseries. See below for more details.

**Expected behavior**

I would have thought only a single timeseries would result for this.

**Steps to reproduce the bug**

The basic steps to replicate are:

1. Install latest Istio, and the latest bookinfo demo, and the latest Kiali
2. Install Kiali's traffic generator test pod with a sidecar, and have it push requests to bookinfo through the istio-ingressgateway (via the URL http://istio-ingressgateway.istio-system.svc.cluster.local/productpage). You do this by executing the following two commands to create the configmap then the deployment:

```
curl https://raw.githubusercontent.com/kiali/kiali-test-mesh/master/traffic-generator/openshift/traffic-generator-configmap.yaml | DURATION='0s' ROUTE="http://istio-ingressgateway.istio-system.svc.cluster.local/productpage" RATE="1"  envsubst | kubectl create -n bookinfo -f -

curl https://raw.githubusercontent.com/kiali/kiali-test-mesh/master/traffic-generator/openshift/traffic-generator.yaml | istioctl kube-inject -f - | kubectl create --validate=false -n bookinfo -f -
```

**Version**

We've seen this with Istio 1.1.0-snapshot.6 as well as the latest 1.1.0-rc.0.

**Installation**

Normal installation. Nothing fancy.

**Environment**

OpenShift 3.11, but the cluster environment shouldn't matter.

**Gory Details**

With a pod (with sidecar) inside the mesh pushing requests at 1-request-per-second to the istio-ingress, there are two timeseries that result. Yes, this is weird - why would someone push a request through ingressgateway if already in the mesh? This was done inside Kiali's QE test environment - there is no real world use-case I can apply this to off the top of my head. That being said, it still seems weird that two timeseries are the result. The question is - is this just a quirk of how istio-ingressgateway is being accessed (from inside the mesh) or is this a more general problem that should be fixed?

Here's what Kiali's workload graph shows when this is done. Notice there are TWO edges leaving kiali-traffic-generator when there should be only one (kiali-traffic-generator only ever sends requests to the istio-ingressgateway - it never directly makes requests to productpage, yet here we see the telemetry showing this):

![wl](https://user-images.githubusercontent.com/2029470/53422512-9bf28b00-39ad-11e9-86a0-4e5e5a045e6f.png)

If we inject service nodes in the Kiali graph, you see this telemetry visualized thusly:

![wl-with-svc](https://user-images.githubusercontent.com/2029470/53422536-a745b680-39ad-11e9-9ec4-f3b979484035.png)

Notice the request-per-seconds - its showing 2 requests per second leaving the traffic generator. This is incorrect but is a result of the fact we have two timeseries here when there should have been only one.

Here's the prometheus query:

```
sum(istio_requests_total{source_workload="kiali-traffic-generator", reporter="source", 
       source_workload_namespace="bookinfo"}) by (reporter, destination_service, 
       destination_workload, destination_workload_namespace)
```
 
which results in two timeseries:

```
{destination_service="istio-ingressgateway.istio-system.svc.cluster.local",
destination_workload="istio-ingressgateway",
destination_workload_namespace="istio-system",
reporter="source"}
```

and

```
{destination_service="istio-ingressgateway.istio-system.svc.cluster.local",
destination_workload="productpage-v1",
destination_workload_namespace="bookinfo",
reporter="source"}
```

Take a look at these two timeseries that are a result of the traffic generator sending requests to `http://istio-ingressgateway.istio-system.svc.cluster.local/productpage` - the question is:

How can one request to destination_service "istio-ingressgateway" result in going to destination_workload "productpage-v1.bookinfo" ***and*** destination_workload "istio-ingressgateway.istio-system"?

**Comment by jmazzitelli** [comment]
@douglas-reid I was hoping someone in the telemetry team would be able to know the answer to this pretty quickly by just reading the problem description. I have a feeling this could be my lack of understanding of how istio-ingressgateway works internally and how it reports telemetry for this use-case. Feel free to set me straight if this isn't a bug, if that is the case. But on its face, it just seems wrong to have two timeseries resulting in this scenario, hence why I wrote this up as a bug report.

**Comment by bianpengyuan** [comment]
I am wondering do you inject sidecar to your traffic generator?

**Comment by jmazzitelli** [comment]
> I am wondering do you inject sidecar to your traffic generator?

Yes, as mentioned in the first sentence of the original description, it says,

- Sending a request to istio-ingressgateway from a pod **that has a sidecar** results in two timeseries.

In addition, in the replication procedures in the original description, see step 2 where it said:

```
2. Install Kiali's traffic generator test pod with a sidecar, ...

curl ...traffic-generator.yaml | istioctl kube-inject -f - | kubectl create ...
```

**Comment by douglas-reid** [comment]
IIUC, you have a sidecar proxy on your generator, and are routing traffic through ingressgateway.

So, you have a `reporter=source` timeseries from the source sidecar proxy (generation workload -> ingressgateway) and a `reporter=source` timeseries from the ingressgateway. The tricky bit -- and the part that looks wrong -- is that that ingressgateway is pulling the `source.` attributes in, and honoring them.

We need a clear way to signal to an ingressgateway that it is an ingress point, and should not honor the `source.*` attributes in the forwarded istio attributes header.

/cc @mandarjog

**Comment by gbaufake** [comment]
@bianpengyuan it was injected by accident on the test.

My question remains:
Can it be a valid scenario when some service (with a sidecar) on a mesh requires to connect to another service on a mesh which may be on the same or another namespace?
