### ISSUE TITLE
Need way to configure trace sampling

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio#1206]
cc: @kyessenov @louiscryan 

We should support a mechanism to control trace sampling in Istio. Right now, tracing is either 100% on or it is off.

**Comment by mandarjog** [comment]
Related to https://github.com/istio/issues/issues/100

**Comment by mandarjog** [comment]
I think it is best to sample requests one time at envoy / at the edge.

https://www.envoyproxy.io/envoy/configuration/http_conn_man/runtime.html#config-http-conn-man-runtime-random-sampling.

From then on Mixer should add spans only if the request is already traced. @douglas-reid

**Comment by douglas-reid** [comment]
@kyessenov i believe you had a recommended set of places to open issues to get this support in all the right places for the new APIs. can you list your suggestions here?

**Comment by kyessenov** [comment]
envoyproxy/data-plane-api to expose the setting away from bootstrap config (if  it's not done already) and envoy/envoy to implement the change in the api. then an issue in pilot if the repo is still going to be around.

**Comment by skydoctor** [comment]
Is there a way now to configure trace sampling?

**Comment by objectiser** [comment]
@skydoctor https://preliminary.istio.io/docs/tasks/telemetry/distributed-tracing/overview/#trace-sampling

**Comment by skydoctor** [comment]
Thanks @objectiser! From the [PR](https://github.com/istio/istio/pull/6989), this seems like a mesh-wide config, do you know if this will apply for requests coming in to the mesh via ingress-gateway? I presume yes because the envoy in ingress-gateway is also controlled by the same pilot but it is treated special in some cases so wanted to make sure.

**Comment by objectiser** [comment]
Yes the same config applies.
