### ISSUE TITLE
istioctl experimental rbac can incorrectly reports 'deny'

### ISSUE THREAD

**Issue by esnible** [istio/istio#12075]
To reproduce, I first deployed httpbin in the usual way.  Follow https://istio.io/docs/tasks/traffic-management/ingress/ or just do

```
kubectl apply -f samples/httpbin/httpbin.yaml
kubectl apply -f samples/httpbin/httpbin-gateway.yaml
```

I verified it worked: `curl -s -o /dev/null -w "%{http_code}" http://$INGRESS_HOST:31380`

I did `istioctl experimental rbac can GET httpbin /` and the response was ```
deny
```

I tried various options such as `--user default` and `--user cluster.local/ns/default/sa/default`.  I always received "deny".

The documentation shows `... GET rating /v1/health` and probably `ratings` is intended instead of `rating`.

**Comment by yangminzhu** [comment]
The `experimental rbac` is actually outdated at this point, I will try to either update it to latest or remove it for now.
/cc @liminw  @pitlv2109

**Comment by esnible** [comment]
The PR to remove this command is now https://github.com/istio/istio/pull/12238

The intention is to restore it when a new design is available.

**Comment by esnible** [comment]
The command syntax was `istioctl experimental rbac can METHOD SERVICE PATH [flags]`.

The documentation included examples https://preliminary.istio.io/docs/reference/commands/istioctl/#istioctl-experimental-rbac-can

```
# Query if user "cluster.local/ns/default/sa/productpage" is allowed to GET /v1/health of service rating.
istioctl experimental rbac can -u cluster.local/ns/default/sa/productpage GET rating /v1/health

# Query if namespace foo is allowed to POST to /data of service rating with label version=dev.
istioctl experimental rbac can -s source.namespace=foo POST rating /data -a destination.labels[version]=dev
```

@yangminzhu Is the intention for a replacement to support the same syntax?

If I do `kubectl get crds | grep -i rbac` I see five different Istio RBAC CRDs.  Which ones are we recommending for users to using in 1.1?  Can we offer docs until this command returns?

**Comment by yangminzhu** [comment]
@esnible 
The new syntax is probably going to be a little different. As for the CRD, there are some legacy old CRDs probably could be cleaned after 1.1 (we kept them for backward compatible). For 1.1, you only need `ClusterRbacConfig`, `ServiceRole` and `ServiceRoleBinding`, see https://istio.io/docs/concepts/security/#authorization-policy
