### ISSUE TITLE
Document how to run multiple validation webhooks in different namespaces

### ISSUE THREAD

**Issue by costinm** [istio/istio#12077]
Running Galley with 2 replicas - logs seem to loop every minute attempting to update.

 2019-02-26T18:36:21.614749Z	info	validation	istio-galley validatingwebhookconfiguration updated
2019-02-26T18:36:22.215182Z	info	validation	istio-galley validatingwebhookconfiguration updated
2019-02-26T18:36:22.817268Z	info	validation	istio-galley validatingwebhookconfiguration updated
2019-02-26T18:36:23.414291Z	info	validation	istio-galley validatingwebhookconfiguration updated
2019-02-26T18:36:24.014600Z	info	validation	istio-galley validatingwebhookconfiguration updated
2019-02-26T18:36:24.614843Z	info	validation	istio-galley validatingwebhookconfiguration updated
2019-02-26T18:36:25.214363Z	info	validation	istio-galley validatingwebhookconfiguration updated
2019-02-26T18:36:25.815563Z	info	validation	istio-galley validatingwebhookconfiguration updated
2019-02-26T18:36:26.418884Z	info	validation	istio-galley validatingwebhookconfiguration updated
2019-02-26T18:36:27.014805Z	info	validation	istio-galley validatingwebhookconfiguration updated
2019-02-26T18:36:27.615246Z	info	validation	istio-galley validatingwebhookconfiguration updated
2019-02-26T18:36:28.215556Z	info	validation	istio-galley validatingwebhookconfiguration updated
2019-02-26T18:36:28.814463Z	info	validation	istio-galley validatingwebhookconfiguration updated
2019-02-26T18:36:29.414740Z	info	validation	istio-galley validatingwebhookconfiguration updated
2019-02-26T18:36:30.014659Z	info	validation	istio-galley validatingwebhookconfiguration updated
2019-02-26T18:36:30.615261Z	info	validation	istio-galley validatingwebhookconfiguration updated
2019-02-26T18:36:31.219348Z	info	validation	istio-galley validatingwebhookconfiguration updated

**Comment by costinm** [comment]
I  think the problem was that I had a different namespace running control plane ( with the 'a-la-carte' installer ). So it would be a P2 for 1.1 - but we need to fix it for 1.2 where we'll switch to allowing multiple control plane environments and break into separate namespaces for security.

**Comment by costinm** [comment]
( same problem exists in Citadel - both are 'singletons', can't run instances in multiple namespaces)

**Comment by ayj** [comment]
(updated the title to reflect the nature of the issue)

> I think the problem was that I had a different namespace running control plane.

This isn't likely to work unless we ensure all of the validation command line flags are set correctly. k8s ValidatingWebhookConfiguration is cluster-scoped and points to a specific k8s service/namespace to handle the validation. A single copy of our ValidationWebhookConfiguration cannot be shared across namespaces as-is. You'd either need to elect one Galley to handle validation across all namespaces, or better isolate validation, e.g.

- replicate the configuration and change the k8s webhook names accordingly to avoid the update conflict described above.
- scope the webhook with the namespace selector so that handled namespaces don't overlap.

**Comment by duderino** [comment]
@ayj @ozevren @munrodg @costinm is this really a P0 for 1.1?  If not please drop priority or move to 1.2

**Comment by sushicw** [comment]
Where should this documentation be added? I've got most of the steps figured out (including a new galley flag to allow the webhook to be namespace scoped, see https://github.com/istio/istio/pull/15927).

**Comment by sushicw** [comment]
I'm happy to put this in a more appropriate place once I know where that is, but in the meantime, here are steps to follow. This assumes you want namespace ```istio-system-1``` managing ```default-1``` and ```istio-system-2``` managing ```default-2```

  * Create a modified istio.yaml for ```istio-system-1```:
    e.g. 
    ```
    cat install/kubernetes/istio.yaml | sed -e "s/istio-system/istio-system-1/g" > /tmp/istio-1.yaml
    ```
  * Modify ```istio-1.yaml``` to include a unique webhook name in the galley command line options, e.g. ```--webhook-name=istio-system-1-istio-galley```
  * Modify the ```kubectl get validatingwebhookconfiguration``` script line in ```istio-1.yaml``` to use the new webhook name. 
    e.g. 
    ```
    sed -ie "s/kubectl get validatingwebhookconfiguration istio-galley/kubectl get validatingwebhookconfiguration istio-system-1-istio-galley/" /tmp/istio-1.yaml
    ```
  * Modify ```istio-1.yaml``` to include ```--listened-namespaces=istio-system-1``` in the citadel command line options.
  * Modify the validatingwebhook configuration embedded in ```istio-1.yaml``` to include a namespace selector for each webhook:
    ```
    namespaceSelector:
      matchLabels:
        galley.istio.io/env: istio-system-1
    ```
  * Repeat the above for ```istio-system-2``` and ```default-2``` (creating ```istio-2.yaml```), so now you have a yaml for each istio install / control plane.
  * Create the data plane namespaces and label them. 
    ```
    kubectl create namespace default-1
    kubectl create namespace default-2
    kubectl label namespace default-1 galley.istio.io/env=istio-system-1
    kubectl label namespace default-2 galley.istio.io/env=istio-system-2
    ```
  * Apply the yamls to install istio twice.

**Comment by sushicw** [comment]
Recorded the steps to take as a doc in the config working group folder: https://goto.google.com/multi-tenant-galley-validation-webook-config

**Comment by ozevren** [comment]
I don't think this documentation will be easily accessible. Any chance we can have a section for this in istio.io website?

**Comment by costinm** [comment]
The istio/installer repo already does this for injector and galley I think
- the webhook name includes the namespace where istio runs.

The critical issue remains provisioning the DNS-based cert for the webhooks
- there are tools to do this, but it's not automated.

Note that injector, citadel, etc allow using some labels to specify which
namespaces are 'managed' by a particular instance.

I think Galley should follow the same pattern, including for validation: it
should read and validate CRs only from annotated namespaces
when operating in 'opt-in' mode ( like injector's istio-injected: true or
istio-env: foo ), and respect the opt-out when operating in full mode.

**Comment by costinm** [comment]
Reopening this since 'canary' for galley and multiple versions is still not fully resolved in installer ( or operator ).

**Comment by howardjohn** [comment]
The plan is to have validation be a singleton, so closingthis
