### ISSUE TITLE
Automate installation of multi-cluster

### ISSUE THREAD

**Issue by louiscryan** [istio/istio#12080]
**Describe the feature request**
In a world where istio has an automated installer it should be able to provision deployments that provide the variations of multi-cluster install 

https://preliminary.istio.io/docs/setup/kubernetes/multicluster-install/gateways/

In particular the installer should be able to:
- Setup one cluster as control-plane master
- Setup for control-plane replicas in each cluster
- Create gateway bridges based on users-knowledge of cluster networks
- Define network id annotations
- Have one instance act as the root-CA or integrate with a 3rd party root.

As a hypothetical user-experience imagine

istioctl install {cluster1}  # Installs control-plane in cluster1
istioctl install {cluster2} --join {cluster1}  # Install and join mesh if clusters have same L3 network
istioctl install {cluster2} --join {cluster1}  --novpn  # Install and join mesh if clusters have different L3 networks)
istioctl install {cluster2} --join {cluster1} --noctrlplane # Join a remote mesh control plane

**Describe alternatives you've considered**
None

**Additional context**

**Comment by sdake** [comment]
@louiscryan good idea.  In fact, such a good idea, I've been planning to kick something like this off for about a month - waiting for 1.1 to release.  Will provide more information on a "Gateway Control Protocol" in the next networking meeting and the environment meeting following.

Cheers
-steve

**Comment by esnible** [comment]
I would like to see this under an `istioctl mc` subcommand.

Knowing that a cluster is already set up for multicluster is also important.  I have created a document at https://docs.google.com/document/d/19mQojPz0A6W56CE9iREjSfCXjrvCf_hkU-bw5trzRpI/edit perhaps you could comment on it and we could move forward together with a proposal for how users interact with multi-cluster configuration.

**Comment by sdake** [comment]
@esnible thanks for getting that kicked off.  I've changed the scope to involve both env wg and ux workgroup as we will need expertise from both workgroups to approve the design and implement the work.

I will provide comments on the UX portion this week.

Cheers
-steve

**Comment by incfly** [comment]
To me, `istioctl install` can be generalized to mesh expansion setup. Today's mesh expansion setup is also very troublesome and error-prone.

If we go with `istioctl mc`, then we need to add another something like `istioctl expansion`.

**Comment by sdake** [comment]
@ayj is moving on this work.

This is targeted as P0 for 1.3.

**Comment by sdake** [comment]
I had a misunderstanding about what P0 is.  The current definition (and the definition we are using) is P0 blocks the release.  Features never block a release.  Still, focus should remain on this area.

Cheers
-steve
