### ISSUE TITLE
Install 1.1 (RC) with helm fails at step 5.

### ISSUE THREAD

**Issue by diemtvu** [istio/istio#12081]
**Describe the bug**
{{ 
Helm install istio command fails:

```
helm install istio --name istio --namespace istio-system
Error: failed to download "istio" (hint: running `helm repo update` may help)
```
 }}

**Expected behavior**
{{ What did you expect to happen? }}

**Steps to reproduce the bug**
{{ 
Download 1.1 RC
```
wget https://github.com/istio/istio/releases/download/1.1.0-rc.0/istio-1.1.0-rc.0-linux.tar.gz
```
Then follow installation [instruction with helm and tiller](https://preliminary.istio.io/docs/setup/kubernetes/helm-install/)
 }}

**Version**
{{ 
kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.7-gke.4", GitCommit:"618716cbb236fb7ca9cabd822b5947e298ad09f7", GitTreeState:"clean", BuildDate:"2019-02-05T19:22:29Z", GoVersion:"go1.10.7b4", Compiler:"gc", Platform:"linux/amd64"}
 }}

**Installation**
{{ Please describe how Istio was installed }}

**Environment**
{{ Which environment, cloud vendor, OS, etc are you using? }}

**Cluster state**
{{ If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue. }}

**Comment by duderino** [comment]
@ostromart can you take a look at this one when you work on https://github.com/istio/istio/issues/11951 ?

**Comment by ostromart** [comment]
Ack, will take a look.

**Comment by ostromart** [comment]
Just tried this with both rc0 and rc1 and works for me in both cases. 
@diemtvu could you provide your whole bash history in trying to install this?

**Comment by diemtvu** [comment]
I've run again on my brand new cluster, helm 2.13, no tiller
```
helm version
Client: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
Error: could not find tiller
```

Here are commands:

```
DIR='/usr/local/google/home/diemvu/Downloads/istio1.1-test'
mkdir -p $DIR/istio-fetch

helm repo add istio.io "https://gcsweb.istio.io/gcs/istio-prerelease/daily-build/release-1.1-latest-daily/charts/"

helm fetch istio.io/istio-init --untar --untardir $DIR/istio-fetch
helm fetch istio.io/istio --untar --untardir $DIR/istio-fetch

kubectl create namespace istio-system

helm template $DIR/istio-fetch/istio-init --name istio-init --namespace istio-system | kubectl apply -f -
```

Error after the last command
```
Error from server (Forbidden): error when creating "STDIN": clusterroles.rbac.authorization.k8s.io "istio-init-istio-system" is forbidden: attempt to grant extra privileges: [{[get] [] [configmaps] [] []} {[list] [] [configmaps] [] []} {[create] [] [configmaps] [] []} {[watch] [] [configmaps] [] []} {[create] [apiextensions.k8s.io] [customresourcedefinitions] [] []} {[get] [apiextensions.k8s.io] [customresourcedefinitions] [] []} {[list] [apiextensions.k8s.io] [customresourcedefinitions] [] []} {[watch] [apiextensions.k8s.io] [customresourcedefinitions] [] []} {[patch] [apiextensions.k8s.io] [customresourcedefinitions] [] []}] user=&{diemvu@google.com  [system:authenticated] map[user-assertion.cloud.google.com:[AKUJVpkORRiKsqa6vRKZQGTiA7uQt6EpcCXLbt9OpjHEMZj0boEnRJNaxl7DcvS/w37yEpfQSbliCRh31MPmj/220Dd5qPmV/82EmupK4o/1+smaBZkZPmlrONYF7uveSVarCqNe0/zb1LbfqmP0Cw9mdu7SjVYXG58rXmLsuavEp8l7tDcTsW5B6OwfgTw3aGOgw0F+MiLMa3K0XrU9AiXc4d3U6Drksg3A]]} ownerrules=[{[create] [authorization.k8s.io] [selfsubjectaccessreviews selfsubjectrulesreviews] [] []} {[get] [] [] [] [/api /api/* /apis /apis/* /healthz /openapi /openapi/* /swagger-2.0.0.pb-v1 /swagger.json /swaggerapi /swaggerapi/* /version /version/]}] ruleResolutionErrors=[]

```

**Comment by ostromart** [comment]
Ok, so you're doing option 2 (template) now rather than option 1 (tiller) as before. 
Did you run 
kc create clusterrolebinding cluster-admin-binding --clusterrole=cluster-admin --user=$(gcloud config get-value core/account)
on the cluster?
The error you're showing is usually due to that step being missed.

**Comment by diemtvu** [comment]
Whoop. I'm sorry. I forgot which one I was testing :). Will try the other one again.
One note though, I noticed my helm was pretty old (2.9), so just update it today and seems fixing few other issues (not related to this). I'll try again with option 2 and let you know.

**Comment by diemtvu** [comment]
It's still fail with Heml + Tiller. Btw, set RBAC do fix option 1. I remember that we mention this somewhere, but I think it's may be good to repeat it here again.

Anyway, the error with Helm + Tiller is the same as I saw this other day. I'm using RC1, btw.

```
helm install istio.io/istio-init --name istio-init --namespace istio-system
NAME:   istio-init
LAST DEPLOYED: Thu Feb 28 19:26:06 2019
NAMESPACE: istio-system
STATUS: DEPLOYED

RESOURCES:
==> v1/ClusterRole
NAME                     AGE
istio-init-istio-system  0s

==> v1/ClusterRoleBinding
NAME                                        AGE
istio-init-admin-role-binding-istio-system  0s

==> v1/ConfigMap
NAME                      DATA  AGE
istio-crd-10              1     0s
istio-crd-11              1     0s
istio-crd-certmanager-10  1     0s

==> v1/Job
NAME                           COMPLETIONS  DURATION  AGE
istio-init-crd-10              0/1          0s        0s
istio-init-crd-11              0/1          0s        0s
istio-init-crd-certmanager-10  0/1          0s        0s

==> v1/Pod(related)
NAME                                 READY  STATUS             RESTARTS  AGE
istio-init-crd-10-c8bd5              0/1    ContainerCreating  0         0s
istio-init-crd-11-kl2tj              0/1    ContainerCreating  0         0s
istio-init-crd-certmanager-10-z95qk  0/1    ContainerCreating  0         0s

==> v1/ServiceAccount
NAME                        SECRETS  AGE
istio-init-service-account  1        0s


diemvu@cocoa2:~/Downloads/istio1.1-test/istio-1.1.0-rc.1 $  kubectl get crds | grep 'istio.io\|certmanager.k8s.io' | wc -l
56
diemvu@cocoa2:~/Downloads/istio1.1-test/istio-1.1.0-rc.1 $ helm install istio --name istio --namespace istio-system
Error: failed to download "istio" (hint: running `helm repo update` may help)
diemvu@cocoa2:~/Downloads/istio1.1-test/istio-1.1.0-rc.1 $ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "istio.io" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈ 
diemvu@cocoa2:~/Downloads/istio1.1-test/istio-1.1.0-rc.1 $ helm install istio --name istio --namespace istio-system
Error: failed to download "istio" (hint: running `helm repo update` may help)
```

**Comment by sdake** [comment]
step 5 in the preliminary docs is incorrect.

try `helm install istio.io/istio --name istio --namespace istio-system`

Cheers
-steve

**Comment by sdake** [comment]
> Ok, so you're doing option 2 (template) now rather than option 1 (tiller) as before.
> Did you run
> kc create clusterrolebinding cluster-admin-binding --clusterrole=cluster-admin --user=$(gcloud config get-value core/account)
> on the cluster?
> The error you're showing is usually due to that step being missed.

Why would this step be needed?

What does it do?

Cheers
-steve

**Comment by ostromart** [comment]
@sdake that step is needed for RBAC, otherwise things like adding roles fails, see
https://preliminary.istio.io/docs/setup/kubernetes/platform-setup/gke/
step 3.

**Comment by sdake** [comment]
@ostromart got it - so a GKE specific thing - sounds fair.

Cheers
--steve
