### ISSUE TITLE
Move Ingress (status) controller from Pilot to Galley

### ISSUE THREAD

**Issue by ozevren** [istio/istio#12083]
Pilot has an K8s ingress controller that listens and updates status of the Ingress resource. As part of making Pilot less dependent on K8s, we should move it to Galley.

**Comment by Nino-K** [comment]
@ozevren are you working on this, if not I would like to help with this one.

**Comment by ozevren** [comment]
Hey @Nino-K sorry, I missed the tag. I am currently not working on it, feel free to grab it. Thanks!

**Comment by sushicw** [comment]
@Nino-K are you still working on this?

**Comment by ozevren** [comment]
@Nino-K are you still on this?

**Comment by Nino-K** [comment]
No I have not done any work on this, as I got involved in other works with higher priority. Feel free to unassigned me.

**Comment by ayj** [comment]
@utako, were you still planning to work on this?

**Comment by utako** [comment]
@ayj, yes! I'm starting out by fitting the existing Pilot status controller into the pattern in the Galley server. were people in the config wg hoping for a full rewrite? were there problems

**Comment by howardjohn** [comment]
Given Istiod movement I don't think this is required
