### ISSUE TITLE
istioctl proxy-config bootstrap '--output' not respected

### ISSUE THREAD

**Issue by esnible** [istio/istio#12082]
The `--output short` feature of istioctl proxy-config only has been implemented for cluster/endpoint/listener/route but is shown on the documentation as applying to `bootstrap`.

It should be moved, or bootstrap should offer a short version.

To reproduce:
```
POD=$(kubectl get pod --selector app=httpbin --output jsonpath='{.items..metadata.name}')
istioctl proxy-config bootstrap $POD --output short
```

(output is still JSON)

**Comment by liamawhite** [comment]
It's not entirely clear what we would put in a summary output, this is why it was never implemented. Any suggestions on a format?

**Comment by esnible** [comment]
If we choose to fix this by creating a short version, instead of just removing the argument,

Just show the value of ISTIO_VERSION and buildVersion:

```
Istio Version            Envoy Version
1.1.0-rc.0                fc273e117a6ed875c7cb9b3c3251c8d982bc7196/1.10.0-dev/Clean/RELEASE/BoringSSL
```

I often want to know which version of the sidecar is running.
