### ISSUE TITLE
Documentation for multi-cluster via Gateway install is broken

### ISSUE THREAD

**Issue by louiscryan** [istio/istio#12087]
**Describe the bug**
Documentation for 
https://preliminary.istio.io/docs/setup/kubernetes/multicluster-install/gateways/
is out-of-date

**Expected behavior**
Should be able to setup 

**Steps to reproduce the bug**
Follow instructions and the following issues are found...

- Install instructions vary from the 'helm template' install docs. Would be better just to reference them
- Commands to 'Setup DNS' do not work. They presume the existence of 'istiocoredns' service which does not exist if the install instructions are followed. This is true for both kubedns and coredns variations

The page should probably also come with a warning about the stability of this feature, which is Alpha IIRC.

**Version**
1.13

**Environment**
Running on Kind but this seems irrelevant

**Cluster state**

**Comment by duderino** [comment]
P0 for the stability warning.  Actually making it work is a P1

**Comment by duderino** [comment]
@howardjohn can take this

**Comment by rshriram** [comment]
So per @louiscryan it worked. He had missed one step in the install steps..

**Comment by howardjohn** [comment]
Updated docs to be more clear about install: https://github.com/istio/istio.io/pull/3418
