### ISSUE TITLE
Create Istio 1.0.8

### ISSUE THREAD

**Issue by duderino** [istio/istio#12090]
**Describe the feature request**

1.0.7 must have https://github.com/istio/istio/pull/12030 and it should be the release manager's discretion whether it contains anything other than that.  Ideally not since we don't have the bandwidth to go through a full qualification cycle with release 1.1 demanding so much attention.

CC: @Stono @costinm @howardjohn

**Comment by duderino** [comment]
Reopening.  Istio 1.0.7 was created for an emergency security fix, but the PRs referenced by this issue still need to go out in a 1.0.8 release

**Comment by duderino** [comment]
OK, https://github.com/istio/istio/pull/12766/ from the 1.1 branch is the PR that actually fixed the issue.   https://github.com/istio/istio/pull/12030 has been abandoned.

So... if we ever create a 1.0.8 release, it would be good to backport https://github.com/istio/istio/pull/12766/ to the 1.0 branch

**Comment by duderino** [comment]
Dropping to P2 since the original requestor, @Stono, has moved onto 1.1.x which has the fix

**Comment by howardjohn** [comment]
I don't think is relevant anymore, 1.0.x is near end of life and the fix in 1.1.x can not be directly backport (code has changed substantially)
