### ISSUE TITLE
preliminary 1.1 doc for Multicluster Google Kubernetes Engine fails

### ISSUE THREAD

**Issue by lei-tang** [istio/istio#12097]
{{
https://preliminary.istio.io/docs/examples/multicluster/gke/

Follow the instruction in the section "Create the GKE Clusters", failed with "ERROR: (gcloud.container.clusters.create) unrecognized arguments".

~$ gcloud container clusters create $cluster --zone $zone --username "admin" \
  --cluster-version "1.9.6-gke.1" --machine-type "n1-standard-2" --image-type "COS" --disk-size "100" \
  --scopes "https://www.googleapis.com/auth/compute","https://www.googleapis.com/auth/devstorage.read_only",\
  "https://www.googleapis.com/auth/logging.write","https://www.googleapis.com/auth/monitoring",\
  "https://www.googleapis.com/auth/servicecontrol","https://www.googleapis.com/auth/service.management.readonly",\
  "https://www.googleapis.com/auth/trace.append" \
  --num-nodes "4" --network "default" --enable-cloud-logging --enable-cloud-monitoring --enable-ip-alias --async
ERROR: (gcloud.container.clusters.create) unrecognized arguments:
  https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring,
  https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,
  https://www.googleapis.com/auth/trace.append
  To search the help text of gcloud commands, run:
  gcloud help -- SEARCH_TERMS

**Expected behavior**
{{
Creating clusters should succeed
}}

**Steps to reproduce the bug**
{{
https://preliminary.istio.io/docs/examples/multicluster/gke/,
create a cluster in the section "Create the GKE Clusters".
}}

**Version**
{{
istio-release-1.1-20190226-09-16
}}

**Installation**
{{
Follow "Before you begin"
}}

**Environment**
{{
~$ gcloud version
Google Cloud SDK 236.0.0
alpha 2019.02.22
app-engine-java 1.9.72
app-engine-python 1.9.83
beta 2019.02.22
bq 2.0.41
cloud-datastore-emulator 2.1.0
core 2019.02.22
gsutil 4.36
}}

**Cluster state**
{{ N/A }}

**Comment by incfly** [comment]
is your env var set? `cluster, zone` stuff? I doubt they're empty.

**Comment by lei-tang** [comment]
Env var are set based on the instructions in: https://preliminary.istio.io/docs/examples/multicluster/gke/

~$ echo $cluster
cluster-1
~$ echo $zone
us-east1-b

**Comment by incfly** [comment]
The scope argument is not properly splitted and make bash think it's a separate argument. This will work.

```
gcloud container clusters create $cluster --zone $zone --username "admin" \
  --cluster-version "1.9.6-gke.1" --machine-type "n1-standard-2" --image-type "COS" --disk-size "100" \
  --scopes scope="https://www.googleapis.com/auth/compute","https://www.googleapis.com/auth/devstorage.read_only",\
"https://www.googleapis.com/auth/logging.write","https://www.googleapis.com/auth/monitoring",\
"https://www.googleapis.com/auth/servicecontrol","https://www.googleapis.com/auth/service.management.readonly",\
"https://www.googleapis.com/auth/trace.append" --num-nodes "4" --network "default" --enable-cloud-logging --enable-cloud-monitoring --enable-ip-alias --async
```

**Comment by incfly** [comment]
Could you help to send a PR to update this? @lei-tang  I can review it, thanks!

**Comment by lei-tang** [comment]
~$ gcloud container clusters create $cluster --zone $zone --username "admin" \
  --cluster-version "1.9.6-gke.1" --machine-type "n1-standard-2" --image-type "COS" --disk-size "100" \
  --scopes scope="https://www.googleapis.com/auth/compute","https://www.googleapis.com/auth/devstorage.read_only",\
"https://www.googleapis.com/auth/logging.write","https://www.googleapis.com/auth/monitoring",\
"https://www.googleapis.com/auth/servicecontrol","https://www.googleapis.com/auth/service.management.readonly",\
"https://www.googleapis.com/auth/trace.append" --num-nodes "4" --network "default" --enable-cloud-logging --enable-cloud-monitoring --enable-ip-alias --async
WARNING: Starting in 1.12, new clusters will not have a client certificate issued. You can manually enable (or disable) the issuance of the client certificate using the `--[no-]issue-client-
certificate` flag.
WARNING: Starting in 1.12, default node pools in new clusters will have their legacy Compute Engine instance metadata endpoints disabled by default. To create a cluster with legacy instance
metadata endpoints disabled in the default node pool, run `clusters create` with the flag `--metadata disable-legacy-endpoints=true`.
This will enable the autorepair feature for nodes. Please see https://cloud.google.com/kubernetes-engine/docs/node-auto-repair for more information on node autorepairs.
WARNING: Starting in Kubernetes v1.10, new clusters will no longer get compute-rw and storage-ro scopes added to what is specified in --scopes (though the latter will remain included in the
default --scopes). To use these scopes, add them explicitly to --scopes. To use the new behavior, set container/new_scopes_behavior property (gcloud config set container/new_scopes_behavior
true).
ERROR: (gcloud.container.clusters.create) ResponseError: code=400, message=Master version "1.9.6-gke.1" is unsupported.

**Comment by lei-tang** [comment]
After changing the gke version from "1.9.6-gke.1" to "1.11.7-gke.4", the unsupported version error is gone but there is other errors:

~$ gcloud container clusters create $cluster --zone $zone --username "admin"   --cluster-version "1.11.7-gke.4" --machine-type "n1-standard-2" --image-type "COS" --disk-size "100"   --scopes
 scope="https://www.googleapis.com/auth/compute","https://www.googleapis.com/auth/devstorage.read_only","https://www.googleapis.com/auth/logging.write","https://www.googleapis.com/auth/monit
oring","https://www.googleapis.com/auth/servicecontrol","https://www.googleapis.com/auth/service.management.readonly","https://www.googleapis.com/auth/trace.append" --num-nodes "4" --network
 "default" --enable-cloud-logging --enable-cloud-monitoring --enable-ip-alias --async
WARNING: Starting in 1.12, new clusters will not have a client certificate issued. You can manually enable (or disable) the issuance of the client certificate using the `--[no-]issue-client-
certificate` flag.                                                         
WARNING: Starting in 1.12, default node pools in new clusters will have their legacy Compute Engine instance metadata endpoints disabled by default. To create a cluster with legacy instance
metadata endpoints disabled in the default node pool, run `clusters create` with the flag `--metadata disable-legacy-endpoints=true`.
This will enable the autorepair feature for nodes. Please see https://cloud.google.com/kubernetes-engine/docs/node-auto-repair for more information on node autorepairs.
WARNING: Starting in Kubernetes v1.10, new clusters will no longer get compute-rw and storage-ro scopes added to what is specified in --scopes (though the latter will remain included in the
default --scopes). To use these scopes, add them explicitly to --scopes. To use the new behavior, set container/new_scopes_behavior property (gcloud config set container/new_scopes_behavior
true).                                                                                                          
ERROR: (gcloud.container.clusters.create) ResponseError: code=400, message=Scope does not exist: scope=https://www.googleapis.com/auth/compute.

**Comment by ymesika** [comment]
Instructions aren't updated.
Specifically for [creating the `istio-remote`](https://preliminary.istio.io/docs/examples/multicluster/gke/#generate-remote-cluster-manifest) we no longer have `istio-remote` chart/dir.
I will subit a PR for that.

**Comment by lei-tang** [comment]
The fix for this issue is at: https://github.com/istio/istio.io/pull/3415

**Comment by ymesika** [comment]
Additional doc fix: https://github.com/istio/istio.io/pull/3407
