### ISSUE TITLE
Flakey test: codecov

### ISSUE THREAD

**Issue by GregHanson** [istio/istio#12094]
**Describe the bug**
https://circleci.com/gh/istio/istio/338465?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

test fails due to timeout installing golang tooling:
```
/go/out/codecov/pr /go/src/istio.io/istio
package golang.org/x/tools/cover: unrecognized import path "golang.org/x/tools/cover" (https fetch: Get https://golang.org/x/tools/cover?go-get=1: dial tcp 172.217.164.145:443: connect: connection refused)
```

**Comment by utka** [comment]
codecov is definitely flaky, but mostly because of https://github.com/istio/istio/issues/12316
Closing this one, reopen if see it again.
