### ISSUE TITLE
Spiffe identities are generated from pods without ServiceAccounts (in kube-system)

### ISSUE THREAD

**Issue by morvencao** [istio/istio#12108]
**Describe the bug**
After install istio-1.1.0-snapshot.6, and deploy applications with istio, find lots of error message in pilot discovery container:
```
2019-02-27T00:58:27.161235Z info    ads     Push debounce stable[174] 1: 100.139211ms since last change, 100.139211ms since last push, full=true
2019-02-27T00:58:27.450424Z error namespace or service account can't be empty ns=kube-system serviceaccount=
2019-02-27T00:58:27.521175Z error namespace or service account can't be empty ns=kube-system serviceaccount=
2019-02-27T00:58:27.715277Z error namespace or service account can't be empty ns=kube-system serviceaccount=
2019-02-27T00:58:27.957708Z error namespace or service account can't be empty ns=kube-system serviceaccount=
```

These error messages should be generated during converting k8s serviceaccount to istio serviceaccount(in spiffe format). 
Why pilot can't get `serviceaccount` for pod while getting namespace is normal?

**Expected behavior**
No error messages

**Version**
istio-1.1.0-snapshot.6
```
[root@master istio-1.1.0-snapshot.6]# ./bin/istioctl version
version.BuildInfo{Version:"1.1.0-snapshot.6", GitRevision:"14777199b85ba56ebca2a4516afff33c97199eb4", User:"root", Host:"f0f1db73-2fb5-11e9-86e9-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-snapshot.5-156-g1477719"}
[root@master istio-1.1.0-snapshot.6]# kubectl version
Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2018-10-10T16:38:01Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-02-08T23:07:29Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

{{ Which environment, cloud vendor, OS, etc are you using? }}
openshift
redhat

**Cluster state**
{{ If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue. }}

**Comment by morvencao** [comment]
Latest investigation result show that there are some static pods(api-server, etcd, controller-manager and scheduler...) in `kube-system` namespace, and they don’t have `ServiceAccountName` in their Spec.

And for `api-server` service, Istio has build-in [destinationrule](https://github.com/istio/istio/blob/release-1.1/install/kubernetes/helm/istio/charts/security/templates/enable-mesh-mtls.yaml#L44-L62) to define `non-mTLS` when access `api-server`.

This should not be a critical issue. Just wondering if we can skip some static pods when generating the spiffe. Or can we change the log level from `error` to `warning`...

**Comment by howardjohn** [comment]
Do we even want to just drop it to `warning`? If there is no problem with having no serviceaccount, as some of the kube-system pods don't, then is there any reason to even log it at all? It seems to work just fine with a uri like `spiffe://cluster.local/ns/kube-system/sa/`

**Comment by myidpt** [comment]
I don't think "spiffe://cluster.local/ns/kube-system/sa/" is a valid identity. We should avoid it. The correct behavior is not generating the certs for these pods.

**Comment by myidpt** [comment]
Thank you for investigating this, @morvencao 
Is it true that only some of the pods in k8s control plane don't have the service accounts? Is it possible for a user to deploy a pod without service account?

**Comment by howardjohn** [comment]
As far as I know, you cannot deploy a pod without a SA: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#use-the-default-service-account-to-access-the-api-server A default one will be assigned. I have also verified that there are some pods without a SA in kube-system, though. On GKE I don't think this is the case, but running in [kind](https://kind.sigs.k8s.io) (and probably minikube, etc), api-server has no service account.

**Comment by myidpt** [comment]
Thank you, @howardjohn 
Since Istio is not used to manage the traffic for kube-system, I think it's fine to not generate SPIFFE identities / certs for the pods not having service accounts, right?

**Comment by morvencao** [comment]
Some static pods(api-server, etcd, controller-manager and scheduler...) in `kube-system` namespace, don’t have ServiceAccountName, and they are not user deployed pods.

**Comment by duderino** [comment]
I think this is a good one for a post 1.1 patch release

**Comment by howardjohn** [comment]
@duderino sounds good. https://github.com/istio/istio/pull/12239/files just drops the log level down as a short term improvement until a real fix is developed. That could also be in 1.1.1 though, up to you

**Comment by morvencao** [comment]
agreed, move this to post 1.1.

**Comment by howardjohn** [comment]
Fix to not log an error is merged in. I am going to pass this over to the security side to decide if we should not generate spiffee identities, etc for pods without service accounts.
