### ISSUE TITLE
Pods of one app from two clusters are registered in one pilot service entry

### ISSUE THREAD

**Issue by xiaozhongliu** [istio/istio#12112]
**Describe the bug**
We've successfully deployed the Single control plane topology with two clusters.
Some of our apps are deployed simultaneously in these clusters, this results in this problem:
Pods of one app from two clusters are registered in one pilot service entry as below.
```json
  {
   "service-key": "k8s-demo.stage.svc.cluster.local|http",
   "hosts": [
    {
     "ip_address": "172.20.2.187",
     "port": 7001
    },
    {
     "ip_address": "172.20.2.189",
     "port": 7001
    },
    {
     "ip_address": "172.22.1.164",
     "port": 7001
    },
    {
     "ip_address": "172.22.2.60",
     "port": 7001
    }
   ]
  }
```

**Expected behavior**
Pods of one app from two clusters are registered in different pilot services entries.

**Steps to reproduce the bug**
Deploy an app simultaneously in two clusters, visit the k8s service of the app from an injected pod.

**Version**
```shell
➜  ~ istioctl version
Version: 1.0.5
GitRevision: c1707e45e71c75d74bf3a5dec8c7086f32f32fad
User: root@6f6ea1061f2b
Hub: docker.io/istio
GolangVersion: go1.10.4
BuildStatus: Clean
➜  ~ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T22:29:25Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Installation**
Alibaba Cloud -> Istio helm chart

**Environment**
Alibaba Cloud

**Cluster state**
No need to provide

**Comment by xiaozhongliu** [comment]
I tried to differentiate the service-key with k8s service port name, like:
port name of app svc from cluster1: http-cluster1
port name of app svc from cluster2: http-cluster2

Then only one pilot service entry is created:
```json
  {
   "service-key": "k8s-demo.stage.svc.cluster.local|http-cluster1",
   "hosts": [
    {
     "ip_address": "172.20.2.187",
     "port": 7001
    },
    {
     "ip_address": "172.20.2.189",
     "port": 7001
    }
   ]
  }
```

**Comment by hzxuzhonghu** [comment]
>Pods of one app from two clusters are registered in one pilot service entry as below, only half requests on the service are successful.

I see your two clusters are not of flat network.
I think this is expected, app from cluster one can not request the other cluster pod directly.

**Comment by hzxuzhonghu** [comment]
`MeshNetworks` may help

**Comment by hzxuzhonghu** [comment]
> I tried to differentiate the service-key with k8s service port name, like:
port name of app svc from cluster1: http-cluster1
port name of app svc from cluster2: http-cluster2

Then only one pilot service entry is created

This is also expected, if services from 2 clusters with same name, istio assumes they are one same service. So the service port from the first cluster will be used.

**Comment by ymesika** [comment]
@hzxuzhonghu the Istio version is 1.0.5 which doesn't have the Split Horizon feature.

@xiaolanz This is normal that you see endpoints from both clusters as the instances of the same service. This is because then Envoy can (by default) round robin between local and remote endpoints.
Your issue is that in cases when the remote endpoints (IPs) are picked up it fails to connect to.

This can either be that the endpoints on your cluster2 are not accessible from cluster1 or, if you have auth on, Citadels on both clusters aren't sharing the same root CA.
If there is no flat network between the two clusters then we have solutions for this in v1.1 that redirects traffic through gateways instead of directly.

**Comment by xiaozhongliu** [comment]
> This is also expected, if services from 2 clusters with same name, istio assumes they are one same service. So the service port from the first cluster will be used.
@hzxuzhonghu So two k8s services with the same name forms one istio service, I see istio generates multi internal services for multi ports of one same k8s service. These situations are all normal, right?

**Comment by xiaozhongliu** [comment]
@ymesika Actually we have the flat network ready. My latest test result is as below, that all four pods are accessible via the istio service.
![1](https://user-images.githubusercontent.com/17674404/53547868-216f6a00-3b6b-11e9-8bea-0d8192de1e0b.png)
![image](https://user-images.githubusercontent.com/17674404/53547892-2c29ff00-3b6b-11e9-8a67-8d4ab6cd1501.png)

**Comment by hzxuzhonghu** [comment]
>So two k8s services with the same name forms one istio service, I see istio generates multi internal services for multi ports of one same k8s service

 I am not sure what do you mean by this ` internal services `

**Comment by hzxuzhonghu** [comment]
>Pods of one app from two clusters are registered in different istio services

I think they belong to a same service as showed in above graph

**Comment by xiaozhongliu** [comment]
> I am not sure what do you mean by this `internal services`

I mean istio services got with {pilot}:8080/v1/registration

> I think they belong to a same service as showed in above graph.

This is the current situation, that services with same name are merged. It's not what we expect.
We expect that requests are routed to pods from local cluster.

**Comment by hzxuzhonghu** [comment]
> We expect that requests are routed to pods from local cluster

So I think locality based LB feature may satisfy you.

**Comment by xiaozhongliu** [comment]
> So I think locality based LB feature may satisfy you.

It produces more complexity. We want it getting done with a ready made option. Does istio have this option to disable services merging?
If not, we might distinguish services by adding a postfix to the namespaces, as the last choice.

**Comment by hzxuzhonghu** [comment]
No, pilot higher level does not care about cluster. Also one cluster may across many regions., so route to instances in same cluster is not reasonable.

**Comment by xiaozhongliu** [comment]
we solved this by distinguish namespaces.
