### ISSUE TITLE
Istio Documentation without Kubernetes

### ISSUE THREAD

**Issue by Onewaysidewalks** [istio/istio#12126]
**Describe the feature request**
Documentation to run the suite of Istio components in an environment that doesn't use a container orchestrator (like k8s)

Is this still supported? (note the text about `Platform Independence` but lack of documentation other than anything running in k8s/consul)

**Comment by DinoChiesa** [comment]
It seems like people still want the information.  Shouldn't be considered stale just because no one has responded. The desire is still there.

**Comment by sdake** [comment]
@DinoChiesa our stalebot is a little to aggressive in my opinion :) .  To unstale an item, please leave a comment and the stalebot will remove the stale label.

**Comment by sdake** [comment]
@irisdingbj note I assigned this to you for nebulous future (IOW not 1.3).

**Comment by scalp42** [comment]
It's still something desired @Onewaysidewalks @sdake

**Comment by nickb937** [comment]
It is something that I would have liked to see.  The very question was posed at work today: can Istio and Envoy be used without Kubernetes whilst a transition from traditional VMs and hosting to a Kubernetes managed system is considered.  We can clearly identify a benefit from using Istio but are not ready to migrate the whole fleet to K8s just to reap the benefits.

**Comment by zengqi826** [comment]
i also want to know how to deploy istio without k8s

**Comment by arganzheng** [comment]
i also want to know how to deploy istio without k8s. +1.

**Comment by emwalker** [comment]
I'm getting the sense that Istio has aspirations to be platform-independent, but this dimension hasn't been prioritized yet, and so people are kind of on their own at this point.
