### ISSUE TITLE
Redis client can't connect to server when sidecar is injected on both sides

### ISSUE THREAD

**Issue by incfly** [istio/istio#12139]
**Describe the bug**
Redis client can't talk to redis server when sidecar is injected on client side.

**Expected behavior**
Client side should be able to talk to server.

**Steps to reproduce the bug**
- Install Istio, enable sidecar auto inject.
- Remove `MeshPolicy default` to exclude mTLS effect
``` bash
kubectl delete meshpolicy default
```
- Apply redis [YAML file](https://gist.githubusercontent.com/incfly/6ffa1381d7f3f971001a4490307ca047/raw/659522e17d7e4adb469a5606dfe684df390d3a40/istio-redis.yaml)
```
kubectl apply -f https://gist.githubusercontent.com/incfly/6ffa1381d7f3f971001a4490307ca047/raw/659522e17d7e4adb469a5606dfe684df390d3a40/istio-redis.yaml
```
- Exec into the redis-cli container and try to connect to server
```bash
$ kubectl get po -owide
# look at the redis-cart pod, and find the ip, say it's 10.0.0.1
$ kubectl exec -it redis-cli-test  -- bash
$ redis-cli -h 10.0.0.1
> PING
PONG
```
This will succeed. Because we annotate the `redis-cli-test` pod to disable sidecar injection (look at the github gist yaml file) `    sidecar.istio.io/inject: "false"`.

- Download the YAML file, remove the annotation, redeploy. Repeat the same command to login into the redis-cli-test container.  `PING` command line will fail.

**Version**
I use 1.1-snapshot6.

**Installation**
I installed with mesh expansion enabled helm flag, but I don't think that matters. If anyone can reproduce it with the default istio config, that's great enough.

**Environment**
GKE.

**Comment by howardjohn** [comment]
Testing on 1.1 rc1 with default settings and it works with our without sidecar

**Comment by davidebbo** [comment]
@howardjohn did you trying reproing the issue by installing the Hipster app sample (https://github.com/GoogleCloudPlatform/microservices-demo)? It consistently works on 1.0 for me, and breaks on 1.1rc (with proxies enabled).

**Comment by howardjohn** [comment]
Yes, Hipster breaks for me on 1.1. But I can still access redis-cart with my own service, so it's not that straightforward. See https://github.com/GoogleCloudPlatform/microservices-demo/issues/162 (on phone so not sure how to link to my comment)

**Comment by davidebbo** [comment]
Got it. Any thought on how we can take the next step here? We seem to be sort of stuck in a place where Istio folks feel cartservice may be at fault, and Hipster app folks think it's likely an Istio issue. :)

**Comment by howardjohn** [comment]
To be more clear, I don't think it is not an Istio issue - given cartservice works without Istio and with Istio 1.0, I think Istio 1.1 certainly is involved in it not working. All I am suggesting is that it is not as straight forward as "Redis does not work under Istio 1.1". I briefly looked at cartservice's code and it seems like pretty standard Redis connection, so I am not sure why it is getting errors but `redis-cli` works. Isolating where the connection issue is happening so we can identify where the bug is should be the next steps. I have been looking into it a bit but haven't had much success with it yet.

**Comment by incfly** [comment]
More digging with @howardjohn 

- We find the redis-cli is able to do more than `PING/PONG` command to redis server. And `sudo tcpdump port 6379` on both sides indicate the packet go thru client and server side as expected.
- I can't observe such packet log for `cartservice` yet.

Next step I feel we can look at envoy access log (or stats) and do a diff comparison.

**Comment by incfly** [comment]
Changed server side `redis-cart.yaml` service port name from "redis" to "tcp" get cartservice back to work again. So it sounds like a client libraries & envoy redis not working together issue...

**Comment by howardjohn** [comment]
I can confirm that renaming the service port name (or deleting it) fixed this for me. https://istio.io/docs/setup/kubernetes/spec-requirements/

Redis filter doesn't seem new at all https://github.com/istio/istio/search?q=redis&type=Commits but this change is new in 1.1 https://github.com/istio/istio/commit/2205d021b1691a069828ad0f97b84806326e021f.

**Comment by rshriram** [comment]
What happens if you disable sidecar on server side, but allow on client side? Does that work? 
@venilnoronha , we should disable the redis filter (yet again) for a good measure

**Comment by rshriram** [comment]
fixed

**Comment by incfly** [comment]
Thanks @rshriram and @venilnoronha for the quick fix!

The fixing PR seems to disable the redis proxy filter on Envoy, which I believe is the safe thing to do. However, I think there's still something we need to further investigate if it's Envoy redis filter implementation is incompatible with some client libraries or not. Right?

Do you want us to file separate issue to track that? @rshriram
