### ISSUE TITLE
Failed to change mixer component logging output level 

### ISSUE THREAD

**Issue by patrickppeng** [istio/istio#12133]
I'd like to change the logging output level on pilot and mixer and here is the example with failure. What is the correct method to change the logging level? Is it possible to change the level on a running container?

[root@vf-zr647 istio-1.0.6]# kubectl exec -ti istio-telemetry-8499b4db64-l9rx6 -c mixer -- mixs server --log_output_level attributes:debug,adapters:debug
Mixer started with
MaxMessageSize: 1048576
MaxConcurrentStreams: 1024
APIWorkerPoolSize: 1024
AdapterWorkerPoolSize: 1024
APIPort: 9091
APIAddress: 
MonitoringPort: 9093
EnableProfiling: true
SingleThreaded: false
NumCheckCacheEntries: 1500000
ConfigStoreURL: 
ConfigDefaultNamespace: istio-system
LoggingOptions: log.Options{OutputPaths:[]string{"stdout"}, ErrorOutputPaths:[]string{"stderr"}, RotateOutputPath:"", RotationMaxSize:104857600, RotationMaxAge:30, RotationMaxBackups:1000, JSONEncoding:false, LogGrpc:true, outputLevels:"attributes:debug,adapters:debug", logCallers:"", stackTraceLevels:"default:none"}
TracingOptions: tracing.Options{ZipkinURL:"", JaegerURL:"", LogTraceSpans:false}
IntrospectionOptions: ctrlz.Options{Port:0x2694, Address:"127.0.0.1"}

Unable to initialize Mixer: unable to listen: listen tcp :9091: bind: address already in use
command terminated with exit code 255
[root@vf-zr647 istio-1.0.6]#

**Comment by esnible** [comment]
Try `kubectl -n istio-system edit deployment istio-telemetry` and go to the `- args:` section and add

```
        - --log_output_level=attributes:debug,adapters:debug
```

**Comment by kyessenov** [comment]
There is Logging Scopes topic in ctrlz interface 127.0.0.1:9876

**Comment by patrickppeng** [comment]
> Try kubectl -n istio-system edit deployment istio-telemetry and go to the - args: section and add
>         - --log_output_level=attributes:debug,adapters:debug
> 
> Kubernetes should restart the istio-telemetry pod with the additional argument.

Thanks Ed. 
I works from modifying the deployment.
Does that mean we cannot use commands to change the logging configurations on the components?

**Comment by patrickppeng** [comment]
> There is Logging Scopes topic in ctrlz interface 127.0.0.1:9876

Thanks for the information. Unfortunately we don't have local browser to open ctrlz with port forwarding. Is there any other way I can access to the ctrlz interface?

**Comment by kyessenov** [comment]
You can use kubectl port-forward to the pod. There's probably some URL to apply changes without a browser, but I can't recall it ATM.
