### ISSUE TITLE
Envoy sidecar must run as istio-proxy with UID 1337

### ISSUE THREAD

**Issue by morvencao** [istio/istio#12147]
Currently Envoy Sidecar Proxy MUST run as `istio-proxy` with UID `1337`.
Any special consideration for this? 

I have changed UID from 1337 to others and rebuild the images, seems that Istio is working fine. 
Maybe we can make the UID configurable.

**Comment by kyessenov** [comment]
The UID is completely arbitrary. We chose it back in the days since it seemed like unlikely to collide with anything.
Regarding configuration: there is a risk that 1337 is hard-coded in some script/code around injection, iptables, and start-up of envoy.

**Comment by morvencao** [comment]
Thanks @kyessenov 
The UID is spread everywhere across the source tree, it's not an easy job to concentrate the configuration.
