### ISSUE TITLE
Version number shows wrong after building from code

### ISSUE THREAD

**Issue by shuiqing05** [istio/istio#12146]
**Describe the bug**
Clone from git hub, then checkout to the "1.0.6" tag. Building istio from source code, use "istioctl version" to check the version num. The number shows a commit number.
Do I miss any step in building the binary file?
The version info is as below:
root@2494927b4666:/go/out/linux_amd64/release# ./istioctl version
Version: 98598f88f6ee9c1e6b3f03b652d8e0e3cd114fa2
GitRevision: 98598f88f6ee9c1e6b3f03b652d8e0e3cd114fa2
User: root@2494927b4666
Hub: docker.io/istio
GolangVersion: go1.9.7
BuildStatus: Clean

**Expected behavior**
The number should be "1.0.6"

**Steps to reproduce the bug**
1. git clone from git hub
2. git checkout 1.0.6
3. make build
4. "istioctl version" to check the version

**Version**
Version: 1.0.6

**Comment by esnible** [comment]
@shuiqing05 The _istioctl_ version is baked into the binary. The script _bin/get_workspace_status.sh_ uses the environment variables `VERSION` and `BUILD_GIT_REVISION` to create some flags, then _bin/gobuild.sh_ uses the `-ldflags` to bake them in.

The folks doing Homebrew installs of _istioctl_ (see https://github.com/istio/istio/issues/10484 ) via a recipe are using this.  What is your use case for installing from source and needing a particular value to appear?

**Comment by shuiqing05** [comment]
> @shuiqing05 The _istioctl_ version is baked into the binary. The script _bin/get_workspace_status.sh_ uses the environment variables `VERSION` and `BUILD_GIT_REVISION` to create some flags, then _bin/gobuild.sh_ uses the `-ldflags` to bake them in.
> 
> The folks doing Homebrew installs of _istioctl_ (see #10484 ) via a recipe are using this. What is your use case for installing from source and needing a particular value to appear?

Thanks, I had fixed it. This issue can be closed.
