### ISSUE TITLE
Empty collection config for mcp client

### ISSUE THREAD

**Issue by irisdingbj** [istio/istio#12152]
When no collections are defined for the mcp client, the client will be blocked in "stream.Recv()" with no message given to user.  

So I think we can at least print error message to user about this wrong config  like "The sink has not been configured to receive any collection"

Not sure whether we need to stop/cancel the client or not in this case.

@ozevren @ayj  any Comments for this?

**Comment by esnible** [comment]
Please add a description of how to reproduce this issue.

**Comment by ozevren** [comment]
This sounds like a simple precondition check to make sure the client is asking for at least one collection.

**Comment by ayj** [comment]
Agreed with @ozevren. We should be able to catch this when the client is created. `sink.NewClient` doesn't return an error today. One option would be to panic. Another would be to return an error from that function.

**Comment by irisdingbj** [comment]
Thanks @ozevren @ayj  I will add return error for this function and print out this error message to user.
