### ISSUE TITLE
kubernetes-api only accessible via FQDN "kubernetes.default.svc.cluster.local" in 1.1.0-rc.0+

### ISSUE THREAD

**Issue by thomschke** [istio/istio#12157]
**Describe the bug**
Since `1.1.0-rc.0` the kubernetes-api
- is only accessible via `kubernetes.default.svc.cluster.local` and 
- no more via `kubernetes.default.svc` or via corresponding `Cluster-IP`.

It's caused by an additional `filterChainMatch` in the listeners config of every sidecar-proxy:
```
"filterChainMatch": {
    "serverNames": [
        "kubernetes.default.svc.cluster.local"
    ]
}
```
**Expected behavior**
- The [official k8s docu](https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/#accessing-the-api-from-a-pod) recommends `kubernetes.default.svc` and
- a lot of applications are using the Cluster-IP via [service env variable](https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/#accessing-the-service) `KUBERNETES_SERVICE_HOST` too.

For backward compatibility I would loosen this new rule a bit :-)

**Steps to reproduce the bug**
```
CA_CERT=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
AUTH="Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)"

it works:
curl --cacert $CA_CERT -H "$AUTH" "https://kubernetes.default.svc.cluster.local/api/v1/"

not working any more:
curl --cacert $CA_CERT -H "$AUTH" "https://kubernetes.default.svc/api/v1/"
curl --cacert $CA_CERT -H "$AUTH" "https://${KUBERNETES_SERVICE_HOST}/api/v1/"
```
**Version**
`version.BuildInfo{Version:"1.1.0-rc.1", GitRevision:"cdc39e70054be670d2c141dec7b8517a0812b021", User:"root", Host:"72433e36-3ac1-11e9-8dad-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-rc.0-54-gcdc39e7"}
`
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-04T04:49:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.6-gke.3", GitCommit:"04ad69a117f331df6272a343b5d8f9e2aee5ab0c", GitTreeState:"clean", BuildDate:"2019-01-10T00:39:15Z", GoVersion:"go1.10.3b4", Compiler:"gc", Platform:"linux/amd64"}

```
**Installation**
Helm/Tiller

**Environment**
GKE, MacOS

**Comment by rshriram** [comment]
I didn't know this was new.. 
Question: is it common to access the service as https://kubernetes/.. or https://kubernetes.default/.. ?
The reason I ask is because the filter chain matches could use the same logic as the HTTP virtual host permutations (svc, svc.ns, svc.ns.svc, svc.ns.svc.cluster, clusterIP, ..)..

**Comment by thomschke** [comment]
In my opinion these are common permutations
```
"filterChainMatch": {
    "serverNames": [
        "kubernetes.default.svc.cluster.local",
        "kubernetes.default.svc.cluster.local:443",
        "kubernetes.default.svc",
        "kubernetes.default.svc:443",
        "<CLUSTER-IP>",
        "<CLUSTER-IP>:443"
    ]
}
```
But it does not matter if you generate all permutations (like routes):
```
"filterChainMatch": {
    "serverNames": [
        "kubernetes.default.svc.cluster.local",
        "kubernetes.default.svc.cluster.local:443",
        "kubernetes.default.svc.cluster",
        "kubernetes.default.svc.cluster:443",
        "kubernetes.default.svc",
        "kubernetes.default.svc:443",
        "kubernetes.default",
        "kubernetes.default:443",
        "<CLUSTER-IP>",
        "<CLUSTER-IP>:443"
    ]
}
```

**Comment by rshriram** [comment]
Thanks. I skipped the entire SNI match as its unnecessary if there is a VIP for the service..

**Comment by sdake** [comment]
I have verified tip of release-1.1 fixes the problem.  Thanks @rshriram !!

**Comment by thomschke** [comment]
Thanks @rshriram - LGTM
