### ISSUE TITLE
Add sidecar for Galley

### ISSUE THREAD

**Issue by costinm** [istio/istio#12165]
I think this should be prioritized for 1.1.1 - I did some initial config/testing with 
https://github.com/istio-ecosystem/istio-installer/tree/master/istio-control/istio-config/templates/....
( still need to put the proper cert)

The goal is to make Galley MCP consistent with Mixer and Pilot - use Spiffe certs ( so it doesn't behave differently or have problems in multicluster), and eventually can use SDS.  Using Galley in MC is needed by few users, and switching to SDS (to remove the use of k8s secrets in such environments) is required as well.

**Comment by ozevren** [comment]
Tracked here: https://github.com/istio/istio/issues/11787
