### ISSUE TITLE
Ansible Playbook Installation Fails in Python Error: The error was: Version comparison: LooseVersion instance has no attribute 'version'

### ISSUE THREAD

**Issue by CoryARamirez** [istio/istio#12197]
**Describe the bug**
Running the Ansible playbook results in the below error despite the Kubernetes version being compatible. 

`fatal: [localhost]: FAILED! => {"msg": "The conditional check 'vo.stdout is version_compare(minimum_cluster_version,'>=')' failed. The error was: Version comparison: LooseVersion instance has no attribute 'version'"}`

**Expected behavior**
Given the below output:

`[hostname ansible]# kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}`

The playbook should continue installation, but it fails.

**Steps to reproduce the bug**
Running the Istio Ansible playbook on Centos 7.6.  Ansible & Tower versions both above 2.4. Python 3.  Valid Kubernetes version.

**Installation**
Created a playbook that points to upstream Istio playbook and executing via Tower.

**Environment**
Centos 7.6

**Comment by sdake** [comment]
@CoryARamirez the Ansible playbook has been deprecated as per discussions with the maintainerrs of that work (@knrc specifically).

Cheers
-steve

**Comment by sdake** [comment]
Closing issue as no response from OP and Ansible implementation is deprecated, unmaintained, and removed.
