### ISSUE TITLE
release-1.0 branch refers to missing go-control-plane branch

### ISSUE THREAD

**Issue by alexh-sauce** [istio/istio#12190]
The `revert_grpc_version_update` branch was deleted from the go-control-plane repo, so `dep` can't download the dependencies: https://github.com/istio/istio/blob/release-1.0/Gopkg.toml#L115-L117

Only master exists here: https://github.com/envoyproxy/go-control-plane/branches

This was fixed in Istio master: https://github.com/istio/istio/issues/7985

**Comment by howardjohn** [comment]
Sorry if this was never fixed, 1.0 has reached EOL now though so I don't think this will be fixed
