### ISSUE TITLE
Add more test cases to upgrade test

### ISSUE THREAD

**Issue by ostromart** [istio/istio#12229]
The upgrade tests that use test_crossgrade.sh are limited to non-MTLS, template only scenarios. 
We need to add at least the following:
- MTLS
- helm tiller 
- more complex parameter sets

**Comment by elfinhe** [comment]
Reopening as stale bot closed it but I do not see the upgrade tests added/referred.

Upgrade tests are still required:

- MTLS
- helm tiller 
- more complex parameter sets

**Comment by elfinhe** [comment]
carolynhu@ is now working on the integration tests for upgrade. We are going to create jobs for both 'istioctl x upgrade' and `helm template | kubectl apply` upgrade. 
This issue may be a follow-up work item to extend the integration tests to cover more profiles, such as security, and sds.
