### ISSUE TITLE
Gateway-connectivity: Use the standard port 443 instead of port 15443 to facilitate working with firewalls and setup instructions

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio#12224]

**Comment by elevran** [comment]
How related #12830?

**Comment by vadimeisenbergibm** [comment]
This one is for communication between micro services in different clusters. #12830 is for communication between sidecars and control plane, and between pilot and kube-apiserver in multiple clusters.

**Comment by vadimeisenbergibm** [comment]
@elevran I have added a line to #12830 : Access pilot and mixer through 443, and also kube-apiserver.

This issue is agreed with @rshriram . We should agree on #12830 if it is worth it.

**Comment by elevran** [comment]
not sure I follow. If you open 443 for cross cluster communication, won't that include any service running on the remote cluster (i.e., user created services, Istio services such as Pilot and Mixer, and the `kubernetes` service to access the API masters)? Why are we tracking these separately?

**Comment by vadimeisenbergibm** [comment]
You need to configure explicitly access from sidecars to remote Pilot and Mixer, and to configure access to a remote kube-apiserver by Pilot.
