### ISSUE TITLE
Adding simple e2e test using KIND 

### ISSUE THREAD

**Issue by utka** [istio/istio#12230]
**Describe the feature request**
k8s has new infra KIND https://github.com/kubernetes-sigs/kind 
It will allow to have faster and more reliable tests on Prow. We need to create simple KIND test for istio.
{{ Succinctly describe your request }}
New test infra to improve flakiness and speed of e2e tests

**Describe alternatives you've considered**
Did not look into other alternatives, but want to compare existing e2e tests infra vs KIND.

**Comment by howardjohn** [comment]
This is done, we have e2e simple kind and the integration tests are all using kind
