### ISSUE TITLE
Multi-cluster capability for supporting 2 or more K8s clusters

### ISSUE THREAD

**Issue by gnirodi** [istio/istio#1223]
This requires mostly testing and documentation for the multi-k8s registry code we have.

Use cases covered: https://goo.gl/AQARBs#heading=h.myl1ds62om2j

**Comment by ldemailly** [comment]
curious, why did you remove all the blocking sub issues ? conversion to epic ?
but shouldn't they all be in the epic ?
( like https://github.com/istio/istio/issues/626 )

**Comment by Rigdon** [comment]
Relevant additional use case
https://github.com/istio/issues/issues/236

**Comment by kinghrothgar** [comment]
Was this idea abandoned or completed?

**Comment by smawson** [comment]
Completed, see https://istio.io/docs/setup/kubernetes/multicluster-install/
