### ISSUE TITLE
more granularity to differentiate if mtls is strict or permissive in stackdriver metric

### ISSUE THREAD

**Issue by quanjielin** [istio/istio#12244]
**Background**
Today [service_authentication_policy](https://github.com/istio/istio/blob/0f39c7daa9abf255e069370866da529e9bb2270b/tests/e2e/tests/stackdriver/adapter.yaml#L145) in stackdriver adapter only has two mode: mtls and none

we probably want to have better granularity to differentiate if mtls is strict or permissive in metric 

**Problem**
```
service_authentication_policy: conditional((context.reporter.kind | "inbound") == "outbound", "unknown", conditional(connection.mtls | false, "mutual_tls", "none"))
```
Today connection.mtls value is get in istio-proxy like 
```
bool IsMutualTLS(const Network::Connection* connection) {
  return connection != nullptr && connection->ssl() != nullptr &&
         connection->ssl()->peerCertificatePresented();
}
```

**Possible solution**
we probably will need pilot side contribute(who knows about authn policy) to connection.mtls

**Comment by kyessenov** [comment]
Observation should not depend on config, IMHO. So ideally envoy should provide all data without any input.

Also see https://docs.google.com/document/d/1IdUL7qObUTGR2dNZuIE21AJyBOAiv_MIHbFoHfohGE8/edit#
