### ISSUE TITLE
Design Doc - Istio multi-cluster Hybrid Mesh on flat networks

### ISSUE THREAD

**Issue by gnirodi** [istio/istio#1224]
Needs review / approval by Environments working group
https://goo.gl/AQARBs

**Comment by gnirodi** [comment]
Hi Laurent / Costin (and Jose Ortiz)

I've updated the design doc with comments from the community so far. Please could you review the design doc towards eventual approval.

Note: Does anyone know how to reach Jose Ortiz? He seems to be one of the reviewers on the Environments Working Group but there's no email listed there and nor do I see him listed as a github member.

Thanks,

Gautam

**Comment by ldemailly** [comment]
done (apparently!)
