### ISSUE TITLE
Add an e2e test for Cluster-aware (Split Horizon)

### ISSUE THREAD

**Issue by ymesika** [istio/istio#12268]
Should use a similar logic for setting up two-clusters on flat network (istio-pilot-multicluster-e2e).
Run a scenario that tests routing two local and remote endpoints.

**Comment by howardjohn** [comment]
Make sure this gets in the test grid https://github.com/kubernetes/test-infra/blob/2128cd49ec494b32d99c1f914a831d401365a21b/testgrid/config.yaml#L3074

**Comment by ericvn** [comment]
At this point, I'm not sure that the test would actually run if it was in the testgrid. At least I'm seeing changes made in other PRs that might have made this test fail had it been there at the time (causing changes to actually have made this test pass now).
