### ISSUE TITLE
Update Features list on istio.io

### ISSUE THREAD

**Issue by jasminejaksic** [istio/istio#12266]
Update this page for 1.1 release: https://istio.io/about/feature-stages/

**Comment by duderino** [comment]
@jasminejaksic Thanks for jumping in.

@jasminejaksic-zz Thank you too

**Comment by duderino** [comment]
@jasminejaksic do you still have time to do this?  If not please ask for it to be reassigned earlier rather later

**Comment by jasminejaksic** [comment]
@oaktowner was working on this last week but for some odd reason I can't assign this to him

**Comment by howardjohn** [comment]
This was updated with 1.2
