### ISSUE TITLE
Ansible Installer fails to install Istio on Istio 1.1.0-rc2 because crds are not being included on Ansible Installer

### ISSUE THREAD

**Issue by gbaufake** [istio/istio#12262]
**Describe the bug**

- Installing Istio with Ansible on 1.1.0-rc2 is going to work because it doesn't include the crds files from helm template (https://preliminary.istio.io/docs/setup/kubernetes/install/minimal/)

**Expected behavior**
- Ansible should install Istio

**Steps to reproduce the bug**
- Download Istio 1.1.0-rc2

- Execute  `ansible-playbook istio-1.1.0-rc.2/install/kubernetes/ansible/main.yml -e '{"github_api_token": "********", "istio": {"delete_resources": true, "auth": false}}`

**Comment by sdake** [comment]
Ansible has been deprecated and removed from the system as per @knrc discussion.

Cheers
-steve
