### ISSUE TITLE
Get k8s env, integration2 framework test suite passing and required in presubmit test

### ISSUE THREAD

**Issue by incfly** [istio/istio#12267]
What we want
- A test suite running as presubmit tests, for k8s environment, using integration2 test framework.
- This is stably passing and eventually marked as required.

What we have 
- We have a prow test presubmit test, but currently it's failing and not marked as required. 

Why
- Pretty much we need the test stable and marking as required to encourage people writing e2e tests using new framework.

Details
- I'm working on such a test. It's currently failing on my own k8s cluster with images built from 0302.
I dig into the failure a bit. The tests failed at Istio system failed to deploy and I believe the error is Galley segfault. I filed bug https://github.com/istio/istio/issues/12265 separately.
- That failure might be just one example. Scanning through PRs, and many also failed on "Deployed Istio". [Example 1](https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/12257/istio-integ-k8s-tests/4617?log#log),  [Example2](https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/12263/istio-integ-k8s-tests/4623)
- test grid has a cell, https://testgrid.k8s.io/istio-presubmits#integration-k8s-tests. I'm not sure if that corresponds to prow/istio-integ-k8s-tests

**Comment by howardjohn** [comment]
I think all of the other ones are failing because of this 
```
2019-03-05T18:55:47.751921Z	info	CI	executing: helm --home /tmp/galley-validation-test-b31e448c/helmrepo template /home/prow/go/src/istio.io/istio/install/kubernetes/helm/istio --name istio-system-1551812146681441286 --namespace istio-system --values /home/prow/go/src/istio.io/istio/install/kubernetes/helm/istio/test-values/values-istio-mcp.yaml  --set global.mtls.enabled=true --set galley.enabled=true --set global.hub=gcr.io/istio-testing --set global.tag=1dcb37b04dc9ba663f75cd3cdcb90e01b107ecd4 --set global.proxy.enableCoreDump=true
```

We need to be using `test-values/values-e2e.yaml` as well, otherwise the resource requests are too large and we get pods in pending state.

**Comment by incfly** [comment]
Thanks @howardjohn . 

I dig a little bit. It's surprised to me that the while I pass
 `-istio.test.kube.helm.values "global.hub=gcr.io/jianfeih-test,global.tag=0302a"` when running the test, they don't seem take effect.

- They used to work, unsure if anything has changed.
- My changes, however, also have some changes on how to specify helm values overrides. I'll need to double check if it's not my own changes fail the setup :)

**Comment by howardjohn** [comment]
Seems like it should work? https://github.com/istio/istio/blob/134a31aea0da04e01ace7a865d4f26006b09dfcc/tests/integration2/tests.mk#L45

did you pass `-istio` and not `--istio`? Either way you can just set the HUB and TAG variables and that definitely works

**Comment by howardjohn** [comment]
Hopefully fixed in https://github.com/istio/istio/pull/12274

**Comment by ozevren** [comment]
As part of https://github.com/istio/istio/pull/12574, I've created an integration test for the test framework itself. This currently only has Istio deployment in it as a test, but it is possible to expand more to add more aspects.

My hope is to create a single, required presubmit gate (both Prow & CI) with that test. This way, we can at least make sure that the framework bits will not rot.

**Comment by ozevren** [comment]
Here is the test location: https://github.com/istio/istio/tree/master/tests/integration/framework

**Comment by incfly** [comment]
Obsolete since now it's very closed to all green. Thanks everyone for the efforts, especially @ozevren
