### ISSUE TITLE
kiali is not included in demo profile

### ISSUE THREAD

**Issue by linsun** [istio/istio#12270]
followed our install guide to fetch istio helm charts, then installed it via:

```
 helm template $HOME/istio-fetch/istio --name istio --values=istio/values-istio-demo.yaml --set mixer.policy.enabled=false gateways.istio-egressgateway.enabled=false --namespace istio-system | kubectl apply -f -
```

result: not seeing kiali in the istio-system ns.

**Comment by howardjohn** [comment]
I think this is because most of the config is in `values-istio-demo-common.yaml` now. When we generate `istio-demo.yaml` we apply both value files together.  

Running a quick grep we only reference these files in the docs in one place: `content/docs/setup/kubernetes/install/ibm/index.md`

**Comment by linsun** [comment]
I suggest we remove values-istio-demo-common.yaml and merge the content into values-istio-demo.yaml or values-istio-demo-auth.yaml.  it is confusing to our users to specify 2 files.

While this  content is only in that one place, that is our instruction to quick start with istio.

**Comment by howardjohn** [comment]
I think the reason we have it is because the demo and demo-auth were getting out of sync. @mandarjog made the change

**Comment by jmazzitelli** [comment]
So, are we saying that we now have to add this:

```
--values=istio/values-istio-demo-common.yaml
```

In addition to the original `--values=istio/values-istio-demo.yaml` when we run the helm command?

**Comment by howardjohn** [comment]
Yes, if you are using helm and want the demo profile, that is what is needed currently. All of the docs except the IBM page use `kubectl apply -f istio-demo.yaml` instead of helm - helm is used only for the production install

**Comment by linsun** [comment]
Note: we are also in the process of creating a table for each profile which will include the demo profile.  It is odd experience if we ask users to feed 2 values.yaml for demo but not for other profiles.

So I proposed https://github.com/istio/istio/pull/12280 PTAL

**Comment by mandarjog** [comment]
Need to be careful about precedence order. Made they change because files were getting out of sync.
