### ISSUE TITLE
'istioctl proxy-status' command gets wrong version for release 1.0.3-1.0.6

### ISSUE THREAD

**Issue by morvencao** [istio/istio#12295]
**Describe the bug**
The `istioctl proxy-status` command gets the wrong version, as you can see from below output(last column), version `1.0.2` is shown, expect `1.0.6`
```
# istioctl proxy-status
Stderr when execute [/usr/local/bin/pilot-discovery request GET /debug/syncz ]: gc 1 @0.018s 15%: 0.24+3.8+3.5 ms clock, 1.9+0.17/0.81/1.5+28 ms cpu, 4->4->1 MB, 5 MB goal, 8 P
gc 2 @0.035s 17%: 0.010+6.0+4.0 ms clock, 0.087+0.094/2.3/0.29+32 ms cpu, 4->4->2 MB, 5 MB goal, 8 P

PROXY                                                  CDS        LDS        EDS               RDS          PILOT                           VERSION
istio-egressgateway-65dfbf888-q6tkj.istio-system       SYNCED     SYNCED     SYNCED (100%)     NOT SENT     istio-pilot-878499dd5-88mdz     1.0.2
istio-ingressgateway-79c8bcccc5-gtb97.istio-system     SYNCED     SYNCED     SYNCED (100%)     NOT SENT     istio-pilot-878499dd5-88mdz     1.0.2
```

We need to make sure the `ISTIO_META_ISTIO_PROXY_VERSION` environment variable is set to right version for every later release in `proxyv2` dockefile.

See: https://github.com/istio/istio/blob/1.0.6/pilot/docker/Dockerfile.proxyv2#L9

/cc @linsun @vadimeisenbergibm

**Comment by linsun** [comment]
@duderino @utka FYI, I'd like to discuss this in the next release test call, how can we automate this more so this won't happen.

**Comment by linsun** [comment]
cc @ibm-jason

**Comment by ibm-jason** [comment]
/cc @morvencao 

Just to make sure that I'm clear, it sounds like we need to checkout to each release tag (from 1.0.3 to 1.0.6), and update this `ISTIO_META_ISTIO_PROXY_VERSION` variable to reflect the correct version. For example, I'd checkout `1.0.3`, prep a PR based on that, and update the `ISTIO_META_ISTIO_PROXY_VERSION` to 1.0.3, then repeat the process for the remaining releases up to `1.0.6`?

**Comment by utka** [comment]
@ibm-jason yes, that's correct

**Comment by morvencao** [comment]
@ibm-jason I'm not sure if we need to fix the released versions. I suggest to add to some automation tests to make sure we won't have same issue in future versions.

**Comment by ibm-jason** [comment]
/cc @morvencao @utka 

I took a stab at creating two PRs ☝️ that attempt to update the `ISTIO_META_ISTIO_PROXY_VERSION` environment variable, based off the tagged commit(s). I'm not 100% sure that the PRs were created in the appropriate manner to ensure that #12354 is specifically for changing the value for the 1.0.3 tagged commit, and #12355 specifically changes the 1.0.4 tagged commit. If either of you can take a look at it and advise me on next steps, that would be awesome. 🎉

**Comment by linsun** [comment]
@ibm-jason I agree with @morvencao - we should not change the already released version.  We should look into how to automate this, prevent this from happening again.

**Comment by ibm-jason** [comment]
@linsun Sure, no problem. The plan was to fix the previous versions _and_ update the tests, but if our time is better spent creating the automation to prevent this from happening again, I'll work on that instead. 👍

**Comment by ibm-jason** [comment]
I've been digging around the codebase looking for the appropriate place to add this test automation. I look at this:

https://github.com/istio/istio/blob/fd6055a78808b5e5e3577989c0442f35050d48f8/Makefile#L49

This looks to be the Makefile target for istioctl tests. Can someone confirm whether I'm in the right place for adding this functionality?

**Comment by utka** [comment]
One thing that I would add test for this file pilot/docker/Dockerfile.proxyv2 and tools/deb/istio-start.sh should have the same version for ISTIO_META_ISTIO_PROXY_VERSION. 

But in general it is not clear to me what is ISTIO_META_ISTIO_PROXY_VERSION supposed to be, for example for master it is[ 1.1.0 ](https://github.com/istio/istio/blob/f7feb0fcbab73d05375815f06956ac3002f231d6/pilot/docker/Dockerfile.proxyv2#L14
) as well as for release [1.1.0](https://github.com/istio/istio/blob/190d4c1c59328e2aca2611f3056a03d45c583ca8/pilot/docker/Dockerfile.proxyv2#L9)
Is someone just decides what is it supposed to be or is there some correlation with tags?

**Comment by ibm-jason** [comment]
@utka I'm not 100% certain, but yes, it sounds like the value for `ISTIO_META_ISTIO_PROXY_VERSION` should match the commit/release tag. `ISTIO_META_ISTIO_PROXY_VERSION` is equal to `RELEASE_TAG`, essentially. However, I'm not sure what that means for the master branch.

**Comment by ibm-jason** [comment]
@utka - BUMP ☝️

**Comment by ibm-jason** [comment]
@utka, @linsun - BUMPing this issue once again ☝️

**Comment by utka** [comment]
I think for master it should be 1.2 or one version up compare to current release

**Comment by ibm-jason** [comment]
@howardjohn sounds like https://github.com/istio/istio/pull/14222 fixes this issue. Is that correct? If so, I think we can close this one.

**Comment by howardjohn** [comment]
Yes should be fixed
