### ISSUE TITLE
Log message "use_original_dst is deprecated"; Istio needs a replacement

### ISSUE THREAD

**Issue by esnible** [istio/istio#12294]
I'm using 1.1 RC2

The sidecar logs frequently complain about "use_original_dst'"

```
[warning][misc] [external/envoy/source/common/protobuf/utility.cc:129] Using deprecated option 'envoy.api.v2.Listener.use_original_dst'. This configuration will be removed from Envoy soon. Please see https://github.com/envoyproxy/envoy/blob/master/DEPRECATED.md for details.
```

The large number of these messages makes it easy to miss real problems.

https://github.com/envoyproxy/envoy/blob/master/DEPRECATED.md#version-160-march-20-2018 says this was deprecated last March.  Envoy recommends "Use listener filters and filter chain matching instead."

**Comment by esnible** [comment]
@andraxylia @rshriram This message appears in the log of every proxy every half hour.  Do we consider this an `area/networking` concern?

**Comment by dotw** [comment]
Hello guys, 1.1.2 still has the same error and it generates 3 logs every second per sidecar. this makes our ELK server has huge pressure. How can I suppress this warning?

**Comment by esnible** [comment]
@dotw There are no instructions for disabling this message.  For Istio 1.2 it will be handled by https://github.com/istio/istio/pull/13182 .  As a work around you can probably do `kubectl -n istio-system edit cm istio-sidecar-injector` and add `"--component-log-level", "misc:error"` to the sidecar pod arguments following the example of the Istio 1.2 work.

**Comment by supereagle** [comment]
@esnible  Will #13182 be cherry-picked into release-1.1 branch?

**Comment by esnible** [comment]
@andraxylia @rshriram This problem seems to cause a lot of difficulties.  Do we have a plan for Istio 1.1 users?

**Comment by howardjohn** [comment]
The logs are supressed, https://github.com/istio/istio/issues/16275 is tracking envoy deprecation, and this is being worked on (filter chain discovery), so I am going to close
