### ISSUE TITLE
Gateway rules in istio-remote cluster does not take effect

### ISSUE THREAD

**Issue by xiaozhongliu** [istio/istio#12291]
**Describe the bug**
We've successfully deployed the Single control plane topology with two clusters.
Now we have istio gateways installed in both clusters. But gateway rules in istio-remote cluster does not take effect.
If I config gateway rules only on remote cluster, no final rule is generated:
```
[root@iZ2zegdhs7pd18ik2o49fsZ ~]# istioctl pc routes istio-ingressgateway-84b4868f6b-jqkdq -o json
[
    {
        "virtualHosts": [
            {
                "name": "backend",
                "domains": [
                    "*"
                ],
                "routes": [
                    {
                        "match": {
                            "prefix": "/stats/prometheus"
                        },
                        "route": {
                            "cluster": "prometheus_stats"
                        }
                    }
                ]
            }
        ]
    }
]
```

**Expected behavior**
Gateway rules in istio-remote cluster take effect.

**Steps to reproduce the bug**
Config gateways and related virtualservices in both clusters of a Single control plane topology.

**Version**
```
➜  ~ istioctl version
Version: 1.0.5
GitRevision: c1707e45e71c75d74bf3a5dec8c7086f32f32fad
User: root@6f6ea1061f2b
Hub: docker.io/istio
GolangVersion: go1.10.4
BuildStatus: Clean
➜  ~ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T22:29:25Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Installation**
Alibaba Cloud -> Istio helm chart

**Environment**
Alibaba Cloud

**Cluster state**
No need to provide

**Comment by xiaozhongliu** [comment]
Solved by creating all rules from main cluster.

**Comment by ymesika** [comment]
As there is a single control plane the rules your create in the primary are affecting both the primary and remote clusters. As you've figured by yourself.

Moreover, the remote cluster don't need the Istio CRDs deployed so you basically can't deploy rules to the remote clusters.

**Comment by xiaozhongliu** [comment]
@ymesika Thanks for ur reply.
At the beginning, I installed CRDs(istio-init) in remote clusters in order to create gateway rules there.
Now that rules from all clusters are created from the primary cluster, no istio-init is needed in remote clusters. For our situation, only istio-remote and istio-gateway are needed in remote clusters, right?
Please help to comfirm this, thanks a lot.

**Comment by ymesika** [comment]
Yes, @xiaozhongliu. That's correct.
You will also need Citadel if your security is on and Sidecar Injector if you need automatic injection.

**Comment by xiaozhongliu** [comment]
Get it. Thanks a lot.

**Comment by sdake** [comment]
@xiaozhongliu are we good to close this issue then?
