### ISSUE TITLE
Add debug config dump support to Galley Ctrlz page

### ISSUE THREAD

**Issue by ozevren** [istio/istio#12298]
We need a debug output page for Galley, that can show its current internal config state. This should work as a Ctrlz topic. MCP Server code is the ideal place to tap into. 

This includes:
- Creating a new Ctrlz topic that has the right interface to listen to MCP Server to different snapshots it is serving.
- Plumb the interface in through the MCP Server/initialization code.
- Set it up at the top level in Galley.

**Comment by ozevren** [comment]
@clyang82 I was about to assign this to you, and I noticed you already self assigned. :) Thanks

**Comment by clyang82** [comment]
This issue was implemented. so close it.
