### ISSUE TITLE
1.1 RC2 error running istio authn tls-check

### ISSUE THREAD

**Issue by ekarlso** [istio/istio#12305]
**Describe the bug**
Warning! error execing into istio-pilot-544b5d9bc6-xcnpr/istio-system discovery container: gc 1 @0.015s 2%: 0.008+1.3+0.065 ms clock, 0.034+0.12/1.0/1.5+0.26 ms cpu, 4->4->2 MB, 5 MB goal, 4 P
gc 2 @0.027s 3%: 0.008+1.9+0.094 ms clock, 0.033+0.11/1.7/2.6+0.37 ms cpu, 4->4->2 MB, 5 MB goal, 4 P

Error: nothing to output

**Expected behavior**
It should work?

**Steps to reproduce the bug**
Run *istioctl authn tls-check ...*

**Version**
1.1.0 RC2

**Installation**
Helm ref doc.

**Environment**
Azure AKS 1.12.5

**Cluster state**
-

**Comment by aguromanodg** [comment]
I am getting same error, I have `istio` `1.1.0-rc.3` deployed with helm in a GKE cluster.
Also using `istioctl` `1.1.0-rc.3`
The output is :

```
Error: nothing to output
```

Thanks!

**Comment by yangminzhu** [comment]
Could you try to use the latest 1.1 rc5, and yes we have updated it to accept the pod name recently.
/cc @diemtvu

**Comment by jpittis** [comment]
Confirming that this is a problem for us too.

```
istioctl authn tls-check my-pod.my-namespace
istioctl -n my-namespace authn tls-check my-pod.my-namespace
istioctl authn tls-check my-pod.my-namespace my-service.service-namespace.svc.cluster.local
istioctl -n my-namespace authn tls-check my-pod.my-namespace my-service.service-namespace.svc.cluster.local
```

All four of the above commands return 

```
Error: nothing to output
```

Using `istio-1.1.0-rc.6`.

**Comment by jpittis** [comment]
Yeah this is for sure broken on 1.1 master.

**Comment by jaygorrell** [comment]
Also hitting this on 1.1

**Comment by diemtvu** [comment]
I've just tried with 1.1.0 and 1.1.1 release. Both are working. You need to use the pod with namespace though. For example
```
istioctl authn tls-check sleep-74c95d6f7f-66h2p.foo
```

**Comment by jaygorrell** [comment]
This is working for me after updating to 1.1.1 as well. I'm actually wondering if it was a problem before i enabled `global.controlPlaneSecurityEnabled`. Following the mTLS migration guide leaves that disabled.

**Comment by dwradcliffe** [comment]
Duplicate of https://github.com/istio/istio/issues/13028
