### ISSUE TITLE
Clarification between Service Entry and Synthetic Service Entry

### ISSUE THREAD

**Issue by Nino-K** [istio/istio#12311]
I would like to get some clarification on what would be the recommended way of generating Service Entries. Presently, Galley generates Synthetic Service Entries for the platform generated configs and Service Entries are generated by the user only. This does not exactly align with what other platforms are doing. For instance, Cloud Foundry Service Entries are generate by the platform (copilot) and not the user. This behaviour does not align with what Galley does today. What is the correct/semantic way of generating Service Entries/synthetic SEs? Also, we do not have a clear documentation on what distinguishes the two. It becomes more important to distinguish the behaviour between the two as there is a [PR](https://github.com/istio/istio/pull/12276) in flight which introduces incremental endpoint updates to envoy based on a type of service entry (and other parameters) that is received.

**Comment by Nino-K** [comment]
@XanderStrike

**Comment by andraxylia** [comment]
Semantically they are the same,  cc @louiscryan. Ultimately they lead to creation of Envoy clusters and endpoints.

We introduced synthetic service entries to ease the transition to MCP and make incremental code changes in Pilot, which has different historical code paths for user-generated configs (ServiceEntries CRDs) and k8s native resources (k8s services and endpoints). The Pilot Decomposition doc https://goo.gl/qAsEQx depicts them, the golang interfaces are IstioConfigStore() and ServiceDiscovery(). The ServiceDiscovery() interface has been lately optimized for endpoint changes and transformed into XDSPush(), but nothing prevents us from using the optimized path for user-defined ServiceEntries.
