### ISSUE TITLE
Codecov flake:  Coverage dropped: proxy/envoy/v2/rds.go:-12.200000% (73.200000% to 61.000000%)

### ISSUE THREAD

**Issue by duderino** [istio/istio#12316]
**Describe the bug**

I've seen this one a bunch of times when reviewing PRs.  It comes and goes and appears to be completely unrelated to PR.

https://circleci.com/gh/istio/istio/347770?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

```
--- FAIL: TestCheckCoverage (8.09s)
    main_test.go:216: Coverage dropped:
        istio.io/istio/pilot/pkg/proxy/envoy/v2/rds.go:-12.200000% (73.200000% to 61.000000%)
=== RUN   TestGoPath
--- PASS: TestGoPath (0.00s)
```

**Comment by esnible** [comment]
Is this only happening for _rds.go_?

I suspect what is happening is that there are no tests for failure cases.  So if a test fails, or partially fails and recovers, more code will be executed than usual.  This becomes a new baseline for the amount of code executed during tests.

We could solve this by writing tests that make sure all code is hit every time.  This may mean a lot of new tests.  Let's use this Issue to determine which lines are not being covered consistently.

**Comment by esnible** [comment]
I remember seeing coverage reports added as comments to PRs.  I did not see such a report on https://github.com/istio/istio/pull/12314 .

I found https://codecov.io/gh/istio/istio which shows the code coverage of Istio.  It looks like it is 70% overall and "pilot" is mostly **red**.  We had an issue to raise coverage to 90% but it is closed https://github.com/istio/istio/issues/1455 .

**Comment by duderino** [comment]
@esnible I've only seen it for rds.go.  rds.go often passes, but when it doesn't it's always a 73% to 61% drop

**Comment by duderino** [comment]
@kyessenov mentioned there was some non-determinism in that test.  I wonder if that non-determinism means that sometimes some code paths are not executed

**Comment by esnible** [comment]
Here is the coverage for _rds.go_: https://codecov.io/gh/istio/istio/src/e294254e6b0415f798e8f5fb02e6a1d4ca304c5f/pilot/pkg/proxy/envoy/v2/rds.go at 71%

I couldn't find any Code Coverage reports for that file at 56% in the UI.  Strangely it was marked as "New File" in many reports.

**Comment by kyessenov** [comment]
Codecov is not a reliable sort of input here. I think we stopped uploading reports as of a couple of months ago for PRs. Probably, checking the coverage reports in circleci artifacts for failing PRs would help narrow down which code is no longer covered.

**Comment by esnible** [comment]
I just had this problem with https://circleci.com/gh/istio/istio/348829 .  That build says 

```
Uploading /go/out/codecov/pr/coverage.cov (4.9 MB): DONE
Uploading /go/out/codecov/pr/coverage.html (12 MB): DONE
Uploading /go/out/codecov/pr/junit.xml (61 kB): DONE
Uploading /go/out/codecov/pr/report.out (31 kB): DONE
```
but I don't understand where it put these.  @kyessenov How do I see them?

**Comment by kyessenov** [comment]
https://348829-74175805-gh.circle-artifacts.com/0/go/out/codecov/pr/coverage.html#file0

Click on Artifacts > go/out/codecov/{baseline,pr}/coverage.html.

**Comment by esnible** [comment]
Closing because the threshold changed has been merged.
