### ISSUE TITLE
Unable to see access logs in istio-proxy logs.

### ISSUE THREAD

**Issue by velumaniduraisamy** [istio/istio#12323]
Today I installed istio-1.1.0-rc2 version and started sample bookinfo application. When I hit the APIs, I couldn't see any access logs for Incoming and Outgoing calls in the Application's Istio-Proxy.

**Comment by velumaniduraisamy** [comment]
I installed using helm where the default value for "global.proxy.accessLogFile" is empty. After changing that to "/dev/stdout", I am able to see the logs. 
But in the documentation, it is mentioned that the default value for"global.proxy.accessLogFile" is "/dev/stdout"

https://preliminary.istio.io/docs/reference/config/installation-options/#global-options

**Comment by howardjohn** [comment]
Docs have been correctly updated to show default is now `""`. Thanks!
