### ISSUE TITLE
All containers should have memory limits

### ISSUE THREAD

**Issue by clyang82** [istio/istio#12344]
All containers should have memory limits in order to prevent denial of service due to a container consuming all of the host's memory. As a best practice, all the containers should have memory limits specified in the deployment spec. 

I check the code, there are default values before. But they are commented right now. I am not sure what is the reason?
https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/values.yaml#L350:L355

We have some default resource requests and limits for `telemetry` and `zipkin`. we do not have for others.

Any thoughts? @linsun @morvencao @sdake

**Comment by linsun** [comment]
@mandarjog can you comment on why this is commented out now?

cc @duderino @jnativio

**Comment by jnativio** [comment]
I don't think the default limits were ever enabled. The default value for requests (10m) are basically just to enable HPA. Some components now have defined requests and limits for both cpu and memory in their own charts (telemetry, istio-proxy). The fact is whatever values are defined by default, the user should review and change them to values compatible to the cluster/nodes size they are installing into.

**Comment by mandarjog** [comment]
Not sure why it was commented out, but it is not recent. https://github.com/istio/istio/commit/e5a09e9da2b2a43a34e3d9ba50f6fcea4c403341 @ymesika

We should set limits though.

**Comment by linsun** [comment]
@clyang82 can you submit a PR for this?  Maybe too late for 1.1, but we can get it in 1.1.1.

**Comment by ymesika** [comment]
The intention of the PR that added the default resources was to enable HPA. And for that you needs to set requested resources for all containers.

What values will you put for the limits? Shouldn't it be tailored for each component?

**Comment by clyang82** [comment]
@linsun @ymesika Just revert the default value to 
```
  defaultResources:
    requests:
      cpu: 10m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 128Mi
```
or do you have new suggested values? Thanks

**Comment by linsun** [comment]
This is for all control plane components' default, correct?

@mandarjog @jnativio do you have recommendations?

**Comment by jnativio** [comment]
Just using these default values are not a good solution. Pilot for instance has a memory requests of 2G in its chart but no limits, so using the default of 128M for limits  is not going to work. Prometheus is another component that uses a good deal of memory. Telemetry and the gateways (when PR #12315 is merged) have limits defined. Probably other components can have a common set of values.

**Comment by morvencao** [comment]
Setting the default global resource limits is risky.
It's will be convincing if we have sufficient perf test data to support those settings.

**Comment by linsun** [comment]
@clyang82 is this still an issue?  I think we have set mem and cpu limits in 1.1

**Comment by rvennam** [comment]
This is still an issue in 1.1. I see Requests and Limits are set on the istio-proxy containers only.

**Comment by zqzzq** [comment]
I am confused about this. I updated to 1.1.3 by the istio-demo.yaml, but when I applied this yaml to k8s , the pilot, the ingressgateway, and the egressgateway were all restarted constantly because the OOMKilled, then I found that they are all set to a smaller limit，so I had to delete the limit，and now everything is fine. So I want to know why set such a small limit?

**Comment by dreadbird** [comment]
I agree with @morvencao @zqzzq. 
With istio1.1.3, use the isito-demo.yaml with default value, and OOMKilled...

**Comment by clyang82** [comment]
Yes. I think we should have some best practices for supporting the limits for each component. otherwise, it is risky here. if we do not have that data, we can leave it to the user who can modify the values.yaml to set the proper values to fit for their environment.

**Comment by wansuiye** [comment]
pilot、policy、telemetry were all restarted continually in 1.1.3 beacuse the  OOMKilled

**Comment by sdake** [comment]
reset milestone as 1.1 is no more :)
