### ISSUE TITLE
istio-manifests.yaml fails validation on Istio 1.1 

### ISSUE THREAD

**Issue by duderino** [istio/istio#12341]
See https://github.com/GoogleCloudPlatform/microservices-demo/issues/161

**Comment by howardjohn** [comment]
Should be fixed in https://github.com/GoogleCloudPlatform/microservices-demo/pull/183. ServiceEntry validation was changed so IP address is not a valid host in 1.1.

**Comment by howardjohn** [comment]
Closing as fix was merged (into the microservices-demo repo, not Istio)
