### ISSUE TITLE
Regression on injected pod startup time.

### ISSUE THREAD

**Issue by jnativio** [istio/istio#12358]
**Describe the bug**
Startup time of pod/service increased for a recent 1.1 build when compared with 1.0.3. This can be observed in the chart below showing the startup time of a single pod when a number of pods/services are already present in the cluster. The startup time is better in 1.1 only when there is a large number of services.
![image](https://user-images.githubusercontent.com/18554027/54042043-36fe1880-4197-11e9-9d93-b2688b519a5d.png)

There was  a big improvement in Pilot cpu consumption though:
![image](https://user-images.githubusercontent.com/18554027/54042021-2cdc1a00-4197-11e9-8313-84c1c49480f0.png)

**Expected behavior**
No regression in pod+sidecar startup time.

**Steps to reproduce the bug**
Measure the time to start a pod with sidecar, from the deployment command until it responds a request.

**Version**
K8s version: 1.11.7_1543

**Installation**
Helm chart template

**Environment**
IKS

**Comment by jnativio** [comment]
@mandarjog Could you pls add the Perf and scalability tag

**Comment by mandarjog** [comment]
@jnativio how do you measure this?
In the large clusters with 1000 to 2000 services,
It takes less than 5s to see “envoy is ready” message and a few seconds more for k8s to pick it up.

**Comment by jnativio** [comment]
@mandarjog The times in the chart were measured based on when the service responds a valid request, not in log messages.
