### ISSUE TITLE
need a linter for OWNERS/CODEOWNERS files

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#12362]
We managed to bork a file during cherry pick (#12361 ). It's a trivial file format to validate.

**Comment by geeknoid** [comment]
Should be able to do this as a script checked into istio/common-files.

**Comment by howardjohn** [comment]
Prow can do it with `verify-owners` plugin. https://prow.k8s.io/plugins

**Comment by howardjohn** [comment]
verify-owners plugin is turned on, this is working now. Tested in a PR: https://github.com/istio/istio/pull/15550
