### ISSUE TITLE
need to update helm repo when 1.1 goes out

### ISSUE THREAD

**Issue by linsun** [istio/istio#12360]
currently it uses a 1.1 build repo

https://preliminary.istio.io/docs/setup/kubernetes/install/helm/#installation-steps

cc @geeknoid

**Comment by howardjohn** [comment]
@linsun is this done now? Not 100% sure what the original issue was since the docs have changed

**Comment by howardjohn** [comment]
The docs seem fine now, I think this is a stale issue -- if not we should move to the 1.2 milestone since the 1.1 one isn't looked at much
