### ISSUE TITLE
Istioctl homebrew formula (MacOS) should be updated

### ISSUE THREAD

**Issue by ymesika** [istio/istio#12367]
Once we have v1.1 out of the door we should also create a PR for the Homebrew `istioctl` formula (we already have such brew).

**Comment by rvennam** [comment]
cc: @murarisumit

**Comment by murarisumit** [comment]
Thanks @rvennam for keeping in loop

@ymesika already have notification for release update and will  create the PR at homebrew as v1.1 gets released, and check if I can automate this process for simple version bumps.

**Comment by murarisumit** [comment]
Couldn't get time trying out automation, but created PR for 1.1.0 at https://github.com/Homebrew/homebrew-core/pull/38058

**Comment by ericvn** [comment]
Looks like we are slightly ahead of schedule

```brew info istioctl                                                                                                                                                                                                                      
istioctl: stable 1.3.2 (bottled)
Istio configuration command-line utility
https://github.com/istio/istio```

**Comment by ericvn** [comment]
Looking at PRs, it appears that things are being kept up to date. I'm not sure if it's automated at this point or not.

I'll close this PR since things are good. Please reopen if it seems things are regressing in the home-brew repo.
