### ISSUE TITLE
Platform Setup Dependencies for aws

### ISSUE THREAD

**Issue by alok87** [istio/istio#12386]
**Describe the bug**

How many are still relevant from this list of admission controllers?
https://istio.io/docs/setup/kubernetes/platform-setup/aws/
```
- NamespaceLifecycle
    - LimitRanger
    - ServiceAccount
    - PersistentVolumeLabel
    - DefaultStorageClass
    - DefaultTolerationSeconds
    - MutatingAdmissionWebhook
    - ValidatingAdmissionWebhook
    - ResourceQuota
    - NodeRestriction
    - Priority
```

**Expected behavior**
- PersistentVolumeLabel  is deprecated is it still required?

**Comment by sdake** [comment]
@alok87 this document has been deleted from the preliminary documentation as nobody is available to maintain it at this time.  The current document is focused around kops, however, we believe it makes more sense to document around EKS.  Istio does work on Amazon EC2, however, I am not entirely clear what set of config creds are needed for this plaform.

Cheers
-steve

**Comment by howardjohn** [comment]
@alok87 as sdake mentioned, we no longer have this in the docs so I don't think this is relevant. If you have any follow up questions please direct them to discuss.istio.io. If not I'll assume this is resolved as there has been no followup for months. Thanks
