### ISSUE TITLE
Problem with connecting to redis

### ISSUE THREAD

**Issue by retroryan** [istio/istio#1238]
Application can not connect to redis when using named ports that route traffic through Istio.  

Example application:

`https://github.com/retroryan/istio-workshop/blob/master/guestbook/`

This works:

`guestbook/deployGuestBookIstio.sh`

Delete the redis service and guestbook-ui and redeploy with broken redis service to observe the problem: 

```
kubectl delete -f guestbook/guestbook-ui-deployment.yaml
kubectl delete -f guestbook/redis-service.yaml
```

Redeploy with redis named port:

```
kubectl create -f broken-redis-service.yaml 
kubectl apply -f <(istioctl kube-inject -f guestbook-ui-deployment.yaml) -f guestbook-ui-service.yaml
```

When guestbook-ui the logs show a connection error to redis.

**Comment by GregHanson** [comment]
@retroryan are you still seeing this problem in istio version 0.5.1 or later?

**Comment by GregHanson** [comment]
closing until issue can be reproduced in istio 0.5.1 or later
