### ISSUE TITLE
Accessing non-default namespace service with mTLS enabled always results in "upstream connect error or disconnect/reset before headers" / 503 error

### ISSUE THREAD

**Issue by ac111** [istio/istio#12395]
**Describe the bug**
Installed 1.0.6 via Helm chart with mTLS enabled.  First deployed httpbin and sleep sample services to default namespace, and verified (using curl) that requests sleep --> httpbin work as expected.  Next, created an auto-injected sidecar namespace called "foo" and deployed the same httpbin and sleep services to this new namespace.  Retried curl operations between sleep (primary container) and httpbin, but all requests failed with 503 Service Unavailable error with message "upstream connect error or disconnect/reset before headers".  However, when curl'ing via sleep "istio-proxy" container with certificate options, the request completes successfully.  It only fails when requests originate from non-proxy container.

Used both mesh-wide mTLS policy and *.local DestinationRule (confirmed OK via istioctl authn tls-check), as well as service-specific Policy and DestinationRule.  Neither fixed the errors.  Tried resetting Pilot as well, but no luck.  Only applications deployed to "default" namespace seem to work.  Confirmed in Kiali that default namespace service requests show the "security" badge.  Not seeing any errors in istio-proxy logs (even with trace-level debugging enabled), and istioctl proxy-config cluster (JSON output) details appear correct.

I confirmed that the same sample applications (httpbin, sleep) work as expected when deployed to default namespace.

**Expected behavior**
Curl requests from primary sleep container to httpbin service should be successful.

**Steps to reproduce the bug**
Download release 1.0.6 (https://github.com/istio/istio/releases/) and run Helm install:
helm install --name istio --namespace istio-system --set global.mtls.enabled=true,kiali.enabled=true,grafana.enabled=true,tracing.enabled=true ./istio

Create "foo" namespace:
kubectl create ns foo
kubectl label namespace foo istio-injection=enabled

Deploy sample httpbin and sleep applications:
kubectl apply -f <(istioctl kube-inject -f samples/httpbin/httpbin.yaml) -n foo
kubectl apply -f <(istioctl kube-inject -f samples/sleep/sleep.yaml) -n foo

Once pods are running, check service access between sleep and httpbin as follows:
kubectl exec <SLEEP_POD_ID> -c sleep -n foo -- curl https://httpbin.foo:8000/ip -v

**Version**
# istioctl version
Version: 1.0.6
GitRevision: 98598f88f6ee9c1e6b3f03b652d8e0e3cd114fa2
User: root@464fc845-2bf8-11e9-b805-0a580a2c0506
Hub: docker.io/istio
GolangVersion: go1.10.4
BuildStatus: Clean

# kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

**Installation**
Via Helm chart from locally-cloned Git repo with 1.0.6 release tag (see specific deploy command above).

**Environment**
EC2, 5-node cluster

# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial

**Cluster state**
Attached istio-dump.tar.gz.
[istio-dump.tar.gz](https://github.com/istio/istio/files/2951877/istio-dump.tar.gz)

# kubectl get nodes
NAME                     STATUS   ROLES    AGE     VERSION
k8sdemo1.cenx.localnet   Ready    node     2d18h   v1.13.2
k8sdemo2.cenx.localnet   Ready    master   2d18h   v1.13.2
k8sdemo3.cenx.localnet   Ready    node     2d18h   v1.13.2
k8sdemo4.cenx.localnet   Ready    node     2d18h   v1.13.2
k8sdemo5.cenx.localnet   Ready    node     2d18h   v1.13.2

**Comment by ac111** [comment]
Please note the issue only occurs when mTLS is enabled.  When mTLS is NOT enabled in this same cluster, services are able to communicate without error for any namespace (not just default).
I have also tried this same test with latest 1.1-rc2 and also tried without using the Helm chart (ie. just kubectl apply CRDs + auth-demo YAML).

**Comment by esnible** [comment]
I am surprised that it is not working.  I have a “4 point” debugging strategy.  Let's try the following to get more information.

Point 1 is the app itself. Verify that your service really exposes the URL you are trying by doing kubectl exec <any-httpbin-pod> -c istio-proxy -- curl localhost:80/
// 80 is the targetPort

Point 2 is the sidecar of the app. You have global.mtls.enabled=true. You can simulate an mTLS request coming into example-backend like this:

```
PODNAME=...
SERVICE=httpbin
NS=foo
SVCPORT=80
PATH=/example-backend/info
PODIP=$(kubectl get pod $PODNAME -o jsonpath='{.status.podIP}')
kubectl exec $PODNAME -c istio-proxy -- curl -v https://$SERVICE.$NS.svc.cluster.local:$SVCPORT/$PATH --resolve "$SERVICE.$NS.svc.cluster.local:$SVCPORT:$PODIP" --key /etc/certs/key.pem --cert /etc/certs/cert-chain.pem --cacert /etc/certs/root-cert.pem --insecure
```

If this works go on to point 3 by running the same test from the sidecar of frontend.

Point 4 is what you have already tried.  We need to see what is happening earlier.

Use `kubectl get virtualservice,destinationrule --all-namespaces` to make sure there isn't some configuration that is performing unexpected configuration.

**Comment by ac111** [comment]
Thank you for your recommendations to troubleshoot this issue.  I ended up entirely re-creating my cluster (via kubeadm), and re-deployed istio using the 1.0.6 Helm chart package.  I've just retried my simple sample sleep --> httpbin test using a namespace "foo" and it now appears to be working correctly:

kubectl exec sleep-69f8fcfdf6-kfpr8 -c sleep -n foo -- curl http://httpbin.foo:8000/ip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0{
  "origin": "127.0.0.1"
}
100    28  100    28    0     0   1866      0 --:--:-- --:--:-- --:--:--  1866

I will continue to test this out, and will use a more complex stack that includes Ambassador as well, just to make sure it's all working as expected...

**Comment by ac111** [comment]
OK, so after further testing I can confirm that the issue lies with deploying an operator that copies all secrets from "default" to any created / new namespace automatically.
I'm not yet sure why this is causing a problem, but once I deployed the operator, and recreated my test scenario, the service interaction started to fail between sleep --> httpbin.

$ kubectl exec sleep-69f8fcfdf6-mcn5k -c sleep -n foo -- curl http://httpbin.foo:8000/ip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    57  100    57    0     0   4384      0 --:--:-- --:--:-- --:--:--  4384upstream connect error or disconnect/reset before headers

$ kubectl get secret -n foo
NAME                  TYPE                                  DATA   AGE
default-token-nqqzs   kubernetes.io/service-account-token   3      3m2s
istio.default         istio.io/key-and-cert                 3      3m3s
myregistrykey         kubernetes.io/dockerconfigjson        1      3m3s

So this is interesting...

**Comment by esnible** [comment]
I suspect that the copied secrets are preventing Istio from creating secrets.

I predict that if you delete the secrets Istio will recreate them correctly.

Try:

```
kubectl -n <NAMESPACE> get secret istio.<SERVICEACCOUNT> -o yaml | grep cert-chain.pem | awk '{ print $2 }' | base64 --decode | openssl x509 -text -noout > before.txt
kubectl -n <NAMESPACE> delete secret istio.<SERVICEACCOUNT>
kubectl -n <NAMESPACE> get secret istio.<SERVICEACCOUNT> -o yaml | grep cert-chain.pem | awk '{ print $2 }' | base64 --decode | openssl x509 -text -noout > recreated.txt
diff before.txt recreated.txt
```

You can also try the same thing with "root-cert.pem" instead of "cert-chain.pem".

**Comment by yangminzhu** [comment]
I'm curious about why do you want to copy the istio generated secrets to other namespace? Why not let istio to do this for you?

**Comment by ac111** [comment]
Copying the Istio secrets via the operator was as unintended side-effect -- the operator was originally used to copy other secrets between namespaces (eg. docker registry secret, for example), which was beneficial for my company's product stack deployment.  However, this interfered with the normal operation of Istio unintentionally.
