### ISSUE TITLE
Sidecar validator port parsing regression between 1.1 rc2 and rc3.

### ISSUE THREAD

**Issue by jpittis** [istio/istio#12396]
**Describe the bug**

Below are `Sidecar` resources in two separate clusters. The `staging` cluster is running `1.1.0-rc.3` and the `production` cluster is running `1.1.0-rc.2`.

```
$ k describe sidecar web -n irs-client-staging --context staging
...
Spec:
  Egress:
    Hosts:
      irs-server-staging/*
  Ingress:
    Default Endpoint:  127.0.0.1:80
    Port:
      Number:          80
      Protocol:        TCP
    Default Endpoint:  127.0.0.1:8888
    Port:
      Number:    8888
      Protocol:  TCP
```

```
$ k describe sidecar web -n irs-client-production --context production
...
Spec:
  Egress:
    Hosts:
      irs-server-production/*
  Ingress:
    Default Endpoint:  127.0.0.1:80
    Port:
      Number:          80
      Protocol:        TCP
    Default Endpoint:  127.0.0.1:8888
    Port:
      Number:    8888
      Protocol:  TCP
```

I edit the above resources to add `istio-system/*` to their egress `Hosts` list:

```
Spec:
  Egress:
    Hosts:
      - istio-system/*
      - irs-server-production/*
```

At this point, the edit in the `production` cluster running rc2 succeeds. The edit in the `staging` cluster running rc3 fails with the following error:

```
admission webhook "pilot.validation.istio.io" denied the request: configuration is invalid: 2 errors occurred:

* invalid port name:
* invalid port name:
```

**Expected behavior**

I would expect the rc3 control plane to accept the edit successfully.

**Steps to reproduce the bug**

Create a sidecar resource using the rc3 branch with the configuration above.

**Version**

- Kubernetes `v1.11.6-gke.11`
- Istio `1.1.0-rc.2` and `1.1.0-rc.3`

**Installation**

Custom install based on the helm charts.

**Environment**

GKE

cc @mandarjog

**Comment by ymesika** [comment]
Sidecar validation has been added in #12233 between RC2 and RC3.
I believe that if you'll add port names it will become a valid sidecar but the doc doesn't specify it's required. I will check the validator.

**Comment by jpittis** [comment]
Confirming that this is the problem:

Editing the resource to the following succeeds:

```
      name: "8888"
      number: 8888
      protocol: TCP
```

As you say, the docs say not required so IMO this should be fixed to not require a `name`.

Appreciate the fast response. Thanks @ymesika.

**Comment by jpittis** [comment]
Can you think of any reason why we can't set `name` to the string of the number until this is fixed?

**Comment by jpittis** [comment]
We want to get rc3 deployed ASAP so that we can continue to fuzzy test it before release.

**Comment by ymesika** [comment]
Name, if specified, should adhere DNS-1123 name format.

**Comment by jpittis** [comment]
<3 <3 <3
