### ISSUE TITLE
istioctl  version info is not right

### ISSUE THREAD

**Issue by wuzhihui1123** [istio/istio#1240]
see below image:  
![image](https://user-images.githubusercontent.com/4246626/32046098-9a1a2bee-ba74-11e7-9f24-b70d2540cd36.png)

my istio release is : 0.2.10

---- so the problem is coming. when I apply bookinfo to kubernetes , i get the info :
![image](https://user-images.githubusercontent.com/4246626/32056889-634a613c-ba98-11e7-8f35-5a08fbf44a40.png)

docker hub :
![image](https://user-images.githubusercontent.com/4246626/32056754-149c4b2c-ba98-11e7-9116-c793a26ca490.png)

**Comment by rcurran1** [comment]
Can not reproduce. Bug seems fixed on 'release' version. Reproduce steps taken:
>curl -L https://git.io/getLatestIstio | ISTIO_VERSION=0.2.10 sh -
>cd istio-0.2.10
> ./bin/istioctl version
Version: 0.2.10
GitRevision: f27f2803f59994367c1cca47467c362b1702d605
GitBranch: release-0.2
User: sebastienvas@ee792364cfc2
GolangVersion: go1.8.3

**Comment by ldemailly** [comment]
reopen if you see it again after downloading the current version/image ?
