### ISSUE TITLE
Unable to run e2e tests on my own cluster with generate_e2e_yaml changes.

### ISSUE THREAD

**Issue by pitlv2109** [istio/istio#12403]
**Describe the bug**
Unable to run e2e tests on my own GKE cluster. I used to be able to run e2e on my own GKE cluster by following the instructions [here](https://github.com/istio/istio/blob/master/tests/e2e/UsingGKE.md). However, since we introduced `generate_e2e_yaml` and removed `generate_yaml` (maybe this PR #12076?, not sure) , it stopped working for me. It would work if I reverted back to a commit that had `generate_yaml`.

**Expected behavior**
Able to run e2e tests on my own GKE cluster.

**Steps to reproduce the bug**
Try running the `e2e_pilot` test with your own GKE cluster, be sure to set the `--cluster_wide` flag.

**Comment by utka** [comment]
@howardjohn can you look into that, is it related to your change?

**Comment by howardjohn** [comment]
What error are you getting? When I run `make e2e_pilot E2E_ARGS="--cluster_wide"` it succeeds. I am running on GKE as well.

**Comment by pitlv2109** [comment]
@howardjohn Thanks for looking into the issue, John. The issue seems to be my own `Galley` image did not start properly (similar to this #12246). When I reverted back to using `generate_yaml`, my own `Galley` worked just fine. `generate_e2e_yaml` worked if I used `gcr.io/istio-release/galley:release-1.1-latest-daily`. So I'm not sure if the issue is my `Galley` image or something else, though it worked with `generate_yaml`.

**Comment by howardjohn** [comment]
generate_yaml and generate_e2e_yaml should do the same thing, it was just a refactoring, so I don't think that is the issue. I suspect if you run the e2e tests from the head of release-1.1 with no current istio installation it would work fine.
