### ISSUE TITLE
Use envoy's jaeger native tracing support

### ISSUE THREAD

**Issue by skydoctor** [istio/istio#12400]
**Describe the feature request**
Envoy has added support for generating tracing headers using the *native* Jaeger format instead of the default Zipkin format. There should be a way for Istio users to configure the ingress/egress gateways and sidecar proxies to use that feature.

**Describe alternatives you've considered**

**Additional context**
At present Istio does support collection of traces from envoy applications via Jaeger. This works because the Jaeger collector understands both native Jaeger format as well as the Zipkin B3 format that envoy uses by default. But there are significant advantages of configuring envoy to use native Jaeger format as listed in envoy's documentation: https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/jaeger_native_tracing

- Trace propagation will work with the other services using Jaeger without needing to make configuration changes.
- A variety of different sampling strategies can be used, including probabilistic or remote where sampling can be centrally controlled from Jaeger’s backend.
- Spans are sent to the collector in a more efficient binary encoding.

It would be great if we can enable/configure this envoy feature via Istio.

**Comment by douglas-reid** [comment]
@skydoctor do you have a proposal for updating the proxy images to include the plugin?  is your proposal that istio/proxy should be pre-built with that library?  or that when configured, Istio would be responsible for distribution?

**Comment by skydoctor** [comment]
In the envoy configuration, this is done by setting the tracer type to be [dynamic.ot](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/trace/v2/trace.proto#config-trace-v2-tracing-http), and specifying the location of the library as per this [example](https://github.com/envoyproxy/envoy/blob/c61661a8144c95fd428973280907c515699c6437/examples/jaeger-native-tracing/service2-envoy-jaeger.yaml#L46).

I think it will be easiest to have the [jaeger-client-cpp library](https://github.com/jaegertracing/jaeger-client-cpp/releases/) pre-built in the proxy image - it is fairly stable and small. Otherwise, is there an easy way to copy the library to the injected sidecars? Volume-mounts are not usually used for this but perhaps that's an option?

**Comment by skydoctor** [comment]
@douglas-reid: Any thoughts on this?

**Comment by douglas-reid** [comment]
@skydoctor something to bring up at the next P&T working group meeting?

**Comment by skydoctor** [comment]
Sure. Is the next one scheduled?

**Comment by douglas-reid** [comment]
6/19 - 11 AM Pacific (sorry for the late notice, I just saw your question).  If not, two weeks after that (July 3).

**Comment by mandarjog** [comment]
@skydoctor distributing .so files is a problem that needs some discussion.
We have talked about other distribution mechanisms for WASM for example.

Enabling this feature makes sense once we figure out how to distribute those files.

**Comment by mandarjog** [comment]
@douglas-reid we need to decide if we support jaeger first class, or just enable ot dynamic tracers and support files thru volume mounts.
If jaeger is important, we should just support it directly.

**Comment by douglas-reid** [comment]
One alternative to consider: export via OpenCensus.  Deploying the OC Service configured to export to Jaeger should be possible (and already supported in Envoy).

**Comment by objectiser** [comment]
+1 I think that would be my preference too - move towards OpenTelemetry with a range of exporters (including Jaeger), rather than having to directly support those tracers.

**Comment by skydoctor** [comment]
Agree. Supporting the full list of what envoy supports would be a good start. They currently have: 

https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/trace/v2/trace.proto

-     envoy.lightstep
-     envoy.zipkin
-     envoy.dynamic.ot
-     envoy.tracers.datadog
-     envoy.tracers.opencensus

**Comment by douglas-reid** [comment]
@skydoctor as @mandarjog relates distributing .so files is a bit thorny. however, we should have support for the rest of the envoy tracers now.

I think we probably could use some documentation on opencensus and some discussion on that model of exporters (to identify any feature gaps).

**Comment by jessberg** [comment]
Are there any updates on this?  Can you use Jaeger native tracing with Istio now?
