### ISSUE TITLE
preliminary 1.1 doc for multicluster gateway has bugs on Istio installation instructions

### ISSUE THREAD

**Issue by lei-tang** [istio/istio#12405]
{{
https://preliminary.istio.io/docs/setup/kubernetes/install/multicluster/gateways/

In the section "Deploy the Istio control plane in each cluster", istio.yaml is generated but is never used to install Istio. Instead, an inconsistent way of installing Istio is provided in the document.
Moreover, the Istio installation failed due to lack of k8s RBAC configuration.

Expected behavior
{{
The istio.yaml generated in the document should be used for installing Istio. The Istio installation should succeed.
}}

Steps to reproduce the bug
{{
https://preliminary.istio.io/docs/setup/kubernetes/install/multicluster/gateways/

In the section "Deploy the Istio control plane in each cluster", istio.yaml is generated but never used to install Istio. The Istio installation failed due to lack of k8s RBAC configuration.
}}

Version
{{
istio-release-1.1-20190311-09-16
}}

Installation
{{
Follow "Before you begin"
}}

Environment
{{
~$ gcloud version
Google Cloud SDK 236.0.0
alpha 2019.02.22
app-engine-java 1.9.72
app-engine-python 1.9.83
beta 2019.02.22
bq 2.0.41
cloud-datastore-emulator 2.1.0
core 2019.02.22
gsutil 4.36
}}

Cluster state
{{ N/A }}

**Comment by howardjohn** [comment]
Looks like it is used in step 3?

> Use the Istio installation yaml file generated in a previous step to install Istio:
> 
> `$ kubectl apply -f $HOME/istio.yaml`

**Comment by lei-tang** [comment]
This issue has been fixed by the PR https://github.com/istio/istio.io/pull/3628.
