### ISSUE TITLE
istio ingressgateway http2 request stucked pending in chrome

### ISSUE THREAD

**Issue by rvgud** [istio/istio#12417]
**Describe the bug**
I have a nginx server running in kubernetes cluster and servicemesh istio. I have provided self signed certifcates to create a https-gateway(Istio ingress gateway). Whenever i make a call from google chrome browser sometimes in network tab request are being stucked in pending state. It is not a regular issue but coming randomly like out 3 out of 10 requests. In istio ingress gateway logs i can see it is being served over http2 protocol. And in proxy log of my nginx server it is being served over http1.1, So it is being transformed from http2 to http1.1 internally. All the request from curl are being serverd properly. This pending issue comes with browsers only. My google chrome browser version is v70.
I wonder if there ia any way to disable http2 on istio ingress gateway and accept only http1.1 traffic? or if there is any fix to this random issue.

**Expected behavior**
 It should serve all the request over http2. 

**Steps to reproduce the bug**
Use Self Signed certificates for istio ingress gateway. 

**Version**
 Istio: 1.0.5

**Comment by rvgud** [comment]
there is one update to this issue:- When i upgraded my nginx container to http2 it is working fine without any issue. this is because the entire call browser---> istio ingress----> nginx pod is being served on http2. and there is no transformation of protocol at istio envoy. But i have other container having spring boot in them whic basically can't be upgraded to http2(due to tls). So here lets suppose i have a micro-service m1 written in spring boot  and if make a call from browser------http2------>istio ingress-------http1.1----->m1.  here protocol transformation is taking place. And it is givign randomly pending state issue. I have also checked with curl and disable http2 flag, it is working fine in case of curl. Only browser with http2 giving issue. Which is obvious that envoy is not able to transform protocol efficiently sometimes.

Still not able to force istio ingress envoy to listen only http/1.1.

**Comment by JagadeeshSreeram** [comment]
We are running into same issue with nodejs app, where chrome uses h2 --> ingress --> envoy --> nodejs(http/1.1). And randomly some connections hang on envoy sockets goto CLOSE_WAIT . Looks like issue with envoy. As a workaround if we can make istio ingress to use http/1.1 that will work.  So, if anyone has figured out how to do that pls let me know?

**Comment by rvgud** [comment]
Just for workaround you can run your node js server to http2 only.

**Comment by JagadeeshSreeram** [comment]
@rvgud   Thanks for the quick response!  The http2 and spdy npms that nodejs support doesn't support  non-ssl http2  and if we enable http2 with ssl at nodejs we have issues exposing our other non-ssl (liberty services)  and this nodejs ssl service via single ingress gateway port.

**Comment by JagadeeshSreeram** [comment]
@rvgud   Good new! we were able to configure nodejs to support http/2 with no-ssl and make istio to talk to our service using http2 protocol in service and now things work fine.  We still used spdy npm and looks like there is an option to enable http2 without ssl. And in service definition I had to prefix name with http2 i.e.  `name: http2-myservice` after that it worked.  But I still believe there is some problem with envoy when it does protocol hop.

**Comment by montss** [comment]
@JagadeeshSreeram Could you please describe what you did exactly we are having the exact same issue, but we are using Jetty, we as well were able to configure Jetty to support http/2 with no-ssl.

By adding `RUN java -jar "$JETTY_HOME/start.jar" --create-startd --add-to-start=http2c --approve-all-licenses` to our Dockerfile

But what did you mean by "make istio to talk to our service using http2 protocol in service" ?

**Comment by JagadeeshSreeram** [comment]
@montss  Our was with nodejs, so we enabled http2 in nodejs without ssl.  about make istio talk to app using http2. I was referring to naming your service right with right protocol prefix. Istio determines the protocol based on service name prefix if specified otherwise it defaults to TCP. Here is the doc that explains it https://istio.io/docs/setup/kubernetes/prepare/requirements/

**Comment by rvgud** [comment]
@montss Simply reame your kubernetes service object's port to "http2-yourservicename". By doing this istio will always use h2 to communicate to this service.

**Comment by montss** [comment]
The port in our service/NodePort had now name at all after naming it http2 
```
ports:
  - name: http2
    nodePort: 32456
    port: 80
    protocol: TCP
    targetPort: 8080
```
Things are working fine, of course that's after enabling non-SLI HTTP/2 in jetty as well.

Thanks

**Comment by itayariel** [comment]
We also experience this issue, is there a way to make the connection end-to-end pure http1.1?
