### ISSUE TITLE
Enable trusting multiple roots of trust

### ISSUE THREAD

**Issue by myidpt** [istio/istio#12427]
**Describe the feature request**
Istio workloads need to support multiple roots of trust for migration and trust domain federation

**Describe alternatives you've considered**
No.

**Additional context**
We need to do the following:
- [ ] Support dynamically inserted trusted roots for secret volume mount.
- [ ] Support dynamically inserted trusted roots for SDS.

**Comment by howardjohn** [comment]
@lei-tang is this done from #12483 or is more work needed?

**Comment by yangminzhu** [comment]
@lei-tang @myidpt Is this still needed? There has been no update for 6 months.
