### ISSUE TITLE
Documentation mesh expansion istioctl register vs ServiceEntry

### ISSUE THREAD

**Issue by incfly** [istio/istio#12439]
- `istioctl register` creates a selectorless service, used for mesh expansion.
- `ServiceEntry` is used to model mesh expansion service discovery as well

We currently documented both in the mesh expansion doc. `istioctl` is used just to create a DNS entry for k8s svc calling out to vm services. And we'd like to use `ServiceEntry` to actually model endpoints discovery.

However, we should not encourage the same IP address in two places. I believe that result into undefined behavior, which service discovery wins in Pilot is undetermined.

This result into unintended xDS config observed for the proxy running on the VM.

**Comment by incfly** [comment]
Actually should belong to documentation, but I didn't find such a label.

**Comment by incfly** [comment]
Same thing applies for Service Definition, we should encourage the port name to match in ServiceEntry if we want to illustrate usage of istioctl to get basic DNS working.

**Comment by esnible** [comment]
@incfly Do you think this is a documentation problem, a networking problem, or a user experience problem?

**Comment by esnible** [comment]
Removing `staleproof` because I don't understand this issue.  Please add context explaining what needs to be done.
