### ISSUE TITLE
istioctl allow --envoyConfigDump as an alternate to invoking KubeExec to get the Envoy's /config_dump

### ISSUE THREAD

**Issue by incfly** [istio/istio#12437]
We can define some hook to in a `$HOME/.istioctl/config` to allow customer specify how they want to ssh/communicate with their VM instances managed by Istio mesh expansion.

istioctl can specify a target of the VM endpoint from `ServiceEntry`, invoke the hook, send the http request to the `localhost:15000` via the hook, the config and parse it, present it to end user.

This allows the same UX to people who work on mesh expansion when debugging and trouble shooting. Without this, they have to dive deeper lower level to figure out that by themselves.

**Comment by esnible** [comment]
@incfly Can you give an example of what the istioctl-specific config for mesh expansion should look like?  I don't have much experience with running Istio on VMs.

**Comment by incfly** [comment]
/no-stale-bot

Mesh expansion vm runs envoy as kubernetes pods. For this bug, `istioctl proxy-config/proxy-status`, all we need is a way to interact/access the VM machine, to get the `localhost:15000/config_dump`, that's all istioctl needs. The rest part of parsing and comparison of the config should stay the same as k8s pod.

So I think we can define a hook, for istioctl to invoke, this hook will be implemented as `gcloud compute ssh ${vm-name} -- cur localhost:15000/config_dump` for GCP, `bx xxx <vm-cmd-that-i-dont-know>` for IBM cloud.

wdyt?

**Comment by esnible** [comment]
@incfly Could we extend `proxy-config`/`proxy-status` with `--envoyDumpFile <fname>`?

If supplied, we wouldn't ask the VM machine for the configuration.  Users would do things like

```
gcloud compute ssh ${vm-name} -- cur localhost:15000/config_dump > dump.json
istioctl proxy-config bootstrap ${vm-name} --envoyDumpFile dump.json
```

Or, as a one-liner, `istioctl proxy-config bootstrap ${vm-name} --envoyDumpFile <(gcloud compute ssh ${vm-name} -- cur localhost:15000/config_dump)`

That gets all the VM handling out of _istioctl_ making it more flexible with different implementations.

**Comment by incfly** [comment]
@esnible big +1!

I like the idea, this seems much better compared with the need to interact with different VM environments.

**Comment by incfly** [comment]
Additionally, this can be generalized to more than VM, consul, cloudfoundry if they provide tooling to get the Envoy config dump. I changed the title correspondingly.

**Comment by esnible** [comment]
On the UX meeting today we decided to implement `--envoyDumpFile` for every _istioctl_ subcommand that currently uses KubeConfig or PortForward to get localhost:15000/config_dump from the sidecar.  If that argument is supplied we will not use the K8s API to perform the task.

@incfly Do you still want this item?  If not I will assign someone else.

**Comment by incfly** [comment]
@esnible I won't have bandwidth for this one. Feel free to re-assign to other folks. Thanks for triaging!

**Comment by esnible** [comment]
At the UX meeting October 8th we decided to use `istioctl proxy-config bootstrap ${vm-name} --envoyDumpFile <(gcloud compute ssh ${vm-name} -- cur localhost:15000/config_dump)`

This should be easy to test and simpler than approaches that required us to set up a running SSH tunnel and pass in the host:port of the tunnel.

**Comment by incfly** [comment]
I think we can start from `proxy-config`.

**Comment by incfly** [comment]
Thanks for making this happen!
