### ISSUE TITLE
Internal Grafana metrics aren't collected

### ISSUE THREAD

**Issue by charleskorn** [istio/istio#12438]
**Describe the bug**
[The internal metrics that Grafana exposes](http://docs.grafana.org/administration/metrics/) aren't configured in Prometheus when installing Grafana and Prometheus using the Helm chart. 

**Expected behavior**
Internal Grafana metrics are scraped by Prometheus.

**Steps to reproduce the bug**
1. Install Istio using Helm chart with `grafana.enabled=true`
2. Go to Prometheus targets list
3. Observe that Grafana container is not in the list

**Version**
Istio 1.0.5, Kubernetes 1.11.6

**Installation**
Helm chart with `grafana.enabled=true`

**Environment**
AWS, Kubernetes installed with kops

**Cluster state**
Can provide if required.

**Comment by charleskorn** [comment]
If this is a valid bug, I'm happy to provide a PR, looks like the Grafana deployment just needs a `prometheus.io/scrape: "true"` annotation.

**Comment by douglas-reid** [comment]
@charleskorn This seems like a valid issue. Thanks for identifying! Happy to review any related PR!
