### ISSUE TITLE
Need a test framework to test multi-threading behavior of Pilot.

### ISSUE THREAD

**Issue by JimmyCYJ** [istio/istio#12442]
**Describe the feature request**
This is motivated by #12432. We do not have a Pilot integration test where we can test race conditions of concurrent map writes. It would be nice if there is one test framework that covers Pilot behavior in multi-thread case. E.g. let 10 ADS clients send config requests to Pilot in parallel, and verify that the config generation does not hit any race condition in Pilot.

**Comment by JimmyCYJ** [comment]
@howardjohn @andraxylia Can networking team take this one, or close it if the framework already exists?

**Comment by howardjohn** [comment]
we have adsc which makes many connections and we do have tests with many connections so I think this is done?

**Comment by JimmyCYJ** [comment]
@howardjohn Thanks for the update. I am closing this issue now.
