### ISSUE TITLE
Revisit customer facing SDS related settings for better usability

### ISSUE THREAD

**Issue by quanjielin** [istio/istio#12444]
**Describe the feature request**
current customer facing SDS related settings includes
1. meshconfig.SdsUdsPath (meshconfig.EnableSdsTokenMount, meshconfig,SdsUseK8SSaJwt won't take effect when SdsUdsPath not set). 
2. helm values in nodeagent and global SDS.

In coming 1.2, we plan to support per-pod SDS rollout(migration) and SDS in control plane, those coming changes may bring more customer facing settings, we need to revisit those params together for clear/better usability when users adopt SDS.

**Comment by wenchenglu** [comment]
why this fix should wait till 1.2? I think these need to addressed in 1.1.x (putting aside migration), no?

**Comment by quanjielin** [comment]
1.1.x is doable(not include migration), fix will be something like - 

1. add sdsenable flag to meshconfig.
2. update istio api sha
3. add something in ValidateMeshConfig(https://github.com/istio/istio/blob/a9fe655d1d/pilot/pkg/model/validation.go).

Resolve this as dup.

**Comment by costinm** [comment]
Please don't add more to meshconfig. It's global, not friendly to upgrade
and gradual adopiton, or the new installer.

**Comment by quanjielin** [comment]
Costin, we plan to use pod annotation to decide whether to generate sds config for certain sidecar for roll out case, a global flag may still necessary for new cluster case and add uds setup for control plane component like mixer and pilot; I'm doing some prototype, will schedule a meeting with you for offline discussion, thanks.

**Comment by costinm** [comment]
Mesh config is not used by pilot sidecar and we don't plan to use it - will
likely be deprecated anyways by operator.

**Comment by quanjielin** [comment]
@costinm instead of putting global.sds flag in meshconfig, I used env instead, could you pls take a look at https://github.com/istio/istio/pull/12534? If it's ok, I will move other existing SDS fields(in meshconfig) like this later.
