### ISSUE TITLE
Can't view the bookinfo services in Jaeger UI after the latest Istio deployed

### ISSUE THREAD

**Issue by xianke9** [istio/istio#12445]
After I followed the link and installed the latest Istio into our Kubernetes platform, I checked the Istio pod status as the following:
root@m-1:~/istio-1.1.0-rc.4/samples/bookinfo# kubectl get po -n istio-system
NAME                                      READY     STATUS      RESTARTS   AGE
istio-citadel-5bf5488468-vn5w5            1/1       Running     0          12m
istio-galley-96d888b56-sxbcc              1/1       Running     0          12m
istio-ingressgateway-665ffb67b8-bz5r9     1/1       Running     0          12m
istio-ingressgateway-665ffb67b8-d8xk9     1/1       Running     0          9m
istio-init-crd-10-hgkl7                   0/1       Completed   0          13m
istio-init-crd-11-lbk6z                   0/1       Completed   0          13m
istio-init-crd-certmanager-10-9gksp       0/1       Completed   0          13m
istio-init-crd-certmanager-11-fd9w8       0/1       Completed   0          13m
istio-pilot-5f4fd55b86-4dk4m              2/2       Running     0          12m
istio-policy-5674979c46-brnsr             2/2       Running     2          12m
istio-sidecar-injector-744f68bf5f-r4c6l   1/1       Running     0          12m
istio-telemetry-577955c48d-l8j9r          2/2       Running     2          12m
istio-tracing-75dd89b8b4-kqdvq            1/1       Running     0          12m
kiali-5d68f4c676-57mz5                    1/1       Running     0          12m
prometheus-89bc5668c-q4jsm                1/1       Running     0          12m

Then I deployed the sample: bookinfo into this env. I can view the topology in Kiali, but I can't view these services in Jaeger UI, except jaeger-query.
root@m-1:~# kubectl get po
NAME                              READY     STATUS    RESTARTS   AGE
details-v1-68868454f5-stfvw       2/2       Running   0          31m
productpage-v1-5cb458d74f-lhcgt   2/2       Running   0          31m
ratings-v1-76f4c9765f-cjl8j       2/2       Running   0          31m
reviews-v1-56f6855586-85fwj       2/2       Running   0          31m
reviews-v2-65c9df47f8-tbnjj       2/2       Running   0          31m
reviews-v3-6cf47594fd-ctbbx       2/2       Running   0          31m

![kiali](https://user-images.githubusercontent.com/12079079/54255177-ef5dff00-4591-11e9-9e2e-00c2f9e65832.png)

![jaeger](https://user-images.githubusercontent.com/12079079/54255322-904cba00-4592-11e9-9421-2f2caa5647b2.png)

root@m-1:~# helm list istio --tls
NAME            REVISION        UPDATED                         STATUS          CHART                   NAMESPACE
istio           1               Wed Mar 13 00:37:55 2019        DEPLOYED        istio-1.1.0             istio-system
istio-init      1               Wed Mar 13 00:36:33 2019        DEPLOYED        istio-init-1.1.0        istio-system

root@m-1:~# helm status istio --tls
LAST DEPLOYED: Wed Mar 13 00:37:55 2019
NAMESPACE: istio-system
STATUS: DEPLOYED

RESOURCES:
==> v1/ServiceAccount
NAME                                    SECRETS  AGE
istio-galley-service-account            1        37m
istio-ingressgateway-service-account    1        37m
kiali-service-account                   1        37m
istio-mixer-service-account             1        37m
istio-pilot-service-account             1        37m
prometheus                              1        37m
istio-security-post-install-account     1        37m
istio-citadel-service-account           1        37m
istio-sidecar-injector-service-account  1        37m
istio-multi                             1        37m

==> v1/ClusterRole
NAME                                 AGE
istio-galley-istio-system            37m
istio-ingressgateway-istio-system    37m
kiali                                37m
istio-mixer-istio-system             37m
istio-pilot-istio-system             37m
prometheus-istio-system              37m
istio-citadel-istio-system           37m
istio-sidecar-injector-istio-system  37m
istio-reader                         37m

==> v1beta1/ClusterRole
istio-security-post-install-istio-system  37m

==> v1/Role
istio-ingressgateway-sds  37m

==> v1beta1/Deployment
NAME                    DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
istio-galley            1        1        1           1          37m
istio-ingressgateway    1        1        1           1          37m
kiali                   1        1        1           1          37m
istio-telemetry         1        1        1           1          37m
istio-policy            1        1        1           1          37m
istio-pilot             1        1        1           1          37m
prometheus              1        1        1           1          37m
istio-citadel           1        1        1           1          37m
istio-sidecar-injector  1        1        1           1          37m
istio-tracing           1        1        1           1          37m

==> v1beta1/PodDisruptionBudget
NAME                  MIN AVAILABLE  MAX UNAVAILABLE  ALLOWED DISRUPTIONS  AGE
istio-galley          1              N/A              0                    37m
istio-ingressgateway  1              N/A              0                    37m
istio-telemetry       1              N/A              0                    37m
istio-policy          1              N/A              0                    37m
istio-pilot           1              N/A              0                    37m

==> v1alpha2/kubernetes
NAME        AGE
attributes  37m

==> v1/ClusterRoleBinding
NAME                                                    AGE
istio-galley-admin-role-binding-istio-system            37m
istio-ingressgateway-istio-system                       37m
istio-kiali-admin-role-binding-istio-system             37m
istio-mixer-admin-role-binding-istio-system             37m
istio-pilot-istio-system                                37m
prometheus-istio-system                                 37m
istio-citadel-istio-system                              37m
istio-sidecar-injector-admin-role-binding-istio-system  37m
istio-multi                                             37m

==> v1alpha3/DestinationRule
NAME             AGE
istio-telemetry  37m
istio-policy     37m

==> v1alpha2/handler
prometheus     37m
kubernetesenv  37m

==> v1alpha2/metric
tcpconnectionsopened  37m
tcpconnectionsclosed  37m
requestduration       37m
tcpbytereceived       37m
responsesize          37m
requestsize           37m
tcpbytesent           37m
requestcount          37m

==> v1/Pod(related)
NAME                                     READY  STATUS   RESTARTS  AGE
istio-galley-96d888b56-sxbcc             1/1    Running  0         37m
istio-ingressgateway-665ffb67b8-bz5r9    1/1    Running  0         37m
kiali-5d68f4c676-57mz5                   1/1    Running  0         37m
istio-telemetry-577955c48d-l8j9r         2/2    Running  2         37m
istio-policy-5674979c46-brnsr            2/2    Running  2         37m
istio-pilot-5f4fd55b86-4dk4m             2/2    Running  0         37m
prometheus-89bc5668c-q4jsm               1/1    Running  0         37m
istio-citadel-5bf5488468-vn5w5           1/1    Running  0         37m
istio-sidecar-injector-744f68bf5f-r4c6l  1/1    Running  0         37m
istio-tracing-75dd89b8b4-kqdvq           1/1    Running  0         37m

==> v1/RoleBinding
NAME                      AGE
istio-ingressgateway-sds  37m

==> v1/Service
NAME                    TYPE          CLUSTER-IP    EXTERNAL-IP  PORT(S)                                                                                                                                     AGE
istio-galley            ClusterIP     10.0.136.225  <none>       443/TCP,15014/TCP,9901/TCP                                                                                                                  37m
istio-ingressgateway    LoadBalancer  10.0.195.59   <pending>    80:31380/TCP,443:31390/TCP,31400:31400/TCP,15029:32400/TCP,15030:31654/TCP,15031:31881/TCP,15032:30277/TCP,15443:31242/TCP,15020:31020/TCP  37m
kiali                   NodePort      10.0.218.175  <none>       20001:32193/TCP                                                                                                                             37m
istio-policy            ClusterIP     10.0.185.37   <none>       9091/TCP,15004/TCP,15014/TCP                                                                                                                37m
istio-telemetry         ClusterIP     10.0.25.95    <none>       9091/TCP,15004/TCP,15014/TCP,42422/TCP                                                                                                      37m
istio-pilot             ClusterIP     10.0.86.42    <none>       15010/TCP,15011/TCP,8080/TCP,15014/TCP                                                                                                      37m
prometheus              ClusterIP     10.0.184.211  <none>       9090/TCP                                                                                                                                    37m
istio-citadel           ClusterIP     10.0.22.15    <none>       8060/TCP,15014/TCP                                                                                                                          37m
istio-sidecar-injector  ClusterIP     10.0.29.87    <none>       443/TCP                                                                                                                                     37m
jaeger-query            NodePort      10.0.88.12    <none>       16686:30813/TCP                                                                                                                             37m
jaeger-collector        ClusterIP     10.0.148.144  <none>       14267/TCP,14268/TCP                                                                                                                         37m
jaeger-agent            ClusterIP     None          <none>       5775/UDP,6831/UDP,6832/UDP                                                                                                                  37m
zipkin                  ClusterIP     10.0.245.191  <none>       9411/TCP                                                                                                                                    37m
tracing                 ClusterIP     10.0.154.47   <none>       80/TCP                                                                                                                                      37m

==> v1beta1/MutatingWebhookConfiguration
NAME                    AGE
istio-sidecar-injector  E0313 01:14:59.160882    6762 portforward.go:303] error copying from remote stream to local connection: readfrom tcp4 127.0.0.1:43155->127.0.0.1:43156: write tcp4 127.0.0.1:43155->127.0.0.1:43156: write: broken pipe
37m

==> v1alpha2/rule
promhttp                 37m
promtcpconnectionopen    37m
promtcp                  37m
tcpkubeattrgenrulerule   37m
kubeattrgenrulerule      37m
promtcpconnectionclosed  37m

==> v1/ConfigMap
NAME                             DATA  AGE
istio-galley-configuration       1     37m
kiali                            1     37m
prometheus                       1     37m
istio-security-custom-resources  2     37m
istio                            2     37m
istio-sidecar-injector           1     37m

==> v1beta1/ClusterRoleBinding
NAME                                                   AGE
istio-security-post-install-role-binding-istio-system  37m

==> v2beta1/HorizontalPodAutoscaler
NAME                  REFERENCE                        TARGETS  MINPODS  MAXPODS  REPLICAS  AGE
istio-ingressgateway  Deployment/istio-ingressgateway  40%/80%  1        5        1         37m
istio-policy          Deployment/istio-policy          7%/80%   1        5        1         37m
istio-telemetry       Deployment/istio-telemetry       0%/80%   1        5        1         37m
istio-pilot           Deployment/istio-pilot           1%/80%   1        5        1         37m

==> v1alpha2/attributemanifest
NAME        AGE
istioproxy  37m
kubernetes  37m

NOTES:
Thank you for installing istio.

Your release is named istio.

To get started running application with Istio, execute the following steps:
1. Label namespace that application object will be deployed to by the following command (take default namespace as an example)

$ kubectl label namespace default istio-injection=enabled
$ kubectl get namespace -L istio-injection

2. Deploy your applications

$ kubectl apply -f <your-application>.yaml

For more information on running Istio, visit:
https://istio.io/

**Comment by xianke9** [comment]
![jaeger](https://user-images.githubusercontent.com/12079079/54255302-7ca15380-4592-11e9-8114-2b9ae3dc9fd7.png)

**Comment by objectiser** [comment]
Have you tried increasing the trace sampling rate? https://preliminary.istio.io/docs/tasks/telemetry/distributed-tracing/overview/#trace-sampling

**Comment by xianke9** [comment]
as you said, once I increase the sampling rate to 100, it is working fine. thank you so much!
