### ISSUE TITLE
istioctl cluster list type is wrapped in &{}

### ISSUE THREAD

**Issue by dwradcliffe** [istio/istio#12455]
**Describe the bug**
When running `istioctl proxy-config clusters <POD>` the Type field is wrapped in &{} like this:

```
SERVICE FQDN                                                                                               PORT      SUBSET     DIRECTION     TYPE
BlackHoleCluster                                                                                           -         -          -             <nil>
PassthroughCluster                                                                                         -         -          -             &{ORIGINAL_DST}
go-app-testing.anthony-test.svc.cluster.local                                                              80        -          outbound      &{EDS}
kube-dns-prometheus-discovery.kube-system.svc.cluster.local                                                10054     -          outbound      &{ORIGINAL_DST}
```

I have confirmed that istioctl binary v 1.1.0-rc.3 has the correct behavior against 1.1.0-rc.4 mesh.

**Expected behavior**
I would expect to see `EDS` instead of `&{EDS}`, etc.

Also, I would expect BlackHoleCluster to be `STATIC` not `<nil>`

**Steps to reproduce the bug**
Run `istioctl proxy-config clusters <POD>`

**Version**
istio `1.1.0-rc.4`
kubernetes `v1.11.6-gke.2`

**Installation**
Custom install via helm template

**Environment**
GKE

**Comment by esnible** [comment]
@kyessenov Why did the test case expected output change in https://github.com/istio/istio/commit/009730f1abc86ee10d530022c5d79e18fe31fa37#diff-9f9aaaf90d81f80f51dd7e71d9175a8a ?

**Comment by kyessenov** [comment]
There is a new cluster type (custom) that needs to be handled.

**Comment by esnible** [comment]
@kyessenov I'd like to add an `istioctl proxy-config cluster` test for the new cluster type.  Can you give me instructions on how to create one *or* an Envoy config_dump fragment that includes one?

**Comment by kyessenov** [comment]
@esnible It is in xDS API https://github.com/envoyproxy/data-plane-api/blob/master/envoy/api/v2/cds.proto#L100. I don't know the purpose or the history of this new extension.
