### ISSUE TITLE
Unknown value for the connection_security_policy

### ISSUE THREAD

**Issue by sethokayba** [istio/istio#12452]
**Describe the bug**
i am using istio with mTLS mode enabled. Checking communications with istioctl authn tls-check gives no conflicts for my services in the targeted namespace, but when using Prometheus to debug telemetry data, i found that the attribute connection_security_policy has a value 'unknown'. What is the signification of this status ?

**Expected behavior**
connection_security_policy should have a value of 'mutual_tls'

**Steps to reproduce the bug**
applying Policy and DestinationRule as specified in the official Istio Doc, part talking about Specific mTLS for a Namespace https://istio.io/docs/tasks/security/authn-policy/#enable-mutual-tls-per-namespace-or-service

**Version**
Istio 1.0.5
Prometheus 2.3.1
Kubernetes v1.11.3

**Installation**
Istio was installed with crds.yaml and istio-demo.yaml files

**Environment**
Linux
 
More details on : 
https://groups.google.com/forum/#!topic/kiali-users/ABzSvGT6o38

**Comment by douglas-reid** [comment]
Let's keep this discussion on the forum.  https://discuss.istio.io/t/unknown-status-on-connection-security-policy-with-prometheus/1362.  This is a known limitation for client-side metrics and there is on-going work related to it.
