### ISSUE TITLE
Gateway FQDN collides with same name(space)d Service (?)

### ISSUE THREAD

**Issue by dkrieger** [istio/istio#12469]
From what I've gathered reading issues, Gateways are given FQDNs like `name.namespace.svc.cluster.local`. If one has a Service by the same name in the same namespace -- a fairly common scenario, I'd think -- they would in theory have the same FQDN. I haven't checked  whether this applies to VirtualService as well, but in either case, it should at the very least be clearly documented on all Istio resources that have FQDNs that look like Service FQDNs. Kubernetes resources can typically share the same name so long as they are of different kinds. Ideally these resources would not be given FQDNs that look like Service FQDNs at all.

**Comment by dkrieger** [comment]
when I run an alpine image, `apk add --no-cache bind-tools`, and `host -l cluster.local`, there is no trace of gateways or virtual services -- just services, as I would have expected. Are references to `name.namespace.svc.cluster.local` as Gateway FQDN outdated? I checked on istio 1.0.6 . I'd like to avoid redundantly adding resource kind to the resource's name if possible.

**Comment by evanlouie** [comment]
Just based on some experimentation, I don't believe the FQDN is actually used when listing `gateways` for a VirtualService. Instead, it delimits on either `.` or `/`.

**If using `.` notation**, anything matching a `([^\.]+)\.([^\.]+)(\..+)?` pattern will be treated the same.  Only using the first two capture groups:

`name.namespace.svc.cluster.local` is treated the same as `name.namespace`, `name.namespace.foobar`, and `name.namespace.foo.bar.baz`.

**if using `/` notation** (as seen in https://istio.io/docs/reference/config/networking/v1alpha3/gateway/):

You will just list them as `namespace/name`

**Comment by howardjohn** [comment]
As @evanlouie mentioned, we only look at the first two segments. See https://github.com/istio/istio/blob/8476158e82721ec4929e7071eb85f26b85189241/pilot/pkg/model/config.go#L614 for the full code if you want to dig into it more.

I think this is resolved so I am going to close it out, please reopen if you have other issues
