### ISSUE TITLE
Istio Proxy producing invalid statsd metrics

### ISSUE THREAD

**Issue by michaelkipper** [istio/istio#12461]
**Describe the bug**
See: https://github.com/DataDog/datadog-agent/issues/2982

```
[ AGENT ] 2019-02-03 02:55:13 UTC | ERROR | (server.go:252 in worker) | Dogstatsd: error parsing metrics: invalid field number for "envoy.cluster.outbound|80||heapster.kube-system.svc.cluster.local.membership_total:1|g"
[ AGENT ] 2019-02-03 02:55:13 UTC | ERROR | (server.go:252 in worker) | Dogstatsd: error parsing metrics: invalid field number for "envoy.cluster.outbound|443||kubernetes-dashboard.kube-system.svc.cluster.local.membership_total:1|g"
[ AGENT ] 2019-02-03 02:55:13 UTC | ERROR | (server.go:252 in worker) | Dogstatsd: error parsing metrics: invalid field number for "envoy.cluster.outbound|443||kubernetes-dashboard.kube-system.svc.cluster.local.membership_healthy:1|g"
```

It appears that the output metrics contain pipes, which break the statsd parsing code.

**Expected behavior**
Valid stats in DataDog.

**Steps to reproduce the bug**
Set up the proxy with `--statsdUdpAddress=<ADDR>:8125`

**Version**
1.0.4 (Haven't attempted to reproduce this on 1.1.x)

**Environment**
GKE, DataDog Agent v6

**Comment by douglas-reid** [comment]
Yeah, the `|` delimiter has caused other issues before, iirc. I think it was breaking Prom export in envoy at one point as well, which is why we have our custom `stats_tags` [config](https://github.com/istio/istio/blob/master/tools/deb/envoy_bootstrap_v2.json#L18-L53).

@rshriram what your recommendation here?  how baked in is `|`?

**Comment by douglas-reid** [comment]
@rshriram is there a list of previously rejected dividers? Did we use `~` at one point?

**Comment by kyessenov** [comment]
/cc @mandarjog 
There is C++ code in proxy that parses this identifier and expects |. It needs to be taken care of.
