### ISSUE TITLE
Traces are lost when container port is not defined in deployment

### ISSUE THREAD

**Issue by dotw** [istio/istio#12486]
**Describe the bug**
Traces are not correct in jaeger. Do we have any constraint with `container port` when using tracing?

**Expected behavior**
Traces are displayed as the examples.

**Steps to reproduce the bug**
using the [bookinfo app](https://github.com/istio/istio/blob/1.0.5/samples/bookinfo/platform/kube/bookinfo.yaml) but remove the `container port` in the `deployment`.

**Version**
1.0.5 

**Installation**
using helm chart with trace enabled and sampling=100.0

**Environment**
kubenetes v1.12.4

**Cluster state**

**Comment by dotw** [comment]
snapshots
with container ports
![with cp](https://user-images.githubusercontent.com/1314173/54335092-db360280-4662-11e9-8051-9c6e952ca0a6.png)
without container ports
![without cp](https://user-images.githubusercontent.com/1314173/54335103-e38e3d80-4662-11e9-8d55-859bf8840748.png)

**Comment by douglas-reid** [comment]
I believe container ports are required for proper proxy function, including tracing. So, this is Working As Intended, I believe.

The Networking WG was looking at changing this requirement. Perhaps @andraxylia can provide comment here?

**Comment by howardjohn** [comment]
Like Doug mentioned, this is a requirement for Istio. FYI https://istio.io/docs/setup/kubernetes/prepare/requirements/
