### ISSUE TITLE
istio rbac not having an effect despite enabling RbacConfig on all namespaces & services

### ISSUE THREAD

**Issue by itsvikasgupta** [istio/istio#12496]
I have 2 services A and B in namespace dev. A is making a REST call to B. A has an API /responseTime which calls B's API /about

I am using istio 1.0.5 with mtls.

I am still new to istio RBAC but my understanding is that once RBAC is enabled on ALL namespaces and services, A shouldn't be able to talk to B right?

On applying this yaml, 

    apiVersion: "rbac.istio.io/v1alpha1"
    kind: RbacConfig
    metadata:
      name: default
    spec:
      mode: 'ON' #ON: Istio authorization is enabled for all services in the mesh.

However, it looks like A can still talk to B:

I can get a shell into A's container and make this call fine:

    curl --user user:password B:8081/about

Also, I have an istio gateway and virtualservice which is configured to hit A. After applying the RbacConfig, it is able to talk to A which talks to B just fine.

    $ curl  --user apsampleapp:apapppass!  http://${GATEWAY_URL}/responseTime
    .. 
    works as expected
    ..

Shouldn't the above curl not work since no user/service should be able to talk to either A/B?

Here's the Gateway & VirtualService yaml:

    apiVersion: networking.istio.io/v1alpha3
    kind: Gateway
    metadata:
      name: istio-authz-demo-gateway
    spec:
      selector:
        istio: ingressgateway # use istio default controller
      servers:
      - port:
          number: 80
          name: http
          protocol: HTTP
        hosts:
        - "*"
---
    apiVersion: networking.istio.io/v1alpha3
    kind: VirtualService
    metadata:
      name: istio-authz-demo
    spec:
      hosts:
      - "*"
      gateways:
      - istio-authz-demo-gateway
      http:
      - match:
        - uri:
            exact: /responseTime
        - uri:
            exact: /actuator/health
        route:
        - destination:
            host: A
            port:
              number: 8080

PS: I posted this on SO yesterday. It didn't receive any replies. So, posting it here. Hoping someone can point me in the right direction. I will be adding more details today.

**Version**
    $ istioctl version
    
    Version: 1.0.5
    GitRevision: c1707e45e71c75d74bf3a5dec8c7086f32f32fad
    User: root@6f6ea1061f2b
    Hub: docker.io/istio
    GolangVersion: go1.10.4
    BuildStatus: Clean

    $ kubectl version

    Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
    Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:00:59Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**

    AWS
    Red Hat Enterprise Linux Server release 7.6 (Maipo)

**Installation**
I used the istio-demo-auth.yaml file in the istio-1.0.5 release and did:

        $ kubectl apply -f istio-demo-auth.yaml

I injected istio-proxy using commands like:

        $ kubectl apply -f rbac/B-service-account.yaml
        $ kubectl apply -f <($ISTIO_CTL kube-inject -f rbac/B-service.yaml)
        $ kubectl apply -f <($ISTIO_CTL kube-inject -f rbac/B-deployment-with-service-account.yaml)

**Comment by pitlv2109** [comment]
Could you try this page first? https://istio.io/help/ops/security/debugging-authorization/

**Comment by vikasguptaanaplan** [comment]
I followed the steps at https://istio.io/help/ops/security/debugging-authorization/

Ensured that there is only 1 RbacConfig with the name default:

    $ kubectl get rbacconfigs.rbac.istio.io --all-namespaces
    NAMESPACE   NAME      CREATED AT
    dev         default   15h

Changed the rbac Output Level to debug.

I believe the issue is that the discovery container isn't printing any line containing rbac except this one line:

    $ kubectl logs $(kubectl -n istio-system get pods -l istio=pilot -o jsonpath='{.items[0].metadata.name}') -c discovery -n istio-system | grep rbac
    2019-03-14T05:01:29.661032Z     info    registering for apiVersion rbac.istio.io/v1alpha1

even after turning on debug.

There isn't any line containing: "built filter config for ..." etc.

**Comment by vikasguptaanaplan** [comment]
here's the cluster dump:

https://www.dropbox.com/s/kr66b7fvi5o56ah/istio-dump.tar.gz?dl=0

     curl https://raw.githubusercontent.com/istio/istio/release-1.0/tools/dump_kubernetes.sh | sh -s -- -z
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100  7837  100  7837    0     0  33370      0 --:--:-- --:--:-- --:--:-- 33491
    Fetching debug/configz from pilot
    Unable to use a TTY - input is not a terminal or the right kind of file
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100 10577    0 10577    0     0  1255k      0 --:--:-- --:--:-- --:--:-- 1291k
    Fetching debug/endpointz from pilot
    Unable to use a TTY - input is not a terminal or the right kind of file
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100 75797    0 75797    0     0  8771k      0 --:--:-- --:--:-- --:--:-- 9252k
    Fetching debug/adsz from pilot
    Unable to use a TTY - input is not a terminal or the right kind of file
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100  1069  100  1069    0     0   207k      0 --:--:-- --:--:-- --:--:--  260k
    Fetching metrics from pilot
    Unable to use a TTY - input is not a terminal or the right kind of file
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100 16759    0 16759    0     0  2622k      0 --:--:-- --:--:-- --:--:-- 2727k
    Retrieving kubernetes resource configurations
    Retrieving istio resource configurations

    fatal error: runtime: out of memory

    runtime stack:
    runtime.throw(0x17d2253, 0x16)
            /usr/local/go/src/runtime/panic.go:608 +0x72
    runtime.sysMap(0xc044000000, 0x40000000, 0x29969b8)
            /usr/local/go/src/runtime/mem_linux.go:156 +0xc7
    runtime.(*mheap).sysAlloc(0x297d180, 0x40000000, 0x0, 0x0)
            /usr/local/go/src/runtime/malloc.go:619 +0x1c7
    runtime.(*mheap).grow(0x297d180, 0x20000, 0x0)
            /usr/local/go/src/runtime/mheap.go:920 +0x42
    runtime.(*mheap).allocSpanLocked(0x297d180, 0x20000, 0x29969c8, 0x43310d)
            /usr/local/go/src/runtime/mheap.go:848 +0x337
    runtime.(*mheap).alloc_m(0x297d180, 0x20000, 0xffffffffffff0101, 0xc00006ff10)
            /usr/local/go/src/runtime/mheap.go:692 +0x119
    runtime.(*mheap).alloc.func1()
            /usr/local/go/src/runtime/mheap.go:759 +0x4c
    runtime.(*mheap).alloc(0x297d180, 0x20000, 0xc000010101, 0xc00006ff90)
            /usr/local/go/src/runtime/mheap.go:758 +0x8a
    runtime.largeAlloc(0x3ffffe00, 0x7f4366ed0101, 0x1)
            /usr/local/go/src/runtime/malloc.go:1019 +0x97
    runtime.mallocgc.func1()
            /usr/local/go/src/runtime/malloc.go:914 +0x46
    runtime.systemstack(0x0)
            /usr/local/go/src/runtime/asm_amd64.s:351 +0x66
    runtime.mstart()
            /usr/local/go/src/runtime/proc.go:1229

    goroutine 1 [running]:
    runtime.systemstack_switch()
            /usr/local/go/src/runtime/asm_amd64.s:311 fp=0xc000939278 sp=0xc000939270 pc=0x4583b0
    runtime.mallocgc(0x3ffffe00, 0x1575d40, 0xc000939301, 0xc000939350)
            /usr/local/go/src/runtime/malloc.go:913 +0x896 fp=0xc000939318 sp=0xc000939278 pc=0x40c136
    runtime.makeslice(0x1575d40, 0x3ffffe00, 0x3ffffe00, 0xc0000f6590, 0x200, 0xc0000f6590)
            /usr/local/go/src/runtime/slice.go:70 +0x77 fp=0xc000939348 sp=0xc000939318 pc=0x443067
    bytes.makeSlice(0x3ffffe00, 0x0, 0x0, 0x0)
            /usr/local/go/src/bytes/buffer.go:231 +0x6d fp=0xc000939388 sp=0xc000939348 pc=0x4eb17d
    bytes.(*Buffer).grow(0xc0008b31f0, 0x200, 0xe00)
            /usr/local/go/src/bytes/buffer.go:144 +0x16c fp=0xc0009393d8 sp=0xc000939388 pc=0x4eaadc
    bytes.(*Buffer).ReadFrom(0xc0008b31f0, 0x7f4366efe650, 0xc0007a88c0, 0xc00002e000, 0x1610a60, 0x1672b40)
            /usr/local/go/src/bytes/buffer.go:204 +0x4b fp=0xc000939448 sp=0xc0009393d8 pc=0x4eaf6b
    io/ioutil.readAll(0x7f4366efe650, 0xc0007a88c0, 0x200, 0x0, 0x0, 0x0, 0x0, 0x0)
            /usr/local/go/src/io/ioutil/ioutil.go:36 +0xb5 fp=0xc000939490 sp=0xc000939448 pc=0x5d56a5
    io/ioutil.ReadAll(0x7f4366efe650, 0xc0007a88c0, 0xc0007a88c0, 0x7f4366efe650, 0xc0007a88c0, 0xc0006f3538, 0x42ad12)
            /usr/local/go/src/io/ioutil/ioutil.go:45 +0x3e fp=0xc0009394e0 sp=0xc000939490 pc=0x5d576e
    k8s.io/kubernetes/vendor/k8s.io/client-go/rest.(*Request).DoRaw.func1(0xc000644200, 0xc00073c2d0)
            /workspace/anago-v1.13.3-beta.0.37+721bfa751924da/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/rest/request.go:819 +0x72 fp=0xc000939548 sp=0xc0009394e0 pc=0xecc172
    k8s.io/kubernetes/vendor/k8s.io/client-go/rest.(*Request).request.func2(0xc00073c2d0, 0xc0006f3648, 0xa, 0xc000740180, 0xc0006f3720, 0xc000644200, 0xc0001022a0, 0x7d, 0x0)
            /workspace/anago-v1.13.3-beta.0.37+721bfa751924da/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/rest/request.go:783 +0xca fp=0xc0009395f0 sp=0xc000939548 pc=0xecbd0a
    k8s.io/kubernetes/vendor/k8s.io/client-go/rest.(*Request).request(0xc000740180, 0xc000939720, 0x0, 0x0)
            /workspace/anago-v1.13.3-beta.0.37+721bfa751924da/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/rest/request.go:785 +0x6ac fp=0xc000939700 sp=0xc0009395f0 pc=0xec71dc
    k8s.io/kubernetes/vendor/k8s.io/client-go/rest.(*Request).DoRaw(0xc000740180, 0xc000375500, 0x19b18e0, 0xc000287000, 0x19b19e0, 0xc000656000)
            /workspace/anago-v1.13.3-beta.0.37+721bfa751924da/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/rest/request.go:818 +0xa3 fp=0xc000939798 sp=0xc000939700 pc=0xec7993
    k8s.io/kubernetes/pkg/kubectl/cmd/clusterinfo.(*ClusterInfoDumpOptions).Run.func1(0x19a9a00, 0xc00000c020, 0xc0009b2c60, 0xb, 0xc0009d0360, 0x1a, 0x0, 0x0, 0x0, 0x0, ...)
            /workspace/anago-v1.13.3-beta.0.37+721bfa751924da/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/clusterinfo/clusterinfo_dump.go:267 +0x407 fp=0xc0009398e0 sp=0xc000939798 pc=0x11bc457
    k8s.io/kubernetes/pkg/kubectl/cmd/clusterinfo.(*ClusterInfoDumpOptions).Run(0xc0000df440, 0x0, 0xc000375500)
            /workspace/anago-v1.13.3-beta.0.37+721bfa751924da/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/clusterinfo/clusterinfo_dump.go:283 +0x240 fp=0xc000939c78 sp=0xc0009398e0 pc=0x11ba4b0
    k8s.io/kubernetes/pkg/kubectl/cmd/clusterinfo.NewCmdClusterInfoDump.func1(0xc00041a280, 0x2994bf0, 0x0, 0x0)
            /workspace/anago-v1.13.3-beta.0.37+721bfa751924da/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/clusterinfo/clusterinfo_dump.go:79 +0x75 fp=0xc000939cc0 sp=0xc000939c78 pc=0x11bc015
    k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc00041a280, 0x2994bf0, 0x0, 0x0, 0xc00041a280, 0x2994bf0)
            /workspace/anago-v1.13.3-beta.0.37+721bfa751924da/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:760 +0x2cc fp=0xc000939db0 sp=0xc000939cc0 pc=0x66a36c
    k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000848f00, 0xc0002519e0, 0x12a05f200, 0xc000b53f28)
            /workspace/anago-v1.13.3-beta.0.37+721bfa751924da/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:846 +0x2fd fp=0xc000939ef0 sp=0xc000939db0 pc=0x66af0d
    k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(0xc000848f00, 0x187bed0, 0x2976160)
            /workspace/anago-v1.13.3-beta.0.37+721bfa751924da/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:794 +0x2b fp=0xc000939f20 sp=0xc000939ef0 pc=0x66abeb
    main.main()
            _output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:50 +0xf3 fp=0xc000939f98 sp=0xc000939f20 pc=0x1483603
    runtime.main()
            /usr/local/go/src/runtime/proc.go:201 +0x207 fp=0xc000939fe0 sp=0xc000939f98 pc=0x42d927
    runtime.goexit()
            /usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc000939fe8 sp=0xc000939fe0 pc=0x45a311

    goroutine 5 [chan receive]:
    k8s.io/kubernetes/vendor/k8s.io/klog.(*loggingT).flushDaemon(0x29764e0)
            /workspace/anago-v1.13.3-beta.0.37+721bfa751924da/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:941 +0x8b
    created by k8s.io/kubernetes/vendor/k8s.io/klog.init.0
            /workspace/anago-v1.13.3-beta.0.37+721bfa751924da/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:403 +0x69

    goroutine 6 [syscall]:
    os/signal.signal_recv(0x0)
            /usr/local/go/src/runtime/sigqueue.go:139 +0x9c
    os/signal.loop()
            /usr/local/go/src/os/signal/signal_unix.go:23 +0x22
    created by os/signal.init.0
            /usr/local/go/src/os/signal/signal_unix.go:29 +0x41

    goroutine 9 [select]:
    k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x187de18, 0x12a05f200, 0x0, 0x1, 0xc00004afc0)
            /workspace/anago-v1.13.3-beta.0.37+721bfa751924da/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:145 +0x147
    k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0x187de18, 0x12a05f200, 0xc00004afc0)
            /workspace/anago-v1.13.3-beta.0.37+721bfa751924da/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
    created by k8s.io/kubernetes/pkg/kubectl/util/logs.InitLogs
            /workspace/anago-v1.13.3-beta.0.37+721bfa751924da/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/util/logs/logs.go:51 +0x89

    goroutine 17 [IO wait]:
    internal/poll.runtime_pollWait(0x7f4366ed1e30, 0x72, 0xc00063e870)
            /usr/local/go/src/runtime/netpoll.go:173 +0x66
    internal/poll.(*pollDesc).wait(0xc0004f4b98, 0x72, 0xffffffffffffff00, 0x19ab480, 0x27c9578)
            /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
    internal/poll.(*pollDesc).waitRead(0xc0004f4b98, 0xc000534000, 0x8000, 0x8000)
            /usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
    internal/poll.(*FD).Read(0xc0004f4b80, 0xc000534000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
            /usr/local/go/src/internal/poll/fd_unix.go:169 +0x179
    net.(*netFD).Read(0xc0004f4b80, 0xc000534000, 0x8000, 0x8000, 0x408a7b, 0xc00002e000, 0x1610a60)
            /usr/local/go/src/net/fd_unix.go:202 +0x4f
    net.(*conn).Read(0xc00000c010, 0xc000534000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
            /usr/local/go/src/net/net.go:177 +0x68
    crypto/tls.(*block).readFromUntil(0xc0005a7620, 0x19a95c0, 0xc00000c010, 0x5, 0xc00000c010, 0x0)
            /usr/local/go/src/crypto/tls/conn.go:492 +0x89
    crypto/tls.(*Conn).readRecord(0xc000062700, 0x187e817, 0xc000062820, 0x187e848)
            /usr/local/go/src/crypto/tls/conn.go:593 +0xdd
    crypto/tls.(*Conn).Read(0xc000062700, 0xc000888000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
            /usr/local/go/src/crypto/tls/conn.go:1145 +0xf1
    bufio.(*Reader).Read(0xc000822360, 0xc00015a578, 0x9, 0x9, 0x7fb8b0, 0x42de3c, 0xc00063ec50)
            /usr/local/go/src/bufio/bufio.go:216 +0x22f
    io.ReadAtLeast(0x19a6ca0, 0xc000822360, 0xc00015a578, 0x9, 0x9, 0x9, 0x187e848, 0xc00063ecf0, 0xc00063ece0)
            /usr/local/go/src/io/io.go:310 +0x88
    io.ReadFull(0x19a6ca0, 0xc000822360, 0xc00015a578, 0x9, 0x9, 0xc000958000, 0x1000, 0x4000)
            /usr/local/go/src/io/io.go:329 +0x58
    k8s.io/kubernetes/vendor/golang.org/x/net/http2.readFrameHeader(0xc00015a578, 0x9, 0x9, 0x19a6ca0, 0xc000822360, 0x0, 0x0, 0x0, 0x0)
            /workspace/anago-v1.13.3-beta.0.37+721bfa751924da/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/frame.go:237 +0x7b
    k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc00015a540, 0xc040f47380, 0x0, 0x0, 0x0)
            /workspace/anago-v1.13.3-beta.0.37+721bfa751924da/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/frame.go:492 +0xa3
    k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*clientConnReadLoop).run(0xc00063efb8, 0x187d280, 0xc00005a7b8)
            /workspace/anago-v1.13.3-beta.0.37+721bfa751924da/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/transport.go:1477 +0x9e
    k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*ClientConn).readLoop(0xc0000f6540)
            /workspace/anago-v1.13.3-beta.0.37+721bfa751924da/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/transport.go:1405 +0x76
    created by k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*Transport).newClientConn
            /workspace/anago-v1.13.3-beta.0.37+721bfa751924da/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/transport.go:592 +0x60d
    Retrieving logs for copy_core_dumps_if_istio_proxy//
    error: You must provide one or more resources by argument or filename.
    Example resource specifications include:
       '-f rsrc.yaml'
       '--filename=rsrc.json'
       '<resource> <name>'
       '<resource>'
    error: resource name may not be empty
    sh: line 108: [: : integer expression expected
    Wrote ./istio-dump.tar.gz
    Wrote to istio-dump
    sh: line 283: return: tap_containers: numeric argument required

**Comment by vikasguptaanaplan** [comment]
I created a separate bug for the OOM error in the cluster state collection tool:

https://github.com/istio/istio/issues/12510

**Comment by yangminzhu** [comment]
Istio 1.0 is no longer supported: https://istio.io/blog/2019/announcing-1.0-eol-final/, could you try about newer version? (Istio 1.1 or 1.2) Thanks.

**Comment by incfly** [comment]
Closing as @yangminzhu suggests 1.0 is no longer supported, please file separate bug if you observe this in newer version that we supports.
