### ISSUE TITLE
Update gateways chart to list port 15443 (or some other always-on port) first in Service entries

### ISSUE THREAD

**Issue by venezia** [istio/istio#12503]
**Describe the feature request**
Update helm chart (or other possible vectors of installing istio) such that 15443 is the first port listed in the `ingressgateway` kubernetes service.

**Describe alternatives you've considered**
Out-of-band updating health check on ELB, is not fun

**Additional context**
In AWS environment, the first port on a service record is used for a health check.  In a default istio environment, the ingressgateway's behavior on port 80 is to reject connections (until a VirtualService references the ingressgateway at port 80) - this will result in the ELB showing up as unhealthy when this really is not the case.

In Istio 1.1, multicluster service meshes can be created on an AWS environment.  A remote server may not be exposing any "public" services through the ingress gateway, but might allow connections in through port 15443 for the mutual TLS connection between istio control planes.

Such an environment could be "configured as intended" not actually working "correctly" because the ingressgateway service will be down (as far as ELB health checks are concerned) because the ELB health check is looking for valid TCP connections on port 80 (by default)

The user experience might be lacking, as a person might get frustrated that examples in the documentation are not working, etc. and not appreciate that the problem is with the ELB's health check.

Whatever is listed as the first port in a Service of type LoadBalancer in an AWS cloud enabled environment is picked to be the port used for health checks.  If 15443 will always accept connections (or some other port) it would be desirable to list this port first for AWS customers

In other words, let's try to enhance the helm charts so that AWS customers will not be frustrated with their istio experience.

**Comment by nrjpoddar** [comment]
Thanks for filing this @venezia. We had similar problems and was quite painful to pin down the issue. I have a PR out to address this.

**Comment by nrjpoddar** [comment]
This can be closed as 1.1.3 has the fix.

**Comment by TqrHsn** [comment]
How to disable 15020 to be exposed from cluster? In our scenario we cannot expose any ports other than 443.

**Comment by iusergii** [comment]
> How to disable 15020 to be exposed from cluster? In our scenario we cannot expose any ports other than 443.

Same here. @nrjpoddar Is it possible?

**Comment by nrjpoddar** [comment]
@TqrHsn @iusergii AWS health check only requires that the first port be available and should be receiving connections. If you're only using `443`, update your [Helm chart values file](https://github.com/istio/istio/blob/a0d57801554ce44cebac868fbc818a7ed4bdb43c/install/kubernetes/helm/istio/values.yaml) and override this subchart value https://github.com/istio/istio/blob/a0d57801554ce44cebac868fbc818a7ed4bdb43c/install/kubernetes/helm/istio/charts/gateways/values.yaml#L60 to only have port `443`.

**Comment by sshishov** [comment]
Hey, I am not a professional here. But is it good practice to open some random port to the public just to have health-check? What if this port or SW running on this port have vulnerabilities? Also to have LB healthy without any VirtualService running behind it is not what is considered a healthy environment. If you do not have consumers of your request, how the stack can be healthy? Did I miss something here?

**Comment by su225** [comment]
#33090 - custom logic for strategic merge patch by port and protocol. Keeping 15021 and 15020 as the first two because of this issue. (This comment is for reference only)
