### ISSUE TITLE
Add mixer e2e test to cover out of process adapter feature

### ISSUE THREAD

**Issue by bianpengyuan** [istio/istio#12506]
An e2e test is needed to cover mixer out of process code path. Propose to replicate at least two test cases from the current mixer e2e suite: one for report with an oop prometheus adapter, and one for an oop check adapter. If we have an example route directive adapter, we could also add a case for that to exercise out of process decoding code path.

cc @douglas-reid @kyessenov

**Comment by kyessenov** [comment]
Adding OOP route direct adapter with https://github.com/istio/istio/pull/12505

**Comment by douglas-reid** [comment]
what is left for this issue now that #12577 and #12505 have merged ?

**Comment by bianpengyuan** [comment]
I am trying to add an end to end test for policy oop adapter in the new test framework. It's simple and almost done since there is already a fake policy backend talking template api.

We should also introduce an end to end test for oop route directive adapter added by kuat, though not sure how hard it would be to add it with the new test framework, maybe we could add the functionality into the fake policy backend.
