### ISSUE TITLE
Clearer signal the test phases in e2e-tests with durations in log

### ISSUE THREAD

**Issue by yutongz** [istio/istio#1251]
Golang library to signal the following test phases: Test setup, test run and Test teardown
Min requirements: golang should log the following phases
*Setup Started
*Setup Done + time
*Run Started
*Run Completed + time
*Teardown started
*Teardown Completed + time 

cc @gnirodi

**Comment by hklai** [comment]
Looks obsolete. Please reopen if this is still applicable.
