### ISSUE TITLE
IDEA: Batch/offline Pilot

### ISSUE THREAD

**Issue by esnible** [istio/istio#12523]
This idea comes from a conversation between myself and @elevran as well as a comment from @nmittler https://github.com/istio/istio/issues/9504#issuecomment-473342916

The idea is to create an "offline Pilot".

We could feed the output of `dump_kubernetes.sh` to the tool and it would generate Envoy configuration for debugging problems that needed a dump.

You could also feed it the current system state and it could produce an Envoy configuration that could be mounted into a sidecar.  This might be good for very short-lived pods, and let them run without a control plane.

It could also help developers troubleshoot their Deployment descriptors without a live K8s cluster.

This could be an extension to _pilot-discovery_ or a new CLI.

**Comment by linsun** [comment]
This is interesting idea. when troubleshooting pilot issues, I had to run it in k8s today and takes a lot of time and sometimes requires step through the code.

**Comment by esnible** [comment]
Thanks @linsun .  I have been talking with @mbanikazemi about this idea.  There is a lot of checking in pilot-discovery that could be leveraged for testing.  We also hope to write further checking in Pilot so that Pilot stops generating configuration that Envoy rejects and eliminating STALE sidecars.

Once such validation is in place in pilot-discovery it would be easy to run pilot discovery on a set of resources, then again with the existing resources merged with additional resources.  If supplying additional resources leads to invalid Envoy configuration being generated we could flag the new configuration as leading to an invalid Istio system state.
