### ISSUE TITLE
Ubuntu as Istio base image

### ISSUE THREAD

**Issue by wattli** [istio/istio#12527]
Reported by a customer:

"Istio is using ubuntu 16.04 with a full 150MB operating container which
is expanded to a 5 GB system disk.

This is much to much for a sidecar running in every pod.

You should find a solution with statically linked code. Envoy is already
statically linked. Please repeat it also for the pilot application and other programs needed
in the init container."

**Comment by wattli** [comment]
The ubuntu image was defined here: https://github.com/istio/istio/blob/d93e9eb86a104c77275e84077fd20435ab1c9cfa/docker/Dockerfile.xenial_debug#L1

It's been here for a while and I put it as a P1 for 1.2, but I would like to hear feedbacks.

@mandarjog @duderino for information.

**Comment by loewenstein** [comment]
See https://github.com/istio/istio/issues/12122 as well. We are currently looking into https://github.com/GoogleContainerTools/distroless for Envoy and later Istio images.

**Comment by howardjohn** [comment]
We have support for distroless now. See https://github.com/istio/istio/issues/12122. I think this can be closed?
