### ISSUE TITLE
galley log says authorizationpolicies.rbac.istio.io/v1alpha1 resource type not found

### ISSUE THREAD

**Issue by kylebevans** [istio/istio#12535]
**Describe the bug**
The istio-galley, istio-pilot, and istio-policy pods all go into a crash loop.  I think the cause is related to these errors in the galley log:

```
2019-03-15T19:49:33.102258Z	info	kube	authorizationpolicies.rbac.istio.io/v1alpha1 resource type not found
2019-03-15T19:49:34.102430Z	info	kube	authorizationpolicies.rbac.istio.io/v1alpha1 resource type not found
2019-03-15T19:49:34.103557Z	info	kube	authorizationpolicies.rbac.istio.io/v1alpha1 resource type not found
2019-03-15T19:49:34.103583Z	fatal	Unable to initialize Galley Server: timed out waiting for the condition: the following resource type(s) were not found: [authorizationpolicies]
```

The errors in the pilot log are:

```
2019-03-15T19:57:15.955346Z	info	mcp	(re)trying to establish new MCP sink stream
2019-03-15T19:57:15.955440Z	error	mcp	Failed to create a new MCP sink stream: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 172.20.216.107:9901: connect: connection refused"
2019-03-15T19:57:16.955613Z	info	mcp	(re)trying to establish new MCP sink stream
2019-03-15T19:57:16.955702Z	error	mcp	Failed to create a new MCP sink stream: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 172.20.216.107:9901: connect: connection refused"
2019-03-15T19:57:17.534246Z	info	pickfirstBalancer: HandleSubConnStateChange: 0xc4204bd8c0, CONNECTING
2019-03-15T19:57:17.955922Z	info	mcp	(re)trying to establish new MCP sink stream
```

The errors in the policy log are:

```
2019-03-15T20:03:33.585556Z	info	mcp	  [32] istio/config/v1alpha2/legacy/bypasses
2019-03-15T20:03:33.585565Z	info	mcp	  [33] istio/config/v1alpha2/legacy/checknothings
2019-03-15T20:03:33.585570Z	info	mcp	  [34] istio/config/v1alpha2/legacy/fluentds
2019-03-15T20:03:33.585575Z	info	mcp	  [35] istio/config/v1alpha2/legacy/memquotas
2019-03-15T20:03:33.585579Z	info	mcp	  [36] istio/policy/v1beta1/rules
2019-03-15T20:03:33.585600Z	info	parsed scheme: ""
2019-03-15T20:03:33.585613Z	info	scheme "" not registered, fallback to default scheme
2019-03-15T20:03:33.585698Z	info	Using new MCP client sink stack
2019-03-15T20:03:33.585745Z	info	Awaiting for config store sync...
2019-03-15T20:03:33.585809Z	info	mcp	(re)trying to establish new MCP sink stream
2019-03-15T20:03:33.585833Z	info	ccResolverWrapper: sending new addresses to cc: [{istio-galley.istio-system.svc:9901 0  <nil>}]
2019-03-15T20:03:33.585845Z	info	ClientConn switching balancer to "pick_first"
2019-03-15T20:03:33.585908Z	info	pickfirstBalancer: HandleSubConnStateChange: 0xc420499960, CONNECTING
2019-03-15T20:03:33.585913Z	info	blockingPicker: the picked transport is not ready, loop back to repick
```

**Expected behavior**
I expected all of the containers to run.  I have another cluster where everything is working normally.

**Steps to reproduce the bug**
I am not sure of the exact steps to reproduce.

**Version**
1.1.0 installed from the 1.1.0 chart
kubectl: 1.11.8 EKS

**Installation**
helm chart from istio.io repository

**Environment**
AWS EKS

**Comment by kylebevans** [comment]
I had to add this CRD, which is CRD-12 here: istio/install/kubernetes/helm/istio-init/files/crd-12.yaml
However, I think that still needs to make it into the istio-init helm chart.

```
kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1beta1
metadata:
  name: authorizationpolicies.rbac.istio.io
  labels:
    app: istio-pilot
    istio: rbac
    heritage: Tiller
    release: istio
spec:
  group: rbac.istio.io
  names:
    kind: AuthorizationPolicy
    plural: authorizationpolicies
    singular: authorizationpolicy
    categories:
      - istio-io
      - rbac-istio-io
  scope: Namespaced
  version: v1alpha1
```

**Comment by yangminzhu** [comment]
How are you installing Istio? We just added the authorizationpolicy, maybe we missed some place for the installation.

/cc @ozevren

**Comment by kylebevans** [comment]
Using the helm charts in the Istio.io helm repo.

**Comment by zimmertr** [comment]
I can confirm I'm effected by this issue as well. Using the Helm Template install solution to an EKS cluster.

**Comment by yangminzhu** [comment]
I have sent out a PR to fix this, meanwhile you can manually apply the
crd-12.yaml to solve it.

**Comment by ozevren** [comment]
@kylebevans are you sure that this is a 1.1 installation? Galley should not be looking for AuthorizationPolicies in 1.1.

**Comment by kylebevans** [comment]
Yes, installed from the istio.io helm repo.  Perhaps that repo is sourced from the absolute latest version.  To be honest, it would be nice if there was a helm repo for the stable version.

Here is the output from helm list:
```
NAME      	REVISION	UPDATED                 	STATUS  	CHART           	APP VERSION	NAMESPACE   
istio     	4       	Fri Mar 15 14:41:54 2019	DEPLOYED	istio-1.1.0     	1.1.0      	istio-system
istio-init	3       	Fri Mar 15 18:05:51 2019	DEPLOYED	istio-init-1.1.0	1.1.0      	istio-system
```

**Comment by ozevren** [comment]
/cc @costinm @sdake. I am not sure how the helm repos are setup, but if I am not mistaken, the charts are showing as 1.1, even though they seem to be coming from master. 

Can you guys update the version numbers so that it is explicit that the installations are coming from master?

**Comment by yangminzhu** [comment]
@costinm @sdake, I have another question, does it mean we could potentially break the 1.1 installation with change committed to `master` branch? This doesn't seem right and we need to fix it as we're releasing 1.1 very soon, thoughts?

**Comment by zimmertr** [comment]
I'm still experiencing this issue when installing Istio by generating a template with Helm sourced from this command:

`curl -L https://git.io/getLatestIstio | ISTIO_VERSION=1.1.0 sh -`

**Comment by yangminzhu** [comment]
@zimmertr I just tried and installed successfully, could you paste the contents of the yaml you used to install istio?

**Comment by sdake** [comment]
Before we do anything drastic like backport this to 1.1.1 - it seems we need to verify it is actually a 1.1.1 problem.

@kylebevans can you paste the output of:
```
sdake@beast-01:~$ helm repo list
```

Cheers
-steve

**Comment by sdake** [comment]
@kylebevans can you also paste a describe of one of your containers (galley, pilot, any willl do)

e.g.
```
kubectl describe pod galley-UUID -n istio-system
```

Cheers
-steve

**Comment by zimmertr** [comment]
Sure, I'm using an Ansible Role that looks like this:
```
- name: Downloading Istio.
  shell: cd /tmp && curl -L https://git.io/getLatestIstio | ISTIO_VERSION={{ istio_version }} sh -

- name: Generating the manifest for the Istio CRDs.
  shell: helm template /tmp/istio-{{ istio_version }}/install/kubernetes/helm/istio-init --name istio-init --namespace istio-system > /tmp/istio-{{ istio_version }}/istio-init.yml

- name: Generating the manifest for remaining Istio assets.
  shell: helm template /tmp/istio-{{ istio_version }}/install/kubernetes/helm/istio --name istio --namespace istio-system > /tmp/istio-{{ istio_version }}/istio.yml

- name: Creating a namespace for Istio.
  k8s: 
      name: istio-system
      api_version: v1
      kind: Namespace
      kubeconfig: /mnt/data/existing_platforms/{{ platform }}/kubeconfig

- name: Deploying the CRDs for Istio.
  shell: kubectl apply -f /tmp/istio-{{ istio_version }}/istio-init.yml --kubeconfig /mnt/data/existing_platforms/{{ platform }}/kubeconfig

- name: Deploying the remaining assets for Istio.
  shell: kubectl apply -f /tmp/istio-{{ istio_version }}/istio.yml --kubeconfig /mnt/data/existing_platforms/{{ platform }}/kubeconfig
  register: result
  retries: 5
  delay: 60
  until: result is succeeded
  
- name: Deleting the temporary Istio files.
  file: 
      path: /tmp/istio-{{ istio_version }}
      state: absent
```

Which produces and applies the following files:

[istio-init.yml](https://gist.githubusercontent.com/zimmertr/56a1599bde1b1e0ed99e26ef1a08be80/raw/fbff870765abd1280c29e92695ce16e3ad02fccb/istio-init.yml)
[istio.yml](https://gist.githubusercontent.com/zimmertr/4ad5380b19ab1e61fef45f16c22f5434/raw/8b8c62781af971a7d15e6833183cc73a2374a9b6/istio.yml)

Which I unfortunately have to apply using the `shell` module instead of the `k8s` module because they contain several trailing `---` entries which breaks Ansible.

**Comment by sdake** [comment]
@zimmertr can you paste the output of a describe operatiion on one of your containers (such as galley or pilot)?

Thanks
-steve

**Comment by zimmertr** [comment]
I have since manually applied the CRD from the above described manifest and redeployed the failed pods. So that may have tainted my describe. But [here](https://gist.githubusercontent.com/zimmertr/f03e46a4522341901c56bcbd1cf5aae4/raw/3ec40b14e1ee6d3c860d432352b852d402a1a1ff/istio-galley-694f4bd7bd-svsm7) is the Galley.

**Comment by sdake** [comment]
This is a problem

```
Image:         gcr.io/istio-release/galley:master-latest-daily
```
The manifest (istio.yaml) clearly specify 1.1.0 yet yoursystem is clearly running a daily release.  The daily releases are of master.

Additionally you need some type of sync step in your Ansible script to wait for crds to register.

Cheers
-steve

**Comment by zimmertr** [comment]
The syncing of the CRDs is addressed by:
```
  register: result
  retries: 5
  delay: 60
  until: result is succeeded
```

The shell module will instruct Ansible to report a failure unless all of the manifests apply successfully. This attempts an apply, fails, waits 60 seconds, attempts another apply, etc. Until all have succeeded. 

As for the galley image being the nightly release, I'm unsure why that is happening as well. It doesn't seem like user error though unless I'm mistaken?

**Comment by sdake** [comment]
@zimmertr CRD application is asynchronous, therefore, it is possible to report a result of success while the CRDs are not yet committed to the API server.  I believe this is being resolved in 1.14, but it is still racey at this time.

It is difficult to say why this is happening in your case.  your manifest clearly states 1.1.0 for images, yet your running master images.

**Comment by sdake** [comment]
Here are the results of the GetIstio shell step:

```
sdake@beast-01:~$ curl -L https://git.io/getLatestIstio | ISTIO_VERSION=1.1.0 sh -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  1631  100  1631    0     0   1681      0 --:--:-- --:--:-- --:--:--  1681
Downloading istio-1.1.0 from https://github.com/istio/istio/releases/download/1.1.0/istio-1.1.0-linux.tar.gz ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   614    0   614    0     0   1216      0 --:--:-- --:--:-- --:--:--  1215
100 15.0M  100 15.0M    0     0  2056k      0  0:00:07  0:00:07 --:--:-- 2766k
Downloaded into istio-1.1.0:
bin  install  istio.VERSION  LICENSE  README.md  samples  tools
Add /home/sdake/istio-1.1.0/bin to your path; e.g copy paste in your shell and/or ~/.profile:
export PATH="$PATH:/home/sdake/istio-1.1.0/bin"
```


This downloads istio 1.1.0 to $HOME/istio-1.1.0.  In this case, the Ansible is running helm template against files in /tmp.  My guess is the files in /tmp contain the master-latest-daily images.
```
- name: Deploying the CRDs for Istio.
  shell: kubectl apply -f /tmp/istio-{{ istio_version }}/istio-init.yml --kubeconfig /mnt/data/existing_platforms/{{ platform }}/kubeconfig
```

Cheers
-steve

**Comment by zimmertr** [comment]
As I'm sure you know the curl command is downloading to your home directory because you're currently within that directory. My Ansible command instructs curl to download to `/tmp` by first changing into that directory.

```
$> ls /tmp/ | grep istio

$> ansible-playbook test.yml
 [WARNING]: Unable to parse /etc/ansible/hosts as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAY [localhost] ******************************************************************************************************************************************************************

TASK [Downloading Istio.] *********************************************************************************************************************************************************
changed: [localhost]

TASK [Generating the manifest for the Istio CRDs.] ********************************************************************************************************************************
changed: [localhost]

TASK [Generating the manifest for remaining Istio assets.] ************************************************************************************************************************
changed: [localhost]

PLAY RECAP ************************************************************************************************************************************************************************
localhost                  : ok=3    changed=3    unreachable=0    failed=0


$> ls /tmp/ | grep istio
istio-1.1.0
```

**Comment by zimmertr** [comment]
I just reran everything from scratch and it looks like 1.1.0 was deployed instead of latest. And everything is stable. I guess this was user error somehow after all. Thank you for your help in troubleshooting this.

**Comment by sdake** [comment]
@zimmertr it would be great to get to a root cause, but if your running, that is a good first step.

Cheers
-steve

**Comment by sdake** [comment]
@kylebevans problem is not yet resolved.  This OPs problem may be different than @zimmertr.

**Comment by kylebevans** [comment]
This was my mistake. My istio.io repo was installed with this as the url: https://storage.googleapis.com/istio-prerelease/daily-build/master-latest-daily/charts

I changed it to: https://gcsweb.istio.io/gcs/istio-release/releases/1.1.0/charts/
and that seems correct.

**Comment by sdake** [comment]
@kylebevans we have work in progress to improve the docs here.  In the past the docs may have indicated istio-prerrelease for preliminary, while instead the release docs may not mention the helm location at all.

Thank you for your contributions in helping us sort out this problem.

Cheers
-steve
