### ISSUE TITLE
Ingress gateway idle timeout

### ISSUE THREAD

**Issue by vadimi** [istio/istio#12533]
**Describe the bug**
We're running istio ingress as `DaemonSet` in AWS EKS. We also have AWS ALB in front of the ingress. Everything is working fine until kubernetes drops connections to ALB due to `--conntrack-tcp-timeout-established` timeout configured in kube-proxy (https://kubernetes.io/docs/reference/command-line-tools-reference/kube-proxy/), 24 hours by default. After that when we make requests to our apps AWS ALB returns 502 errors a few times and establishes new connections. It happens because AWS ALB never closes existing connections and istio ingress (envoy) doesn't have idle timeout configured either which means it never expires those connections. AWS ALB has idle timeout settings which are only applicable to client connections, not the backend ones. I was able to patch pilot to configure idle timeout in istio gateway and 502 errors disappeared. 

Maybe I'm missing something in the configuration - is there a way to configure idle timeout in istio ingress? If not, I'd like to contribute a PR to make sure it's configurable. Should I add new config item to `https://github.com/istio/api/blob/master/mesh/v1alpha1/config.proto`?

**Expected behavior**
Istio ingress allows configuring idle timeout to gracefully close connections to the AWS load balancer.

**Steps to reproduce the bug**
Run istio ingress as DaemonSet, enable AWS ALB in front of it, make a request to the app, wait for the `--conntrack-tcp-timeout-established` timeout configured in kube-proxy, retry the request.

**Version**
`AWS EKS 1.11.5`
`Istio 1.0.6`

**Installation**
generated yaml files from the helm templates, kubectl apply ...

**Environment**
AWS EKS

**Comment by howardjohn** [comment]
Related pr: https://github.com/istio/istio/pull/13515

**Comment by Liv1020** [comment]
I also meet this bug on aliyun slb, How to fix?

**Comment by howardjohn** [comment]
It is confiurable, you can set ISTIO_META_IDLE_TIMEOUT env var on the gateway

**Comment by howardjohn** [comment]
Fixed  by #13515.

If that doesn't satisfy the requirement let me know and we can reopen this

**Comment by vadimi** [comment]
It’s working perfectly fine, thank you.

**Comment by jdomag** [comment]
@vadimi @howardjohn 
Can you guys share how to set this for istio ingress? Is it possible to add it somewhere in the istio profile definition?
