### ISSUE TITLE
install instruction in preliminary 1.1 does not work

### ISSUE THREAD

**Issue by silentdai** [istio/istio#12531]
**Describe the bug**
https://preliminary.istio.io/docs/setup/kubernetes/download/
I am try to download the latest 1.1.0-rc5 following instruction [here](https://preliminary.istio.io/docs/setup/kubernetes/download/#download-and-prepare-for-the-installation) but it report error

The reason is that 1.1.0 is not submitted to https://api.github.com/repos/istio/istio/releases/latest 
To maintain the compatibility with 1.0 instruction, I suggest 
- modify `https://git.io/getLatestIstio`. It should work when submit 1.1.0 prerelease in step 2
- submit 1.1.0 to github release, with an attribute `prerelease = true`
- modify 1.1.0 doc

Alternatively we can provide a new https://git.io/getLatestIstio-*1.1* to avoid other usage of getLatestIstio

**Expected behavior**
Download 1.1.0-rc5

**Steps to reproduce the bug**
$ curl -L https://git.io/getLatestIstio | ISTIO_VERSION=1.1.0 sh -

**Version**
1.1

**Installation**
This is the thing. Cannot install.

**Environment**
linux but it would fail on mac as well.

**Cluster state**
N/A

**Comment by howardjohn** [comment]
I think the docs are just meant for the real release not prereleases

**Comment by dwradcliffe** [comment]
This is somewhat duplicate of https://github.com/istio/istio.io/issues/3325

Your original steps would have worked if you used the actual pre-release version `1.1.0-rc.5`. So: `curl -L https://git.io/getLatestIstio | ISTIO_VERSION=1.1.0-rc.5 sh -` does work.

**Comment by esnible** [comment]
This is how I do it:

```
CANDIDATE=1.1.0-rc.5
curl -L https://git.io/getLatestIstio \
   | ISTIO_VERSION=$CANDIDATE sh -
cd istio-$CANDIDATE
```

**Comment by silentdai** [comment]
Thank you for the comments. I assumed we should avoid user do extra homework to find the latest prerelease tag.
It's reasonable if we explicitly list the latest tag in doc. 
Close this one as it duplicate istio/istio.io#3325.

**Comment by dwradcliffe** [comment]
You're right, for the pre-release site it would be better to show the latest rc version tag. Feel free to open an issue on that repo. 😄
