### ISSUE TITLE
ProxyConfig.InterceptionMode of NONE does not disable iptables interception

### ISSUE THREAD

**Issue by mdgreenfield** [istio/istio#12543]
**Describe the bug**
I'm trying to enable whitebox mode for istio by setting `.ProxyConfig.InterceptionMode` to `NONE` in the `istio` ConfigMap. However, doing so does not disable the `istio-init` `initContainer` in the sidecar injector.

**Expected behavior**
I believe that setting `.ProxyConfig.InterceptionMode` to `NONE` should disable the init container and therefore iptables redirect configuration. https://github.com/istio/istio/blob/c386865bda31bd3d6580520e496e31ef787d04a8/install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml#L20

**Steps to reproduce the bug**
1. Configure `interceptionMode: NONE` in https://github.com/istio/istio/blob/8b519e53298fea63ef228bca5f1be0f65eeb7e19/install/kubernetes/helm/istio/templates/configmap.yaml#L177
1. Observe that a sidecar injected pod has the `istio-init` initContainer injected.

**Version**
1.1.0-rc.5

**Installation**
One primary control plane cluster. Two remote data plane clusters.

/cc @costinm @howardjohn

**Comment by howardjohn** [comment]
Looks like NONE is not a part of the ProxyConfig.InterceptionMode proto: https://github.com/istio/istio/blob/319ae418ed6564e4323b19d29a679f6f9234f829/vendor/istio.io/api/mesh/v1alpha1/proxy.proto#L156

I think we just need to add this and it should work

```bash
$ istioctl kube-inject -f app.yaml
2019-03-18T19:03:47.581886Z     warn    model   Failed to decode proto: "unknown value \"NONE\" for enum istio.mesh.v1alpha1.ProxyConfig_InboundInterceptionMode". Trying decode with AllowUnknownFields=true
Error: istioctl version 1.1.0-rc.5 cannot parse mesh config.  Install istioctl from the latest Istio release; failed to convert to proto. unknown value "NONE" for enum istio.mesh.v1alpha1.ProxyConfig_InboundInterceptionMode
```

**Comment by howardjohn** [comment]
Just spoke with @costinm, who says this is working as intended. In order to disable the init container you will need the annotation on each pod. The sidecar injector template is a little misleading in indicating that it can be set disabled in the mesh config. Do you have any specific use cases where you would need to do this?

**Comment by mdgreenfield** [comment]
Our planned default behavior in production is to disable the `istio-init` `initContainer`.

**Comment by howardjohn** [comment]
Ok, thanks for the info. We would prefer to not change the ProxyConfig.InterceptionMode proto. Instead, we could just modify the injector behavior with helm values, by adding some value like `noneByDefault`.

Current behavior:
```
if annotation == none, don't create init.
```
Proposed behavior:
```
if .Values.noneByDefault:
  if annotation present and annotation != none, create init
  else: don't create init
else if annotation == none, don't create init
```

Would something like this work for you? If so we can get it out in 1.1.x

**Comment by mdgreenfield** [comment]
That will work for us. Prior to opening this issue, your proposed solution is what I envisioned until I saw the `interceptionMode` configuration.

**Comment by costinm** [comment]
As I mentioned, there are few other use cases for disabling the init container and iptables:
- CNI - it manages iptables 
- user has its own iptable setup

I would rather improve consistency and make it clear what is happening - something like 'sidecarInjectorWebhook.initContainer=false'. 
It would be equivalent with whaty is provided by istio_cni.enabled=true

I couldn't find the other PR disabling just the iptables.

**Comment by duderino** [comment]
@mdgreenfield can this be closed?

**Comment by howardjohn** [comment]
@duderino no this is not yet fixed. We need to do further work on readiness with NONE mode

**Comment by killcity** [comment]
Any progress on this? I may not want to use iptables at all for performance reasons and also for ease of integration into an existing stack.
