### ISSUE TITLE
VirtualService in hosts not permite domain+port

### ISSUE THREAD

**Issue by qiyongxiao** [istio/istio#12545]
## Hello, I use istio(version:1.0.6) to edit VirtualService that hosts add an port. It show issues like this:

```
error: virtualservices.networking.istio.io "mytest" could not be patched: admission 
webhook "pilot.validation.istio.io" denied the request: configuration is invalid:
domain name "quick:31380" invalid (label "quick:31380" invalid)
```

## This is the config.yaml
<img width="973" alt="dddd" src="https://user-images.githubusercontent.com/7349963/54471443-eec4a300-47f3-11e9-862b-162a6e6e9727.png">

### My istio cluster expose an nodePort 31380 to forward traffic. 
While the VirtualService.spec.hosts value is "*",  and I can access my service. 
When I modified it to change domainName:port, show some issues like above.

I has asked someone about this and see the source code on this part of virtualservice know has changed on 2018.8. But his istio version is also 1.0.6, could add an port on domain name. 
if anyone help me?

**Comment by mingfang** [comment]
I'm experiencing the exact same problem.

When I set host to "*" I was able to route traffic to a httpbin service.  \
Httpbin shows the Host header as  `"Host": "httpbin.192.168.2.146.nip.io:31380"`.

According to https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Host, the port is legal.

This looks like a bug in VirtualService.

**Comment by mingfang** [comment]
I found a workaround here https://github.com/istio/istio/issues/11828

Hack it by setting host="*" and then use match authority 
```
- match:
    - authority:
         prefix: "httpbin"
```

**Comment by howardjohn** [comment]
@hzxuzhonghu you mentioned in https://github.com/istio/istio/pull/13720 this was already fixed in 1.2, is this the case? Can we close this?

**Comment by hzxuzhonghu** [comment]
They are not same thing.

**Comment by hzxuzhonghu** [comment]
```
- match:
    - authority:
         exact: "bookinfo.example.com:31380"
```
Try this

**Comment by vadimi** [comment]
This started breaking our cluster when we moved to `1.2`. Previously we were disabling galley and using "host:port" in the gateways and virtualservices to send some NodePort traffic. It worked perfectly fine. But with `1.2` galley is required now due to https://github.com/istio/istio/issues/14841. 

Is there a way to allow ports in host names? we have lots of virtual services and changing all of them to use authority matchers is not that trivial.

**Comment by sdake** [comment]
> This started breaking our cluster when we moved to `1.2`. Previously we were disabling galley and using "host:port" in the gateways and virtualservices to send some NodePort traffic. It worked perfectly fine. But with `1.2` galley is required now due to #14841.
> 
> Is there a way to allow ports in host names? we have lots of virtual services and changing all of them to use authority matchers is not that trivial.

@vadimi Hi.  I respect that you want to use NodePort.  NodePort is usually used for evaluations, but not production.

I'd like to understand a little more about your use case.  Does your environment not have support for a load balancer?  Could you expand on your environment a bit?  Are you using NodePort in production?

Cheers
-steve

**Comment by vadimi** [comment]
hi @sdake. We use istio in AWS EKS and we do have load balancers for http1 apps. But we also have lots of grpc services that we expose from the cluster (internally only) and using node ports was pretty simple - we just configured route53 with ip addresses of istio-ingressgateway nodes.

**Comment by duanhaowei** [comment]
so we need a outside LB to avoid use port in url ?

**Comment by strzelecki-maciek** [comment]
@sdake im coming from a slightly different angle here - istio ingress gateway is very much underwhelming when it comes to functionality it offers (starting with big things - proxyprotocol - and then moving over to dozens of small things - just compare nginx-ingress vs istio-ingress)

so - i have a istio-proxy injected nginx-ingress deployment. it works great for 99% of traffic, but some other systems like to call us via 'Host: my-domain:443' and then istio-proxy throws 503UC. Easy to solve right? Just add this my-domain:443 in addition to my-domain on my istio-virtual-service definition... But it doesnt pass the validation.

Having a strong requirement of proxyprotocol and mtls between each service/pod - what are my options?

**Comment by laobaox** [comment]
I'm experiencing the exact same problem,  Is there a solution?

**Comment by andye2004** [comment]
+1, this is really annoying
