### ISSUE TITLE
bookinfo service not able to communicate using short DNS names, while FQDN works.

### ISSUE THREAD

**Issue by olegchorny** [istio/istio#12563]
Not sure if this is an issue or not, but the behavior is pretty weird, and should be somehow related to the setup. My bookinfo services not able to communicate to each other (stuck on envoy?) using short DNS names and able to do it using FQDN.

And it seems like non-DNS issue, since curl didn't return "Could not resolve host error".

**Describe the bug**
` kubectl exec -it $(kubectl get pod -l app=ratings -o jsonpath='{.items[0].metadata.name}') -c ratings -- curl productpage:9080/productpage `command returns nothing
while `kubectl exec -it $(kubectl get pod -l app=ratings -o jsonpath='{.items[0].metadata.name}') -c ratings -- curl productpage.default.svc.cluster.local:9080/productpage | grep -o "<title>.*</title>"` returns ` <title>Simple Bookstore App</title>`
**Expected behavior**
`<title>Simple Bookstore App</title>` should be returned

**Steps to reproduce the bug**
Install first cluster: https://preliminary.istio.io/docs/setup/kubernetes/install/multicluster/gateways/
Then, install bookinfo on it:
https://preliminary.istio.io/docs/examples/bookinfo/

**Version**
Istio 1.1 
Kubernetes 1.11 and 1.12

**Installation**
https://preliminary.istio.io/docs/setup/kubernetes/install/multicluster/gateways/

**Environment**
GKE

**Comment by esnible** [comment]
Can you try

```
kubectl exec -it $(kubectl get pod -l app=ratings -o jsonpath='{.items[0].metadata.name}') -c ratings -- cat /etc/resolv.conf
```

For me, I get 

```
search default.svc.cluster.local svc.cluster.local cluster.local
nameserver 172.21.0.10
options ndots:5
```

The way name resolution works in Linux is that the system first tries to resolve.  If that fails, it tries each of the SEARCH choices as suffixes.  There is a limit of six search suffixes.

**Comment by olegchorny** [comment]
```
nameserver 10.59.240.10
search default.svc.cluster.local svc.cluster.local cluster.local us-central1-a.c.blue-green-234712.internal c.blue-green-234712.internal google.internal
options ndots:5
```
Little bit more requests:
```
$ kubectl exec  $SLEEP_POD -n foo -c sleep -- curl -I productpage.default:9080/productpage 
HTTP/1.1 404 Not Found
$ kubectl exec  $SLEEP_POD -n foo -c sleep -- curl -I productpage.default.svc.cluster.local:9080 
HTTP/1.1 200 OK
$ kubectl exec  $SLEEP_POD -n foo -c sleep -- curl -I productpage:9080 | grep HTTP
curl: (6) Could not resolve host: productpage
```

**Comment by esnible** [comment]
OK.  It is different with multicluster.

This may be a duplicate of https://github.com/istio/istio/issues/12324

Are the sleep pod and productpage on the same pod?

**Comment by olegchorny** [comment]
They are in different pods and namespaces and it looks like your reference to the issue is the answer for my question. 

What I need to change exactly (as temp solution) to make it work and check if it helps?

**Comment by elevran** [comment]
@olegchorny if the pods are in different namespaces the short name should include the namespace. 
See https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#what-things-get-dns-names:
>Assume a Service named foo in the Kubernetes namespace bar. A Pod running in namespace bar can look up this service by simply doing a DNS query for foo. A Pod running in namespace quux can look up this service by doing a DNS query for foo.bar.

This may still fail due to #12324 and not having the short name (w/ns) in the host name config.

**Comment by olegchorny** [comment]
@elevran 
yep, in my example I've provided three different cases with different outputs, let me copy them:
This case is not expected:
```
$ kubectl exec  $SLEEP_POD -n foo -c sleep -- curl -I **productpage.default**:9080/productpage 
HTTP/1.1 **404 Not Found**
```
These two expected:
```
$ kubectl exec  $SLEEP_POD -n foo -c sleep -- curl -I **productpage.default.svc.cluster.local**:9080 
HTTP/1.1 **200 OK**
$ kubectl exec  $SLEEP_POD -n foo -c sleep -- curl -I **productpage:9080** | grep HTTP
curl: (6) **Could not resolve host: productpage**
```

**Comment by elevran** [comment]
I missed the example with the NS. Can you please do a DNS lookup on the `sleep` pod to confirm you're getting the same correct IP address in all cases. If so, I'd suggest marking this as duplicate of #12324. 
I'd suspect a fix will be in 1.1.1 shortly after the release.

**Comment by olegchorny** [comment]
@elevran 

```
kubectl exec --context=$CTX_CLUSTER1 $SLEEP_POD -n foo -c sleep -- nslookup productpage.default.svc.cluster.local
Name:      productpage.default.svc.cluster.local
Address 1: 10.59.245.62 productpage.default.svc.cluster.local
```
```
kubectl exec --context=$CTX_CLUSTER1 $SLEEP_POD -n foo -c sleep -- nslookup productpage.default
Name:      productpage.default
Address 1: 10.59.245.62 productpage.default.svc.cluster.local
```
```
kubectl get svc 
NAME          TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
details       ClusterIP   10.59.247.84    <none>        9080/TCP   10m
kubernetes    ClusterIP   10.59.240.1     <none>        443/TCP    16m
productpage   ClusterIP   10.59.245.62    <none>        9080/TCP   10m
ratings       ClusterIP   10.59.240.146   <none>        9080/TCP   10m
reviews       ClusterIP   10.59.246.36    <none>        9080/TCP   10m
```

**Comment by esnible** [comment]
Could this be a duplicate of https://github.com/istio/istio/issues/12324 ?

**Comment by elevran** [comment]
Seems to be.

**Comment by olegchorny** [comment]
Hi All, 
I've made the fresh install using the release 1.1 bits and can't reproduce the issue.
I think I did the deployment using the bits from master branch, but not from release-1.1 branch, and something is not merged to master (yet).
I'm closing the issue. many thanks!
