### ISSUE TITLE
CRD Installation instructions out of date

### ISSUE THREAD

**Issue by mpuncel** [istio/istio#12565]
**Describe the bug**
https://istio.io/docs/setup/kubernetes/quick-start/#installation-steps says to `kubectl apply -f install/kubernetes/helm/istio/templates/crds.yaml`, but this YAML file no longer exists as of January.

**Comment by jaygorrell** [comment]
Those are the 1.0 docs and the CRD file is still in 1.0.6. For 1.1 you should be using https://preliminary.istio.io/docs/

**Comment by mpuncel** [comment]
got it, thanks!
