### ISSUE TITLE
http.url in spans reported by istio are being cut to a fixed length (116 characters of qs values)

### ISSUE THREAD

**Issue by Stono** [istio/istio#12561]
**Describe the bug**
http.url in the span context is being stripped down (not showing the complete thing) which makes debugging rather difficult.

Taking my good old test case of `[ingress-nginx] -> [consumer-gateway] -> [sauron-web]`.

Here is the first span, which for us is recorded by `ingress-nginx` using the opentracing libraries:

```
                        {
                            "key": "http.url",
                            "type": "string",
                            "value": "https://<our private site>/car-search?sort=price-asc\u0026newTabClick=false\u0026onesearchad=Nearly%20New\u0026make=JAGUAR\u0026model=F-PACE\u0026aggregatedTrim=Portfolio\u0026min-monthly-price=50\u0026deposit=1000\u0026term=60\u0026yearly-mileage=10000\u0026maximum-mileage=10000\u0026maximum-badge-engine-size=2.0\u0026zero-to-60=TO_8\u0026co2-emissions-cars=TO_165\u0026postcode=ll302up\u0026radius=1"
                        },
```

And here is the span for consumer-gateway, as recorded by istio (163 characters):

```
                        {
                            "key": "http.url",
                            "type": "string",
                            "value": "https://<our private site>/car-search?sort=price-asc\u0026newTabClick=false\u0026onesearchad=Nearly%20New\u0026make=JAGUAR\u0026model=F-PACE\u0026aggregatedTrim=Portfolio\u0026min-mont"
                        },
```

And then again down to sauron-web (150 characters):
```
                        {
                            "key": "http.url",
                            "type": "string",
                            "value": "https://app.sauron-web/car-search?min-monthly-price=50\u0026maximum-badge-engine-size=2.0\u0026maximum-mileage=10000\u0026postcode=ll302up\u0026sort=price-asc\u0026yearly-mile"
                        },
```

In both examples, the length of the recorded querystring parameters seems to be `116`.

cc. @douglas-reid

**Comment by douglas-reid** [comment]
@Stono just to clarify: in the traces you are seeing the `http.url` tag be truncated?

@objectiser any thoughts here?

**Comment by Stono** [comment]
Yes yes I can give you the JSON blob on slack

**Comment by douglas-reid** [comment]
@Stono here's a quick dig through source for what I think is the relevant bit:

https://github.com/envoyproxy/envoy/blob/23bf90446b4c196d64342b20cf39bbac18795fa9/source/common/tracing/http_tracer_impl.cc#L33-L36

**Comment by douglas-reid** [comment]
I can't find any solid reason for that limit in a quick search, but hopefully someone else can provide insight.

**Comment by douglas-reid** [comment]
Asked a question here: https://github.com/envoyproxy/envoy/pull/444

**Comment by Stono** [comment]
Don't suppose anyone has had any traction understanding why this was?  It's really annoying for us investigating downstream systems!

**Comment by douglas-reid** [comment]
I have not heard any more about this. Probably time to send a PR to bump up the limit.

**Comment by douglas-reid** [comment]
@Stono I believe 1.1.3 contains the patch that updates the limit to `256`. That might not totally meet your requirement, but it should be an improvement. Are you able to test it out?

**Comment by Stono** [comment]
Tested and working as expected in 1.1.3, still trims some of our rather large urls short though but 🤷‍♂️

**Comment by douglas-reid** [comment]
@Stono are you OK with me closing this issue for now?  ultimately, it would be nice to fully support long URLs (perhaps through configuration controlled limits), but that is a bigger undertaking.

**Comment by Stono** [comment]
Go for it.

**Comment by douglas-reid** [comment]
Thanks!
