### ISSUE TITLE
TCP connections inside mesh - "Connection closed by foreign host"

### ISSUE THREAD

**Issue by motek80** [istio/istio#12572]
**Describe the bug**
Cannot establish TCP connection from one pod to another inside mesh (with sidecars injected in both pods).

**Expected behavior**
Pods should be able to communicate with other pods in same mesh.

**Steps to reproduce the bug**
We have several developers in the team, all of us apparently have the same environment. However, I'm the only one who experiencing this weird issue.

Steps:
1. Have running Kubernetes with Istio running inside. mTLS is disabled. Sidecars are auto-injected.
2. Deploy two different pods. PodA exposed via Kubernetes service (serviceA).

PodA accepts TCP connections (e.g. mysql or redis). Everything deployed in same namespace "product".

3. From podB, open telnet to the serviceA using its full DNS name, e.g. "telnet serviceA.product.svc.cluster.local 3306"

4. With Istio, podB fails communicate to serviceA ("Connection closed by foreign host"). Without Istio, everything works as expected (telnet actually returns result, both for redis and mysql)

What I tried:

- Full reinstall (OS, Kubernetes, Istio, pods...)
- turning off firewall (ufw)

**Version**
{{ What version of Istio and Kubernetes are you using? Use `istioctl version --remote` and `kubectl version` }}

Kubernetes 1.13.4
Istio 1.0.6

**Installation**
I tried two different ways (both give same results):

- Microk8s with Istio plugin enabled
- KubeAdm with Istio installed via Helm (template method)

**Environment**
Windows 10 host with Linux Ubuntu 18.04 (on HyperV/VirtualBox)

**Cluster State**
- all pods in "istio-system" in "running" state (some of them with restarts)

**REST based calls seems to work, TCP based connections doesn't**

**Comment by hzxuzhonghu** [comment]
It may has something todo with envoy tcp proxy. Can not remember the issue number .
Actually for mysql or redis, you can use the cli to access. `Connection closed` should be caused by you send invalid data via the connection.

**Comment by motek80** [comment]
@hzxuzhonghu

Thank you for your response. I can hardly believe it has something to do with data I sending, since: a - I just opening telnet, not sending anything and; b - without Istio it works as expected.

I will appreciate if you could recall issue number.

**Comment by hzxuzhonghu** [comment]
#10832  I am not sure if this can help

**Comment by hzxuzhonghu** [comment]
Also https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/lds.proto.html

The listener_filters_timeout is 15s by default.

**Comment by esnible** [comment]
Your Sidecar may not be "READY".  Do `kubectl get pods` and verify that it is `2/2`.  https://github.com/istio/istio/issues/9504

I always do `kubectl get gw,vs,dr,se,policy,sidecar` and make sure I didn't forget some test configuration that adds or changes security.

Does this succeed:

```
PODNAME=e.g. reviews-v1-cb8655c75-8n85h
SERVICE=reviews
NS=default
SVCPORT=9080
PATH=/reviews/0
PODIP=$(kubectl get pod $PODNAME -o jsonpath='{.status.podIP}')
kubectl exec $PODNAME -c istio-proxy -- curl -v https://$SERVICE.$NS.svc.cluster.local:$SVCPORT/$PATH --resolve "$SERVICE.$NS.svc.cluster.local:$SVCPORT:$PODIP" --key /etc/certs/key.pem --cert /etc/certs/cert-chain.pem --cacert /etc/certs/root-cert.pem --insecure
```

**Comment by 2ZZ** [comment]
I'm also having this problem on 1.1.2 deployed to EKS

For example, connecting from a pod to a mysql service in the same namespace using netcat normally outputs gibberish showing the MySQL version, but with istio enabled and sidecar running in both pods a connection is established but no traffic seems to be passing.
```bash-4.2# nc -v mysql 3306
Ncat: Version 7.50 ( https://nmap.org/ncat )
Ncat: Connected to 10.100.17.243:3306.```
Eventually the connection will close and istio-proxy logs:
```[2019-04-16T16:05:20.579Z] "- - -" 0 - "-" 0 0 69394 - "-" "-" "-" "-" "100.73.64.167:3306" outbound|3306||mysql.mynamespace.svc.cluster.local 100.73.66.183:41838 10.100.17.243:3306 100.73.66.183:33746 -```
