### ISSUE TITLE
503 retries, istio vs application source

### ISSUE THREAD

**Issue by Stono** [istio/istio#12583]
I have a question regarding all the work that's been done recently with istio retries behind the scenes.  My question at a high level is *will istio differentiate between a 503 returned by envoy, and a 503 returned by an application*?

It's my understanding (cc @nmittler) that the transparent retries behind the scenes will do connection errors etc, but also, 502/503.

Now what is to happen if the service is up and available, but decides to return a 503 in response to a request?  The reason I ask is I have stumbled across a couple of our services that return 503 under certain scenarios and we wouldn't want them to be retried, and I am concerned that they will be.

I could get them to change what response code they use, but it raised the thought above with me and that is I think istio should really only be transparently retrying mesh related errors, and if it gets a response from the app, even if it is a status code we don't want, it should *never* retry that unless the operator has explicitly configured to do so.

**Comment by nmittler** [comment]
@Stono Our retry logic by default will retry 503s returned by the application (but not 502s). I don't believe we have a way of differentiating between a 503 generated by Envoy and a 503 from the application. 

In all of the following cases below, envoyA will retry:

```
appA->envoyA->envoyB->appB(returns 503)

appA->envoyA->envoyB-> (failed connection)

appA->envoyA-> (failed connection)
```

In all of these cases, the retry logic is nestled within envoyA and it only has the ability to determine whether the immediate request failed because of a 503 returned from the server or a broken connection. 

If we disable retries for 503, the following will **not** retry:

```
appA->envoyA->envoyB->appB(returns 503)

appA->envoyA->envoyB-> (failed connection)

appA->envoyA->envoyB->appB->envoyB->envoyC->appC(returns 503)
```

The following will still retry:

```
appA->envoyA-> (failed connection)

appA->envoyA->envoyB->appB->envoyB-> (failed connection)
```

We may be fine leaving out 503 from the default, but I'm not sure if there are cases I'm not considering. One that comes to mind is that we lose retries if the app Envoy is up but the app is down.

@knrc @costinm @rshriram thoughts?

**Comment by Stono** [comment]
OK so been chatting about this more.  We've discovered that a lot of the http client libraries that are used in our java apps us http://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/impl/client/DefaultServiceUnavailableRetryStrategy.html - so they default retry 503's.

So what we'd end up with is:
```
app 1 -> app 2:
   envoy: retry xN (whatever is configured transparently)
 app 1 retry N (whatever the client library is configured to do:
   envoy: retry xN (whatever is configured transparently)
```

It feels like perhaps the mesh should only retry totally transparent things (such as connection errors), and if a status code is returned, that should be left to the application? 

No solution seems perfect here!

**Comment by rshriram** [comment]
the solution is to stop using computers and go back to abacus

**Comment by nmittler** [comment]
@Stono I'm not completely against excluding retryOn 503 by default.  In fact @rshriram was pushing for this [in my PR](https://github.com/istio/istio/pull/10566#pullrequestreview-188099348). 

The one case that comes to mind is where the Envoy is up but the application behind it is down. By default this would cause a 503, but application readiness probes should be the solution here. I suspect there may be other edge cases as well.

Maybe something to consider for 1.1.x?

@louiscryan @duderino @costinm @rshriram

**Comment by Stono** [comment]
`Envoy is up but the application behind it is down` - yes application ready probes should stop that traffic getting to the envoy however, if an application goes unready from a previously ready state, that EDS update takes some time to propagate to the sending envoy so there will be a window == the duration of the EDS update in which traffic will get to that envoy.

Also our envoys never shut down before the app, always the other way round (we have a pre-stop hook in istio-proxy which ensures it doesn't quit until after the app quits, to work around the issue where the app could still be making outbound requests as part of its shutdown process).  

It's all a little bit "racey", doesn't feel deterministic at all.

**Comment by Stono** [comment]
Closing this in favour of https://github.com/istio/istio/issues/13851

There have been many following conversations about how 503 is too broad, and what the ideal retry strategy should actually be (cc @duderino)
