### ISSUE TITLE
how to enable mtls for mixer e2e-test?

### ISSUE THREAD

**Issue by luguoxiang** [istio/istio#12591]
**Describe the bug**
{{ Succinctly describe the bug }}
It seems mixer's e2e tests are using non-mTLS destination rule,  I need to do following change to run the tests under mTLS enabled istio installation. 
```
tests/e2e/tests/mixer/mixer_test.go

-	destinationRuleAll          = "destination-rule-all"
+	destinationRuleAll          = "destination-rule-all-mtls"
```
Is there any way to avoid such code change and make the test run under  mTLS enabled istio installation?

**Expected behavior**
{{ What did you expect to happen? }}
Test passed

**Steps to reproduce the bug**
{{ Minimal steps to reproduce the behavior }}

**Version**
{{ What version of Istio and Kubernetes are you using? Use `istioctl version --remote` and `kubectl version` }}
release-1.1

**Installation**
{{ Please describe how Istio was installed }}
helm install with --set global.mtls.enabled=true

**Environment**
{{ Which environment, cloud vendor, OS, etc are you using? }}

**Cluster state**
{{ If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue. }}

**Comment by howardjohn** [comment]
--auth_enable. All the flags are in the README https://github.com/istio/istio/blob/master/tests/e2e/README.md#L69

**Comment by howardjohn** [comment]
If the above didn't fix your problem feel free to reopen
