### ISSUE TITLE
Does 1.1 support  two virtualService share the same host.

### ISSUE THREAD

**Issue by idouba** [istio/istio#12590]
In the spec of [1.0 VirtualService](https://istio.io/docs/reference/config/istio.networking.v1alpha3/#VirtualService)， host is described "Alternatively, the traffic properties of a host can be defined using more than one VirtualService". Especially for the case [One host(domain) and path-based service delegation in gateway](https://istio.io/help/ops/traffic-management/deploy-guidelines/#multiple-virtual-services-and-destination-rules-for-the-same-host).

In spec of of [1.1 VirtualService](https://preliminary.istio.io/docs/reference/config/networking/v1alpha3/virtual-service/#VirtualService) it is emphasised that "A host name can be defined by only one VirtualService". what does this mean?

Does 1.1 support  two virtualService share the same host. and how to deal with the path-based service delegation which is  a common case of ingress.   Maybe[ VirtualService chain](https://github.com/istio/istio/issues/6070)  can help solve the problem.

**Comment by idouba** [comment]
#6070

**Comment by hzxuzhonghu** [comment]
I find https://github.com/istio/api/pull/621 is in release-1.0 but not in release-1.1. 

But in 1.1, add a note **A host name can be defined by only one VirtualService**

**Comment by linsun** [comment]
it is documented here:  https://preliminary.istio.io/help/ops/traffic-management/deploy-guidelines/#multiple-virtual-services-and-destination-rules-for-the-same-host

cc @frankbu @louiscryan

**Comment by rshriram** [comment]
still supported..

**Comment by frankbu** [comment]
According to @rshriram, the "Alternatively, the traffic properties of a host can be defined using more than one VirtualService" part of the doc probably got accidentally removed with all the updating and merging for 1.1. So this issue should be redirected to istio/api. We need to put back in the reference doc that multiple VirtualServices for gateway host is allowed.

**Comment by idouba** [comment]
OK, thanks. @linsun @rshriram 
Will the VirtualService chain we mentioned #6070  be provided in the next version? @frankbu

**Comment by hzxuzhonghu** [comment]
Thanks all. @idouba Would you help put back the reference doc

**Comment by idouba** [comment]
YES, @hzxuzhonghu, I have submit a PR: https://github.com/istio/api/pull/870

**Comment by frankbu** [comment]
Fixed by https://github.com/istio/api/pull/873 and https://github.com/istio/api/pull/874
