### ISSUE TITLE
gRPC tracing on in pilot-discovery

### ISSUE THREAD

**Issue by rvansa** [istio/istio#12594]
**Describe the bug**
gRPC tracing is on by default in `pilot-discovery` process which leads to excessive memory usage. This is the offending line:
https://github.com/istio/istio/blob/1.1.0-rc.5/pilot/pkg/bootstrap/server.go#L121
When turning it off I can see substantially decreased memory usage as there are no `istio.io/istio/vendor/golang.org/x/net/trace.trace` objects on the heap.

**Expected behavior**
Tracing is off by default or controlled through config map.

**Steps to reproduce the bug**
Always present.

**Version**
1.1.0.rc-5, Openshift 3.10

**Installation**
Helm charts

**Environment**
Openshift 3.10 on RHEL 7

**Comment by rvansa** [comment]
Should I create a PR to fix it, linking the option to config map's `enableTracing`?

**Comment by hzxuzhonghu** [comment]
I suggest providing a flag `--enableGrpcTracing`

**Comment by linsun** [comment]
A PR would be good, it would be good to be configurable via helm.  Please loop in @GregHanson for review as he has been making changes to get our logs configurable.

**Comment by rvansa** [comment]
@linsun Ok, if an option is a better way to go, I'll use that. So in helm, this should be configurable through `--set pilot.enableGrpcTracing=true`, right? (default should be false).

**Comment by linsun** [comment]
check out this: https://github.com/istio/istio/pull/12639

probably good to have a flag for pilot.tracing.enableGrpcTracing?
