### ISSUE TITLE
Helm Ingress Prometheus & Grafana not working!

### ISSUE THREAD

**Issue by emichaf** [istio/istio#12598]
Deploying Istio via Helm chart istio-1.1.0.tgz

Ingresses not working for Prometheus & Grafana (but works for Kiali, Jaeger & Servicegraph)

**Setting subchart params for ingresses:**

prometheus.enabled="true"
prometheus.ingress.enabled="true"
prometheus.ingress.hosts={"prometheus.mysystem.com"}

grafana.enabled="true"
grafana.ingress.enabled="true"
grafana.ingress.hosts={"grafana.mysystem.com"}

**K8S Ingresses:**
**$ kubectl describe ingress prometheus -n istio-system**
Name:             prometheus
Namespace:        istio-system
Address:
Default backend:  default-http-backend:80 (<none>)
Rules:
  Host                                                    Path  Backends
  ----                                                    ----  --------
  prometheus.mysystem.com
                                                          /prometheus   prometheus:9090 (<none>)

**$ kubectl describe ingress grafana -n istio-system**
Name:             grafana
Namespace:        istio-system
Address:
Default backend:  default-http-backend:80 (<none>)
Rules:
  Host                                                 Path  Backends
  ----                                                 ----  --------
  grafana.mysystem.com
                                                       /grafana   grafana:3000 (<none>)
Annotations:
Events:  <none>

**Comment by howardjohn** [comment]
Can you describe what you mean by "not working"? Can you provide the differences between config that works for kiali but doesn't work for prometheus?
