### ISSUE TITLE
Build istioctl tab completion file along with binaries; document how to use it.

### ISSUE THREAD

**Issue by esnible** [istio/istio#12607]
We have a "tab completion" ability in istioctl.  This saves typing for long commands such as "istioctl experimental verify-install".

We have a mechanism to generate the bash config file, `istioctl collateral --bash`.  But the command is hidden so users don't see it and we don't document it.

I produced a PR to make this option visible, possibly with a new name, but the feedback on that PR was that we shouldn't have people create the file.  Instead we should provide it as part of our builds, and document how users should get it.

For example, for `git` tab completion see this post https://git-scm.com/book/en/v1/Git-Basics-Tips-and-Tricks where users are shown how to download the file and set it up.

**Comment by ibm-jason** [comment]
@esnible, I'm interested in tackling this one. Should I just re-assign this to myself?

**Comment by ibm-jason** [comment]
@esnible A couple of things to mention on this:

1. From the master branch, I used the `istioctl collateral --bash` command option to generate the bash completion file. The place that made the most sense (to me) to store/host this file is the `./tools` directory.

2. Once the `istioctl.bash` file was generated, I sourced it with the following command:

```
$ source ./tools/istioctl.bash
```
IIUC, at this point the tab completion should function properly. Below is a screenshot of what happens on my system when I use a tab immediately _after_ the `istioctl` command:

<img width="1151" alt="Screen Shot 2019-03-29 at 5 22 06 AM" src="https://user-images.githubusercontent.com/38068894/55222593-b012ed80-51e2-11e9-800d-eaea8df44901.png">

Is there something that I'm missing to get this working? I want to ensure that I document the steps properly.

Thanks,

@ibm-jason

**Comment by esnible** [comment]
@ibm-jason I followed your steps and they work for me.  I am on a Mac, OSX, 10.13.x (High Sierra).  I see that I did `brew install bash-completion` back in March 2018.  `brew info bash-completion` says I am using 
```
bash-completion: stable 1.3 (bottled)
```

I also see that I put `[ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion` into my _~/.bash_profile_ at the suggestion of _brew_.

If you are not on OSX, run `echo $SHELL` to see what shell you are using.  Run `$(echo $SHELL) --version` to see what shell version you are using.

**Comment by ibm-jason** [comment]
@esnible thanks. That's good info to add to the docs. I'll try this out and report back shortly.

**Comment by ibm-jason** [comment]
@esnible yes, it works now. The key was adding the `[[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . "/usr/local/etc/profile.d/bash_completion.sh"` to my `~/.bash_profile`.

So, does this location make sense to add the completion file?  Also, where on istio.io does this documentation make the most sense? I was thinking here:

https://istio.io/docs/reference/commands/istioctl/  <-- a new section here, perhaps?

**Comment by ericvn** [comment]
How does this work with zsh completion?

**Comment by ibm-jason** [comment]
@ericvn Great point. Would you mind trying it out and letting us know? I don't know much about zsh...

**Comment by esnible** [comment]
> So, does this location make sense to add the completion file? Also, where on istio.io does this documentation make the most sense? I was thinking here:
> 
> https://istio.io/docs/reference/commands/istioctl/ <-- a new section here, perhaps?

I believe that page is auto-generated.  I suspect tab completion documentation would be expected at https://istio.io/docs/setup/kubernetes/download/#download-and-prepare-for-the-installation .  I suspect everyone who wants bash completion will see _istioctl.bash_ in the download and know what to do with it.  It is also possible to put it in a blog article.

**Comment by ibm-jason** [comment]
@esnible and the location of the completion file? Does the tools dir make sense?

**Comment by esnible** [comment]
@ibm-jason I was thinking _bin_ but _tools_ will also work.  Does anyone have a preference?

**Comment by ericvn** [comment]
The current issue with zsh is:
```
source istioctl.bash
istioctl.bash:type:1098: bad option: -t
```
because the zsh builtin `type` does not have a -t option

If I remove the -t, I can source the file, but run into:
```
istioctl __start_istioctl:5: command not found: _init_completion
```
when trying to use tab completion.

**Comment by esnible** [comment]
`istioctl` uses cobra.  zsh completion for Cobra is mostly done, see https://github.com/spf13/cobra/issues/107 .  It should be possible to add a `--zsh` option to `istioctl collateral`.  The `--bash` option we have no doesn't use the new Cobra features/

**Comment by ericvn** [comment]
@esnible I assume you mean we would have to add the -zsh option within istioctl to generate the file. It's not exposed at the moment. I'm not sure how many people use zsh, but all the other tools I use do support both bash and zsh for completion.

**Comment by esnible** [comment]
We would have to add the -zsh option.  Most or all of the functionality has been implemented in Cobra in the last six months.  We would need someone with zsh to test it.

**Comment by ericvn** [comment]
@esnible I'm certainly willing to test.

**Comment by ericvn** [comment]
As a semi quick test to see what would work with `zsh` completion, I updated the code locally to take a `--zsh` parameter and call the root.GenZshCompletionFile and generate an `_istioctl` file. I tried to source that file. That completed fine, but looking at the file, it was incomplete and `istioctl <tab>` didn't work correctly.

I then looked at the `cobra` repo and pulled the file in their unmerged PR:https://github.com/spf13/cobra/pull/828  and rebuilt the file and sourced it. That actually worked. Trying to place the file so it is automatically sourced like the other files (like _kubectl_) hasn't worked for me, yet...

But, it seems that if the `cobra` team does get the PR merged, and we pull that new dependency and generate the file using --ksh (I can merge my changes into a PR if you want) we are getting farther along the _add zsh completion_ path as well.

**Comment by ericvn** [comment]
Note that #13871 is for the Zsh version of the tab completion, along with its associated PRs.

**Comment by ericvn** [comment]
Today, we have a few parallel work threads; 1) make _istioctl_ downloadable (https://github.com/istio/istio/issues/11527) and 2) this item to add completion files.

I see a problem in that if someone wants to download the executable using 1), there is no documented way to use 2). The reason is because 2) has us build the completion files as part of the build process and add them to the archives and then how to use these archived files.

What if we changed the way to files are created to no longer be a _collaberation_ flag but to be a _completion_ noun which tags _bash_ or _zsh_ and dumps to stdout? This allows someone to create there own file using _istioctl completion bash > istioctl.bash_ or to simply source the output _source < istioctl completion bash_.
 - Pros:
    - Behaves like other commands like _kubectl_
    - Prevents us from having to build and archive a file and have the customer use it.
        - If the customer updates their _istioctl_ it automatically gets the changes if they use _source < ..._
  - Cons:
    - ?

**Comment by ibm-jason** [comment]
@ericvn I see your point here.  Although the PRs to add the completion files merged, and the separate istioctl download PR in review, enabling istioctl to simply dump the completion files to stdout would make UX improvement and allow us to source the completion files as you've described. I would like to hear what folks like @esnible and @howardjohn think about this before we proceed...

**Comment by esnible** [comment]
@ibm-jason I have noticed some tools encourage the user to generate the completion file, and other tools encourage the user to download it.  I thought it would be good to un-hide completion generation because I have my experience using the former.  See https://github.com/istio/istio/pull/12637 for that discussion.

**Comment by ericvn** [comment]
Maybe we can get @geeknoid to weigh in on this again. I think this change (move the --zsh and --bash to their own completion noun) would make for a better UX. But am fine with whatever you decide. From a zsh standpoint, it matches what is being done for bash, which was my original comment.

**Comment by ibm-jason** [comment]
@ericvn agreed. I'm fine with either.

**Comment by ibm-jason** [comment]
@geeknoid do you mind chiming in (once again) on this?

**Comment by ibm-jason** [comment]
@esnible, @ericvn, @geeknoid:

At this point, now that the completion file PRs have been merged, and the documentation has been updated, do we "punt" this discussion past the 1.2 release? Perhaps create a new issue to discuss this further? Or, are we settled on this?

**Comment by esnible** [comment]
@ibm-jason Is this work done?

**Comment by ibm-jason** [comment]
@esnible Yes, I believe that this work is complete with the following PRs merged:

- https://github.com/istio/istio/pull/13024
- https://github.com/istio/istio/pull/13871
- https://github.com/istio/istio.io/pull/4274
