### ISSUE TITLE
Sidecar tests are flaky

### ISSUE THREAD

**Issue by ozevren** [istio/istio#12601]
The sidecar tests using the new test framework are flaky. This seems to be due to the use of fsnotify in Galley. I am disabling the test and opening this bug to track re-enablement, so that I can land the new refactorings in master.

Once they land, I'll re-enable the tests.

**Comment by louiscryan** [comment]
Fixed in https://github.com/istio/istio/pull/11617

**Comment by howardjohn** [comment]
Test is still disabled, I am working on getting it back up now

**Comment by louiscryan** [comment]
The fsnotify stuff is removed so it should be much more stable now

**Comment by howardjohn** [comment]
https://testgrid.k8s.io/istio-postsubmits#integration-local-tests&width=10&sort-by-flakiness=

Tests have been re-enabled and have no flakes, closing this
