### ISSUE TITLE
Non-http/ssh traffic between pods?

### ISSUE THREAD

**Issue by hdimitriou** [istio/istio#12616]
I am trying to perform ssh between pods and the sidecar envoy proxy is denying it with 
`ssh_exchange_identification: Connection closed by remote host`
If I understand well the sidecar proxy iptables(?) rules redirect all incoming traffic and denies the ssh traffic. 

Is there a way to work around that / tweak the configuration?

**Comment by hdimitriou** [comment]
Not an issue, i found my way around this

**Comment by danvy** [comment]
> Not an issue, i found my way around this

What was your workaround?

**Comment by cheekykesav** [comment]
> Not an issue, i found my way around this

Please let know what was the workaround? I am struggling to find a solution.
