### ISSUE TITLE
Image used in Grafana was removed with the 1.1 release

### ISSUE THREAD

**Issue by jaygorrell** [istio/istio#12612]
**Describe the bug**
Grafana displays the image at https://istio.io/img/istio-logo.svg in 1.1. This was removed in the 1.1 docs.

**Expected behavior**
Image shows up

**Steps to reproduce the bug**
View Grafana Mesh dashboard

**Version**
1.1

**Comment by jaygorrell** [comment]
Sorry, this should probably be on the istio.io repo so it can be fixed for existing releases.

**Comment by mjordan79** [comment]
Still not fixed in 1.1.2, why the bug has been closed?

**Comment by jaygorrell** [comment]
Because it was opened here instead, which was also closed though: https://github.com/istio/istio.io/issues/3788
