### ISSUE TITLE
istio-1.1.0/install/kubernetes/istio-demo.yaml line 1467 miss Separator

### ISSUE THREAD

**Issue by w564791** [istio/istio#12617]
istio-1.1.0/install/kubernetes/istio-demo.yaml line 1467 miss separate

**Comment by linsun** [comment]
Thanks for reporting this.  Did this impact anything for you?  my install went fine when i tried it yesterday.

**Comment by w564791** [comment]
> Thanks for reporting this. Did this impact anything for you? my install went fine when i tried it yesterday.

我没直接apply呢,我先浏览了一遍,加上分隔符再测试的

**Comment by linsun** [comment]
think this is fixed via a PR that is based on #12464
