### ISSUE TITLE
Test Flake: TestProcessor_EventAccumulation_WithFullSync

### ISSUE THREAD

**Issue by ozevren** [istio/istio#12628]
https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/12626/istio-unit-tests/22329

**Comment by ozevren** [comment]
@nmittler I believe you made some changes in this area recently. Could PTAL?

**Comment by kyessenov** [comment]
Still flakes https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/12822/istio-unit-tests/22736
