### ISSUE TITLE
Istio sidecar upstream pod reconnection issue

### ISSUE THREAD

**Issue by karsten42** [istio/istio#12625]
**Describe the bug**
I'm running istio 1.0.6 (no mTLS) on our EKS cluster and am experiencing connection issues between two pods that I can't seem to figure out.

I have a gRPC client (abc-client) and server (abc-server) running both written in go. The cluster has automatic sidecar injection enabled, so both have it running.
Everything is working fine if I just start the two services, but whenever the server restarts, the client is not able to reconnect to it. From the restart onwards I continuously get the following error message on the client:

{"level":"error","error":"rpc error: code = Unavailable desc = upstream connect error or disconnect/reset before headers","time":"2019-03-19T12:07:52Z","message":"abc-server service unhealthy"}

Without the istio sidecar the reconnection is working immediately. When I look at the sidecar logs of the abc-client I see a lot of the following messages for the health checks the client is trying to do:

2019-03-19T12:09:41.527Z] "POST /grpc.health.v1.Health/CheckHTTP/2" 200 UF 5 0 1002 - "-" "grpc-go/1.15.0" "6a874d67-9c43-4b67-ad24-7337a26cac8d" "abc-server.abc-namespace:8086" "172.31.18.194:8086" outbound|8086||abc-server.abc-namespace.svc.cluster.local - 172.31.18.194:8086 172.31.22.131:44994

My takeaway from these logs is that the proxy is experiencing problems connecting to the upstream server that is not there anymore, hence the UF flag (upstream failure) but is still returning a 200 status code to the client. To me it seems that this behaviour doesn't trigger a reconnection.

I have not any VirtualServices or DestinationRules set up, it's just a simple istio cluster with the sidecars enabled.

What am I missing? Thanks in advance for your help.

**Expected behavior**
The client should reconnect to the server when it restarts.

**Steps to reproduce the bug**
Have a gRPC client and server running in kubernetes. Restart the server and see if the client can still access the server.

**Version**
Istio
Version: 1.0.6
GitRevision: 98598f88f6ee9c1e6b3f03b652d8e0e3cd114fa2
User: root@464fc845-2bf8-11e9-b805-0a580a2c0506
Hub: docker.io/istio
GolangVersion: go1.10.4
BuildStatus: Clean

Kubernetes
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.13-eks-g484b8", GitCommit:"484b857e3134d55ac6373fea2f51798fefa0533f", GitTreeState:"clean", BuildDate:"2019-03-08T05:32:36Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

**Installation**
[Via Helm](https://istio.io/docs/setup/kubernetes/install/helm/#option-1-install-with-helm-via-helm-template) 

**Environment**
Dev machine: macOS
Cloud: AWS EKS

**Cluster state**
-

**Comment by karsten42** [comment]
The problem is connecting to headless services. My `service.yaml` looked like this:

```
apiVersion: v1
kind: Service
metadata:
  name: grpc-test-server
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: grpc-test-server
    role: grpc-test-server
  ports:
    - name: grpc
      port: 9999
      targetPort: grpc
```

As per the issues https://github.com/istio/istio/issues/10659 and https://github.com/istio/istio/issues/7495 istio doesn't work yet with headless services. 

So, if you don't need your service to be headless, you can just remove `clusterIP: None` from the yaml and everything should work as expected. 

I still don't know though how to make statefulsets work which [require](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#limitations) headless services.

**Comment by arielb135** [comment]
> The problem is connecting to headless services. My `service.yaml` looked like this:
> 
> ```
> apiVersion: v1
> kind: Service
> metadata:
>   name: grpc-test-server
> spec:
>   type: ClusterIP
>   clusterIP: None
>   selector:
>     app: grpc-test-server
>     role: grpc-test-server
>   ports:
>     - name: grpc
>       port: 9999
>       targetPort: grpc
> ```
> As per the issues #10659 and #7495 istio doesn't work yet with headless services.
> 
> So, if you don't need your service to be headless, you can just remove `clusterIP: None` from the yaml and everything should work as expected.
> 
> I still don't know though how to make statefulsets work which [require](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#limitations) headless services.

Battling with this issue aswell,
there's a suggested solution in #7495 - but the solution just doesn't work, there's no TLS communication even with a per-pod ServiceEntry configuration.
It looks like we need to abandon istio until this is fixed or there's a workaround
