### ISSUE TITLE
Test Gap: Istio check-in gates are not testing based on published Helm charts

### ISSUE THREAD

**Issue by ozevren** [istio/istio#12647]
https://github.com/istio/istio/issues/12535
https://github.com/istio/istio/issues/12624
https://github.com/istio/istio/issues/12600

It looks like the check-in gates we have do not properly cover helm based installation. We've slipped in issues into the branch without tests catching them. We need to make sure there is at least one test gate that ensures the helm charts agree with the checked-in code.

**Comment by howardjohn** [comment]
We have `e2e-simpleTests` running directly from the helm install now, so I think this is resolved
