### ISSUE TITLE
Feature Request: Configurable service name format in tracing data

### ISSUE THREAD

**Issue by Stono** [istio/istio#12644]
[This change](https://github.com/istio/istio/pull/7803) resulted in span names being recorded as `app-label:namespace`.  The PR makes sense, however for users like me where we have a loosely 1-2-1 mapping between application and namespace it is just overly verbose as the two values are typically the same:

<img width="441" alt="Screenshot 2019-03-20 at 21 48 56" src="https://user-images.githubusercontent.com/1486729/54722092-8e1ec880-4b5b-11e9-81ef-ad70895344d2.png">

You can imagine how noisy this gets on deep nested spans.

I understand why the change was made, but it'd be much appreciated if it was a configurable thing.

**Comment by douglas-reid** [comment]
I think this might be something we should consider as part of a refactoring of a Trace API, as well.  Similar to access log format, we could support `traceOperationFormat` or similar.

/cc @objectiser

**Comment by objectiser** [comment]
@douglas-reid Agree would be good to support in Trace API - although this would be about the service name, not operation name. Suggestion: title should be something like "Configurable service name format in tracing data"?

**Comment by Stono** [comment]
@geeknoid @howardjohn not sure your bot is working :'(

**Comment by howardjohn** [comment]
Stop closing this :slightly_frowning_face:

**Comment by Stono** [comment]
@douglas-reid we still have to work around this by modifying our injector, is there anything in the newer tracing apis that allows us to handle this?

The config is:

```
        - --serviceCluster
        {{ if ne "" (index .ObjectMeta.Labels "app") -}}
        - "{{ index .ObjectMeta.Labels `app` }}.$(POD_NAMESPACE)"
        {{ else -}}
```

For us; the `$(POD_NAMESPACE)` part is just noise  so we're looking for a way to ensure `serviceCluster` is simply `labels.app`.

**Comment by douglas-reid** [comment]
@Stono not at the moment. i'm not sure how to model that particular bit in the proposed APIs, as service cluster is set via bootstrap -- and the proposed APIs don't address bootstrap concerns.

**Comment by Stono** [comment]
Maybe it's not a observability concern then and more of an injector config option 🤷

**Comment by douglas-reid** [comment]
@Stono that's my thought as well. Make this a meshconfig option.

**Comment by Stono** [comment]
@douglas-reid @howardjohn please can we reopen this, the workaround above seems to be broken in `1.12`, we have pods with the `serviceCluster` being set:

<img width="209" alt="Screenshot 2021-11-19 at 08 37 39" src="https://user-images.githubusercontent.com/1486729/142591824-a445a7cb-cc49-40f4-9071-7426e7486d40.png">

But traces are once again coming through as `namespace.name`:

<img width="413" alt="Screenshot 2021-11-19 at 08 36 04" src="https://user-images.githubusercontent.com/1486729/142591849-53ed12cd-7f92-46e7-9317-03b1d742a9d8.png">

**Comment by Stono** [comment]
Decided to open a new issue (https://github.com/istio/istio/issues/36162) to track the bug as this issue was specifically about being able to control the serviceName programatically

**Comment by Stono** [comment]
Closing in favour of the discussion in https://github.com/istio/istio/issues/36162
