### ISSUE TITLE
Istio-proxy pretty much always initially fails readinessProbes

### ISSUE THREAD

**Issue by Stono** [istio/istio#12653]
Not urgent, but the default `initalDelaySeconds` on the `istio-proxy` `readinessProbe` of 1 second always results in at least one failure, which when you've got 500+ proxies, it's a lot :D

`42m         Warning   Unhealthy           Pod          Readiness probe failed: HTTP probe failed with statuscode: 503`

https://github.com/istio/istio/blob/0e9cecab053aab744a7c3a731aacb07fd794d5f9/install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml#L202

This is on a cluster with basically next to no services too so probably thinking the initial delay of 1 second is a bit too low.  We've bumped `global.proxy.readinessInitialDelaySeconds` to `5`.

**Comment by linsun** [comment]
@mandarjog @jnativio - thoughts?  okay to make this change as default?

**Comment by jnativio** [comment]
I don't think this is a good idea. It will delay directly the startup of a pod with sidecar. What is the impact of the warning message?

**Comment by Stono** [comment]
Yeah I think I active with @jnativio - from a serverless perspective perhaps it needs to be on 1s and then the goal is to get that sidecar start time right down.  

@jnativio in terms of impact we alert when apps fail their readiness probes successively so at the moment we get alerts every time a proxy starts.  We can tweak these values internally though.

**Comment by Stono** [comment]
I'm going to close this, it's configurable at the end of the day :)

**Comment by prabaharanit** [comment]
hi how to change to global config parameter.. pls provide me the command to change to global value.. below cmd not working for me kubectl get cm istio-sidecar-injector -n istio-system -o yaml | sed -e 's/initialDelaySeconds`  1/initialDelaySeconds`  10/' | kubectl apply -f -

**Comment by jnativio** [comment]
@prabaharanit You can use: `helm template --set global.proxy.readinessInitialDelaySeconds=10  helm/istio --name istio --namespace istio-system | kubectl apply -f -`

**Comment by eskuai** [comment]
how can i do it without helm?

cause, this global.proxy.xxx not found ...

**Comment by linsun** [comment]
We aren't support customized config without helm today, you'd have to dig through the code to check what yaml are changed for DIY.

**Comment by eskuai** [comment]
root@k8s-master istio-1.1.7]#  helm template --set global.proxy.readinessInitialDelaySeconds=10 helm/istio --name istio --namespace istio-system | kubectl apply -f -
Error: stat helm/istio: no such file or directory
error: no objects passed to apply

Great!
