### ISSUE TITLE
Control plane upgrade from 1.0.6 to 1.1.0 resulted in a batch of 503's

### ISSUE THREAD

**Issue by Stono** [istio/istio#12658]
I decided to test some load against a simple echo endpoint during a 1.0.6 to 1.1.0 upgrade of about 200 requests/second.

We experienced a whole batch of 503s (43 to be precise):

<img width="1007" alt="Screenshot 2019-03-21 at 11 53 51" src="https://user-images.githubusercontent.com/1486729/54750684-72a1d500-4bd0-11e9-9237-55c089288a13.png">

It's important that we're able to roll out control plane upgrades without any downtime!  Maybe this will be improved in 1.1.0 with the transparent retries?

Are you doing testing of loaded control planes as part of upgrade testing?

**Comment by linsun** [comment]
yes, we are doing continuously ping test (probably not much load) think we are testing ~85% passing rate.

If you are NOT using mixer, it is probably good to disable mixer or mixer check before the upgrade, because that is the only thing intercepts the app flow.

**Comment by Stono** [comment]
We have `policyCheckFailOpen` = true, which I thought was doing the same thing?

So just to be clear, you're saying there's currently not zero downtime method of upgrading the istio control plane?

**Comment by linsun** [comment]
I don't think these two params are the same. policyCheckFailOpen will perform the policy check but still allow the call to go through to mixer which could get stuck when mixer is down, where disablePolicyCheck will disable check completely.

Our test currently checks for 85% passing rate:  https://github.com/istio/istio/blob/release-1.1/tests/upgrade/test_crossgrade.sh#L47  In 1.0.x we didn't implement pod disruption budge (which is added in 1.1) as that is the k8s support to help ensure 1 replica stays up for a given deployment, all times.  cc @ostromart if I missed anything.

I'd defer to mixer team for mixer related upgrade issue.  cc @mandarjog

**Comment by linsun** [comment]
I think this can be closed?  @stono indicated he was able to not get 503 by disable mixer check, leverage pod disruption budget and rolling strategy.  I opened an issue to improve our rolling strategy configuration:  https://github.com/istio/istio/issues/13552

**Comment by linsun** [comment]
pls reopen if needed.  for 1.0.6, we didn't implement pod disruption budget so it will have issue, however from 1.1 to 1.1.x, PDB is in place.
