### ISSUE TITLE
Remove unneeded lists from jaeger templates

### ISSUE THREAD

**Issue by kramvan1** [istio/istio#12662]
**Describe the bug**
Embedded lists in the jaeger template can cause issues with automation tools like kustomize.  The list are not really needed and would be nice if they could be removed.
https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/tracing/templates/service-jaeger.yaml

**Expected behavior**
No Lists in the resource templates.

**Steps to reproduce the bug**

**Version**
1.1.0

**Installation**
helm template, then kubectl apply

**Environment**

**Cluster state**

**Comment by kramvan1** [comment]
@linsun cc

**Comment by douglas-reid** [comment]
Given the resolution for https://github.com/istio/istio/pull/12669, I think it is safe to close this issue as well.
