### ISSUE TITLE
Error: unknown command "server" for "galley"

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#12673]
Looks like Mixer error but actually Galley.
Occurs in many tests preventing merges from tide pool. See https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/12505/e2e-mixer-no_auth/13913

/assign @ozevren

**Comment by ozevren** [comment]
I think this was a one off failure. Do you concur? Can we close this?
