### ISSUE TITLE
tests/kubeTest.sh command-line arguments

### ISSUE THREAD

**Issue by esnible** [istio/istio#127]
The meaning of the -i option has changed

```
-    i) ISTIOCTL_URL="${OPTARG}";;
+    i) ISTIOCLI="${OPTARG}";;
```

With this change, the instructions at https://github.com/istio/istio/blob/master/tests/README.md no longer work for updating _istioctl_ version.

Furthermore, but unrelated, it would be nice to print success/failure AFTER cleanup because it scrolls off the screen if it is only printed before cleanup.

**Comment by sebastienvas** [comment]
This breaks the e2e-smoke test. How do we we pass in the istioctl url now ? We need to put 
i) ISTIOCTL_URL="${OPTARG}";; back and use a different option for ISTIOCLI

**Comment by sebastienvas** [comment]
For reference, this is used here
https://github.com/istio/istio/blob/master/Jenkinsfile#L36

**Comment by frankbu** [comment]
Ah, sorry about that. I thought that the build would point to the built linux binary instead of downloading it. Can that be done. If not, I guess you're suggestion makes sense ... we need two different args, because in the general case people will want to test the built binary before it's built and uploaded

**Comment by sebastienvas** [comment]
We don't have binaries stored in the source code anymore. The e2e smoke test actually run in a different workspace so it easier download istioctl binary for traceability. I agree that we need 2 cases.

**Comment by frankbu** [comment]
OK, I'll fix it with a second arg

**Comment by frankbu** [comment]
Fixed with PR https://github.com/istio/istio/pull/131
