### ISSUE TITLE
istioctl version should report server version not just client version

### ISSUE THREAD

**Issue by esnible** [istio/istio#12703]
`istioctl version` should be more like similar commands `kubectl version` and `linkerd version` and print the server version by default.

This could be as easy as making `istioctl version --remote --short` the defaults.

**Comment by linsun** [comment]
Our current version cmd only displays the client side version.  It should be enhanced to display the server version and use it as the default (without the needing to specify --remote or --short).

We should also have a verbose option for versions.  Our default version today is verbose but only prints out the client side.

**Comment by esnible** [comment]
@linsun it would be trivial to make remote and short the defaults.  That could break scripts that parse the output as JSON.  I don't know of any scripts like that in the wild.  Thoughts?

**Comment by leecalcote** [comment]
@esnible @linsun showing both by default resonates with me. The proposed new experience here is akin to that of kubectl, which is familiar to most users.

**Comment by howardjohn** [comment]
May be nice to also output each version as it reads it, on a large cluster its really slow. Although this may not work if we need to sort it
