### ISSUE TITLE
Routing issues with Ingress + SDS 

### ISSUE THREAD

**Issue by iamjem** [istio/istio#12700]
**Describe the bug**
After installing Istio 1.1 using the default config, and following the steps in the configuring ingress with SDS task, I am unable to make requests to the httpbin service.

**Expected behavior**
I should be able to make both http and https requests to the ELB for the `httpbin.example.com` host, have them routed to the httpbin service, and see the expected responses.

**Steps to reproduce the bug**
Follow the steps on [securing ingress gateway using SDS task](https://istio.io/docs/tasks/traffic-management/secure-ingress/sds/). In my case I completed up through "Configure a TLS ingress gateway for a single host."

The basic steps:
1. Install istio 1.1 with default config as described [here](https://istio.io/docs/setup/kubernetes/install/helm/)
2. Create and apply the new deployment for ingress as described in [step 1](https://istio.io/docs/tasks/traffic-management/secure-ingress/sds/#configure-a-tls-ingress-gateway-using-sds)
3. Follow the [Configure a TLS ingress gateway for a single host](https://istio.io/docs/tasks/traffic-management/secure-ingress/sds/#configure-a-tls-ingress-gateway-for-a-single-host), up until step 5, where the curl returns an error:
  ```
  * TLSv1.2 (OUT), TLS handshake, Client hello (1):
  * LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to httpbin.example.com:443 
  * stopped the pause stream!
  * Closing connection 0
  curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to httpbin.example.com:443 
```

Even making a normal http request with `curl -v -H "Host: httpbin.example.com" http://$INGRESS_HOST/status/418` does not work (empty response from server).

I am able to make http requests from within the cluster to the httpbin service.

I've done some sanity checks provisioning the cluster with Istio 1.1 and _no_ SDS and things work as expected for Ingress.

**Version**
curl:
```
curl --version | grep LibreSSL
curl 7.54.0 (x86_64-apple-darwin18.0) libcurl/7.54.0 LibreSSL/2.6.4 zlib/1.2.11 nghttp2/1.24.1
```
istio:
```
version.BuildInfo{Version:"1.1.0", GitRevision:"82797c0c0649a3f73029b33957ae105260458c6e", User:"root", Host:"996cd064-49c1-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-rc.6"}
```
kubernetes:
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-13T23:15:13Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.8-eks-7c34c0", GitCommit:"7c34c0d2f2d0f11f397d55a46945193a0e22d8f3", GitTreeState:"clean", BuildDate:"2019-03-01T22:49:39Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Installation**
I previously had Istio 1.0.5 installed. I removed the existing install with:
```
kubernetes delete -f istio.yaml # this was the original config used to install 1.0.5
kubernetes delete -f install/kubernetes/helm/istio/templates/crds.yaml
kubernetes delete ns istio-system
```
To install Istio 1.1, I followed the [helm install instructions with default config](https://istio.io/docs/setup/kubernetes/install/helm/).

**Environment**
AWS EKS

**Cluster state**

ingress-sds logs (is the cert being applied ???):
```
kubectl logs -n istio-system $(kubectl get pod -l istio=ingressgateway \
-n istio-system -o jsonpath='{.items[0].metadata.name}') -c ingress-sds
2019-03-22T15:24:57.393262Z	info	SDS gRPC server start, listen "/var/run/ingress_gateway/sds" 

2019-03-22T15:24:57.393894Z	info	Start SDS grpc server for ingress gateway proxy
2019-03-22T15:40:04.148920Z	info	SDS: push key/cert pair from node agent to proxy: "router~10.0.74.64~istio-ingressgateway-6cb65d86cb-lrlt6.istio-system~istio-system.svc.cluster.local-1"
```

Config dump from envoy shows the httpbin.example.com routes in `dynamic_route_configs`, and listener config:
```
"dynamic_active_listeners": [
 {
  "version_info": "2019-03-22T15:40:04Z/13",
  "listener": {
   "name": "0.0.0.0_443",
   "address": {
    "socket_address": {
     "address": "0.0.0.0",
     "port_value": 443
    }
   },
   "filter_chains": [
    {
     "filter_chain_match": {
      "server_names": [
       "httpbin.example.com"
      ]
     },
     "tls_context": {
      "common_tls_context": {
       "alpn_protocols": [
        "h2",
        "http/1.1"
       ],
       "tls_certificate_sds_secret_configs": [
        {
         "name": "httpbin-credential",
         "sds_config": {
          "api_config_source": {
           "api_type": "GRPC",
           "grpc_services": [
            {
             "google_grpc": {
              "target_uri": "unix:/var/run/ingress_gateway/sds",
              "stat_prefix": "sdsstat"
             }
            }
           ]
          }
         }
        }
       ]
      },
      "require_client_certificate": false
     },
     # ...
```
[istio-dump.zip](https://github.com/istio/istio/files/2997382/istio-dump.zip)

**Comment by JimmyCYJ** [comment]
@iamjem Could you verify if your secret httpbin-credential is created correctly, and check envoy logs (-c istio-proxy) to see if Envoy has received the key/cert successfully?

**Comment by iamjem** [comment]
I should be able to re-visit this before the end of the week. I've killed off my old cluster, but I'll go through the steps again with a new one and see where I land.

**Comment by JimmyCYJ** [comment]
Thanks @iamjem , I suspect the gateway was not working properly, because even plain HTTP request does not work. I don't find any issue from the envoy config and ingress-sds logs you posted.

**Comment by iamjem** [comment]
So, initially followed through the steps again against a fresh cluster with istio 1.1 installed, came to the same result.

Then I decided to "go back" to the non-SDS version and double check I could make normal HTTP requests. So I applied the original istio-ingressgateway deployment again (without the ingress-sds bits), and attempted to make an HTTP request to the ELB for the httpbin host. My request failed, and then I realized the `Gateway` from the tutorial only included a TLS server and nothing for normal HTTP traffic. So I updated the gateway spec, getting rid of the TLS server completely:
```
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP
```

Made a request:
```
curl -H "Host: httpbin.example.com" $ELB_HOSTNAME/status/418    
                                                                                                                                         
    -=[ teapot ]=-                                                                                                                                        
                                                                                                                                                         
       _...._                                                                                                                                             
     .'  _ _ `.                                                                                                                                          
    | ."` ^ `". _,                                                                                                                                        
    \_;`"---"`|//                                                                                                                                        
      |       ;/                                                                                                                                          
      \_     _/                                                                                                                                           
        `"""`
```
Worked, as expected. Then I updated the istio-ingressgateway deployment _again_, putting it back on the SDS version from the tutorial. Started by making the same HTTP request as above, and it worked. Following this, I put the TLS server back into the `Gateway` spec from the tutorial (and left the HTTP one as well):

```
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP
  - hosts:
    - httpbin.example.com
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: httpbin-credential
      mode: SIMPLE
```

Then I proceeded to make an HTTPS request with the same command that failed me before, and magically it worked this time. Outside of my `Gateway` now also having an HTTP server, I have no idea what else could have changed. There was nothing new in istio-proxy or ingress-sds container logs that wasn't there before, and no other resources were touched during the back and forth besides the ingress deployment and the single `Gateway`.

So I'll leave it up to you all as to whether you want to go ahead and close this. We'll likely continue investigating things more on our end as we'd like to switch to SDS for managing the potentially many ingress certs present in our clusters today (having to update volumes and create new deployments isn't great).

**Comment by JimmyCYJ** [comment]
@iamjem Thanks a lot for the investigation and all the details posted above. As this problem does not happen again I don't have any clue about the root cause. If you are continuing investigating, would you mind to keep http port 80 open in your ingressgateway, so that it could show whether this is a SDS issue or other issues. I am going to close the issue for now, but please feel free to reopen and update with any thing you discover. Thanks!
