### ISSUE TITLE
How we implement kiali

### ISSUE THREAD

**Issue by naveeng68** [istio/istio#12722]
I installed istio 1.1(kubectl version 1.11 and Kops 1.10) without helm, kiali is coming with it.
I edit kiali service and change type Cluster ip to Loadbalancer. 

as per helm we add grafana and jaeger via 

> helm template \
>     --set kiali.enabled=true \
>     --set "kiali.dashboard.jaegerURL=http://jaeger-query:16686" \
>     --set "kiali.dashboard.grafanaURL=http://grafana:3000" \
>     install/kubernetes/helm/istio \
>     --name istio --namespace istio-system > $HOME/istio.yaml
> 

But how we can add grafanaURL and jaegerURL under yaml file (service or deployement)?
Please do needful

**Comment by jmazzitelli** [comment]
If I understand the question correctly, you are asking how to configure Kiali so it knows the jaegerURL and grafanaURL when not installing Kiali via helm or the Kiali [installation script](https://git.io/getLatestKialiKubernetes).

If that is true, the settings are easily defined in Kiali's configmap.

```
external_services:
  jaeger:
    url: http://my-jaeger:80
  grafana:
    url: http://my-grafana:3000
```

See this page for a description of all the configmap settings: https://github.com/kiali/kiali/blob/master/README.adoc#environment-variables

**Comment by douglas-reid** [comment]
Closing this issue as this has been answered.

**Comment by naveeng68** [comment]
i am not looking via helm.
I have deployment .yaml

> apiVersion: extensions/v1beta1
> kind: Deployment
> metadata:
>   name: kiali
>   namespace: istio-system
>   labels:
>     app: kiali
>     chart: kiali
>     heritage: Tiller
>     release: istio
> spec:
>   replicas: 1
>   selector:
>     matchLabels:
>       app: kiali
>   template:
>     metadata:
>       name: kiali
>       labels:
>         app: kiali
>         chart: kiali
>         heritage: Tiller
>         release: istio
>       annotations:
>         sidecar.istio.io/inject: "false"
>         scheduler.alpha.kubernetes.io/critical-pod: ""
>     spec:
>       serviceAccountName: kiali-service-account
>       containers:
>       - image: "docker.io/kiali/kiali:v0.14"
>         name: kiali
>         command:
>         - "/opt/kiali/kiali"
>         - "-config"
>         - "/kiali-configuration/config.yaml"
>         - "-v"
>         - "4"
>         env:
>         - name: ACTIVE_NAMESPACE
>           valueFrom:
>             fieldRef:
>               fieldPath: metadata.namespace
>         - name: SERVER_CREDENTIALS_USERNAME
>           valueFrom:
>             secretKeyRef:
>               name: kiali
>               key: username
>               optional: true
>         - name: SERVER_CREDENTIALS_PASSWORD
>           valueFrom:
>             secretKeyRef:
>               name: kiali
>               key: passphrase
>               optional: true
>         - name: PROMETHEUS_SERVICE_URL
>           value: http://prometheus:9090
>         - name: SERVER_WEB_ROOT
>           value: /kiali
>         volumeMounts:
>         - name: kiali-configuration
>           mountPath: "/kiali-configuration"
>         resources:
>           requests:
>             cpu: 10m
> 
>       volumes:
>       - name: kiali-configuration
>         configMap:
>           name: kiali
>       affinity:
>         nodeAffinity:
>           requiredDuringSchedulingIgnoredDuringExecution:
>             nodeSelectorTerms:
>             - matchExpressions:
>               - key: beta.kubernetes.io/arch
>                 operator: In
>                 values:
>                 - amd64
>                 - ppc64le
>                 - s390x
>           preferredDuringSchedulingIgnoredDuringExecution:
>           - weight: 2
>             preference:
>               matchExpressions:
>               - key: beta.kubernetes.io/arch
>                 operator: In
>                 values:
>                 - amd64
>           - weight: 2
>             preference:
>               matchExpressions:
>               - key: beta.kubernetes.io/arch
>                 operator: In
>                 values:
>                 - ppc64le
>           - weight: 2
>             preference:
>               matchExpressions:
>               - key: beta.kubernetes.io/arch
>                 operator: In
>                 values:
>                 - s390x

Please let me know how we pass grafana url in this file:

**Comment by jmazzitelli** [comment]
See above - I believe I answered your question already.
