### ISSUE TITLE
Grafana/Kiali don't show data with overlapping global DestinationRule enabling mTLS

### ISSUE THREAD

**Issue by jaygorrell** [istio/istio#12723]
**Describe the bug**
When deploying a global `DestinationRule` to set `ISTIO_MUTUAL` for `host: "*.local"`, everything works correctly on the traffic side but Grafana does not show any data and Kiali just shows the first hop.

**Expected behavior**
Grafana and Kiali continue to show data.

**Steps to reproduce the bug**
Run the following
```
kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml
kubectl apply -f samples/bookinfo/networking/bookinfo-gateway.yaml
kubectl apply -f samples/bookinfo/networking/destination-rule-all-mtls.yaml
kubectl apply -f samples/bookinfo/networking/virtual-service-all-v1.yaml

kubectl apply -f - <<EOF
apiVersion: authentication.istio.io/v1alpha1
kind: MeshPolicy
metadata:
  name: default
spec:
  peers:
    - mtls:
        mode: STRICT
---
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: default
  namespace: default
spec:
  host: "*.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
EOF
```
You should see that traffic is working correctly -- reviews v1 is always loaded and if you drop the `ISTIO_MUTUAL` on any of the DestinationRules it will fail because `STRICT` mode is set. However Grafana shows none of the traffic and Kiali just shows the first hop.

If you delete the default `DestinationRule`, traffic will show up.

That policy came from this page:
https://istio.io/docs/tasks/security/authn-policy/#globally-enabling-istio-mutual-tls

**Version**
k8s 1.11.7, Istio 1.1

**Installation**
Helm Template with
```
grafana:
  enabled: true
```

**Environment**
AWS / Kops

You can see here what happens right after the global `DestinationRule` is applied. The request traffic drops to nothing and all services have no traffic. I had a curl loop running this whole time and it continues to receive 200 responses.
![image](https://user-images.githubusercontent.com/12174604/54886424-38e5fe00-4e5e-11e9-8855-d3aeaecaa895.png)

**Comment by jaygorrell** [comment]
I figured this out. The `host` rule needs to be scoped to the namespace as well using `*.default.svc.cluster.local`, not just the `namespace` attribute of the resource. 

I want to leave this open a bit to get confirmation that this is expected -- which may mean there's an issue to open on the docs side of things.

**Comment by jaygorrell** [comment]
Okay, the real setting here is `global.controlPlaneSecurityEnabled` that needs to be enabled. That will create a mTLS destination rule for telemetry. There might be a documentation gap here still.

**Comment by ceastman-ibm** [comment]
@jaygorrell do you have an example destination rule that works? also you mention global.controlPlaneSecurityEnabled, where should that be set?

**Comment by jaygorrell** [comment]
Those are related. See `global.controlPlaneSecurityEnabled` in the Helm values... it will create the DR when enabled.

**Comment by ceastman-ibm** [comment]
Can i create the DR manually? I'll have to see if I can change the helm value, I'm working with IBM cloud's managed istio platform.

**Comment by ceastman-ibm** [comment]
Which helm chart would I be modifying?

**Comment by jaygorrell** [comment]
Sorry not able to look at the moment but look at the istio chart and see
what resources are affected by controlPlaneSecurityEnabled... that'll lead
you to the DR it creates.

**Comment by ceastman-ibm** [comment]
ok thanks, ill check it out later today.

**Comment by ceastman-ibm** [comment]
looks like other things besides just the creation of DR are affected when that flag is true or false. Im seeing changes to the istio configmap.

**Comment by ceastman-ibm** [comment]
i believe this is the yaml your referring to: https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/security/templates/enable-mesh-mtls.yaml

**Comment by 3RX0** [comment]
Solution with enabling global.controlPlaneSecurityEnabled and defining DR with full ns name works for seeing requests in Kiali, but I'm still not able to see HTTP statuses
