### ISSUE TITLE
Istio mesh monitoring dashboard contains duplicate list of all service with unknown workload and namespace

### ISSUE THREAD

**Issue by iftachsc** [istio/istio#12737]
**Describe the bug**
at some point, most likely because of a fault, we started to have in additional to correct service and metrics, an entry per service, where service name is correct but with "unknown.unknown" entry for the workload column (destination_workload & destination_workload_name) with 0 metrics.
so all works because we have all the correct metrics but we want to remove the duplicates from the list.
its not a problem in the dashboard but with the metrics exposed by istio-telemetry and can be seen in prometheus.
i have for every real service metrics with correct details  another with same destination service name with:
destination_workload="unknown",destination_workload_namespace="unknown" labels.
i don't know where its coming from

![image](https://user-images.githubusercontent.com/28829551/54906230-83fa2280-4eeb-11e9-970c-d865972c652b.png)

**Expected behaviour**
as in the beginning, when we had only the real part. no unknown namespace and workload names for these labels

**Steps to reproduce the bug**
i dunno how but i know it happened before and then somehow got fixed by itself.

**Version**
istio 1.0.6
"1.11.7-gke.6

**Installation**
regulat 1.0.6 official chart

**Environment**
GCP

**Comment by douglas-reid** [comment]
Without a way to repro this issue, this will be hard to diagnose. It is possible that there were failures with attribute generation for some reported metrics. The "easiest" way to get rid of these metrics is to configure timeouts for the prom adapter.

Unfortunately, without a good repro, I don't see a path forward. I'm going to close this issue. Hopefully, there is no recurrence in 1.1.x and 1.2.x branches.
