### ISSUE TITLE
Global Istio mutual TLS tutorial problem: discuss.istio.io reported issue with solution

### ISSUE THREAD

**Issue by sdake** [istio/istio#12738]
**Describe the bug**
Istio tutorial doesn't work: https://istio.io/docs/tasks/security/authn-policy/#globally-enabling-istio-mutual-tls

**Expected behavior**
Istio tutorial should work

**Steps to reproduce the bug**
See: https://discuss.istio.io/t/istio-tutorial-doesnt-work-on-minikube/1528

**Version**
Istio 1.1.0

**Installation**
Installing with mtls enabled=true doesn't suffer this problem.

**Environment**
{{ Which environment, cloud vendor, OS, etc are you using? }}

**Cluster state**
{{ If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue. }}

**Comment by howardjohn** [comment]
We recently changed how we look for DestinationRules. We look in the namespace of the source and destintion (foo and bar) and the root config namespace (defaults to istio-system). It no longer will search all namespaces. So in the default setup, I think you would need to add the DR to either foo, bar (probably want both), or istio-system.

**Comment by howardjohn** [comment]
Thats also why mtls=true works, it creates the rule in istio-system

**Comment by jericks-duo** [comment]
I'd like to add that I experienced this as well. For me, adding destinationrules in `foo` and `bar` namespaces doesn't work, but adding one in `istio-system` works. 

I was getting
```
$ kubectl logs --tail 2  httpbin-9d88f6c98-jfjkl -c istio-proxy -n foo
...
503 UAEX ""UNAVAILABLE:upstream connect error or disconnect/reset before headers""
...
```
in the logs, if that helps.

**Comment by linsun** [comment]
@johnma14 can you get the doc updated accordingly?

**Comment by johnma14** [comment]
@linsun will do

**Comment by jericks-duo** [comment]
I'm not sure it's only a documentation issue. Shouldn't it work if I add destinationrules to the `foo` and `bar` namespace? msoule's comment [here] (https://discuss.istio.io/t/istio-tutorial-doesnt-work-on-minikube/1528) implies so.

Right now, it's very unclear to me which namespaces I have to add rules to in order to have them take effect. The original `foo`/`bar` namespace destinationrules didn't work, but the [single-namespace policy/destinationrule part of the tutorial](https://istio.io/docs/tasks/security/authn-policy/#namespace-wide-policy) _did_ work, just putting the rules in `foo`.

**Comment by jericks-duo** [comment]
Following the [Authentication Policy](https://istio.io/docs/tasks/security/authn-policy) guide, when I create a destination rule for the `bar` namespace, the behavior is very odd.
```
$ kubectl apply -f - <<EOF
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"                                                                        metadata:                  
  name: "default"
  namespace: "bar"
spec:
  host: "*.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
EOF
destinationrule.networking.istio.io/default created
```
```
$ for from in "foo" "bar"; do for to in "foo" "bar"; do kubectl exec $(kubectl get pod -l app=sleep -n ${from} -o jsonpath={.items..metadata.name}) -c sleep -n ${from} -- curl "http://httpbin.${to}:8000/ip" -s -o /dev/null -w "sleep.${from} to httpbin.${to}: %{http_code}\n"; done; done
sleep.foo to httpbin.foo: 503
sleep.foo to httpbin.bar: 503
sleep.bar to httpbin.foo: 200
sleep.bar to httpbin.bar: 503
```
```
$ kubectl logs --tail=2 -f -n bar sleep-5d7c88d99f-4xz4q -c istio-proxy
[2019-03-26T20:59:02.514Z] "GET /ip HTTP/1.1" 200 - "-" 0 28 17 17 "-" "curl/7.60.0" "80c7c138-ce1c-9002-b32f-40001f5b7538" "httpbin.foo:8000" "10.48.2.33:80" outbound|8000||httpbin.foo.svc.cluster.local - 10.51.255.199:8000 10.48.1.48:35026 -
[2019-03-26T20:59:03.271Z] "GET /ip HTTP/1.1" 503 URX "-" 0 69 100 100 "-" "curl/7.60.0" "57c73ea9-32ad-91f3-9254-515af390d588" "httpbin.bar:8000" "10.48.1.47:80" outbound|8000||httpbin.bar.svc.cluster.local - 10.51.255.79:8000 10.48.1.48:56632 -
```
```
$ kubectl logs --tail=2 -f -n bar httpbin-9d88f6c98-tpr48 -c istio-proxy
[2019-03-26T20:59:03.285Z] "GET /ip HTTP/1.1" 503 UAEX ""UNAVAILABLE:upstream connect error or disconnect/reset before headers"" 0 69 55 - "-" "curl/7.60.0" "57c73ea9-32ad-91f3-9254-515af390d588" "httpbin.bar:8000" "-" - - 10.48.1.47:80 10.48.1.48:57582 outbound_.8000_._.httpbin.bar.svc.cluster.local
[2019-03-26T20:59:03.369Z] "GET /ip HTTP/1.1" 503 UAEX ""UNAVAILABLE:upstream connect error or disconnect/reset before headers"" 0 69 1 - "-" "curl/7.60.0" "57c73ea9-32ad-91f3-9254-515af390d588" "httpbin.bar:8000" "-" - - 10.48.1.47:80 10.48.1.48:57586 outbound_.8000_._.httpbin.bar.svc.cluster.local
```
```
$ istioctl authn tls-check sleep-5d7c88d99f-4xz4q.bar httpbin.bar.svc.cluster.local
HOST:PORT                              STATUS     SERVER     CLIENT     AUTHN POLICY     DESTINATION RULE
httpbin.bar.svc.cluster.local:8000     OK         mTLS       mTLS       default/         default/bar
```

Why, if the destination rule is namespaced to `bar`, does the connection from `sleep.bar`->`httpbin.foo` work, but not `sleep.bar`->`httpbin.bar`?

**Comment by jericks-duo** [comment]
```
$ kubectl apply -f - <<EOF                                  
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "default"
  namespace: "bar"
spec:
  host: "httpbin.bar.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
EOF
destinationrule.networking.istio.io/default created
```
```
$ for from in "foo" "bar"; do for to in "foo" "bar"; do kubectl exec $(kubectl get pod -l app=sleep -n ${from} -o jsonpath={.items..metadata.name}) -c sleep -n ${from} -- curl "http://httpbin.${to}:8000/ip" -s -o /dev/null -w "sleep.${from} to httpbin.${to}: %{http_code}\n"; done; done
sleep.foo to httpbin.foo: 503
sleep.foo to httpbin.bar: 200
sleep.bar to httpbin.foo: 503
sleep.bar to httpbin.bar: 200
```

This behaves as expected. Is there something funny going on with the `*.local` host?

**Comment by jericks-duo** [comment]
> We recently changed how we look for DestinationRules. We look in the namespace of the source and destintion (foo and bar) and the root config namespace (defaults to istio-system). It no longer will search all namespaces. So in the default setup, I think you would need to add the DR to either foo, bar (probably want both), or istio-system.

Given this comment by @howardjohn, this behavior makes sense as well:

```
$ cat destinationrule.yaml 
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "httpbin.bar"
  namespace: "bar"
spec:
  host: "httpbin.bar.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "httpbin.foo"
  namespace: "bar"
spec:
  host: "httpbin.foo.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
```
```
$ kubectl apply -f destinationrule.yaml 
destinationrule.networking.istio.io/httpbin.bar created
destinationrule.networking.istio.io/httpbin.foo created
```
```
$ for from in "foo" "bar"; do for to in "foo" "bar"; do kubectl exec $(kubectl get pod -l app=sleep -n ${from} -o jsonpath={.items..metadata.name}) -c sleep -n ${from} -- curl "http://httpbin.${to}:8000/ip" -s -o /dev/null -w "sleep.${from} to httpbin.${to}: %{http_code}\n"; done; done
sleep.foo to httpbin.foo: 503
sleep.foo to httpbin.bar: 200
sleep.bar to httpbin.foo: 200
sleep.bar to httpbin.bar: 200
```

**Comment by howardjohn** [comment]
Seems to me to be a duplicate (in terms of work to be done) of https://github.com/istio/istio/issues/14817, just need to update docs for the DR resolution

**Comment by howardjohn** [comment]
Going to close this to consolidate with https://github.com/istio/istio/issues/14817 -- thanks everyone for digging into this
