### ISSUE TITLE
Are compiledAdapter and adapter the required fields in Mixer Handler 1.0 & 1.1 ?

### ISSUE THREAD

**Issue by idouba** [istio/istio#12732]
Are compiledAdapter and adapter is the required field in 1.1 Mixer [Handler](https://istio.io/docs/reference/config/policy-and-telemetry/istio.policy.v1beta1/#Handler)?

And the two field are also marked as required filed [in 1.0 ](https://archive.istio.io/v1.0/docs/reference/config/policy-and-telemetry/istio.policy.v1beta1/#Handler).  But it seems that the two are not  used in 1.0 helm.

**Comment by bianpengyuan** [comment]
If you are defining handler and instance via handler CRD and instance CRD, then this two fields are required. See https://github.com/istio/istio/pull/12689/files for some samples of migrating: e.g. https://github.com/istio/istio/pull/12689/files#diff-d82ce256f2730bbce70ea7fe116c20bf

**Comment by douglas-reid** [comment]
Closing this issue, as the question appears to have been answered.
