### ISSUE TITLE
Re-enable Mixer tests using the new test framework

### ISSUE THREAD

**Issue by ozevren** [istio/istio#12750]
The Mixer tests written on the new test framework are flaking, especially in Prow w/ Kubernetes:
https://k8s-testgrid.appspot.com/istio-postsubmits#integration-k8s-tests

**Comment by douglas-reid** [comment]
Looking at the logs, it seems like the tests fail because of a failure to deploy Istio:

`2019-03-23T00:29:15.002609Z	info	CI	=== FAILED: Deploy Istio ===`

It seems like the first couple of tests run by Prow results in failure, based on pods in pending state.

**Comment by ozevren** [comment]
The issue turned out to be change of behavior with the legacy CRDs. The K8s deployment is not requesting the legacy CRDs. The native version was instantiating the Mixer instance directly, and the default value for the legacy CRD flag causes it to still process legacy CRDs.

I don't have bandwidth to convert the tests to use the new adapter model. I'll disable the K8s version of the tests. I'll keep this bug around to re-enable the tests.

**Comment by douglas-reid** [comment]
@kyessenov can you take a look at this as part of your CRD clean up work?

**Comment by kyessenov** [comment]
We can keep old style CRDs in some parts of the code base since we still support them. This can be a process to migrate all configs and switching flags one-by-one. 

Can we change flags in TF to use old style CRDs for now?

**Comment by ozevren** [comment]
These tests were meant to be baseline tests for using Mixer in the new Test Framework. I think it might be ok to keep the existing behavior for the short term. This can be done by modifying the helm values used when deploying Istio for the Mixer cases, in the test setup phase.

However, I think the thing that will be most beneficial is updating these, so that it works with the latest & the greatest that Mixer does. :)

**Comment by gargnupur** [comment]
@ozevren , @kyessenov : Tests seem to pass now... looks like https://github.com/istio/istio/pull/12851 fixed it?

**Comment by gargnupur** [comment]
spoke too soon.. TestCheck_Allow passes but TestCheck_Deny fails :(

**Comment by gargnupur** [comment]
Tests are passing now.. ok to close?

**Comment by ozevren** [comment]
These are still failing. There is a bunch of them:
https://testgrid.k8s.io/istio-postsubmits#integration-k8s-tests&exclude-non-failed-tests=

**Comment by gargnupur** [comment]
The one's that fail before 03-02 are fixed by @howardjohn fix: https://github.com/istio/istio/commit/81ab4c79e72b938e0b83aa2e5eb62dfcfb2f4ff8.

TestCheck_Deny and TestMixerReport_Direct can be flaky at times, because I think we are not waiting for rules to sink. Will add retries so as to reduce the flakes.

**Comment by gargnupur** [comment]
Update: Looks like all the postsubmit tests are failing because of some authentication in getting boskos resource.. so couldn't make a decision if we can remove flake flags from the tests that were added by this issue yet..
