### ISSUE TITLE
User can configure location of certificates in authentication policy

### ISSUE THREAD

**Issue by XanderStrike** [istio/istio#12757]
**Describe the feature request**
Provide users the option to configure locations of certificates used for configuring the envoy proxy when using mTLS. We want to provide the location of the certificates when configuring the authentication policy.

Right now the authentication policy is using hardcoded paths specific to Kubernetes. In CloudFoundry we put our application instance certs in a different location.

**Describe alternatives you've considered**
We could move the certificates in our application instances, but our application developers depend on the certs being where they are. We could also symlink them, but that seems dirty. It feels like this should be configurable anyway if Istio is meant to be platform agnostic.

**Additional context**
Other folks worth asking about this: @christianang @ndhanushkodi @tstannard @jeffpak

**Comment by rshriram** [comment]
https://github.com/istio/istio/pull/12189 already solved it..

**Comment by XanderStrike** [comment]
Ah... it was merged to master. Last I heard development was happening against release-1.1... thanks.

**Comment by wattli** [comment]
It's already in master, which will be in 1.2 milestone.
