### ISSUE TITLE
Test Framework: Add support for dumping K8s events

### ISSUE THREAD

**Issue by ozevren** [istio/istio#12758]
We're currently dumping pod state and logs when a test fails when running under K8s. We should add dumping of K8s events as well.

**Comment by draveness** [comment]
Hi @ozevren, if this is not taken, I'm willing to start working on this. :)
And I dug into this issue and found out the previous PR https://github.com/istio/istio/pull/9936 which dumps pod state and logs. And by "k8s events", does it mean that we need to dump the `kubectl get events` output?

**Comment by draveness** [comment]
This issue could be closed by #12821
