### ISSUE TITLE
Envoy stats around connections

### ISSUE THREAD

**Issue by Stono** [istio/istio#12764]
Hey, 
We're trying to get some increased visibility into the load balancing of traffic on the mesh, in particular we want to observe changes by enabling [locality aware routing](https://github.com/istio/istio.io/pull/3593/files).

We used to be able to get the following metrics from envoy:

  - `downstream_cx_total` 
  - `downstream_cx_active` 
  - `downstream_rq_total` 
  - `downstream_rq_active`

But they don't seem to be there any more?

@douglas-reid I know some work was done to reduce metrics / metric cardinality, do we only expose certain metrics now?

CC. @liamawhite 
Ta!
Karl

**Comment by douglas-reid** [comment]
@Stono yup. a large number of envoy stats were disabled by default (in an effort to reduce memory consumption, as well as duplication). it was _intended to_ be possible to change the exposed stats, but you'll need to be careful to include all the ones that Istio uses for health checking etc.

More work is needed here to fix it up. See: https://github.com/istio/istio/pull/11398, https://github.com/istio/istio/issues/11992.

**Comment by douglas-reid** [comment]
@Stono @mandarjog should we close this in favor of #12807 ?

**Comment by Stono** [comment]
Probably feels fair @douglas-reid
