### ISSUE TITLE
istio 1.1.1 : envoy proxies keep dying when there are ~600-700 TCP services in a cluster

### ISSUE THREAD

**Issue by gotwarlost** [istio/istio#12765]
**Describe the bug**
We upgraded one of our larger clusters to `istio 1.1.0` from `1.0.6`. This caused all envoy proxies to thrash, constantly reloading with the message `Epoch 0 terminated with an error: signal: killed`. 

Context: We are trying istio http for a few services but the cluster has a lot of older services (~650) that do not have an `http` prefix and so are being treated as TCP services. This was working in istio 1.0 but broke as soon as we upgraded. None of the HTTP services using the proxy are able to serve traffic, except for one test workload that also defines a sidecar to constrain the set of services for egress to ones in its own namespace.

Digging deeper, I created a test rig that creates 1 HTTP service and deployment in a namespace. In addition, I create a sidecar that scopes egress proxies to only the current namespace. Then creating around 700 TCP-type service objects (no corresponding workloads) causes the envoy proxy for the pod to exhibit the problematic behavior. There is no single tipping point at which this happens, the exact number of services needed to reproduce is not clear. Sometimes you have to "nudge" the envoy proxy to crash by `curl`-ing the `http://localhost:15000/config_dump` endpoint. 

**Expected behavior**
All envoy proxies are stable and do not keep reloading

**Steps to reproduce the bug**

Documented in the gist: https://gist.github.com/gotwarlost/e50efe260448f1f1c21d38060c6e56ef

* Install istio 1.1.1 using exactly the commands in `install-istio.md`
* The `workloads.yaml` file has the basic deployment/ service/ sidecar
* While tailing the `istio-proxy` container logs in one window, execute the `create-services.sh` command in another. You will see the container logs flaking out at some point after 600 services have been created.

**Version**
```
$ istioctl version --remote
client version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-17-g2b13318"}
citadel version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
galley version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
ingressgateway version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-17-g2b13318"}
ingressgateway version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-17-g2b13318"}
ingressgateway version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-17-g2b13318"}
pilot version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
policy version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
sidecar-injector version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
telemetry version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
```

```
$ kc version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-13T22:27:55Z", GoVersion:"go1.9.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.8", GitCommit:"4e209c9383fa00631d124c8adcc011d617339b3c", GitTreeState:"clean", BuildDate:"2019-02-28T18:40:05Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Installation**
See gist

**Environment**
AWS

**Cluster state**
Not doing this. My cluster is set up close to a real environment we use and this will cause information leakage about our setup

**Comment by gotwarlost** [comment]
Note that I updated the test rig to use istio 1.1.1 that was just released. Same problem.

**Comment by gotwarlost** [comment]
Also I could not reproduce the problem when the `create-service` script creates services with port name `http`. I created 1000 services in that case and everything continued to work.

**Comment by gotwarlost** [comment]
It looks like what was happening is that the proxy container ran out of memory (limit was set to 128Mi). When I upped those limits the problem _seems_ to have gone away. I will confirm this by tomorrow and close the bug if everything works ok.

**Comment by mandarjog** [comment]
Every TCP service will add new listeners which consumes more memory than just adding a new virtual host. So it is possible that TCP puts you on the other side of the limit.

Can you upload your config dump? There is a possibility that the `sidecar` resource is not taking effect at all, to test that use a simpler sidecar resource.

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: reg
  namespace: istio-test
spec:
  egress:
  - hosts:
    - ./*
    - istio-system/*
```

**Comment by gotwarlost** [comment]
The sidecar resource _was_ taking effect. As you said the ton of TCP resources was causing unexpected memory use (although this seems to have increased from istio 1.0 where the same set up was working).

In any case, upping the memory limits for the sidecar has solved this issue for us. Thanks for the help!

**Comment by dwradcliffe** [comment]
In general I would suggest monitoring cpu and memory usage vs requests/limits and watch for OOM events too.
