### ISSUE TITLE
Gateway sample invalid and makes Ingress go stale

### ISSUE THREAD

**Issue by esnible** [istio/istio#12761]
To reproduce: obtain the `my-gateway` sample from https://istio.io/docs/reference/config/networking/v1alpha3/gateway/ and replace the namespace with `default` and the selector with `istio: ingressgateway`.  Do a `kubectl apply -f` against it.

After this, `istioctl proxy-status` reports LDS is `STALE (Never Acknowledged)`

This is because the sample uses 
```
    tls:
      mode: SIMPLE # enables HTTPS on this port
      credentialName: bookinfo-secret # fetches certs from Kubernetes secret
```

Istio can't validate this, so it allows it.

Pilot reports `warn	ads	ADS:LDS: ACK ERROR` caused by 

```
code:13 message:"Proto constraint validation failed (ListenerValidationError.FilterChains[i]: [\"embedded message failed validation\"] | caused by FilterChainValidationError.TlsContext: [\"embedded message failed validation\"] | caused by DownstreamTlsContextValidationError.CommonTlsContext: [\"embedded message failed validation\"] | caused by CommonTlsContextValidationError.TlsCertificates[i]: [\"embedded message failed validation\"] | caused by TlsCertificateValidationError.CertificateChain: [\"embedded message failed validation\"] | caused by DataSourceValidationError.Filename: [\"value length must be at least \" '\\x01' \" bytes\"]
...
  tls_context {
    common_tls_context {
      tls_certificates {
        certificate_chain {
          filename: ""
        }
        private_key {
          filename: ""
        }
      }
...
```

I have snipped out the problem to make it more obvious.  It is hard to spot in a large dump.  

The User Experience problem here is that a single typo in a Gateway brings down Istio for any pod matching the workload _selector_.

It would be better if Envoy could communicate to Pilot the problem, and a K8s Event could be attached to the Gateway explaining the problem.

**Comment by jeremygiberson** [comment]
@esnible can you elaborate what the typo is? I seem to be experiencing this issue but I'm not sure how to resolve it.

**Comment by marshallford** [comment]
@jeremygiberson I ran into this error because I used the `sds` installation profile thinking that would configure the ingress gateway to pick up secrets created by cert-manager. After re-reading the [docs](https://istio.io/docs/tasks/traffic-management/secure-ingress/sds/#configure-a-tls-ingress-gateway-using-sds) I realized my mistake. Be sure to enable SDS for the ingress gateway specifically. Cluster SDS and ingress gateway SDS seem unrelated (please correct me if I am wrong).

```
--set gateways.istio-ingressgateway.sds.enabled=true
```

Hope this helps!

**Comment by esnible** [comment]
@jeremygiberson The problem is that If using `credentialName:`, the secret must exist.  If the secret doesn't exist Envoy will be unable to retrieve it, and it will put `""` into a field that must contain a non-empty string.

Unfortunately Istio can't validate that the secret exists, because the secret and the Gateway might not be created in order.

**Comment by marshallford** [comment]
@esnible is right on the money. A note to future readers: Cert manager partially solves this problem by issuing a temporary self signed certificate while issuance is in progress. This isn't a perfect fix as Helm has a [set order for applying resources](https://github.com/helm/helm/blob/master/pkg/tiller/kind_sorter.go#L29) and it appears that multiple CRDs aren't guaranteed to be applied in the same order (Certificate and Gateway).

**Comment by xeor** [comment]
Thanks for the tip about sds @marshallford! You ended my 3 day frustration! (tho I did learn a lot of istio debugging on the way).

Using the istio-operator, you need to set:

```
spec:
  gateways:
    ingress:
      sds:
        enabled: true
```

note that there is also an sds under `spec.sds`. That is not the one you are looking for..

**Comment by Ghost---Shadow** [comment]
> Thanks for the tip about sds @marshallford! You ended my 3 day frustration! (tho I did learn a lot of istio debugging on the way).
> 
> Using the istio-operator, you need to set:
> 
> ```
> spec:
>   gateways:
>     ingress:
>       sds:
>         enabled: true
> ```
> 
> note that there is also an sds under `spec.sds`. That is not the one you are looking for..

 istio-operator?

I did a helm template apply with sds enabled, the problem persists. Any ideas?

**Comment by mooperd** [comment]
+1

**Comment by Ghost---Shadow** [comment]
This worked for me

```sh
helm install istio.io/istio --name istio --set gateways.istio-ingressgateway.sds.enabled=true --set sds.enabled=true --namespace istio-system
```

**Comment by ayj** [comment]
The config analyzer may be able to catch this problem. cc @sushicw

**Comment by sushicw** [comment]
Yes, writing an analyzer that covers this case would make sense. 
Adding this to the Analyzers epic.

**Comment by sushicw** [comment]
We have an issue to track that credentialName points to a secret that exists: https://github.com/istio/istio/issues/19097. Closing this issue.
