### ISSUE TITLE
[Proposal] Alternative to ServiceEntry Synthesis

### ISSUE THREAD

**Issue by nmittler** [istio/istio#12776]
ServiceEntry is useful as a resource for authoring services in Istio. However, it has performance issues when used as the mechanism for sending service and endpoint information to Pilot.

**Background:**

Our [current plan](https://github.com/istio/istio/pull/12409) is to have Galley handle k8s service and endpoints events and generate synthetic ServiceEntry resources which it then sends to Pilot over MCP. The main goal of this work is to support endpoints for [multicluster use cases](https://github.com/istio/istio/issues/10589), but it is also a step in removing the k8s dependency in Pilot altogether. 

The ADS processing in Pilot relies heavily on knowing the type of change that occurred: service or endpoints. If the service changed (fairly infrequent), then a full update is required. However, if only endpoints changed, it is a candidate for sending an incremental EDS update to the Envoys. Incremental EDS drastically reduces the load on both Envoy and Pilot.

**The Problem:**

If the service and endpoints are merged together in a ServiceEntry, Pilot then has to perform some level of diff on the resource to determine what changed. Additional processing in Pilot is generally something we want to avoid, given the scalability concerns.

**Proposal:**

To avoid this problem, I propose two new protobuf messages (and Galley collections) which split out the service and endpoints components of ServiceEntry. This will generally not be a user-facing API, but instead will be synthesized by Galley when receiving k8s service/endpoints.  The collections can be served by Galley in two separate snapshots, allowing endpoints to be updated more frequently. When Pilot receives either snapshot, it will be able to process the event immediately based on the collection that was updated (no diff required).  We'll still be using incremental MCP at least for endpoints, if not both (I suspect we'll want to eventually transition all MCP clients in Pilot over to incremental, but we can table that discussion for now).

Additionally we can consider whether the existing ServiceEntry path in Galley should convert to these same protos.

The new protos could live side-by-side in the API repository with ServiceEntry and could even re-use some of the same types. This might help to simplify conversion between the types.

**Comment by andraxylia** [comment]
This is the same as my attempt in istio/api#628 which received strong push back based on various justified or less justified arguments. Maybe we can revisit splitting the Service and Endpoint API for real, instead of continuing the compromise and finding workarounds. These workarounds complicate the code base and do not contribute to the product excellence.

So I propose making this change all the way to the API level.

**Comment by andraxylia** [comment]
Note that the split is only useful if Envoy also supports true incremental EDS, which is the ability to send a single Endpoint (not what some people call incremental EDS which is sending a single cluster). That will be needed for services with large number of endpoints > 1000.

In the absence of incremental EDS in Envoy, Pilot will still have to send the full list of Endpoints for a single Service, so the split will not be so effective. Incremental MCP for ServiceEntry solves the problem of sending a single service with all the endpoints. There is no need to diff those endpoints, just pass them straight to the XDSPush in pilot @Nino-K

**Comment by Nino-K** [comment]
Just to clarify, the current EDS interface that pilot uses it sends all the endpoints associated to a service (hostname). Splitting serviceEntry into two protos would still benefit the current workflow in a sense that 1) we receive only updated endpoints and like @andraxylia mentioned we can just pass them through via EDS update. 2) we no longer have to iterate over the old configStore to do a comparison between `serviceVersion`&`endpointVersion` which were provided via annotations in our original contract.

**Comment by costinm** [comment]
Having separate collection just for endpoints sounds good, that's what I proposed from the start.
 
Having a 5th way to represent endpoint info - I don't see the point or benefits. We can express all the info about endpoint in ServiceEntry - or we can use the ClusterLoadAssignment ( i.e. the envoy proto which we use internally ), or even Service.Entries proto from K8s. In addition to the 3 representations we have IstioEndpoint we use internally. 

And the HDS which we plan to implement soon adds the readiness/health info that is currently missing.

**Comment by costinm** [comment]
In general - the restriction that each 'collection' must have a different proto is arbitrary and should be fixed if it is still a limitation of MCP or Galley.

**Comment by nmittler** [comment]
> In general - the restriction that each 'collection' must have a different proto is arbitrary and should be fixed if it is still a limitation of MCP or Galley.

I don't agree. Even if we provided sub-resource versioning, we still run up against the problem of "what changed?" ... you end up doing the diff all over again. Perhaps Incremental MCP could take sub-resources into account and carve out only a portion of the resource when it sends it ... but that significantly complicates the protocol. And for little benefit, that I can see. If we get to the point of needing sub-resource diffing built into the protocol, I think it's clear that our data model is wrong.

**Comment by costinm** [comment]
I mean - I agree with having different collections, as you suggested. And
it has all the benefits - but without needing another proto to convert back
and forth from.

**Comment by costinm** [comment]
But if we need to use a different proto than ServiceEntry - at least use a repeated ServiceEntry.Endpoint in the body, so we don't have to waste more CPU/memory and have more bugs converting between protos.

**Comment by andraxylia** [comment]
right @nmittler we need to fix this at the root.

**Comment by andraxylia** [comment]
We can consider using the new APIs just for the "synthetic" ServiceEntry and migrate the old API as a separate step.

**Comment by andraxylia** [comment]
@costinm MCP is designed to send Istio resources not sub-messages. All these workarounds just complicate the design. I still do not see a compelling justification on why not do the suggested split.

**Comment by nmittler** [comment]
Ok, sounds like we're in general agreement that this is the right approach.  I'll put together a PR and we can continue the discussion there.

**Comment by nmittler** [comment]
After some rounds of discussion, we've decided not to do this at this time.

Pilot's internal data structures are continuing to evolve. Once we have a better understanding of the "optimal" Pilot data model, we can switch the Galley API over to something more accommodating.
