### ISSUE TITLE
Istio 1.1.1 Helm chart version is 1.1.0

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#12777]
```
 ~/istio/istio-1.1.1/install/kubernetes/helm/istio $ cat Chart.yaml
apiVersion: v1
name: istio
version: 1.1.0
appVersion: 1.1.0
....
```

**Comment by linsun** [comment]
@ibm-jason can you develop a simple script to update the chart version for all Chart.yaml files?  Then we just need to run the script prior to each release.   

cc @duderino @utka

**Comment by ibm-jason** [comment]
@linsun sure thing.

**Comment by utka** [comment]
https://github.com/istio/istio/pull/12762 should fix it for future releases. we need to fix past one.

**Comment by ibm-jason** [comment]
@linsun, @utka:

I took a look at the PR mentioned above ☝️ . Once this change to the `helm_values.sh` file is merged, future releases of `Chart.yml` should have the correct values. 

@utka when you said, `we need to fix past one`, it sounds like we're saying that the PRs we need now should be for the `release-1.0` and `release-1.1` branches to ensure the values are correct in those tagged commits. Is this accurate?

**Comment by ibm-jason** [comment]
@linsun, @utka - BUMP. ☝️

**Comment by howardjohn** [comment]
Previous releases were already manually fixed I believe

**Comment by utka** [comment]
Manually fixed

**Comment by ibm-jason** [comment]
@utka, @linsun sounds like we can close this one then, correct?

**Comment by ibm-jason** [comment]
@utka, @linsun Based on the feedback that the previous releases have had the Chart.yaml file fixed, I think we can close this issue once #12762 is merged.

**Comment by utka** [comment]
Yes, that's correct

**Comment by ibm-jason** [comment]
@utka, @linsun 

Now that #12762 is merged, I've pull down `master` and took a look at Chart.yaml:

```
$ cat install/kubernetes/helm/istio/Chart.yaml
apiVersion: v1
name: istio
version: 1.1.0
appVersion: 1.1.0
tillerVersion: ">=2.7.2-0"
description: Helm chart for all istio components
keywords:
  - istio
  - security
  - sidecarInjectorWebhook
  - mixer
  - pilot
  - galley
sources:
  - http://github.com/istio/istio
engine: gotpl
icon: https://istio.io/favicons/android-192x192.png
```
At this point, the `Chart.yml` file still shows 1.1.0. Should this be 1.1.1 at this point and if so, should we submit a PR to update it?  If 1.1.0 is correct, then I think we can close this issue now.

**Comment by linsun** [comment]
Not for master, master should be updated later to 1.2.

**Comment by linsun** [comment]
@utka @ibm-jason i just downloaded 1.1.2, and I saw a few chart.yaml that I opened still have version 1.1.0.

**Comment by utka** [comment]
I only fixed gs://istio-release/releases/1.1.2/
What is location from where you download?

**Comment by ibm-jason** [comment]
@utka I looked at the Chart.yaml file after `git pull` on the `master` branch.  Shouldn't the Chart.yaml file in the codebase be updated as well? How has gs://istio-release/releases/1.1.2/ been updated? Are the release artifacts the result of a daily build of some kind?

**Comment by utka** [comment]
I updated it manually, but i am fixing the issue which was reason for manual fix.
release artifacts are created not as daily but as monthly release 
More info here
https://github.com/istio/istio/tree/master/release

**Comment by eperdeme** [comment]
The issue exists for the 1.1.3 chart, it is the 1.1.0 tars.

**Comment by howardjohn** [comment]
@utka what is the state of this? Looks like https://github.com/istio/istio/pull/12762 did not do the fix we needed since 1.1.3 has the same issue?

**Comment by sapien99** [comment]
even 1.1.6 seems to have the same issue. We updated vom 1.1.1 to 1.1.2, 1.1.3....right until 1.1.6 now. And everytime helm shows 1.1.0 as the current release. All the images are in the right version of 1.1.6 and istio as a whole is working fine

**Comment by howardjohn** [comment]
Fixed in https://github.com/istio/istio/pull/13993.
