### ISSUE TITLE
Simple Redis fails to connect on 1.1.0

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#12779]
I have a simple setup of a Redis client and Redis server. Without sidecar injection, they can connect fine. Once I enable sidecar injection, I am unable to connect.

Config: https://github.com/istio/tools/pull/95

```
$ kubectl exec -it redis-client-5c7df95955-v8x24 -c redis-client -- redis-cli -h redis-server ping
Error: Server closed the connection
command terminated with exit code 1
```

I don't think it is related to https://github.com/istio/istio/issues/5453, my setup doesn't specify runAsUser.

**Comment by esnible** [comment]
I am using your setup under Istio 1.1.1 on IBM IKS with Kubernetes 1.13.  The pods are injected.

I get "PONG".

My exact commands:

```
kubectl apply -f https://raw.githubusercontent.com/istio/tools/808e81d993a68db28323a3425bef8e59f20619f2/perf/stability/redis/templates/redis.yaml
kubectl apply -f https://raw.githubusercontent.com/istio/tools/808e81d993a68db28323a3425bef8e59f20619f2/perf/stability/redis/templates/client.yaml
kubectl exec $(kubectl get pod --selector app=redis-client --output jsonpath='{.items[0].metadata.name}') -c redis-client -- redis-cli -h redis-server ping
```

**Comment by howardjohn** [comment]
Thanks, maybe I had something weird going on then. Let me test again

**Comment by howardjohn** [comment]
Weird, I had done a clean install of Istio and got this issue, but on a fresh cluster this worked... Going to close this though
