### ISSUE TITLE
Should set priority class for istio components to prevent preempted

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#12786]
As [Pod Priority and Preemption](https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/#how-to-disable-preemption) is GA in kubernetes 1.14.  And the `Preemption` is enabled by default in kubernetes 1.11.  So we should set the highest priority for each istio components. 

```
priorityClassName: system-cluster-critical
```

**Comment by linsun** [comment]
Thanks, agreed @hzxuzhonghu!  

Morven, can you take this one too?

**Comment by loewenstein** [comment]
I would suggest instead of giving the highest possible priority, we should leave room for users to decide. What about adding one or two magnitudes to the globalDefault priority?

**Comment by morvencao** [comment]
Actually we have provide the users the option of `priorityClassName `, see: https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/values.yaml#L374_#L379

Currently default value of `priorityClassName` is empty, should we update to `system-cluster-critical`?

**Comment by linsun** [comment]
+1 @morvencao that works as the default.  And if user wants to tweak it, he/she can.

**Comment by morvencao** [comment]
Can we close this? As we have empty value for priorityClassName and the user is free to update to `system-cluster-critical` if needed.

**Comment by hzxuzhonghu** [comment]
Thanks for your work @morvencao

**Comment by tariq1890** [comment]
I don't see why this should have been closed

**Comment by tariq1890** [comment]
I feel we need a better default than `""`

How do we feel about this now that we are more than a year past this discussion?

**Comment by morvencao** [comment]
@tariq1890  Any comments on this? What default value it should be? 
End user is able to set the priorityClassName other than default "" by the k8s settings.

**Comment by tariq1890** [comment]
Yes. We are setting it in our helm charts, but I am asking for better defaults.

If more customizations of ours are sent upstream, our helm chart management becomes easier.

If you agree on the default to be system-cluster-critical, I can send a PR for that

**Comment by morvencao** [comment]
Feel free to raise PR to update it and add @linsun @hzxuzhonghu as reviewers.
