### ISSUE TITLE
Pilot discovery readiness probe not working

### ISSUE THREAD

**Issue by edussx** [istio/istio#12783]
**Describe the bug**
the readiness probe for Pilot didn't work right on pod start: 
```
Warning  Unhealthy         7s                 kubelet, tess-node-f4mb4.stratus.lvs.ebay.com  Readiness probe failed: Get http://10.199.89.121:8080/ready: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```
and I tried getting into the pilot discovery container and curling localhost but it didn't work either: 
```
root@istio-pilot-785c8cb887-8xfqm:/# curl -iv localhost:8080/ready
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /ready HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.47.0
> Accept: */*
>
``` 
the port 8080 is open and the server is simply time out.

However, in this case Pilot is **functioning** which means all the gateway pods are able to get the correct envoy configs if I disable this readiness probe.

**Expected behavior**
readiness probe should work. Per https://github.com/istio/istio/issues/12308 mentions, at least `curl localhost:8080/ready` shouldn't time out with this ipv4 cluster.

**Steps to reproduce the bug**
clean install istio 1.1

**Comment by hzxuzhonghu** [comment]
any more log from pilot?

**Comment by edussx** [comment]
@hzxuzhonghu I'm not sure if it's related but I missed some `ClusterRole`s for my Galley(didn't notice it was from 1.0.x) and it kept errorring. Once it got fixed, the Pilot discovery readiness probe works well. 

I will close this issue. Thanks!
