### ISSUE TITLE
I cannot find any config for routing with querystring

### ISSUE THREAD

**Issue by gxthrj** [istio/istio#12782]
I want to be able to route through http queryString, but http-match-request has no related configuration.

Then I turned to envoyFilter, hoping to get the queryString, and modify the header according to the queryString, but the public function exposed by lua does not provide an API to get the queryString.

However, envoy has provided the ability to route according to queryString in version 1.6.0.

Does Istio plan to provide such an ability?

**Comment by venilnoronha** [comment]
I'd like to work on this.

**Comment by howardjohn** [comment]
Added support in https://github.com/istio/istio/pull/13730
