### ISSUE TITLE
Docs: Fault injection should use abort instead of timeout

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#1279]
Task fault injection:
https://istio.io/docs/tasks/traffic-management/fault-injection.html

is similar with Injecting Timeouts here. they both set http timeout
https://istio.io/docs/tasks/traffic-management/request-timeouts.html

The fault injection task could instead inject an http abort to simulate a failure:
envoyproxy/envoy#219

**Comment by asomya** [comment]
I'm interested in working on this as an intro to contributing to Istio. So far i have created another yaml to inject a http abort similar to the timeout fault injection. Should i keep the existing timeout fault injection and add this or replace it entirely?

**Comment by andraxylia** [comment]
@asomya welcome and thank you for offering to help with this.

Can you please add a new task for aborts, we need both timeouts and aborts.

**Comment by andraxylia** [comment]
@rshriram I see some issues being closed but without a comment or an explanation. Is it a mistake or some script issue?

**Comment by rshriram** [comment]
late night trolling, sorry.
