### ISSUE TITLE
Templatize the ACME provider in certmanager helm template

### ISSUE THREAD

**Issue by ryan-dyer** [istio/istio#12799]
**Describe the feature request**
Currently enabling certmanager via helm assumes an http01 ACME provider.  There are other providers beyond http01 and it would be nice if these could be specified through values.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by costinm** [comment]
I think a better option is to stop bundling certmanager, and user certmanager own installer. 
Aligned with the 'a-la-carte' model, and the plans to use prometheus operator, etc.
