### ISSUE TITLE
Galley testing for --server-dry-run validation

### ISSUE THREAD

**Issue by esnible** [istio/istio#12803]
Istio 1.2 will support `--server-dry-run` validation of Istio CRDs.  We don't test this.

It would be easy to test this on K8s 1.13 using tests/e2e/tests/galley/galley_test.go. (I could just do a pass through all of the existing validation cases with --server-dry-run. That would catch the case where this PR stops working.)

The build/test pipeline machines use K8s 1.9 which does not support this feature.

Please flag this Issue `Test and Release`.  https://github.com/istio/istio/pull/12670#issuecomment-476724430

**Comment by esnible** [comment]
@ozevren I need advice.  I wrote automated tests for `--server-dry-run` as part of https://github.com/istio/istio/pull/12670/commits/d187dbee30ca4198e5847ef005e7dba35a39cf36 .  But the next commit backed them out because the tests can't pass on the pipeline K8s clusters.  I have neither the skill nor permission to switch the build K8s version.

**Comment by ozevren** [comment]
Hey @esnible I think we should hold on to the bug. You can also keep a PR open.

1.9 is not a reasonable target, we should upgrade our K8s deployments to the minimum baseline that we support, which would be 1.11.

I'll follow up.

**Comment by esnible** [comment]
Removing myself, because we can't write tests for this until we have at least K8s 1.11 in the pipeline.

**Comment by howardjohn** [comment]
We have K8s 1.15 now

**Comment by ozevren** [comment]
@esnible any chance you can get your PR in, now that 1.15 in the lab?

**Comment by howardjohn** [comment]
I also added a new feature to the integ test framework to specify a minimum k8s version, since we run 1.12 - 1.16 in postsubmit, so you can use that. I guess not for this if it only needs 1.11 though
