### ISSUE TITLE
Support: stats regex inclusions, exclusion, and suffixes

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#12807]
At present istio supports 
sidecar.istio.io/statsInclusionPrefixes that translates into `stats_matcher.inclustion_list...`
In order to collect downstream stats at the main inbound port one needs to be able to use
`http.{endpoint_ip}_{port}` like `http.10.16.48.226_8080.downstream_rq_time`
This requires knowing your own IP, which the pilot agent already knows.

In addition to this, we need to be able to specify suffixes as well.

In absence of this feature, a user is required to add `http.` as prefix that drags in too many stats.

**Comment by mandarjog** [comment]
It is a common ask to have `downstream_cx_total,downstream_cx_active,downstream_rq_total,downstream_rq_active` which will be possible efficiently with endpoint_ip.
It will also be possible with regex matches.

**Comment by mandarjog** [comment]
@Stono you will have to add `http.` to the prefixes which is not recommended.

**Comment by Stono** [comment]
Yeah I guess I'll not bother for the time being! Thanks

**Comment by douglas-reid** [comment]
We should include sensible defaults (no shooting yourself in the foot) with any updates here.

**Comment by esnible** [comment]
The https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/metrics/v2/stats.proto#config-metrics-v2-statsmatcher doesn't let us mix inclusions and exclusions.  Our design can be improving inclusions.

It would be straightforward to offer `sidecar.istio.io/statsInclusionRegexps` and `sidecar.istio.io/statsInclusionSuffixes` annotations.  (There seems to be no point in doing exact).

The documentation is at https://www.envoyproxy.io/docs/envoy/latest/api-v2/type/matcher/string.proto#type-matcher-stringmatcher

@mandarjog Would you like to see `sidecar.istio.io/statsInclusionRegexps` or `alpha.sidecar.istio.io/statsInclusionRegexps`.

**Comment by esnible** [comment]
@mandarjog I don't see how to support `{port}`.  Do you have any ideas?

To support `{endpoint_ip}` the code in _bootstrap_config.go_ could get the IP address, but this seems error-prone.  At the point the inclusion_list is constructed we don't yet have communication to pilot.

Would it be reasonable to skip implementing `{endpoint_ip}` and `{port}` and recommend developers do something like `sidecar.istio.io/statsInclusionRegexps=http.[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*_8080.downstream_rq_time`?

**Comment by mandarjog** [comment]
@esnible look at the attached PR.
It already implements prefix and suffix inclusions with endpoint ip via bootstrap.

**Comment by esnible** [comment]
Closing because handled by https://github.com/istio/istio/pull/14212
