### ISSUE TITLE
Without istio-system services in the Sidecar resource, you lose metrics

### ISSUE THREAD

**Issue by Stono** [istio/istio#12813]
Hey, 
I consider this behaviour a little unexpected, but if you're using `Sidecar` to control egress, without appending istio-system services, eg:

```
    - istio-system/zipkin.istio-system.svc.cluster.local
    - istio-system/jaeger-agent.istio-system.svc.cluster.local
    - istio-system/istio-telemetry.istio-system.svc.cluster.local
    - istio-system/istio-policy.istio-system.svc.cluster.local
```

You lose metrics.

Personally I'd expect this to *just work*, istio should probably transparently clusters which are just required for things to be functional.

this graph shows where we didn't have `istio-system` egress routes in our app sidecar:

<img width="1644" alt="Screenshot 2019-03-26 at 20 26 49" src="https://user-images.githubusercontent.com/1486729/55030990-82bd1880-5005-11e9-8a77-cbcc90b9d190.png">

`round(sum(irate(istio_requests_total{destination_service="app.forecourt-service.svc.cluster.local"}[1m])) by (source_app, response_code), 0.001)`

**Comment by Stono** [comment]
As an added comment, it wasn't easy to spot.  We'd actually just mistakenly not used the fqdn, for example:

**Comment by douglas-reid** [comment]
@costinm @rshriram @mandarjog @louiscryan what are our thoughts on defaulting access to `istio-system` resources?  is this the sort of thing that should be automatic (always allow traffic to the gloabl tracing service and `istio-telemetry`)?

Or is this primarily a docs issue (that we should emphasize)?

**Comment by hzxuzhonghu** [comment]
for ux, i vote for make it default

**Comment by Stono** [comment]
Yeah from a UX perspective why would anyone ever do `tracing.enabled=true` and then not want connectivity to tracing services?

**Comment by nrjpoddar** [comment]
Duplicate of this: https://github.com/istio/istio/issues/12237

**Comment by howardjohn** [comment]
Closing in favor of https://github.com/istio/istio/issues/12237
