### ISSUE TITLE
TestConversion/networking.istio.io_v1alpha3_synthetic_serviceEntry is flaky

### ISSUE THREAD

**Issue by ozevren** [istio/istio#12820]
https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/12819/istio-integ-local-tests/7409

**Comment by ozevren** [comment]
This seems to be pretty severe.

**Comment by nmittler** [comment]
Understood.  I know why it's happening and am working on a fix.  In the meantime, I'll send a PR that should quiet CI.

**Comment by nmittler** [comment]
@ozevren temporary fix: #12837

**Comment by nmittler** [comment]
@ozevren why did you close this? https://github.com/istio/istio/pull/12890 hasn't been merged yet

**Comment by ozevren** [comment]
I closed because the test itself is not flaky anymore. If you want to use this to track #12890, we can reopen.

**Comment by nmittler** [comment]
Interesting ... ok, thanks @ozevren
