### ISSUE TITLE
Upgrade to autoscaling/v2beta2

### ISSUE THREAD

**Issue by erikwilson** [istio/istio#12823]
**Describe the feature request**
Upgrade autoscaling/v2beta1 to autoscaling/v2beta2 

**Additional context**
autoscaling/v2beta2 has been available since Kubernetes 1.10, I would like to see istio work well with k3s by default, which has removed the autoscaling/v2beta1 API (see rancher/k3s/issues/90).

The change seems fairly straight forward, I can submit a PR if it will help to get this feature through.

**Comment by hzxuzhonghu** [comment]
all prs are welcome

**Comment by hzxuzhonghu** [comment]
one issue i think is istio support 1.9 in official doc

**Comment by ibuildthecloud** [comment]
@hzxuzhonghu Can you drop support for 1.9?  It's no longer supported by the community I believe.  In general I think 1.10 is a reasonable lower bound.

**Comment by howardjohn** [comment]
I would guess we support 1.11+. The FAQs do say 1.9 but the FAQs also have references to Istio 0.1, so its a bit old. https://istio.io/docs/setup/kubernetes/ says tested on 1.11-1.13. Will verify and report back. 

k3s 0.4 rc has v2beta1 anyways though so less urgent. Not sure if this was a work around for istio or a permanent decision or what though

**Comment by erikwilson** [comment]
autoscaling/v2beta1 was enabled as a work-around for istio.

Interestingly tho, on Kubernetes v1.10.11 bundled with Docker Desktop 2.0.0.3 for macOS api-versions shows only autoscaling/v2beta1.

**Comment by howardjohn** [comment]
Still valid
