### ISSUE TITLE
mTLS probe rewrite with no original probe

### ISSUE THREAD

**Issue by NilsWild** [istio/istio#12828]
**Describe the bug**
When no readiness probe is defined in original pod template and mTLS proberewrite is enabled a readiness probe is added that fails for obvious reasons

**Expected behavior**
no readiness probe

**Steps to reproduce the bug**
create a deployment with a pod that has no readinessprobe with mTLS probe rewrite enabled

**Version**
kubernetes: 1.12.5
istio: 1.1.0

**Installation**
istio cni and istio via helm

**Environment**

**Cluster state**

**Comment by incfly** [comment]
This seems to be quite weird and we should already have some unit test coverage.

Do you mind trying it without cni? CNI AFAIK, interacts with sidecar injector, which might cause some behavior difference...

**Comment by NilsWild** [comment]
I fiddled a bit more and realized that there was no service defined for that deployment as soon as i created the service everything works fine. Think this can be closed
