### ISSUE TITLE
Grafana: "Incoming Success Rate (non-5xx responses)" by Source percentages are wrong

### ISSUE THREAD

**Issue by jaygorrell** [istio/istio#12839]
**Describe the bug**
The Grafana "Incoming Success Rate (non-5xx responses)" by Source percentages are wrong on both the service and workload dashboards. It often wavers above and below 100% when things are working fine... above 100% is the clear indicator something is wrong though.

![image](https://user-images.githubusercontent.com/12174604/55109237-b81c4180-50ab-11e9-8e18-0c980fdc201a.png)

**Expected behavior**
Metric is accurately reported to the dashboard.

**Steps to reproduce the bug**
I'm using the bookinfo example so I assume this is true for any situation. Everything else looks good on the board.

**Version**
1.1.1

**Comment by douglas-reid** [comment]
I believe this was an issue with `irate` v `rate` in the queries. I think this issue was resolved in a prior PR (https://github.com/istio/installer/pull/166).  Closing for now.
