### ISSUE TITLE
Report GRPC response codes when protocol is GRPC

### ISSUE THREAD

**Issue by jshaughn** [istio/istio#12846]
This issue stems from the discussion thread [found here](https://discuss.istio.io/t/grpc-status-codes-in-telemetry/354).

Currently the istio_requests_total telemetry reports HTTP response codes (I've ever only seen 200) for GRPC requests (when request_protocol="grpc").   This doesn't seem correct given that GRPC has its own [set of response codes](https://github.com/grpc/grpc/blob/master/doc/statuscodes.md).

This is true in the 1.1.1 release and prior releases.

Is there a plan to change this behavior?  I've flagged it as a bug but feel free to convert to a feature request if that seems more appropriate.

**Comment by dsanchor** [comment]
I just had same needs and set a workaround (for demo purposes) to configure grpc codes... but the side-effect was that I was forced to lose http ones (due to CEXL and type checking). I commented on this as well:[ CEXL / CEL improvements ](https://github.com/istio/istio/issues/12454#issuecomment-473957417 )

**Comment by mdhume** [comment]
@rlenglet can someone take a look at this issue? or is there an alternate way of exposing GRPC response codes in Istio now?

**Comment by rlenglet** [comment]
@douglas-reid is there any update on this feature?

**Comment by douglas-reid** [comment]
i believe we were awaiting a promised PR from the community. I don't believe that PR ever was sent. I will try to follow up with the individual.

**Comment by jshaughn** [comment]
@douglas-reid Can we get this targeted for 1.5 milestone, it was on the want-list from the wg meeting?

**Comment by Sovietaced** [comment]
Kialia isn't really useful without this feature imo.

**Comment by jshaughn** [comment]
correct!
