### ISSUE TITLE
Thrift Support for Istio 

### ISSUE THREAD

**Issue by chisom-igwe** [istio/istio#12845]
**Describe the feature request**
This feature is necessary because at my company, we use thrift for services and currently, it is not supported by Istio. A conversation on the this has been discussed in the Istio slack channel [here](https://istio.slack.com/archives/C38CF1PEC/p1552688874543900). It seems that the general steps include: 

- [ ] Adding Integration with Envoy's Thrift proxy filter 
- [ ] Add virtual service protocol 
- [ ] Testing

If there are any steps missing, please feel free to modify this feature request
@rshriram

**Comment by hzxuzhonghu** [comment]
We can do that by `envoyfilter` for now

**Comment by pnovotnak** [comment]
Done. See https://github.com/istio/istio/pull/19852

**Comment by zhaohuabing** [comment]
[Aeraki](https://github.com/aeraki-framework/aeraki) can help to support Thrift in an Istio service mesh, including traffic management, such as version-based routing and traffic splitting, and service metrics.

Demo:
http://aeraki.zhaohuabing.com:3000/d/pgz7wp-Gz/aeraki-demo?orgId=1&refresh=10s&kiosk
https://www.youtube.com/watch?v=vrjp-Yg3Leg
