### ISSUE TITLE
Envoy access logs are not showing up

### ISSUE THREAD

**Issue by mehemken** [istio/istio#12854]
**Describe the bug**
I am not getting any access logs even though I am definitely accessing my service.

**Expected behavior**
Envoy access logs.

**Steps to reproduce the bug**
New installation of Istio 1.1 with the `helm template` method on GKE 1.10 (Can we get a version compatibility table). Then do a 
`kubectl logs -n namespace pod-name-adkd89j37823kjw3 | grep -v deprecated`
The `grep` there is necessary because there is a lot of log spam (#12642).

**Version**
Kubernetes v1.10.11-gke.1
Istio 1.1.0

**Installation**
Helm Template

**Environment**
GKE

**Cluster state**
I can give specifics upon request, but I don't want to post private company data.

**Comment by douglas-reid** [comment]
In 1.1, you need to enable Envoy access logs. See: https://istio.io/docs/tasks/telemetry/logs/access-log/ for more details.

**Comment by mehemken** [comment]
Thank you @douglas-reid
