### ISSUE TITLE
Kubernetes deprecating resource versions

### ISSUE THREAD

**Issue by kramvan1** [istio/istio#12859]
**Describe the bug**
Kubernetes is deprecating resource versions, need to move to the new levels
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.14.md#deprecation
- 1.16: `Deployment`, `DaemonSet`, `ReplicaSet` resources from `extensions/v1beta1`, `apps/v1beta1` and `apps/v1beta2` APIs.
- v1.16: `PodSecurityPolicy` and `NetworkPolicy` resources from `extensions/v1beta1` API.
- v1.17: `PriorityClass` resources from `scheduling.k8s.io/v1beta1` and `scheduling.k8s.io/v1alpha1` APIs.
- v1.18: `Ingress` resources from `extensions/v1beta1` API
For most of these, the API replacements have been available for a long time.  Please see https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.14.md#deprecations for full details.

**Expected behavior**
Change the deprecated resource versions used in the deployment yamls

**Steps to reproduce the bug**
Look at deployment yaml definitions

**Version**
latest

**Installation**
kubernetes

**Environment**
kubernetes

**Cluster state**

**Comment by kramvan1** [comment]
@linsun  fyi

**Comment by hzxuzhonghu** [comment]
duplicate with #12211

**Comment by ozevren** [comment]
I
