### ISSUE TITLE
ServiceRoleBinding for Google Cloud Function

### ISSUE THREAD

**Issue by aguromanodg** [istio/istio#12877]
**Describe the bug**
I'm trying to add a Google Service Account into `ServiceRoleBinding` to authorize a Google Cloud Function to certain services.

**Expected behavior**
I expect the GC Function with an specific ServiceAccount as identity, to be authorized according to a ServiceRoleBinding and ServiceRole to perform actions.

**Steps to reproduce the bug**

1. With `ClusterRbacConfig` enabled,
2. Create a `ServiceRole` with the methods and services needed, and 
3. A `ServiceRoleBinding`, referencing that `ServiceRole`, tried with the following:

```
subjects:
  - user: "serviceaccountemail"
```

Where `serviceaccountemail` is the Google Cloud Service Account email.

4. Deploy a Google Cloud Function with that Google Cloud Service Account as identity, and that tries to perform actions defined in the `ServiceRole`, and you will get `403 RBAC: access denied`.

I can achieve this for any user, or for a local serviceaccount with `cluster.local/ns/<namespace>/sa/<serviceaccount>`, but cannot do it for a SA of a GC Function.

**Version**
Istio: `1.1.0`
Kubernetes: `v1.12.5-gke.5`

**Installation**
Downloaded it with `wget -qO- https://github.com/istio/istio/releases/download/${ISTIO_VERSION}/istio-${ISTIO_VERSION}-linux.tar.gz | tar xvz` where `ISTIO_VERSION=1.1.0`

Installed with `helm install` 
Enabled the sidecard injection with

`kubectl label namespace <namespace> istio-injection=enabled --overwrite`

**Environment**
GKE with NodeImage `Container-Optimized OS (cos)`

**Comment by pitlv2109** [comment]
The problem is that Istio mesh uses Kubernetes service accounts, which are different than Google Cloud service accounts. My guess is that you have to federate Google Cloud service account. This is an interesting use case. I'll see if I can find out more.

**Comment by aguromanodg** [comment]
Thanks @pitlv2109 ! Were you able to find something about it?

We have a pretty good setup for authentication and authorization, but we need to enable functions to access some of our services in our cluster. So until we get this fixed for functions, we have set `originIsOptional: true` in the istio policy and allow actions for everyone...but we need to allow only the functions.

**Comment by pitlv2109** [comment]
I think supporting Google Cloud Function is still under development...
@yangminzhu could you confirm?

**Comment by yangminzhu** [comment]
The GCP service account is not supported in Istio authorization. Could you modify your function to attach the [identity token](https://cloud.google.com/functions/docs/securing/function-identity#identity_tokens) with the request, and use Istio Authentication/Authorization policy to check the identity token?

**Comment by aguromanodg** [comment]
thanks @yangminzhu , that was our alternative, and we have done that. Thanks!
