### ISSUE TITLE
Unknown flag used in istio-policy sidecar mixer

### ISSUE THREAD

**Issue by jnsvd** [istio/istio#12879]
**Describe the bug**
The `istio-policy` pod can't be started because in the `mixer` sidecar an unknown flag is passed as argument: `Error: unknown flag: --useTemplateCRDs`

The unknown argument is defined in [this](https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/mixer/templates/deployment.yaml) file, on line 68.

**Expected behavior**
The `istio-policy` pod starting to run successfully

**Steps to reproduce the bug**

Install Istio using helm:
* `helm install istio-init`
* `helm install istio`

With the following custom values:
```
istio:
  prometheus:
    enabled: false
  kiali:
    enabled: true
  servicegraph:
    enabled: true
```

**Version**
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.7-gke.12", GitCommit:"06f08e60069231bd21bdf673cf0595aac80b99f6", GitTreeState:"clean", BuildDate:"2019-02-25T20:37:10Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```

Chart version: 1.1.0

**Installation**
* `helm install istio-init`
* `helm install istio`

**Environment**
Kubernetes, GKE

**Comment by howardjohn** [comment]
This change got added yesterday, to the master branch: https://github.com/istio/istio/commit/a64b2d1f5c0c2aabbb596e738ce128ae7293e6c6

Are you sure you are running 1.1.0? Please run
```
istioctl version --remote
```
So we can verify?

If those are using 1.1.0, then did you install using the Helm chart from master?

**Comment by jnsvd** [comment]
I can't install `istioctl`, getting a 404 when running `curl -L https://git.io/getIstio | sh -` (as instructed [here](https://istio-releases.github.io/v0.1/docs/tasks/installing-istio.html)).

I've installed using Helm repository https://storage.googleapis.com/istio-prerelease/daily-build/master-latest-daily/charts. The image in the cluster is `gcr.io/istio-release/mixer:master-latest-daily`, image ID is `docker-pullable://gcr.io/istio-release/mixer@sha256:11a5d6f59f44f110863ff9244df532b8071cb1522233afa1f8363605d0015d08`.

**Comment by howardjohn** [comment]
Thanks for pointing out the 404.

You are using they daily builds from master, which contains code that is not supported or thoroughly tested, etc.

Please install from the release at https://github.com/istio/istio/releases

More details at https://istio.io/docs/setup/kubernetes/install/

**Comment by jnsvd** [comment]
> Please install from the release at https://github.com/istio/istio/releases

Thanks, I was looking for a more stable repository but I didn't manage to find it.

> More details at https://istio.io/docs/setup/kubernetes/install/

There seem to be no instructions for adding the correct, stable repository here. It may be more clear to add it also [here](https://github.com/istio/istio/tree/master/install/kubernetes/helm/istio), and include instructions for adding the repository on https://istio.io/docs/setup/kubernetes/install/?

I will try out with the updated repository right now.

**Comment by howardjohn** [comment]
Yes currently our documentation doesn't recommend using helm repos and instead downloading the release and installing from there. I believe someone was planning on adding the repo info, I'll follow up there. Thanks for the feedback

**Comment by howardjohn** [comment]
Also -- just noticed the docs you are using were for v0.1 - released 2 years ago, which is why you got a 404. Make sure you are using the latest at istio.io.

I am going to close this since I think it should be working now, but feel free to reopen if you have other issues.

**Comment by jnsvd** [comment]
The installation is now failing when installing `Istio-init`:

```
pulling image "gcr.io/istio-release/kubectl:1.1.1"
Failed to pull image "gcr.io/istio-release/kubectl:1.1.1": rpc error: code = Unknown desc = Error response from daemon: manifest for gcr.io/istio-release/kubectl:1.1.1 not found
Error: ErrImagePull
```

**Comment by howardjohn** [comment]
Sorry, think we ran into another issue, we have been having some issues with the helm repo as it something new we just added. 

In the meantime, can you use 1.1.0 (https://storage.googleapis.com/istio-release/releases/1.1.0/charts) which should work, or install without using the repo.

**Comment by howardjohn** [comment]
Created an issue for that here: https://github.com/istio/istio/issues/12884 
Thanks for finding

**Comment by howardjohn** [comment]
1.1.1 is now fixed, so you can use that as well
