### ISSUE TITLE
Document K8s cluster node resource requirements for the Istio profiles

### ISSUE THREAD

**Issue by esnible** [istio/istio#12880]
What is the minimum number of nodes, and the CPU and memory of the nodes, for the various Istio profiles?

Put this into the documentation under the profiles, probably at https://istio.io/docs/setup/kubernetes/install/helm/

**Comment by Tushar120120** [comment]
Yes, can we have this.
As per "https://docs.giantswarm.io/guides/deploying-istio/"

Some of them, as pilot, have a large impact in terms of memory and CPU, so it is recommended to have around 8GB of memory and 4 CPUs free in your cluster. Obviously, all components have requested resources defined, so if you don’t have enough capacity you will see pods not starting.
