### ISSUE TITLE
Authorization for http services not working

### ISSUE THREAD

**Issue by arielb135** [istio/istio#12881]
**Describe the bug**
Following the tutorial: https://istio.io/docs/tasks/security/authz-http/
when enabling the global istio authorization and supplying the ServiceRole and ServiceRoleBinding - i still see "RBAC access denied".
i'm not sure if it's again documentation issues or it's indeed a bug.

**Expected behavior**
See the product page after applying the exclusion by namespace

**Steps to reproduce the bug**
Just follow the tutorial

**Version**
Kubernetes
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-07-26T20:40:11Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.13-eks-g484b8", GitCommit:"484b857e3134d55ac6373fea2f51798fefa0533f", GitTreeState:"clean", BuildDate:"2019-03-08T05:32:36Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

Istio
client version: version.BuildInfo{Version:"1.1.0", GitRevision:"82797c0c0649a3f73029b33957ae105260458c6e", User:"root", Host:"996cd064-49c1-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-rc.6"}
citadel version: version.BuildInfo{Version:"1.1.0", GitRevision:"82797c0c0649a3f73029b33957ae105260458c6e-dirty", User:"root", Host:"1f4e9557-49cd-11e9-86e9-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-rc.6"}
egressgateway version: version.BuildInfo{Version:"1.1.0", GitRevision:"82797c0c0649a3f73029b33957ae105260458c6e", User:"root", Host:"1f4e9557-49cd-11e9-86e9-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-rc.6"}
galley version: version.BuildInfo{Version:"1.1.0", GitRevision:"82797c0c0649a3f73029b33957ae105260458c6e-dirty", User:"root", Host:"1f4e9557-49cd-11e9-86e9-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-rc.6"}
ingressgateway version: version.BuildInfo{Version:"1.1.0", GitRevision:"82797c0c0649a3f73029b33957ae105260458c6e", User:"root", Host:"1f4e9557-49cd-11e9-86e9-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-rc.6"}
pilot version: version.BuildInfo{Version:"1.1.0", GitRevision:"82797c0c0649a3f73029b33957ae105260458c6e-dirty", User:"root", Host:"1f4e9557-49cd-11e9-86e9-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-rc.6"}
policy version: version.BuildInfo{Version:"1.1.0", GitRevision:"82797c0c0649a3f73029b33957ae105260458c6e-dirty", User:"root", Host:"1f4e9557-49cd-11e9-86e9-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-rc.6"}
sidecar-injector version: version.BuildInfo{Version:"1.1.0", GitRevision:"82797c0c0649a3f73029b33957ae105260458c6e-dirty", User:"root", Host:"1f4e9557-49cd-11e9-86e9-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-rc.6"}
telemetry version: version.BuildInfo{Version:"1.1.0", GitRevision:"82797c0c0649a3f73029b33957ae105260458c6e-dirty", User:"root", Host:"1f4e9557-49cd-11e9-86e9-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-rc.6"}

**Installation**
using helm template
kubectl create -f install/kubernetes/helm/helm-service-account.yaml
```
helm template install/kubernetes/helm/istio --name istio --namespace istio-system --set grafana.enabled=true --set servicegraph.enabled=true > istio.yaml
kubectl create namespace istio-system
kubectl apply -f istio.yaml
```

**Environment**
EKS enviroment

**Cluster state**
3 logs of the "debugging rbac" attached:
[1.txt](https://github.com/istio/istio/files/3018846/1.txt)
[2.txt](https://github.com/istio/istio/files/3018847/2.txt)
[3.txt](https://github.com/istio/istio/files/3018848/3.txt)

**Comment by yangminzhu** [comment]
@arielb135 From the log it seems you didn't enable the authentication for the service, the `source.namespace` attribute is depending on the authentication results, could you enable authentication and try again? Thank you.

**Comment by arielb135** [comment]
I've enabled it for the default namespace, that's why I get rbac error no?
If not, how to enable it for the service?

**Comment by yangminzhu** [comment]
From the envoy config dump (2.txt), looking at the `"name": "172.31.32.103_9080"` listener, it indicates the mTLS is not enabled (no TLS or authN filter config). Could you follow https://istio.io/docs/tasks/security/authn-policy/#globally-enabling-istio-mutual-tls to make sure it's enabled correctly?

**Comment by arielb135** [comment]
> From the envoy config dump (2.txt), looking at the `"name": "172.31.32.103_9080"` listener, it indicates the mTLS is not enabled (no TLS or authN filter config). Could you follow https://istio.io/docs/tasks/security/authn-policy/#globally-enabling-istio-mutual-tls to make sure it's enabled correctly?

You were correct, thank you.
the documentation is pretty confusing..

I'm now having issues with https://istio.io/docs/tasks/security/authz-tcp/
the prerequisites say:
![image](https://user-images.githubusercontent.com/33662254/55317081-79ee9b80-5478-11e9-812a-bd544003a3ec.png)

Those are not the same step?
My failure was that after deploying mongo - i couldn't see the rating.

**Comment by yangminzhu** [comment]
> Those are not the same step?

Yes, they're referring to the same thing here.

> My failure was that after deploying mongo - i couldn't see the rating.

This seems some misconfiguration in networking, maybe some left over from the HTTP task, could you try to clean the cluster and start the TCP task from the beginning? If it still doesn't work, could you run `dump_kubernetes.sh` and upload the output? Thanks
