### ISSUE TITLE
prow/e2e-bookInfoTests-trustdomain.sh stuck forever

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#12885]
See: https://github.com/istio/istio/pull/12844

It has been in state: 

```prow/e2e-bookInfoTests-trustdomain.sh Expected — Waiting for status to be reported```

For over 24 hours

**Comment by utka** [comment]
I don't think that's correct, I just approve the change to enable the test https://github.com/istio/test-infra/pull/1193

**Comment by howardjohn** [comment]
I reran the test and it worked fine, so if we aren't seeing this anywhere else I guess its fixed
