### ISSUE TITLE
Stale bot ignores "no stalebot" label.

### ISSUE THREAD

**Issue by ozevren** [istio/istio#12891]
PRs tagged with "no stalebot" label are still being tagged as stale by the stale bot. The label should be honored.

**Comment by howardjohn** [comment]
It is in the config:
https://github.com/istio/istio/blob/master/.github/stale.yml
If this is happening maybe a bug with the bot

**Comment by ozevren** [comment]
I guess exemptLabels needs to be applied to pull requests as well.

**Comment by howardjohn** [comment]
I think you can make it top level as well
