### ISSUE TITLE
istioctl command to view applied Sidecar configuration

### ISSUE THREAD

**Issue by mdgreenfield** [istio/istio#12896]
**Describe the feature request**
When using namespace isolation and defining `Sidecar` config provide an `istioctl` command to identify what `Sidecar` configuration has been applied to a particular Envoy.

**Describe alternatives you've considered**
If there is a better solution I'd be interested in those as well.

**Additional context**

/cc @howardjohn @hmakkapati

**Comment by Stono** [comment]
I mean `istioctl proxy-config endpoint <proxy name>` will give you the clusters, we use this to validate our Sidecar.

**Comment by leecalcote** [comment]
@howardjohn we're running through the list of UX issues for 1.2. In considering this issue for inclusion, it'd be good to know if you've taken action on it, yet, or not. Could you provide status?

**Comment by howardjohn** [comment]
@leecalcote No work has been done on this

**Comment by esnible** [comment]
@howardjohn @andraxylia I am willing to implement this.

One strategy is to implement https://github.com/istio/istio/issues/16000 and get this information from Envoy.  I am not sure I am skilled enough with pilot-discovery to do this for 1.3.

Another strategy is to fetch all the Sidecar.networking.istio.io objects and write my own ad-hoc client-side _istioctl_ logic to match the Sidecar workload selectors against a pod.  I could print this out as part of `istioctl inspect` or a separate CLI.  https://github.com/istio/istio/pull/15827
