### ISSUE TITLE
Enabling Istio breaks some apps that make outgoing requests

### ISSUE THREAD

**Issue by davidebbo** [istio/istio#12903]
**Describe the bug**

The assumption I'm making is that when enabling Istio in PERMISSIVE mode, it should not break any apps. This assumption was confirmed by @geeknoid.

But in the case of https://github.com/GoogleCloudPlatform/microservices-demo, the currency pod becomes broken when Istio injection is enabled.

**Steps to reproduce the bug**
- Start with a clean cluster
- Clone https://github.com/GoogleCloudPlatform/microservices-demo
- From the app root, run `kubectl apply -f ./release/kubernetes-manifests.yaml` to install the app
- Run `kubectl get svc frontend-external` and hit the external IP to make sure the app works
- Install Istio. I used the [Quick Start Evaluation Install](https://istio.io/docs/setup/kubernetes/install/kubernetes/) PERMISSIVE steps
- Run `kubectl label namespace default istio-injection=enabled` to enable injection
- Run `kubectl delete pod --all` to restart all the pods

**Result**: the *currency* pod crashes on start
**Expected**: in permissive mode, the app should not be affected

Note that it can be fixed by adding a [ServiceEntry](https://github.com/GoogleCloudPlatform/microservices-demo/blob/a84331eda142178eef8115b4a2708cfbde6b29d5/release/istio-manifests.yaml#L50-L63). But the point is that in permissive mode, the previously working app should need any Istio specific config to be kept running.

**Version**
Using Istio 1.1.1

**Installation**
See repro steps above.

**Environment**
GKE

**Comment by geeknoid** [comment]
We really need to be a on a plan of "deploy Istio and things just work". Otherwise, the first thing an operator must do when deploying Istio is to debug why their system stopped working.

**Comment by howardjohn** [comment]
I think this is related to https://github.com/istio/istio.io/issues/3883.

It is very frustrating/confusing that having a traffic policy of ALLOW_ANY effectively means any traffic not on port 80 (or others once you create services on them).

**Comment by esnible** [comment]
> I think this is related to [istio/istio.io#3883](https://github.com/istio/istio.io/issues/3883).
> 
> It is very frustrating/confusing that having a traffic policy of ALLOW_ANY effectively means any traffic not on port 80 (or others once you create services on them).

`ALLOW_ANY` is confusing because it doesn't do what is expected.  Apparently the other choice is `REGISTRY_ONLY` but our documentation page https://istio.io/docs/reference/config/installation-options/#global-options doesn't document the setting or the other possible values.

Another reason it is confusing is that developers must ask the operator what mode Istio was installed in.  Users should be able to discover the most important settings through the CLI.  I have drafted https://docs.google.com/document/d/11n1TvXoXiaaBKnZSoMf6KDZ_-Otf2GMcTHs_U4SJsQc/edit to address this issue.

**Comment by howardjohn** [comment]
Potential fix: https://github.com/istio/istio/pull/12916

**Comment by davidebbo** [comment]
@howardjohn thanks for getting the fix in. Which release to you expect it to go in? From what I can tell, it is not in `1.1.2`.

**Comment by howardjohn** [comment]
It will be in 1.1.3, should be around 4/15. It is behind a feature flag currently though as we haven't done enough testing yet

**Comment by davidebbo** [comment]
Cool, I'll try it once 1.1.3 is out. What's the basic instruction on enabling/disabling the feature flag?

**Comment by howardjohn** [comment]
Here are the docs: https://istio.io/docs/examples/advanced-gateways/egress-gateway/#before-you-begin

They probably should not have been released yet as the flag isn't released yet, but 1.1.3 will be out 4/15ish so at that point the docs will be correct

**Comment by howardjohn** [comment]
Fixed in 1.1.4 by the PRs linked above
