### ISSUE TITLE
[helm] Switching from init-container to istio-cni

### ISSUE THREAD

**Issue by StefanCenusa** [istio/istio#12906]
**Describe the bug**
I've tried switching from using init-containers to configure pod networking to using istio-cni. Everything worked fine, but some options from `values.yaml` were not taken into account when installing with `istio_cni: enabled: true`.

```
proxy:
     includeIPRanges: "100.64.0.0/10"
```

is ignored when `istio_cni: enabled: true`.

At a closer inspection, I noticed that the sidecarInjector-configmap sets `includeIPRanges` only on the istio-init container, thus when istio-cni is enabled those annotations are not set on the pod for the istio-cni to use at a later time.

**Expected behavior**
I was expecting that the sidecarInjector to still add the right annotations to the pods (as described [here](https://istio.io/docs/setup/kubernetes/additional-setup/cni/#traffic-redirection-details))

**Steps to reproduce the bug**
Install istio-cni & istio via helm charts;
enable istio-cni;
try to set includeIPRanges from helm chart;

**Version**
release-1.1

**Installation**
helm

**Comment by dmccaffery** [comment]
This just smacked us in the face too. :feelsgood: 

Looking at workarounds now (probably by modifying the helm chart a bit) -- will report back if we have any success!

**Comment by john-a-joyce** [comment]
Just catching up with this now.  If this is still an issue and you have not found any workarounds that are satisfactory could you raise in issue on the istio/cni repo directly as well.   Unfortunately, the Istio community wanted the CNI and Istio repos split so we can't directly get any of the Istio helm values when installing the CNI.  In fat the CNI install is completely decoupled from Istio and occurs before the Istio install.  We can investigate if these values are propagated to somewhere where the CNI can get them.  Another possible solution that would be quite straight forward is to replicate some of these same helm values in the CNI repo charts.

**Comment by tiswanso** [comment]
The pod annotation `traffic.sidecar.istio.io/includeOutboundIPRanges` is the parameter to pass to the istio-cni for this (also for the init-container).  

For your work-around to get the same behavior as defaulting to the istio/istio helm setting, the sidecar-injector-configmap could be modified to set that pod annotation.
