### ISSUE TITLE
Unable to configure volumes for Prometheus via Helm chart

### ISSUE THREAD

**Issue by msoule-cb** [istio/istio#12915]
The prometheus template here: https://github.com/istio/istio/tree/master/install/kubernetes/helm/istio/charts/prometheus/templates 

Does not have options for configuring persistent volumes, persistent volume claims, or storage classes. `stable/prometheus` does: https://github.com/helm/charts/tree/master/stable/prometheus/templates

Many Prometheus users will need to be able to configure those options. The Istio Helm chart should provide a way so users don't need to apply custom configuration on top of the Helm chart.

**Comment by douglas-reid** [comment]
The addon that Istio exposes is not meant to expose the full set of Prometheus configuration options, etc. As you point out, there are many different repos that offer full-fledged Prometheus installations.

In the 1.2 timeframe, we hope to ease support for existing Prom installs, etc. During that time, we can revisit how configuration options get exposed.

**Comment by msoule-cb** [comment]
Then what is the use case for having Prometheus installable from Istio's Helm chart at all?

**Comment by douglas-reid** [comment]
@msoule-cb the addon is really intended as an example of how to use Prometheus with Istio. At best, the addon should be thought of as a temporary store (defaults to retention period of `6h`) from which important metrics should be exported to a more production-grade deployment/store. This can be achieved via federation and/or using the addon config in your production system. Istio should not, imho, own managing production deployment and configuration of the addons.

That being said, Istio should strive to make using production deployments easy -- this is where we have work to do and why I'm tagging it for 1.2 (and part of the Code Mauve effort).

Does that make sense?

**Comment by msoule-cb** [comment]
@douglas-reid Thanks for the explanation. Perfectly reasonable that Istio doesn't manage production deployment of Prometheus. It does leave the user to forge our own production deployment patterns of Istio + addons. I hope Code Mauve assists in this way.

**Comment by peter-c-larsson** [comment]
I have created a PR to add PVC to prometheus since we are suffering from that in our Istio installation: https://github.com/istio/istio/pull/13698

**Comment by howardjohn** [comment]
We have support for this in the operator/new installer, I don't think there are any plans to add this for the legacy installer. See https://github.com/istio/istio/pull/13698#issuecomment-498079063 for details. Thanks!
