### ISSUE TITLE
Istio PR bot doesn't respect Github approvals

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#12919]
Reviewers commonly give "Github Approve". The istio-testing bot does not treat these as /lgtm or /approve.

This leads to a lot of PRs that should be approved but aren't.

One example: https://github.com/istio/istio/pull/12857

**Comment by pitlv2109** [comment]
Same with this PR #12849

**Comment by pitlv2109** [comment]
Has this been fixed? I think it's happening again (https://github.com/istio/api/pull/885)

**Comment by ozevren** [comment]
I think this is a well-known limitation. My understanding is, this can't be fixed in a cheap way.

**Comment by howardjohn** [comment]
https://prow.k8s.io/command-help "/lgtm [cancel] or GitHub Review action" sounds like its bug and should support github review action?

**Comment by ozevren** [comment]
Interesting. I've never seen it working though. We always needed explicit lgtms

**Comment by geeknoid** [comment]
We'll switch to mergify and get this behavior. #14873
