### ISSUE TITLE
TestSplitHorizonEds test flake

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#12911]
Example failure: https://circleci.com/gh/istio/istio/369443?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

@ymesika @hzxuzhonghu

**Comment by hzxuzhonghu** [comment]
find that it has something todo with `defer s.removeCon(con.ConID, con)`->removeEdsCon  just called after `s.addEdsCon(cn, con.ConID, con)`, which means the `edsClusters` does not contain the requested cluster, so the test flakes.

**Comment by hzxuzhonghu** [comment]
It is a deeper time sequence error in xDS server.
