### ISSUE TITLE
Daily Build Repository causes Issues

### ISSUE THREAD

**Issue by bradenwright** [istio/istio#12923]
**Describe the bug**
There has been a number of times we go to rebuild our env and the Istio chart won't install.  2 recent issues were related to upgrading the CertManager subchart and CRDs not being created.  I think a daily build is a good idea, but is there a more stable repo, or stable version that can be used as well.  Also curious about CICD that's run b/c the issue with the missing CRD didn't allow galley and pilot to start so gateways weren't working.  I know things are moving fast which is good, but having a stable way to install Istio via helm is super important in my eyes.

**Expected behavior**
If I have a chart on disk already and I need to rebuild a GKE cluster istio chart works properly even if time has gone by.

**Version**
1.10

**Installation**
Helm Chart

**Comment by howardjohn** [comment]
The stable Helm repos can be found under https://github.com/istio/istio/releases ("Helm Chart Index")

We are currently working on adding Helm repo information to istio.io (https://github.com/istio/istio.io/issues/3852). Until then we recommend following https://istio.io/docs/setup/kubernetes/install/helm/

**Comment by tiswanso** [comment]
Correction on @howardjohn 's comment... the issue for providing helm repo documentation is istio/istio.io#3703.  The other one, istio/istio.io#3852, is for Istio CNI documentation updates to match the current recommended helm install.

**Comment by howardjohn** [comment]
Documented at https://istio.io/docs/setup/kubernetes/download/

Please reopen if you have other issues

**Comment by bradenwright** [comment]
Also worth noting for anyone who comes across this.  If you want to ensure you can install the same "version" of Istio, you may also want to set `.Values.global.tag` to something like `master-20190424-09-16` by default its `master-latest-daily` which means you can get new versions of docker images.

This has broken Istio on my, most recently Sidecar injector wouldn't start.  So I've started to download my releases and use them from disk and set `.Values.global.tag` to something I've tested and consider stable.

I really feel this should be the default values and that there should be more thorough testing via CI/CD before publishing.  You know have a stable helm repo, nightly is probably only what a small majority of people want.  And I'm pretty sure most people expect to be able to use a chart with default values and a public helm repo, and have it continue to work.

**Comment by howardjohn** [comment]
We do have a stable helm repo it's on https://github.com/istio/istio/releases. If you want stable releases then don't use our development builds.

**Comment by bradenwright** [comment]
@howardjohn unless I'm missing something both issue I mentioned are still a concern:

(1)  https://github.com/istio/istio/releases is not a helm repo that I can add via `helm repo add istio https://github.com/istio/istio/releases`

`Error: Looks like "https://github.com/istio/istio/releases" is not a valid chart repository or cannot be reached: Failed to fetch https://github.com/istio/istio/releases/index.yaml : 404 Not Found`

(2) Chart.yaml version is 1.1.0 for all 1.1.x releases

I've been able to work around the issue by pinned the docker tag via helm value, and downloading the release and pointing to it in my requirements.yaml.  

Having an Istio chart setup to be stable by default would be much preferred.  This setup is good for bleeding edge development, but if I'm coming from the world of use Helm and the Stable repo... I expect Helm install to be more reproducible, versioned properly (bumping for every change), and preferably tested.
