### ISSUE TITLE
Prow tests are broken, Failed to get Boskos resource

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#12920]
All prow E2E tests are currently failing. Example: https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/12916/istio-pilot-e2e-envoyv2-v1alpha3/17520

```
+ echo 'failed to get a Boskos resource'
failed to get a Boskos resource
+ return 1
+ cleanup
+ [[ True == \T\r\u\e ]]
+ unsetup_clusters
++ kubectl config current-context
error: current-context is not set
```

**Comment by utka** [comment]
I do not see anything particularly bad in logs, the clusters are cleaning up and released, we are slowly getting more available resources.

**Comment by icygalz** [comment]
Seems like some of the resources are free now.
https://velodrome.istio.io/dashboard/db/boskos-dashboard?orgId=1&panelId=4&fullscreen&from=1553879782654&to=1553888147207

We have a total of 89 clusters managed by boskos right now and from the past 30days(except today), ~50% of these are free..
https://velodrome.istio.io/dashboard/db/boskos-dashboard?orgId=1&panelId=4&fullscreen&from=1551299260750&to=1553887660750

we can increase the number of clusters if we are seeing this issues again/often as this might be a red herring.

**Comment by howardjohn** [comment]
Seems to be fixed

**Comment by howardjohn** [comment]
Happening again

https://velodrome.istio.io/dashboard/db/boskos-dashboard?orgId=1

**Comment by icygalz** [comment]
I think we should increase the number of instances + timeout used by test while waiting for boskos resources.

**Comment by utka** [comment]
Adding 20 more projects
