### ISSUE TITLE
TestProcessor_EventAccumulation is flaky

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#12935]
https://circleci.com/gh/istio/istio/370624?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

/assign @ozevren 
(for dispatch)

**Comment by ozevren** [comment]
This should be fixed now:
https://testgrid.k8s.io/istio-postsubmits#unit-tests&include-filter-by-regex=EventAccumulation
