### ISSUE TITLE
Mixer unable to parse attributes correctly

### ISSUE THREAD

**Issue by Daniel-Houston** [istio/istio#12934]
**Describe the bug**

I have a custom authorization template instance configured to be called by mixer:
```
# instance for template authorization⏎                                                                                  
apiVersion: "config.istio.io/v1alpha2"⏎                                                                                 
kind: authorization⏎                                                                                                    
metadata:⏎                                                                                                              
 name: iam-authorization⏎                                                                                               
 namespace: istio-system⏎                                                                                               
spec:⏎                                                                                                                  
  subject:⏎                                                                                                             
   user: source.principal | ""⏎                                                                                                    
   groups: "groups/ENGINEERING"⏎                                                                                        
  action:⏎                                                                                                              
   namespace: "istio-system"⏎                                                                                           
   service: tester⏎                                                                                                     
   path:  "/"⏎            
```
However, when I run mixer server, I get the following error: 
`failed to evaluate expression for field 'Subject'; failed to evaluate expression 
for field 'Subject.User': unknown attribute source.principal`

The odd thing is, I get the same error if I use a string as a user. For example, if in the config above, subject.user = "hello", I will get the same error:

`failed to evaluate expression for field 'Subject'; failed to evaluate expression 
for field 'Subject.User': unknown attribute hello`

**Expected behavior**
I expected Subject.User to be parsed correctly

**Steps to reproduce the bug**
Configure mixer to run with the above authorization template configuration

**Version**
I am running mixer on the latest master branch using the following command:
`$GOPATH/out/linux_amd64/release/mixs server --configStoreURL=fs://$(pwd)/mixer/adapter/mygrpcadapter/testdata`

**Installation**
cloned from github, running locally with the command above

**Environment**
archlinux

**Cluster state**
not deployed in any cluster

**Comment by Daniel-Houston** [comment]
It seems similar to this issue: https://github.com/istio/istio/issues/12494, but I have verified that the attribute I'm using exists

**Comment by douglas-reid** [comment]
Do you have the template you are using? What is the template type for `subject`? Is it `map<string, string>`?

**Comment by Daniel-Houston** [comment]
I determined the problem was that I was missing the 'attributes.yaml' file in my configStoreURL folder. Is there somewhere in the documentation that is stated and i just missed it? I would recommend making that a little more clear for people trying to develop custom adapters in the future

**Comment by Daniel-Houston** [comment]
@douglas-reid I am using the authorization template

**Comment by Daniel-Houston** [comment]
Turns out I needed to include the attributes.yaml file in my configurations. The attributes.yaml file can be found in `mixer/testdata/config/attributes.yaml`

**Comment by douglas-reid** [comment]
This appears to be resolved. Closing.
