### ISSUE TITLE
No expected locality aware loadbalancing

### ISSUE THREAD

**Issue by osswangxining** [istio/istio#12947]
**Describe the bug**

The locality arware loadbalancing is enabled with the following configuration in values.yaml which is used for Helm installation. For the following configuration, the services from two regions (e.g. cn-beijing and cn-hangzhou) cannot be accessed to each other. So it looks that the distribute config is available for locality.

localityLbSetting:
    distribute:
    - from: "cn-beijing/*"
      to:
        "cn-beijing/*": 100
    - from: "cn-hangzhou/*"
      to:
        "cn-hangzhou/*": 100

But when we change to the following parameters (weight ratio 80:20 for two regions), and each region has 3 pods. Per the localityLbSetting/distribute definition, the traffic should be routed to the same region( with 80% traffice) when the service in one region tries to call the other service. But in the actual verification testing, the routing is scheduled with Round-Robin way.
 
localityLbSetting:
    distribute:
    - from: "cn-beijing/*"
      to:
        "cn-beijing/*": 80
       "cn-hangzhou/*": 20
    - from: "cn-hangzhou/*"
      to:
        "cn-hangzhou/*": 80
        "cn-beijing/*": 20

**Expected behavior**
Locality aware routing should be enabled with correct weight.

**Version**
Istio 1.1.1 
**Install**
Helm installation

**Comment by hzxuzhonghu** [comment]
Can you show me your node yaml? This feature rely on node annotation to acquire the locality.

**Comment by osswangxining** [comment]
> Can you show me your node yaml? This feature rely on node annotation to acquire the locality.

Thanks for your help, I paste them here. Annotation or Labels for locality info retrieval? 

apiVersion: v1
  kind: Node
  metadata:
    annotations:
      flannel.alpha.coreos.com/backend-data: "null"
      flannel.alpha.coreos.com/backend-type: ""
      flannel.alpha.coreos.com/kube-subnet-manager: "true"
      flannel.alpha.coreos.com/public-ip: 192.168.1.170
      kubeadm.alpha.kubernetes.io/cri-socket: /var/run/dockershim.sock
      node.alpha.kubernetes.io/ttl: "0"
    labels:
      beta.kubernetes.io/arch: amd64
      beta.kubernetes.io/instance-type: ecs.n4.xlarge
      beta.kubernetes.io/os: linux
      failure-domain.beta.kubernetes.io/region: cn-beijing
      failure-domain.beta.kubernetes.io/zone: cn-beijing-a
      kubernetes.io/hostname: cn-beijing.i-2ze8304v3rfjbtu3brb0
    name: cn-beijing.i-2ze8304v3rfjbtu3brb0

**Comment by hzxuzhonghu** [comment]
dump the cluster configuration of the src pod

**Comment by osswangxining** [comment]
It looks that the weight value is equal to the number of endpoints. 
[edsz.json.txt](https://github.com/istio/istio/files/3028588/edsz.json.txt)


> dump the cluster configuration of the src pod to see the loadBalancingWeight value

**Comment by hzxuzhonghu** [comment]
oh, i think maybe you do not enable this feature, it is controlled by a flag, by default it is not enabled.

`PILOT_ENABLE_LOCALITY_LOAD_BALANCING`

**Comment by osswangxining** [comment]
> oh, i think maybe you do not enable this feature, it is controlled by a flag, by default it is not enabled.
> 
> `PILOT_ENABLE_LOCALITY_LOAD_BALANCING`

In istio-pilot/discovery POD YAML,  the following environment variable is defined. Is this ok ?

      PILOT_ENABLE_LOCALITY_LOAD_BALANCING:  ON

**Comment by osswangxining** [comment]
> oh, i think maybe you do not enable this feature, it is controlled by a flag, by default it is not enabled.
> 
> `PILOT_ENABLE_LOCALITY_LOAD_BALANCING`

Containers:
   discovery:
    .....  
    Args:
      discovery
      --monitoringAddr=:15014
      --domain
      cluster.local
      --secureGrpcAddr

      --keepaliveMaxServerConnectionAge
      30m
    Requests:
      cpu:      500m
      memory:   2Gi
    Readiness:  http-get http://:8080/ready delay=5s timeout=5s period=30s #success=1 #failure=3
    Environment:
      POD_NAME:                               (v1:metadata.name)
      POD_NAMESPACE:                          (v1:metadata.namespace)
      GODEBUG:                               gctrace=1
      PILOT_PUSH_THROTTLE:                   100
      PILOT_TRACE_SAMPLING:                  100
      **PILOT_ENABLE_LOCALITY_LOAD_BALANCING:  ON**
      PILOT_DISABLE_XDS_MARSHALING_TO_ANY:   1

**Comment by osswangxining** [comment]
btw we are using official Istio 1.1.1.  Do you know if this version already contains this feature or not?

**Comment by hzxuzhonghu** [comment]
why env` **PILOT_ENABLE_LOCALITY_LOAD_BALANCING` contains `**`?

of course, from 1.1.0 it is supported

**Comment by howardjohn** [comment]
1.1.1 contains the feature.

In order for the LB settings to apply, you need the following:

1. `PILOT_ENABLE_LOCALITY_LOAD_BALANCING` set (you have this).
1. A kubernetes `Service` associated with the caller.
1. `outlierDetection` in DestinationRule enabled for the endpoint. (https://github.com/istio/istio/issues/12961 maybe not required in the future)

I suspect you are missing 2 or 3. Please try those out

**Comment by osswangxining** [comment]
> why env` **PILOT_ENABLE_LOCALITY_LOAD_BALANCING` contains `**`?
> 
> of course, from 1.1.0 it is supported

OH, just highlight here, in YAML the env variable name is "PILOT_ENABLE_LOCALITY_LOAD_BALANCING" and its value is assigned as "ON"

**Comment by osswangxining** [comment]
> 3\. #12961

Thank you very much @howardjohn  I have done for 1 & 2,  so that the caller and the service provider are associated with K8s service. But I did not define **outlierDetection** in DestinationRule, as I didn't find any hint about this from document.  Looks like it is required for now. Can you share more info or document or sample with me? Thanks very much.

**Comment by hzxuzhonghu** [comment]
currently **outlierDetection** is not a must for eds locality weighted lb

**Comment by howardjohn** [comment]
Yes that is correct, outlierDetection is not a must for eds locality weighted lb, I was mistaken. See https://github.com/istio/istio/issues/12961 for details.

**Comment by howardjohn** [comment]
I think I figured out the probem. You mentioned you configured this through Helm, right? The Helm support for this feature was just recently added and is not yet released: https://github.com/istio/istio/pull/12683.

Just to verify, could you attach the output of `kubectl -n istio-system get cm istio -o jsonpath={.data.mesh} `?

In the meantime, you can directly modify the istio configmap to include the locality lb settings

**Comment by osswangxining** [comment]
> currently **outlierDetection** is not a must for eds locality weighted lb



> I think I figured out the probem. You mentioned you configured this through Helm, right? The Helm support for this feature was just recently added and is not yet released: #12683.
> 
> Just to verify, could you attach the output of `kubectl -n istio-system get cm istio -o jsonpath={.data.mesh} `?
> 
> In the meantime, you can directly modify the istio configmap to include the locality lb settings

I did change the configmap to add locality lb setting. Below is the configmap content.
.....
# Set the default behavior of the sidecar for handling outbound traffic from the application:
# ALLOW_ANY - outbound traffic to unknown destinations will be allowed, in case there are no
#   services or ServiceEntries for the destination port
# REGISTRY_ONLY - restrict outbound traffic to services defined in the service registry as well
#   as those defined through ServiceEntries
outboundTrafficPolicy:
  mode: ALLOW_ANY

localityLbSetting:
  distribute:
  - from: cn-beijing/*
    to:
      cn-beijing/*: 80
      cn-hangzhou/*: 20
  - from: cn-hangzhou/*
    to:
      cn-beijing/*: 20
      cn-hangzhou/*: 80


# The namespace to treat as the administrative root namespace for istio
# configuration.
rootNamespace: istio-system
.......

**Comment by osswangxining** [comment]
@hzxuzhonghu @howardjohn  any suggestion to debug this will be appreciated greatly!

**Comment by howardjohn** [comment]
Probably not the problem, but Pilot needs to be restarted to pick up the changes to the distribute config if you haven't done that since changing the config.

**Comment by hzxuzhonghu** [comment]
I have no idea, just add some debug info and rebuild a pilot image?

**Comment by osswangxining** [comment]
> Probably not the problem, but Pilot needs to be restarted to pick up the changes to the distribute config if you haven't done that since changing the config.

Yes, I restarted the Pilot container. Do you have running sample files about this feature?

**Comment by osswangxining** [comment]
> I have no idea, just add some debug info and rebuild a pilot image?

Thanks, let me try.

**Comment by howardjohn** [comment]
Ok, it sounds like you have everything set up as required. It is possible this is a bug. It looks like the locallity code is never ran. This could happen if Pilot flag is not set correctly, locallity config is not read correctly, or locallity of the node is not read correctly.

Tomorrow I will try to see if I can reproduced this issue.

**Comment by howardjohn** [comment]
I think I found the issue. You DO need a outlierDetection. This is a bug. This code here needs a different check: https://github.com/istio/istio/blob/c486aaddfc56b1c73f94cbb0168fab4323158a15/pilot/pkg/networking/core/v1alpha3/cluster.go#L790-L797

Here is an example of one:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: outlier
spec:
  host: "google.com"
  trafficPolicy:
    outlierDetection:
      consecutiveErrors: 7
      interval: 5m
      baseEjectionTime: 15m
```

**Comment by osswangxining** [comment]
> ```yaml
> trafficPolicy:
>     outlierDetection:
>       consecutiveErrors: 7
>       interval: 5m
>       baseEjectionTime: 15m
> ```

Thanks a lot. It works after adding this outlierDetection. But not clear the reason why need to add this? Any missing logic?

**Comment by osswangxining** [comment]
btw, when I exec the caller's pod, run curl istio-pilot.istio-system:8080/debug/edsz, it looks that the loadBalancingWeight value is still the number of endpoint for each region.  @hzxuzhonghu @howardjohn could you help confirm this is right or I miss others?

**Comment by howardjohn** [comment]
The reason outlier detection is needed is for the other locallity lb mode, failover. In this mode all traffic is sent to the same region/zone, unless that zone becomes unhealthy. For this case we need the outlier detection, otherwise we would never know when to send traffic out if the zone. For distribute this isn't needed but we had too tight of a restriction. I'll get this fixed soon.

Are you saying you actually see 80/20% traffic like you expect but edsz shows load balancing weights that are different than the actual traffic you see?

**Comment by osswangxining** [comment]
> Are you saying you actually see 80/20% traffic like you expect but edsz shows load balancing weights that are different than the actual traffic you see?

Yes, the actual traffic is splitted to 80:20,  but the edsz shows the loadBalancingWeight is still the size of endpoints within each region. @howardjohn  Thanks a lot again.

**Comment by howardjohn** [comment]
Ok thanks, I reproduced the issue, it sounds like a bug in the edsz debug endpoint

**Comment by howardjohn** [comment]
edsz outputs https://github.com/istio/istio/blob/6db5cd03157c12e542a335851f239d62f757e8b8/pilot/pkg/proxy/envoy/v2/eds.go#L66

This isn't updated with Sidecar isolation mode, so probably not as useful anymore

Also, it makes sense that edsz cannot give locality information - locality information is calculated on the fly for each client based on the clients locality. edsz gives the global state in pilot, so since we don't know the locality, we cannot expose the locality information

**Comment by osswangxining** [comment]
@howardjohn  Thanks to make this more clear.

**Comment by sathishkumar64** [comment]
@howardjohn 

I have one question? How to setup multi region in GKE for Locality-weighted load balancing? Have to create Multicluster with Gateway connectivity ? Because we dont have option for create multi region setup in GKE ?  So how to achieve following setup ?

# localityLbSetting:
  #   failover:
  #   - from: us-east
  #     to: eu-west
  #   - from: us-west
  #     to: us-east

Regards,
Sathish.V

**Comment by howardjohn** [comment]
GKE should be no different than other k8s providers. To get the multicluster setup you should see https://istio.io/docs/setup/kubernetes/install/multicluster/gateways/.

Once you have that setup is it still not working?

**Comment by sathishkumar64** [comment]
@howardjohn 

Thanks for your reply. My question was not setting up for multicluster. How to setup failover with different region?

I can able to test "distribute" with different zone with in same region. But i want to do multi region like US,Europe region. Can you tell me how to do this setup?

Regards,
Sathish V

**Comment by mpanchmatia** [comment]
> The reason outlier detection is needed is for the other locallity lb mode, failover. In this mode all traffic is sent to the same region/zone, unless that zone becomes unhealthy. For this case we need the outlier detection, otherwise we would never know when to send traffic out if the zone. For distribute this isn't needed but we had too tight of a restriction. I'll get this fixed soon.

Hi, I think, we need outlier detection for "Locality-weighted load balancing" mode also. As per Envoy Proxy documentation https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/locality_weight   the weight adjustment happens, when more than 71.4 % of service end points become unhealthy with default over provisioning factor of 1.4 The outlier detection is needed to determine the service instance is healthy or not, as passive health check. 

Please correct me, if I am wrong. 

Thanks. I am posting first time to Istio github and open to learn more.
