### ISSUE TITLE
Test Flake: istio.io/istio/galley/pkg/runtime TestProcessor_Publishing is flakey

### ISSUE THREAD

**Issue by sdake** [istio/istio#12944]
**Describe the bug**
simpletest fails recently with this test case:

https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/12914/istio-unit-tests/23057

**Expected behavior**
test case passes (or code is correct)

**Comment by ozevren** [comment]
This should be fixed now:
https://testgrid.k8s.io/istio-postsubmits#unit-tests&include-filter-by-regex=TestProcessor_Publishing
