### ISSUE TITLE
ServiceEntry is error with timeout

### ISSUE THREAD

**Issue by truyet** [istio/istio#12949]
**Describe the bug**
I setup a service entry, which is using make connection to another service on a diff namesapce in k8s. It's worked, but I can't call this service after about 1 day and I need to resetup this serviceentry

**Expected behavior**
We only setup serviceentry one time

**Steps to reproduce the bug**
You just setup a serviceentry call to another service (diff namespace & not setup sidecar) in k8s and wait about 1 day
**Version**
K8s
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Istio version: 1.1.1

**Installation**
I install it on k8s cluster on AWS using kops
**Environment**
AWS EC2

**Comment by hpohl** [comment]
Can confirm, had this already in 1.0.6. Happens whenever the non-sidecar pod gets replaced by another one (due to rescheduling on another node for example).

**Comment by sdake** [comment]
> Can confirm, had this already in 1.0.6. Happens whenever the non-sidecar pod gets replaced by another one (due to rescheduling on another node for example). I guess in your case this happened in about a day.
> 
> I was hoping 1.1 would fix this but I could not upgrade and check due to another bu

@hpohl can you expand on the upgrade bug?

Thanks
-steve

**Comment by hpohl** [comment]
Due to https://github.com/istio/istio/issues/12801.

**Comment by truyet** [comment]
Hi @hpohl ,
I confirm serviceentry on istio 1.0.6 work well. But this issue has happened since I updated to version 1.1.1 . Pod is connected running a long time 
Pods: 
`postgresql-stolon-proxy-6b46b7469b-8j8zt      1/1     Running     0          15d` 
Service:
`postgresql-stolon-proxy             ClusterIP   100.65.57.57   <none>        5432/TCP   15d`
ServiceEntry
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  clusterName: ""
  creationTimestamp: "2019-03-30T16:55:10Z"
  generation: 1
  name: postgresql
  namespace: default
  resourceVersion: "29320001"
  selfLink: /apis/networking.istio.io/v1alpha3/namespaces/default/serviceentries/postgresql
  uid: 9496e68f-530c-11e9-8054-067727bb92c6
spec:
  hosts:
  - postgresql-stolon-proxy.postgresql.svc.cluster.local
  location: MESH_INTERNAL
  ports:
  - name: postgres
    number: 5432
    protocol: TCP
  resolution: NONE
```

**Comment by philrud** [comment]
@truyet I don't think you need a ServiceEntry here. Your Postgres is a regular service within the same cluster, it should be reachable without any extra configuration. If your Postgres doesn't have a sidecar injected and the rest of your mesh has mTLS enabled, then you might want to define a DestinationRule for Postgres in order to turn mTLS off for that service. See the docs: https://istio.io/docs/tasks/security/authn-policy/#request-from-istio-services-to-non-istio-services

@hpohl would you please provide any extra info on #12801? I'm still looking for ways to reproduce the issue. Thanks!

**Comment by hpohl** [comment]
@philrud I've been trying to reproduce it a bit locally as well, but was unable. Maybe I can slim it down a bit tomorrow. Will also get to tinker a bit around regarding this issue hopefully.

**Comment by truyet** [comment]
Thanks @philrud ,
I tried remove this entry and it worked. But I configured host with `*.postgresql.svc.cluster.local`, it worked well. So what's two way different?

**Comment by howardjohn** [comment]
This was found on a now unsupported version and doesn't have enough info to drive action from. If you run into this in the future please get config dumps https://github.com/istio/istio/wiki/Troubleshooting-Istio#collecting-information-2
