### ISSUE TITLE
Istio BookInfo sample pods not starting on Minishift 3.11.0 - Init:CrashLoopBackOff - message: 'containers with incomplete status: [istio-init]'

### ISSUE THREAD

**Issue by codependent** [istio/istio#12948]
**Describe the bug**
Istio BookInfo sample pods not starting on Minishift 3.11.0  with Init:CrashLoopBackOff - message: 'containers with incomplete status: [istio-init]'

**Expected behavior**
BookInfo pods should start

**Steps to reproduce the bug**
The full information to reproduce this issue is available on Stackoverflow: https://stackoverflow.com/questions/55432252/istio-bookinfo-sample-nos-working-on-minishift-3-11-0-initcrashloopbackoff

**Version**
Istio 1.1.1
Openshift v3.11.0

**Installation**
See referenced SO question

**Environment**
See referenced SO question

**Comment by esnible** [comment]
The log shows

```
+ iptables -t nat -A ISTIO_REDIRECT -p tcp -j REDIRECT --to-port 15001
iptables: No chain/target/match by that name.
+ dump
```

**Comment by codependent** [comment]
@esnible any idea about what could be wrong? I have no clue how to go on...

**Comment by codependent** [comment]
I fixed it manually editing the securityContext of the istio-init container and setting `privileged: true`. Is there any way to automate it?

Notice I use istioctl kube-inject to add the istio container into existing OpenShift DeploymentConfigs

**Comment by esnible** [comment]
The `privileged: true` setting should work automatically.

I am using Istio 1.1.1.  I did `kubectl get cm -n istio-system istio-sidecar-injector -o jsonpath='{.data.config}'` and I see that my injector is configured to add 

```
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
```

and 

```
    securityContext:
      privileged: true
```

to the init container.  Do you see those settings on your configuration?  Do you have a fresh install or an upgraded.  If an upgrade, from which version?

**Comment by codependent** [comment]
I don't have the `privileged: true` bit in the configmap:
```
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
```

I installed Istio following the OpenShift setup (https://istio.io/docs/setup/kubernetes/prepare/platform-setup/openshift/) and the quickstart evaluation install: https://istio.io/docs/setup/kubernetes/install/kubernetes/

I guess that I can manually edit the cm and add the privileged flag. Anyway I'm curious why it wasn't added in the injector configmap.

**Comment by esnible** [comment]
Could this be a duplicate of https://github.com/istio/istio/issues/4500 ?

Would it help if instead of the message "iptables: No chain/target/match by that name." the logs showed something like

```
iptables: No chain/target/match by that name.
istio-init container needs to be privileged
Verify the istio-sidecar-injector sets securityContext:  privileged: true
```
?

**Comment by codependent** [comment]
Well it would definitely help find the problem. +1 for that detailed message.
