### ISSUE TITLE
outboundTrafficPolicy : ALLOW_ANY but I can access to external url

### ISSUE THREAD

**Issue by truyet** [istio/istio#12952]
**Describe the bug**
I setup istio version 1.1.1 with default config:
```
  outboundTrafficPolicy:
    mode: ALLOW_ANY
```
I call wget http://httpbin.org/ in a pod injected sidecar but it return wget: server returned error: HTTP/1.1 404 Not Found

**Expected behavior**
wget success get data from url

**Steps to reproduce the bug**
I cleanup istio 1.0.6 and setup istio version 1.1.1, deploy a pod in injected sidecar namespace and using ssh to this pod and call wget http://httpbin.org/

**Version**
1.1.1

**Installation**

**Environment**
EC2 using kops

**Cluster state**

**Comment by erezzarum** [comment]
You mean can't access external url?

> ALLOW_ANY - outbound traffic to unknown destinations will be allowed, in case there are no services or ServiceEntries for the destination port

If you used the default installation with ingressgateway you already have port 80 (destination port) as a service that Istio (Envoy) is aware of, these it will not work as you have a listener for that port already.

**Comment by truyet** [comment]
Thanks @erezzarum, document doesn't note it, so I try to call as document describe but it not work. 

I have another question. So with configuration ALLOW_ANY, we can call another service in k8s cluster but it's not inject to sidecar ? (my case is postgresql-stolon-proxy.postgresql.svc.cluster.local port 5432 )

**Comment by springrain** [comment]
This problem still exists in version 1.1.3

**Comment by erezzarum** [comment]
@springrain It is not noted in the documents, or perhaps a bug? but you should add an environment variable ``PILOT_ENABLE_FALLTHROUGH_ROUTE``` set to 1 to allow this feature.
If you use the default helm values, add this to your values (considering you didn't modify any other environment variables for Pilot)
```
pilot:
  env:
    PILOT_PUSH_THROTTLE: 100
    GODEBUG: gctrace=1
    PILOT_ENABLE_FALLTHROUGH_ROUTE: 1
```

**Comment by springrain** [comment]
> @springrain It is not noted in the documents, or perhaps a bug? but you should add an environment variable `PILOT_ENABLE_FALLTHROUGH_ROUTE` set to 1 to allow this feature.
> If you use the default helm values, add this to your values (considering you didn't modify any other environment variables for Pilot)
> 
> ```
> pilot:
>   env:
>     PILOT_PUSH_THROTTLE: 100
>     GODEBUG: gctrace=1
>     PILOT_ENABLE_FALLTHROUGH_ROUTE: 1
> ```
Thank you very much, I can increase the PILOT_ENABLE_FALLTHROUGH_ROUTE parameter.

**Comment by howardjohn** [comment]
Sounds like this was fixed with PILOT_ENABLE_FALLTHROUGH_ROUTE, so I am going to close this. This is the default behavior on 1.1.4 by the way.
