### ISSUE TITLE
ServiceEntry MESH_EXTERNAL does not work

### ISSUE THREAD

**Issue by leszko** [istio/istio#12955]
**Describe the bug**
I follow the Bookinfo example and the follow up on [Consuming External Web Services](https://istio.io/blog/2018/egress-https/). After creating the ServiceEntry, the traffic to the external service is still blocked.

So, I still see the following info in the Bookinfo App:
```
Error fetching product details!
```

It works correctly when I check with the Istio version `1.0.6`.

**Expected behavior**
The example should work and the external traffic should be unblocked and show the following message.
```
Book Details
...
```

**Steps to reproduce the bug**
 [Consuming External Web Services](https://istio.io/blog/2018/egress-https/)

**Version**
```
$ istioctl version --remote
client version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-17-g2b13318"}
citadel version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
galley version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
ingressgateway version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-17-g2b13318"}
pilot version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
policy version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
sidecar-injector version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
telemetry version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.7-gke.12", GitCommit:"06f08e60069231bd21bdf673cf0595aac80b99f6", GitTreeState:"clean", BuildDate:"2019-02-25T20:37:10Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Installation**
I installed Istio using `helm template`.

**Environment**
GKE

**Comment by vadimeisenbergibm** [comment]
@leszko First note that you have to enable the blocking policy in Istio 1.1 so the egress will be blocked by default.

Are you able to access https://www.googleapis.com/books/v1/volumes?q=isbn:0486424618 from a pod without Istio?

And which section in the blog post does not work for you: this one https://istio.io/blog/2018/egress-https/#bookinfo-with-https-access-to-a-google-books-web-service or this one https://istio.io/blog/2018/egress-https/#bookinfo-with-tls-origination-to-a-google-books-web-service ?

**Comment by vadimeisenbergibm** [comment]
To enable the blocking policy: http://localhost:1313/docs/tasks/traffic-management/egress/#change-to-the-blocking-by-default-policy

**Comment by leszko** [comment]
@vadimeisenbergibm Thanks for your reply.

To answer your questions:

1. Yes, without Istio I'm able to access Google Apis Books.
```
$ kubectl run curl -it --rm --image=tutum/curl -- sh
# curl https://www.googleapis.com/books/v1/volumes?q=isbn:0486424618
{
 "kind": "books#volumes",
 "totalItems": 1,
...
```

2. About the blog post, the first part somehow does not work. I to follow the steps and:
- If I [Apply Default Destination Rules](https://istio.io/docs/examples/bookinfo/#apply-default-destination-rules), then I always get access to the external service (so cannot really observe the idea of MESH_EXTERNAL)
- If I don't apply the default destination rules, then I don't have access to Google Api even if MESH_EXTERNAL is applied

Could you double check the blog post step by step if it works for you?

3. About the blocking policy, it seems to be enabled for me by default. Anyway, [this part](https://istio.io/docs/tasks/traffic-management/egress/#access-an-external-http-service) worked for me, so the MESH_EXTERNAL works, so maybe it's just Bookinfo Egress blog post that has some steps not updated.

**Comment by vadimeisenbergibm** [comment]
@leszko You have to apply the default destination rules, it is not related to the blog post. So if you apply the default destination rules, and follow the steps of the blog post, does it work for you?

Another thing, can you try `kubectl exec -it <your ratings pod> -c ratings -n default -- curl http://www.googleapis.com:443/books/v1/volumes?q=isbn:04864246` ? It will tell you if you can access googleapis by curl from the Istio-enabled ratings?

**Comment by leszko** [comment]
@vadimeisenbergibm Ok, I know what was wrong, two things I did wrong:
- I didn't set up auto-injection (and my details v2 was not injected with Istio)
- I didn't apply the default  destination rules
Now it works fine, thanks for the help.

I still cannot configure the same scenario for the web service that is in the same Kubernetes cluster. If you know how to do it or there is some documentation out there, please let me know. I've raise a StackOverflow question on that: https://stackoverflow.com/questions/55455523/istio-direct-pod-to-pod-communication

Concerning, this issue, you can close it. Thanks!

**Comment by vadimeisenbergibm** [comment]
@leszko I am glad everything works now. Regarding your question, I think for Istio to operate you need a service, this is the simplest solution. Closing this issue.
