### ISSUE TITLE
MutatingWebhookConfiguration is not a namespaced resource

### ISSUE THREAD

**Issue by mingfang** [istio/istio#12966]
Please remove this line
https://github.com/istio/istio/blob/ac12b0ec83f9c6d18a9e4bef5a44cf0aeff235b7/install/kubernetes/helm/istio/charts/sidecarInjectorWebhook/templates/mutatingwebhook.yaml#L5

**Comment by hzxuzhonghu** [comment]
Also validatingwebhook

**Comment by hobbytp** [comment]
Hi, I have a question, how to support multiple istio in one k8s cluster? according to these kind of admission controller webhooks are not namespace related. It is possible separate them for different istio instances in same k8s cluster? e.g. multi-tenances.
