### ISSUE TITLE
/retest does not trigger prow tests to run

### ISSUE THREAD

**Issue by pitlv2109** [istio/istio#12962]
For example: #12849

**Comment by pitlv2109** [comment]
@utka Feel free to reassign it to someone else. Not sure if that is your territory  :)

**Comment by howardjohn** [comment]
I've had to do `/test <testname>` for it to work

**Comment by pitlv2109** [comment]
I think it worked before. `/retest` would trigger all prow tests at once.

**Comment by ozevren** [comment]
It might be ```/test``` or ```/test all```. Could you give it a try?

**Comment by utka** [comment]
Tried `/test all` It works

**Comment by howardjohn** [comment]
Test all works but the bot says to run `/retest`. People get it confused all the time
