### ISSUE TITLE
Test Flake: istio.io/istio/galley/pkg/runtime.TestProcessor_EventAccumulation_WithFullSync

### ISSUE THREAD

**Issue by ericvn** [istio/istio#12967]
Describe the bug:
Recent failure for subject test

https://prow.k8s.io/view/gcs/istio-prow/logs/istio-postsubmit/4836

Expected behavior:
test case passes (or code is correct)

**Comment by ozevren** [comment]
I believe this was fixed some time ago. The postsubmit board seems to show all green now:
https://testgrid.k8s.io/istio-postsubmits#unit-tests&include-filter-by-regex=WithFullSync
