### ISSUE TITLE
Locality LB outlierDetection requirement

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#12961]
Currently:

- For CDS, outlierDetection is required for both failover and distribute mode.
- For EDS, outlierDetection is not required at all.

I think the correct behavior should be, require outlierDetection for failover mode, for CDS and EDS.

It is needed for failover, as without it we would never drop down to lower priority levels.

I do not see how it is needed for distribute though.

@hzxuzhonghu @liamawhite

**Comment by liamawhite** [comment]
Agreed. Would be good if we can encapsulate this in the locality mutation functions, rather than relying on people remembering to check if outlier is on.

**Comment by howardjohn** [comment]
This is still broken:

For EDS, outlierDetection is not required at all and it should be.

**Comment by howardjohn** [comment]
Fixed in #14099
