### ISSUE TITLE
GolangCI internal error

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#12971]
Example: https://golangci.com/r/github.com/istio/istio/pulls/12916

```
GOLANGCI_COM_RUN=1 golangci-lint run --out-format=json --issues-exit-code=0 --deadline=5m --new=false --new-from-rev= --new-from-patch=../changes.patch
    fatal error: runtime: out of memory
```

**Comment by kyessenov** [comment]
@utka 
This is not a required gate. In fact, things like the above are a good reason why we might hold on to make it required. We run CI check on circleci machine with beefier CPU/memory.

**Comment by howardjohn** [comment]
Seems to be fixed
