### ISSUE TITLE
Include additional debug statements to E2E test scripts

### ISSUE THREAD

**Issue by ibm-jason** [istio/istio#12979]
**Describe the feature request**

While observing the log output from E2E tests, it is difficult to determine the failures that occur in the output. Adding debug statements to the test output that indicate the failures that occur in each of the individual E2E tests would help to clarify which test scripts are failing and why.

**Additional context**

@rvennam and I discovered this while working on https://github.com/istio/istio/issues/11922. As we ran the E2E tests, we realized the difficulty in finding out which scripts in the E2E test(s) were failing, and why.

**Comment by rvennam** [comment]
Currently, it logs:
```
...
=== RUN   TestVersionRouting
...
--- PASS: TestVersionRouting (93.63s)
```
We can improve the output when test fails so you can identify the failing test case and reason faster.

**Comment by ibm-jason** [comment]
@rvennam I slightly reworded the issue description, based on your findings. Sounds like we have the RUN/PASS distinction we need, it's the failure output that would help.
