### ISSUE TITLE
Test Flake: e2e-dashboard (fails to deploy?)

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#12976]
Example failure: https://circleci.com/gh/istio/istio/372670?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Seen this happen at least twice.

**Comment by howardjohn** [comment]
Still flakey if anyone has a chance to take a look. Another example: https://circleci.com/gh/istio/istio/380325?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification

**Comment by ozevren** [comment]
@douglas-reid I am assuming this is under your purview. Could you triage/reroute as appropriate?

Thanks

**Comment by douglas-reid** [comment]
I think this problem has gone away... or at least moved to a different problem.  All of the circleci presubmits are flaky. And the failures are before the tests even start.

Example: https://circleci.com/gh/istio/istio/405299

> Checkout code
git reset --hard "$CIRCLE_SHA1"
Cloning into '.'...
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
remote: Enumerating objects: 97, done.        
remote: Counting objects: 100% (97/97), done.        
remote: Compressing objects: 100% (83/83), done.        
remote: Total 127864 (delta 35), reused 21 (delta 13), pack-reused 127767        
Receiving objects: 100% (127864/127864), 83.38 MiB | 23.31 MiB/s, done.
Resolving deltas: 100% (80630/80630), done.
remote: Enumerating objects: 26, done.        
remote: Counting objects: 100% (26/26), done.        
remote: Compressing objects: 100% (15/15), done.        
  remote: Total 26 (delta 8), reused 20 (delta 8), pack-reused 0        
  Unpacking objects: 100% (26/26), done.
  From github.com:istio/istio
   [new ref]             refs/pull/13759/head -> origin/pull/13759
  fatal: Could not parse object '6d72d06f7b982b3f706c0ad899fa0c24a3b1aad9'.
  Exited with code 128

I'm going to close this issue, as these failures are unrelated to the dashboard test. They should be tracked  in a more appropriate way.

Feel free to reopen if needed.
