### ISSUE TITLE
EDS Unit test is broken

### ISSUE THREAD

**Issue by mbanikazemi** [istio/istio#12994]
The current EDS test is incorrect and passes because the check calls time
out rather than successfully completing.

Return values of some adsc.Wait() calls are not checked and in the following case the parameter being passed is incorrect: https://github.com/istio/istio/blob/master/pilot/pkg/proxy/envoy/v2/eds_test.go#L310-L312

**Comment by esnible** [comment]
Although I believe this is an `area/networking` I believe only the Networking Working Group should assign the label when they acknowledge the issue.  I have removed the label but expect them to restore it.
