### ISSUE TITLE
Using Istio with Couchbase operator 1.1

### ISSUE THREAD

**Issue by mmosttler** [istio/istio#12998]
I am trying to create a Couchbase cluster in GKE with Istio (envoy proxy) using the Autonomous Operator 1.1.
The operator starts up fine, and after running the yaml to create the couchbasecluster the first node starts up and then the 2nd node starts. Issue is that the 2nd node appears to fail to join the cluster and additional nodes are not being started.

I am not sure how to debug what is happening or what needs to be done to get the cluster to start up in my gke cluster. Any assistance is appreceated.

**Version**
Istio 1.0.5
GKE 1.12.5-gke.5
Couchbase Autonomous Operator 1.1

**Installation**
Istio with MTLS

**Comment by esnible** [comment]
Consider running https://github.com/aspenmesh/istio-vet for basic sanity checks for things Istio needs.

According to the Couchbase docs, https://docs.couchbase.com/server/6.0/install/install-ports.html , the Couchbase pods need to communicate using ports 4369, 8091-8096, 9100-9105, 9110-9118, 9120-9122, 9999, 11209, 11210, 18094, 21100-21299.  Probably at least one of these ports is not compatible with the default configuration Istio gives to Envoy.

If Couchbase instances need to communicate outside of the K8s service directly pod-to-pod, and Istio+Envoy is blocking this, the `sidecar.istio.io/inject` annotation can be used to turn off Istio for the Couchbase deployments, or the `traffic.sidecar.istio.io/excludeInboundPorts` can be done to disable Envoy for certain ports.  I don't have a working example for CouchBase.

You can turn off Istio for a particular deployment using

```
kubectl patch deployment <deployment> --type=json --patch='[{"op": "add", "path": "/spec/template/metadata/annotations", "value": {"sidecar.istio.io/inject": "false"}}]'
```

Let us know if that works and is sufficient for your issue.  Turning off Istio completely like this for your pod means no telemetry or Istio rules for Couchbase.  Apps that talk to Couchbase can still use the rules.

**Comment by mmosttler** [comment]
I tried looking into using the istio-vet from aspenmesh, but it seems to not be working with my istio installation or something.  I continually get errors in the log like this:

> github.com/aspenmesh/istio-vet/vendor/github.com/aspenmesh/istio-client-go/pkg/client/informers/externalversions/factory.go:76: Failed to list *v1alpha3.VirtualService: v1alpha3.VirtualServiceList: Items: []v1alpha3.VirtualService: v1alpha3.VirtualService: Spec: v1alpha3.VirtualServiceSpec: VirtualService: Http: []*v1alpha3.HTTPRoute: v1alpha3.HTTPRoute: Timeout: readObjectStart: expect { or n, but found ", error found in #10 byte of ...|timeout":"30s"},{"co|..., bigger context ...|uster.local","port":{"number":8088}}}],"timeout":"30s"},{"corsPolicy":{"allowCredentials":false,"all|...

I tried to patch the couchbase operator deployment and its not starting, seems its health check is failing. 

I am curious about the `traffic.sidecar.istio.io/excludeInboundPorts` option.  do you have any examples (not necessarily for couchbase) that I can work from?

**Comment by mmosttler** [comment]
@esnible is the ```traffic.sidecar.istio.io/excludeInboundPorts``` an annotation only for deployments or is it available on all pod types? 

I tried to exclude my couchbase namespace from istio (so no side car on couchbase pods in couchbase namespace).  Couchbase finished its startup, but now I am no longer able to access couchbase from my service running inside the istio mesh.  I am seeing errors when it tries to connect, and the following errors in the itio-proxy for my service:

```
I  [2019-04-05T15:38:13.605Z] UF 0 0 5 "35.247.96.101:11210" outbound|11210||cb-example-srv.couchbase.svc.cluster.local 10.36.10.6:36062 35.247.96.101:11210 10.36.10.6:36060
 
I  [2019-04-05T15:38:16.486Z] UF 0 0 3 "35.247.96.101:11210" outbound|11210||cb-example-srv.couchbase.svc.cluster.local 10.36.10.6:36070 35.247.96.101:11210 10.36.10.6:36068
 
I  [2019-04-05T15:38:16.522Z] UF 0 0 4 "35.247.96.101:8091" outbound|8091||cb-example.couchbase.svc.cluster.local 10.36.10.6:38794 35.247.96.101:8091 10.36.10.6:38792
 
```

Does anyone know what I need to do to allow a service in the istio mesh to access something that is running outside the istio mesh in the same kubernetes cluster?
