### ISSUE TITLE
tag 1.1.2's commit hash is same as 1.1.1

### ISSUE THREAD

**Issue by sunadm** [istio/istio#13016]
as subject title.

**Comment by howardjohn** [comment]
The "1.1.2" release is not a real release. We have an issue with our release process that occasionally tags commits in misleading ways that we are working on.

Please only use the officially published releases from https://github.com/istio/istio/releases, not drafts.

**Comment by dimpavloff** [comment]
Should the 1.1.2 tag be deleted then?

**Comment by AshWater** [comment]
So, can I just checkout to the tag 1.1.2, and then build the istio1.1.2 package? or can I still checkout tag 1.1.1, and then build the package?

**Comment by AshWater** [comment]
> The "1.1.2" release is not a real release. We have an issue with our release process that occasionally tags commits in misleading ways that we are working on.
> 
> Please only use the officially published releases from https://github.com/istio/istio/releases, not drafts.
So, can I just checkout to the tag 1.1.2, and then build the istio1.1.2 package? or can I still checkout tag 1.1.1, and then build the package?
