### ISSUE TITLE
Unable to get successful integration test run on GKE

### ISSUE THREAD

**Issue by liamawhite** [istio/istio#13025]
**Describe the bug**
Integration tests don't run successfully on GKE cluster. Pretty sure it's not GKE specific though.

**Expected behavior**
Successful integration test run.

**Steps to reproduce the bug**

- Create a new cluster.
- Bind account to `cluster-admin` role
- `cd test/integration && go test ./...  -istio.test.env kube`

**Version**
N/A - ran using the latest master branch
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T19:44:19Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-gke.7", GitCommit:"aeaa96020ec0614a8773799058c3b8d58c19b9ff", GitTreeState:"clean", BuildDate:"2019-03-13T11:22:57Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**
GKE - 1.12.6-gke.7

**Logs**
https://pastebin.com/qGfjrY8Z

**Comment by liamawhite** [comment]
[citadel-test-e1016d603eae40cc9a.zip](https://github.com/istio/istio/files/3039284/citadel-test-e1016d603eae40cc9a.zip)

Attached as discussed.

**Comment by ozevren** [comment]
I reproed in GKE - 1.12.6-gke.7. This looks like cross-test interference, as running suites individually seems to work fine.

**Comment by ozevren** [comment]
ok, this is probably simpler than I thought.

When running from the top-level integration folder, you'll need to specify -p 1 to avoid parallelism. 

I'll see if I can incorporate something to the test framework to avoid this problem somehow.

**Comment by nmittler** [comment]
@ozevren I thought parallelism was disabled by default and that you had to explicitly opt-in for a test via `t.Parallel()`?

**Comment by ozevren** [comment]
For tests, yes, but not for multiple TestMain's. :)
```

-parallel n
    Allow parallel execution of test functions that call t.Parallel.
    The value of this flag is the maximum number of tests to run
    simultaneously; by default, it is set to the value of GOMAXPROCS.
    Note that -parallel only applies within a single test binary.
    The 'go test' command may run tests for different packages
    in parallel as well, according to the setting of the -p flag
    (see 'go help build').
```
Notice the last sentence.

**Comment by nmittler** [comment]
Ah interesting ... good to know!

**Comment by ozevren** [comment]
Added more documentation, and opened a separate bug for a proper fix. Closing this one for the time being.
https://github.com/istio/istio/pull/13032
https://github.com/istio/istio/issues/13031
