### ISSUE TITLE
VM service TCP missing destination.service - mixer/pilot service uid/pods match

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#1302]
Currently any inbound call to a TCP service on VM yields the following error in mixer:
```
E1017 05:58:02.900969       1 grpcServer.go:181] Check returned with
error : INTERNAL (destination.service identity not found in
attributes[context.time destination.ip source.ip destination.uid
context.protocol source.port])
```

We may want to solve this globally where mixer would stop using pods for figuring out service names

ideally a (quick) fix would be cherry picked in 0.2 (a hacky version of that is https://github.com/istio/pilot/pull/1515)

**Comment by ldemailly** [comment]
cc @sakshigoel12

**Comment by douglas-reid** [comment]
It seems like there are multiple layers that need attention here. Is this tracking just the sending of `destination.service` from Envoy to Mixer?  Or is this covering the additions/modifications to the `kubernetes` adapter code for Mixer too?

I think I'd prefer to track adapter changes separately, if that makes sense to everyone involved.

**Comment by ldemailly** [comment]
happy to split into 
a) short term: pilot to send the service name even for tcp
b) longer term: mixer to not use pod cache/... at all

**Comment by ldemailly** [comment]
afaik for a) it's just changing `mixerTCPConfig` in a less hacky way than https://github.com/istio/old_pilot_repo/pull/1515/files but by actually using the service object from the parent

**Comment by ldemailly** [comment]
cc @hklai , @jasminejaksic this is a critical issue with 0.2 that needs resolution/tracking

**Comment by andraxylia** [comment]
This has currently multiple people assigned, which means nobody is working on it. I will assign it solely to you @ldemailly .

**Comment by ldemailly** [comment]
jasmine can you find an owner ? thanks! (someone from pilot and/or someone from mixer)

**Comment by andraxylia** [comment]
a) changes in pilot should completely fix the problem, no need to do anything in mixer.

**Comment by ldemailly** [comment]
mixer shouldn't be looking at pods (directly) that part of the issue is beyond the VM problem
(and so is assuming there is an app label and said label is == to the service name)

**Comment by jasminejaksic** [comment]
Jason and Wayne - Has there been any progress on the short-term fix (sending service name to Mixer)?

**Comment by ayj** [comment]
The proxy/mixerclient should now be sending `destination.service` to the Mixer in Check/Report calls.

**Comment by jasminejaksic** [comment]
Perfect! I'm going to close this issue. Laurent et al, feel free to open a new one for the long term fix.

**Comment by ldemailly** [comment]
@ayj which PR changed that ?

**Comment by ayj** [comment]
https://github.com/istio/istio/pull/1845 added `destination.service` to TCP config filter attribute list 
(see [mixerTCPConfig](https://github.com/istio/istio/commit/85983c26a893d9321f035b440b3d9185a85856dd#diff-83699eda922e729afb2122093ca240b4R229)).

https://github.com/istio/mixerclient/pull/248 includes these attributes in Report/Check calls to mixer (see https://github.com/istio/mixerclient/pull/248/files#diff-095c85dbca675290424501565e6f8e20R37), though this support may have also been present in earlier versions of mixerclient. cc @qiwzhang

**Comment by ldemailly** [comment]
cool thanks, I filled the longer term follow up as #2367 (though that may be a dup of some other issues) and I added to my todo to retest the mesh expansion and confirm this is indeed fixed.
