### ISSUE TITLE
[Test Framework] Avoid accidental test parallelism in the test framework

### ISSUE THREAD

**Issue by ozevren** [istio/istio#13031]
When integration tests are run in the integration folder with:
``` go test ./... --istio.test.env kube ```

The tests fail as the go test framework runs the TestMains in parallel. A mitigation is to use the ```-p 1``` flag, but that is subtle and easy to miss.

We should implement a locking/election mechanism when the tests are acquiring the environment, so that even when the tests are ran in parallel, then can work without stepping on each other's toes.

Here is a strawman algorithm for accomplishing this, similar to K8s leader election: We can use a singleton resource in the K8s environment as a locking mechanism.

When the Kubernetes environment is first created, the framework, in a loop, should check whether a resource (e.g. a namespace) with a well-known name exists or not. It should wait in a retry loop, until it notices that the resource doesn't exist and should try creating it. If it can create the resource, then it means it acquired the environment. Otherwise it should keep looping. Once it is done with the tests, it should delete the resource to signal availability to other suites.

To deal with stale entries (e.g. due to crashes), a well-known annotation field on the resource can be used to track the 'lease timeout'. This should be a relatively short period (i.e. 30 seconds). To keep the lease alive, the lock owner will need to keep updating it frequently. The waiters can keep checking the annotation and if it detects the resource is stale, it can delete the resource before commencing with the acquisition algorithm outlined above.

**Comment by draveness** [comment]
Hi @ozevren , If nobody claims this, I'd like to give it a try.

**Comment by ozevren** [comment]
ok, assigned to you.

**Comment by draveness** [comment]
I looked around at the test files in the integration folder and found that each test called framework.NewContext before running the actual tests. The `NewContext` finally called the `newTextContext' function.

```go
func newTestContext(s *suiteContext, parentScope *scope, t *testing.T) *testContext {
	id := s.allocateContextID(t.Name())

	if s.skipAll {
		t.Skipf("Skipping: %s", s.skipReason)
	}

	scopes.Framework.Debugf("Creating New test context")
	workDir := path.Join(s.settings.RunDir(), t.Name())
	if err := os.MkdirAll(workDir, os.ModePerm); err != nil {
		t.Fatalf("Error creating work dir %q: %v", workDir, err)
	}

	scopes.Framework.Debugf("Creating new testContext: %q", id)

	scopeID := fmt.Sprintf("[%s]", id)
	return &testContext{
		id:      id,
		suite:   s,
		scope:   newScope(scopeID, parentScope),
		workDir: workDir,
	}
}
```

Is it appropriate to acquire the lock in this and release is in `testContext.Done`:

```go
func (c *testContext) Done(t *testing.T) {
	if t.Failed() {
		scopes.Framework.Debugf("Begin dumping testContext: %q", c.id)
		c.scope.dump()
		scopes.Framework.Debugf("Completed dumping testContext: %q", c.id)
	}

	scopes.Framework.Debugf("Begin cleaning up testContext: %q", c.id)
	if err := c.scope.done(c.suite.settings.NoCleanup); err != nil {
		t.Fatalf("error scope cleanup: %v", err)
	}
	scopes.Framework.Debugf("Completed cleaning up testContext: %q", c.id)
}
```
