### ISSUE TITLE
Implement coherent mechanism for resolving short DNS names that doesn't crash the mesh

### ISSUE THREAD

**Issue by morvencao** [istio/istio#13045]
**Describe the bug**
This should be part of https://github.com/istio/istio/issues/11731

In multicluster installation with gateway scenario, deployed `sleep` in cluster1 and `httpbin` in cluster2, then accessing `httpbin` service will get `404` because SNI is not matched.

I have to access the complete host: `httpbin.bar.global` or add header: `host: httpbin.bar.global`.

But this introduces inconvenience because the location of destination service (here `httpbin`) should be transparent to other services. 

Usually the developer usually access the destination service with k8s service name, they may not add the `host` header or use the FQDN with `global`. 

I have tried to change the host field of `istio-multicluster-ingressgateway` from `*.global` to `*`, and the `sni` field in envoy has been updated after that, but `curl httpbin.bar` is still not working.

Am I missing something?

@rshriram Any thought for this case?

```
# curl -v httpbin.bar:8000
* Rebuilt URL to: httpbin.bar:8000/
*   Trying 127.255.0.2...
* TCP_NODELAY set
* Connected to httpbin.bar (127.255.0.2) port 8000 (#0)
> GET / HTTP/1.1
> Host: httpbin.bar:8000
> User-Agent: curl/7.60.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
< date: Thu, 04 Apr 2019 04:00:47 GMT
< server: envoy
< content-length: 0
<
* Connection #0 to host httpbin.bar left intact


# curl -v -H "host: httpbin.bar.global" httpbin.bar:8000
* Rebuilt URL to: httpbin.bar:8000/
*   Trying 127.255.0.2...
* TCP_NODELAY set
* Connected to httpbin.bar (127.255.0.2) port 8000 (#0)
> GET / HTTP/1.1
> Host: httpbin.bar.global
> User-Agent: curl/7.60.0
> Accept: */*
>
< HTTP/1.1 200 OK
< server: envoy
< date: Thu, 04 Apr 2019 04:07:29 GMT
< content-type: text/html; charset=utf-8
< content-length: 9593
< access-control-allow-origin: *
< access-control-allow-credentials: true
< x-envoy-upstream-service-time: 16
<
<!DOCTYPE html>
<html lang="en">
```

**Expected behavior**
The location of destination service (here `httpbin`) should be transparent to other services. 

The developer should access the destination service with k8s service name, without `host` header or the FQDN with `global`. 

**Version**
```
# ./bin/istioctl version
version.BuildInfo{Version:"1.1.0", GitRevision:"82797c0c0649a3f73029b33957ae105260458c6e", User:"root", Host:"996cd064-49c1-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-rc.6"}
```

```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3+icp-ee", GitCommit:"5f4327948913b3c0bd330cae0e5bf7cf09d1f0ae", GitTreeState:"clean", BuildDate:"2018-09-21T05:53:39Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3+icp-ee", GitCommit:"5f4327948913b3c0bd330cae0e5bf7cf09d1f0ae", GitTreeState:"clean", BuildDate:"2018-09-21T05:53:39Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Installation**
Deploy Istio multicluster with gateway following the instruction: https://istio.io/docs/setup/kubernetes/install/multicluster/gateways/

/CC @clyang82

**Comment by sdake** [comment]
@morvencao the concept of curling or otherwise accessing `httpbin` without namespace.global was implemented in 1.1, but reverted 1 day prior to release because it could result in duplicate routes advertised, crashing every service mesh.  This would occur if someone deployed httpbin in the default namespace on both clusters.

Most of the work is done and in the git repo history if it is unreverted.  What is missing is a coherent way to advertise the routes (how do we pick which one of these to advertise?).  Local user experience is more important the multicluster user experience.

I'd invite you to take a look at sorting out this specific problem.  The git hash at which this was reverted was:

The commit where this worked well enough but was open to this user error cratering the entire mesh:
```
commit 60f4405d14ccc13ba01824143fe4ab00a6716589
Author: Steven Dake <steven.dake@gmail.com>
Date:   Fri Mar 8 11:58:37 2019 -0700

    fix dns suffix extraction algorithm (#12346)

    * context_test.go fix

    * Re-implement GetUniqueStrings

    GetUniqueStrings was originally implemented in this fashion, however,
    the algorithm was deemed to complex in a prior review.  The implementation
    works, and what is in release-1.1 does not work.

    * Updated implementation of GetUniqueStrings

    hzxuzhonghu has kindly reimplemented the original algorithm for
    simplicity.

    * stable sort

    * test fix

    * string sort
```

The revert of this work started here:
```
commit 6d8b5c2ffcd6068594e9d9a4b8af065e9a4a1381
Author: Shriram Rajagopalan <rshriram@users.noreply.github.com>
Date:   Fri Mar 8 16:39:09 2019 -0500

    Revert #11522: fix routing when DNS is resolved (#12365)

    * Revert #11522: fix routing when DNS is resolved

    * stray reference

    Signed-off-by: Shriram Rajagopalan <shriramr@vmware.com>

commit 3b4f97a5e94877add66d55e5464ed056eba7e51b
Author: Shriram Rajagopalan <rshriram@users.noreply.github.com>
Date:   Fri Mar 8 14:55:08 2019 -0500

    Revert "fix dns suffix extraction algorithm (#12346)" (#12363)

    This reverts commit 60f4405d14ccc13ba01824143fe4ab00a6716589.
```

**Comment by sdake** [comment]
PR 1: https://github.com/istio/istio/pull/11522
PR 2: https://github.com/istio/istio/pull/12346

**Comment by morvencao** [comment]
@sdake Thanks, that helps. I thought this should be working since I have tested it with 1.1 RC.

**Comment by sdake** [comment]
@morvencao it worked in 1.1 rc, but again at the last moment prior to 1.1 release, some of the work was reverted to prevent mesh-wide crashes.

Cheers
-steve
