### ISSUE TITLE
Mixer deployment has 2 port lists in helm chart.

### ISSUE THREAD

**Issue by markusthoemmes** [istio/istio#13048]
**Describe the bug**
As per title, the mixer's deployment definition has two separate port lists in the helm chart. If the specified option is triggered, only the second port list will be applied by kubectl.

https://github.com/istio/istio/blob/6407364027e24ed738dbeca64e82146a7424aba5/install/kubernetes/helm/istio/charts/mixer/templates/deployment.yaml#L168-L179

This only applies to the 1.0.x series. It's already fixed at HEAD/1.1.x.

**Expected behavior**
{{ What did you expect to happen? }}

**Steps to reproduce the bug**
1. `kubectl apply -f istio.yaml`
2. `kubectl describe pod` on the created `istio-policy` pod.

**Version**
- Istio 1.0.6
- Istio 1.0.7

**Installation**
Helm templating and kubectl apply of the generated template.

**Environment**
Any.

**Comment by markusthoemmes** [comment]
I'll assemble a PR to fix it.

**Comment by howardjohn** [comment]
This is only for 1.0 and confirmed fixed in 1.1. We aren't making anymore 1.0 releases so I am going to close this
