### ISSUE TITLE
Trim our port numbers for the ingress gateway

### ISSUE THREAD

**Issue by linsun** [istio/istio#13042]
user has reported that we open up too many ports on ingress gateway.  Need to examine if each port is truly needed to expose outside of the cluster.

https://discuss.istio.io/t/why-does-istio-create-so-many-ports-on-my-aws-sg-for-elb/1646

**Comment by mingfang** [comment]
The ports other than 80/443 are meant to enable access to telemetry tools like grafana, tracing, etc, using port based routing.  I think a better solution would be to use just 80/443 and using virtual host based routing.

**Comment by linsun** [comment]
agreed, I think these are just ports we forgot to clean up:

```
  - port: 15029
    targetPort: 15029
    name: https-kiali
  - port: 15030
    targetPort: 15030
    name: https-prometheus
  - port: 15031
    targetPort: 15031
    name: https-grafana
  - port: 15032
    targetPort: 15032
    name: https-tracing
```

since we requires user to run additional steps to configure gateway with these components now for accessing them now:  https://istio.io/docs/tasks/telemetry/gateways/

**Comment by linsun** [comment]
hold this work a bit for new installer merge in cc @costinm @howardjohn

**Comment by nycnewman** [comment]
We still see this issue with latest Istio. Will this be fixed?
