### ISSUE TITLE
Istio galley dashboard's data is not fully populated

### ISSUE THREAD

**Issue by jacob-delgado** [istio/istio#13040]
**Describe the bug**
When visiting the Galley grafana dashboard after setting up istio there can be issues where data is not properly being displayed.

**Expected behavior**
The galley dashboard to be populated.

**Steps to reproduce the bug**
1. Install istio
2. Setup grafana; for my case I do not use local storage, but remote storage
3. Visit the galley dashboard

**Version**
Istio 1.1.0
Kubernetes 1.11.8

**Installation**
Using the documentation provided by istio.

**Environment**
Running on AWS. Provisioned with kops.

**Comment by jacob-delgado** [comment]
To me,  https://github.com/istio/istio/blob/1.1.0/install/kubernetes/helm/istio/charts/grafana/dashboards/galley-dashboard.json is missing the following

```json
 "__inputs": [
    {
      "name": "DS_PROMETHEUS",
      "label": "Prometheus",
      "description": "",
      "type": "datasource",
      "pluginId": "prometheus",
      "pluginName": "Prometheus"
    }
],
```

at the top of the file, unlike the other grafana dashboards. This is how I was able to get it fixed.

**Comment by howardjohn** [comment]
Are you running istio 1.0 or 1.1.0? You can run `istioctl version --remote`.

(I believe) Galley is new in 1.1

**Comment by jacob-delgado** [comment]
Istio 1.1.0. Sorry

**Comment by nrjpoddar** [comment]
@howardjohn I have #13041 to address this, if you can take a look.
