### ISSUE TITLE
1.1.1 Connection Refused - Fresh Install

### ISSUE THREAD

**Issue by bitva77** [istio/istio#13057]
**Describe the bug**

Istio 1.1.1, fresh install, is not accepting connections to the HTTP port (31380)

```
telnet 10.245.2.95 31380
Trying 10.245.2.95...
telnet: connect to address 10.245.2.95: Connection refused
```

It is listening on the port however:

```
netstat -an |grep 31380
tcp6       0      0 :::31380                :::*                    LISTEN
```

I can verify it is not a server/firewall issue as netcat -l 31380 accepts connections just fine. 

**Expected behavior**

I expect Istio to accept connections.

**NOTE:  Istio 1.0.6 work fine.**

Differs from https://github.com/istio/istio/issues/12755 as I can't even connect to get a 5xx error.

Seems similar to https://github.com/istio/istio/issues/9943 however restarting the ingress-gateway pod does not fix the issue.

**Steps to reproduce the bug**

helm template install/kubernetes/helm/istio --name istio --namespace istio-system --set gateways.istio-ingressgateway.type=NodePort | kubectl apply -f -

Have a gateway definition like:

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: my-gateway
  namespace: blah
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 31380
      name: http2
      protocol: HTTP
    hosts:
    - blah.blah.com
```

Then try to connect to port 31380 on the node.

**Version**

```
client version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-17-g2b13318"}
citadel version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
galley version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
ingressgateway version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-17-g2b13318"}
pilot version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
policy version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
sidecar-injector version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
telemetry version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
```
K8s:

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Installation**
helm template install/kubernetes/helm/istio --name istio --namespace istio-system --set gateways.istio-ingressgateway.type=NodePort | kubectl apply -f -

**Environment**
On-Premise Kubernetes cluster.  Installed via Kubeadm.  Flannel CNI.

**Cluster state**

[istio-dump.tar.gz](https://github.com/istio/istio/files/3044591/istio-dump.tar.gz)

**Comment by esnible** [comment]
Your `istio-ingressgateway` NodePort Service has a port

```
    - name: http2
      nodePort: 31380
      port: 80
      protocol: TCP
      targetPort: 80
```

This means that the Service will expose whatever is listening on port 80 on 31380 on the public IP.

Your `netstat` shows the pod is listening on 31380 itself.  Follow the _samples/bookinfo/networking/bookinfo-gateway.yaml_ sample and use port 80.  It will still be exposed on 31380 because of the NodePort.

**Comment by bitva77** [comment]
Right but it's not accepting connections on that port:

```
telnet 10.245.2.95 31380
Trying 10.245.2.95...
telnet: connect to address 10.245.2.95: Connection refused
```

It's listening on it:

```
sudo netstat -anp |grep 31380
tcp6       0      0 :::31380                :::*                    LISTEN      37861/kube-proxy
```

I've verified it's not firewall or anything else like that on the node.  Where's the "Connection refused" coming from?

Thanks!

**Comment by esnible** [comment]
The reason it is not accepting is that it isn't listening on port 80.

If the IngressGateway doesn't see any Istio configuration to get traffic to port 80 it won't listen.  This can be confusing because it is hard to tell an Ingress misconfiguration from a rule misconfiguration.

Change your Gateway so that it has `number: 80` instead of 31380.  Put a destination port matching the blah.blah service.  Follow the _bookinfo-gateway.yaml_ or _helloworld-gateway.yaml_ examples.

**Comment by bitva77** [comment]
I must be an idiot.

@esnible I owe you a beer if we ever meet  :)
