### ISSUE TITLE
AccessLogFile/AccessLogPath settings are NOP

### ISSUE THREAD

**Issue by dingxiangfei2009** [istio/istio#13051]
**Describe the bug**
Since `istio` 1.1.1, access logs from `envoyproxy` have been disabled by default, by setting `admin.access_log_file` to `/dev/null`. If CNI is enabled on `istio` 1.1.1, no access logs are produced even if `global.proxy.accessLogPath=/dev/stdout` is set.

**Expected behavior**
Setting `AccessLogFile`/`AccessLogPath` should have instructed `envoyproxy` in a cluster configured with `istio` 1.1.1 and CNI to output access logs to the designated file, such as `/dev/stdout`.

**Steps to reproduce the bug**
1. Create a new cluster with Kubernetes 1.12.10.
1. Enable CNI and install Istio CNI.
1. `helm template install/kubernetes/helm/istio --set global.proxy.accessLogPath=/dev/stdout --namespace istio-system`
1. optionally restart pods in `istio-system`
1. start a service, such as the BookInfo example, and hit the endpoint of the service
1. view the configuration of the `envoyproxy` in the `istio-proxy` sidecar of the relevant pods and observe that `access_log_file` is set to `/dev/null`; logs from these pods do not have access log output

**Version**
Kubernetes: 1.12.0

Istio: 1.1.1

**Installation**

Standard installation of Istio 1.1.1 with `helm template` method

**Environment**

Google Cloud Platform

**Cluster state**

**Comment by howardjohn** [comment]
I believe you need to set accessLogFile not accessLogPath

**Comment by dingxiangfei2009** [comment]
@howardjohn Yes, I have set `accessLogFile` to `/dev/stdout` for the helm template. However, it seems having no effect, either. `grep`ing through `istio` source code is sort of supporting the theory that this option is not used anywhere.

`accessLogFile` is used here. https://github.com/istio/istio/blob/ad8f60933dea7b1efaa3c99dc7f15862499c5217/vendor/istio.io/api/mesh/v1alpha1/config.pb.go#L205
Notice that this field is not used anywhere, except the tests.

**Comment by dingxiangfei2009** [comment]
@howardjohn Yes, I also tried `global.proxy.accessLogFile` to `/dev/stdout`. However, according to the admin page from `envoyproxy`, the access log is still written to `/dev/null`.

**Comment by dingxiangfei2009** [comment]
Ah, I see. Yes, I can confirm that `envoy.file_access_log` is set to `/dev/stdout`.

However, the access logs are still not coming in. I notice that there are many deprecation warnings in the log, and one of them is about `envoy.config.filter.accesslog.v2.AccessLog.config`.
```
Using deprecated option 'envoy.config.filter.accesslog.v2.AccessLog.config'. This configuration will be removed from Envoy soon.
```
Could this be related?

**Comment by howardjohn** [comment]
The deprecation warning is unrelated.

I just tried out bookinfo on 1.1.1 on GKE with log filed enabled and see logs:

```
w[istio-proxy]: [2019-04-10T14:56:54.983Z] "GET /details/0 HTTP/1.1" 200 - "-" 0 178 4 3 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36" "cdc63dbf-a4eb-400f-8dcc-db699a26c0f5" "details:9080" "10.60.3.144:9080" outbound|9080||details.book.svc.cluster.local - 10.63.254.37:9080 10.60.1.30:41498 -
....
```

Are you sure you are looking at the logs for the istio-proxy container and not the application?

**Comment by dingxiangfei2009** [comment]
Yes, I am looking at `istio-proxy` container.
I followed the `bookinfo` sample to `curl` the product page while the logs are rolling, but I cannot find any `GET /details/0 ...` entry.

**Comment by dingxiangfei2009** [comment]
@howardjohn I did some more test and came back the following results. Both scenarios are run in a freshly created GKE cluster with network policy enabled.

- Enabling CNI breaks access logs.
```bash
helm template ~/istio-fetch/istio-init --name istio-init --namespace istio-system | kubectl apply -f -
helm template ~/istio-fetch/istio-cni --name istio-cni --namespace istio-system --set cniBinDir=/home/kubernetes/bin | kubectl apply -f -
helm template ~/istio-fetch/istio --name istio --namespace istio-system -f values.yaml | kubectl apply -f -
kubectl label namespace default istio-injection=enabled
< ... set up bookinfo and istio ingress gateway in default namespace ... >
export INGRESS_HOST=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
export INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="http2")].port}')
export SECURE_INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="https")].port}')
export GATEWAY_URL=$INGRESS_HOST:$INGRESS_PORT
curl -s http://${GATEWAY_URL}/productpage | grep -o "<title>.*</title>"
```
`values.yaml`:
```yaml
tracing:
  enabled: true
kiali:
  enabled: true
istio_cni:
  enabled: true
pilot:
  traceSampling: "100"
global:
  proxy:
    accessLogFile: /dev/stdout
```
No access logs can be seen in the Stackdriver.

- Delete the cluster and recreate another. Then in the recreated cluster, `istio` without CNI allows access logs.
```bash
helm template ~/istio-fetch/istio-init --name istio-init --namespace istio-system | kubectl apply -f -
helm template ~/istio-fetch/istio --name istio --namespace istio-system -f values.yaml | kubectl apply -f -
kubectl label namespace default istio-injection=enabled
< ... set up bookinfo and istio ingress gateway in default namespace ... >
export INGRESS_HOST=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
export INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="http2")].port}')
export SECURE_INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="https")].port}')
export GATEWAY_URL=$INGRESS_HOST:$INGRESS_PORT
curl -s http://${GATEWAY_URL}/productpage | grep -o "<title>.*</title>"
```
`values.yaml`:
```yaml
tracing:
  enabled: true
kiali:
  enabled: true
pilot:
  traceSampling: "100"
global:
  proxy:
    accessLogFile: /dev/stdout
```
I obtained the following:
```
"GET /productpage HTTP/1.1" 200 - "-" 0 5723 54 53 "10.148.x.x" "curl/7.64.0" "f7529773-e243-9c93-8ed7-faf23f5f3505" "35.x.x.x" "127.0.0.1:9080" inbound|9080|http|productpage.default.svc.cluster.local - 10.4.x.x:9080 10.148.x.x:0 -
```

**Comment by dingxiangfei2009** [comment]
Looks like Jaeger stops working with CNI enabled, too (#13171).

**Comment by howardjohn** [comment]
Closing this in favor of https://github.com/istio/istio/issues/13171 which is the same issue
