### ISSUE TITLE
Can't access Zipkins dashboard

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#13055]
Following https://istio.io/docs/tasks/telemetry/distributed-tracing/zipkin/ on Istio 1.1.1.

```
$ helm get values istio
tracing:
  enabled: true
  ingress:
    enabled: true
  provider: zipkin
```

Zipkin pod is running

When I follow the [Access Dashboard](https://istio.io/docs/tasks/telemetry/distributed-tracing/zipkin/#accessing-the-dashboard) step, it fails.

```
$ kubectl -n istio-system port-forward $(kubectl -n istio-system get pod -l app=istio-ingressgateway -o jsonpath='{.items[0].metadata.name}') 15032:15032
Forwarding from 127.0.0.1:15032 -> 15032
Forwarding from [::1]:15032 -> 15032
Handling connection for 15032
E0404 07:56:09.755891   40574 portforward.go:400] an error occurred forwarding 15032 -> 15032: error forwarding port 15032 to pod 5f3af6feaff32832a25da4181fd60e3853ed58c33c2d8d39a72d8c7708303b0f, uid : exit status 1: 2019/04/04 14:56:09 socat[404216] E connect(5, AF=2 127.0.0.1:15032, 16): Connection refused
```

```
$ curl http://localhost:15032/
curl: (52) Empty reply from server
```

**Comment by objectiser** [comment]
I think you are probably missing this part: https://istio.io/docs/tasks/telemetry/gateways/

If this is the problem, then we need to add a link to this page from the `Accessing the dashboard` section.

**Comment by howardjohn** [comment]
Yep looks like that's the problem, think we just need to link to that page

**Comment by douglas-reid** [comment]
Other option: update the `port-forward` command. That should still work, but it should be done against the tracing workload instead of the ingress gateway. This would show a way to access without having to expose the service.

Thoughts?

**Comment by howardjohn** [comment]
port-forward sounds like a good idea
