### ISSUE TITLE
produce smaller istioctl

### ISSUE THREAD

**Issue by esnible** [istio/istio#13064]
When installing Istio using `curl -L https://git.io/getLatestIstio | ISTIO_VERSION=1.1.1 sh -` the download is 95% the _istioctl_ binary and 5% all of the Helm charts, samples, and tools.

That's big!

Experimental result:

Following https://blog.filippo.io/shrink-your-go-binaries-with-this-one-weird-trick/ I was able to reduce the size of _istioctl_.  For `master` `make istioctl` generates a 57.0 MB file on OSX.  By adding `-s -w` to _gobuild.sh_ the size drops to 48.8 MB.

57.6 MB to 42.9 MB on Linux.

I then ran `upx --brute /home/vagrant/go/out/linux_amd64/release/istioctl` on the Linux version.  This reduces the size of _istioctl_ on Linux to 8.3 MB!  No functional difference.  It took 14 minutes for my Vagrant machine to do the compression.  I don't know of a comparable tool for OSX or Windows.

@geeknoid

**Comment by geeknoid** [comment]
So is running upx actually useful? Our releases are gzipped, so we should be getting the same benefits in terms of compression.

**Comment by esnible** [comment]
`gzip` with `-9` takes _istioctl_ down to 12.8 MB.  The `upx` is 1/3 smaller.  Perhaps this gives is a slight performance increase using `upx` for CLI downloads and Docker pulls.  I didn't compare execution time between compressed and uncompressed binaries.

**Comment by linsun** [comment]
@esnible this is interesting, I think we should look into enabling this as part of our build system.

@ibm-jason @utka thoughts?

**Comment by ibm-jason** [comment]
@linsun I certainly think it's a good idea to make the footprint of istioctl smaller. `gzip -9` or `upx`, we can try whichever compression tool works best.

**Comment by ibm-jason** [comment]
@esnible I think we're good on this issue, no?

**Comment by ibm-jason** [comment]
@esnible Unless there is something we're missing here, this issue is closed with https://github.com/istio/istio/pull/13641 merged.
