### ISSUE TITLE
Virtual Service Deserialization Missing Fields

### ISSUE THREAD

**Issue by ivelichkovich** [istio/istio#13065]
So I'm using a wrapper around the kubernetes client to programmatically access istio resources.

I have this chunk of code just requesting for virtualservice and trying to transform it into the virtualservice struct

`result = &v1alpha3.VirtualService{} err = c.client.Get(). Namespace(c.ns). Resource("virtualservices"). Name(name). VersionedParams(&options, scheme.ParameterCodec). Do(). Into(result)`

It works for the most part but the virtualservice is missing some fields, they're all protobuf_oneof fields as far as I can tell.

for example with this virtualservice
`spec:
hosts:

details
http:
fault:
delay:
fixedDelay: 7s
percent: 100
route:
destination:
host: details
subset: v1
weight: 63
destination:
host: details
subset: v2
weight: 37`
I'm getting this result
`spec: hosts: - details http: - route: - destination: host: details subset: v1 weight: 63 - destination: host: details subset: v2 weight: 37 fault: delay: percent: 100 HttpDelayType: null`

Is this just a versioning issue or am I doing something wrong? I'm running istio-1.0.6 on my cluster and using release-1.0 in my code so I doubt the virtualservice protobuf stuff changed between those but it's possible.

Any help would be greatly appreciated though.

**Comment by esnible** [comment]
The logic to convert the resources from Kubernetes into Protobufs that Istio uses internally is a bit tricky.  Maybe this will get you started.

_pilot/pkg/config/kube/crd/client.go_ does

```
	err := rc.dynamic.Get().
		Namespace(namespace).
		Resource(ResourceName(schema.Plural)).
		Name(name).
		Do().Into(config)
```

... where `config` is

```
&VirtualService{
			TypeMeta: meta_v1.TypeMeta{
				Kind:       "VirtualService",
				APIVersion: apiVersion(&model.VirtualService),
			}
```

It then calls `ConvertObject()` to re-attach the metadata.

**Comment by ivelichkovich** [comment]
This is what my virtual service class looks like 

> type VirtualService struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec VirtualServiceSpec `json:"spec"`
}

func (vs *VirtualService) GetSpecMessage() proto.Message {
	return &vs.Spec.VirtualService
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// VirtualServiceList is a list of VirtualService resources
type VirtualServiceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata"`

	Items []VirtualService `json:"items"`
}

// VirtualServiceSpec is a wrapper around Istio VirtualService
type VirtualServiceSpec struct {
	istiov1alpha3.VirtualService
}

**Comment by howardjohn** [comment]
@ivelichkovich Ed's answer seems to explain the behavior and it doesn't look like there is any activity here anymore. 

We are trying to clean up some stale issues so I am going to close this, but if you have any more issues feel free to open/reopen another issue. Thanks
