### ISSUE TITLE
Sidecar readiness doesn't handle inbound wildcard addresses

### ISSUE THREAD

**Issue by nmittler** [istio/istio#13067]
Taken from https://github.com/istio/istio/issues/9504#issuecomment-479981385.

The readiness logic for checking application ports doesn't appear recognize wildcard addresses (`0.0.0.0`) as inbound:

```
kind: Deployment
metadata:
  name: echo
  labels:
    k8s-app: echo
  namespace: default
spec:
  replicas: 20
  selector:
    matchLabels:
      k8s-app: echo
  template:
    metadata:
      labels:
        k8s-app: echo
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: echo-service
        image: k8s.gcr.io/echoserver:1.10
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echo
  labels:
    k8s-app: echo
  namespace: default
spec:
  ports:
  - name: http
    port: 8080
  selector:
    k8s-app: echo

NAME                   READY   STATUS    RESTARTS   AGE
echo-95894744f-72kdn   2/2     Running   0          2m
echo-95894744f-7dwst   2/2     Running   0          2m
echo-95894744f-c84fv   1/2     Running   0          2m
echo-95894744f-cdsc5   1/2     Running   0          2m
echo-95894744f-fr9bn   1/2     Running   0          2m
echo-95894744f-ftbfw   2/2     Running   0          2m
echo-95894744f-hfbgm   2/2     Running   0          2m
echo-95894744f-hvpk7   2/2     Running   0          2m
echo-95894744f-ks7vf   2/2     Running   0          2m
echo-95894744f-kvbd5   2/2     Running   0          2m
echo-95894744f-mdl86   2/2     Running   0          2m
echo-95894744f-nckdf   1/2     Running   0          2m
echo-95894744f-nfm8f   2/2     Running   0          2m
echo-95894744f-nz4mn   1/2     Running   0          2m
echo-95894744f-p74mq   1/2     Running   0          2m
echo-95894744f-stz7s   2/2     Running   0          2m
echo-95894744f-vrfjl   1/2     Running   0          2m
echo-95894744f-whn64   2/2     Running   0          2m
echo-95894744f-zcsbl   2/2     Running   0          2m
echo-95894744f-zjcp7   1/2     Running   0          2m

$ k logs -f echo-95894744f-vrfjl -c istio-proxy

* failed checking application ports. listeners="0.0.0.0:15090","10.0.5.201:443","10.0.2.108:15029","10.0.10.235:42422","10.0.9.253:443","10.0.11.84:8443","10.0.5.153:15011","10.0.2.108:443","10.0.2.108:31400","10.0.2.108:15443","10.0.2.210:443","10.0.0.10:53","10.0.3.24:443","10.0.0.1:443","10.0.0.13:443","10.0.2.108:15030","10.0.4.88:443","10.0.2.108:15031","10.0.2.108:15032","10.0.3.222:80","10.0.2.108:15020","10.0.3.24:15443","0.0.0.0:15010","0.0.0.0:15004","0.0.0.0:80","0.0.0.0:9901","0.0.0.0:9091","0.0.0.0:8060","0.0.0.0:8080","0.0.0.0:15014","0.0.0.0:15001"
* envoy missing listener for inbound application port: 8080
```

It's not immediately clear if Pilot changes have introduced this issue, but the readiness logic should account for it.

**Comment by waynz0r** [comment]
@nmittler actually i think there should be `podIP:8080` between the listeners for each pod, the healthy envoys all have those.

I assume that for currently unknown reasons the initial envoy config from pilot doesn't always contains the proper listeners. The problems disappears, `podIP:8080` will be propagated as a listener and the envoys goes healthy after an update arrives from pilot. Pretty easy to test this, for example by triggering it with deploying virtualservice or something similar.

**Comment by nmittler** [comment]
@costinm @rshriram any idea why the initial Pilot update contains an inbound listener for `0.0.0.0:port` but not `podIP:port`?

**Comment by waynz0r** [comment]
@nmittler  Actually, I believe the `0.0.0.0:8080` is there, because pilot listens on 8080 and the bare existence of that listener it is totally unrelated to this problem.

You can change the demo deployment port from 8080 to 8000 to avoid the confusion. `0.0.0.0:8080` would be still there, but `podIP:8000` also should be.

**Comment by nmittler** [comment]
@waynz0r ok, interesting.  Not sure why pilot would be giving the sidecar an inbound listener for its discovery port, but I guess it doesn't matter for now.

In any case, it sounds like this is not a real issue ... it was just a delay in receiving the inbound ports from Pilot ... does that sound right?

**Comment by waynz0r** [comment]
@nmittler every envoy should be healthy as soon as it gets the initial config from pilot, but for currently unknown reason sometimes some of them gets wrong initial config, I would consider it as a bug.

If in same cases there would be a several seconds delay in getting – the otherwise good – initial config, that could be probably acceptable, but that is not the case here.

I think this is not acceptable nor how it should work:

```NAME                    READY   STATUS    RESTARTS   AGE
echo-8557f647f9-4bcsg   2/2     Running   0          8m
echo-8557f647f9-6cdgx   2/2     Running   0          8m
echo-8557f647f9-85s7j   1/2     Running   0          8m
echo-8557f647f9-9pvvc   1/2     Running   0          8m
echo-8557f647f9-bd2fl   2/2     Running   0          8m
echo-8557f647f9-cj4gp   1/2     Running   0          8m
echo-8557f647f9-f5677   2/2     Running   0          8m
echo-8557f647f9-jd6mq   2/2     Running   0          8m
echo-8557f647f9-kjbsf   2/2     Running   0          8m
echo-8557f647f9-km5sg   1/2     Running   0          8m
echo-8557f647f9-msdtt   1/2     Running   0          8m
echo-8557f647f9-pvb69   2/2     Running   0          8m
echo-8557f647f9-pvtct   1/2     Running   0          8m
echo-8557f647f9-rcjl7   2/2     Running   0          8m
echo-8557f647f9-rdjw8   2/2     Running   0          8m
echo-8557f647f9-sn7xn   2/2     Running   0          8m
echo-8557f647f9-snr2l   2/2     Running   0          8m
echo-8557f647f9-wbzg2   2/2     Running   0          8m
```

The same deployment works with Istio 1.0.x without a glitch!

**Comment by nmittler** [comment]
@waynz0r ok, this sounds like more of an issue with Pilot.  Mind raising a separate bug and assigning to @rshriram and @costinm?

**Comment by nmittler** [comment]
I'm going to close this out as WAI

**Comment by joberdick** [comment]
@nmittler, I have to agree with @waynz0r. I am seeing the same issue and it can take minutes for istio-proxy to become ready. I dont think its ok either...

**Comment by nmittler** [comment]
@joberdick understood, I've closed this because that's a separate issue ... go ahead and file a separate bug.

**Comment by rshriram** [comment]
There are no wildcard addresses in the inbound path. Pilot sets up inbound listeners only for the pod IP and nothing else. So, I think this is a bug with the  readiness logic for checking application ports - Its probably picking up wildcard outbound listeners as well.

**Comment by waynz0r** [comment]
@rshriram the listener for an unhealthy envoy:

```
NAME                    READY   STATUS    RESTARTS   AGE   IP
echo-5d495b548f-288s2   1/2     Running   0          25s   10.24.0.45

["0.0.0.0:15090","10.0.3.222:80","10.0.0.10:53","10.0.9.247:31400","10.0.9.247:15443","10.0.9.247:15029","10.0.9.247:15030","10.0.9.247:15032","10.0.8.176:42422","10.0.11.84:8443","10.0.13.75:443","10.0.10.34:15011","10.0.9.247:15031","10.0.9.253:443","10.0.9.247:443","10.0.5.201:443","10.0.0.1:443","10.0.9.247:15020","10.0.4.48:443","10.0.15.203:443","10.0.4.88:443","10.0.15.203:15443","0.0.0.0:8060","0.0.0.0:8080","0.0.0.0:9901","0.0.0.0:80","0.0.0.0:9091","0.0.0.0:15010","0.0.0.0:15014","0.0.0.0:15004","0.0.0.0:8000","0.0.0.0:15001"]
```

after it gets healthy (triggered by another deployment):

```
NAME                              READY   STATUS    RESTARTS   AGE   IP
echo-5d495b548f-288s2             2/2     Running   0          2m    10.24.0.45

["0.0.0.0:15090","10.0.3.222:80","10.0.0.10:53","10.0.9.247:31400","10.0.9.247:15443","10.0.9.247:15029","10.0.9.247:15030","10.0.9.247:15032","10.0.8.176:42422","10.0.11.84:8443","10.0.13.75:443","10.0.10.34:15011","10.0.9.247:15031","10.0.9.253:443","10.0.9.247:443","10.0.5.201:443","10.0.0.1:443","10.0.9.247:15020","10.0.4.48:443","10.0.15.203:443","10.0.4.88:443","10.0.15.203:15443","0.0.0.0:8060","0.0.0.0:8080","0.0.0.0:9901","0.0.0.0:80","0.0.0.0:9091","0.0.0.0:15010","0.0.0.0:15014","0.0.0.0:15004","0.0.0.0:8000","0.0.0.0:15001","10.24.0.45:8000","10.24.0.45:15020","0.0.0.0:9080"]
```

so the only difference is that in proper config there is these two `"10.24.0.45:8000","10.24.0.45:15020"` listeners, so as i understand it, this is not a readiness logic issue but rather a wrong update from pilot.

**Comment by waynz0r** [comment]
I've opened #13106 to track this problem.
