### ISSUE TITLE
Health check rewrite for mTLS per deployment annotation

### ISSUE THREAD

**Issue by incfly** [istio/istio#13074]
**Describe the feature request**
Support annotation in deployment(pod?), `sidecar.istio.io/rewriteAppProbers: true/false`. True indicates we rewrite k8s PodSpec YAML. This will always takes higher priority over `istio-sidecar-injector` configmap `rewriteAppHTTPProbe` option (configured in Istio installation stage via helm flag).

The change should be relevatively straightforward, update the [`ShouldRewrite`](https://github.com/istio/istio/blob/cc1c163766690d32eb432eb0a38905f52d1044e1/pilot/pkg/kube/inject/app_probe.go#L47) to return result based on annotation.

This way customer can opt-in the feature more incrementally.

**Comment by arief-hidayat** [comment]
Hi,

Is anyone working on this? I am interested to start contributing here.

Thanks

**Comment by incfly** [comment]
@arief-hidayat feel free to take, assigned it to you.

You might need to plumb annotation information somehow, or refactored the `ShouldRewrite` function. Look around [sidecar.istio.io/inject](https://github.com/istio/istio/blob/8d82dbe6377f2ab8ea24a12b9ef0c0a1f7cd2f13/pilot/pkg/kube/inject/inject.go#L54) for  an example.

@geeknoid recently filed a bug to centralize about all the annotations Istio support, you probably need to use `annotations.Register` for that. Look https://github.com/istio/istio/issues/12940 for more details.

**Comment by incfly** [comment]
Seems like github only allows me assign to Istio org members, but that should matter :)

Thanks for volunteering your help!

**Comment by arief-hidayat** [comment]
Thanks. I'll start looking into it.

**Comment by arief-hidayat** [comment]
@incfly  I have raised PR. Should you be included as reviewer?

Note that I am not able to run the whole tests in my mac.
(might be related with notes in https://github.com/istio/istio/wiki/Dev-Guide#running-tests)
So, I just run 
```
go test -count=1 -v ./pilot/pkg/kube/inject/...
```
Please feel free to give any suggestion. thanks

**Comment by incfly** [comment]
Yes., please send it out to me for review.

Tests under `pilot/pkg/kube/inject` is good enough. Just ensure you add more input files and tests for this feature.  Note we have two different injection mechanism, `https://github.com/istio/istio/tree/master/pilot/pkg/kube/inject/testdata`. webhook and kubeinject, each of them has their own test cases.

**Comment by arief-hidayat** [comment]
I have added you as reviewers. Please let me know if I missed out something.
Thanks

**Comment by incfly** [comment]
@arief-hidayat Thanks for work!

Please update the documentation on https://istio.io/help/ops/setup/app-health-check/, with a concrete example (verified by yourself of course :) 

E2E test mentioned before is also something worth considering.
