### ISSUE TITLE
prow: make test rerun command argument match the job name

### ISSUE THREAD

**Issue by listx** [istio/istio#13072]
**Describe the feature request**
If the `prow/e2e_pilotv2_auth_sds.sh` test fails, the command to rerun it is: ` /test istio_auth_sds_e2e`. Notice how the argument `istio_auth_sds_e2e` is not `prow/e2e_pilotv2_auth_sds.sh`. Let's make these the same so that humans don't make the time-consuming mistake of trying to do `/test prow/e2e_pilotv2_auth_sds.sh`, as witnessed in https://github.com/istio/istio/pull/12203#issuecomment-479726114.

**Describe alternatives you've considered**
There is really no reason why the arguments shouldn't match...

**Additional context**
Looks like the tests all reside in https://github.com/istio/istio/tree/master/prow. Sounds like that's the entrypoint for performing the Prow job renames.

**Comment by listx** [comment]
Any thoughts on this?

**Comment by utka** [comment]
I think it is a good idea.

**Comment by utka** [comment]
Looking into that a little bit more. I think there is more necessary change for separating tests for  branches in testgrid. This two changes do not work together.

**Comment by howardjohn** [comment]
I think we can just get rid of the "context" argument on all the jobs

**Comment by howardjohn** [comment]
I will get this done soon, tracking in https://github.com/istio/test-infra/issues/1460. I am going to close this one since its hard to track two at once
