### ISSUE TITLE
Support for http 1.0 in Istio Ingress Gateway

### ISSUE THREAD

**Issue by pbochynski** [istio/istio#13085]
**Describe the feature request**
I found that istio 1.1 supports now http 1.0 requests. When you set the environment variable for pilot `PILOT_HTTP10 = 1` then each envoy proxy gets the configuration with
`accept_http_10: true`. So it is possible to perform HTTP 1.0 request from one pod to another. But this configuration is not propagated to the envoy instance in `istio-ingressgateway` component and in the result external request is blocked with such response:
```
< HTTP/1.1 426 Upgrade Required
< date: Thu, 04 Apr 2019 12:17:47 GMT
< server: istio-envoy
< content-length: 0
```
Is there a way to set a flag: accept_http_10: true for envoy in istio-ingressgateway?

**Describe alternatives you've considered**
nginx ingress supports http 1.0 out of the box

**Additional context**
Related issue: #11235
Related PR: https://github.com/istio/istio/pull/11511

**Comment by GregHanson** [comment]
As it stands, PR #11511 only added the logic to support that flag in the buildSidecarListeners() logic, see [here](https://github.com/istio/istio/pull/11511/files#diff-86fb73d7dd150e47328ead76ceca0992R245).  Similar logic would have to be added to the Gateway generation code in https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/gateway.go#L39

**Comment by MohammedAliKadri** [comment]
@GregHanson  @pbochynski even i am facing the same issue, where my go based micro service  is not functioning over ingress gateway!

whats the alternative now!

**Comment by piotrmsc** [comment]
@GregHanson I would like to contribute to this, is anyone already working on that?

**Comment by Demonsthere** [comment]
Related PR: https://github.com/istio/istio/pull/14448

**Comment by piotrmsc** [comment]
Since PR is already merged, is there any ETA when it will be released? will this be part of 1.2 or later?

**Comment by GregHanson** [comment]
@piotrmsc was not part of the 1.2 release, but there is a cherry pick PR here: https://github.com/istio/istio/pull/15062

Should be available when 1.2.1 goes out

**Comment by duderino** [comment]
And will be in 1.1.11 too

**Comment by venomwaqar** [comment]
Sorry I am new to istio.
But can someone please guide me how do I make envoy and gateway accept http1.0 requests.
In the comments I can see that PR is merged and code is there.
but I cant figure out what do I need to do just by looking at code.
Please provide the instructions.

Thanks alot :-)

**Comment by Quarky9** [comment]
After couple hours of source codding digging adding this the my helm values did the trick of setting the right ENV for the ingressgateway pods:
```
gateways:
  istio-ingressgateway:
    env:
      ISTIO_META_HTTP10: '"1"'
```
Escaping is needed as we need a string rather than an Int in the end.

**Comment by rms1000watt** [comment]
@Quarky9 Where in the source code did you find this env var `ISTIO_META_HTTP10 ` declared? Just looking to edify myself on the inner workings of istio. I'm not seeing anything when I search this project in github.. or really anywhere else in google.

**Comment by Quarky9** [comment]
@rms1000watt 
based on https://github.com/istio/istio/blob/022c70f5cf7a078a70ba4abc92414f344913d880/pilot/pkg/networking/core/v1alpha3/gateway.go#L336 and some deductions on how node.metadata is constructed and already used for other options like see: https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/gateways/templates/deployment.yaml#L249

**Comment by xring** [comment]
@Quarky9 which version does env `ISTIO_META_HTTP10 ` start working?

**Comment by Quarky9** [comment]
I use Istio since v1.4 so I cannot comment on anything earlier.

**Comment by egegunes** [comment]
I enabled HTTP/1.0 support with IstioOperator using @Quarky9 's method:

```
    ingressGateways:
    - enabled: true
      k8s:
        env:
        - name: ISTIO_META_ROUTER_MODE
          value: sni-dnat
        - name: ISTIO_META_HTTP10
          value: '1'

**Comment by chiraggb** [comment]
> I enabled HTTP/1.0 support with IstioOperator using @Quarky9 's method:
> 
> ```
>     ingressGateways:
>     - enabled: true
>       k8s:
>         env:
>         - name: ISTIO_META_ROUTER_MODE
>           value: sni-dnat
>         - name: ISTIO_META_HTTP10
>           value: '1'
> ```

I am facing 426 error as well can you please share your yaml where you place this
thank you appreciate your help

**Comment by lober-io** [comment]
@chiraggb 
You need to add this to your IstioOperator. You can find at this page more details [IstioOperator](https://istio.io/latest/docs/reference/config/istio.operator.v1alpha1/#KubernetesResourcesSpec)
For example:
`apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  labels:
    app.kubernetes.io/part-of: "service-mesh"
    app.kubernetes.io/managed-by: "Terraform"
spec:
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          env:
            - name: ISTIO_META_ROUTER_MODE
              value: sni-dnat
            - name: ISTIO_META_HTTP10
              value: '1'`
