### ISSUE TITLE
Routing allows unauthorised access to internal services

### ISSUE THREAD

**Issue by jkbschmid** [istio/istio#13086]
**Describe the bug**

We tried to configure mutual TLS access to grafana from outside the cluster. But we recognised that grafana was also reachable over normal HTTP although we never configured this.

We stripped down the problem by replacing the mutual TLS configuration in the deployed Gateway with HTTP for a different port.

When sending an HTTP-request to the ingress-gateway on port 80, the request is routed to Grafana, instead of returning 404. This is a security issue.
Note: We could not reproduce this with the default helm installation method, but still, this behaviour should not occur independent of the installation method.
```
export INGRESS_HOST=$(kubectl -n istio-ingress get service ingressgateway -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
curl http://grafana.mydomain.local/ --resolve grafana.mydomain.local:80:${INGRESS_HOST} -v
```

**Expected behavior**

The curl on port 80 returns a 404-not found.

**Steps to reproduce the bug**

Install istio-1.1.0 using [this script](https://github.com/istio-ecosystem/istio-installer/blob/master/bin/install.sh) from istio-ecosystem. It installs the istio components into separate namespaces and has mTLS enabled.

* Apply the following configuration:

```bash
INGRESS_NAMESPACE=istio-ingress
TELEMETRY_NAMESPACE=istio-telemetry

kubectl -n $INGRESS_NAMESPACE apply -f - <<EOF
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: grafana-gateway
spec:
  servers:
  - hosts:
    - grafana.mydomain.local
    port:
      number: 10001
      name: http
      protocol: HTTP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana
spec:
  hosts:
  - grafana.mydomain.local
  gateways:
  - grafana-gateway
  http:
  - route:
    - destination:
        host: grafana.${TELEMETRY_NAMESPACE}.svc.cluster.local 
        port:
          number: 3000
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: grafana 
spec:
  host: grafana.${TELEMETRY_NAMESPACE}.svc.cluster.local 
  trafficPolicy:
    tls:
      mode: DISABLE
EOF
```

**Version**

istio 1.1.0

**Installation**

Install istio-1.1.0 using [this script](https://github.com/istio-ecosystem/istio-installer/blob/master/bin/install.sh).

**Environment**

GCP

**Cluster state**

**Comment by howardjohn** [comment]
Are you still seeing this? On latest Istio I see:
```
$ curl http://grafana.mydomain.local/ --resolve grafana.mydomain.local:80:${INGRESS_HOST} -v
* Expire in 0 ms for 6 (transfer 0x55ee458cedd0)
* Added grafana.mydomain.local:80:34.67.60.151 to DNS cache
* Hostname grafana.mydomain.local was found in DNS cache
*   Trying 34.67.60.151...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x55ee458cedd0)
* Connected to grafana.mydomain.local (34.67.60.151) port 80 (#0)
> GET / HTTP/1.1
> Host: grafana.mydomain.local
> User-Agent: curl/7.64.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
< date: Sun, 25 Aug 2019 22:23:07 GMT
< server: istio-envoy
< content-length: 0
<
```

Which is what we expect?

**Comment by holgero** [comment]
It was a corner case anyway and we found our way around it in the mean time.
