### ISSUE TITLE
Helm Repo index.yaml wrong for 1.1.2

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#13102]
`wget https://storage.googleapis.com/istio-release/releases/1.1.2/charts/istio-1.1.2.tgz` works as expected

```bash
$ helm repo add istio.io https://storage.googleapis.com/istio-release/releases/1.1.2/charts/
$ helm fetch istio.io/istio
Error: Failed to fetch https://storage.googleapis.com/istio-release/releases/1.1.2/charts/istio-1.1.0.tgz : 404 Not Found
```
Fails

curl `curl https://storage.googleapis.com/istio-release/releases/1.1.2/charts/index.yaml` shows the manifest lists 1.1.0 as the version so it tries to download a version that doesn't exist

**Comment by utka** [comment]
Updated.
