### ISSUE TITLE
Azure kubernetes service has 12GB memory , but Istio pilot pod can't run cause by insufficient memory.

### ISSUE THREAD

**Issue by tozastation** [istio/istio#13111]
**Describe the bug**
Azure kubernetes service has 12GB memory , but Istio pilot pod can't run cause by insufficient memory.

**Expected behavior**
```
Warning  FailedScheduling  2m12s (x41 over 30m)  default-scheduler  0/3 nodes are available: 3 Insufficient memory.
```

**Steps to reproduce the bug**

**Version**
k8s: 1.12.6
istio: 1.1.2

**Installation**
- `kubectl apply -f install/kubernetes/helm/istio-init/files/`
- `kubectl apply -f install/kubernetes/istio-demo.yaml`

**Environment**

**Cluster state**
- [istio-dump.zip](https://github.com/istio/istio/files/3050189/istio-dump.zip)

**Comment by sasachan** [comment]
Warning  FailedScheduling  53s (x16 over 4m8s)  default-scheduler  0/2 nodes are available:
2 Insufficient memory.  I will give a try to upgrade node memory to 8GB

**Comment by howardjohn** [comment]
I would suggest you look at `kubectl describe nodes` which will show all the resource requests.

I suspect you have something that is requesting a lot of your 12GB of memory (that isn't that much, so I wouldn't be surprised if you did).

I don't think this is related to Istio, https://kubernetes.io/docs/tasks/configure-pod-container/assign-memory-resource/ may help you further.

If you want to change the memory requests for Pilot, see https://istio.io/docs/reference/config/installation-options/ for the options to do so.

I don't think this is directly an Istio problem though, so I think it is best if we close this (nothing personal, we are trying to clean up issues though).
