### ISSUE TITLE
Simple denials - Bookinfo rules not work

### ISSUE THREAD

**Issue by ardhiee** [istio/istio#13122]
**Describe the bug**
The star ratings in the sample http://myhostname:31380/productpage still showing the v3 reviews (3 red start), although i already apply the **kubectl apply -f samples/bookinfo/policy/mixer-rule-deny-label.yaml**

**Expected behavior**
The red star is not showing

**Steps to reproduce the bug**
Uninstall bookinfo sample applications

**Version**
istio 1.1.0
k8s 1.12.5

**Installation**
helm install

**Environment**
RHEL 7.0

**Comment by dotw** [comment]
Did you --set global.disablePolicyChecks=false 
see more details https://istio.io/docs/tasks/policy-enforcement/enabling-policy/

**Comment by ardhiee** [comment]
Yes @dotw . I already set the policy enforcement

`
[root@node1 ~]# kubectl -n istio-system get cm istio -o jsonpath="{@.data.mesh}" | grep disablePolicyChecks
disablePolicyChecks: false
`

**Comment by ardhiee** [comment]
`apiVersion: "config.istio.io/v1alpha2"
kind: denier
metadata:
  name: denyreviewsv3handler
spec:
  status:
    code: 7
    message: Not allowed
---
apiVersion: "config.istio.io/v1alpha2"
kind: checknothing
metadata:
  name: denyreviewsv3request
spec:
---
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: denyreviewsv3
spec:
  match: destination.labels["app"] == "ratings" && source.labels["app"]=="reviews" && source.labels["version"] == "v3"
  actions:
  - handler: denyreviewsv3handler.denier
    instances: [ denyreviewsv3request.checknothing ]`

using this kind of yaml configuration the red start still showing.

**Comment by ardhiee** [comment]
Hi @kyessenov did you know how to debug this policy, since i still cannot get the mixer policy enforcement runs

**Comment by kyessenov** [comment]
There's a certain amount of delay before the policy applies. Proxies generally cache the results of the policy evaluation for seconds-to-minute, so you might need to wait a bit before seeing the denial.

Also, the policies must reside in the namespace of the application. So if you installed the bookinfo into some other namespace, then you need to move the policy resources to the same namespace or to `istio-system`, which acts as the default override.

From what I can tell, the sample is a copy of https://raw.githubusercontent.com/istio/istio/release-1.1/samples/bookinfo/policy/mixer-rule-deny-label.yaml, which is regularly tested as part of our presubmit.

**Comment by ardhiee** [comment]
Hi @kyessenov thanks for your reply, 

So i assume i just wait a bit after apply the yaml. Bookinfo deployed in the default namespace
```
[root@node1 ~]# kubectl get pods -n default
NAME                              READY   STATUS    RESTARTS   AGE
details-v1-bc557b7fc-vrk6s        2/2     Running   0          12h
fortio-deploy-7cc887f7f5-9g95w    2/2     Running   0          9h
productpage-v1-6597cb5df9-ll6fw   2/2     Running   0          12h
ratings-v1-5c46fc6f85-974m2       2/2     Running   0          12h
reviews-v1-69dcdb544-dk96m        2/2     Running   0          12h
reviews-v2-65fbdc9f88-8kl7c       2/2     Running   0          12h
reviews-v3-bd8855bdd-rm2n2        2/2     Running   0          12h
```

denier + checknothing + rule also in the default namespace
```
[root@node1 istio-1.1.0]# kubectl get rule -n default
NAME            AGE
denyreviewsv3   5m
[root@node1 istio-1.1.0]# kubectl get denier -n default
NAME                   AGE
denyreviewsv3handler   5m
[root@node1 istio-1.1.0]# kubectl get checknothing  -n default
NAME                   AGE
denyreviewsv3request   6m
```

Based on your comment may i know is there any way to somehow clear the cache so the policy will get the new updated configuration ?

**Comment by kyessenov** [comment]
I think the only reliable way to flush the cache is to restart the pod with the sidecar proxy. Freshly started proxy will see the latest policy state.

**Comment by ardhiee** [comment]
Hi @kyessenov 

The red star rating still showing after i deleted all the pods in the namespace default.
```
[root@node1 ~]# kubectl get pods -n default
NAME                              READY   STATUS    RESTARTS   AGE
details-v1-bc557b7fc-g86bp        2/2     Running   0          62s
fortio-deploy-7cc887f7f5-bhgx2    2/2     Running   0          62s
productpage-v1-6597cb5df9-cplzt   2/2     Running   0          62s
ratings-v1-5c46fc6f85-65ntr       2/2     Running   0          61s
reviews-v1-69dcdb544-rt8js        2/2     Running   0          61s
reviews-v2-65fbdc9f88-lg7vq       2/2     Running   0          61s
reviews-v3-bd8855bdd-jgwmb        2/2     Running   0          61s
```

Do you have any tips to debug the mixer policy ? so i know where are the root cause of this issues ? appreciate your help

**Comment by douglas-reid** [comment]
One suggestion: ensure that traffic is going to your `istio-policy` service. Related FAQ entry: https://istio.io/help/ops/telemetry/missing-metrics/#verify-mixer-is-receiving-report-calls (you will need to look for requests to the `istio-policy` pod instead).

**Comment by Parvathy-Geetha** [comment]
@douglas-reid  i think my traffic for the denier isn't going via the denier anymore. It was initially but not anymore. How can i debug this?
