### ISSUE TITLE
EndUser Authentication failure in private GKE

### ISSUE THREAD

**Issue by sumeetoc** [istio/istio#13132]
**Describe the bug**
I've a demo application with end user authentication and RBAC enabled which works fine in Istio enabled public GKE cluster, however, the same in Private GKE cluster- the end user authentication is not working, Istio is not validating the tokens, all of the requests which comes to the ingress-gateway is send to the destination directly from the defined Gateway and VirtualService

**Expected behavior**
The End user authentication should have worked for Istio enabled Private GKE cluster as well

**Steps to reproduce the bug**
In GCP, create a private GKE(private master and node) with Istio enabled as STRICT and deploy an application with gateway, virtualservice, and policy to validate the jwt token(using OKTA)

**Version**
Istio Version:"1.1.1"
Kubernetes Version:"1.11.7-gke.12"

**Installation**
As an add-on in GKE with mTLS as STRICT

**Environment**
Google Cloud

**Cluster state**
Attached

[k8s_resources.yaml.tar.gz](https://github.com/istio/istio/files/3053363/k8s_resources.yaml.tar.gz)

**Comment by sumeetoc** [comment]
On more investigation I found out that what I am trying might not be possible, need some help getting confirmation though.

So my usecase uses Istio's End user authentication in a private gke cluster where master and nodes both are private without any source of Internet connectivity.

Only the Istio ingressgateway has the public IP and hence all of the requests made from the Internet is reachable to the application running inside the cluster. In the Istio's ingress gateway logs I have found that it is not able to reach to the OKTA for jwt token authentication, it timeouts.

If I configure an Engress gateway with an External LoadBalancer will the traffic from Ingress will be able to reach to the internet using it?

**Comment by yangminzhu** [comment]
Just FYI, if you're using the Istio Authentication JWT Policy, then Pilot needs to talk to external server to fetch the JWT public key needed to verify the JWT token. I'm not sure how is the okta configured on the ingress gateway, but I guess it needs to do the same thing in order to validate the JWT token.

 I haven't tried to use Egress gateway to proxy the request from Ingress (or even Pilot), but this seems possible. 

Adding some networking experts, @costinm @rshriram

**Comment by sumeetoc** [comment]
@yangminzhu Thanks for the reply, it would be helpful i believe in a private environment with only one service communicating the outside world.
