### ISSUE TITLE
Extend istioctl tab completion to support zsh

### ISSUE THREAD

**Issue by ericvn** [istio/istio#13139]
Issue #12607 was create to enable `istioctl` tab completion. The main focus for that issue is for the *bash* shell. This issue is extending that support for users of the *Z* shell.

This support requires a few items:
  - extend `istioctl` to actually generate the *zsh* completion file
     This will use the _corba_ framework similar to the way the *bash* completion file is done.
     The problem is that currently, the *zsh* completion file generated by the _corba_ framework doesn't work. They have a PR, https://github.com/spf13/cobra/pull/828, which does actually provide a *zsh* completion file that works.
 - update the process to distribute this new file similar to the *bash* completion file
 - update docs as need.

**Comment by ericvn** [comment]
A PR, https://github.com/istio/istio/pull/13140, for the first bullet.

**Comment by ericvn** [comment]
The changes as noted depend on a cobra PR spf13/cobra#828. Not seeing any traction on the PR, and from the UX workgroup, @therealmitchconnors communicated with Steve (owner of the repo):
```
 I talked to Steve Francia about zsh completions in cobra. It sounds like it has been a thorny enough issue for cobra that he’s not really interested in picking a winner and kicking the hornets’ nest, so to speak. He offered to make someone on the team a maintainer, and let us sort through the problems with zsh completion, but that’s not something I have time to invest in.

My recommendation for the time being would be to see if we can somehow leverage kubectl’s zsh completion logic without copying it outright. What do you think?

Mitch
``` 

Based on that feedback, I created a number of branches to figure out ways to move forward:

1) Fix the broken _cobra_ zsh completion. The current file generated by the cobra _GenZshCompletion_ does not work. I was able to add some lines to the top and bottom of the generated output to fix the problems. I can do that programmatically.
 - Pro: Easy change
 - Con: the completion file only completes sub-command names, and not any flags.
    ie. `istioctl authn tls-check` but no tab with a - to add `--log_output_level` to the above

I will note that trying to use the _bash_ completion support in _zsh_ did not work for _cobra_ related completion files. The files contain _bash_ specific command flags, and won't work on their own. The cobra PR basically derived some constants from the `kubectl` source and added them to a file around the _GenBashCompletion_ output. to allow the _GenBashCompletion_ output to work with zsh. The constants have been stable for a while.

2) Call the Kubernetes kubectl method to generate the file
https://github.com/ericvn/istio/commits/istioctlZSH (two commits, 1 for vendor, 1 for our change)
Pros:
 - We don't have any derived K8s code
Cons:
 - We pull in a large vendor commit to add the `k8s.io/kubernetes/pkg/kubectl/cmd` dependency
    1,065 changed files with 188,735 additions and 3,102 deletions.
 - The package above changes in 1.12 so we would need at least an import change along with the dep/module changes.
 - The generated completion file has a bunch of _kubectl_s spread around it:
```
__kubectl_convert_bash_to_zsh() {
	sed \
	-e 's/declare -F/whence -w/' \
	-e 's/_get_comp_words_by_ref "\$@"/_get_comp_words_by_ref "\$*"/' \
	-e 's/local \([a-zA-Z0-9_]*\)=/local \1; \1=/' \
	-e 's/flags+=("\(--.*\)=")/flags+=("\1"); two_word_flags+=("\1")/' \
	-e 's/must_have_one_flag+=("\(--.*\)=")/must_have_one_flag+=("\1")/' \
	-e "s/${LWORD}_filedir${RWORD}/__istioctl_filedir/g" \
	-e "s/${LWORD}_get_comp_words_by_ref${RWORD}/__istioctl_get_comp_words_by_ref/g" \
	-e "s/${LWORD}__ltrim_colon_completions${RWORD}/__kubectl_ltrim_colon_completions/g" \
	-e "s/${LWORD}compgen${RWORD}/__kubectl_compgen/g" \
	-e "s/${LWORD}compopt${RWORD}/__kubectl_compopt/g" \
	-e "s/${LWORD}declare${RWORD}/builtin declare/g" \
	-e "s/\\\$(type${RWORD}/\$(__kubectl_type/g" \
	<<'BASH_COMPLETION_EOF'
``` 

3) Make local change derived on K8s code: Branch: https://github.com/ericvn/istio/commits/istioctlZSH_2  

A small commit deriving the 3 constants from K8s code and adding them to the output along with the _GenBashCompletion_ output
Pros:
  - Small change
  - Has support for flags
  - completion file has istioctl names instead of kubectl names.
Cons:
 - Add Note that we derived constants from K8s?

**Comment by ericvn** [comment]
@linsun @kyessenov @andraxylia @costinm @esnible 

Can I get some feedback on the previous comment relative to the options. Feel free to add others as needed. 

Thanks.

**Comment by linsun** [comment]
Giving 1) doesn't work for flags and 2) drags on large dependency and potentially increase on istioctl binary, I'd vote for 3.

**Comment by ericvn** [comment]
I asked here and in Slack for discussion on this item, and based on the limited feedback, I will go ahead with and create the PR for option #3.

**Comment by ericvn** [comment]
Part #1: https://github.com/istio/istio/pull/13871

**Comment by ericvn** [comment]
Completed in #13871
