### ISSUE TITLE
istio grafana issue "Invalid dimensions for plot, width = 422, height = 0"

### ISSUE THREAD

**Issue by dotw** [istio/istio#13133]
**Describe the bug**
grafana panel can be shared using iframe. But istio customized grafan (istio 1.1.2) has one issue when using iframe. the panel reports "Invalid dimensions for plot, width = 422, height = 0"

Please notice, istio 1.0.5 has no similar bugs.

**Expected behavior**
istio 1.1.2 should work.

**Steps to reproduce the bug**
1. go to grafana
2. go to istio service dashboard
3. choose one service
4. click the title 'client request duration'
5. choose share -> embedded, and then copy the iframe source to a empty html file e.g test.html
6. open test.html using chrome
7. the page reports "Invalid dimensions for plot, width = 422, height = 0"

Please notice, panels like 'client request volume'  don't have similar issues. 
**Version**
1.1.2

**Installation**
istio is installed using helm chart

**Environment**
istio 1.1.2
k8s 1.12.4

**Comment by esnible** [comment]
I have tagged this `area/user experience` but none of us have experience with Grafana as far as I know.  @mandarjog @douglas-reid Can we also tag this `area/policies and telemetry`?  And who is the owner of Grafana dashboard stuff?

**Comment by dotw** [comment]
@esnible I downgrade grafana from 5.4.0 to 5.2.3. iframe works again. my question is do we have any dependencies with 5.4.0 in istio 1.1.2?

**Comment by dotw** [comment]
tried 5.4.3 just now. iframe also works.

**Comment by esnible** [comment]
Moving to Istio 1.2.  @dotw suggests upgrading Grafana to 5.4.3.  Is this already fixed in master?  The chart _install/kubernetes/helm/istio/charts/grafana/values.yaml_ makes it look like we now install Grafana 6.0.2

**Comment by douglas-reid** [comment]
@esnible The P&T WG owns the dashboards.

I'm not aware of any dependencies on a particular grafana version, but we have indeed upgraded to 6.X.

**Comment by fpesce** [comment]
> @esnible The P&T WG owns the dashboards.

Maybe ping @mandarjog

**Comment by esnible** [comment]
Closing because Istio 1.2 shipped with Grafana 6.1.6.  If anyone is getting this issue please re-open.
