### ISSUE TITLE
Reduce Latency spikes due to batch reports to istio-telemetry

### ISSUE THREAD

**Issue by zachidan** [istio/istio#13142]
**Describe the bug**
From my performance benchmark [results](https://github.com/istio/istio/files/3054827/IKS-Latency.pdf) - when `istio-telemetry` is enabled, there are latency spikes that dramatically increase the 90th percentile and 99th percentile.

For example:
| istio-telemetry | p=90 | p=99 |
| :------------- | :---: | :---: |
| enabled | 7.3 msec | 14.1 msec |
| disabled | 2.4 msec | 5.0  msec |

Command: fortio load -qps 1000 -c 10 -t 60s fortio-server

It looks that the spikes are coming from the batch report which is sent by the `istio-proxy` every 1,000 requests to the `istio-telemetry`.

**Expected behavior**
No huge latency spikes even if `istio-telemetry` is enabled.

It is clear that `istio-telemetry` adds some overhead, but I think that it is possible to optimize the batch reports and to smooth the spikes.

**Version**
istio-1.1-snapshot.5

**Environment**
IBM Kubernetes service (IKS) version **1.12.6** with 3 worker nodes (4 CPUs, 16GB RAM)
[Fortio](https://github.com/fortio/fortio) as load generator

**Comment by mandarjog** [comment]
@zachidan The batch size  [100](https://github.com/istio/proxy/blob/master/include/istio/mixerclient/options.h#L59)

You can make it configurable and see the effect. It is a tradeoff between tail latency and CPU usage on mixer server.

**Comment by zachidan** [comment]
@mandarjog The main reason for the tail latency is that a **lock** is held throughout the `SendReport` operation which might takes several milliseconds. I'll take a look into this issue.
