### ISSUE TITLE
Envoy deprecated field tcp_proxy.proto:deprecated_v1

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#13156]
This field will be deprecated, we need to remove it
envoy.deprecated_features.tcp_proxy.proto:deprecated_v1"

https://github.com/envoyproxy/envoy/pull/6509/files

cc @duderino

**Comment by silentdai** [comment]
I searched the code base as well. The only struct in deprecated_v1 is TCPRoute. There was reference to "TCPRoute" but that "TCPRoute" is actually in other namespace. I think istio is good on the this deprecation.

**Comment by andraxylia** [comment]
Thanks for investigatin @silentdai
