### ISSUE TITLE
istio.io/istio/tests/integration/mixer TestCheck_Deny is failing

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#13155]
https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/13151/istio-integ-local-tests/8234

appears to be failing for unrelated change

/cc @nmittler

**Comment by duderino** [comment]
@kyessenov I'm hoping that others can debug integration test framework failures other than Nate and Oz

**Comment by kyessenov** [comment]
There was a known flake that is re-mediated by increasing timeout from 1 minute to 5 minutes in here https://github.com/istio/istio/pull/14758. The culprit is that gRPC makes just 2 DNS resolutions per minute, so if you lucked out on the first one, the test would fail.

**Comment by kyessenov** [comment]
Last failure is due to short-wait in the test:
https://prow.k8s.io/view/gcs/istio-prow/logs/integ-mixer-k8s-postsubmit-tests-master/142

The test only waited 36s instead of >5 mins. I think this can be closed once the fix to increase the time out to 5 minutes makes it to all branches.
