### ISSUE TITLE
CA rotation in node agent when using sds

### ISSUE THREAD

**Issue by MarcosDY** [istio/istio#13158]
**Describe the bug**
When a new CA certificate is issued, it's updated into the cache, but not propagated to proxies, which causes mTLS connections to fail when the CA certs in possession by the the proxies expire. This issue affects the current external CA providers (vault, google), as well as Spire, which is being worked on currently.
This issue is probably related to this `TODO`
https://github.com/istio/istio/blob/576850c8780233e17ea0c9e5ec9c120e7a998fdd/security/pkg/nodeagent/cache/secretcache.go#L537

**Expected behavior**
CAs are propagated to proxies the same way certificates are.

**Comment by evan2645** [comment]
This is fixed, right?

**Comment by MarcosDY** [comment]
it is waiting for a final review, all suggested changes are done

**Comment by evan2645** [comment]
@MarcosDY Is the fix for this not #13163? It has already been merged

**Comment by MarcosDY** [comment]
Sorry it is merged! so this is issue is currently fixed, sorry for confusion
