### ISSUE TITLE
Gateways doesn't work with GCP + Kubernetes 1.13.2

### ISSUE THREAD

**Issue by sdake** [istio/istio#13162]
**Describe the bug**
The gateways implementation doesn't work when deployed on GCP + Kubernetes 1.13.2.

**Expected behavior**
Gateways implementation should work.

**Steps to reproduce the bug**
Deploy Kubernetes via stackpoint.io GCP -> leads to k8s 1.13.2 with screenshots in 2nd comment
Deploy Kubernetes via stackpoint.io GKE -> leads to k8s 1.12.6 with screenshots in 3rd dcomment

**Version**
Istio 1.1.0 was used for this test
Kubernetes 1.12.6 (GKE based)
Kubernetes 1.13.2 (GCP based)

**Installation**
See: https://istio.io/docs/setup/kubernetes/install/multicluster/gateways/

**Environment**
GCP + Kubernetes 1.13.2 in one case (doesn't work)
GKE + Kubernetes 1.12.6 in the other case (does work)

**Comment by sdake** [comment]
GCP + Kubernetes 1.13.2 screenshots of load balancer:

<img width="1165" alt="Screen Shot 2019-04-08 at 5 05 56 PM" src="https://user-images.githubusercontent.com/755849/55764732-ad559b00-5a21-11e9-9796-8ceed0853809.png">


<img width="671" alt="Screen Shot 2019-04-08 at 5 06 05 PM" src="https://user-images.githubusercontent.com/755849/55764745-bcd4e400-5a21-11e9-8af8-82e4b5cd86ee.png">


<img width="1058" alt="Screen Shot 2019-04-08 at 5 06 17 PM" src="https://user-images.githubusercontent.com/755849/55764752-c52d1f00-5a21-11e9-93bc-d797d7f98947.png">


<img width="652" alt="Screen Shot 2019-04-08 at 5 06 30 PM" src="https://user-images.githubusercontent.com/755849/55764758-d0804a80-5a21-11e9-8877-cc954c6d8d7f.png">


<img width="861" alt="Screen Shot 2019-04-08 at 5 06 47 PM" src="https://user-images.githubusercontent.com/755849/55764780-df66fd00-5a21-11e9-83ea-c4f806e06eae.png">


<img width="357" alt="Screen Shot 2019-04-08 at 5 07 18 PM" src="https://user-images.githubusercontent.com/755849/55764795-ea219200-5a21-11e9-8a5a-5f824bc5f514.png">

**Comment by sdake** [comment]
GKE + Kubernetes 1.12.6 screenshots of load balancer:

<img width="1161" alt="Screen Shot 2019-04-08 at 4 55 38 PM" src="https://user-images.githubusercontent.com/755849/55764967-75028c80-5a22-11e9-9a5a-6ee4bd070416.png">
<img width="658" alt="Screen Shot 2019-04-08 at 4 55 53 PM" src="https://user-images.githubusercontent.com/755849/55765006-91062e00-5a22-11e9-831a-8f602f52412d.png">

<img width="1019" alt="Screen Shot 2019-04-08 at 4 56 03 PM" src="https://user-images.githubusercontent.com/755849/55765014-9e231d00-5a22-11e9-84ac-3f167efdb1d6.png">

<img width="640" alt="Screen Shot 2019-04-08 at 4 56 11 PM" src="https://user-images.githubusercontent.com/755849/55765032-b6933780-5a22-11e9-918d-3bbbd9b366b8.png">

<img width="637" alt="Screen Shot 2019-04-08 at 4 56 23 PM" src="https://user-images.githubusercontent.com/755849/55765061-d32f6f80-5a22-11e9-99f0-7b8bd55e84d2.png">

<img width="874" alt="Screen Shot 2019-04-08 at 4 56 30 PM" src="https://user-images.githubusercontent.com/755849/55765072-de829b00-5a22-11e9-888b-56e9b0718e8f.png">


<img width="381" alt="Screen Shot 2019-04-08 at 4 56 54 PM" src="https://user-images.githubusercontent.com/755849/55765087-e80c0300-5a22-11e9-9f3a-35db7d80595a.png">

**Comment by sdake** [comment]
healthchecks are different.  Not sure if this is material.

**Comment by sdake** [comment]
proxy protocol should likely be TCP rather than none on 1.13.2.

Cheers
-steve

**Comment by duderino** [comment]
Hi @andraxylia could you take a look and perhaps pull in the right GKE denizen?

**Comment by sdake** [comment]
I have found kubeadm 1.13.2 does not create a deployment called `l7-default-backend` when deployed on GCP.  GKE does create this deployment.  I believe what is happening is that the l7-default-backend deployment is used by the load balancer for health checking.  As GCP 1.13.2 is missing the deployment, the LB takes the month off :)

The contents of the deployment are as follows
```
sdake@beast-01:~/ $ kubectl get deployment -n kube-system l7-default-backend -oyaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","k8s-app":"glbc","kubernetes.io/cluster-service":"true","kubernetes.io/name":"GLBC"},"name":"l7-default-backend","namespace":"kube-system"},"spec":{"selector":{"matchLabels":{"k8s-app":"glbc"}},"template":{"metadata":{"annotations":{"seccomp.security.alpha.kubernetes.io/pod":"docker/default"},"labels":{"k8s-app":"glbc","name":"glbc"}},"spec":{"containers":[{"image":"k8s.gcr.io/defaultbackend-amd64:1.5","livenessProbe":{"httpGet":{"path":"/healthz","port":8080,"scheme":"HTTP"},"initialDelaySeconds":30,"timeoutSeconds":5},"name":"default-http-backend","ports":[{"containerPort":8080}],"resources":{"limits":{"cpu":"10m","memory":"20Mi"},"requests":{"cpu":"10m","memory":"20Mi"}}}]}}}}
  creationTimestamp: "2019-04-09T18:07:02Z"
  generation: 1
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    k8s-app: glbc
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: GLBC
  name: l7-default-backend
  namespace: kube-system
  resourceVersion: "914"
  selfLink: /apis/extensions/v1beta1/namespaces/kube-system/deployments/l7-default-backend
  uid: 46a0b17f-5af2-11e9-8602-42010a8e0fc4
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: glbc
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: docker/default
      creationTimestamp: null
      labels:
        k8s-app: glbc
        name: glbc
    spec:
      containers:
      - image: k8s.gcr.io/defaultbackend-amd64:1.5
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: default-http-backend
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
          requests:
            cpu: 10m
            memory: 20Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-04-09T18:07:55Z"
    lastUpdateTime: "2019-04-09T18:07:55Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2019-04-09T18:07:02Z"
    lastUpdateTime: "2019-04-09T18:07:55Z"
    message: ReplicaSet "l7-default-backend-fd59995cd" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
```

**Comment by sdake** [comment]
this was an error in the implementation of stackpoint.io.
