### ISSUE TITLE
TLS Passthrough with Caddy autogenerating Certificate is broken

### ISSUE THREAD

**Issue by bradenwright** [istio/istio#13174]
**Describe the bug**
We use Caddy so when users hit the site via a domain, if the certificate doesn't exists on first connection to port 443 Caddy will fetch the cert, set it up on disk and then allow the connection to use the cert that was dynamically generated (via letsencrypt).

Problem is that first time Caddy is hit the connection is closed.  Therefore connection errors, the certificate is never downloaded, so the page never starts working.  If I use a Service LB, then the TCP connection works great and fetching the Cert and showing me a valid SSL cert but I started getting errors when trying to login to the site, etc.  Seems like headers were getting dropped.

Everything works great if I setup a Service resource of type LB, but just can't seem to get it to work.  I'll post some more details

**Expected behavior**
The SSL certificate gets dynamically created without reseting the connection, so on the first connection to port 443 the cert is made available and SSL/TLS just work.

**Steps to reproduce the bug**
Setup Caddy running in a pod, I'm fairly new to Caddy but can def share some configs if needed

**Version**
1.1.0

**Installation**
helm

**Environment**
GKE

**Cluster state**
N/A

**Comment by bradenwright** [comment]
Anyone have any ideas?  I don't even really know where to start

**Comment by g-p-n** [comment]
@bradenwright Can you please share your helm chart and any values that you might be using?
I shall attempt to reproduce the issue you are seeing.

**Comment by bradenwright** [comment]
Working on getting that put together and will post soon

**Comment by incfly** [comment]
Bug scrubbing
Closing since this can be fixed by changing configuration.
