### ISSUE TITLE
[Test Framework]: Re-think Native Sidecar

### ISSUE THREAD

**Issue by nmittler** [istio/istio#13177]
The current apps component employs a lot of hackery when running an Envoy sidecar natively, which leads to issues:

- Not running with the real Pilot Agent. This is mostly due to the fact that pilot agent is a bit of a mess and isn't usable natively in its current form. This is a large chunk of code that is completely untested when running natively.
- The native (i.e. fake) Pilot Agent filters the Discovery responses from Pilot: 
  - Remove the bound virtual listener port (where iptables redirects to). It's assigned a constant value, which will collide with other apps. 
  - Remove management clusters. They're assigned constant values, which will collide with other apps.
  - Remove all inbound listeners, since they are statically created in the Envoy boostrap yaml. In addition, I believe that since we're using 127.0.0.1 as the IP address for all services/instances Pilot may mistakenly return inbound listeners for all service instances since they're all on the same IP.
  - Since there are no iptables to intercept outbound traffic, we need to bind real local ports for the outbound listeners that the application can send to. This requires that the application has to be aware of which ports will ultimately be routed to a given target service (see below for details). 
- The application has to be *aware* of the sidecar in that it has to modify outbound requests in the following ways:
  -  Since there is no host on native OS for the destination service (e.g. `service-b.svc.local`), the host must be changed to `127.0.0.1`
  - In order to make the request go through the application's Envoy, the destination port must be changed to the port of the outbound listener for the destination service.

All of this greatly changes the behavior of the system to the point where it's unclear how much of Pilot/Envoy we're actually testing. It's also fragile and will likely be hard to maintain going forward as the contract between Pilot and Envoy evolves.

We need to re-think how we run Pilot and Envoy in a native environment to reduce the overall complexity and increase test coverage.

**Comment by howardjohn** [comment]
Just a datapoint - this is blocking using native for https://github.com/istio/istio/pull/13099

**Comment by nmittler** [comment]
@louiscryan @smawson @duderino @ozevren @howardjohn @costinm @rshriram  Regarding sidecar in the native environment:

I've been playing around a bit with docker in [this branch](https://github.com/nmittler/istio/tree/echo-docker) and have [some basic things working](https://github.com/nmittler/istio/blob/echo-docker/pkg/test/framework/components/echo/docker/docker_test.go).

For now this would essentially be the no-sidecar case, but I suspect it should be reasonable to add support for sidecar as well.

Before I go further, however, I'd like to take a step back and discuss. A couple of things that come to mind:

1. Does this seem like a reasonable approach for the native environment? Debuggability will only be lost on the echo containers.  Other services, such as Pilot and Galley will be running on the native host.
2. What prior work exists (if any) that I might be able to leverage? I know there has been on-going work in the VM area, for example. It would be good to use as much production code as possible, rather than writing yet another harness just for native testing.

I'm sure there are a ton of things I'm not thinking about, but I just want to get the discussion started.
