### ISSUE TITLE
Refactor istioctl commands out of istioctl/cmd/istioctl for testing

### ISSUE THREAD

**Issue by esnible** [istio/istio#13180]
_istioctl/cmd/istioctl_ is a `main` -- a program rather than a library package.

This means there is no way for tests outside _istioctl/cmd/istioctl_ to call any of the commands.

This work item is to move nearly all of the code in _istioctl/cmd/istioctl_ into _istioctl/pkg_ similarly to how the `validate` command is implemented.

**Comment by esnible** [comment]
It looks like there is already a PR for almost exactly the same thing: https://github.com/istio/istio/pull/13277

**Comment by jwendell** [comment]
@esnible yep. My intention after this PR gets merged is to make istioctl subcommands more modular so that we can selectively choose what subcommands we want to expose rather than have all of them in a single `GetRootCmd()`

**Comment by esnible** [comment]
@jwendell After your PR gets merged we will be able to write a great deal more testing, to get code coverage up.  I have a PR that is blocked because of code coverage, and there is no way to increase the code coverage until your PR is merged.
