### ISSUE TITLE
Call to K8s ExternalName service fails when using Istio sidecar

### ISSUE THREAD

**Issue by akashrv** [istio/istio#13193]
**Describe the bug**
A call to K8s ExternalName service fails, when using Istio sidecar in the POD from where the call is made. This happens when the K8s service to which the ExternalName service points to has a named port.

**Expected behavior**
Since K8s ExternalName service is a native K8s feature, I expect Istio side car should support it. This affects Knative eventing where we us K8s External Service (in user namespace) to route events to a common dispatcher service (in Knative eventing namespace)

**Steps to reproduce the bug**
1. Go to: https://github.com/akashrv/exp. Branch: istioexternalnameissue
2. ko apply -f [SetupWithSideCarWithNamedPort.yaml ](https://github.com/akashrv/exp/blob/istioexternalnameissue/SetupWithSideCarWithNamedPort.yaml)--> To reproduce the issue
3. ko apply -f [SetupWithSideCarAndNoNamedPort.yaml](https://github.com/akashrv/exp/blob/istioexternalnameissue/SetupWithSideCarAndNoNamedPort.yaml) --> To see the issue goes away when not using named port
4. ko apply -f [SetupNoSideCarWithNamedPort.yaml](https://github.com/akashrv/exp/blob/istioexternalnameissue/SetupNoSideCarWithNamedPort.yaml) --> To see the issue goes away when not using istio sidecar

After installing any yaml.
1. Get the curl pod
2. k -n istioissue exec -it <curl pod name> -- /bin/sh
3. curl -v http://es-ws-kne/
4. Either returns 404 (in case of an issue) or 200 (no issue)

**Version**
{{ What version of Istio and Kubernetes are you using? Use `istioctl version --remote` and `kubectl version` }}
**istioctl version --remote:**
client version: version.BuildInfo{Version:"1.1.2", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989", User:"root", Host:"35adf5bb-5570-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.1"}
cluster-local-gateway version: version.BuildInfo{Version:"", GitRevision:"", User:"", Host:"", GolangVersion:"", DockerHub:"", BuildStatus:"", GitTag:""}
citadel version: version.BuildInfo{Version:"1.1.2", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"35adf5bb-5570-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.1"}
galley version: version.BuildInfo{Version:"1.1.2", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"35adf5bb-5570-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.1"}
ingressgateway version: version.BuildInfo{Version:"bdda7cfcf5ba1397e6e0e2629d53114c9ea8fc14", GitRevision:"bdda7cfcf5ba1397e6e0e2629d53114c9ea8fc14", User:"mjog", Host:"devinstance.c.mixologist-142215.internal", GolangVersion:"go1.10.1", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-snapshot.4-592-gbdda7cf"}
pilot version: version.BuildInfo{Version:"1.1.2", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"35adf5bb-5570-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.1"}
pilot version: version.BuildInfo{Version:"1.1.2", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"35adf5bb-5570-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.1"}
policy version: version.BuildInfo{Version:"1.1.2", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"35adf5bb-5570-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.1"}
sidecar-injector version: version.BuildInfo{Version:"1.1.2", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"35adf5bb-5570-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.1"}
telemetry version: version.BuildInfo{Version:"1.1.2", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"35adf5bb-5570-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.1"}

**kubectl version**
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-gke.10", GitCommit:"aaf0906400b5fc1d858ce0566a571e4f3ed06b9f", GitTreeState:"clean", BuildDate:"2019-03-30T19:30:48Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}

**Installation**
{{ Please describe how Istio was installed }}
1. Created a new GKE cluster
2. ko apply -f [istio-crds.yaml](https://github.com/knative/serving/blob/master/third_party/istio-1.1.2/istio-crds.yaml)
3. ko apply -f [istio.yaml](https://github.com/knative/serving/blob/master/third_party/istio-1.1.2/istio.yaml)

**Environment**
GKE

**Cluster state**
{{ If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue. }}
[istio-dump.tar.gz](https://github.com/istio/istio/files/3060813/istio-dump.tar.gz)

**Comment by esnible** [comment]
According to https://github.com/istio/istio/issues/9950 users are expected to delete the ExternalName Service and create something else.  I could not find documentation or examples explaining this.

**Comment by akashrv** [comment]
Just to add more observations. The issue is only with the first named port specified. Example: change the service definition to this one:
kind: Service
apiVersion: v1
metadata:
  name: my-web-server-service
  namespace: istioissue
spec:
  selector:
    app: my-web-server
  ports:
  - name: http
    port: 8888
    protocol: TCP
    targetPort: 8080
  - name: myport
    port: 8081
    protocol: TCP
    targetPort: 8080
  - name: port1234
    port: 1234
    protocol: TCP
    targetPort: 8080
  - name: port80
    port: 80
    protocol: TCP
    targetPort: 8080

Now exec curl from the curl pod:
curl http://es-ws-kne:8888 --> 404
curl http://es-ws-kne:80 --> 200
curl http://es-ws-kne:1234 --> 200
curl http://es-ws-kne:8081 --> 200

**Comment by akashrv** [comment]
> According to #9950 users are expected to delete the ExternalName Service and create something else. I could not find documentation or examples explaining this.

Deleting and re-creating doesn't work. In fact there is no virtual service anywhere. I believe this is a different issue, but I am not an expert.

**Comment by philrud** [comment]
Confirming I'm able to reproduce the issue and renaming the port resolves it. Seeing the following in Pilot logs:
```
    "ProxyStatus": {
        "pilot_conflict_inbound_listener": {
            "my-web-server-7c9d86649-tnf4n.istioissue": {
                "proxy": "my-web-server-7c9d86649-tnf4n.istioissue",
                "message": "Conflicting inbound listener:10.60.2.15:8080. existing: my-web-server-service.istioissue.svc.cluster.local, incoming: my-web-server-service.istioissue.svc.cluster.local"
            }
        },
    ...
}
```

Investigating a potential fix.

**Comment by philrud** [comment]
There was some work done to enable support for using "ExternalName" typed service as an alias for mesh-internal services in this PR: https://github.com/istio/istio/pull/10182. This is why the TCP case works (and changing the port name to anything other than "http" helps).

For the HTTP case the client-side sidecar routes config apparently only has domain name variants for the "real" (destination) service populated ("virtual_hosts/domains") – domain name variants for "ExternalName" aliases aren't there, that's why requests cannot be routed to a proper upstream cluster based on the "Host" header value:

https://github.com/istio/istio/blob/bfea6044ef93511bcdf5b26faf53c0e33a1da4f7/pilot/pkg/networking/core/v1alpha3/httproute.go#L185

We need to generate domains for all aliases along with the destination service domains (working on it).

**Comment by rshriram** [comment]
@philrud the op is accessing the service with the proper service name (es-ws-kne) as it should be accessed. He is not using the actual value of the ExternalName field as the whole point of the external name service is to hide the destination from all end users and instead use a facade. So, your PR linked in the issue will not the issue.

It would be helpful to see the RDS dump for port 80 to see if there are vhost alternatives for es-ws-kne

**Comment by philrud** [comment]
@rshriram yeah, I understand that and that's exactly what I'm testing/fixing. There's no separate RDS vhost for "es-ws-kne" service (it's "meshExtrernal" service with "DNSLB" resolution and no endpoints). The following request `curl -v http://es-ws-kne/` is failing with 404 because it will actually be using "my-web-server-service" vhost. Here's what it's looking like (curl-side sidecar):
```
       {
        "name": "my-web-server-service.istioissue.svc.cluster.local:80",
        "domains": [
         "my-web-server-service.istioissue.svc.cluster.local",
         "my-web-server-service.istioissue.svc.cluster.local:80",
         "my-web-server-service",
         "my-web-server-service:80",
         "my-web-server-service.istioissue.svc.cluster",
         "my-web-server-service.istioissue.svc.cluster:80",
         "my-web-server-service.istioissue.svc",
         "my-web-server-service.istioissue.svc:80",
         "my-web-server-service.istioissue",
         "my-web-server-service.istioissue:80",
         "10.63.241.187",
         "10.63.241.187:80"
        ],
        "routes": [
        ...
```
As there are no host alternatives matching 'es-ws-kne' the request is failing with 404. After the fix from my PR is applied the same vhost looks like this:
```
       {
        "name": "my-web-server-service.istioissue.svc.cluster.local:80",
        "domains": [
         "my-web-server-service.istioissue.svc.cluster.local",
         "my-web-server-service.istioissue.svc.cluster.local:80",
         "my-web-server-service",
         "my-web-server-service:80",
         "my-web-server-service.istioissue.svc.cluster",
         "my-web-server-service.istioissue.svc.cluster:80",
         "my-web-server-service.istioissue.svc",
         "my-web-server-service.istioissue.svc:80",
         "my-web-server-service.istioissue",
         "my-web-server-service.istioissue:80",
         "es-ws-kne",
         "es-ws-kne:80",
         "es-ws-kne.istioissue.svc.cluster",
         "es-ws-kne.istioissue.svc.cluster:80",
         "es-ws-kne.istioissue.svc",
         "es-ws-kne.istioissue.svc:80",
         "es-ws-kne.istioissue",
         "es-ws-kne.istioissue:80",
         "10.63.241.187",
         "10.63.241.187:80"
        ],
        "routes": [
        ...
```
Now the same request `curl -v http://es-ws-kne/` succeeds and returns 200 OK. I have tested with and without my PR applied and it does resolve the issue.

Thanks for the review btw!

**Comment by rshriram** [comment]
There is no RDS for es-ws-kne because that service does not have a port. So, in RDS calls, when Pilot tries to determine the set of hosts on port 80, it does not have es-ws-kne in the list.

 This k8s external name service is a royal pain. I would hate its eccentricities to become part of the main networking code.

@akashrv you are missing a virtual service definition for the external name service. Since the service doesn't have a port, there is no way Pilot can automagically setup virtual hosts for this service. Declare a virtual service as follows:

```
hosts:
- es-ws-kne.blah.svc.cluster.local
- es-ws-kne.blah
http:
- route:
   - destination:
           host: my-web-server-service.istioissue.svc.cluster.local
           port: 80
```

This will create the appropriate virtual hosts in Envoy that allows you to route to the destination as intended.

Looking at your original PR in knative,
```Removed Istio virtual service dependency from in-memory channel``` is the reason the routing broke. If you had the virtual service in place, then traffic would have been properly redirected to the right service.

This was the way we had designed support for External name services starting 1.0.

**Comment by philrud** [comment]
Well I'm looking https://github.com/istio/istio/pull/9975 this is clearly an afterthought and user experience isn't looking great atm: now the TCP case works, renaming port "fixes" the issue, while for the most basic case we require a VirtualService, etc.

**Comment by akashrv** [comment]
> ooking at your original PR in knativ

Necessitating the use of a virtual service doesn't to use ExternalName service doesn't seem like the right way. Here is my exact use case in Knative which will explain why.
 - Knative exposes and Addressable resource to end users. An Addressable resource is defines as something that has a URL specified on it that can be reached by end users. The exact infra that handles the requests to this URL is abstracted behind this Addressable resource. Example a Channel in Knative eventing.
- We have a use case where users can create multiple Channels but the infra could be common say a service hosted in knative-eventing namespace. To route the requests coming to individual user channel objects to this common infra we use an ExternalName service. Which internally in K8s is just a CNAME lookup and DNS resolution. This way the infra doesn't have to create any ISTIO resources as we do not want to enforce ISTIO dependency on our end users.
- Now, the client say some user pod that calls this Channel may or may not have ISTIO sidecar as this is not in our control. If it doesn't have a sidecar that it works fine because K8s supports this natively.
- If the client pod has a ISTIO sidecar then, it wont work. And end users will be stuck because they do not control the Knative infra.
- Moreover, if Knative creates an ISTIO virtual service, then we enforce the client pods to always have istio sidecar, without which requests won't be routed correctly.
- As a platform on K8s, we don't want to enforce the usage or non-usage of ISTIO.

Makes sense? Please let me know if I am missing anything.

**Comment by akashrv** [comment]
> There is no RDS for es-ws-kne because that service does not have a port. So, in RDS calls, when Pilot tries to determine the set of hosts on port 80, it does not have es-ws-kne in the list.
> 
> This k8s external name service is a royal pain. I would hate its eccentricities to become part of the main networking code.
> 
> @akashrv you are missing a virtual service definition for the external name service. Since the service doesn't have a port, there is no way Pilot can automagically setup virtual hosts for this service. Declare a virtual service as follows:
> 
> ```
> hosts:
> - es-ws-kne.blah.svc.cluster.local
> - es-ws-kne.blah
> http:
> - route:
>    - destination:
>            host: my-web-server-service.istioissue.svc.cluster.local
>            port: 80
> ```
> This will create the appropriate virtual hosts in Envoy that allows you to route to the destination as intended.
> 
> Looking at your original PR in knative,
> `Removed Istio virtual service dependency from in-memory channel` is the reason the routing broke. If you had the virtual service in place, then traffic would have been properly redirected to the right service.
> 
> This was the way we had designed support for External name services starting 1.0.

Necessitating the use of a virtual service doesn't to use ExternalName service doesn't seem like the right way. Here is my exact use case in Knative which will explain why.

Knative exposes and Addressable resource to end users. An Addressable resource is defines as something that has a URL specified on it that can be reached by end users. The exact infra that handles the requests to this URL is abstracted behind this Addressable resource. Example a Channel in Knative eventing.
We have a use case where users can create multiple Channels but the infra could be common say a service hosted in knative-eventing namespace. To route the requests coming to individual user channel objects to this common infra we use an ExternalName service. Which internally in K8s is just a CNAME lookup and DNS resolution. This way the infra doesn't have to create any ISTIO resources as we do not want to enforce ISTIO dependency on our end users.
Now, the client say some user pod that calls this Channel may or may not have ISTIO sidecar as this is not in our control. If it doesn't have a sidecar that it works fine because K8s supports this natively.
If the client pod has a ISTIO sidecar then, it wont work. And end users will be stuck because they do not control the Knative infra.
Moreover, if Knative creates an ISTIO virtual service, then we enforce the client pods to always have istio sidecar, without which requests won't be routed correctly.
As a platform on K8s, we don't want to enforce the usage or non-usage of ISTIO.

@rshriram Makes sense? Please let me know if I am missing anything.

**Comment by rshriram** [comment]
@philrud I dont mind undoing #9975 but this whole alias is definitely not the solution as it leaks k8s specific strange external name semantics all over the networking code. Your solution is to fix the k8s service registry code such that if you see an external name service thats backed by an actual k8s service, you copy the ports, and other details from the backing service and create a proper model.Service object with ports, host (pointing to service name of the external name service, not the backing object), etc.

Ofcouse, this goes without saying that the moment you refer to a non-k8s service in the external name service, all bets are off and we cant do anything about it in Istio as we have no idea about the ports/protocols involved with the external service.

**Comment by akashrv** [comment]
Any updates on this one? @rshriram, @philrud Does the explanation I gave above makes sense? Please let me know if you need any more info.

**Comment by philrud** [comment]
@rshriram of course primary reason behind my PR is an attempt to address the issue in the least intrusive way for a minor release. Not sure if we can justify a bigger refactoring considering "Code Mauve" effort. @costinm, thoughts?

I can look into creating a "real" Service for each alias, but the benefits of this approach aren't clear to me. This is merely a DNS alias, why don't we want to handle it as such (more consistent metrics, less overhead, etc.)? There's nothing inherently K8s-specific about a basic DNS-alias – that's why I went with more generic naming, I can see how other service discovery backends may feature a similar concept. It doesn't leak more than has already leaked.

No strong opinion on that though. I'm sure there are many nuances and things I'm not aware of, I'm not a fan of either approach, so would go with whatever you recommend, gentlemen.

**Comment by rshriram** [comment]
least intrusive does not mean breaking platform abstraction boundaries.
Also, @akashrv I think your main problem is that your external services have no ports. Once you add the ports to the external service, things should work properly.

**Comment by akashrv** [comment]
@rshriram Could you elaborate what you mean by ports for an external service? From [K8s documentation](https://kubernetes.io/docs/concepts/services-networking/service/#externalname) it seems that ExternalName services have an external name for which a CNAME record is created with the DNS.

**Comment by philrud** [comment]
@akashrv you're absolutely correct, ports on ExternalName-typed service don't make any sense from Kubernetes perspective. However due to the PR that I previously mentioned (https://github.com/istio/istio/pull/9975) Istio actually respects them to some degree.

**Comment by brunooliveiramac** [comment]
We are facing same issue here. Should we follow a different approach,maybe using a ServiceEntry instead.
