### ISSUE TITLE
Sidecar object with  `defaultEndpoint: unix:///..` doesn't work.

### ISSUE THREAD

**Issue by fleeto** [istio/istio#13204]
**Describe the bug**

Sidecar object with  `defaultEndpoint: unix:///..`in ingress doesn't work.

**Expected behavior**

I can access the service with the `http://nginx:80`  in other pods. 

**Steps to reproduce the bug**

[workload-sidecar.tar.gz](https://github.com/istio/istio/files/3063789/workload-sidecar.tar.gz)

1. Deploy a workload of nginx, listening to `unix:///tmp/backend.socket`
1. Create a `Sidecar` object, set its `IstioIngressListener` as:
  ~~~yaml
  - port:
      number: 80
      protocol: HTTP
      name: nginx
    defaultEndpoint: unix:///tmp/backend.socket
  ~~~
1. Access nginx from other pods:
  ~~~command
  $ kubectl exec -it -c sleep sleep-85887ff9c-skj25 -- http  http://nginx
  HTTP/1.1 503 Service Unavailable
  upstream connect error or disconnect/reset before headers
  ~~~
1. Check proxy status with `istioctl pc endpoints`:
  ~~~command
  $ istioctl pc endpoints nginx-56d86f6985-lbd2b
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x2286719]

goroutine 1 [running]:
istio.io/istio/istioctl/pkg/writer/envoy/clusters.retrieveEndpointAddress(...)
        /workspace/go/src/istio.io/istio/istioctl/pkg/writer/envoy/clusters/clusters.go:67
istio.io/istio/istioctl/pkg/writer/envoy/clusters.(*ConfigWriter).PrintEndpointsSummary(0xc4201b1460, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc420209ca0)
        /workspace/go/src/istio.io/istio/istioctl/pkg/writer/envoy/clusters/clusters.go:111 +0x1e9
main.glob..func13(0x33711e0, 0xc4204e0290, 0x1, 0x1, 0x0, 0x0)
        /workspace/go/src/istio.io/istio/istioctl/cmd/istioctl/proxyconfig.go:218 +0x2b1
istio.io/istio/vendor/github.com/spf13/cobra.(*Command).execute(0x33711e0, 0xc4204e0250, 0x1, 0x1, 0x33711e0, 0xc4204e0250)
        /workspace/go/src/istio.io/istio/vendor/github.com/spf13/cobra/command.go:756 +0x468
istio.io/istio/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x336fee0, 0xc420387f78, 0xc420387f78, 0x1003abc)
        /workspace/go/src/istio.io/istio/vendor/github.com/spf13/cobra/command.go:846 +0x30a
istio.io/istio/vendor/github.com/spf13/cobra.(*Command).Execute(0x336fee0, 0x20, 0x0)
        /workspace/go/src/istio.io/istio/vendor/github.com/spf13/cobra/command.go:794 +0x2b
  ~~~
**Version**

~~~command
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-26T00:04:52Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.5", GitCommit:"51dd616cdd25d6ee22c83a858773b607328a18ec", GitTreeState:"clean", BuildDate:"2019-01-16T18:14:49Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}
$ istioctl version --remote
client version: version.BuildInfo{Version:"1.1.2", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989", User:"root", Host:"35adf5bb-5570-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.1"}
citadel version: version.BuildInfo{Version:"1.1.2", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"35adf5bb-5570-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.1"}
egressgateway version: version.BuildInfo{Version:"bdda7cfcf5ba1397e6e0e2629d53114c9ea8fc14", GitRevision:"bdda7cfcf5ba1397e6e0e2629d53114c9ea8fc14", User:"mjog", Host:"devinstance.c.mixologist-142215.internal", GolangVersion:"go1.10.1", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-snapshot.4-592-gbdda7cf"}
galley version: version.BuildInfo{Version:"1.1.2", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"35adf5bb-5570-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.1"}
ingressgateway version: version.BuildInfo{Version:"bdda7cfcf5ba1397e6e0e2629d53114c9ea8fc14", GitRevision:"bdda7cfcf5ba1397e6e0e2629d53114c9ea8fc14", User:"mjog", Host:"devinstance.c.mixologist-142215.internal", GolangVersion:"go1.10.1", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-snapshot.4-592-gbdda7cf"}
pilot version: version.BuildInfo{Version:"1.1.2", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"35adf5bb-5570-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.1"}
policy version: version.BuildInfo{Version:"1.1.2", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"35adf5bb-5570-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.1"}
sidecar-injector version: version.BuildInfo{Version:"1.1.2", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"35adf5bb-5570-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.1"}
telemetry version: version.BuildInfo{Version:"1.1.2", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"35adf5bb-5570-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.1"}
~~~

**Installation**

~~~command
helm template install/kubernetes/helm/istio --name istio --namespace istio-system \           master
    --values install/kubernetes/helm/istio/values-istio-demo.yaml | kubectl apply -f -
~~~

**Environment**

OS X

**Cluster state**

**Comment by rshriram** [comment]
You have to mount the socket in the istio proxy. Otherwise it can’t see your Unix domain socket in the Nginx container. This is a k8s restriction.

**Comment by fleeto** [comment]
@rshriram thank you, I'd mounted socket files into `istio-proxy`, and I can run `curl --unix-socket /nginx/socket/backend.socket http://local/` to get pages from nginx on the `istio-proxy` container of nginx pod.

~~~command
$ istioctl pc endpoints sleep-6c5667f85f-486kz  | grep -v istio
ENDPOINT                STATUS      CLUSTER
10.244.0.28:53          HEALTHY     outbound|53||kube-dns.kube-system.svc.cluster.local
10.244.1.125:80         HEALTHY     outbound|80||sleep.default.svc.cluster.local
10.244.1.2:80           HEALTHY     outbound|80||nginx.default.svc.cluster.local
....
~~~

But in another pod:

~~~command
$ kubectl exec -it nginx-79569f8cb6-lhlhp -c istio-proxy sh
# curl http://nginx
upstream connect error or disconnect/reset before headers. reset reason: connection failure
~~~

Then I was trying to get access logs from telemetry:

~~~json
{
    "level": "info",
    "time": "2019-04-24T16:07:42.235422Z",
    "instance": "accesslog.logentry.istio-system",
    "apiClaims": "",
    "apiKey": "",
    "clientTraceId": "",
    "connection_security_policy": "none",
    "destinationApp": "nginx",
    "destinationIp": "10.244.1.2",
    "destinationName": "nginx-79569f8cb6-lhlhp",
    "destinationNamespace": "default",
    "destinationOwner": "kubernetes://apis/apps/v1/namespaces/default/deployments/nginx",
    "destinationPrincipal": "",
    "destinationServiceHost": "nginx.default.svc.cluster.local",
    "destinationWorkload": "nginx",
    "grpcMessage": "",
    "grpcStatus": "",
    "httpAuthority": "nginx",
    "latency": "214.748µs",
    "method": "GET",
    "permissiveResponseCode": "none",
    "permissiveResponsePolicyID": "none",
    "protocol": "http",
    "receivedBytes": 603,
    "referer": "",
    "reporter": "destination",
    "requestId": "0483a466-4750-9c00-b4d0-e8832baf21fc",
    "requestSize": 0,
    "requestedServerName": "",
    "responseCode": 503,
    "responseFlags": "UF",
    "responseSize": 91,
    "responseTimestamp": "2019-04-24T16:07:42.235548Z",
    "sentBytes": 189,
    "sourceApp": "sleep",
    "sourceIp": "10.244.1.125",
    "sourceName": "sleep-6c5667f85f-486kz",
    "sourceNamespace": "default",
    "sourceOwner": "kubernetes://apis/apps/v1/namespaces/default/deployments/sleep",
    "sourcePrincipal": "",
    "sourceWorkload": "sleep",
    "url": "/",
    "userAgent": "curl/7.61.1",
    "xForwardedFor": "0.0.0.0"
}
~~~

~~~json
{
    "level": "info",
    "time": "2019-04-24T16:07:42.222046Z",
    "instance": "accesslog.logentry.istio-system",
    "apiClaims": "",
    "apiKey": "",
    "clientTraceId": "",
    "connection_security_policy": "unknown",
    "destinationApp": "nginx",
    "destinationIp": "10.244.1.2",
    "destinationName": "nginx-79569f8cb6-lhlhp",
    "destinationNamespace": "default",
    "destinationOwner": "kubernetes://apis/apps/v1/namespaces/default/deployments/nginx",
    "destinationPrincipal": "",
    "destinationServiceHost": "nginx.default.svc.cluster.local",
    "destinationWorkload": "nginx",
    "grpcMessage": "",
    "grpcStatus": "",
    "httpAuthority": "nginx",
    "latency": "50.88791ms",
    "method": "GET",
    "permissiveResponseCode": "none",
    "permissiveResponsePolicyID": "none",
    "protocol": "http",
    "receivedBytes": 193,
    "referer": "",
    "reporter": "source",
    "requestId": "0483a466-4750-9c00-b4d0-e8832baf21fc",
    "requestSize": 0,
    "requestedServerName": "",
    "responseCode": 503,
    "responseFlags": "URX",
    "responseSize": 91,
    "responseTimestamp": "2019-04-24T16:07:42.272823Z",
    "sentBytes": 214,
    "sourceApp": "sleep",
    "sourceIp": "10.244.1.125",
    "sourceName": "sleep-6c5667f85f-486kz",
    "sourceNamespace": "default",
    "sourceOwner": "kubernetes://apis/apps/v1/namespaces/default/deployments/sleep",
    "sourcePrincipal": "",
    "sourceWorkload": "sleep",
    "url": "/",
    "userAgent": "curl/7.61.1",
    "xForwardedFor": "0.0.0.0"
}
~~~

Any suggestions? thanks again.

**Comment by sterchelen** [comment]
@fleeto How did you mount the socket ?

**Comment by sterchelen** [comment]
@rshriram I have the same problem here.

I have a containerPort on 40000 named 'http' with the TCP protocol.

Here is my Sidecar object:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: my-app
  namespace: stage
spec:
  workloadSelector:
    labels:
      app: my-app
  ingress:
  - port:
      number: 40000
      protocol: HTTP
      name: http
    defaultEndpoint: unix:///var/run/myapp/http.sock
  egress:
  - hosts:
    - "istio-system/*"
```

Like @fleeto, if I connect inside the istio-proxy container and using `curl --unix-socket /var/run/myapp/http.sock http://test/demo` it works.
Additional info, my socket has the same uid , guid as istio-proxy.
Outside the container I have the following error :  `upstream connect error or disconnect/reset before headers. reset reason: connection failure`

Last thing, mounting the socket unix from my app to the istio-proxy container was not a peace of cake ! It is not documented. I used the following annotation in my Deployment object `sidecar.istio.io/userVolumeMount: '{"unix-socket":{"mountPath":"/var/run/myapp"}}'`

Any ideas ?

**Comment by jaygorrell** [comment]
> You have to mount the socket in the istio proxy. Otherwise it can’t see your Unix domain socket in the Nginx container. This is a k8s restriction.

What socket is getting mounted here? The examples refer to "/var/run/myapp", but I'm still unclear what that should be in a real example.

**Comment by rshriram** [comment]
Does this help: https://github.com/istio/istio/blob/master/tests/e2e/tests/pilot/testdata/app.yaml.tmpl ? see how the socket is mounted using the annotation..
I am sorry that this is not well documented. We will try to fix it soon.

**Comment by jaygorrell** [comment]
It does help a bit but I'm a little unclear about what socket needs mounted for this purpose. Are we mounting from the app container to the proxy container? From the host to the proxy?

I know a lot of systems (ie. DataDog) mount the Docker socket from the host but in this case, is there a pod-specific socket that should be mounted so traffic can be sent to it?

**Comment by rshriram** [comment]
This is socket exposed by the application process, in the app container. The socket is from the app container to the proxy container. The annotation tells the sidecar injector to mount that same socket into the sidecar container.

The expectation here is that your application has a volume mount, with a unix domain socket on that volume mount. You then expose that volume mount to the istio-proxy as well, following which you can use the Sidecar to setup access to that thing.

**Comment by jaygorrell** [comment]
Ah, now that helps! Thank you... I should be able to figure it out from there. Linked issue above should capture the documentation side of this, too.

Is there any reason this is handled by `Sidecar` and not a `DestinationRule`? Also are there any downsides to routing traffic this way? Using sockets seems to resolve some concurrency issues we were experiencing in Node services.

**Comment by sterchelen** [comment]
@rshriram Did you saw my message on this topic ? https://github.com/istio/istio/issues/13204#issuecomment-489995457

**Comment by rshriram** [comment]
@jaygorrell the unix domain socket in the `Sidecar` is meant for inbound connections. DestinationRule applies on the outbound, at the client side. In terms of downsides, I dont have much data. We introduced the unix domain socket based inbound routing as an alternative to traffic capture using iptables. Some folks asked for it.

**Comment by rshriram** [comment]
@sterchelen hmm.. is `40000` exposed on the pod ? Secondly, how were you connecting to the pod? via podIP and the port? It would be good to get the proxy config and look at the listeners in envoy

**Comment by jaygorrell** [comment]
Thanks for the help @rshriram -- I've got the socket mounted and am able to use it from the envoy container. Is port information in the deployment/service ignored in this configuration?

Happy to help get this documented when I have it all working.

**Comment by jaygorrell** [comment]
Here's where I'm at right now:
```
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: my-service-tmp
spec:
  workloadSelector:
    labels:
      app: my-service-tmp
  ingress:
    - bind: 127.0.0.1
      port:
        number: 8080
        protocol: HTTP
        name: somename
      defaultEndpoint: unix:///var/run/app/http.sock
  egress:
    - hosts:
        - "*/*"
```

I have a service on `80` that has a `targetPort` of 8080. I confirmed that curling with `--unix-socket` on the istio-proxy container and the above socket, I'm able to reach the service. However, going through the k8s service dns/ip, I get a 504 using this configuration (with or without the Sidecar).

**Comment by fleeto** [comment]
I don't know if my suggestion is right or not. 

Here is what I'm thinking of:

Client Service->Envoy proxy of the Server->Shared uds file->Server.
It means that: http->envoy->uds.

And I'd tried in these steps:

1. Create an nginx deployment (nginx.yaml) as the workload.
   - There is an EmptyDir volume for the `nginx.sock`, mounted as `/nginx-run/`
   - Nginx inside the workload container is listening on UDS file: `/nginx-run/nginx.sock`
1. Build the istio workload with the command `istio kube-inject -f nginx.yaml -o injected.yaml`
1. Mount the `nginx-run` volume mentioned above in `istio-proxy` container in the injected file.
1. **Remove the init-container**
1. Create a sidecar object, with `defaultEndpoint: unix:///`
1. Then I should access the nginx service in another service in the mesh.

**Comment by jaygorrell** [comment]
>4. Remove the init-container

Since you bolded this, and it's not a step I currently do, I'm guessing this was the key. I'm not sure if there's an annotation or anything to prevent the initContainer on an auto-inject setup though -- but also not sure if that's the _right_ approach here. Do you know why this worked?

**Comment by fleeto** [comment]
Just a suggestion. I'd tried and failed.

**Comment by rshriram** [comment]
Hi, please see  #16298 . this should hopefully be available in a release daily. It would be good if you could test the unix domain socket issue.
