### ISSUE TITLE
Helm values in daily builds are incorrect  

### ISSUE THREAD

**Issue by utka** [istio/istio#13212]
**Describe the bug**
Incorrect tag and hub under charts/values.yaml for daily and RC builds 

**Expected behavior**
Look under https://gcsweb.istio.io/gcs/istio-prerelease/daily-build/master-20190410-09-16/charts/
the value for tag should be master-20190410-09-16 instead of *-latest-daily, as well as hub is incorrect.

**Version**
Does not work for master and release-1.1

**Installation**
N/a

**Environment**
Build and release.

**Cluster state**
N/a

**Comment by howardjohn** [comment]
Tested istio-master-20190618-09-15 and I think this is fixed

```
rg tag:
istio-master-20190618-09-15/install/kubernetes/helm/istio-cni/values.yaml
2:tag: master-20190618-09-15

istio-master-20190618-09-15/install/kubernetes/helm/istio-cni/values_gke.yaml
2:tag: master-latest-daily

istio-master-20190618-09-15/install/kubernetes/helm/istio/values.yaml
113:  tag: master-20190618-09-15

istio-master-20190618-09-15/install/kubernetes/helm/istio-init/values.yaml
8:  tag: master-20190618-09-15
```

Note the values_gke one is still wrong though, will fix in another one.

I think this is fixed, if not please reopen @utka
