### ISSUE TITLE
docker.kubectl target is broken on MacOS

### ISSUE THREAD

**Issue by tvieira** [istio/istio#13219]
**Describe the bug**
Running `GOOS=linux make docker` fails while building kubectl container image, with the following error:
```
time (mkdir -p /Users/tmoreira/Projects/go/out/linux_amd64/release/docker_build/docker.kubectl && cp -r docker/Dockerfile.kubectl /Users/tmoreira/Projects/go/bin/kubectl /Users/tmoreira/Projects/go/out/linux_amd64/release/docker_build/docker.kubectl && cd /Users/tmoreira/Projects/go/out/linux_amd64/release/docker_build/docker.kubectl &&  docker build  -t kind/kubectl:e2e -f Dockerfile.kubectl .)
cp: cannot stat '/Users/tmoreira/Projects/go/bin/kubectl': No such file or directory

real	0m0.009s
user	0m0.003s
sys	0m0.003s
make: *** [docker.kubectl] Error 1
```

**Expected behavior**
`docker.kubectl` is within the DOCKER_TARGETS, I should be able to have the container image built successfully.

**Steps to reproduce the bug**

1. build docker images:
`GOOS=linux make docker HUB=kind TAG=e2e`

**Version**
n/a

**Installation**
n/a

**Environment**
MacOS 10.14.4 / istio master branch

**Cluster state**
n/a

**Comment by esnible** [comment]
I did `GOOS=linux make docker` using OSX 10.13.6 and `master`.  It was able to build without problems.

`ls -l $GOPATH/out/linux_amd64/release/docker_build/docker.kubectl/kubectl` shows _kubectl_ was built today.

Can anyone else try this and reproduce either my success or @tvieira 's failure?

**Comment by tvieira** [comment]
Thanks @esnible ! Where does your kubectl live? Do you have it in your $GOPATH/bin folder?

**Comment by sdake** [comment]
@tvieira did you set $ISTIO in your environmeent variable?

Here is what my profile sort of looks like (note I haven't attempted to reproduce your issue)

```
export GOPATH=~/go
export PATH=$PATH:/usr/local/go/bin:/usr/local/kubebuilder_1.0.8_linux_amd64/bin:$GOPATH/bin
export ISTIO=$GOPATH/src/istio.io # eg. ~/go/src/istio.io

# Please change HUB to the desired HUB for custom docker container
# builds.
export HUB="docker.io/$USER"

# The Istio Docker build system will build images with a tag composed of
# $USER and timestamp. The codebase doesn't consistently use the same timestamp
# tag. To simplify development the development process when later using
# updateVersion.sh you may find it helpful to set TAG to something consistent
# such as $USER.
export TAG=$USER

# If your github username is not the same as your local user name (saved in the
# shell variable $USER), then replace "$USER" below with your github username
export GITHUB_USER=$USER

# Specify which Kube config you'll use for testing. This depends on whether
# you're using Minikube or your own Kubernetes cluster for local testing
# For a GKE cluster:
export KUBECONFIG=${HOME}/.kube/config

# set PATH so it includes user's private bin directories
PATH="$HOME/bin:$HOME/.local/bin:$PATH"
```

**Comment by esnible** [comment]
I have no $ISTIO.

I have $GOPATH/bin/kubectl.

`GOOS=linux make docker` put a 1.11 version into the Docker image.

I was mistaken about _$GOPATH/out/linux_amd64/release/docker_build/docker.kubectl/kubectl_.  It was built today, but it is not the same size or version as the _kubectl_ in the Docker image that was built around the same time.

**Comment by tvieira** [comment]
> I have $GOPATH/bin/kubectl.

Right, that's why your build is successful. I install kubectl via brew, therefore it is located somewhere else. 

@sdake - I have set the `ISTIO` variable. The main problem is that this specific target depends on https://github.com/istio/istio/blob/master/bin/testEnvLocalK8S.sh to get dependencies (`getDeps` call) - see: 

https://github.com/istio/istio/blob/1c0fbe3ff59f05a685bfa21b4cdc567ab11534dc/tools/istio-docker.mk#L73

But once it hits this:

https://github.com/istio/istio/blob/1c0fbe3ff59f05a685bfa21b4cdc567ab11534dc/bin/testEnvLocalK8S.sh#L30

`getDeps` never runs and therefore I never get the `kubectl` where the target expects it to be.

Correct me if I'm wrong, but this is where the problem is.

**Comment by ericvn** [comment]
I don't have any issues building on my Mac either, although I usually run more `makefile` targets.

I'm a little confused and this wouldn't use any kubectl version that it finds locally (it would be a MacOS version)..

Looking at the Makefile, I don't know why we try to copy the `kubectl` is going a `ADD https://storage.googleapis.com/kubernetes-release/release/v1.11.1/bin/linux/amd64/kubectl /usr/bin/kubectl`

**Comment by ericvn** [comment]
PR submitted.

**Comment by sdake** [comment]
@tvieira thanks for the debug analysis.

Thanks @ericvn for the PR.

Is any further work here required?

**Comment by tvieira** [comment]
@sdake all good! The #13256 fixed it.
