### ISSUE TITLE
All CircleCI tests failing

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#13216]
Seems like all CircleCI tests are failing with:

"There was an issue while running this container and it was rerun. The most recent run is shown."

examples: 

https://circleci.com/gh/istio/istio/382055?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
https://circleci.com/gh/istio/istio/382057?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Probably an issue on Circle's side..

**Comment by Radau** [comment]
CircleCI is having a bit of an outage it looks like, we've been affected by it since around 10:30AM (Docker builds). They recently updated the [status page](https://status.circleci.com/) to reflect the issue.

**Comment by kyessenov** [comment]
We should probably asses reliability of circle CI in the context of this project. It feels like there's a problem with it every couple of weeks. Just last Friday they had tens-of-minutes of delays starting jobs.

 cc @utka

**Comment by ozevren** [comment]
Any objections to closing this? I assume the outage is complete at this point?

We have a separate issue for investigation of using another build/CI system: https://github.com/istio/istio/issues/13428
