### ISSUE TITLE
Proxy: Enable configurable client cert paths for pilot + metrics service connections

### ISSUE THREAD

**Issue by drichelson** [istio/istio#13221]
**Describe the feature request**
Enable configurable client cert paths for pilot + metrics service connections. The same  client certs used by https://github.com/istio/istio/issues/11984 will be used for pilot + metrics service connections.

**Describe alternatives you've considered**
Modifying mount paths for K8s services works fine with the current hardcoded paths. For our (Salesforce) use case we also run baremetal services where we don't have control over cert paths. For this use case there is no alternative

**Additional context**
Related: https://github.com/istio/istio/issues/11984

**Comment by howardjohn** [comment]
I think ive seen some PRs for this, can you close this if they are done (and link the PRs for tracking purposes if possible)?

**Comment by shakti-das** [comment]
It's partly done, the bootstrap config changes related to ControlPlaneAuthPolicy flag and TLS metrics service are still pending.
