### ISSUE TITLE
Locality LB Integration test failures

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#13227]
Example: https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/13225/istio-integ-k8s-tests/6562

**Comment by liamawhite** [comment]
which images do these use @howardjohn?

**Comment by howardjohn** [comment]
Another example: https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/13237/istio-integ-k8s-tests/6597

For all prow failures you can look at build log

```
+ HUB=gcr.io/istio-testing
+ export TAG=9931f66aff641ef5a77459038c50e571a17ecb60
```

Another issue: it logs ~20k lines when it fails. Can we just make one error message? We probably don't need that many requests total either

**Comment by liamawhite** [comment]
Will be resolved by https://github.com/istio/istio/pull/13207.

I'll fix up the spammy nature in my PR adding tests for failover.

**Comment by liamawhite** [comment]
Will leave this open until we confirm that the release-1.1 merge into master fixes the issue.

**Comment by howardjohn** [comment]
Fixed
