### ISSUE TITLE
Timeout error when re running egress rules post upgrade of istio 1.0.6 to 1.0.7

### ISSUE THREAD

**Issue by pc-rshetty** [istio/istio#13230]
**Describe the bug**
We get Timeout errors when re running  egress rules (a yaml file with bunch of egress) after upgrading . This started happening after we upgraded from 1.0.5 to 1.0.6 and also when we upgraded from 1.0.6 to 1.0.7. We have to keep running and eventually it succeeds

we get this error on running kubectl apply -f egress-control.yml  

`STDERR:

Error from server (Timeout): error when applying patch:
{"metadata":{"annotations":{}}}
to:
&{0xc42009b980 0xc4204ef570 default aws-metadata /Users/myuser/code/myorg/myrepo/config/istio/egress-control.yml 0xc42000c008 47543 false}
for: "/Users/myuser/code/myorg/myrepo/config/istio/egress-control.yml": Timeout: request did not complete within allowed duration
Error from server (Timeout): error when applying patch:
{"metadata":{"annotations":{}}}
to:
&{0xc4208ba180 0xc420481420 default s3-us-west-2 /Users/myuser/code/myorg/myrepo/config/istio/egress-control.yml 0xc420e525f8 47544 false}
for: "/Users/myuser/code/myorg/myrepo/config/istio/egress-control.yml": Timeout: request did not complete within allowed duration
Error from server (Timeout): error when applying patch:
{"metadata":{"annotations":{}}}
to:
&{0xc4208ba240 0xc42044aa80 default s3-us-west-2 /Users/myuser/code/myorg/myrepo/config/istio/egress-control.yml 0xc420e52690 47545 false}
for: "/Users/myuser/code/myorg/myrepo/config/istio/egress-control.yml": Timeout: request did not complete within allowed duration
Error from server (Timeout): error when applying patch:
{"metadata":{"annotations":{}}}
to:
&{0xc42009bbc0 0xc42034dea0 default ssm.us-west-2.amazonaws.com /Users/myuser/code/myorg/myrepo/config/istio/egress-control.yml 0xc42000c728 47548 false}
for: "/Users/myuser/code/myorg/myrepo/config/istio/egress-control.yml": Timeout: request did not complete within allowed duration
Error from server (Timeout): error when applying patch:
{"metadata":{"annotations":{}}}
to:
&{0xc4209500c0 0xc42012a0e0 default ssm.us-west-2.amazonaws.com /Users/myuser/code/myorg/myrepo/config/istio/egress-control.yml 0xc420e52000 47551 false}
for: "/Users/myuser/code/myorg/myrepo/config/istio/egress-control.yml": Timeout: request did not complete within allowed duration
Error from server (Timeout): error when applying patch:
{"metadata":{"annotations":{}}}
to:
&{0xc42009af00 0xc420327650 default kms.us-west-2.amazonaws.com /Users/myuser/code/myorg/myrepo/config/istio/egress-control.yml 0xc420e52138 531653 false}
for: "/Users/myuser/code/myorg/myrepo/config/istio/egress-control.yml": Timeout: request did not complete within allowed duration
Error from server (Timeout): error when applying patch:
{"metadata":{"annotations":{}}}
to:
&{0xc420950180 0xc4204ef9d0 default kms.us-west-2.amazonaws.com /Users/myuser/code/myorg/myrepo/config/istio/egress-control.yml 0xc4200a2228 531654 false}
for: "/Users/myuser/code/myorg/myrepo/config/istio/egress-control.yml": Timeout: request did not complete within allowed duration
Error from server (Timeout): error when applying patch:
{"metadata":{"annotations":{}}}
`

**On the kube api server log we see** 

`W0410 17:11:30.716840 1 dispatcher.go:71] Failed calling webhook, failing closed pilot.validation.istio.io: failed calling admission webhook "pilot.validation.istio.io": Post https://istio-galley.istio-system.svc:443/admitpilot?timeout=30s: net/http: request canceled (Client.Timeout exceeded while awaiting headers)`

**Expected behavior**
#run following with many egress serviceentries and virtualservice entries and it should suceed
kubectl apply -f egress-control.yml 

**Steps to reproduce the bug**
this happens once we upgrade with helm and soon try re running the egress rules

**Version**
istio 1.0.6 as well as istio 1.0.7 had same issues
this is on k8s 1.11 on eks

**Installation**
Using helm

**Environment**
EKS on AWS

**Cluster state**
{{ If you're running on Kubernetes, consider [following the
instructions](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
to generate "istio-dump.tar.gz", then attach it here by dragging and dropping
the file onto this issue. }}

**Comment by sdake** [comment]
EKS has performance problems in general from my experience with the platform.  Is this issue reproducible if you deploy on AWS EC2?

Cheers
-steve

**Comment by pc-rshetty** [comment]
thanks @sdake testing on non EKS environment is a bigger effort. If we know what is wrong we can escalate. Right now i see istio errors hence posted the issue in istio

**Comment by howardjohn** [comment]
Are you still seeing this on newer Istio versions? Sorry we didnt get this resolve in the 1.0 timeframe, but many things have changed.

if you do still see this on new versions please open a new issue and provide logs/info about the galley deployment
