### ISSUE TITLE
Bookinfo CSS broken in master

### ISSUE THREAD

**Issue by esnible** [istio/istio#13244]
Caused by https://github.com/istio/istio/commit/e9a94e4b4d5f44942d92d249d1647fa079c43815#diff-84a607622f5980c681c4c6ce0fe61c7d

The new ProductPage image serves .css files from /static instead of the https://ajax.googleapis.com/ location used in earlier Istio versions.

The _samples/bookinfo/networking/bookinfo-gateway.yaml_ does not include `/static` in the prefixes exposed.

Either the ProductPage must stop offering /static URLs or the gateway VirtualService must expose them.

cc @venilnoronha @yubingjiaocn

**Comment by rvennam** [comment]
This is related to #13153 

Bootstrap css, js and fonts assets needs to be served and allowed from the VirtualService.
