### ISSUE TITLE
make generate_e2e_yaml alternating bug 

### ISSUE THREAD

**Issue by pitlv2109** [istio/istio#13257]
**Describe the bug**
In the `master` branch, the `--grpc-hostname` flag has been removed for Citadel. When running `make generate_e2e_yaml`, the `--grpc-hostname` are generated alternating-ly in Citadel deployment config. 

**Expected behavior**
`--grpc-hostname` should not be generated for Citadel deployment config. 

**Steps to reproduce the bug**
1. Run `make generate_e2e_yaml`, open `install/kubernetes/istio-auth.yaml`, check if `--grpc-hostname` is there (under Citadel deployment).
2. If not, perform step 1 again. `--grpc-hostname` should be there.

**Comment by howardjohn** [comment]
I'll take a look

**Comment by howardjohn** [comment]
I ran 
```
make generate_e2e_yaml
cat install/kubernetes/istio-auth.yaml | grep grpc-hostname
```
10 times with no result. Are you sure you are running latest master?

**Comment by pitlv2109** [comment]
Yes I'm pretty sure I sync to the latest master. I tried reproducing this error in two other machines, and one of them also had this issue. It's not really alternating, but eventually I'll see two different versions. Not only this `grpc` flag, but many older flags as well. I'm not sure sure `helm` uses some kind of caching. We can try reproducing it tomorrow offline. Thanks for looking into this!

**Comment by pitlv2109** [comment]
Discussed offline, running `git clean -f` resolved the issue. 

Thanks @howardjohn. Feel free to add your explanation here for future reference and close this issue :)
