### ISSUE TITLE
istioctl: create a convenient install cmd

### ISSUE THREAD

**Issue by linsun** [istio/istio#13259]
Install: istioctl install

We don’t currently have an install cmd and our installation steps are complicated today.  Having an install cmd will help simplify our install experience.  This cmd should do pre-check to see if the env meets prerequisites of install, and then install if it meets the prerequisites. 

Options: 
--profile where users can specify which profile.  Default profile is used when none is specified.
Additional options should be exposed to allow users to overwrite configurations for a given profile.

When istio-operator is mature and stable, this could install the operator, and then use the operator to do the install.

As part of this work, we need to consider beyond k8s as well as there is a lot of feedback that istio is only k8s. Users should be able to run istioctl install to install control plane on a VM or do it themselves if they choose to.

**Comment by howardjohn** [comment]
We should create a library in https://github.com/istio-ecosystem/istio-installer using the new installer and access that through istioctl. Making an install command for the current installer isn't a good use of time since we will be using the new installer in 1.2

**Comment by incfly** [comment]
/cc @incfly 

I think this warrants a design doc. We need to consider wide range of install scenario.

- multi cluster installation in different modes, we have three.
- plan for operator / installer.

**Comment by linsun** [comment]
As part of this work, we need to consider beyond k8s as well as there is a lot of feedback that istio is only k8s.  Users should be able to run istioctl install to install control plane on a VM or do it themselves if they choose to.

**Comment by linsun** [comment]
I agree we will need a design doc for this.  @esnible  has started something not solely for istioctl: https://docs.google.com/document/d/1yxoQNfWgNFFPgyGHGvpTMN_Xy6KAoq57O2U8Wx0Nv8A/edit

**Comment by esnible** [comment]
@linsun I was intending to share that document after running it past @sdake and @ostromart .  We are trying to understand how _istioctl_, the new installer, and the operator play together for 1.3.

**Comment by linsun** [comment]
AFAIK, the new installer won't make to 1.3 either.  @sdake @rlenglet @brian-avery pls correct me if I'm wrong.

If we implement this on the older installer, how much additional work to switch to the new installer when it is ready?  Or should we introduce an experimental install cmd that uses the new installer only?  that may be the best way for users to get hands on on the new installer.

**Comment by howardjohn** [comment]
@linsun take a look at https://docs.google.com/document/d/1QoQHjjqkLkK0OsVpi9E_FTqHbMzD6bUpbBmXFi4D1pI if you have not seen it yet

It seems (to me at least) that the operator cli will become the all-in-one istio install cli?

**Comment by linsun** [comment]
Thanks @howardjohn!  a few thoughts -

- what if user wants to install but not have istio to manage the install?  This is designed as a convenient cmd where user doesn't have to read pages of install docs to quickly start with install istio.
- would operator be enabled and always on by default?
- it seems reasonable to have this as a top cmd in istioctl, and when operator becomes the main thing and default everywhere, this cmd can just call the `iop install` cmd.

cc @ostromart

**Comment by howardjohn** [comment]
I believe the intent is that the operator will be able to function both as an in-cluster operator as well as out of cluster, so you could do something like `iop template` and get the same output as helm template for example.

**Comment by rlenglet** [comment]
> AFAIK, the new installer won't make to 1.3 either. @sdake @rlenglet @brian-avery pls correct me if I'm wrong.

It is currently a P1 for 1.3, i.e. we won't hold the 1.3 release for it. My understanding is that this will be an alpha feature in 1.3.

**Comment by ostromart** [comment]
That's right - the operator has both a controller and CLI mode, so there's no need to install it in the cluster. We are currently working on integrating iop into istioctl and I think that should make it into 1.3 in some form (see https://docs.google.com/document/d/16SWW14zrwFKc9OzH6biMQD1u9INllzMa56jde9vgQkM/edit#heading=h.6krlfi8l3nek for a proposed CLI reference). @ayj is leading that integration. At least we will definitely have the standalone CLI available in time if not istioctl.

**Comment by ayj** [comment]
The proposed goal is to integrate the operator CLI functionality into istioctl. The IstioControlPlane API would be the common contract between istioctl, the optional operator/controller, and users intent (CR). That would roughly give us the following type of istioctl commands:

```bash
# Generate  install manifests which the user can then `kubectl apply`
$ istioctl mesh manifest --file=spec.yaml

# Install directly into cluster. 
$ istioctl mesh install --file=spec.yaml

# Check control plane status. Reference the provided control
# plane spec if provided. Otherwise, looks for the in-cluster
# operator’s IstioControlPlane CR.
$ istioctl mesh check  [--spec=spec.yaml] 

# Deploy the istio operator into the cluster. A default control plane
# profile will be created unless the `--spec` option is provided.
$ istioctl mesh deploy-operator [--spec=spec.yaml] 
```

I'd like to get the `manifest` and `install` sub-commands integrated into istioctl in the 1.3 timeframe under the experimental command. `check` and `deploy-operator` would come later. If, for some reason that isn't doable, we could ship the same `manifest` and `install` temporarily in the iop binary but conceptually aligned with the rest of istioctl.

**Comment by ostromart** [comment]
I dislike the idea of putting this under experimental because it send a different message from alpha (i.e. experimental = we may decide not to go forward with this). It's really important we communicate to users that this is the direction we're committed to. If we don't have an alpha category in istioctl can we just note that it's alpha in the documentation?

**Comment by ayj** [comment]
Per https://istio.io/about/feature-stages/#feature-phase-definitions, alpha features don't have a deprecation policy or compatibility guarantees. That said, we can certainly communicate our commitment to  istioctl/operator for install, though the specific API is not stable yet.

**Comment by ostromart** [comment]
I think that's ok - alpha with a long term plan communicated. Experimental isn't even defined.

**Comment by sdake** [comment]
to catch everyone up on where we stand today:

Please see these preliminary release notes around the `istioctl` experimental commands that made 1.3: https://deploy-preview-4934--preliminary-istio.netlify.com/about/notes/1.3/

**Comment by sdake** [comment]
The operator installation guide: https://deploy-preview-4934--preliminary-istio.netlify.com/docs/setup/install/operator/

**Comment by howardjohn** [comment]
I tihnk this is resolved, see docs above. Thanks everyone!
