### ISSUE TITLE
istioctl: provide convenient get all cmd

### ISSUE THREAD

**Issue by linsun** [istio/istio#13260]
**Describe the feature request**

istioctl get all
Currently deprecated but it is one of my favorite cmds.  The alternative is not user friendly: `kubectl get gw,vs,dr,se,policy,sidecar,meshpolicy` which can be a growing list.

**Comment by linsun** [comment]
This cmd is already there but it is marked as deprecated which I disagree.

**Comment by linsun** [comment]
It would be good to also investigate https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/ - is this something we can pioneer as extending kubectl?

**Comment by darwin67** [comment]
I agree with keeping the `get` command unless there's an alternative and using kubectl get for Istio is not a nice experience.

**Comment by irisdingbj** [comment]
start to work on this

**Comment by jwendell** [comment]
We have `kubectl get istio-io` that retrieves everything istio-related.

**Comment by linsun** [comment]
@jwendell can you confirm that `k get istio-io` returns everything, including `policy,sidecar,meshpolicy`?

Even if it returns everything,  the return of the `k get istio-io` result if not as friendly and missing some interesting info.

```
$ k get istio-io                                                                                                       
NAME                                                             HOST        AGE
destinationrule.networking.istio.io/destination-rule-guestbook   guestbook   3d

NAME                                            AGE
gateway.networking.istio.io/guestbook-gateway   3d

NAME                                                           GATEWAYS              HOSTS   AGE
virtualservice.networking.istio.io/virtual-service-guestbook   [guestbook-gateway]   [*]     2d
(⎈ |linistio8:default)
~/go/src/istio.io/installer on  master ⌚ 11:06:30
$ istioctl get all
Command "get" is deprecated, Use `kubectl get` instead (see https://kubernetes.io/docs/tasks/tools/install-kubectl)
DESTINATION-RULE NAME        HOST        SUBSETS   NAMESPACE   AGE
destination-rule-guestbook   guestbook   v1,v2     default     3d

VIRTUAL-SERVICE NAME        GATEWAYS            HOSTS     #HTTP     #TCP      NAMESPACE   AGE
virtual-service-guestbook   guestbook-gateway   *             1        0      default     2d

GATEWAY NAME        HOSTS     NAMESPACE   AGE
guestbook-gateway   *         default     4d
```

**Comment by jwendell** [comment]
We can improve what we get with `k get istio-io` by improving our CRD's definitions (see for instance https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio-init/files/crd-10.yaml#L26)

So, I believe it's more a matter of tradeoff between having duplicating functionality on `istioctl` that's already present on `kubectl` and improving our existing CRD's. I'd vote for the latter.

**Comment by linsun** [comment]
I think it is hard to figure out this cmd `k get istio-io`.  I know it because you told us.

This cmd isn't intuitive as `istioctl get all` which folks can remember and resonate well.

**Comment by linsun** [comment]
close this in favor of `k get istio-io` for now.
