### ISSUE TITLE
Add debugMode option in sidecar helm template 

### ISSUE THREAD

**Issue by mathspanda** [istio/istio#13263]
**Describe the feature request**
After PR #10830 merged, the hardcoded sidecar template is removed. We had a [debugMode](https://github.com/istio/istio/blob/release-1.1/pilot/pkg/kube/inject/mesh.go#L72) option in [hardcoded sidecar template](https://github.com/istio/istio/blob/release-1.1/pilot/pkg/kube/inject/mesh.go) to control the docker image used. However, there is no debugMode option in sidecar helm template. We need to add it.

See [comment](https://github.com/istio/istio/pull/10830#discussion_r247588224).

**Comment by howardjohn** [comment]
I don't think we have any demand for this anymore
