### ISSUE TITLE
Pilot does not refresh the endpoint,when a new pod was running, the uri reach to a wrong endpoint(the old pod)

### ISSUE THREAD

**Issue by dreadbird** [istio/istio#13270]
**Describe the bug**
When I kill the pod and a new pod is running,I get "upstream connect error or disconnect/reset before headers"
In the ingressgateway logs,find the uri reached a wrong endpoint
![image](https://user-images.githubusercontent.com/2113395/56020476-d5067500-5d39-11e9-8390-1c22e1180d8d.png)
and I cannot find any pod use the ip "10.1.53.43"
![image](https://user-images.githubusercontent.com/2113395/56020534-f5363400-5d39-11e9-946d-12d018255593.png)
the new pod ip is "10.1.119.181"
![image](https://user-images.githubusercontent.com/2113395/56020626-23b40f00-5d3a-11e9-9139-412c71c3813a.png)

I kill the pilot pod, the problem will be resovled temporarily.

**Steps to reproduce the bug**
1. kill a pod
2. run a new pod
3. can not access the uri

**Version**
Version: 1.0.0
GitRevision: 3a136c90ec5e308f236e0d7ebb5c4c5e405217f4
User: root@71a9470ea93c
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean

Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1+icp-ee", GitCommit:"5803c3b1f9422c43a963e0610b3a4cad565e127e", GitTreeState:"clean", BuildDate:"2018-09-04T09:29:02Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1+icp-ee", GitCommit:"5803c3b1f9422c43a963e0610b3a4cad565e127e", GitTreeState:"clean", BuildDate:"2018-09-04T09:29:02Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**Installation**
installed with helm

**Comment by GregHanson** [comment]
@dreadbird curious about the timing on this.  
 - How much of a delay between when you killed the app pod and attempted to reach the service through the ingress gateway?  
 - Is it eventually consistent?  Do later requests get directed to the correct endpoint/IP

Just trying to get a sense of whether pilot failed to push an updated service endpoint to envoy or if envoy was using a pooled/cached/existing connection to perform the request

**Comment by dreadbird** [comment]
tks  for u reply!
1.more than one hour,if I do not to restart pilot,will be delayed for several hours
2.I can not wait to see if it will be consistent eventually, because many teams are using ....

and , there were several error or failed messages in the pilot-discovery logs:
```
2019-04-12T01:21:49.468516Z     info    1 error occurred:

* gateway omitting listener "0.0.0.0_27017" due to: must have more than 0 chains in listener: &v2.Listener{Name:"0.0.0.0_27017", Address:core.Address{Address:(*core.Address_SocketAddress)(0xc471031c48)}, FilterChains:[]listener.FilterChain{}, UseOriginalDst:nil, PerConnectionBufferLimitBytes:nil, Metadata:(*core.Metadata)(nil), DeprecatedV1:(*v2.Listener_DeprecatedV1)(nil), DrainType:0, ListenerFilters:[]listener.ListenerFilter(nil), Transparent:nil, Freebind:nil, SocketOptions:[]*core.SocketOption(nil), TcpFastOpenQueueLength:nil}
```

```
2019-04-12T01:23:42.089456Z     warn    ads     Repeated failure to push 17 sidecar~10.1.232.169~kk-58ddb658b6-4ksfc.iam~iam.svc.cluster.local-239
2019-04-12T01:23:42.109584Z     warn    ads     Repeated failure to push 83 sidecar~10.1.77.34~app-bq96hfpc-instance-lt2lq72s-98qz544g-58f4f7b99c-snclq.demo~demo.svc.cluster.local-172
2019-04-12T01:23:42.176851Z     warn    ads     Repeated failure to push 56 sidecar~10.1.77.34~app-bq96hfpc-instance-lt2lq72s-98qz544g-58f4f7b99c-snclq.demo~demo.svc.cluster.local-172

```

**Comment by howardjohn** [comment]
All of this logic has changed since 1.0, please try on newer Istio 1.3. Sorry we didn't help resolve this sooner
