### ISSUE TITLE
Enable racetest for e2e/integration tests

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#13282]
We currently do not do a racetest for any integration/e2e tests. There are many race conditions we miss because of this.

We should consider enabling this on tests that exercise full code paths to capture more race conditions.

**Comment by ozevren** [comment]
There was a similar bug opened about this. https://github.com/istio/istio/issues/13341

How valuable it is to have integ/e2e tests doing this? (There are already racetests for unit tests).

**Comment by howardjohn** [comment]
@ozevren I built images of pilot with race test enabled and ran in a live kubernetes env and got 10s of failures (which I have filed bugs for), so it seems there are some race conditions that are missed. 
Perhaps the integration tests are not the best place to do this, but  I think there is some value to race testing in a "real" environment

**Comment by howardjohn** [comment]
Closing as dupe of https://github.com/istio/istio/issues/14049
