### ISSUE TITLE
connectionPool.http.idleTimeout not workiing

### ISSUE THREAD

**Issue by Stono** [istio/istio#13289]
According to https://istio.io/docs/reference/config/networking/v1alpha3/destination-rule I should be able to use the above setting however i'm getting the following error in pilot:

```
2019-04-12T18:45:34.079616Z	error	Failed to convert destination-rule object, ignoring: sourcing-recommendation-service/sourcing-recommendation-service YAML decoding error: host: app
trafficPolicy:
  connectionPool:
    http:
      idleTimeout: 30s
  loadBalancer:
    simple: LEAST_CONN
  tls:
    mode: ISTIO_MUTUAL
 unknown field "idleTimeout" in v1alpha3.ConnectionPoolSettings_HTTPSettings map[trafficPolicy:map[connectionPool:map[http:map[idleTimeout:30s]] loadBalancer:map[simple:LEAST_CONN] tls:map[mode:ISTIO_MUTUAL]] host:app]
```

Istio 1.1.2

**Comment by GregHanson** [comment]
@Stono I think this feature went in 2 days ago https://github.com/istio/istio/pull/13146/files
are you using a daily build or the official 1.1.2 release?

**Comment by Stono** [comment]
Ahhh official, I could grab the latest daily and use that instead.

**Comment by Stono** [comment]
Yup works with the latest daily, thanks.
Probably want to keep the docs inline with the current official release - it's confusing! :)
