### ISSUE TITLE
Istio IP blacklists for country blocking

### ISSUE THREAD

**Issue by mwei2016** [istio/istio#13283]
**Describe the feature request**
Didn't see similar support for country blocking in Istio as in Ngnix. For Istio, looks we need parse GeoIP data to extract blacklist IPs which is IP CIDR first. To block them, the options provided by Istio today are simple denial or ip-based blacklists. 
(https://istio.io/docs/tasks/policy-enforcement/denial-and-list/#ip-based-whitelists-or-blacklists)

There are some limitations for both options: 
1. For ip-based blacklists, there is no way to specify status. For feature parity as what we have for Ngnix, we need 403 and a customized message. Although list adapter has fixed the default return code from 404 to 403, there is no way to specify a customized message. 

2. For simple denials, though it allows specifying status code, didn't seem it supports IP CIDR match in the rule (https://istio.io/docs/reference/config/policy-and-telemetry/istio.policy.v1beta1/#Rule). 

Feature requests:
1. Provide built-in support for country blocking which eliminates the need for generating blacklist IPs. 
2. For ip-based blacklists, allow specifying status (including code, message).
3. For simple denials, support IP CIDR match. 

Also for attribute-based blacklists, how to pass a completely local list? 
Is there any other viable solution missed here?

**Comment by mwei2016** [comment]
Looks the default return code has been changed from NOT_FOUND to PERMISSION_DENIED (https://github.com/istio/istio/pull/10444). It is great! For that option, how to pass a completely local list?

**Comment by douglas-reid** [comment]
Yes, the overrides should work for attribute-based blacklists.

**Comment by gargnupur** [comment]
https://github.com/istio/istio/blob/1588b23e12b845f85e9aedb089288fdf10b75dc0/mixer/adapter/list/list_integration_test.go has an example of specifying overrides for ip list..

**Comment by gargnupur** [comment]
@mwei2016: Did overriding using IP list work for you?

**Comment by mwei2016** [comment]
Not yet: used overrides to pass 11K IP CIDR, but got blocked in the testing due to an issue in the env.

**Comment by Parvathy-Geetha** [comment]
@douglas-reid The attribute-based blacklisting also gives an empty error code.

`2019-07-29T18:43:26.195722Z	debug	api	Dispatching Check
2019-07-29T18:43:26.195785Z	debug	begin dispatch: destination='listentry:blacklistip.test(listchecker)'
2019-07-29T18:43:26.195806Z	debug	complete dispatch: destination='listentry:blacklistip.test(listchecker)' _{err:<nil>}_
2019-07-29T18:43:26.195846Z	debug	api	Check denied: {7 blacklistip.test:172.20.35.230 is blacklisted [] {} [] 0}`

**Comment by gargnupur** [comment]
@Parvathy-Geetha : Is this still an issue and if yes, how does your override config looks like?

**Comment by bmacauley-reward** [comment]
useful feature...would still be interested

**Comment by heylong6551** [comment]
@gargnupur , will this ip-based blacklist still working if I have millions of IP CIDR? For my usecase, I got the geo IP from GeoLite2 database provided by Maxmind, and US country consist of millions of IP CIRD.

**Comment by lukaesch** [comment]
Useful feature. Any updates so far?

**Comment by gargnupur** [comment]
+@yangminzhu , @mandarjog 
@lukaesch : In Istio 1.5 and forward we are actually suggesting users to use Authorization Policy to do this stuff as compared to using Mixer. https://preliminary.istio.io/docs/reference/config/security/authorization-policy/
So, we should add this feature to Authorization Policy in that case..
@yangminzhu : can we send custom status and message using Authorization Policy? It would be good to add country based blocking for IP's

**Comment by mwei2016** [comment]
Quick update from us: we are still on istio 1.3. We end up using out of process adapter to query GeoIP database with each client's IP and compares the response to a blacklist of countries.

**Comment by douglas-reid** [comment]
Assigning to @yangminzhu , as this is a FR for AuthorizationPolicy at this point.

**Comment by howardjohn** [comment]
Isn't this done by https://preliminary.istio.io/latest/docs/tasks/security/authorization/authz-ingress/#ip-based-allow-list-and-deny-list?

**Comment by douglas-reid** [comment]
@howardjohn only partially right? Does that support country-level blocking, or custom response codes and messages? I don't believe it does at the moment.
