### ISSUE TITLE
1.1.1 and 1.1.2 are identical, how the Envoy patch is applied?

### ISSUE THREAD

**Issue by mailzyok** [istio/istio#13318]
Hi, 

We build istio/proxy to get the envoy binary running on a different Linux. But 1.1.1 and 1.1.2 are identical, how can we apply the security patches for envoy?

Thanks,
yzha

**Comment by howardjohn** [comment]
I believe the patches were applied from a private repo due to the envoy embargo. They are being backported (or will be soon?) to the public repo

**Comment by nrjpoddar** [comment]
@howardjohn it will be really useful if decisions like this are conveyed to the broader public. Is there an easy way for anyone build a private version of istio proxy repo to build a version with Envoy patches without diverging from upstream release 1.1.2 branch?

**Comment by howardjohn** [comment]
That is about all I know, I wasn't involved with the release at all. @mjog or @silentdai can provide more info

**Comment by nrjpoddar** [comment]
Thanks @howardjohn Your clarification helped me out understand how 1.1.2 was built. Looks like 1.1.3 proxy tag has the correct Envoy version.

**Comment by mailzyok** [comment]
For the coming 1.1.3, according to the commit id of envoy used in file istio/proxy/istio.deps, the fix below for the securities are there, so i will wait for the official 1.1.3 release, then build my private envoy binary.

1. codec: reject embedded NUL in headers. (#2)  …
2. build: import manually minified Chrome URL lib. (#3)  …
3. hcm: path normalization. (#1)

Thanks.

**Comment by mjog** [comment]
Honestly, if I get CC'ed on another one of your tickets, I'm going to start posting goatse in reply every time it happens.

**Comment by howardjohn** [comment]
@mandarjog

**Comment by mandarjog** [comment]
@mailzyok That is correct. 1.1.2 istio-proxy was built from a private branch of envoy.
With 1.1.3 we are back to using upstream envoy sha. You should be able to build your own version of envoy from that now.

**Comment by mailzyok** [comment]
@mandarjog Thanks a lot! This issue is closed.
