### ISSUE TITLE
Whether ARM64 platform is available Now？

### ISSUE THREAD

**Issue by DragonSuper** [istio/istio#13321]
Hi，I want to compile the source code manually in ARM64 platform。
I don't know if it will work。
If I package it as  docker mirror images，Whether istio works properly in ARM64 platform now.
I want to make sure if it's going to happen,Because I didn't find anything docker ARM64 mirror images in docker hub.

**Comment by sdake** [comment]
@DragonSuper at this time, ARM64 is not a supported platform for Istio.  Your welcome to try to build it yourself following the developer guide:
https://github.com/istio/istio/wiki/Dev-Guide

The Istio project would need gating with ARM hardware to effectively release ARM64 containers.

**Comment by Alxandr** [comment]
What do you mean "gating with ARM hardware"?

**Comment by DragonSuper** [comment]
> What do you mean "gating with ARM hardware"?
Hi，My K8s runs  in the arm64 platform。I want to use istio。
But Docker Hub doesn't have any docker mirror images。
If istio works properly in ARM64 platform， i will compile the source code manually to generate arm64 docker image。
I just want to make sure，I don't want to fool around。

**Comment by howardjohn** [comment]
@DragonSuper as Steve mentioned, I don't know of any current plans to add ARM64 support, but contributions are welcome
@Alxandr I believe Steve is referring to the CI checks. If we add support for ARM64 we would want to add it to our tests, and our CI may or may not support ARM (I am not sure if it does)

**Comment by zqzzq** [comment]
@DragonSuper Have you succeeded? Now I want to compile and package the istio image in ARM too.

**Comment by DragonSuper** [comment]
> @DragonSuper Have you succeeded? Now I want to compile and package the istio image in ARM too.

Sorry,I don't have Internet,  offline download required,the test progress is slow. Istio Compile it right away.

**Comment by aliariff** [comment]
Hi, I have tried to build from the source inside my raspberry pi but the result is 
`cmd/go: unsupported GOOS/GOARCH pair linux/armv7l`

![image](https://user-images.githubusercontent.com/6806035/61500266-bbc13480-a9ca-11e9-865b-ae0d5884f13a.png)

Any idea to solve this? 

Btw I also have the interest to help to create a PR in order to support ARM if possible, but I need help to show me the way what to look for because I am not familiar with the codebase.

**Comment by howardjohn** [comment]
bin/gobuild.sh is a wrapper around "go build" that we use and adds some settings. I'd try to `go build ./... ` and if that works then it's something in that's script preventing the build

**Comment by aliariff** [comment]
@howardjohn 
yes, you are right there is a problem with the `bin/gobuild.sh`, it does not parse the `GOARCH` properly. I can build istio for ARM properly, but now the problem is that Envoy does not support ARM yet, and it seems it is hard to compile it to ARM.

Ref: https://github.com/envoyproxy/envoy/issues/1861#issuecomment-476690359

**Comment by howardjohn** [comment]
Ah makes sense. Well if its useful to get istio built on ARM even without envoy feel free to send a PR for the fix, happy to have Istio running in more places

**Comment by DragonSuper** [comment]
> @howardjohn
> yes, you are right there is a problem with the `bin/gobuild.sh` that get the value from https://github.com/istio/istio/blob/master/Makefile#L61, it does not parse the `GOARCH` properly. I can build istio for ARM properly, but now the problem is that Envoy does not support ARM yet, and it seems it is hard to compile it to ARM.
> 
> Ref: [envoyproxy/envoy#1861 (comment)](https://github.com/envoyproxy/envoy/issues/1861#issuecomment-476690359)

Hi，My arm64 CUP is ok，but I don't know the other architecture about arm。
envoy support structure arm64 and arm32，but  I didn't compile other architecture except aarch64

**Comment by aliariff** [comment]
@DragonSuper 
Could you show me the output of `uname -m` from your machine, because in my Raspberry Pi it showed `armv7l` and this is the reason the build is failed. We need to normalize that string to a proper arm version either it is `arm` or `arm64` so that GOARCH can understand it.

Regarding the envoy/istio proxy, I still can not find any working tutorial to compile it to arm arch, if you have any luck to make it run in arm, please show me how.

**Comment by DragonSuper** [comment]
> armv7l

uname -m
aarch64

**Comment by DragonSuper** [comment]
> @DragonSuper
> Could you show me the output of `uname -m` from your machine, because in my Raspberry Pi it showed `armv7l` and this is the reason the build is failed. We need to normalize that string to a proper arm version either it is `arm` or `arm64` so that GOARCH can understand it.
> 
> Regarding the envoy/istio proxy, I still can not find any working tutorial to compile it to arm arch, if you have any luck to make it run in arm, please show me how.

uname -m
aarch64

**Comment by aliariff** [comment]
@DragonSuper 
Based on the documentation here https://golang.org/doc/install/source#environment
GOARCH value `aarch64` is not valid, and need to be parsed to `arm64`, so I don't think you can compile it properly without getting an error. Could you try to run `make build` from your machine with `master` branch?

**Comment by aliariff** [comment]
@DragonSuper 
Ah I know what happens, the current master branch is still hardcoded the GOARCH value to `amd64` therefore there will be no error even your arch is `aarch64`. The resulting binaries are `amd64`.
I don't know if those binaries can run in the `aarch64` system.

**Comment by DragonSuper** [comment]
@aliariff 
uname -m
aarch64

**Comment by DragonSuper** [comment]
@aliariff 
My binaries that was compiled is ok in the aarch64 system。

**Comment by DragonSuper** [comment]
@aliariff 
I changed the related "aarch64" to "arm64". Because I think aarch64 is the same as arm64

**Comment by aliariff** [comment]
@DragonSuper 
I see, so you change it manually. Ok good to know, I thought it works without you changing anything.

**Comment by zqzzq** [comment]
The GOARCH should be equal to the value in the output of "go version", for example, in my host:
```
# go version           
go version go1.12.5 linux/arm64
```
so my GOARCH must be arm64, If I set the GOARCH value to others like aarch64, it will give an error like:
```
# go version
cmd/go: unsupported GOOS/GOARCH pair linux/aarch64
```

**Comment by warlice** [comment]
> 
> 
> @aliariff
> My binaries that was compiled is ok in the aarch64 system。

Is there any note or readme for compile istio to share？ I also want use istio in arm64 platform, I d appreciate  if U can give a hand ！

**Comment by aliariff** [comment]
@warlice 

Right now if you compile from the master branch, change this 2 line
https://github.com/istio/istio/blob/master/Makefile#L358
https://github.com/istio/istio/blob/master/Makefile#L362

from hardcoded `amd64` to `arm64`.
If you compile it from mac, change `GOOS=$(GOOS)` to `GOOS=linux` in the same line.

**Comment by AL-Cui** [comment]
I can't find the istio/base docker image  based arm64. Where can I find it? or,Where can I find the dockerfile

**Comment by DragonSuper** [comment]
my arm64 istio is ok! your email or qq?------------------ 原始邮件 ------------------
发件人: "崔铎"<notifications@github.com>
发送时间: 2019年11月5日(星期二) 下午4:19
收件人: "istio/istio"<istio@noreply.github.com>;
抄送: "Super"<xiaozheng8187@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [istio/istio] Whether ARM64 platform is available Now？ (#13321)



I can't find the istio/base docker image  based arm64. Where can I find it? or,Where can I find the dockerfile
 
&mdash;

**Comment by AL-Cui** [comment]
> my arm64 istio is ok! your email or qq?------------------ 原始邮件 ------------------ 发件人: "崔铎"<notifications@github.com> 发送时间: 2019年11月5日(星期二) 下午4:19 收件人: "istio/istio"<istio@noreply.github.com>; 抄送: "Super"<xiaozheng8187@qq.com>;"Mention"<mention@noreply.github.com>; 主题: Re: [istio/istio] Whether ARM64 platform is available Now？ (#13321) I can't find the istio/base docker image based arm64. Where can I find it? or,Where can I find the dockerfile &mdash; You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

qq1966590104,thanks

**Comment by xUnholy** [comment]
@DragonSuper seeing as Enovy now supports ARM architecture will there be any plans in the near future for the Istio team to likewise maintain their own images?

I noticed today when attempting to set up my local Raspberry Pi Kube cluster, whilst I was setting up Istio that my scheduler could not pick a node to run any of my pods due to the `nodeAffinity` only allowing the following:

`          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x`

**Comment by DragonSuper** [comment]
@xUnholy Hi，My arm64 Isito is ok！
Because I don't have a CPU architecture about ppc64le，so  I change the value of “ppc64le” to “arm64”
 as follow:
`      affinity:      
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
                - s390x `

And of course you can add “arm64” , you should be carefully checked。

**Comment by DragonSuper** [comment]
@DragonSuper Arm64-Istio-Image is compiled by me. I didn't find the corresponding mirror image in ‘Docker Hub’ before。 So I don't have official documentation，Modify the YAML file as my understand it。I change the value of “ppc64le” to “arm64” by searching for keywords “ppc64le”。

**Comment by xUnholy** [comment]
@DragonSuper I'm setting everything up on a Raspberry Pi cluster so it's armv7l not quite arm64 arch.

Have you attempted to build for arm? I'm in the process of compiling my own however, it takes time and effort. Would be interested if you or anyone else has successfully done it before.

**Comment by DragonSuper** [comment]
@xUnholy I compiled istio and envoy for arm64. I don't know if istio is normal for armv7l。
I refer to the following url for compilation。
https://medium.com/@nadundesilva/building-istio-from-source-on-linux-be860d660aa7

**Comment by xUnholy** [comment]
Thanks @DragonSuper 

I'll attempt to compile for armv7l and post my artifact links here for reference.

I did see the istio makefile supports just arm as apposed to arm64 however, I'm guessing it's just not officially supported and will require I compile it from source.

Appreciate the helpful response and link!

**Comment by pisymbol** [comment]
@xUnholy I am in the same boat. I want to run Istio/Envoy on armv7 on my RPi4 cluster. Any luck?

**Comment by xUnholy** [comment]
Hi @pisymbol I plan on attempting the compiling of istio again for armv7l and I'll let you know my findings, firstly I had to compile golang for armv7l which if you're also looking for support you can check out my unofficial repository - https://github.com/Raspbernetes/armv7l-arch-images

Keep in mind I haven't published the package for the golang tarball / image quite yet, however, I will anticipate on doing so in the near future unless you wanted to assist in that regard.

**Comment by xUnholy** [comment]
@aliariff did you have any success with compiling Istio for armv7l? I'm now going down the rabbit hole where build dependencies aren't compatible, such as Bazel and Golang (although I managed to sort golang out as mentioned above)

**Comment by hphde** [comment]
+1 for Raspberry!

**Comment by aliariff** [comment]
@xUnholy nope! I did not manage to make it worked.

**Comment by tegk** [comment]
Did anybody get it to work? I can build envoy with arn64 so this should be now possible?

**Comment by xUnholy** [comment]
@tegk if you've done the envoy side, I've done the istio control plane side, the only part I didn't get time to complete was envoy for the dataplane, perhaps we should get in contact here https://discord.gg/RGvKzVg and collaborate on supporting arm64 until the upstream maintainers have capacity to do so themselves.

**Comment by aurorazl** [comment]
> compiled

How to generate YAML files?Do you use command "kubectl apply -f" to install istio?

**Comment by aurorazl** [comment]
> @xUnholy Arm64-Istio-Image is compiled by me. I didn't find the corresponding mirror image in ‘Docker Hub’ before。 So I don't have official documentation，Modify the YAML file as my understand it。I change the value of “ppc64le” to “arm64” by searching for keywords “ppc64le”。

How to generate YAML files?Do you use command "kubectl apply -f" to install istio?

**Comment by aurorazl** [comment]
> @DragonSuper I'm setting everything up on a Raspberry Pi cluster so it's armv7l not quite arm64 arch.
> 
> Have you attempted to build for arm? I'm in the process of compiling my own however, it takes time and effort. Would be interested if you or anyone else has successfully done it before.

I use "istioctl profile dump > istio-default.yaml" or "istioctl manifest generate > generated-manifest.yaml" and modify arch.But Both "istioctl install -f" and "istioctl install --charts" failed with error “unknown field "arm64" in v1alpha1.ArchConfig”。

**Comment by DragonSuper** [comment]
> > @DragonSuper I'm setting everything up on a Raspberry Pi cluster so it's armv7l not quite arm64 arch.
> > Have you attempted to build for arm? I'm in the process of compiling my own however, it takes time and effort. Would be interested if you or anyone else has successfully done it before.
> 
> I use "istioctl profile dump > istio-default.yaml" or "istioctl manifest generate > generated-manifest.yaml" and modify arch.But Both "istioctl install -f" and "istioctl install --charts" failed with error “unknown field "arm64" in v1alpha1.ArchConfig”。

my yaml is ok!   all !

          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
                - s390x
