### ISSUE TITLE
go-junit-report sometimes misses failures leading to confusing test results

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#13320]
Example: https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/13175/istio-unit-tests/23817

Header says: 

> 0 failed / 7403 succeeded

And test is marked as failed. Digging into the logs shows a real failure, but it isn't recorded as one. This may actually be an issue with the junit report (if that is how prow gets this info)

This makes it really hard to debug failures

**Comment by ozevren** [comment]
@utka, I am assigning this to you for further triage/investigation/reassignment.

**Comment by howardjohn** [comment]
https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/13746/istio-unit-tests/24687 another example
Failure is the ApplyThrice one, junit report shows it as passing

**Comment by utka** [comment]
Though all test marked as Pass, Prow still reports the run as failed https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/13746/istio-unit-tests/24687

Looking into junit report

**Comment by howardjohn** [comment]
@utka this is actually a tricky case. `panic: Fail in goroutine after TestApplyThrice has completed`. The test is actually marked as passing, then fails AFTER it passes.

This may be the only instance when we see this bug -- both examples I posted are from the same test, and we had a PR that fixed this test, so maybe this isn't a big issue

**Comment by utka** [comment]
Yes, I noticed that test marked as pass, but summary is Fail
I created issue for junit report https://github.com/jstemmer/go-junit-report/issues/87

**Comment by howardjohn** [comment]
gotestsum is an alternative to the junit thing we use. If this becomes a bigger issue we can consider migration.

It's made by circleci so they have some vested interest in maintaining it, as they only support junit as well

**Comment by howardjohn** [comment]
still important
