### ISSUE TITLE
Explore using Kind for integration tests

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#13323]
Problems with the kube integration tests: tests are slow, and will grow slower as we add tests because they cannot be run in parallel - in general, each tests creates and tears down a full Istio install. They are also hard to debug in CI and often CI failures cannot be reproduced (https://github.com/istio/istio/issues/13307) 

We should explore using KinD for the new integration framework. At the very least, this will ensure a hermetic test environment.

Steps:

- [ ] 1. Get simple KinD running - Cluster created in makefile
- [ ] 2. Explore creating KinD clusters within the framework - one cluster per suite
- [ ] 3. Explore optimizations
- Turn on parallelism in tests
- preload Istio images into custom Kind node image at start of test, so that image loading is only done once?

**Comment by incfly** [comment]
If the slowness comes from istio profile install in each test, instead of spawning GKE cluster, switching to a lightweight k8s cluster implementation does not seem help.

Instead, we can look into if the tests are able to reuse the same Istio installation, and use different per deployment annotation, or focused scope CRD to speed up.

**Comment by howardjohn** [comment]
True it will probably not make the istio install faster. We can run the tests in parallel though, which could speed things up.

**Comment by incfly** [comment]
By run tests in parallel, you mean we spawn up many KinD cluster instances, and each for an Istio installation and test suite?

**Comment by howardjohn** [comment]
That is the idea. This is an experiment though, definitely not going to turn this on in the test right now/ever.

I have gotten kind+istio deployed in ~2min btw, it is pretty quick

**Comment by incfly** [comment]
Another alternative can be claiming multiple prow cluster from beginning
and assign one to each test. This allows parallelism as well.

Just for brainstorming.

**Comment by ozevren** [comment]
@howardjohn Are you actively looking at this? Who is on point for this?

**Comment by howardjohn** [comment]
I am semi-actively looking at this when I have free time. It is kind of blocked by https://github.com/istio/istio/pull/13324, but since this is just experimenting with it for now I can still test it out by building on that PR for now.

As I mentioned before I don't know if this is something we want, but it might be so I want to play around with it and see what benefits it provides, if any. Just wanted to be clear this wasn't a decision made that we should make this change, just that we should look into it

**Comment by ozevren** [comment]
Ok, I'll assign the issue to you, since you're the one that is looking at it for the time being (even if it is semi-active). Please update the issue (or write a doc) once the exploration is complete, or unassign when you're no longer working on this.

**Comment by howardjohn** [comment]
Some quick experiments show KinD adding about 1m to each test. Each test takes about 3m.

On my desktop I have 6 cores so I ran 6 tests in parallel. Security suite completed in 6 min vs estimated 18 min without kind. This of course comes at the cost of a lot more CPU usage.

**Comment by ozevren** [comment]
Just following up on this. What is the status? Any blockers?

**Comment by ozevren** [comment]
Why is the addition? Is that setup time for Kind, or general slowness.

**Comment by ozevren** [comment]
Any update on this?

**Comment by howardjohn** [comment]
With the splitting of the targets, I think this is less valuable specfically to the integration tests (creating cluster per suite). We should still explore using kind in general, and I think we have an issue for that, so we can close this

**Comment by ozevren** [comment]
Thanks. Can you add a link to the issue here as well, for tracking purposes?
