### ISSUE TITLE
Separate server / client secrets in nodeagent to make ingress MTLS possible with cert-manager

### ISSUE THREAD

**Issue by farcaller** [istio/istio#13339]
**Describe the feature request**

This is a followup to #12132 and #11496 because the discussion there seems to focus on a different problem.

**Problem statement**

istio's nodeagent [performs 1:M mapping](https://github.com/istio/istio/blob/0e9cecab053aab744a7c3a731aacb07fd794d5f9/security/pkg/nodeagent/secretfetcher/secretfetcher.go#L144) from k8s Secret to the SecretItem: it generates the server SecretItem from the `cert`/`key` pair and the client SecretItem from the `cacert`. This makes it impossible to use it with cert-manager as is as the [code path](https://github.com/istio/istio/blob/0e9cecab053aab744a7c3a731aacb07fd794d5f9/security/pkg/nodeagent/secretfetcher/secretfetcher.go#L152) for the cert-manager certificates wouldn't fetch any client certificate ever.

**Proposed solution**

nodeagent should map both server key+cert pair and client cert 1:1 to different k8s secrets. In such a case it can create a SecretItem for cert-manager managed Secret and fetch the client CA certificate from a different Secret.

Note that cert-manager shouldn't manage client CA in any way, it's fully out of the scope of their project. Cert-manager manages the server certs and keys.

Client CA might have a different lifetime, origins, and management. It doesn't make sense to bundle those two together.

Willing to submit a PR with a fix.

**Comment by farcaller** [comment]
/cc @myidpt @prune998 @thomschke @JimmyCYJ 

copying over from #12132. I know these tickets are very closely related but #12132 seems to go into a different direction and I focus this one on a very narrow and a very explicit problem: separation of client/server auth for the k8s use case.

**Comment by JimmyCYJ** [comment]
https://github.com/istio/istio/pull/15496 has major feature changes, unit tests and integration test.
Next step is adding more unit tests, integration tests and performance tests, and updating user guide.

**Comment by farcaller** [comment]
I believe the docs aren't updated yet.
