### ISSUE TITLE
Upgrading from Istio 1.0.6 to 1.0.7 has no effect(Helm chart version is same)

### ISSUE THREAD

**Issue by pc-rshetty** [istio/istio#13338]
**Describe the bug**
After upgrading istio the version still shows 1.0.6. Also i am not sure if it even upgraded anything

**Expected behavior**
Version should be 1.0.7

**Steps to reproduce the bug**
Helm install with istio 1.0.6 and then helm upgrade to istio 1.0.7

**Version**
kubernetes 1.11 istio 1.0.7

**Installation**
Helm

**Environment**
EKS

**Cluster state**
Everything is working but not sure if the security fix made it

**Comment by howardjohn** [comment]
This seems to be the same as https://github.com/istio/istio/issues/13176. Please take a look at the discussion there and comment there if you have any more info/questions
