### ISSUE TITLE
Galley built in sink server handles only one sink client

### ISSUE THREAD

**Issue by rshriram** [istio/istio#13334]
The code for the sink server inside Galley can handle only one sink client. It is not possible for multiple clients to send data to the same galley (as sink) as the internal data structures are not built for it. 

The updater interface (and the params passed) does not have a way to identify the client where data is coming from.

**Comment by hzxuzhonghu** [comment]
Some users have asked how to support multi cluster service mesh if using galley , especially when the service and endpoints are propagated from galley.

**Comment by ayj** [comment]
We don't have a real use case yet for galley needing to consume multiple sources of config/resources. We can re-open or create a new bug later if this changes.
