### ISSUE TITLE
Add tests that detect race condition

### ISSUE THREAD

**Issue by lei-tang** [istio/istio#13341]
**Describe the feature request**
Race condition causes various kinds of program errors in Istio. This feature requests for adding Istio tests (unit tests, integration tests, and etc) that detect race condition.

**Describe alternatives you've considered**
N.A.

**Additional context**
Race condition causes various kinds of program errors in Istio.

**Comment by ozevren** [comment]
Is this an actual problem we hit?
This is not going to work for K8s based tests, and for native it will have limited value at the limit I think.

**Comment by lei-tang** [comment]
Yes, race condition is an actual problem we hit. There were ~100 [commits](https://github.com/istio/istio/search?q=race&type=Commits) in Istio repo for fixing bugs caused by race condition. Currently detecting race condition is only enabled in istio-integ-race-native-tests for integration tests running in native environment. The race condition detection is not enabled yet for tests that use Istio images in k8s environoment because Istio images are currently not built with -race flag due to CPU and memory overhead.

**Comment by ozevren** [comment]
I was asking specifically about race conditions *and* the integration testing.
Unit tests are more likely to give us a much stronger signal about race conditions.

**Comment by lei-tang** [comment]
Revised the issue description to cover unit tests.

**Comment by ozevren** [comment]
BTW, we already have racetests: https://testgrid.k8s.io/istio-presubmits#circleci-racetest

**Comment by lei-tang** [comment]
Thanks for the link!

**Comment by ozevren** [comment]
Closing this in favor of https://github.com/istio/istio/issues/13282
