### ISSUE TITLE
RouteConfiguration rejected due to constraint validation failed on CorsPolicy

### ISSUE THREAD

**Issue by sterchelen** [istio/istio#13358]
**Describe the bug**
I have cors policy set. When I have two replicas of a gateway deployment, one of them has the following error message:
```
[2019-04-15 19:00:42.513][12][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_mux_subscription_lib/common/config/grpc_mux_subscription_impl.h:77]
 gRPC config for type.googleapis.com/envoy.api.v2.RouteConfiguration rejected: Proto constraint validation failed 
(Using deprecated option 'envoy.api.v2.route.CorsPolicy.enabled' from file route.proto. This configuration will be removed from Envoy soon.
Please see https://www.envoyproxy.io/docs/envoy/latest/intro/deprecated for details. 
If continued use of this field is absolutely necessary, see https://www.envoyproxy.io/docs/envoy/latest/configuration/runtime#using-runtime-overrides-for-deprecated-features for how to apply a temporary and highly discouraged override.): allow_origin: "MYDOMAIN"
```
The one that has this message is not handling the traffic.

**Expected behavior**
Deprecated configuration should not reject proto constraint.

**Version**
1.1.0

**Installation**
With helm

**Environment**
GKE

**Comment by howardjohn** [comment]
@kyessenov is this related to what you were working on with the RuntimeFractionalPercent stuff?

**Comment by esnible** [comment]
@sterchelen Can you attach your Istio rule that caused Envoy to generate this message?  I'd like to use it as a test case to improve Istio validation.

**Comment by kyessenov** [comment]
1.1.3 has a patch to avoid using the deprecated field in Envoy. Although, I'm not sure how you ended up with 1.0.0 istio and a recent envoy in your set-up. I think the recommendation is to use a released version of istio,e.g. 1.1.3.

**Comment by sterchelen** [comment]
@kyessenov, where do you see that I'm running two versions of istio?

**Comment by howardjohn** [comment]
This issue has been fixed on 1.1.3+ I believe. If you have issues with newer versions please reopen this

**Comment by enmasse** [comment]
Do you have a workaround for this issue?

**Comment by howardjohn** [comment]
using Istio 1.1.3+ is the only workaround as far as I know

**Comment by robeferre-leroy** [comment]
2019-12-30T18:36:12.135923Z	warn	ads	ADS:LDS: ACK ERROR 127.0.0.1:58138 router~192.168.161.45~istio-ingressgateway-788fdd64c8-c6fzp.istio-system~istio-system.svc.cluster.local-8 (istio-ingressgateway-788fdd64c8-c6fzp.istio-system) Internal:Error adding/updating listener(s) 0.0.0.0_443: Invalid path: /etc/istio/ingressgateway-certs/tls.crt


Same issue on version 1.4.
