### ISSUE TITLE
Authentication v1alpha2

### ISSUE THREAD

**Issue by diemtvu** [istio/istio#13356]
Tasks for new authentication policy works.

- [ ] API design (TBD: links)

- [ ] Define protos and CRDs needed for new API

- [ ] (Pilot/Galley) Validation 

- [ ] (Pilot/Galley) Config store method to retrieve the policy. May include Galley pushConfig

- [ ] (Pilot/Galley) Online conversion from alpha1 to alpha2.

- [ ] (Pilot) Envoy config generation and distribution.

- [ ] (Envoy) New authn filter. 

- [ ] Integration tests.

**Comment by yangminzhu** [comment]
/cc @yangminzhu 
The PR for `(Pilot/Galley) Online conversion from alpha1 to alpha2.` (https://github.com/istio/istio/pull/12099) is blocked by some major refactor to galley from Oz.

**Comment by diemtvu** [comment]
Obsolete. https://github.com/istio/istio/issues/18399 is the new tracking.
