### ISSUE TITLE
Ingress gateway Envoy Memory/Connections leak

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#13355]
Running with ingressgateway-sds on 1.1.1

Memory usage grows ~2.5gb over days

envoy stats shows a ton of connections:
```
server.memory_allocated: 421730408
server.memory_heap_size: 2643460096
server.parent_connections: 0
server.total_connections: 83036
server.uptime: 580934
server.version: 5621769
server.watchdog_mega_miss: 2
server.watchdog_miss: 7
```

```
root@istio-ingressgateway-598b5d6fdc-95ftf:/# netstat -npa | grep envoy | wc -l
83469
```

Config dump doesn't show anything interesting

cc @jcetkov @mandarjog @JimmyCYJ

**Comment by costinm** [comment]
What are the connections ? Can you include a sample ? If from external hosts - it's quite normal.

**Comment by JimmyCYJ** [comment]
Is the memory usage from ingress-sds or istio-proxy(envoy)? Did you build the ingress-sds image with latest fix (https://github.com/istio/istio/pull/13251)? Without that fix the performance is going down.

**Comment by howardjohn** [comment]
Memory usage is from envoy

**Comment by howardjohn** [comment]
Cause is because Envoy isn't closing connections

**Comment by howardjohn** [comment]
@JimmyCYJ what ever came out of this?

**Comment by jcetkov** [comment]
I believe the conclusion was that the agent has to expose the envoy timeout idle connection property and set it to some more reasonable value than the default 'no timeout'. (Probably both for ingress and the injected sidecar)

**Comment by JimmyCYJ** [comment]
Let me check the timeout settings at gateway agent. We already have long running tests for workload SDS, and I am not ware of such issue.

**Comment by JimmyCYJ** [comment]
@jcetkov May I ask for more context about the issue? I remember last time we found that there were lots of connections to port 80 which caused the issue. Are there any new findings after that?

**Comment by howardjohn** [comment]
@JimmyCYJ Open a bunch of connections to ingress gateway with netcat or other, look at :15000/stats on the gateway and see `server.total_connections: some_big_number`. The connections are never closed

**Comment by jcetkov** [comment]
In essence, if client opens keep-alive connection and abandons it, it hangs there possibly indefinitely. We observed this going up to ~100k connections, at which point we were forced to restart the gateway, as the connections were coming through NAT, from limited set of IPs which started causing port collisions and timeouts.

**Comment by JimmyCYJ** [comment]
I need to take a look at the ingress-sds log to find out whether the number of SDS connections grows up. By default it should keep one connection. The SDS is using gRPC streaming service over one connection.

**Comment by howardjohn** [comment]
I don't think its related to SDS, th same thing happens without SDS

**Comment by JimmyCYJ** [comment]
@howardjohn could you ask Costin or other ingress gateway experts from networking team to take a look? I don't think this is related to SDS, since it happens without SDS.

**Comment by JimmyCYJ** [comment]
Tentatively reassign to Costin for triage.

**Comment by duderino** [comment]
@silentdai will take a look (while I figure out how to get him added to the github org so I can assign issues to him).  @PiotrSikora is OOO this week but should take a look too when he can

**Comment by howardjohn** [comment]
https://github.com/istio/istio/blob/323ef68f4176c6b5487de2d92206477393dc37b9/pilot/pkg/networking/core/v1alpha3/listener.go#L1407

Setting this will close the connections. Not sure what the difference between that and the stream idle timeout is, or what impact it may have on other areas though. @silentdai

**Comment by jcetkov** [comment]
I don't think this requires much code change, just allow the envoy wrapper (agent) to pass in the configuration @howardjohn mentioned (and possibly update the helm charts to use it by default)

**Comment by silentdai** [comment]
@JimmyCYJ @howardjohn Thank you for confirming that it's not SDS issue. Make life easier :)
@fpesce No need for action for you. It may(or may not) have relationship with your discovered keepalive bug

**Comment by duderino** [comment]
Current state of this bug is that we have exposed the ability to set idle timeouts in https://github.com/istio/istio/pull/13515 which will be in 1.1.4, but it's currently opt-in.

**Comment by geeknoid** [comment]
Can we close this, given #13515, or is there still more work needed?

**Comment by howardjohn** [comment]
In 1.1.4 set it with `--set gateways.istio-ingressgateway.env.ISTIO_META_IDLE_TIMEOUT=5s`

Value should be go duration format
