### ISSUE TITLE
Istio Pilot's Discovery container is not ready in Istio 1.1.2 and 1.1.3

### ISSUE THREAD

**Issue by Tushar120120** [istio/istio#13366]
**Describe the bug**
Installed Istio with helm on a hosted K8 cluster comprising 2 worker node and 1 master node running on ubuntu(CNI used is calico)

Found similar issues in git, but not much of help

**kubectl logs -n istio-system istio-pilot-7d57d987bb-c7j8t discovery | grep error**
2019-04-16T17:51:05.872407ZerrormcpError receiving MCP response: rpc error: code = Unavailable desc = transort is closing

 **kubectl describe pod -n istio-system istio-pilot-7d57d987bb-c7j8t** 
...
Events:
  Type     Reason     Age                 From               Message
  ----     ------     ----                ----               -------
  Normal   Scheduled  16m                 default-scheduler  Successfully assigned istio-system/istio-pilot-7d57d987bb
-c7j8t to tushar-5
  Normal   Pulling    16m                 kubelet, tushar-5  Pulling image "docker.io/istio/pilot:1.1.3"
  Normal   Pulled     15m                 kubelet, tushar-5  Successfully pulled image "docker.io/istio/pilot:1.1.3"
  Normal   Created    15m                 kubelet, tushar-5  Created container discovery
  Normal   Started    15m                 kubelet, tushar-5  Started container discovery
  Normal   Pulling    15m                 kubelet, tushar-5  Pulling image "docker.io/istio/proxyv2:1.1.3"
  Normal   Pulled     15m                 kubelet, tushar-5  Successfully pulled image "docker.io/istio/proxyv2:1.1.3"
  Normal   Created    15m                 kubelet, tushar-5  Created container istio-proxy
  Normal   Started    15m                 kubelet, tushar-5  Started container istio-proxy
  Warning  Unhealthy  97s (x27 over 14m)  kubelet, tushar-5  Readiness probe failed: Get http://172.168.1.53:8080/read
y: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

 **kubectl get pods -n istio-system istio-pilot-7d57d987bb-c7j8t  -o yaml | grep discovery**
    - discovery
    name: discovery
    message: 'containers with unready status: [discovery]'
    message: 'containers with unready status: [discovery]'
    name: discovery

**Expected behavior**
Pilot should be up
**Steps to reproduce the bug**
Install istio with Helm template 

**Version**
 **kubectl version**
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23
b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux
/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23
b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux
/amd64"}

**Installation**
helm template install/kubernetes/helm/istio --name istio --namespace istio-system -- **set global.configValidation=false** | kubectl apply -f -

**Environment**
{{ Which environment, cloud vendor, OS, etc are you using? }}

**Cluster state**
2 worker and 1 master are up, guestbook and busy box K8 samples are working.

**Comment by Tushar120120** [comment]
Here is an update, i found if the POD is scheduled int 1 of the 2 worker nodes, the POD runs, but if scheduled in the master node(tushar 5), readiness probe is still failing(Pilot got scheduled in worker node, so working)

NAME                             READY   STATUS    RESTARTS   AGE     IP              NODE       NOMINATED NODE   READIN
ESS GATES
details-v1-677c45466d-kfnww      2/2     Running   0          19h     172.168.2.128   tushar-4   <none>           <none>
frontend-69859f6796-86fxj        1/1     Running   0          2d22h   172.168.2.120   tushar-4   <none>           <none>
frontend-69859f6796-n2qzp        1/1     Running   0          2d22h   172.168.1.65    tushar-5   <none>           <none>
frontend-69859f6796-xlvf8        1/1     Running   0          2d22h   172.168.2.117   tushar-4   <none>           <none>
**httpbin-8c96b975-4lgpx           1/2     Running   0          19h     172.168.1.95    tushar-5   <none>           <none>**
productpage-v1-ff4f97586-hmhkl   2/2     Running   0          38h     172.168.2.127   tushar-4   <none>           <none>
ratings-v1-6d65ccbfb-xbc2c       1/2     Running   0          19h     172.168.1.97    tushar-5   <none>           <none>
redis-master-596696dd4-9gtfx     1/1     Running   0          2d22h   172.168.2.119   tushar-4   <none>           <none>
redis-slave-96685cfdb-9sgd7      1/1     Running   0          2d22h   172.168.2.118   tushar-4   <none>           <none>
redis-slave-96685cfdb-nh26p      1/1     Running   0          2d22h   172.168.1.64    tushar-5   <none>           <none>
**reviews-v1-64d7876b95-gjs5t      1/2     Running   0          19h     172.168.1.96    tushar-5   <none>           <none>**
reviews-v2-df87b76b-x4fvt        2/2     Running   0          38h     172.168.2.125   tushar-4   <none>           <none>
reviews-v3-6b7965c8df-hkn7p      2/2     Running   0          38h     172.168.2.126   tushar-4   <none>           <none>
sleep-6864ddbf94-bfhn6           2/2     Running   0          2d22h   172.168.2.121   tushar-4   <none>           <none>

**Comment by andraxylia** [comment]
Is this still an issue with the latest release?
