### ISSUE TITLE
No assets for release 1.1.3

### ISSUE THREAD

**Issue by erezzarum** [istio/istio#13365]
There is no "compiled" release for 1.1.3.
Command below as mentioned in the documents will fail:
```
curl -L https://git.io/getLatestIstio | ISTIO_VERSION=1.1.3 sh -
```

**Comment by GregHanson** [comment]
@erezzarum please use `1.1.2` for the version.  1.1.3 is still marked as a draft: https://github.com/istio/istio/releases

**Comment by erezzarum** [comment]
@GregHanson New users trying to install Istio for the first time will not be able to do so as the documents in the official site are updated to 1.1.3 as well as an official announcement in the Blog.
https://istio.io/blog/2019/announcing-1.1.3/

**Comment by geeknoid** [comment]
The bits have been published, we should be all set now.
