### ISSUE TITLE
Add E2E test for mesh expansion using new testing framework.

### ISSUE THREAD

**Issue by incfly** [istio/istio#13373]
Mesh expansion does not have proper test coverage, we need to write an E2E test under the new test framework. This is essential to ensure follow-up mesh expansion related work does not break it.

We used to have some preliminary test written using old testing framework. It has been disabled due to the GCE instance can't be `ssh` into. I figured out the reason is because testing pods are running as root and VM instance can't be login-to as root user.

All we need to do is to write an E2E test where
- Setup istio installation with mesh expansion enabled
- Create VM and deploy application in that VM, create service entry and k8s service correspondingly.
- Send request to a k8s pod, which send request to VM service, and verifies that succeed.

**Comment by costinm** [comment]
This can be done using Kind - you can run the deb installer inside the kind node and verify it works.

**Comment by howardjohn** [comment]
This is done now
