### ISSUE TITLE
Add config validation for Citadel deployment.

### ISSUE THREAD

**Issue by JimmyCYJ** [istio/istio#13383]
**Describe the feature request**
This is motivated by https://github.com/istio/istio/issues/13354, where there are two Citadels running in one cluster, and those two Citadels are not properly configured which causes a race condition. One Citadel keeps overwriting workload certificates generated by the other, and vise versa.

To avoid such kind of issue, we could enhance our config validation at Galley to guarantee that 
(1) Only one Citadel will be deployed in a cluster; and
(2) If multiple Citadels are deployed, command flags --read-signing-cert-only and --server-only are properly set.

It is also recommended to deploy one Citadel per cluster, as Citadel is not running in a critical path. Unless there are special needs, one Citadel is sufficient to provision certificates for all workloads.

**Comment by lei-tang** [comment]
https://github.com/istio/istio/pull/13519

**Comment by lei-tang** [comment]
Regarding to "enhance our config validation at Galley to guarantee that (1) Only one Citadel will be deployed in a cluster; and (2) If multiple Citadels are deployed, command flags --read-signing-cert-only and --server-only are properly set.", currently Galley only validates CRD and doesn't do validation at the deployment level.

**Comment by geeknoid** [comment]
Given #13519, can we close this issue or is there more work we want to do?

**Comment by lei-tang** [comment]
Closing this issue sounds good to me.
