### ISSUE TITLE
Integration tests failed with "no matching pod found for selectors" in presubmit

### ISSUE THREAD

**Issue by pitlv2109** [istio/istio#13390]
https://circleci.com/gh/istio/istio/388990?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link failed with `Failed retrieving pods: no matching pod found for selectors: [app=a version=v1]`

Search for `TestMutualTlsReachability` or `TestRBACV2`. These tests are set with Presubmit label in a WIP PR (https://github.com/istio/istio/pull/13384) and are using `GetAppOrFail`. Both tests passed when running locally with a GKE cluster.

**Comment by nmittler** [comment]
I suspect it's related to https://github.com/istio/istio/commit/bb90fed4ebada6f8fc7b9d5d26a89b306892b3af

@howardjohn can you confirm?

**Comment by howardjohn** [comment]
It's possible. Why fail only on circle though and and not prow? Easy check is to get logs from injector. I got pulled into some high priority bugs so won't get much time to look into this if you have a chance to dig deeper Phillip. If it's relayed to the injector I am pretty sure it will show an error in the logs of the injector

**Comment by pitlv2109** [comment]
It's not that urgent, you can take a look later when you have time. This is not blocking anything, at least for this week's planning. Thanks, John.

**Comment by pitlv2109** [comment]
@howardjohn  Any update on this?
fyi @yangminzhu

**Comment by howardjohn** [comment]
Haven't looked into it, it only fails when you enable those tests as presubmit and therefor run in circle? Because testgrid shows no failures

**Comment by pitlv2109** [comment]
Yes. It fails only when presubmit label is enabled and if it uses testing apps, e.g. a, b, c

**Comment by pitlv2109** [comment]
ping. Any update? Some tests are stable enough to have presubmit label.

**Comment by nmittler** [comment]
@pitlv2109 is this still an issue?

**Comment by pitlv2109** [comment]
I don't know. I haven't tried it (will try soon), but since we're using echo app now, maybe this issue is not relevant now?

**Comment by pitlv2109** [comment]
Actually, I think they are running in presubmit now? 
https://circleci.com/gh/istio/istio/412177?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link (search for TestRBACV2Basic in the test logs), 
compared to https://circleci.com/gh/istio/istio/409372?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link (Search for TestRBACV2 <- same test, it was renamed in recent PR. This test was skipped) from PR #13824. They both seem to be using label `CustomSetup`. Has anything changed in the way tests are setup to run in presubmit? @howardjohn @nmittler

**Comment by pitlv2109** [comment]
@lei-tang @yangminzhu fyi

**Comment by nmittler** [comment]
@pitlv2109 I've raised #13969

**Comment by pitlv2109** [comment]
Close this one since we don't use test apps anymore.
