### ISSUE TITLE
Call istio enabled container service from another namespace without istio

### ISSUE THREAD

**Issue by dwdraju** [istio/istio#13393]
**Bug description**
I am trying to call the service running on `default` namespace which is istio tls enabled from another namespace `test` which is non istio. But failed to reach

**Expected behavior**
I can reach another namespace(istio not enabled) service through `test` but can't reach services running on `default`
**Steps to reproduce the bug**
Call service from non-istio enabled namespace to istio enabled service.
I am getting error
```
curl user.default.svc.cluster.local
curl: (56) Recv failure: Connection reset by peer
```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Its Istio-1.0.5

```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.8-eks-7c34c0", GitCommit:"7c34c0d2f2d0f11f397d55a46945193a0e22d8f3", GitTreeState:"clean", BuildDate:"2019-03-01T22:49:39Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```
**How was Istio installed?**
`$ kubectl apply -f install/kubernetes/istio-demo-auth.yaml`

**Environment where bug was observed (cloud vendor, OS, etc)**
EKS 1.11

**Comment by esnible** [comment]
mTLS is a security feature.  Only pods participating in mTLS can talk to your mTLS pods.

If you must have mTLS between pods AND also allow non-Istio pods to access your services using plaintext HTTP you can use PERMISSIVE MODE.  https://istio.io/docs/concepts/security/#permissive-mode

**Comment by howardjohn** [comment]
@dwdraju thanks for the question. Like Ed said, I think this is working as intended. If you have any other issues please reopen
