### ISSUE TITLE
Environments WG 1.2 Feature and Code Mauve Epic

### ISSUE THREAD

**Issue by sdake** [istio/istio#13400]
Last reviewed at edit date.

These are features and code mauve wok planned in the Environments workgroup.  Focusing on these items is our priority.  Folks are free to submit work unrelated to these items.  We can consider altering the Epic features over time.

(P0) Code Mauve:
- stability testing for multi cluster and mesh expansion
- Load balancing with locality (howardjohn) 
- More automated stability tests for whitebox - stability, performance, etc
- Tests for environments WG related documentation
   - multicluster
   - mesh expansion: https://github.com/istio/istio/pull/13374
- SRE-related documentation
   - metrics
   - alerts
- selection of applications added to test cases
    - casandra
    - consul
    - kafka
    - nats
    - mysql
    - postgresql
    - redis
- Will be added under modular installer, and be included by the test/stability.
- MCP automated stability and install tests
    - Move the install/upgrade to KIND
    - Move bookinfo tests to KIND
- Evaluate KIND for CNI tests.

Features:
- (P?) Distroless images Issue #12122 (P?)
- (P0) Decomposed Installation - repository:  https://github.com/istio-ecosystem/istio-installer
- (P1) Operator - repository: 
- (P1) Multicluster Gaps Issue #11731

**Comment by ozevren** [comment]
Would it make sense to open this as an actual Epic? You can do this through the ZenHub UI, through the New Issue button.

**Comment by sdake** [comment]
@ozevren will do thanks.

**Comment by sdake** [comment]
closing in favor of an actual epic :) https://github.com/istio/istio/issues/13649
