### ISSUE TITLE
Pilot does not remove old endpoints from Envoy

### ISSUE THREAD

**Issue by dwradcliffe** [istio/istio#13402]
**Bug description**
Repeat of https://github.com/istio/istio/issues/9480
The bug was fixed (https://github.com/istio/istio/pull/9805) on 1.0 branch and never made it to 1.1 branch. 😞 

TL;DR: Endpoints are removed from k8s but never removed from envoy.

**Expected behavior**
Endpoints should be removed from envoy very quickly after they are removed from k8s.

**Steps to reproduce the bug**
Run helloworld sample. Scale down the deployment to 0 replicas and watch the endpoints (`istioctl proxy-config endpoints sleep-57f9d6fd6b-8lx6p.sample --cluster outbound|5000||helloworld.sample.svc.cluster.local`) and notice that they take many minutes to go away.

**Version**
1.1.2

**How was Istio installed?**
helm template + kubectl apply

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

**Comment by Stono** [comment]
I'm pretty worried about the fact we're not porting bug fixes across branches, resulting in regressions during upgrades.

**Comment by dwradcliffe** [comment]
Should leave this open until this is fixed on master

**Comment by ericvn** [comment]
@dwradcliffe I think we can close this as #13470 cherry picked the change to *master*.

**Comment by dwradcliffe** [comment]
Yep, thanks for that!
