### ISSUE TITLE
Revive setupMeshEx.sh automation

### ISSUE THREAD

**Issue by incfly** [istio/istio#13414]
**Describe the feature request**
Today mesh expansion doc is 100% manual work, which is error-prone. This causes each developer maintains their own bash automation, very sub-optimal and waste of duplicated work.

We used to have some automation bash script.  https://github.com/istio/istio/blob/master/install/tools/setupMeshEx.sh

This script now is out of dated with current implementation. But it's still largely good, only need a bit of special tweak to make it work again.

Specifically

- We document Gateway based approach to expose control plane. (ILB is still a good option in some case). The DNSMasq needs to be updated to point to gateway ip address.
- DNS resolution for kube dns is not working. I guess this has something to do with dnsmasq use UDP by default. We expose DNS over TLS on gateway... Need to investigate how to make it work.

**Describe alternatives you've considered**
None.

**Comment by xliuxu** [comment]
I would like to pick up this : )

**Comment by sdake** [comment]
@irisdingbj I am aware you are developing a presence in this technical area.  Can you take a look at this work?

Cheers
-steve
