### ISSUE TITLE
Logs missing after new ISTIO installation

### ISSUE THREAD

**Issue by viktorpeacock** [istio/istio#13415]
**Bug description**
We are in a process of adopting ISTIO and have recently upgraded to ISTIO 1.1.2 from 1.0.6. Once we upgraded, the ingress and envoy proxy logs do not display incoming requests, even though traffic is being routed correctly to the pods.

**Expected behavior**
Ingress and envoy logs appear for all the incoming requests that reach ingress and envoy proxies.

**Steps to reproduce the bug**
- Install ISTO 1.1.2 using default instructions
- Setup ingress gateway and a RESTful service running in a pod. Route traffic from gateway to the pod. 
- Open up ingress envoy and view logs. No logs will appear for incoming requests.
- Open up pod envoy proxy and view logs. No logs will appear for incoming requests.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-17-g2b13318"}

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
Via standard documentation on official istio site

**Environment where bug was observed (cloud vendor, OS, etc)**

Local docker-for-desktop kubernetes cluster

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by ibelikov** [comment]
This is the default behaviour in 1.1.x releases.

For a helm installation access logging can be enabled by changing this config (in case of 1.1.2) https://github.com/istio/istio/blob/1.1.2/install/kubernetes/helm/istio/values.yaml#L151-L155

**Comment by viktorpeacock** [comment]
Thank you @ibelikov. I'm looking through documentation and cannot find a way of modifying this via istioctl or kubectl - not sure if it's even possible? Also is there a way to view global configuration via istoktl or kubectl? Sorry if this is a wrong forum for this, but lacking some basic understanding and can't find relevant docs.

**Comment by dwradcliffe** [comment]
Full docs are here: https://istio.io/docs/tasks/telemetry/logs/access-log/

You can modify the configmap directly: `kubectl edit configmap -n istio-system istio` and look for `accessLogFile`, `accessLogFormat`, and `accessLogEncoding`

**Comment by viktorpeacock** [comment]
@dwradcliffe , thank you!
