### ISSUE TITLE
Add e2e test for distributed tracing 

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio#13425]
We need a test that verifies distributed tracing functionality in a way that incorporates multiple services, including the Istio services. The test should validate that the expected span structure is created, along with the expected tags.

Ideally, this should match the Tasks on distributed tracing.

We've had a number of trace behavior regressions as the system has evolved. Such a test should help prevent that moving forward.

Previous request: https://github.com/istio/istio/issues/3947

**Comment by fpesce** [comment]
@douglas-reid is there any remaining code change related to this issue? (I'm seeing that #13790 was closed)

**Comment by bianpengyuan** [comment]
No that is all for this issue. Closing now.
