### ISSUE TITLE
Documented default request timeout of 15s is not applied

### ISSUE THREAD

**Issue by jaygorrell** [istio/istio#13421]
**Bug description**
The documentation (in multiple places) says there is a 15s timeout with requests by default. I can confirm that this is not functioning if it is intended -- in fact, I have requests that go over 60s just fine. There may not even be a real timeout in place.

Applying a VirutalService with a timeout works as expected.

**Expected behavior**
Documented default timeout is actually what's used. Not sure if this is a documentation issue or an Istio issue itself.

**Steps to reproduce the bug**
1. Make requests to a service with 20s+ response time with no request timeout overrides
2. Observe that the request completes successfully.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Istio 1.1.3
Kubernetes 1.11.8

**How was Istio installed?**
Helm with basic settings

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS / Kops

**Comment by jaygorrell** [comment]
Removed references to Kiali showing 10s maximums (see referenced issue above). This is now solely on the default timeout not being applied.

**Comment by mbanikazemi** [comment]
Yes, it seems that request timeout was disabled a while ago here: https://github.com/istio/istio/pull/6042 but the documentations have not been updated accordingly.

**Comment by mbanikazemi** [comment]
The documentation was fixed to note that the request timeout is disabled by default.
