### ISSUE TITLE
Define branch usage model

### ISSUE THREAD

**Issue by ozevren** [istio/istio#13429]
As part of Code Mauve, we'd like to define the branch usage model for development & release management. We need to identify the branch model, and how we can use testing for gating merges between branches.

**Comment by ozevren** [comment]
Link for a proposal doc: https://docs.google.com/document/d/14s0Xx_X-uEGyS9BLHlskj--wsPJv71QTBsqneq6m29M/edit

**Comment by geeknoid** [comment]
What's left here?
