### ISSUE TITLE
Policies and Telemetry Code Mauve Epic

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio#13424]
This epic is used to track the Code Mauve work related to the policy and telemetry subsystems for Istio. Work on this epic is to be prioritized with a preference for improvements to Testing And Stability over UX Enhancements.

**Comment by kyessenov** [comment]
For the people who don't see zenhub-augmented UI, can you please tag all issues in this epic with "Code Mauve"?

**Comment by douglas-reid** [comment]
@kyessenov I'm trying to go through each one and assign priorities and labels appropriately. If I miss a few, I apologize.

**Comment by douglas-reid** [comment]
Links for issue search:
- [P0 items](https://github.com/istio/istio/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22code+mauve%22+label%3Apriority%2F0+label%3A%22area%2Fpolicies+and+telemetry%22)
- [P1 items](https://github.com/istio/istio/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22code+mauve%22+label%3Apriority%2F1+label%3A%22area%2Fpolicies+and+telemetry%22+)

**Comment by douglas-reid** [comment]
I'm going to close this Epic. The `code mauve` effort shifted a bit in focus since the creation of this Epic and there are other efforts to prioritize, etc.

At the time of closing, 17 of 47 tasks were completed, with 2 remaining open P0s.
