### ISSUE TITLE
Ensure all P&T Tasks have matching test using the same config

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio#13433]
Right now, some of the tasks on the website use different config than the tests that are exercising the feature being demonstrated and/or there is no matching test.  We should harmonize the tests and the tasks.  This issue is for the Policies and Telemetry related tasks.

**Comment by kyessenov** [comment]
This is unblocked by moving samples here by #13196 . We now should look into de-duping what is used for tests and what is published in docs.

**Comment by gargnupur** [comment]
I think we need tests for following tasks:
1) IP whitelist : https://preliminary.istio.io/docs/tasks/policy-enforcement/denial-and-list/#attribute-based-whitelists-or-blacklists (https://github.com/istio/istio/pull/13654)
2) Control Headers : https://istio.io/docs/tasks/policy-enforcement/control-headers/
3) Logs: Collecting Istio and Envoys logs : https://preliminary.istio.io/docs/tasks/telemetry/logs/collecting-logs/, https://preliminary.istio.io/docs/tasks/telemetry/logs/access-log/
4) Remotely accessing Mixer Addons: https://preliminary.istio.io/docs/tasks/telemetry/gateways/
5) Distributed Tracing: Covered in https://github.com/issues/istio/istio/13425

**Comment by fpesce** [comment]
@douglas-reid Is this issue depending on your approval on 13763?

**Comment by linsun** [comment]
Anything remaining for this?

**Comment by gargnupur** [comment]
I think we should definitely add envoys access log test, as we are moving a lot of mixer functionality to envoy..
