### ISSUE TITLE
Istio citadel does not push external certs to envoy proxies

### ISSUE THREAD

**Issue by varungbt** [istio/istio#13438]
**Bug description**
I am trying to use my own set of certificates for mTLS. Citadel does not push my external certificates to the envoy proxies. 

**Expected behavior**
I would expect my external certificates to be synced into envoy proxies

**Steps to reproduce the bug**
1. Install istio as described in the documentation using helm templates (this installs istio-1.1.3)
2. Enable mesh wide mTLS policy
3. Execute the steps mentioned here [Plugin ext ca-certs](https://istio.io/docs/tasks/security/plugin-ca-cert/)

4. Exec into ratings pod and I do not see any certs in /etc/cacerts, which essentially proves the fact the sync did not take place at all

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Can be found here [link](https://gist.github.com/varungbt/b8ab407c33b5c515e954f86d828f6cbf)
Also I notice the istioctl proxy-status is at [50%](https://gist.github.com/varungbt/164bf1e4e00a52280bbe7bdab37132d0)

**How was Istio installed?**
Installed using  [link](https://istio.io/docs/setup/kubernetes/install/helm/) on GKE
**Environment where bug was observed (cloud vendor, OS, etc)**
GKE, Linux

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by jswattjr** [comment]
I'm having a similar issue, but I'm seeing 'x509: certificate signed by unknown authority' errors all over.

**Steps to reproduce** 
1. Install istio as described in the documentation using helm templates (this installs istio-1.1.3), using values-istio-multicluster-gateways.yml and --set global.mtls.enabled to 'true'
2. Sign custom certs with custom CA per [instructions here](https://jamielinux.com/docs/openssl-certificate-authority/sign-server-and-client-certificates.html)
3. Execute steps from [Plugin ext ca-certs](https://istio.io/docs/tasks/security/plugin-ca-cert/)
4. Attempt to launch pod in namespace with istio-injection fails with error
```
Error from server (InternalError): Internal error occurred: failed calling webhook "sidecar-injector.istio.io": Post https://istio-sidecar-injector.istio-system.svc:443/inject?timeout=30s: x509: certificate signed by unknown authority
```

kubectl get pods -n istio-system reveals crashback loops in telemetry and policy pods. Mixer container in telemetry or policy pod has error:

```
Failed to create a new MCP sink stream: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: authentication handshake failed: x509: certificate signed by unknown authority"
```

**Version**
kubectl version:
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```
istioctl version
```
version.BuildInfo{Version:"1.1.3", GitRevision:"d19179769183541c5db473ae8d062ca899abb3be", User:"root", Host:"fbd493e1-5d72-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.2-56-gd191797"}
```

**Environment**
Azure aks-engine installation, linux

**Comment by varungbt** [comment]
Yes I can confirm that I too see `x509: certificate signed by unknown authority` when I use a valid certificate.
I have  a end user certificate signed by a intermediate authority.

I tried all possible combinations of splitting the certs into various files (ca-cert.pem,cert-chain.pem) and none of the various splits worked. It would be helpful if an example highlighting the usage of a certificate with one or more intermediate CAs is documented.

Also note that after deleting the citadel pod, the certs were pushed to the workload pods but the tls check fails due to `x509: certificate signed by unknown authority`

**Comment by jswattjr** [comment]
@varungbt I tried redeploying the cluster with no intermediate certificate (i.e. end user cert signed by the root) and have the same errors. Not sure custom CA's are working at all with mTLS.

**Comment by amutt** [comment]
@varungbt

Does your workaround allow for the use of external certificates from a separate CA to be used by istio/citadel in place of of it's generic certificates?
