### ISSUE TITLE
Refine/Improve the responsibilities of Build Cop

### ISSUE THREAD

**Issue by ozevren** [istio/istio#13430]
The current build cop process is not working well. As it stands today, the build cop process is only marginally helpful in improving the flow of PRs and health of quality gates.

We need to ensure that the rules/responsibility of the Build Cop is clearly defined, and is followed by the people in the rotation.

**Comment by geeknoid** [comment]
What should we do here? We've updated the Wiki with guidance. You had a doc to suggest changing the role and moving some of the build cop responsibilities elsewhere. Do we need to get this doc finished and reviewed by TOC?

**Comment by ozevren** [comment]
I think so. I'll move the doc to Test WG folder and put it in TOC agenda.

**Comment by ozevren** [comment]
In WG leads meeting, we've decided to kill the on-call process. (We probably should wait until the bots can come online though).

Closing this issue.
