### ISSUE TITLE
Security Code Mauve Epic

### ISSUE THREAD

**Issue by myidpt** [istio/istio#13439]
This epic is used to track the Code Mauve work related to the security subsystem for Istio. Work on this epic is to be prioritized with a preference for improvements to Testing And Stability over UX Enhancements.

**Comment by myidpt** [comment]
@wenchenglu @wattli @liminw @diemtvu @JimmyCYJ @quanjielin @lei-tang @incfly @yangminzhu @pitlv2109 
Please link related issues into this one.

**Comment by lei-tang** [comment]
https://github.com/istio/istio/pull/13199

**Comment by lei-tang** [comment]
https://github.com/istio/istio/pull/13253

**Comment by lei-tang** [comment]
https://github.com/istio/istio/pull/13342

**Comment by lei-tang** [comment]
https://github.com/istio/istio/pull/13127

**Comment by lei-tang** [comment]
https://github.com/istio/istio.io/pull/3886

**Comment by lei-tang** [comment]
https://github.com/istio/istio/pull/13304

**Comment by lei-tang** [comment]
https://github.com/istio/istio/pull/13035

**Comment by pitlv2109** [comment]
There is an on going discussion about using `native` env instead of `kube` env if possible (also applies to security tests), starting from https://github.com/istio/istio/pull/13384#issuecomment-484728050
Many (if not all) of our tests are using `kube` env exclusively. We should look at this. cc @lei-tang for code mauve effort

**Comment by lei-tang** [comment]
The integration tests in the k8s environment uses real Istio images. To support the integration tests in the native environment, some components need to be mocked (e.g., k8s api). We need to have a discussion on the resource and priority of supporting security integration tests in the native environment.

**Comment by incfly** [comment]
We should add integration test for node agent on VM with Citadel.

This can just run using native environment. Spawning up native Citadel and node agent, configure a short time TTL, verify the certificate are refreshed.

I envision we need to refactor & improve node agent over next stage. So this can be very helpful.

**Comment by pitlv2109** [comment]
@lei-tang This PR https://github.com/istio/istio/pull/13099 has been merged, which means most of the checking in `Call` in `kube.go` have been removed. We may need to revise the `CheckConnection()` in `connection.go`, i.e. adding checking for port, what it means for a request to be successful (versus network failure, etc.), etc.

**Comment by lei-tang** [comment]
https://github.com/istio/istio/pull/13557

**Comment by lei-tang** [comment]
https://github.com/istio/istio/pull/13628

**Comment by lei-tang** [comment]
#13683

**Comment by lei-tang** [comment]
#13684

**Comment by lei-tang** [comment]
#13685

**Comment by lei-tang** [comment]
https://github.com/istio/tools/pull/151

**Comment by pitlv2109** [comment]
RBAC test tracker is here #14213

**Comment by lei-tang** [comment]
https://github.com/istio/istio/issues/14364

**Comment by lei-tang** [comment]
https://github.com/istio/tools/pull/156

**Comment by JimmyCYJ** [comment]
https://github.com/istio/istio/issues/9177
