### ISSUE TITLE
Automate Long Running Qualification Tests

### ISSUE THREAD

**Issue by ozevren** [istio/istio#13435]
We need to automate the long-running qualification tests, so that they can be used for gating merges between branches.

**Comment by ozevren** [comment]
Update: going through blocking issus.
Currently: Fixing issue: CRD is not applied in first attempt.

**Comment by therealmitchconnors** [comment]
Release qualification tests are automated here: https://github.com/istio/tools/pull/126

**Comment by ozevren** [comment]
Tagging this with test & release label. T&R folks:, feel free to manage this bug as you see fit.

**Comment by howardjohn** [comment]
still desired
