### ISSUE TITLE
The istio-demo.yaml in 1.1.3 will cause OOMKilled

### ISSUE THREAD

**Issue by zqzzq** [istio/istio#13448]
**Bug description**
I updated to 1.1.3 by the istio-demo.yaml, but when I applied this yaml to k8s, the pilot, the ingressgateway, and the egressgateway were all restarted constantly because the OOMKilled, then I found that they are all set to a smaller limit which not set before 1.1.3, so I had to delete the limit, and now everything is fine. So I want to know why set such a small limit? I don't think this limit is necessary.
**Expected behavior**
the pilot, the ingressgateway, and the egressgateway are running normally.
**Steps to reproduce the bug**
install the 1.1.3 with istio-demo.yaml
**Version (include the output of `istioctl version --remote` and `kubectl version`)**
version.BuildInfo{Version:"1.1.3", GitRevision:"d19179769183541c5db473ae8d062ca899abb3be", User:"root", Host:"fbd493e1-5d72-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.2-56-gd191797"}
**How was Istio installed?**
kubectl apply -f istio-demo.yaml
**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by zqzzq** [comment]
I can find this information via  `kubectl -n istio-system describe po istio-pilot-8647cf5859-49bkz` 👍 

> Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Fri, 19 Apr 2019 09:06:16 +0800
      Finished:     Fri, 19 Apr 2019 09:07:59 +0800
    Ready:          False
    Restart Count:  3
    Limits:
      cpu:     100m
      memory:  200Mi
    Requests:
      cpu:      10m
      memory:   100Mi
 
the ingressgateway, and the egressgateway:

> Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    255
      Started:      Fri, 19 Apr 2019 08:59:57 +0800
      Finished:     Fri, 19 Apr 2019 09:05:26 +0800
    Ready:          False
    Restart Count:  1
    Limits:
      cpu:     100m
      memory:  128Mi
    Requests:
      cpu:      10m
      memory:   40Mi

**Comment by zqzzq** [comment]
Here are some discussions #12344

**Comment by howardjohn** [comment]
Are you seeing increases memory usage by the gateways? I don't think we changed their limits recently

**Comment by ericvn** [comment]
@zqzzq Which environment are you seeing this in? I have several 1.1.3 istio-demo installs and haven't seen this failure.

**Comment by howardjohn** [comment]
Probably has a larger cluster? @zqzzq if you have a large cluster we recommend using the default profile which has performance oriented settings https://istio.io/docs/setup/kubernetes/additional-setup/config-profiles/. The demo is just intended to run on a small cluster and showcase all of Istio's features.

That being said, we may want to raise the limits, we can still keep requests low

**Comment by zqzzq** [comment]
@ericvn @howardjohn My cluster has 368 pods and 273 services, and I always use this file to install and upgrade because it is very convenient, I believe that there are still many people who do this like me. But now due to these limits, this file may cause trouble to some people.

**Comment by howardjohn** [comment]
Fixed by https://github.com/istio/istio/pull/14776
