### ISSUE TITLE
goxbuild: istioctl broken on OSX

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#13444]
Test failure: https://circleci.com/gh/istio/istio/391573?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Its also possible that istioctl isn't broken and that we are just trying to run a osx binary on linux.

**Comment by howardjohn** [comment]
Actually pretty sure its because we run the osx binary on linux @ibm-jason I think it is from the bash script generation

**Comment by howardjohn** [comment]
@ibm-jason do you have a chance to fix this?

**Comment by ibm-jason** [comment]
@howardjohn I hadn't, but it looks like the PR from @tvieira should fix the issue.

**Comment by ericvn** [comment]
It looks like there were at least 3 of us working on a fix and two PRs created.
