### ISSUE TITLE
Multicluster E2E test needs to be on test grid

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#13455]
https://testgrid.k8s.io/istio-presubmits#Summary&width=20 no multicluster test present
@utka @john-a-joyce

**Comment by utka** [comment]
Add it here https://github.com/kubernetes/test-infra/blob/2128cd49ec494b32d99c1f914a831d401365a21b/testgrid/config.yaml#L3074

**Comment by howardjohn** [comment]
@john-a-joyce do you have a chance to make this change?

**Comment by linsun** [comment]
cc @vadimeisenbergibm @ericvn

**Comment by ericvn** [comment]
Will submit a PR once I get the CLA stuff set up for Kubernetes.

**Comment by howardjohn** [comment]
done
