### ISSUE TITLE
[test-framework] Add Native Environment Support for Prometheus

### ISSUE THREAD

**Issue by ozevren** [istio/istio#13467]
We currently have the Kube environment support. We should be able to bring up Prometheus natively and use it in integration testing.

**Comment by Chrischuck** [comment]
I'd be happy to help, but I'm new to OS so I'd need some help as well if that's OK.

**Comment by ozevren** [comment]
It's ok. You can get started by creating a draft/WIP PR (please keep it short) and we can guide you from there. I'd recommend looking at other test components to figure out how to do this.

**Comment by ibm-jason** [comment]
@Chrischuck are you still planning to tackle this one? If not, I'd like to pick this one up and give it a shot.

**Comment by ibm-jason** [comment]
@ozevren I'm going to take a stab at this one. Just finished reading up on the new integration test framework stuff- I'll try to have a draft/WIP PR up soon.

**Comment by hprateek43** [comment]
@ozevren Is someone working on this? If, not, I am picking this up.

**Comment by ozevren** [comment]
@nmittler @duderino

**Comment by nmittler** [comment]
@hprateek43 go for it! :)
