### ISSUE TITLE
Document diff between native env and kube env in the new integration test framework

### ISSUE THREAD

**Issue by pitlv2109** [istio/istio#13462]
**Describe the feature request**
Document the differences (if any) between native env and kube env, limitations of native env compared to kube env if any, etc. in order to make choosing the testing env easier.

**Comment by ozevren** [comment]
The environment is not meant to be chosen by the test author. Ideally, the tests should be written in an envrionment-agnostic way (the components should hide the details of execution for each environment).

Only in an exceptionally small set of cases, it should be legitimate to constraint to a specific environment (i.e. when specifically testing integration with K8s, for example).

**Comment by ozevren** [comment]
We just have a bunch of unimplemented components at this point.

**Comment by pitlv2109** [comment]
>We just have a bunch of unimplemented components at this point.

Any rough ETA of these unimplemented components? I think if the ETA is months, then we should at least have some document to mention the limitations of the `native` env at its current stage.

**Comment by ozevren** [comment]
It should be a community/group effort. If you see something missing, you should help implement it. :)
