### ISSUE TITLE
proposal: move `PILOT_TRACE_SAMPLING`   from pilot env var to global mesh config

### ISSUE THREAD

**Issue by zhongfox** [istio/istio#13468]
I noticed there are 2 config about tracing feature, in 2 separate place:

1. `enableTracing` is in global mesh config, this is from configmap, and located to `/etc/istio/config/mesh`
 
   ```
   # Set enableTracing to false to disable request tracing.
   enableTracing: true
   ```
   
   there is file watcher on `/etc/istio/config/mesh`, so pilot don’t need restart after `enableTracing`  changed

2. the tracing rate config `PILOT_TRACE_SAMPLING`  is in env var of pilot pod, user need restart pilot after change this var.

so is that reasonable to move `PILOT_TRACE_SAMPLING`   from env var to global mesh config?

benefits:
1. all tracing configs are in the one place, easy to maintain
2. avoid restart pilot after user change trace sampling rate.

**Comment by douglas-reid** [comment]
I agree that we should move beyond the environment variable.

However, I don't know that we want to push more into mesh config. I believe we want to have an ability to control this at a more granular level.

I'm working on a general proposal for better tracing API that I hope to share out next week.

**Comment by douglas-reid** [comment]
See: https://discuss.istio.io/t/feedback-requested-proposal-on-adding-tracing-api-to-sidecar/1996

**Comment by linsun** [comment]
mark as no stale bot think this is an important issue to not forget, unless the new operator provides a decent pass for user to change it effectively.

**Comment by douglas-reid** [comment]
This has been addressed in the short term by EnvoyFilter-based approaches.

See: https://github.com/istio/istio/wiki/EnvoyFilter-Samples#tracing-and-access-logging

Closing for now.
