### ISSUE TITLE
New test framework flags not working 

### ISSUE THREAD

**Issue by costinm** [istio/istio#13476]
Trying to run the presubmit tests with:

```
--istio.test.kube.minikube 
--istio.test.kube.systemNamespace istio-control 
--istio.test.nocleanup 
--istio.test.kube.deploy=false
```

I get errors like:

```


flag provided but not defined: -istio.test.kube.systemNamespace
Usage of /usr/local/google/workspace/istio-master/go/out/tmp/go-build537714160/b455/echo.test:

flag provided but not defined: -istio.test.kube.systemNamespace
Usage of /usr/local/google/workspace/istio-master/go/out/tmp/go-build537714160/b467/conversion.test:

```

The 'nocleanup' flag should be included in CircleCI runs - the VM is removed after use,
there is no reason for the tests to uninstall istio.

Since the plan is to ship 1.2 with the modular installer - and we want to be able to
test the operator as well ( which uses different way to install), we should also have 
the 'kube.deploy=false' set for presubmits, and pre-deploy istio demo in the makefile before
starting the pre-submit tests.  The tests should not depend on the mechanism or templates
used to install istio.

**Comment by ozevren** [comment]
Can you give the full command-line?

Different tests require different deployment modes. Just predeploying istio demo wouldn't work. If you want to write a test for deployer, then you can simply not deploy istio during test main.

The new installer should provide a integration component for using it in the rest of the tests.

**Comment by howardjohn** [comment]
@costinm a lot of tests depend on configuring the Istio install via helm. Tests behavior is different for install settings (allow any vs block external for example). How would that work if we don't deploy kube

**Comment by costinm** [comment]
Test command:
```
 /usr/local/go/bin/go test -p 1 -v istio.io/istio/tests/integration/citadel istio.io/istio/tests/integration/echo istio.io/istio/tests/integration/framework istio.io/istio/tests/integration/galley/conversion istio.io/istio/tests/integration/galley/validation istio.io/istio/tests/integration/mixer istio.io/istio/tests/integration/pilot istio.io/istio/tests/integration/pilot/reachabiity istio.io/istio/tests/integration/pilot/security istio.io/istio/tests/integration/security/healthcheck  --istio.test.ci -timeout 30m \
--istio.test.env kube \
--istio.test.kube.config /etc/kubernetes/admin.conf \
--istio.test.hub=istionightly \
--istio.test.tag=release-1.1-latest-daily \
--istio.test.pullpolicy=IfNotPresent       \
--istio.test.kube.minikube --istio.test.kube.systemNamespace istio-control       --istio.test.nocleanup --istio.test.kube.deploy=false

```

**Comment by costinm** [comment]
I just added a TEST_FLAGS option to the test.integration.kube and test.integration.kube.presubmit, 
with the options above - so it can run against an istio installed with the new installer. 

The flag is documented and should be supported - if tests depend on the demo installer they need to be 
marked or excluded.

Since the plan is to ship 1.2 with the new installer - not clear what value there is to run those tests, but 
we can keep running them with the demo installer until they are converted. 

In general tests should not depend on how istio is installed - to test allow any or block it should be possible to create per-namespace config ( destination rule, etc). Same for auth on or off, etc.

We do plan to run the tests against Istio in different configurations - for the global settings that just can't
be avoided, like SDS node agent, or CNI. We can have an install with block external if needed. But the point is that the tests should not modify Istio environment or depend on a specific installer (or if they do - 
we should be able to exclude them).

In any case - the short term issue is that the 'deploy=false' flag and 'systemnamespace' should work
 as documented ( and they do work for most tests - so far only 2 packages seem to lack the systemnamespace)

**Comment by howardjohn** [comment]
How does this sound

* Modify test so that if no setup flag is passed then we skip tests that require special setup
* Ensure only tests that actually require special setup do special set up
* (longer term) switch those that do require special setup to do so using the new installer

**Comment by howardjohn** [comment]
My one concern is disabling the setting makes what we are testing less clear.

For a concrete example, when we test external traffic:

`When we have Istio installed with ALLOW_ANY and the feature flag enabled, and we send an external request -> we get a 200`

This is a very explicit and clear test.


We can simplify this test and make it setup Istio, but with the default settings:

`When we have a default installation, and we send an external request -> we get a 200`

This is still fairly explicit, although it is implicit that we are relying on ALLOW_ANY and the feature flags to be enabled by default.



If we completely skip the setup, we now have:

`If we have any Istio installation, and we send an external request -> ???`

It is impossible to fill in the blank here - there are so many possible combinations of settings that can vary the expected behavior.


So if we do have installation skipped, we should expect that Istio is only installed with defaults, or at the very worst with changes that should have no user impact (ex: CNI probably shouldn't impact any tests)

**Comment by ozevren** [comment]
It should be dead easy to execute tests locally by the developer, which means they need to be self-contained. That has been the goal of the framework. Today, they can be executed using "go test", which is dead obvious and requires no ramp up, no special incantations or understanding of how to run things. Unless the test is broken, it just works. Often, this involves deploying Istio. The test can choose to make changes to the deployment, if they depend on it. Some of the health/security tests already take advantage of this.

Re: moving away from Helm: It should be easy. It requires the installer to be modeled as a test-framework component, just like the current Helm based deployment.

Beyond this, things should be pretty simple, unless I am missing something. We'd like the operator based installer to work off of a CRD. All a test needs to do is to declare the CRD values.yaml that they depend on. The test component can apply this to perform the actual installation. In most cases, where the installation values.yaml will be standard, this should turn out to be a no-op. (I am hoping that the operator will do minimal changes to the running system when a CRD changes.). So it should be immaterial whether there is pre-existing Istio deployment, or whether it is modified by the test. So long as all the tests change the deployment in a declarative manner (through the operator), which turns these into a minimal set of actual changes in the runtime, it should just work.

The only exception to this is the cases where we need to test the installer itself, which presumably requires a clean slate to start with and apply successive values.yaml changes and observe the results. Luckily, with the latest refactoring of the test framework itself, it is easy to write such tests.

**Comment by ozevren** [comment]
@costinm I tried the command-line locally, and I can't repro this. The messages seem to indicate that the test framework flags are not being registered properly.

I have suspicion that some of tests you're pulling as part of that command-line is not opting into the test framework by implementing a proper test main. If some of these are new tests, I'd suggest implmenting proper TestMains.

**Comment by howardjohn** [comment]
I can reproduce:
`go test ./tests/integration/echo/... ./tests/integration/pilot/locality/... -v -p 1 --istio.test.ci --istio.test.env kube --istio.test.kube.minikube --istio.test.nocleanup --istio.test.kube.deploy=false`

Echo runs first, and is native only so doesn't run the `init` that sets up the kube specific flags.

**Comment by ozevren** [comment]
Thanks for catching this.https://github.com/istio/istio/pull/13513

**Comment by costinm** [comment]
@ozevren - it is fine if the tests are "deploying istio" ( or a specific configuration ), however they need to support the flag that is defined and be able to run ( or skip ) and run against a istio deployment created 
by other tools. 

Current tests are running against the demo setup - the 'deploy=false' flag needs to be respected and 
allow the test to run against other install options - like operator, a-la-carte installer, etc.
And since we plan to deprecate the 'demo installer' and move to a-la-carte (1.2) and operator (1.3) - probably the tests should be moved asap to use various profiles of 'a-la-carte'. We can express this as 'environment' - like use 'IstioMinimal', 'IstioFull', etc.

@howardjohn regarding tests that depend on particular defaults, it is perfectly possible now to have
multiple Istio environments available at the same time, and we can create separate environment targets
in the tests framework for things that really require 'global' defaults. However the goal is to minimize 
the 'global' settings, and have more hermetic and self-contained tests. It would be great if the tests for
egress could have per-namespace configs - which is something we need to support and test ( since user may have some namespaces where they want egress on or off ).

We have quite a few configurations we need to tests where Istio install can't be altered by the tests - 
operator for example or k8s add-on or knative. Most tests should be able to run just fine and test the
behavior of those istio installations ( and we are required to test them ).

**Comment by costinm** [comment]
@ostromart  - for add-on/knative and operator related testing

**Comment by ostromart** [comment]
I agree that test should be self-contained, but that doesn't necessarily imply that every test has to install Istio from scratch, or even that the test has to be aware of / turning environment knobs.
We can take the approach of bucketizing tests - the analogy being that Go tests are grouped per package that focus on some area and assume a certain common setup (init/TestMain). 
Similarly, we can group tests by area and come up with an install profile that all those tests assume.
Let's not entangle this with testing the installer itself - non-installer tests can have a static install profile. A separate group of tests can vary the install profile itself but I don't think we should be adding this behavior to most functional tests.

**Comment by ozevren** [comment]
Are you seeing the flags as not being respected? If so, it is a bug and it should be fixed (The last time I tried, they were working, so I am assuming yours is a general comment).

[Generally speaking]
If a developer walks up to a particular folder with tests in it, and run ```go test```, then it should work. This means the test should be able to deploy Istio (components), if need be. If there is an already existing deployment that can satisfy the tests requirements, then it is great and the test should be able to use it. But that can't be the only operating mode.

It boils down to test specifying the particulars of the deployment it needs, and the environment being able to express what it has at the moment. Currently, we have the Helm flags for the former, and the nodeploy flag for the latter. We can do better.

And in my my mind, "better" is being able to make use of the "K8s operator"ness of the operator. I should be able to apply the exact same installer CR and that should result in no changes and I can detect this in an extremely short amount of time. If we have that, then it becomes immaterial if the test is trying to deploy Istio (components). It can simply "overwrite" the existing deployment. It should work for cases where the test needs to do very specific changes to the installation profile as well, as presumably, the operator should be able to do incremental changes to the deployment based on the delta changes coming in with the new CR. 

Is there a counter argument to this? (I might have missed it, but it doesn't look like there is one).

**Comment by ostromart** [comment]
That assumes that the operator will be able to correctly transition between every possible configuration, which is the long term goal but it will take a while to get there. 
From a pragmatic standpoint we probably need more constraint here for the time being. The environment can be specified through operator, but initially O(10) rather than O(100) test environments would be a realistic target (excluding those environments that are part of the installer test itself).

**Comment by kyessenov** [comment]
My 2c: go test is too simplistic for the kind of batching and parallelization that we need. I think it makes sense to group tests by environment to avoid unnecessary transitions between system values. It also makes sense to parallelize tests across environments if there are multiple available.
