### ISSUE TITLE
Need to dynamically add ServiceEntry VM IP addresses in Istio Config

### ISSUE THREAD

**Issue by monubamb** [istio/istio#13485]

**Comment by monubamb** [comment]
I have a scenario wherein AKS-Istio is acting as a front-proxy. The proxy needs to route traffic to Azure VM's which AKS VNET is VNET peered into. What i want to know is how to dynamically add IP address/ports into the ServiceEntry section of istio config for VM's which may come up dynamically based on load.

Also can xCD services of Envoy inside Istio help with it?

Thanks much

**Comment by sdake** [comment]
@monubamb there are some vague ideas to support service entry synthesis in 1.3 release via MCP.  This would automate the SE creation for some scenarios, but not the scenario you describe (which is specifically synthesis in virtual machines).

The MCP protocol is designed to handle this problem, but the work is as I mentioned incomplete and won't make 1.2 and is not available in 1.1.

One option is to write your own controller that listens for service events on the vm, communicates that to the opposing cluster, and creates external SEs there.  This is pretty complicated, but does work.

**Comment by sdake** [comment]
@nmittler ^^

**Comment by monubamb** [comment]
Thank you @sdake. Appreciate the response. The controller part is done (there is a resource manager running on the VM's collecting that information). What i want to know is how do I provide it to the Istio Config.  Also I need a point to point web socket connection between client and the VM's which preserves session affinity(there is stateful VM on the other side).

Below is what i have now and would like to update with dynamic IP/Port Info from the resource manager.

I put a gateway, service entry and virtual service together.

you see those ports, they could by dynamic and i would like to update them from the resource manager into these configurations including gateway. Any help is much appreciated.


**VirtualService**
  http:
      - match:
        - gateways:
          - front-proxy
          port: 80
          uri:
            prefix: /
        route:
        - destination:
            host: 172.16.0.5
            port:
              number: 6004
          weight: 50
        - destination:
            host: 172.16.0.4
            port:
              number: 6005
          weight: 50

**ServiceEntry**
   kind: ServiceEntry
    metadata:
      name: vm2
    spec:
      hosts:
      - 172.16.0.4
      ports:
      - number: 6005
        name: http
        protocol: HTTP
      endpoints:
      - address: 172.16.0.4
        ports: 
          http: 6005
      location: MESH_EXTERNAL

**Gateway -** 
      selector:
        istio: ingressgateway # use istio default ingress gateway
      servers:
      - port:
          number: 80
          name: http
          protocol: HTTP
        hosts:
        - "*"

**Comment by monubamb** [comment]
any comments on ^^

**Comment by monubamb** [comment]
Hello.. Any update on this either way.. If dynamically updating PILOT config is not possible.. that is ok.. but i need to know before we finalize architectural decision.

**Comment by nmittler** [comment]
The Pilot-side work to process synthetic SeviceEntry is ongoing (see #12276). Once implemented, Pilot will be able to handle endpoint updates for the service.  As @sdake suggested, this is all using the MCP protocol, so you'd have to publish these events via an MCP collection.

cc @Nino-K @costinm

**Comment by ozevren** [comment]
I am closing this bug, as it is not actionable by itself. I believe the response that @nmittler provided is the right actionable item for this bug. 
If you disagree, please reopen the bug, with a specific actionable item (i.e. enhancement proposal or bug repro steps).

Thanks
