### ISSUE TITLE
Istio - Mysql Query failure from the Service POD

### ISSUE THREAD

**Issue by karthimohan** [istio/istio#13484]
**Mysql Query fails after certain number of records. Query just stuck in the mysql client**

**We upgraded Istio from 1.0.5 to 1.1.2 and both the service POD and the Mysql POD has istio-proxy container**

When running certain queries Mysql doesnt return the response back to the service. 
Connected to Mysql POD from Mysql-client using service (mysql.dev) and run the same query and the query just gets stuck and does not return anything. But filtering the query limiting the rows, i could get the result. 
If i connect to mysql directly bypassing istio(not connecting via service endpoint) the same query returns the result.
Also disabled Istio for mysql container and i no longer see the issue. Same queries worked with version 1.0.5. This feels like some kind response size limit or buffer limit which i am not sure how to override the default.  

Appreciate any help here

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

istioctl version --remote
client version: version.BuildInfo{Version:"1.1.2", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989", User:"root", Host:"35adf5bb-5570-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.1"}
citadel version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
egressgateway version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-17-g2b13318"}
galley version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
ingressgateway version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-17-g2b13318"}
ingressgateway version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-17-g2b13318"}
pilot version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
policy version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
sidecar-injector version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
telemetry version: version.BuildInfo{Version:"1.1.1", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989-dirty", User:"root", Host:"7077232d-4c6c-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-17-g2b13318"}
public-ingressgateway version: version.BuildInfo{Version:"", GitRevision:"", User:"", Host:"", GolangVersion:"", DockerHub:"", BuildStatus:"", GitTag:""}

kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-28T20:03:09Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.8-eks-7c34c0", GitCommit:"7c34c0d2f2d0f11f397d55a46945193a0e22d8f3", GitTreeState:"clean", BuildDate:"2019-03-01T22:49:39Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

**Istio was installed via helm**

**Comment by 27wyc** [comment]
Got similar problem.

```
$ mysql -hmysql-server -utest -p
Enter password:
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 8215121
Server version: 5.6.36-82.0-log Percona Server (GPL), Release 82.0, Revision 58e846a

Copyright (c) 2009-2017 Percona LLC and/or its affiliates
Copyright (c) 2000, 2017, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> use test_medical
```
with proxyv2:1.1.3

![image](https://user-images.githubusercontent.com/8376288/56578585-93f74600-6600-11e9-8102-b4526f56013b.png)

and with proxy2:1.0.5
![image](https://user-images.githubusercontent.com/8376288/56579107-e4bb6e80-6601-11e9-9b38-0a571e38fd96.png)

**Comment by farcaller** [comment]
Same here. FWIW changing the mysql service port name from `mysql` to `tcp-mysql` fixed it for me with istio's mTLS still enabled, but the [istio docs](https://istio.io/docs/setup/kubernetes/prepare/requirements/) don't name the mysql port as anything special.

**Comment by farcaller** [comment]
And indeed, the envoy on the mysql side has `envoy.filters.network.mysql_proxy` loaded when the port name is `mysql`. Here's some of the envoy logging:

```
mysql-5f9ff684c-nv5nc istio-proxy [2019-04-24 07:18:58.870][31][trace][filter] [external/envoy/source/extensions/filters/network/mysql_proxy/mysql_decoder.cc:140] mysql_proxy: decoding 16384 bytes at offset 16402
mysql-5f9ff684c-nv5nc istio-proxy [2019-04-24 07:18:58.871][31][info][filter] [external/envoy/source/extensions/filters/network/mysql_proxy/mysql_filter.cc:57] mysql_proxy: decoding error: error parsing mysql packet header
```

Apparently envoy fails to parse a mysql packet and that silently stalls the connection.

Why is mysql filter silently enabled in istio with no docs is it's called "alpha"?..

**Comment by farcaller** [comment]
I did the further debugging in the [envoy bug](https://github.com/envoyproxy/envoy/issues/6696).

I guess the current workaround is to not use `mysql` in the service port names.

Istio [pods & services docs](https://istio.io/docs/setup/kubernetes/prepare/requirements/) should be updated to mention the mysql special case (and – preferably – a warning that it's broken).

**Comment by karthimohan** [comment]
@farcaller Changing the mysql service port name from mysql to anyname worked actually. Thanks for the solution. However i disabled Istioproxy for mysql pod when i was facing the issue. So i am puzzled how the above service port name change for mysql helped my application POD with istio enabled to get the full packet without any issue.

**Comment by farcaller** [comment]
@karthimohan no idea, really, disabling the sidecar should have mitigated the issue same good but given renaming the port helped you we seem to be talking about the same issue.

**Comment by Multiply** [comment]
We can also reliably reproduce this behaviour with the latest istio.

Simply changing the port-name to something that doesn't match the mysql filter helps.

**Comment by farcaller** [comment]
This is being handled in https://github.com/istio/istio/issues/13998.
