### ISSUE TITLE
Attributes source.namespace and destination.namespace are "default" instead of "unknown" when source.uid/destination.uid and source.name/destination.name are "unknown".

### ISSUE THREAD

**Issue by tokaplan** [istio/istio#13494]
Mixer OOP adapter is seeing attributes source.namespace and destination.namespace as "default" instead of "unknown" when source.uid/destination.uid and source.name/destination.name are "unknown".

**Expected behavior**
I'm expecting *.namespace to be set to "unknown" as well

**Steps to reproduce the bug**
Repro in default Istio "quickstart" deployment.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
_istioctl version_
Version: 1.0.5
GitRevision: c1707e45e71c75d74bf3a5dec8c7086f32f32fad
User: root@6f6ea1061f2b
Hub: docker.io/istio
GolangVersion: go1.10.4
BuildStatus: Clean

_kubectl version_
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
"Quickstart" installation option.

**Environment where bug was observed (cloud vendor, OS, etc)**
Azure

**Comment by bianpengyuan** [comment]
Do you mind to share you oop adapter related configs?

**Comment by tokaplan** [comment]
Well I'm not sure what's relevant. It's an OOP mixer adapter which receives tracespan instances. Some of the attributes that I'm inspecting are _source.namespace_, _destination.namespace_, _source.uid_, _destination.uid_, _source.name_ _destination.name_.
All values in incoming instances seem to make sense except this one particular aspect described above.

**Comment by douglas-reid** [comment]
Without a bunch more information, I'm not sure how to help debug or address this issue. Given that we are less than two weeks away from the end of support for 1.0 (https://discuss.istio.io/t/support-for-istio-1-0-ends-on-june-19th-2019/2315) and the age of this issue, I'm not sure much more can be done. Closing. Feel free to re-open if the problem persists, especially for more recent versions.
