### ISSUE TITLE
Unable to apply RBAC with multicluster installs

### ISSUE THREAD

**Issue by fnature** [istio/istio#13493]
After I install istio with same steps as either

https://istio.io/docs/examples/multicluster/gke/
or
https://istio.io/docs/setup/kubernetes/install/multicluster/gateways/

RBAC authorization will work when servicerolebinding has
- user: "*"
but not when it has
- user: "cluster.local/ns/default/sa/service-account-name"
  After applyig an authorization, I still receive access denied.

Tested with Istio 1.1.2 in GKE cluster 1.12. 

I posted in
https://discuss.istio.io/t/unable-to-apply-auth-to-service-accounts/1990/8

My install is like `setup-istio-all-gw` in https://github.com/fnature/istio/blob/master/setup-clusters.sh

In comparison, I have no issue when installing istio based on
https://istio.io/docs/setup/kubernetes/install/kubernetes/

Am I missing something here to have RBAC working with the multicluster based installs ?
my goal is to have RBAC with multicluster ..

**Comment by fnature** [comment]
any ideas ?

**Comment by yangminzhu** [comment]
Please see my reply in https://discuss.istio.io/t/unable-to-apply-auth-to-service-accounts/1990/11

I suspect the mTLS is not used between your 2 clusters that's why the `user: "cluster.local/ns/default/sa/service-account-name"` doesn't work, as there is no certificate to provide the identity in this case.

**Comment by fnature** [comment]
Issue resolved after enabling mTLS. 
mTLS is not enabled by default in multicluster installation steps.
