### ISSUE TITLE
EDS STALE (Never Acknowledged) (0%)

### ISSUE THREAD

**Issue by strzelecki-maciek** [istio/istio#13492]
**Bug description**
When running istioctl  proxy-status i see every single record as "STALE (Never Acknowledged) (0%)". Moreover PIlot needs manual killing when i remove ServiceEntries (i am connecting a namespace with istio mtls enabled to a namespace without istio that runs zookeeper/kafka and postgresql;)

**Expected behavior**
The command should report "SYNCED"

**Steps to reproduce the bug** 
Install istio-demo-auth.yaml from 1.1.3 release. Kube cluster was install via kubespray on several nodes. All security groups, firewall rules are disabled between the nodes.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```
client version: version.BuildInfo{Version:"1.1.3", GitRevision:"d19179769183541c5db473ae8d062ca899abb3be", User:"root", Host:"fbd493e1-5d72-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.2-56-gd191797"}
citadel version: version.BuildInfo{Version:"1.1.3", GitRevision:"d19179769183541c5db473ae8d062ca899abb3be-dirty", User:"root", Host:"fbd493e1-5d72-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.2-56-gd191797"}
egressgateway version: version.BuildInfo{Version:"1.1.3", GitRevision:"d19179769183541c5db473ae8d062ca899abb3be", User:"root", Host:"fbd493e1-5d72-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.2-56-gd191797"}
galley version: version.BuildInfo{Version:"1.1.3", GitRevision:"d19179769183541c5db473ae8d062ca899abb3be-dirty", User:"root", Host:"fbd493e1-5d72-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.2-56-gd191797"}
ingressgateway version: version.BuildInfo{Version:"1.1.3", GitRevision:"d19179769183541c5db473ae8d062ca899abb3be", User:"root", Host:"fbd493e1-5d72-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.2-56-gd191797"}
pilot version: version.BuildInfo{Version:"1.1.3", GitRevision:"d19179769183541c5db473ae8d062ca899abb3be-dirty", User:"root", Host:"fbd493e1-5d72-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.2-56-gd191797"}
policy version: version.BuildInfo{Version:"1.1.3", GitRevision:"d19179769183541c5db473ae8d062ca899abb3be-dirty", User:"root", Host:"fbd493e1-5d72-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.2-56-gd191797"}
sidecar-injector version: version.BuildInfo{Version:"1.1.3", GitRevision:"d19179769183541c5db473ae8d062ca899abb3be-dirty", User:"root", Host:"fbd493e1-5d72-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.2-56-gd191797"}
telemetry version: version.BuildInfo{Version:"1.1.3", GitRevision:"d19179769183541c5db473ae8d062ca899abb3be-dirty", User:"root", Host:"fbd493e1-5d72-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.2-56-gd191797"}
```
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-04T04:48:03Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

```

**How was Istio installed?**
1.1.3 release via applying istio-demo-auth.yaml

**Environment where bug was observed (cloud vendor, OS, etc)**
Openstack (T-systems), centos7, kubespray 2.8.3 installation of kubernetes with calico.

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by iftachsc** [comment]
We see this in 1.1.4 after Upgrading from 1.0.6 according to the instructions using helm upgrades path. We see it toggling between this status and synced. So every now and then if u run proxy-status u will see it sometimes synced all (some with 50%) but most of the times we see many STALE (Never Acknowledged). Is this a regression from 1.0.6? I see many hit this but ok the other hand I hear this version is great... not clear. What’s sure is that it’s unpredictable and we have production environments now running 1.0.6 and don’t know what todo. The upgrade in dev environment revealed this

**Comment by esnible** [comment]
Other Issues related to STALE may be duplicates of this one.

https://github.com/istio/istio/issues/13822 STALE (Never Acknowledged) comes & ago every few seconds ...
https://github.com/istio/istio/issues/14522 Cannot see any error logs in pilot but getting errors in prometheus metrics
https://github.com/istio/istio/issues/14336 Scale to zero

**Comment by strzelecki-maciek** [comment]
> We see this in 1.1.4 after Upgrading from 1.0.6 according to the instructions using helm upgrades path. We see it toggling between this status and synced. So every now and then if u run proxy-status u will see it sometimes synced all (some with 50%) but most of the times we see many STALE (Never Acknowledged). Is this a regression from 1.0.6? I see many hit this but ok the other hand I hear this version is great... not clear. What’s sure is that it’s unpredictable and we have production environments now running 1.0.6 and don’t know what todo. The upgrade in dev environment revealed this . We see this under cds and all
> Other columns.

On 1.2.4 i see it still happening. Once i saw proxy-status report all "synced", and pretty much everytime the great majority is STALE. I am running 10 pilots, each 2cpu/2gb. I have more or less 500 istio injected pods spanning 8 namespaces.
