### ISSUE TITLE
support kustomize

### ISSUE THREAD

**Issue by imroc** [istio/istio#13507]
**Describe the feature request**
install istio on kubernetes now support helm and ansible, I think we should support kustomize too, kustomize is getting more and more popular, the newest kubectl also support kustomize, and I think it's a great way to manage kubernetes resources

**Comment by howardjohn** [comment]
We do in https://github.com/istio-ecosystem/istio-installer which will be the new installer in 1.2

**Comment by sdake** [comment]
@imroc if your satisfied with this outcome, please close this issue and leave a comment.  Note we won't be adding features to the 1.1.z (z streams).  This is planned as a new feature for 1.2.  If you want to get involved in the installer development, now is the time :)

Cheers
-steve

**Comment by imroc** [comment]
that sound great
