### ISSUE TITLE
Busybox image not configurable

### ISSUE THREAD

**Issue by nodanero** [istio/istio#13501]
**Bug description**
The location where busybox is downloaded is not configurable.

**Expected behavior**
Busybox image should be configurable.

**Steps to reproduce the bug**
Install Istio with Helm
Prometheus will fail because busybox cannot be downloaded.
**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.1.3

**How was Istio installed?**
With Helm
**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

In a restricted environment an internal docker registry is commonly used, having deployments without configurable image values make it not possible to deploy easily.

**Comment by sdake** [comment]
Depending on how tidy the change is, this should be considered for backport to the 1.1 series.  Not being able to deploy in a firewalled environment is a problem.

@duderino agree?

Cheers
-steve

**Comment by linsun** [comment]
agreed this should be configurable, most of our images are already configurable, think we missed this one.

**Comment by bianpengyuan** [comment]
Init container has been removed. so configurability is no longer needed.
