### ISSUE TITLE
Integration Tests run istio setup even when no tests are run

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#13512]
Run only some tests like: `go test ./tests/integration/... -v -istio.test.env kube --istio.test.ci -p 1 -run TestRBACV2`. All of the tests will install Istio still.

This also happens when we add a skip to all of the tests.

**Comment by jwendell** [comment]
Any reason to close this one? I think it's a valid issue.

**Comment by brian-avery** [comment]
+1. We actually have an entire suite commented out right now because of this. I vote we reopen.

**Comment by howardjohn** [comment]
Sorry I incorrectly thought this was fixed already! reopening
