### ISSUE TITLE
Significant performance degradation with istio-proxy

### ISSUE THREAD

**Issue by huang195** [istio/istio#13517]
**Bug description**

I thought building a new `envoy` binary from istio/proxy (branch `release-1.1`) and putting it into a new image would give me the same setup as if using the official `proxyv2`, but it didn't. There's significant regression in terms of CPU usage and latency.

**Expected behavior**

Expected the `proxyv2` image built from istio/proxy `release-1.1` would give the same result as the official version.

**Steps to reproduce the bug**

- build `envoy` binary from istio/proxy
- run `make docker.proxyv2` in istio/istio to make a new `proxyv2` image
- modify `global.proxy.image` to point to the new `proxyv2` image
- run `fortio` benchmark

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

```
root@haih-istio1:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```
Didn't use `istioctl`

**How was Istio installed?**

helm

**Environment where bug was observed (cloud vendor, OS, etc)**

ubuntu 16.04 VMs

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by huang195** [comment]
Benchmark command:
```
fortio load -qps 1000 -c 20 -t 60s 10.97.103.115:8080
```
With the official proxyv2 image, latency result looks like:
```
# target 50% 0.00264974
# target 75% 0.00370588
# target 90% 0.00635211
# target 99% 0.0168143
# target 99.9% 0.0305868
Sockets used: 20 (for perfect keepalive, would be 20)
Code 200 : 7960 (100.0 %)
Response Header Sizes : count 7960 avg 205.01457 +/- 0.1198 min 205 max 206 sum 1631916
Response Body/Total Sizes : count 7960 avg 205.01457 +/- 0.1198 min 205 max 206 sum 1631916
All done 7960 calls (plus 20 warmup) 3.514 ms avg, 1001.6 qps
```

With the custom build `proxyv2` image (no code changes, just the `release-1.1` branch from istio/proxy), the latency result looks like:
```
# target 50% 0.00824729
# target 75% 0.011379
# target 90% 0.0211115
# target 99% 0.0412288
# target 99.9% 0.0652941
Sockets used: 20 (for perfect keepalive, would be 20)
Code 200 : 60000 (100.0 %)
Response Header Sizes : count 60000 avg 205.05243 +/- 0.2229 min 205 max 206 sum 12303146
Response Body/Total Sizes : count 60000 avg 205.05243 +/- 0.2229 min 205 max 206 sum 12303146
All done 60000 calls (plus 20 warmup) 10.632 ms avg, 999.2 qps
```

**Comment by howardjohn** [comment]
What version of the official image are you using? 1.1.3?

**Comment by mandarjog** [comment]
You need to create a release build ‘-c release’ to produce optimized code.
Otherwise a debug image is produced.

**Comment by huang195** [comment]
@howardjohn the official image I was using was `image: gcr.io/istio-release/proxyv2:release-1.1-latest-daily`, which had good performance. The custom built one had issues, but as @mandarjog mentioned, I could have been using an optimized code. The documentation in istio/proxy is pretty lacking as I couldn't find any instruction on how to build the code, let alone optimized one vs. unoptimized one. 

Question: the flag '-c release' mentioned above is a flag passed to which command?

**Comment by huang195** [comment]
OK, got it. I think you meant '-c opt' that gets passed to `bazel build` comand. After making the change, latency number from the custom build proxyv2 matches that of the official image. Thanks @mandarjog for pointing this out. It would be nice to have this documented somewhere for folks who's tinkering with these envoy filters (unless I missed the document somewhere).
