### ISSUE TITLE
expose DNS / ExternalName in test framework

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#13527]
OOP LB depends on gRPC DNS round robin balancing. For that we need to have a DNS server running that exposes several endpoints for an OOP adapter. We need an ability to either mock ExternalName services or run a native DNS server in the framework.

/assign @nmittler 
/assign @ozevren 
for re-assignment

**Comment by howardjohn** [comment]
@kyessenov is this still something we are interested in?

**Comment by kyessenov** [comment]
I think so. This is basically requesting an ability to exercise DNS dependent behavior.
