### ISSUE TITLE
CNI Not published in 1.2 release archive

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#13526]
CNI chart is not included in the 1.1.3 release, but it is in previous releases and [docs](https://istio.io/docs/setup/kubernetes/additional-setup/cni) still reference it

 ```
$ wget https://github.com/istio/istio/releases/download/1.1.2/istio-1.1.2-linux.tar.gz && tar xvf istio-1.1.2-linux.tar.gz && find -name "*cni*"./istio-1.1.2/install/kubernetes/helm/charts/istio-cni-0.1.0.tgz
...
./istio-1.1.2/install/kubernetes/helm/charts/istio-cni-0.1.0.tgz


$ wget https://github.com/istio/istio/releases/download/1.1.3/istio-1.1.3-linux.tar.gz && tar xvf istio-1.1.3-linux.tar.gz && find -name "*cni*"
<NO OUTPUT>
```

**Comment by utka** [comment]
The  folder /charts  under install/kubernetes/helm is not present. But it actually looks to me, like that how it is suppose to be, under helm there is already istio and istio-init, with correct tag and hub values.
Meanwhile under 1.1.2 the /charts folder contains tar.gz files with incorrect values.

The only issue is CNI is still missing in /helm folder

**Comment by tiswanso** [comment]
<ugh so much thrashing on this helm stuff>  This has changed several times in the 1.1 timeframe.  I can't keep up with where things stand with it... I know at one point this script was what updated the chart repo:  https://github.com/istio/istio/blob/release-1.1/release/gcb/helm_charts.sh#L30-L53

But I guess there's something else that creates the release tarball and we need the same type of code for that.

**Comment by utka** [comment]
@tiswanso  The code you pointed to is adding cni to release/charts, but does not add it to -linux.tar.gz files. Working on fixing it.

**Comment by utka** [comment]
This looks incorrect https://github.com/istio/istio/blob/9f57f080bb8fa239643a0265769f0cf5dd8e79d9/release/gcb/helm_charts.sh#L31
Getting master even for release 1.1

**Comment by tiswanso** [comment]
It's correct... since no one has merged #12186 there is no release-1.1 tagged image for CNI in gcr.io/istio-release.  Anyway, it's exactly the same content in release-1.1 and master for istio/cni.  In istio/cni we CI test every PR against both istio master and release-1.1.

**Comment by tiswanso** [comment]
@utka -- actually, we should probably change it to checkout the release branch but it's not urgent (will have little/no net effect) for the reasons I mention.  I was thinking more of the HUB and TAG settings in the helm chart.  Do you want to do that now or in a follow on PR?  Is there a release branch env var that this type of code could use?

**Comment by mobilitie** [comment]
I ran into two issues when installed with CNI 
1) tar build file doesn't exist as mentioned in docs for both 1.1.3 and 1.1.4 ( Too BAD  )
2) Gallery, policy and telemetry pods go into crashbackloop because it doesnt have communication to proxy , probably because of CRD's, which i thought was part of istio-init 

There could be 1 or 2 extra steps but below are the sequential  manual steps i followed to get CNI worked
```
# Download CNI repo to manually build with HELM
git clone https://github.com/istio/cni.git
cd cni
helm init
helm package deployments/kubernetes/install/helm/istio-cni

 cd 
curl -L https://git.io/getLatestIstio | ISTIO_VERSION=1.1.4 sh -
cd istio-1.1.4
export PATH=$PWD/bin:$PATH
helm repo add istio.io https://storage.googleapis.com/istio-release/releases/1.1.4/charts/
mkdir -p install/kubernetes/helm/charts
kubectl create namespace istio-system
cp ../cni/istio-cni*.tgz install/kubernetes/helm/charts
tar -xzf install/kubernetes/helm/charts/istio-cni-*.tgz -C install/kubernetes/helm/

#Adding CRD's from init so gallery pod wont fail
for i in install/kubernetes/helm/istio-init/files/crd*yaml; do kubectl apply -f $i; done

kubectl apply -f install/kubernetes/helm/helm-service-account.yaml

helm install install/kubernetes/helm/istio-cni --name=istio-cni --namespace=istio-system
kubectl get pods,svc,deployments -n istio-system

#<<WAIT>>kubectl 
sleep 30s


curl -L https://github.com/knative/serving/releases/download/v0.5.2/istio-crds.yaml \
  | kubectl apply --filename -



helm template install/kubernetes/helm/istio --name istio --namespace istio-system \
  --set istio_cni.enabled=true | kubectl apply -f -

kubectl get pods,svc,deployments -n istio-system
```

**Comment by howardjohn** [comment]
Need to get https://github.com/istio/istio/pull/13615 into 1.2

**Comment by duderino** [comment]
I'm hoping either @rlenglet or @tiswanso (or both) can assume these responsibilities.  It's area specific and if @utka has to do it then we're stealing too much away from cross-area work (Prow, etc etc)

**Comment by howardjohn** [comment]
This is merged via https://github.com/istio/istio/pull/14756

P0 is updating docs for this https://github.com/istio/istio.io/issues/4327
