### ISSUE TITLE
Grafana UI do not load any data

### ISSUE THREAD

**Issue by viharikrishna** [istio/istio#13533]
I've the Prometheus UI loading data and also data source with in Grafana working. But for some reason Grafana UI doesn't load any data.
Any suggestions on where to look for?

**Comment by howardjohn** [comment]
Can you provide some more information? What error messages are there? How did you install? 

Without any info we cannot help you

**Comment by viharikrishna** [comment]
Hello howardjohn

Setup we have is Istio, gRPC running on GKE for handling Millions of RPS.
We are using Isito’s build-in monitoring framework with Prometheus, Grafana and following instructions as mentioned in https://istio.io/docs/tasks/telemetry/metrics/querying-metrics/ and https://istio.io/docs/tasks/telemetry/metrics/using-istio-dashboard/

Prometheus version - image: docker.io/prom/prometheus:v2.3.1
Grafana - I don’t see it in the UI anywhere
Istio - 1.1.1

Prometheus seems to be working fine.. All the targets are up

![image](https://user-images.githubusercontent.com/23062111/56599401-561c0280-65ab-11e9-8286-e7179b327c97.png)

![image](https://user-images.githubusercontent.com/23062111/56599458-72b83a80-65ab-11e9-85a6-208cd15ae3e2.png)


￼However, Grafana doesn’t load any data.
￼
![image](https://user-images.githubusercontent.com/23062111/56599474-78ae1b80-65ab-11e9-9b44-47de652e2eb0.png)

￼
![image](https://user-images.githubusercontent.com/23062111/56599479-7c41a280-65ab-11e9-9dc5-97b3592c0f9f.png)


Datasource is valid here and says it’s working
￼
![image](https://user-images.githubusercontent.com/23062111/56599489-819eed00-65ab-11e9-932d-c9cc3882f6a9.png)

**Comment by howardjohn** [comment]
Thanks for the info @douglas-reid can you help or direct to someone who can?

**Comment by douglas-reid** [comment]
What happens if you issue some of the queries in the dashboard directly against Prometheus?  Even just something simple like `sum(istio_requests_total)` ?

Do you have live traffic for the time period in which you are looking in the dashboard?

What do the Mixer metrics look like in Prometheus (`grpc_io_server_completed_rpcs{grpc_server_method="istio.mixer.v1.Mixer/Report"} `)?

Have you gone through the Help documentation: https://istio.io/help/ops/telemetry/missing-metrics/ ?

**Comment by viharikrishna** [comment]
@douglas-reid 

Yes, We are sending 1million RPS to gRPC server on Istio/GKE and it shows up on Stackdriver. 

sum(istio_requests_total) doesn't execute any data. 

(grpc_io_server_completed_rpcs{grpc_server_method="istio.mixer.v1.Mixer/Report"} )
![image](https://user-images.githubusercontent.com/23062111/56601688-aa75b100-65b0-11e9-9244-6a983fc116c3.png)

I did verified the outputs of the commands as per the documentation. Seems to be fine.

**Comment by douglas-reid** [comment]
So wait, you are using both Stackdriver and Prometheus?

How did you install Istio?

Not having any `istio_requests_total` to me suggests that the Prometheus adapter isn't properly configured, but more info is needed.

**Comment by douglas-reid** [comment]
As there has been over a month between last communication, I'm going to close this issue. If there is more that can be done, please feel free to reopen.

**Comment by kjanshair** [comment]
I'm using Istio on EKS. I don't see element `grpc_io_server_completed_rpcs` in the `http://localhost:15014/metrics` as described in the first section of the [docs](https://istio.io/docs/ops/telemetry/missing-metrics/#verify-mixer-is-receiving-report-calls). This might be the reason I see missing metrics in Grafana dashboards.

Kubernetes: v1.13
Istio: v1.2.4

My way of installing Istio:

```
helm install install/kubernetes/helm/istio-init --name istio-init --namespace istio-system
```

```
helm install install/kubernetes/helm/istio --name istio --namespace istio-system --set global.configValidation=false --set sidecarInjectorWebhook.enabled=true --set grafana.enabled=true --set servicegraph.enabled=true
```

**Comment by kjanshair** [comment]
Also I see below error in the first install:

```
kubectl describe pod istio-telemetry-77797d4d8-d85lt -n istio-system
```
```
Events:
  Type     Reason     Age                From                                                 Message
  ----     ------     ----               ----                                                 -------
  Normal   Scheduled  51s                default-scheduler                                    Successfully assigned istio-system/istio-telemetry-77797d4d8-d85lt to ip-10-0-122-254.us-west-2.compute.internal
  Normal   Pulled     46s                kubelet, ip-10-0-122-254.us-west-2.compute.internal  Container image "docker.io/istio/mixer:1.2.4" already present on machine
  Normal   Created    46s                kubelet, ip-10-0-122-254.us-west-2.compute.internal  Created container
  Normal   Started    46s                kubelet, ip-10-0-122-254.us-west-2.compute.internal  Started container
  Normal   Pulled     46s                kubelet, ip-10-0-122-254.us-west-2.compute.internal  Container image "docker.io/istio/proxyv2:1.2.4" already present on machine
  Normal   Created    46s                kubelet, ip-10-0-122-254.us-west-2.compute.internal  Created container
  Normal   Started    46s                kubelet, ip-10-0-122-254.us-west-2.compute.internal  Started container
  Warning  Unhealthy  34s (x2 over 39s)  kubelet, ip-10-0-122-254.us-west-2.compute.internal  Liveness probe failed: Get http://10.0.79.129:15014/version: dial tcp 10.0.79.129:15014: connect: connection refused

```
