### ISSUE TITLE
Test framework Echo component https/grpc broken

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#13530]
`instance.go:121: failed calling a->'https://b:34431/': rpc error: code = Unknown desc = Get https://127.0.0.1:34805: http: server gave HTTP response to HTTPS client`

Anytime a call over https is made

I am looking into it @nmittler, but if you have any pointers that would be useful

**Comment by howardjohn** [comment]
GRPC also fails
```
        instance.go:121: failed calling a->'grpc://b:41555/': rpc error: code = Unknown desc = context deadline exceeded

```

**Comment by howardjohn** [comment]
GRPC issue is with the framework, https seems to be with echo client/server itself:

```
pkg-test-application-echo-client -url https://localhost:8080
2019-04-22T22:53:56.822751Z     info    Error Get https://localhost:8080: http: server gave HTTP response to HTTPS client
```

**Comment by howardjohn** [comment]
Part of the GRPC issue is the timeout will be 0 if you don't explicitly set it, but even with that fix still had errors

**Comment by nmittler** [comment]
FYI I'm having similar issues in echo right now. Ongoing work in #13586

**Comment by nmittler** [comment]
@howardjohn remind me, was this issue created before or after the migration to docker for native testing?

**Comment by howardjohn** [comment]
This was before moving to docker. I think we have some grpc tests now, so this may be fixed?

**Comment by nmittler** [comment]
Yeah I think it's resolved now. Closing.
