### ISSUE TITLE
Whether you can add a layer of custom interceptor

### ISSUE THREAD

**Issue by An0nymous0** [istio/istio#13543]
**Describe the feature request**

Whether you can add a layer of custom interceptor, you can customize the pointing service to handle complex interception requests. It can also be written in a language that you are familiar with, similar to the Spring Interceptor feature.

**Describe alternatives you've considered**

Mixer Adapter

But the Mixer Adapter is too dependent on the language and the developer.

**Additional context**

**Comment by howardjohn** [comment]
@douglas-reid can you direct this to the right people/get follow up info needed?

**Comment by douglas-reid** [comment]
I believe this FR is related to some of the motivations behind Mixer V2.

/cc @mandarjog

**Comment by douglas-reid** [comment]
I'm going to close this issue. There is on-going design work to allow flexible extension of behavior within the proxy. Outside of the proxy, there are out-of-process adapters that can be written in any language, and are capable of handling some complex logic.

**Comment by An0nymous0** [comment]
cheer
