### ISSUE TITLE
How to config yaml when a http-proxy visit a grpc service in another pod.

### ISSUE THREAD

**Issue by jmzwcn** [istio/istio#13541]
A api-gateway expose 8080, it will proxy a grpc service with 50051.
I hit '{"error":"stream terminated by RST_STREAM with error code: PROTOCOL_ERROR","code":500}' problem.

yaml is as follows:
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: nevis-system
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    nevis.io/service: api-gateway
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    nevis.io/service: api-gateway
  name: api-gateway
  namespace: nevis-system
spec:
  selector:
    matchLabels:
      nevis.io/service: api-gateway
  template:
    metadata:
      labels:
        nevis.io/service: api-gateway
    spec:
      containers:
      - image: registry.dpool.sina.com.cn/nevis-system/api-gateway:74b3539-190418113253
        imagePullPolicy: Always
        name: api-gateway
        ports:
        - containerPort: 8080
          protocol: TCP

any help?

**Comment by xiongxiaoxx** [comment]
@jmzwcn How did you solve this?  I meet the same problem
