### ISSUE TITLE
tune rolling update strategy for istio

### ISSUE THREAD

**Issue by linsun** [istio/istio#13552]
our current strategy is

  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

I don't think that is as efficient as using percentage as it doesn't count towards number of replicas.

We should revisit this:

https://medium.com/kokster/updating-kubernetes-deployments-867421d4e337

@Stono shared his config that he didn't get 503 during istio update (at least not caused by istio):

  yaml['spec']['strategy'] = {
    "type" => "RollingUpdate",
    "rollingUpdate" => {
      "maxUnavailable" => "25%",
      "maxSurge" => "100%"
    }
  }

**Comment by Stono** [comment]
Hey.
I'd probably suggest making it user configurable as it's largely down to personal preference.

We run 3 pilot instances and prefer 100% burst, then scale down the old as it helps to keep the load more evenly spread across the new instances of pilot (from proxy reconnections).

**Comment by linsun** [comment]
good point, yea configurable seems reasonable too, along with a reasonable default.

**Comment by linsun** [comment]
cc @morvencao if you have bandwidth to add this.
