### ISSUE TITLE
Pilot MCP sink shouldn't expect all collection types from source server

### ISSUE THREAD

**Issue by ndhanushkodi** [istio/istio#13559]
**Describe the feature request**
When the source server only provides a subset of collections (e.g. istio/networking/v1alpha3/VirtualService), pilot operates on just the data provided, without throwing this error for the collections not in the subset `Error receiving MCP response: rpc error: code = InvalidArgument desc = unsupported collection "istio/mixer/v1/config/client/quotaspecs"`. 

**Describe alternatives you've considered**
The source server would have to send empty collection resources for all of the collections not being used. As new collection types are added, source servers for MCP resources need to send empty resources for these as well.

**Comment by Nino-K** [comment]
I think it is reasonable to configure Pilot to only support (listen for) types that source can provide. This could also be a configuration where default is all the istio config types so we can guarantee that it will not impact config path for galley or other components if one decides not to provide this config property. @ozevren & @ayj WDYT?

**Comment by ndhanushkodi** [comment]
We are going to start working on a PR to configure pilot to listen for specific config types, with the default being all config types, as @Nino-K mentioned. 

In the long term, we'd like to discuss a potential change to MCP itself to have sinks discover the config types supported by a source server.

**Comment by ozevren** [comment]
Discovery is something we have discussed in the past. I think it is reasonable have a collection that will serve discoverability metadata.

I am a bit worried about serving empty collections when the source is not serving the requested collection. This is likely to be an indicator of misconfiguration and it is harder to diagnose when looking from only one side (i.e. just Pilot logs).

**Comment by costinm** [comment]
Let's not make this even more complex without a reason. 
Pilot asks for all the things it cares about. 
The MCP server should send empty result if it doesn't have any resource of that type ( including if the CRD is missing or it's something it doesn't know about ). 

Simple and easy.

**Comment by ndhanushkodi** [comment]
We think that if we leave it this way, in a world where there are multiple MCP servers sending Pilot configuration, every MCP server would have to know to send these empty results, so they would break anytime Pilot starts requesting a new resource type. 

It seems like the goal of MCP servers is so that unique configuration can be sent to Pilot, and requiring all MCP servers to implement the full set of configuration types that Pilot is _capable_ of accepting doesn't line up with this goal. It would be a breaking change to Pilot every time new configuration was added.

Let us know what you think, and if we have the wrong idea.

**Comment by Nino-K** [comment]
We need to consider the fact that not all the environments (K8s, CF, Consul, etc) are equal in the type of configuration they provide. Having a source that sends empty resources to bypass MCP errors does not seem very semantic. Discovery process seems very reasonable where a source and a server can establish a contract on what collection types they should exchange. Also, this will solidify the MCP contract and increases the efficiency (potentially) between source and the server and perhaps makes debugging less cumbersome. Currently, MCP controller initializes with an assumption that the source is going to provide all istio config types, but in the case of CloudFoundry, there are only a handful of types (ServiceEntries, Virtual Services, Gateways and destination rules) that are currently useful to the environment. For other types CF source server is forced to forward an empty resource. This also introduces code instability where the source server code has to change/break every time a new type is introduced in pilot.

**Comment by ndhanushkodi** [comment]
Do you all think you'd consider a PR  at this point with configuring Pilot with config types to start with, and at the next config working group meeting we can bring up the possibility of discovery for resource types for the long term?

**Comment by XanderStrike** [comment]
In the config meeting, a third option was proposed:

Pilot could handle `unsupported collection` errors, and assume that that means the configuration source doesn't support that configuration type. Then Pilot could report that configuration type as synced and not attempt to retrieve configuration for that type from that source again.

This reduces the configuration burden while still satisfying our use case, but also has the risk of suppressing real errors. We will compile a proposal based on the options in this issue.

**Comment by howardjohn** [comment]
> We think that if we leave it this way, in a world where there are multiple MCP servers sending Pilot configuration, every MCP server would have to know to send these empty results, so they would break anytime Pilot starts requesting a new resource type.

I am not sure why this is the case? The source shouldn't need a special case for every resource type. If a source only new about VS and SE, can it just have code like

```go
switch resourcetype {
  case VS: send []{list of virtual service}
  case SE: send []{list of service entry}
  default: send empty list
}
```

@sushicw this is the issue I was referring to

**Comment by howardjohn** [comment]
Not that this introduces a strong coupling between the MCP source and sink, where the source MUST upgrade first when new resources are introduced. In the standard Istio case this means you need to upgrade galley before Pilot. Most users are not actually doing this and just upgrading everything at once and hoping things will work out.

**Comment by ayj** [comment]
Unsupported collections can occur as transient or permanent errors. Transient errors occur during upgrade/downgrade and should _eventually_ resolve. Service may be disrupted until source/sink agree again. Permanent errors occur in CF-type use cases. Here are the solutions I've seen proposed so far:

1) source provides an explicit list of supported collections as a collection itself (i.e. a meta-collection per @ozevren's suggestion). 
2) source returns "collection not supported error" if sink requests an unsupported collection.
3) source returns empty collection for unsupported collections.

(1) is the most complex and most explicit. Requires code changes to source and sink.

(2) is also explicit and is what we support today. Requires minimal code changes to sink if we want to skip over unsupported collections.

(3) requires the least amount of code change. It's also the least explicit. The client can't differentiate unsupported from empty collections. Requires minimal code changes to source.

I'd argue for enhancing (2) with better sink/client handling of unsupported collections. It's simpler than (1) and doesn't hide errors like (3). In practice, MCP connections will reset when either source or sink is upgraded, giving an opportunity for the list of supported collections to be reset. (2) could be further enhanced so that the sink doesn't request collections it knows it doesn't need (CF case).

**Comment by ayj** [comment]
@XanderStrike, you marked this as staleproof. Were you interested in pursuing one of the options suggested above?

**Comment by XanderStrike** [comment]
I marked it as staleproof because an issue doesn't stop being an issue just because nobody has the bandwidth to work on it. That system is bad.

We would prefer 2, but have changed priorities since the issue was created and we're likely not going to pick up this work any time soon.

**Comment by esnible** [comment]
Can I retarget this for 1.6?  Who is working on it?

**Comment by ayj** [comment]
IMO this is lower priority with istiod. It may be worth reconsidering if someone wants implement option 2.

**Comment by howardjohn** [comment]
Given our current plans moving away from MCP I don't think we will implement this
