### ISSUE TITLE
JWT scope support does not support space delimted format

### ISSUE THREAD

**Issue by joberdick** [istio/istio#13565]
**Bug description**
Currently, policies with JWT scopes only support an array.. That is actually not how the scope claim is to be implemented by spec: https://tools.ietf.org/html/rfc6749#page-23

The official way is via a single string that is space delimited. This is causing issues with token issuers that only support generating tokens via space delimited, such as Auth0.

**Some clarification: it seems the the RFC only specifies the client side to request a scope, but using space delimited in the scope claim of the access token seems valid.**

Can we consider extending the functionality to support space delimited?

**Expected behavior**
Scope claims with space delimited scopes work same as array.

**Comment by yangminzhu** [comment]
I think we can add this support, @liminw @lei-tang Any thoughts?

**Comment by yangminzhu** [comment]
I'll take this and work on the implementation, hopefully we can deliver this in 1.3 release.

**Comment by yangminzhu** [comment]
@andrewjjenkins Oh sorry I haven't had time to work on this and is currently busy with the authz-v2 stuff. I will see if we can spend sometime on it this week.

**Comment by yangminzhu** [comment]
@andrewridout @joberdick This should be supported in 1.4 which should be released in Nov. Reopen to keep tracking as I will add some e2e tests in Istio.

**Comment by howardjohn** [comment]
@yangminzhu did you ever add tests for this?

**Comment by yangminzhu** [comment]
@howardjohn No I haven't, the original PR includes test in the proxy repo, but I think we should still add some tests in the istio repo, will do this soon.
