### ISSUE TITLE
support istio quota config: write quota name/amount in Envoy mixer filter

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1356]
@qiwzhang commented on [Wed Sep 06 2017](https://github.com/istio/old_pilot_repo/issues/1186)

Now "RequestCount" quota is hard coded in the Envoy Mixer HTTP filter config.   Pilot needs to process istio quota config, and write quota name/amount for each metric in Envoy mixer filter.

---

@kyessenov commented on [Sat Sep 09 2017](https://github.com/istio/old_pilot_repo/issues/1186#issuecomment-328309148)

What is the scope of the quota name? Per service, per namespace, per cluster?

**Comment by douglas-reid** [comment]
@mandarjog can you provide an update here?

**Comment by mandarjog** [comment]
When specific quota bindings are configured, they are already injected in the configuration.

**Comment by qiwzhang** [comment]
This is fixed.  Quota config is defined here https://github.com/istio/api/blob/master/mixer/v1/config/client/quota.proto

It is pushed to Envoy by Pilot
