### ISSUE TITLE
Fix the breakage of mesh expansion due to IsValidIP in iptables-start.sh

### ISSUE THREAD

**Issue by incfly** [istio/istio#13562]
**Bug description**
Mesh expansion does not work due to #13291 

1. iptable-starts.sh stops on a mesh expansion VM instance. 
1. Cluster.env file is
```bash
ISTIO_SERVICE_CIDR=10.43.240.0/20
ISTIO_SYSTEM_NAMESPACE=istio-system
ISTIO_CP_AUTH=MUTUAL_TLS
```

**Expected behavior**
istio-sidecar.deb package after installed on a VM, we are able to start Envoy side car. 

**Steps to reproduce the bug**

1. Build sidecar Debian package, install it on a VM. 
1. `iptable-start.sh` will fail at `IsValidIP` function

```bash
function isValidIP() {
   if [ "$1" != "${1#*[0-9].[0-9].[0-9].[0-9]}" ]; then
      true
   elif [ "$1" != "${1#*:[0-9a-fA-F]}" ]; then
      true
   else
      echo "not valid ip $1"
   fi
}
isValidIP "10.3.240.0"
```
output not valid ip 10.3.240.0, and the iptable setups stops.

More description can be found at https://github.com/istio/istio/pull/13291#issuecomment-486001220

**Comment by incfly** [comment]
Apart from the fix, I really think we should invest less on bash script... They are hard to be unit testable and maintain and syntax is quirky, IMHO. We've already have 500+ LOC of iptables.sh

For this particular case, we might need to live with what currently have, but we should really starts thinking about better language(python, e.g) for new tasks like this.

fyi @utka @kyessenov @louiscryan ...

**Comment by kyessenov** [comment]
Besides the choice of the language, what is missing is testing with a sufficient functional coverage.

**Comment by sbezverk** [comment]
@incfly Agree 100%, I would love to refactor it into a nice go code with bunch of unit tests ;)

**Comment by incfly** [comment]
@kyessenov yup on testing coverage. I actually find the issue when writing e2e test for mesh expansion. I will add that to our PR gate. I just think switching to a more maintainable language still benefit us additionally.
