### ISSUE TITLE
Investigate spurious cert change events

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1357]
@ldemailly commented on [Thu Sep 14 2017](https://github.com/istio/old_pilot_repo/issues/1277)

Investigate spurious cert change events
```
W0915 03:19:54.388] W0915 03:15:46.863128       1 cert.go:70] failed to read file "/etc/istio/ingress-certs/tls.crt"
W0915 03:19:54.388] W0915 03:15:46.863147       1 cert.go:70] failed to read file "/etc/istio/ingress-certs/tls.key"
W0915 03:19:54.389] I0915 03:15:46.863620       1 cert.go:51] Change to "/etc/certs/" is detected, reload the proxy if necessary
W0915 03:19:54.389] W0915 03:15:46.863700       1 cert.go:70] failed to read file "/etc/istio/ingress-certs/tls.crt"
W0915 03:19:54.389] W0915 03:15:46.863708       1 cert.go:70] failed to read file "/etc/istio/ingress-certs/tls.key"
W0915 03:19:54.389] I0915 03:15:46.863745       1 cert.go:51] Change to "/etc/certs/" is detected, reload the proxy if necessary
W0915 03:19:54.389] W0915 03:15:46.863870       1 cert.go:70] failed to read file "/etc/istio/ingress-certs/tls.crt"
W0915 03:19:54.389] W0915 03:15:46.863903       1 cert.go:70] failed to read file "/etc/istio/ingress-certs/tls.key"
W0915 03:19:54.389] I0915 03:15:46.863916       1 cert.go:51] Change to "/etc/certs/" is detected, reload the proxy if necessary
W0915 03:19:54.390] W0915 03:15:46.863965       1 cert.go:70] failed to read file "/etc/istio/ingress-certs/tls.crt"
W0915 03:19:54.390] W0915 03:15:46.863977       1 cert.go:70] failed to read file "/etc/istio/ingress-certs/tls.key"
W0915 03:19:54.390] I0915 03:15:46.864052       1 cert.go:51] Change to "/etc/certs/" is detected, reload the proxy if necessary
W0915 03:19:54.390] W0915 03:15:46.864139       1 cert.go:70] failed to read file "/etc/istio/ingress-certs/tls.crt"
W0915 03:19:54.390] W0915 03:15:46.864150       1 cert.go:70] failed to read file "/etc/istio/ingress-certs/tls.key"
```
also would be great to have a test confirming that no errors occur early at startup (that we don't show anything ready/available for serving traffic before it is actually available)

---

@ldemailly commented on [Thu Sep 14 2017](https://github.com/istio/old_pilot_repo/issues/1277#issuecomment-329672146)

seen in https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/819/e2e-suite-rbac-auth/608/?log#log

---

@ldemailly commented on [Thu Sep 14 2017](https://github.com/istio/old_pilot_repo/issues/1277#issuecomment-329672237)

See also https://github.com/kubernetes/kubernetes/issues/50345 [pointer from @kyessenov , thx!]

---

@kyessenov commented on [Thu Sep 14 2017](https://github.com/istio/old_pilot_repo/issues/1277#issuecomment-329672873)

@lookuptable @myidpt any idea why fsnotify is spamming when there is no seeming change to certs?

---

@myidpt commented on [Thu Sep 14 2017](https://github.com/istio/old_pilot_repo/issues/1277#issuecomment-329698148)

I'm not sure. I guess any change to the directory / files inode will be detected by fsnotify, and Kubelet is continuously reading? Does this spam stop after all the certs are successfully mounted?

I'll investigate more tomorrow.

---

@kyessenov commented on [Thu Sep 21 2017](https://github.com/istio/old_pilot_repo/issues/1277#issuecomment-331272905)

@myidpt can you please install a rate limit between fsnotify and proxy agent? it's causing unnecessary races by triggering restarts halfway through updating files.

cc @mandarjog

**Comment by rshriram** [comment]
This issue is almost a year old. Cna it be reproduced ? @ldemailly . If not, I am going to close it.

**Comment by ldemailly** [comment]
has SDS been implemented ? if so I guess this can be closed; the logging isn't in the code base anymore so it won't log for sure but maybe it still restarts envoy more often than needed (and cause issues during restart) - do we have metrics on envoy restarts by pilot agent?

**Comment by louiscryan** [comment]
@myidpt can you triage this and either close or assign appropriate milestone & priority
