### ISSUE TITLE
Amend documentation about proxy settings - automatic sidecar injection issue in istio.io/help

### ISSUE THREAD

**Issue by Baykonur** [istio/istio#13575]
**Describe the feature request**
I propose to give an alternative solution to [Automatic sidecar injection fails if the Kubernetes API server has proxy settings](https://istio.io/help/ops/misc/#automatic-sidecar-injection-fails-if-the-kubernetes-api-server-has-proxy-settings) where we did not have the chance to remove the `https_proxy, http_proxy, no_proxy` environmental variables for kube-apiserver because of the IdP we are using. 
Therefore, instead of removing the proxy settings for the cluster, we have added `istio-sidecar-injector.istio-system.svc` (`.svc` also works which is better to use I believe) in the `no_proxy` environmental variable for the kube-apiserver and automatic sidecar injection just worked for the namespaces labelled with `istio-injection=enabled`

**Comment by howardjohn** [comment]
That sounds like an improvement on the current solutions, we would welcome a PR against https://github.com/istio/istio.io to change the docs.

**Comment by howardjohn** [comment]
Fixed in https://github.com/istio/istio.io/pull/4030
