### ISSUE TITLE
istio-initializer fails to initialize jobs

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1359]
@ayj commented on [Wed Oct 11 2017](https://github.com/istio/old_pilot_repo/issues/1439)

istio-initializer fails to initialize jobs. The same job can be properly initialized with `istioctl kube-inject` which suggests this is a problem with the initializer specifically and not the overall injection template.

* Steps to reproduce

```bash
kubectl apply -f install/kubernetes/istio.yaml
kubectl apply -f install/kubernetes/istio-initializer.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes/kubernetes.github.io/master/docs/concepts/workloads/controllers/job.yaml
```
The job creation will timeout. The initializer logs show that the apiserver thinks the pod template is invalid.

```bash
E1011 16:16:52.833475       1 initializer.go:154] Job.batch "pi" is invalid: spec.template: Invalid value: api.PodTemplateSpec{ /* ... snip ... */}
```

Discovered in https://github.com/istio/issues/issues/93 but not specific to helm.

**Comment by mattmoor** [comment]
This isn't specific to Istio.  The Spec of the Kubernetes Job object is considered immutable, which doesn't play nicely with Initializers that want to do things like inject Pods.

See also my comment [here](https://github.com/kubernetes/kubernetes/issues/48388#issuecomment-353692442).

**Comment by costinm** [comment]
My understanding was that latest k8s client removed initializer ? What's
the status of webhooks, can we start deprecating and
removing initializer ( i.e. announce that 0.4 is last version of istio with
initializer, 0.5 will have webhooks ? )

**Comment by ayj** [comment]
https://github.com/istio/istio/issues/2177

**Comment by ayj** [comment]
Fixed by switching to pod-level injection in https://github.com/istio/istio/pull/2830
