### ISSUE TITLE
Authentication policy side-effects and debugging

### ISSUE THREAD

**Issue by mgrand** [istio/istio#13595]
The issue 
_authentication policy side-effects and debugging #7464_
is marked stale and closed. I just had the same issue with Istio 1.1.0

**Comment by yangminzhu** [comment]
The essential problem is that we allow only 1 authentication for 1 specific service. This has a side effect that you cannot share 1 authentication policy (e.g. JWT) easily to other people as it will override the mTLS setting (i.e. the side effect). Instead, the other people have to add the `peers: mtls` before using the shared policy.

I think this is still an issue for the ongoing authentication v1alpha2 design. Splitting the mTLS and JWT policy into 2 separate CRD might be an options, any thoughts? @diemtvu

**Comment by mgrand** [comment]
Another option that will work is that if you apply a policy that does not specify a mTLS setting, it defaults to the existing mTLS setting. The question is which way of doing this will cause the least breakage and inconvenience. I think that there will be many situation in which the option of defaulting the the current setting will not break anything.  The option of splitting the policies will break all existing policy specifications.
