### ISSUE TITLE
Add more integration tests for the native environment

### ISSUE THREAD

**Issue by lei-tang** [istio/istio#13606]
**Describe the feature request**
Currently, most integration tests under tests/integration folder are for k8s environment. This feature requests for adding more integration tests for the native environment. Moreover, the test framework needs more support for native integration tests, e.g., ApplyPolicyFiles(env *kube.Environment, ...), in pkg/test/util/policy/policy.go, only supports k8s environment. 

**Describe alternatives you've considered**

**Additional context**

**Comment by lei-tang** [comment]
#13439

**Comment by incfly** [comment]
I think we need to state more specifically what tests should be native env, as a feature request or bug. This can be stated in the code mauve one as a general goal.
