### ISSUE TITLE
Use readable cluster names in stats

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1360]
@rshriram commented on [Tue Oct 24 2017](https://github.com/istio/old_pilot_repo/issues/1613)

Currently, the cluster names are using cryptic shas. This is not useful from monitoring perspective, since end users cannot decode these shas. Envoy now has the ability to use configurable cluster name lengths. (--max-obj-len). We need to use this option to start Envoy with larger max obj lengths (189 characters), and use plain cluster names where possible. When the cluster name exceeds 189 characters, we can fall back to a SHA. Choice of 189 is based on Envoy internal implementation (there is an additional 67 character overhead per stat, for a total of 256 characters - i.e. word aligned)

Ideally, this change requires a change in istio/api to add a `max_stat_prefix` length parameter. And we can then read in this parameter (defaults to 189), and supply it as a CLI option to envoy (via max-obj-len parameter).

Without this fix, its impossible to make sense of stats in prometheus, making envoy monitoring pointless in production.

---

@rshriram commented on [Tue Oct 24 2017](https://github.com/istio/old_pilot_repo/issues/1613#issuecomment-339056816)

cc @nmnellis @fabolive FYI. Nick, once we have this fixed, you will see full cluster names in your prometheus feeds.

---

@kyessenov commented on [Tue Oct 24 2017](https://github.com/istio/old_pilot_repo/issues/1613#issuecomment-339062413)

We still need some hashing since the cluster names currently may include key-value pairs as well, and those are 64 characters each.

---

@rshriram commented on [Tue Oct 24 2017](https://github.com/istio/old_pilot_repo/issues/1613#issuecomment-339067999)

Right.. so, if the net name length is less than the max length, we can stick with it as is. If it exceeds the length, then we truncate, have some readable prefix and then the SHA.

**Comment by ijsnellf** [comment]
This was partially implemented in https://github.com/istio/istio/pull/1344. The PR makes the clustername human readable as described above and makes the length 189 chars, but does not make the length configurable.

**Comment by rshriram** [comment]
This has been solved for a while, but with some holes (#4430 ).
Closing my own issue.
