### ISSUE TITLE
Security of Istio

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#13618]
(P0) Secure coding & testing practices that affect all new work  -code-mauve style
(P0) CVE practice - disclosure, remediation, including a way to validate that we are doing it right.
(P1) Security scanning/adversarial testing of Istio codebase
(P2) Distroless prototype

**Comment by fpesce** [comment]
This Epic has no linked bugs.
This is going to be stale unless you want to attach some actionable items to it.

**Comment by howardjohn** [comment]
I think all of these are done, without associated issues it is hard to tell though. Can you either associate issues or I think this can be closed

**Comment by fpesce** [comment]
Not sure that:
(P0) Secure coding & testing practices that affect all new work -code-mauve style
(P1) Security scanning/adversarial testing of Istio codebase

are addressed, the rest is. Let's creat e 2 bugs to 1.3/1.4 for them and close this one.
