### ISSUE TITLE
Incorrect service grafana dashboard with traffic split

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#13626]
With traffic splitting enabled during canary deployment, service dashboard show incorrect success percentages.
Success rate varies from 50% to 150%. 

https://snapshot.raintank.io/dashboard/snapshot/mimQl4yS42oWPWpaW0na0rDozt5jRYLf

**Comment by douglas-reid** [comment]
This appears to be caused by, at least in part, the difference in use of `irate` and `rate` in the numerator and denominator.

**Comment by douglas-reid** [comment]
Closing, based on istio/installer/pull/166.

Please re-open if that does not resolve issue.
