### ISSUE TITLE
Enabling Envoy gRPC Access Log Service (ALS)

### ISSUE THREAD

**Issue by hanahmily** [istio/istio#13639]
**Describe the feature request**
Envoy gRPC access log service is another option for the access log. A user could use it to send access logs to a central log inventory or AMP system. [Apache SkyWalking](https://github.com/apache/skywalking) as an oss APM project has supported this protocol, so I submit this proposal to enable it in istio.

I submit the following PR to support this feature.
 - https://github.com/istio/api/pull/911
 - #13638

**Comment by douglas-reid** [comment]
The referenced PRs are now in the repo. Closing this issue as the functionality has been added.

**Comment by yury-alpatov** [comment]
How to enable ALS in already installed Istio? Where is it configured?

**Comment by HashTableHu** [comment]
> How to enable ALS in already installed Istio? Where is it configured?

Did you send skywalking from envoy successfully
