### ISSUE TITLE
Improve Pilot metrics 

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#13643]
We got some feedback that users are parsing Pilot logs and deriving metrics. This is because:

* we don't expose metrics they need
Some examples:
```
# HELP ipe_pilot_proxy_imbalanced A gauge which represents if the proxies to pilots ratio is imbalanced
# TYPE ipe_pilot_proxy_imbalanced gauge
ipe_pilot_proxy_imbalanced{pilot="istio-pilot-bbd8d59dd-hn6gp",proxies_connected="190",percentage_target="50",percentage_connected="49.47916666666667"} 0
ipe_pilot_proxy_imbalanced{pilot="istio-pilot-bbd8d59dd-96gdt",proxies_connected="194",percentage_target="50",percentage_connected="50.520833333333336"} 0
# HELP ipe_pilot_conflict_outbound_listener_tcp_over_current_tcp Multiple TCP services requesting the same port
# TYPE ipe_pilot_conflict_outbound_listener_tcp_over_current_tcp gauge

# HELP ipe_pilot_eds_no_instances Clusters with no instances
# TYPE ipe_pilot_eds_no_instances gauge

# HELP ipe_pilot_push_duration Full push duration
# TYPE ipe_pilot_push_duration gauge
ipe_pilot_push_duration{pilot="istio-pilot-bbd8d59dd-96gdt",start="1556295700291",end="1556295702269"} 1978
ipe_pilot_push_duration{pilot="istio-pilot-bbd8d59dd-hn6gp",start="1556295700290",end="1556295703059"} 2769

# HELP ipe_proxy_sync_status Represents the sync status of istio proxies
# TYPE ipe_proxy_sync_status gauge
ipe_proxy_sync_status{pod_name="abtest-allocator-74585db66-d97xw",namespace="abtest-allocator",cds="SYNCED",lds="SYNCED",rds="SYNCED",eds="SYNCED",pilot="istio-pilot-bbd8d59dd-hn6gp",proxy_version="1.1.3"} 1
```
* we don't document the metrics we do expose
Other than digging around prometheus or reading the code, there is no documentation.
* we expose metrics with enough details
ex: `pilot_xds_push_errors` doesn't indicate target

At the very least, adding some documentation on these would be very useful. 

Additionally:
> In your prometheus configuration that you ship with helm (and in doco), pre configured alerts for common problem cases.  We would just import the ruleset into our prometheus then 

@Stono @dwradcliffe

**Comment by Stono** [comment]
Why can't I thumbs up this! :-)

**Comment by douglas-reid** [comment]
OK. I've added support for auto-generating documentation on the exported metrics. So, at least one part of this concern has been addressed.

Some of these suggested metrics are a bit difficult. Putting pod names into the metrics could cause a huge explosion in metrics cardinality.

More thinking is needed here re: selecting a set of metrics to add and around common alerting.
