### ISSUE TITLE
Environments WG Code Mauve and Features

### ISSUE THREAD

**Issue by sdake** [istio/istio#13649]
These are features and code mauve work planned by the Environments workgroup. Individuals are free to submit work unrelated to these items. We can consider altering the Epic features over time.

- More automated stability tests for whitebox - stability, performance, etc (@costinm this code mauve item is confusing and needs a better definition.).

**Comment by linsun** [comment]
@sdake can this be closed?  I'm assigned to bug bash this one.

**Comment by sdake** [comment]
Closing.  I think we have solved the initial problems identified in the code mauve and we have bigger fish to fry in 1.5.
