### ISSUE TITLE
Operator Implementation

### ISSUE THREAD

**Issue by sdake** [istio/istio#13652]
Experimental version for 1.2. It will be released in parallel with Istio 1.2 from its own repo. 
MVP:
 - work with new istio-ecosystem/istio-installer helm charts
 - define functional install API, while Istio dynamic config will remain a passthrough to values.yaml. The Istio config specific part of values.yaml will be deprecated in future releases and install part will remain in operator API.
 - provide kustomize style overlay mechanism for patching rendered manifest
 - provide CLI mode equivalent to helm template but using new API
 - provide migration path for existing helm users
 - support upgrade from 1.1->1.2, with automated tests included
 - early version of controller. Will be functional but testing coverage depends on community.

**Comment by howardjohn** [comment]
The core of this is done, and there is a whole label dedicated to additional work - i think this is safe to close
