### ISSUE TITLE
Transparent proxy injection into existing K8s clusters

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1365]
@andraxylia commented on [Wed Mar 15 2017](https://github.com/istio/old_pilot_repo/issues/335)

- Initial initializer deployment and configuration is merged into istio/pilot. Additional enhancements are pending review (https://github.com/istio/pilot/pull/1104). 
- The feature is disabled by default in in e2e presubmit tests but can be enabled with `-use-initializer` flag to `bin/e2e.sh`. The feature will by enabled by default in istio/pilot after https://github.com/istio/pilot/pull/1104 is merged. The initializer is cluster scoped so any bugs could affect the entire test cluster. We should be prepared to revert to default-off and manually delete the initializer configuration. ClusterPool testing feature will help here (cc @sebastienvas). The feature can be enabled in istio/istio after istio/pilot switch over is complete.

TODO
- [x] Merge enhancement PR https://github.com/istio/pilot/issues/1104
- [x] Update istio/istio template files for initializer deployment/configuration 
- [x] Document injection method for istio.io https://github.com/istio/pilot/issues/1046

```release-note
Automated sidecar injection
By leveraging the alpha initializer feature provided by Kubernetes 1.7, envoy sidecars can now be automatically injected into application deployments when your cluster has the initializer enabled. This enables you to deploy microservices using kubectl, the exact same command that you normally use for deploying the microservices without Istio.
```

---

@kyessenov commented on [Wed Mar 15 2017](https://github.com/istio/old_pilot_repo/issues/335#issuecomment-286913322)

Please reference the upstream issue from Kubernetes. We might get it for 1.7.

---

@andraxylia commented on [Wed Mar 15 2017](https://github.com/istio/old_pilot_repo/issues/335#issuecomment-286916079)

Depends on kubernetes/community#132

---

@andraxylia commented on [Thu Mar 30 2017](https://github.com/istio/old_pilot_repo/issues/335#issuecomment-290557259)

I opened this issue, hopefully we can enhance PodPreset and re-use functionality:
kubernetes/kubernetes#43874

---

@ldemailly commented on [Fri Jul 28 2017](https://github.com/istio/old_pilot_repo/issues/335#issuecomment-318690026)

doc is https://docs.google.com/document/d/1-5rLhv6MbB27lL8l2CWD6kR-eMa13_PPwOScVVZq8bo/

---

@kyessenov commented on [Fri Jul 28 2017](https://github.com/istio/old_pilot_repo/issues/335#issuecomment-318724684)

There are two aspects of proxy injection: inserting a sidecar and programming iptables. Rephrased the title to be about the first item.

---

@ldemailly commented on [Fri Jul 28 2017](https://github.com/istio/old_pilot_repo/issues/335#issuecomment-318730882)

this is an epic so maybe it should cover both ?

---

@andraxylia commented on [Fri Jul 28 2017](https://github.com/istio/old_pilot_repo/issues/335#issuecomment-318793585)

Yes, it's an epic and covers everything. You can open issues and group them under this epic.

---

@andraxylia commented on [Fri Jul 28 2017](https://github.com/istio/old_pilot_repo/issues/335#issuecomment-318793624)

The title matches the roadmap item, let's leave it as it is.

---

@ldemailly commented on [Fri Aug 18 2017](https://github.com/istio/old_pilot_repo/issues/335#issuecomment-323438912)

epic should not be closed yet

---

@andraxylia commented on [Fri Sep 29 2017](https://github.com/istio/old_pilot_repo/issues/335#issuecomment-333176629)

This is done. P1 enhancements are possible, but they will need to be prioritized.

---

@Promaethius commented on [Wed Nov 01 2017](https://github.com/istio/old_pilot_repo/issues/335#issuecomment-341160462)

What's the status on this? Istios documentation says it's not ready but all the pull requests and issues are merged and closed respectively.

---

@ldemailly commented on [Wed Nov 01 2017](https://github.com/istio/old_pilot_repo/issues/335#issuecomment-341164567)

@Promaethius can you provide a link to where it says it's not ready ?

---

@Promaethius commented on [Wed Nov 01 2017](https://github.com/istio/old_pilot_repo/issues/335#issuecomment-341176221)

https://github.com/istio/pilot/blob/master/doc/proxy-injection.md
https://istio.io/docs/reference/commands/istioctl.html#istioctl-kube-inject

**Comment by ayj** [comment]
Automatic sidecar injection is available on k8s >= 1.9 (see https://istio.io/docs/setup/kubernetes/sidecar-injection.html).
