### ISSUE TITLE
stability testing for multi cluster and mesh expansion

### ISSUE THREAD

**Issue by sdake** [istio/istio#13655]

**Comment by phil9909** [comment]
I am willing to help, but need a little more details to get started.

**Comment by howardjohn** [comment]
Related PR https://github.com/istio/tools/pull/147

**Comment by fpesce** [comment]
Hey @philrud any update on this ? (another phil was wrongly assigned this bug)

**Comment by philrud** [comment]
My PR that lays down the foundation for multicluster perf/stability is merged – that's what John referred above. However adding more scenarios covering all multicluster/mesh expansion features is an ongoing work. I'd say we can close it unless somebody wants to keep it open to track this as an ongoing/continuous effort.

**Comment by howardjohn** [comment]
@philrud have you had a chance ran the tests on 1.1 or 1.2? And if so did you encounter any issues?

**Comment by philrud** [comment]
@howardjohn working on it, will update the community testing spreadsheet accordingly once I'm done (no surprises, so far, although there are known issues)

**Comment by philrud** [comment]
Apparently this is tracked as P0 in the context of upcoming 1.2 release. Closing this as the code has already landed and this set of scenarios was used during 1.2 community testing. I will file more specific issues for expanding the set of covered scenarios.
