### ISSUE TITLE
Manifest test failure reasons due to test infra failures

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1366]
@xiaolanz commented on [Mon Sep 18 2017](https://github.com/istio/old_pilot_repo/issues/1302)

modify https://github.com/istio/pilot/blob/master/test/integration/driver.go to clearly delineate if a test died because the test fails or if the test died because of infrastructure setup / teardown.

---

@kyessenov commented on [Mon Sep 18 2017](https://github.com/istio/old_pilot_repo/issues/1302#issuecomment-330392439)

How can we tell? If a component fails with panic/segfault, it's indistinguishable from failing from infrastructure failure.

---

@xiaolanz commented on [Mon Sep 18 2017](https://github.com/istio/old_pilot_repo/issues/1302#issuecomment-330429141)

I would treat if best efforts.

**Comment by rshriram** [comment]
This issue is not relevant anymore given the new test framework
