### ISSUE TITLE
SRE-related documentation

### ISSUE THREAD

**Issue by sdake** [istio/istio#13665]
**Describe the feature request**
- Document metrics.
- Document alerts.

**Describe alternatives you've considered**

**Additional context**

**Comment by douglas-reid** [comment]
We don't currently have any alerts configured. We have added to the collateral commands documentation on all exported system metrics. @geeknoid is working on generating a "components" metrics page that pulls from the generated reference pages, as I understand it.

That will cover all of the metrics except for the "default" or "Istio standard" metrics (and the envoy metrics which are documented elsewhere).

**Comment by douglas-reid** [comment]
Ok. All of the metrics for Istio should now be documented, either on the reference page for "Default Metrics" or on the pages for each component (mixs, pilot-discovery, galley).

I'm going to close this given those updates.

There is more work to be done to improve the docs, but they exist.
