### ISSUE TITLE
TestClientOnExampleHttpVaultCA Unit Test Failure - Breaks ALL commits

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#13668]
Example: https://circleci.com/gh/istio/istio/400907?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Reproduce with: `go test ./security/pkg/nodeagent/caclient/providers/vault/... -v`

This failure was NOT introduced by the code change. Commits that were passing previous are now failing. I think certs expired or something.

**Comment by howardjohn** [comment]
Fix needs to be applied to release-1.1 and master

**Comment by lei-tang** [comment]
These test failures are due to that the GKE cluster hosting the Vault server on the GCP endpoints-jenkins project were deleted. I have to find a GKE cluster that is reliable, re-create a Vault server, and update the test cases to use the IP address of the new Vault server. In addition, all Vault related user guides and integration tests need to be updated to use the new IP address.

**Comment by howardjohn** [comment]
A unit test should not depend on GKE... it should not even require internet connection

**Comment by lei-tang** [comment]
The unit tests ./security/pkg/nodeagent/caclient/providers/vault/ consists of tests on mock Vault server and on real Vault server. I can move the ones using real Vault server to integration tests after creating a  new Vault server.

**Comment by ozevren** [comment]
External dependencies for unit tests is a no-no, and mostly a bad idea even for integration and end to end tests. 

Can we deploy it hermetically?

**Comment by lei-tang** [comment]
I will create a PR to make these unit tests hermetical. The tests that use real Vault server will be moved to integration tests; there are manual steps to set up the Vault server, so an external Vault server is set up for testing purpose.

**Comment by lei-tang** [comment]
https://github.com/istio/istio/pull/13683 has been created to fix the failed unit tests of Vault CA integration, which:
- Fixes the failed tests to use a new Vault server.
- Moves the tests using real Vault server to integration tests.
