### ISSUE TITLE
Test framework needs support for Mac Envoy builds

### ISSUE THREAD

**Issue by liamawhite** [istio/istio#13677]
**Bug description**
When calling `apps.NewOrFail` during native tests I'm only and to get the latter half of that promise...

```
--- FAIL: TestLocalityPrioritizedLoadBalancing (13.38s)
    prioritized_test.go:106: apps.NewOrFail: timeout while waiting (last error: invalid character 'e' looking for beginning of value)
FAIL
```

**Expected behavior**
App is created.

**Steps to reproduce the bug**
Comment out [this line](https://github.com/istio/istio/blob/master/tests/integration/pilot/locality/prioritized/prioritized_test.go#L90) and run the tests in native mode...
```
go test -v ./... -istio.test.env native --istio.test.hub=gcr.io/istio-release --istio.test.tag=master-latest-daily
```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
master

**Comment by liamawhite** [comment]
cc @howardjohn

**Comment by howardjohn** [comment]
maybe a mac issue since it runs fine in ci?

**Comment by nmittler** [comment]
Yeah it's Envoy ... we don't create mac new builds for Envoy.  We probably should though.

@PiotrSikora we had discussed this briefly in the past.  Do you recall what is involved?

**Comment by PiotrSikora** [comment]
Prow, which we use to build releases, doesn't support macOS. The releases that are available were created and uploaded manually, which isn't great.

cc @utka

**Comment by liamawhite** [comment]
We (Tetrate) will be building macOS istio proxies soon. I wonder if Istio could leverage some of our infra? cc @lizan.

**Comment by nmittler** [comment]
@liamawhite that sounds good.  Do you want to take over this issue?

**Comment by liamawhite** [comment]
Yup, this may well just end up being some developer docs about a homebrew installation.
