### ISSUE TITLE
gRPC-web

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1368]
@arbarlow commented on [Mon Oct 30 2017](https://github.com/istio/old_pilot_repo/issues/1663)

As discussed in https://github.com/istio/pilot/issues/928 it would great if Pilot could enable Envoy's gPRC-web filter so that browsers can interact with backend gRPC services directly (useful for admin interfaces etc).

Also, in general, it would great to get a bit more control over Envoy config for filters etc, being a more useful ingress, getting closer to to nginx ingress for usefulness!

**Comment by peijenlin** [comment]
Is there an update on this?  Or documentation on how to enable grpc-web filter on sidecar?

**Comment by rshriram** [comment]
can you describe this in more detail? We are enabling a host of envoy filters now and we can look into enabling this as well, as long as there is no additional config input from anywhere

**Comment by rshriram** [comment]
cc @louiscryan / @ZackButcher

**Comment by ZackButcher** [comment]
This is for JS gRPC support? We can add the filter easily (AFAICT it's just an empty filter a la CORS), we need some way to indicate that a port/service should be gRPC-web and not regular gRPC (since AFAIK they're mutually exclusive, given gRPC-web's different wire protocol).

**Comment by adamyi** [comment]
Just a follow-up on @peijenlin 's comment. Here's a link to Google's repo: https://github.com/grpc/grpc-web. The protocol is described here: https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-WEB.md

It would also be nice if we can have something similar to the PbLite in the OSS community.

**Comment by ZackButcher** [comment]
Sorry, let me clarify: [a gRPC web implementation already exists in Envoy today](https://www.envoyproxy.io/docs/envoy/latest/configuration/http_filters/grpc_web_filter), Istio just doesn't support wiring it up. The work here is for Istio to support configuring the gRPC web filter; AFAIK it's just an empty filter config, so the only thing to do is support a new `grpc-web-` port protocol/prefix, and use that as the signal to include the gRPC web filter in the listeners we send to the sidecar for that service.

**Comment by rshriram** [comment]
@lizan can we uniformly enable the grpc-web filter for all grpc listeners? or atleast for the listeners on the gateway ?

**Comment by lizan** [comment]
Though it is possible, grpc listeners is usually h2 only but grpc-web is http/1.1 or h2, so rather make this opt-in?

**Comment by andraxylia** [comment]
@rshriram is this fixed?

**Comment by rshriram** [comment]
Nope

**Comment by codelowr** [comment]
any update on this one? Is it possible to enable grpc-web on envoy sidecar now ?

**Comment by vyshane** [comment]
We're also keen on this feature. Is there anything we can do to help progress it?

**Comment by nigeltiany** [comment]
Really need this too. And according to @ZackButcher an empty filter and a reserve word for port names is all that is needed. Anyway this can be unstaled? I also suggest ```grpcweb-${somename}``` for named ports supporting grpc.

**Comment by louiscryan** [comment]
If someone wants to get their hands a little dirty you could try to use

https://istio.io/docs/reference/config/istio.networking.v1alpha3/#EnvoyFilter

and if you're successful share a Gist with the community

**Comment by mier85** [comment]
What I need is exposing all the grpc-ports via proxy as grpc-endpoints as well as grpc-web-endpoints. 

i want to use exactly the same endpoints in my services for serving "all". is there a way to do that with filters? 

i got this up and running on a local envoy proxy already and it works great , so this is just about istio and the sidecar configuration.

**Comment by nigeltiany** [comment]
I found that this settings work
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: echo-filter
spec:
  workloadLabels:
    app: echo-service #your service name
  filters:
  - listenerMatch:
      portNumber: 80 #your service's port
      listenerType: SIDECAR_INBOUND
    filterName: envoy.grpc_web
    filterType: HTTP
    filterConfig: {}
    insertPosition:
      index: FIRST
```

**Comment by venilnoronha** [comment]
Port names prefixed with `grpc-web-` will have the `envoy.grpc_web` filter enabled automatically. See #10064 for further details.

**Comment by yuanyouxi** [comment]
> Port names prefixed with `grpc-web-` will have the `envoy.grpc_web` filter enabled automatically. See #10064 for further details.

does this name prefixed still work on istio 1.19 ?
