### ISSUE TITLE
Information of Unavailable PODs in prometheus

### ISSUE THREAD

**Issue by hitesh1907nayyar** [istio/istio#13680]
**Bug description**
Information is required as how can i get the number of unavailable PODs in prometheus. Presently if i install prometheus through istio then all the information of kubernetes is there in kubelet_XXX_XX table names. I am not able to find any table which specifies the information related to unavailable PODs. By unavailable i mean which PODs have gone from running state to evicted/crashoff states.

I need to show the PODs that have gone down in Grafana through promtheus.

This is more of information that is required.

**Comment by howardjohn** [comment]
If you use https://github.com/kubernetes/kube-state-metrics you can do a query like: `rate(kube_pod_container_status_restarts_total{job="kube-state-metrics"}[15m])`

AFAIK this isn't really related to Istio, we don't deal with any kubernetes level metrics, there are already other solutions for those as linked above.

**Comment by douglas-reid** [comment]
Closing, as this issue appears to be more directly related to k8s than istio and a suggestion has been provided.
