### ISSUE TITLE
helm chart deploy error

### ISSUE THREAD

**Issue by dellkeji** [istio/istio#13691]
**Bug description**
helm apply istio error; parse the configmap error, found character `\t` in follow files

file path:
charts/security/templates/configmap.yaml & charts/security/templates/create-custom-resources-job.yaml

istio version: 1.1.4

**Comment by howardjohn** [comment]
Are you upgrading or a new installer? What is the error?

It doesn't seem like those files have been changed recently and we haven't seen any issues like this before

**Comment by sdake** [comment]
not reproducible yet.  Please provide more information in the bug.

**Comment by dellkeji** [comment]
lastest version not found this, close it!
