### ISSUE TITLE
Add a script to query pilot for proxy configurations

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1369]
@baodongli commented on [Fri Oct 27 2017](https://github.com/istio/old_pilot_repo/issues/1641)

Per Istio Networking Roadmap: https://docs.google.com/document/d/1oLiEkescgAbUmv7ZsAW-W4_4g4xmrpbnOpyo6yfn06A/edit#heading=h.x9snb54sjlu9, there is a feature in the Debuggability section to introspect on Pilot. Open this issue to track the effort.

**Comment by rshriram** [comment]
we have several scripts now in istio/istio for this very purpose
