### ISSUE TITLE
PRs are being blocked from merge because prow tests are stuck

### ISSUE THREAD

**Issue by pitlv2109** [istio/istio#13726]
Prow tests were somehow turned off yesterday, now they are stuck with `Expected — Waiting for status to be reported`, causing approved PRs not being merged. For example: https://github.com/istio/istio/pull/13683. Posting here besides Slack for visibility, awareness, and better tracking.

**Comment by cjwagner** [comment]
The root issue has been resolved. You can use `/test all` to trigger tests on PRs where they are currently missing.

**Comment by pitlv2109** [comment]
Looks like it's been fixed. Thanks Cole.
