### ISSUE TITLE
Build fails on Intel for Istioctl(pilot)

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1372]
@kadamvandita commented on [Wed Oct 25 2017](https://github.com/istio/old_pilot_repo/issues/1622)

Hi ,

The pilot version used is 0.2.9 and bazel version used is 0.7.0

The pilot build fails on x86 with error ERROR: /usr/local/go/src/istio.io/pilot/tools/version/BUILD:3:1: in go_library rule //tools/version:go_default_library:
Traceback (most recent call last):
        File "/usr/local/go/src/istio.io/pilot/tools/version/BUILD", line 3
                go_library(name = 'go_default_library')
        File "/root/.cache/bazel/_bazel_root/2325d0d2e5f42b9a686a34f251405905/external/io_bazel_rules_go/go/private/library.bzl" line 143, in _go_library_impl
                emit_library_actions(ctx, sources = depset(ctx.files.sr...), <4 more arguments>)
        File "/root/.cache/bazel/_bazel_root/2325d0d2e5f42b9a686a34f251405905/external/io_bazel_rules_go/go/private/library.bzl" line 44, in emit_library_actions
                depset([], order = "link")

Order name 'link' is deprecated, use 'topological' instead.
ERROR: Analysis of target '//tools/version:go_default_test' failed; build aborted: Analysis of target '//tools/version:go_defaul_library' failed; build aborted.

Any solution to this

---

@ketank-new commented on [Wed Oct 25 2017](https://github.com/istio/old_pilot_repo/issues/1622#issuecomment-339308724)

I have been trying to build the same version of pilot on intel machine
Used bazel version 0.7

Some inputs on thsi will be very helpful from istio dev team

---

@rshriram commented on [Wed Oct 25 2017](https://github.com/istio/old_pilot_repo/issues/1622#issuecomment-339422535)

Can you use bazel 0.6.x? Thats what we are using in our CI/CD as well

---

@rshriram commented on [Wed Oct 25 2017](https://github.com/istio/old_pilot_repo/issues/1622#issuecomment-339422580)

Unfortunately, bazel is not all that backward compatible.

---

@ketank-new commented on [Wed Oct 25 2017](https://github.com/istio/old_pilot_repo/issues/1622#issuecomment-339553468)

@rshriram : Thanks for the reply
as per your suggestion i have moved back to bazel 0.60, using same version for pilot that is 0.2.9
When i start the build with command "make setup"

I get the below error

root@878a9e4f0af9:/usr/local/go/src/istio.io/pilot# make setup
++ pwd
+ PDIR=/usr/local/go/src/istio.io/pilot
+ '[' /usr/local/go/src/istio.io/pilot '!=' /usr/local/go/src/istio.io/pilot ']'
+ bazel build //...
Extracting Bazel installation...
.....................
ERROR: /root/.cache/bazel/_bazel_root/2325d0d2e5f42b9a686a34f251405905/external/io_bazel_rules_go/go/pri**vate/binary.bzl:226:48: name 'lib' is not defined (did you mean 'libs'?).**
ERROR: error loading package '': Extension 'go/private/binary.bzl' has errors.
INFO: Elapsed time: 9.141s
Makefile:19: recipe for target 'setup' failed
make: *** [setup] Error 1

Your inputs would help , thank sin advance

---

@ketank-new commented on [Thu Oct 26 2017](https://github.com/istio/old_pilot_repo/issues/1622#issuecomment-339595390)

also with bazel 0.6.1 we face the same issues

++ pwd
+ PDIR=/usr/local/go/src/istio.io/pilot
+ '[' /usr/local/go/src/istio.io/pilot '!=' /usr/local/go/src/istio.io/pilot ']'
+ bazel build //...
.....................
ERROR: /root/.cache/bazel/_bazel_root/2325d0d2e5f42b9a686a34f251405905/external/io_bazel_rules_go/go/private/binary.bzl:226:48: name 'lib' is not defined (did you mean 'libs'?).
ERROR: error loading package '': Extension 'go/private/binary.bzl' has errors.
INFO: Elapsed time: 1.451s
Makefile:19: recipe for target 'setup' failed
make: *** [setup] Error 1

---

@ketank-new commented on [Thu Oct 26 2017](https://github.com/istio/old_pilot_repo/issues/1622#issuecomment-339609643)

@rshriram : We would also like to know if you have build istio/pilot project on x86 before, is yes than could you share the build steps 

---

@rshriram commented on [Thu Oct 26 2017](https://github.com/istio/old_pilot_repo/issues/1622#issuecomment-339729956)

Our test infrastructure is on X86. and its using bazel 0.6.0. When you downgraded, did you do bazel clean --expunge? Typically, after changing bazel versions, you should wipe everything clean and start from scratch.

---

@ketank-new commented on [Thu Oct 26 2017](https://github.com/istio/old_pilot_repo/issues/1622#issuecomment-339874161)

@rshriram : Thanks for the reply , I have followed your steps to use "bazel clean --expunge"
followed by this i have restarted the build using "make setup" and i get the same error.

ERROR: /root/.cache/bazel/_bazel_root/2325d0d2e5f42b9a686a34f251405905/external/io_bazel_rules_go/go/private/binary.bzl:226:48: name 'lib' is not defined (did you mean 'libs'?).
ERROR: error loading package '': Extension 'go/private/binary.bzl' has errors.
INFO: Elapsed time: 1.451s
Makefile:19: recipe for target 'setup' failed
make: *** [setup] Error 1

I am a little surprised, to see this error in the release version, so hence i was trying to make sure if i was not missing anythg from my side
has this release version of pilot built on your end? 

---

@kadamvandita commented on [Thu Oct 26 2017](https://github.com/istio/old_pilot_repo/issues/1622#issuecomment-339889249)

hi @rshriram ,

I tried pilot build for version 0.2.9 with bazel 0.6.0 on Intel.Got libs related error as mentioned by @ketank-new . Also cleaned the previous bazel  build with "bazel clean --expunge" command,but the same above error persists.

The error is as follows:
++ pwd
+ PDIR=/usr/local/go/src/istio.io/pilot
+ '[' /usr/local/go/src/istio.io/pilot '!=' /usr/local/go/src/istio.io/pilot ']'
+ bazel build //...
ERROR: /root/.cache/bazel/_bazel_root/2325d0d2e5f42b9a686a34f251405905/external/io_bazel_rules_go/go/private/binary.bzl:226:48: name 'lib' is not defined (did you mean 'libs'?).
ERROR: error loading package '': Extension 'go/private/binary.bzl' has errors.
INFO: Elapsed time: 7.927s
Makefile:19: recipe for target 'setup' failed

Please let us know your comments on this

---

@kadamvandita commented on [Mon Oct 30 2017](https://github.com/istio/old_pilot_repo/issues/1622#issuecomment-340390364)

Hi @rshriram 

I tried building other istio components like CA,auth etc for version 0.2.9 with bazel version 0.6.0. They also fail with similar error as reported above ( same error with which pilot build failed).

Please let us know your comments on this.

---

@kadamvandita commented on [Mon Oct 30 2017](https://github.com/istio/old_pilot_repo/issues/1622#issuecomment-340405420)

Hi @rshriram ,

I tried building pilot latest verison (0.2.10) with **lower bazel version (0.5.4).** The build was successful . But the readme of pilot mentions to use 0.6.x and above. (https://github.com/istio/pilot).  Is it advisable to build pilot with a lower version like (0.5.4) or continue its build with 0.6.x and above.

Please let us know your comments on this.

---

@ayj commented on [Mon Oct 30 2017](https://github.com/istio/old_pilot_repo/issues/1622#issuecomment-340493135)

The minimum required bazel version was updated to 0.6.x _after_ we created 0.2.x branch. The 0.2.10 release requires the older bazel version (e.g. 0.5.4).

---

@kadamvandita commented on [Wed Nov 01 2017](https://github.com/istio/old_pilot_repo/issues/1622#issuecomment-341332737)

Hi @rshriram 

The pilot source code is moved to old_repo in github . Is it like the some new code is being added there , or pilot code is being moved out.

We found pilot code in master branch. Why is the structure changed?. How will it affect the build steps. 

Please let us know on this.

**Comment by kadamvandita** [comment]
Hi @rshriram ,

A new stable release of pilot is out 0.2.12.But can't find pilot source code  in the source. Moreover If I try building with bazel 0.6.1 on Intel it fails with below error.

ERROR: /root/.cache/bazel/_bazel_root/2325d0d2e5f42b9a686a34f251405905/external/io_bazel_rules_go/go/private/binary.bzl:226:48: name 'lib' is not defined (did you mean 'libs'?).
 ERROR: error loading package '': Extension 'go/private/binary.bzl' has errors.
 INFO: Elapsed time: 9.141s
 Makefile:19: recipe for target 'setup' failed
 make: *** [setup] Error 1

Could you please update us on this? 

Also you had mentioned there will be build instructions to build source using go like go build, is that supported in his version?

**Comment by kadamvandita** [comment]
Hi @rshriram ,

I followed the instructions mentioned by you as follows:

cd $GOPATH/src/istio.io/istio
 git clone https://github.com/istio/istio.git
 cd istio
 git checkout 0.2.12
 dep init
 dep ensure
 go build .//...

I get the error : 
tests/e2e/apps/hop/app.go:36:2: no Go files in /home/test/go_new_dir/src/istio.io/istio/tests/e2e/apps/hop/config

Any updates on this?

**Comment by rshriram** [comment]
dep ensure only works on master.

**Comment by kadamvandita** [comment]
Any specific instructions for stable release branch?

**Comment by rshriram** [comment]
none. there is no dep ensure for stable release branch.

**Comment by kadamvandita** [comment]
@rshriram : I have been trying to build istio **release v 0.2.12** on intel 
I have installed go - 1.9 as pre requisites, jdk 1.8
I have used build instruction 

- istio/istio> go build .//... ( but the build fails with the below log)
tests/e2e/apps/hop/app.go:36:2: no Go files in /home/test/go_new_dir/src/istio.io/istio/tests/e2e/apps/hop/config

So I was optimistic to know why is the build failing with stable release , can you provide me some inputs

**Comment by rshriram** [comment]
@costinm FYI

**Comment by kadamvandita** [comment]
@costinm , Any updates on this for the stable release?

**Comment by mandarjog** [comment]
Hi vandita,
If your goal is to build and use the istioctl binary from 0.2.x, you should use bazel. 

Is there a reason why you specifically want to use pure go tools to build 0.2.x ?

**Comment by kadamvandita** [comment]
Hi @mandarjog ,

As mentioned by you in your comments about use of bazel, which bazel version should be used to build istio? The readme file mentions 0.6.1 (But that doesn't seem to work and fails with .libs error ), as can be seen in my previous comments.

**Comment by GregHanson** [comment]
@kadamvandita istio no longer requires bazel as a build tool and can instead be built directly using go.  

```
make istioctl

ls -al $GOAPTH/out/linux_amd64/release/istioctl 
```
