### ISSUE TITLE
Support headless services with auth

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1373]
@kyessenov commented on [Tue Sep 12 2017](https://github.com/istio/old_pilot_repo/issues/1253)

Tracking issue to support mTLS auto-upgrade for headless services.

---

@rshriram commented on [Tue Sep 12 2017](https://github.com/istio/old_pilot_repo/issues/1253#issuecomment-328971370)

Currently auth is automatically disabled for headless services.. see #1249

**Comment by selmanj** [comment]
Any upcoming plans on adding support for headless services? Using a StatefulSet requires use of a headless service.

Right now the experience is subpar as well - rather than getting any error/log messages anywhere, the connection is merely dropped.

**Comment by andraxylia** [comment]
Duplicate of #1277
