### ISSUE TITLE
httpredirect on error

### ISSUE THREAD

**Issue by mikosa** [istio/istio#13749]
**Describe the feature request**
Suppose I have service1 receiving traffic through a gateway.
I need a way to redirect the traffic to another service or url in case there is an error 400 or 500 received from service1

**Describe alternatives you've considered**
I have seen that virtualservice supports retries in case of errors, but the httpredirect does not support on condition there is an error

**Additional context**
I need this for different cases, mainly in case jwt token origin verification using a policy returns a 400 error, I need to redirect the user to the login service instead (or to oauth.com)
Another use case this can be useful is in case a service is not reachable, the redirect can send the traffic to a static page instead.

**Comment by howardjohn** [comment]
I don't think this is possible in Envoy, which means its not something we can implement in Istio. That is what I gathered from https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto. 

I see the use case, but I don't think there is anything we can do here. If you really want this feature, perhaps you could submit a feature request against Envoy?
