### ISSUE TITLE
Eureka adapter support for Eureka pre-v1.2.2

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1374]
@ijsnellf commented on [Mon Oct 02 2017](https://github.com/istio/old_pilot_repo/issues/1378)

We need to have additional logic to handle pre-v1.2.2 Eureka servers as pointed out here: https://github.com/istio/pilot/pull/994#pullrequestreview-56501078

See https://github.com/hudl/fargo/pull/59 for precedent in handling the differences.

We need to either add logic or switch to fargo/hudl.

**Comment by rshriram** [comment]
closing as stale, as no one has asked for this yet.
