### ISSUE TITLE
istio-pilot's istio-proxy 100% ram increase almost instantly 

### ISSUE THREAD

**Issue by Stono** [istio/istio#13752]
Well a picture says a 1000 words, check the istio-proxy on istio-pilot suddenly double its memory:
<img width="804" alt="Screenshot 2019-05-01 at 19 43 11" src="https://user-images.githubusercontent.com/1486729/57035216-61c19600-6c49-11e9-8d8f-2b4872f46a2b.png">

Another pilot in the same cluster, did it at exactly the same time:
<img width="808" alt="Screenshot 2019-05-01 at 19 43 54" src="https://user-images.githubusercontent.com/1486729/57035266-8584dc00-6c49-11e9-85f9-da13ffcaeb79.png">

Unfortunately I only keep 48 hours of pilot logs so can't see what actually happened.  However i've just restarted them so will keep an eye and try and capture some logs.

I don't know if you have any long running clusters you can compare against.

**Comment by mandarjog** [comment]
Can you get config dump from after?
Since some times it is the high watermark I am wondering if proxy gets some transient config and then back to normal but does not release memory.

@silentdai am incorrect in thinking that the allocator does not release memory back?

**Comment by mandarjog** [comment]
@Stono did you by any chance delete the sidecar resource around that time and then re-created it ?

**Comment by silentdai** [comment]
@mandarjog I have the same guess. There was a high cpu usage at the ram bump moment. And I don't expect istio-proxy ram because of tcmalloc.

**Comment by Stono** [comment]
No we didn't delete and recreate any Sidecars at that time.

**Comment by silentdai** [comment]
@Stono I don't think we can triage at this moment: Logs are not in retention. Neither pilot nor envoy. 
Do you have any metrics on request per second, or listener/cluster destruction per second or any other metrics to reason about what was happenning?

**Comment by Stono** [comment]
Hey, 
Yeah i understand.   I was keeping the issue open in case it occurred again and I could provide more logs but as of yet, it hasn't.  I'll close for now and just re-open if i see it again.
