### ISSUE TITLE
Test framework features needed for reusing existing installer

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#13765]
We need to be able to

- [x]  Skip tests that require custom install
- [ ]  Cleanup tests without cleaning up Istio - maybe
- [x]  Investigate why echo tests fail (may be new installer related)
- [x]  Investigate why mixer/bookinfo tests create a file with contents `null` and try to kubectl apply it (may be new installer related). Fixed in https://github.com/istio/istio/pull/13767

**Comment by ozevren** [comment]
Why do we need to skip the tests that need custom install? Can we simply add support to use the new installer deploy/undeploy Istio, similar to the existing model we have right now?

**Comment by howardjohn** [comment]
I don't think the partial cleanup is very useful for us anymore, so this can be closed as all others are done.

**Comment by ozevren** [comment]
Still, I am worried about skipping tests that use custom install. Does this mean we will never execute those tests with the new installer?

**Comment by howardjohn** [comment]
Yes they will not be executed, which I agree is a bit worrying. the best solution is probably to make a new installer component like you mentioned (at least my opinion, not sure about Costin), but we haven't had the time to do that

**Comment by ozevren** [comment]
Can we track this as an issue? I think we should take a look at this within the context of Code Mauve.
@geeknoid @nmittler

**Comment by howardjohn** [comment]
Sure, created https://github.com/istio/istio/issues/14098
