### ISSUE TITLE
Need a way to configure max connections on PassthroughCluster

### ISSUE THREAD

**Issue by dwradcliffe** [istio/istio#13771]
**Describe the feature request**

We need a way to customize the max connections on the passthrough cluster. As we transition onto the mesh we will have many outbound connections and the default of 1024 is not enough.

**Describe alternatives you've considered**
Since there is no destination rule for the passthrough/fallback, we can't use that.

**Additional context**
I can see clearly where to add this config in pilot code, but we probably need a way to configure it instead of hardcoding to something larger than the default. (I did hardcode it for my testing and it worked well.)
https://github.com/istio/istio/blob/fede70ebc0f781b7bbf62242ce7531e60bcdf749/pilot/pkg/networking/core/v1alpha3/cluster.go#L1011-L1019

**Comment by hzxuzhonghu** [comment]
Maybe we can add mesh wide option just like `ConnectTimeout`

Or add it to Sidecar

/cc @rshriram

**Comment by rshriram** [comment]
Do you really need this to be configurable? I would be okay to simply bump up the limits on the passthrough cluster to a high value (i.e. no limit).

**Comment by dwradcliffe** [comment]
At the moment I don't think we need it to be configurable, as long as it is sufficiently high that we never worry about it. (I wasn't sure if everyone would be ok with a huge number?)

**Comment by hzxuzhonghu** [comment]
Agreed, seems no harm since it is used for outbound.

**Comment by dwradcliffe** [comment]
In that case I can drop the patch I'm running now into a PR.
