### ISSUE TITLE
Relational database adapter for Pilot config store

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1378]
@shalako commented on [Thu Oct 19 2017](https://github.com/istio/old_pilot_repo/issues/1557)

Cloud Foundry Routing team is offering to submit a PR for an adapter and runtime options to use it.

Proposal: https://docs.google.com/document/d/16SexdTBgKyhM3ebUB4eVk-lJSXwiCDdJwH3L9yShf5o/edit?usp=sharing

---

@kyessenov commented on [Thu Oct 19 2017](https://github.com/istio/old_pilot_repo/issues/1557#issuecomment-338074613)

cc @louiscryan @smawson 

---

@cmluciano commented on [Fri Oct 20 2017](https://github.com/istio/old_pilot_repo/issues/1557#issuecomment-338250539)

cc @xiaolanz for Config WG

---

@cmluciano commented on [Fri Oct 20 2017](https://github.com/istio/old_pilot_repo/issues/1557#issuecomment-338305553)

cc @istio/pilot-hackers 

---

@shalako commented on [Fri Oct 20 2017](https://github.com/istio/old_pilot_repo/issues/1557#issuecomment-338308469)

In Istio Slack #cloudfoundry, @kyessenov said:
> It seems to me in the same vein as consul/eureka/VM integration - it's fine for custom flags/deployment until we have a proper plugin model generalized in the config group. I would gladly accept contributions, but want to keep config group (@smawson and @louiscryan) in the loop for the architectural direction

Thank you!

---

@rshriram commented on [Fri Oct 20 2017](https://github.com/istio/old_pilot_repo/issues/1557#issuecomment-338311551)

This is cool. Looking forward to the PRs. I would suggest getting started with the concrete PRs for platform and config adapters. When the config story materializes, we can align the code, instead of waiting few months for the config system to land.

---

@smawson commented on [Fri Oct 20 2017](https://github.com/istio/old_pilot_repo/issues/1557#issuecomment-338313486)

I'm very worried about ecosystem fragmentation if we support multiple configuration APIs for istio. Having multiple config stores will also cause problems for the hybrid / multi-zone configuration model. So I don't think this makes sense to do.

Instead we should just run the istio config API inside cloud foundry, just like we do in all environments. I'd like to understand why that wouldn't be an option here.

---

@andraxylia commented on [Fri Oct 20 2017](https://github.com/istio/old_pilot_repo/issues/1557#issuecomment-338318998)

Can you please send the proposal to istio-networking email as well, with a pointer to the issue?

---

@smawson commented on [Sat Oct 28 2017](https://github.com/istio/old_pilot_repo/issues/1557#issuecomment-340215775)

Following up on my comment, it sounds like etcd is the primary issue, we should see if we can resolve that in coordination with the config API group.

---

@xiaolanz commented on [Sun Oct 29 2017](https://github.com/istio/old_pilot_repo/issues/1557#issuecomment-340242370)

One possible config design is that each zone maintains a separate config store. There is only one "master Galley" exposing config API and rolling out configs to all the zones. The zone-local config store is pluggable, which can be either in etcd or other implementations.  

This way, we don't need to deal with multi-zone distributed config convergence. Each zone will get the performance benefit from local config access.

**Comment by louiscryan** [comment]
@rosenhouse is this stale in light of the downward facing Pilot api. If so feel free to close.

**Comment by rosenhouse** [comment]
I think you mean this pilot decomposition design?  

https://docs.google.com/document/d/1S5ygkxR1alNI8cWGG4O4iV8zp8dA6Oc23zQCvFxr83U

Then yes.
