### ISSUE TITLE
Multicluster Service MeshGateway - Connected Clusters - Could not resolve host: httpbin.bar.global

### ISSUE THREAD

**Issue by mario-dicarlo** [istio/istio#13781]
I'm following the steps to create connected clusters from this page:
https://istio.io/docs/examples/multicluster/gateways/

I get to step 5 which calls:
`kubectl exec --context=$CTX_CLUSTER1 $SLEEP_POD -n foo -c sleep -- curl -I httpbin.bar.global:8000/headers`

and the response is:
`curl: (6) Could not resolve host: httpbin.bar.global`

Also, when looking at the CoreDNS ConfigMap which has been taken from this page and applied:
https://istio.io/docs/setup/kubernetes/install/multicluster/gateways/

the ConfigMap reverts back and deletes the global section after a few minutes:
```
global:53 {
        errors
        cache 30
        proxy . xx.xx.xx.xx
    }
```

Are there any issues which would cause this to happen?

Thanks

**Comment by shawnho1018** [comment]
I also suffered from the same issue. Is there any help on the way?

**Comment by mystxbr** [comment]
Same here...
istio-coredns-plugin container shows de registry but cannot resolve
2019-05-23T19:07:30.655920Z	info	adding DNS mapping: httpbin.bar.global.->[127.255.0.2]

172.20.137.198 is the address of my istiocoredns svc
nslookup: can't resolve 'httpbin.bar.global': Name does not resolve
/ # nslookup httpbin.bar.global. 172.20.137.198

**Comment by RossWhitehead** [comment]
Lost a day to this problem last week. It appears to be a limitation with AKS - https://github.com/Azure/AKS/issues/811

The coredns configmap cannot be overwritten. The resolution is to extend the coredns configmap by creating a coredns-custom configmap.

Please take note of the name used in the data section. It must be suffixed with ".service" otherwise it will not work.

```
kubectl apply -f - <<EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  istio.service: | # you may select any name here, but it must end with the .server file extension
    global:53 {
        errors
        cache 30
        proxy . $(kubectl get svc -n istio-system istiocoredns -o jsonpath={.spec.clusterIP})
    }
EOF
```

**Comment by billbertrand** [comment]
Same issue in K8 not in AKS. 

curl: (6) Could not resolve host: httpbin.bar.global

apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
data:
  Corefile: |
    .:53 {
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           upstream /etc/resolv.conf
           fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
    global:53 {
        errors
        cache 30
        forward . xx.xx.xx.xx
    }

**Comment by camille-rodriguez** [comment]
I am blocked on this issue and the workaround does not seem to work for me.
