### ISSUE TITLE
sds_vault_flow_test test failures

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#13780]
https://circleci.com/gh/istio/istio/405901?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Might be a flake, I didn't investigate much. 

Another example: https://circleci.com/gh/istio/istio/406310?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by lei-tang** [comment]
Created a PR https://github.com/istio/istio/pull/13785 to trigger integration tests and check the integration tests.

**Comment by lei-tang** [comment]
The integration tests of PR #13785 pass: https://circleci.com/gh/istio/istio/406603?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link.

**Comment by howardjohn** [comment]
I think testgrid is missing failures due to https://github.com/istio/istio/issues/13789, as mentioned in the PR there are 2 failures in very recent history

**Comment by myidpt** [comment]
Hi Lei, is this already fixed?

**Comment by lei-tang** [comment]
Based on https://k8s-testgrid.appspot.com/istio-postsubmits-master#integration-k8s-tests, sds_vault_flow_test has passed the tests since 5-11-2019. Hence, the issue is closed; if the problem reoccurs, the issue can be opened again.

**Comment by myidpt** [comment]
Thanks, Lei.
