### ISSUE TITLE
Istio metrics for TLS (including mTLS) related errors

### ISSUE THREAD

**Issue by nrjpoddar** [istio/istio#13791]
**Describe the feature request**

When you turn on mTLS for a subset of services in your cluster often you have misconfigurations like missing DestinationRules, incorrect TLS setting (one side has STRICT but other side has no TLS setting) or SSL handshake error (invalid cert, protocol negotiation errors) which leads to traffic failures. This issue also exists when you have an incorrect setting in ServiceEntries or DestinationRules which are used for communicating to external services.

These kind of failures don't currently update any existing Istio metric. It is quite difficult to debug these failures and having a metric will make it easy to monitor and alert for these scenarios.

**Describe alternatives you've considered**
Envoy does provide SSL related stats for [listeners](https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/stats#listener) but as Istio uses the same listeners for various outbound calls it's not easy to get the context you want from these stats.

**Additional context**
The metric should at least support the following labels to enable ease of debugging:
* Source Workload
* Destination Workload (if known)
* Destination Service
* SSL error type i.e. no cert, san failure, unknown.

Adding SAN in general might be a good label but might lead to cardinality explosion.

This feature request complements https://github.com/istio/istio/issues/7669 but that issue deals exclusively with traffic handled by BlackHole cluster which can happen due to missing Istio configuration like ServiceEntry.

**Comment by douglas-reid** [comment]
Let's combine this with #11600 (and close #11600).

> Today we have connection.mtls boolean property that Indicates whether a request is received over a mutual TLS, It will be nice if we can add the version of the mTLS as attribute.

/assign @kyessenov (as he was assigned to the other issue).

**Comment by douglas-reid** [comment]
From off-thread conversation:

> add the client-side TLS attributes to the bucket of missing TLS information

**Comment by yangminzhu** [comment]
@douglas-reid I have a PR to add metrics for JWT in pilot: https://github.com/istio/istio/pull/15013, does that look good to you? If that's the appropriate way to add metrics in Istio I would love to add more for things like `missing DestinationRules`, `incorrect TLS setting`, etc.  Thanks!

**Comment by kyessenov** [comment]
@yangminzhu the issue refers to Envoy-produced telemetry. I think it is useful to detect mis-configuration in Pilot/Galley, but we still need to observe the actual data path security properties. Things like SSL error codes during negotiation supplemented TCP connection reset errors or TLS version used for an HTTP request. If you can help exposing those properties through Envoy StreamInfo / API, then we can certainly make use of it in our filters.

**Comment by nrjpoddar** [comment]
@kyessenov is there any progress on this issue? I would like to explore how to get this exposed via Istio filters and get a design going if no one has started working on it.

**Comment by nrjpoddar** [comment]
This PR https://github.com/istio/proxy/pull/2434 adds reporting capabilities for client side SSL state.
