### ISSUE TITLE
Load balancer does not come up on AWS 

### ISSUE THREAD

**Issue by mabushey** [istio/istio#13799]
Running Istio 1.1.2 via the amazing Banzai operator, but this has been an issue as far back as 0.8. Under Kops, the ELB for Istio comes right up, however with either Typhoon or KubeSpray, it doesn't bring it up:

```
✗  kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}

✗  kubectl get service -n istio-system | grep LoadBalancer
istio-ingressgateway                                LoadBalancer   10.233.19.19    <pending>     15020:31460/TCP,80:31380/TCP,443:31390/TCP,31400:31400/TCP,15029:31410/TCP,15030:31420/TCP,15031:31430/TCP,15032:31440/TCP,15443:31450/TCP   33m
```

Both master and nodes have roles with the following IAM policies:
```
    {
      "Effect": "Allow",
      "Action": ["ec2:*"],
      "Resource": ["*"]
    },
    {
      "Effect": "Allow",
      "Action": ["elasticloadbalancing:*"],
      "Resource": ["*"]
    },
```

**Bug description**
LoadBalancer stays in `<pending>`

**Expected behavior**
LoadBalancer is provisioned

**Steps to reproduce the bug**
Install Istio

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS / CoreOS

**Affected product area (please put an X in all that apply)**

[X ] Configuration Infrastructure
[ ] Docs
[X ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

**Comment by howardjohn** [comment]
I don't this is an Istio issue, unless you can create load balancers for other services but not for ingress gateway

**Comment by mabushey** [comment]
You can claim this is not an Istio issue, however the reality is the only AWS distro of Kubernetes that Istio works on is Kops, which is two major versions back. Six moths ago I tried using Typhoon, and the developer of Typhoon says to file this as an Istio issue: https://github.com/poseidon/typhoon/issues/358 Please either help me fix the issue, or update the docs to reflect that Istio only compatible with AWS when using Kops.

**Comment by howardjohn** [comment]
Sorry I misunderstood the problem, I didn't realize LoadBalancer type is only/usually available on managed Kubernetes environments. You can configure what type of Service is used with `--set gateways.istio-ingressgateway.type=ClusterIP` or `--set gateways.istio-ingressgateway.type=NodePort`

**Comment by mabushey** [comment]
Not sure what the `--set` commands are for. What .yaml file are you referring to? Why would I want to change this? If it works with Kops, lets figure why it doesn't work with any other AWS distro.

This is interesting.. Under Kops the `--domain` and `Readiness` do not exist.
```
kubectl describe pod istio-ingressgateway -n istio-system
...
      proxy
      router
      --domain
      $(POD_NAMESPACE).svc.cluster.local
...
    Readiness:  http-get http://:15020/healthz/ready delay=1s timeout=1s period=2s #success=1 #failure=30
...
```

**Comment by howardjohn** [comment]
`--set` are passed to Helm. If you are not using helm then you can modify the `istio-ingressgateway` Service.

The LoadBalancer type creates an AWS ELB (if you are on AWS, when on GKE it would create a Google Cloud Load Balancer), so Typhoon or whatever probably doesn't have support for doing that.

**Comment by mabushey** [comment]
I switched from Helm to the Bonzai Operator. I was never a fan of Helm, and the Bonzai Operator is awesome.

I want an AWS ELB. The masters and the workers have a role that gives them `"Action": ["elasticloadbalancing:*"]`.

**Comment by howardjohn** [comment]
I am not experienced with running Kubernetes outside of GKE, but my understanding -- If you want an ELB I believe you need to use LoadBalancer type. But Typhoon does not support this (https://github.com/poseidon/typhoon/issues/231#issuecomment-393352849). 

I think how you would accomplish this is to manually create a load balancer and point it at your ingress using NodePort as the type. You may find some more info at https://istio.io/docs/examples/advanced-gateways/ingress-certmgr/, although it is for a slightly different goal

**Comment by mabushey** [comment]
One issue with creating it myself is I'm using HPA to add more nodes on demand, and if I create the ELB myself via terraform it's not going to have the new HPA nodes in it. Typhoon does not support this, so now I'm trying Kubespray and having the same issue. What's in common is Istio.

**Comment by howardjohn** [comment]
I understand the frustration that it isn't working, but Istio may be common, but it is not the root cause. All Istio does is tell Kubernetes to create a LoadBalancer. Typhoon (intentionally) does not support this. Because of uses like this, Istio provides an option to NOT create a LoadBalancer. I am not clear what you actually expect Istio to do here... it cannot create a ELB for you, that is Kubernetes job.

Create this config and you will see it Pending as well - no Istio involved.
```yaml
apiVersion: v1
kind: Service
metadata:
  name: httpbin
spec:
  selector:
    app: httpbin
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
```

**Comment by mabushey** [comment]
@howardjohn You're correct. Thank you very much for isolating this down.

**Comment by howardjohn** [comment]
No problem, it definitely isn't the most simple part of Kubernetes

**Comment by arianmotamedi** [comment]
@mabushey out of curiosity, are there any events logged for the `istio-ingressgateway` pod hinting as to why the load balancer can't be created?

**Comment by mabushey** [comment]
Hi @arianmotamedi 

Not that I can see:
```
✗  kubectl -n istio-system describe pod/istio-ingressgateway-6986f594f7-7dnz6
Name:               istio-ingressgateway-6986f594f7-7dnz6
Namespace:          istio-system                           
...
Status:             Running
...
    State:          Running
      Started:      Thu, 02 May 2019 23:03:04 +0000
    Ready:          True
    Restart Count:  0
...
Events:          <none>
...
```

```
✗  kubectl -n istio-system describe service/istio-ingressgateway
Name:                     istio-ingressgateway
Namespace:                istio-system
Labels:                   app=istio-ingressgateway
                          istio=ingressgateway
Annotations:              service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: 300
                          service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-west-2:xxxxxxxxxxxx:certificate/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxdxxx
                          service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
Selector:                 app=istio-ingressgateway,istio=ingressgateway
Type:                     LoadBalancer
...
Events:                   <none>
```

**Comment by arianmotamedi** [comment]
Hmm weird. Does typhoon impose any vpc-tagging requirements like kops/eks do for creating load balancers? Just something to double check. Other than that I agree with John that this is K8s specific, not Istio, so if creating a `kind: Service` of type LoadBalancer results in the same behavior then I suggest opening another issue in their repo (without mentioning Istio to prevent confusion 😉)

**Comment by elnemesisdivina** [comment]
> Hi @arianmotamedi
> 
> Not that I can see:
> 
> ```
> ✗  kubectl -n istio-system describe pod/istio-ingressgateway-6986f594f7-7dnz6
> Name:               istio-ingressgateway-6986f594f7-7dnz6
> Namespace:          istio-system                           
> ...
> Status:             Running
> ...
>     State:          Running
>       Started:      Thu, 02 May 2019 23:03:04 +0000
>     Ready:          True
>     Restart Count:  0
> ...
> Events:          <none>
> ...
> ```
> 
> ```
> ✗  kubectl -n istio-system describe service/istio-ingressgateway
> Name:                     istio-ingressgateway
> Namespace:                istio-system
> Labels:                   app=istio-ingressgateway
>                           istio=ingressgateway
> Annotations:              service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: 300
>                           service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-west-2:xxxxxxxxxxxx:certificate/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxdxxx
>                           service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
> Selector:                 app=istio-ingressgateway,istio=ingressgateway
> Type:                     LoadBalancer
> ...
> Events:                   <none>
> ```

Ho this annotation should be entered in case I don't use kops, just flat was cli and also this should be done every time I install a new cluster with istio? txs.
