### ISSUE TITLE
access istio provided grafana, prometheus dashboard

### ISSUE THREAD

**Issue by bhushanrade** [istio/istio#13804]
not able to access istio-system's grafana, Prometheus etc dashboard through an external network
I tried to do port forwarding for grafana but it works with the only localhost  like http://localhost:3000 but not for http://publicip:3000

**Comment by howardjohn** [comment]
To set up external access to the dashboards, you can find instructions at https://istio.io/docs/tasks/telemetry/gateways/

**Comment by douglas-reid** [comment]
I believe this has been answered. Please send further questions around this to discuss.istio.io
