### ISSUE TITLE
Flaky Test: istio.io/istio/tests/integration/pilot/locality/failover.TestLocalityFailover

### ISSUE THREAD

**Issue by ozevren** [istio/istio#13812]
https://prow.k8s.io/view/gcs/istio-prow/logs/istio-integ-k8s-tests/7620
@liamawhite I believe you wrote the tests?

**Comment by liamawhite** [comment]
These have only failed once during their lifetime in the [post-submit](https://k8s-testgrid.appspot.com/istio-postsubmits#integration-k8s-tests). Is there any info on how frequent the failure is here?

**Comment by ozevren** [comment]
They fail fairly frequently: https://k8s-testgrid.appspot.com/istio-postsubmits-master#integration-k8s-tests

**Comment by liamawhite** [comment]
Ok, will investigate.

**Comment by howardjohn** [comment]
Root cause: race condition at https://github.com/istio/istio/blob/555ec2a9b4f1c58b309ed5e4431d52ed8ca0e051/pilot/pkg/proxy/envoy/v2/ads.go#L638

if we have no instances (delay in propagation) then we won't use the override locality labels

**Comment by howardjohn** [comment]
This has improved, but we still do see some flakes, so I will reopen and add the flaky label
https://testgrid.k8s.io/istio-presubmits-master#integ-pilot-k8s-presubmit-tests
