### ISSUE TITLE
Flaky Test: istio.io/istio/tests/integration/mixer.TestMixer_Report_Direct

### ISSUE THREAD

**Issue by ozevren** [istio/istio#13811]
https://testgrid.k8s.io/istio-postsubmits#integration-k8s-tests&exclude-non-failed-tests=

https://prow.k8s.io/view/gcs/istio-prow/logs/istio-integ-k8s-tests/7672

**Comment by ozevren** [comment]
Since you're looking at Mixer tests, I've assigned this to you.

**Comment by douglas-reid** [comment]
Looking at istio-postsubmit in testgrid, this test appears to be passing now. Closing pending recurrence.
