### ISSUE TITLE
Make BoringSSL available to Lua FFI

### ISSUE THREAD

**Issue by robertpanzer** [istio/istio#13818]
**Describe the feature request**
We are validating cryptographic signatures within Lua scripts.
Envoy and istio-proxy use BoringSSL as the implementation for TLS and this would provide everything that we would need as well.

Unfortunately we are not able to call the respective functions because the symbols are not exported or stripped from the binary so that Lua is not able to call them.

To get our functionality working we would need the following symbols:
```c
     void CBS_init(CBS *cbs, const uint8_t *data, size_t len);
     EVP_PKEY *EVP_parse_public_key(CBS *cbs);

     int SHA256_Init(SHA256_CTX *sha);
     int SHA256_Update(SHA256_CTX *sha, const void *data, size_t len);
     int SHA256_Final(uint8_t *md, SHA256_CTX *sha);

     void OPENSSL_cleanse(void *ptr, size_t len);

     int RSA_verify(int hash_nid, const uint8_t *msg, size_t msg_len,
                    const uint8_t *sig, size_t sig_len, void *rsa);

     int EVP_DecodeBase64(uint8_t *out, size_t *out_len,
                          size_t max_out, const uint8_t *in, size_t in_len);
```

**Describe alternatives you've considered**
As an alternative we are currently loading libnettle.so, libhogweed.so and libgmp.so.
Parsing public keys is much more complicated though.
Also this approach is brittle because it relies on the environment or the file system the proxy is running in.

**Additional context**

**Comment by crazyxy** [comment]
@robertpanzer can we just expose one function, for example, validateSignature instead of exposing all those functions since you only need to signature validation?

**Comment by robertpanzer** [comment]
@crazyxy Sure, if there is an alternative that does this.
Currently the input to our signature validation looks like this:
- public key formatted as a X.509 SubjectPublicKeyInfo encoded in Base64 
- Signature computed by the client, also encoded in Base64
- Clear text as a string or byte array

I could not find any function in BoringSSL or OpenSSL that does all of this with one function, therefore I had to split it into the steps (our scheme is SHA256withRSA):
- Decode public key from Base64 and create a matching public key "object"
- Decode signature
- Compute SHA256 of the clear text
- Pass key, hash of clear text and signature to the signature validation function to know if the signature is correct or not.

If the Istio-proxy can provide a single function for this I would be more than happy to use it.

**Comment by crazyxy** [comment]
@robertpanzer I think exposing one function is preferred since Envoy might not want to give direct access to lower-level functions.

**Comment by robertpanzer** [comment]
Sure, makes sense.
Other users might use other encryption schemes though, so it might be nice to expose one function per possible scenario (e.g. including other key formats, other hash functions, other encodings than Base64 etc)

**Comment by crazyxy** [comment]
@PiotrSikora WDYT? Do we need to expose one function per possible scenario?

**Comment by crazyxy** [comment]
I am going to add two functions. 
```
// decode string encoded in base64
// @param string encoded in base64
decodeBase64();

// verify signature
// @param public key 
// @param hash function name( including MD4, MD5, SHA1, SHA224, SHA256, SHA384, SHA512, MD5_SHA1)
// @param signature
// @param data
verifySignature();
```

**Comment by robertpanzer** [comment]
Nice.
So verifySignature also computes the hash over the data? Or is data already expected to be the hash?
What is the expected format of the key? I think there is also a variety of different formats, X.509 SubjectPublicKeyInfo being the one that we use, others might use full X.509 certs.

**Comment by crazyxy** [comment]
I used this function to implementation signature verification. 
```c
int EVP_DigestVerifyInit(EVP_MD_CTX *ctx, EVP_PKEY_CTX **pctx,
                          const EVP_MD *type, ENGINE *e, EVP_PKEY *pkey);
 int EVP_DigestVerify(EVP_MD_CTX *ctx, const unsigned char *sigret,
                      size_t siglen, const unsigned char *tbs, size_t tbslen);
```
https://www.openssl.org/docs/man1.1.1/man3/EVP_DigestVerify.html

The data is not expected to be hashed. The format of the key is a byte array (uint8_t* or char*), for your case, it's the result from calling decodeBase64. In verifySignature, I will use
```c
     void CBS_init(CBS *cbs, const uint8_t *data, size_t len);
     EVP_PKEY *EVP_parse_public_key(CBS *cbs);
```
to parse the public key. In this case, we don't need to know the format of key.

Does this make sense?

**Comment by robertpanzer** [comment]
Expecting the key as the Base64 encoded binary is actually not so nice.
That means the key would be decoded and parsed again for every single signature validation.
This should have a significant performance impact.

**Comment by duderino** [comment]
@robertpanzer Please update this issue with a relatively small list of functions you want exposed.

**Comment by robertpanzer** [comment]
Sure.
If BoringSSL should not be exposed directly, we would need sth like this:

```
// Takes the string at `in` of length `in_len` and decodes it to memory at `out` 
// and returns the length in `out_len`. Tries to write at most `max_out` bytes.
// Returns 0 or 1 on success
int decodeBase64(uint8_t *out, size_t *out_len,
	                         size_t max_out, const uint8_t *in, size_t in_len)

// Takes a X.509 SubjectPublicKeyInfo in binary asn.1 encoding with length `len`.
// Creates some internal representation and writes the pointer to it at `*key`.
// Instead of `void*` for a key a type definition would be fine as well
// Returns 0 on success, other numbers on error, 
// possibly multiple different values indicating the type of error (e.g. wrong objectId, bad formatting, etc)
int importPublicKey(const uint8_t *data, size_t len, void** key)

// verify signature: verifies that signature contains a valid signature using the key over clear data
// @param public key 
// @param hash function name( including MD4, MD5, SHA1, SHA224, SHA256, SHA384, SHA512, MD5_SHA1)
// @param signature
// @param data
int verifySignature(void* key, 
          const uint8_t* clear, 
          const size_t clear_len, 
          hash_function, 
          const uint8_t* signature,
          const size_t signature_length);
```

This should cover our current use case.

**Comment by crazyxy** [comment]
FYI https://github.com/envoyproxy/envoy/pull/7050

Add an extra function 
```c
releasePublicKey(void*)
```
to release the public key resource.

**Comment by robertpanzer** [comment]
@PiotrSikora I tried with your binary, but it didn't work unfortunately:
```
PANIC: unprotected error in call to Lua API ([string "local ffi = require "ffi"..."]:89: /x/usr/local/bin/envoy: undefined symbol: EVP_DecodeBase64)
```

**Comment by PiotrSikora** [comment]
Just to verify, did you try the binary from `envoy-symbol-...` or `envoy-alpha-...` archive? I originally provided link to a wrong one, and if you clicked on the link in the email, then you might have used binary with stripped symbols.

**Comment by robertpanzer** [comment]
@PiotrSikora I downloaded the updated link, also fetched envoy-alpha..., but both give me the same error.
I can see that the envoy-symbol binary seems to have a size of 567MB, while the envoy-alpha has 25MB, so I suppose I got the right archives.

**Comment by PiotrSikora** [comment]
@robertpanzer ok, thanks!

**Comment by wheleph** [comment]
Can you provide any examples on how to use `verifySignature` and `importPublicKey`?

Specifically how to generate the public key and sign data in compatible way? In which format should the public key be provided to `verifySignature`?
