### ISSUE TITLE
Failing test on Kube: TestEcho/NoSidecar

### ISSUE THREAD

**Issue by ozevren** [istio/istio#13810]
https://testgrid.k8s.io/istio-postsubmits#integration-k8s-tests&exclude-non-failed-tests=

https://prow.k8s.io/view/gcs/istio-prow/logs/istio-integ-k8s-tests/7708

**Comment by ozevren** [comment]
It looks like this is after your Echo related changes has landed. Could you take a look?

**Comment by nmittler** [comment]
@ozevren This is just the NoSidecar test that we already knew was flaking on Kube. I thought you submitted a PR to skip this test, no?

**Comment by ozevren** [comment]
This is not on the "required" gate, so it executes. My Pr was tagging things as flake'y, but I haven't made the PR to make use of the labels yet.

**Comment by nmittler** [comment]
This should be resolved by #14015

**Comment by ozevren** [comment]
This is still failing in post submit.

**Comment by nmittler** [comment]
@ozevren AFAICT the TestGrid postsubmits tab shows that the last failure was on 5/8 ... or am I missing something?

**Comment by ozevren** [comment]
The link in this bug is probably stale. Here is the dashboard showing failures:
https://testgrid.k8s.io/istio-postsubmits-master#integration-k8s-tests&exclude-non-failed-tests=

**Comment by nmittler** [comment]
Ah ok, so that's a different issue. The panic is identified in #14108 and was just fixed. #14084 is the root cause.  Closing this as a duplicate of #14084.
