### ISSUE TITLE
Flaky test: istio.io/istio/tests/integration/pilot/outboundtrafficpolicy/allowany.TestOutboundTrafficPolicyAllowAny

### ISSUE THREAD

**Issue by ozevren** [istio/istio#13813]
https://testgrid.k8s.io/istio-postsubmits#integration-k8s-tests&exclude-non-failed-tests=
https://prow.k8s.io/view/gcs/istio-prow/logs/istio-integ-k8s-tests/7620

**Comment by howardjohn** [comment]
This has been stable for a week now after some fixes. Just need to turn off the flakey label

**Comment by geeknoid** [comment]
Can we close this issue then?

**Comment by ozevren** [comment]
The tests needs to be marked as non-flaky. Then we can close the bug.
