### ISSUE TITLE
prow/release-test.sh is constantly failing.

### ISSUE THREAD

**Issue by ozevren** [istio/istio#13823]
Making the test non-required. Opening this bug to track.

**Comment by howardjohn** [comment]
The release-test failure is probably indicative of a real problem. Looks like the 5/4 daily build wasn't created (not sure why/where to see the failure reason though) https://gcsweb.istio.io/gcs/istio-prerelease/daily-build/

**Comment by bianpengyuan** [comment]
This is also happening in 1.1 branch. Looks like the script takes too long to execute:
> {"component":"entrypoint","level":"error","msg":"Process did not finish before 2h0m0s timeout","time":"2019-05-08T18:58:12Z"}

**Comment by howardjohn** [comment]
I haven't seen this failing for a while, I think this is fixed? It isn't on testgrid though so hard to verify

**Comment by ozevren** [comment]
Did we make this required? I opened the bug to track to make it required. If we haven't done so, we should not close this bug.

**Comment by howardjohn** [comment]
No I did not, let's reopen this then

**Comment by icygalz** [comment]
done. Closing this issue.
