### ISSUE TITLE
Istio injection is not working for modified Deployments.

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1382]
@ayj commented on [Fri Oct 13 2017](https://github.com/istio/old_pilot_repo/issues/1477)

@emaildanwilson commented on [Fri Oct 13 2017](https://github.com/istio/istio/issues/1130)

With istio injection running with a setting of `disabled` I'm experiencing an issue where Deployments which are modified to contain `annotations:
    sidecar.istio.io/inject: "true"` do not get injected with envoy. If they are deleted and recreated then the injection works.

The log shows `I1013 20:53:45.569177       1 initializer.go:202] ObjectMeta initializer info extensions/v1beta1, Kind=ReplicaSet central-architecture/mydeployment-62
8804509 policy:"true" status:"" nil`

Is this expected?

---

@emaildanwilson commented on [Wed Oct 18 2017](https://github.com/istio/old_pilot_repo/issues/1477#issuecomment-337754709)

I can dig in and try to fix this if you agree it's broke and should work. An easy repro is to `kubectl edit deployment mydeployment` and remove the injected portions but leave the annotation `sidecar.istio.io/inject: "true"`.

---

@ayj commented on [Wed Oct 18 2017](https://github.com/istio/old_pilot_repo/issues/1477#issuecomment-337759661)

Copying my response from https://github.com/istio/istio/issues/1130)
> Are you modifying the sidecar.istio.io/inject annotation after the deployment is created? k8s initializers only run when deployments are created.

---

@ayj commented on [Wed Oct 18 2017](https://github.com/istio/old_pilot_repo/issues/1477#issuecomment-337760660)

I'm not sure this problem is easily solvable while we're using initializers for automatic injection. However, this may be solvable when add support for mutating webhooks. See https://github.com/istio/pilot/issues/1474

---

@linsun commented on [Wed Oct 18 2017](https://github.com/istio/old_pilot_repo/issues/1477#issuecomment-337774019)

I think this is a corner case and we can document as a 0.2 limitation, given we are planning to switch to mutating webhooks also.

---

@emaildanwilson commented on [Thu Oct 19 2017](https://github.com/istio/old_pilot_repo/issues/1477#issuecomment-337967317)

Thank you, that makes sense.
I can workaround this for now by changing our deployment process.

**Comment by ayj** [comment]
The automatic sidecar injection (via webhook) supports pod-level injection. Modifying the annotation in the pod template spec should trigger a rolling update which will (re)inject the sidecar into the new pods if the value is `true` or omit it if the value is `false`.
