### ISSUE TITLE
Pilot discovery doesn't have retries of requests to apiserver

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1383]
@ijsnellf commented on [Wed Oct 04 2017](https://github.com/istio/old_pilot_repo/issues/1392)

Noticeable when deploying the Eureka/Consul demos. The API server takes half a second to startup, which means that pilot isn't not able to make the initial request to the apiserver.
```
I1004 20:15:45.779376       1 client.go:169] registering CRD "routerules.config.istio.io"
Error: failed to register custom resources. Post http://istio-apiserver:8080/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions: dial tcp 172.18.0.7:8080: getsockopt: connection refused
```

This wouldn't be a big deal in K8S or with Nomad, since the container would restart and work the 2nd time, but you have to restart the container manually in Docker.

---

@rshriram commented on [Wed Oct 11 2017](https://github.com/istio/old_pilot_repo/issues/1392#issuecomment-335971324)

This is still an issue as it causes downtime in K8S or Nomad.. Its silly to expect the platform to restart Pilot if it can't reach the API server.

**Comment by rshriram** [comment]
No longer valid with the move to file based configs
