### ISSUE TITLE
Certificate Rotation

### ISSUE THREAD

**Issue by tushar00jain** [istio/istio#13832]
For mTLS is there any documentation on the validity of the certificates? How long are the certificates valid for and are they rotated automatically or not? Is the root CA also rotated automatically upon expiration? Is there a way to rotate the private keys? Can we trigger the rotation manually?

**Comment by adityats2020** [comment]
90 days - https://istio.io/help/faq/security/
Automatic rotation AFAIK.

**Comment by tushar00jain** [comment]
@adityats2020 I just checked the CA and it's valid for 1 year, I checked a few other certificates created which are valid for 90 days

**Comment by tushar00jain** [comment]
This seems a new document https://istio.io/docs/ops/security/root-transition. So this means CA certificates are not rotated automatically, is there a plan to automate this?

**Comment by adityats2020** [comment]
IIRC the root certificates are now valid for 10 years.

**Comment by tushar00jain** [comment]
@adityats2020 not automatic or triggered rotation sounds dangerous and I wonder why both kubernetes and istio chose to go down this path

do you know if what happens to the intermediate ca certificates and certificate chain when self signed certificates are disabled, will at least those be rotated automatically?

**Comment by elevran** [comment]
@tushar00jain

Expiration of root CA (Citadel) certificates:
- if self-signed, expiration is long (>1y IIRC)
- if [imported](https://istio.io/docs/tasks/security/plugin-ca-cert/) - whatever is set by the cert's creator 
It is currently your responsibility to rotate these. There have been some design attempts to automate this process, but I don't think they were merged (@wattli ?)

workload certificates used in mTLS are automatically rotated by Citadel and have a short lifetime (<1h, IIRC).

Hope this answers your questions

**Comment by tushar00jain** [comment]
@elevran 

I see root CA is 10 years now. Does the intermediate CA count as a workload certificate or is it also subject to being our responsibility to rotate also?

BTW k8s has an issue to rotate CA here https://github.com/kubernetes/kubeadm/issues/1350, can Istio also do the same? If it's our own responsibility, I'd be more inclined to canary migrate to a new cluster

**Comment by incfly** [comment]
This is done. We have released the automatic cert rotation in 1.4. @JimmyCYJ for visibility.

**Comment by sandeep1699** [comment]
@elevran @incfly  @tushar00jain  @adityats2020  
We are plugging in existing CA certificates as mentioned in this https://istio.io/latest/docs/tasks/security/cert-management/plugin-ca-cert/
Could you please let me know, Root CA, Intermediate CA will be rotated automatically upon expiration? Will there be any downtime during this process?
