### ISSUE TITLE
Istio sidecar/envoy terminating application ports in kubernetes

### ISSUE THREAD

**Issue by Rajankhosla** [istio/istio#13847]
**Bug description**
Hello,

We are facing issue with Istio sidecar injection with our GRPC app in kubernetes. We have created Ingress Gateway, Virtual Service and Destination Rule. Gateway is publicly exposed, Service has port mapping where request should route and also have destination rule for traffic routing.

So now what happens is as soon as we inject the istio sidecar it stops one of the port 50051 which our app is listening and that breaks things to work. Below is the sample yaml file for reference.

Please let us know how to fix this.

**Expected behavior**

Listener ports shouldn't be changed 

**Steps to reproduce the bug**

Deployment.yaml

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: 2019-05-02T06:09:38Z
  generation: 3
  labels:
    app: example-dev
  name: example-dev
  namespace: default
  resourceVersion: "2734130"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/example-dev
  uid: ddc75612-6ca0-11e9-966f-42010a8000a3
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: example-dev
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: example-dev
    spec:
      containers:
      - env:
        - name: bt_hhd_instance
          valueFrom:
            configMapKeyRef:
              key: bt_hhd_instance
              name: dev-ws-configmap
        - name: bt_ssd_instance
          valueFrom:
            configMapKeyRef:
             key: bt_ssd_instance
              name: dev-ws-configmap
        - name: is_staging
          valueFrom:
            configMapKeyRef:
              key: is_staging
              name: dev-ws-configmap
        - name: username
          valueFrom:
            secretKeyRef:
              key: username
              name: credentials
        - name: password
          valueFrom:
            secretKeyRef:
              key: password
              name: credentials
        image: gcr.io/example/svc-example@sha256:e5b6643534f723d423165386421d4bd2d01ce4fb6c6b75cc300b28f69134d012
        imagePullPolicy: IfNotPresent
        name: svc-example-sha256
        ports:
        - containerPort: 80
          name: http2
          protocol: TCP
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 50051
          name: grpc
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

----
example-dev-gateway.yaml

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: example-dev-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 50051
      name: grpc
      protocol: GRPC
    hosts:
    - '*'
  - port:
      number: 8080
      name: http
      protocol: TCP
    hosts:
    - '*'

--------

example-dev-virtualservice.yaml

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: example-dev-virtualservice
spec:
  gateways:
  - example-dev-gateway
  hosts:
  - '*'
  tcp:
  - match:
    - port: 50051
    route:
    - destination:
        host: example-dev-service
        port:
          number: 50051

-------

example-dev-destinationrule.yaml

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: example-dev-destinationrule
spec:
  host: example-dev-service
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

ISTIO_VERSION=1.0.5

**How was Istio installed?**
We have installed the istio by following this article:
https://medium.com/google-cloud/istio-grpc-loadbalancing-with-gcp-internal-loadbalancer-ilb-1b058b517640

Apart from this we have also tried with enabling the feature of istio from GKE itself, both cases result is same.

**Environment where bug was observed (cloud vendor, OS, etc)**

Google Kubernetes Engine
**Affected product area (please put an X in all that apply)**

[X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

![Before-NS](https://user-images.githubusercontent.com/35162457/57238818-e9dbdd00-7047-11e9-89b3-47b422664c72.PNG)
![After-NS](https://user-images.githubusercontent.com/35162457/57238824-eea09100-7047-11e9-8b80-e1ec210781fa.PNG)

**Comment by howardjohn** [comment]
Thanks for the report. It doesn't seem like there is enough info here for us to take any action and there hasn't been any activity.

If you are still experience this problem feel free to open an issue with more information. Thanks!
