### ISSUE TITLE
Expose admin API for load balance

### ISSUE THREAD

**Issue by Kiddinglife** [istio/istio#13859]
Hi, I am from game server background. Currently I am using ICE rpc framework where I can make my own load balancing rule by creating .so library and register it to ice's ice grid. In such way, I can handle the case where a player's states can move around across back servers with a fixed communication point attached in load balance.  Hopefully I make myself understood.

Is there similar thing existing in istio?

thanks.

**Comment by howardjohn** [comment]
I am not sure exactly what you are asking, but all our APIs that define various forms of load balancing can be found in https://istio.io/docs/reference/config/networking/ which may be a good starting place

**Comment by Kiddinglife** [comment]
thanks for your reply.

What I need is actually an programmatic way to make my own load balancing rule instead of hard coded rules.

Current Istio load balancer is perfect for web developments that have a fixed ‘patterns’ of round robin weighted and so on.

But game server does need a customised load balancing rule that is closely coupled with game plays.

If you still do not know I want, please search zero ice load balancer admin api.



Sent from my iPhone

On 1 Jun 2019, at 4:20 am, John Howard <notifications@github.com<mailto:notifications@github.com>> wrote:


I am not sure exactly what you are asking, but all our APIs that define various forms of load balancing can be found in https://istio.io/docs/reference/config/networking/ which may be a good starting place

**Comment by howardjohn** [comment]
if your needs extend beyond
https://www.envoyproxy.io/docs/envoy/v1.5.0/intro/arch_overview/load_balancing
then we probably don't support it. I think the most dynamic you can get
would be to have a layer above Istio that configures the CRDs, but not a
full custom lb strategy

**Comment by Kiddinglife** [comment]
ok thanks.
can close this issue

Sent from my iPhone

On 1 Jun 2019, at 12:51 pm, John Howard <notifications@github.com<mailto:notifications@github.com>> wrote:

if your needs extend beyond
https://www.envoyproxy.io/docs/envoy/v1.5.0/intro/arch_overview/load_balancing
then we probably don't support it. I think the most dynamic you can get
would be to have a layer above Istio that configures the CRDs, but not a
full custom lb strategy
