### ISSUE TITLE
istioctl produces unhelpful error message when using a incorrectly formatted file

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1385]
@kyessenov commented on [Tue Aug 29 2017](https://github.com/istio/old_pilot_repo/issues/1140)

@kyessenov commented on [Mon Jun 19 2017](https://github.com/istio/galley/issues/36)

@saturnism commented on [Mon Jun 19 2017](https://github.com/istio/istio/issues/420)

E.g.,

```
istioctl create -f guestbook-service-retry.yaml
Error: the server rejected our request for an unknown reason
```

However, when you turn on verbose mode, you can see the server side error:
```
...
I0619 17:33:00.227081   92174 request.go:991] Response Body: cannot parse proto message: unknown field "uri" in istio_proxy_v1_config.MatchCondition
```

**Comment by esnible** [comment]
I believe this has been fixed elsewhere and this Issue can be closed.

I built a version of _istioctl_ with both client side validation checks commented out.

```
istioctl create -f tests/e2e/tests/galley/testdata/networking-v1alpha3-DestinationRule-invalid.yaml
Error: admission webhook "pilot.validation.istio.io" denied the request: configuration is invalid: 2 errors occurred:

* empty domain name not allowed
*  is not a valid IP
```
