### ISSUE TITLE
Issue with Mixer reporting to Mixer with controlPlaneSecurity enabled

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio#13850]
In testing the new installer with the existing mixer e2e tests, I discovered that enabling control plane security broke comms between `istio-policy` and `istio-telemetry`.

This manifests in the logs as follows:

> [2019-05-06 17:46:39.032][20][warning][filter] [src/istio/mixerclient/report_batch.cc:106] Mixer Report failed with: UNAVAILABLE:upstream connect error or disconnect/reset before headers. reset reason: connection failure

There is also the suspicious bits of envoy config generated (this cluster appears twice in the config, also):

```json
"cluster": {
      "name": "mixer_report_server",
      "type": "STRICT_DNS",
      "connect_timeout": "1s",
      "hosts": [
       {
        "socket_address": {
         "address": "istio-telemetry",
         "port_value": 15004
        }
       }
      ],
      "circuit_breakers": {
       "thresholds": [
        {
         "max_connections": 100000,
         "max_pending_requests": 100000,
         "max_requests": 100000,
         "max_retries": 3
        }
       ]
      },
      "tls_context": {
       "common_tls_context": {
        "tls_certificates": [
         {
          "certificate_chain": {
           "filename": "/etc/certs/cert-chain.pem"
          },
          "private_key": {
           "filename": "/etc/certs/key.pem"
          }
         }
        ],
        "validation_context": {
         "trusted_ca": {
          "filename": "/etc/certs/root-cert.pem"
         },
         "verify_subject_alt_name": [
          "\u003cno value\u003e"
         ]
        }
       }
      },
      "http2_protocol_options": {},
      "dns_lookup_family": "V4_ONLY"
     },
     "last_updated": "2019-04-17T18:06:44.728Z"
    },
```

In particular, this snippet: 

```json
         "verify_subject_alt_name": [
          "\u003cno value\u003e"
         ]
```

We need a validation that mixer-to-mixer reporting works when control plane security is enabled.

**Comment by nak3** [comment]
This issue sometimes happen on my env with Istio 1.3.0 mTLS STRICT mode.

> [2019-10-03 11:58:47.182][24][warning][filter] [src/istio/mixerclient/report_batch.cc:109] Mixer Report failed with: UNAVAILABLE:upstream connect error or disconnect/reset before headers. reset reason: connection failure

It does not happen on e2e tests anymore?
