### ISSUE TITLE
istioctl: command not found

### ISSUE THREAD

**Issue by apacoco9861** [istio/istio#13858]
**Bug description**
istioctl: command not found

**Expected behavior**
istioctl should be in bin, when export PATH=$PWD/bin:$PATH, istioctl should be able to call

**Steps to reproduce the bug**
Trying to follow procedures,
https://istio.io/docs/examples/integrating-vms/

when running this command
istioctl kube-inject -n bookinfo -f samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql-vm.yaml | kubectl apply -n bookinfo -f -

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.1.4
1.14.1

**How was Istio installed?**
Download package and helm

**Environment where bug was observed (cloud vendor, OS, etc)**
Ubuntu 18.10

**Affected product area (please put an X in all that apply)**

[ x] Configuration Infrastructure
[ ] Docs
[ x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
What is in `$PWD/bin`? You will need to download the Istio release, and istioctl will be inside the bin folder of the release

**Comment by apacoco9861** [comment]
from 1.1.3, 1.1.4 and 1.1.5, all bin does not contain the command,
kindly let me know where I can download.

root@d-201-20:~/istio# ll istio-1.1.5/bin/
total 184
drwxrwxr-x  3 root root  4096 May  7 10:48 ./
drwxrwxr-x 20 root root  4096 May  2 02:18 ../
drwxrwxr-x  3 root root  4096 May  2 02:18 boilerplate/
-rwxrwxr-x  1 root root  1017 May  2 02:18 check_boilerplate.sh*
-rwxrwxr-x  1 root root  1152 May  2 02:18 check_dashboards.sh*
-rwxrwxr-x  1 root root  2258 May  2 02:18 check_license.sh*
-rwxrwxr-x  1 root root   861 May  2 02:18 check_links.sh*
-rwxrwxr-x  1 root root   978 May  2 02:18 check_pilot_codegen.sh*
-rwxrwxr-x  1 root root  1677 May  2 02:18 check_shell_scripts.sh*
-rwxrwxr-x  1 root root  1240 May  2 02:18 check_spelling.sh*
-rwxrwxr-x  1 root root  2189 May  2 02:18 ci2gubernator.sh*
-rwxrwxr-x  1 root root  2751 May  2 02:18 codecov_diff.sh*
-rwxrwxr-x  1 root root  3631 May  2 02:18 codecov.sh*
-rwxrwxr-x  1 root root  1084 May  2 02:18 counterfeiter.sh*
-rwxrwxr-x  1 root root  4562 May  2 02:18 diff_yaml.py*
-rw-rw-r--  1 root root   345 May  2 02:18 Dockerfile.goimports
-rwxrwxr-x  1 root root  2784 May  2 02:18 envsetup.sh*
-rwxrwxr-x  1 root root  3442 May  2 02:18 fmt.sh*
-rwxrwxr-x  1 root root  1654 May  2 02:18 get_workspace_status.sh*
-rwxrwxr-x  1 root root  2167 May  2 02:18 ghdata.py*
-rwxrwxr-x  1 root root  1057 May  2 02:18 go-bindata.sh*
-rwxrwxr-x  1 root root  2056 May  2 02:18 gobuild.sh*
-rwxrwxr-x  1 root root  2445 May  2 02:18 init_helm.sh*
-rwxrwxr-x  1 root root  6319 May  2 02:18 init.sh*
-rwxrwxr-x  1 root root 13220 May  2 02:18 istio-proxy-cfg.py*
-rwxrwxr-x  1 root root  3856 May  2 02:18 linters.sh*
-rwxrwxr-x  1 root root  6996 May  2 02:18 mixer_codegen.sh*
-rw-rw-r--  1 root root    64 May  2 02:18 OWNERS
-rwxrwxr-x  1 root root 16630 May  2 02:18 perfcheck.sh*
-rwxrwxr-x  1 root root  1138 May  2 02:18 protoc.sh*
-rwxrwxr-x  1 root root    15 May  2 02:18 .spelling_failures*
-rwxrwxr-x  1 root root 12374 May  2 02:18 testEnvLocalK8S.sh*
-rwxrwxr-x  1 root root  3828 May  2 02:18 testEnvRootMinikube.sh*

**Comment by howardjohn** [comment]
Interesting, that doesn't seem right. Where did you download from? I think I have the 1.1.5 binary in the bin folder from https://github.com/istio/istio/releases (Linux). Is that where you downloaded from?

On mobile though so can't verify.

**Comment by apacoco9861** [comment]
hmm... I know the problem
curl -L https://git.io/getLatestIstio | ISTIO_VERSION=1.1.5 sh -
When you not run this command to download, the download package will miss something.

**Comment by apacoco9861** [comment]
Thanks for your kind response.

I recall when I first try 1.1.3, the curl -L https://git.io/getLatestIstio | ISTIO_VERSION=1.1.3 sh - not work
so that I download from the link you provide https://github.com/istio/istio/releases via wget and tar xvf the package, run the installation according to 
https://istio.io/docs/setup/kubernetes/install/kubernetes/
also attempted
https://istio.io/docs/setup/kubernetes/install/helm/

even I upgrade 1.1.4 I still can't locate istioctl

I just try the 

root@d-201-20:~/istio# curl -L https://git.io/getLatestIstio | ISTIO_VERSION=1.1.5 sh -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  1631  100  1631    0     0   1707      0 --:--:-- --:--:-- --:--:--  227k
Downloading istio-1.1.5 from https://github.com/istio/istio/releases/download/1.1.5/istio-1.1.5-linux.tar.gz ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   614    0   614    0     0    812      0 --:--:-- --:--:-- --:--:--   812
100 14.9M  100 14.9M    0     0   378k      0  0:00:40  0:00:40 --:--:--  377k
Downloaded into istio-1.1.5:
bin  install  istio.VERSION  LICENSE  README.md  samples  tools
Add /root/istio/istio-1.1.5/bin to your path; e.g copy paste in your shell and/or ~/.profile:
export PATH="$PATH:/root/istio/istio-1.1.5/bin"

root@d-201-20:~/istio# istioctl
Istio configuration command line utility. Available configuration types: [destination-policy ingress-rule route-rule]

Usage:
  istioctl [command]

Available Commands:
  create      Create policies and rules
  delete      Delete policies or rules
  get         Retrieve a policy or rule
  kube-inject Inject istio sidecar proxy into kubernetes resources
  replace     Replace policies and rules
  version     Display version information and exit

Flags:
  -h, --help                             help for istioctl
  -c, --kubeconfig string                Use a Kubernetes configuration file instead of in-cluster configuration
      --log_backtrace_at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
  -n, --namespace string                 Select a Kubernetes namespace (default "default")
  -v, --v Level                          log level for V logs
      --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging

Use "istioctl [command] --help" for more information about a command.

the command installed

**Comment by linsun** [comment]
@apacoco9861 anything we should improve in our doc to make it easier for u?

**Comment by apacoco9861** [comment]
I think the first curl link I tried some how not work and I tried another way round partially work causing the problem. It's ok now I think. Thanks,

**Comment by arindam-b** [comment]
Hello,

I am facing the same issue. It shows:

```
-bash: istioctl: command not found
```

I tried it twice and in different gke clusters as per the said specification but it does not work. 

Though all the services are running smoothly.

**Comment by howardjohn** [comment]
istioctl is just a binary we include in the bin folder of the release, you don't run it on your cluster you run it locally, just like kubectl

**Comment by arindam-b** [comment]
@howardjohn : Thanks for yoru response.

I am trying to run:

```
arindam_gcp_atos@cloudshell:~/istio-gke/football-wcservice/k8s (rcup-mza-dev)$ kubectl apply -f <(istioctl kube-inject -f deployment.yml)
-bash: istioctl: command not found
error: no objects passed to apply
```

Got this error.

**Comment by howardjohn** [comment]
I see you are using cloudshell - I am not familiar with it but I would guess that comes with kubectl, but not istioctl. You can download the release https://github.com/istio/istio/releases, extract it, and run istioctl from the bin folder.

There are some more instructions here https://istio.io/docs/setup/kubernetes/download/

**Comment by shamsher31** [comment]
On the Linux system, you can follow these steps.

1. Download the [latest Istio release](https://istio.io/docs/setup/getting-started/#download) to your $HOME.
2. `$ sudo gedit ~/.bash_profile` 

 Add following:

```bash
export ISTIOPATH=$HOME/istio-1.4.3
export PATH=$ISTIOPATH/bin:$PATH
```
3. `$ source ~/.bash_profile`.
4. `$ istioctl version`
