### ISSUE TITLE
Prometheus collects application metrics from pods in environments without mutual TLS in kubernetes-pods-istio-secure job 

### ISSUE THREAD

**Issue by zhiqli** [istio/istio#13860]
Hey，
I want to use Prometheus to scrape the metrics of my application without mutual TLS。so，i add   annotations in my pod yaml like this

```
annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
```

But the result I saw was my application endpoint in `kubernetes-pods-istio-secure` job。
![image](https://user-images.githubusercontent.com/3350002/57269660-dddd3300-70ba-11e9-8f03-62fd306e6fc0.png)

I have testing，can be returned metrics with http, but https does not work, why not under the job `kubernetes-pods`，because my application sidercar without mutual TLS。

btw my istio version is 1.1.5。

**Comment by bianpengyuan** [comment]
Does your pod have `istio_mtls` label?

**Comment by zhiqli** [comment]
> Does your pod have `istio_mtls` label?

no @bianpengyuan

**Comment by zhiqli** [comment]
I have solved this problem, and the annotations are modified so that it will be fine.
```
annotations:
         Prometheus.io/scrape: "true"
         Prometheus.io/port: "9090"
         Prometheus.io/scheme: "http"
```
