### ISSUE TITLE
pkg/test/framework/README.md incorrect

### ISSUE THREAD

**Issue by esnible** [istio/istio#13870]
(I am using _master_ branch).

The README.md gives a code sample that uses `ctx := framework.GetContext(t)` but there is no such method.

The guide says there will be an overview of the framework architecture at https://github.com/istio/istio/wiki/Preparing-for-Development but I couldn't find it.

I would also like better comments on _pkg/test/framework/label/labels.go_ for `presubmit` and `postsubmit`.  I only have a fuzzy idea what those words mean.  They are not defined by Wikipedia or Wiktionary.

**Comment by howardjohn** [comment]
I think all of these have been addressed -- if not please reopen

* README updated code samples with proper syntax -- most examples are now actual code that runs too, so its never stale.
* Readme doesn't link to the wiki anymore
* presubmit label is removed so doesn't need more documentation
