### ISSUE TITLE
Enable Slack Github Integration and Notifications

### ISSUE THREAD

**Issue by devstein** [istio/istio#13874]
**Describe the feature request**
Allow GitHub notifications in Slack on the `istio` repository.

I want to enable Github notifications for `istio` in my team's slack channel, but receive the following error: 

```
Either the app isn't installed on your repository or the repository does not exist. Install it to proceed.
```

**Describe alternatives you've considered**
Regular email notifications

**Additional context**
Only a repository owner can enable the Slack + Github integration  

To reproduce: 

1. Add GitHub app to your Slack workspace
2. In a channel, run `/github subscribe istio/istio`
3. See error

**Comment by howardjohn** [comment]
I think the github app is added, if I click apps on the channel github is there

**Comment by shadiramadan** [comment]
@howardjohn I was about to do the same to subscribe to Istio releases.

```
/github subscribe istio/istio releases
```
![image](https://user-images.githubusercontent.com/875944/91195198-d0d8be80-e6c6-11ea-9d41-c3aefd1c6f38.png)

Has the *Slack* app been added to the `Istio Organization -> Settings -> Github Apps`?

If not, visiting this should prompt you to install it:
https://github.com/apps/slack/installations/new
