### ISSUE TITLE
Ingress Status is updated with Pilot's address instead of Ingress controller's node address

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1387]
@andraxylia commented on [Fri Aug 11 2017](https://github.com/istio/old_pilot_repo/issues/1021)

Observed by debugging the Ingress Status gets updated with the node where the pilot discovery pod is scheduled, and it should be updated with the node where the ingress-controller pod is scheduled.

---

@ijsnellf commented on [Fri Aug 18 2017](https://github.com/istio/old_pilot_repo/issues/1021#issuecomment-323462796)

Did you verify that `IngressService` was set correctly in the ConfigMap? I assume this occurs when `IngressService` has not been set, in which case it is a bug.

---

@andraxylia commented on [Mon Sep 18 2017](https://github.com/istio/old_pilot_repo/issues/1021#issuecomment-330398247)

This is for when Ingress is deployed as NodePort. In that case, the external IP of the service is not used. Please go inside k8s code and check.

---

@ijsnellf commented on [Tue Sep 19 2017](https://github.com/istio/old_pilot_repo/issues/1021#issuecomment-330580901)

As per @andraxylia's suggestion, it may be possible to fix this by writing our own implementation of this line:
https://github.com/istio/pilot/blob/master/adapter/config/ingress/status.go#L87

**Comment by rshriram** [comment]
We fixed this didn't we? @ijsnellf ??

**Comment by rshriram** [comment]
No longer relevant with the move to gateway and users seem to not mind using gateway over ingress.
