### ISSUE TITLE
Missing Cherrypicks from 1.0 to master manual review

### ISSUE THREAD

**Issue by fpesce** [istio/istio#13888]
Looking at #13625 discussion, a comment from @mattmi88 made me realize that we might have some missing features and bugfix that landed to the 1.0 branch (I haven't check any other yet).

I have manually reviewed the commits returned by the following command:
```
git log --no-merges --right-only --cherry-pick master...release-1.0
```

**Please NOTE: I'm mentioning the authors of the code changes but I intend to provide the cherrypick PR if you don't have time.**

And here is the commits that I think were **NOT** backported to master:
~~- commit 9dccd5a94b50f97d0b39aebf3a4ed4dc50c94b58
  Add Close() handling to kubernetesenv adapter (#10880)
  Cc: @douglas-reid 
  Track under #13876~~

~~- commit a5b0902212be7330ecb32b62e58b8af0099f9c0e
  Fix typo and add more log (#11462)
  (*Cosmetic though*).
  Cc: @wattli 
  Track under #13877~~

~~- commit 69b4d9b8fd5a255d8d84193ed277c7043e781118
  Remove noisy metric (#11388)
  (*Cosmetic though*).
  Cc: @ostromart 
  Track under #13878~~

~~- commit 1fa778726fc149088fa9f9a5c694835bf9dd712c
  fix release-1.0 for prow releases
  Cc: @rkpagadala 
  Track under #13879~~

~~- commit 073ed9b752c6eedce40e58a97a0c7f82073dcd07
  First round or mutex fixing (#10379)
  **more details**:
    pilot/pkg/proxy/envoy/v2/eds.go  -> defer are largely covering functions,
    should cherrypick the most precise lock/unlock from #10379
    same for ./pilot/pkg/serviceregistry/kube/pod.go that moved to pilot/pkg/serviceregistry/kube/cache.go
  Cc: @costinm 
  Track under #13880~~

~~- commit fb68c291454f8d2fb6bde2a0132944124f906ad8
  Disable Mixer server side L2 cache (#10202)
  Cc: @kyessenov 
  Track under #13881~~

~~- commit e9a851bbab9119c092efc4b6797e2d073e33e28f
  Resolve helm upgrade failure (#10005)
  **more details**:
    install/kubernetes/helm/istio/charts/galley/templates/validatingwebhookconfiguration.yaml.tpl
    still has 2 additional lines but there is no more:
    install/kubernetes/helm/istio/templates/crds.yaml
    bunch of install/kubernetes/helm/istio-init/files/crd ... instead ?
    Cc: @sdake 
  Track under #13882~~

- commit 4da522d4b3a3bdbeb1d64947c89f3115815b1a47
  warn if params are missing (#9474)
  **more details**:
  mixer/pkg/runtime/config/config_test.go does not seem fixed.
  mixer/pkg/runtime/config/ephemeral.go does not seem fixed.
  Cc: @mandarjog 
  Track under #13883

~~- commit fc4d01059644ccefe6eeacf00d85066c9afae699
  Incremental EDS (#8722)
  Cc: @costinm 
  Track under #13884~~

- commit a5efd2174a4f892e8d98beb7d3d9c95c089e552d
  Inject pod labels and annotations in node.metadata (#9208)
  **more details**:
    install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml does not seem to share the logic of this change
    Other .go files seem to not have the base64 logic either.
  @mandarjog 
  Track under #13885

Things I'm not sure about:
~~- commit 543774d739dc4aa94ed8d8545eadde8c38f3f98d
  Use externalTrafficPolicy: Local for ingress and gateways. (#7918)
    ./install/kubernetes/helm/istio/charts/gateways/values.yaml should have
    externalTrafficPolicy: Local ?
    Has this changed?
  @PiotrSikora 
  Track under #13886~~

~~- commit 4c3d1f60e2027200d3ae3408a6451093478d9091
  fix map concurrent read write (#10970)
  pilot/pkg/model/push_context.go  diverged a lot, code seems totally different
  Overall, seems Master similarly fixed in #10970
  @hzxuzhonghu 
  Track under #13887~~

**Comment by howardjohn** [comment]
i think these are false positives (we have them in master):
* incremental EDS
* fix map concurrent read write

**Comment by duderino** [comment]
@douglas-reid @wattli @ostromart @utka @kyessenov @sdake @mandarjog @PiotrSikora @hzxuzhonghu please take a look asap just to be sure.   We will create the 1.2 branch from master in about 2 weeks so it would be really good to be sure that everything from 1.0 was merged to master before we cut the 1.2 branch

**Comment by duderino** [comment]
and meta-comment, @fpesce did the review and intentionally erred on the side of false positives.   I think that was the right thing to do here.

**Comment by kyessenov** [comment]
#13881 is a false positive. L2 cache is disabled on master and 1.1 via different means.

**Comment by fpesce** [comment]
> i think these are false positives (we have them in master):
> 
> * incremental EDS
> * fix map concurrent read write
> * suspect we don't need "fix release-1.0 for prow releases" but not clear to me what it is doing - doesn't look like there was pr even

@howardjohn , I think I've seen some missing lines like 
```
s.EnvoyXdsServer.InitDebug(s.mux, s.ServiceController)
```
missing the discovery param, maybe the logic diverged?

**Comment by fpesce** [comment]
> #13881 is a false positive. L2 cache is disabled on master and 1.1 via different means.

Thanks for reviewing @kyessenov , will mark invalid.

**Comment by douglas-reid** [comment]
commit 9dccd5a is a false positive. The 1.0 codebase was sufficiently different from the 1.1 codebase that it required a 1.0 only PR. 1.1 was updated separately and those updates should have been carried forward with the merge back to master that followed.

**Comment by wattli** [comment]
I will handle a5b0902
