### ISSUE TITLE
TestGroupV1RBAC and TestGroupV2RBAC failing in postsubmit

### ISSUE THREAD

**Issue by yangminzhu** [istio/istio#13895]
For example: https://k8s-gubernator.appspot.com/build/istio-prow/logs/istio-integ-k8s-tests/7865

Not sure if this is caused by the test framework or caused by some actual issues but the other  `TestRBACV2` doesn't fail.

/assign @lei-tang 
/cc @nmittler @ozevren @pitlv2109

**Comment by pitlv2109** [comment]
`Galley.ApplyConfigOrFail: exit status 1: error: no objects passed to apply` seems like either the test framework or the caller?

**Comment by lei-tang** [comment]
According to https://testgrid.k8s.io/istio-postsubmits#integration-k8s-tests, these tests consistently pass until the SHA 25547e20c [Testing] Change security tests to use Echo (#13824). 
Add @nmittler for that the PR #13824 breaks the postsubmit tests.

**Comment by pitlv2109** [comment]
That PR deleted some functions in the `policy.go` file that we used for applying and deleting configs. I think it's worth investigating on that. On the other hand, `TestRBACV2` didn't seem to be suffered from it.

**Comment by lei-tang** [comment]
@nmittler The PR "[Testing] Change security tests to use Echo" (#13824)  breaks the postsubmit tests; can you revise the PR #13824 to fix the postsubmit test failures caused by the PR #13824?

**Comment by lei-tang** [comment]
@nmittler As far as I know, https://github.com/istio/istio/pull/13896 is not for fixing failed tests in this issue. https://testgrid.k8s.io/istio-postsubmits#integration-k8s-tests shows that these tests still fail. 
@yangminzhu Does https://github.com/istio/istio/pull/13896 fix failed tests in this issue?

**Comment by lei-tang** [comment]
@nmittler As far as I know, https://github.com/istio/istio/pull/13896 is not for fixing the failed tests in this issue. https://testgrid.k8s.io/istio-postsubmits#integration-k8s-tests shows that the tests in this issue still fail.
@yangminzhu Does https://github.com/istio/istio/pull/13896 fix failed tests in this issue?

**Comment by lei-tang** [comment]
@nmittler As far as I know, https://github.com/istio/istio/pull/13896 is not for fixing the failed tests in this issue. https://testgrid.k8s.io/istio-postsubmits#integration-k8s-tests shows that the tests in this issue still fail.
@yangminzhu Does https://github.com/istio/istio/pull/13896 fix failed tests in this issue?

**Comment by lei-tang** [comment]
@nmittler As far as I know, https://github.com/istio/istio/pull/13896 is not for fixing the failed tests in this issue. https://testgrid.k8s.io/istio-postsubmits#integration-k8s-tests shows that the tests in this issue still fail.
@yangminzhu Does https://github.com/istio/istio/pull/13896 fix failed tests in this issue?

**Comment by lei-tang** [comment]
@nmittler As far as I know, https://github.com/istio/istio/pull/13896 is not for fixing the failed tests in this issue. https://testgrid.k8s.io/istio-postsubmits#integration-k8s-tests shows that the tests in this issue still fail.
@yangminzhu Does https://github.com/istio/istio/pull/13896 fix failed tests in this issue?

**Comment by lei-tang** [comment]
@nmittler As far as I know, https://github.com/istio/istio/pull/13896 is not for fixing the failed tests in this issue. https://testgrid.k8s.io/istio-postsubmits#integration-k8s-tests shows that the tests in this issue still fail.
@yangminzhu Does https://github.com/istio/istio/pull/13896 fix failed tests in this issue?

**Comment by lei-tang** [comment]
@nmittler As far as I know, https://github.com/istio/istio/pull/13896 is not for fixing the failed tests in this issue. https://testgrid.k8s.io/istio-postsubmits#integration-k8s-tests shows that the tests in this issue still fail.
@yangminzhu Does https://github.com/istio/istio/pull/13896 fix failed tests in this issue?

**Comment by lei-tang** [comment]
@nmittler As far as I know, https://github.com/istio/istio/pull/13896 is not for fixing the failed tests in this issue. https://testgrid.k8s.io/istio-postsubmits#integration-k8s-tests shows that the tests in this issue still fail.
@yangminzhu Does https://github.com/istio/istio/pull/13896 fix failed tests in this issue?

**Comment by lei-tang** [comment]
> @lei-tang
> 
> > @nmittler The PR "[Testing] Change security tests to use Echo" (#13824)  breaks the postsubmit tests; can you revise the PR #13824 to fix the postsubmit test failures caused by the PR #13824?
> 
> It appears that #13896 is passing ... perhaps we should just get that merged?

@nmittler As far as I know, https://github.com/istio/istio/pull/13896 is not for fixing the failed tests in this issue. https://testgrid.k8s.io/istio-postsubmits#integration-k8s-tests shows that the tests in this issue still fail.
@yangminzhu Does https://github.com/istio/istio/pull/13896 fix failed tests in this issue?

**Comment by lei-tang** [comment]
https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/13896/istio-integ-k8s-tests/7897 shows that https://github.com/istio/istio/pull/13896 does not fix tests failed in this issue.

**Comment by lei-tang** [comment]
https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/13896/istio-integ-k8s-tests/7897 shows that #13896 does not fix tests failed in the issue #13895.

**Comment by pitlv2109** [comment]
`TestGroupRBACV1` passed in postsubmit but `TestGroupRBACV2` is still failing.
https://testgrid.k8s.io/istio-postsubmits-master#integration-k8s-tests 
Logs: https://storage.googleapis.com/istio-prow/logs/istio-integ-k8s-tests-master/43/build-log.txt

**Comment by nmittler** [comment]
@pitlv2109 I think I have a fix for that here: #13961

**Comment by pitlv2109** [comment]
Hmm Yangmin's PR (https://github.com/istio/istio/pull/13928) removed the starting `---` in both files, but only one of them passed. Both still have trailing `---` though (but #13961 claims they will fail? again, one of them passed). 

https://github.com/istio/istio/blob/master/tests/integration/security/rbac/v1/group/testdata/istio-group-list-rbac-rules.yaml.tmpl (this one passed, has trailing `---`)
https://github.com/istio/istio/blob/master/tests/integration/security/rbac/v2/group/testdata/istio-group-list-rbac-v2-rules.yaml.tmpl (this one failed, has trailing `---` and also an extra line at then end)

**Comment by pitlv2109** [comment]
I think this test has started passing now (starting from this morning) due to some changes in the test framework.

**Comment by nmittler** [comment]
@pitlv2109 yeah I suspect it was #14023 ... glad it's working.
