### ISSUE TITLE
Extend the CNCF's Istio dashboard to match our needs. 

### ISSUE THREAD

**Issue by geeknoid** [istio/istio#13891]
As described [here](https://github.com/istio/istio/wiki/Project%20Dashboards), the CNCF maintains some dashboards about the Istio project. We'd like to extend this to our needs.

The dashboards are described in <https://github.com/cncf/devstats.> 

The work here is to copy+adapt the kubernetes dashboard definitions for Istio, and then augment with whatever is missing to meet the Code Mauve exit criteria.

The Kubernetes stuff is defined here: <https://github.com/cncf/devstats/tree/master/grafana/dashboards/kubernetes>

The Code Mauve metrics are specified in <https://docs.google.com/document/d/1YeirXz0kGssg5TSBq9f95qHnSe2u6Aa0Z-OlkZ5jXHk/edit> and  <https://docs.google.com/document/d/1oMJITHK9blV6UzTTgJIu-UnNsP_QfYNP26s9_5ILq3E/edit>

**Comment by utako** [comment]
# flakes experienced by PR: Are there metrics that differentiate flakes from real failures on PRs?

**Comment by geeknoid** [comment]
I plan on building some tooling around this. The tooling will eventually tag the issue with a label to indicate "has experience a flake". So can we just agree on a label for the PR or do you need more?

How about simply this label:

has-experienced-a-flake

**Comment by utako** [comment]
That label is clear, and should work as long as `# flakes experienced by PRs` meant the number of PRs with flakes. It looks like that metric was removed from the Istio issues doc today, though.

**Comment by geeknoid** [comment]
Yeah, that's what the metric is intended to capture.

Thanks for working on these dashboards!

**Comment by utako** [comment]
@geeknoid who maintains https://istio.teststats.cncf.io? can i get access?

**Comment by lukaszgryglicki** [comment]
Can't help with this, I have no access to `The Code Mauve` docs mentioned in the issue. You can request bug fixes/new dashboards on CNCF devstats repos.

**Comment by utako** [comment]
submitted feature request here: https://github.com/cncf/devstats/issues/181

**Comment by lukaszgryglicki** [comment]
I'm working on that feature request.

**Comment by geeknoid** [comment]
Hi there,

Any progress on this front?

**Comment by lukaszgryglicki** [comment]
I'm blocked on https://github.com/cncf/devstats/issues/181

**Comment by utako** [comment]
@geeknoid are you still planning on building tooling around a `has-experienced-a-flake` label, or has it been built? 

For `Track how many issues are closed as fixed, duplicate, stale, or unknown`, we have the `stale` label but I don't see any others. Do we have a plan to incorporate these labels into the community workflow?

**Comment by geeknoid** [comment]
It's been slow going to add all this functionality.

I do plan the has-experienced-a-flake label. We've done the groundwork here to track flakes, now we need to finish the top-level part of that and label things and produce a UI on our eng dashboard.

We've tried previously to have disposition labels (stale, fixed, rejected, dupe, not repro, insufficient info), but since GitHub doesn't require those labels to be applied upon close, it ends up being a losing battle to use those labels without extra bots that can bug people if no disposition label is applied. Not great though, but I don't have any other ideas here given the constraints imposed by GitHub.

For the "waiting for additional action" thing, I think this needs to be piggy-backed on the staleness tracker. When an issue is marked as stale, we can add a message to invite the assigner to annotate the issue with the "missing information" label. As soon as the issue's author adds a comment, then label would be removed. If the author never responds, then the issue will be closed with the "insufficient information" disposition.
