### ISSUE TITLE
sidecarInjectorWebhook incorrect nesting in values-istio-demo-common.yaml

### ISSUE THREAD

**Issue by pfenig** [istio/istio#13898]
**Bug description**
The sidecarInjectorWebhook configuration is nested under global when the chart expects it at the top level.

https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/values-istio-demo-common.yaml#L15

**Expected behavior**
It should be at the top level

**Steps to reproduce the bug**
1) Change `rewriteAppHTTPProbe: true` in values-istio-demo.yaml
2) `helm template install/kubernetes/helm/istio --name istio --namespace istio-system --values install/kubernetes/helm/istio/values-istio-demo.yaml | grep rewrite`

Expect: `rewriteAppHTTPProbe: true`
Got: `rewriteAppHTTPProbe: false`

When sidecarInjectorWebhook is at the top level, it works.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.1.5

**How was Istio installed?**
curl -L https://git.io/getLatestIstio | sh -

**Environment where bug was observed (cloud vendor, OS, etc)**
OS X

**Affected product area (please put an X in all that apply)**

[X] Configuration Infrastructure
[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by AsCat** [comment]
@pfenig  I think UR right, the fix should be in  values-istio-demo-common.yaml, the PR in [here](https://github.com/istio/istio/pull/13904)

**Comment by howardjohn** [comment]
Got merged in https://github.com/istio/istio/pull/14880
