### ISSUE TITLE
namespace change

### ISSUE THREAD

**Issue by majorinche** [istio/istio#13902]
i'd like to change namespace from default "istio-system" to another one
but encounter problem on galley pod
failed logs show as following:

2019-05-08T02:49:06.585767Z	warn	Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
2019-05-08T02:49:06.611464Z	warn	validation	Could not find istio-system/istio-galley deployment to set ownerRef. The validatingwebhookconfiguration must be deleted manually
2019-05-08T02:49:06.611559Z	info	validation	Checking if istio-system/istio-galley is ready before registering webhook configuration 
2019-05-08T02:49:06.612138Z	fatal	validation	admission webhook ListenAndServeTLS failed: listen tcp :443: bind: permission denied

checking the script， find the name “istio-system” already coded
vim galley/pkg/crd/validation/webhook.go
...
165 // DefaultArgs allocates an WebhookParameters struct initialized with Webhook's default configuration.
166 func DefaultArgs() *WebhookParameters {
167         return &WebhookParameters{
168                 Port:                          443,
169                 CertFile:                      "/etc/certs/cert-chain.pem",
170                 KeyFile:                       "/etc/certs/key.pem",
171                 CACertFile:                    "/etc/certs/root-cert.pem",
172                 DeploymentAndServiceNamespace: "istio-system",
173                 DeploymentName:                "istio-galley",
174                 ServiceName:                   "istio-galley",
175                 WebhookName:                   "istio-galley",
176                 EnableValidation:              true,

so is it the reason and how can i fix it?

**Comment by linsun** [comment]
This is something we are targeting to fix in the new installer, pls check:  GitHub.com/istio/installer

**Comment by howardjohn** [comment]
Like Lin mentioned, in https://github.com/istio/installer, targeted for 1.2 we will support this (and encourage it). There have been a fair number of changes needed to get this working, so I suspect the current installer in 1.1 would not be able to fully support a different namespace. While there are a lot of places where we are not dependent on `istio-system`, there are probably a few places we explicitly set the namespace as istio-system which may cause issues

**Comment by costinm** [comment]
New installer appears to support this - there are some extra steps on setup to get the proper certificates, but this is a separate usability issue. 

Note that Galley MCP can now run in any namespace with the a-la-carte installer - it uses regular istio certificates verified by envoy. The validation part requires special certs and needs to be handled with care if a different namespace is used.
