### ISSUE TITLE
Development instructions are out of date

### ISSUE THREAD

**Issue by jroper** [istio/istio#13903]
It appears the development environment instructions are out of date and no longer work with master, since 3f1bca2a28abdb337eab8e4324a43341b6cfc4c1, due to the removal of the `generate_yaml` make target. Specifically, these instructions need to be updated:

https://github.com/istio/istio/wiki/Using-the-Code-Base#building-the-istio-manifests

I'm completely new to the Istio codebase (just trying to get started today), but I guess it needs to be updated to `make generate_e2e_yaml`. I would submit a PR but to my knowledge, you can't submit a PR for changes to GitHub wikis.

**Comment by linsun** [comment]
@geeknoid how should we handle this?  user can't submit a pr to wiki.

**Comment by geeknoid** [comment]
Only members of the istio GitHub organization can edit the Wiki. So someone on our side needs to fix it.

**Comment by linsun** [comment]
I don't mind updating wiki directly, however, i would be missing reviews when I update it.

I think the new cmd is installgen

**Comment by linsun** [comment]
page has been updated, thanks @jroper for reporting this

**Comment by jroper** [comment]
No worries, thanks for updating!
