### ISSUE TITLE
non-transparent proxy support

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1390]
@rshriram commented on [Tue Aug 29 2017](https://github.com/istio/old_pilot_repo/issues/1129)

Allow folks to run envoy without the iptables interception.
1. Requires fixed inbound and outbound port (cluster wide) for HTTP services (partly solved via HTTP_PROXY support)
2. a startup flag in pilot that generates appropriate envoy configs
3. real listeners in the outbound path for tcp services
4. omit tcp listeners in inbound path for tcp services.

With this support, Pilot+Envoy can run on any non-k8s platform. Probably also needs the ability to use custom config at pilot-agent end.
cc @kyessenov 

---

@ldemailly commented on [Tue Aug 29 2017](https://github.com/istio/old_pilot_repo/issues/1129#issuecomment-325772686)

is this issue to document/cover #1069 ?

---

@rshriram commented on [Tue Aug 29 2017](https://github.com/istio/old_pilot_repo/issues/1129#issuecomment-325773467)

it goes beyond that. 

---

@ldemailly commented on [Tue Aug 29 2017](https://github.com/istio/old_pilot_repo/issues/1129#issuecomment-325773804)

should be for 0.3 then?

---

@kyessenov commented on [Tue Aug 29 2017](https://github.com/istio/old_pilot_repo/issues/1129#issuecomment-325774431)

It might happen sooner before final 0.2 release. We'll have several 0.2.x ones.

**Comment by rshriram** [comment]
closing (my own issue).. We have HTTP_PROXY for the moment
