### ISSUE TITLE
Istioctl namespace support

### ISSUE THREAD

**Issue by richardwxn** [istio/istio#13900]
@howardjohn commented on [Tue May 07 2019](https://github.com/istio/installer/issues/129)

Right now istioctl takes in an istioSystem argument, but we cannot support multiple namespaces

**Comment by costinm** [comment]
Can you elaborate ? Istio can be installed in other namespaces, and istioctl seems to work with this. 

Operator and default installer are not using multiple namespaces - but advanced users can use the templates directly. 

For example knative is running Istio in a separate namespace.
