### ISSUE TITLE
Check that artifacts and image already exist before pushing them

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1391]
@sebastienvas commented on [Sat Aug 26 2017](https://github.com/istio/old_pilot_repo/issues/1109)

This apply to docker and istioctl. We should not attempt to push an image if it already exists. If possible prevent build as well

---

@sebastienvas commented on [Tue Aug 29 2017](https://github.com/istio/old_pilot_repo/issues/1109#issuecomment-325747946)

This was not the reason of the issue. This is still a good optimization, but does not need to be done as a P0

**Comment by hklai** [comment]
Seems obsolete. Please reopen if this is still an issue.
