### ISSUE TITLE
[Test Framework] Support for Parallel tests

### ISSUE THREAD

**Issue by nmittler** [istio/istio#13915]
The test framework currently has issues when running parallel tests with respect to the teardown of resources. 

Parallelism is important for reducing the test duration.

**Comment by howardjohn** [comment]
Just a comment in case it helps with anything - in istio/installer we run with setup/cleanup disabled and parallel tests and tests seem to work in that case.

**Comment by nmittler** [comment]
@howardjohn I'm not sure that choice of installer has much to do with it.  I have been playing with multiple nested tests with multiple levels of parallelism and there are definitely issues.  When a test calls Parallel(), the parent test exits before it continues, leading to the framework (potentially) destroying resources that it needs (e.g. namespaces).

**Comment by howardjohn** [comment]
Oh got it, I think that is different then. I am talking about omitting the `-p 1` flag, which I think means it will run each test suite in parallel but not individual tests within those suites? I could be wrong though

**Comment by nmittler** [comment]
Yes that's right. The current plan is to switch over to having per-suite targets, where we can allow the tests in the same suite to run in parallel, so we will eventually be able to get rid of the `-p 1` flag.
