### ISSUE TITLE
Stale Ingress certificates after Ingress resource is deleted

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1392]
@andraxylia commented on [Fri Aug 11 2017](https://github.com/istio/old_pilot_repo/issues/1020)

Certifs are still there after resource is deleted:

$ kubectl exec istio-ingress-1709403620-m1czk -n istio12 -- ls /etc/istio/ingress-certs
tls.crt
tls.key

---

@rshriram commented on [Wed Oct 11 2017](https://github.com/istio/old_pilot_repo/issues/1020#issuecomment-335967548)

close if no longer valid

**Comment by rshriram** [comment]
please try gateway.
