### ISSUE TITLE
Citadel should expose 'istio_build' metric

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio#13937]
mixer, pilot, and galley all expose a common `istio_build` metric. this allows tracking deployed versions across rollouts etc.

Citadel should as well. It can be as simple as adding a line like:

`version.Info.RecordComponentBuildTag("citadel")`

to the citadel codebase in server.go or whatever.

See also: https://github.com/istio/istio/issues/13936#issuecomment-490693636

**Comment by howardjohn** [comment]
@wattli your PR on 1.1 got closed, did this ever make it into master?

**Comment by howardjohn** [comment]
Verified this is done
