### ISSUE TITLE
inbound cluster is not listening on IPv6 localhost

### ISSUE THREAD

**Issue by tibetsam** [istio/istio#13942]
**Bug description**
I have pulled latest master branch which include fix for #13117 and #13027

But still inbound cluster for bookinfo productpage is still using ipv4 localhost.

root@mastermint:~/go/src/istio.io/istio# kb get pod productpage-v1-7c8b44b5c5-6fxvc -ojsonpath='{.status.hostIP}{"\n"}'
fd01:0:0:1::100
root@mastermint:~/go/src/istio.io/istio# kb get pod productpage-v1-7c8b44b5c5-6fxvc -ojsonpath='{.status.podIP}{"\n"}' 
fd01:0:0:2::d1

     "cluster": {
      "name": "inbound|9080|http|productpage.default.svc.cluster.local",
      "type": "STATIC",
      "connect_timeout": "10s",
      "circuit_breakers": {
       "thresholds": [
        {}
       ]
      },
      "load_assignment": {
       "cluster_name": "inbound|9080|http|productpage.default.svc.cluster.local",
       "endpoints": [
        {
         "lb_endpoints": [
          {
           "endpoint": {
            "address": {
             "socket_address": {
              "address": "127.0.0.1",
              "port_value": 9080
             }
            }
           }
          }
         ]
        }
       ]
      }
     },
     "last_updated": "2019-05-08T06:55:22.775Z"
    }

**Expected behavior**
it should use ipv6 localhost instead.

I think we can reuse getActualWildcardAndLocalHost() fuction in cluster.go

**Steps to reproduce the bug**
1. install istio
2. enable isito-inject
3. install bookinfo
4. get istio-proxy config from productpage

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
root@mastermint:/# kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
helm install

**Environment where bug was observed (cloud vendor, OS, etc)**
root@mastermint:/# uname -a
Linux mastermint 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by tibetsam** [comment]
@sbezverk i saw you provide the fix IPv6, maybe you can do same for this one?:)

**Comment by sbezverk** [comment]
@tibetsam Thanks for reporting it. Let me look into it and get back to you.

**Comment by mailzyok** [comment]
I this issue was added to 1.2 milestone, however i didn't see #13117 and #13027 (in the issue description) added to 1.2 milestone.  Will 1.2 include all the necessary fixes for IPv6 support?

Thanks
