### ISSUE TITLE
When Duplicate entry of domain curl any domain return 404

### ISSUE THREAD

**Issue by Liv1020** [istio/istio#13940]
**Bug description**
![image](https://user-images.githubusercontent.com/5382358/57446523-71635f00-7287-11e9-9688-fe8396ed4a77.png)

![image](https://user-images.githubusercontent.com/5382358/57446812-29910780-7288-11e9-811f-07f518f30062.png)

Inadvertently posted the wrong configuration causing two domain names inside the route, curl any domain will return 404

**Expected behavior**
return ALLOW_ANY/REGISTRY_ONLY 200/502

**Steps to reproduce the bug**
publish double gateway + virtualservice

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.1.5
**How was Istio installed?**
helm
**Environment where bug was observed (cloud vendor, OS, etc)**
aliyun
**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
Can you provide the Gateway config that is doubled? We had very similar issue in https://github.com/istio/istio/pull/13731 fixed in 1.1.5. Do you see the `pilot_total_rejected_configs` metric incremented?
