### ISSUE TITLE
Back-off restarting failed container for prometheus in istio 1.1.0

### ISSUE THREAD

**Issue by RaduRaducuIlie** [istio/istio#13944]
**Bug description**
Since moving to istio1.1.0 prometheus pod in state "Waiting: CrashLoopBackOff" -Back-off restarting failed container
**Expected behavior**
Update must have been done smoothly.
**Steps to reproduce the bug**
Install istio
Install/reinstall
**Version (include the output of `istioctl version --remote` and `kubectl version`)**
client version: version.BuildInfo{Version:"1.1.0", GitRevision:"82797c0c0649a3f73029b33957ae1052604
58c6e", User:"root", Host:"996cd064-49c1-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerH
ub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-rc.6"}
citadel version: version.BuildInfo{Version:"1.1.0", GitRevision:"82797c0c0649a3f73029b33957ae105260
458c6e-dirty", User:"root", Host:"1f4e9557-49cd-11e9-86e9-0a580a2c0304", GolangVersion:"go1.10.4", 
DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-rc.6"}
galley version: version.BuildInfo{Version:"1.1.0", GitRevision:"82797c0c0649a3f73029b33957ae1052604
58c6e-dirty", User:"root", Host:"1f4e9557-49cd-11e9-86e9-0a580a2c0304", GolangVersion:"go1.10.4", D
ockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-rc.6"}
ingressgateway version: version.BuildInfo{Version:"1.1.0", GitRevision:"82797c0c0649a3f73029b33957a
e105260458c6e", User:"root", Host:"1f4e9557-49cd-11e9-86e9-0a580a2c0304", GolangVersion:"go1.10.4",
 DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-rc.6"}
ingressgateway version: version.BuildInfo{Version:"1.1.0", GitRevision:"82797c0c0649a3f73029b33957a
e105260458c6e", User:"root", Host:"1f4e9557-49cd-11e9-86e9-0a580a2c0304", GolangVersion:"go1.10.4",
 DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-rc.6"}
pilot version: version.BuildInfo{Version:"1.1.0", GitRevision:"82797c0c0649a3f73029b33957ae10526045
8c6e-dirty", User:"root", Host:"1f4e9557-49cd-11e9-86e9-0a580a2c0304", GolangVersion:"go1.10.4", Do
ckerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-rc.6"}
policy version: version.BuildInfo{Version:"1.1.0", GitRevision:"82797c0c0649a3f73029b33957ae1052604
58c6e-dirty", User:"root", Host:"1f4e9557-49cd-11e9-86e9-0a580a2c0304", GolangVersion:"go1.10.4", D
ockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-rc.6"}
sidecar-injector version: version.BuildInfo{Version:"1.1.0", GitRevision:"82797c0c0649a3f73029b3395
7ae105260458c6e-dirty", User:"root", Host:"1f4e9557-49cd-11e9-86e9-0a580a2c0304", GolangVersion:"go
1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-rc.6"}
telemetry version: version.BuildInfo{Version:"1.1.0", GitRevision:"82797c0c0649a3f73029b33957ae1052
60458c6e-dirty", User:"root", Host:"1f4e9557-49cd-11e9-86e9-0a580a2c0304", GolangVersion:"go1.10.4"
, DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-rc.6"}

Kubectl version:
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a
46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1
.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.6", GitCommit:"ab91afd7062d42
40e95e51ac00a18bd58fddd365", GitTreeState:"clean", BuildDate:"2019-02-26T12:49:28Z", GoVersion:"go1
.10.8", Compiler:"gc", Platform:"linux/amd64"}
**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**
helm install install/kubernetes/helm/istio --name istio --namespace istio-system `
   --set global.controlPlaneSecurityEnabled=true `
  --set global.proxy.includeIPRanges="MyServiceCIDR" ` 
  --set certmanager.enabled=true `
  --set grafana.enabled=true `
  --set tracing.enabled=true `
  --timeout 900
**Affected product area (please put an X in all that apply)**
I'm using the values.yaml file provided in istio1.1.0 release.
After moving to istio1.1.0 prometheus container is in failed state and restarts continuosly.Here are the logs from prometheus pod:
level=info ts=2019-05-09T13:43:40.421034394Z caller=main.go:222 msg="Starting Prometheus" version="(version=2.3.1, branch=HEAD, revision=188ca45bd85ce843071e768d855722a9d9dabe03)"
level=info ts=2019-05-09T13:43:40.421103994Z caller=main.go:223 build_context="(go=go1.10.3, user=root@82ef94f1b8f7, date=20180619-15:56:22)"
level=info ts=2019-05-09T13:43:40.421125593Z caller=main.go:224 host_details="(Linux 4.15.0-1040-azure #44-Ubuntu SMP Thu Feb 21 14:24:01 UTC 2019 x86_64 prometheus-789d4676c6-lc6fv (none))"
level=info ts=2019-05-09T13:43:40.421141493Z caller=main.go:225 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2019-05-09T13:43:40.422112191Z caller=main.go:514 msg="Starting TSDB ..."
level=info ts=2019-05-09T13:43:40.422934188Z caller=web.go:415 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2019-05-09T13:43:40.525031407Z caller=main.go:524 msg="TSDB started"
level=info ts=2019-05-09T13:43:40.525069206Z caller=main.go:603 msg="Loading configuration file" filename=/etc/prometheus/prometheus.yml
level=info ts=2019-05-09T13:43:40.528479197Z caller=kubernetes.go:188 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-05-09T13:43:40.529518894Z caller=kubernetes.go:188 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-05-09T13:43:40.620692542Z caller=kubernetes.go:188 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-05-09T13:43:40.62156974Z caller=kubernetes.go:188 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-05-09T13:43:40.622419438Z caller=kubernetes.go:188 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-05-09T13:43:40.720978865Z caller=kubernetes.go:188 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-05-09T13:43:40.721711363Z caller=kubernetes.go:188 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-05-09T13:43:40.722485761Z caller=kubernetes.go:188 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-05-09T13:43:40.723193859Z caller=kubernetes.go:188 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-05-09T13:43:40.723902357Z caller=kubernetes.go:188 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-05-09T13:43:40.724575955Z caller=kubernetes.go:188 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-05-09T13:43:40.821796187Z caller=kubernetes.go:188 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-05-09T13:43:40.822481685Z caller=main.go:500 msg="Server is ready to receive web requests."
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
**Any idea what might cause this? Thank you!**
Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
The logs look healthy, is there no logging from when it actually crashes? It just goes from `Server is ready to receive web requests.` to crashed?

**Comment by RaduRaducuIlie** [comment]
Yes, there  is no logging from when it actually crashes. Logging is `Server is ready to receive web requests` but the container state is "Waiting: CrashLoopBackOff" -Back-off restarting failed container

**Comment by bianpengyuan** [comment]
@RaduRaducuIlie Could you try to run `kubectl describe pods your-prometheus-pod` and see if there is anything abnormal? Looks like some kind of readiness check failure.

**Comment by RaduRaducuIlie** [comment]
Here is the pod described:
Name:               prometheus-789d4676c6-6cwsb
Namespace:          istio-system
Priority:           0
PriorityClassName:  <none>
Node:               aks-nodepool1-40509737-2/10.2.32.227
Start Time:         Fri, 10 May 2019 13:40:27 +0300
Labels:             app=prometheus
                    chart=prometheus
                    heritage=Tiller
                    pod-template-hash=789d4676c6
                    release=istio
Annotations:        scheduler.alpha.kubernetes.io/critical-pod=
                    sidecar.istio.io/inject=false
Status:             Running
IP:                 "internal-ip"
Controlled By:      ReplicaSet/prometheus-789d4676c6
Init Containers:
  prom-init:
    Container ID:  docker://29c15fc039dbf50ac117345d500f83ed22195cf17720d839fed3e02937e7886e
    Image:         busybox:1.30.1
    Image ID:      docker-pullable://busybox@sha256:571799d08f03150e5a882e91ada196a8be808463461d0c8
bef8018c68ee1c267
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
      counter=0; until [ "$counter" -ge 30 ]; do if [ -f /etc/istio-certs/key.pem ]; then exit 0; e
lse echo waiting for istio certs && sleep 1 && counter=$((counter+1)); fi; done; exit 1;
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Fri, 10 May 2019 13:40:31 +0300
      Finished:     Fri, 10 May 2019 13:40:31 +0300
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /etc/istio-certs from istio-certs (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from prometheus-token-5blxq (ro)
Containers:
  prometheus:
    Container ID:  docker://8317f51edfd2ce02a1de3733076e28011489eccc26b84a8ca228bc5f5bbd361d
    Image:         docker.io/prom/prometheus:v2.3.1
    Image ID:      docker-pullable://prom/prometheus@sha256:0283ae2509e1ccc71830edf382713cc3906aa55
ca9418c50911854223829bf0b
    Port:          9090/TCP
    Host Port:     0/TCP
    Args:
      --storage.tsdb.retention=6h
      --config.file=/etc/prometheus/prometheus.yml
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Mon, 13 May 2019 12:17:04 +0300
      Finished:     Mon, 13 May 2019 12:17:25 +0300
    Ready:          False
    Restart Count:  778
    Limits:
      cpu:     100m
      memory:  128Mi
    Requests:
      cpu:      100m
      memory:   128Mi
    Liveness:   http-get http://:9090/-/healthy delay=0s timeout=1s period=10s #success=1 #failure=
3
    Readiness:  http-get http://:9090/-/ready delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      KUBERNETES_PORT_443_TCP_ADDR:  "aksname-rgname"-2356fc-91dab57a.hcp.westeurope.azmk8s
.io
      KUBERNETES_PORT:               tcp://"aksname-rgname"-2356fc-91dab57a.hcp.westeurope.
azmk8s.io:443
      KUBERNETES_PORT_443_TCP:       tcp://"aksname-rgname"-2356fc-91dab57a.hcp.westeurope.
azmk8s.io:443
      KUBERNETES_SERVICE_HOST:       "aksname-rgname"-2356fc-91dab57a.hcp.westeurope.azmk8s
.io
    Mounts:
      /etc/istio-certs from istio-certs (rw)
      /etc/prometheus from config-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from prometheus-token-5blxq (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      prometheus
    Optional:  false
  istio-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  istio.default
    Optional:    true
  prometheus-token-5blxq:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  prometheus-token-5blxq
    Optional:    false
QoS Class:       Guaranteed
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason   Age                  From                               Message
  ----     ------   ----                 ----                               -------
  Warning  BackOff  1m (x18596 over 2d)  kubelet, aks-nodepool1-40509737-2  Back-off restarting fai
led container

**Comment by howardjohn** [comment]
It is getting OOM Killed, did you set the memory limit to 128mi? I don't think that's the default.

**Comment by RaduRaducuIlie** [comment]
Yes, it is set to 128Mi, for all current releases.

**Comment by howardjohn** [comment]
On the default I see:
```
          resources:
            requests:
              cpu: 10m
```

not sure where you got 128 Mi from? Regardless, I think prometheus needs way more than that. In a medium cluster I have prometheus using almost 1gb.

If we do set 128 Mi as the default somewhere, let me know and we can change it

**Comment by arne-klein** [comment]
When removing the comments in `global.defaultResources` in `install/kubernetes/helm/istio/values.yaml`, these are used as defaults for the prometheus deployment and will cause it to continuously crash.
```
global:
  defaultResources:
    requests:
      cpu: 10m
    #   memory: 128Mi
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
```
Should we have a reasonable default (1Gi?) in the values file of the prometheus chart?

**Comment by howardjohn** [comment]
This has been resolved, prometheus needs more memory than was given causing OOM. This is *not* the default, so not changes needed
