### ISSUE TITLE
ServiceRoleBinding for unauthenticated only

### ISSUE THREAD

**Issue by aguromano** [istio/istio#13957]
**Bug description**
Not sure if this is a bug, but just cannot find it in the documentation. So I have a service, and there are paths I need unauthenticated, and others for authenticated. So in order to allow unauthenticated I have set `originIsOptional: true` in the istio Policy. And on the `ServiceRoleBinding` I used:
```
  subjects:
  - user: "*"
```
As stated in the [documentation](https://istio.io/docs/concepts/security/#servicerolebinding), and it works!. How ever, I need to prevent `authenticated` users to access some path, and since I have `user: "*"` I cannot do it.

**Expected behavior**
Have a path enabled for `unauthenticated`, but disabled for `authenticated`

**Steps to reproduce the bug**

1. Set `originIsOptional: true` in the policy.
2. Create a **servicerole** and **servicerolebinding** for unauthenticated, and use `user: "*"` in **servicerolebinding**, and allow them to access some paths.
3. Create a **servicerole** and **servicerolebinding** for authenticated, and allow them to access some other paths, but not the ones allowed in step 2
4. Test with an unauthenticated and an authenticated user.

**Version **
Istio: `1.1.4`
Kubernetes: `v1.12.7-gke.10`

**How was Istio installed?**
Downloaded it with 
```
wget -qO- https://github.com/istio/istio/releases/download/${ISTIO_VERSION}/istio-${ISTIO_VERSION}-linux.tar.gz | tar xvz where ISTIO_VERSION=1.1.4
```

Installed with helm install
Enabled the sidecard injection with
```
kubectl label namespace <namespace> istio-injection=enabled --overwrite
```

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE with NodeImage `Container-Optimized OS (cos)`

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by pitlv2109** [comment]
If I understand you correctly, say you have two paths, `path1` and `path2`, and you want unauthenticated users to access `path1` but not authenticated users?

**Comment by aguromano** [comment]
Hi @pitlv2109 , yes, exactly that! Sorry for explaining it so badly

**Comment by pitlv2109** [comment]
I don't think you can do it currently, since technically authenticated users are also "any users" (this is what `user: "*"` means).

Why would you want authenticated users to not access some paths? They can just use their "any users" privilege (e.g. by logging out) to access those paths, right?

**Comment by aguromano** [comment]
Yes, on this case I get your point and you are right. But for example if I want to allow `unauthenticated` to do the following

```
DELETE /:id/discount-codes/:discountCodeId
```

I have to do it with `DELETE /*`, since `DELETE /*/discount-codes/*` doesn't work, as stated [here](https://github.com/istio/istio/issues/10068#issuecomment-491280861), which ends up allowing anyone to delete any path on that service.

So yeah, probably its more important to be able to properly allow some PATHs (with multiple wildcards or wildcard at the end), than triggering `unauthenticated` only.

Thanks again for the help @pitlv2109 !

**Comment by yangminzhu** [comment]
> Yes, on this case I get your point and you are right. But for example if I want to allow `unauthenticated` to do the following
> 
> ```
> DELETE /:id/discount-codes/:discountCodeId
> ```
> 
> I have to do it with `DELETE /*`, since `DELETE /*/discount-codes/*` doesn't work, as stated [here](https://github.com/istio/istio/issues/10068#issuecomment-491280861), which ends up allowing anyone to delete any path on that service.
> 
> So yeah, probably its more important to be able to properly allow some PATHs (with multiple wildcards or wildcard at the end), than triggering `unauthenticated` only.

Probably we should support regex in this case, in addition to the prefix/suffix.

> 
> Thanks again for the help @pitlv2109 !

**Comment by pitlv2109** [comment]
Yep. I talked to @liminw this morning about supporting regex. I don't think there are any drawbacks. We should discuss offline about this :)

**Comment by yangminzhu** [comment]
> Yep. I talked to @liminw this morning about supporting regex. I don't think there are any drawbacks. We should discuss offline about this :)

The problem is how do you know if it's a regex expression in the policy. It would be a tricky implementation without changing the API.

**Comment by pitlv2109** [comment]
We can use some key word or characters to indicate that we should use reg ex for this? This doesn't require change the API. For example:

```
paths: ["regex:<your regex>", <normal, non-regex path]
```

**Comment by jpatters** [comment]
Instead of introducing another syntax for matching strings, I think it would be nice to add some consistency to the apis and use `StringMatch` like in `VirtualService` and `Gateway`.
ie:
```
paths:
- exact: /v1
- regex: "\/.*/docs\/.*"
- prefix: /v2
```
