### ISSUE TITLE
Implement test framework support for example testing

### ISSUE THREAD

**Issue by geeknoid** [istio/istio#13964]
See https://docs.google.com/document/d/1ilZUZvuH_OaebxC7jdpySmJdEju_3neytMaamIqy9fI/edit?ts=5cd49196# for details.

**Comment by brian-avery** [comment]
Still working on this.

**Comment by howardjohn** [comment]
What is left to do here? Write tests?

**Comment by brian-avery** [comment]
This was implemented by https://github.com/istio/istio/pull/17119
