### ISSUE TITLE
ability to change envoy configuration without istio code change/release

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1396]
@ldemailly commented on [Fri Jun 16 2017](https://github.com/istio/old_pilot_repo/issues/883)

there should be an optional "merge" or "patch" or externalized template so people can tweak the resulting envoy configs

ps: it does mean they can also break istio but that's not a reason to have it completely locked down and hardcoded like now

---

@rshriram commented on [Fri Jun 16 2017](https://github.com/istio/old_pilot_repo/issues/883#issuecomment-309169141)

I don't think this is a good idea. We have covered 90% of Envoy config.
Allowing people to break istio while trying to provide seamless experience
is contradictory.

Very few people have asked for this.

---

@ldemailly commented on [Fri Jun 16 2017](https://github.com/istio/old_pilot_repo/issues/883#issuecomment-309171327)

it should be possible to patch or change config without making a new release - if only for emergency fixes

---

@kyessenov commented on [Sat Jun 17 2017](https://github.com/istio/old_pilot_repo/issues/883#issuecomment-309230885)

Plausible but difficult to reconcile custom templates with machine-generated config. Feels like a hacky workaround overall. Assigning it to you to think of ways to reconcile the two.

---

@ldemailly commented on [Thu Aug 17 2017](https://github.com/istio/old_pilot_repo/issues/883#issuecomment-323226763)

putting it for 0.3 as I'm pretty sure we'll learn in 0.2 and rawvm that we need this

**Comment by cmluciano** [comment]
@ldemailly Are you working on this? 

cc @ayj Is this effectively the template that we are working on?

**Comment by ayj** [comment]
No, this is referring to externalizing envoy's [configuration](https://www.envoyproxy.io/envoy/configuration/configuration) so a user could, for example, tweak filter settings that aren't exposed through existing Istio config.

**Comment by ldemailly** [comment]
@cmluciano no but I think it'd be very useful so users can try / tweak envoy features

**Comment by louiscryan** [comment]
I think this is stale. We have a proposal for injected extensions and for plugins / api proxying

**Comment by rshriram** [comment]
Just referring to the PR for this: #6401 ..
