### ISSUE TITLE
Rewrite istio-iptables.sh in go for testability

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#13967]
The current istio-iptables.sh is a extremely critical part of Istio, yet is poorly tested and relies on all sorts of crazy bash stuff that most people don't really understand. This makes it hard to test (I think we just recently added some tests, but only for a small part of the code). Since it it hard to test, it is also hard to confidently change (for example: https://github.com/istio/istio/pull/13579#discussion_r282694480).

I don't think "If it ain't broke don't fix it" applies here. Rewriting may cause some risk of changes, but will allow future changes to be made safely and allow us to get better coverage of the existing code, so I think it is safer overall.

**Comment by howardjohn** [comment]
Another example motivation: https://github.com/istio/istio/pull/13970/files

**Comment by kramerul** [comment]
We at SAP started an implementation in go.

**Comment by kramerul** [comment]
We created a PR (#14071) for this issue.

**Comment by costinm** [comment]
I'm not sure how go will help testing - what needs to be tested is if the actual rules work. Go or shell or anything else - the test would be the same, code to verify that after the rules are applied the interception 
works as expected. 

And independent of this, we want users to be able to understand what is going on and be able to 
either customize or take parts and integrate with their own iptables - as would be the case on VMs 
where user already has iptables.

**Comment by holgero** [comment]
> I'm not sure how go will help testing 

Shell code is notoriously hard to test. For go coding it is so much easier to write good unit tests. 

>... - what needs to be tested is if the actual rules work. Go or shell or anything else - the test would be the same, code to verify that after the rules are applied the interception works as expected.

This can be done and should be independently, too.

> And independent of this, we want users to be able to understand what is going on

Agreed, therefore we log extensively what is been done in the executable. And on the other hand, a 530 lines long shell script is not easy to digest either. I would argue that at some point go source becomes easier to understand.

>  and be able to
> either customize or take parts and integrate with their own iptables - as would be the case on VMs
> where user already has iptables.

This is a goal? Are you sure about this?

**Comment by costinm** [comment]
Unit tests are not the problem here - the actual functionality of the rules is what must be tested. 
User may use ufw or other frameworks - and may also modify the script to add his own rules and customizations. What needs to be tested is kernel actually captures what we want.

I am pretty sure real customers have integrated or modified the iptables script with other rules,
and that many VMs have additional iptables rules and at least some admins look carefully at 
what is actually applied and would not appreciate an opaque binary messing with the firewall.

I'm not disagreeing that the 530-lines script has become too complicated. It is relatively 
easy to simplify it - the TPROXY stuff never got enough testing and can be removed, and 
1/2 deals with command line flags we are likely to replace with just env variables, to make it
easier to kustomize.   And once we have split filter chains - the remaining script will be back to 
the simple chains we had initially.

**Comment by costinm** [comment]
Also, the plan of record is to stop using iptables in the first place - CNI will start separate docker 
containers for the sidecars, and this will allow using only routing, without contraq.

**Comment by sdake** [comment]
For distroless images (of which no customers are using atm nor have customized rules), a go rewrite is fine, and will be welcome in the CNI implementation in the future.

The idea of simplifying the bash is orthogonal to the desire to having go code that can be properly unit tested.

@costin, I have to mostly agree with @holgero here, that having both in the repo (one for distroless, one for operators that want to customize their rules) doesn't cause any harm in the short term and only upside in the long term.

Cheers
-steve

**Comment by rlenglet** [comment]
Instead of calling `iptables` for every single rule, as the current Go reimplementation does, a better design would be to generate one list of rules for `iptables-restore`, and call `iptables-restore`. That's only one command to run, and it's easier to test a long string like the input to `iptables-restore` than a series of commands.

**Comment by kramerul** [comment]
@rlenglet , that's a great idea. 

Currently, the go-version and the shell script of `istio-iptables` exist in parallel. The go-version is only used in distroless images. Both versions use the same golden master tests to ensure that they are doing the same.
Therefore, the first step should be to replace the shell script with the go-version. Afterwards, a refactoring of the go-version could take place.

**Comment by abhide** [comment]
Discussed with @rlenglet about this issue, and will work on it.

**Comment by howardjohn** [comment]
@abhide if you haven't seen there is already some work on this merged in , I think cni uses it

**Comment by rlenglet** [comment]
@howardjohn CNI doesn't use it yet, but we'll get there at some point.

**Comment by abhide** [comment]
Making some progress on this issue:

**Comment by abhide** [comment]
Refactored go implementation and added unit tests for individual modules.
Added support for `istio-restore` to Golang implementation. 

Starting to do change to do end-to-end tests for golang implementation with `iptables-restore'

**Comment by rlenglet** [comment]
@abhide since you enabled `iptables-restore` by default, the trick will be to run the whole test suite using `proxyv2`'s `distroless` variant. @howardjohn do you know how we could do that?

**Comment by howardjohn** [comment]
We have a test using distroless already is that sufficient?

**Comment by abhide** [comment]
@howardjohn @rlenglet I meant running e2e tests that would use golang implementation. 
I think if I set `BASE_DISTRIBUTION` to `distroless` in Dockerfile; the golang implementation will get invoked. See this in almost all Dockerfile. Wanted to know which ones change?

**Comment by abhide** [comment]
> We have a test using distroless already is that sufficient?

are you referring to `e2e-simpleTests-distroless_istio`?

**Comment by howardjohn** [comment]
Yes, all of the tests use ubuntu images (and therefor bash iptables) except `e2e-simpleTests-distroless_istio` which is using the go impl.

**Comment by abhide** [comment]
> Yes, all of the tests use ubuntu images (and therefor bash iptables) except `e2e-simpleTests-distroless_istio` which is using the go impl.

Hmm.. that seems very limited: 
```TestSimpleIngress
TestSvc2Svc
TestAuth
TestAuthWithHeaders
TestNginx
TestNginx/Reachable```

**Comment by abhide** [comment]
To get more test coverage; we might have to add `--variant distroless` to some jobs under prow.
Similar to https://github.com/istio/test-infra/blob/master/prow/config/jobs/istio.yaml#L122

@howardjohn @rlenglet what do you think?

**Comment by abhide** [comment]
^^^ Referred wrong GH issue in PR

**Comment by rlenglet** [comment]
> To get more test coverage; we might have to add --variant distroless to some jobs under prow.

Yes, good idea. It would be nice to run all tests with that config.

**Comment by howardjohn** [comment]
We don't have the resources to double the number of tests we run, we already run way too many e2e tests

**Comment by abhide** [comment]
@howardjohn understand your point. I didnt mean to run double the tests continuously. I want to make a WIP PR and how the entire E2E CI looks like. 

Seems like making a PR to test-infra wont trigger the e2e ci for istio repo.
Can you tell me what I need to do to run e2e tests locally?

**Comment by howardjohn** [comment]
Ah one time, that is good.

Yeah it is unfortunate we cannot make changes to the test config in a pr to trigger runs. See https://github.com/istio/test-infra/issues/1734

To run the tests locally, you should be able to run the exact script that is defined in test-infra, like ` prow/e2e-kind-suite.sh --auth_enable --single_test e2e_simple --installer helm --variant distroless`

Anothre option would be to submit a change to istio/istio that modifies prow/e2e-kind-suite.sh to make `--variant distroless` the default, which will run all of them as distroless. Probably the easiest optin

**Comment by abhide** [comment]
I like your last option! 😄 😄

**Comment by howardjohn** [comment]
Should we just make the non-distroless one use the golang impl as well? afaik the only motivation to having it not was for stability purposes

**Comment by abhide** [comment]
@howardjohn we can change non-distroless to use golang impl. I would like to get a CI run with golang to see what issues we run into.

Compared to bash script, golang impl has way more unit test coverage and we can improve that.

Can you take a look at my latest comment on: https://github.com/istio/istio/pull/18962

**Comment by abhide** [comment]
@howardjohn @rlenglet I think we can close this issue now as `fixed`? :)
