### ISSUE TITLE
istio-iptables.sh doesn't handle IPv6 address ranges correctly

### ISSUE THREAD

**Issue by kramerul** [istio/istio#13980]
**Bug description**

Using the `-x` or `-i` option in `istio-iptables.sh` with a valid IPv6 address range (e.g. `1111:a2a2:b3b3:c4c4:d5d5:e5e5:f6f6:a8a8/32` ) doesn't work properly. There is no `ip6tables` command executed with this ip range.

**Expected behavior**

Script works correctly

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

master

**How was Istio installed?**

N/A

**Environment where bug was observed (cloud vendor, OS, etc)**

N/A

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
@sbezverk fyi

**Comment by sbezverk** [comment]
@kramerul Hello, thanks a lot for reporting the issue. Have you managed by any chance to collect the resulting ip6tables or any error generated. I have a unit test which is testing ip addresses for validity. Have you tried to add this address and run test? I will look into this issue and get back to you as soon as I have any results.

**Comment by kramerul** [comment]
@sbezverk I had a look at the resulting `ip6tables` commands. There was no command executed where the IPv6 address from the command line was included.

**Comment by kramerul** [comment]
This problem was caused by the fact, that the local IP address had version V4. Therefore `ENABLE_INBOUND_IPV6` was empty.
