### ISSUE TITLE
How does pilot retrieve and apply configuration in Kubernetes?

### ISSUE THREAD

**Issue by yuchen9459** [istio/istio#13981]
I am using Istio with Kubernetes currently. As far as I know, the pilot in control plane is responsible for the configuration of data plane (Envoy proxy), and we configure Istio with YAML file in Kubernetes. 

For example, if we want to configure a new virtual service, we will use `kubectl apply -f newvs.yaml`. I wonder how does Istio pilot retrieve the configuration and apply the new configuration in each data plane? Does it get from the Kubernetes master or somewhere else?

I was searching around and read several blogs but I didn't find an answer.

**Comment by howardjohn** [comment]
Generally [Galley](https://istio.io/docs/concepts/what-is-istio/#galley) is used to read from kubernetes api server and pushes the config to Pilot. I am not very familiar with Galley but afaik all of the code for that can be found here https://github.com/istio/istio/tree/master/galley/pkg/source/kube.

I believe everything is based on [shared informers](https://www.firehydrant.io/blog/stay-informed-with-kubernetes-informers/)

**Comment by pitlv2109** [comment]
Galley subscribes to resources and when said resources are pushed to your k8s cluster, Galley will receive them, do some validation and push them to Pilot. Pilot then convert resources to Envoy config and distribute it to appropriate sidecars.
