### ISSUE TITLE
envVar framework logs errors too liberally

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#13995]
I see a lot of logs like: `warn    Invalid environment variable value ``, expecting true/false, defaulting to true`.

It seems if a variable is not provided, we should just use the default, this is not an exceptional case - most feature flags will actually never be set at all.

**Comment by geeknoid** [comment]
This error message is puzzling. This message only comes out if an environment variable is defined but the type of data it holds is not what is expected. In this case, it is saying the environment variable has no value. Is that a valid thing, to have environment variables that are defined but don't have a value?

**Comment by howardjohn** [comment]
Oh I actually misunderstood this. It is not common to be set to empty string, but I happened to have it set to one because of some stuff I was doing locally. I thought this happened even when it was unset. Seems like it behaves in a reasonable way
