### ISSUE TITLE
Disable MySql filter by default

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#13998]
As of May 2019 mysql filter in envoy is `experimental`.
Pilot configures a `envoy.filters.network.mysql_proxy` filter when the service port is named `mysql`. This port name is default in most helm charts. The result is that most customers start using the mysql filter without opting in.

We have seen customer reported mysql connection issues when upgrading from 1.0.x to 1.1.x

MySQL filter should be enabled only when requested by the user.

1. Keep this behind a feature flag until mysql filter become stable.
2. Use a different magic name instead of `mysql` which will be opt-in

I prefer option 1.

**Comment by howardjohn** [comment]
Prefer option 1 as well. Perhaps option 2 was better when we first introduced the feature but it is too late now
