### ISSUE TITLE
For same service X, different workload sidecar has different region/zone info on outbound cluster

### ISSUE THREAD

**Issue by incfly** [istio/istio#13994]
**Envoy Cluster does not always same region zone info**

**Expected behavior**
Without config push, when mesh is stabilized, for a same outbound cluster X, we should expect the same `region`, `zone` info on all client side CDS.

**Steps to reproduce the bug**
Deploy a large number of the workloads, do query on Prometheus for the selected workloads, need to exclude ingress, since that will have different cds config for sure.

`envoy_cluster_manager_cds_version{namespace="test-namespace"}`, we can see different number of the cds hash.

Dig down into the envoy `localhost:15000/clusters` in different workloads, we can see that same cluster X, have region/zone info on some workloads, but not on some others.

The ratio is roughly 1%. Still worth calling out though.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.1.2

**How was Istio installed?**
istio-demo.yaml

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

[X] Networking
[X ] Performance and Scalability
[ ] Policies and Telemetry

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
Additional info - 1% may actually be huge, because I *think* this is the same locality used for locality LB, in which case 1% of workloads would not respect the locality rules

**Comment by howardjohn** [comment]
I have been able to reproduce this consistently and confirmed that this DOES impact locality LB.

Steps I followed:

Deploy a service. Locality is applied correctly.
`kubectl scale` it up, new instances don't get locality: Verified with 

```
$ curl -s http://localhost:15000/clusters | grep identity | grep region
outbound|80||identity.envoylite.svc.cluster.local::10.60.22.82:8080::region::us-central1
outbound|80||identity.envoylite.svc.cluster.local::10.60.22.85:8080::region::
outbound|80||identity.envoylite.svc.cluster.local::10.60.23.78:8080::region::
outbound|80||identity.envoylite.svc.cluster.local::10.60.24.10:8080::region::
outbound|80||identity.envoylite.svc.cluster.local::10.60.24.9:8080::region::
```

Then send traffic to the endpoint
```
$ for i in {0..10}; do curl identity; done
Hello from behind service a! hostname: 10.60.22.82
Hello from behind service a! hostname: 10.60.22.82
Hello from behind service a! hostname: 10.60.22.82
Hello from behind service a! hostname: 10.60.22.82
Hello from behind service a! hostname: 10.60.22.82
Hello from behind service a! hostname: 10.60.22.82
Hello from behind service a! hostname: 10.60.22.82
Hello from behind service a! hostname: 10.60.22.82
Hello from behind service a! hostname: 10.60.22.82
Hello from behind service a! hostname: 10.60.22.82
Hello from behind service a! hostname: 10.60.22.82
```

We see it only goes to the one with locality set


Impact for user: if they have locality LB set they may see only one instance getting traffic

fyi @liamawhite @hzxuzhonghu 

I am actively working on this btw, but haven't found root cause yet so wanted to give an update
