### ISSUE TITLE
SSO(SAML2) support for the various UI(Dashboard)

### ISSUE THREAD

**Issue by pc-rshetty** [istio/istio#13991]
**Describe the feature request**
Currently the UI for observability like Grafana etc can be used only if user has port forward access. It would be great if this is exposed using SSO using saml2

**Describe alternatives you've considered**
Currently only the admin has access using portforward. since it is very risky to give port forward to everyone. 

**Additional context**

**Comment by pc-rshetty** [comment]
This feature IMHO is very critical to the success if Istio since observability is a key aspect and if normal non admin users like developers are unable to view what is going on then it might not make sense to stick with Istio. 
We are exploring AWS Mesh just for this reason

**Comment by douglas-reid** [comment]
@pc-rshetty to be clear, port-forward access is **not** required. please see: [Remotely Accessing Telemetry Addons](https://istio.io/docs/tasks/telemetry/gateways/).

**Comment by pc-rshetty** [comment]
thanks @douglas-reid  will give it a try.

**Comment by howardjohn** [comment]
Presumed fixed by  Remotely Accessing Telemetry Addons.
