### ISSUE TITLE
Operator needs to integrate with Istio common packages

### ISSUE THREAD

**Issue by geeknoid** [istio/istio#14001]
The operator component needs to fully embrace the Istio common packages:

- Use Cobra for command-line parsing.
- Use istio/pkg/log for logging.
- Use istio/pkg/env to read environment variables
- Use istio/pkg/version for standard versioning support
- Use istio/pkg/ctrlz for standerd introspection support
- Use istio/pkg/collateral to support doc output for use on istio.io

**Comment by costinm** [comment]
Not sure operator will be ready for 1.2 - and if it is it'll be very alpha, we can fix this kind of issues in 1.3.
