### ISSUE TITLE
CNI plugin needs to integrate with Istio common packages

### ISSUE THREAD

**Issue by geeknoid** [istio/istio#14002]
The CNI plugin component needs to fully embrace the Istio common packages:

- [ ] Use Cobra for command-line parsing.
- [x] Use istio/pkg/log for logging.
- [ ] Use istio/pkg/env to read environment variables
- [ ] Use istio/pkg/annotations to declare K8s annotations
- [ ] Use istio/pkg/version for standard versioning support
- [ ] Use istio/pkg/ctrlz for standerd introspection support
- [ ] Use istio/pkg/collateral to support doc output for use on istio.io

**Comment by geeknoid** [comment]
See these PRs in the operator repo for the steps needed to get onboard.

https://github.com/istio/operator/pull/24
https://github.com/istio/operator/pull/25

**Comment by geeknoid** [comment]
This needs to be done before CNI can be released to customers.

**Comment by rlenglet** [comment]
I got started on moving logging.

**Comment by rlenglet** [comment]
The biggest motivation will be the ability to integrate code from `istio/istio`, esp. the Golang port of `istio-iptables.sh`.

**Comment by geeknoid** [comment]
@tiswanso 

Several comments...

- The motivation for using cobra for command-line parsing is that our other libraries assume it. pkg/logging, pkg/ctrlz, pkg/collateral, pkg/version all assume you use cobra for command-line parsing.

- pkg/annotations is indeed gone. Register annotations in istio/api/annotations instead.

- You should use pkg/env even in tests. Otherwise when we turn on linting for env var usage in this repo, it'll trigger a warning.

- The recent improvements I did to the build system should take care of BuildInfo.

- Adding support for ctrl-z is a one-line to start with. You don't need to add custom integration if you don't need. I don't think you need any new container, etc.

**Comment by tiswanso** [comment]
Thanks @geeknoid for the responses.

re: cobra, ctrlz, version...
Just to make sure the CNI component runtime architecture is understood...
-  CNI plugins are executables that get exec'd by kubelet **on every pod lifecycle event**
-  The golang code in `istio/cni` is currently only the CNI plugin binary and tests.
-  The istio-cni daemonset contains only 1 container that is a bash program that installs/uninstalls the binary on each node and adds to the node's CNI config file.

So, the golang code not being a daemon or an executable ever used by anything other than kubelet is why I'm saying it doesn't necessarily make sense to integrate cobra/ctrlz/version in there.  IMHO, it makes the most sense to refactor the daemonset bash program to golang or create a new golang program for another container in the daemonset to usefully integrate with these specific istio libs and to get the benefits of the toolchains built upon them.

**Comment by geeknoid** [comment]
@tiswanso Thanks for the context.

I don't want to force unnatural stuff onto CNI just for the sake of meeting a checklist requirement. So let's consider each item separately and make sure it is reasonable.

We would like our source code to all be using a common logging solution, that's pkg/log. I think that's meaningful for CNI too, correct?

Configuring log parameters is normally done from the command-line at startup, or dynamically via browser by connecting to a ctrlz port. In the context in which the CNI binary is run, is there opportunity for the user to control the command-line parameters passed to the CNI binary?

From what you say, the lifetime of the CNI binary is very short, it's not a long-live thing running constantly like Galley or Pilot. So pkg/ctrlz wouldn't make sense as there's no way for a user to connect and interact with the process at runtime as it is ephemeral in nature.

pkg/collateral exists in order to produce the documentation reference page for each of our binary for istio.io: <https://istio.io/docs/reference/commands/>. If the CNI binary has effectively no command-line options, then is probably no value in having any reference page generated for it, so no need to integrate with pkg/collateral. But if we do need a reference page, then we'll need to integrate with pkg/collateral which in turns means using cobra for arg parsing (since pkg/collateral gets all its doc content by leveraging the cobra state)

**Comment by tiswanso** [comment]
> @tiswanso Thanks for the context.
> 
> I don't want to force unnatural stuff onto CNI just for the sake of meeting a checklist requirement. So let's consider each item separately and make sure it is reasonable.
> 
> We would like our source code to all be using a common logging solution, that's pkg/log. I think that's meaningful for CNI too, correct?
> 
Yes this is meaningful for CNI.  Currently, we're using logrus lib.  I believe @rlenglet has started moving CNI to istio/pkg/log so I haven't gotten into details on that yet.

> Configuring log parameters is normally done from the command-line at startup, or dynamically via browser by connecting to a ctrlz port. In the context in which the CNI binary is run, is there opportunity for the user to control the command-line parameters passed to the CNI binary?
> 

Right... in the case of the istio-cni executable, it gets its logging config from the node's CNI config file.  Currently, the istio-cni portion of that config is setup by the bash program in the istio-cni daemonset.  To modify the istio-cni config an operator would have to modify the `istio-cni-config` configmap and restart the istio-cni daemonset.  So, moving the istio-cni daemonset to ctrlz support should improve that experience.  It would require refactoring the bash program and creating a new golang portion of the daemonset.  

Also, the version ctrlz support seems useful and low-hanging fruit if/when ctrlz is there.

> From what you say, the lifetime of the CNI binary is very short, it's not a long-live thing running constantly like Galley or Pilot. So pkg/ctrlz wouldn't make sense as there's no way for a user to connect and interact with the process at runtime as it is ephemeral in nature.
> 
Right ... ctrlz support within the CNI binary itself doesn't make sense.

> pkg/collateral exists in order to produce the documentation reference page for each of our binary for istio.io: https://istio.io/docs/reference/commands/. If the CNI binary has effectively no command-line options, then is probably no value in having any reference page generated for it, so no need to integrate with pkg/collateral. But if we do need a reference page, then we'll need to integrate with pkg/collateral which in turns means using cobra for arg parsing (since pkg/collateral gets all its doc content by leveraging the cobra state)

Yeah... I think this makes sense to integrate with the daemonset.  The reference page seems useful.  So, another compelling reason.  

Also, my initial reading of ctrlz leads me to believe there's good potential for adding status query/reporting type support under custom topics which could be an avenue to address some troubleshooting concerns for the istio-cni.

**Comment by sdake** [comment]
> I got started on moving logging.

@rlenglet I have been looking at the broken `go mod tidy` in cni.  As a result, the conclusion was that logging is busted, and needs to be functional.  I have work in progress to fix up logging.  If you don't think you will get to this in the next few days, let me know, otherwise, I will submit a PR for atleast the log implementation.  I will need heavy reviewing :)

Cheers
-steve

**Comment by rlenglet** [comment]
@sdake If you can get to doing that, that'd be great, thanks! I will review your PR(s).

**Comment by rlenglet** [comment]
@sdake I worked on fixing logging months ago, but didn't finish the work. My WIP branch is at https://github.com/istio/cni/tree/fix-logging. You could use it as a starting point?

**Comment by rlenglet** [comment]
not stale
