### ISSUE TITLE
Single page output for protoc-gen-docs

### ISSUE THREAD

**Issue by labkode** [istio/istio#14008]
Hi, 

first of all, kudos for the nice protoc-gen-docs tool.

It would be nice to have a mode where you can generate a single page output with the structure defined below. This structure makes easy to create single page documents (HTML, PDFs, RFCs) where you only have one index file. The current modes only allows you to have fragments per package level, not as a whole

# Package 1

### Message 2

# Package 2

### Message 2

**Comment by howardjohn** [comment]
@geeknoid do you plan to do this?

**Comment by geeknoid** [comment]
No, I'm not planning to do this work. I'd welcome any contributions to that effect though :-)
