### ISSUE TITLE
anyway to adjust service metrics histogram resolution in istio performance testing

### ISSUE THREAD

**Issue by ardenxu** [istio/istio#14004]
we are using perf/load testing tools to verify istio's performance with one namespace & 20 services.
 with 1000 QPS, we want to get p50/p90/p95 latency data, but found out P90 and P95 even P80 has  same latency value around 500 ms.

histogram_quantile(0.95, sum(rate(fortio_request_duration_seconds_bucket[5m])) by (le))

based on service metrics data, looks delay over 500ms will be counted in "le="+Inf"part. is it possible to adjust the latency resolution via config?  so we can know the real latency data in our case. thanks.

# TYPE service_request_duration_seconds histogram
service_request_duration_seconds_bucket{code="200",le="0.007"} 5691
service_request_duration_seconds_bucket{code="200",le="0.008"} 7093
service_request_duration_seconds_bucket{code="200",le="0.009"} 8609
service_request_duration_seconds_bucket{code="200",le="0.01"} 10185
service_request_duration_seconds_bucket{code="200",le="0.011"} 11830
service_request_duration_seconds_bucket{code="200",le="0.012"} 13442
service_request_duration_seconds_bucket{code="200",le="0.014"} 16672
service_request_duration_seconds_bucket{code="200",le="0.016"} 20007
service_request_duration_seconds_bucket{code="200",le="0.018"} 23130
service_request_duration_seconds_bucket{code="200",le="0.02"} 26131
service_request_duration_seconds_bucket{code="200",le="0.025"} 33000
service_request_duration_seconds_bucket{code="200",le="0.03"} 38979
service_request_duration_seconds_bucket{code="200",le="0.035"} 44241
service_request_duration_seconds_bucket{code="200",le="0.04"} 49167
service_request_duration_seconds_bucket{code="200",le="0.045"} 53620
service_request_duration_seconds_bucket{code="200",le="0.05"} 57729
service_request_duration_seconds_bucket{code="200",le="0.06"} 65257
service_request_duration_seconds_bucket{code="200",le="0.07"} 71881
service_request_duration_seconds_bucket{code="200",le="0.08"} 78005
service_request_duration_seconds_bucket{code="200",le="0.09"} 83686
service_request_duration_seconds_bucket{code="200",le="0.1"} 88876
service_request_duration_seconds_bucket{code="200",le="0.12"} 98584
service_request_duration_seconds_bucket{code="200",le="0.14"} 107432
service_request_duration_seconds_bucket{code="200",le="0.16"} 115621
service_request_duration_seconds_bucket{code="200",le="0.18"} 122914
service_request_duration_seconds_bucket{code="200",le="0.2"} 129519
service_request_duration_seconds_bucket{code="200",le="0.25"} 144404
service_request_duration_seconds_bucket{code="200",le="0.3"} 156277
service_request_duration_seconds_bucket{code="200",le="0.35"} 166657
service_request_duration_seconds_bucket{code="200",le="0.4"} 175283
service_request_duration_seconds_bucket{code="200",le="0.45"} 182717
service_request_duration_seconds_bucket{code="200",le="0.5"} 189152
service_request_duration_seconds_bucket{code="200",le="+Inf"} 215936

**Comment by howardjohn** [comment]
These metrics are not from istio, so I am going to close this. Istio metrics are istio_request_duration_seconds_bucket, you are looking at fortio metrics
