### ISSUE TITLE
Setup long running tests with 1000 services

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#14012]
The purpose of this test is to ensure stability of istio and collect metrics.

- [ ] Long running cluster created by isotope with a standard topology.
1000 services   4 levels deep
1000 sidecars 
1000 virtualservices
100 services share a port.. (so 10 ports)

Add flapping service. Flip-flops between healthy and unhealthy.
Add and remove virtual services and service entries.

Default configuration - envoy access logs on, mixer access logs on
Proxy - 500 mCPU
Pilot and Mixer get 7000 mCPU

- [ ] start 2 http servers. separate http server for metrics on a standard port.
- [ ] add "port" support to mock application
- [ ] Check and upgrade nightly on a cron job
- [ ] Watch for 503s/404s during upgrade
- [ ] Watch for errors, memory spikes during upgrade

Future
- [ ] Measure Config push time from Pilot
- [ ] Measure and record startup time
- [ ] Extract metrics summary several times a day
- [ ] Watch and alert on core dumps / memory spike etc

**Comment by howardjohn** [comment]
I believe all of these steps are done now
