### ISSUE TITLE
e2e checkLogs in mixer unreliable in minikube

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1401]
@andraxylia commented on [Mon Aug 21 2017](https://github.com/istio/old_pilot_repo/issues/1088)

Pilot e2e checkLogs check for the existence of a request ID in mixer logs.

I have seen mixer logs rotate in minikube, it seems rotation is enabled by default:

https://github.com/kubernetes/minikube/issues/830

The VM has something like this:
https://stackoverflow.com/questions/39021832/kubernetes-how-to-set-the-maximum-size-of-the-log-file

checkLogs parameter should be disabled by default, since it is expensive and flaky/misleading. The absence of a request ID in the logs can be due to rotation, not to a bug.

**Comment by hklai** [comment]
Is this still an issue?

**Comment by andraxylia** [comment]
Closing, I removed that logic a while ago, it was too expensive.
