### ISSUE TITLE
Add change scenarios to log running tests

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#14010]
https://github.com/istio/tools/blob/master/perf/servicegraph/templates/
contains a config-changer pod, at present this pod just adds and removes a virtual service.
Add the following to this config changer

I . Application editions
1. Add version to service graph services
2. Add 2 versions of a particular service, and thru a virtual service use weighted routing to affect application rollout from v1 --> v2
3. Do a roll back from v2 --> v1 

II. Use egress proxy to route requests

III. Use middle proxy from ns1 to ns2

**Comment by howardjohn** [comment]
We have added version rollouts and deployment scaling up/down, so I think this is pretty much done
