### ISSUE TITLE
ConsistentHash loadbalancing not working for gRPC

### ISSUE THREAD

**Issue by prestonvanloon** [istio/istio#14017]
**Bug description**

When setting the following traffic policy on a gRPC destination, requests are still round robin and evenly weighted.

```yaml
   trafficPolicy:
     loadBalancer:
       consistentHash:
         useSourceIp: true
```

The documentation here states the traffic policy only applies to "http" connections. I'm not sure if this is meant to exclude GRPC connections as well.
https://istio.io/docs/reference/config/networking/v1alpha3/destination-rule/#LoadBalancerSettings-ConsistentHashLB

**Expected behavior**

The requests are routed to a single backend consistently based on the hashed source IP.

See `istioctl proxy-config endpoints client-pod -o json --cluster "outbound|9090||destinationservicestring" `

With three backends, the endpoint configuration returned three hosts of equal weight.

Also through testing I have witness the requests be round robin routed instead of consistently routed. 

**Steps to reproduce the bug**

Create a virtual service with a `grpc-` port and destination with the above traffic policy.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

version.BuildInfo{Version:"1.1.5", GitRevision:"9b6d31b74d1c0cc9358cc82d395b53f71393326b", User:"root", Host:"3e29fde4-6c3f-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.4-10-g9b6d31b"}

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.8-gke.6", GitCommit:"394ee507d00f15a63cef577a14026096c310698e", GitTreeState:"clean", BuildDate:"2019-03-30T19:31:43Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**

https://istio.io/docs/setup/kubernetes/install/helm/#option-1-install-with-helm-via-helm-template

**Environment where bug was observed (cloud vendor, OS, etc)**

GKE

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[X] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by prestonvanloon** [comment]
I didn't have my virtual service properly configured so it wasn't going through envoy at all.

It does work when configured properly :)

**Comment by inewlife** [comment]
I also had the same problem,can you apply a config to me?thanks

**Comment by alexey-boyko** [comment]
> I didn't have my virtual service properly configured (it was missing for the destination route) so it wasn't going through envoy at all.
> 
> It does work when configured properly :)

@prestonvanloon could you please post example of your config, i can't make grpc loadbalancing work(
