### ISSUE TITLE
NeverInjectSelector is missing in Helm chart

### ISSUE THREAD

**Issue by cagataygurturk** [istio/istio#14020]
Hello,

The latest Helm chart does not allow specifying `NeverInjectSelector` in https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/files/injection-template.yaml

It would be quite nice to have this feature.

Thanks.

**Comment by morvencao** [comment]
@cagataygurturk Currently you need to edit the `istio-sidecar-injector` ConfigMap manually to add `neverInjectSelector ` or `alwaysInjectSelector `. 

Do you mean that it's better to set the fields through helm parameters during Istio installation?

**Comment by cagataygurturk** [comment]
@morvencao it's perfectly possible to edit ConfigMap and then restart the injector. However with every Istio upgrade, this ConfigMap will be overwritten. Users should be careful about setting again the values in ConfigMap manually.

Having this option in Helm chart lets users to add this configuration value to their own Helm values file they can use to reproduce Istio deployment with.
