### ISSUE TITLE
k8s svc vip integration (istio init/iptables and kube proxy (node proxy or other))

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1402]
@ldemailly commented on [Thu Jun 29 2017](https://github.com/istio/old_pilot_repo/issues/905)

Today istio bypasses and re implements the k8s svc vip->pod translation through the side car injection 

consider integrating at the svc vip -> pod k8s level (for kubernetes env)

was:
integrate kube-proxy and istio init

it seems odd to have 2 layers of iptables and 2 components attempting the same task of load balancing/directing traffic

I had that question during the community day and it also came up on the user list:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/istio-users/BgV0_wnL74Q/fC2tGeaYBwAJ

ps: this isn't a small change clearly and hasn't been prioritized yet either - we may decide to never do that but we should document why not

---

@kyessenov commented on [Thu Jun 29 2017](https://github.com/istio/old_pilot_repo/issues/905#issuecomment-312178850)

I assume this is with regards to per-node deployment?
What's the path forward with GKE root access?
cc @smawson @louiscryan 

---

@ldemailly commented on [Thu Jun 29 2017](https://github.com/istio/old_pilot_repo/issues/905#issuecomment-312179888)

It's the natural next step of auto inject (maybe already part of it?) ?

---

@ldemailly commented on [Fri Jun 30 2017](https://github.com/istio/old_pilot_repo/issues/905#issuecomment-312367380)

updated the description and mentioning we may never do that but we should document why not or in the meantime keep it open as one of the things we may want to do

**Comment by louiscryan** [comment]
@kyessenov I think this is stale. We have no immediate plans to do per-node etc. Please re-open if you disagree
