### ISSUE TITLE
Istio is breaking mysql client for queries returning more than 100 rows

### ISSUE THREAD

**Issue by bradenwright** [istio/istio#14028]
**Bug description**
I'm using mysql chart, along with a php app that has a pod and connect to mysql.  If I disable to istio proxy sidecar on php app then mysql query works as expected.  When the sidecar proxy is enable I can get a query with 80 rows to return, but 90 rows just hangs.  The DB shows that the query resolved and the connection is idle

```
kubectl exec -it my-php-app-7c87d9596d-r8nd8
MySQL [mydatabase]> select * from cfg limit 80;
------+---------------------+------------+---------------------+-------------+------------+------------+-----------+
80 rows in set (0.001 sec)

MySQL [mydatabase]> select * from cfg limit 100;
```

**Expected behavior**
I'd expect to be able to have queries with more than 90 rows return without an issue, not just cause the connection to hang.

**Steps to reproduce the bug**
Deploy MySQL chart (I disabled Istio Proxy / sidecar here), deploy MySQL Client (enable Istio Proxy / sidecar).  `kubectl exec -it <myql-client-pod> sh`, run mysql command to connect to db.  Then run a query that will return 100 rows or more.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.1.0

**How was Istio installed?**
helm 

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[X] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by bradenwright** [comment]
FYI, I currently have mutual TLS turned off

**Comment by howardjohn** [comment]
There is a known bug in the mysql filter in Envoy. We currently match protocols by the name of the port in the Service (in this case, mysql). This had the unintended side effect that users (like you, I suspect) unknowingly enable an alpha feature because of the port name.

This will be fixed in 1.1.7, https://github.com/istio/istio/pull/13999

As a workaround, you can change your port name to something that doesn't start with `mysql`

**Comment by bradenwright** [comment]
That worked great!  Thanks for the help.  Should I close this issue or leave it open until 1.1.7 is released?

**Comment by howardjohn** [comment]
We can close this now, 1.1.7 will be out very soon
