### ISSUE TITLE
1.1.6 helm repository missing istio-init chart

### ISSUE THREAD

**Issue by marshallford** [istio/istio#14025]
**Bug description**

```
Error: failed to download "istio.io/istio-init" (hint: running `helm repo update` may help)
```

`https://storage.googleapis.com/istio-release/releases/1.1.6/charts/istio-init-1.1.6.tgz` does not exist but is referenced in `index.yaml`.

**Expected behavior**

Google Cloud Storage uri should not 404. The `istio.io/istio-init` chart should be available for download.

**Steps to reproduce the bug**

1. `helm repo add istio.io https://storage.googleapis.com/istio-release/releases/1.1.6/charts/`
2. `helm repo update`
3. `helm upgrade --install istio-init istio.io/istio-init --force ...`

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

```
➜ kubectl version  
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.7-gke.10", GitCommit:"8d9b8641e72cf7c96efa61421e87f96387242ba1", GitTreeState:"clean", BuildDate:"2019-04-12T22:59:24Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

Helm

**Environment where bug was observed (cloud vendor, OS, etc)**

N/A

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

**Comment by harshal-shah** [comment]
I see this is a problem due to incorrect naming convention in istio-init v1.1.6

the name should have been `istio-init-1.1.6.tgz` instead of `istio-init.1.1.6.tgz`

![image](https://user-images.githubusercontent.com/16479600/57632473-088b2800-75a2-11e9-966e-faa3b5d50deb.png)

![image](https://user-images.githubusercontent.com/16479600/57632489-117bf980-75a2-11e9-93f6-8613ba3fbc37.png)

**Comment by utka** [comment]
Fixed.
