### ISSUE TITLE
podAntiAffinityTermLabelSelector broken due to #13905

### ISSUE THREAD

**Issue by ebensom** [istio/istio#14034]
**Bug description**
The commit for #13905 removed the weight attribute from the preferredDuringSchedulingIgnoredDuringExecution array elements, causing the following failure when trying to deploy:
Error: UPGRADE FAILED: Deployment.apps "istio-galley" is invalid: [spec.template.spec.affinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution[0].weight: Invalid value: 0: must be in the range 1-100, spec.template.spec.affinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution[1].weight: Invalid value: 0: must be in the range 1-100] && Deployment.apps "istio-ingressgateway" is invalid: [spec.template.spec.affinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution[0].weight: Invalid value: 0: must be in the range 1-100, spec.template.spec.affinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution[1].weight: Invalid value: 0: must be in the range 1-100] && Deployment.apps "istio-policy" is invalid: [spec.template.spec.affinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution[0].weight: Invalid value: 0: must be in the range 1-100, spec.template.spec.affinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution[1].weight: Invalid value: 0: must be in the range 1-100] && Deployment.apps "istio-telemetry" is invalid: [spec.template.spec.affinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution[0].weight: Invalid value: 0: must be in the range 1-100, spec.template.spec.affinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution[1].weight: Invalid value: 0: must be in the range 1-100] && Deployment.apps "istio-pilot" is invalid: [spec.template.spec.affinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution[0].weight: Invalid value: 0: must be in the range 1-100, spec.template.spec.affinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution[1].weight: Invalid value: 0: must be in the range 1-100] && Deployment.apps "istio-citadel" is invalid: [spec.template.spec.affinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution[0].weight: Invalid value: 0: must be in the range 1-100, spec.template.spec.affinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution[1].weight: Invalid value: 0: must be in the range 1-100] && Deployment.apps "istio-sidecar-injector" is invalid: [spec.template.spec.affinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution[0].weight: Invalid value: 0: must be in the range 1-100, spec.template.spec.affinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution[1].weight: Invalid value: 0: must be in the range 1-100]

Please note from the Kubernates API that a WeightedPodAffinityTerm array element must have a weight attribute with a value from 1-100:
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.12/#weightedpodaffinityterm-v1-core

**Expected behavior**
Deployment from helm chards using podAntiAffinityTermLabelSelector values completes successfully.

**Steps to reproduce the bug**
1. Define a podAntiAffinityTermLabelSelector config, e.g. 
gateways:
  istio-ingressgateway:
    podAntiAffinityTermLabelSelector:
      - key: app
        operator: In
        values: istio-ingressgateway
        topologyKey: "kubernetes.io/hostname"

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.1.6

**How was Istio installed?**
Using kubernetes helm charts

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by ebensom** [comment]
@morvencao Can you please look into this? You could simply add back the weight: 100 to the list elements or you could make it configurable and using a value of 100 by default if it is not provided by the user config.

**Comment by ebensom** [comment]
Also adding @linsun

**Comment by morvencao** [comment]
@ebensom Thanks for catching this, we didn't have upgrade test to cover this. 
Have talked about it with @linsun before, we reached a consensus that we hard code the `weight` rather that expose it.

**Comment by kramvan1** [comment]
https://github.com/istio/istio/commit/1fb691d4198243252ce5c7f50d72d7b40064b433#diff-a20dac6f4f0a506966d5e729c0d50f00L91    somehow I missed this in the review, but `weight: 100` was removed here, and it’s a required field.

**Comment by esnible** [comment]
Could we add to the tests a `helm template ...` followed by `istioctl validate -f ...` to ensure that all Istio CRDs are valid in the helm output?

**Comment by howardjohn** [comment]
@esnible it is invalid kubernetes config, but I think we can do the same with `kubernetes --dry-run` or something similar. Or is that what istioctl does as well? Either way I agree it is a good idea

**Comment by linsun** [comment]
+1 on adding some helm template dry run.  I think this issue is fixed now with #14418 but could use some tests to enforce the fix.

**Comment by morvencao** [comment]
Correct, it's a invalid kubernetes config and only will be triggered when affinity is explicitly enabled, looks like we need to add case for `helm template` + `kubernetes --dry-run` to cover this.

**Comment by aaron-trout** [comment]
For Galley specifically in the 1.2.2 helm chart, the `.tpl` file for the pod affinity stuff seems to be missing.

```bash
aaron@Aarons-MacBook-Pro ~/Downloads/istio-1.2.2/install/kubernetes/helm/istio/charts/galley/templates $ ls -l
total 72
-rw-r--r--@ 1 aaron  staff   994 27 Jun 18:03 _helpers.tpl
-rw-r--r--@ 1 aaron  staff  1209 27 Jun 18:03 clusterrole.yaml
-rw-r--r--@ 1 aaron  staff   531 27 Jun 18:03 clusterrolebinding.yaml
-rw-r--r--@ 1 aaron  staff   415 27 Jun 18:03 configmap.yaml
-rw-r--r--@ 1 aaron  staff  3864 27 Jun 18:03 deployment.yaml
-rw-r--r--@ 1 aaron  staff   660 27 Jun 18:03 poddisruptionbudget.yaml
-rw-r--r--@ 1 aaron  staff   471 27 Jun 18:03 service.yaml
-rw-r--r--@ 1 aaron  staff   429 27 Jun 18:03 serviceaccount.yaml
-rw-r--r--@ 1 aaron  staff  2647 27 Jun 18:03 validatingwebhookconfiguration.yaml.tpl
aaron@Aarons-MacBook-Pro ~/Downloads/istio-1.2.2/install/kubernetes/helm/istio/charts/galley/templates $ cat deployment.yaml| grep include
      {{- include "nodeaffinity" . | indent 6 }}
      {{- include "podAntiAffinity" . | indent 6 }}
```

For other components such as gateways there is an `_affinity.tpl` file.

```bash
aaron@Aarons-MacBook-Pro ~/Downloads/istio-1.2.2/install/kubernetes/helm/istio/charts/gateways/templates $ ls -l
total 104
-rw-r--r--@ 1 aaron  staff   3005 27 Jun 18:03 _affinity.tpl
...
```

**Comment by aaron-trout** [comment]
I think #13912 is related to this too; it could certainly be one work item to fix both these issues.

**Comment by morvencao** [comment]
@aaron-trout I think the original issue for this ticket has been fixed. If there is further discussion for pod anti-affinity, we can switch to https://github.com/istio/istio/issues/13912, do you agree?

**Comment by aaron-trout** [comment]
@morvencao sounds good to me. Although I still think Galley's pod affinity/anti affinity being broken is a separate issue (although will most likely get fixed at the same time as #13912.

https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/galley/templates/deployment.yaml#L116

As you can see above it tries to include templates named `nodeaffinity` and `podAntiAffinity` but those don't seem to be defined in the chart?

```
{{- include "nodeaffinity" . | indent 6 }}
{{- include "podAntiAffinity" . | indent 6 }}
```

**Comment by morvencao** [comment]
@aaron-trout The two template are defined in `parent` chart template, not in single subchart, because they are totally reusable, see : https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/templates/_affinity.tpl

**Comment by aaron-trout** [comment]
> @aaron-trout The two templates are defined in `parent` chart template, not in single subchart, because they are totally reusable, see : https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/templates/_affinity.tpl

@morvencao ah! In which case that needs removing from most of the other components helm charts I guess? 😄 

For example: https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/gateways/templates/_affinity.tpl

**Comment by morvencao** [comment]
@aaron-trout The affinity templates in gateways subchart is a little different from others, that's why we place that affinity templates for gateways only.

**Comment by morvencao** [comment]
Closing this as the original issue has been fixed, feel free to reopen it if needed.
