### ISSUE TITLE
SDS support for Client Certificate and CA cert used for TLS/mTLS Origination from Egress Gateway

### ISSUE THREAD

**Issue by skydoctor** [istio/istio#14039]
**Describe the feature request**
Currently we have an option to include a node-agent container in the ingress-gateway pods to enable SDS as the communication channel to manage the external-facing certificates. We should have a similar mechanism for egress gateway.

**Describe alternatives you've considered**
Without a node-agent, loading new certificates requires a process restart.

**Additional context**
Ingress and Egress gateways are symmetrical concepts to provide edge-traffic management capabilities via Istio. The use-cases for adding egress gateway to a service mesh are listed at https://istio.io/docs/examples/advanced-gateways/egress-gateway/. We can maintain symmetry and enable SDS at the egress gateway by including a node-agent.

**Comment by skydoctor** [comment]
@JimmyCYJ @myidpt @costinm: Would this make sense? Any complexities apart from adding the required sections in the helm chart for gateways?

**Comment by incfly** [comment]
Can you elaborate what identity you want to use for what connection?

Are you using your own certificate with DNS SAN or you're using Citadel issued certificate? Is the connection between workload in the mesh and egress gateway or gateway and public internet?

@Monkeyanator is working on something related, https://github.com/istio/istio/issues/15485, FYI.

**Comment by nitishm** [comment]
> Can you elaborate what identity you want to use for what connection?
> 
I am not sure what you mean by identity. So i probably dont have a good answer for that, sorry :/

> Are you using your own certificate with DNS SAN or you're using Citadel issued certificate? 
We will  be using our own certificate for this.

> Is the connection between workload in the mesh and egress gateway or gateway and public internet?
Neither of the two. This will be from Gateway to Gateway. We will be using mTLS between an Egress Gateway in namespace A talking to the Ingress Gateway in namespace B.

Something like 
`{//NS-A ... [worload->sidecar]->[egress GW] //end NS-A}->{ //NS-B [ingress GW]->[sidecar->workload] ... //end NS-B}`

**Comment by incfly** [comment]
@nitishm Okay, I see. So you want the connection between egress gateway to ingress gateway in mutual TLS. So given both them are Istio workloads, it's okay and possible to use Citadel issued workload certificates with "SPIFFE" SAN? Or you're looking for having control what certificates to use in egress as well?

**Comment by nitishm** [comment]
We most definitely need to control the certificates. We will use citadel for inter-workload comms but namespace to namespace will need our own certificates (client and server)

**Comment by JimmyCYJ** [comment]
I think what @nitishm asked for is to create k8s secret which has (1) CA cert of ingress GW B when B is TLS gateway, or (2) CA cert of ingress GW B and client key/cert when B is mTLS gateway. So that egress gateway agent could watch this k8s secret, extract key/cert/ca cert and push to egress GW A.

**Comment by nitishm** [comment]
I should add that we want the management to be symmetric to the ingress gateway. Using the sds agent like the ingress gateway, for the egress gateway.

**Comment by nitishm** [comment]
> I think what @nitishm asked for is to create k8s secret which has (1) CA cert of ingress GW B when B is TLS gateway, or (2) CA cert of ingress GW B and client key/cert when B is mTLS gateway. So that egress gateway agent could watch this k8s secret, extract key/cert/ca cert and push to egress GW A.

Yea that seems to capture the requirements pretty well. Thanks @JimmyCYJ

**Comment by JimmyCYJ** [comment]
I am working on PKI reliability. Once the ingress SDS is stable and we have better monitoring and test coverage. I will enable SDS on egress gateway. Please let us know if you have any concerns. @myidpt

**Comment by nitishm** [comment]
> @nitishm Okay, I see. So you want the connection between egress gateway to ingress gateway in mutual TLS. For the first question, let me ask in another way, given both them are Istio workloads, it's okay and possible to use Citadel issued workload certificates with "SPIFFE" SAN? Or you're looking for having control what certificates to use in egress as well?

I also should've added that we provision and manage our certificates using cert-manager. 
As for now SDS is the right choice by watching the secret generated by cert-manager, but if there are any proposals to support cert-manager directly through the agen, rather than a `secretFetcher` that would be ideal.

Let me know what you think about this enhancement @JimmyCYJ @incfly

**Comment by JimmyCYJ** [comment]
We do have a plan to let gateway agent fetch secret directly from cert-manager or let's encrypt. https://github.com/istio/istio/issues/12132. 
But we need to make the SDS feature reliable before we move forward.
The short term solution would be using cert-manager with gateway agent to provision key/cert via SDS.

**Comment by nitishm** [comment]
> The short term solution would be using cert-manager with gateway agent to provision key/cert via SDS.

Just to add more information, for everybody else reading though this issue, the Secret generated by Cert Manager is only good for `mode: SIMPLE` and will not work for `mode: MUTUAL` TLS since the secretFetcher in SDS agent is not capable of reading ca-certificates from the type/tls Secret type.

It is however possible to read the ca certificates from a separate Secret (manually/programatically generated) that contains only the certificate based on the changes merged by @JimmyCYJ in this PR https://github.com/istio/istio/pull/15496

**Comment by chadlwilson** [comment]
Yes, there is still a requirement for this; as well as (arguably) to support SDS for sidecar egress, e.g for direct TLS and mTLS origination to external services from sidecars. Currently you have to use the `sidecar.istio.io/userVolumeMount` annotation approach.

**Comment by incfly** [comment]
> for direct TLS and mTLS origination to external services from sidecar

I think our DestinationRule API already covers that with full TLS configuration knobs. Along with the annotations you mentioned, they should be able to achieve what you want.

Reopening for the sake of SDS... I doubt the full built-in or extensible SDS support for bring your own identity can be satified in the near feature, but open this as I believe it's a legit feature request.

**Comment by chadlwilson** [comment]
Hi @incfly - thanks for the reply! Are you able to point us to where the documentation/example is to say how to get a sidecar to mount TLS/mTLS secrets via SDS rather than direct `userVolumeMount`s and how to configure the `DestinationRule` as such? We looked for it, but could only find examples which rely on volume mounts. :'(

**Comment by incfly** [comment]
Sorry maybe I confused you. By that, I don't mean the SDS works. We don't offer a mechansim to extend SDS for certificate for the workloads. I'm just saying that the DestinationRule can be used to configure client TLS after the cert/key are mounted.

**Comment by chadlwilson** [comment]
@incfly OK thanks for the clarification. In a general sense it'd be great to have SDS support everywhere, based on the magic secret discovery used for ingress.

It's rather messy at the moment having to use a mixture of SDS and volume mount support across the mesh for various purposes (ingress gateway - SDS, inter-workload - SDS, egress gateway - mounts, workload egress - mounts); and automating the config generation for mounting secrets and server certs into workloads and gateways is a bit painful for use cases where you might be calling multiple external services (/clusters) outside the mesh.

**Comment by nitishm** [comment]
Can this be prioritized in any way? Egress Gateway should be symmtric to the Ingress Gateway. Would love to see this added to the roadmap for a future release.

**Comment by balamuru** [comment]
What's the roadmap for SDS vs volume mount support in later releases of Istio 1.4.x and Istio 1.5 and beyond ?

I'd like to adopt SDS but encounter issues like  not being able to install egress-gateway if using SDS on the ingress-gateway.

**Comment by kunalekawde** [comment]
Assuming we still don't have this, what are the ways we can achieve configuring multiple certs, key dynamically possibly w/o restarting envoy. As I understand current we would have to:
1. Use the cert, key provided to generate secret. 
2. Mount this at egress gw.
3. To handle any dynamic addition of #1 or revocation, generate new secrets and restart envoy.
@chadlwilson

**Comment by mandarjog** [comment]
@JimmyCYJ @myidpt can we have this feature for 1.7 still?

**Comment by myidpt** [comment]
Yes we do. We have an intern to work on this.

**Comment by JimmyCYJ** [comment]
@nschhina is working on this, but I cannot find his id in the assignee list.

**Comment by nschhina** [comment]
Do I need to be a part of Istio organization first? If so I'll request membership now

**Comment by JimmyCYJ** [comment]
> Do I need to be a part of Istio organization first? If so I'll request membership now

After you left the comment, your ID shows up in the assignee list now :)

**Comment by nschhina** [comment]
[Design Doc](https://docs.google.com/document/d/1--c7Y4MR5CL-q6Fl5UlYLzluQpAlRcdyJ1gOUB98Njg/edit#heading=h.7zgnj8bwqfld) for this feature is now in review. Please take a look if interested, feature is scheduled to be out in Istio 1.7

**Comment by incfly** [comment]
I change the title. Since this is already causing some confusion when we think about egress gateway as server, receiving traffic from sdiecar within the mesh.

That SDS && ISTIO_MUTUAL is already supported.

**Comment by nschhina** [comment]
@incfly thanks for point that out- I think the title I changed to is more explicit for this issue. Feel free to change it back if you think the older title described the issue better
