### ISSUE TITLE
Observed some 503 UC's not being retried

### ISSUE THREAD

**Issue by Stono** [istio/istio#14037]
Whilst testing https://github.com/istio/istio/issues/13848, we have observed some 503 UC errors that are not getting retried, when they should be.  

This trace should go `nginx | envoy` -> `envoy | singleview-package-viewer`, however it stops at nginx's envoy, with an `UC` flag, with no retry.

<img width="1680" alt="Screenshot 2019-05-13 at 13 48 59" src="https://user-images.githubusercontent.com/1486729/57622636-f1d6d800-7585-11e9-8dda-7f9de87cafc3.png">

[here is the trace json](https://github.com/istio/istio/files/3172909/trace.log)

You can see the cluster is in the config:
```
❯ istioctl proxy-config endpoints ingress-nginx-internal-controller-6664895fcb-bfv9t.ingress-nginx | grep single
10.194.16.131:8088      HEALTHY     outbound|80||app.singleview-package-viewer.svc.cluster.local
10.194.16.131:9080      HEALTHY     outbound|9080||admin.singleview-package-viewer.svc.cluster.local
10.194.5.96:8088        HEALTHY     outbound|80||app.singleview-package-viewer.svc.cluster.local
10.194.5.96:9080        HEALTHY     outbound|9080||admin.singleview-package-viewer.svc.cluster.local
```

I did notice this happened at 9am, and 11am, and in both examples I **one** of the **two** instances of the app failed their liveness probe, but the other was fine.

The failure was pretty obscure:
```
Liveness probe failed: rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused "process_linux.go:87: adding pid 379135 to cgroups caused \"failed to write 379135 to cgroup.procs: write /sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/pod7dc88c9a-700d-11e9-95fd-42010aa40061/11d5c36b2ae84a312eb4abf95456816aa8a856b5d6f44d67a1c680cd27e9554c/cgroup.procs: invalid argument\""
```

It looks like a known bug on GKE: https://discuss.kubernetes.io/t/readiness-and-liveness-probes-fail-randomly-on-gke/3898.

FYI: It **did not** restart the pod, as the liveness probe passed on the next attempt, and it was at no point considered unready:

<img width="1631" alt="Screenshot 2019-05-13 at 14 00 25" src="https://user-images.githubusercontent.com/1486729/57623347-7a09ad00-7587-11e9-97d6-adf516473133.png">

So at the most basic level, I'm unsure why a flakey liveness probe would cause what we're observing here.

**Comment by Stono** [comment]
https://github.com/envoyproxy/envoy/issues/1979#issuecomment-355343645

**Comment by Stono** [comment]
I'm going to close this.  There are so many moving parts when it comes to 503 retries at the moment and I've very rarely seen this.

I'll reopen it shout the issues persist post 1.2 I think.

**Comment by dkushner** [comment]
@Stono We are now experiencing this in 1.2.2 and are quite tired of trying to tweeze our way through Pilot's source to figure out what the source of these errors are. Are you having any more luck?

**Comment by Stono** [comment]
Hey @dkushner, istio usage of 503s is currently very broad :( it's a pain.

My advice would be to debug exactly what is the root cause of the 503 then open an issue specific to that scenario.

I wrote up a bit of a blog post about how I debugged some recently. It might help you 

https://karlstoney.com/2019/05/31/istio-503s-ucs-and-tcp-fun-times/

**Comment by dkushner** [comment]
@Stono Much appreciated, will take a look at what you've found. We've traced 503s back to everything from health checks being misconfigured (mTLS installation interfering with native k8s health checks, pretty easy to diagnose) to Pilot quietly soft-locking while waiting for rescheduling after hitting resource limits. And then sometimes, it just doesn't work and we haven't the slightest indication from any of the logs what might be causing it, which is a blast. Glad to know we're not the only ones.

**Comment by Stono** [comment]
Yeah we have one that we can't track down at the moment either, I feel your pain.  

Another one we found was pilot-agent sidecar shutting down before the application was done.  At the moment it drains (fine) but then if your app makes an outbound connection after that drain it'll fail.  We actually have a wrapper around pilot-agent now which blocks the sigint getting to pilot agent until the main application has exit.

 https://github.com/istio/istio/issues/12183

Good luck!

**Comment by amir-hadi** [comment]
@Stono Do you think we should re-open this? Because I am getting the same results as you, but in istio 1.4.4. Not 100% if its the exact same problem though, but setting `maxRequestsPerConnection: 1` seems to fix the issue. AFAIK this effectively disables pooling between envoy and app, so it could be related.

**Comment by Stono** [comment]
Hey @amir-hadi - I don't see this issue any more and narrowed down those 503UC errors to general issues with keep alive timeouts (as per my blog).

I'm not sure what we'd get from reopening the issue.

If you've got some specific debug information though perhaps it's worth opening a new issue, you can always reference this one back if you feel it's related?
