### ISSUE TITLE
unknown field "trigger_rules" in v1alpha1.Jwt

### ISSUE THREAD

**Issue by vishdv** [istio/istio#14031]
**Bug description**

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by esnible** [comment]
Which version of Istio are you using?  Where is this error appearing?

The api/authentication/v1alpha1/policy.proto field trigger_rules is at least 9 months old.

**Comment by yangminzhu** [comment]
Could you provide some additional information about this?

**Comment by vishdv** [comment]
Hi All, Thanks for the info, i understood the issue. Its regarding with the istio version . We are sorted out

**Comment by yangminzhu** [comment]
Thanks @vishdv for the update, Closing the issue now.
