### ISSUE TITLE
Tracing: sampling and configuration

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1403]
@kyessenov commented on [Mon May 22 2017](https://github.com/istio/old_pilot_repo/issues/808)

It seems that we might be over-sampling the tracing data, especially the health probes.
We should expose the configuration to sample and filter certain traces.

---

@kyessenov commented on [Mon May 22 2017](https://github.com/istio/old_pilot_repo/issues/808#issuecomment-303252162)

ref https://github.com/lyft/envoy/issues/960

---

@ijsnellf commented on [Fri Jun 16 2017](https://github.com/istio/old_pilot_repo/issues/808#issuecomment-309033924)

Currently, we are tracing everything. Envoy has configuration to set the amount of random tracing, but it isn't exposed conveniently right now: https://lyft.github.io/envoy/docs/configuration/http_conn_man/runtime.html#config-http-conn-man-runtime-random-sampling

---

@rshriram commented on [Fri Jun 16 2017](https://github.com/istio/old_pilot_repo/issues/808#issuecomment-309042096)

@ijsnellf Can you file this an issue in Envoy repo and reference this?
-- 

~shriram

---

@bobbytables commented on [Tue Oct 03 2017](https://github.com/istio/old_pilot_repo/issues/808#issuecomment-333836928)

Has anyone come up with a convenient way to disable health check traces at least? I'm worried that we're just bloating our database instance for no reason.

**Comment by mandarjog** [comment]
Related to https://github.com/istio/istio/issues/1206
