### ISSUE TITLE
Switch the istio/operator repo to use Go modules

### ISSUE THREAD

**Issue by geeknoid** [istio/istio#14045]
We're switching all repos to use Go modules instead of dep for dependency tracking. I tried to get the operator repo building with modules, but got stuck in some dependency tracking problem. But this needs to happen.

To try:

  export GO111MODULE=on
  go build ./...

Iterate until go build ./... works. Then you can delete Gopkg* and vendor and you'll be on the module plan.

**Comment by kramerul** [comment]
I fixed this issue in https://github.com/kramerul/operator/tree/gomod. 

But I was not able to create a pull request. I got an 405 HTTP status code.

**Comment by kramerul** [comment]
I did the following:

- Start with an empty require section in go.mod
- Run `go build ./...`
- Add `replace k8s.io/client-go => k8s.io/client-go v10.0.0+incompatible` to go.mod
- Checkout client-go in release-10.0
- Run `go mod init k8s.io/client-go`
- Copy k8s stuff from `client-go/go.mod` to `go.mod` replace section
- Run `go build ./...`
- Remove `promentheus-operator` stuff from go/mod
- Run `go build ./...`


At the end, I ran `go mod vendor` to replace the vendor folder.

**Comment by kramerul** [comment]
Closing this because it's a duplicate of #15240
