### ISSUE TITLE
Pod crashlooping can cause excessive full pushes from Pilot

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#14042]
When a service drops down to 0 endpoints, we remove all references to it. This was added in https://github.com/istio/istio/pull/11183 to prevent memory leaks. When a new service is created, a full push is triggered to every envoy.

These two together allow a pod that is crashlooping (going from 0 to 1 endpoints repeatedly) to trigger constant full pushes. In one case I saw roughly 20x pilot CPU usages from full pushes being triggered every 5s or so. 

This is especially bad because a single pod crashing can cause a mesh-wide failure.

We should also be aware of the memory leak fixed in 11183 and make sure we do not repeat this

**Comment by nishanth-pinnapareddy** [comment]
@nishanth-pinnapareddy /cc

**Comment by howardjohn** [comment]
@hzxuzhonghu fyi

**Comment by hzxuzhonghu** [comment]
I think we can fix it by  delete the associated key of  `EndpointShardsByService` only when svc deleted.

**Comment by hzxuzhonghu** [comment]
Or another option: 

Seems it is viable to remove the below logic to trigger full push. I am not sure why it is needed.
```
	// Update the data structures for the service.
	// 1. Find the 'per service' data
	ep, f := s.EndpointShardsByService[serviceName]
	if !f {
		// This endpoint is for a service that was not previously loaded.
		// Return an error to force a full sync, which will also cause the
		// EndpointsShardsByService to be initialized with all services.
		ep = &EndpointShards{
			Shards:          map[string][]*model.IstioEndpoint{},
			ServiceAccounts: map[string]bool{},
		}
		s.EndpointShardsByService[serviceName] = ep
		if !internal {
			adsLog.Infof("Full push, new service %s", serviceName)
			requireFull = true
		}
	}
```

**Comment by hzxuzhonghu** [comment]
@costinm You first added it, any comments?

**Comment by howardjohn** [comment]
Closing as duplicate of https://github.com/istio/istio/issues/13822
