### ISSUE TITLE
Enable race-test detection for integration & end-to-end tests.

### ISSUE THREAD

**Issue by ozevren** [istio/istio#14049]
We'd like to enable race-test detection for our larger test suites, where the code in question runs in pods in K8s. This entails:

- Creating appropriately instrumented binaries
- Creating deployment/setup using these binaries
- Ensuring that we can reliably detect race-test issues in code running in a pod. Specifically, if there is a crash due to the race-test detection induced failure, we'd like to reliably detect and fail the tests as needed.

**Comment by howardjohn** [comment]
This was completed
