### ISSUE TITLE
move code generation scripts to istio/pkg from istio/istio

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#14054]
istio/pkg references istio/istio scripts from go generate directives.
Since we can no longer assume istio is in GOPATH, the scripts need to be updated.

/cc @geeknoid

**Comment by kyessenov** [comment]
Also the existing scripts in istio/pkg (fmt.sh) does not appear to be functional.

**Comment by howardjohn** [comment]
Fixed by https://github.com/istio/pkg/pull/9
