### ISSUE TITLE
Implement Feature/Test tracking infrastructure

### ISSUE THREAD

**Issue by ozevren** [istio/istio#14051]
We'd like to implement some infrastructure for tracking/correlating Istio Features and corresponding tests. The following document captures the details:
https://docs.google.com/document/d/1Q5lkzc_xz31pbh2MGu0JNzH0WWM5d7LRBgkhn2cj3H0

**Comment by ozevren** [comment]
@therealmitchconnors I believe you're currently working on this. If not, please feel free to unassign.

**Comment by therealmitchconnors** [comment]
I have been, but I'm 100% on the 1.2 release for another three weeks...
