### ISSUE TITLE
CNI plugin chart in releases newer than 1.1.2

### ISSUE THREAD

**Issue by PigNatovsky** [istio/istio#14069]
First of all, I know how to fix this "bug"- I can use CNI plugin package from previous releases. But to get this information, I had to read docs from CNI plugin repo, check releases etc. Typical user should follow docs and hapilly install ISTIO release.
**Bug description**
Installing ISTIO with CNI isn't possible in the way described in documentation ([Here_is_source](https://istio.io/docs/setup/kubernetes/additional-setup/cni/)), because istio-cni chart is not in the right place.
**Expected behavior**
After downloading realese archive, I can install ISTIO with CNI plugin following official documentation. 
**Steps to reproduce the bug**
Just download any release newer than 1.1.2, unpack and check for any istio-cni chart available. 
**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Information not important in this case.
**How was Istio installed?**
Helm without tiller
**Environment where bug was observed (cloud vendor, OS, etc)**
Any environment in which I can download release :)
**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[X ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

**Comment by howardjohn** [comment]
@tiswanso @utka

**Comment by tiswanso** [comment]
Will be fixed by #13615

**Comment by PigNatovsky** [comment]
Thanks guys, now everything is clear :)
