### ISSUE TITLE
Connection: Keep-Alive headers stripped from response

### ISSUE THREAD

**Issue by Stono** [istio/istio#14075]
Hi, 
I'm raising this as a separate issue to https://github.com/istio/istio/issues/13848, but it could all be related.

Take the following setup:

`[consumer-gateway | envoy]` -> `[envoy | sauron-seo-app]`

If I curl the `sauron-seo-app` on localhost (cutting out envoy) I correctly get back the `Connection: keep-alive` headers indicating to the client that the connection can be kept alive, as you'd expect:

```
[atcloud@sauron-seo-app-6f449d5795-x9g82 app]$ curl -s -v -o /dev/null http://127.0.0.1:8080/cars/bmw
* About to connect() to 127.0.0.1 port 8080 (#0)
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> GET /cars/bmw HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 127.0.0.1:8080
> Accept: */*
>
< HTTP/1.1 200 OK
< X-Powered-By: Express
< Cache-Control: max-age=300
< Content-Type: text/html; charset=utf-8
< Content-Length: 319401
< ETag: W/"4dfa9-p62Vws25oYvDohb0eYlcYQDeduk"
< Vary: Accept-Encoding
< Date: Tue, 14 May 2019 14:24:46 GMT
< Connection: keep-alive
<
{ [data not shown]
``` 

However, making the same request from the `consumer-gateway` pod, results in no keep alive:
```
[atcloud@consumer-gateway-6c778d487c-tms9b app]$ curl -s -v -o /dev/null http://app.sauron-seo-app/cars/bmw
* About to connect() to app.sauron-seo-app port 80 (#0)
*   Trying 10.192.1.163...
* Connected to app.sauron-seo-app (10.192.1.163) port 80 (#0)
> GET /cars/bmw HTTP/1.1
> User-Agent: curl/7.29.0
> Host: app.sauron-seo-app
> Accept: */*
>
< HTTP/1.1 200 OK
< x-powered-by: Express
< cache-control: max-age=300
< content-type: text/html; charset=utf-8
< content-length: 319401
< etag: W/"4dfa9-p62Vws25oYvDohb0eYlcYQDeduk"
< vary: Accept-Encoding
< date: Tue, 14 May 2019 14:25:35 GMT
< x-envoy-upstream-service-time: 9
< server: envoy
<
{ [data not shown]
```

Our destinationrule is configured as so:
```
  spec:
    host: app
    trafficPolicy:
      connectionPool:
        http:
          http1MaxPendingRequests: 1024
          http2MaxRequests: 10240
          idleTimeout: 5m
          maxRequestsPerConnection: 1024
```

So when envoy is in play, keep alive header is being removed. 

The http1.1 spec says that the default behaviour should be to keep alive (http1.0 was to close), but I'm unsure of the impact that this header omission is having on the calling clients, and if they all correctly implement the spec or not.  It feels like it probably shouldn't be being removed.

**Comment by howardjohn** [comment]
@silentdai @PiotrSikora can you take a look? Is this expected?

**Comment by Stono** [comment]
I tried adding out of curiosity the following to my destination virtualservice: 
```
  http:
  - headers:
      response:
        set:
          connection: keep-alive
          karl: testing
```

I saw the `karl` header, but not the `connection`:

```
[atcloud@consumer-gateway-6c778d487c-tms9b app]$ curl -s -o /dev/null -v http://app.sauron-seo-app/cars/bmw
* About to connect() to app.sauron-seo-app port 80 (#0)
*   Trying 10.192.1.163...
* Connected to app.sauron-seo-app (10.192.1.163) port 80 (#0)
> GET /cars/bmw HTTP/1.1
> User-Agent: curl/7.29.0
> Host: app.sauron-seo-app
> Accept: */*
>
< HTTP/1.1 200 OK
< x-powered-by: Express
< cache-control: max-age=300
< content-type: text/html; charset=utf-8
< content-length: 315608
< etag: W/"4d0d8-dKJ0y1OrqhdCWxLn25GiWzLCIXo"
< vary: Accept-Encoding
< date: Tue, 14 May 2019 17:24:05 GMT
< x-envoy-upstream-service-time: 10
< server: envoy
< karl: testing
<
{ [data not shown]
```

**Comment by Stono** [comment]
Potentially related https://github.com/istio/istio/pull/12227 
cc. @rshriram

**Comment by silentdai** [comment]
IIRC http1.1 is implicitly turning on keep-alive. It might be unrelated.

**Comment by Stono** [comment]
@silentdai that's what the http1.1 spec says, yes, but are you confident the clients in nodejs, python, java, etc etc etc are all doing keepalive in the absence of that header?

It's being explicitly removed somewhere and I'd like to understand if that was a conscious decision 🤷‍♂

**Comment by Stono** [comment]
https://github.com/envoyproxy/envoy/issues/3011 related

**Comment by kramerul** [comment]
If there is an envoy running in front of your application, the client side connection handling is done by envoy and no longer by your application. Therefore, it's up to envoy to choose the right connection policy. As part of this job, envoy might decide to remove this header.

There is a [unit-test in envoy](https://github.com/envoyproxy/envoy/blob/6dd4b6f83119e6b284f95ed9c74e4dfcbb4efc8c/test/common/http/conn_manager_utility_test.cc#L1092), which is exactly testing the removal of this header.

**Comment by Stono** [comment]
@kramerul that test is assering that the `keep-alive` header is not present, which is the configuration for the keepalive connection, it isn't asserting that `connection: keep-alive` has been removed.

**Comment by kramerul** [comment]
That's correct.

**Comment by Stono** [comment]
So my original query was about the removal of the connection header?

**Comment by kramerul** [comment]
Envoy is [removing the `connection` header](https://github.com/envoyproxy/envoy/blob/cbd8d57e9fc2921d26236db24b6bf91246ba3b4f/source/common/http/conn_manager_utility.cc#L71) , because it needs to do the connection management by itself.
As Yuchen Dai said, this conforms to the HTTP 1.1 spec. Clients should handle this correctly.

**Comment by Stono** [comment]
> As Yuchen Dai said
As did I, in my original post - which you would know if you read it in its entirety.  I'm well aware of the http1.1 spec.  

> Clients should handle this correctly.
My statement was I don't have confidence in the vast array of client implementations for many legacy applications to **implicitly** implement the http1.1 behaviour rather than explicitly implementing it in response to a header which we previously **explicitly** added by us.

For context; we have 350+ applications of many ages, being migrated to the service mesh that work _just fine_ currently.  With envoy in play, we're experiencing [various connection issues](https://github.com/istio/istio/issues/13848) seemingly related to timeouts, keep alives etc.  This thread was a spin off for one finding.  It's very easy for you to say those 350 clients should "handle it correctly", you're not the one trying to understand why some of them are experiencing keep alive issues when using envoy.

The simple solution for us clearly, is to not use istio/envoy.

**Comment by emedina** [comment]
@Stono I completely emphasize with you and I already showed my frustration throughout the different issues I've opened.

I still cannot understand how this is considered as production-ready, even with whatever the workarounds are to retry or ignore `503` errors, taking for granted that they will not run into idempotence issues.

Not sure what else we can try out on our side, but as you mention, maybe it's time to think about alternatives, such as linkerd, ambassador, solo.io, to name a few.

**Comment by kramerul** [comment]
I'm not part of the istio team. I just tired to figure out, why the connection header is removed in envoy.

In my point of view, envoy handles this in the right way. 

I can also understand your disappointment, that you need to test and rewrite all your clients. 

One solution could be to use [Lua to add this header](https://www.envoyproxy.io/docs/envoy/latest/configuration/http_filters/lua_filter) in envoy. But I have no experience in that topic.

**Comment by PiotrSikora** [comment]
`Connection` header is hop-by-hop, so it's value shouldn't be forwarded by a proxy.

`Connection: keep-alive` is leftover from `HTTP/1.0` days, and it's a no-op in `HTTP/1.1` and `HTTP/2`, where connections are persistent by default.

Furthermore, setting `Connection` header's value manually, without control over connection's lifetime, is going to result in more issues that it's worth it.

In any case, I doubt that lack of `Connection: keep-alive` is leading to any errors.

**Comment by Stono** [comment]
Thanks @PiotrSikora - it isn't no-op in 1.1, it's omitted `keep-alive`, or present with `close`.  But either way, if you don't think it's related to the other UC/503 errors then that's fine - we're simply just exploring all differences between mesh and none mesh and are running out of avenues of exploration.

as @emedina said; it's really frustrating for us as we don't know what else we can do to help debug the problems and it doesn't feel like there is much traction on the istio side.
