### ISSUE TITLE
Test Framework structpath cannot handle fallthrough route

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#14084]
Example failure: It says that the route cannot be found, but it appears to be there. ctrl+f `outbound|7070||a.failover-eds-1-62618.svc.cluster.local` on https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/14041/integ-pilot-k8s-presubmit-tests-master/252/build-log.txt.

I am pretty confident it is a bug with the structpath stuff. in OutboundConfigAcceptFunc I added some debugging code that does the same as the srtuctpath but working directly with the proto and it finds the config, but the struct path does not.

I think I know what is happening (though I am not sure why). The route stuff has a weird API that requires casting (see https://github.com/istio/istio/blob/84370fffc1ce1fda6345e24868c955bb4bfcb5cb/pkg/test/envoy/admin_util.go#L149-L162). The new changes being merged introduce an additional route and maybe it gets confused by the proto API there? Because turning off the additional route fixes the tests

cc @nmittler

**Comment by nmittler** [comment]
@howardjohn The envoy config doesn't seem to have changed ... it's simply a change to the parsing. I suspect that #13324 is the culprit. It updated the json path library.

**Comment by howardjohn** [comment]
@nmittler this is the change that introduced the failures:

https://github.com/istio/istio/blob/13cb3422ae47f95dfbc829a327724a56929cab3b/pilot/pkg/networking/core/v1alpha3/httproute.go#L223-L227

(rather, turning it on by default)

Turning the feature flag back off fixes it, and it is still failing in post submit in the tests that directly exercise this feature (so the flag is on), so I think that is the culprit. It has the weird `isRoute_Action` type that maybe cannot be handled properly?

**Comment by nmittler** [comment]
ok interesting ... let me play with it and see if I can find something that works.

**Comment by pitlv2109** [comment]
I assume this has been fixed? Several tests set `pilot.env.PILOT_ENABLE_FALLTHROUGH_ROUTE = 0`.
https://github.com/istio/istio/blob/460b55f1d9c5ffce01e4239f0f846e85575a6b41/tests/integration/security/rbac/v2/basic/main_test.go#L68

**Comment by howardjohn** [comment]
Haven't got a chance to try it out yet without those, but I *think* it would work now
