### ISSUE TITLE
Bookinfo needs updating to 1.14

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#14088]
In https://github.com/istio/istio/pull/13316 we introduced changes to bookinfo, alongside changes to master at the same time. This #13316 needs to be merged into master and appropriate images updated.

This was NOT done by the standard release-1.1 merges because it is way to complicated to handle in a merge commit with 33 other commits, so deferring to the person who knows what to do here @vadimeisenbergibm

**Comment by howardjohn** [comment]
@vadimeisenbergibm can you pick this up? It isn't clear to me exactly what needs to be done and what the impact of not getting this updated is

**Comment by howardjohn** [comment]
@vadimeisenbergibm is this still needed? Your change in release 1.1 will NOT be in 1.2 if nothing is done

**Comment by howardjohn** [comment]
@vadimeisenbergibm is this still needed? We want to be very careful we do not miss changes to 1.1 in 1.2 like we did for 1.0 -> 1.1

**Comment by vadimeisenbergibm** [comment]
@howardjohn Hi, sorry, missed that, was on vacations/business trip. Let me handle it this week.

**Comment by howardjohn** [comment]
No worries, thanks for looking into it

**Comment by howardjohn** [comment]
Fixed by #15261
