### ISSUE TITLE
integ-framework-k8s-presubmit-tests-master are flaky

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#14083]
The test seems to use a node port which causes conflicts during presubmit due to birthday paradox.
The test should not be using a limited shared resource.
Example: https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/14057/integ-framework-k8s-presubmit-tests-master/258

**Comment by ozevren** [comment]
This is the deployment yaml files, not the test itself. The framework is using the same deployment model in the Makefile.

**Comment by douglas-reid** [comment]
I'm seeing a flake in this test, but for other reasons:

> Process did not exit before 15s grace period

From: https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/14671/integ-security-k8s-presubmit-tests-master/1440

That's kinda frustrating for a test that actually "PASS"'d.

**Comment by ozevren** [comment]
@douglas-reid it looks like, in that case the test maybe simply timing out due to the time spent on creating the images. Eyeballing some of the numbers, it takes quite a bit of time to download some of the images.

**Comment by nmittler** [comment]
@ozevren yeah looks like a timeout.

@duderino this issue doesn't appear to have anything to do with the test framework at all ... would you mind finding a victim that has some spare cycles?

**Comment by ozevren** [comment]
Neither of those issues are flakes with the test suit itself. I am inclined to close this bug. I believe there is a bug that is already open tracking the first problem (node port conflict). If there isn't a bug for the second case, we should open one. But neither is a flake with the test itself.

**Comment by sushicw** [comment]
First issue (nodeport conflict) is tracked here: https://github.com/istio/istio/issues/14190

Second issue (process did not exit fast enough) doesn't currently have an issue tracking it, so I created one: https://github.com/istio/istio/issues/15095

Closing this issue as recommended by @ozevren
