### ISSUE TITLE
mergify force squashes PRs

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#14091]
I think we need a mechanism to prevent auto-squashing (e.g. https://github.com/istio/pkg/pull/11 is not a good practice).
This will become critical once we start moving commits between branches.

/cc @geeknoid

**Comment by geeknoid** [comment]
It's been our general policy to squash checkins and our repos are all configured for that. We explicitly turn squash off when doing changes that require merging while preserving histories.

I'm not sure how to preserve squashing in general and allow exceptions, except by explicitly going behind the scenes through the admin settings, which is what I have been doing when moving stuff around across repos.

**Comment by kyessenov** [comment]
How about creating a label "requires-admin-merge" and making sure the bot respects it?

**Comment by geeknoid** [comment]
Actually, you can already set the do-not-merge label to prevent
auto-merging. So the pattern is to set that label, and then ping me
explicitly to do the merge in merge mode.

*From: *Kuat <notifications@github.com>
*Date: *Tue, May 14, 2019 at 8:54 PM
*To: *istio/istio
*Cc: *Martin Taillefer, Mention

How about creating a label "requires-admin-merge" and making sure the bot
