### ISSUE TITLE
Extend cluster ingress to TCP services

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1409]
@kyessenov commented on [Fri Jul 28 2017](https://github.com/istio/old_pilot_repo/issues/969)

Currently, cluster ingress is entirely HTTP based (in line with k8s notion of ingress).
There's extra benefit of having dedicated TCP proxy ingress in Istio:
- reuse IP for multiple services using port redirection (contrast with LoadBalancer type service which requires a fresh external IP address)
- enforce mTLS for in-cluster TCP services (LoadBalancer services cannot accept external traffic once istio auth feature is enabled)
- consistent policy injection at the cluster ingress point

The downside is that we would be diverging from the k8s specification for ingress. We would need to consume ingress rules directly, in addition to ingesting k8s ingress resources.

Thoughts?
@rshriram @louiscryan 

---

@rshriram commented on [Fri Jul 28 2017](https://github.com/istio/old_pilot_repo/issues/969#issuecomment-318781729)

Cc @cmluciano since you expressed interest in this

---

@cmluciano commented on [Wed Aug 02 2017](https://github.com/istio/old_pilot_repo/issues/969#issuecomment-319745847)

Can we add an example config file for how a user would specify this? Do we expect if I send a packet destined for localhost:myspecialport that Pilot would note that all myspecialport resembles this cluster-ip?

---

@kyessenov commented on [Wed Aug 02 2017](https://github.com/istio/old_pilot_repo/issues/969#issuecomment-319780365)

Here's a very basic example. Let's say we run istio ingress as `istio-ingress` service that's exposed externally. We want to route istio-ingress:3000 to mysql:5000 where mysql is an internal service. We might want auth enabled on both sides. The config might look like:
```
kind: ingress-rule
name: mysql-exposed
port: 3000
tlsSecret: mysql-secret
destination: mysql
destinationPort: 5000  
```

---

@cmluciano commented on [Fri Aug 04 2017](https://github.com/istio/old_pilot_repo/issues/969#issuecomment-320320528)

There was thought around requesting TCP support in k8s ingress, is this something that we still think is viable?

---

@cmluciano commented on [Fri Aug 04 2017](https://github.com/istio/old_pilot_repo/issues/969#issuecomment-320321997)

This seems possible in the nginx implementation of k8s ingress

https://github.com/kubernetes/ingress/blob/master/examples/tcp/nginx/nginx-tcp-ingress-configmap.yaml

---

@aledbf commented on [Fri Aug 04 2017](https://github.com/istio/old_pilot_repo/issues/969#issuecomment-320324252)

@cmluciano that only exists because there is no k8s loadbalancer option in baremetal. This option should not be used if you are in a cloud provider.

---

@cmluciano commented on [Fri Aug 04 2017](https://github.com/istio/old_pilot_repo/issues/969#issuecomment-320327281)

ack, I'm not sure if Istio makes assumptions on a cloud provider, but this could collide in the end. Do you have any thoughts on support for TCP @aledbf ?

---

@aledbf commented on [Fri Aug 04 2017](https://github.com/istio/old_pilot_repo/issues/969#issuecomment-320328933)

@cmluciano I think Ingress (k8s concept) should not support TCP and just use `type=Loadbalancer` in the service. 
The users ask for TCP support in Ingress because if you are running in the cloud you cannot share the load balancer between different services which means 1 loadbalancer per service (using the nginx ingress controller you can bypass this)

The kyessenov example should be just another k8s service, not need to use Ingress (k8s) for that usecase

---

@cmluciano commented on [Fri Aug 04 2017](https://github.com/istio/old_pilot_repo/issues/969#issuecomment-320338172)

Ahhhh, I understand. I never used some of these features in k8s. Thanks for pointing this out!

---

@kyessenov commented on [Fri Aug 04 2017](https://github.com/istio/old_pilot_repo/issues/969#issuecomment-320340905)

@aledbf the problem in Istio case is that LoadBalancer type service cannot accept external connection since it expect mTLS handshake. We need some intermediary for terminating end-user auth to in-cluster auth.

---

@cmluciano commented on [Wed Aug 16 2017](https://github.com/istio/old_pilot_repo/issues/969#issuecomment-322901931)

xref: https://github.com/kubernetes/kubernetes/issues/17571

---

@linsun commented on [Wed Aug 30 2017](https://github.com/istio/old_pilot_repo/issues/969#issuecomment-326014383)

@cmluciano can you provide your outlook for this?  Trying to understand if this can be in beta or not.  Thanks!

---

@cmluciano commented on [Wed Aug 30 2017](https://github.com/istio/old_pilot_repo/issues/969#issuecomment-326064597)

Discussed with @kyessenov This should not be a blocker for 0.2. I can continue to own this and deliver in a 0.2.X release.

---

@douglas-reid commented on [Tue Oct 03 2017](https://github.com/istio/old_pilot_repo/issues/969#issuecomment-333892496)

Has there been any update to the work on this issue?

---

@cmluciano commented on [Tue Oct 03 2017](https://github.com/istio/old_pilot_repo/issues/969#issuecomment-333937254)

I have not worked on it recently.

---

@kyessenov commented on [Tue Oct 03 2017](https://github.com/istio/old_pilot_repo/issues/969#issuecomment-333937902)

No update, this feature is not making it to 0.2

**Comment by cmluciano** [comment]
cc @ZackButcher Is this part of your work in Ingress?

**Comment by ZackButcher** [comment]
Short term my work is focused on k8s ingress which is HTTP only. So no, I'm not planning on working this in the short term (next month or so). I'll definitely keep this in mind so it'll be easier to add down the line.

**Comment by cmluciano** [comment]
@rshriram Is this something that we can still do now or is this awaiting pending changes to either upstream k8s ingress or our own ingress implementation?

**Comment by idevz** [comment]
any update here? could I set ingress-nginx as a LoadBalancer for istio-ingress in a bare metal Env?

```yaml
################################
# Istio ingress
################################
apiVersion: v1
kind: Service
metadata:
  name: istio-ingress
  namespace: istio-system
  labels:
    istio: ingress
spec:
  type: LoadBalancer
  loadBalancerIP: 10.211.55.75 ## loadBalancerIP is a ingress-nginx address
  ports:
  - port: 80
#   nodePort: 32000
    name: http
  - port: 443
    name: https
  selector:
    istio: ingress
```

**Comment by rshriram** [comment]
Handled by the new Istio Gateway. Please wait for 0.8 release to try this.

**Comment by kim0** [comment]
@rshriram .. Thanks for the update. Anywhere we can read more about this now ?

**Comment by rshriram** [comment]
If you are feeling adventurous, you could run istio from master and try it out for yourself.. we have e2e tests using TCP gateway..
