### ISSUE TITLE
Create helm chart for istio components

### ISSUE THREAD

**Issue by dcberg** [istio/istio#141]
It would be nice if we had a [helm](https://helm.sh) chart for installing the necessary istio components.

**Comment by baldwinSPC** [comment]
We're open to helping with this if no one is working on it?

**Comment by andraxylia** [comment]
We are happy to get help on this.

**Comment by rimusz** [comment]
I have started to work on Helm chart at https://github.com/StackPointCloud/istio.

**Comment by rimusz** [comment]
unfortunately having the helm chart will break generation from templates, all changes/new stuff will need to be updated/added manually

**Comment by baldwinSPC** [comment]
We're done and will test through all the deployment options tomorrow. We should be sending in a PR around then, too.

**Comment by rimusz** [comment]
#330 for the helm chart

**Comment by deedubs** [comment]
Looks like this can be closed now.

**Comment by ebullient** [comment]
Is this done? #330 is complete

**Comment by gyliu513** [comment]
It is here https://github.com/kubernetes/charts/tree/master/incubator/istio and hosted in kubernets charts but not istio. @ebullient I think we can close this one now.
