### ISSUE TITLE
Dep init failed

### ISSUE THREAD

**Issue by aus729xz** [istio/istio#14105]
The latest istio source tree 
dep init
Importing configuration from glide. These are only initial constraints, and are further refined during the solve process.
Importing configuration from glide. These are only initial constraints, and are further refined during the solve process.
....
init failed: unable to solve the dependency graph: Solving failure: package k8s.io/apimachinery/pkg/apis/meta/v1/unstructured/unstructuredscheme does not exist within project k8s.io/apimachinery

**Comment by howardjohn** [comment]
We recently moved to using go modules, I think we don't support/use dep anymore

**Comment by kyessenov** [comment]
Yes, we can no longer support dep since we moved to go modules, and the two don't agree on dependency resolution.
