### ISSUE TITLE
What is the roadmap for Istio installation?

### ISSUE THREAD

**Issue by fpesce** [istio/istio#14116]
@andrecastro commented on [Wed May 15 2019](https://github.com/istio/installer/issues/175)

Hello guys,

I would like to understand what is the roadmap of how to deploy Istio and what is the tool you seek to use/maintain in future versions.

My task is to evaluate what are the possible ways to install Istio in my k8s cluster, and today I see 3 options:

* Use helm chart
* Use istio-operator from banzai cloud
* Use this installer

but I would like to understand what you guys have in mind. Some questions I have:

* Are going to deprecate the usage of helm chart?
* Are going to create a new Istio Operator?
* What exactly this installer has in advantage of the helm chart?

**Comment by vhosakot** [comment]
> My task is to evaluate what are the possible ways to install Istio in my k8s cluster, and today I see 3 options:
>
> Use helm chart
> Use istio-operator from banzai cloud
> Use this installer

I've used all three ways to deploy istio and I think https://github.com/istio/installer is complicated and it needs a single command to install istio IMO, hence opened https://github.com/istio/istio/issues/14175.

Also, I don't see an "istio-operator" in https://github.com/istio/installer like what https://github.com/banzaicloud/istio-operator#installation creates (see below):

```
$ helm ls istio-operator
NAME          	REVISION	UPDATED                 	STATUS  	CHART               	APP VERSION	NAMESPACE   
istio-operator	1       	Wed May 15 18:16:14 2019	DEPLOYED	istio-operator-0.0.5	0.1.6      	istio-system

$ kubectl get pods -n=istio-system
...
istio-operator-operator-0                 2/2     Running   0          8m1s
...

kubectl describe pods -n=istio-system | grep Image:
...
    Image:         banzaicloud/istio-operator:0.1.6
...
```

The other two ways are easy to use in my experience compared to https://github.com/istio/installer:

1. Helm:
    - https://github.com/istio/istio/tree/master/install/kubernetes/helm/istio-init
    - https://github.com/istio/istio/tree/master/install/kubernetes/helm/istio

2. https://github.com/banzaicloud/istio-operator#installation

**Comment by andrecastro** [comment]
I agree with you @vhosakot, the installer seems to be complicated and the helm chart seems to be pretty straight forward. My only concern is if they will maintain the chart for future Istio releases or if they are working on other tools to install Istio.

I see some efforts on the [istio-installer](https://github.com/istio/installer) and also on [operator](https://github.com/istio/operator), but I would like to know which one will be the official tool for future releases.

**Comment by mabushey** [comment]
I switched to the Bonzai operator and several issues went away, such as upgrading Istio and still having a functioning cluster. It's easier, better, and cleaner. The config is everything you need in one small readable yaml file.

**Comment by vhosakot** [comment]
@mabushey Yeah, https://github.com/banzaicloud/istio-operator is great, but fyi, it does not currently install istio's prometheus and grafana needed to monitor istio - https://github.com/banzaicloud/istio-operator/issues/41#issuecomment-492823635

**Comment by mabushey** [comment]
@vhosakot I ripped the grafana section of the config out of the old helm install. Works great. The operator even has enough control that I was able to run jaeger in a tracing namespace. I put it into production as I finally felt I could rely on it and everyone has been happy, it's been running flawless.

**Comment by howardjohn** [comment]
The roadmap is the operator, see new operator docs on istio.io
