### ISSUE TITLE
No Access Log when Istio Blocks External Request

### ISSUE THREAD

**Issue by aaronmell** [istio/istio#14110]
**Bug description**
When global.outboundTrafficPolicy.mode is set to REGISTRY_ONLY, there are no logs showing up in istio-proxy that a request for an external resource is being rejected. global.proxy.accessLogFile is set to /dev/stdout

**Expected behavior**
I would expect the proxy to log that it rejected an external request.

**Steps to reproduce the bug**

1. Enable outboundTrafficPolicy
2. Enable AccessLogs
3. Exec into a running pod that is sending traffic through the proxy
4. curl an external endpoint
5. Check stdout of the proxy, no reject log's exist

exec into a running pod and curl to an external endpoint like google. 

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T19:44:19Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}

Istio 1.1.6

**How was Istio installed?**
Via Helm

**Environment where bug was observed (cloud vendor, OS, etc)**
Docker Macos

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[x] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by aaronmell** [comment]
Looks like it only affects requests made over https 
curling https://www.google.com returns the following error and no long in access-logs
 LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to www.google.com:443 
curling http://www.google.com returns nothing and I get a log in istio-proxy that contains a 502

**Comment by howardjohn** [comment]
@aaronmell due to how the http/https routing works in Envoy, we return different responses for different circumstances. If you send traffic to a port with another service on it (80 in your case) we will 502. If it won't be intercepted by Envoy (https), or is tcp in which case we can't return a 502, then we just block the request. In 1.1.6 we added access logs that I thought cover the blocked requests, but I never tried it myself.

Could you post the output of `istioctl pc listener POD --port 15001 -ojson`

**Comment by aaronmell** [comment]
@howardjohn 
[
    {
        "name": "virtual",
        "address": {
            "socketAddress": {
                "address": "0.0.0.0",
                "portValue": 15001
            }
        },
        "filterChains": [
            {
                "filters": [
                    {
                        "name": "envoy.tcp_proxy",
                        "config": {
                            "cluster": "BlackHoleCluster",
                            "stat_prefix": "BlackHoleCluster"
                        }
                    }
                ]
            }
        ],
        "useOriginalDst": true
    }
]

**Comment by howardjohn** [comment]
Ah I see the problem now, we only add for Passthrough. https://github.com/istio/istio/pull/13776/files#diff-86fb73d7dd150e47328ead76ceca0992R205

@dwradcliffe was there any reason to not add this for blackhole cluster?

**Comment by dwradcliffe** [comment]
The only reason was that I'm not using REGISTRY_ONLY at the moment, but seems like we should add it there too. 👍

**Comment by esauser** [comment]
@rshriram @lei-tang @dwradcliffe was this functionality ever actually added to a release? The referenced pull request was soon reverted, https://github.com/lei-tang/istio/commit/b638ba2770a514204764996e11c2c6fb6e1c7a8f.  

We also have a need to log Istio blocks to external requests and have not been able to find a solution.

**Comment by dwradcliffe** [comment]
Oops, I didn't realize it was reverted. I'm not using this anymore so I'm not sure if anyone else fixed it. Sorry!
