### ISSUE TITLE
Eliminate hardcoded exceptions for `kube-system` or make it optional

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1411]
@kyessenov commented on [Tue Aug 29 2017](https://github.com/istio/old_pilot_repo/issues/1133)

Currently, the service controller is excluding kube-system without a way to change it. This will cause problems when istio runs in kube-system.
See https://github.com/istio/pilot/commit/720d751f5a82dcd746e3b36d8dadee96647c1d17#diff-9b493b4288200b30b3d0953052d6abdaR425

---

@ldemailly commented on [Tue Aug 29 2017](https://github.com/istio/old_pilot_repo/issues/1133#issuecomment-325762543)

istio managing kube-system without breaking it seems like a much bigger task than just making the excluded namespace configurable

this being said I think we should have a whitelist/blacklist and selector based setup instead of the current 1 namespace vs all namespaces (minus kube-system) setup. but none of that is for 0.2

**Comment by ijsnellf** [comment]
This is still valid.
