### ISSUE TITLE
Add CtrlZ support and other status support to Citadel Agent

### ISSUE THREAD

**Issue by JimmyCYJ** [istio/istio#14128]
**Describe the feature request**
Currently Citadel, Mixer, Pilot and Galley has [ControlZ](https://istio.io/help/ops/controlz/) support.  We need to add ControlZ to Citadel Agent. That could help to debug SDS issues.
1. ControlZ allows us to change log level at runtime
1. We could add counters into Citadel Agent and monitor the counter values via ControlZ
1. ControlZ presents process info, memory usage, cpu usage etc. which are helpful for debugging.

We need another endpoint at Citadel Agent to keep track of secret push. e.g.
open browser to http://localhost:9876/sds which lists information as below

citadel agent start time

* connection ID
* connect begin time
* status (active/stale)
* resource name
* ACK timestamp
* all pushed secrets' version info
* pushed cert info(SAN, issuer, expiration time)

This information should not cause any security leak.

**Comment by JimmyCYJ** [comment]
cc @diemtvu @myidpt @quanjielin @wattli

**Comment by JimmyCYJ** [comment]
We probably also need a similar endpoint at Citadel to monitor cert sign status. E.g.
table 1
timestamp of CSR request, citadel agent id, timestamp of CSR response
table 2
list of citadel agent and timestamp of most recent CSR

**Comment by incfly** [comment]
One thing:

- we need to ensure the ctrlz is exposed as `localhost:port`, which is default. The `0.0.0.0` bound address will make it accessible to as `POD_IP:port`.
- we probably need to set rbac for port-forwarding as well. not sure if today's rbac is strong enough.
