### ISSUE TITLE
Move any generic tools from istio/istio to istio/tools

### ISSUE THREAD

**Issue by geeknoid** [istio/istio#14123]

**Comment by incfly** [comment]
Can you elaborate a bit of more on what meets the criteria of generic tools? Debugging, development, all counts?

**Comment by incfly** [comment]
And some tools take some go library dependency with istio/istio. That requires decompose the repo and have a repo for common util, logging/constants/etc?

**Comment by geeknoid** [comment]
By common tool, I mean anything that is used by multiple repos.

We have istio/common-files for build-related files that need be to mirrored in all repos. istio/pkg for packages shared across repos. pkg/tools for tools shared across repos.

Note that there's a different issue opened to consolidate docker container creation to istio/tools as well. So the tools can be built there along with the images.

**Comment by howardjohn** [comment]
Done?
