### ISSUE TITLE
Turndown use of CircleCI in all repos

### ISSUE THREAD

**Issue by geeknoid** [istio/istio#14122]
We are consolidating around prow, we need to turn down all CircleCI use.

**Comment by howardjohn** [comment]
are we going to use prow in other repos?

**Comment by geeknoid** [comment]
That's the plan. Prow everywhere, no CircleCI.

**Comment by howardjohn** [comment]
Istio/Istio has no circleci running in presubmit anymore, just need the other repos now

**Comment by howardjohn** [comment]
just istio/proxy left

**Comment by duderino** [comment]
@PiotrSikora but we need to keep circleci around for macos builds

**Comment by PiotrSikora** [comment]
See: https://github.com/istio/istio/issues/16030

**Comment by howardjohn** [comment]
Closing as everything is done but proxy which is tracked in https://github.com/istio/istio/issues/16030
