### ISSUE TITLE
Move pkg/test to the test-framework repo.

### ISSUE THREAD

**Issue by geeknoid** [istio/istio#14121]
We should move generic parts of the test framework to the istio/pkg repo/

**Comment by kyessenov** [comment]
pkg/test has a circular dependency on the istio itself. We should separate the pieces out of pkg/test first that are istio specific.

**Comment by geeknoid** [comment]
That's why I said "generic parts" :-)

**Comment by geeknoid** [comment]
Can we make this happen soon? We now have multiple active code repos that can't leverage the test frameworkl.

**Comment by ozevren** [comment]
The core of the framework needs a few minor refactorings, but otherwise relatively easy to move. 
However, components and environments needs consideration.

Most components are quite heavily tied to istio/istio repo. Very few of them can be moved to pkg/, along with the framework. This is not an issue for istio/istio repo (as we can simply keep the components in there), however it means the components will not be usable in other repos. So, depending on which repos we want to target first to use this framework in, the value proposition of having the framework may not be high.

The environments is another issue. Moving environment support (kube & native) means also taking a dependency to the K8s libraries from pkg, which will permeate everywhere. Is that acceptable?

**Comment by kyessenov** [comment]
I don't think it's acceptable to have k8s dependency from istio/pkg. It's a very heavy weight library, adding megabytes to the binary.

**Comment by kyessenov** [comment]
Should we create a separate repo for the test framework? I don't think any released component should take a dependency on the tests. Moving it to istio/pkg allows this possibility, but if we keep test framework as a separate repo, it's much harder to introduce undesired dependency. The test repo can also take a dependency on all other istio repos.

**Comment by ozevren** [comment]
The dependency linking should be per binary/executable, so I don't think just having the dependency from the test framework will permeate to actual product binaries.

However, I am not sure how vendoring/go modules work in this regard. I see that as the most problematic aspect.

In terms of repo layering, separating out test framework to its own repo will cause it to become a leaf node in repo hierarchy, and stop us from using it in tests in many of the repos where it would be useful. For example, if we separate out Galley and Pilot to its own repo, then we won't be able to use the framework to test within those repos.

**Comment by kyessenov** [comment]
Here's a simple trick to avoid binary dependency on tests: move all framework code into _test.go files. Then we can be sure dependencies are not leaking to the binaries.

**Comment by geeknoid** [comment]
Can you have code in a _test.go import from another package and access the stuff in its _test.go files?

**Comment by ozevren** [comment]
How big a concern is this? I've never seen prod binaries taking a dependency on testing related code, but it may just be me. It is generally dead obvious when such a thing happens, especially in a code review. It is much more likely to accidentally sneak in a "simple method or a const" from a seemingly innocent library that ends up pulling the kitchen sink.

I don't think _test.go approach works. I don't think you reference _test.go code in other packages. I remember trying this and seeing this not working (though I have the memory capacity of a goldfish, so I might be misremembering things).

As said before, the vendoring (or go modules) would be my main concern. In istio/istio, it has generally been a nightmare to keep the vendor folder updated. I am not sure how it would work with go modules, with cross-repository dependencies within istio repositories.

**Comment by kyessenov** [comment]
We already introduced a dependency on pkg/test from released binaries, so this is a real concern:
```sh
go list -f '{{ join .Deps "\n"  }}' ./pilot/... | grep "pkg/test"
istio.io/istio/pkg/test
 go list -f '{{ join .Deps "\n"  }}' ./mixer/... | grep "pkg/test"
istio.io/istio/pkg/test
istio.io/istio/pkg/test/env
istio.io/istio/pkg/test/fakes/policy
```

**Comment by ozevren** [comment]
I tried Goland to find references and it looks like the only non-test dependency in Pilot is mock/config (which seems like a test library).

Similarly in Mixer, the references are either from tests, or from code under mixer/test.

**Comment by kyessenov** [comment]
I am having flashbacks to the early istio with multiple repos, where it would take 3 PRs to fix a test, so I understand your concern with the code layout and modules. However, it is more important not to ship test artifacts in the binary. We don't have bazel-like system to enforce code separation, and we cannot rely on reviewers accidentally slipping a dependency on something in pkg/test that ends up pulling all the rest of pkg/test.

**Comment by geeknoid** [comment]
Given the dependency chain, perhaps we would be better off with an
istio/test-framework repo? It would still need to be generic stuff, so no
component-specific logic, but at least all the k8s dependencies would be
constrained so we don't pull that in everywhere. Ideally, once we're done
with all this, only the galley repo and istioctl repo will have
dependencies on k8s, everything else should be generic.

**Comment by ozevren** [comment]
As per offline discussion, if we switch to a binary only dependency to the underlying components from the test framework and leave test framework's "components" as shims to drive the binaries, then we can break the dependency cycles and make the test framework a dependency of pkg (and K8s libraries). This should allow use of the framework from other repos, although we may still need to do some refactoring to avoid pulling in K8s libraries transitively when they are not needed by the leaf dependency repo.

**Comment by ozevren** [comment]
@nmittler

**Comment by kyessenov** [comment]
Please make sure to add proper linting to avoid pulling client-go in any consumer of pkg. All it takes is a single init constructor to cause unwanted dependencies.
