### ISSUE TITLE
Consolidate all tool-related docker image creation to the istio/tools repo

### ISSUE THREAD

**Issue by geeknoid** [istio/istio#14124]
We build docker images in several different repos, using several different approaches. We should

- [ ] consolidate the number of images to the smallest meaningful number.
- [ ] consolidate creation of the images in the tools repo.
- [ ] provide a consistent way to propagate current image names to use across repos. The istio/common-files repo may be useful for this.

**Comment by costinm** [comment]
First item: the recommendation from almost all CI/CD systems I reviewed is to use specialized, narrow images. GCB for example maintain a set of images for common tasks that can be reused, knative builder has a similar standard. Unfortunately some CI/CD environment is slightly different - so at least some images need to be specialized.

Second part - sounds great for tools that are used across repos. However please don't move all docker images to tools, only the tool-related images and base images. Pilot, installer, mixer, etc create images - and it doesn't make sense to move them around.

On 3rd - using labels (:latest in particular) works very well.

**Comment by geeknoid** [comment]
@costinm Agreed on all fronts.

**Comment by ericvn** [comment]
Intermediate doc as I'm figuring out the Istio build and image creation process. 
[Istio_Dockerfiles.xlsx](https://github.com/istio/istio/files/3209271/Istio_Dockerfiles.xlsx)

**Comment by incfly** [comment]
/cc @incfly 

subscribed as I'm writing some testing binary, and under current schema, we have to create another Docker image, which not ideal.

**Comment by geeknoid** [comment]
Wow, that spreadsheet is amazing. I didn't realize things had gotten so out of control. I think you missed the istio/api repo, there are some more images being created from there.
