### ISSUE TITLE
Istioctl namespace support

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#14139]
Right now istioctl takes in an istioSystem argument, but we cannot support multiple namespaces

**Comment by esnible** [comment]
@richardwxn Do you have a design for this we can review?  Do you expect a PR for 1.2?

**Comment by howardjohn** [comment]
For 1.3 we are keeping the new installer limited to a single namespace for the most part, so I moved the milestone. This is still something we should solve eventually though

**Comment by howardjohn** [comment]
Namespaces are no longer important, we will have 1 namespace now. But we will need to be careful about multiple control planes
