### ISSUE TITLE
Can we change grafana datasource name to "prometheus"?

### ISSUE THREAD

**Issue by zgfh** [istio/istio#14137]
because  datasource name of promethues operator  create is "prometheus",not "Prometheus", If we change to same, it will be easy to import 

https://github.com/istio/installer/blob/master/istio-telemetry/grafana/dashboards/galley-dashboard.json#L35
https://github.com/coreos/kube-prometheus/blob/master/manifests/grafana-dashboardDatasources.yaml#L3

**Comment by howardjohn** [comment]
I think if we made this change we would get some users requesting we switch it back to "Prometheus" for some reason or another. Is there a better solution where we can make it configurable using the grafana template stuff?
