### ISSUE TITLE
Fix tests relying on SystemNamespace

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#14141]
At least one does, `mixer_policy_ratelimit`.

Probably need to search for usages of https://github.com/istio/istio/blob/baa1815a1422cb52aa2112dcf3ce1604884bf747/pkg/test/framework/components/istio/config.go#L78 and clean them all up

**Comment by rlenglet** [comment]
According to @howardjohn, this can be solved by https://github.com/istio/istio/issues/14098.
