### ISSUE TITLE
istio-installer does not work anymore for release-1.1

### ISSUE THREAD

**Issue by c0d1ngm0nk3y** [istio/istio#14146]
Since https://github.com/istio-ecosystem/istio-installer/commit/b7e869e69f8755af913ae19763e7483b01db0974, the istio-installer does not work anymore with release-1.1. Reason is that the sidecar-injector does not understand the introduced template.

Currently the concourse pipeline is testing following:

* Install release-1.1-daily
* Test it
* Install 1.1.0 (to have something to update from)
* Update to release-1.1-daily
* Test it

What are the actual supported usecases for the istio-installer? Especially with istio version can be installed and updated to.

**Comment by costinm** [comment]
I think given the time and remaining issues - we can start this for 1.2, and assume 1.1 is installed with old installer.
