### ISSUE TITLE
Need to supply ingressNamespace and mcpAddr to Pilot

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#14148]
https://github.com/istio-ecosystem/istio-installer/pull/33/files

mcpAddr:
> That's a bug - should go into configmap-envoy.yaml.
It's a bit more complicated - Galley has a cert that is based on the name, so we'll need to test how using a different mcpAddress really work - I don't think in the istio/istio it was tested too much.

ingressNamespace:
> Interesting - that would be a bug. Pilot needs to know where to find the IP of the ingress service.

**Comment by costinm** [comment]
On this topic - please double check that Policy is using the same configs as telemetry and pilot ( envoy sidecar, mcpAddr, etc ).

**Comment by howardjohn** [comment]
@costinm can you explain what work is needed for this and why? Things seem to be working fine without these options so I am not sure what we need to do

**Comment by howardjohn** [comment]
There is no clear action here on why we need these options
