### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by loewenstein** [istio/istio#14155]
We should automatically verify that the new installer can install known Istio versions. As the current CI of the Istio community is CircleCI, we should deliver this as CircleCI config.

Things to verify:
* The installation is indeed modular:
   - Install Istio Citadel + Control plane and verify a service A can reach a service B via Envoy data plane 
   - Add an Istio Ingress Gateway and verify we can reach service A from outside the cluster 
   - Add Istio telemetry and verify we get metrics from the service mesh
   - Add Istio Policy and verify that it works
   - Add Istio Egress Gateway and verify that it works
* The installation can be updated without service degradation:
  - Update all Istio components and verify that the service mesh stays functional 

I propose we verify the installation of Istio 1.1.0 and the update to the branch release-1.1.

**Comment by costinm** [comment]
I'll close this - file new issues if you find problems.
