### ISSUE TITLE
Autoinject: support 1.1 labels

### ISSUE THREAD

**Issue by costinm** [istio/istio#14150]
For upgrade/migration, add a flag to allow one 'environment' to support the 1.1 injection labels.
This will allow a smooth upgrade.

istio-env label allows namespaces to target a specific environment.

**Comment by esnible** [comment]
Can you link me to the docs on what the 1.1 injection labels are?

**Comment by howardjohn** [comment]
This is done, see https://github.com/istio/installer/blob/master/istio-control/istio-autoinject/templates/mutatingwebhook.yaml#L32-L50
