### ISSUE TITLE
Review ClusterRoles for all components

### ISSUE THREAD

**Issue by costinm** [istio/istio#14158]
- Pilot appears to have read access to all cluster Secrets - not aware of any need for this.
Only Citadel should have access to cluster-wide Secrets, nothing else.
- probably other components also have too broad access, which is a security issue ( escalation )

**Comment by costinm** [comment]
Pilot needs to watch secrets in its own namespace, not cluster wide. This is even more important with new installer, as it should be possible to deploy pilot in a less trusted namespace (testing environments, etc).

If MCP is enabled, Pilot should need even fewer cluster rules (galley reads/watches the resources)

**Comment by yangminzhu** [comment]
> Pilot needs to watch secrets in its own namespace, not cluster wide. This is even more important with new installer, as it should be possible to deploy pilot in a less trusted namespace (testing environments, etc).
> 
> If MCP is enabled, Pilot should need even fewer cluster rules (galley reads/watches the resources)

If MCP is enabled, does Pilot still need to read/watch any k8s resources? I thought it doesn't but just would like to confirm if there is any exception here. Currently I think pilot still reads some resources (e.g. Service) even if MCP is enabled as galley doesn't return all resources at the moment, but in the long run it should, maybe in 1.3?

**Comment by andraxylia** [comment]
With MCP fully enabled and if we clean up Pilot from all K8s dependency, Pilot will no longer need to read any secrets.

**Comment by kyessenov** [comment]
@fpesce I am not sure it is a good idea to remove authorization roles from pilot if it uses an alternative channel to read information. In a way, MCP allows unauthorized access that is not subject to k8s RBAC. So even though Pilot does not need k8s roles attached to its service account, it has all the privileges that come with it, so should be associated with an equivalent or more capable role.

**Comment by andraxylia** [comment]
I deem this kind of change too risky for 1.2 @fpesce we should move this to later.

**Comment by fpesce** [comment]
@andraxylia / @kyessenov your concerns are valid, we need to discuss this on a different milestone. shifting this to 1.3.

**Comment by sdake** [comment]
if this is a P0 for 1.3, the work needs be done for old and new installer.
