### ISSUE TITLE
CA and auth setup improvements

### ISSUE THREAD

**Issue by costinm** [istio/istio#14167]
1. Default to 'provisioned cert', use the tool to generate the root and upload it - for consistency 
and to make multi-cluster setup easier. This will eliminate some options and simplify the templates.
2. Extend the tooling to generate a .CRT and .PFX file that can be imported in browsers
3.  Switch grafana/prom/etc access via gateway to use client certs and istio-based RBAC, using the generate CRT/PFX

**Comment by incfly** [comment]
fyi https://github.com/istio/istio/blob/master/security/tools/generate_cert/main.go
