### ISSUE TITLE
Citadel CrashLoopBackOff Error: unknown flag: --grpc-hostname

### ISSUE THREAD

**Issue by cuongsimplypost** [istio/istio#14169]
(This is used to report product bugs, please visit <https://discuss.istio.io> for questions on using Istio)

**Bug description**
Installation of istio using helm template fails with start of Citadel.

Error: unknown flag: --grpc-hostname
Usage:
  istio_ca [flags]
  istio_ca [command]

Available Commands:
  help        Help about any command
  probe       Check the liveness or readiness of a locally-running server
  version     Prints out build version information

Flags:
      --append-dns-names                           Append DNS names to the certificates for webhook services. (default true)
      --cert-chain string                          Path to the certificate chain file.
      --citadel-storage-namespace string           Namespace where the Citadel pod is running. Will not be used if explicit file or other storage mechanism is specified. (default "istio-system")
      --ctrlz_address string                       The IP Address to listen on for the ControlZ introspection facility. Use '*' to indicate all addresses. (default "localhost")
      --ctrlz_port uint16                          The IP port to use for the ControlZ introspection facility (default 9876)
      --custom-dns-names string                    The list of account.namespace:customdns names, separated by comma.
      --enable-profiling                           Enabling profiling when monitoring Citadel.
      --experimental-dual-use                      Enable dual-use mode. Generates certificates with a CommonName identical to the SAN.
      --explicit-opt-in                            Specifies whether Citadel requires explicit opt-in for creating secrets. If set, only namespaces labeled with 'istio-managed=enabled' will have secrets created. This feature is only available in key and certificates delivered through secret volume mount.
      --grpc-host-identities string                The list of hostnames for istio ca server, separated by comma. (default "istio-ca,istio-citadel")
      --grpc-port int                              The port number for Citadel GRPC server. If unspecified, Citadel will not serve GRPC requests. (default 8060)
  -h, --help                                       help for istio_ca
      --key-size int                               Size of generated private key. (default 2048)
      --kube-config string                         Specifies path to kubeconfig file. This must be specified when not running inside a Kubernetes pod.
      --listened-namespaces string                 Select the namespaces for the Citadel to listen to, separated by comma. If unspecified, Citadel tries to use the ${NAMESPACE} environment variable. If neither is set, Citadel listens to all namespaces.
      --liveness-probe-interval duration           Interval of updating file for the liveness probe.
      --liveness-probe-path string                 Path to the file for the liveness probe.
      --log_as_json                                Whether to format output as JSON or in plain console-friendly format
      --log_caller string                          Comma-separated list of scopes for which to include caller information, scopes can be any of [default, model, rbac]
      --log_output_level string                    Comma-separated minimum per-scope logging level of messages to output, in the form of <scope>:<level>,<scope>:<level>,... where scope can be one of [default, model, rbac] and level can be one of [debug, info, warn, error, fatal, none] (default "default:info")
      --log_rotate string                          The path for the optional rotating log file
      --log_rotate_max_age int                     The maximum age in days of a log file beyond which the file is rotated (0 indicates no limit) (default 30)
      --log_rotate_max_backups int                 The maximum number of log file backups to keep before older files are deleted (0 indicates no limit) (default 1000)
      --log_rotate_max_size int                    The maximum size in megabytes of a log file beyond which the file is rotated (default 104857600)
      --log_stacktrace_level string                Comma-separated minimum per-scope logging level at which stack traces are captured, in the form of <scope>:<level>,<scope:level>,... where scope can be one of [default, model, rbac] and level can be one of [debug, info, warn, error, fatal, none] (default "default:none")
      --log_target stringArray                     The set of paths where to output the log. This can be any path as well as the special values stdout and stderr (default [stdout])
      --max-workload-cert-ttl duration             The max TTL of issued workload certificates. (default 2160h0m0s)
      --monitoring-port int                        The port number for monitoring Citadel. If unspecified, Citadel will disable monitoring. (default 15014)
      --org string                                 Organization for the certificate.
      --pkcs8-keys                                 Whether to generate PKCS#8 private keys.
      --probe-check-interval duration              Interval of checking the liveness of the CA. (default 30s)
      --read-signing-cert-only                     When set, Citadel only reads the self-signed signing key and cert from Kubernetes secret without generating one (if not exist). This flag avoids racing condition between multiple Citadels generating self-signed key and cert. Please make sure one and only one Citadel instance has this flag set to false.
      --requested-ca-cert-ttl duration             The requested TTL for the CA certificate. (default 8760h0m0s)
      --root-cert string                           Path to the root certificate file.
      --self-signed-ca                             Indicates whether to use auto-generated self-signed CA certificate. When set to true, the '--signing-cert' and '--signing-key' options are ignored.
      --self-signed-ca-cert-ttl duration           The TTL of self-signed CA root certificate. (default 8760h0m0s)
      --server-only                                When set, Citadel only serves as a server without writing the Kubernetes secrets.
      --sign-ca-certs                              Whether Citadel signs certificates for other CAs.
      --signing-cert string                        Path to the CA signing certificate file.
      --signing-key string                         Path to the CA signing key file.
      --trust-domain string                        The domain serves to identify the system with SPIFFE.
      --upstream-ca-address string                 The IP:port address of the upstream CA. When set, the CA will rely on the upstream Citadel to provision its own certificate.
      --workload-cert-grace-period-ratio float32   The workload certificate rotation grace period, as a ratio of the workload certificate TTL. (default 0.5)
      --workload-cert-min-grace-period duration    The minimum workload certificate rotation grace period. (default 10m0s)
      --workload-cert-ttl duration                 The TTL of issued workload certificates. (default 2160h0m0s)

Use "istio_ca [command] --help" for more information about a command.

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.9", GitCommit:"16236ce91790d4c75b79f6ce96841db1c843e7d2", GitTreeState:"clean", BuildDate:"2019-03-25T06:30:48Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
helm template istio-1.1.5/install/kubernetes/helm/istio --name istio --namespace istio-system --values ./istio/values.yaml | kubectl apply -f -

**Environment where bug was observed (cloud vendor, OS, etc)**
aws ec2 linux 2 iam

**Comment by howardjohn** [comment]
Can you `kubectl describe` the citadel pod (or just get what image it is running)? I think what happened is we removed the flag on the master branch, so I suspect somehow you are using the newer images?

**Comment by cuongsimplypost** [comment]
I manage to resolved the issue by cloning the istio's source instead of downloading from command:
curl -L https://git.io/getLatestIstio | ISTIO_VERSION=1.1.6 sh -

**Comment by pitlv2109** [comment]
That flag should have been removed from helm files. Citadel doesn't accept --grpc-hostname anymore
