### ISSUE TITLE
Add resource lower bounds to sidecar proxy container

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1417]
@kyessenov commented on [Thu Apr 27 2017](https://github.com/istio/old_pilot_repo/issues/608)

Need to add lower bounds. Since the proxy agent is a go program that runs a bunch of watchers, we may need more RAM than k8s may choose to give to us.

---

@costinm commented on [Fri Apr 28 2017](https://github.com/istio/old_pilot_repo/issues/608#issuecomment-298048887)

I did a bit more research into this - I don't think we can hardcode a value, it needs to be a flag in istioctl
kube-apply, and we'll need some docs, it's tricky to get it right and depends a lot on the app type,  
expected traffic, node CPUs and available resources. 

If the cluster nodes have N CPU, there is some percent taken by daemons and other jobs.
The user may configure his job to fit - say 1500m - and needs to leave space for the sidecar. 

If total cpu reservations across daemons, user job and sidecar is > N, the job won't be scheduled.

As we run more loadtests we should get a better idea on how much CPU needs to be allocated based
on expected QPS and configuration.

---

@kyessenov commented on [Fri Apr 28 2017](https://github.com/istio/old_pilot_repo/issues/608#issuecomment-298061763)

we can start with over-provisioning resources and narrow it down. take a look at `kube-system` resources, e.g. heapster:
```
requests:
            cpu: 50m
            memory: 92560Ki
```
It's a lot easier to understand scheduling errors than from an under-provisioned system.

---

@costinm commented on [Fri Apr 28 2017](https://github.com/istio/old_pilot_repo/issues/608#issuecomment-298070178)

50m is 5% of cpu - you mean under-provision ? The default in GKE for a small cluster is 10%.

Scheduling errors are not so easy - the messages are quite cryptic, and figuring out how much
the daemons take is tricky. 

If we over-provision by default - we pretty much guarantee that users with small clusters will run
into problems and will have to override. Which in turn requires istioctl flags and a bit of math,
and it's a bit frustrating experience. The cluster may actually  have sensible defaults, the 
10% in a small cluster is ok for small loads.

---

@frankbu commented on [Wed Jun 14 2017](https://github.com/istio/old_pilot_repo/issues/608#issuecomment-308572561)

Another reason to do this is because without it horizontal pod autoscaling for istio-enabled services won't work. Hpa only works if ALL containers in the pods request cpu. Otherwise it just stays `<waiting>` foreever. I had to manually update the kube-injected proxy container to request cpu in the helloworld (autoscaling) sample: https://github.com/istio/istio/blob/master/samples/apps/helloworld/README.md. It's a pretty ugly workaround.

---

@cmluciano commented on [Wed Oct 18 2017](https://github.com/istio/old_pilot_repo/issues/608#issuecomment-337624096)

Has there been any progress on this? I'm guessing that we still may not have numbers that we are confident will span small/large clusters, but users are struggling with this when they use the Horizontal Pod Autoscaler (as mentioned above by @frankbu). 

---

@linsun commented on [Wed Oct 18 2017](https://github.com/istio/old_pilot_repo/issues/608#issuecomment-337626128)

Adding the production readiness label because auto scale of micro service app is a fairly common scenario, and this breaks auto scale without being able to get the metrics for the side car.  Some user actually hit this today, Error msg:

Kubectl describe hpa shows 
`Conditions:
  Type        Status    Reason            Message
  ----        ------    ------            -------
  AbleToScale    True    SucceededGetScale    the HPA controller was able to get the target’s current scale
  ScalingActive    False    FailedGetResourceMetric    the HPA was unable to compute the replica count: missing request for memory on container istio-proxy in pod default/bxdev1017-deployment-3936706214-cc74b

---

@linsun commented on [Wed Oct 18 2017](https://github.com/istio/old_pilot_repo/issues/608#issuecomment-337626904)

cc performance team for recommendation on request cpu/mem for side car @ldemailly @ayj @suryadu 

---

@gyliu513 commented on [Wed Oct 18 2017](https://github.com/istio/old_pilot_repo/issues/608#issuecomment-337627933)

With istio initializer, we now support customizing the `initImage`, `proxyImage` etc, perhaps we can also add the resource request as parameter in the configMap?

https://github.com/istio/pilot/blob/master/test/integration/testdata/initializer-configmap.yaml.tmpl

---

@andraxylia commented on [Wed Oct 18 2017](https://github.com/istio/old_pilot_repo/issues/608#issuecomment-337652819)

@cmluciano do you want to take this one?

---

@cmluciano commented on [Wed Oct 18 2017](https://github.com/istio/old_pilot_repo/issues/608#issuecomment-337682304)

@andraxylia Sure

**Comment by costinm** [comment]
https://github.com/istio/istio/issues/1914
