### ISSUE TITLE
e2e-mixer-no_auth-master test failure - fails to install redis

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#14179]
Example: https://prow.k8s.io/view/gcs/istio-prow/pr-logs/directory/e2e-mixer-no_auth-master/431

Error: error validating "": error validating data: field spec.volumeClaimTemplates[0].spec.dataSource for v1.PersistentVolumeClaimSpec is required
2019-05-16T20:05:04.523096Z	info	Command error: exit status 1
2019-05-16T20:05:04.523143Z	error	Failed to complete Init. Error helm install stable/redis failed, setValue=--set usePassword=false,persistence.enabled=false

If it is related to a change in redis we should pin the version we use.

https://testgrid.k8s.io/istio-postsubmits-master#e2e-mixer-no_auth
https://testgrid.k8s.io/istio-presubmits-master#e2e-mixer-no_auth

**Comment by yangminzhu** [comment]
It seems https://github.com/istio/istio/pull/14192 will fix this

**Comment by kyessenov** [comment]
Redis tests were removed from e2e-mixer in favor of integ-k8s-mixer tests.
