### ISSUE TITLE
Integration tests for Ingress Gateway SDS

### ISSUE THREAD

**Issue by JimmyCYJ** [istio/istio#14180]
Have Ingress Gateway SDS integration tests that cover the following test cases:
   - [ ] Secret rotations
   - [ ] Multiple Gateway instances
   - [ ] Invalid secrets, without secrets 
   - [ ] mTLS Gateways

**Comment by myidpt** [comment]
Part of https://github.com/istio/istio/issues/13439

**Comment by howardjohn** [comment]
@JimmyCYJ the PR is merged, is this done

**Comment by fpesce** [comment]
@JimmyCYJ I'm closing it because #14307 was merged, re-open if needed

**Comment by JimmyCYJ** [comment]
https://github.com/istio/istio/issues/13439
