### ISSUE TITLE
Add sidecar initializer option to customize injected sidecar per deployment

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1418]
@ayj commented on [Fri Aug 18 2017](https://github.com/istio/old_pilot_repo/issues/1061)

cc @costinm 

> It would be great to customize the sidecar tag (or full path) using annotations. For example to pick a debug image of sidecar for a job that needs debugging (ideally the full path of the sidecar should be specified ). Or a job may use a specialized sidecar. Or many other use cases

For example, customizing the injected sidecar image per deployment would look something like the following. The initializer would look for this annotation during injection and override the default sidecar image. The initializer may need additional policy to allow/disallow such customization to avoid undesirable proxy bypass.  

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    options.sidecar.istio.io/proxy_image: "docker.io/ayj/my_debug_proxy_image:e6ebaa8
  name: my-deployment 
# etc ... 
```

---

@costinm commented on [Fri Aug 18 2017](https://github.com/istio/old_pilot_repo/issues/1061#issuecomment-323410246)

Thanks, that would be perfect. Same for the initializer, and maybe the initializer options. 
As mentioned in a separate PR, I am evaluating using the sidecar image for initialization as well,
i.e. have both the iptables script and envoy.

Is this style of annotation names the standard ( a.b.c/d ) ? Maybe a bit shorter ?
  sidecar.istio.io/proxy_image, or istio.io/sidecar_image ? 

---

@ayj commented on [Fri Aug 18 2017](https://github.com/istio/old_pilot_repo/issues/1061#issuecomment-323420963)

https://github.com/istio/pilot/issues/1062 should address the initializer configuration. 

Which PR did you reference initialization? Were you thinking of using the same sidecar template for non-k8s VM deployments? 

This style seems somewhat consistent with k8s ingress annotations which are defined 
[here](https://github.com/kubernetes/ingress/blob/master/docs/annotations.md). `sidecar.istio.io/proxy_image` would work though I think the extra `options` category further clarified how that annotation was used, e.g. policy vs. status vs. options.

---

@saumoh commented on [Thu Aug 24 2017](https://github.com/istio/old_pilot_repo/issues/1061#issuecomment-324760974)

@costinm, which pr are you using for using the initializer for influencing the deployment/pod iptables configuration.
cc @vadimeisenbergibm @elevran 

---

@ayj commented on [Tue Aug 29 2017](https://github.com/istio/old_pilot_repo/issues/1061#issuecomment-325794845)

@saumoh was going to take a look at this issue, but I wasn't able to assign it to them. Is assignment restricted to org members?

---

@kyessenov commented on [Tue Aug 29 2017](https://github.com/istio/old_pilot_repo/issues/1061#issuecomment-325801836)

@geeknoid must be some administrative setting: we seem to unable to assign to non-org members

---

@geeknoid commented on [Tue Aug 29 2017](https://github.com/istio/old_pilot_repo/issues/1061#issuecomment-325827172)

I think you can only assign issues to team members, or people that have been explicitly added as collaborators.

---

@gyliu513 commented on [Thu Sep 07 2017](https://github.com/istio/old_pilot_repo/issues/1061#issuecomment-327725568)

I think that we are already able to customize the images for both init and proxy at here https://github.com/istio/pilot/blob/master/test/integration/testdata/initializer-configmap.yaml.tmpl#L13-L14 , can this one be closed?

---

@ayj commented on [Thu Sep 07 2017](https://github.com/istio/old_pilot_repo/issues/1061#issuecomment-327849187)

This issue is to allow per-deployment overrides whereas the Initializer ConfigMap applies globally.

---

@gyliu513 commented on [Thu Sep 07 2017](https://github.com/istio/old_pilot_repo/issues/1061#issuecomment-327999068)

@ayj Ah, I see, thanks, update the summary a bit to reflect the real case here.

**Comment by ayj** [comment]
This is now possible with the templated sidecar configuration. Specific customizable options can be added to end-users configuration or the official templates as needed.
