### ISSUE TITLE
Improve workload SDS fault injection / fuzzy test coverage

### ISSUE THREAD

**Issue by myidpt** [istio/istio#14187]
Currently we have several performance tests for Citadel SDS tests. They are not triggered for release qualification yet:
* https://github.com/istio/tools/tree/master/perf/security/sds-tests

We need to extend the existing release qualification tests to include the following test cases:
- [ ] After Citadel Agent crashes/disconnected, Envoy should still work (without the new certs)
- [ ] After Envoy crashes, it should be able to recover after restart
- [ ] If Citadel is crashes / is disconnected, Citadel Agent and Envoy should still work with existing key/cert.

**Comment by myidpt** [comment]
> Currently we have several performance tests for Citadel SDS tests. They are not triggered for release qualification yet:
> 
> * https://github.com/istio/tools/tree/master/perf/security/sds-tests
> 
> We need to extend the existing release qualification tests to include the following test cases:
> 
> * [ ]  After Citadel Agent crashes/disconnected, Envoy should still work (without the new certs)
> * [ ]  After Envoy crashes, it should be able to recover after restart
> * [ ]  If Citadel is crashes / is disconnected, Citadel Agent and Envoy should still work with existing key/cert.

**Comment by incfly** [comment]
> After Citadel Agent crashes/disconnected, Envoy should still work (without the new certs)
After Envoy crashes, it should be able to recover after restart

These sounds like testing against Envoy behavior. Not Istio components. Do we encounter similar problems before? If so, tests should go under envoyproxy/envoy?

**Comment by myidpt** [comment]
Yes, it could be under envoyproxy/envoy, or on Istio fuzzy tests. Either way is OK to me.
