### ISSUE TITLE
Master daily builds broken

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#14182]
https://gcsweb.istio.io/gcs/istio-prerelease/daily-build/master-latest-daily/

There has been no new releases for about a week

https://github.com/istio-releases/pipeline/pull/614

cc @fpesce we will need this to create a 1.2 release

**Comment by icygalz** [comment]
the failure happened because the release-bot are failing to update daily/* folder. This is PR trying to update the file:
https://github.com/istio-releases/pipeline/pull/622


It seems prow/release-istioctl-tests has been failing for a while for  master branch....

**Comment by howardjohn** [comment]
```
$ istio-master-20190516-09-15/bin/istioctl version --remote=false --short=false
version.BuildInfo{Version:"unknown", GitRevision:"unknown", User:"unknown", Host:"unknown", GolangVersion:"go1.10.4", DockerHub:"unknown", BuildStatus:"unknown", GitTag:"unknown"}
```

istioctl version command is broken

@esnible

**Comment by howardjohn** [comment]
Seems we broke this out to https://github.com/istio/pkg/, probably the root cause

**Comment by howardjohn** [comment]
https://github.com/istio/istio/blob/13cb3422ae47f95dfbc829a327724a56929cab3b/vendor/istio.io/pkg/version/version.go#L24-L34

```diff
diff --git a/bin/get_workspace_status.sh b/bin/get_workspace_status.sh
index 0fba368e7..c83181152 100755
--- a/bin/get_workspace_status.sh
+++ b/bin/get_workspace_status.sh
@@ -43,10 +43,10 @@ fi
 GIT_DESCRIBE_TAG=$(git describe)

 # used by bin/gobuild.sh
-echo "istio.io/istio/pkg/version.buildVersion=${VERSION}"
-echo "istio.io/istio/pkg/version.buildGitRevision=${BUILD_GIT_REVISION}"
-echo "istio.io/istio/pkg/version.buildUser=$(whoami)"
-echo "istio.io/istio/pkg/version.buildHost=$(hostname -f)"
-echo "istio.io/istio/pkg/version.buildDockerHub=${DOCKER_HUB}"
-echo "istio.io/istio/pkg/version.buildStatus=${tree_status}"
-echo "istio.io/istio/pkg/version.buildTag=${GIT_DESCRIBE_TAG}"
+echo "istio.io/pkg/version.buildVersion=${VERSION}"
+echo "istio.io/pkg/version.buildGitRevision=${BUILD_GIT_REVISION}"
+echo "istio.io/pkg/version.buildUser=$(whoami)"
+echo "istio.io/pkg/version.buildHost=$(hostname -f)"
+echo "istio.io/pkg/version.buildDockerHub=${DOCKER_HUB}"
+echo "istio.io/pkg/version.buildStatus=${tree_status}"
+echo "istio.io/pkg/version.buildTag=${GIT_DESCRIBE_TAG}"
```

Does not seem to fix it, not sure why though...

**Comment by howardjohn** [comment]
Nevermind, need to set `istio.io/istio/vendor/istio.io/pkg/version.buildUser=$(whoami)"`. Will send pr
