### ISSUE TITLE
Include root CA file for outgoing HTTPS requests

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1419]
@kyessenov commented on [Mon Apr 17 2017](https://github.com/istio/old_pilot_repo/issues/548)

Now that proxies can make HTTPS requests outside the cluster, we need to include a collection of root CAs for the root of trust. We can use the standard debian package and wire a reference to it to `envoy`.

---

@rshriram commented on [Tue Apr 18 2017](https://github.com/istio/old_pilot_repo/issues/548#issuecomment-294994192)

I suggest including the mozilla ca cert bundle that curl uses. https://curl.haxx.se/docs/caextract.html

---

@kyessenov commented on [Mon May 01 2017](https://github.com/istio/old_pilot_repo/issues/548#issuecomment-298449432)

This is in reference to egress proxy config as created here:
https://github.com/istio/manager/blob/master/proxy/envoy/egress.go#L104
and end-to-end test here:
https://github.com/istio/manager/blob/master/test/integration/egress.go

We will likely need root CA in the sidecar once we start making out-of-cluster requests from the proxy.

**Comment by djgilcrease** [comment]
Please do not forget the ability to add custom root CA's, eg internal company CAs for internal services.

Also better documentation about this would be good as it took me a few days to track down the cause of the error ```http: server gave HTTP response to HTTPS client``` I was getting from my go service when deployed to k8s with istio side car and talking to an external service

**Comment by zillani** [comment]
Hey @kyessenov I am unable to find this file, https://github.com/istio/manager/blob/master/proxy/envoy/egress.go

**Comment by tariq1890** [comment]
I am currently facing this problem: `http: server gave HTTP response to HTTPS client`

How do we fix this? We have set MTLS to PERMISSIVE and outboundTrafficPolicy has been defaulted to `ALLOW_ANY`.
