### ISSUE TITLE
Use adsc client to test against citadel agent

### ISSUE THREAD

**Issue by incfly** [istio/istio#14199]
Citadel agent is a SDS server. We can have integration test covered with fake envoy.

We already have an fake client implementation, under `pkg/adsc/`. This is used to  for some light weight testing against Pilot. We should reuse it for citadel agent as well.

This way we can easily simulate tons of clients with very minimal resources against citadel agent.

https://github.com/istio/istio/blob/master/pkg/adsc/adsc.go

This adsc client is going to be used in two type of tests.
1. Integration test in a native environment
1. Perf test/release quialification test in k8s environment

**Comment by incfly** [comment]
@mandarjog @wattli @JimmyCYJ thoughts?

**Comment by JimmyCYJ** [comment]
I like this idea. Citadel agent is a SDS proxy and we need some test framework to test Citadel agent from networking perspective.

**Comment by JimmyCYJ** [comment]
Edited the issue description per discussion with @incfly.

**Comment by myidpt** [comment]
Just curious, can you explain why it's not used for integration tests in K8s environment?

**Comment by incfly** [comment]
we definitely can add this to k8s environment as well. but i think @lei-tang already have an e2e integration test for the sds.

**Comment by JimmyCYJ** [comment]
blocked by https://github.com/istio/istio/issues/9177

**Comment by myidpt** [comment]
This is very useful for testing the Citadel / Istio agent. I think we can have it implemented for perf / release tests first.
