### ISSUE TITLE
Integration tests for mTLS authentication 

### ISSUE THREAD

**Issue by diemtvu** [istio/istio#14195]
- [x] Migrate (reach-ability) tests from e2e framework to new integration framework.

- [ ] Add tests for mTLS for HTTPS backend. 

- [ ] Adding test case permutations of control and data plane secure mode (e.g insecure control + global mTLS policies/DR).

**Comment by pitlv2109** [comment]
@diemtvu  Should we set this (and other authentication integration test issues) to P0 for visibility?
