### ISSUE TITLE
e2e-simpleTests fails due to nodePort conflict

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#14190]
Error: release istio failed: Service "istio-ingressgateway" is invalid: spec.ports[1].nodePort: Invalid value: 31380: provided port is already allocated

https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/13948/e2e-simpleTests-master/469

**Comment by ozevren** [comment]
I've seen this type of failure in other tests as well. To me, it feels like an issue with the current installer.
@costinm, @sdake is this a known issue? Could this be from the installation scripts and/or the test environment?

**Comment by mandarjog** [comment]
@sushicw ingress gateway defines a NodePort. It seems that there is another test from a suite that creates the same gateway. It could be related to the re-use of cluster thru boskos.

The solution is no disable use of NodePort for tests. I would first verify that NodePort is not required for any of these tests.

**Comment by sushicw** [comment]
Removing the static nodePort definitions from values.yaml seems to not break any tests: https://github.com/istio/istio/pull/15042

After asking around a bit, I haven't heard any reason why we shouldn't go ahead and remove the static nodeports from the helm config. If anyone has further thoughts, please add them here or on the above PR.

**Comment by sushicw** [comment]
Closed #15042 in favor of https://github.com/istio/istio/pull/15596

**Comment by sushicw** [comment]
This should hopefully be fixed going forward.
