### ISSUE TITLE
Intergartions tests for authentication policies

### ISSUE THREAD

**Issue by diemtvu** [istio/istio#14197]
- [ ] Verify the policies are distributed correctly, to the expected workloads.

- [ ] Verify the interaction behaviors with other APIs (e.g gateways, sidecar, VS)

- [ ] Combine with DRs, verify connection can be made

Note: some of these are overlapping with https://github.com/istio/istio/issues/14195

**Comment by incfly** [comment]
This can be closed I believe? @diemtvu
