### ISSUE TITLE
BookInfo GATEWAY_URL resulting in connection refused

### ISSUE THREAD

**Issue by objectiser** [istio/istio#142]
Commit: d75c67b81f7b8014b67ab54f50f5b44d7c3e7675
Fedora 23

Followed the https://istio.io/docs/samples/bookinfo.html instructions, only skipping the 'apply addons' step.

> NAME                                        READY     STATUS    RESTARTS   AGE
details-v1-3876634233-n3wx6                 2/2       Running   0          27m
istio-ca-2343704264-3j184                   1/1       Running   0          31m
istio-ingress-controller-1227707491-6g33q   1/1       Running   0          31m
istio-manager-3903014443-psq3f              1/1       Running   0          31m
istio-mixer-2291004578-n7blt                1/1       Running   0          31m
productpage-v1-1048626081-fg644             2/2       Running   0          27m
ratings-v1-4140089007-9nmlb                 2/2       Running   0          27m
reviews-v1-743947990-24s48                  2/2       Running   0          27m
reviews-v2-1273544408-0jms0                 2/2       Running   0          27m
reviews-v3-1803140826-xn8hl                 2/2       Running   0          27m

All pods seem to be running ok, but when obtaining the ENDPOINT_URL I got connection refused in a browser and also using curl.

**Comment by objectiser** [comment]
After doing `minikube delete` and running through the steps again, I now get:

> INTERNAL:configuration is not yet available

after the pods have been running over 20 minutes. Any suggestions on how to investigate?

**Comment by AnthonyAmanse** [comment]
Got the `INTERNAL:configuration is not yet available` as well. What I did was edit the `/kubernetes/istio-install/istio-ingress-controller.yaml` located in . I changed the type from **LoadBalancer to NodePort** and added **nodePort** on the controller service.
```yaml
apiVersion: v1
kind: Service
metadata:
  name: istio-ingress-controller
  labels:
    infra: istio-ingress-controller
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 32000
```
I did that before doing `kubectl apply -f ./kubernetes/istio-install`

**Comment by objectiser** [comment]
Thanks, although this seems to be fixed in the most recent version. It was possibly related to https://github.com/istio/istio/pull/147
