### ISSUE TITLE
livenessProbe and ReadnessProbe not in pair

### ISSUE THREAD

**Issue by mailzyok** [istio/istio#14202]
Hi,

The livenessProbe and ReadnessProble are not paired in the latest Istio helm chart:

1. livenessProbe is not implemented for pilot discovery containers
2. livenessProbe is not implemented for istio-proxy containers.
3. ReadnessProbe is not implemented for citadel container.

Is there any specific reason that these missing probe should not be implemented? Can we add the missing probe by using the same command? For example, using the command by readnessProbe for the livenessProbe but using a different initialDelaySeconds.

Thanks,

**Comment by howardjohn** [comment]
> livenessProbe is not implemented for pilot discovery containers
> livenessProbe is not implemented for istio-proxy containers.
> ReadnessProbe is not implemented for citadel container.

Is there any reason you think these are needed?

**Comment by mailzyok** [comment]
@howardjohn sorry for late response. I am just back from vacation.

in my view, for containers that require liveliness supervision, a liveness probe must be specified. If there is no livenessProbe for pilot discovery and istio-proxy, if something wrong happened for these containers, how can they recover from it automatically?

For citadel container, there is a service exposed accordingly, which means it will receive traffic from other services, so readnessProbe can help to make sure the traffic can be handled when the probe succeeds.

Thanks.

**Comment by humboldt-xie** [comment]
the envoy would get a warning:

```
[2019-08-01 12:31:11.820][25][warning][upstream] external/envoy/source/common/config/grpc_mux_impl.cc:240] gRPC config stream closed: 14, no healthy upstream
[2019-08-01 12:31:11.820][25][warning][upstream] external/envoy/source/common/config/grpc_mux_impl.cc:41] Unable to establish new stream
```

The reason is that the pilot(istio-pilot.istio-system:15007) cannot be connected

restart pilot recovery

Maybe we need livenessProbe

**Comment by JohnWillker** [comment]
There's a good reason for livenessProbe is not implemented for istio-proxy containers?
I think is a good practice have both, readiness and liveness: 
- https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
- https://cloud.google.com/blog/products/gcp/kubernetes-best-practices-setting-up-health-checks-with-readiness-and-liveness-probes

**Comment by kppullin** [comment]
FWIW, I ran across an issue today in our dev cluster due to the lack of a livenessProbe in `istiod`.

`istiod` was running on a flaky, failing node and became non-responsive.  This in turn caused all calls to the injector webhook to fail and block pods from rolling out (in this case failures are visbile at the `replicaset` level).

I expected that `istiod`'s livenessprobe would fail to trigger it to move elsewhere and eventually discovered the lack thereof, which lead me here.
