### ISSUE TITLE
DELTA_ENCODING does not support attribute reference tracking

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#14211]
Found during code inspection:
https://github.com/istio/istio/blob/8c3ad44d3c67a941fbe02b045343568fb268cf4b/mixer/pkg/attribute/protoBag.go#L671

Note that the released string map does not have a parent bag owner, meaning its de-references are not tracked. Reference tracking is critical for policy tracking. Since we don't use delta encoding for policy checks, I think this is safe, but something we should be aware of.

/cc @mandarjog 
/cc @geeknoid

**Comment by douglas-reid** [comment]
@kyessenov i think, given the state of Mixer, that is safe to say that this issue will not be resolved. I'm going to close it (status: WON'T FIX).

Please re-open if you feel this should require attention.
