### ISSUE TITLE
[Feature request] A script or subcommand in istioctl to validate k8s clusters to see if it's compliant and ready for installation

### ISSUE THREAD

**Issue by darwin67** [istio/istio#14223]
**Describe the feature request**

Linkerd has a subcommand that will validate the kubernetes cluster to see if it's ready to install the control plane.
https://linkerd.io/2/getting-started/#step-2-validate-your-kubernetes-cluster

```
❯ linkerd check --pre
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

pre-kubernetes-setup
--------------------
√ control plane namespace does not already exist
√ can create Namespaces
√ can create ClusterRoles
√ can create ClusterRoleBindings
√ can create CustomResourceDefinitions
√ can create ServiceAccounts
√ can create Services
√ can create Deployments
√ can create ConfigMaps

pre-kubernetes-capability
-------------------------
√ has NET_ADMIN capability

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

Status check results are √
```

I think this can be pretty useful since Istio is pretty complicated and it can be hard to tell what you get wrong with so many moving parts, both Istio itself and the kubernetes cluster setup that it will be running on.

**Describe alternatives you've considered**

Nothing I can think of at the moment unless switching to Linkerd.

**Additional context**

I've been hitting issues every once in a while that it's unclear what is wrong (is it my setup or is it Istio), and there seems to be a lot of issues being closed because maintainers cannot identify the scope of the problem.

Having a tool like this could at least help narrow down the scope of issues which I think could save a lot of back and forth at the information sharing phase, especially for people who really can't share much information about their environment.

I think this can also be helpful for validating clusters before upgrades since the current procedure is just try it out and pray that it doesn't break..., which almost never happens...

**Comment by esnible** [comment]
@irisdingbj Make sure your new commands can be used for this scenario.

**Comment by irisdingbj** [comment]
@darwin67 we have the similar command in master branch which do the pre-check and let you know whether your k8s cluster is ready for a new istio installation:
```
./istioctl verify-install -i test

Checking the cluster to make sure it is ready for Istio installation...

Kubernetes-api
-----------------------
Can initialize the Kubernetes client.
Can query the Kubernetes API Server.

Kubernetes-version
-----------------------
Istio is compatible with Kubernetes: v1.13.5.

Istio-existence
-----------------------
Istio will be installed in the test namespace.

Kubernetes-setup
-----------------------
Can create necessary Kubernetes configurations: Namespace,ClusterRole,ClusterRoleBinding,CustomResourceDefinition,Role,ServiceAccount,Service,Deployments,ConfigMap. 

SideCar-Injector
-----------------------
Istio Configured to use automatic sidecar injection for 'default' namespace. To enable injection for other namespaces see https://istio.io/docs/setup/kubernetes/additional-setup/sidecar-injection/#deploying-an-app

-----------------------
Install Pre-Check passed! The cluster is ready for Istio installation.
```

Please try this and comment back if you need any more things for this.

**Comment by darwin67** [comment]
i would love to but this repo isn't trivial to build...
```
❯ make
Not building in expected path 'GOPATH/src/istio.io/istio'. Make sure to clone Istio into that path. Istio root=/home/darwin67/workspace/istio, GO_TOP=/home/darwin67/go/1.12.5
Makefile:237: recipe for target 'check-tree' failed
make: *** [check-tree] Error 1
```

**Comment by esnible** [comment]
@darwin67 Like many Go projects Istio needs to be in the GOPATH.  It does an extra check to make sure it didn't get there by symlink.

There are daily builds at https://gcsweb.istio.io/gcs/istio-prerelease/daily-build/release-1.2-latest-daily/ and you only need to get the version for your OS and untar/unzip to get _istioctl_.

**Comment by darwin67** [comment]
@irisdingbj @esnible Hi, just tried the `verify-install` command on a clean cluster and I think it looks good!

```
❯ ./istioctl verify-install

Checking the cluster to make sure it is ready for Istio installation...

Kubernetes-api
-----------------------
Can initialize the Kubernetes client.
Can query the Kubernetes API Server.

Kubernetes-version
-----------------------
Istio is compatible with Kubernetes: v1.14.1.

Istio-existence
-----------------------
Istio will be installed in the istio-system namespace.

Kubernetes-setup
-----------------------
Can create necessary Kubernetes configurations: Namespace,ClusterRole,ClusterRoleBinding,CustomResourceDefinition,Role,ServiceAccount,Service,Deployments,ConfigMap.

SideCar-Injector
-----------------------
Istio Configured to use automatic sidecar injection for 'default' namespace. To enable injection for other namespaces see https://istio.io/docs/setup/kubernetes/additional-setup/sidecar-injection/#deploying-an-app

-----------------------
Install Pre-Check passed! The cluster is ready for Istio installation.
```

It'll be great if there's a `verify-upgrade` command as well, but I do understand that can be tricky to implement especially how different 1.0 and 1.1 is.
I do think this is a good start.

**Comment by darwin67** [comment]
Oops, forgot to close.
