### ISSUE TITLE
envoy_bootstrap_drain malformed IP address

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#14231]
Running from master.

```
error initializing configuration '/var/lib/istio/envoy/envoy_bootstrap_drain.json': malformed IP address: {{ .localhost }}
```

Reproduce by killing a pod.

I don't think this one is templated.

**Comment by sbezverk** [comment]
@howardjohn I will take care of it on my return from kubecon, unless somebody else does it earlier.

**Comment by howardjohn** [comment]
@sbezverk this is a release blocker so I'll do it
