### ISSUE TITLE
pilot is listening on ipv4 for istioctl in ipv6  k8s cluster

### ISSUE THREAD

**Issue by tibetsam** [istio/istio#14236]
(This is used to report product bugs, please visit <https://discuss.istio.io> for questions on using Istio)

**Bug description**
root@mastermint:~/go/src/istio.io# kb exec -nistio-system istio-pilot-6dd595fdd5-4v499 -c discovery -- lsof -i | grep IPv4
pilot-dis   1 root   12u  IPv4   45865      0t0  TCP localhost:9876 (LISTEN)

**Expected behavior**
All ports should be listening on ipv6 in pure ipv6 k8s cluster

**Steps to reproduce the bug**
install k8s
install istio

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
root@mastermint:~/go/src/istio.io# istioctl version
client version: unknown
citadel version: master-20190510-09-16
galley version: master-20190510-09-16
ingressgateway version: master-20190510-09-16
pilot version: master-20190510-09-16
policy version: master-20190510-09-16
sidecar-injector version: master-20190510-09-16
telemetry version: master-20190510-09-16
root@mastermint:~/go/src/istio.io# kb version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
helm install
**Environment where bug was observed (cloud vendor, OS, etc)**
Linux mastermint 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
I don't think we fully support ipv6 yet, but I could be wrong. @sbezverk is working on this feature so maybe he can provide some help here

**Comment by sbezverk** [comment]
It has been fixed in master. Please confirm which istio version is being used.

**Comment by howardjohn** [comment]
@tibetsam without more info I am going to assume this is due to using a version that doesn't support ipv6 yet, as the feature is very new. If this is not the case please another issue so we can investigate further. Thanks!

**Comment by tibetsam** [comment]
sure. thanks. I'm following another track on this issue. --->Change dnsRefreshRate from flag to env var (#14176)
