### ISSUE TITLE
Bookinfo samples image not fully qualified

### ISSUE THREAD

**Issue by kramvan1** [istio/istio#14237]
To be consistent and to remove any ambiguity for the images pulls, the bookinfo yaml `image:` fields should be fully qualified.
```
image: istio/examples-bookinfo-ratings-v1:1.12.0 
```
```
image: docker.io/istio/examples-bookinfo-ratings-v1:1.12.0
```

**Comment by kramvan1** [comment]
cc @linsun @rvennam

**Comment by kramvan1** [comment]
I also noticed this one: `image: "grafana/grafana:6.0.2"`

**Comment by ibm-jason** [comment]
@kramvan1 where did you see `image: "grafana/grafana:6.0.2"`?

**Comment by kramvan1** [comment]
@ibm-jason This is where that is defined: https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/grafana/values.yaml#L7-L8  Need to get that fully qualified.

**Comment by linsun** [comment]
Is this ambiguity causing any issue for you?  @kramvan1

**Comment by kramvan1** [comment]
@linsun yes, currently since we are "processing" the yaml output from helm template, the tools assume a fully qualified image name.    It means easier automation when fully qualified, else I have to go thru all the yaml looking for image refs and convert them.

**Comment by ibm-jason** [comment]
### Status Update

I had a brief conversation yesterday with @linsun, who asked that we determine the tangible benefit of implementing the "fix" for this issue. Later, I spoke with @kramvan1 asked him what the benefit is and he stated the following:

> Sure, the main reason is automation.   I’m using the `helm template` to produce the yaml.   I need to change the image registries to point to the IBM internal ones, if they are not fully qualified, this will not work.   I can take the time to add parsing to my automation to try to find all the image regs and change them, but that is a pain.

> If they are fully qualified, it’s at least consistent with the current base stuff.
So for now, I just need them fully qualified like `docker.io/istio/examples-bookinfo-ratings-v1:1.12.0` and it’s good.

The PR that I've prepped for this issue #14312 updates all of the bookinfo sample charts to use the fully qualified image names for each docker image. At this point, I think we can leave this issue/PR in the hands of the maintainers to decide whether it is worth merging in.

/cc @howardjohn
