### ISSUE TITLE
istioctl validate no longer reports a message if a file is valid

### ISSUE THREAD

**Issue by esnible** [istio/istio#14238]
Commit https://github.com/istio/istio/commit/995276a3da1d7f54f6881f987c58ba322366ab5a#diff-baef65426d2d2b26ba35559728c3e783 removed the `"is valid"` output when `istioctl validate` is run on a valid file.

**Comment by kyessenov** [comment]
Can you removing "Validating ..." if you are going to bring back "is valid"? It's not worth having the two proclamations.
