### ISSUE TITLE
Introduce a protoc plugin to generate OpenAPI spec.

### ISSUE THREAD

**Issue by geeknoid** [istio/istio#14246]
Istio keeps its API definitions in proto format. We would like to turn those into OpenAPI for better integration into the overall ecosystem. In particular, we can use OpenAPI specs as part of our CRD definitions in order to have the API server perform validation for us.

**Comment by jasonwzm** [comment]
This is done in https://github.com/istio/tools/tree/master/protoc-gen-openapi, openapi spec will be generated in https://github.com/istio/api/pull/957. Closing this.
