### ISSUE TITLE
Task 'Provisioning Identity through SDS' does not work with 1.1.7

### ISSUE THREAD

**Issue by c0d1ngm0nk3y** [istio/istio#14244]
**Bug description**
Running the following command as [documented](https://istio.io/docs/tasks/security/auth-sds/)
```bash
kubectl create -f istio-auth-sds.yaml
```
results in the following error messages:
```bash
unable to recognize "istio-auth-sds.yaml": no matches for kind "attributemanifest" in version "config.istio.io/v1alpha2"
unable to recognize "istio-auth-sds.yaml": no matches for kind "attributemanifest" in version "config.istio.io/v1alpha2"
unable to recognize "istio-auth-sds.yaml": no matches for kind "metric" in version 
[...]
unable to recognize "istio-auth-sds.yaml": no matches for kind "DestinationRule" in version "networking.istio.io/v1alpha3"
unable to recognize "istio-auth-sds.yaml": no matches for kind "DestinationRule" in version "networking.istio.io/v1alpha3"
```
This happens with istio @ tag 1.1.7, but not when using 1.1.6.

**Expected behavior**
Demo works...

**Steps to reproduce the bug**
See https://istio.io/docs/tasks/security/auth-sds/

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
istio @ tag 1.1.7
```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T18:55:03Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:45:25Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```
**How was Istio installed?**
See https://istio.io/docs/tasks/security/auth-sds/

**Environment where bug was observed (cloud vendor, OS, etc)**
Gardener Cluster on GCP.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[X] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience

**Comment by howardjohn** [comment]
Sounds like the CRDs did not get installed?

Did you follow https://istio.io/docs/tasks/security/auth-sds/#before-you-begin? Specifically `cat install/kubernetes/helm/istio-init/files/crd-* >> istio-auth-sds.yaml`

**Comment by c0d1ngm0nk3y** [comment]
Yes, that is actually the step where the error occurred, when executing `kubectl create -f istio-auth-sds.yaml`.

The exact same steps work when switching to tag 1.1.6. Could it be a timing issue?

We haven't investigated further because 1.1.6 is OK for us. But I think it should work just as smooth as with 1.1.6, right?

**Comment by yangminzhu** [comment]
This is actually not about the security, but more about the config.

**Comment by c0d1ngm0nk3y** [comment]
@yangminzhu So far, we have only seen it with this task, but we are currently looking into SDS, so we did not check other tasks. I also think it is about the config.

**Comment by howardjohn** [comment]
Docs fixed https://istio.io/docs/tasks/security/auth-sds/#before-you-begin
