### ISSUE TITLE
Istio demo helm chart and jaeger integration/embedded mode in Kiali

### ISSUE THREAD

**Issue by emptywee** [istio/istio#14248]
**Bug description**

When Istio 1.1.6 is installed from Helm charts (istio-demo) with tracing enabled, it appears that istio-tracing deployment specs and service is created with incorrect data.

Kiali is expecting jaeger query service to be at http://jaeger-query and it tries to read services available from http://jaeger-query/api/services

```
kiali-68677d47d7-wp4kl kiali E0520 17:40:04.576232       1 kiali.go:106] Jaeger is not available : Get http://jaeger-query/api/services: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

At the same time istio-tracing pod is created with `QUERY_BASE_PATH:             /jaeger` and service port at 16686. Kiali just times out trying it at port 80. I could not find any parameters that we could give to Kiali to use different port and prefix to access Jaeger.

Logs when QUERY_BASE_PATH is still set to `/jaeger`:
```
kiali-68677d47d7-5t7fd kiali E0520 17:48:59.321554       1 jaeger_helper.go:104] Error Unmarshal Jaeger Response fetching Services: %!s(<nil>)
kiali-68677d47d7-5t7fd kiali E0520 17:48:59.321572       1 kiali.go:106] Jaeger is not available : invalid character '<' looking for beginning of value
```

After changing QUERY_BASE_PATH to empty string and updating jaeger-query service to listen on port 80, I got tracing working properly in Kiali's console. No complaints in the logs from Kiali anymore and the UI looks good.

**Expected behavior**

Tracing to be working in Kiali when deployed using Helm charts.

**Steps to reproduce the bug**

Install Istio 1.1.6 from the istio-demo.yaml chart using Helm with tracing enabled. Go to Kiali's console and you won't find tracing working. Unless I did something wrong, but I did not touch much regarding the tracing. Just found out it wasn't working and had to make corrections to make it work. Decided to report it with as much details as possible.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```
$ bin/istioctl version --remote
client version: version.BuildInfo{Version:"1.1.6", GitRevision:"04850e14d38a69a38c16c800e237b1108056513e", User:"root", Host:"1844d064-72cc-11e9-a0d5-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.5-11-g04850e1"}
citadel version: version.BuildInfo{Version:"1.1.6", GitRevision:"04850e14d38a69a38c16c800e237b1108056513e-dirty", User:"root", Host:"1844d064-72cc-11e9-a0d5-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.5-11-g04850e1"}
citadel version: version.BuildInfo{Version:"1.1.6", GitRevision:"04850e14d38a69a38c16c800e237b1108056513e-dirty", User:"root", Host:"1844d064-72cc-11e9-a0d5-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.5-11-g04850e1"}
egressgateway version: version.BuildInfo{Version:"1.1.6", GitRevision:"04850e14d38a69a38c16c800e237b1108056513e", User:"root", Host:"1844d064-72cc-11e9-a0d5-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.5-11-g04850e1"}
galley version: version.BuildInfo{Version:"1.1.6", GitRevision:"04850e14d38a69a38c16c800e237b1108056513e-dirty", User:"root", Host:"1844d064-72cc-11e9-a0d5-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.5-11-g04850e1"}
ingressgateway version: version.BuildInfo{Version:"1.1.6", GitRevision:"04850e14d38a69a38c16c800e237b1108056513e", User:"root", Host:"1844d064-72cc-11e9-a0d5-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.5-11-g04850e1"}
ingressgateway version: version.BuildInfo{Version:"1.1.6", GitRevision:"04850e14d38a69a38c16c800e237b1108056513e", User:"root", Host:"1844d064-72cc-11e9-a0d5-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.5-11-g04850e1"}
pilot version: version.BuildInfo{Version:"1.1.6", GitRevision:"04850e14d38a69a38c16c800e237b1108056513e-dirty", User:"root", Host:"1844d064-72cc-11e9-a0d5-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.5-11-g04850e1"}
pilot version: version.BuildInfo{Version:"1.1.6", GitRevision:"04850e14d38a69a38c16c800e237b1108056513e-dirty", User:"root", Host:"1844d064-72cc-11e9-a0d5-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.5-11-g04850e1"}
policy version: version.BuildInfo{Version:"1.1.6", GitRevision:"04850e14d38a69a38c16c800e237b1108056513e-dirty", User:"root", Host:"1844d064-72cc-11e9-a0d5-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.5-11-g04850e1"}
policy version: version.BuildInfo{Version:"1.1.6", GitRevision:"04850e14d38a69a38c16c800e237b1108056513e-dirty", User:"root", Host:"1844d064-72cc-11e9-a0d5-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.5-11-g04850e1"}
sidecar-injector version: version.BuildInfo{Version:"1.1.6", GitRevision:"04850e14d38a69a38c16c800e237b1108056513e-dirty", User:"root", Host:"1844d064-72cc-11e9-a0d5-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.5-11-g04850e1"}
telemetry version: version.BuildInfo{Version:"1.1.6", GitRevision:"04850e14d38a69a38c16c800e237b1108056513e-dirty", User:"root", Host:"1844d064-72cc-11e9-a0d5-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.5-11-g04850e1"}
telemetry version: version.BuildInfo{Version:"1.1.6", GitRevision:"04850e14d38a69a38c16c800e237b1108056513e-dirty", User:"root", Host:"1844d064-72cc-11e9-a0d5-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.5-11-g04850e1"}
```
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-eks-d69f1b", GitCommit:"d69f1bf3669bf00b7f4a758e978e0e7a1e3a68f7", GitTreeState:"clean", BuildDate:"2019-02-28T20:26:10Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

Heml chart istio-demo.yaml.

**Environment where bug was observed (cloud vendor, OS, etc)**

AWS EKS.

**Affected product area (please put an X in all that apply)**

Not really sure here...

[X] Configuration Infrastructure
[X] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

**Comment by douglas-reid** [comment]
This strikes me as an issue with Kiali install.  @jmazzitelli any thoughts here?

**Comment by jmazzitelli** [comment]
I can tell you the latest Kiali supports these settings as seen here: https://github.com/kiali/kiali/blob/master/operator/deploy/kiali/kiali_cr.yaml#L192-L202

```
external_services:
    tracing:
      namespace: ""
      service : ""
      url: ""
```

You can modify these in the kiali configmap directly if you have not installed kiali via the operator (i.e. if you installed via the helm charts).

These are valid for the latest kiali versions - I do not think these work with the version that is included in Istio 1.1.x. But I think the setting that is needed is available - the jaeger.url setting: https://github.com/istio/istio/blob/release-1.1/install/kubernetes/helm/istio/charts/kiali/templates/configmap.yaml#L20

So, perhaps we should set kiali.jaegerURL helm chart value to the one that is the Istio default (based on this issue's description, sounds like that might be: `http://jaeger-query:16686/jaeger/api/services` ??).

**Comment by emptywee** [comment]
@jmazzitelli I have those set, but they are not used by kiali for some reason. They are used when I share a link to a trace in the UI. I made externally available dns entries on the load balancer, verified them working, and fed them to Kiali in the configmap, still it appears to be using http://jaeger-query instead.

(note: redacted 2nd level domain)
```
$ kubectl -n istio-system get configmap kiali -o yaml
apiVersion: v1
data:
  config.yaml: |
    istio_namespace: istio-system
    server:
      port: 20001
    external_services:
      istio:
        url_service_version: http://istio-pilot:8080/version
      jaeger:
        url: https://orq-jaeger.example.com
      grafana:
        url: https://orq-grafana.example.com
kind: ConfigMap
metadata:
  creationTimestamp: "2019-05-16T17:51:49Z"
  labels:
    app: kiali
    chart: kiali
    heritage: Tiller
    release: istio
  name: kiali
  namespace: istio-system
  resourceVersion: "44645228"
  selfLink: /api/v1/namespaces/istio-system/configmaps/kiali
  uid: 47e6c40d-7803-11e9-9497-0224bfec908a
```

I am not a Go developer, so not really sure how you can override this constant: https://github.com/kiali/kiali/blob/master/config/config.go#L235

All I found is that line and then it uses it here: https://github.com/kiali/kiali/blob/master/status/discover.go#L98

**Comment by emptywee** [comment]
Oh it seems like a fallback value when `tracing` is not set under `external_services`: https://github.com/kiali/kiali/blob/master/status/discover.go#L117

Which helm charts don't set, at least for me.

**Comment by emptywee** [comment]
And also Helm charts didn't set `QUERY_BASE_PATH` for the kiali deployment, as it seems to be supporting it: https://github.com/kiali/kiali/blob/master/status/discover.go#L74

It sets it here: ./install/kubernetes/helm/istio/charts/tracing/templates/deployment-jaeger.yaml only, but not for Kiali. I'll experiment more with all this.

**Comment by emptywee** [comment]
So Istio 1.1.6 comes with Kiali v0.16, so it wasn't appropriate to refer to the master branch as it has different config and other stuff. My bad.

**Comment by jmazzitelli** [comment]
OK, those links to the kiali code are to master - that's the latest version I was talking about. This is not the code you are running - you installed from the helm charts, which means you are running kiali v0.16 and that's this:

https://github.com/kiali/kiali/blob/v0.16/config/config.go#L248

Notice there is this "service" configmap setting: https://github.com/kiali/kiali/blob/v0.16/config/config.go#L128-L130

So it looks like v0.16 supports these in the configmap:

```
external_services:
  jaeger:
    url: <your URL here>
   service: <your service name here>
```

But I think what you are hitting has been fixed already - see https://github.com/kiali/kiali/pull/1082
Edgar did the work, not I - he would know more.  If this still doesn't help, either (1) submit an issue on kiali github at https://github.com/kiali/kiali or (2) go on IRC in #kiali (freenode) or (3) send a message to kiali-users googlegroups at https://groups.google.com/forum/#!forum/kiali-users and we can discuss with the entire kiali team.

**Comment by emptywee** [comment]
Yep, I am glad this has been fixed :) Thanks!

**Comment by douglas-reid** [comment]
@emptywee  @jmazzitelli  should we close this issue then?

**Comment by emptywee** [comment]
Yeah, I'll close it. Thanks.
