### ISSUE TITLE
Can not create sidecar using istioctl

### ISSUE THREAD

**Issue by kc004** [istio/istio#14241]
(This is used to report product bugs, please visit <https://discuss.istio.io> for questions on using Istio)

**Bug description**
I have installed istio and download latest istio using `curl -L https://git.io/getLatestIstio | sh -`
script and move that latest istio to istio-latest folder. After doing these step when i test using sleep deployment which is provided in istio site it fails.

**Expected behavior**
It should be inject and create sidecar to deployment.

```
istio# istioctl kube-inject -f samples/sleep/sleep.yaml | kubectl apply -f -
Error: error converting YAML to JSON: yaml: line 3: could not find expected ':'
serviceaccount/sleep created
service/sleep created
error: error parsing STDIN: error converting YAML to JSON: yaml: mapping values are not allowed in this context
```
**Steps to reproduce the bug**
1. Install istio using helm.
2. Download latest istio and move it to istio-latest
3. After that execute command: istioctl kube-inject -f samples/sleep/sleep.yaml | kubectl apply -f -
**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```
client version: version.BuildInfo{Version:"1.1.7", GitRevision:"eec7a74473deee98cad0a996f41a32a47dd453c2", User:"root", Host:"341b3bf0-76ac-11e9-b644-0a580a2c0404", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.6-6-geec7a74"}
citadel version: version.BuildInfo{Version:"master-20190520-09-15", GitRevision:"3a243984020e891deb3c694af896a315ff26405f-dirty", User:"root", Host:"e9c5153b-7adf-11e9-b644-0a580a2c0404", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.6-853-g3a24398"}
galley version: version.BuildInfo{Version:"master-20190520-09-15", GitRevision:"3a243984020e891deb3c694af896a315ff26405f-dirty", User:"root", Host:"e9c5153b-7adf-11e9-b644-0a580a2c0404", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.6-853-g3a24398"}
ingressgateway version: version.BuildInfo{Version:"master-20190520-09-15", GitRevision:"3a243984020e891deb3c694af896a315ff26405f", User:"root", Host:"e9c5153b-7adf-11e9-b644-0a580a2c0404", GolangVersion:"go1.10.4", DockerHub:"gcr.io/istio-release", BuildStatus:"Clean", GitTag:"1.1.6-853-g3a24398"}
pilot version: version.BuildInfo{Version:"master-20190520-09-15", GitRevision:"3a243984020e891deb3c694af896a315ff26405f-dirty", User:"root", Host:"e9c5153b-7adf-11e9-b644-0a580a2c0404", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.6-853-g3a24398"}
policy version: version.BuildInfo{Version:"master-20190520-09-15", GitRevision:"3a243984020e891deb3c694af896a315ff26405f-dirty", User:"root", Host:"e9c5153b-7adf-11e9-b644-0a580a2c0404", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.6-853-g3a24398"}
telemetry version: version.BuildInfo{Version:"master-20190520-09-15", GitRevision:"3a243984020e891deb3c694af896a315ff26405f-dirty", User:"root", Host:"e9c5153b-7adf-11e9-b644-0a580a2c0404", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.6-853-g3a24398"}
```
**How was Istio installed?**
HELM
**Environment where bug was observed (cloud vendor, OS, etc)**
Baremetal
**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
You are using `istioctl` 1.1.7 with images from master. If you want to run Istio 1.1.x, please follow the instructions from https://istio.io/docs/setup/kubernetes/quick-start/ and do not install from our Github source.

If you did mean to install from our github source, then please make sure you use the istioctl from source as well. Not this is not supported at all though and is meant for development only.
