### ISSUE TITLE
Ingress controller: SNI support

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1424]
@zcahana commented on [Sun Apr 09 2017](https://github.com/istio/old_pilot_repo/issues/484)

[Ingress spec](https://kubernetes.io/docs/api-reference/v1.6/#ingressspec-v1beta1-extensions) allows for per-host TLS cert/key, which needs to be served on a single port.
Implementation depends on Envoy to support SNI, which is track in lyft/envoy#95.

**Comment by ese** [comment]
Envoy has released SNI support https://www.envoyproxy.io/docs/envoy/latest/intro/version_history#id1

**Comment by danehans** [comment]
@ZackButcher if you have not started this work, I would like to take a stab at it. Let me know when you have a moment.

**Comment by ZackButcher** [comment]
I have not, be my guest! Lets sync up before you start to make sure we're on the same page.

**Comment by louiscryan** [comment]
FYI @costinm

**Comment by danehans** [comment]
@ZackButcher what is the best way to sync-up? I am trying to login to the istio.slack.com channel, but I'm failing auth. Can someone add me to the slack channel (daneyonhansen@gmail.com)? Otherwise, let me know how you would like to sync-up.

**Comment by danehans** [comment]
@ZackButcher never mind the above. I just saw your slack invite. Thanks!

**Comment by danehans** [comment]
The current proxy is based on an Envoy SHA from 10/31/2017. It needs to be updated to support SNI: https://github.com/istio/proxy/blob/master/WORKSPACE#L37

**Comment by rosenhouse** [comment]
we almost had it with https://github.com/istio/proxy/pull/934  but then that got rolled back via https://github.com/istio/proxy/pull/936

**Comment by ldemailly** [comment]
ETA for this shipping / which release?

**Comment by rosenhouse** [comment]
The Cloud Foundry team is interested in this feature for our ingress-like use-case.  Is this something we might be able to pick up?  Anyone want to help us estimate the scope involved?

**Comment by vietwow** [comment]
Hi,

Any update about this ? Thanks

Best Regards,

**Comment by ZackButcher** [comment]
We're targeting 0.8, our next release, for supporting SNI. We support SNI today via the Gateway API, but still only serve a single cert. The remaining work is supporting multiple certs. The Envoy side of that landed a while ago and we're just plumbing it through Pilot now.

**Comment by andraxylia** [comment]
Closing this in favor of #4879, which outlines precisely the outstanding changes needed in pilot to support multiple certs.
