### ISSUE TITLE
Update Vault integration doc with ServiceEntry

### ISSUE THREAD

**Issue by incfly** [istio/istio#14253]
As networking team pointed out, excluded annotation is a to be deprecated mode. We are suggested to use ServicEntry to access Vault.

Also some customers report some limitations about such mechanism, where Vault does not have a stable IP range, behind a load balancer.

https://discuss.istio.io/t/whitelist-domain/798

**Comment by incfly** [comment]
@andraxylia provides recommendation of `ServiceEntry` is better approach.

**Comment by howardjohn** [comment]
Fixed https://github.com/istio/istio.io/pull/4199
