### ISSUE TITLE
istio-security-test fails on e2e-simpleTests consistently

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#14252]
Example failure, changing no code: https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/14251/e2e-simpleTests-master/664

```
RUNNING: istio-security-test
FAILED: istio-security-test, run `kubectl logs istio-security-test --namespace istio-system` for more info
Error: 1 test(s) failed
2019-05-20T20:28:15.967524Z	info	Command error: exit status 1
2019-05-20T20:28:15.967571Z	error	Failed to execute Istio helm tests.
2019-05-20T20:28:15.967596Z	error	Failed to complete Init. Error helm test istio failed
```

**Comment by howardjohn** [comment]
Every test since noon today has failed https://testgrid.k8s.io/istio-presubmits-master#e2e-simpleTests

**Comment by icygalz** [comment]
Is it possible that adding KIND image to the istio-builder caused this issue?
https://github.com/istio/test-infra/pull/1257

**Comment by ericvn** [comment]
I was thinking it might be galley related and https://github.com/istio/istio/pull/14216? Still looking some more.

**Comment by howardjohn** [comment]
It is the security helm tests, it just curls citadel, so I don't think that code is really called in the test? We reverted the kind image, we can see if that fixes it (somehow). #14216 passed postsubmit which is why I don't suspect it

**Comment by pitlv2109** [comment]
Are we still investigating the cause?

**Comment by ericvn** [comment]
@pitlv2109 Looking at the tests, I do see mostly green again (although mine just failed). I'm suspecting a rebase is needed to get the tests to pass?

**Comment by howardjohn** [comment]
@ericvn this was fixed by reverting @icygalz PR. (I have no clue how it caused the issue though). Since this wasn't on istio/istio a rebase doesn't fix it, but if you do `/test e2e-simpleTest` it seems like it doesn't fully restart enough so it uses the old broken prow image. Basically I think you need to do `/test all` (or maybe rebase just to trigger new changes, not sure)

**Comment by ericvn** [comment]
Thanks. I did see the revert fixed the issue. I suspect there was something strange in the newly created image, although I did pull it and try some things locally, but couldn't figure out what it was exactly. I didn't spend a lot of time since things got reverted. I did a rebase on my PR and things passed.
