### ISSUE TITLE
sample/bookinfo can not be built

### ISSUE THREAD

**Issue by zhangbo1882** [istio/istio#14258]
./build-services.sh 0.1
~/go/src/github.com/istio/samples/bookinfo/src/productpage ~/go/src/github.com/istio/samples/bookinfo/src
Sending build context to Docker daemon   1.21MB
Step 1/16 : FROM python:3.6-slim
 ---> b75ddbd45c17
Step 2/16 : COPY requirements.txt ./
 ---> Using cache
 ---> 673d3c554b04
Step 3/16 : RUN pip install --no-cache-dir -r requirements.txt
 ---> Using cache
 ---> 93e1cc437d25
Step 4/16 : COPY test-requirements.txt ./
 ---> Using cache
 ---> 23dc756a2ebd
Step 5/16 : RUN pip install --no-cache-dir -r test-requirements.txt
 ---> Using cache
 ---> 7dece546949c
Step 6/16 : COPY productpage.py /opt/microservices/
 ---> Using cache
 ---> c902c63bef46
Step 7/16 : COPY tests/unit/* /opt/microservices/
 ---> Using cache
 ---> 12ebff516339
Step 8/16 : COPY templates /opt/microservices/templates
 ---> Using cache
 ---> 414f975a5677
Step 9/16 : COPY static /opt/microservices/static
 ---> Using cache
 ---> cf1176da8a7a
Step 10/16 : COPY requirements.txt /opt/microservices/
 ---> Using cache
 ---> 6b018061a66a
Step 11/16 : ARG flood_factor
 ---> Using cache
 ---> 191aba6cc7bd
Step 12/16 : ENV FLOOD_FACTOR ${flood_factor:-0}
 ---> Using cache
 ---> b2417092463f
Step 13/16 : EXPOSE 9080
 ---> Using cache
 ---> bb422e2953fb
Step 14/16 : WORKDIR /opt/microservices
 ---> Using cache
 ---> cba4fb13bb32
Step 15/16 : RUN python -m unittest discover
 ---> Running in 51ca3e74f666

ERROR: test_productpage (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_productpage
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/opt/microservices/test_productpage.py", line 25, in <module>
    import productpage
  File "/opt/microservices/productpage.py", line 65, in <module>
    "name" : "http://{0}{1}:9080".format(detailsHostname, servicesDomain),
NameError: name 'detailsHostname' is not defined

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
The command '/bin/sh -c python -m unittest discover' returned a non-zero code: 1

**Comment by vadimeisenbergibm** [comment]
@zhangbo1882 It works on master, does not work on release-1.2. @howardjohn should I handle it for release-1.2? I am not sure if it is important, since we can just update the yamls without updating the source code of bookinfo.

**Comment by vadimeisenbergibm** [comment]
Should be fixed by https://github.com/istio/istio/pull/15261.

**Comment by zhangbo1882** [comment]
thanks

**Comment by vadimeisenbergibm** [comment]
@zhangbo1882 Could you please close this issue?
