### ISSUE TITLE
Support sharing between TCP and HTTP services

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1426]
@ayj commented on [Tue Feb 28 2017](https://github.com/istio/old_pilot_repo/issues/237)

Envoy currently doesn't support using both `tcp_proxy` and `http_connection_manager` filter on the same port for different services. Support for this features requires updating envoy tcp_proxy filter to be optionally non-terminal and fallback to other filters (e.g. HTTP) on the same port. The workaround for this limitation is to not share ports between destination services with different protocols.

---

@kyessenov commented on [Thu Mar 02 2017](https://github.com/istio/old_pilot_repo/issues/237#issuecomment-283801176)

Started https://github.com/lyft/envoy/issues/527 to initiate a design discussion how to handle it properly.

**Comment by ijsnellf** [comment]
This will be possible once the fields here are implemented: https://github.com/envoyproxy/envoy/blob/master/api/envoy/api/v2/listener/listener.proto#L76
