### ISSUE TITLE
build job and e2e tests are done with a different version of go

### ISSUE THREAD

**Issue by jacob-delgado** [istio/istio#14269]
**Bug description**
For Istio 1.1.x releases, go 1.11 is used to build istio https://github.com/istio/istio/blob/1.1.7/.circleci/Dockerfile#L1 and https://github.com/istio/istio/blob/1.1.7/.circleci/config.yml#L7

However, it appears as if go 1.10.4 is used to run e2e tests. See https://github.com/istio/istio/blob/1.1.7/.circleci/config.yml#L44

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[X] Test and Release
[ ] User Experience

**Comment by sdake** [comment]
@jacob-delgado thanks for the report.  I think some people were aware of this problem and it is being resolved now.

Cheers
-steve
