### ISSUE TITLE
anyway to get istio related counter w/o deploying mixed 

### ISSUE THREAD

**Issue by ardenxu** [istio/istio#14262]
we find out the istio_* related counter like requestcount are label as mixer in default yaml config,  but we don't want to  deploy mix in our trial, is there any way to get these counters?

-------------------------------------------------------
apiVersion: "config.istio.io/v1alpha2"
kind: metric
metadata:
  name: requestcount
  namespace: istio-system
  labels:
    app: mixer
    chart: mixer
    heritage: Tiller
    release: istio
spec:
  value: "1"
  dimensions:
    reporter: conditional((context.reporter.kind | "inbound") == "outbound", "source", "destination")
    source_workload: source.workload.name | "unknown"
    source_workload_namespace: source.workload.namespace | "unknown"
    source_principal: source.principal | "unknown"
    source_app: source.labels["app"] | "unknown"
    source_version: source.labels["version"] | "unknown"
    destination_workload: destination.workload.name | "unknown"
    destination_workload_namespace: destination.workload.namespace | "unknown"
    destination_principal: destination.principal | "unknown"
    destination_app: destination.labels["app"] | "unknown"
    destination_version: destination.labels["version"] | "unknown"
    destination_service: destination.service.host | "unknown"
    destination_service_name: destination.service.name | "unknown"
    destination_service_namespace: destination.service.namespace | "unknown"
    request_protocol: api.protocol | context.protocol | "unknown"
    response_code: response.code | 200
    response_flags: context.proxy_error_code | "-"
    permissive_response_code: rbac.permissive.response_code | "none"
    permissive_response_policyid: rbac.permissive.effective_policy_id | "none"
    connection_security_policy: conditional((context.reporter.kind | "inbound") == "outbound", "unknown", conditional(connection.mtls | false, "mutual_tls", "none"))
  monitored_resource_type: '"UNSPECIFIED"'

**Comment by douglas-reid** [comment]
@ardenxu Short answer: no. Mixer is *solely* responsible for generation of the metrics in the current architecture. In the coming months, we will retire mixer as a binary (and separate services) entirely from the Istio architecture. That may address your underlying concerns.

This is a question better answered on the forums (discuss.istio.io). Let's move the conversation there, if there are any follow-ups.
