### ISSUE TITLE
Using an external jaeger installation

### ISSUE THREAD

**Issue by r0fls** [istio/istio#14274]
**Describe the feature request**
I would like to be able to point the tracing helm options to an external jaeger installation.

**Describe alternatives you've considered**
Anything that will allow me to get the istio and jaeger integration working with an external jaeger. I've tried looking into the helm chart and seeing if I can point it to the jaeger we have in a different namespace for example, or if the jaeger agent URL is being specified anywhere that I can override with `kubectl patch`

**Comment by objectiser** [comment]
When installing Istio, you can specify the URL to the collector using:
```
helm template install/kubernetes/helm/istio --name istio --namespace istio-system --set global.tracer.zipkin.address=simplest-collector.observability:9411 | kubectl apply -f -
```
This was based on setting up the Jaeger instance using the [jaeger-operator](https://github.com/jaegertracing/jaeger-operator) with the [simplest CR](https://github.com/jaegertracing/jaeger-operator/blob/master/deploy/examples/simplest.yaml).

**Comment by r0fls** [comment]
Thank you, that did it :100:
