### ISSUE TITLE
Consider aligning Istio API with smi-spec

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#14288]
[smi spec](https://github.com/deislabs/smi-spec) was recently released that aims to work across many mesh implementations.

It defines a Traffic API, Access Control API and a Metrics API.
The networking APIs have a much narrower surface than the Istio APIs.

The Metrics API adds a standard way of consuming metrics using k8s aggregation aPI.

/cc @louiscryan @rshriram @costinm

**Comment by imroc** [comment]
+1

**Comment by imroc** [comment]
or just use operator to translate SMI CRD to istio CRD?
check this out: https://github.com/deislabs/smi-adapter-istio
