### ISSUE TITLE
Google Chrome v. 73 and later breaks conditional rate limit task

### ISSUE THREAD

**Issue by dmitri-d** [istio/istio#14284]
**Bug description**
In Chrome version 73 a feature called "Preload pages for faster browsing and searching" has been added, which, if enabled, can result in Chrome adding data to cookies. When that happens, quota rule matcher ```request.headers["cookie"], "session=*"``` no longer matches, and "RESOURCE_EXHAUSTED" message is shown, regardless whether a user is logged in.

**Comment by dmitri-d** [comment]
Google's support
(https://support.google.com/chrome/answer/114836?hl=en&co=GENIE.Platform=Desktop)
has this clarification:
Preload pages for faster browsing and searching: Browsers use an IP
address to load a webpage. When you visit a webpage, Chrome can look
up the IP addresses of all the page's links and load the ones you
might navigate to next. If you turn this setting on, websites and any
embedded content that are preloaded can set and read their own cookies
as if you had visited them, even if you don't.

**Comment by douglas-reid** [comment]
@gargnupur can you add a WARNING to the task to turn off chrome preload ?

**Comment by gargnupur** [comment]
Sure...
