### ISSUE TITLE
Improve build security.

### ISSUE THREAD

**Issue by costinm** [istio/istio#14306]
Istio release and all tools used to build the release need to be built in a secure environment, where the machines used for building have clean state and are not shared with untrusted code. 
gcr.io/istio-testing credentials are available on the test workloads running in priv mode. 

In particular - PR#13531 should be reverted, and the release scripts need to be reviewed to make sure they don't use other images created on untrusted environments. 

Using GoogleCloudBuild, CircleCI or a dedicated, secure cluster for building the build tools and the release would be ideal.

**Comment by costinm** [comment]
@duderino @utka

**Comment by kyessenov** [comment]
@fpesce @utka 

I concur we need a common go build image. It's difficult to track down all the image sources complicating the upgrade process for go SDK, k8s version, and all the tools used in the build process.

**Comment by icygalz** [comment]
one of the idea i have:
1. Get rid run_after_success mechanism for all istio-release/pipeline branches ASAP.
2. Ask prow team to help setup a new HEAD binary prow cluster with correct configuration(build cluster only for building image and workload cluster where the tests are running on)  for istio-release/pipeline only**.

This will hopefully enough to solve release security issue.

** All other repos needs to be migrated to this new prow cluster once they are rid of run_after_success.

**Comment by fejta** [comment]
You can configure a prow job to create its pod resources in any kubernetes cluster. Long-term I would definitely recommend creating a trusted kubernetes cluster and only allow pods that use trusted images on trusted code (aka no presubmits) to run in this cluster. 

In the mean time, jobs on prow are reasonably safe assuming:
* prow jobs have been configured to use a trusted image
* the community has not pushed malicious commits
* community members sanity check PRs before leaving an `/ok-to-test` comment to allow jobs to run that code.

I believe right now you may have separate node pools, which -- assuming you configure the pod's correctly -- will ensure that presubmit and trusted code run on separate VMs (but still the same cluster).

**Comment by duderino** [comment]
@fejta thank you for weighing in here.

@costinm and @fpesce, why has this issue become a blocker for the 1.2 release?  Is it because https://github.com/istio/istio/pull/13531 violated @fejta's first point that we no longer use a trusted image?   If so our choices are to revert the PR or make it safe over the next two weeks?

If not, please explain in actionable terms the work that needs to be done here

**Comment by costinm** [comment]
Any update on this ? I can confirm that none of @fejta assumptions are valid in Istio - 

- prow jobs have been configured to use a trusted image - not clear what the trusted image would be, but there are plenty of ways to abuse what we currently use.

-the community has not pushed malicious commits - given the size and composition of the community 
it wouldn't be safe to rely on this 

- community members sanity check PRs before leaving an /ok-to-test comment to allow jobs to run that code - I did ask and nobody really does this, plus running jobs from commiters is not subject to this ( and see above point )

And that doesn't include the risk of attackers hijacking the machine/account of one of a committers.

So I think at least for 1.4 we should make sure the binaries we ship to users are generated on a trusted cluster where tests running in privileged mode are not allowed and with sufficient access control to the build machines.

**Comment by fejta** [comment]
Yes, the trusted cluster exists -- https://github.com/istio/test-infra/issues/1670
/cc @clarketm 

Which jobs create released binaries? Agree that those should not run on the same nodes as ones that run presubmits.

**Comment by clarketm** [comment]
Currently, as of istio/test-infra#1670, **all** Istio prowjobs (except for [test-infra deploy/image jobs](https://github.com/clarketm/istio_test-infra/blob/master/prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml)) by *default* run pods on a separate build cluster (`istio-prow-build`) and do not have access to secrets defined in `istio-testing`.
