### ISSUE TITLE
Make this CNI compliant with ipv6

### ISSUE THREAD

**Issue by venilnoronha** [istio/istio#14318]
@alexlovelltroy commented on [Thu Mar 07 2019](https://github.com/istio/cni/issues/95)

This CNI only appears to manage the iptables associated with ipv4.  Kubernetes is broadly moving to ipv6 and dual-stack support.  Adding an issue to track ipv6 needs and suggestions.

---

@john-a-joyce commented on [Thu Mar 07 2019](https://github.com/istio/cni/issues/95#issuecomment-470722446)

@alexlovelltroy - some of my peers at Cisco were championing the K8s dual stack IPv6 support so I am well aware of the status.   Additionally we had done some work in Istio to determine IPv6 Gaps,  but did not complete the work.  Recently sbezverk has been trying to fix some of the gaps that in this regard.   We would love to ensure that the CNI is ahead of both K8s and Istio wrt to IPv6 support so if this is an area you can help with that would be much appreciated. 

---

@alexlovelltroy commented on [Sat Mar 09 2019](https://github.com/istio/cni/issues/95#issuecomment-471230898)

Having explored the codebase a bit, I don't think I'm ready to contribute code, but I'm happy to do triage, review PRs, write/update docs.

**Comment by tiswanso** [comment]
This has been ongoing here:  https://github.com/istio/cni/pull/100

It incorporates the istio-iptables.sh changes to support IPv6 but also accounts for iptables locking problems seen in some CNI usage scenarios.  The majority of the PR is mainly the testing effort for IPv6 on KDC.  The e2e-simple tests require the changes from PR #13753

**Comment by tiswanso** [comment]
Closing this as ipv6 support for CNI has been added in 1.2
