### ISSUE TITLE
Envoy port is not configurable

### ISSUE THREAD

**Issue by venilnoronha** [istio/istio#14317]
@luksa commented on [Mon Feb 11 2019](https://github.com/istio/cni/issues/84)

Looking at the code, I don't see a way to override the default redirect port (15001). We should introduce a ConfigMap to make the port configurable (as it is when using the init container - see MeshConfig.ProxyListenPort)

---

@luksa commented on [Mon Feb 11 2019](https://github.com/istio/cni/issues/84#issuecomment-462248275)

The same goes for `.ProxyConfig.InterceptionMode`

---

@tiswanso commented on [Thu Feb 28 2019](https://github.com/istio/cni/issues/84#issuecomment-468468703)

For intercept mode the pod annotation can set this:  `sidecar.istio.io/interceptionMode`

**Comment by howardjohn** [comment]
You can edit mesh config for this value
