### ISSUE TITLE
Is there any requirements for jq's version?

### ISSUE THREAD

**Issue by venilnoronha** [istio/istio#14324]
@shuiqing05 commented on [Thu Mar 21 2019](https://github.com/istio/cni/issues/97)

Hi,
    I found the jq is one of dependency in the CNI. But, there are not any description of the jq's version.
    Is there any place record the requirement of all tool's version?
    Thanks!

**Comment by mabushey** [comment]
I doubt it, jq is the json equivalent of grep. It's simply an amazing simple cli tool. I never heard of versioning issues with it.

**Comment by howardjohn** [comment]
As mentioned above, this doesn't seem relevant. If it is a problem, assume the latest version :slightly_smiling_face:. Soon we will have reproducible docker builds
