### ISSUE TITLE
Istio generic service registry based on Etcd

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1432]
@andraxylia commented on [Thu Jun 01 2017](https://github.com/istio/old_pilot_repo/issues/824)

---

@rshriram commented on [Tue Jun 27 2017](https://github.com/istio/old_pilot_repo/issues/824#issuecomment-311390173)

For VM/CF environments with no service registry solution in place, it would be beneficial to provide a simple service registry implementation based on Etcd backend. The idea is not to provide a full fledged service registry implementation, until requested for by end users. Instead, the focus should be enabling VMs, CF apps and other non-k8s environments to get bootstrapped quickly. Towards this goal,
the first cut (for 0.2 release) would focus on providing a simple service registration agent (perhaps as part of the proxy agent itself), that does the following:
1. Reads registration information from a user provided configuration file. The configuration file would describe details such as the ports exposed by the VM/CF app, the names for the ports (http|https|gRPC|http2|tcp), the name of the service with which the VM instance is associated with, tags associated with the VM instance if any, and the service registry with which this VM is associated with (scope).
2. Obtains the local IP address (through the interface/obtained from config file) and registers the VM instance with the Istio service registry service (whose schema closely follows the Istio service model).
3. The question of who provides periodic heartbeats/health checks to the service registry is still open. If Envoy's HDS API lands on time, this can be re-used(?).

The simple file configuration based approach allows folks to easily distribute the (static) service registration information (except endpoint IP) via things like Git, and/or embed them into their VM/CF images.

Per offline discussions with @louiscryan the registry API would be a very simple hierarchy of 3 resources: `registry -> service->endpoint`, where each resource has a name, metadata and standard CRUD semantics. (the registry level resource allows for named registries with ACLs - not part of 0.2).

Docs to follow.

cc @kyessenov @ldemailly @zitroij @louiscryan @andraxylia @ijsnellf 

---

@ldemailly commented on [Mon Jul 24 2017](https://github.com/istio/old_pilot_repo/issues/824#issuecomment-317577124)

hopefully we go for option A and we're done. otherwise this will be for 0.3+

---

@rshriram commented on [Mon Jul 24 2017](https://github.com/istio/old_pilot_repo/issues/824#issuecomment-317588823)

Its not that simple. K8S does not have a good API for registering endpoints. The one that is currently present is limited (no tags, etc.) as per Saurabh in the istio-environments list.

---

@kyessenov commented on [Mon Jul 24 2017](https://github.com/istio/old_pilot_repo/issues/824#issuecomment-317589184)

Lack of tags on endpoints can be worked-around by attaching labels to NetworkEndpoint object, but it's not pretty.

**Comment by andraxylia** [comment]
@rshriram do we still need this?

**Comment by rshriram** [comment]
Nope. Thats why I closed this.

**Comment by ijsnellf** [comment]
I believe this can be closed because we now support `ServiceEntry`s.

**Comment by andraxylia** [comment]
This will be solved in Pilot by Pilot Decomposition. There is no concrete use case for etcd registry other than a quick bootstrap, for which the file base registry used by the testing framework might be preferable.
