### ISSUE TITLE
[Galley] Query CRD resource to discover available versions

### ISSUE THREAD

**Issue by irisdingbj** [istio/istio#14330]
This will be needed for being able to do up-down conversions within Galley where, upon start-up, Galley detects that the available version in the cluster is lower than the version it can serve.

**Comment by ozevren** [comment]
I don't think this is needed to support multi-version CRDs. We should be able to target always the lowest version.

**Comment by irisdingbj** [comment]
@ozevren In our original discussion, we need to discover k8s api server to find out the correct crd version. Do you think current lowest version logic is enough?

**Comment by ayj** [comment]
related: https://github.com/istio/istio/issues/13559
