### ISSUE TITLE
How to enable istioctl mixer?

### ISSUE THREAD

**Issue by yuchen9459** [istio/istio#14333]
I followed the instruction in [Collecting Metrics and Logs](https://istio-releases.github.io/v0.1/docs/tasks/metrics-logs.html) to set up a rule for mixer, with which I can monitor the service response time. When I type in `istioctl mixer rule get reviews.default.svc.cluster.local reviews.default.svc.cluster.local`, it reminds me  `Error: unknown command "mixer" for "istioctl"`. I have also checked `istioctl --help` but I didn't find the `mixer` sub-command in the available commands list. Can anybody tell me how to enable istioctl mixer? If the mixer configuration is deprecated, is there any other ways that I can use to monitor the service response time?

**Comment by howardjohn** [comment]
You are reading the docs from Istio v0.1 so it is probably all wrong by now. Please view the up to date docs at https://istio.io
