### ISSUE TITLE
issues with k8s 1.14

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#14344]
There have been reports of broken mixer/pilot->galley communication in k8s 1.14, where only the version of k8s makes a difference. E.g. it works fine with 1.13.

We should investigate if we're using some deprecated API or deprecated features in k8s that causes this.

**Comment by howardjohn** [comment]
Is this still an issue? We run all our tests on kubernetes 1.15 now and haven't ran into issues

**Comment by howardjohn** [comment]
Given we are testing on 1.14 and many users are now on 1.14 I think we have some confidence things work and there have been no concrete issues
