### ISSUE TITLE
Force better decoupling of manager components

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1434]
@ayj commented on [Wed May 31 2017](https://github.com/istio/old_pilot_repo/issues/821)

The istio/manager repo includes many components that share code. This is advantageous for code-reuse but introduces possibility of unnecessary tight coupling between components at the wrong abstraction level. It would be good to enforce stricter decoupling between these components and make the API integration points more explicit. 

One solution is to use bazel's [visibility capability](https://bazel.build/versions/master/docs/be/common-definitions.html#common.visibility). To ease into this change we can enable [--nocheck-visibility](https://bazel.build/versions/master/docs/bazel-user-manual.html#flag--check_visibility) in [tools/bazel.rc](https://github.com/istio/manager/blob/master/tools/bazel.rc) and start updating package's BUILD visibility. This will likely require some refactoring to eliminate visibility violations. We can remove `--nocheck-visibility` once we are confident with this refactoring.

The suggestion is to start with decoupling egress from platform/kube.

**Comment by andraxylia** [comment]
Is this still applicable after the move to a single repo?

**Comment by ayj** [comment]
This is less applicable with move way from bazel to native go tooling. At best we can rely on https://golang.org/doc/go1.4#internalpackages and code reviews to enforce proper package dependencies.
