### ISSUE TITLE
IngressGateway fails to start with unknown proxyComponentLogLevel flag

### ISSUE THREAD

**Issue by mousavian** [istio/istio#14389]
**Bug description**
IngressGateway component is failing with following error:
```bash
$kubectl log istio-ingressgateway-868fc8d7fd-9n4cv -n istio-ingress -p
2019-05-28T04:52:03.543645Z	error	unknown flag: --proxyComponentLogLevel
Error: unknown flag: --proxyComponentLogLevel
```

I suspect [this PR](https://github.com/istio/installer/pull/181), which provides `proxyComponentLogLevel` and `proxyLogLevel` as parameter for `istio/proxyv2`.
While [pilot supports this parameter](https://github.com/istio/istio/pull/13182), it seems `istio/proxy` [does not support](https://github.com/istio/proxy/search?utf8=%E2%9C%93&q=proxyComponentLogLevel&type=) this parameter yet.

**Expected behavior**
`istio-ingressgateway` pods to get to Ready state upon installation.

**Steps to reproduce the bug**
Simply try `docker run -it istio/proxyv2:1.1.7 proxy router --proxyComponentLogLevel=misc:error` or 
follow installation step below and observe logs of ingressgateway pods.
 
**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```
$ istioctl version --remote
client version: version.BuildInfo{Version:"1.1.6", GitRevision:"04850e14d38a69a38c16c800e237b1108056513e-dirty", User:"brew", Host:"Mojave-2.local", GolangVersion:"go1.12.5", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.6"}
citadel version: version.BuildInfo{Version:"1.1.7", GitRevision:"eec7a74473deee98cad0a996f41a32a47dd453c2-dirty", User:"root", Host:"341b3bf0-76ac-11e9-b644-0a580a2c0404", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.6-6-geec7a74"}
$
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-19T22:12:47Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.9", GitCommit:"16236ce91790d4c75b79f6ce96841db1c843e7d2", GitTreeState:"clean", BuildDate:"2019-03-25T06:30:48Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

I've tried this with both 1.1.4 and 1.1.7 versions.

**How was Istio installed?**
1. Clone istio/installer repository
2. Checkout [current master](https://github.com/istio/installer/tree/5e1bd7f)
3. Run `./bin/install.sh install_all` with all default values

**Environment where bug was observed (cloud vendor, OS, etc)**
cloud vendor=AWS
newly kubernetes cluster span up via KOPS

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

**Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.**

My attempt to dump state failed :( with following error. let me know if you still need this I'll dive into the script to see what's wrong there.
```
sh: line 118: "0" + "1084782": syntax error: operand expected (error token is ""0" + "1084782"")
```

**Comment by howardjohn** [comment]
The flag is a part of pilot agent not envoy: https://github.com/istio/istio/blob/8476158e82721ec4929e7071eb85f26b85189241/pilot/cmd/pilot-agent/main.go#L78

It is not in release-1.1, which is why it doesn't work -- istio/installer can only install 1.2 (master), not 1.1. I don't think we have settings to make it install 1.1, did you maybe have TAG environment variable set? If not maybe a bug somewhere that sets it incorrectly

**Comment by howardjohn** [comment]
This will be fixed now. 1.2 has the flag, and in 1.1 we allowed unknown flags

**Comment by mousavian** [comment]
Thank you @howardjohn
