### ISSUE TITLE
httpproxy fail when use istio

### ISSUE THREAD

**Issue by mofee** [istio/istio#14386]
(This is used to report product bugs, please visit <https://discuss.istio.io> for questions on using Istio)

**Bug description**
I have a app writed in java, and the app access X site use a proxy http://www.myproxy.com:8080.
I start the app use "java -Dhttps.proxyHost=www.myproxy.com -Dhttps.proxyPort=8080 -jar myapp".
It runs well in k8s without istio.
when i inject the istio sidecar into the app (without any serviceEntry), then it can not access X site by proxy http://www.myproxy.com:8080, it's response status is 404.

**Expected behavior**
the app can access external site by specify proxy

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
kubectl version:
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}

istioctl version --remote:
client version: version.BuildInfo{Version:"1.1.5", GitRevision:"9b6d31b74d1c0cc9358cc82d395b53f71393326b", User:"root", Host:"3e29fde4-6c3f-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.4-10-g9b6d31b"}
citadel version: version.BuildInfo{Version:"1.1.5", GitRevision:"9b6d31b74d1c0cc9358cc82d395b53f71393326b-dirty", User:"root", Host:"3e29fde4-6c3f-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.4-10-g9b6d31b"}
galley version: version.BuildInfo{Version:"1.1.5", GitRevision:"9b6d31b74d1c0cc9358cc82d395b53f71393326b-dirty", User:"root", Host:"3e29fde4-6c3f-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.4-10-g9b6d31b"}
ingressgateway version: version.BuildInfo{Version:"1.1.5", GitRevision:"9b6d31b74d1c0cc9358cc82d395b53f71393326b", User:"root", Host:"3e29fde4-6c3f-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.4-10-g9b6d31b"}
pilot version: version.BuildInfo{Version:"1.1.5", GitRevision:"9b6d31b74d1c0cc9358cc82d395b53f71393326b-dirty", User:"root", Host:"3e29fde4-6c3f-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.4-10-g9b6d31b"}
policy version: version.BuildInfo{Version:"1.1.5", GitRevision:"9b6d31b74d1c0cc9358cc82d395b53f71393326b-dirty", User:"root", Host:"3e29fde4-6c3f-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.4-10-g9b6d31b"}
sidecar-injector version: version.BuildInfo{Version:"1.1.5", GitRevision:"9b6d31b74d1c0cc9358cc82d395b53f71393326b-dirty", User:"root", Host:"3e29fde4-6c3f-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.4-10-g9b6d31b"}
telemetry version: version.BuildInfo{Version:"1.1.5", GitRevision:"9b6d31b74d1c0cc9358cc82d395b53f71393326b-dirty", User:"root", Host:"3e29fde4-6c3f-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.4-10-g9b6d31b"}

**How was Istio installed?**
install use helm

**Environment where bug was observed (cloud vendor, OS, etc)**
CentOS Linux release 7.6.1810 (Core)

**Comment by mofee** [comment]
> kubectl get configmap istio -n istio-system -o yaml | grep -o "mode: ALLOW_ANY"
mode: ALLOW_ANY

**Comment by mofee** [comment]
use a ServiceEntry allow X site and www.myproxy.com:8080 also faild

**Comment by g-p-n** [comment]
@mofee 
In our experimental setup, we are perhaps seeing a manifestation of this issue.
a) Does your app attempt to connect to the proxy only once, i.e. soon after the Pod is Running?

b) If your app connects to the proxy on-demand or periodically sometime after the Pod has been Running, then what happens to these connection attempts?

c) I do not believe that this issue has to do anything with connecting to a proxy.
In our setup, we have a Pod which attempts to curl GET sample data from a test server. All attempts succeed to get the data from the server succeed.

We see an issue in a variant of the same Pod which has the istio-sidecar manually injected. The first attempt always fails because curl is unable to connect to the test server (connection refused). However, subsequent attempts succeed.
With access logging enabled, in istio-proxy, I see that the number of outbound GET requests logged correspond to the number of successful attempts by curl.

I am debugging this further, and shall post the findings/results.

**Comment by g-p-n** [comment]
Attached are:
(a) the logs from the pod/container that attempts to curl GET sample/test data from a server
(b) logs from the proxy container (with --proxyLogLevel=trace, and hence a bit noisy)
[server/host names and public IP addresses changed to preserve identities, but length preserved]

- TCP stats and iptables stats are below.
- Container logs show that the first connection attempt has failed, while the subsequent 4 attempts succeed. The first connection attempt is made even before the proxy container logs that an active listener for 15001 has been added.
- Proxy container logs show that the listener is aware of four requests (post a listener has been active on 15001).

Tcp:
    13 active connections openings
    82 passive connection openings
    2 failed connection attempts
    0 connection resets received
    4 connections established
    546 segments received
    715 segments send out
    1 segments retransmited
    0 bad segments received.
    2 resets sent

root@istio-curler-pod:~# iptables -nvL -t nat
Chain PREROUTING (policy ACCEPT 95 packets, 5700 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain INPUT (policy ACCEPT 95 packets, 5700 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 50 packets, 4232 bytes)
 pkts bytes target     prot opt in     out     source               destination         
   13   780 ISTIO_OUTPUT  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain POSTROUTING (policy ACCEPT 56 packets, 4592 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain ISTIO_IN_REDIRECT (0 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            redir ports 15001

Chain ISTIO_OUTPUT (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 ISTIO_REDIRECT  all  --  *      lo      0.0.0.0/0           !127.0.0.1           
    7   420 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 1337
    0     0 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner GID match 1337
    0     0 RETURN     all  --  *      *       0.0.0.0/0            127.0.0.1           
    6   360 ISTIO_REDIRECT  all  --  *      *       0.0.0.0/0            0.0.0.0/0           

[curler.3.log](https://github.com/istio/istio/files/3316678/curler.3.log)
[curler.3.proxy.log](https://github.com/istio/istio/files/3316679/curler.3.proxy.log)

**Comment by mofee** [comment]
@g-p-n , thanks for your reply.
I also test use a curl pod, the image from [https://hub.docker.com/r/appropriate/curl](https://hub.docker.com/r/appropriate/curl), and be injected the istio sidecar with  --proxyLogLevel=trace.
Then i sue cmd: 
  `curl -x http://hkproxy.global.test.com:8080 https://www.google.com`
and the response is
  `curl: (56) Received HTTP code 404 from proxy after CONNECT`

the istio-proxy trace log file is [here](https://github.com/mofee/files/blob/master/istio_proxy.log)
I can see the envoy add some headers in http connect, i don't know if it is the cause
`[2019-06-25 07:12:48.248][26][trace][http] [external/envoy/source/common/http/http1/codec_impl.cc:363] [C5] parsing 120 bytes
[2019-06-25 07:12:48.248][26][trace][http] [external/envoy/source/common/http/http1/codec_impl.cc:476] [C5] message begin
[2019-06-25 07:12:48.249][26][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:243] [C5] new stream
[2019-06-25 07:12:48.249][26][trace][http] [external/envoy/source/common/http/http1/codec_impl.cc:331] [C5] completed header: key=Host value=www.google.com:443
[2019-06-25 07:12:48.249][26][trace][http] [external/envoy/source/common/http/http1/codec_impl.cc:331] [C5] completed header: key=User-Agent value=curl/7.59.0
[2019-06-25 07:12:48.249][26][trace][http] [external/envoy/source/common/http/http1/codec_impl.cc:442] [C5] headers complete
[2019-06-25 07:12:48.249][26][trace][http] [external/envoy/source/common/http/http1/codec_impl.cc:331] [C5] completed header: key=Proxy-Connection value=Keep-Alive
[2019-06-25 07:12:48.249][26][trace][http] [external/envoy/source/common/http/http1/codec_impl.cc:463] [C5] message complete
[2019-06-25 07:12:48.249][26][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:580] [C5][S5680453476879491337] request headers complete (end_stream=true):
':authority', 'www.google.com:443'
':path', 'www.google.com:443'
':method', 'CONNECT'
'user-agent', 'curl/7.59.0'
'proxy-connection', 'Keep-Alive'

[2019-06-25 07:12:48.249][26][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:1040] [C5][S5680453476879491337] request end stream
[2019-06-25 07:12:48.249][26][debug][filter] [src/envoy/http/mixer/filter.cc:39] Called Mixer::Filter : Filter
[2019-06-25 07:12:48.249][26][debug][filter] [src/envoy/http/mixer/filter.cc:146] Called Mixer::Filter : setDecoderFilterCallbacks
[2019-06-25 07:12:48.249][26][trace][http] [external/envoy/source/common/http/conn_manager_impl.cc:1200] [C5][S5680453476879491337] encode headers called: filter=0x2ecfd60 status=0
[2019-06-25 07:12:48.249][26][trace][http] [external/envoy/source/common/http/conn_manager_impl.cc:1200] [C5][S5680453476879491337] encode headers called: filter=0x2ecfcc0 status=0
[2019-06-25 07:12:48.249][26][debug][filter] [src/envoy/http/mixer/filter.cc:133] Called Mixer::Filter : encodeHeaders 0
[2019-06-25 07:12:48.249][26][trace][http] [external/envoy/source/common/http/conn_manager_impl.cc:1200] [C5][S5680453476879491337] encode headers called: filter=0x2ecfa40 status=0
[2019-06-25 07:12:48.249][26][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:1305] [C5][S5680453476879491337] encoding headers via codec (end_stream=true):
':status', '404'
'date', 'Tue, 25 Jun 2019 07:12:48 GMT'
'server', 'envoy'
`

**Comment by g-p-n** [comment]
@mofee 
Thank you for the traces. Shall take a look at it.
Will I be able to use http://hkproxy.global.test.com:8080 to reproduce the issue locally?

**Comment by mofee** [comment]
@g-p-n  http://hkproxy.global.test.com:8080 is our internal  http proxy, can not be accessed for you.

**Comment by g-p-n** [comment]
@mofee 
Never mind about my request to use your proxy server.
I able to reproduce the issue.

**Comment by mofee** [comment]
@g-p-n  
Never mind, but it's a  internal ip [192.168.195.9]
i have tried visiting a http website
   `curl -x http://hkproxy.global.test.com:8080  http://www.website.org/`
the curl not print the error message, but also can not received the response, nothing print out.

**Comment by g-p-n** [comment]
@mofee 
Your logs with trace enabled helped.
Here is my investigation. In summary, I see that envoy does not support CONNECT.
We could wait to hear from the istio/proxy/envoy experts.

This is the output from curl.
```
*   Trying AA.BB.CCC.DDD...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x561e653037a0)
* Connected to someproxy.com (AA.BB.CCC.DDD) port 8080 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to www.google.com:443
> CONNECT www.google.com:443 HTTP/1.1
> Host: www.google.com:443
> User-Agent: curl/7.64.0
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 404 Not Found
HTTP/1.1 404 Not Found
< date: Tue, 25 Jun 2019 13:41:53 GMT
date: Tue, 25 Jun 2019 13:41:53 GMT
< server: envoy
server: envoy
< content-length: 0
content-length: 0
< 

* Received HTTP code 404 from proxy after CONNECT
* CONNECT phase completed!
* Closing connection 0
curl: (56) Received HTTP code 404 from proxy after CONNECT
```

Here is the corresponding output of the parsing from istio-proxy.
```
[external/envoy/source/common/http/conn_manager_impl.cc:580] [C5][S5680453476879491337] request headers complete (end_stream=true):
':authority', 'www.google.com:443'
':path', 'www.google.com:443'
':method', 'CONNECT'
'user-agent', 'curl/7.59.0'
'proxy-connection', 'Keep-Alive'
```

In this case of a request via a proxy, the first HTTP command/method issued is CONNECT. Also, the "path" above is really not a relative path.

Hence, I believe we are running into this code segment, which is sending an HTTP 404 as the response to the client (in this case curl). I suspect the same is happening to your Java application too.

```
  // Currently we only support relative paths at the application layer. We expect the codec to have
  // broken the path into pieces if applicable. NOTE: Currently the HTTP/1.1 codec only does this
  // when the allow_absolute_url flag is enabled on the HCM.
  // https://tools.ietf.org/html/rfc7230#section-5.3 We also need to check for the existence of
  // :path because CONNECT does not have a path, and we don't support that currently.
  if (!request_headers_->Path() || request_headers_->Path()->value().getStringView().empty() ||
      request_headers_->Path()->value().getStringView()[0] != '/') {
    const bool has_path =
        request_headers_->Path() && !request_headers_->Path()->value().getStringView().empty();
    connection_manager_.stats_.named_.downstream_rq_non_relative_path_.inc();
    sendLocalReply(Grpc::Common::hasGrpcContentType(*request_headers_), Code::NotFound, "", nullptr,
                   is_head_request_, absl::nullopt,
                   has_path ? StreamInfo::ResponseCodeDetails::get().AbsolutePath
                            : StreamInfo::ResponseCodeDetails::get().MissingPath);
    return;
  }
```
in https://github.com/envoyproxy/envoy/blob/master/source/common/http/conn_manager_impl.cc.

Hence, this log in istio-proxy seen in my setup.
```
[2019-06-25 13:41:53.689][23][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:1137] [C6][S2763635160165889090] Sending local reply with details absolute_path_rejected
```

**Comment by g-p-n** [comment]
@mofee 
Digging further, it looks like envoy can perform as a HTTP proxy. Here are the links to the envoy documentation and configuration.

https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/http_proxy#arch-overview-http-dynamic-forward-proxy
https://www.envoyproxy.io/docs/envoy/latest/configuration/http_filters/dynamic_forward_proxy_filter#config-http-filters-dynamic-forward-proxy

However, the envoy documentation clearly states that this feature is to be considered as alpha and not production ready.
I haven't tried this out myself.

**Comment by rshriram** [comment]
does the application have to access X site only using myproxy? can it access the site using the local sidecar's HTTP proxy ?

**Comment by mofee** [comment]
@g-p-n  thank you, i will try follow the links 
@rshriram , for some reasons, our apps can not access the internet except by the http proxy

**Comment by mofee** [comment]
today, i tried to config the envoy dynamic forward proxy, but it required that 
1. filter should be configured with the name envoy.filters.http.dynamic_forward_proxy
2.Both filter and cluster must be configured together and point to the same DNS cache parameters for Envoy to operate as an HTTP dynamic forward proxy

i can config the http filter via the istio envoy filter, how can i config cluster  use istio?
