### ISSUE TITLE
Certmanager missing replica count

### ISSUE THREAD

**Issue by ChrisCooney** [istio/istio#14380]
**Describe the feature request**
In the [values.yaml file for the certmanager helm chart](https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/certmanager/values.yaml), there is no option to set the number of replicas. Given that this helm chart comes with a pod disruption budget, it means that the pod can't be evicted during node maintenance and you have to manually either kill the pod or scale the deployment to two instances.

To make this simpler, the helm chart should support a `replicaCount` field that will allow us to start the deployment with two pods instead of one. This makes maintenance of the node possible. I'm unsure why the field isn't already supported since it is everywhere else.

**Comment by jmagnusson** [comment]
This hit me as well, while trying to drain the pods on the node pool containing istio (during kubernetes upgrade).

The error that I was getting was:
```
error when evicting pod "certmanager-5954db8bcd-5mtp4" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget.
```

For `istio-ingressgateway`, `istio-pilot`, `istio-policy` and `istio-telemetry` I could just set the HorizontalPodAutoscaler to require a minimum of 2 pods (`minReplicas`) and for `istio-galley` I could just increase the replica count on the deployment. These values can all be configured through the helm chart as well.

For `certmanager` however, this would have to be done manually, like you mentioned.

Is there an underlying reason for `certmanager` having its `replicaCount` hardcoded to `1` in the helm chart?

**Comment by ChrisCooney** [comment]
Sweet 🔥🔥🎉🎉🙏
