### ISSUE TITLE
[istio remote] telemetry and tracing data not available

### ISSUE THREAD

**Issue by shubhamitc** [istio/istio#14385]
(This is used to report product bugs, please visit <https://discuss.istio.io> for questions on using Istio)

**Bug description**
We are running single control plane and 1 remote cluster. We are trying to capture tracing and prometheus information of services running on remote cluster. There is no data for both of them. 
I have tried to enable jaeger for control plane first, that did not work. 

Modified remote cluster with below command :
```
helm template install/kubernetes/helm/istio --namespace istio-system --name istio-remote --values install/kubernetes/helm/istio/values-istio-remote.yaml --set global.remotePilotAddress=${PILOT_POD_IP} --set global.remotePolicyAddress=${POLICY_POD_IP} --set global.remoteTelemetryAddress=${TELEMETRY_POD_IP} --set tracing.enabled=true  --set prometheus.enabled=true   --set grafana.enabled=true > istio_remote_east.yaml

```
And able to see some data. However that means tracing data wont be at single place for all the services as we start running more remote clusters. We run Netflix hysterics as well so be able to compare the data between envoys and hysterics.   

Problems
* Centralised tracing data
* Centralised metrics data 
* Compare data between envoys and hysterics , remove hysterics in future releases 

**Expected behavior**
Should be able to see metrics and tracing information in prometheus and jaeger. Core tracing services are running on control plane. 

**Steps to reproduce the bug**
Follow this document of GKE:  https://istio.io/docs/examples/multicluster/gke/ 
Modify helm commands to below for control plane
```
helm template install/kubernetes/helm/istio --name istio --namespace istio-system  --set grafana.enabled=true --set kiali.enabled=true --set prometheus.enabled=true --set tracing.enabled=true --set tracing.ingress.enabled=true >> istio_master_us_east.yaml 
kubectl create ns istio-system
kubectl apply -f istio_master_us_east.yaml 
kubectl label namespace default istio-injection=enabled
```

Modify helm command to below for remote plane 
```
helm template install/kubernetes/helm/istio --namespace istio-system --name istio-remote --values install/kubernetes/helm/istio/values-istio-remote.yaml --set global.remotePilotAddress=${PILOT_POD_IP} --set global.remotePolicyAddress=${POLICY_POD_IP} --set global.remoteTelemetryAddress=${TELEMETRY_POD_IP} > istio_remote_east.yaml
```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```
./istioctl version --remote

client version: version.BuildInfo{Version:"1.1.0", GitRevision:"82797c0c0649a3f73029b33957ae105260458c6e", User:"root", Host:"996cd064-49c1-11e9-813c-0a580a2c0506", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-rc.6"}
citadel version: version.BuildInfo{Version:"1.1.0", GitRevision:"82797c0c0649a3f73029b33957ae105260458c6e-dirty", User:"root", Host:"1f4e9557-49cd-11e9-86e9-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-rc.6"}
galley version: version.BuildInfo{Version:"1.1.0", GitRevision:"82797c0c0649a3f73029b33957ae105260458c6e-dirty", User:"root", Host:"1f4e9557-49cd-11e9-86e9-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-rc.6"}
ingressgateway version: version.BuildInfo{Version:"1.1.0", GitRevision:"82797c0c0649a3f73029b33957ae105260458c6e", User:"root", Host:"1f4e9557-49cd-11e9-86e9-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.0-rc.6"}
pilot version: version.BuildInfo{Version:"1.1.0", GitRevision:"82797c0c0649a3f73029b33957ae105260458c6e-dirty", User:"root", Host:"1f4e9557-49cd-11e9-86e9-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-rc.6"}
policy version: version.BuildInfo{Version:"1.1.0", GitRevision:"82797c0c0649a3f73029b33957ae105260458c6e-dirty", User:"root", Host:"1f4e9557-49cd-11e9-86e9-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-rc.6"}
sidecar-injector version: version.BuildInfo{Version:"1.1.0", GitRevision:"82797c0c0649a3f73029b33957ae105260458c6e-dirty", User:"root", Host:"1f4e9557-49cd-11e9-86e9-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.0-rc.6"}
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.8-gke.6", GitCommit:"394ee507d00f15a63cef577a14026096c310698e", GitTreeState:"clean", BuildDate:"2019-03-30T19:31:43Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
using Helm and kubectl apply 

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by douglas-reid** [comment]
Are you trying to figure out how to send traces to a remote endpoint, rather than in-cluster?

Have you looked at `global.tracer.zipkin.address` ?

As for metrics, is the concern that prometheus will not be able to scrape the remote targets?

**Comment by shubhamitc** [comment]
can you guide me to some documentation that explains tracing configuration for remote cluster. I am also difficulty to capture metrics from remote host. To answer your questions : 

Are you trying to figure out how to send traces to a remote endpoint, rather than in-cluster? - Yes from remote cluster to management cluster. This is to make sure all the tracing is at one place. 

Have you looked at global.tracer.zipkin.address ? - No , can you guide me to some documents 

As for metrics, is the concern that prometheus will not be able to scrape the remote targets? - Yes

**Comment by douglas-reid** [comment]
@shubhamitc i'm not sure there are any documents that will provide details around using `global.tracer.zipkin.address`. It is a helm install option. You would point it at the remove zipkin endpoint you desire to send tracing data to.

For prometheus, you just need to ensure that your prom can access the endpoints. There isn't much Istio-specific about this. There are a variety of possible architectures, including prometheus federation.

You may want to take a look at the docs for [Multicluster](https://istio.io/docs/setup/kubernetes/install/multicluster/) to understand the role of the remote* install options better.

I'd suggest sending general questions about standalone collectors to the forums. You are more likely to find others with similar setups there.

I'm going to close this issue, as this the forums are the better venue for follow-up.

**Comment by shubhamitc** [comment]
@douglas-reid prometheus running in control cluster is not able to do service discovery of pods running in remote cluster. I do understand the prometheus does not have much to do with istio however service discovery aspect of it has to be addressed. 

Currently it looks like we need to give access of tokens and secrets for remote cluster to scrap them.

**Comment by douglas-reid** [comment]
@shubhamitc why not run a prometheus in each cluster and use prometheus federation or some other strategy to achieve the same goal?
