### ISSUE TITLE
how to get database call span in a trace

### ISSUE THREAD

**Issue by aliartiza75** [istio/istio#14384]
Hello everyone,

**Question**

I have a question regarding how to get spans for database calls?

**Description**

* According to the documentation when we need to configure pods and service using the conventions given on this [link](https://istio.io/docs/setup/kubernetes/prepare/requirements/). 

* the Second point is that applications need to pass these [request params](https://istio.io/docs/tasks/telemetry/distributed-tracing/overview/) in egress requests but the issue is that I can handle these things on application code but how to do it on database calls side what I meant is that I cannot change the database client's code to pass those request headers.

**Comment by douglas-reid** [comment]
Please move this question to our discuss forum, as that is a more appropriate venue for questions.  Thanks.

**Comment by aliartiza75** [comment]
@douglas-reid I have created a topic on forum for it.
