### ISSUE TITLE
Bypass ingress proxy for in-cluster routes to ingress

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1438]
@kyessenov commented on [Mon May 22 2017](https://github.com/istio/old_pilot_repo/issues/805)

There is an evolving pattern to use a single proxy endpoint for all routing (e.g. ambassador, apigee), which can act as an advanced ingress proxy. With the current design, there would be 3 network hops (client sidecar, ingress, server sidecar). We can bypass the ingress proxy on the request path from the client sidecar if we incorporate the routing table in the sidecar.

---

@kyessenov commented on [Mon May 22 2017](https://github.com/istio/old_pilot_repo/issues/805#issuecomment-303196635)

cc @mpnally

**Comment by louiscryan** [comment]
This seems out of date. We program the sidecars with routes.
