### ISSUE TITLE
istio ingress-gateway not aware of file mounted tls certs on GKE

### ISSUE THREAD

**Issue by majelbstoat** [istio/istio#14397]
**Bug description**

Following the instructions [here](https://preliminary.istio.io/docs/tasks/traffic-management/ingress/secure-ingress-mount/) to secure an ingress gateway with file mounted tls certs, the certs are mounted correctly, but the ingress gateway is not aware of them.

Istio is provided by the Istio GKE add-on. Cloud Run is also enabled on the cluster.

Deleting the pod and recreating it does not solve the problem.

Regular HTTP access through the gateway works as expected.

HTTPS Requests give an immediate `Connection refused`

Ingress gateway logs show requests for HTTP traffic. No logs appear for HTTPS traffic.

**Expected behavior**

```
$ kubectl exec -ti $(kubectl get po -l istio=ingressgateway -n istio-system -o jsonpath='{.items[0].metadata.name}') -n istio-system -- curl  127.0.0.1:15000/certs
{
  // certificate data
}  
```

**Steps to reproduce the bug**

Per trouble-shooting:

*Verify that the Subject is correct in the certificate of the ingress gateway:*
```
$ kubectl exec -i -n istio-system $(kubectl get pod -l istio=ingressgateway -n istio-system -o jsonpath='{.items[0].metadata.name}')  -- cat /etc/istio/ingressgateway-certs/tls.crt | openssl x509 -text -noout | grep 'Subject:'
        Subject: OU=Domain Control Validated, OU=PositiveSSL, CN=sutro.cc
```

*Verify that the proxy of the ingress gateway is aware of the certificates:*
```
$ kubectl exec -ti $(kubectl get po -l istio=ingressgateway -n istio-system -o jsonpath='{.items[0].metadata.name}') -n istio-system -- curl  127.0.0.1:15000/certs
 <no output>
```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

Per GKE [docs](https://cloud.google.com/istio/docs/istio-on-gke/installing), server version is 1.0.6-gke.3

```
$ istioctl version
Version: 1.0.6
GitRevision: 98598f88f6ee9c1e6b3f03b652d8e0e3cd114fa2-dirty
User: brew@Mojave-2.local
Hub: docker.io/istio
GolangVersion: go1.11.5
BuildStatus: Modified
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.7-gke.10", GitCommit:"8d9b8641e72cf7c96efa61421e87f96387242ba1", GitTreeState:"clean", BuildDate:"2019-04-12T22:59:24Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

Istio on GKE add-on. istioctl through brew on MacOS.

**Environment where bug was observed (cloud vendor, OS, etc)**

GKE

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by majelbstoat** [comment]
After further searching, I believe I'm seeing the same issue as https://github.com/istio/istio/issues/12290. Closing for now.

**Comment by mizhkeao** [comment]
Hi, I'm running into the same issue. Were you able to get a workaround for this?
