### ISSUE TITLE
Using ServiceEntry to configure an external tcp connection does not take effect.

### ISSUE THREAD

**Issue by tuantuan11233** [istio/istio#14391]
(This is used to report product bugs, please visit <https://discuss.istio.io> for questions on using Istio)

**Bug description**
Hi, 
I want to connect to the external tcp service in the Kubernetes cluster. I know that there is a native Kubernetes Service and Endpoint to connect, but after injecting istio I occasionally encounter connection tcp service failure. 
I am not sure if I have to use ServiceEntry for external tcp declarations. Otherwise the above situation will occur, so I tried to configure the external tcp connection using ServiceEntry.
But I am having trouble configuring external tcp connections using ServiceEntry. When connecting to the tcp service, the pod will display an error indicating that the name or service is unknown (the same is displayed when pinging from the shell terminal).
Below, I will show my configuration (I want to know if there is a problem with my configuration and understanding).
I look forward to your reply, thank you, good morning.

**Expected behavior**
Can perform normal tcp connection

**Steps to reproduce the bug**
I tried to use the configuration in both documents, but the final effect is the same, this is the first one:
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: mongo.testdomain
  namespace: ccsrv
spec:
  hosts:
  - mongo.testdomain.svc.cluster.local
  addresses:
  - 10.19.142.223/32
  ports:
  - number: 20000
    name: tcp-mongo
    protocol: TCP
  resolution: STATIC
  location: MESH_EXTERNAL
  endpoints:
  - address: 10.19.142.223
    ports:
      tcp-mongo: 20000

This is the second:
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: mongo.testdomain
  namespace: ccsrv
spec:
  hosts:
  - mongo.testdomain
  ports:
  - number: 20000
    name: tcp-mongo
    protocol: TCP
  resolution: NONE
  location: MESH_EXTERNAL
EOF
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mongo.testdomain
  namespace: ccsrv
spec:
  hosts:
  - mongo.testdomain
  tls:
  - match:
    - port: 20000
      sni_hosts:
      - mongo.testdomain
    route:
    - destination:
        host: 10.19.142.223
        port:
          number: 20000

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
istioctl version && kubectl version
version.BuildInfo{Version:"1.1.7", GitRevision:"eec7a74473deee98cad0a996f41a32a47dd453c2", User:"root", Host:"341b3bf0-76ac-11e9-b644-0a580a2c0404", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.6-6-geec7a74"}

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:45:25Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
kubectl apply -f install/kubernetes/istio-demo.yaml 

**Environment where bug was observed (cloud vendor, OS, etc)**
cat /etc/centos-release && uname -a

CentOS Linux release 7.5.1804 (Core) 
Linux 10-19-133-245-k8s-new-master1 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Affected product area (please put an X in all that apply)**

[X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
>  the pod will display an error indicating that the name or service is unknown (the same is displayed when pinging from the shell terminal).

This sounds like its not resolving in DNS. Unlike a kuberetes Service, a ServiceEntry will not create a DNS entry for you
