### ISSUE TITLE
Release process somewhat broken wrt multi-repo and Go modules

### ISSUE THREAD

**Issue by geeknoid** [istio/istio#14411]
Our current release process has not kept pace with multi-repo work and the switch to Go modules:

#1. Need to branch every repo.

When preparing for a release, we need to create release branches in all repos that contribute to a release. For example right now, istio/pkg is not branched so changes in the master branch can come pollute a release branch in istio/istio.

#2. Need to update go.mod.

Once we have created all the release branches, we need to update the go.mod files in all the repos so that cross-repo dependencies are entirely branch-based. Specifically, we want istio/istio's release-1.2 branch to depend on istio/pkg's release-1.2 branch.

**Comment by linsun** [comment]
yes I raised issue #1 to @duderino and @fpesce yesterday also.  I know operator isn't branched yet.

I think we need a list of repos that can build the release with 1.2 given the multi-repo work.  Is this accurate?
- istio
- installer
- proxy
- api
- cni

Is this an accurate list?  you mentioned pkg, could you point me to some docs on how it is used by other repos?

Given the state of operator (still finalizing APIs), I'll say it is a stretch goal and may land in 1.3.

**Comment by geeknoid** [comment]
istio/pkg is used by the other repos and provides a whole bunch of common low-level packages (logging, controlz, doc output, env var access, etc).  So it needs to be on the list too.

We also build stuff from the tools repo. I think we'll eventually want to be branching this too, once we have our docker image build issues under control. For now, it's probably OK without branching.

And then there's istio.io, which needs branching, but it is handled independently from the others since it's not a build dependency of the product.

**Comment by howardjohn** [comment]
All of this worked was tracked for 1.3 in  https://github.com/istio/istio/issues/16201 the intent is this issue will become the new "release process". So I think this issue is done, unless there was specific work for this other than "make sure you do steps 1 and 2 when you make a branch"
