### ISSUE TITLE
Support k8s app protocols alpha annotation

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1441]
@kyessenov commented on [Tue Jul 25 2017](https://github.com/istio/old_pilot_repo/issues/957)

k8s GCE ingress supports a new annotation to clarify the port protocols, e.g.
`service.alpha.kubernetes.io/app-protocols: {"my-aport":"HTTPS","my-bport":"HTTP"}`
(defined https://github.com/kubernetes/ingress/blob/103d082d89e23ce61f895b77be81210ec6406f6a/controllers/gce/controller/utils.go#L69-L73)

We should support this as an alternative to using port names.

**Comment by qiujian16** [comment]
I would like to work on this one.

**Comment by louiscryan** [comment]
@qiujian16 are you still interested in working on this ?
