### ISSUE TITLE
the sidecar with my own envoy get 503

### ISSUE THREAD

**Issue by zqzzq** [istio/istio#14417]
**Bug description**
I compiled the envoy binary from the source code, and then built the proxyv2 image with this envoy binary, but the pods with this sidecar were all get 503, in the istio-proxy logs I can find this:
```
gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener(s) 158.158.116.7_9080: Didn't find a registered implementation for name: 'mixer', .....
```
**Expected behavior**
the sidecar is running.
**Version (include the output of `istioctl version --remote` and `kubectl version`)**
the istio: 1.1.4
the envoy: 1.10.0

**Comment by howardjohn** [comment]
Did you build from https://github.com/istio/proxy or envoy repo directly?

**Comment by zqzzq** [comment]
@howardjohn envoy repo directly, so do I need to build it from https://github.com/istio/proxy?

**Comment by howardjohn** [comment]
@zqzzq yes. I am not very familiar with the details, but we add some Istio stuff, such as the Mixer filter that was giving you an error

**Comment by zqzzq** [comment]
@howardjohn ok, thanks a lot! Closing the issue.
