### ISSUE TITLE
Update everything to Go 1.12

### ISSUE THREAD

**Issue by geeknoid** [istio/istio#14420]
It appears as though some of our stuff is being built with Go 1.12 while some of our test jobs are using Go 1.11. We need to be using a consistent tool chain for everything.

Check out https://github.com/istio/istio/pull/14410 for evidence of this. Some test jobs are passing, some are failing because they're using Go 1.11

**Comment by sdake** [comment]
A potentially relevant PR: https://github.com/istio/istio/pull/14294/files

**Comment by sdake** [comment]
A potentially relevant PR: https://github.com/istio/istio/pull/14270

**Comment by sdake** [comment]
Duplicate bug: https://github.com/istio/istio/issues/14269

**Comment by sdake** [comment]
A potentially relevant PR: https://github.com/istio/istio/pull/14214/files

**Comment by sdake** [comment]
@ericvn this is a P0 for 1.2.  It looks like you have the work under control.  If you need any help, please reach out.  It seems like from the other issue tracker, prow may need attention as well.  Could you comment?

Cheers
-steve

**Comment by icygalz** [comment]
hmm most of our prow testing/build is using this image:
gcr.io/istio-testing/istio-builder:v20181008-db31a9fd
Which has: go version go1.10.4 linux/amd64

I will need to figure out which tests are using go1.11 instead.. The last time I tried to upgrade the image to use go.1.12(with KinD package included), e2e-simpleTests test was failing. Let me create a new image with go.1.12(without KinD package) and update the prow tests and see the impact.
Do we want to update ALL branches' tests to use go.1.12? or only specific branch?

**Comment by ericvn** [comment]
@icygalz I am assuming that we need to do `master` first and then cherry-pick back to 1.2 as this issue has a ``1.2 milestone.

**Comment by ericvn** [comment]
@icygalz The failure I saw with prow tests was I had made a Makefile change to `GO_VERSION_REQUIRED:=1.10` making it 1.12. It failed all prow tests IIRC (as prow was at 1.10.4 as you mention).

**Comment by geeknoid** [comment]
We need to have everything consistently building with and single compiler suite. In particular, all tests must be built with the same tool suite as the product. I think that means we want everything we do in release-1.2 and in master in every repo to be using Go 1.12.5

**Comment by ericvn** [comment]
With a few PRs: https://github.com/istio/istio/pull/14610, https://github.com/istio/test-infra/pull/1310, and https://github.com/istio/test-infra/pull/1314, I believe we are now using Golang 1.12 everywhere in the _master_ branch.

To get things using Golang 1.12.5 in the _release-1.2_ branch I think we need to cherry-pick https://github.com/istio/istio/pull/14610 forward so tests will pass and then we can merge https://github.com/istio/test-infra/pull/1298. 

@linsun @fpesce I see this is labeled a release 1.2 item. Should we move forward with getting the PRs merged (in the correct order) in release 1.2?

**Comment by linsun** [comment]
Given how close we are to release 1.2, I'm in favor of not porting this to 1.2 unless we know of a user impact.  I think it is great we have got this fixed in master!!!

@fpesce pls chime in if you disagree. :)

**Comment by howardjohn** [comment]
@ericvn I don't think we have 1.12 everywhere yet, our releases are still in 1.10

```
$ dk run gcr.io/istio-release/pilot:master-20190610-09-15 version
version.BuildInfo{Version:"master-20190610-09-15", GitRevision:"b034753e104adff9faad7969d9246a2157fa6bd1-dirty", User:"root", Host:"6194d580-8b60-11e9-a7d1-0a580a2c6405", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.7-989-gb034753"}
```

It would be great if we could get master builds built on 1.12 so we can get some testing before 1.3. And distroless (not related to this)

**Comment by sdake** [comment]
The main advantage of golang 1.12 is improved performance.  The main disadvantage of moving to golang 1.12 for 1.2 is no serious testing has been done with Istio running with the golang 1.12 toolchain.

Doesn't seem to be worth the risk to me.

Cheers
-steve

**Comment by ericvn** [comment]
@howardjohn Let me look into this one some more based on what you posted. I'm wondering about the GitTag. Need to investigate part of the build more.

**Comment by howardjohn** [comment]
GitTag one is tracked in https://github.com/istio/istio/issues/13602. Should we fixed as well though.

**Comment by ericvn** [comment]
OK. Found the issue. The image we thought should have Golang 1.12 in it for the build doesn't so will try moving the build again (but first in staging branch). As this issue now seems to me master/1.3, I'll lower the priority a bit to get some of the 1.2 doc/testing done.

**Comment by duderino** [comment]
@ericvn are you saying that the build image we use for the 1.2 branch does not use Golang 1.12 so this isn't a blocker for the 1.2 release?

What version of Golang is used for the build images used for the 1.2 branch?   1.11?

**Comment by ericvn** [comment]
@duderino Right now, the images used to build both the master branch and the release-1.2 branches use Golang 1.10.4. We moved the master branch to an image that should have contained Golang 1.12.5, but because of some of the issues with the CI pipeline, that is no longer the case. As John noted above, master is still using Golang 1.12.5. We have created a new build image and today we are going to try building the current master code in a staging branch. If tests and builds pass, we will attempt to merge that into master. I hope that makes sense. Then we could entertain moving the release-1.2 branch if so desired.

**Comment by ericvn** [comment]
https://github.com/istio/istio/pull/14757 was created (using prow-staging brach) to build/test.

**Comment by duderino** [comment]
@ericvn thanks for the update

Both 1.2 release managers (@linsun and @fpesce) voiced concern about updating 1.2 to go 1.12 so close to the release.  We thought we were in a bind that we were testing with 1.12 but building with an earlier version.  So the fact that 1.2 still uses an older version of go is great news.

Please do not update go for the 1.2 branch.  This is a great thing for master and, in the future, 1.3.

I'm re-prioritizing accordingly

**Comment by ericvn** [comment]
@duderino I believe we are testing with Golang 1.12.5 and building with Golang 1.10.4 in release-1.2 branch (have to go back and verify that). 

As of earlier this morning with https://github.com/istio/test-infra/pull/1334, we should be totally on Golang 1.12.5 in master.

**Comment by icygalz** [comment]
prow uses go1.10.4 for building and testing release-1.2.
I am not sure about circleci.

**Comment by ericvn** [comment]
circleci uses Golang 1.12.5 in both master and release-1.2.

**Comment by ericvn** [comment]
Based on the @duderino comment that this should be done in `master` and we shouldn't do this in `release-1.2` (even though the milestone target is still 1.2), I will close this issue.

Note that the work done in the PRs was to update the builds to using Golang 1.12.5, but does not include migrating things to using go modules during the builds instead of vendor. There are other on-going discussions like https://github.com/istio/istio/issues/14795 which discuss this issue.

Please re-open if you think there is additional work needed in this issue.
