### ISSUE TITLE
istioctl: Potentially misspelled annotation warning

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#14427]
Run `istioctl kube-inject -f file.yaml > injected` and I see first line:

`2019-05-29T15:11:25.765384Z     warn    Potentially misspelled annotation 'sidecar.istio.io/bootstrapOverride' with value 'istio-custom-bootstrap-config' encountered`

Two problems:
* shouldn't this warning go to stderr?
* We need to update the list of known annotations. I know the one above is missing, but there are more too, like proxyCPU. Should be a simple grep of the injection template

**Comment by esnible** [comment]
Do we know what all the annotations are?  https://github.com/istio/istio/issues/12940 is supposed to be tracking the creation of a master list.
