### ISSUE TITLE
UX Improvement: Add a home dashboard to grafana

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#14429]
Right now when users open grafana there is pretty much a blank page. We can add a home dashboard that at least lists all the istio dashboards so they don't have to dig through home > dashboards > istio. We are all probably mostly familiar with this by now, but I have seen people, including myself, confused by this.

One example: https://istio.teststats.cncf.io/d/8/dashboards?refresh=15m&orgId=1

**Comment by douglas-reid** [comment]
Home dashboards are per-user or per-org, as I understand it. And there is no good way to set them via the provisioning process, meaning that it would require a series of API calls at grafana startup to star the appropriate dashboard and then set it as the org default.

**Comment by howardjohn** [comment]
That makes sense. if that is the case this probably isn't feasible so you can close it if you want

**Comment by douglas-reid** [comment]
OK. I'll close it for now, but continue to think about better UX for the dashboard consumption.
