### ISSUE TITLE
Random ECONNRESET Errors

### ISSUE THREAD

**Issue by aaronmell** [istio/istio#14430]
**Bug description**
Our application logs are seeing random ECONNRESET Errors when sending traffic through the proxies. In environments not using the istio proxy, we do not see any errors. The proxy logs do not show any issues. I believe we are creating a long lived connection here. 

Application logs are as follows
{"msg":"read ECONNRESET","data":{"message":"read ECONNRESET","stack":"Error: read ECONNRESET\n at TLSWrap.onread (net.js:622:25)","awsError":{"message":"read ECONNRESET","errno":"ECONNRESET","code":"NetworkingError","syscall":"read","region":"us-west-2","hostname":"sqs.us-west-2.amazonaws.com","retryable":true,"time":"2019-05-29T14:40:16.663Z"}}

We also see
Error: getaddrinfo EAI_AGAIN sqs.us-west-2.amazonaws.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Istio 1.1.4
K8 1.10.13

**How was Istio installed?**
Using helm 

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS EKS

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by aaronmell** [comment]
WE think this might be related to running 1.10 and kube-dns. Planning to upgrade and test.

**Comment by linsun** [comment]
good, pls keep us posted. I don't think k8s 1.10 is supported now with istio 1.1 - https://istio.io/docs/setup/kubernetes/prepare/platform-setup/

**Comment by Vespinosa** [comment]
Any update? We're seeing the same error using envoy with "ALLOW_ANY". `K8s 1.11.8`, `Istio 1.1.8`.

**Comment by aaronmell** [comment]
We have upgraded everything to run on on 1.12 and CoreDns. We haven't see the issue occur again.

**Comment by aaronmell** [comment]
Looks like I was mistaken, we are still seeing EAI_AGAIN Errors in the logs.  I double checked, and its only happening in environments where istio has been turned on.

**Comment by howardjohn** [comment]
> We also see
> Error: getaddrinfo EAI_AGAIN sqs.us-west-2.amazonaws.com:443
> at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)

This means DNS lookup is failing, right? DNS traffic is not capture by envoy generally I think, unless its using TCP for the lookups

**Comment by lodotek** [comment]
Having the same issue. @aaronmell did you ever figure this out?

**Comment by aaronmell** [comment]
@lodotek I think they went away when we upgraded to 1.2
