### ISSUE TITLE
Granular access log control

### ISSUE THREAD

**Issue by MrSaints** [istio/istio#14433]
**Describe the feature request**

Since Istio 1.1(?), Envoy access logs has been disabled by default through `accessLogFile` for performance reasons. If Helm is used, it can be enabled **globally** by changing `global.proxy.accessLogFile`.

This configuration however, affects all proxies. It would be ideal to be able to enable access logging for specific pods.

**Describe alternatives you've considered**

At the moment, we are ingesting our logs with Stackdriver, and frankly, it is introducing a lot of noise. We can filter most of it out through exclusions. The `accessLogFile` does not seem to be too easy to change per proxy as it is set in a global `ConfigMap`.

**Additional context**

Using Helm template, and currently on Istio 1.1.5.

**Comment by douglas-reid** [comment]
Related:
- https://github.com/istio/istio/issues/11582
- https://tinyurl.com/y3lnlf7n

**Comment by Demonian** [comment]
@douglas-reid Any news on this?

**Comment by douglas-reid** [comment]
Working through the proposal now.  I'm OOO for awhile, but hopefully there will be concrete news to share soonish.

**Comment by fcantournet** [comment]
This would be very valuable for us too : I'd like to get access logs from the ingress gateways but not the rest of the mesh proxies. Currently I'd have to fork the chart to do that :/

**Comment by cacedo** [comment]
> This would be very valuable for us too : I'd like to get access logs from the ingress gateways but not the rest of the mesh proxies. Currently I'd have to fork the chart to do that :/

Hi @fcantournet could you share how to enable access logs on ingress gateways by updating Istio Charts? Thanks!

**Comment by douglas-reid** [comment]
Please take a look at: https://github.com/istio/istio/wiki/EnvoyFilter-Samples#tracing-and-access-logging

**Comment by cacedo** [comment]
Is there an example of EnvoyFilter for Istio 1.2 specification?

**Comment by douglas-reid** [comment]
This is not an easy way to accomplish in 1.2.

Closing for now, as there is a way via EnvoyFilters to achieve this goal.
