### ISSUE TITLE
Support fractional mirroring

### ISSUE THREAD

**Issue by jwendell** [istio/istio#14437]
It seems Envoy already [supports it](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto.html#route-routeaction-requestmirrorpolicy), but Istio doesn't expose it yet.

**Comment by brianwolfe** [comment]
@jwendell @rshriram 

For many of the other percent fields in istio, we use percentage as a floating point to permit small percentages. #16939 added `mirror_percent` as a UInt, making it impossible to mirror less than 1% even though Envoy supports down to 1 / 1e6. Would it be reasonable for me to create a `mirror_percentage` field for this and deprecating `mirror_percent`?
