### ISSUE TITLE
Need API be override instance weights and tags

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1443]
@rshriram commented on [Fri May 19 2017](https://github.com/istio/old_pilot_repo/issues/798)

Envoy supports weighted routing within a cluster as well. We need to expose an API to allow users to set such weights as well as add additional tags to the instances through an API. There are use cases where the tags attached to a pod change frequently and a single pod can host multiple different tags (1000s of tags) [imagine a content cache]. 

An internal use case came up, where both pods and external entities need to be able to specify the set of tags that each pod serves. Also, there is a need to assign rank (or weights) to pods based on certain processing costs, and then send traffic to the pod with lowest/highest weight, within an envoy cluster. While tags can be manifested as k8s labels, we do not know the overhead of adding or removing 1000s of labels per pod very frequently. Even if it's low, if services want to be able to control the tags assigned to their pods at runtime via APIs, they would have to interact with k8s runtime (which creates platform dependence)

Two options: the manager calls out to external entities for rewriting routes (requires others to understand our data model) or it exposes an API for others to just specify the additional info, while we apply the overrides. There are trade offs and operational complexities in both cases. 

cc @louiscryan @kyessenov 

---

@rshriram commented on [Sun May 21 2017](https://github.com/istio/old_pilot_repo/issues/798#issuecomment-302952263)

Referring to https://github.com/istio/proxy/issues/278

---

@kyessenov commented on [Fri Nov 03 2017](https://github.com/istio/old_pilot_repo/issues/798#issuecomment-341846351)

Issue moved to [istio/istio #1442](https://github.com/istio/istio/issues/1442) via [**ZenHub**](https://www.zenhub.com/)

**Comment by louiscryan** [comment]
ServiceEntry is likely to be the API we expose for this. We can also investigate annotating pods / services in K8S to control this behavior without an API.
