### ISSUE TITLE
"istioctl uninject"

### ISSUE THREAD

**Issue by esnible** [istio/istio#14435]
This command provides the inverse of "istioctl kube-inject -f <file>".

This command is used to prevent Istio from adding a sidecar.  It works on Deployment .yaml, allowing an operator to `istioctl uninject -f <file> | kubectl apply -f -` to prevent Istio from attaching sidecars.  Used for debugging or for creating successful deployments for middleware not yet compatible with Istio.

Implementation: This command reads a Kubernetes deployment YAML.  For any Deployments we delete any containers where `.spec.template.spec.containers[*].name` is "istio-proxy", "istio-init", or "enable-core-dump".  We delete any volumes where `.spec.template.spec.volumes[*].name` is "istio-envoy" or "istio-certs".  We add .spect.template.metadata.annotation `sidecar.istio.io/inject: false` to default the auto-injector in case it is present.

cc: @linsun

**Comment by linsun** [comment]
+1 on this, this will be very helpful for troubleshooting.  I'd like to have this in 1.3 if we could.

**Comment by clyang82** [comment]
@linsun @esnible 
I think 2 cases we need to consider in this feature:
1. With Istio: When the namespace is configured as `istio-injection=enabled`, if the app is not desired to inject the sidecar, `istioctl uninject -f <file> | kubectl apply -f -` can help.
2. Without Istio: When uninstall the istio, use `istioctl uninject -f <file> | kubectl apply -f -` to uninstall the data plane.

WDYT?

**Comment by esnible** [comment]
For case 1 there are two sub-cases.  One case is where the auto-injector is used, the other case is where BOTH the auto-injector and manual injector are used.  We can eliminate work done by manual inject by removing sidecars.  We can eliminate work done by auto-inject by adding annotation.

To uninstall the data plane, we can first uninstall sidecars using the steps required for case 1, then we can do `kubectl delete ns istio-system`.

**Comment by clyang82** [comment]
Thanks @esnible for your comments. I have checked the implementation of `kube-inject` which is get  the injection information from sidecar-injector-configmap. for the uninject, in some cases, the sidecar-injector-configmap does not exist. so we have to hardcode to add the logic as you described in `implementation` section.  right?

**Comment by linsun** [comment]
@clyang82 I agree with the comments from @esnible.  When I initially think of this WI, I didn't think of uninstall istio scenario but you added.  I was mainly more for manual injection where manual injection doesn't work and users want to quickly undo it.  Obviously, this can be also applied to auto injection.

I would prioritize the scenarios that has istio higher, because if users are removing istio completely, they can also do a roll update of all their app deployments.  I would assume they have that somewhere in git recorded.

**Comment by esnible** [comment]
@clyang82 It would be difficult to write a tool that understood the ConfigMap and was able to "reverse" the changes.

For Istio 0.1 through 1.2, we add sidecars named istio-inject and istio-proxy.  I propose we code an algorithm that removes pods named "istio-inject" and "istio-proxy" from a pod.  We should also remove volumes added by Istio for TLS certificates because if Istio is deleted those secrets will no longer be present.

In addition to remove things added by Istio we should add an annotation to prevent the auto-injector from restoring the Istio pieces if it is running.  If the injector is not running the extra annotation will not hurt.

**Comment by clyang82** [comment]
> @clyang82 I agree with the comments from @esnible. When I initially think of this WI, I didn't think of uninstall istio scenario but you added. I was mainly more for manual injection where manual injection doesn't work and users want to quickly undo it. Obviously, this can be also applied to auto injection.
> 
> I would prioritize the scenarios that has istio higher, because if users are removing istio completely, they can also do a roll update of all their app deployments. I would assume they have that somewhere in git recorded.

Thanks for your comments. Let me implement the scenarios with istio as high priority firstly.

**Comment by clyang82** [comment]
This feature was implemented.
