### ISSUE TITLE
Make istioctl kube-inject operation idempotent

### ISSUE THREAD

**Issue by SataQiu** [istio/istio#14445]
**Describe the feature request**

Make istioctl kube-inject operation idempotent!
Now, repeated injection produces invalid yaml because of duplicate name, such as duplicate `istio-proxy` container name.
If we support idempotent operation, it will address this issue.

**Describe alternatives you've considered**

**Additional context**

**Comment by linsun** [comment]
@irisdingbj this is a very reasonable request and what user is expecting kube-inject to do.  Could you check if we could detect the proxy is already injected and skip the kube-inject in this case?

**Comment by howardjohn** [comment]
```
gke ~/go/src/istio.io/file-envoy (master)*
$ ik2 kube-inject -f ~/kube/shell/shell.yaml | wc -l
177
gke ~/go/src/istio.io/file-envoy (master)*
$ ik2 kube-inject -f ~/kube/shell/shell.yaml | ik2 kube-inject -f - | wc -l
308
gke ~/go/src/istio.io/file-envoy (master)*
$ ik2 kube-inject -f ~/kube/shell/shell.yaml | ik2 kube-inject -f - | ik2 kube-inject -f - | wc -l
439
```

Looks like it doesn't detect it

**Comment by irisdingbj** [comment]
Yes, I agree this request is very reasonable. start to look at it.

**Comment by irisdingbj** [comment]
https://github.com/istio/istio/pull/14518
