### ISSUE TITLE
routeconfig for http(s)- named ports

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1445]
@akshaychitneni commented on [Fri Aug 04 2017](https://github.com/istio/old_pilot_repo/issues/992)

I am trying to see if communication with podIP works between replica containers in a single deployment with istio. I see the following issue with http named ports.
For communication with podIP, when I use http- named ports, istio proxy uses httpproxy to filter requests. This is using envoy rds api to get route config. For example, where service-one pod communicates with service-two pod using podIP, route config used by envoy is

"name": "service-two.default.svc.cluster.local|http-status",
     "domains": [
      "service-two:80",
      "service-two",
      "service-two.default:80",
      "service-two.default",
      "service-two.default.svc:80",
      "service-two.default.svc",
      "service-two.default.svc.cluster:80",
      "service-two.default.svc.cluster",
      "service-two.default.svc.cluster.local:80",
      "service-two.default.svc.cluster.local",
      "10.0.0.28:80",
      "10.0.0.28"
     ],
     "routes": [
      {
       "prefix": "/",
       "cluster": "out.c3143c03f62f0275a228bee93ae7460fad6a2182"
      }

This doesn't have the pod ip in the domain for inbound traffic to this proxy, hence proxy rejects the request.
However, when using non http named port, it uses tcp proxy which allows the inbound traffic and communication looks good. 

So, can we have PodIP in the config?

Also, I am using --includeIPRanges to include only serviceIP range when starting the proxy. I see the range is being applied only to outbound rules in the iptables. Can this be applied to inbound rule to bypass proxy for requests having podIP in the destination? 

Thanks!

---

@kyessenov commented on [Thu Aug 17 2017](https://github.com/istio/old_pilot_repo/issues/992#issuecomment-322987928)

This looks like outbound config actually (see out cluster). The inbound config binds to POD_IP. We don't allow direct access to POD_IP:PORT pairs for outbound requests since pods are churning a lot faster than services. There's an issue for headless TCP services where this restriction might be relaxed.

**Comment by rshriram** [comment]
Echoing kuat's response:
This looks like outbound config actually (see out cluster). The inbound config binds to POD_IP. *We don't allow direct access to POD_IP:PORT pairs for outbound requests since pods are churning a lot faster than services.*
