### ISSUE TITLE
Node Agent is broken

### ISSUE THREAD

**Issue by lei-tang** [istio/istio#14472]
**Bug description**
The user guide https://istio.io/docs/tasks/security/vault-ca/ succeeds on the release istio-release-1.1-20190517-09-15 but fails on istio-release-1.2-20190528-09-16 and Istio 1.2.0-rc.0 due to Node Agent crashes after install Istio. Node Agent crash log is attached. This bug may also occur on release-1.1 branch and master branch.

Update 5-29-2019: Node Agent does not crash on istio-release-1.2-20190529-09-16.
Update 6-11-2019: Node Agent crash on Istio 1.2.0-rc.0.

**Expected behavior**
The user guide should work on Istio 1.2.0-rc.0 and istio-release-1.2-20190528-09-16.

**Steps to reproduce the bug**
Follow the steps in https://istio.io/docs/tasks/security/vault-ca/ .

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**
Helm.

**Environment where bug was observed (cloud vendor, OS, etc)**
Linux

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x ] Security
[x] Test and Release
[x ] User Experience

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by lei-tang** [comment]
The error log on Node Agent:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x6a8afb]

goroutine 1 [running]:
crypto/x509.(*CertPool).AddCert(0x0, 0xc4200eeb00)
        /usr/local/go/src/crypto/x509/cert_pool.go:95 +0x6b
crypto/x509.(*CertPool).AppendCertsFromPEM(0x0, 0xc420142480, 0x41d, 0x480, 0x20)
        /usr/local/go/src/crypto/x509/cert_pool.go:128 +0x13d
istio.io/istio/security/pkg/nodeagent/caclient/providers/vault.createVaultTLSClient(0xc42004403b, 0x1a, 0xc420142480, 0x41d, 0x480, 0x0, 0x250d6c0, 0x7)
        /workspace/go/src/istio.io/istio/security/pkg/nodeagent/caclient/providers/vault/client.go:117 +0x3a8
istio.io/istio/security/pkg/nodeagent/caclient/providers/vault.NewVaultClient(0x1, 0xc420142480, 0x41d, 0x480, 0xc42004403b, 0x1a, 0xc42004204b, 0xa, 0xc4200440a0, 0x15, ...)
        /workspace/go/src/istio.io/istio/security/pkg/nodeagent/caclient/providers/vault/client.go:58 +0x153
istio.io/istio/security/pkg/nodeagent/caclient.NewCAClient(0xc420044008, 0x1a, 0xc42004202c, 0x7, 0x166e101, 0xc420142480, 0x41d, 0x480, 0xc42004403b, 0x1a, ...)
        /workspace/go/src/istio.io/istio/security/pkg/nodeagent/caclient/client.go:53 +0x339
istio.io/istio/security/pkg/nodeagent/secretfetcher.NewSecretFetcher(0x0, 0xc420044008, 0x1a, 0xc42004202c, 0x7, 0x401, 0xc420142480, 0x41d, 0x480, 0xc42004403b, ...)
        /workspace/go/src/istio.io/istio/security/pkg/nodeagent/secretfetcher/secretfetcher.go:130 +0x2c0
main.newSecretCache(0x1906432, 0x15, 0x1910563, 0x1c, 0x0, 0x0, 0x0, 0x0, 0xc420044008, 0x1a, ...)
        /workspace/go/src/istio.io/istio/security/cmd/node_agent_k8s/main.go:175 +0x2eb
main.glob..func1(0x24f9940, 0x252af28, 0x0, 0x0, 0x0, 0x0)
        /workspace/go/src/istio.io/istio/security/cmd/node_agent_k8s/main.go:149 +0x167
istio.io/istio/vendor/github.com/spf13/cobra.(*Command).execute(0x24f9940, 0xc4200a8190, 0x0, 0x0, 0x24f9940, 0xc4200a8190)
        /workspace/go/src/istio.io/istio/vendor/github.com/spf13/cobra/command.go:762 +0x468
istio.io/istio/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x24f9940, 0x0, 0xc4201ab400, 0x24f9a90)
        /workspace/go/src/istio.io/istio/vendor/github.com/spf13/cobra/command.go:852 +0x30a
istio.io/istio/vendor/github.com/spf13/cobra.(*Command).Execute(0x24f9940, 0xc420589f58, 0x1)
        /workspace/go/src/istio.io/istio/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
        /workspace/go/src/istio.io/istio/security/cmd/node_agent_k8s/main.go:368 +0x9e8

**Comment by lei-tang** [comment]
The crush log is similar to the one in https://github.com/docker/go-connections/issues/43, which is caused by "ca-certificates package wasn't installed".  Recent commits on release 1.2 removed ca-certificates package on Node Agent, which may cause the Node Agent crash. The PR https://github.com/istio/istio/pull/14474 is created to diagnose this problem.

**Comment by lei-tang** [comment]
A potentially related issue: https://github.com/istio/istio/issues/14364

**Comment by lei-tang** [comment]
A potentially related issue: https://github.com/istio/istio/issues/14364

**Comment by lei-tang** [comment]
The user guide https://istio.io/docs/tasks/security/vault-ca/ succeeds on istio-release-1.2-20190529-09-16.

**Comment by lei-tang** [comment]
Update 6-11-2019: Node Agent crash on Istio 1.2.0-rc.0.

**Comment by howardjohn** [comment]
Merged into 1.2 via https://github.com/istio/istio/pull/14474

if this still needs work please reopen
