### ISSUE TITLE
add some tools to pilot image

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1447]
@andraxylia commented on [Mon Aug 28 2017](https://github.com/istio/old_pilot_repo/issues/1124)

Pilot image has nothing, some tools like ps, ls, etc are useful and do not take so much space.

**Comment by ldemailly** [comment]
should probably be a _debug vs non _debug images
- the non debug is just the binary, a tiny image
- the debug has an os base like proxy_debug

**Comment by ymesika** [comment]
Do you think that a debug image that is based on busybox would be enough?

**Comment by ldemailly** [comment]
not really for actual debugging - I guess @andraxylia can elaborate on what she would do connecting to pilot (that she can't do from the proxy sidecar) ?

**Comment by andraxylia** [comment]
We could use a pilot_debug base linux image to have same tools as proxy_debug images, otherwise it is pretty hard to do any troubleshooting. Similar to this, it installs dnsutils, netcat, tcpdump.

https://github.com/istio/proxy/blob/master/docker/Dockerfile.debug

**Comment by ldemailly** [comment]
with secure pilot there is now a sidecar image with pilot no ? so that can be the launch point for debugging the pilot pod ? do both need to have debug utils ?

**Comment by ldemailly** [comment]
I think we settled on from scratch for prod and debug having the ability to sudo apt-get

closing this
