### ISSUE TITLE
UX: istioctl register needs documentation for labels/annotations behavior

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1448]
@rshriram commented on [Tue Aug 29 2017](https://github.com/istio/old_pilot_repo/issues/1125)

Kubernetes endpoints objects do not support labels. 

`istioctl register svc ip port -l foo:bar` conveys the impression that labels are per endpoint, which is not true. Users need to be made aware that labels are per service and that they need to make sure all invocations of istioctl for the same service need to have identical labels (or that the labels are merged/*overwritten*).

This requires 
1. appropriately wording the usage printouts in the command
2. changing the option name to "service labels"
3. issuing appropriate warnings when labels are being overwritten
4. Docs explaining the caveats and limitations (no intelligent routing features)

This is a tracking issue for all of the tasks above.
cc @ldemailly @costinm

---

@ldemailly commented on [Tue Aug 29 2017](https://github.com/istio/old_pilot_repo/issues/1125#issuecomment-325711840)

having docs is always useful

it does apply the labels and annotations to the endpoints (and the service) so no for 2. (the kubernetes behavior can be explained/pointed to)

---

@rshriram commented on [Tue Aug 29 2017](https://github.com/istio/old_pilot_repo/issues/1125#issuecomment-325713459)

Endpoint objects do not have labels. Please see https://kubernetes.io/docs/api-reference/v1.7/#endpointport-v1-core
Labels are for the service. Without labels per endpoint, there is no smart routing in pilot. Its just load balancing stuff.

---

@rshriram commented on [Tue Aug 29 2017](https://github.com/istio/old_pilot_repo/issues/1125#issuecomment-325713737)

https://github.com/istio/pilot/blob/master/platform/kube/register.go#L129 as proof.. labels and annotations applied to the service object.

---

@ldemailly commented on [Tue Aug 29 2017](https://github.com/istio/old_pilot_repo/issues/1125#issuecomment-325714868)

https://github.com/istio/pilot/blob/master/platform/kube/register.go#L142

---

@kyessenov commented on [Tue Aug 29 2017](https://github.com/istio/old_pilot_repo/issues/1125#issuecomment-325715898)

What are service labels used for? AFAIK, we haven't been using them for anything in pilot.

---

@ldemailly commented on [Tue Aug 29 2017](https://github.com/istio/old_pilot_repo/issues/1125#issuecomment-325719184)

This is getting quite off topic but as we talked about yesterday (and I need to send an email summary) we need to not rely on pods exclusively and start looking for labels/annotations on services / endpoints

---

@ldemailly commented on [Sat Sep 16 2017](https://github.com/istio/old_pilot_repo/issues/1125#issuecomment-330004667)

need to add unit test (though probably first the e2e one), for unit test , ptr to makeTempClient in https://github.com/istio/pilot/issues/1233#issuecomment-329999170

**Comment by ldemailly** [comment]
the doc is https://istio.io/docs/reference/commands/istioctl.html#istioctl-register
it doesn't really say what the labels or annotations are for but they can be used in mixer rules

closing until #1302 gets resolved (mixer looking at pod labels)
