### ISSUE TITLE
Add a bot that performs initial triage

### ISSUE THREAD

**Issue by geeknoid** [istio/istio#14484]
Based on the user-checked item in a bug report, the bot can assign the right area label.

**Comment by douglas-reid** [comment]
Would such a bot triage this issue as well ;) ?

**Comment by geeknoid** [comment]
I've got it half written at this point. Through configuration, you specify
a set of regexes to match in the title or body, for a new issue or PR, and
if there are any matches, then the specified set of labels is applied. So
we can use it for initial triage, but potentially for other things too. For
example, I can auto-label feature requests vs. issues based on the template
the user chose.

**Comment by douglas-reid** [comment]
Cool. I was sorta making a joke about how we only consider issue triaged that have a `area` label and how this issue does not have an `area` label.

**Comment by geeknoid** [comment]
Done and working.
