### ISSUE TITLE
Documentation for Fault Injection Percentage is incorrect

### ISSUE THREAD

**Issue by stevelowery** [istio/istio#14489]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
The examples in the documentation for Fault Injection ( https://istio.io/docs/reference/config/networking/v1alpha3/virtual-service/#HTTPFaultInjection-Abort and https://istio.io/docs/reference/config/networking/v1alpha3/virtual-service/#HTTPFaultInjection-Delay) is misleading.  It gives examples for for setting faults for 1 out of every 1000 requests and lists the value at 0.001, but the percentage documentation (https://istio.io/docs/reference/config/networking/v1alpha3/virtual-service/#Percent) says the value should be between 0.0 and 100.0.

I was attempting to do some fault injection with a value of 0.25, which I believed to be 25%, but it was almost never being hit.  When I changed it to 25.0, it worked ~25% of the time.  

If the 0.001 were changed to 0.1, that'd clear up any confusion users might have.

**Describe alternatives you've considered**

**Additional context**

**Comment by linsun** [comment]
@frankbu can you look at this?

**Comment by frankbu** [comment]
Fixed by https://github.com/istio/api/pull/886

**Comment by linsun** [comment]
Thanks @frankb!  @stevelowery, pls check the preliminary.istio.io doc and reopen if this is not fixed.
