### ISSUE TITLE
Flaky Test: TestProxyTracing

### ISSUE THREAD

**Issue by ozevren** [istio/istio#14492]
https://testgrid.k8s.io/istio-postsubmits-master#integration-k8s-tests&sort-by-flakiness=
https://prow.k8s.io/view/gcs/istio-prow/logs/istio-integ-k8s-tests-master/245

**Comment by douglas-reid** [comment]
This looks resolved?  https://testgrid.k8s.io/istio-postsubmits-master#integ-telemetry-k8s-postsubmit-tests&sort-by-flakiness=

Green for the past 7 days. Closing for now.
