### ISSUE TITLE
Flaky Test: istio.io/istio/tests/integration/mixer/policy.TestRateLimiting_RedisQuotaFixedWindow

### ISSUE THREAD

**Issue by ozevren** [istio/istio#14494]
https://testgrid.k8s.io/istio-postsubmits-master#integration-k8s-tests&sort-by-flakiness=
https://prow.k8s.io/view/gcs/istio-prow/logs/istio-integ-k8s-tests-master/233

**Comment by gargnupur** [comment]
Don't see this as flaky in https://testgrid.k8s.io/istio-postsubmits-master#integ-mixer-k8s-postsubmit-tests&sort-by-flakiness=. But the number of results are really less to make a proper decision.
Will wait for a day or two more to close this bug.

**Comment by ozevren** [comment]
The Postsubmit page is missing entries because of a missing JUnit report
creation step. There might still be some failures. While not as clean as
the postsubmit, presubmit is showing some failures:
https://testgrid.k8s.io/istio-presubmits-master#integ-mixer-k8s-presubmit-tests&sort-by-flakiness=

**Comment by gargnupur** [comment]
Closing as fix is in...
