### ISSUE TITLE
NodePort conflicts with `kubectl expose`d services

### ISSUE THREAD

**Issue by kbruner** [istio/istio#14499]
(This is used to report product bugs, please visit <https://discuss.istio.io> for questions on using Istio)

**Bug description**

The managed and mandatory `default-http-backend` service deployed in GKE clusters apparently randomly picks a NodePort at start time in the lower 30000 range.  (I cannot find any documentation on this, but I spot-checked a dozen different clusters otherwise created the same way and they all had different port numbers.  I even deleted the `Service` resource in one and it was immediately recreated with a *different* node port than it had had previously.  I assume they're doing the equivalent of a `kubectl expose`, which uses the allocation range 30000-32767 by default)

In one cluster today, the `default-http-backend` service randomly got a `nodePort` value of 31390, so when the `istio-ingressgateway` was being deployed, it failed:

`The Service "istio-ingressgateway" is invalid: spec.ports[2].nodePort: Invalid value: 31390: provided port is already allocated`

We deploy Istio using automation into at least a dozen fresh GKE clusters a day and this is the first time it's failed because of this, but obviously, it's a serious issue which GKE is unlikely to address.  I'm not sure what the best/reasonable solution would be here, except not to use nodePorts in the `expose` range, as that carries the risk of conflicts not just with this service in GKE but in virtually any cluster.

For now I'm overriding the node ports in that range in our automation script.

**Expected behavior**

The install does not fail because of a node port collision.

**Steps to reproduce the bug**

It is random, but if you deploy `istio-ingressgateway` to enough GKE clusters, you'll hit it sooner or later.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```
$ istioctl version
version.BuildInfo{Version:"1.1.6", GitRevision:"04850e14d38a69a38c16c800e237b1108056513e-dirty", User:"brew", Host:"Mojave-2.local", GolangVersion:"go1.12.5", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.6"}
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T19:44:19Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.7-gke.10", GitCommit:"8d9b8641e72cf7c96efa61421e87f96387242ba1", GitTreeState:"clean", BuildDate:"2019-04-12T22:59:24Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

```
$ helm template install/kubernetes/helm/istio-init --name istio-init \
        --namespace istio-system \
        --set gateways.istio-egressgateway.enabled=true \
        --set gateways.istio-ingressgateway.autoscaleMin=2 \
        --set gateways.istio-ingressgateway.enabled=true \
        --set global.disablePolicyChecks=false \
        --set global.mtls.enabled=true \
        --set global.outboundTrafficPolicy.mode=REGISTRY_ONLY \
        --set global.proxy.accessLogFile=/dev/stdout \
        --set global.proxy.statusPort=0 \
        --set grafana.enabled=true \
        --set kiali.createDemoSecret=true \
        --set kiali.dashboard.grafanaURL=http://grafana.istio-system.svc.cluster.local:3000 \
        --set kiali.dashboard.jaegerURL=http://jaeger.istio-system.svc.cluster.local:80 \
        --set kiali.enabled=true \
        --set mixer.adapters.stdio.enabled=true \
        --set mixer.policy.autoscaleMin=2 \
        --set mixer.telemetry.autoscaleMin=2 \
        --set pilot.autoscaleMin=2 \
        --set sidecarInjectorWebhook.enableNamespacesByDefault=true \
        --set sidecarInjectorWebhook.rewriteAppHTTPProbe=false \
        --set tracing.enabled=true > istio-init.yaml
$ kubectl apply -f istio-init.yaml
(wait for CRDs)
$ helm template install/kubernetes/helm/istio --name istio \
        --namespace istio-system \
        --set gateways.istio-egressgateway.enabled=true \
        --set gateways.istio-ingressgateway.autoscaleMin=2 \
        --set gateways.istio-ingressgateway.enabled=true \
        --set global.disablePolicyChecks=false \
        --set global.mtls.enabled=true \
        --set global.outboundTrafficPolicy.mode=REGISTRY_ONLY \
        --set global.proxy.accessLogFile=/dev/stdout \
        --set global.proxy.statusPort=0 \
        --set grafana.enabled=true \
        --set kiali.createDemoSecret=true \
        --set kiali.dashboard.grafanaURL=http://grafana.istio-system.svc.cluster.local:3000 \
        --set kiali.dashboard.jaegerURL=http://jaeger.istio-system.svc.cluster.local:80 \
        --set kiali.enabled=true \
        --set mixer.adapters.stdio.enabled=true \
        --set mixer.policy.autoscaleMin=2 \
        --set mixer.telemetry.autoscaleMin=2 \
        --set pilot.autoscaleMin=2 \
        --set sidecarInjectorWebhook.enableNamespacesByDefault=true \
        --set sidecarInjectorWebhook.rewriteAppHTTPProbe=false \
        --set tracing.enabled=true > istio.yaml
$ kubectl apply -f istio.yaml
```

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE, master/node version v1.12.7-gke.10

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[x ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
If it helps, you can set it in Helm as well: https://github.com/istio/istio/blob/8476158e82721ec4929e7071eb85f26b85189241/install/kubernetes/helm/istio/charts/gateways/values.yaml#L67

**Comment by kbruner** [comment]
Actually, because nodePorts are limited to the same range used by `kubectl expose`, there's no way to get them to a "safe" range, at least not in a managed service like GKE.  (Of course, if it weren't a managed service, we wouldn't have `default-http-backend` forced on us on a random port in the first place.)

```
The Service "istio-ingressgateway" is invalid: spec.ports[1].nodePort: Invalid value: 29380: provided port is not in the valid range. The range of valid ports is 30000-32767
```

**Comment by howardjohn** [comment]
@kbruner any ideas how we can prevent this conflict then? It seems even if you configure it yourself you are still in trouble since the default-http-backend could chooes that port? Or is that service created once at cluster creation, so you could see what it gets set to and then configure Istio to use a different port?

**Comment by kbruner** [comment]
Currently, in my cluster build automation, I grab the current `nodePort` for `default-http-backend`, compare it to the list of nodePorts `istio-ingressgateway` is trying to use, and if there's a collision, run `kubectl delete svc -n kube-system default-http-backend`.  GKE will immediately recreate it with a new, random port.  This is far from ideal, obviously.

Without having GKE restrict the range of ports they can assign to their obligatory, managed services that use NodePorts or make those services optional/configurable, I don't know that there is a reliable workaround.  I do have to wonder how they manage this in their own managed Istio add-on.

**Comment by kbruner** [comment]
@howardjohn Oh, my brain just kicked in.  One workaround, unless the nodePorts need to be hardcoded for some reason, would be just not to add the `nodePort` explicitly in the service spec.  K8s will assign them randomly out of the pool.

**Comment by howardjohn** [comment]
@kbruner that seems like the best workaround. I am not sure its something we should do on Istio by default for consistency/documentation reasons, but certainly useful for cases like yours.

Does that seem right to you or is there some action we should take?
