### ISSUE TITLE
kind-simpleTest is faling in post submit.

### ISSUE THREAD

**Issue by ozevren** [istio/istio#14490]
https://prow.k8s.io/view/gcs/istio-prow/logs/istio-kind-simpleTest-master/129
https://testgrid.k8s.io/istio-postsubmits-master#kind-simpleTest-master

**Comment by ozevren** [comment]
@icygalz, I think you've created this test, right?

**Comment by icygalz** [comment]
yes, i created that test... It works when I run the test locally on my workstation but not on prow. I will look into again when i have some cycle. This is not blocking anything right?

**Comment by ozevren** [comment]
I don't believe so, but I want to make sure this is tracked correctly. I am going to assign this to you and lower its priority then.

Thanks

**Comment by howardjohn** [comment]
This is fixed now
