### ISSUE TITLE
Is isto an alternative to apigee?

### ISSUE THREAD

**Issue by rsoika** [istio/istio#14507]
It's just a question: isn't isto an alternative to apigee? Maybe it should be listed at
https://alternativeto.net/software/apigee/
I did not hear about the project until I found this [article on d-zone](https://dzone.com/articles/the-rise-of-service-mesh-architecture).

**Comment by howardjohn** [comment]
I am not very familiar with apigee but I don't think Istio is necessarily an alternative to apigee, although there is some overlap. See https://github.com/apigee/istio-mixer-adapter for example. I believe API management is typically seen as a layer above Istio, this article may explain a bit more https://itnext.io/api-management-and-service-mesh-e7f0e686090e.

If you have any other questions please direct them to https://discuss.istio.io, we try to limit the GH issues to actionable bugs/feature requests so we don't get lost in the noise
