### ISSUE TITLE
Flaky Test: TestEnvoyRDSProtocolError

### ISSUE THREAD

**Issue by ozevren** [istio/istio#14504]
https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/14478/istio-unit-tests-master/1138

**Comment by nmittler** [comment]
@ozevren I don't see any flakes on testgrid: https://k8s-testgrid.appspot.com/istio-presubmits-master#unit-tests

I also can't reproduce locally. Recommend closing this or moving it out of the 1.2 milestone.

**Comment by ozevren** [comment]
[](url)
