### ISSUE TITLE
Flaky Test: istio.io/istio/mixer/test/client/quota_cache.TestQuotaCache

### ISSUE THREAD

**Issue by ozevren** [istio/istio#14500]
https://testgrid.k8s.io/istio-postsubmits-master#unit-tests&sort-by-flakiness=
https://prow.k8s.io/view/gcs/istio-prow/logs/istio-postsubmit-master/145

**Comment by douglas-reid** [comment]
```
--- FAIL: TestQuotaCache (7.35s)
quota_cache_test.go:113: failed to find expected stats: stats http_mixer_filter.total_remote_quota_prefetch_calls does not match. expected vs actual: 1 vs 2
FAIL
FAIL	istio.io/istio/mixer/test/client/quota_cache	7.368s
```

This seems to suggest that perhaps we should be checking `>=` instead of `==` ?

**Comment by howardjohn** [comment]
Any update on this? There have been many recent failures:

https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/14614/istio-unit-tests-master/3034/build-log.txt
https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/14621/istio-unit-tests-master/1481/build-log.txt
https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/14735/istio-unit-tests-master/2279/build-log.txt
https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/14911/istio-unit-tests-master/2386/build-log.txt
https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/14993/istio-unit-tests-master/2398/build-log.txt
https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/14994/istio-unit-tests-master/2422/build-log.txt
https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/15056/istio-codecov-master/53/build-log.txt
https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/15063/istio-racetest-master/63/build-log.txt
https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/15139/istio-unit-tests-master/2730/build-log.txt
https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/15297/istio-racetest-master/537/build-log.txt
https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/15387/istio-racetest-master/1320/build-log.txt
https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/15452/istio-racetest-master/1508/build-log.txt
https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/15462/istio-racetest-master/1525/build-log.txt
