### ISSUE TITLE
Derivation of core mixer attributes

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1450]
@kyessenov commented on [Wed Aug 30 2017](https://github.com/istio/old_pilot_repo/issues/1147)

Follow-up from an offline discussion:
Currently, Mixer is trusted to derive the majority of core Istio attributes (`source.*` and `destination.*`) from the identity of the proxy/app instance (called `source.uid` and `destination.uid`). There's nothing in principle preventing us to perform this derivation at the configuration time by Pilot rather than at runtime by Mixer. We should try to draw the line between which attributes are the responsibility of Pilot and which ones are the responsibility of Mixer, so as not to have inconsistent bags of attributes.

cc @rshriram @geeknoid @douglas-reid 

---

@geeknoid commented on [Wed Aug 30 2017](https://github.com/istio/old_pilot_repo/issues/1147#issuecomment-326137592)

The check cache in Envoy can only operate in terms of Envoy-visible attributes. For this to be effective, the set of attributes needs to be specialized enough. 

As an example of this, in the API management we want to apply quotas to methods. In order for quota caching to be effective, we need the proxy to look at the URL and extract the method name and thus derive the request.method attribute. We can then cache quota results against request.method instead of caching against request.url. This is highly desirable since request.method is stable whereas request.url can contain a bunch of noise that defeats the cache lookup.

Similar thing here. If we want to be able to reason at a fine-grain on individual data and cache check or quota results, we need to break down the attributes into the smaller atoms inside the proxy.

Architecturally, I've been saying that we have these attribute phases:

Proxy: Original attribute production
Proxy: Attribute derivation to produce more attributes, derived from the original set
Mixer: Attribute producing adapters, more derived attributes, typically from the environment
Mixer: Attribute processing, where operators reference any attribute to produce instances.

Proxy-side caching is only possible on the attributes produced by the proxy proper. Operator policy control can be used against any attribute no matter where it is produced.

So the decision of whether Mixer or proxy should derive attributes is really about caching semantics, and perhaps as well in terms of implementation complexity (Mixer adapters vs. Proxy plugins)

---

@geeknoid commented on [Wed Aug 30 2017](https://github.com/istio/old_pilot_repo/issues/1147#issuecomment-326138673)

To be a bit more concrete:

Let's say the proxy produces source.uid and from this we derive source.service and source.pod. If we expect the user to express policies on source.pod explicitly, then we will get potentially quite a bit more efficient caching if source.service is derived in the proxy as opposed to deriving it in Mixer. This is because the cache entry will be associated strictly with source.service and not with the other data that's also implied by source.uid.

**Comment by geeknoid** [comment]
This is an area to investigate if we find proxy level caching to have low hit rates due to Mixer-side derivation.
