### ISSUE TITLE
Have warning log in Citadel to instruct root transition

### ISSUE THREAD

**Issue by myidpt** [istio/istio#14519]
**Describe the feature request**
https://github.com/istio/istio/issues/14516
Citadel should check whether the root cert expiration is close, and gives warning in the log to instruct users that they should do root transition immediately, and point to the on-line doc about how to do it.

**Describe alternatives you've considered**
Complementing approach: exposing root cert expiration TTL via metric channels.

**Affected product area (please put an X in all that apply)**
Security

[ ] Configuration Infrastructure
[ X ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ X ] Security
[ ] Test and Release
[ X ] User Experience

**Additional context**

**Comment by myidpt** [comment]
@Stono @wattli @wenchenglu

**Comment by incfly** [comment]
We definitely can do both. But I feel metrics is more important than log.
They're more flexible and easier to plug into an prod alerting system.

A int64 representing remaining days, e.g.

**Comment by Stono** [comment]
I actually just raised a feature request for metrics as I agree, they're far more valuable than log messages: https://github.com/istio/istio/issues/14526

**Comment by myidpt** [comment]
I agree. That makes sense to me.

**Comment by incfly** [comment]
Closing this one and using https://github.com/istio/istio/issues/14526 to track the work.
