### ISSUE TITLE
Citadel self signed CA does not auto-renew

### ISSUE THREAD

**Issue by Stono** [istio/istio#14516]
**Bug description**
The root certificate generated by citadel `istio-system/istio-ca-secret` hit 365 days old:

```
❯ kubectl -n istio-system get secret istio.istio-sidecar-injector-service-account -o jsonpath='{.data.root-cert\.pem}' | base64 --decode | openssl x509 -noout -text
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            c1:c6:a0:f7:12:e1:14:ba:f0:57:32:d6:59:90:92:ce
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: O=k8s.cluster.local
        Validity
            Not Before: Jun  2 14:02:46 2018 GMT
            Not After : Jun  2 14:02:46 2019 GMT
```

This caused services to be unable to talk to the control plane:

```
2019-06-02T16:52:29.309612Z	info	Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 0 successful, 0 rejected; lds updates: 0 successful, 0 rejected
```

And services unable to talk to each other:
```
upstream connect error or disconnect/reset before headers. reset reason: connection failure
```

Locating this was a nightmare, no logs anywhere indicated there was a problem with certificates.  It was by pure chance I noticed the secret was 365 days old:

`istio-ca-secret                                      istio.io/ca-root                      2      365d`

In order to recover the cluster we had to:

- Delete that secret
- Restart istio-citadel
- Let citadel update all other services secrets
- Restart _all_ other apps (yes, envoys which were running did not dynamically update their certificates and recover - they continued to get 503s until restarted).

However, we were then unable to restart apps because the sidecar-injector certificate suffered a similar fate albeit with a different certificate chain, see: https://github.com/istio/istio/issues/14517

It seems this isn't an unknown issue: https://discuss.istio.io/t/expired-root-certificate/2331/2 - which is quite unbelievably really folks! 

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[x] Docs
[x] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[ ] Test and Release
[x] User Experience

**Expected behaviour**
The blast radius of Istio is _massive_, even more so when you're using mTLS which is all rooted off a single certificate.  I expect citadel to correctly manage and rotate certificates in all parts of the certificate change, not just tick over 365 days and cause a cluster wide outage.

**Steps to reproduce the bug**
Create `istio-system/istio-ca-secret` out of date.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
All 

**How was Istio installed?**
Helm

**Comment by duderino** [comment]
Not sure if 1.2 is feasible for this, but hopefully something can be done in that timeframe

**Comment by duderino** [comment]
At a minimum, reducing the time to root cause this and even better, spewing our warnings ahead of the expiration should be done for both 1.1 and 1.2

**Comment by myidpt** [comment]
In 1.2, we will prolong the root cert TTL to 100 years. This will remove the ticking bomb issue. For 1.1 and 1.2, beyond that, I think we need to have a root transition feature for the users that are already using the old 1 year cert to rotate to new root certs.

**Comment by Stono** [comment]
@myidpt forgive me but I don't see too much value in that 1.2 work.  If you think about it; it's only going to help new users.  Existing users will still be on the old cert.  New users coming along on 1.2 will likely have the certification rotation feature in place way before the 1 year expiry they'd be getting anyway.

I'd suggest more important for 1.2 is:

  - Log messages clearly stating what's up, linking to:
  - Documentation that clearly shows how the fix it

I'd just like to add that this didn't just cause an `envoy` -> `pilot` issue, it caused `envoy` -> to `envoy` too.  After the expiry date, across the cluster, new mTLS connections between envoys were failing.

Annoyingly after fixing the root CA with citadel, and citadel pushed out the new secrets, we still had failing envoy->envoy connections and the only way for us to fully recover was rolling restarting every application on the cluster.  So feels there may be a separate bug here which needs to be really tested as part of the "how to update citadel root ca".

**Comment by wenchenglu** [comment]
@Stono 
Thank you for reporting this issue. Totally understand your frustration. Yes, we definitely should provide a well-tested Citadel root upgrade plan (along with troubleshooting guide) for existing users without disrupting their traffic including envoy->pilot, envoy<->envoy, and others. This will be our P0 work and we will update our plan how to address this ASAP.

**Comment by myidpt** [comment]
@Stono Understood. We will definitely support the existing users by warning in Citadel logging, pointing to documentation on how to manually do root transition. We probably need to build a new release with this fix as well. We may post message on istio.io website to notify users, and announce the rotation procedure in next security community meeting. We will also work on an automatic root transition feature for the old CAs. Prolonging the root cert TTL will ensure new users won't need to do the rotation in the near future.

**Comment by wenchenglu** [comment]
@Stono 
Just a quick follow up on status update: 
We have some concerns on our first version of CA root upgrade user guide which has been shared with you to get your feedbacks, similar to what you have done to recover your workload, since it needs to restart all workload and may cause some traffic disruption. We are drafting and testing on our 2nd version of root upgrade user guide (along with troubleshoot guide) which we plan to share out today. 

Here are the general concept and we'd love to hear your feedbacks:
step 0: run a script to tell your CA expiration time. If it is expiring soon, start following this user guide immediately
step 1: upgrade your root cert to 10 years
step 2: upgrade to latest Istio release (which is expected to be built out today)
step 3: follow some instructions to test if upgrade is successful

After this upgrade, you will have a 10-year root cert. Our recommendation is to annual rotate your root key/cert as a best practice for security. If you forgot to rotate timely, your production workload won't be affected. 

We will provide metrics to help you check your root cert expiration time.  As a followup, we will provide instructions to help automate your root key/cert rotation later.

**Comment by Stono** [comment]
So long as step 2:

 - has the fix in for pilot-agent to pickup certs changing
 - has the fix in for the mutatingwebhookconfiguration to pick up the new ca
 - workloads continue to be able to communicate if they're using mtls certificates signed by the old CA

eg - no downtime, i think that's fine.

**Comment by wenchenglu** [comment]
yes, that is the plan.

**Comment by Stono** [comment]
Sounds good

**Comment by myidpt** [comment]
This is the announcement we will publish: https://github.com/istio/istio.io/pull/4273

**Comment by daretogo** [comment]
@wenchenglu
> We will provide metrics to help you check your root cert expiration time. As a followup, we will provide instructions to help automate your root key/cert rotation later.

has this been automated in any newer releases?

**Comment by myidpt** [comment]
Which version are you using?
We implemented the auto root cert rotation around Oct. last year and all
latest versions since 1.1 have the auto rotator patched. Also for new
clusters the root will have 10 year TTL.

(BTW, Wencheng is not managing Istio anymore).
