### ISSUE TITLE
upgrade google GRPC lib we use

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1451]
@andraxylia commented on [Fri Sep 01 2017](https://github.com/istio/old_pilot_repo/issues/1167)

Currently we are stuck with grpc 1.2.1, because the grpc > 1.5 is not compatible with gogo.

Find a way to upgarde to newer grpc, get it to support gogo or drop gogo.

go_repository(
    name = "org_golang_google_grpc",
    commit = "8050b9cbc271307e5a716a9d782803d09b0d6f2d",  # v1.2.1
    importpath = "google.golang.org/grpc",
)

**Comment by ymesika** [comment]
Is this still valid issue? I can't find any dependency on the specific version after the move to the new repo

**Comment by andraxylia** [comment]
@mandarjog AFAIK we still use gogo

**Comment by hklai** [comment]
I think we are on 1.12 now.
https://github.com/istio/istio/blob/master/Gopkg.lock#L1256
