### ISSUE TITLE
Do not use in-memory root for citadel

### ISSUE THREAD

**Issue by wattli** [istio/istio#14512]
If Citadel fails to update the CA-root stored in K8s secret, it uses an in-memory root for the cluster. This was introduced in very early stages to support testing Citadel in special environments (non-K8s). Now we should not support in-memory root, because the in-memory root is not sustainable for production usage. It may also cause issues in special scenarios. For example, when Citadel fails to read the existing CA-root secret, it may choose to generate a separate root cert and use it to issue certificates for the cluster, which conflicts with the existing root cert.

@wenchenglu @wattli @lei-tang

**Comment by duderino** [comment]
The fix went out in 1.1.8 and 1.0.8.  Is there any reason to keep this issue open?

**Comment by howardjohn** [comment]
We should keep this open until the change gets into 1.2 probably (#14505)

**Comment by duderino** [comment]
@myidpt this is a 1.2 release blocker

**Comment by myidpt** [comment]
Closing. Changes merged to 1.0, 1.1, 1.2 and master branches.
