### ISSUE TITLE
Pilot need to generate the list of pod ips for mixer for envoy

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1452]
@ldemailly commented on [Fri Sep 08 2017](https://github.com/istio/old_pilot_repo/issues/1218)

Pilot need to generate the list of pod ips for mixer for envoy:

As far as I know envoy uses the (service) clusterIP to reach mixer, instead it should do the cluster->podIP translation we do for regular services

cc @kyessenov who says it's already there and @costinm (and I) who need it for rawvm and would avoid an ILB for mixer

putting 0.2 if it's easy/already there, otherwise early 0.3

---

@ldemailly commented on [Sun Sep 10 2017](https://github.com/istio/old_pilot_repo/issues/1218#issuecomment-328373788)

cc @andraxylia who was wondering what I meant on slack

---

@rshriram commented on [Mon Sep 11 2017](https://github.com/istio/old_pilot_repo/issues/1218#issuecomment-328544215)

I don't think we should expose pod IPs outside kubernetes. For all we know, some network policy or firewall setting or even the overlay network itself could prevent all external access to the pod ip network. Your suggestion is based on the assumption that VMs and pods are on the same flat network- which may not be universally true (think of VMs being joined over vpn where only access to the ingress lb ip is allowed).

@gnirodi The consensus in the hybrid doc was that we would always reach a kubernetes cluster via the ingress as typical firewall settings could force all inbound traffic into kubernetes to enter only via ingress. This would mean specifying global dns addressable mixer and pilot for hosts outside k8s cluster. So, I could choose to expose pilot and mixer via an ingress (which gets a dns domain or lb ip in most providers. This does not preclude me from using auth or mTLS because #1234 will allow mTLS at ingress).

---

@kyessenov commented on [Mon Sep 11 2017](https://github.com/istio/old_pilot_repo/issues/1218#issuecomment-328612529)

If the issue is to expose mixer internal pod IPs, then that's already done by Pilot. If the issue is whether or not we should use those IPs, then that's up to debate in the hybrid design, and does not belong here.

---

@ldemailly commented on [Tue Sep 12 2017](https://github.com/istio/old_pilot_repo/issues/1218#issuecomment-328759299)

plesse document how to get those podips so we can save one ilb

**Comment by costinm** [comment]
ILB for mixer no longer needed, zvpn and ingress will take care of this.

**Comment by ldemailly** [comment]
it's still a useful future feature specially for AZ

**Comment by ldemailly** [comment]
Not stale (bot is only creating noise and busy work :/ )
