### ISSUE TITLE
Expose expiry timestamp for all citadel managed certificates

### ISSUE THREAD

**Issue by Stono** [istio/istio#14526]
**Describe the feature request**
Following on from https://github.com/istio/istio/issues/14516, please can Citadel expose prometheus metrics for all certificates it knows about, eg all services accounts, root certificates etc.

The standard for this seems to be `thing_expire_time_seconds` (if you look at other projects eg cert-manager, nginx) with the value being the timestamp as int64.  So perhaps:

`citadel_mtls_cert_expire_time_seconds` and `citadel_mtls_ca_expire_time_seconds`

This allows you to do queries like:

```
  - alert: ScheduledTaskMissedRun
    expr: kube_cronjob_status_next_schedule_time - time() < 0
```

Which gives me cronjobs that have missed their schedule.

**Describe alternatives you've considered**
Logs, but logs aren't great as unless you're actively monitoring them you'll miss things.  Prometheus alerts plug into many peoples existing alerting platforms.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[ ] Test and Release
[x] User Experience

**Additional context**

**Comment by incfly** [comment]
I'm working on this, a WIP diff can be found at https://github.com/istio/istio/compare/master...incfly:cert-metrics?expand=1 

Citadel with that diff can give following metrics 

- `kubectl port-forward istio-citadel-pod-id 15014:15014`.
- `curl localhost:15014/metrics`

We can see a guage metrics for the root cert TTL. Prometheus gauge only supports float64, so the 3.14xx+e7 is a bit of human unfriendly, but I guess the alert system can configure separately.

![Screen Shot 2019-06-03 at 4 55 58 PM](https://user-images.githubusercontent.com/1661831/58841888-ba0cfe80-8620-11e9-950b-dfc2b5b2d696.png)

I'll add unit test for this and send the PR out.

**Comment by Stono** [comment]
I'm not sure about those int64 values... here's a service i wrote with a simple (readable) counter and unix timestamps for expiry:

```
# HELP sweepr_atcloud_service_created_seconds A guage which shows the created timestamp for the atcloud service
# TYPE sweepr_atcloud_service_created_seconds gauge
sweepr_atcloud_service_created_seconds{app="vds-kee-importer",namespace="vds-kee-importer",owner="--------@autotrader.co.uk",squad="stock-search-platform"} 1553869508
```

**Comment by incfly** [comment]
Good point. I checked the cert-manager, https://github.com/jetstack/cert-manager/blob/master/pkg/metrics/metrics.go#L53

Will change to similar semantics.

**Comment by howardjohn** [comment]
@incfly this is done by #14569 right? Is there any work to do here?

**Comment by incfly** [comment]
This can be closed now.
