### ISSUE TITLE
produce small and medium prod profiles

### ISSUE THREAD

**Issue by linsun** [istio/istio#14523]
for the new installer, based on what has been discussed in env WG meeting last week.

**Comment by linsun** [comment]
and possible the multi cluster profile.  Need to check the current profiles list and supply popular ones.

**Comment by howardjohn** [comment]
I personally don't see the value added. We have demo (small) and default (medium) already. Large profile doesn't make much sense, as anyone with large deployments should not be using cookie-cutter profiles and instead will want to customize it (which we should document).

**Comment by linsun** [comment]
@howardjohn thanks! Would like to kick off discussion on this... I created this because many folks think our default is for small production... and there is a desire to have medium production where our control planes are more highly available and can stay highly available during the update.  

I would think demo is tiny of everything instead of small.

**Comment by howardjohn** [comment]
I think currently we have

demo = no limits, no HPA, low requests
default = sane limits and requests, hpa, basic pdb

New profile would be HA, higher limits and requests?
