### ISSUE TITLE
pilot-agent cert rotation broken

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#14539]
Copying slack conversation:

> 
> Anubhav Aeron [1:23 PM]
> Hi, is pilot-agent’s cert watch broken?
> 
> I see that pilot-agent used to watch on the folder but now watches on files. It was changed in this PR - https://github.com/istio/istio/pull/12707
> 
> When citadel updates the certificates, kubernetes deletes the mounted file, which breaks the file watcher.
> 
> Before updating cert
> ```$ ls -lia cert-chain.pem ..data/cert-chain.pem
> 3549057 -rw-r--r-- 1 root root 1131 Jun  3 19:27 ..data/cert-chain.pem
> 3473806 lrwxrwxrwx 1 root root   21 Jun  3 19:19 cert-chain.pem -> ..data/cert-chain.pem```
> 
> After updating cert
> ```$ ls -lia cert-chain.pem ..data/cert-chain.pem new_key ..data/new_key
> 3560732 -rw-r--r-- 1 root root 1131 Jun  3 19:28 ..data/cert-chain.pem
> 3473806 lrwxrwxrwx 1 root root   21 Jun  3 19:19 cert-chain.pem -> ..data/cert-chain.pem```
> 
> istio-proxy logs
> ```2019-06-03T19:19:04.872250Z     info    watching /etc/certs/root-cert.pem for changes
> 
> 
> 2019-06-03T19:27:13.540682Z     info    watchFileEvents: "/etc/certs/root-cert.pem": MODIFY|ATTRIB
> 2019-06-03T19:27:13.540751Z     info    watchFileEvents: "/etc/certs/root-cert.pem": DELETE
> 2019-06-03T19:27:13.540757Z     info    watchFileEvents: "/etc/certs/key.pem": MODIFY|ATTRIB
> 2019-06-03T19:27:13.540841Z     info    watchFileEvents: "/etc/certs/key.pem": DELETE
> 2019-06-03T19:27:13.541036Z     info    watchFileEvents: "/etc/certs/cert-chain.pem": MODIFY|ATTRIB
> 2019-06-03T19:27:13.541051Z     info    watchFileEvents: "/etc/certs/cert-chain.pem": DELETE
> 2019-06-03T19:27:23.540962Z     info    watchFileEvents: notifying
> ```
> 
> After the last “DELETE” event of  each file, pilot-agent does not watch on the cert and hence *no reload* (edited) 
> 
> Stono [1:35 PM]
> Interesting if this is true it would explain why I had to restart all services after citadel distributed a new root CA yesterday (cc @Joshua Blatt)
> 
> Tao Li [3:02 PM]
> @Karl, but i think you don't have to delete the key/cert files at the first place, right?
> 
> Anubhav Aeron [3:33 PM]
> In kubernetes the secrets are symbolic links.
> 
> When a secret is updated, the file is recreated, which breaks the watch
> 
> John Howard [4:22 PM]
> @Anubhav Aeron are you seeing it will restart one time and then never again, or not even restart once?
> 
> John Howard [4:34 PM]
> I reproduced this and rolled back to 1.1.2, before that PR linked, and it works again

@myidpt @wattli @duderino

**Comment by nirvanagit** [comment]
PR - https://github.com/istio/istio/pull/14540

**Comment by howardjohn** [comment]
Keeping this open as we need to backport to 1.2

**Comment by howardjohn** [comment]
This has been fixed, just going to track the backport in https://github.com/istio/istio/issues/14683 to keep things simple
