### ISSUE TITLE
One line install for Istio demo

### ISSUE THREAD

**Issue by ostromart** [istio/istio#14534]
In the context of the operator there are two requirement:
- we are no longer including add on (prom, grafana etc.) charts in Istio 
- we need some way to simply install those component with config suitable for Istio demo
Installing these components side by side with the operator manifest is not reliable because the addon operators require custom CRDs, which need to be installed prior to the addon operator and CR. 
Some mechanism is needed to install Istio operator and external addon CRD together, and only then install addon operator CR, and this must be possible with a single line install.

**Comment by knrc** [comment]
An operator should not be installing other operators but should only be concerned with creating Custom Resources monitored by those other operators (e.g. kiali, jaeger, elasticsearch etc).

The Istio operator should be responsible for translating any related configuration within the ControlPlane resource into resources accepted by the other operators with a check to ensure those deployments have been successful.

There are other mechanisms within the operator ecosystem for handling installation/dependencies however for demo purposes, assuming something like the Operator Lifecycle Manager is not installed, there could be a single yaml file installing all necessary operators.

**Comment by ostromart** [comment]
How can we ensure that this single yaml file doesn't run into the same CRD/CR race conditions that we faced in istio?

**Comment by knrc** [comment]
@ostromart This would install the operators so there is no race condition.  When the ControlPlane is deployed into a namespace the istio operator would react to its creation and run through the installation for the control plane, part of which would be the creation of the custom resources for the other operators.  The istio operator can wait for the operators to deploy their resources just as it would for its own resources.

**Comment by ostromart** [comment]
What do you mean by "this" in "this would install" above? If you mean just a single flat manifest I don't see how you can guarantee that addon operator CRDs are created before the addon operator CRs and resources. 
At the very least afaics it would lead to a two step install process as we have with Istio 1.1.

**Comment by knrc** [comment]
"this" = the yaml file we are discussing so "this would install" refers to the installation of the operators into a specific namespace.  Note this would only be necessary in the absence of OLM.

Yes, it would lead to a two step process in that you first need to have the operators installed and then configure the control plane.  You **could** include the ControlPlane custom resource in the same yaml as the operators however this would not be advisable since it can take some time for the CRDs to deploy and to be made available through the api server.  Any approach which included the creation of the operator's CRDs along with their usage would suffer from this.

**Comment by ostromart** [comment]
Right, that's what I meant by race condition. 
One way we could get around it is to have the operator bootstrap off a configmap which would contain the istio operator CRD as text. The operator itself would create any CRDs. That's a trick we're using in other parts of Istio. 
I'm not necessarily saying that's what we should do, but it's an option. I just think it would be very helpful to simplify (editable) installs down to a single line. Istio also used to use an install script which you piped in from curl so that's another possibility. That was abandoned in favor of the two-step helm approach but I'm not sure what the problem was with that approach, if any.

**Comment by knrc** [comment]
+1 we actually removed those examples from our version and relied on the operator to handle the creation of the istio CRs once the CRDs had established.  We should favour this for this operator as well, at least as far as the Istio CRDs are concerned.

In addition once we start to think about multi-tenancy (there's still work to do in this area within Istio) then we would also need the operator to handle the creation/management of the super sets of resources in case there are any CRDs added/removed from differing versions.

**Comment by ostromart** [comment]
I think we can somewhat claim success on this. We have a single line install/upgrade with istioctl (yes, you have to install istioctl so it's not really one line) and a two line install for operator (there's just no way to get around the race problem of applying CR together with CRD without code).
Unless we feel there's further work to be done here (pipe curl into bash anyone?), I'm closing this - anyone feel free to reopen if you feel differently.
