### ISSUE TITLE
Docs for galley show Pilot's environment variables

### ISSUE THREAD

**Issue by geeknoid** [istio/istio#14543]
When viewing the Galley docs on preliminary.istio.io, you can see listed all of Pilot's environment variables. This is because Galley is pulling in Pilot code for validation. The Pilot code needs to be refactored in order to prevent this overagressive transitive import problem.

**Comment by ozevren** [comment]
@therealmitchconnors Could you please take a look?

**Comment by therealmitchconnors** [comment]
I have been investigating the possibility of separating Galley's dependencies from the larger pilot/pkg/model, which also imports the rest of Galley.  I think I am making progress, but it's quite a web of dependencies.  What priority should we assign to this work?

**Comment by geeknoid** [comment]
Medium I suppose. It's mostly a case of "silly docs".

**Comment by ozevren** [comment]
Darn, I closed the window before publishing my comment. Oh well.

This can be separated into two parts:

1) Documentation (silly docs as @geeknoid ) put it. This part is the most important one, and hopefully should be straightforward to fix for 1.2
2) Break Galley's simple dependencies. I suspect some of the stuff here is low-hanging fruit, so if we can get them done, it is great. It may not need go to 1.2 but that's fine. That work needs to be done anyways.
3) Break Galley's complicated dependencies. This is a gnarly one, and requires some careful planning and consensus. This one is probably the long tail and not urgent in the "do we need this for 1.2" sense.
