### ISSUE TITLE
Add the bash and zsh options to the istioctl collateral command flag.

### ISSUE THREAD

**Issue by ibm-jason** [istio/istio#14541]
As discussed here: https://github.com/istio/istio/issues/12607#issuecomment-490523390, we have identified a UX improvement that would provide Istio users the ability to download the `istioctl` binary separate from the Istio project itself, while also including the bash and zsh auto-completion files:

Provide the `istioctl collateral` command flag with two new options: `istioctl collateral bash` and `istioctl collateral zsh`. Each of these options would generate a tab completion file sent to the console output, allowing users the ability to easily source the tab completion files as part of their shell profile, i.e. `istioctl collateral bash > istioctl.bash` or `source < istioctl collateral bash`.

What we currently have is the alternative, with the tab completion files stored in the `tools` folder. However, providing the istioctl binary as a separate download would not include the tab completion files today.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience

We spoke with @linsun about this, and she has indicated that this would be the preferred approach.

**Comment by linsun** [comment]
can we have istioctl standalone download avail first and add tab completion when it is ready to be added?  Not everyone uses tab completion.

**Comment by ibm-jason** [comment]
@linsun yes, I think we can do that. I re-submit my original PR to add the istioctl download script, and we can add in the tab completion feature later.

**Comment by ericvn** [comment]
I would vote to have the command be `istioctl completion bash` and `istioctl completion zsh` as the _collateral_ noun is hidden.

**Comment by howardjohn** [comment]
`istioctl collateral --zsh` is working now, verified with latest built
