### ISSUE TITLE
Istio performance

### ISSUE THREAD

**Issue by Demonian** [istio/istio#14553]
(This is used to report product bugs, please visit <https://discuss.istio.io> for questions on using Istio)

**Bug description**
Before deploying istio on production we have decided to run some load tests with enabled sidecar and MTLS for our services/pods. Results are pretty bad now, because throughput without istio is 2x times higher than with istio sidecar.

Currently we have more than 100 pods in our cluster/mesh. Our load tests were done with a help of Jmeter. We are executing simple business scenario (aka user registration).
Results without enabling istio sidecar:
<img width="488" alt="Screen Shot 2019-06-04 at 12 48 10" src="https://user-images.githubusercontent.com/9040058/58869723-7de0a900-86c7-11e9-8898-6d2e051f397f.png">
<img width="1003" alt="Screen Shot 2019-06-04 at 12 48 18" src="https://user-images.githubusercontent.com/9040058/58869737-820cc680-86c7-11e9-80d9-3e6dff145ed2.png">
<img width="1009" alt="Screen Shot 2019-06-04 at 12 48 32" src="https://user-images.githubusercontent.com/9040058/58869743-876a1100-86c7-11e9-8fd9-bb58ea8d1856.png">
<img width="1009" alt="Screen Shot 2019-06-04 at 12 48 45" src="https://user-images.githubusercontent.com/9040058/58869752-8b962e80-86c7-11e9-863e-b310a96beda0.png">

Results with istio sidecar and MTLS:
<img width="502" alt="Screen Shot 2019-06-04 at 12 48 56" src="https://user-images.githubusercontent.com/9040058/58869851-b2546500-86c7-11e9-92f1-9007cc5d9cad.png">
<img width="1008" alt="Screen Shot 2019-06-04 at 12 49 14" src="https://user-images.githubusercontent.com/9040058/58869856-b5e7ec00-86c7-11e9-9119-4e5a4c0356f1.png">
<img width="997" alt="Screen Shot 2019-06-04 at 12 49 25" src="https://user-images.githubusercontent.com/9040058/58869859-b7191900-86c7-11e9-92de-5f7f3aec1f65.png">
<img width="1011" alt="Screen Shot 2019-06-04 at 12 49 38" src="https://user-images.githubusercontent.com/9040058/58869866-baaca000-86c7-11e9-9839-09f6941801a4.png">

Do you have any ideas on how to debug this problem? There are no any warning or error logs on sidecar proxies, pilot or mixer. 

If you will need some specific information, I will try to provide it.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[X ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

**Expected behavior**
Throughput should be almost the same with and without istio.

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Istio version: 1.1.6
Kubernetes version: v1.11.7

**How was Istio installed?**
Istio was installed with helm charts, MTLS is enabled.

**Comment by Demonian** [comment]
**BTW** Results with istio sidecar are always the same we have tried to increase proxy concurrency level but still the same results. We have tested it with concurrency level **2** and **4**.

**Comment by howardjohn** [comment]
Can you give some more info about your install? Did you just use the defaults with `--global.mtls.enabled=true` and concurrency changed?

**Comment by mandarjog** [comment]
The statistics report for with and without Istio is for a different set of functions, is that by design? Or I am missing something.

**Comment by Stono** [comment]
> Do you have any ideas on how to debug this problem? There are no any warning or error logs on sidecar proxies, pilot or mixer.

Exactly my ask in https://github.com/istio/istio/issues/10279 actually

**Comment by Demonian** [comment]
@mandarjog Payload is similar, we just make some changes after few bad results, but situation hasn't changed we always get half less throughput for pods with enabled istio. FYI We have made some additional tests throughput is little bit higher with concurrency value set to **1**.
<img width="496" alt="Screen Shot 2019-06-04 at 22 11 03" src="https://user-images.githubusercontent.com/9040058/58906919-b27b5180-8715-11e9-8b3e-4582c1a6aa1a.png">
<img width="1004" alt="Screen Shot 2019-06-04 at 22 11 12" src="https://user-images.githubusercontent.com/9040058/58906924-b6a76f00-8715-11e9-99fc-3f137dd5a1b8.png">
<img width="920" alt="Screen Shot 2019-06-04 at 22 10 54" src="https://user-images.githubusercontent.com/9040058/58906934-bb6c2300-8715-11e9-8ec6-14831ad1bca4.png">
<img width="999" alt="Screen Shot 2019-06-04 at 22 10 42" src="https://user-images.githubusercontent.com/9040058/58906938-bf984080-8715-11e9-84a8-fff4160c3d47.png">

About configs, we have increased resources limits for envoy, pilot and mixer, enable MTLS, tracing and also we enable network policy checks for mixer `disablePolicyChecks: false`, also during our investigation we have changed concurrency level for pilot, tests were done with different values: **1,2,4**. Everything else is configured with default values.

**Comment by sdake** [comment]
can you provide your exact `values.yaml` override file, or a list of KV pairs and the values you set?

Cheers
-steve

**Comment by Demonian** [comment]
```
# Istio global subchart values
tracing:
  enabled: false

# Citadel (certificate management)
security:
  enabled: true

# Policies and metrics
mixer:
  enabled: true
  policy:
    # if policy is enabled the global.disablePolicyChecks has effect
    enabled: true
  telemetry:
    enabled: true

# Pushes configurations to the proxy
pilot:
  enabled: true

# Istio gateways
gateways:
  enabled: false

# We use our own
prometheus:
  enabled: false

# We use our own
grafana:
  enabled: false

# Interactive realtime interation graph
kiali:
  enabled: false

# Access to Kiali
servicegraph:
  enabled: false

# Per node citadel, we use only the deployment
nodeagent:
  enabled: false

# Setups Pod proxy networking. We use init container
istio_cni:
  enabled: false

# Interface with CoreDNS. We use KubeDNS
istiocoredns:
  enabled: false

global:
  tag: 1.1.6
  disablePolicyChecks: false
  proxy:
    autoInject: disabled
    concurrency: 1
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 2048Mi
  controlPlaneSecurityEnabled: true
  mtls:
    enabled: true
  accessLogFile: ""

# Istio subchart values
istio:
  security:
    selfSigned: false

  pilot:
    traceSampling: 0.1

  sidecarInjectorWebhook:
    # Enables istio on namespaces unless label "istio-injection=disabled" is set to a namespace
    # Note that autoInject is disabled (global.proxy.autoInject)
    enableNamespacesByDefault: true


```

**Comment by howardjohn** [comment]
Some notes: the main things that impact data plane performance are the proxy, mixer policy, and mixer telemetry. Even though telemetry is async, it still has a big impact on latency, because the proxy has to process the telemetry at _some point_, and when it does latency will be impacted. See the graph at https://istio.io/docs/concepts/performance-and-scalability/, telemetry doubles the latency.

We have some recent changes in the works to enable more Envoy stats, which makes it viable to disable mixer telemetry if you are in a situation where you care more about latency than telemetry - you get ~75% of the metrics with better performance. I believe the PR was https://github.com/istio/istio/pull/14212, so looks like it will only make it into 1.2 and not 1.1 unfortunately.

My point is, if that is a tradeoff you would be interested in making you may want to test with telemetry off and see what results you get

**Comment by Demonian** [comment]
@howardjohn Thank you for you answer. We will test without telemetry and I will share the results here. (BTW We have planned to test without telemetry, but before that we wanted to cover all possible variants of optimization without disabling mixer =) )

**Comment by Demonian** [comment]
@howardjohn @sdake @Stono I would like to make some conclusion to this topic. First of all we have achieved good results with only **12%** less throughput (MTLS, pilot, telemetry, tracing enabled) in comparison to configuration without istio, we had almost *50%* at the beginning.

Here is our tests results:
<img width="1023" alt="Screen Shot 2019-06-21 at 13 18 19" src="https://user-images.githubusercontent.com/9040058/59916240-4859f080-9427-11e9-8ca4-717ad525ad49.png">

Now I will try to describe how we were able to tune the results:
1. First of all it is very useful to monitor this metric from prometheus:

**Comment by howardjohn** [comment]
> `container_cpu_cfs_throttled_seconds_total` 

Wow very useful, I did not know about this one. Maybe should be added to our performance dashboard. The links you provided look really informative as well, will have to dig into those. 

Glad to see you got it down to only 12% less throughput!

@mandarjog you may be interested in ^

**Comment by Stono** [comment]
Mega.  Thanks for the headsup about `container_cpu_cfs_throttled_seconds_total`

**Comment by Demonian** [comment]
@Stono @howardjohn Will be glad if this help somebody=) BTW I close this.

**Comment by mandarjog** [comment]
Thanks @Demonian. 

I have looked at these metrics before and mostly saw kube-system processes throttled.  I expect istio-telemetry pods to be throttled from time to time. The best way to avoid throttling is to "request" adequately since it decides placement.

Great idea to actually put this on the performance dashboard though.
