### ISSUE TITLE
ingress-gateway does not work when the service has multiple ports

### ISSUE THREAD

**Issue by stone4774** [istio/istio#14557]
(This is used to report product bugs, please visit <https://discuss.istio.io> for questions on using Istio)

**Bug description**

ingress-gateway does not works well when the service has multiple ports

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

**Expected behavior**

**Steps to reproduce the bug**
1： Add a port 9081 for the productpage service in bookinfo

apiVersion: v1
kind: Service
metadata:
  name: productpage
  labels:
    app: productpage
    service: productpage
spec:
  ports:
  - port: 9080
    name: http
  - port: 9081
    name: httptest
    targetPort: 9080
  selector:
    app: productpage

2： create a ingress-gateway for productpage:

kind: Gateway
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: bookinfo-gateway
  namespace: istio-test
  ......
spec:
  servers:
    - hosts:
        - bookinfo.istio.test
      port:
        name: http
        number: 80
        protocol: HTTP
  selector:
    istio: ingressgateway

3： create a virtualservice for productpage:

kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: productpage
  namespace: istio-test
  ......
spec:
  hosts:
    - bookinfo.istio.test
  gateways:
    - bookinfo-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: productpage
            subset: v1
          weight: 100
  tcp: ~
  tls: ~
At this point, accessing productpage through ingress-gateway returns 503 errors. 
I found that after adding port 9081, envoy in ingress-gateway routes the request to cluster: 
  outbound|80|V1|productpage.istio-test.svc.cluster.local, but the cluster does not exist; if port 9081 is removed, envoy routes the request to outbound|9080|V1|productpage.istio-test.svc.cluster, and it works well.

  Maybe we should to specify the target service port in the gateway

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by mbanikazemi** [comment]
Could this be related to https://github.com/istio/istio/pull/14346 ?
Let me reproduce and see if that PR makes a difference.

**Comment by mbanikazemi** [comment]
Well, this works for me. I use the book info resources. then edit the port section of the productpage service and add an entry for port 9081:
```
 spec:
  ports:
  - name: http
    port: 9080
    protocol: TCP
    targetPort: 9080
  - name: httptest
    port: 9081
    protocol: TCP
    targetPort: 9080
```

I am able to access the product page through the gateway as before.

Furthermore, I can edit the vs to forward requests to port 9081 and that will continue to work as before.


If you still have problem, please upgrade to latest istio and if still the issue persist, report the exact yams used and the errors observed.
