### ISSUE TITLE
Virtual Service/Gateway support for ingress controller

### ISSUE THREAD

**Issue by rverma-nikiai** [istio/istio#14552]
**Describe the feature request**
Using ingress gateway we are losing some advantages of CNI plugins. For instance, aws-vpc-cni exposes pod IP and allows to bind them directly to an ALB. Aws-alb-ingress-controller is working on the same principal. Using alb has its own advantages compared to the istio-gateway(Cognito, performance, simplicity, target-group alarms, transparency, WAF, ACM, CloudFront caching, some are available in istio as well).

**Describe alternatives you've considered**
Currently, to use ingress with some service either the service goes off the mesh or it goes through the gateway. 
If we are able to map VirtualService to an ingress directly, which require changes in ingress part as well, we can implement a combination of ingress + gateway benefits. Maybe I am overthinking but looking for suggestions. 

**Affected product area**

[x ] Configuration Infrastructure
[ ] Docs
[x ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

**Additional context**
Opening up this ticket to discuss and understand feasibility around this.

**Comment by howardjohn** [comment]
I think the current plans are to only support the base Ingress features. If you want to use advanced Istio features you would need to use Istio ingrss
