### ISSUE TITLE
Making end user authentication optional for an endpoint

### ISSUE THREAD

**Issue by cagataygurturk** [istio/istio#14555]
**Describe the feature request**

We have and service which can be accessed by both authenticated and non-authenticated users, returning different content according to login status. Our service is validating JWT token and returning 403 if token is invalid. If no token is given in the request, the service understands that this is an anonymous request and does not perform any validation.

We want to offload JWT validation to Istio but with end user authentication enabled, Istio requires always a valid JWT token and it won't allow non-authenticated users to connect to the service.

It would be nice to add an option to allow such a use case.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Policies and Telemetry
[x ] Security
[ ] Test and Release
[ ] User Experience

**Additional context**

**Comment by yangminzhu** [comment]
If your service is going to validate the JWT token anyway, would you mind to clarify a little bit why do you want Istio to do it again?

Also does the `originIsOptional` field solve your issue here? See https://istio.io/docs/reference/config/istio.authentication.v1alpha1/#Policy

**Comment by cagataygurturk** [comment]
We want to shift the JWT token validation responsibility to Istio. Since we are doing end-user authentication, `originIsOptional` is a bit closer to our requirement but not exactly.

The logic we'd like to use in upstream services is like this:

- If there is JWT token coming from Ingress, decode it and use the payload without validating the token again, because Istio already did.
- If there is no token, assume that this was an anonymous request.

With `originIsOptional`, request arrives to the upstream service if request does not have any token. This is good.
However, this option also allows the request when an **invalid** token is given in the request. In this case, as designed, Istio will silently allow the request still. In this case, our upstream service can't trust the incoming token because it does not know whether this is an invalid or valid token without validating it again.

**Comment by yangminzhu** [comment]
> We want to shift the JWT token validation responsibility to Istio. Since we are doing end-user authentication, `originIsOptional` is a bit closer to our requirement but it not doing exactly what we need.
> 
> The logic we'd like to use in upstream services is like this:
> 
> * If there is JWT token coming from Ingress, decode it and use the payload without validating the token again, because assume that Istio already did this and token is valid.

Just do confirm, your application will decode the JWT token (from base64 to json) and use it directly as you assume it's already validated Istio, right?


> * If there is no token, assume that this was an anonymous request.
> 
> With `originIsOptional`, a request still arrives to the upstream service if request does not have any token. This is good.
> However, this option also allows the request when an **invalid** token is given in the request. In this case, as designed, Istio will silently allow the request still. In this case, our upstream service can't trust the incoming token because it does not know whether this is an invalid or valid token without validating it again.

So to summary, a request is allowed if it has a valid JWT token or if it doesn't have JWT token at all?

**Comment by cagataygurturk** [comment]
Yes @yangminzhu this is exactly what is needed. I believe a lot of user-facing API‘s want to work in this way.

**Comment by y0zg** [comment]
@geeknoid  what is alternative by closing this issue? 
We would like to have the same option as per descritption

Thank you

**Comment by diemtvu** [comment]
In 1.5, we will move Jwt policy to a new (`RequestAuthentication`) and it will behave exactly as like that. In short, the new `RequestAuthentication` only specify how to validate JWT; a request with invalid JWT will be rejected, but all other will be allowed.

Access control then can be fine tuned with authz (e.g require requestPrincipal on certain operations).

Please check back in the next release.

**Comment by incfly** [comment]
I believe this issue has been addressed. @diemtvu i think the user is requesting request can go thorough as long as 

- valid token (format), but not reject
- no token

reject invalid token.

this is exactly what we impl in the 1.5 RequestAuthn. Do you think we need additional doc to illustrate how to use this feature? @diemtvu

**Comment by incfly** [comment]
Closing. Feel free to open new issue if new API does not handle your requirement.

**Comment by cagataygurturk** [comment]
The new RequestAuthentication solves our issue. Thanks!
