### ISSUE TITLE
Increase http.url maximum length in traces

### ISSUE THREAD

**Issue by Stono** [istio/istio#14563]
https://github.com/istio/istio/issues/12561 (https://github.com/envoyproxy/envoy/pull/6492) increased the limit from 116 (back to a previous value of 256) but that still isn't enough for many internal urls for us.

It'd be great if this was higher, the generally accepted limit for urls is 2000 characters, or at least that's what most people aim to stay under for maximum compatibility.

I have no idea at all of the implications this would have from a storage perspective (we use elasticsearch which indexes it as text so sure it'll be fine, but i'm thinking about in-memory like the istio default install uses)

cc. @douglas-reid

**Comment by douglas-reid** [comment]
cc: @objectiser 

I think we may want to extend Envoy itself to support a configurable length here, defaulting to the current value.

**Comment by Stono** [comment]
:wave: any progress on this front?  I probably get asked daily about this internally

**Comment by Stono** [comment]
No problem @douglas-reid - hope all is well!

**Comment by douglas-reid** [comment]
@Stono took a shot at step 1 (https://github.com/envoyproxy/envoy/pull/8095).

**Comment by Stono** [comment]
Yeah I saw, thank you very much :-)

**Comment by Stono** [comment]
@douglas-reid  can we reopen this?

**Comment by douglas-reid** [comment]
sure. i'm not sure how we will be addressing this right now, as we don't have an API for it yet.

**Comment by jacob-delgado** [comment]
I'm trying to get this into 1.6. Given some recent discussion it'll be in, albeit a workaround until we can get a telemetry API in place. That way you can utilize the feature without having to write custom EnvoyFilters

**Comment by jacob-delgado** [comment]
Verified in 1.6.0-beta.0
