### ISSUE TITLE
What's the difference between Templates and Instances in mixer?

### ISSUE THREAD

**Issue by sniperking1234** [istio/istio#14575]
The two concepts are very similar and now I'm confused

**Comment by douglas-reid** [comment]
From: https://istio.io/docs/concepts/policies-and-telemetry/#instances

> Instance configuration specifies the request mapping from attributes to adapter inputs. Templates define the specific required content of individual instances.

Put another way, templates define the schema for instances. Instances define how to transform attributes into objects for processing by adapters.

So, you might have a template that defines the vague shape of a metric (for instance, it has a `value` and some set of typed `dimensions`). Then, you have specific instances of that template -- for example, `requestcount` -- that provides further specification within that broad template as well as a mapping for generation. For example, `requestcount` would define how to calculate `value`, which `dimensions` to use (and of what type), and how to populate the `dimensions` from attributes (request/response metadata).

Templates are used to define the contract between Mixer and adapters. For instance, if an adapter author wants to receive metrics, they will need to implement `HandleMetric`. Then operators, at runtime, can define `instances` of the `metric` template without the need to change or specialize the handler code.

Most of the time, it should be possible to ignore templates, as there is decent base coverage (examples: `metric`, `logentry`, and `tracespan` for telemetry).

To provide a somewhat relevant analogy, you can think of templates as being more like interfaces, whereas instances are more like structs with a defined constructor. In the metric example, you can think of the template as being an interface consisting two methods: `GetValue()` and `GetDimensions()`. And your instance would be struct that implements that interface and comes with a specific `New(attributes)` implementation.

Hope that helps.

Let's move this discussion (and similar) to our forum in the future: discuss.istio.io. Closing for now.
