### ISSUE TITLE
Ingress only gets IP when it is in the istio-system namespace

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1457]
@ijsnellf commented on [Wed Sep 27 2017](https://github.com/istio/old_pilot_repo/issues/1367)

The ingress status syncer tries to grab the IP from `<discovery namespace>/<ingress service>`. We watch for ingress definitions in either all namespaces, or a given user namespace.

---

@ijsnellf commented on [Thu Sep 28 2017](https://github.com/istio/old_pilot_repo/issues/1367#issuecomment-332861248)

Might only be in minikube... will verify.

---

@andraxylia commented on [Thu Sep 28 2017](https://github.com/istio/old_pilot_repo/issues/1367#issuecomment-332873425)

How is this different from #1021?

Why are the ingress resources definitions relevant to this? They do not participate in the setting of the IP address. Multiple ingress resources can be defined in multiple namespaces, and they will all get the ingress controller's external IP or nodePort.

**Comment by andraxylia** [comment]
@ijsnellf is this still an issue?
