### ISSUE TITLE
How to manually compile source code to install istio

### ISSUE THREAD

**Issue by DragonSuper** [istio/istio#14579]
Because my cpu architecture is not x86 or x86_64.
So，I need to  compile source code to install istio manually。

But the relevant document cannot be found。

I exec `make` command,but envoy exec file exec format error.
envoy is https://github.com/envoyproxy/envoy  or not?

In summary , I want documentation how to install istio by source code.
Thanks.

**Comment by esnible** [comment]
Is your Kubernetes cloud an x86?  Try `GOOS=linux GOARCH=amd64 make`

I haven't tried to compile on other architectures but when I compile custom versions on OSX I typically do 

```
GOOS=linux make pilot
HUB=<myaccount> TAG=custom GOOS=linux make docker.pilot
docker push <myaccount>/pilot:custom
```

You may need something like that.

**Comment by DragonSuper** [comment]
> Is your Kubernetes cloud an x86? Try `GOOS=linux GOARCH=amd64 make`
> 
> I haven't tried to compile on other architectures but when I compile custom versions on OSX I typically do
> 
> ```
> GOOS=linux make pilot
> HUB=<myaccount> TAG=custom GOOS=linux make docker.pilot
> docker push <myaccount>/pilot:custom
> ```
> 
> You may need something like that.

Thanks，but I can't find out envoy in Makefile。It was downloaded by network。
My Kubernetes cloud is not x86. so i need to build envoy。
envoy is https://github.com/envoyproxy/envoy or not?

**Comment by esnible** [comment]
What are you building on?  Power?

When I build the sidecar I do 

```
GOOS=linux make pilot-agent
HUB=<myaccount> TAG=custom GOOS=linux make docker.proxyv2
docker push <myaccount>/proxyv2:custom
```

For x86 users, a compiled x86 Envoy is downloaded from https://storage.googleapis.com/istio-build/proxy/

If you need a non-x86 Envoy you *SHOULD* be able to do `USE_LOCAL_PROXY=1 make docker.pilot` to cause the Makefile to do a custom Bazel build of Envoy for another architecture.  However, https://github.com/istio/istio/issues/14337 prevents this.  There is a PR to fix that; I have not tried it.

**Comment by silentdai** [comment]
> envoy is https://github.com/envoyproxy/envoy or not?

@DragonSuper Not it's not 100% envoyproxy/envoy as istio has istio-specific filters that can never merge to envoyproxy upstream. To build envoy in istio:

1. checkout istio/proxy, switch to the version tags you need: tag/1.1.7 for stable
2. run BAZEL_BUILD_ARGS=--config=release make build_envoy at proxy directory. You should have the build out envoy static-linked binary.
3. checkout istio/istio, run `make docker.proxyv2 --dry-run`. Find out which envoy-binary it is suppose to use as the envoy in the image. Something like `out/linux_amd64/release/envoy-73fa9b1f29f91029cc2485a685994a0d1dbcde21`
4. override the envoy binary with your built envoy in step 2.

Warning: The container to guarantee the above instruction succeed is `istio/ci:go1.11-bazel0.22-clang7`. You may need extra packages to build your istio-envoy on non-x86.

Following @esnible 's instruction run `make docker.proxyv2`  and `docker push`

**Comment by wxdao** [comment]
I found this article is very useful: https://medium.com/@nadundesilva/building-istio-from-source-on-linux-be860d660aa7

With the steps it mentions I managed to build all istio components for ARM64, and it just works!

However some gotchas:
- This issue #14337. The PR #14338 I proposed fixes this but it isn't merged yet, so you have to manually modify that file for now.
- [istio/docker/Dockerfile.kubectl](https://github.com/istio/istio/blob/master/docker/Dockerfile.kubectl) is hardcoded to download an amd64 version of kubectl. Change it to your target platform.

**Comment by hustshawn** [comment]
> 3\. make docker.proxyv2 --dry-run

Hi @lambdai , I tried to run `make docker.proxyv2 --dry-run` inside of `istio`, but seems it's not available anymore, especially when I was trying to checkout to `1.7.3`.
```
$ cd istio/istio
$ git checkout 1.7.3
$ make docker.proxyv2 --dry-run
./common/scripts/run.sh make --no-print-directory -e -f Makefile.core.mk docker.proxyv2
```
is there any alternative way so I can build the proxyv2 image only?
