### ISSUE TITLE
Citadel fails readyness check for citadel images built using Golang 1.12, causing e2e-simple to fail

### ISSUE THREAD

**Issue by ericvn** [istio/istio#14573]
**Bug description**

Running `make e2e_simple E2E_ARGS="--skip_cleanup --auth_enable --installer helm"` using images built using Golang 1.12 cause the test to fail (these images can be built locally or using an Istio-builder that was updated to use Golang 1.12). Specifically, the test curl to Istio-citadel returns a RC of 52. Note that this is the _prow_ flavor of the test since I'm using IKS to host my cluster.

**Why is this an issue?** If this particular simple-test is valid, than anyone pulling the istio source and building istio using Golang 1.12 will have an istio setup which will not pass the normal tests passed by the istio images.

I did the test against a k8s 1.11 cluster as well as a 1.13 cluster with no differences.

Exec'ing into the galley container and attempting the curl shows the same
```
k exec -it istio-galley-7f66d4fd8f-s2h85 -n istio-system bash
root@istio-galley-7f66d4fd8f-s2h85:/# curl -i http://istio-citadel:8060/-/ready
curl: (52) Empty reply from server
```

When using images built using the older Istio-builder (uses an older Golang version), the curl result is a RC of 0 is:
```
k exec -it istio-galley-6fdc879dbd-wzwdw -n istio-system bash
root@istio-galley-6fdc879dbd-wzwdw:/# curl -isv http://istio-citadel:8060/-/ready
*   Trying 172.21.155.42...
* Connected to istio-citadel (172.21.155.42) port 8060 (#0)
> GET /-/ready HTTP/1.1
> Host: istio-citadel:8060
> User-Agent: curl/7.47.0
> Accept: */*
>

* Connection #0 to host istio-citadel left intact
root@istio-galley-6fdc879dbd-wzwdw:/# echo $?
0
```

If I update the citadel deployment to instead us the first failing Golang 1.12 build for the citadel container, and repeat the test, the curl now fails with the RC of 52.

I turned on _citadel_ debug and got no additional logging to help identify the issue

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[x] Test and Release
[ ] User Experience

**Expected behavior**

Tests should pass for all Golang version builds

**Steps to reproduce the bug**

1. Create a set of istio images using Golang 1.12.5. In my case, I could this with:
`GOOS=linux make clean init test-bins build docker docker.push  HUB=ericvn TAG=ericvn`

2. Create an k8s cluster and set your context to it. In my case, I use IKS clusters of version 1.11 and 1.13.

3. Run the e2e-simple test. Example using my hug/tag from above:
` make e2e_simple E2E_ARGS="--skip_cleanup --auth_enable --installer helm" HUB=ericvn  TAG=ericvn`

The test should fail. 

4. After running the test, exec into your galley container: ex. `k exec -it istio-galley-7f66d4fd8f-s2h85 -n istio-system bash`. Then run a curl to citadel: `curl -isv http://istio-citadel:8060/-/ready`. Check the RC using `echo $?`. I In a passing instance, one should get a 0. In the failure, it returns 52.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

```
/Users/ericvn/work/go/out/darwin_amd64/release/istioctl version --remote
client version: d6d298327117385a51a51a3a4d65f96961006964
citadel version: c1f14d14423b9b952f208f84dac648ef241ef848
egressgateway version: e851492f958f48161de07db19b40aa3c566b2c3c
galley version: e851492f958f48161de07db19b40aa3c566b2c3c
ingressgateway version: e851492f958f48161de07db19b40aa3c566b2c3c
pilot version: e851492f958f48161de07db19b40aa3c566b2c3c
policy version: e851492f958f48161de07db19b40aa3c566b2c3c
policy version: e851492f958f48161de07db19b40aa3c566b2c3c
sidecar-injector version: e851492f958f48161de07db19b40aa3c566b2c3c
telemetry version: e851492f958f48161de07db19b40aa3c566b2c3c
```
```
k version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T18:55:03Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.10+IKS", GitCommit:"7b8624d43d0e5341ae55537998cddb865607059c", GitTreeState:"clean", BuildDate:"2019-05-08T19:47:50Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

By test. Uses helm

**Environment where bug was observed (cloud vendor, OS, etc)**

IKS, and GKE

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
This is not just a test failure, citadel's readiness check (at a minimum, maybe other issues in Citadel or other components) will not work on go 1.12

```
root@istio-galley-676599ffb4-92kkz:/# curl -v http://istio-citadel:8060/-/ready
*   Trying 10.31.242.193...
* Connected to istio-citadel (10.31.242.193) port 8060 (#0)
> GET /-/ready HTTP/1.1
> Host: istio-citadel:8060
> User-Agent: curl/7.47.0
> Accept: */*
>

* Connection #0 to host istio-citadel left intact
root@istio-galley-676599ffb4-92kkz:/# curl -v http://istio-citadel:8060/-/ready
*   Trying 10.31.242.193...
* Connected to istio-citadel (10.31.242.193) port 8060 (#0)
> GET /-/ready HTTP/1.1
> Host: istio-citadel:8060
> User-Agent: curl/7.47.0
> Accept: */*
>
* Empty reply from server
* Connection #0 to host istio-citadel left intact
curl: (52) Empty reply from server
```

Citadel logs `2019-06-04T21:50:23.103439Z     info    grpc: Server.Serve failed to complete security handshake from "10.28.3.12:46458": tls: first record does not look like a TLS handshake`

**Comment by ericvn** [comment]
Note that a curl against citadel on the monitoring report works:
```
curl -is http://istio-citadel:15014/version
HTTP/1.1 200 OK
Date: Wed, 05 Jun 2019 14:08:56 GMT
Content-Length: 151
Content-Type: text/plain; charset=utf-8
```
so it looks like it might only affect GRPC.

**Comment by ericvn** [comment]
An even simpler test possibly:

From `istio/security/cmd` run `run istio_ca/main.go --self-signed-ca` to start a server.  Then just `curl localhost:8060/-/ready`

**Comment by ericvn** [comment]
Thanks to Greg H for testing on Golang 1.12.0 which also fails the curl with an RC of 52, so appears to be 1.12.x wide.

**Comment by GregHanson** [comment]
@howardjohn the log message can apparently be ignored - it appears in both the working case in go 1.11.10 and earlier as well in the failing case with go 1.12.0 and later

**Comment by ericvn** [comment]
Investigating why simpleTest does not fail during CircleCI testing (which is building with Golang 1.12) but does fail in prow. CircleCI doesn't use the set `--installer helm` which implies that `--set global.enableHelmTest=true` is not set (so uses the _false_ value from values.yaml). This prevents the `Istio-security-test` from running in CircleCi. So CircleCI simpleTest is a subset of the prow tests.

**Comment by ericvn** [comment]
Verified that removing the `installer=helm` from the failing _make _ command noted above (so `make e2e_simple E2E_ARGS="--skip_cleanup --auth_enable" HUB=ericvn  TAG=ericvn`) will pass.

**Comment by ericvn** [comment]
Note that this issue prevents completing #14420 which is targeted for 1.2 at present.

**Comment by ericvn** [comment]
@morvencao I've done some searching today and I don't know that `curl` and GRPC servers mix all that well. I'm not sure if you understand this test fully, but do you think curl against the GRPC server should continue to work regardless go Golang version. Or maybe this test should really use `curl` against a path on the _monitoring port_?

The reason I'm asking you is that it seems this helm test was added as part of https://github.com/istio/istio/pull/10623 which you submitted. 

Also note that it doesn't seem that the helm tests are currently part of the Circle test. I haven't looked to see if that is something that changed after the mentioned PR or not.

**Comment by morvencao** [comment]
@ericvn Thanks for catching this. IMO, for the long-term, the helm test should be removed completely; For the short-term,I'm OK with `curl` against a path on the monitoring port, since it's complete plain http protocol now. 
I'll raise a PR to fix this.

**Comment by ericvn** [comment]
Verified that running the failing test with the changes from #14160 now results in a passing test. Thus I will close this issue.

On to testing the new Golang prow 1.2 images with the above fix to verify things pass with prow.
