### ISSUE TITLE
Allow additional ingress settings to be specified in Helm chart values

### ISSUE THREAD

**Issue by polivbr** [istio/istio#14570]
It would be great if additional ingress settings could be specified in Helm chart values, rather than having to modify the config map after installation.

Specifically, I'd like to be able to specify values for:

ingressClass
ingressControllerMode

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

**Comment by morvencao** [comment]
@polivbr What do you mean by `additional ingress settings`? ingress settings for addon service, eg, kiali, jaeger ?

**Comment by polivbr** [comment]
Sorry... I should have been more clear. I'm referring to the ingress gateway.

In my environment I want the Istio ingress gateway to serve as the default gateway of the cluster, so I wind up having to add the following entries to the istio configmap (under the mesh key):

ingressClass: istio
ingressControllerMode: DEFAULT

It would be nice to be able to specify these as helm chart values, in the same way that k8sIngress.gatewayName can be specified.

**Comment by howardjohn** [comment]
We will likely merge values.yaml and meshconfig to be a single structure in the near future, in which case this would be satisfied. Until then, we are trying to avoid bloating values.yaml with more and more configuration options, so the config is effectively frozen, so I do not think this can be done.
