### ISSUE TITLE
tar.gz file is not actually gzipped

### ISSUE THREAD

**Issue by sdake** [istio/istio#14581]
(This is used to report product bugs, please visit <https://discuss.istio.io> for questions on using Istio)

**Bug description**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[X] Test and Release
[ ] User Experience

**Expected behavior**

file should be gzipped

**Steps to reproduce the bug**
```
sdake@beast-01:~/pil$ tar -xzvf pilot.tar.gz 
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
sdake@beast-01:~/pil$ file pilot.tar.gz 
pilot.tar.gz: POSIX tar archive
sdake@beast-01:~/pil$ tar -xvf pilot.tar.gz 
36e56f1ee15757d532948ea0cbe419c97de705433b1d03d6896cda9b68e70491.json
3fc24118a44c46fa6516bac4d2593be987c2a218ec2b3ef05be04bc71f443f23/
3fc24118a44c46fa6516bac4d2593be987c2a218ec2b3ef05be04bc71f443f23/VERSION
3fc24118a44c46fa6516bac4d2593be987c2a218ec2b3ef05be04bc71f443f23/json
3fc24118a44c46fa6516bac4d2593be987c2a218ec2b3ef05be04bc71f443f23/layer.tar
406738fb728f1184975fc09f1bac758732cb9a1eb156ae89f58f085cb99758c3/
406738fb728f1184975fc09f1bac758732cb9a1eb156ae89f58f085cb99758c3/VERSION
406738fb728f1184975fc09f1bac758732cb9a1eb156ae89f58f085cb99758c3/json
406738fb728f1184975fc09f1bac758732cb9a1eb156ae89f58f085cb99758c3/layer.tar
44c3410e879ee180ebf54e77f460302ccd1b176a74ca85c252d3f57e551fcc56/
44c3410e879ee180ebf54e77f460302ccd1b176a74ca85c252d3f57e551fcc56/VERSION
44c3410e879ee180ebf54e77f460302ccd1b176a74ca85c252d3f57e551fcc56/json
44c3410e879ee180ebf54e77f460302ccd1b176a74ca85c252d3f57e551fcc56/layer.tar
58280bc41cebc19fa3839998fcbf05f7d15eaed908a3ef0fe5f9aa1e423eb441/
58280bc41cebc19fa3839998fcbf05f7d15eaed908a3ef0fe5f9aa1e423eb441/VERSION
58280bc41cebc19fa3839998fcbf05f7d15eaed908a3ef0fe5f9aa1e423eb441/json
58280bc41cebc19fa3839998fcbf05f7d15eaed908a3ef0fe5f9aa1e423eb441/layer.tar
5ebf89e1f088aefd880aae471d9134a8a1e7ec280eef92d14eedaba39d610c33/
5ebf89e1f088aefd880aae471d9134a8a1e7ec280eef92d14eedaba39d610c33/VERSION
5ebf89e1f088aefd880aae471d9134a8a1e7ec280eef92d14eedaba39d610c33/json
5ebf89e1f088aefd880aae471d9134a8a1e7ec280eef92d14eedaba39d610c33/layer.tar
7977e5d7f5bae1fc8d251116533fe8f7e17af6353b722f0e3fc18f20c524a97c/
7977e5d7f5bae1fc8d251116533fe8f7e17af6353b722f0e3fc18f20c524a97c/VERSION
7977e5d7f5bae1fc8d251116533fe8f7e17af6353b722f0e3fc18f20c524a97c/json
7977e5d7f5bae1fc8d251116533fe8f7e17af6353b722f0e3fc18f20c524a97c/layer.tar
ae45c75fb12ac7b7b83f5797690ea9f92ec6dc5ad5e3fbf32931eb4d5ff700ad/
ae45c75fb12ac7b7b83f5797690ea9f92ec6dc5ad5e3fbf32931eb4d5ff700ad/VERSION
ae45c75fb12ac7b7b83f5797690ea9f92ec6dc5ad5e3fbf32931eb4d5ff700ad/json
ae45c75fb12ac7b7b83f5797690ea9f92ec6dc5ad5e3fbf32931eb4d5ff700ad/layer.tar
ea97ca88c3e695ca14064c1a27e63e2999c30f0fd28bfdd72ed25b0e1168ed85/
ea97ca88c3e695ca14064c1a27e63e2999c30f0fd28bfdd72ed25b0e1168ed85/VERSION
ea97ca88c3e695ca14064c1a27e63e2999c30f0fd28bfdd72ed25b0e1168ed85/json
ea97ca88c3e695ca14064c1a27e63e2999c30f0fd28bfdd72ed25b0e1168ed85/layer.tar
manifest.json
repositories
sdake@beast-01:~/pil$ 
```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
`istio-release-1.2-20190604-09-16`

**How was Istio installed?**
didn't do that.

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
Where is `pilot.tar.gz` from?

**Comment by sdake** [comment]
@howardjohn - link is here:
https://gcsweb.istio.io/gcs/istio-prerelease/daily-build/release-1.2-latest-daily/docker/

This is produced by the makefile `docker.mk` IIRC.

**Comment by ibm-jason** [comment]
@sdake, @howardjohn: 

I just pulled down the pilot.tar.gz file from the URL you mentioned above, and it seems to untar and gunzip fine. can either of you try again?

**Comment by irisdingbj** [comment]
https://gcsweb.istio.io/gcs/istio-prerelease/daily-build/release-1.0-20190901-13-15/docker/  
Verified manually using build from above location:
tar -xzvf pilot.tar.gz 
x 2ff8468ce2734509af6280902a3718b8f862b3e155e747bfbde7aa2147f50a7f/
x 2ff8468ce2734509af6280902a3718b8f862b3e155e747bfbde7aa2147f50a7f/VERSION
x 2ff8468ce2734509af6280902a3718b8f862b3e155e747bfbde7aa2147f50a7f/json
x 2ff8468ce2734509af6280902a3718b8f862b3e155e747bfbde7aa2147f50a7f/layer.tar
x 406738fb728f1184975fc09f1bac758732cb9a1eb156ae89f58f085cb99758c3/
x 406738fb728f1184975fc09f1bac758732cb9a1eb156ae89f58f085cb99758c3/VERSION
x 406738fb728f1184975fc09f1bac758732cb9a1eb156ae89f58f085cb99758c3/json
x 406738fb728f1184975fc09f1bac758732cb9a1eb156ae89f58f085cb99758c3/layer.tar
x 44c3410e879ee180ebf54e77f460302ccd1b176a74ca85c252d3f57e551fcc56/
x 44c3410e879ee180ebf54e77f460302ccd1b176a74ca85c252d3f57e551fcc56/VERSION
x 44c3410e879ee180ebf54e77f460302ccd1b176a74ca85c252d3f57e551fcc56/json
x 44c3410e879ee180ebf54e77f460302ccd1b176a74ca85c252d3f57e551fcc56/layer.tar
x 5ebf89e1f088aefd880aae471d9134a8a1e7ec280eef92d14eedaba39d610c33/
x 5ebf89e1f088aefd880aae471d9134a8a1e7ec280eef92d14eedaba39d610c33/VERSION
x 5ebf89e1f088aefd880aae471d9134a8a1e7ec280eef92d14eedaba39d610c33/json
x 5ebf89e1f088aefd880aae471d9134a8a1e7ec280eef92d14eedaba39d610c33/layer.tar
x 68e7e96475f0c63c19c90b311e77ed678294726fd396f2f7c3cdc073ccb002cd/
x 68e7e96475f0c63c19c90b311e77ed678294726fd396f2f7c3cdc073ccb002cd/VERSION
x 68e7e96475f0c63c19c90b311e77ed678294726fd396f2f7c3cdc073ccb002cd/json
x 68e7e96475f0c63c19c90b311e77ed678294726fd396f2f7c3cdc073ccb002cd/layer.tar
x b56a923a0f4f39416ab0ecb44e9da3422329898540e68be0028d4c17751f05f5.json
x d9d8b2b532b7b0ee7c3eae11910830e0cc9f52f512ac016f381a4516373d8b79/
x d9d8b2b532b7b0ee7c3eae11910830e0cc9f52f512ac016f381a4516373d8b79/VERSION
x d9d8b2b532b7b0ee7c3eae11910830e0cc9f52f512ac016f381a4516373d8b79/json
x d9d8b2b532b7b0ee7c3eae11910830e0cc9f52f512ac016f381a4516373d8b79/layer.tar
x db350a25378cb156411a2fd8daad0c7bf797a97aaaa8dc45cec97c79fd9171d5/
x db350a25378cb156411a2fd8daad0c7bf797a97aaaa8dc45cec97c79fd9171d5/VERSION
x db350a25378cb156411a2fd8daad0c7bf797a97aaaa8dc45cec97c79fd9171d5/json
x db350a25378cb156411a2fd8daad0c7bf797a97aaaa8dc45cec97c79fd9171d5/layer.tar
x ea97ca88c3e695ca14064c1a27e63e2999c30f0fd28bfdd72ed25b0e1168ed85/
x ea97ca88c3e695ca14064c1a27e63e2999c30f0fd28bfdd72ed25b0e1168ed85/VERSION
x ea97ca88c3e695ca14064c1a27e63e2999c30f0fd28bfdd72ed25b0e1168ed85/json
x ea97ca88c3e695ca14064c1a27e63e2999c30f0fd28bfdd72ed25b0e1168ed85/layer.tar
x manifest.json
x repositories


also checked the scripts has used `gzip`

**Comment by irisdingbj** [comment]
@sdake please check above comments. If no objections, I will close this issue.

**Comment by sdake** [comment]
@irisdingbj tar has varyiing behaviors on different platforms.

Please use the file command to determine what hte metadata is.  The file type should be of type gzip or tar/gzip, not tar alone.  In the past the file was only tar, but misnamed.

**Comment by sdake** [comment]
1.3 is also broken: https://gcsweb.istio.io/gcs/istio-prerelease/daily-build/release-1.3-latest-daily/docker/

the `file` command shows these are posix archives, and not gzipped.  Yet the extension ends in gzip.  @howardjohn - is it possible that in some way gcs is mishandling these files on upload?

**Comment by irisdingbj** [comment]
finally found the issue: we will update the images later in ocker_tag_push_lib.sh and in this it missed the gzip step and remain the file name as tar.gz.
