### ISSUE TITLE
Allow Ingress gateway SDS to search all namespaces for certificate secrets.

### ISSUE THREAD

**Issue by mmckane** [istio/istio#14598]
Currently when using SDS on the ingress gateway to load certificate secrets it forces you to create the certificates secrets in the same namespace as the gateway (or a single namespace set by an env variable). This complicates secret/certificate management in a scenario where you have a shared gateway used by multiple k8s namespaces, where I only want one main ingress gateway to my cluster. When using tools like cert-manager I now need rights to the gateway namespace in addition to the original namespace I deploy my project to.

**It would be nice if the user had the choice to set namespace lookup options as detailed.**
- Default option to lookup secrets in same namespace as gateway.
- Option to override to a specific namespace in the helm chart where all secrets are example:#13345
- Option to set env to * which allows nodeagent secretfetcher to look for secrets in all namespaces it has access to.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience

**Comment by FrederikNS** [comment]
When using normal Kubernetes Ingress, the ingress controller looks in the same namespace as the ingress object.

In my opinion it would make sense for istio to look for the secret in the same namespace as where the gateway is defined. Or at the very least have the option of adding a `spec.servers.[n].tls.credentialNamespace` key to the gateway.

**Comment by diemtvu** [comment]
Should it be better to run another gateway instance(s) on the other namespaces? I don't think accessing secrets cross namespace is the right model (nor supportable)

**Comment by FrederikNS** [comment]
@diemtvu why wouldn't it be "supportable"? Implementation wise, it simply another api call to the Kubernetes API server.

One gateway instance would also require people to use different ports for each gateway. That would be very impractical in my opinion.

But it also don't understand why you think it's the "wrong" model? That is already how the official Kubernetes Nginx Ingress works, and no one is complaining about that. In our organization we have a "you build it, you run it" approach. Therefore each Dev team is allowed to build their service and should take steps to secure it, such as enabling TLS. If I want to allow the Dev teams to create certificates via self-service, it would make a lot of sense to let them store the certificate secret alongside their deployments in a namespace. As it stands now, I need to allow all the developer teams to have access to manage certificates in the Istio-system namespace. So not only can they read each others certificates, they can also inadvendently break each others certificates.

**Comment by diemtvu** [comment]
I was thinking the secret volume mount when I said not supportable. You may be right that it just an API call. However, you need to change K8s RBAC so that `node-agent` (the one who fetch secret and serve it to Envoy) can access secrets in other namespaces; and I have a uneasy feeling about this.

**Comment by diemtvu** [comment]
Actually, I take it back. Looks like the status quo already grant permission to read all secrets. We will discuss to revise this and see if we can change to serve key from any namespace's secrets.

**Comment by Starefossen** [comment]
That would be a huge benefit for us if retrieving keys from multiple namespaces was possible. It already retrieve Gateways across namespaces.

**Comment by mmckane** [comment]
@diemtvu just to add when I wrote this issue up, the helm chart for gateways was setup to deploy a node-agent sidecar running as a service account that only had k8s RBAC rules to read secrets from the namespace the gateway pods are deployed to. The secretsfetcher and rbac rules for the service account can be changed to another namespace, which I tested works mostly using the changes outlined here #18529.

At a minimum changing the secretfetcher in the node-agent pod to search all namespaces it had access to via RBAC would be huge, and as it sits now probably wouldn't change how it's working today. It would give users the functionality to choose where the secrets live using RBAC to manage secretfetcher access to other namespaces, could be all or only some.

**Comment by wpbeckwith** [comment]
I literally just searched "sds secret in same namespace as ingressgateway" because I was wondering if I did something wrong because the only way TLS worked was to put the secret in the istio-system namespace.  This really should be changed.  What we currently do is use cert-manager to provision wildcard certs (*.subdomain.example.com) in a specific namespace.  The individual teams creating can then just deploy an empty secret in their namespace and the secret/configmap replicator will copy the wildcard secret to their namespace.  However, for istio sds to work we also need to copy it into the istio-system namespace and this just seems wrong on so many levels.

**Comment by Starefossen** [comment]
Well, to be honest copying a wildcard cert across namespaces is also wrong in so many ways. Why don’t you use cert-manager to actually provisioning individual certs directly to the namespaces using the Certificate object?

**Comment by wpbeckwith** [comment]
@Starefossen We do use cert-manager for individual certs in the desired namespaces, that's how we found the original issue we are all commenting on. We currently only use the wildcard certs for our PR preview builds which can be hundreds/week.  If we used individual certs for these short lived builds then we would slow the CD builds down while a cert is fetched for every PR as well as hit the Let's Encrypt limit for certs/week.

**Comment by mt-inside** [comment]
I agree with all the above: we run a small number of physical gateways (1-m) and have n namespaces with service teams own. They use cert-manager to get LE certs in their namespace; I really don't want to give them *write* access to *secrets* in `istio-system`. It would be very very useful for `credentialName` to be of the form `namespace/name`. We're running with SDS on so it's fine for this support to be SDS deployments only (to avoid volume-mount headaches), and I'm happy to give "istio" full permissions to secrets, well more than I am happy to give it to the world.

**Comment by igorcezar** [comment]
Is there any updates on this? It would be great if Istio could get the secrets from the same namespace where the Gateway resource is instead of istio-system, just like Nginx Ingress does.

**Comment by myidpt** [comment]
Sorry about the delay. We'll discuss this in the WG meeting this week.

**Comment by howardjohn** [comment]
I think we discussed this in the last WG meeting and decided to not do this as there are major security implications to giving ingress gateway, which is exposed to public internet, cluster wide read access to secrets?

**Comment by myidpt** [comment]
We didn't have time to cover this in today's meeting.
Today we have managed to avoid istiod accessing secrets in other namespaces. Granting istiod the permission to access secrets could be more dangerous since it's by default exposed to the public network.

With above said, the question here is do we want to offer such an option (not default) for users? What can be done to avoid / mitigate the potential vulnerabilities?

**Comment by howardjohn** [comment]
I am not really against giving an option to users (off by default) and they can make their own decisions on whether its secure or not. We do need to figure out how cross namespace references work.

1) we can look only in the namespace of the Gateway object. But in the future we may want all Gateways to reside in the same namespace as the deployment so that would undo this basically
2) allow ns/secret in credentialName

**Comment by igorcezar** [comment]
It would be nice if this was a option when installing Istio, with off by default as @howardjohn said. 

The default could be look in the namespace of the Gateway object if there is no namespace defined in credentialName, otherwise it would get from "ns/secret" in credentialName.

Our policy here is that all resources of an application must be in application's namespace (or any namespace the application owns). But with Istio that's not possible because we need to create the secret in istio-system namespace, or give access for the application to do so, which is not the best option.

**Comment by lodejard** [comment]
I'm actually a quite surprised that the Gateway's namespace is not where the secret is found.

For context - we started with nginx ingress, moved to contour to adopt envoy, and are now moving to istio which is more fully featured. Both nginx and contour support cert-manager and k8s ingress objects in the same way. Because a tenant has the ability to create a certificate object in their namespace, cert-manager will allocate and store the secret in that namespace. Because a tenant has the ability to create an ingress object in their namespace, nginx and contour's proxy layer will use the secret in that namespace to provide host credentials. But the tenant rbac does not provide abilities to see other tenant namespaces, or see the namespace where the ingress systems are installed.

I'm at a bit of a loss how to use istio in a similar way. Our assumption was the same as @igorcezar mentioned, that by policy we would have a tenant application deploy as Deployment+Service+Certificate+Gateway+VirtualService --- giving each team the ability to manager Certificate objects in a shared namespace is a non-starter.

**Comment by fraserdarwent** [comment]
Same use case as people above. Multi tenant cluster, wanting to give tenants access to deploy pods, services, and certificates  within their own namespace(s) to expose their services on the gateway, but not give them permissions on Istio system namespace.

**Comment by mmckane** [comment]
Not super up to date as to what has been going on with SDS and ingress gateway @howardjohn but does this #24667 proposal possibly help with this story?

**Comment by howardjohn** [comment]
@mmckane yes one of the major motivators for that proposal is to enable this use case

**Comment by caffeinism** [comment]
It has been 14 months since the issue was opened, is there any progress?

**Comment by howardjohn** [comment]
@caffeinism yes there is active work on this. See https://docs.google.com/document/d/1nwTh2g7FgdkC8suc3SHZ5le_4Rkm8YvLY8Cgah4cm-I and https://github.com/istio/istio/issues/24667 and https://docs.google.com/document/d/1DEUkk0ocrD_oAH0h8TOUIC94Lf8msDXJb9lyNWlX_Ho/. See https://istio.io/latest/about/community/join/ for drive access

**Comment by caffeinism** [comment]
@howardjohn thanks

**Comment by mmckane** [comment]
@howardjohn was this implemented with the closure of #24667 and the documentation hasn't been updated yet? Or was the ability to specify the namespace in the credentialName dropped from the PR?

For example can I specify:
- Secret format will change from <k8s-secret-name> to kubernetes|<secret-name>.<secret-namespace> to support future changes

**Comment by howardjohn** [comment]
@mmckane that PR lays the groundwork but we still need to design the auth story for authorizing a gateway to access another namespace. The design is in https://docs.google.com/document/d/1nwTh2g7FgdkC8suc3SHZ5le_4Rkm8YvLY8Cgah4cm-I.

**Comment by gimler** [comment]
any update?

**Comment by howardjohn** [comment]
https://docs.google.com/document/d/1gDhj058q2PKKI9SWpxE23ExEXdOkLiueT8JA_oEJ8Mo describes the long term plan. But might be quite long

**Comment by mowies** [comment]
any updates on this?

**Comment by ldemailly** [comment]
Having the secret in same namespace as gateway seems like an easier/safer change than full flexibility and would cover most of the multi tenant use case. We also have that, shared ingresses but multi tenant app/svc that we want to be self contained in their own namespace.

I wonder how hard would it be to workaround this on the cert manager side(ie have cert-manager writes to istio-system even if the cert request is in another namespace) - or a standalone secret copier?

**Comment by ldemailly** [comment]
Looks like this may help https://cert-manager.io/docs/faq/kubed/

**Comment by howardjohn** [comment]
https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io/v1alpha2.ReferencePolicy
will define a way to specify if cross namespace reference is allowed. We
will implement it as part of
https://istio.io/latest/docs/tasks/traffic-management/ingress/gateway-api/

**Comment by sathieu** [comment]
While I agree that k8s gateway API has many improvement for advanced usecases, the ingress API is properly covering simple cases and should not become a second-class citizen. This is explicitely said in [the FAQ](https://gateway-api.sigs.k8s.io/faq/):

> **Will Gateway API replace the Ingress API?**
> A: No. The Ingress API is GA since Kubernetes 1.19. There are no plans to deprecate this API and we expect most Ingress controllers to support it indefinitely.

Also k8s gateway API is currently v1alpha1 (with v1alpha2 *unreleased*). It looks premature to stop improving support for an API that graduated as stable [in 1.19](https://kubernetes.io/blog/2020/08/26/kubernetes-release-1.19-accentuate-the-paw-sitive/#ingress-graduates-to-general-availability), less than 14 months ago!

**Comment by sathieu** [comment]
@ldemailly [Kubitus Ingress Operator](https://gitlab.com/kubitus-project/kubitus-ingress-operator) works too, and also handles correctly secrets with the same name accross namespaces(it uses `'ingress-{namespace}-{secret_name}'` as name, hashing it if longer than 63 chars).

**Comment by tgeci** [comment]
@foal : Thanks! I decided to use the kubed approach. It's currently for me the most practicable way. 

There is a way to reference to gateways in other namespaces in `VirtualServices`:
```  
gateways:
  - some-config-namespace/my-gateway
```
But I don't know if it`s applicable for Ingress Resources as well.

**Comment by mjwhale** [comment]
> > Looks like this may help https://cert-manager.io/docs/faq/kubed/
> 
> Just to circle back for anyone wanting all of a set of service in a single namespace, the above works great, you just need 1 annotation and a template for the secret, e.g.
> 
> ```yaml
> apiVersion: cert-manager.io/v1
> kind: Certificate
> spec:
>   secretTemplate:
>     annotations:
>       # Request the kubed sync to matching namespaces
>       kubed.appscode.com/sync: "cert-manager-tls=istio-system"
> ```

From my limited testing, it would appear that with kubed configured, any user can overwrite any secret that is synchronized to istio-system if two namespaces use the same secretname in the Certificate definition.

Is there any controls that can be used to prevent this from happening other than naming conventions?

**Comment by letmestudy** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by howardjohn** [comment]
This is supported now via https://istio.io/latest/docs/tasks/traffic-management/ingress/gateway-api/

**Comment by mmckane** [comment]
@howardjohn Yes it works, but I am not really sure this fixes the original issue. Like outlined above this has the same issue as the original post. I now need to give developers access to modify a shared gateway CR in istio-system, to not only add the listener but also a certificate reference (this is now a way worse experience than before, I could at least have them define and create their own gateway that was attached to a pre-created grouping of envoy proxies in the cluster). This new Gateway could also have other team's/tenants DNS in it, which pushes me to somehow needing to automate update of this as k8s RBAC isn't granular enough to block someone from changing team A's entry.

If this were a perfect world, the separation of concerns I would prefer on the admin side of things is to define a shared-gateway and set TLS min/max negotiation rules. That's it. I don't want to have to manage more things in the gateway spec in a protected namespace. Let me setup wildcard gateways and define which namespaces can setup routes via a label or something, Cert-Manager and DNS is so easy to use to get certificates the gateway admin team doesn't need to be looped into the process anymore. Designing the gateway in this way forces my team to manage each endpoint and what certificate/DNS maps to which secret/namespace, this creates Toil for my team every time one of these needs an update. Better to just give the developer control to define these from their namespace.

**Comment by letmestudy** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by howardjohn** [comment]
@mmckane all valid concerns. The gateway-api is still evolving, in particular around this type of thing. For example, https://github.com/kubernetes-sigs/gateway-api/pull/1085 (doesn't quite solve this). In an earlier iteration there was the ability to define the TLS references in other namespaces completely, but it was removed as the solution had some issues - but the intent is to bring it back in some form.

**Comment by howardjohn** [comment]
This is now implemented as part of https://istio.io/latest/docs/tasks/traffic-management/ingress/gateway-api/. Due to security concerns in the older API's resource model, allowing cross namespace secret references would not be secure so this is not planned for any other API. Thanks everyone
