### ISSUE TITLE
Chart's bug version should be bumped for Releases

### ISSUE THREAD

**Issue by bradenwright** [istio/istio#14593]
**Bug description**
If you download releases from https://github.com/istio/istio/releases bug version in the Chart.yaml are not bumped so:

istio-1.1.7 Chart.yaml
```
apiVersion: v1
name: istio
version: 1.1.0
appVersion: 1.1.0
```

and 1.1.6 looks identical:
```
apiVersion: v1
name: istio
version: 1.1.0
appVersion: 1.1.0
```

I and I'm sure most people expect semantic versioning and actually bumping of bug versions.  Especially when I've been told that releases are the source of truth.  I still think with proper versions a public helm repo would work well.  But I brought that up https://github.com/istio/istio/issues/12923

**Affected product area (please put an X in all that apply)**

[X] Configuration Infrastructure
[X] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[X] Test and Release
[X] User Experience

**Expected behavior**

Chart versions are bumped, for at least the chart.  App version should probably be used properly or removed as well.

**Steps to reproduce the bug**

Download the release and explode, look at https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/Chart.yaml#L3-L4

Or just look at https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/Chart.yaml#L3-L4 easy to see version is 1.1.0

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
at least 1.1.7, 1.1.6 I assume all releases are effected

**How was Istio installed?**
Via Helm

**Environment where bug was observed (cloud vendor, OS, etc)**
All envs

**Comment by howardjohn** [comment]
This is fixed in 1.1.8, which is releasing in days

See https://github.com/istio/istio/issues/14290  https://github.com/istio/istio/issues/14243

**Comment by bradenwright** [comment]
Excellent!  That will be really nice!  Do you want me to close this issue now, or wait til 1.1.8 is released?

**Comment by howardjohn** [comment]
@bradenwright we can close this, generally we try to close issues when no more work is done so we don't get lost in too many issues. 

This also prompted me to manually verify the 1.1.8 pre-release (it is built but not released yet) and it all looks good

**Comment by bradenwright** [comment]
@howardjohn looks like 1.1.8 is out and it still has a version of 1.1.0 in Chart.yaml, hopefully it'll make it into the next release.

**Comment by howardjohn** [comment]
hm I thought j checked it.. will look again tomorrow

**Comment by howardjohn** [comment]
`curl https://storage.googleapis.com/istio-release/releases/1.1.8/charts/index.yaml` shows 1.1.8

Chart.yaml in the release binary also shows `install/kubernetes/helm/istio/Chart.yaml` also shows 1.1.8.

Chart.yaml from `https://storage.googleapis.com/istio-release/releases/1.1.8/charts/istio-1.1.8.tgz` also shows 1.1.8 in the Chart.

Not sure what I am missing. Where did you see 1.1.0?

**Comment by bradenwright** [comment]
https://github.com/istio/istio/blob/1.1.8/install/kubernetes/helm/istio/Chart.yaml#L3
https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/Chart.yaml#L3

both show `1.1.0` as did the tar.gx I downloaded from releases:

https://github.com/istio/istio/releases/tag/1.1.8
https://github.com/istio/istio/archive/1.1.8.tar.gz

**Comment by howardjohn** [comment]
@bradenwright we don't update the repo versions, users should not install from the Github repo. Instead we process the version # when we build a release

You should be using https://github.com/istio/istio/releases/download/1.1.8/istio-1.1.8-linux.tar.gz (from the release page). See https://istio.io/docs/setup/kubernetes/download/ (although this points to 1.1.7, I think we need to trigger a rebuild of the site for it to say 1.1.8)

We should probably change the version number in our repos to `dev` or something so people are less likely to try to use it.

By the way, if you use our github repos the images are also set to the latest daily builds. You will run into issues if you use those in prod, so please don't if you are! We want to make sure you get only our stable tested versions

**Comment by bradenwright** [comment]
So it's intentional that https://github.com/istio/istio/archive/1.1.8.tar.gz doesn't have bumped release but  https://github.com/istio/istio/releases/download/1.1.8/istio-1.1.8-linux.tar.gz does?

That seems weird to me, I downloaded the generic b/c I'm using the charts across mac/windows/linux, I assume others may do the same.

**Comment by howardjohn** [comment]
I am pretty sure the first link is just our repo turned into a tgz file. So its the same as doing a `git clone`. Where did you get that actually, I have never seen that.

That is good feedback that it is confusing for users though

**Comment by bradenwright** [comment]
Gotcha... and at least we are getting stuff documented here so if others run into it, should be easy to resolve

**Comment by Amos-85** [comment]
I'm curious why don't you publish the index.yaml before the published versions in the url so we can get a dynamic version updates instead of lock the repo to specific version.

**Comment by howardjohn** [comment]
@Amos-85 we aren't specifically against doing that or anything, we just haven't done it yet. The work is being tracked at https://github.com/istio/istio/issues/12974.

Spoke with some people and we hopefully made the docs more clear and the release is fixed so I am going to close this. Thanks
