### ISSUE TITLE
istioctl verify-install usage

### ISSUE THREAD

**Issue by esnible** [istio/istio#14595]
`istioctl verify-install --help` gives usage examples that still include "experimental":

```
		istioctl experimental verify-install
		
		# Verify that the deployment matches the istio-demo profile
		istioctl experimental verify-install -f istio-demo.yaml
		
		# Verify the deployment matches a custom Istio deployment configuration
		istioctl experimental verify-install -f $HOME/istio.yaml
```

The command is not under experimental, so the examples should not include "experimental".

Also I am not sure if the default for `--enableVerbose` should be `TRUE`.  If the user does not specify --enableVerbose they probably don't want verbose output.

**Comment by howardjohn** [comment]
Fixed by https://github.com/istio/istio/pull/14470

**Comment by linsun** [comment]
Note the fix is in master - are we okay with leaving verify-install in both experimental and stable?  Seems quite confusion to be in both.

@irisdingbj @fpesce cc
