### ISSUE TITLE
Ensure user gateways can be created in operator, preferably through values.yaml

### ISSUE THREAD

**Issue by ostromart** [istio/istio#14592]
Operator values.yaml Go struct schema (https://github.com/istio/operator/pull/2/) currently doesn't support user defined gateways. This must be handled either through a custom unmarshal function, or by migrating user gateway creation to the operator CRD.

**Comment by costinm** [comment]
It's an advanced feature, need to get the basics working first. Using multiple gateways can continue to use templates.
