### ISSUE TITLE
Update installation files to deploy cluster-wide in istio-system namespace

### ISSUE THREAD

**Issue by ayj** [istio/istio#146]
It would be nice to run the istio system components in their own kubernetes namespace similar to kube-system. This would be setup as part of the overall istio installation. This was originally planned for alpha release but was prioritized for post-alpha/beta timeframe.

**Comment by andraxylia** [comment]
Changed the title to reflect the planned changes.

**Comment by linsun** [comment]
Any reason why we need istio-system vs just using kube-system?  I'm asking since many other system tools are installed there like calico, helm tiller, draft etc.

**Comment by andraxylia** [comment]
We evaluated the option of installing in kube-system and decided it is preferable to use a separate namespace to allow uninstall by simply deleting the namespace. It is true some other components prefer kube-system, but there is no real advantage there.
BTW, the istio namespace will not be hardcoded to "istio-system" in the code, it can be any namespace. The simple installation files might have it, though.

**Comment by linsun** [comment]
I think it is just what people are expecting to see, and it is easier to configure permissions / ACLs to put stuff in that namespace.  You'll get less questions too.   :)  Ok good to know it is not hardcoded so we could put it in kube-system if we wanted that way.

**Comment by andraxylia** [comment]
Sure, but in in mind kube-system is not easier to configure than any other namespace, given the same starting permissions.

**Comment by sakshigoel12** [comment]
Mostly done, only clean up pending. and renaming files and get ride of rbac files

**Comment by andraxylia** [comment]
Fixed in #860
