### ISSUE TITLE
JWT tokens without exp claim are rejected by Istio

### ISSUE THREAD

**Issue by yangminzhu** [istio/istio#14603]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
Original user report: 

> Hey guys, we were testing the JWT auth and noticed that JWT tokens are required to have the `exp` field or they wont validate, im wondering if thats is a hard requirement or can we have non expiring jwts?

> code-wise if the `exp` claim is not present then the JWTs should verify. https://github.com/envoyproxy/envoy/blob/master/source/extensions/filters/http/jwt_authn/authenticator.cc#L143 

> I found that too. although it does not match Istio https://github.com/istio/proxy/blob/master/src/envoy/http/jwt_auth/jwt_authenticator.cc#L103-L111

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience

**Expected behavior**
It looks like we can align with the envoy JWT filter allow JWT token without `exp` claim and this could be a quick change in the Istio jwt filter. (long time I think we will move to use the Envoy JWT filter anyway, but that require more work)

cc @qiwzhang @diemtvu 

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by nickrmc83** [comment]
Can the fix also include handling of the `nbf` claim too to match the envoy filter's capabilities.

**Comment by nmnellis** [comment]
We noticed that the filter in envoys github has diverged from the one in istio. It may be worth comparing them and syncing. https://github.com/envoyproxy/envoy/blob/master/source/extensions/filters/http/jwt_authn/authenticator.cc#L143
https://github.com/istio/proxy/blob/master/src/envoy/http/jwt_auth/jwt_authenticator.cc#L103-L111

**Comment by pitlv2109** [comment]
We're in the process of updating Istio authentication filter to use Envoy jwt filter. Stay tuned!

**Comment by yangminzhu** [comment]
Closing this one as we will switch to use the Envoy JWT filter in 1.3.
