### ISSUE TITLE
Namespace annotation for sidecar injection

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1460]
@andraxylia commented on [Thu Oct 12 2017](https://github.com/istio/old_pilot_repo/issues/1463)

Need to support annotation for sidecar.istio.io/inject for namespaces, similar to the one for workload, but higher precedence. IncludedNamespaces/ExcludedNamespaces are not under the control of the regular user.

https://istio.io/docs/setup/kubernetes/sidecar-injection.html#configuration-options

Moreover, it should work with hierarchical namespaces.

Precedence will be this and should be uniform with other Istio precedence rules:
- workload
- current-namespace
- parent and ancestor namespace up the chain
- includeNamespace/excludeNamespace in the config map
- global policy flag in the config map

---

@gyliu513 commented on [Thu Oct 12 2017](https://github.com/istio/old_pilot_repo/issues/1463#issuecomment-336324807)

@andraxylia I will work on this in 0.3 release

/cc @ayj @linsun @rshriram 

---

@andraxylia commented on [Fri Oct 13 2017](https://github.com/istio/old_pilot_repo/issues/1463#issuecomment-336570653)

thanks @gyliu513

**Comment by costinm** [comment]
Is this done, can it be done in 0.8 ?

**Comment by ayj** [comment]
We can consider this done. Automatic injection can be white/blacklisted for specific sets of namespaces using the Kubernetes namespaceSelector in the Webhook registration YAML. For example, the following only runs the webhook on pods whose namespace is associated with the `environment` of `foo` or `bar`.

```yaml
namespaceSelector:
  matchExpressions:
  - key: environment
    operator: In
    values:
    - foo
    - bar
```

Likewise, you could enable injection cluster-wide by default, but blacklist special system namespaces labeled with `istio-injection=disabled`.

```yaml
namespaceSelector:
  matchExpressions:
  - key: istio-injection
    operator: NotIn
    values:
    - disabled
```

Hierarchical namespaces isn't a real thing in k8s, but I imagine it would also use the namespaceSelector mechanism if it existed.

Per-workload injection overrides within namespaces can be controlled with the pod template spec annotation `sidecar.istio.io/inject`.



References to k8s webhook registration and namespaceSelector:
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.9/#webhook-v1beta1-admissionregistration
https://github.com/kubernetes/api/blob/master/admissionregistration/v1beta1/types.go#L145
