### ISSUE TITLE
Tracing not working with istio cni

### ISSUE THREAD

**Issue by itsmurugappan** [istio/istio#14628]
I am using istio 1.1.1 on k8s 1.12 with istio-cni enabled. In jaeger i just see ingressgateway spans. I dont see other services. On all my nodes i have 10-calico.conflist with istio cni section. Without cni its working.
Trace sampling set to 100 in istio-pilot

I downloaded istio curl -L https://git.io/getLatestIstio | ISTIO_VERSION=1.1.1 sh - 
From version 1.1.3 onwards i dont even see the charts directory under install/kubernetes/helm as mentioned in https://istio.io/docs/setup/kubernetes/additional-setup/cni/. 

Dont think it is related with this issue https://github.com/istio/istio/issues/13171

**Comment by john-a-joyce** [comment]
@itsmurugappan - can you share some debug information from the system and/or confirm the following items.

1.  That you see the istio-cni deamonset running on all the nodes 
2.   The istio-cni pod is running
3.   The image ID used for the Istio-cni POD
4.  The contents of 10-calico.conflist 
5.  what type of environment are you running this on? 
6.  You could also try to check if the rules are in the iptables https://github.com/istio/cni/blob/master/README.md#troubleshooting

**Comment by itsmurugappan** [comment]
Thank for replying. Below are the details.

1. Yes CNI pod running on all nodes
2. image = 1.1.8
3. contents of 10-calico.conflist
```
{
  "name": "k8s-pod-network",
  "cniVersion": "0.3.0",
  "plugins": [
    {
      "type": "calico",
      "log_level": "info",
      "datastore_type": "kubernetes",
      "nodename": "node1",
      "ipam": {
        "type": "host-local",
        "subnet": "usePodCidr"
      },
      "policy": {
        "type": "k8s"
      },
      "kubernetes": {
        "kubeconfig": "/etc/cni/net.d/calico-kubeconfig"
      }
    },
    {
      "type": "portmap",
      "snat": true,
      "capabilities": {
        "portMappings": true
      }
    },
    {
      "type": "istio-cni",
      "log_level": "info",
      "kubernetes": {
        "kubeconfig": "/etc/cni/net.d/ZZZ-istio-cni-kubeconfig",
        "cni_bin_dir": "/opt/cni/bin",
        "exclude_namespaces": [
          "istio-system"
        ]
      }
    }
  ]
}
```
4. i have k8s installed on 4 node vm
5. Did nsenter and i did see rules are there in the ip tables

**Comment by rlenglet** [comment]
Closing as https://github.com/istio/istio/issues/17795 indicates that tracing is working with Istio CNI 1.3.2.
