### ISSUE TITLE
Make Ingress->VirtualService path conversion configurable

### ISSUE THREAD

**Issue by polivbr** [istio/istio#14636]
When Pilot converts Ingress specs to VirtualServices, it converts paths without wildcard suffixes (.* or /*) to exact matches.

pilot/pkg/config/kube/ingress/conversion.go : createStringMatch()

While this behavior certainly makes sense in some cases, the majority of Helm charts define Ingress paths without wildcard suffixes, instead assuming the ingress controller will perform prefix matching, as the ubiquitous Nginx controller does. This is true even of the Ingress specs in the Istio helm chart (kiali, jaeger, etc.)

As a result, the Istio ingress gateway cannot be used as a drop-in replacement ingress controller with the vast majority of charts. While some charts do allow overriding the ingress path, many do not. Regardless, none can be used without additional configuration.

It would be very helpful if this behavior was configurable, allowing pilot to be configured to generate either exact or prefix matches for non-wildcard ingress paths.

**Affected product area (please put an X in all that apply)**

[x] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[x] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

**Additional context**

**Comment by FrederikNS** [comment]
I just spent two days figuring this out. I was using a helm chart for dex, and wanted to expose it using the built in ingress in the chart, but could not figure out how to get it working.

Finally after fumbling around with the meshConfig, the ingress, the pilot, istioctl, adding and removing labels on namespaces, I finally figured out that istio doesn't match the prefix and instead does a regex match... This breaks almost every ingress in every helm chart that exists.

As a result we will probably have to go with a different ingress controller as we don't want to fork and modify every helm chart we use.

**Comment by FrederikNS** [comment]
I have created a discussion topic in the forums about this, and am also offering to implement the feature. However I would like to have an agreement on the implementation method, before starting work on this.

https://discuss.istio.io/t/making-istio-a-drop-in-replacement-for-other-ingress-controllers/3827

**Comment by FrederikNS** [comment]
It's insanely annoying that some bot tries to close an issue, when there are multiple people who want some feature, and even offers to help build the feature, and the Istio team members, completely ignores it.

Should I just start tagging random istio team members in here?

**Comment by douglas-reid** [comment]
hey @rshriram or @howardjohn or @andraxylia can someone validate that this should be closed?

**Comment by FrederikNS** [comment]
I'm still interested in offering to implement the feature, if people care to help me decide on the design.

**Comment by howardjohn** [comment]
Its interesting nginx treats this as a prefix match. The spec seems to indicate this is not correct:
```
   path <string>
     Path is an extended POSIX regex as defined by IEEE Std 1003.1, (i.e this
     follows the egrep/unix syntax, not the perl syntax) matched against the
     path of an incoming request. Currently it can contain characters disallowed
     from the conventional "path" part of a URL as defined by RFC 3986. Paths
     must begin with a '/'. If unspecified, the path defaults to a catch all
     sending traffic to the backend.
```

Granted, our implementation does not seem to actually follow this either... Another example https://docs.traefik.io/v1.7/basics/#path-matcher-usage-guidelines seems too allow you to configure how it is controlled. This seems like a reasonable approach for us to take as well

**Comment by FrederikNS** [comment]
Huh, yeah, with that description, I must agree that it's quite odd that nginx treats it as a prefix. However all the ingresses in helm charts I have ever seen have used the prefix method. Including the istio charts for Kiali, Prometheus, Grafana and Tracing:

https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/kiali/templates/ingress.yaml#L23

The user documentation for the ingress objects also make no mention of either prefix or regexes, and only shows examples with simple strings, making it pretty resonable for a reader to assume they are prefixes: https://kubernetes.io/docs/concepts/services-networking/ingress/

**Comment by howardjohn** [comment]
This is now configurable: https://preliminary.istio.io/docs/tasks/traffic-management/ingress/kubernetes-ingress/#specifying-path-type
