### ISSUE TITLE
Upgrade documentation needs updates itself w.r.t 1.1 - 1.2 changes

### ISSUE THREAD

**Issue by incfly** [istio/istio#14630]
**Bug description**

Two parts

- https://preliminary.istio.io/docs/setup/kubernetes/upgrade/notice/
documents the behavior different between 1.0 and 1.1 rather than 1.1 to 1.2

- RBAC and mtls policy changes required, in upgrade notice in [Upgrade Steps](https://preliminary.istio.io/docs/setup/kubernetes/upgrade/steps/). I understand we may want to keep the instructions around for a couple of version, but not sure if they're particular to 1.0 -> 1.1?

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by incfly** [comment]
@fpesce  @mandarjog  @duderino we need to consult all the areas owners for fill the information for the first part. replace the system behavior changes between 1.1 and 1.2 .

@diemtvu @liminw for the second part, do you think we still need to keep the clusterrabcconfig and mtls annotation changes in [upgrade steps](https://preliminary.istio.io/docs/setup/kubernetes/upgrade/steps/)?

**Comment by incfly** [comment]
Other than this, I verified the control plane and sidecar rollout instructions work as intended.

**Comment by duderino** [comment]
Issue moved to [istio/istio.io #4387](https://github.com/istio/istio.io/issues/4387) via [**ZenHub**](https://www.zenhub.com/)
