### ISSUE TITLE
Invalid syntax to purge the Helm release in istio-init chart README.md

### ISSUE THREAD

**Issue by rlenglet** [istio/istio#14648]
**Bug description**

The [README.md for the `istio-init` Helm chart](https://github.com/istio/istio/tree/master/install/kubernetes/helm/istio-init) recommends running this `helm` command to delete the `istio-init` release:

```
helm delete istio-init --purge
```

This syntax is incorrect. The `--purge` flag must be given before the release name:

```
helm delete --purge istio-init
```

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

**Comment by sdake** [comment]
thanks @rlenglet for the issue.

Cheers
-steve

**Comment by linsun** [comment]
good catch, could you submit a small PR for this @rlenglet ?
