### ISSUE TITLE
istioctl verify-install fails to compare K8s versions with minor version as xx+(12+)

### ISSUE THREAD

**Issue by rlenglet** [istio/istio#14647]
**Bug description**

`istioctl verify-install` incorrectly determines that k8s version `v1.12.7-gke.10` as lower than `1.11`:

```
$ cd istio-1.2.0-rc.0
$ ./bin/istioctl verify-install

Checking the cluster to make sure it is ready for Istio installation...

Kubernetes-api
-----------------------
Can initialize the Kubernetes client.
Can query the Kubernetes API Server.

Kubernetes-version
-----------------------
Error: The Kubernetes API version: v1.12.7-gke.10 is lower than the minimum version: 1.11
```

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience

**Expected behavior**

`istioctl verify-install` should accept version `v1.12.7-gke.10` as higher than `1.11`.

**Steps to reproduce the bug**

Run `istioctl verify-install` against a 1.12.7 GKE cluster.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

```
$ ./bin/istioctl version --remote
client version: 1.2.0-rc.0
citadel version: 1.1.7
galley version: 1.1.7
ingressgateway version: 1.1.7
pilot version: 1.1.7
policy version: 1.1.7
sidecar-injector version: 1.1.7
telemetry version: 1.1.7
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.7-gke.10", GitCommit:"8d9b8641e72cf7c96efa61421e87f96387242ba1", GitTreeState:"clean", BuildDate:"2019-04-12T22:59:24Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

```
cd istio-1.1.7
helm install install/kubernetes/helm/istio --name istio --namespace istio-system --set global.k8sIngress.enabled=true
```

**Environment where bug was observed (cloud vendor, OS, etc)**

GKE

**Comment by howardjohn** [comment]
Also it probably shouldn't short-circuit if it fails? Or is this the only output expected?

**Comment by rlenglet** [comment]
Yeah, you're right it's short-circuiting. There's a lot more output normally, cf. https://github.com/istio/istio/blob/1c74d317abcd7106f5713c85637ada2906acd9fc/istioctl/pkg/install/pre-check.go#L73

**Comment by linsun** [comment]
@irisdingbj do you have bandwidth to fix this?  cc @esnible

**Comment by irisdingbj** [comment]
yes, working on this

**Comment by howardjohn** [comment]
Fixed in https://github.com/istio/istio/pull/14799/files
