### ISSUE TITLE
Enable H2 upgrade with opportunistic mTLS

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#14645]
With opportunistic mtls, we can certainly present {h2, h1, istio} in alpn. 
However the the way things work right now, the upstream must be designated to be h2 capable by setting h2 protocol options.  
Since this information will not be available at config time, we will have to figure out how to make this work.

If a specific connection pool is initiating the opportunistic mtls, then the h1 or h2 is decided by then.

**Comment by mandarjog** [comment]
@PiotrSikora @lizan

**Comment by PiotrSikora** [comment]
See discussion in envoyproxy/envoy#7135.

**Comment by PiotrSikora** [comment]
Separately, we negotiate mTLS using `"istio"` ALPN, which we can mandate to be H2.
