### ISSUE TITLE
Pilot metrics should not use unbounded strings as label values

### ISSUE THREAD

**Issue by jer** [istio/istio#14642]
**Bug description**
The `err` label of the metric `pilot_xds_cds_reject` sets a value with an arbitrarily large error message. One particular example contained a value with 94k bytes in it. A scrubbed version can be seen in this gist https://gist.githubusercontent.com/jer/cfdaae4edb61ec16286cfc2d2924fd44/raw/fe0aa9bfbad258b02e987af749b567292e13f01f/metricerror.txt

This brought our Prometheus instances to their knees. We were specifically bit by the `pilot_xds_cds_reject` metric, but it appears that there are several other examples that could crop up: https://github.com/istio/istio/blob/49f3d52d3b8c6258561018118f316c718403d4e2/pilot/pkg/proxy/envoy/v2/ads.go#L73

For the time being, we are dropping the metric entirely.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[X] Performance and Scalability
[X] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience

**Expected behavior**
Ideally error messages in Prometheus metrics would be an enum or a short, bounded string. We can get the full error messages from logs.

**Steps to reproduce the bug**
Look at the metrics when pilot rejects CSD configs.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.1.7

**How was Istio installed?**
Using helm template and QBec.

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS

**Comment by douglas-reid** [comment]
The `err` value was meant to be an enum, with limited cardinality and (limited string length). We should do an assessment of other metrics being used in this way, across all Istio components (galley, pilot, mixer). In the short term, it should be possible to wrap all monitoring code to truncate labels to prevent recurrence. That will buy time until individual code path mitigations and corrections can be fully developed.

**Comment by duderino** [comment]
@jer @gotwarlost we'll get a good-enough fix out in 1.1.9 by end of this week (really, the end of this week) and follow-up with a more general audit.

**Comment by douglas-reid** [comment]
@duderino please see the cherry-pick to the 1.1 branch.

**Comment by duderino** [comment]
We fell a little behind here.  This will go out in 1.1.9 which I expect to publish on Monday 6/17
