### ISSUE TITLE
Sidecar injection with mutating webhooks

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1465]
Initializers will not be beta in k8s 1.9. Instead the k8s API machinary SIG's plan is to push mutating webhooks to beta in 1.9. The automatic sidecar injection feature should use these mutating webhooks instead of the initializer mechanism.

Ref https://groups.google.com/forum/#!topic/kubernetes-sig-api-machinery/OTApxKFiGt8

- [x] Update k8s.io/client-go to 1.9 - https://github.com/istio/istio/issues/2177
- [x] Update automatic proxy injection docs on https://istio.io - https://github.com/istio/istio.github.io/pull/882
- [x] Implement mutating webhook per https://goo.gl/jhng56 - https://github.com/istio/istio/pull/2830
- [x] Update e2e tests for mutating webhook - https://github.com/istio/istio/issues/1463. 
- [x] Update testing cluster to 1.9 and enable webhook in e2e tests
- [x] Add micro benchmarks for webhooks
- [x] Document webhook performance and scalability

**Comment by cmluciano** [comment]
[k8s PR for mutating webhooks](https://github.com/kubernetes/kubernetes/pull/54892)

**Comment by ayj** [comment]
https://github.com/istio/istio/pull/3189 adds a simple benchmark for the HTTP serve endpoint. Average time per injected pod is ~1.5us with most of the time spent in the golang net/http code.

**Comment by ayj** [comment]
>  Document webhook performance and scalability

@ldemailly, where's the best place to capture component specific perf/scale charactertistics and tuning guidelines?

**Comment by ldemailly** [comment]
There is https://github.com/istio/istio/wiki/Istio-Performance-oriented-setup-FAQ
and the perf wg folder
https://drive.google.com/corp/drive/u/0/folders/1Zpi5TcBPSqGno96WAq5QkcNKi16opaTL

I also want to add a perf section to istio.io (https://github.com/istio/istio.github.io/issues/911) but it's not there yet

So I'd say a doc in the folder or an entry in the FAQ depending on how extensive it is

**Comment by ayj** [comment]
Thanks. I added https://github.com/istio/istio/wiki/Istio-Performance-oriented-setup-FAQ#automatic-proxy-injection for now since perf/scaling is pretty straightforward for the webhook.
