### ISSUE TITLE
grpc with istio get poor performance

### ISSUE THREAD

**Issue by gxthrj** [istio/istio#14654]
When the server has only one pod, the performance with istio is similar that without istio;
but scale the server replicas=2 , When not using istio, the average delay of 160 concurrent is 120ms; after with istio, the delay is 600ms+

istio version is 1.1.2, Mixer is not enabled for all tests

**Comment by gxthrj** [comment]
sorry,my mistake.
Modify the config in dr `ConnectionPoolSettings.TCPSettings.maxConnections=80`, I get the top performance
one more thing, what is the default value of `ConnectionPoolSettings.TCPSettings.maxConnections`, or default is not limited?

**Comment by gxthrj** [comment]
Hi,I am back 
`ConnectionPoolSettings.TCPSettings.maxConnections `is the limit of destination host.
when scale the server replicas=2, setting maxConnections=80 is not right. so this config is not the solution.

**Comment by incfly** [comment]
Not an networking expert, but it does not seem reasonable to make client side connection number scale up as dynamically as the server side endpoints increase... wouldn't you pay mem/cpu overhead on client side envoy?

I remember envoy api doc somewhere mentioned this is 1024.

**Comment by robinpercy** [comment]
Yes, default for maxConnections is 1024:https://istio.io/docs/reference/config/networking/v1alpha3/destination-rule/#ConnectionPoolSettings-TCPSettings

@gxthrj are you still seeing performance issues?

**Comment by howardjohn** [comment]
Issue seems abandoned. I would encourage anyone seeing similar issues to open a new issue so we can get to the bottom of it. Thanks!
