### ISSUE TITLE
istio-demo-auth is permissive (installation problem)

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#14650]
The documentation states it's strict mTLS, but it is not. Verified with `kubectl run curl` command from a non-injected pod.

**Comment by kyessenov** [comment]
This happens with re-application of istio-demo-auth.yaml over istio-demo.yaml (I deployed the latter by mistake). I think we should document that we cannot re-apply installation YAMLs.

**Comment by kyessenov** [comment]
It appears the root issue is that the installation job that applies auth config is identical between the two YAMLs (istio-demo and istio-demo-auth). I confirmed this by comparing `kubectl get job istio-security-post-install-1.2.0-rc.0 -n istio-system -o yaml`. The effect is that the job _does not run_ after installing auth profile, which means the auth config is not applied. The solution should be to put SHA of config into the job as a label/annotation.

/assign @wattli

**Comment by linsun** [comment]
This is probably not going to be an issue in 1.3, as we decided no need to ship strict mtls for demo profile.

**Comment by incfly** [comment]
Close as duplciates of https://github.com/istio/istio/issues/14650
