### ISSUE TITLE
Bookinfo productpage microservice crashes when run as non-root userid

### ISSUE THREAD

**Issue by dgrove-oss** [istio/istio#14667]
**Bug description**

This is a bug related to the productpage microservice of the Istio Bookinfo example.  When run as a non-root userid, the container crashes because it attempts to write log information into a directory/file owned by the root uid.

Note that the bug can be reproduced without Istio being installed, it is a problem with the productpage cointainer. 

**Affected product area (please put an X in all that apply)**

Bookinfo examples

**Steps to reproduce the bug**

```
$ docker run  --user 1001 istio/examples-bookinfo-productpage-v1:1.14.0
touch: cannot touch '/opt/microservices/microservice.log': Permission denied
Traceback (most recent call last):
  File "productpage.py", line 47, in <module>
    logging.basicConfig(filename='microservice.log',filemode='w',level=logging.DEBUG)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1808, in basicConfig
    h = FileHandler(filename, mode)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1032, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1061, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/opt/microservices/microservice.log'

```

**Comment by esnible** [comment]
Some clouds are configured to prevent containers from running as root.

We should modify _samples/bookinfo/platform/kube/bookinfo.yaml_ to use `runAsUser: 1001` or `runAsUser: 65534` to avoid this problem.

Probably this will require modifying _samples/bookinfo/src/productpage/Dockerfile_ and some other Dockerfiles to grant permissions to that user for logging directories.

This won't improve Istio but might prevent pain for users kicking the tires.

**Comment by McCoyAle** [comment]
I would like to give this one a stab.

**Comment by c0d1ngm0nk3y** [comment]
Why was this already closed? Just because the `see #xyz` reference in the PR? I think first a new image of `examples-bookinfo-productpage` has to be pushed and then consumed.

@venilnoronha Can you give a short update when a new tag is available? I will then add a PR to consume it. Thanks.

**Comment by c0d1ngm0nk3y** [comment]
I just saw https://github.com/istio/istio/pull/14943#issuecomment-503263421. I will create a new minor version and consume it.

**Comment by c0d1ngm0nk3y** [comment]
Can be closed when #14995 is merged.

**Comment by venilnoronha** [comment]
@c0d1ngm0nk3y do we also need this in 1.2.1?

**Comment by tegk** [comment]
Ok, why is this closed again?

This still happens with the sample application included in Istio 1.2.2.

`IOError: [Errno 13] Permission denied: '/opt/microservices/microservice.log'`

**Comment by venilnoronha** [comment]
@tegk the PR was against master so you don't see it in 1.2.2. I've submitted a backport request so it should be available in the next 1.2.x release.

**Comment by mitchellmaler** [comment]
I just tried running this by setting the user in the manifest to 1001 and now the container wont start. I manually started it up and ran the python command and wad able to view the stderr.log to view the issue. Seems like python is hitting an error that is fatal if the uid doesn't actually exist.

```
docker run -it  --user 1001 istio/examples-bookinfo-productpage-v1:1.15.0 sh
python productpage.py 9080
cat /opt/microservices/stderr.log
Traceback (most recent call last):
  File "productpage.py", line 379, in <module>
    app.run(host='0.0.0.0', port=p, debug=True, threaded=True)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 943, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python3.6/site-packages/werkzeug/serving.py", line 751, in run_simple
    application = DebuggedApplication(application, use_evalex)
  File "/usr/local/lib/python3.6/site-packages/werkzeug/debug/__init__.py", line 258, in __init__
    if self.pin is None:
  File "/usr/local/lib/python3.6/site-packages/werkzeug/debug/__init__.py", line 268, in _get_pin
    self._pin, self._pin_cookie = get_pin_and_cookie_name(self.app)
  File "/usr/local/lib/python3.6/site-packages/werkzeug/debug/__init__.py", line 148, in get_pin_and_cookie_name
    username = getpass.getuser()
  File "/usr/local/lib/python3.6/getpass.py", line 169, in getuser
    return pwd.getpwuid(os.getuid())[0]
KeyError: 'getpwuid(): uid not found: 1001'
```

**Comment by tomkukral** [comment]
Same error again, @venilnoronha can you release new image as `istio/examples-bookinfo-productpage-v1:1.15.0` is broken and new image is available?
