### ISSUE TITLE
Remove CPU limits from demo

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#14666]
We have problems with users using demo profile and getting throttled and having crashes, horrible perf, etc. We should remove the CPU limits from the demo (removing == setting them to the same as our default), which keeping requests low to limit this problem.

@mandarjog let me know if you want me to do this

**Comment by sdake** [comment]
See this thread: https://github.com/istio/istio.io/pull/4299#issuecomment-501335535

Cheers
-steve

**Comment by howardjohn** [comment]
waiting on https://github.com/istio/istio/pull/14776 to get into 1.2

**Comment by duderino** [comment]
merged.  Thanks @howardjohn and @fpesce
