### ISSUE TITLE
Regular expression support for origins in CorsPolicy

### ISSUE THREAD

**Issue by richardpoole** [istio/istio#14661]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

With the current implementation of [CorsPolicy](https://istio.io/docs/reference/config/networking/v1alpha3/virtual-service/#CorsPolicy), it's not possible to accept requests from dynamic origins (e.g. `https://{version}--mysite.netlify.com`). Envoy supports this through [allow_origin_regex](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto.html?highlight=cors#route-corspolicy), but this setting isn't available in `CorsPolicy`.

**Describe alternatives you've considered**

One alternative is to update the `allowOrigin` array with each new deployment, but this requires a fair amount of automation glue. Another alternative is to implement CORS policy in the backend service or another sidecar container.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Policies and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience

**Additional context**

We're hosting SPAs in Netlify, where each deploy preview (triggered by a GitHub pull request) gets a dedicated subdomain (e.g. `https://{version}--myapp.netlify.com`), so part of the `Origin` header is dynamic.

**Comment by strideynet** [comment]
I'd like to look into implementing this. Just need to familiarise with the Istio codebase.

**Comment by ajanthan** [comment]
What is the best way to support it in the current config model? adding a new attribute(e.g `allowOrigin_regex`) under `CorsPolicy` or allowing to add regex URLs in `allowOrigin` attribute and separating it while translating it to Envoy config?

**Comment by dgn** [comment]
I think the next API version for VirtualService should use `StringMatch` for all of these fields like upstream Envoy does now.

**Comment by fcantournet** [comment]
Can we expect this to make it into 1.5 ?
Envoy 1.12 is released.

**Comment by yp28** [comment]
It seems like this has been fixed for v1alpha3 in istio/api#1197 and for v1beta1 in istio/api#1232.
