### ISSUE TITLE
istio_auth_sds_e2e-master flake

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#14672]
Example failure:
https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/14439/istio_auth_sds_e2e-master/1653/?log#log

We don't have it on testgrid, so can't see the history as easily, but the log of runs can be viewed at https://k8s-gubernator.appspot.com/builds/istio-prow/pr-logs/directory/istio_auth_sds_e2e-master. Seems to fail every 10 times or so. Seemed to be get worse around 6/3/19.

**Comment by howardjohn** [comment]
https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/14677/istio-pilot-e2e-envoyv2-v1alpha3-master/1701 fails as well

I am a bit worried this may be a regression and not just a test flake

**Comment by JimmyCYJ** [comment]
The istio_auth_sds_e2e is testing workload SDS. TestTLSMultiplexing and TestGrpc are using SDS in this job. I randomly select some failed jobs and the failed tests are not SDS related. I think this may not be a SDS failure.

**Comment by howardjohn** [comment]
Since istio-pilot-e2e-envoyv2-v1alpha3-master is failing as well I would agree it is probably not SDS related

**Comment by JimmyCYJ** [comment]
@utka could you help us to add istio_auth_sds_e2e-master into testgrid, so that it would be convenient to keep tracking of the test results?

**Comment by howardjohn** [comment]
I think we need to add it to https://github.com/kubernetes/test-infra/blob/master/testgrid/config.yaml#L1032.

Would be nice if the test grid stuff was just automatic from our prow config though

**Comment by therealmitchconnors** [comment]
Openned https://github.com/kubernetes/test-infra/pull/13007 to get a better idea if this test is flaky or not...

**Comment by therealmitchconnors** [comment]
@howardjohn @utka @JimmyCYJ I have added this test to testgrid.  I am not familiar enough with that tool to quickly identify flakes, but it does look mostly green.  PTAL.

https://testgrid.k8s.io/istio-postsubmits-master#istio_auth_sds_e2e

**Comment by howardjohn** [comment]
Thank you mitch! I disagree that it looks mostly green though, you only need to look at the "overall" row which shows ~1/5 tests fail

**Comment by therealmitchconnors** [comment]
I do see about 10% overall failures, but I don't see a pattern of any one test case consistently causing those failures, which looks more like tests doing their job rather than flakes.

The key difference (AFAIK) between an actually failing test and a flaky test is the way the failure is resolved.  If the failure disappears by simply rerunning the test, it is a flake, but if the failure is resolved with a code change, it is a legitimate failure.  Does testgrid give us visibility into the commit hashes or pr #s for these test runs?

**Comment by howardjohn** [comment]
It doesn't directly, but you can click one of the individual squares and it will take you to the test page which has the PR #. Not the best though.

These test fail regularly on PRs and we just `/retest` them and they pass

**Comment by therealmitchconnors** [comment]
On the other hand, the failure message in https://prow.k8s.io/view/gcs/istio-prow/pr-logs/directory/istio_auth_sds_e2e-master/1930 ("try again"), along with the function that is throwing the error ([pilot_test.go@runRetriableTest](https://github.com/istio/istio/blob/master/tests/e2e/tests/pilot/pilot_test.go#L191)) suggest that this test is known to be flaky?

The difficulty is that I just don't see evidence of frequent failures in the testgrid history.  This is the only failure of this test in the last two weeks...

**Comment by howardjohn** [comment]
I am not sure what you mean? If you look at https://testgrid.k8s.io/istio-postsubmits-master#Summary&width=5 it shows

`44 of 254 runs (17.3%) failing in the past week` under auth_sds

**Comment by therealmitchconnors** [comment]
And in this case, the PR associated with the only failure (run 1930) is still in a blocked state.  /retest has not been run, nor have further changes been pushed.  If this suite is flaky, we have no evidence that this particular test is the source of flakiness...

**Comment by therealmitchconnors** [comment]
Perhaps the source of flakiness is the test timeouts?  While I don't see consistent test failures, I do see a frequent occurrence where test execution is ended before the tests have finished... while not technically a flake, that would have the same impact as a flake on PRs...

**Comment by howardjohn** [comment]
@therealmitchconnors are you looking at one particular test case? I have been looking at the entire suite as a whole, which has 17% failures.

Prior to the last 2 weeks or so this test was pretty stable, so something recent may have changed (in our code or maybe just prow or something)

**Comment by therealmitchconnors** [comment]
@howardjohn I am trying to discern the source of any flakiness.  If the flaky test failures occur evenly across all the cases, this would indicate either a cross-cutting source of flakiness.  In this case, the most common failure I am seeing is timeouts waiting for Kubernetes.  It is not clear to me how we can improve on this...

**Comment by howardjohn** [comment]
I don't think it is related to the timeouts? for example on https://prow.k8s.io/view/gcs/istio-prow/pr-logs/directory/istio_auth_sds_e2e-master/1930, there are all of those tests that fail and then after that the test times out, if I am understanding it correctly. So it has a problem regardless of the timeout?

**Comment by therealmitchconnors** [comment]
Yes, but the test cases that fail in 1930 don't appear to be flakes... it looks like legitimate failures to me, and we haven't rerun tests on that PR to see if the failures change.

**Comment by therealmitchconnors** [comment]
Ok, I have identified one potential test flake for this suite.  [This execution](https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/14698/istio_auth_sds_e2e-master/1821) failed, while [this](https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/14698/istio_auth_sds_e2e-master/1811) one succeeded for the same commit hash.  The failure messages are less than helpful, though.  @howardjohn can you decipher for me?

**Comment by therealmitchconnors** [comment]
Ok, I can confirm that this test is flakey.  The most recent flake (as of last week) was https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/14927/istio_auth_sds_e2e-master/2349

This test has flaked at least 26 times so far this month, and only 20 times in the month of May, for a flake ratio of 2.2% in may and 3.5% in June.

**Comment by howardjohn** [comment]
On the testgrid now: https://testgrid.k8s.io/istio-postsubmits-master#istio_auth_sds_e2e-master&exclude-non-failed-tests=&width=20&sort-by-flakiness=

**Comment by howardjohn** [comment]
One way to fix a test flake - delete it https://github.com/istio/test-infra/pull/1594
