### ISSUE TITLE
Track 1.1 changes that need to get into 1.2

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#14683]
https://github.com/istio/istio/pull/14618 and https://github.com/istio/istio/pull/14617 are P0 changes in 1.1 that are not in master (or 1.2) yet

This issue is just to track these 2 to make sure they don't get lost. They are blockers for 1.2

**Comment by howardjohn** [comment]
Now tracking 1.2 cherry picks https://github.com/istio/istio/pull/14697 and https://github.com/istio/istio/pull/14699

**Comment by howardjohn** [comment]
And https://github.com/istio/istio/pull/14701

**Comment by duderino** [comment]
@howardjohn I think this is done.  Close it?  We (@duderino and @fpesce) also got the recent istio/proxy and istio/envoy 1.1 changes cherry picked into 1.2 yesterday

**Comment by howardjohn** [comment]
Yes this is done
