### ISSUE TITLE
Sidecar ingress ports binds to 0.0.0.0, binding it to instance IP provides more flexibility

### ISSUE THREAD

**Issue by shakti-das** [istio/istio#14693]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Sidecar ingress ports binds to 0.0.0.0, binding it to instance IP provides more flexibility for other listeners to use the same port.

We (Salesforce) are using the same port for different purposes based on IP. Like:
127.0.0.1:9090 - Egress Listener
10.11.12.14:9090 - HostIP + Port - Ingress Listener

Here, we want to use Sidecar to be able to configure both the listeners.

**Describe alternatives you've considered**
No alternatives found for what we want to achieve as 0.0.0.0:port listener will conflict with any other listener.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

**Additional context**

**Comment by rshriram** [comment]
Thanks for the PR.. 
tangent: can the salesforce folks also take a look at https://github.com/istio/api/pull/899 to see if I have captured everything?

**Comment by shakti-das** [comment]
The PRs are merged for this functionality, closing the issue. Thanks.
