### ISSUE TITLE
CircleCI tests fail for istio/installer

### ISSUE THREAD

**Issue by phil9909** [istio/istio#14694]
**Bug description**
The circle-ci jobs `integration-presubmit-isolated-namespaces-kind`, `integration-presubmit-one-namespace-kind` and `install-minikube` fail since 2019-06-10 without any changes to the installer-repo. They all run the same tests with different cluster configurations and use the `daily-master` docker tag.
Logs:
- https://circleci.com/gh/istio/installer/5115
- https://circleci.com/gh/istio/installer/5110
- https://circleci.com/gh/istio/installer/5114

```
--- FAIL: TestCitadelBootstrapKubernetes (91.40s)
    bootstrap_writesecret_test.go:90: log does not match, expected strings Failed to write secret to CA and Failed to create a self-signed Citadel not found in logs. Current log: 2019-06-11T12:10:28.982057Z	info	The custom-defined DNS name list is [istio-galley-service-account.istio-config:istio-galley.istio-config.svc istio-galley-service-account.istio-control:istio-galley.istio-control.svc istio-galley-service-account.istio-control-master:istio-galley.istio-control-master.svc istio-galley-service-account.istio-master:istio-galley.istio-master.svc istio-galley-service-account.istio-pilot11:istio-galley.istio-pilot11.svc istio-sidecar-injector-service-account.istio-control:istio-sidecar-injector.istio-control.svc istio-sidecar-injector-service-account.istio-control-master:istio-sidecar-injector.istio-control-master.svc istio-sidecar-injector-service-account.istio-master:istio-sidecar-injector.istio-master.svc istio-sidecar-injector-service-account.istio-pilot11:istio-sidecar-injector.istio-pilot11.svc istio-sidecar-injector-service-account.istio-remote:istio-sidecar-injector.istio-remote.svc ]
```

We suspect this commit https://github.com/istio/istio/commit/eda88a08029814c7e837031dc717fb8b0c630e0d to be the root cause, because of the time and message correlation. @myidpt can you have a look?

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[X] Test and Release
[ ] User Experience

**Expected behavior**
green CircleCI Job

**Steps to reproduce the bug**
trigger CircleCI

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
N/A

**How was Istio installed?**
N/A

**Environment where bug was observed (cloud vendor, OS, etc)**
N/A

**Comment by c0d1ngm0nk3y** [comment]
Any updates? The circleci tests are failing for quite some time now. In the meantime, the error seems to be another

```
Error during test framework init: unknown label name: "presubmit"
```

Has the citadel error been fixed or is it just shadowed by this error.

**Comment by c0d1ngm0nk3y** [comment]
Currently this is shadowed by #14949. I don't think the underlying issue is fixed.

**Comment by phil9909** [comment]
The issue is back since #14949 was fixed:
- https://circleci.com/gh/istio/installer/6001
- https://circleci.com/gh/istio/installer/6004
- https://circleci.com/gh/istio/installer/6006

@myidpt could you please have a look?

**Comment by howardjohn** [comment]
Fixed via https://github.com/istio/istio/pull/15138. The only one still failing is due to https://github.com/istio/istio/issues/15222 which is being tracked there

Thanks for all the work tracking this down
