### ISSUE TITLE
Single Control Plane Multicluster > istio-proxy in Main cluster calls kubernetes api server in Remote cluster

### ISSUE THREAD

**Issue by anton-fedorov** [istio/istio#14692]
**Bug description**
I have Single Control Plane Multicluster Istio 1.1.7 setup in GKE. 
From one of the pods, i'm trying to reach kubernetes API from main cluster via ```https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_PORT_443_TCP_PORT/api``` 

In about 50% of cases this happens fine, and in about 50% of cases i receive 
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}
```

After investigating `istio-proxy` logs and `curl` responses, i noticed that response is received from different Kubernetes API Servers - sometimes from Main Cluster, sometimes from Remote Cluster.

It seems like, when i make request to KUBERNETES_SERVICE_HOST (which is ClusterIP of the `kubernetes` service in `default` namespace), istio-proxy sometimes makes request to current cluster's api server and sometimes makes request to remote cluster api server.

Is this expected behavior? Are there recommendations on how i should approach calling kubernetes api server, when in single control plane setup? Note, that i would need to call kubernetes api from pods in both main and remote clusters. 

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

**Expected behavior**
When calling ```https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_PORT_443_TCP_PORT/api``` from pod in either main or remote cluster, istio-proxy routes request to the kubernetes api server in the same cluster where pod is running.

**Steps to reproduce the bug**
1. Follow instructions in https://istio.io/docs/examples/multicluster/gke/ to setup multicluster
2. From any pod in Main cluster try calling multiple times:
```
KUBE_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
curl -sSk --request GET -H "Authorization: Bearer $KUBE_TOKEN" -H "Content-Type:application/json" "https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_PORT_443_TCP_PORT/api"
```

This will sometimes resolve in 200 OK response, and sometimes in:
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}
```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```
./istioctl version --remote
client version: version.BuildInfo{Version:"1.1.7", GitRevision:"eec7a74473deee98cad0a996f41a32a47dd453c2", User:"root", Host:"341b3bf0-76ac-11e9-b644-0a580a2c0404", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.6-6-geec7a74"}
citadel version: version.BuildInfo{Version:"1.1.7", GitRevision:"eec7a74473deee98cad0a996f41a32a47dd453c2-dirty", User:"root", Host:"341b3bf0-76ac-11e9-b644-0a580a2c0404", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.6-6-geec7a74"}
galley version: version.BuildInfo{Version:"1.1.7", GitRevision:"eec7a74473deee98cad0a996f41a32a47dd453c2-dirty", User:"root", Host:"341b3bf0-76ac-11e9-b644-0a580a2c0404", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.6-6-geec7a74"}
ingressgateway version: version.BuildInfo{Version:"1.1.7", GitRevision:"eec7a74473deee98cad0a996f41a32a47dd453c2", User:"root", Host:"341b3bf0-76ac-11e9-b644-0a580a2c0404", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.6-6-geec7a74"}
pilot version: version.BuildInfo{Version:"1.1.7", GitRevision:"eec7a74473deee98cad0a996f41a32a47dd453c2-dirty", User:"root", Host:"341b3bf0-76ac-11e9-b644-0a580a2c0404", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.6-6-geec7a74"}
sidecar-injector version: version.BuildInfo{Version:"1.1.7", GitRevision:"eec7a74473deee98cad0a996f41a32a47dd453c2-dirty", User:"root", Host:"341b3bf0-76ac-11e9-b644-0a580a2c0404", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.6-6-geec7a74"}
```
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.5-gke.10", GitCommit:"f5949b3427099d4e410ef96d6e0fea3cd4794e10", GitTreeState:"clean", BuildDate:"2019-04-10T19:05:37Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
Helm

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by dicarlo2** [comment]
This happens because istio maintains a fqdn -> service mapping and automatically merges services/endpoints with the same fqdn, in this case, kubernetes.default.svc.cluster.local. You're seeing ~50% of requests fail because istio's default algorithm is to round robin between available endpoints, hence half the requests go to the main cluster and half go to the remote one.

One workaround for the issue is to always exclude your kubernetes master ip/cidr using `'traffic.sidecar.istio.io/excludeOutboundIPRanges'`.

**Comment by costinm** [comment]
Thanks for the report and for debugging this.

**Comment by costinm** [comment]
We'll need to document this - I don't think we can fix it easily. We may be able to automatically add the apiserver to the iptables exclude, but currently iptables script (and the go replacement) are pretty tricky to test and high risk, we just spend a week tracking a subtle bug.

**Comment by anton-fedorov** [comment]
Thanks for explanation. For now the way i overcame this is actually switched to referring directly to kubernetes api server by its masterUrl (via IP), caCertData and oauthToken. This way confusion doesn't happen, but it required some coding of course.

Anyway this was more a surprising and unclear issue, rather than unbeatable blocker. So would be good to document.

**Comment by howardjohn** [comment]
Not stale

**Comment by howardjohn** [comment]
@ayj @nmittler are either of you interested in looking at this?

**Comment by nmittler** [comment]
Sounds like the action item here is to add documentation?

**Comment by rolandkool** [comment]
Hi,

We've found an alternative workaround to get this working by creating a destination rule in stead of using the traffic.sidecar annotation.

The rule looks like this:
`apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  annotations:
  name: kubernetes-api
spec:
  host: kubernetes.default.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: PASSTHROUGH
`

The docs states to be careful with the PASSTHROUGH loadbalancer. Does this have any hidden consequences?

In case this is a proper workaround, perhaps this DR can be added by default by the installation?

**Comment by howardjohn** [comment]
@rolandkool the concerns with PASSTHROUGH are that you are essentially trusting the client here. I can do `curl 1.2.3.4 -H "Host: kubernetes.default.svc.cluster.local" and the request will be sent to 1.2.3.4 with all the mtls settings, etc as if I was sending to the k8s service. Depending on your set up, this may or may not be a big concern

**Comment by smawson** [comment]
Nate/Jason since we were just talking about this yesterday, can we chat about a potential short-term fix? Easiest would be a way to opt an entire namespace out of merging, better would be to support topology keys but that would take longer. We should see if there is anything we can do in 1.5 timeframe.

**Comment by nmittler** [comment]
I won't have bandwidth to work on this for 1.5 .... I'm trying to get in some other changes for istiod.

But yes, we should fix this soon (1.6?). The short-term fix sounds reasonable to me.

**Comment by nmittler** [comment]
AFAIK nothing beyond https://github.com/istio/istio/issues/14692#issuecomment-559235529.

For a short-term fix, I think all we would have to do is filter resources from the `kube-system` namespace when talking to remote API Servers. If so, I should be able to cook something up early next week (hopefully in time for 1.5).

@howardjohn @costinm @smawson does that sound about right?

**Comment by nmittler** [comment]
Actually, this will take more work and won't make it for 1.5.  I think this is what needs to happen:

- Pilot will need to know which cluster each endpoint resides in. This is effectively a form of locality, but I'm not sure if Pilot stores this today.
- Pilot will need a blacklist for namespaces that are considered cluster-local.
- When building clusters/listeners, Pilot will only add cluster-local endpoints if the clients resides in the same cluster.

I'll start this work shortly and target for 1.6.

FYI @howardjohn @costinm @smawson

**Comment by nmittler** [comment]
I've just started an RFC for cluster-local services: https://docs.google.com/document/d/1hluC4KfIYodAftZTLRF_I-M75InZo8VyGi8nqUuPfS4/edit#
