### ISSUE TITLE
Dashboards report double metrics in some cases

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#14705]
CPU was fixed in https://github.com/istio/istio/pull/14571, but there are still some broken queries. We need to go through them all and make sure they are not duplicates. I know for sure pilot memory has duplicates

Specific broken query: `sum(container_memory_usage_bytes{container_name=~"discovery|istio-proxy", pod_name=~"istio-pilot-.*"})`

**Comment by howardjohn** [comment]
@douglas-reid is it possible to change the prometheus config instead of each query? Even if our dashboards are fixed, other people use their own dashboards, do ad-hoc queries, etc

**Comment by douglas-reid** [comment]
@howardjohn other people will have their own prom configs too, no? i'm not sure what you are suggesting exactly. This seems to be an issue with new clusters now having new service(s) exposed. If/when we retire support for old k8s versions, I guess we could remove a job (provided all info came from elsewhere moving forward). For now, I'm not sure we have that option.

**Comment by howardjohn** [comment]
Sure, but if they have broken prometheus configs its there problem. Prometheus is the source of truth, so if I query it from `sum(pod_cpu{pod=foo})` I would expect to get the pod CPU, not 2x the CPU. Fixing it in the dashboards seems like a bit of a hack.

Now in saying this, I am not familiar with how the scraping works so maybe this isn't feasible

**Comment by howardjohn** [comment]
Fixed by #15481
