### ISSUE TITLE
add unit test in nodeagent to detect race condition 

### ISSUE THREAD

**Issue by quanjielin** [istio/istio#14714]
Use this bug to track the work adding more unit test to detect race condition in nodeagent,

some race condition bugs we hit before:
https://github.com/istio/istio/pull/13333
https://github.com/istio/istio/pull/14459

**Comment by pitlv2109** [comment]
I see there is a PR checked in. Should we close this issue? @quanjielin

**Comment by quanjielin** [comment]
keep it open as there is more to be added.
