### ISSUE TITLE
Integ and E2E GKE tests fail with "fork/exec /usr/local/bin/envoy: permission denied"

### ISSUE THREAD

**Issue by sushicw** [istio/istio#14718]
**Bug description**

Manually run integ tests and E2E tests run against a GKE cluster fail because the istio-proxy sidecar container dies with the following error:

```
2019-06-11T20:50:57.596010Z	info	Epoch 0 starting
2019-06-11T20:50:57.598533Z	info	Envoy command: [-c /etc/istio/proxy/envoy-rev0.json --restart-epoch 0 --drain-time-s 2 --parent-shutdown-time-s 3 --service-cluster echosrv.istio-system --service-node sidecar~10.24.2.8~echosrv-deployment-1-5589d7bd78-k8tvq.istio-system~istio-system.svc.cluster.local --max-obj-name-len 189 --local-address-ip-version v4 --allow-unknown-fields -l warning --component-log-level misc:error --concurrency 2]
2019-06-11T20:50:57.598999Z	warn	Epoch 0 terminated with an error: fork/exec /usr/local/bin/envoy: permission denied
```

Investigating more closely, it appears that the executable permissions for the envoy binary are set to 750 instead of 755. 

This bug appears to have been introduced in https://github.com/istio/istio/pull/13579. There was some discussion of the impact of removing the chmod statement, but it didn't seem to fail the automatic tests. 

Should we re-add the chmod that was removed in the above PR? Should we use some other mechanism to ensure that all packaged executables are 755 before packaging them into Docker containers? 

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[X] Test and Release
[ ] User Experience

**Expected behavior**

Running [integ](https://github.com/istio/istio/blob/master/tests/integration/README.md#running-tests) and [E2E](https://github.com/istio/istio/blob/master/tests/e2e/UsingGKE.md) tests on GKE as documented should work, and needed binaries should be world-executable.

**Steps to reproduce the bug**

1. Check out a commit on master on or after a51ebc0d0
2. make && make docker && make docker.push && make installgen
3. Start a GKE cluster for testing (using either create_cluster_gke.sh or the steps [here](https://github.com/istio/istio/blob/master/tests/e2e/UsingGKE.md#step-1-create-and-setup-a-kubernetes-cluster)
4. make e2e_simple E2E_ARGS="--skip_cleanup"
5. Note that the test times out and fails, and that the "echosrv" pods on the test cluster are stuck in a crash loop with the error described above.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

Tip of master branch (a51ebc0d0 and forward) 

**How was Istio installed?**

Test script automation

**Environment where bug was observed (cloud vendor, OS, etc)**

GKE

**Comment by sushicw** [comment]
Question: why has this not broken any of the automated tests?

**Comment by gargnupur** [comment]
@fpesce, sushicw : shouldn't this be for 1.2 milestone as it breaks local testing for 1.2 using e2e or integration tests...
