### ISSUE TITLE
Add liveness and readiness probes to proxies, discovery services and CA

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1472]
@kyessenov commented on [Mon Oct 09 2017](https://github.com/istio/old_pilot_repo/issues/1421)

- Add probes to the sidecars, ingress, egress, discovery services, etc.
- Avoid serving traffic with incomplete configuration state.
- Provides signals for horizontal scheduling

Also:
- https://github.com/istio/pilot/issues/908

---

@cmluciano commented on [Mon Oct 30 2017](https://github.com/istio/old_pilot_repo/issues/1421#issuecomment-340575963)

/assign

**Comment by myidpt** [comment]
Design doc is here:
https://docs.google.com/document/d/1ig1ieuaPYr-EB7gByt4BgCQAXudnmZrqXV294K_oU1M/edit#heading=h.x9snb54sjlu9

**Comment by myidpt** [comment]
For Istio CA, the implementation is P0 for Q1.

**Comment by sakshigoel12** [comment]
@myidpt @andraxylia what is pending here? Is there a target release to complete this work item?

**Comment by wattli** [comment]
CA (Citadel) health check is done https://istio.io/docs/tasks/security/health-check/, unassigned @myidpt.

**Comment by howardjohn** [comment]
We have readiness for proxies and pilot, can this be closed? @andraxylia

**Comment by douglas-reid** [comment]
I'm closing, as part of triage, as it appears the work has been done.
