### ISSUE TITLE
pilot_conflict_outbound_listener_tcp_over_current_tcp when start bookinfo example in Consul

### ISSUE THREAD

**Issue by harryge00** [istio/istio#14730]
**Bug description**
I totally follow the https://istio.io/docs/setup/consul/quick-start/ guide, and then start `bookinfo`. But the pilot reports 
```
{
    "ProxyStatus": {
        "pilot_conflict_outbound_listener_tcp_over_current_tcp": {
            "0.0.0.0:9080": {
                "proxy": "172.28.0.11.service.consul",
                "message": "Listener=0.0.0.0:9080 AcceptedTCP=productpage.service.consul RejectedTCP=reviews.service.consul TCPServices=1"
            }
        }
    },
    "Start": "2019-06-12T03:28:50.664700442Z",
    "End": "2019-06-12T03:28:50.737007662Z"
}
```

And accessing `ratings, details, reviews` will all be redirected to `productpage`.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

**Expected behavior**
Bookinfos can be ran under consul 

**Steps to reproduce the bug**
Follow the guide https://istio.io/docs/setup/consul/quick-start/ to start consul.
Follow the guide https://istio.io/docs/examples/bookinfo/ to start bookinfo example.

Visit `productpage`, you will see error.
```
docker exec -ti any_of_the_proxy bash
# curl details:9080
# curl ratings:9080
# curl reviews:9080
```
You will see all the other services will be redirected to one-specific service, like `details`.
And perhaps, pilot will report 
```
2019-06-12T03:28:50.736985Z	info	ads	LDS: PUSH for node:172.28.0.11.service.consul addr:"172.28.0.11:44082" listeners:9 7590
2019-06-12T03:28:50.737131Z	info	ads	Push finished: 72.424863ms {
    "ProxyStatus": {
        "pilot_conflict_outbound_listener_tcp_over_current_tcp": {
            "0.0.0.0:9080": {
                "proxy": "172.28.0.11.service.consul",
                "message": "Listener=0.0.0.0:9080 AcceptedTCP=productpage.service.consul RejectedTCP=reviews.service.consul TCPServices=1"
            }
        }
    },
    "Start": "2019-06-12T03:28:50.664700442Z",
    "End": "2019-06-12T03:28:50.737007662Z"
}
```
If no such error, just restart pilot.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
version.BuildInfo{Version:"1.1.5", GitRevision:"9b6d31b74d1c0cc9358cc82d395b53f71393326b", User:"root", Host:"3e29fde4-6c3f-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.4-10-g9b6d31b"}

1.1.7

**How was Istio installed?**
Consul

**Environment where bug was observed (cloud vendor, OS, etc)**
CentOS 

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by knightXun** [comment]
@hzxuzhonghu

**Comment by harryge00** [comment]
So Istio 1.1 cannot start on Consul?

**Comment by harryge00** [comment]
https://discuss.istio.io/t/quickstart-bookinfo-app-consul-docker-is-redirecting-outbound-to-only-one-microservice/2208

**Comment by harryge00** [comment]
https://discuss.istio.io/t/quickstart-bookinfo-app-consul-docker-is-redirecting-outbound-to-only-one-microservice/2208

I think it is fixed. But 1.1.7 not upgraded to the fixed one
