### ISSUE TITLE
Mutual TLS Deep Dive: Output of commands under `Verify mutual TLS configuration` is different from the docs

### ISSUE THREAD

**Issue by johnma14** [istio/istio#14741]
**Bug description**

Under the **Verify mutual TLS configuration**, the following commands show a different output:
- `$ SLEEP_POD=$(kubectl get pod -l app=sleep -o jsonpath={.items..metadata.name})
   $ istioctl authn tls-check ${SLEEP_POD} httpbin.default.svc.cluster.local`

> HOST:PORT       STATUS     SERVER        CLIENT     AUTHN POLICY     DESTINATION RULE
> httpbin.default.svc.cluster.local:8000     OK         HTTP/mTLS     HTTP       default/         -

- `$ istioctl authn tls-check ${SLEEP_POD} httpbin.default.svc.cluster.local`

> HOST:PORT    STATUS     SERVER        CLIENT     AUTHN POLICY     DESTINATION RULE
> httpbin.default.svc.cluster.local:8000     OK         HTTP/mTLS     HTTP       default/         bad-rule/default

        STATUS is OK instead of CONFLICT as in the doc

- `kubectl exec $(kubectl get pod -l app=sleep -o jsonpath={.items..metadata.name}) -c sleep -- curl httpbin:8000/headers -o /dev/null -s -w '%{http_code}\n'`

        200

        (instead of 503 as mentioned in the docs)

In the **Verify Request** section:
- `$ kubectl exec $(kubectl get pod -l app=sleep -o jsonpath={.items..metadata.name}) -c istio-proxy -- curl http://httpbin:8000/headers -o /dev/null -s -w '%{http_code}\n'`

        200

        (instead of 000 as mentioned in the docs)
- `$ kubectl exec $(kubectl get pod -l app=sleep -o jsonpath={.items..metadata.name}) -c istio-proxy -- curl https://httpbin:8000/headers -o /dev/null -s -w '%{http_code}\n' --key /etc/certs/key.pem --cert /etc/certs/cert-chain.pem --cacert /etc/certs/root-cert.pem -k`

         000 

         (instead of 200 as mentioned in the docs)

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[x ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ x] Security
[ ] Test and Release
[ ] User Experience

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
istio-1.2-rc0

**How was Istio installed?**
using helm install on minikube

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
I followed the steps and it worked for me

**Comment by johnma14** [comment]
@howardjohn ok good. Then we can close this. Could be my env. Not sure why though

**Comment by howardjohn** [comment]
It could very well be a real bug, but it isn't a universal one at least

**Comment by pitlv2109** [comment]
I tried this task a few days ago and it worked as expected for me. When applying a policy config, you'll need to wait a bit for that config to be propagated to the proxy.
