### ISSUE TITLE
Istio CNI tarball is not built nor released

### ISSUE THREAD

**Issue by sdake** [istio/istio#14742]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
The documentation for istio-cni was reviewed and a problem was found WRT the lack of released helm charts.

see: https://github.com/istio/istio.io/issues/4327

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[X] Test and Release
[ ] User Experience

**Expected behavior**
An artifact exists to install CNI

**Steps to reproduce the bug**
Follow installation CNI guide here: https://preliminary.istio.io/docs/setup/kubernetes/additional-setup/cni/#installation

There is no artifact available for step 3.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.2.0-rc0

**How was Istio installed?**
following guide from istio-cni

**Environment where bug was observed (cloud vendor, OS, etc)**
not relevant

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by sdake** [comment]
https://github.com/istio/istio.io/issues/4327#issuecomment-500879135

**Comment by sdake** [comment]
@icygalz can you help us with this issue?  This is a critical issue for 1.2...  If the build can't be done, we have a whole lot of documentation to change...

**Comment by howardjohn** [comment]
See https://github.com/istio/istio/issues/13526 and associated PR. Hopefully we just need to merge that

**Comment by howardjohn** [comment]
This is merged via https://github.com/istio/istio/pull/14756

P0 is updating docs for this https://github.com/istio/istio.io/issues/4327
