### ISSUE TITLE
List of applications incompatible (or some features don't work) with Istio

### ISSUE THREAD

**Issue by esnible** [istio/istio#14743]
Several packages don't work due to current Istio limitations.  We have work items and epics for the *functionality* needed but no epic that shows our progress towards our goal of supporting everything.

(Some of these work partially, or mostly.)

ElasticSearch https://github.com/istio/istio/issues/14662  <-- FAQ entry added https://github.com/istio/istio.io/pull/4821
- also https://github.com/istio/istio/issues/24176

Cassandra https://github.com/istio/istio/issues/10053 <--FAQ entry being reviewed https://github.com/istio/istio.io/pull/4867

MySQL https://github.com/istio/istio/issues/13484 * <-- fixed/closed https://github.com/istio/istio/issues/16455
Apps using Java JMX / JRMP https://github.com/istio/istio/issues/15293  <-- see the issue for solution
CockroachDB https://github.com/istio/istio/issues/14909 <-- see the issue for solution

Couchbase Operator https://github.com/istio/istio/issues/12998
Apache Thrift https://github.com/istio/istio/issues/12845
Concourse https://github.com/istio/istio/issues/12521
Postgres ~~https://github.com/istio/istio/issues/11987~~ ~~https://github.com/istio/istio/issues/16506~~ https://github.com/istio/istio/issues/29761

Redis ~~https://github.com/istio/istio/issues/12079~~ ~~https://github.com/istio/istio/issues/14138~~ ~~https://github.com/istio/istio/issues/15429~~ ~~https://github.com/istio/istio/issues/16078~~ <-- see this issue for possible solution https://github.com/istio/istio/issues/24544

RabbitMQ ~~https://github.com/istio/istio/issues/15896~~ ~~https://github.com/istio/istio/issues/15726~~
Java 11 apps https://github.com/istio/istio/issues/16391 <-- envoyproxy issue #7973
*NEW* Zookeeper https://github.com/istio/istio/issues/19280

Spark https://github.com/istio/istio/issues/27900 - default bind

"*" addressed in newer releases. See the issue for release numbers.

**Comment by esnible** [comment]
@rlenglet Why Nebulous Future?

**Comment by rlenglet** [comment]
@esnible Will all those applications be supported in 1.3? If that's the goal, feel free to move to 1.3.

**Comment by esnible** [comment]
@frankbu Can you document this list?

**Comment by mbanikazemi** [comment]
I have been going through this list. For a lot of these applications, the configuration needs to be a bit different from that used when Istio is not involved. I am going to try to show common requirements first and then address these applications individually.

**Comment by mbanikazemi** [comment]
How to have ES work with Istio please see https://github.com/istio/istio/issues/14662.

**Comment by jpantsjoha** [comment]
Glad i came across this handy list, thank you.

**Comment by linsun** [comment]
https://github.com/istio/istio/issues/9784

**Comment by linsun** [comment]
per networking WG mtg today, mysql and SMTP protocol should be working for permissive mode now in 1.3.

**Comment by esnible** [comment]
There is a report that Apache NiFi is incompatible.  https://github.com/istio/istio/issues/17918

**Comment by linsun** [comment]
https://github.com/istio/istio/issues/19280

**Comment by esnible** [comment]
Should we add WebFluxRequestExecutingMessageHandler as discussed in #19728 to this list?

**Comment by Kyrremann** [comment]
Can you also add [Dask](https://dask.org/) to the list, as it communicate over IP between the workers. See thread: https://github.com/dask/dask-kubernetes/issues/197

**Comment by m-czernek** [comment]
Seems like the Java 11 issues have been fixed? Could you check and update the main page with fixed/closed please?

**Comment by howardjohn** [comment]
To the best if my knowledge all of these are working as of 1.10+

**Comment by fsniper** [comment]
Ignite is an application I have trouble with. Only way I could make it work is with excluding ignite ports.

**Comment by hanxiaop** [comment]
> Ignite is an application I have trouble with. Only way I could make it work is with excluding ignite ports.

Not sure about this app but I think you'd better create a new issue and describe your situation there.

**Comment by howardjohn** [comment]
I think ignite is a
https://istio.io/latest/docs/ops/deployment/requirements/#server-first-protocols;
that doc may help
