### ISSUE TITLE
Implement TOC-approved versioning and release scheme.

### ISSUE THREAD

**Issue by geeknoid** [istio/istio#14770]
Please see https://docs.google.com/document/d/1ilwz-HGSeiRDCFwP5rm-5d_UY6OOYL_nflx7bNggek0/edit?ts=5cfa97f8#

**Comment by howardjohn** [comment]
@geeknoid I may end up implementing some/all of this, so I left some clarification questions on the doc if you have a chance to follow up at some point

**Comment by howardjohn** [comment]
This is done via istio/release-builder
