### ISSUE TITLE
label "istio-injection=enabled" is not namespaced

### ISSUE THREAD

**Issue by thockin** [istio/istio#14777]
**Bug description**

Kubernetes labels are namespaced, with non-namespaced labels being reserved for end-users.  The correct name would be "istio.io/injection" or similar

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience

**Comment by irisdingbj** [comment]
+1 for changing to `istio.io/injection` as below reason: 

Valid label keys have two segments: an optional prefix and name, The prefix is optional. 

If the prefix is omitted, the label Key is presumed to be private to the user. Automated system components (e.g. kube-scheduler, kube-controller-manager, kube-apiserver, kubectl, or other third-party automation) which add labels to end-user objects must specify a prefix.

**Comment by thockin** [comment]
Is there a bot command to stale-proof this without label-edit access on my part?
