### ISSUE TITLE
Docs:  `kubectl get` for labels is -l, doc says -L

### ISSUE THREAD

**Issue by thockin** [istio/istio#14778]
https://istio.io/docs/setup/kubernetes/additional-setup/sidecar-injection/

lists at least one `-L` - "kubectl get namespace -L istio-injection"

**Comment by pitlv2109** [comment]
With `-l`, I got
```
NAME           STATUS   AGE
default        Active   42d
foobar         Active   41d
istio-system   Active   42d
```
With `-L`, I got
```
NAME           STATUS   AGE   ISTIO-INJECTION
default        Active   42d   enabled
foobar         Active   41d   enabled
istio-system   Active   42d   disabled
kube-public    Active   42d   
kube-system    Active   42d   
```

So I think `-L` should be use in this context.

**Comment by thockin** [comment]
OMG! i didn't know -L was a thing.  The version I tested yesterday must be old.  How embarrassing.
