### ISSUE TITLE
Add SDS stats back into bootstrap config.

### ISSUE THREAD

**Issue by JimmyCYJ** [istio/istio#14773]
**Describe the feature request**
https://github.com/istio/istio/pull/10184 introduced a stats_matcher. cluster and listener stats are not in the inclusion list. There are SDS stats that are not shown in the /stats. listener.<LISTENER_IP>.server_ssl_socket_factory.ssl_context_update_by_sds and cluster.<CLUSTER_IP>.client_ssl_socket_factory.ssl_context_update_by_sds. These stats are useful for testing, monitoring, and debugging key/cert provisioning via SDS in Istio. 

**Describe alternatives you've considered**
Add the stats back with minimum CPU and memory cost.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Policies and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience

**Comment by howardjohn** [comment]
There is a statsInclusion annotation that should work - can provide a link soon on my phone right now though

**Comment by JimmyCYJ** [comment]
I am going to add listener.<LISTENER_IP>.server_ssl_socket_factory.ssl_context_update_by_sds and cluster.<CLUSTER_IP>.client_ssl_socket_factory.ssl_context_update_by_sds into the inclusion list. I am wondering if there are other useful stats we can add to monitor and debug ADS.

**Comment by howardjohn** [comment]
you can add it just to the test if it isn't universally useful as well

**Comment by douglas-reid** [comment]
yeah, if these are for debugging, I wonder if we really need them on by default.  @JimmyCYJ do you think these should be on for every proxy in the mesh all the time?

**Comment by howardjohn** [comment]
@JimmyCYJ sorry couldn't give more details later. if it is just for the tests we can just add an annotation like:
`sidecar.istio.io/statsInclusionPrefixes: cluster.outbound,cluster_manager,listener_manager,http_mixer_filter,tcp_mixer_filter,server,cluster.xds-grpc` (except with your stats)

Or statsInclusionSuffixes or statsInclusionRegexps if those are better

**Comment by JimmyCYJ** [comment]
@howardjohn @douglas-reid Thanks for the response. I think we need these two SDS counters on by default. If customers hit a production issue with SDS, these counters are useful for debugging. Right now we don't have a convenient view of SDS secret pushes. Is it okay for me to add requiredEnvoyStatsMatcherInclusionSuffixes="ssl_context_update_by_sds", and pass it here?https://github.com/istio/istio/blob/52e9659759c01fa91701dfc1d4da72abd9aa1f1a/pkg/bootstrap/bootstrap_config.go#L124.

**Comment by howardjohn** [comment]
@JimmyCYJ I think the required ones are actually **required**. Pilot-agent will not function without them, they can never be disabled.

So we could potentionally turn it on by default but cannot make it required

**Comment by mandarjog** [comment]
Add the following annotion to the POD `sidecar.istio.io/statsInclusionSuffixes: ssl_context_update_by_sds`

For ingress you need to add it directly as env.
https://github.com/istio/istio/wiki/Envoy-native-telemetry
