### ISSUE TITLE
Tests: Server side configuration validation with WebHooks

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1478]
@kyessenov commented on [Mon Oct 09 2017](https://github.com/istio/old_pilot_repo/issues/1413)

Context: [production readiness proposal and plan](https://goo.gl/pmjuYg)

The feature “_configuration validation_” is identified as incomplete test coverage. As a measure to reach Istio production quality in 0.3, this issue is opened to track the progress of providing sufficient test coverage for the feature in question.

This issue is initially assigned to the working group leads.

**Recommendations**:
- Come up with a test plan for how the feature should be tested. Identify and document (in this issue, or a separate document this issue will link to) test cases and whether each will be covered by an integration test (with some level of mocking and/or starting up selected components in test environment), or end to end test (aka system test, which brings up the whole Istio to exercise the feature; currently live in the istio/istio repo).
- If you expect the test plan is complex and controversial, consider having it formally reviewed.
- State an ETA in the issue, and assign this to a developer who will execute the test plan.
- Execute the test plan as the highest priority for 0.3.
- For any bug or defect identified by the new test cases, file a new issue and link it from this one.
- Close this issue only when the test plan is completely executed, and all additional issues identified in step 3 are fixed.

If you see a risk of not fixing this issue by end of 0.3, please contact istio-production-quality@googlegroups.com as soon as possible. We will also periodically ping the issue for update.

---

@rshriram commented on [Wed Oct 11 2017](https://github.com/istio/old_pilot_repo/issues/1413#issuecomment-335964798)

@ayj if you think this is well tested, feel free to close this down. For the moment, assigning this to you since you worked on this.

---

@ayj commented on [Fri Oct 20 2017](https://github.com/istio/old_pilot_repo/issues/1413#issuecomment-338325044)

Moving  testing infrastructure to k8s 1.8 and additional changes are required to enable this feature end-to-end. Probably about a weeks worth of effort to update the code to work out-of-box with k8s 1.8.

/cc @istio/test-infra-hackers for updating testing infrastructure to GKE 1.8

---

@yutongz commented on [Fri Oct 20 2017](https://github.com/istio/old_pilot_repo/issues/1413#issuecomment-338338395)

Since it's already Friday afternoon, let's do this on Monday.

---

@yutongz commented on [Mon Oct 23 2017](https://github.com/istio/old_pilot_repo/issues/1413#issuecomment-338733672)

It turns out, GKE hasn't gone that fast to provide 1.8 clusters. @ayj 

---

@cmluciano commented on [Mon Oct 30 2017](https://github.com/istio/old_pilot_repo/issues/1413#issuecomment-340573918)

/assign 

I will be helping with this feature

**Comment by cmluciano** [comment]
https://github.com/istio/istio/blob/master/pilot/platform/kube/admit/admit_test.go is now running successfully in pilot-presubmit.

@andraxylia @kuat @ayj Is there still a need for a dedicated e2e test?

**Comment by ayj** [comment]
Yes, I think so. `admin_test.go` unit tests elements of validation but server-side validation via webhook is still not on by default in e2e tests.

**Comment by cmluciano** [comment]
fixed in #1987
