### ISSUE TITLE
Stackdriver Traces Always Report Request/Response size '0'

### ISSUE THREAD

**Issue by dansiviter** [istio/istio#14785]
**Bug description**
From the `mixer/adapter/stackdriver/operatorconfig/stackdriver.yaml`the Trace spans always report zero bytes:

![Screenshot 2019-06-13 at 09 59 16](https://user-images.githubusercontent.com/1540398/59420783-64c1b180-8dc5-11e9-858d-17fa9da07bec.png)

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

**Expected behavior**
Useful data in the spans.

It appears it's using the attributes `request.size` and `response.size` which extract their data from the `content-length`. Unfortunately, much of the data is chunked so rarely gives useful data. It seems `[request|response].total_size` may work but this would also include headers and trailers in addition to the body, although this may be preferred.

**Steps to reproduce the bug**
Run in `mixer/adapter/stackdriver/operatorconfig/stackdriver.yaml` and observe traces.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Tag `1.1.8`.

**How was Istio installed?**
Helm

**Environment where bug was observed (cloud vendor, OS, etc)**
GCP Stackdriver

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by bianpengyuan** [comment]
Why do you think `request.size` and `response.size` are from `context-length` header? Envoy accumulates the bytes it decodes and encodes, no? e.g. https://github.com/envoyproxy/envoy/blob/838eb20c67d594425fb98f203857b292f37b5778/source/common/router/router.cc#L1370 and https://github.com/envoyproxy/envoy/blob/838eb20c67d594425fb98f203857b292f37b5778/source/common/router/router.cc#L1426. My understanding is that these two attributes track request/response body size. Is it the case that those two attributes are 0 even request/response body is not empty?

**Comment by dansiviter** [comment]
> Size of the request in bytes. For HTTP requests this is equivalent to the Content-Length header.
From: https://istio.io/docs/reference/config/policy-and-telemetry/attribute-vocabulary/#targetText=A%20given%20Istio%20deployment%20has,services%20can%20also%20introduce%20attributes.

Although as you've started that may not be the case, the documentation implies it is. Either way, I just want useful values rather than zero.

**Comment by bianpengyuan** [comment]
So what is the size you want to observe? In the issue description, seems like [request|response].total_size (headers + body) is what you should use, no?

**Comment by douglas-reid** [comment]
How can we resolve this issue?  Should this be closed, given the pending stackdriver trace integration?

**Comment by bianpengyuan** [comment]
@dansiviter Please let us know if [request|response].total_size does not resolve your issue. Thanks!
