### ISSUE TITLE
TestPodCache/localApiserver unit-test flake

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#14791]
https://testgrid.k8s.io/istio-presubmits-master#unit-tests&width=20

Example failures:
* https://prow.k8s.io/view/gcs/istio-prow/pr-logs/directory/istio-unit-tests-master/1759
* https://prow.k8s.io/view/gcs/istio-prow/pr-logs/directory/istio-unit-tests-master/1767
* https://prow.k8s.io/view/gcs/istio-prow/pr-logs/directory/istio-unit-tests-master/1844
* https://prow.k8s.io/view/gcs/istio-prow/pr-logs/directory/istio-unit-tests-master/1854

4 times in ~a day, so happens fairly regularly

**Comment by pitlv2109** [comment]
Looks like it was timed out either during service account creation or secret creation. Recently, it's been passing pretty consistently though.

**Comment by howardjohn** [comment]
Seems to still be failing. Recent one: https://gubernator.k8s.io/build/istio-prow/pr-logs/pull/istio_istio/15297/istio-unit-tests-master/3070/

**Comment by howardjohn** [comment]
@geeknoid your bot may need a new clock, it looks like it triggers every day instead of every 3 days

**Comment by howardjohn** [comment]
This doesn't really seem to fail anymore
