### ISSUE TITLE
New Installer needs Kustomize support for the injection template

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#14793]
Wanting to modify the injection template is a fairly common task, but as far as I know we can't use Kustomize to modify it.

We should either:
* Document how to kustomize it if it is possible
* Try to find a way to kustomize it or some alternative

**Comment by c0d1ngm0nk3y** [comment]
You mean the template of the configmap `istio-sidecar-injector` located at `kustomize/istio-control/istio-autoinject.yaml`, right?

Shouldn't it be possible to have an own `kustomization.yaml` referring to the existing files and patching the template property? Would that be an option?

**Comment by howardjohn** [comment]
yeah but the template is just a string, the templating is done in the injector at runtime. So I don't think Kustomize can handle that - if it can that would be great though

**Comment by c0d1ngm0nk3y** [comment]
I don't know how the modifications to the template normally look like. Do you have an example. Right now, I see options:

1) Overwriting the whole template string in an overlay. This is already now possible, but there is no reuse of the existing template.
2) Introducing a `template-patch` property which is by default empty and will be merged after the templating is done. So this property can be overwritten. Would this be an option or do the modifications normally involve the use of template parameters? I wouldn't think so.

I guess 1) is not enough (hence this issue). @howardjohn Do you think 2) is an option? The implementation should't be to much and keep it compatible (if there is no `template-patch`, nothing is done.

**Comment by howardjohn** [comment]
I don't think there is any strong demand for this
