### ISSUE TITLE
We should have a linter for go mod tidy

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#14795]
In dep we had a test that would fail if you didn't vendor correctly.

Now with go mod require devs to follow https://github.com/istio/istio/wiki/Vendor-FAQ and `go mod tidy && go mod vendor` but we don't actually test this, so a lot of bad changes get in.

@kyessenov @geeknoid

**Comment by geeknoid** [comment]
I'd rather simply stop vendoring. We're not vendoring in other repos and it's been working well.

**Comment by kyessenov** [comment]
+1 to stop vendoring.
- wait until 1.2 is out so we can move forward with go 1.12
- update license checker script
- add a few module proxies; the default one went down last Sunday

**Comment by hzxuzhonghu** [comment]
We all adapted to vendor,  please do not remove it.    

Just need to add a CI for it

**Comment by geeknoid** [comment]
@hzxuzhonghu Why do you think vendor is worth keeping?

**Comment by hzxuzhonghu** [comment]
Without vendor, users have to get all the vendors before compile, even just reading code requires all the vendors.

**Comment by howardjohn** [comment]
How does having multiple branches work without vendor? If I hop between 1.0, 1.1 and 1.2 there are different dependencies, do I need to figure out all the dependencies every time I switch branches? Does it impact CI speed?

**Comment by geeknoid** [comment]
When you don't use vendor, packages are stored in an invisible module
directory. Multiple versions of these packages exist, based on the hash or
version #. So you can switch branches all you want and you get the correct
version of the modules as specified in the branch's go.mod file. It
actually works well.

**Comment by ericvn** [comment]
We can't remove vendor yet since it's actually used during the build iirc. Some more investigation to be done on the current build process.

**Comment by ericvn** [comment]
I don't believe we actually are doing as @geeknoid mentions else we would be broken as we were using Golang 10 for the builds up until yesterday.

**Comment by ericvn** [comment]
@hzxuzhonghu Without vendor you would only need to pull once to get the files into the go mod cache. But you are correct that you have to do it once to prime the cache so you can do some of the more advanced IDE things.

**Comment by kyessenov** [comment]
@howardjohn 
Modules are a standard part of the language now, so sooner or later vendor will have to go. There is no difference between keeping code in the vendor git directory, or in some shared infra cache, such as the one provided by the google module proxy. There are just two possible problems:
- module cache can go down (e.g. recent GCP outage brought it down); we need several alternatives, as well as a GCS backup (go modules can read directly from files instead of HTTP servers) any time we make an important build.
- external repository can disappear: one would question why we would even depend on such a repository to begin with, but a GCS backup can surely help here.

**Comment by ericvn** [comment]
This all said, we do need a linter for the short term. We build from the _vendor_ directory, not the cache, so someone putting a change into the go.* files won't really see the change during a build (they won't when building locally either (unless the set GO111MODULE=on or are using a non-standard dev path). Now that we have 1.12 in _master_ we can decide on the best way forward. I suspect we'll keep the path for consistency, so start with GO111MODULE=on. and so forth. @kyessenov had some comments earlier. I'll gladly help with the move forward to modules fully in our dev environment.

**Comment by geeknoid** [comment]
Can we switch everything on master to Go 1.12? Then we can disable vendor.

We're already on the no-vendor go module plan in other repos.

**Comment by howardjohn** [comment]
I think @costinm  has some strong opinions on this, may want to get his opinion before we make such a change

**Comment by hzxuzhonghu** [comment]
Also take those who can not access the vendors (like in private cloud or firewall stopping from accessing outside ) in to consideration,

**Comment by ericvn** [comment]
I think we can simply do something like this somewhere in prow (we used to do this in circles but that is going away)
```
	GO111MODULE=on go mod tidy && GO111MODULE=on go mod vendor
	git diff --name-only HEAD -- vendor | grep -v vendor/modules.txt | wc -l and compare to zero
```

I had to grep out `vendor/modules.txt` as on my laptop I had one line moved in the file running the above command.

I'll see if I can maybe come up with something in my free time.

**Comment by hzxuzhonghu** [comment]
We can refer to kubernetes vendor linter as well, i see it is there.

**Comment by costinm** [comment]
/vendor has 2 main purposes:
1. Make sure we can reproduce a build - git repos can go away. There are a couple of 'archives' that use go mod and keep old versions - I think it should be a requirement to integrate with one and test that it works.

2. Speed. We did tests and it appears a build using vendor is faster, or at least it was for dep. Any change to remove vendor should include numbers and tests to confirm we don't regress.

For the first issue - the proper solution is to make sure our releases include the source code of all 
dependencies ( i.e. what vendor contains now ) and  it is possible to take the released .src.tar.gz and make it to produce a binary. 

For the second issue - I believe some of the mod proxies may be close to the speed of having vendor, most of the overhead is in making connections and fetching N repositories (with full history) instead of one connection downloading all.

**Comment by costinm** [comment]
In other words: we should have a test that verifies we can reproduce a build ( maybe by adding a full .tar.gz and doing a make build from the .tar.gz without any network access ), and a second test for the build speed, before we can remove vendor.

**Comment by hzxuzhonghu** [comment]
have a look at #15056

**Comment by ericvn** [comment]
@hzxuzhonghu What failure do you have with particular repos? You mention you don't have access to certain ones. Just trying to figure out a path moving forward if we remove vendor. As mentioned, most IDEs don't need the vendor anymore.

If you simply deleted vendor (or rename it) and try `GO111MODULE=on go mod vendor`, what happens? I would hope that Go would pull all the required repos into a new vendor directory. I understand it might take a bit (you might be able to set GOPROXY to local proxy to help with that). This would be a simple step to get a vendor directory if it was no longer in our repo.

I do see a change being made locally after testing myself:
```
	modified:   go.mod
	modified:   vendor/modules.txt
```
that I want to see about. Maybe the lack of a linter has allowed some changes...

**Comment by ericvn** [comment]
@costin I agree with your #1 in that the lack of a vendor directory can make it harder to reproduce a build. I'm not sure if we, Istio, want to get into hosting a GOPROXY (Athens, go proxy, etc) that would keep old versions, etc. It would need to use some storage that is adequately backed up. This was always one of my reasons to say that the vendor directory should be checked in with the source. It seems that the new dependency management is making that tougher. The question is if we really think we can rely on the GOPROXY to cache versions or just fall back indirect access to the repos.

Network/no network test. I'm not sure how valid this is. We have to be able to have network access to at least get to a starting point (clone our current repo for example). If we simply say that we also need to pull the modules from the proxy (which is mimicking the clone of the vendor directory), is that allowed? In the later case, the tar would be the Istio directory plus go/pkg/mod.

For speed in #2, the actual _go build_ post getting the modules seems to be equal. I'll see about getting some specific timings. The difference will be in cloning the repo with the vendor vs the time to clone the repo minus vendor and doing a `go mod download` (the build time should be approx equal post that) vs cloning the repo and doing a go build and letting it download modules during the build.

**Comment by ericvn** [comment]
A quick check averaging over several attempts (clearing go modcache before each run)
  - go mod download (direct, no proxy): 82 seconds
  - go mod download (go proxy.io): 47 seconds

**Comment by geeknoid** [comment]
If we're paranoid about goproxy.io disappearing or losing old versions, we
could host this proxy ourselves. It's pretty simple. modules.istio.io
anyone?

**Comment by kyessenov** [comment]
https://proxy.golang.org is in beta, has on-call support, and is almost ready for general consumption.

**Comment by ericvn** [comment]
For setting up our own, I've also looked at https://github.com/gomods/athens which has storage drivers and https://github.com/goproxyio/goproxy which uses disk. The later doesn't seem like something to depend on, unless we have a way to back up the disk occasionally. Not sure what's available storage wise for setting up the former.

I did try the https://proxy.golang.org, but found a number of our modules aren't there yet.

**Comment by hzxuzhonghu** [comment]
> @hzxuzhonghu What failure do you have with particular repos? You mention you don't have access to certain ones. Just trying to figure out a path moving forward if we remove vendor. As mentioned, most IDEs don't need the vendor anymore.

@ericvn It is because we have network limit from accessing google in China. We have to set a proxy, which may introduce unknow error. Also think about the hosts, which may have no access to the internet at all.

**Comment by howardjohn** [comment]
my understanding is that once you build once and the dependency are pulled down you can continue to build without internet - just like with vendor.

if we set up a proxy would you he able to access it? can you access other existing proxies?

**Comment by hzxuzhonghu** [comment]
I will test it later.

**Comment by ericvn** [comment]
@howardjohn Yes. I could build fine once the modules are pulled down and in my local Go module cache and removing internet access.

@hzxuzhonghu I'm hoping your testing does show things will work. To simply get the modules into the cache you can try `GO111MODULE=on go mod download` which uses `GOPROXY` to define where to pull the modules. If unset, it will try to get them directly from the repos, else you can try `export GOPROXY=https://goproxy.io` and point to one of the caches (sorry if you already know all this). 

If your IDE needs to find the files in the _vendor_ directory you can run the `go mod vendor` which will place them there as well.

**Comment by hzxuzhonghu** [comment]
Feel very sad, We are already using a proxy to access internet from office, and do the above, a lot of errors occur.

```
$ go mod download
go: finding github.com/grpc-ecosystem/go-grpc-prometheus v0.0.0-20160910222444-6b7015e65d36
go: finding github.com/Microsoft/go-winio v0.4.12
go: finding github.com/alicebob/gopher-json v0.0.0-20180125190556-5a6b3ba71ee6
go: finding github.com/gotestyourself/gotestyourself v2.2.0+incompatible
go: finding github.com/Azure/go-autorest v11.1.0+incompatible
go: finding github.com/sethgrid/pester v0.0.0-20180227223404-ed9870dad317
go: finding github.com/ryanuber/go-glob v0.0.0-20160226084822-572520ed46db
go: finding github.com/coreos/go-oidc v0.0.0-20180117170138-065b426bd416
go: finding github.com/gogo/status v1.0.3
go: finding github.com/gogo/protobuf v1.2.1


go: github.com/sethgrid/pester@v0.0.0-20180227223404-ed9870dad317: unexpected status (https://goproxy.io/github.com/sethgrid/pester/@v/v0.0.0-20180227223404-ed9870dad317.info): 401 authenticationrequired
go: finding github.com/googleapis/gax-go/v2 v2.0.4
go: github.com/gogo/protobuf@v1.2.1: unexpected status (https://goproxy.io/github.com/gogo/protobuf/@v/v1.2.1.info): 401 authenticationrequired
go: finding github.com/cenkalti/backoff v2.0.0+incompatible
go: github.com/ryanuber/go-glob@v0.0.0-20160226084822-572520ed46db: unexpected status (https://goproxy.io/github.com/ryanuber/go-glob/@v/v0.0.0-20160226084822-572520ed46db.info): 401 authenticationrequired
go: github.com/alicebob/gopher-json@v0.0.0-20180125190556-5a6b3ba71ee6: unexpected status (https://goproxy.io/github.com/alicebob/gopher-json/@v/v0.0.0-20180125190556-5a6b3ba71ee6.info): 401 authenticationrequired
go: finding github.com/docker/docker v1.13.1
go: github.com/grpc-ecosystem/go-grpc-prometheus@v0.0.0-20160910222444-6b7015e65d36: unexpected status (https://goproxy.io/github.com/grpc-ecosystem/go-grpc-prometheus/@v/v0.0.0-20160910222444-6b7015e65d36.info): 401 authenticationrequired
go: finding k8s.io/kube-openapi v0.0.0-20180216212618-50ae88d24ede
go: finding github.com/istio/viper v1.3.3-0.20190515210538-2789fed3109c
go: github.com/Azure/go-autorest@v11.1.0+incompatible: unexpected status (https://goproxy.io/github.com/%21azure/go-autorest/@v/v11.1.0+incompatible.info): 401 authenticationrequired
go: github.com/gotestyourself/gotestyourself@v2.2.0+incompatible: unexpected status (https://goproxy.io/github.com/gotestyourself/gotestyourself/@v/v2.2.0+incompatible.info): 401 authenticationrequired
go: finding github.com/keybase/go-crypto v0.0.0-20190416182011-b785b22cc757
go: finding github.com/circonus-labs/circonus-gometrics v2.3.1+incompatible
go: github.com/coreos/go-oidc@v0.0.0-20180117170138-065b426bd416: unexpected status (https://goproxy.io/github.com/coreos/go-oidc/@v/v0.0.0-20180117170138-065b426bd416.info): 401 authenticationrequired

...
```

**Comment by howardjohn** [comment]
I added `go mod tidy` to the `make format`. So we are 90% of the way there. I wasn't sure if doing `go mod tidy` and then `git status` was a good idea for the lint though

**Comment by howardjohn** [comment]
@geeknoid added some new gen-checks that will run `go mod tidy` and others and check git status, so I am closing this as done
