### ISSUE TITLE
in code: wait for, instead of create, pilot CRDs (as those are created when pilot is installed already (yaml))

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1480]
@linsun commented on [Fri Sep 29 2017](https://github.com/istio/old_pilot_repo/issues/1375)

We have code in pilot to create CRDs and we also added code in istio.yaml to create these same resources via istio installation, mainly for the purpose to delete them easily during istio uninstallation via `kubectl delete -f istio.yaml`.   We should look into an optimized approach.

open this for discussion and resolution of this.  slack chat histories:

Lin Sun [7:58 PM] 
oh i was not referring to the the template in pilot.  i’m talking about this code:  https://github.com/istio/pilot/blob/master/adapter/config/crd/client.go#L147
GitHub
istio/pilot
pilot - Istio Pilot implementation
 

Andra Cismaru [8:21 PM] 
that code is fine, it does not require changes, @kuat can confirm

Lin Sun [8:43 PM] 
i’d appreciate if @kuat can chime in.  I thought the purpose of doing the resource install via yaml is we don’t need to do it in the code.

kuat
[9:07 PM] 
i don't think code change is necessary since the code won't fail if CRDs are present

Lin Sun [9:10 PM] 
that was my worry, would it not fail (i assume you’ll get XX already exist warning) plus it is unnecessary code.

kuat
[9:10 PM] 
@andra's definitions are derived from the programmatic creation, i think it'll be easier to keep it in sync when CRDs change

[9:11] 
mixer does similar thing, we install a snapshot of 0.2 CRDs but these CRDs might change

Lin Sun 
[9:21 PM] 
oh, i thought the registerResource() only runs when discovery service starts…  no?   i don’t understand your comment about keep in sync when CRDs change…. is that when user edits the CRD?

Laurent Demailly [9:30 PM] 
I don't think we have a good process to keep those yaml and the code in sync, something for 0.3 also agree with lin that we probably don't need to try to create the crds if we expect them to be created at install time - on the other hand it may be more resilient to create them in the code and maybe have a cleanup

----- Today September 29th, 2017 -----
Andra Cismaru [12:08 AM] 
because we do not control the timeing of the application of resources, CRDs and pilot/mixer svc, we still have to create them in the code. Their presence in the yaml files is required if we want to do a clean cleanup.

Laurent Demailly [1:03 AM] 
As the CRD is in the same file as pilot there is no reason (except to mask typos between the code and the file) that I can see (happy to hear one though) to create them again in the code, is there ? Just need to wait that they are all available to process the CRs (edited)

Lin Sun 
[9:13 AM] 
@andra were your definition in the yml file generated programmatically from pilot code?

Andra Cismaru [12:05 PM] 
To recap, since it seems to have gotten lost in slack, the purpose of adding the CRDs to the yaml file was that they are cleaned during un-install, so the user does not need to run a fancy command to clean them. It was not to simplify or remove that code from pilot. They are not programmatically generated, that would be overkill for little benefit. If you look at the code more carefully, there is no error if the resource already exists. Yes, the yaml files have to be kept in sync with the code, this is true for all other resources in the yaml, secrets, configMaps etc. The worst thing that can happen in case of a typo is they would be left in the system after uninstall, not serious enough to justify a machinery to generate based on code or other complexity. (edited)

Laurent Demailly 
[12:09 PM] 
I think we are just asking why keep re creating in code / I don't think you answered that (my question above)

Andra Cismaru [12:15 PM] 
because we do not control the timing of the start, I commented about that in the mixer channel. Imagine the CRDs creation and mixer/pilot start can be in any order .

[12:16] 
this is why we still need that in the code

[12:17] 
though mixer and pilot may be different here, mixer does not create them, indeed, but it has some logic to wait for their creation. It would be indeed good to re-design this part to behave the same @kuat and @mjog own this code

[12:19] 
we should probably move this discussion to github, please open an issue in pilot and assign it to kuat

Lin Sun [12:27 PM] 
ok the unable to control timing makes sense to me now.   @kuat do you think it is possible to delete the resource in pilot code like how the resource is created in discovery init?

[12:29] 
not sure if k8s has a delete pod/deployment hookpoint

kuat [12:34 PM] 
@linsun yes, but it's a programmatic call, not just `kubectl` command. registering/deregistering CRDs can be a multi-minute process

Laurent Demailly 
[12:35 PM] 
That's why I said "wait" above, not create

Lin Sun [12:38 PM] 
i see, thanks @kuat!  yea, it’d be consistent if we do it either all in yaml which we need to wait, or all in code.  we are hybird now :slightly_smiling_face:

---

@ldemailly commented on [Thu Oct 05 2017](https://github.com/istio/old_pilot_repo/issues/1375#issuecomment-334648517)

another reason to not create crd in code: https://groups.google.com/forum/#!msg/istio-users/NrQ6iABjcqo/jlTemfoEBQAJ

cc @rkpagadala

**Comment by louiscryan** [comment]
This seems pretty stale.

**Comment by kyessenov** [comment]
I don't think anything has been done about it: https://github.com/istio/istio/blob/master/pilot/pkg/config/kube/crd/client.go#L221

**Comment by ayj** [comment]
CRD are now installed via explicit YAML. Installing them from Pilot isn't necessary. It's also lead to subtle bugs where the YAML and Pilot CRD definition diverge, e.g. Namespace vs. Cluster scoped RBACConfig. We should consider removing self-installing CRD from Pilot by default with `--disable-install-crds=true` for 1.1 release. This aligns with the longer term plan to remove direct k8s code dependencies from Pilot for 1.2+.

https://github.com/istio/istio/blob/5cf84e5e31b8425154ce524044cf5a3f05ddd67d/pilot/cmd/pilot-discovery/main.go#L115
