### ISSUE TITLE
TestIngessToPrometheus_ServiceMetric is flaky

### ISSUE THREAD

**Issue by gargnupur** [istio/istio#14819]
**Bug description**
TestIngessToPrometheus_ServiceMetric is flaky.
This applies to all the tests under tests/integration/mixer/telemetry/scenarios_test.go as they try to do new bookinfo deployment for each test case.
**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ x] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

**Comment by gargnupur** [comment]
Does not look flaky in postsubmits... https://testgrid.k8s.io/istio_istio_postsubmit#integ-mixer-k8s-tests_istio_postsubmit
Will remove the flaky tag...

**Comment by howardjohn** [comment]
https://prow.k8s.io/view/gcs/istio-prow/logs/integ-mixer-k8s-tests_istio_postsubmit/468
https://prow.k8s.io/view/gcs/istio-prow/logs/integ-mixer-k8s-tests_istio_postsubmit/497
https://prow.k8s.io/view/gcs/istio-prow/logs/integ-mixer-k8s-tests_istio_postsubmit/430
https://prow.k8s.io/view/gcs/istio-prow/logs/integ-mixer-k8s-tests_istio_postsubmit/441
