### ISSUE TITLE
Default config values should be for production, not testing

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1482]
@andraxylia commented on [Tue Sep 19 2017](https://github.com/istio/old_pilot_repo/issues/1312)

Current default config values int he code (discovery refresh rate etc) are good for testing, not for production. It should be the other way, so the user only needs to override values that they want to change, not all of them.

https://github.com/istio/pilot/blob/master/proxy/context.go#L145

The configMap should be used to tune specific environments of the deployment environment, and fields should be present there, but commented out.

Also, if auth should be enabled by default in the code.

**Comment by louiscryan** [comment]
I think this is out of date now that we push changes rather than polling.
