### ISSUE TITLE
Add workload kind as an attribute

### ISSUE THREAD

**Issue by Pothulapati** [istio/istio#14839]
**Describe the feature request**

If the workload `kind` is also a supported attribute, then there can be metrics to show based on the granularity i.e pod, service, deployment, etc. As there are already some attributes specific to kubernetes i.e uuid, etc, I was thinking adding this shouldn't be a problem. I think this will not only be useful for [SMI-Metrics](https://github.com/deislabs/smi-metrics) but also a lot of other tools being built on top of istio telemetry.

If the issue is accepted and the team thinks it can be done, I will be glad to take this up and contribute to Istio on adding `workload_kind` as an attribute. :)

**Describe alternatives you've considered**

Right now, Tools like Kiali and Stackdriver depend on fields like `workload` and `uuid` and talk to the k8s api to get the workload type info. But having this label, would make it more easy to build tools as they would only depend on the adapter and don't have to talk to k8s API.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience

**Additional context**

**Comment by douglas-reid** [comment]
The issue, as I see it, with such an approach is that `kind` is specific to k8s (for instance, what would the meaning of `kind` be in VM scenarios, etc.).  We do already populate `workload.owner` attributes, which include the kind information for k8s, however.

Example: `kubernetes://apis/extensions/v1beta1/namespaces/istio-system/deployments/istio-telemetry`

In the work to move attribute-like information into the proxy metadata, we explicitly chose not to provide a breakout of `kind` (and the associated `apiversion`), and instead continue to use the opaque `owner`. 

I'm going to close this issue, given that context.
