### ISSUE TITLE
Tracking: perf profiling for Pilot Ingress

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1484]
@rshriram commented on [Mon Sep 11 2017](https://github.com/istio/old_pilot_repo/issues/1237)

Use this issue to track all perf profiling aspects of Istio pilot.
Sample app: acme air (diagram below)
![pasted image at 2017_09_11 12_25 pm](https://user-images.githubusercontent.com/8202871/30287152-04011f1e-96f2-11e7-970d-ef7d0b3c2bba.png)

First tested with Istio 0.1.6. Big performance jump when refresh interval was increased from 10ms to 60s. CPU Usage still seems high (2 cores - not visible in the CPU figure below). This needs to be tested with Istio 0.2.x series and we need to set the defaults, logging levels, etc. correctly before making the release. Turning on pprof in pilot - nothing useful at all in the profiling data. Next step is to use linux perf tests..

cc @kyessenov @ayj 

![pasted image at 2017_09_11 09_53 am](https://user-images.githubusercontent.com/8202871/30287203-3a910788-96f2-11e7-8540-58eb0bcb3c75.png)

![pasted image at 2017_09_11 09_57 am](https://user-images.githubusercontent.com/8202871/30287214-450859be-96f2-11e7-9584-7e797a40ba24.png)

---

@suryadu commented on [Mon Sep 11 2017](https://github.com/istio/old_pilot_repo/issues/1237#issuecomment-328605263)

Here is the Istio Ingress Contoller CPU usage chart
![image](https://user-images.githubusercontent.com/13684010/30288689-488b28ee-96ef-11e7-84c5-b940b6d11d28.png)

---

@kyessenov commented on [Mon Sep 11 2017](https://github.com/istio/old_pilot_repo/issues/1237#issuecomment-328609571)

Ingress has entirely different performance requirements than the sidecar. Let's focus on the ingress here and not mix the two.

---

@suryadu commented on [Mon Sep 11 2017](https://github.com/istio/old_pilot_repo/issues/1237#issuecomment-328614350)

That makes sense! I will open a separate issue for each area of Istio from performance point of view as we see performance degradation from logging, Mixer, Ingress etc.,

---

@rshriram commented on [Mon Sep 11 2017](https://github.com/istio/old_pilot_repo/issues/1237#issuecomment-328615015)

cc @louiscryan FYI, since you were asking about this.

---

@rshriram commented on [Wed Sep 27 2017](https://github.com/istio/old_pilot_repo/issues/1237#issuecomment-332646408)

This is with Istio 0.2.4 (which includes mixerclient caching). 
cc @douglas-reid 
![istio-0 2 4](https://user-images.githubusercontent.com/8202871/30936303-674fd7ac-a3a1-11e7-803b-dd324849131c.png)

Armada ingress is nginx
Istio ingress is Envoy, no mixer, and no sidecar Envoys.
Istio full is ingress plus sidecar envoys (with or without mixer checks, but reports are always on)
4vCPU and 16GB RAM per node. 

---

@suryadu commented on [Wed Sep 27 2017](https://github.com/istio/old_pilot_repo/issues/1237#issuecomment-332648747)

Here is the view from response time (Latency) perspective.
![image](https://user-images.githubusercontent.com/13684010/30936709-5340b5e4-a39a-11e7-833e-d4f6cad659b3.png)

---

@ldemailly commented on [Wed Sep 27 2017](https://github.com/istio/old_pilot_repo/issues/1237#issuecomment-332655612)

Subscribe

---

@linsun commented on [Wed Sep 27 2017](https://github.com/istio/old_pilot_repo/issues/1237#issuecomment-332657822)

subscribe

---

@kyessenov commented on [Mon Oct 02 2017](https://github.com/istio/old_pilot_repo/issues/1237#issuecomment-333612877)

cc @ldemailly @andraxylia @smawson 

---

@suryadu commented on [Mon Oct 02 2017](https://github.com/istio/old_pilot_repo/issues/1237#issuecomment-333629659)

Here is the improvement once we disable the sidecars
![image](https://user-images.githubusercontent.com/13684010/31093932-f5b9880a-a778-11e7-861a-372e48eb43aa.png)

---

@sdake commented on [Tue Oct 10 2017](https://github.com/istio/old_pilot_repo/issues/1237#issuecomment-335481657)

subscribe

**Comment by ldemailly** [comment]
open a new issue if needed based on current data
