### ISSUE TITLE
Latest version went from 1.1.8 down to 1.0.8

### ISSUE THREAD

**Issue by roberthamel** [istio/istio#14843]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
We use a Bash command to determine the latest Istio version before executing the command from the documentation to download the latest version from the command line.

#### Command to fetch latest version from GitHub
`ISTIO_VERSION=$(curl -s https://api.github.com/repos/istio/istio/releases/latest | grep "tag_name" | cut -c 15- | tr -d \" | tr -d ,)`

#### Command to download latest version
`curl -L https://git.io/getLatestIstio | ISTIO_VERSION=${ISTIO_VERSION} sh -`

For some reason, latest version is currently 1.0.8. Previously it was one minor version higher: 1.1.8. This caused our automated deployment script to break because the instructions to install Istio CRD's differs (i.e. the folder structure was modified between versions).

Is this a mistake, or is there a different method I should use to determine the current highest stable Istio version?

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience

**Expected behavior**
Istio version is consistently marked as a version higher than previously released.

**Steps to reproduce the bug**
Try to follow current documentation to install Istio version marked as latest.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**
Command line with Helm

**Environment where bug was observed (cloud vendor, OS, etc)**
Linux based.

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
In a chronological sense, technically we release 1.0.8 after we released 1.1.8, although it is logically an older version. Unfortunately Github doesn't allow us to change the order of releases. We were concerned something like this would happen as a result of that but as far as I know there isn't much we can do about it.

**Comment by roberthamel** [comment]
Thanks for the reply. I will close this issue since has more to do with how GitHub handles current versions and, as you stated, technically 1.0.8 is the newest version. Not a big deal on our end since we can hardcode the version number, which provides a couple of advantages in itself.
