### ISSUE TITLE
ci/cd on circleci seems a little flakey

### ISSUE THREAD

**Issue by sdake** [istio/istio#14848]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

```
2019-06-14T15:41:06.600335Z	info	Logging initialized
2019-06-14T15:41:06.600409Z	info	Using temp dir /tmp/istio.e2e.896127008
2019-06-14T15:41:06.603561Z	info	Using release dir: /go/src/istio.io/istio
2019-06-14T15:41:06.603597Z	info	Fortio hub  tag  -> image fortio/fortio:latest
2019-06-14T15:41:06.603608Z	info	Starting Initialization
2019-06-14T15:41:06.603616Z	info	Setting up kubeInfo setupSkip=false
2019-06-14T15:41:06.603718Z	info	Running command kubectl create namespace istio-system --kubeconfig=
2019-06-14T15:41:06.711398Z	info	Command error: exit status 1
2019-06-14T15:41:06.711450Z	error	Unable to create namespace istio-system: command failed: "The connection to the server 10.142.4.249:8443 was refused - did you specify the right host or port?\n" exit status 1
```

It appears when `kubectl create` occurs and `kubeapi ` is not yet operational,` kubectl` is not retried and the gig is up.

**Affected product area (please put an X in all that apply)**

[X] Base Infrastructure
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[X] Test and Release
[ ] User Experience

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

https://circleci.com/gh/istio/istio/444091?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by douglas-reid** [comment]
can we update the issue description to include `(infrastructure issue)`? That will make it clear that the issue is not in the test logic itself.

**Comment by sdake** [comment]
@douglas-reid - ya, was going to suggest to @geeknoid to add an [Infrastructure Issue] to his bot.

**Comment by sdake** [comment]
@douglas-reid submitted request to @geeknoid in PR https://github.com/istio/istio/pull/14859 to add a `Base Infrastructure` area to the bot/github issue list/github bug template.

Cheers
-steve

**Comment by geeknoid** [comment]
We can easily extend the template to add a new category. Do we need a new label to go with it, or is area/test-and-release sufficient?

What should the template text be? Considering end-users can see this, is "Infrastructure" adequate and understandable? Or maybe "Istio Build and Release Infrastructure"?

**Comment by sdake** [comment]
I extended the template, but the text may not be correct.  I used `Base Infrastructure`.  I think `Infrastructure` might be better as base might be misconstrued to mean "the installer, the docs, or anything else:)".  I think a new label would be best, or a sublabel - for searching with zenhub.

Cheers
-steve

**Comment by sdake** [comment]
This appears to be a general problem with either the infrastructure or the test case implementation (the test cases should retry a few times and then give up IMO).  Here is a e2e_simple PR failure in circleci:

https://circleci.com/gh/istio/istio/444632?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
