### ISSUE TITLE
Epic: Ingress bugs

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1486]
@kyessenov commented on [Mon Oct 09 2017](https://github.com/istio/old_pilot_repo/issues/1414)

Context: [production readiness proposal and plan](https://goo.gl/pmjuYg)

The feature “_cluster ingress_” is identified as incomplete test coverage. As a measure to reach Istio production quality in 0.3, this issue is opened to track the progress of providing sufficient test coverage for the feature in question.

This issue is initially assigned to the working group leads.

**Recommendations**:
- Come up with a test plan for how the feature should be tested. Identify and document (in this issue, or a separate document this issue will link to) test cases and whether each will be covered by an integration test (with some level of mocking and/or starting up selected components in test environment), or end to end test (aka system test, which brings up the whole Istio to exercise the feature; currently live in the istio/istio repo).
- If you expect the test plan is complex and controversial, consider having it formally reviewed.
- State an ETA in the issue, and assign this to a developer who will execute the test plan.
- Execute the test plan as the highest priority for 0.3.
- For any bug or defect identified by the new test cases, file a new issue and link it from this one.
- Close this issue only when the test plan is completely executed, and all additional issues identified in step 3 are fixed.

If you see a risk of not fixing this issue by end of 0.3, please contact istio-production-quality@googlegroups.com as soon as possible. We will also periodically ping the issue for update.

---

@rshriram commented on [Fri Oct 13 2017](https://github.com/istio/old_pilot_repo/issues/1414#issuecomment-335968139)

https://github.com/istio/pilot/issues/730
https://github.com/istio/pilot/issues/484
https://github.com/istio/pilot/issues/533
https://github.com/istio/pilot/issues/731
https://github.com/istio/pilot/issues/805
https://github.com/istio/pilot/issues/926
https://github.com/istio/pilot/issues/969
https://github.com/istio/pilot/issues/1021
https://github.com/istio/pilot/issues/1389
https://github.com/istio/pilot/issues/1367
https://github.com/istio/pilot/issues/1234
https://github.com/istio/pilot/issues/1021
https://github.com/istio/istio/issues/1024
https://github.com/istio/pilot/issues/1478
https://github.com/istio/istio/issues/585

---

@rshriram commented on [Wed Oct 11 2017](https://github.com/istio/old_pilot_repo/issues/1414#issuecomment-335968630)

just FYI @smawson ^^^

---

@linsun commented on [Wed Oct 11 2017](https://github.com/istio/old_pilot_repo/issues/1414#issuecomment-336006466)

subscribe

**Comment by sakshigoel12** [comment]
@ZackButcher assigning this to you as you are the owner of Ingress on go/istio-schedule. please reassigng as appropriate if you are not working on this P0.

**Comment by rshriram** [comment]
This can be closed given that people seem to have happily adopted the gateway (See mailing list traffic). Gateway + VirtualService solves all the issues that ingress was facing.
