### ISSUE TITLE
Improve security perf tests

### ISSUE THREAD

**Issue by JimmyCYJ** [istio/istio#14899]
**Describe the feature request**

1. Make the helm values composable. Currently security perf tests use a separate values-istio-sds-auth.yaml file which is easy to get out of sync with the default values.yaml file. We need to provide a composable option to apply helm flag changes from values-istio-sds-auth.yaml to default values.yaml.

1. Add SDS for ingress gateway. Ingress SDS test is enabled in general perf test, but we are lacking of ingress SDS test in security perf tests.

1. Export test output to grafana instead of presenting on terminal. Currently the security perf test does not enable grafana, and prints success rate on terminal. Any unexpected power shutdown could easily break the test. 

1. Use a prober to periodically send request to prometheus server for stats (qps, 200 rate, CPU/memory usage in istio-system control plane, CPU/memory usage of workload sidecars, SDS push latency, SDS push failures, etc.). Currently there are four security perf tests running in four clusters, using a prober would help to get timely update on each test.
    - There is already a [tool](https://github.com/istio/tools/blob/master/bin/export_grafana_snapshot.py) to create a snapshot of grafana

1. We manually run security perf tests in istio/tools/perf/security to guard Istio release. We need to automate these perf tests to test against daily release.

    - Create CronJobs in GKE (https://cloud.google.com/kubernetes-engine/docs/how-to/cronjobs) to automatically run perf tests daily. 

    - Define a set of alerting rules at Prometheus config to fire alerts if any regression is detected. For example, an increase in 5xx, CPU and memory usage, or abnormal pod restarts. 

    - Use Prometheus AlertManager to notify us via Slack or Email if alert is fired.

https://github.com/istio/istio/issues/13439

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[X] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by howardjohn** [comment]
I would recommend syncing up with @therealmitchconnors and/or @utka who are doing similar work
