### ISSUE TITLE
circleci racing between ns create via cli and via aply

### ISSUE THREAD

**Issue by sdake** [istio/istio#14897]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
CirlceCI seems to think that a create followed by an apply is a problem.  This is not desireable in kubernetes.

What is strange is this is a new error.  See: https://circleci.com/gh/istio/istio/445769?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[X] Developer Infrastrcture

**Expected behavior**
test cases pass

**Steps to reproduce the bug**
run the gate a bunch of times

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
master

**How was Istio installed?**
by e2e-dashboard

**Environment where bug was observed (cloud vendor, OS, etc)**
circleci

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
Are you talking about

> Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply

I have seen this before a lot, even in my own usage. I think maybe when overriding mesh config, so maybe helm is making the config maps in a way that is different than apply? Not exactly sure.

**Comment by sdake** [comment]
That is one of the problems, but this one actually blocked circleci's check.

What occured in the gate was a 

kubectl create ns istio-system

followed by an apply of a makefile generated manifest.  The manifest "creates" an istio-system namespace via cat.  I am not sure how to create a namespace compatible with a further apply operation.  Once we sort out this problem, we can probably address it throughout the infrastructure and change all creates to be compatible with apply...

**Comment by howardjohn** [comment]
But what is the actual problem this causes? As far as I know, its just a warning message

Even our demo install steps run into this warning but I have never seen any problems from it:

```bash
$ k create namespace istio-system
namespace/istio-system created
$ kaf istio-demo.yaml
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
namespace/istio-system configured
```

My understanding is apply is idempotent so it shouldn't cause any issues. Is this not the case?

**Comment by sdake** [comment]
The circleci gate failed for some reason with this as the problem...

https://circleci.com/gh/istio/istio/445769?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification

I know we have removed circleci for the most part, but others may use it as part of their validation, and any of these types of warnings are sloppy.  If they can be fixed, they should be.  I don't personally know how to fix it or I'd have submitted a pr for it. (how does one apply a namespace??)

Cheers
-steve

**Comment by howardjohn** [comment]
You can apply a namespace with 

```
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    istio-injection: disabled
```

Which we do on the install.


The warning isn't the actual failure, circle is just bad at showing what the real error is.

If you look further down you can see the real error

```
2019-06-16T15:25:03.573988Z	info	Deployment rollout ends after [9m58.930059352s] with err [deployments/istio-egressgateway in namespace istio-system failed]
2019-06-16T15:25:03.573999Z	error	Failed to deploy Istio.
2019-06-16T15:25:03.574008Z	error	Failed to complete Init. Error deployments/istio-egressgateway in namespace istio-system failed
```

So I don't think there is anything we need to do here

**Comment by howardjohn** [comment]
I don't think this is a problem - feel free to reopen if you disagree @sdake
