### ISSUE TITLE
Istio retrying even though i havent configured retry

### ISSUE THREAD

**Issue by pc-rshetty** [istio/istio#14900]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

Ours a a financial application and we use Istio. We observed that Istio does a retry when the http request takes longer than 1 min and timeous. 
We are working on making this async but there are similar scenarios where istio retry doesnt makes sense. We would like to switch off the default retry. We use the ingress gateway.

**Affected product area (please put an X in all that apply)**

[ Y] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ Y] Networking
[ ] Performance and Scalability
[ Y] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ Y] User Experience
[ ] Developer Infrastrcture

**Expected behavior**
We would like to stop the retry. We will configure retry if we need it. Right now from documentation it is not clear how to switch off the retry.
**Steps to reproduce the bug**
Configure a http service and make it run for more than 1 min. The Istio will timeout and retry will get triggered. We tried adding timeout in virtual service but that doesnt seem to help
**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.0.7
**How was Istio installed?**
helm
**Environment where bug was observed (cloud vendor, OS, etc)**
EKS
Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
You should be able to configure with a virtual service. See https://istio.io/docs/reference/config/networking/v1alpha3/virtual-service/#HTTPRetry

**Comment by pc-rshetty** [comment]
@howardjohn i tried specifying following but that config gives me error
    retries:
      attempts: 0

**Comment by GregHanson** [comment]
@pc-rshetty can you provide the VirtualService and the corresponding error you got?  If I had to guess, this appears to be a bug in our validation logic.  Specifically in the validation webhook:
https://github.com/istio/istio/blob/master/pilot/pkg/model/validation.go#L2272
and how we attempt to detect whether to disable the default retries istio appends for each Route:
https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/route/retry/retry.go#L69

**Comment by pc-rshetty** [comment]
@GregHanson  this is how my original virtual service (in helm templates ) looks like 
`apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: pcb-service
  namespace: pcb-app
  labels:
    app.kubernetes.io/name: {{ include "pcb-service.name" . }}
    helm.sh/chart: {{ include "pcb-service.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}    
spec:
  hosts:
  - "*"
  gateways:
  - {{ .Values.istio.gateways.name }}
  http:
  - match:
    - uri:
        prefix: /pcb
    rewrite:
      uri: "/pcb"
    timeout: 120s
    route:
    - destination:
        host: {{ include "pcb-service.name" . }}
        port:
          number: {{ .Values.service.port }}

`

When i tried editing the config directly via kubeconfig it looks like this 

```
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: 2019-04-01T21:43:39Z
  generation: 1
  labels:
    app.kubernetes.io/instance: pcb-service
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: pcb-service
    helm.sh/chart: pcb-service-0.0.1
  name: pcb-service
  namespace: pcb-app
  resourceVersion: "22709537"
  selfLink: /apis/networking.istio.io/v1alpha3/namespaces/pcb-app/virtualservices/pcb-service
  uid: 35ec3081-54c7-11e9-ac8c-0635af468e42
spec:
  gateways:
  - pcapapigateway.default.svc.cluster.local
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /pcb
    rewrite:
      uri: /pcb
    route:
    - destination:
        host: pcb-service
        port:
          number: 8080
    timeout: 120s
    retries:
      attempts: 3
      perTryTimeout: 2s
      retryOn: gateway-error,connect-failure,refused-stream
```

I get this error 
unknown field "retryOn" in v1alpha3.HTTPRetry
You can run `kubectl replace -f /var/folders/2m/tz2q61b96ps2c1pq2ffhzzy8_lbw_w/T/kubectl-edit-r21js.yaml` to try this update again.

Notice that even for valid value of 3 i get the same errror as i get for 0

**Comment by pc-rshetty** [comment]
Also then i tied just specifying the retry 
    retries:
      attempts: 3

This works , but i am back to square 1 since when i give this 
    retries:
      attempts: 0

then i get this error 

error: virtualservices.networking.istio.io "pcb-service" could not be patched: admission webhook "pilot.validation.istio.io" denied the request: configuration is invalid: 1 error occurred:

* attempts must be positive

**Comment by pc-rshetty** [comment]
So seems like i have to give atleast 1 like this 
retries:
attempts: 1

But i dont want it to retry at all

**Comment by GregHanson** [comment]
@pc-rshetty yes, definitely a bug.  I submitted a PR here:
https://github.com/istio/istio/pull/14925

**Comment by howardjohn** [comment]
https://github.com/istio/istio/blob/d557ad36c9ad254355ff33e651e7de680fa5dc3f/pilot/pkg/networking/core/v1alpha3/route/retry/retry.go#L68-L71

looks like internally we support this but validation is too extreme

**Comment by GregHanson** [comment]
@pc-rshetty PR merged to master and release 1.2 branch.  The fix did not make it in time for the 1.2.0 release, but will be part of 1.2.1

**Comment by rinormaloku** [comment]
As of 1.7.2 setting the property attempt to 0 fails the validation when **Patching** i.e. `kubectl edit vs <vs>`

**Comment by GregHanson** [comment]
@rinormaloku what's the validation error message you are seeing when you try to edit your vs?  We allow retry fields `>=0`:
https://github.com/istio/istio/blob/master/pkg/config/validation/validation.go#L2148

Istio does have some validation logic that complains if `retries = 0` and some of the other HTTPRetry fields are set, is this what you are seeing?
https://github.com/istio/istio/blob/master/pkg/config/validation/validation.go#L2152

**Comment by rinormaloku** [comment]
@GregHanson  I am not sure if that is the line. But this is how you can reproduce it:
1. Create a VS.
2. Patch the VS, or kubectl edit and update retries to 0.
3. Save changes.

And you will get the error. If this ain't descriptive enough, I can set up a script to reproduce this issue. Let me know

**Comment by samucamarques** [comment]
I'm still facing this issue on Istio 1.7.4
Can someone help me?

**Comment by FeiYing9** [comment]
This issue still exist in Istio 1.9.2

**Comment by vivuu1989** [comment]
in 1.11.2 also facing the same issue. Any solution or workaround to disable the retry on 50e3 errors?

**Comment by vivuu1989** [comment]
I am not sure, whether we are talking about the smae issue.  I will try to explain the scenario which I am trying. I have 2 services appservice-A and  appservice-B, both are in the same namespace "mynamespace" and both have seperate Virtual service called VS-A and VS-B.
 

In MyAPPLICATION, there is a call from appservice-A to appservice-B , and I want to disable the retry when the ServiceB throwing a 503 error, and the ServiceA should not retry again.  So what I enabled is in the VS-B,  I added the retry-attempt to 0, by expecting that appservice-A wont retry an attempt if the appservice-B throws a 503 error.. Which is not working for me.

I performed a testing again with the sample again for you by making the attempt 0 in the VS-B. but still there is no change is happening to the retries, still showing 2.

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  name: appservice-B
  namespace: mynamespace
spec:
  gateways:
  - istio-system/ingress-gateway
  hosts:
  - appservice-B.mynamespace.svc.cluster.local
  - appservice-B.mycompany.com
  http:
  - match:
    - uri:
        prefix: /
    retries:
      attempts: 0
    route:
    - destination:
        host: appservice-B.mynamespace.svc.cluster.local
        port:
          number: 8080
        subset: v1
```

this is the  proxy config routing rule out put which generated from appservice-A

istioctl proxy-config route appservice-A-6dbb74bc88-dffb8 -n mynamespace -o json
```
                "routes": [
                    {
                        "name": "default",
                        "match": {
                            "prefix": "/"
                        },
                        "route": {
                            "cluster": "outbound|8080||appservice-B.mynamespace.svc.cluster.local",
                            "timeout": "0s",
                            "retryPolicy": {
                                "retryOn": "connect-failure,refused-stream,unavailable,cancelled,retriable-status-codes",
                                "numRetries": 2,
                                "retryHostPredicate": [
                                    {
                                        "name": "envoy.retry_host_predicates.previous_hosts"
                                    }
                                ],
                                "hostSelectionRetryMaxAttempts": "5",
                                "retriableStatusCodes": [
                                    503
                                ]
                            },
                            "maxStreamDuration": {
                                "maxStreamDuration": "0s",
                                "grpcTimeoutHeaderMax": "0s"
                            }
                        },
                        "decorator": {
                            "operation": "appservice-B.mynamespace.svc.cluster.local:8080/*"
                        }
                    }
                ],
                "includeRequestAttemptCount": true
```

So, According to your comment, I suspect that , whether I am trying right things for my scenario, If this also right, any workaround  like  Is there achange the property of status codes or headers  from responses to disable, so that istio wont retry appservice-B from appservice-A if a 503 errorcode got from appservice-B ?

**Comment by ramaraochavali** [comment]
Can you share complete config_dump?
