### ISSUE TITLE
Citadel should set audience field when making a TokenReview

### ISSUE THREAD

**Issue by mikedanese** [istio/istio#14913]
From looking at the code, istio is not using an audience binding with it's Kubernetes service account token authenticator:

https://github.com/istio/istio/blob/master/security/pkg/k8s/tokenreview/k8sauthn.go

Citadel should designate an audience for itself and use the audience binding capabilities of the TokenReview API. See the "audiences" field:

https://github.com/kubernetes/api/blob/1d1b8b084b3057162613acc6cba8af4e30dc2ec4/authentication/v1/types.go#L67-L73

**Comment by lei-tang** [comment]
@mikedanese @myidpt 
My understanding is that the k8s service account authenticated in https://github.com/istio/istio/blob/master/security/pkg/k8s/tokenreview/k8sauthn.go is the k8s service account on a workload pod, which does not have Citadel as audience. Thus, in this scenario, I am not sure Citadel can designate the audience as itself when invoking the TokenReview API.

**Comment by mikedanese** [comment]
Token request allows an audience to be specified:

https://github.com/kubernetes/kubernetes/blob/47459465254b840b16220a163540631e416b22c2/pkg/apis/authentication/types.go#L121-L127

Token review accepts an audience:

https://github.com/kubernetes/kubernetes/blob/47459465254b840b16220a163540631e416b22c2/pkg/apis/authentication/types.go#L59-L64

cc @wattli

**Comment by myidpt** [comment]
I think this field should be set with our recent work on enforcing the use of trustworthy JWTs by @pitlv2109 .

**Comment by pitlv2109** [comment]
@myidpt This just needs a few lines of code, but we need to bump the support to k8s 1.3.

**Comment by pitlv2109** [comment]
This is already done. Close.
