### ISSUE TITLE
Pilot exposes metric pilot_virt_services but never sets it

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#14932]
Pilot has a metric `pilot_virt_services`, but it is never actually set. This is also in the dashboard so it is misleading.

I am fine with not having it if it isn't feasible due to some code changes or something, but we should remove it from the dashboard if that is the case.

**Comment by c0d1ngm0nk3y** [comment]
Is there any downside in just reporting the number of virtual services known? For which gateway? The metric name does not say anything about that. I have used ISTIO_MESH_GATEWAY for now since it can be done with the existing code of the `pushContext`.

Any thoughts?
