### ISSUE TITLE
Expand edge case coverage with fuzz testing

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#14935]
Right now we do not have any fuzz testing. There are a lot of areas this could help us with. For example, we have had many bugs of pilot generating invalid config. We can probably catch many of these with fuzzing.

I have started some [basic fuzzing](https://github.com/howardjohn/istio/commit/c98fe6605fbf18dd54cfb4aa4f3847f89b991af6) and found issues, so it seems promising:
* https://github.com/istio/istio/pull/14910
* https://github.com/gogo/protobuf/issues/579

Ideally we would could have something that generates a bunch of random config (VS, SE, Gateways, etc) and feeds it to pilot to test generation of XDS responses. There are probably other areas where this is useful as well.

Most fuzzing is done by defining a function of `bytes -> pass/fail`, which makes this a bit hard. Envoy uses https://github.com/google/libprotobuf-mutator#integrating-with-libfuzzer which allows generating protobuf much easier, but we will need an alternative approach as I believe this only works for C. 

https://github.com/dvyukov/go-fuzz seems to be the defacto standard for Go fuzzing and seems pretty solid. It looks like there is some work to integrate this with oss-fuzz at https://github.com/google/oss-fuzz/pull/2188 which would be ideal.

Areas to fuzz:

- [ ] All CRD validation
- [ ] All XDS response generation
- [ ] ... TODO ...

Problems to solve:
- [ ] How do we reliably translate raw bytes to many protos. https://github.com/dvyukov/go-fuzz/issues/251 has some tips on how not to do it at least.
- [ ] Where do we run it? oss-fuzz is probably ideal if possible
- [ ] Can we use libprotobuf-mutator if we use https://github.com/dvyukov/go-fuzz#libfuzzer-support?

**Comment by howardjohn** [comment]
Also, I explored https://github.com/google/gofuzz a bit. This is nowhere near as good as go-fuzz. go-fuzz is doing coverage guided fuzzing, so it will generate new inputs to try to gain more coverage. gofuzz is just generating random stuff and will never generate a valid config

**Comment by howardjohn** [comment]
Example of oss-fuzz (may have to login with google, but I think everyone has access): https://oss-fuzz.com/testcases?open=yes&project=envoy

**Comment by howardjohn** [comment]
Basically the scope of this task would be just getting the basics off fuzzing set up and running. Actually adding fuzz tests for various scenarios can be added once we have this

**Comment by sushicw** [comment]
Another use-case for this: with fuzzed / generated resources, we can do performance testing at various scales. (e.g. https://github.com/istio/istio/issues/18008 is in the context of analysis).

**Comment by howardjohn** [comment]
could utilize https://github.com/munnerz/crd-schema-fuzz/blob/master/fuzz.go#L39

**Comment by howardjohn** [comment]
This would have caught the pruning bugs we say @jasonwzm

**Comment by AdamKorcz** [comment]
I am just chiming in here to let everyone in this thread know that 2 fuzzers have been added by way of go-fuzz which is supported by OSS-fuzz: https://github.com/istio/istio/pull/29295 and the integration with OSS-fuzz is set up here: https://github.com/google/oss-fuzz/pull/4762

**Comment by howardjohn** [comment]
Not stale

**Comment by howardjohn** [comment]
We have made a ton of progress here in tests/fuzz. We can continue to improve but I think we can consider this done.
