### ISSUE TITLE
Source-code and os-specific assets of the same release contains different helm charts

### ISSUE THREAD

**Issue by thomschke** [istio/istio#14947]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
The source code assets and the os-specific assets of the same release contains different helm charts.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastrcture

**Expected behavior**
All assets of the same release should contain identical helm charts.

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
I am not sure what you mean by this. I downloaded 1.2rc3 in windows and linux variants and they are identical (except istioctl, as expected):
```
$ diff -r win linux
Only in linux/bin: istioctl
Only in win/bin: istioctl.exe
```

**Comment by thomschke** [comment]
Hi @howardjohn, please make a diff (./install/kubernetes/helm) between any os-specific asset (win, linux, osx) and any source-code asset (contains helm charts too).

**Comment by howardjohn** [comment]
Oh I see what you mean.

I thought you meant https://github.com/istio/istio/releases/download/1.2.0-rc.3/istio-1.2.0-rc.3-linux.tar.gz vs https://github.com/istio/istio/releases/download/1.2.0-rc.3/istio-1.2.0-rc.3-osx.tar.gz.

You mean https://github.com/istio/istio/releases/download/1.2.0-rc.3/istio-1.2.0-rc.3-linux.tar.gz vs https://github.com/istio/istio/archive/1.2.0-rc.3.tar.gz.


The source code is NOT the release. We do post-processing in the release. Please follow the instructions at https://istio.io/docs/setup/kubernetes/download/.

I wish we could turn off the "source code" section, but its added by github and we cannot

**Comment by thomschke** [comment]
All right :-)
