### ISSUE TITLE
circleci test AND `make test` fail for installer because of `presubmit` label

### ISSUE THREAD

**Issue by c0d1ngm0nk3y** [istio/istio#14949]
See [circleci and build icons](https://github.com/istio/installer/blob/master/README.md)

**Bug description**

Both the circleci tests and the build (`make test`) fail for the installer. For quite some time.

```
Error during test framework init: unknown label name: "presubmit"
```

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[X] Test and Release
[ ] User Experience
[X] Developer Infrastrcture

**Expected behavior**
A working CI and at least some basic validation like `make test` should work.

**Steps to reproduce the bug**
Call `make test` in the installer repo.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
n/a

**How was Istio installed?**
n/a

**Environment where bug was observed (cloud vendor, OS, etc)**
n/a

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by c0d1ngm0nk3y** [comment]
It looks like a `Presubmit` value is missing in `pkg/test/framework/label/labels.go`. But *where* is this label set and *why* has this not been noticed?

@ozevren Do you have some insights for me?

**Comment by c0d1ngm0nk3y** [comment]
This commit could be related :) https://github.com/istio/istio/commit/70523617e92f1b8a640fbb5349c00790aba939cd

**Comment by ozevren** [comment]
I removed the label since it is not needed/used anymore.

**Comment by c0d1ngm0nk3y** [comment]
@ozevren The tests of the installer think otherwise :) ([link](https://buildkite.com/istio/istio-installer/builds/557#7e765be0-de10-4498-8344-434b8d882473/14-9600)) Any idea way it is still used there?

**Comment by ozevren** [comment]
I don't know how istio/installer is syncing PRs/code from istio/istio. It looks like the updates done to the makefiles (particularly tests/integration/tests.mk) in istio/istio is not reflected properly.

```
istio.io/istio/tests/integration/security/util/connection istio.io/istio/tests/integration/security/util/secret --istio.test.select -customsetup,+presubmit
```

**Comment by phil9909** [comment]
#237 fixed this problem (`make test` is still failing, but for another reason).
