### ISSUE TITLE
Istio not stable after cluster restart

### ISSUE THREAD

**Issue by bkrahmer** [istio/istio#14941]
I have an OpenShift 3.11 cluster which is shut down each evening.  When I start it back up again in the morning to work with it, istio is often unstable.  I believe OpenShift is using the docker pause at shutdown, and resuming them at restart, because my pod names are consistent across the restarts.

I have a script that looks for not-fully-healthy pods in all namespaces, and over 25 minutes after startup today, I saw these:
```
istio-system                        istio-ingressgateway-6854fc7467-87xx6          0/1       Running            1          18h
istio-system                        istio-telemetry-c7ffd7847-wgg2m                1/2       CrashLoopBackOff   13         18h
istio-system                        jaeger-collector-576b66f88c-k28ff              0/1       CrashLoopBackOff   11         18h
istio-system                        jaeger-query-7549b87c55-hct6k                  0/1       CrashLoopBackOff   11         18h
kube-service-catalog                apiserver-4mzw8                                0/1       CrashLoopBackOff   11         19h
openshift-infra                     hawkular-metrics-schema-mk25j                  0/1       Completed          0          19h
openshift-logging                   logging-fluentd-jjx2j                          0/1       CrashLoopBackOff   10         19h
operator-lifecycle-manager          olm-operator-787d9ff9b-2lx6d                   0/1       CrashLoopBackOff   10         19h
```
I deleted all of those pods, and all of their replacements seemed to come up healthy.  However, I could still not deploy an application.  This was due to "Warning	FailedRetry		4m			deployer-controller		Stop retrying: couldn't create deployer pod for "development/jdbc-example-10": Internal error occurred: failed calling admission webhook "sidecar-injector.istio.io": Post https://istio-sidecar-injector.istio-system.svc:443/inject?timeout=30s: dial tcp 172.30.209.149:443: connect: no route to host"

I checked the logs of istio-sidecar-injector, and saw this repeated about 1x per second: "error	istio.io/istio/pilot/pkg/kube/inject/config.go:64: Failed to list *v1beta1.MutatingWebhookConfiguration: Get https://172.30.0.1:443/apis/admissionregi
stration.k8s.io/v1beta1/mutatingwebhookconfigurations?fieldSelector=metadata.name%3Dsidecar-injector.istio.io&limit=500&resourceVersion=0: dial tcp 172.30.0.1:443: connect: network is unreac
hable"

I killed that pod, restarted my deployment, and everything worked.  The bug in the sidecar injector seems to be pretty serious, as it doesn't update its state to reflect changes in the environment.

Istio TP10 

$ istioctl version --remote
client version: version.BuildInfo{Version:"1.1.6", GitRevision:"04850e14d38a69a38c16c800e237b1108056513e", User:"root", Host:"1844d064-72cc-11e9-a0d5-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.5-11-g04850e1"}
citadel version: version.BuildInfo{Version:"0.10.0-1", GitRevision:"a998810d2048a4c4acf206613f9c789a0df7a5aa", User:"redhat", Host:"redhat", GolangVersion:"go1.11.4", DockerHub:"brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/openshift-istio-tech-preview", BuildStatus:"Clean", GitTag:"unknown"}
egressgateway version: version.BuildInfo{Version:"0.10.0-1", GitRevision:"4408997686d86a157f006403acfd46508d166f8c", User:"redhat", Host:"redhat", GolangVersion:"go1.11.4", DockerHub:"brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/openshift-istio-tech-preview", BuildStatus:"Clean", GitTag:"unknown"}
galley version: version.BuildInfo{Version:"0.10.0-1", GitRevision:"a998810d2048a4c4acf206613f9c789a0df7a5aa", User:"redhat", Host:"redhat", GolangVersion:"go1.11.4", DockerHub:"brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/openshift-istio-tech-preview", BuildStatus:"Clean", GitTag:"unknown"}
ingressgateway version: version.BuildInfo{Version:"0.10.0-1", GitRevision:"4408997686d86a157f006403acfd46508d166f8c", User:"redhat", Host:"redhat", GolangVersion:"go1.11.4", DockerHub:"brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/openshift-istio-tech-preview", BuildStatus:"Clean", GitTag:"unknown"}
pilot version: version.BuildInfo{Version:"0.10.0-1", GitRevision:"a998810d2048a4c4acf206613f9c789a0df7a5aa", User:"redhat", Host:"redhat", GolangVersion:"go1.11.4", DockerHub:"brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/openshift-istio-tech-preview", BuildStatus:"Clean", GitTag:"unknown"}
policy version: version.BuildInfo{Version:"0.10.0-1", GitRevision:"a998810d2048a4c4acf206613f9c789a0df7a5aa", User:"redhat", Host:"redhat", GolangVersion:"go1.11.4", DockerHub:"brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/openshift-istio-tech-preview", BuildStatus:"Clean", GitTag:"unknown"}
sidecar-injector version: version.BuildInfo{Version:"0.10.0-1", GitRevision:"a998810d2048a4c4acf206613f9c789a0df7a5aa", User:"redhat", Host:"redhat", GolangVersion:"go1.11.4", DockerHub:"brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/openshift-istio-tech-preview", BuildStatus:"Clean", GitTag:"unknown"}
telemetry version: version.BuildInfo{Version:"0.10.0-1", GitRevision:"a998810d2048a4c4acf206613f9c789a0df7a5aa", User:"redhat", Host:"redhat", GolangVersion:"go1.11.4", DockerHub:"brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/openshift-istio-tech-preview", BuildStatus:"Clean", GitTag:"unknown"}

$ oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://loadbalancer.d9a0.xxx.com:443
openshift v3.11.59
kubernetes v1.11.0+d4cacc0

**Comment by howardjohn** [comment]
Sounds more like it my be a bug in your Kubernetes set up: `172.30.0.1:443: connect: network is unreachable`. I assume that IP is your apiserver which from your logs seems to be crash looping? Once you fix the apiserver I suspect Istio will start working as well (or at least work a bit better)

**Comment by bkrahmer** [comment]
I had already killed the apiserver pod and it was replaced with a healthy one several minutes before I had to diagnose the issue.  So when I restarted the sidecar injector and it started working again immediately. I believe that speaks against your comment.

**Comment by howardjohn** [comment]
Was the `172.30.0.1:443: connect: network is unreachable` log after you fixed the apiserver?

If you try to reach 172.30.0.1:443 from a different pod does it work?

I saw in the logs `istio.io/istio/pilot/pkg/kube/inject/config.go` is specified as the source, but this file doesn't exist in Istio 1.0, 1.1, or 1.2. What is Istio "TP10"?

**Comment by bkrahmer** [comment]
Yes, it continued to report the error even after restarting the apiserver, which is why I filed this bug.  I didn't do any further diagnosis since restarting the injector fixed it.  TP10 refers to Red Hat Service Mesh tech preview 10, which is downstream, and I think contains istio 1.1.2

**Comment by hzxuzhonghu** [comment]
> I believe OpenShift is using the docker pause at shutdown, and resuming them at restart

I think the network issue mostly related with this, `network is unreachable` indicates the network is not ready yet.

**Comment by bkrahmer** [comment]
I don't disagree that it may be a transient network problem due to things starting up, but in order to have a resilient platform, I expect  services to retry a number of times, and kill themselves after some time if necessary

**Comment by hzxuzhonghu** [comment]
We can do this kind of enhancement, though in k8s cluster container will be restarted after exit.

**Comment by howardjohn** [comment]
The code that is failing isn't even part of Istio, its a custom Red Hat modification. I agree it should probably retry but I am not sure what we can do here since it is not a part of Istio.

**Comment by bkrahmer** [comment]
Ok, thanks for investigating.  I will report it against Red Hat Service Mesh.

**Comment by knrc** [comment]
@howardjohn We haven't made changes to the Istio codebase in this area so it's hard to see how this is due to any Red Hat modifications, we can investigate however.

**Comment by howardjohn** [comment]
@knrc this is where the error is coming from https://github.com/Maistra/istio/blob/maistra-0.12/pilot/pkg/kube/inject/config.go which doesn't seem to be in Istio's codebase

**Comment by knrc** [comment]
@howardjohn Gotcha, although that's 99.9% taken from the galley codebase.

We're trying to get access to the system where this is occurring so we can track the issue down.
