### ISSUE TITLE
Integration test framework depends on testdata causing test failures when using go modules

### ISSUE THREAD

**Issue by PhilipGough** [istio/istio#14945]
**Bug description**
I will start by saying I don't have a full understanding of go modules internals as of yet so apologies if this is a non-issue or there is a simple workaround.

I am using the integration test framework in istio 1.1.7 in an OOP adapter.
However when I migrate my code to use go modules, the integration tests begin to fail.

My understanding is that go modules strips all non `.go` files from the projects dependencies. 
The integration test framework depends on yaml config here, loaded from relative path https://github.com/istio/istio/blob/1.1.7/mixer/pkg/adapter/test/integration.go#L347-L359 causing test failures.

Do you have any suggestions to workaround this or am I overlooking something/ missing an obvious workaround?

I guess we could embed the content directly in the go code but not sure this is an ideal solution.

**Comment by howardjohn** [comment]
With dep there was a setting like `keep non go code`, but I am not sure if there is a way to do that with `go mod`. @kyessenov may be able to help here

**Comment by PhilipGough** [comment]
@howardjohn yeah, with dep that was possible to set not to prune specific directories etc and non-go go. Haven't been able to achieve this so far with `go mod`

**Comment by kyessenov** [comment]
`go mod` does not preserve non-go files in a dependency by design.
I think we should embed the tests into go files using `bindata` and then follow something like https://github.com/golang/go/wiki/Modules#how-can-i-track-tool-dependencies-for-a-module to include them in the build.

**Comment by PhilipGough** [comment]
@kyessenov great thanks for clarifying. Can workaround this for now and will try to take a look at this myself if time allows.
