### ISSUE TITLE
Add Istio repo to helmhub

### ISSUE THREAD

**Issue by jdfalk** [istio/istio#14951]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Helm hub is an aggregation of other helm chart repos that does not require the chart to be published to the helm repo allowing Istio to update the charts independently yet still benefit from having Istio automatically included in helm. Having one central place that helm automatically looks at is extremely helpful in reducing friction when deploying istio. 

See: https://github.com/helm/hub/blob/master/Repositories.md

**Describe alternatives you've considered**
N/A
**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Additional context**
https://github.com/helm/hub/blob/master/README.md

**Comment by linsun** [comment]
is this only useful when helm install is used?  We are moving to use more helm template instead.

**Comment by wxdao** [comment]
> is this only useful when helm install is used? We are moving to use more helm template instead.

Really? I've been thinking helm install is a more complete way to setup. I find helm template really bad at switching on and off different components, switching off especially. If it's tiller that makes helm install upsetting, since v3 helm does get rid of it.

**Comment by jdfalk** [comment]
We prefer helm install as we automate it via flux. Right now it's a bit of a mess, as your charts repo is for some reason `https://storage.googleapis.com/istio-release/releases/1.2.1/charts/` instead of `https://storage.googleapis.com/istio-release/releases/charts/` which should hold all of the releases  like other helm repos. Yes there is an index.yaml in `https://storage.googleapis.com/istio-release/releases/charts/` but it doesn't contain all releases.

**Comment by sdake** [comment]
I have filed several issues on this.  Th

> We prefer helm install as we automate it via flux. Right now it's a bit of a mess, as your charts repo is for some reason `https://storage.googleapis.com/istio-release/releases/1.2.1/charts/` instead of `https://storage.googleapis.com/istio-release/releases/charts/` which should hold all of the releases like other helm repos. Yes there is an index.yaml in `https://storage.googleapis.com/istio-release/releases/charts/` but it doesn't contain all releases.

Your issue is being tracked here: https://github.com/istio/istio/issues/15498

**Comment by howardjohn** [comment]
We do not yet follow the best practices required to be added

* Every chart to have a maintainer listed along with valid contact information for each maintainer. The contact information could be in the form of an email address or link to a contact form
* Charts to pass Helm lint, be installable and upgradable in all community supported versions of Kubernetes, and to use semantic versioning to share intent in released changes. To help with this we suggest leveraging the Chart Testing project.


Along with #15498

**Comment by koalalorenzo** [comment]
Similar to: #25467 and #29222
