### ISSUE TITLE
Deploy broker into Istio core and add integration tests

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1495]
@xiaolanz commented on [Tue Oct 03 2017](https://github.com/istio/old_broker_repo/issues/35)

**Comment by andraxylia** [comment]
Is this still the plan?

**Comment by xiaolanz** [comment]
broker work is paused but we may restart anytime.

**Comment by andraxylia** [comment]
Let"s close this then, it may not be relevant later.
