### ISSUE TITLE
Add support for expr

### ISSUE THREAD

**Issue by antonmedv** [istio/istio#14967]
Please, add support for expressions via [expr](https://github.com/antonmedv/expr) evaluator. 

- [x] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

Currently it's fastest:

```
Benchmark_expr-8                50000000               274 ns/op
Benchmark_celgo-8               30000000               425 ns/op
Benchmark_govaluate-8           30000000               464 ns/op
Benchmark_goja-8                30000000               472 ns/op
Benchmark_bexpr-8               20000000               998 ns/op
Benchmark_otto-8                10000000              1279 ns/op
Benchmark_gval-8                 1000000             10491 ns/op
```

**Comment by kyessenov** [comment]
@antonmedv does expr support C++ or WASM runtimes? We're looking to move expression evaluation into Envoy proxy (C++ code with a potential for an embedded WASM runtime).

**Comment by antonmedv** [comment]
Currently only go runtime is supposed, but if your are interesting in WASM support I can work on it. Since expr compiling expressions to bytecode, expr can compile expressions directly into WASM. 
Let me know what you think.

**Comment by kyessenov** [comment]
@antonmedv Given we are not sure our WASM satisfies the performance requirement, we're hedging with C++ runtime. CEL does provide a C++ runtime, which makes it the obvious candidate.

If you are interested in building a WASM runtime, please consider the problem of retrieving the environment information from the host. We are also trying to develop a WASM API to read host information in https://github.com/envoyproxy/envoy-wasm/issues/42, as part of the WASM-host interface.

**Comment by antonmedv** [comment]
Okay I see, thanks.
