### ISSUE TITLE
Improve eng.istio.io

### ISSUE THREAD

**Issue by venilnoronha** [istio/istio#14966]
I noticed the following issues with [eng.istio.io](http://eng.istio.io/).

* Menu options not visible on mobile browsers (Safari)
* Failed page loads (e.g. /maintainers)
* Slow page loads (e.g. /members)
* Unsecured domain (currently http not https)

/cc @geeknoid

**Comment by howardjohn** [comment]
I see the issues as well (didn't test mobile safari though)

**Comment by venilnoronha** [comment]
The issue exists on mobile Chrome as well.

**Comment by geeknoid** [comment]
You can connect with https: too, at least I do with Chrome. Not sure how to turn off http:, I'll see if there's an option for that somewhere.

As for the latency, well, yeah, this is still very preliminary. It'll get better.

**Comment by venilnoronha** [comment]
Should we redirect http to https then?

**Comment by geeknoid** [comment]
These are all addressed I think.
