### ISSUE TITLE
Helm template on istio 1.2.0 produces duplicate CRDs

### ISSUE THREAD

**Issue by Stono** [istio/istio#14976]
Hi, 
We still use the slightly old method of doing `helm template` on the istio repos to generate manifests into an `istio-auth.yaml`.

The result had multiple `sidecars.networking.istio.io` CRD's with slightly different specs.

[istio-auth.yaml.tar.gz](https://github.com/istio/istio/files/3305066/istio-auth.yaml.tar.gz)

**Comment by howardjohn** [comment]
I see this as well.

One has 
```
      annotations:
        "helm.sh/resource-policy": keep
```

**Comment by sdake** [comment]
This was a merge error from a forward port that occured in d93e9eb8.  This (hopefully) wont occur again with our new master-first policy.

In the meantime, I'll fix the duplicate CRD problem.

Cheers
-steve

**Comment by linsun** [comment]
Thanks, i saw this prob in istio-demo.yaml and istio-demo-auth.yaml as well, I will look into it.

**Comment by sdake** [comment]
note this wasn't "my" forward port error, it was "by" a forward port error. :)
