### ISSUE TITLE
Install istio-cni in namespace istio-system failed according to the documentation

### ISSUE THREAD

**Issue by waret** [istio/istio#14977]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
Following the document [https://istio.io/docs/setup/kubernetes/additional-setup/cni/](https://istio.io/docs/setup/kubernetes/additional-setup/cni/), I installed istio-cni in namespace istio-system, but no pod was started. 
```
helm template install/kubernetes/helm/istio-cni --name=istio-cni --namespace=istio-system | kubectl apply -f -
```

When I check details of daemonset istio-cni-node, the result is as follows:
```
# kubectl describe daemonsets. istio-cni-node
Name:           istio-cni-node
Selector:       k8s-app=istio-cni-node
......
Events:
  Type     Reason        Age                    From                  Message
  ----     ------        ----                   ----                  -------
  Warning  FailedCreate  5m54s (x12 over 6m4s)  daemonset-controller  Error creating: pods "istio-cni-node-" is forbidden: pods with system-node-critical priorityClass is not permitted in istio-system namespace
```

**Affected product area (please put an X in all that apply)**
[ ] Configuration Infrastructure
[x] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastrcture

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
istio-1.2.0

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by linsun** [comment]
@tiswanso @rlenglet can you check this out?

**Comment by linsun** [comment]
@waret did you follow instruction to give sufficient permission to istio cni? saw this error from ur log:

```pods with system-node-critical priorityClass is not permitted in istio-system namespace```

**Comment by rlenglet** [comment]
@waret Could you please try to create `istio-cni` in namespace `kube-system` instead, and confirm it works?

**Comment by rlenglet** [comment]
Related to https://github.com/kubernetes/kubernetes/pull/65593.
