### ISSUE TITLE
Is there any way to identify internal - incoming traffic without envoy on kiali

### ISSUE THREAD

**Issue by maxh8086** [istio/istio#14980]
Hello,

i have implemented scenario of mtls migration where i am trying to send traffic from sleep.legacy to httpbin.foo while using permissive mode, kiali shows traffic from unknown source. 

1. is there any way that we could actually identify traffic source?

while setting  strict mode, it reject traffic as expected,

2. since traffic source is unknown (from internal cluster and being not part of mesh) it wont shows up rejected traffic either. 

https://istio.io/docs/tasks/security/mtls-migration/

**Comment by linsun** [comment]
cc @jmazzitelli @knrc to comment.  This may not be possible given there is no envoy on client side but I'd assume you can see the services in the mesh at the minimum.
