### ISSUE TITLE
Allow for configuring TERMINATION_DRAIN_DURATION_SECONDS in Helm

### ISSUE THREAD

**Issue by nicktrav** [istio/istio#14988]
**Describe the feature request**

When working around issues related to Envoy shutting down before its counterpart container, we discovered that Pilot has the [`TERMINATION_DRAIN_DURATION_SECONDS` environment variable](https://github.com/istio/istio/blob/1e062cf7108d254d929be8d22561f5856ddab9b8/pkg/features/pilot/pilot.go#L107) that allows for configuring the amount of time that the pilot-agent allows for Envoy to drain existing connections before gracefully exiting.

Suggestion: Allow for the `TERMINATION_DRAIN_DURATION_SECONDS` environment variable to be set and tuned in the Helm chart.

_Note that I am not proposing this as a means for solving the shutdown ordering problem, just that it seems like a useful configuration parameter to be able to play with._

**Describe alternatives you've considered**

Lightly forking the Helm chart to expose a means of passing the drain duration in the values.yaml files. This works well for us now, but we'd love to upstream this change. Happy to send a patch.

**Affected product area (please put an X in all that apply)**

[X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

Related to #7136.

**Comment by costinm** [comment]
We already support 
pilot:
  env:
    key: val

This works for all env variables - the current model is to treat this as 'escape hatch', and if there is 
broad use we can add it as a proper API in mesh config or Sidecar/networking proper API. 

In this case - it doesn't feel like a good candidate for a global setting, but something that should
be adjustable per workload, so an annotation or sidecar API would be better long term future than 
a helm setting.
