### ISSUE TITLE
Cache invalidation not working for host header

### ISSUE THREAD

**Issue by costinm** [istio/istio#1499]
1. Created an ingress resource, with a "host" option 

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: httpbin
  namespace: istio-test
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
  - host: httpbin.release02.istio.webinf.info
    http:
      paths:
      - path: /.*
        backend:
          serviceName: httpbin
          servicePort: 8000

2. Deploy 

3.  curl -v  $INGRES_IP -H Host:httpbin.release02.istio.webinf.info

4. Modify the host header to 'httpbin.weekly.istio.webinf.info'

5. The old name still works, new name doesn't.
 curl -v  $INGRES_IP -H Host:httpbin.weekly.istio.webinf.info

Verified that kubecl get ingress ... shows the new domain name,

You can try it - I've set the DNS name, cluster is 'weekly' under istio-testing project.

Fails:
curl -v  httpbin.weekly.istio.webinf.info
Works: 
curl -v  httpbin.weekly.istio.webinf.info -H Host:httpbin.release02.istio.webinf.info

Also the pilot routes are old:
curl -v $PILOT/v1/routes/80/istio-proxy/ingress~~istio-ingress-4019532693-q4g32.istio-system~istio-system.svc.cluster.local
...
 "httpbin.release02.istio.webinf.info"
...

**Comment by louiscryan** [comment]
Is this completely stale or known to still be an issue ?

If its still relevant @GregHanson can you assign it an appropriate priority & milestone in Zenhub
