### ISSUE TITLE
operator: ability to configure mixer policy check enabled or disabled

### ISSUE THREAD

**Issue by linsun** [istio/istio#15026]
@ostromart @rcernich looking at the operator spec, I don't see a way to tune the following common configs.  (other than do it via baseSpecPath yaml file).

- mixer policy check on or off
- trace sampling configuration

**Comment by linsun** [comment]
cc @sdake - should we propose new APIs for this?

**Comment by sdake** [comment]
@linsunall changes to the API of install happen in the API protobufs which are mislocated at present in theoperator repo (they belong in istio.io/api).  This doc describes  the protobufs:

https://docs.google.com/document/d/1xVhtDK0nMGqVVe9HaDi1zzIasOQHq42SCz8Q79AihJs/edit

**Comment by linsun** [comment]
Even with this doc, it is not obvious to me how to disable mixer policy but keep telemetry on.

@ostromart @sdake would appreciate some example if I missed it. probably good to have the example in GitHub.

**Comment by linsun** [comment]
cc @morvencao @clyang82 @sdake - this is needed for us to consume the operator work.

**Comment by richardwxn** [comment]
@linsun I think the example is listed here for how to do feature and component enablement override? https://github.com/istio/operator#new-api-customization

**Comment by morvencao** [comment]
We have migrated the [basic profiles](https://github.com/istio/operator/tree/master/data/profiles) to operator, which are good starting point for end user to customize their installation, some examples are shown at: https://github.com/istio/operator#new-api-customization, maybe we can add the complete relationship between feature and component.

**Comment by linsun** [comment]
Thank you @richardwxn @morvencao!  @ostromart and I chatted offline and he confirmed that trace sampling is only configurable via helm API.

I did find how Istio-policy can be enabled/disabled, via 

```
  policy:
    components:
      namespace: istio-policy
```

This is something user can do in addition to specify https://github.com/istio/operator/blob/master/pkg/apis/istio/v1alpha2/istiocontrolplane_types.proto#L228.
