### ISSUE TITLE
Pilot loads initial mesh config directly from K8s ConfigMap

### ISSUE THREAD

**Issue by dgn** [istio/istio#15024]
**Bug description**
When a MeshConfig file is not found or could not be loaded, Pilot resorts to reading from the 'istio' ConfigMap directly (in case we're on Kubernetes). It doesn't do this for the MeshNetworks- here, it only tries to load from a file and uses a default configuration if that's not possible.

My understanding is that Pilot should not be directly dependent on Kubernetes in the future so I think it should only try to read the MeshConfig from a file (which on Kubernetes will be the mounted ConfigMap anyway). I understand there are still a lot of places where Pilot uses K8s directly but this seems like an instance where it could be easily removed.

Am I missing something here? Is this code path used for testing purposes (codecov looks like it's not)?

**Affected product area (please put an X in all that apply)**

[x] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastrcture

**Expected behavior**
Pilot never polls the Kubernetes API to load the ConfigMap but only reads the MeshConfig from a file.

**Steps to reproduce the bug**
reading code (see [`pilot/pkg/bootstrap/server.go:408`](https://github.com/istio/istio/blob/59b2c7e376779482006efbaf545f28604a57f081/pilot/pkg/bootstrap/server.go#L408))

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
current master (commit 59b2c7e376779482006efbaf545f28604a57f081)

**Comment by howardjohn** [comment]
Seems reasonable, not sure why we directly read the configmap

**Comment by howardjohn** [comment]
Still reasonable to remove this if we haven't already
