### ISSUE TITLE
vault.TestClientOnExampleHttpVaultCA failing on presubmit

### ISSUE THREAD

**Issue by pitlv2109** [istio/istio#15034]
https://prow.k8s.io/view/gcs/istio-prow/pr-logs/directory/istio-unit-tests/25193
https://prow.k8s.io/view/gcs/istio-prow/pr-logs/directory/istio-unit-tests/25195
https://prow.k8s.io/view/gcs/istio-prow/pr-logs/directory/istio-unit-tests/25196

Looks like this endpoint `35.233.249.249:8200` is not ready. Tests were timed out.

**Comment by howardjohn** [comment]
I thought this test got move to a unit test?

**Comment by lei-tang** [comment]
Yes, this test got moved to an integration test: https://github.com/istio/istio/pull/13684.
The following links in the issue description are for the PR https://github.com/istio/istio/pull/15007, which is for on a branch called "authz-v2". I am not sure the code and test status of the branch "authz-v2" and how such branches should be maintained.
https://prow.k8s.io/view/gcs/istio-prow/pr-logs/directory/istio-unit-tests/25193
https://prow.k8s.io/view/gcs/istio-prow/pr-logs/directory/istio-unit-tests/25195
https://prow.k8s.io/view/gcs/istio-prow/pr-logs/directory/istio-unit-tests/25196

**Comment by pitlv2109** [comment]
@lei-tang Feel free to close this if it fails on `authz-v2`, since that branch won't be used anymore.

**Comment by lei-tang** [comment]
The issue is closed since the branch authz-v2 won't be used anymore.
