### ISSUE TITLE
Pilot-agent to implement a quitquitquit endpoint like envoy

### ISSUE THREAD

**Issue by Stono** [istio/istio#15041]
**Describe the feature request**
It would be great if `pilot-agent` implemented a `quitquitquit` endpoint like envoy does.  This would enable us to programatically kill pilot-agent from other containers in the same pod, for example - at the end of a [CronJob](https://github.com/istio/istio/issues/11659), or using a tool like https://github.com/monzo/envoy-preflight.

**Describe alternatives you've considered**
At the moment I build a custom istio-proxy image which wraps the `pilot-agent` binary with a crude script that presumes if envoy is not around for 5 seconds, it's probably crashed or been `quitquitquit`, so sends a SIGTERM to pilot-agent.  Then from our other containers we can call `curl -XPOST http://127.0.0.1:15000/quitquitquit`

```
#!/bin/bash
echo "Starting custom autotrader pilot-agent wrapper..."

/usr/local/bin/pilot-agent-original $* &
AGENT_PID=$!
echo "Pilot agent started with pid: $AGENT_PID"

cleanup()
{
  echo "Stopping pilot-agent"
  kill -s TERM $AGENT_PID
  exit 0
}
trap cleanup SIGINT SIGTERM

n=0
until [ $n -ge 5 ]
do
  if ! pidof envoy &>/dev/null; then
    echo "envoy is not running!"
    n=$[$n+1]
  else
    n=0
    tail --pid=$(pidof -s envoy) -f /dev/null 
    echo "envoy exited, waiting up to 5 seconds for a new envoy to spawn..."
  fi
  sleep 1
done
cleanup
```

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
Just to make sure I full understand, you have jobs and when they complete the pods stick around because Envoy/pilot-agent is still running?

Seems like a reasonable and pretty simple feature.

In the mean time may I suggest `pilot-agent-agent` for the name of your script :slightly_smiling_face:

**Comment by Stono** [comment]
Haha nice name.
Yes, basically we have cronjobs that require sidecars, when the main process exits 0 the sidecar process does not.

We work around this by having the entry point of the main container TRAP the main script and then curl envoy when it ends with quitquitquit so the Pod/Job then completes.

**Comment by howardjohn** [comment]
When we do this we should also probably make sure we drain Envoy rather than force quitting. We already have code for this with TERMINATION_DRAIN_DURATION so should be pretty straightforward

**Comment by Stono** [comment]
@hzxuzhonghu do you know what release this will be in?  Looks like it isn't in 1.2.2 unless i'm missing something.

**Comment by yangminzhu** [comment]
Thanks @incfly for noticing this and we have some security concern on the PR https://github.com/istio/istio/pull/15123.

Is the 15020 port accessible to everyone? If so, It seems a malicious pod could potentially shutdown another pilot-agent with a simple HTTP request. 

Is 15020 enabled on ingress gateway by default? If so, it makes the situation worse as anyone can shutdown the pilot-agent on ingress gateway with a simple HTTP request.

I'm not sure the exact impact of shutting down the ingress gateway, but I don't think it's a good idea if it could be done by anyone, which could be a potential security vulnerability.

We need to evaluate and hold this before any release, @duderino @fpesce

**Comment by incfly** [comment]
I tried in a previous istio release. I'm definitely able to use public
ingress gateway ip to send request at 15020 port. If same applies for this
quitquitquit It will expose ingress gateway with being restart able by
anyone...

**Comment by Stono** [comment]
The fact that 15020 is open on the public ingress gateway seems crazy, and should be closed.  I can't see any logical reason to have public ingress traffic straight to pilot-agent?

Is `15000` open too (i can't check, I don't use ingress gateways and also have a very locked down NetworkPolicy which completely mitigates this issue).  I ask this as you can _currently_ call `15000/quitquitquit` to get envoy to quit.

**Comment by yangminzhu** [comment]
@Stono I believe the envoy 15000 is only accessible from the localhost which means it cannot be called outside of the pod.

**Comment by howardjohn** [comment]
Looks to me like we can access 15020.. that doesn't seem right

**Comment by hzxuzhonghu** [comment]
Thanks, so we could expose another port in pilot-agent listen only on the localhost and handle the quit request. Does this make sense?

**Comment by incfly** [comment]
Yeah, I talked with @howardjohn. A reasonable fix can be listening on
localhost with a separate port.

Meanwhile, we should remove 1502 from ingress gateway service as well.

**Comment by hzxuzhonghu** [comment]
> Meanwhile, we should remove 1502 from ingress gateway service as well.

Why remove this, then how do readiness probe for gateway?

**Comment by incfly** [comment]
We remove the k8s service object definition's port mapping, but not on the deployment object. readiness probe should continue to work, I think this can make public-ingress-gateway-ip:15020 unaccessible from internet, but i'm not 100% sure.

**Comment by hzxuzhonghu** [comment]
I know what you mean, SG

**Comment by hzxuzhonghu** [comment]
opened #15320

**Comment by costinm** [comment]
I'm not sure this is the right approach - in particular considering future plans on CNI. 
Even exposing 15000 - with all the /admin capabilities - to the app seems risky, and I think should be avoided. I don't know if it's a good idea to assume that the sidecar will always be in the same network namespace with the application, or that application should have access to the /admin of envoy.

If I understand this correctly, the goal is to make sure the sidecar container is shut down when the job is completed.  Can we turn this around, and add an option for the agent to connect to a port exposed by the application, and when that port stop responding - to shut down ? This is also the mechanism used for readiness/lifeness, and same port could be used for both.

So instead of app killing envoy and agent by connecting to a port, the sidecar will suicide if the app 
is not ready or send a special response on the app readiness port. At the same time we can lock down /admin - for example using a UDS socket to communicate with pilot agent.

**Comment by Stono** [comment]
The goal I thinj is to not have to make modifications to applications in
order for them to run effectively on the mesh.

https://github.com/monzo/envoy-preflight is an example of how the community
already does this with envoy, pilot-agent breaks this

Karl

**Comment by Stono** [comment]
Also we have quite a few apps that don't expose http listeners, eg cronjobs

**Comment by howardjohn** [comment]
Fixed by #15406

**Comment by howardjohn** [comment]
1.3 which will be roughly a month from now

**Comment by chadlwilson** [comment]
Thanks for the work on this! We just upgraded to Istio 1.3 in our lower environments and have been making good use of this already; allowing us to retire some hacky cleanup scripts and "is container completed?" API calls to determine job status independent of the pod/proxy.

However I was wondering if someone could clarify whether `localhost:15000` (admin) or `localhost:15020` (status) is the right port to use for this when running from an application container itself (assuming defaults for the ports) - with the intention of causing the sidecar container to complete/exit normally.

It's anecdotal, and I didn't really dig into it, but I initially tried with `:15000` and it seemed to just cause an Envoy restart internally in the container (so job didn't complete) whereas switching to `15020` caused the sidecar to exit as expected and the `Job` to run to completion. Is that expected? Am I missing something?

**Comment by howardjohn** [comment]
yes that is expected . 15020 is pilot agent, which manages the envoy instance - if you kill envoy at 15000 it will restart it. So you want 15020. That is what we added, envoy had quitquitquit for a while

**Comment by chadlwilson** [comment]
I see, thanks for the clarification! I didn't realise that 15000 was raw envoy - that explains it.

Thanks again for the work here, makes life much easier.
