### ISSUE TITLE
Headless services fail to start (pilot-agent) crash on 1.2.0

### ISSUE THREAD

**Issue by Stono** [istio/istio#15043]
**Bug description**
Pods which do not have containerPorts specified no longer work on 1.2.0.  We have some applications that only make outbound connections so as such do not need listeners so this is a regression for us.

This manifests as:
```
2019-06-20T21:48:59.542110Z    error    flag needs an argument: --applicationPorts
```

Because pilot-agent is being started with an empty value for applicationPorts:
```
proxy sidecar --domain platform-testing.svc.cluster.local --configPath /etc/istio/proxy --binaryPath /usr/local/bin/envoy --serviceCluster platform-testing --drainDuration 45s --parentShutdownDuration 1m0s --discoveryAddress istio-pilot.istio-system:15011 --zipkinAddress zipkin.istio-system:9411 --proxyLogLevel=error --dnsRefreshRate 300s --connectTimeout 10s --proxyAdminPort 15000 --concurrency 1 --controlPlaneAuthPolicy MUTUAL_TLS --statusPort 15020 --applicationPorts
```

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastrcture

**Expected behavior**
pilot-agent should still start, like it did in `1.1.9`

**Steps to reproduce the bug**
Create a deployment without any containerPorts

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.2.0

**How was Istio installed?**
Helm

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE 

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
Behavior looks the same on 1.1.9/1.2.0
```
$ dk run istio/proxyv2:1.1.9 proxy --applicationPorts
Error: flag needs an argument: --applicationPorts
2019-06-20T21:56:50.326114Z     error   flag needs an argument: --applicationPorts
```
```
$ dk run istio/proxyv2:1.2.0 proxy --applicationPorts
2019-06-20T21:57:00.497196Z     error   flag needs an argument: --applicationPorts
Error: flag needs an argument: --applicationPorts
```
1.1 template:
https://github.com/istio/istio/blob/release-1.1/install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml#L159

Essentially the same template in 1.2:
https://github.com/istio/istio/blob/release-1.2/install/kubernetes/helm/istio/files/injection-template.yaml#L157


So this same application didn't experience this in 1.1.9? Any idea where the difference is? If its working on 1.1.9 it would be useful to get the injected yaml to see what the `applicationPorts` looks like.

**Comment by Stono** [comment]
Hmmm, then it is likely a product of my exhaustion.  I'll head to bed and look it with fresh eyes, and re-open if it's actually an issue. 

Cheers John

**Comment by howardjohn** [comment]
Even if it happens on 1.1 it may still be an issue, it seems we should probably not pass the flag if there are no ports. Let me know what you find, maybe we should tweak the template a bit
