### ISSUE TITLE
Does istio support cutomized load balance mechnism?

### ISSUE THREAD

**Issue by Kiddinglife** [istio/istio#15057]
Hi folks,

I want to use istio in game server developments.
I am wondering if istio provides an admin API for developers to control or update the existing routing rules for load balance? 

for example, a game player teleports from Map Server A to Map Server B. The load balancer should expose an admin api to a caller who can change the current map server where the player locates currently from map server A to map server B.

I also investigated [Kong](https://github.com/Kong/kong) who provides quite poerful js and lua plugins that expose admin APIs for dynamic updatings on the routing rules. It satisfies all my needs except of not supporting UDP packet forwarding. 

Looking forward any reply.

Thanks.

**Comment by howardjohn** [comment]
Related: https://github.com/istio/istio/issues/13859

**Comment by howardjohn** [comment]
@Kiddinglife take a look at https://istio.io/docs/reference/config/networking/v1alpha3/virtual-service/#HTTPRoute. You can determine where you want to route to based on matching various things like headers, etc specified at https://istio.io/docs/reference/config/networking/v1alpha3/virtual-service/#HTTPMatchRequest

In terms of fully custom lua/js, I am not sure this is possible today.

> It satisfies all my needs except of not supporting UDP packet forwarding.

Istio doesn't yet support UDP either. I think there is some ongoing work in this area though, see https://github.com/istio/istio/issues/1430 for more details

**Comment by Kiddinglife** [comment]
I see envoy has implemented UFO protocol to support quic 4 months ago. I believe adding that to Istio should not be hard task.

**Comment by howardjohn** [comment]
There is interest in doing so, but I am sure its easy. I think @rlenglet is working on it/familiar with it

**Comment by rlenglet** [comment]
I didn't look into the details of Quic, but I believe there's any general UDP support in Envoy.

And wok is not only required in Envoy. There's work required in the CNI. When using iptables REDIRECT (the default) for redirection, we can't redirect UDP traffic. This requires using the iptables TPROXY mode. Using TPROXY requires running the Envoy sidecar proxy with CAP_NET_ADMIN, which is not acceptable for many users. So to make UDP redirection viable, we'll have to run Envoy sidecar proxies outside of the application pod, which is something we plan to do as part of Istio CNI, but we've just started that work. That's not an easy task.

**Comment by howardjohn** [comment]
@rlenglet thanks, I never quite got the CNI/UDP/TPROXY connection until now.

**Comment by howardjohn** [comment]
@Kiddinglife is there any additiona work/questions here? UDP support is tracked in another issue

**Comment by Kiddinglife** [comment]
all good. close it.
