### ISSUE TITLE
Support arbitrary labels on ServiceMonitors in installer prometheus-operator 

### ISSUE THREAD

**Issue by jwineinger** [istio/istio#15058]
**Describe the feature request**
We run prometheus-operator with the intention of allowing teams to run their own prometheus instances with config to target their own ServiceMonitors (and PrometheusRule) objects via [prometheus.prometheusSpec.serviceMonitorSelector](https://github.com/helm/charts/blob/master/stable/prometheus-operator/templates/prometheus-operator/crd-prometheus.yaml#L2433) in the stable helm chart. Our own prometheus does this as well, and so we need to apply our labels to the istio ServiceMonitors.

For our purposes, it would be sufficient to be able to specify an object of extra labels to apply to all service monitors added via the [istio/installer prometheus-operator subchart](https://github.com/istio/installer/tree/master/istio-telemetry/prometheus-operator).

**Describe alternatives you've considered**
1. Retagging all of our own ServiceMonitors and PrometheusRules with the "monitoring" label that istio uses and using "In" via matchExpressions. This is doable but we'd have to change a number of repos as well as our prometheus config.
1. Copying istio ServiceMonitor entries into our own codebase. This is undesirable since we'd need to watch and manually pull changes from upstream.
1. Forking istio/installer repo and making changes to ServiceMonitor labels. Less bad but still undesirable to maintain a fork.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by douglas-reid** [comment]
@jwineinger this sounds reasonable. happy to review PRs or help get this in somehow. we'd like to move operator integration into a stable form, and this seems like a step along the way.

**Comment by jwineinger** [comment]
CLA with employer isn't in place (yet?) so I'm afraid no PRs from me at the moment.
