### ISSUE TITLE
Egress pod RDS is not sent

### ISSUE THREAD

**Issue by pandey-adarsh147** [istio/istio#15055]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
Egress pod is not in sync state

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ Y] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastrcture

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
istio: 1.0.6
v1.12.6-gke

**How was Istio installed?**
Helm

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

PROXY                                                           CDS        LDS        EDS               RDS          PILOT                            VERSION
istio-egressgateway-6b8c9d476c-dz6gp.istio-system               SYNCED     SYNCED     SYNCED (100%)     NOT SENT     istio-pilot-54dfc4c47f-4wpds     1.0.2
istio-egressgateway-6b8c9d476c-kw6rk.istio-system               SYNCED     SYNCED     SYNCED (100%)     NOT SENT     istio-pilot-54dfc4c47f-4wpds     1.0.2
istio-egressgateway-6b8c9d476c-qllwx.istio-system               SYNCED     SYNCED     SYNCED (100%)     NOT SENT     istio-pilot-54dfc4c47f-4wpds     1.0.2
istio-ingressgateway-5b9d888c78-55n4c.istio-system              SYNCED     SYNCED     SYNCED (100%)     SYNCED       istio-pilot-54dfc4c47f-4wpds     1.0.2
istio-ingressgateway-5b9d888c78-npb5v.istio-system              SYNCED     SYNCED     SYNCED (100%)     SYNCED       istio-pilot-54dfc4c47f-4wpds     1.0.2

**Comment by howardjohn** [comment]
Are you seeing any real problems? Or just the "Not Sent"?

Its not necessarily a bus for it to be "Not sent", it depends on your config. Out of the box egress won't get any routes afaik

**Comment by pandey-adarsh147** [comment]
My serviceentry not wokring for a specific URL.

**Comment by GregHanson** [comment]
@pandey-adarsh147 can you share the ServiceEntry and corresponding VirutalService?  Typically if RDS is `NOT SENT` it means there was no VirtualService that applied to the egress gateway and so no route configs were generated for it.  You need a VirtualService in order to route traffic from apps/sidecars through the egress gateway to external services, otherwise apps will call the external services directly through their local sidecar proxy.  See how to setup an egress gateway to accept external traffic here: https://istio.io/docs/tasks/traffic-management/egress/egress-gateway/#egress-gateway-for-http-traffic

**Comment by mrshengzyzy** [comment]
Anyone solve this? I got the same issue.
```
istio-egressgateway-5c46cdf567-4kmd7.istio-system                    SYNCED     SYNCED     SYNCED (100%)     NOT SENT     istio-pilot-6f54c4c4ff-nj9ch     1.1.0
istio-egressgateway-5c46cdf567-lvfhb.istio-system                    SYNCED     SYNCED     SYNCED (100%)     NOT SENT     istio-pilot-6f54c4c4ff-mq2bp     1.1.0
istio-egressgateway-5c46cdf567-thz6w.istio-system                    SYNCED     SYNCED     SYNCED (100%)     NOT SENT     istio-pilot-6f54c4c4ff-nj9ch     1.1.0
istio-egressgateway-5c46cdf567-trpwp.istio-system                    SYNCED     SYNCED     SYNCED (100%)     NOT SENT     istio-pilot-6f54c4c4ff-58mc2     1.1.0
```

**Comment by howardjohn** [comment]
Issue seems abandoned, I don't think there is any actual bug here unless there is additional info provided - from what I can tell this is working as intended.

> You need a VirtualService in order to route traffic from apps/sidecars through the egress gateway to external services, otherwise apps will call the external services directly through their local sidecar proxy. See how to setup an egress gateway to accept external traffic here: https://istio.io/docs/tasks/traffic-management/egress/egress-gateway/#egress-gateway-for-http-traffic
