### ISSUE TITLE
istioctl kube-inject w/o cluster has additional required arguments in 1.2

### ISSUE THREAD

**Issue by esnible** [istio/istio#15061]
`istioctl kube-inject` now requires a Kubernetes cluster:

```
kubectl -n istio-system get cm istio-sidecar-injector  -o jsonpath="{.data.config}" > /tmp/inj-template.tmpl
kubectl -n istio-system get cm istio -o jsonpath="{.data.mesh}" > /tmp/mesh.yaml
istioctl kube-inject -f samples/bookinfo/platform/kube/bookinfo.yaml --injectConfigFile /tmp/inj-template.tmpl --meshConfigFile /tmp/mesh.yaml
unset KUBECONFIG
istioctl kube-inject -f samples/bookinfo/platform/kube/bookinfo.yaml --injectConfigFile /tmp/inj-template.tmpl --meshConfigFile /tmp/mesh.yaml 
Error: could not read valid configmap "istio" from namespace  "istio-system"
```

Even though the mesh configuration and injection configuration have been supplied, istioctl tried to read something and failed.

The fix for this item should include adding a test that lacks Kubernetes access.

@rvennam 

Probably introduced with https://github.com/istio/istio/pull/10830

**Comment by howardjohn** [comment]
I think you just need `--values-file` as well now possibly?

Are you working on this or want me to

**Comment by rvennam** [comment]
Want to add some additional context: 

Users should be able to run `istioctl kube-inject -f samples/bookinfo/platform/kube/bookinfo.yaml` independently - disconnected from any cluster. For example: This can be in a CI/CD pipeline where the output yaml is saved and applied later. 

This was working in 1.1.x and regressed in 1.2

**Comment by howardjohn** [comment]
You can you just need to pass an extra parameter. Just tested with 

```
istioctl kube-inject -f ~/kube/shell/shell.yaml --injectConfigFile /dev/null --meshConfigFile /dev/null --valuesFile /dev/null
```

We should update the docs though

**Comment by kramvan1** [comment]
Also happens with `version`
```
istioctl version
1.2.0
Error: unable to find any Istio pod in namespace istio-system
```

**Comment by esnible** [comment]
@kramvan1 The message is intended to indicate that there is no control plane.  It may be that we need to improve the message, what text would have made it clear to you?

If I run `istioctl version` without a cluster I see

```
1.2.0-rc.0
Error: unable to retrieve Pods: Get https://9.59.192.223:8001/api/v1/namespaces/istio-system/pods?fieldSelector=status.phase%3DRunning&labelSelector=istio: dial tcp 9.59.192.223:8001: i/o timeout
```

**Comment by kramvan1** [comment]
@esnible   Should this really be an Error for `version` and rc=1?    Seems like version and kube-inject type commands should not have a hard cluster dependency.

Was expecting to issue a `istioctl version` during a batch cd/ci job without cluster and not have it fail.  (added `|| true` to workaround for now).    While I expect errors from kube-inject if the files/yamls are bad, I don't expect it to require a cluster.

**Comment by esnible** [comment]
@howardjohn If you pass `/dev/null` for the outside-the-cluster files the injection doesn't actually happen.

I was able to get it working without a cluster.  First, with a cluster do

```
kubectl -n istio-system get cm istio-sidecar-injector  -o jsonpath="{.data.config}" > /tmp/inj-template.tmpl
kubectl -n istio-system get cm istio -o jsonpath="{.data.mesh}" > /tmp/mesh.yaml
istioctl kube-inject -f samples/bookinfo/platform/kube/bookinfo.yaml --injectConfigFile /tmp/inj-template.tmpl --meshConfigFile /tmp/mesh.yaml
kubectl -n istio-system get cm istio-sidecar-injector -o jsonpath="{.data.values}" > /tmp/values.json
```

Then, get rid of your cluster (I did `unset KUBECONFIG`), and do

```
istioctl kube-inject -f samples/bookinfo/platform/kube/bookinfo.yaml --injectConfigFile /tmp/inj-template.tmpl --meshConfigFile /tmp/mesh.yaml --valuesFile /tmp/values.json
```

I see injected file, based on the values of my cluster, but the injection did not require a cluster.  This work item should become a `Doc` item to update the documents.  It is unclear if better messages from _istioctl_ are also needed.

@frankbu

**Comment by howardjohn** [comment]
In 1.2 `istioctl version` change the default for the remote flag to be true. Remote reads the version of the control plane which of course requires a cluster. if you want no cluster you should be able to do `istioctl version --remote=false`

**Comment by kramvan1** [comment]
@esnible to clarify above, I see in your first group of cluster steps there's a call to `istioctl kube-inject` without the `--valuesFile`   is that really needed?

**Comment by kramvan1** [comment]
@howardjohn thx for the version clarification.    Is that `--remote=false` also needed with kube-inject when specifying all three inputs? --injectConfigFile --meshConfigFile --valuesFile

**Comment by howardjohn** [comment]
@kramvan1 nope it is just a flag on the version command. For kube-inject it will look for those flags and fallback to the cluster if they aren't provided, so if you provide all 3 it will not depend on the cluster

**Comment by linsun** [comment]
wonder if we can make this the default when not connecting to a remote cluster?

`istioctl kube-inject -f samples/bookinfo/platform/kube/bookinfo.yaml`

-->

`istioctl kube-inject -f samples/bookinfo/platform/kube/bookinfo.yaml --injectConfigFile /dev/null --meshConfigFile /dev/null --valuesFile /dev/null`

so that users don't have to remember the long syntax and we are backwards compatible to 1.1 as well?

@esnible @howardjohn

**Comment by howardjohn** [comment]
@linsun if they actually provide `/dev/null` then the injection won't do anything though. I just used that to test if it would not try to reach out to the cluster because I didn't have the 3 files on hand - probably wasn't the best example.

I think the best thing we can do is fail (with a better error message probably), rather than silently succeed but get unexpected behavior

**Comment by linsun** [comment]
Ohhhh i had thought doing these params would provide the injection behavior similar as 1.1...  why can't we provide a default injection behavior like 1.2 for quick starters?  we'd be asking users to run 3 cmds (https://github.com/istio/istio/issues/15061#issuecomment-504487646) to do a simple kube-injection that they could have done in 1.1

**Comment by howardjohn** [comment]
With a cluster running, in 1.1 and 1.2 they need no flags.

In 1.1, they need `--injectConfigFile ... --meshConfigFile ...` if they have no cluster.

In 1.2, they need `--injectConfigFile ... --meshConfigFile ... --valuesFile ...` if they have no cluster.

So the only change should be the one additional new flag.

Basically the kube-inject will normally get config from kubernetes if possible, but if not they need to be provided by the flags. In 1.2 we now depend on some more info (the values file) so that needs to be provided as well.

**Comment by linsun** [comment]
it just feels odd they need to provide these if just use the default that comes with a given istio release.     I had always thought the injectConfigFile and meshConfigFile were introduced to allow the customization which I think was the initial intention.  Seems istioctl itself would be able to know the default config for a given istio release as there is no cluster specific info inn the injectConfigFile or meshConfigFile.

**Comment by howardjohn** [comment]
@linsun I think that is possible but we would need a way to embed the default yamls into the istioctl binary. This is possible, and I think we do it in some other places

**Comment by linsun** [comment]
@howardjohn thanks, and I do believe that provides a better experience.  Maybe we can target this simplification for 1.3.

**Comment by esnible** [comment]
@linsun What would the user experience be if we baked in the template?

Although we removed the template there is no reason `make istioctl` couldn't copy _/install/kubernetes/helm/istio/files/injection-template.yaml_ into a .go file allowing it to be included in the build.  That wouldn't have solved the problem of a 1.1 user being surprised to know a new `--valuesFile` parameter is needed.

The simplest CLI I can imagine is  `istioctl kube-inject -f samples/bookinfo/platform/kube/bookinfo.yaml --remote=false --valuesFile=install/kubernetes/helm/istio/values.yaml`.  That is still quite difficult.

There are other UX problems related to the move to 1.2.  Using the 1.1 _istioctl_ against a 1.2 control plane gives an error:

```
istioctl-1.1 kube-inject -f samples/bookinfo/platform/kube/bookinfo.yaml
Error: error converting YAML to JSON: yaml: line 3: could not find expected ':'
```

We may not have upgrade tests related to kube-inject.

**Comment by howardjohn** [comment]
@esnible did we intend to support 1.1 `istioctl` with 1.2 control plane?

**Comment by dano0b** [comment]
Might be related, a fresh istio 1.2.0 installation via helm fails for me with various deployments including the bookinfo example with:
```
Name:           reviews-v1-796d4c54d7
Namespace:      default
Selector:       app=reviews,pod-template-hash=796d4c54d7,version=v1
Labels:         app=reviews
                pod-template-hash=796d4c54d7
                version=v1
Annotations:    deployment.kubernetes.io/desired-replicas: 1
                deployment.kubernetes.io/max-replicas: 2
                deployment.kubernetes.io/revision: 1
Controlled By:  Deployment/reviews-v1
Replicas:       0 current / 1 desired
Pods Status:    0 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           app=reviews
                    pod-template-hash=796d4c54d7
                    version=v1
  Service Account:  bookinfo-reviews
  Containers:
   reviews:
    Image:        istio/examples-bookinfo-reviews-v1:1.12.0
    Port:         9080/TCP
    Host Port:    0/TCP
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Conditions:
  Type             Status  Reason
  ----             ------  ------
  ReplicaFailure   True    FailedCreate
Events:
  Type     Reason        Age                    From                   Message
  ----     ------        ----                   ----                   -------
  Warning  FailedCreate  2m21s (x16 over 5m6s)  replicaset-controller  Error creating: Internal error occurred: admission webhook "sidecar-injector.istio.io" denied the request: error converting YAML to JSON: yaml: line 150: did not find expected '-' indicator
```
No pod creation at all.
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by irisdingbj** [comment]
> In 1.2 `istioctl version` change the default for the remote flag to be true. Remote reads the version of the control plane which of course requires a cluster. if you want no cluster you should be able to do `istioctl version --remote=false`

**Comment by irisdingbj** [comment]
For the version one, if there is no cluster connected, we should just put the istioctl client version and a waring(instead of an error) that no control plane available.

For the kube-inject one,  we can package a default config/value/mesh info into istioctl and if no cluster connected, we can use the packaged one as default and do the injection.

**Comment by esnible** [comment]
@irisdingbj This default is just about `kube-inject`, not version.

For 1.2 we purposefully removed the packaged injection template from _istioctl_.  It was not my design, but I gave it a positive review, because we were unable to keep the template in sync with the rest of Istio.  If we package default values into _istioctl_ we are back to the same problem -- the build needs to be modified to generate .go files for templates in _install_.  Is that what we want?

I am still struggling with the use case for manual inject.  To allow pipelines to create deployments with different defaults than a running cluster?

**Comment by esnible** [comment]
@howardjohn We did not intend to support 1.1 _istioctl_ with 1.2 control plane but we had hoped for a better error message than "Error: error converting YAML to JSON: yaml: line 3: could not find expected ':'".

A fix specific to Istio 1.1.10 seems like a waste of time.  We don't exactly know what went wrong.  Maybe we can come up with a strategy so this doesn't happen again for 1.2 users against 1.3.  Can we add a field or annotation to the _istio-sidecar-injector_ and _istio_ ConfigMaps saying which CLI they are compatible with?  Then we can print for example `mesh.controlPlaneVersion` as part of the error message.

**Comment by kramvan1** [comment]
@esnible   Our use case is to Allow our build pipeline to create deployments for future running clusters that are also defined during the pipeline so will always match/sync up.

**Comment by esnible** [comment]
@kramvan1 If your Istio cluster have auto-inject enabled, you almost never want to manual inject.  Manual inject will bake in a particular sidecar version, forever.  Usually we want the "future running cluster" to supply its own injection settings rather than letting the pipeline override them.

**Comment by kramvan1** [comment]
@esnible Yup, we do NOT have auto-inject enabled for any namespace.  We include the bookinfo sample as an optional piece of our install and  did not want to force the `default` namespace to be inject enabled, so the inject is done at build time instead.   This allows the customer to have complete control over what namespaces are enable for injection.      

Hope that makes some sense, we are focused on providing a "Managed" Istio, where our build side does most of the heavy lifting and the customer just has to click a single button to get Istio functionality in their cluster that we manage/maintain for them.
