### ISSUE TITLE
Helm install istio-security-post-install pod fails

### ISSUE THREAD

**Issue by jamborta** [istio/istio#15089]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

If global.proxy.autoInject is enabled and istio is installed in a namespace where istio-injection is enabled, istio-security-post-install fails with `containers with unready status: [kubectl]`. I suspect this is the result of the pod being injected with istio-proxy, as it is not annotated with `sidecar.istio.io/inject: "false"`

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastrcture

**Expected behavior**

Installation to complete.

**Steps to reproduce the bug**

Set proxy.autoInject to enabled and install in a namespace where istio-injection is enabled.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

istio version: 1.1.9
kubectl version: 1.11.3

**How was Istio installed?**

Helm

**Comment by howardjohn** [comment]
> istio is installed in a namespace where istio-injection is enabled

Does `istio-system` have injection enabled or are you installing in a different namespace? 

Regardless sounds like we need `sidecar.istio.io/inject: "false"`

**Comment by jamborta** [comment]
@howardjohn I'm installing it in a different namespace where injection is enabled.

**Comment by sdake** [comment]
Seems like a corner case for 1.2 - but definitely something to be fixed for 1.3.  If someone works up a patch for master, we can merge it there, but no guarantees it will make 1.2.

Cheers
-steve
