### ISSUE TITLE
"Process did not exit before 15s grace period" test flake

### ISSUE THREAD

**Issue by sushicw** [istio/istio#15095]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
Split off from https://github.com/istio/istio/issues/14083
From @douglas-reid: 
>I'm seeing a flake in this test, but for other reasons:
>
> Process did not exit before 15s grace period
>
> From: https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/14671/integ-security-k8s-presubmit-tests-master/1440
>
> That's kinda frustrating for a test that actually "PASS"'d.

From @ozevren:
> @douglas-reid it looks like, in that case the test maybe simply timing out due to the time spent on creating the images. Eyeballing some of the numbers, it takes quite a bit of time to download some of the images.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[X] Test and Release
[ ] User Experience
[ ] Developer Infrastrcture

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
My guess: I think this is just prow infrastructure flakes. The timeout isn't the real error, see above:

`{"component":"entrypoint","level":"error","msg":"Entrypoint received interrupt: terminated","time":"2019-06-10T21:33:12Z"}`

The test gets a SIGTERM because the node is getting killed, then forwards a SIGINT to the test process which probably does nothing with it.

Even if we handled the SIGINT, the test is still going to fail anyways

**Comment by howardjohn** [comment]
@sushicw any disagreement with above? I think this can be closed.

By the way, when the test hits the prow timeout (2 hours) it will have a different message -- the one you showed is different. Prow has a 2hr timeout then 15s for the test to "gracefully exit" once it gets a termination signal

**Comment by sushicw** [comment]
No disagreement, closing.
