### ISSUE TITLE
replicate istio release build on non google infra

### ISSUE THREAD

**Issue by linsun** [istio/istio#15090]
This is to explore some of the documentations out to ensure we can replicate Istio release build process on non google infra.  Some useful info from @utka:

this is docs about creating your own prow instance https://github.com/kubernetes/test-infra/blob/master/prow/getting_started_deploy.md

This is repo we use to trigger the release https://github.com/istio-releases/pipeline
istio-releases/pipeline
Istio Release Pipeline
Stars
4
Language
Shell
istio-releases/pipelineDec 5th, 2018Added by GitHub
I think forking it and connecting to your prow instance is one option.

@ibm-jason would be great if you could update this WI with progress and any PR/issues you opened along the journey!

cc @louiscryan @knrc @dcberg

**Comment by howardjohn** [comment]
Would be great to be infrastructure independent (`make release` on my laptop) as well. I guess the tests may be harder to get to that state, but the actual release should be able to other than doing things like tagging github, etc

**Comment by linsun** [comment]
@howardjohn agreed. I think @utka said she is working on that and may already have a WI tracking that effort to make the release process lightweight to run on dev's machine.   This WI is opened to replicate the monolithic process with prow etc on another k8s cluster.

**Comment by holgero** [comment]
Hi @linsun Is a WI an github issue (like this one) or something else?
I am asking because we are interested in being able to run the prow tests locally, too. We would even like to contribute here.

**Comment by linsun** [comment]
https://docs.google.com/document/d/1pV9Yta0W4F6shI5bw8TbF_SOne1fnrsZeeS4kjW5ApA/edit?ts=5d67fed2

**Comment by howardjohn** [comment]
To be clear ^ is only about build and publishing, not running tests. The key for testing is that prow should **not** be required. We are mostly there -- almost all tests can be run locally using kind

**Comment by linsun** [comment]
Re-assign to @ericvn - Would make sense to wait this until the prow dependency is removed (if that happens in 1.4ish timeframe).

**Comment by howardjohn** [comment]
Please give this a try: https://github.com/istio/release-builder/blob/4e570f92cba8adc82a251a5019cc3a69ed11c7e2/test/publish.sh#L1

This is how we publish dev builds now and will be used for 1.4. You can run it locally, have it point to private sources (like local path or private github repo), and publish to wherever you want.

**Comment by howardjohn** [comment]
Once one more PR lands to simplify things a bit I'll create a doc on how to do this. All you need is docker and you can build exactly like we do for official releases

**Comment by howardjohn** [comment]
See https://github.com/istio/release-builder/blob/master/release/README.md#L11

**Comment by linsun** [comment]
@ericvn Could you try what John has done in release-builder to see if we can produce the builds ourselves?

**Comment by howardjohn** [comment]
Is this done? If not please let me know if you need help.

**Comment by ericvn** [comment]
@linsun I mentioned on the T&R call today that I was successful running the release-builder code inside a docker container on my Mac. This included the build and validation steps. I did copy out of the container a number of artifacts included docker save images of the images, the various archive files which would be available for download as well as artifacts for licenses, etc.

At this point, I will write up the steps and add it to the release-builder readme so others can follow my steps. The biggest issue I had was setting some env vars in the container which affected how the components built and the release-builder code couldn't find the artifacts.

I have not actually tried to install and use one of the archives created, and relying on the validation code to be a good indicator. I will try using one of the archives soon.
