### ISSUE TITLE
Add SDS prober to check if Citadel Agent is reachable via UDS

### ISSUE THREAD

**Issue by JimmyCYJ** [istio/istio#15096]
**Describe the feature request**
Today we mount UDS path for Citadel Agent via volume mount. When this path is broken, SDS fails. In such cases, Citadel Agent does not receive any request and does not show any errors. Envoy proxy would show grpc stream closes with errors, and that log does not indicate root cause explicitly. 

To improve debuggability, we can add a SDS prober to test the UDS path. We could build this SDS prober into Pilot Agent to make periodical probe, or build the prober as a command option of istioctl to make ad hoc probe. The prober sends a SDS request to Citadel Agent via the UDS path, and we could add a metric into Citadel metric to show the most recent probe (source and timestamp).

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
Not relevant, nodeagent is gone
