### ISSUE TITLE
IP-based whitelists or blacklists deletion takes 4+ minutes to see the cleanup effect

### ISSUE THREAD

**Issue by yxun** [istio/istio#15097]
**Bug description**
Istio 1.1.7 and 1.2.0 "IP-based whitelists or blacklists" cleanup "mixer-rule-deny-ip.yaml" takes 4+ minutes to see the cleanup effect.
After applying the "mixer-rule-deny-ip.yaml" in Istio task "Denials and White/Black Listing" [1], user can see the "PERMISSION_DENIED... is not whitelisted" response when trying to access the Bookinfo productpage.
However, user will still see the "PERMISSION_DENIED... is not whitelisted" response until 4+ minutes after the deletion of the  "mixer-rule-deny-ip.yaml" . 

Is this an expected behaviour that requires 4+ minutes to see the effect of the IP based handler, instance, rule deletion ? 
Why does it take so long to see the deletion effect ?

[1] https://istio.io/docs/tasks/policy-enforcement/denial-and-list/

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ X ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ X ] User Experience
[ ] Developer Infrastrcture

**Expected behavior**
User should be able to access the Bookinfo productpage again after the deletion of IP-based whitelists or blacklists ("mixer-rule-deny-ip.yaml")

**Steps to reproduce the bug**
1. Installation Istio system
2. Deploy Bookinfo sample application with Gateway and DestinationRules [1]
3. Apply virtual-service-all-v1.yaml [2] and virtual-service-reviews-jason-v2-v3.yaml [3]
4. Apply mixer-rule-deny-ip.yaml [4] 
5. Try to access the Bookinfo productpage at http://$GATEWAY_URL/productpage and verify that you get an error similar to: PERMISSION_DENIED:staticversion.istio-system:<your mesh source ip> is not whitelisted
6. Delete mixer-rule-deny-ip.yaml [4] 
7. Try to access the Bookinfo productpage at http://$GATEWAY_URL/productpage and verify that you still get an error similar to: PERMISSION_DENIED:staticversion.istio-system:<your mesh source ip> is not whitelisted until 4+ minutes after the deletion.

[1] https://istio.io/docs/examples/bookinfo/
[2] https://raw.githubusercontent.com/istio/istio/release-1.2/samples/bookinfo/networking/virtual-service-all-v1.yaml
[3] https://raw.githubusercontent.com/istio/istio/release-1.2/samples/bookinfo/networking/virtual-service-reviews-jason-v2-v3.yaml
[4] https://raw.githubusercontent.com/istio/istio/release-1.2/samples/bookinfo/policy/mixer-rule-deny-ip.yaml

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
$ istioctl version --remote
client version: 1.2.0
citadel version: 1.2.0
galley version: 1.2.0
ingressgateway version: 1.2.0
pilot version: 1.2.0
policy version: 1.2.0
sidecar-injector version: 1.2.0
telemetry version: 1.2.0

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-04-16T12:43:51Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
Istio was installed with Helm via helm default template [1] on Minikube

[1] https://istio.io/docs/setup/kubernetes/install/helm/

**Environment where bug was observed (cloud vendor, OS, etc)**
$ minikube version
minikube version: v1.1.0

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by gargnupur** [comment]
Looks like a config question, that a config is taking a long time to cleanup. 
@douglas-reid , @ozevren : any clue here? Is this expected?

**Comment by ozevren** [comment]
This sounds more like a Mixer/caching related issue. Galley does not delay config propagation. A 4 minute delay would have been certainly noticeable in other parts of the system as well.

**Comment by gargnupur** [comment]
@ozevren : Thanks for the info...
@yxun : Can you repro this issue and share the logs of mixer policy pods when this is happening?

**Comment by yxun** [comment]
@gargnupur @ozevren Here is the istio-policy pod mixer container log:

[issue-15097.log](https://github.com/istio/istio/files/3698650/issue-15097.log)

minikube version: v1.1.0
istio verion: 1.3.1
kubectl version: v1.14.2
istio was installed in `istio-system` ns and bookinfo was installed in `bookinfo` ns.

I applied the mixer-rule-deny-ip.yaml in bookinfo ns (log file line: 14+) . And then after 20s, I deleted the  mixer-rule-deny-ip.yaml in bookinfo ns (log file line: 26? ). 
However, bookinfo permission denied message does not disappear until 4+ minutes after my mixer-rule-deny-ip.yaml deletion.

Do you need any other information ? Is this an issue related to the " informer caches to sync" ?

Thanks,
