### ISSUE TITLE
Missing tolerations for sidecarInjectorWebhook on 1.2.0 release

### ISSUE THREAD

**Issue by sterchelen** [istio/istio#15092]
**Bug description**
After upgrading from 1.1.3 to 1.2.0 version by setting tolerations, the sidecarInjectorWebhook could not be scheduled because of missing tolerations support on the deployment yaml file.

I'm seeing that on the master branch, the sidecarInjectorWebhook has tolerations support ... Plus a global variable to set tolerations.

When do you plan to release the master branch ?

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastrcture

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.2.0

**How was Istio installed?**
Helm

**Comment by howardjohn** [comment]
There is  PR to get it into a 1.2.x release https://github.com/istio/istio/pull/15081

Provided its merged it will be release very soon

**Comment by sterchelen** [comment]
Will it be the next release?

**Comment by fpesce** [comment]
> Will it be the next release?

Yes, I'll merge it before cutting 1.2.1

**Comment by howardjohn** [comment]
Fixed https://github.com/istio/istio/pull/15081
