### ISSUE TITLE
Pilot does not check global.sds.enabled when creating SDS config.

### ISSUE THREAD

**Issue by JimmyCYJ** [istio/istio#15102]
**Bug description**
This is found when I am modifying the perf test helm file. In a extra helm values.yaml, I set global.sds.enabled to false and global.sds.udsPath unset. When this extra values.yaml overrides  default values.yaml, the global.sds.udsPath has non-empty default value. This causes Pilot to generate SDS config for sidecar proxy. The deployment has no Citadel Agent pods because global.sds.enabled is false. This only affects workload SDS. Customers would hit such issue if they switch SDS to non-SDS and leave udsPath unchanged.

https://github.com/istio/istio/blob/5fcdb826dd8e4e08757c52a4587d0c499c1cafc5/pilot/pkg/security/authn/v1alpha1/policy_applier.go#L279

https://github.com/istio/istio/blob/5fcdb826dd8e4e08757c52a4587d0c499c1cafc5/pilot/pkg/networking/core/v1alpha3/cluster.go#L990

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastrcture

**Expected behavior**
Ideally, Pilot needs to check global.sds.udsPath before generating SDS config, or clear SdsUdsPath in MeshConfig. So that Pilot does not generate SDS config if global.sds.enabled is false.

**Comment by quanjielin** [comment]
it's a known issue that we had several PRs try to fix this before(https://github.com/istio/istio/pull/12534, https://github.com/istio/istio/pull/13605) , better sync with @costinm before making the change, see comments in https://github.com/istio/istio/pull/12534

**Comment by JimmyCYJ** [comment]
https://github.com/istio/istio/issues/13439

**Comment by JimmyCYJ** [comment]
According to https://github.com/istio/istio/pull/15109#discussion_r299634997, there is ongoing work on improving the UX for SDS installation and to support opt-in/gradual. That will solve the current issue in istio 1.3
