### ISSUE TITLE
Needs to link kube config to build and test istio

### ISSUE THREAD

**Issue by sebastienvas** [istio/istio#1511]
This is an artifacts from pilot, where we need to link the kube config in order to get pilot to build and run certain tests. If tests need such things that s fine, they can be tagged as manual, but user should be able to build and test istio out of the box.

**Comment by hklai** [comment]
@sebastienvas is this still applicable?

**Comment by sebastienvas** [comment]
I am not sure, I think the framework is going fix this, but if you do make test out of the box does it work ?
