### ISSUE TITLE
Expose stackdriver tracing for istio-proxy

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#15117]
https://github.com/envoyproxy/envoy/pull/5387 Added support for stack driver tracing.

This option is added to bootstrap along with all other options.

1. Add 
 configuration to mesh config 
https://github.com/istio/api/blob/6f137ab2ce6dd070df734d2c3cca69c8ea34b9c0/mesh/v1alpha1/proxy.proto#L40-L78 
2. The config should expose minimal knobs, potentially none since sampling is controlled elsewhere.   Specifically the desired config is [always parent](https://github.com/census-instrumentation/opencensus-proto/blob/master/src/opencensus/proto/trace/v1/trace_config.proto#L71) to conform to other tracers.
3. Add values options and update templates to inject bootstrap.

**Comment by kyessenov** [comment]
Example: https://gist.github.com/kyessenov/ae8e003bfba451f660cb9f875de8c8f4

**Comment by howardjohn** [comment]
@mandarjog is this done or did you have more left?

**Comment by mandarjog** [comment]
Not fully done.

**Comment by gargnupur** [comment]
I think this is not yet done completely?

**Comment by mandarjog** [comment]
What remains to be done.
1. Thread the stack driver option thru bootstrap. 
    meshconfig ---> sidecar injector --> encode as env var --> pilot agent uses env var to reconstitute meshconfig --> update boostrap.
2. Same envvar works for gateways which does not use sidecar injector.
3. Update the custom bootstrap in installer to have this option, so it can be used with TD.

**Comment by mandarjog** [comment]
@gargnupur after you verify and/or add e2e test for SD tracing, please close this issue.
Thanks.

**Comment by howardjohn** [comment]
@gargnupur any update on verify/e2e testing? I will move this to 1.5 milestone
