### ISSUE TITLE
Is there any way to have sidecar create the same number of tcp connections for the business container?

### ISSUE THREAD

**Issue by gxthrj** [istio/istio#15127]
istio version:1.2.0
scenes: grpc with istio

in my bussiness client using grpc created n channels for performance. (n > 1)
but with istio,  the tcp connection between sidecar is only one .

Is there any way to have sidecar create the same number of tcp connections for the business container?

**Comment by howardjohn** [comment]
I don't think this is supported: all supported options are in https://istio.io/docs/reference/config/networking/v1alpha3/destination-rule/. I  don't see any way to configure this in envoy either
