### ISSUE TITLE
Istio 1.2.0 is modifying `x-forwarded-proto`

### ISSUE THREAD

**Issue by Stono** [istio/istio#15124]
**Bug description**
We have the following setup:

`[nginx | sidecar] -> [sidecar | app]`.

The `sidecar` on nginx is configured with `traffic.sidecar.istio.io/includeInboundPorts: ""` which effectively makes nginx an edge load balancer for us.

A user hits `app.platform-testing.environment.k8.atcloud.io`, and hits nginx, that goes through the two sidecars to the destination app.

In istio 1.1.9 and below, we observed the `x-forwarded-proto` header being correctly set as https:

```
{
  "path": "/",
  "headers": {
    "host": "app.platform-testing.prod.k8.atcloud.io",
    "x-b3-flags": "0",
    "x-real-ip": "10.193.0.42",
    "x-forwarded-for": "10.193.0.42",
    "x-forwarded-host": "app.platform-testing.prod.k8.atcloud.io",
    "x-forwarded-port": "443",
    "x-scheme": "https",
    "x-forwarded-proto": "https",
```

In istio 1.2.0 (fortunately only in our preprod environments), it is being set to http:
```
{
    "path": "/",
    "headers": {
    "host": "app.platform-testing.preprod.k8.atcloud.io",
    "x-b3-flags": "0",
    "x-real-ip": "10.193.96.22",
    "x-forwarded-for": "10.193.96.22,10.206.9.91",
    "x-forwarded-host": "app.platform-testing.preprod.k8.atcloud.io",
    "x-forwarded-port": "443",
    "x-scheme": "https",
    "x-forwarded-proto": "http",
```

The other interesting change here is that the `x-forwarded-for` contains an additional IP.  for us `10.193.x.x` === `nodes`, `10.206.x.x` === `pod` (this seems fine btw just an observation).

This is a pretty severe breaking change for us, this breaks all SSO (as redirect urls are being sent as https), and all apps providing fully qualified links are incorrectly showing http.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[x] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Istio should not be overwriting this header.

**Steps to reproduce the bug**
See above

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Istio 1.2.0

**How was Istio installed?**
Helm

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

**Comment by Stono** [comment]
Potentially related envoy issue: https://github.com/envoyproxy/envoy/issues/4496

**Comment by Stono** [comment]
Using a `1.1.9` sidecar does not resolve this, so it is something to do with the config being sent from pilot.

**Comment by Stono** [comment]
Using a pilot `1.1.9` resolves the issue

**Comment by Stono** [comment]
Further testing shows that running with a pilot `1.1.9` images resolves this issue.  Diffing the envoy configuration for a `1.2.0` sidecar configured by both a `1.1.9` and `1.2.0` pilot shows changes in `use_remote_address`, which correlates to the issue I've linked above.

```
❯ cat pilot-1.2.0-envoy-1.2.0|grep use_remote_address
           "use_remote_address": false,
           "use_remote_address": true,
           "use_remote_address": true,
           "use_remote_address": true,
           "use_remote_address": true,
           "use_remote_address": true,

helm-platform-istio git/master
❯ cat pilot-1.1.9-envoy-1.2.0|grep use_remote_address
           "use_remote_address": false,
           "use_remote_address": false,
           "use_remote_address": false
           "use_remote_address": false,
           "use_remote_address": false,
```

I've attached two full diffs for you.
[pilot-1.1.9-envoy-1.2.0.log](https://github.com/istio/istio/files/3324907/pilot-1.1.9-envoy-1.2.0.log)
[pilot-1.2.0-envoy-1.2.0.log](https://github.com/istio/istio/files/3324908/pilot-1.2.0-envoy-1.2.0.log)

**Comment by Stono** [comment]
The associated commit seems to be: https://github.com/istio/istio/pull/14097

**Comment by rshriram** [comment]
nice find @Stono .. this is a side effect I didnt think of. Though @ramaraochavali 's PR had a different and valid point (app provided timeout headers being stripped). would it help to have a feature toggle for this in the interim? I believe setting use remote address is correct in sidecar, but your use case is equally valid. I am working on https://github.com/istio/api/pull/899 which will allow you to tweak the x-ff in nginx sidecar to set the xff-proto to https.

@ramaraochavali thoughts?

**Comment by Stono** [comment]
Anything to get the 1.1.9 behaviour back would be much appreciated so if you can get something in a nightly for me I'd be very happy.

**Comment by ramaraochavali** [comment]
@Stono Sorry, this change has caused you trouble. And I also did not realize that it would have the side effect of modifying the `x-forwarded-proto`. I am good with a feature toggle. Would it be OK, If I send PR tomorrow?  

@rshriram  Can I send directly to `1.2` branch?

**Comment by GregHanson** [comment]
@ramaraochavali the new practice is to send to master branch and tag the PR with the `merge to release branch` tag.  This will automatically open a PR to the current release branch once it merges to master.  This is important because it ensures the fix always ends up in master for future releases going forward.

**Comment by rshriram** [comment]
Send Pr to master and we can cherry pick immediately to 1.2.

**Comment by ramaraochavali** [comment]
Sure. Thanks. Makes sense. Will send a PR to master tomorrow

**Comment by duderino** [comment]
@fpesce heads up.  this may not land in time for 1.2.1, but please get it in asap

@ramaraochavali this is pretty important, so if you need help please ask on the networking slack channel.  If you can't wrap it up tomorrow for any reason, please tell us so we can get someone else on it.

Thank you

**Comment by ramaraochavali** [comment]
@duderino PR to fix this https://github.com/istio/istio/pull/15147

cc: @Stono

**Comment by fpesce** [comment]
@duderino : message acknowledged. Indeed, it 1.2.1 was cut yesterday, but we identified 2 changes at least we should
I'm hoping to cut 1.2.2 today, and if the Continuous Integration pipeline is good, maybe can release by tonight.

**Comment by linsun** [comment]
should this be closed?  pls reopen if I'm wrong after you found it differently @Stono

**Comment by Stono** [comment]
I've rolled out 1.2.2 and it's working as expected, thank you all.
