### ISSUE TITLE
Move Cluster-aware (Split Horizon) e2e test to new integration framework 

### ISSUE THREAD

**Issue by ericvn** [istio/istio#15131]
An initial version of this test created with https://github.com/istio/istio/pull/12709 closing https://github.com/istio/istio/issues/12268 and https://github.com/istio/istio/pull/12420.

It should be noted that this test was never added into the test framework so has not been run recently.

Trying to run that test locally against two IKS clusters I have having issues getting things to work. Some of it may be related to the IKS clusters and the e2e test framework, but I believe the underlying tests has issues as well:
  - The docs that the original test followed were the initial sample that was initially published with 1.1. Work was done for https://github.com/istio/istio/issues/12623 which changed the documented sample, and I believe that the current test would have failed with that work, requiring a rework of this test.

**Comment by ericvn** [comment]
I am still trying to get the existing test to work locally using IKS. I have run into a few issues:
  - The test relies on a secret named with the remote cluster. I first had a `_` in the name and this prevented the secret from being created (secret names must be a valid domain name?).
  - The e2e test framework uses kubectl to get the current config and dump that to a file in a temp directory and use that directory to specify the context in various commands. IKS uses a .pem file within the config and that .pem file is not placed in the directory so commands fail. A hack to work around the issue is to simply copy the .pem file from the config (I know where it is) to the temp directory. This will not work going forward. It may not need to be solved if the tests only run on GKE.
  - As noted above, the sample has changed, which requires changes in the test data and some of the process. Example its that we need to add network 1 and update the code to `sed` the master cluster IP for that.

**Comment by ericvn** [comment]
I was able to make code changes to run the SH test against two IKS clusters. A number of things needed to be done:
  - in test-values/values-istio-multicluster-split-horizon.yaml (updates to match new sample)
    - Add _network1_ in meshnetworks
    - set global network to _network1_
    - set int ingressgateway ISTIO_META_NETWORK env var to _network1_
  - kubernetes.go
    - don't create the multicluster secret if SH. Will create that within the SH test.
      This might be OK is I moved the secret creation logic I added in SH to this secret
  - split-horizon-test.go
    - create var to mimic the kubeconfig secret (IKS uses a .pem so this matches the the sample).
    - add test to make sure we access the primary cluster when calling the remote cluster.
    - get and sed the local GW Addr in the config map. (needed to update sed calling code to not add quotes).
    - create the kubeconfig secret similar to the example. the existing test just created the secret from the kubeconfig file, put that mentions a .pem. Could I create the secret adding the pem file if it was there? Something to test.
  - kube-utils
    - Be able to use a kubeconfig string instead of a file
    - Big hack copying the pem file directly from my drive when making the remote kubeconfig. This needs to be updated.
    - New method to do sed without quotes as needed by the test updating the cm code.

Note: I may throw this in a commit and attach as well.

**Comment by ericvn** [comment]
I need to do some investigation based on the above:
  -  Is there an issue with getting the tokens and using in a kubeconfig instead of using the actual kubeconfig? Will this result in some expiring tokens that will cause theSH test to fail at some point.
  - Random failure in the test (once fails will fail until I do another ix ks cluster config on the remote cluster). I think there is something with a token timing out when the test is trying to use use the k8s client.

**Comment by ericvn** [comment]
Reprioritization of work moves me to creating a multiple control plane multicluster test in the new integration framework so un-assigning myself in case someone else wants to work on this test.

**Comment by ericvn** [comment]
#15706 was created for the creation a new multi cluster test framework. I'm not sure at this point if the split horizon test is the best first choice for a test with that framework. I know there is on-going work to create single-mesh multi-cluster install guides based on best practices. The plan is to have tests for each of the documented cases. Some of that work can be found at https://github.com/philrud/istio-multicluster-examples. I'm not sure if this issue should be retargetted for one of those tests or if that work is contained somewhere else.

**Comment by ericvn** [comment]
This might be a duplicate of #15706

**Comment by hzxuzhonghu** [comment]
@elevran is this done?
