### ISSUE TITLE
istioctl add-to-mesh cmd

### ISSUE THREAD

**Issue by linsun** [istio/istio#15134]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
We need a single cmd to allow users to add a service to mesh, with istioctl.  Ideally, this cmd should work for adding k8s services to istio or adding services running in VM to istio.

**Describe alternatives you've considered**
Manual steps and VM expansion steps.

**Affected product area (please put an X in all that apply)**
There is protocol sniffing work that is in flight to simplify user's on boarding experience.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ x ] User Experience
[ ] Developer Infrastructure

**Additional context**
The goal is with this cmd, the user should be able to enjoy the telemetry or mTLS benefits that istio mesh can bring without any other configuration.  

cc @louiscryan @dcberg @esnible @irisdingbj

**Comment by esnible** [comment]
I have a proposal for CLI commands.  https://docs.google.com/document/d/1cO1TysDZca6e59Qq9VhcbPZXAcln0YxJZ9ssPVrwSiE/edit

Do the commands proposed look reasonable or did you have a different idea?

**Comment by linsun** [comment]
looks reasonable to me, I think i like add-to-mesh better than meshify.  Also, a key item here is the VM experience in addition to k8s.

**Comment by linsun** [comment]
@irisdingbj could you update if this is containable before 1.3 DCUT (mid Aug)?

**Comment by ayj** [comment]
Can we address the comment from @esnible's proposal re: [structural idioms](https://docs.google.com/a/google.com/document/d/1cO1TysDZca6e59Qq9VhcbPZXAcln0YxJZ9ssPVrwSiE/edit?disco=AAAACp459y0) before we add more commands? For example, do we want `istioctl services add <service-name>` or `istioctl add-to-mesh --service <service>`?

**Comment by linsun** [comment]
Thanks, missed that, I will add this as an agenda for next UX mtg on 7/23

**Comment by irisdingbj** [comment]
@incfly  #15640 is a good implementation for adding services which is running on VM into mesh. (scenario 2).

We want `istioctl add-to-mesh --service <service>` works for five scenarios:
1. add existing services which are running into service mesh(inject sidecar to it)
2. add services which are running on VM into mesh
3. add services which are running on VM with gateway connection into mesh
4. add service which are running on another cluster 
5. add service which are running on another cluster with  gateway connection

**Comment by incfly** [comment]
How is 2 different from 3?

`istioctl register` is about Service Registry part, and gateway or vpn is about L3 network part. These two should be independent.

Gateway or VPN mostly affect the installation phase, what you put in `/etc/hosts` on the VM IIRC.

**Comment by irisdingbj** [comment]
#2 requries a flat network between the cluster and vm while #3 remove this limit - I am working on this part now to provide this support.

**Comment by linsun** [comment]
https://github.com/istio/istio/issues/15804

**Comment by esnible** [comment]
@irisdingbj are you working on this?  Can you tell me which subcommands you can implement for 1.3?  I would like to divide the work that can be done for 1.3 from post-1.3 work and track them separately.

**Comment by irisdingbj** [comment]
@esnible  I am working on #1 for 1.3 and are using `istioctl add-to-mesh service serviceName` the PR is in https://github.com/istio/istio/pull/16156

**Comment by linsun** [comment]
@irisdingbj thank you!  Is it accurate to say add-to-mesh is in 1.3, but external service & remove in 1.4?

**Comment by irisdingbj** [comment]
I think all of the three PRs can be part of 1.3. Should I cherry pick them to 1.3 release manually?

**Comment by liamawhite** [comment]
@irisdingbj @linsun Is this issue resolved?
