### ISSUE TITLE
HTTP01 challenge failed with global.mTLS enabled 

### ISSUE THREAD

**Issue by adenis-sv** [istio/istio#15148]
**Bug description**

Routing to http01 challenge in Cert-manager fails if global mTLS is enabled.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[X] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Letsencrypt certificate should be normally issued/renewed even in case global mTLS is enabled.  

**Steps to reproduce the bug**

Deploy Istio 1.1.x or 1.2.0 with globally enabled mTLS:
https://istio.io/docs/tasks/security/authn-policy/#globally-enabling-istio-mutual-tls

CertManager could be installed as part of Istio (--set.certmanager.enabled=true) or 
as a separate application (version 0.6.2, 0.7.0)

Cert Issuer:
```apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt-http01-staging
  namespace: istio-system
spec:
  acme:
    email: redactedemail@domain.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: http01-issuer-staging-account-key
    http01: {}
```
Request certificate:
```apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: cert-httpbin-test-domain-com
  namespace: istio-system
spec:
  secretName: cert-httpbin-test-domain-com
  issuerRef:
    name: letsencrypt-http01-staging
    kind: Issuer
  commonName: httpbin-test.redacted.domain.com
  dnsNames:
  - httpbin-test.redacted.domain.com
  acme:
    config:
    - http01:
        ingressClass: istio
      domains:
      - httpbin-test.redacted.domain.com
```
logs from cert-manager looks the following
```
I0624 23:52:13.729050       1 http.go:111] could not reach 'http://httpbin-test.redacted.domain.com/.well-known/acme-challenge/68zD3DSKIsoL_u4vF8Y1lZAJJle03An7s2Y-Mk7hPr8': wrong status code '503', expected '200'
I0624 23:52:13.729096       1 controller.go:211] challenges controller: Finished processing work item "istio-system/cert-httpbin-test-domain-com-2664052065-0"
I0624 23:52:23.729251       1 controller.go:205] challenges controller: syncing item 'istio-system/cert-httpbin--test-domain-com-2664052065-0'
I0624 23:52:23.833234       1 http.go:111] could not reach 'http://httpbin-test.redacted.domain.com/.well-known/acme-challenge/68zD3DSKIsoL_u4vF8Y1lZAJJle03An7s2Y-Mk7hPr8': wrong status code '503', expected '200'
I0624 23:52:23.833276       1 controller.go:211] challenges controller: Finished processing work item "istio-system/cert-httpbin-test-domain-com-2664052065-0"
I0624 23:52:33.833424       1 controller.go:205] challenges controller: syncing item 'istio-system/cert-httpbin--test-domain-com-2664052065-0'
I0624 23:52:33.876820       1 http.go:111] could not reach 'http://httpbin-test.redacted.domain.com/.well-known/acme-challenge/68zD3DSKIsoL_u4vF8Y1lZAJJle03An7s2Y-Mk7hPr8': wrong status code '503', expected '200'
I0624 23:52:33.876857       1 controller.go:211] challenges controller: Finished processing work item "istio-system/cert-httpbin-test-domain-com-2664052065-0"
```
Service generated by HTTP01 challenge could not be reached (503) and certificate is not issued.

Possible MANUAL workaround to relax mTLS restriction:
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: cert-httpbin-test-domain-com
  namespace: istio-system
spec:
  trafficPolicy:
    tls:
      mode: DISABLE
  host: “cm-acme-http-solver-wgvxd.istio-system.svc.cluster.local"
```
here `cm-acme-http-solver-wgvxd` is a name of service generated as part of http01 challenge.
As soon as this DestinationRule deployed certificate is issued.
BUT this destinationRule is handcrafted. It is not a part of normal workflow. We could not generate these kind of DestinationRules for renew process because it is relied on random service name generated by CertManager as part of the challenge.

PLEASE NOTE that if global mTLS is not enabled by default everything works smoothly and certificate is normally issued without manual intervention (generation of Destinationrule).

Probably some more generic setup for DestinationRules or Policies for CertManager could help here, but I could not find ant documentation and discussion on Istio forum stoped here as well.

https://discuss.istio.io/t/using-gateway-virtualservice-http01-sds/2534/6

Any advises would be highly appreciated.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

Tested for Istio 1.1.2, 1.1.9, 1.2.0 with AWS EKS 1.11, 1.12, 1.13

**How was Istio installed?**

via helm chart. One of the options
```helm install install/kubernetes/helm/istio --name istio \
    --namespace istio-system \
    --set gateways.istio-ingressgateway.sds.enabled=true \
    --set tracing.enabled=true \
    --set kiali.enabled=true \
    --set global.mtls.enabled=true \
    --set global.k8sIngress.enabled=true \
    --set global.k8sIngress.gatewayName=ingressgateway \
    --set certmanager.enabled=true \
    --set certmanager.email=redacted.email@domain.com \
    --set global.proxy.accessLogFile="/dev/stdout"
```
**Environment where bug was observed (cloud vendor, OS, etc)**

AWS EKS

**Comment by invertigo** [comment]
I just replicated this problem on Kubernetes 1.13 running in Docker Desktop for Windows, so it's definitely not EKS specific

**Comment by JimmyCYJ** [comment]
There is a user guide on ingress with cert-manager, which uses DNS challenge. I think we don't support HTTP01 challenge while enabling mTLS for internal service-to-service communication. This is because cm-acme-http-solver-wgvxd may not have a sidecar injected. @diemtvu

**Comment by JimmyCYJ** [comment]
@diemtvu @howardjohn Could you please take a look and help to triage this issue?

**Comment by howardjohn** [comment]
So certmanager will create a service on the fly with a random name like `cm-acme-http-solver-wgvxd`, and then we fail to connect to it because we have mTLS and the created service does not. Who is calling `cm-acme-http-solver-wgvxd`? I am not familiar with this area

**Comment by gustavovalverde** [comment]
@adenis-sv this seems like a solution for your problem: https://github.com/jetstack/cert-manager/issues/1097

I'll be testing it

**Comment by diemtvu** [comment]
You can do the opposite, to set DR that disable mTLS for all (in `isitio-system` namespace), except for those you need. As a matter of fact, as of today, all services come with installation in `istio-system` either has its own DRs (policy, telemetry), don't have sidecar (citadel, grafana etc) or don't need DR (pilot). So it may be safe to add a rule like this
```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: disable-mtls-in-istio-system
  namespace: istio-system
spec:
  trafficPolicy:
    tls:
      mode: DISABLE
  host: “*.istio-system.svc.cluster.local"
```

**Comment by gustavovalverde** [comment]
@diemtvu I ended up following this steps: https://github.com/istio/istio/issues/6486#issuecomment-531346748

**Comment by gustavovalverde** [comment]
IMHO there are 2 main issues:
1- We need to have two gateways to issue the certificate, but they can't live together without causing issues: https://github.com/istio/istio/issues/13113

2- cert-manager does not allow the **same secret** to hold **multiple certificates**, making the certificate creation completely manual as each secret must be added to our gateway.

If both of this are solved; taking this https://github.com/istio/istio/issues/6486#issuecomment-531346748 considerations, the `http01` could be completely automated.

**Comment by yangminzhu** [comment]
@gustavovalverde is the issue resolved with https://github.com/istio/istio/issues/6486#issuecomment-531346748? If so I think we can close this one for bug report, feel free to open an feature request if needed.

**Comment by Anujay-Saraf** [comment]
@howardjohn @gustavovalverde @prune998

Need one help here with your expertise.

I am unable to receive a working certificate thru letsencrypt prod/staging API:

Snapshot
![image](https://user-images.githubusercontent.com/27989098/88177282-3bb95480-cc46-11ea-99df-82abde108ecf.png)


The current setup includes below approach

K8s cluster setup with 1.0.2 Istio Dex Yaml, mentioned in kubeflow.org documentation, which comes with istio 1.3.1 and cert-manager by default.
As my major task is to complete this with kubeflow enabled with istio-ingressgateway along with HTTPS Lets-Encrypt ACME SSL Certificate generation.
Kindly let me know a possible solution.

K8s API version 1.14
Istio -1.3.1
Cert-Manager: the same which comes with default manifest.
