### ISSUE TITLE
ControlZ Not Working

### ISSUE THREAD

**Issue by divya21raj** [istio/istio#15149]
**Bug description**
I'm trying to access envoy logs, so I found [ControlZ](https://istio.io/docs/ops/controlz/) which is supposed to give me some logs. I followed the documentation and ran this -

` kubectl port-forward -n istio-system istio-ingressgateway-64b798d69d-vn7fk 9876:9876`

But upon hitting localhost:9876, I get this 
```
Handling connection for 9876
E0626 13:42:46.772249   11428 portforward.go:400] an error occurred forwarding 9876 -> 9876: error forwarding port 9876 to pod 9d70cc7f5d869da7bc15688c4af61aa7398ac3e8fc442bdf170067eb180f54ea, uid : exit status 1: 2019/06/26 08:12:46 socat[20806] E connect(5, AF=2 127.0.0.1:9876, 16): Connection refused
```
What am I doing wrong?

**Affected product area (please put an X in all that apply)**

[x] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
I should be able to access the logs on localhost:9876

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
`client version: version.BuildInfo{Version:"1.1.7", GitRevision:"eec7a74473deee98cad0a996f41a32a47dd453c2", User:"root", Host:"341b3bf0-76ac-11e9-b644-0a580a2c0404", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.6-6-geec7a74"}`

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
Using helm template. I followed [this](https://medium.com/google-cloud/back-to-microservices-with-istio-p1-827c872daa53) article.
 
**Environment where bug was observed (cloud vendor, OS, etc)**
Minikube cluster.

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
controlz only runs on the control plane (Pilot, mixer, galley, etc) not in the ingressgateway. If you want to see the logs you can do `kubectl logs PODNAME`. The same goes for the control plane as well, controlz is mostly for changing the logging level on the fly and some other debug info, I don't think it shows the actual logs as well

**Comment by ozevren** [comment]
We should clarify the documentation about Ctrlz being on the control plane.

**Comment by divya21raj** [comment]
> controlz only runs on the control plane (Pilot, mixer, galley, etc) not in the ingressgateway. If you want to see the logs you can do `kubectl logs PODNAME`. The same goes for the control plane as well, controlz is mostly for changing the logging level on the fly and some other debug info, I don't think it shows the actual logs as well

Ok, what I'm trying to do is check logs from envoy which are there in files like _jwt_authenticator.cc_
`ENVOY_LOG(debug, "fetch pubkey [uri = {}]: success", uri_);` <- things like this.

I was trying to follow [this](https://discuss.istio.io/t/grpc-jwt-authentication-silently-failing-in-istio/2829/2) conversation, but got stuck with the controlz thing. How can I achieve this? Thanks for the help!

**Comment by howardjohn** [comment]
kubectl exec $(kubectl get pods -l istio=ingressgateway -n istio-system -o
jsonpath='{.items[0].metadata.name}') -c istio-proxy -n istio-system --
curl -X POST "localhost:15000/logging?filter=debug" -s

should work

**Comment by divya21raj** [comment]
@howardjohn Say I want to do this for a different pod(sa-web-app-599cf47c7c-94jb4), how will this command change?

**Comment by divya21raj** [comment]
Got it, thanks! The command will be 
```
kubectl exec $(kubectl get pods -l app=sa-web-app -o jsonpath='{.items[0].metadata.name}') -c istio-proxy -- curl -X POST "loca
lhost:15000/logging?filter=debug" -s
```
Just had to change the label parameter. Now upon doing `kubectl logs <pod> -c istio-proxy` I can see the required logs :)
