### ISSUE TITLE
The istio/operator repository README.md is uninviting and hard to understand

### ISSUE THREAD

**Issue by sdake** [istio/istio#15151]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

- Clean up the content of the README.md to ensure wide community participation.
- More clearly specify the initial objectives / MVP of the repository. 

**Describe alternatives you've considered**

status quo.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by ostromart** [comment]
Fixed in https://github.com/istio/operator/pull/61
