### ISSUE TITLE
Bazel_to_go should copy genfiles only on change and maintain go dep file

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#1515]
Bazel_to_go already processes the workspace.

1. It copies generated files and updates a manifest.
2. Creates symlinks from vendors dir

It should 
1. Only copy gen files if they have meaningfully changed.
 The generated files have the absolute source file path embedded in them.
 This makes it susceptible to spurious changes. Tool should ignore change if it is purely path change in the genfile.
2. It should authoritatively generate and maintain the go dep file.

@costinm @jmuk

**Comment by costinm** [comment]
The 'dep file' doesn't have to be updated on every build, it is ok to do it daily or if a new dep is added or needs to be updated. 

I think we should fix 'absolute source files embedded' - I doubt it helps in any real use, and then we can
just copy files on each build and git will detect they're unchanged. This way any submit that changes 
a proto or file that has generated artifacts will include the generated files as well.

**Comment by jmuk** [comment]
done for 1. for 2 -- it's a bit harder for me due to my lack of knowledge of Gopkg.lock file format -- @rshriram, do you have bandwidth for that?

**Comment by rshriram** [comment]
There is no gopkg.lock file. You just have to update sha in the toml file

**Comment by jmuk** [comment]
ah, okay, so this is done. Sorry I accidentally fixed by #1930 but let's keep it as-is. Thanks!
