### ISSUE TITLE
VirtualService HTTPDestination weight = 0 value overriden in code to 100

### ISSUE THREAD

**Issue by abonas** [istio/istio#15157]
**Bug description**
The case where there is a single route with weight = 0, there might be need  to add some validations and logic fixes.

Per the docs
https://istio.io/docs/reference/config/networking/v1alpha3/virtual-service/#HTTPRouteDestination
"If there is only one destination in a rule, the weight value is assumed to be 100."
In case that the user has added a yaml with weight = 0, it seems that there are a few things that might be happening:

1. the weight = 0 is treated/overriden in code to 100, but the yaml remains with weight = 0 which is not very user friendly. So even if user explicitly wrote 0, 100 is used in code. 
the comment in docs is not very clear that even if the weight *is* set, then its value is ignored.
(user could have left it empty too)
https://github.com/istio/istio/blob/7fbfec5e8e4afebc8e1d715854a7e22545e32e87/pilot/pkg/networking/core/v1alpha3/route/route.go#L393

2. there seems to be no validation for the case when there is a single weight that is !=100
https://github.com/istio/istio/blob/870877a1e3d01f6a2c285f67ed1f709a9f993095/pilot/pkg/model/validation.go#L2079

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] User Experience

**Expected behavior**

1. the code reflects the yaml configuration set by user, not silently overriding it. 
2. validation for the case where a single weight destination is either 0 or just <100 is added, so users know their setup is incorrect (which is the reason why it is overriden in the first place)

**Steps to reproduce the bug**

add a virtual service with one route and weight = 0
(although it's probably will work the same with any value < 100)

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
latest
![weightzero](https://user-images.githubusercontent.com/6277245/60192729-0f62b700-983f-11e9-8be5-734888ad557d.png)

**Comment by abonas** [comment]
@xeviknal fyi

**Comment by esnible** [comment]
@GregHanson I am not sure how to tag this.  Does it belong in the https://github.com/istio/api repo?

The documentation comes from https://github.com/istio/api/blob/master/networking/v1alpha3/virtual_service.proto .  Because Istio internally represents configuration as an `int32` it is difficult to distinguish skipping the field and explicitly setting it to 0.

@abonas is your user setting the weight to 0 intending to get Istio to send no traffic?  When I wish Istio to send no traffic I typically do

```
   fault:
       abort:
         percentage:
           value: 1
         httpStatus: 501
```

**Comment by abonas** [comment]
> @GregHanson I am not sure how to tag this. Does it belong in the https://github.com/istio/api repo?
> 
> The documentation comes from https://github.com/istio/api/blob/master/networking/v1alpha3/virtual_service.proto . Because Istio internally represents configuration as an `int32` it is difficult to distinguish skipping the field and explicitly setting it to 0.

Not sure I understand this part - "explicitly setting it to 0"
The configuration arrived with weight = 0 , and then the code sets it to 100, that's a complete change of logic IMO.

> 
> @abonas is your user setting the weight to 0 intending to get Istio to send no traffic? When I wish Istio to send no traffic I typically do

I witnessed it on a knative environment where user is creating an entity of type Channel, and then (I'm guessing, not that familiar with Knative) it's converted to VS by Knative
> 
> ```
>    fault:
>        abort:
>          percentage:
>            value: 1
>          httpStatus: 501
> ```

**Comment by esnible** [comment]
@abonas `kubectl` converts your YAML into JSON, then Istio converts that YAML into a Protobuf-derived Go struct that represents weight as an `int32`.  Once the weight is an int32 we can't tell if was explicitly set to 0 or skipped in the YAML.  The code that looks for 0 and sets it to 100 is trying to implement the default of 100% of traffic if the weight is skipped.

**Comment by abonas** [comment]
But isn't Galley validating the json before the conversion when the request is received?
