### ISSUE TITLE
Zombie configuration from deleted objects

### ISSUE THREAD

**Issue by bkrahmer** [istio/istio#15185]
**Bug description**
I was trying to configure istio to do a simple task yesterday, and together with my colleague, we were troubleshooting and were seeing strange things.  We started deleting pieces of the config (made up of a couple gateways, virtual services, destination rules, and a service entry), and even after all of the config was deleted, we were still seeing traffic being routed by istio.  We restarted all of the istio components (galley, pilot, policy, ingressgw and egressgw), and the problem remained.  I killed the pod where I was curl'ing from, and the problem remained.  This morning, the problem still remains, I took a config dump, and all of those deleted objects are still in the filter chains, with current timestamps.  Have you seen something like this before, or have any ideas on how to correct this issue?

**Affected product area (please put an X in all that apply)**

[X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Environment where bug was observed (cloud vendor, OS, etc)**
OpenShift 3.11 w/ Red Hat Service Mesh TP10 

[istio-dump.tar.gz](https://github.com/istio/istio/files/3333755/istio-dump.tar.gz)

**Comment by hzxuzhonghu** [comment]
@bkrahmer  I doubt there is some thing wrong oabout the mcp connection between pilot and galley.

**Comment by bkrahmer** [comment]
Yeah, I think that's fair.  I do believe there is something wrong with this openshift installation...

**Comment by bkrahmer** [comment]
I was reviewing the logs again, and realized you probably saw the dns errors from yesterday.  This happened because the galley service disappeared (that in itself is a mystery, but we recreated the service, and restarted the istio components after that.)  Since then, the istio components _seem_ to be healthy from my naive eyes, so I would appreciate it if you could check the logs again and see if there is any obvious explanation for what could be causing this.

**Comment by howardjohn** [comment]
Is this still an issue? sounds like it was resolved

**Comment by bkrahmer** [comment]
I don't know if the problem persists or not.  Our project direction changed, and istio was removed from the architecture (for now, at least).
