### ISSUE TITLE
Internal Service to Service communication using weighted routing

### ISSUE THREAD

**Issue by bradenwright** [istio/istio#15186]
**Bug description**
I'm attempting to get internal services communicating via a virtual service / destination rules with weighted routing.  

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[X] Docs
[X] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Not sure if I have all the configuration right but I've tried lots of different options and have not been able to get it working

**Steps to reproduce the bug**
I created a helm chart via helm create to setup an nginx hello world page.  I then created a 2nd service and deployment.  So I have deployments: (1) frontend-blue (2) frontend-green and services: (a) frontend-blue (b) frontend-green

I then created a single virtualservice in front of both.  When trying to route from the outside the cluster and using a match on authority it works fine
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: 2019-06-25T21:39:40Z
  generation: 1
  name: frontend
  namespace: sb2-app
  resourceVersion: "4493987"
  selfLink: /apis/networking.istio.io/v1alpha3/namespaces/sb2-app/virtualservices/ds-frontend
  uid: bd1137a0-9791-11e9-a8c7-42010a0c2005
spec:
  gateways:
  - istio-system/istio-public
  hosts:
  - '*.sb2.example.io'
  http:
  - match:
    - authority:
        exact: frontend.sb2.example.io
      uri:
        regex: ^/(?!aggregator).*$
    route:
    - destination:
        host: frontend-blue.sb2-app.svc.cluster.local
        port:
          number: 80
        subset: blue
      weight: 50
    - destination:
        host: frontend-green.sb2-app.svc.cluster.local
        port:
          number: 80
        subset: green
      weight: 50
```

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  creationTimestamp: 2019-06-25T21:16:29Z
  generation: 1
  name: frontend
  namespace: sb2-app
  resourceVersion: "4487483"
  selfLink: /apis/networking.istio.io/v1alpha3/namespaces/sb2-app/destinationrules/frontend
  uid: 7fb4d3b4-978e-11e9-a8c7-42010a0c2005
spec:
  host: '*'
  subsets:
  - labels:
      version: blue
    name: blue
  - labels:
      version: green
    name: green
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
```

I've tried numerous things e.g.:

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: 2019-06-25T21:02:49Z
  generation: 4
  name: frontend
  namespace: sb2-app
  resourceVersion: "4490841"
  selfLink: /apis/networking.istio.io/v1alpha3/namespaces/sb2-app/virtualservices/ds-frontend
  uid: 96ad359d-978c-11e9-a8c7-42010a0c2005
spec:
  gateways:
  - istio-system/istio-public
  hosts:
  - '*'
  http:
  - match:
    - uri:
        regex: ^/(?!aggregator).*$
    route:
    - destination:
        host: frontend-blue.sb2-app.svc.cluster.local
        port:
          number: 80
        subset: blue
      weight: 0
    - destination:
        host: frontend-green.sb2-app.svc.cluster.local
        port:
          number: 80
        subset: green
      weight: 100
```

For Host I was trying internal service name like `frontend-blue` or `frontend-green`, I also tried to see if I could create a host of `frontend` that would be routable to both but the VirtualService doesn't create a dns entry so that didn't work.  I was hoping I would be able to override the hostname so for instance send 100% of traffic to `green` and try to hit `frontend-blue` hoping it would actually go to green b/c of the 100 weight.

I just feel like I'm missing something. 

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Istio 1.1.8

**How was Istio installed?**
Helm

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

**Comment by rcaballeromx** [comment]
@bradenwright Can you help me understand what conditions you want to set up to route the traffic? Based on the configuration you shared:
```
  http:
  - match:
    - authority:
        exact: frontend.sb2.example.io
      uri:
        regex: ^/(?!aggregator).*$
    route:
    - destination:
        host: frontend-blue.sb2-app.svc.cluster.local
        port:
          number: 80
        subset: blue
      weight: 50
    - destination:
        host: frontend-green.sb2-app.svc.cluster.local
        port:
          number: 80
        subset: green
      weight: 50
```
I am not entirely sure what conditions need to be met for a request to reach a service in the blue subset, for example.

**Comment by bradenwright** [comment]
It should be same conditions, ultimately I just want to be able to flip traffic from blue having 100 of the weight and green having 0, to green having 100 of the weight and blue having 0.

For the matching you can ignore the `uri: regex` I'm fine with all traffic routing to the service if the authority matches (aka the service name)

**Comment by vadimeisenbergibm** [comment]
@bradenwright Could you please clarify what exactly you are trying to achieve and what is currently working?

Do you want to route a request that arrives to `istio-public` ingress gateway, 100% either to frontend-blue.sb2-app.svc.cluster.local or to frontend-green.sb2-app.svc.cluster.local ?

And it works with 50/50 but does not work with 100% routing to one of the hosts?
