### ISSUE TITLE
Support hot reload sidecar inject configuration

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#15182]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

Support reload sidecar inject configuration. Currently if we change the `istio-sidecar-injector` configmap, it will not take effect , this can be easily verified.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
I think we have this feature. maybe it's not fast enough but there is code in the injector that claims to do this at least

**Comment by esnible** [comment]
Are you reporting that new pods created after _istio-sidecar-injector_ is modified do not include the modifications?

Or are you reporting that pods created before the injector is modified are not restarted with the new configuration?

**Comment by hzxuzhonghu** [comment]
>Are you reporting that new pods created after istio-sidecar-injector is modified do not include the modifications?

I mean this.  And i take a fast look at code, do not find the file watcher about the config file.

**Comment by howardjohn** [comment]
take a look at https://github.com/istio/istio/pull/13480/files I think it modifies part of it. the part with the timer

**Comment by hzxuzhonghu** [comment]
Thanks, that's it.
