### ISSUE TITLE
Support "use_http_header" configuration for PassThroughClusters

### ISSUE THREAD

**Issue by ramaraochavali** [istio/istio#15183]
**Describe the feature request**

This feature request is to allow `PassThroughCluster` to be configured with [`use_http_header` ](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/cds.proto#cluster-originaldstlbconfig) when creating a destination rule. This allows us to route traffic to ip:port specified in the header [x-envoy-original-dst-host](https://www.envoyproxy.io/docs/envoy/latest/configuration/http_conn_man/headers.html?highlight=original%20dst#x-envoy-original-dst-host).

**Describe alternatives you've considered**
Currently there are no alternatives available.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by ramaraochavali** [comment]
Couple of possible options
- Add a boolean flag [here](https://github.com/istio/api/blob/master/networking/v1alpha3/destination_rule.proto#L283).
- Add a feature flag to generate the config for default PassThroughCluster and we can use the wild card route?

@rshriram I know https://github.com/istio/api/pull/899 might possibly address this case - But thinking first class support for this may be good. What do you think? Any other suggestions?

**Comment by hzxuzhonghu** [comment]
Under what case, do you need to pass this in header?

If u really want to specify he host, why not try ServiceEntry or Headless service? Without thinking too much,  maybe both of these can satisfy you..

**Comment by ramaraochavali** [comment]
This is a use case of dynamic request routing where the ip:port is determined based on some logic. It is not known ahead - so we can not create service entry and wait for it to be pushed to all Envoys.

Sorry, I should have made this point clear.

**Comment by hzxuzhonghu** [comment]
It is really special, also a doubt now that you can already set the header according your logic, why can not access it directly?

**Comment by ramaraochavali** [comment]
Because we want to take the benefit of mTLS from proxy instead of application taking care of SSL + cert rotations etc.

**Comment by howardjohn** [comment]
seems like a perfect use case for EnvoyFilter

**Comment by howardjohn** [comment]
seems like a perfect use case for EnvoyFilter

**Comment by howardjohn** [comment]
I don't think destination rule will work since Passthrough Cluster is shared by everyone

**Comment by ramaraochavali** [comment]
Do you mean a Passthrough Cluster created by a destination rule is shared by every one? If that is the case, we can add this config as an optional/configurable thing for the default PassThroughCluster - that also should work for our use case

**Comment by howardjohn** [comment]
There is only one "PassthroughCluster", its always there whether or not you configure a destinationrule or not.

I guess you probably mean the `PASSTHROUGH` loadbalancer type though so that makes sense

**Comment by ramaraochavali** [comment]
Yes, I meant specifying `PASSTHROUGH` loadbalancer type while creating `DestinationRule`.

So which approach should we take here - add that configuration in `DestinationRule` or add a flag to either in feature flags/mesh config and set this config for default 'PassThroughCluster'? Either would work for us. 

I am leaning towards option #2 for now as it is simple.

We are blocked on this for one  of our use cases so based on what we decide here, I will submit a PR.

**Comment by howardjohn** [comment]
Will EnvoyFilter not work for this? I haven't kept too much up to date on its development but I think this is like the exact type of use case it is intended for

**Comment by ramaraochavali** [comment]
I think it might work. But the reason I am proposing alternative is because
- We need this immediately , so looking for a solution that we can start with and migrate to EnvoyFilter if it works later
- And possibly exposing API for this does not harm as we do not have to go via complex EnvoyFilter manipulation for this simple setting.

**Comment by ramaraochavali** [comment]
@howardjohn @rshriram Any objections  on adding the "use_http_header" to default passthrough cluster based on a config? I will push a PR to that effect if you are fine with it.

**Comment by howardjohn** [comment]
this seems like a security vulnerability waiting to happen. For instance someone sets this on their DR, now users through ingress gateway can set this header and he routed to arbitrary services? Maybe I misunderstand the feature though

**Comment by ramaraochavali** [comment]
Yes, it is a possibility as documented here https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/cds.proto#cluster-originaldstlbconfig - That is why we only enable only few namespaces with care. I think PASSTHROUGH LB it self is for advanced use cases and must be used with care as documented here https://github.com/istio/api/blob/master/networking/v1alpha3/destination_rule.proto#L304.

**Comment by rshriram** [comment]
Sorry for the delay. So, I am planning on finishing up the EnvoyFilter asap in the next week or so - all the things in https://github.com/istio/api/pull/899 [the CDS piece should be dead simple]

**Comment by ramaraochavali** [comment]
Thank you. Will wait for your PR then.

**Comment by ramaraochavali** [comment]
@howardjohn  No. Not yet. but I am sure it will work. We can close this and will reopen if it becomes an issue.

**Comment by imcom** [comment]
@howardjohn @ramaraochavali I went through your conversations in this thread but I could not really tell what's the conclusion here ... Sounds like the EnvoyFilter should be able to fulfil the need here but may I have a working example on how to configure the EnvoyFilter via istio resources and the filter can actually select an upstream endpoint based on the request header? 

Thanks in advance

**Comment by imcom** [comment]
My use case is as follows, I have a EDS cluster using k8s service discovery, this is pretty default. But then the each endpoint in the upstream cluster is exclusive, so one endpoint can only serve one client. This brings the need that we would like to use a HTTP header to control which upstream endpoint should be used for a given client. What I have imagined is that to the very least we have LEAST_REQUEST LB rule in place so most of cases we trust envoy to find the idle upstream. But in case one client lands on an already serving upstream, the upstream can instead give a spare upstream to the client (e.g. 302 redirect with the chosen upstream ip:port, later on client can include this ip:port in the follow up request) So envoy can use the ip:port as specified in this header. 

Or any other advices would be greatly appreciated!

**Comment by ramaraochavali** [comment]
you have add an envoy filter (see example https://github.com/istio/istio/wiki/EnvoyFilter-Samples) that targets the upstream cluster and set that flag to true.

**Comment by imcom** [comment]
> you have add an envoy filter (see example https://github.com/istio/istio/wiki/EnvoyFilter-Samples) that targets the upstream cluster and set that flag to true.

Oh, I see, I will give it a shot, thanks for the direction!

**Comment by howardjohn** [comment]
I'd recommend you just use PASSTHROUGH lb https://istio.io/latest/docs/reference/config/networking/destination-rule/#LoadBalancerSettings-SimpleLB for most cases though. You can match on a header and send to a subset w/ that policy if you don'rt always want it

**Comment by imcom** [comment]
> I'd recommend you just use PASSTHROUGH lb https://istio.io/latest/docs/reference/config/networking/destination-rule/#LoadBalancerSettings-SimpleLB for most cases though. You can match on a header and send to a subset w/ that policy if you don'rt always want it

The EnvoyFilter worked for me thanks to @ramaraochavali . To be more precise, I used the `PASSTHROUGH` and EnvoyFilter together to achieve that the client could use the header to select an endpoint in upstream. 

On the other hand, IIUC just use `PASSTHROUGH` won't get me anywhere in k8s? Because the original destination would always be the ingress's IP:PORT. Am I getting something wrong here? @howardjohn
