### ISSUE TITLE
Pilot dashboard could use a refactoring

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#15193]
Current issues:

* Pilot pushes attempts to show errors and non errors, but you essentially will never see the errors due to the number of pushes. See https://github.com/istio/istio/pull/14929
* Errors dashboard has some issues where the push error type is not displayed properly https://github.com/istio/istio/pull/14929
* There is no consistent place for errors. We have a pilot errors panel and then 4 rejected _DS config panels. These can probably be consolidated into one.
* ADS Monitoring panel has just a bunch of stuff thrown together in one panel, much of it already exposed in other panels. This can be cleaned up a lot and make it more understandable.
* I'm not sure the EDS Instances panel is really useful.. its effectively the number of replicas of a service and has crazy cardinality. if anything, maybe we just show ones with zero instances?
* It should be made clear what metrics are from envoy's and which are from pilots. For example "Active Connections" is from envoy metrics, and in ADS Monitoring we have connected endpoints which is from Pilot.
* We should irate and rate together on one CPU graph with no distinction
* We should expose proxy convergence time. maybe some other metrics too, we should go through all of them and see what is useful and not on the dashboard.

I will work on this if I find some free time but wouldn't object if someone else picked it up

**Comment by douglas-reid** [comment]
@howardjohn thanks for putting together this list! the dashboard has been long overdue for a critical assessment. i'm happy to help get this in for 1.3. let's figure out a way to help make sure it gets done.

**Comment by howardjohn** [comment]
Sounds good. I've played around with the metrics a bit and look at the pilot dashboards all the time so I am definitely interested in doing this or helping do this

**Comment by howardjohn** [comment]
#15665
