### ISSUE TITLE
Metrics for Citadel agent

### ISSUE THREAD

**Issue by pitlv2109** [istio/istio#15205]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Collect more metrics from Citadel agent, such as latency, number of retries, success rate, etc. Some of the work has been done by @JimmyCYJ for SDS metrics. This is useful for perf tests and for users in general.

- [x] Switch to use OpenCensus instead of Prometheus as the metric collector (duplicated of #14362) 
- [x] Collect metrics from Citadel agent to other services (token exchange server and CA).
- [x] Collect metrics from Citadel agent to workload sidecars (most of it has been done by @JimmyCYJ for SDS metrics).
- [ ] Export metrics to Prometheus server so they can be queried.
 
**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[X] Performance and Scalability
[X] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by JimmyCYJ** [comment]
1. We first need to convert prometheus library to open census library https://github.com/istio/istio/pull/14854/files.
1. Then we need to set up config to export metrics to prometheus server.
1. Some metrics require code refactoring. We can list most interested metrics, walk through them, and work in parallel.
