### ISSUE TITLE
Why envoyFilter is not isolated by namespace?

### ISSUE THREAD

**Issue by ChangyuWang** [istio/istio#15216]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
* If a envoyfilter with incorrect configuration created, the entire mesh could be crashed. So, why not support isolated feature like virtualservice or sidecar ?

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[  X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
Envoyfilter is isolated by namespace (see https://github.com/istio/istio/issues/17414)
