### ISSUE TITLE
Remove call to exec kubectl in iop install command

### ISSUE THREAD

**Issue by ostromart** [istio/istio#15217]
Currently, there's a cmd.Exec call to kubectl to install manifests in iop install. This is a temporary measure to unblock usability testing of the CLI tool and should be removed when integration with the real controller kubeclient code is complete.

**Comment by elfinhe** [comment]
One possible solution: 
Switch to use istioctl/pkg/kubernetes/client.go, so we can have an unified kube client lib in both istioctl and operator.

**Comment by elfinhe** [comment]
@ostromart I am thinking about extending istio.io/istio/pkg/kubernetes/client to solve this issue, sounds good? or we have someone building operator specific 'kubeclient code' mentioned in the original post.

**Comment by ostromart** [comment]
Per discussion in your PR, we still really need kubectl features - kube client is not enough. In particular we need --prune. Parking this for now until k8s libs are available.

**Comment by ostromart** [comment]
We have a reasonably functional prune implementation now so we can revive this as part of the code de-duplication effort.

**Comment by ostromart** [comment]
Fixed in https://github.com/istio/istio/pull/23165.
