### ISSUE TITLE
Add Grafana dashboard for Citadel

### ISSUE THREAD

**Issue by Monkeyanator** [istio/istio#15228]
**Describe the feature request**
Other major Istio components have Grafana dashboards (galley, pilot, mixer) to visualize their core metrics. We collect metrics from Citadel but do not provide a pre-made default dashboard. Such a dashboard might be useful for some operators.

**Describe alternatives you've considered**
Incorporating the Citadel metrics into another dashboard (rather than creating a dedicated one), or just not having a default dashboard for Citadel.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by carolynhu** [comment]
@Monkeyanator as this issue have been solved and we also ported it over to istio/installer repo https://github.com/istio/installer/pull/326. I'm gonna to close this issue. Thanks.
