### ISSUE TITLE
Gateway Hosts Don't Match If Host Headers Include Port Number

### ISSUE THREAD

**Issue by AWSmith0216** [istio/istio#15221]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
A Gateway object's hosts list doesn't match against host headers that include a port

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Either the list of 'hosts' should match against just the host portion of the header, or the user be allowed to specify host entries with ports included.

**Steps to reproduce the bug**
This can be reproduced with slight modifications to the httpbin tutorial example. I did everything according to the tutorial, except in my environment I can add a DNS alias to my $INGRESS_HOST. I updated the Gateway and VirtualService objects to use that alias rather than the 'httpbin.example.com' one, so both of their host entries look like:

```
  hosts:
  - hostname.company.com
```
...where hostname.company.com is an alias to the $INGRESS_HOST. Also note that in my environment I don't have a functioning LoadBalancer, so I'm forced to use the $INGRESS_PORT 
(31380 default). I can then perform the following two curl calls:
```
# curl -I -HHost:hostname.company.com:80 http://hostname.company.com:31380/status/200
HTTP/1.1 200 OK

# curl -I -HHost:hostname.company.com http://hostname.company.com:31380/status/200
HTTP/1.1 200 OK
```

All is well. However, the following does not work:

```
# curl -I -HHost:hostname.company.com:31380 http://hostname.company.com:31380/status/200
HTTP/1.1 404 Not Found
```

How do I make the 31380 port work? Things I tried:

1. Set the 'hosts' value to '*'. This works, but obviously undesirable
2. Add a hosts entry to the Gateway such as 'hostname.company.com:31380'. This is rejected as an invalid domain name.

The host header that includes no port makes sense that it works. However, the host header that includes port 80 seems to be treated as special. Why does that match on the hosts list, while the header that includes a non-standard port doesn't?

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

istioctl version --remote
client version: 1.2.0
citadel version: 1.2.0
galley version: 1.2.0
ingressgateway version: 1.2.0
pilot version: 1.2.0
policy version: 1.2.0
sidecar-injector version: 1.2.0
telemetry version: 1.2.0
**How was Istio installed?**
Used helm to install the 1.2.0 release, default configuration

**Environment where bug was observed (cloud vendor, OS, etc)**
On premises install on RHEL 7.6 VMs

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
Maybe related, I think right now port 80 is a special case: https://github.com/istio/istio/pull/14346. @mbanikazemi what is the status on that pr? https://github.com/istio/istio/issues/14033

**Comment by silverReaperMaster** [comment]
host in gateway i think is been ignored as seen on #15262 
I'm hitting this issue also. 

Has some one been able to filter  directly by Host header ? would that work?

**Comment by silverReaperMaster** [comment]
host in gateway i think is been ignored as seen on #15262 
I'm hitting this issue also. 

Has some one been able to filter  directly by Host header ? would that work?

**Comment by yuzisun** [comment]
Is this issue still on track with 1.4 release ?
