### ISSUE TITLE
Errors are too cryptic in Istio operator

### ISSUE THREAD

**Issue by ostromart** [istio/istio#15225]
Much more work needs to be done to include context in the errors that are displayed to the user. Frequently, we are just returning err without wrapping any context around it which makes the error hard to track down.

**Comment by ayj** [comment]
@elfinhe will be working on this

**Comment by ostromart** [comment]
Just to clarify the work item a bit, the first step would be to understand what's missing. To do that, we should exercise a bunch of different error scenarios in using the tool:
- bad file path to CR file
- bad yaml in user CR
- unknown field in yaml
- bad value for type constrained field
- bad value in validated field (IP address list, port number etc -- see validate.go)
- bad path for k8s overlay 
Make sure the errors are clear and make it easy for the user to understand the problem.

**Comment by elfinhe** [comment]
looking at cmd/iop/shared.go / validate.go to see if I can identify those scenarios from err returned.
