### ISSUE TITLE
user gateways are not supported in values_types.go

### ISSUE THREAD

**Issue by ostromart** [istio/istio#15239]
values_types.go is supposed to be a schema for values.yaml. 
Currently, it does not support user defined gateways, which is possible when using helm directly. 
Either provide an unvalidated passthrough for user defined gateways or (better) figure out how to represent this in the existing Go structs. Preferably without a custom unmarshal if it can be avoided.

**Comment by ostromart** [comment]
It looks like for istio/installer charts there are no plans to support user gateways for 1.3, so lowering the priority on this.

**Comment by ostromart** [comment]
We're going to fix this in 1.5.

**Comment by howardjohn** [comment]
Another motivator: https://knative.dev/docs/serving/setting-up-custom-ingress-gateway/#step-3-update-gateway-configmap

knative has a recommended yaml for a custom gateway installation Istio 1.0 proxy

**Comment by ostromart** [comment]
Update: user gateways are still not in values_types (which is the validating schema for values) but since we now have an API for adding user gateways through IstioOperatorSpec, this is not an urgent problem. At worst, if users don't want to migrate to IOPS from values, we can give a workaround for this using unvalidatedValues.
