### ISSUE TITLE
rbac namespace-level access control not working

### ISSUE THREAD

**Issue by csantanapr** [istio/istio#15232]
**Bug description**

rbac namespace-level access control not working

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Followed the instructions in the section _Enforcing Namespace-level access control_
https://istio.io/docs/tasks/security/authz-http/#enforcing-namespace-level-access-control
And expect to be able to access the any of the bookinfo services going thru ingressgateway or from service to service.

**Steps to reproduce the bug**
Install bookinfo
```
kubectl label namespace default istio-injection=enabled
kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml
```
Install gateway
```
kubectl apply -f samples/bookinfo/networking/bookinfo-gateway.yaml
```
Install destination rules
```
kubectl apply -f samples/bookinfo/networking/destination-rule-all.yaml
```
Follow instructions in [Enforcing Namespace-level access control](https://istio.io/docs/tasks/security/authz-http/#enforcing-namespace-level-access-control)
```
kubectl apply -f samples/bookinfo/platform/kube/rbac/namespace-policy.yaml
```
Then
```
kubectl apply -f samples/bookinfo/platform/kube/rbac/namespace-policy.yaml
```

After waiting a while bookinfo productpage can't be access from browser using ingressgateway
```
open http://$GATEWAY_URL/productpage
```
You get `RBAC: access denied`
or
```
kubectl exec -it $(kubectl get pod -l app=ratings -o jsonpath='{.items[0].metadata.name}') -c ratings -- curl productpage:9080/productpage 

RBAC: access denied
```

While to troubleshoot I was able to change the subjects to allow any unauthenticated access
From:
```
subjects:
- properties:
     source.namespace: "istio-system"
- properties:
     source.namespace: "default"
```
To:
```
subjects:
- user: "*"
```
And then it works, so this narrows down that there is something wrong with `source.namespace` not working properly

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
latest `1.2.0`

**How was Istio installed?**
Using `kubectl`
```
#Install Istio CRDs
for i in install/kubernetes/helm/istio-init/files/crd*yaml; do kubectl apply -f $i; done


# Install Istio Evaluation
kubectl apply -f install/kubernetes/istio-demo.yaml
```
**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive]
[istio-dump.tar.gz](https://github.com/istio/istio/files/3341412/istio-dump.tar.gz)

**Comment by yangminzhu** [comment]
`source.namespace` requires mTLS to be enabled, I think `istio-demo.yaml` doesn't enable mTLS by default. See https://istio.io/docs/tasks/security/authz-http/#before-you-begin.

**Comment by csantanapr** [comment]
Yes I enabled mTLS as and enable rbac as instructions say in the page 

I did this also:
$ kubectl apply -f samples/bookinfo/platform/kube/rbac/rbac-config-ON.yaml

**Comment by yangminzhu** [comment]
Could you follow https://istio.io/docs/ops/security/debugging-authorization/ to debug this? It would be very helpful to debug the issue if you can attach the logs from each step. Thanks.

**Comment by csantanapr** [comment]
I’m currently on PTO but I will double check and try to debug and attach logs when I return. 

Does this works for you?

**Comment by yangminzhu** [comment]
@csantanapr Sure, thank you!

**Comment by csantanapr** [comment]
I got back from PTO 🏖 😃 

Re tried again today using 1.2.2 and I can confirm that strict mode for mTLS is required on the destination services to be able to have RBAC to be able to work

Minimum fix after trying many permutations on installing with permissive and strict mTLS is to install the destination rules for the bookinfo with mTLS strict
```
kubectl apply -f samples/bookinfo/networking/destination-rule-all-mtls.yaml
```
It doesn't matter how it was istio was installed.

PS: I tried the steps in [debugging-authorization](https://istio.io/docs/ops/security/debugging-authorization/) super 😎 the ability to have an UI to adjust the log levels and set to debug per component, I might steal the idea for knative 🤖 

thanks @yangminzhu for the quick look into this.
