### ISSUE TITLE
Automatic sidecar injection failing after re-installed

### ISSUE THREAD

**Issue by aanoaa** [istio/istio#15234]
**Bug description**

couldn't deploy application on namespace which is `istio-injection` label enabled.
when this error occurs, no log message `sidecar-injector-webhook`.

~~[Manual sidecar injection](https://istio.io/docs/setup/kubernetes/additional-setup/sidecar-injection/#manual-sidecar-injection) is working.~~

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

```
$ kubectl get namespace -L istio-injection
NAME            STATUS   AGE     ISTIO-INJECTION
default         Active   8d      enabled

$ kubectl apply -f https://k8s.io/examples/admin/dns/busybox.yaml
pod/busybox created
```

**Steps to reproduce the bug**

but, when I was trying

```
$ kubectl apply -f https://k8s.io/examples/admin/dns/busybox.yaml
Error from server (InternalError): error when creating "https://k8s.io/examples/admin/dns/busybox.yaml": Internal error occurred: failed calling admission webhook "sidecar-injector.istio.io": Post https://istio-sidecar-injector.istio-system.svc:443/inject?timeout=30s: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

test manually, got response.

```
$ kubectl exec -ti alpine -- curl -k -X POST https://istio-sidecar-injector.istio-system.svc:443/inject?timeout=30s
no body found

# sidecar-injector-webhook log.
# 2019-06-29T14:06:38.092294Zu0009erroru0009no body found
```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

```
$ istioctl version
client version: 1.2.2
citadel version: 1.2.2
galley version: 1.2.2
ingressgateway version: 1.2.2
pilot version: 1.2.2
policy version: 1.2.2
sidecar-injector version: 1.2.2
telemetry version: 1.2.2
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-eks-d69f1b", GitCommit:"d69f1bf3669bf00b7f4a758e978e0e7a1e3a68f7", GitTreeState:"clean", BuildDate:"2019-02-28T20:26:10Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

```
$ kubectl api-versions | grep admissionregistration
admissionregistration.k8s.io/v1beta1
```

**How was Istio installed?**

```
$ export ISTIO_VERSION=1.2.2
$ helm repo add istio.io https://storage.googleapis.com/istio-release/releases/$ISTIO_VERSION/charts/
$ helm repo update
$ curl -L https://git.io/getLatestIstio | sh -
$ cd ./istio-$ISTIO_VERSION/
$ export PATH=$PWD/bin:$PATH
$ kubectl create namespace istio-system
$ helm install install/kubernetes/helm/istio-init --name istio-init --namespace istio-system
$ helm install install/kubernetes/helm/istio --name istio --namespace istio-system
$ kubectl label namespace default istio-injection=enabled
```

**Environment where bug was observed (cloud vendor, OS, etc)**

amazon EKS

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by aanoaa** [comment]
this is happened when i was uninstall then install again.
at first time, <https://istio.io/docs/examples/bookinfo/> was working.

but now, all example pods can't starting.

    $ kubectl describe replicaset productpage-v1-689ff955c6
    ...
    Events:
      Type     Reason        Age                 From                   Message
      ----     ------        ----                ----                   -------
      Warning  FailedCreate  2m (x2 over 2m30s)  replicaset-controller  Error creating: Internal error occurred: failed calling admission webhook "sidecar-injector.istio.io": Post https://istio-sidecar-injector.istio-system.svc:443/inject?timeout=30s: dial tcp 10.0.102.238:443: i/o timeout
      Warning  FailedCreate  28s (x7 over 5m)    replicaset-controller  Error creating: Internal error occurred: failed calling admission webhook "sidecar-injector.istio.io": Post https://istio-sidecar-injector.istio-system.svc:443/inject?timeout=30s: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by aanoaa** [comment]
manual sidecar injection failed.

    $ istioctl kube-inject -f samples/sleep/sleep.yaml | kubectl apply -f -
    serviceaccount/sleep unchanged
    service/sleep created
    deployment.extensions/sleep created
    
    $ kubectl describe replicaset -l app=sleep
    ...
    Conditions:
      Type             Status  Reason
      ----             ------  ------
      ReplicaFailure   True    FailedCreate
    Events:
      Type     Reason        Age               From                   Message
      ----     ------        ----              ----                   -------
      Warning  FailedCreate  3s (x2 over 33s)  replicaset-controller  Error creating: Internal error occurred: failed calling admission webhook "sidecar-injector.istio.io": Post https://istio-sidecar-injector.istio-system.svc:443/inject?timeout=30s: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by markuszm** [comment]
Most likely this is related to #13762 and #13840 as in these issues, sidecar injector is also restarted and admisson hooks are failing afterwards.
In all these issues this one included, EKS is used and this issue here is also using EKS. 

Does your issue with sidecar injection also fix itself after around 20 minutes?

**Comment by aanoaa** [comment]
still failing.

**Comment by aanoaa** [comment]
i think this would be my mistake.
but not sure, the failing cluster already destroyed.

when i was create a new cluster with same terraform files,
the security group which belongs to worker node only allows port 1025 ~ 63353.

fix the security group rules(allow 443 port between subnet) then it works.

i guess the first installation,
the sample app pod and istio-sidecar-injector pod seem to have been run on the same node.

thanks.
