### ISSUE TITLE
Multi-cluster install

### ISSUE THREAD

**Issue by ostromart** [istio/istio#15246]
Support a basic recommended case of multi-cluster installation. This includes docs for user experience, modifications to the API and code to perform any required actions when iop install is run with a multi-cluster CR defined.

**Comment by ayj** [comment]
See https://docs.google.com/document/d/1ZwZ4KrE2pvcrdE1FVLke6ZMIAfC3y8_SYTzk6K2U9aQ for a proposed multi-cluster operator/CLI
