### ISSUE TITLE
istio.io docs for operator CLI mode

### ISSUE THREAD

**Issue by ostromart** [istio/istio#15242]
Create user facing docs for the istio.io website.

**Comment by esnible** [comment]
FYI: Operator CLI reference at https://docs.google.com/document/d/16SWW14zrwFKc9OzH6biMQD1u9INllzMa56jde9vgQkM

**Comment by ostromart** [comment]
We now have an tech writer (Adam Miller) that will own this item, based on the draft material I've created. This issue is now moved to istio/istio.io https://github.com/istio/istio.io/issues/4744
