### ISSUE TITLE
Migrate operator repo to Go modules

### ISSUE THREAD

**Issue by ostromart** [istio/istio#15240]
We are still using dep and should switch to Go modules.

**Comment by kramerul** [comment]
I tried to create a PRs. But unfortunately, I have no permission to do so.

My PR is located here https://github.com/ConcourseWdf/operator/tree/go-modules.

**Comment by ostromart** [comment]
Hi Ulrich, thanks for tackling that. I don't think you need special permissions to create a PR, only approve and merge. I suggest trying the following workflow:
- clone istio.io/operator, call your repo origin 
- create your branch for the work
- commit the work and push to origin <your branch>
This will create a PR in your repo. When you go to github, it should invite you to create a PR against istio/operator.

**Comment by kramerul** [comment]
Hi @ostromart,
that's exactly what I did. For the last step, I get a HTTP 405.

![image](https://user-images.githubusercontent.com/13213351/60565057-529eb780-9d62-11e9-91fa-941e95db212f.png)

**Comment by richardwxn** [comment]
@kramerul Hi Ulrich, I try to help create a PR from your fork and also got a 405. Is it because pr size issue?

**Comment by ericvn** [comment]
Assigning to @richardwxn so no one grabs the issue to work as this one looks underway.

**Comment by ostromart** [comment]
Looks to be working now.
