### ISSUE TITLE
Semantic validations for new API and values.yaml

### ISSUE THREAD

**Issue by ostromart** [istio/istio#15248]
The current validations are very bare-bones and are just a simple syntax and schema check. While this is a big improvement over helm, we want to go even further and prevent cases of incompatible parameters, questionable values and just in general a lint-like functionality to help users find errors in their config.

**Comment by elfinhe** [comment]
@sushicw 
I guess we can call analyzer against the ICPS. wdyt?

**Comment by sushicw** [comment]
Sorry, I'm not familiar with ICPS as a term. 

General recommendations for validating CRDs:

For single-resource validation checks, you'll want to add them to https://github.com/istio/istio/blob/master/pkg/config/validation/validation.go. These get run both by analyzers and also the validation webhook. 

For checks that require looking at multiple resources at once, OR that you want to emit warnings but not block on, write an analyzer. (These are NOT called by the validation webhook).  https://github.com/istio/istio/blob/master/galley/pkg/config/analysis/README.md
