### ISSUE TITLE
Create a release process

### ISSUE THREAD

**Issue by ostromart** [istio/istio#15247]
Operator is intended to be released alongside Istio, since it has compiled-in charts and a behavioral dependency on Istio. 
Some open question include:
- should charts be released separately as an install package for an operator, since it's possible to specify an URL target for the charts? This will eliminate need to constantly upgrade the operator binary to get latest charts but requires work in operator itself to understand chart versions.
- which compiled-in versions should be included per released version?
- release independently or always as a part of istioctl?

**Comment by howardjohn** [comment]
May need some coordination with https://github.com/istio/istio/issues/15207

**Comment by ostromart** [comment]
Just had a meeting with @howardjohn, @utka and @richardwxn, here's what we decided:
- operator will be released as part of istioctl so it will be included in the istio release.
- istio/installer will create release branches 1:1 with istio
- istio/operator will also create 1:1 release branches to create the release tars (these need profile files and some version info) - these will come from the installer repo @ the same version
- istio release will copy the charts and profiles from operator @ the same version and bundle them as part of the release image.

**Comment by howardjohn** [comment]
Is this done?

**Comment by ostromart** [comment]
Yes, through 
https://github.com/istio/istio/pull/16208
https://github.com/istio/operator/pull/190
https://github.com/istio/operator/pull/196
https://github.com/istio/operator/pull/195
https://github.com/istio/operator/pull/216
