### ISSUE TITLE
ingressgateway can't access http service with TLS termination

### ISSUE THREAD

**Issue by rkamisetti792** [istio/istio#15252]
Bug description
I tried to set up a gateway and virtual service for an http service.
used SIMPLE mode for the TLS termination in gateway
And the http service return upstream connect error or disconnect/reset before headers. reset reason: connection failure
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: sample-tls-gateway
spec:
  selector:
    istio: ingressgateway 
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
    hosts:
    - "*.example.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sample-tls-vs
spec:
  hosts:
  - "*.example.com"
  gateways:
  - sample-tls-gateway
  http:
  - match:
    - uri:
        prefix: /console
    route:
    - destination:
        port:
          number: 80
        host: sample
    retries:
      attempts: 3
      perTryTimeout: 2s
      retryOn: gateway-error,connect-failure,refused-stream

**Comment by howardjohn** [comment]
Duplicate of https://github.com/istio/istio/issues/13578
