### ISSUE TITLE
Pilot agent won't start if SDS is used for control-plane security.

### ISSUE THREAD

**Issue by costinm** [istio/istio#15268]
Epic: https://github.com/istio/istio/issues/15267

Issue: if controlPlaneAuthPolicy is enabled, but SDS is used to communicate with Pilot - the sidecar will keep looking for mounted certificates. 

Desired behavior, taking into account 'upgrade' and gradual adoption: 
- Pilot agent should verify that the SDS UDS path exists:
-- use SDS_PATH environment variable, with a list of ":" separated paths ( like CLASSPATH or GOPATH).
-- if SDS_PATH is not specified, default to '/var/run/sds/uds_path'
- if any of the paths in SDS_PATH exists ( file.exists ) - do not monitor /etc/certs and don't delay the startup until /etc/certs is populated.
- include the SDS path that was found in the "metadata" that is passed to pilot. 

Same thing for SDS_TOKEN_PATH - with the default set to 
'/var/run/secrets/tokens/istio-token:/var/run/secrets/kubernetes.io/serviceaccount/token'

The defaults are matching the default installation option for Istio.

**Comment by quanjielin** [comment]
most change in pilot agent was in my original https://github.com/istio/istio/pull/13593, difference is using env var instead of proxy argument. 

btw, why sds_path and sds_token_path are list of string(instead of one), what's pilot expected behavior is multiple values are set ? only first value is used or generate multiple sdsconfig ? if later, how to match uds path/token path, do we plan to support one envoy fetch certs from different services(on same node) , does that work ?

**Comment by costinm** [comment]
List of paths for UDS is P2 - it's fine to have only one, with the default set. The use case is support of other SDS providers, like the SPIRE agent (or other SDS implementations). Technically we can map whatever host paths they have to a constant name.

For token - the point is to verify if the 'trustworthy' token is set first, and if yes use it. Otherwise fall back to the less secure token. And for VMs - they may get tokens from different locations. So that would be P1 or P0 for usability. 

Yes, it is possible for some workloads to use a different SDS provider - in cases of upgrades, migrations, etc. There is a document in Env WG discussing safe upgrade - anything that relies on a global needs to be fixed, and the fact SDS server has a fixed UDS path is a problem. If users want to test a new version of the SDS provider, or a different implementation - they would run them side-by-side, and annotate the 
test workloads to use the new one.

**Comment by costinm** [comment]
I left few additional comments on #13593 - if you can create a separate PR with just the pilot-agent changes (i.e. check if UDS and which token exist, pass to pilot - without the additional setup complexity and risks) we can probably have the fix merged sooner.

**Comment by quanjielin** [comment]
sounds like a plan, I will create a new PR only for pilot-agent first; then we may change pilot code where sdsconfig is constructed, replacing global flag with sds related values passed by pilot-agent.  

sg we should make uds path/token path configurable for each sidecar, IMO it's fine to just pass a single string env var(both uds path/token path) to pilot-agent and let sidecar injector to handle the value to set, trustworthy jwt is injected by sidecar injector, so let sidecar injector to handle this align better; single value simply logic in pilot agent, and support the use cases(ex point to different sds provider, choose which token to use)

**Comment by costinm** [comment]
I don't think we have a use case to making it configurable - the problem we have is that we have far too much complexity in configuring and troboubleshooting. I am ok with having an env var to override the path for testing or VMs or special cases - but it must have a default value and by default should just work.  If it is ok to use /etc/certs as a fixed path ( with some env to override that we added recently ) - it should be the same for the uds path. 

Simpler is better. 

For tokens - we certainly need to check both locations, if the 'trustworthy' JWT is installed we use it otherwise the old k8s one. Again - the second is hardcoded anyways, and hardcoding the first is not 
a problem, just like we hardcode the location of the certs. Any injector or tool using a different kind of token can just place it in the specified location.

**Comment by costinm** [comment]
So the minimum requirements for pilot-agent are:
- check the hardcoded UDS path. If file is present - send it to pilot as metadata.
- check a hardcoded list of 2 tokens. First found - send it to pilot as metadata.
 
Optional:
- env variable to override the hardcoded UDS path. We can add it later (in 1.4).
- env variable to override the search path for tokens

For SPIRE agent ( or other agents  that authenticate pod by UDS socket, and don't need token ) - 
we will still enable SDS if only the UDS path is sent to pilot.

**Comment by quanjielin** [comment]
this is done.
