### ISSUE TITLE
Citadel configuration option on which tokens to accept

### ISSUE THREAD

**Issue by costinm** [istio/istio#15269]
Epic: #15267

Currently Istio injection and pilot can be configured to use either the weak, long lived, unscoped k8s token or the new token type that expires, has audience - but is not supported in all k8s environments. 

However Citadel doesn't appear to have any documented option in values.yaml to 
enable/disable either of those tokens.

It is not clear if the default installation in 1.2 ships with Citadel configured to generate certs
based on un-scoped k8s token - if it does it will need to be disabled by default, and we should
have some test that Citadel by default never allows generation of certificates with the less
secure token ( unless user explicitly selected this option when citadel is installed ). The
rest of the sds settings for pilot or injector have no effect since user can use its own commands
to communicate with Citadel.

**Comment by myidpt** [comment]
values.yaml has flags to enable using trust-worthy JWT:
https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/values.yaml#L448
Yes, I think we are missing the document about how to enable it.

The default installation of 1.2 allows Citadel to generate certs based on either the un-scoped or trustworthy JWT. I agree that by default Citadel should not generate certs based on the un-scoped JWT. I will try to fix that this week.

**Comment by costinm** [comment]
The flags to enable trust-worthy JWT exist - but don't apply to Citadel. Same for the flag to use un-trustworthy.

**Comment by fpesce** [comment]
A reminder here: please submit your fixes to master and cherrypick to 1.2 :
- master is going to be branched for 1.3 in a few weeks, and fixes will automatically land to 1.3 and further.

If your fix happens after that branch creation [planned for August 13th](https://discuss.istio.io/t/action-required-please-move-issues-for-1-3-to-the-1-3-milestone/3022) , you will have to cherrypick to 1.3 and 1.2
