### ISSUE TITLE
when use curl command to visit 'httpbin.org'  in pod, it shows 'Could not resolve host: httpbin.org'

### ISSUE THREAD

**Issue by zhaofengcumt** [istio/istio#15279]

**Comment by howardjohn** [comment]
This sounds like a DNS issue.

Can you run `nslookup httpbin.org` and `nslookup google.com`?

Can you `curl httpbin.org` from pods without a sidecar and it fails from pods in a sidecar?

Can you provide some more info?

**Comment by howardjohn** [comment]
Issue is abandoned. Please add follow up information if you are still seeing this
