### ISSUE TITLE
istio-autogenerated-k8s-ingress gateway conflicts with other gateways

### ISSUE THREAD

**Issue by perrymana** [istio/istio#15277]
**Bug description**
I’m trying to setup autogenerated Lets Encrypt certificates using cert-manager in an Kubernetes Istio environment. There seems to have been a lot of discussion on this and many improvements on how certificates are managed and reloaded, but very few documented outcomes on how to specifically setup cert manager to achieve this. There is of course the tutorial, [Kubernetes Ingress with Cert-Manager](https://istio.io/docs/tasks/traffic-management/ingress/ingress-certmgr/), that looks promising, and does work in the trivial example provided, but doesn’t appear to work for non-trivial scenarios.

I was initially having problems getting the tutorial to work until I started with a clean fresh Kubernetes cluster, with some further digging it appears the “magic” istio-autogenerated-k8s-ingress gateway conflicts with other gateways you might have setup, and it depends on the order they were applied as to which one works, the other giving a 404 error.

There doesn’t appear to be any further documentation or guidance on how (or if!?) the istio-autogenerated-k8s-ingress gateway should be used in more complicated scenarios. Is this by design? Is this a bug?

Ideally I want to use istio Gateways and Virtual Services for all my normal endpoints, and only use the k8s Ingress records for when cert-manager needs to solve a challenge. On the surface this would appear to be possible if the istio-autogenerated-k8s-ingress gateway worked along-side other gateways.

**Affected product area**
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behaviour**
When I have both a istio-autogenerated-k8s-ingress Gateway & Ingress (on host A) and another Gateway & Virtual Service (on host B) I expect both to route traffic to the backend service.

**Steps To Reproduce**
* Start with a clean Kubernetes Cluster
* Run through the tutorial (https://istio.io/docs/tasks/traffic-management/ingress/ingress-certmgr/)
* At this point I have hello world responding on both http/https at (for example) `http://ingress-certmgr-example.mydnsexample.com/hello`
* Now add a “normal” Gateway and Virtual Service to expose the same hello world service on a different hostname, `http://helloworld-example.mydnsexample.com/hello`

```
$ cat <<EOF | kubectl apply -f -
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: helloworld-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - helloworld-example.mydnsexample.com
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: helloworld
spec:
  hosts:
  - helloworld-example.mydnsexample.com
  gateways:
  - helloworld-gateway
  http:
  - match:
    - uri:
        exact: /hello
    route:
    - destination:
        host: helloworld
        port:
          number: 5000
---
EOF
```

* Now trying to navigate to my new hostname, `http://helloworld-example.mydnsexample.com/hello` (just on http) fails with a 404 as the autogenerated gateway seems to take precedence.
* If I then delete the istio-autogenerated-k8s-ingress, I can now get to my new hostname:
`kubectl delete gateway -n istio-system istio-autogenerated-k8s-ingress`

**Version**
$ istioctl.exe version --remote
client version: 1.2.0
citadel version: 1.2.0
galley version: 1.2.0
ingressgateway version: 1.2.0
pilot version: 1.2.0
policy version: 1.2.0
sidecar-injector version: 1.2.0
telemetry version: 1.2.0

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
As per tutorial

**Environment**
AKS

**Comment by jeinwag** [comment]
Also currently struggling with this (on Istio 1.4.0). 
If the istio-autogenerated-k8s-ingress is there, I can't geht HTTP to work on any custom gateway. 
When I delete the istio-autogenerated-k8s-ingress, ingress resources of the istio ingress-class stop working.

**Comment by carpenike** [comment]
Should this be re-opened? Also having this same problem.

**Comment by Trojaner** [comment]
I have the same issue

**Comment by spacejam101** [comment]
Same here

**Comment by pjmorr** [comment]
I am also seeing this issue on a fresh install while going through the istio tutorials.  Is there no feedback that can be provided?  This issue is over a year old without any comment other than 'me too'...

**Comment by LeonardoBonacci** [comment]
me too
