### ISSUE TITLE
TestMTlsWithAuthNPolicy is broken in presubmit

### ISSUE THREAD

**Issue by yangminzhu** [istio/istio#15276]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
See https://k8s-testgrid.appspot.com/istio-presubmits-master#pilot-e2e-envoyv2-v1alpha3&width=20

```
=== RUN   TestMTlsWithAuthNPolicy
2019-07-01T23:52:40.996896Z	info	Running command kubectl get MeshPolicy default -n default -o yaml --kubeconfig= --export
2019-07-01T23:52:41.324308Z	info	Command output: 
Flag --export has been deprecated, This flag is deprecated and will be removed in future.
apiVersion: authentication.istio.io/v1alpha1
kind: MeshPolicy
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"authentication.istio.io/v1alpha1","kind":"MeshPolicy","metadata":{"annotations":{},"labels":{"app":"security","chart":"security","heritage":"Tiller","release":"istio"},"name":"default","namespace":""},"spec":{"peers":[{"mtls":{"mode":"PERMISSIVE"}}]}}
  generation: 1
  labels:
    app: security
    chart: security
    heritage: Tiller
    release: istio
  name: default
  selfLink: /apis/authentication.istio.io/v1alpha1/meshpolicies/default
spec:
  peers:
  - mtls:
      mode: PERMISSIVE
2019-07-01T23:52:41.324611Z	info	Running command kubectl delete -f /tmp/kubedelete807161404.yaml --kubeconfig=
2019-07-01T23:52:41.382309Z	info	Command output: 
error: error parsing /tmp/kubedelete807161404.yaml: error converting YAML to JSON: yaml: line 2: mapping values are not allowed in this context
2019-07-01T23:52:41.382382Z	info	Command error: exit status 1
--- FAIL: TestMTlsWithAuthNPolicy (5.39s)
    authn_policy_test.go:49: command failed: "error: error parsing /tmp/kubedelete807161404.yaml: error converting YAML to JSON: yaml: line 2: mapping values are not allowed in this context\n" exit status 1

```

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[x] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by yangminzhu** [comment]
From the log, it seems it failed with `authn_policy_test.go:49: command failed: "error: error parsing /tmp/kubedelete807161404.yaml: error converting YAML to JSON: yaml: line 2: mapping values are not allowed in this context\n" exit status 1
`

cc @nmittler @ozevren in case you know some changes in the test framework that might be related to this.

**Comment by ozevren** [comment]
e2e tests are using the old framework not the new one.

**Comment by yangminzhu** [comment]
@ozevren It's actually caused by `--export` being deprecated in kubectl: https://github.com/kubernetes/kubernetes/pull/73787, Let me see if https://github.com/istio/istio/pull/15278 will fix it.
