### ISSUE TITLE
Operator should produce manifests that are diffable - in a consistent way

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#15273]
At present a textual diff between `iop manifest` and `iop manifest -f custom.yaml`  is enormous. The reason is that the manifests are produced in a non-repeatable way. Most likely this is due 
* Raging over Maps inside the code without sorting
* merging slices in an inconsistent way.

You can use 
`istio.io/istio/bin/diff_yaml.py` to see what the actual differences.

**Comment by ayj** [comment]
@morvencao, is this issue addressed by https://github.com/istio/istio/issues/15534?

**Comment by morvencao** [comment]
@ayj Correct.

**Comment by ostromart** [comment]
Note that the command has changed from "iop" to "mesh" per the README.

**Comment by stewartbutler** [comment]
I've created a PR over on the istio/operator repository that should fix this (https://github.com/istio/operator/pull/249).
