### ISSUE TITLE
HELM: istio-sidecar-injector istio-1.2.2

### ISSUE THREAD

**Issue by vitalijsvolodenkovsmagebit** [istio/istio#15288]
After upgrading istio from 1.1 to 1.2 we have issue with istio-sidecar-injector Configmap.
You have changed template to "{{ .Files.Get "files/injection-template.yaml" | indent 6 }}"
For .Files.Get. function rendering is not working as result sidecar injector is not working as well. 
From istio-sidacat-injector logs:
2019-07-02T11:39:57.005122Z	info	Policy: enabled
2019-07-02T11:39:57.005128Z	info	AlwaysInjectSelector: []
2019-07-02T11:39:57.005132Z	info	NeverInjectSelector: []
2019-07-02T11:39:57.005198Z	info	Template: |
  rewriteAppHTTPProbe: {{ valueOrDefault .Values.sidecarInjectorWebhook.rewriteAppHTTPProbe false }}
  {{- if or (not .Values.istio_cni.enabled) .Values.global.proxy.enableCoreDump }}
  initContainers:
  {{ if ne (annotation .ObjectMeta `sidecar.istio.io/interceptionMode` .ProxyConfig.InterceptionMode) `NONE` }}
  {{- if not .Values.istio_cni.enabled }}
  - name: istio-init
  {{- if contains "/" .Values.global.proxy_init.image }}
....
2019-07-02T12:04:10.221921Z	info	Injection data: err=template: inject:27:92: executing "inject" at <ne .Values.global.pr...>: error calling ne: invalid type for comparison spec=

As workaround is to move and modify content of files/injection-template.yaml  to templates/sidecar-injector-configmap.yaml 

helm version
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}

**Comment by howardjohn** [comment]
I just updated to Helm `2.14.1` like you have and I am not seeing this error.


It seems to be caused by https://github.com/istio/istio/blob/f9394255ea6eacdb71bc96704e8029aa199d8f8c/install/kubernetes/helm/istio/files/injection-template.yaml#L27

I am suprised moving the file does anything.. it should be the same.

Can you add the output of `kubectl -n istio-system get cm istio-sidecar-injector`

**Comment by vitalijsvolodenkovsmagebit** [comment]
I have removed version 1.2.2. 
But as I said, in files/injection-template.yaml you have:
rewriteAppHTTPProbe: {{ valueOrDefault .Values.sidecarInjectorWebhook.rewriteAppHTTPProbe false }}
{{- if or (not .Values.istio_cni.enabled) .Values.global.proxy.enableCoreDump }}
and so on
This values(for example, .Values.global.proxy.enableCoreDump) will not be rendered by .Files.Get. (https://github.com/helm/helm/blob/master/docs/chart_template_guide/accessing_files.md)

**Comment by howardjohn** [comment]
It does get templated still, in the sidecar injector not by helm. The sidecar injector gets .Values passed to it.

> As workaround is to move and modify content of files/injection-template.yaml to templates/sidecar-injector-configmap.yaml

Did this actually work or did you just downgrade? Because there are all sorts of custom functions and things we add to the injector templating that aren't in Helm, not to mention things like `.ProxyConfig.ConfigPath` which helm doesn't know about, so I would suspect it wouldn't work

**Comment by vitalijsvolodenkovsmagebit** [comment]
Ok, I will try to upgrade once more tomorrow

**Comment by vitalijsvolodenkovsmagebit** [comment]
I will upgrade istio in 5 min, I will give you info in 15 min

**Comment by vitalijsvolodenkovsmagebit** [comment]
kubectl -n istio-system get cm istio-sidecar-injector -o yaml > istio-sidecar-injector

**Comment by vitalijsvolodenkovsmagebit** [comment]
[istio-sidecar-injector.txt](https://github.com/istio/istio/files/3351798/istio-sidecar-injector.txt)

**Comment by vitalijsvolodenkovsmagebit** [comment]
Warning from replica set side:
  Warning  FailedCreate  25s (x42 over 8h)  replicaset-controller  Error creating: Internal error occurred: admission webhook "sidecar-injector.istio.io" denied the request: template: inject:27:92: executing "inject" at <ne .Values.global.pr...>: error calling ne: invalid type for comparison

Log from istio-sidecar-injector:
2019-07-02T18:29:19.485959Z	info	Injection data: err=template: inject:27:92: executing "inject" at <ne .Values.global.pr...>: error calling ne: invalid type for comparison spec=

**Comment by vitalijsvolodenkovsmagebit** [comment]
I have solved this issue, closing ticket for now.
Thank you for you time.
You are a good person ;)

**Comment by howardjohn** [comment]
Looks like you don't have `excludeOutboundPorts` in the values which is weird since its set as a default. Not sure how that happened

**Comment by vstrizaks** [comment]
On Istio 1.2.5 problem still present. vitalijsvolodenkovsmagebit can you please tell how you solved the issue?
