### ISSUE TITLE
ServiceEntry does not accept IPv6 Addresses and Endpoints

### ISSUE THREAD

**Issue by istionary** [istio/istio#15281]
**Bug description**

The ServiceEntry validator in pilot/pkg/model/validation.go only accepts 

- IPv4 subnets for Addresses
- IPv4 addresses for Endpoints

For example in https://github.com/istio/istio/blob/1.2.2/pilot/pkg/model/validation.go:

Lines 2321 – 2324 (2323):

```
for _, address := range serviceEntry.Addresses {
           cidrFound = cidrFound || strings.Contains(address, "/")
           errs = appendErrors(errs, **ValidateIPv4Subnet(address)**)
}
```

Lines 2357 – 2366 (2366):

```
for _, endpoint := range serviceEntry.Endpoints {
                addr := endpoint.GetAddress()
                if strings.HasPrefix(addr, UnixAddressPrefix) {
                      ...
                } else {
                      errs = appendErrors(errs, **ValidateIPv4Address(addr)**)

```
Attempts to use IPv6 Addresses or Endpoints results in the respective error messages from the ValidateIPv4... functions.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Being able to specify
- IPv6 subnets for Addresses
- IPv6 addresses for Endpoints

in a ServiceEntry yaml file.

**Steps to reproduce the bug**

Specify one or more
- IPv6 subnets for Addresses
- IPv6 addresses for Endpoints

in a ServiceEntry yaml file. Attempt to apply the file.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Istio 1.2.2 and earlier. See above for references to 1.2.2 source code.

**How was Istio installed?**
-
**Environment where bug was observed (cloud vendor, OS, etc)**
-

**Comment by howardjohn** [comment]
fyi @sbezverk

**Comment by howardjohn** [comment]
Part of https://github.com/istio/istio/issues/1756

**Comment by sbezverk** [comment]
@istionary  could you please share your ServiceEntry yaml, I will repro it and fix it.
