### ISSUE TITLE
HTTP Host is not checked by envoy proxy

### ISSUE THREAD

**Issue by tibetsam** [istio/istio#15291]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
The sidecar proxy of an application pod does not verify HOST:

kubectl exec -it $(kubectl get pod -l app=sleep -o jsonpath='{.items[0].metadata.name}') -c sleep -- curl httpbin:8000/headers -HHost:myhost.com
{
"headers": {
"Accept": "/",
"Host": "myhost.com",
"User-Agent": "curl/7.60.0"
}
}

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
domain should be checked.
**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
root@mastermint:~# istioctl version
client version: a6291603b7634a44a72f2af8f8efdc54b6a89a2a
citadel version: master-20190628-09-15
galley version: master-20190628-09-15
ingressgateway version: master-20190628-09-15
pilot version: master-20190628-09-15
policy version: master-20190628-09-15
sidecar-injector version: master-20190628-09-15
telemetry version: master-20190628-09-15

root@mastermint:~# kb version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
**How was Istio installed?**
helm install
**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by tibetsam** [comment]
@gyliu513 @vadimeisenbergibm could you please have a look into this issue? I saw you guys worked on https://github.com/istio/istio/issues/5995. Thanks a lot.

**Comment by vadimeisenbergibm** [comment]
@tibetsam Please note that in the passthru mode, the traffic is encrypted, so the HOST header and any other HTTP information can be seen by Envoy. So it cannot verify HOST.

**Comment by tibetsam** [comment]
@vadimeisenbergibm thanks a lot...you are right....that is encrypted and that's why we have SNI...stupid me...
And you mentioned that proxy is not validating HOST in HTTP neither, so it's an expected behavior? 
To me it's an bug for HTTP then.

**Comment by vadimeisenbergibm** [comment]
Yes, it seems it is an expected behavior for HTTP, see the output in https://github.com/istio/istio/issues/15291#issuecomment-508928851.

**Comment by tibetsam** [comment]
@vadimeisenbergibm  yes, i've checked your output. but it only tells me it is current behavior rather than expected behavior. what do you say ?

**Comment by vadimeisenbergibm** [comment]
You may want to rename the issue: Host names are not checked by application envoy proxy. Let's get the feedback of the community on this.

**Comment by tibetsam** [comment]
it's done. thanks for the suggestion.

**Comment by vadimeisenbergibm** [comment]
Could you please rewrite the first comment as well? It could be just:

> The sidecar proxy of an application pod does not verify HOST in case HTTP either:

> kubectl exec -it $(kubectl get pod -l app=sleep -o jsonpath='{.items[0].metadata.name}')  -c sleep -- curl httpbin:8000/headers -HHost:myhost.com
{
  "headers": {
    "Accept": "*/*", 
    "Host": "myhost.com", 
    "User-Agent": "curl/7.60.0"
  }
}

**Comment by howardjohn** [comment]
Are you suggesting on the inbound we reject traffic that doesn't match the host header?

**Comment by tibetsam** [comment]
@howardjohn  Yes.

**Comment by howardjohn** [comment]
This does not seem like a good idea.. does any server do this? A single pod can have 100s of services associated with it. How do you know what is a valid host and what isn't? What is the benefit of rejecting it?

**Comment by tibetsam** [comment]
If a single pod has 100s service, then it should use wildcard *. 
It will have same benefit as SNI validation for https.

**Comment by howardjohn** [comment]
What should use a wildcard? I should just be able to add Istio to a pod with associate services `foo` and `bar` and `curl foo` and `curl bar` work as before. Are you suggesting now the user needs to configure some virtual service or something with a wildcard?

**Comment by tibetsam** [comment]
sorry for confusing you. let me clarify here.

When I configure a virtual service for my bookinfo, I set hosts to "erenqgo.bookinfo.com". But in envoy config it is not reflected, the domain part is still wildcard "*", rather then "erenqgo.bookinfo.com".

apiVersion: v1
items:
- apiVersion: networking.istio.io/v1alpha3
  kind: VirtualService
  spec:
    **hosts:
    - erenqgo.bookinfo.com**
    http:
    - match:
      - uri:
          exact: /productpage
      - uri:
          prefix: /static
      - uri:
          exact: /login
      - uri:
          exact: /logout
      - uri:
          prefix: /api/v1/products
      route:
      - destination:
          host: productpage
          port:
            number: 9080

   "dynamic_active_listeners": [
    {
     "version_info": "2019-09-23T14:19:24Z/5",
     "listener": {
      "name": "2001:db8:10a:c6b1:81d1:2c15:bcb6:7a6e_9080",
      "address": {
       "socket_address": {
        "address": "2001:db8:10a:c6b1:81d1:2c15:bcb6:7a6e",
        "port_value": 9080
       }
      },
      "filter_chains": [
       {
        "filter_chain_match": {
         "application_protocols": [
          "istio"
         ]
        },
        "tls_context": {
         "common_tls_context": {
          "tls_certificates": [
           {
            "certificate_chain": {
             "filename": "/etc/certs/cert-chain.pem"
            },
            "private_key": {
             "filename": "/etc/certs/key.pem"
            }
           }
          ],
          "validation_context": {
           "trusted_ca": {
            "filename": "/etc/certs/root-cert.pem"
           }
          },
          "alpn_protocols": [
           "h2",
           "http/1.1"
          ]
         },
         "require_client_certificate": true
        },
        "filters": [
         {
          "name": "envoy.http_connection_manager",
          "config": {
           "server_name": "istio-envoy",
           "access_log": [],
           "http_filters": [
            {
             "config": {
              "policy": {
               "peers": [
                {
                 "mtls": {
                  "mode": "PERMISSIVE"
                 }
                }
               ]
              }
             },
             "name": "istio_authn"
            },
            {
             "name": "envoy.cors"
            },
            {
             "name": "envoy.fault"
            },
            {
             "name": "envoy.router"
            }
           ],
           "normalize_path": true,
           "route_config": {
            "name": "inbound|9080|http|productpage.erenqgo.svc.cluster.local",
            "validate_clusters": false,
            "virtual_hosts": [
             {
              "routes": [
               {
                "match": {
                 "prefix": "/"
                },
                "decorator": {
                 "operation": "productpage.erenqgo.svc.cluster.local:9080/*"
                },
                "route": {
                 "max_grpc_timeout": "0s",
                 "cluster": "inbound|9080|http|productpage.erenqgo.svc.cluster.local",
                 "timeout": "0s"
                }
               }
              ],
              **"domains": [
               "*"
              ],**
              "name": "inbound|http|9080"
             }
            ]
           }

**Comment by howardjohn** [comment]
Virtualservice is optional, what should happen if no virtual service is specified? It's a wildcard? Then you will get strange behavior when someone adds a virtual service and all of the sudden traffic breaks.

If you want to prevent traffic please use stuff like rbac or policies - I think this is not the right approach

**Comment by tibetsam** [comment]
yes, sure. we can do that in this way and do host check on gateway. thanks.
