### ISSUE TITLE
pilot ctlz listening on ipv4 in ipv6 cluster

### ISSUE THREAD

**Issue by tibetsam** [istio/istio#15290]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
i'm running istio in an ipv6 cluster. But when i check ports which pilot is listening. I found one of port(9876) is listening on ipv4 loopback.

root@mastermint:~/go/src/istio.io/istio# kb exec istio-pilot-557f858dc4-26d9v -nistio-system -- netstat -anp
Defaulting container name to discovery.
Use 'kubectl describe pod/istio-pilot-557f858dc4-26d9v -n istio-system' to see all of the containers in this pod.
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address Foreign Address State PID/Program name
tcp 0 0 127.0.0.1:9876 0.0.0.0:* LISTEN 1/pilot-discovery
tcp6 0 0 :::15014 :::* LISTEN 1/pilot-discovery
tcp6 0 0 :::8080 :::* LISTEN 1/pilot-discovery
tcp6 0 0 ::1:15000 :::* LISTEN -
tcp6 0 0 :::15003 :::* LISTEN -
tcp6 0 0 :::15005 :::* LISTEN -
tcp6 0 0 :::15007 :::* LISTEN -
tcp6 0 0 :::15010 :::* LISTEN 1/pilot-discovery
tcp6 0 0 :::15011 :::* LISTEN -
tcp6 0 0 fd01:0:0:2::437:8080 fd01:0:0:1:💯34150 TIME_WAIT -
tcp6 0 0 fd01:0:0:2::437:15014 fd01:0:0:2::43a:46162 ESTABLISHED 1/pilot-discovery
tcp6 0 0 fd01:0:0:2::437:15010 fd01:0:0:2::438:51976 ESTABLISHED 1/pilot-discovery
tcp6 0 0 fd01:0:0:2::437:15010 fd01:0:0:2::440:60154 ESTABLISHED 1/pilot-discovery
tcp6 0 0 fd01:0:0:2::437:43884 fd01:0:0:3::1:443 ESTABLISHED 1/pilot-discovery
tcp6 0 0 fd01:0:0:2::437:41802 fd01:0:0:3::d6dd:9901 ESTABLISHED 1/pilot-discovery
tcp6 0 0 fd01:0:0:2::437:8080 fd01:0:0:1:💯34472 TIME_WAIT -
Active UNIX domain sockets (servers and established)
Proto RefCnt Flags Type State I-Node PID/Program name Path
unix 2 [ ] DGRAM 1540721 - @envoy_domain_socket_parent_0@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
unix 2 [ ] DGRAM 1540720 - @envoy_domain_socket_child_0@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

after checking code, found out it comes from vendor/istio.io/pkg/ctrlz/options.go and the code itself looks good to me, using localhost rather than hard coded v4 loopback.
func DefaultOptions() *Options {
return &Options{
Port: 9876,
Address: "localhost",
}
}

of course in pilot /etc/hosts file localhost has both v4 and v6 addresses, but my question is in this case shouldn't ipv6 take precedence?
root@istio-pilot-557f858dc4-26d9v:/# cat /etc/hosts
**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
should listening on ::1
**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
root@mastermint:~/go/src/istio.io/istio# istioctl version
client version: a6291603b7634a44a72f2af8f8efdc54b6a89a2a
citadel version: master-20190628-09-15
galley version: master-20190628-09-15
ingressgateway version: master-20190628-09-15
pilot version: master-20190628-09-15
policy version: master-20190628-09-15
sidecar-injector version: master-20190628-09-15
telemetry version: master-20190628-09-15

**How was Istio installed?**
helm install
**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by tibetsam** [comment]
@sbezverk any ideas?

**Comment by howardjohn** [comment]
duplicate of https://github.com/istio/istio/issues/15290

**Comment by howardjohn** [comment]
I meant https://github.com/istio/istio/issues/15410
