### ISSUE TITLE
Develop and adopt templates for repositories' top-level README.md and DESIGN.md 

### ISSUE THREAD

**Issue by rcaballeromx** [istio/istio#15299]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Develop and adopt templates for the top level README.md and DESIGN.md files in all Istio repositories.

**Describe alternatives you've considered**
The top level README.md files that have been created so far are inconsistent in terms of what information they contain. This inconsistency has made it difficult for users to find the information they need. Contributors provide information on the components they develop on the README files in the code, add it to the tasks or topics of the operations guide on istio.io, include it in the API specs, or provide the information as blog posts. All these scattered sources of information make it harder for users to determine whether or not the information they've found is accurate and up-to-date. 

**Affected product area (please put an X in all that apply)**

[ X ] Configuration Infrastructure
[ X ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ X ] User Experience
[ ] Developer Infrastructure

**Additional context**
The goal is to provide contributors with clear guidance to be able to produce and maintain effective README and DESIGN files for the Istio repositories.

The Istio operator repo houses the latest example of a new README that would benefit from having a template, see https://github.com/istio/operator/pull/61

This issue is meant to track the work of developing the proposed templates and splitting the content for the operator's README and DESIGN files. Other issues will be needed for the work involved in adopting this approach to the other README files in the other repos.

The proposed template will focus on the information users expect to find in a README, very short and simple answers to the following questions:

- Why does the repo exist?
- What does the repo do?
- How can I contribute or participate? (A call to action)

Answering these questions aligns with technical writing best practices for overviews: https://goldydocs.netlify.com/docs/overview/
The goal is for the README template proposed here to adhere to these best practices.

Answering: How does the repo work? Should not be part of the README and instead be the contents of a DESIGN.md 
The goal is for the DESIGN template proposed here to adhere to the best practices for  conceptual documentation: https://goldydocs.netlify.com/docs/concepts/

Once the information is split consistently between README.md and DESIGN.md files, we can develop automation to pull the contents of the DESIGN.md files in all repos to populate a new Architecture section on istio.io/docs

**Comment by sdake** [comment]
sounds excellent, especially given the upcoming repository split.  If you make a template, I'll transition the installer repo to the new template(s).

Cheers
-steve
