### ISSUE TITLE
Can't access Kiali / Grafana with ingress on Azure AKS

### ISSUE THREAD

**Issue by sylus** [istio/istio#15296]
**Bug description**

Can't access Kiali / Grafana with ingress on Azure AKS. I can successfully port-forward without issue to both services so this is just related to ingress.

The following works:

```sh
kubectl port-forward -n istio-system $(kubectl get pod -n istio-system -l app=kiali -o jsonpath='{.items[0].metadata.name}') 20001:20001     
```

Everything is running:

```sh
❯ kubectl get po -n istio-system                                                                                                                                        
NAME                                      READY   STATUS      RESTARTS   AGE
grafana-67c69bb567-pp27t                  1/1     Running     0          19h
istio-citadel-58fc8bfb55-mk6rm            1/1     Running     0          19h
istio-galley-79595c6b67-j8pqr             1/1     Running     0          19h
istio-ingressgateway-844d87d84b-9jln5     2/2     Running     0          19h
istio-init-crd-10-fn7m2                   0/1     Completed   0          19h
istio-init-crd-11-p9cjv                   0/1     Completed   0          19h
istio-pilot-5489577b86-82pqr              2/2     Running     0          19h
istio-policy-776dcfb654-q2zmf             2/2     Running     4          19h
istio-sidecar-injector-6fd47fb7c8-xk8mz   1/1     Running     0          19h
istio-telemetry-5944bd454d-xt7jr          2/2     Running     4          19h
kiali-56f5c59f79-lnqh6                    1/1     Running     0          19h
prometheus-d8d46c5b5-dvwht                1/1     Running     0          19h
tiller-deploy-876cbc9-pk67n               1/1     Running     0          20h
```

But whenever I go to http://istio-kiali.xxxx.ca I get "upstream connect error or disconnect/reset before headers. reset reason: connection failure" and the https variant doesn't work at all and gives a time out.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

That http traffic for Kiali + Grafana will be redirected to https and that https is accessible over the ingress.

**Steps to reproduce the bug**

a) Install istio-init with Helm Chart
b) Install istio with Helm Chart
c) The following is what my values.yaml looks like for Istio on Azure AKS:

```sh
# Use a specific image
global:
  # tag: release-1.1-latest-daily

  k8sIngress:
    enabled: true
    enableHttps: true

  controlPlaneSecurityEnabled: true
  disablePolicyChecks: false
  policyCheckFailOpen: false
  enableTracing: false

  mtls:
    enabled: true

  outboundTrafficPolicy:
    mode: ALLOW_ANY

sidecarInjectorWebhook:
  enabled: true
  # If true, webhook or istioctl injector will rewrite PodSpec for liveness
  # health check to redirect request to sidecar. This makes liveness check work
  # even when mTLS is enabled.
  rewriteAppHTTPProbe: true

gateways:
  istio-ingressgateway:
    sds:
      enabled: true
    serviceAnnotations: {}

kiali:
  enabled: true
  contextPath: /
  ingress:
    enabled: true
    ## Used to create an Ingress record.
    hosts:
      - istio-kiali.govcloud.ca
    annotations:
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
      kubernetes.io/ingress.class: "istio"
    tls:
      # Secrets must be manually created in the namespace.
      # - secretName: kiali-tls
      #   hosts:
      #     - kiali.local

  dashboard:
    grafanaURL: https://istio-grafana.XXXX.ca

grafana:
  enabled: true
  contextPath: /
  ingress:
    enabled: true
    ## Used to create an Ingress record.
    hosts:
      - istio-grafana.XXXX.ca
    annotations:
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
      kubernetes.io/ingress.class: "istio"
    tls:
      # Secrets must be manually created in the namespace.
      # - secretName: grafana-tls
      #   hosts:
      #     - grafana.local

prometheus:
  enabled: true
```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

Helm Chart 1.1.8

**How was Istio installed?**

With Helm Chart

**Environment where bug was observed (cloud vendor, OS, etc)**

Azure AKS

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
I don't think you can access them over gateway out of the box, you need to follow https://istio.io/docs/tasks/telemetry/gateways/. Did you go through this already?

(I could be wrong, I have not done this before)

**Comment by sylus** [comment]
Yeah I gave that a go I did get the http one to work with just the http method and port but otherwise can't get the ingress with lets encrypt to work. Not super sure where am going wrong.

**Comment by gargnupur** [comment]
@sylus : did you get this working? can you share your config for exposing Kilali for https, to see where it can be going wrong?

Also, this is more of a question and not a bug, thus closing the bug and can you please take this conversation further on discuss.istio.io?
