### ISSUE TITLE
Configuring Gateway TLS for GoDaddy wildcard certs

### ISSUE THREAD

**Issue by sreenivasmrpivot** [istio/istio#15302]
I have enabled my cluster with self signed cert. The problem I have with it is, "Citadel signs it with its own root/chain". As a result of this, browsers are not able to identify my test1.example.com, test2.example.com etc as secured sites and prompts for exception.

I assume, to avoid this, I will have to plugin external CA as mentioned here. https://istio.io/docs/tasks/security/plugin-ca-cert/

I have my domain in GoDaddy. If I buy my wildcard cert *.example.com from GoDaddy, what files will they give me for download?
Where can I get the root cert and cert chain of GoDaddy which needs to be configured on Citadel?

Can I completely avoid Citadel configuration and use the chain in the 
tls:
    caCertificates: 

Any help is much appreciated.

**Comment by ZacharyJoswick** [comment]
I'm having a similar issue. I have a godaddy wildcard certificate and am using the tls simple mode. My browser (google chrome) is able to authenticate with the server as it already contains the intermediate certificates. However, curl and docker cannot access the server without manually installing the ca.crt onto my laptop.  If anyone has a better way to handle this I'm all ears.
