### ISSUE TITLE
enableNamespacesByDefault does not work properly

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#15309]
The current logic:

https://github.com/istio/istio/blob/9c1d128ed95e880922a82756f5555d12b2f72ae7/install/kubernetes/helm/istio/charts/sidecarInjectorWebhook/templates/mutatingwebhook.yaml#L26-L34

This doesn't do what is expected -- `name` cannot be used out of the box because matchExpressions only looks at labels and name is not (always, or by default) a label.

Because of this sidecar injector can never be created. 

This is following the steps at https://istio.io/docs/setup/kubernetes/install/helm/#option-1-install-with-helm-via-helm-template

**Comment by howardjohn** [comment]
This impacts istio/istio and istio/installer

**Comment by howardjohn** [comment]
not stale

**Comment by costinm** [comment]
Not very harmful, the entire webhook config is getting changed - I would wait until istiod and operator are more stable before looking at this. 

Easy to remove the name to avoid the confusion, but P4
