### ISSUE TITLE
Operator fails to compile

### ISSUE THREAD

**Issue by Niksko** [istio/istio#15317]
**Bug description**

Operator is failing to compile.

I seem to be able to fix this by calling 

```
go build -mod vendor -o $GOPATH/bin ./cmd/iop.go
```

However I'm pretty clueless about go modules so I'm not sure if adding this `-mod vendor` option is valid or not.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Compiles

**Steps to reproduce the bug**

```bash
go build -o $GOPATH/bin ./cmd/iop.go
go: finding k8s.io/helm/pkg/proto/hapi/chart latest
go: finding k8s.io/helm/pkg/timeconv latest
go: finding k8s.io/helm/pkg/engine latest
go: finding k8s.io/helm/pkg/chartutil latest
go: finding k8s.io/helm/pkg/proto/hapi latest
go: finding k8s.io/helm/pkg latest
go: finding k8s.io/helm/pkg/proto latest
# k8s.io/client-go/rest
../../../../pkg/mod/k8s.io/client-go@v11.0.0+incompatible/rest/request.go:598:31: not enough arguments in call to watch.NewStreamWatcher
        have (*versioned.Decoder)
        want (watch.Decoder, watch.Reporter)
```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

Istio operator repo at commit 905dd84e868a0b88c08d95b7ccf14d085d9a6f6b

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by kramerul** [comment]
The operator is not using go modules yet (#15240). 
For the moment you need to move your project to `$GOPATH/src/istio.io/operator`, ensure `GO111MODULE` environment variable is not set, and run `go build ./cmd/iop.go`.
This was working for me with commit 905dd84e868a0b88c08d95b7ccf14d085d9a6f6b.

**Comment by Niksko** [comment]
Apologies, I had removed `GO111MODULE=on` from my environment setup script, but it was being set elsewhere
