### ISSUE TITLE
ABORTED test is reported as passed on Github

### ISSUE THREAD

**Issue by yangminzhu** [istio/istio#15315]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
`prow/integ-security-k8s-presubmit-tests.sh` showed as passed in PR https://github.com/istio/istio/pull/15224 but actually it's aborted in prow: https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/15224/integ-security-k8s-presubmit-tests-master/2441

The PR gets merged even if it breaks some tests: https://github.com/istio/istio/pull/15314 

cc @utka 

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[X] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Aborted test should be treated as failed test

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
the test isn't required so it would have been merged anyways I think. Still very problematic that it was marked as a success when it didn't pass though.

**Comment by howardjohn** [comment]
Looks like the last run was marked as a success by prow
```
24f66e86-99eb-11e9-959d-9a93bcd038da   integ-security-k8s-presubmit-tests-master                 2441      presubmit    istio            istio        15224   4d          4d               success
f07b77fd-99df-11e9-9128-86fcf257fff4   integ-security-k8s-presubmit-tests-master                 2430      presubmit    istio            istio        15224   4d          4d               failure
```

The test pod isn't around anymore so hard to debug further. My guess is the node got killed and the failure wasn't properly reported because it got forcefully terminated -- I would expect it to default to failure in this case though, but I am not familiar with the internals to understand the behavior.

**Comment by howardjohn** [comment]
There has been many changes to this area that I don't think there is much we can do more here
