### ISSUE TITLE
tracing-jaeger: Add ability to specify different Jaeger storage backends in Istio Helm chart

### ISSUE THREAD

**Issue by chadlwilson** [istio/istio#15316]
**Describe the feature request**

The current tracing-jaeger chart doesn't appear to allow you to change the storage backend. In our case we would like to use an **elasticsearch** backend. (in our case an AWS ElasticCache outside the cluster). We can hack the chart to specify env vars to the `jaeger:all-in-one` container to do so, but it'd be nice if the chart had an abstraction to support supplying additional env vars to the tracing provider you have selected.

In our case we need to specify `SPAN_STORAGE_TYPE`,`ES_SERVER_URLS` and `ES_INDEX_PREFIX`; however there is probably a wider use case for using Kafka or Cassandra storage backends.

**Describe alternatives you've considered**

* Ability to mount a custom jaeger config file into the container somehow
* Apply a post-install patch to the `Deployment`
* Installing Jaeger separately, as discussed in #8893 and #14274 is an option

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by objectiser** [comment]
Hi @chadlwilson 

The topic has been discussed in a number of threads as well as in the Policy/Telemetry WG. The current position is that configuring a production environment for tools such as Jaeger should be done outside the Istio installation - so for example the Jaeger operator could be used to provision an ES based environment, and then Istio refer to the Jaeger instance as described here: https://istio.io/docs/tasks/telemetry/distributed-tracing/jaeger/#before-you-begin.

**Comment by chadlwilson** [comment]
OK, fair enough @objectiser  - I thought that might be the answer; but also thought that perhaps allowing the env vars to be customised might be a quick win for little cost. I prefer to only have to install/configure one "thing" (Istio) rather than two, where we can - but do appeciate that it can be a death of a thousand cuts (just add this... and this.... and this other thing....) when you're maintaining Helm charts for 3rd party components that integrate with Istio.

**Comment by objectiser** [comment]
I believe this issue can be closed - but please reopen if there are further questions/suggestions.
