### ISSUE TITLE
Document virtual filesystem generation in operator repo

### ISSUE THREAD

**Issue by Niksko** [istio/istio#15324]
**Describe the feature request**

The operator repo requires you to run the `vfsgen` make target before building, otherwise your changes to the baked in profiles are not included in the compiled binary. This may be obvious to those familiar with how vfs works in Go, but it could be worth explicitly documenting it.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by ostromart** [comment]
This should be covered in https://github.com/istio/istio/issues/15237 (vfsgen should be a dependency in the makefile so devs shouldn't have to worry about it).
I do think it will be worthwhile to document vfsgen though if devs have to mess with that part of the code, so let's keep this bug open.
