### ISSUE TITLE
Sidecar egress configuration is not honored when mode is ALLOW_ANY

### ISSUE THREAD

**Issue by josejulio** [istio/istio#15329]
**Bug description**

Sidecar egress configuration is not honored when `global.outboundTrafficPolicy.mode` is set to `ALLOW_ANY`.

I think it shouldn't matter what your configuration for `outboundTrafficPolicy` is, because  as the [docs](https://istio.io/docs/tasks/traffic-management/egress/egress-control/#envoy-passthrough-to-external-services) say (emphasis mine):

> Istio has an installation option, global.outboundTrafficPolicy.mode, that configures the sidecar handling of **external services**, that is, those services that are not defined in Istio’s internal service registry.

Note that even if the workload is allowed to reach the service, the telemetry is not being reported for that event (even when having `istio-system/*` in the egress list). but if switch to `REGISTER_ONLY` the telemetry is being reported as going to an `unknown` service

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[X] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Workload is only able to access the services defined in the `egress.host` list of Sidecar resource.

**Steps to reproduce the bug**

1. [Ensure](https://istio.io/docs/tasks/traffic-management/egress/egress-control/#envoy-passthrough-to-external-services) `global.outboundTrafficPolicy.mode` set to `ALLOW_ANY` 
2. Install bookinfo
3. Install the following resource:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: sidecar-reviews-v2
  namespace: bookinfo
spec:
  workloadSelector:
    labels:
      app: reviews
      version: v2
  egress:
    - hosts:
        - "istio-system/*"
        - "bookinfo/details.bookinfo.svc.cluster.local"
```
Notice that we are only allowing istio-system and details service
4. Check that you are still able to access ratings from workload reviews-v2
```bash
kubectl exec -it $(kubectl get pod -l app=reviews -l version=v2 -o jsonpath={.items..metadata.name}) -c reviews -- bash -c "wget -q -O - --header='Content-Type: application/json' http://ratings.bookinfo.svc.cluster.local:9080/ratings/0 && echo ''"
```
yields:
```
{"id":0,"ratings":{"Reviewer1":5,"Reviewer2":4}}
```
5. [Set](https://istio.io/docs/tasks/traffic-management/egress/egress-control/#change-to-the-blocking-by-default-policy) `global.outboundTrafficPolicy.mode` to `REGISTER_ONLY` and wait a few seconds until the policy is in place.
6. Try the same command done in step 4 and see the error output, in my case
```
command terminated with exit code 8
```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

```
$ istioctl version --remote
client version: 1.2.0
citadel version: 1.2.0
egressgateway version: 1.2.0
galley version: 1.2.0
ingressgateway version: 1.2.0
pilot version: 1.2.0
policy version: 1.2.0
sidecar-injector version: 1.2.0
telemetry version: 1.2.0
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T10:09:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-06-20T16:29:27Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

With Helm

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
I don't think it makes sense to do this. You set the mode ALLOW_ANY, which does exactly what it says -- allow **any** traffic.

> Istio has an installation option, global.outboundTrafficPolicy.mode, that configures the sidecar handling of external services, that is, those services that are not defined in **Istio’s internal service registry.**

What you are asking for is not really possible. When you create the sidecar, the Envoy will only get config for the things you specify, in this case details and istio-system. When you send a request to `reviews`, Envoy has no way of knowing where the service is -- it just passes the traffic through.

This is exactly why REGISTRY_ONLY mode exists.

Regardless, does it really make sense to restrict mesh internal traffic then leave mesh external traffic wide open? if you really want that there are plenty of options with network policy, rbac, etc, but I don't think Sidecar is the right place for them

**Comment by josejulio** [comment]
> Istio has an installation option, global.outboundTrafficPolicy.mode, that configures the sidecar handling of external services, that is, those services that are not defined in **Istio’s internal service registry.**

Isn't the `ratings` service defined in Istio's internal service registry?

I think the description is a bit misleading in that sense, maybe a note to clarify this behavior would be the best, or a warning in the resources (Sidecar) that are impacted by this default setting (allow_any).

**Comment by howardjohn** [comment]
No, because you didn't specify it in the Sidecar. I guess what is a bit misleading here is "Istio's" internal service registry. Yes, pilot knows about it so it is in its internal service registry, but the Envoy's will not so it is not in its internal service registry.

I agree we should improve the docs to clarify the purpose and intent, and direct users trying to restrict access to other services to other approaches like rbac and network policy

**Comment by josejulio** [comment]
> Regardless, does it really make sense to restrict mesh internal traffic then leave mesh external traffic wide open? if you really want that there are plenty of options with network policy, rbac, etc, but I don't think Sidecar is the right place for them

Would it make sense to use `Sidecar` to restrict traffic from one service to the other if the mode is set to `REGISTRY_ONLY`?

**Comment by howardjohn** [comment]
I'm not sure what our official suggestion is on this, I will ask in the new networking meeting.

In theory it should work. I think the difference is that if there was a bug in sidecar restricting access it would be a normal (but high priority) bug, whereas if there was a bug in the rbac stuff which would cause a CVE, etc. In the future these features may converge.

Take what I said with a huge grain of salt though it may not be 100% accurate

**Comment by howardjohn** [comment]
I don't think there is any action items from this. Thanks for the report though, very useful
