### ISSUE TITLE
Document / allow generation of CRDs in operator repo

### ISSUE THREAD

**Issue by Niksko** [istio/istio#15325]
**Describe the feature request**

Playing around the with operator repo, using the default profiles, the CRD manifest is empty with the commend `crds component is disabled`. My read of the code is that it's actually not possible to enable this component at the moment, because the `IstioControlPlaneSpec` struct does not contain a `Base` field, which is the name of the base feature under which the crds component resides. This causes [IsComponentEnabled](https://github.com/istio/operator/blob/8c190bfa9dc175a05544d75d95cd2d8ba93c5d3b/pkg/name/name.go#L78) to always evaluate to `false`, because the field being searched for in the struct (`Base.Components.crds.Enabled`) doesn't exist.

**Describe alternatives you've considered**

1. This should be documented (the need to apply the CRDs manually at this point).
2. This should be fixed, happy to submit a PR with a bit of guidance. Can we just create the required fields in the protobuf and map them to sensible json fields? Do they need configuration options? 

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[X] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
I believe this is fixed now, @ostromart can you confirm?
