### ISSUE TITLE
a problem arise when i create gateway and virutalservice

### ISSUE THREAD

**Issue by bruse-peng** [istio/istio#15321]
below is my configuration:
![image](https://user-images.githubusercontent.com/47881861/60571956-193c6b00-9da7-11e9-9311-665ac013a7be.png)

when  i  acccess http://114.55.204.248/php/ (request default index.php)  is ok below:
![image](https://user-images.githubusercontent.com/47881861/60572059-5a347f80-9da7-11e9-852d-3bb43cdfb744.png)

but when i access http://114.55.204.248/php/phpinfo.php  it is back 404 below
![image](https://user-images.githubusercontent.com/47881861/60572169-9f58b180-9da7-11e9-9cd0-f99e9ca17ac7.png)

how i can resolve this problem

**Comment by linzhou-zhong** [comment]
Could you please upload a simple screenshot about the configuration of your pod "nginx-php"  ?

**Comment by bruse-peng** [comment]
below is my configuration of “nginx-php”
![image](https://user-images.githubusercontent.com/47881861/60633557-c8c41c80-9e3d-11e9-8e61-712a44f64156.png)

**Comment by bruse-peng** [comment]
under the web document, phpinfo.php and index.php avalaiable but i can only access index.php when i config gateway and virtualservice
![image](https://user-images.githubusercontent.com/47881861/60633820-037a8480-9e3f-11e9-992f-5d2a44109cb1.png)

**Comment by bruse-peng** [comment]
![image](https://user-images.githubusercontent.com/47881861/60633906-679d4880-9e3f-11e9-8cbb-bd70a4904151.png)

**Comment by bruse-peng** [comment]
who can help me i will appreaction for you helping

**Comment by linzhou-zhong** [comment]
> below is my configuration of “nginx-php”
> ![image](https://user-images.githubusercontent.com/47881861/60633557-c8c41c80-9e3d-11e9-8e61-712a44f64156.png)

I don't even understand how the image of ngnix-php looks like. Whatever all my instinct tell me that  
http://114.55.204.248/php/phpinfo.php is unknown from your ngnix-php Pod. 

Please try to complete the process of treatment when a request comes in.

In other words, how to make your application ngnix-php to apply the page phpinfo.php when it receives  http://114.55.204.248/php/phpinfo.php from others ?

**Comment by vadimeisenbergibm** [comment]
@bruse-peng Are you able to perform the request from inside the `Nginx-php` container? Calling `localhost/php/` and `localhost/php/phpinfo.php`?
