### ISSUE TITLE
can not report to istio-telemetry on VMs if not using ILB

### ISSUE THREAD

**Issue by irisdingbj** [istio/istio#15323]
I follow this guide https://istio.io/docs/setup/kubernetes/additional-setup/mesh-expansion/#setting-up-the-vm to set up the mesh expansion.

The envoy running on vm failed to report to istio-telemetry:
```
[src/istio/mixerclient/report_batch.cc:106] Mixer Report failed with: UNAVAILABLE:upstream request timeout
```
Have tried to create the virtual service manually for istio-telemetry, but it still failed with the same error message.

**Comment by irisdingbj** [comment]
@incfly looking forward to your comments for this problem. Thanks

**Comment by incfly** [comment]
Adding `istio-mixer` to the `/etc/hosts` for the gateway dns? I think it get it work sometime without adding `istio-mixer` though...
https://github.com/incfly/eztio/blob/master/bin/istio-gce.sh

Btw, I don't think you'll get meaningful metrics from mixer currently...

**Comment by irisdingbj** [comment]
@incfly    Thanks for the reply~

[3362][warning][filter] [src/istio/mixerclient/report_batch.cc:106] Mixer Report failed with: UNAVAILABLE:upstream request timeout

Have created virutal service for istio-telemetry and also added istio-telemetry into /etc/hosts. However it still report above error.
Why we can not get meaningful metrics even if we connect to mixer? Can you share the reason?

**Comment by irisdingbj** [comment]
1. 

The envoy config  has entry like ```"report_cluster": "outbound|15004||istio-telemetry.istio-system.svc.cluster.local" ```

1. 

create vs for istio-telemetry: ``` apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: meshexpansion-vs-telemetry
  namespace: istio-system
  labels:
    app: mixer
    istio: mixer
    istio-mixer-type: telemetry
spec:
  hosts:
  - istio-telemetry.istio-system.svc.cluster.local
  gateways:
  - meshexpansion-gateway
  tcp:
  - match:
    - port: 15004
    route:
    - destination:
        host: istio-telemetry.istio-system.svc.cluster.local
        port:
          number: 15004```

- 

1. 

add below entry into /etc/hosts on vm:

```Ingressgateway-public-ip  istio-citadel istio-pilot istio-pilot.istio-system istio-telemetry istio-telemetry.istio-system```
After all above steps still can not connect to mixer with the same error.

**Comment by incfly** [comment]
The reason that telemetry does not work for mesh expansion/vm is due to the way how mixer maps workload uid to the service/workload name. In k8s case, it's k8s pod uid, looking up apiserver, and then resolves to the service/workload object.

In VM case, the correct solution will be look up ServiceEntry via VM ip. However, that changes only works for mixer v1, not for v2, and v2 is currently the priority for telemetry WG.


/cc @douglas-reid

**Comment by jeffcai** [comment]
as a workaround, we resolved the issue:
- update the istio configmap to change the check and report url with our own defined host and port
- create a service entry with defined host and port which points to the policy and telemetry service with nodeport type
- update the VM hosts to point the policy and telemetry host to local VM IP which makes sure the policy and telemetry clusters will be route to proper outbounds

with above changes, the envoy on VM can connects to the telemetry and policy services

**Comment by incfly** [comment]
Do you just connect to the mixer or are you able to get the actual telemetry data? What will the workload/service attribute shows on on grafana?

**Comment by jeffcai** [comment]
tested with a simple log entry, the data can be sent to telemetry but not meaningful like desitionation is unknown (may be caused by logentry config, not sure), the function we'd like to use is ratelimit which actually works when VM app calls app on K8s.

**Comment by incfly** [comment]
that's expected.

**Comment by sdake** [comment]
Setting priority p1 for nebulous future.  As this issue is dependent upon the mixerv2 implementation completion, nothing can really be done at present to resolve the issue as far as I understand the issue tracker.

Cheers
-steve
