### ISSUE TITLE
Operator default value of dry-run: true is confusing

### ISSUE THREAD

**Issue by Niksko** [istio/istio#15322]
**Describe the feature request**

Just spent most of the day trying to figure out why the `iop` binary from the operator repo doesn't output anything when running an `iop manifest -o manifest_dir`, despite looking like it's going to.

Why is `dry-run` set to true by default?

**Describe alternatives you've considered**

A few options here:

1. Change `dry-run` to default to `false`. I understand that the operator isn't officially 'released' yet, but this seems like a messaging/docs thing rather than something that should be baked into the `iop` binary which prevents people testing. Actions: change default value of dry run to false, and perhaps add a big warning at the top of the repo that says 'This is not ready yet, use caution etc.' until it is.
2. Make the fact that the dry run is true by default and that `--dry-run=false` is needed to do anything slightly more prominent.
3. Do 2, but also temporarily add `--dry-run=false` into the documented examples to make it more explicit that this required for the moment. These can be removed once dry running is not the default.
4. Should there be some sort of log output that indicates that this is a dry run?

Happy to submit PRs

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by ostromart** [comment]
Thanks for testing this out Nik.
You're quite right - the dry run thing was documented but easy to miss. I created a PR to fix it but it would also be good to have log output stating that the tool is in dry run and won't apply or write anything. If you're willing to take that on it would be great. Also feel free to suggest any other improvements to the docs or elsewhere.
