### ISSUE TITLE
yamllint spams logs with warnings

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#15334]
Example (repeated ~1000 times):

```
./galley/testdata/validation/dataset/config-v1alpha2-rule-valid.yaml
  1:1       warning  missing document start "---"  (document-start)
```

Example test: https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/12276/istio-lint-master/827/?log#log

We should probably turn off this warning or fix it.

In general I don't think it really makes sense to have warnings anyways -- no one is going to look at a passing lint log to see the warning. We should either pass or fail. Others may disagree though

**Comment by irisdingbj** [comment]
Agree the current warning is meanless as nobody will take action on them. In that case, I  have changed the yamllintrules to not warn anymore
