### ISSUE TITLE
Adding multiple gateways on istio ingressgateway

### ISSUE THREAD

**Issue by 3223554** [istio/istio#15354]
**Bug description**
 i am trying to add multiple gateways on istio-ingressgateway
 ingressgateway  is LoadBalancer,  i use aliyun,
 but other gateway can not work, i find istio-ingressgateway log ,  requests cannot be properly proxied

**### this Success  log** 
"OPTIONS /api/StoreAdmin/GetAlreadyStoreList?type=0 HTTP/2" 200 - "-" 0 0 0 - "192.168.6.1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:67.0) Gecko/20100101 Firefox/67.0" "fed55f83-bd2a-4bec-9164-cc9683487e37" "sellerapi.yunquanlaile.com" "-" - - 192.168.6.110:443 192.168.6.1:33538 sellerapi.yunquanlaile.com

### **this error log**
 "OPTIONS /api/Login/GetInitData HTTP/2" 404 NR "-" 0 0 0 - "192.168.6.1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:67.0) Gecko/20100101 Firefox/67.0" "9f4e9637-9239-411e-bf79-1fba1a9b824e" "passportapi.yunquanlaile.com" "-" - - 192.168.6.110:443 192.168.6.1:33538 sellerapi.yunquanlaile.com

my file :
[mchcenterapi - 副本.txt](https://github.com/istio/istio/files/3358364/mchcenterapi.-.txt)

[passportapi - 副本.txt](https://github.com/istio/istio/files/3358367/passportapi.-.txt)

why i try request passportapi.yunquanlaile.com the request Handled by sellerapi.xiaokeduo.com?

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
Can you get config dumps from the gateway? https://github.com/istio/istio/wiki/Troubleshooting-Istio#collecting-information-2

**Comment by howardjohn** [comment]
Not enough info to reproduce. If you are still seeing this issue feel free to reopen with more info. Thanks!
