### ISSUE TITLE
Invalid pilot deployment manifest generated with istio operator

### ISSUE THREAD

**Issue by morvencao** [istio/istio#15366]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

Generate the manifests with default profile plus build-in chart for Istio installer and apply into the k8s env, get invalid `istio-pilot` deployment yaml:
```
root@mcdev1:~/go/src/istio.io/operator/cmd# pwd
/root/go/src/istio.io/operator/cmd
root@mcdev1:~/go/src/istio.io/operator/cmd# go build -o istio-operator
root@mcdev1:~/go/src/istio.io/operator/cmd# ./istio-operator manifest > istio.yaml
root@mcdev1:~/go/src/istio.io/operator/cmd# kubectl apply -f istio.yaml
...
Error from server (Invalid): error when creating "istio.yaml": Deployment.apps "istio-pilot" is invalid: spec.template.spec.containers[0].readinessProbe: Required value: must specify a handler type
...
```

**Bug description**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by morvencao** [comment]
@ostromart Any special reason why we comment these lines in default profile: https://github.com/istio/operator/blob/master/data/profiles/default.yaml#L32-L35

This results in invalid pilot deployment.

**Comment by ostromart** [comment]
There's some problem with unmarshaling into the struct because of this - perhaps it's the wrong version of the API, or something like that. I haven't had time to look into it yet, feel free to take a crack at :-)

**Comment by morvencao** [comment]
Yes, it's a json to pb unmarshaling issue, if I put this in profile:

```
          readinessProbe:
            #handler: {}
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 5
```

Then I will get `unknown field "httpGet" in v1.Probe`, still investigating on the solution.

**Comment by morvencao** [comment]
For this error after I add `handler` parent to profile:
```
error unmarahsling the json to protobuf with json: cannot unmarshal number into Go value of type map[string]json.RawMessage
```

There is a similar issue logged at kubernetes community, see: https://github.com/kubernetes/apimachinery/issues/59

The guys from kubernetes community suggest to use the json stdlib to marshal/unmarshal the API, since the proto support was added later.

**Comment by ostromart** [comment]
It's worth a try - however there are other proto fields like BoolValue that may not unmarshal using the built in library. 
Another possibility is to patch the Go structs after proto generation as we are doing for components.values fields to get a map[string]interface{} type.

**Comment by morvencao** [comment]
Actually I have tried to unmarshal with json standlib, the problem is that the json field names in the generated go struct are not camelcase, but `xxx_xxx`, see: https://github.com/istio/operator/blob/master/pkg/apis/istio/v1alpha2/istiocontrolplane_types.pb.go#L242-L252 
As a result, the json unmarshaler doesn't recognize the camelcase json/yaml.

I have tried to add `json_name` option in protobuf to control the go struct tag for json, however, it doesn't work because of https://github.com/golang/protobuf/issues/189


Finally I mirrored the kubernetes Probe definition in the protobuf, just like the other fields, `Resources`, `PodDisruptionBudgetSpec`, see: https://github.com/istio/operator/blob/master/pkg/apis/istio/v1alpha2/istiocontrolplane_types.proto#L616-L632 
It works well except the [`intOrStr` type](https://github.com/kubernetes/apimachinery/tree/master/pkg/util/intstr) can't be unmarshalled properly with error:
```
error unmarahsling the json to protobuf with json: cannot unmarshal number into Go value of type map[string]json.RawMessage
```
The currently workaround is that making the `port` field to be number type, the side effect is tat we can't specify port name in that field.

**Comment by ostromart** [comment]
I think patch is the way to go here, unfortunately. What we absolutely want to avoid is inconsistency with the k8s schema - even if this is documented I can see it causing lots of frustration for users.

**Comment by morvencao** [comment]
To fix the intOrStr type issue and avoid inconsistency with the k8s schema, I have extended the k8s `IntOrString` type and generated patch to the generated go code to make sure both the port number and port name can be marshal/unmarshal properly.

**Comment by morvencao** [comment]
Tried the latest master code, found the the `port` unmarshal issue happens again:

```
root@mcdev1:~/go/src/istio.io/operator/cmd# pwd
/root/go/src/istio.io/operator/cmd
root@mcdev1:~/go/src/istio.io/operator/cmd# go build -o $GOPATH/bin/iop ./cmd/iop.go
root@mcdev1:~/go/src/istio.io/operator/cmd# iop manifest 
root@mcdev1:~/go/src/istio.io/operator/cmd# cat ./iop.log
...
error unmarashling the json to protobuf with json: cannot unmarshal number into Go value of type map[string]json.RawMessage
```
