### ISSUE TITLE
Deployment manager template does not work with latest releases.

### ISSUE THREAD

**Issue by Martinlck** [istio/istio#15362]
Deployment manager template cannot properly install versions 1.1.x or 1.2.x

The problem is that it does not install istio-init which has the CRD's definitions that can be used later for tracing, etc...

[ ] Configuration Infrastructure
[ x ] Docs
[ x ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ x ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Deployment manager template should be able to install the version that has been released to with all it's components including the CRD's

**Steps to reproduce the bug**
Try to use the template by changing to any 1.1.x or 1.2.x version

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.1.x or 1.2.x
**How was Istio installed?**
Using deployment manager template on the release

**Environment where bug was observed (cloud vendor, OS, etc)**
All GKE versions that support istio

The jinja.schema as well does not allow you to change the version, which it should, as it comes as part of the other releases that are not 1.0.0

I want to submit a PR to fix this, but I want a very tiny bit of guidance, if we are going to be installing 1.0.0 we dont need to do the istio-init, but if we want to install the other versions we do and we need to do a tiny sleep before we run the istio one, otherwise the CRD's are still not ready and it fails later.

Please let me know what's the approach preferred and I'll take care of it.

**Comment by howardjohn** [comment]
wow I did not know we even had this.. I don't think it's documented at all.

Is there any reason you want to use this?

**Comment by Martinlck** [comment]
@howardjohn 
Hi! Well my reason is, that I do not want to use Istio on GKE as it does not allow me to touch the control plane, even for things like trace sampling on the pilot, which is very annoying.
So I decided to do my own install on my GKE cluster, and I have most of my GCP resources deployed through deployment manager, that's how I found the template on how to install it, which comes on the Istio releases. 
Besides, is already there in the releases, I guess it would not hurt to document it and make it work for all the versions, I'm more than happy to do that, and submit a PR.

**Comment by howardjohn** [comment]
Yeah I would say we either need to fix it up or get rid of it. I would recommend you take a look at GitHub.com/Istio/installer as well which is where we are working on a newer installer that is more flexible

**Comment by Martinlck** [comment]
Oh wow, I did not knew about this installer repository... So what do you suggest? I could fix this installer for now, and later on when the new one is released I can migrate to it. Or do you want me to look at something in particular about the new installer?

**Comment by howardjohn** [comment]
If users are using deployment manager we want to make it easy for them to
integrate that, but I worry we will just have it get really stale like it
is now (and I think we have ansible installer as well which I suspect is in
the same state).

Just took a look at the current implementation, it looks like a very loose
wrapper around the helm installation we have. Really just sets up a GKE
cluster (most of the work seems here) and then runs helm install Istio,
which is a couple lines and exposes a tiny subset of the options helm does

I'm wondering if it makes sense to just use a dedicated GKE setup template
(which is probably more robust/customizable than ours) and then after do
the couple steps it takes to install Istio and get the full customizability
+ support. I've never used this deployment manager though, would that make
sense?

**Comment by Martinlck** [comment]
Sounds good,  we can spin up a regional cluster with more customisable parameters.

Then install istio taking a few more parameters into consideration (like tracing sample), also update the helm version as Istio site recommends to be greater than 2.9 

I'll put a PR soon

**Comment by howardjohn** [comment]
What I meant was would it make more sense to use a supported templates for
gke like
https://github.com/GoogleCloudPlatform/deploymentmanager-samples/blob/master/community/cloud-foundation/templates/gke/README.md
then install Istio into it using the supported install methods?

We already have settings exposed through helm, I don't think it makes too
much sense to have another abstraction over this. Like I said though, never
used it before though so maybe I don't understand the use case.

**Comment by Martinlck** [comment]
I see! That looks good, the only thing I would like to change from there are some of the deprecated properties.
https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.zones.clusters#resource-cluster

- initialNodeCount
- nodeConfig (as optional)

Instead of using nodePool, and node configurations.

Then install istio using helm just as is now, but with the fix for latest versions.

**Comment by sdake** [comment]
GKE Deployment Manager, along with the Ansible implementation were removed from master as a result of lack of maintenance.

If you wish to revive these efforts, please submit a PR with an appropriate implementation for either installer technology.

In the meantime, I am closing this issue.

Cheers
-steve
