### ISSUE TITLE
Readiness probe failed: HTTP probe failed with statuscode: 503

### ISSUE THREAD

**Issue by harshul4274** [istio/istio#15371]
Events:
  Type     Reason     Age    From                        Message
  ----     ------     ----   ----                        -------
  Normal   Scheduled  8m14s  default-scheduler           Successfully assigned ns-beta/pod-istio1-55476bf445-bjnkv to nkv01.example.com
  Normal   Pulled     8m13s  kubelet, nkv01.example.com  Container image "docker.io/istio/proxy_init:1.2.0" already present on machine
  Normal   Created    8m13s  kubelet, nkv01.example.com  Created container istio-init
  Normal   Started    8m13s  kubelet, nkv01.example.com  Started container istio-init
  Normal   Pulling    8m10s  kubelet, nkv01.example.com  Pulling image "nginx:latest"
  Normal   Pulled     8m8s   kubelet, nkv01.example.com  Successfully pulled image "nginx:latest"
  Normal   Created    8m8s   kubelet, nkv01.example.com  Created container nginx-istio1
  Normal   Started    8m8s   kubelet, nkv01.example.com  Started container nginx-istio1
  Normal   Pulled     8m8s   kubelet, nkv01.example.com  Container image "docker.io/istio/proxyv2:1.2.0" already present on machine
  Normal   Created    8m8s   kubelet, nkv01.example.com  Created container istio-proxy
  Normal   Started    8m8s   kubelet, nkv01.example.com  Started container istio-proxy
  Warning  Unhealthy  8m6s   kubelet, nkv01.example.com  Readiness probe failed: HTTP probe failed with statuscode: 503

**Comment by harshul4274** [comment]
In kubernetes a issue come during ingress gateway used. When i check the log a error come is Readiness probe failed: HTTP probe failed with statuscode: 503. All pod are run in the container and all are running mode. If i put the request through a curl and error come is curl: (6) Could not resolve host: abc.example.info .

**Comment by howardjohn** [comment]
could not resolve host sounds like you are having dns issues

**Comment by harshul4274** [comment]
> could not resolve host sounds like you are having dns issues

Thanks for give a comment. A actually problem is a ip address not set and in back end are not set a namespace which is not find a ip.

Now a proble, Resolve.
![Screenshot from 2019-07-08 13-34-45](https://user-images.githubusercontent.com/34963521/60793371-37c6ab80-a185-11e9-82b3-a9f0a37056cb.png)

**Comment by howardjohn** [comment]
Sorry this wasn't clear to me, is this fixed now or are you still seeing problems?

**Comment by harshul4274** [comment]
Yes, problem is fixed and working with **abc.example.info** .

**Comment by howardjohn** [comment]
Great!

**Comment by harshul4274** [comment]
Thanks for shared your information.
