### ISSUE TITLE
Gateway setting need to be sync between value.yaml and new IstioControlPlaneSpec

### ISSUE THREAD

**Issue by richardwxn** [istio/istio#15375]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
The gateways definition in operator API and values.yaml is different. In operator API, IngressGateway and EgressGateway consists of array of gateways spec https://github.com/istio/operator/blob/master/pkg/apis/istio/v1alpha2/istiocontrolplane_types.pb.go#L1198 while in the current values api, is has only one gateway config struct for IngressGateway and EgressGateway https://github.com/istio/operator/blob/master/pkg/apis/istio/v1alpha2/values_types.go#L76. 

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by ostromart** [comment]
Since user gateways cannot be defined in the new istio/installer helm values, we will not support it either. Users are expected to install and manage their own gateways going forward.
