### ISSUE TITLE
Ability to add custom dashboards to Grafana

### ISSUE THREAD

**Issue by cagataygurturk** [istio/istio#15385]
**Describe the feature request**

It is already easy to add custom dashboards to Istio's Graphana instance by copying dashboard JSON into Helm chart before installing it. It smells a bit hacky though. I wonder if it possible to add an extra option to installer to streamline this process.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[x ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by giggio** [comment]
I noticed that it wouldn't be that difficult. This is where the dashboards are defined on the deployment:

https://github.com/istio/istio/blob/338a788766fb2d7c3e99da8e25636b8b9cbcf344/install/kubernetes/helm/istio/charts/grafana/templates/deployment.yaml#L99-L105

And these are the configs:

https://github.com/istio/istio/blob/338a788766fb2d7c3e99da8e25636b8b9cbcf344/install/kubernetes/helm/istio/charts/grafana/templates/deployment.yaml#L134-L138

I agree that manually adding the files is cumbersome. A simple config would be much better.

**Comment by giggio** [comment]
This is important. Please reopen.
