### ISSUE TITLE
istio CNI is not working correctly with IPv6

### ISSUE THREAD

**Issue by tibetsam** [istio/istio#15381]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
after enabling istio-cni and the side-car proxy never came up bcz of readiness failing.
the root cause is ip6tables INPUT tables rules are not correctly set.

```
root@mastermint:~/cni# kb get pod
NAME                              READY   STATUS    RESTARTS   AGE
productpage-v1-79f4bf97c9-9cpsl   1/2     Running   2          2d20h
```

**Event:**
```
  Warning  Unhealthy       3m18s (x130 over 8m)      kubelet, mastermint  Readiness probe failed: Get http://[fd01:0:0:2::514]:15020/healthz/ready: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```
```
root@mastermint:~/cni# nsenter -t 9347 -n curl -v http://[fd01:0:0:2::514]:15020/healthz/ready
*   Trying fd01:0:0:2::514...
* TCP_NODELAY set
* connect to fd01:0:0:2::514 port 15020 failed: Connection refused
* Failed to connect to fd01:0:0:2::514 port 15020: Connection refused
* Closing connection 0
curl: (7) Failed to connect to fd01:0:0:2::514 port 15020: Connection refused
```

**ip6tables which were created by istio CNI plugin**

```
root@mastermint:~# nsenter -t 26306 -n ip6tables-save
Generated by ip6tables-save v1.6.1 on Mon Jul  8 13:59:37 2019
filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [345:39852]
-A INPUT -m state --state ESTABLISHED -j ACCEPT
-A INPUT -d ::1/128 -i lo -j ACCEPT
-A INPUT -j REJECT --reject-with icmp6-port-unreachable
COMMIT
Completed on Mon Jul  8 13:59:37 2019
mangle
:PREROUTING ACCEPT [306:26163]
:INPUT ACCEPT [288:23820]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [345:39852]
:POSTROUTING ACCEPT [345:39852]
COMMIT
Completed on Mon Jul  8 13:59:37 2019
Generated by ip6tables-save v1.6.1 on Mon Jul  8 13:59:37 2019
nat
:PREROUTING ACCEPT [157:13347]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [18:1904]
:POSTROUTING ACCEPT [18:1904]
COMMIT
Completed on Mon Jul  8 13:59:37 2019
```

So CNI didn't set proper proxy nat rules instead set filter table to drop all inbound traffic.

And which comes from tools/packaging/common/istio-iptables.sh if function isIPv6() returns 1
```
663 else
664   # Drop all inbound traffic except established connections.
665   ip6tables -F INPUT || true
666   ip6tables -A INPUT -m state --state ESTABLISHED -j ACCEPT || true
667   ip6tables -A INPUT -i lo -d ::1 -j ACCEPT || true
668   ip6tables -A INPUT -j REJECT || true
669 fi
```

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

if there is any IPv6 addresses configured on the node, we shouldn't drop all IPv6 inbound traffic.

**Proposal**
 tools/packaging/common/istio-iptables.sh
use all-ip-addresses instead of ip-address to avoid to missing any other IPv6 addresses on the POD.

```
278 POD_IP=($(hostname --all-ip-addresses))
279 # Check if pod's ip is ipv4 or ipv6, in case of ipv6 set variable
280 # to program ip6tables
281 for IP in "$POD_IP"; do
282     IP=${IP// /}
283     if isIPv6 "$IP"; then
284         ENABLE_INBOUND_IPV6=$IP
285         break
286     fi
287 done
```

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by tibetsam** [comment]
@tiswanso I saw you worked on https://github.com/istio/istio/issues/14318. 
could you please help here? Thanks.

**Comment by howardjohn** [comment]
fyi @sbezverk

**Comment by tibetsam** [comment]
@tiswanso i'm not seeing same problem on 1.3.0
root@mastermint:~/istio-1.3.0/bin# ./istioctl proxy-status
NAME                                                   CDS        LDS        EDS        RDS          PILOT                           VERSION
istio-ingressgateway-7c4bbf46c9-fhmq8.istio-system     SYNCED     SYNCED     SYNCED     NOT SENT     istio-pilot-8c5b9b6c5-shrpb     release-1.3-20190916-10-16
sleep-5bbf6b4f77-jjf22.erenqgo                         SYNCED     SYNCED     SYNCED     SYNCED       istio-pilot-8c5b9b6c5-shrpb     1.3.0

but anyway, to avoid /etc/hosts related environment problem we should use --all-ip-addresses instead which is also recommended by man page
"
       -i, --ip-address
              Display  the  network address(es) of the host name. Note that this works only if the host name can be resolved. Avoid using this option; use hostname --all-ip-addresses instead."

**Comment by rlenglet** [comment]
Closing this, as the issue is not reproducible. Let's reopen if this is observable again in a version ≥1.3.x.
