### ISSUE TITLE
End user authn: add support for alg=RS384 and alg=RS512 claims in JWT filter

### ISSUE THREAD

**Issue by dgn** [istio/istio#15380]
**Describe the feature request**
I'd like to use existing JWTs with alg=RS384 or alg=RS512 claims with Istio's end user authentication policies. Currently, the JWT authn filter will reject all JWTs with `alg` claims outside of `['RS256', 'ES256']`.

**Describe alternatives you've considered**
The only way right now seems to be changing existing applications to use the weaker hash algorithm (SHA256 for RS256), which is not a good option.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**
[I created a PR](https://github.com/google/jwt_verify_lib/pull/24) to the jwt_verify_lib that is used by the upstream Envoy JWT filter. Will file a PR to make the same changes to `istio/proxy`'s JWT filter as well, so we have parity as long as the switchover has not happened yet.

**Comment by dgn** [comment]
I also filed a PR in the istio/proxy repository to apply the changes to the 'old' JWT filter: https://github.com/istio/proxy/pull/2301

**Comment by dgn** [comment]
Closing this as PRs have been merged

**Comment by dgn** [comment]
Reopening because this is working in 1.2 but not 1.3 due to switch from envoy filter in `istio/proxy` to the one in `istio/envoy`

**Comment by PiotrSikora** [comment]
This should be fixed in the upcoming `1.3.1` release (https://github.com/istio/envoy/pull/106) and `master` branch (https://github.com/istio/proxy/pull/2421, which includes sync with upstream).

@istio/release-managers-1-3 it's probably worth noting that this regression in `1.3.0` was fixed in `1.3.1`.

**Comment by rlenglet** [comment]
@PiotrSikora could you please add an item about this fix in the [1.3.1 release note draft](https://github.com/istio/istio/wiki/Release-Note-1.3.1-Draft)?

**Comment by PiotrSikora** [comment]
@rlenglet I think you meant @dgn.

**Comment by dgn** [comment]
@PiotrSikora @rlenglet I'm afraid I don't have commit rights to the wiki and GitHub does not support PRs for wikis. Here's a patch with the note added: https://gist.github.com/dgn/034a484714029d22874e2a5322120bc5

**Comment by rlenglet** [comment]
@dgn Added, thanks!

**Comment by dgn** [comment]
Closing this as it works on 1.3.1
