### ISSUE TITLE
Test Framework: Bookinfo should support native environment

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#15386]
As far as I know there is nothing blocking native environment for bookinfo

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[x] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by howardjohn** [comment]
Actually this is a lot less trivial than I thought..

@nmittler what do you think? Options I can think of:

* Migrate mixer tests to use echo and not bookinfo
* Get bookinfo running on docker as well -- probably way to much effort/complexity to be worth it
* Keep all the mixer tests as kube only (:slightly_frowning_face:)

**Comment by nmittler** [comment]
@howardjohn makes sense.  At this point, I think migrating the tests to use echo is the right way to go.

**Comment by kyessenov** [comment]
Echo does not represent a realistic micro-services app. Mixer tests require sufficient complexity so we can show the interesting features (deep traces, policies between services, etc).

**Comment by howardjohn** [comment]
closing as won't-fix
