### ISSUE TITLE
Istio CNI and MUTUAL_TLS 

### ISSUE THREAD

**Issue by cscetbon** [istio/istio#15399]
**Bug description**
Using istio-cni to encrypt communications between pods of a StatefulSet. When controlPlaneSecurityEnabled is globally enabled my service starts correctly but communications are not encrypted. I was able to confirm it using tcpdump in one of the Istio-proxy containers. istioctl shows that client uses HTTP :

```
istioctl authn tls-check cassandra-0|head
HOST:PORT                                                     STATUS     SERVER        CLIENT     AUTHN POLICY                                 DESTINATION RULE
cassandra.cassandra-e2e.svc.cluster.local:7000                OK         HTTP/mTLS     HTTP       default/                                     -
cassandra.cassandra-e2e.svc.cluster.local:7001                OK         HTTP/mTLS     HTTP       default/                                     -
cassandra.cassandra-e2e.svc.cluster.local:7199                OK         HTTP/mTLS     HTTP       default/                                     -
cassandra.cassandra-e2e.svc.cluster.local:9042                OK         HTTP/mTLS     HTTP       default/                                     -
```

the different tests I tried show that 

- when [g] global controlPlaneSecurityEnabled is disabled pod can communicate [OK]
- when [g] controlPlaneSecurityEnabled is disabled + annotation set to NONE OK
- when [g] controlPlaneSecurityEnabled is disabled + annotation set to MUTUAL_TLS NOK 
- when [g] controlPlaneSecurityEnabled is enabled OK 
- when [g] controlPlaneSecurityEnabled is enabled + annotation set to NONE NOK 
- when [g] controlPlaneSecurityEnabled is enabled + annotation set to MUTUAL_TLS OK

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

I expect communications to be encrypted when controlPlaneSecurityEnabled is enabled and no Destination Rules or annotation like https://gist.github.com/cscetbon/b58c5bb617f7dbbcce0a830067f34ffb#file-aspen-mesh-cni-testing-yaml-L61 are used.
I also expect to be able to enable encryption only on my namespace and/or service without having to enable it globally

It seems that the annotation sidecar.istio.io/controlPlaneAuthPolicy has to be set accordingly to the global controlPlaneSecurityEnabled configuration otherwise envoy can't communicate with the pilot. I would expect to be able to use the annotation when  controlPlaneSecurityEnabled is disabled to enable it for my StatefulSet. I also tried to not use the annotation and use instead https://gist.github.com/cscetbon/b58c5bb617f7dbbcce0a830067f34ffb#file-aspen-mesh-cni-testing-yaml-L1-L19 but it does not help. 

mTLS is enabled on both server and client
```
istioctl authn tls-check cassandra-0|head 
HOST:PORT                                                     STATUS     SERVER        CLIENT     AUTHN POLICY                                 DESTINATION RULE
cassandra.cassandra-e2e.svc.cluster.local:7000                OK         mTLS          mTLS       default/cassandra-e2e                        default/cassandra-e2e
cassandra.cassandra-e2e.svc.cluster.local:7001                OK         mTLS          mTLS       default/cassandra-e2e                        default/cassandra-e2e
cassandra.cassandra-e2e.svc.cluster.local:7199                OK         mTLS          mTLS       default/cassandra-e2e                        default/cassandra-e2e
cassandra.cassandra-e2e.svc.cluster.local:9042                OK         mTLS          mTLS       default/cassandra-e2e                        default/cassandra-e2e         -
``` 

However I have to make the pod listen on 127.0.0.1 for envoy to get ready and pods can't communicate to each other ...

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
istio 1.2.2
k8s 1.13

**How was Istio installed?**

using helm templates 

```
k create namespace istio-system
helm template install/kubernetes/helm/istio-init --name istio-init --namespace istio-system | kubectl apply -f -

k get crds | grep 'istio.io\|certmanager.k8s.io' | wc -l
23

helm template install/kubernetes/helm/istio-cni --name=istio-cni --namespace=istio-system | kubectl apply -f -

- with global authentication enabled :
helm template install/kubernetes/helm/istio --name istio --namespace istio-system --values install/kubernetes/helm/istio/values-istio-demo-auth.yaml --set istio_cni.enabled=true --set sidecarInjectorWebhook.rewriteAppHTTPProbe=true --set kiali.enabled=true| kubectl apply -f -

- with global authentication disabled :
helm template install/kubernetes/helm/istio --name istio --namespace istio-system --values install/kubernetes/helm/istio/values-istio-demo.yaml --set istio_cni.enabled=true --set sidecarInjectorWebhook.rewriteAppHTTPProbe=true --set kiali.enabled=true| kubectl apply -f -

```

**Environment where bug was observed (cloud vendor, OS, etc)**
MacOS [dind](https://github.com/kubernetes-sigs/kubeadm-dind-cluster/blob/master/dind-cluster.sh)

**Comment by hzxuzhonghu** [comment]
@cscetbon I doubt if you enabled `allow_any` outbound traffic policy, so the traffic goes through the PassthroughCluster  cluster, and it is expected to be passed transparently.

**Comment by cscetbon** [comment]
@hzxuzhonghu all the commands I used are in the description (see how Istio was installed and my gist). I'm not sure I understand your point, can you elaborate ?

**Comment by rlenglet** [comment]
This issue is not specific to CNI, which has nothing to do with mTLS. Updating labels.

**Comment by cscetbon** [comment]
@rlenglet I don't have that issue when I don't set up Istio using istio-cni.

**Comment by rlenglet** [comment]
@cscetbon does this still happen with 1.3.3? The iptables setup is now the same with and without Istio CNI starting with the 1.3.0 release, which should remove any discrepancies between setups with and without Istio CNI.

**Comment by cscetbon** [comment]
@rlenglet I haven't tried but I can.
