### ISSUE TITLE
Adding a SDS scenario to our existing upgrade tests

### ISSUE THREAD

**Issue by fpesce** [istio/istio#15408]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
As per [ @duderino 's comment](https://github.com/istio/istio/issues/15020#issuecomment-505561763) in #15020 , we should have a SDS scenario in our upgrade tests.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[X] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.2/1.3

https://github.com/istio/istio/issues/13439

**Comment by myidpt** [comment]
Hi Jimmy, could you add this to your Code Mauve doc, and let's prioritize and delegate the work.

**Comment by JimmyCYJ** [comment]
> Hi Jimmy, could you add this to your Code Mauve doc, and let's prioritize and delegate the work.

Sure! Will do.
