### ISSUE TITLE
Need tests that exercise IPv6, ideally with IPv4 disabled so we can be sure that IPv6 continues to work / doesn't regress

### ISSUE THREAD

**Issue by fpesce** [istio/istio#15407]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
There is no test or not enough testing for IPv6 support.
This is created after a [comment from @duderino ](https://github.com/istio/istio/issues/1756#issuecomment-503264543) 
Istio 1.2 's release notes contain IPv6 support marked as experimental, we should qualify this feature as beta by adding the necessary tests.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[X] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
There should be tests for IPv6 support.

**Steps to reproduce the bug**
make test

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.2

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
cc @sbezverk
