### ISSUE TITLE
Istio mutual TLS with consul

### ISSUE THREAD

**Issue by nirvanacc** [istio/istio#15401]
In k8s, i want to use 'Istio mutual TLS' to control the communication between consul server and consul server, or consul server and consul client. At this time, i need to ensure the safe of the communication with TLS.
So i inject sidecar to consul, the method to join consul cluster is via
-retry-join="provider=k8s label_selector=\"app=consul-server\" namespace=micro-service"
i got a err msg from consul：
[ERR] agent: Join LAN: discover-k8s: error listing pods: an error on the server ("") has prevented the request from succeeding (get pods)
I am sure it can join each other before i inject the sidecar.
what wrong with it? help me plz.
and if istio can do this effect for consul?

**Comment by nirvanacc** [comment]
yes, it work good even if i inject the sidecar as long as i don't usr 'Globally enabling Istio mutual TLS'

**Comment by ayj** [comment]
@nirvanacc, have you followed the instructions at https://istio.io/faq/general/#istio-doesnt-work? If you have and the problem still persists, please re-open this issue with the current state (see https://istio.io/about/bugs/).
