### ISSUE TITLE
Add debug endpoints to Citadel agent

### ISSUE THREAD

**Issue by Monkeyanator** [istio/istio#15416]
**Describe the feature request**

The current [node agent](https://istio.io/docs/concepts/security/#node-agent-in-kubernetes) does not expose information on its active connections with proxies ([it includes count metrics](https://github.com/istio/istio/blob/master/security/pkg/nodeagent/sds/monitoring.go), but nothing more specific), and the secret configuration it is providing. This feature request calls for the addition of debug endpoints which expose this information.

**Describe alternatives you've considered**

Not exposing this information at all.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

Ties in [with this PR](https://www.google.com/url?q=https://github.com/envoyproxy/envoy/pull/7365&sa=D&source=hangouts&ust=1562788552319000&usg=AFQjCNFG7EbcZBGkLVoSTs2No7C7q7MJaA), which once merged, will expose SDS configuration on the envoy side. These two features together will let us find discrepancies between the two configurations.

**Comment by JimmyCYJ** [comment]
When running in gateway agent mode, Citadel agent watches k8s API server for ingress gateway secrets. It would be nice if this debug endpoint could list all added k8s secrets with added time and cert expire time, and keep updating the list. 

We could also add/update SDS integration test to cover the debug endpoint.
