### ISSUE TITLE
Status and Events for Istio CRDs

### ISSUE THREAD

**Issue by esnible** [istio/istio#15412]
This work item tracks the progress of 

Istio Config: Status Field Requirements
https://docs.google.com/document/d/1kS1X5GYVyxx1_yuMsi96eZ0u7UXc8M1FugFpt7fT6zM/edit?ts=5d24b8a2

Istio Config: Validation Approach
https://docs.google.com/document/d/1Ag0H7BAsAcW8BeIArQ57bX3U0rLc1cKwN1B5oVRN1Yw/edit

@ozevren @rvennam

**Comment by esnible** [comment]
@ozevren Should we move this to 1.4?

**Comment by ozevren** [comment]
I am assigning this to @sushicw as he has been ramping up on this area.

**Comment by sushicw** [comment]
https://github.com/istio/istio/pull/16350 has a lot of the groundwork for this.

**Comment by sushicw** [comment]
https://github.com/istio/istio/pull/17360 adds this into master.

Closing this issue, https://github.com/istio/istio/issues/882 is still open and tracks this area more comprehensively.
