### ISSUE TITLE
Option to control istio configuration through annotations

### ISSUE THREAD

**Issue by cgetzen** [istio/istio#15411]
**Describe the feature request**
Problem: Decouple istio configuration from helm charts.
Example Solution: Ambassador can be controlled via CRD or annotations. You can then pass annotations into your helm chart via values.yaml. The users are given the flexibility to to hook ambassador up to any chart that allows annotations to be passed in.

Currently, my belief is that to incorporate istio into a deployable helm chart, you need to modify the helm chart itself to add all of the required CRDs, making the chart inflexible and dependent on istio.

**Describe alternatives you've considered**
Custom Controller on services that create VirtualServices.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ x ] User Experience
[ ] Developer Infrastructure

**Comment by howardjohn** [comment]
Can you clarify a bit what is your goal here, so I can better understand what this would entail?

To completely replace the use of Istio CRDs and instead use annotations? To use annotations to configure things per-deployment rather than globally/per namespace/etc? To make a helm chart that consists of Istio and some other stuff? Something else entirely?

**Comment by cgetzen** [comment]
I think "to configure things per-deployment" almost fits the bill. By allowing configuration through annotation, power is given to helm users to hook into almost any chart.

To make it more concrete: I would not be able to inject the required istio config into the wordpress chart, but I would be able to hook ambassador into wordpress using ambassador's [annotations](https://www.getambassador.io/reference/configuration/#configuration-sources) and [this](https://github.com/helm/charts/blob/master/stable/wordpress/templates/svc.yaml#L12)

The istio way would be to launch the chart with a values.yaml, then create some CRDs.
The ambassador way would be to launch the chart, with specific ambassador config in the values.yaml.

This makes managing the releases and their upgrades much easier.

**Comment by howardjohn** [comment]
In your example with the wordpress chart, why is it easier to inject annotations, which may or may not be configurable in all helm charts, rather than just adding an extra resource?

If the chart just has a top level `{{ .Values.extraConfig }}` or something, then you can just add in all of your Istio CRs there. From the helm install perspective it is the same, you just are setting a different values field.

I am not sure how common it is to have such a field though - but it doesn't sound like your use case *requires* annotations, rather it just requires the chart to allow to put configs at the top level

**Comment by cgetzen** [comment]
I would love it if that was standard (_a la_ monochart), but I can't find any stable chart that includes a top level extra config.
With charts within our org, we bake istio CRDs into the chart itself.
With charts in helm's stable repository, the overwhelming standard is to allow extension through annotations. We would have to copy and modify them to allow istio to be configured through the chart.

Some numbers for you:

|  | script | result |
|-|-|-|
|total charts|`ls stable \| wc -l` | 279 |
|annotation-injected charts| `ag "Values.*annotation" stable/ -c \| cut -d/ -f2 \| uniq \| wc -l` | 171 |

Allowing us to hook into these 60+% of helm charts would be really powerful.

In the meantime, it is keeping us glued to ambassador or copying and editing the charts.

> rather than just adding an extra resource?

Our CI/CD solution is heavily embedded with helm, and we've found controlling both a helm release and random resources leads to lost resources and difficult upgrades and rollbacks.

**Comment by howardjohn** [comment]
> In the meantime, it is keeping us glued to also running ambassador or copying and editing the charts.

I think an alternative solution that may work is by extending a chart with requirements.yaml. For example, you make a chart `WordpressWithIstio`, and in it you put all your istio CRDs for the chart. Then in requirements.yaml you just depend on stable/wordpress. I've never tried it but my understanding is that would work.

I think that would solve copying the charts (although you do need your own chart now) and keeping them all bundled together as one release. Not a helm expert though so maybe it won't work out as I envision it.

I find it unlikely we would support annotations, at least not in the near future. I think with Ambassador there is sort of a 1:1 mapping between their config and a Kubernetes service/deployment, so it makes sense for an annotation, but this is not the always case for Istio CRs. So it is highly confusing to have a VirtualService that applies to `a` and `b` but is an annotation for `a`?

**Comment by sdake** [comment]
We are not making further investments in any helm related technology for Istio. As such I am closing this bug.  Our future solution for deployment is focused around the operator here: https://github.com/istio/operator.

**Comment by howardjohn** [comment]
@sdake shipping the operator and supporting users using Helm charts to install Istio CRs are two different things. Users are using helm - we should meet them where they are. I don't think we should add annotation support though for the reasons mentioned above

**Comment by iusergii** [comment]
Also would like to deprecate our existing Ingress Controller in favour of istio-ingressgateway. And even 3rd party apps (Kialy, Grafana, Prometheus) from Istio demo profile have only Ingress Objects.
Looking for good way for exposing this externally with Istio 0bjects.
