### ISSUE TITLE
Dropping websocket connections on scale (800+ pods)

### ISSUE THREAD

**Issue by yarivlifchuk** [istio/istio#15428]
**Bug description**
On scale when creating 600+ pods with virtual services that are connected through web socket, connections get broken. Connections are dropped by Pilot and ingressGateway.

Pilot error msg: 
"Client received GoAway with http2.ErrCodeEnhanceYourCalm
transport: loopyWriter.run returning. connection error: desc = "transport is closing"
mcp Error receiving MCP resource: rpc error: code = Unavailable desc = transport is closing
error mcp Error receiving MCP response: rpc error: code = Unavailable desc = transport is closing"

IngressGateway msg:
"ProxyStatus": {
        "pilot_eds_no_instances": {
            "outbound_.5473_._.calico-typha.kube-system.svc.cluster.local": {},
            "outbound_.9001_._.workspaces-ws-lfj4j-service.busy-shrew.svc.cluster.local": {},
            "outbound|5473||calico-typha.kube-system.svc.cluster.local": {},
            "outbound|9001||workspaces-ws-lfj4j-service.busy-shrew.svc.cluster.local": {}
and later
"Epoch 0 terminated with an error: signal: killed.."

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[X] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
No dropped Connections when adding new Pods with their virtual service.

**Steps to reproduce the bug**
- Install istio 1.2.2 on AWS K8S cluster.(side car injection=disabled)
- Max pilot and ingress instances = 15
- Create 800 pods while establish websocket connection after creation of each pod.
- Each pod should have virtual service with 6 host that refer to one destination.
- use ping every 5 second to each pod to hold the connection and detect disconnection

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.2.2

**How was Istio installed?**
helm chart

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
What issues are you actually running into? it is expected that pilot will drop connections.

The only log you provided that looks potentially concerning is the "epoch killed" but I would need to see the full log to know more.

Are you actually seeing real issues or just error messaged in the logs?

**Comment by yarivlifchuk** [comment]
Hi,
We experience disconnections of opened websockets to pods/services that were already established in different namespaces.
Attached the logs.

We are creating namespace for each user that has pod,service, configmap,secret and virtual service.
We expect that adding new namespace with virtual service and establishing websocket to this pod/service will not cause to disconnection of websocket to other pods/services in different namespaces.

Below you can find the pilot dashboard showing that pilot active connections are dropped.

[cid:image002.jpg@01D53764.4C09DDF0]

Thanks,
Yariv

**Comment by howardjohn** [comment]
> [cid:image002.jpg@01D53764.4C09DDF0]
the image never actually got uploaded

> Below you can find the pilot dashboard showing that pilot active connections are dropped.

Pilot active connections are unrelated to your websocket connections. Pilot just configures envoy, envoy is handling the connections between your apps

**Comment by yarivlifchuk** [comment]
Attached the pilot Dashboard image.
I am aware that Pilot active connections are unrelated to the websockets.
The websockets start to drop when the pilot active connections start to drop so it may relate.

Is it possible to check the logs to see the root cause of websocket disconnections (IngressGateway issue that may relate to Pilot behavior)

Thanks,
Yariv

**Comment by howardjohn** [comment]
I don't think you can send images as email attachments, please upload on github

**Comment by yarivlifchuk** [comment]
![PilotDashboard](https://user-images.githubusercontent.com/36994532/61027314-8317ce80-a3be-11e9-8f28-70ae5aa8a87e.jpg)
[istio_pilot_gateway_galley_logs.zip](https://github.com/istio/istio/files/3380523/istio_pilot_gateway_galley_logs.zip)

**Comment by yarivlifchuk** [comment]
logs and dashboard image are accessible now.

**Comment by howardjohn** [comment]
I see.. maybe when pilot disconnects + reconnects, it sends new config to envoy which causes envoy to drop the connections it has open?

Ingressgateway looks like it may be getting OOMkilled?

**Comment by rshriram** [comment]
i have a theory.. for the moment can you use the Sidecar resource with `egress: ./*` in each namespace? I think this should solve the websocket issue.

**Comment by rshriram** [comment]
ftr, its happeninng because rds is reloaded in every sidecar outbound.. consequently, existing connections get drained.. on the gateway, same thing might be happening.. if the error is happening at gateway, then your only option is to use separate ports for each websocket.

**Comment by yarivlifchuk** [comment]
It looks as the pilot memory leak fix helps to solve the disconnections
https://github.com/istio/istio/issues/14782

**Comment by hzxuzhonghu** [comment]
this may also duplicate with #18089
