### ISSUE TITLE
Use gateways for mesh expansion

### ISSUE THREAD

**Issue by sdake** [istio/istio#15427]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Mesh expansion is pretty cool.  Unfortunately, it requires a VPC.  Sort out how to use a gateway instead.

**Describe alternatives you've considered**
None.  I want mesh expasion integration with gateways.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[X] Docs
[X] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by linsun** [comment]
+1 on using gateway for mesh expansion, we have got too many users ask about mesh expansion not working or not easy to get it working for non flat L3 network among k8s pods and VMs.

The question I want to bring up is:  is this in addition to the existing mesh expansion doc as a different model or we are proposing to get rid of the current mesh expansion?

cc @costinm @duderino

**Comment by incfly** [comment]
No, it's inaccurate. We already use gateway for mesh expansion. https://istio.io/docs/setup/kubernetes/additional-setup/mesh-expansion/

We might want to document both supports. Not aware of any any technical obstacles other than doc and testing...

**Comment by linsun** [comment]
@incfly thanks, you are right, it was embedded in there.

**Comment by irisdingbj** [comment]
@incfly https://istio.io/docs/setup/kubernetes/additional-setup/mesh-expansion/  has a prereq: Mesh expansion machines must have IP connectivity to the endpoints in the mesh. This typically requires a VPC or a VPN, as well as a container network that provides direct (without NAT or firewall deny) routing to the endpoints. The machine is not required to have access to the cluster IP addresses assigned by Kubernetes.

The gateway in this doc is only for connecting pilot and citadel.  So we need a new doc to cover using gateway to connect workloads as well and this is the one: https://github.com/istio/istio.io/pull/4713
