### ISSUE TITLE
Multicluster routing ServiceEntry to service without sidecar

### ISSUE THREAD

**Issue by steffengy** [istio/istio#15431]
If you proceed like here
https://istio.io/docs/setup/kubernetes/install/multicluster/gateways/
everything works.

But how is this expected to work for pods without a sidecar (It doesn't, the ingress only returns 503's)?
This can be reproduced by omitting the `istio-injection=enabled` labeling for httpbin.

The only workaround I can think of is hosting another service that reverse-proxies and which uses injection?

**Comment by silencehe09** [comment]
By the way ,  in "Multiple control plane topology" , does it support to reach remote pods through gateway  without mTLS for some sake of ops ?  How  to change the configuration of istio control plane deployments ?

**Comment by howardjohn** [comment]
To send mTLS requests/understand ServiceEntry you will need a sidecar
