### ISSUE TITLE
Connect external https services from istio mesh, with certificate provided by the  service

### ISSUE THREAD

**Issue by ayan1207** [istio/istio#15451]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Connect external https services from istio mesh, with certificate provided by the  service.

**Describe alternatives you've considered**
Currently we have certificate inside application. We want same thing to be moved to istio.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by elevran** [comment]
@ayan1207 - thanks for opening this.
Could you please elaborate more on what you are trying to achieve?
From the above description, my understanding is that you want to import a **client** certificate from an external source and add it to Istio proxy to be used when connecting to the external service. That means that the certificate will be used to authenticate services inside the mesh to the external service but the certificate will not be managed by Istio.
Is that correct?

**Comment by rakeshjain1213** [comment]
Hi,

We need to connect the external service which has its own certificate.
For this we have created the ServiceEntry for the service outside the mesh and a DestinationRule where we have passed the certificate.
After applying this and trying to connect the external service , we get the error as:
2019-08-12 11:20:16.583 ERROR 1 --- [ault-executor-0] j.d.p.g.s.DigitalApiGrpcServiceProcessor : Service exception, error message is : Exception occured while invoking service interface, Error Message : I/O error: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target; nested exception is javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target


[destinationrule_estel.txt](https://github.com/istio/istio/files/3491194/destinationrule_estel.txt)
[serviceentry_estel.txt](https://github.com/istio/istio/files/3491195/serviceentry_estel.txt)

**Comment by elevran** [comment]
@rakeshjain1213 it seems that the error above comes from the workload application (i.e., client)?
If so, it seems to attempt TLS on its own since the error is **not** reported by Istio's sidecar proxy.
You should reconfigure the workload to use HTTP instead of HTTPS in that case.

I think you're trying to have the application access a server and want to have Istio initiate the TLS.
If the server certificate is not signed by a well known CA (i.e., there is a trust path from the server certificate to some established CA), you may need to import the CA for that connection in the TLSSetting configuration object (see https://github.com/istio/api/blob/93fc23ae4a32512b282e25491b7f06eadbbb7336/networking/v1alpha3/destination_rule.proto#L606).

**Comment by rakeshjain1213** [comment]
Hi, 

Will you please let me know what need to be done in order to connect the service which is outside the mesh and has its own .crt (certificate file).
Please let us know what all configurations need to be done to achieve the same.

**Comment by elevran** [comment]
hi @rakeshjain1213. Have you gone through the Istio tasks and concepts for egress traffic?
For example, https://istio.io/docs/tasks/traffic-management/egress/egress-tls-origination/?

**Comment by rakeshjain1213** [comment]
Hi Elevran,

I have gone through this concepts, but it is difficult to understand how this would be implemented.
Will you please help me to achieve this, I want to call a service outside the mesh over https with the certificate provided by them.
Please let me know what all configurations i need to do.
Thanks in advance.

**Comment by elevran** [comment]
hi @rakeshjain1213 
The needed configuration for TLS origination from egress is shown in https://istio.io/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/#configure-mutual-tls-origination-for-egress-traffic (ignore the mTLS part, you need one way TLS):

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - nginx.example.com
    tls:
      mode: MUTUAL
      serverCertificate: /etc/certs/cert-chain.pem
      privateKey: /etc/certs/key.pem
      caCertificates: /etc/certs/root-cert.pem
```

Note that the TLS mode should be set to `SIMPLE` in your case and `privateKey` is not needed

**Comment by rakeshjain1213** [comment]
Hi Elevran,

I have not created a Egress Gateway, but have just created the ServiceEntry and DestinationRule.
PFA files that i was using to configure https traffic.

[serviceentry_estel.txt](https://github.com/istio/istio/files/3532899/serviceentry_estel.txt)
[destinationrule_estel.txt](https://github.com/istio/istio/files/3532900/destinationrule_estel.txt)

**Comment by rakeshjain1213** [comment]
Hi,  

Also please let me know , what about ca certificate. What we need to be configure in that, as from client side I have received only one certificate file that is estelvms.crt.
So I dint from where we will be getting ca cert file.

**Comment by rakeshjain1213** [comment]
Any Update

**Comment by diemtvu** [comment]
Hi @rakeshjain1213,
Do you still have trouble with this issue? 

As @elevran  mentioned, you need CA cert file if the (external) server you are talking to use the cert signed by non-wellknown root CA. You should be able to get the cert by contacting the service owner.

**Comment by incfly** [comment]
i believe this is a duplicate of https://github.com/istio/istio/issues/21368. you can comment +1 and follow up there.

closing. feel free to reopen.

**Comment by rahul6941** [comment]
@rakeshjain1213 


> Hi Elevran,
> 
> I have not created a Egress Gateway, but have just created the ServiceEntry and DestinationRule. PFA files that i was using to configure https traffic.
> 
> [serviceentry_estel.txt](https://github.com/istio/istio/files/3532899/serviceentry_estel.txt) [destinationrule_estel.txt](https://github.com/istio/istio/files/3532900/destinationrule_estel.txt)

@rakeshjain1213 
We are also using same configuration but still  issue not solved . please share your solution . Thanks for help

**Comment by SpecialYang** [comment]
@rahul6941 There are two cases.
1. If your external svc works on the mtls mode, you shoud set the tls mode as MUTUAL and specify client cert and ca cert in DR.
2. If your external svc only work on the tls mode, you just set the tls mode as SIMPLE.

**Comment by rahul6941** [comment]
> @rahul6941 There are two cases.
> 
> 1. If your external svc works on the mtls mode, you shoud set the tls mode as MUTUAL and specify client cert and ca cert in DR.
> 2. If your external svc only work on the tls mode, you just set the tls mode as SIMPLE.
> 
> The important thing you have to do is that switch the client application to use http:// instead of https://.
Do client cert and ca cert in DR are required on tls mode as SIMPLE? 
Sorry for  dump question and also #newbee here : Its not true that all istio outbound traffic  are encrypted with TLS protocol ?
