### ISSUE TITLE
Make kiali 'auth.strategy' dynamic, currently its hardcoded to 'login'

### ISSUE THREAD

**Issue by venomwaqar** [istio/istio#15467]
In the istio - kiali templates, `auth.strategy` is hardcoded to `login` [Here](https://github.com/istio/istio/blob/9e050364f41a86e38eb6a352acec1e63d3ed776a/install/kubernetes/helm/istio/charts/kiali/templates/configmap.yaml#L15)
It would be very helpful, if we can make it dynamic or allow it to get the value from charts variable.

If there is any other way to supply that value, please assist me.

**Comment by jmazzitelli** [comment]
We've had two PRs submitted on this :)

https://github.com/istio/istio/pull/15459

Waiting on this one: https://github.com/istio/istio/pull/15146

**Comment by venomwaqar** [comment]
@jmazzitelli Okay, thanks.

**Comment by costinm** [comment]
The PRs seem to be merged, closing this bug.

Note that Kiali has its own operator and we should stop maintaining duplicated installer for kiali ( like we  are planning to do for CertManager, Prometheus, etc).
