### ISSUE TITLE
TestWorkloadAgentRefreshSecret racetest failures

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#15478]
Example Failures:
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/14938/istio-racetest-master/35
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/15056/istio-racetest-master/260
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/15138/istio-racetest-master/239
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/15227/istio-racetest-master/431
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/15345/istio-racetest-master/1358
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/15406/istio-racetest-master/1401
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/15460/istio-racetest-master/1511
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/15464/istio-racetest-master/1573

**Comment by howardjohn** [comment]
/assign @JimmyCYJ @myidpt 

There are lots of these failures, can one of you take a look?

https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/14938/istio-racetest-master/35
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/15056/istio-racetest-master/260
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/15138/istio-racetest-master/239
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/15227/istio-racetest-master/431
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/15345/istio-racetest-master/1358
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/15406/istio-racetest-master/1401
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/15445/istio-racetest-master/1477
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/15460/istio-racetest-master/1511
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/15464/istio-racetest-master/1573
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/15486/istio-racetest-master/1607
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/15491/istio-racetest-master/1632

**Comment by JimmyCYJ** [comment]
Thanks @howardjohn , these are unit tests in Citadel Agent. @quanjielin and I will take a look.

**Comment by JimmyCYJ** [comment]
Per discussion with @howardjohn, the test failures can be found back to 06/20. Need to reproduce it locally first and identify whether the failure is caused by prow or potential bug in the code.

**Comment by JimmyCYJ** [comment]
One option is to run the test in docker with limited CPUs 
for example `docker run -it --mount source=<$GOPATH>,target=/root/go,type=bind --cpus=1 gcr.io/istio-testing/istio-builder:v20190619-72a31e48 -- bash`
Thanks @howardjohn for the tips!

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/20215/unit-tests_istio/6643
