### ISSUE TITLE
Service Dashboard in Grafana broken

### ISSUE THREAD

**Issue by christian-posta** [istio/istio#15475]
On Istio 1.2.2 when using Istio-demo.yaml, the out of the box Istio Service Dashboard in Grafana is broken. It appears in an effort to trip CRDs in the yaml file, the `metric` CRD and any of the defined metrics which that particular dashboard uses is missing.

**Comment by howardjohn** [comment]
Looks fine to me? What is yours missing?

https://snapshot.raintank.io/dashboard/snapshot/pJ8GRk4B4h0iNQhdaKgOV4t5gSFimUDp

**Comment by christian-posta** [comment]
Yah, of course it works for me now lol... I was on an airplane when I saw the incorrect behavior. Sorry for those noise, thanks for double checking @howardjohn
