### ISSUE TITLE
ServiceEntry.Resolution DNS lookup only ipv4 address

### ISSUE THREAD

**Issue by tibetsam** [istio/istio#15488]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
envoy is only trying to resolve ipv4 address, so all ipv6 external services can't be reached with resolution.DNS mode.

And according to Envoy documents by default it should be Auto, means first IPv6 and then IPv4. 
but i found in istio code, it is specifically set to IPv4 only.

erenqgo@ubuntu:~/go/src/istio.io/istio$ grep "cluster.DnsLookupFamily" * -r
pilot/pkg/networking/core/v1alpha3/cluster.go:          cluster.DnsLookupFamily = apiv2.Cluster_V4_ONLY

Enum Cluster.DnsLookupFamily
[Cluster.DnsLookupFamily proto]

When V4_ONLY is selected, the DNS resolver will only perform a lookup for addresses in the IPv4 family. If V6_ONLY is selected, the DNS resolver will only perform a lookup for addresses in the IPv6 family. If AUTO is specified, the DNS resolver will first perform a lookup for addresses in the IPv6 family and fallback to a lookup for addresses in the IPv4 family. For cluster types other than STRICT_DNS and LOGICAL_DNS, this setting is ignored.

AUTO
(DEFAULT) ⁣

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
It should either use envoy Auto mode by default or provide a plilot-agent command line argument to change the mode (considering Auto mode's side effect for ipv4 users)

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by tibetsam** [comment]
@vadimeisenbergibm Could you please help to revert or improve the fix? https://github.com/istio/istio/pull/5447

**Comment by howardjohn** [comment]
This was intentional because we were getting DNS spam for ipv6 in non-ipv6 environments. So I don't think we can just switch it to auto.

Ref https://github.com/istio/istio/issues/13710

**Comment by tibetsam** [comment]
@howardjohn yes, you are right, so let's try to provide a plilot-agent command line argument to change the mode by user.

**Comment by howardjohn** [comment]
I don't think we would want to add another field to ServiceEntry. Why do you need to configure it in ServiceEntry anyways? My understanding is you would want to use ipv6 cluster wide or ipv6 cluster wide, not per service?

**Comment by tibetsam** [comment]
Yes, you are right. Then maybe it is better to set the dns_lookup_family value based on k8s cluster ip version. Will you plan to implement this in near feature ?

**Comment by howardjohn** [comment]
Part of https://github.com/istio/istio/issues/1756
