### ISSUE TITLE
pilot and rest of control-plane not starting after full restart

### ISSUE THREAD

**Issue by castlemilk** [istio/istio#15487]
**Bug description**
If a kubernetes cluster undergoes a scenario where all pods are destroyed and then rescheduled, the istio control plane will not successfully restore itself back to functionality when the number of pilot pods is > 1. Consequently the rest of the istio control-plane, and gateways never stabilise/get their configuration.

all pilot pods will report the following in their logs until the number of replicas is scaled to 1:

```
2019-07-12T07:24:16.823007Z     info    Configuration not synced: first push for [istio/config/v1alpha2/httpapispecs istio/networking/v1alpha3/gateways istio/networking/v1alpha3/serviceentries istio/networking/v1alpha3/destinationrules istio/networking/v1alpha3/envoyfilters istio/networking/v1alpha3/sidecars istio/config/v1alpha2/httpapispecbindings istio/mixer/v1/config/client/quotaspecs istio/rbac/v1alpha1/serviceroles istio/networking/v1alpha3/virtualservices istio/rbac/v1alpha1/servicerolebindings istio/rbac/v1alpha1/rbacconfigs istio/rbac/v1alpha1/clusterrbacconfigs istio/mixer/v1/config/client/quotaspecbindings istio/authentication/v1alpha1/policies istio/authentication/v1alpha1/meshpolicies] not received
```

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ x ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ x] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ x ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

On a full cluster restart, the istio control-plane should be able to successfully recover itself back to functionality.

**Steps to reproduce the bug**

1. Create a kubernetes cluster on say GKE, should also work on local cluster like minikube etc.
2. install istio with the number of pilot replicas > 1, then once the istio deployment is successfully stabilised, scale down the number of worker nodes to 0, or destroy all pods (after removing the `PodDistruptionBudget` resources, or install with `global.defaultPodDisruptionBudget.enabled=false`
3. monitor the istio components, you should see it fail to stabilise until you scale down the pilot replicas to 1.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

istio 1.1.9

**How was Istio installed?**

helm template

**Environment where bug was observed (cloud vendor, OS, etc)**

tested on GKE

**Comment by howardjohn** [comment]
Interesting, I'll test this out. The error means it isn't getting config from galley btw, does galley come up properly?

Are both replicas displaying that or only one.

**Comment by howardjohn** [comment]
Just killing the pods didn't do it for me, I had 3 pilot replicas all come up fine -- they had that log message but only for a few seconds.

Will try again with killing a node

**Comment by howardjohn** [comment]
I tried killing nodes too and didn't run into the issue either

**Comment by castlemilk** [comment]
sorry for delayed response, its all pods showing this. In my case I had 4 running, all of which failed to come up. I'll try again

**Comment by leecalcote** [comment]
@castlemilk where you able to resolve this issue? What was the problem?
