### ISSUE TITLE
Operator should support in-place upgrades

### ISSUE THREAD

**Issue by ayj** [istio/istio#15482]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

The istio/operator should support a basic in-place upgrades of the control plane.

**Describe alternatives you've considered**

Dual-control plane with proper canary deployments for Istio components. This is the ideal upgrade method and the operator should eventually support. We also need the in-place upgrade. The latter is simpler and a better realistic candidate for the 1.3 timeframe.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

The main issue is how to constrain range of supported versions per operator version. Code needs some additional refactoring so all version info is completely encapsulated in data, not code.

**Comment by ostromart** [comment]
We now have the necessary plumbing in place to support this. Since this is the first version we don't have the ability to test this until there are at least two releases of the install package from istio/istio. Keeping this open but lowering to P1 for now.

**Comment by ostromart** [comment]
Implemented in https://github.com/istio/operator/pull/348.
