### ISSUE TITLE
istio/operator broken developer quick start instructions

### ISSUE THREAD

**Issue by Monkeyanator** [istio/istio#15497]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
 [Developer quick start](https://github.com/istio/operator#installation) from istio/operator points to invalid git repo, and doesn't provide dependency installation overview. 

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Running `git clone https://istio.io/operator.git` should bring down the `operator` repo, but does not. The repo should also mention how dependencies are managed in istio/operator, since the included build steps will fail as listed.

**Steps to reproduce the bug**
Run `git clone https://istio.io/operator.git` or `git ls-remote http://istio.io/operator.git` (attempt to follow developer quickstart as written).

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
N/A

**How was Istio installed?**
N/A

**Environment where bug was observed (cloud vendor, OS, etc)**
Linux host

**Comment by ostromart** [comment]
@ayj, could Tao investigate this? If not, feel free to reassign back to me.

**Comment by ostromart** [comment]
I fixed the repo path at least in https://github.com/istio/operator/pull/84
But it would be good to investigate the dependency breakage by starting with a clean slate and trying this out. In theory all deps should be handled by go.mod but perhaps something is missing or broken there.

**Comment by ayj** [comment]
cc @elfinhe 

I left a comment on istio/operator#84 that `export GO111MODULE=on` was needed with golang < 1.13. I was able to start from a clean slate with this additional change.

**Comment by Monkeyanator** [comment]
Quick follow-up: `export GO111MODULE=on` was all that was needed (for my case).

**Comment by ostromart** [comment]
Great, looks like istio/operator#84 is all we need then. I added the env var export to the instructions there.
