### ISSUE TITLE
All Istio charts should be consolidated into one release directory

### ISSUE THREAD

**Issue by sdake** [istio/istio#15498]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
We support https://istio.io/charts however it only contains the latest charts version.  See 
**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[X] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**
It is not possible to install old versions of Istio charts nor upgrade the charts from the same location.  See https://github.com/istio/istio.io/issues/3789 for more details.  (the second part of the issue there)

Note it is completely fine to keep the per-version charts repo, but all charts need to additionally be consolidated into one directory and an index created for them.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
All versions.

**Comment by howardjohn** [comment]
Also dupe of https://github.com/istio/istio/issues/12974 up to you which to close

**Comment by yinzara** [comment]
any traction on this? Using Terraform and Helm to manage this is extremely difficult.  If there was some kind of Terraform provider for Istio it would really be incredible :)

**Comment by linsun** [comment]
still valid req as long as we will support helm charts.

**Comment by yinzara** [comment]
#reopen

**Comment by hazcod** [comment]
What is the preferred way to install istio using terraform? I am looking at the helm provider, but can  that just use https://github.com/istio/istio/tree/master/manifests ?
