### ISSUE TITLE
Figure out how to integrate the prometheus chart

### ISSUE THREAD

**Issue by ostromart** [istio/istio#15505]
Prom is not a first class Istio component but is needed for demos. Figure out the right way to integrate the chart to support a single line demo install while not integrating prom too deeply into the operator. 
One way to kick the can down the road is to install it through the existing values.yaml passthrough API.

**Comment by howardjohn** [comment]
Whats the plan for non-demo? Bring your own Prometheus operator and we provide the yamls to get istio scraping?

**Comment by morvencao** [comment]
Also should we consider integrating with prometheus that already exists in the cluster?

**Comment by ostromart** [comment]
I believe @mandarjog and @douglas-reid worked on integrating the prom operator - can you guys comment on the plan for it going forward? Is it just a straight drop in replacement for the chart we had before?

**Comment by douglas-reid** [comment]
@ostromart it can be used a straight drop-in. The plan for the prom operator is to allow people that are already managing a prom deployment with the prom operator to generate the CRs necessary to scrape istio endpoints. There is a mode for also generating a prom CR, in the cases where the user is not already running a prometheus instance. Used in that way, it can be a drop-in replacement.

**Comment by ostromart** [comment]
In that case I propose we use it as a drop-in for the demo profile, using the helm passthrough API. For integrating with existing prom, we'll leave that outside operator scope. 
@douglas-reid is there a values.yaml available somewhere for the demo use case?

**Comment by ayj** [comment]
Does prom CR depend on how the Istio control plane is deployed? Or will a single static definition be sufficient for any control plane deployment?

**Comment by ostromart** [comment]
It's not static - see https://github.com/istio/installer/tree/master/istio-telemetry/prometheus-operator/templates

**Comment by ostromart** [comment]
Fixed.
