### ISSUE TITLE
Handle loading client-side certificates in egress gateways

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio#15517]
**Describe the feature request**
There are cases when non-Istio-managed client certificate must be used for some hosts, in particular in the case of egress gateway performing mTLS with an external service. While DestinationRule allows specifying a client certificate and a private key in https://istio.io/docs/reference/config/networking/v1alpha3/destination-rule/#TLSSettings, it does not allow to specify the specific pod (for example the egress gateway) where the certificate/key must be loaded. Using the DestinationRule with client certificate in TLSSettings causes all the Envoys in the namespace to try to load the certificate/key and to fail in case the certificate/key are loaded in a single pod only.

The current "exportTo" field specifies namespaces. The proposal is to change the semantics, in the backward-compatible way:

```
exportTo: "./app=label" # export to the pods with label app=label in the current namespace
```
When the label part is omitted in the value of `exportTo`, the semantics is as previously:
```
exportTo: "." # export to all the pods in the current namespace.
```
**Describe alternatives you've considered**
1. Deploy the pod with client certificate/key in a separate namespace. Can be wasteful in the terms of namespaces, and also not feasible in some cases, for example in OpenShift, where namespaces can have separated networks and there could be a requirement to deploy the gateway pod in the same namespace with the application pods.
1. Mount client certificate/private key in all the pods in the namespace. Not good security-wise.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**
Will solve https://github.com/istio/istio/issues/9659.

**Comment by vadimeisenbergibm** [comment]
cc @rshriram

**Comment by nitishm** [comment]
Any activity on this request ?

**Comment by saurabhygk** [comment]
Any update on this feature? Or is there any workaround to specify caCertificate only available for relevant pod?

**Comment by vadimeisenbergibm** [comment]
@saurabhygk no updates yet, sorry.

**Comment by vadimeisenbergibm** [comment]
An alternative solution: add a selector to the DestinationRule, so it will be used at specific pods or gateways, similarly to VirtualService's https://istio.io/docs/reference/config/networking/virtual-service/#L4MatchAttributes `sourceLabels`/`gateways` fields.

**Comment by zachidan** [comment]
Another alternative solution: Filtered out DestinationRules (also known as upstream clusters in Envoy) that are not referenced by any VirtualService. This filtering along with the VirtualService `sourceLabels` / `gateways` fields, can provide the same functionality of eliminating specific DestinationRules from specific pods.

**Comment by zachidan** [comment]
The current behavior (Istio version 1.4, xDS enabled, mutual TLS mode) is that `istio-proxy` ignores an upstream cluster that is defined with a missing certificate/key (the certs are NOT mounted to the pod).

Here is the **warning** message that `envoy` (istio-proxy) reports when it receives from `pilot` an upstream cluster with missing certificate:

```
[Envoy (Epoch 0)] [2019-12-04 15:38:58.163][19][warning][config] [external/envoy/source/common/config/grpc_mux_subscription_impl.cc:82] gRPC config for type.googleapis.com/envoy.api.v2.Cluster rejected: Error adding/updating cluster(s) outbound|80||exampledr.myns.svc.cluster.local: Invalid path: /tmp/certs/myclientcert.pem, outbound|80|v1|exampledr.myns.svc.cluster.local: Invalid path: /tmp/certs/myclientcert.pem
```

Here is the `DestinationRule` that defines the missing certificate/key:

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: exampledr
spec:
  host: exampledr.myns.svc.cluster.local
  trafficPolicy:
    tls:
      mode: MUTUAL
      clientCertificate: /tmp/certs/myclientcert.pem
      privateKey: /tmp/certs/client_private_key.pem
      caCertificates: /tmp/certs/rootcacerts.pem
  subsets:
  - name: v1
    labels:
      version: v1
```

@vadimeisenbergibm do you think that this behavior is good enough ?

**Comment by vadimeisenbergibm** [comment]
This issue should be taken into consideration in the design of the new APIs for DestinationRules, for Istio 1.5/Istio 1.6. 

cc @duderino @louiscryan @rshriram

**Comment by incfly** [comment]
So the other pods rejecting entire CDS  because it contains one single cluster which intended only for egressgateway. Is that the problem?

**Comment by zachidan** [comment]
@incfly No, currently the other pods rejecting ONLY the single cluster which intended only for the egress-gateway. That is, the other pods do not reject the entire CDS.

**Comment by incfly** [comment]
Then it's not that bad, only causing extra warning/error log, and traffic
can still flow as it should be? Or do I miss anything? What other harm it
does for current behavior?

**Comment by zachidan** [comment]
@incfly you don't miss anything. No other harm, except the extra warning log message.

My thought is that it is good enough for now. For the next Istio releases, we may want to consider extending the `DestinationRule` API to support a list of `gateways` (similar to what is currently supported by the `VirtualService` API).

**Comment by nitishm** [comment]
I don't think it is just a benign warning.
On seeing this error message in pilot logs 
```
message:"Error adding/updating cluster(s) outbound|31290||3msdsip.com: Invalid path: /etc/example.com/certs/cert" >
```
I also checked the proxy-status and it seems to show STALE CDS entries
```
~istioctl proxy-status -i fed-istio                                                                                                                                       
NAME                                                                            CDS        LDS        EDS        RDS        PILOT                                                            VERSION
goodbye-world-1-0-0-148-main-int-workspace-dbg-855556dfb8-m9cld.fed-example     STALE      SYNCED     SYNCED     SYNCED     istio-pilot-1-0-0-90-main-int-workspace-dbg-5c87574bc8-4ghdm     1.1.3*
hello-world-1-0-0-179-main-int-dbg-848896b7c4-n4w99.fed-example                 STALE      SYNCED     SYNCED     SYNCED     istio-pilot-1-0-0-90-main-int-workspace-dbg-5c87574bc8-4ghdm     1.1.3*
istcfgagt-1-0-0-23-main-int-workspace-dbg-7d878d7559-ngndr.fed-example          STALE      SYNCED     SYNCED     SYNCED     istio-pilot-1-0-0-90-main-int-workspace-dbg-5c87574bc8-4ghdm     1.1.3*
istio-egressgateway-1-0-0-60-main-int-workspace-dbg-f46b65xqvqh.fed-example     SYNCED     SYNCED     SYNCED     SYNCED     istio-pilot-1-0-0-90-main-int-workspace-dbg-5c87574bc8-4ghdm     1.1.3*
istio-ingressgateway-1-0-0-60-main-int-workspace-dbg-5d6dbzhjhf.fed-example     STALE      SYNCED     SYNCED     SYNCED     istio-pilot-1-0-0-90-main-int-workspace-dbg-5c87574bc8-4ghdm     1.1.3*
pod-cfgmgr-1-0-0-200-main-int-dbg-7bc95f5f7f-jzs2c.fed-example                  STALE      SYNCED     SYNCED     SYNCED     istio-pilot-1-0-0-90-main-int-workspace-dbg-5c87574bc8-4ghdm     1.1.3*
pod-fileserver-1-0-0-50-main-int-workspace-dbg-7df9d4df7f-sppjw.fed-example     STALE      SYNCED     SYNCED     SYNCED     istio-pilot-1-0-0-90-main-int-workspace-dbg-5c87574bc8-4ghdm     1.1.3*
timer-1-0-0-148-main-int-dbg-75fb9654b5-rjx96.fed-example                       STALE      SYNCED     SYNCED     SYNCED     istio-pilot-1-0-0-90-main-int-workspace-dbg-5c87574bc8-4ghdm     1.1.3*
```

IMO a specific selector for `DestinationRule` like @vadimeisenbergibm mentioned, is the best route.

**Comment by nrjpoddar** [comment]
I tried adding a DR in a new namespace with exportTo: "." with egressgateways installed in that namespace (this namespace is not istio-system). I still see that Pilot is trying to push certificates for the cluster to all sidecars instead of just to egressgateway. This is with 1.3.6.

**Comment by iftachsc** [comment]
we are hitting this on 1.4.7, 1.5.1

**Comment by spanspan** [comment]
any update on this one? seeing this on 1.5.5.

**Comment by amckee23** [comment]
Ran into the same issue today and spent a significant amount of time debugging.  I have a work around for now which is to scope the DestinationRule as only exported to the namespace of the egress gateway as mentioned above but also deploy the egress gateway to its own namespace.

Not sure if this is related to: https://github.com/istio/istio/pull/12234 but i have read through a long list of historical issues it seems that Istio treats the istio-system namespace differently when applying DestinationRules and seems to ignore them if they are marked as not exported.

**Comment by juanamat** [comment]
I am using istion 1.5.5/

I have been hit by a similar problem too.
I am not using an egress gateway but doing TLS origination directly from one pod.
The problem is that another pod, which does not care about that, does not start as it cannot find the certificates specified in the destination rule.
