### ISSUE TITLE
the commit  cd4a148 seems wrong for istio 1.2.2 release 

### ISSUE THREAD

**Issue by clyang82** [istio/istio#15518]
**Bug description**

<img width="1013" alt="image" src="https://user-images.githubusercontent.com/7711311/61181488-e3766c80-a659-11e9-9d10-a33b6de6846b.png">

the commit `cd4a148` seems wrong. use this commit cannot build the bookinfo successfully.
Have to apply this commit - https://github.com/istio/istio/commit/491acb07b4c58f063de77e8824b868c9f14e45f8

I remembered I can download the 1.2.2 in Jun. 27. but the release note is 4 days ago. what happened?

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[x] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
The release was retagged to the same commit. That is why it is 4 days ago

not sure what you mean by the commit is wrong

**Comment by clyang82** [comment]
I used this commit cannot build the bookinfo images. I am not sure if the istio 1.2.2 build the bookinfo example images or not. Thanks.

**Comment by howardjohn** [comment]
the bookinfo images are published independently of the release so its possible it was broken at that commit and later fixed

**Comment by clyang82** [comment]
OK. Got it. Thanks @howardjohn for your information.
