### ISSUE TITLE
"istioctl inspect"

### ISSUE THREAD

**Issue by esnible** [istio/istio#15526]
This work item tracks the progress of

Istioctl inspect
https://docs.google.com/document/d/1OnJpw1Hi5vtfnIajOFwvuJPlnPlB2rJeCkRvSVJx9vI/edit#

Initially we will implement this as "istioctl experimental inspect" so that we can get feedback on the output and implementation before finalizing.

**Comment by linsun** [comment]
+1 would love to see an experimental cmd on this.

@esnible what is the outlook for this in in 1.3?

**Comment by linsun** [comment]
should this be service level inspect given many istio resources are applied to service not pod?

**Comment by ayj** [comment]
+1 for using experimental and getting user feedback before finalizing. In particular, it would be useful to understand whether it makes sense to anchor on workload (pod), host (service), or a higher-level service concept (IstioService?).

**Comment by esnible** [comment]
Much of the needed data is now in the Envoy configuration, in the filter_medata/istio JSON.

If you do `kubectl exec $POD -c istio-proxy -- curl localhost:15000/config_dump | jq '.. | . as $parent | .metadata?.filter_metadata? | select(.!=null) | { route: $parent.name, config: $parent.metadata.filter_metadata.istio.config}` you'll see output like

```
...
{
  "route": "inbound|8079|grpc-ping|fortio-echo.default.svc.cluster.local",
  "config": "/apis/networking/v1alpha3/namespaces/default/destination-rule/fortio-echo"
}
{
  "route": "inbound|8080|http-echo|fortio-echo.default.svc.cluster.local",
  "config": "/apis/networking/v1alpha3/namespaces/default/destination-rule/fortio-echo"
}
...

We could clean up that information and produce something human-readable that is very similar to what was discussed in the proposal.  I think we can get a minimal version of this in 1.3.

**Comment by esnible** [comment]
Totally re-architected to get all information from sidecar:15000/config_dump and pilot:/debug/authenticationz.

The code already validates many Kubernetes Service things, such as port names.  I will add support for "a port 80 service being called tcp" as requested in https://github.com/istio/istio/issues/6892

**Comment by esnible** [comment]
Still looking for PR reviewers.

I am using this to validate all meshed pods on a cluster using

```
for ns in $(kubectl get ns -o custom-columns=NAME:.metadata.name --no-headers); do
	for pod in $(kubectl get pods -n $ns -o custom-columns=NAME:.metadata.name --no-headers); do
	~/go/out/darwin_amd64/release/istioctl experimental inspect pod $pod.$ns --ignoreUnmeshed | grep -i warning
	done
done
```

I designed `inspect` as an inspection tool but it is proving handy as a validation tool.
