### ISSUE TITLE
Missing metrics in prometheus for egress gateway

### ISSUE THREAD

**Issue by anycz** [istio/istio#15528]
**Bug description**
In Grafana, Istio workload/service data is extremely limited for egress gateway. "Istio service dashboard" show data in "SERVICE: istio-egressgateway.istio-system.svc.cluster.local" section, for the "Client request volume", "Client success rate" and "Client request duration" subsections. Other parts are empty. "Istio workload dashboard" is totally empty.

Associated query in Prometheus also return empty result set.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Ability to see the different values associated with egress gateway in Grafana. (same as for other pods using istio sidecars).

**Steps to reproduce the bug**
Follow istio example on egress gateway TLS origination : https://istio.io/docs/tasks/traffic-management/egress/egress-tls-origination/
Repeat the last curl to generate some data in prometheus.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Istio 1.1.8 / Kubernetes 1.13.3
istioctl version --remote
client version: version.BuildInfo{Version:"1.1.8", GitRevision:"145b18a441045d6fad33d7916380d8642c7bf21d", User:"root", Host:"11387264-87af-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.7-14-g145b18a"}
citadel version: version.BuildInfo{Version:"1.1.8", GitRevision:"145b18a441045d6fad33d7916380d8642c7bf21d-dirty", User:"root", Host:"11387264-87af-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.7-14-g145b18a"}
egressgateway version: version.BuildInfo{Version:"1.1.8", GitRevision:"145b18a441045d6fad33d7916380d8642c7bf21d", User:"root", Host:"11387264-87af-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.7-14-g145b18a"}
galley version: version.BuildInfo{Version:"1.1.8", GitRevision:"145b18a441045d6fad33d7916380d8642c7bf21d-dirty", User:"root", Host:"11387264-87af-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.7-14-g145b18a"}
ingressgateway version: version.BuildInfo{Version:"1.1.8", GitRevision:"145b18a441045d6fad33d7916380d8642c7bf21d", User:"root", Host:"11387264-87af-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.7-14-g145b18a"}
pilot version: version.BuildInfo{Version:"1.1.8", GitRevision:"145b18a441045d6fad33d7916380d8642c7bf21d-dirty", User:"root", Host:"11387264-87af-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.7-14-g145b18a"}
policy version: version.BuildInfo{Version:"1.1.8", GitRevision:"145b18a441045d6fad33d7916380d8642c7bf21d-dirty", User:"root", Host:"11387264-87af-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.7-14-g145b18a"}
sidecar-injector version: version.BuildInfo{Version:"1.1.8", GitRevision:"145b18a441045d6fad33d7916380d8642c7bf21d-dirty", User:"root", Host:"11387264-87af-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.7-14-g145b18a"}
telemetry version: version.BuildInfo{Version:"1.1.8", GitRevision:"145b18a441045d6fad33d7916380d8642c7bf21d-dirty", User:"root", Host:"11387264-87af-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.7-14-g145b18a"}

kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
Using helm template :
helm template install/kubernetes/helm/istio --name istio --namespace istio-system --set tracing.enabled=true --set grafana.enabled=true --set kiali.enabled=true --set kiali.createDemoSecret=true --set gateways.istio-egressgateway.enabled=true --set pilot.traceSampling=100 --set global.proxy.accessLogFile=\"/dev/stdout\" | kubectl apply -f -

**Environment where bug was observed (cloud vendor, OS, etc)**
Linux version 4.15.0-1043-aws (buildd@lcy01-amd64-030) (gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)) #45-Ubuntu SMP Mon Jun 24 14:07:03 UTC 2019

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by anycz** [comment]
Any news on this?

**Comment by douglas-reid** [comment]
I believe this has been (at least partially) addressed now. Please try with the 1.4 release and re-open if still an issue.

**Comment by pravi1991** [comment]
Hi,
Even I am using the same setup as given above and I see the same results.
Some of my dashboards are empty.

I digged deeper using prometheus and ran these empty graph's prometheus query and I was able to find that the reporter label for **istio_requests_total** was showing as "destination" for bookinfo app and "source" for my custom app. The only difference between my app and bookinfo is the image used and the names and labels given. But still the label "destination_app" for bookinfo app shows as "productpage-v1" and for my app it is "istio-telemetry".

**Comment by douglas-reid** [comment]
@pravi1991 if you see your app reporting to istio-telemetry, that is expected. Is your app calling out through an egressgateway?

**Comment by pravi1991** [comment]
No. I am not using any egressgateway. After some research, I found out this **connection_security_policy="none"** for bookinfo app and **connection_security_policy="unknown"** for my app. So I checked if there is any destination rule applied and I found that there is one for bookinfo and nothing for mine. I followed the documentation and applied a destination rule and policy for that service with mutual tls thinking that it should atleast show **connection_security_policy="mutual_tls"** as per documentation, but it was still showing **unknown** .Also, I am able to find that my **destination_workload** label is showing my app name as value now and I didn't do anything except the facts stated above.

**Comment by douglas-reid** [comment]
@pravi1991 if you are not using egressgateway then your app is likely calling out through the passthrough cluster. you might want to read https://istio.io/blog/2019/monitoring-external-service-traffic/. "unknown" is expected for client-side metrics.

I suggest moving this conversation to the [forums](discuss.istio.io), as this isuse was about egressgateway.

**Comment by tanyyeah** [comment]
hey @douglas-reid, I am facing this issue. How to fix this?
