### ISSUE TITLE
Deeper ALB support

### ISSUE THREAD

**Issue by rverma-nikiai** [istio/istio#15522]
**Describe the feature request**
Hi team, planning to implement deeper integration of istio gateway with aws ALB. There are many advantages of using ALB and in particular a target group [Default metrics and alarms]. It's readily integrated with other services as well e.g. SNS notification.

The interesting part is that target groups can register a pod as a target directly, thanks to aws vpc cni plugin.

**Describe alternatives you've considered**
An alternative to metrics and alarms is to manage everything using Prometheus and Alert manager. But there is no evident equivalent to the networking provided by the target group.

**Affected product area (please put an X in all that apply)**

[ x] Configuration Infrastructure
[ x] Docs
[ x] Installation
[ x] Networking
[ x] Performance and Scalability
[ x] Policies and Telemetry
[ x] Security
[ x] Test and Release
[ x] User Experience
[ x] Developer Infrastructure

**Additional context**
I am looking for contributing to the existing code which can enable to use the same behavior as aws-alb-ingress-controller, possibly using the gateway+virtual service as rule to modify the rules to target group and using pods as target group members. The tricky part is the destination rule. Since some of the functionalities are overlapping in aws-alb-ingress-controller I am thinking if there is a way to delegate the actions of Gateway, VirtualService, and DestinationRule to some other controller.

**Comment by sdake** [comment]
@rverma-nikiai note currently we recommend using NLBs, although ALBs are known to work.  Feel free to propose your work to the istio/installer repo.

Cheers
-steve

**Comment by rverma-nikiai** [comment]
@sak0 I haven't started yet, I don't have enough clarity on where to start and how to proceed.

Some of the key components of ingress-gateways which can also be handled with ALB
1. API security (Cognito)
2. TLS, most of us still terminate TLA at the load balancer
3. Fine traffic shaping, though load balancer doesn't support this natively, the preferred way is to use Route53 to provide weight. This might require us to manage two ALB instances under different groups eg. current, canary. 

There are some disadvantages as well e.g. telemetry and policies would be limited, need to think about an end to end tracing, rate-limiting etc.

I still believe that with the out of box functionalities of ALB and directing traffic direct to pod(envoy-proxy) we can make the best of both worlds.

I believe we can connect online and can estimate what can we do?
