### ISSUE TITLE
istio-ingressgateway not listening on port 80/443

### ISSUE THREAD

**Issue by codingmaths** [istio/istio#15529]
We have installed istio-1.1.6 on our cluster 1.14.3. I can see all services has been installed successfully. but when I check istio-ingressgateway port 80 and 443 is not listening

**istio SVC**
`➜  helm k get svc
NAME                     TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                                                                                                                                    AGE
istio-citadel            ClusterIP   10.233.11.116   <none>        8060/TCP,15014/TCP                                                                                                                           14m
istio-galley             ClusterIP   10.233.61.88    <none>        443/TCP,15014/TCP,9901/TCP                                                                                                                   14m
istio-ingressgateway     NodePort    10.233.2.231    <none>        15020:31093/TCP,80:31380/TCP,443:31390/TCP,31400:31400/TCP,15029:30247/TCP,15030:31181/TCP,15031:31883/TCP,15032:31180/TCP,15443:30832/TCP   14m
istio-pilot              ClusterIP   10.233.45.7     <none>        15010/TCP,15011/TCP,8080/TCP,15014/TCP                                                                                                       14m
istio-policy             ClusterIP   10.233.21.167   <none>        9091/TCP,15004/TCP,15014/TCP                                                                                                                 14m
istio-sidecar-injector   ClusterIP   10.233.61.85    <none>        443/TCP                                                                                                                                      14m
istio-telemetry          ClusterIP   10.233.46.105   <none>        9091/TCP,15004/TCP,15014/TCP,42422/TCP                                                                                                       14m
prometheus               ClusterIP   10.233.13.168   <none>        9090/TCP                                                                                                                                     14m`

**Istio Ingress pod**
`➜  helm k get pods istio-ingressgateway-9c9474-kznqh
NAME                                READY   STATUS    RESTARTS   AGE
istio-ingressgateway-9c9474-kznqh   1/1     Running   0          13m`

**ingress pod ssh** 

> k exec -it istio-ingressgateway-9c9474-kznqh -- bash

> root@istio-ingressgateway-9c9474-kznqh:/# netstat -nultp
 > Active Internet connections (only servers)
 > Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
> tcp        0      0 0.0.0.0:15090           0.0.0.0:*               LISTEN      16/envoy
> tcp        0      0 127.0.0.1:15000         0.0.0.0:*               LISTEN      16/envoy
> tcp6       0      0 :::15020                :::*                    LISTEN      1/pilot-agent 

with logs everything is fine not sure what is the issue with port 80/443. 

I have tried Istio-1.1.8 as well facing same issue. 
Using [https://istio.io/docs/setup/kubernetes/install/helm/](url) for istio installation

**Comment by GregHanson** [comment]
@codingmaths do you have any Gateway rules created? 
```
istioctl get gateways --all-namespaces
```
Without any Gateway's defined, there will not be any ports open on the istio-ingressgateway

**Comment by codingmaths** [comment]
@GregHanson I haven't defined any gateway specifically . I am using nodeport for ingress. also how to create a gateway now

**Comment by GregHanson** [comment]
@codingmaths we have some doc and examples here:
https://istio.io/docs/tasks/traffic-management/ingress/ingress-control/
https://istio.io/docs/tasks/traffic-management/ingress/ingress-control/#configuring-ingress-using-an-istio-gateway

You will need a Gateway rule to expose a port and/hostname for incoming requests to the istio-ingressgateway and you will also need a corresponding VirtualService rule to define which istio managed service to route the incoming request to.  Hope that helps

**Comment by codingmaths** [comment]
Thanks for your support, it was a miss at my end. I got it resolved.

**Comment by mbehrisch** [comment]
> istioctl get gateways --all-namespaces

I know that this issue is closed, but could someone just state the _newer version_ of this command

**Comment by DonaldKellett** [comment]
> > istioctl get gateways --all-namespaces
> 
> I know that this issue is closed, but could someone just state the _newer version_ of this command

Seems like a typo, the correct command should be `kubectl get gateways --all-namespaces`
