### ISSUE TITLE
Create tests to compare helm output with iop

### ISSUE THREAD

**Issue by ostromart** [istio/istio#15534]
Tests are needed to compare the output from helm template with iop for a variety of parameter settings. There should be no diff between the outputs, which can be verified using a YAML diff tool.

**Comment by ostromart** [comment]
That's correct, but you can use some of the scripts in istio/installer to aggregate that - I think bin/iop should do it more or less.
fyi we also now have a sub-command iop diff-manifest (by @richardwxn) that can help with the diffing.

**Comment by morvencao** [comment]
Yes, That what I'm doing now:
1. Render the templates for each profile with `helm template`
2. Generate the manifest for the same profile with `iop manifest`
3. Compare the manifests with `iop diff-manifest` subcommand.
