### ISSUE TITLE
Add integration test case for an internal client calling an internal service, and the service is using a wrong certificate

### ISSUE THREAD

**Issue by JimmyCYJ** [istio/istio#15533]
Add integration test case for an internal client calling an internal service, and the service is using a wrong certificate. The test cases need to cover file mount and workload SDS.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**
https://github.com/istio/istio/issues/13439

**Comment by myidpt** [comment]
Thank you!
