### ISSUE TITLE
Pilot discovery container keeps crashing after injected sidecar, due to invalid virtualservice

### ISSUE THREAD

**Issue by patrickppeng** [istio/istio#15540]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
discovery container keeps crashing with SIGSEGV if auto sidecar injection enabled in cluster. Here is the stack trace (see full logs attached):

istio-citadel-76554d9779-xqt9b            1/1     Running            0          27h
istio-egressgateway-698d57c5d6-4dd5t      1/1     Running            0          27h
istio-galley-566847b9b4-z2lc8             1/1     Running            0          27h
istio-ingressgateway-7bdbbfc79-mt68w      1/1     Running            0          27h
istio-pilot-859fd7df87-f5cjl              1/2     CrashLoopBackOff   45         3h53m
istio-policy-7869b9864b-7q6vb             2/2     Running            7          27h
istio-sidecar-injector-6bf56bd554-lk9qq   1/1     Running            0          27h
istio-telemetry-6dc97fd4bd-rgp48          2/2     Running            7          27h

```
2019-07-15T19:23:41.916727Z     warn    Failed to find port for service default/analytics-event-normalizer: no suitable port for manifest: a403302f-a655-11e9-b604-005056be395c
2019-07-15T19:23:42.010041Z     info    ads     ADS:CDS: REQ 10.200.27.21:44192 sidecar~10.200.27.21~analytics-event-normalizer-744bfb445-fkv2f.default~default.svc.cluster.local-40 505.619918ms raw: version_info:"2019-07-15T19:12:05Z/2" node:<id:"sidecar~10.200.27.21~analytics-event-normalizer-744bfb445-fkv2f.default~default.svc.cluster.local" cluster:"istio-proxy.default" metadata:<fields:<key:"CONFIG_NAMESPACE" value:<string_value:"default" > > fields:<key:"INTERCEPTION_MODE" value:<string_value:"REDIRECT" > > fields:<key:"ISTIO_META_INSTANCE_IPS" value:<string_value:"10.200.27.21,10.200.27.21" > > fields:<key:"ISTIO_PROXY_SHA" value:<string_value:"istio-proxy:73fa9b1f29f91029cc2485a685994a0d1dbcde21" > > fields:<key:"ISTIO_PROXY_VERSION" value:<string_value:"1.1.3" > > fields:<key:"ISTIO_VERSION" value:<string_value:"1.1.6" > > fields:<key:"POD_NAME" value:<string_value:"analytics-event-normalizer-744bfb445-fkv2f" > > fields:<key:"app.kubernetes.io/instance" value:<string_value:"analytics" > > fields:<key:"app.kubernetes.io/name" value:<string_value:"analytics-event-normalizer" > > fields:<key:"checksum/config" value:<string_value:"64c762f112023e713ac9b6c5e6aad0b2d63bc3b100a3c1bb39961c17393ffc71" > > fields:<key:"istio" value:<string_value:"sidecar" > > fields:<key:"kubernetes.io/psp" value:<string_value:"00-default-psp" > > fields:<key:"pod-template-hash" value:<string_value:"744bfb445" > > fields:<key:"seccomp.security.alpha.kubernetes.io/pod" value:<string_value:"docker/default" > > > locality:<> build_version:"73fa9b1f29f91029cc2485a685994a0d1dbcde21/1.11.0-dev/Clean/RELEASE/BoringSSL" > type_url:"type.googleapis.com/envoy.api.v2.Cluster" response_nonce:"40e2e39f-e038-4d4e-bb8f-291c089345bb"
2019-07-15T19:23:42.115101Z     warn    Failed to find port for service default/analytics-dbmgr: no suitable port for manifest: a3bb5dff-a655-11e9-b604-005056be395c
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x158526f]

goroutine 476 [running]:
istio.io/istio/pilot/pkg/networking/core/v1alpha3/route.translateHeaderMatch(0xc4204f03da, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /workspace/go/src/istio.io/istio/pilot/pkg/networking/core/v1alpha3/route/route.go:563 +0x8f
istio.io/istio/pilot/pkg/networking/core/v1alpha3/route.translateRouteMatch(0xc420622540, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /workspace/go/src/istio.io/istio/pilot/pkg/networking/core/v1alpha3/route/route.go:519 +0x1b7
istio.io/istio/pilot/pkg/networking/core/v1alpha3/route.translateRoute(0xc4207bc500, 0xc4251fdc80, 0xc420cd0540, 0xc420622540, 0x50, 0x1c28bad, 0xf, 0x1c218d3, 0xa, 0x1c1f26d, ...)
        /workspace/go/src/istio.io/istio/pilot/pkg/networking/core/v1alpha3/route/route.go:321 +0xb1
istio.io/istio/pilot/pkg/networking/core/v1alpha3/route.BuildHTTPRoutesForVirtualService(0xc4251fdc80, 0xc4207bc500, 0x1c28bad, 0xf, 0x1c218d3, 0xa, 0x1c1f26d, 0x8, 0xc420a08b28, 0x12, ...)
        /workspace/go/src/istio.io/istio/pilot/pkg/networking/core/v1alpha3/route/route.go:260 +0x1d4
istio.io/istio/pilot/pkg/networking/core/v1alpha3.(*ConfigGeneratorImpl).buildGatewayHTTPRouteConfig(0xc4206f43c0, 0xc42050a640, 0xc4251fdc80, 0xc4207bc500, 0xc422fa8560, 0x3, 0x4, 0xc424353f98, 0x7, 0x1bb4f80, ...)
        /workspace/go/src/istio.io/istio/pilot/pkg/networking/core/v1alpha3/gateway.go:253 +0x769
istio.io/istio/pilot/pkg/networking/core/v1alpha3.(*ConfigGeneratorImpl).BuildHTTPRoutes(0xc4206f43c0, 0xc42050a640, 0xc4251fdc80, 0xc4207bc500, 0xc424353f98, 0x7, 0xc424985fc0, 0x10, 0x10)
        /workspace/go/src/istio.io/istio/pilot/pkg/networking/core/v1alpha3/httproute.go:43 +0xc4
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).generateRawRoutes(0xc4205ac370, 0xc424578a80, 0xc4207bc500, 0x0, 0x1, 0x1, 0x0, 0x1)
        /workspace/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/rds.go:60 +0x116
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).pushRoute(0xc4205ac370, 0xc424578a80, 0xc4207bc500, 0xc4264d9940, 0x3)
        /workspace/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/rds.go:28 +0x68
istio.io/istio/pilot/pkg/proxy/envoy/v2.(*DiscoveryServer).StreamAggregatedResources(0xc4205ac370, 0x1de1ea0, 0xc420cc4180, 0x0, 0x0)
        /workspace/go/src/istio.io/istio/pilot/pkg/proxy/envoy/v2/ads.go:519 +0x2014
istio.io/istio/vendor/github.com/envoyproxy/go-control-plane/envoy/service/discovery/v2._AggregatedDiscoveryService_StreamAggregatedResources_Handler(0x1c09100, 0xc4205ac370, 0x1ddb840, 0xc422e08000, 0x2a464b8, 0xc422f3a720)
        /workspace/go/src/istio.io/istio/vendor/github.com/envoyproxy/go-control-plane/envoy/service/discovery/v2/ads.pb.go:197 +0xb2
istio.io/istio/vendor/google.golang.org/grpc.(*Server).processStreamingRPC(0xc420458f00, 0x1de4000, 0xc423c0ef00, 0xc422f98000, 0xc4205abda0, 0x2a0e500, 0xc422f3a6c0, 0x0, 0x0)
        /workspace/go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:1124 +0x911
istio.io/istio/vendor/google.golang.org/grpc.(*Server).handleStream(0xc420458f00, 0x1de4000, 0xc423c0ef00, 0xc422f98000, 0xc422f3a6c0)
        /workspace/go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:1212 +0x12b1
istio.io/istio/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc4227e60d0, 0xc420458f00, 0x1de4000, 0xc423c0ef00, 0xc422f98000)
        /workspace/go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:686 +0x9f
created by istio.io/istio/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
        /workspace/go/src/istio.io/istio/vendor/google.golang.org/grpc/server.go:684 +0xa1
~
```
**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**
We have a list of deployments (~90) and around 130 pods deployed
[cust@flex-201 ~]$ sudo kubectl get deployment --all-namespaces
NAMESPACE        NAME                                                READY   UP-TO-DATE   AVAILABLE   AGE
avaya-kafka      eventing-kafka-cp-kafka-connect                     1/1     1            1           4h39m
avaya-kafka      eventing-kafka-cp-schema-registry                   1/1     1            1           4h39m
avaya-kafka      eventing-kafka-topic-operator                       1/1     1            1           4h39m
default          admin-cc-attribute-admin-portal-plugin              1/1     1            1           27h  
default          admin-cc-elite-admin-portal-plugin                  1/1     1            1           27h  
default          admin-cc-user-admin-portal-plugin                   1/1     1            1           27h  
default          admin-portal-service                                1/1     1            1           27h  
default          adp-bpm-service                                     1/1     1            1           27h  
default          adp-broadcast-service                               1/1     1            1           27h  
default          adp-cis-service                                     0/1     1            0           27h  
default          adp-notification-service                            1/1     1            1           27h  
default          adp-request-validation-service                      1/1     1            1           27h  
default          adp-sec-service                                     1/1     1            1           27h  
default          alarming-db-common-services                         1/1     1            1           27h  
default          alarming-service                                    1/1     1            1           27h  
default          analytics-analytics-admin-service                   1/1     1            1           27h  
default          analytics-analytics-cumulative-proc                 1/1     1            1           27h  
default          analytics-analytics-dimension-data-consolidator     1/1     1            1           27h  
default          analytics-analytics-dimension-database-adaptor      1/1     1            1           27h  
default          analytics-analytics-event-filter                    0/1     1            0           27h  
default          analytics-analytics-historical-stats-adaptor        1/1     1            1           27h  
default          analytics-analytics-historical-stats-consolidator   1/1     1            1           27h  
default          analytics-analytics-journal-database-adaptor        1/1     1            1           27h  
default          analytics-analytics-measure-aggregator              1/1     1            1           27h  
default          analytics-analytics-passthrough-proc                1/1     1            1           27h  
default          analytics-analytics-sem                             0/1     1            0           27h  
default          analytics-analytics-streams-rest                    1/1     1            1           27h  
default          analytics-analytics-streams-websocket-sender        1/1     1            1           27h  
default          analytics-dbmgr                                     1/1     1            1           27h  
default          analytics-dsi                                       1/1     1            1           27h  
default          analytics-duration-proc                             1/1     1            1           27h  
default          analytics-event-normalizer                          1/1     1            1           27h  
default          analytics-itd-consolidator                          1/1     1            1           27h  
default          analytics-journal-consolidator                      1/1     1            1           27h  
default          analytics-measure-management                        1/1     1            1           27h  
default          analytics-measure-registration                      1/1     1            1           27h  
default          analytics-rbac-service                              1/1     1            1           27h  
default          antivirus-umr                                       1/1     1            1           27h  
default          authdb-common-services                              1/1     1            1           27h  
default          bre-service                                         3/3     3            3           27h  
default          cc-admin-attribute                                  1/1     1            1           27h  
default          cc-admin-elite                                      1/1     1            1           27h  
default          cc-admin-postgres-admin                             1/1     1            1           27h  
default          cc-admin-user                                       1/1     1            1           27h  
default          cert-manager-certmgmt-agent                         1/1     1            1           27h  
default          cert-manager-certmgmt-service                       1/1     1            1           27h  
default          cert-manager-database-cert-manager                  1/1     1            1           27h  
default          cm-service                                          1/1     1            1           27h  
default          cmonitor                                            1/1     1            1           27h  
default          common-services-grafana                             1/1     1            1           27h  
default          common-services-kube-state-metrics                  1/1     1            1           27h  
default          common-services-logging-service                     1/1     1            1           27h  
default          common-services-prometheus-operator                 1/1     1            1           27h  
default          crunchy-watch-analytics                             1/1     1            1           27h  
default          custom-channel-msg-agent-controller                 1/1     1            1           27h
default          custom-channel-msg-cc-routing                       1/1     1            1           27h
default          custom-channel-msg-conversation-manager             1/1     1            1           27h
default          custom-channel-msg-session-manager                  1/1     1            1           27h
default          custom-channel-msg-web-connector                    1/1     1            1           27h
default          customer-journey-customer-journey-etl               1/1     1            1           27h
default          customer-journey-journey-service                    1/1     1            1           27h
default          db-postgres-aps-uwf                                 1/1     1            1           27h
default          db-postgres-cmservice-cm                            1/1     1            1           27h
default          db-postgres-inv-uwf                                 1/1     1            1           27h
default          db-postgres-org-users                               1/1     1            1           27h
default          db-postgres-user-users                              1/1     1            1           27h
default          ecc-service                                         1/1     1            1           27h
default          ecc-ui-service                                      1/1     1            1           27h
default          inventory-service                                   1/1     1            1           27h
default          ix-deskconn-ix-dsk-admin-connector                  1/1     1            1           27h
default          ix-deskconn-ix-dsk-connector                        1/1     1            1           27h
default          ixo-licensing-licensing-service                     1/1     1            1           27h
default          mysql-umr                                           1/1     1            1           27h
default          org-service                                         1/1     1            1           27h
default          owncloud-umr                                        1/1     1            1           27h
default          rbac-deployment                                     1/1     1            1           27h
default          redis-slave                                         1/1     1            1           27h
default          umr                                                 1/1     1            1           27h
default          user-service                                        1/1     1            1           27h
default          uwf-client                                          1/1     1            1           27h
default          uwf-query-service                                   1/1     1            1           27h
default          uwf-redis-slave                                     1/1     1            1           27h
default          uwf-registry                                        1/1     1            1           27h
default          vrc-voice-api-service                               1/1     1            1           27h
default          vrc-vrc-availability-service                        1/1     1            1           27h
default          vrc-vrc-conv-rekey-service                          1/1     1            1           27h
default          vrc-vrc-elite-connector                             2/2     2            2           27h
default          vrc-vrc-elite-connector-adaptor                     1/1     1            1           27h
default          vrc-vrc-login-service                               1/1     1            1           27h
default          vrc-vrc-matching-service                            1/1     1            1           27h
default          vrc-vrc-matching-service-rest                       1/1     1            1           27h
default          vrc-vrc-ready-service                               1/1     1            1           27h
default          workspaces-content-service                          0/1     1            0           27h
image-registry   registry                                            1/1     1            1           27h
istio-system     istio-citadel                                       1/1     1            1           27h
istio-system     istio-egressgateway                                 1/1     1            1           27h
istio-system     istio-galley                                        1/1     1            1           27h
istio-system     istio-ingressgateway                                1/1     1            1           27h
istio-system     istio-pilot                                         0/1     1            0           3h42m
istio-system     istio-policy                                        1/1     1            1           27h
istio-system     istio-sidecar-injector                              1/1     1            1           27h
istio-system     istio-telemetry                                     1/1     1            1           27h
kube-system      coredns                                             3/3     3            3           28h
kube-system      metrics-server                                      1/1     1            1           27h
kube-system      tiller-deploy                                       1/1     1            1           27h

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Istio-1.1.6
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
helm

**Environment where bug was observed (cloud vendor, OS, etc)**
RHEL7.6

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.
[discovery2.log](https://github.com/istio/istio/files/3393983/discovery2.log)
[discovery3.log](https://github.com/istio/istio/files/3393984/discovery3.log)
[discovery.log](https://github.com/istio/istio/files/3393985/discovery.log)
[discovery1.log](https://github.com/istio/istio/files/3393986/discovery1.log)

**Comment by howardjohn** [comment]
Looks like crash is here https://github.com/istio/istio/blob/1.1.6/pilot/pkg/networking/core/v1alpha3/route/route.go#L563

Do you have a virtualservice with a missing header match or something?

Something like
```yaml
  http:
  - match:
    - headers:
        end-user: # nil here!
```

**Comment by patrickppeng** [comment]
yes, I found one of the virtualservice as:

- apiVersion: networking.istio.io/v1alpha3
  kind: VirtualService
  metadata:
    creationTimestamp: "2019-07-14T16:47:30Z"
    generation: 1
    name: uwf-virtualservice
    namespace: default
    resourceVersion: "14033"
    selfLink: /apis/networking.istio.io/v1alpha3/namespaces/default/virtualservices/uwf-virtualservice
    uid: 11b5034b-a657-11e9-b604-005056be395c
  spec:
    gateways:
    - default-ingressgateway
    hosts:
    - '*'
    http:
    - match:
      - headers:
          cookie: null
        uri:
          prefix: /services/ApplicationCenter
      rewrite:
        uri: /
      route:
      - destination:
          host: uwf-client
          port:
            number: 8080
    - match:
      - headers:
          cookie: null
        uri:
          prefix: /assets/css/neo.min.css
      rewrite:
        uri: /assets/css/neo.min.css
      route:
      - destination:
          host: uwf-client
          port:
            number: 8080
    - match:
      - uri:
          prefix: /services/ApplicationCenter
      route:
      - destination:
          host: uwf-client
          port:
            number: 80

**Comment by howardjohn** [comment]
Great, does fixing that one solve the issue? sounds like we just need to reject this config as invalid

**Comment by patrickppeng** [comment]
I don't know what the intention the service developer tried to do... in virtualservice, how to define a match header with "null" cookie?

**Comment by patrickppeng** [comment]
yes, it solved the issue after removed the "cookie: null" header
  - match:
    - uri:
        prefix: /services/ApplicationCenter
    rewrite:
      uri: /
    route:
    - destination:
        host: uwf-client
        port:
          number: 8080
  - match:
    - uri:
        prefix: /assets/css/neo.min.css
    rewrite:
      uri: /assets/css/neo.min.css
    route:
    - destination:
        host: uwf-client
        port:
          number: 8080

**Comment by patrickppeng** [comment]
is it possible to add error handling or null validation in this function without crashing the container?

**Comment by howardjohn** [comment]
I am not sure what you mean, once #15549 is merged this config will get rejected by `kubectl apply`, so it will never get to the crashing function?

**Comment by patrickppeng** [comment]
oops! just saw the Reject null header matches... thanks again John.

**Comment by howardjohn** [comment]
No problem, thanks for finding this. I am hoping to get some fuzzing working for pilot so this would be caught but haven't gotten it up and running yet
