### ISSUE TITLE
Make it easy to add custom CA root certificates to istio-proxy

### ISSUE THREAD

**Issue by flatmap13** [istio/istio#15558]
**Describe the feature request**
Make it possible to add custom CA root certificates to auto-injected istio-proxy (sidecar) containers.

**Describe alternatives you've considered**
n/a

**Affected product area (please put an X in all that apply)**

[x] Configuration Infrastructure
[x] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by costinm** [comment]
This is related to the root ca rotation and multicluster setup, work in progress - we must get it in.

**Comment by myidpt** [comment]
We may already support it. We need to verify adding extra roots to the file works. Will provide docs about this, and add integration tests.

**Comment by duderino** [comment]
@myidpt can you link to the solution documentation?  Also what is the minimum Istio release version?
