### ISSUE TITLE
helm delete - does not remove namespace

### ISSUE THREAD

**Issue by kubesure** [istio/istio#15554]
**Bug description**
helm delete does not remove istio-system namespace. 

helm delete --purge istio
helm delete --purge istio-init

**Affected product area (please put an X in all that apply)**

[X] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Istio-system is active after helm delete and purge

**Steps to reproduce the bug**

helm delete --purge istio
helm delete --purge istio-init

k get po -n istio-system

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

Version: 1.0.5
GitRevision: c1707e45e71c75d74bf3a5dec8c7086f32f32fad
User: root@6f6ea1061f2b
Hub: docker.io/istio
GolangVersion: go1.10.4
BuildStatus: Clean

Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**

using helm

**Environment where bug was observed (cloud vendor, OS, etc)**

AWS EC2

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
I think this is just the behavior of helm - see https://github.com/helm/helm/issues/1464

Is there anything else we can do?
