### ISSUE TITLE
Not clear how VirtualService is supposed to work

### ISSUE THREAD

**Issue by qfel** [istio/istio#15567]
**Bug description**
When using VirtualService in conjunction with the **mesh** gateway, it is not clear what the resulting semantics should be. In particular, how hosts declared in VritualService overlap with hosts owned by K8s Services (or rather, Istio ServiceEntries?) seems to affect what hosts and ports Envoy listens on, but the result doesn't make much sense. Eg. I get listeners on port 80 which comes out of nowhere, sometimes domain expansion is performed, sometimes only FQDN is used. Port filters in `HTTPMatchRequest.port` seem to get ignored.

My best (empirical) understanding of the current algorithm is:
- VirtualService generates one set of rules that gets appended to multiple virtual hosts (existing or new)
- For each host, create an Envoy virtual host on port 80 (no domain expansion)
- For each host matching a ServiceEntry, append rules to its existing Envoy virtual host (those do have expansion and usually listen on non-80 ports)
- Also create virtual hosts for hosts not matching ServiceEntries, but on ports of ServiceEntries matched by other hosts of the VirtualService

Or something like that. Feels messy.

We should document what the precise behavior should be (such that it is possible to write code based on that) and then fix the current implementation to conform to it.

See the [doc](https://docs.google.com/document/d/1ENq0n7JalqlQ7CP7Xy3n3p2mbtKn9dJfttha6GZLcJA) for a more concrete example.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by qfel** [comment]
FYI @howardjohn @andraxylia @duderino

**Comment by qfel** [comment]
FYI @louiscryan

**Comment by andraxylia** [comment]
There is nothing unclear in the API, just a bug in Pilot. Under no circumstance with the given config, should Pilot generate outbound clusters to reach svc A on port 80. My only hope is those clusters ("cluster": "outbound|80||svc-a.default.svc.cluster.local") have zero endpoints, otherwise we have bigger troubles.

**Comment by andraxylia** [comment]
cc @costinm

**Comment by andraxylia** [comment]
VirtualService behavior for traffic matching should be as follows:
- if the hosts points to an existing service from the service registry (native or ServiceEntry), the ports for matching can be inferred and Pilot should generate Envoy virtual_hosts for host+port, for each port of the service
- for BYON (bring your own name) hosts aliases, the port cannot be inferred. If the VS is attached to a Gateway, we can infer the ports from the Gateway. If the VS is attached to the "mesh", there is currently no way to infer the port. Current code assumes port 80, so BYON for mesh services on port 80 will still work. Any services not using port 80 become inaccessible. The workaround is to include the port in the hosts field, ex: "byon.com:9083". We need an VirtualService API change where the port either becomes part of the hosts field, or a field on its own.

**Comment by andraxylia** [comment]
For all VirtualServices applied to mesh config, there is determinism if the port is explicitly configured in the [match rule](https://github.com/istio/api/blob/master/networking/v1alpha3/virtual_service.proto#L653). This can function in the absence of the API or semantic changes I was suggesting, albeit it requires more configuration.

For VirtualServices applied to the Gateway, the traffic can only come via one of the Gateway ports. An explicit port configuration on a VS, in the match rule or elsewhere, makes it not portable on both mesh gateways and ingress gateways.
