### ISSUE TITLE
istio-cni daemonset shall use "apiVersion: apps/v1" instead of "extensions/v1beta1"

### ISSUE THREAD

**Issue by hobbytp** [istio/istio#15572]
**Bug description**
I think istio-cni DaemonSet shall use "apiVersion: apps/v1" instead of "extensions/v1beta1", is there any concert to still use extensions/v1beta1 in 1.2.2?

**Affected product area (please put an X in all that apply)**

[x] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
Whtat is your use case for not wanting to us apps/v1?

**Comment by hobbytp** [comment]
> Whtat is your use case for not wanting to us apps/v1?

no, I want to use apps/v1 instead of extensions/v1beta1.

**Comment by howardjohn** [comment]
oops, I misunderstood that. We absolutely want to use apps/v1. This is a high priority for 1.3 as the old ones will be removed in the next k8s version

**Comment by hobbytp** [comment]
cool, thanks,

**Comment by howardjohn** [comment]
We are tracking this in https://github.com/istio/istio/issues/12211 as a P0 for 1.3
