### ISSUE TITLE
how istio gateway and virtualservice support  cookie and request arg_xxx

### ISSUE THREAD

**Issue by bruse-peng** [istio/istio#15570]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

according the official document，gateway and virtualservice support url route rule，but how i  can set the route rule according the request agrs or request cookie. and  satisfied request agrs  and request cookie at the same time

**Comment by hzxuzhonghu** [comment]
https://istio.io/docs/reference/config/networking/v1alpha3/destination-rule/

```
//
// The following example sets up sticky sessions for the ratings service
// hashing-based load balancer for the same ratings service using the
// the User cookie as the hash key.
//
// ```yaml
//  apiVersion: networking.istio.io/v1alpha3
//  kind: DestinationRule
//  metadata:
//    name: bookinfo-ratings
//  spec:
//    host: ratings.prod.svc.cluster.local
//    trafficPolicy:
//      loadBalancer:
//        consistentHash:
//          httpCookie:
//            name: user
//            ttl: 0s
// ```
```
