### ISSUE TITLE
Adding common labels to e2e tests

### ISSUE THREAD

**Issue by johscheuer** [istio/istio#15576]
**Describe the feature request**

I would like to add a set of common labels to the istio e2e tests e.g.:

```yaml
labels:
  istio.io/e2e-test: simple
  istio.io/e2e-testrun: simple-ingress
```

This makes a clean/debugging up after the e2e tests easier e.g. if some hanging resources or if you want to use some of the tests as "conformance" tests. In a perfect world these labels would be automatically added to the resources during creation without the need to specify something in the resource definitions.

**Describe alternatives you've considered**

I took a look at the current setup and it seems that there are no common labels for the resources created during the e2e tests. I borrowed the idea mainly from the Kubernetes e2e/conformance tests.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[X] Test and Release
[ ] User Experience
[X] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
The e2e tests are mostly considered legacy, all new tests are being written in tests/integration. This has some more sophisticated resource tracking, although not based on labels. You may be particularly interested in `tests/integration/conformance`

**Comment by johscheuer** [comment]
Thanks for your response ! If the e2e tests are mostly legacy (or vintage ;)) a little note about this should be put inside the readme https://github.com/istio/istio/tree/master/tests/e2e ?

**Comment by johscheuer** [comment]
Close this issue since like howard said the e2e tests are mostly considered legacy.
