### ISSUE TITLE
when i access the application  it return 404

### ISSUE THREAD

**Issue by bruse-peng** [istio/istio#15574]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

when i access the application  it return 404,below is my configuration

![image](https://user-images.githubusercontent.com/47881861/61345749-e905c980-a888-11e9-83fe-d4d481118ca5.png)
![image](https://user-images.githubusercontent.com/47881861/61345776-0470d480-a889-11e9-9a10-7baf09c3e812.png)

**Comment by dpiessens** [comment]
Disclaimer: I'm not on the Istio team, just another user who has spent some time with it.

Here's a few things to check:
- Do you have MTLS enabled? If so make sure that auth is working the way you expect it.
- Did you version the Deployment / Service with labels? If so, do you have a DestinationRule for versioning?
- Is the service working and have running pods?

I've discovered that Kiali is useful in debugging and graphing the traffic flow. Also looking at the ingress gateway logs can help with routing.

**Comment by bruse-peng** [comment]
mime istio version is 1.0.0,but it's Virtual Service not support queryParams.  is it right?
