### ISSUE TITLE
Check if KinD supports Trustworthy Jwts.

### ISSUE THREAD

**Issue by pitlv2109** [istio/istio#15607]
From https://github.com/istio/istio/pull/15568.

Trustworthy Jwt type is available from v1.12 and later.

The `sds_citadel_flow_test` passed in my v1.12.x and v1.13.x GKE clusters. However, it's failing in KinD (kindest/node:v1.14.2). Reason of failing is control plane components with sidecar (e.g. Pilot, Mixer, etc.) failed to deploy. My guess is that KinD was having problems with trustworthy jwts so it couldn't spin up the containers. I don't have access to Prow clusters so it's hard to debug. 

Logs: https://prow.istio.io/log?id=3081&job=integ-security-k8s-presubmit-tests-master 

One way to test this is create a simple test using the new test framework with these extra config (similar to my PR) to see if Istio can be deployed.
```
cfg.Values["global.controlPlaneSecurityEnabled"] = "false"
cfg.Values["global.mtls.enabled"] = "true"
cfg.Values["global.sds.enabled"] = "true"
cfg.Values["global.sds.udsPath"] = "unix:/var/run/sds/uds_path"
// Trustworthy JWTs are available in Kubernetes 1.12 (beta) and later.
cfg.Values["global.sds.useTrustworthyJwt"] = "true"
cfg.Values["nodeagent.enabled"] = "true"
cfg.Values["nodeagent.image"] = "node-agent-k8s"
cfg.Values["nodeagent.env.CA_PROVIDER"] = "Citadel"
cfg.Values["nodeagent.env.CA_ADDR"] = "istio-citadel:8060"
cfg.Values["nodeagent.env.VALID_TOKEN"] = "true"
```

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[X] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by pitlv2109** [comment]
I don't have access to Prow and I'm not really familiar with KinD, can one of you guys see if you can deploy Istio in a test with those config? @fejta @howardjohn @utka @icygalz.

**Comment by fejta** [comment]
The kind utility can create a local cluster using any version of kubernetes. You can build your own images, and releases ship with their own set of prebuilt images. See https://github.com/kubernetes-sigs/kind/releases/tag/v0.4.0 for instructions for how to create a cluster using 1.13:

```console
$ kind create cluster --image=kindest/node:v1.13.7@sha256:f3f1cfc2318d1eb88d91253a9c5fa45f6e9121b6b1e65aea6c7ef59f1549aaaf
```

**Comment by pitlv2109** [comment]
So looks like k8s on KinD node v1.14.2 (which is prow is using) can not deploy Istio because of trustworthy jwts. I also tested with KinD newest verion 1.15.

Logs from Pilot
```
  Warning  FailedMount  50s                kubelet, kind-control-plane  MountVolume.SetUp failed for volume "istio-pilot-service-account-token-22h8l" : couldn't propagate object cache: timed out waiting for the condition
  Warning  FailedMount  50s                kubelet, kind-control-plane  MountVolume.SetUp failed for volume "istio-certs" : couldn't propagate object cache: timed out waiting for the condition
  Warning  FailedMount  14s (x7 over 47s)  kubelet, kind-control-plane  MountVolume.SetUp failed for volume "istio-token" : failed to fetch token: the server could not find the requested resource
```

@myidpt @quanjielin. How do you guys want to proceed? We can change the SDS Citadel flow test to use legacy jwts for short-term, unless fixing this KinD issue does not require a lot of time. Again, the test runs fine on GKE clusters with version 1.12 or higher.

**Comment by quanjielin** [comment]
@pitlv2109 using legacy jwt in test sounds good to me.

**Comment by howardjohn** [comment]
> Again, the test runs fine on GKE clusters with version 1.12 or higher

just because it works on GKE doesn't mean it is standard. Afaik kind is a fully compliant k8s distribution so if it isn't enabled by default there then it may not be in other platforms. at the very least we should document this

**Comment by pitlv2109** [comment]
> > Again, the test runs fine on GKE clusters with version 1.12 or higher
> 
> just because it works on GKE doesn't mean it is standard. Afaik kind is a fully compliant k8s distribution so if it isn't enabled by default there then it may not be in other platforms. at the very least we should document this

Yes. I'll investigate more on this.
