### ISSUE TITLE
Basic authentication in Istio

### ISSUE THREAD

**Issue by suneeshkumar-urolime** [istio/istio#15618]
We have a couple of services running with Istio and we need to add basic authentication with credentials saved in a k8s secret. Is there any possibility to implement basic authentication for a service using Istio as we do with Nginx Ingress controller, Ref link: https://kubernetes.github.io/ingress-nginx/examples/auth/basic/  ?

**Comment by elevran** [comment]
Istio currently support [end user authentication based on JTW](https://istio.io/docs/ops/security/end-user-auth/).
Otherwise, you could implement basic authorization by creating a mixer adapter that responds to Check() calls. It can provide whatever custom logic needed (e.g., realm, messages, etc.)

**Comment by fentas** [comment]
duplicate of https://github.com/istio/istio/issues/4693

**Comment by yangminzhu** [comment]
Closing as it's a duplicate of #4693
