### ISSUE TITLE
Injected sidecar's do not update when the global.proxy Values are updated

### ISSUE THREAD

**Issue by meganwalker-ibm** [istio/istio#15617]
**Bug description**

When you update the Values file and re-assert the helm install of istio, changes to the `global.proxy` section do not appear to cause already injected sidecars to be updated.

**Affected product area (please put an X in all that apply)**
(I've put some best guesses in here, it's not clear to me what 'istio-proxy auto-injection configuration during an upgrade would fall under)

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Changes to the `global.proxy` section of the helm values file (e.g. `global.proxy.excludeIPRanges`) should trigger sidecars that have already been injected to be updated to follow the new configuration.

**Steps to reproduce the bug**
(NB: I've used example.com for this example. As far as I can tell the domain always resolves to one consistent IP, but it might be worth checking that or using a different domain with a known-static IP instead).
Install istio with the following values yaml being applied over the top.
```
global:
  proxy:
    includeIPRanges: "*"
    excludeIPRanges: "93.184.216.34" # Example.com IP
  outboundTrafficPolicy:
    mode: REGISTRY_ONLY
```
to exclude example.com from going through the cluster, and also restrict traffic to only entries with a ServiceEntry.

Configure sidecare autoinjection as per the docs
`kubectl label namespace default istio-injection=enabled`

Deploy a sample container that you can use to curl `example.com`

Note that you have not provided a ServiceEntry, thus when you curl to `https://example.com` it succeeds due to the `excludeIPRanges` clause in the configuration.

Now do a `helm upgrade` of istio with the following values yaml being applied over the top of the chart
```
global:
  proxy:
    includeIPRanges: "*"
    excludeIPRanges: "" # No excluded IPs
  outboundTrafficPolicy:
    mode: REGISTRY_ONLY
```
Note that the auto-injected sidecar did not appear to reload.
If you try and curl to example.com again, it will still succeed.
If you do a `kubectl describe pod <pod>`and look at the `istio-init` container, you will see it still has the old excludeIPRanges set.

If you manually kill  the pod `kubectl delete pod <pod>` and allow it to be reinitialised, it will have the new config and talking to example.com will fail.

I would have expected the new config to be applied to existing injected sidecars (gracefully). Instead we appear to need to trigger a graceful start-up of all the pods (~200) ourselves.....

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.8+IKS", GitCommit:"fe3e332c2b0f47d4572433c3b0a1687a27fb88c6", GitTreeState:"clean", BuildDate:"2019-07-11T13:45:03Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```
```
client version: version.BuildInfo{Version:"1.1.6", GitRevision:"04850e14d38a69a38c16c800e237b1108056513e", User:"root", Host:"1844d064-72cc-11e9-a0d5-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.5-11-g04850e1"}
citadel version: version.BuildInfo{Version:"1.1.6", GitRevision:"04850e14d38a69a38c16c800e237b1108056513e-dirty", User:"root", Host:"1844d064-72cc-11e9-a0d5-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.5-11-g04850e1"}
galley version: version.BuildInfo{Version:"1.1.6", GitRevision:"04850e14d38a69a38c16c800e237b1108056513e-dirty", User:"root", Host:"1844d064-72cc-11e9-a0d5-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.5-11-g04850e1"}
ingressgateway version: version.BuildInfo{Version:"1.1.6", GitRevision:"04850e14d38a69a38c16c800e237b1108056513e", User:"root", Host:"1844d064-72cc-11e9-a0d5-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.5-11-g04850e1"}
ingressgateway version: version.BuildInfo{Version:"1.1.6", GitRevision:"04850e14d38a69a38c16c800e237b1108056513e", User:"root", Host:"1844d064-72cc-11e9-a0d5-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.5-11-g04850e1"}
ingressgateway version: version.BuildInfo{Version:"1.1.6", GitRevision:"04850e14d38a69a38c16c800e237b1108056513e", User:"root", Host:"1844d064-72cc-11e9-a0d5-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.5-11-g04850e1"}
pilot version: version.BuildInfo{Version:"1.1.6", GitRevision:"04850e14d38a69a38c16c800e237b1108056513e-dirty", User:"root", Host:"1844d064-72cc-11e9-a0d5-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.5-11-g04850e1"}
pilot version: version.BuildInfo{Version:"1.1.6", GitRevision:"04850e14d38a69a38c16c800e237b1108056513e-dirty", User:"root", Host:"1844d064-72cc-11e9-a0d5-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.5-11-g04850e1"}
pilot version: version.BuildInfo{Version:"1.1.6", GitRevision:"04850e14d38a69a38c16c800e237b1108056513e-dirty", User:"root", Host:"1844d064-72cc-11e9-a0d5-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.5-11-g04850e1"}
pilot version: version.BuildInfo{Version:"1.1.6", GitRevision:"04850e14d38a69a38c16c800e237b1108056513e-dirty", User:"root", Host:"1844d064-72cc-11e9-a0d5-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.5-11-g04850e1"}
pilot version: version.BuildInfo{Version:"1.1.6", GitRevision:"04850e14d38a69a38c16c800e237b1108056513e-dirty", User:"root", Host:"1844d064-72cc-11e9-a0d5-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.5-11-g04850e1"}
policy version: version.BuildInfo{Version:"1.1.6", GitRevision:"04850e14d38a69a38c16c800e237b1108056513e-dirty", User:"root", Host:"1844d064-72cc-11e9-a0d5-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.5-11-g04850e1"}
sidecar-injector version: version.BuildInfo{Version:"1.1.6", GitRevision:"04850e14d38a69a38c16c800e237b1108056513e-dirty", User:"root", Host:"1844d064-72cc-11e9-a0d5-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.5-11-g04850e1"}
telemetry version: version.BuildInfo{Version:"1.1.6", GitRevision:"04850e14d38a69a38c16c800e237b1108056513e-dirty", User:"root", Host:"1844d064-72cc-11e9-a0d5-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.5-11-g04850e1"}
```

(I'm aware we're somewhat backlevel on our istio version, but a read of the changelog doesn't seem to indicate anything that would have fixed this. I'm working on getting this reproduced on 1.2.2 at the moment)

**How was Istio installed?**

CRDs via the install/kubernetes/helm/istio-init/files/crd*.yaml files
Istio via `helm upgrade istio install/kubernetes/helm/istio --install --namespace istio-system --values ${ISTIO_VALUES_FILE}`

**Environment where bug was observed (cloud vendor, OS, etc)**
IBM Kubernetes Service

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
This is expected. Please see https://istio.io/docs/setup/kubernetes/upgrade/steps/#sidecar-upgrade

Currently the only way to upgrade the sidecars is to kill your pod, as you saw. This is generally not something that is a good idea for us to do automatically (or likely even possible using helm).

In the future we may have the Envoy's run outside of the pod, in which case we would have full control of them and could update them independently (possibly, I am not sure if this is the case)

**Comment by meganwalker-ibm** [comment]
Hmm, it's interesting that you don't think is a good idea.

I was thinking of this as analogous to the situation that something like [Wave](https://github.com/pusher/wave) tries to solve.

Wave, in a nutshell, watches for changes to ConfigMaps or Secrets, and then goes and triggers a change to Deployments that use those changed resources which causes a rolling update of those pods, in accordance with the deployments configured rolling update strategy, to force them to notice the new ConfigMaps or Secret values, to ensure any changes are reflected in the running code.

This seems like an analogous situation - the user has indicated a desired change to a resource, but other resources that depend on that aren't updating automatically

Can you elaborate a bit on why you consider this to be a bad idea?

**Comment by howardjohn** [comment]
Maybe not a "bad idea" but "not always a good idea". There are plenty of applications that users wouldn't want killed (maybe databases, etc), users may want to slowly test out the proxy upgrade, etc. Additionally we don't really have a way to accomplish this right now. There is work on github.com/Istio/operator that could eventually handle this type of thing.

I think I'm some form we will probably support this in the future but it is not quite there yet

**Comment by sdake** [comment]
@clyang82 why don't you consider taking a crack out how to solve this in a bigger context of reconfigure of the `data plane` within the operator repo.

Cheers
-steve
