### ISSUE TITLE
migrate cni circleci jobs to prow

### ISSUE THREAD

**Issue by sdake** [istio/istio#15622]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
move circleci jobs to prow.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[X] Developer Infrastructure

**Expected behavior**
All CI jobs run in prow.

**Comment by sdake** [comment]
Note you can take a look at these jobs to get a basic idea of how to move off circleci to prow:
https://github.com/istio/test-infra/blob/master/prow/cluster/jobs/istio/operator/istio.operator.master.yaml

Cheers
-steve

**Comment by sdake** [comment]
note for any complex tasks, make targets should be used, rather than adding a bunch of junk to the prow job.

Cheers :)
-steve

**Comment by howardjohn** [comment]
This is done except the ipv6 which is not feasible to move

**Comment by howardjohn** [comment]
We have no feasible way to migrate the ipv6 on prow right now
