### ISSUE TITLE
mixer produces errors during graceful shutdown of adapter pods

### ISSUE THREAD

**Issue by gotwarlost** [istio/istio#15638]
**Bug description**

`istio-policy` pods call out to our custom adapters for policy checks. We notice that every time an adapter pod is killed (either due to a deployment or an eviction), a small set of requests from mixer fail. 

We tried adding a prestop hook of `sleep 30` to the adapter pods to give mixer a chance to update its endpoints but that seems to have no effect. My hypothesis is that these are persistent grpc connections that only fail when the adapter pod closes the connection. (I haven't dug into how this works so I may be totally offbase).

Is this a known issue and, if so, is there a workaround to get zero-downtime deployments of adapter pods?

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ X] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

100% of policy checks succeed during a rolling update of adapter pods.

**Steps to reproduce the bug**
Will update shortly

**How was Istio installed?**
helm charts

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

```
client version: version.BuildInfo{Version:"1.1.2", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989", User:"root", Host:"35adf5bb-5570-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.1"}
citadel version: version.BuildInfo{Version:"1.1.8", GitRevision:"145b18a441045d6fad33d7916380d8642c7bf21d-dirty", User:"root", Host:"11387264-87af-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.7-14-g145b18a"}
galley version: version.BuildInfo{Version:"1.1.8", GitRevision:"145b18a441045d6fad33d7916380d8642c7bf21d-dirty", User:"root", Host:"11387264-87af-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.7-14-g145b18a"}
pilot version: version.BuildInfo{Version:"1.1.8", GitRevision:"145b18a441045d6fad33d7916380d8642c7bf21d-dirty", User:"root", Host:"11387264-87af-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.7-14-g145b18a"}
policy version: version.BuildInfo{Version:"1.1.8", GitRevision:"145b18a441045d6fad33d7916380d8642c7bf21d-dirty", User:"root", Host:"11387264-87af-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.7-14-g145b18a"}
sidecar-injector version: version.BuildInfo{Version:"1.1.8", GitRevision:"145b18a441045d6fad33d7916380d8642c7bf21d-dirty", User:"root", Host:"11387264-87af-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.7-14-g145b18a"}
telemetry version: version.BuildInfo{Version:"1.1.8", GitRevision:"145b18a441045d6fad33d7916380d8642c7bf21d-dirty", User:"root", Host:"11387264-87af-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.7-14-g145b18a"}
```

```Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:46:06Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.8", GitCommit:"4e209c9383fa00631d124c8adcc011d617339b3c", GitTreeState:"clean", BuildDate:"2019-02-28T18:40:05Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by gotwarlost** [comment]
Errors are of the form:

```
2019-07-18T23:14:27.866106Z	error	api	Check failed: performing check operation failed: 1 error occurred:
* rpc error: code = Canceled desc = context canceled
```

**Comment by gotwarlost** [comment]
Looks like https://github.com/istio/istio/issues/9992#issuecomment-466229569 is relevant to this case, we will try out this feature

**Comment by bianpengyuan** [comment]
Thanks for reporting this! I think the retry happens on transport error between mixer proxy filter to mixer server and I doubt it could help mitigate the transport error between mixer server and oop adapter. But yeah please try it out, meanwhile I think we should really add retry into mixer server.
