### ISSUE TITLE
reduce the time of integ-security-k8s-presubmit-tests-master 

### ISSUE THREAD

**Issue by yangminzhu** [istio/istio#15641]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
[integ-security-k8s-presubmit-tests-master](https://prow.istio.io/?repo=istio%2Fistio&type=presubmit&job=integ-security-k8s-presubmit-tests-master&state=success) takes about 50m to run which is the slowest test among other integ tests: 

As a comparison, 
[integ-pilot-k8s-presubmit-tests-master](https://prow.istio.io/?repo=istio%2Fistio&type=presubmit&job=integ-pilot-k8s-presubmit-tests-master&state=success) takes about 25m
[integ-galley-k8s-presubmit-tests-master](https://prow.istio.io/?repo=istio%2Fistio&type=presubmit&job=integ-galley-k8s-presubmit-tests-master&state=success) takes about 20m
[integ-telemetry-k8s-presubmit-tests-master](https://prow.istio.io/?repo=istio%2Fistio&type=presubmit&job=integ-telemetry-k8s-presubmit-tests-master&state=success) takes about 25m

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[x] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
One possible reason is the test cases are spread among a lot of different test files and each test file will need to create/delete the Istio cluster separately.

We should investigate if it's possible to merge some tests to single file to make it faster, or look into the test to see if there are any other issues causing the slowness.

The other thing that could be considered is to split the security tests into 2 parts and run them in parallel, then ideally all the integ tests could finish in the 30m level which saves at least 20m for each single PR.

cc @howardjohn

**Comment by yangminzhu** [comment]
There are 7 tests under `tests/integration/security/sds_ingress` all marked as flaky and skipped from the test.

I'm afraid it will easily increase the test time to more than 1 hour if these tests are enabled. @JimmyCYJ

**Comment by howardjohn** [comment]
I may be wrong, but I think some of them the tests were actually taking a while I remember the rbac ones spending 500s or more. that is much more than just the deploy of Istio.

So yes the extra deployments may be an issue, but it's probably not the only way to improve.

Also the deployment is per package not per file, so you can still have some organization, you don't need to shove them all in one file.

Regarding sharding the tests - we can but need to be careful. initially we had all of the tests in one (pilot security, etc) and that got long so we split them. Now I think we have gone too far - some like the istioctl just run one test. Each test needs to build all of the images so there is some fixed cost

**Comment by yangminzhu** [comment]
`istio.io/istio/tests/integration/security.TestAuthnJwt` is constantly taking >4 minutes to complete, this is due to the `sleep(60)` for each test case in https://github.com/istio/istio/blob/c58def259087f72aac4ac20390a1249cfbe858a4/tests/integration/security/jwt_test.go#L331

Will send out a PR to optimize this to not to wait for 60 seconds blindly, this should save 4 minutes for the security test.
