### ISSUE TITLE
Make `istioctl register` work again for VM

### ISSUE THREAD

**Issue by incfly** [istio/istio#15640]
**Bug description**

`istioctl register` is used to simplify mesh expansion UX. What it does essentially is creating k8s service, and endpoints with user provided IPs, such that Pilot can then distribute the expected EDS for the VM service. 

It also provides some facility about annotate the k8s service with service accounts, such that Pilot will configure the CDS with correct secure naming configuration.

Since 1.0 release, however, we switched to use `ServiceEntry` for endpoints discovery. `istioctl register` thus no longer works. Today what user needs to do is

1. create service entry with ip, protocol, host name, etc.
1. create k8s service. this is needed for vm service' dns resolution.
1. annotate the k8s service with VM service account. 

This should be managed by `istioctl register` for better UX. Users can have a easier learning curve when start playing with mesh expansion. (They can still customize ServiceEntry later if needed).

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[X ] Docs
[X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by incfly** [comment]
Some prototype branch can be found, https://github.com/istio/istio/compare/master...incfly:vm-istioctl

That's an illustration of what we want to achieve from `istioctl register`. Actual cli details might be tweakable.

**Comment by incfly** [comment]
The scope of this bug should also include the documentation updates on istio.io.

**Comment by linsun** [comment]
`istioctl register` cmd is to register a VM, which is mainly used for testing. If you use consul, there is consul connect to auto register consul services with k8s thus no need to run `istioctl register` cmd.

add-to-mesh is different because it describes a experience of adding a service to the mesh whether the service runs on VM or as a k8s service.

cc @esnible @irisdingbj

**Comment by sdake** [comment]
please work with @irisdingbj on this effort - she is making great improvements in mesh expansion.

Cheers
-steve

**Comment by incfly** [comment]
@irisdingbj do you want to make this part of add-to-mesh? That's fine to me as well as long as we can make sure the documented steps in this issue can be automated via `istioctl`.

**Comment by irisdingbj** [comment]
@incfly Thanks! Yes, I will make it part of `istioctl add-to-mesh`

**Comment by linsun** [comment]
@incfly @irisdingbj - can this be closed now given add-to-mesh is added?

**Comment by irisdingbj** [comment]
sure. Let me close it.

**Comment by incfly** [comment]
Sounds good. Just need to ensure the `register` is marked as deprecated and
update our mesh expansion documentation.
