### ISSUE TITLE
not able to setup https ingressgateway for applications which will accept only https traffic

### ISSUE THREAD

**Issue by dhineshbabuelango** [istio/istio#15647]
I have istio installed in eks cluster. I am able to setup https ingress gateway and access http application but when it comes to application which accepts only https traffic, I am not able to use the actual method by mentioning the secret name and tls mode simple. always getting the below error.

upstream connect error or disconnect/reset before headers. reset reason: connection termination

**Comment by howardjohn** [comment]
Can you provide the config you have?

**Comment by dhineshbabuelango** [comment]
Hi, please find the config file below

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: tls-gateway
spec:
  selector:
    istio: admin-ingressgateway # use istio default controller
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: ingressgateway-certs
      minProtocolVersion: TLSV1_2
      maxProtocolVersion: TLSV1_2
    hosts:
    - "*"

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: isam-service
spec:
  hosts:
  - "*"
  gateways:
  - tls-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: myapp
        port:
          number: 9443

I have seen the below link for accessing https service, but the below link suggest we have to edit the actual application container yaml file to add the secrets and add a config file, The yaml files are given by vendor which has their customized variables, they are not recommeding to add the values as suggested in the below link.

https://istio.io/docs/tasks/traffic-management/ingress/ingress-sni-passthrough/
