### ISSUE TITLE
Fix prow path problems

### ISSUE THREAD

**Issue by ostromart** [istio/istio#15659]
https://github.com/istio/operator/pull/100 introduces a workaround for prow path problems. This should be resolved in prow and the workaround removed.

**Comment by sdake** [comment]
@fejta can you take a look at how to get prow to add bin to the path?  I see this file: https://github.com/istio/test-infra/blob/master/vars/goBuildNode.groovy#L15

but not sure how or if it is being used.  It sort of looks to the untrained eye like the right tool for the job :)

**Comment by howardjohn** [comment]
```
$ dk run -it gcr.io/istio-testing/test-infra-builder:v20190607-32702dcd bash
+ service docker start
 * Starting Docker: docker                                                                                                                                                                                                       [ OK ]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ exec bash
root@578f3b61fdbd:/# echo $PATH
/usr/local/go/bin:/opt/go/bin:/usr/lib/google-cloud-sdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

Looks like it is already in the path? So maybe gopath is somewhere other than where that is set

**Comment by howardjohn** [comment]
@sdake is this solved? If its not solved can you explain what the issue is and maybe I/someone can fix it?
