### ISSUE TITLE
Galley test server flakes - address in use

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#15666]
We see failures like
```
    server_test.go:65: 
        Expected
            <*net.OpError | 0xc000121bd0>: {
                Op: "listen",
                Net: "tcp",
                Source: nil,
                Addr: {
                    IP: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 255, 127, 0, 0, 1],
                    Port: 9876,
                    Zone: "",
                },
                Err: {Syscall: "bind", Err: 0x62},
            }
        to be nil
```

This error is `EADDRINUSE`, so sounds like we are just trying to bind to 9876 when it is already in use.

Example failures:

- https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/15336/istio-unit-tests-master/3182
- https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/15340/istio-unit-tests-master/3171
- https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/15342/istio-codecov-master/773
- https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/15402/istio-unit-tests-master/3360
- https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/15418/istio-unit-tests-master/3484
- https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/15422/istio-racetest-master/1715
- https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/15424/istio-racetest-master/1510
- https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/15489/istio-unit-tests-master/3581
- https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/15496/istio-unit-tests-master/3602
- https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/15512/istio-codecov-master/2078

**Comment by kyessenov** [comment]
We need some guide lines on the hermetic unit tests:
- do not use any system resources in a shared test environment, that includes shared files, inotify watches, sockets.

**Comment by howardjohn** [comment]
@ozevren I fixed one problem but not the other controlz tests as I think they would need to refactor the code to permit returning the port, or come up with a different fix. my solution was set port == 0 to randomly assign port, but the other tests need the port # so they can call it

**Comment by ozevren** [comment]
I thought @qfel already fixed those?

**Comment by howardjohn** [comment]
It doesn't look like it, I am talking about https://github.com/istio/istio/blob/ce15e23389b86f43387071b5bbdd31046f40ec27/galley/pkg/server/components/ctrlz_test.go#L36

**Comment by qfel** [comment]
For the record, what I did was #10840 - seems like a different CtrlZ test. Well, I'm glad at least now somebody runs into those issues so they get reported;)

**Comment by ozevren** [comment]
Ah I see. This is a test I've introduced recently. I'll fix it. Do you want to use this bug to track the work you've done so far, or should we repurpose?

**Comment by ozevren** [comment]
I believe this is fixed? Closing now. If there are more issues, please open a bug, this one or another one.
