### ISSUE TITLE
Consolidate fmt.sh

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#1566]
`make fmt` target should format source code.
At present mixer, pilot, security have their own ways of formatting in `*/bin/fmt.sh`
1. Consolidate the script at the top leve bin/fmt.sh
2. Add a top level make target for it.

**Comment by guptasu** [comment]
@mandarjog  The first step is to make the scripts work since they are currently broken. Then I can look into consolidation, which can be tricky because that will need finding a shared set of features that every component devs are happy about.

**Comment by geeknoid** [comment]
Subsumed by #1844
