### ISSUE TITLE
Mixer > Stackdriver > Example does not work

### ISSUE THREAD

**Issue by kuwas** [istio/istio#15662]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
Example usage (https://github.com/istio/istio/blob/master/mixer/adapter/stackdriver/operatorconfig/stackdriver.yaml) of the stackdriver adapter is out of date
```
unable to recognize "./kubernetes/manifests/istio.stackdriver.yml": no matches for kind "stackdriver" in version "config.istio.io/v1alpha2"
unable to recognize "./kubernetes/manifests/istio.stackdriver.yml": no matches for kind "metric" in version "config.istio.io/v1alpha2"
unable to recognize "./kubernetes/manifests/istio.stackdriver.yml": no matches for kind "metric" in version "config.istio.io/v1alpha2"
unable to recognize "./kubernetes/manifests/istio.stackdriver.yml": no matches for kind "metric" in version "config.istio.io/v1alpha2"
unable to recognize "./kubernetes/manifests/istio.stackdriver.yml": no matches for kind "metric" in version "config.istio.io/v1alpha2"
unable to recognize "./kubernetes/manifests/istio.stackdriver.yml": no matches for kind "metric" in version "config.istio.io/v1alpha2"
unable to recognize "./kubernetes/manifests/istio.stackdriver.yml": no matches for kind "metric" in version "config.istio.io/v1alpha2"
unable to recognize "./kubernetes/manifests/istio.stackdriver.yml": no matches for kind "metric" in version "config.istio.io/v1alpha2"
unable to recognize "./kubernetes/manifests/istio.stackdriver.yml": no matches for kind "metric" in version "config.istio.io/v1alpha2"
unable to recognize "./kubernetes/manifests/istio.stackdriver.yml": no matches for kind "metric" in version "config.istio.io/v1alpha2"
unable to recognize "./kubernetes/manifests/istio.stackdriver.yml": no matches for kind "metric" in version "config.istio.io/v1alpha2"
unable to recognize "./kubernetes/manifests/istio.stackdriver.yml": no matches for kind "metric" in version "config.istio.io/v1alpha2"
unable to recognize "./kubernetes/manifests/istio.stackdriver.yml": no matches for kind "metric" in version "config.istio.io/v1alpha2"
unable to recognize "./kubernetes/manifests/istio.stackdriver.yml": no matches for kind "logentry" in version "config.istio.io/v1alpha2"
unable to recognize "./kubernetes/manifests/istio.stackdriver.yml": no matches for kind "logentry" in version "config.istio.io/v1alpha2"
unable to recognize "./kubernetes/manifests/istio.stackdriver.yml": no matches for kind "tracespan" in version "config.istio.io/v1alpha2"
```

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Should not be using deprecated CRDs

**Steps to reproduce the bug**
* Install Istio 1.2.2
* Attempt to install https://github.com/istio/istio/blob/master/mixer/adapter/stackdriver/operatorconfig/stackdriver.yaml

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.6", GitCommit:"abdda3f9fefa29172298a2e42f5102e777a8ec25", GitTreeState:"clean", BuildDate:"2019-05-08T13:53:53Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-eks-c57ff8", GitCommit:"c57ff8e35590932c652433fab07988da79265d5b", GitTreeState:"clean", BuildDate:"2019-06-07T20:43:03Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```
```
client version: 1.2.2
citadel version: 1.2.2
egressgateway version: 1.2.2
galley version: 1.2.2
ingressgateway version: 1.2.2
nodeagent version:
nodeagent version:
nodeagent version:
nodeagent version:
pilot version: 1.2.2
policy version: 1.2.2
sidecar-injector version: 1.2.2
telemetry version: 1.2.2
```

**How was Istio installed?**
* Helm

**Environment where bug was observed (cloud vendor, OS, etc)**
* AWS EKS cluster

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by canthefason** [comment]
This happens because useAdapterCRD and useTemplateCRD flags for mixer is set to false by default for v1.2. If you set these flags to true, you can still use that [legacy](https://github.com/istio/istio/blob/master/mixer/adapter/stackdriver/operatorconfig/stackdriver.yaml) configuration. 

As a better approach, it is also possible to convert them to handler and instance resources, where an example is not included anywhere in this repo. However, I've some running examples of it which I can share. 

As a long term solution, @kyessenov I can also contribute to the helm charts by adding stackdriver related handlers/rules/instances, but is there a particular reason that stackdriver configuration has been excluded from this repo?

**Comment by bianpengyuan** [comment]
Stackdriver config has been added into istio/installer, which is going to replace the current helm charts be ready in 1.3 I think: https://github.com/istio/installer/blob/fea3727752f66d6a2a8e1a2fa1bc83312b0febb0/istio-telemetry/mixer-telemetry/templates/stackdriver.yaml

**Comment by kuwas** [comment]
@bianpengyuan Awesome

**Comment by BradErz** [comment]
For anyone coming accross this in the future and just want something that works, i spent my day:

https://gist.github.com/BradErz/347a3cbf253c0460a00b405e0d9a0051

**Comment by kuwas** [comment]
@BradErz 👍

**Comment by kyessenov** [comment]
Looks like the referenced stale samples are gone, and the new samples in installation repo are updated. Closing. Thanks @BradErz !
