### ISSUE TITLE
Add documenting comments to values_structs.proto

### ISSUE THREAD

**Issue by ostromart** [istio/istio#15691]
The values_structs.proto file is the source of truth for both the schema for Helm values, as used in the operator, and istio.io docs. These need to be cleaned up and made consistent. Please include the component TL, rcaballeromx and sdake in the reviews.
The format of comment we want is:

Brief one line desctription.
<blank line>
A paragraph explanation that can be added to the one line description (i.e. it does not repeat it) and which gives additional information. The paragraph should be no more than ten lines long - any longer should point to a web page. 
<blank line>
Allowed values: only if appropriate, not obvious like an IP address.
<blank line>
Examples: one or more examples of values.
<blank line>

For a starting point on the description, see https://docs.google.com/spreadsheets/d/1a7uwBq4XdaM3MDFJYEGVj8sULcCwfCmnkIhcA3p30r0/edit#gid=0, which has been edited by @rcaballeromx. Then check against the values.yaml files in istio/installer to ensure the meaning hasn't changed and the value still exists (the spreadsheet is out of date). 

Here's are two examples:

1. global.enableHttps

Adds port 443 on the ingress.

Enabling this setting REQUIRES that the certificates are installed  in the expected secrets - enabling this option without certificates will result in LDS rejection and the ingress will not work.

2.  global.dnsRefreshRate

Configures the DNS refresh rate for an Envoy cluster of type STRICT_DNS.

The value must be given in seconds. 

Allowed values: Ns (where N is the number of seconds).

Examples: 100s

See https://github.com/istio/operator/pull/113 for more examples.

**Comment by rcaballeromx** [comment]
@ostromart As I mentioned before, I only did a quick edit pass on the entries. A more detailed review of the content is still needed.

**Comment by ostromart** [comment]
Hi Rigs, yes, thanks for pointing that out. I forgot to mention in the bug that Rigs should be a reviewer of all the docs PRs above.

**Comment by ibm-jason** [comment]
Sorry for the assign/un-assign confusion. I didn't realize at first that this was an EPIC issue. I'll work on covering one of the issues(stories) contained in this epic, but we'll need to get some additional hands on the other issues under this EPIC.
