### ISSUE TITLE
Pilot platform adapter returns nil slice for Instances

### ISSUE THREAD

**Issue by rosenhouse** [istio/istio#1569]
In building the platform adapter for Cloud Foundry (#1371), we were cribbing from the k8s adapter.  

We see that the [k8s platform adapter's `Instances` function sometimes returns `nil`](https://github.com/istio/istio/blob/8c078c6ec6e41857a39fbf01b0561223a2c5d16d/pilot/platform/kube/controller.go#L276).

This was a bit surprising, and we're curious if it has a particular purpose.  Do clients interpret a `nil, nil` result in a particular way?

We're wondering if the nil result deserves particular test coverage for this reason.

Thanks!

@rosenhouse and @Nino-K

**Comment by kyessenov** [comment]
I think clients interpret nil as an empty array. This seems sensible when the requested service does not exist.

**Comment by rosenhouse** [comment]
Yes, as long as those clients are not relying on the distinction between an empty slice and a nil one.  In other words, a platform adapter is free to return `[]*model.ServiceInstance{}` instead of `nil` without causing any surprises for clients.
