### ISSUE TITLE
Update "helm install" command in docs

### ISSUE THREAD

**Issue by youalreadydid** [istio/istio#15705]
I was trying to install the current Istio version (1.2.2) with Helm following the [docs](https://istio.io/docs/setup/kubernetes/install/helm/), but the step 3 from option 2 is defined as
```
helm install install/kubernetes/helm/istio-init --name istio-init --namespace istio-system
```
and it only worked with
```
helm install istio.io/istio-init --name istio-init --namespace istio-system
```

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
It is expected to install Istio with Helm.

**Steps to reproduce the bug**
Follow the documentation.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Istio v1.2.2
kubectl v1.15.0

**How was Istio installed?**
After I used the command with "istio.io" in it.

**Environment where bug was observed (cloud vendor, OS, etc)**
The cloud is GKE, my machine is a Fedora 30.

**Comment by howardjohn** [comment]
this is expected, you can install from the repo (as you did) or download the release. see note in the doc:

> The commands in this guide use the Helm charts that are included in the Istio release image. If you want to use the Istio release Helm chart repository instead, adjust the commands accordingly and add the Istio release repository as follows:

**Comment by youalreadydid** [comment]
Oh, sorry for the confusion, thanks!

**Comment by howardjohn** [comment]
no worries, it's not the most obvious that you need to download the
release. We are hoping to not require a download in the future install to
simplify things
