### ISSUE TITLE
Create a multi-network multicluster test

### ISSUE THREAD

**Issue by ericvn** [istio/istio#15706]
Create a multi-network multicluster test using the new integration framework.

**Comment by howardjohn** [comment]
You should be able to use kind when doing this, should make things simpler. If you are using the integ framework it already will be though

**Comment by howardjohn** [comment]
related: https://github.com/istio/istio/issues/17362

**Comment by ericvn** [comment]
There is on-going work to create single-mesh multi-cluster install guides based on best practices. The plan is to have tests for each of the documented cases. Some of that work can be found at https://github.com/philrud/istio-multicluster-examples. This issue would be for creating the first test using the framework.
