### ISSUE TITLE
istio 1.2.2 request routing does not work

### ISSUE THREAD

**Issue by ajitchahal** [istio/istio#15707]
The virtual service is deployed to route traffic to v2. The requests via istio ingress are successfully able to route traffic correctly to v2 of application, but a pod-to-pod curl request always does a 50/50 traffic split between the two subsets of apps.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[x ] Installation
[x ] Networking
[ ] Performance and Scalability
[ x] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
The traffic in case of a pod-to-pod request must be influenced by virtual service and sent 100% to v2 version of application i.e. nginx home page in  [my case](https://raw.githubusercontent.com/ajit-dev-ops/k8s-istio/master/istio-ingress/istio-ing-route-on-query-param-remote.yml)

**Steps to reproduce the bug**
Create a k8s cluster may be kind cluster with 3 nodes and 2GB of ram to docker.
kind create cluster --config [kind-config.yaml](https://github.com/ajit-dev-ops/k8s-concepts/edit/master/kind-cluster/kind-config.yaml)

Create deployments and virtual service and destination rule as tried in following k8s manifest. 
https://raw.githubusercontent.com/ajit-dev-ops/k8s-istio/master/istio-ingress/istio-ing-route-on-query-param-remote.yml

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
`k version                                                                                                      
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-07T09:55:27Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-25T23:41:27Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}`

`istioctl version                                                                                                         
client version: 1.2.1
citadel version: 1.2.2
egressgateway version: 1.2.2
galley version: 1.2.2
ingressgateway version: 1.2.2
pilot version: 1.2.2
policy version: 1.2.2
sidecar-injector version: 1.2.2
telemetry version: 1.2.2`

**How was Istio installed?**
using helm template method, istio-init -> istio-cni (cni enabled) -> istio chart

**Environment where bug was observed (cloud vendor, OS, etc)**
both on k8s deployed on aws with kops and on local kind clusters.

**Comment by howardjohn** [comment]
This seems to work as intended; you set the `gateways` field to limit the scope of the VrtiaulService to only the gateway. If you want it to apply to sidecar as well you need to add `mesh` to the list. See docs here: https://istio.io/docs/reference/config/networking/v1alpha3/virtual-service/#VirtualService (gateway field)
