### ISSUE TITLE
Pilot reports `unauthorized` when attempting to access k8s resources.

### ISSUE THREAD

**Issue by dkushner** [istio/istio#15703]
**Bug description**
Having started with a single-control plane, multi-cluster installation using the multi-network strategy outlined in the documentation, we experienced numerous issues resolving services across clusters and decided to eliminate the remotes and their associated networks. I modified the `istio` ConfigMap resource in the `istio-system` namespace and removed the two superfluous networks referring to the remotes. I maintained the primary network which references the gateway in the primary cluster, however. 

The gateway definition we had been using before continued to work just fine as we redeployed our services into this single cluster. However, subsequent services (VirtualService resources) configured identically to the working ones and applied to the same cluster have started failing to resolve other services in the _same_ cluster. I have checked the Pilot logs in an attempt to debug and the only relevant error I can find is the following: 

```
2019-07-22T10:05:25.054539Z	error	istio.io/istio/pilot/pkg/serviceregistry/kube/controller.go:266: Failed to list *v1.Service: Unauthorized
2019-07-22T10:05:25.617531Z	debug	Listing and watching *v1.Pod from istio.io/istio/pilot/pkg/serviceregistry/kube/controller.go:267
2019-07-22T10:05:25.629190Z	info	Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401}

2019-07-22T10:05:25.629351Z	error	istio.io/istio/pilot/pkg/serviceregistry/kube/controller.go:267: Failed to list *v1.Pod: Unauthorized
2019-07-22T10:05:25.647908Z	debug	Listing and watching *v1.Node from istio.io/istio/pilot/pkg/serviceregistry/kube/controller.go:268
2019-07-22T10:05:25.656980Z	info	Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401}

2019-07-22T10:05:25.657425Z	error	istio.io/istio/pilot/pkg/serviceregistry/kube/controller.go:268: Failed to list *v1.Node: Unauthorized
```
This is with debug logging enabled across the board for Pilot. It gives no further information about which cluster/namespace it is attempting to access. 

**Affected product area (please put an X in all that apply)**

[X] Configuration Infrastructure
[ ] Docs
[X] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Single-plane, multi-network installation should continue to function if the remotes are removed from the `ConfigMap` resource. 

**Steps to reproduce the bug**
1. Install Istio in the multi-network, single control-plane method described in the documentation joining two clusters.
2. Remove the remote definition from the `istio` ConfigMap resource.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```
client version: 1.2.2
citadel version: release-1.2-20190705-09-16
galley version: release-1.2-20190705-09-16
ingressgateway version: release-1.2-20190705-09-16
pilot version: release-1.2-20190705-09-16
policy version: release-1.2-20190705-09-16
sidecar-injector version: release-1.2-20190705-09-16
telemetry version: release-1.2-20190705-09-16
```

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-21T13:09:06Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.8-gke.10", GitCommit:"f53039cc1e5295eed20969a4f10fb6ad99461e37", GitTreeState:"clean", BuildDate:"2019-06-19T20:48:40Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

Helm chart following the documentation for multi-network, single control-plane installation.

**Environment where bug was observed (cloud vendor, OS, etc)**

GKE

**Comment by howardjohn** [comment]
What clusterrole is pilot using? It will need
```
- apiGroups: [""]
  resources: ["endpoints", "pods", "services", "namespaces", "nodes", "secrets"]
  verbs: ["get", "list", "watch"]
```
