### ISSUE TITLE
cherry pick specific commit of Envoy to 1.2 release

### ISSUE THREAD

**Issue by ramaraochavali** [istio/istio#15717]
We would like to see the possibility of having this PR (envoyproxy/envoy#7019)  available in 1.2 Proxy. Are proxy changes to 1.2 release acceptable? If yes, what is the way we can cherry pick that PR ?

**Comment by howardjohn** [comment]
Did we do this? do we still need it?

**Comment by ramaraochavali** [comment]
We can close this
