### ISSUE TITLE
Number of objects increasing beyond specific thresholds cause control plane pods to grind to a halt

### ISSUE THREAD

**Issue by gotwarlost** [istio/istio#15711]
**Bug description**

There are many people experimenting on our playground cluster with istio objects. CI/CD pieplines create test objects with some TTL after which they are deleted. We have seen that transient increase in the number of such objects will cause the istio control plane to fall over because of gRPC message sizes going over 4MB. 

It is not that istio cannot handle this load but the fact that the cluster can exhibit random behavior based on whether there are 24 or 25 templates in the cluster that is the problem.

Further, we note that not all components seem to allow customization of the max size of gRPC messages. Galley seems to be sending entire collections of objects in one shot to mixer/ pilot etc. and any of this communication can fail at random times and cause unexpected outages in an environment that people also use for integration and get paged on.

Things that we have seen break the cluster:

* Excessive virtual services (~200 range - our virtual service defs are large) will break pilot
* Excessive number of templates (~25) will break mixer 

and so on. Note that these numbers are not unreasonable and were it not for the msg size being maxed out, we believe the control plane would be able to handle this load.

It's not clear to what the solution to this problem is or how we can get some predictable operations and sanity in managing the cluster. We would like to see:

* gRPC message sizes to be configurable for all components
* galley throttling the amount of data sent in one payload
* other solutions?

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[X ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Small changes in the number of istio objects (past a threshold that cannot be known in advance because of variation in object size) do not cause full control plane outages.

**Steps to reproduce the bug**

* Keep adding templates, one at a time to the system and watch telemetry pods abruptly stop working and going into crash loop backoffs once some threshold is crossed.

* Ditto with virtual services and pilot pods

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

```
client version: version.BuildInfo{Version:"1.1.2", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989", User:"root", Host:"35adf5bb-5570-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.1"}
citadel version: version.BuildInfo{Version:"1.1.8", GitRevision:"145b18a441045d6fad33d7916380d8642c7bf21d-dirty", User:"root", Host:"11387264-87af-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.7-14-g145b18a"}
galley version: version.BuildInfo{Version:"1.1.8", GitRevision:"145b18a441045d6fad33d7916380d8642c7bf21d-dirty", User:"root", Host:"11387264-87af-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.7-14-g145b18a"}
pilot version: version.BuildInfo{Version:"1.1.8", GitRevision:"145b18a441045d6fad33d7916380d8642c7bf21d-dirty", User:"root", Host:"11387264-87af-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.7-14-g145b18a"}
policy version: version.BuildInfo{Version:"1.1.8", GitRevision:"145b18a441045d6fad33d7916380d8642c7bf21d-dirty", User:"root", Host:"11387264-87af-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.7-14-g145b18a"}
sidecar-injector version: version.BuildInfo{Version:"1.1.8", GitRevision:"145b18a441045d6fad33d7916380d8642c7bf21d-dirty", User:"root", Host:"11387264-87af-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.7-14-g145b18a"}
telemetry version: version.BuildInfo{Version:"1.1.8", GitRevision:"145b18a441045d6fad33d7916380d8642c7bf21d-dirty", User:"root", Host:"11387264-87af-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.7-14-g145b18a"}
```

**How was Istio installed?**

Helm charts

**Environment where bug was observed (cloud vendor, OS, etc)**

AWS, kops

**Comment by howardjohn** [comment]
cc @costinm
