### ISSUE TITLE
Expose envoy metrics service config via envoy pilot agent

### ISSUE THREAD

**Issue by pnambiarsf** [istio/istio#15734]
We currently run mainline envoy as sidecars with a limited in-house implementation of the control plane in production.We are in the process of migrating to Istio. Metrics are published from envoy to the metrics service that in turn publishes to our company’s telemetry backend. We will need to support this flow during the migration at the very least along with telemetry via mixer.

Therefore we would like the metrics service config (https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/metrics/v2/metrics_service.proto) exposed via envoy pilot agent so that we can configure istio proxy to publish metrics to the metrics service. 
We would like this exposed in the ProxyConfig as well.

**Comment by howardjohn** [comment]
This is done now
