### ISSUE TITLE
istio-proxy fails on startup in Kubernetes if a Service object is not defined

### ISSUE THREAD

**Issue by zachidan** [istio/istio#15731]
It looks that the _istio-proxy_ (sidecar) requires a Service object, otherwise the proxy fails to startup.

If I create a POD object **without** a Service object, the istio-proxy fails to startup (see logs below)

In addition:
1. **TCP protocol**: it seems that it is NOT possible to connect to the POD instance by using the POD IP. Only the Service Name ({service}.{namespace}.svc.cluster.local) or the Service IP can be used.
2. **HTTP protocol**: the http HOST header MUST be the Service Name or the Service IP. If the http HOST header is the POD IP, the connection is refused by the _istio-proxy_.

Is it by design ? If yes, it should be documented.

Setup:
- Kubernetes cluster v1.12.5+IKS
- istio-1.1.0-snapshot.5

Logs:
~~~~

2019-02-25T09:22:43.112211Z    info    Envoy proxy is NOT ready: 3 errors occurred:

* failed checking application ports. listeners="0.0.0.0:15090","172.21.252.88:15030","172.21.252.88:15031","172.21.66.1:42422","172.21.252.88:15032","172.21.234.188:53","172.21.156.95:15011","172.21.252.88:443","172.21.252.88:15443","172.21.9.91:443","172.21.252.88:31400","172.21.252.88:15029","172.21.0.1:443","172.21.83.228:443","172.21.83.228:15443","172.21.125.115:443","0.0.0.0:8080","0.0.0.0:8060","0.0.0.0:9093","0.0.0.0:9091","0.0.0.0:15010","0.0.0.0:8000","0.0.0.0:80","0.0.0.0:9901","0.0.0.0:15004","0.0.0.0:9090","172.30.80.142:15020","[fe80::4cde:eaff:feac:527f]:3333","[fe80::4cde:eaff:feac:527f]:9999","0.0.0.0:15001"
* envoy missing listener for inbound application port: 0
* envoy missing listener for inbound application port: 5201

**Comment by howardjohn** [comment]
This is documented https://istio.io/docs/setup/additional-setup/requirements/
