### ISSUE TITLE
Security issues granting istio l7 load balancer admin privileges 

### ISSUE THREAD

**Issue by texzone** [istio/istio#15745]
Hello,

It is my understanding that istio needs root access to my (kubernetes) containers to work in order to modify iptables (and perhaps other things). Is there a workaround for this? I would love to have istio as my load balancer implementation, but there are security issues attached with granting it root access. It would be great if either my understanding is incorrect or this issue has been fixed. I see there was an [issue](https://github.com/istio/old_issues_repo/issues/172) opened before. Not 100% this is addressing the same issue, but if it is, was it resolved?

Thank you

**Comment by andraxylia** [comment]
This should be now fixed by #7890
