### ISSUE TITLE
jwt_auth filter does not have full support of x509 public key 

### ISSUE THREAD

**Issue by JimmyCYJ** [istio/istio#15749]
By reading code, two issues are observed which block jwt_auth filter from fully support of public key in x509 . 

1. We have Pubkeys::CreateFrom(const std::string &pkey, Type type) which takes public key in string and create Pubkeys object ([link](https://github.com/istio/proxy/blob/71f918875f883c07e6c2258e472de7fee1fb305d/src/envoy/http/jwt_auth/jwt.cc#L575)), but we only call this function when we fetch public keys in JWKS ([link](https://github.com/istio/proxy/blob/da18323bf354c55dac27a97a8dfbaa998b7c6a4d/src/envoy/http/jwt_auth/pubkey_cache.h#L74)). 

2. void Pubkeys::CreateFromPemCore(const std::string &pkey_pem) assumes that pkey_pem only contains one key ([link](https://github.com/istio/proxy/blob/71f918875f883c07e6c2258e472de7fee1fb305d/src/envoy/http/jwt_auth/jwt.cc#L457)).

**Comment by nareddyt** [comment]
FYI the latest version of the JWT_authn filter supports `x509` format now. I have verified it with an integration test in [github.com/GoogleCloudPlatform/esp-v2](github.com/GoogleCloudPlatform/esp-v2)
