### ISSUE TITLE
Add trace spans for client

### ISSUE THREAD

**Issue by geeknoid** [istio/istio#15757]
@douglas-reid commented on [Mon Jan 29 2018](https://github.com/istio/mixerclient/issues/405)

For the distributed tracing features of Istio, we want to have mixerclient spans in the generated trace data. This would help with a number of debug-ability related items:

- better understanding caching
- better understanding perf of client library
- better understanding impact of network

cc: @rshriram

**Comment by howardjohn** [comment]
Is this still relevant? Given no comments in almost 2 years I would guess not?

**Comment by douglas-reid** [comment]
I think the need is still valid, but the likelihood of the work actually being conducted and used is so small as not really be useful or relevant.  Let's close this as: Won't Fix.
