### ISSUE TITLE
Should regenerate `istio-sidecar-injector` mutatingWebhookConfiguration when deleted

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#15775]
Recently observed `istio-sidecar-injector` mutatingWebhookConfiguration is gone in one env. 

I think it should be recreated automatically.

**Comment by howardjohn** [comment]
This doesn't seem like a great idea to me. 

First, it requires elevated permissions for the sidecar injector (I think, unless it already has those permissions).

Second, it couples the webhook to the injector, which is not something we want. You can have one webhook pointing to two independant injector instances, or a webhook pointing to an external injector that isn't even in the cluster

**Comment by hzxuzhonghu** [comment]
Yes, it already has this permission, it updates the webhoolconfiguration when certs changes.

**Comment by hzxuzhonghu** [comment]
Should close at the moment
