### ISSUE TITLE
Evaluate authentication filter in WASM

### ISSUE THREAD

**Issue by yangminzhu** [istio/istio#15772]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
This issue is to track the evaluation of  migrating the istio authentication filter to WASM which allows us to get rid of the dependency on the istio/proxy repo and with more flexibility of the filter deployment.

We need to evaluate the functionality, performance, testing and debuggability of the WASM approach compared to the current implementation. I believe the functionality would not be a concern as the authentication filter only uses a very small set of Envoy API, mostly the dynamic metadata and connection->ssl(). 
I'm more concerned about the testing/debuggability at this moment.

@incfly I will soon create a separate branch in istio/proxy with a minimal skeleton authn-v2 filter in WASM using the null-vm for our evaluation.

cc @PiotrSikora @jplevyak @diemtvu @mandarjog @kyessenov @bianpengyuan @silentdai 

**Describe alternatives you've considered**
We could also consider to upstream the authN filter to Envoy if we only want the benefit of getting rid of the dependency on istio/proxy repo after the evaluation of the pros/cons of migrating to WASM. This will be tracked separately if needed.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by Shikugawa** [comment]
@yangminzhu I'm working with this as continuation of your awesome work. Can you re-open this and assign me?

**Comment by PiotrSikora** [comment]
@Shikugawa thanks for your work! Do you think it will be ready in the next 2 weeks (for 1.6 code freeze)?

**Comment by Shikugawa** [comment]
@PiotrSikora Thanks. I think that it is difficult because of the complexity of dependencies on AuthN filter. It will be resolved by using bazel but that is not applied now on wasm build. I'll continue to work in [this repository](https://github.com/Shikugawa/istio-proxy-authn-wasm). And I will create a PR after work on there.

**Comment by yangminzhu** [comment]
@Shikugawa Thanks for looking into this.

@PiotrSikora We shouldn't push this to 1.6, that's not planned for the 1.6 from the security WG. We also need more investigations especially about the stability and debuggability of WASM filter to better justify migrating the already fully working istio_authn filter to a new WASM filter.

**Comment by lizan** [comment]
@yangminzhu while it is not planned in security WG it is a P1 in networking WG to migrate existing filters. Though I agree this isn't a blocker for 1.6 so if it is not mature yet we shouldn't push it into 1.6
