### ISSUE TITLE
sidecar-injector pods does not produce matching CA certificates

### ISSUE THREAD

**Issue by tegk** [istio/istio#15777]
**Bug description**

Restarting the sidecar-injector pods does not produce matching CA certificates.

**Affected product area (please put an X in all that apply)**

[X] Configuration Infrastructure
[X] Docs
[X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
When experienceing x509-certificate-related-errors steps are performed according to
https://istio.io/docs/ops/setup/injection/#x509-certificate-related-errors

but this does not resolve the issue as the restarting of pod does not produce matching md5 sums

**Steps to reproduce the bug**

kubectl get mutatingwebhookconfiguration istio-sidecar-injector -o yaml -o jsonpath='{.webhooks[0].clientConfig.caBundle}' | md5sum

kubectl -n istio-system get secret istio.istio-sidecar-injector-service-account -o jsonpath='{.data.root-cert\.pem}' | md5sum

kubectl -n istio-system patch deployment istio-sidecar-injector \
    -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"

kubectl get mutatingwebhookconfiguration istio-sidecar-injector -o yaml -o jsonpath='{.webhooks[0].clientConfig.caBundle}' | md5sum

kubectl -n istio-system get secret istio.istio-sidecar-injector-service-account -o jsonpath='{.data.root-cert\.pem}' | md5sum

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Istio 1.2

**How was Istio installed?**
Quick Start Evaluation Install from https://istio.io/docs/setup/kubernetes/install/kubernetes/
**Environment where bug was observed (cloud vendor, OS, etc)**

Kubernetes v1.11.0+d4cacc0
OKD v3.11.0+01dd962-225
CentOS 7

**Comment by sdake** [comment]
OKD has a variant of the sidecar injector that is different than upstream's sidecar injector.  Therefore, I have assigned @knrc to find the appropriate owner for you.

**Comment by knrc** [comment]
Apologies, I have not been tracking my issues as closely as I should have done.  Just to be clear this issue appears to be deploying upstream istio, i.e. not the maistra version, into OKD?  If that is the case then you should be using the same codebase.

In the maistra version we modified the sidecar injector so it was responsible for updating the certificates, this was previously handled during the installation process, but have since moved this behaviour to the operator to reduce the need for elevated permissions.

**Comment by tegk** [comment]
Yes, maistra was used

**Comment by knrc** [comment]
The report states istio 1.2 was used which is not a maistra version, it's also says the upstream installation instructions were followed which would not apply to maistra.  Could you please confirm the operator/image versions which you were using?  Was this one of the tech preview releases?

Thanks very much
