### ISSUE TITLE
We should remove repo write access from most users

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#15770]
Right now all users in the org have write access, which is probably more than needed. GitHub has a triager role (https://help.github.com/en/articles/repository-permission-levels-for-an-organization) that may be appropriate.

I am the guinea pig for this change so going to keep track of issues I run into here

**Comment by howardjohn** [comment]
Things I have noticed so far:

* I cannot modify milestones
* Minor: For some reason while I am creating an issue I cannot edit labels or assignees, but after I create it I can
* Minor: There is no "assign me" button on issues. I can still assign myself though, just not in one click
* I can modify zenhub through the full zenhub UI, but cannot set priority from within an issue

**Comment by geeknoid** [comment]
Access to istio/installer was due to an unusual configuration in that repo. I've cleaned that up and it should no longer be special.

**Comment by geeknoid** [comment]
And you also mentioned the coupling between CODEOWNERS and Triager. You can't be a code owner with only Triager permission. So any  code owner needs to at least have write access.

**Comment by howardjohn** [comment]
@geeknoid is this done?

**Comment by geeknoid** [comment]
Nope, I don't think we'll do this given the constraints it imposes. So I think we should just close this.
