### ISSUE TITLE
Add SDS support into command `istioctl proxy-status`

### ISSUE THREAD

**Issue by JimmyCYJ** [istio/istio#15789]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Currently, Istioctl proxy-status provides an overview of xDS push between Pilot and Envoy in a mesh. We could add support for SDS to get an overview of SDS push between Citadel Agent and each SDS client. The SDS client could be named as `pod-name`+`SDS resource name`

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**
https://github.com/istio/istio/issues/16724
https://github.com/istio/istio/issues/13439

**Comment by Monkeyanator** [comment]
@JimmyCYJ I looked around and couldn't find an existing issue for this, thanks for making one :)  For context, the work in [this PR](https://github.com/istio/istio/pull/15418) gives us the information we need from the `nodeagent` side, but we still need [this PR](https://github.com/envoyproxy/envoy/pull/7365) merged before we can access the `envoy` side of things and make the diff.

As I understand it, the logic wouldn't be too different from the existing logic in [proxystatus.go](https://github.com/istio/istio/blob/master/istioctl/cmd/proxystatus.go). If a user specifies a single envoy/pod, we:

1. Figure out which node the envoy/pod is running on
2.  Hit the new `/debug/sds/...` endpoint on the `nodeagent` running on that node to obtain its most updated secret configuration
3. Hit the `config_dump` endpoint on that envoy instance to obtain its secret configuration
4. Diff the two results (I'm not 100% certain on what we'd be diffing, but I suppose just the actual lists of secrets contained in the two results)

And then if the user doesn't specify, we do that same procedure for all envoys in the mesh.

@incfly does that seem about right?

**Comment by incfly** [comment]
@Monkeyanator 

Almost. We expect several states

1. Client has trouble load the initial value of the secret, which you'll see the secret in the list of `warming_secret`.
1. Value client currently hold is v1, and server think it delivers v2. see if v1 and v2 are different.
1. Note the secret are not just tls_certificate, can be validation context, and root, and other things. You might want have a column for the output to denote that.
1. denote the difference between gateway ingress cert and workload identity.
1. some aggregated information might also be helpful.

So I think spent some time thinking about what output format can be helpful, w.r.t above points into consideration.

But you can always starts from simplest case,  focusing on workload identity as tls_keycert.

**Comment by Monkeyanator** [comment]
[This PR](https://github.com/istio/istio/pull/16498) is the WIP implementation of what's being discussed in this issue.

There are two features that ended up in the actual implementation:

1. `istioctl proxy-config secret` to dump secrets Envoy config dump
2. `istioctl proxy-status <pod.[namespace]> --sds` which hits the node agent endpoint for secrets and diffs with the dynamic active secrets on Envoy

The feature to dump _all_ secrets from a target node agent was implemented, but did not make it into the PR, in order to make it more reviewable. The plumbing for retrieving, formatting, and outputting that data is in place now however, and it would be trivial to add it back in.
