### ISSUE TITLE
productpage v1:1.15.0 wont run with different uid

### ISSUE THREAD

**Issue by mitchellmaler** [istio/istio#15787]
**Bug description**
If you try to start productpage v1:1.15.0 with a different uid such as 1001 python will error with `KeyError: 'getpwuid(): uid not found: 1001'`

```
docker run -it  --user 1001 istio/examples-bookinfo-productpage-v1:1.15.0 sh
python productpage.py 9080
cat /opt/microservices/stderr.log
Traceback (most recent call last):
  File "productpage.py", line 379, in <module>
    app.run(host='0.0.0.0', port=p, debug=True, threaded=True)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 943, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python3.6/site-packages/werkzeug/serving.py", line 751, in run_simple
    application = DebuggedApplication(application, use_evalex)
  File "/usr/local/lib/python3.6/site-packages/werkzeug/debug/__init__.py", line 258, in __init__
    if self.pin is None:
  File "/usr/local/lib/python3.6/site-packages/werkzeug/debug/__init__.py", line 268, in _get_pin
    self._pin, self._pin_cookie = get_pin_and_cookie_name(self.app)
  File "/usr/local/lib/python3.6/site-packages/werkzeug/debug/__init__.py", line 148, in get_pin_and_cookie_name
    username = getpass.getuser()
  File "/usr/local/lib/python3.6/getpass.py", line 169, in getuser
    return pwd.getpwuid(os.getuid())[0]
KeyError: 'getpwuid(): uid not found: 1001'
```

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Start productpage with different security context user (non-root) such as 1001 and it starts up correctly.

**Steps to reproduce the bug**

```
docker run -it  --user 1001 istio/examples-bookinfo-productpage-v1:1.15.0 sh
python productpage.py 9080
```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
istio 1.2.2
k8s 1.15.0

**How was Istio installed?**
Helm Chart

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by esnible** [comment]
This may be fixed in Python 3.7.  https://bugs.python.org/issue31469
