### ISSUE TITLE
Draining of pilot-agent seems not to work in all cases (ingressgateway)

### ISSUE THREAD

**Issue by c0d1ngm0nk3y** [istio/istio#15809]
**Bug description**

When restarting the istio-ingressgateway pods and simultaneous requesting (e.g. with curl), some request fail with `Empty reply` even if a `rolling update` is used.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

No request should fail during an update. The draining of the pilot agent should take care.

Note: Using a simple `preStop` lifecycle like suggested in https://github.com/istio/istio/issues/15704 mitigates the problem.

**Steps to reproduce the bug**

### Preconditions

* `maxReplicas` of the HPA should be set to 1 to be more focused

### Continuous restarting

```bash
while true; do
  kubectl set env  deployment/istio-ingressgateway --env="LAST_MANUAL_RESTART=$(date +%s)" --namespace=istio-system
  sleep 1
  kubectl rollout status deployment istio-ingressgateway -n istio-system --timeout=1m
  sleep 1
done
```

### Continuous requesting ingress

```bash
TARGET=${TARGET:-url.istio.test/path}
N=${N:-5000}
LOG_FILE=$(mktemp)
for i in $(seq "${N}"); do
  echo -n .; SEC=$(date '+%s') ; curl -v  --fail http://$TARGET > "$LOG_FILE" 2>&1 || ( date; echo "$i. curl took $(($(date '+%s')-SEC))s"; cat "$LOG_FILE";   exit 1) || exit
done
```

In this setup we are able to reproduce this issue within 30min max. Getting to the correct logs can be a bit tricky because of the rolling updates, but the interesting part is that there is *NO* `caught SIGTERM` from the pilot-agent in those cases.

*NOTE*

The failing curl takes several seconds to actually fail with `Empty reply`. It turns out that the seconds the curl takes are TERMINATION_DRAIN_DURATION_SECONDS. So the request is not answered and not denied, but gets closed when the envoy shuts down. No draining!

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

Using istio master.

**Comment by c0d1ngm0nk3y** [comment]
@howardjohn We have created a separate issue for that as discussed in #15704 . With those steps, it should be easy to reproduce.

**Comment by howardjohn** [comment]
I think this should be fixed by https://github.com/istio/istio/pull/17460
