### ISSUE TITLE
standardize istioctl structure idiom

### ISSUE THREAD

**Issue by linsun** [istio/istio#15804]
We need to standardize this as we keep growing commands to it.

It was discussed briefly in today's UX mtg but no consensus has reached yet.  There is a few WIs that depends on this.

**Comment by esnible** [comment]
Notes from https://docs.google.com/document/d/1cO1TysDZca6e59Qq9VhcbPZXAcln0YxJZ9ssPVrwSiE/edit

Louis Ryan
`istioctl <type> <commands>` or `istioctl <commands> <type-specific-qualifiers>`

e.g.

```
istioctl services add <service-name>
```

vs

```
istioctl add-to-mesh --service <service>
```

Examples of various patterns:
docker (former)
vagrant (former)
kubectl (mixed but verb set is CRUD 
only)
gcloud (former)


Lin Sun
I think i prefer `istioctl <commands> + commands options` given that is where istioctl is and it is much easier to maintain backwards compatible.

Ed Snible
Openstack used '<category> <type> <verb>', for example `openstack compute service create`. Having categories helps users from being overwhelmed with lots of top-level commands. Within a category I like <verb> <type> for CRUD.

**Comment by esnible** [comment]
The Istio Operator CLI is proposing `istioctl <category> <type> <verb>`.  See  https://docs.google.com/document/d/16SWW14zrwFKc9OzH6biMQD1u9INllzMa56jde9vgQkM/edit (Operator CLI reference, Martin Ostrowski)

Here is a summary of those proposed commands:

```
istioctl manifest versions [--versionsURI <uri>]
istioctl manifest generate [--dry-run]
istioctl manifest apply [--filename <icp.yaml>] [--kubeconfig <path>] [--set <key>=<val>]*
istioctl manifest migrate
istioctl profile list
istioctl profile dump
istioctl profile diff
```

**Comment by esnible** [comment]
The Istio MC Operator CLI uses, I think, `istioctl <type> <verb>`.  See https://docs.google.com/document/d/1ZwZ4KrE2pvcrdE1FVLke6ZMIAfC3y8_SYTzk6K2U9aQ (Multi-cluster mesh operator support proposal, Jason Young)

Here is a summary of those proposed commands

```
istioctl profile generate --profile=default -o spec.yaml
istioctl mesh generate --profile=spec.yaml --clusters=c0,c1 -o mesh.yaml
istioctl mesh describe --mesh=mesh.yaml
istioctl mesh check --mesh=mesh.yaml
istioctl mesh apply --mesh=mesh.yaml
istioctl mesh add cluster=c2 --mesh=mesh.yaml
istioctl mesh check --mesh=mesh.yaml
```

**Comment by mwringe** [comment]
How do we want people to vote on this?

Personally, I like '<verb> <object>' (like how kubectl does things). I feel like it helps with discovery of what you can do with the verb, and it can also help if some verbs have objects that wont exist for other commands.

**Comment by smawson** [comment]
Interestingly kubectl isn't even consistent here, they are mostly `<verb> <object>` but they also have rollout which is `<object> <verb>` style.

I'm OK with either `<object> <verb>` or `<verb> <object>`, I strongly dislike `<verb>-<object>`. If we go with `<verb> <object>` we should be very careful about the set of verbs we support and try to reuse, for example 'check' should be a standard verb we can use on multiple objects, same with generate, list, dump, etc. Of course we should do that anyway though, consistency is good.

Do you want to just propose one of these and bring it up in TOC? Or do you want to get UX group consensus first?

**Comment by ozevren** [comment]
I maybe being a bit pedantic here, but I don't believe this taxonomy is quite right. It is not about `noun`s and `verb`s. It is more about `context`s and `action`s. 

So the alternatives are:
`istioctl <verb> <verb-specific-paremeters>`
v.s.
`istioctl <context> <verb>  <verb-specific-paremeters>`

kubectl follows the first model, where what we call noun (e.g. `pods`) is a `verb-specific-parameter`. Since kubectl's main task is to interact with REST resource, which has a rigid set of actions against a set of resource collections, the REST operations are modeled as verbs and all of those verbs have the same `verb-specific-parameter` as the first thing (i.e. `resource name`). In that sense, rollout is a verb and has its own `verb-specific-parameter`s.

It looks like previous art indicates that `context` (which can hypothetically be things `config`, `cluster`, `debug`, `injection` in our case) is not needed, and we can rely on `verb`s. Certain verbs can have similar/same `verb-specific-parameters` (e.g. Istio resource names, component names such as `pilot` or `galley` etc.).

**Comment by smawson** [comment]
Take a look at the kubectl reference: https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands

They have a lot of verbs, it is by no means a rigid set of actions. They also have a few noun verb combos (rollout, certificate, config). I really don't think kubectl is a good thing to copy from, it isn't self-consistent at all :) Also rollout is not a verb, it is a noun, just as certificate and config are nouns. The user is not certificating something, they are doing an action on certificates (approving or denying them). Same with rollouts, they are restarting a rollout, pausing a rollout, etc.

So for me, noun/verb is absolutely the right way to think about this, all of the "contexts" for kubectl and for istioctl are just nouns, and IMO it is easier for users to think about things that way.

So the question comes down to whether users are going to be thinking about actions first, and then the thing they want to take the action on, or whether they are thinking about the thing they want to interact with, and then want to know what actions are available.

To make this concrete, here are the two flavors:

noun verb:
```
istioctl manifest versions
istioctl manifest generate
istioctl manifest apply
istioctl manifest migrate
istioctl profile generate
istioctl profile list
istioctl profile dump
istioctl profile diff
istioctl mesh generate
istioctl mesh describe
istioctl mesh check
istioctl mesh apply
istioctl mesh add
```
verb noun:
```
istioctl list manifest | profile
istioctl describe profile | mesh
istioctl generate manifest | profile | mesh
istioctl apply manifest | mesh
istioctl migrate manifest
istioctl diff profile
istioctl check mesh
istioctl add mesh
```

Generally the noun - verb one is easier for us to manage but makes inconsistency easier, verb - noun requires us to keep things consistent (for example I lumped describe and dump together, versions and list together).

**Comment by ayj** [comment]
`istioctl <verb> <noun>` could force UX consistency assuming the verbs are well curated. It would require some refactoring of commands. Here's a strawman for what that scheme might look like applied to the current set of istioctl commands.

Assuming the following common verbs ...

```
istioctl generate  # generate Istio API resources (inc. control plane manifest). Can be piped to kubectl apply 
istioctl validate  # Istio API resource validation 
istioctl describe # Report the current state/status of Istio API resources and their effect on services/workloads
istioctl convert  # Convert Istio API resources from one version to another.
istioctl check    # Report the current state/status of the Istio Control and Data plane (not resources)
istioctl apply    # Special case for installing/upgrade
istioctl open   # open tooling, e.g. UI (dashboard), views (metrics, top?)
```

... we might might the current commands

Current | Proposed | Description
-- | -- | --
authn tls-check | check auth | Check whether TLS setting are matching between authentication policy and destination rule
deregister | generate serviceentry \| kubectl delete -f - | De-registers a service instance
register | generate serviceentry \| kubectl apply -f - | Registers a service instance (e.g. VM) joining the mesh
kube-inject | ??? | Manually injects the Envoy sidecar into Kubernetes workloads
proxy-config | check proxy-config | A group of commands used to retrieve information about proxy configuration from the Envoy config dump
proxy-status | check proxy-status | Retrieves last sent and last acknowledged xDS sync from Pilot to each Envoy in the mesh
validate | validate | Istio configuration command line utility for service operators to debug and diagnose their Istio mesh.
verify-install | check control | Verifies Istio installation status against the installation file you specified when you installed Istio
version | version | CLI and control plane version
auth | check auth | Inspect and interact with authentication and authorization policies in the mesh
convert-ingress | convert | Convert Ingress configuration into Istio VirtualService configuration
dashboard | open dashboard | Access to Istio web UIs
kube-uninject | ??? | Uninject Envoy sidecar from Kubernetes pod resources
manifest apply | apply control | Generates and applies Istio install manifest.
manifest diff |   | Compare manifests and generate diff.
manifest generate | generate control | Generates Istio install manifest
manifest migrate | convert | migrates a file containing Helm values to IstioControlPlane format.
manifest versions | N/A | List the version of Istio recommended for and supported by this version of the operator binary.
metrics | open metrics | Prints the metrics for the specified service(s) when running in Kubernetes.
profile diff | generate profile-diff A B | Diffs two Istio configuration profiles.
profile dump | describe profile <profile> | Dumps an Istio configuration profile.
profile list | describe profile [<profile>]* | Lists available Istio configuration profiles.
  |   |

**Comment by smawson** [comment]
Any chance you can throw that in a doc Jason? Maybe hold off and see if anyone is opposed, but bringing consistency seems like exactly what we're shooting for here?

**Comment by ayj** [comment]
https://docs.google.com/document/d/1_s7OW5lCIOuuliQcfOP-B0vFXCg_1NXpxcu6_N_rDDE

**Comment by esnible** [comment]
We didn't standardize this for 1.4.

I'd like to add one other point.  We added `istioctl proxy-config log`.  This is a new command that joins the other `istioctl proxy-config` commands.  Should we have called it `istioctl proxy-config experimental log` because it is new?

My intuition is that if we add new subcommands they should begin life as experimental.  Thoughts?

**Comment by ayj** [comment]
So option 0 or 1 below? How would this change if we used `alpha`/`beta` instead of `experimental` for the prefix? cc @geeknoid 

```
# option 0
istioctl x proxy-config listeners
istioctl x proxy-config log

# option 1
istioctl proxy-config listeners
istioctl proxy-config x log
```
