### ISSUE TITLE
Promote SDS integration from Alpha to Beta

### ISSUE THREAD

**Issue by linsun** [istio/istio#15803]
**Describe the feature request**
SDS integration has drawn lots of interests from users.  We need to identify action items to promote this feature from alpha to beta.

Some known issue in this area:

- SDS doesn't work with egress gateway: https://github.com/istio/istio/issues/15485
- Allow easy trouble shooting: https://github.com/istio/istio/issues/15789
- others?

Additional things to check off:
- sufficient automated tests

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by linsun** [comment]
cc @incfly @myidpt

**Comment by incfly** [comment]
/cc @Monkeyanator given he's working on both two mentioned feature requests.

@linsun  I'm not surprised about the user interests of SDS, but still wondering the feedback you got from them. Is the motivation coming from getting rid of the k8s secrets? How much customization to adapt to their own CA is needed?

**Comment by howardjohn** [comment]
I think this is a duplicate of https://github.com/istio/istio/issues/15267

**Comment by JimmyCYJ** [comment]
cc @JimmyCYJ

**Comment by linsun** [comment]
Agreed this is a dup.  I'll close it now, great it is being making progress elsewhere.

@incfly yes, it is mainly to get rid of k8s secrets and be more secure.  That is the first thing before any additional customization.
