### ISSUE TITLE
How do I use -- set gateways. istio - ingress gateway. nodeSelector

### ISSUE THREAD

**Issue by Hwting** [istio/istio#15808]
**Bug description**
How do I use 
```
-- set gateways.istio-ingressgateway.nodeSelector
```
**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ X] Docs
[ X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Specify ingressgateway scheduling on nodes labeled ingressgateway = true
**Steps to reproduce the bug**
```
Error: render error in "istio/charts/gateways/templates/deployment.yaml": template: istio/charts/gateways/templates/deployment.yaml:306:10: executing "istio/charts/gateways/templates/deployment.yaml" at <include "gatewaynodeaffinity" (dict "root" $ "nodeSelector" $spec.nodeSelector)>: error calling include: template: istio/charts/gateways/templates/_affinity.tpl:6:8: executing "gatewaynodeaffinity" at <include "gatewayNodeAffinityRequiredDuringScheduling" .>: error calling include: template: istio/charts/gateways/templates/_affinity.tpl:23:32: executing "gatewayNodeAffinityRequiredDuringScheduling" at <$nodeSelector>: range can't iterate over test:

```
**Version (include the output of `istioctl version --remote` and `kubectl version`)**
kubernetes:"v1.13.5"
istio:v1.2.2
**How was Istio installed?**
helm template
**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by Hwting** [comment]
Looks like it worked. Thank you @howardjohn

**Comment by howardjohn** [comment]
Great to hear!
