### ISSUE TITLE
Incomplete tests: ingress fault injection

### ISSUE THREAD

**Issue by cmluciano** [istio/istio#1581]
xref: #1474

We are lacking tests for ingress fault injection rules with delay/abort timeouts.

Similar tests for this features can be based on the following:
https://github.com/istio/istio/blob/a97ee8df3a1bc4a163ae56aa8b9d99951c3352bb/pilot/test/integration/routing.go#L82

https://github.com/istio/istio/blob/master/pilot/test/integration/testdata/rule-fault-injection.yaml.tmpl

**Comment by hklai** [comment]
Removing "area/test and release" label as it is not meant for adding functional tests or test coverage.
Please assign issues to the appropriate functional area going forward.
