### ISSUE TITLE
Operator: Translation of gateways components enablement does not work

### ISSUE THREAD

**Issue by richardwxn** [istio/istio#15829]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
For IstioControlPlaneSpec translation, translation of gateways components enablement does not work properly, enabling the gateway features would always enable the components as well, ignoring the specific component enablement value.

E.g.
```gateways:
   components:
     ingressGateway:
     - gateway:
         common:
           enabled: false
     egressGateway:
     - gateway:
         common:
           enabled: false
   enabled: true
```
would translate in ingressGateway and egressGateway enabled: true
**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by sdake** [comment]
@morvencao I'ce removed @ostromart as he is probably overloaded on issues for the operator repo and added you as an assigneer.  If you are not interested in solving this problem please unassign yourself.

Cheers
-steve

**Comment by morvencao** [comment]
@sdake Let me take this one.

**Comment by ostromart** [comment]
Hi @morvencao it may be better for me to take this one. It's a little complicated and I know the code pretty well. If you really want to take it I won't fight you for it though :-)

**Comment by morvencao** [comment]
@ostromart Sure, go ahead if you have enough bandwidth to handle this. 
I can take other tasks.

**Comment by ostromart** [comment]
Fixed in https://github.com/istio/operator/pull/133.
