### ISSUE TITLE
Figure out correct labeling to indicate an Istio resource is under operator management

### ISSUE THREAD

**Issue by ostromart** [istio/istio#15825]
We need a label that makes it clear to users what the behavior of the operator will be wrt that resource. 
Current placeholder proposal is to follow k8s addon manager pattern which adds the following label:
istio-operator-managed: [Reconcile|EnsureExists]
The reason this label is required is so that operator never prunes objects that are not directly under its control. The actual label name and allowed values should be revisited.

**Comment by ayj** [comment]
Related https://github.com/istio/istio/issues/14777 which suggests namespace'ing our labels, e.g. operator.istio.io/managed

**Comment by elfinhe** [comment]
Just verified that all resources managed by operator is using labels:
operator.istio.io/component={{ComponentName}},
operator.istio.io/managed=Reconcile

except for namespace, namespace is still using:
istio-operator-managed
https://github.com/istio/installer/blob/master/crds/templates/namespaces.yaml
