### ISSUE TITLE
istioctl kube-inject doesn't support podAnnotation

### ISSUE THREAD

**Issue by gitirabassi** [istio/istio#15837]
why is istioctl not calling https://github.com/istio/istio/blob/master/pilot/pkg/kube/inject/inject.go#L408?

This makes the behaviour of `istioctl kube-inject` different then the mutatingwebook

**Comment by irisdingbj** [comment]
Thanks  and I agree we should make the webhook and istioctl behave the same.

**Comment by esnible** [comment]
@irisdingbj What are the plans for this issue?

**Comment by esnible** [comment]
@irisdingbj Will you be able to get this in 1.5?
