### ISSUE TITLE
pilot/test/mixer/wordlist/wordlist.go: is it necessary?

### ISSUE THREAD

**Issue by jmuk** [istio/istio#1583]
I've noticed that there's a file called `pilot/test/mixer/wordlist/wordlist.go` which nobody refers to. As a quick research, pilot repository had `test/mixer` code for mock mixer server (for pilot e2e test), and this `wordlist.go` file was a part of it. That mock server code isn't in this istio monorepo now, but the `wordlist.go` still exists.

Does this mean we can simply remove the whole `pilot/test/mixer` directory? or are there any cases  I'm missing?

**Comment by jmuk** [comment]
@kyessenov

**Comment by rshriram** [comment]
you could remove it as long as you build the mixer as part of pilot e2e test. But please dont use bazel to build it as it wont work in circle ci.

**Comment by kyessenov** [comment]
Feel free remove. I removed mock mixer as part of the move since we can run real mixer under one roof.
