### ISSUE TITLE
unable to apply multiple certificates in istio-ingressgateway while hosting multiple site using same single gateway

### ISSUE THREAD

**Issue by ngbit95** [istio/istio#15835]
as mentioned in offical documnetation https://archive.istio.io/v1.1/docs/tasks/traffic-management/secure-ingress/sds/
I followed same procedure to host mult-site using multiple certificate but failed to apply both.
for ex:-

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http-abc
      protocol: HTTP
    tls:
      httpsRedirect: true # sends 301 redirect for http requests
    hosts:
    - "abc.com"
  - port:
      number: 443
      name: https-abc
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: "abc-credential"
    hosts:
    - "abc.com"
  - port:
      number: 80
      name: http-xyz
      protocol: HTTP
    tls:
      httpsRedirect: true # sends 301 redirect for http requests
    hosts:
    - "xyz.com"
  - port:
      number: 443
      name: https-xyz
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: "xyz-credential"
    hosts:
    - "xyz.com"

both the certificates are uploaded in istio-system namespace as TLS/secret but it can only works for first one i.e abc-credential and unable to works for xyz-credential.
Please let me know if anyone find solution for it.

**Comment by ngbit95** [comment]
Can anyone please give me solution for this issue, i need this asap!!

**Comment by ngbit95** [comment]
Any update on this issue, i need this to be resolved asap , since it need to be implemented for production level in project, can anyone from istio help out in this, its already being a month nearly, i didn't got any response for this.!!

**Comment by JimmyCYJ** [comment]
@ngbit95 Could you provide more information for investigation. For example, which release version of Istio are you using? What tools do you use to generate credentials? Could you show us the log of ingress-sds container, and the log of ingress gateway container?
