### ISSUE TITLE
Fully automate migration from helm with manifest migrate/upgrade

### ISSUE THREAD

**Issue by ostromart** [istio/istio#15843]
See https://docs.google.com/document/d/16SWW14zrwFKc9OzH6biMQD1u9INllzMa56jde9vgQkM/edit?ts=5d39c8d1#
Ed Snible:
`Users typically install Istio once, then upgrade four times a year. The upgrade is a "major task". Can we implement an "istioctl upgrade" command that checks for IstioControlPlane CR, does "istioctl manifest migrate" to create the IstioControlPlane CR from the istio-sidecar-injector data.values if needed, then does "istioctl manifest apply"?

When I look at https://istio.io/docs/setup/kubernetes/upgrade/steps/ there are many decisions about CNI, profiles, and customizations. Can the CLI include a command that handles all of that?`
Investigate if this could be done safely, perhaps using manifest diff to determine if the migrated config is equivalent wrt output manifest. It probably will not be (at least for 1.2) because operator is using the new charts, so the diff would have to be quite sophisticated.

**Comment by elfinhe** [comment]
@howardjohn, @ostromart, to be clear, this was discussed in the [upgrade design doc](https://docs.google.com/document/d/1OdnfyBai5ytjQy6lwU1KWOVgRHf-RSIRDLx_SFpOXGE/edit#heading=h.5ngf21150qdg).

We will NOT include this migration in the `istioctl upgrade` command, but will probably propose a new sub-command like `istioctl manifest apply --migrate` or `istioctl manifest generate --migrate`, which will require a separate design doc to address specific problems in the migration.

--
I think I will focus on `istilctl x upgrade` before 1.4.0 code freeze. 
Un-assign myself, to give others an opportunity to take a look, and if possible, pls take this issue. Or I can own this probably in November.

**Comment by ostromart** [comment]
Repurposing this issue for 1.6. The plan now is to only support upgrade using dual control plane - manifest migrate should just take care of translating values.yaml from the old helm charts to whatever the 1.6 format will be with istiod.
Since values.yaml is likely to be heavily reduced post istiod, we need to take a fresh look at the translations - many parameters will disappear which should probably result in some warning message.

**Comment by howardjohn** [comment]
We have removed manifest migrate so I think this is not relevant anymore?
