### ISSUE TITLE
Introduce Mesh ID, for aggregating telemetry

### ISSUE THREAD

**Issue by djazayeri** [istio/istio#15849]
Add a Mesh UID to Istio to support the specific use case of aggregating telemetry from multiple Istio meshes in one place, and then being able to query it, distinguishing which mesh particular entries came from.

(There are other uses for Mesh UID, relating to multicluster and cross-mesh service identity, but these are out of scope.)

This was approved by the P&T WG on 7/17/19 and referred for a Config and Security discussion of where to store it. The response was to store this in MeshConfig.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Details**

1. MeshConfig should support a mesh_uid attribute
   * if the mesh admin specifies a value, we should use it; otherwise we should autogenerate a UUID value. (I don't know exactly the flow, so where it would be stored in this case.)
2. Define and populate a mixer attribute `destination.mesh.uid`
3. Change the Stackdriver adapter's config to consume the new attribute and attach it to metrics.

**Additional context**

See this doc for more details: https://tinyurl.com/y45s5x2d

**Comment by djazayeri** [comment]
@kyessenov, @geeknoid suggested you can implement this, but I don't have privs to assign to you.

**Comment by kyessenov** [comment]
Did networking & environments approve adding things to MeshConfig?

**Comment by djazayeri** [comment]
No. I have spoken with P&T, Config, and Security. And I assumed that Config could sign off on adding something to MeshConfig. Do I also need to reach out to those groups?

**Comment by kyessenov** [comment]
@costinm FYI, we're planning to make these changes.

**Comment by djazayeri** [comment]
Costin commented at https://discuss.istio.io/t/fyi-adding-mesh-uid-for-an-initially-limited-telemetry-use-case/3287/2 (and I asked a followup)

**Comment by djazayeri** [comment]
Changes:

* Call this “Mesh ID” (not “Mesh UID”)
* Admin can specify this in values.yaml; the value is eventually exposed in the istio-sidecar-injector ConfigMap (not in MeshConfig)
* Default value when not specified by the admin will be the mesh’s Trust Domain. (Do not autogenerate a UUID.)

See https://discuss.istio.io/t/proposal-adding-mesh-uid-for-telemetry/3118/3
