### ISSUE TITLE
Use in-cluster config as a default for manifest migrate

### ISSUE THREAD

**Issue by ostromart** [istio/istio#15842]
See https://docs.google.com/document/d/16SWW14zrwFKc9OzH6biMQD1u9INllzMa56jde9vgQkM/edit?ts=5d39c8d1#heading=h.24ooes3koj32
If --file is not specified, manifest migrate should be able to get the full config in cluster using 
`kubectl -n istio-system get cm istio-sidecar-injector -o jsonpath="{.data.values}"`

**Comment by richardwxn** [comment]
It was merged as part of manifest migrate command: [operator#132](https://github.com/istio/operator/pull/132)
