### ISSUE TITLE
istioctl version output: option to show client version only

### ISSUE THREAD

**Issue by palmerabollo** [istio/istio#15858]
**Describe the feature request**

`istioctl version` in istio 1.2.0 breaks backwards compatibility because it returns an exit code 1 when it is not able to determine the control plane version. In istio 1.1.x the same command always returns an exit code 0 because it doesn't check the remote pods.

With the current approach, it is more difficult to use it in automated scripts. It would be nice to **have an option to get the client version only**.

**Describe alternatives you've considered**

**Option 1**: Add a `istioctl version --client` similar to the existing `--remote` argument (#2491).

**Option 2**: Make `istioctl version` return the client version only and leave the existing `--remote` parameter for those who also need to determine the control plane version.

I'd prefer option 2 but I understand it changes the current behavior.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Additional context**

Thanks

**Comment by howardjohn** [comment]
`istioctl version --remote=false` should do it

**Comment by palmerabollo** [comment]
Thanks, it works.
