### ISSUE TITLE
cleanup pilot-agent related logic with controlPlaneBootstrap

### ISSUE THREAD

**Issue by quanjielin** [istio/istio#15853]
[ProxyConfig](https://github.com/istio/api/blob/master/mesh/v1alpha1/proxy.proto#L115) doesn't have 
```controlPlaneBootstrap``` property anymore

however pilot-agent code still uses ```controlPlaneBootstrap``` , for example, below code supposed to only run for controlplane sidecar, now it run for every workload sidecar(since controlPlaneBootstrap is set to true and unconfigurable now)
```
			if controlPlaneBootstrap {
				if templateFile != "" && proxyConfig.CustomConfigFile == "" {
					opts["PodName"] = podNameVar.Get()
					opts["PodNamespace"] = podNamespaceVar.Get()
					// Setting default to ipv4 local 
```

**Comment by quanjielin** [comment]
@costinm with this, logic in https://github.com/istio/istio/pull/15420 has to be tweaked (since it also rely on controlPlaneBootstrap)

**Comment by costinm** [comment]
Why doesn't it have it anymore ? Removing properties from APIs is a big no.

**Comment by quanjielin** [comment]
I don't have much context on the history...today proxyconfig doesn't have controlPlaneBootstrap property, which result in controlPlaneBootstrap is configurable(always set to true) in pilot-agent( https://github.com/istio/istio/blob/master/pilot/cmd/pilot-agent/main.go#L621)
