### ISSUE TITLE
How to rewrite a regex uri

### ISSUE THREAD

**Issue by kingsqv** [istio/istio#15857]
in this case how to rewrite 
\- match:
    \- uri:
        regex: /xxx-api/.\*/export
    rewrite:
      uri: /.\*/export 
    route:
    ...
does support rewrite like nginx : 
rewrite ^/api/files/(\w+)/filters(.*)$ /files/$1/filters$2 break;

**Comment by arianmotamedi** [comment]
This is currently not supported by Envoy. I looked at the code and looks like the rewrite action on the Route doesn't capture the prefix context. Could you please open up a feature request in https://github.com/envoyproxy/envoy?

**Comment by kingsqv** [comment]
OK THANKS

**Comment by dotbalo** [comment]
How is this problem handled? I want to achieve access to /api/abc to /abc, it seems impossible?
