### ISSUE TITLE
Istio Mixer TCP filter doesn't report attributes if `onData` event is not called

### ISSUE THREAD

**Issue by nrjpoddar** [istio/istio#15867]
**Describe the feature request**
The Istio TCP Mixer filter currently only exports attributes if `onData` event is invoked. This means when the new connections are created https://github.com/istio/proxy/blob/master/src/envoy/tcp/mixer/filter.cc#L138 and the connection is not successful, no attributes get generated.

We recently added telemetry for BlackHole cluster https://github.com/istio/istio/pull/15512 but since the mixer filters don't send attributes on new connection, we are still not getting any telemetry for BlackHole cluster.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[x] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**
https://github.com/envoyproxy/envoy/issues/7725
https://github.com/istio/istio/issues/7669

**Comment by nrjpoddar** [comment]
cc @kyessenov

**Comment by bianpengyuan** [comment]
@qiwzhang Do you recall why we add check in onData instead of onNewConnection? I remember when I added connection open event we want to have it to be reported after policy check passes, and I think you mentioned some reason that check has to be in onData but I cannot recall now... https://github.com/istio/proxy/pull/1849

**Comment by kyessenov** [comment]
The issue is with telemetry. We don't collect anything about connection that are dropped after onNewConnection, which we should.

**Comment by kyessenov** [comment]
The policy check should remain in onData since SSL info is populated after newConnection.

**Comment by bianpengyuan** [comment]
Right yeah, it is because of TLS. It should be fine to move the connection open event to newConnection.

**Comment by nrjpoddar** [comment]
That sounds correct. We need to think about the trigger for reporting the attributes as currently that happens inside connection close event.
