### ISSUE TITLE
IP whitelist does not work

### ISSUE THREAD

**Issue by bmonteiro** [istio/istio#15885]
The functionality IP whitelist is not working like it is documented here https://raw.githubusercontent.com/istio/istio/release-1.2/samples/bookinfo/policy/mixer-rule-deny-ip.yaml 

[ ] Configuration Infrastructure
[X] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

When provided a list of CIDRs here :
...   
kind: handler
...
 overrides: ["ip1/xx","ip2/xx",...] 
....

Install istio 1.2.2

kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T18:55:03Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-eks-c57ff8", GitCommit:"c57ff8e35590932c652433fab07988da79265d5b", GitTreeState:"clean", BuildDate:"2019-06-07T20:43:03Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

kubectl get deployment istio-pilot -o yaml -n istio-system | grep image
        image: docker.io/istio/pilot:1.2.2
        imagePullPolicy: IfNotPresent
        image: docker.io/istio/proxyv2:1.2.2
        imagePullPolicy: IfNotPresent

**Comment by gargnupur** [comment]
@bmonteiro : is this still an issue and what is the error that you are seeing?

**Comment by gargnupur** [comment]
@bmonteiro : Closing this, as haven't heard back from you. Please re-open with more details.
