### ISSUE TITLE
Pods with sidecar injection stuck in ContainerCreating status

### ISSUE THREAD

**Issue by mishaque** [istio/istio#15895]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
My pods with side car injection is not starting: 

Pod logs shows following error

` Warning  FailedCreatePodSandBox  61s (x4 over 2m32s)  kubelet, lxappstrldev0001  (combined from similar events): Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "a7d47adab4560c602c0e491b9e4a2f2ebd89cd2a3cc61232842c94ad02dc9a2a" network for pod "httpbin-6cbc6f986f-kh52h": NetworkPlugin cni failed to set up pod "httpbin-6cbc6f986f-kh52h_default" network: exit status 3`

Here is the status of istio pods:

`kube-system    istio-cni-node-4kfl4                               1/1     Running             0          2d15h   172.29.172.188   lxappomsdev002   <none>           <none>
kube-system    istio-cni-node-9tmt2                               1/1     Running             0          2d15h   172.29.162.36    lxappomsdev007             <none>           <none>
kube-system    istio-cni-node-l48kp                               1/1     Running             0          2d15h   172.29.162.35    lxappomsdev006             <none>           <none>
kube-system    istio-cni-node-lt277                               1/1     Running             0          2d15h   172.29.172.189   lxappomsdev003.lowes.com   <none>           <none>
kube-system    istio-cni-node-n5nmn                               1/1     Running             0          2d15h   172.29.162.110   lxappstrldev0001           <none>           <none>
kube-system    istio-cni-node-pqnnj                               1/1     Running             0          2d15h   172.29.162.111   lxappstrldev0002           <none>           <none>
kube-system    istio-cni-node-wk9kh                               1/1     Running             0          2d15h   172.29.172.187   lxappomsdev001.lowes.com   <none>           <none>
`

`istio-system   istio-galley-5b984f89b-n74xp                       1/1     Running             0          2d15h   10.244.3.7       lxappomsdev006             <none>           <none>
`

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
I have followed the documentation for enabling the istio CNI. Galley and CNI pods are in running state with no error. 
**Steps to reproduce the bug**
- Install istio with side car injection on a single control plane cluster created with "kubeadm"
- deploy the pod with side car injection

`kubectl apply -f <(istioctl kube-inject -f samples/httpbin/httpbin.yaml)`

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
`client version: 1.2.2
citadel version: 1.2.2
galley version: 1.2.2
ingressgateway version: 1.2.2
pilot version: 1.2.2
policy version: 1.2.2
sidecar-injector version: 1.2.2
telemetry version: 1.2.2
`

`Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T14:25:20Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
`

**How was Istio installed?**
` helm install install/kubernetes/helm/istio --name istio --namespace istio-system --set istio_cni.enabled=true`

**Environment where bug was observed (cloud vendor, OS, etc)**
On prem Kubernetes

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by rlenglet** [comment]
Istio CNI logs into journalctl on the node. Can you grep for  "nsenter" in journalctl logs?

**Comment by rlenglet** [comment]
@mishaque more specifically look for a log containing "nsenter failed".

**Comment by rlenglet** [comment]
@mishaque Also can you give more details about the kernel on your worker nodes? What version? Does it support iptables? nftables?

**Comment by mishaque** [comment]
@rlenglet here is the logs for nsenter:

`Jul 29 11:21:24 lxappstrldev0001 kubelet[12441]: 2019-07-29 11:21:24.695 [ERROR][24692] redirect.go 264: nsenter failed: exit status 3 err=exit status 3 out="Environment:\n------------\nENVOY_PORT=\nISTIO_INBOUND_INTERCEPTION_MODE=\nISTIO_INBOUND_TPROXY_MARK=\nISTIO_INBOUND_TPROXY_ROUTE_TABLE=\nISTIO_INBOUND_PORTS=\nISTIO_LOCAL_EXCLUDE_PORTS=\nISTIO_SERVICE_CIDR=\nISTIO_SERVICE_EXCLUDE_CIDR=\n\nVariables:\n----------\nPROXY_PORT=15001\nINBOUND_CAPTURE_PORT=15001\nPROXY_UID=1337\nINBOUND_INTERCEPTION_MODE=REDIRECT\nINBOUND_TPROXY_MARK=1337\nINBOUND_TPROXY_ROUTE_TABLE=133\nINBOUND_PORTS_INCLUDE=80\nINBOUND_PORTS_EXCLUDE=15020\nOUTBOUND_IP_RANGES_INCLUDE=*\nOUTBOUND_IP_RANGES_EXCLUDE=\nOUTBOUND_PORTS_EXCLUDE=15020\nKUBEVIRT_INTERFACES=\nENABLE_INBOUND_IPV6=\n\n+ IPTABLES_RETRY=true\n+ iptables -t nat -N ISTIO_REDIRECT\n+ iptables_retry /usr/sbin/iptables -t nat -N ISTIO_REDIRECT\n+ '[' true '!=' true ']'\n+ local iptables_wait=30\n+ set +o errexit\n+ true\n+ /usr/sbin/iptables -t nat -N ISTIO_REDIRECT\n+ local err_code=0\n+ [[ 0 == 0 ]]\n+ break\n+ set -o errexit\n+ return 0\n+ iptables -t nat -A ISTIO_REDIRECT -p tcp -j REDIRECT --to-port 15001\n+ iptables_retry /usr/sbin/iptables -t nat -A ISTIO_REDIRECT -p tcp -j REDIRECT --to-port 15001\n+ '[' true '!=' true ']'\n+ local iptables_wait=30\n+ set +o errexit\n+ true\n+ /usr/sbin/iptables -t nat -A ISTIO_REDIRECT -p tcp -j REDIRECT --to-port 15001\n+ local err_code=0\n+ [[ 0 == 0 ]]\n+ break\n+ set -o errexit\n+ return 0\n+ iptables -t nat -N ISTIO_IN_REDIRECT\n+ iptables_retry /usr/sbin/iptables -t nat -N ISTIO_IN_REDIRECT\n+ '[' true '!=' true ']'\n+ local iptables_wait=30\n+ set +o errexit\n+ true\n+ /usr/sbin/iptables -t nat -N ISTIO_IN_REDIRECT\n+ local err_code=0\n+ [[ 0 == 0 ]]\n+ break\n+ set -o errexit\n+ return 0\n+ iptables -t nat -A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-port 15001\n+ iptables_retry /usr/sbin/iptables -t nat -A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-port 15001\n+ '[' true '!=' true ']'\n+ local iptables_wait=30\n+ set +o errexit\n+ true\n+ /usr/sbin/iptables -t nat -A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-port 15001\n+ local err_code=0\n+ [[ 0 == 0 ]]\n+ break\n+ set -o errexit\n+ return 0\n+ '[' -n 80 ']'\n+ '[' REDIRECT = TPROXY ']'\n+ table=nat\n+ iptables -t nat -N ISTIO_INBOUND\n+ iptables_retry /usr/sbin/iptables -t nat -N ISTIO_INBOUND\n+ '[' true '!=' true ']'\n+ local iptables_wait=30\n+ set +o errexit\n+ true\n+ /usr/sbin/iptables -t nat -N ISTIO_INBOUND\n+ local err_code=0\n+ [[ 0 == 0 ]]\n+ break\n+ set -o errexit\n+ return 0\n+ iptables -t nat -A PREROUTING -p tcp -j ISTIO_INBOUND\n+ iptables_retry /usr/sbin/iptables -t nat -A PREROUTING -p tcp -j ISTIO_INBOUND\n+ '[' true '!=' true ']'\n+ local iptables_wait=30\n+ set +o errexit\n+ true\n+ /usr/sbin/iptables -t nat -A PREROUTING -p tcp -j ISTIO_INBOUND\n+ local err_code=0\n+ [[ 0 == 0 ]]\n+ break\n+ set -o errexit\n+ return 0\n+ '[' 80 == '*' ']'\n+ for port in '${INBOUND_PORTS_INCLUDE}'\n+ '[' REDIRECT = TPROXY ']'\n+ iptables -t nat -A ISTIO_INBOUND -p tcp --dport 80 -j ISTIO_IN_REDIRECT\n+ iptables_retry /usr/sbin/iptables -t nat -A ISTIO_INBOUND -p tcp --dport 80 -j ISTIO_IN_REDIRECT\n+ '[' true '!=' true ']'\n+ local iptables_wait=30\n+ set +o errexit\n+ true\n+ /usr/sbin/iptables -t nat -A ISTIO_INBOUND -p tcp --dport 80 -j ISTIO_IN_REDIRECT\n+ local err_code=0\n+ [[ 0 == 0 ]]\n+ break\n+ set -o errexit\n+ return 0\n+ iptables -t nat -N ISTIO_OUTPUT\n+ iptables_retry /usr/sbin/iptables -t nat -N ISTIO_OUTPUT\n+ '[' true '!=' true ']'\n+ local iptables_wait=30\n+ set +o errexit\n+ true\n+ /usr/sbin/iptables -t nat -N ISTIO_OUTPUT\n+ local err_code=0\n+ [[ 0 == 0 ]]\n+ break\n+ set -o errexit\n+ return 0\n+ iptables -t nat -A OUTPUT -p tcp -j ISTIO_OUTPUT\n+ iptables_retry /usr/sbin/iptables -t nat -A OUTPUT -p tcp -j ISTIO_OUTPUT\n+ '[' true '!=' true ']'\n+ local iptables_wait=30\n+ set +o errexit\n+ true\n+ /usr/sbin/iptables -t nat -A OUTPUT -p tcp -j ISTIO_OUTPUT\n+ local err_code=0\n+ [[ 0 == 0 ]]\n+ break\n+ set -o errexit\n+ return 0\n+ '[' -n 15020 ']'\n+ for port in '${OUTBOUND_PORTS_EXCLUDE}'\n+ iptables -t nat -A ISTIO_OUTPUT -p tcp --dport 15020 -j RETURN\n+ iptables_retry /usr/sbin/iptables -t nat -A ISTIO_OUTPUT -p tcp --dport 15020 -j RETURN\n+ '[' true '!=' true ']'\n+ local iptables_wait=30\n+ set +o errexit\n+ true\n+ /usr/sbin/iptables -t nat -A ISTIO_OUTPUT -p tcp --dport 15020 -j RETURN\n+ local err_code=0\n+ [[ 0 == 0 ]]\n+ break\n+ set -o errexit\n+ return 0\n+ '[' -z '' ']'\n+ iptables -t nat -A ISTIO_OUTPUT -o lo '!' -d 127.0.0.1/32 -j ISTIO_REDIRECT\n+ iptables_retry /usr/sbin/iptables -t nat -A ISTIO_OUTPUT -o lo '!' -d 127.0.0.1/32 -j ISTIO_REDIRECT\n+ '[' true '!=' true ']'\n+ local iptables_wait=30\n+ set +o errexit\n+ true\n+ /usr/sbin/iptables -t nat -A ISTIO_OUTPUT -o lo '!' -d 127.0.0.1/32 -j ISTIO_REDIRECT\n+ local err_code=0\n+ [[ 0 == 0 ]]\n+ break\n+ set -o errexit\n+ return 0\n+ for uid in '${PROXY_UID}'\n+ iptables -t nat -A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN\n+ iptables_retry /usr/sbin/iptables -t nat -A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN\n+ '[' true '!=' true ']'\n+ local iptables_wait=30\n+ set +o errexit\n+ true\n+ /usr/sbin/iptables -t nat -A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN\n+ local err_code=0\n+ [[ 0 == 0 ]]\n+ break\n+ set -o errexit\n+ return 0\n+ for gid in '${PROXY_GID}'\n+ iptables -t nat -A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN\n+ iptables_retry /usr/sbin/iptables -t nat -A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN\n+ '[' true '!=' true ']'\n+ local iptables_wait=30\n+ set +o errexit\n+ true\n+ /usr/sbin/iptables -t nat -A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN\n+ local err_code=0\n+ [[ 0 == 0 ]]\n+ break\n+ set -o errexit\n+ return 0\n+ iptables -t nat -A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN\n+ iptables_retry /usr/sbin/iptables -t nat -A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN\n+ '[' true '!=' true ']'\n+ local iptables_wait=30\n+ set +o errexit\n+ true\n+ /usr/sbin/iptables -t nat -A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN\n+ local err_code=0\n+ [[ 0 == 0 ]]\n+ break\n+ set -o errexit\n+ return 0\n+ '[' 0 -gt 0 ']'\n+ '[' 1 -gt 0 ']'\n+ '[' '*' == '*' ']'\n+ iptables -t nat -A ISTIO_OUTPUT -j ISTIO_REDIRECT\n+ iptables_retry /usr/sbin/iptables -t nat -A ISTIO_OUTPUT -j ISTIO_REDIRECT\n+ '[' true '!=' true ']'\n+ local iptables_wait=30\n+ set +o errexit\n+ true\n+ /usr/sbin/iptables -t nat -A ISTIO_OUTPUT -j ISTIO_REDIRECT\n+ local err_code=0\n+ [[ 0 == 0 ]]\n+ break\n+ set -o errexit\n+ return 0\n+ set +o nounset\n+ '[' -n '' ']'\n+ ip6tables -F INPUT\n+ iptables_retry /usr/sbin/ip6tables -F INPUT\n+ '[' true '!=' true ']'\n+ local iptables_wait=30\n+ set +o errexit\n+ true\n+ /usr/sbin/ip6tables -F INPUT\nip6tables v1.4.21: can't initialize ip6tables table `filter': Address family not supported by protocol\nPerhaps ip6tables or your kernel needs to be upgraded.\n+ local err_code=3\n+ [[ 3 == 0 ]]\n+ iptables_wait=29\n+ ((  iptables_wait > 0  ))\n+ sleep 1\n+ true\n+ /usr/sbin/ip6tables -F INPUT\nip6tables v1.4.21: can't initialize ip6tables table `filter': Address family not supported by protocol\nPerhaps ip6tables or your kernel needs to be upgraded.\n+ local err_code=3\n+ [[ 3 == 0 ]]\n+ iptables_wait=28\n+ ((  iptables_wait > 0  ))\n+ sleep 1\n+ true\n+ /usr/sbin/ip6tables -F INPUT\nip6tables v1.4.21: can't initialize ip6tables table `filter': Address family not supported by protocol\nPerhaps ip6tables or your kernel needs to be upgraded.\n+ local err_code=3\n+ [[ 3 == 0 ]]\n+ iptables_wait=27\n+ ((  iptables_wait > 0  ))\n+ sleep 1\n+ true\n+ /usr/sbin/ip6tables -F INPUT\nip6tables v1.4.21: can't initialize ip6tables table `filter': Address family not supported by protocol\nPerhaps ip6tables or your kernel needs to be upgraded.\n+ local err_code=3\n+ [[ 3 == 0 ]]\n+ iptables_wait=26\n+ ((  iptables_wait > 0  ))\n+ sleep 1\n+ true\n+ /usr/sbin/ip6tables -F INPUT\nip6tables v1.4.21: can't initialize ip6tables table `filter': Address family not supported by protocol\nPerhaps ip6tables or your kernel needs to be upgraded.\n+ local err_code=3\n+ [[ 3 == 0 ]]\n+ iptables_wait=25\n+ ((  iptables_wait > 0  ))\n+ sleep 1\n+ true\n+ /usr/sbin/ip6tables -F INPUT\nip6tables v1.4.21: can't initialize ip6tables table `filter': Address family not supported by protocol\nPerhaps ip6tables or your kernel needs to be upgraded.\n+ local err_code=3\n+ [[ 3 == 0 ]]\n+ iptables_wait=24\n+ ((  iptables_wait > 0  ))\n+ sleep 1\n+ true\n+ /usr/sbin/ip6tables -F INPUT\nip6tables v1.4.21: can't initialize ip6tables table `filter': Address family not supported by protocol\nPerhaps ip6tables or your kernel needs to be upgraded.\n+ local err_code=3\n+ [[ 3 == 0 ]]\n+ iptables_wait=23\n+ ((  iptables_wait > 0  ))\n+ sleep 1\n+ true\n+ /usr/sbin/ip6tables -F INPUT\nip6tables v1.4.21: can't initialize ip6tables table `filter': Address family not supported by protocol\nPerhaps ip6tables or your kernel needs to be upgraded.\n+ local err_code=3\n+ [[ 3 == 0 ]]\n+ iptables_wait=22\n+ ((  iptables_wait > 0  ))\n+ sleep 1\n+ true\n+ /usr/sbin/ip6tables -F INPUT\nip6tables v1.4.21: can't initialize ip6tables table `filter': Address family not supported by protocol\nPerhaps ip6tables or your kernel needs to be upgraded.\n+ local err_code=3\n+ [[ 3 == 0 ]]\n+ iptables_wait=21\n+ ((  iptables_wait > 0  ))\n+ sleep 1\n+ true\n+ /usr/sbin/ip6tables -F INPUT\nip6tables v1.4.21: can't initialize ip6tables table `filter': Address family not supported by protocol\nPerhaps ip6tables or your kernel needs to be upgraded.\n+ local err_code=3\n+ [[ 3 == 0 ]]\n+ iptables_wait=20\n+ ((  iptables_wait > 0  ))\n+ sleep 1\n+ true\n+ /usr/sbin/ip6tables -F INPUT\nip6tables v1.4.21: can't initialize ip6tables table `filter': Address family not supported by protocol\nPerhaps ip6tables or your kernel needs to be upgraded.\n+ local err_code=3\n+ [[ 3 == 0 ]]\n+ iptables_wait=19\n+ ((  iptables_wait > 0  ))\n+ sleep 1\n+ true\n+ /usr/sbin/ip6tables -F INPUT\nip6tables v1.4.21: can't initialize ip6tables table `filter': Address family not supported by protocol\nPerhaps ip6tables or your kernel needs to be upgraded.\n+ local err_code=3\n+ [[ 3 == 0 ]]\n+ iptables_wait=18\n+ ((  iptables_wait > 0  ))\n+ sleep 1\n+ true\n+ /usr/sbin/ip6tables -F INPUT\nip6tables v1.4.21: can't initialize ip6tables table `filter': Address family not supported by protocol\nPerhaps ip6tables or your kernel needs to be upgraded.\n+ local err_code=3\n+ [[ 3 == 0 ]]\n+ iptables_wait=17\n+ ((  iptables_wait > 0  ))\n+ sleep 1\n+ true\n+ /usr/sbin/ip6tables -F INPUT\nip6tables v1.4.21: can't initialize ip6tables table `filter': Address family not supported by protocol\nPerhaps ip6tables or your kernel needs to be upgraded.\n+ local err_code=3\n+ [[ 3 == 0 ]]\n+ iptables_wait=16\n+ ((  iptables_wait > 0  ))\n+ sleep 1\n+ true\n+ /usr/sbin/ip6tables -F INPUT\nip6tables v1.4.21: can't initialize ip6tables table `filter': Address family not supported by protocol\nPerhaps ip6tables or your kernel needs to be upgraded.\n+ local err_code=3\n+ [[ 3 == 0 ]]\n+ iptables_wait=15\n+ ((  iptables_wait > 0  ))\n+ sleep 1\n+ true\n+ /usr/sbin/ip6tables -F INPUT\nip6tables v1.4.21: can't initialize ip6tables table `filter': Address family not supported by protocol\nPerhaps ip6tables or your kernel needs to be upgraded.\n+ local err_code=3\n+ [[ 3 == 0 ]]\n+ iptables_wait=14\n+ ((  iptables_wait > 0  ))\n+ sleep 1\n+ true\n+ /usr/sbin/ip6tables -F INPUT\nip6tables v1.4.21: can't initialize ip6tables table `filter': Address family not supported by protocol\nPerhaps ip6tables or your kernel needs to be upgraded.\n+ local err_code=3\n+ [[ 3 == 0 ]]\n+ iptables_wait=13\n+ ((  iptables_wait > 0  ))\n+ sleep 1\n+ true\n+ /usr/sbin/ip6tables -F INPUT\nip6tables v1.4.21: can't initialize ip6tables table `filter': Address family not supported by protocol\nPerhaps ip6tables or your kernel needs to be upgraded.\n+ local err_code=3\n+ [[ 3 == 0 ]]\n+ iptables_wait=12\n+ ((  iptables_wait > 0  ))\n+ sleep 1\n+ true\n+ /usr/sbin/ip6tables -F INPUT\nip6tables v1.4.21: can't initialize ip6tables table `filter': Address family not supported by protocol\nPerhaps ip6tables or your kernel needs to be upgraded.\n+ local err_code=3\n+ [[ 3 == 0 ]]\n+ iptables_wait=11\n+ ((  iptables_wait > 0  ))\n+ sleep 1\n+ true\n+ /usr/sbin/ip6tables -F INPUT\nip6tables v1.4.21: can't initialize ip6tables table `filter': Address family not supported by protocol\nPerhaps ip6tables or your kernel needs to be upgraded.\n+ local err_code=3\n+ [[ 3 == 0 ]]\n+ iptables_wait=10\n+ ((  iptables_wait > 0  ))\n+ sleep 1\n+ true\n+ /usr/sbin/ip6tables -F INPUT\nip6tables v1.4.21: can't initialize ip6tables table `filter': Address family not supported by protocol\nPerhaps ip6tables or your kernel needs to be upgraded.\n+ local err_code=3\n+ [[ 3 == 0 ]]\n+ iptables_wait=9\n+ ((  iptables_wait > 0  ))\n+ sleep 1\n+ true\n+ /usr/sbin/ip6tables -F INPUT\nip6tables v1.4.21: can't initialize ip6tables table `filter': Address family not supported by protocol\nPerhaps ip6tables or your kernel needs to be upgraded.\n+ local err_code=3\n+ [[ 3 == 0 ]]\n+ iptables_wait=8\n+ ((  iptables_wait > 0  ))\n+ sleep 1\n+ true\n+ /usr/sbin/ip6tables -F INPUT\nip6tables v1.4.21: can't initialize ip6tables table `filter': Address family not supported by protocol\nPerhaps ip6tables or your kernel needs to be upgraded.\n+ local err_code=3\n+ [[ 3 == 0 ]]\n+ iptables_wait=7\n+ ((  iptables_wait > 0  ))\n+ sleep 1\n+ true\n+ /usr/sbin/ip6tables -F INPUT\nip6tables v1.4.21: can't initialize ip6tables table `filter': Address family not supported by protocol\nPerhaps ip6tables or your kernel needs to be upgraded.\n+ local err_code=3\n+ [[ 3 == 0 ]]\n+ iptables_wait=6\n+ ((  iptables_wait > 0  ))\n+ sleep 1\n+ true\n+ /usr/sbin/ip6tables -F INPUT\nip6tables v1.4.21: can't initialize ip6tables table `filter': Address family not supported by protocol\nPerhaps ip6tables or your kernel needs to be upgraded.\n+ local err_code=3\n+ [[ 3 == 0 ]]\n+ iptables_wait=5\n+ ((  iptables_wait > 0  ))\n+ sleep 1\n+ true\n+ /usr/sbin/ip6tables -F INPUT\nip6tables v1.4.21: can't initialize ip6tables table `filter': Address family not supported by protocol\nPerhaps ip6tables or your kernel needs to be upgraded.\n+ local err_code=3\n+ [[ 3 == 0 ]]\n+ iptables_wait=4\n+ ((  iptables_wait > 0  ))\n+ sleep 1\n+ true\n+ /usr/sbin/ip6tables -F INPUT\nip6tables v1.4.21: can't initialize ip6tables table `filter': Address family not supported by protocol\nPerhaps ip6tables or your kernel needs to be upgraded.\n+ local err_code=3\n+ [[ 3 == 0 ]]\n+ iptables_wait=3\n+ ((  iptables_wait > 0  ))\n+ sleep 1\n+ true\n+ /usr/sbin/ip6tables -F INPUT\nip6tables v1.4.21: can't initialize ip6tables table `filter': Address family not supported by protocol\nPerhaps ip6tables or your kernel needs to be upgraded.\n+ local err_code=3\n+ [[ 3 == 0 ]]\n+ iptables_wait=2\n+ ((  iptables_wait > 0  ))\n+ sleep 1\n+ true\n+ /usr/sbin/ip6tables -F INPUT\nip6tables v1.4.21: can't initialize ip6tables table `filter': Address family not supported by protocol\nPerhaps ip6tables or your kernel needs to be upgraded.\n+ local err_code=3\n+ [[ 3 == 0 ]]\n+ iptables_wait=1\n+ ((  iptables_wait > 0  ))\n+ sleep 1\n+ true\n+ /usr/sbin/ip6tables -F INPUT\nip6tables v1.4.21: can't initialize ip6tables table `filter': Address family not supported by protocol\nPerhaps ip6tables or your kernel needs to be upgraded.\n+ local err_code=3\n+ [[ 3 == 0 ]]\n+ iptables_wait=0\n+ ((  iptables_wait > 0  ))\n+ exit 3\n+ dump\n+ iptables-save\n# Generated by iptables-save v1.4.21 on Mon Jul 29 11:21:24 2019\n*mangle\n:PREROUTING ACCEPT [2:286]\n:INPUT ACCEPT [2:286]\n:FORWARD ACCEPT [0:0]\n:OUTPUT ACCEPT [2:144]\n:POSTROUTING ACCEPT [2:144]\nCOMMIT\n# Completed on Mon Jul 29 11:21:24 2019\n# Generated by iptables-save v1.4.21 on Mon Jul 29 11:21:24 2019\n*nat\n:PREROUTING ACCEPT [0:0]\n:INPUT ACCEPT [0:0]\n:OUTPUT ACCEPT [0:0]\n:POSTROUTING ACCEPT [0:0]\n:ISTIO_INBOUND - [0:0]\n:ISTIO_IN_REDIRECT - [0:0]\n:ISTIO_OUTPUT - [0:0]\n:ISTIO_REDIRECT - [0:0]\n-A PREROUTING -p tcp -j ISTIO_INBOUND\n-A OUTPUT -p tcp -j ISTIO_OUTPUT\n-A ISTIO_INBOUND -p tcp -m tcp --dport 80 -j ISTIO_IN_REDIRECT\n-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15001\n-A ISTIO_OUTPUT -p tcp -m tcp --dport 15020 -j RETURN\n-A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -j ISTIO_REDIRECT\n-A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN\n-A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN\n-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN\n-A ISTIO_OUTPUT -j ISTIO_REDIRECT\n-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001\nCOMMIT\n# Completed on Mon Jul 29 11:21:24 2019\n# Generated by iptables-save v1.4.21 on Mon Jul 29 11:21:24 2019\n*filter\n:INPUT ACCEPT [2:286]\n:FORWARD ACCEPT [0:0]\n:OUTPUT ACCEPT [2:144]\nCOMMIT\n# Completed on Mon Jul 29 11:21:24 2019\n+ ip6tables-save\n"
`
We are using RHEL 7 Kernel version is : 3.10.0-957.21.3.el7.x86_64

**Comment by rlenglet** [comment]
Ok so IPv6 is disabled in your kernel?

**Comment by rlenglet** [comment]
That is weird because the script attempts to setup ip6tables chains only if the pod has an IPv6 address.
@mishaque could you please run "ip addr" inside a pod (without injection)?

**Comment by mishaque** [comment]
Here is the output from ifconfig for the same "httpbin" pod without the injection:

`eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
        inet 10.244.5.6  netmask 255.255.255.0  broadcast 0.0.0.0
        ether 7a:c8:a5:a6:f9:0b  txqueuelen 0  (Ethernet)
        RX packets 110  bytes 202824 (202.8 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 80  bytes 5572 (5.5 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
`

**Comment by rlenglet** [comment]
Thanks! So that means that the isIPv6 function in the istio-iptables.sh script is buggy. I'll fix that.

**Comment by mishaque** [comment]
@rlenglet is there a workaround for time being?

**Comment by mishaque** [comment]
@rlenglet, thanks for including this in the 1.3 milestone. I will try enabling the IPV6 on the Node as a workaround; I am not sure if this would solve the issue. Please let me know your recommendation/workaround.

**Comment by rlenglet** [comment]
The `ENABLE_INBOUND_IPV6` variable is not set in your logs:
```
ENABLE_INBOUND_IPV6=\n
```
So there is no mis-detection of IPv6. That part is correct.
The commands that are failing are those executed in case IPv6 is **not** detected:
https://github.com/istio/cni/blob/master/tools/packaging/common/istio-iptables.sh#L665-L668
```
  ip6tables -F INPUT || true
  ip6tables -A INPUT -m state --state ESTABLISHED -j ACCEPT || true
  ip6tables -A INPUT -i lo -d ::1 -j ACCEPT || true
  ip6tables -A INPUT -j REJECT || true
```
These commands are failing because of the retrying of the commands in this script.
I need to disable retries for those in case IPv6 is disabled.

This bug is specific to Istio CNI's version of the `istio-iptables.sh` script.
So @mishaque you could try using normal injection instead of Istio CNI. It won't have this problem.
