### ISSUE TITLE
Performance regression detected starting on build 07/25

### ISSUE THREAD

**Issue by jnativio** [istio/istio#15899]
**Bug description**
The Istio Regression Patrol  is showing a regression in throughput and response time on all 3 configurations (full istio, no mixer, ingress only) and for the 2 branches tested (1.1 and 1.2) for builds starting on 07/25. The degradation is from 10% to 15% compared with the baseline (1.1 GA) or previous builds (see https://ibmcloud-perf.istio.io/regpatrol/).
To verify that this degradation was not due to some unforeseen change in the test environment, I ran again the load with build 07/22 and got good results, as shown in the comparison charts below for 2 configurations:

![image](https://user-images.githubusercontent.com/18554027/62059646-a1206400-b1f1-11e9-8577-ad9a3917b9cc.png)
![image](https://user-images.githubusercontent.com/18554027/62059689-b0071680-b1f1-11e9-9830-a9a1f69dfed0.png)

Since the "ingress_only" configuration is equally affected, that indicates a change introduced in the ingress gateway could be the cause of this regression.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[x] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
No performance regression from build to build.

**Steps to reproduce the bug**
Compare throughput and latency of app using an Istio build prior and after 07/25.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
istioctl version:
release-1.2-20190725-09-15 and later
kubectl version:
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.8+IKS", GitCommit:"fe3e332c2b0f47d4572433c3b0a1687a27fb88c6", GitTreeState:"clean", BuildDate:"2019-07-11T13:45:03Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
Helm

**Environment where bug was observed (cloud vendor, OS, etc)**
IKS

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.
Plenty of data and metrics when drilling down specific build/configuration on https://ibmcloud-perf.istio.io/regpatrol/

**Comment by jnativio** [comment]
@mandarjog

**Comment by howardjohn** [comment]
1.1 had a regression? There has been nothing new on the 1.1 branch though?

**Comment by jnativio** [comment]
@howardjohn That is interesting. I wonder why new builds of 1.1 are being produced every day. In any case, do you have performance tests for builds prior and after 07/25 that can be compared, so we can cross-check the results?

**Comment by howardjohn** [comment]
@jnativio we produce new builds of all versions that are still in the support window every day, even if there are no commits during that time. I don't have any perf tests for those builds though

**Comment by mandarjog** [comment]
@jnativio Is there anything in your cluster that is different? If you can retest baseline and get the same results, that will rule it out.
@howardjohn did we make any other build change, such as go compiler version, dep upgrade of any kind ?

**Comment by howardjohn** [comment]
No changes to our release process as far as I can tell.

**Comment by jnativio** [comment]
@mandarjog No change in the environment that I could detect. As I said, I went back to a previous build and ran the workload again with it and I saw no regression. It would be great to have some results with Fortio using builds from before 07/25 and after.

**Comment by jnativio** [comment]
After some more tests, I concluded that something in the underlying infrastructure has changed and that is likely the cause of the performance loss observed. To avoid the regression patrol to continue showing current and future builds as "regressed" in comparison with the previous baseline, I started a new landing page using 1.2.3 as the new baseline. 
Closing this issue.
