### ISSUE TITLE
Multicluster setup issue 

### ISSUE THREAD

**Issue by rajeshneo** [istio/istio#15908]
**Bug description**
I have two EKS clusters in private subnets in EKS. I am trying to connect them via steps mentioned in https://istio.io/docs/setup/kubernetes/install/multicluster/gateways/. Installation looks ok but when i try to connect cross cluster httpbin service i get following

 kubectl exec --context=$CTX_CLUSTER1 $SLEEP_POD -n foo -c sleep -- curl -I httpbin.bar.global:8000/headers
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (52) Empty reply from server
command terminated with exit code 52

-------
This is seen on istiocoredns

2019-07-29T22:28:49.022180Z	info	Have 1 service entries
2019-07-29T22:28:49.022222Z	info	adding DNS mapping: httpbin.bar.global.->[127.255.0.3]
2019-07-29T22:28:53.612113Z	info	DNS query  ;; opcode: QUERY, status: NOERROR, id: 61096
;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;httpbin.bar.global.global.	IN	 AAAA
2019-07-29T22:28:53.612195Z	info	Could not find the service requested
2019-07-29T22:28:53.612232Z	info	DNS query  ;; opcode: QUERY, status: NOERROR, id: 60888
;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;httpbin.bar.global.global.	IN	 A
2019-07-29T22:28:53.612254Z	info	Query A record: httpbin.bar.global.global.->{httpbin.bar.global.global. 1 1}
2019-07-29T22:28:53.612264Z	info	Could not find the service requested
2019-07-29T22:28:53.613557Z	info	DNS query  ;; opcode: QUERY, status: NOERROR, id: 10366
;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;httpbin.bar.global.	IN	 AAAA
2019-07-29T22:28:53.613589Z	info	Could not find the service requested
2019-07-29T22:28:53.613655Z	info	DNS query  ;; opcode: QUERY, status: NOERROR, id: 10225
;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;httpbin.bar.global.	IN	 A
2019-07-29T22:28:53.613704Z	info	Query A record: httpbin.bar.global.->{httpbin.bar.global. 1 1}
2019-07-29T22:28:53.613711Z	info	Found httpbin.bar.global.->[127.255.0.3]

Any pointers what i could be doing wrong or what logs should i be looking into.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Cross cluster connection should be established.
**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
 istioctl version --remote
client version: 1.2.2
citadel version: master-20190725-09-15
egressgateway version: master-20190725-09-15
galley version: master-20190725-09-15
ingressgateway version: master-20190725-09-15
pilot version: master-20190725-09-15
policy version: master-20190725-09-15
sidecar-injector version: master-20190725-09-15
telemetry version: master-20190725-09-15

 kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-20T04:49:16Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-eks-c57ff8", GitCommit:"c57ff8e35590932c652433fab07988da79265d5b", GitTreeState:"clean", BuildDate:"2019-06-07T20:43:03Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
**How was Istio installed?**
Istio installed via steps mentioned in https://istio.io/docs/setup/kubernetes/install/multicluster/gateways/
**Environment where bug was observed (cloud vendor, OS, etc)**
EKS
Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by ayj** [comment]
@rajeshneo, are you still seeing this problem? If so, can you re-post on discuss.istio.io with the latest details?
