### ISSUE TITLE
Cloudant Egress Does not Work

### ISSUE THREAD

**Issue by brentcty** [istio/istio#1590]
using...

istio 0.2.12
kubectl 1.8.x
minikube 0.23.0

I've applied the EgressRule to allow access to *.cloudant.com from the mesh. I can curl to HTTP specifying port 443 inside the pod shell. 

curl http://70d5a96b-b80f-4e87-a0bf-fc22053d6a2d-bluemix:55e07c44dbe7d359ddc1ecc36599ce0b586b6db3d3820bd2dafde31499076928@70d5a96b-b80f-4e87-a0bf-fc22053d6a2d-bluemix.cloudant.com:443

I get the below, so egress rule looks like it worked.

{"couchdb":"Welcome","version":"2.0.0","vendor":{"name":"IBM Cloudant","version":"6365","variant":"paas"},"features":["geo","scheduler"]}

However, in Node.JS app when inserting record into Cloudant database that I have initialized with kube secrets like the following...

var cloudant = Cloudant({
  "username": process.env.CLOUDANT_USERNAME,
  "password": process.env.CLOUDANT_PASSWORD,
  "host": process.env.CLOUDANT_HOST,
  "port": process.env.CLOUDANT_PORT,
  "url": process.env.CLOUDANT_URL
});

I am getting the following error...

Error: write EPROTO 140557910480704:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:797

I have tried every combo for the url when initializing Cloudant with HTTPS and HTTP, and specifying the 443 port and not. Nothing seems to work.

**Comment by brentcty** [comment]
Looks like wildcards for EgressRules requires quotes (i.e. "*.cloudant.com") according to YAML LINT. Should probably update the documentation to indicate such.

**Comment by brentcty** [comment]
I'm getting the following console.log when initializing cloudant like above when I use the http:// preface in the url. Looks like this is happening before the request gets to the envoy. As a result, envoy is sending as https:// url, which does not seem to work.

WARNING: You are sending your password as plaintext over the HTTP; switching to HTTPS

**Comment by rshriram** [comment]
@vadimeisenbergibm ^^^

**Comment by vadimeisenbergibm** [comment]
@brentcty as you noted, the client library switches to https ( TLS origination on the client), which is not yet supported by Istio egress rules. Before this support is added in Istio, you can call Cloudant directly - see https://istio.io/docs/tasks/traffic-management/egress.html#calling-external-services-directly .

**Comment by brentcty** [comment]
Thank you. I would hate to lose out on the istio auditing and tracing. If I am able to configure Cloudant client libs to use an HTTP server, what address would I give it? The address of the egress service?  with port 80?

**Comment by vadimeisenbergibm** [comment]
@brentcty note that egress service does not function as HTTP Proxy. It intercepts tcp traffic by iptables. So you cannot use it a HTTP proxy. The only solution I see currently is calling Cloudant directly - https://istio.io/docs/tasks/traffic-management/egress.html#calling-external-services-directly.

**Comment by brentcty** [comment]
Unfortunately, direct is not working either. I am running in minikube and issue the following command

kubectl apply -f <(istioctl kube-inject -f install/app.yml --includeIPRanges=10.0.0.1/24)

I go into the app shell, and...

curl http://httpbin.org/headers

and I get nothing. I am using auto initializer if that matters.

**Comment by vadimeisenbergibm** [comment]
@brentcty I do not know how kube-inject works with istio initializer. @ayj - any comment on this?
I would remove initializer and try to perform kube-inject.

**Comment by ayj** [comment]
Both automatic (initializer) and manual (kube-inject) injection methods have no effect if the input resource already has a sidecar injected. This is determined by the presence of `sidecar.istio.io/status` annotation. 

You can try disabling automatic injection for the specific workload and using kube-inject instead. Override the default automatic injection policy by adding the `sidecar.istio.io/inject: "false"` annotation to your deployment, e.g.

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myapp
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  replicas: 1
  template:
```

See https://istio.io/docs/setup/kubernetes/sidecar-injection.html#overriding-automatic-injection for details.

**Comment by vadimeisenbergibm** [comment]
Thanks, @ayj !
