### ISSUE TITLE
"certificate is not valid for any names" error when invoking validation webhook in multi-tenant scenario

### ISSUE THREAD

**Issue by sushicw** [istio/istio#15904]
**Bug description**

I'm working on improving how the Galley validation webhook works so that we can fully support a [multi-tenant scenario](https://istio.io/blog/2018/soft-multitenancy/) (separate parallel control planes). While working on this, I'm running into a certificate error that I'm not sure how to handle. I could use some help understanding what's happening. 

CC @nmittler @ayj

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
I want to properly configure multi-tenant galley 

**Steps to reproduce the bug**

1. Created a test version of istio.yaml (istio-1.yaml) with the following changes:
* Changed namespace ```s/istio-system/istio-system-1/g```
* Specify ```--webhook-name=istio-system-1-istio-galley``` in galley command line options
* ```s/kubectl get validatingwebhookconfiguration istio-galley/kubectl get validatingwebhookconfiguration istio-system-1-istio-galley```
2. Created istio-2.yaml similarly, using namespace istio-system-2
3. Installed the first control plane: ```kubectl apply -f install/kubernetes/istio-1.yaml```
4. Waited, and then verified webhook configuration installed: ```kubectl get ValidatingWebhookConfiguration```
5. Test applying istio-specific config:
5.1. ```kubectl apply -f samples/bookinfo/networking/destination-rule-all.yaml```
5.2. ```kubectl delete -f samples/bookinfo/networking/destination-rule-all.yaml```
6. Install the second control plane: ```kubectl apply -f install/kubernetes/istio-2.yaml```
7. Waited, and then verified a second webhook configuration was installed: ```kubectl get ValidatingWebhookConfiguration```.
8. Test applying config again:
8.1 ```kubectl apply -f samples/bookinfo/networking/destination-rule-all.yaml```
8.2 This time, though, it fails with this error message on the command line: 
```
Error from server (InternalError): error when creating "samples/bookinfo/networking/destination-rule-all.yaml": Internal error occurred: failed calling admission webhook "pilot.validation.istio.io": Post https://istio-galley.istio-system-2.svc:443/admitpilot?timeout=30s: x509: certificate is not valid for any names, but wanted to match istio-galley.istio-system-2.svc
Error from server (InternalError): error when creating "samples/bookinfo/networking/destination-rule-all.yaml": Internal error occurred: failed calling admission webhook "pilot.validation.istio.io": Post https://istio-galley.istio-system-2.svc:443/admitpilot?timeout=30s: x509: certificate is not valid for any names, but wanted to match istio-galley.istio-system-2.svc
Error from server (InternalError): error when creating "samples/bookinfo/networking/destination-rule-all.yaml": Internal error occurred: failed calling admission webhook "pilot.validation.istio.io": Post https://istio-galley.istio-system-2.svc:443/admitpilot?timeout=30s: x509: certificate is not valid for any names, but wanted to match istio-galley.istio-system-2.svc
Error from server (InternalError): error when creating "samples/bookinfo/networking/destination-rule-all.yaml": Internal error occurred: failed calling admission webhook "pilot.validation.istio.io": Post https://istio-galley.istio-system-2.svc:443/admitpilot?timeout=30s: x509: certificate is not valid for any names, but wanted to match istio-galley.istio-system-2.svc
```
8.3 Meanwhile, the galley logs contain: 
```
2019-07-29T20:02:27.046416Z	info	http: TLS handshake error from 10.138.15.233:43308: remote error: tls: bad certificate
2019-07-29T20:02:27.059455Z	info	http: TLS handshake error from 10.138.15.233:43310: remote error: tls: bad certificate
2019-07-29T20:02:27.073913Z	info	http: TLS handshake error from 10.138.15.234:37054: remote error: tls: bad certificate
2019-07-29T20:02:27.088227Z	info	http: TLS handshake error from 10.12.0.1:43314: remote error: tls: bad certificate
```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

Master (currently at 3e44854b200c50042225b9d2ab84b2652b84f9a3)

**How was Istio installed?**

See above

**Environment where bug was observed (cloud vendor, OS, etc)**

GKE cluster

[istio-dump.tar.gz](https://github.com/istio/istio/files/3444181/istio-dump.tar.gz)

**Comment by ayj** [comment]
>  x509: certificate is not valid for any names, but wanted to match istio-galley.istio-system-2.svc

The apiserver constructed the DNS name from the validatingwebhookconfiguration (i.e. `<service>.<namespace>.svc`). In this case the name corresponds to the istio-galley instance in istio-system-2 namespace which is correct. However, Galley in namespace istio-system-2 is likely presenting a different SAN. Based on the secrets in `istio-dump/resources.yaml` it looks like galley's cert contains the spiffie identity `URI:spiffe://cluster.local/ns/istio-system-1/sa/istio-galley-service-account` and not a DNS hostname (`DNS:istio-galley.istio-system-2.svc`). Next steps would be to debug why Citadel is generating a cert with spiffie identity instead of DNS.

**Comment by sushicw** [comment]
After talking with @ayj offline, I was able to solve this by adding ```--listened-namespaces=default-1``` to the command line args in istio-citadel. Thanks Jason!

**Comment by sb1975** [comment]
This didnt work for and still getting below error - Error from server (InternalError): error when creating "install/kubernetes/istio-demo.yaml": Internal error occurred: failed calling webhook "1-mixer.validation.istio.io": Post https://istio-galley-1.istio-system1.svc:443/admitmixer?timeout=30s: x509: certificate is not valid for any names, but wanted to match istio-galley-1.istio-system1.svc
