### ISSUE TITLE
Addon installation documentation for GKE Istio with out helm

### ISSUE THREAD

**Issue by etsrepo** [istio/istio#15924]
**Describe the feature request**

- There is no straight forward documentation for istio installed by GKE, there is no helm setup or any manually configured process in GKE. 
- By default it uses stackdriver for metrics and traces. 
- No documentation for setting up Kiali or Grafana with above setup. 

**Affected product area (please put an X in all that apply)**

[x] Configuration Infrastructure
[x] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[x] Developer Infrastructure

**Comment by howardjohn** [comment]
I believe there are docs at https://cloud.google.com/istio/docs/istio-on-gke/overview. Is there something more you are looking for?

**Comment by etsrepo** [comment]
specifically there is no configuration for kiali and grafana. there is no option in GKE console or gcloud command or any other option.

if we do any changes with helm repo, somehow changes made by helm reverting back what configured by GKE. 

I would like to have some options where we can use kiali, servicegraph in GKE enabled Istio without messing with stackdriver or any default configurations.

**Comment by howardjohn** [comment]
We don't control the Istio on GKE docs. If https://cloud.google.com/istio/docs/istio-on-gke/overview isn't sufficient then I suggest filing a bug against the GKE docs.

> if we do any changes with helm repo, somehow changes made by helm reverting back what configured by GKE.

This is expected, Istio on GKE will revert any changes you make
