### ISSUE TITLE
TestStreamSecretsMultiplePush test failure

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#15923]
I am seeing this often now. One example: 
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/15882/istio-unit-tests-master/4489

**Comment by JimmyCYJ** [comment]
Thanks for catching this. I can reproduce it in 100 runs. This is caused by a timing issue. When the SDS connection is teared down, gRPC library will close connection and transport accordingly. There is a chance that the test client receives different error message at that stage. I will send out a fix soon.

**Comment by howardjohn** [comment]
Thanks! we have some perf issues where kubelet is stealing tons of CPU on
prow causing all sorts of test failures that rely on timing. Should be
fixed in the next few days but in the mean time we can improve some of our
tests

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gcs/istio-prow/logs/unit-tests_istio_postsubmit/1812

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gcs/istio-prow/logs/unit-tests_istio_postsubmit/1831

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gcs/istio-prow/logs/unit-tests_istio_postsubmit/1846

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/22361/unit-tests_istio/10548

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gcs/istio-prow/logs/unit-tests_istio_postsubmit/1864

**Comment by JimmyCYJ** [comment]
It flakes at the last verification which checks number of total push. I will send out a PR to disable that verification soon.
