### ISSUE TITLE
"curl -L https://git.io/getIstio | sh -"  is not working

### ISSUE THREAD

**Issue by fedeagu** [istio/istio#15921]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

istioctl binary in my path

**Steps to reproduce the bug**

curl -L https://git.io/getIstio | sh -

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

https://istio-releases.github.io/v0.1/docs/tasks/installing-istio.html#installation-steps

**Comment by howardjohn** [comment]
The script is `curl -L https://git.io/getLatestIstio | ISTIO_VERSION=1.2.2 sh -`

as indicated by https://istio.io/docs/setup/kubernetes/#downloading-the-release

Are you looking at old docs maybe?

**Comment by fedeagu** [comment]
Sorry! Google took me directly there
