### ISSUE TITLE
Feature: Selectively disable istio-telemetry or istio-telemetry httpFilter 

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#15935]
1. Switch off istio-telemetry only for http on the client side. Only install mixer client network filter.  *Do not* install filter in http_connection manager.
2. Switch off Istio-telemetry without switching off policy

This will be used to smoothly migrate from Mixer based telemetry to Mixerv2.

**Comment by douglas-reid** [comment]
Need to investigate using `EnvoyFilter` to remove / modify legacy mixer filter. Could save on impl costs.

**Comment by howardjohn** [comment]
Done by #17695?
