### ISSUE TITLE
Add Alibaba Nacos as a new services discovery backend

### ISSUE THREAD

**Issue by IanCao** [istio/istio#15943]
Alibaba Nacos is Service Discovery and Management,and more and more chinese company use it.
So i want add nacos as a new istio services discovery backend

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
This should be done as an MCP server rather than integrating directly into pilot code

**Comment by IanCao** [comment]
> This should be done as an MCP server rather than integrating directly into pilot code

could u provider some docs for me to start?

**Comment by howardjohn** [comment]
Here is an example WIP for a nacos MCP server https://github.com/nacos-group/nacos-istio and here is one for consul https://github.com/costinm/istio-consul
