### ISSUE TITLE
Grafana can't login

### ISSUE THREAD

**Issue by winds6206** [istio/istio#15957]
Hello

I installed istio-1.2.2 by reference this 
URL: https://istio.io/docs/setup/kubernetes/install/kubernetes/ 

then install Kiali by reference this
URL: https://istio.io/docs/tasks/telemetry/kiali/

I can use admin/admin to login Kiali, but I can't use admin/admin to login grafana 
what is the grafana default account . BTW I try  admin/space ,too

**Comment by howardjohn** [comment]
As far as I know you shouldn't need to login to grafana. If you want to set up accounts though here is all the variables we set up:
https://github.com/istio/istio/blob/c5ff36a66084fe7f3b72d5a15203f5783317dbec/install/kubernetes/helm/istio/charts/grafana/templates/deployment.yaml#L53-L76

From https://grafana.com/docs/installation/configuration/#security the default is admin/admin

**Comment by winds6206** [comment]
Oh ~ Thank you 
but, I try to use helm to  customizable install , I try to custom grafana account .
Here is my command

$ helm template install/kubernetes/helm/istio --name istio --namespace istio-system --set grafana.security.enabled=true --set grafana.security.usernameKey=admin --set grafana.security.passphraseKey=admin --values install/kubernetes/helm/istio/values-istio-demo.yaml | kubectl apply -f -

I add --set <key>=<value> reference by this
URL: https://istio.io/docs/reference/config/installation-options/#grafana-options

I still can't login my grafana

**Comment by winds6206** [comment]
Oh .. I know everything ...
I forgot that I install another grafana in my host before.
Now I can login direct ,but I wanna setup my account
Here is my command
```
helm template install/kubernetes/helm/istio --name istio --namespace istio-system \
--set "grafana.security.enabled=true" \
--set "grafana.security.usernameKey=admin" \
--set "grafana.security.passphraseKey=admin" \
--values install/kubernetes/helm/istio/values-istio-demo.yaml | kubectl apply -f -
```

when deploy complete, my grafana pod status become "CreateContainerConfigError"

**Comment by winds6206** [comment]
Now I can login direct ,but I wanna user  variables to set up default account
here is my command
```
helm template install/kubernetes/helm/istio --name istio --namespace istio-system \
--set "grafana.security.enabled=true" \
--set "grafana.security.usernameKey=admin" \
--set "grafana.security.passphraseKey=admin" \
--values install/kubernetes/helm/istio/values-istio-demo.yaml | kubectl apply -f -
```

when deploy competed, the grafana pod status become "CreateContainerConfigError "
