### ISSUE TITLE
Pilot connection failures due to low proxy timeout

### ISSUE THREAD

**Issue by bzurkowski** [istio/istio#15954]
**Bug description**

Every 50 seconds Pilot populates the following error entries indicating that a connection to Galley has been closed:

```
{"level":"error","time":"2019-07-30T08:29:16.031511Z","scope":"mcp","msg":"Error receiving MCP resource: rpc error: code = Unavailable desc = transport is closing"}
{"level":"error","time":"2019-07-30T08:29:16.032531Z","scope":"mcp","msg":"Error receiving MCP response: rpc error: code = Unavailable desc = transport is closing"}

{"level":"error","time":"2019-07-30T08:30:07.043039Z","scope":"mcp","msg":"Error receiving MCP resource: rpc error: code = Unavailable desc = transport is closing"}
{"level":"error","time":"2019-07-30T08:30:07.043079Z","scope":"mcp","msg":"Error receiving MCP response: rpc error: code = Unavailable desc = transport is closing"}

{"level":"error","time":"2019-07-30T08:30:58.050878Z","scope":"mcp","msg":"Error receiving MCP resource: rpc error: code = Unavailable desc = transport is closing"}
{"level":"error","time":"2019-07-30T08:30:58.052275Z","scope":"mcp","msg":"Error receiving MCP response: rpc error: code = Unavailable desc = transport is closing"}
```

This behaviour, similarly to cases described in https://github.com/istio/istio/issues/15774 and https://github.com/istio/istio/issues/15457, is caused by a low client timeout configured in a mid proxy mediating traffic between services.

In my case, the proxy is provided by OpenStack Neutron LB operated by [Kuryr Kubernetes CNI](https://docs.openstack.org/kuryr-kubernetes/latest/devref/kuryr_kubernetes_design.html) which for each Kuberentes service spawns a HAProxy instance in tcp mode with the following configuration:

```
global
    daemon
    user nobody
    group haproxy
    log /dev/log local0
    log /dev/log local1 notice
    maxconn 2000
    stats socket /var/lib/neutron/lbaas/v2/0a847509-af53-4e1f-a67c-02ed360f49d9/haproxy_stats.sock mode 0666 level user

defaults
    log global
    retries 3
    option redispatch
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend 2e483339-071f-4ec0-bad9-d9155b3040ed
    option tcplog
    bind 10.100.1.1:443
    mode tcp
    default_backend 28fed07e-4041-4777-895d-fc0fa816dbc0

backend 28fed07e-4041-4777-895d-fc0fa816dbc0
    mode tcp
    balance roundrobin
    server 6d636e77-590e-4622-b7d5-d435ef4e384c 10.100.0.104:6443 weight 1
```

The configuration explains the regular frequency of connection errors and failed watches occurring every 50 seconds - `timeout client` set to 50 seconds.

Most services in Kubernetes and Istio control plane communicate using gRPC performing RPCs via long-lived HTTP/2 connections. Without proper mechanisms for keeping connections open frequent errors will be common, especially for idle services.

Idle Istio service mesh generates too many errors, which, although harmless, significantly limit the clarity of operation. Having connection errors populated every few seconds makes it difficult to detect and debug "real" issues.

Istio provides keepalive options for several control plane components e.g. `keepaliveInterval` and `keepaliveTimeout` parameters for Pilot, however, these options are not applied for the use case of keeping idle connections open. Keepalive pings are sent only if there are active RPCs present. This behaviour is controled via `PermitWithoutStream` option:

```go
// If true, client sends keepalive pings even with no active RPCs. If false,
// when there are no active RPCs, Time and Timeout will be ignored and no
// keepalive pings will be sent.
PermitWithoutStream bool // false by default.
```

For some components i.e. [Galley](https://github.com/istio/istio/pull/15141), on the [server side](https://github.com/istio/istio/blob/08d475e78b396444529e49a4ef0e3d4dd4d1370f/galley/pkg/server/components/processing.go#L240-L242), we permit keepalive pings over idle connections:

```go
grpc.KeepaliveEnforcementPolicy(keepalive.EnforcementPolicy{
    MinTime:             30 * time.Second,
    PermitWithoutStream: true,
}),
```

However, there is no corresponding configuration no the client side:

> // ClientParameters is used to set keepalive parameters on the client-side.
// These configure how the client will actively probe to notice when a
// connection is broken and send pings so intermediaries will be aware of the
// liveness of the connection. Make sure these parameters are set in
// coordination with the keepalive policy on the server, as incompatible
// settings can result in closing of connection.

My proposal is to enable keepalive pings for idle connections by switching the `PermitWithoutStream` flag to `true` for the communication between Istio control plane services. That should reduce the number of connection failures on regular operation.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

No connection failures occurring on regular operation.

**Steps to reproduce the bug**

1. Configure inter-service proxy LB with a low client timeout.
2. Install Istio v1.2.2 and wait until the installation completes.
3. Start observing Pilot logs: connection failures occur once in a proxy timeout (e.g. every 50 seconds).

**Version**

Istio:
```
client version: 1.2.2
citadel version: 1.2.2
galley version: 1.2.2
ingressgateway version: 1.2.2
pilot version: 1.2.2
sidecar-injector version: 1.2.2
telemetry version: 1.2.2
telemetry version: 1.2.2
```

Kubernetes:
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

Helm chart

**Environment where bug was observed (cloud vendor, OS, etc)**

Bare metal, Kubernetes (Kuryr Kubernetes CNI), CentOS

**Comment by rshriram** [comment]
> My proposal is to enable keepalive pings for idle connections by switching the PermitWithoutStream flag to true for the communication between Istio control plane services. That should reduce the number of connection failures on regular operation.

go for it! thanks for the troubleshooting

**Comment by bzurkowski** [comment]
Keepalive pings from grpc library have empty data field and as such are not respected by mid proxy. The approach described above didn't fix the issue.

**Comment by hzxuzhonghu** [comment]
@bzurkowski I can not imagine the proxy is in tcp mode, why the pings not passed through?
