### ISSUE TITLE
error   rbac    nil service instance

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#15960]
I am seeing `error   rbac    nil service instance` in pilot logs repeatedly

Need to investigate if this is a real issue or not. If it is, find out whats going on, if not see if we can add more info to the log - it is not very helpful without more context.

cc @yangminzhu

**Comment by howardjohn** [comment]
Seems like this is due to defining a Gateway on a port that isn't defined in the ingressgateway Service spec

**Comment by yangminzhu** [comment]
> Seems like this is due to defining a Gateway on a port that isn't defined in the ingressgateway Service spec

@howardjohn Hmm, Should this be allowed? The logging in rbac is just checking `ServiceInstance` not nil which is the prerequisite for generating any RBAC filter config, if it's too noisy, we could change it to debug level.

**Comment by howardjohn** [comment]
> Seems like this is due to defining a Gateway on a port that isn't defined in the ingressgateway Service spec

I don't think this works but the only indication I of an issue was the obscure rbac error. Maybe we just need a more explicit check for this (outside of the rbac logic), preferably in a way we expose to the user

**Comment by esnible** [comment]
For medium-term we have https://github.com/istio/istio/pull/15824 which introduces multi-resource analysis with reporting through CRD Status field or Event.  For the near-term how can we surface this to the user?

**Comment by howardjohn** [comment]
Our only options right now are logging or metrics I think

**Comment by rforberger** [comment]
I am getting the same error ```error	rbac	nil service instance```

@howardjohn How do you mean 

> Seems like this is due to defining a Gateway on a port that isn't defined in the ingressgateway Service spec

Do I have to define the Istio Gateway port in the ingressgateway service spec? I think this contradicts the idea of the dynamic of the istio-ingressgateway.

**Comment by howardjohn** [comment]
That's just how kubernetes works, you cannot call a service on a port that isn't defined in the service spec. The Service can be a superset of the gateway though

**Comment by rforberger** [comment]
@howardjohn 
That means I need to define my Gateway service ports also in the istio-ingressgateway service spec?
I was thinking, I call the istio-ingressgateway on its <clusterIP>:<ExposedPort> or <NodeIP>:<Nodeport> and the istio service mesh handles the traffic routing to the target pod.

**Comment by howardjohn** [comment]
You can do that but both the node ports and exposed ports need to he defined in the Service. Until the traffic reaches envoy it goes through k8s service routing so there isn't really a way to get around that

**Comment by rforberger** [comment]
@howardjohn 
Well, my node ports and exposed ports are both defined in the istio-ingressgateway service. But when I am trying to connect to the Nodeport on the correct serving node, I get connection refused. I also have that message ``` rbac nil service instance``` in the pilot log.
