### ISSUE TITLE
mixer/test/client/fault_inject fails on mac

### ISSUE THREAD

**Issue by qiyongxiao** [istio/istio#15974]
Hi, I'm prepare to make build istio on my mbp. I meet some issue like below. With the message show, it stop to proced for many times.
```
pe:text/plain date:Thu, 01 Aug 2019 03:08:08 GMT server:envoy]
        response.size                 : 18
        response.time                 : 2019-08-01 03:08:09.06957 +0000 UTC
        response.total_size           : 110
        source.namespace              : XYZ11
        source.uid                    : POD11
        target.name                   : target-name
        target.namespace              : XYZ222
        target.uid                    : POD222
        target.user                   : target-user
FAIL
FAIL	istio.io/istio/mixer/test/client/fault_inject	3.626s
```
Does i how to build on my loongxin(mips64)?

**Comment by howardjohn** [comment]
> mips64

I don't think we support mips64, so there may be some modifications needed to get it working. recently someone added ARM support in #15668 so maybe that would be a good reference.

Anyhow it looks like you aren't actually just building, but also running a test? Does the build work? If its just test failing can you run with `go test -v` and provide the full output?

**Comment by qiyongxiao** [comment]
[save.txt](https://github.com/istio/istio/files/3459320/save.txt)
Hi, here is the make logs on darwin

**Comment by qiyongxiao** [comment]
> > mips64
> 
> I don't think we support mips64, so there may be some modifications needed to get it working. recently someone added ARM support in #15668 so maybe that would be a good reference.
> 
> Anyhow it looks like you aren't actually just building, but also running a test? Does the build work? If its just test failing can you run with `go test -v` and provide the full output?

Hi, here is the make logs on darwin. I only excute the make command. 
https://github.com/istio/istio/files/3459320/save.txt

**Comment by qiyongxiao** [comment]
> > mips64
> 
> I don't think we support mips64, so there may be some modifications needed to get it working. recently someone added ARM support in #15668 so maybe that would be a good reference.
> 
> Anyhow it looks like you aren't actually just building, but also running a test? Does the build work? If its just test failing can you run with `go test -v` and provide the full output?

While I build on macbook to execute，there are same error 
```
make
FAIL	istio.io/istio/mixer/test/client/fault_inject	3.620s
```

**Comment by kyessenov** [comment]
mixer/test/client tests are using native Envoy binary. We only provide a Linux build of istio/proxy, which means we only support these tests on Linux. Feel free to ignore the failures of these tests on non-Linux platforms. Sorry!
