### ISSUE TITLE
Istio - ingress not working after enabling SDS

### ISSUE THREAD

**Issue by srirajk** [istio/istio#15971]
I generated a cert from our internal CA team and then created a secret in the Istio-system ns.
Followed this document https://istio.io/docs/tasks/traffic-management/ingress/secure-ingress-sds/
I am not sure what else is missing but not able to make it work, tried redeploying  the ingress SDS pod after creating the secret and gateway.
Once I install SDS, I am not able to communicate using http as well.

Is there also a way that we can configure our cert for mutual TLS communication internally? 

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  annotations:
  creationTimestamp: "2019-07-31T20:37:21Z"
  generation: 1
  name: istio-xxx
  namespace: istio-xxx
  resourceVersion: "25249206"
  uid: feeb9147-b3d2-11e9-81cf-5a53bd44ba40
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - custom-domain.com
    port:
      name: https-catalog
      number: 443
      protocol: HTTPS
    tls:
      credentialName: istio-ingressgateway-certs
      mode: SIMPLE

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  annotations:
  creationTimestamp: "2019-07-31T20:37:21Z"
  generation: 1
  name: istio-xxx
  namespace: istio-xxx
spec:
  gateways:
  - istio-xxx
  hosts:
  - custom-domain.com
  http:
  - match:
    - uri:
        prefix: /istio-custom-pod
    rewrite:
      uri: ' '
    route:
    - destination:
        host: istio-custom-service
        port:
          number: 8080

**Comment by esnible** [comment]
Closing as duplicate of https://github.com/istio/istio/issues/15866

**Comment by Monkeyanator** [comment]
@esnible [#15866](https://github.com/istio/istio/issues/15866) ended up being a configuration issue on my end, so we could probably reopen this issue for discussion.

What's the specific error you're encountering @srirajk? Could you drop a `kubectl describe` for your `ingress-gateway` pod, and/or provide a dump of the `ingress-gateway`'s envoy config_dump if possible?

**Comment by howardjohn** [comment]
Please add the follow up info if you are still running into this
