### ISSUE TITLE
istioctl commands graduate out of experimental

### ISSUE THREAD

**Issue by linsun** [istio/istio#15973]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
As part of 1.3 release, we should consider certain commands to be graduated out of experimental.  I would recommend at least dashboard.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by esnible** [comment]
@linsun Are you asking for specific commands to be graduated?  Or for the community to define a process for how commands are graduated?

**Comment by linsun** [comment]
@esnible I opened this to track which istioctl cmds we can graduate in 1.3.  I was looking for dashboard cmd last night, I had thought it is already graduated but still in experimental.

**Comment by esnible** [comment]
Would it help all of the experimental commands `istioctl X` print `Use istioctl experimental X`?

I don't want them to do the work, but it might help users who forget which commands have graduated?

**Comment by linsun** [comment]
@esnible that is helpful, I had thought that is already done but it is not.

We still need to graduate good commands that has been around for 1-2 releases.

**Comment by esnible** [comment]
The commands we have are

  auth            Inspect and interact with authentication and authorization policies in the mesh
  convert-ingress Convert Ingress configuration into Istio VirtualService configuration
  dashboard       Access to Istio web UIs
  metrics         Prints the metrics for the specified workload(s) when running in Kubernetes.

`dashboard` was new in 1.2.
`auth` was reworked in 1.2.
`convert-ingress` and `metrics` have been in use for a while and have no complaints.  I rarely use them and don't know if they are worthy of graduation or merely obscure.

I like `dashboard` a lot, and recommend we graduate it even though it is new.  Which items do you recommend?

I will create tiny commands for the others directing users to the experimental subcommand.
