### ISSUE TITLE
ISTIO_META_ISTIO_PROXY_VERSION not match proxy version

### ISSUE THREAD

**Issue by linsun** [istio/istio#15985]
In this https://github.com/istio/istio/blob/release-1.2/pilot/docker/Dockerfile.proxyv2#L14 file, we have ```ENV ISTIO_META_ISTIO_PROXY_VERSION "1.1.3"``` but this is already 1.2.  Master also has similar prob.  We should not hardcode the version in this file as it can easily get outdated.

Also, what is the purpose of this ISTIO_META_ISTIO_PROXY_VERSION?  Seems not used now.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
consistent version or remove the no longer needed env var.

**Comment by howardjohn** [comment]
@linsun we have a PR to address this https://github.com/istio/istio/pull/15886

The variable is used, and is essential, we use it to make sure we don't send config to old envoys that don't support the config. If Envoy adds some `foo` field and we send it to old envoys they will reject the config.

**Comment by douglas-reid** [comment]
This was previously reported in https://github.com/istio/istio/issues/15229

**Comment by howardjohn** [comment]
Fixed by https://github.com/istio/istio/pull/15886
