### ISSUE TITLE
istio-sidecar-injector Config Map automatically reverts to `policy: enabled`

### ISSUE THREAD

**Issue by eyeezzi** [istio/istio#15991]
**Bug description**

When I edit the _istio-sidecar-injector_ config map to set `policy: disabled`, after a few minutes, the config map reverts back to `policy: enabled`. I have tried doing the edit on the GCP Console, and using `kubectl -n istio-system edit configmap istio-sidecar-injector`...same result.

**Some background on what I want to accomplish**

I only want a proxy injected into a pod iff `sidecar.istio.io/inject: "true"` annotation is set. So, to achieve this, I do the following:
1. Edit the _istio-sidecar-injector_ config map to set `policy: disabled`.
2. Add the `istio-injection: enabled` label to my namespace.

To my understanding, this is sufficient to prevent auto-sidecar-injection unless I explicitly set the annotation `sidecar.istio.io/inject: "true"` on the deployment. However, step 1 is the buggy part hindering my efforts.

**Affected product area (please put an X in all that apply)**

[x] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[x] Developer Infrastructure

**Expected behavior**
Edited _istio-sidecar-injector_ config map SHOULD NOT revert changes to the `policy` property.

**Steps to reproduce the bug**
1. Create a new GKE cluster with istio enabled. Check that it installs the same version of istio components like specified down below.
2. Edit the _istio-sidecar-injector_ config map to set `policy: disabled`.
3. After 2-3 minutes, it should revert back to `policy: enabled`.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

```
#istioctl version
client version: 1.2.2
citadel version: cba9054abf594acf792a985393ade7f2304a9e17
galley version: cba9054abf594acf792a985393ade7f2304a9e17
ingressgateway version: cba9054abf594acf792a985393ade7f2304a9e17
pilot version: cba9054abf594acf792a985393ade7f2304a9e17
policy version: cba9054abf594acf792a985393ade7f2304a9e17
sidecar-injector version: cba9054abf594acf792a985393ade7f2304a9e17
telemetry version: cba9054abf594acf792a985393ade7f2304a9e17

# kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-07T09:55:27Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-gke.8", GitCommit:"7d3d6f113e933ed1b44b78dff4baf649258415e5", GitTreeState:"clean", BuildDate:"2019-06-19T16:37:16Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}
```
**How was Istio installed?**

Istio was installed by enabling "istio" in the Google Kubernetes Engine console as part of the options during cluster creation. mTLS mode was set to PERMISSIVE if that matters.

**Environment where bug was observed (cloud vendor, OS, etc)**

Google Kubernetes Engine, Container-Optimized OS (cos).

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

[istio-dump.tar.gz](https://github.com/istio/istio/files/3457640/istio-dump.tar.gz)

**Comment by howardjohn** [comment]
Istio on GKE does not support the full customization of the Helm install. See https://cloud.google.com/istio/docs/istio-on-gke/overview#modifying_control_plane_settings

I think you only need `Add the istio-injection: enabled label to my namespace` in order to do what you want - based on https://cloud.google.com/istio/docs/istio-on-gke/installing#enabling_sidecar_injection

**Comment by eyeezzi** [comment]
@howardjohn Thanks for that resource, indeed the configuration reversal was due to GKE's weird behaviour. Installing Istio manually did not exhibit this reversal. Such important deviation from the norm should be made explicitly clear on the GCP Console when enabling Istio...but that is an issue for the GCP team.

I consider this issue resolved. Thanks.
