### ISSUE TITLE
Scraping all cluster pods using Prometheus + SDS 

### ISSUE THREAD

**Issue by jacobgo93** [istio/istio#15992]
**Bug description**
We're using prometheus 2.10.0 with this scrape config: https://raw.githubusercontent.com/istio/istio/release-1.2/install/kubernetes/helm/istio/charts/prometheus/templates/configmap.yaml. As you can see, one must supply the pods scrape job with TLS certs and keys paths. As we've activated SDS, we do not have these certs locally on the file system and we're relying on in-memory TLS infra. Seems like SDS activation is breaking official scrape config for Prometheus, since without these files, Prometheus is blocked from reaching the pods. 

**Affected product area (please put an X in all that apply)**

[X] Configuration Infrastructure
[X] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[X] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Succeed scraping all pods automatically, both securely (TLS) and insecurely. 

**Steps to reproduce the bug**
Supply Prometheus with official scrape config on a cluster running Istio + SDS. 

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Istio 1.2.2
Kubectl: Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-20T04:52:26Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-eks-d69f1b", GitCommit:"d69f1bf3669bf00b7f4a758e978e0e7a1e3a68f7", GitTreeState:"clean", BuildDate:"2019-02-28T20:26:10Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
Helm

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS EKS

**Comment by incfly** [comment]
Adding sidecar with a SDS config seems would work for this use case?

But I'm under the impression that we would like to make Istio leaner in general, not Istio's core component's responsibility to maintain the telemetry add-on. So I understand we need a way to get it work, but should it be in istio's repo?

Off the topic, I'm curious though, would you use this Prometheus instance only scrape Istio workloads(those with SDS and sidecar)? Above proposal won't work with workloads not adopting Istio, will that be a concern for you?

**Comment by jacob-koren-zooz** [comment]
It will be a concern because we are not injecting envoy in all namespaces. However, it will be much better position to be in.
