### ISSUE TITLE
`istioctl authn tls-check` consider actual Envoy configuration

### ISSUE THREAD

**Issue by incfly** [istio/istio#16008]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

I see many customers using `istioctl authn tls-check` to validate their Istio mTLS configuration. However, when debugging cni and sds can't be enabled together, https://github.com/istio/istio/issues/15701, I noticed that `istioctl authn tls-check` does not check the actual pod listener/cluster configuration, and report falsely the mTLS is enabled on server side.

** Expected Behavior **

Look at ConfigDump and then detect the case where Istio API is inconsistent of authn policy status. I know this is somewhat overlaps with `istioctl proxy-status`, not sure how to design the best CLI interface for our customer to troubleshoot.

@esnible 

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ X] Security
[ ] Test and Release
[X ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by esnible** [comment]
Can you supply brief instructions to deploy something that demonstrates incorrect output?

Currently the tool just asks Pilot's /debug/authenticationz for the information.  I am uncertain if a fix for Pilot or a fix for _istioctl_ is best.

@incfly I noticed that if there is no sidecar injected Pilot reports mTLS.  (Stale issue https://github.com/istio/istio/issues/11697 ).  I would like to see a solution that fixes that problem as well.

I have a new proposal, `istioctl inspect` ( https://github.com/istio/istio/issues/15526 ).  That tool checks BOTH Envoy configuration and Pilot's /debug/authenticationz but it currently only outputs the results from Pilot.  I would like to fix this problem for that tool as well.

**Comment by incfly** [comment]
Do you plan to make other existing kinda of inspectional utilities in `istioctl` under `istioctl inspect`? For example, authn/rbac/proxy-status those commands.

I'm worried if the commands proliferates without nice organization, operators can't easily remember each of them.

**Comment by incfly** [comment]
https://github.com/istio/istio/issues/15701 is an example of a buggy scenario. We definitely need to fix that one in pilot anyway independently. But it's sometimes misleading and easy to forget this potential inconsistency of what Pilot thinks vs what actual is.

**Comment by yangminzhu** [comment]
"istioctl experimental auth" is added to do the exact work you described here, it's still WIP for now and will be part of the upcoming reliable policy enforcement deaign, stay tuned :)

**Comment by irisdingbj** [comment]
`istioctl experimental auth check` is already been in release.
