### ISSUE TITLE
integration test (istioctl at least) running locally against Kube is failing

### ISSUE THREAD

**Issue by ericvn** [istio/istio#16004]
**Bug description**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ x ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Tests should pass

**Steps to reproduce the bug**

From _tests/integration_ run `go test ./istioctl/... --istio.test.env kube --log_output_level=tf:debug` and it fails 
```
2019-08-01T21:37:02.015845Z	error	tf	Test setup error: timeout while waiting (last error: 1 error occurred:
	* istio-system/istio-sidecar-injector-5786bff4b4-dxmv5: container not ready: 'sidecar-injector-webhook'
```

```
pod/istio-sidecar-injector-5786bff4b4-dxmv5    0/1     CrashLoopBackOff   6          4m58s
```

logs from pod end in:
```
2019-08-01T21:34:04.180290Z	error	Health check update of "/tmp/health" failed: open /tmp/health: no such file or directory
2019-08-01T21:34:06.180278Z	error	Health check update of "/tmp/health" failed: open /tmp/health: no such file or directory
2019-08-01T21:34:08.180281Z	error	Health check update of "/tmp/health" failed: open /tmp/health: no such file or directory
2019-08-01T21:34:10.180256Z	error	Health check update of "/tmp/health" failed: open /tmp/health: no such file or directory
```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

Currently latest from master built and pushed

```
istioctl version --remote                                                                                                                                                            
1.2.2
Error: unable to find any Istio pod in namespace istio-system
```
**How was Istio installed?**

via test

**Environment where bug was observed (cloud vendor, OS, etc)**

IKS and docker

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by ericvn** [comment]
As noted in another issue, this might be caused by https://github.com/istio/istio/pull/15948 (it updated the health path). My builds on Wednesday morning worked, today's are failing, and the mentioned PR went in during that time. I will try and revert that PR and see if the tests pass.

**Comment by ericvn** [comment]
I cleared all my local images using `docker system prune -a, built and pushed everything again, and the test appears to be passing. Will try again shortly with the bucket to see if that helps.

I suspect a base image was updated and the build did not pull a new one causing the failure. Deleting all the base images so the build had to pull the new base image seems to have worked.

**Comment by clyang82** [comment]
@ericvn Yes. the base image was updated so that you have to clean your local images to run the test again. You said that it is working now. Do I need to have a look at as well? Thanks.

**Comment by ericvn** [comment]
See my comment in #16001 about if there is a need to add an additional flag to make sure this doesn't happen, or maybe it's a seldom enough occurrence that a comment is discuss is sufficient?
