### ISSUE TITLE
Broken Build after go mod vendor

### ISSUE THREAD

**Issue by therealmitchconnors** [istio/istio#16006]
**Bug description**
https://github.com/istio/pkg/pull/42 and https://github.com/istio/istio/pull/15891 conflict, resulting in broken builds.

**Affected product area (please put an X in all that apply)**

[ x ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ x ] Test and Release
[ ] User Experience
[ x ] Developer Infrastructure

**Expected behavior**
build succeeds

**Steps to reproduce the bug**
```
go get istio.io/istio
cd $GOPATH/src/istio.io/istio
go mod tidy
go mod vendor
make
```

**Comment by geeknoid** [comment]
Fixed.
