### ISSUE TITLE
Inconsistency between operator CLI generated manifest and helm generated manifest

### ISSUE THREAD

**Issue by richardwxn** [istio/istio#16029]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
Run manifest diff command to compare manifests generated from helm vs operator CLI, there are some fields which are inconsistent between each other. Create this issue to track fixing them.
**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Manifest diff command should not output any difference between helm generated manifests vs operator cli generated manifests.

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by richardwxn** [comment]
Issues I have found so far include:
1. Some fields in global.yaml are missing in the profile values section: e.g. localitylbsetting, meshNetworks
2. Enum fields are not correct after translation, e.g. outboundTrafficPolicy would become int in translated value.yaml
3. Some translations are missing for iscp to value.yaml, e.g. HPASpec related setting
4. There is extra enabled field in the translated value.yaml global setting

**Comment by ostromart** [comment]
Could you please create individual issues with some additional info in them? We can split these up for people to tackle. I'll do the same for the stuff I discovered.

**Comment by ostromart** [comment]
Fixed in https://github.com/istio/operator/pull/173
