### ISSUE TITLE
Missing HPA spec for ingressgateway

### ISSUE THREAD

**Issue by ostromart** [istio/istio#16039]
run_manifest.sh for default profile shows the following resource missing:
HorizontalPodAutoscaler:istio-ingress:ingressgateway
(this may be due to bad namespace)

**Comment by morvencao** [comment]
If I understand it correctly, this will be fixed in https://github.com/istio/operator/pull/149

**Comment by ostromart** [comment]
Fixed in 149 and https://github.com/istio/operator/pull/173.
