### ISSUE TITLE
Retire as many CircleCi jobs as possible in the istio/proxy repo

### ISSUE THREAD

**Issue by geeknoid** [istio/istio#16030]
We're trying to eliminate our dependency on CircleCi. Any jobs  that  can be run on Prow should be run on Prow. Right now, the proxy repo has jobs that run in both environments, we don't need  that at  this point.

Thanks.

**Comment by rshriram** [comment]
I dont have experience in proxy [all the bazel stuff]. @yxue / @lizan / @mandarjog ?

**Comment by lizan** [comment]
Is there any gap between circle and prow? we're almost doing everything in prow now right? @PiotrSikora.

**Comment by PiotrSikora** [comment]
Prow was quite unreliable until 2-3 months ago, so we had to rely on CircleCI.

Nowadays, I think that we can retire everything other than macOS builds.

**Comment by geeknoid** [comment]
Correct. All other repos are on prow and its working well. The only case it doesn't handle properly is non-Linux builds.

**Comment by PiotrSikora** [comment]
Note that we can always migrate the macOS build from CircleCI to Azure Pipelines.

**Comment by PiotrSikora** [comment]
@geeknoid the only CircleCI job left is the macOS one. Let me know if we should migrate it to Azure Pipelines or if you prefer to leave it on CircleCI (in which case, this issue can be closed). Thanks!

**Comment by geeknoid** [comment]
Thanks!

I think the remaining jobs can stay on CircleCI. We've gotten usage so low now that we should be able to switch to a free plan once we're done building older releases.

**Comment by PiotrSikora** [comment]
@geeknoid AFAIK, free plan doesn't include macOS, so we won't be able to do that... hence my question about Azure Pipelines.

**Comment by geeknoid** [comment]
Oh, I didn't know mac wasn't available on the free plan. If switching to Azure pipelines is a 15 minute thing, than sure. If it's an involved thing, then it's not worth it. CircleCi will not cost us much anymore...
