### ISSUE TITLE
Enhance security integration tests

### ISSUE THREAD

**Issue by pitlv2109** [istio/istio#16055]
Currently we're not:
* testing authN and authZ with SDS
* testing authZ with and without authN
* making the tests flexible enough so we can test against any CA (e.g. Citadel, Vault, external CAs, etc.)

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[X] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by myidpt** [comment]
Pleas sync with Jimmy. I think this is in our Code Mauve plan.

**Comment by JimmyCYJ** [comment]
The first two items are more on security policy side. @yangminzhu 
About the third item, we already have integration tests using Citadel and Vault. To support other CA providers in the test framework, we need simple and robust configure option to select CA provider at Istio installation stage. That requires some efforts on installation and configuration change.

**Comment by yangminzhu** [comment]
Aren't the first two items already covered? I think we have e2e tests is setup to use SDS, @JimmyCYJ to confirm. I think we also already covers the AuthN + AuthZ flow, you could add tests for testing AuthZ only but I would put that as P2 for now.

**Comment by JimmyCYJ** [comment]
I just did a search, only sds_citadel_flow and sds_vault_flow are using workload SDS. The existing AuthZ and AuthN tests are using file mount secret. I think @pitlv2109 is asking AuthN and AuthZ with workload SDS enabled. We could find a way to make the existing test cases shared by file mount secret setup and workload SDS setup. 

https://github.com/istio/istio/search?q=cfg.Values%5B%22global.sds.enabled%22%5D+%3D+%22true%22&unscoped_q=cfg.Values%5B%22global.sds.enabled%22%5D+%3D+%22true%22

**Comment by pitlv2109** [comment]
Yea we don't test authZ and authN with SDS yet. That requires changing the prow job config in test-infra.
