### ISSUE TITLE
Fluentd handler start failed if the fluentd server connection cannot succeed at first try

### ISSUE THREAD

**Issue by winterTTr** [istio/istio#16051]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Based on the previews discussion [here](https://github.com/istio/istio/issues/6699), the fluentd client should use the async way for creation, so the when the fluentd service does not fully start up yet when the "fluentd" handle is created, it should get retry or re-connect later. But it seems not right now. 

**Steps to reproduce the bug**
Create 1 raw yaml file to create fluentd service and fluentd handle at the same time ( so fluentd service need time to start up, and fluentd handler create very soon, so cannot find a fluentd service to connect). 

Logs i found as below:
> 2019-08-05T12:20:41.347541Z     info    Setting up event handlers
2019-08-05T12:20:41.347588Z     info    Starting Secrets controller
2019-08-05T12:20:41.347629Z     info    Waiting for informer caches to sync
2019-08-05T12:20:44.347939Z     error   Unable to initialize adapter: snapshot='3', handler='geneva-fluentd-handler.istio-system', adapter='fluentd', err='adapter instantiation error: dial tcp 10.0.174.109:24224: i/o timeout'.
Please remove the handler or fix the configuration.
2019-08-05T12:20:44.348673Z     warn    Unable to find a handler for action. rule[action]='gateway-request-record.rule.istio-system[0]', handler='geneva-fluentd-handler.istio-system'
2019-08-05T12:20:44.350928Z     info    Cleaning up handler table, with config ID:2

But if i manually create the fluentd service and wait for it startup, and then create the handle, everything is correct. 

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
`kubectl version`
> Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:43:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

istioctl version --remote:
> client version: version.BuildInfo{Version:"1.1.7", GitRevision:"eec7a74473deee98cad0a996f41a32a47dd453c2", User:"root", Host:"341b3bf0-76ac-11e9-b644-0a580a2c0404", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.6-6-geec7a74"}
citadel version: version.BuildInfo{Version:"release-1.1-20190731-09-16", GitRevision:"473d9b376acf780fa1929eaf44dc65a3049d3765-dirty", User:"root", Host:"e13f257c-b373-11e9-a57f-baf6a3f505e7", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.11-2-g473d9b3"}
galley version: version.BuildInfo{Version:"release-1.1-20190804-09-15", GitRevision:"473d9b376acf780fa1929eaf44dc65a3049d3765-dirty", User:"root", Host:"83f4a229-b698-11e9-b677-42867a701db8", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.12"}
galley version: version.BuildInfo{Version:"release-1.1-20190705-09-16", GitRevision:"0cf9ca07c7425fd49db431c0644b4e6b2fb9e63b-dirty", User:"root", Host:"95431e6a-9f05-11e9-bbbf-c6c1e2f0cc80", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.11"}
ingressgateway version: version.BuildInfo{Version:"release-1.1-20190728-09-15", GitRevision:"34d85f53b1c03414d9cff73958fd4a7185308a06", User:"root", Host:"512f9c4a-b118-11e9-a818-66f2038fb1cc", GolangVersion:"go1.10.4", DockerHub:"gcr.io/istio-release", BuildStatus:"Clean", GitTag:"1.1.11-1-g34d85f5"}
ingressgateway version: version.BuildInfo{Version:"release-1.1-20190705-09-16", GitRevision:"0cf9ca07c7425fd49db431c0644b4e6b2fb9e63b", User:"root", Host:"95431e6a-9f05-11e9-bbbf-c6c1e2f0cc80", GolangVersion:"go1.10.4", DockerHub:"gcr.io/istio-release", BuildStatus:"Clean", GitTag:"1.1.11"}
pilot version: version.BuildInfo{Version:"release-1.1-20190705-09-16", GitRevision:"0cf9ca07c7425fd49db431c0644b4e6b2fb9e63b-dirty", User:"root", Host:"95431e6a-9f05-11e9-bbbf-c6c1e2f0cc80", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.11"}
pilot version: version.BuildInfo{Version:"release-1.1-20190723-09-16", GitRevision:"34d85f53b1c03414d9cff73958fd4a7185308a06-dirty", User:"root", Host:"937b1bff-ad2a-11e9-a339-62631f7eb25d", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.11-1-g34d85f5"}
policy version: version.BuildInfo{Version:"release-1.1-20190705-09-16", GitRevision:"0cf9ca07c7425fd49db431c0644b4e6b2fb9e63b-dirty", User:"root", Host:"95431e6a-9f05-11e9-bbbf-c6c1e2f0cc80", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.11"}
policy version: version.BuildInfo{Version:"release-1.1-20190804-09-15", GitRevision:"473d9b376acf780fa1929eaf44dc65a3049d3765-dirty", User:"root", Host:"83f4a229-b698-11e9-b677-42867a701db8", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.12"}
sidecar-injector version: version.BuildInfo{Version:"release-1.1-20190730-09-16", GitRevision:"473d9b376acf780fa1929eaf44dc65a3049d3765-dirty", User:"root", Host:"c55494f2-b2aa-11e9-9e19-160b02173aa1", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.11-2-g473d9b3"}
telemetry version: version.BuildInfo{Version:"release-1.1-20190705-09-16", GitRevision:"0cf9ca07c7425fd49db431c0644b4e6b2fb9e63b-dirty", User:"root", Host:"95431e6a-9f05-11e9-bbbf-c6c1e2f0cc80", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.11"}
telemetry version: version.BuildInfo{Version:"release-1.1-20190804-09-15", GitRevision:"473d9b376acf780fa1929eaf44dc65a3049d3765-dirty", User:"root", Host:"83f4a229-b698-11e9-b677-42867a701db8", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.12"}

**How was Istio installed?**
helm install

**Environment where bug was observed (cloud vendor, OS, etc)**
Ubuntu, Azure VM.

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by winterTTr** [comment]
BTW, I just found that, the istio master branch don't use the fluentd logger package latest version, which support async better. 

istio master branch:
https://github.com/istio/istio/blob/master/vendor/github.com/fluent/fluent-logger-golang/fluent/fluent.go
```
	if config.MaxRetry == 0 {
		config.MaxRetry = defaultMaxRetry
	}
	if config.AsyncConnect {
		f = &Fluent{Config: config, reconnecting: true}
		go f.reconnect()
	} else {
		f = &Fluent{Config: config, reconnecting: false}
		err = f.connect()
	}
	return
}
```

 
fluentd go package:
https://github.com/fluent/fluent-logger-golang/blob/master/fluent/fluent.go
```
	if config.AsyncConnect {
		fmt.Fprintf(os.Stderr, "fluent#New: AsyncConnect is now deprecated, please use Async instead")
		config.Async = config.Async || config.AsyncConnect
	}
	if config.Async {
		f = &Fluent{
			Config:  config,
			pending: make(chan *msgToSend, config.BufferLimit),
		}
		f.wg.Add(1)
		go f.run()
	} else {
		f = &Fluent{Config: config}
		err = f.connect()
	}
	return
}
```
Shall we upgrade to use the `async` way by default?
I did go through the code, but i don't find where we initialize the fluentd config in istio code.

**Comment by douglas-reid** [comment]
Upgrading is fine by me.

**Comment by winterTTr** [comment]
I do think we need this improvement, so vote it to avoid disabled by bot.
