### ISSUE TITLE
Allow non-root deployment

### ISSUE THREAD

**Issue by srettenmeier** [istio/istio#16054]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

Currently we're trying to install Istio in a managed on premises Kubernetes cluster. Therein it's not allowed to run containers as root user. Thus several Istio components cannot be deployed correctly.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Being able to install Istio in an environment where containers cannot run as root user

**Steps to reproduce the bug**

Apply Helm chart in an environment where containers cannot run as root user

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

Istio v1.2.3

**How was Istio installed?**

Helm chart

**Environment where bug was observed (cloud vendor, OS, etc)**

Managed on premises Kubernetes cluster (Kubernetes 1.14 on CoreOS)

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
Thanks for the issue. This is being actively worked on right now (multiple PRs merged in last week) and should be ready very soon. I am going to close this as it is being tracked in https://github.com/istio/istio/issues/10768
