### ISSUE TITLE
istio-init doesn't remove CRDs on uninstall

### ISSUE THREAD

**Issue by ddrechse** [istio/istio#16064]
Using Istio 1.1.3

$ **helm install install/kubernetes/helm/istio-init --name istio-init --namespace istio-system**
NAME:   istio-init
LAST DEPLOYED: Mon Aug  5 17:19:13 2019
NAMESPACE: istio-system
STATUS: DEPLOYED

RESOURCES:
==> v1/ConfigMap
NAME          DATA  AGE
istio-crd-10  1     2s
istio-crd-11  1     2s

==> v1/ServiceAccount
NAME                        SECRETS  AGE
istio-init-service-account  1        1s

==> v1/ClusterRole
NAME                     AGE
istio-init-istio-system  1s

==> v1/ClusterRoleBinding
NAME                                        AGE
istio-init-admin-role-binding-istio-system  1s

==> v1/Job
NAME               DESIRED  SUCCESSFUL  AGE
istio-init-crd-10  1        0           1s
istio-init-crd-11  1        0           1s

==> v1/Pod(related)
NAME                     READY  STATUS             RESTARTS  AGE
istio-init-crd-10-wb66p  0/1    ContainerCreating  0         1s
istio-init-crd-11-tphz4  0/1    ContainerCreating  0         1s

$ **k get po --all-namespaces**
NAMESPACE      NAME                                    READY   STATUS      RESTARTS   AGE
istio-system   istio-init-crd-10-wb66p                 0/1     Completed   0          13s
istio-system   istio-init-crd-11-tphz4                 0/1     Completed   0          13s
kube-system    kube-dns-6fb9dcb8bf-92q2z               3/3     Running     0          12d
kube-system    kube-dns-6fb9dcb8bf-ktfhr               3/3     Running     0          12d
kube-system    kube-dns-6fb9dcb8bf-tnc52               3/3     Running     0          12d
kube-system    kube-dns-autoscaler-656d6f6b8f-gqh6q    1/1     Running     0          12d
kube-system    kube-flannel-ds-gss9l                   1/1     Running     1          12d
kube-system    kube-flannel-ds-p9mg4                   1/1     Running     1          12d
kube-system    kube-flannel-ds-rlr98                   1/1     Running     1          12d
kube-system    kube-proxy-4xkzp                        1/1     Running     0          46h
kube-system    kube-proxy-m4t87                        1/1     Running     0          12d
kube-system    kube-proxy-mmbjd                        1/1     Running     0          12d
kube-system    kubernetes-dashboard-85b859ccbb-b9hqp   1/1     Running     0          12d
kube-system    proxymux-client-10.0.10.2               1/1     Running     0          12d
kube-system    proxymux-client-10.0.11.2               1/1     Running     0          12d
kube-system    proxymux-client-10.0.12.2               1/1     Running     0          12d
kube-system    tiller-deploy-d9dfc7699-gqmts           1/1     Running     0          12d

$ **kubectl get crds | grep 'istio.io\|certmanager.k8s.io' | wc -l**
      53
$ **helm delete --purge istio-init**
release "istio-init" deleted
$ **kubectl get crds | grep 'istio.io\|certmanager.k8s.io' | wc -l**
      53

It seems to have cleaned up after itself except for CRDs
$ **k get po --all-namespaces**
NAMESPACE     NAME                                    READY   STATUS    RESTARTS   AGE
kube-system   kube-dns-6fb9dcb8bf-92q2z               3/3     Running   0          12d
kube-system   kube-dns-6fb9dcb8bf-ktfhr               3/3     Running   0          12d
kube-system   kube-dns-6fb9dcb8bf-tnc52               3/3     Running   0          12d
kube-system   kube-dns-autoscaler-656d6f6b8f-gqh6q    1/1     Running   0          12d
kube-system   kube-flannel-ds-gss9l                   1/1     Running   1          12d
kube-system   kube-flannel-ds-p9mg4                   1/1     Running   1          12d
kube-system   kube-flannel-ds-rlr98                   1/1     Running   1          12d
kube-system   kube-proxy-4xkzp                        1/1     Running   0          47h
kube-system   kube-proxy-m4t87                        1/1     Running   0          12d
kube-system   kube-proxy-mmbjd                        1/1     Running   0          12d
kube-system   kubernetes-dashboard-85b859ccbb-b9hqp   1/1     Running   0          12d
kube-system   proxymux-client-10.0.10.2               1/1     Running   0          12d
kube-system   proxymux-client-10.0.11.2               1/1     Running   0          12d
kube-system   proxymux-client-10.0.12.2               1/1     Running   0          12d
kube-system   tiller-deploy-d9dfc7699-gqmts           1

**Comment by howardjohn** [comment]
This is intentional, otherwise all resources you defined would be deleted when you do this could have very negative impact .

If you want to remove the CRD I believe the uninstall docs explain how

**Comment by ddrechse** [comment]
Hey, Tnx for the update. RTFM

Follow up question

After uninstalling istio and istio-init, i noticed the CRDs still there which has been covered

I then reinstalled istio w/o installing istio-init first
and istio seemed to come up fine

Is istio-init always required prior to installing istio?  Or is it a one time thing?

Thnx

**Comment by howardjohn** [comment]
istio-init just installs the CRDs, so assuming you are installing the same version and same settings, then the CRDs will remain the same so you don't need to install it.

That being said, you may want to as we may add other things to istio-init

**Comment by ddrechse** [comment]
Thanks
