### ISSUE TITLE
The request of the application container was rejected by sidecar when sidecar was not ready

### ISSUE THREAD

**Issue by zqzzq** [istio/istio#16067]
**Bug description**
My app needs to make a request to another service when it starts, then due to iptables rule the request is redirected to sidecar, but at this time sidecar is not ready yet, so the request is rejected. Now I have to add a 30 second delay in my code to make this request. Is there a better way to solve this problem? Very thanks!
**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
The app can start normally

**Comment by howardjohn** [comment]
There is a ton of discussion around this subject at https://github.com/istio/istio/issues/11366. We are hoping to have some solution similar to the one in that issue in alpha in the next release or two. Thanks!
