### ISSUE TITLE
Istioctl ps issue

### ISSUE THREAD

**Issue by clyang82** [istio/istio#16071]
**Bug description**
`istioctl ps` get the data from pilot debug interface `debug/syncz`.
### before 1.1.0, the result is timestamp.
```
"cluster_sent": "2019-08-06 04:45:07.5415578 +0000 UTC m=+164.525105293",
"cluster_acked": "2019-08-06 04:45:07.5415578 +0000 UTC m=+164.525105293",
```
### after 1.1.0, the return value is uuid
```
"cluster_sent": "5968cebf-fac3-4b66-a7f8-a33d714f99a2", "cluster_acked": "5968cebf-fac3-4b66-a7f8-a33d714f99a2",
```
There should has code error to parse the uuid to time
https://github.com/istio/istio/blob/1c5a959476abe1f5379fee49188f004b4aced931/istioctl/pkg/writer/pilot/status.go#L107:L120.

That is why we met the `STALE (Never Acknowledged)` only if the send is not equal to acked.

/cc @esnible @linsun @irisdingbj 

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by clyang82** [comment]
Can we return the timestamp from pilot? if cannot, we may consider to just return `STALE` if `acked` is not equal to `send`

**Comment by esnible** [comment]
In addition to fixing this issue we need an integration test for `istioctl proxy-status` to prevent this from happening again.  I believe we currently have only a Go/unit test.

**Comment by AsCat** [comment]
I just create a [pr](https://github.com/istio/istio/pull/16446) which may this problem.
The PR also include the unit test fix.

**Comment by clyang82** [comment]
@AsCat Thanks for your PR.

**Comment by AsCat** [comment]
@clyang82 It's my pleasure : )

**Comment by linsun** [comment]
@clyang82 - can you check if this issue can be closed?

**Comment by clyang82** [comment]
@linsun I just add label to merge the fix to release branch. I will test it in release branch. Thanks.
