### ISSUE TITLE
gRPC config stream closed: 14, upstream connect error or disconnect/reset before headers. reset reason: connection failure

### ISSUE THREAD

**Issue by mar1n3r0** [istio/istio#16074]
**Bug description**

Follow up on a closed issue in an unknown state:
https://github.com/istio/istio/issues/13205

"This is fixed in envoyproxy/envoy#7505. I think this issue can be closed once those changes are pulled into Istio."

Didn't see it in the changelog of latest version 1.2.3. Updated, the issue still persists.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Reaching the public IP.
**Steps to reproduce the bug**
Try accesing the istio-ingressgateway public IP
**Version (include the output of `istioctl version --remote` and `kubectl version`)**
istioctl version --remote: 1.2.3
kuectl version: v1.13.7-gke.8
**How was Istio installed?**
via helmRelease part of this setup: https://github.com/stefanprodan/gitops-istio
**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

**Comment by mar1n3r0** [comment]
Solved by aligning the ports between the deployment and the canary which was creating the virtual service with the wrong ports.

**Comment by yudaprama** [comment]
@mar1n3r0 I guess I get similar issue as you. Can you get more detail which port wrong port in Deployment and VirtualService?

**Comment by mar1n3r0** [comment]
@yudaprama In this particular case it was here:

https://github.com/stefanprodan/gitops-istio/blob/master/prod/backend/canary.yaml

I am using this strategy for production deployment. The original flow is based on a go service exposed on port 9898 so before I changed all ports to my default 80 it was throwing the above mentioned error. 

The error is very generic so you will need to post more details in order to figure out what exactly went wrong.
