### ISSUE TITLE
Metrics for Istio Sidecar Injector

### ISSUE THREAD

**Issue by ramaraochavali** [istio/istio#16073]
**Describe the feature request**

Currently Istio Sidecar Injector does not record and push any metrics. When Istio is deployed in large we want to know Injection failures so that we can monitor and create alerts. The feature request is to support the following metrics from Istio Side car injector to start with and later can be expanded
- istio_sideecar_injections_total
- istio_sidecar_injections_success
- istio_sidecar_injections_failures

**Describe alternatives you've considered**
None
**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**
N/A

**Comment by howardjohn** [comment]
Seems useful, but in most cases I've seen injection failing it's because kube cannot talk to the injector, which the injector could not report. Maybe kubernetes exposed a metric here 

Do you see injector failing often when it is actually reached?

**Comment by ramaraochavali** [comment]
Yes for the case where Kube can not talk to Injector Kube api provides metrics for the rest calls it makes including latencies. This is for the case injector failing for some bug/reason similar to https://github.com/istio/istio/issues/16072.

**Comment by howardjohn** [comment]
:+1: thanks, seems like something useful
