### ISSUE TITLE
redis with sentinel misreporting as 127.0.0.1

### ISSUE THREAD

**Issue by ceastman-ibm** [istio/istio#16078]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
I have a three pod installation of redis, each pod is running redis and sentinel. The master redis node is showing 2 connected slaves but their ip addresses are reported as 127.0.0.1 instead of the pods actual ip address.

# Replication
role:master
connected_slaves:2
slave0:ip=127.0.0.1,port=6379,state=online,offset=10489650,lag=0
slave1:ip=127.0.0.1,port=6379,state=online,offset=10489650,lag=1

I am assuming its an issue with the istio-proxy, here is a snippet of the logs:
[redis-0 istio-proxy] [2019-08-06T14:40:46.091Z] "- - -" 0 - "-" 321 42 1936 - "-" "-" "-" "-" "127.0.0.1:26379" inbound|26379|redis-sentinel|redis.redis.svc.cluster.local 127.0.0.1:49242 172.30.41.196:26379 172.30.18.175:34824 - 
[redis-0 istio-proxy] [2019-08-06T14:40:48.068Z] "- - -" 0 - "-" 229 23 2032 - "-" "-" "-" "-" "127.0.0.1:26379" inbound|26379|redis-sentinel|redis.redis.svc.cluster.local 127.0.0.1:50960 172.30.41.196:26379 172.30.194.250:48478 - 

kubectl get pods -o wide 
NAME      READY   STATUS    RESTARTS   AGE   IP               NODE
redis-0   2/2     Running   2          63m   172.30.41.196    10.177.187.44
redis-1   2/2     Running   2          63m   172.30.18.175    10.177.187.75
redis-2   2/2     Running   2          62m   172.30.194.250   10.177.187.4

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
The expected behaviour is that the redis master knows the ip addresses of its connected slaves.

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
managed istio version 1.2.2

kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-19T22:13:37Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.8+IKS", GitCommit:"fe3e332c2b0f47d4572433c3b0a1687a27fb88c6", GitTreeState:"clean", BuildDate:"2019-07-11T13:45:03Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
IBM - managed istio 

**Environment where bug was observed (cloud vendor, OS, etc)**
IBM 
Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by ceastman-ibm** [comment]
I also found this in the redis-0 logs:
[redis-0 istio-proxy] [2019-08-06 16:34:27.480][25][warning][config] [external/envoy/source/common/config/grpc_mux_subscription_impl.cc:73] gRPC config for type.googleapis.com/envoy.api.v2.ClusterLoadAssignment rejected: malformed IP address: redis.redis.svc.cluster.local. Consider setting resolver_name or setting cluster type to 'STRICT_DNS' or 'LOGICAL_DNS'

**Comment by ceastman-ibm** [comment]
redis service description:

Carls-MBP:istio carleastman$ kubectl describe svc redis
Name:              redis
Namespace:         redis
Labels:            app=redis
                   heritage=tiller
                   release=ace_redis_console_4
Annotations:       kubectl.kubernetes.io/last-applied-configuration:
                     {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"redis","heritage":"tiller","release":"ace_redis_console_...
Selector:          app=redis
Type:              ClusterIP
IP:                172.21.139.201
Port:              redis-server  6379/TCP
TargetPort:        6379/TCP
Endpoints:         172.30.153.136:6379,172.30.41.223:6379,172.30.88.84:6379
Port:              redis-sentinel  26379/TCP
TargetPort:        26379/TCP
Endpoints:         172.30.153.136:26379,172.30.41.223:26379,172.30.88.84:26379
Session Affinity:  None
Events:            <none>

**Comment by esnible** [comment]
I am not a Redis guy.  How do I ask Redis for a list of slaves?

I attempted to reproduce the problem.  I installed from the Helm chart.  The master worked fine, the slaves did not see the value for `mycounter`.  I used the instructions from the Helm install:

```
helm install stable/redis
export REDIS_PASSWORD=$(kubectl get secret --namespace default existing-waterbuffalo-redis -o jsonpath="{.data.redis-password}" | base64 --decode)
kubectl run --namespace default existing-waterbuffalo-redis-client --rm --tty -i --restart='Never' \
    --env REDIS_PASSWORD=$REDIS_PASSWORD \
   --image docker.io/bitnami/redis:4.0.12 -- bash
redis-cli -h existing-waterbuffalo-redis-master -a $REDIS_PASSWORD
incr mycounter
incr mycounter
control-D
redis-cli -h existing-waterbuffalo-redis-master -a $REDIS_PASSWORD
incr mycounter
redis-cli -h existing-waterbuffalo-redis-slave -a $REDIS_PASSWORD
get mycounter
(nil)
```

The final `(nil)` demonstrates the problem.  The slaves don't have the data.  If you wish to repeat what I did note that Helm will give you a different name, not `existing-waterbuffalo`.

I noticed that the client sidecar was not READY.  `kubectl get pods` showed the containers in `1/2` state.  Istio's pod requirements insists that ever pod, even clients, have a Service.  I created the following service:

```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis-client
spec:
  ports:
    - port: 8080
      name: http-dummy
  selector:
    run: existing-waterbuffalo-redis-client
EOF
```

I re-ran the test and again saw the master's value for `mycounter` was persistent, but the slaves never had a value.

**Comment by ceastman-ibm** [comment]
@esnible i log into one of the redis pods and run:
redis-cli info

**Comment by esnible** [comment]
For me, `/opt/bitnami/redis/bin/redis-cli -a $REDIS_PASSWORD info | grep slaves` gives `connected_slaves:0`.  You are getting further than me.

For me, `kubectl logs <slave-pod> -c existing-waterbuffalo-redis` reports

```
1:S 06 Aug 17:27:06.420 # Error condition on socket for SYNC: Connection reset by peer
1:S 06 Aug 17:27:07.424 * Connecting to MASTER existing-waterbuffalo-redis-master:6379
```

**Comment by emrahcetiner** [comment]
I have the same issue: [https://github.com/helm/charts/issues/16622](url)

> I did a few tests. This issue was caused by istio-sidecar injection.
> 
> When i disable injection, slave's IP defined correct on master. 😅
> 
> ```
> master:
>   podAnnotations:
>     sidecar.istio.io/inject: "false"
> ```
> 
> i think, istio-proxy container in pod is blocking IP resolution.

so, how can i fix this without injection disabling?

**Comment by mbanikazemi** [comment]
I solved the problem by explicitly specifying  "replica-announce-ip" config parameter and setting it to the pod IP address for slaves.

More specifically, I added the following to my Statefulset env to use the pod IP address :

        ```- name: "POD_IP"
          valueFrom:
            fieldRef:
              fieldPath: status.podIP```

and under the “command” subsection of the slave Statefulset I added:

          ```echo "" >> /opt/bitnami/redis/etc/replica.conf
          echo "replica-announce-ip $POD_IP" >> /opt/bitnami/redis/etc/replica.conf```

to add this config parameter to the config file my Redis uses.

and then I see the correct addresses:

```
connected_slaves:2
slave0:ip=172.30.229.191,port=6379,state=online,offset=56,lag=1
slave1:ip=172.30.144.169,port=6379,state=online,offset=56,lag=0```

@emrahcetiner  Please let me know if this solves your problem.
