### ISSUE TITLE
Add CRDs to istio helm chart instead of istio-init

### ISSUE THREAD

**Issue by woodcockjosh** [istio/istio#16085]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
I believe the CRDs were initially moved to istio-init because of the helm CRD hook bug. As it is now fixed we should move the CRD's back into the templates so that the chart can actually be used as a dependency without additional set up steps. 

**Describe alternatives you've considered**
Install CRD's separately before running helm installation

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Additional context**
https://github.com/helm/helm/releases/tag/v2.14.3

**Comment by Aaron-ML** [comment]
I agree with @woodcockjosh, trying to automate the installation with istio-init and istio causes problems due to the helm charts being exclusive from each other. The CRD's don't populate immediately and it just asks for more problems when you run them back to back. 

I see no reason to separate them as the bug is now fixed. This would reduce toil and allow operators to wrap their heads around what matters versus added baggage.

**Comment by woodcockjosh** [comment]
They're probably just going to sit on this until helm 3 so I wouldn't hold your breath

**Comment by sdake** [comment]
Whether or not the "bug" is fixed is a subject of debate. The reality that it took the helm community 4 releases to fix this critical issue (if it is indeed fixed, which I doubt), is completely unacceptable, given the amount of complaining that took place on the issue trackers.  This CRD issue nearly killed Istio's entire deployment technology.

We are not making further investments in any helm related technology for Istio, *ever*. As such I am closing this bug.  Our future solution for deployment is focused around the operator here: https://github.com/istio/operator.

**Comment by woodcockjosh** [comment]
@sdake is right that helm is incredibly unstable and response to critical issuesis below average, however until a better alternative emerges we are all stuck with helm like it or not. Istio init is not better than including crds in helm chart.
