### ISSUE TITLE
istio/installer demo broken by rootless, sidecar injector crash loop

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#16086]
Sidecar injector fails with error: ` Health check update of "/tmp/health" failed: open /tmp/health: no such file or directory`

Not sure if this is fixed by @costinm recent changes or not?

**Comment by costinm** [comment]
It seems to be passing in installer, will look into it.

**Comment by howardjohn** [comment]
It breaks for me when doing just `kubectl apply -k github.com/istio/installer/test/demo`

**Comment by howardjohn** [comment]
fixed via revert
