### ISSUE TITLE
Enable wait time between retry attempts in Virtual Service configuration

### ISSUE THREAD

**Issue by safvankothawala** [istio/istio#16098]
**Enable provision of wait time between retry attempts in Virtual Service Configuration**

**Describe alternatives you've considered**
The workaround is to increase the retry attempts.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**
Consider a scenario where the destination server is not reachable due to some temporary network problem or the destination gateway is restarting.
During this time, if my application sends a request to the destination server, I will get an HTTP error.
If I wait for some very small time (few ms) and then retry again then my request may be processed successfully.
Hence, I need an additional field in Istio's VirtualService defining the wait time between different retry attempts.

**Comment by howardjohn** [comment]
This is handled automatically. See https://www.envoyproxy.io/docs/envoy/v1.7.0/configuration/http_filters/router_filter#x-envoy-max-retries
