### ISSUE TITLE
AWS ELB  - Istio IngressGateway TLS SDS - Connection Issue

### ISSUE THREAD

**Issue by vsquare1** [istio/istio#16109]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

I have installed Istio 1.2.2 on AWS EKS and enabled TLS on Istio IngressGateway with SDS.

Created Secret with the my company signed certificate.

Gateway info as follow:
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: abc-gw
  namespace: my-ns
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: "abc-credential"
    hosts:
    - "myhost"

Istio ingress gateway is annotated with the following and successfully created
service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0

Created Route 53 record set "myhost" pointing to the ELB created from the above.

I have tried curl on my Mac terminal and it worked fine with "https"

But when we tried from the same endpoint on F5, it failed.
Ran the following openssl command:
echo | openssl s_client -showcerts -connect myhost:443 2>/dev/null

CONNECTED(00000006)

no peer certificate available

No client certificate CA names sent

SSL handshake has read 0 bytes and written 0 bytes

New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    Start Time: 1565206805
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)

Same output when I ran from the Mac as well.

The ELB created has the following:

Load Balancer Protocol | Load Balancer Port | Instance Protocol | Instance Port | Cipher | SSL Certificate
TCP | 443 | TCP | 31390 | N/A | N/A

To rule out the certificate issue, I configured ELB to terminate the same cert using AWS Certificate Manager on the ELB and point to Istio IngressGateway with http then it worked fine.
Checked the following openssl command and it is working fine with correct data.
echo | openssl s_client -showcerts -connect myhost:443 2>/dev/null

 But Terminating TLS at ELB and pointing ELB to Istio IngressGateway on https (port 31390) then fails with HTTP/1.1 408 REQUEST_TIMEOUT

Any idea why the TLS connectivity and unable to recognize the cert on the Istio IngressGateway ?

 Appreciated your help!

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
The https connectivity should work

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.2.2
**How was Istio installed?**
Helm Template

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS EKS

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by vsquare1** [comment]
The issue was due to F5 older version SSL protocol version. It is SSL 3.0 and failed. To fix the issue , I had terminated the TLS at ELB (By selecting the Protocol-SSLv3) and reestablish the TLS on port 31390 to Istio Ingress Gateway.

Is there a way to change the Istio Ingress Gateway to support the SSLv3?

Thanks

**Comment by JimmyCYJ** [comment]
For the SSL 3.0 support, could you file a issue at https://github.com/envoyproxy/envoy? The gateway agent extracts key/cert from Kubernetes and pushes to the ingress gateway (Envoy) regardless of SSL version.
