### ISSUE TITLE
Kiali can't get meshpolicies.authentication.istio.io

### ISSUE THREAD

**Issue by stevehipwell** [istio/istio#16103]
**Bug description**
When installing and accessing Kiali via a Helm deploy I'm getting the following error message.
![image](https://user-images.githubusercontent.com/6552347/62632317-332f1780-b92a-11e9-87d3-fa08c2de49f8.png)

This can also be seen in the Kiali logs.
>I0807 14:38:42.179426       1 kiali.go:67] Kiali: Version: v0.20.0, Commit: 140969bc2ef1a77ca7387b47f8b23dcbd4818bd0
I0807 14:38:42.182276       1 kiali.go:68] DEBUG: Kiali: Command line: [/opt/kiali/kiali -config /kiali-configuration/config.yaml -v 4]
I0807 14:38:42.183506       1 config.go:461] DEBUG: Reading YAML config from [/kiali-configuration/config.yaml]
I0807 14:38:42.187114       1 kiali.go:203] Using authentication strategy [login]
I0807 14:38:42.189746       1 kiali.go:88] Kiali: Console version: 0.20.0
E0807 14:38:42.196942       1 kiali.go:106] Jaeger is not available : Get http:///api/services: http: no Host in request URL
I0807 14:38:42.198614       1 server.go:49] Server endpoint will start at [:20001/]
I0807 14:38:42.198649       1 server.go:50] Server endpoint will serve static content from [/opt/kiali/console]
I0807 14:38:42.198666       1 metrics_server.go:18] Starting Metrics Server on [:9090]
I0807 14:38:42.200218       1 kiali.go:135] Secret is now available.
I0807 14:40:08.297545       1 client.go:180] DEBUG: Rest perf config QPS: 175.000000 Burst: 200
I0807 14:40:08.298061       1 client.go:180] DEBUG: Rest perf config QPS: 175.000000 Burst: 200
I0807 14:40:08.404006       1 versions.go:140] DEBUG: Detected Istio version [root@ced2af60-b3ec-11e9-b2dc-4e6c8cb30ee5-docker.io/istio-1.2.3-c562694ea6e554c2b60d12c9876d2641cfdd917d-dirty-Modified]
I0807 14:40:08.407193       1 discover.go:107] DEBUG: Kiali is looking for Tracing/Jaeger service ...
I0807 14:40:08.407343       1 discover.go:117] DEBUG: Kiali didn't found Tracing/Jaerger
W0807 14:40:08.601051       1 istio_rules_service.go:114] Querying template got an error: istio-system doesn't return a logentries list
W0807 14:40:08.606517       1 istio_rules_service.go:114] Querying template got an error: istio-system doesn't return a listentries list
W0807 14:40:08.612860       1 istio_rules_service.go:114] Querying adapter got an error: istio-system doesn't return a opas list
W0807 14:40:08.615699       1 istio_rules_service.go:114] Querying adapter got an error: istio-system doesn't return a fluentds list
W0807 14:40:08.626997       1 istio_rules_service.go:114] Querying adapter got an error: istio-system doesn't return a kubernetesenvs list
W0807 14:40:08.628208       1 istio_rules_service.go:114] Querying template got an error: istio-system doesn't return a edges list
W0807 14:40:08.632096       1 istio_rules_service.go:114] Querying adapter got an error: istio-system doesn't return a deniers list
W0807 14:40:08.632283       1 istio_rules_service.go:114] Querying template got an error: istio-system doesn't return a metrics list
W0807 14:40:08.632390       1 istio_rules_service.go:114] Querying template got an error: istio-system doesn't return a quotas list
W0807 14:40:08.632671       1 istio_rules_service.go:114] Querying template got an error: istio-system doesn't return a authorizations list
W0807 14:40:08.632784       1 istio_rules_service.go:114] Querying adapter got an error: istio-system doesn't return a stdios list
W0807 14:40:08.632900       1 istio_rules_service.go:114] Querying adapter got an error: istio-system doesn't return a listcheckers list
W0807 14:40:08.633318       1 istio_rules_service.go:114] Querying adapter got an error: istio-system doesn't return a statsds list
W0807 14:40:08.633444       1 istio_rules_service.go:114] Querying adapter got an error: istio-system doesn't return a cloudwatches list
W0807 14:40:08.633565       1 istio_rules_service.go:114] Querying adapter got an error: istio-system doesn't return a signalfxs list
W0807 14:40:08.633650       1 istio_rules_service.go:114] Querying adapter got an error: istio-system doesn't return a rbacs list
W0807 14:40:08.633751       1 istio_rules_service.go:114] Querying adapter got an error: istio-system doesn't return a redisquotas list
W0807 14:40:08.633853       1 istio_rules_service.go:114] Querying adapter got an error: istio-system doesn't return a stackdrivers list
W0807 14:40:08.633882       1 istio_rules_service.go:114] Querying template got an error: istio-system doesn't return a checknothings list
W0807 14:40:08.634007       1 istio_rules_service.go:114] Querying template got an error: istio-system doesn't return a apikeys list
W0807 14:40:08.634101       1 istio_rules_service.go:114] Querying template got an error: istio-system doesn't return a tracespans list
W0807 14:40:08.633949       1 istio_rules_service.go:114] Querying adapter got an error: istio-system doesn't return a noops list
W0807 14:40:08.634298       1 istio_rules_service.go:114] Querying adapter got an error: istio-system doesn't return a dogstatsds list
W0807 14:40:08.634349       1 istio_rules_service.go:114] Querying adapter got an error: istio-system doesn't return a circonuses list
W0807 14:40:08.634403       1 istio_rules_service.go:114] Querying adapter got an error: istio-system doesn't return a zipkins list

**Affected product area (please put an X in all that apply)**

[x ] Configuration Infrastructure
[ ] Docs
[x ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ x] Security
[ ] Test and Release
[ ] User Experience
[x ] Developer Infrastructure

**Expected behavior**
To see the Istio MeshPolicy. This was working until recently.

**Steps to reproduce the bug**
- Uninstall _Istio_
- Uninstall _Istio-Init_
- Remove _Istio_ CRDs
- Delete _istio-system_ namespace
- Reinstall _Istio-Init_
- Reinstall _Istio_

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

> client version: 1.2.2
> citadel version: 1.2.3
> galley version: 1.2.3
> ingressgateway version: 1.2.3
> pilot version: 1.2.3
> policy version: 1.2.3
> sidecar-injector version: 1.2.3
> telemetry version: 1.2.3

> Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:46:06Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"windows/amd64"}
> Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.10-eks-2e569f", GitCommit:"2e569fd887357952e506846ed47fc30cc385409a", GitTreeState:"clean", BuildDate:"2019-07-25T23:13:33Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
Helm

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS EKS

**Comment by bhavyanshu** [comment]
We are facing the exact problem in our EKS cluster. We installed everything using Helm.

**Comment by jaygridley** [comment]
Same here on Azure AKS. We installed using Kiali Operator.

**Comment by jmazzitelli** [comment]
Some work very recently went into meshpolicies / servicemeshpolicies (mainly for Maistra integration).
@lucasponce can you look at this and see what you think?

This seems like the installation is just missing some permissions, but I am not sure if that's all that is happening here.

**Comment by jmazzitelli** [comment]
Kiali 1.2 has the meshpolicies permissions:

https://github.com/kiali/kiali/blob/v1.2/operator/roles/kiali-deploy/templates/kubernetes/role.yaml#L109-L119

Kiali 0.20 does as well:

https://github.com/kiali/kiali/blob/v0.20/operator/roles/kiali-deploy/templates/kubernetes/clusterrole.yaml#L108-L118

Note that both are valid only if you installed via the Operator.

Istio 1.2 helm chart has it, too:

https://github.com/istio/istio/blob/release-1.2/install/kubernetes/helm/istio/charts/kiali/templates/clusterrole.yaml#L109-L119

So it doesn't seem to be a permissions issue.

**Comment by jmazzitelli** [comment]
I believe this is a dup of this issue: https://github.com/kiali/kiali/issues/1337

**Comment by abonas** [comment]
related issue https://github.com/kiali/kiali/issues/1337

**Comment by israel-hdez** [comment]
@stevehipwell @bhavyanshu @jaygridley Can you please provide you AKS/EKS versions?

**Comment by jaygridley** [comment]
I've tried on Kubernetes 1.13.9 and 1.14.5 with Kiali 1.3.1/1.1.0/0.20 all with same issue.

**Comment by bhavyanshu** [comment]
My cluster is: 

```
Istio 1.2.2
Kubernetes Version: 1.13
Platform Version : eks.2

Client Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-eks-fa4c70", GitCommit:"fa4c703fa1706fac99d00d7f1f2080e9d4cc7eed", GitTreeState:"clean", BuildDate:"2019-07-23T03:14:24Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.8-eks-a977ba", GitCommit:"a977bab148535ec195f12edc8720913c7b943f9c", GitTreeState:"clean", BuildDate:"2019-07-29T20:47:04Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by lucasponce** [comment]
Yes, this issues is related kiali/kiali#1337.
A fix has already sent https://github.com/kiali/kiali/pull/1346

**Comment by clyang82** [comment]
This issue was fixed in https://github.com/istio/istio/pull/16993
