### ISSUE TITLE
[Mixer/CEL] Align Mixer's match function with CEL counterpart (matches).

### ISSUE THREAD

**Issue by ozevren** [istio/istio#1613]
Mixer currently has a "match" function that performs a prefix/suffix match:

`match("ns1.svc.local", "ns1.*") => true`
`match("ns1.svc.local", "ns2.*") => false`
`match("svc1.ns1.cluster", "*.ns1.cluster") => true`
`match("svc1.ns1.cluster", "*.ns1.cluster1") => false`

CEL also introduces a similar function matches:
https://github.com/google/cel-spec/blob/master/doc/langdef.md
`// matches second argument against regular expression in first argument`
`matches: (string, string) -> bool `

e.g.

`matches("ns1\\.svc\\.local","ns1.svc.local") => true`
`matches("ns1.*","ns1.svc.local") => true`
`matches("ns2.*","ns1.svc.local") => false`

These two functions have very similar names, which is prone to cause confusion. Given that we both want [CEL alignment](https://github.com/istio/old_mixer_repo/issues/1490) and want to have [regex matching support](https://github.com/istio/old_mixer_repo/issues/1493), it makes sense to implement the regex function as "matches" and refactor the existing match function.

The most straightforward refactoring is to introduce two special case methods for prefix or postfix matching:
`// Picked starts & ends as names, to start the discussion. We can replace with better names.`
`starts(prefix, expression)`
`ends(suffix, expression)`

e.g.

`starts("ns1", foo)`
`starts("ns1.", "ns1.svc.local") => true`
`starts("ns2.", "ns1.svc.local") => false`
`ends(".ns1.cluster", "svc1.ns1.cluster") => true`
`ends(".ns2.cluster", "svc1.ns1.cluster") => false`

Alternatives are:

- Keep things as is: 
  - Names are too close to each other, which is bound to cause confusion.
- Rename matches (i.e. mask): `mask("ns1.*", foo)`
  - Not a commonly encountered type of string function: Specialized format, involving "*", that suspiciously looks like regex. Many languages have (separate) string suffix/prefix check functions natively.
- Remove the function altogether and depend on "matches".
  - Writing some of these constraints in regex can be awkward:
    - `starts("ns1.svc.", foo)` v.s. `match("ns1\\.svc\\..*", foo)`

**Comment by ozevren** [comment]
@geeknoid @mandarjog @guptasu @douglas-reid

**Comment by geeknoid** [comment]
I like starts/ends, they're simple and intuitive.

**Comment by douglas-reid** [comment]
starts/ends seems reasonable. As for better names, I might be inclined to use `startsWith` and `endsWith`, or `hasPrefix` and `hasSuffix`.

I also wonder whether or not the prefix/suffix arg should be second in the args order (`hasPrefix(foo, "ns1")`), but I guess we should follow whatever the CEL convention is.

**Comment by ozevren** [comment]
I did a cursory research in CEL implementations and, there is very little reliable information to glean from.

It looks like matches has two implementations in two different places: one instance method, the other not (i.e. "foo.*".matches("fooo") v.s. matches("foo.*", "fooo") ). The matches parameter ordering makes sense for use as instance method model.

For prefix/suffix functions, my initial thinking was to align with non-instance matches, and also tried to avoid composite words since it can cause speed bumps in reading & writing. However, if we can model these as instance methods (i.e. "foo".startsWith("f")), then it makes sense to change both the parameter ordering and the name as well. 

I am following up with the CEL folks, will update.

**Comment by ozevren** [comment]
Here is the latest:
matches function in CEL will be an instance method.
There is an ongoing proposal for startsWith/endsWith instance methods.

With this, the final shape will be:
`"regex".matches("input") => bool`

`"str".startsWith("prefix") => bool`

`"str".endsWith("suffix") => bool`
