### ISSUE TITLE
Dynamic percentage based traffic routing with istio

### ISSUE THREAD

**Issue by navneetyps** [istio/istio#16130]
**Describe the feature request**
I want to use istio for doing blue green deployment but i don’t want the traffic percentage to be static. I want it to be variable acccording to some logic i apply For example i want the logic to be http error count in both versions and the one with lower error count would get a higher traffic percentage. Can this be accomplished via some istio feature or has to be done manually?

**Describe alternatives you've considered**
The current alternative i think is writing a shell script for getting the errors via curl requests, replacing percentages in virtual service yaml file and applying it again and doing all this in a loop.Is there a better way?

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by howardjohn** [comment]
The general idea of dynamic perctanges is a bit outside the scope of what we are trying to do, but is something that could be potentionally handled by istio/operator or other higher level tools.

However your specific ask
> For example i want the logic to be http error count in both versions and the one with lower error count would get a higher traffic percentage. 

I would suggest you look at https://istio.io/docs/reference/config/networking/v1alpha3/destination-rule/#OutlierDetection
