### ISSUE TITLE
Document version skew policy for upgrades and downgrades

### ISSUE THREAD

**Issue by ayj** [istio/istio#16137]
Kubernetes has a documented [version skew policy](https://kubernetes.io/docs/setup/release/version-skew-policy/) for their components. Istio should do the same. Its often not clear which versions of the control plane, proxy, and istioctl are compatible with one another. In particular, we frequently rely on "use the latest istioctl version" which may not work during upgrades/downgrades when the data and control plane are on a mixed set of versions.

[X] Networking

(Additional context from [istioctl and control plane version compatibility](https://docs.google.com/document/d/1GWxKEEVseQxk0cEAzHgCq_K-EK8MdUwdr1lOUK-kkrQ) doc)

(@costinm)
> We must support 'previous envoy' and 'current control plane' - otherwise you wouldn't be able to upgrade. During upgrade there is a rather long window where some workloads run with old envoy. Unfortunately this implies that the config format of envoy may not match - and proxy-config has failed many times, but AFAIK Envoy requires backward compatibility so 'latest' istioctl should also work, unless one of the deprecated fields is remo

(@ayj)
> envoy-- is a given for upgrades. Do we need envoy++ for downgrades, or do users need to always downgrade the data plane for control plane?

(@costinm)
> Good question.. Envoy is generally backward compatible, so old control plane should handle new envoy without problems - but I doubt we test for it. I don't think we have a choice - you can't downgrade the workloads if the new injector is still running, so if something goes wrong you need to downgrade the control plane - which implies updated workloads with envoy++ must keep working

**Comment by esnible** [comment]
@frankbu Does this belong here or in https://github.com/istio/istio.io ?

**Comment by keithmattix** [comment]
@howardjohn Did this ever get addressed anywhere? Specifically the control plane/proxy skew compatibility guarantees

**Comment by howardjohn** [comment]
Doesn't look like it. Should be on https://istio.io/latest/docs/releases/supported-releases/ if so.

The policy is control plane can be 1 version ahead of data plane. Data plane cannot be ahead of control plane. Recommendation is to use revisions then there is no skew at all.

So far data plane to data plane is compatible across all versions - that may change in the future but TBD

**Comment by keithmattix** [comment]
Awesome, thanks! I can add a "Control/Data Plane Version Skew" section to that page via a PR
