### ISSUE TITLE
istio/installer references `non.existent.cluster`

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#16155]
I have no clue what this is trying to do, but for some reason `preconfigured.yaml` references `non.existent.cluster` in egress... If this is intentional can we document why?

**Comment by costinm** [comment]
To be honest - no idea about it, it's from some version we merged. I haven't touched egress much.

**Comment by howardjohn** [comment]
>  it's from some version we merged

I think you added this, preconfigured.yaml does not have any VirtualServices in istio/istio. The whole preconfigured stuff is completely untested and different that istio/istio, where it was also problem untested

**Comment by howardjohn** [comment]
This is guarded under `gateway.zvpn.enabled` which didn't exist on the old install. I think we should just delete it given nobody knows what it is supposed to do?
