### ISSUE TITLE
mixer.telemetry.enabled not working properly

### ISSUE THREAD

**Issue by seth-hg** [istio/istio#16159]
**Bug description**

Changing "mixer.telemetry.enabled" to "false" does not turn off report calls in the sidecar. Instead, it disabled policy check calls.

Here is the mixer filter configuration dumped from the sidecar. I think "disable_check_calls" should be "disable_report_calls".

```
	{
             "config": {
              "transport": {
               "check_cluster": "outbound|9091||istio-policy.istio-system.svc.cluster.local",
               "network_fail_policy": {
                "policy": "FAIL_CLOSE",
                "max_retry_wait": "1s",
                "base_retry_wait": "0.080s"
               }
              },
              "service_configs": {
               "default": {
                "disable_check_calls": true
               }
              },
              "default_destination_service": "default",
              "mixer_attributes": {
               "attributes": {
                "destination.ip": {
                 "bytes_value": "AAAAAAAAAAAAAP//rBAAFQ=="
                },
                "destination.uid": {
                 "string_value": "kubernetes://hello-7987976576-92v76.pandora-test"
                },
                "context.reporter.kind": {
                 "string_value": "inbound"
                },
                "destination.port": {
                 "int64_value": "50052"
                },
                "context.reporter.uid": {
                 "string_value": "kubernetes://hello-7987976576-92v76.pandora-test"
                },
                "destination.namespace": {
                 "string_value": "pandora-test"
                }
               }
              }
             },
             "name": "mixer"
            }
```

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

istioctl version --remote
client version: 1.2.2
citadel version: 1.2.2
galley version: 1.2.2
ingressgateway version: 1.2.2
pilot version: 1.2.2
policy version: 1.2.2
sidecar-injector version: 1.2.2

kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.13", GitCommit:"290fb182489a396dce5d136451388f9b12f29c94", GitTreeState:"clean", BuildDate:"2018-05-15T18:16:09Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.4-tke.3", GitCommit:"ab6e1c10a35382c2ec70036e0e51c201eb3fc3f8", GitTreeState:"clean", BuildDate:"2019-06-18T12:12:29Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**

helm template install/kubernetes/helm/istio --name istio --namespace istio-system|kubectl apply -f -

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by bianpengyuan** [comment]
Did you observe the telemetry server is still receiving report calls? I think actually the report call is effectively disabled. Reason being `report_cluster` is not specified, thus the mixer_filter will fallback to use `mixer_server` as `report_cluster`, which does not exist so report call will just fail.

Sorry that this is confusing and we should fill in `disable_report_calls: false` as you suggested. I will send a PR for this. If you need neither telemetry nor policy, you could set both `mixer.policy.enabled` and `mixer.telemetry.enabled` as false so that mixer filter will not be injected, that way you can make sure there is no report happening.

**Comment by seth-hg** [comment]
> Did you observe the telemetry server is still receiving report calls? I think actually the report call is effectively disabled. Reason being `report_cluster` is not specified, thus the mixer_filter will fallback to use `mixer_server` as `report_cluster`, which does not exist so report call will just fail.

Yes, report calls failed. My point is that these calls should never be made since telemetry is disabled.

Actually, I was benchmarking my own service over istio and encountered some performance issues. The sidecar has introduced about 60ms to the average latency. So I tried disabling policy checks and telemetry reports, none works. But when I disabled both, performance boosted up. 

I tried to understand these results and found out that even when I disabled mixer telemetry, the sidecar is still making report calls. I think that these report calls is the main cause of my performance issue. Do you have any suggestions?

**Comment by bianpengyuan** [comment]
> Yes, report calls failed. My point is that these calls should never be made since telemetry is disabled.

Yeah, that is the work item I mentioned.

> Actually, I was benchmarking my own service over istio and encountered some performance issues. The sidecar has introduced about 60ms to the average latency. So I tried disabling policy checks and telemetry reports, none works. But when I disabled both, performance boosted up.
> 
> I tried to understand these results and found out that even when I disabled mixer telemetry, the sidecar is still making report calls. I think that these report calls is the main cause of my performance issue. Do you have any suggestions?

The expensive part is Mixer filter, which extracts attributes and assemble request to policy and telemetry services. After disabling both policy and telemetry, pilot will stop injecting mixer filter and thus you saw the performance boost.

**Comment by seth-hg** [comment]
I profiled the envoy sidecar in two scenarios:

1. [policy & telemetry enabled](https://drive.google.com/open?id=1QqiNc-xaCp1NRLeXKXhiyalBzg97yTPU) [[svg](https://drive.google.com/open?id=1KULcdDKqdn8cxPxA9tVQ9GGcKVqKUm9X)]
2. [policy enabled & telemetry disabled](https://drive.google.com/open?id=1tBwvAlrWKtABPs1u2WO9cadqscRtyyF8) [[svg](https://drive.google.com/open?id=17qXYW6UAjZdQK_3k1yh5_Xkuxjs91vYA)]

It seems that [`istio::control::http::RequestHandlerImpl::Report()`](https://github.com/istio/proxy/blob/1.2.2/src/istio/control/http/request_handler_impl.cc#L103) was consuming a significant fraction of cpu time. And I believe this lead to the poor performance.

In the second scenario, if `disable_report_calls` is set to `true` as I expected, this performance penalty could be avoided since `RequestHandlerImpl::Report()` will return without doing anything.

**Comment by bianpengyuan** [comment]
Thanks for the profiling! `Report()` is an async call and does not block request, which could affect tail latency but might not affect median latency that much. Do you want to enable only policy check or do you want to disable both policy and telemetry?

**Comment by bianpengyuan** [comment]
Actually the method is called after every request finished, which affect throughput and median latency. Add disable report call could help with the performance. Anyway if you want neither check nor report, you could set both options false to avoid any performance penalty by removing mixer filter.
