### ISSUE TITLE
Pilot readiness probe causes delays in startup

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#16164]
Pilot's readiness probe is set to an initial delay of 5s, with a period of 30s. In my experience, Pilot is pretty much never ready within 5s, so that mean it won't be marked ready until 35s in. In reality pilot seems to take about 10s to start up typically (maybe less, I didn't test it too much).

The proper solution is probably not to just drop the readiness probe though, as it is hit even once it is marked as ready. Ideally we could say "when not ready, probe every second, then probe every 30s when it is ready"

**Comment by ckcd** [comment]
Can we just decrease the period, cause 30s is a little big for readiness probe. Does a 5s-10s period makes some bad effect ?

**Comment by howardjohn** [comment]
I would imagine 5s is fine, not sure why 30 was chosen
