### ISSUE TITLE
Retire docker.io/istionightly

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#16182]
This is no longer actually published nightly, since we are off of circleci. As such, it has not been updated in 2 months

**Comment by costinm** [comment]
How about publishing it from cloud builder or similar ? Including variants
for deb, bionic ?

The purpose was to speed the build and have a set of common tools for
debug. And a common base.

**Comment by howardjohn** [comment]
How does it speed up the build? we do the same thing now just in gcr.io/istio-testing as far as I know.

If you are talking about the base image I don't mean getting rid of that, I mean the repo that it is in

**Comment by howardjohn** [comment]
@sdake is working on our base image and making it updated in each release

**Comment by howardjohn** [comment]
I dont really know what i meant by retire it. We already don't publish to it. We should just not push more stuff there in the future
