### ISSUE TITLE
Unit test failure - re-enable pilotplugin_mtls test

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#16184]
Certs are expired: https://github.com/istio/istio/tree/2bfefe78b746c4f0c2b23e3bc2605492c2ab74a8/mixer/test/client/pilotplugin_mtls/testdata

**Comment by silentdai** [comment]
errr...

**Comment by howardjohn** [comment]
this needs to be backported to 1.1 and 1.2

**Comment by PiotrSikora** [comment]
Uhm, why this disabling test instead of renewing certificates?
