### ISSUE TITLE
tls :    Mode: SIMPLE

### ISSUE THREAD

**Issue by rakeshjain1213** [istio/istio#16190]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
I am not sure what `tlsMode: SIMPLE` means. Can you please fill in the template and give more detail?

**Comment by rakeshjain1213** [comment]
Hi,

Please have a look at attachment files.
    tls:
      mode: SIMPLE
The mode could be SIMPLE, MUTUAL.
So when trying to call a service which is outside the mesh, the external certificate needs certificate to be presented by caller.
The configuration for the same need to be done at ISTIO end, the same we did using DestinationRule and ServiceEntry, but was not able to hit the service.
**So need to know what is the configuration that need to be done from ISTIO end, so that we can call service outside the mesh using there certificate.**

**Comment by rakeshjain1213** [comment]
Please reopen the issue as it is not solved yet.

**Comment by vadimeisenbergibm** [comment]
@rakeshjain1213 If you need to perform MUTUAL TLS to an external service, you can check this task https://istio.io/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/#perform-mutual-tls-origination-with-an-egress-gateway

**Comment by rakeshjain1213** [comment]
Hi,

My Only question is, is it possible to call external services which need to be communicated over https by just configuring DestinationRule and ServiceEntry.
If yes how?
