### ISSUE TITLE
Istio (with Kubernetes) unable to connect to external ldap server 

### ISSUE THREAD

**Issue by maheshsin** [istio/istio#16198]
### **Issue:**
I am unable to connect to ldap ad server with istio from application deployed in Kubernetes cluster. Getting "Connect Error" in web api response.

### **Detailed Information:**
I have created web application (front-end : Angular, middle layer: Asp.net Core Web API, back-end: SQL server), deployed it on Kubernetes cluster. I have enabled Istio in Kubernetes. 

For application login functionality, I have used active directory authentication in asp.net core web API. but in web api response I am getting "Connect Error".
**I have created ServiceEntry as follows:**

apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: ldap-external
spec:
  hosts:
  - XYZ
  addresses:
  - 10.x.y.z
  ports:
  - name: tcp
    number: 389
    protocol: tcp
  location: MESH_EXTERNAL

**Also created egress firewall rule like below:**
In Destination Filters, I have added ldap server IP address and in Protocols and Ports : tcp:389. I have applied this rule to all resources.

**Asp.Net Core Web API code which I am using for ldap connection:**

`private object GenerateAccessToken(Parameters parameters)
        {
            ResponseObj response = new ResponseObj();
            try
            {
                var userName = parameters.UserName;
                var password = parameters.password;
                bool isValid = false;

                if (!string.IsNullOrEmpty(userName) && !string.IsNullOrEmpty(password))
                {
                    isValid = true;
                    int ldapPort = LdapConnection.DEFAULT_SSL_PORT;
                    System.String ldapHost = _ldapConSettings.Value.ldapHost;
                    System.String loginDN = (_ldapConSettings.Value.domainName != "")  ? (_ldapConSettings.Value.domainName + @"\" + userName) : (userName);                   
                    System.String pass = password;
                    System.String objectDN = String.Format(_ldapConSettings.Value.objectDN, userName);
                    System.String name =  parameters.UserName;
                    LdapConnection conn = new LdapConnection();                   
                    conn.Connect(ldapHost, ldapPort);
                    
		   if (!string.IsNullOrEmpty(loginDN))
                    {
                        try
                        {
                            conn.Bind(loginDN, pass);
                            isValid = true;
                        }
                        catch (LdapException ex)
                        {
                            isValid = false;
                            return Json(new ResponseData { Code = "104", Message = "Unable to eastablish connection with active directory.." + ' ' + ex.Message.ToString(), Data = null });
                        }
                    }
                    
                    conn.Disconnect();

                    if (isValid == true)
                    {
			return response;
                    }
                    else
                    {
                        return Json(new ResponseData {});
                    }
                }
                else
                {
                    return Json(new ResponseData { });
                }
            }
            catch (Exception e)
            {
                return "Ldap="+ _ldapConSettings.Value.ldapHost.ToString() + e.Message.ToString();
            }
        }`

As you can see in above code I am reading ldaphost from appsetting.json file in asp.net core web api project. I tried to keep ldap server ip address as value for ldapHost key and also tried with istio serviceentry i.e. ldap-external. but still I am getting "Connect Error" in API response.

**Comment by vadimeisenbergibm** [comment]
I would test it with telnet or some ldap client directly from the command line, to check which IP address is actually used.

>  I tried to keep ldap server ip address as value for ldapHost key and also tried with istio serviceentry

So is the same IP address as you specify in the service entry actually used?
