### ISSUE TITLE
Enable security vulnerability scanning of Istio images

### ISSUE THREAD

**Issue by johnma14** [istio/istio#16195]
Enabling security vulnerability scanning of Istio images on a periodic basis (e.g once a week) will enable us to proactively identify any security vulnerabilities in our images. As part of this feature, some of the things we want to do are listed below:

- Currently we are using the ImageScanner tool. Investigate if there are any other open source tools we can  leverage to scan images OR write our own tool to scan Istio images
- Enable a mechanism where an email can be sent to the team that handles security vulnerabilities on a periodic basis ( istio-security-vulnerability-reports@googlegroups.com).

Currently we have a basic mechanism to scan Istio images using the ImageScanner tool.
- To scan Istio images we can run the command (from istio.io/istio directory):  
`make docker.scan_images`
- To scan bookinfo sample app images run the command (from istio.io.docker/sample/bookinfo directory): `./build_push_update_images.sh [version] --scan-images`

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x ] Security
[x ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by howardjohn** [comment]
The easiest way to automate this is probably just to use https://cloud.google.com/container-registry/docs/get-image-vulnerabilities#notifications. We already scan all our daily builds, just need to set up notifications

**Comment by johnma14** [comment]
Hi @howardjohn, thank you for letting us know. We will subscribe to these notifications and evaluate the differences between the vulnerability scan results and if needed will reopen this later. Closing this for now. Thank you.
