### ISSUE TITLE
Integrate URL installPackagePath support into CLI command

### ISSUE THREAD

**Issue by ostromart** [istio/istio#16203]
We need to be able to set installPackagePath to something like 
https://github.com/istio/istio/releases/tag/1.2.3
(or simply version: 1.2.3, which is an alias for the above)
manifest commands must:
1. fetch the release tar if it's not locally cached (with appropriate timeout/network problem errors)
2. untar it to a local cache temp dir
3. setup a FS helm renderer pointing to the extracted charts root dir

**Comment by richardwxn** [comment]
merged in [operator/186](https://github.com/istio/operator/pull/186)
