### ISSUE TITLE
Provide config to disable issuer validation in JWT auth.

### ISSUE THREAD

**Issue by TonyDou** [istio/istio#16212]
Support a config to disable issuer validation in JWT auth filter.

I'm trying to enable Azure Active Directory (AAD) support with this JWT auth filter. For a signle AAD tenant (each tenant is an issuer), it works perfectly. But as for multi-tenant applications, it does not work properly. Because  for multi-tenant, the issuer (related to tenant id) is unpredictable, but all issuers are using the same set of keys to sign and validate tokens.

So if the jwt auth filter allows to disable issuer validation, and try to validate the jwt token with all specified JWKS. It will solve the current issue to integrate with AAD multi-tenant application. 

[X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by luxianlong** [comment]
I have the same problem when ingrate with AAD
