### ISSUE TITLE
Avoid bypassing authN/authZ when using protocol sniffing

### ISSUE THREAD

**Issue by yxue** [istio/istio#16214]
https://github.com/istio/istio/commit/2d4c642725c00c1436977924d5d5213b4f991b80

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
if we can bypass authN we must document this. Can you add it to https://github.com/istio/istio/wiki/Release-Note-1.3-Draft
