### ISSUE TITLE
istio-proxy envoy access log sampling

### ISSUE THREAD

**Issue by erks** [istio/istio#16210]
**Describe the feature request**

Envoy provides a way to change access log sampling as follows: https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/accesslog/v2/accesslog.proto#envoy-api-msg-config-filter-accesslog-v2-runtimefilter. However, istio-proxy doesn't seem to provide a way to configure that. Being able to sample envoy access log is helpful to avoid overwhelming logging infrastructure (e.g. splunk, datadog) while still maintaining the benefits of having some (sampled) log data to investigate issues.

**Describe alternatives you've considered**

None.

**Affected product area (please put an X in all that apply)**

[x] Configuration Infrastructure
[x] Docs
[ ] Installation
[ ] Networking
[x] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by douglas-reid** [comment]
There is an outstanding proposal to add support for this config to the `Sidecar` resource. I hopefully will have more to share in the coming weeks.

**Comment by douglas-reid** [comment]
@erks There is some debate over API surface at the moment. In the meantime, EnvoyFilter API may be able to help here.  Please see: https://github.com/istio/istio/wiki/EnvoyFilter-Samples#tracing-and-access-logging. You should be able to modify those examples to meet your use case.

**Comment by erks** [comment]
@douglas-reid Is this supported in istio 1.2.x? or is it 1.3 only? The example looks like 1.3 syntax.

**Comment by douglas-reid** [comment]
This is 1.3 only.

**Comment by douglas-reid** [comment]
There is not any proposal pending for adding support for older versions of Istio.

**Comment by DNorv** [comment]
please update docs for use v3 api 

new version envoy do not support v2 api:

` Proto constraint validation failed (Illegal use of hidden_envoy_deprecated_ V2 field 'envoy.config.accesslog.v3.AccessLog.hidden_envoy_deprecated_config' from file accesslog.proto while using the latest V3 configuration. This field has been removed from the current Envoy API. Please see https://www.envoyproxy.io/docs/envoy/latest/version_history/version_history for details.)`

**Comment by anoopl** [comment]
I have updated this to v3 on my yaml file. But log doesn't show the header Test. I do not see any error on config json or logs
`apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: access-log
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: ANY
      listener:
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
    patch:
      operation: MERGE
      value:
          access_log:
          - name: envoy.file_access_log
            typed_config:
              "@type": "type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog"
              path: /dev/stdout
              format: "%REQ(Test)% %REQ(:METHOD)% %PROTOCOL% %RESPONSE_CODE% %RESPONSE_FLAGS%\n"`

I removed the sampling rate from example here:  https://github.com/istio/istio/wiki/EnvoyFilter-Samples#tracing-and-access-logging

Any help on this is appreciated. I remember I had this working on 1.4 version of Istio. Right now I am using Istio 1.7.3
