### ISSUE TITLE
[help wanted] istio-init: readdirent: invalid argument 

### ISSUE THREAD

**Issue by Blasterdick** [istio/istio#1621]
I have VirtualBox vm with Ubuntu Server 16.04 and `kubernetes-core`, installed by `conjure-up` on local `lxd`. Also, `Istio` v0.2.12 is up and running.

```
$ istioctl version
Version: 0.2.12
GitRevision: 998e0e00d375688bcb2af042fc81a60ce5264009
GitBranch: release-0.2
User: releng@0d29a2c0d15f
GolangVersion: go1.8.3
```

```
$ kubectl get svc -n istio-system
NAME            TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                                  AGE
istio-egress    ClusterIP   10.152.183.55    <none>        80/TCP                                                   52m
istio-ingress   NodePort    10.152.183.200   <none>        80:30841/TCP,443:32311/TCP                               52m
istio-mixer     ClusterIP   10.152.183.20    <none>        9091/TCP,9093/TCP,9094/TCP,9102/TCP,9125/UDP,42422/TCP   52m
istio-pilot     ClusterIP   10.152.183.38    <none>        8080/TCP,443/TCP                                         52m

```
```
$ kubectl get pod -n istio-system
NAME                             READY     STATUS    RESTARTS   AGE
istio-ca-57f9bd7ddb-8sfgf        1/1       Running   0          52m
istio-egress-6c6b84cd5d-ztb9z    1/1       Running   0          52m
istio-ingress-79cf84458b-7fs94   1/1       Running   0          52m
istio-mixer-6fdc6784c7-n89z2     2/2       Running   0          52m
istio-pilot-5f4865659b-kncj6     1/1       Running   0          52m

```
But when I'm trying to execute this:

`istioctl kube-inject -f app-deployment.yaml |kubectl create -f -`

pod won't get created with following error in kubernetes dashboard:

`failed to start container "istio-init": Error response from daemon: linux runtime spec devices: readdirent: invalid argument`

while the deployment by itself works as expected. What can be wrong with it? Thanks in advance.

**Comment by ldemailly** [comment]
@rkpagadala can you try a 1.8 cluster (gke first) and see if you get the same error (or find someone who can) ?

**Comment by andraxylia** [comment]
The built & tested with docker containers, not sure if it works with lxd.

**Comment by costinm** [comment]
Not sure if it's still happening, reopen if needed but I don't think lxd support is a priority before 1.0
