### ISSUE TITLE
istio-iptables.sh fails to configure net ns via CNI on GKE with COS due to missing modules

### ISSUE THREAD

**Issue by davidsmd** [istio/istio#16218]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

The istio-iptables.sh script fails on GKE when using:

COS version:    gke-1128-gke10-cos-69-10895-277-0-v190620-pre 
k8s version :     1.12.8-gke.10 

due to missing kernel modules required by ip6tables rules.
The script fails during net ns setup, and results in pods stuck in containercreating state indefinitely.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Expected behavior**

The istio-iptables.sh script should run to completion without errors on GKE setups using recent version of the Container OS image.

**Steps to reproduce the bug**

1. Create a new cluster on GKE, version 1.12.8-gke.10, using COS as the node image.
2. Install istio via the CNI method described in the documentation.
3. Deploy pods to a namespace, default for ease of use.
4. Label deployment namespace with `istio-injection=enabled`.
5. Delete/Recycle one or more pods in the tagged namespace.
6. The recycled pod(s) should get to containercreating before being terminated due to sandbox setup errors; this will repeat and is visible in `k describe po <podname>` events.
7. Get the name of the node that the broken pod is running on: `k get po -o wide`.
8. SSH into the node that the broken pod is running on.
9. Verify isitio-iptables.sh exists in /home/kubernetes/bin (per target dir for CNI install in Istio guide).

10. Use `journalctl -t kublet -n 1000` to get kubelet logs.
11. Search for `Error adding network: exit status 1` or `Error while adding to cni network: exit status 1`
12. Scroll upward from there to view the errors leading to this state.

13. Since the pods aren't starting, you can't nsenter them, but the logs will contain repeats of:
 `/sbin/ip6tables -A INPUT -m state --state ESTABLISHED -j ACCEPT`
 `ip6tables: Protocol wrong type for socket.`

14. Looking at the serial console logs, 
 `xt_conntrack: cannot load conntrack support for proto=10`
shows up continuously as the CNI script tries to run, and then retries.

15. `lsmod | grep conntrack` returns nothing
16. Visual inspection of lsmod indicates that the module required for `ip6tables` to work with `-m state` flag is not present.

Removing the ip6tables commands entirely (including the ip6 save command further up in the script) allows the script to complete correctly.

(I can't remember off the top of my head if I checked the iptables of the pods that started after modifying the script for certain. Pretty sure I did and they were fine after the changes.)

I'd submit a PR for this, but honestly, I'm not sure what non-GKE systems may need or not need in the istio-iptables.sh script that, and not totally comfortable just guessing at that.
 
 

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
istioctl:
client version: 1.2.3
citadel version: 1.2.3
galley version: 1.2.3
ingressgateway version: 1.2.3
pilot version: 1.2.3
policy version: 1.2.3
sidecar-injector version: 1.2.3
telemetry version: 1.2.3

kubectl:
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:23:26Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.8-gke.10", GitCommit:"f53039cc1e5295eed20969a4f10fb6ad99461e37", GitTreeState:"clean", BuildDate:"2019-06-19T20:48:40Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**

With helm, from generated templates; no tiller install.

**Environment where bug was observed (cloud vendor, OS, etc)**

Vendor:  Google Cloud Platform, GKE
COS version:    gke-1128-gke10-cos-69-10895-277-0-v190620-pre 
k8s version :     1.12.8-gke.10 

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

I can generate a dump file if need be, but I'm not sure that's going to be a lot of help here.

**Comment by davidsmd** [comment]
Any information on this?

**Comment by costinm** [comment]
@fpesce  - this seems P0 - should be relatively small change.

**Comment by howardjohn** [comment]
@rlenglet any ideas here?

**Comment by rlenglet** [comment]
When IPv6 is enabled, and the pod gets an IPv6 address, we require ip6tables support in the kernel. Otherwise, IPv6 traffic would bypass the sidecar.
If that's not intended, I'd suggest disabling IPv6 support on the nodes altogether.

**Comment by rlenglet** [comment]
Also I'd first check whether this is still reproduceable in 1.3/1.4/1.5. We've fixed quite a few issues with CNI's IPv6 detection and support since Aug 2019.
