### ISSUE TITLE
helm create wrong accessLogFormat in Istio cm. Istio 1.2.3.

### ISSUE THREAD

**Issue by kidiyoor** [istio/istio#16220]
**Bug description**
`--set global.proxy.accessLogFormat='{ "start_time": "%START_TIME%" }' ` results in 
```
accessLogFormat: \"[ \\\"start_time\\\": \\\"%START_TIME%\\\"
    ]\"\n\n
```

whereas it should be 
```
accessLogFormat: \"{ \\\"start_time\\\": \\\"%START_TIME%\\\"
    }\"\n\n
```

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**
```
helm template install/kubernetes/helm/istio --name istio --namespace istio-system --set gateways.istio-egressgateway.enabled=false --set gateways.istio-ingressgateway.sds.enabled=true --set grafana.enabled=true --set global.proxy.accessLogFile="/dev/stdout" --set global.proxy.accessLogEncoding="JSON" --set global.proxy.accessLogFormat='{ "start_time": "%START_TIME%" }' | kubectl apply -f -
```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
$istioctl version --remote
client version: 1.2.3
citadel version: 1.2.3
galley version: 1.2.3
ingressgateway version: 1.2.3
pilot version: 1.2.3
policy version: 1.2.3
sidecar-injector version: 1.2.3
telemetry version: 1.2.3

$kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T18:56:40Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.8-gke.10", GitCommit:"f53039cc1e5295eed20969a4f10fb6ad99461e37", GitTreeState:"clean", BuildDate:"2019-06-19T20:48:40Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
https://istio.io/docs/setup/kubernetes/install/helm/

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
Helm treats `{a,b}` as a list of a and b. , I think that is the problem

**Comment by kidiyoor** [comment]
how to pass a map[string]string interface to `global.proxy.accessLogFormat`

**Comment by kidiyoor** [comment]
`--set-string` didn't help

**Comment by howardjohn** [comment]
try `--set global.proxy.accessLogFormat='\{ "start_time": "%START_TIME%" \}' `, seems to work for me

**Comment by kidiyoor** [comment]
That trick only works with only one key/value pair. 
```
$ helm template install/kubernetes/helm/istio --name istio --namespace istio-system \
--set global.proxy.accessLogFile="/dev/stdout" --set global.proxy.accessLogEncoding="JSON" \
--set global.proxy.accessLogFormat='\{ "timestamp": "%START_TIME%", "upstream_org": "%REQ(UPSTREAM-ORG)%" \}' | kubectl apply -f -
Error: failed parsing --set data: key " \"upstream_org\": \"%REQ(UPSTREAM-ORG)%\" }" has no value
error: no objects passed to apply
```

If you do not separate key/value pairs with comma, helm cmd passes but the generated ConfigMap won't have the right JSON.
```
accessLogFormat: \"{ \\\"timestamp\\\": \\\"%START_TIME%\\\"
    \\\"upstream_org\\\": \\\"%REQ(UPSTREAM-ORG)%\\\" }
```

**Comment by howardjohn** [comment]
Interesting. Well it seems there is not  reason to fight helm like this, I would just do it as a file.

```
$ helm template install/kubernetes/helm/istio --name istio --namespace istio-system -f values.yaml | grep accessLogFormat:
    accessLogFormat: "{\"start_time\":\"%START_TIME%\", \"foo\":\"bar\"}"
$ cat values.yaml
global:
  proxy:
    accessLogFormat: '{"start_time":"%START_TIME%", "foo":"bar"}'
```

Seems to work?
