### ISSUE TITLE
[Mixer] unit tests fail for `go test ./mixer/...`

### ISSUE THREAD

**Issue by GregHanson** [istio/istio#1622]
Mixer tests only work with bazel currently.  Mixer tests should not require bazel and should be compatible with `dep ensure`.  For example:

```
go get -u github.com/golang/dep/cmd/dep
cd $GOPATH/src/istio.io/istio; dep ensure
go test ./mixer/...
```

Bazel has significant memory needs and some circleci jobs fail due to OOM errors

**Comment by jmuk** [comment]
seems failing on `tools/codegen` tests, possibly some expected filepath is different among bazel and `go test`?  @guptasu FYI

But, I think we will keep using bazel as for our canonical build tool. I'm not sure if "flaky-test" label can apply here.

**Comment by mandarjog** [comment]
This is related to https://github.com/istio/istio/issues/1578.
I have added  PR #1682 to run code coverage that includes running all tests except the one in the above issue.

**Comment by GregHanson** [comment]
bazel dependencies have been removed and `go test ./mixer/...` works now
