### ISSUE TITLE
Traffic failed during renew the certificate

### ISSUE THREAD

**Issue by eyaweiy** [istio/istio#16222]
**Bug description**
Running traffic on istio 1.2.2 with workloadCertTtl=1h, there is traffic failed.

The test case is sending traffic with h2load for 3 minutes, keep running test cases with different configurations like with/without sidecar, different payload size, different connections for 5 hours.
At last there are 3 cases failed because there are traffic failed like logs from h2load:
Process Request Failure:20
requests: 756732 total, 756732 started, 756732 done, 756719 succeeded, 13 failed, 13 errored, 0 timeout

When I set workloadCertTtl=720h (30 days), all the cases can pass.

It seems the renew of certificate will impact the traffic.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[X] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Traffic will not be impacted during renew the certificate.

**Steps to reproduce the bug**
set workloadCertTtl=1h
running traffic for hours to see if there is traffic failed

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
istio 1.2.2

**How was Istio installed?**
via helm template

**Comment by howardjohn** [comment]
When the request fail, what is the failure? Connection closed, 503, etc?

**Comment by eyaweiy** [comment]
It is connection failure, not 503. 
From h2load log, no error code returned.
requests: 756732 total, 756732 started, 756732 done, 756719 succeeded, 13 failed, 13 errored, 0 timeout
status codes: 756719 2xx, 0 3xx, 0 4xx, 0 5xx

**Comment by howardjohn** [comment]
when a new cert is configure, envoy will do a hot restart. My guess is it's dropping some connections there. Can you correlate the 13 errors to cert rotation?

**Comment by eyaweiy** [comment]
Yes, the certificate is renewed about each 1m30s, and the connection failure happened also.
I test with fortio as traffic sender,
`09:07:48 I http_client.go:648> Closing dead socket &{{0xc000160580}} (err EOF at first read)
09:07:48 I http_client.go:648> Closing dead socket &{{0xc000160a80}} (err EOF at first read)
09:07:49 I http_client.go:648> Closing dead socket &{{0xc0002ba280}} (err EOF at first read)
09:07:49 I http_client.go:648> Closing dead socket &{{0xc00014c680}} (err EOF at first read)`
Logs from ingressgateway:
`2019-08-15T09:07:46.592615Z     info    watchFileEvents: "/etc/certs/..2019_08_15_09_07_46.865503026": CREATE
2019-08-15T09:07:46.592681Z     info    watchFileEvents: "/etc/certs/..2019_08_15_09_07_46.865503026": MODIFY|ATTRIB
2019-08-15T09:07:46.592689Z     info    watchFileEvents: "/etc/certs/..data_tmp": RENAME
2019-08-15T09:07:46.592757Z     info    watchFileEvents: "/etc/certs/..data": CREATE
2019-08-15T09:07:46.592774Z     info    watchFileEvents: "/etc/certs/..2019_08_15_09_06_31.910336012": DELETE`
