### ISSUE TITLE
Unable to access Swagger-UI from the ingress node port

### ISSUE THREAD

**Issue by rakeshjain1213** [istio/istio#16227]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by rakeshjain1213** [comment]
HI,

Please consider the below scenario:
Service X --> type: NodePort(1234) --> Service accessible using swagger-ui (http://localhost:1234/swagger-ui.html)

Service X --> type: ClusterIP (changed from NodePort to ClusterIP)--> Istio Ingress Gateway configured --> Gateway, VirtualService and DestinationRule configured -->Now Ingress is exposed as type: Nodeport(31380) -->Now Service not accessible using swagger-ui (http://localhost:31380/swagger-ui.html), but if you try to access the service X using postman/soap-ui the request routes from ingress to the service and the response for the same can be seen.

So the issue is Service is accessible but the swagger-ui is not.

**Comment by howardjohn** [comment]
is port 1234 exposed in the Service? Can you include your Service, Virtual service, etc

**Comment by rakeshjain1213** [comment]
Hi,

Please find the configurations files and 1234 is just a example, actual port used is 8089.


[gateway.txt](https://github.com/istio/istio/files/3499835/gateway.txt)
[service.txt](https://github.com/istio/istio/files/3499836/service.txt)
[virtualservice.txt](https://github.com/istio/istio/files/3499837/virtualservice.txt)

**Comment by rakeshjain1213** [comment]
Hi,

Please update.

**Comment by malathi-thangarajan** [comment]
I am also facing the same issue when I access the swagger ui from istio-ingress-gateway with nodePort. The swagger UI has basePath missing the nodePort. So the "Try It Out" option for all the endpoints are not working.

**Comment by malathit** [comment]
I am also facing the same issue when I access the swagger ui from istio-ingress-gateway with nodePort. I use minikube for my kubernetes cluster. The swagger UI has basePath missing the nodePort. So the "Try It Out" option for all the endpoints are not working.

**Comment by girisheduru** [comment]
I am facing the same issue with version 1.6.5
