### ISSUE TITLE
OPA adapter not working in Mixer

### ISSUE THREAD

**Issue by emedina** [istio/istio#16239]
I followed the instructions in this closed issue, but I just cannot make it work (see my comments at the end of the issue itself):

https://github.com/istio/istio/issues/13098

**Comment by douglas-reid** [comment]
@liminw can you provide any guidance here?

**Comment by liminw** [comment]
We are not actively maintaining this feature currently. I suspect the samples may be out of date. @kyessenov or @douglas-reid are able to help answer the questions on Mixer config changes. If there are questions on OPA semantics, I will refer it to @tsandall. 

On the other note, according to @mandarjog, the existing Mixer adapters will be deprecated in 1.3 release. With Mixer V2 proposal, some of the existing Mixer functionality will be moved to Proxy.
