### ISSUE TITLE
access https service through istio ingress gateway 

### ISSUE THREAD

**Issue by dhineshbabuelango** [istio/istio#16231]
Hi All, 
We are using istio in aws eks. We are trying to deploy an IBM application inside istio, this IBM application will accept only https traffic. We followed the below steps after installing istio.

1. Deployed the application in the namespace where istio label is injected by default.
2. Created secrets for ingress gateway(SDS enabled) and mentioned the secrets name in the gateway
   
   apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: tls-gateway
spec:
  selector:
    istio: admin-ingressgateway # use istio default controller
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: ingressgateway-certs
      minProtocolVersion: TLSV1_2
      maxProtocolVersion: TLSV1_2
    hosts:
    - "*"

3. Created virtual service for ibm application
    ---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: isam-service
spec:
  hosts:
  - "*"
  gateways:
  - tls-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: isamconfig-service
        port:
          number: 9443

and then tried to access the application through ingress gateway loadbalancer but got the below 
"upstream connect error or disconnect/reset before headers. reset reason: connection termination"

Then I created a destination rule like below for that particular service after which I was able to access my application through ingress gateway loadbalancer.

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: test-http-dr
spec:
  host: isamconfig-service
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 9443
      tls:
        mode: SIMPLE

But after I enable mTLS  at the namespace level, again I was not able to access getting the below error.

"upstream connect error or disconnect/reset before headers. reset reason: connection failure"

This is because after we enable mTLS, all the services are expeting only mTLSconnection and accept only mTLS connection but our destination rule says tls mode is SIMPLE which is creating a conflict in pilot.

HOST:PORT                                                      STATUS       SERVER        CLIENT     AUTHN POLICY                                 DESTINATION RULE

isamconfig-service.apps.svc.cluster.local:9443                 CONFLICT     mTLS          TLS        default/apps                                 test-http-dr/apps

I have seen some istio docs where they have asked us to use config map and certificates manually inside the delpoyment yaml file, tried the below technote as well which has steps for mTLS enabled HTTPS application., but this shows the steps on how can we access service to service but what I need is to access through istio-ingress gateway.

https://istio.io/docs/tasks/security/https-overlay/

How can I achieve this.

**Comment by vadimeisenbergibm** [comment]
This one looks tricky. The ingress gateway has to perform both TLS origination and mTLS origination on top of it. I do not think it is possible with Envoy. A possible solution could be to define an additional Gateway on some port, let's say 444, that gateway will perform mTLS origination without TLS termination. Your original Gateway will perform TLS origination and direct the traffic to port 444 on the localhost.

So the traffic will flow in the following way:
Internet -> port 443 of the first Gateway -> TLS termination -> TLS origination to port 444 -> mTLS origination to the destination

**Comment by dhineshbabuelango** [comment]
Thanks Vadmin. so I should create another gateway and let the first gateway to point to the newly created gateway and the newly created gateway to the virtual service created for application?
