### ISSUE TITLE
Upgrades in istio

### ISSUE THREAD

**Issue by dhineshbabuelango** [istio/istio#16232]
Hi All, 
We are using istio in EKS, we have istio 1.2.2 running in our environment, We want to upgrade istio to newer version 1.2.3, looking if there is any doc or steps that I can get for this.

Our environment is without internet and we have downloaded all the below images and put it in ECR and changed the helm values files. so If we just upgrade the new package with the same values file will it work.

INGRESS GATEWAY:
        image: docker.io/istio/node-agent-k8s:1.2.2
        image: docker.io/istio/proxyv2:1.2.2

ISTIO-CITADEL:
        image: docker.io/istio/citadel:1.2.2
		
EGRESS GATEWAY:
        image: docker.io/istio/proxyv2:1.2.2
				
ISTIO-GALLEY:
        image: docker.io/istio/galley:1.2.2

ISTIO-PILOT:
        image: docker.io/istio/pilot:1.2.2
        image: docker.io/istio/proxyv2:1.2.2
        		
ISTIO-POLICY:
        image: docker.io/istio/mixer:1.2.2
        image: docker.io/istio/proxyv2:1.2.2
        		
ISTIO-SIDECAR-INJECTOR:
        image: docker.io/istio/sidecar_injector:1.2.2
        
ISTIO-TELEMETRY:
        image: docker.io/istio/mixer:1.2.2
        image: docker.io/istio/proxyv2:1.2.2
       		
ISTIO-TRACING:
        image: docker.io/jaegertracing/all-in-one:1.9

**Comment by howardjohn** [comment]
Please see https://istio.io/docs/setup/kubernetes/upgrade/steps/
