### ISSUE TITLE
Nginx pod with sidecar injection returning 400 when proxy passing urls with spaces

### ISSUE THREAD

**Issue by leoncard** [istio/istio#16240]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

Nginx pod with sidecar injection turned on is returning `400` when proxy passing urls with spaces to upstreams.

The same behaviour doesn't happen with other urls that go to the same upstream but don't have spaces. They resolve just fine.

In addition, if the sidecar is disabled, the urls (with or without spaces) resolve just fine.

When the sidecar injection is turned, the `location block with "~/b/(.*)$"` is definitely being reached for urls with spaces, but the upstream is not. Again, urls without spaces work just fine.

**Affected product area (please put an X in all that apply)**

[X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Urls such as /a/b/my%20spaced%20path should give a 200 with the sidecarinjection enabled.

**Steps to reproduce the bug**

Having an nginx configuration such as the one down below pointing to a valid upstream within Kubernetes.

```
    upstream mytarget {
        least_conn;

        server mytargetkubernetesservice max_fails=0 fail_timeout=10s;

        keepalive 32;
    }

        location "~^/a/b" {
            rewrite "^/(.*)$"  "/b/$1?mykey=empty"  last;
        }

        location "~/b/(.*)$" {
            internal;
            proxy_connect_timeout 10s;
            proxy_read_timeout 900s;
            proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
            proxy_set_header Host sapi-core;
            proxy_pass "http://mytarget/$1?$args";
            proxy_ignore_headers "Cache-Control";
            proxy_ignore_headers "Expires";
        }
```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

istioctl output

```
client version: 1.2.3
citadel version: 1.2.2
galley version: 1.2.2
ingressgateway version: 1.2.2
ingressgateway version: 1.2.2
ingressgateway version: 1.2.2
ingressgateway version: 1.2.2
ingressgateway version: 1.2.2
ingressgateway version: 1.2.2
pilot version: 1.2.2
pilot version: 1.2.2
policy version: 1.2.2
sidecar-injector version: 1.2.2
telemetry version: 1.2.2
```

kubectl output

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

Our installation was based on the helm installation
https://istio.io/docs/setup/kubernetes/install/helm/

We have the `global.outboundTrafficPolicy.mode` set to `REGISTRY_ONLY` and `global.proxy.includeIPRanges` to `10.0.0.1/8` and our subnet.

**Environment where bug was observed (cloud vendor, OS, etc)**

Istio 1.2.2, Kubernetes 1.13.1, Nginx 1.15.8, Ubuntu 16 (docker image openresty/openresty:1.15.8.1-xenial)

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

Logs from the nginx pod:

For the url with spaces:

We have an inbound

```
[2019-08-13T15:59:15.037Z] "GET  /a/b/my%20spaced%20path HTTP/1.1" 400 - "-" "-" 0 0 1 0 "81.19.23.44,10.244.7.0" "vscode-restclient" "dc355188-3ae3-4e7a-9c92-b42d53d24485" "nginx.integration.domain" "127.0.0.1:80" inbound|80|http|nginx.integration.svc.cluster.local - 10.244.3.30:80 10.244.7.0:0 -
```

For the url with no spaces

We have an inbound and outbound

Inbound

```
[2019-08-13T16:01:13.161Z] "GET /a/b/mypathwithoutspaces HTTP/1.1" 200 - "-" "-" 0 0 165 165 "81.19.23.44,10.244.5.0" "vscode-restclient" "38255d65-651e-46e2-87d3-5ebf44094afe" "nginx.integration.domain" "127.0.0.1:80" inbound|80|http|nginx.integration.svc.cluster.local - 10.244.7.2:80 10.244.5.0:0 -
```

Outbound

```
[2019-08-13T16:01:13.162Z] "GET /a/b/mypathwithoutspaces?mykey=empty HTTP/1.1" 200 - "-" "-" 0 0 164 163 "81.19.23.44,10.244.5.0" "vscode-restclient" "38255d65-651e-46e2-87d3-5ebf44094afe" "mytargetkubernetesservice " "10.244.5.73:5001" outbound|5001||mytargetkubernetesservice.integration.svc.cluster.local - 10.102.12.168:5001 10.244.5.0:0 -
```

**Comment by howardjohn** [comment]
Is it possible nginx is doing something weird here? just going to httpbin with spaces seems to work fine:

```
/ $ curl 'httpbin.org/anything/fo%20o'
{
  "args": {},
  "data": "",
  "files": {},
  "form": {},
  "headers": {
    "Accept": "*/*",
    "Host": "httpbin.org",
    "User-Agent": "curl/7.58.0",
    "X-B3-Sampled": "0",
    "X-B3-Spanid": "38e1b21e353275fe",
    "X-B3-Traceid": "0d783fe8b329157938e1b21e353275fe",
    "X-Envoy-Expected-Rq-Timeout-Ms": "15000",
    "X-Istio-Attributes": "CjAKGGRlc3RpbmF0aW9uLnNlcnZpY2UubmFtZRIUEhJQYXNzdGhyb3VnaENsdXN0ZXIKOwoKc291cmNlLnVpZBItEitrdWJlcm5ldGVzOi8vc2hlbGwtNTk1OGJjZGI0NC1jeG50OS5kZWZhdWx0"
  },
  "json": null,
  "method": "GET",
  "origin": "35.239.76.81, 35.239.76.81",
  "url": "https://httpbin.org/anything/fo o"
}
/ $ curl 'httpbin.org/anything/foo'
{
  "args": {},
  "data": "",
  "files": {},
  "form": {},
  "headers": {
    "Accept": "*/*",
    "Host": "httpbin.org",
    "User-Agent": "curl/7.58.0",
    "X-B3-Sampled": "0",
    "X-B3-Spanid": "481fb2e986c6b5dd",
    "X-B3-Traceid": "c09b32d629b768ad481fb2e986c6b5dd",
    "X-Envoy-Expected-Rq-Timeout-Ms": "15000",
    "X-Istio-Attributes": "CjAKGGRlc3RpbmF0aW9uLnNlcnZpY2UubmFtZRIUEhJQYXNzdGhyb3VnaENsdXN0ZXIKOwoKc291cmNlLnVpZBItEitrdWJlcm5ldGVzOi8vc2hlbGwtNTk1OGJjZGI0NC1jeG50OS5kZWZhdWx0"
  },
  "json": null,
  "method": "GET",
  "origin": "35.239.76.81, 35.239.76.81",
  "url": "https://httpbin.org/anything/foo"
}
```
