### ISSUE TITLE
ISTIO- Case sensitive Virtual Service

### ISSUE THREAD

**Issue by dhineshbabuelango** [istio/istio#16264]
Hi All , We are using istio in EKS, to access a micro service through istio ingress gateway load balacner, we create gateway and virtual service. But the path we mention in the virtual service in prefix is case sensitive. I have seen some tech notes to use ignoreUriCase: true, but it doesn't worked, 
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: otp-service
spec:
  hosts:
  - "*"
  gateways:
  - tls-gateway
  http:
  - match:
    - uri:
        prefix: /otp/verify
    - uri:
        prefix: /otp/generateandsend
    route:
    - destination:
        host: webbook
        port:
          number: 80

ignoreuricase updated yaml.

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: otp-service
spec:
  hosts:
  - "*"
  gateways:
  - tls-gateway
  http:
  - match:
    - uri:
        prefix: /otp/verify
      ignoreUriCase: true
    - uri:
        prefix: /otp/generateandsend
    route:
    - destination:
        host: webbook
        port:
          number: 80

**Comment by howardjohn** [comment]
This was merged in https://github.com/istio/istio/pull/14304, after 1.2. It will be included in Istio 1.3, relasing in early sept
