### ISSUE TITLE
Junit style test results for go-tests

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#1627]
It would be great to have junit/xunit style test results output for go-test.

There are several  libraries that do this.
https://github.com/jstemmer/go-junit-report

There is a proposal to add `-json` output flag to gotest
https://github.com/golang/go/issues/2981

@sebastienvas @yutongz

**Comment by hklai** [comment]
I believe this has been done as those results are used to populate https://k8s-testgrid.appspot.com/istio-daily
