### ISSUE TITLE
Jwt authentication does not work when deploying Istio with any CA (e.g. Vault) other than Citadel

### ISSUE THREAD

**Issue by pitlv2109** [istio/istio#16274]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
Jwt authentication does not work when deploying Istio with any CA (e.g. Vault) other than Citadel. Response code is 503, instead of the expected 200 or 401. This is strange because Jwt authentication and (m)TLS should be independent of each other. I tested using fresh clusters. I couldn't get any logs from the proxy. Hopefully this is a false alarm.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Steps to reproduce the bug**
Deploy Istio with Vault, then deploy 2 workloads. Apply some jwt policy on one workload and send requests from the other to this one.

The other option is to run modify the current jwt test by changing the setup config (https://github.com/istio/istio/blob/master/tests/integration/security/authn/jwt/main_test.go#L35) to use Vault helm values (can be found at the sds_vault_flow_test).

**Comment by yangminzhu** [comment]
If this is P0, it would be 1.3 blocker, cc @rlenglet 

@pitlv2109 could you provide the istio install yaml that could be used to reproduce the issue?

**Comment by pitlv2109** [comment]
@yangminzhu I think the easiest way to test with Vault is just to use the integration test. Otherwise, you can try to deploy Istio with this https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/example-values/values-istio-example-sds-vault.yaml

**Comment by yangminzhu** [comment]
@pitlv2109 could you provide the full generated yaml? Just to make sure we can reproduce it in the same environment. Thanks.

**Comment by rlenglet** [comment]
@pitlv2109 @yangminzhu 
What is the status of Vault support in Istio 1.2? Is this issue a regression?

**Comment by pitlv2109** [comment]
@rlenglet Not sure about Vault; @lei-tang should have more info. This might be a false alarm, I'll test it further.

**Comment by lei-tang** [comment]
Vault CA is supported in Istio 1.2. Vault CA signs the certificates for workload sidecars, which are not related to the JWT authentication.

**Comment by pitlv2109** [comment]
False alarm. Thanks Yangmin for the help,
