### ISSUE TITLE
Automatic detection/tracking of Envoy deprecation

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#16275]
Process: we need to track Envoy deprecation pro-actively in our tests so we can address them timely:
https://www.envoyproxy.io/docs/envoy/latest/intro/deprecated

Currently Envoy emits warnings similar to this:
[2019-02-21 15:21:07.272][15][warning][misc] [external/envoy/source/common/protobuf/utility.cc:129] Using deprecated option 'envoy.api.v2.listener.Filter.config'. This configuration will be removed from Envoy soon. Please see https://github.com/envoyproxy/envoy/blob/master/DEPRECATED.md for details.

Can we have an automated tests option that enables Envoy log warning and fails the tests/opens  issues for deprecations?

**Comment by alyssawilk** [comment]
https://github.com/envoyproxy/envoy/issues/7548 may help with this: plan of record is to have a build option to make warnings fatal, which would make picking them up quite easy if you're willing to run one build with the build option flipped?

**Comment by jwendell** [comment]
Attempt to fix this: https://github.com/istio/istio/pull/17599

**Comment by jwendell** [comment]
Now that #17599 is merged, we just need a CI job that makes use of this flag.
