### ISSUE TITLE
gRPC https service requires declare service port as "https"

### ISSUE THREAD

**Issue by incfly** [istio/istio#16282]
**Bug description**

gRPC server serving traffic in https, client verifies it using shared trusted CA. This setup with Istio requires declaring service port as "https-xxx" rather than "grpc", otherwise it does not work.

The reason is because, I believe

- `HTTPS` we setup tcp proxy to pass through bytes.
- 'gRPC' is treated as http and using HCM. Envoy trying to proxy the TCP connection and does not work.

Solution

- Don't do anything. Add documentation to istio.io, (it's not obvious from istio.io and seems requiring more Istio specific knowledge to figure this out)
- This is a random idea. We can add a tls inspector in oubound client listener and dispatch request to tcp proxy filter chain if it's already tls.
- Not sure how this works with under new better networking / http, tcp inspector. Would this problem no longer exists? @silentdai to confirm.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ X] Docs
[ ] Installation
[ X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by silentdai** [comment]
I don't understand the end-2-end flow a grpc protocol. The bottom line is inbound listener, outbound cluster should act consistently in terms of alpn and auth filters. 
Need to explore how istio can add value if user specify protocol name "grpc"

**Comment by esnible** [comment]
Related: https://github.com/istio/istio/issues/14909 which was closed, perhaps prematurely.

**Comment by robinbraemer** [comment]
To throw in some question:
- Is this being worked on?
- Why does the istio `grpc` protocol even exist if it's not working or how should we use this type of protocol?

**Comment by esnible** [comment]
Re-opening because the policy bot closed it after I triaged it.  My triage should be considered activity from an Istio team member.

**Comment by hzxuzhonghu** [comment]
same for http2
