### ISSUE TITLE
istio without internet

### ISSUE THREAD

**Issue by dhineshbabuelango** [istio/istio#16293]
Hi All, 
we are using istio in EKS. We are trying to install istio without internet access. 
So we have downloaded all the images and put in ECR and changed the istio configuration file to take the image from ECR. we were able to to do that but not able to start the istio-proxy getting the below error.

Events:
  Type     Reason     Age                     From                                                     Message
  ----     ------     ----                    ----                                                     -------
  Normal   Scheduled  7m24s                   default-scheduler                                        Successfully assigned istio-system/istio-ingressgateway-6bddcf5766-zzzwf to ip-10-76-38-42.ap-southeast-1.compute.internal
  Normal   Pulled     7m23s                   kubelet, ip-10-76-38-42.ap-southeast-1.compute.internal  Container image "XXXXXXXX.dkr.ecr.ap-southeast-1.amazonaws.com/istio-nodeagent:latest" already present on machine
  Normal   Created    7m23s                   kubelet, ip-10-76-38-42.ap-southeast-1.compute.internal  Created container
  Normal   Started    7m23s                   kubelet, ip-10-76-38-42.ap-southeast-1.compute.internal  Started container
  Normal   Pulled     5m58s (x5 over 7m23s)   kubelet, ip-10-76-38-42.ap-southeast-1.compute.internal  Container image "XXXXXXXX.dkr.ecr.ap-southeast-1.amazonaws.com/istio-proxy:latest" already present on machine
  Normal   Created    5m58s (x5 over 7m22s)   kubelet, ip-10-76-38-42.ap-southeast-1.compute.internal  Created container
  Warning  Failed     5m58s (x5 over 7m22s)   kubelet, ip-10-76-38-42.ap-southeast-1.compute.internal  Error: failed to start container "istio-proxy": Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"proxy\": executable file not found in $PATH": unknown
  Warning  BackOff    2m21s (x23 over 7m20s)  kubelet, ip-10-76-38-42.ap-southeast-1.compute.internal  Back-off restarting failed container

**Comment by DJDANNY123** [comment]
> Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: "proxy": executable file not found in $PATH": unknown

This seems to suggest the docker image for istio-proxy does not have the "proxy" executable in and the image has been mishandled, when importing images to ECR, was this automated or did you do this manually? 

I had a similar error from doing a docker save to create a .tar and then docker import instead of docker load, which has a surprisingly large difference/impact on the imported image.

**Comment by dhineshbabuelango** [comment]
Hi Dany, I downloaded the image from docker using Docker pull and then uploaded the images to ecr and changed the values in helm chart to point to ecr and started this

**Comment by DJDANNY123** [comment]
To get it into ECR did you docker tag the image to point to the ECR image and then docker push or did you docker export/docker save to a file and upload the file? 
docker export may have messed up your image as "The docker export command does not export the contents of volumes associated with the container."

I am unfamiliar with ECR but imagining it works like other image registries.

**Comment by dhineshbabuelango** [comment]
Yes, I first have to run docker tag and the run docker push to push the image to ECR.

1. Docker pull
2. Docker tag
3. Docker push

**Comment by howardjohn** [comment]
the sidecar doesn't have an executable named proxy. It runs `pilot-agent proxy ... ` I believe . so it seems the cmd/entry point got messed up maybe

**Comment by dhineshbabuelango** [comment]
Thanks John, I have found the issue, i have not updated the ECR image tag in the values file for that particular container, now its running but not in ready state. I am also seeing the below issues in galley and sidecar_injector 

[ec2-user@ip-10-76-11-201 istio]$ kubectl describe pod istio-galley-554bc46d86-wzmnw -n istio-system |grep -i warning |head -1
  Warning  FailedMount  62s (x10 over 5m17s)  kubelet, ip-10-76-38-42.ap-southeast-1.compute.internal  MountVolume.SetUp failed for volume "certs" : secrets "istio.istio-galley-service-account" not found
[ec2-user@ip-10-76-11-201 istio]$

But I could see the service account and secrets are created.

[ec2-user@ip-10-76-11-201 istio]$ kubectl get serviceaccount -n istio-system |grep galley
istio-galley-service-account             1         7m22s
[ec2-user@ip-10-76-11-201 istio]$ kubectl get secrets -n istio-system |grep galley
istio-galley-service-account-token-ssgjv             kubernetes.io/service-account-token   3      9m27s
[ec2-user@ip-10-76-11-201 istio]$

Is it a recommended approach to use istio without internet?

**Comment by howardjohn** [comment]
You don't have the secret it references, you should have
```
istio-galley-service-account-token-pgjk6             kubernetes.io/service-account-token   3      2d23h
istio.istio-galley-service-account                   istio.io/key-and-cert                 3      10h
```

Is citadel running properly?

**Comment by dhineshbabuelango** [comment]
Thanks John, it was citadel issue, citadel was not running properly, i restarted now all the services running fine, But is it a recommended approach to use istio without internet as we have new releases very frequently in istio.

Again, thanks for your help

**Comment by howardjohn** [comment]
I haven't heard of other users doing it, but I'm sure there are many others that do it. it should just work if you get all the images loaded properly

**Comment by howardjohn** [comment]
Issue seems resolved, feel free to reopen if not

**Comment by ormam** [comment]
hello, can you please share your configuration files for noninternet access environments?
It would be amazing!
or if you can create a helm chart for it
