### ISSUE TITLE
Remote istio-pilot gets connected slowly

### ISSUE THREAD

**Issue by xiaozhongliu** [istio/istio#16295]
**Bug description**
I have two clusters:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Cluster A in one region - data plane
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Cluster B in another region - control plane
A joins B to form a single control plane topology. There is 200ms delay between the two regions.

All pods of apps deployed in A takes about 10 minutes in average to succeed connecting the remote istio-pilot in B.
Finally all pods will succeed. But it's really slow.

Sidecar log:
![image](https://user-images.githubusercontent.com/17674404/63096212-e984a380-bf9f-11e9-8483-2f8daa7829bf.png)

Note that when a pod of an app is continuously failing connecting the pilot, I can make successful requests to the pilot from a succeeded pod of the same app.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Remote istio-pilot gets quickly connected.

**Steps to reproduce the bug**
None.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```bash
# istioctl version --remote
client version: version.BuildInfo{Version:"1.1.13", GitRevision:"473d9b376acf780fa1929eaf44dc65a3049d3765", User:"root", Host:"0f070bc0-b950-11e9-acd3-2edd5d7d4cc8", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.12"}
citadel version: version.BuildInfo{Version:"1.1.8", GitRevision:"145b18a441045d6fad33d7916380d8642c7bf21d-dirty", User:"root", Host:"11387264-87af-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.7-14-g145b18a"}
ingressgateway version: version.BuildInfo{Version:"1.1.8", GitRevision:"145b18a441045d6fad33d7916380d8642c7bf21d", User:"root", Host:"11387264-87af-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.7-14-g145b18a"}
sidecar-injector version: version.BuildInfo{Version:"1.1.8", GitRevision:"145b18a441045d6fad33d7916380d8642c7bf21d-dirty", User:"root", Host:"11387264-87af-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.7-14-g145b18a"}

# kubectl version
Client Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-aliyun.1", GitCommit:"4304b26", GitTreeState:"", BuildDate:"2019-04-08T08:50:29Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-aliyun.1", GitCommit:"8cb561c", GitTreeState:"", BuildDate:"2019-04-22T11:34:20Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
Aliyun ACK, Operator

**Environment where bug was observed (cloud vendor, OS, etc)**
Aliyun ACK, CentOS 7

**Comment by howardjohn** [comment]
It doesn't look like its failing to connect to pilot, just pilot fails to send LDS response. This can be either due to Envoy not sendin the LDS request or Pilot not sending the LDS response. I suspect its the former. I have seen some cases like this when Envoy was overloaded (high memory usage) it would not send lds request
