### ISSUE TITLE
Move attribute producing adapters to the new adapter model.

### ISSUE THREAD

**Issue by geeknoid** [istio/istio#1630]
@geeknoid commented on [Fri Oct 20 2017](https://github.com/istio/old_mixer_repo/issues/1477)

We need to move the APAs to the new adapter model and then proceed to expunge all old adapter model code from the codebase.

---

@jmuk commented on [Fri Oct 20 2017](https://github.com/istio/old_mixer_repo/issues/1477#issuecomment-338269609)

blocking #1411

---

@guptasu commented on [Fri Oct 27 2017](https://github.com/istio/old_mixer_repo/issues/1477#issuecomment-340047711)

This will achieve the following requirements as mentioned in the old bug (#534) around this task 
* type-checking on inputs to Generate (perhaps figure out how to wire in populated struct of inputs, etc.)
* type-checking on outputs from Generate (perhaps pass in AttributeDefinitions for controlling outputs, etc.)

---

@guptasu commented on [Fri Oct 27 2017](https://github.com/istio/old_mixer_repo/issues/1477#issuecomment-340060349)

https://docs.google.com/document/d/1r_yJdZCa1QzJeh5qnoNRF3KmuhQVcAQ4CEFEeWtH6N0/edit#heading=h.x9snb54sjlu9 defines the plan.
#1522 is a followup item (how to communicate the used attributes by the adapter) that might change the signature of the interface.

**Comment by guptasu** [comment]
Done
