### ISSUE TITLE
Need test to exercise Envoy version n with Pilot version n+1

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#16306]
During an upgrade, users will have a newer pilot than envoy for some (or maybe a long) period of time. During this time, if pilot sends any config that the proxy doesn't understand, it will blow up.

We need to have a test case for this. It should be fairly simple, just set `proxyImage` and have an extra run of some the reachability tests for example.

**Comment by howardjohn** [comment]
If someone starts working on this please comment, I may work on it when I find some time if not

**Comment by utako** [comment]
@howardjohn have you gotten a chance to work on this yet? if not, i can take this.

**Comment by howardjohn** [comment]
I haven't done anything, except deploying envoy n-1 in my own cluster an manually testing

**Comment by utako** [comment]
i could supply a N-1 proxy version to `make docker push`, and run another CI job that will build the envoy N-1 version istio component images and run a small subset of tests against those. does that sound reasonable?

**Comment by howardjohn** [comment]
@utako I think the problem is we cannot build an envoy N-1 version in CI. For each PR we the repo gets `git cloned` at the given sha - we don't have access to the old code I think. I think what we could do is instead pull down from release-1.2-latest-daily (on release-1.3 branch) and that could work. So maybe we can just change one of the tests (in postsubmit only) to pass something like `--proxyImage=istio/proxyv2:n-1` (not sure what the flag is, if there is one).

I think its ok if the postsubmit tests aren't don't fully hermetically and are pulling down published images, just not presubmit

**Comment by howardjohn** [comment]
I bumped this to P1 because its not terribly onerous to have these tests done manually per release anyways

@carolynhu does the upgrade test you are working on exercise this at all? I think it should, but haven't looked at the logic in the test

**Comment by carolynhu** [comment]
@howardjohn no, the upgrade script do not have this logic.

**Comment by howardjohn** [comment]
But when we upgrade we will have new control plane and old proxy for some
period of time right? Do we restart all the proxies as well?
