### ISSUE TITLE
Istio retry not working as expected

### ISSUE THREAD

**Issue by Parvathy-Geetha** [istio/istio#16327]
**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Retries to work and 15 GET requests to be sent to the unavailable service.

**Steps to reproduce the bug**

- Deploy the httpbin sample app
- Apply the following rety rule.
`apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: retry
spec:
  hosts:
    - httpbin
  http:
  - route:
    - destination:
        host: httpbin
    retries:
      attempts: 15         # 2
      perTryTimeout: 1s   # 3
      retryOn: "5xx"`
- curl to the httpbin.pgeetha-bookinfo:8000/status/503 from any other service with side car injected.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
client version: 1.2.2
citadel version: 1.2.2
galley version: 1.2.2
ingressgateway version: 1.2.2
pilot version: 1.2.2
policy version: 1.2.2
sidecar-injector version: 1.2.2
sidecar-injector version: 1.2.2
sidecar-injector version: 1.2.2
telemetry version: 1.2.2

**How was Istio installed?**
Using helm

**Comment by dgn** [comment]
Can you enclose your config in triple backticks (ie ` ``` `)? It's hard to figure out if this might be related to wrong indentation. Note that the `retries:` block should be on the same indentation level as `route:`

**Comment by codingmaths** [comment]
Hi Have used below virtual service config still getting intermittent 503s
`apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: shelf-stg-vs
spec:
  hosts:
  - shelf.stg.xyz.com
  http:
  - route:
    - destination:
        host: shelf.stg.xyz.com
    retries:
      attempts: 4
      perTryTimeout: 1s
      retryOn: "503"`

**Comment by Parvathy-Geetha** [comment]
@dgn Updated the config. I am using retries at the same level.

**Comment by dgn** [comment]
I can not reprodoce this, neither on master nor on 1.2.2. Can you post relevant parts of your proxy config?

Try:
`istioctl pc route <CLIENT_POD_NAME> -o json`

You should see something like this:
```
        "virtualHosts": [
            {
                "name": "httpbin.default.svc.cluster.local:80",
                "domains": [
                    "httpbin.default.svc.cluster.local",
                    "httpbin.default.svc.cluster.local:80"
                ],
                "routes": [
                    {
                        "match": {
                            "prefix": "/"
                        },
                        "route": {
                            "cluster": "outbound|80||httpbin.default.svc.cluster.local",
                            "timeout": "0s",
                            "retryPolicy": {
                                "retryOn": "5xx",
                                "numRetries": 15,
                                "perTryTimeout": "1s",
                                "retryHostPredicate": [
                                    {
                                        "name": "envoy.retry_host_predicates.previous_hosts"
                                    }
                                ],
                                "hostSelectionRetryMaxAttempts": "5"
                            },
                            "maxGrpcTimeout": "0s"
...
```
