### ISSUE TITLE
Citadel: Certificate is NOT authorized to sign other certificate

### ISSUE THREAD

**Issue by shantanookirtane** [istio/istio#16337]
I am trying to install istio citadel using https://istio.io/docs/tasks/security/plugin-ca-cert/

I have below files with me

ca-cert.pem - public key of the certificate I requested ca-key.pem - private key of the certificate I requested

Note: These certifcates are created off of the below root-ca.pem

root-ca.pem - Root public certificate cert-chain.pem - intermediate public certs

I have followed the exact steps mentioned in above link.

When I run below command

`helm template install/kubernetes/helm/istio --name istio --namespace istio-system -x charts/security/templates/deployment.yaml \
--set global.mtls.enabled=true --set security.selfSigned=false > $HOME/citadel-plugin-cert.yaml
kubectl apply -f $HOME/citadel-plugin-cert.yaml`

I see the citadel instance status goes to Error.

When I looked at the logs I see below

`2019-08-16T05:18:29.125157Z info    The custom-defined DNS name list is [istio-pilot-service-account.istio-system:istio-pilot.istio-system]
2019-08-16T05:18:29.127037Z info    ControlZ available at 127.0.0.1:9876
2019-08-16T05:18:29.128213Z info    Use certificate from argument as the CA certificate
2019-08-16T05:18:29.134411Z error   Failed to create an Citadel (error: certificate is not authorized to sign other certificates)`

Cloud Details
Azure
K8s version: 1.13.5
Istio version: 1.2.2

**Comment by sumitkgaur** [comment]
Do we have any triage on this issue. Facing same issue after upgrade from 1.1.7 to 1.2.7 :-(

**Comment by sumitkgaur** [comment]
same issue with 1.2.2
