### ISSUE TITLE
Port conflict on egress when ALLOW_ALL is used

### ISSUE THREAD

**Issue by couniojc** [istio/istio#16331]
**Bug description**

We have a ElasticSearch service is running inside the cluster (outside of the mesh) on http on port 9200, port is named 'http' in the service. ALLOW_ALL is activated for egress. When a request is sent to an external url on https also on port 9200, the request responds :
curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number

If the port of the service is renamed to 'https' (even if it serves only http), it works properly

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[X] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

The call to an external url should work irrespective of the ports used on the cluster and how they are named (especially when they follow Istio naming convention)

**Steps to reproduce the bug**

- Have a service running a (eg ElasticSearch) running on port 9200 and named 'http'
- Have ALLOW_ALL mode set for egress
- Create a 'sleep' pod on a namespace with istio activated (so the istio-proxy is set)
- curl https://myexternalurl:9200
- It answers '(35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number'
- rename the service name to 'https'
- curl https://myexternalurl:9200
- It is working

We have similar issues on other standard ports such as 6379 for Redis. We used to have the same issues with https on port 443, but it is gone with upgrade to 1.2.x

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

client version: version.BuildInfo{Version:"1.1.2", GitRevision:"2b1331886076df103179e3da5dc9077fed59c989", User:"root", Host:"35adf5bb-5570-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.1"}
citadel version: version.BuildInfo{Version:"1.2.4", GitRevision:"c562694ea6e554c2b60d12c9876d2641cfdd917d-dirty", User:"root", Host:"418fcd4e-b951-11e9-a7c2-029eefb01290", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.2.3"}
galley version: version.BuildInfo{Version:"1.2.4", GitRevision:"c562694ea6e554c2b60d12c9876d2641cfdd917d-dirty", User:"root", Host:"418fcd4e-b951-11e9-a7c2-029eefb01290", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.2.3"}
ingressgateway version: version.BuildInfo{Version:"94746ccd404a8e056483dd02e4e478097b950da6-dirty", GitRevision:"94746ccd404a8e056483dd02e4e478097b950da6-dirty", User:"root", Host:"ubuntu", GolangVersion:"go1.12.7", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.2.4"}
nodeagent version: version.BuildInfo{Version:"", GitRevision:"", User:"", Host:"", GolangVersion:"", DockerHub:"", BuildStatus:"", GitTag:""}
nodeagent version: version.BuildInfo{Version:"", GitRevision:"", User:"", Host:"", GolangVersion:"", DockerHub:"", BuildStatus:"", GitTag:""}
nodeagent version: version.BuildInfo{Version:"", GitRevision:"", User:"", Host:"", GolangVersion:"", DockerHub:"", BuildStatus:"", GitTag:""}
nodeagent version: version.BuildInfo{Version:"", GitRevision:"", User:"", Host:"", GolangVersion:"", DockerHub:"", BuildStatus:"", GitTag:""}
nodeagent version: version.BuildInfo{Version:"", GitRevision:"", User:"", Host:"", GolangVersion:"", DockerHub:"", BuildStatus:"", GitTag:""}
pilot version: version.BuildInfo{Version:"1.2.4", GitRevision:"c562694ea6e554c2b60d12c9876d2641cfdd917d-dirty", User:"root", Host:"418fcd4e-b951-11e9-a7c2-029eefb01290", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.2.3"}
policy version: version.BuildInfo{Version:"1.2.4", GitRevision:"c562694ea6e554c2b60d12c9876d2641cfdd917d-dirty", User:"root", Host:"418fcd4e-b951-11e9-a7c2-029eefb01290", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.2.3"}
sidecar-injector version: version.BuildInfo{Version:"1.2.4", GitRevision:"c562694ea6e554c2b60d12c9876d2641cfdd917d-dirty", User:"root", Host:"418fcd4e-b951-11e9-a7c2-029eefb01290", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.2.3"}
telemetry version: version.BuildInfo{Version:"1.2.4", GitRevision:"c562694ea6e554c2b60d12c9876d2641cfdd917d-dirty", User:"root", Host:"418fcd4e-b951-11e9-a7c2-029eefb01290", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.2.3"}

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-19T22:13:37Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.10-eks-f12431", GitCommit:"f12431e9d92fa990fbbc2b52006351d381bd4bed", GitTreeState:"clean", BuildDate:"2019-07-26T01:16:21Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**

Using Helm Chart

**Environment where bug was observed (cloud vendor, OS, etc)**

EKS cluster

**Comment by howardjohn** [comment]
Opened https://github.com/istio/istio/issues/16458 to track this and consildate a few issues. Thanks for the report!
