### ISSUE TITLE
Incomplete Documentation: Custom Ingress Gateway + Cert-Manager

### ISSUE THREAD

**Issue by eyeezzi** [istio/istio#16369]
**Describe the feature request**
Improve the documentation of [Deploy a Custom Ingress Gateway Using Cert-Manager](https://istio.io/blog/2019/custom-ingress-gateway/). In step 4, it states that *"Make a note of the value of secretName since a future step requires it"*, but the secret is not used in any future steps. 

**Describe alternatives you've considered**
To my understanding, the certificate *secret* generated by Cert-Manager is supposed to be manually mounted in the *istio-ingressgateway* pod, so that it can be referenced in the `tls` section of a `Gateway` resource. The secret will only be automatically mounted if it is exactly named `istio-ingressgateway-certs` according to [here](https://istio.io/docs/tasks/traffic-management/ingress/secure-ingress-mount/#configure-a-tls-ingress-gateway-with-a-file-mount-based-approach). Including this important detail would have saved me a lot of time.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
It looks like this is actually done in step 6 already - maybe fixed since this issue. If you want to make this more clear a PR is welcomed, but generally blog posts are not changed much after they are published
