### ISSUE TITLE
grpc lb not working

### ISSUE THREAD

**Issue by inewlife** [istio/istio#16364]
**Bug description**
I have two service client and server deploy on k8s with auto inside istio,grpc communication between two service. many-to-many, I found that there was no load balance on the client access server.Is it not configurable? 
**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[* ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
What do you mean by "no load balancing"? Do all requests go to one instance instead of round robin? Do requests fail entirely? Is this unary calls or streaming?

**Comment by inewlife** [comment]
@howardjohn yes,I mean all requests go to one instance instead of round robin
I use the host name which  is service name, but my VirtualService host is my gateway host 
this is my wrong config
`
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: nlp-grammar-route
  namespace: ai
  resourceVersion: '2674981'
  generation: 17
spec:
  hosts:
    - grammar.sr.cvte.cn
  gateways:
    - grpc-grammar-gateway
  http:
    - match:
        - uri:
            regex: .*
      route:
        - destination:
            host: grammar
            port:
              number: 21012
  tcp: ~
  tls: ~
`

Then I use service config host name to VirtualService host 
And now It's ok 
`
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: nlp-grammar-route
  namespace: ai
  resourceVersion: '2674981'
  generation: 17
spec:
  hosts:
    - grammar
  gateways:
    - grpc-grammar-gateway
  http:
    - match:
        - uri:
            regex: .*
      route:
        - destination:
            host: grammar
            port:
              number: 21012
  tcp: ~
  tls: ~
`

**Comment by howardjohn** [comment]
Yes the host should be the host of the Service, not gateway. Glad you got it resolved
