### ISSUE TITLE
Building istio fails

### ISSUE THREAD

**Issue by asridharan** [istio/istio#1636]
OS: Mac OS X :
```
System Software Overview:

      System Version: OS X 10.11.4 (15E65)
      Kernel Version: Darwin 15.4.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: Avinash’s MacBook Pro
      User Name: Avinash Sridharan (asridharan)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 1 day 6:48
```

Bazel:
```  
bazel version
Build label: 0.2.1-homebrew
Build target: bazel-out/local_darwin-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Apr 1 00:35:17 2016 (1459470917)
Build timestamp: 1459470917
Build timestamp as int: 1459470917
```
Getting the following error when I compile from the `istio` source directory.

make build
bazel  build  //...
ERROR: package contains errors: .
ERROR: no such package '@io_bazel_rules_go//go': error loading package 'external': Could not load //external package.
INFO: Elapsed time: 0.084s
make: *** [build] Error 1
Avinashs-MBP:istio asridharan$
```
SHA:  12b89fddd9124014b6bd5cb899301b38482e7c6f
<!--
Please see https://istio.io/troubleshooting for potential workarounds.
Please add the correct labels and epics (and priority and milestones if you have that information)
-->

**Comment by dpacierpnik** [comment]
Hi,
We also haven't managed to build Istio directly on MacOS, however we've managed to build it using Docker Tools (it does not work with Docker native driver for MacOS because of lack of support for AUFS) and Docker image with Ubuntu. We just start the container in which we build Istio and publish image to docker registry. Maybe you can also try this approach.

Cheers,
Damian

**Comment by geeknoid** [comment]
You need a newer version of Bazel. I currently use:

Build label: 0.7.0-homebrew
Build target: bazel-out/darwin_x86_64-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Oct 19 09:12:48 2017 (1508404368)
Build timestamp: 1508404368
Build timestamp as int: 1508404368
