### ISSUE TITLE
unable to apply multiple certificates in istio-ingressgateway while hosting multiple site using same single gateway

### ISSUE THREAD

**Issue by ngbit95** [istio/istio#16366]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

as mentioned in offical documnetation https://archive.istio.io/v1.1/docs/tasks/traffic-management/secure-ingress/sds/
I followed same procedure to host mult-site using multiple certificate but failed to apply both.
for ex:-

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
name: gateway
spec:
selector:
istio: ingressgateway # use Istio default gateway implementation
servers:

port:
number: 80
name: http-abc
protocol: HTTP
tls:
httpsRedirect: true # sends 301 redirect for http requests
hosts:
"abc.com"
port:
number: 443
name: https-abc
protocol: HTTPS
tls:
mode: SIMPLE
credentialName: "abc-credential"
hosts:
"abc.com"
port:
number: 80
name: http-xyz
protocol: HTTP
tls:
httpsRedirect: true # sends 301 redirect for http requests
hosts:
"xyz.com"
port:
number: 443
name: https-xyz
protocol: HTTPS
tls:
mode: SIMPLE
credentialName: "xyz-credential"
hosts:
"xyz.com"
both the certificates are uploaded in istio-system namespace as TLS/secret but it can only works for first one i.e abc-credential and unable to works for xyz-credential.
Please let me know if anyone find solution for it.

**Comment by incfly** [comment]
https://istio.io/news/2019/announcing-1.1-eol/ 1.1 is deprecated. Please file bug separately if you observe this in 1.2

/cc @JimmyCYJ  just FYI.
