### ISSUE TITLE
Ingress gateway not accepting rps(request per second) more than 1024

### ISSUE THREAD

**Issue by sujithvs74** [istio/istio#16377]
I am using Istio 1.1.8 which is installed with helm charts. I have noticed an issue with ingress gateway. Ingress gateway not accepting rps(request per second) more than 1024 with one ingress gateway. Is there any such limit in istio sidecar containers.

`outbound_.80_._.sleep.bar.svc.cluster.local::default_priority::max_connections::1024
outbound_.80_._.sleep.bar.svc.cluster.local::default_priority::max_requests::1024`

How can I update above limits in Istio.

**Comment by howardjohn** [comment]
See https://istio.io/docs/reference/config/networking/v1alpha3/destination-rule/#ConnectionPoolSettings-HTTPSettings (http2MaxRequests) and https://istio.io/docs/reference/config/networking/v1alpha3/destination-rule/#ConnectionPoolSettings-TCPSettings (maxConnections)

Note this does not mean you are limited to 1024 RPS, it means you can only have 1024 parallel connections/requests

**Comment by sujithvs74** [comment]
@howardjohn I already tried with http2MaxRequests and maxConnections, I could see above values got updated. But still ingress gateway (only one pod) not accepting more then 1024 connections.

`outbound|8080||k8sloadtest.prf-ns.svc.cluster.local::default_priority::max_connections::2048
outbound|8080||k8sloadtest.prf-ns.svc.cluster.local::high_priority::max_connections::1024
outbound_.8080_._.k8sloadtest.prf-ns.svc.cluster.local::default_priority::max_connections::2048
outbound_.8080_._.k8sloadtest.prf-ns.svc.cluster.local::high_priority::max_connections::1024`

**DestinationRule config**
`apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: k8sloadtest-http
spec:
  host: k8sloadtest
  trafficPolicy:
    connectionPool:
      http:
        http2MaxRequests: 2048
      tcp:
        maxConnections: 2048`

**Comment by howardjohn** [comment]
```
outbound|8080||k8sloadtest.prf-ns.svc.cluster.local::default_priority::max_connections::2048 
```

Looks good to me. I think you can ignore the one with "high_priority", as far as I know we don't support it so envoy just puts the default of 1024 there -- but it doesn't mean anything.

**Comment by howardjohn** [comment]
Is this still a problem?

**Comment by chetan061292** [comment]
I am facing the same problem. Any help would be appreciated.
