### ISSUE TITLE
The ValidatingWebhook failed, remote error: tls: bad certificate

### ISSUE THREAD

**Issue by zqzzq** [istio/istio#16374]
**Bug description**
when I apply a file to k8s：
```
# kubectl apply -f bookinfo-gateway.yaml 
Error from server (InternalError): error when creating "bookinfo-gateway.yaml": Internal error occurred: failed calling admission webhook "pilot.validation.istio.io": Post https://istio-galley.istio-system.svc:443/admitpilot?timeout=30s: x509: certificate has expired or is not yet valid
```
Then in galley's logs I find this error:
```
2019-08-19T07:50:59.868505Z     info    http: TLS handshake error from 10.xxx.192:41246: remote error: tls: bad certificate
2019-08-19T07:57:01.461182Z     info    http: TLS handshake error from 10.xxx.192:45590: remote error: tls: bad certificate
```
The strange thing is that I cann't find the ip 10.xxx.192 in any pod or svc. In addition, The MutatingWebhook which has the same caBundle as ValidatingWebhookConfiguration can work normally. Is there somebody can help me? Very thanks!

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
the ValidatingWebhook can work normally.
**Version (include the output of `istioctl version --remote` and `kubectl version`)**
the istio is 1.1.2
the k8s version:
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1+icp-ee", GitCommit:"5803c3b1f9422c43a963e0610b3a4cad565e127e", GitTreeState:"clean", BuildDate:"2018-09-04T09:29:02Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1+icp-ee", GitCommit:"5803c3b1f9422c43a963e0610b3a4cad565e127e", GitTreeState:"clean", BuildDate:"2018-09-04T09:29:02Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
**How was Istio installed?**
by istio-demo.yaml

**Comment by zqzzq** [comment]
solved, closing this

**Comment by yinpengchong** [comment]
@zqzzq I met the same error and don't know how to resolve it. Could you please tell me how you fixed. thank you very much.

**Comment by zqzzq** [comment]
@yinpengchong In my case this is because the root certificate expired, delete istio-ca-secret and istio.istio-galley-service-account and regenerate them, then delete galley pod to reload them.

**Comment by yinpengchong** [comment]
@zqzzq thanks a lot!!  I resolved this issue according to your suggestion

**Comment by christian-posta** [comment]
For others that may be using AWS EKS, you may get this similar looking error because of: https://github.com/istio/istio/issues/24997

**Comment by devdattakulkarni** [comment]
@zqzzq I am getting this error in another mutatingwebhook (not istio). Would you mind sharing details about how you investigated the issue and how did you determine that the root certificate had expired?
