### ISSUE TITLE
istio cni tproxy

### ISSUE THREAD

**Issue by grinb** [istio/istio#16387]
Hi,
Im using istio cni 1.2.3
I tried to use it with tproxy ( in istio config map) .
I got error in istio=proxy log:
"Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?)".
And also see in kublet log in the specific node that istio-iptables.sh got parameter -m to redirect and not tproxy .
Is tproxy should work with cni?

**Comment by jaxklag** [comment]
Hello,
Me too, i wonder how to activate TPROXY with Istio CNI.
