### ISSUE TITLE
1.2.4 proxy version incorrect (94746cc-dirty)

### ISSUE THREAD

**Issue by dhineshbabuelango** [istio/istio#16396]
Hi All,
We are using istio in AWS EKS. I recently tried to upgrade the istio version from 1.2.2 to 1.2.4 following the steps mentioned in the below link. 

https://istio.io/docs/setup/kubernetes/upgrade/steps/

After the upgrade, I was able to deploy application and the normal sanity test check shows everything is running as expected. But if i run istioctl version, i am getting like below for ingress adn egress like "DIRTY"

[ec2-user@ip-10-76-11-201 ~]$ istioctl version
client version: 1.2.4
admin-ingressgateway version:
citadel version: 1.2.4
egressgateway version: 94746ccd404a8e056483dd02e4e478097b950da6-dirty
galley version: 1.2.4
ingressgateway version: 94746ccd404a8e056483dd02e4e478097b950da6-dirty
pilot version: 1.2.4
policy version: 1.2.4
sidecar-injector version: 1.2.4
telemetry version: 1.2.4

[ec2-user@ip-10-76-11-201 ~]$ istioctl proxy-status
NAME                                                   CDS        LDS        EDS               RDS          PILOT                            VERSION
admin-ingressgateway-69c6d67499-s74sb.istio-system     SYNCED     SYNCED     SYNCED (50%)      NOT SENT     istio-pilot-7487f765d9-kwxbh     1.0-dev
isam-config-7578557d4d-9qfhb.apps                      SYNCED     SYNCED     SYNCED (50%)      SYNCED       istio-pilot-7487f765d9-kwxbh     1.0-dev
istio-egressgateway-69d5769c-2gr5b.istio-system        SYNCED     SYNCED     SYNCED (100%)     NOT SENT     istio-pilot-7487f765d9-kwxbh     1.0-dev
istio-ingressgateway-677c66978b-cksks.istio-system     SYNCED     SYNCED     SYNCED (100%)     NOT SENT     istio-pilot-7487f765d9-kwxbh     1.0-dev
[ec2-user@ip-10-76-11-201 ~]$

**Comment by howardjohn** [comment]
When we built the 1.2.4 proxy we made a mistake setting the correct version number, which is why you see that instead of 1.2.4. Its just a version label issue, everything else should be fine. In a couple days we are releasing a fix for it and a couple other things

**Comment by dhineshbabuelango** [comment]
Thanks John for the input. 
Because in istio.io we found 1.2.4 we tried to upgrade our environment. is there any way we can find an version  to be production ready before we try to upgrade.

Also istioctl proxy-status shows something SYNCED (50%), will that be an issue.

**Comment by howardjohn** [comment]
no the synced thing is misleading, 50% is expected - we are removing it in the next release since it is confusing

**Comment by dhineshbabuelango** [comment]
Thanks John, one last question before we close this, I tried updating the sidecar using the script provided by istio, but I could see the below results, it says no change, i tried describing the pod, stil the pod was using 1.2.2 version only,

[ec2-user@ip-10-76-8-135 bin]$ export NS=apps
[ec2-user@ip-10-76-8-135 bin]$ DEPLOYMENT_LIST=$(kubectl -n $NS get deployment -o jsonpath='{.items[*].metadata.name}')
[ec2-user@ip-10-76-8-135 bin]$ export deployment_name=isam-config
[ec2-user@ip-10-76-8-135 bin]$ TERMINATION_GRACE_PERIOD_SECONDS=$(kubectl -n $NS get deployment "$deployment_name" -o jsonpath='{.spec.template.spec.terminationGracePeriodSeconds}')
[ec2-user@ip-10-76-8-135 bin]$ patch_string="{\"spec\":{\"template\":{\"spec\":{\"terminationGracePeriodSeconds\":$TERMINATION_GRACE_PERIOD_SECONDS}}}}"
[ec2-user@ip-10-76-8-135 bin]$ kubectl -n $NS patch deployment $deployment_name -p $patch_string
deployment.extensions/isam-config patched (no change)

**Comment by howardjohn** [comment]
To do a restart I suggest `kubectl rollout restart` rather than the script you used

**Comment by howardjohn** [comment]
The version will be fixed in 1.2.5, releasing soon, and we are working on a long term fix to ensure something like this cannot happen again
