### ISSUE TITLE
Missing prefix for INSTANCE_IPS

### ISSUE THREAD

**Issue by Jason-ZW** [istio/istio#16398]
**Bug description**
ISTIO auto inject env with `IstioMetaPrefix = "ISTIO_META_"` at bootstrap stage.
But discovery can not found IPS from node metadata, this because missing `ISTIO_META_` prefix when reading from metadata struct.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
master

**Comment by hzxuzhonghu** [comment]
`ISTIO_META_` this is for env var only. For node.meta, it should not include this prefix.

**Comment by Jason-ZW** [comment]
@hzxuzhonghu But this line will never get the `ISTIO_META_INSTANCE_IPS` isn't it? https://github.com/istio/istio/blob/master/pilot/pkg/model/context.go#L344

**Comment by hzxuzhonghu** [comment]
```
$ cat /etc/istio/proxy/envoy-rev2.json
{
  "node": {
    "id": "sidecar~10.32.0.16~sleep-6758c4cb78-gj4jg.default~default.svc.cluster.local",
    "cluster": "sleep.default",
    "locality": {
      
      
      
    },
    "metadata": {"CONFIG_NAMESPACE":"default","INCLUDE_INBOUND_PORTS":"","INSTANCE_IPS":"10.32.0.16","INTERCEPTION_MODE":"REDIRECT","ISTIO_PROXY_SHA":"istio-proxy:47e4559b8e4f0d516c0d17b233d127a3deb3d7ce","ISTIO_VERSION":"master-20190814-09-16","POD_NAME":"sleep-6758c4cb78-gj4jg","app":"sleep","istio":"sidecar","istio.io/metadata":{"ip":"10.32.0.16","labels":{"app":"sleep","pod-template-hash":"6758c4cb78"},"name":"sleep-6758c4cb78-gj4jg","namespace":"default"},"pod-template-hash":"6758c4cb78"}

```

It is `INSTANCE_IPS` here, should work well.

**Comment by Jason-ZW** [comment]
@hzxuzhonghu 
Form this PR line I think the original intent should be prefixed
https://github.com/istio/istio/pull/9688/files#diff-03c8888f03893e7e2ff9bc099c637e53R249

**Comment by hzxuzhonghu** [comment]
There is a bug there. I fixed it.

**Comment by Jason-ZW** [comment]
@hzxuzhonghu  Could you please give commit id, so that I can check that. Maybe it's my mistake because my istio-proxy using 1.2.0.

**Comment by Jason-ZW** [comment]
I'm going to close this issue. I'm going to try it again with the master. @hzxuzhonghu  Thanks a lot.
