### ISSUE TITLE
In the multiple control plane multi-cluster mesh as documented on istio.io, all the services are exposed by default.

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio#16406]
Following the [Networking WG meeting on 15-th of August 2019](https://docs.google.com/document/d/1xHy2jQ8oiwMponMVY2zJr2eUAmHW_Hi9JK42a7cg5Pc/edit#heading=h.2ju2wl4o5jbc): In the [multiple control plane multi-cluster mesh](https://istio.io/docs/setup/kubernetes/install/multicluster/gateways/) pattern, all the services are exposed by default. This is the behaviour as it is documented in the installation example.

There is a claim that it is a P0 bug, while in my opinion it is a feature of the pattern, it was implemented this way by design. The multi-cluster mesh by design designates a single _logical_ mesh spread between multiple _physical_ clusters, so it is reasonable to expect that all the services within a single logical mesh are exposed by default within the single mesh. The implementation of the pattern is explained in a https://github.com/istio/istio/issues/16406#issuecomment-523038974.

Since in the [multiple control plane multi-cluster mesh](https://istio.io/docs/setup/kubernetes/install/multicluster/gateways/) all the services are exposed by default and there is no control of the incoming traffic at the boundary of the cluster, it does not provide boundary protection (see [this blog post](https://github.com/istio/istio.io/pull/4776)). The question is how to fix this behaviour and what is the amount of effort required.

The requirements for the boundary protection:
1. the services should be not exposed unless explicitly configured to be exposed
1. there should be access control: which source principle (at least the identity of the consuming cluster) may access specific services in the  providing cluster
1. the access control must be enforced **at the boundary** (at the ingress gateway).

Proposed next steps:
1. Someone provides a design how to implement boundary protection for [multiple control plane multi-cluster mesh](https://istio.io/docs/setup/kubernetes/install/multicluster/gateways/) .
1. Someone provides estimation of effort for the required design.
1. If there is a significant effort to implement boundary protection for [multiple control plane multi-cluster mesh](https://istio.io/docs/setup/kubernetes/install/multicluster/gateways/) )(for example if fixing the bug would mean reimplementing the whole pattern), we should decide if it is worth to invest this effort, considering that we have [another pattern](https://github.com/istio/istio.io/pull/4776) that provides boundary protection and works today with Istio AS IS.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by vadimeisenbergibm** [comment]
In the dedicated control planes pattern (a.k.a multiple control planes, a.k.a. gateway connectivity), a passthrough ingress gateway is used. This gateway is a TCP passthrough proxy.
It does not perform TLS termination, it does not see the client certificate and cannot filter traffic by the source principal.
It sniffs the SNI value, replaces the `.global` suffix with `.svc.cluster.local` and directs the traffic to a cluster by the resulting name.

The following configuration is used for the passthrough ingress gateway:
```
{
    "name": "envoy.filters.network.sni_cluster"
},
{
     "name": "envoy.filters.network.tcp_cluster_rewrite",
     "config": {
            "cluster_pattern": "\\.global$",
            "cluster_replacement": ".svc.cluster.local"
      }
},
```

**Comment by vadimeisenbergibm** [comment]
@costinm @smawson @louiscryan @rshriram @andraxylia @sdake @linsun I have opened this issue following the Networking WG meeting on 15-th of August 2019. Your comments are welcome.

**Comment by vadimeisenbergibm** [comment]
^ @nmittler

**Comment by vadimeisenbergibm** [comment]
^ @frankbu

**Comment by vadimeisenbergibm** [comment]
Comments of @costinm:

> To answer your comments: Gateway provides a clear mechanism to control what hosts can be exposed, since Istio 1.1.

> Multicluster for multiple networks is using Gateway - configured in SNI-proxy mode. The SNI-proxy
port - just like any other port in the Gateway - should follow the same rules, and allow configuration
of which namespaces and services can be exposed.

> The control of the Gateway resides with the gateway admin - he can decides which ports and hosts are exposed, and which namespaces are allowed to bind to a gateway.

> Also "multiple control plane" has nothing to do with the issue - one or more control plane is not a factor.

> Neither is the number of clusters: even if you have a single cluster with just mesh expansion, the Gateway should still follow its own specification in exposing internal services via SNI-routing mode.

> The real bug is in Gateway implementation of SNI-proxy mode - which may be used in various topologies and for multicluster, but it is not specific to MC.

**Comment by vadimeisenbergibm** [comment]
@costinm please note that I am talking about the specific pattern, the one that appears at Istio.io: https://istio.io/docs/setup/kubernetes/install/multicluster/gateways/.

That specific pattern, as documented at istio.io, exposes all the services by default. Until someone documents how to expose nothing by default, this is what the Istio users will do.

**Comment by vadimeisenbergibm** [comment]
@costinm To provide more information: the pattern as documented at https://istio.io/docs/setup/kubernetes/install/multicluster/gateways/ uses a specific Istio installation, defined by the following helm values https://raw.githubusercontent.com/istio/istio/release-1.2/install/kubernetes/helm/istio/example-values/values-istio-multicluster-gateways.yaml.

It deploys the special passthrough ingress gateway configured as described in https://github.com/istio/istio/issues/16406#issuecomment-523038974.

When Istio users want to connect multiple clusters using Istio, they have the following choices: https://istio.io/docs/setup/kubernetes/install/multicluster/. None of the choices provides boundary protection. The users cannot know how to implement boundary protection until we document it on istio.io. In particular, if the users will use https://istio.io/docs/setup/kubernetes/install/multicluster/gateways/, they will expose all their services by default.

**Comment by mbanikazemi** [comment]
The issue of this being a bug or a feature seems to be mute for your purposes. What you have suggested, using a private gateway with an appropriate configuration and rbac or something along those lines will be what you need for selectively exposing services. This pattern is not documented and I think having it documented is fine. The current documentation can be updated to explicitly let the users know what they get.

**Comment by smawson** [comment]
A mesh exposing all services by default is an explicit design goal of a multicluster mesh. Another explicitly goal is that the details of clusters and networks is abstracted away so the user is only dealing with logical concepts of a mesh, a namespace, and a service. So exposure is intentionally limited to being about those concepts. You can expose services between namespaces, or block them from namespaces, but not expose them between clusters.

If we want to design a solution for boundary protection, we should have a discussion about how to support boundary protections. My strawman is that each mesh is by definition a boundary, so if you want to put boundaries around things those are two different meshes. But we should have that discussion in a feature request for supporting boundary protections, not in an issue about a particular implementation of a mesh. So this one should be closed, and please open a feature request for adding boundary protections to Istio.

**Comment by costinm** [comment]
@smawson  there are few different issues: 

- RBAC rules should be able to use the 'cluster' as one of the labels. I don't see any reason why it shouldn't, among all the other labels it supports already. We expose network as an attribute, and should be possible to use that in RBAC rules as well.

- as long as Gateway is used to expose resources between networks, the implementation must follow the spec - and that already include a mechanism to control what is exposed. The SNI filtering we use  is in no way specific to multi-cluster or specific install patterns - even if I have a single cluster, or just a raw-VM-only Istio with no clusters at all - it should still work. 

- the actual doc we have is an example of how to configure Istio - not a spec on how it should be configured.

I agree that exposing all services by default is an explicit goal and should be supported - but that doesn't mean Gateway should not allow control over what is exposed. You may use internal load balancers or dedicated gateways for different namespaces or any other combination.

There is a separate issue on how to control access if 'flat networks' are used, without Gateways - and I think allowing RBAC to control consistently all cases, by using 'cluster' as any other label remain best option.  User may change the topology - set up or remove VPNs or peering - the behavior of access control should not change based on the implementation detail. And at the same time if SNI routing is used in Gateway for other purpose than multi-cluster - it should allow all the expected controls.

**Comment by smawson** [comment]
> @smawson there are few different issues:
> 
> * RBAC rules should be able to use the 'cluster' as one of the labels. I don't see any reason why it shouldn't, among all the other labels it supports already. We expose network as an attribute, and should be possible to use that in RBAC rules as well.

I think we already have cluster as an attribute, so it can already use it? Or at least we were adding this if it isn't in yet. So yeah we can support it. I think we should discourage it though since it is an anti-pattern.

> * as long as Gateway is used to expose resources between networks, the implementation must follow the spec - and that already include a mechanism to control what is exposed. The SNI filtering we use  is in no way specific to multi-cluster or specific install patterns - even if I have a single cluster, or just a raw-VM-only Istio with no clusters at all - it should still work.

I think we should discuss this model. SNI Gateway should be an implementation detail of bridging networks IMO, and not used as an access control mechanism. That should be left to explicit access control through things like RBAC. Obviously you want access control on ingress and egress gateways, but bridging gateways having access control also sounds like an anti-pattern.

> * the actual doc we have is an example of how to configure Istio - not a spec on how it should be configured.

Describing something in a doc explicitly condones its use, which I want to avoid for some of these anti-patterns. So I'd rather focus on coming up with real solutions to user problems rather than hacking up solutions using our existing support. Our existing documentation is also an anti-pattern, it is absolutely horrible to read as a user, incredibly confusing, and really only useful for someone intimately familiar with Istio. We should force ourselves to do better rather than using the status quo as an excuse.

> I agree that exposing all services by default is an explicit goal and should be supported - but that doesn't mean Gateway should not allow control over what is exposed. You may use internal load balancers or dedicated gateways for different namespaces or any other combination.

It depends on the use case. Gateways for ingress/egress need to allow control over exposure. Gateways for network bridging within a mesh should not. Networks should not be used as isolation mechanisms. Again, that's an anti-pattern we want to push users away from. Clusters are the same, they should not be used as isolation mechanisms, it is far too fragile and complex to manage, and is not at the right abstraction level.

> There is a separate issue on how to control access if 'flat networks' are used, without Gateways - and I think allowing RBAC to control consistently all cases, by using 'cluster' as any other label remain best option. User may change the topology - set up or remove VPNs or peering - the behavior of access control should not change based on the implementation detail. And at the same time if SNI routing is used in Gateway for other purpose than multi-cluster - it should allow all the expected controls.

Agree with the basic premise, that we shouldn't be relying on implementation details of Gateways to control access. Also agree that RBAC is the right way to do access control, although with the caveat that cluster should not be promoted as a boundary (again, too fragile and breaks abstractions Istio tries to create). The boundaries we are promoting are:
- Meshes
- Namespaces
- Service Accounts

Those should be the happy path for isolation, not cluster or network.

**Comment by vadimeisenbergibm** [comment]
@smawson 
> Networks should not be used as isolation mechanisms. Again, that's an anti-pattern we want to push users away from.

This is the basic point that I probably failed to make clear. Though I wrote in the blog post:

> [PCI DSS](https://www.pcisecuritystandards.org/pci_security), for example, recommends putting cardholder data
environment on a separate network. It requires using a [DMZ](https://en.wikipedia.org/wiki/DMZ_(computing)),
and setting firewalls between the public Internet and the DMZ, and between the DMZ and the internal network.

Until you manage to convince the [PCI Security Standards Council](https://www.pcisecuritystandards.org) that using networks should not be used as an isolation mechanism, the companies that process payment card data have to use networks for isolation. In my blog post, I propose to use a cluster for isolation in addition to using a network for isolation.

[Google Cloud’s PCI DSS compliance guide](https://cloud.google.com/solutions/pci-dss-compliance-in-gcp) proposes to use Network Policies for isolation within the same cluster: 

> Implement network policies in the GKE cluster when your in-scope projects contain different types of pods. Network policies work similar to the virtual private cloud (VPC) firewalls that you might already be familiar with. You can allow or deny traffic based on IP rules or labels.

For a large customer we work with, Network Policies isolation is not enough – they want isolation by clusters in addition to isolation by networks.

You may want to check the slides I showed during the last Networking WG meeting, it cites the relevant PCI DSS compliance parts and explains the involved patterns: https://drive.google.com/drive/folders/0BzW5bSyKst8Jb1QwTXl1WTRqWHM . The meeting's recording is on Youtube, the first 45 minutes are related to isolation&boundary protection, and to mesh federation https://www.youtube.com/watch?v=dgMxzjoH4OI&feature=youtu.be.

**Comment by vadimeisenbergibm** [comment]
@smawson You nailed it:

> A mesh exposing all services by default is an explicit design goal of a multicluster mesh. Another explicitly goal is that the details of clusters and networks is abstracted away so the user is only dealing with logical concepts of a mesh, a namespace, and a service. So exposure is intentionally limited to being about those concepts. You can expose services between namespaces, or block them from namespaces, but not expose them between clusters.

> If we want to design a solution for boundary protection, we should have a discussion about how to support boundary protections. My strawman is that each mesh is by definition a boundary, so if you want to put boundaries around things those are two different meshes. But we should have that discussion in a feature request for supporting boundary protections, not in an issue about a particular implementation of a mesh. So this one should be closed, and please open a feature request for adding boundary protections to Istio.

> SNI Gateway should be an implementation detail of bridging networks IMO, and not used as an access control mechanism. That should be left to explicit access control through things like RBAC. Obviously you want access control on ingress and egress gateways, but bridging gateways having access control also sounds like an anti-pattern.

This is my position as well. Exposing-all by default is a feature and not a bug. It is done by design of the single multi-cluster mesh. The gateway used in https://istio.io/docs/setup/kubernetes/install/multicluster/gateways/ is a **bridging gateway** (this is the definition I missed, thank you for providing it!), and not an _access-control gateway_. *By design*, a **briding gateway** exposes everything by default, since it is a single logical mesh. For isolation and boundary protection, we cannot use a single multi-cluster mesh, we have to connect multiple meshes with access-control gateways between them (whatever name you want to use for this connection).

> So this one should be closed, and please open a feature request for adding boundary protections to Istio.

Here I agree with you, but @costinm and @louiscryan think that it is a P0 bug. Let's agree with @costinm and @louiscryan that it is not a bug, and I will be happy to close this issue.

cc @andraxylia @rshriram @sdake @frankbu @nmittler @linsun 

@smawson  You may want to see the last Networking WG meeting on Youtube, the first 45 minutes are related to isolation&boundary protection, and to mesh federation https://www.youtube.com/watch?v=dgMxzjoH4OI&feature=youtu.be.

**Comment by vadimeisenbergibm** [comment]
@mbanikazemi 
> The issue of this being a bug or a feature seems to be not relevant for what you want to achieve. 

It is relevant in the sense of the required effort. If something is a major feature of some solution, to fix that feature could mean to reimplement the whole solution. Since we have an alternative solution - https://github.com/istio/istio.io/pull/4776, we should think if we want to invest effort in fixing the bug/feature, or to leave the solution with the bug/feature AS IS, and to use [the alternative solution](https://github.com/istio/istio.io/pull/4776) for isolation&boundary protection.

**Comment by smawson** [comment]
> @smawson
> 
> > Networks should not be used as isolation mechanisms. Again, that's an anti-pattern we want to push users away from.
> 
> This is the basic point that I probably failed to make clear. Though I wrote in the blog post:
> 
> > [PCI DSS](https://www.pcisecuritystandards.org/pci_security), for example, recommends putting cardholder data
> > environment on a separate network. It requires using a [DMZ](https://en.wikipedia.org/wiki/DMZ_(computing)),
> > and setting firewalls between the public Internet and the DMZ, and between the DMZ and the internal network.
> 
> Until you manage to convince the [PCI Security Standards Council](https://www.pcisecuritystandards.org) that using networks should not be used as an isolation mechanism, the companies that process payment card data have to use networks for isolation. In my blog post, I propose to use a cluster for isolation in addition to using a network for isolation.

Interesting. If they actually want strong isolation, they should use either namespace or mesh isolation in addition to network isolation, since Istio just bridges the networks and makes network isolation irrelevant. So I'll walk my position back a bit, the anti pattern is relying on network isolation as the sole isolation mechanism.

Best practice for real isolation would be to have multiple meshes (and therefore multiple clusters), and each mesh on its own network. I think that's what you're also saying? I believe that would meet all of the isolation requirements you laid out in the deck?

> 
> [Google Cloud’s PCI DSS compliance guide](https://cloud.google.com/solutions/pci-dss-compliance-in-gcp) proposes to use Network Policies for isolation within the same cluster:
> 
> > Implement network policies in the GKE cluster when your in-scope projects contain different types of pods. Network policies work similar to the virtual private cloud (VPC) firewalls that you might already be familiar with. You can allow or deny traffic based on IP rules or labels.
> 
> For a large customer we work with, Network Policies isolation is not enough – they want isolation by clusters in addition to isolation by networks.

Note that Network Policies are different than isolation by network, although they can have similar effects. Network policies in K8s can actually operate using label selectors and are hence slightly less bad than plain IP policies (although still not as good as Istio policies since they can't handle L6/7). They can also provide namespace isolation in a way that networks cannot, unless you have also locked a namespace to a network, which may be something we should look into.

All that said, we should probably have someone start interacting with the PCI council to discuss what compliant policies look like with Istio in the mix, since we provide new tools and concepts for security, although we have some known gaps still.

> You may want to check the slides I showed during the last Networking WG meeting, it cites the relevant PCI DSS compliance parts and explains the involved patterns: https://drive.google.com/drive/folders/0BzW5bSyKst8Jb1QwTXl1WTRqWHM . The meeting's recording is on Youtube, the first 45 minutes are related to isolation&boundary protection, and to mesh federation https://www.youtube.com/watch?v=dgMxzjoH4OI&feature=youtu.be.

**Comment by vadimeisenbergibm** [comment]
@smawson 
> If they actually want strong isolation, they should use either namespace or mesh isolation in addition to network isolation, since Istio just bridges the networks and makes network isolation irrelevant. So I'll walk my position back a bit, the anti pattern is relying on network isolation as the sole isolation mechanism.

PCI DSS requires isolation by networks + boundary protection (they do not use the term boundary protection, it is a term used by [NIST Special Publication 800-53, Revision 4, Security and Privacy Controls for Federal Information Systems and Organizations](http://dx.doi.org/10.6028/NIST.SP.800-53r4), _Appendix F, Security Control Catalog, SC-7 Boundary Protection_.) For PCI DSS, the boundary protection means:
* put an access control mechanism at the boundary (firewall, gateway, etc.)
* all the access control mechanisms must be deny-all by default
* do not expose private IP addresses from the boundary (they have a relaxed requirement - do not expose private IP addresses from the boundary to unauthorised parties). NIST talks about not disclosing private IPs in general: _Prevent discovery of components/devices
… Network addresses are not available for discovery (e.g., network address not published or entered in domain name systems)_
* do not let components from outside the boundary to manage security inside the boundary

> Best practice for real isolation would be to have multiple meshes (and therefore multiple clusters), and each mesh on its own network. I think that's what you're also saying? I believe that would meet all of the isolation requirements you laid out in the deck?

Right, this is exactly my proposal. In the blog post https://github.com/istio/istio.io/pull/4776, I show how you can connect these meshes and to perform cross-mesh routing and load-balancing.

> Note that Network Policies are different than isolation by network, although they can have similar effects. Network policies in K8s can actually operate using label selectors and are hence slightly less bad than plain IP policies (although still not as good as Istio policies since they can't handle L6/7). They can also provide namespace isolation in a way that networks cannot, unless you have also locked a namespace to a network, which may be something we should look into.

As far as I understand, the [Google Cloud’s PCI DSS compliance guide](https://cloud.google.com/solutions/pci-dss-compliance-in-gcp) proposes to simulate network segmentation by Network Policies. I hope that the PCI council accepts such definition. The large client we work with are not convinced that Network Policies within a cluster provide enough isolation.

From the PCI DSS guide: _Network segmentation can be achieved through a number of physical or logical means, such as properly configured internal network firewalls, routers with strong access control lists, or other technologies that restrict access to a particular segment of a network._

> All that said, we should probably have someone start interacting with the PCI council to discuss what compliant policies look like with Istio in the mix, since we provide new tools and concepts for security, although we have some known gaps still.

I think it would be great! Both the Kubernetes and Istio communities should clarify with the PCI council what is considered appropriate isolation of a cardholder data environment, in the context of Kubernetes clusters/namespaces/network policies, with or without Istio. It think it should promote using Kubernetes and Istio in organisations that require isolation of sensitive data environments.

**Comment by smawson** [comment]
Per our discussion today, do we want to change this issue into being one about SNI not supporting access control (per @costinm comments):

The SNI-proxy port - just like any other port in the Gateway - should follow the same rules, and allow configuration of which namespaces and services can be exposed.

We should either change this issue into that or create a new issue for that and close this one.

**Comment by vadimeisenbergibm** [comment]
@smawson I have changed the title to include `as documented on istio.io`. Let me be more specific about the issue:

**The setting:** a user chooses https://istio.io/docs/setup/kubernetes/install/multicluster/gateways/ to connect their clusters. He/she follows the instructions in https://istio.io/docs/setup/kubernetes/install/multicluster/gateways.

**The issue:** the user has all the services exposed to the other cluster.

**The expected result:** none of the services are exposed by default. 

**Possible solutions:**
The user should be warned that all their services are exposed by default.
Alternatively, the user should be instructed how to prevent exposure by default. Or the documentation on istio.io should be changed to not expose everything by default.

@costinm @louiscryan @linsun @smawson @andraxylia do we agree on the following?

1. the issue - after following the steps at https://istio.io/docs/setup/kubernetes/install/multicluster/gateways, the user will have all their services exposed
1. the expected result
1. Is it a P0 bug as @costin claimed or is it Nebulous Future as set by @andraxylia or is it by design, as claimed by me and @smawson ?

**Comment by smawson** [comment]
IMO this is a documentation bug, we should clean up this scenario completely to either be:
1) A single mesh with multiple control planes and multiple networks, where everything is shared.
2) An example of federation between multiple meshes, where nothing is shared.

Right now it is some weird Frankenstein hybrid.

The key question is whether this is meant to show one mesh or two meshes.

**Comment by vadimeisenbergibm** [comment]
@smawson OK, let's treat it as a documentation bug. If so, there is nothing to fix in Istio code, closing the issue.

**Comment by frankbu** [comment]
@smawson, I'm a little confused why you think the current example is a hybrid. It is a "one mesh" example: `1. A single mesh with multiple control planes and multiple networks, where everything is shared.`.

In the intro it says `A single Istio service mesh across the clusters is achieved by replicating shared services ...` and then shows how to replicate the needed service manually, but it also says that part could be automated (https://istio.io/docs/setup/kubernetes/install/multicluster/gateways/#summary).

A multi-mesh federation example would be quite different. It would show how to manually map different services from one isolated mesh to another.

**Comment by louiscryan** [comment]
@vadimeisenbergibm Have you validated that the exposure is an issue when exportTo is set on a ServiceEntry or the equivalent annotation on a Service. That should constrain the visibility of services to the gateway. If thats not working its a bug for sure

**Comment by smawson** [comment]
@frankbu you're right, this is just a single mesh. My real objection is to the way we handle DNS, I have a strong aversion to the .global thing. I think that was just a workaround though, we should figure out a better DNS (and service discovery replication in general) story.

@louiscryan just to clarify, you mean that the list of exportTo namespaces should be enforced at the gateway? Where is that enforced without a gateway, is that at the client? Maybe we should enforce at both client and gateway when we have the gateway connectivity setup?

Agree we should verify that exportTo is being enforced correctly, that would be part of the better multi-network tests that @costinm has been advocating for :)

**Comment by vadimeisenbergibm** [comment]
@louiscryan I tried a Sidecar resource to limit all the traffic from the ingress gateway to `istio-system` (to block any incoming traffic to any application services) but it did not take any effect:
```
kubectl apply --context=$CTX_CLUSTER2 -n istio-system -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: ingress-gateway
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  egress:
  - hosts:
    - "istio-system/*"
EOF
```

Even if the Sidecar resource above would work, it would expose access to Istio-system service, not good for security/compliance. If you do not provide access to Istio-system, I guess the ingress gateway will not be able to communicate with the control plane.


Note that there are no VirtualService involved, only plain Kubernetes services. How can one limit scope of Kubernetes services?

**Comment by vadimeisenbergibm** [comment]
@frankbu cc @louiscryan 

Thank you for letting me know about `networking.istio.io/exportTo`, I did not know about that annotation. I see it is documented https://istio.io/docs/ops/traffic-management/deploy-guidelines/#cross-namespace-configuration-sharing.

Two points:
1. From the note I see in https://istio.io/docs/reference/config/networking/v1alpha3/virtual-service/#VirtualService `exportTo` currently supports only `.` or `*`. So if I want to export a service outside the namespace, but inside a cluster, I cannot do it. The boundary is the namespace, not the cluster.
1. `exportTo` does not change the fact that all the services are exposed **by default** in the multiple control planes multi-cluster mesh. So if the user did not use `exportTo` and allowed their services to be accessed outside the namespace, the services will be exposed by default to all other connected clusters once the user performs the multi-cluster Istio installation. The user will have to go over their Kubernetes services and add the `exportTo` annotation. Moreover, every new Kubernetes service will be automatically exposed, unless the user limits its exposure by `exportTo`.
