### ISSUE TITLE
isito sidecar update after version upgrade

### ISSUE THREAD

**Issue by dhineshbabuelango** [istio/istio#16432]
Hi All, I am using istio in EKS.
After upgrading istio version from 1.2.2 to 1.2.3,
I tried updating the sidecar using the script provided by istio, but I could see the below results, it says no change, i tried describing the pod, stil the pod was using 1.2.2 version only.

```
[ec2-user@ip-10-76-8-135 bin]$ export NS=apps
[ec2-user@ip-10-76-8-135 bin]$ DEPLOYMENT_LIST=$(kubectl -n $NS get deployment -o jsonpath='{.items[*].metadata.name}')
[ec2-user@ip-10-76-8-135 bin]$ export deployment_name=isam-config
[ec2-user@ip-10-76-8-135 bin]$ TERMINATION_GRACE_PERIOD_SECONDS=$(kubectl -n $NS get deployment "$deployment_name" -o jsonpath='{.spec.template.spec.terminationGracePeriodSeconds}')
[ec2-user@ip-10-76-8-135 bin]$ patch_string="{"spec":{"template":{"spec":{"terminationGracePeriodSeconds":$TERMINATION_GRACE_PERIOD_SECONDS}}}}"
[ec2-user@ip-10-76-8-135 bin]$ kubectl -n $NS patch deployment $deployment_name -p $patch_string
deployment.extensions/isam-config patched (no change)
```
also Is there a way we can update only the envoy without restarting the actual applications.

**Comment by howardjohn** [comment]
There is no way to update envoy without restarting the pod currently.

To trigger a restart of your pods I suggest `kubectl rollout restart` if you have a newer kubectl

**Comment by howardjohn** [comment]
If you have old kubectl I would suggest running https://github.com/istio/tools/blob/master/bin/redeploy.sh
`./redeploy.sh NS` will perform a rolling update. Strongly recommend the `kubectl rollout restart` which is built in support for this
