### ISSUE TITLE
1.2.4 istio envoy version incorrect

### ISSUE THREAD

**Issue by xxxiarrren** [istio/istio#16431]
Hi all,
    We are trying the new release istio 1.2.4.  We found the envoy version in the  proxy/istio.deps  is not the latest according to the version 1.2.4. The commits about the security update(refered in the 1.2.4 release note) are not included in the version specified. 
    How to deal with this situation since we compile the binary packages of istio-proxy by ourselves.  We look forward to receiving your early reply. 

proxy/istio.deps : 
[https://github.com/istio/proxy/blob/1.2.4/istio.deps](url)

		"_comment": "",
		"name": "ENVOY_SHA",
		"repoName": "istio/envoy",
		"file": "WORKSPACE",
		"lastStableSHA": "cba9f5e3544a6c00c2d8f4406f98f2d4dfad773a"

Thanks for your help.

**Comment by bianpengyuan** [comment]
Sorry I think we made a mistake and forgot to update the istio.deps, but bazel WORKSPACE file (which decides the envoy SHA that proxy uses) is correctly updated and the 1.2.4 proxy should include the security fix:
https://github.com/istio/proxy/blob/568f2b648f7185e8396caf00a5a3a9b306c36416/WORKSPACE#L40

We will make a new release in a couple of days with isito.deps updated: https://github.com/istio/proxy/pull/2378

**Comment by howardjohn** [comment]
the ENVOY_SHA is not actually used, we are considering removing it. See discussion in https://github.com/istio/proxy/pull/2364

**Comment by xxxiarrren** [comment]
> Sorry I think we made a mistake and forgot to update the istio.deps, but bazel WORKSPACE file (which decides the envoy SHA that proxy uses) is correctly updated and the 1.2.4 proxy should include the security fix:
> https://github.com/istio/proxy/blob/568f2b648f7185e8396caf00a5a3a9b306c36416/WORKSPACE#L40
> We will make a new release in a couple of days with isito.deps updated: istio/proxy#2378

Thanks for your prompt reply and we have received it.

**Comment by xxxiarrren** [comment]
Thanks for your prompt reply and we have received it.

**Comment by bianpengyuan** [comment]
I am going to close this issue, please reopen if you have further questions. thanks!
