### ISSUE TITLE
istio virtual service for ingress gateway

### ISSUE THREAD

**Issue by dhineshbabuelango** [istio/istio#16437]
Hi All, 
we are using istio in AWS EKS.
I could see the istio virtual service can be created using variety of steps in the below link

https://istio.io/docs/concepts/traffic-management/

But if we want to access a service using ingress gateway load balancer, we normally create virtual service and mention the uri which we can use with load balancer like path based routing, but if we create virtual service like below, how do we reach the service through ingress gateway where we didnt mentioned any path.

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ratings
spec:
  hosts:
  - ratings
  http:
  - match:
      sourceLabels:
        app: reviews
    route:
    ...

**Comment by vadimeisenbergibm** [comment]
Hello, see https://istio.io/docs/tasks/traffic-management/ingress/ingress-control/.

**Comment by dhineshbabuelango** [comment]
Hi Vadim, Thanks for the reply. 
In the above shared link, we have created a virtual service and calling the virtual service through ingress gateway, this works fine.
But if I create a virtual service for a service(service A) and tries to call that service from serviceB like https://serviceA, will istio still use virtual service created for service A while sending traffic to service A or do we need to specifically mention somewhere about this virtual service while calling service A

**Comment by vadimeisenbergibm** [comment]
@dhineshbabuelango The virtual service will be applied within the mesh by default.

**Comment by vadimeisenbergibm** [comment]
@dhineshbabuelango So the virtual service will be applied by default to requests sent to serviceA within the mesh without additional configuration.

**Comment by dhineshbabuelango** [comment]
thanks Vadim for the reply
