### ISSUE TITLE
istio operator should be using kiali operator

### ISSUE THREAD

**Issue by jmazzitelli** [istio/istio#16435]
**Describe the feature request**

Right now, the Istio Operator under development is building out Kiali's deployment and other resources itself - e.g. https://github.com/istio/operator/blob/6f2cee687e7512845663b449051b1edea279ca69/pkg/controller/istiocontrolplane/listeners.go#L298-L336

However, it should instead simply just install the Kiali Operator and create a single Kiali CR and let the Kiali Operator install Kiali.

This means the Istio repo will no longer have to maintain full knowledge of how to install Kiali for each Kiali that gets released. As Kiali changes, it is difficult to keep in sync this Istio operator, but by using Kiali Operator, the istio operator needs only to know to create an operator (if the user uses [OLM](https://github.com/operator-framework/operator-lifecycle-manager), it can defer to that) and a proper Kiali CR (see [the fully documented kiali_cr.yaml](https://github.com/kiali/kiali/blob/master/operator/deploy/kiali/kiali_cr.yaml) to see what it looks like).

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

For details on using the Kiali Operator, see https://www.kiali.io/documentation/getting-started and the Maistra operator's use of the Kiali operator (the Istio operator will need to do something similiar) - e.g.:

* https://github.com/Maistra/istio-operator/blob/maistra-1.0/pkg/controller/servicemesh/controlplane/hooks.go#L62-L181
* https://github.com/Maistra/istio-operator/blob/maistra-1.0/helm/istio/charts/kiali/templates/kiali-cr.yaml
* https://github.com/Maistra/istio-operator/blob/maistra-1.0/pkg/controller/servicemesh/memberroll/controller.go#L446-L492

**Comment by clyang82** [comment]
This PR is for kiali operator - https://github.com/istio/installer/pull/295

**Comment by jmazzitelli** [comment]
BTW: there is a PR that addresses this issue. See: https://github.com/istio/istio/pull/20131
