### ISSUE TITLE
Pilot's automatic roll deployments do not work

### ISSUE THREAD

**Issue by kostyrev** [istio/istio#16442]
**Bug description**
When you change istio's ConfigMap Pilot is not being redeployed

**Affected product area (please put an X in all that apply)**

[X] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Changing istio.configmap should invoke new pilot's deployment

**Steps to reproduce the bug**
change one of istio's configmap values, e.g. set enableTracing to `false` or completely remove any values from configmap and get the same `checksum/config-volume` annotation:
```bash
[kostyrev ~/github/istio/install/kubernetes/helm/istio (minikube:default) (master) Wed Aug 21 16:33]
> helm template -f values-istio-minimal.yaml -x charts/pilot/templates/deployment.yaml . | grep 'checksum/'
    checksum/config-volume: f8da08b6b8c170dde721efd680270b2901e750d4aa186ebb6c22bef5b78a43f9
```
```bash
[kostyrev ~/github/istio/install/kubernetes/helm/istio (minikube:default) (master) Wed Aug 21 16:33]
> helm template -f values-istio-remote.yaml --set pilot.enabled=true -x charts/pilot/templates/deployment.yaml . | grep 'checksum/'
    checksum/config-volume: f8da08b6b8c170dde721efd680270b2901e750d4aa186ebb6c22bef5b78a43f9
```
**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.2.4+
**How was Istio installed?**
with helm
```bash
Client: &version.Version{SemVer:"v2.12.2", GitCommit:"7d2b0c73d734f6586ed222a567c5d103fed435be", GitTreeState:"clean"}
```
Error happens [here](https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/templates/_helpers.tpl#L45) and [here](https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/pilot/templates/deployment.yaml#L14).
It happens because instead of rendering sha256sum of ConfigMap's content helm renders sha256 of line `'istio/charts/pilot/templates/configmap.yaml'`

that can be proved by running
```bash
> echo -n 'istio/charts/pilot/templates/configmap.yaml' | shasum -a 256
f8da08b6b8c170dde721efd680270b2901e750d4aa186ebb6c22bef5b78a43f9  -
```

**Comment by howardjohn** [comment]
not sure why we have that anyways, pilot will reload the config map now. Probably just a legacy from before that worked. So seems like the fix may be to remove this rather than fix it?

**Comment by rshriram** [comment]
cc @hzxuzhonghu

**Comment by hzxuzhonghu** [comment]
I am sure we updated the mesh config in pilot without restart.

Agree we should remove the legacy `checksum/config-volume` annotation in pilot deployment.
