### ISSUE TITLE
Fix default MySQL connectivity

### ISSUE THREAD

**Issue by saturnism** [istio/istio#16455]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

Istio default setup doesn't allow connection from JDBC to MySQL services.  The workaround is documented here: https://istio.io/faq/security/#mysql-with-mtls

However, I've interacted w/ many people who runs into this issue and unable to resolve it. Running an application w/ MySQL service is a pretty common use case. Istio should work with this out of the box.

**Affected product area (please put an X in all that apply)**

[x] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Expected behavior**

MySQL just works w/o the workaround.

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

GKE (v1.13.6-gke.13) w/ Istio Add On(Istio 1.1.3-gke.0)

**How was Istio installed?**

GKE Istio Add On

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by vadimeisenbergibm** [comment]
@saturnism Please note that the workaround is for the PERMISSIVE mode, it should not be related to STRICT mutual TLS of Istio.

Are your MySQL services inside the mesh (have Istio sidecars injected)? Do you name their port with `tcp-` prefix? See requirements for port names in Istio https://istio.io/docs/setup/kubernetes/additional-setup/requirements/

**Comment by saturnism** [comment]
The default installation is permissive mode.
No the port name is not prefixed w/ `tcp-`. I recall any non-matched prefixes defaulted to tcp in the past. Also, almost all examples of app + MySQL deployments don't use the tcp- prefix, and they won't work in Istio environment by default either.

**Comment by vadimeisenbergibm** [comment]
@saturnism So if you will try the STRICT mode of mTLS, will it work?

**Comment by esnible** [comment]
Assigning myself to verify the claim that PERMISSIVE works for MySQL in 1.3 and add a test case to the spreadsheet.
