### ISSUE TITLE
Dynamic black list

### ISSUE THREAD

**Issue by tx19980520** [istio/istio#16465]
**Dynamic Black List**

dynamic ip black list like nginx + lua + mysql

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

We have requirements about dynamic ip black list to defend against some cyber attacks and ensure cluster performance, We have used nginx + lua to do it.
Istio is using nginx as ingressgateway so I think it is up to the job.
Maybe someone can give advice to me about how to realize the requirements in istio or k8s

**Comment by douglas-reid** [comment]
Istio's ingressgateway is using Envoy. Envoy supports Lua filters -- which Istio enables via [EnvoyFilter](https://istio.io/docs/reference/config/networking/v1alpha3/envoy-filter/) configuration.

Please let us know if you have any questions about Istio + Lua on our forums: discuss.istio.io
