### ISSUE TITLE
egress gateway mutual TLS

### ISSUE THREAD

**Issue by dhineshbabuelango** [istio/istio#16464]
Hi All, We are using istio in AWS EKS.
While working on egress gateway, we just created service entry and it worked fine.  But when we try to use mutual TLS, as per the istio doc, it is asking to update the client certificates like below.

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: ext-res-dr
spec:
  host: ext-resource.com
  trafficPolicy:
    tls:
      mode: MUTUAL
      clientCertificate: /etc/certs/myclientcert.pem
      privateKey: /etc/certs/client_private_key.pem
      caCertificates: /etc/certs/rootcacerts.pem

Do we need to get these certificates including the private key  from external vendors.
the above mentioned certificates are client certificates or istio certificates created by citadel?

If we need to import the client certificate inside istio, the way should be create secret for egress gateway.

**Comment by vadimeisenbergibm** [comment]
The certificates are client certificates trusted by your specific vendor. You should mount them by using a Kubernetes secret. The certificates are not managed by Citadel.

**Comment by dhineshbabuelango** [comment]
Thanks Vadim, so for mutual TLS, we get the above mentioned certificates from them and we need to share any of istio related certificates to client for this to be mutual.

**Comment by vadimeisenbergibm** [comment]
No, no need to pass Istio related certificates to vendor.

**Comment by vadimeisenbergibm** [comment]
@dhineshbabuelango do you still have any questions regarding egress gateway mutual TLS?
If you have more questions, please ask them at [discuss.istio.io](https://discuss.istio.io).

Closing this issue since it is neither a bug nor enhancement.
