### ISSUE TITLE
Add validation for values in operator API

### ISSUE THREAD

**Issue by richardwxn** [istio/istio#16468]
Right now there are validations of some basic fields of IstioControlPlaneSpec under operator, however there is no validation for pass through values.yaml field.

We need to update the existing validate_values.go file for more thorough validation and enable it in validate.go file.

**Comment by richardwxn** [comment]
PR created: https://github.com/istio/operator/pull/227

**Comment by ostromart** [comment]
Closed though https://github.com/istio/operator/pull/383.
