### ISSUE TITLE
Implement Post-Submit test failure alerts

### ISSUE THREAD

**Issue by hklai** [istio/istio#1646]
When PostSubmit test failures, the current oncall needs to be alerted, so that s/he can resolve the failures ASAP.

Possible resolutions include:
1. Identify and fix the issue.
2. Identify the culprit PR and roll it back.
3. Get help from other developers to help debug and identify the problems.

Without prompt alerts, oncall needs to periodically and manually check post-submit test results. It is not scalable and it is easy to miss test failures, and prolong the broken state.

**Comment by sebastienvas** [comment]
Prow supports slack notification, but I don't know how configurable it is. It would be good to have the failure being set to the #oncall channel directly.

**Comment by hklai** [comment]
@yutongz is there anything left to be done to improve post submit alerting?

**Comment by yutongz** [comment]
I don't have anything to add to this issue right now.  Let's just close it.
/close
