### ISSUE TITLE
istio egress gateway open to all even with REGISTER_ONLY mode

### ISSUE THREAD

**Issue by dhineshbabuelango** [istio/istio#16472]
Hi All, we are using istio in EKS. 
the isito version is 1.2.4. While working on egress gateway, we came to know that by default global.outboundTrafficPolicy.mode will be set to ALLOW_ANY and istio will allow all traffic by default, but I have changed this setting to REGISTER_ONLY and still I could see istio is allowing all the traffics. Do we need to change any other configuration to block all the default connection other than updating the istio configmap.

[ec2-user@ip-10-76-8-135 istio-upgrade]$ kubectl get configmap istio -n istio-system -o yaml | grep -o "mode: ALLOW_ANY"
[ec2-user@ip-10-76-8-135 istio-upgrade]$ kubectl get configmap istio -n istio-system -o yaml | grep -o "mode: REGISTER_ONLY"
mode: REGISTER_ONLY
[ec2-user@ip-10-76-8-135 istio-upgrade]$ kubectl -n apps exec -it $SOURCE_POD -c sleep -- curl -I https://www.google.com | grep  "HTTP/"; kubectl exec -it -n apps $SOURCE_POD -c sleep -- curl -I https://edition.cnn.com | grep "HTTP/"
HTTP/2 200
HTTP/2 200
[ec2-user@ip-10-76-8-135 istio-upgrade]$ kubectl get serviceentry --all-namespaces
No resources found.
[ec2-user@ip-10-76-8-135 istio-upgrade]$

**Comment by vadimeisenbergibm** [comment]
@dhineshbabuelango Note that it can time for configuration to propagate. Can you retry your curl commands?

**Comment by dhineshbabuelango** [comment]
Hi Vadim, Thanks for the reply, I tried even now, still the same

[ec2-user@ip-10-76-8-135 ~]$ kubectl -n apps exec -it $SOURCE_POD -c sleep -- curl -I https://www.google.com | grep  "HTTP/"; kubectl exec -it -n apps $SOURCE_POD -c sleep -- curl -I https://edition.cnn.com | grep "HTTP/"
HTTP/2 200
HTTP/2 200
[ec2-user@ip-10-76-8-135 ~]$ kubectl get configmap istio -n istio-system -o yaml | grep -o "mode: REGISTER_ONLY"
mode: REGISTER_ONLY
[ec2-user@ip-10-76-8-135 ~]$

**Comment by dhineshbabuelango** [comment]
Thanks Vadim :), its now working as expected

**Comment by dhineshbabuelango** [comment]
Hi Vadmin, after the change the connection from application container was working as expected but if any connection initiated from the istio-proxy it is still reaching internet. Was this an expected behaviour. Also creating a service entry alone will be enough to pass through the connection or still we need egress gateway and virtual service to be created.?

[ec2-user@ip-10-76-8-135 external]$ kubectl exec -it $SOURCE_POD -c istio-proxy -n apps -- curl -I https://www.yahoo.com |grep HTTP
HTTP/1.1 200 OK
[ec2-user@ip-10-76-8-135 external]$ kubectl exec -it $SOURCE_POD -c sleep -n apps -- curl -I https://www.yahoo.com |grep HTTP
command terminated with exit code 35
[ec2-user@ip-10-76-8-135 external]$

**Comment by vadimeisenbergibm** [comment]
Hi @dhineshbabuelango 

Istio proxy can access everything, but you should not use the proxy container. 
Egress gateway is for secure control of egress traffic, please see my blog post about it -https://istio.io/blog/2019/egress-traffic-control-in-istio-part-1/. It is for preventing attacks from inside the mesh, in case one of the pods is compromised.

> creating a destination rule and disabling the mTLS connection for that vendor URL is fine?

Yes, it is fine, though I do no think mTLS applied by default to external services.

**Comment by vadimeisenbergibm** [comment]
@dhineshbabuelango Could you please close this issue?

**Comment by dhineshbabuelango** [comment]
Thanks Vadmin, Before I close, one last question, the destination rule created for egress gateway here has only the subset name but nothing defined other than name, this name represents the name of the service entry? we need to create destination rule like this for all our services goes out of service mesh. Also we have a requirement to connect to DB and other AWS services for which we are planning to use only service entry but need to use the egress gateway only for services going to internet, can this be still achieved.

**Comment by vadimeisenbergibm** [comment]
The destination rules defines the subset and the subset name is used in the VirtualService:
```
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: cnn
```

It is not related to the name of the service entry.

You may drop the destination rule and remove the subset from the VirtualService. Destination rule here is not needed, it can be required if you want to set mTLS between the sidecar proxy and the egress gateway.

>  we have a requirement to connect to DB and other AWS services for which we are planning to use only service entry but need to use the egress gateway only for services going to internet, can this be still achieved.

Yes, you configure the traffic per destination - some of the traffic can go through an egress gateway, some other traffic can go directly. You can even use different egress gateways.

May I ask you though why do you want to direct some portion of your traffic through an egress gateway?

**Comment by dhineshbabuelango** [comment]
Thanks Vadim for the reply. The reason for sending only some traffic to egress gateway is the complexness i feel in configuring egress gateway.

For example:
when we create any destination rule, even when we specify subset we will mention some labels just to transfer the traffic, but we didn't mention anything here just the subset name. Is it like if we need to mention the destination rule in virtual service, we need to create a subset,

Also Regarding this

You may drop the destination rule and remove the subset from the VirtualService. Destination rule here is not needed, it can be required if you want to set mTLS between the sidecar proxy and the egress gateway.

We will be enabling mTLS for the complete namespace in which we are deploying our applications, can we still ignore this. Our requirement is, all services in the mesh should use mTLS, services outside of mesh don't need to use mTLS. As per your previous advice, I assume that we don't need any additional configuration to disable mTLS for services outside of mesh as it will be done by default. Is my understanding correct.

**Comment by vadimeisenbergibm** [comment]
Regarding mTLS, to be on the same side, it is better to specify explicitly the tls mode: Istio mTLS inside the mesh, including between the sidecar proxies and the egress gateway, and disable mTLS to the external services. 

TLS modes https://istio.io/docs/reference/config/networking/v1alpha3/destination-rule/#TLSSettings-TLSmode:

`ISTIO_MUTUAL` for Istio mTLS, `DISABLE` for disabling mTLS.

**Comment by dhineshbabuelango** [comment]
Thanks Vadim, So when we enable mTLS at the app namespace level, we need to create destination rule and disable mTLS to the services going outside of mesh?

**Comment by vadimeisenbergibm** [comment]
Right, you should disable mTLS to external services.

**Comment by dhineshbabuelango** [comment]
Thanks Vadim for the help

**Comment by dhineshbabuelango** [comment]
Hi Vadmin, I tried to change the mode to REGISTRY_ONLY and the connections are working as expected but not able to see anything in the logs. Due to this even if I create egress gateway, I was not able to check if the connections are going through egress gateway.

![image](https://user-images.githubusercontent.com/51995628/63857254-f492f700-c9d5-11e9-904e-3e1fd8620ff3.png)

**Comment by vadimeisenbergibm** [comment]
You can enable Envoy's access logs https://istio.io/docs/tasks/telemetry/logs/access-log/#enable-envoy-s-access-logging, and check the logs of the egress gateway:

`kubectl logs -l istio=egressgateway -c istio-proxy -n istio-system | tail`

**Comment by dhineshbabuelango** [comment]
Thanks Vadim, Let me try that. Below is the error once I enable mTLS inside the mesh. the error says connection failure but still I am getting success when I curl the link.


![image](https://user-images.githubusercontent.com/51995628/63859095-45f0b580-c9d9-11e9-8254-74333027d5ff.png)

**Comment by dhineshbabuelango** [comment]
Thanks Vadim, Now I am able to see the logs in egress gateway. But I have one application which supports only HTTP/1.1 is not working if I create egress gateway. It is working only if I create service entry.

Getting the below response when I create only service entry 
HTTP/1.1 200 OK

Getting the below error if I try to route the traffic to egress gateway. 
command terminated with exit code 35

Do I need to change anything for HTTP/1.1 in the egress gateway link mentioned below
https://istio.io/docs/tasks/traffic-management/egress/egress-gateway/

Also I have enabled logs like mentioned in the below link, will this create huge logs so that I have to take care of  my diskspace.

**Comment by vadimeisenbergibm** [comment]
@dhineshbabuelango HTTP/1.1 should work according to the task https://istio.io/docs/tasks/traffic-management/egress/egress-gateway/

**Comment by dhineshbabuelango** [comment]
Thanks Vadim, currently I am trying in version 1.2.5, let me try with some older version.
For this HTTP/1.1, i tried with 2 different URLS, it was the same issue.

**Comment by dhineshbabuelango** [comment]
@vadimeisenbergibm Thanks for the help. I missed to update this URL in the egress gateway hosts. 
It is working as expected now. 

Also I have enabled logs like mentioned in the below link, will this create huge logs so that I have to take care of my diskspace.

https://istio.io/docs/tasks/telemetry/logs/access-log/#enable-envoy-s-access-logging

Thanks again

**Comment by dhineshbabuelango** [comment]
@vadimeisenbergibm Thanks for the help. I missed to update this URL in the egress gateway hosts.
It is working as expected now.

Also I have enabled logs like mentioned in the below link, will this create huge logs so that I have to take care of my diskspace.

https://istio.io/docs/tasks/telemetry/logs/access-log/#enable-envoy-s-access-logging

Thanks again

**Comment by dhineshbabuelango** [comment]
Hi Vadim, Based on your tech note, you said we can restrict which service can access external services.

![image](https://user-images.githubusercontent.com/51995628/63993409-f4544200-cb22-11e9-9783-65156da5ff32.png)

I was looking at this option in egress gateway and not able to found that. could you please help.

![image](https://user-images.githubusercontent.com/51995628/63993453-22398680-cb23-11e9-8839-2be43aa33289.png)

**Comment by vadimeisenbergibm** [comment]
@dhineshbabuelango It is described here - https://istio.io/docs/tasks/traffic-management/egress/wildcard-egress-hosts/.

Could you please close this issue? I do not think it is a good practice to continue asking questions on the same issue, once the original issue was resolved.

**Comment by dhineshbabuelango** [comment]
Thanks Vadim for all the help
