### ISSUE TITLE
Attribute request.body/response.body

### ISSUE THREAD

**Issue by rverma-nikiai** [istio/istio#16471]
**Describe the feature request**
Support request.body/response.body 
Creating a new ticket as can't repoen the #4210. 

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by douglas-reid** [comment]
Thanks for this request. The desire to process request and response body is valid. However, adding this information in the form of attributes is not something that is going to be pursued.

That is not to say all hope is lost. In coming releases, we will be pushing out a new extensions architecture which will support in-proxy policy and telemetry extension. This extension mechanism will be much better positioned to allow access to request and response bodies. Please stay tuned for announcements and documentation of those features.

I'm going to close this issue given this context.

**Comment by rverma-nikiai** [comment]
@douglas-reid is there an open issue which I can subscribe to get updates?
