### ISSUE TITLE
Block Pre-Submit in case Post-Submit tests have failed

### ISSUE THREAD

**Issue by hklai** [istio/istio#1647]
When Post-Submit test failures, normal PRs merge needs to be blocked until post-submit tests are fixed.

This reduces the chance of worsening the broken state, and also increase the pressure for everyone to address the failures ASAP.

**Comment by sebastienvas** [comment]
There is no good way to prevent writers or admins from merging. We can reduce the amount of admins and completely remove writers on each repo and have the bot do the merge.

For info, the api is very limited
https://developer.github.com/v3/repos/collaborators/

**Comment by hklai** [comment]
Given the tests have been fairly green in both post and pre submit, I think the need for something like this has diminished....
