### ISSUE TITLE
remove bazel based docker build in security/*

### ISSUE THREAD

**Issue by rshriram** [istio/istio#1648]
The code under security/* (https://github.com/istio/istio/blob/master/security/bin/push-docker#L29) is using bazel based docker build. This has proven very inefficient in the past and slows down the build as there is not much caching benefit (bazel tars up everything as one layer), and changes timestamps - so new image is pushed no matter what (IIRC).

this needs to be changed to plain Dockerfile based build as is done under pilot/bin/push-docker (https://github.com/istio/istio/blob/master/pilot/bin/push-docker#L52).

This also hinders our move towards dep and non bazel tooling.

cc @costinm

**Comment by mangchiandjjoe** [comment]
PR https://github.com/istio/istio/pull/1661 was made

**Comment by mangchiandjjoe** [comment]
The PR was merged

**Comment by mangchiandjjoe** [comment]
This issue has been resolved.

**Comment by mattdelco** [comment]
bazel and push-docker and both gone now
