### ISSUE TITLE
master-latest-daily blocked by galley crashloop

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#16480]
https://github.com/istio-releases/pipeline/pull/1072

Galley is crashlooping -- https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio-releases_pipeline/1072/release-build-test-upgrade-tests-1.1.7/144

Unfortunately the tests don't capture logs from the pod, so will need to reproduce locally. I would guess its related to the new Authz CRD, but maybe not because the daily builds passed up until last night

**Comment by howardjohn** [comment]
upgrade test should probably be 1.2 -> master/1.3 now, not 1.1

**Comment by howardjohn** [comment]
randomly passed now, and locallly as well?

**Comment by ozevren** [comment]
Can we use this opportunity to add logging to the release tests. There was clearly something wrong, so it would be nice to understand whether it is a heisenbug or an infrastructure fluke.
