### ISSUE TITLE
Create a smoke e2e test

### ISSUE THREAD

**Issue by hklai** [istio/istio#1650]
Break tests/e2e and create a smoke test to be included in presubmit test.

It should not take over 10 minutes, and it is used as a smoke test to cover GKE deployment. The full e2e test suite is tested in post-submit only, but the smoke test can help gate changes that breaks GKE deployment.

**Comment by ldemailly** [comment]
simple/ can be that test and we can add to it

though we still run also mixer and demo in parallel

**Comment by yutongz** [comment]
I did it :)
https://github.com/istio/istio/pull/1654

**Comment by yutongz** [comment]
We can run parallel, but my concern is the resource pressure. Let's first enable one, or maybe two, we can buy some more machine. :)

**Comment by yutongz** [comment]
Fixed in https://github.com/istio/istio/pull/1654
