### ISSUE TITLE
go generate ./... failed

### ISSUE THREAD

**Issue by NiLtheGazettE** [istio/istio#16504]
I encountered a problem when I tried to create an example adapter following the step in the [Mixer Out of Process Adapter Walkthrough](https://github.com/istio/istio/wiki/Mixer-Out-Of-Process-Adapter-Walkthrough). I got the following error when I executed the 'go generate ./...' command.

go list -m: not using modules
go list -m: not using modules
go list -m: not using modules
/usr/bin/docker-current: Error response from daemon: invalid volume spec ":/protos/istio.io/gogo-genproto": invalid volume specification: ':/protos/istio.io/gogo-genproto'.
See '/usr/bin/docker-current run --help'.
mygrpcadapter.go:2: running "/my/workspace/path/mixer_codegen.sh": exit status 125

I think I did exactly the steps described in the article and didn't make any changes. Can someone help me with this? I can't solve this problem only through search engines...
My dev env:
go version: 1.12.9
protoc version: 3.9.1
docker version 1.13.1

I‘m not sure if I can ask question like this here. I'm new to Istio and golang, please excuse me if this is a foolish question...

**Comment by bianpengyuan** [comment]
Could you try to enable go module before running codegen? `GO111MODULE=on go generate ./...`

**Comment by howardjohn** [comment]
@geeknoid is the volume mount error related to the build tools?

**Comment by geeknoid** [comment]
@howardjohn I think the problem is that go modules was turned off, resulting in an invalid command line being produced for docker.

**Comment by NiLtheGazettE** [comment]
Thank you for your reply. @bianpengyuan @howardjohn @geeknoid
As @bianpengyuan said, I have solved this problem after I change GO111MODULE from auto to on. But I found there are some modules I can‘t install them through go get command in my network environment even I have configured the proxy.
Is there any way to manually install the module? I tried to download the related source code from github and run go install to install them but this doesn't seem to work... I see they will generate a '.a' file under pkg/linux_amd64 folder. And I still get the unrecognized exception when I run go build ./... command due to my network environment can't download them directly.
Please excuse me if this is still a boring question...

**Comment by NiLtheGazettE** [comment]
I found the go edit mod --replace command and I think I need to read the tutorial a few more time...(facepalm)
