### ISSUE TITLE
Helm versioning broken, therefor breaking CNI Test

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#16508]
```
$HELM_HOME has been configured at /root/.helm.
Not installing Tiller due to 'client-only' flag having been set
Happy Helming!
+ helm repo add istio.io https://gcsweb.istio.io/gcs/istio-prerelease/daily-build/master-latest-daily/charts/
"istio.io" has been added to your repositories
+ helm fetch --untar --untardir /tmp/tmp.OZoSnpX6qd istio.io/istio-cni
Error: chart "istio-cni" matching  not found in istio.io index. (try 'helm repo update'). No chart version found for istio-cni-
+ cleanup_kind_cluster
+ kind export logs --name istio-testing /logs/artifacts/kind
Exported logs to: /logs/artifacts/kind
+ [[ -z '' ]]
+ echo 'Cleaning up kind cluster'
Cleaning up kind cluster
+ kind delete cluster --name=istio-testing
```

Basically the problem is that the cni version is now `master-something`. Helm doesn't recognize this as a semantic version (its not :slightly_frowning_face: ), so it fails to find a version to use.

Long term we should actually use semver instead of this "master-latest" stuff

Based on https://github.com/helm/helm/issues/3009 I thought we may just be able to add `--devel` flag but it doesn't work either

```
$ helm install istio.io/istio --name foo --namespace istio-system --debug --devel
[debug] Created tunnel using local port: '46263'

[debug] SERVER: "127.0.0.1:46263"

[debug] Original chart version: ""
[debug] setting version to >0.0.0-0
Error: chart "istio" matching version ">0.0.0-0" not found in istio.io index. (try 'helm repo update'). No chart version found for istio->0.0.0-0
```

Note -- istio is broken too, its not just the CNI charts, we must just not have anything using master-latest-daily charts for istio

**Comment by howardjohn** [comment]
temporarily make the tests optional in https://github.com/istio/test-infra/pull/1709 to unblock people unless we can quickly fix

**Comment by rlenglet** [comment]
Helm docs claim that it supports [SemVer 2](https://semver.org/). According to the SemVer 2.0.0 grammar, this should be a valid version number: `0.0.0+master-latest-daily`.
So the trick would be to transform the `version` into `0.0.0+version` if it's not already compatible with SemVer 2.

**Comment by howardjohn** [comment]
interesting, didn't realize the difference between `-` and `+`. sgtm.

Make sure we don't make the official releases `0.0.0+1.3.0`, they should just be `1.3.0`
