### ISSUE TITLE
istioctl needs sds diagnostic commands

### ISSUE THREAD

**Issue by Monkeyanator** [istio/istio#16514]
**Describe the feature request**
Adding an `istioctl` command that makes it more straightforward to diff the SDS secrets active on a pod's sidecar and the secrets present on the pod's corresponding node agent. The command in its default form should behave as follows:

```
samnaser@samnaser:~/go/src/istio.io/istio$ istioctl experimental sds-status istio-ingressgateway-7889b8fbc8-qccd2.istio-system
RESOURCE NAME     TYPE           NODE AGENT                                PROXY       EXPIRATION
ROOTCA            CA             istio-nodeagent-p8lpf                     ABSENT      2020-08-31T19:25:17Z (2 years)
chacha-credoo     Cert Chain     istio-ingressgateway-7889b8fbc8-qccd2     PRESENT     2020-08-31T19:25:17Z (1 year)
default           Cert Chain     istio-nodeagent-p8lpf                     PRESENT     2019-08-24T18:22:34Z (6 mins)
default           Cert Chain     istio-nodeagent-p8lpf                     PRESENT     2019-08-24T18:22:34Z (5 hours)
```

Note that the command was able to show active SDS secrets supplied from both the `ingress-gateway` embedded node agent and the actual per-node `node agent`. The command should also be able to dump secrets active in a nodeagent, without performing diffing, which could look as follows:

```
samnaser@samnaser:~/go/src/istio.io/istio$ istioctl experimental sds-status --nodeagent istio-nodeagent-nxllj
RESOURCE NAME     TYPE           PROXY                     EXPIRATION
ROOTCA            CA             nginx-dbddb74b8-2kltq     2020-08-31T19:25:17Z
default           Cert Chain     nginx-dbddb74b8-4h82h     2019-08-24T18:22:34Z
default           Cert Chain     nginx-dbddb74b8-58szz     2019-08-24T18:22:34Z
...
```

In this case, we are shown *all* secrets the nodeagent is supplying and *exactly which proxies* are being served those secrets. All of the aforementioned commands should have a flag which dumps the data in JSON format along with the actual raw certificate data.

Note that I've done this a bit backwards and an experimental implementation is live [here](https://github.com/istio/istio/pull/16498)

**Describe alternatives you've considered**
These debug steps are possible to do manually (through port-forwarding the config dump port on the enovy proxy, and the debug endpoint on the node agent), but it is tedious and time consuming to diff the secrets.

@esnible 

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

https://github.com/istio/istio/issues/13439

**Comment by esnible** [comment]
This issue tracks the work in https://github.com/istio/istio/pull/16498

**Comment by Monkeyanator** [comment]
closing as duplicate #15789
