### ISSUE TITLE
Introduce` objectSelector` in sidecar-injector MutatingWebhookConfiguration to call sidecar-injector with pod label matching instead of using annotation `sidecar.istio.io/inject`

### ISSUE THREAD

**Issue by ChenLingPeng** [istio/istio#16538]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

Currently, we label a namespace and use `namespaceSelector` in sidecar-injector MutatingWebhookConfiguration to trigger sidecar injection. If the pod is not desired to inject sidecar, the pod need to set `sidecar.istio.io/inject` annotation. 

The problem here is that even when the pod has no need to inject sidecar, the apiserver will call the sidecar webhook. In sidecar injector, we check the annotation and decide not to inject. Once the sidecar injector pod does not work normally(maybe some network reason or pod/node crash), it will affect the pod creation process for those which not need sidecar.

Before k8s v1.15, I think we can't do more to handle this situation. But after v1.15, the k8s teams introduce a new feature for `MutatingWebhookConfiguration`, [`objectSelector`](https://github.com/kubernetes/kubernetes/blob/v1.15.0/staging/src/k8s.io/api/admissionregistration/v1beta1/types.go#L274). By using this feature, we could filter out pods which have no need to inject sidecar. And in the case the injector pod is not available, the normal pods(no need for sidecar) will be created smoothly without any effect.

**Describe alternatives you've considered**
None

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
This has been added to the templates
