### ISSUE TITLE
mTLS for istio ingressgateway

### ISSUE THREAD

**Issue by dhineshbabuelango** [istio/istio#16544]
Hi All, We are using istin in AWS EKS. We have automatic sidecar injection enabled in our apps namespace where we deployed all our applications. We have enabled mTLS for that particular namespace(apps). We have created a gateway like below in our apps namespace and created a virtual service using this gateway. If we tries to hit this gateway using the https link, the connectivity from gateway to the application will be TLS or mTLS?

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: tls-gateway
spec:
  selector:
    istio: admin-ingressgateway # use istio default controller
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: ingressgateway-certs
      minProtocolVersion: TLSV1_2
      maxProtocolVersion: TLSV1_2
    hosts:
    - "*"

**Comment by incfly** [comment]
internet ----https --- > gateway --- mtls or plaintext --> backend app.

gw and app whether mtls or plaintext purely depends on your DestinationRule and Authentication Policy as https://istio.io/docs/tasks/security/authentication/authn-policy/
