### ISSUE TITLE
Use camelCase for JSON/YAML Field Names for Istio APIs

### ISSUE THREAD

**Issue by jasonwzm** [istio/istio#16559]
**Describe the feature request**
According to Kubernetes API Convention guideline, all field names should be in camelCase in JSON, no dashes or underscores. https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#naming-conventions

However, we are using the non-conforming cases in some of our references (e.g. we use jwksUri and jwks_uri interchangeably). 

We should restrict to use only the camelCase in the name. I will start with correcting our docs references.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[X] Configuration Infrastructure
[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
@jasonwzm seems like a lot of PRs for this, is there still work here?

**Comment by ozevren** [comment]
@jasonwzm any updates on this?

**Comment by jasonwzm** [comment]
The PRs should fix the current uses of snake cases in istio/istio. Closing this for now and I will reopen if I spot any misuse.
