### ISSUE TITLE
Provide `istio_build` metric for proxies

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio#16555]
**Describe the feature request**
Istio should provide, either through direct generation or scrape configuration, the `istio_build` metric for proxies (including ingressgateway). This will allow consistent monitoring across Istio-installed artifacts, as it will bring proxies inline with the control plane components. This was originally requested as part of: #13936 .

**Describe alternatives you've considered**
N/A.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ X ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by gargnupur** [comment]
@douglas-reid : we can close this now right? Looks like this is done..

**Comment by howardjohn** [comment]
One other way to do this, if we can't do in proxy, is to have pilot expose it based on the node metadata from the connections. Not 100% accurate but close

**Comment by nicktrav** [comment]
There are a few issues / PRs on this, but it seems like after some back and forth, istio/proxy#2575 adds the metric back in the proxy code.

There's also a [comment](https://github.com/istio/proxy/pull/2431#pullrequestreview-295279563) on the original PR around making this work better with the version in the bootstrap config, though I'm not sure if that's obsolete now?

@douglas-reid @howardjohn - is there anything left to do on this ticket? I noticed that there was a cherry-pick failure on istio/proxy#2575 into 1.5 and 1.4. Any chance we can make those happen, as this would be good to see in at least 1.4.

**Comment by douglas-reid** [comment]
@nicktrav the big work left is to the cherry-picking. it will have to be manual, based on the need to regenerate the wasm files, etc. I have a queue of work items with this task in it.

**Comment by douglas-reid** [comment]
I believe this should be closed at this time, as the work was moved into 1.5 and verified.
