### ISSUE TITLE
Empty env variables are not set

### ISSUE THREAD

**Issue by ostromart** [istio/istio#16550]
Operator assumes that default string values mean unset, therefore setting a customization like this:
spec:
  security:
    components:
      nodeAgent:
       k8s:
         env:
           - name: foo
             value: ""

has no effect.

**Comment by howardjohn** [comment]
Do we have any case where setting a vriable to `""` is an different than not setting it in Istio currently?

**Comment by ostromart** [comment]
The issue is that we cannot unset env variables currently. I don't know if that's really a problem.
