### ISSUE TITLE
Fields from values overrides are not merged with those from IstioControlPlane

### ISSUE THREAD

**Issue by ostromart** [istio/istio#16551]
Some values have paths in both IstioControlPlane and helm e.g. 
 spec.security.components.nodeAgent.k8s.env is the same as
 nodeagent.env

It should be possible to set the values in both places and merge the two trees, but currently IstioControlPlane settings override helm.

**Comment by morvencao** [comment]
looks like the general json/yaml merge doesn't work in operator case, eg. for `env`, we have original snippet:

```
env:
- name: n1
  value: v1
```

and override snippet:
```
env:
- name: n1
  value: v2
```

the general json/yaml merge will just reproduce:
```
env:
- name: n1
  value: v1
- name: n1
  value: v2
```

we need semantic merge, because what we really want is:
```
env:
- name: n1
  value: v2
```
