### ISSUE TITLE
Choice of language

### ISSUE THREAD

**Issue by vermapratyush** [istio/istio#1655]
Hi,
This is not really an issue, but more for information purpose. Not even meant for debating.
I am wondering why golang is the choice of language for a sidecar. From my understanding, SideCar is expected to have a very predictable memory/CPU footprint, since it basically shares the resource with the "main" (host) application.
What I understand about GoLang is that,

- It does not provide a good memory management functionality like JAVA, wherein you can set Max/Min heap usage. It is possible to set a `ulimit` basically would cause the sideCar to crash rather than GC coming into the picture and trying to recovering the application, as JAVA does.
- It does not provide true thread pool, every time a new goroutine is spawned instead of recycling the older one (agreed that it is lightweight). 
- No way to kill a running goroutine. This seems to be an important functionality when a upstream service is latent and the downstream does not want to waste resource on the latent request. If the throughput is high such latent request would lead to spike in goroutine and thus more memory/cpu pressure.
- *debatable* Not as mature in performance tuning framework as compared to other mature languages.

**Comment by mandarjog** [comment]
The sidecar is written in C++. It is the  Envoy proxy. https://istio.io/docs/concepts/what-is-istio/overview.html#envoy

All Other components are written in go.

**Comment by vermapratyush** [comment]
Oops, that's really stupid of me. Thanks.
