### ISSUE TITLE
when pod is deleted, if envoy can handle route correctly without routing to the deleted pod?

### ISSUE THREAD

**Issue by happyxgang** [istio/istio#16562]
i'm using kubernetes, i find that when a pod is being deleted, our route module can't handle pod deletion correctly, it will route traffic to the deleted pod for a while before it detects this. can istio solve this?

**Comment by hzxuzhonghu** [comment]
in k8s it depends on pod graceful termination

in istio, we do that first making use of k8s endpoint, second making use of sidecar graceful shutdown. For more details, there is an issue you can search
