### ISSUE TITLE
Integrate Istio with AWS Certificate Manager Private Certificate Authority

### ISSUE THREAD

**Issue by lcrisci** [istio/istio#16563]
**Describe the feature request**

It would be great to have Istio ( mainly nodeagent's caclient at this point ) integrate with [AWS Certificate Manager Private Certificate Authority](https://aws.amazon.com/certificate-manager/private-certificate-authority/) to deliver signed certificates from a managed CA instead of running our own.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by incfly** [comment]
I think this will be largely a community driven design/proposal.

**Comment by LukeMwila** [comment]
I know this is several years later, but in case someone else lands here looking for a solution. Here you go:

GitHub: [GitHub - LukeMwila/how-to-setup-external-ca-in-istio: This repository contains steps and source code for configuring an external CA in Istio.](https://github.com/LukeMwila/how-to-setup-external-ca-in-istio)
YouTube: [How to Setup External CA Integration in Istio - YouTube](https://youtu.be/jWOfRR4DK8k)
