### ISSUE TITLE
authn tls-check gives vague error

### ISSUE THREAD

**Issue by sdake** [istio/istio#16576]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ X ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
authn tls-verify either succeeds or offers a more valuable path forward.

**Steps to reproduce the bug**
```
sdake@beast-01:~/istio-1.3.0-rc.0$ kubectl apply -f samples/helloworld/
gateway.networking.istio.io/helloworld-gateway created
virtualservice.networking.istio.io/helloworld created
service/helloworld created
deployment.apps/helloworld-v1 created
deployment.apps/helloworld-v2 created
sdake@beast-01:~/istio-1.3.0-rc.0$ kubectl get pods
NAME                             READY   STATUS    RESTARTS   AGE
helloworld-v1-7bb88866c4-f6ss5   1/1     Running   0          4s
helloworld-v2-6cd449dff4-t624c   1/1     Running   0          4s

sdake@beast-01:~/istio-1.3.0-rc.0$ istioctl authn tls-check helloworld-v1-7bb88866c4-f6ss5
Error: checked 1 pilot instances and found no authentication info for helloworld-v1-7bb88866c4-f6ss5.default, check proxy status
```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.3.0-rc0

**How was Istio installed?**
via the auth default template.

**Environment where bug was observed (cloud vendor, OS, etc)**
Linux.

**Comment by esnible** [comment]
@sdake Please explain the problem or close the issue.

**Comment by esnible** [comment]
@sdake Please explain the problem or close the issue.
