### ISSUE TITLE
https://git.io/getLatestIstio installs prerelease version

### ISSUE THREAD

**Issue by whut** [istio/istio#16570]
**Bug description**

The https://git.io/getLatestIstio script after pull request #15449 installs newest version of Istio, including even prerelease version. Before the pull requests it installed most recent version (which was not the right thing to do), but it ignored prerelease versions.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Right now https://git.io/getLatestIstio should pick version 1.2.5, not the 1.3.0-rc.0.

**Steps to reproduce the bug**

1. Run `https://git.io/getLatestIstio | sh -`
2. Right now (27.08.2019) it will install Istio 1.3.0-rc.0

**Comment by whut** [comment]
So the name of the script should change, because it does not install latest;)

But seriously, there must be some way to make it work, either via some more sed/awk magic or just by exposing that information on some separate endpoint, so it will be easier to parse.

**Comment by whut** [comment]
Yes, by default pre-release version should not be considered. This is in line with many other tools, like package managers, in which "installing latest" mean "installing latest stable"

**Comment by howardjohn** [comment]
@whut I don't see a feasible way to accomplish this. Given our documentation always results in the correct version being downloaded, I don't think there is much we can/should do. Thanks for bringing this to our attention though, as I wasn't aware this was the behavior
