### ISSUE TITLE
Long running test for mixer v2 on NullVm and WebAssembly.

### ISSUE THREAD

**Issue by jplevyak** [istio/istio#16589]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request** We need to do a long running test of mixer v2 on the NullVm and on WebAssembly to determine stability and performance of the respective systems.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[x] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[x] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
@mandarjog we can probably consider this done? Or is there anything specific we are missing?

**Comment by mandarjog** [comment]
This is now done, and is the default for 1.5.
