### ISSUE TITLE
Community Test, TCP Traffic Shifting

### ISSUE THREAD

**Issue by yxue** [istio/istio#16582]
Follow steps on this [page](https://preliminary.istio.io/docs/tasks/traffic-management/tcp-traffic-shifting/).

```
kubectl get virtualservice tcp-echo -o yaml
```

![image](https://user-images.githubusercontent.com/3491507/63798149-5e1fe200-c8be-11e9-925c-eccb03a736c1.png)

```
for i in {1..10}; do \
docker run -e INGRESS_HOST=$INGRESS_HOST -e INGRESS_PORT=$INGRESS_PORT -it --rm busybox sh -c "(date; sleep 1) | nc $INGRESS_HOST $INGRESS_PORT"; \
done
```

![image](https://user-images.githubusercontent.com/3491507/63798069-316bca80-c8be-11e9-9962-1f000a00324a.png)

**Bug description**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by hzxuzhonghu** [comment]
@yxue It seems your route does not paste completely

**Comment by hzxuzhonghu** [comment]
reproduced, and i checked both v1 and v2 belongs to ` outbound|9000|v1|tcp-echo.default.svc.cluster.local`. 
Seems the eds is not right.

**Comment by hzxuzhonghu** [comment]
I find the root cause, it is not right here, the service attribute is empty.

```
cfg := ps.DestinationRule(proxy, &Service{Hostname: hostname})
```
