### ISSUE TITLE
Implement `mesh_config.enable_auto_mtls` except for PERMISSIVE mode

### ISSUE THREAD

**Issue by incfly** [istio/istio#16586]
**Describe the feature request**

`enable_auto_mtls` behavior needs to be implemented as [per documented](https://github.com/istio/api/blob/master/mesh/v1alpha1/config.proto#L225)

This bug excludes the PERMISSIVE mode handling.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X ] Security
[ ] Test and Release
[X ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by liamawhite** [comment]
@incfly @diemtvu What's the current status on this?

**Comment by howardjohn** [comment]
@incfly is this done?

**Comment by incfly** [comment]
the implementation ends up being configuring cds the same for permissive and strict.
but yeah, it's done.
