### ISSUE TITLE
[Security] bin/push-docker script no longer works with -build-only flag

### ISSUE THREAD

**Issue by GregHanson** [istio/istio#1658]
PR #1560 changed the `security/bin/push-docker.sh` script and broke the `-build-only` flag.  CircleCI calls `make docker` :
```docker:
    $(TOP)/security/bin/push-docker ${hub} ${tag} -build-only
    $(TOP)/pilot/bin/push-docker ${hub} ${tag} -build-only
    $(TOP)/mixer/bin/push-docker ${hub} ${tag} -build-only
```
The `make` command is specifying `-build-only` so that images are only built and NOT pushed.  This is significant optimization so that our PR jobs do not need to waste time pushing images to dockerhub when the e2e tests can use local images.  The script switched to use `docker_push` instead of `tag_and_push`.  See https://github.com/istio/istio/blob/master/pilot/bin/push-docker for example format

**Comment by myidpt** [comment]
@mangchiandjjoe Jae, any chance you can fix this? Thanks.

**Comment by GregHanson** [comment]
resolved by https://github.com/istio/istio/pull/1661
