### ISSUE TITLE
Package the mixer v2 experimental WebAssembly plugin into the image.

### ISSUE THREAD

**Issue by jplevyak** [istio/istio#16590]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request** Mixer v2 as a NullVm plugin and as a WebAssembly plugin should be made a part of the image.  The WebAssembly version should not be enabled in production, but should be provided for experimentation.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[x] Test and Release
[ ] User Experience
[x] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
This is done
