### ISSUE TITLE
Traffic loss during upgrade from 1.1.x to 1.2.x

### ISSUE THREAD

**Issue by mailzyok** [istio/istio#16607]
Hi

Traffic loss is observed during upgrade from 1.1.x to 1.2.x. After investigation, it is caused by change "set normalize_path to true by default" https://github.com/istio/istio/issues/14185.

Any reason on changing the default value? Is there some workaround to avoid traffic loss for this case.

Thanks.

**Comment by mailzyok** [comment]
We just did a normal upgrade from 1.1.7 to 1.2.2 with background traffic. We notice this configuration change from false to true causing envoy restarting the current connections by removing and adding listeners, see below traces:

[2019-08-26 11:12:23.980][17][debug][config] [external/envoy/source/server/listener_manager_impl.cc:976] begin remove listener: name=b4d8cd9e-de63-4e15-b9a9-2c24b678b920
[2019-08-26 11:12:23.980][17][debug][config][external/envoy/source/server/listener_manager_impl.cc:984] unknown/locked listener 'b4d8cd9e-de63-4e15-b9a9-2c24b678b920'. no remove
[2019-08-26 11:12:23.980][17][debug][config] [external/envoy/source/server/listener_manager_impl.cc:735] begin add/update listener: name=192.168.94.55_8080 hash=15777265373841265193

Thanks

**Comment by howardjohn** [comment]
Oh so its nothing specific to `normalize_path`? So the issue is a new listener was sent causing a drain of connections on the old listener. It should be a drain, so it will hold connections for up to 45s -- were you using long lasting connections?

**Comment by mailzyok** [comment]
Yes, it is nothing specific to normalize_path. But this configuration changes triggers the drain as you mentioned. We are using long http2 connections, so the traffic are impacted during this period.

**Comment by howardjohn** [comment]
@lambdai is there anyway to force long lived connections to stay open?

**Comment by lambdai** [comment]
Sorry there is no support to maintain the long live connection at this moment. That is the restriction of envoyproxy.
Envoyproxy may move to the support named filter chain similar to RDS, where the drain connection won't happen until user actively close it. Will start to discuss by end of Oct

**Comment by mailzyok** [comment]
Thanks @lambdai @howardjohn . The cause is clear now, although it can not be fixed in a short term.
