### ISSUE TITLE
[Istio-1.3.0-rc0] Community Testing, deployment error in Istio Vault CA Integration

### ISSUE THREAD

**Issue by lei-tang** [istio/istio#16604]
**Bug description** Following the instructions on https://preliminary.istio.io/docs/tasks/security/vault-ca/, at the step "kubectl apply -f sleep-injected.yaml", get an error as follows:

~$ kubectl apply -f sleep-injected.yaml
serviceaccount/sleep created
service/sleep created
error: error validating "sleep-injected.yaml": error validating data: ValidationError(Deployment.spec): missing required field "selector" in io.k8s.ap
i.apps.v1.DeploymentSpec; if you choose to ignore these errors, turn validation off with --validate=false

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[X ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
No errors.

**Steps to reproduce the bug**
Following the instructions on https://preliminary.istio.io/docs/tasks/security/vault-ca/, at the step "kubectl apply -f sleep-injected.yaml", an error is returned.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
~$ ./bin/istioctl version --remote
client version: 1.3.0-rc.0
citadel version: 1.3.0-rc.0
galley version: 1.3.0-rc.0
ingressgateway version: 1.3.0-rc.0
nodeagent version:
nodeagent version:
nodeagent version:
pilot version: 1.3.0-rc.0
policy version: 1.3.0-rc.0
sidecar-injector version: 1.3.0-rc.0
telemetry version: 1.3.0-rc.0

~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-13T23:16:58Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.8-gke.10", GitCommit:"f53039cc1e5295eed20969a4f10fb6ad99461e37", GitTreeState:"clean", BuildDate:"2019-06-19T20:48:40Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
helm install.

**Environment where bug was observed (cloud vendor, OS, etc)**
Linux

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by duderino** [comment]
@geeknoid we need a docs approval on https://github.com/istio/istio/pull/16605 so we can close out this release blocker
