### ISSUE TITLE
[Istio-1.3.0-rc0] Community Testing, 503 error in Istio Vault CA Integration

### ISSUE THREAD

**Issue by lei-tang** [istio/istio#16606]
This bug may be related to the changes for k8s trustworthy JWT.

Bug description:
Following the instructions on https://preliminary.istio.io/docs/tasks/security/vault-ca/, at the step "kubectl exec -it $(kubectl get pod -l app=sleep -o jsonpath='{.items[0].metadata.name}') -c sleep -- curl -s -o /dev/null -w "%{http_code}" httpbin:8000/headers", get an error as follows:

~$ kubectl exec -it $(kubectl get pod -l app=sleep -o jsonpath='{.items[0].metadata.name}') -c sleep -- curl -s -o /dev/null -w "%{http_code}" httpbin
:8000/headers
503

Affected product area (please put an X in all that apply)

[ ] Configuration Infrastructure
[X ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Expected behavior
No errors, return 200.

Steps to reproduce the bug
Following the instructions on https://preliminary.istio.io/docs/tasks/security/vault-ca/.

Version (include the output of istioctl version --remote and kubectl version)
~$ ./bin/istioctl version --remote
client version: 1.3.0-rc.0
citadel version: 1.3.0-rc.0
galley version: 1.3.0-rc.0
ingressgateway version: 1.3.0-rc.0
nodeagent version:
nodeagent version:
nodeagent version:
pilot version: 1.3.0-rc.0
policy version: 1.3.0-rc.0
sidecar-injector version: 1.3.0-rc.0
telemetry version: 1.3.0-rc.0

~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-13T23:16:58Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.8-gke.10", GitCommit:"f53039cc1e5295eed20969a4f10fb6ad99461e37", GitTreeState:"clean", BuildDate:"2019-06-19T20:48:40Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}

How was Istio installed?
helm install.

Environment where bug was observed (cloud vendor, OS, etc)
Linux

Additionally, please consider attaching a cluster state archive by attaching
the dump file to this issue.

**Comment by lei-tang** [comment]
Istio release 1.3 uses new k8s JWT (https://github.com/istio/istio/pull/16147), which breaks the user guide of Istio Vault CA integration for release 1.3. The PR https://github.com/istio/istio.io/pull/4904 temporarily disables the user guide of Istio Vault CA integration for release 1.3.

**Comment by myidpt** [comment]
We will remove the Vault CA integration from istio.io.

**Comment by duderino** [comment]
@geeknoid could you also review https://github.com/istio/istio.io/pull/4904 to unblock this additional 1.3 release blocker
