### ISSUE TITLE
Please add ALB X-Amzn-Trace-Id as first class span in a trace

### ISSUE THREAD

**Issue by AceHack** [istio/istio#16617]
When using an amazon load balancer that adds X-Amzn-Trace-Id please use this to create a first client span to the trace.

https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-request-tracing.html

**Comment by douglas-reid** [comment]
What is the existing level of support for this trace id in Envoy?

**Comment by rverma-nsl** [comment]
@douglas-reid Can we reopen this ticket?
