### ISSUE TITLE
Check the JWT audience in Citadel

### ISSUE THREAD

**Issue by myidpt** [istio/istio#16637]
**Bug description**
For 1.3, we will have Citadel to check the audience equals the expected string (Citadel's "identity") in the trustworthy JWT. Now Citadel only checks the JWT is trustworthy JWT, but it doesn't check the exact audience string (due to various reasons), which is insecure.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ x ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by howardjohn** [comment]
Is this a releae blocker? I thought this was a new feature? Is this fixed by the backport of #16666?

**Comment by pitlv2109** [comment]
No. That's it.
