### ISSUE TITLE
Produce a list of images used by a given istio release

### ISSUE THREAD

**Issue by linsun** [istio/istio#16655]
**Describe the feature request**
It is desirable to have visibility to all list of images used by a given istio release, as the images are in different places among docker.io and quay.io.  One way is to reproduce this info to our existing istio.VERSION file so it captures not only control plane but also the data plane and the addons.

**Describe alternatives you've considered**
Doing this manually for each release and can be error prune.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ x] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by linsun** [comment]
@johnma14 - could you look at this?

**Comment by johnma14** [comment]
@linsun will do. Thanks.

**Comment by howardjohn** [comment]
In 1.4 we plan to get rid of istio.VERSION via https://github.com/istio/istio/issues/16887. Just want to make sure we don't waste effort here
