### ISSUE TITLE
can OLM be used with Istio operator

### ISSUE THREAD

**Issue by linsun** [istio/istio#16656]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
What is our compatability statement for OLM and istio operator in the roadmap?  Istio operator started as client side istioctl, which has no intersection with OLM.  However, as we also build the server side function for istio operator, ideally, we want users be able to use OLM with our istio operator.

Background info: Operator Lifecycle Manager (OLM) helps users install, update, and manage the lifecycle of all Operators and their associated services running across their clusters. It is part of the Operator Framework, an open source toolkit designed to manage Kubernetes native applications (Operators) in an effective, automated, and scalable way.  https://docs.openshift.com/container-platform/4.1/applications/operators/olm-understanding-olm.html

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[x ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by linsun** [comment]
@sdake could you use this to track your investigation here?

cc @morvencao

**Comment by brian-avery** [comment]
Hi @linsun @sdake  OpenShift ServiceMesh uses OLM. Let me know if you'd like any help.

**Comment by linsun** [comment]
Thank you @brian-avery !  Through our research, we believe OLM will be able to work with the upcoming operator controller.  The requirement is the operator needs to run within K8S, not as CLI in 1.3.

Another requirement is able to generate the csv file for operator to OLM: https://github.com/operator-framework/operator-sdk/blob/master/doc/sdk-cli-reference.md#gen-csv

Please correct me if I'm wrong here @brian-avery. Thanks.

**Comment by clyang82** [comment]
@linsun what is status for this task?
I saw that there has an istio operator (banzaicloud) in https://github.com/operator-framework/community-operators/tree/master/upstream-community-operators/istio/0.1.6
Do we have a plan to support OLM to manage official istio operator?

**Comment by linsun** [comment]
@clyang82 you can ping @kramvan1 for details, he is using OLM to manage istio operator.  I don't believe there is anything technical from istio operator today not suggesting OLM.  I intend to close this issue out since the validation has already been done by @kramvan1

**Comment by kramvan1** [comment]
@clyang82   The new IBM Cloud Managed Istio 1.4 offering is based upon the operator and uses OLM to handle the operator lifecycle including patch updates.    We are using the latest community OLM 0.13 and have our own config map based catalog.

**Comment by clyang82** [comment]
@linsun Thanks for your information.  @kramvan1 you are talking about IBM Cloud Managed Istio 1.4. I think we need to commit istio csv bundle [here](https://github.com/operator-framework/community-operators/tree/master/community-operators). WDYT?

**Comment by kramvan1** [comment]
@clyang82 Yes, at some point it would be great to get the new Istio operator into the hub, that would mean creating the csv/csd/project bundle.    If that is proposed, please let me know, I would like to compare the bundle with what we already have been using in the IBM Cloud.
