### ISSUE TITLE
Istio ingress gateway configuration

### ISSUE THREAD

**Issue by dhineshbabuelango** [istio/istio#16653]
Hi All, We are using istio in EKS. While looking at the istio doc for gateway configuration, its mentioned like below 

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: httpbin-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "httpbin.example.com"

In our case, we have an AWS load balancer created for ingress gateway, can we put any hostname here and access the gateway using AWS load balancer or do we need to update only AWS loadbalancer in the hosts so that we can access this using AWS loadbalancer.

Also the virtual service is created based on path specification, if I have two services listening to the same path, how can I access both the service using the same load balancer created for istio

**Comment by howardjohn** [comment]
> Also the virtual service is created based on path specification, if I have two services listening to the same path, how can I access both the service using the same load balancer created for istio

Its based on host headers, then you can determine routing based on path within that. So your services have different hosts they match on with two different VirtualServices, then they could both route `/api` (or whatever route) to wherever they need to 

I would encourage you to ask questions on https://discuss.istio.io. This issue tracker is primarily meant for bugs and feature requests
