### ISSUE TITLE
Istio couldn't handle full URL request

### ISSUE THREAD

**Issue by YuraBeznos** [istio/istio#16658]
**Bug description**
Istio couldn't handle full URL request (also reported a year ago on SO [link](https://stackoverflow.com/questions/51801664/istio-ingressgateway-couldnt-handle-full-url-request) )
```
kubectl -n istio-system exec -it istio-ilbgateway-8f844546b-gnxn4 -- /bin/bash
printf "GET / HTTP/1.1\nHost: grafana.grafanaoperator\n\n\n" | nc -v grafana.grafanaoperator 80

grafana.grafanaoperator.svc.cluster.local [172.20.31.159] 80 (?) open
HTTP/1.1 302 Found
content-type: text/html; charset=utf-8
location: /login
set-cookie: redirect_to=%252F; Path=/; HttpOnly
date: Thu, 29 Aug 2019 09:00:20 GMT
content-length: 29
x-envoy-upstream-service-time: 0
server: istio-envoy
x-envoy-decorator-operation: grafana.grafanaoperator.svc.cluster.local:80/*

<a href="/login">Found</a>.
```
and the same resource but with full uri
```
kubectl -n istio-system exec -it istio-ilbgateway-8f844546b-gnxn4 -- /bin/bash
printf "GET http://grafana.grafanaoperator/ HTTP/1.1\nHost: grafana.grafanaoperator\n\n\n" | nc -v grafana.grafanaoperator 80

grafana.grafanaoperator.svc.cluster.local [172.20.31.159] 80 (?) open
HTTP/1.1 404 Not Found
date: Thu, 29 Aug 2019 09:00:44 GMT
server: istio-envoy
content-length: 0
```

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Result should be the same.

**Steps to reproduce the bug**
the same as in description

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.1.5

**How was Istio installed?**
Via helm

**Comment by howardjohn** [comment]
@lambdai does envoy support this?

**Comment by lambdai** [comment]
Envoy proxy support parse absolute url in http1 https://github.com/envoyproxy/envoy/blob/4478c1984d17146b1ff78d0babedae2a4752b027/api/envoy/api/v2/core/protocol.proto#L38

I guess there is reason it wasn't provided at the beginning
@YuraBeznos Is there a breakage? Any library/application only provides absolute url?

**Comment by YuraBeznos** [comment]
Absolute url in requests required by some of our applications (and also part of the standard https://tools.ietf.org/html/rfc2616#section-5.1.2 )

Does it need to be enabled somehow in istio?

**Comment by lambdai** [comment]
@fpesce Do you have any concern if we allow absolute url?
IMHO it's probably safe to add it into outbound listener

**Comment by rshriram** [comment]
it should be enabled always.

**Comment by lambdai** [comment]
Default enabled now.

https://github.com/envoyproxy/envoy/pull/8329

Will verify once we bump the envoy SHA
