### ISSUE TITLE
Istio release 1.3 needs a base image pin

### ISSUE THREAD

**Issue by sdake** [istio/istio#16659]
If the base image for 1.2 is updated, the base image would also be updated for 1.3, and visa-versa.  This is not acceptable behavior.  The base images per release need to be iindependently updated.

The solution here is very much like what I have in my long running PR to do this pinning work, but instead of dealing with the complexities of breaking apart test and release processes into two separate options (currently they are muddled into one operation), we are just going to pin to `base:x.y`.  The base won't be rebuilt each PR, but instead will be pulled from the appropriate repository.

**Comment by sdake** [comment]
cc @linsun @howardjohn

**Comment by sdake** [comment]
cc @istio/release-managers-1-3  @istio/release-managers-1-2 @duderino

**Comment by duderino** [comment]
@sdake agreed this is very important.  In our darkest hour, I'm not sure though whether we'd hold back the 1.3 release for it because it's not a regression

**Comment by rlenglet** [comment]
This is done, and made it into 1.3.0-rc.1.
https://github.com/istio/istio/pull/16727
