### ISSUE TITLE
Upgrade cert-manager before LE blocks requests

### ISSUE THREAD

**Issue by gideonw** [istio/istio#16665]
**Describe the feature request**
Update cert-manager to prevent Let's Encrypt from disabling certificate renewal.
https://github.com/jetstack/cert-manager/issues/1948

**Describe alternatives you've considered**
None.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by dpiessens** [comment]
I did update the tag in the Helm template to force it to 0.8.0 and am not seeing any issues. I had it request a dummy certificate with our domain to test.

**Comment by ljakab** [comment]
> I did update the tag in the Helm template to force it to 0.8.0 and am not seeing any issues. I had it request a dummy certificate with our domain to test.

The issue I see replacing the tag in the Helm template is described in the second row of the following output:

```
$ kubectl -n istio-system get events --field-selector involvedObject.name=ingress-cert
LAST SEEN   TYPE     REASON               KIND          MESSAGE
3m27s       Normal   Generated            Certificate   Generated new private key
3m27s       Normal   GenerateSelfSigned   Certificate   Generated temporary self signed certificate
3m26s       Normal   OrderCreated         Certificate   Created Order resource "ingress-cert-3758195367"
3m3s        Normal   OrderComplete        Certificate   Order "ingress-cert-3758195367" completed successfully
3m3s        Normal   CertIssued           Certificate   Certificate issued successfully
```

A temporary certificate is created by cert-manager, and even when the Let's Encrypt certificate is issued successfully (last row), that self-signed temporary certificate remains in place:

```
* Server certificate:
*  subject: O=cert-manager; CN=example.com
*  start date: Sep 27 18:28:25 2019 GMT
*  expire date: Dec 26 18:28:25 2019 GMT
*  issuer: O=cert-manager; CN=cert-manager.local
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
```

**Comment by ljakab** [comment]
Update: replacing the tag work for me for Istio 1.2.x, but not with 1.3.x, the above results were obtained using 1.3.0. U just tried using Istio 1.2.6 with cert-manager 0.10.1 and it works well.

**Comment by Kampe** [comment]
created PR to address this: https://github.com/istio/istio/pull/17737

**Comment by wstrange** [comment]
Off topic, but it would be really nice if istio could track the more recent versions of things like cert-manager.   We have separate install procedures for cert-manager, prometheus and grafana. It would be great if istio was a one stop shop for all the things. I realize that is a tall order (a lot of testing..). 

From a strategy perspective, I wonder if istio should even attempt to install these 3rd party components?

**Comment by ljakab** [comment]
> From a strategy perspective, I wonder if istio should even attempt to install these 3rd party components?

Yes! It makes it easy to start, and if one needs more customization, one can do separate install.

**Comment by doorkey** [comment]
GKE 1.12 - using GITLAB AutoDevOps. 
Hey guys. I got an email as well. I just updated the tag in deployment file from 0.5.2 to 0.8.0. I am having this error 
2019-10-12 13:18:49.771 EEST
pkg/client/informers/externalversions/factory.go:117: Failed to list *v1alpha1.Order: the server could not find the requested resource (get orders.certmanager.k8s.io)

Any help? 

Cheers.

**Comment by howardjohn** [comment]
Please see our new doc on certmanager: https://preliminary.istio.io/docs/ops/integrations/certmanager/. We are recommending users run their own cert-manager deployments (and have stopped bundling cert-manager) to ensure they are getting the latest and greatest of cert-manager and not relying on our package which may fall out of date.
