### ISSUE TITLE
Istio/SDS-logging: There is no way to change the log level for the sdsServiceLog in node-agent. 

### ISSUE THREAD

**Issue by abhijitherekar** [istio/istio#16669]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Add a way to change the log level for the sdsServiceLog in node-agent**

**There are no alternatives**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[x] Developer Infrastructure

**Additional context**

**Comment by incfly** [comment]
@JimmyCYJ could you see if this is now supported?

**Comment by howardjohn** [comment]
Node-agent is now no longer supported in 1.5 so I think nothing is needed here

**Comment by abhijitherekar** [comment]
@howardjohn then how does the SDS work now? I mean who gives the certs to the pods?
