### ISSUE TITLE
how can redisquota work with a redis use password?

### ISSUE THREAD

**Issue by jianglijie** [istio/istio#16686]
I find the config for redusquota in docs. It show `redisServiceUrl: <redis_server_url>` for the redis instance url , how can I config it with password?(redis auth)

**Comment by hzxuzhonghu** [comment]
cc @kyessenov

**Comment by esnible** [comment]
https://discuss.istio.io is a good place to ask questions.

**Comment by douglas-reid** [comment]
Closing, as is a duplicate of: https://github.com/istio/istio/issues/14830
