### ISSUE TITLE
enhancement: scope xds push

### ISSUE THREAD

**Issue by ChenLingPeng** [istio/istio#16685]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Currently, pilot will trigger a full push(LDS+RDS+CDS+EDS) to all scoped sidecar(determined by Sidecar CRD) whenever a resource update defined [here](https://github.com/istio/istio/blob/master/pkg/config/schemas/schemas.gen.go).
But maybe there is a chance to send a subset of xDS resource to sidecar. I notice that the istio resource is related to some xDS. i.e, a virtualservice may only affect the LDS and RDS, then pilot can only send LDS and RDS config to sidecar if only virtualservice update.
So I'd like to introduce scope for each istio CRD, which defines which xDS config will be affected if the resource update.

I'd like to know if it makes sense for you and if it worth to do since it may make xDS push more complicate.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[X] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by hzxuzhonghu** [comment]
There are many tries on this opt. Mainly on namespace scope. This thought looks good, though it needs careful analysis on which api influence which xDS.  In the long run, the best solution is like this: if a new service added, only gen its related xds and the push to associated proxies. Incremental Xds~

**Comment by ChenLingPeng** [comment]
Namespace scope is great and can combine with this since they are in two different dimensions and seems has no conflict with each other. Do we have any plan on _Incremental Xds_

**Comment by hzxuzhonghu** [comment]
incremental xds is not of high priority now, as we can both define `Sidecar` and ExportTo now.
