### ISSUE TITLE
AWS ALB: Unable to access prometheus and grafana services

### ISSUE THREAD

**Issue by VinothChinnadurai** [istio/istio#16692]
**Bug description**
Unable to load prometheus and grafana services through AWS ALB.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Through Route53 Url -> AWS ALB -> Prometheus service should load in browser
https://domainurl/graph

**Steps to reproduce the bug**
1. Change the Istio ingress gateway type to NodePort and installed istio
helm template \
    --set gateways.istio-ingressgateway.type=NodePort \
    --set prometheus.enabled=true \
    --set grafana.enabled=true \
    --set tracing.enabled=true \
    --set kiali.enabled=true \
    --set "kiali.dashboard.jaegerURL=http://jaeger-query:16686" \
    --set "kiali.dashboard.grafanaURL=http://grafana:3000" \
    install/kubernetes/helm/istio \
    --name istio --namespace istio-system > $HOME/istio.yaml
kubectl apply -f $HOME/istio.yaml

istio-ingressgateway     NodePort    xx.xx.xx.xx    <none>        15020:30768/TCP,80:31380/TCP,443:31390/TCP,31400:31400/TCP,15029:31535/TCP,15030:31703/TCP,15031:32626/TCP,15032:30917/TCP,15443:30107/TCP

2. Placed the ALB through ALB Ingress Controller and Ingress
3. Under Rules pointed the ingressgatewayservice node port(31703) to ALB with a sample host(domainurl) and path(/graph)

4. Tried access prometheus service via https://domainurl/graph. It does not load the service.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-29T16:15:10Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.8-eks-a977ba", GitCommit:"a977bab148535ec195f12edc8720913c7b943f9c", GitTreeState:"clean", BuildDate:"2019-07-29T20:47:04Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS EKS

Am i missing something? 
Do we need to create Virtual service, Gateway, destination rule for these services(prometheus and Grafana) in order to make the above one work or am i missing something?

Appreciate your help on this to resolve the problem.

**Comment by howardjohn** [comment]
what if you directly access the ingrssgateway not through the alb? does it work then? Did you follow https://istio.io/docs/tasks/telemetry/gateways/

**Comment by VinothChinnadurai** [comment]
@howardjohn thanks for the link. After setting up Virtualservice, gateway and Destination rule, it works perfect. I need input on how to use prometheus and grafana for multi environments. Say I have two different environmets like test, dev in my EKS through different namespaces. In such case, how we can monitor that different namespace. Kindly help with us.

**Comment by howardjohn** [comment]
Prometheus monitors should he set up for all namespaces by default

**Comment by VinothChinnadurai** [comment]
Yeah.. is that possible to set it separately for individual namespace? or do we can have multiple istio control planes for each environment hosted in some unique namespaces

**Comment by howardjohn** [comment]
I am not the telemetry expert but I haven't heard of anyone doing that - I suspect we don't support it out of the box but you could configure Prometheus to do it

**Comment by VinothChinnadurai** [comment]
Okay @howardjohn . Thanks for your timely help. We can close this
