### ISSUE TITLE
Support W3C Trace Context for distributed tracing.

### ISSUE THREAD

**Issue by pcwiese** [istio/istio#16703]
Istio current supports distributed tracing via x-b3-* header propagation (via Envoy support). What is the timeline, if any, to support distributed trace context via https://www.w3.org/TR/trace-context/. This is going to be the recommended standard and will be fully supported by OpenTelemetry (the next version of the OpenTracing/OpenCensus merger).

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by bianpengyuan** [comment]
Seems like w3c tracing context is supported in upstream envoy opencensus tracer:
https://github.com/envoyproxy/envoy/blob/0b0aa3f81e6e58327966f8ffa49932c5999a8306/api/envoy/config/trace/v2/trace.proto#L180

@mandarjog do we plan to add global config for opencensus tracer?

**Comment by mandarjog** [comment]
We do have it in mesh config. We can add more there, or change it to opaque string.

**Comment by brianwolfe** [comment]
@mandarjog, the OpenCensus instrumentation & propagation is only supported for StackDriver, see: https://github.com/istio/istio/blob/b9defec56fd417b660912426ee15bb2b6a66cede/tools/packaging/common/envoy_bootstrap_v2.json#L604-L622

The OpenCensus support could actually be used for any of Zipkin, Stackdriver, or OpenCensus Agent exporters. Do you think it would be reasonable to add configuration for the other two OpenCensus formats? We would like to be able to use the OpenCensus protocol to emit traces out of Istio. We can take on the implementation if you agree makes sense as an addition to the Istio API.

That would also make the tracing description around OpenCensus-supported tracers less lonely (right now it's just Stackdriver): https://github.com/istio/istio/issues/19171

wdyt?

**Comment by jnovick** [comment]
Hey, has there been any update with whether W3C will be supported in Istio?
