### ISSUE TITLE
Improve istioctl for troubleshooting security PKI issues.

### ISSUE THREAD

**Issue by JimmyCYJ** [istio/istio#16724]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
We use several tools to investigate security PKI issues. 
On Envoy, we check /config_dump, /certs, log, and we change log level using curl command.
On Citadel agent, we check log and CtrlZ dashboard, and change log level per scope via CtrlZ. We also check /debug endpoint.
On Citadel we check log and CtrlZ. We will add debug endpoint into Citadel later.

It would be nice if we could use istioctl to operate all these tools. For example, use istioctl to change log level of any component, and get debug info from debug endpoint of a particular component.

In the long term, we can add a centralized troubleshooting dashboard to monitor all the debug information and config log level of the mesh.

https://github.com/istio/istio/issues/15789 adds sds diagnostic information into istioctl.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**
https://github.com/istio/istio/issues/13439

**Comment by esnible** [comment]
@JimmyCYJ `istioctl` already has tools for investigating /config_dump.  What do you get from the config_dump that you can't get with `istioctl proxy-config`?

We do not have anything to look at /certs.  I would like to see a command that outputs the cert expiration and serial number.  The proposed `istioctl experimental sds` will print this, but only for SDS secrets.  Is there anything else you are looking for.

I also use the Envoy logs but I retrieve them using `kubectl logs -c istio-proxy`.  What additional function are you requesting?

I also set the Envoy log level using curl, and agree that it is difficult today.  I use `kubectl exec <pod> -c istio-proxy -- curl -X POST http://localhost:15000/logging?level=<level>`  Are you requesting something like this, or something else?

I have not checked Citadel.  What kinds of things do you check it for?

**Comment by JimmyCYJ** [comment]
@esnible Thanks for asking.
For Citadel agent and Citadel, we propose to add debug endpoints. @Monkeyanator already adds a debug endpoint into Citadel agent, and the istioctl experimental sds collects outputs from that endpoint. I would like to have istioctl to get output from Citadel's debug endpoint as well.

We have added CtrlZ into Citadel agent and Citadel, that supports changing the log level for each scope at runtime. To change log level, we need to use port-forward to CtrlZ port, open CtrlZ page in a browser and click the log scope section. I would like to support istioctl to do two things. (1) use istioctl to get all log scopes from a specified Citadel agent or citadel instance (2) use istioctl to change the log level at any scope on a Citadel agent or Citadel instance.

It would be nice if we can also let istioctl to change proxy log level, instead of running kubectl exec to change each proxy container. For example, if we want to turn on debug level log for all sidecars in a namespace, it would be convenient to run istioctl once.

I am thinking about supporting istioctl to do all troubleshooting stuff for the entire mesh, rather than using istioctl to tackle some issues and kubectl to tackle other issues. If that is supported, we could also build a dashboard that runs on top of istioctl for troubleshooting.

**Comment by esnible** [comment]
I am nervous about exposing CtrlZ and a debug port to Citadel.  If the debug level can be set without using K8s APIs, then a pod in the cluster could cause Citadel to log.  That should not be a problem but sometimes log messages and backtraces include secrets that would help an attacker.  I don't want to be responsible for a privilege escalation attack.

When I want to run a command on all the pods in a namespace I do

```
ns=default
for pod in $(kubectl get pods -n $ns -o custom-columns=NAME:.metadata.name --no-headers); do kubectl -n $ns <command> $pod ; done
```

**Comment by esnible** [comment]
@JimmyCYJ Do you want to work on this?  Or write up a proposal?
