### ISSUE TITLE
Secure coding & testing practices that affect all new work -code-mauve style

### ISSUE THREAD

**Issue by fpesce** [istio/istio#16725]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
This task is a spin off of #13618 , the goal here might be to verify the state of golangci linter, see if we're using the latest linters, and if all codebase (including older) passes through linting without errors.
Also we might want to investigate possible secure coding practice not covered by existing linting.

As for the testing, this is TBD (was not explicitly described in original issue).

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[X] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
@fpesce this is a P0 for 1.4, what is left to be done?
