### ISSUE TITLE
istio/tools makefiles broken with BUILD_WITH_CONTAINER, cannot connect to kubernetes

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#16736]
There are a lot of commands in istio/tools that connect to kubernetes. These are not working with BUILD_WITH_CONTAINER, because the container doesn't have access to kubernetes.

I am not sure a good way to fix this.. you could mount `~/.kube`, but technically kube contexts can be anywhere in the file system. A standard setup (and kind!) will use this though so it may be sufficient for 99% of cases.

**Comment by geeknoid** [comment]
The initial solution here is to move tests out of the tools repo and into the newly minted tests repo. This would allow the tests to not use BUILD_WITH_CONTAINER if we need to for a while.

I'm reassigning to @mandarjog for moving the tests over.

**Comment by howardjohn** [comment]
sure, it's not about just tools though, this will break every repo that
uses kubectl. installer, Istio, etc
