### ISSUE TITLE
For my jaeger only jaeger-query service, no other services

### ISSUE THREAD

**Issue by idefav** [istio/istio#16734]
![image](https://user-images.githubusercontent.com/6405415/64064429-e80bda00-cc33-11e9-9d11-2eb88d198a89.png)

Istio version: 1.2.4

For my jaeger only jaeger-query service, no other services!!!

**Comment by howardjohn** [comment]
Please fill out the issue template. Without knowing your set up, it is impossible to help you with this.

See also https://istio.io/faq/distributed-tracing/, https://istio.io/docs/tasks/telemetry/distributed-tracing/, https://istio.io/docs/tasks/telemetry/distributed-tracing/jaeger/
