### ISSUE TITLE
istio/tools cannot gather latency data points for "both" mode

### ISSUE THREAD

**Issue by carolynhu** [istio/istio#16739]
With Mixer or without Mixer:
When I run perf/benchmark test, previously, `baseline` mode hit 503 error as the date of 08/29
Currently,  after I rebased master which has this PR included https://github.com/istio/tools/pull/312, `baseline` mode works, but `both` mode hit 503 error.
Here is the error message:
```
kubectl --namespace twopods exec -i -t fortioclient-66d6795c8-zlqvh  -- fortio load -c 64 -qps 1000 -t 240s -a -r 0.00005  -httpbufferkb=128 -labels 19547637_qps_1000_c_64_1024_both http://fortioserver:8080/echo?size=1024
Defaulting container name to captured.
Use 'kubectl describe pod/fortioclient-66d6795c8-zlqvh -n twopods' to see all of the containers in this pod.
Fortio 1.3.1 running at 1000 queries per second, 32->32 procs, for 4m0s: http://fortioserver:8080/echo?size=1024
07:02:24 I httprunner.go:82> Starting http test for http://fortioserver:8080/echo?size=1024 with 64 threads at 1000.0 qps
07:02:24 W http_client.go:679> Parsed non ok code 503 (HTTP/1.1 503)
Aborting because error 503 for http://fortioserver:8080/echo?size=1024: "HTTP/1.1 503 Service Unavailable\r\ncontent-length: 91\r\ncontent-type: text/plain\r\ndate: Sun, 01 Sep 2019 07:02:24 GMT\r\nserver: envoy\r\n\r\nupstream connect error or disconnect/reset before headers. reset reason: connection failure"
command terminated with exit code 1
```

**Comment by carolynhu** [comment]
cc @lambdai @mandarjog

**Comment by mandarjog** [comment]
@carolynhu 
1. please get config dumps from both client and server sidecars.
2. Also check if “serverside” only is also facing this issue. Since the recent  changes are on the server side, I expect that to fail.

**Comment by lambdai** [comment]
Another thing you can do is to gather the metrics of the particular cluster something equivalent to curl localhost:15000/stats on all the envoy in the flow
