### ISSUE TITLE
Run pilot e2e from dev machine

### ISSUE THREAD

**Issue by diemtvu** [istio/istio#1673]
In the old pilot repo, I can run bin/e2e from my working machine (actual tests were still run on gke cluster, but images were built locally from my machine). However, in the new repo, we stop building the (test) mixer image for this e2e, so it no longer works.

What is the right way to run pilot e2e nowadays? Should we add mixer image to the pilot/bin/push-docker to make it work again?

**Comment by rkpagadala** [comment]
in pilot directory I am running
make e2etest HUB=<your docker repo name> TAG=<your tag name> TESTOPTS="-mixer=false"

**Comment by diemtvu** [comment]
This command assumes you already have the images, right? Is there any command to build all images in the first place, including mixer images?

**Comment by GregHanson** [comment]
Local integration test can run against minikube.  Steps for installing minikube and what params to run it with can be found here:
https://github.com/istio/istio/blob/master/bin/testEnvRootMinikube.sh#L37

Integration tests can be run locally using the following commands as an example

```
make build test-bins docker docker.push HUB=<$HUB> TAG=<$TAG>
make e2e_pilot TESTOPTS="--logtostderr --skip-cleanup -mixer=true -auth=disable  -use-sidecar-injector=false" HUB=<$HUB> TAG=<$TAG>
```
