### ISSUE TITLE
[Discussion]  remove workload label update support

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#16743]
Should we remove the support for pod label update in k8s registry? 

The benefits would reduce the complexity currently caching/comparing all the workload labels.

And as the use case changing pod labels is very rare, i believe it is safe to remove this. 

**Note**: if we stop serving this, we should document explicitly if users want to update labels, they need to recreate workloads.

**Comment by hzxuzhonghu** [comment]
cc @istio/wg-networking-maintainers

**Comment by howardjohn** [comment]
My understanding is in k8s this only happens if you directly modify a pod, are there other ways?

And what about other registries? since we would want to remove it completely not just for k8s? 

I'm leaning towards remove it

**Comment by hzxuzhonghu** [comment]
>My understanding is in k8s this only happens if you directly modify a pod, are there other ways?

Yes, if we update that by deployment labels. the previous pod will be deleted and a new one comes up . So it does not matter in this case.

>And what about other registries?

It will not influence other registries.

**Comment by rshriram** [comment]
Other registries do not support dynamic label updates. They all require recreating the workload

**Comment by rshriram** [comment]
I am up for doing this as well.

**Comment by howardjohn** [comment]
Done in #16748. Thanks!
