### ISSUE TITLE
build-tools needs support for kind/dind

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#16756]
Most of our integration testing relies on being able to run dind and kind. Currently, the build-tools docker image does not support this, although it does have the actual docker and kind binaries in the image.

Requirements for CI:
* `docker run` works from within the image. Presumably this also means `kind create cluster` works as well.

In order to do this in the old image, we had a startup script running `service docker start`. This does not work in the new image, likely we remove some data needed for it to work or something?

Requirements for human developers:
* `kind create cluster` creates a cluster that remains after the command is complete

While the build tools container is ephemeral, kind clusters should not be. Otherwise, it is extremely slow to recreate a cluster every time you do a command and makes debugging harder since the cluster will be torn down each time. There are two options I see here:

* Create the cluster outside of the docker container (`kind-cluster` and `build-tools` container are both running in the host's docker environment). This seems like a good option if its possible. Seems like it should be possible
* Make `build-tools` not ephemeral. This is the approach istio/installer takes. We make a docker image that contains all of our build tools as well as the kind node image, then we spin up a kind cluster and any time we run commands, we do `docker exec` instead of `docker run`.

See also https://github.com/istio/istio/issues/16736

**Comment by howardjohn** [comment]
Oh weird, I thought I tried `-v /var/run/docker.sock:/var/run/docker.sock` and things weren't working but mustve done something wrong. Seems using that, I can now `docker run` and it will create it on the host docker!

`kind create cluster` also works! but we need to give access to the kubectl context on the host, as in https://github.com/istio/istio/issues/16736. I think we can do this by mounting ~/.kube though. What is weird is inside the docker container I cannot connect to the kind cluster, but I can from the host (once ~/.kube is mounted)

For prow I think we just need to add the same volume, I will try it out

**Comment by howardjohn** [comment]
Kubernetes prow team explicitly forbids mounting docker.sock and does `service docker start` instead

**Comment by sdake** [comment]
cc @sdake

**Comment by howardjohn** [comment]
done
