### ISSUE TITLE
SDS no longer works on Kubernetes 1.12, breaking tests

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#16754]
Our Kubernetes 1.12 tests are (somewhat intentionally) broken by https://github.com/istio/istio/pull/16666. We need to either

1. Make SDS work on 1.12 still
2. Make the test still pass on Kubernetes 1.12, by skipping or whatever is needed
3. Decide we don't care and stop testing/supporting Kubernetes 1.12

**Comment by howardjohn** [comment]
https://github.com/istio/istio/pull/16912 will allow us to turn tests back on

**Comment by pitlv2109** [comment]
Should we close this?
