### ISSUE TITLE
set interval for envoy get pilot config

### ISSUE THREAD

**Issue by blueskyll** [istio/istio#16751]
istio version : 1.1.5
In our environment, traffic rules can take effect only after a few second(usually 4-5s), what is the default interval for envoy to get pilot config?  Can we update this value?

**Comment by howardjohn** [comment]
pilot pushes config to envoy after a 100ms delay (it will try to group multiple changes at once together), so it's likely caused by pilot being overloaded not an artificial delay. Is pilot cpu high?

If you want to reduce this I would recommend scaling to Pilot, using Sidecar resource to reduce amount of config sent, or upgrading to 1.3 in a couple weeks which is much much faster

**Comment by blueskyll** [comment]
> pilot pushes config to envoy after a 100ms delay (it will try to group multiple changes at once together), so it's likely caused by pilot being overloaded not an artificial delay. Is pilot cpu high?
> 
> If you want to reduce this I would recommend scaling to Pilot, using Sidecar resource to reduce amount of config sent, or upgrading to 1.3 in a couple weeks which is much much faster

Thanks. It seems pilot-discovery container consumes lots of cpu and pilot container does't,  I will update to 1.3 and observe changes.

**Comment by howardjohn** [comment]
pilot pod has 2 containers discovery and istio-proxy. discovery is the one doing all the work, istio-proxy is just the sidecar

**Comment by blueskyll** [comment]
> pilot pod has 2 containers discovery and istio-proxy. discovery is the one doing all the work, istio-proxy is just the sidecar

Oh, got it, by the way, is kubernetes 1.10 compatible with istio 1.3?

**Comment by howardjohn** [comment]
we test support 1.13-1.15 but test 1.12 as well. So 1.10 might work but we don't test it

**Comment by blueskyll** [comment]
> we test support 1.13-1.15 but test 1.12 as well. So 1.10 might work but we don't test it

ok, thanks, I'll have a try.

**Comment by blueskyll** [comment]
![image](https://user-images.githubusercontent.com/7546095/64149803-84fb8c80-ce59-11e9-8fc0-a3f08af71d5c.png)
one more question, eds here is always synced(50%),  why not 100%?

**Comment by howardjohn** [comment]
Its just an implementation detail, in new release we removed it because it
is misleading. 50% is ok

**Comment by blueskyll** [comment]
> pilot pushes config to envoy after a 100ms delay (it will try to group multiple changes at once together), so it's likely caused by pilot being overloaded not an artificial delay. Is pilot cpu high?
> 
> If you want to reduce this I would recommend scaling to Pilot, using Sidecar resource to reduce amount of config sent, or upgrading to 1.3 in a couple weeks which is much much faster

Why discovery container need so much cpu when group changes?

**Comment by howardjohn** [comment]
it generates a lot of config and pushes it to every proxy in the mesh. In
pilot 1.3 it uses 10x less CPU. If you have a big mesh define  Sidecar
resource to reduce cpu
