### ISSUE TITLE
[Discussion] Enable a way to generate ingress & egress gateways per namespace

### ISSUE THREAD

**Issue by kriston13** [istio/istio#16750]
I see this come up in various places:
- https://stackoverflow.com/questions/51835752/how-to-create-custom-istio-ingress-gateway-controller
- https://knative.dev/docs/serving/setting-up-custom-ingress-gateway/
- https://stackoverflow.com/questions/56826263/how-i-can-make-istio-supports-multiple-custom-ingress-gateway-in-different-names

And I myself have a use case for it, where I want:
- a dev/test cluster shared across multiple teams with their own loadbalancer & gateway configurations, 
- a production cluster that has a dedicated loadbalancer for high volume traffic, and another for intermittent traffic

However, there is no documentation around it, nor any *obvious* way to extract the `Istio/charts/gateways/templates` files. 

What do you all think? Is there a use case for such an activity?

**Comment by howardjohn** [comment]
I am surprised there is no docs, I think this is a fairly common and supported pattern

Especially well supported with the new installer we are working on https://github.com/istio/installer

**Comment by howardjohn** [comment]
Here are docs for doing it for just SDS: https://istio.io/docs/tasks/traffic-management/ingress/secure-ingress-sds/

**Comment by kriston13** [comment]
That specific link actually is more about configuring the gateway, rather than the ingress gateway.

However, it DOES lead to this: https://istio.io/blog/2019/custom-ingress-gateway/

Which kinda shows my point... Point 7 says the equivalent of "copy this `yaml` and use it to create a new ingress gateway". So if that `yaml` isn't kept up to date, then future Istio versions may have issues.

What would be ideal would be a guide on how to use the embedded `gateway` chart to deploy new ingress gateways. I might poke.

Also, that installer thing looks great.

**Comment by howardjohn** [comment]
you can deploy just part of a helm chart with some flag like -x I believe..
That may put you in the right direction at least
