### ISSUE TITLE
Feature - add support for envoy lua http filters

### ISSUE THREAD

**Issue by nmnellis** [istio/istio#1677]
Envoy recently added support to inject filters via lua scripts. [Lua Http Filter](https://github.com/envoyproxy/envoy/blob/986432ac0aca514b62bcf58e8cf51d6c17433675/docs/configuration/http_filters/lua_filter.rst). It would be great to configure and add these filters via pilot.

**Comment by argeualcantara** [comment]
Hi, I'd like to take a look into this.

**Comment by nmnellis** [comment]
@argeualcantara This actually has been implemented and im in the process of testing it out now, because this is an envoy specific feature it is not supported directly, instead the development team decided to expose webhooks that pilot can call to modify the configuration before it is delivered to envoy. I will be closing this issue now as well. https://github.com/istio/istio/pull/2829

**Comment by mandarjog** [comment]
https://github.com/mandarjog/istioluawebhook

I have an example of this working. A golang version is coming soon.

**Comment by argeualcantara** [comment]
@mandarjog awesome man, I'll take a look

**Comment by andraxylia** [comment]
@mandarjog  Will this work with Envoy v2 also?

**Comment by nmnellis** [comment]
@linsun we are tracking this feature in v2 envoy correct?

**Comment by mandarjog** [comment]
@andraxylia for `lua` specifically, we are planning to model it in Istio directly.
It will not be done thru the webhook in v2.

Additionally we need a separate webhook for v2, to do other things.

**Comment by mandarjog** [comment]
I propose we use this issue to track V2 lua filters.

**Comment by linsun** [comment]
subscribe

**Comment by cmluciano** [comment]
@mandarjog are you owning this feature?

**Comment by mandarjog** [comment]
yes.

**Comment by linsun** [comment]
@esnible @mbanikazemi

**Comment by spikecurtis** [comment]
I have an API proposal up here: https://github.com/istio/api/pull/479

Your feedback please
