### ISSUE TITLE
Merge `istioctl experimental analyze` into `istioctl validate`

### ISSUE THREAD

**Issue by sushicw** [istio/istio#16777]
`istioctl experimental analyze` is a new experimental command to support multi-object analysis & validation. `istioctl validate` already exists, and does single-object validation. Rather than having disjoint commands for the job of fully validating istio config, we'd like to combine them, so that `istioctl validate` can handle both single and multi-object validation, against either files or a live cluster. 

For more context, see: 
* https://github.com/istio/istio/pull/16350
  * [This comment thread](https://github.com/istio/istio/pull/16350#discussion_r320370264) in particular
* [Multi-Object Validation In Galley & Command-Line](https://docs.google.com/document/d/1m19jkLyiIXNmUH_TYClRH-IOmuCJO4-vduy5KaCa99E/edit#)
* [Multi-Object Validation In Istio](https://docs.google.com/document/d/1xjzjYN-j5peH5iVF3XxE02-BtAftrCh7EEULQWGhkDY/edit#heading=h.qex63c29z2to)

**Affected product area (please put an X in all that apply)**

[X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Comment by esnible** [comment]
I think we agreed to call it `istioctl experimental describe`, not `analyze`.

**Comment by sushicw** [comment]
> I worked on`istioctl experimental describe`, which PR is `analyze`?

https://github.com/istio/istio/pull/16350. (Not yet in master, but should be imminently).

**Comment by sushicw** [comment]
@ozevren pointed out that if we wrap the existing single-object validation as an analyzer, we can accomplish this goal and also allow for things like detecting validation errors even if the validation webhook is disabled (Because it can appear in the status field if it's part of the analyzer suite). If we do this we may also want to make that analyzer only conditionally run (e.g. if webhook is enabled, skip the single-object validation stuff since it will have already been handled).

**Comment by sushicw** [comment]
Design doc that covers this: https://docs.google.com/document/d/1KuxDRPPt283jx_cIs2C9sFHjoHvoskJt3IGqhPJVHtM

**Comment by esnible** [comment]
Analyze calls the old validators.  There is nothing that `validate` will catch that `analyze` won't.  There is nothing structured about the `validate` output, or the `$?` level returned.  They are basically merged already.  We should "graduate" `x analyze` into `validate` in 1.5 or 1.6.

I'd like to see a UI improvement.  Currently all the errors reported by `analyze` appear on multiple lines, unlike the new analyzers.  I suggest the Analyzer that calls that old framework method see if it was given a github.com/hashicorp/go-multierror instead of a regular Go error, and if so call multierror.WrappedError() and feed each one individually the the Analyze framework.  This would restore structure to the output.

@sushicw What do you think?

**Comment by sushicw** [comment]
"Graduating" `x analyze` into `validate` is certainly the plan of record. The concerns I have that are giving me second thoughts:
* We've started evangelizing `analyze` as `analyze`, and switching the name is likely to cause confusion. 
* If anyone is depending on the current output of `validate`, we'll break them. 

Neither of these is a show-stopper, and I guess both are manageable with adequate communication. 

For the second issue you mention, avoiding the awkward "nested" message structure, that seems very doable. I'll take a quick crack at it.

**Comment by sushicw** [comment]
I'm increasingly leaning towards adding a deprecation notice to `istioctl validate` and redirecting users to `analyze` as being the right path to take. Does anyone have any further thoughts about this?

**Comment by davidebbo** [comment]
> I'm increasingly leaning towards adding a deprecation notice to `istioctl validate` and redirecting users to `analyze` as being the right path to take. Does anyone have any further thoughts about this?

Sounds good to me. Though we probably can't do that until analyze is no longer under experimental.
