### ISSUE TITLE
e2e-dashboard Citadel test failure in postsubmit

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#16775]
https://prow.istio.io/view/gcs/istio-prow/logs/e2e-dashboard-master/6501

```
    --- FAIL: TestDashboards/Citadel (1.94s)
        dashboard_test.go:156: For Citadel, checking 12 queries.
        dashboard_test.go:181: Expected a metric value for 'citadel_server_csr_count{job="citadel"}', found no samples: model.Vector{}
        dashboard_test.go:181: Expected a metric value for 'citadel_server_success_cert_issuance_count{job="citadel"}', found no samples: model.Vector{}
        dashboard_test.go:181: Expected a metric value for 'citadel_server_csr_parsing_err_count{job="citadel"}', found no samples: model.Vector{}
        dashboard_test.go:181: Expected a metric value for 'citadel_server_authentication_failure_count{job="citadel"}', found no samples: model.Vector{}
```

Seems likely related to recent changes to citadel metrics

**Comment by Monkeyanator** [comment]
I believe tests began to fail when #16280 was merged, and then was fixed when #15784 (which ignores more of the Citadel metrics) got merged. Could be that #16280 passed CI before Citadel dashboard test was in. Still need to address the issue that migration from Prom breaks metric tests where the value remains at zero.

Should be safe to close.
