### ISSUE TITLE
Missing template causes panic in Mixer

### ISSUE THREAD

**Issue by theganyo** [istio/istio#1678]
When I failed to register a custom template in mixer/template/BUILD, Mixer crashed with the following error. Hopefully, this could be handled in a more graceful manner.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2051e73]

goroutine 1 [running]:
istio.io/mixer/pkg/runtime.(*handlerFactory).Build(0xc4202315c0, 0xc42037b230, 0xc4200a0a28, 0x1, 0x1, 0x2dc18e0, 0xc4203ce6c0, 0x100b4a0, 0xffffffffffffffff, 0x0, ...)
	pkg/runtime/handler.go:116 +0x273
istio.io/mixer/pkg/runtime.(*Controller).publishSnapShot.func1(0xc42037b230, 0xc4200a0a28, 0x1, 0x1, 0xc42039e8a8, 0x1, 0xc42039e978, 0x2258700)
	pkg/runtime/controller.go:136 +0x145
istio.io/mixer/pkg/runtime.(*handlerTable).initHandler(0xc4201cd458, 0xc4203a8d20)
	pkg/runtime/handlerTable.go:147 +0x267
istio.io/mixer/pkg/runtime.(*handlerTable).Initialize(0xc4201cd458, 0xc42037b110)
	pkg/runtime/handlerTable.go:135 +0x381
istio.io/mixer/pkg/runtime.(*Controller).publishSnapShot(0xc4201b3c20)
	pkg/runtime/controller.go:146 +0x2b3
istio.io/mixer/pkg/runtime.startController(0x2dc2b60, 0xc42025b680, 0xc42025b140, 0xc4203bae40, 0x2dc4160, 0xc42025acf0, 0x2da6660, 0xc4201ec100, 0x2469b71, 0x13, ...)
	pkg/runtime/init.go:112 +0x23c
istio.io/mixer/pkg/runtime.New(0x2dc4160, 0xc42025acf0, 0xc4202fae60, 0xc4202fae80, 0x2469b71, 0x13, 0x24618c1, 0xc, 0x2dc2b60, 0xc42025b680, ...)
	pkg/runtime/init.go:43 +0x11a
istio.io/mixer/cmd/server/cmd.setupServer(0xc4202bc000, 0xc4203bae40, 0xc420010500, 0xa, 0xa, 0xc4204023d0, 0x2, 0x2, 0x24e7740, 0x24e7738, ...)
	cmd/server/cmd/server.go:286 +0x5ba
istio.io/mixer/cmd/server/cmd.runServer(0xc4202bc000, 0xc4203bae40, 0xc420010500, 0xa, 0xa, 0xc4204023d0, 0x2, 0x2, 0x24e7740, 0x24e7738)
	cmd/server/cmd/server.go:439 +0x12c
istio.io/mixer/cmd/server/cmd.serverCmd.func2(0xc4204e5200, 0xc4203bb1a0, 0x0, 0x3)
	cmd/server/cmd/server.go:143 +0x7b
github.com/spf13/cobra.(*Command).execute(0xc4204e5200, 0xc4203bb0b0, 0x3, 0x3, 0xc4204e5200, 0xc4203bb0b0)
	external/com_github_spf13_cobra/command.go:647 +0x234
github.com/spf13/cobra.(*Command).ExecuteC(0xc4204e4000, 0xc4204e5440, 0xc4204e5200, 0xc4204e4240)
	external/com_github_spf13_cobra/command.go:734 +0x2fe
github.com/spf13/cobra.(*Command).Execute(0xc4204e4000, 0x4, 0x4)
	external/com_github_spf13_cobra/command.go:692 +0x2b
main.main()
	cmd/server/main.go:43 +0x248
```

**Comment by mandarjog** [comment]
Did this fail on startup? Or failed at a later time?

I agree It should not sigsegv .

I think it is better to fail hard on internal inconsistencies. An explicit panic is better with a clear error message that states missing template info. 

/cc @guptasu

‘’’
		// ti should be there for a valid configuration.
		ti, _ := h.tmplRepo.GetTemplateInfo(tmplName)
‘’’
Code already states that it expects valid configuration.

**Comment by guptasu** [comment]
This is broken since we are not yet validating the config during config
ingestion. There is  inot much we can do during runtime.

Will take a look to handle this better.

**Comment by mandarjog** [comment]
I don’t think this is strictly related to config Validation. An adapter that is a part of the Mixer build is using an unknown template. This should fail build validation and must fail a unit test.

**Comment by GregHanson** [comment]
@mandarjog is this still a problem in mixer or has validation logic been added??

**Comment by guptasu** [comment]
@jmuk I know you had a PR that was validating config during ingestion if the template referenced by instance config is valid or not ? This problem will go away if we reject the config during ingestion time.
Looking at the code, we are still doing the same thing and expect the config to be valid before.

@GregHanson is this blocking your development ? We are working on a new runtime2 design, and we can address this issue there as a temporary thing, but I think in the long term, we should reject configs that have broken references.

**Comment by guptasu** [comment]
@jmuk friendly ping
