### ISSUE TITLE
Helm: Secret name mismatch in K8S ingress gateway

### ISSUE THREAD

**Issue by maxdebayser** [istio/istio#16784]
**Bug description**

In `istio/install/kubernetes/helm/istio/charts/gateways/templates/preconfigured.yaml` the certificate mount path is hardcoded to:

      serverCertificate: /etc/istio/ingress-certs/tls.crt
      privateKey: /etc/istio/ingress-certs/tls.key

**Affected product area (please put an X in all that apply)**

[] Configuration Infrastructure
[ ] Docs
[ X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

It seems to me that it should reflect the configuration values in `istio/install/kubernetes/helm/istio/charts/gateways/values.yaml`, specifically `gateways.istio-ingressgateway.secretVolumes.mountPath`. Indeed, when I edit the hardcoded path to ingressgateway-certs, the Ingress example here (https://preliminary.istio.io/docs/tasks/traffic-management/ingress/ingress-certmgr/#setting-up-a-demo-application)  starts to work.

**Steps to reproduce the bug**

Install istio with helm according to the documentation and install the Ingress example.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

```
$ istioctl version --remote
client version: 1.2.4
citadel version: 1.2.4
galley version: 1.2.4
ingressgateway version: 1.2.4
pilot version: 1.2.4
policy version: 1.2.4
sidecar-injector version: 1.2.4
telemetry version: 1.2.4

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

Helm

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by maxdebayser** [comment]
If this is confirmed to be a problem I'm willing to write and test a fix.

**Comment by howardjohn** [comment]
@maxdebayser I ran into the same thing, a fix would be appeciated

**Comment by zeph** [comment]
same, I just ran into it @maxdebayser too

**Comment by zeph** [comment]
@howardjohn it is just a formal thing... the fix is just this
`$ argocd app diff istio`
```diff 
===== networking.istio.io/Gateway istio-system/istio-autogenerated-k8s-ingress ======
38,39c38,39
<       privateKey: /etc/istio/ingressgateway-certs/tls.key
<       serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
---
>       privateKey: /etc/istio/ingress-certs/tls.key
>       serverCertificate: /etc/istio/ingress-certs/tls.crt
```

but I agree, it shall be fixed in the template provided too 
(unless they had a good reason for it ...and I would not be surprised)

**Comment by zeph** [comment]
p.s. I confirm it in `tag:1.2.5` and HEAD of `master` too
 - https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/gateways/templates/preconfigured.yaml#L29
- https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/gateways/values.yaml#L116

**Comment by zeph** [comment]
give the comment at [helm/istio/values.yaml#L135](https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/values.yaml#L135) I assume @rshriram can cast some light on this issue

**Comment by rshriram** [comment]
I think the incorrect path was a typo or something changed over time. Would appreciate a PR to fix the issue. Also, if you are using sds at the gateway, then you wouldn’t need to worry about secret mounts at all because the gateway would fetch the secrets directly from k8s.

**Comment by zeph** [comment]
@rshriram can you have a look at PR #17373 ? or shall I dig through the testing suite?

**Comment by ayj** [comment]
Looks like this was fixed by https://github.com/istio/istio/pull/17342. Please re-open if the issue persists.
