### ISSUE TITLE
ISTIOCTL 1.3.0-rc-1 structToJSON not defined

### ISSUE THREAD

**Issue by kramvan1** [istio/istio#16781]
**Bug description**

`istioctl kube-inject --injectConfigFile build/metadata/istio-1.3.0-rc.1/inject-config.yaml --meshConfigFile build/metadata/istio-1.3.0-rc.1/mesh-config.yaml --valuesFile build/metadata/istio-1.3.0-rc.1/inject-values.json -f istio-1.3.0-rc.1/samples/bookinfo/platform/kube/bookinfo.yaml -o _deployment.yaml`

Looks like the following PR is causing the issue:
https://github.com/istio/istio/pull/16161

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

istioctl work properly

**Steps to reproduce the bug**

- using 1.3.0-rc-1 istioctl and bookinfo sample, try to inject the sidecar into sample manually 

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

1.3.0-rc-1

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
You need to upgrade istioctl as well, have you done this?

**Comment by linsun** [comment]
would be good to print out istioctl version output

**Comment by irisdingbj** [comment]
Tried using the istioctl within the 1.3.0-rc-1 and it works well:
```
./istioctl kube-inject -f ../samples/bookinfo/platform/kube/bookinfo.yaml -o bookinfo.inject.yaml
```

**Comment by kramvan1** [comment]
Dang, had a typo in my build script and it ended up using the an older version, sorry for the chaf.
