### ISSUE TITLE
Ingress Deny RouteRules Don't Seem to Work

### ISSUE THREAD

**Issue by brentcty** [istio/istio#1679]
I've followed the Istio Ingress Controller task to the letter, but the Deny RouteRules don't seem to be working. Using Minikube 0.22.3 with automatic injection again. Could this be related to not being able to change sidecar config after they have been injected?

$ curl -I http://$INGRESS_HOST/headers
HTTP/1.1 200 OK
server: envoy
date: Mon, 13 Nov 2017 02:42:41 GMT
content-type: application/json
access-control-allow-origin: *
access-control-allow-credentials: true
content-length: 470
x-envoy-upstream-service-time: 5

Also HTTPS config doesn't seem to work after I follow the instructions on how to do it.

$ curl -I -k https://$INGRESS_HOST/status/200
curl: (35) Unknown SSL protocol error in connection to 192.168.64.10:-9847

Unusual port it is giving me.

$ env | grep INGRESS_HOST
INGRESS_HOST=192.168.64.10:32467

**Comment by sbulman** [comment]
Are there any ideas about this? I am unable to get the deny route rule to work. Thanks.

**Comment by magicluo0755** [comment]
It seems a bug, also occured on  kubernetes 1.8.4 withi istio 0.2.12,

**Comment by Adiqq** [comment]
k8s 1.8.4 with istio 0.3.0 , problem still seems to exists.
Ingress log: https://pastebin.com/Q7zRASst
Mixer log: https://pastebin.com/zHN3fHhi

**Comment by pmint93** [comment]
K8s 1.8.4
Tried with istio 0.2.12 and 0.4.0
Using this routerule: `istioctl create -f samples/bookinfo/kube/route-rule-all-v1.yaml`
But there is no effect, I still see a round robin distribution of no stars, red stars, black stars.
Mixer log still notice that there are no rules:
```
I0117 04:26:36.103143       1 runtime.go:113] unconditionally resolving for kinds: [attributes]
I0117 04:26:36.103224       1 runtime.go:176] no rules for global/default.svc.cluster.local
I0117 04:26:36.103233       1 runtime.go:176] no rules for global/reviews.default.svc.cluster.local
I0117 04:26:36.103238       1 runtime.go:176] no rules for default.svc.cluster.local/default.svc.cluster.local
I0117 04:26:36.103243       1 runtime.go:176] no rules for default.svc.cluster.local/reviews.default.svc.cluster.local
I0117 04:26:36.103247       1 runtime.go:176] no rules for reviews.default.svc.cluster.local/reviews.default.svc.cluster.local
I0117 04:26:36.103252       1 runtime.go:121] unconditionally resolved configs (err=<nil>): [kubernetes]
```
```
$ kubectl get routerules
NAME                  AGE
details-default       36m
productpage-default   36m
ratings-default       36m
reviews-default       36m
```

**Comment by louiscryan** [comment]
This issue is pretty stale. Can you retest with 0.8 and reopen if you still have this problem
