### ISSUE TITLE
istio-codecov-master fails with unknown import path

### ISSUE THREAD

**Issue by yangminzhu** [istio/istio#16793]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
It seems the error is returned by `go tool cover -html=coverage.cov -o coverage.html` in codecov.sh, maybe also related to the switching to GO111MODULE=on.

cc @howardjohn @geeknoid @sushicw @kyessenov 

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[X] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

```
cover: unknown import path "istio.io/istio/galley/pkg/config/analysis": cannot find module providing package istio.io/istio/galley/pkg/config/analysis
``` 
in https://github.com/istio/istio/pull/16350

```
cover: unknown import path "istio.io/istio/pilot/pkg/security/authz/policy/v1alpha1": cannot find module providing package istio.io/istio/pilot/pkg/security/authz/policy/v1alpha1
``` 
in https://github.com/istio/istio/pull/16602

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by yangminzhu** [comment]
@geeknoid @howardjohn @sushicw @kyessenov 
I pushed a [commit](https://github.com/istio/istio/pull/16602/commits/20a21efba167af663ad9157f515bea95e52da61f) that removes the `go tool cover -html=coverage.cov -o coverage.html` to test if it fixes the issue. The coverage.html is never used after its generation so probably we can just remove the statement if this fixes the issue.

**Comment by geeknoid** [comment]
Aren't we uploading this data to codecov.io?

**Comment by geeknoid** [comment]
Oh never mind, we need the coverage.cov file, not the html.

**Comment by yangminzhu** [comment]
@geeknoid Well, when debugging this I just realized `coverage.cov` is also not uploaded due to missing the token:
```
make[1]: Leaving directory '/home/prow/go/src/istio.io/istio'
   _____          _
 / ____|        | |
| |     ___   __| | ___  ___ _____   __
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
| |___| (_) | (_| |  __/ (_| (_) \ V /
 \_____\___/ \__,_|\___|\___\___/ \_/
                              Bash-8a28df4
 x> No CI provider detected.
    Testing inside Docker? http://docs.codecov.io/docs/testing-with-docker
    Testing with Tox? https://docs.codecov.io/docs/python#section-testing-with-tox
    project root: .
/dev/fd/63: line 832: hg: command not found
    Yaml found at: .codecov.yml
    -> Found 1 reports
==> Detecting git/mercurial file structure
==> Reading reports
    + /home/prow/go/out/codecov/pr/coverage.cov bytes=4328976
==> Appending adjustments
    http://docs.codecov.io/docs/fixing-reports
    + Found adjustments
==> Gzipping contents
==> Uploading reports
    url: https://codecov.io
    query: branch=master&commit=69a91b7aa673018de58ebcfe2af2be6f59cbcf82&build=&build_url=&name=&tag=&slug=&service=&flags=&pr=&job=
    -> Pinging Codecov
https://codecov.io/upload/v4?package=bash-8a28df4&token=secret&branch=master&commit=69a91b7aa673018de58ebcfe2af2be6f59cbcf82&build=&build_url=&name=&tag=&slug=&service=&flags=&pr=&job=
HTTP 400
```

**Comment by howardjohn** [comment]
I think the upload doesn't work anyways, see
https://github.com/istio/istio/issues/16181

**Comment by yangminzhu** [comment]
@geeknoid @howardjohn @kyessenov @sushicw Okay, removing the `go tool cover -html=coverage.cov -o coverage.html` fixed the issue in https://github.com/istio/istio/pull/16602, I will send out the fix in a standalone PR.

**Comment by geeknoid** [comment]
Yeah, I think that's fine.
