### ISSUE TITLE
go test fail for undefined flags on go 1.13

### ISSUE THREAD

**Issue by richardwxn** [istio/istio#16797]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
some e2e tests fail on go 1.13 for the error: flag provided but not defined:-test.v. Run with go 1.12 instead works fine.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ X] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
go test should works fine

**Steps to reproduce the bug**
run make e2e_simple_run or directly run go test with standard flags set, for example -v or -timeout, it would gives error of flag provided but not defined: -test.v.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
go version go1.13rc1 linux/amd64
istio version: 1.2.4
kubectl version: 1.15.3

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
should be an easy fix, we need to parse flags in test main instead of init - I had a PR doing exactly this but for a different test. I assume that's the problem at least, I didn't try
