### ISSUE TITLE
Pods deployed in istio-injected namespace are not getting started after scheduled shutdown

### ISSUE THREAD

**Issue by dhineshbabuelango** [istio/istio#16808]
Hi All, 
We are using istio in EKS. 
We have 4 worker nodes, we used to shutdown the worker nodes as part of the daily shutdown(edit the autoscaling group min and max to zero) and provision the instance next day morning(edit the autoscaling group). 
Once the worker nodes comes up all the pods which has istio-label injected are not getting restarted automatically. 
**Even all the istio components in istio-system namespace is running fine.** 

It is happening only to the pods deployed in namespace which has istio-injection=enabled. When I check the logs in replica set, I could see the below error.

![image](https://user-images.githubusercontent.com/51995628/64256921-f53c0800-cf56-11e9-9326-8c5df869856b.png)

![image](https://user-images.githubusercontent.com/51995628/64257036-39c7a380-cf57-11e9-92da-0c3d8f3e34bc.png)

**Comment by howardjohn** [comment]
Hey @dhineshbabuelango thanks for reporting. This is a somewhat common probably we are tracking in https://github.com/istio/istio/issues/13840. I am going to close this so we can consolidate our efforts there.

I would recommend reading through there for some more info, as well as https://github.com/istio/istio/wiki/Troubleshooting-Istio#sidecar-injection. Thanks!
