### ISSUE TITLE
Include k8s version check for Istio installation

### ISSUE THREAD

**Issue by jasminejaksic** [istio/istio#1680]
I tried to install Istio but didn't realize the cluster was running an older k8s version (1.5.x) and got a litany of unhelpful error messages (see below). Though we mention on istio.io that it requires 1.7.3 or newer, it would be a good idea to do a version check on k8s before Istio installation begins. 

Exact message after I tried to install Istio (kubectl apply -f install/kubernetes/istio.yaml)
----------------------------------------------------------------------------------------
W1112 18:41:52.161132   51918 factory_object_mapping.go:423] Failed to download OpenAPI (the server could not find the requested resource), falling back to swagger
namespace "istio-system" configured
clusterrole "istio-pilot-istio-system" configured
clusterrole "istio-initializer-istio-system" configured
clusterrole "istio-mixer-istio-system" configured
clusterrole "istio-ca-istio-system" configured
clusterrole "istio-sidecar-istio-system" configured
clusterrolebinding "istio-pilot-admin-role-binding-istio-system" configured
clusterrolebinding "istio-initializer-admin-role-binding-istio-system" configured
clusterrolebinding "istio-ca-role-binding-istio-system" configured
clusterrolebinding "istio-ingress-admin-role-binding-istio-system" configured
clusterrolebinding "istio-egress-admin-role-binding-istio-system" configured
clusterrolebinding "istio-sidecar-role-binding-istio-system" configured
clusterrolebinding "istio-mixer-admin-role-binding-istio-system" configured
configmap "istio-mixer" configured
service "istio-mixer" configured
serviceaccount "istio-mixer-service-account" configured
deployment "istio-mixer" configured
configmap "istio" configured
service "istio-pilot" configured
serviceaccount "istio-pilot-service-account" configured
deployment "istio-pilot" configured
service "istio-ingress" configured
serviceaccount "istio-ingress-service-account" configured
deployment "istio-ingress" configured
service "istio-egress" configured
serviceaccount "istio-egress-service-account" configured
deployment "istio-egress" configured
serviceaccount "istio-ca-service-account" configured
deployment "istio-ca" configured
unable to recognize "install/kubernetes/istio.yaml": no matches for apiextensions.k8s.io/, Kind=CustomResourceDefinition
unable to recognize "install/kubernetes/istio.yaml": no matches for apiextensions.k8s.io/, Kind=CustomResourceDefinition
unable to recognize "install/kubernetes/istio.yaml": no matches for apiextensions.k8s.io/, Kind=CustomResourceDefinition
unable to recognize "install/kubernetes/istio.yaml": no matches for apiextensions.k8s.io/, Kind=CustomResourceDefinition
unable to recognize "install/kubernetes/istio.yaml": no matches for apiextensions.k8s.io/, Kind=CustomResourceDefinition
unable to recognize "install/kubernetes/istio.yaml": no matches for apiextensions.k8s.io/, Kind=CustomResourceDefinition
unable to recognize "install/kubernetes/istio.yaml": no matches for apiextensions.k8s.io/, Kind=CustomResourceDefinition
unable to recognize "install/kubernetes/istio.yaml": no matches for apiextensions.k8s.io/, Kind=CustomResourceDefinition
unable to recognize "install/kubernetes/istio.yaml": no matches for apiextensions.k8s.io/, Kind=CustomResourceDefinition
unable to recognize "install/kubernetes/istio.yaml": no matches for apiextensions.k8s.io/, Kind=CustomResourceDefinition
unable to recognize "install/kubernetes/istio.yaml": no matches for apiextensions.k8s.io/, Kind=CustomResourceDefinition
unable to recognize "install/kubernetes/istio.yaml": no matches for apiextensions.k8s.io/, Kind=CustomResourceDefinition
unable to recognize "install/kubernetes/istio.yaml": no matches for apiextensions.k8s.io/, Kind=CustomResourceDefinition
unable to recognize "install/kubernetes/istio.yaml": no matches for apiextensions.k8s.io/, Kind=CustomResourceDefinition
unable to recognize "install/kubernetes/istio.yaml": no matches for apiextensions.k8s.io/, Kind=CustomResourceDefinition
unable to recognize "install/kubernetes/istio.yaml": no matches for apiextensions.k8s.io/, Kind=CustomResourceDefinition
unable to recognize "install/kubernetes/istio.yaml": no matches for apiextensions.k8s.io/, Kind=CustomResourceDefinition
unable to recognize "install/kubernetes/istio.yaml": no matches for config.istio.io/, Kind=attributemanifest
unable to recognize "install/kubernetes/istio.yaml": no matches for config.istio.io/, Kind=attributemanifest
unable to recognize "install/kubernetes/istio.yaml": no matches for config.istio.io/, Kind=stdio
unable to recognize "install/kubernetes/istio.yaml": no matches for config.istio.io/, Kind=logentry
unable to recognize "install/kubernetes/istio.yaml": no matches for config.istio.io/, Kind=rule
unable to recognize "install/kubernetes/istio.yaml": no matches for config.istio.io/, Kind=metric
unable to recognize "install/kubernetes/istio.yaml": no matches for config.istio.io/, Kind=metric
unable to recognize "install/kubernetes/istio.yaml": no matches for config.istio.io/, Kind=metric
unable to recognize "install/kubernetes/istio.yaml": no matches for config.istio.io/, Kind=metric
unable to recognize "install/kubernetes/istio.yaml": no matches for config.istio.io/, Kind=metric
unable to recognize "install/kubernetes/istio.yaml": no matches for config.istio.io/, Kind=metric
unable to recognize "install/kubernetes/istio.yaml": no matches for config.istio.io/, Kind=prometheus
unable to recognize "install/kubernetes/istio.yaml": no matches for config.istio.io/, Kind=rule
unable to recognize "install/kubernetes/istio.yaml": no matches for config.istio.io/, Kind=rule
unable to recognize "install/kubernetes/istio.yaml": no matches for apiextensions.k8s.io/, Kind=CustomResourceDefinition
unable to recognize "install/kubernetes/istio.yaml": no matches for apiextensions.k8s.io/, Kind=CustomResourceDefinition
unable to recognize "install/kubernetes/istio.yaml": no matches for apiextensions.k8s.io/, Kind=CustomResourceDefinition

**Comment by ldemailly** [comment]
good idea but where/how would we check, it's just a yaml file at the moment (we don't have an installer...) ?

**Comment by ayj** [comment]
We'll need an installer and/or more detailed installation instructions going forward. For example, use of k8s webhooks required cert provisioning (see [here](https://docs.google.com/document/d/1f61uHoPvozoVhlut6TG66L2XQ_DvFQWUUeFjHJeypHQ/edit#bookmark=id.74mjrvtdgjl4)).

**Comment by jasminejaksic** [comment]
+1 on installer. We are going to need this sooner or later, we might as well do it now.

**Comment by ldemailly** [comment]
cc @andraxylia ^

**Comment by andraxylia** [comment]
We will use helm most likely, so no installer.

**Comment by ayj** [comment]
Is there an issue for install?

Also, does helm manage cert provisioning, e.g. create cert, sign with k8s CA?

**Comment by ldemailly** [comment]
I'm not sure helm meets the requirements but yes there is discussions in #1113 , #851 ...

Not sure we prioritized any of that work though/who is working on it

**Comment by andraxylia** [comment]
It's a P2, not a priority.

**Comment by ayj** [comment]
We need certs provisioned for mutating webhooks (injection) and read-only webhooks (pilot/mixer validation). If the recommendation is to use helm for this, then helm task needs to be higher priority.

**Comment by sbezverk** [comment]
@ayj  WDYT about using an operator for the deployment. The operator in addition to some sanity checks and deployment, could potentially in future run some lifecycle management tasks? It seems there is a trend in k8s community with operators, external provisioners etc.

**Comment by ayj** [comment]
I'm not familiar with k8s operators. A quick Google search suggests it might be something that could be layer on top of Istio, but we may not want to require it as part of minimal install of Istio.
