### ISSUE TITLE
Can Rewrite Rules help fix URL Access (or is it a code moddification)

### ISSUE THREAD

**Issue by jwlai** [istio/istio#16807]
![image](https://user-images.githubusercontent.com/4219846/64256338-43b6bb80-cef1-11e9-8042-1f1ec57882f7.png)
![image](https://user-images.githubusercontent.com/4219846/64256363-4e715080-cef1-11e9-9d4f-38c325a225dc.png)

Hi community,

I just needed some help here. I have the following situation where the first [url]/frontend returns 200 (which is the index of my react application) but when it tries to fetch the javascript files it reaches out to the service with out via [url]/static/*/*.js rather than [url]/frontend/static etc. I just want to know if this is something that can be fixed via rewrite rules in Istio or is a level down in the react code that I need to modify? 

(FYI: When I access the JS files with the [URL]/frontend/static/*/*.js it returns a 200 success)

Thanks!

**Comment by howardjohn** [comment]
Please take a look at virtual service, you should be able to rewrite: https://istio.io/docs/reference/config/networking/v1alpha3/virtual-service/#HTTPRewrite

**Comment by jwlai** [comment]
What rules does the rewrite support? I.e. (wildcards, how do I keep the path after the parsed prefix?)

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ms-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ms
spec:
  hosts:
  - "*"
  gateways:
  - ms-gateway
  http:
  - match:
    - uri:
        prefix: /frontend
    rewrite:
      uri: /frontend/    <- I want to keep the words after the "/".
    route:
    - destination:
        port:
          number: 80
        host: blueprint-msfrontend

**Comment by howardjohn** [comment]
Something like 
```
  - match:
    - uri:
        prefix: /static
    rewrite:
      uri: /frontend/static
```

Should work

**Comment by jwlai** [comment]
Thanks John, this is a little out of scope but after getting the 200 Status OK, I'm running into the scripts erroring out at the "<" sign.. any advice here? The React Application works as it's supposed to when exposed as a service but not using the ingress through istio.

**Comment by howardjohn** [comment]
I dont know, is the script being returned correct? I am not quite sure what the issue is

**Comment by howardjohn** [comment]
Seems the original issue is resolved
