### ISSUE TITLE
Galley validating webhook configuration, replica set and pods are periodically garbage collected by Kubernetes

### ISSUE THREAD

**Issue by mdhume** [istio/istio#16818]
**Bug description**
Galley validating webhook configuration, replica set and pods are periodically garbage collected by Kubernetes. This is due to the fact that the ownerReference field that is added to the ValidatingWebhookConfiguration by galley pods points to the Galley deployment object - https://github.com/istio/istio/blob/release-1.1/galley/pkg/crd/validation/webhook.go#L275-L282 and https://github.com/istio/istio/blob/release-1.1/galley/pkg/crd/validation/config.go#L162-L165
(Part of 1.3 release as well - https://github.com/istio/istio/blob/release-1.3/galley/pkg/crd/validation/config.go#L352-L359)

Since ValidatingWebhookConfiguration is a cluster scoped resource it should not have an owner that is a namespace scoped resource (Deployment). This is clearly stated in the K8s docs - https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/#owners-and-dependents 
```Note: Cross-namespace owner references are disallowed by design. This means: 1) Namespace-scoped dependents can only specify owners in the same namespace, and owners that are cluster-scoped. 2) Cluster-scoped dependents can only specify cluster-scoped owners, but not namespace-scoped owners.```

kube-controller-manager logs showing galley resources getting garbage collected - https://gist.github.com/mdhume/25fc042e30fcd05cce7079a7b0aa6aee

**Affected product area (please put an X in all that apply)**

[X] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Validating webhook configuration should not have a namespace scoped owner
Galley validating webhook configuration, replica set and pods should not get garbage collected

**Steps to reproduce the bug**
Turn on verbose logging in kube-controller-manager
Force the kube-controller-manager lease to be changed by stopping controller-manager which has been elected the leader (consistent way to trigger the kubernetes garbage collector)
Observe galley validating webhook, RS and pods getting deleted and re-created

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
sudo istioctl version --remote
```
client version: version.BuildInfo{Version:"1.1.5", GitRevision:"9b6d31b74d1c0cc9358cc82d395b53f71393326b", User:"root", Host:"3e29fde4-6c3f-11e9-b00d-0a580a2c0205", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.4-10-g9b6d31b"}
citadel version: version.BuildInfo{Version:"1.1.12", GitRevision:"473d9b376acf780fa1929eaf44dc65a3049d3765-dirty", User:"root", Host:"978bd2fb-b3ec-11e9-b9bf-9a92a2df0414", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.11-2-g473d9b3"}
galley version: version.BuildInfo{Version:"1.1.12", GitRevision:"473d9b376acf780fa1929eaf44dc65a3049d3765-dirty", User:"root", Host:"978bd2fb-b3ec-11e9-b9bf-9a92a2df0414", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.11-2-g473d9b3"}
ingressgateway version: version.BuildInfo{Version:"1.1.12", GitRevision:"473d9b376acf780fa1929eaf44dc65a3049d3765", User:"root", Host:"978bd2fb-b3ec-11e9-b9bf-9a92a2df0414", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.11-2-g473d9b3"}
pilot version: version.BuildInfo{Version:"1.1.12", GitRevision:"473d9b376acf780fa1929eaf44dc65a3049d3765-dirty", User:"root", Host:"978bd2fb-b3ec-11e9-b9bf-9a92a2df0414", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.11-2-g473d9b3"}
policy version: version.BuildInfo{Version:"1.1.12", GitRevision:"473d9b376acf780fa1929eaf44dc65a3049d3765-dirty", User:"root", Host:"978bd2fb-b3ec-11e9-b9bf-9a92a2df0414", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.11-2-g473d9b3"}
telemetry version: version.BuildInfo{Version:"1.1.12", GitRevision:"473d9b376acf780fa1929eaf44dc65a3049d3765-dirty", User:"root", Host:"978bd2fb-b3ec-11e9-b9bf-9a92a2df0414", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.1.11-2-g473d9b3"}
```

sudo kubectl version
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.7", GitCommit:"4683545293d792934a7a7e12f2cc47d20b2dd01b", GitTreeState:"archive", BuildDate:"2019-06-06T20:44:33Z", GoVersion:"go1.11.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.7", GitCommit:"4683545293d792934a7a7e12f2cc47d20b2dd01b", GitTreeState:"archive", BuildDate:"2019-06-06T20:44:33Z", GoVersion:"go1.11.10", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
Using helm charts from 1.1.12 release with some custom additions 

**Environment where bug was observed (cloud vendor, OS, etc)**
Kubernetes 1.13.7 running on RHEL 7

/cc @sureshvis @prabushyam @karthikt-yahoo

**Comment by ozevren** [comment]
@ayj @sushicw

**Comment by ozevren** [comment]
@jasonwzm

**Comment by mdhume** [comment]
@ayj @howardjohn @ozevren Is this present in any release? I don't see it in 1.3.1. Can we get this rolled out in 1.3.2?

**Comment by ozevren** [comment]
The change seems to be in master only now. I tagged it to be cherry-picked
into 1.3. If the release managers are ok with it, it should appear in the
next 1.3.x release.
