### ISSUE TITLE
503s in performance cluster with autoscaling

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#16813]
In the service-graph tests we added a new configchanger that will scale deployments up and down. When we added this, we see 503s correlated with scaling up/down events.

This occurs on 1.3, but possibly also on older version as well.

Example: https://snapshot.raintank.io/dashboard/snapshot/dP4MxaYuFOJZvy2nBCV043YlLec9AKdD?refresh=5s&panelId=23&fullscreen&orgId=2

fyi @mandarjog

**Comment by mandarjog** [comment]
Yes, I see the same results in another cluster.

**Comment by howardjohn** [comment]
I turned of the scaling and it goes away, so seems its isolated to that change not something in 1.3. Still should be fixed though
