### ISSUE TITLE
Istio Disaster Recovery: Cold Starts

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#16830]
When (cold) starting an Istio cluster as part of disaster recovery many subsystems get stressed in an unusual way.

 1. Citadel: Start is gated by Citadel issuing certificates. 
     a. Test and measure how long it takes to issues many concurrent certs
     b. re-order cert issue order: Issue import certs first like istio-system or istio-control so other istio components can start first.
 @myidpt @rlenglet @ZackButcher 

2. Pilot: During a big concurrent start pilot must push excessive amounts of config thru the system churn.
    a. Test and measure what is the impact
    b.  Consider if this case requires special attention.
@costinm 

3. Galley - Start of Galley holds up Pilot, perhaps not much needs to be done here.

**Comment by myidpt** [comment]
/cc @JimmyCYJ 
For Citadel:
a. I believe issuing many concurrent certs is needed only when SDS is used, with the file mount approach, the keys and certs are in persistent storage (etcd) so no need to reissue the certs. For  SDS stress tests, it's in our Code Mauve plan. Expected to be done in Q4.
b. This feature makes sense when there are a large number of service accounts in the system, and Citadel needs to issue certs for all in a batch. This won't happen due to a disaster though, unless the etcd is tampered in the disaster.

**Comment by howardjohn** [comment]
> Galley - Start of Galley holds up Pilot, perhaps not much needs to be done here.

I don't think we can do much here other than smart ordering with operator/installer. We cannot serve until we connect to galley or we would generate incorrect configs (missing rbac rules)

> Pilot: During a big concurrent start pilot must push excessive amounts of config thru the system churn.

In 1.3 pilot handles this pretty well by deduping pushes. We may want to increase debounce time from 100ms to something slightly higher (250ms?). 
One concern is the discoveryrequests follow a different codepath, so we can have an infinite number of discoveryrequests being handled at one time, which may lead to decreased performance (ideally, we have exactly the amount of requests pilot can handle without being throttled).

**Comment by JimmyCYJ** [comment]
> For Citadel:
> a. I believe issuing many concurrent certs is needed only when SDS is used, with the file mount approach, the keys and certs are in persistent storage (etcd) so no need to reissue the certs. For SDS stress tests, it's in our Code Mauve plan. Expected to be done in Q4.
> b. This feature makes sense when there are a large number of service accounts in the system, and Citadel needs to issue certs for all in a batch. This won't happen due to a disaster though, unless the etcd is tampered in the disaster. We can prioritize this work for Q4.

My understanding of disaster recovery would be like this, when there are already many workloads running in a cluster managed by Istio, at certain time we cold start Istio for recovery purposes. Given how many service accounts are there to run workloads, with SDS approach, Citadel receives that number of CSRs concurrently and issues certificates.
