### ISSUE TITLE
Watchdog for Istio components [Pilot,SDS Agent]

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#16831]
We have had Istio bugs in the past where Pilot / Citadel or Proxy got stuck in a particular state. A watchdog goroutine can be uniformly applied to many components. A watchdog can  terminate the component if it stops making forward progress.

Pilot has had several distributed deadlocks, stuck pushes which could be healed by a watchdog.

**Comment by howardjohn** [comment]
Isn't this what a liveness probe is for? We do not have a liveness probe for pilot, but this seems the best way to implement this

**Comment by mandarjog** [comment]
Not state
