### ISSUE TITLE
Grafana Install Annotation

### ISSUE THREAD

**Issue by jwlai** [istio/istio#16849]
Hi,
I was just wondering what the reasoning behind preventing the sidecar from being injected into grafana? I wanted to expose grafana to be accessed via browser (Is there a best practice I should follow?)

Re: grafana -> deployment.yaml
annotations:
        sidecar.istio.io/inject: "false"
        prometheus.io/scrape: "true"

**Comment by jwlai** [comment]
Also I can't seem to expose grafana via Istio-ingressgateway, is that correct? I also have another gateway existing pasted beneath it... 

`apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: grafana-gateway
  namespace: istio-grafana
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana
  namespace: istio-grafana
spec:
  hosts:
  - "*"
  gateways:
  - grafana-gateway
  http:
  - match:
    - uri:
        prefix: /grafana
    rewrite:
      uri: /
    route:
    - destination:
        port:
          number: 3000
        host: grafana`

`apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ms-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ms
spec:
  hosts:
  - "*"
  gateways:
  - ms-gateway
  http:
  - match:
    - uri:
        prefix: /frontend
    route:
    - destination:
        port:
          number: 80
        host: blueprint-msfrontend
  - match:
    - uri:
        prefix: /static
    rewrite:
      uri: /frontend/static
    route:
    - destination:
        port:
          number: 80
        host: blueprint-msfrontend
  - match:
    - uri:
        prefix: /backend/
    rewrite:
      uri: /
    route:
    - destination:
        host: blueprint-msbackend
        port:
          number: 80`

**Comment by howardjohn** [comment]
Please see https://istio.io/docs/tasks/telemetry/gateways/

**Comment by jwlai** [comment]
Thanks!! Is it mandatory to use that port 15031?

**Comment by douglas-reid** [comment]
Using port `15031` is not required. However, you may encounter difficulty overlaying it on port `80` or `443` (getting the prefix / rewrite rules correct may prove challenging).

We have not attempted to put proxies in front of any of the add-ons. It may be possible for Grafana, but it hasn't been tested, and isn't required.
