### ISSUE TITLE
Vulnerabilities found in proxy image

### ISSUE THREAD

**Issue by elevran** [istio/istio#1684]
Istio proxy (debug) [image 0.2.9](https://anchore.io/image/dockerhub/istio%2Fproxy_debug:0.2.9) has known vulnerabilities (>70 medium and >70 low priority vulnerabilities).
Result of anchore.io run on 0.2.9 can be found [here](https://anchore.io/image/dockerhub/f0994e4220bc54041dc937ebfe744ef6f44aa112b1973c084ef6e912c2efb09c?repo=istio%2Fproxy_debug&tag=0.2.9#policy) and [here](https://anchore.io/image/dockerhub/f0994e4220bc54041dc937ebfe744ef6f44aa112b1973c084ef6e912c2efb09c?repo=istio%2Fproxy_debug&tag=0.2.9#security)

**Comment by ldemailly** [comment]
none high, also 0.2.9 is old

**Comment by costinm** [comment]
Do you have a run for 0.2.12 ? 

We need  to track this - it seems we mostly need to update to current versions of the packages.

**Comment by GregHanson** [comment]
closing issue since it is out of date with respect to the current release, will open a new issue for tracking VA work on future releases
