### ISSUE TITLE
Documentation on adding a custom template to the mixer

### ISSUE THREAD

**Issue by ashutoshraina** [istio/istio#16854]
I was looking up documentation on how I can attach a custom template to the mixer binary, but the documentation is TBD.
Is there a blog post that I can refer to ? Are there plans of writing up the missing documentation ?

**Comment by douglas-reid** [comment]
I don't believe that the documentation has ever been written, and at this point, I don't foresee it getting written. Mixer is being replaced by an in-proxy extension mechanism, and that work will be coming to the forefront in 1.4 and 1.5 releases.

The best thing may be to ask if anyone has experience with this on discuss.istio.io.
