### ISSUE TITLE
Elasticsearch security not working with Istio

### ISSUE THREAD

**Issue by MVJosh** [istio/istio#16851]
**Bug description**
Deploying Elasticsearch with TLS security enabled (via [helm chart example](https://github.com/elastic/helm-charts/tree/master/elasticsearch/examples/security)) breaks communication with Elasticsearch HTTP(S) API when Istio sidecar injection is enabled (mtls set to `PERMISSIVE`):
```bash
$ kubectl exec -it security-master-0 --sh -c \
  "curl -vk https://security-master:9200/_cluster/health"
Defaulting container name to elasticsearch.
Use 'kubectl describe pod/security-master-0 -n default' to see all of the containers in this pod.
* About to connect() to security-master port 9200 (#0)
*   Trying x.x.x.x...
* Connected to security-master (x.x.x.x) port 9200 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* NSS error -12263 (SSL_ERROR_RX_RECORD_TOO_LONG)
* SSL received a record that exceeded the maximum permissible length.
* Closing connection 0
curl: (35) SSL received a record that exceeded the maximum permissible length.
command terminated with exit code 35
```

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
`kubectl exec -it security-master-0 --sh -c "curl https://security-master:9200/_cluster/health"` should return valid JSON from Elasticsearch

**Steps to reproduce the bug**
From istio-1.2.5 release directory on a fresh Kubernetes cluster with helm & tiller configured:
```bash
$ helm install install/kubernetes/helm/istio-init --name istio-init --namespace istio-system
$ helm install install/kubernetes/helm/istio --name istio --namespace istio-system --values install/kubernetes/helm/istio/values.yaml
$ kubectl label namespace default istio-injection=enabled
$ git clone -b 7.3.0 https://github.com/elastic/helm-charts.git && cd helm-charts/elasticsearch/examples/security
$ make # This step will take a few minutes for the ES pods to become available
```
The make process returns the following error:
```
https://security-master:9200/_cluster/health: status: Error: Get https://security-master:9200/_cluster/health: http: server gave HTTP response to HTTPS client
```
See in more detail via (returns the SSL error described above):
```bash
`kubectl exec -it security-master-0 --sh -c "curl https://security-master:9200/_cluster/health"`
```

* This error occurs both *with and without istio mTLS*.
* Disabling istio-injection solves the issue (demonstrating that the [ES security example](https://github.com/elastic/helm-charts/tree/master/elasticsearch/examples/security) works when not using istio).
* Installing the [default](https://github.com/elastic/helm-charts/tree/master/elasticsearch/examples/default) example (no security) from the [Elasticsearch helm chart repo](https://github.com/elastic/helm-charts) works with istio-injection enabled (demonstrating that the Elasticsearch helm charts, in general, work with istio).

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```bash
$ istiojctl version --remote
client version: 1.2.5
citadel version: 1.2.5
galley version: 1.2.5
ingressgateway version: 1.2.5
pilot version: 1.2.5
policy version: 1.2.5
sidecar-injector version: 1.2.5
telemetry version: 1.2.5
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T14:25:20Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.10", GitCommit:"e3c134023df5dea457638b614ee17ef234dc34a6", GitTreeState:"clean", BuildDate:"2019-07-08T03:40:54Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
Via helm charts from istio 1.2.5 OSX release

**Environment where bug was observed (cloud vendor, OS, etc)**
* Kubernetes running on AWS (installed via [kops](kops))
* Local machine is running macOS 10.14.6

**Comment by howardjohn** [comment]
Maybe related: https://github.com/istio/istio/issues/14662

**Comment by MVJosh** [comment]
> Maybe related: #14662

I did take a look at that issue, but this seems different to me. I can get Elasticsearch working happily with istio sidecar injection, but only *without Elasticsearch security settings enabled*

**Comment by rshriram** [comment]
how is port 9200 declared?

**Comment by MVJosh** [comment]
> how is port 9200 declared?

It's the default value being set from the Elasticsearch Helm chart: https://github.com/elastic/helm-charts/blob/8502b6f5224e51b228c13e21681770c03e337fb8/elasticsearch/values.yaml#L128

**Comment by mc1711** [comment]
We have been hitting the same issue,  communication problem between the elasticsearch-client and the elasticsearch-master

this is the error we see on the client


```
[WARN ][o.e.t.n.Netty4Transport  ] [elasticsearch-client-7c4799bfb4-624kf] exception caught on transport layer [NettyTcpChannel{localAddress=/x.x.x.118:9300, remoteAddress=/127.0.0.6:55035}], closing connection
io.netty.handler.codec.DecoderException: java.io.StreamCorruptedException: invalid internal transport message format, got (16,3,1,0)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459) ~[netty-codec-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[netty-codec-4.1.16.Final.jar:4.1.16.Final]
```

As workaround we create a DestinationRule disabling mTLS for the server service.

**Comment by mc1711** [comment]
@MVJosh  have you had any luck with this issue?

**Comment by MVJosh** [comment]
No luck so far

**Comment by GregHanson** [comment]
@mc1711 @MVJosh during the secure deployment of elasticsearch, secrets are created and used for secure communication:
https://github.com/elastic/helm-charts/blob/master/elasticsearch/examples/security/Makefile#L28

Have you tried creating a DestinationRule that does something besides disabled mtls? for instance:
```
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: tls-elasticsearch
spec:
  host: "security-master"
  trafficPolicy:
    tls:
      mode: SIMPLE
EOF
```
or one which references the mounted secrets directly
```
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: tls-elasticsearch
spec:
  host: security-master
  trafficPolicy:
    tls:
      mode: MUTUAL
      clientCertificate: /usr/share/elasticsearch/config/certs/<filename>.pem
      privateKey: /usr/share/elasticsearch/config/certs/<filename>.pem
      caCertificates:/usr/share/elasticsearch/config/certs/<filename>.pem
EOF
```

**Comment by GregHanson** [comment]
I haven't been able to get elasticsearch to deploy properly in my env (even without istio deployed):
```
$ helm install install/kubernetes/helm/istio-init --name istio-init --namespace istio-system
$ helm install install/kubernetes/helm/istio --name istio --namespace istio-system --values install/kubernetes/helm/istio/values.yaml
$ kubectl label namespace default istio-injection=enabled
$ git clone -b 7.3.0 https://github.com/elastic/helm-charts.git && cd helm-charts/elasticsearch/examples/security
$ make # This step will take a few minutes for the ES pods to become available
```
So I cannot verify the fix.  @mc1711 @MVJosh will close at end of week if I don't hear anything back

**Comment by xinxinzhao1212** [comment]
Did this bug fix already？because i can not find it in the commits .If it had been fixes ,could  anyone kindly share the commit for this bug ? thanks a lot

**Comment by tariq1890** [comment]
I am facing this issue currently. What is the fix for this?

**Comment by MVJosh** [comment]
In the end, creating `DestinationRule`s for the Elasticsearch `Service`s with tls mode `DIASBLED` fixed the issue

**Comment by apshoemaker** [comment]
I am having the same issue.  I have elasticsearch and kibana installed in a namespace called `elastic` and with Istio injection enabled, I am unable to connect to my elasticsearch cluster from kibana to the main service `elasticsearch-master`.  I receive an error such as the below:

```
{"type":"log","@timestamp":"2020-08-04T21:59:42Z","tags":["error","elasticsearch","monitoring"],
"pid":6,"message":"Request error, retrying\nGET https://elasticsearch-master:9200/_xpack => write 
EPROTO 140315166148480:error:1408F10B:SSL routines:ssl3_get_record:wrong 
version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:\n"}
```

It appears that I cannot `curl https://elasticsearch-master:9200` from my kibana pod.  The error above typically indicates that you are trying to connect to an https endpoint where only http is being served; however, when I remove Istio injection from the namespace and redeploy with helm, the same security configurations work fine.  I have attempted to craft a `DestinationRule` such as the one below:

```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: tls-elasticsearch-elastic
  namespace: elastic
spec:
  host: '*.elastic.svc.cluster.local'
  trafficPolicy:
    tls:
      mode: DISABLE
```

I know the above is a bit overkill for the namespace, but it does not seem to to have any effect.  Any thoughts or ideas on things I am missing?  I'm sure it's probably quite obvious and I am staring right at it.  Thanks in advance!
