### ISSUE TITLE
Tests for Istio Webhook Controller

### ISSUE THREAD

**Issue by lei-tang** [istio/istio#16860]
**Describe the feature request**
This issue is to track the tests for Istio Webhook Controller, which is a new feature that manages webhook certificates and webhook configurations. With this feature, Citadel does not need to generate and rotate webhook certificates; Galley and Sidecar Injector do not need to manage their own webhook configurations. 

The tests should include unit tests and integration tests, and will test the various combinations of installer config flags.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X ] Security
[X] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
Done by #16418?
