### ISSUE TITLE
Add Mixer sidecarToTelemetrySessionAffinity option to old 1.3 installer

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#16862]
`sidecarToTelemetrySessionAffinity` is required for Mixer V1 when it talks to services like stackdriver.
This option is only available in the new installer.
This is needed in the old installer and back ported to 1.2.

**Comment by mandarjog** [comment]
@douglas-reid I do not see this in the installer any more. Perhaps it was never there, but I think it was there. @bianpengyuan do you think we just missed it ?

**Comment by douglas-reid** [comment]
I'm bumping this to P0, given that I've needed this several times in the past week in support of customers.
