### ISSUE TITLE
[Istio-Auto-mTLS] Provide a mTLS focused Grafana dashboard for mTLS lockdown

### ISSUE THREAD

**Issue by incfly** [istio/istio#16867]
**Describe the feature request**

Updated 09/08/2019

Per discussion with @diemtvu and @mandarjog , we think the feature is better to built as a Grafana dashboard. reasons, 

Switch from PERMISSIVE to STRICT requires user intervention, and can't be done automatically. The safety of the switch depends on users' own criteria. For example, how much plaintext traffic is tolerable, how much we should look back, what granularity should we be focused on, service/namespace/mesh? The tradeoff between safety and security is made by users.

Having said that, it's still great to have a single grafana dashboard dedicated for mTLS adoption. Service operator/mesh admin are able to filter by services/namespaces/select time range/, and see the plaintext traffic propotion from the plot.

We already have this information exported to Prometheus, and we just need to create a dashboard for that. This combined with `istioctl authn-tls check`, service operators have easier way to flip from PERMISSIVE to STRICT. 

---

/cc @fpesce @GregHanson @diemtvu 

Part of bigger feature request for [`Istio auto mTLS`](https://github.com/istio/istio/issues/14524). The last step is to lock down the server side policy from `PERMISSIVE` to `STRICT`. We need an `istioctl mtls-check` (or better naming) for this.

```bash
istioctl mtls-check [pod.name | namespace | all-for-entire-mesh] --days=3 \
--stats-checker=[prometheus|stackdriver|etc]
# output
Mesh: STRICT/PERMISSIVE/NA
  Namespace Foo:
    Service Bar: STRICT/PERMISSIVE (READY) # to denote whether it's okay to flip from permissive to strict
```

This basically tells the Istio operator whether for a given service `S`, in last `X` days, am I ready to switch from PERMISSIVE to STRICT?

Each telemetry backend has different query language syntax. That's why we have an argument `--stats-checker`. We will ship a default `prometheus` based telemetry query as part of this command. But for third-party telemetry backend system, we can formalize the plugin input params( service name, namespace, x days), and expect a true or false answer, which then will be used for `istioctl` to make decision on the report.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X ] Security
[ ] Test and Release
[X ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by elieser1101** [comment]
hi, i would like to help with this, my doubt is if you think this could be a good first issue?

**Comment by incfly** [comment]
Thanks for offering help!

The whole feature in `istioctl` itself might be a bit too large as first issue. But I think the Prometheus part can be separated out as a sub-task.

Basically we need some utilities and extension points being able to

```bash
$ istio-mtls-report <service-name> -n <namespace> -t <duration(5d, 30m, 10s)>
```

This returns true or false. And istioctl can use the returned value to decide what to show in the output. We can focus on implementing utilities libraries for Prometheus as golang libraries in `istio/istio` first since that's what shipped in default Istio installation and customers can use built-in prometheus based mTLS checker.

Does that sound good to you?

**Comment by incfly** [comment]
@esnible and others  @istio/wg-user-experience-maintainers 

I do want to get some input about high level feedback about the proposal in this FR before jumping into the implementation, thanks!

**Comment by esnible** [comment]
@sdake Will the new operator commands be able to help with this?

**Comment by ayj** [comment]
Is it worth capturing the use case, requirements, and design in a doc? It would be easier to review and comment on.

**Comment by elieser1101** [comment]
@incfly it seems ok to me work on the prometheus part, should be open another issue referencing this one or my pull request for that should be in this issue?

also as said by @ayj , i think the document formalizing requirements and use cases will ease the task

**Comment by incfly** [comment]
I've complete the section in [mTLS adoption simplification, lockdown section](https://docs.google.com/document/d/1yEMDRO2FZCyZnDK1AzNmjQtbtQqE7wN8YoM65FAH7uA/edit#heading=h.495in6gkmu26) , @diemtvu @esnible @ayj PTAL, thanks.

The complete design doc is about `mTLS adoption simplification`. This FR is scoped for one of the step to help customer easily lock down from PERMISSIVE to STRICT.

**Comment by incfly** [comment]
We are not gonna do this in short period... I think
