### ISSUE TITLE
Go mod is not friendly to users with limited network and network disconnection.

### ISSUE THREAD

**Issue by dangit815** [istio/istio#16878]
I wanted to compile istio in my PC, but When I run the "go mod download" command, it failed because of limited network. So, I am confusing about the "go mod", I think the "vendor folder" is more convenient for most people. Can we add the "vendor folder" back?

**Comment by howardjohn** [comment]
At some point you have to download the dependencies, even with vendor. If you can do `git clone` you should be able to do `go mod download`?

you can even do `go mod vendor` locally

**Comment by dangit815** [comment]
Thank you for your reply. I am trying to compile istio in my company network, but this network is restricted and can't access some URLs. I can't do *git clone* for some packages in the go.mod file, so the *go mod download* can't run successfully.
If *vendor file* exists, I can try to compile istio locally without network.

**Comment by dangit815** [comment]
Thank you for your reply. I am trying to compile istio in my company network, but this network is restricted and can't access some URLs. I can't do **git clone** for some packages in the go.mod file, so the **go mod download** can't run successfully.
If **vendor file** exists, I can try to compile istio locally without network.

**Comment by howardjohn** [comment]
You can also get  GOPROXY set. I'm not sure why you can do a git clone of istio but not other GitHub repositories?

The istio project has no intention of adding the vendor folder back. This is the standard Go project setup now

**Comment by dangit815** [comment]
Thank you. I solved this problem by setting up a new proxy! @howardjohn
