### ISSUE TITLE
xds: transition to use goproto stubs instead of gogoproto

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#16871]
The goproto stubs are now available in a branch:
`go get github.com/envoyproxy/go-control-plane/v2@556866f6aea9ab7a1f60a39e6a90156411a4462a`

/cc @geeknoid

**Comment by kyessenov** [comment]
see https://github.com/envoyproxy/go-control-plane/issues/213

**Comment by howardjohn** [comment]
What are the implications of the change? Is performance different? Is the API different at all?

**Comment by kyessenov** [comment]
The performance is likely to degrade in the short term (gogo was chosen because it's faster). However, there's a next-gen golang/protobuf that promises to be better. 
Envoy will also maintain their go stubs automatically so we don't have to manually patch up gogo stubs.
In any case, this is not data plane, so the performance concerns are not as pressing. There's so much JSON round-about still that it's far from being the bottleneck.

**Comment by geeknoid** [comment]
We originally chose to use gogo specifically because of the Envoy->Mixer
protocol, we wanted that as fast as possible. Because of that, everything
ended up on the gogo plan. Things will definitely get simpler if we can
move off of gogo in general.

**Comment by kyessenov** [comment]
@duderino @rshriram - this is a fairly mechanical change that needs to be done at some point. Please consider this for 1.4.

**Comment by howardjohn** [comment]
Done #17132
