### ISSUE TITLE
Proxy tries to read cert file at /etc/certs/cert-chain.pem even though SDS is enabled when a config map is updated

### ISSUE THREAD

**Issue by pitlv2109** [istio/istio#16895]
**Bug description**
Proxy tries to read cert file at /etc/certs/cert-chain.pem even though SDS is enabled when a config map is updated

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Proxy should not be looking for cert file.

**Steps to reproduce the bug**
1. Install Istio 1.3-rc-1 or some newer version with SDS and mTLS.
2. Deploy BookInfo with sidecar, check productpage log with -f and make sure things are working by visiting the webpage.
3. Update a config map, for example, run 
`helm template install/kubernetes/helm/istio --namespace=istio-system -x templates/configmap.yaml --set global.proxy.accessLogFile="/dev/stdout" | kubectl replace -f -`
4. Watch the log of productpage, it should say something like `Invalid path: /etc/certs/cert-chain.pem`, but productpage should still be accessible when visiting the webpage. 
5. Restart all BookInfo pods (this can happen during an update), now it will fail. 

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Istio 1.3-rc-1, but it should happen with older versions as well.

**Comment by JimmyCYJ** [comment]
Per offline discussion, I think this is because when you update config map in step 3, you didn't pass the SDS helm values to generate the installation yaml file. Could you verify that?
