### ISSUE TITLE
IstioControlPlane protoc fails on option go_package

### ISSUE THREAD

**Issue by ostromart** [istio/istio#16899]
Normally, IstioControlPlane proto in istiocontrolplan_types.proto would have 
package istio.operator.v1alpha2;
and 
option go_package="istio.io/operator/pkg/apis/istio/v1alpha2";
to restore the expected v1alpha2 package name for Go structs. 
However, make generate-types errors out with a message about being unable to create a /tmp/pkg dir.

**Comment by howardjohn** [comment]
@ostromart is this still an issue?

**Comment by ostromart** [comment]
No, it got fixed.
