### ISSUE TITLE
presubmit can fail randomly for nonexistent autogen files

### ISSUE THREAD

**Issue by jmuk** [istio/istio#1689]
from https://github.com/istio/istio/pull/1672:

the presubmit fails with missing `mixer/template/authz` files, but those files do not exist on master, on the base branch, nor on the PR. We need to figure out the solution.

cc: @mandarjog @yutongz

**Comment by jmuk** [comment]
It would be summarized the situation here. Here's my theory:
1. presubmit bot instances keep the old build artifacts (binaries or genfiles). This helps to speed up the incremental build.
2. `bin/bazel_to_go.py` checks `bazel-genfiles` in the workspace, and copies the generated files into the repository (and updates `generated_files` file)
3. when a PR adds a new autogen file, and then a presubmit run for another PR is invoked -- there are generated aretifacts in `bazel-genfiles`, but the PR does not have anything for that.
4. presubmit check thinks some autogen files are not properly copied, fail!

**Comment by jmuk** [comment]
Apparently we can run `bazel clean` before building, but the build would take longer with this structure. An idea is cleaning up `bazel-genfiles` directory only -- another approach would be to fix `bin/bazel_to_go.py` to collect the autogen files properly.

**Comment by geeknoid** [comment]
Bazel is dead, can we close?

**Comment by jmuk** [comment]
yes
