### ISSUE TITLE
Multi-cluster with replicated control planes is broken

### ISSUE THREAD

**Issue by israel-hdez** [istio/istio#16890]
**Bug description**

Multi-cluster setup using replicated control planes seems to be broken. Following instructions available at: https://preliminary.istio.io/docs/setup/install/multicluster/gateways/ results in "503 Service Unavailable" errors.

This is using pod-to-remote-istioingress approach (not using istioegress to hop into the remote cluster; which I have not tried, so I cannot say if it would work).

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Services from a remote cluster should be accessible.

**Steps to reproduce the bug**
* Follow install instructions available at: https://preliminary.istio.io/docs/setup/install/multicluster/gateways/
  * At step (2), I'm using a modified command to render the Istio charts:
```bash
helm template install/kubernetes/helm/istio --name istio --namespace istio-system \
  -f install/kubernetes/helm/istio/values-istio-demo.yaml \
  -f install/kubernetes/helm/istio/example-values/values-istio-multicluster-gateways.yaml \
  > istio.yaml
```
* Install the example services following section https://preliminary.istio.io/docs/setup/install/multicluster/gateways/#configure-the-example-services
  * When running step (5) to check if service is accessible I get a `503 Service Unavailable` error. Using curl's -v flag generates this output:

```
*   Trying 127.255.0.2...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x55e006beb7a0)
* Connected to httpbin.bar.global (127.255.0.2) port 8000 (#0)
> HEAD /headers HTTP/1.1
> Host: httpbin.bar.global:8000
> User-Agent: curl/7.64.0
> Accept: */*
> 
HTTP/1.1 503 Service Unavailable
content-length: 91
content-type: text/plain
date: Fri, 06 Sep 2019 17:30:35 GMT
server: istio-envoy
x-envoy-decorator-operation: :0/*

< HTTP/1.1 503 Service Unavailable
< content-length: 91
< content-type: text/plain
< date: Fri, 06 Sep 2019 17:30:35 GMT
< server: istio-envoy
< x-envoy-decorator-operation: :0/*
< 
```

The only logs I can find that may help to troubleshoot are in the istio-proxy of the sleep svc:

```
[2019-09-06T17:36:36.021Z] "HEAD /headers HTTP/1.1" 503 UF "-" "-" 0 0 0 - "-" "curl/7.64.0" "7d8cf243-5069-46b7-ae84-e681a323d1ad" "httpbin.bar.global:8000" "127.255.0.2:8000" InboundPassthroughClusterIpv4 - 127.255.0.2:8000 127.0.0.1:59350 - default
```

I see the "UF" flags. Pinging the remote cluster inside the sleep service works correctly, so communication seems not blocked. 

No logs being generated at remote istioingress. Also, no logs are generated in remote httpbin istio-proxy.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Istio: 1.3.0-rc.1
k8s: 1.15.2

FYI: Using Istio 1.2.4 all works OK. This issue seems to be particular to the coming 1.3 release.

**How was Istio installed?**
* Following the steps at https://preliminary.istio.io/docs/setup/install/multicluster/gateways/.
* ServiceEntries were adapted to the minikube case (using minikube ip to fetch the remote cluster IP and using the TLS NodePort of the ingressgateway)

**Environment where bug was observed (cloud vendor, OS, etc)**
minikube

**Comment by cart** [comment]
I have replicated this in my AKS clusters

**Comment by cart** [comment]
Also: Istio 1.2.5 does work fine for me

**Comment by ameer00** [comment]
Also: Istio 1.2.6 works fine for me.  Confirming this is not working in 1.3.0.  I am following the instructions to the letter [here](https://istio.io/docs/setup/install/multicluster/gateways/) and have tested on GKE 1.13 and GKE 1.14.  I get a:
```
curl: (56) Recv failure: Connection reset by peer
command terminated with exit code 56 
``` 

On the exact same setup, everything being the same and just chsanging the Istio version to 1.2.6 works.

**Comment by tapaskapadia** [comment]
I had the same issue with Istio 1.3.0. I saw 503 errors when I had CNI enabled and the same connection reset by peer posted by @ameer00 when I installed it without cni enabled. 
```
curl: (56) Recv failure: Connection reset by peer
command terminated with exit code 56 
```

Downgrading to Istio 1.2.6 resolved my issue of installing multi-cluster istio with replicated control planes.

**Comment by sodhc718** [comment]
I had the same issue with GKE 1.14, change to using class E address instead of 127.255.0.2 or multicast address fixed it
Related to those: PR https://github.com/istio/istio.io/pull/5036 and https://github.com/istio/istio.io/pull/5051

**Comment by tapaskapadia** [comment]
I can confirm that this resolved the issue for me. The new instructions on the istio page / istio 1.3.1 are working as expected.

**Comment by israel-hdez** [comment]
OK, I also have it working using class E range. So I'm closing this issue.

**Comment by ericvn** [comment]
I just ran through the docs using Istio 1.3.1 on IKS and things worked as expected.
