### ISSUE TITLE
Istio-telemetry rebalancing with session affinity.

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#16905]
Stack driver adapter for mixer v1 needs session affinity from istio-proxy to istio-telemetry pods. If a telemetry pods becomes overloaded,  we start dropping metrics. 

Under normal circumstances an HPA will kick in and take up extra load, but this will not happen due to affinity.

We need to experiment and provide guidance for how to distribute load.

Potential solution
1. Bring up new capacity (several extra pods).
2. Remove the endpoint of the overloaded pod from endpoints
    This should stop new traffic to the pod and give it time to shutdown.
3. Shutdown the pod. --> this will break existing TCP connections and they will be redistributed to other pods.

**Comment by douglas-reid** [comment]
@mandarjog this is fairly open-ended. can you help scope the work effort intended? 

what priority do you think this should be treated as? 

also, how wild can/should we get with our experimentation?  for instance, can/should we consider creating alternate architectures/adapters that push reports into a separate location for offline processing (sorta recreate the mixer backend with a separate set of services)? or say implement/configure some sort of consistent-hashing sharding scheme that uses Mixer's own load-shedding calculations in Mixer's frontend in combination with HPA?

**Comment by mandarjog** [comment]
For a customer that plans to use Mixer V1 /Stackdriver in production with 1.2 or 1.3, We need to provide guidance or double back on "please pre-scale". I would not add too much new code if possible, and too much complexity. We would like to have bounded worst case behaviour.
