### ISSUE TITLE
VirtualService on single virtual gatway using same hosts not able to do uri prefix for more than 16 services.

### ISSUE THREAD

**Issue by librannk** [istio/istio#16933]
Below is my virtual service (removed names to generic ones)

Scenario : i am doing path based routing for host.some.com, and based on the prefix , i am redirecting to various services 

issue: upto 16 services it works fine , after 16 services it is not working , if i delete one service it starts working ..
is there any limit on virtual service ??

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: service1
  namespace: istio-system
spec:
  hosts:
  - "hostname-some.com"
  gateways:
  - plx-gateway
  http:
  - match:
    - uri:
        prefix: /api/v1/service1
    route:
    - destination:
        host: first-service.default.svc.cluster.local
        port:
          number: 80

**Comment by jfeddern** [comment]
I don't think that there is any limitation. We are using a VirtualService configuration with around 70 different services (also prefix based routing).

**Comment by howardjohn** [comment]
Can you provide config with `istioctl proxy-config routes POD -ojson` with 16 and 17 matches?
