### ISSUE TITLE
Additional ingress gateway

### ISSUE THREAD

**Issue by santhosh-git** [istio/istio#16943]
We are using the default ingress gateway for istio. We would like to create two different ingress gateway for using private and public external load balancer.

Is there any way to achieve this?

**Comment by howardjohn** [comment]
Take a look at https://github.com/istio/istio/issues/9426. https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/example-values/values-istio-gateways.yaml

**Comment by santhosh-git** [comment]
> Take a look at #9426. https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/example-values/values-istio-gateways.yaml

It's not properly documented :(
