### ISSUE TITLE
Test gap: verify behavior of SDS when CA gRPC is terminated (citadel restart, etc) 

### ISSUE THREAD

**Issue by costinm** [istio/istio#16942]
Both IstioCA and GoogleCA initialize the gRPC in main() - there is a TODO on both about 
reconnecting, but it doesn't seem to be implemented. For example citadel/client.go:69

sendRetriableRequest is retrying the request - but it is not reconnecting. It doesn't appear to have any other recovery.

Killing citadel can be used to reproduce it.

**Comment by costinm** [comment]
Note this does not affect SDS for ingress.

**Comment by rlenglet** [comment]
> but it is not reconnecting

The gRPC client is normally automatically reconnecting with the default options, which is the case here.
Have you observed that it doesn't reconnect?

**Comment by costinm** [comment]
Sorry, I didn't get to grab the logs. 

Confirmed that grpc is reconnecting with backoff - and there is the backoff on SDS code itself.  It may be just a timing issue.

**Comment by costinm** [comment]
Updated the title - I think the remaining issue is to understand the timing and config options around retries/backoff.  And remove the comment around Dial(), I got confused by it and stopped looking for other causes.

**Comment by costinm** [comment]
https://github.com/grpc/grpc/blob/master/doc/connection-backoff.md - seems 2 minute is the max backoff, with 20 sec min. On top of this there is the retry/backoff in the sds code.

**Comment by incfly** [comment]
Things change a lot since the issue is filed. @myidpt @JimmyCYJ could you confirm whether there still some AI here?
