### ISSUE TITLE
Flaky test:  TestGetNodeAgentSecrets

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#16954]
Example failure in prow: https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16921/unit-tests_istio/150

Easily reproducible locally with `go test ./istioctl/pkg/writer/compare/sds -run TestGetNodeAgentSecrets -count 5`

**Comment by howardjohn** [comment]
It is because the ordering is not deterministic

**Comment by Monkeyanator** [comment]
Addressed in [https://github.com/istio/istio/pull/16956](https://github.com/istio/istio/pull/16956)
