### ISSUE TITLE
Add helm option to make Prometheus not scrape applications metrics

### ISSUE THREAD

**Issue by cebernardi** [istio/istio#16968]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
I would like to explore the possibility to configure Prometheus to NOT scrape any of the applications metrics when I install / update Istio via helm

**Describe alternatives you've considered**
I could obtain the results manually modifying prometheus config map and restarting the service, but since I'm working in an environment that is heavily relying on helm, this solution it's not really practical for my use case

**Affected product area (please put an X in all that apply)**

[X] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**
In my use-case we already have a Prometheus instance in the cluster that is taking care of the application metrics; as you can imagine the applications are already annotated to get discovered by prometheus, so right now we're collecting duplicated metrics.
At the moment configuring a federated instance is not an option, so ideally I would like to limit the kubernetes service discovery by namespaces, because we're interested in Istio metrics, but not in the rest of the apps.

I have a branch with the proposed solution and I can open a PR if you think this request is reasonable.

**Comment by sdake** [comment]
Please be aware that we are no longer investing in the old installer we ship with 1.3 and prior versions of Istio including the upcoming Istio 1.4.  This work will be replaced by the operator here: https://github.com/istio/operator.  If the operator doesnt meet your need please open a new issue with the operator as a baseline.

Cheers
-steve
