### ISSUE TITLE
DEV-GUIDE.md refers to gazelle, do we support that?

### ISSUE THREAD

**Issue by jmuk** [istio/istio#1696]
Currently DEV-GUIDE.md recommends to use gazelle for formatting BUILD files (see https://github.com/istio/istio/blob/580f97c0c232129bdd5560bf2846e6b8e75e73f2/DEV-GUIDE.md#source-file-dependencies). I've heard from @douglas-reid and @mandarjog that gazelle does not work with current istio/istio repository. Also the `make gazelle` command (mentioned in the link) doesn't even exist actually.

Shouldn't we remove this section for the time being?

**Comment by andraxylia** [comment]
We are moving to a standard go build, so gazelle will no longer be used.

**Comment by jmuk** [comment]
That's good to know. Let me close this item for now, we don't have to eagerly remove the mentions of gazelle, anyways the DEV-GUIDE.md will be hugely updated when we fully switch to the standard go build.

**Comment by douglas-reid** [comment]
Before we kill gazelle, let's see what the execution plan is moving forward. It was fixed to work with istio/istio recently, iirc. when we move to go:generate and away from bazel-generation + bazel_to_go scripting but before the cutover from Bazel is complete, running gazelle over the repo to ensure bazel compatibility will likely be desired (if not required).
