### ISSUE TITLE
Istio Operator Patching Prometheus Fails

### ISSUE THREAD

**Issue by William-Newshutz** [istio/istio#16971]
**Bug description**
I tried to have an IstioControlPlane v1alpha2 CustomResource to patch Prometheus into Istio-Telemetry's template. I received an error of "prometheus.io/scrape" not being recognized as valid syntax.
File:
```apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
metadata:
  name: istio-control-plane-custom-resource
spec:
  telemetry:
    components:
      telemetry:
        k8s:
          overlays:
          - kind: Deployment
            name: istio-telemetry
            patches:
            - path: spec.template.metadata.annotations.prometheus.io/scrape
              value: “true”
```
Error: ```patch error: path not found at element prometheus in path spec.template.metadata.annotations.prometheus.io/scrape exit status 255```

We believe the problem is the IstioControlPlane CRD does not have Prometheus in its spec.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
I expected the IstioControlPlane CustomResource to patch the istio-telemetry yaml to include the prometheus.io annotations in the template.
```apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-telemetry
spec:
  template:
    metadata:
      annotations:
        prometheus.io/scrape: “true”
```
**Steps to reproduce the bug**
File:
```apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
metadata:
  name: istio-control-plane-custom-resource
spec:
  telemetry:
    components:
      telemetry:
        k8s:
          overlays:
          - kind: Deployment
            name: istio-telemetry
            patches:
            - path: spec.template.metadata.annotations.prometheus.io/scrape
              value: “true”
```
Take the CR file above, or one like it, and run Mesh against it. Mesh checks the validity of the CR.
```Mesh manifest generate --dryrun -f <file>``` or
```go run mesh.go manifest generate --dry-run -f <file>```  

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Clone of the istio/operator repo as of Sept 9th 2019

**How was Istio installed?**
Mesh was installed using the https://github.com/istio/operator readme.

**Environment where bug was observed (cloud vendor, OS, etc)**
macOS Mojave command line.

**Comment by richardwxn** [comment]
You may try write your patch like below: 
path: spec.template.metadata.annotations 
  value:
            prometheus.io/scrape: "true"
             sidecar.istio.io/inject:  "false"

**Comment by William-Newshutz** [comment]
That format (shown below) did the trick. Thank you.
```
path: spec.template.metadata.annotations
  value:
    prometheus.io/scrape: "true"
    sidecar.istio.io/inject: "false"
```
