### ISSUE TITLE
Add basic suite of multi-object analyzers for validation framework

### ISSUE THREAD

**Issue by sushicw** [istio/istio#16977]
This is a follow up to https://github.com/istio/istio/pull/16350 to add some analyzers to the bare-bones framework. Specifically, we want enough analyzers to 1) vet the process of writing them, 2) demo how to writ them, 3) Add some concrete value for users experimenting with `istioctl experimental analyze`. 

**Affected product area (please put an X in all that apply)**

[X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by sushicw** [comment]
https://github.com/istio/istio/pull/16909

**Comment by esnible** [comment]
Adding myself so that I track this and get the experience of writing an analyzer.  I am not trying to take over @sushicw 's work.

**Comment by sushicw** [comment]
@esnible Check out the above-linked PR for some initial examples.
