### ISSUE TITLE
Observed periodical memory spike during proxy hot restart in perf test against release-1.3 rc.3

### ISSUE THREAD

**Issue by JimmyCYJ** [istio/istio#16987]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
This is observed in perf test against istio release 1.3 rc.3. The perf test use file mount to provide certificate for workloads, and a random port name is used in httpbin and sleep service deployment.
https://snapshot.raintank.io/dashboard/snapshot/jPJKyTv8CfMB0nnW2Nv0DU7u264U3MMK

The spike happens every 15 minutes, and all proxies are hot restart every 15 mins for cert refreshing. Overall the memory usage is quite stable, no memory leak is found. 

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[x] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

Change spec.ports.name to a random string in https://github.com/istio/tools/blob/master/perf/security/workload-deployments/templates/httpbin_template.yaml. 
Follow README in https://github.com/istio/tools/tree/master/perf/security/file-mount-tests/non-sds-1 to start test.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.7", GitCommit:"4683545293d792934a7a7e12f2cc47d20b2dd01b", GitTreeState:"clean", BuildDate:"2019-06-06T01:46:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-gke.8", GitCommit:"7d3d6f113e933ed1b44b78dff4baf649258415e5", GitTreeState:"clean", BuildDate:"2019-06-19T16:37:16Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
I think this is expected. When a hot restart occurs, 2 instances of envoy are running at once, so memory is 2x for a short period of time. Do you not normally see that?

**Comment by JimmyCYJ** [comment]
That makes sense. I just check the old one and find that it is not using a short lived cert, so proxy is not hot restarted that frequently. Closing this issue now.
