### ISSUE TITLE
Remove v1alpha1 authentication policy label selectors

### ISSUE THREAD

**Issue by diemtvu** [istio/istio#16986]
**Describe the feature request**

This is added a while back but got diverted due to the alternative plans for a new authentication policy. The flag has been hidden all the time anyway. It's better to remove it now to avoid misunderstanding.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by diemtvu** [comment]
+ @GregHanson @incfly FYI

**Comment by incfly** [comment]
SGTM

**Comment by incfly** [comment]
Might worth checking the design docs(if any) needs to be updated
correspondingly as well, to reflect status quo.
