### ISSUE TITLE
Downgrade SDS to file-based certs seamlessly 

### ISSUE THREAD

**Issue by pitlv2109** [istio/istio#16984]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Support the case where users want to downgrade from SDS to file-based certs. Currently, it's not working out of the box. 

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
Not a concern anymore, SDS is now the only supported method

**Comment by 1hanymhajna** [comment]
@howardjohn i think need this feature in order to be able to upgrade from 1.2.x with sds to the latest version.
for now if you run with istio with sds in the old version, you cannot upgrade to new versions
