### ISSUE TITLE
Supporting SDS on the new installer

### ISSUE THREAD

**Issue by myidpt** [istio/istio#16982]
**Describe the feature request**
Support SDS on the new installer istio/installer. This includes the following, ordered by priorities:

* SDS for provisioning keys and certs for the workloads.
* SDS for provisioning keys and certs for the control plane services.
* Gradual SDS adoption.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by pitlv2109** [comment]
Could you specify what is "Gradual SDS adoption"?. Also, this may be related https://github.com/istio/istio/issues/16984

**Comment by howardjohn** [comment]
Done
