### ISSUE TITLE
support deployment for add-to-mesh

### ISSUE THREAD

**Issue by irisdingbj** [istio/istio#16997]
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by esnible** [comment]
@irisdingbj Can you label this with the milestone you intend to deliver?  1.5?  Nebulous?

**Comment by esnible** [comment]
@irisdingbj Can you label this with the milestone you intend to deliver? 1.5? Nebulous?
