### ISSUE TITLE
Apply istio rbac for https application

### ISSUE THREAD

**Issue by dhineshbabuelango** [istio/istio#16999]
Hi Team, I am using istio in EKS. We have an application which will accept only HTTPS traffic. The application was working fine and we are able to access the application through istio-ingress gateway until we apply RBAC.

![image](https://user-images.githubusercontent.com/51995628/64668849-cd3a3080-d491-11e9-8a0b-1136c97c0a94.png)
After this we try to apply service role and service role binding, but we are not able to access our application getting the below error…
Do we need to add anything in extra for this hTTPS connection.
**upstream connect error or disconnect/reset before headers. reset reason: connection termination**

when I try to access from other pods, I am getting the below error 
![image](https://user-images.githubusercontent.com/51995628/64756150-6d5e8b00-d560-11e9-86ec-7b5f598c43c7.png)

Service-Role and Role Binding.

![image](https://user-images.githubusercontent.com/51995628/64756171-89622c80-d560-11e9-9670-b7a7db51777c.png)

Our mTLS configuration:

![image](https://user-images.githubusercontent.com/51995628/64668869-e2af5a80-d491-11e9-9b68-22a4f07d1238.png)

**Comment by vadimeisenbergibm** [comment]
I do not see any problem with the configuration. Please note that the `paths` and `methods` are not relevant for HTTPS RBAC.

Please do the following:
1. Remove `paths` and `methods` fields. It should not help, but please check it to be on the safe side.
2. Dump and publish the Envoy configuration (listeners and clusters) for the `isamotp-isamconfig` pod and for the pod you run curl to access `isampotp-isamconfig`. See https://istio.io/docs/ops/traffic-management/proxy-cmd/#deep-dive-into-envoy-configuration.

**Comment by dhineshbabuelango** [comment]
Hi Vadim, After I remove the paths and method, I am able to access the services.  Thanks for the help.

**Comment by vadimeisenbergibm** [comment]
@dhineshbabuelango Yes, you should not mention paths and methods for HTTPS traffic, since for Istio it is just like TCP traffic. The HTTP information, including paths and methods, is encrypted when the traffic is HTTPS, and Istio can neither inspect paths and methods nor apply policies based on them. 

Could you please close the issue?

**Comment by dhineshbabuelango** [comment]
Thanks Vadim for the help :)
