### ISSUE TITLE
helm lint errors 

### ISSUE THREAD

**Issue by ostromart** [istio/istio#17035]
Helm linting has started running on istio/operator and there are errors. These must be fixed in the istio/installer upstream charts.

**Comment by ostromart** [comment]
==> Linting ./data/charts/gateways/istio-ingress
[ERROR] templates/: render error in "istio-ingress/templates/serviceaccount.yaml": template: istio-ingress/templates/serviceaccount.yaml:3:14: executing "istio-ingress/templates/serviceaccount.yaml" at <.Values.global.image...>: map has no entry for key "global"

==> Linting ./data/charts/gateways/istio-egress
[ERROR] templates/: render error in "istio-egress/templates/serviceaccount.yaml": template: istio-egress/templates/serviceaccount.yaml:2:15: executing "istio-egress/templates/serviceaccount.yaml" at <$gateway.sds>: map has no entry for key "sds"

==> Linting ./data/charts/istio-telemetry/grafana
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: render error in "grafana/templates/tests/test-grafana-connection.yaml": template: grafana/templates/tests/test-grafana-connection.yaml:1:14: executing "grafana/templates/tests/test-grafana-connection.yaml" at <.Values.global.enabl...>: map has no entry for key "global"

==> Linting ./data/charts/istio-telemetry/mixer-telemetry
[ERROR] templates/: render error in "mixer-telemetry/templates/serviceaccount.yaml": template: mixer-telemetry/templates/serviceaccount.yaml:3:14: executing "mixer-telemetry/templates/serviceaccount.yaml" at <.Values.global.image...>: map has no entry for key "global"

==> Linting ./data/charts/istio-telemetry/prometheus-operator
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: render error in "prometheus-operator/templates/servicemonitors.yaml": template: prometheus-operator/templates/servicemonitors.yaml:15:18: executing "prometheus-operator/templates/servicemonitors.yaml" at <.Values.global.telem...>: map has no entry for key "global"

==> Linting ./data/charts/istio-telemetry/tracing
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: render error in "tracing/templates/deployment-jaeger.yaml": template: tracing/templates/deployment-jaeger.yaml:24:14: executing "tracing/templates/deployment-jaeger.yaml" at <.Values.tracing.cont...>: map has no entry for key "contextPath"

==> Linting ./data/charts/istio-telemetry/kiali
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: render error in "kiali/templates/serviceaccount.yaml": template: kiali/templates/serviceaccount.yaml:3:16: executing "kiali/templates/serviceaccount.yaml" at <.Values.global.image...>: map has no entry for key "global"

==> Linting ./data/charts/istio-telemetry/prometheus
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: render error in "prometheus/templates/tests/test-prometheus-connection.yaml": template: prometheus/templates/tests/test-prometheus-connection.yaml:1:14: executing "prometheus/templates/tests/test-prometheus-connection.yaml" at <.Values.global.enabl...>: map has no entry for key "global"

==> Linting ./data/charts/istio-control/istio-discovery
[ERROR] templates/: render error in "istio-discovery/templates/serviceaccount.yaml": template: istio-discovery/templates/serviceaccount.yaml:1:13: executing "istio-discovery/templates/serviceaccount.yaml" at <.Values.clusterResou...>: map has no entry for key "clusterResources"

==> Linting ./data/charts/istio-control/istio-config
[ERROR] templates/: render error in "istio-config/templates/serviceaccount.yaml": template: istio-config/templates/serviceaccount.yaml:3:14: executing "istio-config/templates/serviceaccount.yaml" at <.Values.global.image...>: map has no entry for key "global"

==> Linting ./data/charts/istio-control/istio-autoinject
[ERROR] templates/: render error in "istio-autoinject/templates/sidecar-injector-configmap.yaml": template: istio-autoinject/templates/sidecar-injector-configmap.yaml:1:18: executing "istio-autoinject/templates/sidecar-injector-configmap.yaml" at <.Values.global.omitS...>: map has no entry for key "global"

==> Linting ./data/charts/security/nodeagent
[ERROR] templates/: render error in "nodeagent/templates/serviceaccount.yaml": template: nodeagent/templates/serviceaccount.yaml:3:14: executing "nodeagent/templates/serviceaccount.yaml" at <.Values.global.image...>: map has no entry for key "global"

==> Linting ./data/charts/security/certmanager
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: render error in "certmanager/templates/serviceaccount.yaml": template: certmanager/templates/serviceaccount.yaml:3:14: executing "certmanager/templates/serviceaccount.yaml" at <.Values.global.image...>: map has no entry for key "global"

==> Linting ./data/charts/security/citadel
[ERROR] templates/: render error in "citadel/templates/serviceaccount.yaml": template: citadel/templates/serviceaccount.yaml:8:16: executing "citadel/templates/serviceaccount.yaml" at <.Values.global.image...>: map has no entry for key "global"

==> Linting ./data/charts/istio-cni
[ERROR] templates/: render error in "istio-cni/templates/serviceaccount.yaml": template: istio-cni/templates/serviceaccount.yaml:3:14: executing "istio-cni/templates/serviceaccount.yaml" at <.Values.global.image...>: map has no entry for key "global"

==> Linting ./data/charts/crds
[ERROR] Chart.yaml: directory name (crds) and chart name (istio-crds) must be the same
[INFO] values.yaml: file does not exist
[ERROR] templates/: render error in "istio-crds/templates/namespaces.yaml": template: istio-crds/templates/namespaces.yaml:11:17: executing "istio-crds/templates/namespaces.yaml" at <.Values.global.istio...>: map has no entry for key "global"

==> Linting ./data/charts/istiocoredns
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: render error in "istiocoredns/templates/serviceaccount.yaml": template: istiocoredns/templates/serviceaccount.yaml:3:14: executing "istiocoredns/templates/serviceaccount.yaml" at <.Values.global.image...>: map has no entry for key "global"

==> Linting ./data/charts/istio-policy
[ERROR] templates/: render error in "istio-policy/templates/serviceaccount.yaml": template: istio-policy/templates/serviceaccount.yaml:3:14: executing "istio-policy/templates/serviceaccount.yaml" at <.Values.global.image...>: map has no entry for key "global"

**Comment by howardjohn** [comment]
The way we use helm is not really compatible with how linter works. We use the `global.yaml` file, but helm expects all known values to be in the local `values.yaml` file. So it would required a lot of reworking, not just minor patches

**Comment by ostromart** [comment]
Yeah, it's not even possible to silence it by adding nil values because that would cause global.yaml defaults to be overridden when the charts are rendered. 
Basically, this lint error is reporting the fact that even though we claim these are separate charts, they are not really separate because they have implicit dependency on global.yaml.

**Comment by howardjohn** [comment]
@ostromart we do have a lint target actually, `run-lint`, that does things like `helm lint istio-control/istio-discovery -f global.yaml`, and it works well. Do you think there is anything else to do here?

**Comment by gitsupersmecher** [comment]
Could you please explain a bit more in details what do you mean by global.yaml? In the examples I see that you have the values.yaml file, isn't this expected to work for helm lint and helm install? I have the same error that's called out here.

**Comment by howardjohn** [comment]
in the top level istio/installer folder there is a global.yaml file. All
helm commands are expected to be called with -f global.yaml

**Comment by howardjohn** [comment]
Working on fixing this
