### ISSUE TITLE
`istioctl experimental analyze` runs too slowly

### ISSUE THREAD

**Issue by sushicw** [istio/istio#17036]
**Bug description**

Starting from a vanilla install of the hipster demo app, running `istioctl analyze` currently takes about 8 seconds. That time is all spent waiting for resource events to propagate from the k8s client.

The most likely cause here is that the watchers we are using are slow and/or throttled. Using watchers makes a lot of sense for the Galley use case, where we need to react to a constant stream of changes, but it does not make sense for the istioctl use case where we need a point-in-time snapshot as responsively as possible.

@ozevren mentioned that we should be able to use a different kube client API to get resource data more synchronously instead of creating watchers. 

**Affected product area (please put an X in all that apply)**

[X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Go much faster

**Steps to reproduce the bug**

1. Install the hipster demo in a cluster (https://github.com/GoogleCloudPlatform/microservices-demo)
2. From a checked out istio/istio repo synced to master, run ```make istioctl && $GOPATH/out/linux_amd64/release/istioctl experimental analyze -k```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

master branch as of issue creation

**Environment where bug was observed (cloud vendor, OS, etc)**

GKE cluster running hipster demo

**Comment by sushicw** [comment]
Note that trying to get absolutely everything through kubectl is still measured in seconds. 
```
time kubectl get `kubectl api-resources | tail -n +2 | cut -f1 -d' ' | paste -sd','` --all-namespaces -o yaml > /tmp/dump.yaml
Error from server (NotFound): Unable to list "/v1, Resource=bindings": the server could not find the requested resource
Error from server (MethodNotAllowed): the server does not allow this method on the requested resource
Error from server (NotFound): Unable to list "authorization.k8s.io/v1, Resource=localsubjectaccessreviews": the server could not find the requested resource
Error from server (MethodNotAllowed): the server does not allow this method on the requested resource
Error from server (MethodNotAllowed): the server does not allow this method on the requested resource
Error from server (MethodNotAllowed): the server does not allow this method on the requested resource

real	0m6.280s
user	0m2.323s
sys	0m0.323s
```

**Comment by sushicw** [comment]
The current prevailing theory is that we're running into k8s throttling limits, whether via kubectl or the API. Using watchers does not seem to be the main source of lag, as originally supposed.

One TODO task: measure how/if this scales as the number of resources increases. Currently our sample size is "bookinfo is 3 seconds vs hipster is 8 seconds" but it would be good to see how much impact cluster size has here. 

Some ideas on how we could try to mitigate this:
* For each analyzer, keep track of what resource it needs to function. Only get those resources.
  * Caveats:
    1. This needs to be aware of transforms in the processing pipeline, so for each required resource we need to find all "input" resources that generate it and include them in the set to get. 
    2. The benefit of this will decrease as we add more analyzers that cover more and more resources.
  * *NOTE*: A quick & dirty prototype where I went to `metadata.yaml` and disabled a bunch of resources I knew were not needed did speed things up. e.g. removing the legacy resources cut the time down to less than 4 seconds. 
  * Other notes: The disabling needs to happen at the source level, not at the snapshot level. Like how we disable resources if service discovery is disabled. One straightforward way to do this will be to edit the list of resources from metadata (in local/analyze.go) and mark anything not claimed by an Analyzer as disabled. This process would need to be aware of transforms, and the plumbing for that will need some care. 
* Short term, we can just ignore "Optional" resources when running from istioctl. This cuts out a lot of legacy CRDs and in practice seems to make a significant difference (see above). I don't anticipate we'll write analyzers for the legacy CRDs, so this seems like a pretty safe assumption to make. 
* We could implement some sort of caching in istioctl, so that when we execute we just get the delta from the last run instead of re-snapshotting the whole cluster state from scratch.

**Comment by sushicw** [comment]
https://github.com/istio/istio/pull/17214 is pretty effective, bringing the 8 seconds down to about 1.5.

**Comment by davidebbo** [comment]
Sweet!
