### ISSUE TITLE
List all routes registered under a gateway

### ISSUE THREAD

**Issue by Ghost---Shadow** [istio/istio#17040]
**Describe the feature request**

A CLI command which dynamically calculates and lists all the routes attached to a gateway.

e.g.

```sh
$ istioctl describe gateway my-gateway -n my-namespace
registered-routes:
:80/dev/foo -> foo.dev.svc.cluster.local:80
:80/test/foo -> foo.test.svc.cluster.local:80
:80/dev/bar -> bar.dev.svc.cluster.local:80
:443/dev/bar -> bar.dev.svc.cluster.local:443
```

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure
[x] Debugging

**Additional context**

A lot of people (including me) are having trouble setting up istio ingress gateways. Adding this feature would help people debug the problem easily.

**Comment by howardjohn** [comment]
`istioctl proxy-config routes` has some info, maybe not in the shape you requested but it could probably be manipulated to do so (either through istioctl or processing the json output)

**Comment by Ghost---Shadow** [comment]
This was what I was looking for

```sh
istioctl proxy-config routes istio-ingressgateway-866d7949c6-68tt4 -n istio-system -o json > ./temp/routes.json
```

Thank you
