### ISSUE TITLE
ISTIO installation of 1.2.5 gets into CrashLoopBackOff if Citadel is stared with --listened-namespaces 

### ISSUE THREAD

**Issue by mrangana** [istio/istio#17047]
Generate SDS config:

_helm template install/kubernetes/helm/istio --name istio --namespace istio-system --values install/kubernetes/helm/istio/values-istio-sds-auth.yaml > istio-auth-sds.yaml_

Add  "--listened-namespaces=foo" to Citadel istio_ca args 

    _containers:
        - name: citadel
          image: "docker.io/istio/citadel:1.2.5"
          imagePullPolicy: IfNotPresent
          args:
            - --sds-enabled=true
            - --append-dns-names=true
            - --grpc-port=8060
            - --listened-namespaces=foo
            - --citadel-storage-namespace=istio-system
            - --custom-dns-names=istio-pilot-service-account.istio-system:istio-pilot.istio-system
            - --monitoring-port=15014
            - --self-signed-ca=true
            - --workload-cert-ttl=2160h
          resources:
            requests:
              cpu: 10m_

Installation gets into CrashLoopBackOff for policy and telemetry pods and never completes.
```
istio-citadel-6555d5f89b-l7ljv            1/1     Running             0          27m
istio-cleanup-secrets-1.2.5-jgmlj         0/1     Completed           0          27m
istio-galley-7898b587db-t5j9j             0/1     ContainerCreating   0          27m
istio-ingressgateway-795564894b-b9g7r     0/1     Running             0          27m
istio-nodeagent-vnlhg                     1/1     Running             0          27m
istio-pilot-7f7965b969-8gxcs              1/2     Running             6          27m
istio-policy-56d44d8bbd-7qcjz             1/2     CrashLoopBackOff    13         27m
istio-security-post-install-1.2.5-vstng   0/1     Completed           0          27m
istio-sidecar-injector-677bd5ccc5-6qxh6   0/1     ContainerCreating   0          27m
istio-telemetry-64c4556f6d-vkfrr          1/2     CrashLoopBackOff    13         27m
prometheus-776fdf7479-xc772               1/1     Running             0          27m
```
ISTIO comes up fine without this option added.

**Comment by howardjohn** [comment]
I suspect you need to include istio-system in listened-namespaces

**Comment by mrangana** [comment]
I was under the impression that by default it would include the namespace of the control palne it is running. It works after including the istio-system to the list. Thanks!

**Comment by howardjohn** [comment]
Glad its working now
