### ISSUE TITLE
Clean up pilot feature flags for 1.6

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#17053]
Candidates:
* `PILOT_ENABLE_FALLTHROUGH_ROUTE` if we are confident about our infinite loop detection
* `PILOT_DISABLE_XDS_MARSHALING_TO_ANY`  if no bugs found in 1.3
* `USE_ISTIO_JWT_FILTER` if no bugs found in 1.3
* `PILOT_RESTRICT_POD_UP_TRAFFIC_LOOP` I think this is not needed once we are on the split listeners only
* `PILOT_SCOPE_PUSHES` if no bugs found
* `PILOT_RESPECT_DNS_TTL` if no bugs found

Probably still needed:
* `PILOT_ENABLE_PROTOCOL_SNIFFING_FOR_OUTBOUND`/`PILOT_ENABLE_PROTOCOL_SNIFFING_FOR_INBOUND`
* `PILOT_SCOPE_GATEWAY_TO_NAMESPACE` not on by default in 1.3 -- maybe we can turn this to default in 1.4
* `PILOT_ENABLE_HEADLESS_SERVICE_POD_LISTENERS` not on by default in 1.3

**Comment by pbohman** [comment]
Leaving `PILOT_SCOPE_GATEWAY_TO_NAMESPACE` set to false seems to contradict the gateway documentation that states:

> The scope of label search is restricted to the configuration namespace in which the the resource is present. In other words, the Gateway resource must reside in the same namespace as the gateway workload instance.

**Comment by howardjohn** [comment]
Not stale

**Comment by howardjohn** [comment]
Update for 1.6:

Candidates:
USE_ISTIO_JWT_FILTER
PILOT_RESTRICT_POD_UP_TRAFFIC_LOOP

Keep
PILOT_ENABLE_PROTOCOL_SNIFFING_FOR_OUTBOUND/PILOT_ENABLE_PROTOCOL_SNIFFING_FOR_INBOUND
PILOT_SCOPE_GATEWAY_TO_NAMESPACE not on by default in 1.3 -- maybe we can turn this to default in 1.4
PILOT_ENABLE_HEADLESS_SERVICE_POD_LISTENERS not on by default in 1.3

**Comment by hzxuzhonghu** [comment]
i am sure `PILOT_RESTRICT_POD_UP_TRAFFIC_LOOP` can be removed now

**Comment by howardjohn** [comment]
#21977 cleans up `PILOT_RESTRICT_POD_UP_TRAFFIC_LOOP`

**Comment by howardjohn** [comment]
This was cleaned up
