### ISSUE TITLE
Support Citadel to automatically rotate root cert

### ISSUE THREAD

**Issue by JimmyCYJ** [istio/istio#17059]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Citadel needs to do root cert rotation automatically for both SDS and file-mount approach. 

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**
https://github.com/istio/istio/issues/13439

**Comment by JimmyCYJ** [comment]
https://github.com/JimmyCYJ/istio/pull/2

**Comment by JimmyCYJ** [comment]
https://github.com/istio/istio/pull/17942

**Comment by JimmyCYJ** [comment]
https://github.com/istio/istio/issues/18714

**Comment by howardjohn** [comment]
Is this done?

**Comment by howardjohn** [comment]
I am moving this to the 1.5 branch

**Comment by incfly** [comment]
I think it's done. Closing. @JimmyCYJ feel free to reopen if some is left

**Comment by JimmyCYJ** [comment]
https://github.com/istio/istio/issues/19644
