### ISSUE TITLE
CSS Issues on Bookinfo 1.15.0

### ISSUE THREAD

**Issue by gbaufake** [istio/istio#17050]
**Bug description**

Installing Bookinfo 1.15.0 is not loading the css on the product page

<img width="1680" alt="Captura de Tela 2019-09-12 às 10 26 31" src="https://user-images.githubusercontent.com/2313749/64788439-d76b3600-d548-11e9-8b70-518327366d3e.png">

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[X] Samples
**Expected behavior**

**Steps to reproduce the bug**

- Install Bookinfo 1.15.0

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

- Openshift 4.1

**Comment by gbaufake** [comment]
@howardjohn 
Uploading information from productpage
[clusters.txt](https://github.com/istio/istio/files/3618323/clusters.txt)
[config_dump.json.txt](https://github.com/istio/istio/files/3618324/config_dump.json.txt)
[proxy.log.txt](https://github.com/istio/istio/files/3618325/proxy.log.txt)
[stats.txt](https://github.com/istio/istio/files/3618326/stats.txt)

**Comment by gbaufake** [comment]
@rshriram @howardjohn any information on this one?

**Comment by howardjohn** [comment]
I think the problem is ingress -> productpage, so the more useful dump would be from the ingessgateway.

Can you access `curl productpage:9080/static/bootstrap/css/bootstrap.min.css` from another pod?

**Comment by jwendell** [comment]
Just installed istio and bookinfo from master and it is fine.

**Comment by howardjohn** [comment]
We cannot reproduce.

**Comment by bogd** [comment]
Came here because I was facing the exact same issue - 404 errors on /static/* . In my case, it turns out I had installed the bookinfo application, but had not applied the gateway configuration (networking/bookinfo-gateway.yaml).
