### ISSUE TITLE
istioctl validate should report deprecation warnings

### ISSUE THREAD

**Issue by esnible** [istio/istio#17056]
If a deprecated field is used, `istioctl validate` should tell the user.

For example `istioctl validate -f tests/testdata/config/rule-content-route.yaml` should report that sourceLabels is deprecated.

**Comment by esnible** [comment]
Currently `istioctl validate` will surface warnings.  For example

```
$ istioctl validate -f samples/bookinfo/policy/mixer-rule-deny-ip-crd.yaml
2019-09-16T20:46:56.619046Z	warn	deprecated Mixer kind "listchecker", please use "handler" or "instance" instead
2019-09-16T20:46:56.620071Z	warn	deprecated Mixer kind "listentry", please use "handler" or "instance" instead
```

in addition to the reported `error` the webhook-implementation generates.

There is no reporting of fields that are marked hidden or deprecated.

@ozevren Is there any way to surface the .proto information to Istio's Go bindings?

The .proto files have deprecation and hidden information:
```
  // $hide_from_docs
  map<string, string> append_headers = 11 [deprecated=true];
```

The generate Go code does not include a callable API for this.

Ideally there is some way to get `protoc` to surface the `$hide_from_docs` and `[deprecated=true]` into a method or struct tag, but I couldn't find such an approach.

**Comment by esnible** [comment]
@sushicw is there a guide to writing analyzers and attaching them to the framework?

**Comment by sushicw** [comment]
@esnible At the moment, we do not, but it's something that I want to do. I just created https://github.com/istio/istio/issues/17315 to track that work.

**Comment by esnible** [comment]
@sushicw Until we have some docs, is there a simple example analyzer I should use as a basis for creating my own?

**Comment by sushicw** [comment]
What we have so far can be found here: https://github.com/istio/istio/tree/master/galley/pkg/config/analysis/analyzers

Under that tree, virtualservice/gateways.go is probably the simplest one to look at. 

@jasonwzm : is this particular use case (reporting deprecated fields) something we can/should fold into your work with Cue?

**Comment by esnible** [comment]
The deprecation will be part of the `istioctl x analyze` framework.  In the future we may replace `istioctl validate` with that framework.  The analyze framework already reports all of the messages reported by `istioctl validate`.
