### ISSUE TITLE
Easier way to surface/debug state of Istio (ports actually proxied, etc)

### ISSUE THREAD

**Issue by saturnism** [istio/istio#17057]
**Bug description**

Istio is prone to missed-configuration where the missed configuration works perfectly in Kubernetes environment, but doesn't work in Istio environment, and there is no reliable way of debugging or prevent this.

For example, if a container has no `ports` defined, Istio essentially doesn't proxy any ports. However, it still allows consumers to connect to the port. When mTLS is enabled, the consumer will attempt to connect w/ TLS, the producer port is not proxied, and is expecting plain text. In strict mTLS, the producer port shouldn't even be accessible.

However, at the same time, `istio authn tls-check` shows no conflicts and indicated that mTLS is effective - when it's really not.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Expected behavior**

1. If no container ports defined, Istio sidecar proxy should reject/deny all connections, so that consumers sees connection refused.
1. `istioctl` can have a utility command to accurate display all the target names, and ports that are effectively proxied by Istio, and the expected connection type/protocol (mTLS, or plain, http, or grpc, etc)

**Steps to reproduce the bug**
1. Install Istio w/ mTLS turned on (mesh wide, strict mode). Turn on injection in `default` namespace
1. Run nginx - `kubectl run nginx --image=nginx`
1. Expose the service: `kubectl expose deployment nginx --port=80 --target-port=80`
1. Update the service to have the port. At this point, noticed that the pod still has no ports defined.
1. Chekc mTLS: `istio authn tls-check somepod` and see that mTLS is on, and there is no conflict.
1. Port forward to nginx pod: `kubectl port-forward ... 8080:80`
1. Connect to nginx pod: `curl localhost:8080`

This will succeed, which mismatches the the expectation of strict mTLS.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**
```
$ istioctl version
client version: 1.2.5
citadel version: 1.2.4
egressgateway version: 94746ccd404a8e056483dd02e4e478097b950da6-dirty
galley version: 1.2.4
ingressgateway version: 94746ccd404a8e056483dd02e4e478097b950da6-dirty
pilot version: 1.2.4
policy version: 1.2.4
sidecar-injector version: 1.2.4
telemetry version: 1.2.4

$istioctl version --remote
client version: 1.2.5
citadel version: 1.2.4
egressgateway version: 94746ccd404a8e056483dd02e4e478097b950da6-dirty
galley version: 1.2.4
ingressgateway version: 94746ccd404a8e056483dd02e4e478097b950da6-dirty
pilot version: 1.2.4
policy version: 1.2.4
sidecar-injector version: 1.2.4
telemetry version: 1.2.4
```

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

**Comment by esnible** [comment]
@saturnism does the `istioctl x describe pod` command provide any of the features you requested?

**Comment by saturnism** [comment]
> in 1.3 all ports are proxied, we no longer look at container ports

proxying all port was one of the ideal situation discussed w/ @lei-tang; i haven't tried it yet, but i hope the proxy also refuses ports that aren't available in the pod.

> istioctl x describe pod command in 1.3.0 ...

will give this a try.

**Comment by esnible** [comment]
@saturnism Does `istioctl x describe` help with this?  Is there additional output that would make sense for `describe`?

**Comment by JimmyCYJ** [comment]
Closing this issue as istioctl could help. @saturnism please feel free to reopen if there are more issues found.
