### ISSUE TITLE
Mesh expansion: connect VM without public IP and without using VPN

### ISSUE THREAD

**Issue by kirgene** [istio/istio#17062]
I'd like to add VM worker node to a cluster. VM is behind NAT and doesn't have public IP.
I need to access a service running on this VM from Kubernetes cluster (VM access to cluster services not needed).
How to accomplish this task without using VPN?
I follow [this](https://istio.io/docs/examples/mesh-expansion/multi-network/) guide to setup istio-sidecar connection from VM to the cluster, but to my surprise, I cannot use this connection for exposing VM service to cluster. It is said that I need to create ServiceEntry for service resolution using VM IP (like for third party external service).
So what is the point of establishing a connection between istio-sidecar (on VM) and the main cluster if I cannot use it (for port forwarding)?

**Comment by sdake** [comment]
@irisdingbj would you be king enough to answer this question and see if there is engineering work involved here?

Cheers
-steve
