### ISSUE TITLE
Automatically manage ports on ingress LoadBalancer services on behalf of Gateway resources

### ISSUE THREAD

**Issue by nickperry** [istio/istio#17076]
**Describe the feature request**
At present, ports on ingress gateway LoadBalancer services are typically specified via Helm chart values files. Adding a new port to a Gateway resource does not dynamically add that port to the spec of the LoadBalancer service associated with the gateway workload instances.

As an Istio user, I would like Istio to have the option to dynamically manage ports in the specification of the LoadBalancer services associated with the workload instances which host my ingress gateways. When I create a Gateway resource with a new port, or add a new port to an existing Gateway resource, if that port is not already exposed on the LoadBalancer service, Istio should add it.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[X] Configuration Infrastructure
[X] Docs
[X] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
This pretty strongly violates namespace boundaries unless we force Gateway to be in the same namespace as the deployment, since otherwise someone in another namespace (eg does not have permission to istio-system) can arbitrarily modify the gateway deployment
