### ISSUE TITLE
Helm Tracing Chart does not use global priorityClassName

### ISSUE THREAD

**Issue by aaronmell** [istio/istio#17088]
**Bug description**
Set the global.priorityClassName, but that value is not passed to mixer.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
priorityclass should be set in mixer 

**Steps to reproduce the bug**
set priorityClassName in the global config, and install mixer.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.3.0

**Comment by aaronmell** [comment]
priorityClassName is defined under policy_container, but not telemetry_container

**Comment by morvencao** [comment]
@aaronmell I'm using `helm template' + `kubectl apply`, didn't reproduce the issue, see:
```
root@mcdev1:~/istio-1.3.0# kubectl create namespace istio-system
namespace/istio-system created
root@mcdev1:~/istio-1.3.0# helm template install/kubernetes/helm/istio-init --name istio-init --namespace istio-system | kubectl apply -f -
configmap/istio-crd-10 created
configmap/istio-crd-11 created
configmap/istio-crd-12 created
serviceaccount/istio-init-service-account created
clusterrole.rbac.authorization.k8s.io/istio-init-istio-system created
clusterrolebinding.rbac.authorization.k8s.io/istio-init-admin-role-binding-istio-system created
job.batch/istio-init-crd-10-1.3.0 created
job.batch/istio-init-crd-11-1.3.0 created
job.batch/istio-init-crd-12-1.3.0 created
root@mcdev1:~/istio-1.3.0# helm template install/kubernetes/helm/istio --name istio --namespace istio-system --set global.priorityClassName="system-cluster-critical" --set tracing.enabled=true | kubectl apply -f -
...
root@mcdev1:~/istio-1.3.0# kc  -n istio-system get deploy istio-tracing -o yaml | grep priorityClassName -C 2
      dnsPolicy: ClusterFirst
      priorityClassName: system-cluster-critical
      restartPolicy: Always
```

Also tried to switch to zipkin provider, still found the `priorityClassName`:
```
root@mcdev1:~/istio-1.3.0# helm template install/kubernetes/helm/istio --name istio --namespace istio-system --set global.priorityClassName="system-cluster-critical" --set tracing.enabled=true --set tracing.provider=zipkin > istio.yaml
```

**Comment by aaronmell** [comment]
Sorry, my fault. I had the wrong chart. Updating ticket to reflect.

**Comment by aaronmell** [comment]
Looks like the change was made in master, but didn't make it into the 1.3.0 release

https://github.com/istio/istio/commit/409fb9765266db0ba5d24c677b5aabed82e7132c

**Comment by morvencao** [comment]
Yes, that's right, the change didn't make it into the 1.3.0 release. Cherry pick it to release-1.3 so that we can have it in 1.3.x: https://github.com/istio/istio/pull/17104
