### ISSUE TITLE
Multi Clusters (Single Mesh) - service resolution doesn’t work if service only runs in another cluster 

### ISSUE THREAD

**Issue by wenxian** [istio/istio#17087]
The architecture diagram is like Service A in Cluster A and Service B in Cluster B. Cluster A and Cluster B are joined using the Single Control Plane Multicluster Installation approach. If call service B from Cluster A, will that work? My test shows the DNS resolution doesn't work out

**Comment by hzxuzhonghu** [comment]
I donot think so. This model enforce services exists in all clusters by default.  But you can use cascading dns to resolve dns resolution in theory.

**Comment by wenxian** [comment]
If we use 'dns resolution' to expose the cluster DNS server, does istio-dns resolve the service name into Pod IP or Cluster IP?

**Comment by esnible** [comment]
To keep DNS lookups from failing an IP is needed.  But it doesn't need to be a real IP.  For example `127.255.0.2` (or anything `127.255.x.y`) usually works.

Follow the instructions in https://istio.io/docs/setup/install/multicluster/gateways/#setup-dns

**Comment by hzxuzhonghu** [comment]
yep, the multi-control plane dns model can be used in single-plane too.
