### ISSUE TITLE
failed to add sidecars.networking.istio.io CRD

### ISSUE THREAD

**Issue by dontreboot** [istio/istio#17085]
**Bug description**
I apply custom CRDs from `helm template install/kubernetes/helm/istio-init --name istio-init --namespace istio-system`; however, pod for job.batch/istio-init-crd-11-1.3.0 failed to create CRD sidecars.networking.istio.io.

I am running EKS 1.14 for the control plane and EKS 1.13 for the worker nodes.

```
 18:41:09  ~  istio-1.3.0  manifests  kubectl -n istio-system get all
NAME                                READY   STATUS             RESTARTS   AGE
pod/istio-init-crd-10-1.3.0-9fwkb   0/1     Completed          0          9m47s
pod/istio-init-crd-11-1.3.0-btk9p   0/1     CrashLoopBackOff   5          9m47s
pod/istio-init-crd-12-1.3.0-bfp96   0/1     Completed          0          9m47s

NAME                                COMPLETIONS   DURATION   AGE
job.batch/istio-init-crd-10-1.3.0   1/1           2s         9m47s
job.batch/istio-init-crd-11-1.3.0   0/1           9m47s      9m47s
job.batch/istio-init-crd-12-1.3.0   1/1           2s         9m47s
```

I can apply file /etc/istio/crd-11/crd-11.yaml that pod/istio-init-crd-11-1.3.0-btk9p manually without issues; however, I don't understand why pod/istio-init-crd-11-1.3.0-btk9p exited unsuccessfully. 

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
The pod for adding CRD sidecars.networking.istio.io should exit successfully.
**Steps to reproduce the bug**
```
helm template install/kubernetes/helm/istio-init --name istio-init --namespace istio-system|kubectl apply -f -
```
**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```
 18:48:08  ~  istio-1.3.0  manifests  istioctl version
2019-09-13T18:48:14.211958Z	warn	will use `--remote=false` to retrieve version info due to `no Istio pods in namespace "istio-system"`
1.3.0
 19:00:14  ~  istio-1.3.0  manifests  kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-07T09:55:27Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-eks-5047ed", GitCommit:"5047edce664593832e9b889e447ac75ab104f527", GitTreeState:"clean", BuildDate:"2019-08-21T22:32:40Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```
**How was Istio installed?**
With helm template and kubectl apply
**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
Please add logs from the job. You can pass the `-p` flag to get the logs from the previous container so we can see why it crashed

**Comment by howardjohn** [comment]
Can you add logs?
