### ISSUE TITLE
Prometheus Alert Manager On Istio

### ISSUE THREAD

**Issue by librannk** [istio/istio#17094]
Hi
i have been using istio grafana addon since long, now i wanted to enable alterts on the same , i could not  find a feature or addon to add alert manager on istio .

Can any one suggest how if this  feature can be added/exist in istio

i am using istio 1.1.7

**Comment by howardjohn** [comment]
Generally Istio is not trying to manage production grade Prometheus, grafana, etc deployments. We are doing some work to make it easy to integrate istio with your own Prometheus, kiali, etc. See https://github.com/istio/installer/tree/master/istio-telemetry/prometheus-operator as one way you can integrate with the Prometheus operator. You can define your own Prometheus setup then just add the configs to scrape istio components. 

I saw some plans to add alerts in 1.4, I'm not sure if that was a full fledged Prometheus alert manager though or alerts in grafana

**Comment by librannk** [comment]
Thanks for the response, i too thought so that right now add-ons for Prometheus are not production ready , hope to see same with later releases, although it would been great if istio could have been used but as of now i am planning to use Prometheus operator.

**Comment by howardjohn** [comment]
To be clear - you can use your own Prometheus operator with the rest of
istio and just swap out istio's Prometheus install and still use istio

**Comment by librannk** [comment]
yes i meant that only, using own Prometheus Operator instead of istio prom , till the time this addon is stable on istio,also i think same would be true for jaeger as well for tracing ??
  for rest stuff we are very much using istio already.

**Comment by howardjohn** [comment]
Yes, for all the add-ons I would say the official methods to install those
probably have more options exposed, or completely different things like
Thanos for Prometheus. I wouldn't say what ships with Istio is not stable,
just not as feature rich
