### ISSUE TITLE
sourceLabels  and gateways are missing in HTTPMatchRequest of Istio 1.3 

### ISSUE THREAD

**Issue by idouba** [istio/istio#17105]
Two important fields sourceLabels  and gateways are missing in [HTTPMatchRequest ](https://istio.io/docs/reference/config/networking/v1alpha3/virtual-service/#HTTPMatchRequest)of Istio 1.3  which can be used in[ 1.2](https://archive.istio.io/v1.2/docs/reference/config/networking/v1alpha3/virtual-service/#HTTPMatchRequest) and old release.

**Comment by hzxuzhonghu** [comment]
`sourceLabels` is deprecated long ago,  just marked hidden in 1.3

`gateways` is just hidden, should stop using it anymore

**Comment by esnible** [comment]
We discussed https://github.com/istio/api/commit/0e77ec00236554f76109f0e917c6a11de3fa97f7#diff-0820bb0406265ba9b9a9e11dcec06601 at the Networking Working Group meeting last Thursday.  We hope to have documentation of how to use a sidecars.networking.istio.io to get the behavior currently provided by sourceLabels.

The networking group is determining if the field should be restored but marked deprecated, remain hidden, or restored to visibility.

**Comment by hzxuzhonghu** [comment]
Thanks for your info @esnible

**Comment by Datamance** [comment]
@esnible can you briefly explain what the alternate routing configuration for TLS-terminated/HTTP traffic should be? You mentioned custom sidecar configurations - for which gateway? On a more fundamental note, why differentiate the [HTTPMatchRequest](https://istio.io/docs/reference/config/networking/virtual-service/#HTTPMatchRequest) API so much from that of [TLSMatchAttributes](https://istio.io/docs/reference/config/networking/virtual-service/#TLSMatchAttributes) and TCPRoute's [L4MatchAttributes](https://istio.io/docs/reference/config/networking/virtual-service/#L4MatchAttributes)? HTTP is built on top of TCP, so it stands to reason that the attributes provided for by L4MatchAttributes would be congruent with those found in HTTPMatchRequest.

FWIW, I strongly encourage your team to review and update documentation before hiding fields like that. I've spent quite a bit of time today confused by the mismatch between the [Egress Gateway for HTTP Traffic task documentation](https://istio.io/docs/tasks/traffic-management/egress/egress-gateway/#egress-gateway-for-http-traffic) and the API reference for [HTTPMatchRequest](https://istio.io/docs/reference/config/networking/virtual-service/#HTTPMatchRequest).

**Comment by esnible** [comment]
I added `kind/docs` because this Issue involves them.  @frankbu Is there any effort to align the match types or provided guidance for the traffic routing discussed in this issue?

**Comment by frankbu** [comment]
IIRC we wanted to deprecate the sourceLabels and gateways fields and subsequently realized it was a mistake. We put back the doc for sourceLabels, but it looks like we forgot to do the same for the gateways field.

Other than fixing that, what other common fields look like they're missing across the match types? Btw, an issue with the API should really be opened against the istio/api repo.
