### ISSUE TITLE
No mTLS on TCP Traffic

### ISSUE THREAD

**Issue by DaveBben** [istio/istio#17110]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
When the team and I deploy services using Istio, traffic that communicates using HTTP is secured by mutual TLS as viewed by Kiali. However, any service that has a tcp prefix, or TCP protocol is not secured by mTLS (according to the Kiali graph). 

Does Istio not support mTLS on plain TCP traffic? Or could this be due to the fact that our services have their own TLS certificates used to communicate with each other so Istio is not bothering with securing the traffic?

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[X ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X ] Policies and Telemetry
[X ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
All traffic is secured using mTLS

**Steps to reproduce the bug**
Deploy a service with TCP protocol, view the connection in Kiali. The mTLS badge is not present. However, mTLS badge is present with services that communicate over HTTP.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by DaveBben** [comment]
![tcp vs http](https://user-images.githubusercontent.com/12903207/64982688-ca25b280-d88c-11e9-8657-e315d2767961.PNG)

A better example explaining the situation. Should the TCP traffic also have mTLS?

**Comment by douglas-reid** [comment]
mTLS is supported for TCP.

Perhaps this is just a kiali issue?

@jmazzitelli any thoughts?

**Comment by jshaughn** [comment]
@DaveBben , @douglas-reid I did a quick investigation and this looks like a Kiali issue.  I'll move this to a new Kiali issue.

**Comment by jshaughn** [comment]
@DaveBben, The change for Kiali is in and should soon be available with the latest tag.  To ensure that there isn't also an issue in Istio, can you confirm that your TCP time-series in Prometheus (the istio_tcp_sent_bytes_total metric) have the connection_security_policy value set correctly (as "mutual_tls").  Thanks, -Jay

**Comment by DaveBben** [comment]
@jshaughn Great! Thanks. It looks like everything is reading fine from Prometheus.

`istio_tcp_sent_bytes_total{connection_security_policy="mutual_tls",destination_app="tcp-echo",destination_principal="cluster.local/ns/with-istio/sa/default",destination_service="unknown",destination_service_name="unknown",destination_service_namespace="unknown",destination_version="v1",destination_workload="tcp-echo-v1",destination_workload_namespace="with-istio",job="istio-mesh",reporter="destination",response_flags="-",source_app="curl",source_principal="cluster.local/ns/with-istio/sa/default",source_version="unknown",source_workload="curl",source_workload_namespace="with-istio"}`

**Comment by jshaughn** [comment]
Perfect.

**Comment by gargnupur** [comment]
Looks like everything is done here and bug can be closed...
