### ISSUE TITLE
Expose HTTP/2 window size settings as Pilot environment variables

### ISSUE THREAD

**Issue by duderino** [istio/istio#17117]
Expose HTTP/2 connection window settings so that Envoy can be tuned to provide backpressure.  Without this slow upstreams can cause Envoy to consume too much buffer memory relaying requests and slow downstreams can similarly cause Envoy to consume too much buffer memory relaying responses.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by duderino** [comment]
@howardjohn fixed this in https://github.com/istio/istio/pull/17058

John could you provide an example for configuring this here and then close out the bug?

**Comment by howardjohn** [comment]
`--set pilot.env.PILOT_INITIAL_CONNECTION_WINDOW_SIZE=65535 --set pilot.env.PILOT_INITIAL_STREAM_WINDOW_SIZE=65535`
