### ISSUE TITLE
include route/path in prometheus requests metrics

### ISSUE THREAD

**Issue by r0fls** [istio/istio#17118]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Include the endpoint i.e. route/path as one of the dimensions of the exported prometheus metrics

**Describe alternatives you've considered**
I have no idea how this could be implemented alternatively, I looked at the existing metrics and didn't see any that would give response codes per endpoint.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**
Here is an example of a metric right now:

```istio_requests_total{cluster="my.k8s.cluster",connection_security_policy="none",destination_app="telemetry",destination_principal="unknown",destination_service="istio-telemetry.istio-system.svc.cluster.local",destination_service_name="istio-telemetry",destination_service_namespace="istio-system",destination_version="unknown",destination_workload="istio-telemetry",destination_workload_namespace="istio-system",instance="100.100.95.248:42422",job="istio-mesh",permissive_response_code="none",permissive_response_policyid="none",prometheus="istio-system/prometheus-istio",reporter="destination",request_protocol="grpc",response_code="200",response_flags="-",source_app="istio-ingressgateway",source_principal="unknown",source_version="unknown",source_workload="istio-ingressgateway",source_workload_namespace="istio-system"}```

As you can see there is no way to see which endpoint the request is too, for example: `/api/v1/users`

**Comment by douglas-reid** [comment]
We've considered this before, but cannot recommend this as the default for metrics installations. Anything exposed to the open internet quickly will be overwhelmed by the explosion in time series as a consequence of including the request path. And we've seen that happen.

But, all is not lost.

It is possible to update the default config to include that label for your own installation (with the caveat that it can cause time series explosions).  You'll need to update the instances for `requestcount`, `requestduration`, `requestbytes`, and `responsebytes` to include a new label (maybe `path`). You'll likely want to use an expression like: `path: request. url_path | "unknown"`. Then, update the prometheus handler config to include the `path` label as well for `request_count`, `request_duration_seconds`, `request_bytes` and `response_bytes`.

I'm going to close this issue for now, given that there is a way to achieve this feature via config and that it isn't something we are considering to add by default across all of istio at the moment.

Please feel free to follow-up with questions, etc.

**Comment by r0fls** [comment]
>You'll need to update the instances for requestcount, requestduration, requestbytes, and responsebytes to include a new label (maybe path

Do you have any idea if this is supported in the helm chart, or if it will require a `kubectl patch` command?

**Comment by douglas-reid** [comment]
This is not supported via helm. You'll either need to generate the yaml using `helm template` and then edit, or use kubectl.

**Comment by JohnWillker** [comment]
> We've considered this before, but cannot recommend this as the default for metrics installations. Anything exposed to the open internet quickly will be overwhelmed by the explosion in time series as a consequence of including the request path. And we've seen that happen.
> 
> But, all is not lost.
> 
> It is possible to update the default config to include that label for your own installation (with the caveat that it can cause time series explosions). You'll need to update the instances for `requestcount`, `requestduration`, `requestbytes`, and `responsebytes` to include a new label (maybe `path`). You'll likely want to use an expression like: `path: request. url_path | "unknown"`. Then, update the prometheus handler config to include the `path` label as well for `request_count`, `request_duration_seconds`, `request_bytes` and `response_bytes`.
> 
> I'm going to close this issue for now, given that there is a way to achieve this feature via config and that it isn't something we are considering to add by default across all of istio at the moment.
> 
> Please feel free to follow-up with questions, etc.

How to do that in Istio 1.6 where mixer is deprecated.

**Comment by bianpengyuan** [comment]
@JohnWillker take a look at https://istio.io/latest/docs/tasks/observability/metrics/customize-metrics/ and https://istio.io/latest/docs/tasks/observability/metrics/classify-metrics/

**Comment by JohnWillker** [comment]
> https://istio.io/latest/docs/tasks/observability/metrics/classify-metrics/

Thanks! 👍

**Comment by exqlnet** [comment]
Is there any way to edit config gracefully ?

**Comment by bianpengyuan** [comment]
We just extract out telemetry v2 filter configuration into installation option and it will ship with 1.7: https://github.com/istio/istio/pull/26351.

I will update istio.io doc accordingly.
