### ISSUE TITLE
Migrate from deprecated regex to safe_regex field in routes

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#17127]
Envoy has deprecated `regex`. I think we need to move to `safe_regex`.

@duderino @yangminzhu @PiotrSikora can you confirm we want to switch over?

**Comment by PiotrSikora** [comment]
I believe that the TOC requested that we introduce new API in Istio, since `safe_regex` doesn't support everything that `regex` does.

**Comment by yangminzhu** [comment]
> I believe that the TOC requested that we introduce new API in Istio, since `safe_regex` doesn't support everything that `regex` does.

If `regex` is deprecated in Envoy, The only option for the customer is to use the `safe_regex` anyway, does it still make sense to introduce new API in Istio? I feel we could just switch to use the `safe_regex` but the proper documentation and notice to ask customers to do the migration if needed. cc @fpesce

**Comment by yangminzhu** [comment]
I think Istio could just follow the Envoy upgrade to switch to use safe_regex without introducing a new user-facing API. We could provide an option somewhere in helm or environment variable to fall back to the regex field so that user could opt-out the switch. But the customers have to update their regex anyway as upstream Envoy is going to deprecate the old regex field anyway.

**Comment by howardjohn** [comment]
> I think Istio could just follow the Envoy upgrade to switch to use safe_regex without introducing a new user-facing API. We could provide an option somewhere in helm or environment variable to fall back to the regex field so that user could opt-out the switch. But the customers have to update their regex anyway as upstream Envoy is going to deprecate the old regex field anyway.

+1, sounds like the best solution

**Comment by dgn** [comment]
> I think Istio could just follow the Envoy upgrade to switch to use safe_regex without introducing a new user-facing API. We could provide an option somewhere in helm or environment variable to fall back to the regex field so that user could opt-out the switch. But the customers have to update their regex anyway as upstream Envoy is going to deprecate the old regex field anyway.

I favor this solution, too. I opened a PR that implements it
