### ISSUE TITLE
Fallback to use istio-config as default root namespace

### ISSUE THREAD

**Issue by yangminzhu** [istio/istio#17125]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Currently Istio ignores the root namespace if it's empty, for example:

https://github.com/istio/istio/blob/c9ba34bf2aa8a9129a7a5c18124d301bd6a1f2c6/pilot/pkg/model/push_context.go#L1109-L1117

https://github.com/istio/istio/blob/c9ba34bf2aa8a9129a7a5c18124d301bd6a1f2c6/pilot/pkg/model/push_context.go#L583-L591

https://github.com/istio/istio/blob/c9ba34bf2aa8a9129a7a5c18124d301bd6a1f2c6/pilot/pkg/model/push_context.go#L948-L956

https://github.com/istio/istio/blob/8d9a4f71621a0b09daa61210de5b0a4968f6704b/pilot/pkg/model/authorization.go#L152-L154

**Describe alternatives you've considered**
Per @liminw's comment in https://github.com/istio/istio/pull/17037#discussion_r324444918, we should fallback to use `istio-config` if the root namespace is empty in Pilot.

@rshriram @howardjohn @hzxuzhonghu @costinm @liminw @smawson @louiscryan 

Please let me know if this looks to you, thank.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by hzxuzhonghu** [comment]
The root_namespace is `istio-system` by default. Unless user set it to "" by edit the configmap directly, it will never be empty.
```
    # The namespace to treat as the administrative root namespace for istio
    # configuration.
{{- if .Values.global.configRootNamespace }}
    rootNamespace: {{ .Values.global.configRootNamespace }}
{{- else }}
    rootNamespace: {{ .Release.Namespace }}
{{- end }}

```

**Comment by pitlv2109** [comment]
@hzxuzhonghu But the `configRootNamespace` is empty/doesn't exist though.

https://github.com/istio/istio/blob/2890416dcde5b518d9fafecaffcf7779d00da3f1/install/kubernetes/helm/istio/values.yaml#L504

**Comment by incfly** [comment]
I did a grep in pilot and pkg dir, istio-config is only referred in the authorization_test.go and my recent install or code browsing does not seme use istio-config specifically? There's no long this special value?
 
I am closing this one.
