### ISSUE TITLE
Change global.imagePullPolicy in the old installer to "Always"

### ISSUE THREAD

**Issue by arefai** [istio/istio#17128]
The [old installer still uses a "IfNotPresent" ](https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/values.yaml#L297)  global.imagePullPolicy, whereas the [new installer uses "Always"](https://github.com/istio/installer/blob/f00a696ba1186e263de929897b4e4abf505538db/global.yaml#L208). "Always" would be preferred in the case of installing Istio because if there is an old existing image, we don't want it to be used in case there is incompatibility with the new files you are using to install. 

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
New Installs of Istio use the most recent image as indicated by global.HUB and global.TAG 

**Steps to reproduce the bug**
Install Istio on a cluster, delete the namespaces (e.g. istio-system) that were installed, then install again after a day or two. You'll see that the images for the installed components are from the first install in the Docker hub links.

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

**Comment by howardjohn** [comment]
> "Always" would be preferred in the case of installing Istio because if there is an old existing image, we don't want it to be used in case there is incompatibility with the new files you are using to install.

Our images are/should be immutable, so I don't see where this is a problem. What scenario were you thinking of?

**Comment by arefai** [comment]
Correct me if I'm wrong, but the default tag value is master-latest-daily, which moves. I found this problem because I had a cluster that was a couple weeks old that I was installing istio on and then deleting the namespace (for an integrated test). My installations started failing last week and I found that the images for Node-Agent (and other components) were from when I first deployed Istio. These old images were causing problems for me because of a de-sync between them and the updated repo I was using to install. This leads me to believe that "Always" should be the correct policy here, since you would want to pull master-latest-daily from the most recent update to it, not IfNotPresent, which seems to use an old image laying somewhere in the cluster. You might want to sync with @myidpt about this, since I updated him with my findings.

**Comment by howardjohn** [comment]
Installing in `master-latest-daily` in production is not a good idea - hopefully this is not the case? At most I think we should make it Always when `master-latest-daily` is used (in dev) but switch to IfNotPresent when set to a pinned version (production). We should not make production installs worse for development by always setting `Always`.
