### ISSUE TITLE
Stackdriver handler apiKey authentication doesn't work

### ISSUE THREAD

**Issue by duanshiqiang** [istio/istio#17135]
**Bug description**

When creating stackdriver telemetry (handler, instance and rules) to send metrics, logs and tracespans to stackdriver from non-GCP K8S cluster, using apiKey as authentication method doens't work.

Logs from mixer container:

```
2019-09-17T03:25:03.614048Z	info	API keys are not supported for gRPC APIs. Remove the WithAPIKey option from your client-creating call.
2019-09-17T03:25:03.614093Z	error	Unable to initialize adapter: snapshot='4', handler='stackdriver.istio-system', adapter='stackdriver', err='adapter instantiation error: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.'.
Please remove the handler or fix the configuration.
```

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Mixer to send metric, logs and tracespan to stackdriver.

**Steps to reproduce the bug**

I followed the instruction from this blog post: [Istio and Stackdriver](https://medium.com/google-cloud/istio-and-stackdriver-59d157282258). Also tried to use example yaml manifest from @bianpengyuan's example repo: [istio-stackdriver](https://github.com/bianpengyuan/istio-stackdriver/blob/master/yaml/all-in-one.yaml) with modification to use apiKey to authenticate.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

istio: 1.3.0
kubernetes: 1.13.10

**How was Istio installed?**

Helm

**Environment where bug was observed (cloud vendor, OS, etc)**

AWS EKS

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by bianpengyuan** [comment]
API keys is only supported by very limited number of Google APIs: https://cloud.google.com/docs/authentication/api-keys. You should instead use service account: https://cloud.google.com/docs/authentication/production#obtaining_and_providing_service_account_credentials_manually. You could mount it as a secret to telemetry deployment.

**Comment by duanshiqiang** [comment]
@bianpengyuan I see, thanks for your reply. Then the blog post from google cloud medium is totally misleading. It give s reader the impression it's supported.

Then why istio stackdriver adapter includes apiKey as one of the config parameter if it's not supported? I hope the istio documentation can mention this to users.

**Comment by duanshiqiang** [comment]
Sorry to ask but to mount the service account json key into the telemetry deployment, any idea how we can archive via the helm installation?

**Comment by bianpengyuan** [comment]
Sorry I forget to copy the helm link here: https://github.com/istio/istio/blob/9e11075759f113c79a33801685d3bcf259b5a79f/install/kubernetes/helm/istio/charts/mixer/templates/deployment.yaml#L211.

Which blog are you referring to?

**Comment by duanshiqiang** [comment]
@bianpengyuan Oh, thanks! I am referring to this blog [Istio and Stackdriver ](https://medium.com/google-cloud/istio-and-stackdriver-59d157282258)

**Comment by bianpengyuan** [comment]
I guess API key used to work and should be supported by Stackdriver API. But the gRPC client library we are using stops supporting API keys. But anyway, service account should be used to achieve this.. I will update the doc to reflect that.

**Comment by duanshiqiang** [comment]
Cool!

**Comment by douglas-reid** [comment]
Should we close this issue now?

**Comment by bianpengyuan** [comment]
@douglas-reid yes, after https://github.com/istio/istio/pull/17284 is merged.
