### ISSUE TITLE
By default, though *mixer.policy.enabled=false* istio deployment is creating pods related to policy

### ISSUE THREAD

**Issue by sriman-biarca** [istio/istio#17138]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
while installing Istio with helm, though the mixer.policy.enabled=false and mixer.telemetry.enabled=true, I'm able to see the deployments/pods related to policy and telemetry. 
To eradicate this, I'm explicitly mentioning the parameters using --set
```
helm install istio.io/istio --name istio --version 1.1.9 --namespace istio-system  \
  --set mixer.policy.enabled=false \
  --set mixer.telemetry.enabled=true 
```
And what If I need to add podAntiAffinity to these deployments?
I see this policy/telemetry are managed by istio-mixer, and all the labels are same for policy and telemetry, I could not able to add podAntiAffinity to both of the deployments.

Any solution for this, to add podAntiAffinity for policy and telemetry deployments.
**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
@mandarjog has said this is intended but I don't understand why. I am interested in this was well - I think we should remove it.

**Comment by douglas-reid** [comment]
It is/was intended for two primary reasons, iirc:
- ease adoption of policy use cases 
- upgrade / update situations. if you were using `istio-policy` and upgraded, it would be harmful if all of a sudden that workload wasn't available.

**Comment by sriman-biarca** [comment]
I want to enable policy and telemetry, as they are managed by istio-mixer, we have same labels defined for both, but we have diff deployment files, my question is can we differentiate both policy and telemetry so that we can add podAntiAffinity for the both deployment files (coz PDB is enabled for both policy and telemetry).

**Comment by mandarjog** [comment]
yes, the podspec use `istio-mixer-type: policy` and `istio-mixer-type: telemetry` labels.
If this is not enough, please reopen the issue.
