### ISSUE TITLE
Unsafe Envoy readiness check can result 503s during scaling up and rolling update

### ISSUE THREAD

**Issue by iandyh** [istio/istio#17130]
**Bug description**
Istio Envoy proxy is ready before finishing fetching all the configurations. This can result 503 when scaling up the ingress/sidecar pods

**Affected product area (please put an X in all that apply)**

[ x ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ x ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
No 503 when scaling up Istio Ingressgateway

**Steps to reproduce the bug**
1. Send large traffic to Istio ingressgateway
2. Scale up the pods of ingressgateway at the same time. e.g. from --replica=2 to --replica=25

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Istio 1.3.0

**How was Istio installed?**
N/A

**Environment where bug was observed (cloud vendor, OS, etc)**
N/A

https://github.com/istio/istio/blob/1.3.0/pilot/cmd/pilot-agent/status/ready/probe.go#L95

This check is never safe especially when the service registry size is large. Ideal check should compare the existing configuration inside Envoy with pilot. Do you have concern over performing such check?

For critical data plane component, the consistency level of configurations should be high.

**Comment by howardjohn** [comment]
Why is the check not safe? all clusters are sent in a single push

**Comment by esnible** [comment]
@howardjohn Although the Issue was closed I observed in March that Envoy could not route traffic correctly for 2ms after config is pushed to it.  https://github.com/istio/istio/issues/11700#issuecomment-469375832

**Comment by howardjohn** [comment]
@esnible for inbound traffic you do not need ClusterLoadAssignment (EDS). For outbound traffic you do, but Envoy is not marked as ready until EDS is recieved. We do not check just CDS push occurred, we also read Envoy's internal "ready" status

**Comment by lambdai** [comment]
Is the 503 happening only at scale up? Is there any other 503 after stabilization?
I dont know which thing is fishy but ingress listeners(and the envoy) should mark it ready only since clusters(including EDS cluster) are ready 
@howardjohn Do we have scaleup test cluster so that i can fetch the log?

**Comment by iandyh** [comment]
@lambdai @howardjohn in 1.2.5, the issue can be steadily reproduced but in 1.3.0 it becomes harder. 

My initial guess is that the listeners/clusters/endpoints are on the way to Envoy while internal marks it as update_success. From previous thread, it looks like this is NOT the case though.

But if it's 503, which means it is missing either the cluster or the endpoints?

**Comment by howardjohn** [comment]
Oh I think that could be because we actually only check Envoy internal "ready" state in 1.3, so your description probably is accurate in 1.2 but 1.3 behaves differently?

**Comment by iandyh** [comment]
@howardjohn Yes. 1.2 definitely has issues. Does this require pilot to have 1.3 as well? 

> Oh I think that could be because we actually only check Envoy internal "ready" state in 1.3

Is this check at Envoy or at pilot-agent?

**Comment by howardjohn** [comment]
It's pilot agent reading envoy /server_info.

**Comment by howardjohn** [comment]
Pilot 1.3 also has improvements where it will determine inbound listeners from the ndke metadata instead of pod information, so we don't have the issue when we send incomplete LDS

**Comment by howardjohn** [comment]
I think this is fixed in 1.3 and https://github.com/istio/istio/pull/17637 will likely improve it even further in 1.4 if not. Thanks!
