### ISSUE TITLE
TLSv1.3 support for client in istio proxy

### ISSUE THREAD

**Issue by jiarongxu1** [istio/istio#17131]
Hi Experts,
I have a requirement to initialize a TLSv1.3 connection to an external server using istio proxy, but I can not find a guide to configure this.

From the gateway configuration, [https://istio.io/docs/reference/config/networking/v1alpha3/gateway/#Server-TLSOptions](url)
There is a minProtocolVersion and maxProtocolVersion for the gateway server part.
But I can not find similar configuration in destinationrule or some other place for client.

Also in envoy [https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/auth/cert.proto](url)

> (auth.TlsParameters.TlsProtocol) Maximum TLS protocol version. By default, it’s TLSv1_3 for servers in non-FIPS builds, and TLSv1_2 for clients and for servers using BoringSSL FIPS.

It should means TLSv1_3 is supported for client and default maximum value for client is TLSv1_2.

Can you please help to indicate how to configure the TLS version for client part, or this function haven't implemented by istio now,  and any plan to do it? Thanks.

Best Regards

**Comment by kunalekawde** [comment]
Yeah had a doubt and couldn't find any pointer as to setting TLSv1_3 for mTLS between istio-proxies also. Seems be the there for gateways. Is it default TLSv1_2 for istio-proxies and cannot be upgraded to TLSv1_3 ?

**Comment by hobbytp** [comment]
@kunalekawde you can use envoyfilter to configure it, but seems there is an issue [here](https://github.com/envoyproxy/envoy/issues/9300#event-2871548300), that would be why tls 1.3 is not used as default.

**Comment by kunalekawde** [comment]
Thanks @hobbytp , so by default its not enabled but can be enabled on need basis.. shall explore that.
