### ISSUE TITLE
Unable to use Kubernetes ingress records in 1.3.0 without additional config

### ISSUE THREAD

**Issue by zachomedia** [istio/istio#17148]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

I updated one of our clusters to 1.3.0 (using Helm). We enabled k8s Ingress resources with the ingress controller.

After upgrading to 1.3.0, however, they all stopped working. Once I added `ingressClass` and `ingressControllerMode` to the Mesh config in the istio configmap, they started working again.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[X] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

According to https://github.com/istio/istio/blob/1.3.0/galley/pkg/config/meshcfg/defaults.go#L26, the default values for `ingressClass` is `istio` and the `istioControllerMode` is `STRICT`.

Therefore, I shouldn't have had to update the mesh config in the `istio` configmap in order to use the Kubernetes Ingress resources - especially since these values cannot be set in the Helm chart today.

**Steps to reproduce the bug**

1. Install Istio with `k8sIngress.enabled` set to `true`
2. Create an Ingress resource with the `kubernetes.io/ingress.class: istio` annotation

Observe that the navigating to that domain returns a 404.

3. Add `ingressClass: istio` and `ingressControllerMode: STRICT` to the `istio` configmap, under `mesh`

Restart galley and observe that (after a minute or two) the ingress will now work.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

```
❯ istioctl version --remote
client version: 1.3.0
control plane version: 1.3.0

❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:15:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

```

**How was Istio installed?**

Helm

**Environment where bug was observed (cloud vendor, OS, etc)**

Azure AKS-Engine cluster

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
@ozevren do we need to add the default overrides linked above to https://github.com/istio/istio/blob/a19791b326977f47f17412211c09c03e2eecae12/galley/pkg/meshconfig/cache.go#L60 as well?

ref #16270

**Comment by ozevren** [comment]
It looks like the defaults that Galley obtained from Pilot has diverged in https://github.com/istio/istio/pull/12120 (first trace of it I could find). Galley has been operating with those defaults for a long time, so it's been its behavior for better or worse. I think introducing it back is the right thing to do.
