### ISSUE TITLE
Integration test for Kiali

### ISSUE THREAD

**Issue by esnible** [istio/istio#17149]
This item is to create an integration test so that we know if there are incompatibilities between the version of Kiali that we ship.

For Istio 1.3 we had "last minute report about kiali not working: no release coordination with kiali except for community testing.   Was classified as P2 so no one picked it up.  No automated testing to cover it.  Solutions 1) be kiali agnostic, 2) incorporate kiali community in Istio community testing."

This is about a 3rd option, an integration test that queries Kiali rest API to verify that it is receiving telemetry from Istio.

**Comment by jmazzitelli** [comment]
We used to have an integration test that @gbaufake wrote a while ago. Not sure if that test somehow went away. But also, as I understand it, one problem wasn't that kiali wasn't starting or replying to requests; rather, it was because `kubectl dashboard kiali` was somehow creating a proxy that only forwarded or allowed http traffic (and because kiali by default was using https server-side, it was rejecting http requests). So that kind of issue we would need to figure out how to test as well.

**Comment by gbaufake** [comment]
@jmazzitelli 
It still there on https://github.com/istio/istio/blob/master/tests/e2e/tests/kiali/kiali_test.go

**Comment by howardjohn** [comment]
The test is pretty basic, it just checks that kiali doesn't crash

**Comment by gbaufake** [comment]
@howardjohn 
Right. 
At the time, it was submitted we introduced a basic test cover the kiali pod creation by helm charts.

**Comment by mtho11** [comment]
CC: @lucasponce

**Comment by lucasponce** [comment]
@esnible @howardjohn I've created an action in Kiali to not miss this one.
Definetely we may want to enrich the integration tests, with the backend API we can check a major set of features.

I don't know if Istio has some support for UI support, but I guess we can rely on Kiali Integration tests for the UI.

One action that probably would help if how we could automate that when there is some problem on this area we can create some notification that we can track and triage.

I mean, if I review https://github.com/istio/istio/commits/master all commits have failures in the CI, and that creates some distraction about "what CI is the important to look at" and probably we missed something.

So I wonder if there is some action we can add, to receive a notification when some of this CIs fails related a Kiali failure to put someone to look into.

Thanks

**Comment by howardjohn** [comment]
@lucasponce notifications of all postsubmit test failures are sent to the google group `istio-oncall`. This produces a lot of emails every day so I doubt many subscribe to this, but I actually look at every failure. This is an area we have been working on a lot -- if you look at PRs youll notice many are actually passing all tests -- a few months ago this literally never happened. In postsubmit we run some more tests though, so some of those are not as stable.

My point is, if there is a Kiali test and it starts failing it will be noticed

**Comment by esnible** [comment]
@jmazzitelli Is there an issue for the problem with `istioctl dashboard kiali`?

The command just does a port-forward to <kiali-pod>:20001, and then opens the browser to that address prefixed with `http:`.  I could see it failing if Kiali is serving HTTPS on 20001.

**Comment by jmazzitelli** [comment]
> then opens the browser to that address prefixed with `http:`

That would be the problem then - it should have been opening it to use `https`.  But I think the helm chart has been changed to now start Kiali unsecured, so I am not sure if there is anything to do now. See the istio 1.3 branch - here you see the helm chart now installs Kiali without https: https://github.com/istio/istio/blob/release-1.3/install/kubernetes/helm/istio/charts/kiali/values.yaml#L61

**Comment by jmazzitelli** [comment]
Kiali has some molecule tests - requires access to a cluster with Istio installed. These exercise the operator but could be used for testing kiali itself. We could share these or reuse them in Istio somehow. See: https://github.com/kiali/kiali/tree/master/operator/molecule

I have not looked at the Istio testing framework to see how we could plug into it. I assume the test framework just starts up an Istio cluster and tests are run against it - so those molecule tests could be run with against the Istio started by this framework.

**Comment by esnible** [comment]
@jmazzitelli I wrote an integration test verifying _istioctl_ can talk to Prometheus earlier this week.  Your tests could be structured similarly.

https://github.com/istio/istio/pull/17528

The Istio test framework is easy to use.  Write a function named `Test...` with `RequiresEnvironment(environment.Kube).`  The Run() method will be invoked only after an Istio cluster has been started.

```
func TestIstioctlMetrics(t *testing.T) {
 	framework.
 		NewTest(t).
 		RequiresEnvironment(environment.Kube).
...
```
