### ISSUE TITLE
Ability to deploy Citadel into own namespace with Helm install

### ISSUE THREAD

**Issue by casparrolfe** [istio/istio#17141]
**Describe the feature request**
This is recommended by the documentation (see: https://istio.io/docs/concepts/security/#deployment-guidelines), but the helm chart only allows deployment into the release namespace.

**Describe alternatives you've considered**
N/A

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by howardjohn** [comment]
Please see https://github.com/istio/installer if you have not already

**Comment by casparrolfe** [comment]
Excellent! Thanks, John. Would you consider this method of installation stable enough for production use?

**Comment by howardjohn** [comment]
The istio/installer is the backer for the operator which is an alpha: https://istio.io/docs/setup/install/operator/

I would encourage you to try it out, but not depend on it for production

**Comment by howardjohn** [comment]
I think you can also setup citadel in its own namespace once https://github.com/istio/istio/pull/17316 lands in 1.2.7 (?) and already in 1.3

**Comment by casparrolfe** [comment]
Grea. Will take a look. Thanks again, @howardjohn
