### ISSUE TITLE
Test Failure: TestCrdsRetryAsynchronouslyStoreClose

### ISSUE THREAD

**Issue by ozevren** [istio/istio#17147]
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/17121/unit-tests_istio/455

--- FAIL: TestCrdsRetryAsynchronouslyStoreClose (0.09s)
    store_test.go:534: got 5, want no more than 4 calls

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gcs/istio-prow/logs/unit-tests_istio_postsubmit/203

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/17615/racetest_istio/1526

**Comment by kyessenov** [comment]
Is this a real failure or a flake? I think Mixer non-galley backend is on life support, so this will fix itself naturally when galley is integrated fully.

**Comment by kyessenov** [comment]
Marking as area/config as that seems to be the right owner to fully deprecate old Mixer's config backend.

**Comment by howardjohn** [comment]
@kyessenov looks like a broken test:
```
	// Close store, which should shut down the background retry.
	// With 10ms retry interval and 30ms before shutdown, at most 4 discovery calls would be made.
	time.Sleep(30 * time.Millisecond)
	s.Stop()
	time.Sleep(30 * time.Millisecond)
	mutex.RLock()
	if callCount > 4 {
		t.Errorf("got %v, want no more than 4 calls", callCount)
	}
	mutex.RUnlock()
```

Very understandable it fails, we are relying on 10ms precision in an environment that may get heavily throttled

**Comment by howardjohn** [comment]
@kyessenov can you take a look at https://github.com/istio/istio/pull/17716

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/17693/unit-tests_istio/3066 still fails sometimes
