### ISSUE TITLE
Kong Ingress controller is unable to route request to Istio virtual services

### ISSUE THREAD

**Issue by ravibagri5** [istio/istio#17164]
We’re running Istio service mesh on Kubernetes and Kong as API gateway and ingress controller for our K8S cluster.
We’ve created virtual services and destination rules for our micro-services and communications between our micro-services are working as expected except Kong is sending traffic directly to Upstream server instead of applying the virtual service and destination rules.

**Scenario**
We have a micro-service deployed with 3 different versions and we have created virtual service to send traffic to only version v1 and v3. This is working fine when the micro-services communicate internally. But whenever we hit it through kong, the traffic is getting distributed evenly ( like it does without any traffic rule).
Also, kong ingress LB is showing as unknown node and I’m assuming it because the LB is outside the Istio mesh. Is it possible to use Kong instead of istio ingress gateway or am I missing something here?

**Comment by howardjohn** [comment]
So your setup is: outside world -> Kong (with no Istio) -> Service (with sidecar)? Then it makes sense virtual service would not be applied -- they are on client side only and Kong does not have a sidecar. You would either need a sidecar with kong (not sure if feasible), use istio ingessgateway, or use ingressgateway + kong.

**Comment by ravibagri5** [comment]
@howardjohn  Kong is also in istio mesh, i.e running with a sidecar. I thought about putting an ingressgateway in front of kong which would bind to kong virtual service only. But in that case, I won't be able to use Kong as API gateway in true sense as all the traffic would be getting landed on ingressgateway LB first. Also, it would add an extra network hop.
FYI, I'm using kong ingress controller and switching to istio ingress gateway would be difficult since we're using a lot of kong plugins and I'm not sure if ingressgateway would have the configurations to support all the plugin's functionality.

**Comment by howardjohn** [comment]
Interesting, I would look at the config of the Kong sidecar - istioctl pc routes POD -ojson and compare to one that behaves as expected

**Comment by ravibagri5** [comment]
`            {
                "name": "sms-notification-service.hyke-stage.svc.cluster.local:80",
                "domains": [
                    "sms-notification-service.hyke-stage.svc.cluster.local",
                    "sms-notification-service.hyke-stage.svc.cluster.local:80",
                    "sms-notification-service.hyke-stage",
                    "sms-notification-service.hyke-stage:80",
                    "sms-notification-service.hyke-stage.svc.cluster",
                    "sms-notification-service.hyke-stage.svc.cluster:80",
                    "sms-notification-service.hyke-stage.svc",
                    "sms-notification-service.hyke-stage.svc:80",
                    "172.20.148.68",
                    "172.20.148.68:80"
                ],
                "routes": [
                    {
                        "match": {
                            "prefix": "/"
                        },
                        "route": {
                            "cluster": "outbound|80|v1|sms-notification-service.hyke-stage.svc.cluster.local",
                            "timeout": "0s",
                            "retryPolicy": {
                                "retryOn": "connect-failure,refused-stream,unavailable,cancelled,resource-exhausted,retriable-status-codes",
                                "numRetries": 2,
                                "retryHostPredicate": [
                                    {
                                        "name": "envoy.retry_host_predicates.previous_hosts"
                                    }
                                ],
                                "hostSelectionRetryMaxAttempts": "5",
                                "retriableStatusCodes": [
                                    503
                                ]
                            },
                            "maxGrpcTimeout": "0s"
                        },
                        "metadata": {
                            "filterMetadata": {
                                "istio": {
                                    "config": "/apis/networking/v1alpha3/namespaces/hyke-stage/virtual-service/sms-notification-service"
                                }
                            }
                        },
                        "decorator": {
                            "operation": "sms-notification-service.hyke-stage.svc.cluster.local:80/*"
                        },
                        "perFilterConfig": {
                            "mixer": {
                                "disable_check_calls": true,
                                "forward_attributes": {
                                    "attributes": {
                                        "destination.service.host": {
                                            "string_value": "sms-notification-service.hyke-stage.svc.cluster.local"
                                        },
                                        "destination.service.name": {
                                            "string_value": "sms-notification-service"
                                        },
                                        "destination.service.namespace": {
                                            "string_value": "hyke-stage"
                                        },
                                        "destination.service.uid": {
                                            "string_value": "istio://hyke-stage/services/sms-notification-service"
                                        }
                                    }
                                },
                                "mixer_attributes": {
                                    "attributes": {
                                        "destination.service.host": {
                                            "string_value": "sms-notification-service.hyke-stage.svc.cluster.local"
                                        },
                                        "destination.service.name": {
                                            "string_value": "sms-notification-service"
                                        },
                                        "destination.service.namespace": {
                                            "string_value": "hyke-stage"
                                        },
                                        "destination.service.uid": {
                                            "string_value": "istio://hyke-stage/services/sms-notification-service"
                                        }
                                    }
                                }
                            }
                        }
                    }
                ]
            },
`
Here's a snnipet of a service which is showing unexpected behaviour.

**Comment by howardjohn** [comment]
Everything there looks fine.. can you compare to one of the microservices and see if the output is different?

From Istio's point of view requests from kong should be treated the same as from other microservices, since Istio doesn't know Kong is the ingress

**Comment by ravibagri5** [comment]
I apologize for not getting back in time.  There are multiple rules for kong and below routes look suspicious.
`{
        "name": "inbound|80|http-kong-proxy|istio-kong-kong-proxy.istio-kong.svc.cluster.local",
        "virtualHosts": [
            {
                "name": "inbound|http|80",
                "domains": [
                    "*"
                ],
                "routes": [
                    {
                        "match": {
                            "prefix": "/"
                        },
                        "route": {
                            "cluster": "inbound|80|http-kong-proxy|istio-kong-kong-proxy.istio-kong.svc.cluster.local",
                            "timeout": "0s",
                            "maxGrpcTimeout": "0s"
                        },
                        "decorator": {
                            "operation": "istio-kong-kong-proxy.istio-kong.svc.cluster.local:80/*"
                        },
                        "perFilterConfig": {
                            "mixer": {
                                "disable_check_calls": true,
                                "mixer_attributes": {
                                    "attributes": {
                                        "destination.service.host": {
                                            "string_value": "istio-kong-kong-proxy.istio-kong.svc.cluster.local"
                                        },
                                        "destination.service.name": {
                                            "string_value": "istio-kong-kong-proxy"
                                        },
                                        "destination.service.namespace": {
                                            "string_value": "istio-kong"
                                        },
                                        "destination.service.uid": {
                                            "string_value": "istio://istio-kong/services/istio-kong-kong-proxy"
                                        }
                                    }
                                }
                            }
                        }
                    }
                ]
            }
        ],
        "validateClusters": false
    },
    {
        "name": "inbound|80|http-kong-proxy|istio-kong-kong-proxy.istio-kong.svc.cluster.local",
        "virtualHosts": [
            {
                "name": "inbound|http|80",
                "domains": [
                    "*"
                ],
                "routes": [
                    {
                        "match": {
                            "prefix": "/"
                        },
                        "route": {
                            "cluster": "inbound|80|http-kong-proxy|istio-kong-kong-proxy.istio-kong.svc.cluster.local",
                            "timeout": "0s",
                            "maxGrpcTimeout": "0s"
                        },
                        "decorator": {
                            "operation": "istio-kong-kong-proxy.istio-kong.svc.cluster.local:80/*"
                        },
                        "perFilterConfig": {
                            "mixer": {
                                "disable_check_calls": true,
                                "mixer_attributes": {
                                    "attributes": {
                                        "destination.service.host": {
                                            "string_value": "istio-kong-kong-proxy.istio-kong.svc.cluster.local"
                                        },
                                        "destination.service.name": {
                                            "string_value": "istio-kong-kong-proxy"
                                        },
                                        "destination.service.namespace": {
                                            "string_value": "istio-kong"
                                        },
                                        "destination.service.uid": {
                                            "string_value": "istio://istio-kong/services/istio-kong-kong-proxy"
                                        }
                                    }
                                }
                            }
                        }
                    }
                ]
            }
        ],
        "validateClusters": false
    },
`
Can you plesae verify this is right?

**Comment by howardjohn** [comment]
That does look weird that it is duplicated.. but that is the inbound only what matters is the outbound config for the kong sidecar. Can you just attach a full config dump if possible of the kong sidecar? https://github.com/istio/istio/wiki/Troubleshooting-Istio#collecting-information-2
