### ISSUE TITLE
Internal error occurred: failed calling admission webhook "pilot.validation.istio.io"

### ISSUE THREAD

**Issue by xiaozhongliu** [istio/istio#17162]
**Bug description**
Cannot apply some configs after upgrading istio from 1.1.8 to 1.2.5 with the following error:
*Error from server (InternalError): error when creating "src/script/istio-config/isolated-gateway.yml": Internal error occurred: failed calling admission webhook "pilot.validation.istio.io": Post https://istio-galley.istio-system.svc:443/admitpilot?timeout=30s: dial tcp 172.22.0.246:443: connect: connection refused*

I checked the galley pod and find it's not listening on 443:
```
~ k exec -it istio-galley-5b87c47669-hfgwn sh
# netstat -nltp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:9876          0.0.0.0:*               LISTEN      1/galley
tcp6       0      0 :::15014                :::*                    LISTEN      1/galley
tcp6       0      0 :::9901                 :::*                    LISTEN      1/galley
```

**Affected product area (please put an X in all that apply)**

[X] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[X] Test and Release
[ ] User Experience
[X] Developer Infrastructure

**Expected behavior**
Can apply all kinds of configs normally.

**Steps to reproduce the bug**
It's hard to provide.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```
~ istioctl version --remote
client version: 1.2.5
grafana version:
grafana version:
citadel version: 1.2.5
galley version: 1.2.5
ingressgateway version: 1.2.5
pilot version: 1.2.5
pilot-gateway version:
policy version: 1.2.5
policy-gateway version:
sidecar-injector version: 1.2.5
telemetry version: 1.2.5
telemetry-gateway version:
kiali version:
prometheus version:
```
```
~ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T19:44:19Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-aliyun.1", GitCommit:"8cb561c", GitTreeState:"", BuildDate:"2019-05-23T11:28:17Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
Aliyun ACK, Operator

**Environment where bug was observed (cloud vendor, OS, etc)**
Aliyun ACK, CentOS 7

**Comment by howardjohn** [comment]
Interesting, can you provide some more info like `kubectl logs galley`, `kubectl get pod galley -oyaml`

**Comment by xiaozhongliu** [comment]
Galley logs with "err" keyword, comparison between problem one (up) and normal one (down):
![image](https://user-images.githubusercontent.com/17674404/65104584-8fdf2100-da04-11e9-824c-290a48d017ca.png)

And the yaml:
```yaml
~ k get po/istio-galley-5b87c47669-hfgwn -oyaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
    sidecar.istio.io/inject: "false"
  creationTimestamp: "2019-09-16T11:11:28Z"
  generateName: istio-galley-5b87c47669-
  labels:
    app: istio-galley
    istio: galley
    pod-template-hash: 5b87c47669
  name: istio-galley-5b87c47669-hfgwn
  namespace: istio-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: istio-galley-5b87c47669
    uid: 8c1aa0f3-d85c-11e9-9eeb-86acd481b704
  resourceVersion: "1074702418"
  selfLink: /api/v1/namespaces/istio-system/pods/istio-galley-5b87c47669-hfgwn
  uid: bab28e34-d872-11e9-9eeb-86acd481b704
spec:
  containers:
  - args:
    - server
    - --meshConfigFile=/etc/mesh-config/mesh
    - --livenessProbeInterval=1s
    - --livenessProbePath=/healthliveness
    - --readinessProbePath=/healthready
    - --readinessProbeInterval=1s
    - --deployment-namespace=istio-system
    - --validation-webhook-config-file
    - /etc/config/validatingwebhookconfiguration.yaml
    - --monitoringPort=15014
    - --log_output_level=default:info
    - --insecure=true
    - --enable-validation=false
    command:
    - /usr/local/bin/galley
    image: registry.cn-hangzhou.aliyuncs.com/aliacs-app-catalog/galley:1.2.5
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
        - /usr/local/bin/galley
        - probe
        - --probe-path=/healthliveness
        - --interval=10s
      failureThreshold: 3
      initialDelaySeconds: 5
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 1
    name: galley
    ports:
    - containerPort: 443
      protocol: TCP
    - containerPort: 15014
      protocol: TCP
    - containerPort: 9901
      protocol: TCP
    readinessProbe:
      exec:
        command:
        - /usr/local/bin/galley
        - probe
        - --probe-path=/healthready
        - --interval=10s
      failureThreshold: 3
      initialDelaySeconds: 5
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        cpu: "2"
        memory: 2G
      requests:
        cpu: 200m
        memory: 256Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/certs
      name: certs
      readOnly: true
    - mountPath: /etc/config
      name: config
      readOnly: true
    - mountPath: /etc/mesh-config
      name: mesh-config
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: istio-galley-service-account-token-s7dn7
      readOnly: true
  dnsPolicy: ClusterFirst
  nodeName: cn-hangzhou.i-bp141wsgzhh1go605fwv
  nodeSelector:
    beta.kubernetes.io/os: linux
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: istio-galley-service-account
  serviceAccountName: istio-galley-service-account
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: certs
    secret:
      defaultMode: 420
      secretName: istio.istio-galley-service-account
  - configMap:
      defaultMode: 420
      name: istio-galley-configuration
    name: config
  - configMap:
      defaultMode: 420
      name: istio
    name: mesh-config
  - name: istio-galley-service-account-token-s7dn7
    secret:
      defaultMode: 420
      secretName: istio-galley-service-account-token-s7dn7
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2019-09-16T11:11:28Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2019-09-16T11:11:35Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2019-09-16T11:11:35Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2019-09-16T11:11:28Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://d56b7ef3e59b40a58c0adc28a479d18912a86067bd87c0e467bf0422c2311df8
    image: registry.cn-hangzhou.aliyuncs.com/aliacs-app-catalog/galley:1.2.5
    imageID: docker-pullable://registry.cn-hangzhou.aliyuncs.com/aliacs-app-catalog/galley@sha256:fd0546ef908e3ddf2ba1c26353ba8c3dbb9b8e99876af020c11c4f7031e493cb
    lastState: {}
    name: galley
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: "2019-09-16T11:11:30Z"
  hostIP: 172.16.151.36
  phase: Running
  podIP: 172.22.0.246
  qosClass: Burstable
  startTime: "2019-09-16T11:11:28Z"
```

**Comment by howardjohn** [comment]
`    - --enable-validation=false` seems the culrpit

**Comment by osswangxining** [comment]
Yes, this is migrated from previous version which enabled the validation, but currently the configuration does not enable it while the ValidatingWebhookConfiguration resource is not removed together.

Resolution:
option 1: set --enable-validation=true
option 2: remove ValidatingWebhookConfiguration istio-galley by using kubectl

**Comment by howardjohn** [comment]
This is working as intended and a fix is given above. Thanks!

**Comment by vhosakot** [comment]
Saw the same error when installing istio `1.3.6`:

```
Error: release istio failed: Internal error occurred: failed calling webhook "pilot.validation.istio.io": Post https://istio-galley.istio-system.svc:443/admitpilot?timeout=30s: dial tcp 10.107.180.45:443: connect: connection refused
```

Galley and pilot logs had the following errors: 

```
$ kubectl logs istio-galley-66f5bcd4f9-ds2w9 -n=istio-system
...
2019-12-16T22:21:39.963581Z	info	validation	https handler for validation webhook is not ready: HTTP request to https://localhost:443/ready failed: Get https://localhost:443/ready: dial tcp 127.0.0.1:443: connect: connection refused
2019-12-16T22:21:40.052199Z	warn	validation	istio-system/istio-galley endpoint not ready: no subsets
2019-12-16T22:21:40.600664Z	warn	validation	istio-system/istio-galley endpoint not ready: no ready addresses
...

$ kubectl logs istio-pilot-6c94f7f575-69wbf -n=istio-system --all-containers=true
...
2019-12-16T22:21:49.974537Z	info	grpc: addrConn.createTransport failed to connect to {istio-galley.istio-system.svc:9901 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 10.107.180.45:9901: connect: no route to host". Reconnecting...
2019-12-16T22:21:49.974779Z	info	pickfirstBalancer: HandleSubConnStateChange: 0xc00063f670, TRANSIENT_FAILURE
2019-12-16T22:21:49.974936Z	error	mcp	Failed to create a new MCP sink stream: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 10.107.180.45:9901: connect: no route to host"
...
```

Using `--set global.configValidation=false` when installing istio resolved the error for me.

**Comment by kahramanakyil** [comment]
Still getting this error when installed istio on local on-premise kubernetes cluster on Ubuntu 16.04.6.
Error from server (InternalError): error when creating "microservices.yaml": Internal error occurred: failed calling webhook "pilot.validation.istio.io": Post https://istio-galley.istio-system.svc:443/admitpilot?timeout=30s: x509: certificate signed by unknown authority

istioctl version
client version: 1.4.3
control plane version: 1.4.3
data plane version: 1.4.3 (2 proxies)

kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-14T21:04:32Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial


kubectl -n istio-system get pod istio-galley-5c869899f9-6jtd6 -o yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    sidecar.istio.io/inject: "false"
  creationTimestamp: "2020-02-03T15:54:54Z"
  generateName: istio-galley-5c869899f9-
  labels:
    app: galley
    chart: galley
    heritage: Tiller
    istio: galley
    pod-template-hash: 5c869899f9
    release: istio
  name: istio-galley-5c869899f9-6jtd6
  namespace: istio-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: istio-galley-5c869899f9
    uid: e1a4c6f8-3152-4180-9696-1fd734aa47a6
  resourceVersion: "5035998"
  selfLink: /api/v1/namespaces/istio-system/pods/istio-galley-5c869899f9-6jtd6
  uid: 1c124a9a-ed4c-4fd2-a2fb-cd2d43ae6732
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
          - key: beta.kubernetes.io/arch
            operator: In
            values:
            - amd64
        weight: 2
      - preference:
          matchExpressions:
          - key: beta.kubernetes.io/arch
            operator: In
            values:
            - ppc64le
        weight: 2
      - preference:
          matchExpressions:
          - key: beta.kubernetes.io/arch
            operator: In
            values:
            - s390x
        weight: 2
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: beta.kubernetes.io/arch
            operator: In
            values:
            - amd64
            - ppc64le
            - s390x
  containers:
  - command:
    - /usr/local/bin/galley
    - server
    - --meshConfigFile=/etc/mesh-config/mesh
    - --livenessProbeInterval=1s
    - --livenessProbePath=/healthliveness
    - --readinessProbePath=/healthready
    - --readinessProbeInterval=1s
    - --deployment-namespace=istio-system
    - --insecure=true
    - --enable-reconcileWebhookConfiguration=true
    - --validation-webhook-config-file
    - /etc/config/validatingwebhookconfiguration.yaml
    - --monitoringPort=15014
    - --log_output_level=default:info
    image: docker.io/istio/galley:1.4.3
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
        - /usr/local/bin/galley
        - probe
        - --probe-path=/healthliveness
        - --interval=10s
      failureThreshold: 3
      initialDelaySeconds: 5
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 1
    name: galley
    ports:
    - containerPort: 443
      protocol: TCP
    - containerPort: 15014
      protocol: TCP
    - containerPort: 9901
      protocol: TCP
    readinessProbe:
      exec:
        command:
        - /usr/local/bin/galley
        - probe
        - --probe-path=/healthready
        - --interval=10s
      failureThreshold: 3
      initialDelaySeconds: 5
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      requests:
        cpu: 10m
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/certs
      name: certs
      readOnly: true
    - mountPath: /etc/config
      name: config
      readOnly: true
    - mountPath: /etc/mesh-config
      name: mesh-config
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: istio-galley-service-account-token-k8trn
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: worker-node01
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: istio-galley-service-account
  serviceAccountName: istio-galley-service-account
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: certs
    secret:
      defaultMode: 420
      secretName: istio.istio-galley-service-account
  - configMap:
      defaultMode: 420
      name: istio-galley-configuration
    name: config
  - configMap:
      defaultMode: 420
      name: istio
    name: mesh-config
  - name: istio-galley-service-account-token-k8trn
    secret:
      defaultMode: 420
      secretName: istio-galley-service-account-token-k8trn
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-02-03T15:54:59Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-02-03T15:55:25Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-02-03T15:55:25Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-02-03T15:54:54Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://0773b2a1fcf6062ef37e8ab4e1c2ad6ff7e7c29008fdc12e30882eaa91a0217f
    image: istio/galley:1.4.3
    imageID: docker-pullable://istio/galley@sha256:cd808046179ead05a46327b1d7e33c42e5427808d394459cf49b33903b5dce74
    lastState: {}
    name: galley
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-02-03T15:55:16Z"
  hostIP: 100.126.251.154
  phase: Running
  podIP: 10.244.1.131
  podIPs:
  - ip: 10.244.1.131
  qosClass: Burstable
  startTime: "2020-02-03T15:54:59Z"
  
  
kubectl get clusterrole istio-galley-istio-system -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"labels":{"app":"galley","chart":"galley","heritage":"Tiller","release":"istio"},"name":"istio-galley-istio-system"},"rules":[{"apiGroups":["authentication.istio.io","config.istio.io","networking.istio.io","rbac.istio.io","security.istio.io"],"resources":["*"],"verbs":["get","list","watch"]},{"apiGroups":["authentication.istio.io","config.istio.io","networking.istio.io","rbac.istio.io","security.istio.io"],"resources":["*/status"],"verbs":["update"]},{"apiGroups":["admissionregistration.k8s.io"],"resources":["validatingwebhookconfigurations"],"verbs":["*"]},{"apiGroups":["extensions","apps"],"resourceNames":["istio-galley"],"resources":["deployments"],"verbs":["get"]},{"apiGroups":[""],"resources":["pods","nodes","services","endpoints","namespaces"],"verbs":["get","list","watch"]},{"apiGroups":["extensions"],"resources":["ingresses"],"verbs":["get","list","watch"]},{"apiGroups":["extensions"],"resourceNames":["istio-galley"],"resources":["deployments/finalizers"],"verbs":["update"]},{"apiGroups":["apiextensions.k8s.io"],"resources":["customresourcedefinitions"],"verbs":["get","list","watch"]}]}
  creationTimestamp: "2020-02-03T15:54:51Z"
  labels:
    app: galley
    chart: galley
    heritage: Tiller
    release: istio
  name: istio-galley-istio-system
  resourceVersion: "5035442"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/istio-galley-istio-system
  uid: 636ab440-045d-48b1-9f7d-a8020e28fcd9
rules:
- apiGroups:
  - authentication.istio.io
  - config.istio.io
  - networking.istio.io
  - rbac.istio.io
  - security.istio.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authentication.istio.io
  - config.istio.io
  - networking.istio.io
  - rbac.istio.io
  - security.istio.io
  resources:
  - '*/status'
  verbs:
  - update
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - '*'
- apiGroups:
  - extensions
  - apps
  resourceNames:
  - istio-galley
  resources:
  - deployments
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  - services
  - endpoints
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resourceNames:
  - istio-galley
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch

kubectl get mutatingwebhookconfiguration istio-sidecar-injector -o yaml
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"admissionregistration.k8s.io/v1beta1","kind":"MutatingWebhookConfiguration","metadata":{"annotations":{},"labels":{"app":"sidecarInjectorWebhook","chart":"sidecarInjectorWebhook","heritage":"Tiller","release":"istio"},"name":"istio-sidecar-injector"},"webhooks":[{"clientConfig":{"caBundle":"","service":{"name":"istio-sidecar-injector","namespace":"istio-system","path":"/inject"}},"failurePolicy":"Fail","name":"sidecar-injector.istio.io","namespaceSelector":{"matchLabels":{"istio-injection":"enabled"}},"rules":[{"apiGroups":[""],"apiVersions":["v1"],"operations":["CREATE"],"resources":["pods"]}]}]}
  creationTimestamp: "2020-02-03T15:54:55Z"
  generation: 2
  labels:
    app: sidecarInjectorWebhook
    chart: sidecarInjectorWebhook
    heritage: Tiller
    release: istio
  name: istio-sidecar-injector
  resourceVersion: "5035845"
  selfLink: /apis/admissionregistration.k8s.io/v1/mutatingwebhookconfigurations/istio-sidecar-injector
  uid: 88b4abba-5655-4188-b464-a604cf7e0f63
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMzakNDQWNhZ0F3SUJBZ0lSQUxaTExjM1dvSzVLZUJ2SVVtbmhYYzB3RFFZSktvWklodmNOQVFFTEJRQXcKR0RFV01CUUdBMVVFQ2hNTlkyeDFjM1JsY2k1c2IyTmhiREFlRncweU1EQXlNRE14TlRVMU1ETmFGdzB6TURBeApNekV4TlRVMU1ETmFNQmd4RmpBVUJnTlZCQW9URFdOc2RYTjBaWEl1Ykc5allXd3dnZ0VpTUEwR0NTcUdTSWIzCkRRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRFh3dDRPNW5FS21Td2w0c0hDeVN4UE04bTR5ZHF2K20yOUFQRHQKVVRTc1Yyd3lUYWprMGRKV2w3TFhBQ29EenVRdXFXajQ4N0x3V1NBcEh4aFB5VjdyZzRrS2J2Uk9lN1ZZcHdDRAo0dG5FS3VaWWNTcVpmTnhDSFEvemp4U0FxYTdmQ0NlOWNRNVZ0dG93azZudldYaU05OElHV3d5Nnl3S252WXZHCmtkbGpyMVdIQll0L1BoOXo2cGVzVFVLYm9pZU1qaHFEaEFiNFhOL3lqekJPRDBDcFBzWEsxRHU1L3I1cHlYZnYKOEZ2UXlCRVNjTVB2YllTWmU3V2F0ampZTGE3dEV1b0FsUjEwcGI2RVQ3UEwrUHpmcjBEVlZTQVljcWN0djJlNwp1dzZhZzhoaGM4Mlo0SlJEOU5ySGlUZ0EwRVNhWjB1Q0U1TVFYVmJCWm8xMUdLUkJBZ01CQUFHakl6QWhNQTRHCkExVWREd0VCL3dRRUF3SUNCREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUIKQVFBL1Z0Qzk5REZ4WjQzbHhEUEE5Z3hxaWx0OXJ0Sm5VNjRIOG41ZDFOVWlZQzB5N0liSXg3UXh3VDhPK0Z2MgpORVVyOE1vbUhEOGNYS0ZHMSt6Q044WmhEc0xSZ3FxR3J2SCtLQjNqVFlYalQxUFI0cVo4YXBLcGlZdmw3UjlCCmM3bEsvZjZCWUpMVjZ5ZDN5YjVZTnhjKzhoZnVyVnpCRlFzQVNnZFRTYVBUR0NqM0J6Z3RLSWZQL3NkRmJaWncKekVuc1dhWmZnRnovazRrcmJENDlyQlVrRStJbXBxNm9XRVNmbVpTbEcwUFV5VE9jN1MxaEhPSExPMGZBRVdUaAp6dnN5NGEwQVgrUGFMVXZEblZkTVRRUFBoUVE3ZzZUVzhYMXhuSUVBNmVIWmx5K2x2TnhrWi9RUlEySklBVndXCnlvcVpaWHdUM2J3R2NzZUJ6YzlxOXp2bgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: istio-sidecar-injector
      namespace: istio-system
      path: /inject
      port: 443
  failurePolicy: Fail
  matchPolicy: Exact
  name: sidecar-injector.istio.io
  namespaceSelector:
    matchLabels:
      istio-injection: enabled
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
    scope: '*'
  sideEffects: Unknown
  timeoutSeconds: 30

**Comment by shouldnotappearcalm** [comment]
I'm using Istio `1.5.0` and still experience this issue.I replaced `flannel` with `calico` to restart the cluster to solve this problem

**Comment by feliperfmarques** [comment]
For webhook works, firewall rule needs setting to port 15017 instead of 9443 on Istio 1.5, as mentioned here #19532 (comment).

**Comment by ashrafxcoder** [comment]
I've upgraded from 1.0.6 up until 1.3.8 (no skip upgrades) without any issues but when I upgrade to 1.4.8 this is happening consistently.
I using helm/tiller (v2.11.0)

![ConEmu64_iOFiNDWSWh](https://user-images.githubusercontent.com/14987647/81076582-b4303500-8ee3-11ea-86f4-935d39169bd2.png)

**Comment by Sandeep0045** [comment]
> Yes, this is migrated from previous version which enabled the validation, but currently the configuration does not enable it while the ValidatingWebhookConfiguration resource is not removed together.
> 
> Resolution:
> option 1: set --enable-validation=true
> option 2: remove ValidatingWebhookConfiguration istio-galley by using kubectl

can you give full cmd of option . how to use it
