### ISSUE TITLE
 info: skipping unknown hook: "crd-install"

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#17167]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

 info: skipping unknown hook: "crd-install"

**Comment by 13567436138** [comment]
helm3.0.0.beta3

**Comment by howardjohn** [comment]
This is a known hook: https://github.com/helm/helm/blob/master/docs/charts_hooks.md#the-available-hooks

Seems we don't support helm 3.

We are going to remove all helm specific stuff in the future -- you can still use helm but we won't have any hooks. See https://github.com/istio/installer

**Comment by Ciantic** [comment]
If it's not too difficult to update the old charts to work with helm3, it could be a worthwhile. Especially as the new installer is not usable or documented yet.

Only thing I can think of is to install helm2 in order to install istio with customizations.

**Comment by howardjohn** [comment]
We have no desire to support/depend on any helm features (hooks or otherwise) - only things that work with helm template. We unfortunately still do have some still around but we will be shipping the operator as default very soon

**Comment by thomastaylor312** [comment]
@howardjohn So the main thing that might be helpful for you in Helm 3 is that there is now a `crds` directory you can define in a chart that you can drop all your CRDs into. They will be installed first and the discovery cache cleared so as to not run into any "type not available" problems when validating custom resource instantiations. Completely willing to help if you have any questions or run into any bugs

**Comment by howardjohn** [comment]
@thomastaylor312 sounds like a great improvement for helm. The problem is we need to support `helm template`, which won't work with that. But I think we could also probably have a template that just `include`s those files or something.

Another approach we are doing is having a two step install, `kubectl apply -k github.com/istio/installer/kustomize/cluster` which sets up cluster wide stuff like namespace, CRDs, clusterroles, etc, then the normal install for the rest.

**Comment by thomastaylor312** [comment]
The two step process is probably a good approach 👌. Especially for those in enterprise environments where a user might not have cluster-wide access. If you do run into any Helm things as you update things, just let us know!

**Comment by dminca** [comment]
Issue still occurring in Helm v3.0 stable. Just tried to install prometheus operator

```sh
+ NS=monitoring
+ CHART=stable/prometheus-operator
+ NAME=prometheus-operator
+ VALUES_FILE=values-prometheus-operator.yml
+ CHART_VERSION=8.2.2
+ helm upgrade --install --version 8.2.2 --namespace monitoring --wait --force -f values-prometheus-operator.yml prometheus-operator stable/prometheus-operator
Release "prometheus-operator" does not exist. Installing it now.
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"

```

**Comment by Ciantic** [comment]
@dminca it means the charts are not updated to Helm 3, and you should install Helm 2 if you wish to use those charts that depend on that hook.
