### ISSUE TITLE
Grafana dashboard should display proxy version

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#17173]
Highly related to https://github.com/istio/istio/issues/17172

Right now the dashboard shows control plane versions, but we don't expose data plane versions. This would be very useful

**Comment by douglas-reid** [comment]
This is definitely something we want to do. There was another issue open asking for it to be exposed as an `istio_build` metric -- to match the control plane. The issue was finding the right spot to put it. I think the v2 architecture may help here, too.

**Comment by howardjohn** [comment]
Any ideas how we can get this? I don't think pilot-agent exposes any metrics right now so its a bit heavy weight to do it there, and it won't work for native-envoy cases. Can you add a stat to envoy stats with the mixerv2 stuff?

**Comment by douglas-reid** [comment]
the extensibility v2 stuff is certainly a promising path forward. and one that works for even the bring-your-own-Envoy cases.

**Comment by ramaraochavali** [comment]
@howardjohn @douglas-reid I have been thinking about similar thing for our use case and I have created this issue https://github.com/envoyproxy/envoy/issues/8318 in Envoy? Does it help this use case?

**Comment by howardjohn** [comment]
@ramaraochavali see https://github.com/istio/proxy/pull/2431 if you haven't yet

**Comment by ramaraochavali** [comment]
@howardjohn Thanks. Will take a look.

**Comment by howardjohn** [comment]
Need https://github.com/istio/istio/pull/17828 then just a PR to the dashboard

**Comment by howardjohn** [comment]
Its there now
