### ISSUE TITLE
Flaky test: TestStreamSecretsForGatewaySds

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#17175]
This blocked a daily build of master: https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio-releases_pipeline/1219/unit-tests_pipeline/8

**Comment by JimmyCYJ** [comment]
@pitlv2109 since you add this test recently, could you please take a look?

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16800/unit-tests_istio/859 is another example

**Comment by JimmyCYJ** [comment]
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/17550/unit-tests_istio/1503

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18989/unit-tests_istio/4111

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gcs/istio-prow/logs/unit-tests_istio_postsubmit/1176

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gs/istio-prow/logs/unit-tests_istio_postsubmit/3413

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/26779/unit-tests_istio/19406

**Comment by williamaronli** [comment]
it seems the same the connection are not cleaned:

`expect "total_stale_connections" to be 0, got 1.000000`
deeping dive into the real root cause

**Comment by williamaronli** [comment]
Just wondering why the unit test testing both GatewaySDS and WorkloadSDS not flaky
https://github.com/istio/istio/blob/07782fd8d2ff0225af494b172dc459e5c9ace04a/security/pkg/nodeagent/sds/sdsservice_test.go#L113

but the unit test that only testing the GatewaySDS works https://github.com/istio/istio/blob/07782fd8d2ff0225af494b172dc459e5c9ace04a/security/pkg/nodeagent/sds/sdsservice_test.go#L102

**Comment by williamaronli** [comment]
I run this flaky test TestStreamSecretsForGatewaySds for about 100 times in my own linux. but it doesn't fail any time

**Comment by williamaronli** [comment]
The root cause is that before each test the staledClientKeys and totalStaleConnCounts should be reset
