### ISSUE TITLE
Enable proxy trace easily for a given deployment

### ISSUE THREAD

**Issue by linsun** [istio/istio#17186]
**Describe the feature request**

We sometimes need to enable trace just for a deployment, for example, when debugging https://github.com/istio/istio/issues/17181 there is a need to enable trace for istio-ingress gateway to see if envoy complains, after checking the proxy-config on istio-ingress gateway pod is valid.

Chatting with @GregHanson - Currently workaround is to ssh into the pod and run `curl -XPOST localhost:15000/logging?level=trace`.  Would be great to have a better way that is easier, such as `istioctl pod XXX --log_output_level trace` or `istioctl deployment XXX --log_output_level trace`

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ x] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by liamawhite** [comment]
Resolved by #17339.
