### ISSUE TITLE
Ship stats filter and metadata exchange filter WASM files with istio-proxy

### ISSUE THREAD

**Issue by bianpengyuan** [istio/istio#17188]
Minimum steps to ship the WASM files with proxy:
- [ ] Add an integration test in istio/proxy for the WASM based filters. 
- [ ] Build and push the WASM files to the same GCS bucket as proxy artifacts.
- [ ] Download the WASM files and add those WASM files in istio/istio. 

cc @jplevyak @PiotrSikora @duderino @mandarjog @kyessenov 

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by mmnelemane** [comment]
Is there any further activity on this bug. Its interesting to me since my integration with istio also requires stats and metadata_exchange filters to be shipped in the image in the *.wasm format. Is there an alternative to this or is this task waiting for someone to pick up and work on ? 

I can try to pick this issue, but I am new to Istio and will need some guidance and help.

**Comment by bianpengyuan** [comment]
It is already done: https://istio.io/latest/docs/reference/config/proxy_extensions/wasm_telemetry/. I am curious though what kind of integration are you doing?

**Comment by mmnelemane** [comment]
@bianpengyuan Thanks. I am working with Istio >= 1.5.4 using envoy (with WASM support) along with cilium-filters. The proxyv2 container image definition (https://github.com/istio/istio/blob/1.5.4/pilot/docker/Dockerfile.proxyv2) uses `stats-filter.wasm` and `metadata-exchange-filter.wasm. I am looking for a simple (if possible automated by build) way of generating and including these files with the proxy image I build.

**Comment by bianpengyuan** [comment]
I don't think there is a way to make it extensible. You can build your own images based on istio proxy image  with additional layer of your own wasm modules.

**Comment by h0tbird** [comment]
Where is the source code for the `stats ` and `metadata_exchange` filters?
How can I build and push them to my proxy artifacts collection?
