### ISSUE TITLE
Adding First meshNetwork entry creates outage

### ISSUE THREAD

**Issue by therealmitchconnors** [istio/istio#17185]
**Bug description**
If you have a working mesh with no named networks in the meshNetworks file, and then add an entry to that same file and redeploy pilot (so that it now loads the named networks), pilot will begin rejecting all xDS requests from the existing sidecars, which have no named network, causing them to become unavailable.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ x ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ x ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Pilot continues serving discovery requests from existing sidecars

**Steps to reproduce the bug**
On any running mesh with no named networks, create a named network and restart pilot.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
reproduced on 1.2.2

**How was Istio installed?**
helm defaults

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

**Comment by esnible** [comment]
@therealmitchconnors Do you have a suggestion for a solution?

- Should the user be required to restart pods when adding the first meshNetwork?
- Should Pilot accept any pod from unnamed network, in case it was created before the first named network?
- Should Pilot "grandfather" pod IDs it has seen before?
