### ISSUE TITLE
Installation of 1.3.0 does not complete with SDS config

### ISSUE THREAD

**Issue by mrangana** [istio/istio#17183]
**Bug description**

Installation of 1.3.0 does not complete with generated SDS config. Ingress, pilot, policy and telemetry pods are stuck at creating status.

# kubectl get pods -n istio-system
NAME                                      READY   STATUS              RESTARTS   AGE
istio-citadel-56c4574585-rblks            1/1     Running             0          5m23s
istio-cleanup-secrets-1.3.0-t4tbh         0/1     Completed           0          5m24s
istio-galley-7ff97f98b5-254jx             1/1     Running             0          5m24s
istio-ingressgateway-6bcf946899-2ll9z     0/1     ContainerCreating   0          5m24s
istio-nodeagent-92c46                     1/1     Running             0          5m24s
istio-pilot-f6fbf97f8-6j4k4               0/2     ContainerCreating   0          5m23s
istio-policy-dcc5b896c-rsr4b              0/2     ContainerCreating   0          5m24s
istio-security-post-install-1.3.0-wmhht   0/1     Completed           0          5m24s
istio-sidecar-injector-68f4668959-xvhxl   1/1     Running             0          5m23s
istio-telemetry-64f78bfd46-d458r          0/2     ContainerCreating   0          5m24s
prometheus-776fdf7479-6d75t               1/1     Running             0          5m23s

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

All the pods in running state

**Steps to reproduce the bug**

Generate SDS config:

helm template install/kubernetes/helm/istio --name istio --namespace istio-system --values install/kubernetes/helm/istio/values-istio-sds-auth.yaml > istio-auth-sds.yaml

Install ISTIO :

 for i in install/kubernetes/helm/istio-init/files/crd*yaml; do kubectl apply -f $i; done
 kubectl apply -f ./istio-auth-sds.yaml

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

# istioctl version --remote
client version: 1.3.0
citadel version: 1.3.0
galley version: 1.3.0
nodeagent version:
sidecar-injector version: 1.3.0

# kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.5", GitCommit:"0e9fcb426b100a2aea5ed5c25b3d8cfbb01a8acf", GitTreeState:"clean", BuildDate:"2019-08-05T09:13:08Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**

Using SDS profile

**Environment where bug was observed (cloud vendor, OS, etc)**

On-prem k8s cluster

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by pitlv2109** [comment]
You need to add some flags to your api server deployment. For more information, please take a look https://istio.io/blog/2019/trustworthy-jwt-sds/

**Comment by pitlv2109** [comment]
I'll close this issue for now. Feel free to re-open it.
