### ISSUE TITLE
Need tests/maintainer for TPROXY

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#17199]
Currently we have a proxytproxy image that we ship. It has been broken many times, failed to get security patches, etc, because we have no maintainer for it.

We either need to have someone dedicate some time to maintaining this, including adding tests, or remove the feature as we cannot adequately support it right now.

**Comment by rlenglet** [comment]
The `proxy_debug` image is not tested either. Both need tests.

**Comment by grinb** [comment]
Hi,
The only diff between Dockerfile.proxyv2 and Dockerfile.proxytproxy is USER 0:1337. The tproxy image is needed to have the tproxy enable. Can you merge the two images ?

**Comment by howardjohn** [comment]
We have removed proxy_debug.

I plan to remove TPROXY in 1.5 unless someone can take ownership here
