### ISSUE TITLE
Operator CLI Installation Support ingressgateway nodeprot

### ISSUE THREAD

**Issue by An0nymous0** [istio/istio#17208]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

Operator CLI Installation Support ingressgateway nodeprot

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[x] Configuration Infrastructure
[x] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
`istioctl x manifest generate --set values.gateways.istio-ingressgateway.type=NodePort` seems to work, is this sufficient or are you asking for something else?
