### ISSUE TITLE
Add mesh operator install command

### ISSUE THREAD

**Issue by ostromart** [istio/istio#17219]
This command would basically kubectl apply the manifest to bootstrap the in-cluster controller. 
There should be a corresponding operator delete command to remove the operator from the cluster (this could have a --delete-istio flag to also remove Istio).

**Comment by howardjohn** [comment]
This is marked as a 1.4 P0, do we have an owner?

**Comment by ostromart** [comment]
Fixed through https://github.com/istio/operator/pull/348.
