### ISSUE TITLE
Python client for Istio

### ISSUE THREAD

**Issue by 1032231418** [istio/istio#17212]
hi:
    Would you consider a python client?

**Comment by nrjpoddar** [comment]
We are currently adding Go client and that is WIP. You can track that here: https://github.com/istio/client-go

I don't know what support Kubernetes community provides for Python client code generation for API machinery but if it's well supported we can consider it.

We will have to work out repository layouts specially around generating Python objects from protos in github.com/istio/api repo and then make progress towards creating client sets/informers on top of that.

**Comment by 1032231418** [comment]
@nrjpoddar 
Kubernetes official does not have support for the istio client interface，Hopefully, add, delete and modify istio's Python interface

**Comment by 1032231418** [comment]
Can you give me an example of a request? I'll try to write my own client.

**Comment by 1032231418** [comment]
Hi:

I've written an operation on gateway here, but when updating, it's incomprehensible to pass in resourceVersion.

```
#coding=utf8
from kubernetes import client
from kubernetes.client.api_client import ApiClient
import json

configuration = client.Configuration()
setattr(configuration, 'verify_ssl', False)
client.Configuration.set_default(configuration)
configuration.host = "https://192.168.90.221:6443"
configuration.verify_ssl = False
configuration.debug = True
configuration.api_key = {"authorization": "Bearer " + ApiToken}
client.Configuration.set_default(configuration)

#gateways list

api_client = ApiClient()
res = api_client.request('GET', 'https://192.168.90.221:6443/apis/networking.istio.io/v1alpha3/gateways')
res_dict = json.loads(res.data)
print('\n')
print(res_dict)


#create gateways

api_client = ApiClient()
body = eval("{'kind': 'Gateway','spec': {'selector': {'istio': 'ingressgateway'}, 'servers': [{'hosts': ['*'], 'port': {'protocol': 'HTTP', 'number': 81, 'name': 'http'}}]}, 'apiVersion': 'networking.istio.io/v1alpha3', 'metadata': {'name': 'dev-api1'}}")
res = api_client.request('POST', 'https://192.168.90.221:6443/apis/networking.istio.io/v1alpha3/namespaces/default/gateways', body=body)
res_dict = json.loads(res.data)
print('\n')
print(res_dict)


#update gateways
#I don't know why I want to pass this value. If I don't, I will report the error.
#resourceVersion: id

api_client = ApiClient()
body = eval("{'kind': 'Gateway','spec': {'selector': {'istio': 'ingressgateway'}, 'servers': [{'hosts': ['*'], 'port': {'protocol': 'HTTP', 'number': 82, 'name': 'http'}}]}, 'apiVersion': 'networking.istio.io/v1alpha3', 'metadata': {'name': 'dev-api1','resourceVersion':'5480619'}}")
res = api_client.request('PUT', 'https://192.168.90.221:6443/apis/networking.istio.io/v1alpha3/namespaces/default/gateways/dev-api1/',body=body)
res_dict = json.loads(res.data)
print('\n')
print(res_dict)


#delete  gateways

api_client = ApiClient()
res = api_client.request('DELETE', 'https://192.168.90.221:6443/apis/networking.istio.io/v1alpha3/namespaces/default/gateways/dev-api1')
res_dict = json.loads(res.data)
print('\n')
print(res_dict)
```

**Comment by 1032231418** [comment]
@howardjohn 
Hi:
Here are a few examples, not elegant, but the basic operation is there.
 https://github.com/1032231418/istio_python_client

**Comment by DrAuYueng** [comment]
> @howardjohn
> Hi:
> Here are a few examples, not elegant, but the basic operation is there.
> https://github.com/1032231418/istio_python_client

you mean this case?
https://github.com/kubernetes-client/python/pull/1122

**Comment by mikeage** [comment]
(I know this is an old thread, but I just found it while looking for the same thing)

Additionally, if one prefers to not write the full HTTP URLs, the python custom object support makes this rather straightforward (see the full docs at https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CustomObjectsApi.md )

```python
import kubernetes
kubernetes.config.load_kube_config()
cust_api = kubernetes.client.CustomObjectsApi()
vs = cust_api.list_namespaced_custom_object("networking.istio.io", "v1beta1", "istio-test", "virtualservices")
```
