### ISSUE TITLE
Merge IstioControlPlane with MeshConfig

### ISSUE THREAD

**Issue by ostromart** [istio/istio#17216]
See https://docs.google.com/document/d/19IKo6DDv0x6DKtollcbFivjqLkQGwts3dFCzIFm2swM/

**Comment by howardjohn** [comment]
https://github.com/istio/api/pull/1101

**Comment by ostromart** [comment]
https://github.com/istio/api/pull/1177 is the latest attempt.

**Comment by howardjohn** [comment]
@ostromart are there more changes here, or this current rev what we are sticking to for now?
