### ISSUE TITLE
Automatically generate the default profile from istio/installer using manifest migrate

### ISSUE THREAD

**Issue by ostromart** [istio/istio#17217]
manifest migrate should be able to migrate the istio/installer default values.yaml into IstioControlPlane.

**Comment by richardwxn** [comment]
Still WIP for this issue, it is necessary to automate this process

**Comment by ostromart** [comment]
Partly fixed in https://github.com/istio/operator/pull/393, just need to integrate it with run_update_charts.sh (or where appropriate).
