### ISSUE TITLE
Add upgrade hook functionality to operator

### ISSUE THREAD

**Issue by ostromart** [istio/istio#17223]
We need a backdoor mechanism for any upgrade related fixups.

**Comment by howardjohn** [comment]
This is marked as a 1.4 P0, do we have an owner?

**Comment by elfinhe** [comment]
Happy to take this one, thanks!

**Comment by howardjohn** [comment]
@elfinhe sorry I thought this is what you were already working on. Feel free to unassign if that's not the case -- I didn't intend to give you more work, just make github match reality.

**Comment by elfinhe** [comment]
resolved by https://github.com/istio/operator/pull/385
