### ISSUE TITLE
Rule doesn't apply when calling external service

### ISSUE THREAD

**Issue by bogdanciuca** [istio/istio#17226]
**Istio 1.2.3 (EKS)**

I'm developing an attribute generating adapter which works perfectly fine with `Rule`s that match ingress and/or mesh traffic, but not so much with egress (even when applied with `match: "true"`).

Not sure if this is a bug, or if `Mixer`'s check API call doesn't occur when a service in the mesh is calling external services.

**Comment by atrifan** [comment]
Can anybody help with this? We are facing the same issue in our team, this will help us alot with the adoption of istio inside our cluster

**Comment by douglas-reid** [comment]
Closing issue for now. Please feel free to reopen.

For questions about policy checking, please use the [forums](discuss.istio.io).
