### ISSUE TITLE
Migrate istio/istio tests to use istioctl manifest apply 

### ISSUE THREAD

**Issue by ostromart** [istio/istio#17221]
All istio/istio tests should be compatible with the istio/installer charts now - therefore it should be possible to replace the istio installation steps in the e2e tests with istioctl manifest apply.

**Comment by howardjohn** [comment]
https://github.com/istio/istio/pull/15440 will be a useful reference

**Comment by howardjohn** [comment]
This is marked as a 1.4 P0, do we have an owner?

**Comment by howardjohn** [comment]
A WIP at https://github.com/istio/istio/pull/17547

**Comment by howardjohn** [comment]
Still working on this as part of https://github.com/istio/istio/pull/18991

**Comment by howardjohn** [comment]
We have all integ tests other than security on istioctl

e2e tests are still on helm

**Comment by howardjohn** [comment]
e2e tests are slated for removal rather than migration, so this is done?
