### ISSUE TITLE
In cluster controller e2e tests

### ISSUE THREAD

**Issue by ostromart** [istio/istio#17220]
Prow tests to install controller into the cluster along with CR, check for health, make some changes to the CR and observe the resulting changes to Istio resources.
Ideally, this test would use the new e2e test framework.

**Comment by howardjohn** [comment]
This is marked as a 1.4 P0, do we have an owner?

**Comment by ostromart** [comment]
@sdake has started on this in https://github.com/istio/operator/pull/379.

**Comment by sdake** [comment]
I am unassigning myself.  I have other current responsibilities.  I have simply enabled very basic e2e tests and added check jobs for them.  I am available to consult on more advanced use cases.

**Comment by howardjohn** [comment]
We have this running now
