### ISSUE TITLE
Add --prune back to manifest apply kubectl command

### ISSUE THREAD

**Issue by ostromart** [istio/istio#17236]
Currently this is removed because the manifest is applied in parallel per component, and --prune requires an aggregate of all resources for the entire manifest of all the components together. 
One possible solution is to continue to do the apply normally, in parallel as we do right now, but follow it with a cleanup step that does a kubectl apply on the whole concatenated manifest at the end with --prune. 
This will cause apply to take longer but not prohibitively so because the prior apply would be the one doing most of the work.

**Comment by howardjohn** [comment]
This is marked as a 1.4 P0, do we have an owner?

**Comment by elfinhe** [comment]
This is P0 for 'istioctl x upgrade', I will talk with @ostromart to find a way out.
