### ISSUE TITLE
Disable circuit breaking by default

### ISSUE THREAD

**Issue by PiotrSikora** [istio/istio#17233]
**Bug description**

Circuit breaking (which defaults to a low value of 1024 requests) has been nothing but a source of issues in Istio. We should completely disable it by default, and allow users to configure limits appropriate for their deployment when wanted/needed.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Traffic doesn't break for no reason.

**Steps to reproduce the bug**

Send more than 1024 requests.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

All.

**How was Istio installed?**

N/A

**Environment where bug was observed (cloud vendor, OS, etc)**

All.

cc @duderino @jplevyak

**Comment by PiotrSikora** [comment]
Alternatively, use [Adaptive Concurrency Control L7 Filter](https://github.com/envoyproxy/envoy/issues/7789).

**Comment by dgn** [comment]
I filed a draft PR that disables circuit breaking by default, but will use current defaults (really only `maxRetries: 1024`) if the user enables it by explicitly setting any of the relevant fields. Not sure if that's enough though, it certainly lacks testing

**Comment by rshriram** [comment]
is it possible to disable it by default though? We used to disable it by default in the past IIRC, but I vaguely recall that it just didn't work

**Comment by rshriram** [comment]
Also, our APIs have been stating that its by default set to 1024. Though I guess its just a docs issue. I have no issues. We could definitely use the adaptive circuit breaking and set it as the default in Istio so that people wont have to worry about it at all

**Comment by duderino** [comment]
Needs to be in 1.4.  Introducing in patch releases feels like too big a change.   

Thank you @PiotrSikora for filing this

**Comment by PiotrSikora** [comment]
> I filed a draft PR that disables circuit breaking by default, but will use current defaults (really only `maxRetries: 1024`) if the user enables it by explicitly setting any of the relevant fields. Not sure if that's enough though, it certainly lacks testing

@dgn thanks for working on that! Please keep in mind that all unspecified fields will use Envoy's default (1024), so we must explicitly configure them to high values (max uint32), otherwise we're not disabling anything.

> is it possible to disable it by default though? We used to disable it by default in the past IIRC, but I vaguely recall that it just didn't work

@rshriram you can configure it to high values (max uint32) to effectively disable all limits, not configuring them at all will result in default limits (1024) everywhere.

> We could definitely use the adaptive circuit breaking and set it as the default in Istio so that people wont have to worry about it at all

@rshriram @tonya11en mentioned (on the upstream issue) that adaptive circuit breaking requires default maximum concurrency, which might result in more issues for us, so let's completely disable circuit breaking, instead of trading one set of issues for another.

> Needs to be in 1.4. Introducing in patch releases feels like too big a change.

@duderino agreed.

**Comment by howardjohn** [comment]
Thanks @dgn, looks like everything including doc changes are merged and I will add a release note for 1.4
