### ISSUE TITLE
Cannot connect to a Postgres Server in a Kubernetes pod with Istio-Proxy as sidecar container

### ISSUE THREAD

**Issue by huydinhle** [istio/istio#17232]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
I am trying to connect to a postgres server using psql in a pod in Kubernetes cluster that has istio-proxy as a sidecar container. I keep getting unhealthy upstream error in the logs that prevents me from connecting to the server.

If I do the same thing in a pod without istio-proxy sidecar, things would work and I am able to connect to the postgres server

```
[2019-09-19T19:41:01.754Z] "- - -" 0 UH "-" 0 0 0 - "-" "-" "-" "-" "-" - - 13.66.226.202:5432 10.244.38.68:36886 -
[2019-09-19T19:41:06.278Z] "- - -" 0 UH "-" 0 0 0 - "-" "-" "-" "-" "-" - - 13.66.226.202:5432 10.244.38.68:37002 -
[2019-09-19T19:41:07.331Z] "- - -" 0 UH "-" 0 0 0 - "-" "-" "-" "-" "-" - - 13.66.226.202:5432 10.244.38.68:37030 -
```

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
I should be able to connect to postgress successfully 
**Steps to reproduce the bug**
- This is weird, we only see this in our of our clusters. The other works fine. 
**Version (include the output of `istioctl version --remote` and `kubectl version`)**
istio :1.15
Kubernetes: 1.14.1

**How was Istio installed?**
helm render out all manifest and then apply to cluster.

**Environment where bug was observed (cloud vendor, OS, etc)**
Azure cloud

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by huydinhle** [comment]
output from a telnet command
```
/ # telnet stage-database-westus2-enabling-chimp.postgres.database.azure.com 5432
Connected to stage-database-westus2-enabling-chimp.postgres.database.azure.com
Connection closed by foreign host
```

**Comment by huydinhle** [comment]
@howardjohn can you have someone point me to a direction on how to debug this?. Like which configuration I should be checking?

**Comment by howardjohn** [comment]
We made some bug fixes in this area in 1.3: https://istio.io/news/2019/announcing-1.3/#traffic-management

1.1 is no longer supported: https://istio.io/blog/2019/announcing-1.1-eol/

Please try on recent versions, if you do see the same issues please post all of your config and get config dumps: https://github.com/istio/istio/wiki/Troubleshooting-Istio#collecting-information-2

**Comment by huydinhle** [comment]
@howardjohn This problem seems to be related to mysql deployed within kubernetes cluster that has istio-proxy as sidecar. I am having problem connecting mysql outsie of my cluster that used to work. can't really upgrade our istio right now. Any workaround recommended?

**Comment by huydinhle** [comment]
@howardjohn I tried to delete the meshpolicies default like other thread suggest how to fix this problem with mysql and it still doesn't work. Here is another use having similar issue like I do 
```
https://discuss.istio.io/t/empty-istio-proxy-logs-0-uh/1849```
Can you point me to a good place on how to debug this issue with envoy returning `UH` Unhealthy Upstream
