### ISSUE TITLE
Add missing unit tests is relect_test.go

### ISSUE THREAD

**Issue by ostromart** [istio/istio#17246]
Not all public functions have unit tests in this file.

**Comment by XanderStrike** [comment]
Does `relect_test.go` appear in the istio repository? I can't seem to track it down

**Comment by howardjohn** [comment]
I think this is in istio/operator

**Comment by ostromart** [comment]
This is a more general problem of test coverage. The operator is stable enough now that it makes sense to write more unit tests to improve coverage. 
Closing and moving to https://github.com/istio/istio/issues/19145.
