### ISSUE TITLE
Mixer telemetry add sampling function

### ISSUE THREAD

**Issue by sniperking1234** [istio/istio#17250]
**Describe the feature request**
Sometimes I don't need every piece of data, such as log adapter. I think Mixer can add sampling settings in Rules  to control the telemetry volume.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by bianpengyuan** [comment]
For log adapter, rather than sampling, isn't it better to use rules to filter out the log entry that you need? Such as filter based on response code, request duration (latency) etc.

**Comment by bianpengyuan** [comment]
Sorry I forgot to mention, Mixer rule already supports sampling: https://github.com/istio/api/blob/master/policy/v1beta1/cfg.proto#L183

**Comment by douglas-reid** [comment]
@bianpengyuan almost ;). The reason that is hidden from docs is that we started to provide support for it, but then the work was de-prioritized.

Sampling would be great -- and useful. Especially if we were smart about it.

But as @bianpengyuan points out, it can *mostly* be achieved with smarter config.

With the advent of the extensibility v2 architecture, I don't think adding this feature is top priority for the P&T WG, but I'd be willing to help guide a PR through, if anyone was interested in contributing it. Should be a relatively straightforward contribution.
