### ISSUE TITLE
[Better networking Defaults] What's desired behavior for mTLS + Capture All Inbound traffic

### ISSUE THREAD

**Issue by incfly** [istio/istio#17278]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Copied from comment, https://github.com/istio/istio/pull/16716/files/e6405e61b8b6e565cb2fd1a8e7b0f813ebd5b513#discussion_r326447483

@diemtvu @lambdai with new capture-all mode for inbound traffic, if I'm defining a mTLS authentication policy without specifying port for a service, should I expect all inbound traffic is treated as mTLS enabled? I would expect so, but not sure.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by incfly** [comment]
I talked with @lambdai today.

- today's authn policy is still service targeting, so the mtls/jwt configuration only applies for the port defined in the service definition, not for things beyond that. this is fine.
- in future if we switch to workload selector authn policy, or anything else that configures the mtls for inbound traffic, then we need to ensure the ports not declared in the container ports will also be using mtls configuration.

Something we only need to double check whenworkload policy + capture all inbound traffic both are in effect.

@diemtvu fyi

**Comment by howardjohn** [comment]
Seems like this is resolved?

**Comment by incfly** [comment]
I don't think this is resolved... we have service based policy (only configure ports declared in the service object) and we have inbound traffic capturing all. The non mapped ports does not have mTLS or JWT policy, this should be fixed maybe as part of new authn policy.

/cc @diemtvu
