### ISSUE TITLE
Don't manage custom ca-certificates in Dockerfiles

### ISSUE THREAD

**Issue by tallclair** [istio/istio#17286]
**Bug description**

Lots of dockerfiles in this repo are installing custom ca-certificates via `ADD ca-certificates.tgz /`. I can't tell if the build process downloads fresh certificates, but https://github.com/istio/istio/blob/master/docker/ca-certificates.tgz is over a year old.

Instead, I recommend grabbing the latest ca-certificates via the package manager, as the base dockerfile does: https://github.com/istio/istio/blob/master/docker/Dockerfile.base#L14

Alternatively, consider rebasing on [distroless/static](https://github.com/GoogleContainerTools/distroless/tree/master/base) (see https://github.com/kubernetes/enhancements/blob/d5f6bbe0cc72077125833d8f5af2287b564d4392/keps/sig-release/20190316-rebase-images-to-distroless.md)

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[X] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Steps to reproduce the bug**

Based off reading source code, haven't actually verified in a running version.

**Comment by howardjohn** [comment]
Thanks for the report, seems like something we can and should do. I'll take
a look. By the way, starting in 1.3 we do ship distroless images
