### ISSUE TITLE
*.global dns resolve failed

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#17290]
I tested on istio 1.3, it works well. After we upgraded coredns #16417 this problem happened. I am not sure if the dns Corefile is not right. But i am sure the coredns did not send a request to `127.0.0.1:8053`(verified by tcpdump).

/cc @johscheuer would help on this 

I am familiar with coredns configuration.

**Comment by johscheuer** [comment]
I take a look at this one.

**Comment by johscheuer** [comment]
I just cross-checked it and everything worked fine.

Here is my test setup:

```bash
curl -L https://git.io/getLatestIstio | ISTIO_VERSION=1.3.0 sh -
cd istio-1.3.0
export PATH=$PWD/bin:$PATH
kubectl create namespace istio-system
helm template install/kubernetes/helm/istio-init --name istio-init --namespace istio-system | kubectl apply -f -
helm template install/kubernetes/helm/istio-cni --name=istio-cni --namespace=kube-system | kubectl apply -f -
helm template install/kubernetes/helm/istio --name istio --set istio_cni.enabled=true --namespace istio-system \\n    --values install/kubernetes/helm/istio/values-istio-demo-auth.yaml | kubectl apply -f -
```

I added this part to the `values-istio-demo-auth`:

```yaml
  # Provides dns resolution for global services
  podDNSSearchNamespaces:
  - global
  - "{{ valueOrDefault .DeploymentMeta.Namespace \"default\" }}.global"

  multiCluster:
    enabled: true
    
istiocoredns:
  enabled: true
```

Then I create the stub fir `kubedns` (GKE is using kubedns):

```bash
kubectl apply -f - <<EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns
  namespace: kube-system
data:
  stubDomains: |
    {"global": ["$(kubectl get svc -n istio-system istiocoredns -o jsonpath={.spec.clusterIP})"]}
EOF
```

and then I created a SE:

```bash
kubectl apply -n default -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: httpbin-bar
spec:
  hosts:
  # must be of form name.default.global
  - httpbin.bar.global
  # Treat remote cluster services as part of the service mesh
  # as all clusters in the service mesh share the same root of trust.
  location: MESH_INTERNAL
  ports:
  - name: http1
    number: 8000
    protocol: http
  resolution: DNS
  addresses:
  # the IP address to which httpbin.bar.global will resolve to
  # must be unique for each remote service, within a given cluster.
  # This address need not be routable. Traffic for this IP will be captured
  # by the sidecar and routed appropriately.
  - 127.255.0.2
  endpoints:
  # This is the routable address of the ingress gateway in cluster2 that
  # sits in front of sleep.foo service. Traffic from the sidecar will be
  # routed to this address.
  - address: $(kubectl get --context=$CTX_CLUSTER2 svc --selector=app=istio-ingressgateway -n istio-system -o jsonpath='{.items[0].status.loadBalancer.ingress[0].ip}')
    ports:
      http1: 15443 # Do not change this port value
EOF
```

And using dig from a Pod (I installed the book info):

```bash
$ kubectl exec -ti details-v1-c5b5f496d-p2lhb -- bash  
dig httpbin.bar.global

; <<>> DiG 9.10.3-P4-Debian <<>> httpbin.bar.global
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 49300
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;httpbin.bar.global.		IN	A

;; ANSWER SECTION:
httpbin.bar.global.	30	IN	A	127.255.0.2

;; Query time: 3 msec
;; SERVER: 10.7.240.10#53(10.7.240.10)
;; WHEN: Sat Sep 21 05:49:39 UTC 2019
;; MSG SIZE  rcvd: 70
```

Gives me the expected result.

**Comment by johscheuer** [comment]
If you are using `CoreDNS` you can turn on the [debug mode](https://github.com/coredns/coredns/tree/master/plugin/debug) to see why the Cluster `CoreDNS` doesn't forward the request to the Istio `CoreDNS`

**Comment by hzxuzhonghu** [comment]
Istio 1.3.0 works well, because your pr is not in 1.3. You can test with master daily build

**Comment by hzxuzhonghu** [comment]
https://gcsweb.istio.io/gcs/istio-prerelease/daily-build/master-latest-daily/

**Comment by camille-rodriguez** [comment]
@hzxuzhonghu  @johscheuer 
I am having the same issue. The setup works with kube-dns but not with coredns. I think this issue should be reopened.

**Comment by johscheuer** [comment]
Could you ensure that this fix is already included in your setup: https://github.com/istio/istio/pull/17291 ? Also what version are you using ?

**Comment by camille-rodriguez** [comment]
Hi @johscheuer , thanks for the quick reply! I am using istio 1.3.3, so the template is a bit different. The corefile part looks like this : 

install/kubernetes/helm/istio/charts/istiocoredns/templates
```
data:
  Corefile: |
    .:53 {
          errors
          health
          proxy global 127.0.0.1:8053 {
            protocol grpc insecure
          }
          prometheus :9153
          proxy . /etc/resolv.conf
          cache 30
          reload
        }
```

**Comment by johscheuer** [comment]
I actually didn't changed anything in the old code (see:  https://github.com/istio/istio/pull/16417/files) and seems to be correct (at least with a quick review). What domain are trying to resolve?

I will spin up a cluster later on and will cross check it with version 1.3.3.

What istio version are you using ?

Thanks for your report !

**Comment by camille-rodriguez** [comment]
The error message disappeared, but I am still stuck with a failure. The coredns coreconfig keeps reverting to its original configuration. I tried creating a new config map coredns-custom with the global configuration, and the result is the same

**Comment by johscheuer** [comment]
Please take a look here: https://preliminary.istio.io/docs/setup/install/multicluster/gateways/#setup-dns the docs update was merged just recently (see: https://github.com/istio/istio.io/pull/4811) if you follow the instructions for 1.4.0+ everything should work just fine. If you still have some trouble let me know :)
