### ISSUE TITLE
Route traffic directly to service

### ISSUE THREAD

**Issue by rakeshjain1213** [istio/istio#17307]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by rakeshjain1213** [comment]
Hi,

Just wanted to know that is it possible by any means or configuration, that Service A communicating with Service B both having sidecar enabled, to communicate without sidecar.
I mean Service A hitting Service B, but this communication is not via sidecar but it is direct Service to Service communication.

**Comment by howardjohn** [comment]
@rakeshjain1213 see https://preliminary.istio.io/docs/reference/config/annotations.html, there are various `excludePort`/`excludeIP` options you can use to partially opt out of sending through sidecar

**Comment by rakeshjain1213** [comment]
Hi John Howard,

As per my understanding, using **traffic.sidecar.istio.io/excludeInboundPorts** or **traffic.sidecar.istio.io/excludeOutboundIPRanges** requires a change in Deployment yaml.
If we do so, we need to restart the service. I don't want to restart my service and want to achieve the same with only configuration changes.
Is that possible? 

The above requirement is for following scenario :

Suppose Service A is communicating with Service B in production, with sidecar enabled.
Now for some reasons, there is some issue with the sidecar attached to Service B. Now since every communication is through sidecar, we wont be able to hit Service B.
So our need is to do some configuration changes, because of which now Service A sidecar will communicate directly to Service B.
So what we are expected to do is only configuration changes and no restarts/redeploy.
--

**Comment by howardjohn** [comment]
it is not possible to do this without a restart. The interception is determined by iptables which only run during init
