### ISSUE TITLE
How to use `request.auth.claims` on custom header?

### ISSUE THREAD

**Issue by Jeffwan** [istio/istio#17300]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
I am working on an istio authorization solution. Authentication layer I uses AWS Application Load Balancer and Cognito and once user get authenticated, all following request will have a header `x-amzn-oidc-data` which is a JWT token I'd like to use in istio authorization by comparing user's username or email. 

Example: 
```
HEADER:
{
  "typ": "JWT",
  "kid": "6d153c7d-c654-4ce0-9531-d557d46a39e6",
  "alg": "ES256",
  "iss": "https://cognito-idp.us-west-2.amazonaws.com/us-west-2_DtjdVUviC",
  "client": "21p7fb1d7hbuflkqi31n2mddke",
  "signer": "arn:aws:elasticloadbalancing:us-west-2:xxxx:loadbalancer/app/xxx-istiosystem-istio-2af2/xxxxx",
  "exp": 1569130880
}

PAYLOAD:
{
  "sub": "3acb2cd4-xxxx-xxxx-e6db86c1bebb",
  "email_verified": "true",
  "email": "alice@example.com",
  "username": "alice",
  "exp": 1569130880,
  "iss": "https://cognito-idp.us-west-2.amazonaws.com/us-west-2_xxx"
}
```

looked at this documentation 
https://istio.io/docs/reference/config/authorization/constraints-and-properties/

Trying to use `request.auth.claims[email]: alice@example.com`. But seems `request.auth.claims` refers `Claims from the origin JWT. ` I don't know what's the origin JWT is. Does it mean `Authorization: Bear $TOKEN`. Can I use a custom header for it? 

**Describe alternatives you've considered**
Is there a way I can do 
`request.headers[x-amzn-oidc-data].auth.claims[email]: alice.example.com`

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by yangminzhu** [comment]
You first need to create a JWT policy to authenticate your JWT token, check https://istio.io/docs/tasks/security/authentication/authn-policy/#end-user-authentication for an example of the JWT policy. You can set the `jwtHeaders` field (see https://istio.io/docs/reference/config/security/istio.authentication.v1alpha1/#Jwt) in the policy for JWT token on custom headers.

After you have applied the JWT policy, you can use the `request.auth.claims` normally, you don't need to specify the custom header in the authorization policy.

**Comment by incfly** [comment]
https://github.com/istio/api/blob/master/security/v1beta1/jwt.proto#L118

our new api supports this as well, specify customized header value and remove the prefix, use it in the authz later.

**Comment by incfly** [comment]
seems more appropriate to ask on slack/discuss first, i think :)

**Comment by Jeffwan** [comment]
@incfly @yangminzhu Thanks for the response. As I use 1.1.6, I add a [mixer adaptor](https://github.com/istio/istio/wiki/Route-directive-adapter-development-guide) to solve this problem. In the adaptor, I decode the jwt token and create a new header instead. Then my istio RBAC can use that customized header directly. Do you think that's the best practice?

**Comment by incfly** [comment]
I would strongly suggest you to upgrade to a supported version if you are on 1.1.6... the oldest version we support are 1.4. so many feature/improvements/security vulnerabilities etc. since then.

**Comment by Jeffwan** [comment]
Got it. @incfly Thanks! I will try to upgrade istio control plane.
