### ISSUE TITLE
make download istioctl script work against latest build and publish process

### ISSUE THREAD

**Issue by irisdingbj** [istio/istio#17312]
the https://github.com/istio/istio/blob/master/release/downloadIstioCtl.sh is there already. Need to make sure doc updated and the script can work together with new build and publish process.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[X ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by irisdingbj** [comment]
@howardjohn please let me know once you finished the publish process and it is ready for me to work on this.

**Comment by howardjohn** [comment]
Just tested, it already works
