### ISSUE TITLE
Operator ships charts with testing tag/hub

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#17324]
Downloaded 1.3 release, and see:

```
$ head install/kubernetes/operator/profiles/default.yaml
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  hub: gcr.io/istio-release
  tag: release-1.3-latest-daily
  defaultNamespace: istio-system
```

These need to be `hub: istio` `tag: 1.3.0`.

**Comment by howardjohn** [comment]
Working on this.. should be done by 1.4

**Comment by howardjohn** [comment]
Bumped to P0 -- we cannot ship operator as a stable solution with nightly images

**Comment by jwendell** [comment]
Is the fix for this https://github.com/istio/pkg/pull/83?
Does it need to be backported to 1.3?

**Comment by howardjohn** [comment]
fixed
