### ISSUE TITLE
Update rewriteAppHTTPProbe not working

### ISSUE THREAD

**Issue by BernhardLenz** [istio/istio#17328]
**Bug description**
I am creating a gke cluster using 
```
gcloud beta container clusters create 
...
 --addons=Istio \
  --istio-config=auth=MTLS_STRICT

```

I then proceed to update the rewriteAppHTTPProbe flag to true as described in the following link: 
https://istio.io/docs/ops/app-health-check/#enable-via-helm-option-globally

`kubectl get cm istio-sidecar-injector -n istio-system -o yaml | sed -e "s/ rewriteAppHTTPProbe: false/ rewriteAppHTTPProbe: true/" | kubectl apply -f -
`
Above command applies the config to the default namespace. Is this correct as istio is installed in istio-system? 

Assuming that the change needs to be applied to the istio-system namespace I modified the command to below: 
`kubectl get cm istio-sidecar-injector -n istio-system -o yaml | sed -e "s/ rewriteAppHTTPProbe: false/ rewriteAppHTTPProbe: true/" | kubectl apply -n istio-system -f -
`
I get below output 
`configmap/istio-sidecar-injector configured`

However, when i grep for the rewriteAppHTTPProbe to be set to try, I can see it is still set to false:

```
kubectl get cm istio-sidecar-injector -n istio-system -o yaml | grep rewriteAppHTTPProbe
      rewriteAppHTTPProbe: false
      {"apiVersion":"v1","data":{"config":"policy: enabled\ntemplate: |-\n  rewriteAppHTTPProbe: false\n 
```
**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
1. Correct or clarify the namespace usage in the documentation at https://istio.io/docs/ops/app-health-check/#enable-via-helm-option-globally
2. If the namespace should be istio-system, the `kubectl get cm istio-sidecar-injector -n istio-system -o yaml | grep rewriteAppHTTPProbe` command should show that the setting was updated to true. 

**Steps to reproduce the bug**
See above

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```
istioctl version
client version: 1.2.5
citadel version: d3ed357dbb236f0f6188a7fcd17a47941442f9a8
galley version: d3ed357dbb236f0f6188a7fcd17a47941442f9a8
ingressgateway version: d3ed357dbb236f0f6188a7fcd17a47941442f9a8
pilot version: d3ed357dbb236f0f6188a7fcd17a47941442f9a8
policy version: d3ed357dbb236f0f6188a7fcd17a47941442f9a8
sidecar-injector version: d3ed357dbb236f0f6188a7fcd17a47941442f9a8
telemetry version: d3ed357dbb236f0f6188a7fcd17a47941442f9a8
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-gke.1", GitCommit:"61c30f98599ad5309185df308962054d9670bafa", GitTreeState:"clean", BuildDate:"2019-08-28T11:06:42Z", GoVersion:"go1.12.9b4", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
gcloud beta container clusters create
with
--addons=Istio  --istio-config=auth=MTLS_STRICT

**Environment where bug was observed (cloud vendor, OS, etc)**
gke

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
`kubectl get cm istio-sidecar-injector -n istio-system -o yaml ` already has the namespace in it, so you don't need to pass it to `kubectl`. But you are using the GKE addon so you can't make changes. See https://cloud.google.com/istio/docs/istio-on-gke/overview#how_does_the_upgrade_process_work

**Comment by howardjohn** [comment]
So any change you make GKE will revert shortly after

**Comment by BernhardLenz** [comment]
Thanks. Should the documentation be updated to point gke addon users to that this method is not working?

**Comment by howardjohn** [comment]
None of the docs that involve modifying anything about Istio will work on the GKE addon. I wish https://cloud.google.com/istio/docs/istio-on-gke/overview was a bit more explicit about this but I don't think it makes sense to add a note to the istio.io docs
