### ISSUE TITLE
cx_active per backend maxes out at 16 even with higher maxConnections

### ISSUE THREAD

**Issue by joseret** [istio/istio#17320]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
sum of backends for destination rule should be based on max connections, but we see the limit per backend at 16 (cx_active)
[connectionDump-cx.zip](https://github.com/istio/istio/files/3643358/connectionDump-cx.zip)

**Steps to reproduce the bug**

cat <<EOF | kubectl apply -f -
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: ingestion-frontend
spec:
  host: ingesstion-frontend.default.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTAL
    connectionPool:
      tcp:
        maxConnections: 100000
      http:
        http2MaxRequests: 100000
EOF

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.1.15

**How was Istio installed?**
helm template - OSS
**Environment where bug was observed (cloud vendor, OS, etc)**

Customer

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by dgn** [comment]
I'm assuming this is just a copy/paste mistake, but there's a typo in your `host:`.

Could you attach the clusters section of your gateways `config_dump`? The values should be inserted in the `circuitbreakers.thresholds` section of the upstream cluster

**Comment by howardjohn** [comment]
This is marked as a 1.4 P0, do we have an owner?

**Comment by joseret** [comment]
@dgn here is the dump
[prd-eu-ingestion-config (2).txt](https://github.com/istio/istio/files/3664821/prd-eu-ingestion-config.2.txt)

**Comment by howardjohn** [comment]
This needs more info. Please reopen with additional info if you are still running into issues
