### ISSUE TITLE
Get rid of storing root cert in config map

### ISSUE THREAD

**Issue by JimmyCYJ** [istio/istio#17329]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
While working on https://github.com/istio/istio/issues/17059, the root cert is stored in config map and is ready by Citadel agent. With auto root upgrade, Citadel agent need to periodically check the root cert in config map and reload root cert. Reading config map from multiple nodes is not efficient, and we can mount ca cert into Citadel agent to get rid of dependency on config map.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by JimmyCYJ** [comment]
cc @rlenglet @myidpt

**Comment by rlenglet** [comment]
This is a pre-requisite to merging the node agent into pilot-agent, which runs with a service account that typically wouldn't have the credentials to query this config map.

**Comment by ayj** [comment]
Can we keep the CA cert ConfigMap even if the {node,pilot}agent loads the ca cert from elsewhere? It's  useful for tooling discover the root CA cert without requiring access to any secrets or private keys. For example, I'm using this to automate joining multiple clusters into a mesh.
