### ISSUE TITLE
Dynamic pod labels: Spinnaker pod quarantine

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#17332]
Spinnaker uses dynamic pod labels to quarantine pods out of a service.
Removing a specific label directly from a pod, removes the endpoint from the service.

This is an example of dynamic pod labels.

Recently we have made several decisions regarding static nature of pod labels.

1. Pod labels are placed in nodemetada and deemed constants for the life of the proxy process.
2. Pilot uses this node metadata to decide ServiceInstances.

a. Investigate the mode of failure for spinnaker like behaviour.
b. Decide if we want to support this mode.

**Comment by mandarjog** [comment]
cc @douglas-reid @kyessenov @rshriram @howardjohn

**Comment by howardjohn** [comment]
@hzxuzhonghu

**Comment by kyessenov** [comment]
Is this on k8s?

**Comment by mandarjog** [comment]
yes, this is used with k8s *and* other platforms.

**Comment by kyessenov** [comment]
on k8s, this is also breaking downwards API.

**Comment by howardjohn** [comment]
I think you cannot get labels in `env` using downwards API - probably for
this reason?

**Comment by kyessenov** [comment]
You should be able to query pod labels via Downward API:
https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/#capabilities-of-the-downward-api

**Comment by hzxuzhonghu** [comment]
We can address this in a more easy way than before.   
FYI: I added a new field in https://github.com/istio/istio/pull/17338/files#diff-ee39cd332931ab6f8c10713ce3446d09R159

**Comment by hzxuzhonghu** [comment]
We can use downward api volume mount the labels to sidecar, and watch the file changes, restart envoy when it changes. This is same as And when we change labels in deployment, the pod will recreate too.

I am not sure if it is acceptable in this case.

**Comment by rshriram** [comment]
I think that is fine. And given that its not a common thing to do, its okay to do the envoy restart thing, given that the other 90% of users would benefit greatly from higher decoupling from k8s, lesser reliance on k8s api, as well as the reduced impact of eventual consistency. It seems like a worthwhile tradeoff for usability. What do you guys think?

**Comment by rshriram** [comment]
Ofcourse, if it turns out that 50% of the planet is using Spinnaker in production and that they all rely a LOT on this dynamic label thing, then we have to rethink. May be one option is to have some flag in Pilot that allows these people to choose the old style mode of always going to k8s for the pod labels.

**Comment by douglas-reid** [comment]
Having the labels be considered consts for the lifetime of the proxy was a known compromise to support the simple use case without adding a whole bunch of complexity.

What is the Envoy story around support for dynamic metadata? I know that we could add a filter that could run for the extensions use case, but that won't help Pilot.

**Comment by kyessenov** [comment]
Envoy supports dynamic metadata on listeners, routes, clusters, endpoints, but not on singleton resources such as bootstrap.

We probably want to implement some sort of MetadataDiscoveryService that can subscribe to metadata and update node-level metadata with it.

**Comment by mandarjog** [comment]
@rshriram i don’t think we can restart envoy, because quarantine is the main use case and we typically want to inspect the proxy and app after quarantine and not restart it.
Perhaps we can directly support quarantine instead of this particular method.

**Comment by mandarjog** [comment]
I think this is still an issue.

**Comment by mandarjog** [comment]
Not stale

**Comment by kyessenov** [comment]
Not stale.

**Comment by hzxuzhonghu** [comment]
>We probably want to implement some sort of MetadataDiscoveryService that can subscribe to metadata and update node-level metadata with it.

As we have xds proxy now, i think this is easier now.  I can dig into it.

**Comment by mandarjog** [comment]
I think we have multiple use cases. The quarantine main use case is to remove the it from receiving traffic. We want the outbound config to be unaffected. 
Inbound policies should apply just like before if the pod happens to receive traffic. Perhaps even start drain.

we want the outbound traffic to work as normal if the pod needs to reach outside.

**Comment by kyessenov** [comment]
We don't have restart envoy when labels change. That argues for not having labels in the bootstrap to begin with which is a radical change from today. An interesting case is that pods can re-assign their canonical services as well.

**Comment by howardjohn** [comment]
dynamic change was implemented a while back
