### ISSUE TITLE
Non-Deterministic LDS responses from ServiceRoleBinding

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#17347]
See original report: https://discuss.istio.io/t/non-deterministic-lds-updates-causing-connection-draining/3876/5

I suspect we just need to add a `sortConfigByCreationTime()` here: https://github.com/istio/istio/blob/05e2605d771b43159f4b548afcfe187d8321f9dc/pilot/pkg/model/authorization.go#L70-L74

@yangminzhu do you have time to look at this?

**Comment by yangminzhu** [comment]
@howardjohn sorry I'm OOO and won't have time to look at this for short term, @pitlv2109 @liminw could you help take a look at this? Thanks.
