### ISSUE TITLE
Generate RPM files in addition to Debian files for mesh expansion

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio#17348]
**Describe the feature request**
Currently, only Debian files are provided to be used on a VM for mesh expansion, see
https://istio.io/docs/examples/mesh-expansion/multi-network/#setting-up-the-vm.

For RHEL, RPM files are required.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[X ] Installation
[ X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by jwendell** [comment]
duplicate of https://github.com/istio/istio/issues/9117 ?

**Comment by vadimeisenbergibm** [comment]
@jwendell you are right, it is a duplicate, closing the issue.
