### ISSUE TITLE
String field 'istio.mixer.v1.ReportRequest.default_words' contains invalid UTF-8 Data

### ISSUE THREAD

**Issue by rafaelbmoraes** [istio/istio#17359]
**Bug description**

After upgrading to istio 1.3.0 some of my pods are throwing this error 

[libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/wire_format_lite.cc:603] String field 'istio.mixer.v1.ReportRequest.default_words' contains invalid UTF-8 data when serializing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes.

**Affected product area (please put an X in all that apply)**

[X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[X] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
client version: 1.3.0
citadel version: 1.3.0
citadel version: 1.3.0
egressgateway version: 1.3.0
galley version: 1.3.0
galley version: 1.3.0
ingressgateway version: 1.3.0
ingressgateway version: 1.3.0
pilot version: 1.3.0
pilot version: 1.3.0
pilot version: 1.3.0
pilot version: 1.3.0
policy version: 1.3.0
policy version: 1.3.0
sidecar-injector version: 1.3.0
telemetry version: 1.3.0
telemetry version: 1.3.0

Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-eks-5047ed", GitCommit:"5047edce664593832e9b889e447ac75ab104f527", GitTreeState:"clean", BuildDate:"2019-08-21T22:32:40Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
Helm

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS EKS v1.14

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by douglas-reid** [comment]
Do you possibly have illegal UTF-8 in a service or workload name or maybe a pod label?

**Comment by rafaelbmoraes** [comment]
Services and workload using istio naming convention ex: http-server...

**Comment by Stono** [comment]
Hey, so as you can see I raised the same issue.  All of my workloads are `a-z0-9` and `-`

**Comment by douglas-reid** [comment]
@mandarjog @kyessenov any ideas related to changes in the proxy?

**Comment by sirajmansour** [comment]
facing the same issue

**Comment by kyessenov** [comment]
Do you have strange header values by any chance, e.g. NUL octet? We place C++ strings into protobuf which assumes UTF-8, so if there is some encoded input that is beyond 7 bit ASCII, it might cause the warning that you see. For example, headers are expected to be ASCII so they are not decoded at all. Do you observe any strange values in the metrics? That might help to pin-point where this is happening.

**Comment by sirajmansour** [comment]
I actually don't think this is a warning, i think mixer is not being invoked because of this ?

**Comment by kyessenov** [comment]
It could lead to some loss of some strings in the protobuf payload (this is some auto-generated code so it's hard to tell),  but the call should still be done.

**Comment by sirajmansour** [comment]
I just inspected the headers just for my sanity, they're regular browser headers nothing special there

**Comment by howardjohn** [comment]
@kyessenov @douglas-reid this is marked as P0 for 1.4, is this still correct?

**Comment by kyessenov** [comment]
@howardjohn It's a bug, but we don't know how to reproduce it. It's very hard to tell where the source of invalid UTF-8 is, and it can happen in any protobuf string setter.

**Comment by kyessenov** [comment]
I looked closer at this issue. What happens is that envoy does not validate utf-8 in headers (e.g. `a\xc5z` is a valid value for a header). Protobuf logs a warning but sets the value regardless. Google gRPC client fails to send such proto. Envoy gRPC client does send it but then Google gRPC server rejects it.

**Comment by howardjohn** [comment]
@kyessenov sounds like you have root caused this already, but if it helps I ran into this on ingress on a more or less inactive cluster:
```
[libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/wire_format_lite.cc:584] String field 'istio.mixer.v1.ReportRequest.default_words' contains invalid UTF-8 data when serializing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes.
```

Let me know if there is any useful info I can gather

**Comment by kyessenov** [comment]
If you have a reliable way to get the warning, can you bump the log level to trace or debug? We have two possibilities:
1. Some random request from internet is sending invalid utf-8 in headers/metadata.
2. There is memory corruption in Envoy that overrides bits in strings.

If we can identify the request, we can check for 1).

**Comment by howardjohn** [comment]
I don't think I have a reliable way, I just had it sitting around for a day and saw it logged twice. I'll bump the level up and hopefully the logs don't get truncated

I suspect it's (1) though

**Comment by Stono** [comment]
For what it’s worth the apps I saw it on weren’t internet facing.

**Comment by Stono** [comment]
@howardjohn this was autoclosed but we still see this on 1.4.5 🤷‍♂

**Comment by howardjohn** [comment]
Sorry, reopening
