### ISSUE TITLE
Restrictive network policies result in slow istio-proxy start ups due to locality lookup

### ISSUE THREAD

**Issue by Stono** [istio/istio#17357]
**Bug description**
On deployments which do not permit egress policy, the startup of istio-proxy is quite significantly delayed (10s or so) when attempting to read the metadata:

```
2019-09-24T18:21:41.246128Z     info    Reconciling retry (budget 10)
2019-09-24T18:21:41.246138Z     info    Epoch 0 starting
2019-09-24T18:21:41.246879Z     info    watching /etc/certs for changes
2019-09-24T18:21:50.654026Z     info    Envoy proxy is NOT ready: failed retrieving Envoy stats: Get http://127.0.0.1:15000/stats?usedonly: dial tcp 127.0.0.1:15000: connect: connection refused
2019-09-24T18:21:51.264064Z     warn    Error fetching GCP zone: Get http://169.254.169.254/computeMetadata/v1/instance/zone: dial tcp 169.254.169.254:80: i/o timeout
2019-09-24T18:21:51.264459Z     info    Envoy command: [-c /etc/istio/proxy/envoy-rev0.json --restart-epoch 0 --drain-time-s 45 --parent-shutdown-time-s 60 --service-cluster ssh --service-node sidecar~10.206.3.25~istio-6499cc9554-nrg5g.istio-tcp-issue~istio-tcp-issue.svc.cluster.local --max-obj-name-len 189 --local-address-ip-version v4 --allow-unknown-fields -l error --component-log-level misc:error --concurrency 1]
```

We run with `global.localityLbSetting.enabled` = false, so why does istio/proxy even need zonal information?  Perhaps it could look this up as/when it's required/enabled?

In our particular use case, we inject a liveness probe to istio-pilot which is aggressive enough to detect this as a failed proxy, thus getting it stuck in a crash loop:

```
❯ k get pods
NAME                   READY   STATUS             RESTARTS   AGE
istio-6499cc9554-kxsvf   1/2     CrashLoopBackOff   6          11m
```

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[x] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Locality lookups should fail faster than 10s

**Steps to reproduce the bug**
Set a restrictive `NetworkPolicy` which blocks the egress traffic.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.3.0

**How was Istio installed?**
Helm

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by Stono** [comment]
I was just reliably informed by one of my team that we also had this problem when we enabled https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity, and had to roll it back (metadata lookups failed and took too long, causing crash loops in proxies).

**Comment by duderino** [comment]
@howardjohn @costinm @lambdai @PiotrSikora what do you think the correct solution to this is?

**Comment by howardjohn** [comment]
+ @douglas-reid @mandarjog who are using some of the metadata for stackdriver (I think, maybe its mixerv2)

**Comment by douglas-reid** [comment]
We need more testing with workload identity. It should not be preventing us from accessing the metadata server.

**Comment by howardjohn** [comment]
I can reproduce the original finding that network policy results in ~10s delay. Just apply policy like
```
cat <<EOF | kaf -
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: default-deny-all
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
            name: istio-system
  - to:
    - namespaceSelector:
        matchLabels:
            name: kube-system
EOF
```

and start a pod and look at logs:


```
2019-09-25T18:31:18.338587Z     info    Epoch 0 starting
2019-09-25T18:31:28.358371Z     warn    Error fetching GCP zone: Get http://169.254.169.254/computeMetadata/v1/instance/zone: dial tcp 169.254.169.254:80: i/o timeout
2019-09-25T18:31:28.359015Z     info    Envoy command: ...
```

Note the 10s betwen starting and "Envoy command" (when it actually runs)

**Comment by howardjohn** [comment]
Running outside of GKE does *not* have this issue, because the check looks if it is on GCE first -- it does this by a request to the 169.254.169.254 OR a `nslookup` of `metadata.google.internal`. I assume the latter check works, so there is no timeout issue.

**Comment by Stono** [comment]
I just stumbled across this by the way, I don't know if it'll have any impact for istio?  https://cloud.google.com/compute/docs/migrating-from-0.1-to-v1-metadata-server

**Comment by douglas-reid** [comment]
What is the status here?  Are we still blocked?  Should this be moved to the 1.5 milestone?

**Comment by howardjohn** [comment]
I believe this is still an issue, but I am not sure there are any blockers on a fix - just need to figure out how to workaround this

**Comment by Stono** [comment]
@howardjohn is this still a problem?

**Comment by howardjohn** [comment]
This should be fixed via https://github.com/istio/istio/pull/19971

**Comment by douglas-reid** [comment]
@Minh-Ng if you are using stackdriver, how are you providing the project config to the proxies ?

**Comment by Minh-Ng** [comment]
@douglas-reid I'm in the process of upgrading from 1.4 to 1.8, which included the change from an adapter to wasm so I haven't had time to fill in the details of how tracing works entirely. From my understanding we don't specify it, and it is attempted to be discovered using the instance metadata server.

**Comment by Minh-Ng** [comment]
I've found https://github.com/istio/istio/issues/29268, which seems to be tangentially related, but should a failure of tracing configuration block Istio-proxy from bootstrapping?

**Comment by douglas-reid** [comment]
@Minh-Ng it should not, but I actually think the timeout here is related to `Locality` as well. I'm wondering if you are using `GCP_METADATA` environment variables to pass that logic in. If you are not, I'm worried that you won't be able to get tracing setup properly.

Here's a WIP PR: https://github.com/istio/istio/pull/31685

Tracing should be fixed in a prior PR (https://github.com/istio/istio/pull/29882). We can see about cherry-picking that fix backwards:

**Comment by Minh-Ng** [comment]
I'm not currently using GCP_METADATA env vars and looked at that as a workaround to see if I could set it and bypass the need for communicating to the instance metadata server. It seems that it would not be a workaround (yet) as your PR is still a WIP. 

To clarify, we are running on GCP VM's and are not concerned with running istio with stackdriver tracing on non-GCP environments. For this particular use-case, I'm actually fine with tracing failing, but would like Istio-proxy to start up at the very least. In our 1.4 configuration, the Locality call times out but Istio-proxy successfully bootstraps.

**Comment by Minh-Ng** [comment]
So I switched .values.global.proxy.tracer from "stackdriver" to "zipkin" and was able to start up despite the failed call for zone. So this solidifies the idea that the stackdriver tracer configuration breaks Istio by failing with an error rather than a warning.

```
2021-03-24T20:54:45.554224Z	info	Epoch 0 starting
2021-03-24T20:55:05.571721Z	warn	Error fetching GCP zone: Get "http://169.254.169.254/computeMetadata/v1/instance/zone": dial tcp 169.254.169.254:80: i/o timeout
2021-03-24T20:55:05.572919Z	info	Envoy command: [-c etc/istio/proxy/envoy-rev0.json ...
```

**Comment by douglas-reid** [comment]
@Minh-Ng yes. there are two issues here. the `Locality()` one causing slow starts -- which your logs show is still happening to you (and for which I've started that draft PR) -- and the tracing configuration failing.

For the tracing configuration failing, to use Stackdriver as the tracer, you need to have a project to report against. If that is not configured, tracing to SD will not work. Whether or not that should bork the bootstrap is a reasonable question, but the proxy will be in a "bad" state (as tracing will fail). Let's pursue the tracing bit in another issue.
