### ISSUE TITLE
Few pods are not coming up with SDS enabled istio-1.3.0

### ISSUE THREAD

**Issue by subashd** [istio/istio#17378]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[x ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
All the pods  in namespace Istio-system should be up and running, and service account and token needs to be created automatically 

**Steps to reproduce the bug**
Followed following to setup Istio with SDS
https://istio.io/docs/setup/install/helm/#option-2-install-with-helm-and-tiller-via-helm-install

 kubectl get pods -o wide -n istio-system
NAME                                      READY   STATUS              RESTARTS   AGE   IP             NODE      NOMINATED NODE   READINESS GATES
istio-citadel-7dfc979d4b-zh2j6            1/1     Running             0          24s   10.244.0.123   ubuntu1   <none>           <none>
istio-galley-54689bbc9d-ndm25             0/1     Running             0          24s   10.244.0.128   ubuntu1   <none>           <none>
istio-ingressgateway-c9b5b4d6d-c47vz      0/1     ContainerCreating   0          24s   <none>         ubuntu1   <none>           <none>
istio-init-crd-10-1.3.0-qgv4l             0/1     Completed           0          35s   10.244.0.121   ubuntu1   <none>           <none>
istio-init-crd-11-1.3.0-t8pf5             0/1     Completed           0          35s   10.244.0.120   ubuntu1   <none>           <none>
istio-init-crd-12-1.3.0-pvff8             0/1     Completed           0          35s   10.244.0.119   ubuntu1   <none>           <none>
istio-nodeagent-xcztr                     1/1     Running             0          24s   10.244.0.125   ubuntu1   <none>           <none>
istio-pilot-d879b58f5-s6rpl               0/2     ContainerCreating   0          24s   <none>         ubuntu1   <none>           <none>
istio-policy-64854d5bd8-sbdgb             0/2     ContainerCreating   0          24s   <none>         ubuntu1   <none>           <none>
istio-sidecar-injector-5f9655997b-ddpw6   1/1     Running             0          24s   10.244.0.127   ubuntu1   <none>           <none>
istio-telemetry-5746ccccdc-5fctg          0/2     ContainerCreating   0          24s   <none>         ubuntu1   <none>           <none>
prometheus-7d7b9f7844-wr5pz               0/1     Running             0          24s   10.244.0.126   ubuntu1   <none>           <none>

kubectl describe pods -n istio-system istio-ingressgateway-c9b5b4d6d-c47vz
Name:           istio-ingressgateway-c9b5b4d6d-c47vz
Namespace:      istio-system
Priority:       0
Node:           ubuntu1/10.102.53.122
Start Time:     Wed, 25 Sep 2019 16:22:24 +0530
Labels:         app=istio-ingressgateway
                chart=gateways
                heritage=Tiller
                istio=ingressgateway
                pod-template-hash=c9b5b4d6d
                release=istio
Annotations:    sidecar.istio.io/inject: false
Status:         Pending
IP:
Controlled By:  ReplicaSet/istio-ingressgateway-c9b5b4d6d
Containers:
  istio-proxy:
    Container ID:
    Image:         docker.io/istio/proxyv2:1.3.0
    Image ID:
    Ports:         15020/TCP, 80/TCP, 443/TCP, 31400/TCP, 15029/TCP, 15030/TCP, 15031/TCP, 15032/TCP, 15443/TCP, 15090/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP
    Args:
      proxy
      router
      --domain
      $(POD_NAMESPACE).svc.cluster.local
      --log_output_level=default:info
      --drainDuration
      45s
      --parentShutdownDuration
      1m0s
      --connectTimeout
      10s
      --serviceCluster
      istio-ingressgateway
      --zipkinAddress
      zipkin:9411
      --proxyAdminPort
      15000
      --statusPort
      15020
      --controlPlaneAuthPolicy
      MUTUAL_TLS
      --discoveryAddress
      istio-pilot:15011
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     2
      memory:  1Gi
    Requests:
      cpu:      100m
      memory:   128Mi
    Readiness:  http-get http://:15020/healthz/ready delay=1s timeout=1s period=2s #success=1 #failure=30
    Environment:
      NODE_NAME:                     (v1:spec.nodeName)
      POD_NAME:                     istio-ingressgateway-c9b5b4d6d-c47vz (v1:metadata.name)
      POD_NAMESPACE:                istio-system (v1:metadata.namespace)
      INSTANCE_IP:                   (v1:status.podIP)
      HOST_IP:                       (v1:status.hostIP)
      SERVICE_ACCOUNT:               (v1:spec.serviceAccountName)
      ISTIO_META_POD_NAME:          istio-ingressgateway-c9b5b4d6d-c47vz (v1:metadata.name)
      ISTIO_META_CONFIG_NAMESPACE:  istio-system (v1:metadata.namespace)
      SDS_ENABLED:                  true
      ISTIO_META_WORKLOAD_NAME:     istio-ingressgateway
      ISTIO_META_OWNER:             kubernetes://api/apps/v1/namespaces/istio-system/deployments/istio-ingressgateway
      ISTIO_META_ROUTER_MODE:       sni-dnat
    Mounts:
      /etc/certs from istio-certs (ro)
      /etc/istio/ingressgateway-ca-certs from ingressgateway-ca-certs (ro)
      /etc/istio/ingressgateway-certs from ingressgateway-certs (ro)
      /var/run/sds from sdsudspath (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from istio-ingressgateway-service-account-token-tbz9z (ro)
      /var/run/secrets/tokens from istio-token (rw)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  sdsudspath:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/sds
    HostPathType:
  istio-token:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  43200
  istio-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  istio.istio-ingressgateway-service-account
    Optional:    true
  ingressgateway-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  istio-ingressgateway-certs
    Optional:    true
  ingressgateway-ca-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  istio-ingressgateway-ca-certs
    Optional:    true
  istio-ingressgateway-service-account-token-tbz9z:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  istio-ingressgateway-service-account-token-tbz9z
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason       Age                   From              Message
  ----     ------       ----                  ----              -------
  Warning  FailedMount  8m14s (x50 over 93m)  kubelet, ubuntu1  MountVolume.SetUp failed for volume "istio-token" : failed to fetch token: the server could not find the requested resource
  Warning  FailedMount  3m18s (x40 over 91m)  kubelet, ubuntu1  Unable to mount volumes for pod "istio-ingressgateway-c9b5b4d6d-c47vz_istio-system(36ad41d6-84ac-404f-be4b-bdbef9f82c68)": timeout expired waiting for volumes to attach or mount for pod "istio-system"/"istio-ingressgateway-c9b5b4d6d-c47vz". list of unmounted volumes=[istio-token]. list of unattached volumes=[sdsudspath istio-token istio-certs ingressgateway-certs ingressgateway-ca-certs istio-ingressgateway-service-account-token-tbz9z]                                                                                                                                                                        

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
istioctl version 1.3.0
kubectl version 1.15

**How was Istio installed?**
Followed following to setup Istio with SDS
https://istio.io/docs/setup/install/helm/#option-2-install-with-helm-and-tiller-via-helm-install

**Environment where bug was observed (cloud vendor, OS, etc)**
Kuberentes
Ubuntu 

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by pitlv2109** [comment]
Have you read this https://istio.io/blog/2019/trustworthy-jwt-sds/?

@rcaballeromx  I don't think we're doing a good job at informing this change.

**Comment by rcaballeromx** [comment]
@pitlv2109 I tend to agree, I think we need to provide a more detailed procedure for enabling this feature. Could you file and issue for us to tackle this problem?

**Comment by subashd** [comment]
@pitlv2109 I have read https://istio.io/blog/2019/trustworthy-jwt-sds/ it says:
"On-prem Kubernetes and GKE on-prem: Add extra configurations to your Kubernetes. You may also want to refer to the api-server page for the most up-to-date flag names."
Here it was asked to add extra configurations, the extra configurations is for Kubernetes 1.12 but I am already at 1.15.
Even creating trustworthy JWT should be part of Istio Helm chart or should provide a way to create that??

**Comment by pitlv2109** [comment]
No, the extra configurations are not for k8s 1.12, it's for k8s 1.12 and above. To be more clear, k8s 1.12 and above has trustworthy jwt, but for OSS k8s, you need to add some extra config

**Comment by pitlv2109** [comment]
For example, we use this https://github.com/istio/istio/blob/master/prow/config/trustworthy-jwt.yaml for Kubernetes in Docker with k8s 1.15.

**Comment by subashd** [comment]
@pitlv2109 could you please help me in creating token for regular Kubernetes rather than installing cluster using "kind" (https://kind.sigs.k8s.io/docs/user/quick-start) ?

**Comment by pitlv2109** [comment]
What do you mean regular Kubernetes? KinD uses regular/out of the box OSS Kubernetes. What platform are you using for running Kubernetes?

**Comment by subashd** [comment]
In Ubuntu machine

**Comment by pitlv2109** [comment]
But using what in Ubuntu to run k8s? https://istio.io/docs/setup/platform-setup/, https://ubuntu.com/kubernetes/install. In any case, you should be able to pass in the config I mentioned above when installing k8s

**Comment by howardjohn** [comment]
@subashd see https://microk8s.io/docs/ "Configuring MicroK8s services" shows how to add flags to API server. You need to change your actual kubernetes cluster setup

**Comment by subashd** [comment]
@howardjohn I tried to create service account and keys but not able to make all the pods in isitio-system up and running. It would be great if you guys can give steps to be followed for generating tokens and installing istio for SDS. For people like me who is trying to create SDS based istio the document looks little incomplete.

**Comment by howardjohn** [comment]
@subashd we have instructions here: https://istio.io/blog/2019/trustworthy-jwt-sds/ you need to modify your kubernetes installation and pass certain flags to api server

**Comment by subashd** [comment]
@howardjohn  the extra flags are 
```--service-account-issuer
--service-account-signing-key-file
--service-account-api-audience ```
blog tells audience should be "istio-ca", I am not able to generate token for this?? 
I am struggling to create token and cert and keys.

**Comment by pitlv2109** [comment]
You don't need to worry about the istio-ca audience part. What you need to
do is pass in the flags and their values as shown in the config file I
shared earlier.

**Comment by subashd** [comment]
@pitlv2109 I did not see those sa.key in case of https://ubuntu.com/kubernetes/install... so was trying to generate it manually..

**Comment by subashd** [comment]
@pitlv2109 I am able to install istio finally in my K8 setup. But please do update the document it needs some update. 
Though for microK8s I am still not able to find the sa.key as you mentioned in the config file.

**Comment by pitlv2109** [comment]
> @pitlv2109 I am able to install istio finally in my K8 setup. But please do update the document it needs some update.
> Though for microK8s I am still not able to find the sa.key as you mentioned in the config file.

What do you suggest here?

**Comment by subashd** [comment]
@pitlv2109 mention in platform setup, K8s need to be configured with config file like   "https://github.com/istio/istio/blob/master/prow/config/trustworthy-jwt.yaml"
and also please find a way to achieve same for microk8s as well?

**Comment by pitlv2109** [comment]
We do mention it for some platforms https://istio.io/docs/setup/platform-setup/gke/, https://istio.io/docs/setup/platform-setup/minikube/. The community is welcome to contribute to other platforms as well

**Comment by subashd** [comment]
still in for those platforms, it is mentioned that to add extra config flags but not mentioned which one... when I raised you gave an example ... I am just suggesting to mention same example for setting config flags. @pitlv2109

**Comment by pitlv2109** [comment]
Those are Kubernetes specifics, we don't want to have multiple sources of truth. You can discuss this issue with @rcaballeromx. I'll close this issue for now. Feel free to open another one about Istio document at https://github.com/istio/istio.io

**Comment by buluba89** [comment]
For anyone using a kubespray installation you should:
1.  Edit `inventory/yourcluster/group_vars/k8s-cluster/k8s-cluster.yml`
    Add these settings:
     ```yaml
     kube_kubeadm_apiserver_extra_args:
      service-account-issuer: kubernetes.default.svc
      service-account-signing-key-file: "/etc/kubernetes/ssl/sa.key"
     ```
2.  Upgrade cluster
3.  Validate that `/etc/kubernetes/kubeadm-config.yaml` has the extra args

For me the kubespray upgrade didnt apply the settings so i had to run:
`sudo kubeadm upgrade apply --config /etc/kubernetes/kubeadm-config.yaml --force` 

After that the problem with mounting the istio-token was gone

**Comment by mathieu-gilloots** [comment]
Any ideas with kops ?
Thanks

**Comment by rvirdiz** [comment]
In kops, to enable Istio-1.3+ SDS configuration, add following parameters to your kops cluster.yaml.

spec:
  kubeAPIServer:
    apiAudiences:
    - api
    - istio-ca
    featureGates:
      TokenRequest: "true"
    serviceAccountIssuer: kubernetes.default.svc
    serviceAccountKeyFile:
    - /srv/kubernetes/server.key
    serviceAccountSigningKeyFile: /srv/kubernetes/server.key

**Comment by irizzant** [comment]
For minikube 1.8.2, you need to enable it with:
```
minikube start --extra-config=apiserver.service-account-signing-key-file=/var/lib/minikube/certs/sa.key --extra-config=apiserver.service-account-issuer=kubernetes/serviceaccount --extra-config=apiserver.service-account-api-audiences=api

**Comment by irizzant** [comment]
For kubespray I updated:
roles/kubernetes/master/defaults/main/main.yml

 to be like:
```yaml
kube_kubeadm_apiserver_extra_args:
  service-account-issuer: kubernetes.default.svc
  service-account-signing-key-file: "/etc/kubernetes/ssl/sa.key"
  service-account-api-audiences: api
```

and then I updated the cluster with the corresponding playbook. This way the cluster can be restarted and it takes the configuration straight away.
