### ISSUE TITLE
Update Envoy to support new ALS protocol

### ISSUE THREAD

**Issue by hanahmily** [istio/istio#17374]
I create this issue is to track update Envoy to support new ALS protocol added in https://github.com/envoyproxy/envoy-wasm/pull/205/commits/1f8c137605326f7c04e1eb1c1e503cae43360bfb

 - ~~Update Envoy in istio/proxy. https://github.com/istio/proxy/pull/2432~~
 - Update proxy in istio. #17403

**Comment by lizan** [comment]
I think @JimmyCYJ is working on updating istio/proxy to pickup proto hash fix for SDS, which is included in same envoy-wasm commit.

**Comment by hanahmily** [comment]
Since these changes are merged into istio/proxy, I sent a PR #17403 to update proxy.

**Comment by JimmyCYJ** [comment]
The proxy SHA is already updated in https://github.com/istio/proxy/pull/2421. Could you check if proxy already supports ALS now?
