### ISSUE TITLE
How to decide if a pod needs sidecar upgrade?

### ISSUE THREAD

**Issue by truongnh1992** [istio/istio#17375]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

In [istio/operator](https://github.com/istio/operator) source codes, [`pkg/controller/istiocontrolplane`](https://github.com/istio/operator/tree/master/pkg/controller/istiocontrolplane) there is a file named `istiocontrolplane_controller.go` and struct [**ReconcileIstioControlPlane**](https://github.com/istio/operator/blob/9f9c81e8fb9b191c54ba2511d6995a071986f2b7/pkg/controller/istiocontrolplane/istiocontrolplane_controller.go#L86)

**Describe alternatives you've considered**

Does Istio operator support DataPlane upgrading? It means ReconcileSideCar?
And **when upgrading Istio**, how to decide if a pod needs sidecar upgrade?

**Comment by truongnh1992** [comment]
\area/environments/operator

**Comment by howardjohn** [comment]
I believe the current plan is to not have the operator reconcile the data plane but I may be wrong. The reason is that restarting a users pods is pretty invasive and could cause major outages.

In the very distant future we will be able to upgrade envoy without restarting the full pod

in the near future we plan to add istioctl command / dashboards to show version mismatch

**Comment by truongnh1992** [comment]
Thank you @howardjohn 
**Regarding to upgrading Envoy without restarting the full pod**, could you share with me some idea, please. If possible, I want to contribute to this feature.

**Comment by howardjohn** [comment]
On phone so can't send links, but the general idea is to run envoy through
CNI or CRI (so outside the pod). There are a few issues floating around if
you search for those terms

**Comment by truongnh1992** [comment]
Thank you @howardjohn 
I will discover them.

**Comment by howardjohn** [comment]
https://github.com/istio/istio/issues/11366

Related issues about determining proxy versions: https://github.com/istio/istio/issues/17172 https://github.com/istio/istio/issues/17173
