### ISSUE TITLE
Add vendor support

### ISSUE THREAD

**Issue by farmer-hutao** [istio/istio#17372]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

I recommend adding a vendor dir to holds all dependencies.
Otherwise, it is difficult to download all the dependencies after downloading the istio repo in China.
We can't access a lot of sites because of the well-known reasons（Great Wall Firewall）.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[X] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
We don't plan to do this. I think some other folks have set up GOPROXY that will allow them to access all dependencies they need

**Comment by ericvn** [comment]
Basic steps would be (assuming you are on the _master_ branch as earlier branches had _vendor_):
- Make sure you are using Golang 1.13
- Clone the Istio repo
- Setup a GOPROXY. Not sure if there is a specific one for China development or if the default can be used.
- Run `go mod download` to download modules to local cache for build/test.
- We may need to check that we aren't overriding a locally environment specified GOPROXY in the container builds if indeed you don't have access to that.
