### ISSUE TITLE
Add trace tags related to istio config objects

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#17386]
Envoy PR https://github.com/envoyproxy/envoy/pull/8279 adds the ability to add custom tags based on metadata.

Add trace tags related to istio configuration objects.
The result is that we will be able to see all istio config information in traces.

@objectiser @nrjpoddar @douglas-reid @kyessenov @jshaughn

**Comment by maxbischoff** [comment]
I would also like to statically add trace tags for all envoys in my cluster, would that also be in scope of this issue for you?

**Comment by douglas-reid** [comment]
Still waiting on the upstream PR to merge.

**Comment by douglas-reid** [comment]
I think we have most of the underlying support here, modulo support for using node metadata.

**Comment by jacob-delgado** [comment]
cc @douglas-reid What is the status of this? It will have to wait post 1.6.0.

**Comment by douglas-reid** [comment]
I think we need to expand the API to include Metadata custom tags. I think this is 1.7 territory.

**Comment by jacob-delgado** [comment]
> I would also like to statically add trace tags for all envoys in my cluster, would that also be in scope of this issue for you?

There will be support, albeit it's in development, for this in Istio 1.6.

**Comment by douglas-reid** [comment]
@mandarjog based on conversations today, perhaps this is something we should tackle for 1.8, given annotations that will exist for endpoints and clusters?

/cc: @bianpengyuan

**Comment by douglas-reid** [comment]
Related: https://github.com/istio/istio/issues/28833

We currently have `istio.*` tags for canonical service info. We can add tags with that scheme for config fairly easily. Maybe: `istio.networking.destination_rule` or similar.
