### ISSUE TITLE
Confusing analysis warning for cloud provider namespaces

### ISSUE THREAD

**Issue by esnible** [istio/istio#17381]
When I run `istioctl x analyze --use-kube` using my own build of HEAD I get three warnings:

```
Warn [IST0102](Namespace/ibm-cert-store) The namespace is not enabled for Istio injection. Run 'kubectl label namespace ibm-cert-store istio-injection=enabled' to enable it, or 'kubectl label namespace ibm-cert-store istio-injection=disabled' to explicitly mark it as not needing injection
Warn [IST0102](Namespace/ibm-observe) The namespace is not enabled for Istio injection. Run 'kubectl label namespace ibm-observe istio-injection=enabled' to enable it, or 'kubectl label namespace ibm-observe istio-injection=disabled' to explicitly mark it as not needing injection
Warn [IST0102](Namespace/ibm-system) The namespace is not enabled for Istio injection. Run 'kubectl label namespace ibm-system istio-injection=enabled' to enable it, or 'kubectl label namespace ibm-system istio-injection=disabled' to explicitly mark it as not needing injection
```

I wondered why I saw these for `ibm-` namespaces, but not other namespaces, and found _galley/pkg/config/analysis/analyzers/injection/injection.go_ and found Galley considers `kube-` and `istio-` system namespaces with a `TODO` to make this configurable.

I ask that `ibm-` be added to that list.  Even better: make this configurable as promised so that other cloud providers don't also get these warnings.

**Comment by esnible** [comment]
cc @davidebbo

**Comment by davidebbo** [comment]
It's a tricky problem as there is probably no reliable way to determine whether something is a "system namespace".

So yes, making it configurable would be good, although at the same time we want it to have good defaults. i.e. I wouldn't want everyone to have to specify that kube-system should be excluded.

Short term, I'm good with just adding "ibm-" to the excluded prefix list, until we come up with a proper way of making this configurable.

/cc @sushicw

**Comment by sushicw** [comment]
https://github.com/istio/istio/pull/17869 should greatly mitigate this, since it modifies `istioctl analyze` to analyze one namespace at a time.

We can probably update the injection analyzer to remove those hardcoded exceptions now.

**Comment by sushicw** [comment]
Leaving this issue open for now to track the need to generally ignore system namespaces, even when we want to analyze all namespaces.
