### ISSUE TITLE
Tutorial "Kubernetes Ingress with Cert-Manager" only produces 404

### ISSUE THREAD

**Issue by gboor** [istio/istio#17380]
**Bug description**
I am following the guide at https://istio.io/docs/tasks/traffic-management/ingress/ingress-certmgr/ and cannot get it to work. I have tried on GKE and minikube and always run into the same issue.

One of the steps that seems to be missing from there is annotating the default namespace with the istio-injection label, but even with that done (and the envoy container injected in the hello application pod), following this tutorial stops where you need to check the http connection - all it returns is 404.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[X] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
I expect the hello application to work and not return 404 when I follow this guide.

**Steps to reproduce the bug**
1) Install istio-init as per documentation
2) Follow the tutorial linked above

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
client version: 1.3.0
control plane version: 1.3.0
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-gke.1", GitCommit:"61c30f98599ad5309185df308962054d9670bafa", GitTreeState:"clean", BuildDate:"2019-08-28T11:06:42Z", GoVersion:"go1.12.9b4", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
I installed istio-init as per https://istio.io/docs/setup/install/helm/
I then installed istio as per the tutorial linked above.

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

I have tried to find any relevant logs on the various istio pods, but nothing comes up.

**Comment by howardjohn** [comment]
We had some issues with k8s Ingress in 1.3.0. They have been fixed in https://github.com/istio/istio/pull/17289 which will go in 1.3.1 which is coming this week or early next. See https://github.com/istio/istio/issues/17148 for a workaround

**Comment by gboor** [comment]
Thanks @howardjohn, that worked! Good to know it is going to be fixed soon.

**Comment by woaixky** [comment]
Although i update to 1.3.1, It is still not work. I used --set gateways.istio-ingressgateway.type=NodePort config, but can not get response by curl command.

**Comment by woaixky** [comment]
@howardjohn Can you explain how to resolve this problem? thanks a lot!

**Comment by woaixky** [comment]
@howardjohn  sorry,  i got the 404 by this command "watch -n 1 curl -o /dev/null -s -w %{http_code} $INGRESS_DOMAIN:$INGRESS_PORT" .
