### ISSUE TITLE
Add documentation on using the helm chart in production

### ISSUE THREAD

**Issue by zsrinivas** [istio/istio#17419]
**Describe the feature request**
currently, the helm chart doesn't document that the default tag is latest-master-daily which is generally not suitable in the production.

**Affected product area (please put an X in all that apply)**
if deployed on production things could break when rotating the underlying servers

[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
This is documented: https://istio.io/docs/setup/install/helm/. Please install from the release not github source

**Comment by zsrinivas** [comment]
@howardjohn 
sorry, my mistake, thanks
