### ISSUE TITLE
Multi-Cluster calls (replicated control plane) ignore virtual services in destination clusters

### ISSUE THREAD

**Issue by cart** [istio/istio#17418]
**Bug description**

Cross-cluster calls ignore VirtualServices in destination clusters. Ex: An in-mesh call from ServiceA (ClusterX) to ServiceB (ClusterY) routes directly to ServiceB instead of using Virtual Service rules configured for ServiceB.

This appears to be an artifact of the Envoy configuration in the istio ingress gateway, which routes *.global requests directly to Envoy "clusters" (which translates to a service in k8s). The VirtualService configuration is written to the ingress Envoy's other "normal" Gateway configurations as "dynamic routing rules".

Ex: if i connect the virtual service to a Gateway on port 80, the VirtualService config becomes dynamic_routing_rule config on port 80 in the envoy proxy). This doesn't happen for *.global, even if i directly connect the VirtualService to the "global" Gateway Istio creates for multi-cluster routing.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
I would expect cross cluster calls to be routed the same way for cluster-internal and cluster-external calls instead of cutting straight to the actual service.

**Steps to reproduce the bug**
1. Create two Istio clusters and configure them to use the "replicated control plane" multi-cluster topology
2. Configure a VirtualService in "Cluster B" to perform some form of routing like this;
    * host: servicex.default.svc.cluster.local
        * Note: this service does not actually exist as a K8S service
    * Route:
        * servicex-v1.default.svc.cluster.local (weight: 50%)
        * servicex-v2.default.svc.cluster.local (weight: 50%)
3. Create a ServiceEntry in "Cluster A" for "servicex.default.global", which connects Cluster A to Cluster B.
3. Make a call to the VirtualService in "Cluster B" by routing through a normal Gateway (ex: port 80). 
    * Observe that this succeeds and uses the VirtualService routing.
4. Make a call from a service in "Cluster A" to the "VirtualService" in "Cluster B"
    * Observe that the call fails. Probably because ClusterB's ingress envoy tries to route directly to a "real" servicex.default.svc.cluster.local, but that only exists as a VirtualService.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Istio 1.2.5

**How was Istio installed?**
Helm chart with multi-cluster defaults

**Environment where bug was observed (cloud vendor, OS, etc)**
AKS, Linux

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by hzxuzhonghu** [comment]
@cart Did your virtual service select the gateway?

**Comment by vadimeisenbergibm** [comment]
@cart I think this is by design, this is the current implementation of dedicated control planes multi-cluster. The special gateway is just a passthru gateway. cc @rshriram @sdake.

**Comment by vadimeisenbergibm** [comment]
@cart To clarify my previous answer, the passthru gateway does not perform TLS termination, so it does not see HTTP information and cannot perform routing based on the HTTP information.
