### ISSUE TITLE
Release process doesn't create tags for all repos

### ISSUE THREAD

**Issue by PiotrSikora** [istio/istio#17425]
Release process doesn't create tags for istio/operator and istio/installer (`1.3.1` tag wasn't created for those repos).

cc @istio/release-managers-1-3

**Comment by rlenglet** [comment]
We need to fix the release scripts to tag other repos, following SHA dependencies from `istio/istio` (we can't just randomly tag `HEAD`s in all release branches). The question is: what repos need to be tagged?

cc @duderino @fpesce @howardjohn

**Comment by rlenglet** [comment]
cc @istio/release-managers-1-1 @istio/release-managers-1-2

**Comment by rlenglet** [comment]
@ostromart confirmed that we only need to tag istio/operator and istio/installer.

**Comment by rlenglet** [comment]
The SHA of `istio/operator` can be retrieved from `istio/istio`'s [`go.mod`](https://github.com/istio/istio/blob/master/go.mod), e.g.:
```
	istio.io/operator v0.0.0-20190918001506-3a5dede6e691
```

**Comment by rlenglet** [comment]
The SHA of `istio/installer` can be retrieved from `istio/operator`'s [`installer.sha`](https://github.com/istio/operator/blob/master/installer.sha), e.g.:
```
ed02ef356a8fbf3eeeec2e83ae072c20ce0d8d42
```

**Comment by PiotrSikora** [comment]
Sigh, 1.3.2 was released without those tags again...

cc @duderino

**Comment by PiotrSikora** [comment]
@istio/release-managers-1-3 could you please tag repositories missing 1.3.2 tag?

**Comment by duderino** [comment]
@clarketm how hard do you think it'd be to fix this?

**Comment by clarketm** [comment]
@duderino - This should not be difficult. Where can I help: Adding the tags or updating the current release scripts?

**Comment by clarketm** [comment]
@duderino
I am confused. The `istio/istio` `1.3.1` and `1.3.2` tags point to the same commit SHA. Is this intentional.

```bash
$ git rev-list -n 1 1.3.1 ; git rev-list -n 1 1.3.2

12c4d01552363362b49fce86f83b847b308b9b0d
12c4d01552363362b49fce86f83b847b308b9b0d
```

**Comment by rlenglet** [comment]
Yes, it is intentional.

**Comment by clarketm** [comment]
I manually updated the `1.3.2` tags for:
*  `istio/operator` using `istio/istio@1.3.2` -> [go.mod](https://github.com/istio/istio/blob/12c4d01552363362b49fce86f83b847b308b9b0d/go.mod#L165) 
* `istio/installer` using `istio/operator@1.3.2` -> [installer.sha](https://github.com/istio/operator/blob/f754c5665bbf3a1a440ff4767ea41f34c370484b/installer.sha#L1).

I will work on updating the release script next.

**Comment by clarketm** [comment]
@rlenglet @duderino 
The release script were deleted: #18028 on master. What branch(es) should the fix (#18020) be applied to?

**Comment by rlenglet** [comment]
@clarketm the following branches will need the fix: `release-1.4`, `release-1.3`, `release-1.2`.
Re: `release-1.1`, I'll let @duderino make the call since this branch is approaching EOL.
Thank you!

**Comment by howardjohn** [comment]
1.2 and 1.1 don't need the fix since those repos do not exist. 1.4 doesn't
need the fix since we don't use those scripts.

**Comment by rlenglet** [comment]
> 1.2 and 1.1 don't need the fix since those repos do not exist. 1.4 doesn't need the fix since we don't use those scripts.

You're right. I had only checked the existence of the `/release/gcb` directory.
