### ISSUE TITLE
Enhanced support for Websockets

### ISSUE THREAD

**Issue by Stono** [istio/istio#17424]
**Describe the feature request**
I'm creating this issue to broadly link together my thoughts around websockets on istio.  Websockets are being used more and more at AutoTrader so it's becoming slightly more of a focus point for me.

At a high level:

  - I don't think websocket connections should share the same timeout as the http services.  For example; we have a dashboard which has live chat, the timeout is configured at 10s which is perfectly reasonable for the main http requests, but now the websocket has to reconnect every 10 seconds
  - Many websocket libraries like socket.io have a certain amount of in memory state, therefore they simply don't function unless you use sticky sessions.  I know I can opt-in to this behaviour (and do so) but it feels like perhaps for websocket connections it should just be on by default to give a better out of the box experience.
  - Metrics get distorted quite drastically because of websockets being long lived connections, it'd be great if they were (or could be optionally) excluded from response duration metrics. @douglas-reid started work on this sort of thing here: https://github.com/istio/istio/pull/10877 but the PR went stale.  For example, that same dashboard has api responses typically of sub 100ms, but this is what the response time graphs look like:

![image](https://user-images.githubusercontent.com/1486729/65723212-d2a89500-e0a5-11e9-9a0a-22a0eb24b7f5.png) 

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[ x Networking
[ ] Performance and Scalability
[x] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Comment by HerrTamm** [comment]
We have the same issue with services using websockets.

Our services response time P95 graph:

![image](https://user-images.githubusercontent.com/5142203/73529975-470e8e80-4420-11ea-8906-3d0a6ef803a1.png)

**Comment by jughead** [comment]
@Stono @HerrTamm did you guys found a workaround?

**Comment by sharma-akashdeep** [comment]
Is it technically possible?
