### ISSUE TITLE
Error: failed to start patch cert loop mutatingwebhookconfigurations.admissionregistration.k8s.io "istio-sidecar-injector" not found

### ISSUE THREAD

**Issue by rnkhouse** [istio/istio#17421]
Getting `"istio-sidecar-injector" not found` error on installing istio from helm chart.

    NAME                                      READY     STATUS             RESTARTS   AGE
    certmanager-b8dc8f99c-bw52l               1/1       Running            0          2m
    istio-citadel-5cf47dbf7c-2brk9            1/1       Running            0          2m
    istio-galley-7898b587db-n44z9             1/1       Running            0          2m
    istio-ingressgateway-5d88688454-wrxsr     2/2       Running            0          2m
    istio-init-crd-10-5rkt6                   0/1       Completed          0          2m
    istio-init-crd-11-pg447                   0/1       Completed          0          2m
    istio-init-crd-12-mxrhz                   0/1       Completed          0          2m
    istio-pilot-57b48b77bf-nbjtv              2/2       Running            0          2m
    istio-policy-769664fcf7-59v2n             2/2       Running            0          2m
    istio-sidecar-injector-677bd5ccc5-ckql5   0/1       CrashLoopBackOff   4          2m
    istio-telemetry-f5798dbb7-z6dvz           2/2       Running            1          2m
    prometheus-776fdf7479-psrf5               1/1       Running            0          2m

**Describe Pod**:

	Name:               istio-sidecar-injector-677bd5ccc5-v4shl
	Namespace:          istio-system
	Priority:           0
	PriorityClassName:  <none>
	Node:               aks-agentpool-17141372-2/10.240.0.66
	Start Time:         Thu, 26 Sep 2019 14:53:55 -0400
	Labels:             app=sidecarInjectorWebhook
			    chart=sidecarInjectorWebhook
			    heritage=Tiller
			    istio=sidecar-injector
			    pod-template-hash=677bd5ccc5
			    release=istio
	Annotations:        sidecar.istio.io/inject=false
	Status:             Running
	IP:                 10.240.0.93
	Controlled By:      ReplicaSet/istio-sidecar-injector-677bd5ccc5
	Containers:
	  sidecar-injector-webhook:
	    Container ID:  docker://e5c96af389797e7a0488cf0dac180ff3494fe8602c2cd7a50080e8a848be207a
	    Image:         docker.io/istio/sidecar_injector:1.2.5
	    Image ID:      docker-pullable://istio/sidecar_injector@sha256:6c281139337df6e2f96f3d883e5dc2a75cb6234986ae4f1cd3f9f324112b46eb
	    Port:          <none>
	    Host Port:     <none>
	    Args:
	      --caCertFile=/etc/istio/certs/root-cert.pem
	      --tlsCertFile=/etc/istio/certs/cert-chain.pem
	      --tlsKeyFile=/etc/istio/certs/key.pem
	      --injectConfig=/etc/istio/inject/config
	      --meshConfig=/etc/istio/config/mesh
	      --healthCheckInterval=2s
	      --healthCheckFile=/health
	    State:          Waiting
	      Reason:       CrashLoopBackOff
	    Last State:     Terminated
	      Reason:       Error
	      Exit Code:    255
	      Started:      Thu, 26 Sep 2019 14:55:32 -0400
	      Finished:     Thu, 26 Sep 2019 14:55:32 -0400
	    Ready:          False
	    Restart Count:  4
	    Requests:
	      cpu:        10m
	    Liveness:     exec [/usr/local/bin/sidecar-injector probe --probe-path=/health --interval=4s] delay=4s timeout=1s period=4s #success=1 #failure=3
	    Readiness:    exec [/usr/local/bin/sidecar-injector probe --probe-path=/health --interval=4s] delay=4s timeout=1s period=4s #success=1 #failure=3
	    Environment:  <none>
	    Mounts:
	      /etc/istio/certs from certs (ro)
	      /etc/istio/config from config-volume (ro)
	      /etc/istio/inject from inject-config (ro)
	      /var/run/secrets/kubernetes.io/serviceaccount from istio-sidecar-injector-service-account-token-nxc4z (ro)
	Conditions:
	  Type              Status
	  Initialized       True
	  Ready             False
	  ContainersReady   False
	  PodScheduled      True
	Volumes:
	  config-volume:
	    Type:      ConfigMap (a volume populated by a ConfigMap)
	    Name:      istio
	    Optional:  false
	  certs:
	    Type:        Secret (a volume populated by a Secret)
	    SecretName:  istio.istio-sidecar-injector-service-account
	    Optional:    false
	  inject-config:
	    Type:      ConfigMap (a volume populated by a ConfigMap)
	    Name:      istio-sidecar-injector
	    Optional:  false
	  istio-sidecar-injector-service-account-token-nxc4z:
	    Type:        Secret (a volume populated by a Secret)
	    SecretName:  istio-sidecar-injector-service-account-token-nxc4z
	    Optional:    false
	QoS Class:       Burstable
	Node-Selectors:  <none>
	Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
			 node.kubernetes.io/unreachable:NoExecute for 300s
	Events:
	  Type     Reason     Age               From                               Message
	  ----     ------     ----              ----                               -------
	  Normal   Scheduled  2m                default-scheduler                  Successfully assigned istio-system/istio-sidecar-injector-677bd5ccc5-v4shl to aks-agentpool-17141372-2
	  Warning  BackOff    1m (x10 over 2m)  kubelet, aks-agentpool-17141372-2  Back-off restarting failed container
	  Normal   Pulled     1m (x5 over 2m)   kubelet, aks-agentpool-17141372-2  Container image "docker.io/istio/sidecar_injector:1.2.5" already present on machine
	  Normal   Created    1m (x5 over 2m)   kubelet, aks-agentpool-17141372-2  Created container sidecar-injector-webhook
	  Normal   Started    1m (x5 over 2m)   kubelet, aks-agentpool-17141372-2  Started container sidecar-injector-webhook

**istio version**: v1.2.5

**How was Istio installed?**: Helm chart

**Comment by howardjohn** [comment]
Can you get the logs for the injector? adding `-p` to the `kubectl logs` will get the logs from the previous (crashed) container as well

**Comment by rnkhouse** [comment]
@howardjohn Attaching full logs:

	2019-09-26T20:19:39.094614Z     info    FLAG: --caCertFile="/etc/istio/certs/root-cert.pem"
	2019-09-26T20:19:39.094642Z     info    FLAG: --healthCheckFile="/health"
	2019-09-26T20:19:39.094648Z     info    FLAG: --healthCheckInterval="2s"
	2019-09-26T20:19:39.094653Z     info    FLAG: --help="false"
	2019-09-26T20:19:39.094661Z     info    FLAG: --injectConfig="/etc/istio/inject/config"
	2019-09-26T20:19:39.094665Z     info    FLAG: --injectValues="/etc/istio/inject/values"
	2019-09-26T20:19:39.094668Z     info    FLAG: --kubeconfig=""
	2019-09-26T20:19:39.094675Z     info    FLAG: --log_as_json="false"
	2019-09-26T20:19:39.094678Z     info    FLAG: --log_caller=""
	2019-09-26T20:19:39.094681Z     info    FLAG: --log_output_level="default:info"
	2019-09-26T20:19:39.094684Z     info    FLAG: --log_rotate=""
	2019-09-26T20:19:39.094748Z     info    FLAG: --log_rotate_max_age="30"
	2019-09-26T20:19:39.094752Z     info    FLAG: --log_rotate_max_backups="1000"
	2019-09-26T20:19:39.094756Z     info    FLAG: --log_rotate_max_size="104857600"
	2019-09-26T20:19:39.094763Z     info    FLAG: --log_stacktrace_level="default:none"
	2019-09-26T20:19:39.094772Z     info    FLAG: --log_target="[stdout]"
	2019-09-26T20:19:39.094776Z     info    FLAG: --meshConfig="/etc/istio/config/mesh"
	2019-09-26T20:19:39.094783Z     info    FLAG: --port="443"
	2019-09-26T20:19:39.094787Z     info    FLAG: --tlsCertFile="/etc/istio/certs/cert-chain.pem"
	2019-09-26T20:19:39.094791Z     info    FLAG: --tlsKeyFile="/etc/istio/certs/key.pem"
	2019-09-26T20:19:39.094798Z     info    FLAG: --webhookConfigName="istio-sidecar-injector"
	2019-09-26T20:19:39.094802Z     info    FLAG: --webhookName="sidecar-injector.istio.io"
	2019-09-26T20:19:39.094827Z     info    version root@0798c310-d8da-11e9-89ce-86619cd7d75e-docker.io/istio-1.2.6-b26019f05195188378be9118b0f0fa7613f7ebb4-dirty-Modified
	2019-09-26T20:19:39.097681Z     info    New configuration: sha256sum 5b8d2f71fc7cc3fba59d4d36a16b2aa1fdd18f82ff2c725bd998c0583a7f1e16
	2019-09-26T20:19:39.097754Z     info    Policy: enabled
	2019-09-26T20:19:39.097766Z     info    AlwaysInjectSelector: []
	2019-09-26T20:19:39.097769Z     info    NeverInjectSelector: []
	2019-09-26T20:19:39.097798Z     info    Template: |
	  rewriteAppHTTPProbe: {{ valueOrDefault .Values.sidecarInjectorWebhook.rewriteAppHTTPProbe false }}
	  {{- if or (not .Values.istio_cni.enabled) .Values.global.proxy.enableCoreDump }}
	  initContainers:
	  {{ if ne (annotation .ObjectMeta `sidecar.istio.io/interceptionMode` .ProxyConfig.InterceptionMode) `NONE` }}
	  {{- if not .Values.istio_cni.enabled }}
	  - name: istio-init
	  {{- if contains "/" .Values.global.proxy_init.image }}
	    image: "{{ .Values.global.proxy_init.image }}"
	  {{- else }}
	    image: "{{ .Values.global.hub }}/{{ .Values.global.proxy_init.image }}:{{ .Values.global.tag }}"
	  {{- end }}
	    args:
	    - "-p"
	    - "15001"
	    - "-u"
	    - 1337
	    - "-m"
	    - "{{ annotation .ObjectMeta `sidecar.istio.io/interceptionMode` .ProxyConfig.InterceptionMode }}"
	    - "-i"
	    - "{{ annotation .ObjectMeta `traffic.sidecar.istio.io/includeOutboundIPRanges` .Values.global.proxy.includeIPRanges }}"
	    - "-x"
	    - "{{ annotation .ObjectMeta `traffic.sidecar.istio.io/excludeOutboundIPRanges` .Values.global.proxy.excludeIPRanges }}"
	    - "-b"
	    - "{{ annotation .ObjectMeta `traffic.sidecar.istio.io/includeInboundPorts` (includeInboundPorts .Spec.Containers) }}"
	    - "-d"
	    - "{{ excludeInboundPort (annotation .ObjectMeta `status.sidecar.istio.io/port` .Values.global.proxy.statusPort) (annotation .ObjectMeta `traffic.sidecar.istio.io/excludeInboundPorts` .Values.global.proxy.excludeInboundPorts) }}"
	    {{ if or (isset .ObjectMeta.Annotations `traffic.sidecar.istio.io/excludeOutboundPorts`) (ne .Values.global.proxy.excludeOutboundPorts "") -}}
	    - "-o"
	    - "{{ annotation .ObjectMeta `traffic.sidecar.istio.io/excludeOutboundPorts` .Values.global.proxy.excludeOutboundPorts }}"
	    {{ end -}}
	    {{ if (isset .ObjectMeta.Annotations `traffic.sidecar.istio.io/kubevirtInterfaces`) -}}
	    - "-k"
	    - "{{ index .ObjectMeta.Annotations `traffic.sidecar.istio.io/kubevirtInterfaces` }}"
	    {{ end -}}
	    imagePullPolicy: "{{ .Values.global.imagePullPolicy }}"
	    resources:
	      requests:
		cpu: 10m
		memory: 10Mi
	      limits:
		cpu: 100m
		memory: 50Mi
	    securityContext:
	      runAsUser: 0
	      runAsNonRoot: false
	      capabilities:
		add:
		- NET_ADMIN
	      {{- if .Values.global.proxy.privileged }}
	      privileged: true
	      {{- end }}
	    restartPolicy: Always
	    env:
	    {{- if contains "*" (annotation .ObjectMeta `traffic.sidecar.istio.io/includeInboundPorts` "") }}
	    - name: INBOUND_CAPTURE_PORT
	      value: 15006
	    {{- end }}
	  {{- end }}
	  {{  end -}}
	  {{- if eq .Values.global.proxy.enableCoreDump true }}
	  - name: enable-core-dump
	    args:
	    - -c
	    - sysctl -w kernel.core_pattern=/var/lib/istio/core.proxy && ulimit -c unlimited
	    command:
	      - /bin/sh
	  {{- if contains "/" .Values.global.proxy_init.image }}
	    image: "{{ .Values.global.proxy_init.image }}"
	  {{- else }}
	    image: "{{ .Values.global.hub }}/{{ .Values.global.proxy_init.image }}:{{ .Values.global.tag }}"
	  {{- end }}
	    imagePullPolicy: IfNotPresent
	    resources: {}
	    securityContext:
	      runAsUser: 0
	      runAsNonRoot: false
	      privileged: true
	  {{ end }}
	  {{- end }}
	  containers:
	  - name: istio-proxy
	  {{- if contains "/" .Values.global.proxy.image }}
	    image: "{{ annotation .ObjectMeta `sidecar.istio.io/proxyImage` .Values.global.proxy.image }}"
	  {{- else }}
	    image: "{{ annotation .ObjectMeta `sidecar.istio.io/proxyImage` .Values.global.hub }}/{{ .Values.global.proxy.image }}:{{ .Values.global.tag }}"
	  {{- end }}
	    ports:
	    - containerPort: 15090
	      protocol: TCP
	      name: http-envoy-prom
	    args:
	    - proxy
	    - sidecar
	    - --domain
	    - $(POD_NAMESPACE).svc.{{ .Values.global.proxy.clusterDomain }}
	    - --configPath
	    - "{{ .ProxyConfig.ConfigPath }}"
	    - --binaryPath
	    - "{{ .ProxyConfig.BinaryPath }}"
	    - --serviceCluster
	    {{ if ne "" (index .ObjectMeta.Labels "app") -}}
	    - "{{ index .ObjectMeta.Labels `app` }}.$(POD_NAMESPACE)"
	    {{ else -}}
	    - "{{ valueOrDefault .DeploymentMeta.Name `istio-proxy` }}.{{ valueOrDefault .DeploymentMeta.Namespace `default` }}"
	    {{ end -}}
	    - --drainDuration
	    - "{{ formatDuration .ProxyConfig.DrainDuration }}"
	    - --parentShutdownDuration
	    - "{{ formatDuration .ProxyConfig.ParentShutdownDuration }}"
	    - --discoveryAddress
	    - "{{ annotation .ObjectMeta `sidecar.istio.io/discoveryAddress` .ProxyConfig.DiscoveryAddress }}"
	  {{- if eq .Values.global.proxy.tracer "lightstep" }}
	    - --lightstepAddress
	    - "{{ .ProxyConfig.GetTracing.GetLightstep.GetAddress }}"
	    - --lightstepAccessToken
	    - "{{ .ProxyConfig.GetTracing.GetLightstep.GetAccessToken }}"
	    - --lightstepSecure={{ .ProxyConfig.GetTracing.GetLightstep.GetSecure }}
	    - --lightstepCacertPath
	    - "{{ .ProxyConfig.GetTracing.GetLightstep.GetCacertPath }}"
	  {{- else if eq .Values.global.proxy.tracer "zipkin" }}
	    - --zipkinAddress
	    - "{{ .ProxyConfig.GetTracing.GetZipkin.GetAddress }}"
	  {{- else if eq .Values.global.proxy.tracer "datadog" }}
	    - --datadogAgentAddress
	    - "{{ .ProxyConfig.GetTracing.GetDatadog.GetAddress }}"
	  {{- end }}
	  {{- if .Values.global.proxy.logLevel }}
	    - --proxyLogLevel={{ .Values.global.proxy.logLevel }}
	  {{- end}}
	  {{- if .Values.global.proxy.componentLogLevel }}
	    - --proxyComponentLogLevel={{ .Values.global.proxy.componentLogLevel }}
	  {{- end}}
	    - --dnsRefreshRate
	    - {{ .Values.global.proxy.dnsRefreshRate }}
	    - --connectTimeout
	    - "{{ formatDuration .ProxyConfig.ConnectTimeout }}"
	  {{- if .Values.global.proxy.envoyStatsd.enabled }}
	    - --statsdUdpAddress
	    - "{{ .ProxyConfig.StatsdUdpAddress }}"
	  {{- end }}
	  {{- if .Values.global.proxy.envoyMetricsService.enabled }}
	    - --envoyMetricsServiceAddress
	    - "{{ .ProxyConfig.EnvoyMetricsServiceAddress }}"
	  {{- end }}
	    - --proxyAdminPort
	    - "{{ .ProxyConfig.ProxyAdminPort }}"
	    {{ if gt .ProxyConfig.Concurrency 0 -}}
	    - --concurrency
	    - "{{ .ProxyConfig.Concurrency }}"
	    {{ end -}}
	    - --controlPlaneAuthPolicy
	    - "{{ annotation .ObjectMeta `sidecar.istio.io/controlPlaneAuthPolicy` .ProxyConfig.ControlPlaneAuthPolicy }}"
	  {{- if (ne (annotation .ObjectMeta "status.sidecar.istio.io/port" .Values.global.proxy.statusPort) "0") }}
	    - --statusPort
	    - "{{ annotation .ObjectMeta `status.sidecar.istio.io/port` .Values.global.proxy.statusPort }}"
	    - --applicationPorts
	    - "{{ annotation .ObjectMeta `readiness.status.sidecar.istio.io/applicationPorts` (applicationPorts .Spec.Containers) }}"
	  {{- end }}
	  {{- if .Values.global.trustDomain }}
	    - --trust-domain={{ .Values.global.trustDomain }}
	  {{- end }}
	    env:
	    - name: POD_NAME
	      valueFrom:
		fieldRef:
		  fieldPath: metadata.name
	    - name: POD_NAMESPACE
	      valueFrom:
		fieldRef:
		  fieldPath: metadata.namespace
	    - name: INSTANCE_IP
	      valueFrom:
		fieldRef:
		  fieldPath: status.podIP
	  {{ if eq .Values.global.proxy.tracer "datadog" }}
	    - name: HOST_IP
	      valueFrom:
		fieldRef:
		  fieldPath: status.hostIP
	  {{ end }}
	    - name: ISTIO_META_POD_NAME
	      valueFrom:
		fieldRef:
		  fieldPath: metadata.name
	    - name: ISTIO_META_CONFIG_NAMESPACE
	      valueFrom:
		fieldRef:
		  fieldPath: metadata.namespace
	    - name: ISTIO_META_INTERCEPTION_MODE
	      value: "{{ or (index .ObjectMeta.Annotations `sidecar.istio.io/interceptionMode`) .ProxyConfig.InterceptionMode.String }}"
	    - name: ISTIO_META_INCLUDE_INBOUND_PORTS
	      value: "{{ annotation .ObjectMeta `traffic.sidecar.istio.io/includeInboundPorts` (applicationPorts .Spec.Containers) }}"
	    {{- if .Values.global.network }}
	    - name: ISTIO_META_NETWORK
	      value: "{{ .Values.global.network }}"
	    {{- end }}
	    {{ if .ObjectMeta.Annotations }}
	    - name: ISTIO_METAJSON_ANNOTATIONS
	      value: |
		     {{ toJSON .ObjectMeta.Annotations }}
	    {{ end }}
	    {{ if .ObjectMeta.Labels }}
	    - name: ISTIO_METAJSON_LABELS
	      value: |
		     {{ toJSON .ObjectMeta.Labels }}
	    {{ end }}
	    {{- if (isset .ObjectMeta.Annotations `sidecar.istio.io/bootstrapOverride`) }}
	    - name: ISTIO_BOOTSTRAP_OVERRIDE
	      value: "/etc/istio/custom-bootstrap/custom_bootstrap.json"
	    {{- end }}
	    {{- if .Values.global.sds.customTokenDirectory }}
	    - name: ISTIO_META_SDS_TOKEN_PATH
	      value: "{{ .Values.global.sds.customTokenDirectory -}}/sdstoken"
	    {{- end }}
	    imagePullPolicy: {{ .Values.global.imagePullPolicy }}
	    {{ if ne (annotation .ObjectMeta `status.sidecar.istio.io/port` .Values.global.proxy.statusPort) `0` }}
	    readinessProbe:
	      httpGet:
		path: /healthz/ready
		port: {{ annotation .ObjectMeta `status.sidecar.istio.io/port` .Values.global.proxy.statusPort }}
	      initialDelaySeconds: {{ annotation .ObjectMeta `readiness.status.sidecar.istio.io/initialDelaySeconds` .Values.global.proxy.readinessInitialDelaySeconds }}
	      periodSeconds: {{ annotation .ObjectMeta `readiness.status.sidecar.istio.io/periodSeconds` .Values.global.proxy.readinessPeriodSeconds }}
	      failureThreshold: {{ annotation .ObjectMeta `readiness.status.sidecar.istio.io/failureThreshold` .Values.global.proxy.readinessFailureThreshold }}
	    {{ end -}}
	    securityContext:
	      {{- if .Values.global.proxy.privileged }}
	      privileged: true
	      {{- end }}
	      {{- if ne .Values.global.proxy.enableCoreDump true }}
	      readOnlyRootFilesystem: true
	      {{- end }}
	      {{ if eq (annotation .ObjectMeta `sidecar.istio.io/interceptionMode` .ProxyConfig.InterceptionMode) `TPROXY` -}}
	      capabilities:
		add:
		- NET_ADMIN
	      runAsGroup: 1337
	      {{ else -}}
	      {{ if and .Values.global.sds.enabled .Values.global.sds.useTrustworthyJwt }}
	      runAsGroup: 1337
	      {{- end }}
	      runAsUser: 1337
	      {{- end }}
	    resources:
	      {{ if or (isset .ObjectMeta.Annotations `sidecar.istio.io/proxyCPU`) (isset .ObjectMeta.Annotations `sidecar.istio.io/proxyMemory`) -}}
	      requests:
		{{ if (isset .ObjectMeta.Annotations `sidecar.istio.io/proxyCPU`) -}}
		cpu: "{{ index .ObjectMeta.Annotations `sidecar.istio.io/proxyCPU` }}"
		{{ end}}
		{{ if (isset .ObjectMeta.Annotations `sidecar.istio.io/proxyMemory`) -}}
		memory: "{{ index .ObjectMeta.Annotations `sidecar.istio.io/proxyMemory` }}"
		{{ end }}
	    {{ else -}}
	  {{- if .Values.global.proxy.resources }}
	      {{ toYaml .Values.global.proxy.resources | indent 4 }}
	  {{- end }}
	    {{  end -}}
	    volumeMounts:
	    {{ if (isset .ObjectMeta.Annotations `sidecar.istio.io/bootstrapOverride`) }}
	    - mountPath: /etc/istio/custom-bootstrap
	      name: custom-bootstrap-volume
	    {{- end }}
	    - mountPath: /etc/istio/proxy
	      name: istio-envoy
	    {{- if .Values.global.sds.enabled }}
	    - mountPath: /var/run/sds
	      name: sds-uds-path
	      readOnly: true
	    {{- if .Values.global.sds.useTrustworthyJwt }}
	    - mountPath: /var/run/secrets/tokens
	      name: istio-token
	    {{- end }}
	    {{- if .Values.global.sds.customTokenDirectory }}
	    - mountPath: "{{ .Values.global.sds.customTokenDirectory -}}"
	      name: custom-sds-token
	      readOnly: true
	    {{- end }}
	    {{- else }}
	    - mountPath: /etc/certs/
	      name: istio-certs
	      readOnly: true
	    {{- end }}
	    {{- if and (eq .Values.global.proxy.tracer "lightstep") .Values.global.tracer.lightstep.cacertPath }}
	    - mountPath: {{ directory .ProxyConfig.GetTracing.GetLightstep.GetCacertPath }}
	      name: lightstep-certs
	      readOnly: true
	    {{- end }}
	      {{- if isset .ObjectMeta.Annotations `sidecar.istio.io/userVolumeMount` }}
	      {{ range $index, $value := fromJSON (index .ObjectMeta.Annotations `sidecar.istio.io/userVolumeMount`) }}
	    - name: "{{  $index }}"
	      {{ toYaml $value | indent 4 }}
	      {{ end }}
	      {{- end }}
	  volumes:
	  {{- if (isset .ObjectMeta.Annotations `sidecar.istio.io/bootstrapOverride`) }}
	  - name: custom-bootstrap-volume
	    configMap:
	      name: {{ annotation .ObjectMeta `sidecar.istio.io/bootstrapOverride` "" }}
	  {{- end }}
	  - emptyDir:
	      medium: Memory
	    name: istio-envoy
	  {{- if .Values.global.sds.enabled }}
	  - name: sds-uds-path
	    hostPath:
	      path: /var/run/sds
	  {{- if .Values.global.sds.customTokenDirectory }}
	  - name: custom-sds-token
	    secret:
	      secretName: sdstokensecret
	  {{- end }}
	  {{- if .Values.global.sds.useTrustworthyJwt }}
	  - name: istio-token
	    projected:
	      sources:
	      - serviceAccountToken:
		  path: istio-token
		  expirationSeconds: 43200
		  audience: {{ .Values.global.trustDomain }}
	  {{- end }}
	  {{- else }}
	  - name: istio-certs
	    secret:
	      optional: true
	      {{ if eq .Spec.ServiceAccountName "" }}
	      secretName: istio.default
	      {{ else -}}
	      secretName: {{  printf "istio.%s" .Spec.ServiceAccountName }}
	      {{  end -}}
	    {{- if isset .ObjectMeta.Annotations `sidecar.istio.io/userVolume` }}
	    {{range $index, $value := fromJSON (index .ObjectMeta.Annotations `sidecar.istio.io/userVolume`) }}
	  - name: "{{ $index }}"
	    {{ toYaml $value | indent 2 }}
	    {{ end }}
	    {{ end }}
	  {{- end }}
	  {{- if and (eq .Values.global.proxy.tracer "lightstep") .Values.global.tracer.lightstep.cacertPath }}
	  - name: lightstep-certs
	    secret:
	      optional: true
	      secretName: lightstep.cacert
	  {{- end }}
	  {{- if .Values.global.podDNSSearchNamespaces }}
	  dnsConfig:
	    searches:
	      {{- range .Values.global.podDNSSearchNamespaces }}
	      - {{ render . }}
	      {{- end }}
	  {{- end }}
	Error: failed to start patch cert loop mutatingwebhookconfigurations.admissionregistration.k8s.io "istio-sidecar-injector" not found

**Comment by howardjohn** [comment]
Do you have a mutatingwebhookconfigurations.admissionregistration.k8s.io named `istio-sidecar-injector`? It should be installed with istio. Run `kubectl get mutatingwebhookconfigurations`

**Comment by rnkhouse** [comment]
I checked it. It's not there.
I can see only 1 record.

    kubectl get mutatingwebhookconfigurations                                                                                                                                                                                 
    NAME                               AGE
    aks-webhook-admission-controller   28d

**Comment by howardjohn** [comment]
Something must have gone wrong with the install then? its in the helm charts - https://github.com/istio/istio/blob/9c1d128ed95e880922a82756f5555d12b2f72ae7/install/kubernetes/helm/istio/charts/sidecarInjectorWebhook/templates/mutatingwebhook.yaml#L2

**Comment by rnkhouse** [comment]
Is there any way to check?
I am running below command to install:

    helm install install/kubernetes/helm/istio --name istio --namespace istio-system \
    --set gateways.istio-ingressgateway.loadBalancerIP=xx.xx.xx.xx \
    --set grafana.enabled=false \
    --set tracing.enabled=false \
     --set kiali.enabled=false \
     --set gateways.istio-egressgateway.enabled=false \
     --set gateways.istio-ingressgateway.sds.enabled=true \
      --set global.mtls.enabled=true \
      --set certmanager.enabled=true \
      --set certmanager.email=ronak@example.com \
      --set certmanager.tag=v0.9.0

**Comment by howardjohn** [comment]
I thought helm tiller would fail if it didn't work.. it says it was successfully created? You can try using the `helm template` approach, then there is a least a bit less magic going on behind the scenes and it may be more obvious what the issue is?

**Comment by rnkhouse** [comment]
It just worked with the template approach. Still not sure what went wrong. lol

**Comment by howardjohn** [comment]
Well if you do figure out what went wrong let us know, especially if its on our side. I did just try out the tiller install locally and got the webhook so its at least working in the standard case
