### ISSUE TITLE
After the Ingress Gateway returns 401 response body is changed

### ISSUE THREAD

**Issue by An0nymous0** [istio/istio#17435]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

service return 401 response was changed,Can I return to the original response?

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**
ing

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**
![image](https://user-images.githubusercontent.com/6836030/65757578-06d59180-e14a-11e9-8107-e2323fc6580b.png)

1. Not in the Ingress Gateway

2. After the Ingress Gateway

**Comment by hzxuzhonghu** [comment]
@An0nymous0 We need more info

**Comment by howardjohn** [comment]
I believe this is working as intended, its not specific to ingress or status 401; anytime it goes through envoy headers will be modified, as other proxies do
