### ISSUE TITLE
Service without selector

### ISSUE THREAD

**Issue by mc1711** [istio/istio#17439]
Hi everyone,

I'm very new in using istio so be kind :)

In my application I have a postgres deployed over 3 pods with a statefulset, one of the 3 pods is the master, the other two are replicas. Postgres app has 3 applicationPorts 8008,5432,8080.

This is exposed via a LoadBalancer service without selector. The service expose the tcp port 5432  

When I try to enable istio, I see the listener for the service (10.97.214.221:5432) but the istio-proxy gives me the following error.

2019-09-27T10:10:01.377890Z	info	Envoy proxy is NOT ready: 4 errors occurred:
	* failed checking application ports. listeners="0.0.0.0:15090","10.99.131.137:8086","10.96.205.54:443","10.100.161.241:8443","10.102.131.102:443","10.110.159.121:80","10.111.205.96:42422","10.107.38.173:443","10.97.135.82:9710","10.98.166.7:443","10.102.200.237:15020","10.102.200.237:443","10.96.0.10:53","10.105.86.196:44134","10.107.114.192:5000","10.106.166.162:80","10.96.244.58:26379","10.108.4.68:15443","10.97.214.221:5432","10.96.0.1:443","10.108.4.68:443","0.0.0.0:9300","10.109.244.116:443","10.108.231.110:443","10.104.66.196:5473","10.99.218.106:15011","10.102.200.237:15443","0.0.0.0:9901","0.0.0.0:15010","0.0.0.0:15004","0.0.0.0:15014","0.0.0.0:8080","0.0.0.0:9200","0.0.0.0:8060","0.0.0.0:80","0.0.0.0:9091","10.244.0.54:15020","0.0.0.0:15001"
	* envoy missing listener for inbound application port: 8008
	* envoy missing listener for inbound application port: 5432
	* envoy missing listener for inbound application port: 8080

My question is, is there a best practice to handle services without selector?

**Comment by howardjohn** [comment]
Can you provide the config you have? Is this a service without selector + Endpoints?

If you give config we can apply and easily reproduce it will help a lot in solving this. Thanks!

**Comment by mc1711** [comment]
Hi John, 
here the config of the service, the endpoints and the statefulset.. hope this help 

$kubectl get svc atom-db -o yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: db.atom.staging.db.example.com
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
  creationTimestamp: 2019-09-26T14:40:23Z
  labels:
    application: spilo
    spilo-role: master
    team: atom
    version: atom-db
  name: atom-db
  namespace: default
  resourceVersion: "54034"
  selfLink: /api/v1/namespaces/default/services/atom-db
  uid: 92480a81-e06b-1ee9-a311-c4d455a74c57
spec:
  clusterIP: 10.97.214.221
  externalTrafficPolicy: Cluster
  loadBalancerSourceRanges:
  - 127.0.0.1/32
  ports:
  - name: postgresql
    nodePort: 32576
    port: 5432
    protocol: TCP
    targetPort: 5432
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}


$kubectl get endpoints atom-db -o yaml
apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: 2019-09-26T14:40:22Z
  labels:
    application: spilo
    spilo-role: master
    team: atom
    version: atom-db
  name: atom-db
  namespace: default
  resourceVersion: "53700"
  selfLink: /api/v1/namespaces/default/endpoints/atom-db
  uid: 920fd92b-e06b-11e9-a406-c8d3ffa74c57
subsets:
- addresses:
  - hostname: atom-db-1
    ip: 10.244.0.51
    nodeName: mm1
    targetRef:
      kind: Pod
      name: atom-db-1
      namespace: default
      resourceVersion: "53699"
      uid: 6515ce42-e06b-12e9-a406-c8d3ffa74c57
  - hostname: atom-db-2
    ip: 10.244.0.52
    nodeName: mm1
    targetRef:
      kind: Pod
      name: atom-db-2
      namespace: default
      resourceVersion: "53696"
      uid: 67d0b684-e06b-11e9-a406-c8d3ffa74c57
  - hostname: atom-db-0
    ip: 10.244.0.53
    nodeName: mm1
    targetRef:
      kind: Pod
      name: atom-db-0
      namespace: default
      resourceVersion: "53693"
      uid: 3fe9b567-e06c-11e9-a406-c8d3ffa74c57
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP



$kubectl get statefulset atom-db -o yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    zalando-postgres-operator-rolling-update-required: "false"
  creationTimestamp: 2019-09-30T09:55:25Z
  generation: 1
  labels:
    application: spilo
    team: atom
    version: atom-db
  name: atom-db
  namespace: default
  resourceVersion: "871076"
  selfLink: /apis/apps/v1/namespaces/default/statefulsets/atom-db
  uid: 6d35c3a5-e368-11e9-a406-c8d3ffa74c57
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      application: spilo
      version: atom-db
  serviceName: atom-db
  template:
    metadata:
      creationTimestamp: null
      labels:
        application: spilo
        team: atom
        version: atom-db
      namespace: default
    spec:
      containers:
      - env:
        - name: SCOPE
          value: atom-db
        - name: PGROOT
          value: /home/postgres/pgdata/pgroot
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: PGUSER_SUPERUSER
          value: postgres
        - name: KUBERNETES_SCOPE_LABEL
          value: version
        - name: KUBERNETES_ROLE_LABEL
          value: spilo-role
        - name: KUBERNETES_LABELS
          value: application=spilo
        - name: PGPASSWORD_SUPERUSER
          valueFrom:
            secretKeyRef:
              key: password
              name: postgres.atom-db.credentials
        - name: PGUSER_STANDBY
          value: standby
        - name: PGPASSWORD_STANDBY
          valueFrom:
            secretKeyRef:
              key: password
              name: standby.atom-db.credentials
        - name: PAM_OAUTH2
          value: https://info.example.com/oauth2/tokeninfo?access_token= uid realm=/employees
        - name: SPILO_CONFIGURATION
          value: '{"postgresql":{"bin_dir":"/usr/lib/postgresql/10/bin","pg_hba":["hostssl
            all all 0.0.0.0/0 md5","host    all all 0.0.0.0/0 md5"]},"bootstrap":{"initdb":[{"auth-host":"md5"},{"auth-local":"trust"},"data-checksums",{"encoding":"UTF8"},{"locale":"en_US.UTF-8"}],"users":{"zalandos":{"password":"","options":["CREATEDB","NOLOGIN"]}},"dcs":{}}}'
        - name: DCS_ENABLE_KUBERNETES_API
          value: "true"
        image: registry.opensource.zalan.do/acid/spilo-cdp-11:1.5-p70
        imagePullPolicy: IfNotPresent
        name: postgres
        ports:
        - containerPort: 8008
          protocol: TCP
        - containerPort: 5432
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: "3"
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
          privileged: true
          procMount: Default
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /home/postgres/pgdata
          name: pgdata
        - mountPath: /dev/shm
          name: dshm
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: postgres-operator
      serviceAccountName: postgres-operator
      terminationGracePeriodSeconds: 300
      volumes:
      - emptyDir:
          medium: Memory
        name: dshm
  updateStrategy:
    type: OnDelete
  volumeClaimTemplates:
  - metadata:
      annotations:
        volume.alpha.kubernetes.io/storage-class: default
      creationTimestamp: null
      name: pgdata
    spec:
      accessModes:
      - ReadWriteOnce
      dataSource: null
      resources:
        requests:
          storage: 5Gi
      volumeMode: Filesystem
    status:
      phase: Pending
status:
  collisionCount: 0
  currentReplicas: 3
  currentRevision: atom-db-587b8f4446
  observedGeneration: 1
  readyReplicas: 2
  replicas: 3
  updateRevision: atom-db-587b8f4446
  updatedReplicas: 3

**Comment by mc1711** [comment]
An update, if I check the endpoint list I see that there are no endpoints for the atom-db. Below the related yaml

$kubectl get endpoints
NAME                              ENDPOINTS                                               AGE
atom-db                           <none>                                                  20m
atom-db-repl                      <none>                                                  7d

$kubectl get endpoints atom-db -o yaml
apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: 2019-10-03T13:25:22Z
  labels:
    application: spilo
    spilo-role: master
    team: atom
    version: atom-db
  name: atom-db
  namespace: default
  resourceVersion: "1550465"
  selfLink: /api/v1/namespaces/default/endpoints/atom-db
  uid: 40c14c30-e5e1-11e9-a406-c8d3ffa74c57

**Comment by howardjohn** [comment]
> An update, if I check the endpoint list I see that there are no endpoints for the atom-db. Below the related yaml

That seems like it could be the problem

**Comment by mc1711** [comment]
Thanks John, 

By the way according to kubernetes docs, service without selector not generating endpoints are a  valid configuration https://kubernetes.io/docs/concepts/services-networking/service/#without-selectors .. now is istio not handling at all this kind of scenario or is there a way or a workaround to make istio works?

**Comment by howardjohn** [comment]
@mc1711 correct me if I am wrong but when you have a service without a selector you have to make the Endpoint objects yourself

**Comment by mc1711** [comment]
Yes John I do agree with you in principle. 
If it is not a problem, I would keep this issue open as I need to investigate the deployment a bit further (this is an existing system). I need to understand if there is a specific reason why there are no endpoints (and everything it is still working fine) and if this is still a kubernetes valid configuration.

**Comment by mc1711** [comment]
@howardjohn I think I figured out the issue with my configuration.

The configuration has:
  - 3 postgres pods (db-0,db-1,db-2), one is the master the other two are replicas. 
  - 2 Services (db, db-repl). One to expose the master pod the other to expose the 2 replicas. 

```
$kubectl get svc
NAME                              TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)              AGE
db                           LoadBalancer   10.111.214.22    <pending>     5432:31383/TCP       20h
db-repl                      ClusterIP      10.99.140.84     <none>        5432/TCP             8d

$kubectl get pod
NAME                                               READY     STATUS    RESTARTS   AGE
db-0                                          1/1       Running   0          17h
db-1                                          1/1       Running   0          17h
db-2                                          1/1       Running   0          18h
```


The deployment is done via a postgres operator. The operator creates the 3 pods and then it injects inside each pod a label (role) to decide who is the master and who are the replicas. The operator then uses this label to create the endpoints and associate them to the proper services, db service is associated to the master labeled pod and db-repl is associated to the two replicas (like below). **Consider that this operation takes few seconds.**

```
$kubectl get pod db-0 -o yaml | grep role
    role: replica
$kubectl get pod db-0 -o yaml | grep " podIP:"
  podIP: 10.244.0.133

$kubectl get pod db-1 -o yaml | grep role
    role: master
$kubectl get pod db-1 -o yaml | grep " podIP:"
  podIP: 10.244.0.134

$kubectl get pod db-2 -o yaml | grep role
    role: replica
$kubectl get pod db-2 -o yaml | grep " podIP:"
  podIP: 10.244.0.127

$kubectl get endpoints
NAME                              ENDPOINTS                                                  AGE
db                           10.244.0.134:5432                                          20h
db-repl                      10.244.0.127:5432,10.244.0.133:5432                        8d
```

When I use sidecar injection, the sidecar-proxy run before the operator has labeled the pods, so the endpoints are not yet created and the sidecar-proxy shows as not ready (with the error of my first comment).
 
At that point, when the postgres operator tries to label the pods it cannot reach them because the sidecars are not working properly.

**Comment by howardjohn** [comment]
I think this would work on Istio 1.3, what version are you using?

cc @hzxuzhonghu @mandarjog another case of label updates

**Comment by mc1711** [comment]
I'm using 1.2.5

**Comment by mc1711** [comment]
@howardjohn  I updated to istio 1.3.0 and what I see is that the error on sidecar-proxy not ready is gone, but the postgres operator still not able to to label the pods.

**Comment by hzxuzhonghu** [comment]
@mc1711 What do you mean by ` the postgres operator still not able to to label the pods.` ?  How does postgress operator label pods?

**Comment by mc1711** [comment]
Hi @hzxuzhonghu and @howardjohn, sorry for the late reply. 

After further investigation we found out that the 1.3.1 actually solved the issue, so everything is working fine. 

The postgres-operator not able to label the pods was actually related to another bug from the operator itself.

Thanks a lot for your help and responsiveness.

**Comment by howardjohn** [comment]
Glad its working
