### ISSUE TITLE
Virtual service validation doesn't know about "mesh" or Istio system resources

### ISSUE THREAD

**Issue by esnible** [istio/istio#17442]
To reproduce: `istioctl x analyze tests/e2e/tests/pilot/testdata/rbac/v1alpha1/istio-egressgateway.yaml`

The output `Referenced gateway not found: "mesh"` is not valid.  https://istio.io/docs/reference/config/networking/v1alpha3/virtual-service/#VirtualService says the user may explicitly use `mesh` as one of the gateway names.

The output `Referenced gateway not found: "istio-system/istio-egressgateway"` seems bogus.  This is the conundrum I pointed out in https://github.com/istio/istio/pull/17410#issuecomment-535517844 .  If the user specifies Istio system resources without specifying --use-kube, they probably don't want to hear from Istio that it doesn't know about system resources.

The output `Referenced host not found: "istio-egressgateway.istio-system.svc.cluster.local"` has the same dubious quality as the previous.

**Comment by sushicw** [comment]
The first issue should be fixed by https://github.com/istio/istio/pull/17733.

**Comment by sushicw** [comment]
Revisiting this:

First issue is solved. 

Second issue is still occurring. @esnible Is `istio-system/istio-egressgateway` a special value that is recognized even if no such Gateway CR actually exists in the cluster? If so, I can't find docs indicating that. The repro file defines an `istio-egressgateway` Gateway, but doesn't put it in istio-system specifically. I'm wondering how this is supposed to work, or if there's a test bug lurking here.

Third issue is not currently occurring when looking only at a file. It only comes up if looking at a file with --discovery=true explicitly set. This seems at least mostly correct.

**Comment by esnible** [comment]
When Istio is installed it can be installed with or without "Egress Gateway".  Most users do not install it.  The instructions for adding "Egress Gateway" are at https://istio.io/docs/tasks/traffic-management/egress/egress-gateway/#deploy-istio-egress-gateway

If the user analyzes with `--use-kube` then we want analyze to report an error for _tests/e2e/tests/pilot/testdata/rbac/v1alpha1/istio-egressgateway.yaml_.

We need a rule of thumb for what to do about unsatisfied references in `istio-system`.  I see three possibilities:
- Do nothing, user sees `Referenced gateway not found: "istio-system/istio-egressgateway"`
- Suppress all references to things in `istio-system` if `--use-kube` is ignored
- Have a special analysis code: `INFO IST0112 Skipped check of reference to control plane; use --use-kube` that replaces all errors related to the Istio control plane without getting info from a live cluster.

**Comment by sushicw** [comment]
Thanks for the clarification. 

Setting aside for a moment the "rule of thumb" question, I feel like the test YAML is slightly buggy. It includes an entry that defines istio-egressgateway, but the one that it defines ends up in namespace default, and never gets referenced. If the test file is updated so that the `istio-egressgateway` Gateway is in namespace `istio-system`, then we don't actually generate an error. 

If I'm right about this, it mostly highlights that there are cases where we'd want to show this error even if `--use-kube` is off.

**Comment by sushicw** [comment]
Another option to consider: when `--use-kube` is off, we could include a limited set of default istio-system resource definitions. This would involve less specialized plumbing and would prevent the analyzers from needing to know the state of `--use-kube`. 

The risks are that this could become painful if the default definitions end up changing between versions, or if we need to handle different configuration options. If we're reasonably confident that this is unlikely to happen for the resources we hard-code, then it may be worth it. 

I believe the only ones we need so far are `istio-ingressgateway` and `istio-egressgateway`.

**Comment by esnible** [comment]
It makes sense to provide some default resource definitions if `--use-kube` is off.  It is especially important for pipelines to be able to validate generated YAML without an actual cluster available.

I have `defaultIngressGatewayPorts` in _galley/pkg/config/analysis/analyzers/gateway/gateway.go_ and that is the kind of stuff that should be in the default.

I am not clear on how we generate `istio-system` resources somewhere else for users who want to deploy Istio to a different namespace.  Not sure it is needed at this point.  `istioctl` has a command line argument for that, but not for various other deployment time settings.   It seems like too much to pass in a IstioControlPlane custom resource for this purpose, but that would be very general.

**Comment by sushicw** [comment]
The tricky aspect here is that we don't have a good way to distinguish between the following scenarios:

* The user ran with files only, and didn't include any istio resources
* The user ran with files only, including istio resources (e.g. their istio manifest), but they had configured it with the egress gateway disabled.

In the first case, we probably wouldn't want to report an error if something referenced the default egress gateway, but in the second case, we would. 

If we included a default egress gateway, we'd avoid the false positive in the first case, but then fail to generate a a warning in the second case. 

------

I should note that as of 1.4 the `Referenced gateway not found: "istio-system/istio-egressgateway"` message no longer appears, and `Referenced host not found: "istio-egressgateway.istio-system.svc.cluster.local"` only appears if `--discovery` is enabled. I think the current behavior is reasonable for now, so I'm going to close this out.
