### ISSUE TITLE
istioctl analyze should allow specifying a subset of analyzers by name

### ISSUE THREAD

**Issue by sushicw** [istio/istio#17443]
istioctl analyze should allow specifying a subset of analyzers by name, for testing, scoped debugging, or automated analysis. 

To make this easy to use, it should also allow listing analyzers by name. Available analyzers could be listed in the usage message, or if that gets unwieldy a separate subcommand could print the full list of available analyzers. 

The analyzers README.md should also be updated to reflect this option for testing new analyzers. 

UX aspects of this discussed [here].(https://docs.google.com/document/d/1KuxDRPPt283jx_cIs2C9sFHjoHvoskJt3IGqhPJVHtM/edit)

**Affected product area (please put an X in all that apply)**

[X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by sushicw** [comment]
Another important part of this: the structured validation message should output the name of the analyzer it was generated by. This will make it easier for users to hone in on the subset of analyzers to include (or, in the case of noisy false positives, exclude).

**Comment by sushicw** [comment]
Should we also support exclusions by name?

**Comment by sushicw** [comment]
Should we output, at runtime, which analyzers are run? (Could do that nifty green checkmark thing).

**Comment by selmanj** [comment]
Possibly relevant:

https://docs.google.com/document/d/1r1hOBIwkDesZ8vYaHMj2YThEcUxegB-fLMPBst_yXIU/edit#heading=h.xw1gqgyqs5b

**Comment by sushicw** [comment]
Our strategy around this has evolved a bit since this issue was created.

Our current thinking around supporting CI cases is primarily focused on error code suppression (see https://github.com/istio/istio/issues/17703), and possibly also fine-grained controls for what resources to inspect (see https://github.com/istio/istio/issues/18932). 

Analyzers sit in between this, requiring *N* resources and producing *M* possible validation message types. Requiring users to know those mappings seems sub-optimal, and also redundant when we've got separate controls over the inputs and outputs. 

The only remaining cases where per-analyzer controls could make sense are:
1) if some analyzers are expensive enough that users want to skip over them for performance reasons.
2) if we want to support non-default, "opt-in" analyzers. 

In both cases, we're probably papering over a different underlying issue that we should probably be fixing. 

Since this is not currently looking like a worthy investment of time to implement and maintain, closing this issue.
