### ISSUE TITLE
"istioctl x analyze" success and failure

### ISSUE THREAD

**Issue by esnible** [istio/istio#17440]
`istioctl x analyze` should report success if nothing was logged.  Currently there is no output:

```
$ istioctl x analyze --use-kube
$
```

Model the output on `istioctl validate` if it isn't too hard:
```
istioctl validate -f samples/httpbin/httpbin-gateway.yaml
"samples/httpbin/httpbin-gateway.yaml" is valid
```

`istioctl x analyze` should return an error level through $? if there are any errors (or warnings?)

```
$ istioctl x analyze samples/httpbin/httpbin-gateway.yaml
Error [IST0101](VirtualService/default/httpbin) Referenced host not found: "httpbin"
$ echo $?
0
```

**Comment by howardjohn** [comment]
(likely outside the scope of this issue, and maybe there is another one already) if we included an error code, which I think we should, it may be useful to allow filtering/ignoring certain issues. I am thinking of a case where someone uses this in CI and wants to ignore known "bad" config

**Comment by sushicw** [comment]
Yep, we have a few issues that overlap here.

https://github.com/istio/istio/issues/17862 (exit codes)
https://github.com/istio/istio/issues/17996 (should report success)
https://github.com/istio/istio/issues/17703 (suppressing specific messages per-resource)

@esnible @howardjohn Is there anything else uniquely captured in this issue, or can we close this one?
