### ISSUE TITLE
security: failing test with MarshalToAny

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#17461]
It appears that RBAC config generator is sensitive to the choice of Struct vs Any:
https://github.com/istio/istio/blob/master/pilot/pkg/security/authz/builder/builder_test.go#L225

Adjusting the test to produce Any makes the test fail. It's not clear to me what's being tested, but sensitivity appears to be problematic since we switched to Any.

/cc @howardjohn @yangminzhu

**Comment by yangminzhu** [comment]
I think it's just the tests using the struct for convenient, the code should have any dependency on struct vs any. Probably just need to fix the test to be more robust.

**Comment by kyessenov** [comment]
Please take a look at the linked PR. It fails unit tests, and all I did was to use any instead of struct.
