### ISSUE TITLE
custom define sidecar, not work as we want

### ISSUE THREAD

**Issue by sunvim** [istio/istio#17463]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ X] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
cmd:   curl httpbin.weather:8000/ip -s -o '/dev/null' -w '%{http_code}\n'
out:  404
**Steps to reproduce the bug**
step 1:
In istio 1.1.0,  custom define a sidecar resource, like below:
```bash
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: sidecars-test
  namespace: default
spec:
  workloadSelector:
    labels:
      app: sleep
  egress:
  - hosts:
    - "default/*"
    - "istio-system/*"
```
step 2:
        the example case from istio official sample package 
```bash
        kubectl label namespace default istio-injection=enabled 
         kubectl label namespace weather istio-injection=enabled 
          kubectl apply -f sample/httpbin/httpbin.yaml 
         kubectl apply -f sample/httpbin/httpbin.yaml  -n weather
         kubectl apply -f sample/sleep/sleep.yaml
```
step 3:
  ```bash
        kubectl get po
  ```
output:
```bash
    NAME                                          READY                  STATUS                RESTARTS           AGE
httpbin-7d9d5b55b9-pq75z   2/2                      Running                   0          136m
sleep-7d457d69b5-57rts         2/2                       Running                   0          136m
```
step 4:
```bash
    kubectl exec -t sleep-7d457d69b5-57rts -- curl http://localhost:15000/clusters -s |grep httpbin
```
output:
```bash
Defaulting container name to sleep.
Use 'kubectl describe pod/sleep-7d457d69b5-57rts -n default' to see all of the containers in this pod.
outbound|8000||httpbin.default.svc.cluster.local::default_priority::max_connections::1024
outbound|8000||httpbin.default.svc.cluster.local::default_priority::max_pending_requests::1024
outbound|8000||httpbin.default.svc.cluster.local::default_priority::max_requests::1024
outbound|8000||httpbin.default.svc.cluster.local::default_priority::max_retries::1024
outbound|8000||httpbin.default.svc.cluster.local::high_priority::max_connections::1024
outbound|8000||httpbin.default.svc.cluster.local::high_priority::max_pending_requests::1024
outbound|8000||httpbin.default.svc.cluster.local::high_priority::max_requests::1024
outbound|8000||httpbin.default.svc.cluster.local::high_priority::max_retries::3
outbound|8000||httpbin.default.svc.cluster.local::added_via_api::true
outbound|8000||httpbin.default.svc.cluster.local::172.17.0.20:80::cx_active::1
outbound|8000||httpbin.default.svc.cluster.local::172.17.0.20:80::cx_connect_fail::0
outbound|8000||httpbin.default.svc.cluster.local::172.17.0.20:80::cx_total::1
outbound|8000||httpbin.default.svc.cluster.local::172.17.0.20:80::rq_active::0
outbound|8000||httpbin.default.svc.cluster.local::172.17.0.20:80::rq_error::0
outbound|8000||httpbin.default.svc.cluster.local::172.17.0.20:80::rq_success::1
outbound|8000||httpbin.default.svc.cluster.local::172.17.0.20:80::rq_timeout::0
outbound|8000||httpbin.default.svc.cluster.local::172.17.0.20:80::rq_total::1
outbound|8000||httpbin.default.svc.cluster.local::172.17.0.20:80::health_flags::healthy
outbound|8000||httpbin.default.svc.cluster.local::172.17.0.20:80::weight::1
outbound|8000||httpbin.default.svc.cluster.local::172.17.0.20:80::region::
outbound|8000||httpbin.default.svc.cluster.local::172.17.0.20:80::zone::
outbound|8000||httpbin.default.svc.cluster.local::172.17.0.20:80::sub_zone::
outbound|8000||httpbin.default.svc.cluster.local::172.17.0.20:80::canary::false
outbound|8000||httpbin.default.svc.cluster.local::172.17.0.20:80::success_rate::-1
```
step 5:
```bash
     kubectl exec -t sleep-7d457d69b5-57rts -- curl httpbin.weather:8000/ip -s -o '/dev/null' -w '%{http_code}\n'
```
output:
```bash
200
```
that's not  i want,  the same operation in istio 1.1.15 , istio 1.3.0 and istio 1.3.1,
bug it does work in istio 1.1.0
**Version (include the output of `istioctl version --remote` and `kubectl version`)**
client version: version.BuildInfo{Version:"1.1.15", GitRevision:"b12614cbfb7ac34b79ee3c58980c7fb0024b018e", User:"root", Host:"667bfa36-d64d-11e9-b8d8-22bce088d8b5", GolangVersion:"go1.12.9", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.14-2-gb12614c"}
citadel version: version.BuildInfo{Version:"1.3.1", GitRevision:"12c4d01552363362b49fce86f83b847b308b9b0d-dirty", User:"root", Host:"06aa341a-e025-11e9-84ea-4e420500021b", GolangVersion:"go1.12.9", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.3.0-23-g12c4d01"}
galley version: version.BuildInfo{Version:"1.3.1", GitRevision:"12c4d01552363362b49fce86f83b847b308b9b0d-dirty", User:"root", Host:"06aa341a-e025-11e9-84ea-4e420500021b", GolangVersion:"go1.12.9", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.3.0-23-g12c4d01"}
ingressgateway version: version.BuildInfo{Version:"1.3.1", GitRevision:"12c4d01552363362b49fce86f83b847b308b9b0d", User:"root", Host:"06aa341a-e025-11e9-84ea-4e420500021b", GolangVersion:"go1.12.9", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.3.0-23-g12c4d01"}
pilot version: version.BuildInfo{Version:"1.3.1", GitRevision:"12c4d01552363362b49fce86f83b847b308b9b0d-dirty", User:"root", Host:"06aa341a-e025-11e9-84ea-4e420500021b", GolangVersion:"go1.12.9", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.3.0-23-g12c4d01"}
policy version: version.BuildInfo{Version:"1.3.1", GitRevision:"12c4d01552363362b49fce86f83b847b308b9b0d-dirty", User:"root", Host:"06aa341a-e025-11e9-84ea-4e420500021b", GolangVersion:"go1.12.9", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.3.0-23-g12c4d01"}
sidecar-injector version: version.BuildInfo{Version:"1.3.1", GitRevision:"12c4d01552363362b49fce86f83b847b308b9b0d-dirty", User:"root", Host:"06aa341a-e025-11e9-84ea-4e420500021b", GolangVersion:"go1.12.9", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.3.0-23-g12c4d01"}
telemetry version: version.BuildInfo{Version:"1.3.1", GitRevision:"12c4d01552363362b49fce86f83b847b308b9b0d-dirty", User:"root", Host:"06aa341a-e025-11e9-84ea-4e420500021b", GolangVersion:"go1.12.9", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.3.0-23-g12c4d01"}
**How was Istio installed?**
 1: kubectl create namespace istio-system
 2: helm template install/kubernetes/helm/istio-init --name istio-init --namespace istio-system | kubectl apply -f -
3:  helm template install/kubernetes/helm/istio --name istio --namespace istio-system | kubectl apply -f -
**Environment where bug was observed (cloud vendor, OS, etc)**
    os: ubuntu 18.04
    k8s: 1.15.3
  
Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
This is working as intended. See https://istio.io/docs/tasks/traffic-management/egress/egress-control/#envoy-passthrough-to-external-services

By default Envoy can access all "unknown"/external services. This can be configured by the docs above.

If you want to restrict traffic you should be using RBAC features, see https://istio.io/docs/tasks/security/.

Note the behavior in 1.1.0 is a bug that was fixed in 1.1.4
