### ISSUE TITLE
pilot_conflict_inbound_listener despite annotations to tell envoy to ignore the port

### ISSUE THREAD

**Issue by Stono** [istio/istio#17465]
**Bug description**

As you can see, pilot is complaining about conflicting listeners:

```
            "vds-acceptor-5fcc99d849-f8lzq.vds-acceptor": {
                "proxy": "vds-acceptor-5fcc99d849-f8lzq.vds-acceptor",
                "message": "Conflicting inbound listener:10.194.28.98:8318. existing: sftp.vds-acceptor.svc.cluster.local, incoming: sftp-internal.vds-acceptor.svc.cluster.local"
            },
            "vds-acceptor-5fcc99d849-prkrw.vds-acceptor": {
                "proxy": "vds-acceptor-5fcc99d849-prkrw.vds-acceptor",
                "message": "Conflicting inbound listener:10.194.13.105:8318. existing: sftp.vds-acceptor.svc.cluster.local, incoming: sftp-internal.vds-acceptor.svc.cluster.local"
            }
```

This is likely because we have two services pointing to the same port:
```
❯ k get ep
NAME            ENDPOINTS                               AGE
app             10.194.21.183:8317,10.194.31.107:8317   99d
sftp            10.194.21.183:8318,10.194.31.107:8318   99d
sftp-internal   10.194.21.183:8318,10.194.31.107:8318   95d
```

That's because we have both public and private ips for it:
```
❯ k get svc
NAME            TYPE           CLUSTER-IP     EXTERNAL-IP     PORT(S)        AGE
app             ClusterIP      10.192.7.254   <none>          80/TCP         99d
sftp            LoadBalancer   10.192.12.95   x.x.x.x         22:31488/TCP   99d
sftp-internal   LoadBalancer   10.192.14.5    10.193.0.213    22:32583/TCP   95d
```

I do not want istio to care about `8318`, only `8317`, so I tried to use the following pod annotations:

```
readiness.status.sidecar.istio.io/applicationPorts: "8317"
traffic.sidecar.istio.io/includeInboundPorts: "8317"
```

However, we still get this warning.  Am I missing something when it comes to telling istio to ignore a given port?

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Expected behavior**
We shouldn't get conflicts or listeners being configured for ports that we don't want istio to care about.

**Steps to reproduce the bug**
Replicate as above.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.3.1

**How was Istio installed?**
Helm

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by Stono** [comment]
:wave:

**Comment by lambdai** [comment]
Simulated how listener config is generated, I think the conflict is not originated from port conflict 8318 vs 8317.
Instead it's two services(sftp and sftp-internal) select the same endpoints: 10.194.21.183:8318 
Pilot is generating 2 listeners for pod 10.194.21.183. Both of listeners use the identifier `10.194.21.183:8318`. 
That is why pilot generate that error message. 

I don't think istio is currently supposing two services select the same endpoints `10.194.21.183:8318` when the protocol is not http.

**Comment by Stono** [comment]
Which is fine, I don't want istio to support them.  They aren't part of the mesh and are edge services for receiving FTP and SFTP, so I need a way to tell istio not to attempt to generate the listeners for `8318`, as you can see above i've explicitly said `includeInboundPorts: 8317`

**Comment by lambdai** [comment]
I think sidecar is the solution. It is supposed to filter the inbound and outbound services.
https://istio.io/docs/reference/config/networking/v1alpha3/sidecar/
But I don't have enough knowledge to give your the exact config working for you

**Comment by Stono** [comment]
@lambdai @howardjohn please can we still have this problem?
