### ISSUE TITLE
exportTo behaviour inconsistent and unclear from documentation

### ISSUE THREAD

**Issue by Stono** [istio/istio#17466]
**Bug description**
Hey, 
The behaviour of exportTo is quite confusing and inconsistent, for example https://istio.io/docs/reference/config/networking/v1alpha3/virtual-service states that setting `exportTo` can be a list of namespace, however it appears that only `*` and `.` work, which is what is stated on https://istio.io/docs/reference/config/networking/v1alpha3/sidecar/.

https://istio.io/docs/reference/config/networking/v1alpha3/service-entry/ states you can use namespaces in the `networking.istio.io/exportTo`, but again, that doesn't appear to work.

What's the roadmap for `exportTo`?

**Affected product area (please put an X in all that apply)**
[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Behaviour that matches the documentation.

**Steps to reproduce the bug**
As above

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.3.1

**How was Istio installed?**
Helm

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by hzxuzhonghu** [comment]
It seems that we have rare case for exporting rules to specific namesapces.

**Comment by Stono** [comment]
I actually would like to be able to do export to: namespace/service-name but I appreciate if there isn't much demand the least we could do is have consistent documentation :)

**Comment by hzxuzhonghu** [comment]
>I actually would like to be able to do export to: namespace/service-name  

This can be done by `sidecar` resource

+1 for fixing the docs

**Comment by frankbu** [comment]
@Stono `exportTo` is "designed" to allow a list of namespaces (including special values `.` and `*`), but the current "implementation" only supports `.` and `*`. Implementing the full semantics is non-trivial, so I'm not sure what the ETA is. Maybe @rshriram can comment on that.

That said, the documentation for the `exportTo` field in both `VirtualService` and `ServiceEntry` includes a special note:
```
NOTE: in the current release, the exportTo value is restricted to “.” or “*” (i.e., the current
namespace or all namespaces).
```
Is the problem that you don't think this is highlighted well enough?

**Comment by Stono** [comment]
I don't think it is very clear that the documentation in https://istio.io/docs/reference/config/networking/v1alpha3/virtual-service/ says "can be a list of namespaces" then contains a note saying "actually, it can't its just . and *".

User documentation in my opinion should reflect the current state of play, not a desired/design state - it'd be much clearer if it just said "Export to can be . for current or * for any".

**Comment by frankbu** [comment]
Yeah, I think it was a late change to restrict it (turned out to be harder to implement than expected). I agree with you, if we don't expect to make the full impl work soon, we should just document how it works today. It's a little tricky because the API is a list, even though that makes no sense with the limited impl, but I'm sure we can find some better wording for the doc.

**Comment by sedflix** [comment]
+1
