### ISSUE TITLE
pilot/debug/push_status shows outdated information

### ISSUE THREAD

**Issue by Stono** [istio/istio#17464]
**Bug description**
Whilst trying to debug `pilot_conflict_inbound_listener`, I was using `pilot:8080/debug/push_status` to debug the problem as the metric doesn't slice by proxy.

After making changes to my application I realised that pilots push status continues to show outdated information for pods that are long gone, eg these two:

```
            "vds-acceptor-5fcc99d849-f8lzq.vds-acceptor": {
                "proxy": "vds-acceptor-5fcc99d849-f8lzq.vds-acceptor",
                "message": "Conflicting inbound listener:10.194.28.98:8318. existing: sftp.vds-acceptor.svc.cluster.local, incoming: sftp-internal.vds-acceptor.svc.cluster.local"
            },
            "vds-acceptor-5fcc99d849-prkrw.vds-acceptor": {
                "proxy": "vds-acceptor-5fcc99d849-prkrw.vds-acceptor",
                "message": "Conflicting inbound listener:10.194.13.105:8318. existing: sftp.vds-acceptor.svc.cluster.local, incoming: sftp-internal.vds-acceptor.svc.cluster.local"
            }
```

When you can see they've been gone for 11 minutes and replaced by:
```
❯ k get pods
NAME                            READY   STATUS    RESTARTS   AGE
vds-acceptor-749c5f5954-9f4p2   2/2     Running   0          11m
vds-acceptor-749c5f5954-dpmhc   2/2     Running   0          11m
```

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[x] Developer Infrastructure

**Expected behavior**
Either debug/push_status should show correct information or (and to be honest, preferred) the `pilot_conflict_inbound_listener` metric should have a label of `proxy`.

**Steps to reproduce the bug**
Cause a conflict, restart a pod, observe pilot.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.3.1

**How was Istio installed?**
Helm

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
A brief look at the code suggests we are updating the place `/debug/push_status` reads from, so maybe we aren't updating the PushContexts appropriately

**Comment by hzxuzhonghu** [comment]
The push context is only re-initiated when full push. Maybe there is only eds push during this period.
