### ISSUE TITLE
Can not disable security component

### ISSUE THREAD

**Issue by kebe7jun** [istio/istio#17471]
**Bug description**

If disable security component with `--set security.enabled=false` option, the citadel deployment will not be created, which makes `istio.io/key-and-cert` controller not running.

Almost all components mount secret to `/etc/certs` created by citadel. So, if citadel not running, other components got an error for starting.

I think it is a bug.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Other components work well without citadel.

**Steps to reproduce the bug**

`helm template ./istio --set security.enabled=false --namespace istio-system`

```console
[root@kebe-dev-m1 ~]# kubectl -n istio-system describe po istio-galley-f4fcb5dc4-mkvp5
...
Events:
  Type     Reason       Age               From                  Message
  ----     ------       ----              ----                  -------
  Normal   Scheduled    25s               default-scheduler     Successfully assigned istio-system/istio-galley-f4fcb5dc4-mkvp5 to kebe-dev-n1
  Warning  FailedMount  9s (x6 over 24s)  kubelet, kebe-dev-n1  MountVolume.SetUp failed for volume "certs" : secret "istio.istio-galley-service-account" not found
```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
istio 1.3.0 kubernetes 1.15.3

**How was Istio installed?**
helm

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
What is your expected behavior when you `--set security.enabled=false`?

**Comment by howardjohn** [comment]
This seems working as intended. Its not clear what is expected - you disabled citadel and things that depend on citadel stopped working. Please reopen with more info if there is more details you can provide

**Comment by pinkertonpg** [comment]
@howardjohn I ran into this with a minimal install of only pilot and the sidecar injector; the sidecar injector fails for the same reason as galley above. I'm very new to Istio, but that was unexpected behavior based on my grasp of what the sidecar injector is doing.

It looks istio/install is tackling some of these things (e.g. https://github.com/istio/installer/blob/master/istio-control/istio-autoinject/values.yaml#L21-L24 for the sidecar injector), but as someone new to istio I'm finding it tough to determine what does depend on citadel and what doesn't.

**Comment by howardjohn** [comment]
@pinkertonpg please see the minimal example values file. You can install with `-f install/kubernetes/helm/istio/values-istio-minimal.yaml` and things will work. I think sidecar injector requires citadel for now
