### ISSUE TITLE
Use constants to convert the component and feature name to helm values

### ISSUE THREAD

**Issue by morvencao** [istio/istio#17472]
Currently when we convert the component and feature name to helm values, we're translating first character to lower case with in `ToYAMLPath` function, see: https://github.com/istio/operator/blob/master/pkg/util/path.go#L60-L67

And `ToYAMLPath` is general function invoked at couples of places, the path contains not only component name and feature name, also we should keep operator relevant stuff outside of util package.

We need to figure out how to define constants to convert the component, feature name and other path to helm values.

**Comment by costinm** [comment]
I'm not sure this conversion is the right path - so far the agreement seems to be that mesh.yaml will
be the primary config, and as such components should directly use mesh.yaml and stop using values.yaml. Translation doesn't seem to help anyone and it's not a long-term value or worth complicating the code. We can keep using the existing values.yaml settings without translation for things that are not yet moved to mesh.yaml - and make sure the new config is solid and properly 
implemented ( by Istio components, not helm )
