### ISSUE TITLE
BUILD_WITH_CONTAINER=1 cannot pass environment variables

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#17474]
Tried all of:

```
BUILD_WITH_CONTAINER=1 make WHAT=pkg/envoy selected-pkg-test
BUILD_WITH_CONTAINER=1 WHAT=pkg/envoy make selected-pkg-test
BUILD_WITH_CONTAINER=1 make selected-pkg-test WHAT=pkg/envoy
```

None of these work to pass environment to the container

**Comment by sdake** [comment]
@howardjohn is it blanket enviornment variables you want passed, or only `WHAT`?

**Comment by howardjohn** [comment]
Everything. There is tons of stuff that uses them -- HUB, TAG, ISTIO_VERSION, WHAT, etc

That being said, passing literally everything may break stuff, but I also don't think we want to special case what is passed through?
