### ISSUE TITLE
BUILD_WITH_CONTAINER=1 needs way to run arbitrary commands

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#17476]
Right now you can only run make commands inside the container. This is not enough. Its very common to want to run something like `go test ./pilot/foo/bar/...` or whatever. Without an easy way to run in the container, you either need to adhoc add a make target, run on local toolchain, or painfully recreate the docker run command.

I would suggest we move the docker run command to some file, say `common/scripts/run-docker.sh`. We move all of the docker logic to that file. The `Makefile` then calls `common/scripts/run-docker.sh make whatever`, and developers can do the same

**Comment by ericvn** [comment]
I don't think we want each target rewritten so that we are repeatedly running `docker runs`, but being able to run a target without having to recreate the command would be useful.
