### ISSUE TITLE
Istio jwt policy not effective

### ISSUE THREAD

**Issue by hilliao** [istio/istio#17473]
**After applying the jwt policy per [end-user authentication](https://istio.io/docs/tasks/security/authn-policy/#end-user-authentication), hitting the URL still returns 200**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
HTTP response 401 after 
`kubectl apply -f https://raw.githubusercontent.com/hilliao/enterprise-solutions/master/deployments/policy.yaml`
**Steps to reproduce the bug**
```
kubectl label namespace default istio-injection=enabled
kubectl get namespace -L istio-injection
```
verify default namespace is enabled

```
kubectl apply -f https://raw.githubusercontent.com/hilliao/enterprise-solutions/master/deployments/configmap.yaml
kubectl apply -f https://raw.githubusercontent.com/hilliao/enterprise-solutions/master/deployments/deployment-configmap.yaml
kubectl apply -f https://raw.githubusercontent.com/hilliao/enterprise-solutions/master/deployments/service.yaml
kubectl get pod -l app="hello-java"
```
verify READY shows 2/2 where 1 pod runs 1 container for the deployment, 1 container for the sidecar

```
kubectl apply -f https://raw.githubusercontent.com/hilliao/enterprise-solutions/master/deployments/gateway.yaml
kubectl apply -f https://raw.githubusercontent.com/hilliao/enterprise-solutions/master/deployments/virtualservice.yaml
kubectl apply -f https://raw.githubusercontent.com/hilliao/enterprise-solutions/master/deployments/policy.yaml
export INGRESS_HOST=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.status.loadBalancer.ingress[0].ip}')

curl $INGRESS_HOST/hello -s -o /dev/null -w "%{http_code}\n"
```
_expect 401, observed 200_

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```
~/istioctl version --remote
client version: 1.2.2
cluster-local-gateway version: 
citadel version: cba9054abf594acf792a985393ade7f2304a9e17
galley version: cba9054abf594acf792a985393ade7f2304a9e17
ingressgateway version: cba9054abf594acf792a985393ade7f2304a9e17
pilot version: cba9054abf594acf792a985393ade7f2304a9e17
policy version: cba9054abf594acf792a985393ade7f2304a9e17
sidecar-injector version: cba9054abf594acf792a985393ade7f2304a9e17
telemetry version: cba9054abf594acf792a985393ade7f2304a9e17

~/istioctl version
client version: 1.2.2
cluster-local-gateway version: 
citadel version: cba9054abf594acf792a985393ade7f2304a9e17
galley version: cba9054abf594acf792a985393ade7f2304a9e17
ingressgateway version: cba9054abf594acf792a985393ade7f2304a9e17
pilot version: cba9054abf594acf792a985393ade7f2304a9e17
policy version: cba9054abf594acf792a985393ade7f2304a9e17
sidecar-injector version: cba9054abf594acf792a985393ade7f2304a9e17
telemetry version: cba9054abf594acf792a985393ade7f2304a9e17
```

**How was Istio installed?**
```
export GCLOUD_PROJECT=YOUR_PROJECT_ID
gcloud beta container --project $GCLOUD_PROJECT clusters create "istio-auth-0" --zone "us-central1-f" --no-enable-basic-auth --cluster-version "1.14.6-gke.1" --machine-type "n1-standard-1" --image-type "COS" --disk-type "pd-ssd" --disk-size "20" --metadata disable-legacy-endpoints=true --scopes "https://www.googleapis.com/auth/devstorage.read_only","https://www.googleapis.com/auth/logging.write","https://www.googleapis.com/auth/monitoring","https://www.googleapis.com/auth/servicecontrol","https://www.googleapis.com/auth/service.management.readonly","https://www.googleapis.com/auth/trace.append" --num-nodes "3" --enable-stackdriver-kubernetes --enable-ip-alias --network "projects/tcsplayground/global/networks/default" --subnetwork "projects/tcsplayground/regions/us-central1/subnetworks/default" --default-max-pods-per-node "110" --enable-autoscaling --min-nodes "1" --max-nodes "6" --addons HorizontalPodAutoscaling,HttpLoadBalancing,Istio,CloudRun --istio-config auth=MTLS_PERMISSIVE --enable-autoupgrade --enable-autorepair
```

**Environment where bug was observed (cloud vendor, OS, etc)**
Google Cloud Platform, see gcloud command above, [istio dump](https://drive.google.com/open?id=1UU0YM_OSyE4Sk9wFSAQy7dKfTcuzbmDU)

**Comment by incfly** [comment]
I think this is most likely a misconfiguration issue, but pass to @pitlv2109 to take a look.

**Comment by hilliao** [comment]
I made the image repository in the deployment file public. @pitlv2109 should be able to deploy easily to any cluster with egress Internet access.

**Comment by cyruscode** [comment]
I also have the same issue, with Istio 1.3.0 and mtls enabled inside the mesh

---
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "default"
  namespace: "someNamespace"
spec:
  peers:
  - mtls:
      mode: STRICT
  origins:
  - jwt:
      issuer: "testing@secure.istio.io"
      jwksUri: "https://raw.githubusercontent.com/istio/istio/release-1.3/security/tools/jwt/samples/jwks.json"
  principalBinding: USE_ORIGIN
---
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "default"
  namespace: "someNamespace"
spec:
  host: "*.someNamespace.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL

**Comment by cyruscode** [comment]
Finally made it work, on istio 1.3.3, not tested with others, bug was in the Service definition, apparently the port name must begin with "http" or "https" .... as soon as I changed this, it worked! 

---
apiVersion: v1
kind: Service
metadata:
  name: someName
  namespace: someNamespace
  labels:
    app: someName
spec:
  selector:
    app: someName
  ports:
    - name: http
      port: 80
---

**Comment by hilliao** [comment]
Indeed, after [changing service.yaml to have name: http](https://github.com/hilliao/enterprise-solutions/commit/4d0e74b431c6702d71787206a21466f84cc0ebc4), applying the policy took a minute to cause HTTP request to return 401:

`
istio-1.3.3$ curl $INGRESS_HOST/hello -s -o /dev/null -w "%{http_code}\n"
401
istio-1.3.3$ curl $INGRESS_HOST/hello -s -o /dev/null -w "%{http_code}\n"
200
istio-1.3.3$ curl $INGRESS_HOST/hello -s -o /dev/null -w "%{http_code}\n"
401
istio-1.3.3$ curl $INGRESS_HOST/hello -s -o /dev/null -w "%{http_code}\n"
401
istio-1.3.3$ curl $INGRESS_HOST/hello -s -o /dev/null -w "%{http_code}\n"
401
istio-1.3.3$ curl $INGRESS_HOST/hello -s -o /dev/null -w "%{http_code}\n"
401
istio-1.3.3$ curl $INGRESS_HOST/hello -s -o /dev/null -w "%{http_code}\n"
401
istio-1.3.3$ curl $INGRESS_HOST/hello -s -o /dev/null -w "%{http_code}\n"
401
istio-1.3.3$ curl $INGRESS_HOST/hello -s -o /dev/null -w "%{http_code}\n"
401
istio-1.3.3$ curl $INGRESS_HOST/hello -s -o /dev/null -w "%{http_code}\n"
401
istio-1.3.3$ curl $INGRESS_HOST/hello -s -o /dev/null -w "%{http_code}\n"
401
istio-1.3.3$ curl $INGRESS_HOST/hello -s -o /dev/null -w "%{http_code}\n"
401
istio-1.3.3$ curl $INGRESS_HOST/hello -s -o /dev/null -w "%{http_code}\n"
401
istio-1.3.3$ curl $INGRESS_HOST/hello -s -o /dev/null -w "%{http_code}\n"
401
istio-1.3.3$ curl $INGRESS_HOST/hello -s -o /dev/null -w "%{http_code}\n"
401
istio-1.3.3$ TOKEN=$(curl https://raw.githubusercontent.com/istio/istio/release-1.3/security/tools/jwt/samples/demo.jwt -s)
istio-1.3.3$ curl --header "Authorization: Bearer $TOKEN" $INGRESS_HOST/hello -s -o /dev/null -w "%{http_code}\n"
200
istio-1.3.3$ curl --header "Authorization: Bearer $TOKEN" $INGRESS_HOST/hello -s -o /dev/null -w "%{http_code}\n"
200
`
