### ISSUE TITLE
Add proxyLogLevel in ProxyConfig 

### ISSUE THREAD

**Issue by x15zhang** [istio/istio#17486]
Istio proxy set default proxyLogLevel as warning as following:
_Envoy command: [-c /etc/istio/proxy/envoy-rev0.json --restart-epoch 0 --drain-time-s 45 --parent-shutdown-time-s 60 --service-cluster resmgmt.mmc --service-node sidecar~172.16.23.26XXXXX --max-obj-name-len 189 --allow-unknown-fields **-l **warning**** --concurrency 2]_

When debug istio-proxy startup problem,I need to set the proxyLogLevel as trace or debug level,but istio or istio-injector configmap has no related parameter to set. It is not convenient.

**Comment by howardjohn** [comment]
These are in the injection template: https://github.com/istio/istio/blob/e4f1f0fdbb2e8e7c70078931e235bd26c5e93ad8/install/kubernetes/helm/istio/files/injection-template.yaml#L119-L124

You can also set this at runtime with `curl localhost:15000/logging?level=debug`
