### ISSUE TITLE
TestReachability Case is failed after switched to distroless image

### ISSUE THREAD

**Issue by clyang82** [istio/istio#17484]
**Bug description**

There should have an issue for distroless image  that cannot pass the TestReachability case in istio/installer repo:

context.go:78: failed waiting for Envoy configuration: timeout while waiting (last error: failed exec on pod reachability-1-86770/a-v1-549ffcd8c6-cln5x: exit status 1. Command: curl http://127.0.0.1:15000/config_dump. Output:
        ). Last config_dump:
        nil

the distroless image is not allowed running `exec` command.

FYI @howardjohn 

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[X] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
If we need this before #17283 merges, just cherrypick the change from curl -> pilot-agent GET https://github.com/istio/istio/pull/17283/files/20cdf51d8e7831e6663673646cfbe314df0f4365#diff-ced5f4753371264133324345c3dd722f

I also updated istio.io to not use `curl`

**Comment by howardjohn** [comment]
fixed by above pr
