### ISSUE TITLE
Gateway works as wildcard even if it's not defined like that way

### ISSUE THREAD

**Issue by rnkhouse** [istio/istio#17498]
**Bug description**:
I have 2 domains in different gateway 1) example.com 2) api.example.com

**Website gateway**:

    	---
	apiVersion: networking.istio.io/v1alpha3
	kind: Gateway
	metadata:
	 name: example.com
	spec:
	  selector:
	    istio: ingressgateway # Use Istio default gateway implementation
	  servers:
	  - port:
	      name: example-http-80 # This must be unique
	      number: 80
	      protocol: HTTP
	    hosts:
	    - "example.com"
	    tls:
	      httpsRedirect: true # sends 301 redirect for http requests
	  - port:
	      name: example-https-443 # This must be unique
	      number: 443
	      protocol: HTTPS
	    tls:
	      credentialName: example-crt # The certificate name you created above
	      mode: SIMPLE
	      #privateKey: sds
	      #serverCertificate: sds
	    hosts:
	    - "example.com"

**API gateway**:

    	---
	apiVersion: networking.istio.io/v1alpha3
	kind: Gateway
	metadata:
	 name: api.example.com
	spec:
	  selector:
	    istio: ingressgateway # Use Istio default gateway implementation
	  servers:
	  - port:
	      name: api-example-http-80 # This must be unique
	      number: 80
	      protocol: HTTP
	    hosts:
	    - "api.example.com"
	    tls:
	      httpsRedirect: true # sends 301 redirect for http requests
	  - port:
	      name: api-example-https-443 # This must be unique
	      number: 443
	      protocol: HTTPS
	    tls:
	      credentialName: api-example-crt # The certificate name you created above
	      mode: SIMPLE
	      #privateKey: sds
	      #serverCertificate: sds
	    hosts:
	    - "api.example.com"

**Affected product area (please put an X in all that apply)**

[x] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
It should point to appropriate domains. But, when I try to access `api.example.com` I am getting `404-not found` when I delete `example.com` gateway then I can access `api.example.com` service. It looks like when `example.com` gateway is there it also tries to send api requests thru this gateway which is incorrect.

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
kubernetes version: v.1.12.4
istio version: v.1.2.6

**How was Istio installed?**
helm template

**Environment where bug was observed (cloud vendor, OS, etc)**
AKS

**Comment by rnkhouse** [comment]
So, I had wildcard domains in the certificate issued from `letsencrypt`. It worked when I removed and put simple domain name. But, `istio` should only rely on gateway configurations. However, when I tested with `letsencrypt-staging` with wildcard certificates everything works normally.

**Comment by incfly** [comment]
I can't reproduce this issue, with istio.io docs as https://istio.io/docs/tasks/traffic-management/ingress/secure-ingress-sds/, for the multi host section. I tweaked the credential for the example.com to use `*.example.com` as common name as the certificate. curl request against helloworld still works. Following gist has the content of the keycert, gateway configuration, virtual service I'm using.

https://gist.github.com/incfly/95ce8c4a4bbc28b63dc5bde332fb2e98

**Comment by incfly** [comment]
Plus you get 404 error, I suspect this is a error of your reconfiguration of the routing, virtual service. The gateway CRD looks fine.
