### ISSUE TITLE
 pods fails to deploy on node restart with  istio side-car injector

### ISSUE THREAD

**Issue by dkalani** [istio/istio#17497]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

We have istio 1.3 deployed on our SAAS (running on EKS) and have been testing a few failover scenarios. If we restart the node that has the side-car injector service some of the applications pods fail to get re-deploy after that.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

pods are expected to come up and sidecars should establish connection with pilot.

**Steps to reproduce the bug**
restart the node which has side-car injector service. 

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

kubectl --context arn:aws:eks:us-west-2:966591598624:cluster/prod-1 version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-19T13:57:45Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.10-eks-5ac0f1", GitCommit:"5ac0f1d9ab2c254ea2b0ce3534fd72932094c6e1", GitTreeState:"clean", BuildDate:"2019-08-20T22:39:46Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

EKS as well as a kubernetes cluster deployed on aws. ( we use kops for that).

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

LAST SEEN   TYPE      REASON                   KIND                    MESSAGE
49m         Normal    Scheduled                Pod                     Successfully assigned ekstst001exampleweb4820ca580155c358a11b8de5c106e43d/allspark-ca-v0.2.7-7748b8bb54-slm87 to ip-192-168-47-212.us-west-2.compute.internal
49m         Normal    Pulled                   Pod                     Container image "docker.io/istio/proxy_init:1.3.0" already present on machine
49m         Normal    Created                  Pod                     Created container
49m         Normal    Started                  Pod                     Started container
49m         Normal    Pulling                  Pod                     pulling image "284299419820.dkr.ecr.us-west-2.amazonaws.com/allspark-ca:v0.2.7"
48m         Normal    Pulled                   Pod                     Successfully pulled image "284299419820.dkr.ecr.us-west-2.amazonaws.com/allspark-ca:v0.2.7"
48m         Normal    Created                  Pod                     Created container
48m         Normal    Started                  Pod                     Started container
49m         Normal    Pulled                   Pod                     Container image "docker.io/istio/proxyv2:1.3.0" already present on machine
49m         Normal    Created                  Pod                     Created container
49m         Normal    Started                  Pod                     Started container
49m         Normal    SuccessfulCreate         ReplicaSet              Created pod: allspark-ca-v0.2.7-7748b8bb54-slm87
49m         Normal    ScalingReplicaSet        Deployment              Scaled up replica set allspark-ca-v0.2.7-7748b8bb54 to 1
49m         Normal    Scheduled                Pod                     Successfully assigned ekstst001exampleweb4820ca580155c358a11b8de5c106e43d/connectivity-manager-v1.1.0-557856f55b-8x6g9 to ip-192-168-4-2.us-west-2.compute.internal
49m         Normal    Pulling                  Pod                     pulling image "docker.io/istio/proxy_init:1.3.0"
49m         Normal    Pulled                   Pod                     Successfully pulled image "docker.io/istio/proxy_init:1.3.0"
49m         Normal    Created                  Pod                     Created container
49m         Normal    Started                  Pod                     Started container
48m         Normal    Pulling                  Pod                     pulling image "284299419820.dkr.ecr.us-west-2.amazonaws.com/connectivity-manager:v1.1.0"
48m         Normal    Pulled                   Pod                     Successfully pulled image "284299419820.dkr.ecr.us-west-2.amazonaws.com/connectivity-manager:v1.1.0"
48m         Normal    Created                  Pod                     Created container
48m         Normal    Started                  Pod                     Started container
49m         Normal    Pulled                   Pod                     Container image "docker.io/istio/proxyv2:1.3.0" already present on machine
49m         Normal    Created                  Pod                     Created container
49m         Normal    Started                  Pod                     Started container
48m         Warning   BackOff                  Pod                     Back-off restarting failed container
49m         Normal    SuccessfulCreate         ReplicaSet              Created pod: connectivity-manager-v1.1.0-557856f55b-8x6g9
28m         Warning   FailedCreate             ReplicaSet              Error creating: Internal error occurred: failed calling webhook "sidecar-injector.istio.io": Post https://istio-sidecar-injector.istio-system.svc:443/inject?timeout=30s: context deadline exceeded (Client.Timeout exceeded while awaiting headers)
34m         Warning   FailedCreate             ReplicaSet              Error creating: Internal error occurred: failed calling webhook "sidecar-injector.istio.io": Post https://istio-sidecar-injector.istio-system.svc:443/inject?timeout=30s: context deadline exceeded
31m         Warning   FailedCreate             ReplicaSet              Error creating: Internal error occurred: failed calling webhook "sidecar-injector.istio.io": Post https://istio-sidecar-injector.istio-system.svc:443/inject?timeout=30s: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
27m         Warning   FailedCreate             ReplicaSet              Error creating: the server was unable to return a response in the time allotted, but may still be processing the request (post pods)
49m         Normal    ScalingReplicaSet        Deployment              Scaled up replica set connectivity-manager-v1.1.0-557856f55b to 1

**Comment by howardjohn** [comment]
Does the injector pod go down? It is expected pods cannot deploy if there is no injector pod, but the injector pod should have a pod disruption budget to avoid going down to zero replicas I thought?

**Comment by dkalani** [comment]
yes, it does go down and gets redeployed on another node.

replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

this is what we have in our config, should it be any different?

**Comment by howardjohn** [comment]
I thought we had a pod disruption budget turned on by default, is that not the case?

**Comment by dkalani** [comment]
yea, and here are the default values...

apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: istio-sidecar-injector
  namespace: istio-system
  labels:
    app: sidecarInjectorWebhook
    release: istio
    istio: sidecar-injector
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sidecarInjectorWebhook
      release: istio
      istio: sidecar-injector

**Comment by dkalani** [comment]
We experiment more today and see that even if we set replicateset to 2 this problem persists. 

@howardjohn let us know if you need more info

**Comment by howardjohn** [comment]
I think there was a kubernetes bug, something along the lines of using stale endpoints for the webhook, so it tries to contact the one that was deleted? I will try to send the link tomorrow - on phone right. @morvencao was looking into it I think?

**Comment by morvencao** [comment]
@dkalani We have more discussion about this at: https://github.com/istio/istio/issues/13840, it's caused by an upstream issue of kubernetes: kubernetes/kubernetes#80313

**Comment by howardjohn** [comment]
Close as tracked in https://github.com/istio/istio/issues/13840
