### ISSUE TITLE
Mirroring GRPC test flakes

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#17496]
Some failures:
https://prow.k8s.io/view/gcs/istio-prow/logs/integ-k8s-113_istio_postsubmit/183
https://prow.k8s.io/view/gcs/istio-prow/logs/integ-k8s-112_istio_postsubmit/124
https://prow.k8s.io/view/gcs/istio-prow/logs/integ-k8s-112_istio_postsubmit/125
https://prow.k8s.io/view/gcs/istio-prow/logs/integ-pilot-k8s-tests_istio_postsubmit/182
https://prow.k8s.io/view/gcs/istio-prow/logs/integ-pilot-k8s-tests_istio_postsubmit/178

**Comment by jwendell** [comment]
That's weird, all of them passes locally.

Also, the error is very strange...
`failed calling a->'grpc://b:7070/': rpc error: code = DeadlineExceeded desc = context deadline exceeded`

@howardjohn what do you think of trying 2 or 3 times before actually failing the test?

**Comment by howardjohn** [comment]
@jwendell seems like a good idea, a lot of our tests have this.
