### ISSUE TITLE
Analyzer for no matching workload for gateway selector

### ISSUE THREAD

**Issue by sushicw** [istio/istio#17506]
Kiali implementation: https://www.kiali.io/documentation/validations/#_no_matching_workload_found_for_gateway_selector_in_this_namespace

**Comment by xeviknal** [comment]
Perhaps I am misunderstanding something. Isn't this validation covered in the [gateway analyzer](https://github.com/istio/istio/blob/master/galley/pkg/config/analysis/analyzers/gateway/gateway.go)?
I see that the analyzer checks if there are any pods matching the gateway selector and then reports an error in case there isn't any matching workload present. 

Again, perhaps missing a detail somewhere.

**Comment by sushicw** [comment]
You're right. I think I may have gotten this and https://www.kiali.io/documentation/validations/#_more_than_one_gateway_for_the_same_host_port_combination mixed up, and created an issue for the wrong one. :) An issue exists for the host/port combo now, so I'll close this one. Thanks for your sharp eye!
