### ISSUE TITLE
Analyzer for services in service roles

### ISSUE THREAD

**Issue by sushicw** [istio/istio#17509]
Verify that services referred to by service roles actually exist. (Need to be aware of prefix / wildcard matching)

Kiali implementation: https://www.kiali.io/documentation/validations/#_unable_to_find_all_the_defined_services

(Also see https://www.kiali.io/documentation/validations/#_servicerole_can_only_point_to_current_namespace: should this be called out directly, or just covered implicitly?)

**Comment by xeviknal** [comment]
@sushicw do you think I can be assigned to this one?

**Comment by sushicw** [comment]
Go for it. (In the future, feel free to self-assign! :) )
