### ISSUE TITLE
Move bootstrap generation to init

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#17518]
Current pilot-agent will generate bootstrap config for each epoch. This doesn't really make sense because it is the same for each epoch - we can generate it once. Going a step further, we can put the generation as part of the init container. This would likely involve merging the proxy_init image and proxyv2 image, so we can do `iptables && pilot-agent bootstrap` or something similar.

Benefits
* 1 less docker image to manage
* 1 less docker image to pull
* 1 less thing to do when we restart envoy
* 1 step closer to removing pilot-agent - I think with just this change you could use upstream envoy (with turned off, sds turned on if you care about certs)

@nmittler

**Comment by kyessenov** [comment]
This is from the days when LDS did not exist and the agent was generating LDSes in the bootstrap. As long as we don't to generate different bootstraps, this sounds great.

**Comment by jwendell** [comment]
Would this affect CNI users? They don't have istio-init container already, nor run iptables...

**Comment by howardjohn** [comment]
Yes I realized this after writing... I think we can probably have a mode where pilot agent does `bootstrap && run` for those cases or do the bootstrap in the init and then run in the container - not sure if we can do that without much complexity.

I think we can slowly iterate on this and break stuff out and see what makes sense. We certainly can do bootstrap at startup instead of every time we hot restart, for example, then can combine the init and proxy image. That gives us pretty much all the benefits and makes it trivial to move it to the actual init container if we desire in the future

**Comment by kyessenov** [comment]
I think the key is moving bootstrap generation out of the responsibility of the agent. Then there are many choices where this bootstrap could be produced (pilot, injector, galley, all the way to the operator). It would be great to have a self contained tool that just generates bootstraps from istio APIs.

**Comment by nmittler** [comment]
Agreed. As a first pass, let's just get the creation of the bootstrap file out of `pkg/envoy/agent.go`. We can sort out a way to remove it from pilot_agent later.

**Comment by howardjohn** [comment]
related to https://github.com/istio/istio/issues/20772

**Comment by howardjohn** [comment]
I don't think this is relevant now

1 less docker image to manage - fixed, we have a single image
1 less docker image to pull - fixed
1 less thing to do when we restart envoy - no more hot restarts
1 step closer to removing pilot-agent - I think with just this change you could use upstream envoy (with turned off, sds turned on if you care about certs) - no longer a goal, we have a lot of logic in agent
