### ISSUE TITLE
Potential slow memory issues in istio-proxy

### ISSUE THREAD

**Issue by Stono** [istio/istio#17516]
**Bug description**
Please see the below graph which represents cluster wide istio-proxy memory usage since a 1.3.1 upgrade.

1.2.x was stable around 17.5GB, so this feels at first glance like a regression.

Note this is graphing `container_memory_usage_bytes`, which will count allocated heap even if unused.  @howardjohn mentioned to me that we don't cap the heap size for istio-proxy, as a side note i feel this should be done and correlated to the container memory request.  I've added some scrapes for `envoy_server_memory_allocated` and `envoy_server_memory_heap_size` for a handful of applications so will report on that in a few days.

I stumbled across this whilst investigating some random 504s that have started happening 2 days after the 1.3.x upgrade every 10 minutes or so.  Frustratingly restarting the applications resolved the problem.  I have _no_ idea how golang gc works, so it's likely anecdotal, but this felt similar to Java's GC pauses.  The `reporter=destination` reported the 504s, but the application itself was not logging any slow requests, further pointing the finger at the destination envoy.

<img width="1680" alt="Screenshot 2019-09-30 at 21 51 48" src="https://user-images.githubusercontent.com/1486729/65916083-9f7b4400-e3cc-11e9-8123-6377a03394b1.png">

There appears to be a correlation to qps, the top usage is on the applications processing the most traffic:

<img width="1680" alt="Screenshot 2019-09-30 at 22 04 52" src="https://user-images.githubusercontent.com/1486729/65917040-6ba11e00-e3ce-11e9-99b2-57c7739ae2f6.png">

There's some pretty big jumps in these apps which don't occur in the lower qps apps but I've reported that separately in https://github.com/istio/istio/issues/16188

I'm not sure what else I can do to help debug this.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[x] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Consistent memory usage

**Steps to reproduce the bug**
1.3.1+

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.3.1

**How was Istio installed?**
Helm

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by rshriram** [comment]
cc @lizan

**Comment by lambdai** [comment]
@Stono Could you generate the heap profile? Follow the instruction [here](https://github.com/istio/istio/wiki/Analyzing-Istio-Performance#memory-1)

Maybe you need to adjust the profiling duration since I feel the leak is slow

**Comment by howardjohn** [comment]
I need to update the profile docs -- found out it only works if you have the enableCoreDump helm set. I'll fix it up. @lambdai for leaks generally I just do it once and then later do it again and see what increased, is doing a long period better?

**Comment by Stono** [comment]
This may not be a concern, it seems to be stabalising out so maybe natural heap growth as all proxies were restarted as part of the upgrade.

If it doesn't breach 19G within the next day or two I'll close this as a non-issue.

<img width="1832" alt="Screenshot 2019-10-02 at 08 27 07" src="https://user-images.githubusercontent.com/1486729/66025464-7357e400-e4ee-11e9-9fe4-47c00b4e97d4.png">

**Comment by mandarjog** [comment]
@Stono any update here?

**Comment by Stono** [comment]
Hey really sorry, been really busy with the 504 issue.
Yes this looks like its stablised now:

<img width="1600" alt="Screenshot 2019-10-04 at 16 24 07" src="https://user-images.githubusercontent.com/1486729/66219606-6809e180-e6c3-11e9-91fe-25f4b3bd8f48.png">

I'll close this off!
