### ISSUE TITLE
Design & Implement generated documentation for structured validation messages

### ISSUE THREAD

**Issue by sushicw** [istio/istio#17520]
One design goal of using structured validation messages is to enable generating relevant and useful documentation. Using a canonical `messages.yaml` as the base, we can generate both code and documentation and make sure they are consistent with each other. 

We need to flesh this out into a concrete design proposal & implementation. 

A non-exhaustive list of things to consider:
* We will likely want to link to some human-written documentation (e.g. troubleshooting steps) as well as having purely generated documentation. 
* We need to figure out the end-to-end build flow that we expect. e.g. if we continue to use `go generate` on `messages.yaml` to produce code, then maybe we can extend it to produce documentation artifacts as well.

See [Multi-Object Validation In Galley & Command-Line](https://docs.google.com/document/d/1m19jkLyiIXNmUH_TYClRH-IOmuCJO4-vduy5KaCa99E/edit#heading=h.iabdzcbxutqg) and [Integrating multi-object validation and analysis in Istio](https://docs.google.com/document/d/1KuxDRPPt283jx_cIs2C9sFHjoHvoskJt3IGqhPJVHtM/edit#heading=h.7gpa62t27ug0) for more discussion of this.

**Comment by geeknoid** [comment]
https://github.com/istio/istio.io/pull/5096 and https://github.com/istio/istio/pull/17626 address this issue. Now all that's left is actually writing the per-message doc page.

**Comment by sushicw** [comment]
Created https://github.com/istio/istio/issues/18065 to track backfilling docs.

**Comment by sushicw** [comment]
The initial work here is done and we have it established as a practice to include docs for new analyzers. Closing this out.
