### ISSUE TITLE
Multiple ingress IPs

### ISSUE THREAD

**Issue by Stono** [istio/istio#1752]
Hi all, 
I'm relatively new to istio and currently trying out some more complex scenarios and can't figure out from the documentation of this scenario is supported - and would really like guidance.

At a very high level, I have an istio deployment setup with mutual-tls so when I deploy pods with istioctl, the sidecar transparently handles the mtls for me, which is wonderful.

However, there are certain pods that I still wish to be part of this mesh (so we get the logs, tracing etc), but **excluded** from inbound mtls, IE ingress communication to them does not require the certificates but egress traffic to other internal services does.

What this would facilitate is services that can be exposed on unique ingress IPs (in GKE world, services defined with Type:  LoadBalancer, or kubernetes Ingress types), as the model of a single ingress service to the mesh, and then using hostnames to separate to downstream services is not compatible for my use case.

It's hard to explain in words, so here is a simplistic diagram:

![meh](https://user-images.githubusercontent.com/1486729/32809917-bc4fbaf0-c990-11e7-8022-ca116aa4570e.png)

I suppose in summary, I want to be able to create multiple `Ingress` which are exposed on separate external IPs, rather than the IP of the istio-ingress service, so in this example i need app1 and app2 to have their own ip's and also not require client certificates.

```
❯ kubectl get services --namespace=istio-system istio-ingress
NAME            TYPE           CLUSTER-IP     EXTERNAL-IP      PORT(S)                      AGE
istio-ingress   LoadBalancer   10.176.18.23   35.205.189.139   80:31773/TCP,443:30088/TCP   7h

❯ kubectl get ingress
NAME           HOSTS     ADDRESS          PORTS     AGE
app1-ingress   *         35.205.189.139   80        4m
app2-ingress   *         35.205.189.139   80        4m
```

Anyone have any ideas?  
Thanks

**Comment by kyessenov** [comment]
cc @louiscryan for multiple gateways.

**Comment by Stono** [comment]
FYI I first thought that creating a service with an external IP and using `--includeIPRanges` would work, however as the clientIP is masked by the cluster service the sidecar still intercepts the ingress traffic and expects client certs.

**Comment by Stono** [comment]
Hey...
I'd really love some input on this because not because able to have services exposed on different IPs is a deal breaker for us.

**Comment by linsun** [comment]
I don't think we support this at the moment.  The closest is the SNI support which allows you to do it by host name.

**Comment by Stono** [comment]
This can be closed in favour of https://github.com/istio/istio/issues/3059 - we achieve this using the nginx ingress controller which more easily supports a setup of multiple ingress controllers.
