### ISSUE TITLE
Analyzer for service port prefix

### ISSUE THREAD

**Issue by sushicw** [istio/istio#17532]
istio-vet's implementation: https://github.com/aspenmesh/istio-vet/blob/master/pkg/vetter/serviceportprefix/README.md

This is single-object validation, but it's a case where we need a WARN level message (since the set of valid prefixes could change during upgrade). Since we need WARN level, it makes sense to build it as an analyzer at least for now.

**Comment by xeviknal** [comment]
I guess that this one is the same as the following one on Kiali: https://www.kiali.io/documentation/validations/#_port_name_must_follow_protocol_suffix_form

**Comment by sushicw** [comment]
Example of when this would be relevant: https://docs.google.com/document/d/1uJ2bbkj8t7V-NTXSfHHq7jGmq5KD1Jil3O6uhUZ4fCw/edit?ts=5dc4680b#heading=h.4jxi4a4dzrx6

**Comment by nrjpoddar** [comment]
This was implemented by https://github.com/istio/istio/pull/19375/, so closing this issue.
