### ISSUE TITLE
Analyzer for JWT Authentication policies targeting services with no label selectors

### ISSUE THREAD

**Issue by nrjpoddar** [istio/istio#17538]
More details are located [here](https://github.com/aspenmesh/istio-vet/issues/63)

**Comment by sushicw** [comment]
@nrjpoddar is this a duplicate of https://github.com/istio/istio/issues/17535? Can it be folded in?

**Comment by nrjpoddar** [comment]
@sushicw let's keep it separate for now but they will be under the umbrella of authentication policies. Keeping it separate just enforces multiple people possibly working on it and smaller PRs.

**Comment by sushicw** [comment]
@nrjpoddar Are you still planning to do this in the near future? If not, we can unassign you so it's available for others to pick up. 

Also: will this analyzer still be relevant after switching to the new authorization policy resource?
