### ISSUE TITLE
CircleCI/codecov.sh is consistently failing.

### ISSUE THREAD

**Issue by ozevren** [istio/istio#1753]

**Comment by ozevren** [comment]
https://circleci.com/gh/istio/istio/1479?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

The codecov.sh is consistently failing in CircleCI. I've been unable to glean any useful information at the moment.

**Comment by ozevren** [comment]
It looks like the failure is due to proto files going out of sync with the generated pb files.
@guptasu is working on changes to the build system to run regular go tools as part of Prow jobs. This should avoid this type of breakages in the future.

**Comment by geeknoid** [comment]
Can we close this?
