### ISSUE TITLE
503 UAEX “”UNAVAILABLE:upstream connect error or disconnect/reset before headers

### ISSUE THREAD

**Issue by satishsudini** [istio/istio#17539]
**Bug description**
When ServiceA connecting ServiceB we are seeing 503 UAEX “”UNAVAILABLE:upstream connect error or disconnect/reset before headers 

**Affected product area (please put an X in all that apply)**

[ ] Networking

**Steps to reproduce the bug**

Install istio 1.1.2 connect SvcA to SvcB using host and port .  

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Istio 1.1.2 

**How was Istio installed?**
Regular deployment not with helm

**Environment where bug was observed (cloud vendor, OS, etc)**
K8 version 1.13.4 

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
Please add more details. See https://github.com/istio/istio/wiki/Troubleshooting-Istio on how to collect this.

Without your config we have no way of debugging this
