### ISSUE TITLE
Add connect timeout to virtual services

### ISSUE THREAD

**Issue by aaronmell** [istio/istio#17531]
**Describe the feature request**
For external services, we would like to be able to control both the read timeout and the connect timeout. And those should be independent of each other. We have some services that are slow to return data, and in the event of a failure to connect, we don't want to hang all requests to the timeout. 

**Describe alternatives you've considered**
I think this might be possible with setting envoy configuration directly, not 100% sure on that. 

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
You can do connection timeout in Destination Rule https://istio.io/docs/reference/config/networking/v1alpha3/destination-rule/#ConnectionPoolSettings-TCPSettings
