### ISSUE TITLE
Analyzer for JWT policies targeting invalid services

### ISSUE THREAD

**Issue by sushicw** [istio/istio#17535]
istio-vet issue & implementation: 
https://github.com/aspenmesh/istio-vet/issues/62
https://github.com/aspenmesh/istio-vet/pull/65

**Comment by sushicw** [comment]
@nrjpoddar, this is currently assigned to you. Is it something you are currently working on?

**Comment by nrjpoddar** [comment]
Yes I will work on it next. Thanks for checking in!

**Comment by nrjpoddar** [comment]
@jacob-delgado will be working on this from Aspen Mesh. I cannot assign him the issue.

**Comment by jacob-delgado** [comment]
All work has been completed. It is now in 1.5 and istio 1.4.4.

**Comment by esnible** [comment]
Closing because @jacob-delgado says the work is complete and merged.
