### ISSUE TITLE
JWT validation fails forever if public key retrieval fails

### ISSUE THREAD

**Issue by theganyo** [istio/istio#17541]
**Bug description**

If the retrieval of the public key fails when applying an authentication policy - for example, when the network is down, JWT validation will be applied on the affected pod but will fail forever on that pod.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

I would expect the pod to eventually get the certificate and start working.

**Steps to reproduce the bug**

1. Install Istio
2. Install httpbin & gateway from samples
3. Turn off network
4. Apply an authentication policy for origins/jwt
5. Verify can't access httpbin via curl
6. Enable network
7. Wait... or don't
8. Verify can't access httpbin via curl w/ a valid JWT 

Note: If you kill the pod at this point, the new pod will get a cert and verify the JWT.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

$ istioctl version --remote
client version: 1.3.1
control plane version: 1.3.1

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:47:22Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**

kubectl  apply -f $ISTIO/install/kubernetes/istio-demo.yaml

**Environment where bug was observed (cloud vendor, OS, etc)**

MacOS 10.14.6
Docker Desktop 2.1.0.3

**Comment by pitlv2109** [comment]
Pilot tries fetching the public key N times, but I don't remember if after a while, it'll trigger the retry login again or not. https://github.com/istio/istio/blob/a6e26c7e681dbb1fef8930bcd74ca8fa328685d9/pilot/pkg/model/jwks_resolver.go#L312

**Comment by theganyo** [comment]
It seems to me that it’s a refresh problem in the sidecar.

**Comment by pitlv2109** [comment]
FYI I don't think @yangminzhu is able to look at this any time soon, but we can keep this one open.

**Comment by incfly** [comment]
@yangminzhu is this still valid concern given 1.5 impl? I will be surprised that faiure of fetching public key will make the istiod pushing invalid configuration causing the sidecar validation failure?
