### ISSUE TITLE
operator - unclear which component fields should be `--set` from

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#17545]
Using the operator, I want to the set the outboundTrafficPolicy. In helm this is `--set global.outboundTrafficPolicy.mode=REGISTRY_ONLY`

Attempts in the operator:
```
$ ik x manifest generate --set global.outboundTrafficPolicy.mode=REGISTRY_ONLY
bad path=value: global.outboundTrafficPolicy.mode=REGISTRY_ONLY
$ ik x manifest generate --set values.outboundTrafficPolicy.mode=REGISTRY_ONLY | grep ALLOW_ANY
      mode: ALLOW_ANY  # The overlay did not do anything
$ ik x manifest generate --set trafficManagement.components.pilot.values.outboundTrafficPolicy.mode=REGISTRY_ONLY
bad path=value: trafficManagement.components.pilot.values.outboundTrafficPolicy.mode=REGISTRY_ONLY
```

Its not clear to me what the expected behavior is and what I am doing wrong. Not sure if this is a bug or docs/UX issue

**Comment by ostromart** [comment]
Since you're accessing the values field in the IstioControlPlaneSpec API, it should be 
ik x manifest generate --set values.global.outboundTrafficPolicy.mode=REGISTRY_ONLY
Give that a shot @howardjohn.

**Comment by howardjohn** [comment]
ahh `.values.global`, I think thats the one combination I didn't try. That seems to work. Thanks
