### ISSUE TITLE
Operator CLI spams local folders with .mesh-cli.log files everywhere

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#17546]
I played around for a bit with the operator and found about 15 .mesh-cli.log files spread about my local filesystem. This is pretty unfriendly. I think it would make more sense to just have everything output to stdout and add a `--verbose` or `--loglevel` flag to control how much stuff we log.

**Comment by esnible** [comment]
If we do need a secret log, would it make more sense to put it in ~/.mesh-cli.log instead of in the current directory?

Also if it must go in the current directory can we add it to .gitignore?

**Comment by howardjohn** [comment]
Lets not just hide the problem by adding it to .gitignore. users will run this all over the place. Its a horrible UX to play around with istioctl then find out all your folders have a bunch of garbage in them. ~/.mesh-cli.log sounds reasonable, but I am not sure if a log file is even needed at all?

**Comment by ostromart** [comment]
Originally it was appending everything for post-mortems of issues that could easily be reproduced. Realistically, CLI bugs tend to be easy to reproduce so this does indeed have limited value and should be removed.

**Comment by ostromart** [comment]
Fixed in https://github.com/istio/operator/pull/417.
