### ISSUE TITLE
Cancelled http requests are reported with http status code 500 in prometheus

### ISSUE THREAD

**Issue by tgunsch** [istio/istio#17556]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
If an HTTP request is cancelled/aborted on client side, the request is reported with http status code 500 in mixer / prometheus (which is a server status code).

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ X] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
HTTP requests cancelled by client, should be reported with 4xx status code, to distinguish them from "real" server failures.

**Steps to reproduce the bug**
See example code and description on https://github.com/tgunsch/istio-cancel-request

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
client version: 1.2.5
citadel version: 1.2.4
galley version: 1.2.4
ingressgateway version: 1.2.4
pilot version: 1.2.4
policy version: 1.2.4
sidecar-injector version: 1.2.4

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.4", GitCommit:"a87e9a978f65a8303aa9467537aa59c18122cbf9", GitTreeState:"clean", BuildDate:"2019-07-08T08:51:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.5", GitCommit:"0e9fcb426b100a2aea5ed5c25b3d8cfbb01a8acf", GitTreeState:"clean", BuildDate:"2019-08-05T09:13:08Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
Installed with helm

**Environment where bug was observed (cloud vendor, OS, etc)**
Ubuntu 19.04 

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
Seems like this is probably just something Envoy is doing, would be nice to confirm if this needs work in Envoy or if we need to configure differently

**Comment by tgunsch** [comment]
FYI: Just found an older issue describing the same: https://github.com/istio/istio/issues/9292. We solves this as described there by using `conditional(context.proxy_error_code == "DC", 499, response.code | 0)` in our log instance.

**Comment by Stono** [comment]
Hey, @howardjohn could we perhaps re-open this?

It's causing me a bit of a headache too but i'm not sure on the best source of action.  It'd be nice if this scenario wasn't a 500 code, but a 499 is "nginx specific", technically, but is the most relevant to the scenario.

**Comment by Stono** [comment]
FYI we've taken the action of adjusting our 5xx alerts, and dashboards to exclude `response_flags!="DC"`
