### ISSUE TITLE
GRPC support with certmanager and letsencrypt

### ISSUE THREAD

**Issue by unludo** [istio/istio#17555]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

There is documentation to manage https istio ingress with letsencrypt
[Kubernetes Ingress with Cert-Manager](https://istio.io/docs/tasks/traffic-management/ingress/ingress-certmgr/#getting-a-let-s-encrypt-certificate-issued-using-cert-manager)

**Describe alternatives you've considered**

What would be useful for people using GRPC externally, would be the same but for GRPC.

I am not sure how to do it in GKE as HTTP2 loadbalancers requires health probes in HTTP (there are solutions on the net)

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

thanks!

**Comment by howardjohn** [comment]
grpc is just http, which should work with the example above I would think? What specifically is missing?

**Comment by unludo** [comment]
Grpc is http2 and by default it does not work like https in GKE.

You may see some details [here](https://github.com/kubernetes/ingress-gce/issues/18)

[This](https://github.com/salrashid123/gcegrpc/tree/master/gke_ingress_lb) shows how to manage it with envoy.

I believe the pure Istio solution will face the same problems as the Istio ingress creates a GCP  L7 LB which has some issues as stated in the mentioned posts.
