### ISSUE TITLE
Inconsistent http.url reported in Jaeger traces

### ISSUE THREAD

**Issue by Stono** [istio/istio#17553]
**Bug description**
All of our applications are configured and deployed using the same helm template.  We have mTLS globally enabled and there are no exceptions, however, we see a variety of different prefixes in Jaeger traces.

`http,http://`:
<img width="776" alt="Screenshot 2019-10-02 at 08 49 11" src="https://user-images.githubusercontent.com/1486729/66027117-237b1c00-e4f2-11e9-944f-5d67c42473a9.png">

`https://`:
<img width="560" alt="Screenshot 2019-10-02 at 08 56 09" src="https://user-images.githubusercontent.com/1486729/66027304-810f6880-e4f2-11e9-910b-2062a573776a.png">

`http://`
<img width="788" alt="Screenshot 2019-10-02 at 08 52 34" src="https://user-images.githubusercontent.com/1486729/66027119-237b1c00-e4f2-11e9-9fa2-a6834adebcc0.png">

Any ideas what is going on here?

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
I would expect them all to be `http://app.service-name` as that's the short formed url they all use.

**Steps to reproduce the bug**
No idea

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.3.1

**How was Istio installed?**
Helm

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by objectiser** [comment]
@Stono As this might be difficult to reproduce, would it be possible to switch the backend to zipkin and see whether the same issues occur? This would help us narrow down whether in Jaeger or Envoy?

**Comment by Stono** [comment]
Hey @objectiser - I'm confused, I thought istio is just using zipkin by default? `global.proxy.tracer` in the installation options to `zipkin`?  

Am I missing something?

**Comment by objectiser** [comment]
@Stono Correct - the tracer running in Envoy proxy is zipkin, sending the data to the Jaeger backend. I don't believe there is anything in the Jaeger backend that would modify the `http.url` tag received via the zipkin compatible endpoint provided by Jaeger, but wanted to confirm one way or the other, that the issue is in the Envoy proxy.

**Comment by douglas-reid** [comment]
@Stono @objectiser it looks like this is the relevant code?

https://github.com/envoyproxy/envoy/blob/a36c4684f235fdcabfd12fafae697e7d7f777b57/source/common/tracing/http_tracer_impl.cc#L30-L42

@Stono is it possible each app is doing slightly different things re: headers (perhaps set by different client libraries)?

**Comment by Stono** [comment]
Hey @douglas-reid that is entirely possible, our app estate comprises pretty much every version of every package from every language 😆

**Comment by objectiser** [comment]
@Stono Are the services consistent in the url they report? i.e. does `carzone-web-frontend` always report with `http,http`? If so, any chance of a simple reproducer?

**Comment by Stono** [comment]
Leave it with me and I’ll try and do some digging this week!

**Comment by Stono** [comment]
helloooo please could we reopen this 3 year old bug? :D 
I was confused by this again, googled around and found my own issue haha.

There's a few weird things going on.

<img width="644" alt="Screenshot 2023-07-30 at 21 28 42" src="https://github.com/istio/istio/assets/1486729/646a72e6-5848-4f87-89b7-e3c122f95d45">

Taking these examples, if i dump the incoming requests out I see:

on the ones being logged as https:
```
app.unified-registration-system.svc.cluster.local:
 - :path: /service/1.0/res...
 - :method: GET
 - :scheme: https
 - x-forwarded-proto: https
 - x-forwarded-scheme: https
 - x-scheme: https
 - x-envoy-decorator-operation: app.unified-registration-system.svc.cluster.local:80/*
```

on the ones being logged as http:
```
app.unified-registration-system.svc.cluster.local:
 - :path: /service/1.0/res....
 - :method: GET
 - :scheme: http
 - x-envoy-decorator-operation: app.unified-registration-system.svc.cluster.local:80/*
```

which i think lines up with the code in https://github.com/envoyproxy/envoy/blob/a36c4684f235fdcabfd12fafae697e7d7f777b57/source/common/tracing/http_tracer_impl.cc#L30-L42, which is looking at the forwarded headers.

For the purpose of the trace though, and recording a span, surely it doesn't make sense to use the forwarded headers?  Ultimately this request was made to `http://app.unified-registration-system.svc.cluster.local`.  The fact it had a x-forwarded-proto of https is moot?

And then an extension of this is where some apps use the short form url, and others use long form, eg `app.unified-registration-system` vs `app.unified-registration-system.svc.cluster.local`, that again results in a different `tag.http@url`. 

My VirtualService looks like this:
```
    - destination:
        host: app.unified-registration-system.svc.cluster.local
        port:
          number: 80
```

So really i'd expect the incoming host to always be the fully qualified address?

Ultimately to summarise the issue what i'm craving here is consistency in traces.  i think the recorded `tag.http@url` should be what the client used to make the request, the scheme would be http, and the host should be fully qualified.  The reason I would like this is because users search using `tag.http@url`, and having it 3 different ways is just confusing!.

cc. @howardjohn could you reopen please?

**Comment by Stono** [comment]
Yeah so just to confirm if you set `x-forwarded-proto: https`, you get `:scheme: https` on the inbound request which logs as `https` in jaeger.
