### ISSUE TITLE
Flaky TestWorkloadAgentGenerateSecret test failure

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#17568]
Example: https://prow.k8s.io/view/gcs/istio-prow/logs/racetest_istio_postsubmit/206

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/17571/racetest_istio/1360

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gcs/istio-prow/logs/unit-tests_istio_postsubmit/721

**Comment by JimmyCYJ** [comment]
@pitlv2109 since you made test improvements to this test [PR](https://github.com/istio/istio/pull/15144), could you fix this test?

**Comment by howardjohn** [comment]
Still flaky?: https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/20248/unit-tests_istio/6734

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/20346/unit-tests_istio/6943

**Comment by JimmyCYJ** [comment]
https://github.com/istio/istio/pull/20433 has fixed this issue. It is not flaky after that.
