### ISSUE TITLE
Vault flow disabled since 1.3

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#17561]
Example failures: 

https://prow.k8s.io/view/gcs/istio-prow/logs/integ-k8s-116_istio_postsubmit/206
https://prow.k8s.io/view/gcs/istio-prow/logs/integ-k8s-114_istio_postsubmit/201

unfortunately seems like we aren't getting logs dumped properly here.. not sure why.

**Comment by howardjohn** [comment]
Found it! https://prow.k8s.io/view/gcs/istio-prow/logs/integ-security-k8s-tests_istio_postsubmit/202
Logs: https://storage.googleapis.com/istio-prow/logs/integ-security-k8s-tests_istio_postsubmit/202/artifacts/sds-vault-flow-test-99fe695d2e0/_suite_context/istio-state-371262463/istio-ingressgateway-797d9b44b4-822c8-istio-proxy.log
https://storage.googleapis.com/istio-prow/logs/integ-security-k8s-tests_istio_postsubmit/202/artifacts/sds-vault-flow-test-99fe695d2e0/_suite_context/istio-state-933436192/istio-ingressgateway-797d9b44b4-822c8-istio-proxy.log

**Comment by howardjohn** [comment]
https://prow.k8s.io/view/gcs/istio-prow/logs/integ-k8s-113_istio_postsubmit/204

**Comment by pitlv2109** [comment]
We turned off "support" for Vault since Istio 1.3.

**Comment by lei-tang** [comment]
ingress-gateway has a different SDS flow (compared with workload sidecar) in which node agent fetches a certificate from k8s secret. sds_vault_flow test deploys on workload sidecar, not ingress gateway.

**Comment by howardjohn** [comment]
> ingress-gateway has a different SDS flow (compared with workload sidecar) in which node agent fetches a certificate from k8s secret. sds_vault_flow test deploys on workload sidecar, not ingress gateway.

I am not sure what you mean, the logs look like ingressgateway is trying to talk to vault?

```
[2019-10-02 13:25:26.708][64][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:87] gRPC config stream closed: 2, failed to login Vault at https://34.83.129.211:8200: Error making API request.

URL: PUT https://34.83.129.211:8200/v1/auth/kubernetes/login
Code: 500. Errors:

* claim "iss" is invalid
```

**Comment by lei-tang** [comment]
Per offline discussion, a PR is created to disable this test for Istio 1.3: https://github.com/istio/istio/pull/17571

**Comment by incfly** [comment]
issue  is about test failure, closing
