### ISSUE TITLE
Support Vault integration in Istio 1.3

### ISSUE THREAD

**Issue by lei-tang** [istio/istio#17572]
**Describe the feature request**
Before Istio 1.3, Istio uses normal k8s JWT in its SDS flows. 
Istio 1.3 uses Trustworthy JWT, which, unlike normal k8s JWT, is not recognized on Vault.

**Describe alternatives you've considered**
Provide a flag in Istio 1.3 to choose whether using Trustworthy JWT or using normal k8s JWT. 

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ X] Security
[ ] Test and Release
[X ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by nixgadget** [comment]
@lie-tang is trustworthy JWT supported in 1.2 ?

**Comment by pitlv2109** [comment]
How will turning off trustworth JWT enable support for Vault? Trustworthy JWT is a mechanism to securely create and store jwt. Vault is a CA. They are not related to each other. Surely, using trustworthy JWT affects the Vault task on istio.io, but that task is just a simple toy example. Do we really expect users to run every service with the same identity? 

cc @myidpt @costinm

**Comment by lei-tang** [comment]
@nixgadget Istio 1.2 uses normal k8s JWT.

**Comment by lei-tang** [comment]
This issue is not created to turn off trustworthy JWT. Under the section "Describe alternatives you've considered": Providing a flag in Istio 1.3 to choose whether using Trustworthy JWT or using normal k8s JWT is an alternative to keep the support of Vault integration (Istio 1.2 and 1.1 use normal k8s JWT and support Vault integration).
The task on istio.io provides an example that uses a k8s JWT for authentication, but it does not mean all services must use the same JWT for authentication: an user may configure multiple JWTs on Vault for issuing certificates with different identities and a service may use its own JWT to request a certificate.

**Comment by rvasilevsf** [comment]
@lei-tang trustworthy JWT support is now available under Vault 1.3.1 - https://github.com/hashicorp/vault/pull/7968#issuecomment-566581920

**Comment by lei-tang** [comment]
@rvasilevsf Thanks for the information!

**Comment by hobbytp** [comment]
@lei-tang So can I understand istio 1.3 or later release can support Vault integration (from Vault 1.3.1)?  If yes, when will the integration document ready? Thanks,

**Comment by lei-tang** [comment]
@hobbytp Since Istio 1.3 uses a new Kubernetes JWT, Istio Vault integration is no longer supported. We plan to add the support of Vault integration to Istio (the timeline is to be determined).

**Comment by lei-tang** [comment]
This issue is closed. A new issue https://github.com/istio/istio/issues/21961 is created to track the Istio Vault integration. Please feel free to share your use cases for Vault integration https://github.com/istio/istio/issues/21961. We hope to collect use cases of Vault integration and provide a solution meeting the requirements of representative use cases.
