### ISSUE TITLE
Move values_types.proto into same repo as charts

### ISSUE THREAD

**Issue by ostromart** [istio/istio#17579]
https://github.com/istio/operator/blob/master/pkg/apis/istio/v1alpha1/values_types.proto
It makes more sense to have this in istio/installer since any changes to the charts should:
1. be accompanied with corresponding changes to the proto, if required
2. pass presubmit checks against the proto schema

**Comment by ostromart** [comment]
Relabeling this to reflect the possibility of merging installer and operator.

**Comment by howardjohn** [comment]
dupe of https://github.com/istio/istio/issues/19146
