### ISSUE TITLE
Add all sets of configurations in benchmark job for centralized perf tool

### ISSUE THREAD

**Issue by carolynhu** [istio/istio#17585]
Here is a list of benchmark configurations we want to add for our perf-tool benchmark running job:

- [x]  Increase the number `qps` with fixed number of `conn` to gather `cpu` and `mem` data (with mixer enabled)

- [x] Increase the number `conn` with fixed number of `qps` to gather `p50`, `p90` and `p99` data (with mixer enabled)

- [x] flame graphs

- [x] disable mixer, then gather data for `cpu`, `mem`, `p50`, `p90` and `p99`

- [x] TelemetryV2

Other related things need to do: 

- [x] We need to organize and save all those corresponding `.csv` and `.png`/.`svg` files.

- [x] Later on we may want those performance settings are configurable by users.

- [x] Measure those performance benchmarks with Linkerd

- [ ] Long-running tests with large topology.

**Comment by richardwxn** [comment]
PR created: https://github.com/istio/tools/pull/414

**Comment by carolynhu** [comment]
Further optimization:  passing configuration parameters to different perf jobs with the same underlying run_per_job.sh, then each configuration set can be triggered and run separately.

**Comment by carolynhu** [comment]
Update about periodic jobs:
(1) Currently we have two periodic jobs: one for master, one for the current release. Each job run about 7 hours and take up one cluster. 
(2) another way: we run say five periodic jobs for both mater and release (total is 10), then, we need  10 clusters. If we run in the same cluster with different namespaces (the default namespace is twopods). it's fine that we define 5 different namespaces, but the collected data is unevenly. (We do not want to employ this way now).
(3) when publishing new perf data, we are going to run periodic jobs for several days, to avoid noise/variance data.
