### ISSUE TITLE
Incoming Request logs are not observable at istio-proxy[Envoy] logs

### ISSUE THREAD

**Issue by VinothChinnadurai** [istio/istio#17587]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
Traffic to the application is not observable at istio-proxy[envoy] level logs. We also would like to hear how to configure customized logs
**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
It should print all incoming traffic to the application
**Steps to reproduce the bug**
1. Installed Istio through the following command
 `helm template \
  --set gateways.istio-ingressgateway.type=NodePort \
  --set prometheus.enabled=true \
  --set grafana.enabled=true \
  --set tracing.enabled=true \
  --set kiali.enabled=true \
  --set "kiali.dashboard.jaegerURL=http://jaeger-query:16686" \
  --set "kiali.dashboard.grafanaURL=http://grafana:3000" \
   install/kubernetes/helm/istio \
  --name istio --namespace istio-system > $HOME/istio.yaml`
2. Added Istio-injection enabled to the namespace where app was configured.
3. AWS ALB has been place in before the Istio Ingress gateway
4. Application successfully loading in the browser while hitting through ALB Url
5. To do debugging, enabled Istio-Proxy logging. I followed the below
`helm template install/kubernetes/helm/istio --namespace=istio-system -x templates/configmap.yaml --set global.proxy.accessLogFile="/dev/stdout" --set global.proxy. accessLogFormat =JSON  | kubectl replace -f -
kubectl logs -l app=appname -c istio-proxy

`
6. I got the below in the logs
`{"log":"{\"bytes_sent\":\"1474917\",\"upstream_cluster\":\"inbound|80||metadata-api-svc.development.svc.cluster.local\",\"downstream_remote_address\":\"10.142.192.200:46766\",\"authority\":\"-\",\"path\":\"-\",\"protocol\":\"-\",\"upstream_service_time\":\"-\",\"upstream_local_address\":\"127.0.0.1:33742\",\"duration\":\"63839\",\"downstream_local_address\":\"10.142.192.206:8080\",\"upstream_transport_failure_reason\":\"-\",\"response_code\":\"0\",\"user_agent\":\"-\",\"response_flags\":\"-\",\"start_time\":\"2019-10-01T12:37:38.183Z\",\"method\":\"-\",\"request_id\":\"-\",\"upstream_host\":\"127.0.0.1:8080\",\"x_forwarded_for\":\"-\",\"requested_server_name\":\"-\",\"bytes_received\":\"6450\",\"istio_policy_status\":\"-\"}\n","stream":"stdout","time":"2019-10-01T12:38:50.725306822Z"}`

7. I could not see logs specific to my request fired from the browser and would like to know why most fields(keys) have empty values.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
client version: 1.2.5
citadel version: 1.2.5
galley version: 1.2.5
ingressgateway version: 1.2.5
pilot version: 1.2.5
policy version: 1.2.5
sidecar-injector version: 1.2.5
telemetry version: 1.2.5

**How was Istio installed?**
Through helm
`helm template \
  --set gateways.istio-ingressgateway.type=NodePort \
  --set prometheus.enabled=true \
  --set grafana.enabled=true \
  --set tracing.enabled=true \
  --set kiali.enabled=true \
  --set "kiali.dashboard.jaegerURL=http://jaeger-query:16686" \
  --set "kiali.dashboard.grafanaURL=http://grafana:3000" \
   install/kubernetes/helm/istio \
  --name istio --namespace istio-system > $HOME/istio.yaml`

**Environment where the bug was observed (cloud vendor, OS, etc)**
Amazon AWS Linux EC2
Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by waret** [comment]
The latest code supports update logging level of spedified logger by command `istioctl proxy-config log <pod-name[.namespace]> --level debug`. Maybe this can help you. Please refer to https://github.com/istio/istio/pull/17339.

**Comment by VinothChinnadurai** [comment]
@waret The latest code means any specific istio/envoy version here? And also can we try with kubectl command too like this (kubectl logs -l app=appname -c istio-proxy )

**Comment by douglas-reid** [comment]
Instead of trying to set values for mesh config and hoping that they are picked up, I suggest using an EnvoyFilter for access logging for debugging:

Examples here: https://github.com/istio/istio/wiki/EnvoyFilter-Samples#tracing-and-access-logging

Closing this issue for now.
