### ISSUE TITLE
istio-cni does not return an error when it cannot get pod information from k8s

### ISSUE THREAD

**Issue by gotwarlost** [istio/istio#17583]
**Bug description**

If istio-cni is unable to get pod information, it logs a warning, finds that the number of containers for the pod is not greater than 1, skips injection and succeeds.

https://github.com/istio/cni/blob/c1b9ddf605584b098a9d8ff31622410a81afcaeb/cmd/istio-cni/main.go#L187-L189

It needs to fail fast in this case.

What happened in our case was that we had the cni plugin run as a daemonset in the `istio-system` namespace. Due to races on new node creation, we had to move it to `kube-system` so that we could set its priority class to `system-node-critical`. 

In this move we forgot to update the cluster role binding to the point to the new service account in the `kube-system` namespace. As a result, the CNI pod did not have privileges to get pod info from the k8s API.

In such a situation, I would expect the CNI plugin to fail fast and block pod creation, as opposed to what really happened which was that a bunch of pods came up with no IPTables rules injected and caused a massive, hard-to-debug, cluster-wide outage because no traffic was being redirected to the envoy proxies. 

The fact that we were rolling nodes which causes a bunch of new pods to be created at the same time made the outage worse. OTOH, it was a useful signal to figure out the root cause of a problem that would have been otherwise hard to debug.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by rlenglet** [comment]
Other CNI plugins wait until the pod's info is available from k8s API, with a timeout. Istio CNI should be modified to do the same.

**Comment by rlenglet** [comment]
> we had to move it to kube-system so that we could set its priority class to system-node-critical.

Note that this the default when installing `istio-cni` from any Istio version starting with 1.2.0.

**Comment by mandarjog** [comment]
@rlenglet  Is there a temporary mitigation? Can they use a more recent CNI with an older istio?

**Comment by rlenglet** [comment]
> Is there a temporary mitigation? Can they use a more recent CNI with an older istio?

There is no workaround. Even the `master` implementation still has this issue.

**Comment by howardjohn** [comment]
> Other CNI plugins wait until the pod's info is available from k8s API, with a timeout. Istio CNI should be modified to do the same.

Pilot regularly sees 30s propagation delay in pod info in heavy churn scenarios. I am surprised CNI does not run into the same, often. Maybe the delays are due to more caching in pilot

**Comment by rlenglet** [comment]
> I am surprised CNI does not run into the same, often.

It may be masked by kubelet retrying starting the pod.

**Comment by gotwarlost** [comment]
FWIW, the pod object is created well before the CNI plugin launches in etcd. The call is a get as opposed to a watch (which could lag). IMO, the only times you should see this particular problem is if the K8s API itself is down, or has network connectivity issues, or some RBAC failure as in our case. In any case, the CNI should return an error instead of being a successful noop in this situation.

**Comment by gotwarlost** [comment]
We have ditched istio-cni for init for now and gone back to our crappy, slow init mechanism that involves finding docker container pids and so forth. FYI, this is no longer on the critical path for us.

Our decision is related less to this bug than with race conditions with pod scheduling on new nodes where the CNI plugin execution can be missed for a regular pod. I will document those cases elsewhere.

**Comment by jwendell** [comment]
> > we had to move it to kube-system so that we could set its priority class to system-node-critical.
> 
> Note that this the default when installing `istio-cni` from any Istio version starting with 1.2.0.

Using the new install mechanism `istioctl manifest` as described in CNI doc page, CNI daemonset/pods will be created in `istio-system` namespace. Is this an issue?

**Comment by rlenglet** [comment]
> Using the new install mechanism `istioctl manifest` as described in CNI doc page, CNI daemonset/pods will be created in `istio-system` namespace. Is this an issue?

I have no idea why the namespace was changed. In 1.3, the daemon must be created in `kube-system` due to its `priorityClass`. We @ruigulala changed the priority class, and it should not require being created in `kube-system` anymore. We're lucky this was done before 1.4 release then.

**Comment by ruigulala** [comment]
@rlenglet Some complement information to add here. priorityClass requires a particular feature gate(DynamicKubeletConfig) to be enabled. Prior to Kubernetes 1.11, this feature gate is "false" by default.
https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/
https://v1-13.docs.kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

**Comment by howardjohn** [comment]
@ruigulala Istio 1.4 only supports Kubernetes 1.13+ so I think its reasonable ot assume its enabmed

**Comment by howardjohn** [comment]
Any update on this? is this reasonable to get into 1.4.1?

**Comment by ruigulala** [comment]
> Other CNI plugins wait until the pod's info is available from k8s API, with a timeout. Istio CNI should be modified to do the same.

@rlenglet So what's the final decision in this case? Should I continue with the proposal(wait->timeout->return an error) here?

**Comment by rlenglet** [comment]
> So what's the final decision in this case? Should I continue with the proposal(wait->timeout->return an error) here?

@ruigulala Yes, this proposal sounds good. Thanks!

**Comment by ruigulala** [comment]
Will close the issue when the PR merge.
