### ISSUE TITLE
xDS key validation in pilot

### ISSUE THREAD

**Issue by baodongli** [istio/istio#1758]
pilot accepts queries with keys as in below, for example:

> `/v1/routes/443/istio-proxy/sidecar~ip~podname~domain`

or

> `/v1/routes/443/istio-proxy/sidecar~anything~anything~anything`

The above can apply to any xDS queries for sidecar, ingress and egress.

This means, any keys with the above formats will be accepted by Pilot. Meanwhile, Pilot keeps cache for xDS queries, and never flush it. This could potentially make the cache grow out of bound if random keys are used to query it.

Keys should be validated to conform their definition before going about building the results and caching them.

**Comment by kyessenov** [comment]
Pilot flushes the cache on any change to the inputs, but no TTLs or expirations.
I think the impact is not as big once we start using mTLS between proxies and pilot, but I agree we should add more validation for all external inputs.

**Comment by baodongli** [comment]
I also see that keys corresponding to deleted services (or pods) are not removed from the cache.

I'd like to work on this. Can someone assign this to me? thanks

**Comment by baodongli** [comment]
I am looking at a couple of approaches
 1. Methods in controller code such as platform/kube/controller.go doesn't return error when the result is empty. The methods can either return error, or the caller can check the result in addition to the error to decide if it's a success. This approach takes an easy road, and doesn't validate the key. Also the existing controller methods take partial information from the key. Therefore, they can't perform complete key validation either.
 2. add a new method to the controller for complete key validation according to its specification as documented in here: https://github.com/istio/proxy/blob/master/tools/deb/README.md

On the issue that cache entries are not removed while corresponding services/endpoints have been deleted, the clearCache() method will need to be enhanced to remove the stale entries.

Let me know if I'm on the right track. Especially I'd like to seek guidance on which of the key validation approaches described in above (or other approach you can think of) should I take before I embark on the code change.

**Comment by kyessenov** [comment]
cc @andraxylia @ZackButcher @nmittler

**Comment by nmittler** [comment]
Any reason not to implement [number 2 above](https://github.com/istio/istio/issues/1758#issuecomment-346144127)?

> On the issue that cache entries are not removed while corresponding services/endpoints have been deleted, the clearCache() method will need to be enhanced to remove the stale entries.

Cache staleness seems to be a slightly different (albeit related) issue ... do you think it's worthy of another tracking bug? Perhaps we could just apply a max-age for all entries in the cache?
