### ISSUE TITLE
gRPC client unaware of connection failure, never reconnecting

### ISSUE THREAD

**Issue by seeruk** [istio/istio#17590]
**Bug description**

At Icelolly we're using EKS to host our Kubernetes Cluster. We're running Istio 1.3.1 with mTLS enabled. We're in the process of migrating applications into Kubernetes, but otherwise we have applications running on EC2 instances, managed by Elastic Beanstalk.

In our EKS cluster we have a GraphQL server that consumes several other gRPC services. The gRPC services consumed by the GraphQL server are all hosted in EC2 currently - none of them have been migrated to our Kubernetes clusters. The GraphQL server and the gRPC services are all written in Go.

Overnight, we shut down our staging environment VMs in Elastic Beanstalk. We've found that when we come in on a morning we have to restart the GraphQL service (i.e. delete the pods) for it to start working again. We often arrive hours after the staging environments in Elastic Beanstalk have started again. We've also tested our GraphQL server's reconnection ability without Istio in the mix, and it works fine. This happened to us a few times in production - it's just lucky that right now we're not using this for any mission-critical service.

We believe that the sidecar is keeping a connection open with the GraphQL service, making the gRPC library believe the connection is "Ready", keeping it in the dark about the connection failure.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

If a gRPC server is stopped, and it is outside of the cluster, a client application running inside the cluster should still be able to reconnect even if an Istio sidecar is present.

**Steps to reproduce the bug**

Create a gRPC server, host it outside of the cluster, set up a gRPC client application, host that inside the cluster with sidecar injection enabled, ensure that a service entry is made, verify it all works under normal conditions, then kill the server. Observe that the client is unaware of any failure, and doesn't attempt to reconnect - requests simply time out.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

```
$ istioctl version --remote
client version: 1.3.1
citadel version: 1.3.1
citadel version: 1.3.1
galley version: 1.3.1
galley version: 1.3.1
ilbgateway version: 
ilbgateway version: 
ingressfirewalledgateway version: 
ingressfirewalledgateway version: 
ingressgateway version: 1.3.1
ingressgateway version: 1.3.1
pilot version: 1.3.1
pilot version: 1.3.1
policy version: 1.3.1
policy version: 1.3.1
sidecar-injector version: 1.3.1
sidecar-injector version: 1.3.1
telemetry version: 1.3.1
telemetry version: 1.3.1
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:51:13Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.10-eks-5ac0f1", GitCommit:"5ac0f1d9ab2c254ea2b0ce3534fd72932094c6e1", GitTreeState:"clean", BuildDate:"2019-08-20T22:39:46Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

via Helm.

**Environment where bug was observed (cloud vendor, OS, etc)**

AWS EKS, Linux

**Workaround**

Currently I've worked around this issue by using the `excludeIPRanges` option, bypassing the sidecar entirely for connecting to external services in the VPCs we use in Elastic Beanstalk.

**Additional Info**

I've tested this within the cluster now, deploying one of our gRPC applications within the cluster, scaled it to 0, and scaled it back up and the application does recover completely fine - in fact it recovers quicker within the cluster because the connection isn't closed, and no backoff is applied as a result - so this is solely affecting external services (and to clarify there, I don't mean ExternalName services, I just mean things outside of the cluster).

**Comment by mkinoshi** [comment]
We have experiences the same issue while using istio 1.2.4 on GKE 1.13.7-gke.8

**Comment by nbaztec** [comment]
We're also getting similar issues on `istio 1.7`

The grpc streaming services never seem to identify a server going away (eg. node failure) and as such do not try reconnecting. Not injecting the sidecare successfully mitigated the issue.

Anyone got a better solution?

**Comment by beryanow** [comment]
Any updates?
