### ISSUE TITLE
Rate Limiting by other metrics besides Request/Second

### ISSUE THREAD

**Issue by timbuktuu** [istio/istio#176]
In scenarios where API responses vary in size, it would be ideal to apply rate limiting by metrics other than requests per second.   Often cloud providers bill egress traffic per GB of data via load balancers, so costs per api request can be hard to correlate to actual infrastructure cost associated with the API request/response when the response size can vary.  

Use-case:

1. Bandwidth bytes/second.  For example network capacity estimation or egress charges.  
2.  Total Bytes.  For example, a free API service tier up to 100Mb

**Comment by tinochan** [comment]
Would like to have the team's advice if the function Rate Limiting by bandwidth (e.g. bytes/second) may be included in the coming release?

**Comment by douglas-reid** [comment]
@gargnupur can you take a look at this request?

**Comment by gargnupur** [comment]
This would be great to have! We would have to add a new filter for this or improve current Envoy's rate limiting filter as current one doesn't have this capability https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/rate_limit_filter
