### ISSUE TITLE
Generated client-go doesn't marshal/unmarshal correctly

### ISSUE THREAD

**Issue by nrjpoddar** [istio/istio#17600]
**Bug description**
The `json` and `protobuf` tags differ in the generated go code for any fields which are declared snake case in the proto file and all Istio examples/tests use the CamelCase json tag used in the `protobuf` tag. Here's an example [proto field](https://github.com/istio/api/blob/33a483a29b8e654f7542b1939871d899eeb14da9/authentication/v1alpha1/policy.proto#L63) and it's corresponding generated [go structs](https://github.com/istio/api/blob/33a483a29b8e654f7542b1939871d899eeb14da9/authentication/v1alpha1/policy.pb.go#L206)

Note this line: 
```bash
AllowTls bool `protobuf:"varint,1,opt,name=allow_tls,json=allowTls,proto3" json:"allow_tls,omitempty"`
```
where the `json` tag is different inside `protobuf` tag. 

As, the generated go files from proto have custom marshalers defined only if they have a oneof as is the case [here](https://github.com/istio/api/blob/096de7877b32f265154689bdf6f27631406dad0e/authentication/v1alpha1/policy_json.gen.go). It means that when the generated clientset calls JSON encoding/decoding the fields which are snake case in proto will not work.

We can fix this issue by generating custom Marshal/Unmarshal for the top level Go structs like [this](https://github.com/aspenmesh/istio-client-go/blob/8c72de05fa403f0c3750a4bed20af600e81096fe/pkg/apis/authentication/v1alpha1/policy.go#L60).

**Affected product area (please put an X in all that apply)**

[x] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Related issues**
https://github.com/istio/istio/issues/8772

**Comment by jasonwzm** [comment]
xref: https://github.com/kubernetes/client-go/issues/574
