### ISSUE TITLE
Create tool to generate intermediate CAs

### ISSUE THREAD

**Issue by sdake** [istio/istio#17609]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Intermediate CAs must be manually generated.  The manual process is not easy requiring many manual error-prone steps.  It took me about 2 hours to get through the instructions the first time and the results were not correct.  I had it down to about 10 minutes after I ran through the commands a bunch of times.  It would be great if this could be automated so it was not error prone and produced correct results in the event of butteryfly keyboards or typos 👍 

This is necessary for gateway security.

I used these instructions to generate the certs - and tested them with gateway multicluster.
https://jamielinux.com/docs/openssl-certificate-authority/create-the-intermediate-pair.html

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**
1.4 and prior.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**
This is a request from @smawson so he can resolve so other documentation issues.

**Comment by myidpt** [comment]
Temporarily assign this to myself. I really want to get this done but it got delayed for various reasons. I should get this done sometime after 1.4 and before EOY. Anyone please feel free to take it if you want to contribute.

**Comment by sarajmunjal** [comment]
@myidpt I'd like to take this on as a first issue :)
