### ISSUE TITLE
readinessProbe failing with "separate Port" setup

### ISSUE THREAD

**Issue by BernhardLenz** [istio/istio#17614]
**Bug description**
To test the readinessProbe with Istio mTLS enabled I'm following the instructions of 
https://istio.io/docs/ops/app-health-check/

However when I move the readinessProbe to a different port by applying "samples/health-check/liveness-http.yaml" the readinessProbe still fails. 

I suspect that separate policies/destination rules need to be created for that port that are not mentioned in the documentation. What are those rules and should they be mentioned in the https://istio.io/docs/ops/app-health-check/ documentation?

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
both containers should be in "ready" status

**Steps to reproduce the bug**
Follow instructions in https://istio.io/docs/ops/app-health-check/ for "Separate port"
Run
kubectl apply -f <(istioctl kube-inject -f samples/health-check/liveness-http.yaml)

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
istioctl version --remote
client version: 1.3.1
control plane version: 1.3.1

kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-gke.2", GitCommit:"c9de33b5439df6e206d7ba646787c6ace92d737b", GitTreeState:"clean", BuildDate:"2019-09-06T18:30:33Z", GoVersion:"go1.12.9b4", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
Followed instructions in https://istio.io/docs/ops/app-health-check/

**Environment where bug was observed (cloud vendor, OS, etc)**
google gke

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by incfly** [comment]
This works for me, tried on 1.3.3 release.

https://github.com/istio/istio/blob/release-1.3/samples/health-check/liveness-http.yaml#L34

We don't have a readiness probe defined in the liveness-http.yaml. Only liveness probe. And that works for me as well.

It's using port 8002, which is not listed on the liveness service definition. so mTLS configuration(authentication policy) is not covered there. You shouldn't need to configure Istio API specifically, at least for this example.

**Comment by incfly** [comment]
I'm closing but feel free to reopen.

**Comment by sneko** [comment]
I have this issue too (Istio 1.4.3).

It works for all my microservices, except for frontend pods and the API pod (those that are directly linked to a gateway). That's really strange.
