### ISSUE TITLE
TestAnalyzers test failures (deadlock)

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#17617]
Example failure: https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/16967/racetest_istio/1496

I know this is not the only failure since I have seen a few in the past, but we need to fix the testgrid (https://testgrid.k8s.io/istio_istio#racetest_istio&exclude-non-failed-tests=&width=20) because apparently we have too many results in it, so I can't link to all of them right now. I will update as I see more

**Comment by howardjohn** [comment]
https://prow.k8s.io/view/gcs/istio-prow/logs/unit-tests_istio_postsubmit/229
https://prow.k8s.io/view/gcs/istio-prow/logs/unit-tests_istio_postsubmit/227

**Comment by sushicw** [comment]
It looks like the point where we're blocked is the call to WaitForReport. It's not yet clear to me if we get to the point where the analyzers execute (that's getting logged at too low of a level to appear in the logs).

@ozevren you were mentioning running into this the other day, did you have any specific insights?

**Comment by sushicw** [comment]
Oldest examples I can find:
            Unit tests: 2019-10-04 18:49:34 +0000 UTC
            Racetest:   2019-10-03 17:40:14 +0000 UTC

These tests have been around for weeks before that, so this gives us some idea where to look for changes that triggered problems. Chatting with @ozevren, the most likely triggering commit is https://github.com/istio/istio/commit/8ce0867867d7d5538a70e1640d51d8b1427dead0. He's currently trying to repro in a test branch (https://github.com/istio/istio/pull/17654).

**Comment by sushicw** [comment]
Oz and I both had no luck reproducing this. 

https://github.com/istio/istio/pull/17731 re-enables the test, and adds some more debugging so hopefully we can see better what the problem is if/when it recurs.

**Comment by sushicw** [comment]
New example, with more logging: https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/17731/unit-tests_istio/1890
