### ISSUE TITLE
 Failed to create Istio Control Plane: admission webhook "pilot.validation.istio.io" denied 

### ISSUE THREAD

**Issue by justrohan** [istio/istio#17627]
I am currently runnning a single node cluster using microk8s to deploy kubeflow,
when I try to apply the generated files by kfctl, the following issue occurs:

**ERROR: Failed to create Istio Control Plane: admission webhook "pilot.validation.istio.io" denied the request: unrecognized type ClusterRbacConfig  filename="existing_arrikto/existing.go:457"**

Any ideas what could be causing this , or what I should be checking.

Environment info:
Version: 1.0.5
GitRevision: c1707e45e71c75d74bf3a5dec8c7086f32f32fad
User: root@6f6ea1061f2b
Hub: docker.io/istio
GolangVersion: go1.10.4
BuildStatus: Clean

installed using microk8s => microk8s.enable istio <DID NOT enable TLS between sidecars>

OS:Ubuntu 16.04

k8s version: 1.14

**Comment by howardjohn** [comment]
I'm not sure this CRD even existed with Istio 1.0... I would highly recommend installing a modern version of Istio. 1.0 has not been supported for a while and therefore has a lot of security vulnerability and critical bug fixes missing that have been fixed in new versions

**Comment by justrohan** [comment]
Thanks @howardjohn , I'm currently using microk8s, so that is the version with comes with it, is there anyway to update the istio for microk8s?

**Comment by howardjohn** [comment]
Not very familiar, but it seems to support Istio 1.2?
https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/actions/enable.istio.sh

**Comment by howardjohn** [comment]
This is working as intended, the config does not exist on Istio 1.0
