### ISSUE TITLE
Split istio/install/kubernetes/helm/istio/charts/security/templates/create-custom-resources-job.yaml into multiple templates

### ISSUE THREAD

**Issue by thecodejunkie** [istio/istio#17638]
**Describe the feature request**
All other Helm templates produce 1 file per template, however the `create-custom-resources-job.yaml` creates several resources in a single file. This makes it more complicated if you work with automation or things like Anthos Config Managment

**Describe alternatives you've considered**

Break up `create-custom-resources-job.yaml` into multiple templates

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
In the new operator, where we are focusing most of our efforts, we will not longer have these jobs that create resources. I'm not really sure the jobs are needed in the current helm install either though, maybe we could remove them there as well

**Comment by thecodejunkie** [comment]
@howardjohn thanks for your reply. How would I figure out if those jobs are needed with Istio 1.3.1? Removing it would make my life easier 😄

**Comment by howardjohn** [comment]
(on phone, so this is based on memory) the jobs are creating Istio CRs like DestinationRule or something. My guess is this is done as a job rather than directly due to either

* race condition with the CRD being applied. This is not an issue now since we have the split `istio-init` chart
* race condition with the galley validation webhook. Consider: webhook created, then DestinationRule created. Galley is not yet started, so the webhook call fails.

**Comment by thecodejunkie** [comment]
So if I apply `istio-init` first, then it should be OK?

**Comment by thecodejunkie** [comment]
@howardjohn thoughts? 😄

**Comment by howardjohn** [comment]
@thecodejunkie you definitely need to install istio-init first, regardless of the create-custom-resource job. The init job creates all the CRDs which are prerequisites for all of the other components

**Comment by thecodejunkie** [comment]
@howardjohn Yes, I'm hoping I can install `istio-init` and then the other Istio resources sans `create-custom-resources-job.yaml`

**Comment by howardjohn** [comment]
We have no plans to make changes to the legacy helm charts anymore
