### ISSUE TITLE
istioctl x upgrade: add integ test for upgrade

### ISSUE THREAD

**Issue by elfinhe** [istio/istio#17649]
We'll cover the upgrade the scenarios below with some different profiles installed:
- 1.3.x -> 1.3.y
- 1.3.x -> 1.4.0

The test cases can be a script like [test_crossgrade.sh](https://github.com/istio/istio/blob/master/tests/upgrade/test_crossgrade.sh), or just improvement in the script.

**Comment by elfinhe** [comment]
upgrade subcommand PR: https://github.com/istio/operator/pull/348

**Comment by carolynhu** [comment]
After discussed with @ostromart , at current stage, we'd better put this helm charts install and istioctl upgrade into two periodic jobs. After it's running stable, we can move them to postsubmit job. Therefore, I'm going to add periodic jobs first.
