### ISSUE TITLE
Distroless images rely on copying hacks for iptables

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#17656]
Right now we are copying a bunch of libraries over into the distroless image. These may or may not be compatible with the distroless system, and are pretty hacky. We should be building our own distroless image with these baked in: https://github.com/bazelbuild/rules_docker#container_image-1

**Comment by howardjohn** [comment]
not stale

**Comment by costinm** [comment]
Or we can pass the problem to envoy - I think the goal is to upstream the things from istio-proxy. 

Instead of downloading envoy binary - we can use base images generated from envoy build system ( which is bazel ), including 
ARM, alpine, etc. I assume they'll need to support distroless as well.

We would just add istio-agent and few static files.

**Comment by howardjohn** [comment]
I generally agree but I am not sure it solves the need for us to copy a bunch of dynamically linked stuff for iptables unless envoy includes it in their images?

**Comment by sdake** [comment]
As we don't use the iptables libraries directly, but instead exec() into the iptables binary, compiling statically seems to work with the latest versions of iptables with some small amount of work.

Copying dynamically linked code is dangerous - some libs depend upon others and versions matter. Worse the kernel may have dependencies on libraries used, specifcally all the RTNETLINK code in the kernel.

Here are the libs in use when I dynamically compiled:
```
sdake@beast-01:/tmp/iptables/sbin$ ldd xtables-legacy-multi 
	linux-vdso.so.1 =>  (0x00007ffcf9ff0000)
	libip4tc.so.2 => /tmp/iptables/lib/libip4tc.so.2 (0x00007fbe1b619000)
	libip6tc.so.2 => /tmp/iptables/lib/libip6tc.so.2 (0x00007fbe1b411000)
	libxtables.so.12 => /tmp/iptables/lib/libxtables.so.12 (0x00007fbe1b200000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fbe1aef7000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fbe1ab2d000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fbe1a929000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fbe1b821000)
```

If it was a different tool then iptables, it wouldn't be such a problem.

Cheers,
-steve

**Comment by sdake** [comment]
re Envoy, I am not sure how moving this problem to Envoy solves this problem for the non-root case presented by CNI. Therefore, this project will need to come to a resolution about this specific binary and how to build it properly.

Cheers,
-steve

**Comment by nrjpoddar** [comment]
For the proxy image we don't need iptables so it's probably a good idea to start separating out images for init and proxy container. It might reduce the surface area from a security perspective.

**Comment by howardjohn** [comment]
Fixed by https://github.com/istio/istio/pull/28940
