### ISSUE TITLE
automtls Reachability test flakes

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#17666]
Example failures:

https://prow.k8s.io/view/gcs/istio-prow/logs/integ-security-k8s-tests_istio_postsubmit/241
https://prow.k8s.io/view/gcs/istio-prow/logs/integ-k8s-112_istio_postsubmit/192

**Comment by incfly** [comment]
@diemtvu would you mind taking a look? You mentioned they're identical and okay to be removed, but seems are all failing on timeout?

**Comment by incfly** [comment]
Closing we reinvent this test.
