### ISSUE TITLE
VirtualService file for istio from nginx

### ISSUE THREAD

**Issue by hitesh1907nayyar** [istio/istio#17676]
Hi All , 

I am new to istio.I am planning to migrate from nginx to istio and want to convert the ingress file mentioned below to virtual service file for istio.

   apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    name: ingress-ui
    annotations:
      kubernetes.io/ingress.class: nginx
  spec:
    rules:
      - host: test.tech.co
        http:
          paths:
            - backend:
                serviceName: ui
                servicePort: 80
              path: /
            - backend:
                serviceName: apigateway-portal
                servicePort: 8080
              path: /api

Can anybody please help as how this can be converted ?

I created the below file but this is not working:

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-ui-vs
spec:
  hosts:
  - "test.tech.co"
  gateways:
  - istio-istio-gateway
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        port:
          number: 80
        host: ui.default.svc.cluster.local

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-apigateway-vs
spec:
  hosts:
  - "test.tech.co"
  gateways:
  - istio-istio-gateway
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        port:
          number: 8080
        host: apigateway-portal.default.svc.cluster.local
---

**Comment by howardjohn** [comment]
When you say its "not working" what does that mean? What are you seeing?

What version of Istio?

Please see https://github.com/istio/istio/wiki/Troubleshooting-Istio#collecting-information-2
