### ISSUE TITLE
sidecar fails to marshall json for accesslog and metrics service

### ISSUE THREAD

**Issue by rshriram** [istio/istio#17674]
#17661 fixed the decoding of JSON arguments into the proto after #17495 [though the entire thing used to work before #17495 and #17478 ]. After #17661 the gateways are now getting the proper JSON configs and pilot agent is able to decode them into the RemoteService proto. However the sidecars are now failing to decode the data!

The gateway receives this as the cli arg (camel case)
```
2019-10-08T01:14:35.923815Z	info	FLAG: --envoyAccessLogService="{\"address\":\"oap.istio-system:11800\",\"tlsSettings\":{\"mode\":\"DISABLE\",\"subjectAltNames\":[]},\"tcpKeepalive\":{\"interval\":\"10s\",\"probes\":3,\"time\":\"10s\"}}"
```
and correctly decodes it after #17661 . However, the sidecar is receiving

```
2019-10-08T01:19:03.215249Z	info	FLAG: --envoyAccessLogService="{\"address\":\"oap.istio-system:11800\",\"tls_settings\":{},\"tcp_keepalive\":{\"probes\":3,\"time\":{\"seconds\":10},\"interval\":{\"seconds\":10}}}"
```

which has snake case and types.Duration object itself instead of a string for the "time" and "interval" fields. This is presumably caused by https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/files/injection-template.yaml#L139 that uses structToJSON to serialize the proto into a JSON object. However, jsonpb in https://github.com/istio/istio/blob/master/pilot/cmd/pilot-agent/main.go#L588 does not like this format.

What is perplexing is how did this work in the past? [access logging worked for us certainly. Not sure if the TLS settings or tcp keep alive worked or not]. And why did this break after #17478 [if that is the culprit].

**Comment by rshriram** [comment]
cc @nmittler / @joeyb / @ramaraochavali

**Comment by nmittler** [comment]
@rshriram when you say that sidecars are now failing, are you seeing this on CI? Do you have any links?

**Comment by nrjpoddar** [comment]
@rshriram it might be the same issue underneath as https://github.com/istio/istio/issues/17600

The `json` tags inside the `proto` tag are CamelCased but the `json` tag by itself are snake cased. That's how any field with `_` in proto get converted in `go`.

**Comment by rshriram** [comment]
see #17675 for fix for this issue.
