### ISSUE TITLE
Why the libc++ and libc++abi are not installed for proxyv2 image in 1.3?

### ISSUE THREAD

**Issue by mailzyok** [istio/istio#17678]
Hi,

I found two libraries libc++ and libc++abi are missing for proxyv2 image in 1.3, however these libraries are used to fix the security VA in Istio 1.2.5. 

Any reason?

See the purpose of these two libraries in my previous ticket https://github.com/istio/istio/issues/16568

Thanks,
mailzyok

**Comment by PiotrSikora** [comment]
Istio Proxy binaries in 1.1 and 1.2 are dynamically linked against libc++ and libc++abi, so Docker images needed them.

Istio Proxy binaries in 1.3 are statically linked against libc++ and libc++abi, so the binary is self-contained, and we don't need to install those libraries in Docker anymore.

**Comment by mailzyok** [comment]
Thanks @PiotrSikora , i will check the Istio Proxy build process.
