### ISSUE TITLE
Pilot crashed when receiving MCP data with 8 million endpoints

### ISSUE THREAD

**Issue by nkorange** [istio/istio#17679]
I have tested the MCP protocol between Pilot and my MCP server. I found when I sent a large set of service data to Pilot, Pilot crashed from time to time.

![image](https://user-images.githubusercontent.com/4593375/66471607-324b6b00-eabe-11e9-8646-3c200d68e0d5.png)

This happened when my MCP server generates about 130,000 services and about 8,000,000 endpoints to push to Pilot. 

Note that if I change the generated services count to 10,000. This phenomenon disappears.

The logs from MCP server side:
![image](https://user-images.githubusercontent.com/4593375/66471420-d97bd280-eabd-11e9-8394-224da89af873.png)

My project is here: https://github.com/nacos-group/nacos-istio

**Comment by nkorange** [comment]
It seems Pilot crashed:
![image](https://user-images.githubusercontent.com/4593375/66379371-e29a7000-e9e7-11e9-95cb-69d3c95ee255.png)

The resource limit of Pilot is 4 CPU and 8G memory.

I will increase this resource limit and test again.

**Comment by nkorange** [comment]
I increased the resource limit of Pilot to 8 CPU and 16G memory.
Still got multiple ACKs:
![image](https://user-images.githubusercontent.com/4593375/66382540-fa74f280-e9ed-11e9-84a9-c386d8815f09.png)

And the connections are keeping closing:
![image](https://user-images.githubusercontent.com/4593375/66382602-17112a80-e9ee-11e9-8879-e36b0a4e8d9d.png)

I invoked ```curl '127.0.0.1:15003/debug/registryz'``` in Pilot and found that the services are synchronized to Pilot successfully.

**Comment by howardjohn** [comment]
Can you add logs from pilot when it crashed?

**Comment by nkorange** [comment]
The last few lines of log of Pilot before it crashed:
![image](https://user-images.githubusercontent.com/4593375/66468839-6b351100-eab9-11e9-8a7c-0a2e13acb4c1.png)

**Comment by howardjohn** [comment]
If I'm reading that right it's using 30gb of memory? so probably oom kill

**Comment by nkorange** [comment]
> If I'm reading that right it's using 30gb of memory? so probably oom kill

Yes, I verified it with command ```dmesg```. So why Pilot consumes so much memory? My data size is probably 2GB, but I repeatedly push this same 2GB data to Pilot. Does Pilot have some memory leak?

**Comment by nkorange** [comment]
We are considering to introduce Istio to our production environment, which contains about millions endpoints. This requires Pilot can handle such level amount of data and also frequent data changes.

I just tested the Pilot side communicating with my MCP server and some of the results are:
1. 2GB service entry data will cause about 28GB memory use of Pilot.
2. Frequent push of smaller size of data, like 400MB, will cause Pilot eventually exhausted its 32GB memory.

So my questions are:
1. Does receiving MCP push cause Pilot memory leak?
2. Can incremental MCP push in Pilot solve this problem and when it can be supported?

Thank you!

**Comment by howardjohn** [comment]
@nkorange I would suggest you look at https://github.com/istio/istio/wiki/Analyzing-Istio-Performance for help diagnosing performance. Id be interested to see some heap profiles during this.

Your tool looks really useful, I'll try it out and see what we can learn and if we can optimize this at all.

Are you on pilot 1.3?

**Comment by howardjohn** [comment]
You are creating ServiceEntry of type DNS resolution. This is not what you want to handle an endpoint, you should instead use STATIC. Should be like

```
	se := &v1alpha3.ServiceEntry{
		Hosts:      []string{hostname},
		Addresses:  sh[name][0].Addresses,
		Ports:      sh[name][0].Ports,
		Resolution: v1alpha3.ServiceEntry_STATIC,
	}
```

**Comment by howardjohn** [comment]
How are you getting around `Error receiving MCP resource: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4759554 vs. 4194304)`? Did you increase the max GRPC size in pilot? Right now its set to 4mb. I sent 1 service with 100,000 endpoints and its way above that limit

**Comment by nkorange** [comment]
> You are creating ServiceEntry of type DNS resolution. This is not what you want to handle an endpoint, you should instead use STATIC. Should be like
> 
> ```
> 	se := &v1alpha3.ServiceEntry{
> 		Hosts:      []string{hostname},
> 		Addresses:  sh[name][0].Addresses,
> 		Ports:      sh[name][0].Ports,
> 		Resolution: v1alpha3.ServiceEntry_STATIC,
> 	}
> ```

OK, but this doesn't influence how Pilot consumes the memory, right?

**Comment by nkorange** [comment]
> How are you getting around `Error receiving MCP resource: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4759554 vs. 4194304)`? Did you increase the max GRPC size in pilot? Right now its set to 4mb. I sent 1 service with 100,000 endpoints and its way above that limit

Yes, I set the ```mcpMaxMsgSize``` to 4GB.

**Comment by nkorange** [comment]
> @nkorange I would suggest you look at https://github.com/istio/istio/wiki/Analyzing-Istio-Performance for help diagnosing performance. Id be interested to see some heap profiles during this.
> 
> Your tool looks really useful, I'll try it out and see what we can learn and if we can optimize this at all.
> 
> Are you on pilot 1.3?

Yes, Pilot 1.3.1

**Comment by howardjohn** [comment]
> OK, but this doesn't influence how Pilot consumes the memory, right?

It does, its results in a different internal representation. Not sure if that results in more or less memory though, but its probably not the same.

> Yes, I set the mcpMaxMsgSize to 4GB.

I am curious about the implications of this.. I think this will result in Pilot likely using a more than 4GB just to handle the message due to buffering, etc


Do you have any XDS connections (gateway or sidecar) to pilot, or is it just receiving MCP config?

**Comment by nkorange** [comment]
> > OK, but this doesn't influence how Pilot consumes the memory, right?
> 
> It does, its results in a different internal representation. Not sure if that results in more or less memory though, but its probably not the same.

OK, I will retest with static resolution type.

> 
> > Yes, I set the mcpMaxMsgSize to 4GB.
> 
> I am curious about the implications of this.. I think this will result in Pilot likely using a more than 4GB just to handle the message due to buffering, etc
> 
> Do you have any XDS connections (gateway or sidecar) to pilot, or is it just receiving MCP config?

How can I verify this? 
I just installed an empty K8S cluster and Pilot following the official guide: https://istio.io/docs/setup/install/kubernetes/

There are some xds logs in Pilot:

![image](https://user-images.githubusercontent.com/4593375/66617452-c117cf00-ec07-11e9-8d26-2da33dc42f3a.png)

**Comment by howardjohn** [comment]
looks like no, since connected endpoints is 0. I would encourage you to test with some actual workloads connected to pilot so you can measure envoy memory usage as well, and test pilot xds performance. Generating a bunch of config over mcp isn't very useful unless you are actually sending it to envoy at some point

**Comment by nkorange** [comment]
@howardjohn  Thanks a lot. I will reorganize my test procedures and upload the results later.

**Comment by nkorange** [comment]
@howardjohn I'm writing an article to introduce the MCP protocol and how to write a MCP server to communicate with Istio. Can I cite the content/images in [this document](https://docs.google.com/document/d/1S5ygkxR1alNI8cWGG4O4iV8zp8dA6Oc23zQCvFxr83U/edit#)?

**Comment by hzxuzhonghu** [comment]
Absolutely, it is public

**Comment by nkorange** [comment]
> Absolutely, it is public

Thanks.

**Comment by dzdx** [comment]
the memory leak may be caused by the `DiscoveryServer.EndpointShardsByService`
https://github.com/istio/istio/blob/f3371be953598f89b5bd4ef93061ea7807c10e5e/pilot/pkg/proxy/envoy/v2/eds.go#L270-L309
the above code that update `EndpointShardsByService` will not clear the old service.
you can verify this by：
1. Push 1000 serviceentry
2. Push 1 serviceentry
3. `curl http://$pilotip:15014/debug/endpointShardz` , the response still contains more than 1000 service

If the mcp service continues to push service entries of different hosts,  the size of the EndpointShardsByService will become larger and larger

I try to add code to clear EndpointShardsByService

```

                        s.edsUpdate(registry.ClusterID, string(svc.Hostname), svc.Attributes.Namespace, entries, true)
+                       newNonk8sSvcs[shardSvcItem{
+                               serviceName: string(svc.Hostname),
+                               namespace:   svc.Attributes.Namespace,
+                               clusterID:   registry.ClusterID,
+                       }] = struct{}{}
+               }
+       }
+       toDeleteSvcItems := make([]shardSvcItem, 0)
+       for serviceName, perService := range s.EndpointShardsByService {
+               for namespace, shards := range perService {
+                       for clusterID := range shards.Shards {
+                               if _, ok := nonK8sRegistryClusterIDs[clusterID]; ok {
+                                       if _, ok := newNonk8sSvcs[shardSvcItem{
+                                               serviceName: serviceName,
+                                               namespace: namespace,
+                                               clusterID: clusterID,
+                                       }]; !ok {
+                                               toDeleteSvcItems = append(toDeleteSvcItems, shardSvcItem{
+                                                       serviceName: serviceName,
+                                                       namespace: namespace,
+                                                       clusterID:clusterID,
+                                               })
+                                       }
+                               }
+                       }
                }
        }
-
+       for _, svcItem := range toDeleteSvcItems{
+               s.edsUpdate(svcItem.clusterID, svcItem.serviceName, svcItem.namespace, nil, true)
+       }
        return nil
 }

```
and add the env `GODEBUG=madvdontneed=1`  
https://golang.org/doc/go1.12#runtime

> On Linux, the runtime now uses MADV_FREE to release unused memory. This is more efficient but may result in higher reported RSS. The kernel will reclaim the unused data when it is needed. To revert to the Go 1.11 behavior (MADV_DONTNEED), set the environment variable GODEBUG=madvdontneed=1

after Push 1 serviceentry, 这handler `endpointShardz` Returned a small response body
and the rss dropped from 1GB to 200MB in a few minutes

**Comment by hzxuzhonghu** [comment]
@dzdx Good catch, indeed. Maybe  the mem leak is introduced in #13631.  We should make use of the delete event for each registry other than k8s. @ramaraochavali `SvcUpdate` may be a good choice.
