### ISSUE TITLE
Analyzer for RBAC requiring MTLS

### ISSUE THREAD

**Issue by sushicw** [istio/istio#17687]
~mTLS is required for RBAC. If ClusterRbacConfig is anything but OFF, mTLS should be enabled.~ *EDIT: Not strictly true, see everything below including comments*

Actually, this is a bit more subtle since mTLS can be disabled globally but enabled selectively between services, and we need to handle those cases too. This means we need to be aware of what services / namespaces RBAC is enabled for in ClusterRbacConfig, and verify that mTLS is enabled for everything covered there. 

STRICT and PERMISSIVE both work.

**Comment by sushicw** [comment]
Another specific check to add:

**Comment by sushicw** [comment]
I don't have immediate time to work on this further right now, but I took a stab at a start. 

https://github.com/istio/istio/compare/master...sushicw:analyzer-mtls-rbac

Hopefully whoever picks this up (whether that's Future Me or someone else) will be able to make good use of it.

**Comment by sushicw** [comment]
From a thread on the slack channel:

```
Limin Wang  23 hours ago
If authorization policy does not refer to a service identity, you do not have to enable mTLS.

Limin Wang  23 hours ago
For example, you can use authorization policy only based on end user credential (JWT), or IP addresses.

Limin Wang  23 hours ago
The security best practice is to enable mTLS to secure channel, and authorization policy for access control. But the features can be used independent of each other.
```

**Comment by sushicw** [comment]
There's a blog post here that should cover a bunch of scenarios: https://istio.io/blog/2018/istio-authorization/#service-method-level-isolation-with-without-primary-identities

**Comment by sushicw** [comment]
So more specifically, we want this rule to apply to policies that use service identities.

We should also make sure it applies for the new auth policy as well (see https://github.com/istio/istio/issues/19076)

**Comment by pitlv2109** [comment]
> mTLS is required for RBAC

Actually no. RBAC can be used with or without service to service authentication. One can use end-user authentication (i.e. jwt) with RBAC. RBAC can also be used with other conditions such as IP addresses, request headers, namespaces, etc.

**Comment by sushicw** [comment]
@pitlv2109 Do you think there are any analysis rules that can help prevent the sort of problems highlighted in e.g. #19197? The fact that RBAC just silently doesn't work if you've missed setting up some prerequisites is pretty painful, I've run into it twice myself.

**Comment by pitlv2109** [comment]
If in RBAC rules, you specify service identity (e.g. `user` field in ServiceRoleBinding) or workload identity (e.g. `principals` in AuthorizationPolicy), then service to service authentication must be turned on. The way it works is at the authentication filter layer, it will check the client's identity and pass that into the RBAC filter using envoy metadata. So I guess one way rule to check is if RBAC is relying on identity (based on fields like `user` and `principals` and some other fields), authentication should be on.

**Comment by sushicw** [comment]
@pitlv2109 to clarify: by "authentication should be on" do you mean mTLS specifically, or do we need to be checking more broadly?

**Comment by pitlv2109** [comment]
> @pitlv2109 to clarify: by "authentication should be on" do you mean mTLS specifically, or do we need to be checking more broadly?

So basically the rule is something like this:
If the RBAC rule has a service or workload identity field (e.g. `user`), then Istio should have some service to service authentication mechanism turned on (this is usually mTLS + and/or destination rules). 
If the RBAC rule has jwt-related field, then jwt should be used.

Another thing is that RBAC rules are additive, so if you have something like `user = "*" or ""` (forgot which one), then it will allow anyone.

@yangminzhu and @diemtvu know more about authentication.
