### ISSUE TITLE
Confusing `istioctl analyze` message "failed finding spec for group/kind"

### ISSUE THREAD

**Issue by esnible** [istio/istio#17684]
To reproduce: `istioctl x analyze samples/bookinfo/platform/kube/bookinfo.yaml`

This logs 10 error messages, each looking like:
```
2019-10-08T15:46:26.478331Z	error	source	Error processing samples/bookinfo/platform/kube/bookinfo.yaml[1]: failed finding spec for group/kind: /ServiceAccount
```

The kinds are /ServiceAccount and apps/Deployment.

See https://github.com/istio/istio/issues/17272 for the problem from the point of view of the API.  This Issue is from the point of view of the user of the tool.  They don't want to see log messages for internal limitations of the tool.  It should be at most a warning (off by default in istioctl) when the analysis framework gets something unexpected via the istioctl CLI.

**Comment by sushicw** [comment]
The log level should for those messages should probably be bumped down to WARN, I think.
