### ISSUE TITLE
DeepCopy Error When Importing Client-Go

### ISSUE THREAD

**Issue by Phlak106** [istio/istio#17688]
**Bug description**
When importing client-go compatible types e.g. ```istionetworking "istio.io/client-go/pkg/apis/networking/v1alpha3"``` go vet produces errors such as ```vendor/istio.io/client-go/pkg/apis/networking/v1alpha3/zz_generated.deepcopy.gen.go:16:9: in.Spec.DeepCopyInto undefined (type v1alpha3.DestinationRule has no field or method DeepCopyInto)```

**Affected product area (please put an X in all that apply)**
Extensibility? Not sure if there is an area for this?

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[X] Developer Infrastructure

**Expected behavior**
No errors. Types are available to calling code such as a custom controller.

**Steps to reproduce the bug**
Create a basic controller. Import "istio.io/client-go/pkg/apis/networking/v1alpha3"

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
  branch = "master"
  name = "istio.io/client-go"
  packages = ["pkg/apis/networking/v1alpha3"]
  revision = "97bfafa2744d19a4953eb9a70e2300fd920a8d72"

**How was Istio installed?**
dep ensure

**Environment where bug was observed (cloud vendor, OS, etc)**
Development environment. Local build.

**Comment by howardjohn** [comment]
@rcernich  @nrjpoddar

**Comment by nrjpoddar** [comment]
The PR addresses only a partial fix, we need to regenerate client code and then close this issue.

**Comment by rcernich** [comment]
I'll regenerate the client once a new tools image is available.

**Comment by jasonwzm** [comment]
Note that we will need to cherrypick for 1.4 release.

**Comment by nrjpoddar** [comment]
This is fixed in master of istio.io/client-go as I have an example package using the generated code successfully: https://github.com/istio/client-go/pull/16
