### ISSUE TITLE
Missing required field "selector" in io.k8s.api.apps.v1.DaemonSetSpec in file tests/util/localregistry/localregistry.yaml

### ISSUE THREAD

**Issue by wangluochao902** [istio/istio#17705]
**Bug description**
Hi, developers. We are developing a tool to find potential bugs in Kubernetes configuration files. I found out a potential problem of the file `tests/util/localregistry/localregistry.yaml`. It may miss a required field `"selector"` for document starting from [line 65](https://github.com/istio/istio/blob/8145bf0b6b35287be714a87e592428736de53d4a/tests/util/localregistry/localregistry.yaml#L65).
Also, I use `"kubectl"` to validate the file, after I run

`kubectl apply -f tests/util/localregistry/localregistry.yaml --dry-run=true`

I got the following error:
```error validating data: ValidationError(DaemonSet.spec): missing required field "selector" in io.k8s.api.apps.v1.DaemonSetSpec; if you choose to ignore these errors, turn validation off with --validate=false```

Would you please verifying it is a real bug or not?

**Expected behavior**
No error

**Steps to reproduce the bug**
`kubectl apply -f kubernetes-handbook/examples/projected-volume.yaml --dry-run=true`

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:47:22Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-gke.2", GitCommit:"c9de33b5439df6e206d7ba646787c6ace92d737b", GitTreeState:"clean", BuildDate:"2019-09-06T18:30:33Z", GoVersion:"go1.12.9b4", Compiler:"gc", Platform:"linux/amd64"}
```
**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**
Google Cloud

**Comment by howardjohn** [comment]
Seems broken, the right fix here is to delete the whole localregistry folder though, it is not used anymore
