### ISSUE TITLE
Ability to suppress config analysis messages per-resource

### ISSUE THREAD

**Issue by selmanj** [istio/istio#17703]
**Describe the feature request**
`istioctl experimental analyze` reports a variety of errors and warnings. Not all of these are necessarily bad, and it would be nice to be able to suppress certain messages.

For example, I'm considering an analyzer that warns if a workload is behind multiple services (which makes it difficult/impossible for telemetry to discover what service to associate with outgoing requests). However there are times where this is deliberate, and it's annoying to continue complaining to the user about it.

Proposed solution: The user adds an annotation to the resource with the error code to suppress (e.g. `kubectl annotate istioctl-suppress-code-IST0105=true` or`kubectl annotate istioctl-suppress-codes=IST0105, IST0101` - the first one seems easier for users to incrementally add/remove).

The message generation code in galley suppresses/filters any messages on resources that have this annotation.

**Describe alternatives you've considered**
Ideally we'd be able to suppress via command line flags or explicit configuration. I don't think this feature precludes that, however.

**Affected product area (please put an X in all that apply)**

[X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Comment by selmanj** [comment]
I put together a small, hopefully unsurprising RFC doc here about how we might solve this:
https://docs.google.com/document/d/11a1p0Exi_n_-rGi59l1X9AHH8iFgvdFOMQu0HU4wbss/edit?usp=sharing

**Comment by selmanj** [comment]
Wrong link, see https://docs.google.com/document/d/1r1hOBIwkDesZ8vYaHMj2YThEcUxegB-fLMPBst_yXIU/edit#heading=h.xw1gqgyqs5b (this one is in the UX working group)

**Comment by esnible** [comment]
I prefer `kubectl annotate istioctl-suppress-codes=IST0105, IST0101`, even though it is hard to incrementally add/remove.  We want all annotations to appear on https://istio.io/docs/reference/config/annotations/ , and it seems confusing to have one called `istioctl-suppress-code-<x>`

**Comment by selmanj** [comment]
I plan on doing this, but am waiting for the doc to get reviewed, and for me to make a bit more progress on some other analyzers first...

**Comment by sushicw** [comment]
https://github.com/istio/istio/pull/19375 is a good example of a case where we want to make it easy to suppress a message. This particular one probably should be suppressible at the Code level across all resources.

**Comment by selmanj** [comment]
Closed via #20174
