### ISSUE TITLE
Rate Limiting does not accurately respect rate = maxAmount / validDuration

### ISSUE THREAD

**Issue by balamuru** [istio/istio#17704]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
When configuring rate limiting, it is not possible to configure an accurate rate when using a low valued ```validDuration``` value

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**
 eg. assume I'd like to limit rate to 5 requests / sec . 
If I configure the rate limiting ```handler``` with 
```
        maxAmount: 5
        validDuration: 1s
```
and subject the service to a low traffic rate (say 1 call / sec), many of the calls will still fail with 429
On the other hand,  if I configure a larger interval and proportionately increase the maxAmount, the rate limiter behaves closer to expectations
```
        maxAmount: 50
        validDuration: 10s
```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
$ istioctl version --remote
client version: 1.3.0
control plane version: 1.3.0

**How was Istio installed?**
helm
**Environment where bug was observed (cloud vendor, OS, etc)**
rancher kubernetes (applies to other kubernetes distros too)
Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by douglas-reid** [comment]
This is (almost) by design, based on quota prefetching and the various enforcement mechanisms within Mixer.  Low value `validDuration`s aren't well-supported, unfortunately.

**Comment by jonnysgomes** [comment]
I have the same behaviour that @balamuru when I apply rate limiting to a HTTP service. But when I do it to a HTTPS service the rate limiting does not work. Is there any diference to apply rate limiting to HTTPS endpoints?

My context:
The Ingress Gateway does the TLS termination;
I have a DestinationRule that applies TLS mode simple to my service port (8443).

**Comment by argeualcantara** [comment]
@douglas-reid 
I'm also unable to use rate limiting with https. In my case I'm using the gaeway with TLS mode passthrough. The rate limit simply does not work and gets completely ignored, the same rate limit  config, when applied to a HTTP service I have deployed works. 
Any clue to why that happens, is it by design?

**Comment by douglas-reid** [comment]
@jonnysgomes @argeualcantara it is probably best to move HTTPS discussions to a different forum. With passthrough TLS, a number of HTTP features won't work. I believe tracing and rate limit enforcement are both in that category. This is because passthrough TLS is treated as TCP traffic. If you look at the config dump for an ingressgw, you'll likely find `envoy.tcp_proxy` as the filter for your passthrough tls clusters.

**Comment by jonnysgomes** [comment]
Thanks for your reply @douglas-reid . As you've suggested, I've oppened another forum to discuss it. Please take a look [here](https://github.com/istio/istio/issues/19580). I'd like to ask you to answer there just to maintain the tracking of this discussion.

**Comment by rodrigo-fleischmann-gmail-com** [comment]
@douglas-reid , I am facing pretty much the same scenario described in this issue. As you mentioned that rate limit is not enforced with passthrough TLS, would rate limit work if I use mTLS at the mesh level and my applications goes through HTTP?

**Comment by balamuru** [comment]
Thanks for the clarity

**Comment by bogiva** [comment]
> This is (almost) by design, based on quota prefetching and the various enforcement mechanisms within Mixer. Low value `validDuration`s aren't well-supported, unfortunately.

Could you, please be more specific? What does a low value mean?

**Comment by douglas-reid** [comment]
@bogiva I don't have hard numbers and haven't done exhaustive testing. based on experience with other systems, I tend to think that durations of around ~100s are probably about right.  Of course, this means that it is possible to exhaust all your quota quickly / take more RPS than you may want. The way everything is put together is not meant to support precise quotas, and behaves less consistently for small windows and small limits.

**Comment by bogiva** [comment]
Thanks @douglas-reid. I have one more question - how about recommendations regarding bucketDuration? If validDuration is 100s, what should we use for bucketDuration? The documentation does not really describe what this field is doing and I could not get much looking at the code too (I got to the point where a lua script is called but could not find the script itself to check how this parameter is used). Can you also point to the lua script?
