### ISSUE TITLE
galley doesn't automatically reload the private key when it changes

### ISSUE THREAD

**Issue by ayj** [istio/istio#17739]
Steps to reproduce:

1) install Istio
2) kubectl -n istio-system scale deployment istio-citadel --replicas=0
3) kubectl -n istio-system delete secret istio-ca-secret
4) kubectl -n istio-system scale deployment istio-citadel --replicas=1
5) kubectl -n istio-system delete istio.istio-galley-service-account
6) kubectl apply -f samples/bookinfo/networking/bookinfo-gateway.yaml

**Comment by ayj** [comment]
Observable behavior includes validation failures with ` "x509: certificate signed by unknown authority"` error messages.

**Comment by howardjohn** [comment]
@ayj do your recent PRs address this?

**Comment by ayj** [comment]
This is fixed by https://github.com/istio/istio/pull/17995
