### ISSUE TITLE
Upgrade from 1.3.1 to 1.3.2, x-forwarded-for lost

### ISSUE THREAD

**Issue by springrain** [istio/istio#17746]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

When using 1.3.1, request pod application, header can get x-forwarded-for, after upgrading to 1.3.2, x-forwarded-for is lost,But remoteHost and x-real-ip is right.

I am nginx reverse proxy NodePort 31380 port. Visit nginx--->istio31380--->VirtualService-->Pod, version 1.3.2 can not get x-forwarded-for in Pod, 1.3.1 can.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
The pod application can get x-forwarded-for
**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
`istioctl version --remote`
client version: 1.3.2
citadel version: 1.3.2
egressgateway version: 1.3.2
galley version: 1.3.2
ingressgateway version: 1.3.2
pilot version: 1.3.2
policy version: 1.3.2
sidecar-injector version: 1.3.2
telemetry version: 1.3.2

`kubectl version`
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T16:51:36Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**

kubectl apply -f istio-demo.yaml

**Environment where bug was observed (cloud vendor, OS, etc)**

CentOS Linux release 7.7.1908 (Core)
Linux 5.2.1-1.el7.elrepo.x86_64

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by PiotrSikora** [comment]
cc @lambdai

**Comment by fpesce** [comment]
@springrain would you mind providing a simple way to reproduce the behavior you're observing?

**Comment by lambdai** [comment]
I installed bookinfo istio example 1.3.1 and 1.3.2
Then I turn on debug log on product svc sidecar proxy and run `curl -s http://${GATEWAY_URL}/productpage`
I see `x-forward-for` on both 1.3.1 and 1.3.2

1.3.1
```
[2019-10-10 21:24:35.027][27][debug][router] [external/envoy/source/common/router/router.cc:402] [C49][S17650124278696453546] cluster 'inbound|9080|http|productpage.default.svc.cluster.local' match for URL '/productpage'
[2019-10-10 21:24:35.027][27][debug][router] [external/envoy/source/common/router/router.cc:515] [C49][S17650124278696453546] router decoding headers:
':authority', '35.226.31.11'
':path', '/productpage'
':method', 'HEAD'
':scheme', 'http'
'user-agent', 'curl/7.58.0'
'accept', '*/*'
'x-forwarded-for', '10.8.0.1'
'x-forwarded-proto', 'http'
```

1.3.2
```
[2019-10-10 22:04:37.502][31][debug][router] [external/envoy/source/common/router/router.cc:402] [C41][S8377222730686235676] cluster 'inbound|9080|http|productpage.default.svc.cluster.local' match for URL '/productpage'
[2019-10-10 22:04:37.502][31][debug][router] [external/envoy/source/common/router/router.cc:515] [C41][S8377222730686235676] router decoding headers:
':authority', '34.66.198.115'
':path', '/productpage'
':method', 'GET'
':scheme', 'http'
'user-agent', 'curl/7.58.0'
'accept', '*/*'
'x-forwarded-for', '10.128.0.8'
```
No difference.

@springrain Could you provide more concrete description? At which hop you want to see the x-forward-for?

**Comment by springrain** [comment]
> I installed bookinfo istio example 1.3.1 and 1.3.2
> Then I turn on debug log on product svc sidecar proxy and run `curl -s http://${GATEWAY_URL}/productpage`
> I see `x-forward-for` on both 1.3.1 and 1.3.2
> 
> 1.3.1
> 
> ```
> [2019-10-10 21:24:35.027][27][debug][router] [external/envoy/source/common/router/router.cc:402] [C49][S17650124278696453546] cluster 'inbound|9080|http|productpage.default.svc.cluster.local' match for URL '/productpage'
> [2019-10-10 21:24:35.027][27][debug][router] [external/envoy/source/common/router/router.cc:515] [C49][S17650124278696453546] router decoding headers:
> ':authority', '35.226.31.11'
> ':path', '/productpage'
> ':method', 'HEAD'
> ':scheme', 'http'
> 'user-agent', 'curl/7.58.0'
> 'accept', '*/*'
> 'x-forwarded-for', '10.8.0.1'
> 'x-forwarded-proto', 'http'
> ```
> 
> 1.3.2
> 
> ```
> [2019-10-10 22:04:37.502][31][debug][router] [external/envoy/source/common/router/router.cc:402] [C41][S8377222730686235676] cluster 'inbound|9080|http|productpage.default.svc.cluster.local' match for URL '/productpage'
> [2019-10-10 22:04:37.502][31][debug][router] [external/envoy/source/common/router/router.cc:515] [C41][S8377222730686235676] router decoding headers:
> ':authority', '34.66.198.115'
> ':path', '/productpage'
> ':method', 'GET'
> ':scheme', 'http'
> 'user-agent', 'curl/7.58.0'
> 'accept', '*/*'
> 'x-forwarded-for', '10.128.0.8'
> ```
> 
> No difference.
> 
> @springrain Could you provide more concrete description? At which hop you want to see the x-forward-for?

I am nginx reverse proxy NodePort 31380 port. Visit nginx--->istio31380--->VirtualService-->Pod, version 1.3.2 can not get x-forwarded-for in Pod, 1.3.1 can

**Comment by springrain** [comment]
`Pod里获取的header`

"sec-fetch-mode":"navigate",
"x-request-id":"d39c1c6f-33b2-9c0a-b47e-50b4c3749b0d",
"content-length":"0",
"x-b3-parentspanid":"c5e9aff4190f6646",
"sec-fetch-site":"none",
"x-forwarded-proto":"http",
"accept-language":"zh-CN,zh;q=0.9",
"remoteHost":"117.158.210.228",
"x-b3-sampled":"0","sec-fetch-user":"?1",
"accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3",
"x-real-ip":"117.158.210.228",
"x-envoy-external-address":"192.168.0.202",
"x-b3-traceid":"44688238a409818fc5e9aff4190f6646",
"x-b3-spanid":"cf8d1673ac7165a0",
"host":"443.aibianli.com",
"upgrade-insecure-requests":"1",
"cache-control":"max-age=0",
"accept-encoding":"gzip, deflate, br",
"user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"

**Comment by lambdai** [comment]
It's not helpful when you just dump your application headers. We still don't know where is it stripped.

Could you dump the proxy config of istio-31380 and the config of application pod? I assume it's a sidecar proxy powered by envoy
You can mask out the RDS part. We only need the http_conn_manager config. More precisely the `useRemote`

You can also find the log of each hop of istio-proxy by
```
export POD=YOUR_NGINX_POD and then YOUR_APPLICATION_POD
kubectl exec -it pod/$POD -c istio-proxy -- curl -X POST localhost:15000/logging?route=debug and you can then run 
k logs  pod/$POD -c istio-proxy 
```
Then you will see the logs of headers from envoy's view.
```
[2019-10-10 22:04:37.502][31][debug][router] [external/envoy/source/common/router/router.cc:515] [C41][S8377222730686235676] router decoding headers:
```

**Comment by howardjohn** [comment]
Could not reproduce.

Please give the full config you used to find the problem and the info above

**Comment by duderino** [comment]
@lambdai isn't this already fixed?  Is this a duplicate?

**Comment by lambdai** [comment]
Still looking
The work around is to use x-envoy-external-address
https://www.envoyproxy.io/docs/envoy/v1.11.0/configuration/http_conn_man/headers#x-envoy-external-address

```
It is a common case where a service wants to perform analytics based on the origin client’s IP address. Per the lengthy discussion on XFF, this can get quite complicated, so Envoy simplifies this by setting x-envoy-external-address to the trusted client address if the request is from an external client. x-envoy-external-address is not set or overwritten for internal requests. This header can be safely forwarded between internal services for analytics purposes without having to deal with the complexities of XFF.
```

**Comment by lambdai** [comment]
Additional comment: 
I use httpbin and I don't see X-F-F on 1.3.1 and 1.3.4
remoteHost and x-real-ip are correct only because envoy deem them as payload header.

**Comment by howardjohn** [comment]
@lambdai so there is no envoy bug here?
