### ISSUE TITLE
Operator logs error messages to stdout instead of stderr

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#17743]
This makes doing things like `istioctl manifest generate > file.yaml` unusable. Example error:
```
could not unmarshal the overlay file: unknown field "imagePullPolicy" in v1alpha2.IstioControlPlaneSpec

Original YAML:
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  hub: foo123
  tag: foo123
  imagePullPolicy: foo123
```

**Comment by elfinhe** [comment]
https://github.com/istio/operator/blob/master/cmd/mesh/shared.go#L83
maybe we can change this line, I will create a PR.

**Comment by ostromart** [comment]
We need a bit more work on this. logtostderr is not the same as having errors show up in stderr.

**Comment by howardjohn** [comment]
This breaks `ik manifest migrate install/kubernetes/helm/istio/test-values/values-e2e.yaml > file`

**Comment by ostromart** [comment]
Could you ptal @richardwxn ?

**Comment by ostromart** [comment]
Actually, I created a new issue for this, seems it's not really related to error logging:
https://github.com/istio/istio/issues/18289

**Comment by ostromart** [comment]
I think this is important for release. @elfinhe, would you mind taking another look? It's just a matter of sorting all the outputs correctly into stdout and stderr, ping me if you need help.

**Comment by elfinhe** [comment]
> I think this is important for release. @elfinhe, would you mind taking another look? It's just a matter of sorting all the outputs correctly into stdout and stderr, ping me if you need help.

Sure, I will work on this later today.

**Comment by elfinhe** [comment]
@ostromart  This is more complicated than I thought. But I can start with `manifest generate`, `profile dump` use cases, where --logtostderr is more helpful.

**Comment by elfinhe** [comment]
Reopening because when --logtostderr is specified, INFO log still goes into stdout. stdout is mixed with both INFO log and manifests.
