### ISSUE TITLE
Distroless version of install-cni

### ISSUE THREAD

**Issue by jfourment** [istio/istio#17742]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

All images but install-cni have been moved to a distroless image. It would be nice to have install-cni also converted to distroless

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
This would be nice. At the very least we should retag as distroless so you can just set the flag globally and not have to do anything special for cni

**Comment by jfourment** [comment]
It would be great to mention the cni image in the list of non-updated images here: https://istio.io/docs/ops/security/harden-docker-images/
