### ISSUE TITLE
RDS vs LDS for HTTP routes

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1774]
Currently, HTTP routes are captured on wildcard listeners 0.0.0.0:<http_port>. That means that combined routes for multiple HTTP services on <http_port> are aggregated in RDS, and Envoy selects a route using virtual host domains within the same listener.

An alternative design is to instead capture on the <http_service_ip>:<http_port> and avoid using virtual host selection. RDS becomes optional and multiple services are only aggregated at the LDS level, which seems to offer better de-coupling in terms of xDS.

Any downsides in switching over to the alternative design? There's a change in the error behavior: traffic sent to HTTP port gets terminated at TCP rather than 404'ing at HTTP level. This change does not seem to be that important.

@rshriram am I missing something?

**Comment by ayj** [comment]
This is for inbound and outbound routes? For outbound routes, how would this would work if a source workload tried to reach a destination service through the destination workload IP or explicitly through the proxy via localhost?

**Comment by kyessenov** [comment]
Both are not supported for iptables-based routing. Direct workload IP addressing requires a dedicated port right now. Explicit routing through a middle proxy is a distinct problem.

**Comment by kyessenov** [comment]
cc @louiscryan as for gateways, since we don't have dedicated gateway IP, we can fallback to the wildcard listener. Better granularity should help with less config churn in the long run, it's strange than an HTTP route affects all routes for the same port at the moment.

**Comment by ayj** [comment]
Supported as-in we don't want to support that feature, or it won't work with current code? I thought we handled direct workload IP at one time and the iptable rules should allow for workloads to reach proxy directly via localhost and rely on host header for routing.

**Comment by kyessenov** [comment]
I think it's something we don't want to support in sidecars.
Middle proxy (which is what you're referring for explicit addressing) was always a separate proxy deployment model. This could be a per-node deployment, or a dedicated service. Sidecars assume iptables redirect, and that's what we support and optimize for at the moment.

Direct workload IP never worked for outbound requests. There's special handling code to allow headless services but that comes with an extra assumption of port uniqueness.

**Comment by kyessenov** [comment]
There's one extra upside of not parsing hosts - IPs are not contextualized by source, while authority headers differ between DNS contexts.

**Comment by ayj** [comment]
I was considering explicit addressing in the context of consistent transparent proxying (network capture). There might be confusion around inconsistent auth/policy between services depending on how that remote service was addressed.

**Comment by kyessenov** [comment]
In k8s, we should only support addressing via VIP when it's available in the sidecar. The issue seems to be Consul environment, with no VIPs assigned. Perhaps, may need both modes of operation. The current way is somewhat strange as it routes based on HTTP port, but not HTTP destination IP. If we do transparent proxying then we should rely on both matching the expectation, and if we don't, then we're free to not use the same port.

**Comment by rshriram** [comment]
One advantage of the vip thing is that metrics might be better.

As you pointed out, there are no vips outside kubernetes. Esp in cf.

Even dns might not exist, ie we didn’t have a requirement that sidecar will
always trap by iptables. We made it a point to allow direct access to the
proxy. You can talk to localhost proxy to do your routing. For non
transparent proxy, service ports need to be unique and service port should
not be the same as vm port. With this, non transparent proxying should
work, without any vips.

We also need the port based thing for headless services.

Within a listener, we still need RDS. If I have few 10s of rewrites or path
matches, I would have to reload entire listener for adding or removing
routes. Reload means listeners get drained. RDS is instantaneous iirc.

Also when auth certificates need to be reloaded, we would have a large
number of listeners being drained every few minutes (through hot restart).
In a system where we have a 100 services, having a 100 listeners sharing
2-3 distinct ports seems strange.

The LDS payload and churn will be pretty high right?

I don’t mind exploring this option to see where it leads us - but we need
to have a fallback immediately. We have always been thinking of folding RDS
into LDS and eds into CDS.

**Comment by louiscryan** [comment]
This relates to the listener split work that Piotr is doing.

https://github.com/istio/istio/issues/6259

**Comment by costinm** [comment]
Extracting from Shriram's comments and adding few: 
1. Stateful sets / headless services
2. Non k8s environments (we could solve this once we do our own DNS - but it's not scheduled for 1.0)

I think we could do it for k8s and services that have cluster VIPs, it's also not a huge change - but 
we still need port-based capture for at least the 2 cases above.

**Comment by rshriram** [comment]
I thikn the LDS churn would be too high. Coupled with the fact that @kyessenov complained that disabling RDS from LDS caused mixer filter's cache to go haywire, we are looking at a LDS+RDS request for every service in the system. Which seems wasteful given that we can collapse all http listeners on a port into a single listener with a single RDS call.
