### ISSUE TITLE
Mixer poorly load-balances to zipkin service

### ISSUE THREAD

**Issue by maxbischoff** [istio/istio#17754]
**Bug description**

When using the mixer zipkin adapter, with jaeger-collector as zipkin service, mixer sends its generated spans to the same jaeger-collector instance. It seems like the zipkin reporter is reusing the tcp connection to jaeger-collector as long as possible. This makes it hard to horizontally scale jaeger-collector, as at most one collector instance is used per mixer instance. Even worse, when multiple mixers and collectors are in play, collectors can go unused.

A possible solution might be customizing the client used in the [zipkin adapter's reporter](https://github.com/istio/istio/blob/20a7a7f0cc072b2aa23ba919a9e6acdc587e4823/mixer/adapter/zipkin/zipkin.go#L91) to break up connections regularly.  

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[x] Performance and Scalability
[x] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Mixer should load balance its requests evenly across zipkin instances.

**Steps to reproduce the bug**

Use mixer based tracing with the zipkin adapter. Deploy a test application that sends many spans (I tested around 2k spans/sec from 30 instances of my test application). Scale mixer to 2 instances and jaeger-collector to at least 2 instances. You should observe, that only one ore two instances are used. Restarting mixer will result in the new instance latching randomly to one collector instance (as expected in round-robin load balancing)

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

`istioctl version --remote`
```
client version: 1.2.6
citadel version: 1.2.6
galley version: 1.2.6
galley version: 1.2.6
pilot version: 1.2.6
pilot version: 1.2.6
policy version: 1.2.6
policy version: 1.2.6
sidecar-injector version: 1.2.6
sidecar-injector version: 1.2.6
telemetry version: 1.2.6
telemetry version: 1.2.6
```

`kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

Using the helm-chart, with jaeger being installed separately from the jaeger helm-chart

**Environment where bug was observed (cloud vendor, OS, etc)**
bare-metal kubernetes cluster

**Comment by bianpengyuan** [comment]
Could you send a PR for this? Seems like you already have a solution.

**Comment by maxbischoff** [comment]
I do not have a solution at the moment. I think one possibility would be tweaking the default Go http client to use a shorter connection max TTL, but I didn't figure out the implementation details for that yet.
Is there a preferred solution or an other solution you can think of? The ideal behavior for my use-case would be, that mixer batches many spans, sends one request with those to the zipkin backend and immediately drops the connection afterwards. But this solution might be extreme.
If you could help me identify the most important parameters to tweak, we could also simply add them to the [mixer adapter API resource](https://istio.io/docs/reference/config/policy-and-telemetry/adapters/zipkin/) and let operators tweak it there. Would that make sense for you?

**Comment by bianpengyuan** [comment]
If openzipkin http client does not handle load balancing well or provide any knobs to control it, it is more like an issue that should be raised to them instead of hack a solution inside adapter. Would you mind raising a question in the openzipkin go library repo instead?
