### ISSUE TITLE
gateway perf: restrict cds clusters to only those required by the gateway

### ISSUE THREAD

**Issue by rshriram** [istio/istio#17753]
@istio/wg-networking-maintainers-pilot 

We have avoided this problem till date but fixed it for sidecars. Sidecars decide on the services to generate a cluster for, using the sidecar CRD. But for gateways, we have no such mechanism. In small-average clusters, this is not a problem. But in very large clusters (one of our customers has about 1000+ services!!), this quickly becomes a big problem in terms of memory usage at the gateway, as well as making it hard to debug things. 

In the past (before 0.8), we used to return the list of clusters in almost every function (route generation, listener generation) and collect all these clusters and fix them up. This technique turned out to be very error prone and hard to maintain. So we should avoid going down this path again.

One option is to create some transient xds context in the Node struct, collect the set of all cluster names and perhaps the services [no subsets], ports associated with the cluster as well. And then in the CDS code for gateway, we could look at all the entries with a valid service+port and generate clusters only for those. This seems to be the least intrusive option that I can think of. This would require updating the context in httproute/route, tls.go, networkfilter.go, etc. We also need to be very careful in future to update this context in all places where a cluster is referred to. Otherwise we end up getting 503s or connection issues due to missing clusters.

Thoughts? We should be able to get this into 1.4 pretty easily

**Comment by rshriram** [comment]
A more detailed form of https://github.com/istio/istio/issues/11936

**Comment by hzxuzhonghu** [comment]
Another option: infer the needed clusters from gateway and virtualservice. But donot forget to handle multiclusters gateway.

**Comment by howardjohn** [comment]
Didn't @mandarjog do this at some point but the PR was dropped?

**Comment by mandarjog** [comment]
There were 3 sides
1. Use gw and vs to figure out the clusters that are needed.
2. Ability to opt out for mcg
3. Process EnvoyFilter api for its dependencies.
4. A way to keep required clusters like mixer etc.

I had implemented and tested 1,2,4 . 
At that time i needed equivalent to sidecar’s egress field on gateways.

**Comment by hzxuzhonghu** [comment]
@mandarjog Can you link the old pr?

**Comment by rshriram** [comment]
> A way to keep required clusters like mixer etc.
Isn't mixer cluster added via bootstrap? pilot, als, metrics, tracing clusters are added via bootstrap. So they will always be there. If this is the case, then users (without multicluster) can trim the clusters at the Gateway by setting the SNI-DNAT to false by default.

With that, we are now down to reducing the normal clusters at the gateway - one short cut is to look at the host spec in the gateway. If the hostspec is of the form namespace/host, then we can import that namespace. IOW, if we tell users to only use the namespace/host format, then we will get a list of namespaces to import and we could do some trimming. This will still be not perfect compared to the logic I originally outlined but its better than nothing.
