### ISSUE TITLE
Istio not logging blocked traffic

### ISSUE THREAD

**Issue by bturbes** [istio/istio#17759]
**Bug description**

The release notes for istio 1.3 say, “Added telemetry reporting for traffic destined to the Passthrough and BlackHole clusters”. Unless I am misunderstanding the purpose of the BlackHole cluster, when we have an outboundTrafficPolicy of `REGISTRY_ONLY`, blocked outgoing traffic should go to the BlackHole cluster and be logged. This older issue describes the same problem, but does not appear to have been fixed. https://github.com/istio/istio/issues/14110

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
istio-proxy sidecar logs blocked external traffic

**Steps to reproduce the bug**
In a cluster with an outboundTrafficPolicy of `REGISTRY_ONLY`, make a curl request to anything (without a service entry allowing it). Request is blocked but not logged.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```
$ istioctl version --remote
client version: unknown
citadel version: 1.3.1
citadel version: 1.3.1
egressgateway version: 1.3.1
egressgateway version: 1.3.1
galley version: 1.3.1
galley version: 1.3.1
ilbgateway version:
ilbgateway version:
ingressgateway version: 1.3.1
ingressgateway version: 1.3.1
pilot version: 1.3.1
pilot version: 1.3.1
policy version: 1.3.1
policy version: 1.3.1
sidecar-injector version: 1.3.1
sidecar-injector version: 1.3.1
telemetry version: 1.3.1
telemetry version: 1.3.1
```
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-gke.19", GitCommit:"bebe882824db5431820e3d59851c8fb52cb41675", GitTreeState:"clean", BuildDate:"2019-07-26T00:09:47Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}
```
**How was Istio installed?**
Helm chart

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE cluster

**Comment by howardjohn** [comment]
I think its in metrics only not logs. Is that right @nrjpoddar ?

**Comment by nrjpoddar** [comment]
Yes, we only added telemetry support. Just for clarity, when you mean logging, are you talking about Envoy or Mixer. Mixer should be both access logging and generating metrics for BlackHole.

It's a reasonable feature request to support Envoy access logging in all cases, if that's what you want.

**Comment by bturbes** [comment]
It sounds like I just misunderstood the release notes then.

Here's a hopefully more clear example of the behavior we're looking for. Let's say I have the following ServiceEntry.
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: google-test
  namespace: default
spec:
  exportTo:
  - .
  hosts:
  - www.google.com
  location: MESH_EXTERNAL
  ports:
  - name: https
    number: 443
    protocol: TLS
  resolution: DNS
```
Then we can run a any pod in that namespace with curl on it.
```
kubectl -n prometheus run --generator=run-pod/v1 tmp-shell --rm -i --tty --image nicolaka/netshoot bash
```

From here if we run `curl https://www.google.com/` we'll get a successful response and see the request logged in both istio-proxy and in mixer. If we run `curl https://facebook.com/` the request will fail (as expected), but will not be logged in either istio-proxy or mixer.

**Comment by esauser** [comment]
We are also looking to gain visibility on blocked traffic.  Is this possible currently?  If not, can it be added?

**Comment by mdhume** [comment]
@nrjpoddar We are running into a similar issue. The issue comes when you have a listener such as 0.0.0.0_443 with filter chains with a filter chain match on server_names - https://gist.github.com/mdhume/bf262a5ec426d37e6aa94ddfeb328760 . If a request comes on a domain that is not in the filter chain match e.g. `www.cnn.com` then even though the correct listener gets matched, it does not match any filter chain and hence the request gets dropped. Such requests are not getting reported any where - not in access logs nor in metrics.
