### ISSUE TITLE
Question about incremental push of MCP

### ISSUE THREAD

**Issue by nkorange** [istio/istio#17750]
For incremental MCP message, can I send a subset endpoints of a service to Pilot so that Pilot can either add these endpoints to the service or remove them from the service?

**Comment by nkorange** [comment]
@hzxuzhonghu Is this some extending of current MCP protocol? I don't see annotations in current MCP message.

**Comment by Nino-K** [comment]
@nkorange annotations are part of MCP protocol's [metadata](https://github.com/istio/api/blob/a7165be19fef7f62f4eefde64e0ab62e131b1948/mcp/v1alpha1/metadata.pb.go#L73).

**Comment by nkorange** [comment]
@Nino-K OK, I'm studying your PR now.

**Comment by nkorange** [comment]
Does Pilot currently support incremental MCP service entry message at service level described in https://github.com/istio/api/tree/master/mcp?

**Comment by Nino-K** [comment]
@nkorange The standard MCP controller (the one that listens for all the config types) in pilot currently sends a full update (no incremental) for all the configs that it receives over MCP [here](https://github.com/istio/istio/blob/master/pilot/pkg/config/coredatamodel/controller.go#L195) and [here](https://github.com/istio/istio/blob/ecbed5df617655d6aa72a7b9d19204294fecf7c5/pilot/pkg/bootstrap/server.go#L547) however in the newController (only Service Entry controller) in PR #12276 depending on the incremental flag set on the MCP messages will send either full update or incremental endpoint updates, hope that answer your question.

**Comment by nkorange** [comment]
@Nino-K I see, the configStore of Controller stores all the received data disregarding the incremental flag of the resource.

But for ServiceEntry, I think the subsequent handling process goes into:
https://github.com/istio/istio/blob/d987b85f52bb9fa5937caa6d590c31ed5ffc5882/pilot/pkg/config/coredatamodel/controller.go#L193

In that method, update/add/delete event is dispatched according to its Metadata.version.
