### ISSUE TITLE
build fails on linux (gubuntu)

### ISSUE THREAD

**Issue by theganyo** [istio/istio#1776]
As of commit: 390f196bfbdd3b04f64dd163cf360b7bc9d9509b
bazel version: 0.6.1
```
$ bazel build //...
INFO: Analysed 414 targets (0 packages loaded).
INFO: Found 414 targets...
ERROR: missing input file '//pilot/platform/kube:config'
ERROR: /usr/local/google/home/theganyo/istio/pilot/adapter/config/crd/BUILD:44:1: //pilot/adapter/config/crd:go_default_test: missing input file '//pilot/platform/kube:config'
ERROR: /usr/local/google/home/theganyo/istio/pilot/adapter/config/crd/BUILD:44:1 1 input file(s) do not exist
INFO: Elapsed time: 0.814s, Critical Path: 0.18s
FAILED: Build did NOT complete successfully
```

**Comment by ozevren** [comment]
Once you create/have a kube config, soft-linking to that folder works:

ln -s ~/.kube/config istio/pilot/platform/kube

**Comment by theganyo** [comment]
I don't have kubernetes on that box. Is that a requirement now?

**Comment by theganyo** [comment]
Ok. I got it. I created an empty file at ~/.kube/config. It builds now, so Kubernetes isn't required. It's just a bug in the build expectations.

**Comment by jmuk** [comment]
`make setup` will create the symlink too.

Some pilot tests actually want to connect to kubernetes cluster. An empty file would fix the build, but I think such tests will fail. cc @kyessenov

**Comment by pipejakob** [comment]
Since the [dev guide](https://github.com/istio/istio/blob/f1f06f01ed44fd91db6b63c8e102fe06820c6cae/DEV-GUIDE.md#building-the-code) recommends using `make build`, which is still broken if you don't have an existing `$HOME/.kube/config` file, I've created a patch to address it: https://github.com/istio/istio/pull/1950.
