### ISSUE TITLE
certificate revocation support

### ISSUE THREAD

**Issue by dontreboot** [istio/istio#17763]
**Describe the feature request**
Add certificate revocation support for citadel.

**Describe alternatives you've considered**
Use short-lived TTL workload certificates

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**
https://github.com/istio/istio/issues/7990#issuecomment-416782153

**Comment by myidpt** [comment]
/cc @JimmyCYJ  

Envoy supports CRL, it can be loaded from a local file or transferred over the xDS channel (from Pilot).
https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/cert.proto.html?highlight=crl
But my thoughts:
* If we use the file path, we may have the issue that once file is updated, it is not reloaded by Envoy Maybe a hot restart is required, but this is to be verified.
* If we use inline CRL, it adds overhead to xDS server, as well as the xDS message. Which isn't scalable.
I think we can see:
1. If we use the file path, can we verify if Envoy can automatically reload the file once it's changed? If not, can we enable it?
2. If 1) is not feasible, can we use SDS to pass the CRL?

**Comment by JimmyCYJ** [comment]
We are using [combined_validation_context](https://github.com/envoyproxy/envoy/blob/1a8fac91951d4a3bc3f7fcc96f5adc86a8dab6fb/api/envoy/extensions/transport_sockets/tls/v3/cert.proto#L386). We can let Pilot fill this [CRL](https://github.com/envoyproxy/envoy/blob/1a8fac91951d4a3bc3f7fcc96f5adc86a8dab6fb/api/envoy/extensions/transport_sockets/tls/v3/cert.proto#L327) in a default CertificateValidationContext, which is pushed via CDS. But we need API change to support Customer specify CRL in their deployment, and Pilot could pass that CRL into the default certificate validation context.

**Comment by ddseapy** [comment]
In case helpful, I'll share what we do for crl support on ingress gateway.  As some CRLs can be bigger than etcd allows, we have an istio fork using sds but that reads CRLs from redis.  When CRL changes, it puts the new file in the shared volume so that envoy can read it (would have had to increase grpc limit to use inline).  It alternates between 2 files (one current and one not) and updates the envoy configuration to point to the new one after writing.

Originally I put up a PR for CRL support via sds on ingress gateway, but things got a bit uglier when moving off k8s secret for CRL contents & so didn't go back and update the PR.  I'll definitely keep an eye on this ticket to see if its something we can use instead of maintaining our own fork.

**Comment by howardjohn** [comment]
related https://github.com/istio/istio/issues/7990

**Comment by nrjpoddar** [comment]
Is there any progress on this issue?

**Comment by sumanapaul** [comment]
I would also be interested to get a solution. In telecom world, OCSP and CRL support is mandatory in many usecases.

**Comment by abhide** [comment]
Not working on this. Moved it to unassigned.

**Comment by aterribili** [comment]
About @myidpt 's question:
> If we use the file path, can we verify if Envoy can automatically reload the file once it's changed? If not, can we enable it?

Could anyone confirm?

**Comment by spockz** [comment]
Is there any chance of getting this for CAs? For workload certificates we could rely on short TTL. In our case however we can not easily automate the generation of the CA certs. Combined with the lack of name constraint support for spiffe ids this means that if either of our 100s of clusters gets compromised it can generate workload certs for any workload in any of our clusters.

**Comment by dseapy** [comment]
In case it's helpful to others, using envoy external authorization with a container that validates envoy's xfcc header against the crl(s) for the ca(s) appears feasible as a workaround.

**Comment by kfaseela** [comment]
@ddseapy can we revive your [older PR for CRL support](https://github.com/istio/istio/pull/15110). I see the 1MB limitation discussion, however in most of the cases it is a reasonable limit. Seems like Contour has also done a similar implementation quoting the 1MB limitation as an open issue. https://github.com/projectcontour/contour/pull/4252/files 

For most of our telco usecases, 1MB is good enough.

**Comment by dseapy** [comment]
@kfaseela The company I was working at was definitely handling CRLs that were much larger that most use-cases, so the limitation definitely seems reasonable even though it didn't solve my particular need.

I unfortunately don't have time to pursue getting the changes into the codebase atm, so not sure reopening the PR would be best.  Maybe someone on your team can open a separate PR and copy/port over any changes to that?  Guessing since it's been a while there might be some differences, but hopefully it's still useful.

**Comment by kfaseela** [comment]
> @kfaseela The company I was working at was definitely handling CRLs that were much larger that most use-cases, so the limitation definitely seems reasonable even though it didn't solve my particular need.
> 
> I unfortunately don't have time to pursue getting the changes into the codebase atm, so not sure reopening the PR would be best. Maybe someone on your team can open a separate PR and copy/port over any changes to that? Guessing since it's been a while there might be some differences, but hopefully it's still useful.

Definitely okay for me to open a new PR and port the changes and adapt. Just wondering if 1MB limitation would be okay for the community overall.

**Comment by jacob-delgado** [comment]
CRL support is something that would be great to have, but the last time I looked there are many problems when implementing it. I don't think it'd be simple to add and test, but maybe only behind a way to add this as an experimental feature.

Here's a couple of issues:
1. Where is the CRL deployed for us to fetch? LDAP/HTTP?
2. Are we limited by only size of the CRL or by the number of items?
3. With short TTLs is implementing CRLs useful?
4. How are we going to deal with caches?

I'm sure there are other issues that I'm also not aware of, but perhaps this could be done as a proposal for us to get feedback rather than a single issue.

**Comment by DarthBlair** [comment]
Any progress?

**Comment by kfaseela** [comment]
> Any progress?

no we have not yet started on this.

**Comment by eHildy** [comment]
Any idea when it might be started. We'd love to use Istio in our system, but without CRL or at least OCSP, it's a non-starter.

**Comment by kfaseela** [comment]
@eHildy : We would need a design proposal first for this, which is not yet there, and I am currently stuck with some other higher priority tasks. If you think you can contribute that also would be great.

**Comment by sebltm** [comment]
We've needed the feature internally so we've started implementing it on top of the release1.15 branch. I've implemented a mostly-working OCSP Stapling for Gateways (only external certificates, not the Istio internal ones) on my fork: https://github.com/sebltm/istio/tree/gateway-ocsp any feedback would be appreciated. I recognize this wasn't done in the proper way with design documents etc but I'd love to adapt what I've done to fit the official contributing guides and merge it

**Comment by kfaseela** [comment]
@sebltm : Will you be able to come up with a design document to explain how this was done, and present this in one of our WG meetings?. That would help us decide whether the design is acceptable, and also reduce my effort on reimplementing if your design is already good enough :)

**Comment by sebltm** [comment]
Absolutely, though I'm new to the community: would you be able to guide me with an example of a past design document or a template that I could use?

**Comment by kfaseela** [comment]
@sebltm Here is the [RFC template](https://docs.google.com/document/d/16FLQK8uhhic1ovKnnOG3OXJjFKs2aHnSmbximidpKwM/edit#heading=h.xw1gqgyqs5b).  You can see how to get started in the community [here](https://istio.io/latest/get-involved/). Feel free to ping me on istio slack if you need any further info.

**Comment by lukbuc** [comment]
Hi @kfaseela, 

I need OCSP stapling as well.
Created PR draft #42837 satisfying my requirement. 
My use case seem a bit simpler than @sebltm 's. 
I'm looking for a way to forward OCSP staple from existing kubernetes secret to Envoy.
I'll be happy to prepare design document and present it on WG meeting.

**Comment by kfaseela** [comment]
> Hi @kfaseela,
> 
> I need OCSP stapling as well. Created PR draft #42837 satisfying my requirement. My use case seem a bit simpler than @sebltm 's. I'm looking for a way to forward OCSP staple from existing kubernetes secret to Envoy. I'll be happy to prepare design document and present it on WG meeting.

@howardjohn @lei-tang : would be great if you could suggest a way forward.

**Comment by howardjohn** [comment]
For me personally, I would need to see prior art from other products to make an informed decision. A doc would help captured that.

**Comment by lei-tang** [comment]
I concur with John's comment on preparing a doc for review.

**Comment by tsaarni** [comment]
I want to add an observation that this issue originally is about validating the revocation status of _downstream client certificate_.  

Another use case was brought up here https://github.com/istio/istio/issues/17763#issuecomment-1384811916.  OCSP stapling is surely an excellent feature, but it addresses a different use case: configuring a stapled OCSP response aims to support the downstream client to validate the revocation status of Istio's server certificate.

**Comment by lukbuc** [comment]
Hi, 

I raised PR for just Stage 1 which is forwarding OCSP staple to Envoy proxy.
Setting stapling mode on Envoy can be implemented as Stage 2 or EnovyFilter.

https://github.com/istio/istio/pull/43209

**Comment by kfaseela** [comment]
Here is the RFC for CRL support: https://docs.google.com/document/d/13LNbJnLHe_prlOg7sPr77PjLiIuGj452/edit?usp=sharing&ouid=105743966233121608166&rtpof=true&sd=true

**Comment by kfaseela** [comment]
Fixed by : https://github.com/istio/istio/pull/45104
