### ISSUE TITLE
istioctl analyze does not respect `sidecar.istio.io/inject: "false"` annotation

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#17771]
I ran `analyze` on my cluster and got about 100 instances of IST0103 " The pod is missing its Istio proxy", which is not correct; These should not be injected.

**Comment by howardjohn** [comment]
This is still relevant

**Comment by davidebbo** [comment]
Sorry, it wasn't on our Epic for some reason so we missed it earlier. It's on the radar now!
