### ISSUE TITLE
tools: Import IBM blueperf into the tools repo

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#17777]
IBM blueperf is a standard part of istio nightly test, but the code lives elsewhere.
Import Blueperf into the tools repo as /blueperf.

@vikramkhatri @muchida

I would like to see it split in 2 parts.
PR1. Create /blueperf directory and add readme files etc.
PR2. Code.

**Comment by vikramkhatri** [comment]
@mandarjog - Thanks. I will do that.

**Comment by mossuchida** [comment]
@mandarjog thank you.

**Comment by vikramkhatri** [comment]
@mandarjog - I was talking to Surya and he mentioned that should we put `blueperf` under `/tools`? Do you want this to be separate root level dir `/blueperf` or `/tools/blueperf` and then accordingly I will create the first PR.
