### ISSUE TITLE
mixc doc documents nonexistent `mixc quota` command

### ISSUE THREAD

**Issue by theganyo** [istio/istio#1778]
The command `mixc quota` doesn't exist, but is documented here:
https://istio.io/docs/reference/commands/mixc.html#mixc-quota

The correct command should be `mixc check -q=xxx` or `mixc check --quotas=xxx`.

**Comment by douglas-reid** [comment]
@geeknoid can you update the docs (with the new generator perhaps)?

**Comment by geeknoid** [comment]
Yep, this should be done in a couple days.

**Comment by geeknoid** [comment]
Docs are now clean.

**Comment by Nethminiromina** [comment]
```
Command 'mixc' not found, did you mean:

  command 'minc' from deb mblaze
  command 'mix' from deb elixir

Try: apt install <deb name>

```

But when I am trying to install it, 

```
$ sudo apt install mixc
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package mixc

```
How to fix this issue?

**Comment by douglas-reid** [comment]
from an `istio.io/istio` dir, you can type `make mixc`.

**Comment by Nethminiromina** [comment]
> from an `istio.io/istio` dir, you can type `make mixc`.

Thanks
