### ISSUE TITLE
bin/linters.sh still uses go1.8?

### ISSUE THREAD

**Issue by jmuk** [istio/istio#1779]
bin/linters.sh complains some of my local changes of using `t.Helper()` function which was added by go1.9.

linter is running within a docker container, so -- I think it runs with go runtime built on go 1.8?  Should we update to 1.9? The bazel build already uses 1.9.1.

**Comment by kyessenov** [comment]
Yes it does. Please re-build docker image for gometalinter (https://github.com/istio/istio/blob/master/pilot/docker/Dockerfile.lint)

**Comment by geeknoid** [comment]
Can we close this?

**Comment by jmuk** [comment]
yes, updated. closing.
