### ISSUE TITLE
istioctl analyze could use some color/syntax highlighting

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#17808]
Right now I get a huge blob of text, and its hard to determine what is an error, what is a warning, etc. It would be useful to have some colored output, at least for info/warning/error.

**Comment by esnible** [comment]
_istioctl_ has not done color before.  We could add it.
- The popular libraries are http://godoc.org/github.com/fatih/color (3.1k stars), and https://github.com/logrusorgru/aurora (686 stars)
- We already pre-req Uber Zap, which can color a string https://godoc.org/go.uber.org/zap/internal/color
- We could just explicitly add ANSI color ourselves without using a library.  It's trivial and I have written Go code before to do that.

It has been my experience that we should add a `--nocolor` or `--color=false` top-level flag for scripting users on systems like Jenkins which don't support ANSI colors.  The output of some of these systems looks very strange with the ANSI sequences.  The flag would default to something like `$ISTIOCTL_USE_COLOR` or `true` if the env variable was undefined.  (Documenting the color suppression flag and the env variable is the reason I haven't proposed this myself!)

Do you have an implementation opinion?

**Comment by howardjohn** [comment]
Definitely should have a `--color=false`. I've used aurora before and it works well enough, I don't have a strong preference either way though as long as it doesn't pull in a ton of dependencies.

**Comment by esnible** [comment]
If we are doing this long-term for all of _istioctl_ I suggest the approach of https://github.com/spf13/cobra/issues/692#issuecomment-479631238 .  For this implementation I will do something profoundly simple to get feedback about the desirability of color at all.
