### ISSUE TITLE
Support Locality Load Balancer settings override per host

### ISSUE THREAD

**Issue by aattuluri** [istio/istio#17802]
**Describe the feature request**
We have a use case to support where some services run active active (with uneven distribution of traffic) while most others run in a failover mode. Currently, locality load balancing feature is supported at the global mesh config level. There isn't a way to either disable or override there locality load balancing settings per host. Hence, the use case above in't configurable. I see that it was discussed before [here](https://docs.google.com/document/d/16DvMkaLYPam9JWUH_QStO_2gxZPeXIcL067gEbRWNSU/edit) and wasn't pursued. 

**Describe alternatives you've considered**
None, there isn't an alternative

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**
Can this be supported by adding an ability to override locality load balancer settings at the Destination rule. I see that outlier detection on destination rule is already used to control this feature, we could as well extend it to override the global behavior.

CC @jwebb49

**Comment by aattuluri** [comment]
@howardjohn @rshriram

**Comment by rshriram** [comment]
and @hzxuzhonghu

**Comment by rshriram** [comment]
how about adding in the Sidecar? like the way we have outboundtraffic policy..

**Comment by rshriram** [comment]
the only problem is that sidecar approach wont work for gateways..

**Comment by rshriram** [comment]
thinking more about it, ignore sidecar idea. What you want is finer grained locality setting per destination service, not per source. We have two api-sh options to support this configuration: destination rules which has lb settings, or service entries where you casn specify these service properties [we would have to support merging service entry data with k8s service data].

**Comment by howardjohn** [comment]
I think destination rule is the best choice here. We already have lb
settings, and we are already reading the DR (for outlierDetection) in the
locality lb code

**Comment by hzxuzhonghu** [comment]
Make it in DR is feasible, previously i have tried.

**Comment by aattuluri** [comment]
Looks like destination rule would be a good idea.
@hzxuzhonghu Can you please share you change list for what you have tried?

**Comment by aattuluri** [comment]
@hzxuzhonghu Looks like this was the change list where you also reverted destination rule level changes:
https://github.com/istio/api/commit/6286ff0e63603c77cf7ec30510c39e5cebae65b2#diff-e7424aa96af1917e2a00aea6798dc071

Why wasn't the same object (`LocalityLoadBalancerSetting`) used in DestinationRule? I see there is a different object `LocalityWeightSetting` under `LoadBalancerSettings`

**Comment by hzxuzhonghu** [comment]
I do not remember, but personally i think we can share the same structure

**Comment by aattuluri** [comment]
What would be the next step?, shall I send a PR for the API changes?

**Comment by aattuluri** [comment]
@rshriram @howardjohn ?

**Comment by hzxuzhonghu** [comment]
1.4 is checked out, so i think 1.5 would be ok
