### ISSUE TITLE
istioctl analyze excessive warning for unlabeled namespace

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#17806]
Step 1: create an namespace without label with `istio-injection`

Get warning

```
Warn [IST0102](Namespace/operator) The namespace is not enabled for Istio injection. Run 'kubectl label namespace operator istio-injection=enabled' to enable it, or 'kubectl label namespace operator istio-injection=disabled' to explicitly mark it as not needing injection
```

This is a bit excessive. I don't want to inject pods in this namespace, which is a pretty common usage in Istio (that is why we have the label). 

Now this warning spams me every time when its not relevant to me.

Maybe this is more of a metapoint that I want to suppress warnings in the future or something

**Comment by esnible** [comment]
@sushicw @ozevren Should Istio
- lower this to "info" or "fyi" level, then not show that level unless requested?
- Remove this message
- have the user tell us his intentions about namespaces using flags?

**Comment by sushicw** [comment]
I'm new enough to the project that I'm not 100% sure what will be most helpful to users, but my instinct is that this is probably something we want to show by default but be able to opt out of. It certainly seems like a great candidate for annotation-based suppression. 

Controlling the level of output is also something we need. Created https://github.com/istio/istio/issues/17861 to track that specifically. 

This also may cross over with https://github.com/istio/istio/issues/17595. I think the experience gets a lot better as soon as we are only analyzing one namespace.

**Comment by sushicw** [comment]
https://github.com/istio/istio/pull/17869 should greatly mitigate this: a user won't see this validation message for the `operator` namespace unless they explicitly direct `istioctl` to analyze that namespace. 

@howardjohn are we OK to close this? 

Between making `istioctl analyze` namespace-specific and our already tracked future work to control output levels, analyzers run, and suppress specific warning messages, I think we've got both the immediate cause fixed and plans to avoid similar problems long-term.

**Comment by howardjohn** [comment]
Thanks1
