### ISSUE TITLE
istioctl analyze output not sorted

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#17809]
It seems like the output order is completely random. It doesn't seem like its writing warnings as its finding them, so I see no reason why we can't do some sort of sorting.

A reasonable order may be:
* Error level
* Error Code #
* Namespace/pod or something? I have a bunch of namespaces svc{0..100} and they are in completely random order which is a bit inconvenient

**Comment by sushicw** [comment]
The order right now is determined by the order the analyzers run in, and then whatever happens inside analyzers to determine output. (Which, in some cases, involves map / set structures with no particular order defined).

Adding a sort makes sense and seems straightforward.
