### ISSUE TITLE
istioctl analyze does not respect proxyImage overrides

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#17805]
Step 1: add annotation `sidecar.istio.io/proxyImage: istio/proxyv2:1.3.3`
Step 2: run `istioctl analyze`

Warning:
```
Warn [IST0105](Pod/default/shell-64d5954ccc-nl5nx) The version of the Istio proxy running on the pod does not match the version used by the istio injector (pod version: 1.3.3; injector version: 1.4-alpha.04e758e76bbf4cb00614709672aa5f51614ded4a). This often happens after upgrading the Istio control-plane and can be fixed by redeploying the pod.
```

**Comment by selmanj** [comment]
Verified. I didn't know you could override sidecar injection with an annotation.

As an aside, is this desirable? If my mesh administrator has enabled namespace injection on my namespace (and presumably I don't have access to edit the namespace), it seems I could avoid sidecar injection on my deployment by adding this annotation with a bogus image.

**Comment by howardjohn** [comment]
> As an aside, is this desirable? If my mesh administrator has enabled sidecar injection on my namespace (and presumably I don't have access to edit the namespace), it seems I could avoid sidecar injection on my deployment by adding this annotation with a bogus image.

That's a good point. I don't think Istio has any effort to strictly guarantee a pod is injected and has iptables set up. There are plenty of other annotations that allow bypassing Envoy for example. If the administrator really wanted to I think they could block these annotations?
