### ISSUE TITLE
e2e tests for pilot fail

### ISSUE THREAD

**Issue by sdake** [istio/istio#1781]
In a recent development guide PR, this error popped up:

https://storage.googleapis.com/istio-prow/pull/istio_istio/1746/istio-pilot-e2e/80/build-log.txt

As no code was modified, having a deeper look:
```W1117 04:30:30.992] =================== Failed infrastructure tests! =====================
W1117 04:30:30.992] 2 errors occurred:
W1117 04:30:30.992] 
W1117 04:30:30.992] * Post https://130.211.142.250/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions: dial tcp 130.211.142.250:443: getsockopt: connection refused
W1117 04:30:30.993] * Post https://130.211.142.250/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions: dial tcp 130.211.142.250:443: getsockopt: connection refused
W1117 04:30:30.993] 
W1117 04:30:30.998] ERROR: Non-zero return code '1' from command: Process exited with status 1.
W1117 04:30:31.003] make: *** [e2etest] Error 6
```

The implication of the ECONNREFUSED is that either kube-apiserver is not operational or there may be a synchronization point missing before infrastructure is deployed.

**Comment by sdake** [comment]
This looks suspicious:
```W1117 04:30:15.213] Created [https://container.googleapis.com/v1/projects/istio-testing/zones/us-central1-f/clusters/e2e-pilot-008f26b5].
W1117 04:30:15.219] kubeconfig entry generated for e2e-pilot-008f26b5.
I1117 04:30:15.320] NAME                ZONE           MASTER_VERSION                    MASTER_IP        MACHINE_TYPE   NODE_VERSION  NUM_NODES  STATUS
I1117 04:30:15.320] e2e-pilot-008f26b5  us-central1-f  1.7.8-gke.0 ALPHA (29 days left)  130.211.142.250  n1-standard-4  1.7.8-gke.0   1          RUNNING
W1117 04:30:15.420] + CLUSTER_CREATED=true
W1117 04:30:15.420] + for i in '{1..10}'
W1117 04:30:15.420] ++ kubectl get namespace
W1117 04:30:17.616] + status='NAME          STATUS    AGE
W1117 04:30:17.616] default       Active    1m
W1117 04:30:17.616] kube-public   Active    59s
W1117 04:30:17.616] kube-system   Active    1m'
W1117 04:30:17.616] + [[ NAME          STATUS    AGE
W1117 04:30:17.617] default       Active    1m
W1117 04:30:17.617] kube-public   Active    59s
W1117 04:30:17.617] kube-system   Active    1m == \U\n\r\e\a\c\h\a\b\l\e ]]
W1117 04:30:17.617] + break
```

**Comment by sdake** [comment]
this sync point looks ok although a stronger sync point would be to verify the various pods are operational on the existing 1 node:
https://github.com/istio/istio/blob/master/prow/cluster_lib.sh#L60-L68

Even though the namespace is present, that may not be enough to guarantee that kubernetes itself is ready to operate.

**Comment by sdake** [comment]
timestamp of infrastructure reported as operational in the test cases:
```04:30:17.617
```

timestamp of failed test case:
```04:30:30.992
```

Just speculating, but the 7 seconds may not be sufficient to handle CRD rest operations.

**Comment by sbezverk** [comment]
@sdake if you can list available namespaces, it is pretty much a guarantee that api server is up and running, but with the error you have pasted, you would not get anything back. If you can get logs from kube-apiserver container, it would be easier to figure out what happened.

**Comment by sdake** [comment]
I haven't seen this in the gate for a long time.  As this bug has been open for 3 months, I'm going to close.  If someone in the community comes across it again, please reopen.
