### ISSUE TITLE
Istio Ingress every X response is slow

### ISSUE THREAD

**Issue by Freyert** [istio/istio#17810]
**Bug description**
Every X call we make through our ingress to our health check endpoints takes around 4 seconds when it should only take 100 ms.

I'm just starting my investigation, but wanted to open a ticket to see if anyone had any suggestions on where to look?

Will try to fill out more details as I figure it out.

**Affected product area (please put an X in all that apply)**

[X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[X] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.2 and 1.3 Istio (will get more details)

**How was Istio installed?**
Helm chart

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by cober** [comment]
We have observed the very same issue on 1.3.0, since it was happening on production, we had no time to debug it and needed to manually restart pods. All istio-ingressgateway (hpa kicked in - max. 5) instances were using 1 CPU. After restart, everything was back in normal order.

Latency:

![l1](https://user-images.githubusercontent.com/159293/66703483-68355d00-ed13-11e9-9dd9-0ee601e66c26.png)

**Comment by Freyert** [comment]
Thanks @cober! Good to know I have a friend out there. We'll keep you posted as its running in our staging environment.

Personally, I'm not sure where the best place to start looking is. Are there Envoy/Istio specific metrics I can look into here? Some prime suspects?

**Comment by Freyert** [comment]
Well, it isn't happening for us anymore this morning. :/

**Comment by Freyert** [comment]
Potentially Related Issues:

1. Changing Gateways and or Virtual Services causes slow down: https://github.com/istio/istio/issues/14283
   + Would be good to see if it is one or the other.

**Comment by Freyert** [comment]
@cober did you all have CPU limits enabled?

**Comment by cober** [comment]
@Freyert Sorry for the late response.

We are using default limits set by Istio, however so far we have had no issues.

**Comment by arunbatar** [comment]
I am also having this issue as well with just plain Envoy installed on Digital Ocean Kubernetes cluster.

**Comment by arunbatar** [comment]
My issue was solved by naming the service port correctly according to:
https://istio.io/docs/ops/configuration/traffic-management/protocol-selection/

**Comment by arunbatar** [comment]
For someone configuring Envoy directly, this is the related option if upstream is using HTTP2:
https://www.envoyproxy.io/docs/envoy/v1.12.2/api-v2/api/v2/cds.proto#envoy-api-field-cluster-http2-protocol-options

**Comment by Freyert** [comment]
@arunbatar were there specific metrics that improved when you made the changes?

**Comment by arunbatar** [comment]
> @arunbatar were there specific metrics that improved when you made the changes?

Sorry, no metrics are available. This was a test setup.
