### ISSUE TITLE
Istiod: refactor component startup

### ISSUE THREAD

**Issue by costinm** [istio/istio#17813]
**Describe the feature request**

Right now Galley, Pilot, Injector, NodeAgent  are started from a main() that calls a 
function in the pkg/ which creates gprc server, listens, in some cases handles MTLS,
adds monitoring and ctrlz ports, etc.

While this can be hacked to work for istiod, ideally for each component we would have a pair
of separate functions:

 Init(grpcServer, httpMux, debugMux) - where the component will register its services and 
handlers, without creating its own grpc server/listeners, and do any initialization is needed.

 Start() - start serving.

Istiod will create a single gRPC server, as well as http and debug (ctrlz plus other debug endpoints), and init each component.

Galley and Pilot have some flexibility - the autoinjector is the worse so it would be first priority.

Additional startup options - like patching the webhooks for galley/injector - should not be part
 of the new Init method, but exposed as Public methods that may be called as needed. 
The startup will take care of creating certs if needed and all ordering of components ( so Pilot
Init is called after galley Init and Start are done, etc),

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by costinm** [comment]
@howardjohn

**Comment by nmittler** [comment]
@costinm before we start creating tasks, can we have a kick-off for istiod and put together a rough roadmap and prioritize work? This is a big change and I think we need to take a step back and get on the same page.

**Comment by kyessenov** [comment]
It this slated for 1.4? There's only 3 days left till the freeze.

**Comment by howardjohn** [comment]
> Is this slated for 1.4? There's only 3 days left till the freeze.

1.5 at the earliest
