### ISSUE TITLE
Integration test TestStatsFilter failed

### ISSUE THREAD

**Issue by yxue** [istio/istio#17811]
Failed to update istio/proxy. integ-telemetry-k8s-tests_istio keeps failing. Similar tests in istio/proxy passed. 

https://github.com/istio/istio/pull/17800

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by howardjohn** [comment]
FYI I marked this as a release blocker until we can verify that this is due to a bad test and not a bad code.

This can be resolved by
* Make the test pass
* Confirm this impacts mixer v2 only (alpha only so won't block release)
* Confirm this does not impact users

**Comment by bianpengyuan** [comment]
This is definitely a bug that affects mixer v2. I am debugging it now.

**Comment by howardjohn** [comment]
Is this only mixerv2 though? If so we can bump this down as we wouldn't
block the release for a mixerv2 issue (assuming its still alpha in 1.4,
right?)

**Comment by mandarjog** [comment]
@bianpengyuan lets update the test and doc to use separate vm_id per direction.
I think that will solve this problem.
