### ISSUE TITLE
`istioctl dashboard zipkin` causes an error

### ISSUE THREAD

**Issue by oke-py** [istio/istio#17822]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
`istioctl dashboard zipkin` causes an error.
```
istioctl dashboard zipkin
Error: no Zipkin pods found
```

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Expected behavior**
```
$ kubectl get svc zipkin -o jsonpath="{.spec.selector}"
map[app:jaeger]

$ kubectl get pods -l app=jaeger -o jsonpath="{.items[0].metadata.name}"
istio-tracing-669fd4b9f8-xc2vt
```
port-forward istio-tracing-669fd4b9f8-xc2vt localport:9411

**Steps to reproduce the bug**
1. install istio
2. run `istioctl dashboard zipkin`

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```
istioctl version --remote
client version: unknown
citadel version: 1.3.2
egressgateway version: 1.3.2
galley version: 1.3.2
ingressgateway version: 1.3.2
pilot version: 1.3.2
policy version: 1.3.2
sidecar-injector version: 1.3.2
telemetry version: 1.3.2

kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T23:49:20Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-gke.13", GitCommit:"acdb9a03a6dc0f7f62d7acdda75c9a9faca50fee", GitTreeState:"clean", BuildDate:"2019-09-20T23:13:58Z", GoVersion:"go1.12.9b4", Compiler:"gc", Platform:"linux/amd64"}
```
**How was Istio installed?**
https://istio.io/docs/setup/install/kubernetes/

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

[istio-dump.tar.gz](https://github.com/istio/istio/files/3720032/istio-dump.tar.gz)

**Comment by kebe7jun** [comment]
zipkin should in `istio-system` namespace, it seems that yours are in default.

**Comment by oke-py** [comment]
I used kubens and I was in istio-system namespace.
Avaialble commands other than zipkin worked fine.
```
$ istioctl dashboard -h
...
Available Commands:
  controlz    Open ControlZ web UI
  envoy       Open Envoy admin web UI
  grafana     Open Grafana web UI
  jaeger      Open Jaeger web UI
  kiali       Open Kiali web UI
  prometheus  Open Prometheus web UI
  zipkin      Open Zipkin web UI
...
```

**Comment by kebe7jun** [comment]
https://github.com/istio/istio/blob/master/istioctl/cmd/dashboard.go#L226

The label of zipkin should be `app=zipkin`, not `app=jaeger`

**Comment by oke-py** [comment]
Oh, thanks. There is no pod whose label is `app=zipkin`.
```
$ kubectl get pods -l app=zipkin
No resources found in istio-system namespace.
```

**Comment by oke-py** [comment]
I wonder the installation step doesn't create zipkin pod.
However, this is another issue. I close this issue.
