### ISSUE TITLE
Istio end user authentication returning 401 UnAuthorized with  correct jwt

### ISSUE THREAD

**Issue by mobamb** [istio/istio#17829]
I am getting 401 errors after applying end user authentication for my backend api.

 fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLQF7KE6GPFE", Request id "0HLQF7KE6GPFE:00000002": An unhandled exception was thrown by the application.
System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(Task`1 getTask) 

Here is the policy config.
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: demopolicy
spec:
  targets:
  - name: api2
    ports:
    - number: 80
  origins:
  - jwt:
      issuer: "https://xx.232.244.yy"
      jwksUri: "https://xx.232.244.yy/.well-known/openid-configuration/jwks"
  principalBinding: USE_ORIGIN

![image](https://user-images.githubusercontent.com/56087738/66706654-3b208480-ecea-11e9-9da5-cf67f545d165.png)

![image](https://user-images.githubusercontent.com/56087738/66706651-2b08a500-ecea-11e9-867c-8d86220abc54.png)

![image](https://user-images.githubusercontent.com/56087738/66706642-1a582f00-ecea-11e9-8773-f9d4734b23e0.png)

What am i doing wrong? Any help is much appreciated.

**Comment by incfly** [comment]
can't help much here... we don't have enough reproducible steps to root cause the problem. discuss.istio.io/slack might be a better place.
