### ISSUE TITLE
Install Istio on namespace scope

### ISSUE THREAD

**Issue by alirajabi** [istio/istio#17839]
We are using a K8S cluster but we don't have cluster level permissions, So we can only create `Role` and `ServiceAccount` on our namespaces and we need install Istio only in our namespaces.

Operation team will accept to apply Istio CRD's on cluster for us, but we can't request for cluster admin permissions to install Istio.

We think if we change all `ClusterRole` and `ClusterRoleBinding` to `Role` and `RoleBinding` on Istio helm charts It should be possible. 

We will glad to help us, Do you have any advice?

**Affected product area (please put an X in all that apply)**

[X] Configuration Infrastructure
[X] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by howardjohn** [comment]
I think this is something that would be really useful. My understanding is @knrc has done some work in this area and may be possible to get this into Istio soon. Is that right Kevin?

**Comment by knrc** [comment]
@howardjohn That's partly correct, this forms part of the work we did for multi-tenancy.  There are still elevated privileges required however we moved those to the operator so the control plane itself can be installed by a normal user (via our operator) and an admin only has to install the operator.

I've uploaded [the presentation from last week's Environment WG](https://docs.google.com/presentation/d/1ViQdZM2_n73tvSD5MRWzX4mg2CPBf-UV4L-4oderMwM/edit#slide=id.g5a662668d9_0_5)

**Comment by mostafah** [comment]
@knrc Thanks for the response. The presentation gives an “access denied” error to me. Is it shared publicly?

**Comment by knrc** [comment]
@mostafah It should be accessible to anyone who is part of the Istio community, can you see any other community docs in the shared drive?

**Comment by mostafah** [comment]
I wasn’t aware of that. I just requested Google Drive access through the Google Group and now I can access the file. Thanks.
