### ISSUE TITLE
istioctl describe mtls status is confusing

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#17833]
```
$ ik x describe pod `kp shell`
Pod: shell-64d5954ccc-nl5nx
   Pod Ports: 15090 (istio-proxy)
Suggestion: add 'version' label to pod for Istio telemetry.
--------------------
Service: shell
   Port: http 9087/HTTP
Pilot reports that pod is PERMISSIVE (enforces PERMISSIVE) and clients speak -
Error: no ingress gateway pods
```

The line `Pilot reports that pod is PERMISSIVE (enforces PERMISSIVE) and clients speak -` is confusing to me.

* What does `clients speak -` mean?
* What does `pod is PERMISSIVE (enforces PERMISSIVE) ` mean
* I don't care that Pilot reports this

**Comment by esnible** [comment]
`-` in unexpected.  It comes from https://github.com/istio/istio/commit/f7d2d167c652dc660d1798be2f4429c1820281cd which introduces auto mTLS and means `configNameNotApplicable` which I think means auto MTLS.  I will change `describe`.

`PERMISSIVE (enforces PERMISSIVE)` is also the result of a change brought on by auto MTLS.  I suspect the output of <pilot>/debug/authenticationz?proxyID= has changed.  I couldn't find a Pilot test for the exact output.  Istio's unit tests used canned Pilot output and would not have picked up the change.

I will lose the `Pilot reports`.

**Comment by esnible** [comment]
Similar changes are underway for `istioctl tls-check`: https://github.com/istio/istio/pull/17964

**Comment by esnible** [comment]
@rvennam points out that this message is also confusing:

```
WARNING Pilot predicts TLS Conflict on productpage-v1-7868c48878-b7rrg port 9080 (pod enforces HTTP, clients speak mTLS)
```

**Comment by rvennam** [comment]
pod enforces HTTP -> It is expecting, not enforcing right? enforcing implies a Policy

**Comment by esnible** [comment]
Related problem.  @rvennam reports that when there are no AuthenticationPolicy and no MeshPolicy the output is 
```
Check DestinationRule default/istio-system and AuthenticationPolicy -
```

If there is no policy the tool should say that, not `AuthenticationPolicy -`
