### ISSUE TITLE
No such object: istio-release/releases/1.3.2/charts/ in storage.googleapis.com

### ISSUE THREAD

**Issue by dumindu** [istio/istio#17846]
**Bug description**
I am in the very beginning and I followed https://istio.io/docs/setup/install/helm/

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[x] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Should get 23 while running `kubectl get crds | grep 'istio.io' | wc -l` after `helm template install/kubernetes/helm/istio-init --name istio-init --namespace istio-system | kubectl apply -f -`

**Steps to reproduce the bug**
```
minikube start

kubectl create namespace istio-system
helm repo add istio.io https://storage.googleapis.com/istio-release/releases/1.3.2/charts/
helm template install/kubernetes/helm/istio-init --name istio-init --namespace istio-system | kubectl apply -f -
kubectl get crds | grep 'istio.io' | wc -l
```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.3.2

**How was Istio installed?**
Download binary and moved to `/usr/local/bin/`
```
curl -L https://git.io/getLatestIstio | ISTIO_VERSION=1.3.2 sh -
chmod +x istio-1.3.2/bin/istioctl
sudo mv -f istio-1.3.2/bin/istioctl /usr/local/bin/istioctl
```

**Environment where bug was observed (cloud vendor, OS, etc)**
on Minikube/ Fedora

**Comment by howardjohn** [comment]
seems to be there? https://gcsweb.istio.io/gcs/istio-release/releases/1.3.2/charts/

**Comment by dumindu** [comment]
My mistake! I have used helm 3 beta. Shifted to v2 and run
 
```
curl -L https://git.io/getLatestIstio | ISTIO_VERSION=1.3.2 sh -
chmod +x istio-1.3.2/bin/istioctl
sudo mv -f istio-1.3.2/bin/istioctl /usr/local/bin/istioctl

kubectl create namespace istio-system
helm template istio-1.3.2/install/kubernetes/helm/istio-init --name istio-init --namespace istio-system | kubectl apply -f -
```

It worked!
