### ISSUE TITLE
`istioctl version` does not show build info it istioctl installed via HomeBrew

### ISSUE THREAD

**Issue by yacut** [istio/istio#17849]
**Bug description**
`istioctl version --remote` is broken if the istio is installed via [operator](https://istio.io/docs/setup/install/operator/).

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
`istioctl version --remote` gives the client information

**Steps to reproduce the bug**
see installation...

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```sh
✗ istioctl version --remote
client version: unknown
control plane version: release-1.3-20191013-10-16

✗ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T23:49:07Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6", GitCommit:"5047edce664593832e9b889e447ac75ab104f527", GitTreeState:"clean", BuildDate:"2019-08-21T22:32:40Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

```sh
istioctl experimental manifest apply --yes
```

**Environment where bug was observed (cloud vendor, OS, etc)**
```sh
✗ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15
BuildVersion:	19A583
```

**Comment by esnible** [comment]
You are concerned about `client version: unknown`.  I believe `istioctl experimental manifest apply` installs the control plane, but does not replace the command line with a different version.  I expect you would see the same output for `ls -l $(which istioctl)` before and after applying a new version using operator.

**Comment by howardjohn** [comment]
Yes you likely installed istioctl from `go get` or `make istio-install` or something similar rather than the official release binaries which include version info

**Comment by esnible** [comment]
I just verified that `brew upgrade istioctl` created a directory _/usr/local/Cellar/istioctl/1.3.3_ on my Mac and installed a version of _istioctl_ there which reports that client version as `unknown`.

@yacut can you confirm how you installed `istioctl`?  Via homebrew, from source, etc?

I am not familiar with how `brew` figures out that Istio is on 1.3.3 and builds a binary without a version number.  Anyone?

**Comment by howardjohn** [comment]
How does brew build istioctl? We are not doing anything as part of our
official release pipeline, is it maintained by third party?

**Comment by esnible** [comment]
@howardjohn See https://github.com/istio/istio/issues/10484 for background.

The code that does the work is at https://github.com/Homebrew/homebrew-core/blob/master/Formula/istioctl.rb

The maintainer for that bit of code seems to be a bot.

**Comment by yacut** [comment]
@esnible Yes, I installed istioctl via homebrew

```sh
➜  ~ brew info istioctl
istioctl: stable 1.3.3 (bottled)
Istio configuration command-line utility
https://github.com/istio/istio
/usr/local/Cellar/istioctl/1.3.3 (5 files, 80.2MB) *
  Poured from bottle on 2019-10-14 at 07:56:52
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/istioctl.rb
==> Dependencies
Build: go ✔
==> Analytics
install: 1,896 (30 days), 4,325 (90 days), 10,074 (365 days)
install_on_request: 1,897 (30 days), 4,321 (90 days), 10,076 (365 days)
build_error: 0 (30 days)

➜  ~ ls -l $(which istioctl)
lrwxr-xr-x  1 yacut  admin  37 Oct 14 07:56 /usr/local/bin/istioctl -> ../Cellar/istioctl/1.3.3/bin/istioctl

➜  ~ istioctl version --remote
client version: unknown
control plane version: release-1.3-20191013-10-16
```

**Comment by esnible** [comment]
This seems to be another report of the comment https://github.com/istio/istio/issues/10484#issuecomment-450879610 which was closed.

@murarisumit Can you look at what it would take to get the client version built into the binary?

Because we don't built the binary ourselves we probably shouldn't have Homebrew put an official Istio release number into the Version.  Perhaps we can set the env variable `VERSION` to `homebrew` or `homebrew-$GIT_TAG` so that Homebrew users see `client version: homebrew` or `client version: homebrew-1.3.3`.

**Comment by howardjohn** [comment]
`istioctl manifest` is broken for the same reason
