### ISSUE TITLE
Prepare release-1.4 branches

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#17856]
This issue aims to track all steps needed to prepare the release 1.4 branches/builds.

Please add all steps taken here so we can document for future releases

- [x] (Optional) Update go dependencies. This must be done **before branching** so that PRs can be easily backported later. (owner: @ericvn) _See discussion below if this should be a pre or post branch item._
  - [x] istio/istio - https://github.com/istio/istio/pull/17896
  - [x] istio/pkg - https://github.com/istio/pkg/pull/77
  - [x] istio/api - https://github.com/istio/api/pull/1127
  - [x] istio/cni - `go get -u` and `go mod tidy` fail
  - [x] istio/operator - no updates from `go get -u`
  - [x] istio/installer - no updates from `go get -u`
  - [x] istio/client-go - https://github.com/istio/client-go/pull/8
- [ ] Update common-files in _master_. This will prevent larger differences between _master_ and the new release as the common-files are updated after the branching (only change should be branch).
  - [ ] istio/istio
  - [ ] istio/pkg
  - [ ] istio/api
  - [ ] istio/cni
  - [ ] istio/operator
  - [ ] istio/installer
  - [ ] istio/client-go
  - [ ] istio/release-builder
  - [ ] istio/gogo-genproto
- [x] Set up release manager team (owner: @geeknoid) - Make sure the new team has write access to the repositories. 
- [ ] Create a `release-1.4` branch in every Istio repo - run commands `export org=xyz ; export repo=xyz ; (git clone git@github.com:${org}/${repo}.git && cd $repo && git checkout -b release-1.4 && git push --set-upstream origin release-1.4)`.
  - [x] istio/istio
  - [x] istio/pkg
  - [x] istio/api
  - [x] istio/cni
  - [x] istio/proxy  - Do not branch updated for Envoy 1.12 (owner: @PiotrSikora to notify @howardjohn when this is done)
  - [x] istio/envoy - Do not branch updated for Envoy 1.12 (owner: @PiotrSikora to notify @howardjohn when this is done) - branch was done by @PiotrSikora
  - [x] istio/operator
  - [x] istio/installer
  - [x] istio/client-go
  - [x] istio/tools
  - [x] istio/common-files
  - [x] istio/gogo-genproto
  - [ ] istio/release-builder - Do not branch until release date, as every PR will be for 1.4 since this is used to build 1.4.
  - [x] Explicitly skipped: istio-releases/pipeline, istio/tests, istio/istio.io, istio/test-infra
- [x] Set up prow on release branches (owner: @howardjohn)
  - [x] istio/istio https://github.com/istio/test-infra/pull/1940
  - [x] istio/pkg https://github.com/istio/test-infra/pull/1940
  - [x] istio/api https://github.com/istio/test-infra/pull/1940
  - [x] istio/cni  https://github.com/istio/test-infra/pull/1940
  - [x] istio/proxy https://github.com/istio/test-infra/pull/1942
  - [x] istio/envoy - does not use prow
  - [x] istio/operator https://github.com/istio/test-infra/pull/1940
  - [x] istio/installer  https://github.com/istio/test-infra/pull/1940
  - [x] istio/client-go https://github.com/istio/test-infra/pull/1940
  - [x] istio/tools https://github.com/istio/test-infra/pull/1942
  - [x] istio/common-files https://github.com/istio/test-infra/pull/1940
  - [x] istio/release-builder https://github.com/istio/test-infra/pull/1940
  - [x] istio/gogo-genproto https://github.com/istio/test-infra/pull/1940
- [x] Set up branch protection (owner: @howardjohn) https://github.com/istio/test-infra/pull/1936
- [ ] Update all repos that point to master branch of another repo to point to the release branch. `master-latest-daily` -> `1.4-dev` (see https://discuss.istio.io/t/deprecation-notice-daily-builds/3991), `latest` -> `1.4-dev`, `git clone master` to `git clone release-1.4`, etc. Commit a PR into every `release-1.4` branch to modify every `CODEOWNERS` to contain only the release managers for this release. Command: `export org=xyz ; export repo=xyz ; (git clone git@github.com:${org}/${repo}.git && cd $repo && git checkout release-1.4 && git checkout -b release-1.4-codeowners && echo '* @istio/release-managers-1-4' > CODEOWNERS && git add CODEOWNERS && git commit -m 'Set release managers as CODEOWNERS for release-1.4' && git push --set-upstream origin release-1.4-codeowners)`.
  - [x] istio/istio https://github.com/istio/istio/pull/17934
  - [x] istio/pkg https://github.com/istio/pkg/pull/80
  - [x] istio/api https://github.com/istio/api/pull/1132
  - [x] istio/cni https://github.com/istio/cni/pull/202
  - [x] istio/proxy TODO after branch https://github.com/istio/proxy/pull/2512
  - [x] istio/envoy TODO after branch https://github.com/istio/envoy/pull/114
  - [x] istio/operator https://github.com/istio/operator/pull/391
  - [x] istio/installer https://github.com/istio/installer/pull/437
  - [x] istio/client-go https://github.com/istio/client-go/pull/11
  - [x] istio/tools https://github.com/istio/tools/pull/442
  - [x] istio/common-files https://github.com/istio/common-files/pull/108
  - [x] istio/gogo-genproto
  - [x] istio/release-builder https://github.com/istio/release-builder/pull/58
- [x] Update common-files in _new release_. You first have to manually update the _common/Makefile.common.mk_ *update-common* target to point to the _new release_ and then run 'make update-common'. It may be that this step could be combined in the prior step in the 'make update-common' was done before the branch.
  - [x] istio/common-files should have the branch updated above.
  - [x] istio/istio
  - [x] istio/pkg
  - [x] istio/api
  - [x] istio/cni
  - [x] istio/operator
  - [x] istio/installer
  - [x] istio/client-go
  - [x] istio/gogo-genproto
  - [x] istio/proxy
  - [x] istio/release-builder
- [x] Bump master to version 1.5 https://github.com/istio/istio/pull/17938
- [x] Stop publishing `latest` tags https://github.com/istio/istio/pull/17963
- [x] Run the long-running tests on the dev builds
- [x] Send announcement on Discuss/Slack/Twitter
- [x] Publish a beta release

**Comment by rlenglet** [comment]
@howardjohn s/1-3/1-4/

**Comment by ericvn** [comment]
To upgrade to the latest version for all direct and indirect dependencies, using the latest patch releases, of the current module, the following can be run from the module root directory: `go get -u=patch -t ./...`

**Comment by ericvn** [comment]
I did do some initial testing of updating the go modules across the repos listed above with draft PRs:

- **istio** is still failing some tests. I suspect it might not have liked _prometheus_ updates. Continuing to look at that.
- **installer** and **operator** had no new updates
- I can't get **cni** to get through a `go mod tidy` or `go get -u ...`
- **pkg** and **api** are passing
- **tests** is still being done

**Comment by howardjohn** [comment]
Steps we missed
* update common files in master first
* apply branch protection before doing the branch, not after

**Comment by ericvn** [comment]
Also
 - rebuild the base docker image to pick up security patches

**Comment by jwendell** [comment]
>     * rebuild the base docker image to pick up security patches

+1 for doing that even for z releases

**Comment by geeknoid** [comment]
I think we're doing a couple things incorrectly.

- We should not be updating common files before branching.
- We should not be updating go.mod dependencies before branching.

In general, we want to update the tools dependencies in build-tools, update common-files, and update go.mod _in master_ right _after_ the release branch has been created. That is, update all of this stuff at the start of a release cycle, not as the start of a release branch.

**Comment by rlenglet** [comment]
> update go.mod in master right after the release branch has been created

We thought that the incompatible dependencies could make cherry-picks difficult.

**Comment by ericvn** [comment]
One comment as I was looking at some of the module updates that I didn't do because I was concerned, and a pro for doing in `master` after the branches are cut. I noticed that some packages have changed, I think one example was github.com/golang/sync went to golang.org/x/sync. Best time to do that would be just after the branch is cut in _master_ but it will affect cherry picks.

**Comment by ericvn** [comment]
Note: Remember to change release-builder specified branch to `CHANGE_THIS_TO_RELEASE_BRANCH` in master after branching.

**Comment by howardjohn** [comment]
We still need to branch Envoy and Proxy @PiotrSikora @mandarjog can we do this soon?

**Comment by ericvn** [comment]
Retrospective comments:

1) Google CLA bot and non-Googlers on cherry picks
2) Late change to which installer to document which invalidated some testing event testing

**Comment by jwendell** [comment]
3. Multi-repo is a pain. Changes in a chart need to travel through 3 repos to reach final destination, also add the fact that most PR's need to be cherry-picked which gives 6 PR's!

**Comment by howardjohn** [comment]
Closing as all repos are branched

**Comment by ericvn** [comment]
Another thing we may/may not be doing is the preliminary.io uses scripts from the `master` branch while once it's moved to `istio.io` it'll use the release branch. It may be that the release branch script isn't correct and wasn't necessarily tested.
