### ISSUE TITLE
No access logs for dropped HTTPS/TCP traffic

### ISSUE THREAD

**Issue by EPinci** [istio/istio#17850]
**Bug description**
Enabled egress filtering (mode: REGISTRY_ONLY) and access logging (accessLogFile: "/dev/stdout") per https://istio.io/docs/tasks/traffic-management/egress/egress-control/.
I confirmed traffic egress is getting blocked by default on sidecar-injected pods.

I expected traffic all drops to be stdout logged in the istio-proxy sidercar.
What I can actually see is that only HTTP drops are logged (as 502 responses from the proxy).
HTTPS/TCP calls are positively blocked, as expected, but with no logging whatsoever on the sidecar. This makes troubleshooting payload connectivity extremely difficult effectively blocking istio onboarding for us.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Running istio 1.3.2, minimal install profile on AKS kubernetes 1.14.6

**Comment by howardjohn** [comment]
I have tested this on master. I now see `[2020-04-15T00:02:27.874Z] "- - -" 0 UH "-" "-" 0 0 0 - "-" "-" "-" "-" "-" - - 35.170.216.115:443 10.28.1.90:59692 - -`. See https://github.com/istio/istio/issues/21579 and https://github.com/istio/istio/issues/16458 for more info. Sorry this went unnoticed for so many months...
