### ISSUE TITLE
`istioctl version` does not show a single control plane version in Istio 1.3.2

### ISSUE THREAD

**Issue by esnible** [istio/istio#17852]
Using Istio 1.3.2, `istioctl version` shows the control plane information like this:

```
client version: 1.3.2
citadel version: 1.3.2
galley version: 1.3.2
ingressgateway version: 1.3.2
pilot version: 1.3.2
sidecar-injector version: 1.3.2
telemetry version: 1.3.2
```

It is expected that it would show only

```
client version: 1.3.2
control plane version: 1.3.2
```

The internal logic does not combine entries if the Git Tags don't match, even if the versions do.  For Istio 1.3.2, the IngressGateway has GitTag 1.3.2 but the rest have 1.3.1 (see with `istioctl version -o json`)

Istioctl gets these from the control plane binaries.  It does the equivalent of `kubectl exec -n istio-system $(kubectl get pod -n istio-system --selector istio=pilot --output jsonpath='{.items[0].metadata.name}') -- /usr/local/bin/pilot-discovery version` and gets output like ```version.BuildInfo{Version:"1.3.2", GitRevision:"12c4d01552363362b49fce86f83b847b308b9b0d-dirty", User:"root", Host:"dfb2f357-e469-11e9-915d-7edd31f75cb4", GolangVersion:"go1.12.9", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.3.1"}```

The Istio Version and GitTag have usually match.

**Comment by howardjohn** [comment]
GitTag has always been != version

But it sounds like that is not the problem, rather different control plane artifacts have a different gittag
Which is likely the ingressgateway
See https://github.com/istio/istio/issues/13602. The reason ingressgateway is different is because the image was manual built
