### ISSUE TITLE
`istioctl x analyze` should return useful exit codes

### ISSUE THREAD

**Issue by sushicw** [istio/istio#17862]
The istioctl command for analysis should return a nonzero exit code if:

* Any analyzers fail / generate messages
* Any analyzers are skipped because input resources were not available. 

These should be different codes. The latter case will need to work in conjunction with #17443, which allows a subset of analyzers to be specified. (Specifying a subset should not be treated as a skip). 

Discussed in the [design doc](https://docs.google.com/document/d/1KuxDRPPt283jx_cIs2C9sFHjoHvoskJt3IGqhPJVHtM)

**Comment by esnible** [comment]
@sushicw Do you have someone in mind for this work?

**Comment by sushicw** [comment]
Myself by default, but I'm not picking it up immediately and wouldn't mind if someone else beat me to it.

**Comment by sushicw** [comment]
As a refinement: 

* By default, only return nonzero for ERROR and WARN levels. INFO would still return a zero code. 
* Add a CLI arg to let the user customize that behavior? (So if someone wants a nonzero code for INFO or only on ERROR, they can).
