### ISSUE TITLE
Trust domain should be set using ConfigMap

### ISSUE THREAD

**Issue by pitlv2109** [istio/istio#17873]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Trust domain should be set using ConfigMap. Currently, the trust domain in various Istio components like Citadel and Pilot is set using command line arguments. 

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by incfly** [comment]
internal cleanup.
