### ISSUE TITLE
The deletionTimestamp and finalizers fields are always nil in the IstioControlPlane instance

### ISSUE THREAD

**Issue by morvencao** [istio/istio#17883]
The controller can’t get `deletionTimestamp` and `finalizers` from the IstioControlPlane instance, while they do exist, because I can get the instance from api-server with kubectl:
```
root@mcdev1:~/go/src/istio.io/operator# kc get istiocontrolplane example-istiocontrolplane -o yaml
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
metadata:
  creationTimestamp: "2019-10-12T12:45:39Z"
  deletionGracePeriodSeconds: 0
  deletionTimestamp: "2019-10-12T12:46:52Z"
  finalizers:
  - istio-operator
  generation: 2
  name: example-istiocontrolplane
  namespace: default
  resourceVersion: "1218"
  selfLink: /apis/install.istio.io/v1alpha2/namespaces/default/istiocontrolplanes/example-istiocontrolplane
  uid: 85a3dc1e-fa49-47c2-8210-247f1d39e1a3
spec:
  profile: default
status:
  status:
    Citadel:
      status: 2
    Galley:
      status: 2
    IngressGateway:
      status: 2
    Injector:
      status: 2
    Pilot:
      status: 2
    Policy:
      status: 2
    Prometheus:
      status: 2
    Telemetry:
      status: 2
    crds:
      status: 2
```

Generally, after the end-users delete the IstiocontrolPlane CR with kubectl, the `deletionTimeStamp` will be added to the IstiocontrolPlane CR, and the controller will start to handle the `finalizers`.
The current situation is that, the controller can’t get deletionTimeStamp field(it’s always nil in my env) after I delete the IstiocontrolPlane CR with kubectl.

**Comment by morvencao** [comment]
The issue should be relevant to the tags generated by protobuf.
As `jsonpb` and `json` libs are using separate tags in the generated go struct;
while we can’t handle json tag for some fields, eg. `deletionTimestamp` and `finalizers`.

**Comment by sdake** [comment]
> The issue should be relevant to the tags generated by protobuf.
> As `jsonpb` and `json` libs are using separate tags in the generated go struct;
> while we can’t handle json tag for some fields, eg. `deletionTimestamp` and `finalizers`.

@morvencao Why not just eject gogo as I would suspect it is the cause of this incompatibility?  We are going to have to play wackamole all over the code base because of this type of issue.

**Comment by morvencao** [comment]
@sdake If you mean gogo proto lib, yes, I have tried that besides the official golang proto lib. We may need add customized marshal/unmarshal func, that's a lot work.

**Comment by morvencao** [comment]
Reopen this ticket.

**Comment by ostromart** [comment]
Let's move this work to more general cleanup: https://github.com/istio/istio/issues/17960
We need adequate time to solve this correctly, so targeting 1.5.
