### ISSUE TITLE
EnvoyMetricsService needs backports to istio/installer

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#17889]
There have been a variety of changes to the istio/istio installer that have not been backported to istio/installer. This likely means the operator does not support the metrics service right now.

cc @ramaraochavali

**Comment by ramaraochavali** [comment]
@howardjohn Thanks. Will take care of this.

**Comment by joeyb** [comment]
This should be resolved by https://github.com/istio/installer/pull/485

**Comment by howardjohn** [comment]
Thanks!
