### ISSUE TITLE
istioctl kube-inject not working

### ISSUE THREAD

**Issue by kahootali** [istio/istio#1788]
I am using Minikube 0.23, Kubernetes 1.8.0 and Istio 0.2.7 on Windows 10
The issue is whenever I call 
`kubectl apply -f (istioctl kube-inject -f .\svc.yaml)`
I get 
> Error: kubernetes configuration file "/.kube/config" does not exist

But my kubectl context is set as when I call 
`kubectl config view`,
 I get the desired result and even the file exists in C://,,,/.kube/config

**Comment by ayj** [comment]
istioctl uses the `HOME` environment variable to locate the default kubeconfig. This doesn't seem to be set on windows (see https://github.com/eirslett/kubectl-windows/issues/2). Maybe we need to use `USEPROFILE` [here](https://github.com/istio/istio/blob/95e7a1f3d1d5383f0353dc60977dcc2ddc6daaf9/pilot/cmd/istioctl/main.go#L489) instead on windows?

Setting the path explicitly should work, i.e. `istioctl --kubeconfig <path/to/your/kubeconfig> kube-inject -f .\svc.yaml`.

**Comment by pipejakob** [comment]
For compatibility with how kubectl discovers the default location of this file, you can see the `HomeDir()` utility in `kubernetes/client-go`: [homedir.go](https://github.com/kubernetes/client-go/blob/fcdf37233b57445e4a6a4038ec580e9aaac931de/util/homedir/homedir.go#L26)

**Comment by bacongobbler** [comment]
Related: the code required to get this working for helm. https://github.com/kubernetes/helm/pull/3024
