### ISSUE TITLE
Running Envoy proxy through CRI

### ISSUE THREAD

**Issue by truongnh1992** [istio/istio#17880]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
When upgrading Istio sidecar:
In order to change the sidecar container, the pod needs to be restarted, so the application container will be restarted as well => it will cause downtime for that specific pod.

In order to change the sidecar container without restaring the pod ⇒ We have to run the sidecar out of pod (community has idea that running Envoy through CRI. Unfortunately, there isn’t any formal proposal yet) and Envoy supports hot restart meaning you start a new Envoy binary (could be different version) and traffic is shifted to the new Envoy without traffic loss [1]

[1] https://blog.envoyproxy.io/envoy-hot-restart-1d16b14555b5

**Comment by howardjohn** [comment]
Expanded the scope of https://github.com/istio/istio/issues/11366 to include CRI or CNI (implementation detail), so I think this is a duplicate. There is work being done there already
