### ISSUE TITLE
Istio's CNI repo cross repo gating may cache the repo locally

### ISSUE THREAD

**Issue by sdake** [istio/istio#17906]
See https://github.com/istio/istio/pull/17864/files#r335231601 for weaknesses around Istio's CNI repo gating when run in BUILD_WITH_CONTAINER.  The source tree is cloned if it doesn't exist in a docker volume and never recloned.  A `docker volume prune` seems to fix the problem.

**Comment by howardjohn** [comment]
is it not just mounting the local istio/istio? or is it cloning a separate istio repo than the local files, and that is not updated?

**Comment by howardjohn** [comment]
it was cloing steves personal repo
