### ISSUE TITLE
istioctl analyze: check if hub/image:tag combination exists on gcr.io/docker.io hub

### ISSUE THREAD

**Issue by elfinhe** [istio/istio#17901]
**Describe the feature request**
`istioctl analyze` checks if hub/image:tag combination exists on gcr.io/docker.io hub.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Additional context**
@sushicw please help find the right assignee, thanks!

**Comment by howardjohn** [comment]
I don't think this is a good idea. it means istioctl analyze has a dependency on arbitrary docker registries, which is not always possible. It's common that you could have a registry accessible from the cluster but not from a developer machine running the cli, or CI.

If you do happen to run an invalid image you will immediately see it from kubectl - no need for a fancy istioctl command.

Is there some context I am missing here?

**Comment by elfinhe** [comment]
Sure, I agree this should be in k8s. I opened this because I encountered an issue when upgrading Istio but with an incorrect image tag. That action took down the old istio pods but new pods can never enter ready state.

**Comment by howardjohn** [comment]
@elfinhe I don't think it should take down the old pods, normally kubernetes waits for the new ones to be marked "Ready" before removing the old ones? Maybe something is wrong with some configuration
