### ISSUE TITLE
istio.io doc test TestMTLSMigration has never passed

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#17909]
Fails with `script_step.go:92: script verification failed: expected return code to be 200; actual:` every time.

**Comment by brian-avery** [comment]
Interesting. Just seeing this issue now, but it always passed locally for me. Let me see if I can reproduce.

**Comment by howardjohn** [comment]
Some failures:

https://prow.k8s.io/view/gcs/istio-prow/logs/integ-k8s-113_istio_postsubmit/333
https://prow.k8s.io/view/gcs/istio-prow/logs/integ-k8s-113_istio_postsubmit/334
https://prow.k8s.io/view/gcs/istio-prow/logs/integ-k8s-113_istio_postsubmit/335

**Comment by brian-avery** [comment]
I'm seeing a different failure locally. If I run the mTLS test locally by itself then I don't see any failures. If I run the entire suite, I see failures due to the fact that it can't find the sleep pod. Looking into it.
