### ISSUE TITLE
Feature - Add support for envoy shadow requests

### ISSUE THREAD

**Issue by nmnellis** [istio/istio#1791]
Envoy has the ability to "shadow" requests to another service. It would be great to see this as another routing rule to send requests to another service or version of the same service.

https://www.envoyproxy.io/docs/envoy/latest/configuration/http_conn_man/route_config/route#shadow

**Comment by nmnellis** [comment]
this is already in master! Closing.

**Comment by ldemailly** [comment]
is it ? curious which PR added it and how to configure it

**Comment by nmnellis** [comment]
@ldemailly There is no documentation yet for it but here is an example rule. https://github.com/istio/istio/blob/a97ee8df3a1bc4a163ae56aa8b9d99951c3352bb/pilot/test/integration/testdata/rule-default-route-mirrored.yaml.tmpl
