### ISSUE TITLE
istio 1.2.7: inbound listener is removed during pod shutdown sequence

### ISSUE THREAD

**Issue by gotwarlost** [istio/istio#17913]
**Bug description**

We have situations where pods need to perform a cleanup sequence during shutdown that requires all of the following to be true:

* istio-proxy container up and running
* pod needs to make outbound calls
* pod needs to receive inbound calls (using the pod IP, not the service IP)

When the pod receives a SIGTERM it starts the cleanup sequence. This can last up to 4 minutes (the `terminationGracePeriodSeconds` is set to `240`). 

The istio-proxy container is kept up and running since we inject the following into its definition (via a customized sidecar template)

```
lifecycle:
  preStop:
    exec:
      command:
        - /bin/sh
        - "-c"
        - "while [ $(netstat -plnt | grep ^tcp | grep -v -e envoy -e pilot-agent | wc -l) -ne 0 ]; do sleep 1; done"
``` 

In istio 1.1.x, all of this used to work seamlessly. This behavior has changed in istio 1.2.x. What seems to happen is that within a second or two of the SIGTERM, the inbound listener is removed and all inbound calls fail with `503 NR`. We also see the health checks fail with the standard `envoy missing listener for inbound application port: nnnnn` message. 

(The failing health checks are not the root problem. The problem is that inbound requests are rejected for want of a listener).

**Affected product area (please put an X in all that apply)**

[X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

The inbound listener is not removed and the pod is able to accept inbound traffic until the main container stops.

**Steps to reproduce the bug**

* Create a `chaos` namespace
* Apply this file: https://github.com/gotwarlost/chaos-adapter/blob/master/k8s/simple-server.yaml
* In separate windows, `kubectl logs -f` the `server` and `istio-proxy` containers of the pod created
* Run the following command in a third window to generate some traffic:

```
$ kubectl exec -ti -c server chaos-server-ID  -- bash
# while true; do curl -s $POD_IP:8080; sleep 3; done
hello
hello
hello...
```

* Delete the pod
* At this point, the main container should emit a message saying it's waiting for 2 minutes to shutdown.
* The istio-proxy container should start complaining about missing inbound listeners. If it doesn't, run `kubectl delete svc rando-server` (an unrelated operation) to trigger this behavior.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

1.2.7

**How was Istio installed?**

Helm charts

**Environment where bug was observed (cloud vendor, OS, etc)**

AWS

**Comment by gotwarlost** [comment]
Possibly related commit: https://github.com/istio/istio/pull/13909/files

**Comment by hzxuzhonghu** [comment]
replied here https://github.com/istio/istio/pull/17955#issuecomment-542967968

**Comment by hzxuzhonghu** [comment]
can you elaborate on why you need to receive call during shutdown, is there a workaround if you want to notify a graceful shutdown? Maybe by handling SIGTERM

**Comment by fpesce** [comment]
@hzxuzhonghu thanks for bringing back the discussion of PR #17955 in the original issue it helps a lot for the comprehension of the PR.

If I understand correctly the problem here, there is no way to indicate in pilot a `networkTerminationGracePeriod` (that ideally should have a value somewhere between 0 seconds and  `terminationGracePeriodSeconds` seconds ).
Two points of view here:
1. @hzxuzhonghu 's point is to shutdown listener as soon as possible to help the service to terminate without taking any more network workload.
2. @gotwarlost  's point is that a service might require additional network activity to gracefully terminate in the time that it has to live for.

Maybe the correct fix would be to create that additional networkTerminationGracePeriod additional value?

**Comment by gotwarlost** [comment]
Now I realize that we are talking about a "pod mesh" use case rather than a "service mesh" use-case. The issue is that we don't want 2 vastly different solutions one using istio and another using something else for the 2 cases. This is why we shoe-horned this to work under istio. It used to work perfectly in `1.1.x` but doesn't in the `1.2.x` (or later) releases.

**Comment by gotwarlost** [comment]
Also, there is a mention of memory leaks in the original fix that I don't quite understand. Perhaps you could explain how this happens?

https://github.com/istio/istio/pull/13909#issuecomment-491648562

**Comment by rshriram** [comment]
We introduced this change to reduce the 503s when scale-in happens. 
#17955 will not work reliably due to time synchronization issues [time on pilot node may not match with the time when the grace period actually expires on the affected pod's node].

Are you okay with the inbound listener to not be removed at all, when a deletion timestamp is set? i.e. we would go back to the old behavior of removing the pod only when it is completely removed from the system. If you folks are okay with this behavior, then we could introduce an annotation like `traffic.istio.io/skip-inbound-drain-on-shutdown: true` . You can add this annotation to the limited set of pods that want this behavior. We can then bring back the old behavior in pilot guarded by the presence of this annotation.

WDYT @hzxuzhonghu ?

**Comment by gotwarlost** [comment]
@rshriram  re: the change in https://github.com/istio/istio/pull/13909/files

```
We introduced this change to reduce the 503s when scale-in happens
```

Would it be possible to walk me through why this change reduces 503s when scale-in happens?
I don't see the connection.

From whatever comments I see in that PR and references to others, this change is protecting against pod delete and update events racing against other pod update events of newly created pods that may have been assigned the same IP address immediately after the old pod is gone. 

I'm unfamiliar with the pilot code base so I possibly don't see all the connections but what  I _think_ the change is doing is to forget pods at the first available opportunity so that events for 2 pods don't clobber the information for the same IP address.

**Comment by gotwarlost** [comment]
Also, for the record, I'm against any change that adds `traffic.istio.io/skip-inbound-drain-on-shutdown: true` to invoke logic that at first glance doesn't seem related directly to the drain problem except as a possible side-effect.

**Comment by hzxuzhonghu** [comment]
> When the workload gets a SIGTERM it needs to coordinate with 2 other services, one inbound and another outbound to checkpoint its state. 

Let's come back to the issue.   I understand the outbound is the deleting pod will access a upstream service. But what do you mean the inbound ? Talk to itself?

**Comment by gotwarlost** [comment]
No another service watching pods detects that the pod has been deleted and communicates with it by sending checkpoint requests.

**Comment by gotwarlost** [comment]
this doesn't seem to be happening with the 1.3.3 release, since a connection is now identified using envoy metadata and not its IP address

**Comment by duderino** [comment]
@gotwarlost given the difficulty of backporting a fix without introducing new issues, the recommendation is to for everyone affected by this issue to just upgrade to 1.3+

**Comment by karthikt-yahoo** [comment]
@gotwarlost In 1.3.3 do you see listeners are not getting removed ? we see listeners are getting removed in 1.3.6 with pilot config update do istio sidecar proxies as soon as pod enters into terminating state. Also it would like helpful if some one explains what is the actual solution implemented to fix this issue. Thanks

**Comment by hzxuzhonghu** [comment]
@karthikt-yahoo I wanna know how do u deploy your app? Is it of multi instances? Did you delete service before deleting the pod?  I need more info.

> we see listeners are getting removed in 1.3.6 with pilot config update to istio sidecar proxies as soon as pod enters into terminating state.

Is that inbound direction listeners?

**Comment by nirvanagit** [comment]
@hzxuzhonghu 

Pilot debug logs when pod gets deleted. This does not happen every time.
```
2020-01-03T00:53:31.602844Z     debug   Build 39 listeners for node test-app-bd55c55dc-52gbc.test-ns including 0 inbound, 37 outbound, 1 virtual and 1 virtual inbound listeners
```

And the corresponding application proxy's config_dump shoes that listener was removed and put into draining.

**Comment by nirvanagit** [comment]
@hzxuzhonghu @howardjohn - can we open this issue.

This is what I am observing with 1.3.6.

Pilot is watching on pod and endpoint resources, so an update on either will trigger a push to sidecar proxies.

Whenever the following events occur at the same time
1. POD is deleted
2. Pilot receives the DELETE pod event.
3. Sidecar proxy of the deleted pod requested for a `type.googleapis.com/envoy.api.v2.Listener` 

discovery ends up sending 0 active listeners to the pod which results in the sidecar proxy returning 5xx to clients. 

We have a preStop in the sidecar proxy which waits for the application to get terminated, but the above behavior does not let that happen.

**Comment by hzxuzhonghu** [comment]
We should not allow access to a shutting down pod.  Because we can not guarantee the request can be gracefully handled.
