### ISSUE TITLE
Ingress proxy / service mesh `guid:x-request-id` not compatible with Jaeger UI

### ISSUE THREAD

**Issue by Stono** [istio/istio#1792]
Hey, 
I am trying to trace requests from our monitoring system through Jaeger, after following the [instructions on installation](https://raw.githubusercontent.com/jaegertracing/jaeger-kubernetes/master/all-in-one/jaeger-all-in-one-template.yml).  In my monitoring system, I am setting `x-request-id` on the request, which appears to be being reflected in Jaeger as `guid:x-request-id`:

<img width="837" alt="screen shot 2017-11-20 at 15 08 12" src="https://user-images.githubusercontent.com/1486729/33025001-95601ce6-ce04-11e7-86f7-561dced3fb20.png">

However you're unable to search for `guid:x-request-id` in the Jaeger gui due to the colon, therefore you cannot filter by request id.  As you can see from the Jaeger gui code, they can't handle colons.

https://github.com/jaegertracing/jaeger/blob/master/cmd/query/app/query_parser.go#L190

**Comment by rshriram** [comment]
@objectiser ^^^

**Comment by objectiser** [comment]
This is a Jaeger issue, so could close this - although you might want to keep it open until fixed in case other users find the same problem?

**Comment by Stono** [comment]
I think it makes sense to keep it open, I came here first looking for answers before I spoke with the jaeger devs!

**Comment by andraxylia** [comment]
Unless there is something we can do in Istio to help with this issue, let's close this.

**Comment by tiffon** [comment]
Some work has been done in Jaeger to address this:

- jaegertracing/jaeger#550
- jaegertracing/jaeger-ui#145

The change is to use [logfmt](https://brandur.org/logfmt) for tag matching in the search form. 

The changes are done, but not yet released.

cc @yurishkuro, @objectiser
