### ISSUE TITLE
integ-mixer-k8s-tests TestRateLimiting_RedisQuotaFixedWindow regression

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#17929]
There has been a major regression to the TestRateLimiting test: https://testgrid.k8s.io/istio_istio_postsubmit#integ-mixer-k8s-tests_istio_postsubmit&width=20&exclude-non-failed-tests=

Previously this test passed ~50% of the time. Now, as of 10/15, it has never passed

Related to https://github.com/istio/istio/issues/15686

**Comment by howardjohn** [comment]
@gargnupur I marked this as a release blocker for 1.4 until we can verify this is a test issue, and not a real regression in rate limiting. Please take a look

**Comment by howardjohn** [comment]
Related to https://github.com/istio/istio/issues/15686

**Comment by gargnupur** [comment]
Looks similar to #15686 only

**Comment by howardjohn** [comment]
@gargnupur it is now failing 100% of the time though, do you think its just random chance or something broke recently?

**Comment by gargnupur** [comment]
From logs, it looked random..  I am trying to see if it repro's in this PR too: https://github.com/istio/istio/pull/15593

**Comment by gargnupur** [comment]
Doesn't repro here: https://github.com/istio/istio/pull/15593..

**Comment by howardjohn** [comment]
Its back to failing only 80% of the time  (https://github.com/istio/istio/issues/15686)
