### ISSUE TITLE
Kiali is unable to capture the traffic for bookinfo app.

### ISSUE THREAD

**Issue by chayan88** [istio/istio#17937]
**Bug description**
Kiali is unable to capture the traffic for bookinfo app on Openshift 3.11 on IBM Cloud.

Deployed the bookinfo app and expose the "productpage service" and generated traffic using the productpage svc route , but in Kilai nothing is showing up.

But If I expose a istio ingress gateway service and generate the traffic some portion of traffic showsup in kiali.

Question: Is it necessary to use istio gateway to see the traffic in Kiali?   

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Kiali should show the traffic for bookinfo app.
**Steps to reproduce the bug**
Deploy bookinfo On Openshift 3.11 (on IBM Cloud) and access the app using istio ingress svc (by exposing it securely)
**Version (include the output of `istioctl version --remote` and `kubectl version`)**

bash-4.2$ istioctl version --remote
client version: 1.3.2
citadel version: 1.3.2
egressgateway version: 1.3.2
galley version: 1.3.2
ingressgateway version: 1.3.2
pilot version: 1.3.2
policy version: 1.3.2
sidecar-injector version: 1.3.2
telemetry version: 1.3.2

kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-09-12T23:41:09Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"
**How was Istio installed?**
Using Helm (demo profile)
**Environment where bug was observed (cloud vendor, OS, etc)**
IBM Cloud
Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.
![Screenshot from 2019-10-17 01-09-31](https://user-images.githubusercontent.com/33457041/66952862-0d856380-f07b-11e9-803c-c2be28dbb92d.png)

**Comment by chayan88** [comment]
@howardjohn Do we have any insight on this? I have tried this in multiple cluster and got same result.
Thanks
Chayan

**Comment by linsun** [comment]
Did you use CNI plugin?

Also, what k8s level is openshift 3.11?  You want to make sure it met our k8s requirements: https://istio.io/docs/setup/platform-setup/

**Comment by sethokayba** [comment]
With istio 1.3.3, on OpenShift 3.11.88, i confirm i have the same issue.
![Annotation 2019-10-23 223206](https://user-images.githubusercontent.com/1992713/67435867-01525680-f5e5-11e9-999d-256a510921c4.JPG)

**Comment by chayan88** [comment]
@linsun Please find my answer below:
Did you use CNI plugin: I hope yes. I have installed the istio with below command.
"helm template install/kubernetes/helm/istio --name istio --namespace istio-system --values install/kubernetes/helm/istio/values-istio-demo.yaml --set istio_cni.enabled=true | kubectl apply -f - "
Also as per @sethokayba on openshift 3.11 CNI plugin is enabled by default.-->> https://istio.io/docs/setup/additional-setup/cni/

Version:
openshift v3.11.146
kubernetes v1.11.0+d4cacc0

Also all the platform related configuration are in place . I  am able to spin up the bookinfo app as well.

**Comment by linsun** [comment]
Note: k8s 1.11 is not on the list of recommended k8s from https://istio.io/docs/setup/platform-setup/

**Comment by linsun** [comment]
@brian-avery @knrc could you shed some light on if openshift v3.11 works with Istio 1.3?  

https://istio.io/docs/setup/platform-setup/openshift/

Also, is this instruction only for openshift on prem?  https://docs.openshift.com/container-platform/3.11/servicemesh-install/servicemesh-install.html#service-mesh-install_prerequisites

cc @jwendell

**Comment by jwendell** [comment]
We have tested Istio 1.1 (as shipped in Maistra) with OpenShift 3.11.

Istio 1.3 (and 1.4) were tested on OpenShift 4.1 and 4.2 respectively.

For a good out-of-box experience using Istio on OpenShift we recommend using Maistra: https://maistra.io.

**Comment by chayan88** [comment]
@jwendell I just installed istio-1.1.9 (OpenShift on IBM Cloud). and deployed bookinfo app.
As our FW allows only 443 , I have reconfigured the bookinfo gateway with HTTPS something like this.
```
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      privateKey: /etc/istio/ingressgateway-certs/tls.key
      serverCertificate: `/etc/istio/ingressgateway-certs/tls.crt
```
And able to access the app using istio-ingressgateways external IP.

Problem: Kiali cannot be accessible via route , I did a port forwarding to access. but the problem remains same. Kiali cannot catch all the traffic.

![image (9)](https://user-images.githubusercontent.com/33457041/67514684-d63a3680-f6ba-11e9-9272-44e158078a8c.png)

**Comment by chayan88** [comment]
@jwendell To use Maistra ... I think we will have to configure the nodes and registry ... how do I configure them in openshift on IBM Cloud where you don't have os label access?

**Comment by linsun** [comment]
@chayan88 nodes are already configured for you, so you don't need to worry about it.

**Comment by linsun** [comment]
@chayan88  i believe your issue is sidecar isn't capture any traffic.  So the istio cni doesn't do its job to program the traffic redirect for the pod.

**Comment by sethokayba** [comment]
hello, 

I just installed istio 1.1.15, which is declared as tested with **kubernetes 1.11**, and the problem is the same. 

I used:
- OpenShift 3.11.88 (kubernetes 1.11)
- Istio 1.1.15
- Cni-plugin for sidecar injection.

The traffic is not hitting the other services on kiali : 

![Kiali-istio-1 1 15](https://user-images.githubusercontent.com/1992713/67582546-e517fc00-f741-11e9-80f5-dbfe8ebb2a98.JPG)

**Comment by sethokayba** [comment]
@chayan88 

I tried to go with the same config as in my last comment, and found that kiali is showing 100% of generated traffic but using a different example. https://rinormaloku.com/istio-an-introduction/

![Kiali-istio-rinormaloku-1 1 15](https://user-images.githubusercontent.com/1992713/67600477-21f7e900-f76a-11e9-9268-c5ef4a8eb74d.JPG)


Can you please try this sample app instead of bookinfo app and give us your results ?

**Comment by chayan88** [comment]
@sethokayba If you dont mind could you please let me know what is the exact command you run for the installation along with CNI plugin?
I am running this command 
```helm template install/kubernetes/helm/istio --name istio --namespace istio-system     --values install/kubernetes/helm/istio/values-istio-demo.yaml --set istio_cni.enabled=true | kubectl apply -f -```

**Comment by chayan88** [comment]
@sethokayba this time with 1.3.3 istio upstream with different app mentioned by you worked for me.
![image](https://user-images.githubusercontent.com/33457041/67606811-24753580-f7a0-11e9-9f37-d92a98078e40.png)

**Comment by sethokayba** [comment]
on OpenShift 3.11, you don't need to install the CNI Plugin, it is already included, you need just to pass the --set istio_cni.enabled=true to activate it.

For now, the thing to do, is to find the difference between "sentiment" and "bookinfo" configs. What makes "sentiment" work and what don't for "bookinfo"
