### ISSUE TITLE
Stabilize SDS egress gateway test

### ISSUE THREAD

**Issue by incfly** [istio/istio#17933]
**Bug description**

Integration test for gateway SDS based `ISTIO_MUTUAL` is flaky.
https://testgrid.k8s.io/istio_istio_postsubmit#integ-security-k8s-tests_istio_postsubmit&include-filter-by-regex=.*SdsEgress.*&width=20

Note we have negative test always passing, which expects 503. And the positive failing, returns 503 rather than 200.

We update the gateway config during test for the same port. We probably can use different port/routing to apply the one config, configuring different egress gateway port in the beginning, one serving ISTIO_MUTUAL, one does not. This way, we don't need to wait config propagation during the test.

Also some local run test can't get gateway readiness passing. This is not demonstrated from the failure log from the post submit though.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X ] Security
[X ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by incfly** [comment]
I'll also try to modify the gateway resource to add response header manipulation.

In this way, we can inspect the response rather than rely on Prometheus metrics to verify request goes through gateway.

And thus we can keep sending request from client to "bing.com" util get expected response header.

**Comment by howardjohn** [comment]
not stale, the test is skipped

**Comment by ramaraochavali** [comment]
not stale, the test is skipped

**Comment by howardjohn** [comment]
test is still skipped @istio/wg-security-maintainers

**Comment by JimmyCYJ** [comment]
cc @Monkeyanator who added https://github.com/istio/istio/blob/master/tests/integration/security/sds_egress/sds_istio_mutual_egress_test.go  😄

**Comment by howardjohn** [comment]
Still skipped @istio/wg-security-maintainers, any interest in reviving?

**Comment by lei-tang** [comment]
Quoted from https://github.com/istio/istio/pull/41598: "TestSdsEgressGatewayIstioMutual was disabled for 3 years and it verifies cases already covered by [TestMutualTlsOrigination](https://github.com/istio/istio/blob/b459487e02e19fdbc24ac85924c95b1b44de6c2b/tests/integration/security/egress_gateway_origination_test.go#L122),
so it does not make sense to keep and maintain it. In addition, this test verifies collecting metrics what is also covered in telemetry package." 

As https://github.com/istio/istio/pull/41598 has been merged, this issue is closed.
