### ISSUE TITLE
Stackdriver mixer adapter does not support user-configured mesh_uid in contextgraph (but does in metrics and logs)

### ISSUE THREAD

**Issue by djazayeri** [istio/istio#17952]
**Bug description**

I want to include a user-specified mesh_uid in the telemetry reported by the Stackdriver mixer adapter to the stackdriver backend. I can do this for metrics and logs, but I cannot do so for contextgraph, which hardcodes a value like this: https://github.com/istio/istio/blob/1.3.3/mixer/adapter/stackdriver/contextgraph/contextgraph.go#L82

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

If I specify a mesh_uid in the yaml that configures the stackdriver adapter, this value should be sent to the contextgraph backend. (I don't care about the exact details of the yaml format.)

If I don't specify a value, then the current behavior should remain.

**Steps to reproduce the bug**

N/A

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

All versions

**How was Istio installed?**

N/A

**Environment where bug was observed (cloud vendor, OS, etc)**

N/A

**Comment by djazayeri** [comment]
@douglas-reid FYI

**Comment by douglas-reid** [comment]
fyi: @mandarjog

**Comment by mandarjog** [comment]
@djazayeri do you need this for 1.4 or 1.4.x is ok ?

**Comment by djazayeri** [comment]
1.4.x is okay, because I'll also need to have the change backported to 1.3.x (and maybe 1.2.x).
