### ISSUE TITLE
Flaky test: TestSyntheticServiceEntry

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#17953]
I've only seen this one fail once, but its also new, so not sure how common this is:
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/17946/integ-pilot-k8s-tests_istio_release-1.4/6

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/batch/integ-pilot-local-tests_istio/2373 another one

**Comment by howardjohn** [comment]
https://prow.k8s.io/view/gcs/istio-prow/logs/integ-pilot-local-tests_istio_postsubmit/373 if this isn't easy to fix can you `.Skip` the test for now?

**Comment by Nino-K** [comment]
@howardjohn I havn't had a chance to look at it yet, let me skip it for now and I will look at it first thing tomorrow.

**Comment by Nino-K** [comment]
The data race errors are new, I have never seen them before, however I will look at them shortly.

**Comment by howardjohn** [comment]
I think @Nino-K fixed this

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/20646/integ-pilot-k8s-tests_istio/7289

**Comment by howardjohn** [comment]
https://prow.k8s.io/view/gcs/istio-prow/logs/integ-k8s-115_istio_postsubmit/520

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gcs/istio-prow/logs/integ-k8s-115_istio_postsubmit/522

**Comment by Nino-K** [comment]
Removing this test as part of istiod work https://github.com/istio/istio/pull/20704
