### ISSUE TITLE
istio operator takes long for reconciling

### ISSUE THREAD

**Issue by irisdingbj** [istio/istio#17969]
2019-10-11T05:33:39.787891Z    info    begin reconciling resources
2019-10-11T05:34:41.829544Z    info    end reconciling resources

It will take more than 1 min to finish reconciling every time and most of the time is spending on updating resources.

**Comment by ostromart** [comment]
Fixed in https://github.com/istio/istio/pull/20344 with a workaround but we should revisit this in 1.6 to see if we can find a better solution.

**Comment by howardjohn** [comment]
I think this has been improved a lot in 1.6 - in too many PRs to link here.
