### ISSUE TITLE
use lyft's protoc-gen-validate in our apis

### ISSUE THREAD

**Issue by rshriram** [istio/istio#1796]
The v2 api that we are building out in envoy is using the protoc-gen-validate plugin that automates some of the common validation tasks. It targets Go based code specifically. 

We could use this in our istio/api and cut down on JSON schema style validations across our code base.

https://github.com/lyft/protoc-gen-validate

Thoughts? @geeknoid @mandarjog @ZackButcher @kyessenov @ayj

**Comment by geeknoid** [comment]
This seems very nice.

Do you know if this integrate with gogo code generation?
​

**Comment by geeknoid** [comment]
@wora

**Comment by kyessenov** [comment]
It acts as another protoc plugin over protos. The generated functions `Validate()` currently target golang/proto sources. The functions are templatized (see https://github.com/lyft/protoc-gen-validate/blob/master/templates/go/ltgt.go), so all the differences in gogo would require another set of templates where it matters.

**Comment by kyessenov** [comment]
I'm targeting standard golang protobuf in Envoy contorl plane, by the way.

**Comment by ayj** [comment]
SGTM. 

On a related note, it'd be great to consistently use gogoproto _or_ golang_ proto for user-facing APIs. The current mix of the two leads to funny things like parallel name-to-type maps depending on now the proto was defined, e.g. 

```golang
if proto.MessageType(v.MessageName) == nil && gogoproto.MessageType(v.MessageName) == nil {
    errs = multierror.Append(errs, fmt.Errorf("cannot discover proto message type: %q", v.MessageName))
}
```

I don't think this needs to necessarily match what `go-control-plane` uses, though I wouldn't complain if it did, since we don't mix/match those protos with istio/api protos.

**Comment by kyessenov** [comment]
We could use gogo and goproto at the same time, just not for the same protos. I understand the performance requirements for Mixer request-path protos, but those requirements don't apply to config protos.

**Comment by geeknoid** [comment]
Given that we need the perf for Mixer's stuff, so we want gogo there, is
there a compelling reason why we shouldn't be consistent and not use gogo
everywhere? I think consistency across the project is a pretty important
principle in general.

**Comment by kyessenov** [comment]
I think one-of serialization to JSON is different between the two (hit a
bug there). So we're imposing gogo on all projects which want to use istio
config or istio libraries.

**Comment by kyessenov** [comment]
We also will need to write gen validate for gogo from scratch.
