### ISSUE TITLE
Better Release Note documentation for multiCluster.clusterName in helm/istio/values.yaml

### ISSUE THREAD

**Issue by jtakamine** [istio/istio#17962]
**Describe the feature request**
Please consider explicitly documenting multiCluster.clusterName value in `helm/istio/values.yaml` in the Release Notes, so that users in multi-cluster environments know that they will need to explicitly set the value after upgrading, otherwise their installation can likely experience routing issues: https://github.com/istio/istio/commit/2e789b91d4fc1d9680ba5ce537cbed50313d8dbc#diff-7dad29cba9d2ca3e8570c8f65f4b7e86R408-R411.

In a multi-cluster environment, taking the current default (empty string) causes multiple clusters to inject sidecars with their ISTIO_META_CLUSTER_ID environment variables set to "Kubernetes". In our case, this led to routing problems between clusters. We found that a single proxy was being represented in multiple service registries, which according to the following comment, is unexpected and/or undefined behavior: https://github.com/istio/istio/blob/1.3.1/pilot/pkg/serviceregistry/aggregate/controller.go#L237-L238.

In our environment, we take most of the Istio configuration as-is, but customize some values. We ended up hitting the above issue because we took the default for `multiCluster.clusterName` in the helm template.

Granted, the helm values file has a comment that documents the expected configuration, it would have been helpful to see this variable called out in the Release Notes to warn that the default is incompatible with multi-clusters environments.

**Describe alternatives you've considered**
If it's possible to automatically discover the correct cluster name to use, that could be a better solution than relying on the user to configure the cluster name explicitly.

**Affected product area (please put an X in all that apply)**

[X] Configuration Infrastructure
[X] Docs
[] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
Just seeing this now. Sorry we didn't do a great job here. At this point this is old enough that I don't think there is any action we need as we don't suppotr the old 1.3 docs anymore. Sorry we didn't improve this earlier
