### ISSUE TITLE
Bots: Enable cert auto-rotation on eng.istio.io

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#17997]
https://github.com/istio/bots/blob/master/policybot/deploy/policybot/templates/ingress.yaml

At present the ingress requires pre-issued certificates.
Update the deployment to run cert-manager and auto renew.

Also consider using https://github.com/GoogleCloudPlatform/gke-managed-certs/blob/master/deploy/managed-certificate-controller.yaml

**Comment by mandarjog** [comment]
@geeknoid

**Comment by joshuacox** [comment]
@mandarjog This still seems pertinent.  Why wouldn't we automate the renewal of certs?  This seems like a no-brainer.

**Comment by mandarjog** [comment]
We should, we are looking for someone to do it :-)

**Comment by clarketm** [comment]
The cert for the https://eng.istio.io/ domain has already expired (*Expired: Wednesday, January 15, 2020 at 2:36:26 PM Pacific Standard Time*). @carolynhu - I have implemented both cert-manager and GKE managed certs in the past, so let me know if you need help resolving.
