### ISSUE TITLE
Validate weights in VirtualService sum up to 100

### ISSUE THREAD

**Issue by jasonwzm** [istio/istio#17998]
**Describe the feature request**

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by sushicw** [comment]
This already exists: https://github.com/istio/istio/blob/master/pkg/config/validation/validation.go#L2088-L2091
https://github.com/istio/istio/blob/master/pkg/config/validation/validation.go#L2104-L2107
