### ISSUE TITLE
Perf testing for analyzers

### ISSUE THREAD

**Issue by sushicw** [istio/istio#18008]
1. Do performance testing of analyzers in general, looking for bottlenecks that appear when running it at scale (on large clusters). This should also give us a baseline idea of expected performance. 

2. Set up integration / bench testing so that we can avoid surprise performance regressions.

The performance implications are most important when running via Galley (using `enableAnalysis`), but the good command-line performance is also important for making the tool as useful as possible.

In Galley, we'd want to be aware of performance both for running analysis, and also time to propagate status updates.

**Comment by howardjohn** [comment]
If you set this up as go benchmarks, then I think we have the ability to track results over time. We aren't using it yet though, but we should, something like a postsubmit that runs all the benchmarks. I am planning to expand pilots benchmarks soon and hoping to utilize this so we may be able to share the same setup work
