### ISSUE TITLE
Istio CNI should ignore pods injected with istio-init

### ISSUE THREAD

**Issue by rlenglet** [istio/istio#18021]
Since https://github.com/istio/istio/pull/17044, the `istio-init` container doesn't clean up the `iptables` chains at startup anymore. If Istio's `iptables` chains are already created before `istio-init` executes, `istio-init` now fails. This can happen in two cases: `istio-init` already executed but failed and is restarted by `kubelet`, or Istio CNI is installed and already initialized `iptables`.

The `iptables` initialization should be performed exactly once, since the initialization is not idempotent even with the chain cleanup that was previously done. Therefore, we should make sure that it is done exactly once in normal cases.

Therefore, Istio CNI should exclude any pod that has already been injected with an `istio-init` container. Currently, it injects any pod that has been injected, regardless of whether it has an `istio-init` container, cf. https://github.com/istio/cni/blob/774dea7a1d3872bff22c7dd06fd10a16be552301/cmd/istio-cni/main.go#L191-L231.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

`master` (due to https://github.com/istio/istio/pull/17044) and `release-1.4` (due to https://github.com/istio/istio/pull/17989). Older releases are not affected.

**Comment by abhide** [comment]
@rlenglet @fpesce Do you mind if I work on this?

**Comment by rlenglet** [comment]
@abhide sounds good to me.

**Comment by abhide** [comment]
Thanks @rlenglet and @howardjohn. Will start taking a look.

**Comment by rlenglet** [comment]
Fixed by https://github.com/istio/cni/pull/218
