### ISSUE TITLE
'istioctl x webhook' tests should not print on success

### ISSUE THREAD

**Issue by esnible** [istio/istio#18025]
The `istioctl x webhook` uses `fmt.Printf()`.  It should print using cmd.Printf() or cmd.OutOrStdout() the way the other commands do.  This will prevent it from cluttering up the unit test logs, and make it easier to write tests.

**Comment by lei-tang** [comment]
Under istioctl directory, there are non-test code that uses cmd.Printf() or cmd.OutOrStdout(). However, in the test code (*_test.go), I could not find examples using  cmd.Printf() or cmd.OutOrStdout(). Can you point me examples using  cmd.Printf() or cmd.OutOrStdout() in the test code (*_test.go) so I can follow the convention? It is unclear which output file handle to be created and passed into the test code (*_test.go).

**Comment by esnible** [comment]
What I want you to do is remove all `fmt.Printf(` from webhook.go.  Replace with `fmt.Fprintf(writer, ...` like the other istioctl commands.

The goal is that doing `go test` in the _istioctl/cmd_ should not produce any output from webhook.go or webhook_test.go.

**Comment by lei-tang** [comment]
https://github.com/istio/istio/pull/18068 is created for this issue. Please review it.
