### ISSUE TITLE
allow presubmit to fail for lint errors on some components?

### ISSUE THREAD

**Issue by jmuk** [istio/istio#1803]
I see some new lint failures coming in the mono repo, and that's because presubmit does not fail for lint failures, currently it simply prints out the lint warnings and pass through. That's mostly because we still haven't make security module pass the linters (see #1446). 

Can we make linters.sh to fail for other modules? This will prevent new lint failures anymore to many of the modules.

**Comment by kyessenov** [comment]
Yes, please force linters as a presubmit check once we have lint-clean code.

**Comment by geeknoid** [comment]
Can we close this?

**Comment by hklai** [comment]
We are already running linter checks in presubmit. Closing.
