### ISSUE TITLE
gencheck command occasionally crashes

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#18032]
See error: https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/17992/gencheck_istio/1256
This sometimes crashes with error 

```

--gogoslick_out: protoc-gen-gogoslick: Plugin failed with status code 127.
mixer/adapter/opa/opa.go:16: running "/home/prow/go/src/istio.io/istio/bin/mixer_codegen.sh": exit status 1
```

**Comment by geeknoid** [comment]
This is a bug in protoc, not something under our control.

**Comment by howardjohn** [comment]
It doesn't matter where the bug is, this is blocking PRs from merging. There are plenty of options.

Make the job optional
Use a different tool
Add retries 
Update protoc
Fix protoc

**Comment by howardjohn** [comment]
Mitigated by retries
