### ISSUE TITLE
Validation should be done in webhook

### ISSUE THREAD

**Issue by ostromart** [istio/istio#18034]
Currently, validation only happens when ICP is unmarshaled in the controller, and errors only show up in logs. Thus, it's possible to create a completely wrong ICP and not know about it without looking at the controller logs.

**Comment by howardjohn** [comment]
is there already a webhook for the operator? Since galley can't do this due to bootstrapping problems

**Comment by sdake** [comment]
Can you take a look at solving this problem?  I am not clear what exactly the requirements are.  @ostromart will add more context.

**Comment by ayj** [comment]
Can you generate an OpenAPI schema for the ICP? This can be added to the ICP CRD definition and would avoid the immediate need for a webhook. The operator can perform additional validation post-CREATE and report errors via the CRD status. 

cc @jasonwzm who worked on the OpenAPI schemas for other Istio CRDs.

**Comment by jasonwzm** [comment]
Some validations are already added to the CRD: https://github.com/istio/operator/blob/master/deploy/crds/istio_v1alpha2_istiocontrolplane_crd.yaml But I agree we can cover more for the actual API. 

I thought there is already a validation webhook for operator CRD?

I see this is needed for 1.5. So do we want to wait till the ICP API is merged with istio/api and then use the full tooling there?

**Comment by richardwxn** [comment]
There is no validation webhook yet for operator CRD. I have this pending PR: https://github.com/istio/operator/pull/441 to create it. 

@jasonwzm I am not familiar with the openAPI schemas, does it only check basic schema such as type? The reason why I ask is that there is some concern about whether it is necessary to have a validation webhook for operator CRD, so I hope it can have something more than openAPI can do

**Comment by jasonwzm** [comment]
@richardwxn you can have more than just type checking. https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#validation is the requirement. It can do things like pattern checking, required field checking, etc, but it has smaller scope than json schema.

**Comment by ostromart** [comment]
Per offline discussion, let's keep this one on the backburner - if we find a compelling scenario that openAPI cannot cover let's bring the webhook back.

**Comment by howardjohn** [comment]
Strongly recommend open API over webhook, webhooks cause nothing but pain :slightly_smiling_face:
