### ISSUE TITLE
New Test, TestWebhook/key/cert_reload, flaky

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#18047]
Looks like this has failed a few times since being merged: https://testgrid.k8s.io/istio_istio#integ-galley-k8s-tests_istio&width=20&exclude-non-failed-tests=

**Comment by ayj** [comment]
On it. Fix is being testing in master and 1.3/1.4 cherry-pick PRs.

**Comment by howardjohn** [comment]
Thank you!
