### ISSUE TITLE
RBAC integration tests to use MTLS

### ISSUE THREAD

**Issue by pitlv2109** [istio/istio#18067]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Currently RBAC integration tests are relying on Istio deploys with mtls out of the box, but this is not the case. We need to apply mtls policies and test them with RBAC, since these two features are used together in most cases.

**Describe alternatives you've considered**
Have Prow run two set of tests for RBAC, one with mtls and one without. This is expensive since the security tests are taking too long already, and it's not as flexible as apply mtls on the fly.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[X] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by incfly** [comment]
+1 very helpful to make test hermetic, not relying on external installation defaults.

**Comment by incfly** [comment]
obsolete.
