### ISSUE TITLE
 Print out version in istioctl analyze

### ISSUE THREAD

**Issue by jasonwzm** [istio/istio#18064]
This is a tracking bug. We want to find out if we need to print out the version of istioctl in each analyze command.

The reason behind is that our current instructions ask the users to pull istioctl from master. While we troubleshoot, it is helpful to get the commit sha they are using.

Currently we are using `istioctl version` to get that information. This bug is to track if we need to put the sha in each output.

**Comment by sushicw** [comment]
Original discussion: https://docs.google.com/document/d/1SiFx6SnNme1InaF4E9oNByyCjM6syilUFAfQRLsmT8Q/edit?disco=AAAADlzwyFc&usp_dm=true&ts=5daa2970

**Comment by howardjohn** [comment]
We should not be telling users to pull istioctl from master. I think there was some discussion about which versions of istioctl worked with which istio version and we decided we want them in sync as much as possible. Also master is way less tested. Also in the install docs we have them install the release version, so telling them to download a whole new istioctl doesn't make much sense to me

**Comment by sushicw** [comment]
As I see the reasoning...

We're adding new analyzer functionality to `istioctl x analyze` at a pretty rapid rate right now, and we want 1) to be able to test that new functionality in the real world ASAP and 2) to make it available ASAP to help solve problems. Waiting for the next major release would mean a large gap before we could do either. 

This specific analyze tool is also intended to be downward-compatible, so e.g. users running a 1.1 cluster could use it to debug their issues without needing to upgrade everything. This is different from other istioctl functionality which is often more coupled. 

Once the pace settles down, I agree that we should recommend just using the latest stable version. For now, though, while we're trying to move quickly and also gather as much feedback as possible, we think it's useful to get the latest from master.

This all assumes, of course, that we put enough unit/integ testing in place to prevent painful regressions! 

CC @davidebbo

**Comment by howardjohn** [comment]
You can always get the SHA from `istioctl version`, I am not sure why we would need to put it in istioctl analyze as well

**Comment by davidebbo** [comment]
@howardjohn I tend to agree that `istioctl version` is good enough here, and that we don't need to display the SHA in the analyze command.

**Comment by sushicw** [comment]
It looks like we have agreement that this isn't needed.
