### ISSUE TITLE
mixer/stackdriver: Allow configuration of trace flush interval

### ISSUE THREAD

**Issue by nicktrav** [istio/istio#18077]
**Describe the feature request**

As a follow on to #18042 and #18074, I noticed that the tracing adapter does not currently have a means of specifying the interval at which the underlying tracing library will flush.

The implementation of the adapter prior to #18074 was such that a flush was made on each call to the handler. If #18074 is accepted, the flushing interval will revert to the default of the underlying tracing library, which is [currently 2 seconds](https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/blob/2b93072101d466aa4120b3c23c2e1b08af01541c/trace.go#L64), but is an implementation detail and could change in the future.

The current `stackdriver` adapter configuration exposes a top level [`pushInterval`](https://github.com/istio/istio/blob/3cfabd9b36bcf9b5af3c390982772e8f1e798618/mixer/adapter/stackdriver/config/config.proto#L50-L52) parameter, which is currently used only for configuring how often _metrics_ are sent to the backend. Tracing is not considered due to the existing flush-per-call behavior.

I'd like to propose adding the ability to configure the flushing behavior of the adapter, _specifically for tracing_.

**Describe alternatives you've considered**

There are a few options:

1) Reuse the existing `pushInterval` field for configuring the interval for sending traces
2) Add a more specific set of fields under the `trace` field
3) Do nothing - use the flushing interval of the library

In the case of 1), it would be a "one size fits all" model. The export period would be the same for metrics, tracing and (maybe in the future) logging (which currently does not allow for configuring the export interval).

Option 2) allows for flexibility in the configuration for tracing, and may allow more granular configuration based on both duration (i.e. "flush after N seconds"), as well as size (i.e. "flush if I get more than N traces"). Some example parameters include `countThreshold` and `delayThreshold`, which line up with the parameters exposed by the current Opencensus exporter implementation.

Option 3) might not be sufficient, as certain deployments may want tighter control of how often a flush to a tracing backend takes place, for example, in the case where larger batches are desirable.

My preference would be for option 2, though this is adding more surface area to the configuration API. In that case, maybe option 1 is enough.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by bianpengyuan** [comment]
Let's go with option 1 as a start to keep config simple. If it turns out to be necessary we could add flush interval for different telemetry types.
