### ISSUE TITLE
Listener reload can cause 503UC errors

### ISSUE THREAD

**Issue by Stono** [istio/istio#18089]
**Bug description**
This is a follow on from https://github.com/istio/istio/issues/18088, as it's technically a different issue.

When envoy needs to reload listeners, this can result in a 503UC for in-flight requests, for example:

<img width="1680" alt="Screenshot 2019-10-19 at 21 15 47" src="https://user-images.githubusercontent.com/1486729/67151406-cb982f80-f2bd-11e9-8601-5dbabc0463dc.png">

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
In flight requests should just be drained, and not result in a 503UC.

**Steps to reproduce the bug**
Make a change that results in the inbound listeners to drain and reload, and _sometimes_ you'll get a `503UC` from the `source` and `503DC` from the `destination`.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.3.3

**How was Istio installed?**
Helm.  We use mTLS, and http2 upgrade.

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE 1.14

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by Stono** [comment]
Closing as confirmed fixed in >=1.3.3

**Comment by Stono** [comment]
eeek, this isn't fixed, I closed the wrong issue :D

**Comment by pbohman** [comment]
The envoy drain logic probabilistic. During the first second of a 45 second drain period there is a 1/45 chance of closing the connection, 2/45 for the second, 3/45 for the third and so on. This could explain immediate connection termination without draining.

https://github.com/envoyproxy/envoy/blob/master/source/server/drain_manager_impl.cc#L35

**Comment by Stono** [comment]
Hhmmmm for want of a better word, that sucks!

Why would it not just give everything 45s to drain then close, instead we have a non deterministic lottery chance of closure

**Comment by pbohman** [comment]
I think closing all of the connections at once could cause a large number of clients to re-initiate connections at exactly the same time. It would be great if there was a guaranteed drain period followed by a separate period for probabilistic connection closing.

**Comment by Stono** [comment]
Yes fair enough that would also work, having no guaranteed drain period at all is pretty poor and will cause lots of istio users headaches.

Cc. @rshriram @howardjohn

**Comment by rshriram** [comment]
fair enough.. cc @istio/wg-networking-maintainers-data-plane ^^^ .

**Comment by lambdai** [comment]
I can add a option to minimum drain timeout.
I am curious since the behavior was there at least 1 year. Why is it suddenly escalated?

**Comment by Stono** [comment]
Because there used to be many issues causing 503s, now we are down to just a handful - this being one of them 😊

**Comment by kyessenov** [comment]
Just to add to the topic: 45s is excessively large. Envoy holds on all listeners resources for that duration, which in turn can slow it down. I've seen requests taking 5s with >1000 draining listeners.

**Comment by Stono** [comment]
Excessively large for your use case maybe, but we’re moving hundreds of legacy applications to istio and many of them are old, slow apps that have timeouts for certain batch requests up to 30s, less than ideal but unfortunately the real world for us, and having an increasing probability of premature termination of the in-flight request during a drain is certainly undesirable. 

As our apps don’t have 1000s of listeners, we would most certainly chose deterministic draining.

Anyway, so long as it’s configurable, you could certainly default it lower and leave it to the operator to make the decision that is right for their domain.

**Comment by kyessenov** [comment]
Agree it should be configurable. It just needs to be linked to the rate of xDS change for a particular proxy. As long as we give controls for both, we can provide guidance how to tune them.
