### ISSUE TITLE
Failed to register custom resources

### ISSUE THREAD

**Issue by roommush** [istio/istio#1809]
The error msg is "failed to register custom resources. Post https://kubeleteservice-ip:443/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitons: dial tcp kubeleteservice-ip:443 i/o timeout. ".  I use istio 0.2.12, k8s 1.8.1.

**Comment by roommush** [comment]
After modifying the port, it still doesn't work
"containers": [
      {
        "name": "discovery",
        "image": "docker.io/istio/pilot:0.2.12",
        "args": [
          "discovery",
          "-v",
          "2",
          "--admission-service",
          "istio-pilot-external",
          "**--admission-service-port**",
          "**8080**"
        ],

**Comment by pipejakob** [comment]
Can you detail where you're seeing the `dial tcp kubeleteservice-ip timeout` error? Is this a part of initial installation, or the output of one of the components? What exact command led to that output?

**Comment by GregHanson** [comment]
@roommush have you been able to reproduce this issue in 0.5.1 or later versions of istio?

**Comment by GregHanson** [comment]
closing issue until it can be reproduced in istio version 0.5.1 or later
