### ISSUE TITLE
[Operator controller]Adding k8s settings for component will override other fields

### ISSUE THREAD

**Issue by morvencao** [istio/istio#18093]
Currently if you try to add k8s settings for component in IstioControlPlane CR like this:

```
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
metadata:
  name: example-istiocontrolplane
spec:
  profile: default
  trafficManagement:
    components:
      pilot:
        k8s:
          hpaSpec:
            minReplicas: 2  # ... default 1
```

Then apply the CR into the cluster, other fields in the k8s settings will be 'empty' value in the updated  IstioControlPlane CR:
```
root@mcdev1:~/go/src/istio.io/operator# kc get icp example-istiocontrolplane -o yaml
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
metadata:
  creationTimestamp: "2019-10-20T03:50:00Z"
  finalizers:
  - istio-finalizer.install.istio.io
  generation: 2
  name: example-istiocontrolplane
  namespace: default
  resourceVersion: "2456"
  selfLink: /apis/install.istio.io/v1alpha2/namespaces/default/istiocontrolplanes/example-istiocontrolplane
  uid: 19919684-6169-4c02-9b46-e4b465150c0b
spec:
  profile: default
  traffic_management:
    components:
      pilot:
        k8s:
          hpa_spec:
            maxReplicas: 0
            minReplicas: 2
            scaleTargetRef:
              kind: ""
              name: ""
status:
  status:
    Citadel:
      status: 2
    Galley:
      status: 2
    IngressGateway:
      status: 2
    Injector:
      status: 2
    Pilot:
      status: 2
    Policy:
      status: 2
    Prometheus:
      status: 2
    Telemetry:
      status: 2
    crds:
      status: 2
```

**Comment by morvencao** [comment]
`kubectl` uses `json` lib to marshal/unmarshal the api object, while some json tags(omitempty) are missing the API spec, see: https://github.com/istio/operator/blob/master/pkg/apis/istio/v1alpha2/istiocontrolplane_types.pb.go#L1940 and https://github.com/kubernetes/api/blob/master/autoscaling/v2beta1/types.go#L37-L60

**Comment by ostromart** [comment]
I think this is the same as https://github.com/istio/istio/issues/18036

**Comment by ostromart** [comment]
Is this still an issue @morvencao ? I tried it but cannot repro. It's not clear to me why such behavior would happen since we merge the json trees without any schema using a strategic merge. 
Could you confirm?

**Comment by morvencao** [comment]
@ostromart I can still reproduce the issue. In my env, if I create such ICP cr:
```
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
metadata:
  name: example-istiocontrolplane
spec:
  profile: default
  trafficManagement:
    components:
      pilot:
        k8s:
          hpaSpec:
            minReplicas: 2  # ... default 1
```

As you can see above, I changed the `spec.trafficManagement.components.pilot.k8s.hpaSpec.minReplicas` from default value `1` to `2`, then I get the ICP cr with kubectl:

```
root@mcdev1:~/go/src/istio.io/operator# kc get icp
NAME                        AGE
example-istiocontrolplane   38s
root@mcdev1:~/go/src/istio.io/operator# kc get icp example-istiocontrolplane -o yaml
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
metadata:
  creationTimestamp: "2019-10-25T02:09:20Z"
  finalizers:
  - istio-finalizer.install.istio.io
  generation: 2
  name: example-istiocontrolplane
  namespace: default
  resourceVersion: "2004"
  selfLink: /apis/install.istio.io/v1alpha2/namespaces/default/istiocontrolplanes/example-istiocontrolplane
  uid: 123635af-13a9-4887-988b-4874b7ac90dc
spec:
  profile: default
  traffic_management:
    components:
      pilot:
        k8s:
          hpa_spec:
            maxReplicas: 0
            minReplicas: 2
            scaleTargetRef:
              kind: ""
              name: ""
status:
...
```

As you can see. other fields in HPA, `maxReplicas` `scaleTargetRef` become the default value for its type.

I know the root cause is that in kube-api-server, only the field `minReplicas` has value, others are empty, while other fields like `maxReplicas` and `scaleTargetRef` don't have json tag of `omitempty`, so `json` lib will provide default value of corresponding type.

**Comment by ostromart** [comment]
Per our discussion, it appears that this only affects how ICP is displayed with kubectl get, but when the overlay is merged with the base, the scaleTargetRef fields from base are retained and not set to default nil values. 
Since there's no solution that we can think of right now without drawbacks and this doesn't affect function, let's defer it to 1.5.

**Comment by kramvan1** [comment]
@ostromart @morvencao   Trying to understand this one better.    A few questions to start with:

1. Why does the operator re-write/override the `spec:` section at all?   Seems very unnecessary. 
2. Why do the component names change?  from example above `trafficManagement` to `traffic_management`    Which one is correct for this `v1alpha2` version?   Should the later be used for input then?
3. Does the ICP need to have the `profile: default` ?   I assume that will happen if left out.

For our use case, the ICP resource is "locked" down, such that `spec:`  modifications to the ICP resource will be merged back to include the original settings.   If the section names were the same, this probsblhy would not be so bad.   Can that bug get fixed soon?
This is the mess we end up with:
[icp-before.txt](https://github.com/istio/istio/files/3790611/icp-before.txt)
[icp-after.txt](https://github.com/istio/istio/files/3790610/icp-after.txt)

**Comment by kramvan1** [comment]
@ostromart @morvencao I'm also seeing that our added annotations and labels are also removed during the ICP processing,   this should never happen.

**Comment by morvencao** [comment]
@kramvan1 Did't catch that, let me have a try.

**Comment by kramvan1** [comment]
@morvencao   Hi, we have the following in the `metadata` section to begin with:
```
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
metadata:
  annotations:
    version: 1.4.0_663
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
  name: managed-istiocontrolplane
  namespace: ibm-operators
```
After the reconcile, the annotations and labels are lost.
```
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
metadata:
  name: managed-istiocontrolplane
  namespace: ibm-operators
```
This causes issues with our resource manager which uses these annotations and labels for tracking purposes.

**Comment by kramvan1** [comment]
@ostromart @morvencao

Would be great to get an answer to the question #2 above.  Why the component names are different than the API.

**Comment by sdake** [comment]
This requires a solution sooner rather than later.

**Comment by ostromart** [comment]
I think the issue is that we are accidentally mutating the ICP spec field in the process of unmarshaling, because we overwrite the value back to the original ICP, which is then written back with status. 
What we need to do to fix it is to make a read only copy that is unmarshaled with jsonpb. 
@morvencao do you have time to fix this one? I'm pretty tied down with the release atm but I can explain the fix in more detail if the above doesn't make sense.

**Comment by morvencao** [comment]
@ostr Looks good, let me give it a try.

**Comment by howardjohn** [comment]
Is this the same as https://github.com/istio/istio/issues/18809

**Comment by morvencao** [comment]
@howardjohn See my comment https://github.com/istio/istio/issues/18809#issuecomment-552712096, that issue should also be fixed.
