### ISSUE TITLE
integration/security/mtls gateways fail to startup

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#18102]
Seen this in a few PRs: https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18054/integ-security-k8s-tests_istio/2791

istio-proxy fails to get ready: https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/18054/integ-security-k8s-tests_istio/2791/artifacts/mtls-ced2ab09519c417c81685596e0/_suite_context/istio-state-871796244/istio-egressgateway-5c7b6f9d7c-bwjmp-istio-proxy.log

**Comment by incfly** [comment]
This might just be another consequences of the same root cause, https://github.com/istio/istio/issues/18106

**Comment by howardjohn** [comment]
Maybe similar but not the same? In this case it looks like we cannot even connect to pilot. Maybe this is due to control plane security enabled and issue with certs (maybe certs not loaded, like in the other case?)

**Comment by howardjohn** [comment]
This is still happening https://prow.istio.io/view/gcs/istio-prow/logs/integ-k8s-117_istio_postsubmit/19

**Comment by incfly** [comment]
Addressed, closing

**Comment by incfly** [comment]
sorry, realized this may not be the same issue, i'll need to confirm tomorrow

**Comment by howardjohn** [comment]
Yes I have seen this recently so may be an issue still

**Comment by incfly** [comment]
https://testgrid.k8s.io/istio_istio#integ-security-k8s-tests_istio&include-filter-by-regex=.*mtls.*

Seems pretty stable now, no red even i scroll back to 11/08. Feel free to reopen if above link is inaccurate.
