### ISSUE TITLE
I cannot change TerminationDrainDuration in pilot-agent 

### ISSUE THREAD

**Issue by cebernardi** [istio/istio#18115]
Hi all,
I was unsuccessfully trying to increase the graceful termination period for pilot-agent (both in Istio 1.2.5 and 1.3.3):

following the documentation and this other issue (#14988), I re-deployed Istio via helm chart providing the following relevant configuration:
```
pilot:
  env:
    TERMINATION_DRAIN_DURATION_SECONDS: 10
```

I can see the `pilot` deployment modified accordingly:

```
Environment:
      POD_NAME:                             istio-pilot-7d4d59879d-99fd4 (v1:metadata.name)
      POD_NAMESPACE:                        istio-system (v1:metadata.namespace)
      GODEBUG:                              gctrace=1
      PILOT_PUSH_THROTTLE:                  100
      TERMINATION_DRAIN_DURATION_SECONDS:   10
      PILOT_TRACE_SAMPLING:                 1
      PILOT_DISABLE_XDS_MARSHALING_TO_ANY:  1
```

and `istio-pilot` pod restarted.

However when I delete a pod in the mesh, I can see in the log
```
Graceful termination period is 5s, starting...
```
and then it actually waits for 5secs before shutting down (default behaviour, no custom configuration picked up)

I tried multiple time to restart the pod and it doesn't modify the outcome.

What am I missing?
Thank you!

**Comment by howardjohn** [comment]
The environment variable is in istio-proxy, not pilot

**Comment by cebernardi** [comment]
Hi @howardjohn ,
thank you for your reply!

I probably misunderstood this, then... https://github.com/istio/istio/issues/7136#issuecomment-480975510

I just modified the injection template and it worked.

However we're relying on helm to configure and deploy Istio in our cluster,  and modifying the config map in our use case is a little bit "dirty", because it would need to happen (if I correctly understand) outside of helm release cycle.

If I'm not missing any chart configuration option from this page (https://istio.io/docs/reference/config/installation-options/), do you see any value in submitting a PR allowing https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/files/injection-template.yaml to set any env variable set under `global.proxy.env`?

**Comment by howardjohn** [comment]
That would be useful

**Comment by cebernardi** [comment]
great news!
Thanks @howardjohn !

**Comment by cebernardi** [comment]
@howardjohn I opened a PR on this issue. (https://github.com/istio/istio/pull/18333)
We agreed on a tentative approach of rendering istio-proxy environmant variables from `global.proxy.env`, but the PR also proposes a new annotation to allow single pods to override those variables. Please let me know what you think about the annotation approach, from a user point of view I find useful to have the possibility to specify special configurations to accommodate special test cases.

**Comment by deiwin** [comment]
Fixed by https://github.com/istio/api/pull/1194 I belive

**Comment by howardjohn** [comment]
Fixed by ^

**Comment by cebernardi** [comment]
@howardjohn I don't think https://github.com/istio/api/pull/1194 fixes it.
I don't think it's giving the possibility for the single workload to specify Environment variables for its own sidecar.

There are use cases where we could be potentially be fine with a general settings, BUT we know that a particular workload (and only that one) needs a different configuration.

As I pointed here https://github.com/istio/istio/issues/18115#issuecomment-546419828, we were (are) in need to have a mechanism to allow single workloads to provide special configuration. 
My understanding of  https://github.com/istio/api/pull/1194 is that this is setting the behaviour of the whole mesh.

**Comment by kevin-lindsay-1** [comment]
Posting a reference to a comment that I made after going down this rabbit hole, to hopefully save others some time:
istio/istio#18333 (comment)
