### ISSUE TITLE
shared module for validator webhook server

### ISSUE THREAD

**Issue by jmuk** [istio/istio#1812]
Currently `pilot/platform/kube/admit/admit.go` defines the http server which behaves as k8s external admission webhook for validating pilot config. #1728 is going to add the webhook for mixer config.

The abstract server code (i.e. http server / certification / webhook registration) would be quite similar, although currently it is hard to merge them since some data types are incompatible for historical reason. This will track the issue to unite their implementations; so a single webhook server implementation, but each istio component will attach their own validation logic.

**Comment by ozevren** [comment]
@ayj already implemented this.
