### ISSUE TITLE
Make sure no new breaking change in each API version

### ISSUE THREAD

**Issue by jasonwzm** [istio/istio#18133]
Before we land API versioning, we need to make sure that there is no API break change introduced in the latest API version. 

Current thinking, have a policy bot that detects breaking change in APIs.

**Comment by howardjohn** [comment]
Just wondering, what is the difference between this and the protolock stuff?

**Comment by jasonwzm** [comment]
protolock provides a mechanism to track breaking changes, but it does not currently prevent us from breaking the API.
