### ISSUE TITLE
Principal labels are not filled for telemetry v2

### ISSUE THREAD

**Issue by bianpengyuan** [istio/istio#18139]
Telemetry v2 misses source and destination principal labels. These two attributes are not yet available in wasm data accessor API. We need to add a new wasm API to read SAN from local and peer cert.

**Comment by bianpengyuan** [comment]
@kyessenov @mandarjog

**Comment by kyessenov** [comment]
The current workflow as far as I understand it:
- istio_authn receives a config about the principal binding (SAN peer cert or JWT origin user)
- once computed, it saves under dynamic metadata `istio_authn`, with struct `{request.auth.principal: "..."}`; it also adds source.user, source.principal, etc.
- mixer filter reads this from dynamic metadata and sets the values from there for source.principal
- mixer filter sets destination.principal directly not using authn_filter. There's some parsing logic to strip SPIFFE prefix.

@diemtvu to confirm.

Note that there is no TCP istio_authn filter.

**Comment by kyessenov** [comment]
Ok, source.principal is actually computed the same way AFAICT. So we should be OK re-computing the value in mixer v2 architecture for source and destination principal. 

request.auth.principal should be delegated to authn_filter.

**Comment by kyessenov** [comment]
Example value: cluster.local/ns/default/sa/server
Note the stripped SPIFFE prefix:
```
 X509v3 Subject Alternative Name: critical
                URI:spiffe://cluster.local/ns/default/sa/server
```

**Comment by bianpengyuan** [comment]
Fixed by https://github.com/istio/proxy/pull/2503
