### ISSUE TITLE
Clean up the old mtls integration test

### ISSUE THREAD

**Issue by incfly** [istio/istio#18156]
**Bug description**

TestMTlsWithAuthNPolicy those tests are running with old test framework. 

Only concern is is this might be run in multi cluster env setup. But however, it does not make sense to run two set of the same tests but different test frameworks...

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
This is no longer running
