### ISSUE TITLE
operator master does not appear to start a proxy for pilot

### ISSUE THREAD

**Issue by sdake** [istio/istio#18151]
**Bug description**

The operator is not starting a proxy for pilot.  The last I was aware, this was mandatory:
```
sdake@beast-01:~/go/src/istio.io/istio/install/kubernetes$ kubectl get pods -n istio-system
NAME                                      READY   STATUS    RESTARTS   AGE
grafana-6b58d744b6-v4g27                  1/1     Running   0          4m43s
istio-citadel-6d5c9c8df4-dzb8g            1/1     Running   0          4m48s
istio-egressgateway-784f667bc-gcv2b       1/1     Running   0          4m43s
istio-galley-789b56cb8c-ngxts             1/1     Running   0          4m44s
istio-ingressgateway-7c9d5fbf7-chgrw      1/1     Running   0          4m44s
istio-pilot-75464cd868-j98c8              1/1     Running   0          4m43s
istio-policy-65d79d9996-8qh68             1/1     Running   2          4m41s
istio-sidecar-injector-848c5bc79c-296gn   1/1     Running   0          4m46s
istio-telemetry-6577b95c6b-pzv5k          1/1     Running   1          4m38s
istio-tracing-86cc56bcd4-2khcs            1/1     Running   0          4m51s
kiali-567b6cbfdb-bfxms                    1/1     Running   0          4m46s
prometheus-7c84fcfc59-c2pqj               1/1     Running   0          4m43s
```

**Expected behavior**
Istio installs pilot.

**Steps to reproduce the bug**
```
from `$ISTIO/operator` directory:

```
kubectl apply -k deploy
kubectl apply -f deploy/crds/istio_v1alpha2_istiocontrolplane_cr.yaml
```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
master

**How was Istio installed?**
See above for reproducer.

**Environment where bug was observed (cloud vendor, OS, etc)**
bare metal K8s + metallb for load balancer

**Comment by linsun** [comment]
i noticed this too, and nost just the controller side operator, but also istioctl.

Is this intended?  Does this mean the control plane dashboard will be broken?

**Comment by linsun** [comment]
it is for pilot and policy and telemetry pods, all without sidecar

**Comment by sdake** [comment]
If this breaks control telemetry this is a release blocker as this would be a regression (The implementation change is not operator-specific, but throughout the old and new installers).  At this point, we have been operating under the assumption that the sidecar was only needed for control plane security.

This needs verification that control plane telemetry is not impacted.

**Comment by sdake** [comment]
Reports from @linsun indicate that control plane telemetry is not impacted.
