### ISSUE TITLE
the istioctl binary is tagged as `osx` while uname lists `darwin`

### ISSUE THREAD

**Issue by sdake** [istio/istio#18154]
**Bug description**

IMO the binaries should match the operating system uname.  on Linux - this is `linux` on OSX this is `darwin`. The images are currently named `osx` which makes executing a simple curl operation difficult for those that don't like to run magic install-everything shell scripts that require root from the internet...

**Expected behavior**
https://gcsweb.istio.io/gcs/istio-prerelease/prerelease/1.4.0-alpha.0

those images should be named istioctl-${GOOS}_${GOARCH}.tar.gz - not some other derived form of these platforms.  This is consistent with nearly every other project release process in the cloud native landscape.

Cheers
-steve

**Comment by esnible** [comment]
@sdake Go itself https://golang.org/dl/ does `<project><version>.<os>-<arch>.<compressor>`.

- Is there a name for the convention?  I didn't know what to call this convention and couldn't figure out how to search for best practices.
- You request `<project>-<os>-<arch>.tar.gz` which is slightly different than what Go itself uses.
- Does anyone know how to test `istioctl` on a non-OSX Darwin?  It would be a pity if we went to all this work and then discovered we call some OSX-specific API.

**Comment by sdake** [comment]
@esnible 
- I am not aware of a name for this convention, but I think you will be hard-pressed to find `osx` in the majority of darwin binary naming conventions.
- I think golang has it right by including the version (my original request was incomplete).
- Is there such a thing as a non-osx darwin?
- I am not sure we have any ci around our darwin binaries at this time.
-
