### ISSUE TITLE
TestConformance/k8s/ingress/merge/0 codecov tes

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#18165]
This is failing 100% of the time it seems:

* https://prow.istio.io/view/gcs/istio-prow/logs/codecov_istio_postsubmit/446
* https://prow.istio.io/view/gcs/istio-prow/logs/codecov_istio_postsubmit/445

**Comment by jasonwzm** [comment]
Not seeing the test failing since 10/28. https://k8s-testgrid.appspot.com/istio_istio_postsubmit#codecov_istio_postsubmit

Closing the issue.
