### ISSUE TITLE
istio-mesh metrics data was  partly lost 

### ISSUE THREAD

**Issue by zhangxingdeppon** [istio/istio#18161]
**Bug description**
Hi,buddies,I faced a problem about istio-mesh,when I  get the metric "istio_requests_total" data through prometheus  ,I found that the metric’s data sometimes can be lost over a period of time,
I use this  promQL to search the metric's data:
<pre><code>
istio_requests_total{reporter="source",destination_service=~"idcardocr-xl8meey0-serving.aipaas-modelserving.svc.cluster.local"}
</code></pre>
it will return many metric data,so I just paste the key part:
![image](https://user-images.githubusercontent.com/16789841/67348158-a2ee8f00-f576-11e9-95c2-2c893f1c6b8c.png)

In this picture ,you will find the exception datas in red box,there are two problems:
firstly,the istio_requests_total number 500 straight down to 1,I thinks the number should constantly increase, the number at 1571377638.89 (2019/10/17 16:41:48 ) must large than 500  at 1571301708.89 (2019/10/18 13:47:18),but not.

secondly, between  1571377638.89 (2019/10/17 16:41:48 ) and  1571377638.89 (2019/10/17 16:41:48 ),there is no metric data to capture,so the metrics data was partly lost.
it is important for me,can you give me some ideas?I'm pleasure to provide more details if need.thanks.
**Expected behavior**
I hope I can found the all data through prometheus,tks.
**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
<pre><code>
[root@D21114U24-61-149 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
</code></pre>
<pre><code>
[root@D21114U24-61-149 bin]# ./istioctl version
client version: 1.2.2
citadel version: 1.2.2
egressgateway version: 1.2.2
galley version: 1.2.2
ingressgateway version: 1.2.2
pilot version: 1.2.2
policy version: 1.2.2
sidecar-injector version: 1.2.2
telemetry version: 1.2.2
</code></pre>
**How was Istio installed?**
Customizable Install with Helm
**Environment where bug was observed (cloud vendor, OS, etc)**
In our private enviroment
<pre><code>
[root@D21114U24-61-149 bin]# uname -a
Linux D21114U24-61-149 3.10.0-693.el7.x86_64 #1 SMP Thu Jul 6 19:56:57 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux
</code></pre>

**Comment by howardjohn** [comment]
See https://github.com/istio/istio/issues/12567

**Comment by zhangxingdeppon** [comment]
> See #12567

@howardjohn thanks,but it's not same,because 

> See #12567

@howardjohn thanks,but it's diffirent，#12567 is about prometheus.retention problem,but my problem is data lost and data exception,maybe I  describe it unclearly, so I redescribe it, thanks.

**Comment by zhangxingdeppon** [comment]
@howardjohn hi,dear,i find some new information about this problem , maybe it's a key to resolve our probelem,in other words,  the istio-mesh metric url  is “http://10.222.0.90:42422/metrics” that prometheus target is istio-mesh ,you can look at the below picture: 
![image](https://user-images.githubusercontent.com/16789841/67750316-ef036d00-fa69-11e9-9788-e79ea5779a05.png)

when I access it, it’s response code is 200,but not any data,"Content-Length: 0"，but sometimes you can get the metric and return the correct metric information,so how does the metric work?I have no idea,thanks。
<pre><code>
[logview@D21015U04-62-99 ~]$ curl http://10.222.187.132:42422/metrics  -iv
* About to connect() to 10.222.187.132 port 42422 (#0)
*   Trying 10.222.187.132...
* Connected to 10.222.187.132 (10.222.187.132) port 42422 (#0)
> GET /metrics HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 10.222.187.132:42422
> Accept: */*
> 
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Content-Type: text/plain; version=0.0.4; charset=utf-8
Content-Type: text/plain; version=0.0.4; charset=utf-8
< Date: Tue, 29 Oct 2019 08:18:10 GMT
Date: Tue, 29 Oct 2019 08:18:10 GMT
< Content-Length: 0
Content-Length: 0
</code></pre>

**Comment by zhangxingdeppon** [comment]
@bianpengyuan I carefully checked the log and status,but no useful information to be found,I just found some gc operation in mixer log ,did the gc  cause it ?I have uploaded the relevant logs, maybe you can confirm it,if need,I'm pleasure to provide more details ,thanks.
the status:
<pre><code>
[root@D21112U04-61-142 ~]#  kubectl describe pod istio-telemetry-66d5594d99-z6nhn  -n istio-system 
Name:               istio-telemetry-66d5594d99-z6nhn
Namespace:          istio-system
Priority:           0
PriorityClassName:  <none>
Node:               d21012u11-62-94/172.29.62.94
Start Time:         Thu, 05 Sep 2019 16:46:50 +0800
Labels:             app=telemetry
                    chart=mixer
                    heritage=Tiller
                    istio=mixer
                    istio-mixer-type=telemetry
                    pod-template-hash=66d5594d99
                    release=istio
Annotations:        sidecar.istio.io/inject: false
Status:             Running
IP:                 10.222.187.132
Controlled By:      ReplicaSet/istio-telemetry-66d5594d99
Containers:
  mixer:
    Container ID:  docker://37ca75102741b671e3426371868508c47fda2fe8866814927a3ae587075a6a3d
    Image:         172.29.62.9:8080/istio/mixer:1.2.2
    Image ID:      docker-pullable://172.29.62.9:8080/istio/mixer@sha256:886726967363477eeba4cbf48675b058bcf833c932763b0964db80390fc06ceb
    Ports:         15014/TCP, 42422/TCP
    Host Ports:    0/TCP, 0/TCP
    Args:
      --monitoringPort=15014
      --address
      unix:///sock/mixer.socket
      --log_output_level=default:info
      --configStoreURL=mcp://istio-galley.istio-system.svc:9901
      --configDefaultNamespace=istio-system
      --useAdapterCRDs=false
      --useTemplateCRDs=false
      --trace_zipkin_url=http://zipkin.istio-system:9411/api/v1/spans
      --averageLatencyThreshold
      100ms
      --loadsheddingMode
      enforce
    State:          Running
      Started:      Thu, 05 Sep 2019 16:46:52 +0800
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     4800m
      memory:  4G
    Requests:
      cpu:     1
      memory:  1G
    Liveness:  http-get http://:15014/version delay=5s timeout=1s period=5s #success=1 #failure=3
    Environment:
      GODEBUG:     gctrace=1
      GOMAXPROCS:  6
    Mounts:
      /etc/certs from istio-certs (ro)
      /sock from uds-socket (rw)
      /var/run/secrets/istio.io/telemetry/adapter from telemetry-adapter-secret (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from istio-mixer-service-account-token-jxc2d (ro)
  istio-proxy:
    Container ID:  docker://04fda1c76ee41d3118822c638f6c49b0e1c461b8ea438fda10f0310da371f6b7
    Image:         172.29.62.9:8080/istio/proxyv2:1.2.2
    Image ID:      docker-pullable://172.29.62.9:8080/istio/proxyv2@sha256:236527816ff67f8492d7286775e09c28e207aee2f6f3c3d9258cd2248af4afa5
    Ports:         9091/TCP, 15004/TCP, 15090/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP
    Args:
      proxy
      --domain
      $(POD_NAMESPACE).svc.cluster.local
      --serviceCluster
      istio-telemetry
      --templateFile
      /etc/istio/proxy/envoy_telemetry.yaml.tmpl
      --controlPlaneAuthPolicy
      NONE
    State:          Running
      Started:      Thu, 05 Sep 2019 16:46:53 +0800
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     2
      memory:  1Gi
    Requests:
      cpu:     100m
      memory:  128Mi
    Environment:
      POD_NAME:       istio-telemetry-66d5594d99-z6nhn (v1:metadata.name)
      POD_NAMESPACE:  istio-system (v1:metadata.namespace)
      INSTANCE_IP:     (v1:status.podIP)
    Mounts:
      /etc/certs from istio-certs (ro)
      /sock from uds-socket (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from istio-mixer-service-account-token-jxc2d (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  istio-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  istio.istio-mixer-service-account
    Optional:    true
  uds-socket:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:  
  telemetry-adapter-secret:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  telemetry-adapter-secret
    Optional:    true
  istio-mixer-service-account-token-jxc2d:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  istio-mixer-service-account-token-jxc2d
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  node=worker
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>
</code></pre>
the log:
[istio-telemetry-mixer.log](https://github.com/istio/istio/files/3787148/istio-telemetry-mixer.log)
[istio-telemetry-proxy.log](https://github.com/istio/istio/files/3787149/istio-telemetry-proxy.log)

**Comment by bianpengyuan** [comment]
gc logs are expected and telemetry pod looks like working fine. Please follow https://archive.istio.io/v1.2/docs/ops/telemetry/missing-metrics/ to check if everything is normal.

**Comment by zhangxingdeppon** [comment]
@bianpengyuan I follow https://archive.istio.io/v1.2/docs/ops/telemetry/missing-metrics/ to check it,but still don't get any userful informations.
according to the above article ,I checked the information below：

Firstly，Verify Mixer is receiving Report calls
<pre><code>
[logview@D21015U04-62-99 ~]$ curl 10.222.187.132:15014/metrics |grep grpc_io_server_completed_rpcs
# HELP grpc_io_server_completed_rpcs Count of RPCs by method and status.
# TYPE grpc_io_server_completed_rpcs counter
grpc_io_server_completed_rpcs{grpc_server_method="istio.mixer.v1.Mixer/Report",grpc_server_status="OK"} 816240
</code></pre>
so I know Envoy is truely calling Mixer to report telemetry.

Secondly,Verify the Mixer rules exist
<pre><code>
[root@D21117U10-62-66 ~]# kubectl get rules --all-namespaces
NAMESPACE      NAME                      AGE
istio-system   kubeattrgenrulerule       56d
istio-system   promhttp                  56d
istio-system   promtcp                   56d
istio-system   promtcpconnectionclosed   56d
istio-system   promtcpconnectionopen     56d
istio-system   tcpkubeattrgenrulerule    56d
</code></pre>
the output also shows rules named promhttp or promtcp.

Thirdly,Verify the Prometheus handler configuration exists
<pre><code>
[root@D21117U10-62-66 ~]# kubectl get handlers.config.istio.io --all-namespaces
NAMESPACE      NAME            AGE
istio-system   kubernetesenv   56d
istio-system   prometheus      56d
</code></pre>
the output also shows configured metric instances,it's normal.

Forthly,Verify there are no known configuration errors
<pre><code>
[logview@D21015U04-62-99 ~]$ curl 10.222.187.132:15014/metrics |egrep "mixer_config_adapter_info_config_errors_total|mixer_config_template_config_errors_total|mixer_config_instance_config_errors_total|mixer_config_rule_config_errors_total|mixer_config_rule_config_match_error_total|mixer_config_unsatisfied_action_handler_total|mixer_config_handler_validation_error_total|mixer_handler_handler_build_failures_total"

# HELP mixer_config_adapter_info_config_errors_total The number of errors encountered during processing of the adapter info configuration.
# TYPE mixer_config_adapter_info_config_errors_total gauge
mixer_config_adapter_info_config_errors_total 0
# HELP mixer_config_handler_validation_error_total The number of errors encountered because handler validation returned error.
# TYPE mixer_config_handler_validation_error_total gauge
mixer_config_handler_validation_error_total 0
# HELP mixer_config_instance_config_errors_total The number of errors encountered during processing of the instance configuration.
# TYPE mixer_config_instance_config_errors_total gauge
mixer_config_instance_config_errors_total 0
# HELP mixer_config_rule_config_errors_total The number of errors encountered during processing of the rule configuration.
# TYPE mixer_config_rule_config_errors_total gauge
mixer_config_rule_config_errors_total 0
# HELP mixer_config_rule_config_match_error_total The number of rule conditions that was not parseable.
# TYPE mixer_config_rule_config_match_error_total gauge
mixer_config_rule_config_match_error_total 0
# HELP mixer_config_template_config_errors_total The number of errors encountered during processing of the template configuration.
# TYPE mixer_config_template_config_errors_total gauge
mixer_config_template_config_errors_total 0
# HELP mixer_config_unsatisfied_action_handler_total The number of actions that failed due to handlers being unavailable.
# TYPE mixer_config_unsatisfied_action_handler_total gauge
mixer_config_unsatisfied_action_handler_total 0
# HELP mixer_handler_handler_build_failures_total The number of handlers that failed creation during config transition.
# TYPE mixer_handler_handler_build_failures_total gauge
mixer_handler_handler_build_failures_total 0
</code></pre>
confirm that the metric value with the largest configuration ID is 0, so it's normal.

Fifthly,Verify Mixer is sending metric instances to the Prometheus adapter.
<pre><code>
[logview@D21015U04-62-99 ~]$ curl 10.222.187.132:15014/metrics |egrep "mixer_runtime_dispatches_total"
# HELP mixer_runtime_dispatches_total Total number of adapter dispatches handled by Mixer.
# TYPE mixer_runtime_dispatches_total counter
mixer_runtime_dispatches_total{adapter="kubernetesenv",error="false",handler="kubernetesenv.istio-system",meshFunction="kubernetes"} 1.3705212e+07
mixer_runtime_dispatches_total{adapter="prometheus",error="false",handler="prometheus.istio-system",meshFunction="metric"} 816240
</code></pre>

I can find recorded dispatches to the Prometheus adapter,so there isn't  any configuration issue.

Finally,Verify Prometheus configuration
![image](https://user-images.githubusercontent.com/16789841/67939434-7f79b300-fc0c-11e9-845e-82dbd9dd32c4.png)

<pre><code>
[logview@D21015U04-62-99 ~]$ curl 10.222.250.172:9090/config|grep istio-mesh -A20
 --:--  scrape_interval: 15s
:  scrape_timeout: 10s
-  metrics_path: /metrics
-  scheme: http
   kubernetes_sd_configs:
-  - role: endpoints
-    namespaces:
:      names:
-      - istio-system
-  relabel_configs:
:  - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
-    separator: ;
-    regex: istio-telemetry;prometheus
     replacement: $1
6    action: keep

</code></pre>
 the target and config are also okay.
through the above information, no more valuable information was found,Is there a problem with my operation?thanks.

**Comment by zhangxingdeppon** [comment]
How can I verify the sidecar "envoy" after each request to report telemetry succeed?
In addition,when I access metric "istio-mesh", it’s always response code is 200,but  sometimes not any data,the data length is 0,"Content-Length: 0"，I think if the response code 200 was returned,the result must be return,but it return ""Content-Length: 0",so I feel very confused.

**Comment by bianpengyuan** [comment]
The output from debug steps looking fine to me. Based on the output from the first step indicates, Mixer is receiving reports from the proxy.

Could you try to turn on adapters debug log (add `--log_output_level=adapters:debug` to `istio-telemetry` deployment) and check if there is anything fishy in output?

**Comment by zhangxingdeppon** [comment]
I added the parameter `--log_output_level=adapters:debug`,  but no error messages was found, anyway I find a strange phenomenon，maybe it's key, if service mesh gateway has no traffic  coming in for a period of time ,the  `istio_requests_total` metric statistic  will reset to 0 and response "Content-Length: 0", but as long as the request is coming in , this `istio_requests_total`  metric statistic will restart the calculation, Is there a configuration for this in `istio-telemetry` code? is it right?

**Comment by bianpengyuan** [comment]
This does not sounds right to me. `istio-telemetry` pod should retain all stats collected over its life time. Did your telemetry pod restart during the time when there was no traffic?

**Comment by zhangxingdeppon** [comment]
yes, I also agree, but that event is very strange,and verified the telemetry pod didn't restart during the time , so  I added `--log_output_level=default:debug,adapters:debug,api:debug,attributes:debug,grpcAdapter:debug`, but no any userful message found, you can verify the result,
[istio-telemetry-20191105.log](https://github.com/istio/istio/files/3807799/istio-telemetry-20191105.log)


![image](https://user-images.githubusercontent.com/16789841/68187861-c1c33b80-ffe2-11e9-8f2a-c02b00fc20f2.png)
 In above picture,our application "flaskapp" in istio-mesh, you will find  scraping the metric  return null after `07:15`.,this is GMT time, translate to machine time，it need to add 8 hours, `15:15`

through  curl to verify the result, it returned null:
<pre><code>
[root@ecs-5274-0318501 ~]# curl 10.222.0.143:42422/metrics -iv
* About to connect() to 10.222.0.143 port 42422 (#0)
*   Trying 10.222.0.143...
* Connected to 10.222.0.143 (10.222.0.143) port 42422 (#0)
> GET /metrics HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 10.222.0.143:42422
> Accept: */*
> 
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Content-Type: text/plain; version=0.0.4; charset=utf-8
Content-Type: text/plain; version=0.0.4; charset=utf-8
< Date: Tue, 05 Nov 2019 07:47:27 GMT
Date: Tue, 05 Nov 2019 07:47:27 GMT
< Content-Length: 0
Content-Length: 0

< 
* Connection #0 to host 10.222.0.143 left intact
You have new mail in /var/spool/mail/root
</code></pre>

and verify if the telemetry pod was restarted, form `kubectl describe`, we known  the telemetry pod wasn't  restarted during the time,

<pre><code>
[root@ecs-5274-0318501 ~]# kubectl describe pod istio-telemetry-6d495b7f9f-wtn88  -n istio-system 
Name:               istio-telemetry-6d495b7f9f-wtn88
Namespace:          istio-system
Priority:           0
PriorityClassName:  <none>
Node:               ecs-5274-0318501.novalocal/172.16.1.123
Start Time:         Tue, 05 Nov 2019 14:35:33 +0800
Labels:             app=telemetry
                    chart=mixer
                    heritage=Tiller
                    istio=mixer
                    istio-mixer-type=telemetry
                    pod-template-hash=6d495b7f9f
                    release=istio
Annotations:        sidecar.istio.io/inject: false
Status:             Running
IP:                 10.222.0.143
Controlled By:      ReplicaSet/istio-telemetry-6d495b7f9f
Containers:
  mixer:
    Container ID:  docker://8233a4b54cbd79e373f8314b0e405f66f71ad1efc3360b871687cb970d072936
    Image:         172.16.1.222:10004/istio/mixer:1.2.2
    Image ID:      docker-pullable://172.16.1.222:10004/istio/mixer@sha256:886726967363477eeba4cbf48675b058bcf833c932763b0964db80390fc06ceb
    Ports:         15014/TCP, 42422/TCP
    Host Ports:    0/TCP, 0/TCP
    Args:
      --monitoringPort=15014
      --address
      unix:///sock/mixer.socket
      --log_output_level=default:debug,adapters:debug,api:debug,attributes:debug,grpcAdapter:debug
      --configStoreURL=mcp://istio-galley.istio-system.svc:9901
      --configDefaultNamespace=istio-system
      --useAdapterCRDs=false
      --useTemplateCRDs=false
      --trace_zipkin_url=http://zipkin.istio-system:9411/api/v1/spans
      --averageLatencyThreshold
      100ms
      --loadsheddingMode
      enforce
    State:          Running
      Started:      Tue, 05 Nov 2019 14:35:34 +0800
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     4800m
      memory:  4G
    Requests:
      cpu:     1
      memory:  1G
    Liveness:  http-get http://:15014/version delay=5s timeout=1s period=5s #success=1 #failure=3
    Environment:
      GODEBUG:     gctrace=1
      GOMAXPROCS:  6
    Mounts:
      /etc/certs from istio-certs (ro)
      /sock from uds-socket (rw)
      /var/run/secrets/istio.io/telemetry/adapter from telemetry-adapter-secret (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from istio-mixer-service-account-token-g55ct (ro)
  istio-proxy:
    Container ID:  docker://b0f50b7a753b8b09b158b6be708cbb9d0e2a93f173e68e7078cfdb6af19fd1ff
    Image:         172.16.1.222:10004/istio/proxyv2:1.2.2
    Image ID:      docker-pullable://172.16.1.222:10004/istio/istio/proxyv2@sha256:236527816ff67f8492d7286775e09c28e207aee2f6f3c3d9258cd2248af4afa5
    Ports:         9091/TCP, 15004/TCP, 15090/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP
    Args:
      proxy
      --domain
      $(POD_NAMESPACE).svc.cluster.local
      --serviceCluster
      istio-telemetry
      --templateFile
      /etc/istio/proxy/envoy_telemetry.yaml.tmpl
      --controlPlaneAuthPolicy
      NONE
    State:          Running
      Started:      Tue, 05 Nov 2019 14:35:34 +0800
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     2
      memory:  1Gi
    Requests:
      cpu:     100m
      memory:  128Mi
    Environment:
      POD_NAME:       istio-telemetry-6d495b7f9f-wtn88 (v1:metadata.name)
      POD_NAMESPACE:  istio-system (v1:metadata.namespace)
      INSTANCE_IP:     (v1:status.podIP)
    Mounts:
      /etc/certs from istio-certs (ro)
      /sock from uds-socket (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from istio-mixer-service-account-token-g55ct (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  istio-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  istio.istio-mixer-service-account
    Optional:    true
  uds-socket:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  telemetry-adapter-secret:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  telemetry-adapter-secret
    Optional:    true
  istio-mixer-service-account-token-g55ct:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  istio-mixer-service-account-token-g55ct
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>
You have new mail in /var/spool/mail/roo
</code></pre>

**Comment by zhangxingdeppon** [comment]
@bianpengyuan is there any other mothed to diagnose it? it's so strange, I have  a try to `tcpdump` in istio-telemetry pod,  but no more details i can find.

**Comment by bianpengyuan** [comment]
Do you have any change set the metrics expiry policy in prometheus handler? https://github.com/istio/istio/blob/9bf2abbba7bddbb03d8b4e344b15008dba04baaf/mixer/adapter/prometheus/config/config.proto#L170-L180

**Comment by zhangxingdeppon** [comment]
I didn't change the metrics expiry policy, I see the default value is `10m`, so I set it to `168h`, I will verify the operation if it reslove the problem, waiting for me reply the result later, thanks you very much.

**Comment by zhangxingdeppon** [comment]
@bianpengyuan excellent, this method is okay, change the `metrics expiry policy` to a longer time , that have resloved my problem, I can see the all istio-mesh metrics's data now,  thank you very much.
