### ISSUE TITLE
Helm Charts don't work with helm 2.15.0

### ISSUE THREAD

**Issue by kkunkel** [istio/istio#18172]
**Bug description**

helm 2.15.0 fails to properly enumerate `.Values.global.arch` in `_affinity.tpl` when the values are integers. This results in deployments missing key elements and values for deployments, for example: 
```$ tail istio/charts/galley/templates/deployment.yaml 
          name: istio
      affinity:      
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
          preferredDuringSchedulingIgnoredDuringExecution:  
```
Quoting the values in `values.yaml` like 
```  # Specify pod scheduling arch(amd64, ppc64le, s390x) and weight as follows:
  #   0 - Never scheduled
  #   1 - Least preferred
  #   2 - No preference
  #   3 - Most preferred
  arch:
    amd64: "3"
    s390x: "2"
    ppc64le: "2"
```
produces the desired yaml.

**Expected behavior**

Istio helm charts should produce useable charts with the latest stable Helm version (2.15.0)

**Steps to reproduce the bug**
```helm repo add istio https://storage.googleapis.com/istio-release/releases/1.3.3/charts/
helm fetch --untar --untardir charts istio/istio
helm template charts/istio --namespace istio-system  --output-dir  .
```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```Istio 1.3.3
$ kubectl version --client=true
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
$ helm version
Client: &version.Version{SemVer:"v2.15.0", GitCommit:"c2440264ca6c078a06e088a838b0476d2fc14750", GitTreeState:"clean"}
```
**How was Istio installed?**
This is an installation error with the Helm charts.

**Environment where bug was observed (cloud vendor, OS, etc)**
This is pre-deployment.

**Comment by howardjohn** [comment]
It is a bug in helm 2.15, workaround in  https://github.com/istio/istio/pull/18170.
