### ISSUE TITLE
Operator needs to be update in go.mod of istio/istio

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#18173]
There were a few changes, some which are already documented, that need to be pulled in. This mostly applies to release-1.4, but master should be synced as well.

When we pull these in, we will need to update the gobuild.sh to pass the correct LDFLAGS to set the hub and tag variable. This may require updating common-files first

**Comment by elfinhe** [comment]
For example, when updating operator deps in istio/istio for 1.4:

(...checkout release-1.4 branch in istio/istio before running this)
```
GO111MODULE=on go get istio.io/operator@release-1.4; GO111MODULE=on go mod tidy ; GO111MODULE=on go mod vendor
```
Update Makefile.core.mk (?):

OP_LDFLAGS_HUB="-X istio.io/operator/cmd/mesh.HubValueFromBuild=${HUB}"
OP_LDFLAGS_TAG="-X istio.io/operator/cmd/mesh.TagValueFromBuild=${TAG_VARIANT}"

RELEASE_LDFLAGS="-extldflags -static -s -w ${OP_LDFLAGS_HUB} ${OP_LDFLAGS_TAG}"
DEBUG_LDFLAGS="-extldflags -static ${OP_LDFLAGS_HUB} ${OP_LDFLAGS_TAG}"

**Comment by carolynhu** [comment]
I have back ported to release 1.4.
