### ISSUE TITLE
Istio + nginx

### ISSUE THREAD

**Issue by kotyara85** [istio/istio#18176]
Hello everyone,
Our networking diagram is:
LB -> nginx ingress controllers -> istio sidecar -> service

Istio is 1.1.7, mtls enabled.

Web services are up and running, I can hit the endpoints within istio-proxy container but not outside.

Is there a way to make it work with nginx?

Tried to add this 
```
      annotations:
        traffic.sidecar.istio.io/includeInboundPorts: ""
```

to ingress, but doesn't work.

Thanks

**Comment by howardjohn** [comment]
What errors are you getting? What config have you applied? Strict mTLS or permissive?

**Comment by kotyara85** [comment]
```
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>openresty/1.15.8.1</center>
</body>
</html>
```

**Comment by kotyara85** [comment]
The same problem with kubeless - it's up but throwing connection errors:
```
$ kubeless function call hello --data 'Hello world!'
ERRO[0000] Error: 'read tcp 172.17.0.1:35018->172.17.0.19:8080: read: connection reset by peer'
Trying to reach: 'http://172.17.0.19:8080/'
```

**Comment by howardjohn** [comment]
Can you give a reproducible config? and a config dump for one of the clients having issues: https://github.com/istio/istio/wiki/Troubleshooting-Istio

Please also turn on access logging and get the logs from Envoy, it has useful info about the request

**Comment by howardjohn** [comment]
Closing as this issue is for an unsupported and require info to debug is missing. Please open a new issue if you see more issues. Thanks!

**Comment by robincher** [comment]
Hi @howardjohn i have a similar issue, should i open a Github issue here and filed in under Bug Report?

Or for general questions should i post this in istio forum instead (which i did)
https://discuss.istio.io/t/nginx-ingress-controller-with-istio-mtls/7076
