### ISSUE TITLE
What can cause pilot-discovery to fail on startup

### ISSUE THREAD

**Issue by vsaroopchand** [istio/istio#18182]
Hello, can someone explain what is listening on endpoint localhost:15014 in Pilot? In my cluster, pilot-discovery is failing with a timeout when attempting to connect on [127.0.0.1:15014](https://github.com/istio/istio/blob/4c98e70fc4bdbcc3dfdd5c5527a48cb5a4f4f047/pilot/cmd/pilot-discovery/request.go#L32).

Here is the exception:

Error&#58; error execing into istio-pilot-00cb85f969-abeee/istio-system discovery container&#58; command terminated with exit code 255
gc 1 @0.012s 2%&#58; 0.020+2.2+0.21 ms clock, 0.16+0.34/1.0/0.12+1.7 ms cpu, 4-&gt;4-&gt;1 MB, 5 MB goal, 8 P
gc 2 @0.022s 3%&#58; 0.011+1.0+0.14 ms clock, 0.089+0.40/1.4/1.5+1.1 ms cpu, 4-&gt;4-&gt;2 MB, 5 MB goal, 8 P
Error&#58; **Get http&#58;//127.0.0.1&#58;15014/debug/syncz&#58; dial tcp 127.0.0.1&#58;15014&#58; i/o timeout**

This error is also present:
Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 0 successful, 0 rejected; lds updates: 0 successful, 0 rejected

**Comment by vsaroopchand** [comment]
[](url)

**Comment by howardjohn** [comment]
It seems likely this is from `istioctl ps`, not sure anything else that calls /debug/syncz. This is blocking pilot startup? Please include more info, its not clear what the issue is

**Comment by vsaroopchand** [comment]
I'll close this for now and revisit once I have more logs to share.
