### ISSUE TITLE
Error: release istio failed - AKS, Istio, Helm

### ISSUE THREAD

**Issue by Patrux08** [istio/istio#18186]
**Bug description**
Following [Azure's tutorial](https://docs.microsoft.com/en-us/azure/aks/servicemesh-istio-install?pivots=client-operating-system-windows), at **Install Istio components** you have to run

`helm install istio.io/istio --name istio --namespace istio-system --version "1.3.2" 
  --set global.controlPlaneSecurityEnabled=true 
  --set global.mtls.enabled=true 
  --set grafana.enabled=true --set grafana.security.enabled=true 
  --set tracing.enabled=true 
  --set kiali.enabled=true 
  --set global.defaultNodeSelector."beta\.kubernetes\.io/os"=linux`

**Expected behavior** is to deploy some objects, but what I get instead is this error:
`Error: release istio failed: Deployment.apps "istio-galley" is invalid: spec.template.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].values: Required value: must be specified when `operator` is 'In' or 'NotIn'`

I tried purging istio with helm del --purge istio and re-deploy, but the error is always the same BUT "istio-galley" changes. I collected 4 different errors showing "istio-pilot", "galley", "kiali" and "grafana". It seems random.

I've tryed using **Istio** 1.3.2 and 1.3.3 as well as **Helm** 2.15, 2.14.3 and now 2.13.1. 
Kubectl client is 1.14.6 and server 1.13.11

OS is Windows 10, trying to deploy istio on AKS (Azure Kubernetes)

**Comment by howardjohn** [comment]
Helm 2.15 is broken, see https://github.com/istio/istio/pull/18170

**Comment by howardjohn** [comment]
This is not an Istio bug, but a helm one. They will release 2.15.1 soon with a patch apparently. Until then I would suggest downgrading helm

**Comment by mabushey** [comment]
Use the Bonzai operator and get away from Helm.
