### ISSUE TITLE
could not resolve host while installing specific istio version

### ISSUE THREAD

**Issue by rnkhouse** [istio/istio#18184]
**Bug description**
I am trying to install istio with `curl -L https://git.io/getLatestIstio | ISTIO_VERSION=1.3.3 sh -` but getting below error:

>curl: (6) Could not resolve host: github-production-release-asset-2e65be.s3.amazonaws.com

**Expected behavior**
It should download specific version of istio.

**Comment by howardjohn** [comment]
Works for me, is this persistent or cause by temporary github issue?

**Comment by rnkhouse** [comment]
Looks like it's not working on my Jenkins instance. However, it was working before.

*Logs*

    16:15:25  + curl -L https://git.io/getLatestIstio
    16:15:25  + ISTIO_VERSION=1.2.6 sh -
    16:15:25    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
    16:15:25                                   Dload  Upload   Total   Spent    Left  Speed
    16:15:25  
    0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
    0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
    16:15:25  
    100  2802  100  2802    0     0   5053      0 --:--:-- --:--:-- --:--:--  5053
    16:15:25  Downloading istio-1.2.6 from https://github.com/istio/istio/releases/download/1.2.6/istio-1.2.6-linux.tar.gz ...  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
    16:15:25                                   Dload  Upload   Total   Spent    Left  Speed
    16:15:25  
    0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
    0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
    100   614    0   614    0     0   1600      0 --:--:-- --:--:-- --:--:--  1598
    16:15:41  
    0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:00:06 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:00:07 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:00:08 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:00:09 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:00:11 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:00:12 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:00:13 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:00:14 --:--:--     0curl: (6) Could not resolve host: github-production-release-asset-2e65be.s3.amazonaws.com
    16:15:41  
    16:15:41  gzip: stdin: unexpected end of file
    16:15:41  tar: Child returned status 1
    16:15:41  tar: Error is not recoverable: exiting now
    16:15:41  Istio 1.2.6 Download Complete!

**Comment by howardjohn** [comment]
Interesting. I don't think we have any control over this though, seems like an issue with one of your jenkins/aws/github? The script is just failing to download the release from github it looks like

**Comment by rnkhouse** [comment]
@howardjohn I can understand that. Can you please try it from linux OS? It's working from my mac but not working from any ubuntu OS.

**Comment by howardjohn** [comment]
Works from Debian for me

**Comment by howardjohn** [comment]
https://twitter.com/AWSSupport/status/1186735657387003904
