### ISSUE TITLE
Configurable total destination weight limit.

### ISSUE THREAD

**Issue by prabhu-mannu** [istio/istio#18213]
**Describe the feature request**

> In essence, would like to remove the current total destination weight limit 100

We are using destination weight for canary release.  currently, istio only support a weight limit of 0-100, but  In light of weight limit being removed from the envoy (initially it was 128 ) 

> - https://www.envoyproxy.io/docs/envoy/v1.11.0/intro/version_history
> - https://github.com/envoyproxy/envoy/pull/7437

Consider removing the limit or make it configurable, would allow more fine-grained control over the canary release, allowing for a limit of 0-1000, would allow for 0.1 %  (theoretically 1 in 1000 Request) ( limit split as 1 and 999).
Currently, the pilot validation is what stopping from achieving this, as the number 100 is hardcoded.  Making this parameter as configurable during installation would allow maintaining backwards compatibility and also allow for finer canary release control.

> - https://github.com/istio/istio/blob/8ece9bfa6161b2ec8fc0712f000bcb8ba71ef468/pkg/config/validation/validation.go#L2099
> - https://github.com/istio/istio/blob/8ece9bfa6161b2ec8fc0712f000bcb8ba71ef468/pkg/config/validation/validation.go#L2083

**Describe alternatives you've considered**

**Additional context**

**Comment by howardjohn** [comment]
I think it would be better to change this to a float or something and keep the limit at 100. Having a separate configurable limit is going to be a horrible UX

**Comment by prabhu-mannu** [comment]
Hi, Howard, 
That would absolutely work too.  
It was choice between changing the value from int to float vs changing the limit (in this case increasing the limit over 100 or below 100). Should I create a new ticket with request to use float instead of int32 for weights. 



Note: values need to be in int32 for envoy.

**Comment by howardjohn** [comment]
I think we could just use floats, then in pilot send these as an Int to
envoy. So we would take 33.333 and turn that to 33333 with "total weight"
of 100000. The only problem is we may have float rounding issues I guess

**Comment by prabhu-mannu** [comment]
hi, 
As for using floats, yes there might be an issue. 
This happened in traefik  -> https://github.com/containous/traefik/issues/5595

According to envoy documentation, Envoy does not really care about weights summing up to 100:
https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/load_balancers
> all weights not equal: If two or more hosts in the cluster have different load balancing weights, the load balancer shifts into a mode where it uses a weighted round robin schedule in which weights are dynamically adjusted based on the host’s request load at the time of selection (weight is divided by the current active request count. For example, a host with weight 2 and an active request count of 4 will have a synthetic weight of 2 / 4 = 0.5). This algorithm provides good balance at steady state but may not adapt to load imbalance as quickly. Additionally, unlike P2C, a host will never truly drain, though it will receive fewer requests over time.


So Istio needs to allow use cases where total weight sums up to 99.99 or something similar to address the rounding up problem.
I believe supporting one decimal point would be enough for most use cases, also having a total weight of 100000 may also cause performance issues.

**Comment by ryan4yin** [comment]
configurable weight_total is useful, we need a more fine-grained control over the canary release or the A/B test.
