### ISSUE TITLE
istio-ingressgateway constant 503's - helloworld example

### ISSUE THREAD

**Issue by haf-afa** [istio/istio#18225]
This may or may not be a bug, but I've spent close to 16 hours on this now, and I think I've read every post online about 503's from Istio ingress gateways ;). I think it's a bug that I fail to debug this with the available Istio tools at the very least.

In short; I've deployed the helloworld example on GKE and istio-ingressgateway is always returning 503 Service Unavailable when doing `curl http://35.228.214.214/hello -i`.

When doing `k port-forward svc/helloworld 5000` (in the `fou` namespace`, and then `$ curl http://localhost:5000/hello --silent`, I get the expected reply: `Hello version: v1, instance: helloworld-v1-7bb88866c4-t6jrr`.

I have tried to write a detailed description of the error and some of what I've done to debug it in this Stackoverflow question: https://stackoverflow.com/questions/58509666/istio-503s-between-public-gateway-and-service and on the forum and on GKE's Slack and on the K8S slack (I haven't tried twitter yet!), but no replies. `istioctl` reports A-OK on all things (that I can see), `kiali` the same. 

- I've tried with and without CNI, with and without SDS and I've tried deleting all of Istio and reinstalling it again.
- I can `curl http://localhost/hello` from **within** the istio-ingressgateway and it routes successfully to `helloworld.fou`, giving me an OK reply with the above output (like when I port-forward to it).
- I have mTLS enabled in the cluster, via `--values ./istio/helm/istio/values-istio-sds-auth.yaml` when Helm-templating.
- It worked before, but then broke.
- I see no errors in the logs, even when I put all proxies to verbose logging

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Hello world

**Steps to reproduce the bug**

See https://github.com/istio/istio/issues/18221 but point to GKE and use values-istio-sds-auth.yaml with the helloworld sample and gateway and a public static IP configured on the istio-ingressgateway service (as it's then the LoadBalancer type). Curl the IP.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

```
istioctl version --remote
client version: 1.3.3
citadel version: 1.3.3
galley version: 1.3.3
ingressgateway version: 1.3.3
nodeagent version:
nodeagent version:
nodeagent version:
nodeagent version:
nodeagent version:
pilot version: 1.3.3
policy version: 1.3.3
sidecar-injector version: 1.3.3
telemetry version: 1.3.3
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:47:22Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-gke.13", GitCommit:"acdb9a03a6dc0f7f62d7acdda75c9a9faca50fee", GitTreeState:"clean", BuildDate:"2019-09-20T23:13:58Z", GoVersion:"go1.12.9b4", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

The helm-template way from the install guide. See previous issue for Makefile that does an installation.

**Environment where bug was observed (cloud vendor, OS, etc)** GKE, 1.14

> 
Will do if you want me to.

I'm sorry if this is not a bug, but I have no idea how to understand why I'm getting 503's back. It's probably something small, but I'm really just using the samples/helloworld deployment, so I don't see how I can make a mistake with that. And I don't understand how it can work to curl from the ingress to the service, from the ingress itself, but not when the request comes from the outside. Perhaps I'm missing a debugging step, but then again, I've tried what I could find in the docs :(

Thanks for your help and understanding

**Comment by haf-afa** [comment]
Clean installation with Istio 1.2.8 also returns 503 Service Unavailable on Docker for Desktop for Hello World example.

**Comment by haf-afa** [comment]
It's about what namespaces the virtualservice, gateway and service are in, respectively!

**Comment by dumindu** [comment]
Thanks for the tip. I have put the `deployments` and `services` in separate namespaces according to the app but `virtualservice` and `gateway` in `istio-system` namespace.

So I need to move the `services` to the `istio-system` namespace as well?

**Comment by haf-afa** [comment]
I've done some experimentation with Istio 1.2.8 (since that version works to install locally), here are the results: https://gist.github.com/haf-afa/29d904cd9f7fad6aad22c481bc9c7e9e

In short: if you bring in/remove GW/VS numerous times, you corrupt Istio and you have to reset your cluster before it starts working again. No wonder I had trouble for two days, trying everything. The file called " gw-vs-in-unspecified-n-hello-in-unspecified-gateway-suffix-after-reset.txt" in the gist was after doing ALL the other variants.

This issue is MAJOR! 💣

**Comment by haf-afa** [comment]
@dumindu Since I realised I had to reset my cluster after Istio is corrupted I only did a single try; and that was with **everything** in the *default* namespace and **nothing** in the istio-system namespace.

I would prefer to be able to declare **Gateway** in *istio-system* and the remainder in **fou**, but I guess I have to work around the corruption as well, so I can try that.

**Comment by dumindu** [comment]
I saw #11131, that's why I put virtualservice and gateway in `istio-system` namespace. But I haven't use 
```
Spec:
  Gateways:
    istio-system/<gateway>
```
in VirtualService. That might be the issue. However I am not using `Kiali` and using 
- kubectl version: v1.16.0
- helm version: v2.14.3
- istio version: v1.3.3

Thanks for the tips, I'll check tomorrow and will buzz here if it's succeed 👍

**Comment by dumindu** [comment]
- deployment and service in a separate namespace 
- virtualservice and gateway in istio-system namespace.
- virtualservice having `istio-system/` prefix for `Spec: Gateways:`

But same result.

**Comment by howardjohn** [comment]
@haf-afa just want to clarify current state here: Your last attempt, with everything in the default namespace works, but you want the Gateway in istio-system, right?


I applied your setup with all default namespace, and everything worked.

Then I moved the gateway to istio-system, and it not longer works. I ran the new `istioctl analyze` tool (https://preliminary.istio.io/docs/ops/diagnostic-tools/istioctl-analyze/.) and it warned me that the virtual service referenced an unknown Gateway. I then modified the virtual service to point to `istio-system/helloworld-gateway` instead of `helloworld-gateway` and everything worked.

I then moved the VS to istio-system as well, and things broke again. `analyze` warned me that the host `helloworld` does not exist now; replacing with `helloworld.default.svc.cluster.local` fixes this

**Comment by haf-afa** [comment]
@howardjohn You mean this test? https://gist.github.com/haf-afa/29d904cd9f7fad6aad22c481bc9c7e9e#file-gw-in-is-vs-in-fou-explicit-n-hello-in-fou-txt

**Comment by howardjohn** [comment]
Thanks for the feedback @haf-afa. Some notes:

> The analyze command is insufficiently exposed in the getting started docs, so you can't expect people to understand that they should use it

The command is brand new, as far as I know its not even in istioctl 1.3 so I of course don't expect users to be using it yet. That being said, it is useful, and we intended to ramp up the docs for it as well.

> This issue is about getting the cluster into a terminal state where I had to do I reset to make it work. This was demonstrated by the above test-case, which is identical to @howardjohn 's suggestion, but still doesn't work.

I don't really get what you mean? What exactly did you apply to get in the terminal bad state? All of the configs in the gist in order?

> We should test on Docker Desktop since I can't expect everyone in my team to run a separate cluster-setup tool, so testing on KinD is right now not a solution for us.

I don't think anyone is suggesting you do not run Docker Desktop?

> a. Print Events to the Deployment or Operator CRD instance, like the Elasticsearch Operator does

This is being added in 1.4, see https://preliminary.istio.io/docs/ops/diagnostic-tools/istioctl-analyze/#enabling-validation-messages-for-resource-status

> b. Print logs in envoy-proxy when it fails a request with a 503 response; in fact print every request on a single line so you can enable users to debug your software config

These can be enabled, but are turned off by default due to performance impact. See https://istio.io/docs/tasks/telemetry/logs/access-log/

**Comment by haf-afa** [comment]
> I don't really get what you mean? What exactly did you apply to get in the terminal bad state? All of the configs in the gist in order?

> I don't think anyone is suggesting you do not run Docker Desktop?

Great, so I'm supposed to be able to run Istio on D/D then!

I'm going to 1) try again to run Istio 1.3.3 on D/D WITHOUT SDS, which SHOULD work, 2) see if I create a minimal "step by step" repro for the internal routing corruption. Do you have a QuickCheck suite for actor-invarient property testing?

**Comment by haf-afa** [comment]
Here's a stand-alone repro that fails for 1.2.8 and 1.3.4: https://github.com/haf-afa/istio-bugs

Repro: ` make istio_1_3_4` or `make istio_1_2_8`

**Comment by haf-afa** [comment]
I'm going to close this due to lack of time to reproduce it on my side. I'll reopen if it becomes a problem again and when we a suite around it. It worked well with permissive mode + nginx for now.

**Comment by JayceLau** [comment]
> @haf-afa just want to clarify current state here: Your last attempt, with everything in the default namespace works, but you want the Gateway in istio-system, right?
> 
> I applied your setup with all default namespace, and everything worked.
> 
> Then I moved the gateway to istio-system, and it not longer works. I ran the new `istioctl analyze` tool (https://preliminary.istio.io/docs/ops/diagnostic-tools/istioctl-analyze/.) and it warned me that the virtual service referenced an unknown Gateway. I then modified the virtual service to point to `istio-system/helloworld-gateway` instead of `helloworld-gateway` and everything worked. (although it did find what I think is a minor bug -- the new tool is experimental #18366)
> 
> I then moved the VS to istio-system as well, and things broke again. `analyze` warned me that the host `helloworld` does not exist now; replacing with `helloworld.default.svc.cluster.local` fixes this

Many thanks, `istioctl analyze` save me.
