### ISSUE TITLE
[Kiali] Unable to view Services - release 1.2

### ISSUE THREAD

**Issue by lentzi90** [istio/istio#18220]
**Bug description**
Whenever I click on a Service in the console I get the message `Sorry, there was a problem. Try a refresh or navigate to a different page.` on screen, and in the chrome console this:

```
TypeError: Cannot read property 'filter' of undefined
    at t.getPortIssue (ServiceInfoDescription.tsx:76)
    at t.hasIssue (ServiceInfoDescription.tsx:84)
    at ServiceInfoDescription.tsx:140
    at Array.map (<anonymous>)
    at t.render (ServiceInfoDescription.tsx:138)
    at ca (react-dom.production.min.js:163)
    at sa (react-dom.production.min.js:162)
    at pa (react-dom.production.min.js:169)
    at $a (react-dom.production.min.js:204)
    at qa (react-dom.production.min.js:205)
```

**Expected behavior**
Kiali would display Service details and no error messages.

**Steps to reproduce the bug**

1. Install Istio 1.2.7 and deploy the bookinfo app:
   ```shell
   helm repo add istio.io https://storage.googleapis.com/istio-release/releases/1.2.7/charts/
   helm repo update
   helm upgrade --install istio-init istio.io/istio-init --namespace istio-system
   # wait for it to finish
   helm upgrade --install istio istio.io/istio --namespace istio-system --set kiali.enabled=true --set kiali.createDemoSecret=true
   kubectl create ns test
   kubectl label ns test istio-injection=enabled
   kubectl -n test apply -f https://raw.githubusercontent.com/istio/istio/release-1.2/samples/bookinfo/platform/kube/bookinfo.yaml
   ```
2. Set up port-forward to Kiali: `kubectl -n istio-system port-forward svc/kiali 20001:20001`
3. Go to localhost:20001 and login with `admin:admin`, navigate to Services, select namespace `test` and click on a Service in the list.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```
client version: 1.2.4
citadel version: 1.2.7
galley version: 1.2.7
ingressgateway version: 1.2.7
pilot version: 1.2.7
policy version: 1.2.7
sidecar-injector version: 1.2.7
telemetry version: 1.2.7

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-gke.2", GitCommit:"c9de33b5439df6e206d7ba646787c6ace92d737b", GitTreeState:"clean", BuildDate:"2019-09-06T18:30:33Z", GoVersion:"go1.12.9b4", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
Using helm and tiller v2.14.3

**Environment where bug was observed (cloud vendor, OS, etc)**
Google Kubernetes Engine.

**Comment by lentzi90** [comment]
Note: I'm not able to reproduce this on 1.3.3.

**Comment by howardjohn** [comment]
Thanks for the report! Looks like an internal error, this may be better reported to https://github.com/kiali/kiali. However if it works in 1.3.3 they probably already fixed the issue

**Comment by lentzi90** [comment]
I'm just thinking that maybe the istio release branch for 1.2 should get the newer version of kiali.
The difference I can see is `appVersion: 1.1.0` in 1.3 and `appVersion: 0.20` in 1.2 [here](https://github.com/istio/istio/blob/release-1.2/install/kubernetes/helm/istio/charts/kiali/Chart.yaml).

Without this, kiali will stay broken on 1.2 even when it is still a supported version.
