### ISSUE TITLE
Improve / Break up Pilot integration tests

### ISSUE THREAD

**Issue by hklai** [istio/istio#1823]
Context:
The second issue as documented in https://docs.google.com/document/d/1x2gkagFfqPpb0GWFTmw1k8nFP1dZ7UQiujRpbpNlXC4/edit#heading=h.x9snb54sjlu9

Suggestions:
1. Move the existing Pilot integration tests that use GKE to Post-Submit (or to the E2E suite)
2. Change the existing Pilot integration tests to use the lightweight integration test framework (https://github.com/istio/istio/pull/1675) to bring up standalone pilot.

**Comment by kyessenov** [comment]
Circle CI can run the existing e2e tests in about 3 minutes. Is that acceptable enough?

**Comment by kyessenov** [comment]
(these are tests that use minikube and do not use bazel)

**Comment by hklai** [comment]
Circle CI is currently not required, but maybe we can rely on that for now instead of spending effort on suggestion #2. I'll let Nathan decide.

Also I suppose it is not a bad idea to run these tests in GKE as well for environments coverage. Hence suggestion #1.

**Comment by nmittler** [comment]
hklai@ based on [your comment above](https://github.com/istio/istio/issues/1823#issuecomment-346248269) it seems that the real goal here is to make the existing integration tests run on a variety of platforms (stand-alone, minicube, GKE) ... does that sound right? If so, maybe we rename/re-describe this issue?

**Comment by hklai** [comment]
The bottom line goal here is to remove the GKE dependency from the Pilot presubmit test that runs in Prow, and preserve the same or similar coverage.

Implement multi-environments test support is a bonus and it actually applies to Istio across the board.

**Comment by nmittler** [comment]
@hklai I believe the duration on prow has been greatly reduced since #3663 was submitted.  Is that sufficient for this?

**Comment by hklai** [comment]
A lot had changed since I opened this. circle ci tests are now the presubmit standard and prow tests are not required anymore. 

However, pilot e2e seems to be failing for most PRs.
https://prow.istio.io/?type=presubmit&job=istio-pilot-e2e

Is that expected?

**Comment by nmittler** [comment]
@hklai AFAIK, prow has been broken all week ... not just for that test.

**Comment by hklai** [comment]
@sebastienvas is the pilot e2e failures related to the other post submit failures you were looking at today?

**Comment by hklai** [comment]
Pilot e2e tests are again passing and they now take around 10 mins only.
https://prow.istio.io/?type=presubmit&job=istio-pilot-e2e

Closing this now since the original problem no longer exists.
