### ISSUE TITLE
Add --all-namespaces support to `istioctl analyze`

### ISSUE THREAD

**Issue by sushicw** [istio/istio#18236]
Right now, `istioctl analyze` looks for validation messages in only one namespace at a time. Mirroring kubectl behavior, we should add an `--all-namespaces` option that does analysis for multiple namespaces. 

There may be some subtleties around whether we need to ignore "system" namespaces (e.g. usually `kube-system` and `istio-system`). See https://github.com/istio/istio/issues/17381

**Comment by howardjohn** [comment]
I think this is essential for running in CI systems. Its really confusing where you run `analyze file.yaml` and it does nothing since the namespace is not right

**Comment by sushicw** [comment]
To add more detail: John ran into a situation where he was analyzing a file in namespace `istio-system`. Since he didn't specify a namespace, analysis was done against the `default` namespace, and didn't find the expected errors. 

For this particular situation, an alternate approach may also be to simply be smarter about the default namespace(s) to use. e.g. if a user specifies a YAML with a single resource with a namespace, it's obvious we should be looking at that namespace. etc.

**Comment by sushicw** [comment]
While doing this, we should also have `-v` output include the namespace(s) analyzed.
