### ISSUE TITLE
Add  credentialName to the TLS options of the DestinationRule 

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio#18233]
**Describe the feature request**

Add `credentialName` to the TLS options of the DestinationRule similarly to the `credentialName` of the Gateway's server

**Additional context**

**Comment by incfly** [comment]
This one by itself is a valid FR IMO. Basically bring SDS to client envoy. Might need a mini-page design.
/cc @JimmyCYJ @myidpt

**Comment by JimmyCYJ** [comment]
@vadimeisenbergibm Could you please introduce the motivation and share more context about the usage of this change? We already support SDS for mTLS between workloads.

**Comment by incfly** [comment]
@JimmyCYJ This is to support using SDS + secret referenced by credential name, but also support configuring from client side, using customer provided certificate, rather than Citadel.

Today we only can configure key/cert in that type for gateway, server side, not client side. 

My understanding.

**Comment by howardjohn** [comment]
The main issue is we probably do not want to give secret access to all sidecars, so we probably need istiod to push the secrets or something? Or I guess if they are opting into this they can configure a Role themselves to give Secret access (even to the specific secret they need)?

**Comment by vadimeisenbergibm** [comment]
@howardjohn This option should allow the sidecar proxy to use any secret, for example for performing mTLS with external sites. It will be the user's responsibility to rotate the key/certificate, and the user will define the Role for the Secret's access.

As the next option, out of scope of this issue, Istio Citadel can be extended to rotate keys/certificates for external systems, by integrating it with some external certificate authority.

The general topic here is integrating a service mesh inside an enterprise, where the services inside the mesh must communicate securely with services in the enterprise outside of the mesh, and where the enterprise employs its own internal certificate authority. Another topic is federating multiple Istio meshes, each one with its own Citadel.

**Comment by howardjohn** [comment]
Fixed by https://github.com/istio/api/pull/1468
