### ISSUE TITLE
TestAddUpdateDeleteWithWatcherEnabled test flake

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#18244]
https://prow.istio.io/view/gcs/istio-prow/logs/unit-tests_istio_postsubmit/461

@vikaschoudhary16

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18405/unit-tests_istio/3268

@vikaschoudhary16 please take a look or we may need to revert the PR

**Comment by vikaschoudhary16** [comment]
@howardjohn hey, sorry for the delayed response, i was on vacations. Taking a look

**Comment by howardjohn** [comment]
Closing as essentially duplicate of https://github.com/istio/istio/issues/18385 - same test suite
