### ISSUE TITLE
istioctl analyze does not fail when passed an invalid namespace

### ISSUE THREAD

**Issue by davidebbo** [istio/istio#18247]
When using:

    istioctl x analyze -k -n bogus

It runs successfully. It should instead fail to make this clear to the user.

**Comment by esnible** [comment]
`kubectl` doesn't either, does that make a difference?

```
$ kubectl -n twilight-zone get pods
No resources found.
```

**Comment by davidebbo** [comment]
Fair enough, no reason to diverge here.
