### ISSUE TITLE
SideCarInjector crashing in GKE with error "too many open files"

### ISSUE THREAD

**Issue by epsniff** [istio/istio#18257]
**Bug description**

After our istio-sidecar-injector was upgraded from `gke.gcr.io/istio/sidecar_injector:1.1.7-gke.0` to `gke.gcr.io/istio/sidecar_injector:1.1.13-gke.0`, it began crashing and went into a crash back off loop with the following error: 
```
Error: failed to create injection webhook inotify_init: too many open files
```

As a workaround I added the following to the deployment for the istio-sidecar-injector at the path of `spec.template.spec.containers`
```
      initContainers:
      - command:
        - sysctl
        - -w
        - fs.inotify.max_user_instances=1000
        image: busybox
        imagePullPolicy: Always
        name: init-inotify-limit
        resources: {}
        securityContext:
          privileged: true
```

**Expected behavior**

The sidecar should startup normally and continue to run, without running out of file handles. 

**Steps to reproduce the bug**

Im not sure, but I guess create a sidecar injector for version `gke.gcr.io/istio/sidecar_injector:1.1.13-gke.0`, and over 100 pods running? 

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```
$ istioctl version --remote
client version: 1.4.0-beta.0
control plane version: d3ed357dbb236f0f6188a7fcd17a47941442f9a8
data plane version:  (3 proxies)
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-17T17:16:09Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-gke.24", GitCommit:"2ce02ef1754a457ba464ab87dba9090d90cf0468", GitTreeState:"clean", BuildDate:"2019-08-12T22:05:28Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
Using the use-istio checkbox with in GKE.

**Environment where bug was observed (cloud vendor, OS, etc)**

Google Kubernetes Engine

**Comment by howardjohn** [comment]
Any idea what is using the inotify watches? https://stackoverflow.com/questions/13758877/how-do-i-find-out-what-inotify-watches-have-been-registered might help.. or might not. I recall trying to answer that same question on GKE and had a hard time.

I suspect that something else is consuming the inotify watches (since its a node level resource) and the injector is just a victim of this

Does this problem persist if the injector gets scheduled on a new node?

**Comment by epsniff** [comment]
@howardjohn thanks for the feedback.  Right, since this is a node level resource I should be investigating what's going on at the node level :).  Yeah, that should have been obvious now that I think about it. 

I'll have a look at the GKE node and post a comment if I find anything worthy of sharing.  In the meantime, I think it's safe to close this ticket as it appears not to be an istio issue.

**Comment by howardjohn** [comment]
Thanks. Please reopen if it is our fault. We should be creating only a few watches so if we are doing more we may have a bug
