### ISSUE TITLE
TestJwtPubKeyEvictionForNotRefreshed test failure

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#18268]
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/17693/unit-tests_istio/3045

**Comment by yangminzhu** [comment]
I think the test is not failing recently: https://k8s-testgrid.appspot.com/istio_istio#unit-tests_istio&include-filter-by-regex=TestJwtPubKeyEvictionForNotRefreshed&width=20
