### ISSUE TITLE
istio pods are not coming up after scheduled shutdown

### ISSUE THREAD

**Issue by dhineshbabuelango** [istio/istio#18262]
We are using istio in AWS EKS. We used to shutdown our worker nodes regularly every night and start the nodes at morning.
Previously after scheduled shutdown, we saw an considerable delay in pods coming up particularly in istio-injection enabled namespace, we opened the below case and it was closed and asked to track in ( https://github.com/istio/istio/issues/13840).
https://github.com/istio/istio/issues/16808.

Now for the past one week, after the scheduled shutdown pods in the istio-system namespace are not coming up. Every day I have to restart the entire deployment in istio-system namespace only then the pods are coming up. I am seeing hte below error in all the pods

Readiness probe failed: HTTP probe failed with statuscode: 503

![image](https://user-images.githubusercontent.com/51995628/67446907-b2d4a480-f644-11e9-878f-1ccac74c5ce8.png)

And this is one error in istio-policy pod 

![image](https://user-images.githubusercontent.com/51995628/67447063-4312e980-f645-11e9-9f56-b30989df03f2.png)

**Comment by hzxuzhonghu** [comment]
@dhineshbabuelango Could you provide log in the crash loop back pod?

**Comment by howardjohn** [comment]
Just get the logs from all the control plane pods please.. from the description it looks like pilot/mixer both fail to get ready, probably due to failure to talk to galley. So at very minimum get pilot, galley, and citadel logs

**Comment by dhineshbabuelango** [comment]
Please find attached the logs

galley.log
citadel.log
pilot.mixer.log
pilot.discovery.log

**Comment by howardjohn** [comment]
Yes, pilot and mixer cannot connect to galley. Not sure why though

**Comment by dhineshbabuelango** [comment]
This is happening everytime I restart the worker node but after I restart teh istio-system deployment is is running fine

**Comment by dhineshbabuelango** [comment]
Hi John, the issue is still happening, everyday we have to restart the complete deployment in istio-system namespace as workaround, anything you can suggest
