### ISSUE TITLE
Galley config analyzer panic closed channel

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#18265]
https://prow.k8s.io/view/gcs/istio-prow/logs/integ-istioctl-k8s-tests_istio_postsubmit/468

**Comment by sushicw** [comment]
I've looked at this a bit, and so far haven't been able to find any more examples or anything obvious in the code that could be leading to it.

**Comment by sushicw** [comment]
I haven't been able to find any examples of this more recent than 10/20 (the one linked above). Going ahead and closing this,  but we should reopen if this starts happening again.
