### ISSUE TITLE
Documentation on the best way to install istio

### ISSUE THREAD

**Issue by jdamour98** [istio/istio#18280]
**Describe the feature request**
It seems there are several ways to install istio:
- helm template | kubectl apply
- helm install (Istio wont support helm3?)
- Istio Operator: https://github.com/istio/operator
- Istio Installer: https://github.com/istio/installer

**Describe alternatives you've considered**
On some readme of the istio repo or website, describe the different projects and what the future of istio may look like.

**Additional context**
 I want to set up a cluster to be production ready and stable for the next couple years. what strategy to I choose?

**Comment by sdake** [comment]
I've assigned to @frankbu as he has done a nice job improving the 1.4 installation documentation.  He can close this out as he sees fit.

Cheers
-steve

**Comment by howardjohn** [comment]
@frankbu is there more work to be done here?

**Comment by frankbu** [comment]
It's improved, but there is more to do to integrate the install instructions with deployment models and best practices doc. This will be coming after 1.4.

**Comment by jdamour98** [comment]
@frankbu Thanks, is there a link to the most up-to-date install instructions?

**Comment by mrf** [comment]
At a minimum some clarity around `Istio wont support helm3` would be really welcome. 

We've been happily installing and upgrading Istio with helm2 across a half dozen clusters without issue and would really like to be able upgrade everything to helm3 and stop managing Tiller.

I'm not finding any documentation about when helm2 will go EOL but it will only be a matter of time, I don't see that community maintaining the two versions much longer than a year or two.

**Comment by mrf** [comment]
`Install a Helm client with a version higher than 2.10.` is the only mention of Helm version I'm finding in the 1.4 version of helm docs at https://istio.io/docs/setup/install/helm/  That definitely needs to be updated `<3  >2.10` since 3.x is the latest stable version of helm.

**Comment by frankbu** [comment]
Since for better or worse, we're planning to deprecate the helm install and move to the new istioctl/operator install, I think that all we need to do is add a warning in the helm docs to say that helm 3 is not supported.

**Comment by howardjohn** [comment]
This is done as far as I know
