### ISSUE TITLE
[istio.io testing] Need test for TCP Traffic Shifting

### ISSUE THREAD

**Issue by brian-avery** [istio/istio#18285]
**Describe the feature request**
We need to develop a test for the [TCP Traffic Shifting](https://preliminary.istio.io/docs/tasks/traffic-management/tcp-traffic-shifting/) task in order to provide automated testing of the Istio.io website for future releases.

Example tests and the documentation for the framework can be found here: https://github.com/istio/istio/tree/master/tests/integration/istioio

A YouTube video describing the usage of the framework can be found here: https://www.youtube.com/watch?v=3y-z8NaVwr0

Please reach out to the Test and Release channel on the [Istio Slack](https://discuss.istio.io/t/istio-slack-channel/1527) or [Test and Release Discuss](https://discuss.istio.io/c/test-and-release)  with any questions.

**Comment by su225** [comment]
I'll take this one as well.

**Comment by luizfnunesmarques** [comment]
Hi @su225 Do you mind if I try this one? I started to work on it prior to look on the issues (started with the docs/site tests to get used to the env), my bad. If already started to work on it too, just let me know and I will pick another issue.

thanks :-)

**Comment by su225** [comment]
@luizfnunesmarques  - I already have some work. My bad..I didn't see your comment.

**Comment by luizfnunesmarques** [comment]
Ok, no problems mate, I'll pick another issue then :-)

**Comment by howardjohn** [comment]
this new test seems to be flaky https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/20775/integ-istioio-k8s-tests_istio/4323

**Comment by brian-avery** [comment]
The flakiness is being addressed in https://github.com/istio/istio/issues/20771. As this test was implemented in https://github.com/istio/istio/pull/20232, I am closing this issue.
