### ISSUE TITLE
[istio.io testing] Need test for Traffic Shifting

### ISSUE THREAD

**Issue by brian-avery** [istio/istio#18284]
**Describe the feature request**
We need to develop a test for the [Traffic Shifting](https://preliminary.istio.io/docs/tasks/traffic-management/traffic-shifting/) task in order to provide automated testing of the Istio.io website for future releases.

Example tests and the documentation for the framework can be found here: https://github.com/istio/istio/tree/master/tests/integration/istioio

A YouTube video describing the usage of the framework can be found here: https://www.youtube.com/watch?v=3y-z8NaVwr0

Please reach out to the Test and Release channel on the [Istio Slack](https://discuss.istio.io/t/istio-slack-channel/1527) or [Test and Release Discuss](https://discuss.istio.io/c/test-and-release)  with any questions.

**Comment by su225** [comment]
I'll take this one too.
