### ISSUE TITLE
auto mtls: need fallback to simple tls instead of plaintext

### ISSUE THREAD

**Issue by rshriram** [istio/istio#18293]
**Describe the feature request**
Today, the auto mtls feature falls back to literally plaintext if mtls is not available. This will not work in most enterprises today because almost all their deployments (k8s or vms) use one-way TLS from the ingress LB to pods or VMs. The TLS certs in the app is the same as the TLS certs in the load balancer (this is the poor mans way in the enterprise to ensure that all data in transit remains encrypted). There are two strong use cases for the tls fallback:

1. With Istio, we are advocating that people switch to plaintext for all outbound communications and let the sidecar do any form of TLS, so that they can get rich telemetry, routing, etc. However, when the sidecar has to talk to non-mesh services, we effectively end up sending plaintext traffic from the sidecar to these non-mesh services [which ends up breaking as these services require TLS]. So this will then force the user to either author destination rules for each and every dependency or simply do HTTPS from the application and let the sidecar do SNI passthrough. If they do the latter, they lose all benefits of Istio - especially in a large deployment where Istio is being tested and gradually rolled out.

    The introduction of auto mTLS was really helpful because sidecars could now automatically detect if the other side has a sidecar or not, and if so, it will do mtls. If not, it will do *plaintext*. however, as described above, in most enterprise setups, these sidecars will need to do one-way TLS rather than plaintext. By allowing automTLS to fallback to one-way TLS we can solve this problem.

    The only caveat is that the user wont be able to specify root certs that will verify the server side CA cert. This, while not so great, is still a LOT better than simply doing plaintext to all unknown services, and breaking compliance [all data in transit is not encrypted]. If the user really needs to verify the server side CA, i.e. security is of paramount importance, then they would not be doing PERMISSIVE mode or autoMTLS at all. So, given that these users are willing to relax the security constraints during the migration period (by allowing permissive mode, protocol sniffing, fallback from mtls to literally-plaintext), they are okay with doing unverified https compared to plaintext.

2. The second use case is incremental migration of these TLS workloads themselves. Imagine the following scenario:
   1. User has a details.vm.internal service that is part of bookinfo app
      1. This service is running on 400 VMs where these VMs have a TLS cert (one-way TLS)
      1. This service receives traffic only from k8s where Istio is installed (i.e. from sidecars).
   1. Initially the user created a destination rule that initiated one-way TLS from the productpage service in kubernetes.
   1. The user is slowly migrating these VMs to use Istio mutual TLS, by adding sidecars on these VMs and letting the sidecar take care of all mutual TLS traffic.
   1. During this migration, some set of VMs now gain the ability to use mutual TLS while the rest are doing one-way TLS. However, the destination rule will force all traffic to use one-way TLS and thus results in 503s. If I remove the destination rule, traffic to VMs using one-way TLs will fail, while traffic to VMs using mutual TLS will succeed due to auto mTLS. This is because the auto mtls implementation defaults to falling back to literally plaintext mode. In this case, it should be falling back to the one-way TLS.

    A simple fix to the problem is to stop having a boolean label like `security.istio.io/mtlsReady: true`. Instead, we should have `security.istio.io/tlsMode: plaintext|simple-no-verify|istio`. If the endpoint has plaintext label (which is mostly unlikely), we can use plaintext from the client. If it has sidecar-no-verify label, we can use simple one-way TLS from the sidecar. Granted we will not be able to do root ca verification in this case, but keep in mind: this is a migration use case like the permissive mode on server side - i.e. temporary.
 
**Describe alternatives you've considered**

**Additional context**

**Comment by rshriram** [comment]
A nice benefit of this idea is that it will also work for @uk000 and co, where they have mixed mode (k8s pods with mtls, and VMs with one-way TLS), without requiring API changes. 
Since we have not made a release yet, we should consider changing this label soon. Otherwise, we will have to support backward compatibility and cause more confusion

**Comment by linsun** [comment]
A little worried about tlsMode label and the complexity to under these label meanings and apply at the correct times during the transition period.

if they have 400 services on vm, can we ask them to do canary on these 400 services, like 20% add envoy sidecar (auto mTLS) while 80% stay on one way TLS (via destinationrule) and subsets?  can we put the services with sidecar different subset than services without sidecar?  I'd think the service code could be different too as sidecar can reduce lots of non-essential code from the service.

**Comment by rshriram** [comment]
The question here is why can’t we do the same for auto mtls as well ? Why do we need to have this auto mtls option when we can tell end users to do subsets etc ? 

If we added auto mtls for simplicity, where end users have to add these labels for non k8s workloads, then we should maintain the same approach for simple tls. Also remember that this will become useful in kubernetes as well if people have migrated their workloads from vms to k8s, but haven’t added sidecars yet. Simply assuming that anything not mtls is plain text is forcing users to an even more insecure system than allowing them to do one way tls as they are doing today.

**Comment by linsun** [comment]
So `security.istio.io/tlsMode:istio` is the new `security.istio.io/mtlsReady: true`?

auto mTLS was introduced when user changes from permissive to strict for services already have the sidecar.  I'm just trying to understand how common your cases is and if it is necessary to cause confusing in the configuration for simple cases:

1. user enable strict mTLS for a service or a namespace or the mesh.  This is where auto mTLS can become really handy.  Many of our tutorials in istio.io is this simple scenario.
2. in your specific case, I feel people don't want to declare the services in transition to serve traffic until it is well tested/validated.  That is why I proposed canary or a/b testing for those.

**Comment by rshriram** [comment]
> So `security.istio.io/tlsMode:istio` is the new `security.istio.io/mtlsReady: true`?
> 
yes and it will be auto injected. So no user configuration in either case.

> auto mTLS was introduced when user changes from permissive to strict for services already have the sidecar. 
That is no longer true. See below :)

>I'm just trying to understand how common your cases is and if it is necessary to cause confusing in the configuration for simple cases:
> 
> 1. user enable strict mTLS for a service or a namespace or the mesh.  This is where auto mTLS can become really handy.  Many of our tutorials in istio.io is this simple scenario.

Nope. auto mtls helps to automatically do mTLS when the calling sidecar knows that the destination also has a sidecar, irrespective of whether the destination has strict or permissive mode. This way, anytime you add a sidecar to a service (partial or full), all communications to this sidecar (from other sidecars in the mesh) will automatically do mutual TLS - you dont even have to bother changing from permisssive to strict. Thats the beauty of it. The more sidecars you add, the more mtls you get with zero change.

> 2. in your specific case, I feel people don't want to declare the services in transition to serve traffic until it is well tested/validated.  That is why I proposed canary or a/b testing for those.

So my case is exactly same as the auto mtls case. The biggest assumption/mistake in auto mTLS is that the fallback in case there is no sidecar is always plaintext. This is not an acceptable solution in enterprises because almost all their workloads use one-way TLS from the load balancer to their application pods in k8s or VMs. No one in financial sector does clear text traffic [even before istio]. So, our current model of auto mtls will become useless to them because they cannot do plaintext from a sidecar to a non sidecar pod. I have updated my use case above

**Comment by linsun** [comment]
Thanks for the additional detail and update!  So I think I get there is a need for 3 modes... I was somewhat confused to use these 3 modes.... Here are the 3 modes:

1. no fall back, always plain text.
2. Fall back for mTLS (if mTLS doesn't work out):
- 2.1  plain text 
- 2.2 one way TLS

Are these correct?

**Comment by linsun** [comment]
```auto mtls helps to automatically do mTLS when the calling sidecar knows that the destination also has a sidecar, irrespective of whether the destination has strict or permissive mode. This way, anytime you add a sidecar to a service (partial or full), all communications to this sidecar (from other sidecars in the mesh) will automatically do mutual TLS - you dont even have to bother changing from permisssive to strict. Thats the beauty of it. The more sidecars you add, the more mtls you get with zero change.```

I'm concerned with this... How would I know if I'm enforcing mTLS for my sidecars?  Today I can do it via mesh policy or/and auth policy. Users may likely want the flow to fail when the services not using mTLS when it is mandatory to use mTLS for all services communication.

**Comment by rshriram** [comment]
When you enforce mTLS, the server side will be strict completely. So, any client (sidecar or not) that does plaintext will fail to communicate. At that point, on the client side, all sidecars will default to using the mutual TLS because all the destinations will have that label.

**Comment by diemtvu** [comment]
As comment in the PR, can we design a proper API for setting fallback TLS options instead? I think it would be more flexible to address all needs (the simple TLS fallback seems to limited to me, for example how does it works if server use self-signed cert), and does not complicate the label semantic.

**Comment by PiotrSikora** [comment]
> Today, the auto mtls feature falls back to literally plaintext if mtls is not available.

I think this feature is mixing "service mesh transport security" (which is either mTLS or plaintext) with "workload transport security" (which is either one-way TLS or plaintext; we don't have client certificates to perform workload mTLS from the sidecar, so we treat it as opaque bytes, i.e. plaintext).

**Comment by incfly** [comment]
>  we don't have client certificates to perform workload mTLS from the sidecar, so we treat it as opaque bytes, i.e. plaintext).

So yeah, actually, could users continue to let client app terminate the one way tls connection for those not migrated server workloads? This meets the requirements of not falling back to plain-text, even though traffic is opaque bytes in the point of client sidecar.

If the answer is no, is it because users can't use L7/http Istio features if sidecar don't understand the protocol?

**Comment by louiscryan** [comment]
Clearly we have an issue with a layerng violation. We would rather have as @PiotrSikora describes a mechanism for transport security that can't collide with application security. The fact that we use TLS on the same port as the application port is causing us pain.

Now in this case there is no reason why the fallback behavior can't be the behavior assigned to the endpoint in the DestinationRule rather than plaintext. It's still a layering violation but at least it keeps TLS if it were declared.

Separately we should look for a more holistic solution to the layering violation.

@rlenglet FYI

**Comment by rshriram** [comment]
I dont think it is a violation. Remember that people adopt a mesh for telemetry as well. When tehy add a sidecar to their app, we advise them that they can do plaintext from their app and we will initiate TLS on their behalf, if they want telemetry, routing, etc. So, in this context, if you are going to tell them that `if you want one-way tls, go back to https and ignore the sidecar`, then we are effectively sending the message that mesh adoption is all or nothing. And that you will not get telemetry as you progress in adoption. 
Imagine an org that has 4000 namespaces across VMs and k8s. IF the end user adopts the mesh on a namespace by namespace basis, the first tangible benefit is telemetry (for traffic to in-mesh sidecars and traffic to non-mesh apps as well). So, telling these people that adding a sidecar is going to be of little use until the entire system is on the mesh is not a great thing to do, especially when the competitors are providing the same feature.

**Comment by xiewenzhou** [comment]
what the "security.istio.io/tlsMode:istio" feature?
