### ISSUE TITLE
Grafana is unable to show the graph for bookinfo app 

### ISSUE THREAD

**Issue by chayan88** [istio/istio#18290]
**Bug description**
Deployed the bookinfo app and expose the "productpage service" and generated traffic using the productpage svc route , but in Grafana dashboard nothing is showing up.

**Expected behavior**
Grafana should show the traffic in out of the box workload dashboard.
**Steps to reproduce the bug**
Deploy bookinfo On Openshift 3.11 (on IBM Cloud) and access the app using productpage svc (by exposing it securely)
**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```
bash-4.2$ istioctl version --remote
client version: 1.3.2
citadel version: 1.3.2
egressgateway version: 1.3.2
galley version: 1.3.2
ingressgateway version: 1.3.2
pilot version: 1.3.2
policy version: 1.3.2
sidecar-injector version: 1.3.2
telemetry version: 1.3.2

kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-09-12T23:41:09Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"
```
**How was Istio installed?**
Using Helm (demo profile)
**Environment where bug was observed (cloud vendor, OS, etc)**
IBM Cloud

![image](https://user-images.githubusercontent.com/33457041/67517270-e0126880-f6bf-11e9-92d1-c7e7c37865b2.png)

**Comment by sethokayba** [comment]
have you verified if Prometheus is set for Grafana ?

**Comment by mabushey** [comment]
Your kubectl version is not compatible with your version of K8s. They need to be no more than one minor version apart. 1.11 works with 1.12 or 1.10.

**Comment by douglas-reid** [comment]
We have dashboard tests that verify the underlying queries for the dashboards that run on all commits. We have not seen any issues with the dashboard. Are you sure that you have proxies injected, etc.? 

You may be interested in the troubleshooting entries:
- https://istio.io/docs/ops/common-problems/observability-issues/#missing-grafana-output
- https://istio.io/docs/ops/common-problems/observability-issues/#verify-mixer-is-sending-metric-instances-to-the-prometheus-adapter

Closing for now, as this doesn't seem to be a general problem. Please reach out on the [forums](discuss.istio.io) for related questions.
