### ISSUE TITLE
Clean up token matching in Istio.io Test Framework

### ISSUE THREAD

**Issue by brian-avery** [istio/istio#18297]
Currently, the token matching supports wildcards, but I think that might be too limiting. 

We will likely want to support the following types of token matching at a minimum: 

* Check all output for a command for foo.
* Make sure all output for a command does not contain foo.
* A single line matches a regular expression
* A single line does not match a regular expression.
* Check a single line to make sure that all fields match something except for the last.

**Comment by fpesce** [comment]
single match regex is part of #18449 
Could easily do the negative Regex on a following PR.

**Comment by brian-avery** [comment]
I believe this is still needed.
