### ISSUE TITLE
istio/tools: track benchmark pipeline related issues

### ISSUE THREAD

**Issue by carolynhu** [istio/istio#18298]
Here is a list of issues we found when building benchmark pipeline:

- [x] fortio server connection refused in some circumstances. //cc @richardwxn 

- [ ] Same istio configuration test is triggered and run with different run_id. To optimize, we need to figuring out how to avoid duplicate tests running.
To be more specific: when gathering latency data, we have qps=1000, conn=16. But the same configuration also being used when gathering cpu/mem data. 

- [x] Istio mixerv2-nullvm only has `baseline` and `serveronly` results in .csv file, but it does not have `both` mode numbers.

- [x] could not ssh into gcloud instance when enabling perf record

- [x] Need to fix this error related to perf
```
OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "exec: \"/etc/istio/proxy/get_perfdata.sh\": stat /etc/istio/proxy/get_perfdata.sh: no such file or directory": unknown
command terminated with exit code 126
Defaulting container name to captured.
```

- [x] Investigate why there is a data point missing for serveronly mode when conn=1, qps=1000

Latest run status update:

 The benchmark test finished and uploaded the data successfully for past two days but the test was showing failure status, because pods were down intermittently during clean up process so it failed during one of the debugging kubectl call in the TRAP.

**Comment by carolynhu** [comment]
cc @mandarjog

**Comment by richardwxn** [comment]
As an update, the benchmark test finished and uploaded the data successfully for past two days but the test was showing failure status, because pods were down intermittently during clean up process so it failed during one of the debugging kubectl call in the TRAP.

**Comment by carolynhu** [comment]
@richardwxn please also link your related PRs here, thanks

**Comment by carolynhu** [comment]
https://github.com/istio/tools/pull/488

**Comment by carolynhu** [comment]
Need to fix this error related to perf
```
OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "exec: \"/etc/istio/proxy/get_perfdata.sh\": stat /etc/istio/proxy/get_perfdata.sh: no such file or directory": unknown
command terminated with exit code 126
Defaulting container name to captured.
```
