### ISSUE TITLE
Analyzer to check sidecar configuration matches the injection template

### ISSUE THREAD

**Issue by selmanj** [istio/istio#18302]
Right now there's an injection analyzer that just compares proxy version to the injector version. It would be more correct to actually verify that the injected configuration matches. 

As an example, if you change your network configuration in a multi-cluster setup, the sidecars need to have new configuration injected (and thus need to be restarted).

**Comment by elfinhe** [comment]
this is a great feature and we may also want to add into `istioctl proxy-config` or `istioctl ps`
