### ISSUE TITLE
istioctl analyze should support structured output (json)

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#18306]
To support CI use cases, it would be useful to support structured output. This would allow parsing the output and doing certain things for different errors, or whatever else they want.

**Comment by sushicw** [comment]
This is discussed a bit in this design doc: https://docs.google.com/document/d/1KuxDRPPt283jx_cIs2C9sFHjoHvoskJt3IGqhPJVHtM/edit

TL;DR: we probably want to support `-o yaml` and `-o json` like `kubectl` does.

**Comment by zerobfd** [comment]
I think there's enough acceptance of the doc to go ahead and get started so I'm gonna claim this issue and go ahead.
