### ISSUE TITLE
istio-ingressgateway behind trusted loadbalancer

### ISSUE THREAD

**Issue by lambdai** [istio/istio#18300]
I see a lot of cases deploying istio-ingressgateway behind a trusted cloud provided loadbalancer.

Since the capability of trusted loadbalancer varies, istio-ingressgateway should have correspondent configures. 
There might be some workarounds but long term plan is missing.
There are possible achievables in the istio stack but the config is not open to istio api. 
There might be features not surfacing yet.

I am listing the issues here and feel free to add, refer or discuss. 

1. https redirect iff X-forwarded-Proto is http (@lambdai)
https://github.com/istio/istio/issues/16778

~~2. health check https://github.com/istio/istio/issues/3867~~ Fixed long ago

3. use_remote address https://github.com/istio/istio/issues/12549#issuecomment-544954473

4. sanitize headers if not behind trusted lb #7679

**Comment by linsun** [comment]
I'm under the impression that #3867 is already fixed... we have a status port on the gateway.

**Comment by fcantournet** [comment]
My understanding is this issue #3867 is about a Network Load-balancer, not an HTTP reverse-proxy like a GCLB.

In the case of a GCLB, or any HTTP reverse-proxy / load-balancer, that would be in front of the ingress-gateway, this Load-balancer would terminate TCP/SSL and would reverse-proxy requests.
Among many thing this proxy is responsible for settings `X-Forwarded-For` and `X-Forwarded-Proto`.

I would like to be able to instruct the istio-ingressgateway to trust this loadbalancer and to use those headers as-is.
My understanding is that all this could be achieved by settings `use_remote_address: true` on the istio-ingressgateway, however this is not possible via the `gateway` object or any other means of configuration right now.

The closest option to a working solution is to use an EnvoyFilter but there seems to be a bug in the merging behavior of fields of type `BoolValue` (cf : #18169 )

**Comment by lambdai** [comment]
@fcantournet 
GCLB
I am investigating the another GCLB XFF/XFP issue. What I have found iss that X-F-P is not trusted when use_remote_address is true.
1. Can you confirm that use_remote_address is set to false? I am running 1.3.3 and use_remote_address is set to true by default. 
2. What is your istio version?

**Comment by fcantournet** [comment]
I run istio 1.3.2 & 1.3.3
I cannot set use_remote_address to false on the ingress gateway. 
I tried via an envoy filter but there seems to be a bug in the merging cf #18169

There was a pull request https://github.com/istio/api/pull/897
Here that would have made it configurable via the gateway object but it was closed in favor of envoy filters. I'm not really able to evaluate the reason but it seemed that it was coherent with the overall approach of envoy filter for everything. Maybe @rshriram can shed light on this.

Feel free to ping me for additional information

**Comment by fcantournet** [comment]
I also tried to set it to false via the helm chart but there is no way 
If I had to choose I'd rather do it via a object .
If envoy filters are the way to go why not but I think we should take into account that envoy filters come with no backward compatibility garantees at the moment.

My point of view is that this use case is fairly common and should be supported. So I hope the solution is stable and doesn't involve massive changes at each istio release.

**Comment by lambdai** [comment]
> I cannot set use_remote_address to false on the ingress gateway.

Could you explain what is your goal?
My understanding your istio-ingressgateway is behind GCLB and you want to use the X-Forwarded-Proto provided by GCLB. Why set "use_remote_address" to false?

**Comment by fcantournet** [comment]
Because currently envoy rewrite the X-forwarded-for and x-forwarded-proto
and my understanding is that this is because use_remote_address is set to
true.

Le lun. 28 oct. 2019 à 21:54, Yuchen Dai <notifications@github.com> a
écrit :

**Comment by lambdai** [comment]
OK, we have the same goal that adopting the X-F-P from GCLB. 
I am built a experimental proxy to verify my fix. Will update tomorrow

**Comment by fcantournet** [comment]
This commit in envoy is of interest : https://github.com/istio/envoy/commit/b2da45af1c86efc5056b8eb8f18644954be43809

With this Envoy will keep the x-forwarded-proto if `xff_trusted_num_hops > 0`.
This commit is only on the `release-1.4` branch of istio/envoy.

**Comment by fcantournet** [comment]
https://github.com/istio/istio/issues/7607#issuecomment-490027057

For reference about trusting an external load-balancer for X-F-x headers

**Comment by fcantournet** [comment]
@lambdai FYI with commit b2da45a in envoy, which is available in istio 1.4+ we have what we need for running istio's ingress-gateway behind a trusted LB.

setting `xff_trusted_num_hops ` appropriately is sufficient now & can be done with a simple envoyfilter.
We get proper `x-forwarded-*` headers and envoy's internal variables for downstream address are good too.

**Comment by lambdai** [comment]
@fcantournet Thank you for the sharing. 
Close this since istio-ingressgateway could solve it with simple config now.

**Comment by Arpeet-gupta** [comment]
https://blog.opstree.com/2020/04/07/preserve-source-ip-in-aws-classic-load-balancer-and-istios-envoy-using-proxy-protocol/

**Comment by NickScottKortical** [comment]
@lambdai Hi, from this discussion it sounds like you managed to get a GCLB working infront of the istio ingress gateway, im trying to achieve something similar (i think), where i would like to host my GCLB outside of GKE and my ingress gateway within a cluster, and then have encrypted traffic between the loadbalancer and the gateway. Currently i have managed to get https to the LB then http between LB and gateway working and then mtls inside the cluster, and equally i have had https directly to the cluster working as well (without the GCLB), however i am struggling to get the setup working where the traffic between the GCLB and the gateway is encrypted as i seem to just get 502 Server errors. Do you know any documentation or tips for getting this working?

**Comment by brettcurtis** [comment]
@NickAJScott - did you happen to figure this one out? I've had all the exact same scenarios working as you but failing to get GCLB -> TLS -> Gateway 443 node port.
