### ISSUE TITLE
Reduce RBAC scope: Role instead of ClusterRole for Operator Controller

### ISSUE THREAD

**Issue by kramvan1** [istio/istio#18319]
**Describe the feature request**

The default for the Operator controller was switched to use Cluster roles. 
https://github.com/istio/operator/pull/356/files

Roles should be used to reduce the namespace scope for the operator controller. 
For installing Istio into single namespace (istio-system)  Roles could be used instead of ClusterRoles for that namespace only.

One option could be to provide both yamls and only use the ClusterRole if asked for.

**Describe alternatives you've considered**

**Additional context**

**Comment by linsun** [comment]
@kramvan1  I agree, we should not give more permission than the operator actually needs.  one question, if we reduce to role, how do you know which namespace it should grant the role binding?  (current it is set to istio-operator but it is fine since it is cluster role binding.)   I asked because we don't know which namespace user will be installing istio to.

**Comment by linsun** [comment]
cc @sdake @ostromart @richardwxn

**Comment by kramvan1** [comment]
Will control the namespace and Roles via the OLM CSV.

**Comment by brianwolfe** [comment]
@linsun we just ran into this when checking if we could migrate to use the operator. We kind of balked when we saw that the istio operator would ask for admin privileges over all pods in the cluster.

Would it make sense to have a reduced access configuration for the operator itself in this install situation? The Jaeger operator, for instance: https://www.jaegertracing.io/docs/1.18/operator/#install-modes appears to permit this sort of install. In this mode, we could still create the same role, but not the ClusterRoleBinding. When applying the Istio CR in this mode, we could also apply a RoleBinding alongside it to bind the operator role in this namespace.

This would make our security audit go a bit more smoothly. Granting whole-cluster admin isn't really going to work out for us.

If this sort of makes sense, I can put together a more complete proposal for the environments WG.

**Comment by sdake** [comment]
@brianwolf there is a [multitenancy RFC](https://docs.google.com/document/d/1dmLZf_8lKkj4MozR9mk7J0ZhtMHiBda36CLh7xuc6E4/edit#heading=h.xw1gqgyqs5b)underway. Your specific requirement can be addressed as part of this RFC. Please review and add appropriate content.

Cheers,
-steve
