### ISSUE TITLE
Inconsistent behavior when ports aren't following the naming conventions

### ISSUE THREAD

**Issue by jpkrohling** [istio/istio#18329]
**Bug description**

When the Kubernetes `Service` resource in front of a deployment is exposing a port that doesn't follow the naming conventions, ingress spans aren't being created. I would expect *egress* spans to also not be created. Currently, egress spans are being created, but not ingress spans, which seems inconsistent to me.

Documentation reference: https://istio.io/faq/distributed-tracing/#no-tracing

> ... confirm that your ports conform to the Istio 
**Expected behavior**

Either no egress nor ingress spans should be created, or both types of spans should be created.

**Steps to reproduce the bug**

I can consistently reproduce it with this script, replacing lines 100-116 with `kubectl expose deployment ${app_name}`:
https://github.com/jpkrohling/devoxx19-demo/blob/1cdb4a35dd7395a99da8c9c041d8d0b459160fb4/script.sh

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Istio: 1.3.3
Kubernetes: v1.15.2

**How was Istio installed?**
```
for i in install/kubernetes/helm/istio-init/files/crd*yaml; do kubectl apply -f $i; done
kubectl apply -f install/kubernetes/istio-demo.yaml
```

**Environment where bug was observed (cloud vendor, OS, etc)**
minikube

**Comment by howardjohn** [comment]
In 1.3 we introduced a new protocol detection feature. We found some issues with this on inbound traffic, so right now this one works for outbound traffic. In the very new feature it will work everywhere

**Comment by jpkrohling** [comment]
Thanks for the clarification! Would it be worth documenting this behavior, until the new feature is made available? I spent quite a few hours today trying to figure out what was wrong :-)

**Comment by howardjohn** [comment]
@jpkrohling sorry if the docs aren't super clear here, the problem is up until a few days before the release we intended it to be fully enabled so had written some of the docs as such - we may have missed some updates. Its very subtly mentioned in https://istio.io/news/2019/announcing-1.3/#intelligent-protocol-detection-experimental but we should be more explicit

**Comment by jpkrohling** [comment]
Sounds good. We have a [PR opened](https://github.com/jaegertracing/documentation/pull/317) for the Jaeger documentation, but it might indeed belong to Istio's FAQ instead. 

@objectiser: would you be able to convert that PR into a PR for the Istio's documentation?

**Comment by objectiser** [comment]
Will take a look.
