### ISSUE TITLE
Jwt filter supports mapping multi issuers to one jwks

### ISSUE THREAD

**Issue by luxianlong** [istio/istio#18326]
**Describe the feature request**
In many multi-tenant senario,  jwt tokens with different issuers just use the same jwks. For example, when integrated with AAD, the jwks always be https://login.microsoftonline.com/common/discovery/keys

Current jwt filter config just make one issuer to an jwks URI. It can not support mutli-tenant system well.

I thinks the issuer paramater can support regex match or there is a defaut jwks will be OK. 
Thank you.

**Describe alternatives you've considered**

**Additional context**

**Comment by luxianlong** [comment]
Is there any suggestion about this issuer?

**Comment by incfly** [comment]
we know supports multi issuer in request authn api released as of 1.5.
https://github.com/istio/api/blob/master/security/v1beta1/request_authentication.proto

feel free to reopen as gap you see.

**Comment by luxianlong** [comment]
Thanks a lot.
But there is still a gap to my scenario. For example,  my issuer is something like 
"https://sts.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47/". In a multi-tenant system, different tenant has a different suffix.
