### ISSUE TITLE
Istio pods are running but not ready after installation with Calico

### ISSUE THREAD

**Issue by Wihrt** [istio/istio#18324]
**Bug description**
Istio pods after installation are running but are not ready

**Expected behavior**
All pods are running and ready

**Steps to reproduce the bug**
1. Deploying K8S cluster using KubeSpray
2. Installing Istio without Helm following this [procedure](https://istio.io/docs/setup/install/kubernetes/#installation-steps)

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```bash
root@master:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

```bash
root@master:~# ./istio-1.3.2/bin/istioctl version --remote
client version: 1.3.2
citadel version: 1.3.2
egressgateway version: 1.3.2
galley version: 1.3.2
ingressgateway version: 1.3.2
pilot version: 1.3.2
sidecar-injector version: 1.3.2
Error: 2 errors occurred:
        * error execing into istio-policy-6bf887bb5b-f7rlt mixer container: unable to upgrade connection: container not found ("mixer")
        * error execing into istio-telemetry-6bf94f9d46-m85ck mixer container: unable to upgrade connection: container not found ("mixer")
```

**How was Istio installed?**
Istio was installed following this [procedure](https://istio.io/docs/setup/install/kubernetes/#installation-steps)
I have modified the ingress-gateway service to be a NodePort instead of a Load Balancer

**Environment where bug was observed (cloud vendor, OS, etc)**
The cluster has been deployed on OpenStack VMs using KubeSpray.
Spec of each node

| Name   | vCPU | RAM (Go) | Disk (Go) | OS           |
| ------ | ---- | -------- | --------- | ------------ |
| master | 8    | 16       | 60        | Ubuntu 16.04 |
| node1  | 4    | 8        | 60        | Ubuntu 16.04 |
| node2  | 4    | 8        | 60        | Ubuntu 16.04 |

[istio-dump.tar.gz](https://github.com/istio/istio/files/3771475/istio-dump.tar.gz)
[debug_archive.zip](https://github.com/istio/istio/files/3771355/debug_archive.zip)
I provided all the other informations you needed and I added the pod status + the cluster-info dump

**Comment by Wihrt** [comment]
We have deployed another cluster but with Weave instead of Calico for the networking part
The installation is just going fine

So Istio + Calico seems to not work. Is there a configuration to do in order to make it work ?

**Comment by howardjohn** [comment]
`019-10-25T09:19:35.880734Z     info    Configuration not synced: first push for [istio/networking/v1alpha3/destinationrules] not received` Galley is not sending Pilot the Destination Rule? but the CRD exists on the cluster which is weird

**Comment by Wihrt** [comment]
I can try to deploy Istio on a kubeadm deployed cluster and see if I have the same behavior ?
