### ISSUE TITLE
Move setup_perf_cluster_for_tests.sh to another repo

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#18334]
This test has no reason at all to be in istio/istio. It should probably be in istio/tools.

The motivation here is that we are no longer running ANY tests in istio/istio on Boskos, so I want to cleanup all of the boskos junk in the repo. We should move this out to where-ever appropriate (maybe http://github.com/istio/tests)

**Comment by richardwxn** [comment]
Actually there are two perf related tests in istio/istio now, one is setup_perf_cluster_for_tests.sh you pointed out, which I believe the test result is not used any where now, another one is perf_benchmar_test.sh which serves as entry for benchmark testing in tools repo now.

So I think we can remove the setup_perf_cluster_for_tests.sh and move the perf_benchmar_test.sh to tools repo?

**Comment by howardjohn** [comment]
Yeah everything can be moved. At some point there is some `setup_e2e` function that calls a bunch of stuff related to mason and boskos -- all of that can be moved out since istio/istio is not using it at all.

**Comment by richardwxn** [comment]
- [ ] Move perf related jobs to tools(remove from istio/istio)
- [ ] Add boskos setup to tools
- [ ] Update test-infra jobs to pointing to new jobs path
- [ ] Move other periodic jobs out from istio/istio?, e.g. upgrade

lastly:
if things goes well: - [ ] remove any boskos and mason setup related stuff from istio/istio

**Comment by howardjohn** [comment]
@richardwxn current status of this is we just need to move `prow/upgrade-tests.sh` over?

**Comment by richardwxn** [comment]
@howardjohn yep the only pending piece is upgrade test. But I am still thinking what it should goes to, istio/tools maybe since we already have the boskos setup stuff there?

**Comment by howardjohn** [comment]
@richardwxn I think tools makes sense. Logically, its where we have all of our large scale/benchmark/periodic tests, so this is consistent with that. And it has the boskos stuff, so makes sense code wise as well

**Comment by richardwxn** [comment]
all the pending tasks were done already
