### ISSUE TITLE
istioctl manifest testing: security

### ISSUE THREAD

**Issue by ostromart** [istio/istio#18345]
istioctl will be the default installation method for 1.4 onwards. We need to verify that the Istio installed using istioctl manifest apply works with the following tasks:

https://preliminary.istio.io/docs/tasks/security/

**Comment by ostromart** [comment]
Note: tests should be done with version that has #18342.

**Comment by howardjohn** [comment]
Assigned @pitlv2109 who has been working on running through the tasks with istioctl - can you provide any info on what works and any issues?

**Comment by ostromart** [comment]
Closing this, since security team went though the tasks and all issues were resolved in release (except SDS profile).
