### ISSUE TITLE
Certificate GetWaitTime() has an overflow bug

### ISSUE THREAD

**Issue by lei-tang** [istio/istio#18359]
**Bug description**
The following code in GetWaitTime() has an overflow bug (e.g., when cert.NotAfter.Sub(cert.NotBefore) = time.Hour * 90000, gradePeriod becomes a negative number due to the overflow).

gracePeriod := cert.NotAfter.Sub(cert.NotBefore) * time.Duration(cu.gracePeriodPercentage) / time.Duration(100)

**Expected behavior**
No overflow should occur.

**Steps to reproduce the bug**
Run the following test program and observe the negative time due to the overflow.
~$ go run main.go
gracePeriod (90000h0m0s * 0.000000) = -6240h57m20.737095516s is less than minGracePeriod 10m0s. Apply minGracePeriod.

package main

import (
	"fmt"
	"time"
)

func main() {
	gracePeriodPercentage := 50
	certLifeTime := time.Hour * 90000
	minGracePeriod := 10 * time.Minute

	// The following case will overflow:
	gracePeriod := certLifeTime * time.Duration(gracePeriodPercentage) / time.Duration(100)
	
	if gracePeriod < minGracePeriod {
		fmt.Printf("gracePeriod (%v * %f) = %v is less than minGracePeriod %v. Apply minGracePeriod.\n",
			certLifeTime, float64(gracePeriodPercentage/100), gracePeriod, minGracePeriod)
		gracePeriod = minGracePeriod
	} else {
		fmt.Printf("gracePeriod (%v * %f) = %v\n",
			certLifeTime, float64(gracePeriodPercentage/100), gracePeriod)
	}
}

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Istio 1.4

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
Done https://github.com/istio/istio/pull/18362
