### ISSUE TITLE
ServiceEntry Resolution update fails with EDS ACK Errors

### ISSUE THREAD

**Issue by ramaraochavali** [istio/istio#18355]
**Bug description**
When a ServiceEntry's Resolution Type is updated from `STATIC` to `DNS` after it is created, Pilot generates "ads	ADS:EDS: ACK ERROR ", leading to inconsistent proxy state across the mesh - Endpoints across the mesh have different endpoints because further eds pushes fail with the ACK errors.

The proxies generate the error error_detail:<code:13 message:"malformed IP address: somevip.force.com. Consider setting resolver_name or setting cluster type to 'STRICT_DNS' or 'LOGICAL_DNS'" > 

**Expected behavior**
Update of ServiceEntry (including Resolution) should either work correctly or a validation should prevent from updating the Resolution if it is not easy to support. Mesh Proxy state should be consistent.

**Steps to reproduce the bug**

1. Create a ServiceEntry with Resolution as `STATIC` with fully resolved IPAddresses as end points.
2. Let it propagate to the mesh.
3. After the same ServiceEntry with Resolution as 'DNS' and add a new DNS Address to the existing end points
4. After this, EDS push to any new proxy connections will fail with above error, existing proxies EDS push also fails.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
Master 

**How was Istio installed?**
Helm

**Environment where bug was observed (cloud vendor, OS, etc)**
Local DCs

**Comment by ramaraochavali** [comment]
Attached is the Pilot log from our test cluster where I tested this - If it helps. `invalid-service-entry` is the one which was causing the problem. Ignore the first few CRD create/update failures on it because was trying if we set resolution as STATIC add DNS endpoints, if validation catches or not. Those logs are for that part of the test.
[pilot_logs.zip](https://github.com/istio/istio/files/3774473/pilot_logs.zip)

**Comment by ramaraochavali** [comment]
Looking at the code, I think I see what is going on here. The full push is happening correctly on service entry update. When full push happens, we call cds, eds, lds and routes. When pushEds is called here
https://github.com/istio/istio/blob/master/pilot/pkg/proxy/envoy/v2/ads.go#L551

the `pushEds` function is looping through all the clusters in the connection and preparing endpoints https://github.com/istio/istio/blob/master/pilot/pkg/proxy/envoy/v2/eds.go#L640 - I guess the clusters list only populated by Envoy sends endpoint requests here https://github.com/istio/istio/blob/master/pilot/pkg/proxy/envoy/v2/ads.go#L367.

Since this cluster type has changed, I think we need to the cluster should go away from the con.Clusters some how - otherwise this problem will come.

I think either we should remove this cluster from `con.Clusters` because it is no more an EDS cluster or cross check with the service resolution here https://github.com/istio/istio/blob/master/pilot/pkg/proxy/envoy/v2/eds.go#L600 and just return nil.

@rshriram @hzxuzhonghu  - Does the above make sense to you?

**Comment by ramaraochavali** [comment]
I have a pushed to to fix with Option 2 (which is safe). Added a test that validates the behaviour - before my fix, eds pushes happen with DNS endpoint and after the fix they stopped.

**Comment by hzxuzhonghu** [comment]
@ramaraochavali The log below shows the SE is invalid.
```
protocol:"GRPC" name:"grpc-7443" > location:MESH_INTERNAL resolution:STATIC endpoints:<address:"somevip.force.com" ports:<key:"grpc-7443" value:7443 > labels:<key:"app" value:"app" > > endpoints:<address:"10.252.224.146" ports:<key:"grpc-7443" value:7443 > labels:<key:"app" value:"app" > > endpoints:<address:"10.252.224.148" ports:<key:"grpc-7443" value:7443 > labels:<key:"app" value:"app" > > endpoints:<address:"10.252.224.149" ports:<key:"grpc-7443" value:7443 > labels:<key:"app" value:"app" > > }, error: somevip.force.com is not a valid IP
```

I think u haven't use mcp yet. And the cause is that in `pilot/pkg/config/kube/crd/controller/controller.go`, and  we can find that in `Get`/`List` function, the configs are not cached and get from k8s apiserver directly, but without validation. The validation only applies to informer. That is to say the previous validation is not complete and the performance is bad.

**Comment by ramaraochavali** [comment]
@hzxuzhonghu As I noted in the https://github.com/istio/istio/issues/18355#issuecomment-546569682 - that was intentional test to ensure pilot is actually validation an invalid service entry. After that I actually tested with valid service entries - like service entry with STATIC resolution and endpoints as IPs - then Pilot processes it correctly. After that I updated the service entry resoluition to DNS and added a DNS endpoint - then it fails with the above exception. So I think validation in service entry is not a problem

**Comment by hzxuzhonghu** [comment]
If both ses are valid, i am not sure why eds nacked. I understand we push cds->eds in orders.

**Comment by ramaraochavali** [comment]
eds nacked because, when we do a full push, edsPush is looking at con.Clusters (which are eds clusters) and pushing endpoints for the clusters in that list. The service entry before update to DNS was in that list and pushed. But the service entry is actually updated to DNS. The con.Clusters list only updated again after envoy sends back eds request for cds push. But eds push happens before that in a full push case. Please see the test case in the PR - It explains why it is pushing.

**Comment by hzxuzhonghu** [comment]
Now i got it. The scenario does exist. I didnot know that envoy validate eds still considering cds.

**Comment by ramaraochavali** [comment]
Yeah, Envoy would consider endpoint updates to existing active cluster while a cluster update (cluster warming) is in progress because - cluster could warmed for a variety of reasons.

**Comment by hzxuzhonghu** [comment]
make sense

>I guess - setting con.Clusters at the env of pushCds is the right approach because we know what we have sent rather than relying on Envoy to send them back in EDS request.

looks this way is better, this is less costly. Reduce an additional eds request?

**Comment by ramaraochavali** [comment]
> looks this way is better, this is less costly. Reduce an additional eds request?

It does not reduce any EDS request AFAICT. But would be cleaner. My hesitation is regression risk - We do have logic here https://github.com/istio/istio/blob/master/pilot/pkg/proxy/envoy/v2/ads.go#L344 which has been working for a while - So not 100% sure of regression risks. That is why I chose the second approach which is safe.
