### ISSUE TITLE
ingressgateway 503 during istio upgrade 1.3.1 -> 1.3.2 and rollback 1.3.2 ->1.3.1

### ISSUE THREAD

**Issue by carolynhu** [istio/istio#18369]
To reproduce: 
local run [test_crossgrade.sh](https://github.com/istio/istio/blob/master/tests/upgrade/test_crossgrade.sh)

Internal traffic sent by fortio batch job `cli-fortio` report:
```
E 2019-10-28T02:34:47.076488979Z Code 200 : 4960 (99.4 %)
E 2019-10-28T02:34:47.076492533Z Code 503 : 32 (0.6 %)
```
Also, when external traffic sending in background mode when upgrade and rollback.  Fortio job will never complete:
For example: we are running this command: `fortio load -c 32 -t 500s -qps 10 -timeout 30s -H Host:echosrv.test.svc.cluster.local http://35.188.202.161:80/echo?size=200`, which should finish after 500 seconds, if it fails, there should be some retries. However, the job got stuck there with log: `Waiting for external traffic to complete...`

**Comment by carolynhu** [comment]
cc @elfinhe @ostromart

**Comment by elfinhe** [comment]
@carolynhu can you paste more logs around the 503 errors?

**Comment by lambdai** [comment]
I am seeing all kinds of failure 

```
23:51:16 E http_client.go:542> Unable to connect to 35.193.58.225:80 : dial tcp 35.193.58.225:80: connect: no route to host
23:53:59 I http_client.go:648> Closing dead socket &{{0xc000754a00}} (err read tcp 10.138.0.60:54618->35.193.58.225:80: read: connection reset by peer at firs
t read)                                                                                                 
23:55:55 I http_client.go:648> Closing dead socket &{{0xc0007b8400}} (err EOF at first read)                                                                 
23:55:55 I http_client.go:648> Closing dead socket &{{0xc0002a2900}} (err EOF at first read)     
23:58:01 W http_client.go:695> Parsed non ok code 503 (HTTP/1.1 503)                                                                                          
```
Will investigate

**Comment by lambdai** [comment]
The top priority is 503. 
I see http 503 errors as long as I restart dataplane in 1.3 series.

@carolynhu  Could you add another test case as upgrading from 1.2.4 to 1.2.8? If we see 503 in this case, it is not a pure 1.3.X issue.

**Comment by lambdai** [comment]
@carolynhu  https://prow.istio.io/?type=periodic&job=istio-upgrade-using-helm* this is great!

**Comment by lambdai** [comment]
503 occurs only on internal fortio client where no sidecar is provided. The fortio server could be shutdown before its sidecar envoy and sidecar has to respond fortio envoy with 503.  To eliminate it either
1. fortio server catch SIGTERM and live longer than its sidecar envoy
2. attach sidecar envoy to fortio client so that let client sidecar to retry.

**Comment by lambdai** [comment]
2 is the reason why external traffic doesn't see 503: istio-gateway acts as the sidecar of external fortio client

**Comment by lambdai** [comment]
Close for now. Please reopen if you see different kinds of failure

**Comment by carolynhu** [comment]
@lambdai We set the maximum % of 503 to be 15, which is safe now. Since most of our upgrade tests have a failure rate under 1%.

**Comment by carolynhu** [comment]
@lambdai also, 1.2 job have same error, which identifies that this is not only occurred in 1.3. I'm going to remove 1.2 job.
