### ISSUE TITLE
gRPC implementation for EDS 

### ISSUE THREAD

**Issue by gnirodi** [istio/istio#1836]
New plan: simple EDS implementation. Will revisit / open separate (possibly post 1.0) issue for the 
full sync.
-----

Design doc reference: https://goo.gl/AQARBs#heading=h.w0gvaaiugqls

On the lines of: https://github.com/gnirodi/pilot/blob/hybrid-multi-cluster/bridge/mesh/poller.go

Difference:
Let's spin up gRPC servers / clients instead of REST

Basic capabilities:
- Spin up as many pollers as the number of remote clusters (shut down unwanted ones etc...)
- Fetch endpoints from remote MSAs using zone as a filter and consolidate with in-memory global view
- Pilot will use the same EDS to fetch endpoints. Only it will not filter by whatever labels (service label being the minimum)
- Maintain stats to show on the status page

**Comment by gnirodi** [comment]
@baodongli @sdake @john-a-joyce just indicating that I've begun work on this. 

I have some skeletal code at https://github.com/istio/istio/compare/master...gnirodi:multi-cluster-p2p?expand=1

**Comment by sdake** [comment]
@gnirodi cool - I missed this in my email to the ML related to the questions I had about next steps for multicloud from the existing design document.  How does this relate to https://github.com/istio/istio/issues/1836 and https://github.com/istio/istio/issues/1837?

**Comment by sdake** [comment]
@costinm I think this work is merged, and may not be necessary for 1.0.  Can you confirm by closing.  If necessary we can open a new issue to sort out multicloud post 1.0.
