### ISSUE TITLE
Let Citadel generate additional SAN in its certificates

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio#18370]
**Describe the feature request**

Let Citadel generate an additional SAN in the certificates it generates, for example in the form: `serviceAccount.Namespace.[somesuffix]` with `some_suffix` configurable.

**Describe alternatives you've considered**

The alternative is to mount separate DNS certificates for *.example.com and manage two types of certificates: DNS and SPIFFE ones.

**Additional context**

See discussion https://docs.google.com/document/d/1mkVBUSY86h4mX5A9StX0T2u3xvLV3dYv0HFwYTBxyh0/edit?disco=AAAADtS_ZMs

**Comment by vadimeisenbergibm** [comment]
The use case: integrate Citadel with an external CA, let's say of an organisation with domain example.com. Citadel will generate CSRs for certificates with DNS SAN serviceAccount.namespace.clustername.example.com in addition to the SPIFFE SANs.

Citadel will send the CSRs to the CA of example.com for signing. The certificates can be used both for intra-mesh communication by the means of SPIFFE SANs, and also for inter-mesh and communication with legacy inside the organisation by the means of DNS SANs.

Integration of Citadel with an external CA is described in https://docs.google.com/document/d/1IQJ2HAaf9m1JzQwtVLUvX3u0op63KJpCH2bNk65pP6c, "Delegated mode: Citadel acts as a registration authority (RA) for clients."

The existing clients will be able to access ingress gateways of the clusters by istio-ingressgateway-service-account.istio-system.cluster1.example.com URL, without any change.

**Comment by vadimeisenbergibm** [comment]
To check how it would work, generate certificates for httpbin.example.com, with a SPIFFE SAN:

1.  Create a root certificate and private key to sign the certificate for your services:

    ```
    openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:2048 -subj '/O=example Inc./CN=example.com' -keyout example.com.key -out example.com.crt
    ```

1.  Create an `openssl` configuration file for `httpbin.example.com`:

    ```
    cat > ./httpbin.example.com.conf <<EOF
    [ req ]
    encrypt_key = no
    prompt = no
    utf8 = yes
    default_md = sha256
    req_extensions = req_ext
    x509_extensions = req_ext
    distinguished_name = req_dn
    [ req_ext ]
    subjectKeyIdentifier = hash
    basicConstraints = critical, CA:false
    keyUsage = critical, digitalSignature, nonRepudiation
    extendedKeyUsage = serverAuth
    subjectAltName = critical, @san
    [req_dn]
    O=httpbin example Inc.
    [ san ]
    URI.1 = spiffe://cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account
    DNS.1 = httpbin.example.com
    EOF
    ```

1.  Create a certificate and a private key for `httpbin.example.com`:

    ```
    openssl req -out httpbin.example.com.csr -newkey rsa:2048 -nodes -keyout httpbin.example.com.key -reqexts req_ext -config ./httpbin.example.com.conf
    openssl x509 -req -days 365 -CA example.com.crt -CAkey example.com.key -set_serial 0 -in httpbin.example.com.csr -out httpbin.example.com.crt -extensions req_ext -extfile ./httpbin.example.com.conf
    ```

1.  Test the certificate as part of [Istio Ingress HTTPS task](https://istio.io/docs/tasks/traffic-management/ingress/secure-ingress-mount/).

**Comment by vadimeisenbergibm** [comment]
cc @costinm, for 1.5, following our discussion in https://docs.google.com/document/d/1mkVBUSY86h4mX5A9StX0T2u3xvLV3dYv0HFwYTBxyh0/edit?disco=AAAADtS_ZMs .

**Comment by incfly** [comment]
Adding additional SANs into certificate is very security sensitive topic. I don't think we are heading towards that direction.

302 to @myidpt and closing, feel free to followup with reopen.
