### ISSUE TITLE
New test, TestBuiltinResourceWithWatcherEnabled, is flaky

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#18385]
https://prow.istio.io/view/gcs/istio-prow/logs/unit-tests_istio_postsubmit/509

@vikaschoudhary16 can you take a look at this, looks like you introduced the test

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18310/unit-tests_istio/3356

Please take a look, bumping to P0

**Comment by vikaschoudhary16** [comment]
sure, taking a look!

**Comment by vikaschoudhary16** [comment]
I could not reproduce it in my local environment despite running the galley tests ~20-25 times. 

In the failure case, default timeout of 1 sec happens before the `update` or `delete` could be picked up watcher. While trying to reproduce locally, i even tired with timeout as low as 500 ms but it worked all the time.

on the ci, last time it flaked on 31st october, https://prow.istio.io/view/gcs/istio-prow/logs/unit-tests_istio_postsubmit/557 

To narrow down the issue, created this [PR](https://github.com/istio/istio/pull/18630) with 2 secs as timeout. If still test flakes, will investigate on fsnotify side.

**Comment by howardjohn** [comment]
Using https://godoc.org/golang.org/x/tools/cmd/stress I can easily reproduce
