### ISSUE TITLE
Creating DNS for remote services 

### ISSUE THREAD

**Issue by gnirodi** [istio/istio#1838]
Design doc reference:  https://goo.gl/AQARBs#heading=h.b4jd2sur0ior

Key capabilities:
- Creates headless / selectorless service entries for services that only exist remotely
- Creates a service endpoint with IP addresses to enable Kube DNS to create appropriate entries

On the lines of: https://github.com/gnirodi/pilot/blob/hybrid-multi-cluster/bridge/mesh/agent.go#L169

**Comment by loewenstein** [comment]
@gnirodi Shouldn't DNS creation be part of the interface between Pilot and Environments?

The description here sounds pretty k8s specific...
