### ISSUE TITLE
Operator not cleaning up all control plane resources

### ISSUE THREAD

**Issue by kramvan1** [istio/istio#18384]
**Bug description**

When IstioControlPlane CR is removed, most of the control plane is removed.
There a few resources left over:
- Some secrets generated during the control plane use
- the control plane namespace itself (istio-system)

```
$ k get secret -n istio-system
NAME                                         TYPE                                  DATA   AGE
default-token-lr8bs                          kubernetes.io/service-account-token   3      13m
dns.istio-galley-service-account             istio.io/dns-key-and-cert             3      12m
dns.istio-sidecar-injector-service-account   istio.io/dns-key-and-cert             3      12m
istio-ca-secret                              istio.io/ca-root                      5      12m
istio.default                                istio.io/key-and-cert                 3      12m
```

**Expected behavior**

Resources created by the Operator for the control plane and their children resources are all cleaned up when the control plane/CR is removed. 

**Steps to reproduce the bug**

Install operator
Create istio control plane resource (CR)
Use the control plane (run basic smoke test)
Delete istio control plane resource
If the istio-namespace still exists, check what's left over in the istio-system namespace. Usually some secrets are left behind.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

1.4  and kube 1.16

**How was Istio installed?**

via operator CR

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by sdake** [comment]
@kramvan1 @irisdingbj pointed out a fix for this appears to have merged 4 days ago: https://github.com/istio/operator/pull/461

The original issue tracker was: https://github.com/istio/istio/issues/18031

**Comment by irisdingbj** [comment]
seems we left over above resources with latest master codes.

**Comment by kramvan1** [comment]
With operator image 582a from Nov 3, still seeing some left over secrets
```
$ k get secret -n istio-system
NAME                  TYPE                                  DATA   AGE
default-token-r5sgd   kubernetes.io/service-account-token   3      25m
istio.default         istio.io/key-and-cert                 3      8m29s
```

**Comment by linsun** [comment]
@irisdingbj thoughts on cleaning up the istio.default secret as part of the icp resource deletion for that given namespace?

not removing it is clearly causing us lots of issues as described in #19164.

**Comment by linsun** [comment]
I think the default-token-* for the namespace is fine to stay if that namespace stays.

**Comment by ostromart** [comment]
@irisdingbj @linsun is this still an issue? can we close?

**Comment by ostromart** [comment]
I'm going to close this as stale, please reopen if still relevant.
