### ISSUE TITLE
locality lb: support retry to another locality

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#18418]
Envoy changing priority during retries: https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/http_connection_management#arch-overview-http-retry-plugins

We should look into supporting this

**Comment by howardjohn** [comment]
@ckcd are you planning to implement this? I see the API got merged but I don't think the implementation

**Comment by ckcd** [comment]
@howardjohn 

sorry for the delay, I will send a PR this week.

**Comment by howardjohn** [comment]
Fixed by ^
