### ISSUE TITLE
benchmark test fail to run with telemetry v2 nullvm on both sidecar mode

### ISSUE THREAD

**Issue by richardwxn** [istio/istio#18411]
When running telemetry v2 nullvm setting on both sidecar mode, we are getting error message "Error: Aborting because error -1 for http://fortioserver:8080/echo?size=1024: ", need to investigate why.

Also data for nomixer on both sidecar mode seems not correct though.

@carolynhu @mandarjog

**Comment by lambdai** [comment]
I know most http load client would quit if the client/server has too many errors.

**Comment by richardwxn** [comment]
The issue was caused by using outdated envoyfilter url.  PR to update merged.
