### ISSUE TITLE
gRPC retry not work when server using SetHeader

### ISSUE THREAD

**Issue by elvizlai** [istio/istio#18423]
**Bug description**
Server side code example: 
```
func (s *ExperimentalService) Ping(ctx context.Context, req *hack.Empty) (*hack.ExperimentalPayload, error) {
        grpc.SetHeader(ctx, metadata.Paris("x-request-id", "mock-uuid"))

        // rand gen gRPC status 14 Unavailable
	if rand.Intn(5) == 3 {
		return nil, status.Error(14, "")
	}
        return &hack.ExperimentalPayload{}, nil
}
```

**Expected behavior**
Client call should retry when `Unavailable`. 
Remove  `grpc.SetHeader` in server side, the retry policy `works`!

**Steps to reproduce the bug**

https://github.com/grpc/grpc-go/blob/4ec516e58900fb35115553b525e0fb7eb29fd6e3/internal/transport/http2_server.go#L830-L834

the response header frame is separated when err occur.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
v1.2.8

**Comment by howardjohn** [comment]
@lambdai is this an Envoy bug?

**Comment by lambdai** [comment]
This is interesting. This might join the existing x-request-id with mock-uuid
