### ISSUE TITLE
The behavior of the istio-ingress-controller about HTTP2.0 to HTTP1.1

### ISSUE THREAD

**Issue by flyxiao2000** [istio/istio#1842]
Hi,
   My micro-service only support HTTP 1.1 , but the external client only supports HTTP2.0, can the istio-ingress-controller translate HTTP2.0 to HTTP1.1.
While i run the command "  curl --http2 -k -v https://<ingress node ip>:<ingress node port>/httpsvcistio"
I get information this communication fallback to HTTP1.1.

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: http-svc-istio 
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  tls:
  - secretName: istio-ingress-certs
  rules:
  - http:
      paths:
      - path: /httpsvcistio
        backend:
          serviceName: http-svc-istio
          servicePort: 80
  
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: http-svc-istio
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: http-svc-istio
    spec:
      containers:
      - name: http-svc
        image: gcr.io/google_containers/echoserver:1.8
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: http-svc-istio
  labels:
    app: http-svc-istio
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: http-svc-istio

**Comment by geeknoid** [comment]
Please ask questions on the public forums. See [here](https://istio.io/community) for info.
