### ISSUE TITLE
`istioctl analyze` should flag sidecar restarts

### ISSUE THREAD

**Issue by Shnatsel** [istio/istio#18428]
**Describe the feature request**

It is a fairly common occurrence for Istio sidecars to run out of memory, be killed and restarted. This results in various networking issues that are not obvious how to debug.

`istioctl analyze` should flag presence of restarts for Istio sidecar containers. Simply flagging their presence is good enough for an MVP since the logs for the individual container should explain what's happening (OOM, segfault, etc).

**Describe alternatives you've considered**

- Spread knowledge about the issue through documentation. This is strictly inferior to an automated analyzer for an issue that's so easy to detect.
- Write a bespoke shell script to check for sidecar restarts. This works, but would not be bundled with Istio by default, limiting its audience.

**Comment by howardjohn** [comment]
In Istio 1.4 when sidecar restarts the whole container will restart, so you can use standard kubernetes tooling (metrics, `kubectl get pod`, etc) to figure this out. I think this is outside the scope of istioctl. `kubectl get pod` will show OOMKilled now.

**Comment by Shnatsel** [comment]
So starting with 1.4 it should be impossible to get into a state where the sidecar container restarts but the pod does not? I feel it would still be useful for diagnosing earlier versions of Istio, and not produce any false positives in 1.4 and later, but I understand if this is out of scope.

**Comment by esnible** [comment]
I'd like to add printing istio-proxy restarts to `istioctl x describe`.

The Analyze framework **does** have the information when `--use-kube` is selected.  I did an experiment to count restarts on my own system.

```
pod "sysdig-agent-kr6b7" container "sysdig-agent" restarted 31 times
pod "vpn-6f66f7ccd7-r5vk8" container "vpn" restarted 9 times
pod "sysdig-agent-8v8jp" container "sysdig-agent" restarted 46 times
```

@Shnatsel Do you think Analyze should flag only istio-proxy restarts, or app container restarts?
I think this should be INFO, not WARNING level.  What do you think?

How many restarts should Analyze tolerate before flagging a problem?  50?  10?  10/day?  (My sysdig pod that restarted 46 times has been running for 178 days).

cc @sushicw Can you weigh on on if you think runtime restarts are part of the domain of analyze?

**Comment by howardjohn** [comment]
my 2c - just because we can doesn't mean we should. We should not be reinventing kubectl, its a huge time/complexity sink. I do not think there is any demand for istioctl to tell you that your container has restarted (the original issue applies only to older versions)

**Comment by sushicw** [comment]
I tend to agree with John: this is on the edges of `analyze`'s scope at best, and the cost/benefit seems pretty unfavorable. 

I think something like this is better handled using metrics-oriented methods, which Analyze currently doesn't support (and is not a particularly good fit for).

**Comment by howardjohn** [comment]
I don't think we intend to add this into istioctl given its a kubernetes concern with many solutions already
