### ISSUE TITLE
Do I need to supply --set cni.enabled=true and --set cni.components.cni.enabled=true?

### ISSUE THREAD

**Issue by jwendell** [istio/istio#18439]
According to the new docs, to install CNI I must supply

`--set cni.enabled=true` and `--set cni.components.cni.enabled=true`

to `istioctl manifest apply`.

They sound redundant.

**Comment by ostromart** [comment]
Fixed in https://github.com/istio/operator/pull/522.

**Comment by jwendell** [comment]
@ostromart  Which one wins? The docs still mention both: https://preliminary.istio.io/docs/setup/additional-setup/cni/#installation

**Comment by jwendell** [comment]
Changed the docs: https://github.com/istio/istio.io/pull/5591
