### ISSUE TITLE
SignalFX depends on an incompatible license

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#18434]
@keitwb

The SignalFX adapter has a dependency on the sfxclient library, which depends on a few packages from github.com/juju, which uses a license that we can't use. We need to either get SignalFX to remove this dependency in their sfxclient library, or we need to remove the signalfx adapter code from our repo immediately in master and in the release-1.4 branch.

[ x] Policies and Telemetry

If someone from the signalFx team is unable to help, we will have to remove the code in 1.4.

**Comment by geeknoid** [comment]
RE: https://github.com/istio/istio/issues/18155

**Comment by keitwb** [comment]
Hi, you can remove the adapter from the tree, we have moved to the out of tree model. http://github.com/signalfx/signalfx-istio-adapter

Is it ok if out of tree adapters use an incompatible license?

**Comment by howardjohn** [comment]
@mandarjog what is the action here for 1.4? Remove the folder?

**Comment by douglas-reid** [comment]
@howardjohn i've sent a PR to `master` branch for this issue.
