### ISSUE TITLE
Manifest Yaml Files Need to Be Included in Install Archive

### ISSUE THREAD

**Issue by brian-avery** [istio/istio#18441]
**Describe the feature request**
Currently, the manifest install files aren't present in the install files. This leads to things like: 

```
$ istioctl manifest apply -f samples/pilot-k8s.yaml
```

from https://preliminary.istio.io/docs/setup/install/operator/ not working. We should include the YAML files in our release archive so that users can find them. 

**Describe alternatives you've considered**

**Additional context**

**Comment by sdake** [comment]
@howardjohn can you fix this defect in the packaging?  I think you are or maybe already have done thiis.

If not, please reassign to someone that can for 1.4 or un-assign.

**Comment by sdake** [comment]
Note docker.save should be functional and match that of the other repositories now so the containers can additionally be packaged.

Cheers
-steve

**Comment by howardjohn** [comment]
What files do you want where? Put everything in operator repo samples/ under samples/operator?

**Comment by brian-avery** [comment]
Looking through the istio.io docs, the only referenced file in the operator repo is samples/pilot-k8s.yaml. That said, these are all samples for the IstioControlPlane.

**Comment by sdake** [comment]
the `deploy` directory needs to be put somewhere.  `install/operator` would be a good target for that.

The directory you proposed seems good for samples.

Cheers
-steve

**Comment by howardjohn** [comment]
https://github.com/istio/release-builder/pull/54 adds deploy under install/kubernetes/operator/deploy and samples under samples/operator
