### ISSUE TITLE
Config fuzz test

### ISSUE THREAD

**Issue by lambdai** [istio/istio#18448]
We are hitting non-deterministic config multiple times. I contribute one.
I believe there could be more but we didn't catch only because it is not that destructive.

We should add fuzz test to catch the unknown cases. Maybe not all below are equally sensitive to deterministic config but it's good to have.

[ ] LDS
[ ] CDS
[ ] RDS
[ ] EDS

**Comment by lambdai** [comment]
Related PR and Issues

https://github.com/istio/istio/issues/18088

**Comment by howardjohn** [comment]
https://github.com/istio/istio/issues/14935

**Comment by howardjohn** [comment]
Lets track in #14935
