### ISSUE TITLE
Make it easier to run istioctl commands over multiple clusters in a mesh

### ISSUE THREAD

**Issue by ayj** [istio/istio#18457]
We should consider making it easier to run the same command over all clusters in a mesh. Today, running a kubectl/istioctl command for multiple clusters in a mesh can often result in something like the following.

```bash
for context in ${kubeconfig config get-contexts}; do
    istioctl manifest apply -f istio-${context}.yaml
done
```

This works so long as the list of clusters in the user's kubeconfig file(s) matches the list of clusters in the mesh. Users must keep this lists in sync, e.g. merging via `KUBECONFIG` env or `kubectl config` commands. 

We can minimally document a recipe to do this using existing tools. We could also add a helper function to istioctl that only emits cluster contexts for clusters in the mesh, e.g.

```bash
for context in ${istioctl x multicluster get-contexts -f deployment-model.yaml}; do
    // ... 
done
```

This PR presumes the existence of some client-side representation of a list of clusters. The current experimental multiple cluster commands use a single file containing multiple files. If additional

**Comment by esnible** [comment]
An admin user might have credentials into more than one mesh.  For example, _sales_ and _human-resources_.

I haven't tried this, but I imagine something like

```
SALES="cluster1 cluster2 cluster3"
HR="hrcluster4 hrcluster5"

for context in $SALES; do
   # or 'kubectl config use-context $context'
   istioctl --context $context manifest apply -f istio-${context}.yaml
done
```

Having _istioctl_ manage groups of contexts seems more difficult than doing it explicitly in _bash_.

**Comment by ayj** [comment]
I was thinking of this as a way to filter contexts for a specific mesh. For example, suppose we had a file that defined the mesh deployment model as such:

```
clusters:
  us-central-a_mc0:
    network: vpc0
  us-central-a_mc1:
    network: vpc0
  us-west-mc2:
    network: vpc1
```

The cluster name (i.e .`us-central-a_mc0`) corresponds to the context in the users kubeconfig file(s). Given the user already defined the list of clusters once, it seems a bit cumbersome to  manually redefine the same list as an environment variable.
