### ISSUE TITLE
Pilot DNS certificate provisioning possible timing issue

### ISSUE THREAD

**Issue by kramvan1** [istio/istio#18458]
Related #18456 

**Bug description**

[pilot.log](https://github.com/istio/istio/files/3786478/pilot.log)
[policy.log](https://github.com/istio/istio/files/3786479/policy.log)

There appears to be a possible timing issue for the Pilot certificate creation path.  I'm that during some deploy of the istio control plane (via the operator) the pods end up in this state:
```
$ k get pod -n istio-system
NAME                                     READY   STATUS              RESTARTS   AGE
grafana-7d7bfb9465-nmlj6                 1/1     Running             0          6h18m
istio-citadel-746dcdf6d8-7qb9c           1/1     Running             0          6h19m
istio-egressgateway-76d66dd648-dxnnn     0/1     Running             0          6h17m
istio-egressgateway-76d66dd648-wqrbm     0/1     Running             0          6h19m
istio-galley-54c6f7dc59-kvghq            0/2     ContainerCreating   0          6h19m
istio-ingressgateway-b558bffb4-5tk29     0/1     Running             0          6h17m
istio-ingressgateway-b558bffb4-czgmm     0/1     Running             0          6h19m
istio-pilot-8457fbd987-wbhjq             1/2     Running             0          6h18m
istio-policy-5979bf4bf8-b7w49            1/2     CrashLoopBackOff    135        6h18m
istio-sidecar-injector-88bcd45cf-bwlh2   0/1     ContainerCreating   0          6h19m
istio-telemetry-5bf87d4cbf-5t5vl         1/2     CrashLoopBackOff    135        6h18m
istio-tracing-64b6cd558d-79c2h           1/1     Running             0          6h19m
kiali-7fc7655ccd-hxgsv                   1/1     Running             0          6h19m
prometheus-7f48b4f597-6njcp              1/1     Running             0          6h18m
```

I'm see both galley and sidecar waiting for hung waiting for the DNS certificates to be created.
```
MountVolume.SetUp failed for volume "dnscerts" : secret "dns.istio-galley-service-account" not found
```
Telemetry is crashing with 
```
Liveness probe failed: Get http://172.30.28.81:15014/version: dial tcp 172.30.28.81:15014: connect: connection refused
```

It appears that there are dependencies between the pod startups because of where the certificates are created, that causes a cascade effect to hold up the control plane.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

release 1.4

**How was Istio installed?**

operator

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by kramvan1** [comment]
[galley.log](https://github.com/istio/istio/files/3786563/galley.log)

**Comment by lei-tang** [comment]
@kramvan1 Can you provide the steps to reproduce the problem?

**Comment by kramvan1** [comment]
[pilot-describe.log](https://github.com/istio/istio/files/3786568/pilot-describe.log)

**Comment by howardjohn** [comment]
Please provide the full pilot log and `kubectl get secrets -n istio-system`

**Comment by howardjohn** [comment]
There has always been dependency on ordering of control plane start up, this DNS certs does not change that. To me it looks like the certs just aren't created for some reason, which is why we need the logs

**Comment by kramvan1** [comment]
Pilot and Policy log are at the top of the issue description

**Comment by kramvan1** [comment]
@howardjohn the pilot  is in a hard retry loop with the log section as attached above.   The log has wrapped many times.

**Comment by lei-tang** [comment]
@kramvan1 Can you provide the steps to reproduce the problem?

**Comment by howardjohn** [comment]
`2019-10-30T14:35:48.185903Z     error   err when watching CSR domain-cluster.local-ns-istio-system-secret-dns.istio-galley-service-account: unknown (get certificatesigningrequests.certificates.k8s.io)`

**Comment by lei-tang** [comment]
@kramvan1 To reproduce the problem using the same commands, steps, and environment as yours, can you share the detailed commands, steps, and environments (cluster size, cpu, memory, etc) you use?

**Comment by kramvan1** [comment]
@lei-tang reproduction has been hard to do, it only seems to happen on slower clusters with smaller workers nodes.     As state above, this is just laying down the default profile icp with the operator, no other steps required.    Cluster is 1.16.

**Comment by lei-tang** [comment]
@kramvan1 Can you share the commands you run ("laying down the default profile icp with the operator")?

**Comment by sdake** [comment]
@lei-tang if it is helpful - it seems to possibly occur more often in overload conditions.

**Comment by lei-tang** [comment]
If the cluster is overloaded to the degree that there is no resource to create secrets containing certificates, the certificate provisioning problem in this issue is not a timing issue but a cluster out-of-resource problem.

**Comment by charlesguo404** [comment]
i have the same issue

```
2020-01-03T15:37:16.219188Z     error   err when watching CSR domain-cluster.local-ns-istio-system-secret-dns.istio-galley-service-account: unknown (get certificatesigningrequests.certificates.k8s.io)

2020-01-03T15:37:16.725862Z     error   failed to verify the certificate chain: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "Kubernetes")
2020-01-03T15:37:16.735614Z     error   failed to read signed cert. (domain-cluster.local-ns-istio-system-secret-dns.istio-galley-service-account): failed to verify the certificate chain: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "Kubernetes")
2020-01-03T15:37:16.738214Z     error   failed to delete CSR (domain-cluster.local-ns-istio-system-secret-dns.istio-galley-service-account): certificatesigningrequests.certificates.k8s.io "domain-cluster.local-ns-istio-system-secret-dns.istio-galley-service-account" not found
2020-01-03T15:37:16.738227Z     error   failed to clean up CSR (domain-cluster.local-ns-istio-system-secret-dns.istio-galley-service-account): failed to verify the certificate chain: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "Kubernetes")
2020-01-03T15:37:16.738232Z     error   failed to generate key and certificate for secret dns.istio-galley-service-account in namespace istio-system (error failed to verify the certificate chain: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "Kubernetes"))
2020-01-03T15:37:16.738235Z     error   error when upserting secret (dns.istio-galley-service-account) in ns (istio-system): failed to verify the certificate chain: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "Kubernetes")
2020-01-03T15:37:16.775598Z     info    Configuration not synced: first push for [istio/config/v1alpha2/httpapispecs istio/mixer/v1/config/client/quotaspecs istio/mixer/v1/config/client/quotaspecbindings istio/rbac/v1alpha1/servicerolebindings istio/rbac/v1alpha1/rbacconfigs istio/networking/v1alpha3/virtualservices istio/networking/v1alpha3/destinationrules istio/networking/v1alpha3/sidecars istio/authentication/v1alpha1/policies istio/rbac/v1alpha1/clusterrbacconfigs istio/security/v1beta1/authorizationpolicies istio/networking/v1alpha3/serviceentries istio/config/v1alpha2/httpapispecbindings istio/authentication/v1alpha1/meshpolicies istio/networking/v1alpha3/gateways istio/networking/v1alpha3/envoyfilters istio/rbac/v1alpha1/serviceroles] not received

```

**Comment by howardjohn** [comment]
@charlesguo404 what kubernetes platform are you on

**Comment by charlesguo404** [comment]
Bare metal

John Howard <notifications@github.com>于2020年1月3日 周五23:55写道：

**Comment by howardjohn** [comment]
What ca are you using to sign CSRs? There is an issue where we make an assumption that the same CA is used for that and service account tokens, which is true on most providers but may not be true for bespoke installs

**Comment by lei-tang** [comment]
@charlesguo404 Can you share the platform details and the steps to reproduce the problem?

**Comment by charlesguo404** [comment]
@lei-tang I setup from https://istio.io/docs/tasks/security/dns-cert/ tutorial

**Comment by howardjohn** [comment]
I think we are looking for how you set up your kubernetes. Specifically the certificates and cert signing

**Comment by charlesguo404** [comment]
this is my kubernetes certificates setup
```
ExecStart=/usr/local/bin/kube-apiserver \
  --advertise-address=172.16.10.10 \
  --allow-privileged=true \
  --anonymous-auth=false \
  --insecure-port=0 \
  --profiling=false  \
  --apiserver-count=3 \
  --audit-log-maxage=30 \
  --audit-log-maxbackup=10 \
  --audit-log-maxsize=100 \
  --audit-log-path=/var/log/audit.log \
  --audit-policy-file=/var/lib/kubernetes/audit-policy-minimal.yaml \
  --authorization-mode=Node,RBAC \
  --bind-address=0.0.0.0 \
  --client-ca-file=/etc/pki/trust/anchors/DevOps_CA.crt \
  --enable-admission-plugins=NamespaceLifecycle,NodeRestriction,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota,DenyEscalatingExec,MutatingAdmissionWebhook,ValidatingAdmissionWebhook \
  --enable-swagger-ui=true \
  --etcd-cafile=/etc/pki/trust/anchors/DevOps_CA.crt \
  --etcd-certfile=/etc/pki/minion.crt \
  --etcd-keyfile=/etc/pki/minion.key \
  --etcd-servers=https://172.16.10.22:2379,https://172.16.10.10:2379,https://172.16.10.21:2379 \
  --event-ttl=24h \
  --experimental-encryption-provider-config=/var/lib/kubernetes/encryption-config.yaml \
  --kubelet-certificate-authority=/etc/pki/trust/anchors/DevOps_CA.crt \
  --kubelet-client-certificate=/etc/pki/minion.crt \
  --kubelet-client-key=/etc/pki/minion.key \
  --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_GCM_SHA256 \
  --kubelet-https=true \
  --runtime-config=api/all \
  --service-account-key-file=/etc/pki/sa.key \
  --service-cluster-ip-range=10.24.0.0/16 \
  --service-node-port-range=30000-32767 \
  --tls-cert-file=/etc/pki/minion.crt \
  --tls-private-key-file=/etc/pki/minion.key \
  --requestheader-client-ca-file=/etc/pki/trust/anchors/DevOps_CA.crt \
  --requestheader-extra-headers-prefix="X-Remote-Extra-" \
  --requestheader-group-headers=X-Remote-Group \
  --requestheader-username-headers=X-Remote-User \
  --proxy-client-cert-file=/etc/pki/minion.crt \
  --proxy-client-key-file=/etc/pki/minion.key \
  --enable-aggregator-routing=true \
  --v=2
Restart=on-failure
RestartSec=5
LimitNOFILE=65536
[Install]
WantedBy=multi-user.target

```

**Comment by howardjohn** [comment]
I was expecting `cluster-signing-cert-file` to be different from the root ca but it's not, so maybe a different issue. @lei-tang can help debug further

**Comment by lei-tang** [comment]
@charlesguo404 The following error in the logs you attached ("failed to verify the certificate chain: x509: certificate signed by unknown authority") indicates that there is an error verifying the certificate chain. To debug this error, can you dump the entire certificate chain (the certificate chain dumping statements may be added near https://github.com/istio/istio/blob/master/security/pkg/k8s/chiron/utils.go#L304) and the certificate under /var/run/secrets/kubernetes.io/serviceaccount/ca.crt on a pod in your k8s cluster?

After you dump the entire certificate chain, you may use "openssl verify" command to verify the entire certificate chain and debug why the certificate chain verification failed.

**Comment by charlesguoooo** [comment]
@lei-tang I'm not a developer, i don't know how to do that, but i can provision the cert content.
```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 3381767933950975916 (0x2eee7404bff45fac)
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = CN, CN = Kubernetes, L = Beijing, ST = Beijing, O = 42devops, OU = DevOps
        Validity
            Not Before: Oct 18 10:10:25 2019 GMT
            Not After : Oct 15 10:10:25 2029 GMT
        Subject: C = CN, CN = Kubernetes, L = Beijing, ST = Beijing, O = 42devops, OU = DevOps
...
        X509v3 extensions:
            X509v3 Basic Constraints: critical
                CA:TRUE
            X509v3 Key Usage: critical
                Certificate Sign, CRL Sign
            X509v3 Subject Key Identifier:
                FC:73:0F:AA:4E:6A:01:D0:BC:15:80:0B:11:4B:A3:70:52:E2:14:ED
            X509v3 Authority Key Identifier:
                keyid:FC:73:0F:AA:4E:6A:01:D0:BC:15:80:0B:11:4B:A3:70:52:E2:14:ED
                DirName:/C=CN/CN=Kubernetes/L=Beijing/ST=Beijing/O=42devops/OU=DevOps
                serial:2E:EE:74:04:BF:F4:5F:AC

               

```

**Comment by lei-tang** [comment]
@charlesguo404 What is the certificate you attached? Is it the certificate under /var/run/secrets/kubernetes.io/serviceaccount/ca.crt on a pod in your k8s cluster?
Meanwhile, to debug the certificate chain verification error, the entire certificate chain and the certificate under /var/run/secrets/kubernetes.io/serviceaccount/ca.crt on a pod in your k8s cluster are needed.

**Comment by charlesguo404** [comment]
@lei-tang yes，It's the certificate /var/run/secrets/kubernetes.io/serviceaccount/ca.crt  on a pod.
I suspect it is because my service-account-private-key-file certificate is inconsistent with my tls certificate, i will try change this

**Comment by charlesguo404** [comment]
@lei-tang @howardjohn  Thanks support. As you said, I used a certificate different from root ca as cluster-signing-cert-file, so this kind of problem occurs.The DevOps_CA is a certificate signed by root ca.

**Comment by kramvan1** [comment]
Working better with istiod now.
