### ISSUE TITLE
Way to extend Mixer Check Result response Struct

### ISSUE THREAD

**Issue by ashishksingh** [istio/istio#18466]
**Describe the feature request**
I am looking for a way to extend the Mixer Authz component such that as part of the 'Check' Mixer call, the response from the corresponding Mixer Authz Adapter could also include some custom data, such as a list of roles in case of an allowed=true decision. 
Is there a way to accomplish that ?
 I checked the istio.mixer.package.adapter.check.go file, and CheckResult struct doesn't seem to allow extending the response. Please let me know if there is an alternative. 

**Describe alternatives you've considered**
I looked at creating a new Authorization template first, but then I realized that the response for a 'Check' call is hardcoded to the CheckResult struct, and there doesn't seem to be a way to customize that. 

**Additional context**

**Comment by NilsRenaud** [comment]
Well you probably can't customize the CheckResult struct but you can return your own struct next to the check result and then deal with your custom parameters yourself in the handler.

To be able to check and return results your proto file should have this Template variety : 

```
option (istio.mixer.adapter.model.v1beta1.template_variety) = TEMPLATE_VARIETY_CHECK_WITH_OUTPUT;
```

**Comment by kyessenov** [comment]
Correct, you need to use CHECK_WITH_OUTPUT to supply an extra result with the check response.
