### ISSUE TITLE
Adding analyzer for selector-less Sidecar resources

### ISSUE THREAD

**Issue by xeviknal** [istio/istio#18468]
**Describe the feature request**
Adding an analyzer for selector-less sidecar resources. See the documentation
**Additional context**
cc @sushicw what do you think about this validation?
https://github.com/kiali/kiali/issues/1541

**Comment by sushicw** [comment]
Makes sense. Copying from the relevant reference doc to add context:

https://istio.io/docs/reference/config/networking/v1alpha3/sidecar/

> NOTE 1: Each namespace can have only one Sidecar resource without any workload selector. The behavior of the system is undefined if more than one selector-less Sidecar resources exist in a given namespace. The behavior of the system is undefined if two or more Sidecar resources with a workload selector select the same workload instance.

**Comment by xeviknal** [comment]
It looks like the istio-policy-bot ate half of the issue description.
Thanks for adding the documentation info back.
