### ISSUE TITLE
Stable ports for "istioctl dashboard"

### ISSUE THREAD

**Issue by esnible** [istio/istio#18479]
`istioctl dashboard` uses a dynamic port to avoid dealing with conflicts.

While working on https://github.com/istio/istio.io/pull/5296 I realized this makes it difficult to create documentation that links to dashboards.

The requested feature is that `dashboard` will first try to use the same port locally as the service, only falling back to a dynamic service if the local service is unavailable.

**Comment by howardjohn** [comment]
I feel like that may just cause more confusion when there is a conflict and then it chooses a random port. Won't the user then be confused why the port doesn't match the docs? We should be able to just make the docs not depend on the port most likely

**Comment by esnible** [comment]
@howardjohn My original plan was to make the docs not depend on the port.  I became concerned looking at deep links such as the reference to http://localhost:9090/graph#%5B%7B%22range_input%22%3A%221h%22%2C%22expr%22%3A%22istio_double_request_count%22%2C%22tab%22%3A1%7D%5D from https://preliminary.istio.io/docs/tasks/observability/metrics/collecting-metrics/ .

@frankbu What do you think?  Give users UI instructions instead of deep links, or get `istioctl dashboard` to create stable ports?
