### ISSUE TITLE
External Service - Self-signed - Verification Failed

### ISSUE THREAD

**Issue by vsquare1** [istio/istio#18473]
**Bug description**
I have configured ServiceEntry to point to external server which TLS enabled with Self-Signed cert.
I am getting Verification failed issue.
Our corporate CA has to be added to the CA certificates and How do I add that to the Istio-Proxy?

Tried to issue curl from the istio-proxy and here is the curl -v <myhost>  output.
------
*   Trying 11.16.119.141...
* Connected to <REDACTED> (11.16.119.141) port 443 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 592 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_256_GCM_SHA384
* server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
* Closing connection 0
curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

-----

**Expected behavior**
Expecting to connect without issue. Need a way to add the CA to the current list of CA Certs within the Istio-Proxy
**Steps to reproduce the bug**

**Version (inc lude the output of `istioctl version --remote` and `kubectl version`)**
1.2.2
**How was Istio installed?**
Helm Template
**Environment where bug was observed (cloud vendor, OS, etc)**
EKS

**Comment by incfly** [comment]
Configure DestinationRule with TLS to talk to external service, you may need to mount the certificate/root to the istio-proxy.
