### ISSUE TITLE
istioctl manifest apply command should issue warning if the installed Istio version is different

### ISSUE THREAD

**Issue by ostromart** [istio/istio#18487]
It's quite possible that a user would have multiple versions of istioctl floating around - we want to prevent them running (say) istioctl manifest apply using the wrong version of istioctl, since this may lead to wrong charts being used.

**Comment by elfinhe** [comment]
so the suggestion is to prompt back the version number when confirming the install?

```
This will install the default profile of Istio 1.4.3 into the cluster. Proceed? (y/N) y
```

**Comment by elfinhe** [comment]
Also if the tag of finalICPS does not match the binversion, we also want to output a message.

**Comment by elfinhe** [comment]
Some questions before someone can pick up this issue:

1. If users are using their own charts, should we give this warning?
2. can we trust the docker image tag as the version?
3. what is the string format of a version? should the version also include `lastest` and `1.4-dev`?

we are giving a warning to end-user, so we need to be careful otherwise it will be confusing.

**Comment by esnible** [comment]
Targetting for 1.6 and adding dual responsibility for `User Experience`.

With 1.6 we have the problem that there may be multiple control planes, and if they are different versions the current expectation is to use an Istioctl at the same level as the version.  So this may rise in importance.

We must use the Control Plane Version reported by `istioctl version` in the message.

**Comment by shamsher31** [comment]
> It's quite possible that a user would have multiple versions of istioctl floating around - we want to prevent them running (say) istioctl manifest apply using the wrong version of istioctl

During the `1.6` testing, [I faced this issue](https://github.com/istio/istio/issues/23850#issuecomment-629281487) where I had `1.5.4` configured and I was trying to run `istioctl` from `1.6`release binary using `./bin/istioctl manifest`. 

See the comments: https://github.com/istio/istio/issues/23850

**Comment by esnible** [comment]
@shamsher31 Are you working on this?  Status?

**Comment by shamsher31** [comment]
@esnible Yes, the PR is ready for review. Got some feedback from @howardjohn . Updated it. Please take a look at https://github.com/istio/istio/pull/24263

**Comment by sdake** [comment]
@shamsher31 your PR was closed by the policy bot inadvertently. I will add a staleproof to the PR.
