### ISSUE TITLE
bots repo has bad test advice

### ISSUE THREAD

**Issue by therealmitchconnors** [istio/istio#18493]
The gen-check test on the bots repo has the following in it's failure message:
`Some files need to be updated, please run 'make gen' and include any changed files in your PR`
But running 'make gen' from the root of the repo results in:
`make: *** No rule to make target 'gen'.  Stop.`
And running 'make gen' from the policybot folder results in:
`../../../scripts/gen_topic.sh: line 19: go-bindata: command not found
dashboard/topics/workinggroups/topic.go:15: running "../../../scripts/gen_topic.sh": exit status 127
`
See https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_bots/95/gencheck_bots/11 for example.

**Comment by geeknoid** [comment]
Is your repo up to date? Cause the current sources do contain a `gen` target:

https://github.com/istio/bots/blob/77bd89cf6268fad2e2e451291b722a5060768f79/Makefile.core.mk#L23

**Comment by therealmitchconnors** [comment]
ok, it looks like I can get 'make gen' in the root by rebasing.  running it from /policybot still results in a failure, but that's less of a problem.

**Comment by geeknoid** [comment]
Its not intended to work from the policybot directory, so I'm going to close this.
