### ISSUE TITLE
some error about mixer

### ISSUE THREAD

**Issue by kevinsingapore** [istio/istio#18496]
[root@notepad istio-1.3.3]# kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:18:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:15:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
[root@notepad istio-1.3.3]#

[root@notepad istio-1.3.3]# helm version
Client: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}
[root@notepad istio-1.3.3]#

[root@notepad istio-1.3.3]# istioctl version
client version: 1.3.3
control plane version: 1.3.3
Error: 2 errors occurred:
	* error execing into istio-policy-56c75cc9bb-75msm mixer container: unable to upgrade connection: container not found ("mixer")
	* error execing into istio-telemetry-6f9968579d-gsjp5 mixer container: unable to upgrade connection: container not found ("mixer")

[root@notepad istio-1.3.3]#

And, how to solve the error about mixer？some pod about policy/telemetry/tracing in istio-system namespace always restart.

**Comment by douglas-reid** [comment]
I'm not sure what has generated your errors. The data is not sufficient to debug. You might get some more insights by describing the restarting pods and seeing what other info is available.

In the meantime, I'd suggest moving this sort of support/question to the forums: discuss.istio.io. That is a more appropriate place for questions like this one.
