### ISSUE TITLE
Remove shell e2e once people starting to write test to the golang one

### ISSUE THREAD

**Issue by sebastienvas** [istio/istio#185]

**Comment by sebastienvas** [comment]
@rshriram The shell is still being used by IBM. I cannot find Craig's in Istio, would he be able to switch and use the go framework instead ?

**Comment by rshriram** [comment]
@craigyam ^^^

**Comment by istiotst** [comment]
@sebastienvas I'll take a look at switching over.

**Comment by sebastienvas** [comment]
@craigyam Thanks. Let me know if you need help. We do have a docker image that you can use if you don t want to reinstall all necessary tools. gcr.io/istio-testing/prowbazel:0.1.2

**Comment by istiotst** [comment]
@sebastienvas So what is the flow to run the e2e tests?  tests/e2e.sh from the istio/istio repo?  I'm having some issues running that one.  Is the setup process documented somewhere?

**Comment by istiotst** [comment]
@sebastienvas I have switched the Jenkins job over to tests/e2e.sh.  It does take a fair amount longer to run (seems like the bazel stuff downloads and loads a few things) than the kubeTest script (30 mins vs 8 mins).  Any tips on speeding things up?

**Comment by ldemailly** [comment]
who is @istiotst (nick?) ? don't comment as a "bot" user?

**Comment by craigyam** [comment]
@ldemailly Sorry, it's me.  I was signed in to github as the test id when I initially responded and stuck with it.  I've switched over now.

**Comment by sakshigoel12** [comment]
We will get to as many as possible, making overall epic as P1 for 0.2
