### ISSUE TITLE
Galley "istio_mcp_message_sizes_bytes_bucket" metric flooding

### ISSUE THREAD

**Issue by BoOgatti** [istio/istio#18501]
**Bug description**
(not sure that a bug, just question). After upgrading from 1.2.6 to 1.3.3 I've seen huge increasing amount of prometheus' scraped metrics. After investigation I found new metric _istio_mcp_message_sizes_bytes_bucket_ that not mentioned in [documentation](https://istio.io/docs/reference/commands/galley/#metrics)

**Expected behavior**
Not so much metrics

**Steps to reproduce the bug**
prom query: `scrape_samples_scraped`
result:
![image](https://user-images.githubusercontent.com/28646170/67936479-e97a6400-fbdc-11e9-8428-0b35326c6e87.png)

prom query: `topk(3, count by (__name__)({__name__=~".+", job="istio-galley"}`
result:
```
istio_mcp_message_sizes_bytes_bucket{} | 15274
istio_mcp_request_acks_total{} | 275
istio_mcp_message_sizes_bytes_sum{} | 275
```

Galley's resources usage with pod deleting:
![image](https://user-images.githubusercontent.com/28646170/67937019-d9af4f80-fbdd-11e9-8cec-5eb08f4c804f.png)

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```
$ istioctl version --remote
client version: 1.3.0
citadel version: 1.3.3
egressgateway version: 1.3.3
galley version: 1.3.3
ingressgateway version: 1.3.3
pilot version: 1.3.3
pilot version: 1.3.3
sidecar-injector version: 1.3.3
```
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-gke.2", GitCommit:"c9de33b5439df6e206d7ba646787c6ace92d737b", GitTreeState:"clean", BuildDate:"2019-09-06T18:30:33Z", GoVersion:"go1.12.9b4", Compiler:"gc", Platform:"linux/amd64"}
```
**How was Istio installed?**
Via [Banzaicloud operator](https://github.com/banzaicloud/istio-operator)

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE v1.14.6-gke.2

**Comment by cpick** [comment]
I believe this is the same as https://github.com/istio/istio/issues/19165

**Comment by BoOgatti** [comment]
Yes, it seems fixed
