### ISSUE TITLE
SKIPPED TestAuthorizationForHTTPServices istio.io test failure

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#18511]
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18508/integ-istioio-k8s-tests_istio/964

**Comment by harsha070** [comment]
Can I work on this?

**Comment by pitlv2109** [comment]
> Can I work on this?

Feel free to send out a PR

**Comment by howardjohn** [comment]
Skipped in https://github.com/istio/istio/pull/18776
