### ISSUE TITLE
Write Mixer Adapter in language other than Go

### ISSUE THREAD

**Issue by ashishksingh** [istio/istio#18510]
**Describe the feature request**
Although Mixer uses Grpc to invoke Adapters, most of the samples provide ways to write the adapter in Go only. Is there a reason for that, or can I write an adapter in any language I want as long as it sticks to the grpc service defintion ? 

**Describe alternatives you've considered**

**Additional context**
I wish to write mixer adapters in languages other than Go.

**Comment by douglas-reid** [comment]
@ashishksingh my advice would be to avoid writing an adapter for Mixer altogether, and wait for the dust to settle on 1.4 and the extensibility v2 work.

if, however, you have a business need in the more immediate term, you should be able to write an adapter in any language you desire.
