### ISSUE TITLE
503 reduction:  Add 'reset' as a 'retry_on' condition

### ISSUE THREAD

**Issue by duderino** [istio/istio#18515]
**Describe the feature request**

Upstream Envoy added retry on TCP socket reset (see https://github.com/envoyproxy/envoy/pull/7505/files). 

At a minimum, add 'reset' to the list of supported options in https://github.com/istio/istio/blob/8ece9bfa6161b2ec8fc0712f000bcb8ba71ef468/pkg/config/validation/validation.go#L66

Consider adding it to the default set of things that Istio retries

**Describe alternatives you've considered**

Learning to stop worrying and love the 503

**Additional context**

**Comment by howardjohn** [comment]
> Learning to stop worrying and love the 503

done :slightly_smiling_face:

**Comment by howardjohn** [comment]
This is done
