### ISSUE TITLE
'istioctl x upgrade' fails with cryptic message when using 1.4 beta 1

### ISSUE THREAD

**Issue by davidebbo** [istio/istio#18521]
Steps:
- Start with cluster with Istio 1.3
- Run `'istioctl x upgrade` using Istio 1.4 Beta 1

Result: it fails with `Error: the target version 1.4-dev in  is not supported by istioctl 1.4.0, please download istioctl 1.4-dev and run upgrade again`.

A few issues:

- Ideally, it should work
- If it really cannot, it should give a clear message why. Right now, the message seems to be missing a word  (`in  is`), and as a user I have no idea what to do next

**Comment by elfinhe** [comment]
This is actually great finding! thanks for playing with it and reporting the issue. @davidebbo!
The hub naming pattern (1.4-dev) is a new feature added this week. I will fix this one.

**Comment by davidebbo** [comment]
The error is a little better in beta2, but it still doesn't make much sense:

    Error: the target version 1.4.0-beta.2 is not supported by istioctl 1.4.0, please download istioctl 1.4.0-beta.2 and run upgrade again

It's asking me to download beta2 when it's what I'm already running...

**Comment by elfinhe** [comment]
this error will go away when the official release is out.
agree that we need find a better way to handle the version across different repos.

**Comment by elfinhe** [comment]
verified that the error went away in the official release. closing...

**Comment by Firefishy** [comment]
"Error: the target version 1.4.1 is not supported by istioctl 1.4.0, please download istioctl 1.4.1 and run upgrade again"

**Comment by adamreis** [comment]
I'm seeing the same as @Firefishy trying to upgrade from 1.4.0 to 1.4.1. 

```bash
$ ./bin/istioctl version
client version: 1.4.1
...

$ ./bin/istioctl experimental upgrade -f <path-to-generated-manifest>


Client - istioctl version: 1.4.0

Error: the target version 1.4.1 is not supported by istioctl 1.4.0, please download istioctl 1.4.1 and run upgrade again
```

**Comment by davidebbo** [comment]
That sounds like a bug. @elfinhe?

Until this is fixed: use the `--force`!

**Comment by elfinhe** [comment]
yes, it is. 

related: https://github.com/istio/istio/issues/19475
