### ISSUE TITLE
istioctl manifest apply: "No resources found"

### ISSUE THREAD

**Issue by jwendell** [istio/istio#18534]
Installed Istio with
`istioctl manifest apply --set profile=demo`

And saw some messages like this:

```
Component NodeAgent installed successfully:
===========================================
No resources found

Component Cni installed successfully:
=====================================
No resources found
```

It's confusing because it says it installed successfully which I don't think it's true.

Ideally it should not show those messages for components not present in the profile or not selected for installation.

**Comment by elfinhe** [comment]
Fixed by https://github.com/istio/operator/pull/625
