### ISSUE TITLE
Changes to istioctl to update mesh configuration

### ISSUE THREAD

**Issue by gnirodi** [istio/istio#1854]
Design doc reference: https://goo.gl/AQARBs#heading=h.j8qy0mqyll8p

On the lines of: https://github.com/gnirodi/pilot/blob/hybrid-multi-cluster/bridge/istioctl/cmd/mesh-cmds.go

With the following changes:
- Integrate command update-mesh with the main istioctl binary see https://github.com/istio/istio/blob/master/pilot/cmd/istioctl/main.go#L518

1.Logic changes: 
- We'll need to see how the PR for https://github.com/kubernetes/cluster-registry/pull/65 as to how to update the registry and perform that action possibly calling the appropriate binary
- For each cluster in the registry that has the mesh annotation, run a mesh sync agent (if one's not already started) with a command line option for the registry. In this mode, the msa does reads the registry, writes the appropriate CRDs as necessary and EXITS with success / failure as necessary.
- Upon success, it should create the deployment and service for the MSA

**Comment by cmluciano** [comment]
This work is underway in the [templatized mesh config pr](https://github.com/istio/istio/pull/1895)
