### ISSUE TITLE
CNI charts are outdated

### ISSUE THREAD

**Issue by jwendell** [istio/istio#18576]
Previously (or currently) CNI components can be - and are - encouraged to be installed on `kube-system` namespace:

```
$ helm template install/kubernetes/helm/istio-cni --name=istio-cni --namespace=kube-system | kubectl apply -f -
```
This way users can setup additional priorities for pod scheduling like `system-node-critical`.

With the `istioctl manifest` method, those components are installed in `istio-system` namespace.

Is there an way to install them in a different namespace like it's possible with `helm`?

**Comment by jwendell** [comment]
cc @sdake @ostromart @rlenglet

**Comment by rlenglet** [comment]
This is incorrect. It *had* to be created in `kube-system` due to using the `system-node-critical` priority class. This is no longer required in 1.4, where we use the `system-cluster-critical` priority class.

**Comment by rlenglet** [comment]
cc @ruigulala

**Comment by rlenglet** [comment]
That said, for some reason, `istio/installer` has forked the Helm chart seemingly months ago and never sinced again: https://github.com/istio/installer/blob/release-1.4/istio-cni/templates/daemonset.yaml It does even have the `priorityClass`. This is a recipe for disaster. @jwendell I'd recommend rewording the issue about `istio/installer` being way out of sync with upstream `istio/cni`.

**Comment by rlenglet** [comment]
`istio/installer` CNI charts being out of sync with `istio/cni` is a release blocker IMHO. @istio/release-managers-1-4

**Comment by jwendell** [comment]
@rlenglet Do you know who is the source of truth when we talk about charts? It's confusing to me.

So, we have charts in istio/cni, then install/cni. We also have istio/operator. Where does `istioctl manifest` copy them from? Which one does it use?

**Comment by howardjohn** [comment]
istioctl imports the operator as go code. The operator has the charts built
into the go code using the vfsgen stuff. Those charts are from
istio/installer.

istio/cni also has charts that are shipped as part of the helm install

**Comment by jwendell** [comment]
I've created https://github.com/istio/installer/pull/476

Could someone from CNI team please verify if it's enough?

**Comment by sdake** [comment]
> @rlenglet Do you know who is the source of truth when we talk about charts? It's confusing to me.
> 
> So, we have charts in istio/cni, then install/cni. We also have istio/operator. Where does `istioctl manifest` copy them from? Which one does it use?

The source of truth, for the time being, is istio/installer repo. We plan to delete charts from other repositories including this one to centralize the installation charts.  In istio/istio, the install directory has taken a hard line on merging changes to installer first. Sadly that was not done with this repo.

Cheers
-steve
