### ISSUE TITLE
istio-auth-node-agent can't get certificate if it has been disconnected for >1 hr

### ISSUE THREAD

**Issue by craigbox** [istio/istio#1858]
Running 0.2.12.

istio-ca gets certificates that are valid for 1 hour, and refreshes them every 30 minutes.  If for some reason the node agent is unable to refresh its certificate within the hour (in my case, losing the ability to resolve istio-ca due to #1857), then you end up with an expired cert-chain.pem:

```
$ openssl x509 -in /etc/certs/cert-chain.pem -text -noout
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            82:b0:ff:51:b1:d4:2a:59:a3:1b:ac:db:c8:19:39:0d
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: O = k8s.cluster.local
        Validity
            Not Before: Nov 21 00:10:18 2017 GMT
            Not After : Nov 21 01:10:18 2017 GMT

```
and the node agent will not get a new certificate:

```
Nov 24 14:43:01 istio-vm systemd[1]: Started istio-auth-node-agent: The Istio auth node agent.
Nov 24 14:43:01 istio-vm node_agent[19179]: I1124 14:43:01.602049   19179 main.go:66] Starting Node Agent
Nov 24 14:43:01 istio-vm node_agent[19179]: I1124 14:43:01.602772   19179 nodeagent.go:96] Node Agent starts successfully.
Nov 24 14:43:01 istio-vm node_agent[19179]: I1124 14:43:01.635221   19179 nodeagent.go:112] Sending CSR (retrial #0) ...
Nov 24 14:43:01 istio-vm node_agent[19179]: 2017/11/24 14:43:01 Failed to dial istio-ca:8060: connection error: desc = "transport: remote error: tls: bad certificate"; please retry.
Nov 24 14:43:01 istio-vm node_agent[19179]: E1124 14:43:01.784010   19179 nodeagent.go:143] CSR signing failed: CSR request failed rpc error: code = 13 desc = connection error: desc = "transport: remote error: tls: bad certificate". Will retry in 
```

I fixed this by re-running `install/tools/setupMeshEx.sh machineSetup` script to regenerate the cert-chain.pem file and re-copy it to the node.

**Comment by crazytan** [comment]
@myidpt @wattli should we consider this situation?

**Comment by wattli** [comment]
- We have increased the TTL to 19 hours
- For GCE/GKE, we use GCP metadata instance doc (jwt), so key/cert is unnecessary
- For on-prem, this is the best we can offer, i.e., if the cert expires, you have to redeploy.

**Comment by myidpt** [comment]
We have made some improvement since them:
Now for on-prem, you can explicitly configure the TTL in your certificate request to provision a certificate valid for longer time:
https://github.com/istio/istio/blob/c6166bfc6aa14632f92ded01a2b16bbcd827e913/security/cmd/node_agent/main.go#L55
Note the CA has a workload TTL cap configuration:
https://github.com/istio/istio/blob/c6166bfc6aa14632f92ded01a2b16bbcd827e913/security/cmd/istio_ca/main.go#L157

**Comment by craigbox** [comment]
I would have found it helpful to have a descriptive error: we know exactly why it's a "bad certificate", as Istio controls both ends.  The error could say "certificate has expired: re-issue manually".
