### ISSUE TITLE
disableMixerHttpReports: does not remove http filter from inbound.

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#18586]
With  `meshconfig.disableMixerHttpReports: true`

mixerClient http filter is not inserted in any outbound listeners.
However, it *is* still inserted in the inbound listener.
 `disable_report_calls: true` is present, but filter should not be injected at all.

**Comment by mandarjog** [comment]
Enabling TCP only shows workload as `unknown:unknown`
<img width="1457" alt="Screen Shot 2019-11-03 at 9 00 37 PM" src="https://user-images.githubusercontent.com/800375/68100488-0fbe2f00-fe7d-11e9-948e-395abf196c56.png">

**Comment by douglas-reid** [comment]
is the problem that the filter is present, or that the report calls are still happening?  the code merely sets a value in the service config for the filter, it does not remove the filter altogether.

Removing the filter altogether seems problematic as `Check` and `Report(TCP)` may still be desired.
