### ISSUE TITLE
Unknown flag of mcpMaxMsgSize

### ISSUE THREAD

**Issue by nkorange** [istio/istio#18590]
**Bug description**
When I installed Istio 1.4.0-beta.1 with helm and then there was error below:
```
[root@iZ2ze153b3wzdwgyfjoc75Z istio-1.4.0-beta.1]# kubectl logs  istio-pilot-55f5f76cdc-xdhxd -c discovery -n istio-system
Error: unknown flag: --mcpMaxMsgSiz
2019-11-04T07:53:48.044587Z	error	unknown flag: --mcpMaxMsgSiz
```

**Expected behavior**
No error.

**Steps to reproduce the bug**
Edit file ```install/kubernetes/helm/istio/charts/pilot/templates/deployment.yaml``` and insert the following content at line 78:
```
          - --mcpMaxMsgSiz
          - "419430400"
``` 
Then install.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

Istio version: 1.4.0-beta.1
k8s verion: 1.14.6

**How was Istio installed?**

```
$ kubectl create namespace istio-system
$ helm template install/kubernetes/helm/istio-init --name istio-init --namespace istio-system | kubectl apply -f -
$ helm template install/kubernetes/helm/istio --name istio --namespace istio-system \
    --values install/kubernetes/helm/istio/values-istio-demo.yaml | kubectl apply -f -

```

**Comment by howardjohn** [comment]
mcpMaxMsgSiz -> mcpMaxMsgSize

**Comment by nkorange** [comment]
I can't believe I misspelled it!! 😭
