### ISSUE TITLE
Test data file names not OS agnostic (result in go get failures)

### ISSUE THREAD

**Issue by aattuluri** [istio/istio#18597]
**Bug description**
`go get istio.io/istio` fails due to unzip error. The following files have a `*` in the filename which is not OS agnostic and hence the unzip fails in go get:
`pilot/pkg/security/authz/builder/testdata/v1alpha1/simple-policy-user-with-*-in.yaml`
`pilot/pkg/security/authz/builder/testdata/v1alpha1/simple-policy-user-with-*-out.yaml`

**Expected behavior**
I would expect `go get istio.io/istio` to work

**Steps to reproduce the bug**
run `go get istio.io/istio`

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
N/A

**How was Istio installed?**
N/A

**Environment where bug was observed (cloud vendor, OS, etc)**
N/A

**Comment by howardjohn** [comment]
Fixed:
```
$ find | rg simple-policy-user-with
./pilot/pkg/security/authz/builder/testdata/v1alpha1/simple-policy-user-with-wildcard-in.yaml
./pilot/pkg/security/authz/builder/testdata/v1alpha1/simple-policy-user-with-wildcard-out.yaml
```
