### ISSUE TITLE
Starts using istio-auth.yaml in e2e framework

### ISSUE THREAD

**Issue by sebastienvas** [istio/istio#186]
And allow people to use any of the setup via flag:
istio-15.yaml
istio-16.yaml
istio-auth-15.yaml
istio-auth-16.yaml
istio-auth.yaml

**Comment by lookuptable** [comment]
Last time I checked the demo didn't work when RBAC is on. Can we have a RBAC-enabled K8S cluster to test out istio-*-16 YAMLs?

**Comment by sebastienvas** [comment]
Jenkins is currenlty using 1.6. I am not sure what is supposed to be done to enable RBAC

**Comment by lookuptable** [comment]
This is a command to create a RBAC-enabled 1.6 GKE cluster:
```
gcloud container clusters create $NAME_OF_CLUSTER --cluster-version 1.6.2 --no-enable-legacy-authorization
```

**Comment by sebastienvas** [comment]
@yutongz this is another duplicate of the work you are doing.
