### ISSUE TITLE
SDS: currently there is no way for SDS server to communicate over the abstract_UNIX_Socket as the SDS_UDS_PATH is hard-coded in the pilot-agent.

### ISSUE THREAD

**Issue by abhijitherekar** [istio/istio#18607]
**Bug description**
If you want to change the SDS_UDS_PATH to communicate over unix Abstract sockets, currently we cannot communicate, as the SDS_UDS_PATH is hardcoded. 

Haver talked to @JimmyCYJ about this on slack, hewre's the converstaion: 
https://istio.slack.com/archives/C3TEGNZ7W/p1572396617081000
 
cc: @JimmyCYJ @myidpt 

**Expected behavior**
The SDS server should be able to talk on a given path rather than a hard-coded path. 

**Steps to reproduce the bug**
Install istio for SDS and try to change the SDS_UDS_PATH through the istio configmap. 

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
istioctl version --remote
client version: unknown
citadel version: 1.2.5
galley version: 1.2.5
ingressgateway version: 1.2.5
nodeagent version: 
nodeagent version: 
nodeagent version: 
nodeagent version: 
nodeagent version: 
pilot version: 1.2.5
policy version: 1.2.5
sidecar-injector version: 1.2.5

**How was Istio installed?**
through helm template. 

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

**Comment by myidpt** [comment]
Your Istio version is out of the maintenance window. Even if we fix this, the fix won't be backported to 1.2. Can I understand the reason that you must use the UDS in an abstract namespace?
