### ISSUE TITLE
operator.istio.io/version: 1.4.0 shows wrong version

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#18612]
This version looks to be hardcoded, and does not match the actual version that ends up being installed

**Comment by ostromart** [comment]
We do use a hardcoded internal "charts version" to determine compatibility, regardless of which version is supplied through the build. Where are you seeing this exactly? We may need some way to display this differently.

**Comment by howardjohn** [comment]
I see this on some deployments after using istioctl.

**Comment by ostromart** [comment]
I think this is resolved through https://github.com/istio/operator/pull/610 but not verified. We can see when 1.4.1 is released.

**Comment by howardjohn** [comment]
this is still hardcoded. Not sure if it's intended or not @elfinhe if it is feel free to close
