### ISSUE TITLE
operator controller install fails due to CRD sequencing

### ISSUE THREAD

**Issue by ostromart** [istio/istio#18618]
The CRD should be either installed separately or instructions be given to use -k. Note that the command below succeeded when it was re-run.

$ kubectl apply -f https://preliminary.istio.io/operator.yaml
namespace/istio-operator created
customresourcedefinition.apiextensions.k8s.io/istiocontrolplanes.install.istio.io created
serviceaccount/istio-operator created
clusterrole.rbac.authorization.k8s.io/istio-operator created
clusterrolebinding.rbac.authorization.k8s.io/istio-operator created
service/istio-operator-metrics created
deployment.apps/istio-operator created
error: unable to recognize "https://preliminary.istio.io/operator.yaml": no matches for kind "IstioControlPlane" in version "install.istio.io/v1alpha2"

**Comment by linsun** [comment]
@sdake should we use kustomize instead so that CRDs can be installed first?

**Comment by ostromart** [comment]
Fixed in https://github.com/istio/istio.io/pull/5524 and https://github.com/istio/istio.io/pull/5433.
