### ISSUE TITLE
Proxy: Metrics V2 stackdriver attempting to write metrics from the past.

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#18613]
```
[Envoy (Epoch 0)] [2019-11-04 20:29:52.595][21][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:91] gRPC config stream closed: 2, CONNECTION ID: sidecar~10.44.13.84~fortioserver-f778dbfc7-g2z9x.twopods~twopods.svc.cluster.local-27947, RESOURCE NAME: default, EVENT: Close connection to proxy "sidecar~10.44.13.84~fortioserver-f778dbfc7-g2z9x.twopods~twopods.svc.cluster.local-27947"
CreateTimeSeries request failed (1 RPCs, 8 views, 8 timeseries): INVALID_ARGUMENT: Field timeSeries[0].points[0].interval.end_time had an invalid value of "2019-11-02T18:12:10.707563-07:00": Data points cannot be written more than 24h in the past.
CreateTimeSeries request failed (1 RPCs, 8 views, 8 timeseries): INVALID_ARGUMENT: Field timeSeries[0].points[0].interval.end_time had an invalid value of "2019-11-02T18:12:10.707563-07:00": Data points cannot be written more than 24h in the past.
```

**Comment by bianpengyuan** [comment]
I guess opencensus library retains time series for stale pods and keeps sending them to the backends. @g-easy Any insight about this?

**Comment by douglas-reid** [comment]
This seems like a potential error with the flushing logic. Like, for some reason, a req was left unsent, and then sending more traffic to it all of a sudden (but after 24h) caused a flush of old data.

I'm not sure what would cause that, however.

I saw something similar on a cluster I left up over the weekend, but didn't stop to investigate, unfortunately.

**Comment by bianpengyuan** [comment]
A quick bandaid is to filter out day old time series at sd exporter: https://github.com/census-instrumentation/opencensus-cpp/blob/master/opencensus/exporters/stats/stackdriver/internal/stackdriver_exporter.cc#L105

But this might hide some underlying bug if the behavior is unexpected.

**Comment by g-easy** [comment]
Are you seeing this despite https://github.com/census-instrumentation/opencensus-cpp/pull/395? The end_time should be the time of export.

**Comment by bianpengyuan** [comment]
Ah, I guess the sha in envoyproxy is not new enough: https://github.com/envoyproxy/envoy/blob/cf74f816933d1350d7c588a3b8478dd399ce3d18/bazel/repository_locations.bzl#L262. Let me update that. Thanks!

**Comment by bianpengyuan** [comment]
This should be fixed by https://github.com/istio/proxy/commit/cbb13d43e39f57203d6fb7ccf013816e5eaec809
