### ISSUE TITLE
Operator bug error    json: cannot unmarshal string into Go value of type map[string]json.RawMessage

### ISSUE THREAD

**Issue by kramvan1** [istio/istio#18615]
**Bug description**

Seeing the following bug in the Istio operator logs from image https://console.cloud.google.com/gcr/images/istio-testing/GLOBAL/operator@sha256:582a9f9dce2e11a085f1d4f3f53af51e4137b76fa87e49090aca532d54a35779/details?tab=info

LOGS and ICP content attached

**Expected behavior**

No errors like this in log

**Steps to reproduce the bug**

1.  deploy operator
2. apply the ICP
3. look at the operator logs

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

1.4.0-beta.1
kube 1.16.3

**How was Istio installed?**

operator image noted above

**Environment where bug was observed (cloud vendor, OS, etc)**

IKS

**Comment by kramvan1** [comment]
[operator.log](https://github.com/istio/istio/files/3806358/operator.log)
[icp.txt](https://github.com/istio/istio/files/3806360/icp.txt)

**Comment by sdake** [comment]
Unclear if this is impacting behavior or not.

Marking as P0 for 1.4.

**Comment by howardjohn** [comment]
I got the same issue

**Comment by sdake** [comment]
seems sloppy at best.  Wondering what the impact is.

**Comment by howardjohn** [comment]
Has anyone tracked down the source of this?

**Comment by valer-cara** [comment]
I got a similar issue while customizing the `ingressgateway.k8s.service` part. It went away after removing all `targetPort` keys from the yaml. Can't tell what that was..

**Comment by richardwxn** [comment]
There is an issue when unmarshalling k8s intstr struct type with jsonpb. I will work on the fix in this PR: https://github.com/istio/operator/pull/711

**Comment by esnible** [comment]
I have verified this is not happening in 1.5 beta 4 using the _icp.txt_ attached to this issue.

`istioctl manifest generate -f ~/Downloads/icp.txt` generated YAML.

I found a problem unrelated to unmarshalling and filed https://github.com/istio/istio/issues/21704

Can we close this one?

**Comment by kramvan1** [comment]
yup, don't see this in 1.5 beta.4 closing.
