### ISSUE TITLE
Short proxy log messages

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#18611]
The prefix for each log line is absurdly long, making it really hard to read:

```
[Envoy (Epoch 0)] [2019-11-04 21:07:14.148][20][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:91]
```

Compared to upstream envoy:
```
[2019-11-04 21:23:33.996][1][info][config] [source/server/configuration_impl.cc:62] 
```

Is it feasible to remove all the bazel-out junk?

**Comment by PiotrSikora** [comment]
You're comparing apples (`.h`) to oranges (`.cc`). The output is the same as in upstream.

**Comment by howardjohn** [comment]
Fair enough, thanks for the info
