### ISSUE TITLE
synthetic service entries need full push for eds/config updates

### ISSUE THREAD

**Issue by ramaraochavali** [istio/istio#18625]
**Bug description**
Synthentic service entries need a full push for eds/config update. Currently it is dependent on the behaviour that the eds code removing service from EndpointShardsByService when endpoints become zero which triggers a full push on the next endpoint update. That is changing in https://github.com/istio/istio/pull/18574. With that PR e-e piliot synthetic service entry test fails to push service as well endpoint updates. As part of that PR, it was changed to do a full push on every update (config or eds).

That needs to be fixed.

**Comment by Nino-K** [comment]
Going to close this as it is no longer relevant: https://github.com/istio/istio/pull/21154
