### ISSUE TITLE
Installer - Template labelling issues causing deployment failures

### ISSUE THREAD

**Issue by dbnegative** [istio/istio#18637]
**Bug description**
Various installer templates (for example gateways/ingress-gateway chart) have a hardcoded exclusion statements that overwrite labels when "istio-system"  is used as a  namespace. This causes the release label to be to set to "istio" rather than the provided release name. 

This affects resources such as the horizontal pod autoscaler that require the release label to be to match the ingress-gateway pod. This seems unintentional as all other resources seem to have their release label set to the provided release name.

https://github.com/istio/installer/blob/36f377d6c08ee27b836f52fa0a2c3672ad6fb2a8/gateways/istio-ingress/templates/deployment.yaml#L29

https://github.com/istio/installer/blob/fe4a478fe6c5aa163d54478facc4b85893466250/istio-control/istio-discovery/templates/deployment.yaml#L46

https://github.com/istio/installer/blob/d14e006b7b988d9401ee427f1a281295487161e8/istio-control/istio-config/templates/deployment.yaml#L24

https://github.com/istio/installer/blob/d14e006b7b988d9401ee427f1a281295487161e8/gateways/istio-egress/templates/deployment.yaml#L29

https://github.com/istio/installer/blob/44c9a6a89c60e8465c764b3ba6a7f3a3231f6dc1/istio-control/istio-autoinject/templates/mutatingwebhook.yaml#L6

https://github.com/istio/installer/blob/44c9a6a89c60e8465c764b3ba6a7f3a3231f6dc1/istio-control/istio-autoinject/templates/mutatingwebhook.yaml#L6

https://github.com/istio/installer/blob/d14e006b7b988d9401ee427f1a281295487161e8/istio-control/istio-autoinject/templates/deployment.yaml#L63

**Expected behavior**
Installs the in ingress gateway as expected 

**Steps to reproduce the bug**

```
git clone https://github.com/istio/installer.git

helm template --namespace istio-system -n "istio-ingress" installer/gateways/istio-ingress/ -f installer/global.yaml > ig.yaml

kubectl apply --prune --l release=istio-ingress -f ig.yaml
```
output on apply:
```
serviceaccount/istio-ingressgateway-service-account created
service/istio-ingressgateway created
deployment.apps/istio-ingressgateway created
horizontalpodautoscaler.autoscaling/istio-ingressgateway created
poddisruptionbudget.policy/ingressgateway created
Error from server (Timeout): error when creating "ig.yaml": Timeout: request did not complete within requested timeout 30s
Error from server (Timeout): error when creating "ig.yaml": Timeout: request did not complete within requested timeout 30s
```
events:
```
m39s       Normal    Pulled                         Pod                       Successfully pulled image "gcr.io/istio-release/proxyv2:release-1.3-latest-daily"
2m38s       Warning   Unhealthy                      Pod                       Readiness probe failed: HTTP probe failed with statuscode: 503
2m18s       Normal    DeletedLoadBalancer            Service                   Deleted load balancer
2m18s       Normal    EnsuringLoadBalancer           Service                   Ensuring load balancer
100s        Warning   FailedGetResourceMetric        HorizontalPodAutoscaler   did not receive metrics for any ready pods
100s        Warning   FailedComputeMetricsReplicas   HorizontalPodAutoscaler   failed to get cpu utilization: did not receive metrics for any ready pods
84s         Normal    EnsuredLoadBalancer            Service                   Ensured load balancer
8s          Normal    NoPods                         PodDisruptionBudget       No matching pods found
8s          Normal    NoPods                         PodDisruptionBudget       No matching pods found
8s          Normal    NoPods                         PodDisruptionBudget       No matching pods found
8s          Normal    NoPods                         PodDisruptionBudget       No matching pods found
```
**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.3.4
**How was Istio installed?**
installer repo with helm
**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

**Comment by dbnegative** [comment]
in addition the release label is neverset  on the ingress-gateway pod template even if another namespace is used.

**Comment by howardjohn** [comment]
I believe this is fixed now but we need to add a test in  https://github.com/istio/istio/blob/c0680c17d65da6c217620b3e8c466083927b5b25/operator/cmd/mesh/manifest-generate_test.go#L163
