### ISSUE TITLE
IPv6 loopback broken

### ISSUE THREAD

**Issue by faust64** [istio/istio#18639]
**Bug description**

As I've been trying out Istio on OpenShift 4, I've noticed the following behavior.

Using OpenShift 4.2.2
istio-operator 1.0.1, kiali-operator 1.0.6, jaegger-operator 1.13.1
Working with a dummy OpenLDAP image (github.com/Worteks/docker-ldap).

While booting, my LDAP container would start a slapd service and inject ldifs initializing its database.
Trying to deploy that container with Istio, those configuration steps take an awful long time to "complete" (actually, using a DeploymentConfig, after the default 10 minutes, my Pod gets terminated, as it's not done initializing).

In doubt, I deployed the same image to a namespace without Istio, and couldn't reproduce that issue.

Connecting to a node and stracing some ldapadd process, we can see the following:

```
sh-4.4# strace -p 60713
strace: Process 60713 attached
connect(3, {sa_family=AF_INET6, sin6_port=htons(1389), inet_pton(AF_INET6, "::1", &sin6_addr), sin6_flowinfo=htonl(0), sin6_scope_id=0}, 28 


        ) = -1 ETIMEDOUT (Connection timed out)
shutdown(3, SHUT_RDWR)                  = -1 ENOTCONN (Transport endpoint is not connected)
close(3)                                = 0
socket(AF_INET, SOCK_STREAM, IPPROTO_IP) = 3
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
setsockopt(3, SOL_SOCKET, SO_KEEPALIVE, [1], 4) = 0
setsockopt(3, SOL_TCP, TCP_NODELAY, [1], 4) = 0
connect(3, {sa_family=AF_INET, sin_port=htons(1389), sin_addr=inet_addr("127.0.0.1")}, 16) = 0
write(3, "0M\2\1\1`H\2\1\3\4\31cn=admin,dc=demo,dc="..., 79) = 79
poll([{fd=3, events=POLLIN|POLLPRI}], 1, -1) = 1 ([{fd=3, revents=POLLIN}])
read(3, "0\f\2\1\1a\7\n", 8)            = 8
read(3, "\1\0\4\0\4\0", 6)              = 6
fstat(0, {st_mode=S_IFIFO|0600, st_size=0, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fd961383000
read(0, "dn: cn=admin0,ou=users,dc=demo,d"..., 4096) = 942
fstat(1, {st_mode=S_IFIFO|0600, st_size=0, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fd961382000
write(3, "0\202\2@\2\1\2h\202\29\4#cn=admin0,ou=users,"..., 580) = 580
poll([{fd=3, events=POLLIN|POLLPRI}], 1, 100) = 1 ([{fd=3, revents=POLLIN}])
read(3, "0\f\2\1\2i\7\n", 8)            = 8
read(3, "\1\0\4\0\4\0", 6)              = 6
write(3, "0\201\275\2\1\3h\201\267\4$cn=Admins,ou=groups,d"..., 192) = 192
poll([{fd=3, events=POLLIN|POLLPRI}], 1, 100) = 1 ([{fd=3, revents=POLLIN}])
read(3, "0\f\2\1\3i\7\n", 8)            = 8
read(3, "\1\0\4\0\4\0", 6)              = 6
read(0, "", 4096)                       = 0
write(3, "0\201\264\2\1\4h\201\256\4!cn=All,ou=groups,dc=d"..., 183) = 183
poll([{fd=3, events=POLLIN|POLLPRI}], 1, 100) = 1 ([{fd=3, revents=POLLIN}])
read(3, "0\f\2\1\4i\7\n", 8)            = 8
read(3, "\1\0\4\0\4\0", 6)              = 6
write(3, "0\5\2\1\5B\0", 7)             = 7
shutdown(3, SHUT_RDWR)                  = 0
close(3)                                = 0
write(1, "adding new entry \"cn=admin0,ou=u"..., 167) = 167
exit_group(0)                           = ?
+++ exited with 0 +++
```

**Expected behavior**

When running slapadd against ldap://localhost should be as fast as ldap://127.0.0.1/. I shouldn't hit a timeout then fallback to ipv4.

**Steps to reproduce the bug**

Having deployed Istio, and created a namespace for our test

```
$ oc process -f https://github.com/Worteks/docker-ldap/blob/master/openshift/imagestream.yaml | oc apply -f-
$ oc process -f https://github.com/Worteks/docker-ldap/blob/master/openshift/build.yaml | oc apply -f-
```

Edit deployment configuration:
```
$ vi docker-ldap/openshift/run-ephemeral.yaml
```

In `spec.template.metadata`, add:
```
        annotations:
          sidecar.istio.io/inject: "true"
```

Once our image is done building, deploy a test pod:
```
$ oc process -f https://github.com/Worteks/docker-ldap/blob/master/openshift/secret.yaml | oc apply -f-
$ oc process -f https://github.com/Wortexks/docker-ldap/blob/master/openshift/run-ephemeral.yaml -p LDAP_IMAGE_FRONTNAME=demo | oc apply -f-
```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

```
# oc rsh -n openshift-operators istio-operator-755cc98b8c-bv2pm
sh-4.4# istio-operator --version
version.BuildInfo{Version:"1.0.1-8.el8", GitRevision:"8617354", BuildStatus:"Clean", GitTag:"1.0.1", GoVersion:"go1.12.6", GoArch:"linux/amd64", OperatorSDK:"v0.2.1"}
sh-4.4# exit
[root@ip-172-31-33-81 openshift]# oc version
Client Version: openshift-clients-4.2.0-201910041700
Server Version: 4.2.2
Kubernetes Version: v1.14.6+868bc38
```

Unclear: where would I find istioctl?

**How was Istio installed?**

Through the OperatorHub

**Environment where bug was observed (cloud vendor, OS, etc)**

AWS, RH-CoreOS.

**Comment by dgn** [comment]
OpenShift Service Mesh uses a fork of istio/cni, so it possibly does not affect Istio itself. I'm currently investigating. There's a downstream issue about it: https://issues.jboss.org/browse/MAISTRA-987

**Comment by faust64** [comment]
Interesting. I'll keep an eye on that one, thanks!

And indeed, I've only checked Service Mesh. Upstream might just be fine.
Though considering we have an issue related to CNI tests being broken with v6 (istio#17382) , ... could be worth checking.

**Comment by howardjohn** [comment]
Closing as this is tracked in https://issues.redhat.com/browse/MAISTRA-987?_sscc=t which also claims it is fixed
