### ISSUE TITLE
Proxy postsubmit failing

### ISSUE THREAD

**Issue by jwendell** [istio/istio#18633]
https://prow.istio.io/view/gcs/istio-prow/logs/proxy-postsubmit/819

```
invoking docker-credential-gcloud: exec: "docker-credential-gcloud": executable file not found in $PATH
```

**Comment by jwendell** [comment]
The example job above is for 1.4 branch.

cc @clarketm @howardjohn @PiotrSikora

**Comment by PiotrSikora** [comment]
Hmm, I thought that I fixed this in https://github.com/istio/test-infra/pull/2041, but I must have forgotten to login using service account, so my verification didn't require `docker-credential-gcloud`.

In any case, it seems that we need to install gcloud SDK in the RBE images: https://github.com/envoyproxy/envoy-build-tools/issues/16

In the meantime, let's disable RBE in the postsubmit job: https://github.com/istio/proxy/pull/2518
