### ISSUE TITLE
Envoy too many open files ( tcp sock connections)

### ISSUE THREAD

**Issue by LinLshare** [istio/istio#18638]
**Bug description**
Envoy too many open files ( tcp sock connections), more than 44k, when use istio-ingress-gateway & my service written by Go.

**Expected behavior**
fd less than 7k

**Steps to reproduce the bug**
1. install istio-1.3.4 with default values;
2. deploy a web service written by Go;
3. increase the requests to the web service;
4. see `node_filefd_allocated` metric on prometheus;
5. exec `lsof -c envoy` on the node where istio-ingress-gateway in and you will see many open tcp connections

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
client version: 1.3.4
control plane version: 1.3.4

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-eks-5876d6", GitCommit:"5876d6b7429820450950ade17fe7b4bf5ccada7f", GitTreeState:"clean", BuildDate:"2019-09-24T20:54:25Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
install istio-1.3.4 with default values by helm & tiller

**Environment where bug was observed (cloud vendor, OS, etc)**
Amazon Linux 2

**Comment by hzxuzhonghu** [comment]
You can set the env `ISTIO_META_IDLE_TIMEOUT`

**Comment by LinLshare** [comment]
It work, thanks so much 😘
![image](https://user-images.githubusercontent.com/11910355/68279913-6f038580-00af-11ea-874b-ec759a6fdfe0.png)
