### ISSUE TITLE
istioctl version reports dirty state

### ISSUE THREAD

**Issue by jwendell** [istio/istio#18636]
```
$ istioctl version --short=false --remote=false
version.BuildInfo{Version:"1.4.0-beta.2", GitRevision:"de1187d989f0378f562ca6ec36eef60e0f12ce64-dirty", GolangVersion:"go1.13.3", BuildStatus:"Modified", GitTag:"1.4.0-beta.2"}
```

cc @howardjohn @ericvn

**Comment by howardjohn** [comment]
ack, the issue is we modify the templates to replace the version before we build. Note that this has been an issue in every single Istio version, so not a regression, so I don't think P0 is warrented

**Comment by howardjohn** [comment]
Do we actually care to report `-dirty`? Seems like we can just always make it `clean`...

**Comment by jwendell** [comment]
Tried 1.3 and 1.2, they report a clean build status.

**Comment by howardjohn** [comment]
```
$ docker run istio/pilot:1.3.4 version
version.BuildInfo{Version:"1.3.4", GitRevision:"bcdf2483e7911f63a8edd6706f08674f8b5805f3-dirty", User:"root", Host:"f516dd1c-f78c-11e9-b028-c669b23c61b9", GolangVersion:"go1.12.12", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.3.3-13-gbcdf248"}
```

```
$ docker run istio/pilot:1.2.8 version
version.BuildInfo{Version:"1.2.8", GitRevision:"f5b3c0715e8daf703af1d88abc89ab735055e35d-dirty", User:"root", Host:"9eb42b86-f1f2-11e9-93a7-2a457930fd28", GolangVersion:"go1.12.12", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.2.7-10-gf5b3c07"}
```

I guess its just istioctl is clean but the docker images are dirty

**Comment by jwendell** [comment]
ah ok, just tried istioctl. Which is weird, because all binaries share the same script and values... :/

**Comment by howardjohn** [comment]
we build istioctl at a different point in the release, so probably modify
something between those two are built

**Comment by howardjohn** [comment]
not stale

**Comment by tcdowney** [comment]
Can this be reopened?

Just wanted to add that it's confusing to see something like this:
```
client version: 1.6.5
control plane version: df8ea82bf434fece015767579ef2e4a16e6a3fb3-dirty
data plane version: 1.6-dev (25 proxies)
```

when running `istioctl version` to see what specific version of Istio is deployed. :)

**Comment by howardjohn** [comment]
I am pretty sure that is a different issue, are you running an istioctl
from an official Istio release?

**Comment by tcdowney** [comment]
@howardjohn it was downloaded/installed through this script:
https://istio.io/downloadIstio

**Comment by howardjohn** [comment]
Not stale
