### ISSUE TITLE
Even with CNI enabled the istio-init container is being injected

### ISSUE THREAD

**Issue by jwendell** [istio/istio#18644]
Installed with
```
$ istioctl manifest generate --set profile=demo --set cni.enabled=true --set cni.components.cni.enabled=true --set values.cni.cniBinDir=/var/lib/cni/bin --set values.cni.cniConfDir=/var/run/multus/cni/net.d --set hub=gcr.io/istio-prerelease-testing --set cni.components.cni.namespace=kube-system
```

Installation went fine.

Deployed bookinfo and noticed the init container was being auto injected.

Looked at config map:
`$ kubectl -n istio-system get cm istio-sidecar-injector -o yaml | grep istio_cni`

I see within `values` field: `"istio_cni":{"enabled":false}`

That seems to be what is causing the init container to be injected: https://github.com/istio/installer/blob/master/istio-control/istio-autoinject/files/injection-template.yaml#L3

**Comment by ostromart** [comment]
There are a couple of problems afaics: per prior comments, it should not be necessary to set both feature and component flags, only feature. Also, setting this should reflect in values.cni.enabled, which it doesn't seem to be the case.
