### ISSUE TITLE
istioctl manifest apply --set profile=demo does not create jaeger-agent service

### ISSUE THREAD

**Issue by ericvn** [istio/istio#18658]
**Bug description**

The docs and the helm install of the demo profile mention that there should be a jaeger-agent service (with no clusterIP) after installing the demo profile.

I see the service when using helm, but not when using istioctl.

**Expected behavior**

jaeger-agent service created

**Steps to reproduce the bug**

See https://preliminary.istio.io/docs/setup/install/kubernetes/

Do `istioctl manifest apply --set profile=demo` look at services `kubectl get svc -n istio-system`

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

1.4.0-beta.2

**How was Istio installed?**

untar'd download

**Environment where bug was observed (cloud vendor, OS, etc)**

IKS

**Comment by ericvn** [comment]
I do see the service in:

https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/tracing/templates/service-jaeger.yaml

I do not see the service in:

https://github.com/istio/installer/blob/master/istio-telemetry/tracing/templates/service-jaeger.yaml

**Comment by ericvn** [comment]
https://github.com/istio/installer/pull/132/files was used to move the templates.

**Comment by linsun** [comment]
@costinm @douglas-reid @objectiser @rshriram  what is the purpose of jaeger-agent? I did a quick testing of book info with jaeger, and it seems to work fine with traces shown up.

**Comment by linsun** [comment]
Some history: https://github.com/istio/istio/commit/6dbbacac0b478017179480778637c9d8d781ac25
it was added by @objectiser @rshriram

**Comment by linsun** [comment]
per https://www.jaegertracing.io/docs/1.14/deployment/#agent, it is used as jaeger library and run locally on each host... which I don't think it applies to our jaeger service provided by istio installation.

**Comment by objectiser** [comment]
For the `all-in-one` deployment (which Istio is using) the jaeger agent is bundled in the one container image - in production deployments, the agent is separate and can be used as a sidecar or daemonset.

**Comment by ericvn** [comment]
@objectiser So when should this jaeger-agent service be created in an Istio install if at all? In the deprecated helm install, it was created as part of the demo profile (and maybe others (I haven't looked)). In the new istioctl install, it is no longer part of the demo profile.

**Comment by objectiser** [comment]
@ericvn It should be created to enable Jaeger to be used natively within the applications, along with jaeger-query and jaeger-collector.

**Comment by ericvn** [comment]
Thanks @objectiser. The other two are created, but the agent is not today. It sounds like this PR should be used to add that into the profile.

**Comment by ericvn** [comment]
As a side note, I did run through the jaeger and zipkin tasks using the current profile (without jaeger-ageant) and they did work as documented.

**Comment by linsun** [comment]
@objectiser that is not really istio's goal - re  "enable jaeger to be used natively within applications".   Plus the way jaeger-agent is in 1.3, it is just a service definition.

**Comment by douglas-reid** [comment]
@objectiser @linsun apologies for losing track across all of the install options. whatever happened to jaeger operator based installs? that seems like the ultimate solution here.

**Comment by ericvn** [comment]
Still waiting on a final answer whether the service should be created or not, as it determines if this is an installer or doc PR.

**Comment by objectiser** [comment]
@linsun that is all I am suggesting, to add the `jaeger-agent` Service - this would then enable applications using the Jaeger tracer (configured to use the agent) to work.

@douglas-reid I thought it was agreed that Istio would use a simple install approach, and if a user wanted a more complex (production) setup, they would use the operator themselves?

@ericvn my vote is to add the `jaeger-agent` service so that it is equivalent to the helm chart.

**Comment by linsun** [comment]
@douglas-reid I am not seeing jaeger operator being leveraged today in our code base.

@objectiser if we add it (probably ok for backwards compatible), that is fine.  however i (and probably most of us) don't know how to use it.  It is not doc-ed anywhere in istio.io to my knowledge.

**Comment by ericvn** [comment]
From Slack:
```
Irfan Shah 
@Tasdik @Saptanto Sindu we need jaeger agent to be there ^^^
```

**Comment by objectiser** [comment]
@linsun it is not relevant for Istio directly - but enables an Istio app to use the Jaeger tracer to report additional tracing data about their app. Not sure Istio should be including docs about how to instrument an application using Jaeger - that can be found in the jaeger docs. Its possible a cross reference could be added somewhere.

**Comment by ericvn** [comment]
Is it a regression to have it in the demo profile from 1.3 (helm) and not to have it in the demo profile in 1.4 (istioctl)?

**Comment by objectiser** [comment]
Yes it is a regression.

**Comment by howardjohn** [comment]
Fixed https://github.com/istio/installer/pull/515/files thanks @douglas-reid !

**Comment by ericvn** [comment]
Thanks everyone.
