### ISSUE TITLE
Ingress SDS integration tests are flaky

### ISSUE THREAD

**Issue by JimmyCYJ** [istio/istio#18651]
**Bug description**
The ingress SDS Secret rotation tests are flaky

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by JimmyCYJ** [comment]
@pitlv2109 could you check if the tests are still flaky, and remove the flakiness label if they are not flaky any more?

**Comment by pitlv2109** [comment]
They were pretty stable before my change. https://testgrid.k8s.io/istio_istio_postsubmit#integ-security-k8s-tests_istio_postsubmit (look at the sds ingress tests at the bottom).

I sent out https://github.com/istio/istio/pull/19329 to revert the change and remove the flaky label. I'm closing this issue now, feel free to reopen.
