### ISSUE TITLE
Concurrent access fatal error

### ISSUE THREAD

**Issue by elfinhe** [istio/istio#18664]
···
Applying manifest for component Citadel
fatal error: concurrent map writes
goroutine 169 [running]:
runtime.throw(0x3240c8c, 0x15)
    runtime/panic.go:774 +0x72 fp=0xc000b87e58 sp=0xc000b87e28 pc=0x102de32
runtime.mapassign_faststr(0x2e58b40, 0xc000975d40, 0x3223a6b, 0x7, 0x400000001)
    runtime/map_faststr.go:211 +0x417 fp=0xc000b87ec0 sp=0xc000b87e58 pc=0x1012cf7
istio.io/operator/pkg/manifest.applyRecursive.func1(0x3223a6b, 0x7, 0xc000450d50, 0x21, 0x400000001, 0xc000000000, 0x0, 0x0, 0xc000884a50, 0xc000975d40, ...)
    istio.io/operator@v0.0.0-20191105031444-4d7f1ed76494/pkg/manifest/installer.go:246 +0x13a fp=0xc000b87f88 sp=0xc000b87ec0 pc=0x2b1911a
runtime.goexit()
    runtime/asm_amd64.s:1357 +0x1 fp=0xc000b87f90 sp=0xc000b87f88 pc=0x105b731
created by istio.io/operator/pkg/manifest.applyRecursive
    istio.io/operator@v0.0.0-20191105031444-4d7f1ed76494/pkg/manifest/installer.go:240 +0x19a

···

**Comment by ericvn** [comment]
Looks like #18657
