### ISSUE TITLE
Remove the ability to disable Galley

### ISSUE THREAD

**Issue by geeknoid** [istio/istio#18662]
We need to remove the ability to remove Galley from Istio deployments. Galley implements the validation webhook and without this hook in place, it's possible to insert bogus configuration into the API server, which can lead to Istio to have unexpected and/or undefined behavior.

**Comment by howardjohn** [comment]
I think this is a really bad idea, and strongly recommend we don't go down this path
* A large number of big Istio users are explicitly disabling Galley today
* Knative, and other "minimal" installs disable galley
* This adds a hard dependency on citadel (or some other way to get certs) as well, which is not desired
* Many users do validation offline in CI. 
* Validation webhook must be opt in. It is a cluster wide resource with nearly admin privs - not acceptable for many situations. if we are really worried about bad config coming in, we can always validate it internally and filter out invalid config

Any issue titled "Remove the ability to disable ____" where ____ has valid use cases seems suspect to me
