### ISSUE TITLE
Stackdriver Tracing: incorrect env vars

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#18680]
When annotation and attribute params are not set, the template inserts `nil` thereby injecting an env var with value = `nil`.

The following was obtained by doing kubectl describe pods

```
     STACKDRIVER_TRACING_ENABLED:                       true
      STACKDRIVER_TRACING_DEBUG:                         false
      STACKDRIVER_TRACING_MAX_NUMBER_OF_ANNOTATIONS:     nil
      STACKDRIVER_TRACING_MAX_NUMBER_OF_ATTRIBUTES:      nil
      STACKDRIVER_TRACING_MAX_NUMBER_OF_MESSAGE_EVENTS:  nil
```

**Comment by howardjohn** [comment]
@gargnupur this needs the same patch in istio/installer I think?

**Comment by gargnupur** [comment]
@howardjohn : Yes...

**Comment by howardjohn** [comment]
Still waiting on a patch to istio/installer

**Comment by howardjohn** [comment]
@gargnupur istio/install is the default installation method now so this needs a backport
