### ISSUE TITLE
SDS doesn't work with version 1.3.4

### ISSUE THREAD

**Issue by myidpt** [istio/istio#18690]
**Bug description**

**Expected behavior**
Following https://istio.io/docs/setup/install/helm/
SDS should be configured to work correctly.

**Steps to reproduce the bug**
Following https://istio.io/docs/setup/install/helm/
The auto-injected sidecars do not get the currect SDS configuration. 

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.3.4

**How was Istio installed?**
https://istio.io/docs/setup/install/helm/

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

**Comment by myidpt** [comment]
Jimmy, could you take a look? Thanks.

**Comment by howardjohn** [comment]
Don't we have tests for this?

**Comment by myidpt** [comment]
Sorry, false alarm. SDS works. I will double check again.

**Comment by myidpt** [comment]
It works. I think the error was due to my misconfiguration. Sorry for the confusion.
