### ISSUE TITLE
Istioctl analyze should fail more visibly when it can't parse files

### ISSUE THREAD

**Issue by zerobfd** [istio/istio#18699]
**Bug description**
`istioctl analyze` prints "No validation issues found" and returns a 0 exit code on failing to parse all input files.

**Expected behavior**
Nonzero exit code and possibly a less optimistic message.

**Steps to reproduce the bug**
'''
cd istio/istioctl/cmd
go run istioctl/main.go x analyze testdata/mesh-config.yaml
'''

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
master

**How was Istio installed?**
n/a

**Environment where bug was observed (cloud vendor, OS, etc)**
local dev env

**Comment by zerobfd** [comment]
@sushicw from offline chat, maybe change messaging to "these files were skipped" or "(but there were errors)" and remove the check mark from output in addition to error code.

**Comment by sushicw** [comment]
Also: any failure to read files should produce a nonzero exit code.
