### ISSUE TITLE
Envoy: status code 500, response_flags="-"

### ISSUE THREAD

**Issue by LinLshare** [istio/istio#18694]
**Bug description**
when  using istio, I found the following error from prometheus by `istio_requests_total{destination_service_namespace="my-ns",response_code=~"^5.*",response_flags="-"}`

```
✔istio_requests_total{connection_security_policy="none",destination_app="my-app",destination_principal="unknown",destination_service="my-app.my-ns.svc.cluster.local",destination_service_name="my-app",destination_service_namespace="my-ns",destination_version="stable",destination_workload="my-app-stable",destination_workload_namespace="my-ns",instance="10.9.68.130:42422",job="istio-mesh",permissive_response_code="none",permissive_response_policyid="none",reporter="destination",request_protocol="http",response_code="500",response_flags="-",source_app="unknown",source_principal="unknown",source_version="unknown",source_workload="unknown",source_workload_namespace="unknown"}
```

**Expected behavior**
no such error: `response_flags="-" & status code=500`

**Steps to reproduce the bug**
1. install istio 1.3.4
2. deploy your service
3. query `istio_requests_total{destination_service_namespace="my-ns",response_code=~"^5.*",response_flags="-"}` in prometheus dashboard

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
client version: 1.3.4
control plane version: 1.3.4

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-eks-5876d6", GitCommit:"5876d6b7429820450950ade17fe7b4bf5ccada7f", GitTreeState:"clean", BuildDate:"2019-09-24T20:54:25Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
install istio-1.3.4 with default values by helm & tiller

**Environment where bug was observed (cloud vendor, OS, etc)**
Amazon Linux 2

**Comment by howardjohn** [comment]
What makes you think this is an Istio issue? It looks like the application just returned a 500

**Comment by LinLshare** [comment]
I am curious about `response_flags="-" ` exactly means. However I will open debug log to find out what happen in my service.

**Comment by LinLshare** [comment]
I find out it's my application returned a 500, so I close the issue.
