### ISSUE TITLE
Handle Abort in e2e such that namespace gets deletes when a Jenkins job is interrupted

### ISSUE THREAD

**Issue by sebastienvas** [istio/istio#187]
Currently this leaves a namespace behind

**Comment by sebastienvas** [comment]
Bazel does not pass the SIGINT down to the test. Since we want to run test with Bazel it is debatable if we want to implement this anyway but if we do, there need to be a refactor of the code to support context. Bringing down priority for this item.

**Comment by linsun** [comment]
I assume this is still an issue.  not blocking release, propose to defer.

**Comment by sebastienvas** [comment]
this will be resolved by cluster pool.
