### ISSUE TITLE
Installing Istio with `istioctl` and tracing enabled results in a non-deployable Jaeger pod

### ISSUE THREAD

**Issue by jpapejr** [istio/istio#18707]
**Bug description**
When installing Istio from the `istioctl x manifest apply ...` method with `--set values.tracing.enabled=true` results in a tracing pod that cannot be scheduled due to the incorrect container image name being used. 
```Warning  Failed     51s (x4 over 2m18s)  kubelet, 10.95.207.94  Failed to pull image "docker.io/jaegertracing/all-on-one:1.12": rpc error: code = Unknown desc = failed to resolve image "docker.io/jaegertracing/all-on-one:1.12": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed```

Editing the `istio-tracing` deployment and chaning the image to `docker.io/jaegertracing/all-in-one:1.12` and saving corrects the problem. 

**Expected behavior**
`istio-tracing` deployment should come up successfully

**Steps to reproduce the bug**
1. Create k8s cluster (I used v1.14.8+IKS)
2. Target cluster and run `istioctl x manifest apply --set values.tracing.enabled=true`
3. Wait for completion and then `kubectl get pods -n istio-system` to see failed pod start

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8+IKS", GitCommit:"e92d4d66e0fbcf26d180f9564d6d310341a98481", GitTreeState:"clean", BuildDate:"2019-10-17T11:20:25Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

------------------------------------------------

istioctl version --remote
client version: 1.3.4
control plane version: release-1.3-20191106-10-15

```

**How was Istio installed?**
`istioctl x manifest apply --set values.tracing.enabled=true`

**Environment where bug was observed (cloud vendor, OS, etc)**
IBM Cloud Kubernetes Service (IKS)

**Comment by jpapejr** [comment]
Cluster state archive is baking right now - will attach when done.

**Comment by howardjohn** [comment]
This is fixed on 1.4

**Comment by jpapejr** [comment]
[istio-dump.tar.gz](https://github.com/istio/istio/files/3816816/istio-dump.tar.gz)

**Comment by jpapejr** [comment]
@howardjohn I figured as must after searching the repo for instances of the image name typo. Do we need this issue then; any plans to backport the correction to 1.3.x?
