### ISSUE TITLE
Helm is broke. How do I get the yaml for prometheus and grafana?

### ISSUE THREAD

**Issue by mabushey** [istio/istio#18702]
Istio version: 1.3.4 (Installed via the awesome Bonzai operator)
Helm: v2.16.0 (no Tiller)
```
git clone https://github.com/istio/istio.git helm/istio
cd helm/istio
git checkout release-1.3
cd ../..

✗ helm template helm/istio/install/kubernetes/helm/istio/charts/prometheus  --output-dir ./helm --name prometheus --namespace istio-system
Error: render error in "prometheus/templates/tests/test-prometheus-connection.yaml": template: prometheus/templates/tests/test-prometheus-connection.yaml:1:14: executing "prometheus/templates/tests/test-prometheus-connection.yaml" at <.Values.global.enableHelmTest>: nil pointer evaluating interface {}.enableHelmTest

✗ helm template helm/istio/install/kubernetes/helm/istio/charts/grafana  --output-dir ./helm --name grafana --namespace istio-system
Error: render error in "grafana/templates/tests/test-grafana-connection.yaml": template: grafana/templates/tests/test-grafana-connection.yaml:1:14: executing "grafana/templates/tests/test-grafana-connection.yaml" at <.Values.global.enableHelmTest>: nil pointer evaluating interface {}.enableHelmTest
```

How do I get the yaml config for Prometheus, Grafana, and Jaeger? I can easily manually update or use SED to update any values. I just don't get why such a bloated, complex, and broken system is used to do something so simple.

**Comment by douglas-reid** [comment]
One option:

`$ helm template --name istio --namespace istio-system install/kubernetes/helm/istio -x charts/prometheus/templates/deployment.yaml`

You probably want to list all the templates that you want to generate using multiple `-x <template>` bits, like so:

`$ helm template --name istio --namespace istio-system install/kubernetes/helm/istio -x charts/prometheus/templates/deployment.yaml -x charts/prometheus/templates/configmap.yaml`

For further support, please use the forums, which is a more appropriate place for this discussion.

**Comment by mabushey** [comment]
Thanks for the help @douglas-reid . :)
