### ISSUE TITLE
Add integration tests to cover Citadel running as plugin CA mode

### ISSUE THREAD

**Issue by JimmyCYJ** [istio/istio#18714]
**Describe the feature request**
We don't have any integration tests covering Citadel running as plugin mode.
At least we need to add these test cases.

1. Citadel uses plugin root cert to sign workload certificates.
1. Manually rotating the plugin root cert and restarting Citadel will refresh workload certificates properly.
1. Switching Citadel from self signed CA mode to plugin CA mode will refresh workload certificates properly.

**Describe alternatives you've considered**

**Additional context**

#13439

**Comment by JimmyCYJ** [comment]
cc @myidpt

**Comment by myidpt** [comment]
Thanks Jimmy. This is very helpful.

**Comment by JimmyCYJ** [comment]
This is done in https://github.com/istio/istio/pull/22833 and https://github.com/istio/istio/pull/22671
