### ISSUE TITLE
istioctl analyze --discovery flag should be a bool

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#18718]
Standard bool flag behavior in istioctl/kubectl is `--flag` and `--flag=false` and `--flag=true`. But for discovery you must set `--flag=true` or `--flag=false`, `--flag` does not work

```
$ istioctl x analyze --discovery
Error: flag needs an argument: --discovery
```

**Comment by sushicw** [comment]
The tricky part here is that we actually need this to be tri-state: true, false, or unset, since the "default" behavior differs depending on whether we're hitting a live cluster or not. 

I'm not sure Cobra supports letting us have a tri-state flag without requiring an argument.

**Comment by ayj** [comment]
I think users will find that confusing (I do). If its tri-state we should probably use an enum and not a bool. What's the behavior in the three cases?

**Comment by sushicw** [comment]
If the flag is unset, enable discovery if we're using a live cluster (in other words, if `--use-kube` is also present). Otherwise, use the value of the flag.

**Comment by sushicw** [comment]
One alternative is to use a pair of binary flags to get the same behavior, e.g. `--discovery-enabled` and `--discovery-disabled`. This is more verbose, but perhaps also more obvious? 

A bit of a tangent, but it's also possible that the "discovery" name just kinda sucks here. We could just as well go with something like `--include-kube-resources` + `--exclude-kube-resources`. Or if we want to go with enums we could have something like `--kube-resources=included|excluded|auto`.

**Comment by ayj** [comment]
`--discovery` is only valid when accessing a live cluster. Can you make it a true boolean which is only observed when `--use-kube=true`? 

```
# Analyzing a live cluster. --discovery is observed.
--use-kube=true && --discovery=true   # enabled (default)
--use-kube=true && --discovery=false  # disabled, consider a warning/error if the user selects this combination.

# service discovery analysis is run on live clusters.
--use-kube=false && --discovery=true   # disabled
--use-kube=false && --discovery=false  # disabled
`

**Comment by sushicw** [comment]
--discovery also affects behavior when looking at files only. (This is one reason I'm not enamored of the current naming). 

The reasoning is that although we expect that in most cases users won't be including k8s resources in the set of files to analyze, we want them to be able to do so if they wish. So the default behavior is to only include kube resources if `--use-kube` is set, but we want users to be able to override that both for files-only and live cluster cases.

**Comment by sushicw** [comment]
It looks like Cobra does provide a way to see if a flag was set or not:

```go
if cmd.Flags().Changed("someFlag") {
    // user set the flag
}
```
So @howardjohn 's original ask should be straightforward. 

I still think the `--discovery` name is sub-optimal. As @ayj pointed out in an offline discussion, ``--kube-resources``` is also problematic because it's not obvious what resources are included in that set. Longer-term, we probably need more granular control over what resources get included or excluded, but in any case we should keep trying to make the default "just work" for the majority of users.
