### ISSUE TITLE
Improve dashboards for client-only services

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio#18728]
**Describe the feature request**
The istio grafana dashboards don't make monitoring traffic to / out of an egress gateway very easy. In fact, it is almost impossible to accurately monitor services that only send traffic with the existing dashboards.

The dashboards should be improved to better support egress gateway and client-only use cases.

I believe this is primarily a result of using `reporter=destination` for paramaterizing queries in a bunch of places (variable templates, etc.). But there is likely a bunch of other places that could be improved.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by esnible** [comment]
@douglas-reid Is 1.5 too aggressive for this item?
