### ISSUE TITLE
citadel dashboard appears to not show proper data

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio#18729]
**Bug description**
In debugging session with a few others, using an mTLS enabled cluster, saw a dash like the following:

![image](https://user-images.githubusercontent.com/21148125/68352177-754b2f00-00ba-11ea-96c0-1892578d897f.png)

It didn't seem like the number of certificates signed, etc., was correct.

**Expected behavior**
Report correct behavior

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.4.0-beta2

**How was Istio installed?**
helm ?? It wasn't my cluster.

/cc @Monkeyanator

**Comment by howardjohn** [comment]
@istio/wg-security-maintainers this is a P0 for 1.4 which is shipping ASAP, please assign an owner

**Comment by myidpt** [comment]
Thanks for reporting. We will fix it. But seeing the issue, I don't think it's a blocker for 1.4.

**Comment by douglas-reid** [comment]
Did this ever end up fixed?
