### ISSUE TITLE
edge ingress proxy must be able to validate identity of application instance

### ISSUE THREAD

**Issue by shalako** [istio/istio#1873]
Application developers need to be able to obtain troubleshooting data specific to instances of an application. As an example, Spring apps expose endpoints called Actuator endpoints that provide instance-specific telemetry. 

The Cloud Foundry edge routers facilitate this by routing requests with an HTTP header constructed from the internal identifier for the application and from an index representing the instance: https://docs.cloudfoundry.org/concepts/http-routing.html#app-instance-routing.

In addition, the Cloud Foundry routers use TLS to validate the identity of each instance to guard against port reuse as containers come and go in large multi-tenant environments. An Envoy colocated with each app instance hosts a TLS certificate created with a unique identifier in the certificate domain SAN. The router also knows this identifier and will retry a different app instance if validation fails.

We need to expose this unique instance identifier to Envoy in the Pilot APIs, and be able to configure  Envoy to use it to validate the domain SAN in the upstream server's certificate. 

If we were to do this with the v1 API, I'd recommend adding a new tag to the SDS API response:

```
$ curl /v1/registration/:app-guid

{
  "hosts": [
    {
      "ip_address": "...",
      "port": "...",
      "tags": {
        "az": "...",
        "canary": "...",
        "load_balancing_weight": "...",
        "server_cert_domain_san": "app-instance-guid"
      }
    }
  ]
}
```

**Comment by shalako** [comment]
@rshriram @kyessenov

**Comment by rshriram** [comment]
cc @louiscryan / @ZackButcher 

I don't think you need to tweak the SDS API. Take a look at how the auth configuration is being setup in proxy/envoy/route.go .. We setup an array of SAN fields in every cluster's SSL config block. You can simply collect all the instance SAN ids and populate this array in the cluster's ssl config. AS long as each cluster has unique set of instances, this will work without any issue.

Do you also need to validate inbound connection's identities or is it just outbound TLS only? If its mTLS, we have the necessary machinery. We just need to make the cert provider be pluggable. If its just TLS, then we might need to expose some mesh level config option to enable one-way TLS.

**Comment by shalako** [comment]
Thank you for taking a look Shriram. 

This is for inbound requests only, and is for the TLS handshake between a shared tier of edge Envoys (running on independently scalable VMs) providing routing and load balancing for all apps on the platform, and the Envoys collocated with each application instance (think cluster member host in Envoy API, or K8s pod). 

Each collocated Envoy has a certificate with a unique identifier in the domain SAN that represents the app instance and when an edge Envoy makes a load balancing decision and initiates the TLS handshake with the collocated Envoy, it must accept only one expected identifier as the SAN in the cert. If the SAN does not match the expected identifier, the edge router should remove the host from the cluster and try a different host, or return a 503 if no members of the cluster can be validated.

**Comment by rshriram** [comment]
On Tue, Nov 28, 2017 at 2:26 AM Shannon Coen <notifications@github.com>
wrote:

> Thank you for taking a look Shriram.
>
> This is for inbound requests only, and is for the TLS handshake between a
> shared tier of edge Envoys (running on independently scalable VMs)
> providing routing and load balancing for all apps on the platform, and the
> Envoys collocated with each application instance (think cluster member host
> in Envoy API, or K8s pod).
>
> Each collocated Envoy has a certificate with a unique identifier in the
> domain SAN that represents the app instance and when an edge Envoy makes a
> load balancing decision and initiates the TLS handshake with the collocated
> Envoy, it must accept only one expected identifier as the SAN in the cert.
> If the SAN does not match the expected identifier, the edge router should
> remove the host from the cluster and try a different host, or return a 503
> if no members of the cluster can be validated.
>

Yeah. This needs to be checked on the outbound path (from the lb Envoys aka
ingress tier). We have the ability to validate SAN when making tls
connection.

What I am not sure about is whether we retry a different host in the
cluster if the San does not match.

@lita or @myidpt or @PiotrSikora or finally @mattklein123

**Comment by louiscryan** [comment]
This feature is effectively the same as the 'secure naming' features being worked on by the security folks. 

Assigning to Tao for triage.

**Comment by wattli** [comment]
@myidpt , can you help to take a look please? Thanks.

**Comment by shalako** [comment]
Please link to an issue or gdoc where I can learn more about "secure naming" and validate that a gateway can use instance identity to validate routing consistency. I found #2120 but there's no info there.

**Comment by shalako** [comment]
This is still needed; CF teams should get to it within the next couple of months.
