### ISSUE TITLE
SDS Spiffe ID, currently in SDS the spiffe are hard-coded to a particular format there is no easy way to change the format.

### ISSUE THREAD

**Issue by abhijitherekar** [istio/istio#18743]
**Describe the feature request**
Currently, the spiffe ID format is hard-coded in Istio SDS server. There should be a easy way to configure the Spiffe ID format. 

**Describe alternatives you've considered**
The alternative way to change the spiffe ID is to manually create destination rule for each service created in the cluster. 

**Additional context**
I have discussed on slack with @JimmyCYJ about this issue.

**Comment by incfly** [comment]
I don't know what format you want, this is very unlikely to happen and the use case is vague, given Istio only issues fixed format SPIFFE cert.

**Comment by incfly** [comment]
If you want to reopen, please explain with full e2e worklfow of what format you need, how that can carries namespace and k8s service account information.
