### ISSUE TITLE
proxy test integration:mixer_fault_test is flaky

### ISSUE THREAD

**Issue by jwendell** [istio/istio#18756]
Re: https://github.com/istio/proxy/pull/2533

Old issue? https://github.com/istio/istio/issues/15732

**Comment by PiotrSikora** [comment]
@duderino could you take a look at mixer_fault_test? It became extremely flaky lately.

**Comment by PiotrSikora** [comment]
It's repeatedly failing in `FailOpenAndSendPolicyResponseSlowly`:
```
[ RUN      ] MixerFaultTest.FailOpenAndSendPolicyResponseSlowly
test/integration/mixer_fault_test.cc:821: Failure
Expected equality of these values:
  client->responsesReceived()
    Which is: 456
  requests_to_send
    Which is: 900
Stack trace:
  0x24c53c9: Mixer::Integration::MixerFaultTest_FailOpenAndSendPolicyResponseSlowly_Test::TestBody()
  0x62a4a64: testing::internal::HandleSehExceptionsInMethodIfSupported<>()
  0x629505b: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0x6282c53: testing::Test::Run()
  0x6283617: testing::TestInfo::Run()
... Google Test internal frames ...

test/integration/mixer_fault_test.cc:823: Failure
Expected equality of these values:
  client->class2xxResponses()
    Which is: 456
  requests_to_send
    Which is: 900
Stack trace:
  0x24c5542: Mixer::Integration::MixerFaultTest_FailOpenAndSendPolicyResponseSlowly_Test::TestBody()
  0x62a4a64: testing::internal::HandleSehExceptionsInMethodIfSupported<>()
  0x629505b: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0x6282c53: testing::Test::Run()
  0x6283617: testing::TestInfo::Run()
... Google Test internal frames ...

test/integration/mixer_fault_test.cc:826: Failure
Expected equality of these values:
  client->responseTimeouts()
    Which is: 444
  0
Stack trace:
  0x24c59cb: Mixer::Integration::MixerFaultTest_FailOpenAndSendPolicyResponseSlowly_Test::TestBody()
  0x62a4a64: testing::internal::HandleSehExceptionsInMethodIfSupported<>()
  0x629505b: testing::internal::HandleExceptionsInMethodIfSupported<>()
  0x6282c53: testing::Test::Run()
  0x6283617: testing::TestInfo::Run()
... Google Test internal frames ...

[  FAILED  ] MixerFaultTest.FailOpenAndSendPolicyResponseSlowly (14390 ms)
```
to the point that I'm not sure whether it's flaky test with too low timeout or a real issue...

**Comment by duderino** [comment]
The failures here are different than in #15732

In #15732 the routine / happy path case (no faults, so no recovery needed) was failing.

In this case, the mixer filter is configured to timeout and send a success response if the policy server takes too long to respond.  For some reason that's no longer passing all the time

**Comment by duderino** [comment]
It's imperfect, but the first failure I can find is on 10/30:  https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_proxy/2472/proxy-presubmit/3555

**Comment by PiotrSikora** [comment]
That PR didn't even touch C++ code, so it definitely didn't introduce this issue.

**Comment by duderino** [comment]
At this point I'm convinced it's a test flake and not a real issue.

On release-1.4 branch, I can consistently reproduce the failure with 5 concurrent test runs.  At 4 concurrent test runs, it flakes occasionally.  It never flakes at 3 or less.

On release-1.3 branch, I can consistently reproduce the failure with 4 current test runs, occasionally with 3, never with less.

So things are actually getting better, not worse.

My guess is there is more external pressure on these tests (e.g., noisy neighbor) which is why they started flaking recently.

**Comment by PiotrSikora** [comment]
@duderino thanks for investigating! Yeah, I agree that it's most likely noisy neighbor, since those tests started failing out of nowhere. The question is, should we increase the timeout to make it more resilient to those timing issues and eliminate flakiness?
