### ISSUE TITLE
customizing components via istioctl is confusing in docs

### ISSUE THREAD

**Issue by jmazzitelli** [istio/istio#18755]
Looking at this page:

https://preliminary.istio.io/docs/setup/install/istioctl/

It is confusing how you customize components.

I read this about how to use istioctl to customize components:

```
You can also use this approach to set the component-level configuration, such as enabling the node agent:

$ istioctl manifest apply --set security.components.nodeAgent.enabled=true
```

I see the setting is "security.components.nodeAgent". OK, that looks familiar, I see those names in [the chart of components here](https://preliminary.istio.io/docs/setup/install/istioctl/#identify-an-istio-feature-or-component):

![image](https://user-images.githubusercontent.com/2029470/68419994-58ba0000-0169-11ea-888d-f441bf7e91e9.png)

I want to know how to customize kiali, so I find that in the other chart of telemetry components here:

![image](https://user-images.githubusercontent.com/2029470/68420035-6f605700-0169-11ea-900c-dec58c7708af.png)

So, taking these two things together, I assume I can use `--set telemetry.components.kiali.enabled=true` to enable Kiali.

But that fails:

```
$ istioctl manifest apply --set telemetry.components.kiali.enabled=true
Failed to generate and apply manifests, error: failed to generate tree from the set overlay, error: bad path=value: telemetry.components.kiali.enabled=true
```

So two things that the doc here needs to address:

1) This is confusing or not correct, at least for the telemetry component "kiali"

2) How DO you customize telemetry components (like "kiali")

**Comment by jmazzitelli** [comment]
Another confusing thing related to this is: https://preliminary.istio.io/docs/setup/install/istioctl/#customize-kubernetes-settings

```
Each component has a KubernetesResourceSpec, which allows the following settings to be changed. Use this list to identify the setting to customize:

Resources
...
```

But again this doesn't work like the docs make it seem. "Each component has..." tells me I can follow the example on this page (the example of `$ istioctl manifest apply --set security.components.nodeAgent.enabled=true`). But if I try to pass this in (based on the chart where it shows Telemetry with a component of Telemetry), it fails:

`--set telemetry.components.telemetry.resources.requests.memory=100Mi`

I tried different combinations such as `telemetry.components.resources.requests.memory` and `telemetry.components.telemetry.resources.requests.memory` and `values.telemetry.resources.requests.memory` to no avail.

So it appears (to me, at least) that this page is either incomplete or incorrect when it talks about customizing via istioctl and these `--set` options.

**Comment by jmazzitelli** [comment]
Just a followup on my previous comment, I found out that there is a "k8s" part in the setting name for those resources settings. The docs don't specify this, or (if they do) it isn't clear. But these are the setting I needed: `telemetry.components.telemetry.k8s.resources.requests.memory` (notice `k8s` in there)

**Comment by richardwxn** [comment]
Looks like most of the examples are presented in IstioControlPlane CR yaml format, we may need to add more examples with set override. Although they are essentially the same but users might find it hard to do with a this kind of long set path.

**Comment by elvizlai** [comment]
+1

**Comment by kgamanji** [comment]
**Note: Addons for telemetry can be configured only via Helm chart variables.**


Hence, I have managed to customize kiali via: 
- command line (using Helm parameters)
```istioctl manifest apply  --set values.kiali.enabled=true```
- custom manifest files (integration  between Heml and IstioCtl commands):
```
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
# some IstioCtl commands
  trafficManagement:
    components:
      pilot:
        k8s:
          resources:
            requests:
              memory: 675Mi
  values:
    kiali:
      enabled: true
```

**Comment by howardjohn** [comment]
Strongly agree - there is a few issues around this so I suggest we consolidate to simplify. Lets track in https://github.com/istio/istio/issues/22950
