### ISSUE TITLE
Cannot remove an install done using istioctl manifest

### ISSUE THREAD

**Issue by ericvn** [istio/istio#18765]
**Bug description**

Normally I do a `istioctl manifest apply ...` to install and then a `istioctl manifest generate ... | kubectl delete -f -` to remove it. Sometimes when trying to remove I get an error like:
error: error parsing STDIN: error converting YAML to JSON: yaml: line 3: mapping values are not allowed in this context.

**Expected behavior**

I should be able to uninstall without an error

**Steps to reproduce the bug**

I ran `istioctl manifest apply -f install/kubernetes/operator/examples/multicluster/values-istio-multicluster-gateways.yaml --force` to install Istio.

To uninstall I tried  `istioctl manifest generate -f install/kubernetes/operator/examples/multicluster/values-istio-multicluster-gateways.yaml --force | kubectl delete -f -`

and got an error:
```
error: error parsing STDIN: error converting YAML to JSON: yaml: line 3: mapping values are not allowed in this context
```

If I instead piped to a file, the top portion contained:
```
Run the command with the --force flag if you want to ignore the validation error and proceed.
Run the command with the --force flag if you want to ignore the validation error and proceed.
Proceeding despite the following validation errors: 
unknown field "podDNSSearchNamespaces" in v1alpha1.GlobalConfig
Run the command with the --force flag if you want to ignore the validation error and proceed.
Proceeding despite the following validation errors: 
unknown field "podDNSSearchNamespaces" in v1alpha1.GlobalConfig
Run the command with the --force flag if you want to ignore the validation error and proceed.
Proceeding despite the following validation errors: 
unknown field "podDNSSearchNamespaces" in v1alpha1.GlobalConfig
```

If I removed that from the file and did a `kubectl delete -f <file>` things were uninstalled.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

A daily 1.4 build: istio-1.4-alpha.8389f528ad4102e20ce1fe950b55c5bf61a1e54a
(does contain https://github.com/istio/operator/pull/536 from what I am told).

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
@ericvn can you try this again? The issue was a log message to stdout which has been fixed

**Comment by ericvn** [comment]
I am unable to recreate at this time. I know there where a number of changes in this space.
