### ISSUE TITLE
enforce sidecar inject at namespace level regardless pod-level overrides

### ISSUE THREAD

**Issue by dontreboot** [istio/istio#18767]
**Describe the feature request**
The default Istio installation inject sidecar proxy for pods when a namespace has label `istio-injection=enabled`; however, individual pod can add `sidecar.istio.io/inject: "false"` to opt out.

I think there should be an option to remove the ability to disable sidecar injection for pods.
I image many times namespaces are created by some Kubernetes admins and pod owners potentially are part of different teams. The kubernetes admins enforce namespace level sidecar injection policy (and other service mesh policies) and don't want pod owners to bypass that by not using the sidecar proxy.

**Additional context**

**Comment by howardjohn** [comment]
I think there is some field like `alwaysInjectSelector` that may satisfy this - not sure though, I have never tried this.

Note that they can still always add annotations to bypass envoy for certain ports/ip (or all of them!). Or set their own iptables rules. Maybe you can get the right set of rules to lock all of those down, but we have not tested nor support this case so its not likely to be secure.

Unless you just want a low effort "teams have to try really hard to bypass the proxy" rather than "no one can possibly bypass the proxy", Istio can't really support this case - at least today.

**Comment by dontreboot** [comment]
> I think there is some field like `alwaysInjectSelector` that may satisfy this - not sure though, I have never tried this.
> 

That doesn't help because Pod level annotation has higher priority than the namespace label. 

from https://istio.io/docs/setup/additional-setup/sidecar-injection/:
It’s worth noting that annotations in the pods have higher precedence than the label selectors. If a pod is annotated with sidecar.istio.io/inject: "true/false" then it will be honored. So, the order of evaluation is:

Pod Annotations → NeverInjectSelector → AlwaysInjectSelector → Default Policy

One idea I have is to introduce a new label `istio-injection=always' to namespaces and istio will enforce Istio-injection regardless what the pod annotations are

> Note that they can still always add annotations to bypass envoy for certain ports/ip (or all of them!). Or set their own iptables rules. Maybe you can get the right set of rules to lock all of those down, but we have not tested nor support this case so its not likely to be secure.
> 

Which annotations are these?

> Unless you just want a low effort "teams have to try really hard to bypass the proxy" rather than "no one can possibly bypass the proxy", Istio can't really support this case - at least today.

**Comment by howardjohn** [comment]
See the full list here https://preliminary.istio.io/docs/reference/config/annotations.html

For example `traffic.sidecar.istio.io/excludeOutboundIPRanges`

Does kubernetes support webhooks as a means to enforce security policies like this? I would think for this level of control they would require use of networkpolicy or other config
