### ISSUE TITLE
Multi cluster installs are not working

### ISSUE THREAD

**Issue by ericvn** [istio/istio#18785]
**Bug description**

At last check, all 3 of the multi cluster install scenarios are failing on istio.io. This issue is for changes required in the `istioctl` tooling. There was a beta.3 build last night but I now that the latest installer PR https://github.com/istio/installer/pull/517 is not in that. It is in the 1.4-alpha.b632400c69f127ae453352784567497ddbf05f3a build which I will test with today.

**Expected behavior**

Documented scenarios should work

**Steps to reproduce the bug**

Forthcoming with testing later today (testing on latest build above).

There is a sister documentation issue to this: https://github.com/istio/istio.io/issues/5515

**Comment by ericvn** [comment]
#18656 is an earlier issue. It may or may not be resolved with the  istio/installer#517 PR.

**Comment by ericvn** [comment]
Trying the replicated control plane example today using the latest istio 1.4 build (1.4-alpha.b632400c69f127ae453352784567497ddbf05f3a), which has the above PR in it, I get the following missing field:
istioctl manifest apply \
    -f install/kubernetes/operator/examples/multicluster/values-istio-multicluster-gateways.yaml --set coreDNS.enabled=true

Failed to generate and apply manifests, error: failed to generate manifest: input file failed validation with the following errors: unknown field "podDNSSearchNamespaces" in v1alpha1.GlobalConfig

**Comment by ericvn** [comment]
Some weirdness on the second cluster. I ran the same `istioctl manifest apply \ -f install/kubernetes/operator/examples/multicluster/values-istio-multicluster-gateways.yaml --set coreDNS.enabled=true --force`

I see this in the output:
```
Component CoreDNS failed install:
=================================
Error: error running kubectl: exit status 1

Error detail:

Error from server (NotFound): error when creating "STDIN": namespaces "istio-system" not found (repeated 4 times)



clusterrole.rbac.authorization.k8s.io/istiocoredns created
clusterrolebinding.rbac.authorization.k8s.io/istio-istiocoredns-role-binding-istio-system created
```
I did not pre-create the `Istio-system` namespace but it was created as part of the install so maybe an ordering issue. When removing the install, the nsamespace was removed.

**Comment by ericvn** [comment]
@ostromart @elfinhe FYI

**Comment by ericvn** [comment]
Current issue is the `replicated Control Plane` example uses the egress gateway and I am having an issue trying to create it. I updated the command and using `istioctl manifest apply -f install/kubernetes/operator/examples/multicluster/values-istio-multicluster-gateways.yaml --set hub=gcr.io/istio-testing --set tag=1.4-alpha.b632400c69f127ae453352784567497ddbf05f3a --set coreDNS.enabled=true   --set values.gateways.istio-egressgateway.enabled=true --force`

and I see this in the output:
```
Component EgressGateway installed successfully:
===============================================
No resources found



Component IngressGateway installed successfully:
================================================

serviceaccount/istio-ingressgateway-service-account unchanged
deployment.apps/istio-ingressgateway configured
destinationrule.networking.istio.io/istio-multicluster-destinationrule unchanged
envoyfilter.networking.istio.io/istio-multicluster-ingressgateway unchanged
gateway.networking.istio.io/ingressgateway unchanged
gateway.networking.istio.io/istio-multicluster-ingressgateway unchanged
sidecar.networking.istio.io/default unchanged
poddisruptionbudget.policy/ingressgateway unchanged
horizontalpodautoscaler.autoscaling/istio-ingressgateway unchanged
service/istio-ingressgateway unchanged
```
and no egress gateway service or pod.

**Comment by ericvn** [comment]
@ostromart said I should use `--set gateways.components.egressGateway.enabled=true` and this created the egress gateway but saw following in the output (Note this was ingress):
```
Component IngressGateway failed install:
========================================
Error: error running kubectl: exit status 1

Error detail:

Error from server (AlreadyExists): error when creating "STDIN": destinationrules.networking.istio.io "istio-multicluster-destinationrule" already exists (repeated 1 times)



serviceaccount/istio-ingressgateway-service-account created
deployment.apps/istio-ingressgateway created
envoyfilter.networking.istio.io/istio-multicluster-ingressgateway created
gateway.networking.istio.io/ingressgateway created
gateway.networking.istio.io/istio-multicluster-ingressgateway created
sidecar.networking.istio.io/default created
poddisruptionbudget.policy/ingressgateway created
horizontalpodautoscaler.autoscaling/istio-ingressgateway created
service/istio-ingressgateway created
```
I mentioned the incorrect setting I used in prior comment was from https://preliminary.istio.io/docs/tasks/traffic-management/egress/egress-gateway/#deploy-istio-egress-gateway and Martin said he would fix that page.

**Comment by elfinhe** [comment]
Issues:

1. podDNSSearchNamespaces missing in validation schema;
1. Component EgressGateway is not generated/enabled with `values-istio-multicluster-gateways.yaml `
1.   "istio-multicluster-destinationrule" already exists (repeated 1 times) ?

**Comment by ericvn** [comment]
I'm not sure if 2 is required or not? I know the egress gateway is used as (an optional)? part of the `Replicated Control Plane page` so it could be installed in that section? I don't see the word egress in the other 2 multi cluster install scenarios.

**Comment by elfinhe** [comment]
> I'm not sure if 2 is required or not? I know the egress gateway is used as (an optional)? part of the `Replicated Control Plane` page so it could be installed in that section? I don't see the word egress in the other 2 multi cluster install scenarios.

For documentation, the egress gateway is not directly related to a multi-cluster setup, kinda orthogonal settings for traffic management.

**Comment by ericvn** [comment]
I was able to get through the `Replicated Control Plane` page today with some additions (coreDNS and egress gateway) and needing the --force. The uninstall instructions still use helm and will need to be updated. I will work on a doc PR for that this afternoon.

Then next up is shared multi-network. I was blocked yesterday as I didn't have the `Istio-multi` sa needed to create the kubeconfig to place in the secret. I might be able to use `istio-reader-service-account` but needing some fixes which hopefully are in the latest build.

**Comment by elfinhe** [comment]
I am now creating some PRs to let those cmds running without --force.

**Comment by ericvn** [comment]
@elfinhe The remote cluster on the shared multinetwork has these requiring a `--force`:
```
Proceeding despite the following validation errors:
unknown field "istioRemote" in v1alpha1.GlobalConfig
Proceeding despite the following validation errors:
unknown field "istioRemote" in v1alpha1.GlobalConfig
Proceeding despite the following validation errors:
unknown field "remotePilotCreateSvcEndpoint" in v1alpha1.GlobalConfig
```

I also notice on the master cluster installs fine, no `--force`` using `istioctl manifest apply --context=$CTX_CLUSTER1 \
  -f install/kubernetes/operator/examples/multicluster/values-istio-multicluster-primary.yaml` but converting that to an unsintall requires a `--force`:
```
Proceeding despite the following validation errors:
unknown field "podDNSSearchNamespaces" in v1alpha1.GlobalConfig
Proceeding despite the following validation errors:
unknown field "podDNSSearchNamespaces" in v1alpha1.GlobalConfig
Proceeding despite the following validation errors:
unknown field "podDNSSearchNamespaces" in v1alpha1.GlobalConfig
```
I assume the later will be fixed by your #1 above.

**Comment by ericvn** [comment]
Current status on the shared multi-network:
- The text bash showing pods for cluster 1 needs updating (no completed pods)
- I needed to add --force for cluster 2's `istioctl manifest apply`
- The text bash showing pods for cluster 2 needs updating (no sidecar)
Create the sa in Cluster 2:
```
kubectl create clusterrole istio-reader-istio-system --verb=get,list,watch \                                                               ✔  16:13:05
    --resource=nodes,pods,endpoints,services,replicasets.apps,replicationcontrollers --dry-run -o yaml \
    | kubectl apply -f -

kubectl create serviceaccount istio-reader-service-account -n istio-system  --dry-run -o yaml \
    | kubectl apply -f -

kubectl create clusterrolebinding istio-reader-istio-system --clusterrole=istio-reader-istio-system \
     --serviceaccount=istio-system:istio-reader-service-account  --dry-run -o yaml \
    | kubectl apply -f -
```
- Create the secret in cluster 1 using something like: `istioctl --context $CTX_CLUSTER2 -n istio-system x create-remote-secret --service-account istio-reader-service-account | kubectl -n istio-system --context $CTX_CLUSTER1 apply -f -` but this doesn't create a secret named `n2-k8s-secret` as the scenario uses. 

I messed around at this point to try and get the ingress-gateway pod to become READY but have been unsuccessful.

**Comment by ericvn** [comment]
FYI @ayj

**Comment by elfinhe** [comment]
https://github.com/istio/istio.io/pull/5530
for Shared control plane (single-network)

**Comment by ericvn** [comment]
Tried the shared multi-network install again on beta.4.  I'm still not able to get the inregess-gateway to become ready on cluster #2 using the instructions as doc'd for the secret changing the service account from `istio-multi` to `istio-reader-service-account`

**Comment by ericvn** [comment]
One thing I noted is a change in `values-istio-multicluster-primary.yaml` to add _networks:_
```
    pilot:
      meshNetworks:
        networks:
          network1:
            endpoints:
            - fromRegistry: Kubernetes
            gateways:
            - address: 0.0.0.0
              port: 443
          network2:
            endpoints:
              - fromRegistry: n2-k8s-config
            gateways:
              - address: 0.0.0.0
                port: 443
```

**Comment by ericvn** [comment]
Still failing the pls I think between pilot and ingress.  Looking into that one more. I think `helm` is using mutualTLS and not sure of the `istioctl`, even though the pls values seem to indicate it should be...

**Comment by ayj** [comment]
> Create the secret in cluster 1 using something like: istioctl --context $CTX_CLUSTER2 -n istio-system x create-remote-secret --service-account istio-reader-service-account | kubectl -n istio-system --context $CTX_CLUSTER1 apply -f - but this doesn't create a secret named n2-k8s-secret as the scenario uses.

`create-remote-secret` uses the cluster ID for the name and key. The cluster name (i.e. context) is added as an annotation. The cluster ID is the UID of the kube-system namespace (`kubectl get namespace kube-system -o jsonpath='{.metadata.uid}'`).

**Comment by elfinhe** [comment]
I got the same error when testing shared-control-plane (single network):

In the remote cluster, error:
```
2019-11-11T21:00:09.585257Z	info	Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 0 successful, 0 rejected; lds updates: 0 successful, 0 rejected

```

Also confirmed that the master cluster got the secret and  is able to discover all injected services in the remote cluster.

**Comment by ericvn** [comment]
Thanks to a bunch of detective work by a number of people I think we have a path forward for the shared control plane (multi-network). There are a few PRs coming for:
- Update the values-istio-multicluster-primary.yaml to imbed network1 and 2 inside networks
- Create the meshexpansion-vs-pilot
and doc steps to
- Add autoInjection to cluster 2

**Comment by ericvn** [comment]
https://github.com/istio/istio.io/pull/5639 to cover Shared control plane (multi-network). @elfinhe will work on Shared control plane (single-network).

**Comment by ericvn** [comment]
I think at this point I will close this one since we probably aren't going to take anymore code changes. The `Replicated Control Plane` and `Shared Control Plane (multi-network)` are working with the `istioctl` install. @elfinhe is still working the `Shared Control Plane (multi-network)`, but we can revert back to the `helm` install (I believe that still works).

**Comment by elfinhe** [comment]
`Shared Control Plane (single-network)` with `istioctl` requires some changes in remote.yaml. I am investigating which part is missing. Even if we identifies the issue, more testing is needed.

Agree with @ericvn to revert back to helm in `Shared Control Plane (single-network) ` scenario, which I've tested with the latest 1.4 branch this morning.
