### ISSUE TITLE
internal service error over mTLS - SSL23_GET_SERVER_HELLO:unknown protocol

### ISSUE THREAD

**Issue by rnkhouse** [istio/istio#18788]
**Bug description**
I have mTLS enabled globally. And both of my services are running with sidecar container with mTLS enabled with default policy. When I try to connect to internal service over `https` I am getting below error:

> curl: (35) error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol

**Command I run to connect to the other service**

    kubectl exec $(kubectl get pod -l app=app-1 -o jsonpath={.items..metadata.name}) -c app-1 -- curl https://clamav-rest:8080

**istio authn**

    istioctl authn tls-check app-1-dcf9b48b6-ghvn7 clamav-rest.default.svc.cluster.local
    HOST:PORT                                      STATUS     SERVER     CLIENT     AUTHN POLICY     DESTINATION RULE
    clamav-rest.default.svc.cluster.local:8080     OK         mTLS       mTLS       default/         default/istio-system

**default destinationrule**

    Name:         default
    Namespace:    istio-system
    Labels:       app=security
                  chart=security
                  heritage=Tiller
                  release=istio
    Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                    {"apiVersion":"networking.istio.io/v1alpha3","kind":"DestinationRule","metadata":{"annotations":{},"labels":{"app":"security","chart":"sec...
    API Version:  networking.istio.io/v1alpha3
    Kind:         DestinationRule
    Metadata:
      Creation Timestamp:  2019-10-29T15:05:25Z
      Generation:          1
      Resource Version:    4984
      Self Link:           /apis/networking.istio.io/v1alpha3/namespaces/istio-system/destinationrules/default
      UID:                 8954fc7a-fa5d-11e9-ad9a-f2fbd90cc586
    Spec:
      Host:  *.local
      Traffic Policy:
        Tls:
          Mode:  ISTIO_MUTUAL
    Events:      <none>

**Expected behavior**
It should connect to internal service over `https` just like it works with `http`.

**Steps to reproduce the bug**
Enable mTLS globally and inject sidecar in both services.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.3.4

**How was Istio installed?**
Helm Template

**Environment where bug was observed (cloud vendor, OS, etc)**
AKS

**Few installation options**

    global.mtls.enabled=true
    global.disablePolicyChecks=false
    global.outboundTrafficPolicy.mode=REGISTRY_ONLY

**Comment by howardjohn** [comment]
Maybe related to https://github.com/istio/istio/issues/16458, especially since its on port 8080 which I think pilot has an http service on port 8080 which would conflict

**Comment by rnkhouse** [comment]
@howardjohn I am getting the same error on port 8200.

**Comment by rnkhouse** [comment]
@howardjohn When I run with this command it's working fine and giving me `200` response code.

>kubectl exec $(kubectl get pod -l app=app-1 -o jsonpath={.items..metadata.name}) -c istio-proxy -- curl https://clamav-rest:8080 -o /dev/null -s -w '%{http_code}\n' --key /etc/certs/key.pem --cert /etc/certs/cert-chain.pem --cacert /etc/certs/root-cert.pem -k

That means, mTLS is working fine but it's not working over HTTPS from the other container in the Pod.

**Comment by rnkhouse** [comment]
@howardjohn @incfly Is there any update on this issue? Please let me know if you need anything from me. Thanks!

**Comment by incfly** [comment]
We have a doc https://istio.io/docs/tasks/security/authentication/https-overlay/ which ensures mTLS works with HTTPS, I tried it many times and it works.

I can't tell any differences of your apps vs nginx apps serving https traffic. Would you mind trying that and helping us to narrowing down the differences of your setup with that instructions? 

Have you tried that?

**Comment by howardjohn** [comment]
Please attach config dump from the client and server: https://github.com/istio/istio/wiki/Troubleshooting-Istio

**Comment by incfly** [comment]
Either get config dump of `clamav-rest:8080` and `app-1` sidecar,

or trying out the istio.io instructions for https nginx helps us to proceed, thanks.

**Comment by rnkhouse** [comment]
@incfly Logs from `clamav-rest` sidecar container when I request with https:

    {"upstream_cluster":"inbound|8080||clamav-rest.default.svc.cluster.local","downstream_remote_address":"10.2.0.11:46830","authority":"-","path":"-","protocol":"-","upstream_service_time":"-","upstream_local_address":"127.0.0.1:59470","duration":"509","downstream_local_address":"10.2.0.10:8080","upstream_transport_failure_reason":"-","route_name":"-","response_code":"0","user_agent":"-","response_flags":"-","start_time":"2020-01-02T16:12:54.797Z","method":"-","request_id":"-","upstream_host":"127.0.0.1:8080","x_forwarded_for":"-","requested_server_name":"outbound_.8080_._.clamav-rest.default.svc.cluster.local","bytes_received":"517","istio_policy_status":"-","bytes_sent":"77"}

`app-1` sidecar container logs:

    {"istio_policy_status":"-","bytes_sent":"77","upstream_cluster":"outbound|8080||clamav-rest.default.svc.cluster.local","downstream_remote_address":"10.2.0.11:59902","authority":"-","path":"-","protocol":"-","upstream_service_time":"-","upstream_local_address":"10.2.0.11:47588","duration":"2","downstream_local_address":"10.3.181.93:8080","upstream_transport_failure_reason":"-","route_name":"-","response_code":"0","user_agent":"-","response_flags":"-","start_time":"2020-01-02T16:14:13.882Z","method":"-","request_id":"-","upstream_host":"10.2.0.10:8080","x_forwarded_for":"-","requested_server_name":"clamav-rest","bytes_received":"517"}

**Comment by SecaraR** [comment]
Did anyone manage to get this working?
I'm getting the following error and don't know how it can be resolved: `upstream connect error or disconnect/reset before headers. reset reason: protocol error`

istio proxy is showing this log record:

2023-11-14T11:42:20Z [2023-11-14T11:42:19.989Z] "GET / HTTP/1.1" 502 UPE upstream_reset_before_response_started{protocol_error} - "-" 0 87 1 - "10.55.213.135" "curl/8.0.1" "530228b0-e495-9f56-9f1a-943d332a0f14" "shared-services-aaa.aaa.aaa.aaa.io" "100.65.111.49:3310" outbound|3310||clamav.shared-services.svc.cluster.local 100.65.121.18:49458 10.52.87.83:443 10.55.213.135:57113 shared-services-aaa.aaa.aaa.aaa.io -
