### ISSUE TITLE
How increase connectTimeout over 10s in PassThroughCluster or BlackHole OR increase Connection to Istio proxy

### ISSUE THREAD

**Issue by phuthinh2202** [istio/istio#18786]
**Describe the feature request**
I was load test to my service running on Istio when reach 2000 request/s everything is OK. But when load test over 3000 request/s I see request 502 in kibana dashboard. 
Everybody see this issue and optimize tcp connection created to Istio proxy ingress/sidecar proxy or increase ConnectTimeout 10s in PassThroughCluster or BlackHole.

I was increase tcp_max_connection, http_max_connection in DestinationRule but request 502 still in kibana dashboard.

**Additional context**
EKS: 1.14
Istio 1.3.3

**Comment by howardjohn** [comment]
On Istio 1.4 this is the default

For 1.3 you can configure in the `istio` config map in istio-system: https://github.com/istio/istio/blob/dae1db8c175931436ceb92569a8438260f5927b9/install/kubernetes/helm/istio/templates/configmap.yaml#L103
