### ISSUE TITLE
Cluster unhealthy after failure.  mutatingwebhookconfiguration never retries after failure.

### ISSUE THREAD

**Issue by danpalmer-niceincontact** [istio/istio#18805]
**Bug description**
When deleting all k8s worker nodes any namespace that have istio injection enabled never start up.  There error we receive is:

Internal error occurred: failed calling webhook "sidecar-injector.istio.io": Post https://istio-sidecar-injector.istio-system.svc:443/inject?timeout=30s: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

I believe this is a result of the mutatingwebhookconfiguration failing and never retrying.

**Expected behavior**
If a region fails the cluster needs to be able to heal itself once it comes back up.

**Steps to reproduce the bug**
Deploy istio, enable injection for a particular namespace, delete all k8s worker nodes.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
client version: 1.3.4
control plane version: 1.3.4

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:41:55Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.12-eks-c500e1", GitCommit:"c500e11584c323151d6ab17526d1ed7461e45b0c", GitTreeState:"clean", BuildDate:"2019-10-22T03:11:52Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
quickstart evalutation install

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS EKS w/ AWS CNI

Dump file note:  I deleted all of my deployments to see if I could get the cluster back into a healthy state which the dump file may reflect.  If I need to reproduce it again and retrieve the dump file let me know.
[istio-dump.tar.gz](https://github.com/istio/istio/files/3826147/istio-dump.tar.gz)

**Comment by howardjohn** [comment]
See https://github.com/istio/istio/issues/13840 which has a lot of discussion. I think its a big issue it is never retried, but not sure what we can do from Istio side -- maybe we need to make a change in k8s to retry

**Comment by howardjohn** [comment]
Going to close since this is the same as https://github.com/istio/istio/issues/13840, thanks for  the additional info though
