### ISSUE TITLE
Istio config upgrade process

### ISSUE THREAD

**Issue by xiaolanz** [istio/istio#1880]
Establish feature process for Istio config. The process for adding/removing new features/configs.

The process for configuration API upgrade.

**Comment by xiaolanz** [comment]
Review with k8s: https://docs.google.com/document/d/1XqgYNoV0XCgRokJ-lKMf0RTFLhe_GAtorm2W0V2a0Qw/edit

**Comment by xiaolanz** [comment]
Currently Pilot is accepting both APIs. so far no problem for v1alpha1 to v1alpha2. Also a conversion tool is being worked on https://github.com/istio/istio/issues/3621

**Comment by xiaolanz** [comment]
@yusuoh Actually there is a problem with this approach. K8S doesn't allow to define the same Kind+Group CRD of different versions. Therefore different versions of the same RouteRule.config.istio.io cannot exist. For in-cluster update, we have to remove all the crd instances and crd definitions before we are able to create any CRD of the new version.

**Comment by ijsnellf** [comment]
@xiaolanz: FYI, the CRD names and groups have been changed to mitigate this: https://github.com/istio/api/tree/master/networking/v1alpha3

**Comment by xiaolanz** [comment]
Yes. CRD endpoint change is a solution (1-a in [doc](https://docs.google.com/document/d/1XqgYNoV0XCgRokJ-lKMf0RTFLhe_GAtorm2W0V2a0Qw/edit))
The question is if we can do  1-b at all.

**Comment by yusuoh** [comment]
If we can ensure the backward compatibility of each component with the old APIs, we probably don't need to create identical configs. All we need to do is to convert config to the new version after upgrade is done.

**Comment by yusuoh** [comment]
Also we can set up some test to check whether the system is backward compatible.
1. Install old version of Istio and use the old version tool (istioctl) to generate the config.
2. Upgrade the system (control plane + sidecar) to new version. Check whether the existing config is still parsed correctly and working as expected.
3. Use the new version config tool (istioctl) to regenerate the config in the new version. Check the config is still valid and there is no disruptive changes.

**Comment by xiaolanz** [comment]
Step 2 asks for existing component to handle conversion. I don't think it's a scalable solution long term. It would be nice to have APIs or Galley to handle the conversion.  Solution in APIs is underway for 1.10+. 

Step 3 cannot be done without service interruption. Old configs have to be removed before new configs to be put in place.

**Comment by yusuoh** [comment]
When we make changes to API, existing components already have the logic handling old config. So the only requirement is not to completely discard the old logic but only add the new ones to support new ones. It does not need explicit conversion to achieve backward compatibility. Just like we did now in pilot.

For step 3, you are right, we have to delete the old one first and create the new one. but they are don in a short period and may not cause service disruption if pilot could batch the changes together.

**Comment by xiaolanz** [comment]
What do you mean by batching? 

Let component keeps handling old api solution will work but we need them to keep maintain all APIs within the deprecation window.

**Comment by yusuoh** [comment]
I mean when pilot watches the CRDs and update the cache, two consecutive changes could be picked up together if they are close to each other. So if you delete one CRD and create the same one in a short time interval, it will probably not affect the traffic.

API deprecation needs to be done gradually. For each new version, we should reserve some time for users to switch and allow a smooth upgrade. We have to support multiple versions of APIs during that period.

**Comment by xiaolanz** [comment]
Because there is only a handful of components watching Istio config, probably asking them to be in the deprecation process is not too bad an idea.
