### ISSUE TITLE
ingressgateway is not respecting service annotation

### ISSUE THREAD

**Issue by rnkhouse** [istio/istio#18806]
**Bug description**

I am installing istio ingress gateway using below annotation to use the IP address from the different resource-group but, it's not considering the change.

    --set gateways.istio-ingressgateway.serviceAnnotations.service.beta.kubernetes.io/azure-load-balancer-resource-group=xx.xx.xx.xx

**describe istio-ingressgateway**

    Name:                     istio-ingressgateway
    Namespace:                istio-system
    Labels:                   app=istio-ingressgateway
                              chart=gateways
                              heritage=Tiller
                              istio=ingressgateway
                              release=istio
    Annotations:              kubectl.kubernetes.io/last-applied-configuration:
                                {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"service":"map[beta:map[kubernetes:map[io/azure-load-balancer-resource-grou...
                              service: map[beta:map[kubernetes:map[io/azure-load-balancer-resource-group:mtes-static-pip]]]
    Selector:                 app=istio-ingressgateway,istio=ingressgateway,release=istio
    Type:                     LoadBalancer
    IP:                       10.0.10.113
    IP:                       xx.xx.xx.xx
    Port:                     status-port  15020/TCP
    TargetPort:               15020/TCP
    NodePort:                 status-port  31901/TCP
    Endpoints:                10.0.11.19:15020
    Port:                     http2  80/TCP
    TargetPort:               80/TCP
    NodePort:                 http2  31380/TCP
    Endpoints:                10.0.11.19:80
    Port:                     https  443/TCP
    TargetPort:               443/TCP
    NodePort:                 https  31390/TCP
    Endpoints:                10.0.11.19:443
    Port:                     tcp  31400/TCP
    TargetPort:               31400/TCP
    NodePort:                 tcp  31400/TCP
    Endpoints:                10.0.11.19:31400
    Port:                     https-kiali  15029/TCP
    TargetPort:               15029/TCP
    NodePort:                 https-kiali  31733/TCP
    Endpoints:                10.0.11.19:15029
    Port:                     https-prometheus  15030/TCP
    TargetPort:               15030/TCP
    NodePort:                 https-prometheus  30840/TCP
    Endpoints:                10.0.11.19:15030
    Port:                     https-grafana  15031/TCP
    TargetPort:               15031/TCP
    NodePort:                 https-grafana  32503/TCP
    Endpoints:                10.0.11.19:15031
    Port:                     https-tracing  15032/TCP
    TargetPort:               15032/TCP
    NodePort:                 https-tracing  32422/TCP
    Endpoints:                10.0.11.19:15032
    Port:                     tls  15443/TCP
    TargetPort:               15443/TCP
    NodePort:                 tls  31089/TCP
    Endpoints:                10.0.11.19:15443
    Session Affinity:         None
    External Traffic Policy:  Cluster
    Events:
      Type     Reason                      Age                 From                Message
      ----     ------                      ----                ----                -------
      Normal   EnsuringLoadBalancer        28s (x5 over 104s)  service-controller  Ensuring load balancer
      Warning  CreatingLoadBalancerFailed  28s (x5 over 104s)  service-controller  Error creating load balancer (will retry): failed to ensure load balancer for service istio-system/istio-ingressgateway: user supplied IP Address xx.xx.xx.xx was not found in resource group mc_aks-dev_aks-dev_canadacentral

**Expected behavior**

It should look for the public IP in given resource group which is **mtes-static-pip** as you can see it in describe.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.2.6

**How was Istio installed?**
helm template

**Environment where bug was observed (cloud vendor, OS, etc)**
AKS

**Comment by howardjohn** [comment]
`--set gateways.istio-ingressgateway.serviceAnnotations.service.beta.kubernetes.io/azure-load-balancer-resource-group=xx.xx.xx.xx` is not correct, you need to somehow escape the annotation name. not 100% sure how to do that on helm, it might be something like `--set gateways.istio-ingressgateway.serviceAnnotations."service.beta.kubernetes.io/azure-load-balancer-resource-group"=xx.xx.xx.xx`. Or much easier is just to make a values file and pass with `-f` so you can do it as yaml

**Comment by rnkhouse** [comment]
@howardjohn First I tried with the way you mentioned. But, I was getting the same error.

**Comment by howardjohn** [comment]
See https://stackoverflow.com/questions/49522776/helm-how-to-override-value-with-periods-in-name for how to do it, looks like you need to escape the dots. Or just use a values file, much simpler than dealing with the `--set` pain
