### ISSUE TITLE
Operator CRD istiocontrolplane error message

### ISSUE THREAD

**Issue by kramvan1** [istio/istio#18803]
**Bug description**

See the following in the CRD after creating:
```
   message: '[spec.validation.openAPIV3Schema.properties[metadata]: Forbidden: must
      not specify anything other than name and generateName, but metadata is implicitly
      specified, spec.validation.openAPIV3Schema.type: Required value: must not be
      empty at the root]'
    reason: Violations
    status: "True"
    type: NonStructuralSchema
```

**Expected behavior**
No schema violations in the CRD

**Steps to reproduce the bug**

On kube 1.16 cluster

- get 1.4.0-beta.3 release tar, expaned it and cd into the install/kubernetes/operator dir.
- kubectl apply -k deploy/
- kubectl get crd istiocontrolplanes.install.istio.io  -o yaml

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by jasonwzm** [comment]
@richardwxn It looks like the IstioControlPlane CRD is not structural: https://github.com/istio/operator/blob/master/deploy/crds/istio_v1alpha2_istiocontrolplane_crd.yaml
How are we creating the CRD today?

**Comment by jasonwzm** [comment]
Ideally, the IstioControlPlane API should move to istio/api where it can take advantage of all the Istio tooling available there (including crd generation, deepcopy generation, etc.)

**Comment by richardwxn** [comment]
@jasonwzm The IstioControlPlane proto is defined inside operator now: https://github.com/istio/operator/blob/master/pkg/apis/istio/v1alpha2/istiocontrolplane_types.proto.  We were trying to move to istio/api but due to timeline issue it is sitting inside operator now, see pending PR: https://github.com/istio/api/pull/1101/files

**Comment by richardwxn** [comment]
I created a PR trying to fix it.
