### ISSUE TITLE
How to solve "ISTIO-SECURITY-2019-006: DoS affecting Istio 1.3.x versions" manually

### ISSUE THREAD

**Issue by nerusnayleinad** [istio/istio#18802]
We just upgraded from Istio 1.1.3 to 1.3.4 and hours later received an email notifying about this vulnerability.

From the post, there is a workaround to to override the following options, using helm:

`--set pilot.env.PILOT_INBOUND_PROTOCOL_DETECTION_TIMEOUT=0s --set global.proxy.protocolDetectionTimeout=0s`

I don't use helm, and I upgraded manually, so now I am not sure how can I manually set these options.

`PILOT_INBOUND_PROTOCOL_DETECTION_TIMEOUT` is quite clear. I guess I can edit the deployment, and add this environment variable, and set it to `0`,  but `global` options of the proxy is not that clear. My guess is that I have to add it as a parameter to `args` to get the options upon initialization, for `istio-pilot` deployment. Like this:

```
...
- args:
  - proxy
  - --domain
  - $(POD_NAMESPACE).svc.cluster.local
  - --serviceCluster
  - istio-pilot
  - --templateFile
  - /etc/istio/proxy/envoy_pilot.yaml.tmpl
  - --controlPlaneAuthPolicy
  - MUTUAL_TLS
  - --protocolDetectionTimeout      <- added this line and the one below
  - 0
...

```

If this is not right, please point me out how can I set these parameters manually; without helm.

**Comment by howardjohn** [comment]
I would suggest you grep for all places `global.proxy.protocolDetectionTimeout` shows up. Looks like this is one place: https://github.com/istio/istio/blob/2b971c71aa807f777219c1bf64ed6932770d6f06/install/kubernetes/helm/istio/templates/configmap.yaml#L114 which is the `istio` configmap in istio-system

**Comment by nerusnayleinad** [comment]
thanks. I did that.
