### ISSUE TITLE
TestRateLimiting_RedisQuotaRollingWindowChanges 100% failure rate

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#18817]
https://testgrid.k8s.io/istio_istio_postsubmit#integ-mixer-k8s-tests_istio_postsubmit&width=20

This went from 90% pass rate to 0% pass rate on 11/6

**Comment by howardjohn** [comment]
Regression by https://github.com/istio/istio/pull/18354

@hzxuzhonghu ptal

**Comment by hzxuzhonghu** [comment]
@istio/wg-networking-maintainers-data-plane    I found that if only rds pushed, it will no be reloaded, is that intended?  Does envoy require lds updated simultaneously before rds?
