### ISSUE TITLE
golang/protobuf (1.4) leads to 15% regression in Pilot CPU

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#18826]
In 1.3, we spend 21% of time on gogo marshalling and 12% on gc
In 1.4, we spend 30% of time on golang/protobuf marshalling, and 14% on gc

This adds up to a roughly 15% CPU regression in Pilot as a result of https://github.com/envoyproxy/go-control-plane/ migrating to golang/protobuf.

This is not a surprise, but we should track this and see how we can improve this moving forward.

@kyessenov

**Comment by sdake** [comment]
@ostromart @howardjohn not to hijack this bug, but I believe we should transition the operator to golang/protobuf as performance in the operator is not as crucial as pilot.

Cheers
-steve

**Comment by howardjohn** [comment]
I do't think  we can really do anything about this except acknowledge it happened
