### ISSUE TITLE
Documentation for running Istio outside k8s

### ISSUE THREAD

**Issue by scalp42** [istio/istio#18832]
Hi folks,

I noticed #12126 was closed but I'd love if there was some/any documentation regarding running Istio as a sidecar in Nomad for example.

Probably can't make use of [sidecar_service](https://www.nomadproject.io/docs/job-specification/sidecar_service.html) as it's oriented for Consul Connect I believe but should still be able to leverage [groups](https://www.nomadproject.io/docs/job-specification/group.html) or [canaries](https://www.nomadproject.io/docs/job-specification/service.html#canary_tags) hopefully.

It's mostly a challenge of reverse engineering and keep poking around.

I'm also wondering if Consul ACLs are supported as I only see params for Consul API URL `--consulserverURL`.

Thanks in advance 🙏

**Comment by mk48** [comment]
I really looking for this. I want to run Istio without kubernets.

**Comment by gnz00** [comment]
I’m also in the reverse engineering phase. I’ve got the examples running and the Envoy bootstrap seems straightforward, however, I’m not sure how to deploy the Istio-agent for node and workload attestation for mTLS.

Worth noting that I’m also stuck on 1.4.5 due to a segfault in 1.5.2.

**Comment by shenkonghui** [comment]
> I’m also in the reverse engineering phase. I’ve got the examples running and the Envoy bootstrap seems straightforward, however, I’m not sure how to deploy the Istio-agent for node and workload attestation for mTLS.
> 
> Worth noting that I’m also stuck on 1.4.5 due to a segfault in 1.5.2.

thank you very much . i encounter the question in 1.5.2  about "Invalid path: /etc/certs/root-cert.pem
virtualInbound: Invalid path: /etc/certs/root-cert.pem" . i try to use 1.4.5 then can be success

**Comment by mk48** [comment]
I really need this, but don't know why this is closed without in-activity :(

**Comment by Ankita5892** [comment]
we are still looking any doc for same please share if anyone has any link or steps to setup istio without kubernets
