### ISSUE TITLE
Selective configuration of protocol detection, by listener

### ISSUE THREAD

**Issue by nicktrav** [istio/istio#18837]
**Describe the feature request**

We're recently ran into issues similar to #16581, where the filter timout of 100ms can cause HTTPS connections to timeout when the client is slow to send the first bytes of the Client Hello message (in our case, we have some JVM services that pause for longer than the timeout value).

I'd like to propose adding a means of _selectively disabling protocol detection entirely for certain workloads_. In our case, the traffic that is failing is _always_ expected to be of the same protocol (i.e. TLS), and is being proxied by an ingress Gateway. In our case, there is no derived benefit from having a filter try and determine the protocol, as it will always be proxied as TLS from the previous hop.

Alternatively, a means of configuring the filter timeout _per listener_ could also be useful, given it's hard to arrive at a "one size fits all" value for how long it should take to reasonably determine a protocol on a request.

As another option, perhaps it doesn't even make sense to have protocol sniffing for inbound listeners associated with Gateways, as these are always statically configured with a `protocol` field in the resource.

**Describe alternatives you've considered**

A workaround for us right now is to raise the timeout limit to lower the failure rate. However, this value is used across the mesh, and raising (or lowering) its value is a trade-off.

**Additional context**

See #16581 for more context.

The relevant changes were #15802 and #16835.

**Comment by nicktrav** [comment]
I'm also wondering if there's a bug in the current implementation, given the title of #16835:

> Pilot: set protocol detection timeout for inbound to 1s and outbound 100ms

In the case of a Gateway, the inbound listener gets a timeout of 100ms.

See:

https://github.com/istio/istio/blob/bcdf2483e7911f63a8edd6706f08674f8b5805f3/pilot/pkg/networking/core/v1alpha3/gateway.go#L105

which calls:

https://github.com/istio/istio/blob/bcdf2483e7911f63a8edd6706f08674f8b5805f3/pilot/pkg/networking/core/v1alpha3/listener.go#L1890-L1895

which picks up the mesh value (default of 100ms).

**Comment by howardjohn** [comment]
In 1.3.5 we no longer set timeout at all on the gateway, this was a bug.

The intent is that if you declare your protocols using the service port name, there should be no detection at all. That sounds like what you are looking for? Is there a case where that is not happening?

**Comment by nicktrav** [comment]
Perfect. If it's fixed in 1.3.5 that's good enough for us. We try to specify all our service port names. And in this case it's a Gateway that's causing the issues.

Do you have a link to the patch or the issue?

**Comment by howardjohn** [comment]
That would be 
https://github.com/istio/istio/pull/18526

In the near future we will be adding documentation/maybe some code changes for "how to harden your istio cluster". Part of that will be about protocol detection, and about migrating from having detection to having (and enforcing) all named ports. Not sure if that will be exposed as a metric or tooling or just documentation, but the goal here is to recommend that while some features are great for adoption, they just add more complexity for serious users

**Comment by nicktrav** [comment]
> the goal here is to recommend that while some features are great for adoption, they just add more complexity for serious users

Yeah, unfortunately we got stung here pretty hard with the adoption sugar we didn't really need.

I guess we _could_ just turn this off entirely with `PILOT_ENABLE_PROTOCOL_SNIFFING_FOR_*` flags? I take it the user will get an option somewhere to enable / disable these once the flags go away in future versions?

>  migrating from having detection to having (and enforcing) all named ports.

+1 to this. If the goal is to have users safely migrate to a setup where they have all named ports, that seems like a decent approach.

We can close this one out, as it's fixed in #18526. That said, it would be great to add a regression test for this to save the pain for our future selves.
