### ISSUE TITLE
same prefix mis-forward by VirtualService

### ISSUE THREAD

**Issue by SmartInWhut** [istio/istio#18849]
the log of the log of istio-ingressgateway pod:
`[2019-11-11T06:09:02.823Z] "GET /notebook/name/test-root1/ HTTP/2" 404 -... outbound|80||test-root.name.svc.cluster.local - ...-
`
my http request with uri :/notebook/name/test-root1/ was forward to host test-root.name.svc.cluster.local , while there are two VirtualService's named "test-root" and "test-root1",respectively. Thus lead to a 404 error for test-root1.

VirtualService yaml seems normal.
test-root:
```spec:
  gateways:
  - kubeflow/kubeflow-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /notebook/name/test-root
    rewrite:
      uri: /notebook/name/test-root
    route:
    - destination:
        host: test-root.name.svc.cluster.local
        port:
          number: 80
    timeout: 300s
```
test-root1:
```spec:
  gateways:
  - kubeflow/kubeflow-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /notebook/name/test-root1
    rewrite:
      uri: /notebook/name/test-root1
    route:
    - destination:
        host: test1-root.name.svc.cluster.local
        port:
          number: 80
    timeout: 300s
```
Any ideas about how to fix it? Thanks a lot,XD.

**Comment by SmartInWhut** [comment]
ok, i found it at [istio](https://istio.io/docs/reference/config/networking/v1alpha3/virtual-service/#HTTPMatchRequest)

**Comment by Sovietaced** [comment]
@SmartInWhut Can this be closed?
