### ISSUE TITLE
release ARTIFACTS links always hang for some users

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#1885]
We put those ARTIFACTS links in https://github.com/istio/istio/releases

they look like http://gcsweb.istio.io/gcs/istio-release/releases/<version>/ 

e.g.
http://gcsweb.istio.io/gcs/istio-release/releases/0.2.12/
or
http://gcsweb.istio.io/gcs/istio-release/releases/0.3.0.0/

but they always hang (for me at least)
ERR_CONNECTION_TIMED_OUT

**Comment by mattdelco** [comment]
There doesn't seem to be much value in the links.  There's already links to all 3 debian images, and the only other thing to look at under there is the 3 istioctl's (which are also provided via the tar balls).  IMO we should just change "ARTIFACTS" to be plain text for the already published release and adjust release/create_github_release.sh (at/near line 83) to also use plain text for future releases.

**Comment by hklai** [comment]
What is strange is that http://gcsweb.istio.io/gcs/istio-release/releases/ works for Krishna and Sam, but I am not able to open it from my macbook as well. I am also getting connection problem.

However, I can open it from my phone.

**Comment by mattdelco** [comment]
On my Linux box Chrome hangs on the URL but curl on the same box seems to pull down valid content. The html cites a stylesheet on yahooapis.com but the URL is still valid so that doesn't seem to be a factor. At this point it's unclear if the browser or the browser's use of credentials (or the lack thereof) that makes a difference.

**Comment by hklai** [comment]
Sam and Krishna said they could open it in incognito as well, so I don't expect credential being the issue here.

**Comment by ldemailly** [comment]
looks like it's just me then, very strange, curl works but neither does chrome nor safari

**Comment by hklai** [comment]
No it's not just you. I have the same problem too.

**Comment by silverdev** [comment]
It's odd that this bug seem to be triggered based on who's browser is trying to access it. I tried different networks and lots of retrying but it seams to make no difference. Gcsweb, the webserver running the alternative build UI for https://storage.googleapis.com/ was made by the Kubernetes team. It's supper simple and does not appear to keep user state or even check the browsers user agent (https://github.com/kubernetes/test-infra/blob/master/gcsweb/cmd/gcsweb/gcsweb.go). It's also ironic it has a hidden decency on yahooapis.com  even if it is just to load a style sheet.

**Comment by hklai** [comment]
Using Safari on the same macbook worked for me. So it must be Chrome trying to be smart.

**Comment by hklai** [comment]
kubernetes issue:
https://github.com/kubernetes/test-infra/issues/5934

**Comment by ldemailly** [comment]
do we know that's what makes it hang ?

I tried to clear cookies etc... still and issue for me so I'm quite curious what causes this

**Comment by hklai** [comment]
I think the theory is that the style sheet on yahooapi is somehow not accessible (blacklisted?) by some chrome browsers.

**Comment by ldemailly** [comment]
related to https://github.com/istio/test-infra/issues/675 also

with more people testing/trying the pre-releases it becomes more important/blocking

**Comment by ldemailly** [comment]
Added https://github.com/istio/istio/wiki/Daily-builds

**Comment by ldemailly** [comment]
ping?

**Comment by sebastienvas** [comment]
Fixed by https://github.com/istio/admin-sites/pull/60

**Comment by ldemailly** [comment]
woot ! thx ! (i updated the wiki)

**Comment by hklai** [comment]
I don't think we need the wiki page anymore after
https://github.com/istio/istio/pull/4112.

**Comment by ldemailly** [comment]
well it's useful to find the link - plus we will maybe have additional notes again in the future

**Comment by hklai** [comment]
Let's put all useful release information in one place (at least as much as
possible) =)

the wiki page is so thin that its value is not justified.
