### ISSUE TITLE
Enhance istioctl verify-install output

### ISSUE THREAD

**Issue by jwendell** [istio/istio#18855]
Few suggestions for `istioctl verify-install` output:

- Normal output should print only something like `Install OK` or `Install failed. Errors: <list>`
- Add a verbose flag `-v ?` to print detailed output (like it does currently)
- Continue after finding an error makes sense sometimes. For example, in my env, it's complaining about the lack of `istio-reader-service-account`, but this doesn't prevent the installation to succeed. I mean, the verification could continue and not stop on this error.

**Comment by esnible** [comment]
@irisdingbj Can you think about this issue and propose which of these items should be implemented and which should not be?

**Comment by irisdingbj** [comment]
@esnible sure. assign to myself

**Comment by esnible** [comment]
@irisdingbj If you are no longer working on this please remove yourself.

**Comment by esnible** [comment]
@irisdingbj If you are no longer working on this please remove yourself.
