### ISSUE TITLE
istiocoredns has not been installed even if set `istiocoredns:       enabled: true`

### ISSUE THREAD

**Issue by irisdingbj** [istio/istio#18852]

**Comment by ericvn** [comment]
I used:
```
spec:
  coreDNS:
    enabled: true
```
as in https://github.com/istio/operator/blob/master/data/examples/multicluster/values-istio-multicluster-gateways.yaml

**Comment by sdake** [comment]
@irisdingbj if you are satisfied with @ericvn's answer, please close this isssue and comment.

Cheers
-steve

**Comment by sdake** [comment]
apologies for the accidental close pressed wrong button.

**Comment by ostromart** [comment]
This was an issue a while back but was fixed in https://github.com/istio/operator/pull/530
