### ISSUE TITLE
delete https://github.com/istio/istio/releases/tag/0.3.0.0

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#1886]
That release has (at least) 2 issues

a) there is 1 too many digits in the tag

b) it's not working (contains references to non existant images like docker.io/istio/proxy_debug:0.3.0.0-c5a2b3bc3afe3f5bc4198df726bd0455505212d7

Please delete both the tag and the release entry to avoid confusion and bad UX

In the future please do not label a release as "release", leave it as draft, until it's been at least marginally verified

**Comment by ldemailly** [comment]
reported by users btw https://github.com/istio/issues/issues/130
so please remove this asap (or I can if you want)

**Comment by ldemailly** [comment]
deleted the tag/release for now

**Comment by hklai** [comment]
I just deleted the tag.

**Comment by hklai** [comment]
We will look into adding automated tests to make sure this missing image problem won't happen again later.

**Comment by hklai** [comment]
Created https://github.com/istio/istio/issues/1896
