### ISSUE TITLE
no matches for kind "ClusterIssuer" in version "cert-manager.io/v1alpha2"

### ISSUE THREAD

**Issue by rnkhouse** [istio/istio#18869]
**Bug description**

I am installing cert-manager version 0.11.0 and getting this error.
>error: unable to recognize "test.yaml": no matches for kind "ClusterIssuer" in version "cert-manager.io/v1alpha2"

**cluster_issuer.yaml**

        ---
        apiVersion: cert-manager.io/v1alpha2
        kind: ClusterIssuer
        metadata:
            name: letsencrypt-staging
        spec:
            acme:
                server: https://acme-staging-v02.api.letsencrypt.org/directory
                email: ronak@example.com
                privateKeySecretRef:
                    name: letsencrypt-staging
                solvers:
                - selector: {}
                dns01:
                    azuredns:
                        clientID: xxxx-xxxx-xxxx-xxxx
                        clientSecretSecretRef:
                            name: azuredns-config
                            key: CLIENT_SECRET
                        subscriptionID: xxxx-xxxx-xxxx-xxxx
                        tenantID: xxxx-xxxx-xxxx-xxxx
                        resourceGroupName: mts-dns
                        hostedZoneName: example.com
                        environment: AzurePublicCloud

**Steps to reproduce the bug**
1) helm template install/kubernetes/helm/istio-init --name istio-init --namespace istio-system --set certmanager.enabled=true | kubectl apply -f -
2) helm template install/kubernetes/helm/istio --name istio --namespace istio-system -f ../istio_dev_values.yaml | kubectl apply -f - (**set cert-manager version tag as 0.11.0**)

**istio_dev_values.yaml**

     certmanager:
       enabled: true
       email: "ronak@example.com"
       tag: "v0.11.0"

I checked CRDs for cert manager in `istio-system` namespace and looks like it's configured with old API endpoint. cert-manager changed API endpoint in version 0.11.0 (https://github.com/jetstack/cert-manager/releases)

    Spec:
      Conversion:
        Strategy:  None
      Group:       certmanager.k8s.io
      Names:
        Kind:       ClusterIssuer
        List Kind:  ClusterIssuerList
        Plural:     clusterissuers
        Singular:   clusterissuer
      Scope:        Cluster
      Version:      v1alpha1
      Versions:
        Name:     v1alpha1
        Served:   true
        Storage:  true

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.3.5

**How was Istio installed?**
Helm template

**Environment where bug was observed (cloud vendor, OS, etc)**
AKS

**Comment by davidraleigh** [comment]
When I try and run the ingress + certmgr tutorial: https://istio.io/docs/tasks/traffic-management/ingress/ingress-certmgr/ 
I get the same error:
```bash
no matches for kind "ClusterIssuer" in version "certmanager.k8s.io/v1alpha1"
```
I've actually found that this tutorial for ingress + certmanager has never worked for me once over the past 4 months of playing with istio on occasion. 1.1, 1.2 and 1.3. Not sure what I'm doing wrong, but there are also some inconsistencies with the documentation in that tutorial as compared to others that leads me to believe nobody has tested it in a while.

**Steps to reproduce the bug**
Follow the tutorial step by step in the 3 Istio docs provided

**Version (include the output of istioctl version --remote and kubectl version)**
1.3.4

**How was Istio installed?**
Helm templates from here
https://istio.io/docs/setup/platform-setup/gke/
https://istio.io/docs/setup/install/helm/#option-1-install-with-helm-via-helm-template
https://istio.io/docs/tasks/traffic-management/ingress/ingress-certmgr/


**Environment where bug was observed (cloud vendor, OS, etc)**
GCP

**Comment by rnkhouse** [comment]
@davidraleigh In my case, cert-manager v0.10.x  is working normally. It's just v0.11.0 because they made significant changes in their API so in istio, CRDs must be updated for this new version.

**Comment by davidraleigh** [comment]
@rnkhouse thanks for replying! I see that setting in my `helm template` call `--set certmanager.enabled=true`. But maybe it has to do with the version of certmanager that comes with istio charts is `v0.6.2`:
https://github.com/istio/istio/blob/1.3.4/install/kubernetes/helm/istio/charts/certmanager/values.yaml#L10

Did you just install certmanager directly from the jetstack chart?

**Comment by rnkhouse** [comment]
So, that is default value but it can be overridden from your custom `values.yaml` file or `--set`. I am installing cert-manager through istio. The steps are in my question.

**Comment by howardjohn** [comment]
Please see our new doc on certmanager: https://preliminary.istio.io/docs/ops/integrations/certmanager/. We are recommending users run their own cert-manager deployments (and have stopped bundling cert-manager) to ensure they are getting the latest and greatest of cert-manager and not relying on our package which may fall out of date.
