### ISSUE TITLE
Access logging configuration per namespace/deployment

### ISSUE THREAD

**Issue by iandyh** [istio/istio#18876]
**Describe the feature request**
1. Turn on/off Access logs per namespace or per deployment
2. Configure the logging format per namespace, per deployment.

**Additional context**
Looking at `sidecar` crd, it seems to be an appropriate place where this kind of configurations can go. If it's agreed, I can also work on the feature.

Thanks.

**Comment by howardjohn** [comment]
I think @douglas-reid was looking into this, or at least a similar thing with trace %

**Comment by mmlac** [comment]
I would also like to suggest a way to enable access logs for a specific proxy to debug issues with a service without necessarily enabling all of the mesh (currently the only way?), a full namespace or even a full deployment, when one proxy can provide a good amount of insight without flooding the mesh with meaningless or duplicate logs.

As a side note, I saw somewhere how they got this exact use-case to work (just enable one proxy to log the access logs without changing the full mesh) but I can't find it any more. If anyone has a workaround for this, please share 🙏

**Comment by iandyh** [comment]
@douglas-reid Hi. Can you share the progress of the work now? Thank you.

**Comment by douglas-reid** [comment]
Please see: https://github.com/istio/istio/wiki/EnvoyFilter-Samples#tracing-and-access-logging

There are examples for controlling access logging for individual workloads / namespaces.
