### ISSUE TITLE
TestTempWorkspace/istioConfig test failure

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#18879]
Example: https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18813/pilot-e2e-envoyv2-v1alpha3_istio/3817

This happens on multicluster as well.

Root cause seems to be unable to connect to galley for validation.

This test has not change in years but started failing recently

**Comment by jasonwzm** [comment]
From the test history, it seems it is probably just flaky. https://k8s-testgrid.appspot.com/istio_istio#pilot-e2e-envoyv2-v1alpha3_istio And not all of the failures of the tests are due to the galley validation.

**Comment by howardjohn** [comment]
@jasonwzm you are looking at presubmits, which include people sending completely broken PRs which fail all tests. If you look at postusmibt you will see its the only one that fails often:
https://k8s-testgrid.appspot.com/istio_istio_postsubmit#pilot-multicluster-e2e_istio_postsubmit&width=20&exclude-non-failed-tests=

https://k8s-testgrid.appspot.com/istio_istio_postsubmit#pilot-e2e-envoyv2-v1alpha3_istio_postsubmit&width=20&exclude-non-failed-tests=

The multicluster one runs the same tests by the way, just with two clusters

**Comment by jasonwzm** [comment]
From the postsubmit dashboard, some tests ran in postsubmits also fail due to "broken PRs" (not very clear about what exactly caused the failure from the logs). The `TestTempWorkspace` in postsubmit seems to be just flaky. Taking a look into this...

**Comment by howardjohn** [comment]
@jasonwzm not sure what you mean? Postsubmit is only changes that are merged, in presubmit I can submit a PR that deletes the entire repo if I wanted, which would show as a failure but not have much significance. Or more commonly, one that fails to build

**Comment by jasonwzm** [comment]
For example, this postsubmit test fails due to a non-validation error. https://prow.k8s.io/view/gcs/istio-prow/logs/pilot-multicluster-e2e_istio_postsubmit/654

**Comment by howardjohn** [comment]
Yes, the e2e tests occasionally hit infrastructural flakes where we fail to even set up the test.
