### ISSUE TITLE
Wiki Page Mixer Out of Process Adapter Walkthrough typo

### ISSUE THREAD

**Issue by GiannisSialmas** [istio/istio#18886]
**Bug description**
The `Mixer Out of Process Adapter Walkthrough` guide in the wiki has a typo (probably)
https://github.com/istio/istio/wiki/Mixer-Out-of-Process-Adapter-Walkthrough#step-3-link-adapter-config-with-adapter-code-and-add-business-logic
In the step 3 code for the adapter, in the imports section, the import `istio.io/istio/pkg/log` is not valid, and during the go build it fails with
```
go: finding istio.io/istio/pkg latest
go: finding istio.io/istio/pkg/log latest
mygrpcadapter.go:40:2: no matching versions for query "latest"
```
Maybe this should be `istio.io/pkg/log` for https://godoc.org/istio.io/pkg/log ?

**Expected behavior**
The go build command should build succesfully
**Steps to reproduce the bug**
Follow the wiki istructions
**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by douglas-reid** [comment]
I believe that the entire doc is now sufficiently out of date.

@mandarjog how do you want to proceed with addressing the out-of-date docs on OOP adapters?

**Comment by mengxu2018** [comment]
How did you resolve it?  I will hang on  in my pc.
```
[root@localhost mygrpcadapter]# go build ./...
go: finding istio.io/istio/pkg/log latest
go: finding istio.io/istio/pkg latest

```

**Comment by mengxu2018** [comment]
> I believe that the entire doc is now sufficiently out of date.
> 
> @mandarjog how do you want to proceed with addressing the out-of-date docs on OOP adapters?

But I found there is no comment saying this document is out of date.

**Comment by mandarjog** [comment]
That doc is indeed out of date. We are moving away from Mixer v1 model in general with Mixer deprecation in istio 1.5
The existing adapters will continue to work for 2 release .

Given this I don’t think you should write new OOP adapter.
https://tinyurl.com/mixer-deprecation

**Comment by Gsantomaggio** [comment]
@mandarjog could you please add more info? 
I was writing a RabbitMQ adapter, so should I stop with it? 

> https://tinyurl.com/mixer-deprecation

Can be this document public? 
 
Thank you
