### ISSUE TITLE
installer v2 telemetry: move to its own values namespace.

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#18881]
Move v2 telemetry under a different values namespace.

1. `values.telemetry.v2.*` should be the values namespace for v2 telemetry.
2.  It should reside at https://github.com/istio/installer/tree/master/istio-telemetry/v2-telemetry

This is the first time v2 telemetry is going out with the installer, and it does not belong to the pilot.* values namespace.

This controls
1. one value in meshconfig
2. envoyfilters for stats and metadata exchange.

**Comment by mandarjog** [comment]
if `.Values.pilot.telemetry.*` was only ever use in the new installer, here is what we can do...
set pilot.telemetry:  "key moved to  < new location>".
You can do this if originally .pilot.telemetry was not a "string"
now if I try to set .values.pilot.telemetry,enabled = true helm will complain and I will the key as the error message

**Comment by howardjohn** [comment]
This needs to be done now or never sort of, to maintain backwards compatibility?

**Comment by mandarjog** [comment]
Yes , we don’t want to go out with these values
