### ISSUE TITLE
Readiness probe is not working correctly

### ISSUE THREAD

**Issue by rnkhouse** [istio/istio#18893]
**Bug description**

1) Configuration is not respecting initial delay. In my app initial delay is set to 120s but POD is in Running state before that.

>example-app-6bbdf98bd8-dc57t   1/2     Running   0          34s

2) It sets the application in Running state even if readiness probe fails - `Warning  Unhealthy  15s   kubelet, aks-agentpool-17141372-vmss000000  Readiness probe failed: HTTP probe failed with statuscode: 503`. Also, it should start checking after initial delay.

When I check the website it says: `no healthy upstream`. It routes the traffic even if health check fails.

**Expected behavior**

It should respect and override defined readiness probe configurations.

**Steps to reproduce the bug**
Install istio with this value: `rewriteAppHTTPProbe: true` in `sidecarInjectorWebhook` and mutual TLS is enabled.

    readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 10

**Pod Describe**

    example-app:
      Readiness:    http-get http://:15020/app-health/example-app/readyz delay=120s timeout=10s period=10s #success=1 #failure=3
    istio-proxy:
      ISTIO_META_POD_PORTS:              [
                                             {"containerPort":3000}
                                         ]
      ISTIO_META_CLUSTER_ID:             Kubernetes
      POD_NAMESPACE:                     default (v1:metadata.namespace)
      INSTANCE_IP:                        (v1:status.podIP)
      SERVICE_ACCOUNT:                    (v1:spec.serviceAccountName)
      ISTIO_META_POD_NAME:               example-app-788f77795f-l6ssb (v1:metadata.name)
      ISTIO_META_CONFIG_NAMESPACE:       default (v1:metadata.namespace)
      SDS_ENABLED:                       false
      ISTIO_META_INTERCEPTION_MODE:      REDIRECT
      ISTIO_META_INCLUDE_INBOUND_PORTS:  3000
      ISTIO_METAJSON_LABELS:             {"app":"example-app"}

      ISTIO_META_WORKLOAD_NAME:          example-app
      ISTIO_META_OWNER:                  kubernetes://api/apps/v1/namespaces/default/deployments/example-app
      ISTIO_KUBE_APP_PROBERS:            {"/app-health/example-app/livez":{"path":"/","port":3000},"/app-health/example-app/readyz":{"path":"/","port":3000}}

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
1.3.5

**How was Istio installed?**
Helm template using `values.yaml` file

**Environment where bug was observed (cloud vendor, OS, etc)**
AKS

**Comment by howardjohn** [comment]
I am not sure what the problem is? Here is a pod that is "not ready". No Istio injection at all:
```
NAME                                 READY   STATUS      RESTARTS   AGE
badhealth-6c858d4f85-ltspv           0/1     Running     0          30s
```

Running is independent of "ready"

What you should check is `kubectl get endpoints` and `istioctl pc endpoints` and see if the endpoint shows up

**Comment by rnkhouse** [comment]
Yes. There is an endpoint (`kubectl get endpoints`) and `istioctl pc endpoints` give me an error - Error: accepts 1 arg(s), received 0

Why traffic is going to the pod even if the readiness probe fails?

**Comment by howardjohn** [comment]
If an endpoint exists then it seems like a k8s issue. Does it actually have a ready endpoint or just the object?

Is it like: (not ready)
```
NAME          ENDPOINTS                                          AGE
badhealth                                                        4d16h
```
Or ready:
```
NAME          ENDPOINTS                                          AGE
badhealth     1.2.3.4:80                              4d16h
```
