### ISSUE TITLE
All Istio Control Plane deployments should have request limits for memory and cpu

### ISSUE THREAD

**Issue by kramvan1** [istio/istio#18896]
**Bug description**

Most of the Istio control pods don't have request limits.   This means pod could consume memory and cpu resources without bounds and cause issues.

All Pods should also have a liveness probe to allow for better pod management.

| IMAGE | Readiness Probe | Liveliness Probe | Request Size | Request Limits |
| --- | --- | --- | --- | --- |
| docker.io/istio/pilot:1.4.0-beta.4 | Yes | No | Yes | No |
| docker.io/istio/proxyv2:1.4.0-beta.4 | No | No | Yes | Yes |
| docker.io/istio/mixer:1.4.0-beta.4 | No | Yes | Yes | No |
| docker.io/istio/citadel:1.4.0-beta.4 | No | Yes | Yes | No |
| docker.io/istio/galley:1.4.0-beta.4 | Yes | Yes | Yes | No |
| docker.io/istio/sidecar_injector:1.4.0-beta.4 | Yes | Yes | Yes | No |
| grafana/grafana:6.4.3 | Yes | No | Yes | No |
| quay.io/kiali/kiali:v1.9 | Yes | Yes | Yes | No |
| docker.io/prom/prometheus:v2.12.0 | Yes | Yes | Yes | No |
| docker.io/jaegertracing/all-in-one:1.14 | Yes | Yes | Yes | No |

**Expected behavior**

All Control plane pods have request size and limits, and liveness and readiness probes.

**Steps to reproduce the bug**

Look at the control plane pod deployment yaml.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

1.4.0-beta.4

**How was Istio installed?**

Istio operator

**Environment where bug was observed (cloud vendor, OS, etc)**

IKS with kube 1.1.6

**Comment by kramvan1** [comment]
@linsun opened this to get it on the books.

**Comment by howardjohn** [comment]
@kramvan1 we have discussed this in the past and the reservation is that its hard to set limits that are reasonable for everyone (small vs large scale). On my system Prometheus uses 32gb memory for instance

**Comment by howardjohn** [comment]
Also I don't think a blanket statement like "all deployments should have liveness probes" is accurate. See https://srcco.de/posts/kubernetes-liveness-probes-are-dangerous.html. Especially proxyv2. I REALLY do not want to get in the business of killing a whole cluster's proxies because of some poorly configured liveness probe and causing a cluster wide outage

**Comment by linsun** [comment]
@Stono has graciously offered to give us an example of his proxyv2 liveness probe, and we can check if this is something make sense to generalize for the community.

@kramvan1, Do you notice any component that are not customization for request limit?

**Comment by kramvan1** [comment]
@linsun   I think all the components are covered, we will start the process of trying to figure out what limt values will work for our environments.

I would still think that Pilot should have a liveness probe, curious why it does not?

**Comment by sdake** [comment]
@kramvan1 if you are satisfied with the answers to the issue you have filed, can you close this issue? If not, can you offer further information on your original request?

@costinm any chance you can answer why pilot lacks a liveness probe? Just a gap, or a technical reason?

Cheers
-steve

**Comment by howardjohn** [comment]
I'm happy to add a liveness probe to pilot if someone can come up with one that is useful and has ~0 chance of false positives, but I haven't heard any suggestions along those lines.

Regarding proxy liveness, Stono said they reverted that and no longer have one

**Comment by Stono** [comment]
Correct we have, however we experienced an issue recently where a proxy on one of our pods went haywire, using 100% cpu and effectively causing an outage until it was manually restarted.

As a result we have an action to look at liveness probes for it again.  I'll let you know what we come up with.

**Comment by kramvan1** [comment]
Will use IOP for changes we need here.
