### ISSUE TITLE
Performance benchmark testing has transient network issue

### ISSUE THREAD

**Issue by richardwxn** [istio/istio#18909]
We noticed that for past two days, when running with mixer v1 on and server sidecar only mode, fortio test fails for 1 thread, 1000 qps case.

Error message: 
http_client.go:542> Unable to connect to 10.12.2.4:8080 : dial tcp 10.12.2.4:8080: connect: connection refused. Aborting because error -1

/CC @carolynhu @lambdai

**Comment by richardwxn** [comment]
removed the case running with 1 conn and 1000 qps since it's hard to achieve

**Comment by lambdai** [comment]
What is the avg latency of successful one thread case?
A round trip in data center should be less than 0.5 second. Plus the overhead of sidecar we should have a good chance to achieve  1000 qps if the request/response is small. Is the mixer v1 case connecting to mixer server? If so it's kind of reaching the limit.

Also it's a little weird the failure is connection refuse. Could you paste the full log including the timestamp when pods are ready and when fortio starts?
