### ISSUE TITLE
curl -sL https://git.io/getLatestIstioCtl   does not work yet

### ISSUE THREAD

**Issue by kramvan1** [istio/istio#18905]
**Bug description**

New way to download just istioctl is not working
https://github.com/istio/istio/blob/master/release/downloadIstioCtl.sh#L20

**Expected behavior**

Can use the new curl to get istioctl binary

**Steps to reproduce the bug**

Try new curl cmd

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

1.4.0-beta.4

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by kramvan1** [comment]
cc @linsun

**Comment by linsun** [comment]
@kramvan1 FYI, this is the script - https://raw.githubusercontent.com/istio/istio/release-1.4/release/downloadIstioCtl.sh

I'll try to see if I can get it working

**Comment by linsun** [comment]
@kramvan1 this works pretty well for me

```
$ curl -sL https://raw.githubusercontent.com/istio/istio/release-1.4/release/downloadIstioCtl.sh | sh -
Downloading istioctl-1.4.0-beta.4-osx.tar.gz from https://github.com/istio/istio/releases/download/1.4.0-beta.4/istioctl-1.4.0-beta.4-osx.tar.gz ... 
istioctl-1.4.0-beta.4-osx.tar.gz download complete!

Add the istioctl to your path with:
  export PATH=$PATH:$HOME/.istioctl/bin 

Begin the Istio pre-installation verification check by running:
	 istioctl verify-install 

Need more information? Visit https://istio.io/docs/reference/commands/istioctl/ 
```
