### ISSUE TITLE
turn on/off locality load balancing per destination rule

### ISSUE THREAD

**Issue by yingzhuivy** [istio/istio#18903]
**Describe the feature request**
We'd like to turn on/off locality load balancing per destination rule. 
This change https://github.com/istio/istio/pull/18406 allows overriding locality load balancing settings. But it does not allow overriding turning on/off.

**Describe alternatives you've considered**
no alternative

**Comment by yingzhuivy** [comment]
cc @howardjohn

**Comment by howardjohn** [comment]
@hzxuzhonghu @rshriram should we just add an enabled field? We can't just rely on the presence of `localityLb: {}` because there are three states:

* Enabled
* Disabled
* Unspecified, use mesh config

**Comment by hzxuzhonghu** [comment]
Sounds reasonable requirement, in order not to break compatibility, we can add a disabled field, if it is empty, the behavior is the same as current. If set to true, then we should disable locality lb per DR.

**Comment by howardjohn** [comment]
@hzxuzhonghu I think there is no compatibility issue, this has not been shipped yet in any release?

**Comment by hzxuzhonghu** [comment]
This struct is from mesh configuration. What would you do with enabled field?

this filed may have three values: true, false, not set, imo, false and not set should be same.

**Comment by howardjohn** [comment]
I am talking about the destination rule mesh config

**Comment by ckcd** [comment]
Needs this +1 ...

@howardjohn @hzxuzhonghu  Are we working on it? if not I can do some coding and gives PR in both `istio/api` and here.

**Comment by howardjohn** [comment]
That would be great

**Comment by ckcd** [comment]
Should we use `enable` or `disable` in `LocalityLoadBalancerSetting` per DR ?

considering in early release the behavior of `locality` is controlled by `mesh config` and it's default value is `true`, which means for each DR it's `locality` is `turn on`. So I think we should use `disable` in this feature which means the default `bool disable = 0` is `turn on`.

@howardjohn  PTAL.

**Comment by ckcd** [comment]
Btw, if set `turn off` in global `mesh.config`, but set `turn on` in on DR, should it actually be `on` or `off`?

**Comment by hzxuzhonghu** [comment]
The settings in destination rule can override mesh settings, so it is `on`.

**Comment by yingzhuivy** [comment]
@ckcd wondering if you are still working on the implementation for this since the api change has been merged? I hope to get this in before 1.5 release cut which is Jan.20. If not, I can work on it. let me know~

**Comment by howardjohn** [comment]
oh it never got implemented that explains why it doesn't work.. I thought it was a bug. I have a pr that implements it in https://github.com/istio/istio/pull/20094

**Comment by ckcd** [comment]
@yingzhuivy  I'm not doing this since @howardjohn is already working on it in https://github.com/istio/istio/pull/20094.

**Comment by ckcd** [comment]
> oh it never got implemented that explains why it doesn't work..

yes... since the api change is just merged recently, I haven't done it yet T^T

**Comment by howardjohn** [comment]
This is shipped in 1.5
