### ISSUE TITLE
Can you provide an envoy binary package based on ARM64 architecture? 

### ISSUE THREAD

**Issue by AL-Cui** [istio/istio#18922]
**Describe the feature request**

**Describe alternatives you've considered**

**Additional context**

**Comment by AL-Cui** [comment]
It’s too much trouble to compile with bazel

**Comment by bianpengyuan** [comment]
Are you looking for istio-proxy binary or a pure envoy binary? If it is istio-proxy binary, you could try to use container to build it. Run `BUILD_WITH_CONTAINER=1 make build_envoy` in proxy repo and that does not require any additional deps other than docker. If it is envoy binary, please consider open an issue in `envoyproxy/envoy` instead.

**Comment by AL-Cui** [comment]
> Are you looking for istio-proxy binary or a pure envoy binary? If it is istio-proxy binary, you could try to use container to build it. Run `BUILD_WITH_CONTAINER=1 make build_envoy` in proxy repo and that does not require any additional deps other than docker. If it is envoy binary, please consider open an issue in `envoyproxy/envoy` instead.

I want to  use container to build it. But,Is there an arm version of the docker image?
And，Whether the envoy used by `istio` is `envoyproxy/envoy`

**Comment by bianpengyuan** [comment]
Hmm.. I think the builder image is platform agnostic. istio uses `istio/proxy` (https://github.com/istio/proxy) repo, which uses upstream envoy + some istio specific extensions. So if you want an `istio/proxy` binary, clone istio proxy repo and run `BUILD_WITH_CONTAINER=1 make build_envoy`. If you are looking for a binary from envoyproxy/envoy, please open an issue there.

**Comment by AL-Cui** [comment]
> Hmm.. I think the builder image is platform agnostic. istio uses `istio/proxy` (https://github.com/istio/proxy) repo, which uses upstream envoy + some istio specific extensions. So if you want an `istio/proxy` binary, clone istio proxy repo and run `BUILD_WITH_CONTAINER=1 make build_envoy`. If you are looking for a binary from envoyproxy/envoy, please open an issue there.

yes,i want an istio/proxy binary.but, I want to be based on arm64 architecture。run `BUILD_WITH_CONTAINER=1 make build_envoy` need the `gcr.io/istio-testing/build-tools-proxy` docker image.Is there an arm version of the docker image?

**Comment by bianpengyuan** [comment]
Yeah, the clang/llvm we shipped with the builder image is x86_64, so I guess it won't build an arm64 binary. Maybe you could build your own builder image by updating https://github.com/istio/tools/blob/master/docker/build-tools/Dockerfile, especially the clang part:
https://github.com/istio/tools/blob/master/docker/build-tools/Dockerfile#L437-L521.

**Comment by AL-Cui** [comment]
> Yeah, the clang/llvm we shipped with the builder image is x86_64, so I guess it won't build an arm64 binary. Maybe you could build your own builder image by updating https://github.com/istio/tools/blob/master/docker/build-tools/Dockerfile, especially the clang part:
> https://github.com/istio/tools/blob/master/docker/build-tools/Dockerfile#L437-L521.

oh,thanks.我尝试一下，有问题再问你。不过我觉得最好能提供一个arm64的`istio/proxy` 二进制包

**Comment by AL-Cui** [comment]
> Are you looking for istio-proxy binary or a pure envoy binary? If it is istio-proxy binary, you could try to use container to build it. Run `BUILD_WITH_CONTAINER=1 make build_envoy` in proxy repo and that does not require any additional deps other than docker. If it is envoy binary, please consider open an issue in `envoyproxy/envoy` instead.

when I run  `BUILD_WITH_CONTAINER=1 make build_envoy`,Do I need to install bazel first?

**Comment by sdake** [comment]
@AL-Cui the builder image is located here:

https://github.com/istio/tools/tree/master/docker/build-tools

Whether that builds on arm or not, I am uncertain.  Likely not.  You could always cross-compile with x86-64 - I'd expect this to work as in the above instructions, although I don't have an arm64 platform to test with and they are very expensive to buy (6-8k last I looked).

At this time Istio has no arm64 builders available in CI and the project has not prioritized building a release for this platform.  The next step if you wish an arm64 build to be automated across the project is to submit an RFC to the test and release workgroup and present your RFC in the test and release workgroup.

If you are satisfied with this answer, please close and comment.

Cheers
-steve

**Comment by bianpengyuan** [comment]
Close since arm64 is not prioritized. @AL-Cui Please comment here if you encounter any issue on trying out modifying build-tools image for arm64.

**Comment by stalek71** [comment]
You can use arm64 instance on AWS us-east-1 for instance. This way you can pay for consumed resources only(just stop or destroy arm64 instance after a usage).
I need arm64 istio/envoy for kubernetes cluster on AWS because it can offer signifficant cost  reduction on my workloads. So I don't need it just for experimental usage or to play with... 🙂
