### ISSUE TITLE
miss destination workload telemetry info at client side in cross clusters traffic

### ISSUE THREAD

**Issue by zhongfox** [istio/istio#18924]
**Bug description**

using multi-clusters(single-network) model:
cluster 1: service sleep , pod sleep-in-cluster-1
cluster 2: service helloworld, pod helloworld-in-cluster-2

when service sleep in cluster 1 call service helloworld in cluster 2, everything is ok,  except report info of pod `sleep-in-cluster-1`(client), most destination info is unknown, like:
`destination.name`, `destination.namespace`, `destination.workload.namespace`, `destination.workload.name`

though `destination.service.name`, `destination.service.namespace` are set properly

like this:
```
destination_name=unknown,
destination_workload=unknown,
destination_workload_namespace=unknown,
reporter=source,
destination_service=helloworld.sample.svc.cluster.local,
destination_service_name=helloworld,destination_service_namespace=sample,
request_protocol=http,
source_app=sleep,
source_name=sleep-695c67cb5-lpwjb,
source_workload=sleep,
source_workload_namespace=sample 
count=1,duration=196,request_size=0,request_total_size=221,response_code=200,response_size=60,response_total_size=198
```

set up environment like:
https://istio.io/docs/setup/install/multicluster/shared-vpn/
haven't test multi-network scenario.

[ x] Policies and Telemetry

**Expected behavior**
destination workload info  should not be unknown

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
istio 1.3.4
k8s 1.14

**How was Istio installed?**
helm

**Comment by bianpengyuan** [comment]
I don't have experience on setting this up, but this mostly means that `istio-telemetry` does not have accessibility to the other cluster's API server. You probably want to check logs in `istio-telemetry` pod and look for error logs from `kubeenv` adapter, e.g. https://github.com/istio/istio/blob/7ac8777db26f3224308ea12d9312ca6d5ea7020e/mixer/adapter/kubernetesenv/kubernetesenv.go#L394.

**Comment by douglas-reid** [comment]
What destination namespace did you install the multi-cluster secret into?  If not `istio-system`, then you'll have to set the `cluster_registries_namespace` config value for the kubeenv handler.

**Comment by zhongfox** [comment]
> What destination namespace did you install the multi-cluster secret into? If not `istio-system`, then you'll have to set the `cluster_registries_namespace` config value for the kubeenv handler.

both clusters installed in `istio-system`

**Comment by zhongfox** [comment]
@douglas-reid @bianpengyuan it can be reproduce in istio 1.4.0:

sleep (cluster 1) call helloworld (in cluster 2) :

the metrics in prometheus:
![image](https://user-images.githubusercontent.com/463772/69140256-1e534a00-0afd-11ea-8914-b90c503b5921.png)

server side(reporter="destination") is ok, but the metric form **client**(reporter="source") miss all destination_workload information.

---
Im trying debug the source code, but the stack is too deep
some env info:

cluster2 (remote):
```
istio [tags/1.4.0●] % kci --context sg2 get pod
NAME                                     READY   STATUS    RESTARTS   AGE
istio-citadel-56465d79b9-4drf2           1/1     Running   0          59m
istio-sidecar-injector-9499f5475-5mr5l   1/1     Running   0          59m
istio [tags/1.4.0●] % kci --context sg2 -nsample get pod
NAME                             READY   STATUS    RESTARTS   AGE
helloworld-v2-6cd449dff4-kf5jb   2/2     Running   0          38m
sleep-6857b879fc-zbx4k           2/2     Running   0          35m
```

cluster 1 (master):
```
istio [tags/1.4.0●] % kci get pod
NAME                                     READY   STATUS    RESTARTS   AGE
grafana-846965fdb-rhzlw                  1/1     Running   0          151m
istio-citadel-56465d79b9-bgdjc           1/1     Running   0          151m
istio-egressgateway-856dffb767-npnlv     1/1     Running   0          151m
istio-galley-5f6d8c84f7-lhf84            1/1     Running   0          151m
istio-ingressgateway-598648f4b7-bc24r    1/1     Running   0          151m
istio-pilot-76fb675b5b-srx6g             1/1     Running   0          151m
istio-policy-7ffbbc7966-ddd7s            1/1     Running   4          151m
istio-sidecar-injector-9499f5475-tmg5d   1/1     Running   0          151m
istio-telemetry-7ff4d598d-42rvc          1/1     Running   2          151m
istio-tracing-54b7b5cd96-6ghx5           1/1     Running   0          151m
kiali-5f8d766c97-nr5v7                   1/1     Running   0          151m
prometheus-6bc859cb7-rwf4h               1/1     Running   0          151m
istio [tags/1.4.0●] % kc -nsample get pod
NAME                     READY   STATUS    RESTARTS   AGE
sleep-6857b879fc-7l8vk   2/2     Running   0          34m
istio [tags/1.4.0●] % kubectl exec --context=$CTX_CLUSTER1 -it -n sample -c sleep $(kubectl get pod --context=$CTX_CLUSTER1 -n sample -l app=sleep -o jsonpath='{.items[0].metadata.name}') -- curl helloworld.sample:5000/hello
Hello version: v2, instance: helloworld-v2-6cd449dff4-kf5jb
```

**Comment by zhongfox** [comment]
debug update: 
when `sleep` pod report, there is `destination ip`(helloworld-v2 in remote cluster) in report data, but no `destination.uid`.
so this is probably an issue about envoy (istio/proxy), the outbound envoy(client) miss remote pod uid when report.

please take a look when you can, @douglas-reid @bianpengyuan

**Comment by bianpengyuan** [comment]
cc @carolynhu you might want to take a look at this one as well, as you are starting investigating https://github.com/istio/istio/issues/19158 about mixer in multi-cluster setup.
