### ISSUE TITLE
can not find ''samples/bookinfo/src/build-docker-services.sh''

### ISSUE THREAD

**Issue by CZacker** [istio/istio#18928]
I want to deploy the bookinfo sample by consul platform, but I can't find ```bash samples/bookinfo/src/build-docker-services.sh``` file which mentions in ```bash istio/samples/bookinfo/platform/consul/README.md```, is it impacting this sample?
![image](https://user-images.githubusercontent.com/25023285/68762941-3127d380-0652-11ea-89fe-f4b6163745d2.png)
![image](https://user-images.githubusercontent.com/25023285/68762966-3d139580-0652-11ea-8a7a-30186291a080.png)

**Comment by howardjohn** [comment]
what version of Istio?

**Comment by CZacker** [comment]
the consul platform deployment part

**Comment by GregHanson** [comment]
@CZacker the script has been renamed to:
`istio/samples/bookinfo/src/build-services.sh`

**Comment by GregHanson** [comment]
fixed wording in the README.  Adding disclaimer to section in question since Consul items are not included in Istio.io docs or any of our release tests
