### ISSUE TITLE
Analyzers need to be able to read mesh config

### ISSUE THREAD

**Issue by sushicw** [istio/istio#18931]
e.g. as discussed here: https://github.com/istio/istio/pull/18917#discussion_r345592448

Getting this via kubectl looks like:
```kubectl get configmap -n istio-system istio -o yaml```

This will also require some way of specifying which namespace to look for the configMap resource in. (I think the name of the resource should be invariant as `istio`). The simplest thing would be to have the istio system namespace be a configurable arg to `istioctl` that defaults to `istio-system`. 

Knowing the namespace of the control plane we want to use will also matter for some other kinds of analysis.

**Comment by sushicw** [comment]
Some of this looks to already exist (e.g. local/analyze.go creates an in-memory meshCfg, and there's a meshConfig proto already in the snapshot).

From an analyzer point of view, they probably already have what they need.

The other half of this is making sure that we're reading in the right mesh config to use, for both files-only and cluster-included cases. I don't believe that part currently happens. 

One potential path forward is to update the `local/analyze.go` code to get mesh config from files and/or kube as a sort of prefetch, instead of just using defaults (but of course to still fall back on those).

This will need some care. @ayj I don't know how familiar you are with the new Galley code, but do you have any thoughts about this?

**Comment by ayj** [comment]
What you said sounds right. The file based MeshConfig is already plumbed through to the runtime processor. We can do something similar for local analyzer case. We'll also need create a direct k8s MeshConfig source when `--use-kube=true`
