### ISSUE TITLE
Script mixer_codegen.sh does not work as per Istio mixer custom adapter dev guide

### ISSUE THREAD

**Issue by yangyao-uipath** [istio/istio#18936]
**Bug description**
1. Istio mixer custom adapter guide uses mixer_codegen.sh script which invokes protoc with argument "docs_out=xxxx",  there's no protoc-gen-docs plugin anywhere on the internet. Is it a Google internal plugin? Or is protoc-gen-docs migrated to protoc-gen-doc while the istio mixer custom adapter guide hasn't update accordingly?  

Error message:
"
--docs_out: protoc-gen-docs: Plugin failed with status code 1.
Attempt 1/3 to run protoc failed with exit code 1
protoc-gen-docs: program not found or is not executable
Please specify a program using absolute path or make sure the program is available in your PATH system variable
"

2. protoc.sh invoked by mixer_codegen.sh uses variable REPO_ROOT while it seems to be null at run time. Supposingly,  $REPO_ROOT=$GOPATH/src/istio.io/istio.   

Error message:
"
/common-protos: warning: directory does not exist.
google/protobuf/descriptor.proto: File not found.
mixer/adapter/aifabric/extensions.proto:21:1: Import "google/protobuf/descriptor.proto" was not found or had errors.
mixer/adapter/aifabric/extensions.proto:44:8: "google.protobuf.FileOptions" is not defined.
mixer/adapter/aifabric/extensions.proto: "google.protobuf.FileOptions" is not defined.
mixer/adapter/aifabric/template.proto:3:1: Import "mixer/adapter/aifabric/extensions.proto" was not found or had errors.
Attempt 1/3 to run protoc failed with exit code 1
"

**Expected behavior**
mixer_codegen.sh to run smoothly when following Istio mixer out of process adapter dev guide at https://github.com/istio/istio/wiki/Out-of-process-Attribute-Generating-Adapter-Developer-Walkthrough

**Steps to reproduce the bug**
Follow the guide. 

**Version (include the output of `istioctl version --remote` and `kubectl version`)**
istio release 1.4 (actually 1.3 and 1.2 too)

**How was Istio installed?**
Git clone from github istio repo

**Environment where bug was observed (cloud vendor, OS, etc)**
Local machine. Linux Ubuntu 18.04.

**Comment by douglas-reid** [comment]
Those docs are sufficiently out-of-date, unfortunately. The codegen stuff was all moved over to be docker-ized. We use `BUILD_WITH_CONTAINER=1 make gen` from the root dir to generate any artifacts that are needed.

@geeknoid can explain the codegen migration process.

**Comment by NilsRenaud** [comment]
Will that be possible to create a page explaining how to create the stubs and yaml files without mixer_codegen script ? 

This way we could avoid to use the Istio codebase in order to build our own adapters and use other languages for out-of-process adapters than Go.

**Comment by yangyao-uipath** [comment]
> Those docs are sufficiently out-of-date, unfortunately. The codegen stuff was all moved over to be docker-ized. We use `BUILD_WITH_CONTAINER=1 make gen` from the root dir to generate any artifacts that are needed.
> 
> @geeknoid can explain the codegen migration process.

Hi Douglas, 

Thank you for the clarification.

Hi Martin,
 
Would you please kindly update the document to share more about the correct way for custom mixer out of process adapter development? I managed to get custom adapter yaml generated and then got into troubles connecting custom adapter with mixer as there isn't much detailed info on instance definition.

Looking forward to hear back from you.

**Comment by yangyao-uipath** [comment]
A follow up, after resolving the connection reset error. 
S2I build fails around half the time with error:
"ReadTimeoutError(\"HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)"

One of the suggestion is that set the pip install time out to 100s instead of default 15s.  https://stackoverflow.com/questions/43298872/how-to-solve-readtimeouterror-httpsconnectionpoolhost-pypi-python-org-port 

Is there a way to set the pip install timeout during invoking s2i build command?

**Comment by Gsantomaggio** [comment]
Hi all,
Is there any update on this issue, or another document where is explained how to build an adapter? Thank yoi
