### ISSUE TITLE
Operation control needs to properly support --version

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#18933]
$ docker run -it istio/operator:1.4.0-beta.5 version
whoami: cannot find name for user ID 1001
version.BuildInfo{Version:"unknown", GitRevision:"unknown", GolangVersion:"go1.13.4", BuildStatus:"unknown", GitTag:"unknown"}

This should properly report build information by running `gobuild.sh` instead of `go build` directly.

**Comment by ostromart** [comment]
I think this is fixed in https://github.com/istio/operator/pull/610.
