### ISSUE TITLE
Bogus filenames in DestinationRule cause all sidecars to reject CDS updates

### ISSUE THREAD

**Issue by esnible** [istio/istio#18938]
To reproduce, create a bogus DR:

```
kubectl create svc clusterip deny --tcp=15443

cat <<EOF | kubectl apply -f -
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: deny
spec:
  host: deny
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 15443
      tls:
        mode: MUTUAL
        caCertificates: deny
        clientCertificate: deny
        privateKey: deny
EOF
```

After this, `istioctl proxy-status` will report all sidecars in **all namespaces** have `STALE` CDS.

The sidecars will report
```
[Envoy (Epoch 1)] [2019-11-13 20:37:00.072][31][warning][config] [external/envoy/source/common/config/grpc_mux_subscription_impl.cc:82]
gRPC config for type.googleapis.com/envoy.api.v2.Cluster rejected:
Error adding/updating cluster(s) outbound|15443||deny.default.svc.cluster.local: Invalid path: deny
```

**Comment by howardjohn** [comment]
Not sure what we can do here, pilot doesn't know what files are available on the proxy. Rejecting the config is correct behavior here?

**Comment by esnible** [comment]
My concern is the **STALE**.  If the only thing rejected is clusters with bad cert paths then this is a low-priority problem.  In the past, when I have seen **STALE** from `istioctl proxy-status` it means Envoy is rejecting **all** new configuration.

I created this work item to get an understanding of how serious this issue is.  We don't want config in one namespace blocking updates in other namespaces from reaching Envoy.  If that is happening, we will need a patch on the Envoy site providing the option to tolerate dynamic clusters with bad cert paths.

**Comment by howardjohn** [comment]
It will block all proxies that the DR applies to, which is not necessarily all namespaces but does have a fairly large blast radius

**Comment by ramaraochavali** [comment]
Why should CDS be stale? I have n't looked at on what basis we mark it Stale but Envoy should only reject this specific cluster and update all other clusters. Are you sure Envoys does not have other clusters?

**Comment by esnible** [comment]
@ramaraochavali My test was done using Istio 1.4 beta 4.  I installed bookinfo.  I then did the steps in the description of this issue.  All the bookinfo pods reported being **STALE** when I did `istioctl proxy-status`.

**Comment by howardjohn** [comment]
This bug is fixed and resulted in another bug :slightly_smiling_face: - we will track in https://github.com/istio/istio/issues/23822
