### ISSUE TITLE
Separate control plane pods from data plane output in `istioctl version --short=false`

### ISSUE THREAD

**Issue by kramvan1** [istio/istio#18937]
**Describe the feature request**

`istioctl version --short=false`  data plane output 
```
data plane version: version.ProxyInfo{ID:"istio-egressgateway-647b46cf6b-htr4v.istio-system", IstioVersion:"1.4.0-beta.4"}
data plane version: version.ProxyInfo{ID:"productpage-v1-596598f447-pf9b5.default", IstioVersion:"1.4.0-beta.4"}
data plane version: version.ProxyInfo{ID:"istio-ingressgateway-5579b7b9b4-8xhrw.istio-system", IstioVersion:"1.4.0-beta.4"}
data plane version: version.ProxyInfo{ID:"reviews-v3-68964bc4c8-97bbl.default", IstioVersion:"1.4.0-beta.4"}
data plane version: version.ProxyInfo{ID:"details-v1-78d78fbddf-7r8hp.default", IstioVersion:"1.4.0-beta.4"}
data plane version: version.ProxyInfo{ID:"istio-egressgateway-647b46cf6b-6qbwg.istio-system", IstioVersion:"1.4.0-beta.4"}
data plane version: version.ProxyInfo{ID:"istio-ingressgateway-5579b7b9b4-brkfw.istio-system", IstioVersion:"1.4.0-beta.4"}
data plane version: version.ProxyInfo{ID:"reviews-v2-d7d75fff8-xw49f.default", IstioVersion:"1.4.0-beta.4"}
data plane version: version.ProxyInfo{ID:"ratings-v1-6c9dbf6b45-q6f45.default", IstioVersion:"1.4.0-beta.4"}
data plane version: version.ProxyInfo{ID:"reviews-v1-7bb8ffd9b6-q68r7.default", IstioVersion:"1.4.0-beta.4"}
```

This is a bit messy in that some of the control plane pods ( istio-ingress/ istio-egress) are shown in the list.     Should be simple enough to define the list of control plane pods and remove them or separate them from the customer pods.        This would allow this output (maybe in the json form) to be used for input to automation to get the data plane pods restarted to pick up a new data plane version. 

**Describe alternatives you've considered**

Manually have to edit/filter the output to get the customer data plane pods

**Additional context**

**Comment by kramvan1** [comment]
cc @linsun

**Comment by linsun** [comment]
BTW, a lot of us believe istio ingress gateway and egress gateway are part of data plane.

**Comment by kramvan1** [comment]
@linsun sure, logically so, but we don't want customer trying to manage those pods as that is what the operator is for.    And for when the istio control plane is remote ( not in the same cluster), this would be even more handy to have.

**Comment by howardjohn** [comment]
I was a bit confused by the description until I ran this myself, but to clarify, the issue is that ingress shows up twice, under control plane and data plane

**Comment by esnible** [comment]
Might it also be valuable to sort the output by ID as part of this work?

**Comment by linsun** [comment]
@kramvan1 can you clarify exactly what you are asking for here?  The seperation is pretty clear other than we put the gateway (ingress as the example here) in both mesh and data plane:

```
$ istioctl version --short=false -o json
{
  "clientVersion": {
    "version": "1.4.0",
    "revision": "c4def934e4f8d1feb42725da41ee0078cde8397f-dirty",
    "golang_version": "go1.13.4",
    "status": "Modified",
    "tag": "1.4.0"
  },
  "meshVersion": [
    {
      "Component": "ingressgateway",
      "Info": {
        "version": "1.6-alpha.a2bed16e4d3a5f4cf560f65833472d1e82f3e088",
        "revision": "a2bed16e4d3a5f4cf560f65833472d1e82f3e088",
        "golang_version": "go1.13.8",
        "status": "Clean",
        "tag": "1.6-alpha.a2bed16e4d3a5f4cf560f65833472d1e82f3e088"
      }
    },
    {
      "Component": "pilot",
      "Info": {
        "version": "1.6-alpha.a2bed16e4d3a5f4cf560f65833472d1e82f3e088",
        "revision": "a2bed16e4d3a5f4cf560f65833472d1e82f3e088",
        "golang_version": "go1.13.8",
        "status": "Clean",
        "tag": "1.6-alpha.a2bed16e4d3a5f4cf560f65833472d1e82f3e088"
      }
    }
  ],
  "dataPlaneVersion": [
    {
      "ID": "istio-ingressgateway-c6ccc5655-6l7pk.istio-system",
      "IstioVersion": "1.6-alpha.a2bed16e4d3a5f4cf560f65833472d1e82f3e088"
    }
  ]
}
```

**Comment by kramvan1** [comment]
@linsun yes, this issue was about removing the gateways (control plane pods) from the data plane list.
Right now with 1.5, there are the ingress, egress and prometheus that could show up in the data plane list.
