### ISSUE TITLE
Authz attempts to create policy for inbound cluster

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#18942]
This line is triggered https://github.com/istio/istio/blob/39693f695b93a9800d99896475b3c4fae6bc5401/pilot/pkg/security/authz/builder/builder.go#L65

To give more info I replace with printing serviceInstance, showing this is the virtual inbound:
```
failed to create ServiceMetadata for &{{tcp  %!s(int=15006) %!s(*model.Port=&{ 0 })    %!s(uint32=0)} %!s(*model.Service=&{{    map[] map[]} [] [] {0 0 <nil>}   map[] 0 {{0 0} 0 0 0 0} false})   }: found empty namespace

```

**Comment by yangminzhu** [comment]
I think https://github.com/istio/istio/pull/18926 should fix this.

**Comment by ramaraochavali** [comment]
@howardjohn Closing this as https://github.com/istio/istio/pull/18926 is merged.
