### ISSUE TITLE
Potential bug: missed EDS update for headless services

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#18943]
https://github.com/istio/istio/pull/16845 added some new code for headless services. I think this may have introduced a bug. However, I haven't experienced this, just was looking at the code and noticed this:

https://github.com/istio/istio/blame/master/pilot/pkg/serviceregistry/kube/controller/controller.go#L975-L991

Normally we trigger and EDSUpdate with the endpoints, which updates the data structures and triggers a push.

The new code instead just triggers a ConfigUpdate, but never updates the internal EDS data structures, because we return early

**Comment by hzxuzhonghu** [comment]
We need full push for headless service, because it requires add/delete listeners per service instance.

>but never updates the internal EDS data structures, because we return early

This does not matter, as the Cluster type is `ORIGINAL_DST` rather than `EDS`.

**Comment by howardjohn** [comment]
Why even build the endpoints object in the first place, should we just stop early if it's  headless?

**Comment by hzxuzhonghu** [comment]
Good catch, will fix it.
