### ISSUE TITLE
Default ip6tables rules block outgoing ipv6 traffic when using Istio CNI

### ISSUE THREAD

**Issue by chenwng** [istio/istio#18956]
**Bug description**

In a dual stack k8s env, IPv6 traffic cannot get out from pods with sidecar injected.  After some debugging, it seems following ip6tables rules added by istio-iptables.sh reject incoming ICMPv6 packet, which is used for neighbor advertisement/solicitation(arp).  I suppose this was not by original design, as the script says dropping all inbound traffic. After adding rule  which allows icmpv6 in the container, the traffic can get out.

```
  IPTABLES_RETRY=false
  # Drop all inbound traffic except established connections.
  ip6tables -F INPUT || true
  ip6tables -A INPUT -m state --state ESTABLISHED -j ACCEPT || true
  ip6tables -A INPUT -i lo -d ::1 -j ACCEPT || true
  ip6tables -A INPUT -j REJECT || true
```

```
ip6tables -I INPUT -p icmpv6 -j ACCEPT -n filter
```

**Expected behavior**

IPv6 traffic can get out from pods

**Steps to reproduce the bug**

1. Create a k8s cluster with a dual stack cni (Calico was used in my test).
2. Create a pod with sidecar injected.
3. Try to ping or curl an external IPv6 address.

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

1.3.5

**How was Istio installed?**

Using helm/chart, and enabling Istio CNI.

**Environment where bug was observed (cloud vendor, OS, etc)**

CentOS

**Comment by sbezverk** [comment]
```
ip6tables -I INPUT -p icmpv6 -j ACCEPT -n filter
```
Opening all icmpv6 is not considered secure, but certain icmpv6 types and codes are important for healthy ipv6 network communication. I would suggest to modify rules to include only those types and codes.

**Comment by abhide** [comment]
Agree. we can selectively allow certain ICMPv6. 

http://shouldiblockicmp.com/ seems like a good resource.

**Comment by rlenglet** [comment]
Even though that this not explicitly specified in this PR's description, note that this issue may be specific to Istio CNI (cf. the `IPTABLES_RETRY=false` variable, which exists only in the `istio/cni` variant of the `istio-iptables.sh` script).

**Comment by chenwng** [comment]
Thanks for the response.  I also agree fully open icmpv6 may have security issues.  The ip6tables rule was just for my verification and I didn't expect it to be used directly.
Btw, I am comparing the behaviors of iptables and ip6tables. It looks like iptables doesn't enforce this rejection to all inbound traffic rule by default.  Can any one please explain the difference or I didn't understand it correctly?

@rlenglet Do you mean this issue should only happen when istio-cni is used? I found this issue without istio-cni enabled. Also I think in the code of istio repo, both istio-iptables.sh and go version istio-iptables have this.

https://github.com/istio/istio/blob/9c4f3fa302ac85a70ec5b03049c6a66a5b626f7a/tools/packaging/common/istio-iptables.sh#L619

https://github.com/istio/istio/blob/9c4f3fa302ac85a70ec5b03049c6a66a5b626f7a/tools/istio-iptables/main.go#L510

**Comment by rlenglet** [comment]
I don't know whether this is specific to Istio CNI. I just noted that you used it in your setup, and the setup script is slightly different in Istio CNI.

It wouldn't be surprising if Istio's `iptables` setup for IPv6 was significantly different from that for IPv4. Istio doesn't officially support IPv6, since we have no tests for it. Cf. https://github.com/istio/istio/issues/1756.

**Comment by jcchavezs** [comment]
I wonder what the state of this is. It seems like the issue was closed due to inactivity and not due to readiness.
