### ISSUE TITLE
Reduce envoy memory overhead by removing the unnecessary listeners and clusters from config

### ISSUE THREAD

**Issue by zhaohuabing** [istio/istio#18954]
**Describe the feature request**
The current envoy memory overhead is a bit too much for production, especially in some resource critical environments such as edge computing in 5G scenario. 

My use case:
Listener: 175
Cluster:  325

{
 "allocated": "50992288",
 "heap_size": "137240576",
 "pageheap_unmapped": "1851392",
 "pageheap_free": "49512448",
 "total_thread_cache": "28283216"
}

Currently, the namespace mechanism can be used to reduce the number of clusters and listeners in envoy, but there's still a big room to improve. We can further optimize the memory usage of Envoy by building the necessary listeners and clusters for the used egress services only.  Considering every pod has an envoy inside, the total saved memory would be significant. 

**Describe alternatives you've considered**

**Additional context**

**Comment by howardjohn** [comment]
You can already define which services a sidecar needs config for with Sidecar. It's not clear to me what else this issue is proposing?

**Comment by howardjohn** [comment]
It's not limited to just namespace scoping, you can specify specific services as well

**Comment by zhaohuabing** [comment]
> It's not limited to just namespace scoping, you can specify specific services as well

This feature is already available? that's great! I didn't find the way to specify services at https://istio.io/docs/reference/commands/pilot-agent/, Could you please give me a pointer to how to config it?

**Comment by howardjohn** [comment]
https://istio.io/docs/reference/config/networking/sidecar/ see `egress`

**Comment by zhaohuabing** [comment]
> https://istio.io/docs/reference/config/networking/sidecar/ see `egress`

Is it possible to let the Proxy send an egress service list to Istio along with the xDS request, otherwise we need to create a sidecar config for each of the proxies in the mesh, which is a big burden for operation.

The egress service can be passed to the pilot agent as an environment variable and send to pilot as metadata.

**Comment by howardjohn** [comment]
@zhaohuabing no, it follows the same pattern as every other API like VirtualService, DestinationRule, etc

**Comment by zhaohuabing** [comment]
> @zhaohuabing no, it follows the same pattern as every other API like VirtualService, DestinationRule, etc

I mean, actually, it should be the default behaviour of envoy (we can have a global option for that) rather than a user-specified configuration.  Why should pilot build listeners and clusters the sidecar doesn't need which causes memory and performance overhead?

**Comment by howardjohn** [comment]
How can you tell what listeners and clusters it needs unless they define it in Sidecar?

**Comment by zhaohuabing** [comment]
> How can you tell what listeners and clusters it needs unless they define it in Sidecar?

In our case, the needed services will be defined at development time and be put into the yaml file, then it can be set to an environment variable to the container at deployment.

**Comment by howardjohn** [comment]
You should just create a Sidecar config based on that. I don't see why it needs to be an environment variable

**Comment by zhaohuabing** [comment]
Yes, it could work fine, thanks for the suggestion.
