### ISSUE TITLE
an issue when i config sidecard auto inject 

### ISSUE THREAD

**Issue by bruse-peng** [istio/istio#18957]
**Describe the feature request**

**Describe alternatives you've considered**

**Additional context**

version: istio1.3.5
isseu: when i create a pod under namespace istio-test, it has only one container, the sidecard not inject namespace istio-test

**Comment by bruse-peng** [comment]
[root@k8s-master-240-16 istio]# kubectl get namespace -L istio-injection
NAME             STATUS   AGE    ISTIO-INJECTION
default          Active   328d   
ingress-nginx    Active   9d     
istio-system     Active   147m   disabled
istio-test       Active   145d   enabled
kube-public      Active   328d   
kube-system      Active   328d   
prometheus       Active   17d    
public-service   Active   212d   
[root@k8s-master-240-16 istio]# kubectl get pod -n istio-test
NAME                            READY   STATUS    RESTARTS   AGE
nginx-php-v1-769ff7b459-ndvzp   1/1     Running   0          18s
nginx-php-v2-c459f7cd4-668k8    1/1     Running   0          18s
[root@k8s-master-240-16 istio]#

**Comment by bruse-peng** [comment]
when i manual inject sidecar it arise the problem below:
[root@k8s-master-240-16 istio]# 
[root@k8s-master-240-16 istio]# istioctl kube-inject -f nginx-php.yaml | kubectl apply -f -
Error: failed to convert to proto. unknown field "tracing" in v1alpha1.ProxyConfig
error: no objects passed to apply
[root@k8s-master-240-16 istio]#

**Comment by bruse-peng** [comment]
my kubernets version is :v1.12.4

**Comment by howardjohn** [comment]
can you run `kubectl get mutatingadmissionwebhook` and `kubectl get pods -n istio-system`?

the istioctl error is probably due to using an old version of istioctl

**Comment by bruse-peng** [comment]
can not get the information of mutatingadmissionwebhook  
[root@k8s-master-240-16 istio-1.3.5]# kubectl get mutatingadmissionwebhook              
error: the server doesn't have a resource type "mutatingadmissionwebhook"
[root@k8s-master-240-16 istio-1.3.5]# 


[root@k8s-master-240-16 istio-1.3.5]# kubectl get pod -n istio-system
NAME                                      READY   STATUS             RESTARTS   AGE
grafana-6567b56959-wb6r5                  1/1     Running            0          10m
istio-citadel-8476b48ff5-svnc4            1/1     Running            0          9m58s
istio-egressgateway-5bd8984645-hchwf      1/1     Running            0          10m
istio-galley-64f7454675-blv9j             1/1     Running            0          10m
istio-grafana-post-install-1.3.5-xsz4d    0/1     Completed          0          10m
istio-ingressgateway-759855bfb4-zlbg8     1/1     Running            0          10m
istio-pilot-f84f6c78-zh6mb                2/2     Running            0          10m
istio-policy-6d66b64c75-8w9tq             2/2     Running            8          10m
istio-security-post-install-1.3.5-lr9sf   0/1     Completed          0          10m
istio-sidecar-injector-6dbf496cbb-58kxf   1/1     Running            0          9m57s
istio-telemetry-5cfc95d75c-p7wsk          2/2     Running            8          10m
istio-tracing-756cd59655-976tt            1/1     Running            0          9m56s
kiali-78f4967b95-gsjnh                    0/1     ImagePullBackOff   0          10m
prometheus-5b48f5d49-bk89l                1/1     Running            0          9m59s
[root@k8s-master-240-16 istio-1.3.5]#

**Comment by bruse-peng** [comment]
![2](https://user-images.githubusercontent.com/47881861/68911379-bfee3a80-078f-11ea-80ab-01fb4ed30db2.jpg)


yes now i can inject sidecard manual(is is the version of istioctl) ,but cant not auto inject blow .when i kubectl get mutatingadmissionwebhook,it back error,blow
![图片](https://user-images.githubusercontent.com/47881861/68911484-1ce9f080-0790-11ea-8bbd-5087678bf01e.png)

**Comment by howardjohn** [comment]
see https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#how-do-i-turn-on-an-admission-controller

**Comment by bruse-peng** [comment]
now  my issue is sidecard can be injected manual, but auto inject sidecard failed

**Comment by howardjohn** [comment]
yes it looks like your cluster does not have mutating webhook enabled

**Comment by bruse-peng** [comment]
below is my apiserver configuratuon how can i modify to resolve this issue
![图片](https://user-images.githubusercontent.com/47881861/68911981-bcf44980-0791-11ea-9d98-268eaf7223b0.png)

**Comment by bruse-peng** [comment]
now i inject manual,but wthen i access it back 503

my gateway virtualservice and destinationrule
[root@k8s-master-240-16 istio]# cat nginx-php-vs.yaml
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: nginx-php-gateway
  namespace: istio-test
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: nginx-php-http
      protocol: HTTP
    hosts:
    - '*'
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginx-php-vs
  namespace: istio-test
spec:
  hosts:
  - '*'
  gateways:
  - nginx-php-gateway
  http:
  - match:
    - uri:
        prefix: /php/
    rewrite:
     uri: "/"
    route:
    - destination:
        host: nginx-php.istio-test.svc.cluster.local
        port:
          number: 8089
        subset: v1
      weight: 40
    - destination:
        host: nginx-php.istio-test.svc.cluster.local
        port:
          number: 8089
        subset: v2
      weight: 60

[root@k8s-master-240-16 istio]# cat nginx-php-destirule.yaml 
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: nginx-php-destirule
spec:
  host: nginx-php.istio-test.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2

![图片](https://user-images.githubusercontent.com/47881861/68912926-8ec43900-0794-11ea-91da-69e4924cfaa2.png)

![图片](https://user-images.githubusercontent.com/47881861/68913015-e793d180-0794-11ea-8b40-29a17f2d4fab.png)

**Comment by bruse-peng** [comment]
blow is the log of istio-ingress-gateway
![图片](https://user-images.githubusercontent.com/47881861/68913226-90423100-0795-11ea-87cd-f2a50768bc55.png)
![图片](https://user-images.githubusercontent.com/47881861/68913235-9801d580-0795-11ea-948c-7fcdb02dda01.png)

**Comment by bruse-peng** [comment]
blow is the log of istio-ingress-gateway
![图片](https://user-images.githubusercontent.com/47881861/68913226-90423100-0795-11ea-87cd-f2a50768bc55.png)
![图片](https://user-images.githubusercontent.com/47881861/68913235-9801d580-0795-11ea-948c-7fcdb02dda01.png)

**Comment by bruse-peng** [comment]
when i config nginx-ingress,i can access ,so i am sure my kube-dns and service(nginx-php) are work normal
![图片](https://user-images.githubusercontent.com/47881861/68914840-d6e65a00-079a-11ea-9fe1-b8c0b6ea84d2.png)
![图片](https://user-images.githubusercontent.com/47881861/68914844-dbab0e00-079a-11ea-9bc7-e7eddff5eaca.png)
