### ISSUE TITLE
istio 1.4.0 missing the 'ready' addon in coredns configmap 

### ISSUE THREAD

**Issue by camille-rodriguez** [istio/istio#18971]
**Bug description**
Hello,  I deployed istio 1.4 following https://istio.io/docs/setup/install/multicluster/gateways/ and there is a parameter missing in the files. Upon deploy, a few istio pods were not ready, so I checked the description, and here the issue was:
```Warning  Unhealthy  95s (x22 over 2m17s)  kubelet, node03ob20  Readiness probe failed: Get http://10.1.17.14:15020/healthz/ready: dial tcp 10.1.17.14:15020: connect: connection refused```
From previous deployments, I know that the addon "ready" is necessary in the coredns configmap. It wasn't there!
```
apiVersion: v1
data:
  Corefile: ".:53 {\n      errors\n      health\n       \n      # Removed
    support for the proxy plugin: https://coredns.io/2019/03/03/coredns-1.4.0-release/\n
    \     grpc global 127.0.0.1:8053\n      forward . /etc/resolv.conf {\n        except
    global\n      }\n      \n      prometheus :9153\n      cache 30\n      reload\n
    \   }\n"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"Corefile":".:53 {\n      errors\n      health\n      \n      # Removed support for the proxy plugin: https://coredns.io/2019/03/03/coredns-1.4.0-release/\n      grpc global 127.0.0.1:8053\n      forward . /etc/resolv.conf {\n        except global\n      }\n      \n      prometheus :9153\n      cache 30\n      reload\n    }\n"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app":"istiocoredns","operator.istio.io/component":"CoreDNS","operator.istio.io/managed":"Reconcile","operator.istio.io/version":"1.4.0","release":"istio"},"name":"coredns","namespace":"istio-system"}}
  creationTimestamp: "2019-11-14T22:22:05Z"
  labels:
    app: istiocoredns
    operator.istio.io/component: CoreDNS
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.4.0
    release: istio
  name: coredns
  namespace: istio-system
  resourceVersion: "42218"
  selfLink: /api/v1/namespaces/istio-system/configmaps/coredns
  uid: fc5cf5a5-7bfd-4131-97f5-abc8c9077881
```

So I added the "ready" addon in the annotations: 
 ```
  Corefile: ".:53 {\n      errors\n      health\n     ready\n    \n      # Removed
    support for the proxy plugin: https://coredns.io/2019/03/03/coredns-1.4.0-release/\n
    \     grpc global 127.0.0.1:8053\n      forward . /etc/resolv.conf {\n        except
    global\n      }\n      \n      prometheus :9153\n      cache 30\n      reload\n
    \   }\n"
```
and once that was done, all the pods went into the ready state. This should be updated in the manifest.

**Comment by howardjohn** [comment]
Just to clarify, was this working in previous releases of Istio?

**Comment by camille-rodriguez** [comment]
Hi @howardjohn ! Well, I deployed with 1.3.3 two weeks ago, and the instructions were using helm templates instead of istioctl manifest. Since the current version documentation changed on the website I deployed it that way this time. So yes, it was working, but with a different tool.

**Comment by camille-rodriguez** [comment]
Actually, I did mention something similar in this issue about the coredns template https://github.com/coredns/coredns/issues/3412 , but the issue was closed since there was a workaround (which I found odd, because the documentation wasn't updated).  So there's two errors:
1) in the manifest files used for this command: `istioctl manifest apply \
    -f install/kubernetes/operator/examples/multicluster/values-istio-multicluster-gateways.yaml`
2) in the coredns template in the 'Setup DNS section'

**Comment by johscheuer** [comment]
I thought this one would be closed with https://github.com/istio/istio/issues/17290 but I will take a look today and provide a  fix if required.

Thanks for reporting.

**Comment by johscheuer** [comment]
@camille-rodriguez could you explain the issue with the `istioctl manifest apply` command ?

**Comment by sdake** [comment]
I needed this to get things moving:
```
Stevens-MacBook-Pro-2:multicloud-sdake sdake$ cat coredns.sh
kubectl apply -f - <<EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        ready
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           upstream
           fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
    global:53 {
        errors
        ready localhost:9196
        health localhost:9197
        health
        cache 30
        forward . $(kubectl get svc -n istio-system istiocoredns -o jsonpath={.spec.clusterIP}):53
    }
EOF
```

**Comment by camille-rodriguez** [comment]
> @camille-rodriguez could you explain the issue with the `istioctl manifest apply` command ?

What I meant is that when you use the istioctl command to deploy istio, coredns does not have the addon "ready" . So the manifest files should be updated with that (install/kubernetes/operator/examples/multicluster/values-istio-multicluster-gateways.yaml)

**Comment by johscheuer** [comment]
@sdake like mentioned in my PR the ready and health block in `global ` can be dropped since we don't have a readinessProbe/livenessProbe configured and the actual main issue is/was that the newer versions of CoreDNS have the ready Plugin (1.5.0+) and tools like `kubeadm` create a CoreDNS Deployment with a readinessProbe and in my initial docs PR I didn't explicitly added the `ready` plugin if you just took the snippet you dropped the ready endpoint and the readinessProbe was never successful.

**Comment by johscheuer** [comment]
@camille-rodriguez ah, yeah that's actually not that critical but I can add it.
