### ISSUE TITLE
istioctl analyze for local files documentation not clear

### ISSUE THREAD

**Issue by richardwxn** [istio/istio#18978]
I am following the docs: https://istio.io/docs/ops/diagnostic-tools/istioctl-analyze/ to try out istioctl analyze. The local files analyze part is not clear enough to me as I don't know what kind of yaml file I can analyze and what might be the possible or expected output.  

Although from the q&a section at the bottom, there is a link to the code of different analyzers, but it is still not so clear for a user. Would it be better to keep it as a doc instead of a link to the code directory.

**Comment by esnible** [comment]
@sushicw Can you suggest someone to handle this?

**Comment by sushicw** [comment]
Thanks for the feedback!

Do you think we need to explain better that we're talking about yaml files for K8s resources (including Istio custom resources)?

The output should be in the same format, although what you end up seeing will depend on the set of files you analyze. 

Pinging @davidebbo in case he has any thoughts as well.

**Comment by davidebbo** [comment]
I think it wouldn't hurt to be explicit and change:
> Analyze a specific set of local files

to 
> Analyze a specific set of local Kubernetes resource yaml files

@richardwxn would this have helped?

Another thing that I think could be useful is to capture a whole set of test yaml files and make them downloadable. This way a new user could directly download that, unzip it and run the tool on it. It would make for a nice learning experience. It could be part of some kind of walkthrough.

**Comment by richardwxn** [comment]
@davidebbo That description would definitely be more clear. Yep I think the idea of providing some sample files as learning guide together with list of analyzers for user to walk through would be really helpful.
