### ISSUE TITLE
IstioControlPlane doesn't react to changing hub

### ISSUE THREAD

**Issue by dcberg** [istio/istio#18980]
**Bug description**

I installed Istio using the new 1.4.0 Istio operator. I used the example demo profile for the IstioControlPlane.

apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
metadata:
  namespace: istio-operator
  name: example-istiocontrolplane
spec:
  profile: demo

The issue is that 1.4.0-alpha ... version was installed for the control plane and not 1.4.0. I updated the IstioControlPlane to the following.

apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
metadata:
  namespace: istio-operator
  name: example-istiocontrolplane
spec:
  profile: demo
  hub: docker.io/istio
  tag: 1.4.0

The tag was properly applied but the hub was not. Here is an example of one of the component images after applying the updates.

**image: gcr.io/istio-testing/citadel:1.4.0**

**Expected behavior**

I expected that the adjusted **hub** value in the IstioControlPlane would have been applied.

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

client version: 1.4.0
control plane version: 1.4.0

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:42:50Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5+IKS", GitCommit:"46ea161061498e0ebd9b11d66b3b7dba16fa594d", GitTreeState:"clean", BuildDate:"2019-10-17T13:24:04Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**

Using the 1.4.0 experimental operator.

**Environment where bug was observed (cloud vendor, OS, etc)**

IBM Cloud Kubernetes Service  v1.15.5

**Comment by linsun** [comment]
could be related to https://github.com/istio/istio/issues/18554

**Comment by linsun** [comment]
@irisdingbj this is one example of the update of ICP doesn't work issue I mentioned to you, could  you take a look?

**Comment by irisdingbj** [comment]
> @irisdingbj this is one example of the update of ICP doesn't work issue I mentioned to you, could you take a look?

just noticed this thread. will start to work on it

**Comment by irisdingbj** [comment]
Tried using latest master operator code and changing for HUB and TAG works.
