### ISSUE TITLE
improvement to istioctl describe and authn tls-check

### ISSUE THREAD

**Issue by linsun** [istio/istio#18988]
**Bug description**

For 1.4, when I describe my product page pod, I'm getting:

```Pod is PERMISSIVE, client protocol unspecified```

--- it used to be a msg like this in 1.3, which I think it is more useful.

```Pilot reports that pod is PERMISSIVE (enforces HTTP/mTLS) and clients speak HTTP```

For auto mTLS (kudos to the team that delivered this!), it is working nicely with describe:

```
$ istioctl x describe pod details-v1-78d78fbddf-zcfsb
Pod: details-v1-78d78fbddf-zcfsb
   Pod Ports: 9080 (details), 15090 (istio-proxy)
--------------------
Service: details
   Port: http 9080/HTTP targets pod port 9080
Pod is PERMISSIVE, clients configured automatically
```
I could prefer to have clients configured HTTP automatically here so have the protocol info as in 1.3.

For authn tls-check cmd, what does `-` mean below?  BTW, loved the status=auto here.  Does it mean it doesn't know what client is configured?   and there isn't any destination rule?  We need a better indication for this..
```
$ istioctl authn tls-check productpage-v1-596598f447-6l48d reviews.default.svc.cluster.local
HOST:PORT                                  STATUS     SERVER         CLIENT     AUTHN POLICY     DESTINATION RULE
reviews.default.svc.cluster.local:9080     AUTO       PERMISSIVE     -          /default         -
```

1.4

**Expected behavior**
Message more intuitive 

**Steps to reproduce the bug**
Install 1.4 and follow auto mtls install isntruction: https://istio.io/docs/tasks/security/authentication/auto-mtls/#before-you-begin

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.4 (both control plane and data plane)
**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**
IKS

**Comment by linsun** [comment]
cc @esnible @GregHanson @dcberg @incfly @diemtvu @rshriram

**Comment by linsun** [comment]
Also, when I have mesh policy enabled to be mTLS globally, should the CLIENT below be STRICT also?

```
$ istioctl authn tls-check productpage-v1-596598f447-6l48d reviews.default.svc.cluster.local
HOST:PORT                                  STATUS     SERVER     CLIENT     AUTHN POLICY     DESTINATION RULE
reviews.default.svc.cluster.local:9080     AUTO       STRICT     -          /default         -
```

**Comment by incfly** [comment]
> Also, when I have mesh policy enabled to be mTLS globally, should the CLIENT below be STRICT also?

We don't have client side lock down. It's always using label matching to send mTLS only to sidecar injected endpoints. Even if you change mesh policy to `STRICT`.

Per offline discussion, `-` should be changed to N/A.

**Comment by esnible** [comment]
https://github.com/istio/istio/issues/20898 may be a duplicate of this item.
