### ISSUE TITLE
About the span: cs, cr, ss, sr

### ISSUE THREAD

**Issue by flyer1212** [istio/istio#18984]
hi,  when i use istio version 1.3.2 . i collect the span throw /api/v1/spans/ , but i  find it mostly are cs and cr,  fewer ss and sr,   but  in v1.0.0 ，  cs, cr ,ss, sr usually pair to appear,  why
? thanks for your answer.

**Comment by rverma-nsl** [comment]
@flyer1212 did you find any info on this?

**Comment by Harmelodic** [comment]
FYI for anyone visiting here, it's to do with [Zipkin instrumentation](https://zipkin.io/pages/instrumenting.html):

> cs - Client Send. The client has made the request. This sets the beginning of the span.
>
> sr - Server Receive: The server has received the request and will start processing it. The difference between this and cs will be combination of network latency and clock jitter.
>
> ss - Server Send: The server has completed processing and has sent the request back to the client. The difference between this and sr will be the amount of time it took the server to process the request.
>
> cr - Client Receive: The client has received the response from the server. This sets the end of the span. The RPC is considered complete when this annotation is recorded.
