### ISSUE TITLE
istioctl dashboard to allow pod label --selector instead of requiring explicit pod name

### ISSUE THREAD

**Issue by esnible** [istio/istio#18987]
I'd like to be able to say `istioctl -n istio-system dashboard envoy --selector app=istio-ingressgateway` as an alterate to `istioctl -n istio-system dashboard envoy istio-ingressgateway-66c76dfc5f-7k7tf`

If more than one pod fits, istioctl would use an arbitrary pod match.

**Comment by howardjohn** [comment]
this would almost be perfect to use the Service (you can `kubecctl port-forward` to a service) except it won't work for envoy since 15000 isn't in the svc

**Comment by ckcd** [comment]
> this would almost be perfect to use the Service (you can kubecctl port-forward to a service) except it won't work for envoy since 15000 isn't in the svc

Honestly, in `istioctl dashboard` there are just `istioctl dashboard controlz` and `istioctl dashboard envoy` that needs a `pod name` input, and the port for both of is NOT in the svc (15000 & 9876).

**Comment by esnible** [comment]
Thanks @ckcd for the PR!
