### ISSUE TITLE
Confusing warning from "istioctl manifest apply"

### ISSUE THREAD

**Issue by esnible** [istio/istio#18985]
Using 1.4.0, I did `bin/istioctl manifest apply --set profile=demo --set values.global.mtls.enabled=true --set values.global.controlPlaneSecurityEnabled=false`

Received the usual output, but also

```
...
Component Base installed successfully:
======================================
Error detail:

Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply (repeated 1 times)

...

*** Errors were logged during apply operation. Please check component installation logs above. ***
```

I re-ran the command again and did not receive the message.  When I re-ran, some things were `configured`, some things were `unchanged`.

I have no clue what the message meant.

The cluster had previously been on a 1.4.0 beta release, perhaps beta 4.

**Comment by ncouse** [comment]
I observed the same when following the instructions to enabling mixerless telemetry: https://istio.io/docs/ops/configuration/telemetry/in-proxy-service-telemetry/#enable-service-level-metrics-generation-in-envoy

I got the same behaviour on 2 different Kubernetes clusters after freshly installing Istio 1.4.0. Any previous installations were purged before installation.

**Comment by esnible** [comment]
I added `kind/docs` but this is not a docs problem.  We need docs to look at the output because what is currently being produced is confusing.

**Comment by ericvn** [comment]
I think this was fixed with https://github.com/istio/operator/pull/623.

**Comment by howardjohn** [comment]
https://github.com/istio/operator/pull/623/files fixed
