### ISSUE TITLE
Bug with image docker.io/istio/examples-bookinfo-reviews-v2:1.15.0 

### ISSUE THREAD

**Issue by camille-rodriguez** [istio/istio#18993]
**Bug description**
Hello,  I deployed the bookinfo example and the reviews-v2 would not display on the webpage. Instead, and error message saying "the ratings are unavailable" would display. 
I changed the image from docker.io/istio/examples-bookinfo-reviews-v2:1.15.0 to docker.io/istio/examples-bookinfo-reviews-v2:1.10.0 and the webpage was now displayed correctly.  There's a bug in that image! I downloaded the version 1.4.0 of istio. Thanks!

**Comment by sdake** [comment]
@frankbu i'm not sure who the owner for bookinfo  is. Thought you may know.

**Comment by frankbu** [comment]
@camille-rodriguez Can you be more specific about what environment you are using and exactly what to do to reproduce the issue. Nobody else has reported a problem with the latest Bookinfo images.

**Comment by manikantabandaru** [comment]
Even i am facing same issue when followed https://istio.io/docs/tasks/traffic-management/request-routing/#route-based-on-user-identity   section review based on user.

After login the page show jason user but after refresh the page is not showing reviews from v2

**Comment by frankbu** [comment]
@manikantabandaru What are you seeing when you refresh the page? Are you seeing the same error message as @camille-rodriguez: "the ratings are unavailable"? If not, I think your problem is different (maybe the VirtualService or DestinationRule isn't configured properly). Please try again, and provide more details about your configuration and what exactly you are seeing.

**Comment by manikantabandaru** [comment]
Hi ,

I get error like "Error fetching product details!" and " Error fetching product reviews!"

1. I have created latest gke cluster with istio enabled in gke creation time.
2.  Downloaded  used 1.2.8 istio code for bookinfo app
3. I followed below cmds as per documentation 
`  
kubectl label namespace default istio-injection=enabled

kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml

kubectl exec -it $(kubectl get pod -l app=ratings -o jsonpath='{.items[0].metadata.name}') -c ratings -- curl productpage:9080/productpage | grep -o "<title>.*</title>"

kubectl apply -f samples/bookinfo/networking/bookinfo-gateway.yaml

kubectl get svc istio-ingressgateway -n istio-system

export INGRESS_HOST=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
export INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="http2")].port}')
export SECURE_INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="https")].port}')
export GATEWAY_URL=$INGRESS_HOST:$INGRESS_PORT

Request routing:


* Route to 1 version which don't have review ratings

kubectl apply -f samples/bookinfo/networking/virtual-service-all-v1.yaml

kubectl get virtualservices -o yaml


kubectl get destinationrules -o yaml

* Route based on user here username with jason routed with review rating 5

kubectl apply -f samples/bookinfo/networking/virtual-service-reviews-test-v2.yaml`

4. I logged in as jason user and refreshed but i see no change in the page

**Comment by frankbu** [comment]
@manikantabandaru it's still not clear to me exactly where in the flow that you're describing, the actual errors are occurring. My best guess is that you have some kind of version incompatibility in your setup. You mentioned Istio version 1.2.8. That's pretty old and no longer supported https://istio.io/news/support/announcing-1.2-eol-final/. Maybe you're running a version of bookinfo that is not compatible with the istio version? I'd suggest a clean install of a more resent Istio (1.4.3 is the latest) and make sure to use the matching version of the samples.

**Comment by manikantabandaru** [comment]
Hi,

By installing latest 1.4.3 and applying all rules worked for me. Thanks for your time
