### ISSUE TITLE
Cleanup the istio install directories

### ISSUE THREAD

**Issue by frankbu** [istio/istio#190]
The istio install directory has become a confusing mess (istio-15.yaml, istio-16.yaml, istio-auth-15.yaml, istio-auth-16.yaml, istio-rbac.yaml). There's also a README.md in the install directory that is obsolete. Users will have no idea what to use where. The documented install task doesn't even work on IBM clusters anymore (needs rbac).

We need to cleanup and explain in the README.md what it all is for. Then we need to update the istio install instructions (https://istio.io/docs/tasks/installing-istio.html) to give a simple set of setup instructions that work.

**Comment by kyessenov** [comment]
Is IBM cluster using rbac or not?

**Comment by frankbu** [comment]
yes it is
