### ISSUE TITLE
Add support for HTTPS with SNI in egress rules

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio#1901]

**Comment by rshriram** [comment]
no longer valid. solved in gateway

**Comment by eadred** [comment]
Is there an example of doing this in the documentation?

**Comment by rshriram** [comment]
The external service documentation is all you need. SNI will be set automatically

**Comment by vadimeisenbergibm** [comment]
@rshriram the intention of this issue was to add support for HTTPS traffic originated at the client. Suppose you define a rule (egress rule, external service, mixer policy) that allows access to `*.bluemix.net` only. An application pod starts an HTTPS connection to `myservice.blumix.net`, Istio inspects the SNI, verifies that it matches `*.bluemix.net` and allows the traffic to pass. Then if an application pod starts an HTTPS connection to `myvirusupdate.hacker.org`, Istio does not allow the traffic according the rule, by inspecting the SNI that does not match `*.bluemix.net`. Does it make sense?
