### ISSUE TITLE
istioctl can’t set email for cert-manager

### ISSUE THREAD

**Issue by maxekman** [istio/istio#19012]
**Bug description**

Using istioctl to set the email value (for the cluster issuer) of the included cert manager is not possible when installing Istio.

**Expected behavior**
It should be possible to set the email field of the cert manager values. The email value does exist in the templates for cert manager but seems to be missing in the operator protobuf definitions for values.

**Steps to reproduce the bug**
Use `istioctl manifest apply —certmanager.enabled=true —set values.certmanager.email=a@a.com`.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

Sorry, not on computer right now.
Istio: 1.4.0
Kubernetes: 1.14 (on GCP)

**How was Istio installed?**
Using istioctl, at least tried to install. 🙂 

**Environment where bug was observed (cloud vendor, OS, etc)**
GCP Kubernetes Engine.

**Comment by sdake** [comment]
@maxekman we have been strongly considering deprecating certmanager installation in Istio (and replacing this workload with stronger integration with certmanager).

@ostromart @howardjohn I think we should finally finish deprecation of certmanager given that the upstream certmanager installation is rockin solid and there (as I understand it) is not alot of value for us to maintain a parallel installation method.  @costinm I know you have the most domain knowledge of this area. Could you weigh in as well? 

As far as Istio integration goes with certmanager, we should proceed full steam ahead!

 @munnerz can you offer any thoughts on this approach?

**Comment by sdake** [comment]
@maxekman additoinally for 1.4, it is feasible to turn off istioctl validation (which I believe is what is failing here) to pass through values.yaml configuration.  @ostromart has more details, and the details should end up in our 1.4 docs IMO.  This is probably at this point a documentation bug.

**Comment by howardjohn** [comment]
Another option is to make an IstioControlPlane object and pass that in with -f, I suspect that will work.

Regarding deprecation - we already did it in a light weight manner. All of the docs mention upstream installation methods rather than built in support, so I suspect people using it are those that have experience using it in the past istio releases

**Comment by sdake** [comment]
@howardjohn it would be very interesting to me, and possibly @istio/wg-security-maintainers what type of improved integration Istio can provide with certmanager.  Is what we have good enough?  Or should we do more?  @costinm may have the most domain expertise here as he introduced certmanager IIRC.

Cheers
-steve

**Comment by howardjohn** [comment]
In the latest certmanager release they added some form of Istio integration, but I didn't look to closely. I would suggest talking to Costin, he mentioned something about direct sds implementation in certmanager

**Comment by maxekman** [comment]
Thanks for the guidance! As a matter of fact I am passing a IstioControlPlane yaml, which is not working. Sorry for that miss in my report above. I will try without the validation, and also consider a separate cert manager install instead.

**Comment by sdake** [comment]
I contacted @munnerz (a maintainer Jetstack) this morning via slack. He was busy at the time, but hopefully, the env WG leads can meet up with him at KubeCon and come up with our new plans around cert-manager + istio.

Cheers
-steve

**Comment by richardwxn** [comment]
@maxekman For a workaround, try run your command like this: istioctl manifest apply --force --set security.components.certManager.enabled=true --set values.certmanager.email=a@a.com.

Your certmanagement enablement path is not correct and you may also need to provide the force flag to bypass validation error.

**Comment by maxekman** [comment]
Thanks @richardwxn, it also worked with the -f flag I use.

**Comment by sdake** [comment]
@maxekman if you are satisfied with the workaround, please leave a comment and close the bug.  If you are not satisfied, if you could provide more information on what you would suggest to @richardwxn - the information would be of value.

Cheers
-steve

**Comment by maxekman** [comment]
Thanks for the reminder. I ended up creating an additional cluster issuer which instead used the DNS solver.
