### ISSUE TITLE
Remove need for explicit ISTIO_VERSION in download scripts

### ISSUE THREAD

**Issue by sdake** [istio/istio#19017]
TLDR remove ISTIO_VERSION requirement from download scripts which are automatically redirected from istio.io tot he correct branch and script.

https://github.com/istio/istio/pull/17187#issuecomment-554642053

**Comment by sdake** [comment]
@ericvn as you were the assignee on the last issue related to this - any interest in tackling this?

**Comment by howardjohn** [comment]
Doesn't the script already download the latest one if you don't set that? I haven't tried but I thought it might

**Comment by ericvn** [comment]
I just need to verify. We missed a cherry pick from `master` to `1.4` which should fix the release requirement. It was needed before the cherry pick so it was added to the docs as a workaround.

**Comment by ericvn** [comment]
The https://istio.io/downloadIstio now downloads the latest 1.4.0 by default (no specified version), but we need to apply the same change we did for that to https://istio.io/downloadIstioctl so it pulls the correct version. I'll submit a PR, cherry-pick that to 1.4 and then create a istio.io PR updating the two commands removing the ISTIO_VERSION.

**Comment by ericvn** [comment]
https://github.com/istio/istio/pull/19047 fixes downloadIstioCtl.sh to remove beta, rc, alpha versions.

**Comment by ericvn** [comment]
https://github.com/istio/istio.io/pull/5792 removes from itsio.io commands.
