### ISSUE TITLE
Problem with startinhg istio-sidecar-injector pod due to service account missing

### ISSUE THREAD

**Issue by es1o** [istio/istio#19029]
Hello.
I'm new to istio and I tried to run it in minikube. I use instruction from official website (https://istio.io/docs/setup/getting-started/).

I use demo profile to install istio but some pods can't start:
```
grafana-6b65874977-nr5k7                  1/1     Running             0          22m
istio-citadel-5cd5c778bf-j25hh            0/1     InvalidImageName    0          22m
istio-egressgateway-787c599bbf-h2vxv      0/1     InvalidImageName    0          22m
istio-galley-6889dbd5b7-kghz2             0/1     ContainerCreating   0          14m
istio-ingressgateway-7456579799-wgfpj     0/1     InvalidImageName    0          14m
istio-pilot-69886cd77d-2f4qb              0/1     InvalidImageName    0          14m
istio-policy-6978fc4c5d-4qlr5             0/1     InvalidImageName    0          14m
istio-sidecar-injector-7d6bd5844c-fl8zk   0/1     ContainerCreating   0          14m
istio-telemetry-64fd8dc5c4-pfddx          0/1     InvalidImageName    0          14m
istio-tracing-c66d67cd9-lt8p5             1/1     Running             0          22m
kiali-8559969566-vkwff                    1/1     Running             0          22m
prometheus-66c5887c86-q6z9s               0/1     ContainerCreating   0          14m
```

I check sidecar-injector and it is a problem with accessing to secret: `MountVolume.SetUp failed for volume "certs" : secret "istio.istio-sidecar-injector-service-account" not found`

I don't have that secret defined. Shall I need to define it by myself or is it a bug in installator?

**Expected behavior**

All istio pods are up and running.

**Steps to reproduce the bug**
1. Start minikube cluster: `minikube start`
2. Install istio: `istioctl manifest apply --set profile=demo`

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
Istio version 1.4.0
Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:42:50Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```
**How was Istio installed?**
Homebrew
**Environment where bug was observed (cloud vendor, OS, etc)**
MacOS X minikube 1.5.1

**Comment by howardjohn** [comment]
citadel creates the secret but it's not running due to invalid image because the Homebrew build of Istio has some bugs. Please use the official release istioctl until we can fix Homebrew.

**Comment by howardjohn** [comment]
Going to close this since it's a duplicate, thanks for reporting
