### ISSUE TITLE
The jaeger service could not be accessed via http://localhost:15032 with the version 1.4.0

### ISSUE THREAD

**Issue by quzhixue-Kimi** [istio/istio#19021]
**Bug description**
Based on the doc, the jaeger service could not be accessed.
But, when I run the 
'docker run -itd --restart=always --name=jaeger -p 5775:5775/udp -p 6831:6831/udp -p 6832:6832/udp -p 5778:5778 -p 16686:16686 -p 14268:14268 -p 9411:9411 jaegertracing/all-in-one:1.14', which could accessed via http://localhost:16686

Docs
Installation

**Expected behavior**
When visit http://localhost:15032, the jaeger could be used.

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
client: v1.16.3
server: v.1.14.7

**How was Istio installed?**
download the version 1.4.0 based on https://istio.io/docs/setup/getting-started/#download
And follow the doc based https://istio.io/docs/setup/platform-setup/docker/
apply 'kubectl apply -f istio-demo.yaml'
And then, based on https://istio.io/docs/tasks/observability/gateways/ with Option 2: Insecure access (HTTP) to install these four components.

**Environment where bug was observed (cloud vendor, OS, etc)**
Macbook pro with OS 10.15.1

Sorry for your inconvenience.
BR
Kimi

**Comment by douglas-reid** [comment]
What was the state of jaeger in your cluster at this time?  Was everything up and running?

I'm not clear what the `docker run` bits in your bug description entails. Did you run the all-in-one image before or after you failed to connect via the gateway?  Why did you feel the need to run that container?

**Comment by quzhixue-Kimi** [comment]
Hi there,

I just follow the doc as below to run all components and, the jaeger service starts up.
download the version 1.4.0 based on https://istio.io/docs/setup/getting-started/#download
And follow the doc based https://istio.io/docs/setup/platform-setup/docker/
apply 'kubectl apply -f istio-demo.yaml'
And then, based on https://istio.io/docs/tasks/observability/gateways/ with Option 2: Insecure access (HTTP) to install these four components.

to run 'docker run' command is that I want to check the jaeger service only and, when I follow the doc, I stopped and rm the docker container.

Sorry for your inconvenience.
BR
Kimi

**Comment by quzhixue-Kimi** [comment]
hi there,
from install/kubernetes/istio-demo.yaml file, I could see as below:
spec:
      containers:
        - name: jaeger
          image: "docker.io/jaegertracing/all-in-one:1.14"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9411
            - containerPort: 16686
            - containerPort: 14250
            - containerPort: 14267
            - containerPort: 14268
            - containerPort: 14269
            - containerPort: 5775
              protocol: UDP
            - containerPort: 6831
              protocol: UDP
            - containerPort: 6832
              protocol: UDP
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: BADGER_EPHEMERAL
            value: "false"
          - name: SPAN_STORAGE_TYPE
            value: "badger"
          - name: BADGER_DIRECTORY_VALUE
            value: "/badger/data"
          - name: BADGER_DIRECTORY_KEY
            value: "/badger/key"
          - name: COLLECTOR_ZIPKIN_HTTP_PORT
            value: "9411"
          - name: MEMORY_MAX_TRACES
            value: "50000"
          - name: QUERY_BASE_PATH
            value:  /jaeger 
          livenessProbe:
            httpGet:
              path: /
              port: 14269
          readinessProbe:
            httpGet:
              path: /
              port: 14269
          volumeMounts:
          - name: data
            mountPath: /badger
          resources:
            requests:
              cpu: 10m

**Comment by objectiser** [comment]
@douglas-reid Reproduced on minikube:

```
curl -L https://istio.io/downloadIstio | ISTIO_VERSION=1.4.0 sh -
export PATH="$PATH:/..../istio-1.4.0/bin"

istioctl manifest apply --set profile=demo

istioctl dashboard jaeger
```
Jaeger UI displays correctly.

Then installed tracing gateway config from https://istio.io/docs/tasks/observability/gateways/#option-2-insecure-access-http

Setup port forwarding:
```
kubectl port-forward <istio-ingressgateway-pod> -n istio-system 15032:15032
```
Opened browser on `localhost:15032` but got a blank page.

Tried same with Prometheus gateway and the Prometheus UI displayed correctly.

**Comment by objectiser** [comment]
I think the problem is that the `tracing` service is now mapped onto the zipkin port:
```
tracing                  ClusterIP      10.98.61.189     <none>        9411/TCP
```
which is only used for collection in Jaeger.

**Comment by quzhixue-Kimi** [comment]
hi @objectiser,
Thank you for your feedback and investigation.
Absolutely, you are right, the prometheus, grafana and kiali could be accessed only, the jaeger not.


Sorry for your inconvenience.
BR
Kimi

**Comment by objectiser** [comment]
Assuming that `istioctl manifest apply` is using the new installer, the problem is here: https://github.com/istio/installer/blob/master/istio-telemetry/tracing/templates/service.yaml#L35 / https://github.com/istio/installer/blob/master/istio-telemetry/tracing/values.yaml#L90

This is a breaking change, as the port was `80` (tracing provider independent UI port) but is now `9411`.

**Comment by objectiser** [comment]
@quzhixue-Kimi No problem - thanks for reporting the issue. I'll wait for @douglas-reid to provide feedback to work out the best way forward.

**Comment by douglas-reid** [comment]
@objectiser let's fix it in the installer. it should be port `80` to my understanding.

**Comment by objectiser** [comment]
@douglas-reid I'll create a PR later this week - unless someone else has time before.
