### ISSUE TITLE
istioctl profile diff should take 2 profiles as arguments

### ISSUE THREAD

**Issue by jwendell** [istio/istio#19044]
Instead of having to dump two profiles into files and submit those files to `istioctl profile diff`, it would be more straightforward to just supply two profile names to the command, e.g.:

`istioctl profile diff default demo`

**Comment by howardjohn** [comment]
I think part of the benefit of the current approach is you can provide your own profile. Although it could also just support profile name or file

**Comment by jwendell** [comment]
yeah, supporting both would be nice, e.g., having a `-f` flag to refer to files instead of profile names.

**Comment by esnible** [comment]
As a work-around until this work is done:

```
istioctl profile diff <(istioctl profile dump default)<(istioctl profile dump demo)
```

**Comment by jwendell** [comment]
not stale
