### ISSUE TITLE
Tutorial "Kubernetes Ingress with Cert-Manager" doesn't work at 1.4.0

### ISSUE THREAD

**Issue by davidraleigh** [istio/istio#19049]
**Bug description**
After Installing using these guides:
Setup -> Platform Setup -> Google Kubernetes Engine
Setup -> Install -> Customizable Install with Istioctl

Task in documentation for certmanager + let's encrypt fails at [Setting Up a Demo Application](https://istio.io/docs/tasks/traffic-management/ingress/ingress-certmgr/#setting-up-a-demo-application). Doc location:
Tasks -> Traffic Management -> Ingress -> Kubernetes Ingress with Cert-Manager

when you execute the `cat <<EOF | kubectl apply -f - ` of helloworld Service, Deployment and Ingress in docs the first error you get is:
```bash
service/helloworld created
error: error validating "STDIN": error validating data: ValidationError(Deployment.spec): missing required field "selector" in io.k8s.api.apps.v1.DeploymentSpec; if you choose to ignore these errors, turn validation off with --validate=false
```
After that, if you create a `temp.yaml` file of the helloworld Service, Deployment and Ingress, and `kubectl apply -f temp.yaml  --validate=false` the file you get this error:
```bash
service/helloworld unchanged
ingress.networking.k8s.io/helloworld-ingress created
The Deployment "helloworld" is invalid: 
* spec.selector: Required value
* spec.template.metadata.labels: Invalid value: map[string]string{"app":"helloworld"}: `selector` does not match template `labels`
```
This is pretty straightforward to reproduce. Either something isn't clear in documentation or there's a problem with GKE + Istio + cert manager.

I've been playing around with this tutorial for a while now and I've never had it successfully work on GKE with any of the 1.3.* versions of istio. I was hopefule that 1.4.0 would work as I saw the documentation had been updated.

**Expected behavior**
Tutorial would work and I could have Let's encrypt create certificates for cluster.

**Steps to reproduce the bug**
Setup -> Platform Setup -> Google Kubernetes Engine
Setup -> Install -> Customizable Install with Istioctl
Tasks -> Traffic Management -> Ingress -> Kubernetes Ingress with Cert-Manager

my inputs:
```bash
gcloud container clusters create test-1-4-0   --cluster-version latest   --machine-type=n1-standard-2   --num-nodes 4   --zone us-central1-f   --project $PROJECT_NAME
gcloud container clusters get-credentials test-1-4-0 --zone us-central1-f --project $PROJECT_NAME
kubectl create clusterrolebinding cluster-admin-binding     --clusterrole=cluster-admin     --user=$(gcloud config get-value core/account)

istioctl manifest apply

istioctl manifest apply   --set values.gateways.istio-ingressgateway.sds.enabled=true   --set values.global.k8sIngress.enabled=true   --set values.global.k8sIngress.enableHttps=true   --set values.global.k8sIngress.gatewayName=ingressgateway
kubectl -n istio-system get service istio-ingressgateway
kubectl get svc -n istio-system
kubectl get pods -n istio-system
```
make sure all pods are running. take external ip for svc and associate that with `INGRESS_DOMAIN`.

```bash
INGRESS_DOMAIN=my.domain.com
kubectl -n istio-system   patch gateway istio-autogenerated-k8s-ingress --type=json   -p='[{"op": "replace", "path": "/spec/servers/1/tls", "value": {"credentialName": "ingress-cert", "mode": "SIMPLE", "privateKey": "sds", "serverCertificate": "sds"}}]'

kubectl get pods -n istio-system
kubectl get svc -n istio-system
```
make sure that above applied updates work.

Execute `kubectl apply` command with [this section](https://istio.io/docs/tasks/traffic-management/ingress/ingress-certmgr/#setting-up-a-demo-application).

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```bash
client version: 1.4.0
control plane version: 1.4.0
data plane version: 1.4.0 (1 proxies)
```
**How was Istio installed?**
Setup -> Platform Setup -> Google Kubernetes Engine
Setup -> Install -> Customizable Install with Istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

**Comment by davidraleigh** [comment]
[istio-dump.tar.gz](https://github.com/istio/istio/files/3860535/istio-dump.tar.gz)

**Comment by howardjohn** [comment]
Thanks, looks like a pretty straightforward docs error the deployment yaml is not correct

**Comment by howardjohn** [comment]
Fixed by istio/istio.io/5777 thanks!
