### ISSUE TITLE
GKE Istio 1.4.0 istio-sidecar-injector Internal error occurred: failed calling webhook 

### ISSUE THREAD

**Issue by xvzup** [istio/istio#19066]
**Bug description**

The automatic injection of sidecars is not working. Manual injection using istioctl works fine. The namespace is labeled:
labels:
    istio-injection: enabled

No pod is scheduled. The following log is printed:

0s          Warning   FailedCreate             replicaset/test-c7fc56544    Error creating: Internal error occurred: failed calling webhook "sidecar-injector.istio.io": Post https://istio-sidecar-injector.istio-system.svc:443/inject?timeout=30s: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Expected behavior**

Pod should be deployed with corresponding sidecar.

**Steps to reproduce the bug**

GKE:
- gcloud beta container clusters create cluster1 --create-subnetwork=name=sub-cluster,range=192.168.10.0/24 --services-ipv4-cidr=172.16.0.0/24 --default-max-pods-per-node=64 --enable-autorepair --enable-autoupgrade --network k8s-net --machine-type=n1-standard-4 --enable-ip-alias --metadata disable-legacy-endpoints=true --enable-private-nodes --no-enable-master-authorized-networks --master-ipv4-cidr 192.168.109.0/28  --enable-autoscaling --max-nodes=5 --min-nodes=1 --num-nodes=1 --cluster-version latest
- kubectl create clusterrolebinding cluster-admin-binding --clusterrole=cluster-admin --user=$(gcloud config get-value account)

Istio
istioctl manifest apply

Create namespace and label it accordingly

Test deployment works:
- without sidecars and
- with manual injection

Network communication works as I can curl https://istio-sidecar-injector.istio-system.svc:443/inject

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

client version: 1.4.0
control plane version: 1.4.0
data plane version: 1.4.0 (1 proxies)

**How was Istio installed?**

istioctl manifest apply

**Environment where bug was observed (cloud vendor, OS, etc)**

GKE Version 1.14.8-gke.12

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive
[istio-dump.tar.gz](https://github.com/istio/istio/files/3863393/istio-dump.tar.gz)
) by attaching
the dump file to this issue.

**Comment by xvzup** [comment]
There was a firewall rule missing.
We need to allow traffic to port 9443.

**Comment by sakajunquality** [comment]
@xvzup maybe I'm having the same issue, can you share what you did to solve this?

**Comment by sakajunquality** [comment]
Figured out the solution... thanks

**Comment by quentinleclerc** [comment]
Hi,
@xvzup @sakajunquality can you please explain what was the problem and how did you fix it? I have the exact same problem on one of my clusters and not in another with very similar Istio configuration.

**Comment by hahomdal** [comment]
@quentinleclerc : Add a firewall which allows the master_ipv4_cidr range as source to talk to the network target tag for your instances on port 9443. 

To get the network target tag, do for instance:
`gcloud` compute instances list --project <project> --format=json | /usr/bin/jq '.[].tags.items[0]'|head -1`

Thereafter adapt the following command to suit your environment:
`gcloud compute firewall-rules create allow-master-to-istiowebhook --allow=tcp:9443 --direction=INGRESS --enable-logging --source-ranges=<master_ipv4_cidr> --target-tags=<instance network target tag> --action=ALLOW`

**Comment by quentinleclerc** [comment]
Thank you @hahomdal, it fixed the issue.

I can't find any changes in the behavior of the sidecar injection webhook in releases notes between 1.2.2 (my previous version) and 1.4.0. Do you have any issues/links or explanations on what changes led to the need for this firewall rule?

**Comment by jroper** [comment]
I have a much more detailed writeup of this issue here:

https://github.com/istio/istio/issues/19532

**Comment by kevinsingapore** [comment]
i have met the same error, and do u have sovle it？
