### ISSUE TITLE
How to ensure only certain Pods in a namespace get injected with istio-proxy?

### ISSUE THREAD

**Issue by satyajituk** [istio/istio#19068]
I am using GKE which takes care of the control plane once I switch it ON for the cluster. 
I want to inject istio-proxy only for certain Pods in a namespace. 
I did the following steps:

- Added `istio-injection=enabled` in my namespace
- Added `sidecar.istio.io/inject: "true"` in the deployment file of my particular service. 

What happened is that ALL pods of the namespace ended up getting the sidecar when they restarted. This shouldn't have happened according to this: https://istio.io/docs/ops/setup/injection-concepts/
So how to ensure this doesn't happen?

Also is there any other step to do to ensure istio is working as expected? Since I can't see all my instances doing work. I only see one instance of a service doing the work and the other just sitting there.

**Comment by howardjohn** [comment]
If you look at the table in the doc you linked there is a default policy. By default this is enabled, which means that anything in the namespace where it's enabled is injected. You can then opt OUT by adding the annotation

**Comment by satyajituk** [comment]
You mean I can have a deployment opt OUT by having `sidecar.istio.io/inject: "false"` ? Thanks!

**Comment by howardjohn** [comment]
yep that should work
