### ISSUE TITLE
Helm install of sidecarInjectorWebhook fails with error nil pointer evaluating interface {}.imagePullSecrets

### ISSUE THREAD

**Issue by rishiraaz** [istio/istio#19063]
**Bug description**
Helm install of sidecarInjectorWebhook fails with error nil pointer evaluating interface {}.imagePullSecrets

**Expected behavior**
installation should proceed.

**Steps to reproduce the bug**
Manually install sidecarInjectorWebhook
**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
Helm v2.14.3
Istio 1.3.5
KUbectl v1.14.8
**How was Istio installed?**
Using helm, istio-demo was setup

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by richardwxn** [comment]
what is your istioctl version --remote output?

**Comment by rishiraaz** [comment]
@richardwxn istioctl version --remote

client version: 1.3.5
control plane version: 1.3.5

**Comment by howardjohn** [comment]
what helm command did you use?

**Comment by richardwxn** [comment]
Are you following this guide with helm installation: https://istio.io/docs/setup/install/helm/

**Comment by howardjohn** [comment]
if I had to guess this is installed by istio/installer without -f global.yaml

**Comment by rishiraaz** [comment]
helm install install/kubernetes/helm/istio --name istio --namespace istio-system \
    --values install/kubernetes/helm/istio/values-istio-demo.yaml
Used the above command for installation

**Comment by howardjohn** [comment]
I could not reproduce, can you give more info on how we can?

**Comment by rishiraaz** [comment]
@howardjohn guess this is something to do with galley
 helm install install/kubernetes/helm/istio/charts/galley --name galley --namespace istio-system
Error: render error in "galley/templates/serviceaccount.yaml": template: galley/templates/serviceaccount.yaml:3:14: executing "galley/templates/serviceaccount.yaml" at <.Values.global.imagePullSecrets>: nil pointer evaluating interface {}.imagePullSecrets

**Comment by howardjohn** [comment]
that's not a valid way to install it, you cannot point directly to the galley chart or it loses all the global values (as you noticed)

**Comment by rishiraaz** [comment]
@howardjohn thanks, will close this issue.
