### ISSUE TITLE
istio proxy sidecar doesn't stop when pod completed

### ISSUE THREAD

**Issue by zzzhy** [istio/istio#19072]
**Bug description**
env: openshift 
namespace: istio-injection=enabled
as you see, when I deploy a image on the openshift (what ever image, here i used a nginx image), it lanched a deploy pod to do the job for me. This is quite normal but, when the deploy job done, the deploy container completed while the sidecar still running...
![image](https://user-images.githubusercontent.com/10076707/69166063-96396880-0b2d-11ea-8219-003e775d800f.png)
here's its log page. we can see the running status of the sidecar .
what should I do to prevent this situation or just treat it as a bug ?
![image](https://user-images.githubusercontent.com/10076707/69166074-9c2f4980-0b2d-11ea-9407-732f87fb0657.png)

**Expected behavior**
the sidecar stops as wished.
**Steps to reproduce the bug**
deploy a image on openshift
**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istio: 1.3.2
OpenShift Master: v3.11.0+d8e0721-172
Kubernetes Master: v1.11.0+d4cacc0
OpenShift Web Console: v3.11.0+ea42280
**How was Istio installed?**
whatever
**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by bianpengyuan** [comment]
This is a known issue that sidecar won't terminate when job finishes. Please take a look at https://github.com/istio/istio/issues/11659 for the workaround.
