### ISSUE TITLE
Analyzer for new  v1beta authorization policy resource

### ISSUE THREAD

**Issue by sushicw** [istio/istio#19076]
We should write one or more new [analyzers](https://github.com/istio/istio/blob/master/galley/pkg/config/analysis/README.md) to cover the new v1beta1 authz policy config.

https://istio.io/blog/2019/v1beta1-authorization-policy/

https://istio.io/docs/reference/config/security/authorization-policy

Some analysis rules that probably make sense:

* Make sure that the workload selectors are pointing at a valid pod. (We've already got logic for this for some other analyzers, should be able to share / recycle)
* Make sure the "From" and "To" fields map to things that exist.
* Print a warning / info message if both v1beta1 and v1alpha1 policies are applied to a given workload. (Explain that the v1alpha1 stuff is ignored, point them at properly migrating). 

This will be a good case to make sure that we properly do analysis in these cases where we switch from one model to another, using new resources. It should "just work," it'll be nice to prove / disprove that. :)

**Comment by sushicw** [comment]
From @xeviknal in https://github.com/istio/istio/issues/20025 : 

> Add an analyzer for the AuthenticationPolicy objects.
> What to analyze?
> 
> WorkloadSelector: check if there are deployments (creating pods) with the specific labels.
> Rule.From.Source.Namespace: check if that list of namespaces are present.
> Rule.To.Operation.Methods: check if they are HTTP allowed methods or gRPC well formatted values (/pkg.svc/method)
> Rule.To.Operation.Hosts: check if each host of the list exists.

**Comment by xeviknal** [comment]
@yangminzhu I see this task is marked as stale. Are you going to implement it? I will have some space in the following weeks to approach it. wdyt?

**Comment by yangminzhu** [comment]
@xeviknal Sure, feel free to go ahead to send out PRs, I will not have time to work on it recently. Thank you very much for helping on this!
