### ISSUE TITLE
Upgrade CI to kind v0.6

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#19071]
TODO:

* Update build-tools
* Pin the node image in istio/istio
* Figure out what is needed to support the kubeconfig changes, especially with multicluster
* Set `-v something` flag.
* Upgrade to new node images
* Run `kind version` somewhere for debugging

**Comment by sdake** [comment]
@howardjohn this is done correct?

if so, would you mind closing.

Cheers
-steve
