### ISSUE TITLE
Add `namespace` model and related watcher

### ISSUE THREAD

**Issue by diemtvu** [istio/istio#19083]
To support the new way to set mTLS ([design doc](https://docs.google.com/document/d/1RAsCl4n_F75ANAXrbI9tllA8QmE4etQ3HBHXNjxLPTo/edit#), [issuer](https://github.com/istio/istio/issues/18399)) via namespace annotation/labels, we need to add `namespace` model to Istio, and a function to return the list of namespaces from `Environment`. The simplest option is adding a function such as `Namespaces` to [ServiceDiscovery](https://github.com/istio/istio/blob/master/pilot/pkg/model/service.go#L409) interface and implement appropriate watcher/handler for each platform.

That information will be cached into `PushContext` to extract mTLS settings for the target proxy.

Blocking https://github.com/istio/istio/issues/18399

**Describe alternatives you've considered**

If (get) `Namespaces` function does not fit well with ServiceDiscovery, may be have separate interface for it (e.g NamespaceDiscovery). However, it can be implemented via the same controller under the hood.

Other alternative is via Galley / config store.

**Affected product area (please put an X in all that apply)**

[X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by diemtvu** [comment]
@costinm Do you think this make sense?

**Comment by rshriram** [comment]
I dont think the discussion on the design doc on whether to do annotations vs a simple option in the sidecar CRD was resolved. There are still comments from @nrjpoddar and myself expressing concerns on use of annotations to configure core features like this.

**Comment by incfly** [comment]
closing i don't think we are heading to this direction.
