### ISSUE TITLE
Huge cardinality and complexity jump with telemetry v2

### ISSUE THREAD

**Issue by Stono** [istio/istio#19090]
Hey all, 
I just wanted to share this concern as an issue so it can be discussed further.  My believe is that telemtry v2 will increase prometheus metric cardinality quite significantly, especially for those with existing deployments on large clusters like ours.

This is because of the roll-up effect that the current mixer has at the moment.  What I mean by rollup is that the `pod_name` is not a label on some of the biggest istio metrics, eg:

- istio_request_duration_seconds_bucket
- istio_response_bytes_bucket
- istio_request_bytes_bucket

So take this simplistic example:

![mixer](https://user-images.githubusercontent.com/1486729/69218193-1bda0a00-0b68-11ea-83eb-251acc9bfb11.png)

Currently you would end up with something like:

```
istio_request_duration_seconds_bucket{app="service1", instance="ip-of-mixer", le="whatever"} 40
```

With telemetry v2 you will end up with:

```
istio_request_duration_seconds_bucket{app="service1", pod_name="pod1", le="whatever"} 10
istio_request_duration_seconds_bucket{app="service1", pod_name="pod1", le="whatever"} 10
istio_request_duration_seconds_bucket{app="service1", pod_name="pod1", le="whatever"} 10
istio_request_duration_seconds_bucket{app="service1", pod_name="pod1", le="whatever"} 10
```

Each of these metrics already has high cardinality being a histogram (the `le` label), so this will result in huge increases in prometheus metrics.

Many of our applications run 10-20 pods, so the metrics explosion of switching to metrics which are labeled with the pod name I believe is going to be pretty huge and potentially unmanageable.

**Comment by bianpengyuan** [comment]
Thanks for bring this up! Could you share a bit more about what could be unmanageable? Is it prom query latency, or prom cpu usage?

I don't think we've measured telemetry v2's impact on prometheus server. We should also measure it in our load test.

**Comment by Stono** [comment]
Hello, 
Several things really, as the majority of our dashboards and alerts query these metrics, significantly increasing the cardinality impacts both query performance and prometheus cpu.  Cardinality also significantly impacts prometheus RAM usage.

As an example, we've recently been looking at moving to grafanalabs hosted prometheus which charges consumption pricing based on number of unique series.  At the moment, the cardinality of these metrics is tied to the number of mixer instances (by `instance=ip`).  

You can see here how I halved the number of unique series we were sending purely by going from 4 instances of telemetry to 2 (just to highlight the impact label cardinality has at scale):

![image](https://user-images.githubusercontent.com/1486729/69230857-f0fbb000-0b7f-11ea-958c-f64bc8c78c60.png)

Here you can see the impact of that same change on prometheus RAM:

<img width="1670" alt="Screenshot 2019-11-20 at 10 15 46" src="https://user-images.githubusercontent.com/1486729/69230836-e5a88480-0b7f-11ea-9d21-182fc5dadf9d.png">

**Comment by howardjohn** [comment]
> the only other solution we could do is created a tiered prometheus architecture

Not a Prometheus expert but I was under the impression we could just drop the pod name label and everything should work, is that not true?

**Comment by Stono** [comment]
@howardjohn nope it isn't, the only way to "drop" the pod name and roll up the metrics is to have a recording rule which records a new metric as an aggregate of the others.

If you just drop that label now in your scrape config you'll end up with duplicate metrics:

```
istio_request_duration_seconds_bucket{app="service1", pod_name="pod1", le="whatever"} 10
istio_request_duration_seconds_bucket{app="service1", pod_name="pod1", le="whatever"} 10
```

becomes:
```
istio_request_duration_seconds_bucket{app="service1", le="whatever"} 10
istio_request_duration_seconds_bucket{app="service1", le="whatever"} 10
```

not:
```
istio_request_duration_seconds_bucket{app="service1", le="whatever"} 20
```

See: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#metric_relabel_configs

> Care must be taken with labeldrop and labelkeep to ensure that metrics are still uniquely labeled once the labels are removed.

**Comment by mandarjog** [comment]
@Stono thanks for bringing it up.
We use the operator in large cluster testing so did not experience this issue. Direct pod and endpoint scraping is also the way to export application metrics, so this is not unusual. Perhaps need last mile aggregate and record here. We will get back to you.

**Comment by Stono** [comment]
To be clear, I don't have an issue with pod scraping and i'm not saying the direction you're going is wrong.  We already selectively scrape pod application metrics, and envoy stats on certain important applications.

But you asked me to think about implications of telemetry v2, so i'm purely calling out why adding `pod_name` as a label on already high cardinality istio metrics, for existing users at scale, is a considerable change and one that will impact me personally quite a bit.

As an example; on your test cluster - deploy:

  - 20x workloads with 10 pods each, with 2x mixer's
  - go into prometheus and do `count({__name__="istio_request_bytes_bucket"})`

Ignoring all the other labels your cardinality there is effectively:

  - 20 (workloads) x 2 (mixer `instances`) x 10 (`le`) = 400

Now deploy mixer v2, and check the same count in prometheus and do the same count, you'll likely see it much higher as your cardinality is now:

  - 20 (workloads) x 10 (`pod_name`) x 10 (`le`) =  2000

So effectively a 5 fold increase on this example, on a single metric, and there are quite a few high cardinality istio metrics.

This impacts query performance and resource requirements and in my case, managed prometheus cost.

**Comment by Stono** [comment]
There is also the added issue of `pod_name` for us changes a lot (we deploy 100s of times daily) so its a very high churn label.  Doing any sort of aggregation over time further compounds the issue.

**Comment by mandarjog** [comment]
Pod name is added by scraper, it should not be a dimension on the base metric. Will check.

**Comment by douglas-reid** [comment]
`pod_name` is added (in the default istio config) by the scrape job:

https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/prometheus/templates/configmap.yaml#L237-L239

We definitely want to aggregate over pods. Providing a transition guide is part of the planned deprecation story @Stono. I expect advice on scaling, etc., to be part of that transition guide.

**Comment by Stono** [comment]
Sounds good.
My gut is that you'll need a rolling up recording rule but then the problem you'll have is you'll be storing both unrolled and rolled up series, albeit only querying across one of them.

Also recording rules aggregating across such a large set of metrics are going to be pretty heavyweight.

Looking forward to your suggestions.

**Comment by mandarjog** [comment]
@douglas-reid the instance label has the same cardinality as the pod name so getting rid of it may not move the needle.

**Comment by Stono** [comment]
> @douglas-reid the instance label has the same cardinality as the pod name so getting rid of it may not move the needle.

that is not true, in telemetry v1 instance=ip of mixer, in v2 pod_name=the application pod.

# of mixers <<<<< # of pods.

**Comment by douglas-reid** [comment]
in v2, we are going to be collecting from a large number of sources and we need to account for that appropriately. **any** problematic labels will need to be dealt with, `instance`, `pod_name` or otherwise.

**Comment by Stono** [comment]
To add to this, please see https://github.com/istio/istio/issues/20060 where Locality Aware Routing multiplies some of these high cardinality metrics by the number of zones

**Comment by howardjohn** [comment]
not stale?

**Comment by Stono** [comment]
The result of a days worth of deployments cardinality on metrics with telemetry v2 :-( 

This wouldn't increment at all on v1 due to the rollup effect of mixer.

<img width="805" alt="Screenshot 2020-02-21 at 18 53 43" src="https://user-images.githubusercontent.com/1486729/75062872-92760300-54db-11ea-8929-6cf67286ea1e.png">

We're likely going to have to do a tiered prometheus approach in order to deal with this

**Comment by Stono** [comment]
It might be because it's 10pm and i'm dealing with issues caused by the migration to telemetry v2, but I need to express just how much worse this is for us at our scale.  And warn of anyone else from migrating to v2.

Mixers previous behaviour of rolling up Istios very high cardinality metrics is **required**, without it, the istio metrics sliced by every pod on your cluster create such an overhead on prometheus.  Memory footprint goes up significantly, queries are slower.  It's a nightmare.

Subsequently, you have no choice but to move towards a federated prometheus architecture, where you have a prometheus in the middle, responsible for scraping all of your sidecars, and then it has recording rules to "roll them up".  Your primary prometheus then scrapes that intermediary prometheus for the rolled up metrics.  That prometheus server becomes a behemoth, as it's got all the original data **and** the recording rules version of that.  

But guess you've just had to build there?  Mixer from telemetry v1!  A service in the middle simply to roll up extremely high cardinality metrics!

However rolling it yourself is significantly more complicated than simply deploying mixer.    Federated prometheus are a pain, for example; getting your scrape intervals right so you don't miss data, ensuring you don't miss labels during rollups.   The istio upgrade process now becomes more complex because in each release we're going to have to make sure our recording are still compatible.

You've significantly increased the complexity of running Istio at scale for operators with this change, it is - in my honest opinion, a bad move.

**Comment by mandarjog** [comment]
@Stono I hear you. We will do several things to address your concerns.

1. Provide a way to consolidate/roll up metrics with prometheus and support it.
2. Reduce the amount of data that is scraped. This is imminently doable. we already proxy from :15090/stats/prometheus. --> :15020/stats/prometheus,  we can add a usedonly and a filter param.
This should reduce the scraped amount to what we really want.

I have [spoken](https://github.com/prometheus/prometheus/issues/6352) with Prometheus maintainers, and  they say that scraping every endpoint is the standard and supported way of doing Prom. Mixer V1 provided an alternative, but it is not the norm.

@douglas-reid

**Comment by Stono** [comment]
I agree that it is the standard way of doing prometheus, my grief here is because as an end user the transition to v2 is absolute agony.

There are significant tradeoffs with this approach which need to be clearly defined, addressed and mitigated to help users who have large, production systems, using v1.

**Comment by Stono** [comment]
Also see https://github.com/istio/istio/issues/21377

**Comment by Stono** [comment]
FYI for anyone coming to this thread, I wrote a blog post on how we've tackled this with federation and rollup rules:  https://karlstoney.com/2020/02/25/federated-prometheus-to-reduce-metric-cardinality/
