### ISSUE TITLE
Adaptor development should not mandate bazel

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#1909]
(cc @geeknoid @rshriram )
We had a lot of tension lately with the trend to use gotool and skip bazel for local development and testing. The situation is mostly complicated by the fact that Mixer adaptor development model for in-process adaptor mandates the use of bazel and code generation through bazel. This is the major obstacle to a pure go build of Istio. Can we define a goal to eventually make bazel optional for Mixer adaptor development?

We've started the process already by publishing the generated proto code out there. That means bazel is no longer required for using those protos (e.g. API tooling developer can use `go get`).

We could do it step-by-step. First, externalize code generation tooling to bazel-neutral code, and invoke that code from bazel. Second, provide scripts to run this same code out of bazel, and allow pure go tooling familiar to every single go developer in the world. 

If we find that bazel is that much superior to a non-bazel model, we can also _recommend_ it, and officially _support_ it. Not providing alternatives hurts our adoption by excluding developers that want to integrate with istio but cannot use bazel (due to its fairly large list of limitations).

**Comment by douglas-reid** [comment]
I think the first step is sounds reasonable. Step 1a is probably to just start with adapter config protos, before moving on to inventory generation, and finally to custom template support.

We can start enforcing a setup for generation along the lines of:

```
go get github.com/gogo/protobuf/proto
go get github.com/gogo/protobuf/jsonpb
go get github.com/gogo/protobuf/protoc-gen-gogoslick
go get github.com/gogo/protobuf/gogoproto
```

One speed-bump is the requirement for a `protoc` install. I don't know how many istio devs had `protoc` installed locally before, but this might cause slight hiccups for some devs already used to a bazel workflow.

We'll probably also have to figure out some path issues (so that we can set the import paths correctly) but I don't see anything insurmountable in doing this.

**Comment by kyessenov** [comment]
I think requiring `protoc` for development is the choice we've made for any development. Istio devs actually have protoc installed in the bazel build environment (probably around 4 protoc's actually, since bazel has no workspace aliases :( ). As a transition, we could use the compiler that comes with bazel.

For dependencies, we need to create a base template project, that has glide/dep file with all the dependencies. I'm not sure how to invoke vendorized binaries, but that should be possible I think.

**Comment by douglas-reid** [comment]
They have protoc until they clean ;). I'd prefer to not rely on the compiler from bazel at all, if our goal is to move completely away from it.

Running a few `go get`s in a script doesn't seem all that worrisome to me, but we can figure out the details as we go along. I'm gonna start playing with scripting it and see how far I get before I get tired tonight. Helps procrastinate on making slides.

**Comment by geeknoid** [comment]
Of course, the problem with having people run 'go get' for things is that
we end up with classic versionitis. It becomes difficult to universally
produce a consistent set of binaries. Different users will have different
versions of the tools. The CI system will get silently get new bits, etc.
If at some point in the future, you need to rebuild an older version of
stuff, it becomes nearly impossible to reproduce the actual build from the
past.

We've already had this kind of problem pop up several times with
gometalinter. But never with stuff under Bazel's rule.

This is one of the many 6-of-one-1/2-dozen-of-the-other problems in this
space. Bazel ain't perfect, but Makefiles definitely aren't either.

**Comment by douglas-reid** [comment]
Yeah. Thinking a bit more beyond my initial prototyping suggestion, I think @kyessenov's suggestion of including generators in the go dep manifest as `required` entries probably is the "best" option. I'm not sure how well they compose, but in the short term we could have people copy entries from the main istio/istio one and/or provide a template for starting.
