### ISSUE TITLE
proxyv2: Failed to generate bootstrap config

### ISSUE THREAD

**Issue by cober** [istio/istio#19096]
**Bug description**

**Expected behavior**
Prior v1.4.0 we never noticed this kind of issue, so far some components are working totally fine, few of them are failing

**Steps to reproduce the bug**
Install Istio v1.4.0, restart deployment in specific namespace and check if everything is runnning fine

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
`client version: 1.4.0
control plane version: 1.4.0
data plane version: 1.4.0 (41 proxies), 1.3.4 (2 proxies)
`
`Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:29Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-gke.12", GitCommit:"188432a69210ca32cafded81b4dd1c063720cac0", GitTreeState:"clean", BuildDate:"2019-11-07T19:27:01Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
`

`Client: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}`

**How was Istio installed?**
Helm

**Environment where bug was observed (cloud vendor, OS, etc)**

`2019-11-20T14:45:15.780834Z    info    Received new config, creating new Envoy epoch 0                                                                                                                                                     │
│ 2019-11-20T14:45:15.780917Z    info    watching /etc/certs for changes                                                                                                                                                                     │
│ 2019-11-20T14:45:15.780982Z    info    Epoch 0 starting                                                                                                                                                                                    │
│ 2019-11-20T14:45:15.785155Z    error    Failed to generate bootstrap config: invalid character ',' looking for beginning of value                                                                                                          `

These are the logs from proxyv2 sidecar itself.

**Comment by cober** [comment]
For some reason, if disable sidecar injection, we get it running, but somehow there we see again istio sidecars with v1.2.3. Could this be some mixup with CRDs?

**Comment by howardjohn** [comment]
@cober thanks for bringing this up. I am pretty sure this is fixed by https://github.com/istio/istio/pull/18976 which should be fixed for 1.4.1 in a couple weeks. This should be an issue in 1.3 as well, not just 1.4.

Basically the issue is you have multiple containers, some which defined `containerPort` and others that do not. As a workaround you could make all the containers have a port or none of them have a port until the fix is merged

**Comment by cober** [comment]
Thanks @howardjohn 

I am closing this issue as it will most likely be fixed in 1.4.1 - on other hand, will reopen if we spot same behaviour later on.

**Comment by rolandkool** [comment]
@howardjohn did this issue make it into the 1.4.1 release? I didn't see it being mentioned in the changelog.

**Comment by mjf-recurly** [comment]
I'm running into this issue in 1.1.4 as well. It looks like the fix wasn't back ported and won't be available until 1.4.3

**Comment by howardjohn** [comment]
@rolandkool as mentioned above this unfortunately didn't make it. In the mean time a workaround would be to apply this patch to the injection: https://github.com/istio/istio/pull/19366/files#diff-f8fc93a59be4d8ddb97b619627f4d023. Or don't have deployments with multiple containers where only some define container ports

**Comment by infa-ddeore** [comment]
other workaround would be to move the container to first position in the containers list in k8 deployment object.

the issue happens only when first container doesn't expose any port but it works when first container expose a port and rest don't

**Comment by howardjohn** [comment]
Yes that will work too. 1.4.3 will be released in a week or 2 though
