### ISSUE TITLE
Prometheus: add configmap-reload container

### ISSUE THREAD

**Issue by tkatrichenko** [istio/istio#19095]
Prometheus stable helm chart has an option of a sidecar container, which gives hot config reload to Prometheus once config file changed
https://github.com/helm/charts/blob/master/stable/prometheus/values.yaml#L278-L311

Would that be useful to add this feature to Prometheus provided by Istio helm chart?

Currently, the fastest way to reload Prometheus config is to restart the pod

**Comment by howardjohn** [comment]
Istio has a lot of third party addons like prometheus, and its not very maintainable for us to try to keep up with all of the latest install improvements and additions they are making. We are trying to move to a model where we just provide a small layer of support and allow users to install using upstream methods. For prometheus, this means providing ServiceMonitors to use with a prometheus operator for example https://github.com/istio/installer/tree/master/istio-telemetry/prometheus-operator, which basically leaves you to have full control over whatever you want to do for prometheus like config reload, persistent volumes, etc

**Comment by sdake** [comment]
@tkatrichenko thank you for the report.  What @howardjohn didn't say is that we have intentionally decided to freeze our existing addon integrations and instead move to a model where we provide a very thin set of manifests to launch the respective project's operator (We use prometheus, jaeger, kiali, and grafana, all of which have operators - there is no good reason to continue to develop parallel implementations of telemetry installations.

Istio's value is in integrating with third party components - not integrating IN third party components :)

Cheers
-steve

**Comment by tkatrichenko** [comment]
Thank you all for the explanations. It makes sense to me. Will think to use official operators instead 

Closing this ticket
