### ISSUE TITLE
SDS is not yet working with istio/installer istio/operator

### ISSUE THREAD

**Issue by pitlv2109** [istio/istio#19109]
SDS is not yet working with istio/installer istio/operator. There are a couple of issues:

1. Pilot, Galley, and telemetry-Mixer are still using file mount certs in their bootstrap config, which means they will read their file mounts certificates.  This will break Istio if the control plane is set to use an SDS-based CA (pods like ingress gateway will fail to connect to Pilot, etc. due to having different root certs).
2. Policy-Mixer has a sidecar but it's talking to Galley directly using file mounts cert.

**Comment by pitlv2109** [comment]
Fix (hopefully) for installer: https://github.com/istio/installer/pull/552

**Comment by abhinavkorpal** [comment]
> SDS is not yet working with istio/installer istio/operator. There are a couple of issues:
> 
> 1. Pilot, Galley, and telemetry-Mixer are still using file mount certs in their bootstrap config, which means they will read their file mounts certificates.  This will break Istio if the control plane is set to use an SDS-based CA (pods like ingress gateway will fail to connect to Pilot, etc. due to having different root certs).
> 2. Policy-Mixer has a sidecar but it's talking to Galley directly using file mounts cert.

Mine also facing the same issue. MountVolume.SetUp failed for volume

**Comment by balamuru** [comment]
Anything new on this?
 It's pretty important (given that SDS seems to be implicitly reccomended over file mounted secrets)

**Comment by balamuru** [comment]
What is the alternate recommendation to enable sds ?

**Comment by pitlv2109** [comment]
hey, I _think_ it should be working now, at least for recent 1.4.x release. My fix checked in a while ago. @howardjohn should have more info.

**Comment by myidpt** [comment]
I consider this as resolved. @balamuru Feel free to reopen if it's still an issue for most recent 1.4.x release.
