### ISSUE TITLE
Add check for proxy RBE base image version

### ISSUE THREAD

**Issue by bianpengyuan** [istio/istio#19104]
Context: https://github.com/istio/proxy/pull/2571#discussion_r347113639

`istio/proxy` should be built with xenial (ubuntu 16.04) tool chain because bionic (ubuntu 18.04)  glibc version is not compatible with xenial, which will make the released proxy binary not runnable on xenial VM.

`istio/proxy` post submit has switched to RBE, but there is no check on RBE base image version, we need to add that to prevent accidental upgrade breaks VM installation.

cc @PiotrSikora @lizan

**Comment by lizan** [comment]
I'm more in favor of check the produced binary, i.e. check the output of `objdump -T <envoy_binary>` to see what glibc symbol it is pulled by the binary.

**Comment by bianpengyuan** [comment]
Yeah that makes more sense.

**Comment by PiotrSikora** [comment]
Sounds good. @lizan could you add this?

**Comment by howardjohn** [comment]
Is this still needed? I think we turned off RBE

**Comment by bianpengyuan** [comment]
Yeah we have already added back base image version check in proxy release make target: https://github.com/istio/proxy/pull/2636
