### ISSUE TITLE
_istioctl auto-complete file not found

### ISSUE THREAD

**Issue by bookRa** [istio/istio#19108]
**Bug description**
 I cannot find the istio [autocompletion file as described in the docs](https://istio.io/docs/ops/diagnostic-tools/istioctl/#enabling-auto-completion)
[x] Docs

**Expected behavior**
There is a `_istioctl` file that I can `source` in my `.zshrc`

**Steps to reproduce the bug**
```
❯ ls -aR istio-1.4.0/tools
.                                          convert_RbacConfig_to_ClusterRbacConfig.sh packaging
..                                         dump_kubernetes.sh

istio-1.4.0/tools/packaging:
.      ..     common

istio-1.4.0/tools/packaging/common:
.                 ..                istio-iptables.sh
```
**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**
```
❯ istioctl version --remote
client version: 1.4.0
control plane version: 1.2.8
data plane version: 1.1.14 (1 proxies), 1.2.8 (25 proxies), 1.1.3 (1 proxies)
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.10-gke.17", GitCommit:"27b48e2b4c9535d185ec945c6a513537e4d116cf", GitTreeState:"clean", BuildDate:"2019-10-21T20:10:26Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
```
Thanks for your help and work!

**Comment by howardjohn** [comment]
@bookRa thanks for the report! We noticed this recently as well and sent out a fix, so this will be included in 1.4.1. Sorry for the inconvenience. See https://github.com/istio/release-builder/pull/74
