### ISSUE TITLE
Helm install using values-istio-demo.yaml fails to install mutatingwebhookconfiguration

### ISSUE THREAD

**Issue by rishiraaz** [istio/istio#19113]
Bug description
Helm install using values-istio-demo.yaml fails to install mutatingwebhookconfiguration

 kubectl get mutatingwebhookconfiguration
No resources found.

Expected behavior
installation should proceed.

Steps to reproduce the bug
helm install  install/kubernetes/helm/istio --name istio --namespace istio-system --values install/kubernetes/helm/istio/values-istio-demo.yaml

Version (include the output of istioctl version --remote and kubectl version and helm version if you used Helm)
Helm v2.14.3
Istio 1.3.5
KUbectl v1.14.8
How was Istio installed?
helm install  install/kubernetes/helm/istio --name istio --namespace istio-system --values install/kubernetes/helm/istio/values-istio-demo.yaml

Environment where bug was observed (cloud vendor, OS, etc)

**Comment by rishiraaz** [comment]
`
global:
  proxy:
    accessLogFile: "/dev/stdout"
    resources:
      requests:
        cpu: 10m
        memory: 40Mi

  disablePolicyChecks: false

sidecarInjectorWebhook:
  enabled: true
  # If true, webhook or istioctl injector will rewrite PodSpec for liveness
  # health check to redirect request to sidecar. This makes liveness check work
  # even when mTLS is enabled.
  rewriteAppHTTPProbe: false

pilot:
  enabled: true
  autoscaleEnabled: false
  replicaCount: 1
  traceSampling: 100.0
  resources:
    requests:
      cpu: 10m
      memory: 100Mi

mixer:
  policy:
    enabled: true
    autoscaleEnabled: false
    resources:
      requests:
        cpu: 10m
        memory: 100Mi

  telemetry:
    enabled: true
    autoscaleEnabled: false
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
 
  adapters:
    stdio:
      enabled: true
 
grafana:
  enabled: false

tracing:
  enabled: true

kiali:
  enabled: false
  createDemoSecret: false

gateways:
  istio-ingressgateway:
    autoscaleEnabled: false
    resources:
      requests:
        cpu: 10m
        memory: 40Mi

  istio-egressgateway:
    enabled: true
    autoscaleEnabled: false
    resources:
      requests:
        cpu: 10m
        memory: 40Mi
global:
  controlPlaneSecurityEnabled: false

  mtls:
    enabled: true
`

**Comment by rishiraaz** [comment]
istioctl version --remote

client version: 1.3.5
control plane version: 1.3.5

**Comment by howardjohn** [comment]
helm will generally mention when something goes wrong, right? is there any error messages from helm? does this work if you install without tiller (using helm template)? Does your cluster have webhooks enabled?

**Comment by rishiraaz** [comment]
it doesnt mention any issue, when i try with helm template it takes the default values file and installs everything mentioned in that file.
Also noticed although rewriteAppHTTPProbe is true in values file it doesnt pick it up and has to be done manually

**Comment by howardjohn** [comment]
I am not sure what happened here, but I don't think we can debug further without the output from Helm. Since helm support has been dropped in Istio, I think we can close this. Sorry we didn't resolve this sooner
