### ISSUE TITLE
Add side-car/proxy spec for DeploymentConfig resource of a yaml

### ISSUE THREAD

**Issue by cmoulliard** [istio/istio#1912]
To deploy a pod on Openshift, we use the DeploymentConfig resource which is similar to Kubernetes Deployment but can be triggered when an docker image has been published within the Docker registry.

To test if we can inject the container spec about proxy_init, proxy_debug within the DeploymentConfig, I have executed this scenario and even if no errors are reported, the yaml file hasn't been enhanced

1) cd to istio install directory - 0.2.12
2) cp helloworld.yaml to helloworld-openshift.yaml
3) Change within the helloworld-openshift.yaml file "Deployment" name by "DeploymentConfig" and "apiVersion" to v1
4) Inject istio side car container spec
    ```
    istioctl kube-inject -f helloworld-openshift.yaml -o helloworld-openshift-istio.yaml
    ```
5) helloworld-openshift-istio.yaml file doesn't contain containers spec about proxy and no error is  reported excepted that this message isn't displayed when the istioctl command is executed

```
I1128 15:44:57.670877   43189 inject.go:302] Sidecar injection policy for /helloworld-v1:namespacePolicy:enabled useDefault:true inject:false status:"" required:true
```

6) We can nertheless deploy the project on openshift
```
   oc create -f helloworld-openshift-istio.yaml
   service "helloworld" created
   deploymentconfig "helloworld-dc-v1" created
   deploymentconfig "helloworld-dc-v2" created
   ingress "helloworld" created
```

Response from Jason Young

DeploymentConfig needs to be added to the list of supported GroupVersionKind (GVK) [here](https://github.com/istio/istio/blob/e36ed7b68743e2e3c9761636fedd8d6930879fad/pilot/platform/kube/inject/initializer.go#L63). The default code to locate the Pod template spec uses reflection [here](https://github.com/istio/istio/blob/e36ed7b68743e2e3c9761636fedd8d6930879fad/pilot/platform/kube/inject/inject.go#L509). 

You might need to add a special case, similar to CronJob, if Deploymentconfig doesn't follow the same structure layout as other k8s workloads.

**Comment by ayj** [comment]
Thanks for opening the issue @cmoulliard. We hope to be able to support DeploymentConfig (and any custom controller type that creates pods) through pod-level injection. This is planned as part of the upcoming change to switch to mutating webhooks for automation injection. See https://docs.google.com/document/d/1f61uHoPvozoVhlut6TG66L2XQ_DvFQWUUeFjHJeypHQ/edit#bookmark=id.r9vnshs9e4w2 for details.

**Comment by cmluciano** [comment]
related https://github.com/istio/istio/pull/1895

**Comment by cmluciano** [comment]
@ayj Anything else to do here now that #1895 is fixed ?

**Comment by ayj** [comment]
Closing now that automatic injection supports pod-level injection. 

If someone still wants `kube-inject` support on OpenShift they'll need to add support for DeploymentConfig or further generalize `kube-inject`. For example, arbitrarily accept something like a JSON pointer (RFC6901) to the pod template and return a correspond JSON patch. Alternatively, jsonnet.org be used to consume the same mesh/injection configuration templates and perform the generalized patching directly.

**Comment by mickfeech** [comment]
I issue with automatic injection is that it requires kubernetes 1.9.x and latest version of OpenShift is only running Kubernetes 1.7.x
