### ISSUE TITLE
Istio egress gateway for HTTPS_PROXY Service entry

### ISSUE THREAD

**Issue by dhineshbabuelango** [istio/istio#19129]
We are using istio in EKS. We have some pods connecting to internet, but our subnet doesn't have internet, so we decided to send the connections to a forward proxy. I used the below link to create a service entry for my forward proxy and it was working fine.

https://istio.io/docs/tasks/traffic-management/egress/http-proxy/

 Now we decided to create egress gateway for the forward proxy and below is the configuration, but still we see the connection is going out from the actual pod and not from the egress gateway.

**Service entry:**

apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: proxy
spec:
  hosts:
  - ip-10-86-2-322.us-east-1.compute.internal # ignored
  addresses:
  - 10.86.2.322/32
  ports:
  - number: 8080
    name: tcp
    protocol: TCP
  location: MESH_EXTERNAL

**Egress GW, Destination rule and virtual service.**

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - ip-10-86-2-322.us-east-1.compute.internal
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-for-checkpoint
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: checkpoint

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: direct-cnn-through-egress-gateway
spec:
  hosts:
  - ip-10-86-2-322.us-east-1.compute.internal
  gateways:
  - istio-egressgateway
  - mesh
  http:
  - match:
    - gateways:
      - mesh
      port: 80
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: checkpoint
        port:
          number: 80
      weight: 100
  - match:
    - gateways:
      - istio-egressgateway
      port: 80
    route:
    - destination:
        host: ip-10-86-2-322.us-east-1.compute.internal
        port:
          number: 80
      weight: 100

**Comment by vadimeisenbergibm** [comment]
@dhineshbabuelango So what is the protocol your client uses? Is it HTTPS? Do you define HTTPS_PROXY?

**Comment by vadimeisenbergibm** [comment]
@dhineshbabuelango Could you please specify the exact use case?
1. The protocol used by the client: HTTP/HTTPS.
1. Do you want to use a legacy proxy or an egress gateway?

To direct the traffic through an egress gateway, see https://istio.io/docs/tasks/traffic-management/egress/egress-gateway/, for both protocols.

**Comment by dhineshbabuelango** [comment]
Hi Vadim, 
1. The protocol used by the client: HTTP/HTTPS.
We are using HTTP proxy and we are injecting it as a variable inside the pod as config map like below

apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-environment-variable
data:
  HTTPS_PROXY: http://ip-10-87-2-217:8080
  NO_PROXY: 172.20.0.0/16,localhost,127.0.0.1,10.87.0.0/16,169.254.169.254,.internal,.s3.amazonaws.com

2. Do you want to use a legacy proxy or an egress gateway?
After creating the Service entry we were able to route the traffic through our legacy proxy, but we are trying to pass the traffic to legacy proxy through egress gateway. In a way we are trying to use both legacy proxy and egress gateway both. For istio mesh, egressgateway should be the single gatewaypoint for all the traffic flow

**Comment by vadimeisenbergibm** [comment]
The issue depends on https://github.com/istio/istio/issues/19295. Once it will be fixed, I will update the documentation on how to direct the traffic through the egress gateway.

**Comment by vadimeisenbergibm** [comment]
The instructions to configure the flow to the proxy through an egress gateway https://deploy-preview-6069--preliminary-istio.netlify.com/docs/tasks/traffic-management/egress/http-proxy/#optional-direct-the-traffic-to-the-external-proxy-through-an-egress-gateway.

**Comment by dhineshbabuelango** [comment]
Thanks Vadim, Its working now.
Able to send the https proxy traffic through egress gateway but could you please confirm the below

**If your remote proxy does not have a host name, create a Kubernetes ExternalName service for it:**

My remote proxy has a hostname, if I dont create the service for myproxy in istio system and update my proxy hostname instead $PROXY_HOSTNAME in all the places it is not working.

Could you please confirm if the below step is must

![image](https://user-images.githubusercontent.com/51995628/70989202-2dc6b280-20fe-11ea-820b-fc72e41c9964.png)

**Comment by vadimeisenbergibm** [comment]
@dhineshbabuelango If your proxy has a hostname, you should create a ServiceEntry for that hostname instead of step 5. Step 6 is required in both scenarios.

**Comment by dhineshbabuelango** [comment]
Thanks Vadim, I have tried this but it is not working.
 **Do I need to create a separate service entry other than below, The highlighted my-company-proxy.com is my proxy hostname**

![image](https://user-images.githubusercontent.com/51995628/71001207-c158ad00-2117-11ea-916f-3a4010a806db.png)

**Created the gw and rules like below and its not working, But it is working if I perform step 5 and use that hostname.**

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 7777
      name: tcp
      protocol: TCP
    hosts:
    - my-company-proxy.com
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-for-proxy
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: proxy
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: myproxy
spec:
  host: my-company-proxy.com
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: direct-traffic-to-proxy-through-egress-gateway
spec:
  hosts:
  - my-company-proxy.com
  gateways:
  - mesh
  - istio-egressgateway
  tcp:
  - match:
    - gateways:
      - mesh
      destinationSubnets:
      - 10.85.2.23/32
      port: 8080
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: proxy
        port:
          number: 7777
  - match:
    - gateways:
      - istio-egressgateway
      port: 7777
    route:
    - destination:
        host: my-company-proxy.com
        port:
          number: 8080
      weight: 100

**Comment by vadimeisenbergibm** [comment]
@dhineshbabuelango So can you ping `my-company-proxy.com` from inside the Kubernetes cluster?

**Comment by vadimeisenbergibm** [comment]
@dhineshbabuelango It seems in your case you should just define `PROXY_HOSTNAME` as `ip-10-87-2-217` in step 6, and skip the step 5.

**Comment by dhineshbabuelango** [comment]
@vadimeisenbergibm  my-company-proxy.com and ip-10-87-2-217 represent the same hostname. If I skip step 5 and use ip-10-87-2-217 instead of myproxy.istio-system.svc.cluster.local, its not working. The step 5 looks mandatory to me even if my Proxy IP has proxy hostname.

# curl -vv https://www.google.com
* Expire in 0 ms for 6 (transfer 0x55e6999af680)
* Uses proxy env variable NO_PROXY == '172.20.0.0/16,localhost,127.0.0.1,10.82.0.0/16,169.254.169.254'
* Uses proxy env variable HTTPS_PROXY == 'http://ip-10-87-2-217.ap-southeast-1.compute.internal:8080'

**Comment by vadimeisenbergibm** [comment]
@dhineshbabuelango I see, I will update the text to make the step mandatory.

**Comment by dhineshbabuelango** [comment]
Thanks Vadmin. Is it possible to make this connection as HTTPS connection instead of TCP connection so that I can perform mTLS between egress gateway and my proxy server

**Comment by vadimeisenbergibm** [comment]
@dhineshbabuelango The question is which traffic your proxy server expects? Can you set it to accept TLS? Or mTLS? Then you will have to update the destination rule to the proxy, to use TLS or mTLS, the one in step 7:

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: myproxy
spec:
  host: $PROXY_HOSTNAME
```

**Comment by vadimeisenbergibm** [comment]
@dhineshbabuelango Do you need any additional help with this issue? If not, could you please close it?

**Comment by dhineshbabuelango** [comment]
Thanks Vadim
