### ISSUE TITLE
istio/installer is not tagged with 1.4.x

### ISSUE THREAD

**Issue by bianpengyuan** [istio/istio#19123]
istio/installer repo does not have any 1.4.x tag: https://github.com/istio/installer/tags

Even we don't directly generate any release artifacts from this repo, we should still properly tag the repo. 

cc @howardjohn @clarketm

**Comment by howardjohn** [comment]
I think we just need to add it to the list in release-builder
release/build.sh

**Comment by clarketm** [comment]
@howardjohn 
> I think we just need to add it to the list in release-builder release/build.sh

This is simply adding `installer` to the [manifest](https://github.com/istio/release-builder/blob/3507a933c561979c05f8426ae895a1a245a20525/release/build.sh#L45) correct?

**Comment by howardjohn** [comment]
yes.

and we will need to manually tag for 1.4.0

**Comment by howardjohn** [comment]
Manually pushed a tag https://github.com/istio/installer/tags

will fix in code next
