### ISSUE TITLE
kubectl run test --rm --restart=Never -it --image=ubuntu -- echo HI    Hangs

### ISSUE THREAD

**Issue by kramvan1** [istio/istio#19124]
**Bug description**

With namespace enabled for sidecar injection, run the following kube command:
`kubectl run test --rm --restart=Never -it --image=ubuntu -- echo HI  `

This will hang forever.
This same command works in a namespace without side car injection.

**Expected behavior**

The command should run, display its output and return, then the pod should be deleted.

**Steps to reproduce the bug**

Run the cmd above.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

1.4.0
Kube 1.16

**How was Istio installed?**

Istio operator

**Environment where bug was observed (cloud vendor, OS, etc)**

IBM Cloud

**Comment by kramvan1** [comment]
cc @linsun

**Comment by howardjohn** [comment]
This is working as expected. See more info in https://github.com/istio/istio/issues/11659. Basically not much we can do here until a kubernetes change is made

**Comment by kramvan1** [comment]
@howardjohn thx for the reply, hopefully kube can do something about this.
