### ISSUE TITLE
[operator]controller if reconcile loop finishes and has errors, not attempt a retry

### ISSUE THREAD

**Issue by kramvan1** [istio/istio#19125]
**Bug description**

istio operator controller

ICP is the default profile.

The istio-system was stuck in terminating from a previous manual install of istio and bad clean resulting in the finalizer getting stuck.

Creating the ICP resource, the operator controller attempted to deploy istio, but since the namespace was in a bad state, the applies for resources in istio-sytem failed.   The reconcile loop ended.

The reconcile loop was never re-attempted.    The istio-system namespace was cleaned up forcefully, but the reconcile loop was never re-attempted.

 

**Expected behavior**

The istio operator controller should re-attempt reconcile loop after a few minutes (10?) when ANY part of the the previous reconcile loop failed.

**Steps to reproduce the bug**

This is a bit hard to reproduce, since you need to get the istio-system namespace stuck in terminating.     This can be tried with the following steps:
- from istio operator repo 

1.  deploy istio controller operator  (kubectl apply -k deploy/)
2.  deploy the demo ICP . (kubectl apply -f . deploy/crds/...cr.yaml)
3.  watch the istio control plane come up.
4.  Kill the operator forcefully. kubectl delete -k deploy/
5.  start the namespace delete which should hang now:   kubectl delete ns istio-system
6.  with the ns in terminating
7.  do steps 1-3
8. the operator will attempt the deploys, but will fail
9. the operator will never attempt a 2nd reconcile loop
10. the only way to fix this is to cleanup the namespace forcefully and then edit the ICP (add a label) to trigger a reconcile loop.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

1.4.0

**How was Istio installed?**

operator contoller

**Environment where bug was observed (cloud vendor, OS, etc)**

IBM Cloud .  kube 1.16

**Comment by morvencao** [comment]
The reason why the reconcile loop was never re-attempted, is because manifests render errors is digested in [helm reconciler](https://github.com/istio/operator/blob/master/pkg/helmreconciler/reconciler.go#L109) and only set errors in status to the ICP CR.

> The istio operator controller should re-attempt reconcile loop after a few minutes (10?) when ANY part of the the previous reconcile loop failed.

We can pass these errors to the controller so that re-attempt reconcile loop will be triggered, but I don't think it make any sense since the namespace is  in `terminating`, unless someone manually fix the `terminating` namespace.

**Comment by kramvan1** [comment]
@morvencao    The namespace will eventually  terminate, but that is just 1 reason why the reconcile could have errors.  Any type of error during the reconcile loop should basically invalidate it, so it has to be run/triggered again until it passes successfully.

**Comment by ostromart** [comment]
Normally, I believe reconcile would be reattempted, however there are some category of error/warning which only goes to console but does not result in error being returned e.g. "new resources should be created with apply". 
For sure if there's a real error we should keep retrying so let's verify if this is happening.

**Comment by sdake** [comment]
@ostromart the reconcile loop has many error conditions that don't return an error.  My suggestion would be to audit the code and fix every single one of them, or as Microsoft Press states in Code Complete "If the code is broken, replace it with a new implementation"...
