### ISSUE TITLE
upgrade uses only the global portion of config for upgrade

### ISSUE THREAD

**Issue by ostromart** [istio/istio#19135]
genOverlayICPS returns globalValues separately (btw. this is missing unvalidatedValues, which should be merged) and this is the only block which is used for ignoring diffs for upgrade warnings. 
Instead, the entire ICPS object should be used (for example if user overlays a k8s resource setting and the default changes, it should be ignored).

**Comment by elfinhe** [comment]
If we want to use ICPS to diff, the assumption is to have Istio installed with an ICPS CR applied (maybe used by the operator controller). I'd suggest that we try reading ICPS CR first and then fallback to Values in Injector's ConfigMap.

**Comment by elfinhe** [comment]
synced with Martin offline, we should use the entire ICPS objects to compare.
