### ISSUE TITLE
istio_init 1.4.0 not found

### ISSUE THREAD

**Issue by alesharik** [istio/istio#19131]
Hello! I'm trying to upgrade Istio on my kubernetes cluster to version 1.4.0, but after upgrade docker can't find auto-injected sidecar init container (`docker.io/istio/proxy_init:1.4.0`). Could you please add `proxy_init:1.4.0` image to docker registry?

**Comment by howardjohn** [comment]
This is working as intended, we removed this image. You should use `proxyv2` as our installation does

**Comment by alesharik** [comment]
Sorry to bother you, I have my values.yaml messed up. Thanks!
