### ISSUE TITLE
Autoscaling in Istio using horizontal pod autoscaler

### ISSUE THREAD

**Issue by kahootali** [istio/istio#1914]
I am using Manual SideCar for Istio and I want to use autoscale pods based on resource usage. I have specified resource usage in my yaml file.
```
        resources:
          requests:
            cpu: 250m    
```
But when I run command` istioctl kube-inject -f file.yaml`
I get
```
        ....
        name: istio-proxy
        resources: {}
        ....
```
It adds istio-proxy. But it doesn't add resources to the istio-proxy container. So I am unable to see targets of the pod using horizontal pod autoscaler. When I run 
`kubectl get hpa`
I get 
```
NAMESPACE          NAME              REFERENCE                           TARGETS           MINPODS   MAXPODS   REPLICAS   AGE
default            svc_autoscaler   Deployment/deploy              <unknown> / 70%             1         10        3          9m
```
And it doesn't get a value of target, so how can I specify a resources value at runtime

**Comment by ayj** [comment]
Resource request and limits are per-container. `istioctl kube-inject` currently doesn't support inherit the istio-proxy container resources from the app container. Support for fully customizable injection is being worked on. See https://docs.google.com/document/d/1f61uHoPvozoVhlut6TG66L2XQ_DvFQWUUeFjHJeypHQ/edit#bookmark=id.73bjwkr0nfgr for the template design.

**Comment by kahootali** [comment]
So isn't there any way that I could set any resource value for istio-proxy container. 
And how is it being done in this [example](https://istio.io/blog/canary-deployments-using-istio.html)?

**Comment by ayj** [comment]
No, no without making code changes to istioctl. 

I'm not sure how this is working in the [example](https://istio.io/blog/canary-deployments-using-istio.html). @frankbu, I think you worked on this blog entry?

**Comment by frankbu** [comment]
The workaround (as used in the [example](https://istio.io/blog/canary-deployments-using-istio.html)) is to run kube-inject first and then manually edit the yaml file before applying it:
https://github.com/istio/istio/tree/master/samples/helloworld#start-the-services

**Comment by kahootali** [comment]
A better workaround that I used is after applying the yaml file 
`kubectl apply -f <(istioctl kube-inject -f fileName.yaml)`

You can set the resources through: 
`kubectl set resources deployment <dep-name> -c=istio-proxy --requests=cpu=100m`

**Comment by costinm** [comment]
Adding a tentative 0.6 milestone - the template-based injection is making progress, and it seems a good place to add the resources and any other customization.

**Comment by ayj** [comment]
Similar to https://github.com/istio/istio/issues/2864. Closing this issue so we can track in one issue.
