### ISSUE TITLE
Update manifest migrate command to go from istio/istio helm values.yaml to new IstioOperatorSpec

### ISSUE THREAD

**Issue by ostromart** [istio/istio#19149]
The main task for 1.5 will be to migrate helm users to new operator API (WIP in https://github.com/istio/api/pull/1177). Most of the work will probably be on the destination schema side, as istio/istio values.yaml should be very close or the same as istio/installer. But this also needs to be verified.

**Comment by richardwxn** [comment]
change merged: https://github.com/istio/istio/pull/20542
