### ISSUE TITLE
Integrate telemetry  v2 and make any required API changes

### ISSUE THREAD

**Issue by ostromart** [istio/istio#19148]
Users should be able to select mixer v1 or telemetry v2. This issue also covers any new API required for v2.

**Comment by richardwxn** [comment]
Related templates were added in installer, the pending change is to move the setting part from values pass through to the new IstioOperator API

**Comment by richardwxn** [comment]
installer PR: https://github.com/istio/installer/pull/590
operator PR: https://github.com/istio/operator/pull/670
Need to update istio.io docs for new instruction as well(pending)

**Comment by howardjohn** [comment]
done
