### ISSUE TITLE
Dual control plane traffic steering design

### ISSUE THREAD

**Issue by ostromart** [istio/istio#19151]
Design doc is required to figure out how to coordinate traffic between multiple flavors of a control plane. This should discuss such issues as whether a single controller should handle multiple operator CRs.

**Comment by sdake** [comment]
@ostromart @richardwxn can you start with an RFC first so we are all on the same page about requirements?

Cheers
-steve

**Comment by howardjohn** [comment]
ref https://docs.google.com/document/d/1d1z5PC8wvh9QiR3NesAaPm6w2HnE4-KIfjB7GB-_Wf8/
