### ISSUE TITLE
envoy_cluster_client_ssl_socket_factory_ssl_context_update_by_sds creates too many time series

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#19166]
Time series usage in my cluster:

Metric | Number of Series
-- | --
istio_mcp_message_sizes_bytes_bucket{} | 163557
istio_response_bytes_bucket{} | 73200
istio_request_bytes_bucket{} | 73200
istio_request_duration_milliseconds_bucket{} | 59700
envoy_cluster_client_ssl_socket_factory_ssl_context_update_by_sds{} | 30590
istio_request_duration_seconds_bucket{} | 16200
container_memory_failures_total{} | 14088
envoy_cluster_upstream_cx_connect_ms_bucket{} | 13000
envoy_cluster_upstream_cx_length_ms_bucket{} | 13000
envoy_server_initialization_time_ms_bucket{} | 12780

envoy_cluster_client_ssl_socket_factory_ssl_context_update_by_sds is one of the most expensive stats, and its literally useless in my cluster -- I have no SDS, so its always 0

cc @douglas-reid @mandarjog

**Comment by mandarjog** [comment]
istio_mcp_message_sizes_bytes Is even worse.
@douglas-reid we should check if we really need granular buckets.

**Comment by howardjohn** [comment]
I figured this out in https://github.com/istio/istio/issues/19165 which was about galley and spun this one out into its own issue. Yeah galley is way worse.

Its not about the buckets as much as it is about having an unbounded label for each mcp connection

**Comment by douglas-reid** [comment]
Are any of the dashboards using `mcp` metrics at all?  I think a re-think of the per-component monitoring is definitely a top priority for 1.5.x, especially as `istiod` picks up momentum.

**Comment by howardjohn** [comment]
There is a galley dashboard with some metrics, not sure if that's all of them. I don't think size is on there which is the largest. And they don't query by connection id which is the biggest cardinality issue because it is unbounded.

Agree we should do a larger clean up as well

**Comment by mandarjog** [comment]
@douglas-reid we should do a sweep of all unbounded metrics. Any metric with “instance” label has this problem as stono has complained. There are some pre-aggregation and federation mitigations, but the response from the Prometheus was “live with it, this is how Prometheus works!”

**Comment by howardjohn** [comment]
Should we scrape with `used_only` parameter on envoy so we don't get empty metrics like this?

**Comment by JimmyCYJ** [comment]
@howardjohn would you mind to explain what are the time series for metrics? Does ```used_only``` help to remove time series for unused metrics?

**Comment by howardjohn** [comment]
Each unique metric (the metric name and labels) creates a new time series (eg database entry). So we have this time series created for every single cluster for every single pod. `used_only` is a parameter to the envoy /stats endpoint, which I think might help here, but I haven't tested

**Comment by JimmyCYJ** [comment]
@howardjohn thanks! We are planning to turn SDS on by default in 1.5, and the metrics would be used by default as well.

**Comment by howardjohn** [comment]
This metric is N^2, since its recorded for every pod for every cluster. This is not sustainable for a large cluster. I recommend we remove this metric, unless we can move SDS to the same model as XDS, where there is a single cluster instead of inlined config in every cluster

**Comment by douglas-reid** [comment]
@howardjohn did this ever get resolved ?

**Comment by howardjohn** [comment]
No its still just as bad. Heres a snapshot from master


Name | Count
-- | --
envoy_cluster_client_ssl_socket_factory_ssl_context_update_by_sds | 272768
istio_response_bytes_bucket | 269540
istio_request_duration_milliseconds_bucket | 269540
istio_request_bytes_bucket | 269520
envoy_cluster_upstream_cx_length_ms_bucket | 48120
envoy_server_initialization_time_ms_bucket | 48120
envoy_cluster_upstream_cx_connect_ms_bucket | 48120
container_memory_failures_total | 46168
istio_request_duration_milliseconds_count | 13477
istio_requests_total | 13477

**Comment by douglas-reid** [comment]
@JimmyCYJ any thoughts here?

**Comment by myidpt** [comment]
Conclusion on WG: Disable by default, and turn it on when we debug.

**Comment by JimmyCYJ** [comment]
From offline discussion with @douglas-reid one option to turn off the SDS stats is to use 
sidecar.istio.io/statsInclusionPrefixes and include all stats we need except stats with suffix "ssl_context_update_by_sds". Put this list into https://github.com/istio/istio/blob/master/tools/packaging/common/envoy_bootstrap_v2.json#L184-L210 and follow this link to test it https://istio.io/docs/ops/configuration/telemetry/envoy-stats/.

The SDS stats was introduced back in https://github.com/istio/istio/pull/15266, parts of the code still exist https://github.com/istio/istio/blob/f705cdbb78b56cd87ee011068b6d8690f95fa3c0/pkg/bootstrap/config.go#L54, maybe another option is to rollback that change and check if the issue is solved.

**Comment by myidpt** [comment]
I think we still want to keep the feature since it's still useful, just not enable it by default?

**Comment by JimmyCYJ** [comment]
We can enable it by doing this. https://github.com/istio/istio/wiki/Envoy-native-telemetry#sidecar
