### ISSUE TITLE
Galley CPU leak, metrics are 25mb/day

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#19165]
![2019-23-11_07-29-47](https://user-images.githubusercontent.com/623453/69481109-0c0a3200-0dc3-11ea-93e3-affe395d2a01.png)

over a 24hr window

Its now at ~100m baseline, but after I had it running for a week it was at 700m, as can be seen in the far end of the graph before I restarted it.

**Comment by howardjohn** [comment]
The same can be seen for mixer-policy, suggesting something to do with kube crds

**Comment by howardjohn** [comment]
Its the metrics. After just 1 day of running `/metrics` returns 26mb!

**Comment by howardjohn** [comment]
If I look at most expensive metrics with `topk(10, count by (__name__)({__name__=~".+"}))`

Metric|Number of Series
-- | --
istio_mcp_message_sizes_bytes_bucket{} | 163557
istio_response_bytes_bucket{} | 73200
istio_request_bytes_bucket{} | 73200
istio_request_duration_milliseconds_bucket{} | 59700
envoy_cluster_client_ssl_socket_factory_ssl_context_update_by_sds{} | 30590
istio_request_duration_seconds_bucket{} | 16200
container_memory_failures_total{} | 14088
envoy_cluster_upstream_cx_connect_ms_bucket{} | 13000
envoy_cluster_upstream_cx_length_ms_bucket{} | 13000
envoy_server_initialization_time_ms_bucket{} | 12780

**Comment by howardjohn** [comment]
Job|Series
-- | --
{job="galley"} | 194137
{job="kubernetes-cadvisor"} | 171092
{job="istio-telemetry"} | 59923
{job="kubelet"} | 20619
{job="svc05-0"} | 9516
{job="svc12-0"} | 9436
{job="svc03-0"} | 9382
{job="istio-ingressgateway"} | 9156
{job="svc14-0"} | 9114
{job="svc10-0"} | 9047

**Comment by wu0407** [comment]
It is like memory leak in default profile, there is only two pod  to test.
![memory with galley](https://user-images.githubusercontent.com/7602218/69613266-45b19600-106c-11ea-9cca-3a19ddf69548.png)

**Comment by howardjohn** [comment]
I think this is fixed by #19170
