### ISSUE TITLE
Existing Stackdriver tracing docs propagation info is confusing

### ISSUE THREAD

**Issue by brianwolfe** [istio/istio#19171]
**Bug description**

The existing Stackdriver tracing directions were confusing to me https://istio.io/docs/tasks/observability/distributed-tracing/overview/#trace-context-propagation

> Additionally, tracing integrations based on OpenCensus (e.g. Stackdriver) propagate the following headers:
> x-cloud-trace-context
> traceparent
> grpc-trace-bin

What actually happens is that Envoy will propagate any of the headers found. In this case, we have configured it in the order:

```
 "incoming_trace_context": ["CLOUD_TRACE_CONTEXT", "TRACE_CONTEXT", "GRPC_TRACE_BIN", "B3"],
 "outgoing_trace_context": ["CLOUD_TRACE_CONTEXT", "TRACE_CONTEXT", "GRPC_TRACE_BIN", "B3"],
```
See the [bootstrap configuration](https://github.com/istio/istio/blob/b9defec56fd417b660912426ee15bb2b6a66cede/tools/packaging/common/envoy_bootstrap_v2.json) and envoy's [extraction](https://github.com/envoyproxy/envoy/blob/c776fc3bd710d1c4a5e576144986cbff8f013bf4/source/extensions/tracers/opencensus/opencensus_tracer_impl.cc#L78-L144) and [injection](https://github.com/envoyproxy/envoy/blob/c776fc3bd710d1c4a5e576144986cbff8f013bf4/source/extensions/tracers/opencensus/opencensus_tracer_impl.cc#L192-L222) logic.

A user only needs to to propagate one of these, istio will propagate all of them when Stackdriver is enabled.

I suggest changing the wording from: 

> To do this, an application needs to collect and propagate the following headers from the incoming request to any outgoing requests:

> x-request-id
> x-b3-traceid
> x-b3-spanid
> x-b3-parentspanid
> x-b3-sampled
> x-b3-flags
> x-ot-span-context
> Additionally, tracing integrations based on OpenCensus (e.g. Stackdriver) propagate the following headers:

> x-cloud-trace-context
> traceparent
> grpc-trace-bin

To:

> To do this for Zipkin, Jaeger, and Lightstep, collect and propagate the following headers from any incoming request to any outgoing requests:

> x-request-id
> x-b3-traceid
> x-b3-spanid
> x-b3-parentspanid
> x-b3-sampled
> x-b3-flags
> x-ot-span-context
> Additionally, tracing integrations based on OpenCensus (e.g. Stackdriver) propagate the following headers:

> For Stackdriver, propagate the above headers or just `x-request-id` and any one of the following headers:
> x-cloud-trace-context
> traceparent
> grpc-trace-bin

wdyt? I can make the PR to the docs soon (waiting for CLA verification).

**Expected behavior**

I understand trace propagation behavior for Stackdriver after reading the docs.

**Steps to reproduce the bug**

Read the [distributed tracing docs](https://istio.io/docs/tasks/observability/distributed-tracing/overview/#trace-context-propagation)

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

Current.

**How was Istio installed?**

N/A

**Environment where bug was observed (cloud vendor, OS, etc)**

N/A

**Comment by gargnupur** [comment]
@brianwolfe : How does Istio know which one user is going to propagate? That's why Istio is propagating all the trace contexts..
