### ISSUE TITLE
Istio consumes too much CPU resources

### ISSUE THREAD

**Issue by zhulinwei** [istio/istio#19187]
**Bug description**
Before using istio, the tps of my service app can exceed 4000/s, after using istio, the tps drop to 2300/s, and istio-telemetry service consume more than 1 core

**Expected behavior**
Reduce istio wastage and improve my service app performance

**Steps to reproduce the bug**

1.Install istio 1.3.4
2.Deploy your service
3.Using locust to run test
4.Watching grafana dashboard

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

`istioctl version --remote` output:
```
client version: 1.3.4
control plane version: 1.3.3
```

`kubectl version` output:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.12-eks-c500e1", GitCommit:"c500e11584c323151d6ab17526d1ed7461e45b0c", GitTreeState:"clean", BuildDate:"2019-10-22T03:11:52Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
```

`helm version` output:
```
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
```
**How was Istio installed?**
Using helm

**Environment where bug was observed (cloud vendor, OS, etc)**
Amazon Linux 2

**Addition**
Grafana dashboard:
![grafana dashboard](https://raw.githubusercontent.com/zhulinwei/kubernetes/master/logging/other/images/image2019-11-25_10-34-3.png)
`grinder` is my service app,  it total consumes 1.288 cores but 0.77 cores was consumed by `istio-proxy`. Beyond that, `istio-telemery`  consumes 1.698 cores.

**Comment by howardjohn** [comment]
We are moving to a new deployment model where we remove the istio-telemetry deployment (freeing 1.7 cores in your case) and the proxy uses less (probably 0.77 -> ~0.5 cores). The primary motivation was the high cpu use you are seeing. See https://istio.io/docs/ops/telemetry/in-proxy-service-telemetry/ for more info

**Comment by zhulinwei** [comment]
@howardjohn Thanks you very much. Istio 1.4 version is still in alpha state, may I ask when will it be used in production?

**Comment by howardjohn** [comment]
This is expected to be beta by 1.5, but will depend on how much stability and performance has improved

**Comment by zhulinwei** [comment]
@howardjohn Ok, I am lookging forward to the performance of the new version and close this issue, thanks you.
