### ISSUE TITLE
operator bug right at starting

### ISSUE THREAD

**Issue by sdake** [istio/istio#19183]
**Bug description**
something isn't being proto'ed correctly.

**Expected behavior**
no display of problem.

**Steps to reproduce the bug**
Deploy Managed Istio in IKS.

first 20 lines of logs...

```
2019-11-24T22:11:52.060245Z     info    Reconciling IstioControlPlane
proto: tag has too few fields: "-"
2019-11-24T22:11:52.094644Z     error   json: cannot unmarshal string into Go value of type map[string]json.RawMessage
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.4.0

**How was Istio installed?**
standalone operator 1.4.0 with ICP

**Environment where bug was observed (cloud vendor, OS, etc)**
IKS + Istio 1.4.0.

**Comment by ostromart** [comment]
This is a side effect due to the structs being generated through protoc (specifically it's due to hidden fields being present). It's harmless and there's no easy way to get rid of this except for hacking the generated structs.
