### ISSUE TITLE
operator is not processing a key/value pair

### ISSUE THREAD

**Issue by sdake** [istio/istio#19181]
**Bug description**
it appears the operator is not processing a KV pair.

**Expected behavior**
Key value pair would not be present in the generated manifest.

**Steps to reproduce the bug**
Install operator with default profile:
```
Stevens-MacBook-Pro-2:~ sdake$ grep "if" operator-log
2019-11-24T22:12:01.823981Z     info    Manifest after resources and overlay: 
            tls_certificates:
            - certificate_chain:
              verify_subject_alt_name:
              - spiffe://cluster.local/ns/istio-system/sa/istio-galley-service-account
    {{- if .DisableReportCalls }}
              tls_certificates:
              - certificate_chain:
            require_client_certificate: true
    {{- if .DisableReportCalls }}
```

I don't expect to see DisableReportCalls in the generated log.  This is the only entry.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.4.0

**How was Istio installed?**
operator - with IstioControlPlane file

**Environment where bug was observed (cloud vendor, OS, etc)**
IKS

**Comment by howardjohn** [comment]
this is working as expected, that file is templated at run time

**Comment by sdake** [comment]
I see this file is a configmap - closing.
