### ISSUE TITLE
Jaeger task is nonfunctional

### ISSUE THREAD

**Issue by sdake** [istio/istio#19186]
**Bug description**
The task: https://istio.io/docs/tasks/observability/gateways/#option-2-insecure-access-http is busted.  A 503 is received when connecting to Jaeger after following the cut and paste.

**Expected behavior**
Jaeger is exported via the ingress gateway as specified in the documentation.

**Steps to reproduce the bug**
Follow steps.
kubectl get svc -n istio-system

Open web browser to istio-ingressgateway:15032 as per screenshot - 503 occurs instead of the display of Jaeger.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
Istio 1.4.0, K8s 1.16.3

**How was Istio installed?**
standalone operator

**Environment where bug was observed (cloud vendor, OS, etc)**
IBM Cloud

Prometheus and Grafana work properly.  Jaeger produces a 503.  with `istioctl dashboard` - output from jaeger can be had.

**Comment by objectiser** [comment]
Sounds like the same issue as https://github.com/istio/istio/issues/19021 ?

**Comment by sdake** [comment]
@objectiser #19021  has a similar profile although the task does not use the `ictioctl dashboard` commands - instead, a gateway/vs are installed.  Using `istioctl dashboard jaeger` works in this scenario (with 1.4.0) while usage of Istio traffic management does not.

I did see the change on the port fly by in a prior install build and thought it looked errant...:

```
tracing                  ClusterIP      172.21.58.2      <none>           9411/TCP                                                                                                                     7h35m
zipkin                   ClusterIP      172.21.49.0      <none>           9411/TCP                                                                                                                     7h35m
```

Cheers
-steve

**Comment by objectiser** [comment]
According to the [Operator architecture intro](https://github.com/istio/operator/blob/master/ARCHITECTURE.md#introduction), it uses the [istio.io/installer](https://github.com/istio/installer) helm charts. Therefore the fix https://github.com/istio/installer/pull/563 I applied will be picked up next release. There is also a patch to the 1.4 branch - but not sure when/if that will be released, and whether the operator will be re-released with it.

**Comment by sdake** [comment]
This bug is fixed in master and the backport repos.

The operator for 1.4.1/1.4.2 will be re-released with the changes. I think it is safe to close this bug now, unless someone desires to keep it open until the release has occurred and this issue can be verified resolved.
