### ISSUE TITLE
Use ProxyMatch for v2 telemetry Envoyfilter

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#19185]
https://istio.io/docs/reference/config/networking/envoy-filter/#EnvoyFilter-EnvoyConfigObjectMatch

Supports proxyMatch that can match on proxy version specified by the ISTIO_VERSION env var.

Update all instances of EnvoyFilter API to use proxy version match. Proxy match supports regex for now.

@rshriram Can we support semver here? We had discussed it before, but it would be very useful here.

**Comment by mandarjog** [comment]
@richardwxn to the extent I have tried to use `proxyVersion: 1.4.0.*` it has not been working.

**Comment by howardjohn** [comment]
the release images should have version 1.4.0. Dev builds will look like 1.5-dev.sha

**Comment by richardwxn** [comment]
in the recent merged envoyfilters for 1.4 and master, we used different envoyfilters for different version and hardcoded the proxyMatch version part correspondingly.
