### ISSUE TITLE
Outbound TCP connections reset on config update

### ISSUE THREAD

**Issue by bhicks329** [istio/istio#19198]
When an envoy sidecar receives an update it resets outbound connections to a websockets endpoint. 

Config should be applied silently and not effect the existing connections

Restart any pod in the cluster that forces an update of configuration or restart pilot.

istioctl version --remote
client version: 1.4.0
control plane version: 1.4.0
data plane version: 1.4.0 (22 proxies)

kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:42:50Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"1da9875156ba0ad48e7d09a5d00e41489507f592", GitTreeState:"clean", BuildDate:"2019-11-14T05:19:20Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

Istio installed via istioctl manifest and Helm template - Confirmed the same  in 1.2.5, 1.3.5 and 1.4

Azure AKS - LInux

**Comment by howardjohn** [comment]
> Restart any pod in the cluster that forces an update of configuration or restart pilot.

So to be clear, you have some Service A calling some Service B, and an unrelated service C restarts, and the connection from A -> B is reset?

Generally the only time a reset should happen is when a listener is changed. This happens only when some configs are changed like RBAC, things like new pods and VirtualServices, etc should have no impact. There have been some issues in the past where we accidentally change the listener due to nondeterministic config though which may be the case here

**Comment by bhicks329** [comment]
The service is external to the cluster and this service.

The application makes a https outbound connection however when the config
on the mesh updates, these connections are dropped. I’ve tried every
version of istio to 1.4 with all sorts of config including egress gateways
and I juts can’t get the connection to stay. One thing that is strange is
that if I have a pod outside the mesh restart, it triggers an istio update
as well. I’m assuming this is some sort of update to Azure CNI.

-Ben

From: John Howard <notifications@github.com> <notifications@github.com>
Reply: istio/istio
<reply@reply.github.com>
<reply@reply.github.com>
Date: 25 November 2019 at 18:56:18
To: istio/istio <istio@noreply.github.com> <istio@noreply.github.com>
CC: Ben Hicks <bhicks329@gmail.com> <bhicks329@gmail.com>, Author
<author@noreply.github.com> <author@noreply.github.com>
Subject:  Re: [istio/istio] Outbound TCP connections reset on config update
(#19198)

Restart any pod in the cluster that forces an update of configuration or

**Comment by bhicks329** [comment]
Apologies, just to be clear the service in cluster is making a connection to a https endpoint outside of the cluster. This service, only makes outbound connections and does not server any traffic itself.

**Comment by howardjohn** [comment]
> One thing that is strange is that if I have a pod outside the mesh restart, it triggers an istio update as well

This sounds normal, we send config about pods that are not injected with a sidecar ( I assume this is what you mean by "outside the mesh" - just to verify), so we can load balance to them. 

But these changes should just be endpoint updates which shouldn't impact existing connections.

Any chance you could get a config dump before and after an event that drops the connection? See https://github.com/istio/istio/wiki/Troubleshooting-Istio#collecting-information-2

Then we can hopefully see if something is changing that triggers the connection to drop

**Comment by bhicks329** [comment]
I've taken another look and checked over the config and there wasn't anything obvious changing (I can't post it here unfortunately) 

The app itself is deployed a number of times (not replica-sets - don't ask) and doesn't have an inbound port yet a k8s service for each one had been created of type: LoadBalancer. I've just removed the services as it didn't make sense for them to be there. This appears to have resolved the issue. I'm pretty sure in the past you needed some form of service for Envoy to start.

I would be grateful if you could help me understand this behaviour?

**Comment by bhicks329** [comment]
So interestingly, this app had a k8s service attached yet the container doesn't have any open ports, I've removed the service and it seems to be working as expected now. I believe it was put there originally as envoy wouldn't start without some for of open port / service 

I'm struggling to understand why this may have such an effect? What would happen if the service had both ingress and ingress connections?

**Comment by bhicks329** [comment]
Appreciate all your help btw 👍
