### ISSUE TITLE
helm template unknown flag: --name error: no objects passed to apply

### ISSUE THREAD

**Issue by illidan80** [istio/istio#19193]
Helm 3 missing template "--name" flag. 

Using instructions from [https://istio.io/docs/setup/install/helm/](https://istio.io/docs/setup/install/helm/)

> helm install install/kubernetes/helm/istio-init --name istio-init --namespace istio-system

Causing to helm error:

> unknown flag: --name error: no objects passed to apply

**Comment by howardjohn** [comment]
We do not support helm 3 yet, as it came out after our latest istio version. Please use helm 2.x
