### ISSUE TITLE
Using istioctl to generate manifests causes duplicate value

### ISSUE THREAD

**Issue by thecodejunkie** [istio/istio#19190]
**Bug description**
When using `Istioctl` to generate manifest, then the `Base\Telemetry\Telemetry.yaml` contains duplicate values in the `istioproxy` attributemanifest. There are two entries for `context.proxy_version`. This causes problems with some of our tooling since we parse the YAML which leads to a duplicate key error.

**Expected behavior**

No duplicate keys should be generated

**Steps to reproduce the bug**

Generate manifests and check for `grep context.proxy_version`

```
istioctl manifest generate | grep context.proxy_version
```

This produces two entries for me and looking in the file I can see two entries that look like

```
context.proxy_version:
  valueType: STRING
```

They are on lines 173 and 207

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.4.0

**How was Istio installed?**

```
curl -L https://istio.io/downloadIstio | sh -
```

**Environment where bug was observed (cloud vendor, OS, etc)**
macOS Catalina

**Comment by howardjohn** [comment]
Thanks, we just fixed this a couple days ago: https://github.com/istio/installer/pull/565

This will be in 1.4.1 which we are hoping to release in the next week or 2

**Comment by howardjohn** [comment]
Closing as this is fixed
