### ISSUE TITLE
istioctl --set doesn't support escaping strings

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#19196]
Background: https://github.com/istio/istio/pull/17334

> I can't for the life of me figure out the syntax for passing in values to the sidecarInjectorWebhook.injectedAnnotations parameter, to set the apparmor annotation slightly_smiling_faceMy issue is that the "key" part contains dot-notation so it attempts to split it up no matter how I try to encapsulate it
> 
> Using Helm I think the proper way is to encapsulate it in quotes and escape dots
> ```
> istioctl manifest generate \
>     --set cni.enabled=true \
>     --set values.sidecarInjectorWebhook.injectedAnnotations."container\.apparmor\.security\.beta\.kubernetes\.io/istio-proxy"=runtime/default \
>     --output ./generated
> ```
> However this results in a mess in the actual manifest
> ```
> injectedAnnotations:
>   "container\": "map[apparmor\:map[security\:map[beta\:map[kubernetes\:map[io/istio-proxy:runtime/default]]]]]"
> Doesn't matter if I try to escape the dots or not
> ```
> Thanks!

> 
> adding complex stuff like this is really painful with helm --set and may not even be possible with istioctl.. I am not sure. What I would recommend is just to use a file. This will work:
> ```
> ik manifest generate -f <(echo 'apiVersion: install.istio.io/v1alpha2
> kind: IstioControlPlane
> spec:
>   values:
>     sidecarInjectorWebhook:
>       injectedAnnotations:
>         container.apparmor.security.beta.kubernetes.io/istio-proxy: runtime/default')
> ```

**Comment by ostromart** [comment]
I feel like this is one where we should just document the limitations of --set rather than sinking effort into improving it - we really want to discourage its use except for experimenting.

**Comment by esnible** [comment]
Related: https://github.com/istio/istio/pull/20631 https://github.com/istio/istio/issues/20683

**Comment by esnible** [comment]
This code all lives under https://github.com/istio/istio/blob/master/operator/pkg/util/path.go#L41 through :53.

Is there consensus on what an escaped string would look like?
- Both double quotes and escaped periods `--set values.sidecarInjectorWebhook.injectedAnnotations."container\.apparmor\.security\.beta\.kubernetes\.io/istio-proxy"=runtime/default`
- Double quotes `--set values.sidecarInjectorWebhook.injectedAnnotations."container.apparmor.security.beta.kubernetes.io/istio-proxy"=runtime/default`
- Escaped periods `--set values.sidecarInjectorWebhook.injectedAnnotations.container\.apparmor\.security\.beta\.kubernetes\.io/istio-proxy=runtime/default`
- Other (single quotes, backticks, `&#46` for periods; etc)


@istio/wg-docs-maintainers This change will affect the docs.  If you have an opinion about the format of escaped path names and `--set` please let me know.

**Comment by ostromart** [comment]
i vote for option 3 (escaped periods). i'm not sure if quotes will survive being passed through a go flag without an additional ' and in any case the path has a special syntax for . so adding quotes into the mix could be confusing to users.

**Comment by ostromart** [comment]
as an aside, i agree that we should be discouraging the use of --set in general for anything as complex as this.

**Comment by esnible** [comment]
@ostromart I agree we should discourage use of `--set` for anything that is easy to screw up with a typo.

Can anyone on the @istio/wg-docs-maintainers comment on the style Howard suggests?  The [Helm instructions](https://istio.io/docs/reference/config/installation-options/), and [here](https://istio.io/blog/2018/aws-nlb/) are filled up with slices and maps that can be set.  We have istioctl set options [here](https://istio.io/docs/reference/config/istio.operator.v1alpha12.pb/#k8s-io-api-core-v1-Affinity).

Do we want users using "bash-isms" and yaml, like below, or `--set`?  It seems easy to screw up both of them.

```
istioctl manifest generate -f <(echo 'apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  values:
    sidecarInjectorWebhook:
      injectedAnnotations:
        container.apparmor.security.beta.kubernetes.io/istio-proxy: runtime/default')
```

**Comment by ayj** [comment]
The following would also work if `istioctl manifest generate` accepted input from STDIN like kubectl.

```bash
cat << EOF | istioctl manifest generate -f -
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  values:
    sidecarInjectorWebhook:
      injectedAnnotations:
        container.apparmor.security.beta.kubernetes.io/istio-proxy: runtime/default
EOF

**Comment by towens** [comment]
🖤this. This is key to moving away from installing/customizing Istio with helm. All our installs presently use an `override.yaml` to provision network load balancers.
