### ISSUE TITLE
Analysis for RBAC Service to Service auth with mTLS turned off

### ISSUE THREAD

**Issue by esnible** [istio/istio#19197]
This tricky "gotcha" was the topic of a KubeCon talk by @mt-inside of Tetrate.  https://youtu.be/Rc_MM99wbYo

The problem is explained at the end https://youtu.be/Rc_MM99wbYo?t=1768

Earlier in the talk Matt highlights `istioctl x analyze` not working for this problem: https://www.youtube.com/watch?v=Rc_MM99wbYo

**Comment by sushicw** [comment]
This relates to https://github.com/istio/istio/issues/17687

**Comment by mt-inside** [comment]
Hey @esnible ! Thanks for posting the link to the talk; I wouldn't have seen this issue.

In Istio's defence, it is possible to enable RBAC using principles that aren't the caller's SA, so this isn't /strictly/ wrong. I'd say it's by far the most common setup though so at least a warning would be good.
