### ISSUE TITLE
Unbounded cardinality with ReplicaSets

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#19218]
A customer uses ReplicaSets directly instead of using a Deployment resource. We are not handling ReplicaSet resource correctly, so the source_workload_name degenerates to pod name.

example: 
``` yaml
replicaset: productsvc-latestmaster-v001
pod: productsvc-latestmaster-v001-srk29
```
Normally `source_workload_name == productsvc-latestmaster-v001` , however in this case we are seeing the name of the pod.
so
```yaml
source_workload_name: productsvc-latestmaster-v001-srk29
source_workload_namespace:  product-ns
```

This may affect telemetry v2 as well as Mixer.

**Comment by mandarjog** [comment]
If @douglas-reid cannot get to this, @carolynhu please take over the issue.

**Comment by mandarjog** [comment]
@bianpengyuan cc

**Comment by douglas-reid** [comment]
Are you sure you are seeing pod names in the data?  The code in `kubenetesenv` should be pulling from root controller name.  Code in question: https://sourcegraph.com/github.com/istio/istio@master/-/blob/mixer/adapter/kubernetesenv/cache.go#L138

**Comment by douglas-reid** [comment]
We even have a test for this logic (albeit for `ReplicationController`):

https://sourcegraph.com/github.com/istio/istio@master/-/blob/mixer/adapter/kubernetesenv/cache_test.go#L103-118

**Comment by bianpengyuan** [comment]
This is from user's config, where they uses `destination.name` and `source.name` for workload label. I think this issue could be closed now.
