### ISSUE TITLE
Istio 1.4.0 templated manifest contains creationTimestamp

### ISSUE THREAD

**Issue by Stono** [istio/istio#19224]
**Bug description**
I've noticed in the templated yaml for istio 1.4.0, a bunch of manifests contain a `creationTimestamp ` field, and they probably shouldn't.

<img width="370" alt="Screen Shot 2019-11-26 at 12 05 33" src="https://user-images.githubusercontent.com/1486729/69630800-2d7a5080-1045-11ea-8fa7-6757604bb26d.png">

**Expected behavior**
creationTimestamp should be added by the server not part of these manifests

**Steps to reproduce the bug**
helm template 1.4.0

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.4.0

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by jasonwzm** [comment]
We use direct transformation from CustomResourceDefinition object to yaml in CRD generation (which is the same approach used in kubebuilder). @Stono did it cause validation error on your side?
Anyhow, I will create a patch for this.
