### ISSUE TITLE
Istio 1.4.0 templated manifest CRDs contain a status field

### ISSUE THREAD

**Issue by Stono** [istio/istio#19225]
**Bug description**
Similar to https://github.com/istio/istio/issues/19224, the status field should be added by the server not in the manifests:

<img width="316" alt="Screen Shot 2019-11-26 at 12 13 17" src="https://user-images.githubusercontent.com/1486729/69631911-53ecbb80-1046-11ea-9ec5-f2b33c4787e2.png">

**Expected behavior**
Status field to be added by the server

**Steps to reproduce the bug**
Template 1.4.0

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by thecodejunkie** [comment]
I also ran into this and it does not play well with the Anthos Config Management validation rules and causes https://cloud.google.com/anthos-config-management/docs/reference/errors#knv1045 to be reported
