### ISSUE TITLE
Document HorizontalPodAutoscaling using Latency as Custom Metrics

### ISSUE THREAD

**Issue by pc-rshetty** [istio/istio#19221]
**Bug description**
I know we have Metrics available in Istio . This might includes latency.  What i am trying to do is configure my HPA to scale according to the latency metrics available in istio. Now i believe i need to write query the Prometheus service installed as part of isito. But the complete solution is not documented . There are multiple solutions people have published and with isito release cadence improving i am not sure if they are still valid or not. My use case is simple 
I have installed Istio with Prometheus and telemetry and would like to get some examples to scale as per my http service's latency. Example if latency >2 seconds then autoscale.  

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**
Helm chart

**Environment where bug was observed (cloud vendor, OS, etc)**
EKS

**Comment by pc-rshetty** [comment]
thanks @howardjohn since you added the label as enhancement does it mean this is not possible or just documentation is missing

**Comment by howardjohn** [comment]
> There are multiple solutions people have published 

Based on this I assume its possible and just not documented on our site

**Comment by pc-rshetty** [comment]
So i read these 2 
https://medium.com/google-cloud/kubernetes-autoscaling-with-istio-metrics-76442253a45a
https://medium.com/cloudzone/autoscaling-kubernetes-workloads-with-istio-metrics-92f86baabba9


Still researching ...

**Comment by Arnold1** [comment]
@pc-rshetty any progress? can you share details?
