### ISSUE TITLE
Istio 1.4.0 proxy and proxy_init variables

### ISSUE THREAD

**Issue by Stono** [istio/istio#19235]
**Bug description**
In `1.4.0` istio-init was changed to use the same image as istio proxy, therefore you could infer that setting `global.proxy.image` would change the `image:` for both `istio-init` and `proxy`, however it doesn't. 

In order to use my custom proxy image I had to set two variables:

 - `global.proxy.image` 
 - `global.proxy_init.image`

which was a little counter intuitive.

**Expected behavior**
Setting `global.proxy.image` should set the image for both `proxy` and `init`, unless `global.proxy_init.image` is specified too, which would override it for the init container

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.4.0

**How was Istio installed?**
Helm

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
The motivation for this was that someone might want to use a different image for the two? Not sure there is any real use case for this though

**Comment by Stono** [comment]
Yup and my proposal still accommodates that, `global.proxy.image` is used by default on both but you can override just the init image with `global.proxy_init.image`

**Comment by howardjohn** [comment]
Ah right, I missed that. :+1:
