### ISSUE TITLE
Missing metric galley_istio_networking_virtualservices

### ISSUE THREAD

**Issue by mahendrakariya** [istio/istio#19233]
**Bug description**

The metric `galley_istio_networking_virtualservices` is missing from prometheus.

**Expected behavior**
The above metric should be present.

**Steps to reproduce the bug**
  * Install Istio through Helm.
  * Deploy Bookinfo app.
  * Check for presence of metric in prometheus.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
Istio 1.4.0
Kube 1.14.
Helm 2.14.3

**How was Istio installed?**
Through Helm

**Environment where bug was observed (cloud vendor, OS, etc)**
Cloud (AWS)

**Comment by jwendell** [comment]
This metric is not present on installer charts. Is this a leftover in istio/istio helm charts?
cc @ostromart @howardjohn

**Comment by douglas-reid** [comment]
@jwendell the metric is not controlled by helm.

@mahendrakariya did you add any virtual services to your cluster?

**Comment by mahendrakariya** [comment]
No. We don't have any virtual services yet. Will this metric show up only when we have some virtual services?

**Comment by douglas-reid** [comment]
Yes.  I believe the logic for galley collections only reports on them when they exist.

Closing for now. Please feel free to reopen if you see this behavior after you've added virtual services.

**Comment by mahendrakariya** [comment]
OK cool. Thanks for this.
