### ISSUE TITLE
Handle multiple JWT rules with the same issuer

### ISSUE THREAD

**Issue by diemtvu** [istio/istio#19245]
We need to define how multiple JWT rules with the same issuer (assuming they are slightly different, e.g in `audiences` spec or location) will be handled. Here are few options, but not limited to:

1. Use as is, each rule is treated independently. Might need some change in JWT filter to support different `providers`.
2. Combine into a single rule, where locations, audiences are union.
3. Combine into a single rule, where locations, audiences are intersected.
4. Does not support, the behavior is undefined (one of the rule will be use arbitrary).

This is part of https://github.com/istio/istio/issues/19084

**Additional context**

**Comment by F7502** [comment]
@diemtvu 
I have a question about the current behavior, hope this is the right place to ask:
> Use as is, each rule is treated independently.

What exactly does it mean? If I have two rules for the same issuer but each one is different (e.g. different JWKS or different audiences), which one will be used? The first one? Or all of them and when one succeeds then the request is assumed to be authenticated? Thx in advance :-)
