### ISSUE TITLE
Update Pilot to v1alpha3 routing API

### ISSUE THREAD

**Issue by ijsnellf** [istio/istio#1925]
Update Pilot to use the v1alpha2 version of the routing API being discussed here: https://github.com/istio/api/pull/254. 

The plan is to first add functionality to support v1alpha1 and v1alpha2 together, then remove v1alpha1 after we are comfortable with the new API.

**Comment by rshriram** [comment]
rough list of things that need to be done:
1. match becomes array of matches with OR semanitcs across matches
2. Need to honor port in top level host (match)
3. Need to add port under the route section, allowing forwarding of traffic to a different port (cc @diemtvu in case you want to track this)
4. Need to get rid of namespace dependency and convert to just name/domains.. where namespace must be inferred based on the namespace of service using the rule.

(will add more as I carve out things)

**Comment by rshriram** [comment]
fyi @kyessenov / @ZackButcher .. Lets track the key things here.

**Comment by ZackButcher** [comment]
I already have a branch implementing Gateway validation which I'll submit in a PR as soon as the PR in istio/api is merged.

I was starting to flesh out the code to generate listeners from Gateways, but it's just exploratory (so it someone else wants to take that on, be my guest).

**Comment by kyessenov** [comment]
Don't mix Gateway with RouteRule++. I don't think route rule is close to
ready, but gateway maybe.

**Comment by kyessenov** [comment]
Additionally, xDS v2 will make all the new config generation out-of-date.
Perhaps, you should start with protos and convert them to JSON?

**Comment by ZackButcher** [comment]
We must, since current route rules cannot bind to gateways. I don't think we can make Gateway work as-is without routerule++. Shriram is even implementing them in the same PR atm.

**Comment by kyessenov** [comment]
This is not acceptable to sneak it a major config change due to gateway need :)

**Comment by ijsnellf** [comment]
> Additionally, xDS v2 will make all the new config generation out-of-date.
Good point. otoh, we want to avoid going too big-bang.

**Comment by ZackButcher** [comment]
We're not sneaking in anything, they're all right there in github, as part of the v1alpha2 API.

**Comment by ZackButcher** [comment]
And if you want ingress in the v1alpha1 API world, IngressRoute is still there and usable, as is our support for k8s ingress resources.

**Comment by kyessenov** [comment]
How do you combine v1alpha2 route rule with ingress rule from v1alpha1?
Route rules are affecting everything, not just gateway.

**Comment by ZackButcher** [comment]
That's part of what we need to figure out when we implement all of this stuff.

**Comment by rshriram** [comment]
Yeah, you said that the Gateway PR makes little sense without Route Rule. so I added the Route Rule changes as well in the same Gateway PR in istio/api. And I am not sneaking in anything. I did the PTAL thingy several times :).

I do agree that the V2 thing will make the changes to config.go (for routerules++) kind of difficult to reconcile. That would mean that the Jsonnet thing has to go in as well.. But I don't think that we would completely discard config.go and friends in favor of Jsonnet. We certainly need the go level abstractions and just have to call out to JSonnet for the config generation.

**Comment by kyessenov** [comment]
I'm not in a rush in making jsonnet thingy fully work. At least I haven't been pinged by anyone that it's super important. I'm watching how the project progresses.

**Comment by ijsnellf** [comment]
CRD limitation that is forcing us to use an ugly name for route rules:
https://github.com/istio/istio/issues/2119

**Comment by andraxylia** [comment]
Can we close some of the issues in this epic? The code is there.

**Comment by rshriram** [comment]
completed..
