### ISSUE TITLE
istio/proxy can not build

### ISSUE THREAD

**Issue by AL-Cui** [istio/istio#19254]
**Bug description**
Download from https://github.com/eile/tclap/archive/tclap-1-2-1-release-final.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by bianpengyuan** [comment]
Should have been fixed master.

**Comment by AL-Cui** [comment]
> Should have been fixed in master.

I'm using version 1.4.0

**Comment by bianpengyuan** [comment]
Yeah, try fetch latest 1.4, it is also fixed there.

**Comment by AL-Cui** [comment]
> Yeah, try fetch latest 1.4, it is also fixed there.

我用的就是1.4.0的版本，然后报的这个错误，我在github上发现这个包确实没了

**Comment by bianpengyuan** [comment]
It was fixed by https://github.com/istio/proxy/commit/6ce5512ce09b760f79e33a06c2565f5974362edc, which is not in 1.4.0.

**Comment by AL-Cui** [comment]
> Yeah, try fetch latest 1.4, it is also fixed there.

I will manually modify the code and continue to try

**Comment by bianpengyuan** [comment]
Ok. Feel free to reopen, but this specific issue should have been fixed in all branches.
