### ISSUE TITLE
Auto mTLS cannot be turned off without a complete cluster restart

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#19251]
I had mTLS turned on which was causing some issues (due to a bug in a pilot I was developing). I edited mesh config, and set the flag to false.

Turns out this doesn't actually do anything, this is literally never used (unless I missed somewhere)?

We should either remove it from mesh config, or we should never look for the mtls label on pods if auto mtls is off in mesh config

Having a setting that does nothing is not really a great UX.

I marked this as a release blocker for 1.5 since I don't think its viable to ship auto mTLS on until this is fixed, but I may just be grumpy since I wasted hours debugging this

**Comment by howardjohn** [comment]
I guess the title doesn't match the description. This is really two issues:
* Mesh config does nothing
* I need to remove the label on all of the pods in my entire cluster to stop using auto mtls (I think?)

>  we should never look for the mtls label on pods if auto mtls is off in mesh config

would solve both of these I think

**Comment by incfly** [comment]
We always add labels. no need to remove labels through redeployment. (actually we always add label regardless you enable auto mTLS via helm flag or not)

The actual steps to turn it off will be update mesh config, && restart pilot. This way you should observe different behavior.

I was under the impression pilot does not respect/catch up mesh config update. But seems like not the case, at least for other features controlled by Pilot? Could you give an example?

**Comment by howardjohn** [comment]
Ok I actually realized I am wrong :slightly_smiling_face: I was looking for just direct access to `.EnableAutoMtls` but we call `GetEnableAutoMtls()` so it is actually used

**Comment by incfly** [comment]
> I had mTLS turned on which was causing some issues (due to a bug in a pilot I was developing). I edited mesh config, and set the flag to false.

Just to confirm, do you only **enable** auto mTLS and not configuring DestinationRule with "*.cluster.local" with ISTIO_MUTUAL?

Auto mTLS does not do anything if you define DR explicitly ISTIO_MUTUAL.

**Comment by howardjohn** [comment]
I was actually in a state where things were broken (not sure if its a user error, need to look at it more) and then I just modified mesh config and pilot pushed things and everything started working.

Pilot watches mesh config so no need to restart pilot
