### ISSUE TITLE
Configuring egress IP range for Google Cloud Endpoints (GCE) with istio as add-on on GKE

### ISSUE THREAD

**Issue by Svendegroote91** [istio/istio#19258]
**Bug description**
Istio is deployed as add-on on GKE and I want to open up the egress traffic so my pods can reach Google Cloud Endpoints service. However, when istio is deployed as an add-on, it is not possible to follow the guide (https://istio.io/docs/tasks/traffic-management/egress/egress-control/#direct-access-to-external-services) that shows the set the settings via the deploy config option `--set global.proxy.includeIPRanges="10.4.0.0/14\,10.7.240.0/20"`.

When trying to update the value `traffic.sidecar.istio.io/includeOutboundIPRanges` in the configmap istio-sidecar-injector via `kubectl edit cm istio-sidecar-injector -n istio-system`, the configmap gets overwritten very shortly because of managed mechanisms. One a sandbox project I managed (after a lot of trial and error) to keep this update running for some reason so there must be a workaround in which you can update this config.

Is there any procedural workaround to update the includeOutboundIPRanges when having istio installed as add-on on GKE?

I realize that this is not really a bug but more a request to enrich documentation for the istio-add-on on how you can make that work together with Google Cloud Endpoints because as I can image this will be a frequently occurring setup.

**Expected behavior**
Documentation that clarifies how you can make the istio add-on on GKE work together with Google Cloud Endpoints (configure egress traffic).

**Steps to reproduce the bug**
Deploy istio as add-on on GKE and try to edit `traffic.sidecar.istio.io/includeOutboundIPRanges` via `kubectl edit cm istio-sidecar-injector -n istio-system`. You should notice that shortly after (within a minute) this config value gets overwritten back to `*` - which blocks all egress traffic.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
**istioctl version --remote**
client version: 1.4.0
control plane version: 0f52910f512029f0f8860b4c586cf9667545dd35
data plane version:  (1 proxies)

**kubectl version**
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:34Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.10-gke.17", GitCommit:"27b48e2b4c9535d185ec945c6a513537e4d116cf", GitTreeState:"clean", BuildDate:"2019-10-21T20:10:26Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
As add-on on GKE.

**Environment where bug was observed (cloud vendor, OS, etc)**
Google Cloud.

**Comment by Svendegroote91** [comment]
After browsing around some other related issues I found out that you can annotate your deployments with the following:

```
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/includeOutboundIPRanges: <IP_RANGE>
```

This will open up egress traffic for the specific IP range, even if the configmap istio-sidecar-injector contains the '*' value (which is the case for the istio add-on on GKE). 

Is there a way I can contribute to further clarify the documentation part about Istio add-on on GKE regarding external traffic (https://cloud.google.com/istio/docs/istio-on-gke/installing#accessing_external_services)?

**Comment by howardjohn** [comment]
We do have some (somewhat hidden, granted) docs about this on istio.io here: https://istio.io/docs/reference/config/annotations/. I'll send a PR to make this more explicit.

**Comment by howardjohn** [comment]
https://github.com/istio/istio.io/pull/5896 documents this

**Comment by Svendegroote91** [comment]
Awesome, thanks for the swift support and making the istio.io as complete as possible :-).
