### ISSUE TITLE
egress gateway is ignored in istioctl manifest apply -f : no resources found

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio#19267]
**Bug description**

**Expected behavior**

I should be able to deploy an egress gateway by using IstioControlPlane resource.

**Steps to reproduce the bug**

1. Deploy a demo profile (includes egress gateway, works as expected):

```
istioctl manifest apply --set profile=demo
...
Component EgressGateway installed successfully:
===============================================

serviceaccount/istio-egressgateway-service-account unchanged
deployment.apps/istio-egressgateway created
destinationrule.networking.istio.io/istio-multicluster-destinationrule unchanged
envoyfilter.networking.istio.io/istio-multicluster-egressgateway unchanged
gateway.networking.istio.io/istio-multicluster-egressgateway unchanged
virtualservice.networking.istio.io/istio-multicluster-egressgateway unchanged
poddisruptionbudget.policy/istio-egressgateway unchanged
role.rbac.authorization.k8s.io/istio-egressgateway-sds unchanged
rolebinding.rbac.authorization.k8s.io/istio-egressgateway-sds unchanged
service/istio-egressgateway created
...
```

2. Delete the egress gateway (works as expected):

Attached [egress-manifest-delete.yaml](https://github.com/istio/istio/files/3898303/egress-manifest-delete.yaml.txt)

```
istioctl manifest apply -f egress-manifest-delete.yaml
...
Component EgressGateway installed successfully:
===============================================

service "istio-egressgateway" deleted
deployment.apps "istio-egressgateway" deleted
...
```

3. Add egress gateway (does not work):

Attached [egress-manifest-enable.yaml](https://github.com/istio/istio/files/3898304/egress-manifest-enable.yaml.txt)

```
istioctl manifest apply -f egress-manifest-enable.yaml
...
Component EgressGateway installed successfully:
===============================================

No resources found
...
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

istioctl version --remote
client version: 1.4.0
control plane version: 1.4.0
data plane version: 1.4.0 (3 proxies)

kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.6+IKS", GitCommit:"6e178fd78a715131f29fb16ecd0106764284e36f", GitTreeState:"clean", BuildDate:"2019-11-18T06:08:37Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**

The problem is with installation.

**Comment by ericvn** [comment]
@vadimeisenbergibm I can try this after I create another cluster, but want to note that in your notes above you apply the _delete_ twice (and not the _enable_ the second time). Might just be a cut/paste error. I'm also not sure the indention is correct, but if the first _delete_ worked, then it likely is.

**Comment by vadimeisenbergibm** [comment]
@ericvn This is a copy&paster error in the comment, sorry. In the reality, I do apply egress-manifest-enable.yaml, and get the message "No resources found".

**Comment by vadimeisenbergibm** [comment]
@ericvn cc @howardjohn You are right, it is an indentation problem. Strange that the delete worked.

Attaching the files with the correct indentation:
[egress-manifest-delete.yaml.txt](https://github.com/istio/istio/files/3900898/egress-manifest-delete.yaml.txt)
[egress-manifest-enable.yaml.txt](https://github.com/istio/istio/files/3900899/egress-manifest-enable.yaml.txt)
