### ISSUE TITLE
TestWorkloadAgentGenerateSecretWithPluginProvider test failure

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#19276]
https://prow.istio.io/view/gcs/istio-prow/logs/unit-tests_istio_postsubmit/783

**Comment by JimmyCYJ** [comment]
@pitlv2109 since you refactored the test last time, could you please take a look?

**Comment by howardjohn** [comment]
still falling https://prow.istio.io/view/gcs/istio-prow/logs/unit-tests_istio_postsubmit/1053

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/20128/unit-tests_istio/6279

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/20225/unit-tests_istio/6616

**Comment by howardjohn** [comment]
Still flaking? https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/20213/unit-tests_istio/6766

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/20331/unit-tests_istio/6901

**Comment by JimmyCYJ** [comment]
I cannot reproduce this failure, and by tracing the tests in https://prow.istio.io/job-history/istio-prow/pr-logs/directory/unit-tests_istio?buildId=8854, it seems that this test is stable for a while. Let's reopen this if it flakes again.
