### ISSUE TITLE
Istio exposes one more port 3307 but not the same

### ISSUE THREAD

**Issue by bibi520** [istio/istio#19281]
We have exposed a 3307 port to connect to mysql
istio-ingressgateway   service：
![image](https://user-images.githubusercontent.com/42456284/69770890-ac969280-11c5-11ea-9d11-2f07e0f7e06d.png)
istio-ingressgateway  deployment：
![image](https://user-images.githubusercontent.com/42456284/69770943-e2d41200-11c5-11ea-8d04-fcc45b011d7f.png)
But the port I entered into the istio-ingressgateway pod was not occupied：
![image](https://user-images.githubusercontent.com/42456284/69770987-19aa2800-11c6-11ea-9daa-17ff6bdec0b7.png)

**Comment by howardjohn** [comment]
you need to create a Gateway object as well

**Comment by bibi520** [comment]
This is my gateway object：
![image](https://user-images.githubusercontent.com/42456284/69771201-eb791800-11c6-11ea-91ad-4758e7804b9c.png)
![image](https://user-images.githubusercontent.com/42456284/69771217-f633ad00-11c6-11ea-9363-b09272083325.png)
I can get in by mapping mysql SVC nodepoet alone but I can't get in by istio

**Comment by bibi520** [comment]
I made a mistake. Mysql was supposed to be TCP and I wrote HTTP
