### ISSUE TITLE
syntheticserviceentries CRD left after uninstalling istio

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#19286]
**Bug description**

When i uninstall istio by ` kubectl delete -f install/kubernetes/istio-demo.yaml`, syntheticserviceentries is left.

```
root@opensrc:~/istio-1.5-alpha.3b7b43f911ab6c69bf0da9623966521563cff3f8# kubectl get crd
NAME                                          CREATED AT
syntheticserviceentries.networking.istio.io   2019-11-25T11:57:17Z

```

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
I didn't think SSE was a real CRD we installed in the kubernetes cluster? I thought it was just sent over mcp

**Comment by Nino-K** [comment]
I don't think we install SSE as a CRD either, but let me dig into it see where it comes from since it is listed under `kubectl get crd`.

**Comment by Nino-K** [comment]
@hzxuzhonghu I tried this on a freshly installed cluster using latest master 46193e3bdffc055bac66ed358d5c5a8124f69eed and I'm having a hard time to reproduce it. Since we don't install SSE as a CRD could this be an old CRD in your cluster?

**Comment by howardjohn** [comment]
Maybe with MCP disabled Pilot is creating the CRD

**Comment by Nino-K** [comment]
Why with MCP disabled? MCP is a dependcy for SSE. However I did test the `istio-non-mcp.yaml` and couldn't reproduce.

**Comment by howardjohn** [comment]
@Nino-K pilot without MCP has a mode where it will actually register CRDs if they don't exist. I have no clue if that would get a SSE crd created somehow, but that is the only way I could think.

I just looked at my cluster and I also have SSE installed in my cluster, so somehow its happening

**Comment by Nino-K** [comment]
> pilot without MCP has a mode where it will actually register CRDs if they don't exist

@howardjohn that makes sense now, I did initially have the SSE CRD too when @hzxuzhonghu filed the issue, but I recently had to recreate my cluster and after the upgrade I'm no longer able to repo. 
can you please provide your k8s client/server and istioctl version here?

**Comment by howardjohn** [comment]
@Nino-K this is my development cluster that has had 100s of istio installs of various shapes, including ones where I was messing with this exact code path -- so it could have happened in any number of ways in my case. I didn't try to reproduce on a fresh cluster

**Comment by Nino-K** [comment]
Ok, I got to reproduce it. It is actually being created by the integration test suite. More specifically by galley pkg.
