### ISSUE TITLE
Support shortname for authorizationpolicies.security.istio.io resources

### ISSUE THREAD

**Issue by rolandkool** [istio/istio#19292]
**Describe the feature request**
With the new authorization policies, using kubectl to get or delete them, you'll need to specify the full resource name of `authorizationpolicies.security.istio.io`. This is because there is already a (deprecated) `authorizationpolicies.rbac.istio.io` which takes precedence if you do `kubectl get authorizationpolicy` (or `authorizationpolicies`). 
It would be nice to have a similar short alias as exists for networkpolicies: `netpol`. Something like `authzpol` would work.

**Describe alternatives you've considered**
Removing the `authorizationpolicies.rbac.istio.io` CRD, but not sure what the impact of that is.

**Additional context**

**Comment by rolandkool** [comment]
Checked out the source code and searched for `authorizationpolicies.rbac.istio.io` but there are no mentions of it (anymore). Guess it got left behind after upgrading.

**Comment by yangminzhu** [comment]
`authorizationpolicies.rbac.istio.io` can be deleted safely, it's a leftover of internal implementation detail from previous version. A fresh install of Istio 1.4 should not have this CRD.

I think we can mention this in https://istio.io/news/releases/1.4.x/announcing-1.4/upgrade-notes/

**Comment by esnible** [comment]
@istio/wg-user-experience-maintainers I have been bit by the same issue.  Do we want a short name for authorizationpolicies?

@sushicw Do we want an analyzer that checks for entirely deprecated CRDs?  I wrote code for deprecated fields in current CRDs, but this shows that there can be CRDs whose deletion is missed during an upgrade.

@rolandkool How did you upgrade?

**Comment by sushicw** [comment]
> @sushicw Do we want an analyzer that checks for entirely deprecated CRDs? I wrote code for deprecated fields in current CRDs, but this shows that there can be CRDs whose deletion is missed during an upgrade.

Yes, good idea. Created #19355 to track that.

**Comment by rolandkool** [comment]
@esnible I'm pretty sure the upgrade path to 1.4 was this: on a newly installed cluster, install 1.3.4. Upgrade to 1.3.5. Deinstall Istio, with exception of the CRDs (we typically keep these inside the cluster as removing them will also remove all resources of that type. It's a precaution we build into our provisioning tooling). Do a new installation of 1.4.0.
So there was no upgrade done from 1.3.5 to 1.4.0. 

Having checks in the analyzer sounds like a nice feature.

**Comment by esnible** [comment]
For new installs at least there is only one authorizationpolicies.

@rolandkool @yangminzhu Does it make sense to close this?

**Comment by yangminzhu** [comment]
> For new installs at least there is only one authorizationpolicies.
> 
> @rolandkool @yangminzhu Does it make sense to close this?

Yes, this can be closed as there is only one authorization policy CRD now.
