### ISSUE TITLE
istioctl.bash and _istioctl auto completion files missing

### ISSUE THREAD

**Issue by rolandkool** [istio/istio#19297]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
The istioctl documentation contains a section on enabling bash/zsh autocompletion. It refers to files istioctl.bash and _istioctl in the tools directory. The current istio-1.4.0-linux.tar.gz doesn't contain these files. Releases of istio 1.3.x do contain them.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[X] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Files should be there or the documentation needs to be updated with instructions on how to generate them.

**How was Istio installed?**
Just unpack the tar.gz file

**Comment by rolandkool** [comment]
As a workaround, I managed to generate them using this command: `istioctl collateral completion --bash -o .` as documented in https://github.com/istio/istio/issues/6119

**Comment by howardjohn** [comment]
Hey, thanks for the report. We have this fixed now so in the next release (hopefully pretty soon) will have this fixed. See https://github.com/istio/release-builder/pull/74

**Comment by Moisi** [comment]
FYI @howardjohn :
I couldn't find though files too after installation on ubuntu. 
The mentioned above `istioctl collateral completion --bash -o .`
thankyou @rolandkool
