### ISSUE TITLE
Istio CNI should provide metrics

### ISSUE THREAD

**Issue by johscheuer** [istio/istio#19300]
**Describe the feature request**

During the setup of some alert rules for our Istio Setup (focused on the Istio "system" side) we noticed that Istio CNI is the only component that doesn't provide some metrics. So the only way to monitor Istio CNI is currently to check if the `DaemonSet` ist there and if there are some running `Pods` of Istio CNI.

Some Ideas from other CNI's:

- Calico: https://docs.projectcalico.org/v3.9/reference/felix/prometheus
- Cilium: https://docs.cilium.io/en/v1.6/configuration/metrics

The introduction of a metrics endpoint (with some according metrics) allow a better monitoring of the Istio CNI (which is a relativ critical component from my point of view).

Currently I don't have a clear idea which metrics should be exposed by Istio CNI but I will take some time and write down some ideas probably inspired by the metrics of other CNI's and the Istio CNI code. If you have some ideas what metrics would be useful feel free to comment here.

**Describe alternatives you've considered**

Currently I'm not aware of any alternative. The only decision we could make as an "alternative" is to not implement metrics for Istio CNI.

**Additional context**

**Comment by howardjohn** [comment]
we probably want version, # of success, # of failures at a minimum. This would be useful

**Comment by howardjohn** [comment]
Not stale

**Comment by tariq1890** [comment]
+1 This would be very useful. I can take a crack at this when I find time.

**Comment by abhide** [comment]
@tariq1890 Sure go ahead. I have unassigned myself.
