### ISSUE TITLE
Add hostPort to istio-ingressgateway deployment template of the official helm chart

### ISSUE THREAD

**Issue by rforberger** [istio/istio#19304]
**Describe the feature request**
I want to add a hostPort key to my istio-ingressgateway deployment manifest.
I have added the following code:

```
...
           ports:
             {{- range $key, $val := $spec.ports }}
             - containerPort: {{ $val.port }}
{{- if $val.hostPort }}
              hostPort: {{ $val.hostPort }}
{{- end }}
             {{- end }}
             - containerPort: 15090
               protocol: TCP
...
```

And in the values.yaml I added:

```
...
   ports:
     ## You can add custom gateway ports
     # Note that AWS ELB will by default perform health checks on the first port
     # on this list. Setting this to the health check port will ensure that health
     # checks always work. https://github.com/istio/istio/issues/12503
   - port: 15020
     targetPort: 15020
     name: status-port
   - port: 80
     targetPort: 80
     name: http2
     nodePort: 31380
     hostPort: 81
   - port: 443
     name: https
     nodePort: 31390
     hostPort: 444
   # Example of a port to add. Remove if not needed
   - port: 31400
     name: tcp
     nodePort: 31400
...
```

The problem is, that the istio-ingressgateway service also uses this values.yaml config and is trying to deploy a hostPort field on the service, which is not possible, since the Service object doesn't have that field. 

My question is, how would you solve this or can you add such a feature that a hostPort can be used in the deployment?

The problem is, I would need it asap, not in a further release of istio.

Thanks in advance.

Best regards,
rforberger

**Describe alternatives you've considered**
no alternatives

**Additional context**

**Comment by howardjohn** [comment]
If you are already modifying the helm templates yourself to add this, can't you just change it so that it doesn't use the same value for the deployment and service?

If you use the istioctl install method you could also achieve this with an overlay I think

**Comment by rforberger** [comment]
@howardjohn 
Well, whatever value I use the the values.yaml, in the ports key, it will be used for the istio-ingressgateway service as well. And it will not be deployed when the key there is not found.
What I practically need is a separation of the data (values.yaml) between deployment and Service.

I think I can't use the istioctl install method because in that environment, helm is used.
I don't want to change the code from upstream (Github) since then merging in new releases will be hard for us. Therefore the feature request.

**Comment by howardjohn** [comment]
With istioctl you can overlay arbitrary configs, similar to kustomize, which should be able to handle this case.

**Comment by rforberger** [comment]
@howardjohn 
Ok thanks. We are deplyoing our k8s manifests with ArgoCD. We will run an istioctl init container in order to deploy the config overlay for the hostPort.
`istioctl manifest` is the right command to do this, right?

**Comment by rforberger** [comment]
Or is it `istioctl kube-inject`?

**Comment by howardjohn** [comment]
Yes, you can use istioctl can configure options like this on the GW: https://preliminary.istio.io/docs/setup/install/istioctl/#configure-gateways
