### ISSUE TITLE
istioctl mixerCheckServer and mixerReportServer cluster domain not effect

### ISSUE THREAD

**Issue by wu0407** [istio/istio#19314]
**Bug description**
set cluster domain in global.proxy.clusterDomain not change the mixerCheckServer and mixerReportServer domain in istio configmap.
it relate code:

https://github.com/istio/installer/blob/master/istio-control/istio-discovery/templates/configmap.yaml#L48-L58

https://github.com/istio/istio/blob/c4def934e4f8d1feb42725da41ee0078cde8397f/install/kubernetes/helm/istio/templates/configmap.yaml#L76-L89

**Expected behavior**
mixerCheckServer and mixerReportServer use customize domain.

**Steps to reproduce the bug**
manifest.yaml
```
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  values:
     global:
        proxy:
          clusterDomain: k8s-test-cluster.local
```
istioctl manifest apply -f  manifest.yaml
kubectl get cm -n istio-system istio -o yaml | grep mixerCheckServer
```
mixerCheckServer: istio-policy.istio-system.svc.cluster.local:15004
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
root@test-k8s-master:~# istioctl version --remote
client version: 1.4.0
control plane version: 1.4.0
data plane version: 1.4.0 (3 proxies)
root@test-k8s-master:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.4", GitCommit:"a87e9a978f65a8303aa9467537aa59c18122cbf9", GitTreeState:"clean", BuildDate:"2019-07-08T08:43:10Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.4", GitCommit:"a87e9a978f65a8303aa9467537aa59c18122cbf9", GitTreeState:"clean", BuildDate:"2019-07-08T08:43:10Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
Your manifest is missing the proxy: field it looks like? You are setting global.clusterDomain not global.proxy.clusterDomain

**Comment by wu0407** [comment]
> Your manifest is missing the proxy: field it looks like? You are setting global.clusterDomain not global.proxy.clusterDomain

sorry, has some mistake, but set global.proxy.clusterDomain not change  mixerCheckServer domain

**Comment by howardjohn** [comment]
Ah yes my misunderstanding. Thanks, will fix asap
