### ISSUE TITLE
global includeInboundPorts is not effect

### ISSUE THREAD

**Issue by wu0407** [istio/istio#19312]
**Bug description**
I want to default redirect no inbound traffic to Envoy, according https://github.com/istio/istio/blob/1.4.0/install/kubernetes/helm/istio/values.yaml#L255, it no effect to set `values.global.proxy.includeInboundPorts: ""`
But in init-container  and istio-proxy only use `traffic.sidecar.istio.io/includeInboundPorts`
https://github.com/istio/istio/blob/c4def934e4f8d1feb42725da41ee0078cde8397f/install/kubernetes/helm/istio/files/injection-template.yaml#L27
https://github.com/istio/istio/blob/c4def934e4f8d1feb42725da41ee0078cde8397f/install/kubernetes/helm/istio/files/injection-template.yaml#L216

**Expected behavior**
not redirect ingress traffic to envoy

**Steps to reproduce the bug**
istioctl manifest apply --set values.global.proxy.includeInboundPorts=""

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
root@test-k8s-master:~# istioctl version --remote
client version: 1.4.0
control plane version: 1.4.0
data plane version: 1.4.0 (3 proxies)
root@test-k8s-master:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.4", GitCommit:"a87e9a978f65a8303aa9467537aa59c18122cbf9", GitTreeState:"clean", BuildDate:"2019-07-08T08:43:10Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.4", GitCommit:"a87e9a978f65a8303aa9467537aa59c18122cbf9", GitTreeState:"clean", BuildDate:"2019-07-08T08:43:10Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
@lambdai did you intentionally make this not configurable?
