### ISSUE TITLE
prometheus is configured despite telemetry disabled in IstioControlPlane

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio#19348]
**Bug description**

Deploying an egress gateway only in a new namespace, configures prometheus despite telemetry being disabled.

To reproduce:
1.  `kubectl create namespace mynamespace`

Use attached [egress-gateway-icp.txt](https://github.com/istio/istio/files/3916234/egress-gateway-icp.txt), it has telemetry disabled.

2. `istioctl manifest apply -f egress-gateway-icp.txt --set values.global.istioNamespace=istio-system`

```
...
Component Prometheus installed successfully:
============================================

serviceaccount/prometheus unchanged
clusterrole.rbac.authorization.k8s.io/prometheus-istio-system unchanged
clusterrolebinding.rbac.authorization.k8s.io/prometheus-istio-system unchanged
configmap/prometheus unchanged
deployment.apps/prometheus unchanged
service/prometheus unchanged
...
```
 

**Expected behavior**
The output should be:

```
...
Component Prometheus installed successfully:
============================================
No resources found
...
```

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by irisdingbj** [comment]
prometheus can only be disabled via :

  values:
    prometheus:
      enabled: false

**Comment by howardjohn** [comment]
Telemetry == mixer, this is working as intended
