### ISSUE TITLE
Ingress SDS tests should be run as presubmit

### ISSUE THREAD

**Issue by pitlv2109** [istio/istio#19342]
These tests are stable now, but they are running only in postsubmit. The only concern is that they will add about 15 minutes to the current security test job in presubmit. Native Citadel and/or running multiple test jobs for security tests should address this problem. More context: https://github.com/istio/istio/pull/19329, https://github.com/istio/istio/issues/18651.

**Comment by JimmyCYJ** [comment]
Closing this one in favor of https://github.com/istio/istio/issues/19342
