### ISSUE TITLE
a application start with sidecar some can connect some can not return Connection reset

### ISSUE THREAD

**Issue by zziawan** [istio/istio#19345]
**Bug description**
istio 1.0.4 when deploying some pods in same namespace with sidecar, some can connect some cannot, without sidecar all can connect.  restart pod not work, but after restart pilot or policy pod work. 
what the problem ? can someone  give me a hint ?

**Comment by howardjohn** [comment]
Please upgrade your Istio, version 1.0 has not been supported for many many months and its unlikely the errors correlate to the current code.

**Comment by howardjohn** [comment]
See https://istio.io/blog/2019/announcing-1.0-eol/
