### ISSUE TITLE
Analyzer for deprecated CRDs

### ISSUE THREAD

**Issue by sushicw** [istio/istio#19355]
Add an analyzer to detect deprecated CRDs and issue a warning. e.g. https://github.com/istio/istio/issues/19292

**Comment by jasonwzm** [comment]
Discussed with Chris a bit on this and it sounds like that the hard part is that we don't have a way of tracking deprecated CRDs. Two possible ways: 1. Add deprecated CRDs into the collections so that galley still retrieves the deprecated ones and analyzer will be able to detect the deprecated CRD. 2. Analyzer calls API server directly and compare with its known collection.

**Comment by ayj** [comment]
Here's everything I can think of that should be done as part of deprecating a CRD / API. @jasonwzm @esnible wdyt?

1. Annotate CRD as deprecated
1. Remove any instances (CR) of the deprecated CR from the install manifests.
1. Update istio/api and client-go to indicate the API is deprecated.
1. Add deprecation to release notes.
1. Add CRD to deprecation analyzer. istioctl continues to watch the deprecated CRD.
1. Galley continues to conditionally watch the deprecated CRD to populate CRD status. If CRD is not found (the user migrated) then Galley ignores it and does not produce an user facing warning/error.
1. Create migration tooling when appropriate 

After 1-2 release cycles ...
1. remove the deprecated CRD. 
1. Do not uninstall the CRD or CRs from users clusters (they might downgrade). 
1. Announce removal in release notes. 
1. Remove CRD artifacts from repos.

**Comment by jasonwzm** [comment]
> Annotate CRD as deprecated

What does annotating CRD as deprecated do for the user? 

> Remove any instances (CR) of the deprecated CR from the install manifests.

You mean CRD from the install manifest?

We probably also need to think about Istio upgrade/downgrade cases.

**Comment by ayj** [comment]
> What does annotating CRD as deprecated do for the user?

Not a whole lot unless they bother to look at it. But I figured this was cheap to add, unless we decide to also remove deprecated CRD from the install manifest. In that case I'd say skip the annotation.

> You mean CRD from the install manifest?

I mean we shouldn't use deprecated APIs in our install. 

> We probably also need to think about Istio upgrade/downgrade cases.

Agreed. I think the deprecation process itself along with migration tools handles the bulk of that work. I guess we'd also want to integrate with `istioctl upgrade` to proactively warn users? cc @elfinhe

**Comment by esnible** [comment]
@Jason-ZW Is there a standard/well-known way to do @ayj's step 1, marking CRDs as deprecated?  If so, we haven't done flagged any CRDs deprecated for 1.6.x.

The analyzers see the CRDs but it seems painful to write an analyzer that looks at every possible resource type.  I propose the "deprecated CR" analyzer just be hand-tuned each release to have the deprecated types as inputs, and merely warn about every instance of those types.

**Comment by esnible** [comment]
@Jason-ZW @therealmitchconnors Is there a standard/well-known way to do @ayj 's first step?

**Comment by esnible** [comment]
Comments from the duplicate Issue:

`istioctl analyze` warns about deprecated fields in use in user CRs.

In Master, we only warn about `HTTPRoute.fault.delay.percent`.

Older versions of the deprecation analyzer handled IstioNetworkingV1Alpha3Envoyfilters and metadata.IstioRbacV1Alpha1Servicerolebindings but these types are no longer present so we can't check for them.

This work item is to add recent CRD deprecations to the analyzer
- https://github.com/istio/api/pull/1351 - v1alpha1 RBAC and Authentication policy
- https://github.com/istio/api/pull/1290 - Deprecate authentication alpha policy

Possibly https://github.com/istio/api/pull/1206 but I think it is too old.

@therealmitchconnors I assigned this to myself but at the UX meeting you said you had some thoughts about how we might do it via istio/api.

Currently the analyzer is hand-written.  The .protos generate Go code with `$hide_from_docs` and `Deprecated` comments.  If these comments could make it into Go "struct tags", or into a collection of deprecated fields then the analyzer could just make use of that.

Today I don't know of a way to figure out if a field is `$hide_from`docs` or `Deprecated`.

**Comment by jasonwzm** [comment]
Currently no. Alternatively, we can add deprecated annotation to CRDs. We may need to add the deleted resource schema back to metadata to be able to retrieve the resources.

**Comment by esnible** [comment]
FYI: I will skip the detection of authentication.istio.io/v1alpha1/Policy, because the webhook rejects them in 1.6.0.

The following new deprecations need to be analyzed:
- https://github.com/istio/api/pull/1437

**Comment by jasonwzm** [comment]
We still need to implement deprecation for CRDs. Reopen this.

**Comment by esnible** [comment]
Closing because https://github.com/istio/istio/pull/25454 detects them.
