### ISSUE TITLE
data race in eds

### ISSUE THREAD

**Issue by rshriram** [istio/istio#19365]
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/18941/unit-tests_istio/4752

**Comment by howardjohn** [comment]
Another with full trace https://prow.istio.io/view/gcs/istio-prow/logs/unit-tests_istio_postsubmit/803

**Comment by howardjohn** [comment]
Seems like this can only happen if we have multiple pushes concurrently (which I don't think is the case) or if we have some shared object in the EDS response. The error doesn't give us that much detail about what part of the EDS object causes the race though, so hard to say. I couldn't repro locally, but happens multiple times in CI so not just a weird CI bug it seems

**Comment by hzxuzhonghu** [comment]
Never see it again recently

**Comment by howardjohn** [comment]
I think this may have been fixed
