### ISSUE TITLE
the issue about white&black listing don't work

### ISSUE THREAD

**Issue by tiandong19860806** [istio/istio#19377]
**Bug description**
In my istio cluster, the white listing don't work.
I had test by the match condition by below two kinds:
1. match by 'source.ip' , I want it return real client PC ip, but actual it's istio-ingressgateway pod IP.
2. match by 'request.headers['x-real-ip']', I want it return real client PC ip, but actual it's empty value.
3. the attribute 'blacklist:true', it's can't change the whitelist to the blacklist, the page also can access.

other, Could you give us a detail example to black list and white list by using client_ip and cookies. because istio.io website doc example is less and unvalid.

**Version**
Istio: 1.2.5
Kubectl: 1.13.7

**Expected behavior**
1. white listing can access , when match the real client ip / cookie value / request header value.
2. white listing can reject  , when match the real client ip / cookie value / request header value.

**Steps to reproduce the bug**
1. white listing by match client_ip
<1>. clear and deploy the productpage.
<2>. clear and deploy the white listing.
          detail referenct below 'yaml file 01'.
<3>. refresh the browser about productpage url.

2. white listing by match request header
<1>. clear and deploy the productpage.
<2>. clear and deploy the white listing.
          detail referenct below 'yaml file 02'.
<3>. refresh the browser about productpage url.

3. white listing by match cookie value.
<1>. clear and deploy the productpage.
<2>. clear and deploy the white listing.
          detail referenct below 'yaml file 03'.
<3>. refresh the browser about productpage url.

4. black listing by match client_ip / reqeust header / cookie value.
detail: just change the attribute by 'blacklist:true' , other is same as 1/2/3.

**How was Istio installed?**
Rancher : 2.3.0

**Environment where bug was observed (cloud vendor, OS, etc)**
CentOS 7.4 x64

**detail about yaml file**
192.168.3.22 is my client PC's IP.

<1> yaml file 01
![图片](https://user-images.githubusercontent.com/12596666/70121877-71ef9700-16aa-11ea-9ea3-6e42b6a8b10a.png)

<2> yaml file 02
![图片](https://user-images.githubusercontent.com/12596666/70121939-977ca080-16aa-11ea-9d12-b9742acc98a8.png)

<3> yaml file 03
![图片](https://user-images.githubusercontent.com/12596666/70122017-c8f56c00-16aa-11ea-954b-8937fd05f1b9.png)

**Comment by tiandong19860806** [comment]
the content of all whitelist yaml file as below:
[file.txt](https://github.com/istio/istio/files/3920588/file.txt)

**Comment by tiandong19860806** [comment]
the step 1 '<1>. clear and deploy the productpage.' detail operations as below:

step 1: 
# modify the attribute 'disablePolicyChecks' value to false.
root >> kubectl edit configmap istio -n istio-system -o yaml
# after modify and save , then query the result 
root >> kubectl get configmap istio -n istio-system -o jsonpath="{@.data.mesh}" | grep disablePolicyChecks

----------------------

step 2:  
root >> kubectl apply -n app -f \
https://raw.githubusercontent.com/tiandong19860806/istio/master/samples/bookinfo/platform/kube/bookinfo.yaml

root >> kubectl apply -n app -f \
https://raw.githubusercontent.com/tiandong19860806/istio/master/samples/bookinfo/networking/bookinfo-gateway.yaml

root >> kubectl apply -n app -f \
https://raw.githubusercontent.com/tiandong19860806/istio/master/samples/bookinfo/networking/destination-rule-all.yaml

step 3: 
# access the productpage as below
# format = http://<node_ip>:31380/productpage
http://10.67.37.13:31380/productpage

**Comment by pixystone** [comment]
pilot needs to be restarted to make `disablePolicyChecks` taking effect:
> disablePolicyChecks disables mixer policy checks. if mixer.policy.enabled==true then disablePolicyChecks has affect. Will set the value with same name in istio config map - pilot needs to be restarted to take effect.

refer: https://istio.io/docs/reference/config/installation-options/
