### ISSUE TITLE
Could istio-proxy send traces directly to jaeger-agent?

### ISSUE THREAD

**Issue by skrytt** [istio/istio#19379]
**Describe the feature request**
I'd like to configure istio-proxy to export tracing data to a colocated jaeger-agent, as opposed to via a jaeger-collector. 

Based on the docs I've read for Jaeger and Istio, I think istio-proxy can emit zipkin format traces over HTTP/TCP, but jaeger-agent only accepts a few UDP-transport formats https://www.jaegertracing.io/docs/1.15/deployment/#agent so there is no overlap in supported formats. This means for the moment, sending traces to the jaeger-collector is the only option.

**Describe alternatives you've considered**

- Asking Jaeger project whether jaeger-agent can be enhanced to accept zipkin traces on HTTP port 9411 or another port in a similar manner to how jaeger-collector does
- Writing a bespoke service that accepts zipkin traces on HTTP port 9411, proxying and adapting them to one of the UDP-transported formats jaeger-agent can accept 
- Sending traces to jaeger-collector instead of jaeger-agent https://www.jaegertracing.io/docs/1.15/deployment/#collectors

**Additional context**

**Comment by objectiser** [comment]
Another option would be to use the Opencensus tracer [within envoy](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/trace/v2/trace.proto#config-trace-v2-opencensusconfig), with ocagent exporter, to report to an OpenTelemetry collector (running as a sidecar agent) configured with jaeger exporter - which then reports the traces to the Jaeger collector.

**Comment by diranged** [comment]
Hmm.. looks like this work got dropped. Could this be re-visited?
