### ISSUE TITLE
application can not access until istio-proxy ready

### ISSUE THREAD

**Issue by etherlai** [istio/istio#19378]
hi：
I have a question：when i start deployment with istio-proxy，the app container cat not connect mysql/redis because istio-proxy is not ready the first moment; the app have not liveness and reconnect strategy. Does istio or k8s has strategy to solve this problem, such as app container start after istio-proxy ready.

**Comment by howardjohn** [comment]
You can find a lot of info on this topic here:  https://github.com/istio/istio/issues/11130
