### ISSUE TITLE
istioctl cmd getting unnamed ports

### ISSUE THREAD

**Issue by yxue** [istio/istio#19387]
As protocol detection is on by default, having an istioctl cmd tool to get all unnamed ports will help customers migrate from unnamed ports to named ports. 

The process would be 
1. Running cmd 
```
istioctl experimental unnamedports 
```
and output

```
SERVICE     PORT     TARGET PORT     PORT NAME
svc1        6666     80              port1
svc2        7777     90              port2
svc3        9999     targetport1     port3
```

2. Query prometheus and filter by service name and target port. This step will help the user to figure out which kind of traffic the port is serving and user can re-apply CRD with suggested port name, e.g, for port serving HTTP, http-foo

**Comment by yxue** [comment]
^^ @duderino @esnible

**Comment by liamawhite** [comment]
Could you help me understand why a user would want to migrate to named ports if protocol detection is working for them?

**Comment by yxue** [comment]
The traffic could bypass authN/authZ policy when using protocol detection. E.g., if the user apply the policy to enable GET only. Because pilot cannot infer the protocol from the port name, it will create both HTTP and TCP filter chains and the client can send TCP traffic to bypass that policy.

**Comment by liamawhite** [comment]
Is this something that should be part of the analyze command rather than its own command?

**Comment by yxue** [comment]
Technically we can add the command to the analyze command. I am not familiar with istioctl anaylze. From my limited knowledge on istioctl analyze, istioctl analyze consumes static yaml file and reports error. We can learn unnamed ports from the yaml file but do we want to add this command to the istioctl analyze.

**Comment by liamawhite** [comment]
I believe it does both static yaml analysis and in cluster.

@therealmitchconnors does this seem like a good fit for analyze?

**Comment by sushicw** [comment]
Correct, istioctl analyze can handle:

* Yaml files
* Live cluster
* Live cluster + Yaml files (essentially simulating the effect of applying the files)

If this is something where we want to warn the user / strongly encourage a best practice, it's probably an ok fit for analyze. More about writing analyzers can be found here: https://github.com/istio/istio/blob/master/galley/pkg/config/analysis/README.md

**Comment by yxue** [comment]
Thanks @sushicw! I updated the PR to add the port name analyzer.
