### ISSUE TITLE
Destination Rule host - specify exactly what is a short name

### ISSUE THREAD

**Issue by xeviknal** [istio/istio#19384]
**Bug description**

I am having the issue of not understanding what `short names` means for a DestinationRule.spec.host in https://istio.io/docs/reference/config/networking/destination-rule/#DestinationRule

From the text there, I don't know exactly which formats of hosts are allowed. All possible formats from [K8S](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/)? Be it: service name, fqdn? Can I use `sevice.ns` format? Wildcar?

**Expected behavior**
Specify what kind of values are allowed for that field:
- service names: `reviews`
- service.namespace: `reviews.bookinfo`
- FQDN: `reviews.bookinfo.svc.cluster.local`
and so on.

**Comment by howardjohn** [comment]
short name == no namespace specified as given in the example `(e.g. “reviews” instead of “reviews.default.svc.cluster.local”)`. You can still use any format though
