### ISSUE TITLE
Fall back to compiled in default for local file system profile

### ISSUE THREAD

**Issue by ostromart** [istio/istio#19386]
Currently, local profiles require a default.yaml to be co-located in the same dir. Ideally it should be possible to just point to a profile and use the compiled-in default.yaml if a default.yaml is not found in the target dir.

**Comment by esnible** [comment]
I couldn't figure out the meaning of this issue from the description.

If it involves adding flags or changing the meaning of flags passed to `istioctl generate` please tag it as `User Experience` and explain the intended change.

**Comment by howardjohn** [comment]
```
$ cp manifests/profiles/minimal.yaml /tmp/foo
$ ~/istio/istio-1.6.0-beta.1/bin/istioctl manifest generate --set profile=/tmp/foo/minimal.yaml
Error: open /tmp/foo/default.yaml: no such file or directory
```

This is the issue ^. Seems still valid
