### ISSUE TITLE
Core dump does not work due to container restart

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#19411]
In 1.4 pilot agent was updated to exit when Envoy exits. This generally works well since it gives visibility to the api server that proxy container has restarted.

However it has broken coredump capability, we have not tests for it.
As soon as a coredump finishes, the container exits and we have no mechanisms to copy the core dump over. Even during testing there is not way to override this behaviour.
At least I could not find it.

1. Add override
2. Add core management ?
3. Add tests that produce and then consume a coredump.

@richardwxn Please create a design doc if required.

**Comment by lambdai** [comment]
IIRC @bianpengyuan confirmed a workaround as mount host dir into the pod. 
Hope it would save your time from doubting envoy or k8s change :)

**Comment by kyessenov** [comment]
2c: please don't use persistent storage by default. this would break the node auto-scaler (which is already broken by emptyDir, but nevertheless).

**Comment by bianpengyuan** [comment]
I actually did not get there :). For sure not add persistent storage, it is just a work around. Adding an option to pilot agent to make it not quit if core dump is enabled (that is what mandar suggests about "adding override" I guess?) makes more sense to me.

**Comment by kyessenov** [comment]
Alternatively, the dump should be transferred into some bucket / store. We'd need to bump up termination grace period.

**Comment by sdake** [comment]
@kyessenov sounds like a good proposal to me.

**Comment by mandarjog** [comment]
@geeknoid what else do we need to do to remove needs-triage?

**Comment by bianpengyuan** [comment]
@mandarjog I believe it needs milestone to be added.

**Comment by richardwxn** [comment]
Is it ok to add an env variable which depends on the value of enableCoreDump, the pilot agent can either not quit when this override set to true, or wait sometime before quit for the core dump to finish and transfer into some other storage.

**Comment by mandarjog** [comment]
Yes, that is fine.

**Comment by richardwxn** [comment]
We can just leave the flexibility to user to add prestop hook they would like to the lifecycle of proxy container.

**Comment by howardjohn** [comment]
Fixed by https://github.com/istio/istio/pull/23154 (?)
