### ISSUE TITLE
CNI helm template include/exclude options

### ISSUE THREAD

**Issue by ElliotPM** [istio/istio#19413]
The CNI is a strategic solution to move away from using an init container with NET_ADMIN privileges; however, the helm template does not allow the option to set CIDR ranges or ports to include or exclude from the service mesh. 

These are required for us to continue using init containers which access pod-external services, use statefulsets (We are aware of improvements to statefulset compatibility but have not upgraded or tested this internally), or to implement strict MTLS. 

We have considered setting pod annotations, as suggested in the documentation; however, this is not suitable because we operate in a service oriented team structure and the requirements for exclusions must be cluster-wide and transparent to application teams.

Also considered is moving all of our infrastructure to within the service mesh, although this is not currently possible as we are not in a position to implement multi-cluster Istio deployments.

I was aware of previously raised issues on the istio-init github page, before these were merged and closed.
I am also aware of the Kubernetes sidecar container work, and on a piece of work to move the proxy to within a plugin. 

Thanks,

Elliot

**Comment by rlenglet** [comment]
You can add the [annotations supported by Istio CNI](https://istio.io/docs/setup/additional-setup/cni/#traffic-redirection-parameters) in your injection template, starting from Istio 1.4.0. See https://github.com/istio/istio/pull/17334. Just set the `injectedAnnotations` field in your injection template with the desired annotations.

**Comment by rlenglet** [comment]
@ElliotPM Please reopen this issue if the solution above doesn't work for you.
