### ISSUE TITLE
node-agent: implement SDS for mesh expansion

### ISSUE THREAD

**Issue by dahutu** [istio/istio#19418]
**Describe the feature request**
Implement SDS in node-agent for Mesh Expansion.  Currently (1.4) CA cert chain and workload certs are stored in /etc/certs directory on the VM.  This is fine during bootstrap but not very secure in the long term, especially before Istio has a good cert revocation story.  Citadel agent has built-in SDS support.  node-agent should also implement SDS support so that /etc/certs directory can be deleted after VM becomes part of Istio service mesh.

**Describe alternatives you've considered**
There is not a good way to secure directories on a VM if a user has sudo permission.

**Additional context**

**Comment by FrimIdan** [comment]
In istio 1.5 SDS is on by default, this means that mesh expansion is broken?

**Comment by howardjohn** [comment]
I am pretty sure this is done, @irisdingbj is there any work left?

**Comment by incfly** [comment]
I know @costinm has sent out some PR for SDS, but i'm losing the track w.r.t doc/release etc

Closing as above comment suggests. Anyone can reopen if see any gap in 1.5 in any aspects.
