### ISSUE TITLE
Expose metrics for seconds until cert expiration

### ISSUE THREAD

**Issue by dahutu** [istio/istio#19420]
**Describe the feature request**
We would like Istio to implement a service or cert level metric to report seconds until the specific workload cert is expired.

Rationale:
Envoy currently has a metric, days_until_first_cert_expiring, that repots the number of days "until the next certificate being managed will expire".  However it doesn't fit our needs because:
1. we need to be able to find out the time before a workload cert for a specific services will expire;
2. We will use workload certs with short TTL, e.g., 24 hours, to reduce the impact of workload cert compromise risk before Istio has cert revocation support.  the resolution of days_until_first_cert_expiring is too coarse.
 
**Describe alternatives you've considered**
Envoy days_until_first_cert_expiring metric which does not work well for us for reasons above. 

**Additional context**

**Comment by JimmyCYJ** [comment]
Tentatively assign to @incfly, please feel free to reassign.

**Comment by incfly** [comment]
I thought per slack discussion, we prefer to add metrics in envoy as `seconds_until_first_cert_expiring`?

**Comment by dahutu** [comment]
Correct.  However as I thought about more, the <time>_until_first_cert_expiring metric is not very actionable because it does not tell me which cert is expiring. I may still need to query /certs endpoint to get info for the certificate.  Also it does not tell the user if multiple certs are expiring.  A service / cert specific metric solves these problems.  What do you think?

**Comment by incfly** [comment]
this FR description worded as "workload certificate". AFAIK, in Istio, each workload only has one certificate, except for the gateway which can facing public HTTPS traffic.

So in this case, you shouldn't care about which **cert** will expire, you only need to care about which **workload** is having a cert about to expire. When telemetry backend, e.g. prometheus, scraping Envoy, I assume it can bucket into some workload identifier, to help operator locate the problematic workload?

Do I miss anything?

**Comment by dahutu** [comment]
That works for me.

**Comment by howardjohn** [comment]
Yes prometheus will identify the workload, so we just need to make the envoy metric in seconds

**Comment by howardjohn** [comment]
#23076
related^
