### ISSUE TITLE
The istio pod node accesses the internal istio service through the external network and reports Connection refused

### ISSUE THREAD

**Issue by guojingyinan219** [istio/istio#19430]
**Bug description**
  Access another intranet service on the istio internal node through the extrane
![image](https://user-images.githubusercontent.com/13974995/70290784-fc073f00-1813-11ea-9cab-34fde52ecc26.png)

**Expected behavior**
 how to inside isito pod visit another service by External network
**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
![image](https://user-images.githubusercontent.com/13974995/70291152-49d07700-1815-11ea-94a4-25a801a6016a.png)

**How was Istio installed?**
  helm install
**Environment where bug was observed (cloud vendor, OS, etc)**
。。。。

**Comment by guojingyinan219** [comment]
![image](https://user-images.githubusercontent.com/13974995/70291288-a9c71d80-1815-11ea-9147-546bf02f916a.png)

**Comment by hzxuzhonghu** [comment]
Can you try to access to www.google.com?

**Comment by guojingyinan219** [comment]
@hzxuzhonghu  access to www.google.com is ok , i  have  set up  includeIPRanges: '172.28.0.0/16,172.29.0.0/20' ，  Extranet  without istio

**Comment by hzxuzhonghu** [comment]
And what's your domain resolved to? A public ip or a private ip in the range `172.28.0.0/16,172.29.0.0/20`. I think you can try to set a ServiceEntry

**Comment by guojingyinan219** [comment]
private ip in the range 172.28.0.0/16,172.29.0.0/20 , External normal access is OK, but access through external network inside pod is access denied. ServiceEntry  i tried ，cannot resolve
