### ISSUE TITLE
Clean up CRD status field

### ISSUE THREAD

**Issue by sushicw** [istio/istio#19447]
Currently, Galley can optionally write validation messages to the CRD status field via the `enableAnalysis` flag. (See https://istio.io/docs/ops/diagnostic-tools/istioctl-analyze/#enabling-validation-messages-for-resource-status for more details). 

If status is updated on a resource and then enableAnalysis is turned off, the old message will stay behind. While harmless, it's distracting and noisy. Furthermore, it's painful to clean up manually. e.g. `kubectl edit` will not let you modify the status subresource. 

We should find a way to make sure that Galley cleans up after itself in this case. Perhaps when Galley starts, it can reset the status field on Istio CRDs before starting applicable status controllers?

**Comment by esnible** [comment]
What is the timeline for `enableAnalysis` being the default?

**Comment by sushicw** [comment]
@esnible We're hoping to do this for 1.5. See https://docs.google.com/document/d/1P23Sgvnn1_NVxc9DZNrLEZ6b9tahAPJF_ByMvi0ItYM/edit (and feel free to comment, detailed discussion is probably best suited there).
