### ISSUE TITLE
Resolve pain of private build sync

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#19445]
Today, we handle private builds like so: (using 1.4.2 as an example)

* Once 1.4.1 is shipped, we freeze the 1.4 branch in public - no changes allowed
* In private, we sync to 1.4.1 and apply patches. These patches are referenced by SHA in various repos (istio -> proxy -> envoy)
* Once the embargo is lifted, we directly push the patches to public, preserving the SHA, and tag the public repos with 1.4.2.
  * This publish is done using the standard release-builder pipeline (in public)

This is painful because we cannot allow any changes in public at this time, which blocks work. And, if a change somehow does land, it breaks the entire process and we cannot reverse it.

Even if we resolve the "SHA must match" requirement, this is still a problem. If in public we make change X and in private we make change Y, then our final merged repo will look like `old commits - X - Y`. However, the private build is not containing `X`. Therefor, we cannot actually tag anything in public - there is no point that makes sense to tag.

Proposed solution:
* In public, we continue as usually - no knowledge of private repo needed here at all.
* In private, we sync to 1.4.1 and apply patches. These patches are referenced by SHA in various repos (istio -> proxy -> envoy). Same as before
* Once the embargo is lifted, we directly push the patches to public to **a new branch**,`release-1.4.2` preserving SHA and tag this as 1.4.2
  * This can still be handled by the public release-builder. We will use the release-1.4 branch of release builder, where we just change the "publish" file from 1.4.1 to 1.4.2
* We then cherrypick these patches to release-1.4 branch, not preserving the SHA.
The end state:
release-1.4:  `old commits - X - Y`
release-1.4.2:  `old commits - Y`

For publishing

We make no future changes to the release-1.4.2 branch; 1.4.3 will be built from release-1.4 branch as usually. Like before, 1.4.3 will be a superset of 1.4.2, however it will NOT contain patches in the same linear ordering.

**Comment by ericvn** [comment]
Sounds acceptable to me.

**Comment by rlenglet** [comment]
So the bottom line is: one branch per patch release. I like that.

**Comment by rlenglet** [comment]
I agree with @ericvn that it might be confusing. How about we create one branch for every patch release, private or not?

**Comment by howardjohn** [comment]
If we do that we will quickly end up with 100s of branches. To me, the only benefit of doing that is consistency (public release is the same as private release), but there is no others? Or is there something I am not thinking of?

**Comment by rlenglet** [comment]
That's the only benefit I can think of.

**Comment by ericvn** [comment]
I'm fine with not doing them all. As I mentioned, I think it will become more common over time. We just may have more questions initially.

**Comment by howardjohn** [comment]
I think codifying this issue in the wiki or other place solves that issue. We do a lot more questionable things than this. For example, go look at the list of branches and you'll see like 30 random branches people have made

**Comment by ericvn** [comment]
One other item, is the I would hope the private builds limit the Y commits to a small number so the cherrypick should be easy to contain/automate.

**Comment by clarketm** [comment]
SGTM as well. A few thoughts...

> If we do that we will quickly end up with 100s of branches. To me, the only benefit of doing that is consistency (public release is the same as private release), but there is no others? Or is there something I am not thinking of?

If we want the extra branches but the excessive number of then is disconcerting, then we can prune old branches *after* they have served their purpose for the release. The reference(s) will live on via annotated git tag(s) anyway once the publish is complete. 

> We then cherrypick these patches to release-1.4 branch, not preserving the SHA.
The end state:
release-1.4: old commits - X - Y
release-1.4.2: old commits - Y

We have done a good job creating parity in the *private* test/build/release process thus far. In the near future, if we can streamline the *private* development process even further, then we can perform the publish from the *private* release-builder as well, then just cherry pick directly to `release-1.4` avoiding the intermediate branches in *public* altogether.

**Comment by howardjohn** [comment]
> If we want the extra branches but the excessive number of then is disconcerting, then we can prune old branches after they have served their purpose for the release. The reference(s) will live on via annotated git tag(s) anyway once the publish is complete.

That is great, I didn't realize that. So we can have "dangling" commits basically?

> We have done a good job creating parity in the private test/build/release process thus far. In the near future, if we can streamline the private development process even further, then we can perform the publish from the private release-builder, then just cherry pick directly to public release-1.4 - avoiding the intermediate branches in altogether.

The intermediate branch is not just about the release-builder. The publishing on 1.4.2 would be done by copying from private GCS to public GCS then doing the publish, which would then tag the SHAs on the `release-1.4.2` branch. But even if we did the publish privately, we still need to end up with some commit in public with the 1.4.2 tag

**Comment by howardjohn** [comment]
> One other item, is the I would hope the private builds limit the Y commits to a small number so the cherrypick should be easy to contain/automate.

Even if the private patches created 100 commits, we could squash these when merged to public if desired. That is, we would have 100 commits on the release-1.4.2 branch, but 1 commit from squashing the 100 on the release-1.4 branch. I don't think its a good idea, but it could be done.

**Comment by clarketm** [comment]
> That is great, I didn't realize that. So we can have "dangling" commits basically?

As long as there is a reference to the SHA (which will be the tag), we can safely prune the branches afterwards. A branch is just a reference to the SHA.

**NOTE**: also, I don't thing GitHub garbage collects SHAs anyways even if they are "dangling".

> The publishing on 1.4.2 would be done by copying from private GCS to public GCS then doing the publish, which would then tag the SHAs on the release-1.4.2 branch. But even if we did the publish privately, we still need to end up with some commit in public with the 1.4.2 tag

You are right, the *ordering* of my proposed steps is incorrect - and does not account for actually getting the `1.4.2` tag back to the *public* repos. I was assuming cherry-pick would do this but it will not preserve the SHA.

**Comment by howardjohn** [comment]
> From a git perspective, as long as there is a reference to the SHA (which will be the tag), we can safely prune the branches referencing it afterwards. After all, A branch is just a reference to a SHA.

Thats actually really good because we won't have branch protection so someone could just delete these easily, but the SHA will remain which is what is the important part. Of course we could also add branch protection.

**Comment by howardjohn** [comment]
I codified this in a design doc that should be more clear and will be documentation for future security patches: https://docs.google.com/document/d/19qf0-0GIopEZZWuG-lj8_VpyQF4N9nIKXiZgcJHwBRM/

**Comment by howardjohn** [comment]
implemented
