### ISSUE TITLE
Kiali does not show mTLS enabled for Egress Gateway with mTLS enabled task

### ISSUE THREAD

**Issue by nitishm** [istio/istio#19446]
**Bug description**
Following the steps for https://istio.io/docs/tasks/traffic-management/egress/egress-gateway/ with MeshPolicy mTLS enabled, kiali fails to show the lock icon (mTLS enabled) for traffic directed from the `sleep` app to the `istio-egressgateway`.
Plausible cause is that the way the Egress Gateway resource is setup, it does not use ISTIO_MUTUAL but instead uses TLS mode MUTUAL with the certificates params pointing to the citadel issued cert/key & cacert.
PS: Monitoring the traffic between the two pods, definitely shows the mTLS handshake happening so it is established that it actually uses mTLS on that link. So that is, therefore, not the issue and in the scope of this bug.

**Expected behavior**
Expected to see traffic between `sleep` and `istio-egressgateway` to display the mTLS enabled icon.

**Steps to reproduce the bug**
Follow instructions from https://istio.io/docs/tasks/traffic-management/egress/egress-gateway/ in istio-1.4.1

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
istioctl version --remote
client version: 1.4.1
control plane version: 1.4.1
data plane version: 1.4.1 (4 proxies)
```
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:29Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
```
helm version
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```
**How was Istio installed?**
https://istio.io/docs/reference/config/installation-options/

**Environment where bug was observed (cloud vendor, OS, etc)**
VMs

**Sleep --> Egress Gateway Traffic** (mTLS not displayed in the pane to the right)
![Screen Shot 2019-12-06 at 4 35 03 PM](https://user-images.githubusercontent.com/1494003/70358410-48b83d80-1847-11ea-873b-706fc518397e.png)

**Sleep --> httpbin** (mTLS icon displayed int he pane to the right)
![Screen Shot 2019-12-06 at 4 35 15 PM](https://user-images.githubusercontent.com/1494003/70358482-769d8200-1847-11ea-8fb2-11ffd546092b.png)

**Comment by jmazzitelli** [comment]
cc @jshaughn

**Comment by jshaughn** [comment]
Note that Kiali only shows lock icons for edges that don't comply to the global mTLS setting.  So, a closed lock for mTLS communication when global mTLS is not enabled, or an open lock for non-mTLS traffic when global mTLS is enabled.   This may not be the problem but I wanted to point out the approach.

The second thing is to ensure that the "security" display option is enabled.  It is not enabled by default, so check the Display drop down and make sure it's checked.  I can see in the images above that the Display dropdown is showing "6" enabled options, which is the default, so maybe that's the problem.

Other than that, Kiali typically just reflects the security_policy defined in the telemetry provide by Istio,  So the first thing to figure out is whether Istio is perhaps not reporting the security policy as expected.  You could look at Prometheus directly to check on that, let me know if you need help with that.

**Comment by nitishm** [comment]
@jshaughn 
- The global mTLS was enabled in this case.
- Security option was also enabled using the dropdown (included in the "6" options)
- I might need help with this task. What metric am I looking for in prometheus ?

**Comment by jshaughn** [comment]
So if global mTLS is enabled then I'm not sure you should expect to see a lock icon (because all traffic should have the mutual_tls security policy).

If you create a route for the Prometheus service then you should be able to get to the Prometheus UI via the generated host.
```
> oc expose service prometheus -n istio-system
> oc get routes
```
From there you can enter queries This:

`sum(istio_requests_total{reporter="source"}) by (connection_security_policy,destination_workload,source_workload)`

...would show you all of the requests time-series broken down by source and destination, and the security policy being reported.

One more tip:  If you go to the Graph Find text box you could enter `mTLS` and it will highlight all of the edges with mTLS, regardless of whether you see an icon due to the way kiali decides to show the un/lock icons based on the global policy.  You can also entry `!mTLS` to see the edges without mTLS.

**Comment by jshaughn** [comment]
@nitishm , any updates?

**Comment by nitishm** [comment]
@jshaughn I havent had a chance to test it out on 1.4 yet. On 1.1.11 it shows up as `unknown` in prometheus with your provided query for the egress gateway. 
I will update the issue with 1.4 when I get around to upgrading istio.
