### ISSUE TITLE
Upstream connect error or disconnect/reset before headers. reset reason: overflow

### ISSUE THREAD

**Issue by zhulinwei** [istio/istio#19454]
**Bug description**
One of my service return 503 status and the message `upstream connect error or disconnect/reset before headers. reset reason: overflow`

**Expected behavior**
Don't return  503 and respond normally.

**Steps to reproduce the bug**
I cannot reproduce this bug.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

istioctl version --remote
```
1.3.4
```
kubectl version
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.12-eks-c500e1", GitCommit:"c500e11584c323151d6ab17526d1ed7461e45b0c", GitTreeState:"clean", BuildDate:"2019-10-22T03:11:52Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
```
helm version
```
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
```
**How was Istio installed?**
helm

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS EKS

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

This service worked in the production environment for three days and 503 problem suddenly appears. After delete the pod of istio-ingressgateway, the service can work agagin.

**Comment by zhulinwei** [comment]
Does anyone know what caused the problem?

**Comment by ramaraochavali** [comment]
reset reason overflow generally indicates that circuit breaker has been triggered. Is this happening at higher concurrency?

**Comment by zhulinwei** [comment]
@ramaraochavali Just very low concurrency, the incoming request data from grafana was displayed in 30 ops per second.

**Comment by zhulinwei** [comment]
I can't find any helpful information, but I find `istio-telemetry` and `istio-policy` consume a lot of memory.
![grafana](https://raw.githubusercontent.com/zhulinwei/kubernetes/master/logging/other/images/Snipaste_2019-12-11_16-56-34.png)

**Comment by jaygorrell** [comment]
This was closed by the author with no resolution. Care to share your findings @zhulinwei?

**Comment by kish3007** [comment]
@zhulinwei care to share your findings on how you resolved this issue?

**Comment by zhulinwei** [comment]
> @zhulinwei care to share your findings on how you resolved this issue?

I can't do nothing but restart istio.

**Comment by kish3007** [comment]
i see, @zhulinwei so you restarted all the components in istio and the affected pods with their sidecar prxies too? Did u run into the overflow issue again after restart?

**Comment by kish3007** [comment]
Finally, I figured out whats happening in my environment, I am running istio 1.3.3 with eventhough global envoy circuit breaker setttings were 
`        "circuit_breakers": {
          "thresholds": [
            {
              "priority": "DEFAULT",
              "max_connections": 100000,
              "max_pending_requests": 100000,
              "max_requests": 100000
            },
            {
              "priority": "HIGH",
              "max_connections": 100000,
              "max_pending_requests": 100000,
              "max_requests": 100000
            }
          ]
        },`

These settings were overriden by Istio's destiantion rule which by default accroding to https://archive.istio.io/v1.3/docs/reference/config/networking/v1alpha3/destination-rule/#ConnectionPoolSettings-HTTPSettings
its 1024, which caused overflow errors. Updating these params will help if we are using Istio 1.3 or upgrading to 1.5 which has default of https://istio.io/docs/reference/config/networking/destination-rule/#ConnectionPoolSettings-HTTPSettings.
