### ISSUE TITLE
mTLS migration without service downtime

### ISSUE THREAD

**Issue by spikecurtis** [istio/istio#1946]
Allow operators to enable mTLS on services in the mesh without downtime.  This means that they can go from unencrypted service traffic to fully mTLS encrypted traffic with no application code changes and no downtime to the service.

[Design doc (see phase 2)](https://docs.google.com/document/d/1D7wZCQjVB72Wlwr5ZxP5WUmn3FUDr-XzfX8OodPXe8Y/edit#heading=h.nzoe9lkuyvsf)

**Comment by wattli** [comment]
This is a dup of https://github.com/istio/istio/issues/5059, closed
