### ISSUE TITLE
How to use private image repository?

### ISSUE THREAD

**Issue by lwx294821** [istio/istio#19468]
Before exec "istioctl manifest apply --set profile=demo",I had modified image hub to local registry. But when I check the pod status, k8s report cannot find image, because k8s try to pull from "docker.io", who can help me ?

**Comment by howardjohn** [comment]
Try `istioctl manifest apply --set profile=demo --set hub=my-registry.io`

**Comment by lwx294821** [comment]
The result is the same as before

**Comment by howardjohn** [comment]
Well what images are k8s trying to pull? and do those exist in your private
repo

**Comment by lwx294821** [comment]
k8s tries to pull the all images which istio needs ,but the related images already exist in my private repo

**Comment by howardjohn** [comment]
Which image exactly is it trying to pull? paste the yaml

**Comment by lwx294821** [comment]
docker.io/istio/kubectl:1.4.0
  docker.io/istio/install-cni:1.4.0
  docker.io/istio/node-agent-k8s:1.4.0
  docker.io/istio/proxyv2:1.4.0
  docker.io/istio/mixer:1.4.0
  quay.io/jetstack/cert-manager-controller:v0.8.1
  docker.io/istio/pilot:1.4.0
  docker.io/jaegertracing/all-in-one:1.14
  docker.io/openzipkin/zipkin:2.14.2
  pstauffer/curl:v1.0.3
  docker.io/prom/prometheus:v2.12.0
  docker.io/istio/galley:1.4.0 
  quay.io/kiali/kiali:v1.9
  docker.io/istio/sidecar_injector:1.4.0
  grafana/grafana:6.4.3
  docker.io/istio/citadel:1.4.0
  istio/coredns-plugin:0.2-istio-1.1
  coredns/coredns:1.6.2
  ubuntu:xenial


I try to install istio by "istioctl manifest apply --set profile=demo"

**Comment by lwx294821** [comment]
Maybe there is something wrong with my configuration file,I check it first. thank you all the same.

**Comment by johscheuer** [comment]
I can confirm that the command from above works (nearly) with setting the `HUB` variable the only part that won't work are some external images like Prometheus, Kiali and Jaeger (depending on your config) for there you have to set some additional variables. In your command the `--set hub=my-registry.io` argument is missing e.g.:

```bash
istioctl manifest generate --set profile=demo --set hub=my-registry.io | ag 'image: '
        image: my-registry.io/citadel:1.4.1
        image: my-registry.io/proxyv2:1.4.1
        image: my-registry.io/galley:1.4.1
          image: "grafana/grafana:6.4.3"
        image: my-registry.io/proxyv2:1.4.1
        image: my-registry.io/sidecar_injector:1.4.1
        image: "{{ .Values.global.proxy_init.image }}"
        image: "{{ .Values.global.hub }}/{{ .Values.global.proxy_init.image }}:{{ .Values.global.tag }}"
        image: "{{ .Values.global.proxy_init.image }}"
        image: "{{ .Values.global.hub }}/{{ .Values.global.proxy_init.image }}:{{ .Values.global.tag }}"
        image: "{{ annotation .ObjectMeta `sidecar.istio.io/proxyImage` .Values.global.proxy.image }}"
        image: "{{ .Values.global.hub }}/{{ .Values.global.proxy.image }}:{{ .Values.global.tag }}"
      - image: "quay.io/kiali/kiali:v1.9"
    image: pilot
        image: my-registry.io/pilot:1.4.1
        image: my-registry.io/mixer:1.4.1
          image: "docker.io/prom/prometheus:v2.12.0"
        image: my-registry.io/mixer:1.4.1
          image: "docker.io/jaegertracing/all-in-one:1.14"
```

**Comment by lwx294821** [comment]
Thank you very much , you have solved my problem. Does the cmd  'istioctl manifest apply --set profile=demo'  actually call the file 'istio-demo.yaml'?
