### ISSUE TITLE
Permission denied using telemetry v2 stackdriver

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#19469]
Proxy logs show

```
CreateTimeSeries request failed (1 RPCs, 8 views, 20 timeseries): PERMISSION_DENIED: Permission monitoring.timeSeries.create denied (or the resource may not exist).
```

I followed https://github.com/istio/proxy/blob/release-1.4/extensions/stackdriver/README.md. No steps there related to setting up permissions, so not sure where I went wrong.

**Comment by mandarjog** [comment]
Which project are you using ?are all the apis enabled when check on the pantheon APIs page?

**Comment by howardjohn** [comment]
This is in mixologist. I used the new cluster creation script, but I delete the service account that was created for an unrelated, so that is possibly the root cause? 

I was thinking this was a different cluster than the one with the deleted SA when I first posted but I got my two clusters mixed up

**Comment by howardjohn** [comment]
Adding the SA changes the error to

```
E1209 04:29:29.816806268     231 oauth2_credentials.cc:140]  Call to http server ended with error 404 ["The service account was not found. The instance must be restarted via the Compute Engine API to restore service account access."].
CreateTimeSeries request failed (1 RPCs, 8 views, 20 timeseries): UNAVAILABLE: Error occurred when fetching oauth2 token.
```

I guess this means I need to restart all the nodes.. will try that

**Comment by howardjohn** [comment]
Ok rebooting everything and recreating the SA fixed the issue.

I think no action needed, as this was user error and future mistakes will point to this issue with the fix
