### ISSUE TITLE
istioctl experimental upgrade does not work

### ISSUE THREAD

**Issue by kovalyukm** [istio/istio#19475]
**Bug description**
Cannot upgrade Istio from 1.4.0 to 1.4.1 via istioctl:

I downloaded new versio of istioctl and try to upgrade by running upgrade command:

$istioctl manifest versions

Operator version is 1.4.0.

The following installation package versions are recommended for use with this version of the operator:
  1.4.0

The following installation package versions are supported for upgrade by this version of the operator:
  >=1.3.3
   <1.6

$istioctl experimental upgrade -f ${overlay_file}
Client - istioctl version: 1.4.0

Error: the target version 1.4.1 is not supported by istioctl 1.4.0, please download istioctl 1.4.1 and run upgrade again

Please advise.

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istioctl version
client version: 1.4.1
control plane version: 1.4.0
data plane version: 1.4.0 (4 proxies), 1.3.2 (2 proxies)

**How was Istio installed?**
istioctl manifest apply -f ${overlay_file}

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS

**Comment by elfinhe** [comment]
I will debug this today. thanks.

**Comment by infa-ddeore** [comment]
any updates on this? currently we are in confusing situation since helm method will be deprecated so I chose istioctl method but now stuck because upgrade fails!

upgrade with istioctl fails from `1.4.0` --> `1.4.1` as well as `1.4.2`

**Comment by ostromart** [comment]
I believe you can still upgrade using --force. Could you verify that this works @elfinhe ? We need some kind of workaround asap for 1.4.2, even if this is fixed in 1.4.3.

**Comment by infa-ddeore** [comment]
upgrade works with `--force` option, thx for the workaround

**Comment by elfinhe** [comment]
I double checked that `--force` will work. working on a PR(https://github.com/istio/operator/pull/677) to fix this with forward compatibility.
