### ISSUE TITLE
There is no way to provide "tolerations" to Kiali and tracing components

### ISSUE THREAD

**Issue by nick4fake** [istio/istio#19480]
**Bug description**
There is no way to provide "tolerations" to Kiali component

Istio 1.4.1

I've tried the following:

- Specifying values.kiali.tolerations - doesn't work, there is no such field in spec. Check this file:
https://github.com/istio/operator/blob/9f96fae012485e3fbeeac88ca6b1ab4534f67dd7/pkg/apis/istio/v1alpha1/values_types.proto#L1791
BTW, this also means that documentation is wrong, as the field is there:
https://istio.io/docs/reference/config/installation-options/#kiali-options
- Specifying unvalidatedValues.kiali.tolerations via file - doesn't work, as all unvalidatedValues are ignored. Relevant PR for upgrade: https://github.com/istio/operator/pull/671
- Specifying unvalidatedValues.kiali.tolerations - via cmd - doesn't work, as complex values are not supported. Relevant issue: https://github.com/istio/istio/issues/19392
- Specifying through IstioControlPlane is impossible as there is no telemetry.kiali component

Looks like currently there are only three options:

- Deploying via Helm
- Deploying Kiali as a separate chart (not sure if it is possible)
- Adding additional tweak step to alter Kiali pod fields

**Comment by nick4fake** [comment]
Relevant issue:
https://github.com/istio/istio/issues/19398

**Comment by nick4fake** [comment]
Affects tracing too:
error: failed to generate manifest: input file failed validation with the following errors: unknown field \"tolerations\" in v1alpha1.TracingConfig

**Comment by richardwxn** [comment]
@nick4fake Please see my comment here: https://github.com/istio/istio/issues/19398#issuecomment-563390884. As I said, the reason why you feels like unvalidatedValues doesn't work is because there is even no tolerations defined in kiali and tracing deployment templates. E.g. https://github.com/istio/installer/blob/master/istio-telemetry/kiali/templates/deployment.yaml. I would add it to the templates and corresponding values part, should be available for 1.4.2

**Comment by nick4fake** [comment]
@richardwxn Thank you a lot.

Regarding comments in https://github.com/istio/installer/pull/601: this ticket is not only about "values" not fully covering legacy options. There don't seem to be any ways to specify these values through new API, as several components are not present there (Kiali and Jaeger being examples).

**Comment by nick4fake** [comment]
@richardwxn 
Another note:
 error: failed to generate manifest: input file failed validation with the following errors: unknown field \"defaultTolerations\" in v1alpha1.GlobalConfig\

Looks like values.global.defaultTolerations is also missing.

**Comment by howardjohn** [comment]
This is now provided via https://deploy-preview-7248--preliminary-istio.netlify.app/docs/setup/install/istioctl/#customize-kubernetes-settings. Thanks!
