### ISSUE TITLE
Fluent shortcuts for istioctl analyze use cases

### ISSUE THREAD

**Issue by sushicw** [istio/istio#19484]
As discussed in https://docs.google.com/document/d/1KuxDRPPt283jx_cIs2C9sFHjoHvoskJt3IGqhPJVHtM, we should have fluent subcommands as shortcuts for the most common use cases.

e.g. each of these pairs would be equivalent:

```
istioctl analyze a.yaml b.yaml
Istioctl analyze files a.yaml b.yaml # Explicitly disallows using --live

istioctl analyze --use-kube
istioctl analyze cluster             # Explicitly disallows local files

istioctl analyze --live a.yaml b.yaml
istioctl analyze cluster with-files a.yaml b.yaml # Requires files to be specified
```

**Comment by esnible** [comment]
@sushicw Has this been implemented?  May I close it?

**Comment by sushicw** [comment]
I don't believe this got implemented. We did refactor the command's basic usage enough that it may not still be relevant.
