### ISSUE TITLE
Authentication Policy

### ISSUE THREAD

**Issue by spikecurtis** [istio/istio#1948]
Goals:

 * Describe policy to support all authentication types: mTLS, TLS, JWT + mTLS, JWT + TLS, etc.
 * Describe policy to support service-to-service authentication, enduser-to-service authentication, and impersonation
 * Support incremental Istio authentication enablement

[WIP Proposal](https://docs.google.com/document/d/14Zqj5EAOYdy6GyBzXUo3txnVEapsnEC6-04pJD-QMwk/edit)

**Comment by diemtvu** [comment]
https://github.com/istio/api/pull/361

**Comment by diemtvu** [comment]
https://github.com/istio/api/pull/361

**Comment by diemtvu** [comment]
https://github.com/istio/api/pull/374

**Comment by wattli** [comment]
@diemtvu , this is the umbrella issue for auth policy, can we close it now?
