### ISSUE TITLE
Inconsistencies in IstioControlPlane YAML patching

### ISSUE THREAD

**Issue by ashlineldridge** [istio/istio#19483]
**Bug description**

As mentioned in https://github.com/istio/operator/pull/675, there appears to be an inconsistency between the YAML patching of objects vs arrays.

Arrays are treated as [append-only](https://github.com/istio/operator/blob/master/pkg/patch/patch.go#L68), whereas objects are treated as replace-only. The replace-only behavior for objects is demonstrated in [these passing tests](https://github.com/ashlineldridge/operator/commit/f328ff8c141d5ffb3f27d2cc7c6b6da962f586f3). This seems at odds with the [comment here](https://github.com/istio/operator/blob/master/pkg/patch/patch.go#L68) which indicates that objects should also be additive.

The current patching API (while still useful) seems incomplete as it's not possible to replace an array without individually deleting all elements first. Currently, it's not possible to augment an existing object. If the behavior was modified so that objects were also append-only, that would mean that it wouldn't be possible replace them. It feels like the patch API could use another keyword like, `operation: replace/append/delete`.

**Expected behavior**

I'd expect patching of objects to be additive like arrays. It would be nice to have more control over whether an operation adds or replaces.

**Steps to reproduce the bug**

See [tests](https://github.com/ashlineldridge/operator/commit/f328ff8c141d5ffb3f27d2cc7c6b6da962f586f3).

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

Istio version:

```
client version: 1.4.1
control plane version: 1.4.1
```

Kubectl version:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:34Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-eks-b7174d", GitCommit:"b7174db5ee0e30c94a0b9899c20ac980c0850fc8", GitTreeState:"clean", BuildDate:"2019-10-18T17:56:01Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
Downloaded from the GitHub releases page.

**Environment where bug was observed (cloud vendor, OS, etc)**
On macOS 10.14.6.

**Comment by howardjohn** [comment]
@ostromart made some changes here, this might actually be possible now -- not 100% sure
