### ISSUE TITLE
Add support for istioctl -ojsonpath 

### ISSUE THREAD

**Issue by incfly** [istio/istio#19485]
**Describe the feature request**

This is helpful when we only need partial of the listener/cluster config from the config dump.

```shell
istioctl pc cluster -ojsonpath='items[?(@.name=="outbound||httpbin.svc.cluster.local")]
```

**Comment by esnible** [comment]
As a work-around I've used `jq`.  For example:

```
istioctl pc cluster details-v1-875c6d75d-ghpf4 -ojson | jq '.[] | select(.name=="zipkin")'
```

Do you think it would be worthwhile to bring in k8s.io/client-go/util/jsonpath ?  I am not sure I want to write the docs/examples for using it....

**Comment by howardjohn** [comment]
Related https://github.com/istio/istio/issues/19927

**Comment by incfly** [comment]
jq works for me personally, the downside is that people need to be aware of
that, install etc. I guess we don't have to write json path if we support
that. At most link to somewhere else?
