### ISSUE TITLE
Remove cert-manager from Istio

### ISSUE THREAD

**Issue by KadenLNelson** [istio/istio#19493]
**Describe the feature request**

cert-manager's latest release is `v0.12.0`, it would be nice to have Istio's cert-manager, which is at `v0.8.1`, upgraded to the latest cert-manager release.

**Describe alternatives you've considered**

N/A

**Additional context**

**Comment by howardjohn** [comment]
We likely won't do this. All of our documentation points users to the upstream cert manager installation now.

We don't have any special integrations with certmanager, and we don't have the bandwidth to maintain a certmanager installation fork as we have been doing. It makes more sense for users to use certmanagers instructions, which are certainly better than ours

**Comment by KadenLNelson** [comment]
> We likely won't do this. All of our documentation points users to the upstream cert manager installation now.
> 
> We don't have any special integrations with certmanager, and we don't have the bandwidth to maintain a certmanager installation fork as we have been doing. It makes more sense for users to use certmanagers instructions, which are certainly better than ours

Okay, makes sense. If there's no special integrations, then maybe this issue could be renamed `remove cert-mananger from Istio`?

**Comment by howardjohn** [comment]
That sounds reasonable. We did a pretty soft deprecation of certmanager - I don't think we even announced the change, we just updated the docs to not refer our certmanager component at all. Maybe we should have been more explicit

**Comment by KadenLNelson** [comment]
> That sounds reasonable. We did a pretty soft deprecation of certmanager - I don't think we even announced the change, we just updated the docs to not refer our certmanager component at all. Maybe we should have been more explicit

So what other Istio components does cert-manager need to be removed from? I noticed there's references of it in the `operator` repository.

**Comment by wickedev** [comment]
`apiVersion: certmanager.k8s.io/v1alpha1` in the sample code in the link below is no longer valid after cert-manager 0.11.0. must update the document to the latest version of cert-manager.

[getting-a-let-s-encrypt-certificate-issued-using-cert-manager](https://istio.io/docs/tasks/traffic-management/ingress/ingress-certmgr/#getting-a-let-s-encrypt-certificate-issued-using-cert-manager)

[cert-manager upgrading-0.10-0.11/additional-annotation-changes](https://cert-manager.io/docs/installation/upgrading/upgrading-0.10-0.11/#additional-annotation-changes)

**Comment by ericvn** [comment]
https://github.com/istio/istio.io/pull/6377 has updates for cert-manager version.

**Comment by KadenLNelson** [comment]
I'm closing this issue because https://github.com/istio/istio.io/pull/6377 has been merged to update the Istio cert manager version.
