### ISSUE TITLE
Enforce control plane security when auto mTLS is enabled by default

### ISSUE THREAD

**Issue by incfly** [istio/istio#19494]
**Describe the feature request**

One feedback we got is to always enforce control plane security when (mtls between sidecar and pilot) when data plane has auto mTLS enabled.

Both options become default true in 1.5 release. We just need to add a validation logic in the `istio/operator` repo to reject or print out a warning message when the combination when control_plane_security == false && global.mtls.auto == false.

Long term, we should even consider deprecate this control plane security as an option.

@ostromart @richardwxn let me know if you think differently, otherwise, this should be a PR against [`validation.go`](https://github.com/istio/operator/blob/e31e0d72a8ba9deec34a49411d944f399430d019/pkg/validate/validate.go) if I understand correctly.

**Describe alternatives you've considered**

Alternative is to modify the Helm charts, replacing all the `{{ if values.ControlPlaneSecurity.Enabled }}` with `{{ if values.ControlPlaneSecurity.Enabled || values.global.mtls.auto  }}`, this will result into lots of mess in the code, ControlPlaneSecurity is referenced in many places.

https://github.com/istio/installer/search?q=controlPlaneSecurityEnabled&unscoped_q=controlPlaneSecurityEnabled

**Additional context**

**Comment by sdake** [comment]
I have long wondered why we don’t default to security enabled in all cases.

**Comment by incfly** [comment]
At some point we deliver data plane sds but not control plane. The flag
release the constraint to release that.

But now all the installations support control plane mtls, except
security.enabled==false, which is not installing citadel.

But we should that make better defaults in both cases rather than exposing
control plane security as a option

**Comment by richardwxn** [comment]
I think it would be good to put in validation.go, actually we have been thinking scenario that requires more validation than just schema check, so this case would be an example
