### ISSUE TITLE
Webhook ownerRef may cause issues with istiod

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#19504]
See https://github.com/istio/istio/pull/19476/files#r356298037

We are explicitly looking for an "istio-galley" cluster role to set the owner ref to. This means we still need this role with istiod

Seems like we may want to stop generating the webhook in galley entirely as the real fix though.. the operator should manage the lifecycle, which I believe is being worked on.

cc @morvencao @costinm

**Comment by ayj** [comment]
Galley and istio no longer create the webhook config anymore. We also don't use ownerRef for cleanup. No trickery. The config is in the charts like all of our other config.
