### ISSUE TITLE
Improve/Replace/Remove --discovery in `istioctl analyze`

### ISSUE THREAD

**Issue by sushicw** [istio/istio#19502]
The current `--discovery` flag for `istioctl analyze` is hard to use correctly and awkwardly named. It currently acts as a flag for whether or not to pay attention to Kubernetes (non-CRD) resources, including skipping over analyzers that depend on those resources. It defaults to the value of `--use-kube`, which in practice means that unless the user specifies otherwise any analyzers that look at kube resources (e.g. checking to see if a host exists for a service) only run with --use-kube enabled. So if a user ran `istioctl analyze` against file(s) containing VirtualService and Service entries, hoping to validate that the virtual services point to valid hosts, the analyzer wouldn't even run unless they included `--discovery`. Running with `--verbose` at least makes it somewhat clear that this is happening, but I think we can do a bit better.

Proposed changes:
1. Rename `--discovery` to `--include-kube-resources`. This simply improves the naming so it's more obvious what's going on. Specifying this would continue to force the behavior to include / exclude all kube resources, regardless of whether `--use-kube` is also set. 
2. ~If `--include-kube-resources` isn't specified, start by assuming the value of `--use-kube` (the current behavior), but additionally mark any resource types mentioned at least once in the input files as enabled.~ **EDIT: Currently favoring 2c over this**

Alternatives to consider:
2b. Don't have a separate flag and always just use the behavior described in point 2 above. We may be adding a confusing knob where it's not really needed.
2c. Like 2b, but add CLI options to override and specify resources to analyze. e.g. istioctl analyze --include-resources=virtualservices,gateways,services,<files...> would skip any analyzers that required resources outside that set. Probably with a dual --exclude-resources as well.

**Comment by sushicw** [comment]
@esnible @zerobfd @selmanj @davidebbo PTAL and let me know what you think. Happy to discuss it in the UX working group meeting if it would be helpful to do so.

**Comment by selmanj** [comment]
What use cases does alternative 2b exclude? To me it sounds like the best solution.

**Comment by sushicw** [comment]
> What use cases does alternative 2b exclude? To me it sounds like the best solution.

That's exactly the question I'm asking myself. So far, I've not coming up with any use cases that feel convincing, especially in light of our plans to add granular per-analyzer controls (https://github.com/istio/istio/issues/17443). Having those more granular controls makes this coarse all-kube-resources-or-nothing switch feel pretty redundant.

**Comment by zerobfd** [comment]
I vote yes on 1 and 2b. Why do we have a switch to ignore kube resources at all? Is there ever a downside from looking at them?

**Comment by howardjohn** [comment]
At the very least it should be opt-out not opt-in I think

**Comment by xeviknal** [comment]
IMO, I think it would be easier for users if there only could be one flag. At the end, I think, users want to know if their new configs/config updates are going to be valid in their service mesh.

> At the very least it should be opt-out not opt-in I think

I think that is also a good idea. Instead of making users add `-k` to analyze against the cluster, there could be a flag for preventing it and only analyze input resources.
In case you have the granular per-analyzer controls, then you are totally tight to the needs of the executed analyzers .

**Comment by sushicw** [comment]
> I vote yes on 1 and 2b. Why do we have a switch to ignore kube resources at all? Is there ever a downside from looking at them?

The background here is that these are both user stories for the files-only case:
* I want to analyze my Istio files, and not get false positives because I didn't include kube resource files as well.
* I want to analyze my Istio files and kube resource files together.

In the former case, we want to disable analyzers that would look for kube resources, but in the latter case we expect those resources to be there and want to keep them enabled so we get validation messages if something is misconfigured. 

Put another way: we need to be able to handle both "this stuff is missing because I didn't include it in the set of files to analyze" and "this stuff is missing because the config is broken."

Proposal 1 is simply about renaming the existing flag to better match the actual & intended behavior.
Proposal 2 is about making the default behavior a bit smarter, so that the user doesn't have to manually specify which files-only use case they're trying to accomplish. 
Proposal 2b wonders if 2 is smart enough that we can drop the manual override entirely, especially in light of other (more fine-grained) knobs that we plan to add to suppress messages and/or skip analyzers.

Another option (call it 2c) would be to make the option a list of resources to analyze that overrides the default assumptions. e.g. `istioctl analyze --include-kube-resources=virtualservices,gateways,services,<files...>` would skip any analyzers that required resources outside that set. Possibly with a dual `--exclude-kube-resources` as well. @selmanj I wonder if this would actually be more accessible and useful to users than per-analyzer controls.

**Comment by esnible** [comment]
I struggled with `--discovery` when I was writing the analyzer for Istio annotations on Pods etc.  I'd like to see `--discovery` **DEFAULT** to `true`.  It is much easier to figure out what is going on when there are too many resources being checked instead of two few.

I had a report today from a skilled user that is related.  He expected the default of `--use-kube` to be true and didn't understand why his live cluster Gateway was not seen.  Should we reconsider the default for `--use-kube` as well?  I suspect most users are interactive users.  Users trying to author rules without a live cluster and pipelines are the more advanced (non-default) case.

**Comment by sushicw** [comment]
This overlaps with https://github.com/istio/istio/issues/18932

**Comment by sushicw** [comment]
Specific points to discuss in the next UXWG meeting:
* Clarify what is meant by "included resources" and how it affects which analyzers are run
* Get rid of --discovery in favor of smarter defaults? (Include everything for live clusters, include every kind with at least one specified entry in the file set for files-only). 
* Implement per-resource include/exclude controls to handle edge cases?
* Should --use-kube be true by default?

**Comment by sushicw** [comment]
Summary from 12/17/19 UX WG meeting:

* Let's get rid of `--discovery` entirely. It's confusing and unnecessary.
* Let's *not* make the default behavior smarter, and instead just have all resources included by default. 
* We'll rely on message suppression (WIP by @selmanj) and per-resource controls (https://github.com/istio/istio/issues/18932) to handle the advanced files-only cases.
* Let's make `--use-kube` true by default.
* For the CLI args for per-resource controls, use require/ignore instead of include/exclude language (it's clearer)

So, remaining action items before closing this issue:
* [ ] Update https://github.com/istio/istio/issues/19502 to reflect that we don't want to have "smarter" default resource selection, just the explicit controls, and that we want to use "require/ignore"
* [ ] Remove `--discovery`
* [ ] Make `--use-kube` true by default
