### ISSUE TITLE
mesh-ex sample failed

### ISSUE THREAD

**Issue by minchieh2014** [istio/istio#19518]
**Describe the feature request**
 easy deploy by https://istio.io/docs/examples/virtual-machines/single-network/ 

**Describe alternatives you've considered**
1. i have no gcloud of docs, mush command with 'gcloud' not easy for help my action , i have machines what created by kvm 
2. docs says download pag https://storage.googleapis.com/istio-release/releases/1.4.1/deb/istio-sidecar.deb , em, my kvm's OS is centos7.5, where is rpm pag? I find it any where, but no.

**Additional context**

**Comment by johscheuer** [comment]
It seems like the rpm are not published currently: https://gcsweb.istio.io/gcs/istio-release/releases/1.4.2/ only the debian packages. You should be able to build the rpm packages by yourself until the rpm packages are published officially (see: https://github.com/istio/istio/tree/master/tools/packaging/rpm).

Most `gcloud` commands should be exchangeable with the according command for kvm (or not required with kvm). Running a complete Service Mesh + an extra VM requires a quite beefy machine.

**Comment by howardjohn** [comment]
We are tracking shipping RPMs in https://github.com/istio/istio/issues/9117. Lets continue discussion there .Thanks!
