### ISSUE TITLE
can't set password for redis protocol

### ISSUE THREAD

**Issue by maplebeats** [istio/istio#19514]
**Bug description**

see:
https://discuss.istio.io/t/how-to-set-password-to-a-redis-serviceentry/4623

when I use redis protocol，I can't use the password for the redis.
by the way，if I wanted set pool size, it wouldn't works either。
is there a way to add special parameters for others protocols？

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by AsCat** [comment]
I think this is not a bug but should be a feature request. 
The problem is that where can we store and read the redis password in istio for the redis servcie，Can someone give some advice? I can take this featue.

**Comment by maplebeats** [comment]
> 
> 
> I think this is not a bug but should be a feature request.
> The problem is that where can we store and read the redis password in istio for the redis servcie，Can someone give some advice? I can take this featue.
can we add a new config fields in serivceEntry for each protocol?
