### ISSUE TITLE
Turn off Istio gateway core dumps

### ISSUE THREAD

**Issue by mg03** [istio/istio#19522]
**Bug description**
Deployed istio gateway and set enableCoreDump to false
But still istio gateway container istio-proxy shows core.xxx files being generated

**Expected behavior**
No core dumps to be visible if enableCoreDump value is set to false

**Steps to reproduce the bug**
Install istio gateway and set enableCoreDump: false

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istio version 1.3.5
kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-eks-b7174d", GitCommit:"b7174db5ee0e30c94a0b9899c20ac980c0850fc8", GitTreeState:"clean", BuildDate:"2019-10-18T17:56:01Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
Generated the files via helm which was then applied using kubectl apply -f 

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS EKS

**Comment by mg03** [comment]
@hzxuzhonghu 
hi any update on this ? the coredumps are filing up the disk on the nodes where istio-ingressgateway nodes are running. This is causing production issue for us.

**Comment by bianpengyuan** [comment]
cc @richardwxn

**Comment by mg03** [comment]
@richardwxn : any updates ?

**Comment by richardwxn** [comment]
@mg03 Actually the enableCoreDump is set to false as default. Did you run any other command to turn on coredump before? And how did you install the istio gateway?

**Comment by mg03** [comment]
@richardwxn : No we did not run any command to enable coredump. The istio files were generated from the istio repo using helm. 
```
helm template install/kubernetes/helm/istio-init --name istio-init --set certmanager.enabled=true --namespace istio-system > 01-crd.yaml
```

```
helm template install/kubernetes/helm/istio --name istio --namespace istio-system --values install/kubernetes/helm/istio/values-istio-sds-auth.yaml \
  --set certmanager.enabled=true \
  --set certmanager.replicaCount=2 \
  --set values.sidecarInjectorWebhook.rewriteAppHTTPProbe=true \
  --set values.global.proxy.accessLogFile="/dev/stdout" \
  --set galley.replicaCount=2 \
  --set pilot.autoscaleMin=2 \
  --set mixer.policy.autoscaleMin=2 \
  --set mixer.telemetry.autoscaleMin=2 \
  --set sidecarInjectorWebhook.replicaCount=2 \
  --set security.workloadCertTtl=1h \
  --set global.outboundTrafficPolicy.mode=REGISTRY_ONLY \
  --set grafana.enabled=true \
  --set gateways.istio-ingressgateway.loadBalancerSourceRanges="{0.0.0.0/0}" \
  --set gateways.istio-ingressgateway.serviceAnnotations."service\.beta\.kubernetes\.io/aws-load-balancer-type"="nlb" \
  --set gateways.istio-ingressgateway-restricted.loadBalancerSourceRanges="{5.21.10.75/32,10.0.0.0/14,10.5.0.0/16}" \
  --set gateways.istio-ingressgateway-restricted.serviceAnnotations."service\.beta\.kubernetes\.io/aws-load-balancer-type"="nlb" \
  --set gateways.istio-ingressgateway-private.loadBalancerSourceRanges="{5.21.10.75/32,10.0.0.0/14,10.5.0.0/16}" \
  --set gateways.istio-ingressgateway-private.serviceAnnotations."service\.beta\.kubernetes\.io/aws-load-balancer-type"="nlb" \
  > 02-istio-sds.yaml
```

Applied the above yaml files.

Attaching 01-crd.yam and 02-istio-sds.yaml as txt files
[01-crd.yaml.txt](https://github.com/istio/istio/files/4031748/01-crd.yaml.txt)

[02-istio-sds.yaml.txt](https://github.com/istio/istio/files/4031756/02-istio-sds.yaml.txt)

**Comment by richardwxn** [comment]
From the yaml files you attached, the enabledCoreDump is set to false actually. Can you check the enabledCoreDump value from configmap used by sidecar injector by ```kubectl get configmap istio-sidecar-injector -n istio-system -o yaml```.  Also can you restart the ingressgateway pod to see whether newly injected proxy container still have core dump enabled?

**Comment by mg03** [comment]
@richardwxn :   Checked the configmap as per the command you provided. The enableCoreDump value is false. See attached file.

Before checking the cm , an ingress gateway pod as example
```
root@istio-ingressgateway-596b5857f7-bs9qw:/# ls
bin        core.1597  core.2381  core.3165  core.3949  core.476   core.588  lib64                         sbin
boot       core.1709  core.2493  core.3277  core.4061  core.4845  core.700  media                         srv
core.1036  core.1821  core.251   core.3389  core.4173  core.4957  core.812  metadata_exchange_1_3_1.wasm  stats_1_3_1.wasm
core.1148  core.1933  core.2605  core.3501  core.4285  core.5069  core.924  mnt                           sys
core.1260  core.20    core.2717  core.3613  core.4397  core.5181  dev       opt                           tmp
core.137   core.2045  core.2829  core.363   core.4509  core.5293  etc       proc                          usr
core.1372  core.2157  core.2941  core.3725  core.4621  core.5405  home      root                          var
core.1484  core.2269  core.3053  core.3837  core.4733  core.5517  lib       run

As you can see coredumps are generated
```

I destroyed the pod. A new one showed up .

istio-ingressgateway-596b5857f7-h42wq              2/2     Running     0          47m

```
kubectl -n istio-system exec -it istio-ingressgateway-596b5857f7-h42wq -c istio-proxy bash
root@istio-ingressgateway-596b5857f7-h42wq:/# ls -ltr
total 241380
drwxr-xr-x   2 root root         6 Apr 12  2016 boot
drwxr-xr-x   1 root root        19 Jul 20 13:50 usr
drwxr-xr-x   2 root root         6 Jul 20 13:50 srv
drwxr-xr-x   2 root root         6 Jul 20 13:50 opt
drwxr-xr-x   2 root root         6 Jul 20 13:50 mnt
drwxr-xr-x   2 root root         6 Jul 20 13:50 media
drwxr-xr-x   2 root root        34 Jul 20 13:50 lib64
drwxr-xr-x   1 root root        17 Jul 20 13:51 var
drwxr-xr-x   1 root root        45 Aug 30 15:32 lib
drwxr-xr-x   1 root root       112 Aug 30 15:32 bin
drwxrwxrwt   1 root root         6 Aug 30 15:32 tmp
drwxr-xr-x   1 root root      4096 Aug 30 15:32 sbin
-rw-r--r--   1 root root   1456127 Oct  3 07:10 stats_1_3_1.wasm
-rw-r--r--   1 root root   1087147 Oct  3 07:10 metadata_exchange_1_3_1.wasm
drwxr-xr-x   1 root root        25 Oct  3 07:10 home
dr-xr-xr-x 242 root root         0 Jan  9 18:09 proc
drwxr-xr-x   1 root root        32 Jan  9 18:09 etc
drwxr-xr-x   1 root root        55 Jan  9 18:09 run
drwxr-xr-x   5 root root       360 Jan  9 18:09 dev
drwx------   1 root root        27 Jan  9 18:10 root
-rw-------   1 root root 387104768 Jan  9 18:33 core.21
dr-xr-xr-x  13 root root         0 Jan  9 18:54 sys
-rw-------   1 root root 389197824 Jan  9 19:04 core.194
-rw-------   1 root root 386121728 Jan  9 19:34 core.375

```

As you can see coredumps are still being generated.



[configmap.yaml.txt](https://github.com/istio/istio/files/4042328/configmap.yaml.txt)

**Comment by howardjohn** [comment]
The "enable coredump" setting just tweaks some system settings on the node to allow coredumps. If you already have those set, then the cores will be dump

**Comment by mg03** [comment]
@howardjohn : the system has ulimit core dump setting to 0. So it should not create core dumps.

**Comment by howardjohn** [comment]
if you check on a running pod, is it the same?

**Comment by mg03** [comment]
on the running pod, the ulimit is not 0 by default.  As a workaround, we added ulimit -c 0 to the start command of the gateway pod.

**Comment by howardjohn** [comment]
I think the default is set by the k8s environment/nodes, not something Istio controls?

**Comment by howardjohn** [comment]
As mentioned above, I don't think this is caused by Istio and is based on your k8s setup. If thats not the case, please reopen
