### ISSUE TITLE
Use distroless/cc-debian10 for proxyv2

### ISSUE THREAD

**Issue by deissnerk** [istio/istio#19531]
**Bug description**
The image for proxyv2 that is based on distroless, uses a base image that is still using **Debian 9**:
https://github.com/istio/istio/blob/ca443457122c5738aace64c1b4c732411c726078/pilot/docker/Dockerfile.proxyv2#L20

The Distroless project recommends explicitly specifying the base OS version in image names:
https://github.com/GoogleContainerTools/distroless#base-operating-system

Would it be possible to use Debian 10 instead? This might depend on https://github.com/GoogleContainerTools/distroless/issues/436
Currently there is no `distroless/cc-debian10` that is tagged as `latest`

**Expected behavior**
Use **Debian 10** for istio/proxyv2 to get a more recent version of glibc (2.28 instead of 2.24)

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.4.2

**How was Istio installed?**
I did not install it. I just scanned the image.

**Comment by Henrike42** [comment]
Is there any progress regarding this issue?

**Comment by howardjohn** [comment]
Seems reasonable, I am curious what the motivation is though?

```
$ dk run istio/base:1.4-dev.7 cat /etc/debian_version
buster/sid
```

Current non distroless images are already based on debian10 so seems reasonable. Would be welcome to see a PR, seems like its mostly about sending a tiny PR and testing it works

**Comment by jronak** [comment]
Hi @howardjohn 
I would like to work on a pr for this issue, I have couple of questions:
- should this pr change distroless debian-10 base image for all the components or just pilot?
- which version of distroless debian-10 base image version should I use as the current distroless baseimage is tagged to a specific version?

**Comment by howardjohn** [comment]
I think we should use the latest one, unless they have a "Stable" version. We should tag it to that specific version to be reproducible though

It should be the same for all components

**Comment by jronak** [comment]
@deissnerk pr for this change has been merged, you could close this issue 🎉

**Comment by howardjohn** [comment]
thanks!

**Comment by christian-vent** [comment]
@deissnerk @jronak @howardjohn did this PR #24564 really resolve this ticket? We scanned the istio/proxyv2:distroles-1.7.3 image and found vulnerabilities that are related to glibc 2.24 and were fixed in glibc 2.28. Pilot and operator did not contain the findings.

**Comment by jronak** [comment]
I don't think the commits from the PR were cherry-picked into the release

**Comment by christian-vent** [comment]
@jronak do you know when this change will be released?
