### ISSUE TITLE
Single control plane / Single network multi-cluster setup instructions not correct

### ISSUE THREAD

**Issue by rolandkool** [istio/istio#19546]
**Bug description**
The instructions for setting up a multi-cluster setup using a single network as described here ( https://istio.io/docs/setup/install/multicluster/shared-vpn/) are no longer correct for Istio 1.4.

The steps for generating the secret for the remote cluster to be put in the control plane clusters are incorrect. There is a reference to a service account called `istio-reader-service-account`, however when using the helm based installer, this service account is not provisioned so it doesn't exist. In 1.3, the service account `istio-multi` was used. Looking at the installation files provided in the tar ball, this new service account is only provisioned using the operator.

**Expected behavior**
Instructions should be correct for both installers

**Steps to reproduce the bug**
Follow the docs, but use the helm based installer

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.4.1

**How was Istio installed?**
Using helm

**Environment where bug was observed (cloud vendor, OS, etc)**
On GKE 1.14. Also testing with Anthos Managed CA

**Comment by hzxuzhonghu** [comment]
@vadimeisenbergibm
