### ISSUE TITLE
X-Envoy headers not overriding rules set by VirtualService

### ISSUE THREAD

**Issue by vladg9** [istio/istio#19550]
**Bug description**

Retry and timeout policies specified by VirtualService can't be overridden using X-Envoy headers (https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/router_filter#http-headers-consumed).

**Expected behavior**

Coming from Istio's docs (https://istio.io/docs/tasks/traffic-management/request-timeouts/):

```One more thing to note about timeouts in Istio is that in addition to overriding them in route rules, as you did in this task, they can also be overridden on a per-request basis if the application adds an x-envoy-upstream-rq-timeout-ms header on outbound requests. In the header, the timeout is specified in milliseconds instead of seconds.```

**Steps to reproduce the bug**

Deploy a service and make it pause for 1 second after receiving a request, add a VirtualService specifying timeout of 0.5seconds, make a request and add X-Envoy header for increasing the timeout to 2 seconds and the response should be a success. However, the headers are not respected and still timeouts at 0.5 seconds.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

client version: 1.4.0
control plane version: 1.3.3
data plane version: 1.3.3 (72 proxies)

Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:26:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.6", GitCommit:"ab91afd7062d4240e95e51ac00a18bd58fddd365", GitTreeState:"clean", BuildDate:"2019-02-26T12:49:28Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**

Using `helm template`.

**Environment where bug was observed (cloud vendor, OS, etc)**

Minikube and Kube cluster on AWS.

**Comment by Dev25** [comment]
Related issue https://github.com/istio/istio/issues/14923

This would be super useful to have, especially for dealing with workloads talking to external/3rd party services and not having to deal with workarounds/creating complex VirtualServices before hand

e.g. watch out for a specific header (can't be `x-envoy-` since they get discarded) to indicate its safe to retry a specific POST request, then factor in different timeout config overhead etc

**Comment by Dev25** [comment]
As per a recent post on  [discuss.istio.io](https://discuss.istio.io/t/overridding-vs-rules/5033)  it looks like this is now protected by a pilot env flag `PILOT_SIDECAR_USE_REMOTE_ADDRESS` and was [changed](https://github.com/istio/istio/pull/15167/files) for Istio 1.2+

I've confirmed that setting that flag now allows workloads to tweak envoy behaviour via headers.

**Comment by vladg9** [comment]
Closing the issue as the suggested action above has resolved the problem

**Comment by easylei** [comment]
hello, i have some issue seems quite like your's.
i'm using istio
my services are in same mesh and same namespace. i'm trying to control retry behavier by letting my client send x-envoy headers
x-envoy-attempt-count=3,  x-envoy-upstream-rq-per-try-timeout-ms=100. 
the istio did no try, nor timeout. and my server did not receive  these headers.
