### ISSUE TITLE
common-tests not running full tests (impact: no iptables tests)

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#19559]
Our makefile has these rules:

```
.PHONY: common-test
common-test: build
 	go test ${T} ./pkg/...
	go test ${T} ./tests/common/...
	# Execute bash shell unit tests scripts
	./tests/scripts/scripts_test.sh
	./tests/scripts/istio-iptables-test.sh

.PHONY: common-racetest
common-racetest:
	RACE_TEST=true go test ${T} -race ./pkg/...
```

common-racetest is run in CI, NOT common-test. So we are missing the scripts tests. 

I would just submit a PR but the iptables test actually fails which I am not sure how to resolve.

**Comment by abhide** [comment]
@howardjohn will take a look and push a PR

**Comment by abhide** [comment]
@howardjohn pushed a PR. 
You are suggesting we move istio-iptables tests to `common-racetest`?

**Comment by howardjohn** [comment]
Yes I think that's reasonable. Later the tests can probably be all golang code. Even if it's a script we should probably have go code shell out to it so `go test` runs everything

**Comment by abhide** [comment]
I would like to keep this test to have coverage for `--restore-format=false` flag.
I will send out another PR to move these tests to `common-racetest`.

**Comment by abhide** [comment]
@howardjohn PR: https://github.com/istio/istio/pull/19657 to run the test as part of `common-racetest`

**Comment by abhide** [comment]
Verified that tests are executing as part of `unit-tests` job. 

Closing issue.
