### ISSUE TITLE
Possible future enhancement: control sidecar injection through Sidecar CRD (or similar)

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#19555]
Right now sidecar injection is controlled through mesh config + values.yaml. There is no (well supported) way to have different injection for different workloads.

The current plan of action for control plane traffic shifting was to specify the injection as part of namespace label and/or workload label.

An alternative idea is to instead control injection through a resource, likely the Sidecar. In this config, you can specify things like which control plane to use, CPU/memory, etc etc.

Using inheritance that the CRD already provides ,you can have global values, namespace level values, and workload level.

Overall its a lot more k8s-native experience than labeling a namespace.

One challenge here for using for control plane traffic shifting is we cannot use Sidecar to determine which injector to use, only *how* it is used

cc @costinm @sdake @ostromart

**Comment by ayj** [comment]
We do allow per-field annotation overrides on the workload but that can be ad-hoc. One idea we floated a while back was to be able to select the entire template via a single workload annotation.

That would allow sidecar customizations to be grouped by name and allow deployments to reference that named group, e.g. via the annotation. This is an extension of our current annotation override scheme and allows the entire template to be selectively overridden by the user. It enables pinning a deployment to a particular sidecar version (list of containers and volumes). See https://gist.github.com/ayj/5ee2c91832973ea222f0f54350671e53 for an straw-man demonstrating the idea. 

Upgrading a sidecar might look like the following where `<sidecar-version>` corresponds to one of the sidecar/template CRs.

```bash
kubectl patch deployment foo -p "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"<sidecar-version>\"}}}}}"
```
