### ISSUE TITLE
make init fail for 1.4.2

### ISSUE THREAD

**Issue by kramvan1** [istio/istio#19556]
**Bug description**

clone 1.4.2
`make init`
```
make init
20:19:31 Building with your local toolchain.
20:19:31 ISTIO_OUT=/app/workspace/out/linux_amd64/release bin/init.sh
20:19:31 /app/workspace/out/linux_amd64/debug /app/workspace/src/istio.io/istio
20:19:31 Downloading Envoy: curl -fLSs https://storage.googleapis.com/istio-build/proxy/envoy-debug-a7b2578494d79fe098f0e99282e0236946562fa0.tar.gz to /app/workspace/out/linux_amd64/debug/envoy-debug-a7b2578494d79fe098f0e99282e0236946562fa0
20:19:31 curl: (22) The requested URL returned error: 404 
20:19:31 
20:19:31 gzip: stdin: unexpected end of file
20:19:31 tar: Child returned status 1
20:19:31 tar: Error is not recoverable: exiting now
```

**Expected behavior**

Can run make init sucessfully

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

1.4.2

**How was Istio installed?**

no install needed

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by kramvan1** [comment]
cc @linsun

**Comment by ericvn** [comment]
@howardjohn @kramvan1 is using the SHA from the secure 1.4.2 branch. Does it point to the `private` copy that was available early for our builds and not one that is actually available?

**Comment by howardjohn** [comment]
Ah yes. Good catch. We will likely need to amend the private release process to include copying the envoy binary to GCS. This was our first time doing this process, so we just missed this

**Comment by howardjohn** [comment]
Should be fixed now. Thanks

**Comment by kramvan1** [comment]
The download is working now, will continue with the testing, thx!
