### ISSUE TITLE
How to log istio access logs to fluentd with tags?

### ISSUE THREAD

**Issue by hillbun** [istio/istio#19568]
---
# Configuration for a Fluentd handler
apiVersion: "config.istio.io/v1alpha2"
kind: fluentd
metadata:
  name: handler
  namespace: istio-system
spec:
  address: "fluentd-es.logging:24224"

this is just for fluentd server address, how to define tag?

**Comment by douglas-reid** [comment]
Closing this issue, as this is a question about usage. Please use the [fourms](discuss.istio.io) for these questions.
