### ISSUE TITLE
Allow multiple profiles or ICPs that are merged

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#19562]
Its a common pattern to have layered configuration. For example, in helm you could do `helm install istio -f high-availablity.yaml -f sds.yaml -f enable-telemetry-v2.yaml -f disable-mixer.yaml` or something. With the operator or istioctl, this is no longer possible.

It would be nice to take multiple ICPs. There have been requests for better support for user defined "profiles". This would basically get rid of that need; they would just define multiple ICPs that are used. Or allow multiple profiles.. either one is more or less the same.

**Comment by elfinhe** [comment]
questions - 

- should we allow one component is configured by multiple ICPs?
- what's the common practice of dealing with conflicts?

**Comment by howardjohn** [comment]
I am not sure what the issue is with conflicts? We already have a 3 way hierarchy of profile -> ICP -> --set, right? What I am proposing is an N way hierarchy of profile -> ICP[0] -> ICP[1] -> ICP[n] -> `--set`

**Comment by elfinhe** [comment]
yes, it is a good idea, especially for users who are familiar with helm.

**Comment by elfinhe** [comment]
wdyt, @ostromart

**Comment by howardjohn** [comment]
Another use case that was the primary driver: we have "testing defaults", which sets CPU requests really low, etc. There isn't an easy way to have those defaults and have tests override them with their own ICP files

**Comment by elfinhe** [comment]
I got you, this will be useful in various scenarios, also will match our original overlay idea.

**Comment by kramvan1** [comment]
@elfinhe  I don't think this change can be supported by the operator controller, right?     There is NO way to order the ICP kubernetes resources such that they are processed correctly and consistently.     For the operator controller, it's watching a namespace or namespaces for a single ICP resource.
@linsun @sdake

**Comment by linsun** [comment]
@kramvan1 it looks like helm support it for both install and template where you can specify multiples value files or set values.  For operator controller, I agree it will be challenging.  If we support it to match what Helm has, user would have to specify the multiple ICP files together in 1 command which kubectl doesn't have a easy way to specify it other than all files within a directory.

**Comment by kramvan1** [comment]
@linsun the operator controller is simple watching the ICP resources, there is no way to order kubectl even within directories.       You could use kubectl -k (kustomize), but that would mean that kubectl is doing the merges and still giving a single ICP resource.

**Comment by linsun** [comment]
yes `kubectl -k` is what i was referring to.  I think is the only possible way to support this based on what kubectl provides.   and you are right, the controller would still be processing 1 single icp resource.

**Comment by elfinhe** [comment]
@kramvan1 as for the controller mode, I did not change the logic. So only one CR is supported now in controller. 

I do not think we should support that for now. Instead users can use `istioctl profile dump` to get a merged ICPS and install it as CR. Controller can still use 1 CR as input which makes things easier to understand in controller mode.

**Comment by kramvan1** [comment]
So, maybe a comment to the doc needs to be added to suggest that `kubectl -k` is a alternate way of doing this, especially for the operator controller.
