### ISSUE TITLE
istio not honoring termination grace period

### ISSUE THREAD

**Issue by jcetkov** [istio/istio#19564]
**Bug description**
Consider following scenario: application is doing fairly long running requests. It configures it's `terminationGracePeriodSeconds` to longer time, say 60s to be able to complete all inflight requests on pod termination/upgrade

if istio sidecar is injected, on receiving SIGTERM from k8s, the side car terminates with hardcoded 5s grace period, and due to the existing IP tables rewrites effectively terminates all traffic to the application container, violating the `terminationGracePeriodSeconds` contract.

```
2019-12-12T22:41:00.712626Z	info	pilot-agent is terminating
2019-12-12T22:41:00.712670Z	info	Watcher has successfully terminated
2019-12-12T22:41:00.712682Z	info	Agent draining Proxy
2019-12-12T22:41:00.712692Z	info	Reconciling retry (budget 10)
2019-12-12T22:41:00.712714Z	info	Graceful termination period is 5s, starting...
2019-12-12T22:41:00.712729Z	info	Epoch 1 starting
2019-12-12T22:41:00.712738Z	info	watchFileEvents has successfully terminated
...
2019-12-12T22:41:05.712925Z	info	Graceful termination period complete, terminating remaining proxies.
2019-12-12T22:41:05.713022Z	warn	Aborting epoch 0...
2019-12-12T22:41:05.713038Z	warn	Aborting epoch 1...
2019-12-12T22:41:05.713046Z	warn	Aborted all epochs
2019-12-12T22:41:05.713052Z	info	Agent has successfully terminated
```

**Expected behavior**
sidecar should not terminate until the application container exits (or alternatively before the end of the grace period).

**Steps to reproduce the bug**
configure pod with `terminationGracePeriodSeconds` longer than 5s and application with 10s delay to respond
send some traffic
delete pod
observe the requests being interrupted

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
client version: 1.2.9
citadel version: 1.2.9
egressgateway version: 1.2.9
egressgateway version: 1.2.9
galley version: 1.2.9
galley version: 1.2.9
ingressgateway version: 1.2.9
ingressgateway version: 1.2.9
pilot version: 1.2.9
pilot version: 1.2.9
sidecar-injector version: 1.2.9
sidecar-injector version: 1.2.9
```
**How was Istio installed?**
custom pipeline using helm

**Environment where bug was observed (cloud vendor, OS, etc)**
custom kubernetes installation in top of MS azure

**Comment by jcetkov** [comment]
This can be used to mitigate the issue
https://github.com/istio/api/pull/1194

**Comment by howardjohn** [comment]
Long term solution is https://github.com/kubernetes/enhancements/blob/master/keps/sig-apps/sidecarcontainers.md

**Comment by jcetkov** [comment]
another immediate workaround is to modify the injector template with the following
```
        env:
        - name: TERMINATION_DRAIN_DURATION_SECONDS
          value: {{ .Spec.TerminationGracePeriodSeconds }}
```

**Comment by fcantournet** [comment]
I don't think this is enough for what you want :
If I understand correctly `TERMINATION_DRAIN_DURATION_SECONDS` prevent all new connections being established, including outbound connections.

So imagine you pod is servicing a requests on an established connection and need to make a call to another service, envoy will refuse to establish the outbound connection.

Our current workaround this was to patch the injected template with a prestopHook which sleeps for n seconds.

**Comment by jcetkov** [comment]
my usecase was not to terminate the inflight connections, not allow establishing new ones, where the workaround is sufficient

**Comment by jdomag** [comment]
@fcantournet 
Can you share how do you patch it? Is it automated somehow during workload creation?

**Comment by jdomag** [comment]
@jcetkov 
Any hint how to set those env in istio profile?

**Comment by jcetkov** [comment]
@jdomag by profile you mean by some sort of annotation? you'd have to add it conditionally into the template - I just modified the injection template we install in the clusters as we decided this change should be there globally. I just added it here https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/files/injection-template.yaml#L158
and than it's automated, as the injector uses the template when creating the config for sidecar

however I didn't follow up on the latest changes, if there were any impacting this area, I'm in middle of a parental leave

**Comment by jdomag** [comment]
@jcetkov yes this is istio manifest - I generate my manifests from istio profile and was wondering how to define it inside a profile so i don't need to modify manifest by hand.

**Comment by jcetkov** [comment]
if you don't want to edit it directly, just look through the file if there is a conditional block that works for you
```
    {{- range $key, $value := fromJSON (index .ObjectMeta.Annotations `apm.datadoghq.com/env`) }}
    - name: {{ $key }}
      value: "{{ $value }}"
    {{- end }}
    {{- end }}
    {{- range $key, $value := .ProxyConfig.ProxyMetadata }}
    - name: {{ $key }}
      value: "{{ $value }}"
    {{- end }}
```
your best bet is one of the above; each deployment would have to have an annotation for the first, which may work if you use some template for your deployments. If neither that nor the `ProxyConfig` works for you, I don't see another way how to achieve it in the current version of the template

**Comment by Eslamanwar** [comment]
@jcetkov If you can help on setting TERMINATION_DRAIN_DURATION_SECONDS through .ProxyConfig.ProxyMetadata?
It can be done on the istio operator?

**Comment by mkmik** [comment]
I tried setting istio's `terminationDrainDuration` to match my pod's `terminationGracePeriodSeconds` and it worked as advertised, i.e. istio did in fact wait that long before exiting.

However, in my case I have a `terminationGracePeriodSeconds` of 10 minutes, which is supposed to give enough time for the pod to save its state. However, those 10m are only for the worst case; it's common for the main process to complete the flush way quicker than 10m and yet the pod will stay in `Terminating` state waiting for `istio-proxy` sidecar to terminate.

Any ideas on how to make istio sidecar exit when the other containers have all exited?

**Comment by chuong-ts** [comment]
> I tried setting istio's `terminationDrainDuration` to match my pod's `terminationGracePeriodSeconds` and it worked as advertised, i.e. istio did in fact wait that long before exiting.
> 
> However, in my case I have a `terminationGracePeriodSeconds` of 10 minutes, which is supposed to give enough time for the pod to save its state. However, those 10m are only for the worst case; it's common for the main process to complete the flush way quicker than 10m and yet the pod will stay in `Terminating` state waiting for `istio-proxy` sidecar to terminate.
> 
> Any ideas on how to make istio sidecar exit when the other containers have all exited?

Hope this help in your case: https://fluxcd.io/flagger/tutorials/zero-downtime-deployments/#delay-envoy-shutdown
