### ISSUE TITLE
unable to create kind: fluentd from demo code

### ISSUE THREAD

**Issue by hillbun** [istio/istio#19570]
istio-1.4.0

I run kubectl apply -f samples/bookinfo/telemetry/fluentd-istio-crd.yaml

but get errors:

rule.config.istio.io/newlogtofluentd created
unable to recognize "samples/bookinfo/telemetry/fluentd-istio-crd.yaml": no matches for kind "logentry" in version "config.istio.io/v1alpha2"
unable to recognize "samples/bookinfo/telemetry/fluentd-istio-crd.yaml": no matches for kind "fluentd" in version "config.istio.io/v1alpha2"

**Comment by howardjohn** [comment]
I think this was deprecated, we need to update samples for this.

@kyessenov @douglas-reid

**Comment by esnible** [comment]
Can someone on @istio/wg-docs-maintainers take this on?  @frankbu ?

`istioctl validate -f samples/bookinfo/telemetry/fluentd-istio-crd.yaml` reports deprecation warnings and validation errors for these samples.  Can we eliminate from 1.5 all invalid samples?  Or is the problem that the validation logic is incorrect, and the samples are OK?

These are samples with errors:

- samples/sleep/telemetry/sni-logging.yaml
- samples/sleep/policy/sni-wikipedia.yaml
- samples/sleep/policy/sni-serviceaccount.yaml
- samples/fortio/stackdriver.yaml
- samples/bookinfo/platform/kube/rbac/rbac-permissive-telemetry.yaml
- samples/bookinfo/telemetry/metrics.yaml
- samples/bookinfo/telemetry/fluentd-istio-crd.yaml
- samples/bookinfo/telemetry/metrics-crd.yaml
- samples/bookinfo/telemetry/log-entry.yaml
- samples/bookinfo/telemetry/log-entry-crd.yaml
- samples/bookinfo/telemetry/tcp-metrics-crd.yaml
- samples/bookinfo/telemetry/fluentd-istio.yaml
- samples/bookinfo/telemetry/tcp-metrics.yaml
- samples/bookinfo/policy/mixer-rule-deny-label-crd.yaml
- samples/bookinfo/policy/mixer-rule-productpage-ratelimit-crd.yaml
- samples/bookinfo/policy/mixer-rule-ratings-redis-quota-fixed-window.yaml
- samples/bookinfo/policy/mixer-rule-kubernetesenv-telemetry.yaml
- samples/bookinfo/policy/mixer-rule-kubernetesenv-telemetry.yaml
- samples/bookinfo/policy/prometheus-oop-rule.yaml
- samples/bookinfo/policy/mixer-rule-productpage-ratelimit.yaml
- samples/bookinfo/policy/mixer-rule-deny-whitelist.yaml
- samples/bookinfo/policy/mixer-rule-deny-label.yaml
- samples/bookinfo/policy/mixer-rule-productpage-redis-quota-rolling-window.yaml
- samples/bookinfo/policy/mixer-rule-deny-ip-crd.yaml
- samples/bookinfo/policy/mixer-rule-ratings-redis-quota-rolling-window.yaml

**Comment by howardjohn** [comment]
The docs say to only apply this on 1.1 and earlier: https://istio.io/docs/tasks/observability/mixer/logs/fluentd/#configure-istio

We should probably clean this up since no one is using 1.1 now (hopefully!), but we are going to remove Mixer entirely so its wasted effort.

**Comment by douglas-reid** [comment]
I don't believe that this is ever going to get any attention unfortunately. With Mixer being removed from the codebase now, I think it is appropriate to close this issue.
