### ISSUE TITLE
add concurrency option or annotation override for ingressgateway

### ISSUE THREAD

**Issue by lambdai** [istio/istio#19588]
The concurrency value is default, which is number of cores. It's terrible if ingressgateway is deployed on a 1 core pod while the node is 64 core.

**Comment by ramaraochavali** [comment]
@lambdai why just ingress gateway? Why not do generically do it for sidecars as well?

**Comment by lambdai** [comment]
@ramaraochavali Istio-proxy should already have it `global.proxy.concurrency` as install option
Not ideal but somewhat an option.

**Comment by ChenLingPeng** [comment]
+1 for @ramaraochavali 
I think istio should support the user to specific concurrency from annotation just like other options like proxy_image.

**Comment by howardjohn** [comment]
This is supported by `proxy.istio.io/config` option now in istio 1.6

**Comment by foxracle** [comment]
@howardjohn  but how to set concurrency, would do you mind to give some samples to show the correct way to do it?

I have add the annotation to the deployment of ingressgateway, but it can not work。
1：
proxy.istio.io/config: '{"concurrency" : "32" }'

2：
proxy.istio.io/config: '{"defaultConfig" : {"concurrency" : "32" } }'

Neither works.
