### ISSUE TITLE
Istio response 503

### ISSUE THREAD

**Issue by zhulinwei** [istio/istio#19593]
**Bug description**
Istio return 503 status code and can see the response flags of "-" and "UC" in prometheus.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Want to know why the curves of "-" and "UC" in prometheus are highly coincident？

**Steps to reproduce the bug**

- server.go

```
func main() {
	route := gin.New()
	router.InitRoute(route)

	server := &http.Server{
		Addr:    ":8080",
		Handler: route,
		ReadTimeout:    30 * time.Second,
		WriteTimeout:   30 * time.Second,
		MaxHeaderBytes: 1 << 20,
	}
	if err := server.ListenAndServe(); err != nil {
		log.Error("run server error", log.String("error", err.Error()))
	}
}
```
- make a http request

In product environment, some http request do not transmit data normally, the http readtimeout limit will be triggered, and then Istio will return 503

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

`istioctl version --remote` output:
```
client version: 1.3.4
control plane version: 1.3.3
```

`kubectl version` output:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.12-eks-c500e1", GitCommit:"c500e11584c323151d6ab17526d1ed7461e45b0c", GitTreeState:"clean", BuildDate:"2019-10-22T03:11:52Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
```

`helm version` output:
```
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
```
**How was Istio installed?**
Using helm

**Environment where bug was observed (cloud vendor, OS, etc)**
Amazon Linux 2

**Addition**
Istio return response_flags "-":
![](https://raw.githubusercontent.com/zhulinwei/kubernetes/master/logging/other/images/Snipaste_2019-12-14_17-37-50.png)

Istio return response_flags "UC":
![](https://raw.githubusercontent.com/zhulinwei/kubernetes/master/logging/other/images/Snipaste_2019-12-14_17-43-35.png)
Does anyone know why their curves are highly coincident？
![](https://raw.githubusercontent.com/zhulinwei/kubernetes/master/logging/other/images/Snipaste_2019-12-14_17-38-16.png)

**Comment by howardjohn** [comment]
Maybe be useful: https://karlstoney.com/2019/05/31/istio-503s-ucs-and-tcp-fun-times/

**Comment by LinLshare** [comment]
I had the same problem, and I had set the timeouts in my Go program, see codes below.
```go
func main() {
	route := gin.New()
	router.InitRoute(route)

	server := &http.Server{
		Addr:           config.GrinderConfig().HttpPort,
		Handler:        gin.GetEngine(),
		IdleTimeout:    6 * time.Minute,
		ReadTimeout:    30 * time.Second,
		WriteTimeout:   30 * time.Second,
		MaxHeaderBytes: 1 << 20,
	}
	...
}
```

**Comment by LinLshare** [comment]
I found that my Go program received http body which length < content-length, maybe it is what the problem is!
