### ISSUE TITLE
istio ingress tls orginiation

### ISSUE THREAD

**Issue by dhineshbabuelango** [istio/istio#19609]
When we access our microservice using istio ingress gateway, the tls is getting terminated at ingress and it it sending http traffic to microservice, microservice just add /service to the incoming url which will redirect to a login page. since ingress is terminating the tls microservice just add /service to the http url which doesn't exists.

I tried creating the destination rule mentioning the host rp.sp-asg.app.internal.pcpc.com with tls mode simple but still the connection is changing to http

Request URL: **https://rp.sp-asg.app.internal.pcpc.com/*
Request Method: GET
Status Code: 200 
Remote Address: 10.82.11.69:443
Referrer Policy: no-referrer-when-downgrade
cache-control: no-store
content-length: 9447
content-security-policy: frame-ancestors 'none'
content-type: text/html
date: Mon, 16 Dec 2019 10:44:33 GMT
location: **http://rp.sp-asg.app.internal.pcpc.com/service/?TAM_OP=login&URL=%2F&AUTHNLEVEL=&authlvl=Unknown**
p3p: CP="NON CUR OTPi OUR NOR UNI"
pragma: no-cache
server: istio-envoy
status: 200
strict-transport-security: max-age=31536000; includeSubDomains
x-content-type-options: nosniff
x-envoy-upstream-service-time: 5
x-frame-options: DENY
x-xss-protection: 1

**Comment by dhineshbabuelango** [comment]
Virtual Service that is sending the traffic.

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: appegress
spec:
  hosts:
  - rp.sp-asg.app.internal.pcpc.com
  gateways:
  - tls-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 80
        host: wrp-service

**Comment by vadimeisenbergibm** [comment]
@dhineshbabuelango I still do not understand the description of the issue. So you have a `tis-gateway` ingress gateway, that accepts TLS traffic on port 443, performs TLS termination, and directs the traffic to `wrp-service` port 80. Does `wrp-service` expects TLS traffic on port 80? How do you access it from inside the cluster? What is the definition of `tls-gateway`?

**Comment by dhineshbabuelango** [comment]
@vadimeisenbergibm 
 tls-gateway ingress gateway, that accepts TLS traffic on port 443, performs TLS termination, and directs the traffic to wrp-service port 80
**Yes, the micro service wrp-service, will do some validations on the request and simply add /service to that request** 


https://rp.sp-asg.app.internal.pcpc.com/

We hit the above url and it reaches wrp-service and it has to add /service like below which is another site 
**https:**//rp.sp-asg.app.internal.pcpc.com/service 

but the problem is while the connection coming to wrp-service it is coming as 
**http**://rp.sp-asg.app.internal.pcpc.com and it is trying to add /service and the url becomes 
**http://rp.sp-asg.app.internal.pcpc.com/service which doesnot exists**.

Since this is not an egress connection establishing from the wrp-service, its just a response to the connection that hit the micro service, tls origination on egress is not working. 

Below is my GW.

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: tls-gateway
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: "tlscredential" # must be the same as secret
    hosts:
    - "rp.sp-asg.app.internal.pcpc.com"

**Comment by vadimeisenbergibm** [comment]
@dhineshbabuelango OK, I see. You should do the following:

1. Define a VirtualService to redirect traffic to rp.sp-asg.app.internal.pcpc.com, destined to port 80, to port 443
2. Define a DestinationRule to perform TLS origination for rp.sp-asg.app.internal.pcpc.com

**Comment by dhineshbabuelango** [comment]
@vadimeisenbergibm I tried to create a Virtual service and destination rule like below, but still the response is same, https is getting converted to http. I tried applying this virtual service to my apps namesapce and tried applying this to istio-system namespace as well. 

**Note: This is not an egress connection from the pod, it is just a response the incoming connection**

![image](https://user-images.githubusercontent.com/51995628/71076291-6e870000-21c0-11ea-9b26-fe0a1cdcfd73.png)


Response

![image](https://user-images.githubusercontent.com/51995628/71076439-adb55100-21c0-11ea-8360-ca67e6652fab.png)

**Comment by dhineshbabuelango** [comment]
curl output from server 

![image](https://user-images.githubusercontent.com/51995628/71078359-35508f00-21c4-11ea-98f8-59c53119e25e.png)

**Comment by vadimeisenbergibm** [comment]
I see, so you need to manipulate the `location` header, not the actual traffic. So the virtual service and the destination rule above are not needed. 

You can manipulate response headers in a Virtual Service, https://istio.io/docs/reference/config/networking/virtual-service/#Headers, but I do not see a possibility to set a header based on its previous value.

Your issue is not about Ingress TLS origination, it is about changing the `location` header of the response. Istio cannot update a header of a response (in your case to change the URL schema from `http` to `https`, it only can set a new value). I am not sure it is related to TLS termination, the question what your `wrp-service` actually does. Does it use HTTP schema for the traffic that arrives to port 80? Does it use HTTPS schema for the traffic that arrives to port 443?

**Comment by dhineshbabuelango** [comment]
Actually the ultimate aim is to reach https://rp.sp-asg.app.internal.pcpc.com/service where the actual website resides, this is in a different server. But before reaching the actual website this micro service will do collect some metrics and redirect to the actual website, so the users will hit this microservice using the url 

https://rp.sp-asg.app.internal.pcpc.com/ 

and after performing checks and collect the data it will just add /service to whatever url it receives

https://rp.sp-asg.app.internal.pcpc.com/service

In our case the user is hitting the url with https like below but since it is getting terminated at ingress the micro service is receiving the http connection and redirecting the service to a http url which actually doesn’t exists 

https://rp.sp-asg.app.internal.pcpc.com/

**Comment by vadimeisenbergibm** [comment]
> The micro service is listening on Port 80 only

So how can the microservice know which protocol to expect on port 80, HTTP or HTTPS? Can you see the code that listens on port 80?

**Comment by dhineshbabuelango** [comment]
Basically the micro secure doesn’t check what’s the protocol it is receiving the connection, all it does is store some session information and add /service to the request

**Comment by vadimeisenbergibm** [comment]
> Basically the micro secure doesn’t check what’s the protocol it is receiving the connection,

I think it is not possible since the service has to participate in the HTTPS (TLS) protocol, perform TLS handshake etc. My guess is that the microservice accepts HTTP only and it adds `http://` to the HOST header it receives. The HOST header does not contain the scheme.

The simple way to check it is to run the service in a namespace without istio, send to it an HTTPS request from within the namespace and see the results. My guess is that the service will not be able to return a response to a HTTPS connection.

**Comment by dhineshbabuelango** [comment]
@vadimeisenbergibm we actually tested by making the microservice to listen on port 443 and send the gateway connection through PASSTHROUGH method and it worked fine since there is no tls termination happened it is working fine. But since we can not control the centralised certificate and the microservice has to use its own certificate we are trying to achieve this on port 80 only and make use the ingress gateway certificate

**Comment by vadimeisenbergibm** [comment]
@dhineshbabuelango I do not think I can help you without understanding exactly what the service does - where does it take the schema (`http://` or `https://`) from.

**Comment by dhineshbabuelango** [comment]
The service does some basic authentication but basically after authentication from  whatever the connection it received it just add /service to that url and send that back

**Comment by vadimeisenbergibm** [comment]
And where does it take the schema (http:// or https://) from?

**Comment by dhineshbabuelango** [comment]
when we tried the same service to listen on 443 and configured the gateway as passthrough it performed like below. 

![image](https://user-images.githubusercontent.com/51995628/71092113-933f9f80-21e1-11ea-8456-29672fb41606.png)

and the curl output. IF you see the output since the tls termination doesn't happened it received the url as https and added /service to that url and it works.

![image](https://user-images.githubusercontent.com/51995628/71092355-09440680-21e2-11ea-8cca-53347a26f398.png)

**Comment by vadimeisenbergibm** [comment]
So can you try to direct the traffic at the gateway to the port 443 of the service, and perform TLS origination to this port?

**Comment by dhineshbabuelango** [comment]
@vadimeisenbergibm yes it works for us but the problem is this microservice should listen on port 443 and it has to manage its own certificate. So basically if istio ingress gateway doesn't terminate the tls connection it work fine, if it terminates, then we have to find a way to add https during the response.

**Comment by vadimeisenbergibm** [comment]
I still do not understand where precisely the service gets the schema `http://` or `https://` from. Can you check the code of the service? Can you change the service that it will read the schema from some custom header, for example `SCHEMA`? Then you will be able to set this header with Istio.

**Comment by dhineshbabuelango** [comment]
@vadimeisenbergibm Actually when hit the application with https, at somepoint it is getting terminated to http in the ingress gateway but during the response, the ingress gateway should initiate the terminated response right?

The below is the issue we are facing, when ingress terminates the connection at step3, the connection remain http in all the steps.

![image](https://user-images.githubusercontent.com/51995628/71147302-5c11d280-2263-11ea-8518-fad0a097ec4d.png)

**Comment by vadimeisenbergibm** [comment]
@dhineshbabuelango I understand that, I do not understand how the right microservice on your diagram adds "/service". Where does it get the schema part? Until I understand how your microservice performs this task, in the code, I will not be able to help you, sorry.

**Comment by newbiels** [comment]
> @dhineshbabuelango I understand that, I do not understand how the right microservice on your diagram adds "/service". Where does it get the schema part? Until I understand how your microservice performs this task, in the code, I will not be able to help you, sorry.

Hi @vadimeisenbergibm I think @dhineshbabuelango is referring to "Location" header which http client will follow for 302 direction. 

If Ingress Gateway is the one terminating TLS, it may be expected for microservice to return "http://../service" in Location header in a 302 response(step 4 in the diagram), as the request microservice receives is "**http**://...". However as Ingress receives **https**:// request from ELB, it may be expected that when Ingress forward the 302 response from microservice to ELB, Ingress will rewrite the Location header from **http**://../service to **https**://../service

Hope it clarifies. Thanks.

**Comment by vadimeisenbergibm** [comment]
@newbiels I understand that, I do not understand what the Ingress Gateway must do in order to cause the microservice to return `https://` in the Location header. This is I because I do not understand where the microservice gets the schema from. If @dhineshbabuelango could check the code or documentation of the microservice, I would be able to understand it.

**Comment by howardjohn** [comment]
I am not sure we can debug this without the additional info requested 6 months ago. Without this, I wil close. If we can get more info we can investigate further. Thanks
