### ISSUE TITLE
istio k8s cluster kept on calling host's dns server

### ISSUE THREAD

**Issue by piengeng** [istio/istio#19607]
**Bug description**
on the master node, istio kept on requesting istio-galley.istio-system and zipkin.istio-system, ratio about 474:30, istio-galley.istio-system is asking AAAA record, zipkin.istio-systems is asking A record to my local DNS server. shouldn't this dns request to kube-dns instead of asking the dns set on the host?

**Expected behavior**
not asking istio-galley.istio-system and zipkin.istio-system to the DNS set by the host.

**Steps to reproduce the bug**
setup istio k8s cluster with local forwarding dns server, my dns server is pi-hole.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
$ istioctl version --remote
client version: 1.4.2
control plane version: 1.4.2
data plane version: 1.4.2 (5 proxies)
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
following site's instruction.

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by wu0407** [comment]
check the  dnspolicy of istio component deployment

**Comment by piengeng** [comment]
ok, i'll google it on how to do that, thanks for the tip, appreciate it.

**Comment by piengeng** [comment]
@wu0407 i've check all deployment in 'istio-system' namespace, every single ones has 
"dnsPolicy: ClusterFirst" set, checked via below commands. Where should I check next? the out of cluster dns queries really bugs me.😟
```
$ kubectl -n istio-system get deploy grafana -o yaml | less
$ kubectl -n istio-system get deploy istio-citadel -o yaml | less
$ kubectl -n istio-system get deploy istio-galley -o yaml | less
$ kubectl -n istio-system get deploy istio-ingressgateway -o yaml | less
$ kubectl -n istio-system get deploy istio-pilot -o yaml | less
$ kubectl -n istio-system get deploy istio-policy -o yaml | less
$ kubectl -n istio-system get deploy istio-sidecar-injector -o yaml | less
$ kubectl -n istio-system get deploy istio-telemetry -o yaml | less
$ kubectl -n istio-system get deploy prometheus -o yaml | less
```

**Comment by howardjohn** [comment]
the DNS queries are most likely done by the sidecars, not the control plane.

**Comment by howardjohn** [comment]
At least the zipkin ones, not sure why galley has so many queries
Can you find the source of the lookups? are they often?

**Comment by piengeng** [comment]
how do i find out the source of the lookup? i'm just testing out simple nginx services with 3 pods with automatic sidecar injection enabled. 

Here's my pihole's [queries log](https://gist.github.com/piengeng/92d2add170b174e22b0173285f345e36) log , k8s.c5r.home is the k8s master node (1 master, 3 worker nodes in my hyper-v setup), internally my network doesn't use ipv6.

from the log, on 22:?? hour, there's 1484 queries to istio-galley.istio-system, all AAAA type queries, because no one owns *.istio-system yet, so the dns response is NXDOMAIN. So, in one hour span, on a cluster that's not doing much, i'd consider it's quite frequent.
