### ISSUE TITLE
Istio failed to upgrade from 1.3.3 to 1.4.2 sidecar

### ISSUE THREAD

**Issue by bibi520** [istio/istio#19608]
I failed to upgrade from istio1.3.2 to isito1.4.2 sidecar
![image](https://user-images.githubusercontent.com/42456284/70900435-c2181300-2033-11ea-8607-cb30d411d8b1.png)
kubectl describe pod istio-sidecar-injector-78c55ff8f-7vhld :
![image](https://user-images.githubusercontent.com/42456284/70900474-d4924c80-2033-11ea-94e6-965221f9080f.png)
New environment I just installed 1.3.2 and then started to upgrade 1.4.2

**Comment by howardjohn** [comment]
how did you install?

**Comment by bibi520** [comment]
I installed it with helm，I use helm installation problem is that I use istioctl manifest the apply -- set values. Global. DisablePolicyChecks = false this command to open the flow speed cause I have a part of the upgraded to cluster 1.3.3 1.4.2 finally with helm to upgrade to this mistake

**Comment by bibi520** [comment]
![image](https://user-images.githubusercontent.com/42456284/70955331-6ab58980-20ab-11ea-8015-83c605dda7cf.png)
![image](https://user-images.githubusercontent.com/42456284/70955336-71440100-20ab-11ea-8462-48791e6feee7.png)

**Comment by bibi520** [comment]
![image](https://user-images.githubusercontent.com/42456284/70955809-0f849680-20ad-11ea-8613-0cc73c3a0bf4.png)

**Comment by bibi520** [comment]
I upgraded with helm
![image](https://user-images.githubusercontent.com/42456284/70957401-03023d00-20b1-11ea-82ce-3da87033b935.png)

**Comment by bibi520** [comment]
My kubectl of node node is 1.14.3, will it have any effect

**Comment by howardjohn** [comment]
A user with a similar issue suggested upgrading helm fixed this (not to helm v3 though)

**Comment by jcetkov** [comment]
what is your version of helm/tiller? I observed this issue on helm 2.11 and we confirmed with any newer helm (on the 2.x branch) this issue went away.

if that's not immediately possible, short term workaround is to remove the `subresources` entry in the gateway CRD

**Comment by bibi520** [comment]
Thank you. It's settled
