### ISSUE TITLE
Add ability to forward(/remote_write) metrics collected in Prometheus

### ISSUE THREAD

**Issue by prashantchari** [istio/istio#19619]
Prometheus allows for a remote_write setting to forward metrics to other sources. With the current helm chart for Istio (with prometheus enabled) , there isn't a good way to configure it and it would nice to have that ability or inject any custom prometheus config.

**Comment by riddhi2910** [comment]
Were you able to find a way? @prashantchari

**Comment by howardjohn** [comment]
Hi @prashantchari . The prometheus installed with Istio is meant to get users quickly started. For advanced usages, you may need to modify it manually or integrate with another Prometheus installation. We have documentation for doing this at https://preliminary.istio.io/docs/ops/integrations/prometheus/. Thanks!
