### ISSUE TITLE
Missing definition of BoolValueForPB in components.pb.go

### ISSUE THREAD

**Issue by bianpengyuan** [istio/istio#19616]
**Bug description**
When trying to update istio/istio deps (https://github.com/istio/istio/pull/19597), it fails to build because of missing definition of `BoolValueForPB`. The struct should be generated in `istio/api` by `fixup_structs` step (https://github.com/istio/api/blob/cc9d61a1c5dfb95d5b5b64f57fba58aa40f067a5/Makefile.core.mk#L188) in istio/api code gen.

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by diemtvu** [comment]
What is the status of this? It seems I still have problem with my PR.

**Comment by howardjohn** [comment]
This is fixed, just needs a lot of changes, I am tryng to update

**Comment by howardjohn** [comment]
Nevermind, we need to revert the fix: https://github.com/istio/api/pull/1215

@ostromart

**Comment by ostromart** [comment]
Fixed in https://github.com/istio/api/pull/1216 and https://github.com/istio/api/pull/1223.
