### ISSUE TITLE
Support MCPRegistry in multi-cluster scenarios

### ISSUE THREAD

**Issue by kevin21th** [istio/istio#19626]
**Describe the feature request**
Currently, only KubernetesRegistry was supported in multi-cluster scenarios,  but if we deploy Galley in the remote cluster, then MCPRegistry can also be able to work. Through this feature, pilot can also decoupling from specific platforms in multi-cluster scenarios.

On the other hand, in large-scale clusters, many pilot instances are needed to serve many sidecars, using MCP instead of list/watch apiserver directly will bring less pressure and be more feasible.

**Describe alternatives you've considered**
First, galley will be deployed in remote cluster to provide service discovery, for example via SyntheticServiceEntry.
Similar to now, when a remote cluster joins,  a secret which contains cluster_id and remote galley address will be added to the primary cluster, and then secretController will receive this event and remote sseMCPController will be created.
As the same interfaces, pilot can use the controller with MCPRegistry just like KubernetesRegistry one.

**Additional context**
None for now

**Comment by howardjohn** [comment]
We are no longer supporting Galley as an MCP source so I don't think there is any action items here. Thanks!
