### ISSUE TITLE
Document / Best Practice - Scrape other pods metrics in an Istio Environment

### ISSUE THREAD

**Issue by etiennejournet** [istio/istio#19628]
**Describe the feature request**
Hi, I'm looking into setting up prometheus-operator in a Istio mTLS cluster. For the moment I've not been able to find a satisfying way of scraping the metrics.
The problem is that, after service discovery, prometheus scrapes metrics using pod IP address and envoy throws 503.
I understand the generic solution is to declare a non-mTLS port in your mesh and serve metrics on it, but what about applications on which you can't change the metrics port ? (any addon in the prometheus-operator stack, or generally all the supervision tools)

**Describe alternatives you've considered**
Being new to Istio, I thought I would declare a destinationrule concerning supervision-service.namespace.svc.cluster.local as source, but it's not possible ...
Disabling mTLS on a single port kind of goes against mTLS purpose isn't it ? (And other things mentioned above)
For now  I just got the prometheus container out of the mesh... Not knowing what to think about this solution yet.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**
I should say this a nothing to say about scraping istio specific metrics, for that I've been using [https://github.com/istio/installer/tree/master/istio-telemetry/prometheus-operator](this) which works like a charm :) (are you guys considering releasing it on a helm repo ?)

**Comment by diemtvu** [comment]
Disabling mTLS on the metric port as you said is the the right approach at the moment. Destination rule won't help you in this case as traffic is originated from (prometheus) without sidecar. The other options I can think of is push metrics instead of pull, or adding sidecar to prometheus. (disclaim: I haven't tried neither).

**Comment by incfly** [comment]
https://docs.google.com/document/d/1TTeN4MFmh4aUYYciR4oDBTtJsxl5-T5Tu3m3mGEdSo8/edit#heading=h.tbuedekn7hc6

see here.

**Comment by incfly** [comment]
feel free to voice your requirement there.
