### ISSUE TITLE
Combine `istioctl upgrade` and `help` should offer same args (e.g. `--set` as `manifest apply`

### ISSUE THREAD

**Issue by esnible** [istio/istio#19636]
Should these be aligned?  `apply` lets me set things, upgrade does not.

If I apply and remove something, such as Kiali, does it go away correctly?  Need test cases for apply removing components.

**Comment by howardjohn** [comment]
> If I apply and remove something, such as Kiali, does it go away correctly? Need test cases for apply removing components.

It is supposed to

**Comment by howardjohn** [comment]
These now offer the exact same flags, closing
