### ISSUE TITLE
istio-proxy CPU overload

### ISSUE THREAD

**Issue by Stono** [istio/istio#19634]
**Bug description**
Hi, 
We recently had an issue caused by `istio-proxy` cpu going rather crazy as can be seen by the green line on this graph.  This resulted in no requests being handled by istio-proxy at all (just connect timing out).

<img width="658" alt="Screenshot 2019-12-17 at 13 45 55" src="https://user-images.githubusercontent.com/1486729/71000967-28ed0900-20d4-11ea-8a13-686a562be379.png">

The interesting thing here is that the proxy was maxed out at 1 core, we have no limits on our proxies so I think this is telling me that it's a single thread.

Unfortunately, due to a process breakdown, we didn't capture proxy logs at the time.

We have never seen this in the past, so feels it's potentially something related to `1.4.0` upgrade.  Based on nothing more than my gut, it feels like https://github.com/istio/istio/issues/19112 is some how related.

**Expected behavior**
Proxy not to go haywire

**Steps to reproduce the bug**
Unfortunately, we haven't been able to replicate it

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.4.0

**How was Istio installed?**
Helm

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE `v1.14.8-gke.17`

**Comment by lambdai** [comment]
From the graph it's more like https://istio.io/news/security/istio-security-2019-006/, but it is supposed to be fixed in 1.4

 I feel there is no way to fix it if we only have this graph. However, more details are welcomed.

@Stono When you say `no requests being handled by istio-proxy at all (just connect timing out)`, how did you obtain this assertion? This is the major divergence vs the above istio-security-2019-006

**Comment by Stono** [comment]
Yeah I didn't anticipate that we'd be able to root cause it from the graph alone, I was more trying to trigger "oh I've seen that before" style comments such as that security bulletin. 

We actually already mitigated against that issue (and upgraded to 1.4 too) so I don't think that's the problem :-( 

We obtained that by exec'ing onto the pod and trying to curl downstream services, which just connect timed out, the same call from other unaffected pods in the same workload was fine, and restarting the trouble pod resolved it.

**Comment by Stono** [comment]
Hello
We've just had this happen again on `1.4.5`. 

We've cordoned the pod which has a proxy stuck at 100%.

I've dumped all the config (can provide privately).

Proxies readiness probe passes but all upstream requests fail.

<img width="802" alt="Screenshot 2020-02-21 at 15 11 59" src="https://user-images.githubusercontent.com/1486729/75046178-8d558b80-54bc-11ea-8098-bdd1c36a0f7c.png">

Is there anyone around that can help debug?

**Comment by howardjohn** [comment]
I believe the readiness probe is handled by a different thread than normal traffic, so it would make sense those are succeeding. That likely means the issue was on the data path side not from xds config or anything

**Comment by howardjohn** [comment]
@lambdai @yxue fyi

**Comment by howardjohn** [comment]
it's cordoned so it's taking no traffic right now, so it should be at 0 load but it's stuck at 1 cpu, right?

**Comment by Stono** [comment]
Correct.  
As a side note a readiness probe should really reflect its ability to proxy traffic too!

**Comment by howardjohn** [comment]
That's a good point, we should probably proxy the readiness probe through
envoy. I'll open an issue to track that

**Comment by lambdai** [comment]
@Stono Is the cpu usage at userspace or sys?

**Comment by lambdai** [comment]
Sorry still not much progress made this time. Looks like it's data plane worker threads.
If it happens in the future, we should try to obtain the cpu profile, or some quick info
1. worker threads(data path) or master thread(xds). The clue shows it's worker threads this time. Let's confirm next time. 
2. Single worker threads or more? 
3. cpu util sys or us?
^^ Those two question could be answered by `top -H`
4. logs around the moment when cpu util was sky rocketing.
