### ISSUE TITLE
Sticky session by version rather than pod

### ISSUE THREAD

**Issue by Stono** [istio/istio#19630]
**Describe the feature request**
Hey, 
We have a requirement to have sessions sticky to a particular version of the application, rather than a specific pod.

This means that during canary based rollouts, we would best-effort send traffic to the same version of the application.

This is required because each version of our application will generate a unique hash javascript bundle, so during a canary you could have:

```
v1:
  pod1
  pod2
  pod3

v2:
  pod4
  pod5
```

The HTML page could be returned from `pod4` or `pod5`, which in turn requests v2.js, but the subsequent call for the javascript could hit any of the v1 pods.  

The standard consistentHash sticky session works to an extent however not perfect because it ties the request to a single instance of the v1 pods, which can get terminated in a non deterministic order.

**Describe alternatives you've considered**
Changing our deployment strategy to blue/green but we'd rather not do that as we like canary.  
Changing our applications to prepublish dependencies to GCS storage but that's a big change for a lot of applications.

We're trying to find a "platform" way to solve this problem.

**Additional context**

**Comment by shaoye** [comment]
we have the same issue and curious to know what you ended up choosing?

**Comment by Stono** [comment]
I didn't solve it :D
