### ISSUE TITLE
istioctl installation can't set externalTrafficPolicy

### ISSUE THREAD

**Issue by cagataygurturk** [istio/istio#19642]
**Bug description**

istioctl can't set Ingress Gateway's externalTrafficPolicy

[ ] Configuration Infrastructure
[ ] Docs
[x ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Steps to reproduce the bug**

Failed to generate and apply manifests, error: failed to generate manifest: input file failed validation with the following errors: unknown field "externalTrafficPolicy" in v1alpha1.IngressGatewayConfig

Setting `spec.values.gateways.istio-ingressgateway` of `IstioControlPlane` to externalTrafficPolicy: Local creates the following error:

```Failed to generate and apply manifests, error: failed to generate manifest: input file failed validation with the following errors: unknown field "externalTrafficPolicy" in v1alpha1.IngressGatewayConfig```

Setting `spec.gateways.components.ingressGateway.k8s.service.externalTrafficPolicy` passes the validation but does not create an effect on generated manifest.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

Istio 1.4.2

**How was Istio installed?**

istioctl

**Comment by richardwxn** [comment]
@cagataygurturk Setting it under spec.unvalidatedValues.gateways.istio-ingress or run with --force flag should work

Also I don't think you can override that under k8s section, it is not part of the api:  https://istio.io/docs/setup/install/istioctl/#customize-kubernetes-settings

**Comment by cagataygurturk** [comment]
Will try @richardwxn 
Actually according to the doc there is a service field in K8S config: https://istio.io/docs/reference/config/istio.operator.v1alpha12.pb/#KubernetesResourcesSpec

**Comment by cagataygurturk** [comment]
`unvalidatedValues.gateways.istio-ingressgateway.externalTrafficPolicy` made the trick @richardwxn

**Comment by richardwxn** [comment]
@cagataygurturk oh yes, it is in the K8S spec but it is not working. I may know the issue already and would file a PR. You can use the unvalidatedValues part for now.

**Comment by cagataygurturk** [comment]
@richardwxn I did not want to open a different issue:

`values.global.proxy.accessLogEncoding` passes the validation but it does not have any effect. I tried `unvalidatedValues` and no chance. istio ConfigMap is not constructed properly.

It seems that there are a lot of not compatible Helm installation options or I do something wrong. Should we fallback to Helm as installation method?

**Comment by richardwxn** [comment]
The templates is missing this option and I created a PR to add it: https://github.com/istio/installer/pull/615.

Thanks for reporting these bugs and sry for the inconvenience caused, we are actually working to fill all these kind of gaps. I would encourage you to use istioctl as we are going to not support helm in the future. And we would greatly appreciate it for any feedbacks.

**Comment by cagataygurturk** [comment]
Thanks, I think I can send PR‘s also following your example.

How is the release cycle with PR‘s to installer repo? Will your recent change available immediately or will be there for the next Istio release?

**Comment by richardwxn** [comment]
If you add the cherrypick/release-1.4 label it would be added to next patch release of 1.4. https://github.com/istio/istio/releases/

**Comment by richardwxn** [comment]
accesslog related fix was merged, the change to enable service setting under K8S spec is still pending: https://github.com/istio/operator/pull/711

**Comment by so-jelly** [comment]
@richardwxn I am seeing the same behavior with    --set values.gateways.istio-ilbgateway.enabled=true

**Comment by richardwxn** [comment]
We had a recent api change so the PR to fix this issue was blocked, now I am working on to integrate that with latest master to fix this issue.

**Comment by etiennejournet** [comment]
> @cagataygurturk Setting it under spec.unvalidatedValues.gateways.istio-ingress or run with --force flag should work
> 
> Also I don't think you can override that under k8s section, it is not part of the api: https://istio.io/docs/setup/install/istioctl/#customize-kubernetes-settings

I should say as of yesterday and istio 1.4.1 the new API didn't work on azure.

**Comment by richardwxn** [comment]
@so-jelly Can you provide more details about what you said about the same behavior? Is it failing validation or not take effect? And are you referring to the enablement of ilbgateway or the externaltrafficPolicy for that.

**Comment by so-jelly** [comment]
@richardwxn 

`istioctl manifest generate --set values.gateways.istio-ilbgateway.enabled=true`                                    

> Run the command with the --force flag if you want to ignore the validation error and proceed.
> bad path=value (values.gateways.istio-ilbgateway.enabled=true): unknown field "istio-ilbgateway" in v1alpha1.GatewaysConfig

**Comment by richardwxn** [comment]
@so-jelly we do not provide built-in ilb gateway templates now, instead, you can create your own gateways under ingressGateways or egressGateways section, where we still provide one istio-ingressgateway and istio-egressgateway in istio-system ns respectively, but you can add more or override, take a look at this example: https://github.com/istio/istio/blob/master/operator/cmd/mesh/testdata/manifest-generate/input/gateways.yaml, or https://github.com/istio/istio/blob/master/operator/cmd/mesh/testdata/manifest-generate/input/gateways_override_default.yaml

**Comment by so-jelly** [comment]
thanks @richardwxn, that actually makes a lot of sense.  

i found another one
`istioctl manifest generate --set values.global.proxy.tracer="stackdriver"`

> Run the command with the --force flag if you want to ignore the validation error and proceed.
> bad path=value (values.global.proxy.tracer=stackdriver): unknown value "stackdriver" for enum v1alpha1.Tracer

It appears that this is a useful configuration item as some recent changes were made to enhance this setting.  https://github.com/istio/istio/issues/18680
