### ISSUE TITLE
graduate `istioctl x analyze`

### ISSUE THREAD

**Issue by esnible** [istio/istio#19640]
"Graduate" `analyze`, moving it out of `x`.

Possibly replace `istioctl validate`, possibly as `istioctl analyze` with `validate` being an alias for it.

**Comment by howardjohn** [comment]
I think @sushicw already did this?

**Comment by sushicw** [comment]
Yes, https://github.com/istio/istio/pull/19488

This doesn't immediately remove or replace `istioctl validate` but does add a deprecation notice. The next step (on the next version) would be to remove it. 

Closing this, @esnible feel free to re-open if you think this needs more discussion.
