### ISSUE TITLE
istio/proxy must be buildable without RBE

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#19655]
Remote bazel execution is great for our CI, but not necessarily usable outside. This includes Istio private builds, other companies/users building themselves, and local development (?).

If you try to build the proxy right now you will get errors about xenial/bionic mismatch with the build image. 

We need a way to build the proxy without RBE, but in the same environment as CI is running so it is reproducible.

cc @stewartbutler @bianpengyuan

**Comment by bianpengyuan** [comment]
Yeah, I cannot think of a good solution to this other than separate the proxy build image from istio-tools. glibc is tied to the os version and istio-tools docker image right now is coupled with bionic.

**Comment by howardjohn** [comment]
What environment is being run in RBE? I assume it must be some xenial based environment?

**Comment by bianpengyuan** [comment]
yes ubuntu 16.04. There is an issue (https://github.com/istio/istio/issues/19104) tracking prevention of accidental rbe upgrade breaks build.

**Comment by bianpengyuan** [comment]
this is done.
