### ISSUE TITLE
How to test service-graph in tools/perf/load ?

### ISSUE THREAD

**Issue by Zhangkaikang** [istio/istio#19661]
### what i do ?
```
$ git clone https://github.com/istio/tools.git
$ cd tools/perf/load
$ ./setup_large_test.sh 1
```
### problem
and after that, i don't know how to access service svc00-0 . 
In gateway, this service should listen port 80, but i can't access it .
gateway:
![](https://raw.githubusercontent.com/Zhangkaikang/md-pic/master/4.png)
virtualservice:
![](https://raw.githubusercontent.com/Zhangkaikang/md-pic/master/5.png)
failure: 
```
  //get 404 
  curl http://$My-External-IP
  curl http://$My-External-IP/metrics
```
success:
```
   kubectl exec -it $FORTIO_POD  -c fortio /usr/bin/fortio -- load -curl  http://$My-External-IP/metrics
```
![](https://raw.githubusercontent.com/Zhangkaikang/md-pic/master/3.png)

so , how can i  go on load testing?
i don't know what to do next . i am a newer, thanks .

**Comment by Arnold1** [comment]
I use siege for some simple load testing:
```
siege -c10 -t10S --content-type "application/json" --header="X-Model:10" 'http://xxx.com POST < predict.json'
```

**Comment by howardjohn** [comment]
Why does the virtual service have `host: *`? The templates do not have this: https://github.com/istio/tools/blob/3e58d64a1c8e84a861f2205a6d45d6c1a5219e47/perf/load/templates/istio-ingress.gen.yaml#L37-L38

**Comment by Zhangkaikang** [comment]
> Why does the virtual service have `host: *`? The templates do not have this: https://github.com/istio/tools/blob/3e58d64a1c8e84a861f2205a6d45d6c1a5219e47/perf/load/templates/istio-ingress.gen.yaml#L37-L38

yes，but i want to access it remotely . now all host can access this ip.

**Comment by Zhangkaikang** [comment]
when i set up this service. the deployment client and badhealth not ready, and cannot find GATEWAY_URL.
```
./setup_large_test.sh 1
```
![](https://raw.githubusercontent.com/Zhangkaikang/md-pic/master/6.png)
![](https://raw.githubusercontent.com/Zhangkaikang/md-pic/master/7.png)
my env is EKS, 
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.7-eks-1861c5", GitCommit:"1861c597586f84f1498a9f2151c78d8a6bf47814", GitTreeState:"clean", BuildDate:"2019-09-24T22:12:08Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-ba3d77", GitCommit:"ba3d77818a38ddd3bbe1cb5fce0a68644770244f", GitTreeState:"clean", BuildDate:"2019-12-12T19:13:29Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
$ istioctl version
client version: 1.4.2
control plane version: 1.4.2
data plane version: 1.4.2 (48 proxies)
```

For find GATEWAY_URL,
```
it should be 
$ kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.status.loadBalancer.ingress[0].hostname}'

not as follow
$ kubectl -n istio-system get service istio-ingressgateway -o 'jsonpath={.status.loadBalancer.ingress[0].ip}'
```

So how should I solve this problem？
