### ISSUE TITLE
pilot: glide Failures and private IPs

### ISSUE THREAD

**Issue by gnirodi** [istio/istio#1966]
I seem to be running into errors trying to run glide update. Also for the main repo we should never have anything pulling from private IPs like 192.30.255.112. This is not only a bug but a security issue. Please fix ASAP. It's holding up development on multi-zone hybrid for the Dec release. We have a tight deadline.  

Summarly assigning this issue to
- ldemailly who is shepherding Istio releases atm
- costinm because we the error seems to be hinting at some nested dependency.

Please redirect as necessary.

============================================================
[ERROR]	Update failed for github.com/googleapis/googleapis: Unable to get repository: Cloning into '/home/XXXXXX/.glide/cache/src/git-github.com-costinm-googleapis.git'...
Warning: Permanently added 'github.com,192.30.255.112' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
: exit status 128
[ERROR]	Failed to do initial checkout of config: Unable to get repository: Cloning into '/home/XXXXXX/.glide/cache/src/git-github.com-costinm-googleapis.git'...
Warning: Permanently added 'github.com,192.30.255.112' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
: exit status 128

**Comment by gnirodi** [comment]
Downgrading to P2 given that I was able to recreate my entire dev setup just to get things going :-(

**Comment by rshriram** [comment]
closing as we don't support glide
