### ISSUE TITLE
Pods don't ready after install

### ISSUE THREAD

**Issue by yanolol** [istio/istio#19671]
**Bug description**
After install this pods can't ready

istio-egressgateway-76fff9f75-m52t6
`Readiness probe failed: HTTP probe failed with statuscode: 503`

istio-galley-7699c6f68b-ssvnc
`Back-off restarting failed container`

istio-ingressgateway-6b9f4bb9c6-xsh9t
`Readiness probe failed: HTTP probe failed with statuscode: 503`

istio-pilot-7f7bcbc666-5v8f5 (discovery)
`Readiness probe failed: Get http://10.233.101.216:8080/ready: net/http: request canceled (Client.Timeout exceeded while awaiting headers)`

istio-policy-7c59d7fc5f-4dbpf
`Liveness probe failed: Get http://10.233.101.215:15014/version: dial tcp 10.233.101.215:15014: connect: connection refused`

istio-telemetry-5ff8cbcb8b-sn42w (mixer)
`Liveness probe failed: Get http://10.233.101.214:15014/version: dial tcp 10.233.101.214:15014: connect: connection refused`

**Expected behavior**
![image](https://user-images.githubusercontent.com/9301076/71113815-29a59e00-21ad-11ea-80a8-c1f8c7856ff9.png)

**Steps to reproduce the bug**
Install istio 1.14 with helm.
```
helm install install/kubernetes/helm/istio --name istio --namespace istio-system \
    --values install/kubernetes/helm/istio/values-istio-demo.yaml
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
'Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
'

**How was Istio installed?**
Helm/tiller

**Environment where bug was observed (cloud vendor, OS, etc)**
Calico
RHEL 7.6

**Comment by howardjohn** [comment]
Can you get logs, not the output of describe? Specifically for Galley, the others are failing because galley is failing

**Comment by yanolol** [comment]
Galley
https://raw.githubusercontent.com/yanolol/logs/master/galley.log

Others logs:

pilot
https://raw.githubusercontent.com/yanolol/logs/master/discovery.log

ingressgateway
https://raw.githubusercontent.com/yanolol/logs/master/istio-proxy.log

policy
https://raw.githubusercontent.com/yanolol/logs/master/mixer.log

I trying install in another cluster with k8s 1.15 but i have a same issue.

**Comment by howardjohn** [comment]
Can you output that yaml of the galley pod? The arguments should look like:

```
          - --enable-reconcileWebhookConfiguration=true
          - --validation-webhook-config-file
          - /etc/config/validatingwebhookconfiguration.yaml
          - --monitoringPort=15014
          - --log_output_level=default:info
```


But I suspect somehow it ended up looking like
```
          - --enable-reconcileWebhookConfiguration=true
          - --validation-webhook-config-file
          - --monitoringPort=15014
          - --log_output_level=default:info
```

It is trying to read a file ` --monitoringPort=15014` which is not a file

**Comment by yanolol** [comment]
Has this commands

      containers:
        - name: galley
          image: 'gcr.io/istio-testing/galley:latest'
          command:
            - /usr/local/bin/galley
            - server
            - '--meshConfigFile=/etc/mesh-config/mesh'
            - '--livenessProbeInterval=1s'
            - '--livenessProbePath=/tmp/healthliveness'
            - '--readinessProbePath=/tmp/healthready'
            - '--readinessProbeInterval=1s'
            - '--deployment-namespace=istio-system'
            - '--insecure=true'
            - '--enable-reconcileWebhookConfiguration=true'
            - '--validation-webhook-config-file'
            - '--monitoringPort=15014'
            - '--log_output_level=default:info'

**Comment by yanolol** [comment]
I changed to:

      containers:
        - command:
            - /usr/local/bin/galley
            - server
            - '--meshConfigFile=/etc/mesh-config/mesh'
            - '--livenessProbeInterval=1s'
            - '--livenessProbePath=/tmp/healthliveness'
            - '--readinessProbePath=/tmp/healthready'
            - '--readinessProbeInterval=1s'
            - '--deployment-namespace=istio-system'
            - '--insecure=true'
            - '--enable-reconcileWebhookConfiguration=true'
            - '--validation-webhook-config-file'
            - /etc/config/validatingwebhookconfiguration.yaml
            - '--monitoringPort=15014'
            - '--log_output_level=default:info'
I killed other pods and work!

**Comment by yanolol** [comment]
Guys

It's work only in K8S 1.15

> I changed to:
> 
> ```
>   containers:
>     - command:
>         - /usr/local/bin/galley
>         - server
>         - '--meshConfigFile=/etc/mesh-config/mesh'
>         - '--livenessProbeInterval=1s'
>         - '--livenessProbePath=/tmp/healthliveness'
>         - '--readinessProbePath=/tmp/healthready'
>         - '--readinessProbeInterval=1s'
>         - '--deployment-namespace=istio-system'
>         - '--insecure=true'
>         - '--enable-reconcileWebhookConfiguration=true'
>         - '--validation-webhook-config-file'
>         - /etc/config/validatingwebhookconfiguration.yaml
>         - '--monitoringPort=15014'
>         - '--log_output_level=default:info'
> ```
> 
> I killed other pods and work!

**Comment by yanolol** [comment]
In K8S 1.16 Galley is ready but Pilot, Telemetry, Trancing, Policy, Ingress and Egress not ready.

```
2019-12-19T19:00:23.662438092Z 2019-12-19T19:00:23.662116Z	info	Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 0 successful, 0 rejected; lds updates: 0 successful, 0 rejected
2019-12-19T19:00:24.606133739Z [Envoy (Epoch 0)] [2019-12-19 19:00:24.606][17][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:91] gRPC config stream closed: 14, no healthy upstream
2019-12-19T19:00:24.606178339Z [Envoy (Epoch 0)] [2019-12-19 19:00:24.606][17][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:54] Unable to establish new stream
2019-12-19T19:00:25.662309237Z 2019-12-19T19:00:25.662162Z	info	Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 0 successful, 0 rejected; lds updates: 0 successful, 0 rejected
```

**Comment by howardjohn** [comment]
Please add the logs for other components. There are dependencies between the components so showing the log for ingress doesn't help much if pilot is down.

**Comment by yanolol** [comment]
istio-egressgateway
https://raw.githubusercontent.com/yanolol/logs/master/istio-egressgateway-76fff9f75-xpczm.log

istio-ingressgateway
https://raw.githubusercontent.com/yanolol/logs/master/istio-ingressgateway-6b9f4bb9c6-wr4gw.log

istio-policy
https://raw.githubusercontent.com/yanolol/logs/master/istio-policy-7c59d7fc5f-vhmxz.log

istio-telemetry
https://raw.githubusercontent.com/yanolol/logs/master/istio-telemetry-5ff8cbcb8b-rhb9f

istio-tracing
https://raw.githubusercontent.com/yanolol/logs/master/istio-tracing-55c965d5b6-9vclb%20Logs

istio-pilot
https://raw.githubusercontent.com/yanolol/logs/master/istio-pilot-7f7bcbc666-hhsxv%20Logs

**Comment by howardjohn** [comment]
It cannot connect to galley, is that running ok?

**Comment by yanolol** [comment]
I think is my cluster, i creating a new cluster with same version K8S 1.16 and works.

Thanks @howardjohn !
