### ISSUE TITLE
Pilot build instructions broken

### ISSUE THREAD

**Issue by gnirodi** [istio/istio#1967]
Instructions at https://github.com/gnirodi/istio/tree/master/pilot don't seem to be working :-(

make setup
/bin/bash: bin/install-prereqs.sh: No such file or directory
make: *** [setup] Error 127

**Comment by vadimeisenbergibm** [comment]
@kyessenov @rshriram after being integrated into istio repository, should pilot continue to have its build instructions, Makefile etc. ? Or everything should be performed from the istio/istio/Makefile ?

**Comment by vadimeisenbergibm** [comment]
@elevran @GregHanson @ijsnellf thoughts on the comment above?

**Comment by linsun** [comment]
Would be good to have, can we use something like below:

```go get github.com/golang/dep/cmd/dep
dep ensure
go build ./pilot/cmd/pilot-discovery/main.go

env GOOS=linux GOARCH=amd64 go build

env GOOS=darwin GOARCH=amd64 go build
```

**Comment by gnirodi** [comment]
Downgrading to P2 given that I was able to recreate my entire dev setup just to get things going :-(

Also I've now begun relying on istio/istio instead of istio/istio/pilot

**Comment by sdake** [comment]
This issue can be closed.  As a result of the build refactor, this issue no longer exhibits.
