### ISSUE TITLE
Support SDS flow that gets root certificates or a workload certificate from existing files

### ISSUE THREAD

**Issue by lei-tang** [istio/istio#19686]
**Describe the feature request**
A user may configure root CA certificates or a certificate secret for a workload's Envoy (similar to the secret file mount mechanism of Citadel) and mounted the CA certificates and the secret to the workload pod. Envoy reads the certificates from the path storing the mounted certificates. With SDS being the default in Istio 1.5, we need to support the SDS flow that gets root CA certificates or a workload certificate from existing files.
This feature can be used for:
- Bootstrap the Envoy to istiod connection when k8s CA API is not present and istiod uses a Citadel issued certificate.
- CA migration.
- Support file-mounted certificate after migrating to SDS.

**Describe alternatives you've considered**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
Done rfom #19687
