### ISSUE TITLE
Support delta_grpc ADS API

### ISSUE THREAD

**Issue by l8huang** [istio/istio#19681]
**Describe the feature request**

Envoy is going to support [DELTA_GRPC](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/core/config_source.proto#enum-core-apiconfigsource-apitype).
For Istio, I wonder if DELTA_GRPC is in road-map.

We encountered scalability issue with 5k RouteConfig and 20k ClusterConfig, that caused us withdrawing traffic migration to Istio ingress gateway. Looks like such kind of scalability issue can be resolved by using DELTA_GRPC, so we are looking for working on it, please kindly let me know if any one already working on it, so we can avoid overlapped effort or collaborate.
 

[X ] Performance and Scalability

**Comment by howardjohn** [comment]
Related, about incremental endpoint updates: https://github.com/istio/istio/issues/19287

I don't think there is a lot of work on supporting delta_grpc since it is a large change to implement and its pretty new

**Comment by l8huang** [comment]
After went through related code and document, I understand this could be a large change. 

Currently polit generates CDS/LDS/RDS config on-the-fly for each proxy when DiscoveryServer.pushConnection() is called, and config pushing is triggered by type(Gateway/Destination/...) instead of individual resource, this works for state-of-the-world xDS. But for delta xDS, which supports incremental resource adding/removing and resource versioning, the current implemenation can't provide such kind of flexibility. 

Looks like a kind of data store should be introduced to hold all generated CDS/EDS/LDS/RDS/VHDS configs, then proxies can subscribe configs which they interested in. When any change happens to a resource in this data store, a handler can find out proxies which subscribed to that resource, then push corresponding change out. Basically the proxy config data store should have below capabilities:
- fine granular updating on proxy config data store when k8s resources or Istio configs changed
- resource versioning, if a proxy reconnected, only changed resources need to be pushed
- resource can be subscribed, then if change happened, subscribor can be informed

Below are some possibilities for implementing proxy config data store in my mind:
- implement a in-memory data store, pilot constructs it when start-up. 
  A problem is data are not persistent, so after pilot restarted, service-side(pilot) resource version are different from client-side(proxy), proxy can't be simply reconnected. Pilot deployment with multiple replicas has similar issue, which can be resolved by consensus algorithm(e.g raft), but it may make pilot over complicated.
- leverage stand-alone data store, e.g. etcd.
  In this way, data are persistent, but need to take care of data consistency between k8s/Istio resource and proxy config in some case, e.g restart pilot.

Bases on different design principle, one can make different choice. Any thoughts?

**Comment by howardjohn** [comment]
Having some persistent data sounds like it will be far too complicated, we should remain as stateless as possible

**Comment by seflerZ** [comment]
Time to moving forward. The Delta xDS has been ready on Envoy side. @howardjohn , do you have any suggestions on implementing this?

**Comment by YonkaFang** [comment]
@l8huang 
proxy level config store is too expensive even stored stand alone. I think we should use common resource to compose proxy config rather than build a totally new copy. And that means we may have to decide to give up some "too proxy specific" features.

**Comment by hzxuzhonghu** [comment]
@seflerZ I am ok with this, but i am concerned we would need to cache more configs per proxy than now.  And another concern is `Allows the Envoy to on-demand / lazily request additional resources. For example, requesting a cluster only when a request for that cluster arrives.` this will slow down app request

**Comment by seflerZ** [comment]
@hzxuzhonghu We can just cache each resource's version instead of content. And when requesting, we generate the content like it was but filter it through the version. About the lazy request, we can disable it in the first iteration before finding any solution.

**Comment by rshriram** [comment]
Let us start with CDS first and measure the impact

**Comment by hzxuzhonghu** [comment]
@rshriram Not sure if both delta xds and the current can be used simultaneously.

**Comment by ramaraochavali** [comment]
I think SOTW and Delta can not be combined when using ADS because the request and response types are different DiscoveryRequest/Response vs DeltaDiscoveryRequest/Response.

**Comment by seflerZ** [comment]
Yes. The Delta xDS uses another port and interface. Sidecar can be configured to send CDS in Delta and others in SOTW.

**Comment by ramaraochavali** [comment]
> Sidecar can be configured to send CDS in Delta and others in SOTW.

I do not think this is correct when using ADS

**Comment by gengleilei** [comment]
Delta xDS and SOTW are independent of each other, and can push ordinary LDS and EDS through ADS, and CDS through delta xDS.

**Comment by ramaraochavali** [comment]
Are you sure that LDS and EDS through ADS and CDS through delta xDS works? Based on the documentation here https://www.envoyproxy.io/docs/envoy/latest/api-docs/xds_protocol specifically this part - Looking at last two points when you use ADS either you have to use SOTW for all resources or use Delta for all resources. I thought combination is not possible.

```
So, the four variants of the xDS transport protocol are:

State of the World (Basic xDS): SotW, separate gRPC stream for each resource type
Incremental xDS: incremental, separate gRPC stream for each resource type
Aggregated Discovery Service (ADS): SotW, aggregate stream for all resource types
Incremental ADS: incremental, aggregate stream for all resource types
```

and 

The RPC service and methods for the aggregated protocol variants are:

```
SotW: AggregatedDiscoveryService.StreamAggregatedResources
Incremental: AggregatedDiscoveryService.DeltaAggregatedResources
```

**Comment by seflerZ** [comment]
It's pretty like we have two management systems. One for CDS using "DeltaAggregatedResources" and one for others using "StreamAggregatedResources". The documents tells you must use "State of the World" or the Delta within a connection not system wide. It's pretty like the following diagram shows:
![image](https://user-images.githubusercontent.com/2093588/77879271-9f310800-728c-11ea-8e61-180b96ff6bc2.png)

**Comment by adiprerepa** [comment]
This is now on the 2021 roadmap.

https://docs.google.com/document/d/1hwC81_jS8qARBDcDE6VTxx6fA31In96xAZWqfwnKhpQ

**Comment by hzxuzhonghu** [comment]
Could you propose a design before start?

**Comment by adiprerepa** [comment]
https://docs.google.com/document/d/1hwC81_jS8qARBDcDE6VTxx6fA31In96xAZWqfwnKhpQ


This was reviewed in the networking meeting today, and we got approval.

**Comment by hzxuzhonghu** [comment]
I mean it is lack of critical details

**Comment by howardjohn** [comment]
@hzxuzhonghu the doc has been updated with low level details

**Comment by hzxuzhonghu** [comment]
Thanks, will take a look

**Comment by adiprerepa** [comment]
https://github.com/istio/istio/pull/31212 - PR for anyone who wants to take a look
