### ISSUE TITLE
WORKSPACE contains duplicate go_repository entries 

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio#1969]
I am new to Bazel so I am not sure if it is by intention. If so, maybe it should be documented in the WORKSPACE file.

Can be seen by running `grep " name " WORKSPACE | sort`

**Comment by ldemailly** [comment]
I am not a bazel expert, maybe martin ?

**Comment by mandarjog** [comment]
That is definitely an oversight. I attempted to remove some, but clearly they are there.

**Comment by kyessenov** [comment]
This is a bazel feature. It's ok to redefine names in a single skylark unit (e.g. WORKSPACE). The last one wins (as expected), and the definition is frozen after that. It's useful when overriding child imports.

**Comment by GregHanson** [comment]
Istio no longer requires bazel to build and the WORKSPACE file is no longer present in istio
