### ISSUE TITLE
Istio-proxy access log returns response code:0

### ISSUE THREAD

**Issue by rohit-tiwari-scmp** [istio/istio#19693]
**Bug description**
I have recently setup istio`1.4.2`in Dev environment, and have enabled side-car injection specific to project deployment using annotation. And in order to fully utilizse the service-mesh, i am keen to log the http-request/response traffic using Envoy accesslogs. I have made sure istio-proxy container get enough time to hijack the traffic before actual app container starts, i can see logs at istio-proxy but most fields are blank, specially response code is 0.

**Expected behavior**
Once Envoy access logging is enabled, istio-proxy sidecar container must capture http-request/response traffic at loglevel and must log response_code,  path, request_id etc.

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
Istio-version
client version: 1.4.0
control plane version: 1.4.2

kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.9", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-aliyun.1", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**

I didn't use helm, instead just used helm-client to generate manifests using `helm-template`command and later applied to setup helm.

**Environment where bug was observed (cloud vendor, OS, etc)**
Development

Sample access logs from istio-proxy container:

```{"bytes_sent":"202","upstream_cluster":"inbound|80||basic-service.guilds.svc.cluster.local","downstream_remote_address":"10.200.2.225:52570","authority":"-","path":"-","protocol":"-","upstream_service_time":"-","upstream_local_address":"127.0.0.1:37840","duration":"65001","downstream_local_address":"10.200.4.240:80","upstream_transport_failure_reason":"-","route_name":"-","response_code":"0","user_agent":"-","response_flags":"-","start_time":"2019-12-19T03:40:54.437Z","method":"-","request_id":"-","upstream_host":"127.0.0.1:80","x_forwarded_for":"-","requested_server_name":"-","bytes_received":"803","istio_policy_status":"-"}```

**Comment by howardjohn** [comment]
is this http traffic? see https://istio.io/docs/ops/configuration/traffic-management/protocol-selection/

**Comment by rohit-tiwari-scmp** [comment]
@howardjohn Thankyou so much for your quick suggestion. Works as a charm!!!

**Comment by rohit-tiwari-scmp** [comment]
Hi @howardjohn, could you please look into this issue too --> 

https://github.com/istio/istio/issues/19545

My colleague raised this one and we are trying to fix this for long time now. Many Thanks.

**Comment by howardjohn** [comment]
Closing as this is fixed. I don't know much about tracing but someone who does responded

**Comment by veera-chenna** [comment]
@rohit-tiwari-scmp / @howardjohn , We are seeing the same issue in istio-proxy egress traffic in the version `1.9.5`. What changes we need to do to for this?

**Comment by howardjohn** [comment]
Please don't comment on issues from 3 year ago; if there are _new_ issues they should be address in new issues. however, 1.9 is EOL so we would not provide support.
