### ISSUE TITLE
Version checks in `istioctl upgrade` should support dev/alpha/beta images as a target version

### ISSUE THREAD

**Issue by elfinhe** [istio/istio#19708]
The comparison should based goversion or something similar rather than just string comparing.

Here are some example versions:

- 1.4-dev 
- 1.4-alpha.c4ec4b8c102da86d4d02f4b268f9af60a35dee1c
- 1.4.0-beta.3

All those three should be treated as 1.4.0.

**Comment by howardjohn** [comment]
Why is 1.4-dev 1.4.0? Pilot treats it as 1.4.99999999999999

**Comment by elfinhe** [comment]
with hashicorp/go-version, the version.NewVersion("1.4-dev") will return a version 1.4.0 with pre="dev". I understand why we treat the dev one as the top patch in the minor version.

maybe in the upgrade check we should replace patch version to x.x.99999999999999 if we see pre="dev".

**Comment by howardjohn** [comment]
I am actually wrong, it is treating it as 1.4.0. See https://github.com/istio/istio/blob/3f92dab766c248aa22139be1a891d6c2fff173e1/pilot/pkg/model/context.go#L650

We should use the same logic

**Comment by elfinhe** [comment]
btw, "1.4-dev" cannot pass the semver check.
https://jubianchi.github.io/semver-check/#/version/1.4-dev
