### ISSUE TITLE
Stackdriver Telemetry v2 adapter logging output should be equivalent to what is done by the Mixer adapter

### ISSUE THREAD

**Issue by djazayeri** [istio/istio#19705]
**Describe the feature request**

The Stackdriver telemetry v2 adapter should send logging output equivalent to what was being sent with the Mixer adapter, as much as possible.

**Describe alternatives you've considered**

N/A

**Additional context**

From looking at https://github.com/istio/proxy/blob/master/extensions/stackdriver/log/logger.cc#L79 I believe that the following expected logging need to be added:

* source_uid: source.uid | ""
* source_ip: source.ip | ip("0.0.0.0")
* source_app: source.labels["app"] | ""
* source_owner: source.owner | ""
* destination_uid: destination.uid | ""
* destination_app: destination.labels["app"] | ""
* destination_ip: destination.ip | ip("0.0.0.0")
* destination_owner: destination.owner | ""
* api_name: api.service | ""
* api_version: api.version | ""
* api_claims: request.auth.raw_claims | ""
* api_key: request.api_key | request.headers["x-api-key"] | ""
* method: request.method | ""
* url: request.path | ""
* response_code: response.code | 0
* response_size: response.size | 0
* request_size: request.size | 0
* request_id: request.headers["x-request-id"] | ""
* latency: response.duration | "0ms"
* user_agent: request.useragent | ""
* response_timestamp: response.time
* received_bytes: request.total_size | 0
* sent_bytes: response.total_size | 0
* referer: request.referer | ""

I understand that a handful of these are infeasible; that's okay, we don't need 100% coverage.

**Comment by djazayeri** [comment]
FYI @mandarjog @bianpengyuan

**Comment by bianpengyuan** [comment]
Fix is cherry-picked to 1.4: https://github.com/istio/proxy/pull/2628
