### ISSUE TITLE
istioctl install prometheusOperator issues

### ISSUE THREAD

**Issue by richardwxn** [istio/istio#19714]
Tried using istioctl to install prometheusOperator and it doesn't work. And some CRD are missing.

run istioctl manifest apply --set values.prometheusOperator.enabled=true --force

**Comment by howardjohn** [comment]
it doesn't install the prometheus operator, it just adds the config to scrape istio to an existing prometheus operator install

**Comment by richardwxn** [comment]
yep but I have to look into the installer charts to understand that. Actually we should be able to choose to install prometheus plus the extra configs from prometheusOperator or to install prometheusOperator and let it handles the installation of prometheus stuffs? maybe we should document that better otherwise it is a bit confusing

**Comment by howardjohn** [comment]
cc @douglas-reid

**Comment by douglas-reid** [comment]
Whether or not we should install third-party operators ourselves remains an unresolved question.  Let's start with a position doc that we can circulate to the appropriate WGs to get a better resolution moving forward.

In the short term, adding docs that suggest that installing prom operator is a pre-req seem fine to me.

**Comment by howardjohn** [comment]
I have no strong opinions. On one hand, I want to get us out of the business of managing third party stuff. On the other hand, its not so bad to install 168 lines of yaml: https://github.com/coreos/prometheus-operator/blob/master/bundle.yaml. On the other-other hand, that may be the responsibility of tools like OLM and not istio operator.

**Comment by framled** [comment]
at 1.4.6 if `createPrometheusResource: true` flag is enable you get the following error

`Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(Prometheus.spec.serviceMonitorSelector): unknown field "any" in com.coreos.monitoring.v1.Prometheus.spec.serviceMonitorSelector
`
