### ISSUE TITLE
`istioctl manifest migrate|apply|generate` command always prints `proto: tag has too few fields: "-"` error

### ISSUE THREAD

**Issue by nak3** [istio/istio#19735]
**Bug description**

[X] Installation

**Expected behavior**

`proto: tag has too few fields: "-"` should not be printed.

**Steps to reproduce the bug**

#### 1. Prepare values.yaml (any values can produce the error)

```
$ cat <<EOF > values.yaml
gateways:
  enabled: true
EOF
```

#### 2. Run `istioctl manifest migrate`

```
$ istioctl manifest migrate values.yaml
proto: tag has too few fields: "-"      # <= HERE
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
  ... snip ...
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
$ istioctl version --remote=false --short=false
version.BuildInfo{Version:"1.4.2", GitRevision:"35eb9dc7c6e78dac5bd8c3d142bc2a4601616932-dirty", GolangVersion:"go1.13.4", BuildStatus:"Modified", GitTag:"1.4.2"}
```

The error is caused when this line is called.

https://github.com/istio/operator/blob/f623b65d63f2b3fa68efcea9e89090b4b3fb65b3/cmd/mesh/manifest-migrate.go#L108

And ObjectMeta here causes the error.

https://github.com/istio/operator/blob/f623b65d63f2b3fa68efcea9e89090b4b3fb65b3/pkg/apis/istio/v1alpha2/istiocontrolplane_types.proto#L175

**Comment by elfinhe** [comment]
@morvencao do you know why ObjectMeta will cause the `proto: tag has too few fields: "-"` error?

**Comment by howardjohn** [comment]
we have this same problem in some of our test framework somewhere - see https://prow.istio.io/view/gcs/istio-prow/logs/integ-mixer-k8s-tests_istio_postsubmit/975 for an example

**Comment by martinbaillie** [comment]
I'm seeing this also on the `x multicluster` commands FWIW

**Comment by elfinhe** [comment]
I took a look at the error call stack this afternoon. seems like gogo protobuf cannot marshal the [time.Time](https://github.com/kubernetes/apimachinery/blame/master/pkg/apis/meta/v1/time.go#L34) in apimachinery. I guess this is a typo in the tag of Time.

**Comment by morvencao** [comment]
It's caused by some fields in `ObjectMeta` imported from kubernetes API, we thought that copying the `ObjectMeta` definition to operator API will resolve this, but it would introduce much more maintain work because there are plenty of fields in `ObjectMeta`.

**Comment by elfinhe** [comment]
Related to https://github.com/istio/operator/pull/382?

**Comment by ostromart** [comment]
I think an acceptable solution would be to add a link to this issue in the log.

**Comment by elfinhe** [comment]
logging the issue does not help here, the `proto: tag has too few fields: "-" ` will still show up in the stderr.

**Comment by esnible** [comment]
I also see this if `--set` use used.  For example

```
istioctl manifest generate --set values.global.mtls.enabled=true > /dev/null
proto: tag has too few fields: "-"
```

**Comment by esnible** [comment]
I left this comment at https://github.com/kubernetes/kubernetes/issues/86739#issuecomment-585830624 but will repeat it here.

The problem is in either the gogo/protobuf library or the apimachinery library.  It can be reproduced with this short code:

```
import (
	"github.com/gogo/protobuf/proto"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)
...
	_ = proto.GetProperties(reflect.TypeOf(metav1.Time{}))
```

Is `protobuf:"-"` a valid tag?  If so, fix https://github.com/gogo/protobuf/blob/master/proto/properties.go#L368 so that it ignores `"-"` the same way it ignores `""`.   If not, replace `"-"` with something valid.

I suspect that gogo/protobuf should ignore `-`.  If you agree, I could make a PR and see what they think of it.

**Comment by ostromart** [comment]
sgtm. I also have a workaround PR which avoids the use of jsonpb unmarshal in places where it generates console errors that can't be suppressed.
https://github.com/istio/api/pull/1297
