### ISSUE TITLE
Multi Control Plane: do not prune other control planes with operator

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#19741]
Today, I cannot install two control planes with istioctl, because it will prune the other one every time I try to. I am not certain if the controller behaves the same, but it likely does.

We need some way to prevent this from happening. Likely this would just be some additional label that identifies the control plane, and only prune resources with that label.

One thing we need to be cautious of is shared/cluster wide resources - we don't want to prune CRDs, cluster roles, etc

**Comment by ostromart** [comment]
My initial thoughts on this would be to add a label to all resources which have the value of the parent ICP CR namespace-name, and prune only on selected label values.

**Comment by howardjohn** [comment]
With istioctl you don't have a CR though, but I agree in principal. We could have a flag `--identifier` or something to istioctl I guess? And make it have a default so only people with multiple control planes need to worry about it

**Comment by esnible** [comment]
Would it be reasonable to use a CR in the istioctl case?  cf. https://github.com/istio/istio/issues/20000

**Comment by howardjohn** [comment]
I think we just need to annotate all resources with the revision and then
set up the pruning to take that into account. I had this working locally at
one point but got distracted by some 1.5 tasks
