### ISSUE TITLE
Add helm chart for operator deployment

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#19744]
A lot of users are running helm, so it makes sense to meet them where they are and support helm. We don't need to continue to support both istioctl+helm fully, but instead should just have a simple helm chart, that follows standard best practices and is present in https://hub.helm.sh/.

This chart will be ~100 lines with minimal templating

**Comment by MateusAmin** [comment]
It will also enable chart maintainers that have dependencies on Istio to be able to cleanly specify them in their Helm charts. Helm v3 is a client side only package manager for end users, and Helm hub is federated. All in all its pretty similar to the 'apt-get model' now. Link to existing issue:

https://github.com/istio/istio/issues/14951

**Comment by stevehipwell** [comment]
@ostromart this issue and issue #21861 have both been closed yet PR #21864 is only recorded as a partial implementation. I've tried to figure out if the operator Helm chart was actually built but I can't see it in the release artifacts.

**Comment by ostromart** [comment]
They are in manifests/charts/istio-operator

**Comment by stevehipwell** [comment]
Thanks @ostromart. Is there a reason why the chart isn't being published?

**Comment by koalalorenzo** [comment]
Similar to #29222 and #25467
