### ISSUE TITLE
Add possibility to inject values to readinessGates via Sidecar Injector 

### ISSUE THREAD

**Issue by kuzaxak** [istio/istio#19757]
**Describe the feature request**
I want to use advanced pod `readinessGates` logic to control traffic of pods with Istio. I can modify `preStop` and `postStart` hooks to change the custom pod condition. 

With `readinessGates` I can mark the pod as unready in a moment when termination signal is received, without manipulating envoy draining process via `localhost:15000/healthcheck/fail`.

I want to add support of `readinessGates` spec field to sidecar injector template.

**Describe alternatives you've considered**
Using `preStop` hook [is not enough][1] to control gracefull rolling with Istio and eliminate the amount of 503 UC errors.

**Additional context**

[1]: https://github.com/envoyproxy/envoy/issues/2920#issuecomment-540709506

**Comment by hzxuzhonghu** [comment]
FYI: the kubernetes sidecar container kep will be targetted on 1.18 release.
