### ISSUE TITLE
Gateway component not enabled by .values

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#19799]
`--set values.gateways.istio-egressgateway.enabled=true` does nothing -- egress is still disabled. `--set values.gateways.istio-egressgateway.enabled=true --set gateways.components.egressGateway.enabled=true` must be set, which is breaking the helm passthrough API

**Comment by richardwxn** [comment]
I checked the code and it seems like it is a gap not just for egressgateway. Take a look at the IsComponentEnabledInSpec function at https://github.com/istio/operator/blob/master/pkg/name/name.go#L142, it only check the enablement value from ISCP api node for istio components and only the thirdParty component which is not defined in ISCP would be check against values pass through as well.

**Comment by richardwxn** [comment]
I would verify again and create a PR to fix it

**Comment by myidpt** [comment]
Hi Martin, can you help to take a look?

**Comment by richardwxn** [comment]
The new PR to fix core component enablement issues after new operator API merge: https://github.com/istio/istio/pull/20244.

However, the enablement issue for addOnComponents seems more complicated, check detail here:  https://github.com/istio/istio/issues/20316

**Comment by howardjohn** [comment]
@richardwxn any update on this?

**Comment by richardwxn** [comment]
@howardjohn the fix was merged already, closing it
