### ISSUE TITLE
Use Sidecar CRDs to implement pilot-level service-on-demand

### ISSUE THREAD

**Issue by YonkaFang** [istio/istio#19796]
**Describe the feature request**

Currently we're lacking of a mechanism that limits the size of data fetching from MCP/registries or naming it as `pilot-level-service-on-demand`.

For MCP, `initRequests` seems can be used to accomplish that, but it's pretty poor and limited to the MCP way.

**Describe alternatives you've considered**

Considering that:

1. What pilots needs is determined by what connected sidecars needs.

2. Current SidecarScope concept (or Sidecar CRDs) represents the services exposed to relevant sidecars and that can be understood as what sidecars needs.

Thus: 

We can calculate the services needed by known sidecars from Sidecar CRDs and tell them to proper upstreams (MCP server or other registries).

Further: 

We can identifying the pilot instances with labels (or other things) and send relevant Sidecar CRDs to them accordingly and then let the sidecars connect to correct pilots to implement `service sharding`.

[ X ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

To tell the truth, the ServiceEntry type data(services and relevant instances) is so huge in our production enrivonment that it's impossible for us to get all data stored/served in a single pilot. So it's a really practical problem.

We're working on this and appreciate any ideas about it.

**Comment by howardjohn** [comment]
This seems like something that would be much more complicated than it sounds like
In order to get the Sidecar CRDs we need to start the mcp connection, so at that point we can't tell it to limit. Then we also need to continuely update which Services we care about, which I believe is not supported by mcp

**Comment by YonkaFang** [comment]
> This seems like something that would be much more complicated than it sounds like
> In order to get the Sidecar CRDs we need to start the mcp connection, so at that point we can't tell it to limit. Then we also need to continuely update which Services we care about, which I believe is not supported by mcp

Yeah. How we can enhance MCP protocol is another topic. Such as add init negotiation and update the resources we care about. In our customized registry controller, these are already implemented while we'd like migrate that to MCP later.

As I can see, `update the resource we care about` does not conflict with current protocol design though I have not dived into the MCP server implementation in gally.

I have to comment that this issue is mainly about this idea's correctness or conformation with istio design concept rather than the implementation gap.
