### ISSUE TITLE
Implement deploying egress gateway with additional containers by Istioctl manifest

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio#19792]
In some cases, additional proxy must be deployed at the gateway, see https://istio.io/docs/tasks/traffic-management/egress/wildcard-egress-hosts/#setup-egress-gateway-with-sni-proxy.

Helm contained the following options to support such scenario:

- additionalContainers
- configVolumes
- secretVolumes

These options are missing in  https://github.com/istio/operator/blob/36fc1b825f4fbea45b11c46abba8dee779f644bc/pkg/apis/istio/v1alpha2/istiocontrolplane_types.pb.go#L2062

**Describe the feature request**
istioctl manifest must support deploying egress gateways with additional containers and volumes.

**Describe alternatives you've considered**
Using Helm.

[ ] Configuration Infrastructure
[ ] Docs
[X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by vadimeisenbergibm** [comment]
cc @GregHanson

**Comment by howardjohn** [comment]
Could be part of the generic k8s spec?

**Comment by vadimeisenbergibm** [comment]
@howardjohn 
> Could be part of the generic k8s spec?

Yes, I think so.
