### ISSUE TITLE
Enhance Sidecar CRD to allow exposing instances of specified clusters

### ISSUE THREAD

**Issue by YonkaFang** [istio/istio#19797]
**Describe the feature request**

We're facing an exact requirement that allows exposing the instances of some specified clusters for services. But current Sidecar CRD only describes the services exposed.

**Describe alternatives you've considered**
We are considering the straight way: add a field which exactly represents the clusters needed to `Sidecar` CRD as below.
  
```go
type Sidecar struct {
    // ...

    Hosts []string
    // Add `clusters` constraints to exposed service hosts which means only instances
    // from the specified clusters of relevant service are exposed to the sidecars.
    // Absence of a service means `all known clusters`.      
    HostCluters map[string][]string  // The fact that pb does not support repeated item as map value is not considered here.
}
```

And later the `HostCluters` info of `Sidecar` CRDs will be aggregated to `SidecarScope` along with `Hosts` and used in `ProxyNeedsPush` and `pushEds`.

[ X ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

Our case also requires that the endpoints of a service may be different between SidecarScopes. This may be archieved with subsets and it's the thing to be considered in the next stage.

PS: In out scenario, registry controller needs to know the exact cluster name to fetch the data of ServiceEntry type from relevant cluster.

Thanks.

**Comment by howardjohn** [comment]
Is it feasible to just not fetch those service entries, or do you have some services that can see Service X in multiple clusters and others that can only add it in some clusters?

**Comment by YonkaFang** [comment]
> Is it feasible to just not fetch those service entries, or do you have some services that can see Service X in multiple clusters and others that can only add it in some clusters?

Yes, as I mentioned in #19796 our registry behaves as fetch-what-you-need which may diff with typical way istio fetch config/ServiceEntries.

Also we should know the exact cluster name to add a member cluster and fetch what we need. Unlike the k8s multicluster registry just simply fetches all resource from all known clusters.

PS: As our production environment is pretty large scale (ten thousands of services and millions of service instances), our most components MUST behaves likes this.

**Comment by hzxuzhonghu** [comment]
@YonkaFang I assume you use single control plane multi clusters model.  What's your use case for only route to specific clusters?  BTW, we are considering to support cluster level service affinity.

**Comment by YonkaFang** [comment]
@hzxuzhonghu 

In our env there're pretty many clusters and it's not economic to connect to all of them. Our consumers/workloads depend explicitly some of them and route to them.

I think the "cluster level service affinity" may be what we need from its literal meaning. Could I get some details of that?

**Comment by howardjohn** [comment]
is it feasible to just create service entries only for the service in the
other clusters you need?

**Comment by YonkaFang** [comment]
@howardjohn Do you mean creating a service for a cluster each like `xx.com.cluster1`, `xx.com.cluster2` ...? If in this way we'll be a touch position on how to build the routes.

Currently we only care about how to describe the `depending clusters of service` with a standard istio concept as relevant support is ready on our customized registry controller side.

How to split the instances and send only needed (clusters's) instances is leaved later and we've considered the subset way.

**Comment by seflerZ** [comment]
I think what @YonkaFang need is fully dynamic routing between different clusters in specified service. For example, a "Service" named A has endpoints located in data center Shanghai, Hangzhou, Los Angeles and Tokyo. That is to say, service A got 3 "Clusters". If another "Service" B depends on A, and its endpoints located in Hangzhou. In order to guarantee access reliability, it wants endpoints from Shanghai, Hangzhou. That is to say, a dependency and restriction description for "Clusters" called is need in "SidecarScope" despite the "Service" attribute.

@howardjohn A simple new "ServiceEntry" for "Shanghai, Hangzhou" group maybe a temporary solution but doesn't fully solve the problem because the grouping rule is fully dynamic(Such as a grouping requirements for "Los Angeles and Tokyo"?). Since the Istio system did have a concept of the "Cluster", I think its feasible to support restriction configuration in "SidecarScope" CRD. It is just a more specified restriction compared to "Service" level.

**Comment by howardjohn** [comment]
How are you doing multicluster service discovery today? I think for complex scenarios like this it helps to know more about your environment so we can come to with a better solution

**Comment by YonkaFang** [comment]
@howardjohn Now we're using a customized registry controller and it can do the `multicluster service discovery` by connecting to each cluster it self and merging all endpoints data from clusters. 

We're considering refactoring it to the multicluster way like k8s and the multi-MCP-server way later.

**Comment by hzxuzhonghu** [comment]
Have you read about the locality loadbalancing? Does it satisfy your requirements?

**Comment by YonkaFang** [comment]
> Have you read about the locality loadbalancing? Does it satisfy your requirements?

How to route to correct cluster or do the loadbalancing based on locality/cluster are the later things. As mentioned above, what we care about is that **how to describe the dependencies on specified clusters of service** and so that we can _tell them to registry controller to fetch relevant ServiceInstances_.

**Comment by hzxuzhonghu** [comment]
You can do it in destinationrule? You can set locality loadbalancer with failover.

**Comment by YonkaFang** [comment]
@hzxuzhonghu Yah we've considered do it in destinationrule and splits endpoints from clusters to subsets. 

But, firstly I need to tell the registry controller to get thoses endpoints of **needed clusters** as we can not fetch them of all clusters as mentioned above. And what we're talking about is how to describe that.
