### ISSUE TITLE
Remove the UDS paths shared across pods for SDS

### ISSUE THREAD

**Issue by lei-tang** [istio/istio#19819]
**Describe the feature request**
With current SDS implementation, Node Agent (running as a daemonset) and Envoy communicate through a UDS path that is shared across pods. To safeguard such UDS paths, users need to configure pod security policies. This feature request is to remove the UDS paths shared across pods for the SDS workflows in Istio 1.5 (the design document of the identity workflows for workloads in Istio 1.5 is [here](https://docs.google.com/document/d/10I_BchyXP0ZEGkuCBM3_q4ny6Ji5ygH5nZdlUJ_PNss/edit#heading=h.xw1gqgyqs5b)).

**Describe alternatives you've considered**
Keep the Istio 1.4 behavior as the default behavior.

**Additional context**

**Comment by howardjohn** [comment]
done
