### ISSUE TITLE
Pilot tests incorrectly succeed after panic

### ISSUE THREAD

**Issue by nmittler** [istio/istio#19824]
This was discovered when investigating https://github.com/istio/istio/pull/19823. Pilot has built-in panic handling logic to prevent bad envoy filters from bringing down pilot.

This has the unfortunate side effect of hiding real test failures.

**Comment by howardjohn** [comment]
Possible ideas: turn off recovery for tests, or potentially make the recover finer scoped, or have the places it could panic instead return an error if possible.

**Comment by hzxuzhonghu** [comment]
This recover mechanism is originally added to handle unexpected panic, which we can not handle. This kind of panic may be from libs we import. Once we are confident this will never occur, we can simply remove it.

**Comment by howardjohn** [comment]
It's not about libraries we import, we definitely should panic in that
case. It was about arbitrary EnvoyFilter configs from users crashing pilot

**Comment by hzxuzhonghu** [comment]
IC, the protobuf ops failure.
