### ISSUE TITLE
Port 80/443 not working with virtual service 

### ISSUE THREAD

**Issue by sekhrivijay** [istio/istio#19835]
**kubectl version**
`Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:51:13Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.4-gke.22", GitCommit:"a6ba43f5a24ac29e631bb627c9b2a719c4e93638", GitTreeState:"clean", BuildDate:"2019-11-26T00:40:25Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}`

**istioctl version** 
`client version: 1.4.2
control plane version: 65b6870f1e3bf73fc688a02d10963ea0158e96c6-dirty
data plane version: 1.2.10-gke.0 (22 proxies)`

Modified sample httpbin example 

**service**
![image](https://user-images.githubusercontent.com/6306308/71549640-56646d00-2986-11ea-8a84-c4d6ae0667d1.png)

**deployment** 
![image](https://user-images.githubusercontent.com/6306308/71549650-6ed48780-2986-11ea-966a-4dc6bce4c861.png)

**virtual service**
![image](https://user-images.githubusercontent.com/6306308/71549657-84e24800-2986-11ea-963e-3968db297d59.png)

**Command to deploy to all** 
`istioctl kube-inject apply -f httpbin-all.yaml | kubectl -n itest  apply     -f -`

**Running pods**
`kubectl -n itest get pods`
`NAME                       READY   STATUS    RESTARTS   AGE`
`httpbin-7fbb6744b7-55dm9   2/2     Running   0          21m`

k8s service
![image](https://user-images.githubusercontent.com/6306308/71549670-f8845500-2986-11ea-9e74-706e379fe854.png)

istio vs
![image](https://user-images.githubusercontent.com/6306308/71549671-033eea00-2987-11ea-89c8-61fbf2ca6ab5.png)

**Expected behavior** when the service from another pod in the cluster  is called is to have a fault with 500 status code

![image](https://user-images.githubusercontent.com/6306308/71549686-4600c200-2987-11ea-81ac-9a9e8d5903f1.png)

**Observed behavior** 
If same is changed to port 80 , it bypasses virtual service altogether 
![image](https://user-images.githubusercontent.com/6306308/71549696-629cfa00-2987-11ea-9111-c1fd5fcce5e6.png)

Changing the virtual service port to 8000 makes no difference 
![image](https://user-images.githubusercontent.com/6306308/71549721-c7f0eb00-2987-11ea-8a19-472802b1164f.png)

Apparently if a k8s service has port 80 exposed , the virtual service is not getting used at all.  All other ports seems to be working fine. 

proxy-config for the routes look like this 

![image](https://user-images.githubusercontent.com/6306308/71549736-0b4b5980-2988-11ea-9387-a50021f205ea.png)

Here is the complete yaml file 
[httpbin-all.txt](https://github.com/istio/istio/files/4007491/httpbin-all.txt)

**Comment by sekhrivijay** [comment]
****

**Comment by howardjohn** [comment]
I did not see this behavior when applying your yaml. Please get a config dump from envoy (from where you are calling httpbin from): https://github.com/istio/istio/wiki/Troubleshooting-Istio

**Comment by sekhrivijay** [comment]
Ran this command 
`kubectl -n itest  exec web-v1-55f7599f94-sdfk7 -c istio-proxy -- curl 'localhost:15000/clusters' > clusters.txt
`

Attached file 
[clusters.txt](https://github.com/istio/istio/files/4007554/clusters.txt)


This command works as expected 
`kubectl -n itest exec web-v1-55f7599f94-sdfk7 -- curl http://httpbin:8000/ -v `

This command does not 
`kubectl -n itest exec web-v1-55f7599f94-sdfk7 -- curl http://httpbin/ -v`

**Comment by howardjohn** [comment]
get the full config dump not just clusters please

**Comment by sekhrivijay** [comment]
Attached. Is this what you were looking for @howardjohn  ?
[config_dump.json.txt](https://github.com/istio/istio/files/4007624/config_dump.json.txt)

**Comment by howardjohn** [comment]
Yes. I applied the same config but have different config_dump - mine has config for port 80 but yours does not. Not sure what is going on. Maybe look at pilot logs to see if there are any errors popping up?

**Comment by sekhrivijay** [comment]
I deleted the setup and reapplied it 
`istioctl kube-inject apply -f httpbin-all.yaml | kubectl -n itest delete -f -`
`istioctl kube-inject apply -f httpbin-all.yaml | kubectl -n itest apply -f -`


ran this command
`kubectl -n istio-system logs -f istio-pilot-5889bbb5c5-nbfmb discovery > /tmp/pilot.logs.txt`


Attached are the pilot logs. What am I specifically looking for? 
[pilot.logs.txt](https://github.com/istio/istio/files/4008506/pilot.logs.txt)

I saw some logs about duplicate domain 
![image](https://user-images.githubusercontent.com/6306308/71561971-62facb00-2a43-11ea-91f7-01ce879e9cc6.png)

some error messages like these 
![image](https://user-images.githubusercontent.com/6306308/71562086-2ed3da00-2a44-11ea-9282-718ffa493264.png)

Is there a particular pattern I should be looking for ?

**Comment by hzxuzhonghu** [comment]
There are port protocol conflicts
```
        "pilot_conflict_outbound_listener_tcp_over_current_http": {
            "0.0.0.0:80": {
                "proxy": "zk-search-dev1-1.dev1",
                "message": "Listener=0.0.0.0:80 AcceptedTCP=nginx.default.svc.cluster.local,speedy.default.svc.cluster.local,proxy-service.dev1.svc.cluster.local,proxy-service.idev2.svc.cluster.local,sleep.idev2.svc.cluster.local,istio-ingressgateway.istio-system.svc.cluster.local,sleep.dev1.svc.cluster.local,hpa-sim.default.svc.cluster.local,website.default.svc.cluster.local,website.dev1.svc.cluster.local,website.itest.svc.cluster.local,search-service.dev1.svc.cluster.local,search.itest.svc.cluster.local RejectedHTTP=httpbin.itest.svc.cluster.local TCPServices=13"
            }
        },
```

**Comment by hzxuzhonghu** [comment]
A port can not be set with more than one protocol

**Comment by howardjohn** [comment]
I thought you should be able to have a port with multiple protocols, just
not for the same service? Otherwise things would break pretty often since
not everyone names their ports

**Comment by sekhrivijay** [comment]
I think I ran into some limitation of istio with headless service as I have a few of them in the test cluster https://github.com/istio/istio/issues/9784

I have sts for zookeeper, solr, memcache and I have cleanup all the port name in those and reapplied the changes again . I dont see any conflicting port in pilot logs now. Furthermore, port 80 is working as expected. However , now port 443 is not working

Here is a similar service (like httpbin) with two ports 80 and 443
![image](https://user-images.githubusercontent.com/6306308/71596150-1dea9d80-2b04-11ea-89ef-27ae52b94f6e.png)

The deployment app exposes two ports also 
![image](https://user-images.githubusercontent.com/6306308/71596174-32c73100-2b04-11ea-9792-66ee8db951b9.png)


The virtual service is similar 
![image](https://user-images.githubusercontent.com/6306308/71596214-51c5c300-2b04-11ea-86d0-383498f60372.png)

Running curl from another pod with port 80 work but does not work with port 443
![image](https://user-images.githubusercontent.com/6306308/71596266-7ae65380-2b04-11ea-99d4-b67e368d719e.png)

Pilot logs are attached when applying search-all.yaml file 
[pilot.logs.txt](https://github.com/istio/istio/files/4010736/pilot.logs.txt)

[search-all.yaml.txt](https://github.com/istio/istio/files/4010725/search-all.yaml.txt)

Notice the yaml fill will not work as it has my private images.

**Comment by sekhrivijay** [comment]
I created a simple python flask hello world app that can run as http or https 
https://github.com/sekhrivijay/hello-world-flask/blob/master/server.py

I created the docker image and pushed on docker hub 
`sekhrivijay/hello-world-flask:latest `

Here is the complete yaml file that runs two containers one with http and one with https
https://github.com/sekhrivijay/hello-world-flask/blob/master/hello-two-ports.yaml

![image](https://user-images.githubusercontent.com/6306308/71599465-9f482d00-2b10-11ea-9419-41dd19402fd4.png)

Running the yaml file with istio will run 3 containers
`istioctl kube-inject apply -f hello-two-ports.yaml  | kubectl -n dev1 apply   -f -`

![image](https://user-images.githubusercontent.com/6306308/71599514-c1da4600-2b10-11ea-8a35-38a939e40798.png)
![image](https://user-images.githubusercontent.com/6306308/71599541-d9b1ca00-2b10-11ea-8227-d6950ed21c31.png)

One runs on port 8080 
![image](https://user-images.githubusercontent.com/6306308/71599556-f0f0b780-2b10-11ea-839c-e50d2d2d44a5.png)


Other runs on port 8443
![image](https://user-images.githubusercontent.com/6306308/71599581-0bc32c00-2b11-11ea-92c8-2c2066a2526b.png)


The service maps port 80 to 8080 and port 443 to 8443 respectively 
I don't see any conflicts in pilot logs . You can run this yaml file on your cluster and it will work 
Same behavior. port 80 works but port 443 does not 

![image](https://user-images.githubusercontent.com/6306308/71599639-50e75e00-2b11-11ea-81ad-34e8d5e6357d.png)
 


Mutual TLS is not enabled. Is there a specific configuration that needs to be enabled for https?

**Comment by hzxuzhonghu** [comment]
I donot think http fault injection can work on https protocol, can you show your route config dump? There should be no route named 443

**Comment by sekhrivijay** [comment]
`kubectl -n dev1 exec sleep-75454ccb48-wpqm4 -c istio-proxy -- curl http://localhost:15000/config_dump > /tmp/config.dump.json.txt`

[config.dump.json.txt](https://github.com/istio/istio/files/4011806/config.dump.json.txt)

> vsekhri@cloudshell:~$ istioctl proxy-config route sleep-75454ccb48-wpqm4.dev1
NOTE: This output only contains routes loaded via RDS.
NAME                                             VIRTUAL HOSTS
8983                                             2
inbound|80|http|sleep.dev1.svc.cluster.local     1
8060                                             2
9091                                             3
inbound|80|http|sleep.dev1.svc.cluster.local     1
80                                               7
8080                                             2
8200                                             2
9090                                             3
9150                                             2
9200                                             3
9901                                             2
15004                                            3
15010                                            2
15014                                            6
                                                 1


`istioctl proxy-config cluster   sleep-75454ccb48-wpqm4.dev1`

[cluster.txt](https://github.com/istio/istio/files/4011815/cluster.txt)



Attached. How about the regular traffic routing with https ? Will that work ? I will give it a shot and confirm  but I have doubts

**Comment by hzxuzhonghu** [comment]
That verified the above comment, `https` protocol is not treated as `http`, so http fault injection can not apply to it

**Comment by sekhrivijay** [comment]
@hzxuzhonghu @howardjohn 
As I expected normal traffic routing also does not work with https .

Here is same example without httpFault but with traffic split of 99% and 1% going to version1 and version2 of the deployment 
[hello-both-https-port.yaml.txt](https://github.com/istio/istio/files/4013596/hello-both-https-port.yaml.txt)

It has no impact . I see 50% traffic split 
You can simply apply this yaml file and see for yourself. 
`istioctl kube-inject apply -f  hello-both-https-port.yaml  | kubectl -n dev1 apply   -f -  `

Here is what  am observing . Both version are getting 50% traffic split 
![image](https://user-images.githubusercontent.com/6306308/71635677-20c0bd80-2bec-11ea-9283-db342eead3d8.png)


The VS describes it to be 99% and 1%
![image](https://user-images.githubusercontent.com/6306308/71635694-4948b780-2bec-11ea-8392-ba9e7b9da048.png)


The destination rule is a standard one 
![image](https://user-images.githubusercontent.com/6306308/71635702-5a91c400-2bec-11ea-8c88-b9ae1ac940c8.png)

I will  try the same http port and report back .

**Comment by sekhrivijay** [comment]
Okay, so here is what I have observed and it is reproducible very easily .
Both port 80 and 443 does not work for service to service communication . There is no gateway involved here. It is all within the cluster 
Changing the service port to anything other than 80 or 443 works as expected.
[hello-both-http-port.yaml.txt](https://github.com/istio/istio/files/4014575/hello-both-http-port.yaml.txt)
`istioctl kube-inject apply -f  hello-both-http-port.yaml | kubectl -n dev1 apply   -f -  `


The following does not work
![image](https://user-images.githubusercontent.com/6306308/71646528-a2c5ea80-2caf-11ea-8f09-a6867f431b08.png)

If I call the service endpoint I get 50% traffic split 
![image](https://user-images.githubusercontent.com/6306308/71646536-c5f09a00-2caf-11ea-83e5-f8f6a2fbb03c.png)


If I just change the port to 443 and enable https in the flask app, same issue there as well.

If I change the port to say 8181 and call the service endpoint, then I get 99% and 1% split as expected 
![image](https://user-images.githubusercontent.com/6306308/71646549-f7696580-2caf-11ea-8d53-b4f09f4e7613.png)

![image](https://user-images.githubusercontent.com/6306308/71646557-1bc54200-2cb0-11ea-9f91-ffd2bde5ee61.png)

**Comment by sekhrivijay** [comment]
Confirmed with https , the traffic split is not working for me . It is working fine with http though  (Initially it was not working even with http . I bounced pilot and http at least started working )

Here is the yaml for https with port 443 for k8s service
https://github.com/sekhrivijay/hello-world-flask/blob/master/hello-both-https-port.yaml
[hello-both-https-port.yaml.txt](https://github.com/istio/istio/files/4014664/hello-both-https-port.yaml.txt)

Running this command from sleep pod 
`curl https://hello -k` results in 50-50 traffic split. Not expected 
Changing service port to any other (say 9443) keeping https does not work either . 

Here is the yaml for http with port 80 for k8s service
https://github.com/sekhrivijay/hello-world-flask/blob/master/hello-both-http-port.yaml
[hello-both-http-port.yaml.txt](https://github.com/istio/istio/files/4014665/hello-both-http-port.yaml.txt)

Running this command from sleep pod 
`curl http://hello -k` results in 99-1 traffic split. Expected 

Am I doing something wrong here ?

**Comment by hzxuzhonghu** [comment]
I think you are not understanding HTTP route correctly, it only works on http like protocols, like. HTTP gRPC, etc. But not HTTPS.
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hello
spec:
  hosts:
  - "hello"
    
  http:
  - route:
    - destination:
        host: hello
        subset: v1
      weight: 99
    - destination:
        host: hello
        subset: v2
      weight: 1
```

**Comment by aroundthecode** [comment]
Guys this is still true today after 3 years (I'm using 1.14.1) and it's not written anywhere in documentation, nor tools like kiali or even isitiod log report it as a problem.

I lost 3 days in troubleshooting then hit this issue by googling and changed my port to 8080 and got everything fixed.

Please add this to docs in capital case!!!!

**Comment by hzxuzhonghu** [comment]
Good suggestion, not sure if there is already doc s in FAQ

**Comment by Hronom** [comment]
In my case issue was that my service can be called from outside(by public url) as same as internally.

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata: 
  labels:
    argocd.argoproj.io/instance: example-java-one
  name: example-java-one
  namespace: example
spec:
  gateways:
    - istio-ingress/istio-gateway
    - mesh
  hosts:
    - example-java-one.test.com
    - example-java-one.example.svc.cluster.local
  http:
    - match:
        - uri:
            prefix: /
      name: primary
      route:
        - destination:
            host: example-java-one.example.svc.cluster.local
            port:
              number: 80
            subset: stable
          weight: 100
        - destination:
            host: example-java-one.example.svc.cluster.local
            port:
              number: 80
            subset: canary
          weight: 0
```

Important part here to have `mesh` in gateway to apply VirtualService and gateways not only to gateway but to internal communications e.g. `mesh`.

The other aspect is to add internal host `example-java-one.example.svc.cluster.local` to `hosts`.

Here short version of important parts:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
...
  gateways:
...
    - mesh
  hosts:
...
    - example-java-one.example.svc.cluster.local
...
```

All works good then with port `80` which is http default
