### ISSUE TITLE
Switch to using pkg/cache instead of the hashicorp cache

### ISSUE THREAD

**Issue by geeknoid** [istio/istio#1983]
We want to converge our cache uses on the pkg/cache package as opposed to external cache packages (our is faster and exposes some stats)

This is in reference to the code in evaluator.go which calls lru.New

**Comment by ozevren** [comment]
This is slated to go away as part of switch to the runtime2.

**Comment by ozevren** [comment]
That code is gone now. We do not do caching at the expression level.
