### ISSUE TITLE
TestController_GetPodLocality flake

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#19830]
This case is flake, i have seen many times, the latest one is

https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/19812/unit-tests_istio/5688

**Comment by hzxuzhonghu** [comment]
By running `go test -v -race -run TestController_GetPodLocality -count=100`
 It will definitely reproduce, my finding is that the fake controller does not stop actually. That is to say there is resource leakm including go routine, memory. 
In the end, it timesout with 3k+ go routines in total

**Comment by howardjohn** [comment]
fix merged
