### ISSUE TITLE
make docker.push fails with: No rule to make target `push.docker.app'

### ISSUE THREAD

**Issue by ericvn** [istio/istio#19846]
Running `make docker.push` fails with:

```
make: *** No rule to make target `push.docker.app', needed by `docker.push'.  Stop.
```

**Comment by ericvn** [comment]
I'm not sure if we need to simply add the `filter-out docker.app` to the push?

**Comment by howardjohn** [comment]
I am pretty sure we do not need the filter. Before, the app had all its own targets for (as far as I could tell) no good reason. I removed those in favor of the generic ones but missed the filter stuff.

**Comment by ericvn** [comment]
@howardjohn OK. I pushed the opposite in #19849. I can close that one and continue with yours.
