### ISSUE TITLE
Istio agent needs operator installation support for SDS for 1.5

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#19848]
In 1.4, SDS works with the operator using nodeagent. In master, there is NO working support for SDS, as we delayed it in hopes of going directly to istio-agent based SDS.

This needs to be done by 1.5 or we will need to fallback to nodeagent approach, otherwise there will be a regression.

**Comment by myidpt** [comment]
By operator, you mean istioctl or the "real" operator?

**Comment by howardjohn** [comment]
Its the same code. When someone follows istio.io docs SDS should work, and istio.io documents istioctl install

**Comment by myidpt** [comment]
In order to do this, we need to understand how to install istiod + istio agent using kubectl. Do we have basic instructions to describe how to do this?

**Comment by howardjohn** [comment]
I do not know how to do it. Once we do though it shouldn't be too much
effort, just need to make it enabled when global.sds.enabled=true
