### ISSUE TITLE
Postgres Kubernetes Helm chart fails with Envoy...

### ISSUE THREAD

**Issue by derailed** [istio/istio#1985]
Running a Postgres Helm chart on an Istio enabled cluster is failing, due to failing health probes.

Istio version info:
Version: 0.2.12
GitRevision: 998e0e00d375688bcb2af042fc81a60ce5264009
GitBranch: release-0.2

Operating System: OSX 10.13.1 (high sierra)
Minikube Version: 0.24.1
Helm Version: 2.7.2

Repro Steps:
o Using minikube on OSX
o Enable istio on minikube per installation steps 
   > kubectl create -f istio.yaml -f istio-initializer.yaml
o Init Helm
   > helm init
o Install the Postgresql chart
   > helm install --name pg stable/postgresql --version 0.8.4

Actual
  The postgresql pod is getting decorated correctly with an envoy but remains in 1/2 ready state. 
  Looking at the events on the postgresql pod, health probs are failing.
  Both readiness/liveliness default probes on the Postgres chart issue the shell command pg_isready
  > sh -c - exec pg_isready --host $POD_IP
     a.b.c.d:5432 - no response
  which fails with istio installed. Guessing http 1.0 issue??
  
Expected
  The postgres Helm chart runs correctly in an Istio enabled cluster

Not sure if there is a way to tell Istio NOT to decorate a given service? 

Outcome
  My Istio enabled cluster fails since the db pod is not considered healthy hence dependent services fail as well.

**Comment by sylus** [comment]
Getting the same type of issue, consulted https://istio.io/docs/setup/kubernetes/sidecar-injection.html and still not sure what is going on.

**Comment by ayj** [comment]
> Not sure if there is a way to tell Istio NOT to decorate a given service?

You can opt-out of having the proxy automatically injected by adding the following annotation to the _pod template spec_ in your deployment.

```yaml
annotations:
    sidecar.istio.io/inject: "false"
```

**Comment by costinm** [comment]
Can we add a blacklist (if auto-inject is enabled by default) and whitelist (if auto-inject is off by default) ? In some cases users can't edit the template - for example if they install with helm, or 
from a repository (kubectl apply http:...).

**Comment by ayj** [comment]
{black,white}listing is already supported. First, you can scope when the webhook is invoked using the `NamespaceSelector` in the webhook registration. Second, you can further refine opt-in / opt-out behavior within those namespaces using the `policy` field in the injection ConfigMap. See https://istio.io/docs/setup/kubernetes/sidecar-injection.html#understanding-what-happened for details.

**Comment by Data-drone** [comment]
I added the annotation like:

```
template:
   metadata:
       annotations: 
           sidecar.istio.io/inject: "false"
```

but it seems to still be injecting?
In my deployment yaml I see:

```
   "template": {
      "metadata": {
        "creationTimestamp": null,
        "labels": {
          "app": "dev-db-postgresql"
        },
        "annotations": {
          "sidecar.istio.io/inject": "false",
          "sidecar.istio.io/status": "injected-version-0.2.6"
        }
```

and the probes are still failing?

**Comment by ilyasotkov** [comment]
Just tested it using Istio 0.7.1 (with auto-injection webhook), the postgresql chart (0.8.4) does indeed fail with `Failed create pod sandbox.` error. 

Adding `sidecar.istio.io/inject: "false"` to template.metadata.annotations in the postgres deployment chart fixed the problem for me.

**Comment by sgandon** [comment]
I have the same issue on docker for mac, any idea why it fails ?

**Comment by emedina** [comment]
Facing also this issue with 0.7.1
