### ISSUE TITLE
Kiali painting

### ISSUE THREAD

**Issue by tianxf305** [istio/istio#19855]
Please ask a question. My business model is that the user goes to king-front, and then king-front goes to king-kf (king-front is the reverse agent of nginx).
1. After boarding istio, I used kiali to draw, and found that the service from king-front to king-kf was not the pod from king-front to king-kf, and then to the pod of king-kf
2. However, using curl to access the back-end king-kf on the pod of king-front is the normal display graph. The user goes to the service of king-front and then to the pod of king-front, and then to the service from king-front to king-kf, and then to the pod of king-kf.
3. The following data are obtained from Prometheus
3.1 data obtained by nginx agent
---"istio_request_duration_seconds_bucket{connection_security_policy="unknown",destination_app="king-kf",destination_principal="unknown",destination_service="king-frontend.kingfisher.svc.cluster.local",destination_service_name="king-frontend",destination_service_namespace="kingfisher",destination_version="v2",destination_workload="king-kf-v2",destination_workload_namespace="kingfisher",instance="10.58.27.49:42422",job="istio-mesh",le="+Inf",permissive_response_code="none",permissive_response_policyid="none",reporter="source",request_protocol="http",response_code="200",response_flags="-",source_app="istio-ingressgateway",source_principal="unknown",source_version="unknown",source_workload="istio-ingressgateway",source_workload_namespace="istio-system"}"---
3.2. Data obtained by using curl
---"istio_request_duration_seconds_bucket{connection_security_policy="unknown",destination_app="king-kf",destination_principal="unknown",destination_service="king-kf.kingfisher.svc.cluster.local",destination_service_name="king-kf",destination_service_namespace="kingfisher",destination_version="v2",destination_workload="king-kf-v2",destination_workload_namespace="kingfisher",instance="10.58.34.96:42422",job="istio-mesh",le="5",permissive_response_code="none",permissive_response_policyid="none",reporter="source",request_protocol="http",response_code="404",response_flags="-",source_app="king-frontend",source_principal="unknown",source_version="v4",source_workload="king-frontend-v4",source_workload_namespace="kingfisher"}"---

**Comment by esnible** [comment]
Please open Kiali issues at https://github.com/kiali/kiali/issues
