### ISSUE TITLE
Istiod enables SDS by default, breaking clusters without support

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#19851]
Currently on master the default install will not work on many clusters. This issue just tracks making sure we do not ship 1.5 without reconciling this. There are a variety of options to solve this which I think have issues created - disable by default, allow untrustworthy, etc

**Comment by lei-tang** [comment]
https://github.com/istio/istio/issues/19950

**Comment by howardjohn** [comment]
that only solved half, there is still the jwt issue

**Comment by lei-tang** [comment]
for JWT issue: https://github.com/istio/istio/issues/20178

**Comment by howardjohn** [comment]
update: we have support for it but need automation. Which is in PR: https://github.com/istio/istio/pull/20393

**Comment by howardjohn** [comment]
Done
