### ISSUE TITLE
Support multi-istiocontrolplane testing

### ISSUE THREAD

**Issue by clyang82** [istio/istio#19860]
the new installer is designed for modularity and isolation. it allows installing multiple istiocontrolplane in the same cluster in different namespaces.
the tasks includes:
1. allow customized labels for istio-ingress.
2. test multi-istiocontrolplane in different namespaces. the released version is installed `istio-control/istio-ingress/istio-policy/istio-telemetry` in while the master version is installed in `istio-control-master/istio-ingress-master/istio-policy-master/istio-telemetry-master`. share one citadel installed in `istio-system`
3. allow customized namespace and labels for bookinfo application to test

**Comment by howardjohn** [comment]
Given our plans to consolidate everything to one deployment, investing effort into this for the microservices model may be wasted effort

**Comment by clyang82** [comment]
@howardjohn Could you point me the design doc or discussion threads? Thanks.

**Comment by howardjohn** [comment]
https://www.google.com/url?sa=t&rct=j&esrc=s&source=appssearch&uact=8&cd=1&cad=rja&q&sig2=ptxv889PludfKCnEmvrKzg&ved=0ahUKEwjs_Kr48uPmAhXPsWQKHQ0_BeQ4ABABKAEwAQ&url=https://drive.google.com/a/google.com/open?id%3D1v8BxI07u-mby5f5rCruwF7odSXgb9G8-C9W5hQtSIAg%26usp%3Dchrome_omnibox&usg=AOvVaw0wurP8j3z2PFvtjIJeKFBB

**Comment by clyang82** [comment]
Thanks @howardjohn Do you know why it always throws 404 error?

**Comment by howardjohn** [comment]
I think the link was wrong, i editted my comments. if that doesn't work search istiod in the drive

**Comment by clyang82** [comment]
It works. Thanks
