### ISSUE TITLE
Proxy startup takes 20s due to AWS metadata lookup

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#19868]
Steps to reproduce:

```
kind create cluster
istioctl manifest apply
```

Then run any pod. Look at proxy logs, there is 20s between "Epoch 0 starting" and it actually starting. Additional logging will show this is from the AWS metadata

This does NOT effect GCP (because it will match the gcp one first), and I assume doesn't impact AWS since the check will be fast. However, any other provider is likely to run into this 20s delay.

This is very similar to https://github.com/istio/istio/issues/17357

I marked this as a release blocker since this is a pretty large regression for non GCP/AWS platforms

**Comment by howardjohn** [comment]
https://github.com/aws/aws-sdk-go/issues/582

**Comment by douglas-reid** [comment]
`20s` is fairly bad. we could use a custom http client with a much shorter timeout I suppose (though I'm not clear on the implications there).

**Comment by howardjohn** [comment]
I am not sure the best way to get there, but I would expect an upper bound of 250ms or so in the worst case. A lot of use cases like knative are strongly optimizing for startup time, so anything more would be pretty harmful

**Comment by douglas-reid** [comment]
I guess we *could* also make the platform be explicit, rather than discoverable. That would remove the need for fallbacks and timeouts for irrelevant platforms.

**Comment by howardjohn** [comment]
its a bit hard if you have mixed deployments I would imagine though. It seems reasonable that we could just have some code that fires off a bunch of async calls for all the platforms (say in the future we have 10 we support, we don't want to wait 250ms for each), set a timeout on their response, and use whatever platform we get a positive response from? We could then additionally add an explicit override for users who want to avoid that?
