### ISSUE TITLE
Operator values use inconsistent hyphen vs underscore

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#19872]
If I want to turn off Galley, I use `--set config_management.enabled=false`. If I want to turn off ingress, I use `--set values.gateways.istio-ingressgateway=false`. Note the mismatch `_` and `-`

None of our APIs use `_` as far as I know, so for consistency we should probably use hyphen or camelcase.

**Comment by howardjohn** [comment]
Actually this is a different issue:

```
--set config-management.enabled=false
Error: failed to generate and apply manifests, error: failed to generate tree from the set overlay, error: bad path=value: config-management.enabled=false
```

hyphen is correctly invalidated

```
--set config_management.enabled=false
- Applying manifest for component Base...
✔ Finished applying manifest for component Base.
- Applying manifest for component Prometheus...
- Applying manifest for component IngressGateway...
- Applying manifest for component Galley...
- Applying manifest for component Citadel...
- Applying manifest for component Injector...
- Applying manifest for component Pilot...
✔ Finished applying manifest for component Prometheus.
✔ Finished applying manifest for component Citadel.
✔ Finished applying manifest for component Injector.
✔ Finished applying manifest for component IngressGateway.
✔ Finished applying manifest for component Galley.
✔ Finished applying manifest for component Pilot.


✔ Installation complete
```

underscore is not invalidated, but does nothing

```
--set configManagement.enabled=false
- Applying manifest for component Base...
✔ Finished applying manifest for component Base.
- Applying manifest for component Citadel...
- Applying manifest for component IngressGateway...
- Applying manifest for component Prometheus...
- Applying manifest for component Injector...
- Applying manifest for component Pilot...
- Pruning objects for disabled component Galley...
✔ Finished pruning objects for disabled component Galley.
✔ Finished applying manifest for component IngressGateway.
✔ Finished applying manifest for component Citadel.
✔ Finished applying manifest for component Prometheus.
✔ Finished applying manifest for component Injector.
✔ Finished applying manifest for component Pilot.


✔ Installation complet
```

camelcase works

**Comment by howardjohn** [comment]
is this the same issue or fixed by https://github.com/istio/api/pull/1263 @jackkleeman ?

**Comment by jackkleeman** [comment]
Same issue I think. I don't think we are supposed to use underscores anywhere, but we must use them currently in operator spec. But for example for input to istioctl manifest generate you have to not use them.

**Comment by ostromart** [comment]
I verified that this is now fixed. We still support using both path types foo_bar and fooBar for the same path due to protoc behavior but we'd have to hack the output structs to disallow foo_bar and I think as long as it works the same as fooBar it's not a serious problem. Downgrading to P2.

**Comment by esnible** [comment]
@ostromart I am seeing strange behavior using Master

`istioctl manifest generate --set addonComponents.istioTracing.enabled=true` fails with
```
Error: Asset charts/addons/istioTracing not found
```

`istioctl manifest generate --set addon-components.istio-tracing.enabled=true` fails with
```
Error: failed to generate tree from the set overlay, error: bad path=value: addon-components.istio-tracing.enabled=true
```

`istioctl manifest generate --set addon_components.istio_tracing.enabled=true` outputs a manifest, but so does `istioctl manifest generate --set addon_components.bogus.enabled=true` and we have no **bogus** component.
