### ISSUE TITLE
Prometheus mTLS scraping seems broken, fails to startup in Istiod model

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#19874]
Using istiod we can remove citadel and instead use direct SDS from istio-agent. However, this won't work for prometheus which has no sidecar but mounts the certs.

I believe the intent here is to allow scraping pods with mTLS. As far as I can tell this does NOT actually work. We are looking for this mtls label that never exists: https://github.com/istio/istio/blob/80bee4e1e8c9da71a27dccaf62ccf655d132c0d6/install/kubernetes/helm/istio/charts/prometheus/templates/configmap.yaml#L269. On my cluster, I see that there are 0 targets for kubernetes-pods-secure, and all of the kubernetes-pods fail (presumably due to mTLS).

I think there are a few action items here. If it is broken, and we don't care, we could just remove the kubernetes pod scraping (note - this is scraping user pods, envoy stats are different). However, presumably users need a way to scrape their mTLS pods, so we still need some solution for the certs.

If we do want to keep this, we need to find a more reliable way to identify if a pod is mTLS ready. This could be done easily with auto-mtls, but I am not sure how it would work with just standard strict mTLS.

We also need a way to get the certs to prometheus. This problem may extend beyond prometheus as well for user applications that need access to the certs outside of Envoy. One possibility here is to have an SDS-only mode for istio-agent, that just fetches the certs and writes them to disk as an init container.

cc @myidpt @costinm @douglas-reid

**Comment by douglas-reid** [comment]
Prom with mTLS was working and tested. Was your test cluster using Permissive mode? I believe there was an issue identified earlier with requiring the "istio" ALPN for Permissive that obviously isn't being sent by Prom.

**Comment by howardjohn** [comment]
Its using strict mode. My understand is it will only scrape pods with this `istio-mtls` label which does not exist as far as I know. I'll send you my prom instance

**Comment by mandarjog** [comment]
@howardjohn The pods are scraped even when the `value=istio-mtls` is not present, since it was *never* present. There is something else wrong in your setup. 
I run my tests with prom app scraping enabled from time to time. Like @douglas-reid mentions, permissive mode does not work anymore. 

Have you added scrape annotation to your deployment? 
You need to change `prometheus_scrape: true` in value.yaml.

**Comment by howardjohn** [comment]
I misunderstood what was going on. On my cluster i have 60 pods in the k8s-service-monitor (plain text) that all fail. I thought this was from tls, but its the `client` which has no sidecar. There are 0 in secure.

Adding the scrape label to a pod with sidecar now shows up in the secure monitor, but it fails with "received HTTP response to HTTPS request".

How does it know to scrape it with plaintext or tls? It seems the select is the same for both? https://github.com/istio/installer/blob/72b94963d4fe3e37ef713c3d856745835ce46547/istio-telemetry/prometheus-operator/templates/servicemonitors.yaml#L129-L130

**Comment by mandarjog** [comment]
Received http response for https means
1. Permissive mode 
2. Endpoint with some ports work and some do not

**Comment by myidpt** [comment]
I think this is fixed. @lei-tang
