### ISSUE TITLE
multi-cluster prometheus setup

### ISSUE THREAD

**Issue by carolynhu** [istio/istio#19908]
Add install options and docs for prometheus multi cluster setup

/cc @mandarjog

**Comment by mandarjog** [comment]
Carolyn please point to the experiment and the doc and close this issue if everything is done.

**Comment by carolynhu** [comment]
@mandarjog we are discussing with the doc team about adding a related section to istio.io

/cc @douglas-reid

**Comment by carolynhu** [comment]
published.
