### ISSUE TITLE
Max Throughput limit

### ISSUE THREAD

**Issue by gokhandincer** [istio/istio#19903]
Hello,
Has istio throughtput limit? I did a benchmark and istio throughput is max 20k.while baseline (no proxy) throughput is about 24k Why does the difference occur?

I did set proxy concurrency to 50 and increase limit cpu&memory
Is there way to increase throughput ?
Thanks

**Comment by howardjohn** [comment]
> Has istio throughtput limit? I did a benchmark and istio throughput is max 20k.while baseline (no proxy) throughput is about 24k Why does the difference occur?

Adding an extra network hop will of course impact latency/throughput to some extent. Envoy is adding telemetry, traffic policies, etc, which are not free. I think the decreased thoroughput you see is pretty in line with expectations.

**Comment by gokhandincer** [comment]
@howardjohn Well, if i disabled to mixer. Will it be improve throughput?

**Comment by howardjohn** [comment]
Yes, that generally helps. See https://istio.io/docs/ops/deployment/performance-and-scalability/

**Comment by gokhandincer** [comment]
oke i will try this thank you @howardjohn

**Comment by douglas-reid** [comment]
I'm not sure what is left to be done here. Closing.
