### ISSUE TITLE
TestStsFlow test flake

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#19918]
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/19917/unit-tests_istio/5866

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gcs/istio-prow/logs/unit-tests_istio_postsubmit/1031

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/20696/unit-tests_istio/7710

@JimmyCYJ I will send a PR to skip this test if you are not planning to work on this

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/21330/unit-tests_istio/8945

**Comment by JimmyCYJ** [comment]
I will send a PR to skip this test and then fix it. Thanks.

**Comment by JimmyCYJ** [comment]
I need to add a logic in the test to choose a unused port to bind. The test fails because STS server fail to listen on a port in use.
