### ISSUE TITLE
istioctl install can't set sidecarInjectorWebhook.enable

### ISSUE THREAD

**Issue by christianAckman** [istio/istio#19910]
**Bug description**

istioctl can't set **sidecarInjectorWebhook.enable**

Similar to https://github.com/istio/istio/issues/19642

**Steps to reproduce the bug**

`istioctl manifest generate --set values.sidecarInjectorWebhook.enable=false`

-- 

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

1.4.2

**How was Istio installed?**

istioctl

**Comment by nak3** [comment]
@christianAckman It looks like you typed the option as `enable` instead of `enabled`. Is it a typo maybe?  `values.sidecarInjectorWebhook.enabled` is the correct path.

In my local env, it looks working fine.

```
$ istioctl version --remote=false
1.4.2

$ istioctl manifest generate --set values.sidecarInjectorWebhook.enabled=false > false.yaml
$ istioctl manifest generate --set values.sidecarInjectorWebhook.enabled=true  > true.yaml
```

Then, here is the diff.

```
$ istioctl manifest diff false.yaml true.yaml 
Differences of manifests are:


Object ConfigMap:istio-system:istio-sidecar-injector has diffs:

data:
  values:
    sidecarInjectorWebhook:
      enabled: false -> true
```

**Comment by richardwxn** [comment]
what was the output you observed if it was not caused by the possible typo @nak3 mentioned?

**Comment by christianAckman** [comment]
this was the case. thanks for quick response.
