### ISSUE TITLE
Consider using genericclioptions more heavily

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#19927]
This package provides a lot of features to mimic kubectl that could be useful for istioctl. For example, we have a bunch of stuff we use that is the same as what they do: table printing, `-o json` (except we are missing jsonpath and yaml and other outputs), `--kubeconfig` (except we aren't as flexible), etc. This library can handle all of this for us potentionally

**Comment by incfly** [comment]
https://github.com/kubernetes/cli-runtime/tree/master/pkg/genericclioptions? this one?

**Comment by howardjohn** [comment]
Yes, the docs aren't great but pretty much allows you to easily get all the flags the kubectl has
