### ISSUE TITLE
Provide probe cobra command via istio/pkg

### ISSUE THREAD

**Issue by nak3** [istio/istio#19922]
**Describe the feature request**

mixer, galley and security(istio_ca) have `probe` sub-command and their codes are duplicaed. These should be combined and provided from istio/pkg 

https://github.com/istio/istio/blob/c8966a10a487e7c2b0ab020d9be4c5e24110f2f2/galley/cmd/galley/cmd/probe.go
https://github.com/istio/istio/blob/c8966a10a487e7c2b0ab020d9be4c5e24110f2f2/mixer/cmd/mixs/cmd/probe.go
https://github.com/istio/istio/blob/c8966a10a487e7c2b0ab020d9be4c5e24110f2f2/security/pkg/cmd/probe.go

**Additional context**

* `version` sub-command already does so https://github.com/istio/pkg/blob/1474f181aa7635a8b465edbfdf44df708ee04d6c/version/cobra.go#L49
* Shared code is useful forunique error struct https://github.com/istio/istio/pull/19174/files#r350314865

**TODO**

- [x] Implement probe command in `istio/pkg` - https://github.com/istio/pkg/pull/97
- [ ] Remove probe code from each mixer, galley and security.

**Comment by brian-avery** [comment]
Hey @nak3 can this be closed?

**Comment by howardjohn** [comment]
These components are removed
