### ISSUE TITLE
Can't access gateway host from inside of pod

### ISSUE THREAD

**Issue by tony-Ma-yami** [istio/istio#19931]
fisrt , my ingressgateway name  is "istio.gateway.abd.com"
now i successed deploy the sample of bookinfo and I can visit the "istio.gateway.abd.com/productpage".

But, when i visit the again inside of the "pod/productpage-v1-c7765c886-v8t57", it will be 404.

why ?  can someone help me ?

**Comment by howardjohn** [comment]
Please provide more details of what you did or we will not be able to help. Thanks

**Comment by tony-Ma-yami** [comment]
configuration like this : 
`apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: myapp
spec:
  hosts:
  - myapp.com # cannot use "*" here since this is being combined with the mesh services
  - helloworld.default.svc.cluster.local
  gateways:
  - mesh # applies internally as well as externally
  - myapp-gateway
  http:
  - match:
    - uri:
        prefix: /hello
      gateways:
      - myapp-gateway #restricts this rule to apply only to ingress gateway
    route:
    - destination:
        host: helloworld.default.svc.cluster.local
        subset: v1
  - match:
    - gateways:
      - mesh # applies to all services inside the mesh
    route:
    - destination:
        host: helloworld.default.svc.cluster.local
        subset: v1`

**Comment by howardjohn** [comment]
Can you get a config dump from the client and the access logs: https://github.com/istio/istio/wiki/Troubleshooting-Istio#collecting-information-2

**Comment by howardjohn** [comment]
Closing as required info was not provided

**Comment by howardjohn** [comment]
But you probably need a ServiceEntry for myapp.com if you want to access it internally
