### ISSUE TITLE
istioctl manifest apply command unable to set JSON values

### ISSUE THREAD

**Issue by ragoragino** [istio/istio#19934]
**Bug description**
isitoctl manifest apply uses StringSliceVarP to parse --set command-line arguments. However, according to the Go doc string slice family of functions: "take[s] comma-separated value as arguments and split them accordingly". Therefore, for example, setting argument values.global.proxy.accessLogFormat to any longer JSON (e.g. even the one in the Istio Helm confimap '{"start_time": "%START_TIME%", "req_method": "%REQ(:METHOD)%"}') will not work as the parser will interpret values.global.proxy.accessLogFormat={"start_time": "%START_TIME%" as one argument and then  "req_method": "%REQ(:METHOD)%"}' as another (which will fail on  https://github.com/istio/operator/blob/a2929d01a4d892c869cd9cd03eb37b01d074347a/cmd/mesh/manifest-common.go#L192). Wouldn't using the string array family of functions resolve the problem?

**Expected behavior**
isitoctl manifest apply should be able to set JSON values.

**Steps to reproduce the bug**
isitoctl manifest apply --set values.global.proxy.accessLogFormat='{"start_time": "%START_TIME%", "req_method": "%REQ(:METHOD)%"}'

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
client version: 1.4.2
control plane version: 1.4.2
data plane version: 1.4.2 (3 proxies)

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:11:03Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"1da9875156ba0ad48e7d09a5d00e41489507f592", GitTreeState:"clean", BuildDate:"2019-11-14T05:19:20Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
istioctl manifest apply --set values.global.mtls.enabled=true --set values.global.controlPlaneSecurityEnabled=true --set values.tracing.enabled=true --set values.kiali.enabled=true --set values.prometheus.enabled=false

**Environment where bug was observed (cloud vendor, OS, etc)**
Azure, AKS

**Comment by howardjohn** [comment]
I think we support `--set a=b,x=z` syntax.
If you are going to by passing json I highly recommend you just use a file instead of dealing with the mess of trying to escape json

**Comment by maks-mikhalov** [comment]
Have the same issue. I tried with istioctl --set, IstioControlPlane yaml and istio operator. Getting the same result everywhere - predefined accessLogFormat is not propagating to the configmap. 
The temporary fix is patching istio configmap after istio has been deployed.

**Comment by ragoragino** [comment]
Although what @maks-mikhalov mentions is another issue, it seems to occur also in our cluster. When deploying an adapted TEXT version of our log format, there is no change in the istio configmap (Istio version 1.4.2). However, I believe this would need to be addressed in another bug report.

@howardjohn we need to automate our cluster creation and therefore we need to install Istio without manually changing any config files. Do you have any idea how one could set Envoy accessLogFormat to some JSON programatically? What do you mean by using a file for setting a value?

**Comment by howardjohn** [comment]
You can pass istioctl a file like `-f`. See https://istio.io/docs/setup/install/istioctl/#configure-the-feature-or-component-settings
