### ISSUE TITLE
Ability to set traffic.sidecar.istio.io/includeOutboundIPRanges etc. globally

### ISSUE THREAD

**Issue by cagataygurturk** [istio/istio#19939]
**Describe the feature request**

Currently it is possible to set up the sidecar proxy's some properties such as excludeIPRanges globally, so some CIDR's can be excluded in all the mesh. However, after switching to CNI this settings loses its effectiveness and the only way to exclude those CIDR's from proxies is to set [Traffic redirection parameters](https://istio.io/docs/setup/additional-setup/cni/#traffic-redirection-parameters) on pod level.

It would be nice to have the ability to set those at global level.

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by camattin** [comment]
We have not been able to test this without istio-cni, but we can confirm this bug exists as the OP state. We must do the annotation for this to be functional.

**Comment by cagataygurturk** [comment]
I am working on a PR to fix this.

**Comment by cagataygurturk** [comment]
The issue is adressed but there is still a bug impacting it: #22902
