### ISSUE TITLE
Requested quota 'requestcountquota' is not configured

### ISSUE THREAD

**Issue by rnkhouse** [istio/istio#19946]
**Bug description**
I installed istio version `1.4.2` with disablepolicycheck to false. Following this guide for rate limitting. I am getting `Requested quota 'requestcountquota' is not configured` error.

**kubectl describe instance requestcountquota -n istio-system**

    Name:         requestcountquota
    Namespace:    istio-system
    Labels:       <none>
    Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                    {"apiVersion":"config.istio.io/v1alpha2","kind":"instance","metadata":{"annotations":{},"name":"requestcountquota","namespace":"istio-syst...
    API Version:  config.istio.io/v1alpha2
    Kind:         instance
    Metadata:
      Creation Timestamp:  2020-01-06T16:50:20Z
      Generation:          1
      Resource Version:    2602
      Self Link:           /apis/config.istio.io/v1alpha2/namespaces/istio-system/instances/requestcountquota
      UID:                 52d9cb07-5c89-454c-b806-4b5a9004e155
    Spec:
      Compiled Template:  quota
      Params:
        Dimensions:
          Destination:          destination.labels["app"] | destination.service.name | "unknown"
          Destination Version:  destination.labels["version"] | "unknown"
          Source:               request.headers["x-forwarded-for"] | "unknown"
    Events:                     <none>

I also see below errors in mixer:

    2020-01-06T17:54:14.614728Z	error	46 errors occurred:
	* instance='requestduration.instance.istio-system': failed to evaluate expression for field 'Value'; unknown attribute response.duration
	* instance='tcpconnectionsopened.instance.istio-system': failed to evaluate expression for field 'Dimensions[source_workload_namespace]'; unknown attribute source.workload.namespace
	* instance='tcpbytereceived.instance.istio-system': failed to evaluate expression for field 'Value'; unknown attribute connection.received.bytes
	* instance='requestsize.instance.istio-system': failed to evaluate expression for field 'Value'; unknown attribute request.size
	* instance='tcpconnectionsclosed.instance.istio-system': failed to evaluate expression for field 'Dimensions[source_workload_namespace]'; unknown attribute source.workload.namespace
	* instance='tcpbytesent.instance.istio-system': failed to evaluate expression for field 'Value'; unknown attribute connection.sent.bytes
	* instance='sourceip.instance.default': failed to evaluate expression for field 'Value'; unknown attribute source.ip
	* instance='requestcount.instance.istio-system': failed to evaluate expression for field 'Dimensions[destination_workload]'; unknown attribute destination.workload.name
	* instance='attributes.instance.istio-system': error evaluating AttributeBinding expression for attribute key 'source.labels': unknown attribute source.labels
	* instance='requestcountquota.instance.istio-system': failed to evaluate expression for field 'Dimensions[destinationVersion]'; unknown attribute destination.labels
	* instance='responsesize.instance.istio-system': failed to evaluate expression for field 'Value'; unknown attribute response.size
	* rule='tcpkubeattrgenrulerule.rule.istio-system'.Match: unknown attribute context.protocol
	* action='tcpkubeattrgenrulerule.rule.istio-system[0]': Instance not found: instance='attributes'
	* action='tcpkubeattrgenrulerule.rule.istio-system[0]': No valid instances found
	* rule=tcpkubeattrgenrulerule.rule.istio-system: No valid actions found in rule
	* rule='promtcp.rule.istio-system'.Match: unknown attribute context.protocol
	* action='promtcp.rule.istio-system[0]': Instance not found: instance='tcpbytesent'
	* action='promtcp.rule.istio-system[0]': Instance not found: instance='tcpbytereceived'
	* action='promtcp.rule.istio-system[0]': No valid instances found
	* rule=promtcp.rule.istio-system: No valid actions found in rule
	* rule='promtcpconnectionclosed.rule.istio-system'.Match: unknown attribute context.protocol
	* action='promtcpconnectionclosed.rule.istio-system[0]': Instance not found: instance='tcpconnectionsclosed'
	* action='promtcpconnectionclosed.rule.istio-system[0]': No valid instances found
	* rule=promtcpconnectionclosed.rule.istio-system: No valid actions found in rule
	* rule='promhttp.rule.istio-system'.Match: unknown attribute context.protocol
	* action='promhttp.rule.istio-system[0]': Instance not found: instance='requestcount'
	* action='promhttp.rule.istio-system[0]': Instance not found: instance='requestduration'
	* action='promhttp.rule.istio-system[0]': Instance not found: instance='requestsize'
	* action='promhttp.rule.istio-system[0]': Instance not found: instance='responsesize'
	* action='promhttp.rule.istio-system[0]': No valid instances found
	* rule=promhttp.rule.istio-system: No valid actions found in rule
	* action='kubeattrgenrulerule.rule.istio-system[0]': Instance not found: instance='attributes'
	* action='kubeattrgenrulerule.rule.istio-system[0]': No valid instances found
	* rule=kubeattrgenrulerule.rule.istio-system: No valid actions found in rule
	* rule='checkip.rule.default'.Match: unknown attribute source.labels
	* action='checkip.rule.default[0]': Instance not found: instance='sourceip'
	* action='checkip.rule.default[0]': No valid instances found
	* rule=checkip.rule.default: No valid actions found in rule
	* rule='quota.rule.istio-system'.Match: unknown attribute request.headers
	* action='quota.rule.istio-system[0]': Instance not found: instance='requestcountquota'
	* action='quota.rule.istio-system[0]': No valid instances found
	* rule=quota.rule.istio-system: No valid actions found in rule
	* rule='promtcpconnectionopen.rule.istio-system'.Match: unknown attribute context.protocol
	* action='promtcpconnectionopen.rule.istio-system[0]': Instance not found: instance='tcpconnectionsopened'
	* action='promtcpconnectionopen.rule.istio-system[0]': No valid instances found
	* rule=promtcpconnectionopen.rule.istio-system: No valid actions found in rule

**Expected behavior**
It should configure requestcountquota correctly.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
Istio version: 1.4.2

**How was Istio installed?**
helm template

**Environment where bug was observed (cloud vendor, OS, etc)**
AKS

**Comment by bianpengyuan** [comment]
I think this is same as https://github.com/istio/istio/issues/19164 which is actively being worked on.
