### ISSUE TITLE
Build container: /gobin thrown away on each invocation

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#19943]
On a fresh run of the build container, GOBIN=/gobin, and /gobin is empty. When running `make init`, we store the envoy binary there: https://github.com/istio/istio/blob/94c8d78639bcc92502e0ecb148abea51eb94334d/bin/init.sh#L29

Then, we throw away gobin on the next run, so we lose the envoy binary and things break (try `make pilot-test`. It may work the first time if you don't have `out/linux_amd64/istio_is_init` file, but will fail the next time).

Its not clear to me why we have /gobin instead of just using /go/bin.

This can be fixed by `export GOBIN = $(GOPATH)/bin` in the makefile (or the docker image), but I am not sure if this is a good fix.

**Comment by sdake** [comment]
Will test. envoy is supposed to output to out/os_arch/envoyblob, not to /gobin.

Cheers
-steve

**Comment by howardjohn** [comment]
Fixed by putting it in out/
