### ISSUE TITLE
TestEndpointUpdate fails frequently

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#19941]
https://prow.istio.io/view/gcs/istio-prow/logs/unit-tests_istio_postsubmit/1014 is one example

cc @hzxuzhonghu if you have any ideas. I looked into it a bit and didn't make much progress

**Comment by hzxuzhonghu** [comment]
/assign

I will have a look

**Comment by howardjohn** [comment]
I started looking at this again, its not just that test but many in the suite. Seems like some pods are missing for some reason. The k8s informer doesn't have them at all

**Comment by howardjohn** [comment]
informer.Get() will return no pods, but client.CoreV1.Pods() will return the pods

**Comment by hzxuzhonghu** [comment]
We can use `Informer().GetIndexer().Add` to add pods and nodes instead of using the fake client

**Comment by howardjohn** [comment]
I am not sure how that would work. You mean create a fake client, call newInformer(fake-client), but then use `Informer().GetIndexer().Add` instead of fake-client.Add()?

I am going to open a k8s issue as well since it seems like a bug

**Comment by hzxuzhonghu** [comment]
yes, i mean that. And just take a look at some k8s ut, they do not use it as istio.

**Comment by howardjohn** [comment]
That would involve changing our real implementation, not just the test,
which isn't great

**Comment by howardjohn** [comment]
nevermind, I figured it out. I'll send a PR
