### ISSUE TITLE
Support istiod using a certificate issued by Citadel

### ISSUE THREAD

**Issue by lei-tang** [istio/istio#19950]
**Describe the feature request**
In platforms that do not have k8s signing APIs, istiod can use a certificate issued by Citadel. This feature is to support istiod using a certificate issued by Citadel.

**Describe alternatives you've considered**
istiod uses a certificate issued by a non-k8s CA.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
done
