### ISSUE TITLE
[istio.io testing] Need test for Health Checking of Istio Services

### ISSUE THREAD

**Issue by brian-avery** [istio/istio#19953]
**Describe the feature request**
We need to develop a test for the [Health Checking of Istio Services](https://preliminary.istio.io/docs/ops/configuration/mesh/app-health-check/) task in order to provide automated testing of the Istio.io website for future releases.

Example tests and the documentation for the framework can be found here: https://github.com/istio/istio/tree/master/tests/integration/istioio

A YouTube video describing the usage of the framework can be found here: https://www.youtube.com/watch?v=3y-z8NaVwr0

Please reach out to the Test and Release channel on the [Istio Slack](https://discuss.istio.io/t/istio-slack-channel/1527) or [Test and Release Discuss](https://discuss.istio.io/c/test-and-release)  with any questions.

**Additional context**

**Comment by dgn** [comment]
@shamsher31 are you interested in taking a look at this? I can answer questions should any come up

**Comment by shamsher31** [comment]
Sure, I will work on it.

**Comment by brian-avery** [comment]
Thanks! Let me know if you have any questions.
