### ISSUE TITLE
upstream connect error or disconnect/reset before headers. reset reason: connection termination

### ISSUE THREAD

**Issue by rnkhouse** [istio/istio#19966]
**Bug description**
I upgraded istio from 1.3.6 to 1.4.2 and suddenly getting below error. Are there any changes that I need to make on version 1.4.2 to run previous applications? How can I debug this error to know the actual issue? In the logs there is no info other than error code 503.

>upstream connect error or disconnect/reset before headers. reset reason: connection termination

I checked service is up and running with the valid endpoint.

**service.yaml**

    ---
    apiVersion: v1
    kind: Service
    metadata:
      name: njb
      labels:
        app: njb
    spec:
      selector:
        app: njb
      ports:
      - protocol: TCP
        port: 8080
        targetPort: 8080
      type: ClusterIP

**Application istio-proxy logs**

    {"upstream_local_address":"127.0.0.1:57338","duration":"0","downstream_local_address":"10.2.0.22:8080","upstream_transport_failure_reason":"-","route_name":"-","response_code":"0","user_agent":"-","response_flags":"-","start_time":"2020-01-07T15:27:16.858Z","method":"-","request_id":"-","upstream_host":"127.0.0.1:8080","x_forwarded_for":"-","requested_server_name":"outbound_.8080_._.njb.default.svc.cluster.local","bytes_received":"1026","istio_policy_status":"-","bytes_sent":"47","upstream_cluster":"inbound|8080||njb.default.svc.cluster.local","downstream_remote_address":"10.2.0.27:54704","authority":"-","path":"-","protocol":"-","upstream_service_time":"-"}
    {"upstream_local_address":"127.0.0.1:57342","duration":"7","downstream_local_address":"10.2.0.22:8080","upstream_transport_failure_reason":"-","route_name":"-","response_code":"0","user_agent":"-","response_flags":"-","start_time":"2020-01-07T15:27:17.246Z","method":"-","request_id":"-","upstream_host":"127.0.0.1:8080","x_forwarded_for":"-","requested_server_name":"outbound_.8080_._.njb.default.svc.cluster.local","bytes_received":"976","istio_policy_status":"-","bytes_sent":"47","upstream_cluster":"inbound|8080||njb.default.svc.cluster.local","downstream_remote_address":"10.2.0.27:54708","authority":"-","path":"-","protocol":"-","upstream_service_time":"-"}

**ingress gateway logs**

    {"upstream_host":"10.2.0.22:8080","x_forwarded_for":"xx.xx.xx.xx","requested_server_name":"njb.example.com","bytes_received":"0","istio_policy_status":"-","bytes_sent":"95","upstream_cluster":"outbound|8080||njb.default.svc.cluster.local","downstream_remote_address":"xx.xx.xx.xx:55716","authority":"njb.example.com","path":"/favicon.ico","protocol":"HTTP/2","upstream_service_time":"-","upstream_local_address":"-","duration":"9","downstream_local_address":"10.2.0.27:443","upstream_transport_failure_reason":"-","route_name":"-","response_code":"503","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36","response_flags":"UC","start_time":"2020-01-07T15:27:17.244Z","method":"GET","request_id":"6bee7a01-b823-499d-857a-a2c6025409c3"}

**Extra info**

    istioctl authn tls-check istio-ingressgateway-564dc4b8dc-gng28.istio-system njb.default.svc.cluster.local
    HOST:PORT                              STATUS     SERVER     CLIENT           AUTHN POLICY     DESTINATION RULE
    njb.default.svc.cluster.local:8080     OK         STRICT     ISTIO_MUTUAL     /default         istio-system/default

**Expected behavior**
The application should run without error message over ingress gateway.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.4.2

**How was Istio installed?**
helm template

**Environment where bug was observed (cloud vendor, OS, etc)**
AKS

**Comment by rnkhouse** [comment]
Not sure why is this happening but when I added name in Service ports it worked.

   ports:
       - name: https # Use http or https
          protocol: TCP
          port: 8080
          targetPort: 8080

**Comment by bishtawi** [comment]
Just commenting here to say that I encountered this same error (`upstream connect error or disconnect/reset before headers. reset reason: connection termination`) when I upgraded from 1.3 to 1.4 and wasted a ton of time trying to debug and figure out what exactly was causing it. I was able to downgrade to 1.3.x with no issue so it was not a huge blocker or anything but just had no idea how to fix it.

Your solution of adding names to the ports in the Kubernetes Services worked for me and I am very grateful. 

This should be documented somewhere as it is not obvious. Kubernetes Service port names are optional and I am sure a lot of other people are hitting this wall. [Here](https://github.com/istio/istio/issues/19993#issuecomment-575892321) for example.

**Comment by baocang** [comment]
Thx @rnkhouse, it works for me too

**Comment by JoeJasinski** [comment]
I had this same issue too when I upgraded to Istio 1.4.6, but I did NOT see it with Istio 1.4.3. However, simply giving the port a name did not work. I had previously named it `interface`, but that resulted in the above error. When I named it `http`, then it worked fine.

**Comment by trieszklr** [comment]
see it too with istio 1.4.4

**Comment by Krenair** [comment]
I've just run into this as well - this feels like something that should've been mentioned at https://istio.io/news/releases/1.4.x/announcing-1.4/upgrade-notes/
It looks like things like https://github.com/helm/charts/blob/master/stable/concourse/templates/web-svc.yaml#L36 are incompatible with this requirement?

**Comment by Krenair** [comment]
Setting PILOT_ENABLE_PROTOCOL_SNIFFING_FOR_OUTBOUND=false in the istio-pilot deployment environment and deleting the istio-ingressgateway/gsp-concourse-web pods has also done the trick, with an atc ServicePort name.
I've also found that skipping 1.4.x entirely and going to 1.5 is fine.

**Comment by fatimariaz17** [comment]
Had same issue for jaeger service. Having istio 1.4.3 version.
Changed port name from query-http to http-query and it worked!
Please fix it.

**Comment by sourabhparsekar** [comment]
> Not sure why is this happening but when I added name in Service ports it worked.
> 
> ```
> ports:
>     - name: https # Use http or https
>        protocol: TCP
>        port: 8080
>        targetPort: 8080
> ```

This one worked for us too.. phew..  great save....

**Comment by xh3b4sd** [comment]
FWIW I had the same problem with the service port names. Though in my case it was that `grpcurl` could talk to the gRPC server backend behind envoy, where some webapp could not. So I changed `name` from `grpc` to `grpc-web` and made it work for both the webapp and `grpcurl`. There is something about upgrading HTTP 1.1 to HTTP 2 that I do not fully understand why the Kubernetes service name would have such an effect. `grpcurl` speaks HTTP 2 natively whereas the gRPC web magic does not.

**Comment by eooall** [comment]
ports:
    - port:  12306
      name: web-http
      targetPort: 12306

error 

 ports:
    - port:  12306
      name: grpc-web-http
      targetPort: 12306

success

????

**Comment by jonaseicher** [comment]
@eooall: your second example follows the naming convention from the docs:
https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/#manual-protocol-selection

**Comment by said-saifi** [comment]
Just to make it clear for others, the name is not a free text.

From [the docs](https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/#explicit-protocol-selection)

> By the name of the port: name: <protocol>[-<suffix>].
In Kubernetes 1.18+, by the appProtocol field: appProtocol: <protocol>.

Example from the docs

```yaml
kind: Service
metadata:
  name: myservice
spec:
  ports:
  - number: 3306
    name: database
    appProtocol: https
  - number: 80
    name: http-web

```
