### ISSUE TITLE
Selector of Gateway custom resource is not bound by namespace

### ISSUE THREAD

**Issue by devkid** [istio/istio#19970]
**Bug description**

The [documentation](https://istio.io/docs/reference/config/networking/gateway/#Gateway) for `Gateway` custom resources states:
> `selector`: One or more labels that indicate a specific set of pods/VMs on which this gateway configuration should be applied. The scope of label search is restricted to the configuration namespace in which the the resource is present. In other words, the Gateway resource must reside in the same namespace as the gateway workload instance.

However, this is not the case. The default `istio-ingressgateway` workload in the `istio-system` that comes with the Helm chart setup can be configured with `Gateway` resources in any other namespace.

I would consider this a security risk as it violates the namespace isolation. However, this bug/feature is even used in the bookinfo example application:
* https://istio.io/docs/examples/bookinfo/#determine-the-ingress-ip-and-port
* https://raw.githubusercontent.com/istio/istio/release-1.4/samples/bookinfo/networking/bookinfo-gateway.yaml

**Expected behavior**

`Gateway` custom resources should only configure workloads in the same namespace.

**Steps to reproduce the bug**

Install istio with the helm chart. Create a `test` namespace and create a `Gateway` in that namespace that defines a HTTP server on port 12345, use selector `istio: ingressgateway`:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: testgateway
  namespace: test
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 12345
      protocol: HTTP
```

Notice that the `istio-ingressgateway` pods in the `istio-system` namespace will start to listen on port 12345.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4", GitTreeState:"clean", BuildDate:"2019-12-16T16:32:54Z", GoVersion:"go1.12.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-c0eccc", GitCommit:"c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2", GitTreeState:"clean", BuildDate:"2019-12-22T23:14:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

$ helm version
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}

$ istioctl version --remote
client version: 1.4.0
control plane version: 1.4.0
data plane version: 1.4.0 (7 proxies)
```

**How was Istio installed?**

With helm.

**Environment where bug was observed (cloud vendor, OS, etc)**

AWS EKS 1.14.

**Comment by LaysDragon** [comment]
I don't understand,if this is a bug,that mean we should deploy every loadbalanced gateway for every namespace insteaded of a share ingress gateway like regular ingress controller did,that sounds ridiculous since it eally kind of wasted of public ip. Or did I misunderstanding something?

**Comment by LaysDragon** [comment]
That sounds not conveniences if compare to how we configure ingress resource.why we need to isolated Gateway resources in istio ingress workload namespace.

**Comment by incfly** [comment]
I think this is a bug, we just haven't find any bandwidth to address. I remember this was mentioned mulitple times in networking WG meeting. not sure if anyone is working on that actively though...
@rshriram might know a bit more though.

**Comment by howardjohn** [comment]
There is a flag to switch behavior; PILOT_SCOPE_GATEWAY_TO_NAMESPACE. The problem is we will break 99% of users if we change this in a release, even our demos rely on this scoping

**Comment by myidpt** [comment]
@howardjohn Thanks for the pointer.
So we do have the flag PILOT_SCOPE_GATEWAY_TO_NAMESPACE to enforce the namespace boundary. The questions is can we make it true by default. Changing it in 1.7 will break our customers if they don't follow the instructions. I think in 1.7, we should update the security best practice to instruct enabling PILOT_SCOPE_GATEWAY_TO_NAMESPACE, and change our demos so that they are not misleading. We may change the default behavior in 1.8.

**Comment by howardjohn** [comment]
I would like to point out the Ingress behaves the same way as the default (cross namespace). A common workflow is for app teams to deploy Ingress+certs in their own namespace, without access to `ingress-namespace`. Granted, this doesn't even work in Istio today since the certs aren't searched cross-namespace..

**Comment by myidpt** [comment]
I think the best security practice is enforcing that the ingress gateway pod, ingress gateway certs and gateway configuration should all be in the same namespace. This requires setting `PILOT_SCOPE_GATEWAY_TO_NAMESPACE=true` today, and I hope this can be the default in 1.8.

With that said, we *may* offer an option for cross-namespace Ingress gateway. This breaks the security boundary between namespaces, while offering convenience for single-tenant use cases (I'm seeing customers asking for it). This requires ingress gateway to load ingress gateway keys and certs from different namespaces, which we don't support today.

**Comment by howardjohn** [comment]
I think its useful to look at other providers:

* ingress-gce - just `Ingress`. There is no LB running in cluster. Read secrets from `Ingress` namespace (only)
* ingress-nginx - just `Ingress`. There is a deployment running in cluster. Read secrets from `Ingress` namespace (only). No plans to change - see https://github.com/kubernetes/ingress-nginx/issues/2170
* cert-manager - integrates with `Ingress` and creates secret in the Ingress namespace (see https://cert-manager.io/docs/usage/ingress/). This doesn't work with Istio Ingress but works with every other Ingress
* contour - Supports `Ingress` with standard secret scoping. Also supports CRD [IngressRoute](https://projectcontour.io/docs/v1.4.0/ingressroute/) which can delegate cross namespace ie `secretName: somenamespace/somesecret`. This is controlled by a TLSCertificateDelegation resource which allows declaring which namespaces can access a cert
* Ambassador - TBD, looking into it
* Istio
  * Supports Gateway in any namespace, but certs only in deployment namespace
  * Supports Ingress in any namespace, but certs only in deployment namespace
  * with PILOT_SCOPE_GATEWAY_TO_NAMESPACE=true, supports Gateway in deployment namespace, and certs only in deployment namespace

Things to note here based on the above - this may not be 100% accurate as there are other Ingress providers I missed:
* Istio is the only Ingress provider not implementing the Ingress spec correctly - I confirmed with the k8s networking team, cross namespace secret reference is *not* following the Ingress spec.
* Istio is the only provider that doesn't allow cross namespace deployment <-> certificate
