### ISSUE TITLE
Hard-coded namespaces in istiod

### ISSUE THREAD

**Issue by lei-tang** [istio/istio#19987]
**Bug description**
In istiod, there are hard-coded namespaces in "istiod.istio-system", e.g.,
- https://github.com/istio/istio/blob/master/pilot/pkg/bootstrap/certcontroller.go#L123 
- https://github.com/istio/istio/blob/master/pilot/pkg/bootstrap/certcontroller.go#L124
	if hostname == "istio-pilot.istio-system.svc" {
		names = append(names, "istiod.istio-system.svc")
	}
- https://github.com/istio/istio/blob/master/pilot/pkg/bootstrap/certcontroller.go#L128
- https://github.com/istio/istio/blob/master/pilot/pkg/bootstrap/certcontroller.go#L129
	if hostname == "istiod.istio-system.svc" {
		names = append(names, "istio-pilot.istio-system.svc")
	}
- https://github.com/istio/istio/blob/master/pilot/pkg/bootstrap/istio_ca.go#L164
	caServer, startErr := caserver.NewWithGRPC(grpc, ca, maxWorkloadCertTTL.Get(),
		false, []string{"istiod.istio-system"}, 0, spiffe.GetTrustDomain(),
		true)
- https://github.com/istio/istio/blob/master/pkg/istio-agent/sds-agent.go#L204
         discHost = "istiod.istio-system.svc"
- https://github.com/istio/istio/blob/master/pkg/istio-agent/sds-agent.go#L354
	serverOptions.CAEndpoint = "istio-citadel.istio-system:8060"
- https://github.com/istio/istio/blob/master/pkg/istio-agent/sds-agent.go#L359
https://github.com/istio/istio/blob/master/pkg/istio-agent/sds-agent.go#L362
					serverOptions.CAEndpoint = "istiod.istio-system.svc:15010"
				} else {
					log.Info("Using default istiod CA, with K8S certificates for SDS")
					serverOptions.CAEndpoint = "istiod.istio-system.svc:15012"

[X ] Configuration Infrastructure
[ ] Docs
[X ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by incfly** [comment]
Would be better to use priority when tracking internal work item.

**Comment by howardjohn** [comment]
Not stale - we should add a test outside of istio-system

**Comment by williamaronli** [comment]
it seems code here(https://github.com/istio/istio/blob/master/pilot/pkg/bootstrap/certcontroller.go#L121-L124) is not ever hardcoded could we close it?

**Comment by howardjohn** [comment]
All usages mentioned above and as detected by `rg "istio-system" **/*.go -l | grep -v test | xargs rg istio-system -C 2` seem appropriate or resolved. Closing
