### ISSUE TITLE
istioctl version panic 

### ISSUE THREAD

**Issue by esnible** [istio/istio#19981]
Reported in Istio Slack by Adam Miller

$ istioctl version
panic: runtime error: index out of range [0] with length 0
goroutine 1 [running]:
istio.io/pkg/version.identicalVersions(0x4140a00, 0x0, 0x0, 0xc00083d928)
        istio.io/pkg@v0.0.0-20191030005435-10d06b6b315e/version/cobra.go:151 +0x12a
istio.io/pkg/version.coalesceVersions(...)
        istio.io/pkg@v0.0.0-20191030005435-10d06b6b315e/version/cobra.go:138
istio.io/pkg/version.CobraCommandWithOptions.func1(0xc000639180, 0x4140a00, 0x0, 0x0, 0x0, 0x0)
        istio.io/pkg@v0.0.0-20191030005435-10d06b6b315e/version/cobra.go:87 +0x12f
github.com/spf13/cobra.(*Command).execute(0xc000639180, 0x4140a00, 0x0, 0x0, 0xc000639180, 0x4140a00)
        github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc000638f00, 0x1, 0x1, 0xc000638f00)
        github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
        istio.io/istio@/istioctl/cmd/istioctl/main.go:29 +0x76

**Comment by esnible** [comment]
Closing as a duplicate of https://github.com/istio/istio/issues/18925 .  This fix is in master, not 1.4.x.

@howardjohn Should https://github.com/istio/pkg/pull/90 be back-ported to Istio 1.4.x?

**Comment by esnible** [comment]
@adammil2000 if this happens again please do `istioctl version -o json` and paste the output here or send it to me, so that I can further improve things.

You can also download Istio 1.5.0 alpha-0, which has this fixed, but the problem might not be obvious with the fixed version.  Istio tries to do `kubectl exec` into the control plane running instances, which could fail under some circumstances.

**Comment by ericvn** [comment]
It looks like the original problem was written against 1.3.4 so maybe really needs to be cherrypicked back to 1.4 and 1.3?

**Comment by esnible** [comment]
@ericvn Agreed.  I have added the labels to cherry pick, but the change was two months ago, and this is istio/pkg not istio/istio.  Let us see if the automatic cherry-picking works.  If not, I will ask @georgyturevich to create 1.3 and 1.4 PRs with his commit for https://github.com/istio/pkg/pull/90 .

**Comment by a-h-abid** [comment]
> @adammil2000 if this happens again please do `istioctl version -o json` and paste the output here or send it to me, so that I can further improve things.

I am having similar problem when running `istioctl version`. Pods are showing `Running` status.

```
$ istioctl version -o json
{
  "clientVersion": {
    "version": "1.4.3",
    "revision": "17f6bfc3d7121ad527c2d617ffc27c758d6a7241-dirty",
    "golang_version": "go1.13.4",
    "status": "Modified",
    "tag": "1.4.3"
  },
  "meshVersion": []
}
Error: 7 errors occurred:
        * error execing into istio-citadel-f78ff689-hz6c7 citadel container: error dialing backend: dial tcp 10.10.23.60:10250: connect: connection refused
        * error execing into istio-galley-fd9694b9c-fclf5 galley container: error dialing backend: dial tcp 10.10.23.61:10250: connect: connection refused
        * error execing into istio-ingressgateway-576f494c7c-b4jg6 istio-proxy container: error dialing backend: dial tcp 10.10.23.60:10250: connect: connection refused
        * error execing into istio-pilot-5c68bb85df-q2b2d discovery container: error dialing backend: dial tcp 10.10.23.61:10250: connect: connection refused
        * error execing into istio-policy-587798bdcc-rsx7g mixer container: error dialing backend: dial tcp 10.10.23.60:10250: connect: connection refused
        * error execing into istio-sidecar-injector-7dd87d7989-hwknn sidecar-injector-webhook container: error dialing backend: dial tcp 10.10.23.60:10250: connect: connection refused
        * error execing into istio-telemetry-75c64d988b-gld46 mixer container: error dialing backend: dial tcp 10.10.23.60:10250: connect: connection refused
```
