### ISSUE TITLE
istioctl manifest apply upgrades without confirmation

### ISSUE THREAD

**Issue by esnible** [istio/istio#19997]
`istioctl manifest apply` MUST ask for confirmation unless `--skip-confirmation` is supplied.

It does.  However, `istioctl manifest apply --set profile=demo` also MUST ask, and it doesn't.

In addition, `istioctl manifest apply --dry-run` expects confirmation.  It shouldn't, the default for skip-confirmation should be TRUE for dry runs.

**Comment by esnible** [comment]
At the same time, let's change the text for the `--filename` parameter:

```
 --filename string              Path to file containing IstioControlPlane CustomResource
```

should be

```
 --filename string              Path to file containing IstioControlPlane custom resource
```

**Comment by esnible** [comment]
When I originally created this I thought that it was a bug that `istioctl manifest apply --profile=demo` automatically installs the demo profile, instead of asking for confirmation the way `istioctl manifest apply`.  However, this behavior was by design.  We can change it, but I have not heard any complaints.

The remaining problem is that it asks for confirmation for a --dry-run which is silly.

**Comment by esnible** [comment]
Accidentally closed.

cc @j-martin

**Comment by j-martin** [comment]
Sounds good, I am assuming `istio install` is depending on `istio upgrade` (and other helm semantics) so we can assume they'll both be fixed or should the issue be modified to include both `install` and `upgrade`?
