### ISSUE TITLE
AuthorizationPolicy documentation errors

### ISSUE THREAD

**Issue by xeviknal** [istio/istio#19994]
**Bug description**
There are couple of broken references at [AuthenticationPolicy reference page](https://istio.io/docs/reference/config/security/authorization-policy/).

1. [WorkloadSelector](https://istio.io/docs/reference/config/security/authorization-policy/#AuthorizationPolicy) - In the table, in the selector row description, the column Type has the WorkloadSelector link broken.

2. [Condition type](https://istio.io/docs/reference/config/security/authorization-policy/#Condition) - The link on the key row goes to an unexpected place. If I am not wrong, it should point to https://istio.io/docs/reference/config/security/conditions/

**Comment by frankbu** [comment]
Both of these links are generated from the .proto file in istio/api. They need to be fixed there.

**Comment by yangminzhu** [comment]
thanks for the report, I will fix this in the api repo.

**Comment by incfly** [comment]
Seems like you already fixed? Closing.
