### ISSUE TITLE
TCP Traffic Shifting task bug

### ISSUE THREAD

**Issue by karlhungus** [istio/istio#19995]
**Bug description**

Attempting to run through the task [TCP Traffic Shifting](https://istio.io/docs/tasks/traffic-management/tcp-traffic-shifting/), fails when attempting to retrieve the INGRESS_PORT (step 3):

`export INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="tcp")].port}')`

**Expected behavior**

I expected to get a port from the previous command but got none, looking at the yaml generated by `istioctl manifest generate --set profile=demo` (assuming this is the same as used by `istioctl manifest apply --set profile=demo`) gives:

```
apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  namespace: istio-system
  annotations:
  labels:
    app: istio-ingressgateway
    release: istio
    istio: ingressgateway
spec:
  type: LoadBalancer
  selector:
    app: istio-ingressgateway
  ports:
    -
      name: status-port
      port: 15020
      targetPort: 15020
    -
      name: http2
      port: 80
      targetPort: 80
    -
      name: https
      port: 443
    -
      name: kiali
      port: 15029
      targetPort: 15029
    -
      name: prometheus
      port: 15030
      targetPort: 15030
    -
      name: grafana
      port: 15031
      targetPort: 15031
    -
      name: tracing
      port: 15032
      targetPort: 15032
    -
      name: tls
      port: 15443
      targetPort: 15443
```

Which has no port named tcp, looking at yaml output for my applied service is identical:

```
kubectl -n istio-system get service istio-ingressgateway -o yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"istio-ingressgateway","istio":"ingressgateway","operator.istio.io/component":"IngressGateway","operator.istio.io/managed":"Reconcile","operator.istio.io/version":"1.4.0","release":"istio"},"name":"istio-ingressgateway","namespace":"istio-system"},"spec":{"ports":[{"name":"status-port","port":15020,"targetPort":15020},{"name":"http2","port":80,"targetPort":80},{"name":"https","port":443},{"name":"kiali","port":15029,"targetPort":15029},{"name":"prometheus","port":15030,"targetPort":15030},{"name":"grafana","port":15031,"targetPort":15031},{"name":"tracing","port":15032,"targetPort":15032},{"name":"tls","port":15443,"targetPort":15443}],"selector":{"app":"istio-ingressgateway"},"type":"LoadBalancer"}}
  creationTimestamp: "2020-01-06T20:24:54Z"
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
    operator.istio.io/component: IngressGateway
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.4.0
    release: istio
  name: istio-ingressgateway
  namespace: istio-system
  resourceVersion: "2388201"
  selfLink: /api/v1/namespaces/istio-system/services/istio-ingressgateway
  uid: 9931e977-30c2-11ea-971f-025000000001
spec:
  clusterIP: 10.96.9.163
  externalTrafficPolicy: Cluster
  ports:
  - name: status-port
    nodePort: 32073
    port: 15020
    protocol: TCP
    targetPort: 15020
  - name: http2
    nodePort: 32300
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    nodePort: 30452
    port: 443
    protocol: TCP
    targetPort: 443
  - name: kiali
    nodePort: 30940
    port: 15029
    protocol: TCP
    targetPort: 15029
  - name: prometheus
    nodePort: 31494
    port: 15030
    protocol: TCP
    targetPort: 15030
  - name: grafana
    nodePort: 31657
    port: 15031
    protocol: TCP
    targetPort: 15031
  - name: tracing
    nodePort: 30764
    port: 15032
    protocol: TCP
    targetPort: 15032
  - name: tls
    nodePort: 32307
    port: 15443
    protocol: TCP
    targetPort: 15443
  selector:
    app: istio-ingressgateway
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: localhost
```

**Steps to reproduce the bug**

Follow the getting started install instructions, then follow "tcp traffic shifting" task

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
client version: 1.4.2
control plane version: 1.4.2
data plane version: 1.4.2 (2 proxies)
```

**How was Istio installed?**

Following the setup instructions https://istio.io/docs/setup/getting-started/ (using docker desktop)

**Environment where bug was observed (cloud vendor, OS, etc)**

docker desktop for mac

**Comment by howardjohn** [comment]
We are missing the 
```
  - port: 31400
    name: tcp
    nodePort: 31400
```

The old installer had

**Comment by karlhungus** [comment]
@howardjohn in an attempt to be a smidgeon helpful i added some updates to operator here: https://github.com/istio/operator/compare/master...karlhungus:add_back_tcp_to_default_installer?expand=1, in particular https://github.com/istio/operator/compare/master...karlhungus:add_back_tcp_to_default_installer?expand=1#diff-d15d785a311f59dff2902f7cd6c55d0cR39566

I've got some tests to fix, and i suspect the `fmt` commit could be contentious, but before i pr'd that i wanted to double check the port number -- 31400 looks nodeport ish to me - i would have expected something in the 15000's

**Comment by howardjohn** [comment]
The `fmt` commit is contentious because the file is autogenerated :slightly_smiling_face: 

I think the original intent of the 31400 was just as an example, so its possible it was intentionally removed. What may be more useful would be to instead document how to add a port and include that in the docs. I don't feel too strongly either way though

**Comment by karlhungus** [comment]
>file is autogenerated

woops!

> instead document how to add a port

yeah, that makes more sense; ie update the tutorial -- having a port named tcp seemed weird.
