### ISSUE TITLE
istioctl manifest apply --set has poor/incorrect CLI usage instructions

### ISSUE THREAD

**Issue by esnible** [istio/istio#19999]
`istioctl manifest apply --help` explains:

```
  -s, --set strings                  Set a value in IstioControlPlane CustomResource. e.g. --set policy.enabled=true.
                                     Overrides the corresponding path value in the selected profile or passed through IstioControlPlane CR
```

@frankbu The CLI usage SHOULD tell users that the path values are documented at https://istio.io/docs/reference/config/istio.operator.v1alpha12.pb/#IstioControlPlaneSpec

`--set` is used to:

- choose a profile (`--set profile=demo`)
- enable/disable components (`--set policy.enabled=true`)
- override Istio settings (`--set values.global.mtls.enabled=true`)

The CLI usage instructions should have an examples of all three of these cases.

Currently _istio.io/operator/cmd/mesh/manifest-apply.go_ has no `Example:` under it's cobra.Command.

The current text "Overrides the corresponding path value in the selected profile" is especially confusing because the command can be used to select the profile, not just override the selected profile.

**Comment by howardjohn** [comment]
```
  -s, --set stringArray              Override an IstioOperator value, e.g. to choose a profile
                                     (--set profile=demo), enable or disable components (--set components.policy.enabled=true), or override Istio
                                     settings (--set values.grafana.enabled=true). See documentation for more info:
                                     https://istio.io/docs/reference/config/istio.operator.v1alpha12.pb/#IstioControlPlaneSpec
```

This appears fixed
