### ISSUE TITLE
istioctl manifest apply should preserve the IstioControlPlane custom resource used

### ISSUE THREAD

**Issue by esnible** [istio/istio#20000]
The custom resource is needed for the `istioctl verify-install` command.

I'd like to see it preserve it in the cluster by default, in the CLI's file system optionally.

`istioctl verify-install` has an issue to be able to read these https://github.com/istio/istio/issues/18547

`istioctl verify-install` needs to know what the user installed.  Currently they do they by using what Helm generates when Istio is installed.  The linked work item is to allow the CLI to use the configuration from the Istio operator or `manifest apply` commands.

cc @irisdingbj

**Comment by esnible** [comment]
Currently, the user SHOULD do something like this:

```
./istioctl manifest apply --set values.global.mtls.enabled=true
./istioctl manifest generate --set values.global.mtls.enabled=true > i1.5mtls.yaml
./istioctl verify-install --enableVerbose=false --filename i1.5mtls.yaml
```

It is hard for the user to remember what options were used to deploy, and hard to remember how to create the "install manifest".  Also, `manifest generate` calls the output an "install manifest" but `verify-install` calls the input "Istio YAML installation file."

**Comment by irisdingbj** [comment]
@esnible 

Through https://github.com/istio/istio/pull/19284/

we support both IstioControlPlane cr as input: eg: 
```verify-install -f example-istiocontrolplane.cr.yaml```

we also support --set as input, eg: 
```verify-install -s profile=minimal .```

So it means we can use the same icp as we install Istio, no need to use istioctl manifest to generate the installation file before hand

**Comment by sdake** [comment]
storing the full generated manifest in `IstioControlPlane` imo is a nonstarter. The manifest can be enormous and its not really a good pattern used with operators.

@rcaballeromx do you have any thoughts on this particular point? Would like your expertise.

Cheers
-steve

**Comment by rcaballeromx** [comment]
@sdake I'll take a look

**Comment by sdake** [comment]
@rcaballeromx that was a mistarget, apologies, you can ignore.

**Comment by sdake** [comment]
@rcernich in case github didn't notify on the edit, can you PTAL :)

**Comment by rcernich** [comment]
Somebody needs to catch me up.  What is the goal behind this?  In the meantime...

If I'm inferring correctly, this is asking that the ICP resource be created in the cluster, so that it can be queried and used by the verify tool.  If that's the case, sounds good to me.  Maybe that syntax becomes something like:
```bash
$ kubctl -n istio-system get icp/my-mesh | istioctl verify-install -f -
```

Let me know how far off base I am.

**Comment by irisdingbj** [comment]
We already have `istioctl profile dump` so I do not think we need save the manifest in cluster any more and current command supports -set directly --means the same command parameter you used when you install Istio.

**Comment by rcernich** [comment]
My understanding was that this required you to remember what you used when you installed the control plane, hence the reason for storing the ICP.

@esnible can you confirm/clarify your original intent?

**Comment by esnible** [comment]
@sdake I don't want to store the full manifest in IstioControlPlane.  What I want is to store the ICP, ideally on the cluster, to act as a "bill of materials".  I propose adding the ICP CRD to Istio so users would get it without the operator, and `istioctl manifest apply` would save it.  This means 3k for the CRD, and 200 to 16k bytes per Istio control plane (typically one plane, sometimes two, rarely more).

I have several scenarios in mind.  We have a PR to let `istioctl verify-install` use an ICP in addition to the manifest.  Saving the ICP to the cluster would allow users -- the original installer and other cluster operators -- to verify the install without remembering the original install options.

It would also mean that if Istio got out-of-whack through manual actions the admin could install the Istio Operator and it would bring Istio back to the original intention.  Or the user could bring it back manually by doing `istioctl manifest apply --filename <(kubectl get istiocontrolplane default)`

If we can't save the ICP to the cluster in this version, because we don't want the ICP CRD present without the operator, can we at least add a CLI option to save it locally, e.g. `istioctl manifest apply --save-icp ~/my-istio-install.yaml` ?

Unrelated question: Why is https://github.com/istio/istio.io/blob/master/static/operator-profile-default.yaml 164 bytes long but `istioctl profile dump default` produces 15999 bytes?

**Comment by rcernich** [comment]
@esnible, thanks.  Makes sense to me.

**Comment by irisdingbj** [comment]
@esnible To your question: 

https://github.com/istio/istio.io/blob/master/static/operator-profile-default.yaml will get all base values from operator (default.yaml) and underneath it will use the some similar like the output in `istioctl profile dump` during install.

**Comment by irisdingbj** [comment]
@esnible regarding to the saving of istioctl command, can we use the way like `istioctl manifest apply --record=true`, and save the command we used as annotation in the installed ICP cr? similar thing like `kubectl --record=true`

**Comment by esnible** [comment]
@sdake @ayj I want this in 1.6.  Which working group can approve this?

All I am asking for is with this item is:
1. The IstioOperator CRD get installed in base Istio, even if the operator is not installed.
2. `istioctl` creates IstioOperator CR for each control plane it installs.
3. The CRD have printer fields so `kubectl get istiooperator` will list the control plane revisions in a multiple-control-plane scenario.
```

**Comment by ayj** [comment]
Env and UX sound like the right WGs. Can we use [RFC: Record Istio config using IstioControlPlane](https://docs.google.com/document/d/18Wv58x7U1EecEuQFIJScRDttluH15pgzmwq1nmup-24/) to discuss requirements?
