### ISSUE TITLE
Updates to existing multi-cluster configuration are not picked up by Pilot

### ISSUE THREAD

**Issue by nicktrav** [istio/istio#20005]
**Bug description**

Currently, when an existing multi-cluster Secret is updated, no action is taken by the secret controller.

This causes problems in situations where the configuration is modified to update, for example, the API endpoint for remote K8s masters that Pilot calls to infer workload information. Without a restart of Pilot pods, this configuration is not reflected. Principle of least surprise would lead us to believe there should be an update of the multi-cluster clients in this case.

A real world consequence of this in our deployment was that the API endpoints for the remote clusters was updated, Pilot did not pick up the configuration and could not fetch workload information from the remote clusters (the endpoints had been removed, but Pilot continued to attempt to scrape them). This resulted in stale endpoint configuration in each of the data plane proxies.

**Expected behavior**

Updating an existing multi-cluster secret with a new K8s API endpoint should result in existing clients being shut down and new clients being instantiated with the new endpoint configuration.

This could just be missing documentation (I took a look through the multi-cluster docs, but didn't see anything), however, I believe not honoring an update to an existing secret is something that should be addressed.

**Steps to reproduce the bug**

Updates are currently not handled in the secret controller:

https://github.com/istio/istio/blob/2a54b0a217b3520688c97a34605aaec2cfe90664/pkg/kube/secretcontroller/secretcontroller.go#L122-L137

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:41:55Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-gke.14", GitCommit:"56d89863d1033f9668ddd6e1c1aea81cd846ef88", GitTreeState:"clean", BuildDate:"2019-11-07T19:12:22Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}

$ istioctl version --remote
client version: unknown
control plane version: 1.4.2
```

NOTE: Despite running 1.4.x, the problem still exists on master.

**How was Istio installed?**

Helm.

**Environment where bug was observed (cloud vendor, OS, etc)**

GKE.

**Comment by hzxuzhonghu** [comment]
I remember we do support update in pilot before use the common secret controller

**Comment by hzxuzhonghu** [comment]
FYI https://github.com/istio/istio/pull/8479/files
