### ISSUE TITLE
perf tools: Integrate daily-performance runs into testgrid

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#20015]
Perf daily runs as a monolithic as runs for 11 hours.
The job should be integrated into testgrid so that individual tests are separately visible and failures are easy to identify.

**Comment by howardjohn** [comment]
This is already done: https://testgrid.k8s.io/istio_release-pipeline#daily-performance-benchmark-release-1.4

A better way to get notified of failures (in my opinion) is to join #test-failures in slack

**Comment by mandarjog** [comment]
That is not granular enough. We need these tests to be separated for visibility.

**Comment by howardjohn** [comment]
I see, I misunderstood. In that case you need the test to output a junit.xml file to `$ARTIFACTS` directory

**Comment by howardjohn** [comment]
@carolynhu should look like https://testgrid.k8s.io/istio_istio#integ-pilot-local-tests_istio&width=20&exclude-non-failed-tests=
