### ISSUE TITLE
Secure Prometheus scraping

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#20011]
Prometheus is a key part of Istio. In V2 telemetry It is used to scrape metrics exported directly by proxy at `:15090/stats/prometheus` and to scrape application metrics.

1. `:15090/stats/prometheus` is plaintext. We need to be able to protect behind mtls.
2. Scraping prometheus metrics from application is supported, but not fully.
   a. Relies on local certificates - so rotation is a problem.
   b. Istio Permissive mode does not work, unless alpn: istio is supplied
   c. Needs to use `no_verify_cert` option which disable all server verification.

There are several ways this can be done
1. Use a client side Envoy that uses SDS certs for cluster. 
    a. use [dynamic forward proxy](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/dynamic_forward_proxy_filter)
   b. set `tls_context` to use SDS
   c. use `proxy_url` scrape config option instead of ip tables.   This way only sidecar injected targets use envoy. [example](https://medium.com/jaegertracing/avoid-undesirable-trace-instances-when-scraping-prometheus-metrics-in-istio-92c26ebd7108)

Other options may be possible.

**Comment by douglas-reid** [comment]
@mandarjog is someone actively working on this issue, or are we looking for an owner?

**Comment by mandarjog** [comment]
Looking for an owner.

**Comment by mandarjog** [comment]
Not stale
