### ISSUE TITLE
Add analyzer for AuthorizationPolicy objects

### ISSUE THREAD

**Issue by xeviknal** [istio/istio#20025]
Add an analyzer for the AuthenticationPolicy objects.
What to analyze?
- [WorkloadSelector](https://istio.io/docs/reference/config/security/authorization-policy/#Source): check if there are deployments (creating pods) with the specific labels.
- [Rule.From.Source.Namespace](https://istio.io/docs/reference/config/security/authorization-policy/#Source): check if that list of namespaces are present.
- [Rule.To.Operation.Methods](https://istio.io/docs/reference/config/security/authorization-policy/#Operation): check if they are HTTP allowed methods or gRPC well formatted values (/pkg.svc/method)
- [Rule.To.Operation.Hosts](https://istio.io/docs/reference/config/security/authorization-policy/#Operation): check if each host of the list exists.

What do you think @sushicw ?

**Additional context**

**Comment by sushicw** [comment]
We should definitely do it. 

This duplicates https://github.com/istio/istio/issues/19076, closing this in favor of that. (I've copied your comments into the other issue).

**Comment by xeviknal** [comment]
Oh, didn't see that issue. Thanks :)
