### ISSUE TITLE
Istioctl autoscaleMin not applying

### ISSUE THREAD

**Issue by so-jelly** [istio/istio#20032]
**Bug description**

**Expected behavior**
`istioctl manifest generate --set values.mixer.policy.autoscaleMin=2` applies the appropriate HPA min pods value.

**Steps to reproduce the bug**
```
istioctl manifest apply --set values.mixer.policy.autoscaleMin=2
kubectl get -n istio-system hpa istio-policy -o yaml | yq .spec.minReplicas | grep 2
``` 

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

`istioctl version --remote`
> client version: 1.4.3
> citadel version: 1.4.3
> galley version: 1.4.3
> ingressgateway version: 1.4.3
> nodeagent version: 
> nodeagent version: 
> nodeagent version: 
> pilot version: 1.4.3
> pilot version: 1.4.3
> pilot version: 1.4.3
> policy version: 1.4.3
> policy version: 1.4.3
> sidecar-injector version: 1.4.3
> telemetry version: 1.4.3
> telemetry version: 1.4.3
> data plane version: 1.4.3 (5 proxies)
> 

`kubectl version`

> Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:51:13Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
> Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.4-gke.22", GitCommit:"a6ba43f5a24ac29e631bb627c9b2a719c4e93638", GitTreeState:"clean", BuildDate:"2019-11-26T00:40:25Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
> 

**How was Istio installed?**
istioctl manifest apply

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

This is a freshly installed cluster:

```
  gcloud container clusters create $CLUSTER \
    --cluster-version latest \
    --disk-type=pd-ssd \
    --enable-network-policy \
    --enable-stackdriver-kubernetes \
    --machine-type=n1-standard-4 \
    --no-enable-autoupgrade \
    --num-nodes=3 \
    --project $PROJECT \
    --zone $ZONE
```

The only reference to this setting is in the istio-sidecar config.   Is this where it should be set?

**Comment by richardwxn** [comment]
This issue was fixed in one recent PR I believed. And to verify, I tried istioctl from 1.4.2 and can reproduce the problem and latest master works ok.

This is correct way to do(using the helm values pass through), another way and actually what we recommend is setting from the operator API, the autoScaleMin is part of the HPA spec
