### ISSUE TITLE
Istioctl enable ILB Gateway

### ISSUE THREAD

**Issue by so-jelly** [istio/istio#20033]
**Bug description**

**Expected behavior**

`istioctl manifest generate --set values.gateways.istio-ilbgateway.enabled=true` creates the appropriate config

**Steps to reproduce the bug**

`istioctl manifest generate --set values.gateways.istio-ilbgateway.enabled=true`

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

1.4.3

**How was Istio installed?**

`istioctl`

**Environment where bug was observed (cloud vendor, OS, etc)**
MacOS

Additionally,  using `--set unvalidatedValues.gateways.istio-ilbgateway.enabled=true` does not create an ILB configuration as well.

**Comment by k8s-skipper** [comment]
Same problem, trying to migrate from helm installation to istioctl (as recommended), converting istio-values.yml to istio-profile.yml
`apiVersion: install.istio.io/v1alpha2`
`kind: IstioControlPlane`
`spec:`
`  values:`
`    global:`
`      gateways:`
`        istio-ilbgateway:`
`          enabled: true`
getting
` istioctl manifest generate -f istio-profile.yaml`
` input file failed validation with the following errors: unknown field "istio-ilbgateway" in v1alpha1.GatewaysConfig `

**Comment by pingz** [comment]
looks like for 1.4.3, this can only accept `istio-ingressgatey`.

https://github.com/istio/operator/blob/1.4.3/pkg/apis/istio/v1alpha1/values_types.pb.go

**Comment by EvertonSA** [comment]
So istio 1.4.3 cannot have a ilb if we install using istioctl?

**Comment by so-jelly** [comment]
@EvertonSA you have to add manually.  i believe 1.5.0 will use a list of both ingress and egress gateways to create multiple or custom ingresses

**Comment by seeruk** [comment]
Seems like Istio 1.5.0 was released without this. I'm quite eager to move from Helm to istioctl. It looks like master still only accepts the default `istio-ingressgateway`. Are there plans to fix this issue?

**Comment by ostromart** [comment]
@seeruk and others, there's no separate ILB anymore but it's possible to create an ILB gateway in 1.5 by setting serviceAnnotations like this:
```yaml
spec:
  ingressGateways:
  - name: istio-ilbgateway
    enabled: true
    k8s:
      serviceAnnotations:
        cloud.google.com/load-balancer-type: "internal"
        service:
          ports:
          # ...
```
Note that there's a bug in 1.5.0 that affects gateway naming fixed in https://github.com/istio/istio/pull/22138 that will be part of 1.5.1, so the name above currently will still show up in the generated manifest as istio-ingressgateway.
We're going to update the docs and provide some gateway examples as part of 1.5.1 release.

**Comment by PavelKarpenka** [comment]
@ostromart 
So starting v1.5.0 we don't have istio-ilbgateway any more and the workaround is to modify istio-ingressgateway (add annotation to make LB internal)?
