### ISSUE TITLE
Imbalanced load on spike traffic applications

### ISSUE THREAD

**Issue by Stono** [istio/istio#20055]
**Bug description**
Hi, 
I've been trying to debug why one instance of our application is getting significantly more load than the other during periods of burst load.  The setup is very simple:

![spike](https://user-images.githubusercontent.com/1486729/72135101-96abee00-337d-11ea-8439-1342dbd8da51.png)

You can see from this graph that there was a big spike in traffic (normal):

`sum(irate(envoy_cluster_upstream_rq_total{app="searchone-consumer", cluster_name=~"outbound.*search-one.svc.cluster.local"}[1m])) by (pod_name)`

<img width="1663" alt="Screenshot 2020-01-10 at 08 13 18" src="https://user-images.githubusercontent.com/1486729/72136613-18514b00-3381-11ea-9168-6660dd8b277c.png">

But the vast majority of them seemed to go to a single instance of search-one:

`sum(envoy_cluster_upstream_cx_active{app="search-one", cluster_name=~"inbound.*search-one.svc.cluster.local"}) by (pod_name, cluster_name)`

<img width="1624" alt="Screenshot 2020-01-10 at 08 10 36" src="https://user-images.githubusercontent.com/1486729/72136434-b7297780-3380-11ea-9a9c-fa9128904360.png">

This results in a huge amount more load on that instance (cpu graph):

<img width="1640" alt="Screenshot 2020-01-10 at 08 09 35" src="https://user-images.githubusercontent.com/1486729/72136393-9d883000-3380-11ea-983d-a7e68908692e.png">

I wondered it was some locality aware routing thing but we'd see that under normal load too, also you can see here the nodes don't align with those graphs:

```
❯ k get pods -o wide
NAME                          READY   STATUS    RESTARTS   AGE   IP             NODE                                                  NOMINATED NODE   READINESS GATES
search-one-7c54ff8bb4-6dfnj   2/2     Running   0          14h   10.226.12.48   gke-delivery-platform-normal-20191114-de0849f6-l6vx   <none>           <none>
search-one-7c54ff8bb4-rhc88   2/2     Running   0          14h   10.226.11.69   gke-delivery-platform-normal-20191114-4e7329f7-plhb   <none>           <none>
search-one-7c54ff8bb4-s9kgd   2/2     Running   0          14h   10.226.4.7     gke-delivery-platform-normal-20191114-de0849f6-mrl2   <none>           <none>
                                                                                                                                                             
searchone git/master  
❯ k -n searchone-consumer get pods -o wide
NAME                   READY   STATUS    RESTARTS   AGE   IP            NODE                                                  NOMINATED NODE   READINESS GATES
searchone-consumer-0   2/2     Running   0          38h   10.226.5.7    gke-delivery-platform-normal-20191114-4e7329f7-nfv6   <none>           <none>
searchone-consumer-1   2/2     Running   0          17h   10.226.3.25   gke-delivery-platform-normal-20191114-6b042e4d-wpq2   <none>           <none>
```
🤷‍♂ 

**Expected behavior**
Balanced load

**Steps to reproduce the bug**
Unknown

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.4.2

**How was Istio installed?**
Helm

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

**Comment by Stono** [comment]
I grabbed all of the `/stats/prometheus` for `searchone-consumer-0` and `searchone-consumer-1` whilst it was currently imbalanced to see if there is anything you can spot
[istio.tar.gz](https://github.com/istio/istio/files/4044847/istio.tar.gz)

Things that stick out to me:

`envoy_cluster_lb_healthy_panic{cluster_name="outbound|80||app.search-one.svc.cluster.local"} 17135` in one but `envoy_cluster_lb_healthy_panic{cluster_name="outbound|80||app.search-one.svc.cluster.local"} 0` in the other

**Comment by hzxuzhonghu** [comment]
Is this caused by long-running connections?

**Comment by Stono** [comment]
I considered that, and restarted them (and in doing so removed outlierDetection as a test) and saw the same behaviour, so no.

**Comment by lambdai** [comment]
@Stono Is it possible cpu load high is the cause of high active cx, **not** the consequence?

cx_active is not a good metric to reason about the load balancer unless it is load-based LB

It's possible that the cx_active is because high response(due to app) but equal number of incoming request(due to RR or random LB).

**Comment by Stono** [comment]
Hey @lambdai - i'm not sure i follow.  I can't understand how 1 instance of 3 would (consistently) be more than double the others.  They're all processing the same incoming requests (just distributed for load)

**Comment by Stono** [comment]
Perhaps this graph helps clarify the problem
<img width="1064" alt="Screenshot 2020-01-15 at 08 07 27" src="https://user-images.githubusercontent.com/1486729/72416220-1666fd80-376e-11ea-95f0-f83239e9ebdf.png">

**Comment by Stono** [comment]
OK so I think I've figured this out and @lambdai was right (thank you), so updating here in case other people see the same problem.

What we're seeing above appears to be a symptom rather than a cause.  The extremely high connection count to one instance of the application, was simply envoy _needing_ to create more connections, because that specific instance of the application was being slow to respond.

I was originally acting under the impression that the weight of the requests were in fact the same - and also being evenly distributed, but after some deeper investigation from the product team it does appears that the messages being processed can vary greatly in their impact - and they've identified one in particular which causes a complete JVM heap overload, causing mass GC throttling, thus CPU cfs throttling, thus very slow responses, therefore the downstream envoy is simply creating more connections as they're needed to maintain the concurrency it's looking for.

**Comment by lambdai** [comment]
Thank you for the update and explantion! @Stono
