### ISSUE TITLE
duplicate content in the wiki doc

### ISSUE THREAD

**Issue by xujinguang** [istio/istio#20051]
https://github.com/istio/istio/wiki/Mixer-Template-Dev-Guide 
End of article，this paragraph is repeated.

> There is currently no support for nested messages, enums, oneof, and repeated.
>
>The type istio.mixer.adapter.model.v1beta1.Value has a special meaning. Use of this type tells Mixer that the associated value can be any of the supported attribute types which are defined by the ValueType enum. The specific type that will be used at runtime depends on the configuration the operator writes. Adapters are told what these types are at configuration time so they can prepare themselves accordingly.

**Comment by hzxuzhonghu** [comment]
Thanks，I can remove it

**Comment by hzxuzhonghu** [comment]
fixed
