### ISSUE TITLE
Perfdashboard: Add configurations for stackdriver metrics

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#20065]
Add new configurations for stackdriver filters

1. Full SD --> Metrics + logs + context graph
2. No Logs --> Metrics + context graph

@richardwxn

**Comment by richardwxn** [comment]
@carolynhu @mandarjog I would add this part

**Comment by mandarjog** [comment]
Great! @richardwxn given the number of (growing) configs now is a great time to spend of extracting a basic framework out of it.
