### ISSUE TITLE
Does istio ingress gateway support for external TLS connection for TCP-based client?

### ISSUE THREAD

**Issue by barryzhounb** [istio/istio#20074]
**Bug description**
Error from server: error when creating "tcpserver-gateway.yaml": admission webhook "pilot.validation.istio.io" denied the request: configuration is invalid: server cannot have TLS settings for non HTTPS/TLS ports

I have a TLS client in outside of OpenShift, then I create a istio ingress gateway and inject key and certificate to istio successfully.

Then I add tls properties into Gateway yaml as following:

``
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: tcpserver-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 6677
      name: tcp
      protocol: TCP
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
    hosts:
    - "*"
``
When I run this yaml file, I got the following errors:
``
Error from server: error when creating "tcpserver-gateway.yaml": admission webhook "pilot.validation.istio.io" denied the request: configuration is invalid: server cannot have TLS settings for non HTTPS/TLS ports
``

In my case, my client is TCP-based traffic, and port is 6677, I can not set TLS configuration successfully.

My question is, does istio ingress gateway support non-HTTP traffic (TCP-based) TLS? If support, what wrong is it in my case? How to fix it?

[ X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
dupe https://github.com/istio/istio/issues/20076
