### ISSUE TITLE
Kube controller metrics are never set, leading to missing metrics

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#20073]
See this line: https://github.com/istio/istio/blob/7bcc6d059ac4d22457c9a7b966dc74e9c127f321/pilot/pkg/serviceregistry/kube/controller/controller.go#L162

Metrics is never set, under any conditions. I assume this is a regression from https://github.com/istio/istio/commit/0a1bfcdb6265bd6dc268a6dc26e10251dd2edcfb but I didn't dig into it too much

**Comment by nmittler** [comment]
@howardjohn yikes good catch ... its a little scary that nothing on CI found this bug. I've sent out the fix.

We should probably start thinking about how to better test metrics going forward.
