### ISSUE TITLE
Errors upgrading 1.4.2=>1.4.3: error retrieving RESTMappings to prune

### ISSUE THREAD

**Issue by xiaozhongliu** [istio/istio#20089]
**Bug description**
Following this guide: https://istio.io/docs/setup/upgrade/istioctl-upgrade/,
same errors occurred when upgrading 1.4.2=>1.4.3 on many components, though the components are upgraded to the new version.
Take one error for example:
```
error: error retrieving RESTMappings to prune: invalid resource extensions/v1beta1, Kind=DaemonSet, Namespaced=true: no matches for kind "DaemonSet" in version "extensions/v1beta1" (repeated 1 times)
```

**Expected behavior**
Istio gets upgraded normally.

**Steps to reproduce the bug**
```
istioctl experimental upgrade
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
➜  ~ istioctl version
client version: 1.4.3
control plane version: 1.4.3
data plane version: 1.4.3 (2 proxies)
➜  ~ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T19:44:19Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
```
# it's 1.4.2 then.
istioctl manifest apply --set profile=demo
```

**Environment where bug was observed (cloud vendor, OS, etc)**
Virtual Machines + Rancher Kubernetes

**Comment by howardjohn** [comment]
@elfinhe is this cosmetic (extra logs) or does this have real impact? The root cause I assume is because this api does not exist on k8s 1.16. We don't even use that in any of the install though so we shouldn't be looking at it at all

**Comment by elfinhe** [comment]
@xiaozhongliu what's `kubectl` version? I see the error message at older version of kubectl: https://github.com/MrHohn/kubernetes/blob/4523ce8f32a13b3331d91b64824f43f22c1caf8b/pkg/kubectl/cmd/apply.go#L310. Because `istioctl` depends on your local `kubectl`, so please try upgrading `kubectl` first.

@howardjohn for istioctl, I'd suggest we also add version check of `kubectl` before we run any command with it.

**Comment by howardjohn** [comment]
it's kubectl 1.13 it's in the original issue

seems like we should be using client-go not exec to kubectl, what do other operators do

**Comment by PeopleRange** [comment]
Same issue for Fresh Install today

GKE: 	
1.16.0-gke.20

Install Command:
./istioctl manifest apply --set profile=sds --set values.gateways.istio-ingressgateway.sds.enabled=true --set values.global.k8sIngress.enabled=true --set values.global.k8sIngress.enableHttps=true --set values.global.k8sIngress.gatewayName=ingressgateway --set cni.enabled=true

Generated manifests do the same.

CLI Output (little bit long, I know some of it says unchanged I re-ran the command to copy the error):

``
./istioctl manifest apply --set profile=sds --set values.gateways.istio-ingressgateway.sds.enabled=true --set values.global.k8sIngress.enabled=true --set values.global.k8sIngress.enableHttps=true --set values.global.k8sIngress.gatewayName=ingressgateway --set cni.enabled=true
- Applying manifest for component Base...
✔ Finished applying manifest for component Base.
- Applying manifest for component Cni...
- Applying manifest for component IngressGateway...
- Applying manifest for component Citadel...
- Applying manifest for component Injector...
- Applying manifest for component Prometheus...
- Applying manifest for component Pilot...
- Applying manifest for component NodeAgent...
- Applying manifest for component Galley...
- Applying manifest for component Policy...
- Applying manifest for component Telemetry...
✘ Finished applying manifest for component Cni.
✘ Finished applying manifest for component NodeAgent.
✘ Finished applying manifest for component Galley.
✘ Finished applying manifest for component Pilot.
✘ Finished applying manifest for component Policy.
✘ Finished applying manifest for component Citadel.
✘ Finished applying manifest for component Prometheus.
✘ Finished applying manifest for component Injector.
✘ Finished applying manifest for component IngressGateway.
✘ Finished applying manifest for component Telemetry.

Component Pilot - manifest apply returned the following errors:
Error: error running kubectl: exit status 1

Error detail:

error: error retrieving RESTMappings to prune: invalid resource extensions/v1beta1, Kind=DaemonSet, Namespaced=true: no matches for kind "DaemonSet" in version "extensions/v1beta1" (repeated 1 times)


serviceaccount/istio-pilot-service-account unchanged
clusterrole.rbac.authorization.k8s.io/istio-pilot-istio-system unchanged
clusterrolebinding.rbac.authorization.k8s.io/istio-pilot-istio-system unchanged
configmap/istio unchanged
configmap/pilot-envoy-config unchanged
deployment.apps/istio-pilot configured
meshpolicy.authentication.istio.io/default unchanged
destinationrule.networking.istio.io/api-server unchanged
destinationrule.networking.istio.io/default unchanged
poddisruptionbudget.policy/istio-pilot unchanged
horizontalpodautoscaler.autoscaling/istio-pilot unchanged
service/istio-pilot unchanged



Component Citadel - manifest apply returned the following errors:
Error: error running kubectl: exit status 1

Error detail:

error: error retrieving RESTMappings to prune: invalid resource extensions/v1beta1, Kind=DaemonSet, Namespaced=true: no matches for kind "DaemonSet" in version "extensions/v1beta1" (repeated 1 times)


serviceaccount/istio-citadel-service-account unchanged
clusterrole.rbac.authorization.k8s.io/istio-citadel-istio-system unchanged
clusterrolebinding.rbac.authorization.k8s.io/istio-citadel-istio-system unchanged
deployment.apps/istio-citadel configured
poddisruptionbudget.policy/istio-citadel unchanged
service/istio-citadel unchanged



Component Policy - manifest apply returned the following errors:
Error: error running kubectl: exit status 1

Error detail:

error: error retrieving RESTMappings to prune: invalid resource extensions/v1beta1, Kind=DaemonSet, Namespaced=true: no matches for kind "DaemonSet" in version "extensions/v1beta1" (repeated 1 times)


serviceaccount/istio-policy-service-account unchanged
clusterrole.rbac.authorization.k8s.io/istio-policy unchanged
clusterrolebinding.rbac.authorization.k8s.io/istio-policy-admin-role-binding-istio-system unchanged
configmap/policy-envoy-config unchanged
deployment.apps/istio-policy configured
destinationrule.networking.istio.io/istio-policy unchanged
poddisruptionbudget.policy/istio-policy unchanged
horizontalpodautoscaler.autoscaling/istio-policy unchanged
service/istio-policy unchanged



Component NodeAgent - manifest apply returned the following errors:
Error: error running kubectl: exit status 1

Error detail:

error: error retrieving RESTMappings to prune: invalid resource extensions/v1beta1, Kind=DaemonSet, Namespaced=true: no matches for kind "DaemonSet" in version "extensions/v1beta1" (repeated 1 times)


serviceaccount/istio-nodeagent-service-account unchanged
clusterrole.rbac.authorization.k8s.io/istio-nodeagent-istio-system unchanged
clusterrolebinding.rbac.authorization.k8s.io/istio-nodeagent-istio-system unchanged
daemonset.apps/istio-nodeagent configured



Component IngressGateway - manifest apply returned the following errors:
Error: error running kubectl: exit status 1

Error detail:

error: error retrieving RESTMappings to prune: invalid resource extensions/v1beta1, Kind=DaemonSet, Namespaced=true: no matches for kind "DaemonSet" in version "extensions/v1beta1" (repeated 1 times)


serviceaccount/istio-ingressgateway-service-account unchanged
deployment.apps/istio-ingressgateway configured
gateway.networking.istio.io/ingressgateway unchanged
gateway.networking.istio.io/istio-autogenerated-k8s-ingress unchanged
sidecar.networking.istio.io/default unchanged
poddisruptionbudget.policy/ingressgateway unchanged
role.rbac.authorization.k8s.io/istio-ingressgateway-sds unchanged
rolebinding.rbac.authorization.k8s.io/istio-ingressgateway-sds unchanged
horizontalpodautoscaler.autoscaling/istio-ingressgateway unchanged
service/istio-ingressgateway unchanged



Component Telemetry - manifest apply returned the following errors:
Error: error running kubectl: exit status 1

Error detail:

error: error retrieving RESTMappings to prune: invalid resource extensions/v1beta1, Kind=DaemonSet, Namespaced=true: no matches for kind "DaemonSet" in version "extensions/v1beta1" (repeated 1 times)


serviceaccount/istio-mixer-service-account unchanged
clusterrole.rbac.authorization.k8s.io/istio-mixer-istio-system unchanged
clusterrolebinding.rbac.authorization.k8s.io/istio-mixer-admin-role-binding-istio-system unchanged
configmap/telemetry-envoy-config unchanged
deployment.apps/istio-telemetry configured
attributemanifest.config.istio.io/istioproxy unchanged
attributemanifest.config.istio.io/kubernetes unchanged
handler.config.istio.io/kubernetesenv unchanged
handler.config.istio.io/prometheus unchanged
instance.config.istio.io/attributes unchanged
instance.config.istio.io/requestcount unchanged
instance.config.istio.io/requestduration unchanged
instance.config.istio.io/requestsize unchanged
instance.config.istio.io/responsesize unchanged
instance.config.istio.io/tcpbytereceived unchanged
instance.config.istio.io/tcpbytesent unchanged
instance.config.istio.io/tcpconnectionsclosed unchanged
instance.config.istio.io/tcpconnectionsopened unchanged
rule.config.istio.io/kubeattrgenrulerule unchanged
rule.config.istio.io/promhttp unchanged
rule.config.istio.io/promtcp unchanged
rule.config.istio.io/promtcpconnectionclosed unchanged
rule.config.istio.io/promtcpconnectionopen unchanged
rule.config.istio.io/tcpkubeattrgenrulerule unchanged
destinationrule.networking.istio.io/istio-telemetry unchanged
poddisruptionbudget.policy/istio-telemetry unchanged
horizontalpodautoscaler.autoscaling/istio-telemetry unchanged
service/istio-telemetry unchanged



Component Injector - manifest apply returned the following errors:
Error: error running kubectl: exit status 1

Error detail:

error: error retrieving RESTMappings to prune: invalid resource extensions/v1beta1, Kind=DaemonSet, Namespaced=true: no matches for kind "DaemonSet" in version "extensions/v1beta1" (repeated 1 times)


serviceaccount/istio-sidecar-injector-service-account unchanged
clusterrole.rbac.authorization.k8s.io/istio-sidecar-injector-istio-system unchanged
clusterrolebinding.rbac.authorization.k8s.io/istio-sidecar-injector-admin-role-binding-istio-system unchanged
configmap/injector-mesh unchanged
configmap/istio-sidecar-injector configured
mutatingwebhookconfiguration.admissionregistration.k8s.io/istio-sidecar-injector configured
deployment.apps/istio-sidecar-injector configured
poddisruptionbudget.policy/istio-sidecar-injector unchanged
service/istio-sidecar-injector unchanged



Component Cni - manifest apply returned the following errors:
Error: error running kubectl: exit status 1

Error detail:

error: error retrieving RESTMappings to prune: invalid resource extensions/v1beta1, Kind=DaemonSet, Namespaced=true: no matches for kind "DaemonSet" in version "extensions/v1beta1" (repeated 1 times)


serviceaccount/istio-cni unchanged
clusterrole.rbac.authorization.k8s.io/istio-cni unchanged
clusterrolebinding.rbac.authorization.k8s.io/istio-cni unchanged
configmap/istio-cni-config unchanged
daemonset.apps/istio-cni-node created



Component Galley - manifest apply returned the following errors:
Error: error running kubectl: exit status 1

Error detail:

error: error retrieving RESTMappings to prune: invalid resource extensions/v1beta1, Kind=DaemonSet, Namespaced=true: no matches for kind "DaemonSet" in version "extensions/v1beta1" (repeated 1 times)


serviceaccount/istio-galley-service-account unchanged
clusterrole.rbac.authorization.k8s.io/istio-galley-istio-system unchanged
clusterrolebinding.rbac.authorization.k8s.io/istio-galley-admin-role-binding-istio-system unchanged
configmap/galley-envoy-config unchanged
configmap/istio-galley-configuration unchanged
configmap/istio-mesh-galley unchanged
deployment.apps/istio-galley configured
poddisruptionbudget.policy/istio-galley unchanged
service/istio-galley unchanged



Component Prometheus - manifest apply returned the following errors:
Error: error running kubectl: exit status 1

Error detail:

error: error retrieving RESTMappings to prune: invalid resource extensions/v1beta1, Kind=DaemonSet, Namespaced=true: no matches for kind "DaemonSet" in version "extensions/v1beta1" (repeated 1 times)


serviceaccount/prometheus unchanged
clusterrole.rbac.authorization.k8s.io/prometheus-istio-system unchanged
clusterrolebinding.rbac.authorization.k8s.io/prometheus-istio-system unchanged
configmap/prometheus unchanged
deployment.apps/prometheus unchanged
service/prometheus unchanged




✘ Errors were logged during apply operation. Please check component installation logs above.

Failed to generate and apply manifests, error: errors were logged during apply operation
``

All Expected Pods etc are running except cni which show 0/0 running.

**Comment by elfinhe** [comment]
hi @PeopleRange, thanks for letting us know. we will fix this by either detecting `kubectl` version or using kube go-client instead. 
As for a short term workaround, try upgrading your local kubectl and then run istioctl.

**Comment by jdomag** [comment]
Hi, 
I'm having the same issue with kubectl 1.16.7 and istioctl 1.5.1
![image](https://user-images.githubusercontent.com/28705876/80185716-16985400-860d-11ea-997a-4640a2511745.png)

Command i used:
`./bin/istioctl manifest apply --set addonComponents.prometheus.enabled=false --set addonComponents.kiali.enabled=true --set addonComponents.tracing.enabled=true`

Error I'm getting:
```
Component IngressGateways - manifest apply returned the following errors:                                                                                                                                                                     
Error: error running kubectl: exit status 1                                                                                                                                                                                                   
                                                                                                                                                                                                                                              
Error detail:

error: error retrieving RESTMappings to prune: invalid resource extensions/v1beta1, Kind=DaemonSet, Namespaced=true: no matches for kind "DaemonSet" in version "extensions/v1beta1" (repeated 1 times)
```
