### ISSUE TITLE
JWKS update for JWT authentication pushes changes to envoy sidecar without actual changes

### ISSUE THREAD

**Issue by justinrsweeney** [istio/istio#20090]
**Bug description**
When the pilots checks jwks uri on an interval, changes are found more frequently than anything is actually changed. The code here: https://github.com/istio/istio/blob/f2222fe2c3c1543cb90562fa03d7887191b37844/pilot/pkg/model/jwks_resolver.go#L397-L399 is checking that the response is exactly the same as the previous response and doesn't account for ordering differences in the JSON response.

This results in pushing changes to the envoy sidecars and killing any connections.

**Expected behavior**
If the key doesn't change from the JWKS response, then the envoy sidecars should not have changes pushed and should not need to be reloaded.

**Steps to reproduce the bug**
1. Setup a service using Istio and JWT authentication for the service (this has been seen specifically with JWT using google service accounts
2. Every 20 minutes you will see the envoy sidecar reload the configuration after the pilot gets and updated JWT public key 

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
Istio:
client version: 1.4.0
control plane version: 1.4.0
data plane version: 1.4.0 (7 proxies)

Kubectl:
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.7", GitCommit:"4683545293d792934a7a7e12f2cc47d20b2dd01b", GitTreeState:"clean", BuildDate:"2019-06-06T01:46:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-gke.14", GitCommit:"56d89863d1033f9668ddd6e1c1aea81cd846ef88", GitTreeState:"clean", BuildDate:"2019-11-07T19:12:22Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}

Helm:
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}

**How was Istio installed?**
Using Helm to install onto a GKE cluster

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

**Comment by yangminzhu** [comment]
Thanks for reporting the issue. What jwks server do you use in this case? It's a little bit weird that it returns the public key in a different order on every request.

**Comment by justinrsweeney** [comment]
No problem, thanks for looking at it. Using a googleapis URL: https://www.googleapis.com/service_accounts/v1/jwk/<service_account>, where the last part is a google service account.

**Comment by yangminzhu** [comment]
I just did a quick test and it turns out the response is very unstable: https://www.googleapis.com/service_accounts/v1/jwk/test-service-account@ymzhu-istio.iam.gserviceaccount.com, each jwt key is a map and the fields in the map could have arbitrary order on each request.

We need to think about how to best improve our handling in Pilot to be more smart about this unstable. One option is to deserialize the string to a JSON object and use some special compare method that ignores the order in the list and map.

cc @liminw @diemtvu

**Comment by yangminzhu** [comment]
Some more background copied from the original report on slack:

> Hi all, we are using Istio in GKE with an application using gRPC. We occasionally use gRPC streaming to stream data from the server to a client and some of these streams can be long running. I’ve tweaked a few settings to get the stream_idle_timeout disabled, but currently it seems like every 20 minutes the envoy sidecars are reloading configs and killing any running streams? Any thoughts on how to avoid that?

**Comment by justinrsweeney** [comment]
I have not used this in Go, but have used a similar one in Java to compare JSON: https://github.com/kinbiko/jsonassert and determine if two JSON strings are semantically equivalent.

**Comment by justinrsweeney** [comment]
I'd like to tackle this issue and I am working on a PR on a fork that should be ready shortly.

**Comment by justinrsweeney** [comment]
I have created this PR for this issue: https://github.com/istio/istio/pull/22394. This is my first attempt at contributing a PR here, I welcome any feedback.

**Comment by justinrsweeney** [comment]
@yangminzhu Looks like the bot closed this. The PR was merged, is there a way to link that to this issue?

**Comment by justinrsweeney** [comment]
@howardjohn Just wanted to check in on the best way to update this issue with the associated PR and mark as resolved or at least not closed. Anything I can do there?

**Comment by howardjohn** [comment]
I don't think there is any official way to link it other than mentioning it in the PR or vise-versa
