### ISSUE TITLE
echo server gets "cannot assign requested address" after making too many requests

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#20093]
I have a test that is failing (in development, not an issue). What happens when it fails is the issue. We use the retryUntilSuccess, and send traffic: https://github.com/istio/istio/blob/a952c41a0921bc0694f238c79f23a020956acb30/tests/integration/pilot/locality/main_test.go#L230

The first few iterations are all "normal" errors. However, eventually the errors change to ` a->fake-eds-external-service-1829332088327486510.com failed sending: failed calling a->'http://a:80/': rpc error: code = Unknown desc = Get http://a.locality-distribute-eds-1-80629.svc.cluster.local:80: dial tcp 10.105.51.196:80: connect: cannot assign requested address:`.

This suggests to me maybe we aren't cleaning things up properly? It also obscures the real error from the test

cc @nmittler 
cc @ramaraochavali I think this is why you saw this on your one PR

**Comment by ramaraochavali** [comment]
@howardjohn Thanks. This makes sense now.

**Comment by hzxuzhonghu** [comment]
Is that the forwarder listens on a fixed port? And the listener does not close properly

**Comment by howardjohn** [comment]
I didn't look too much into it, but the forwarder is not a fixed port. From
what I can tell it is closed properly. I ran `netstat -n` during this time
and it never increased much, but I didn't investigate more beyond that

**Comment by nmittler** [comment]
Is it possible that the forwarder be going down for some reason?

**Comment by howardjohn** [comment]
it was because we never close connections, we do now
