### ISSUE TITLE
Istio install (using istioctl) with sds profile doesn't work 

### ISSUE THREAD

**Issue by balamuru** [istio/istio#20098]
**Bug description**
Istio cannot be installed with the sds profile using istioctl

[ x] Configuration Infrastructure
[ x] Docs
[ x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Successful installation
**Steps to reproduce the bug**
```
istioctl manifest apply --set profile=sds
```
The install will fail with the following error
```
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "pilot.validation.istio.io": Post https://istio-galley.istio-system.svc:443/admitpilot?timeout=30s: dial tcp 10.43.80.21:443: connect: connection refused (repeated 1 times)

```
**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.4.3
**How was Istio installed?**
istioctl
**Environment where bug was observed (cloud vendor, OS, etc)**
rancher
Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive
) by attaching
the dump file to this issue.
[istioctl.log](https://github.com/istio/istio/files/4049073/istioctl.log)
[istio-dump.tar.gz](https://github.com/istio/istio/files/4049080/istio-dump.tar.gz)

**Comment by balamuru** [comment]
I can get the istioctl install to "complete" by turning off validation but some of the pods don't come up because of volume mount issues

```
istioctl manifest apply --set profile=sds --set values.global.configValidation=false 
```

```
vinayb@carbon ~/junk/sds $ kc get po -n istio-system
NAME                                      READY   STATUS              RESTARTS   AGE
istio-citadel-5c7766d4f9-c6gf5            1/1     Running             0          2m32s
istio-galley-5b6c74c5c6-c6pbs             0/2     ContainerCreating   0          2m31s
istio-ingressgateway-598585c8d6-j49g8     0/1     ContainerCreating   0          2m32s
istio-nodeagent-s6s82                     1/1     Running             0          2m32s
istio-pilot-677d766cf7-2blm2              0/2     ContainerCreating   0          2m31s
istio-policy-558fd8d577-9wpwq             0/2     ContainerCreating   0          2m31s
istio-sidecar-injector-75ff97b4d8-dbkjf   1/1     Running             0          2m30s
istio-telemetry-6984b86d8-4p8tm           0/2     ContainerCreating   0          2m32s
prometheus-586d4445c7-wmpt5               1/1     Running             0          2m31s
vinayb@carbon ~/junk/sds $ 
```

```
kc describe po istio-ingressgateway-598585c8d6-j49g8  -n istio-system
.
.
.
.
Events:
  Type     Reason       Age                   From               Message
  ----     ------       ----                  ----               -------
  Normal   Scheduled    5m37s                 default-scheduler  Successfully assigned istio-system/istio-ingressgateway-598585c8d6-j49g8 to carbon
  Warning  FailedMount  81s (x10 over 5m36s)  kubelet, carbon    MountVolume.SetUp failed for volume "istio-token" : failed to fetch token: the server could not find the requested resource
  Warning  FailedMount  80s (x2 over 3m34s)   kubelet, carbon    Unable to mount volumes for pod "istio-ingressgateway-598585c8d6-j49g8_istio-system(bc16e513-3448-11ea-b250-1c4d7021a566)": timeout expired waiting for volumes to attach or mount for pod "istio-system"/"istio-ingressgateway-598585c8d6-j49g8". list of unmounted volumes=[istio-token]. list of unattached volumes=[sdsudspath istio-token ingressgateway-certs ingressgateway-ca-certs istio-ingressgateway-service-account-token-2hds2]
vinayb@carbon ~/junk/sds $ 

```

**Comment by howardjohn** [comment]
See https://istio.io/blog/2019/trustworthy-jwt-sds/, it appears rancher is not configured to support a prerequisite for SDS

**Comment by balamuru** [comment]
Thanks, let me see what I can do. I'll try with plain K8s too.

**Comment by nak3** [comment]
In https://istio.io/blog/2019/trustworthy-jwt-sds/ it mentioned:

> If your vendor does not support trustworthy JWTs, you will need to fall back to the file-mount approach to propagate the workload keys and certificates in Istio 1.3.

But is is possible to use file-mount approach by `istioctl manifest apply` and complete the installation?

**Comment by howardjohn** [comment]
yes, just need to turn off SDS (which is the default)

**Comment by nak3** [comment]
Thank you. Yes turning off SDS worked fine on 1.4.2 and local build from master branch.

But only daily build (I needed to use for https://github.com/istio/istio/issues/17837#issuecomment-575407320)  gets rid of `{{- if .Values.global.sds.enabled }}` and it does not work :cry: 

```
$ istioctl manifest generate --set profile=default --dry-run |less
  ... in pilot's Deployment ...
      - name: istio-token
        projected:
          sources:
          - serviceAccountToken:
              audience: istio-ca
              expirationSeconds: 43200
              path: istio-token
```

I guess that it is by design.

**Comment by howardjohn** [comment]
by the time 1.5 comes out we will support clusters without projected token
mounts, but right now we don't

**Comment by balamuru** [comment]
> Thanks, let me see what I can do. I'll try with plain K8s too.

Works with upstream k8s as long as i add the service-account-issuer and service-account-signing-key-file parms to kube-apiserver.yaml. 

At this point (or in the near future), is sds a recommended means of secrets delivery or is the file mount still the way to go. We have to make a decision at work but I don't see a clear recommendation either way?

Closing the issue for now

**Comment by balamuru** [comment]
Also, glad to report that istio/sds installs correctly with k3s. 


From the documented logs at https://rancher.com/docs/k3s/latest/en/advanced/, I'm guessing the requisite kube-apiserver flags are set

```                  
INFO[2019-01-22T15:16:19.908934479-07:00] Running kube-apiserver --allow-privileged=true --authorization-mode Node,RBAC --service-account-signing-key-file /var/lib/rancher/k3s/server/tls/service.key --service-cluster-ip-range 10.43.0.0/16 --advertise-port 6445 --advertise-address 127.0.0.1 --insecure-port 0 --secure-port 6444 --bind-address 127.0.0.1 --tls-cert-file /var/lib/rancher/k3s/server/tls/localhost.crt --tls-private-key-file /var/lib/rancher/k3s/server/tls/localhost.key --service-account-key-file /var/lib/rancher/k3s/server/tls/service.key --service-account-issuer k3s --api-audiences unknown --basic-auth-file /var/lib/rancher/k3s/server/cred/passwd --kubelet-client-certificate /var/lib/rancher/k3s/server/tls/token-node.crt --kubelet-client-key /var/lib/rancher/k3s/server/tls/token-node.key 


```
