### ISSUE TITLE
define "Istio Authors" (copyright holder) somewhere

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#201]
- [x] Define Istio Authors (copyright holder) somewhere
- [x] Fill up / remove https://github.com/istio/istio/blob/master/OWNERS
- [x] it will probably be a FAQ to know which companies are supporting Istio's development: we can put a list either here or on in https://istio.io/faq/

**Comment by geeknoid** [comment]
I deleted istio/istio/OWNERS. I added an Istio Authors seciton to istio/istio/README.md, and I added a note about authorship to the istio.io FAQ page.
