### ISSUE TITLE
istiocontroller cannot probe 

### ISSUE THREAD

**Issue by softputer** [istio/istio#20105]
When I installed the helloworld-go ksvc, the status of ksvc is IngressNotConfigured

And the Knative networking-istio component said 

"{"level":"error","ts":"2020-01-12T17:06:30.733Z","logger":"istiocontroller.ingress-controller.status-manager","caller":"ingress/status.go:366","msg":"Probing of http://helloworld-go.default.example.com:80/ failed, IP: 192.168.165.5:80, ready: false, error: unexpected status code: want [200], got 503 (depth: 0)","commit":"6b0e5c6","knative.dev/controller":"ingress-controller","stacktrace":"knative.dev/serving/pkg/reconciler/ingress.(*StatusProber).processWorkItem\n\t/home/prow/go/src/knative.dev/serving/pkg/reconciler/ingress/status.go:366\nknative.dev/serving/pkg/reconciler/ingress.(*StatusProber).Start.func1\n\t/home/prow/go/src/knative.dev/serving/pkg/reconciler/ingress/status.go:268"}"

so what is the problem,thx

**Comment by howardjohn** [comment]
I am not sure what any of this means, this seems like a knative issue?
