### ISSUE TITLE
Template field type map<string, string> cannot be set in yaml with map[string, string] attribute directly

### ISSUE THREAD

**Issue by guptasu** [istio/istio#2010]
Currently if template field is of type map<string, string> (example `map<string, string> foo`), operator is expected to write config as 
```
foo:
  x: "some string1"
  y: somestr.attribute | "unknown"
  ...
```

However, the intention of the template developer might be that the field is to be set with a single StringMap attribute. For example: 
```
foo: source.labels
```
We don't support this.

Currently in existing templates we have not had this requirements, but need to eventually provide a mechanism for template developer to express if a `map<string, string>` is going to be a single expression or multiple entries of string -> expressions.

Mixers @jmuk @geeknoid @mandarjog @ozevren @douglas-reid for FYI

**Comment by jmuk** [comment]
From config store point of view, I'm wondering how its `InstanceParams` proto will look like, since those specs are first converted into a proto message. I think `oneof` would be sufficient for this, though.

**Comment by ozevren** [comment]
With the future Mixer plans, does this become stale?

**Comment by anandkumarpatel** [comment]
We have a use case for this. We need to pass all headers to our adapter because we do not know the name of the header value we need to look for during deploy time.

**Comment by sandmman** [comment]
My team would also like to be able to pass all headers and query_params in our adapter. Have there been any updates on this front or workarounds?

**Comment by douglas-reid** [comment]
There have not been any updates on this front. I believe that the proposed re-architecting of Mixer will render this moot for the preferred adapter architecture.

@geeknoid @kyessenov thoughts here?

**Comment by geeknoid** [comment]
Yeah, let's close this.
