### ISSUE TITLE
Operator stable_manifest test is not stable

### ISSUE THREAD

**Issue by morvencao** [istio/istio#20115]
**Bug description**

The operator `stable_manifest` test is not stable, if you check the latest test jobs fro prow dashboard, many of them failed because of `stable_manifest` test. I drag the logs of failed job logs:

```
 apiVersion: rbac.authorization.k8s.io/v1
 kind: ClusterRole
 metadata:
   labels:
-    app: prometheus
+    app: istiocoredns
     release: istio
-  name: prometheus-istio-system
+  name: istiocoredns
 rules:
 - apiGroups:
-  - ""
+  - networking.istio.io
   resources:
-  - nodes
-  - services
-  - endpoints
-  - pods
-  - nodes/proxy
+  - '*'
   verbs:
   - get
-  - list
   - watch
-- apiGroups:
-  - ""
-  resources:
-  - configmaps
-  verbs:
-  - get
-- nonResourceURLs:
-  - /metrics
-  verbs:
-  - get
+  - list
 --- FAIL: TestManifestGenerateOrdered (13.60s)
    --- FAIL: TestManifestGenerateOrdered/stable_manifest (13.60s)
        manifest-generate_test.go:164: stable_manifest: Manifest generation is not producing stable text output.
```

[ ] Configuration Infrastructure
[ ] Docs
[ X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
I am skipping the test as part of https://github.com/istio/istio/issues/20112. istio/istio has a much higher bar of test stability than istio/operator

**Comment by ostromart** [comment]
Fixed in https://github.com/istio/istio/pull/20145.
