### ISSUE TITLE
operator and installer post merge tasks

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#20112]
https://github.com/istio/istio/pull/20106 merges the two repos as is, but we need to hook these together and remove duplication. Below is an incomplete list of action items in random order:

* integrate operator docker build into istio-docker.mk (owner: @howardjohn) https://github.com/istio/istio/pull/20128
* update release builder to not reference these repos (owner: @howardjohn) https://github.com/istio/release-builder/pull/115
* integrate operator build into standard makefile (owner: @howardjohn) https://github.com/istio/istio/pull/20128 
* integrate operator tests into standard makefile (owner: @howardjohn) https://github.com/istio/istio/pull/20128
* integrate operator `gen` target into standard makefile (owner: @ostromart) 
* drop dependency on istio.io/operator, move to the local files (owner: @howardjohn) https://github.com/istio/istio/pull/20128
* Make vfsgen use the local installer files - do NOT copy them into data/, instead use the location in manifests/. Likely will involve copying all of data to a tmp folder to get the right structure for vfsgen. Note: #20128 explicitly disables the go:generate command until this is done, so you will need to add this back (owner: @ostromart) 
* Make sure all installer tests are covered. For the most part I think this is just the helm linter?
* Fix linting - right now manifests/ and operator/ are disabled since they fail lints (owner: @howardjohn) https://github.com/istio/istio/pull/20144 
* `./operator/release/create_release_charts.sh` use proper charts (owner: @ostromart) 
* make `injection_test.go` use manifest/ template instead of legacy helm one
* move operator/cmd under istioctl (owner: @ostromart) 

Please add items to the list as we find them, and possibly link PRs as well

**Comment by dgn** [comment]
We're currently skipping the tests in `operator/pkg/translate` -- I don't see an entry in the list for that yet

**Comment by ostromart** [comment]
afaict all items have finally been addressed, including the skipped test. At least all the issues without separate tracking issues are fixed, so closing this.
