### ISSUE TITLE
Unexpected edge on service graph

### ISSUE THREAD

**Issue by xiaozhongliu** [istio/istio#20119]
**Bug description**
The following idle edge highlighted is unexpected, no calling path for this definitely. Per my testing, no doubt it's always idle.
![image](https://user-images.githubusercontent.com/17674404/72254069-fd5f2f00-363d-11ea-8059-7b835c6d52a3.png)

**Expected behavior**
The edge highlighted should not exist.

**Steps to reproduce the bug**
The [k8s-demo-canary] app is an nginx server with the following conf, it will only visit [k8s-demo-bff-canary] other than [k8s-demo-bff].
```
server {
    listen 80;
    root /app;
    index index.html;
    gzip on;
    gzip_vary on;
    gzip_disable "msie6";
    gzip_min_length 1k;
    gzip_comp_level 2;
    gzip_types text/plain application/javascript application/x-javascript text/css application/xml text/javascript image/jpeg image/gif image/png;

    location /health {
        return 200;
    }

    location /k8s-demo-bff/ {
        proxy_http_version 1.1;
        proxy_pass http://k8s-demo-bff-canary/;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
~ istioctl version --remote
client version: 1.2.7
grafana version:
citadel version: 1.1.8
galley version: 1.1.8
ingressgateway version: 1.1.8
pilot version: 1.1.8
pilot-gateway version:
policy version: 1.1.8
policy-gateway version:
sidecar-injector version: 1.1.8
telemetry version: 1.1.8
telemetry version: 1.1.8
telemetry version: 1.1.8
telemetry version: 1.1.8
telemetry version: 1.1.8
telemetry-gateway version:
kiali version:
prometheus version:

~ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T19:44:19Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-aliyun.1", GitCommit:"01a904e", GitTreeState:"", BuildDate:"2019-02-28T13:54:16Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
Aliyun ACK, Istio Operator

**Environment where bug was observed (cloud vendor, OS, etc)**
Aliyun ACK, CentOS 7

**Comment by hickert33** [comment]
I also have a ghost edge in kiali graph on the bookinfo sample between productpage and ratings (direct) which I've never seen until istio 1.5.1 and we know that productpage does NOT call ratings directly ever. Not sure this helps but might be able to duplicate the issue and thus find the bug.
