### ISSUE TITLE
istio-pilot discovery container consuming huge CPU respurces

### ISSUE THREAD

**Issue by nnadig-ebsco** [istio/istio#20129]
**We are using Istio 1.2.2  and seeing lot of cpu usage by istio-pilot discovery container**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[x ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x ] User Experience
[ x] Developer Infrastructure

**Consume cpu within suggested limits**

**Install Istio and create a multiple namespaces and services  in parallel with mtls enabled**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
(awseks) ➜  ~ istioctl version --remote
client version: 1.4.2
control plane version: 1.2.2
data plane version: 1.2.2 (434 proxies)
**How was Istio installed?**
Helm template with installation options
**Environment where bug was observed (cloud vendor, OS, etc)**
EKS with 1.13 version and EKS 1.14

We are assigning 10 cores (now giving 14 cores) cpu on a m5.4xlarge ec2 instances

**Comment by nnadig-ebsco** [comment]
istio-dump attched:
[istio-dump-20129.zip](https://github.com/istio/istio/files/4055692/istio-dump-20129.zip)

**Comment by nnadig-ebsco** [comment]
[dashboards-pilot.docx](https://github.com/istio/istio/files/4055743/dashboards-pilot.docx)

**Comment by nnadig-ebsco** [comment]
cpu profile:
[pprof.pilot-discovery.localhost:8080.samples.cpu.001.pb.gz](https://github.com/istio/istio/files/4055955/pprof.pilot-discovery.localhost.8080.samples.cpu.001.pb.gz)

**Comment by hzxuzhonghu** [comment]
You should upgrade, there is a known performance issue related to pb Struct marshal/unmarshal
