### ISSUE TITLE
istioctl prune does not remove partially removed components

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#20122]
**Bug description**

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
If you set `components.injection=disabled` or whatever, it will prune everything. But, if you set `istio.enabled`, which removes the injection deployment (but keeps other stuff in the injection folder!) then the injector deployment is not pruned.

cc @elfinhe this impacts upgrade

**Comment by elfinhe** [comment]
hi John, which cmd was used? I tried `--set components.injection=disabled`, but obviously it will return an error.

**Comment by howardjohn** [comment]
Sorry that wasn't the exact command. Try installing `global.istiod.enabled=false` then again with `global.istiod.enabled=true`. You will see the injector deployment sticks around. If you just went straight to `true` it would never have been created

**Comment by howardjohn** [comment]
workaround: https://github.com/istio/istio/pull/20280

**Comment by howardjohn** [comment]
Dropping priority since we have a workaround

**Comment by howardjohn** [comment]
Fixed by setting nmespace correctly
