### ISSUE TITLE
Add a STS token service that allows Envoy to set up gRPC stream using dynamic token

### ISSUE THREAD

**Issue by JimmyCYJ** [istio/istio#20133]
**Describe the feature request**
There is an [OAuth token exchange spec ](https://tools.ietf.org/html/draft-ietf-oauth-token-exchange-16) that specifies security token exchange protocol (STS). 

gRPC has the support for fetching dynamic OAuth2 token via STS [link](https://github.com/grpc/grpc/blob/1326593d3f033899a0eca390e77c72767f5a973b/include/grpcpp/security/credentials_impl.h#L265). This helps Envoy to get dynamic token to set up an gRPC stream. We could implement an STS server which serves token exchange requests and provisions tokens.

**Describe alternatives you've considered**

**Additional context**

**Comment by JimmyCYJ** [comment]
https://github.com/envoyproxy/envoy/pull/9101

**Comment by JimmyCYJ** [comment]
https://github.com/istio/istio/pull/19589

**Comment by JimmyCYJ** [comment]
https://github.com/istio/istio/pull/19752

**Comment by JimmyCYJ** [comment]
https://github.com/istio/istio/pull/19897

**Comment by howardjohn** [comment]
This is done (?)
