### ISSUE TITLE
Installer: Label changes breaks helm upgrade

### ISSUE THREAD

**Issue by bplotnick** [istio/istio#20142]
**Bug description**
Since https://github.com/istio/installer/pull/533 upgrades from 1.3 fail with:

```
Deployment.apps "istio-policy" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"istio":"mixer", "istio-mixer-type":"policy"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```

`LabelSelector`s are immutable per https://github.com/kubernetes/kubernetes/issues/50808 and helm i guess doesn't support changing these immutable fields per https://github.com/helm/helm/issues/7082

**Expected behavior**
I think the main issue is that upgrades between consecutive versions is expected to work. If not, then this should probably be reported as a breaking change with workaround steps.

Ideally this would Just Work, though I think that's a taller order.

**Steps to reproduce the bug**
Install Istio 1.3 using the installer then install Istio 1.4 using the installer

**Comment by bplotnick** [comment]
One option would be to change the name of the deployment as is done here: https://github.com/salesforce/helm-starter-istio/pull/2/files. However, I think this would leave behind old objects that would have to be manually cleaned up.

CC: @howardjohn @ostromart

**Comment by howardjohn** [comment]
@bplotnick that is our plan starting in 1.6, to make every upgrade a completely new deployment, etc

**Comment by bplotnick** [comment]
@howardjohn can you elaborate or link me to an issue? We're sorta stuck here unable to upgrade. We might be able to figure out how to move forward by looking at the plan for 1.6

**Comment by howardjohn** [comment]
https://docs.google.com/document/d/1d1z5PC8wvh9QiR3NesAaPm6w2HnE4-KIfjB7GB-_Wf8/edit#
