### ISSUE TITLE
test regression: codecov test extremely flaky

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#20158]
See https://testgrid.k8s.io/istio_istio_postsubmit#codecov_istio_postsubmit

Root cause likely https://github.com/istio/istio/pull/20104

**Comment by howardjohn** [comment]
This also fails 100% of the time for me locally.. TestEndpointFlipFlops and PushIncremental specifically. Not sure how it works in CI? @ramaraochavali any idea why?

**Comment by ramaraochavali** [comment]
@howardjohn Not sure. Will take a look

**Comment by ramaraochavali** [comment]
@howardjohn Is it possible to get logs for one failure?
