### ISSUE TITLE
Istio APIs stored outside of istio/api repo

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#20177]
Some protos we are using, like security/proto/envoy/config/filter/http/alpn/v2alpha1/config.proto, are stored in istio/istio. This makes it impossible for a dependency to fully read our XDS without taking a dependency on istio/istio. These should be accessible in istio/api, since they are APIs.

**Comment by yxue** [comment]
We have proto in istio/api https://github.com/istio/api/tree/master/envoy/config/filter/http/alpn/v2alpha1

**Comment by howardjohn** [comment]
Oh... Why do we copy it to istio/istio?

**Comment by yxue** [comment]
TBH I don't know. I copied here to follow other filters. I think we can remove the proto files in istio/istio and what we need is the generated file.

**Comment by howardjohn** [comment]
We also have citadel protos, etc in repo @myidpt

**Comment by myidpt** [comment]
Planning to get CSR api migration done in 1.7.

**Comment by howardjohn** [comment]
Can we move the ALPN ones as well? Its impossible to parse the XDS config dump without importing all of istio

**Comment by howardjohn** [comment]
not stale

**Comment by kyessenov** [comment]
That's because we need two versions of the proto (gogo again). So golang version is in istio/istio.
