### ISSUE TITLE
Support first party JWT for platforms that do not have third party JWTs

### ISSUE THREAD

**Issue by lei-tang** [istio/istio#20178]
**Describe the feature request**
Support first party JWT for platforms that do not have third party JWTs (e.g., Kubernetes with versions < 1.13).

**Describe alternatives you've considered**
Istio does not support first party JWT.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
done other than testing
