### ISSUE TITLE
V2 Stackdriver Telemetry: STS call credential support

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#20183]
V2 Stackdriver telemetry is required to support STS for fetching call credentials to support workload Identity.

- [x] 1. Update [Opencensus CPP](https://github.com/census-instrumentation/opencensus-cpp/issues/429) to support STS for SD tracing and metrics
- [x] 2. Update upstream Envoy to use STS SD Tracing
- [x] 3. Update istio-proxy SD metrics extension to use STS SD metrics.
- [x] 4. Update Istio-proxy SD logging and context graph extension to pass thru Envoy STS call credentials. 
- [ ] 5. Update istio integration tests using reference [PR](https://github.com/istio/istio/pull/20173)

**Comment by mandarjog** [comment]
@JimmyCYJ

**Comment by JimmyCYJ** [comment]
Thanks @mandarjog 
cc @liminw

**Comment by mandarjog** [comment]
These changes also need to be backported to proxy 1.4

**Comment by kyessenov** [comment]
Xref: https://github.com/istio/proxy/pull/2638

**Comment by bianpengyuan** [comment]
https://github.com/istio/istio/pull/20595

**Comment by mandarjog** [comment]
merged: https://github.com/istio/proxy/pull/2638  STS SD changes in master.
