### ISSUE TITLE
istio/tools: perf istio release commit_sha does not match istio/istio repo

### ISSUE THREAD

**Issue by carolynhu** [istio/istio#20185]
@richardwxn 
For our perf pipeline, we get the github sha: https://github.com/istio/tools/blob/master/perf/benchmark/run_benchmark_job.sh#L207

which through the url of github.com/istio/istio/commits/{SHA} , I get 404 error.

**Comment by richardwxn** [comment]
There is some mismatch between the release sha and the tools repo sha, I will create a PR to fix that.
