### ISSUE TITLE
Rare test flake in apiserver source_dynamic_test.go tests (< 0.5% error rate)

### ISSUE THREAD

**Issue by sushicw** [istio/istio#20209]
To reproduce: 
```
go test -c -race ./galley/pkg/config/source/kube/apiserver
stress -p 64 ./apiserver.test
```

Note that rarely (< 0.5% of runs on my machine in the above scenario) there will be a test failure. These are all from various tests in `source_dynamic_test.go`. If you dig deeper into the run error logs, you will see these timeout waiting for expected results, and you'll also see that the underlying issue is that we receive the CRD FullSync event before sending the CRD Add event, triggering a Reset event (which the testing doesn't handle).   

See https://github.com/istio/istio/issues/20072 for more context and analysis.

**Comment by howardjohn** [comment]
This is no longer flaky
