### ISSUE TITLE
Pods in same controllers should speak to each others in STRICT mode

### ISSUE THREAD

**Issue by etiennejournet** [istio/istio#20200]
Hello,

I just figured that pods in same controllers (i.e. deployment, sts, daemonset, etc...) can't speak to each other in mtls STRICT Mode.
Why is that ? Databases or kv engines need to speak to each others on their pod address for quorum or replication and that makes them unable to.

Could you clarify ?

Thanks,

**Comment by hzxuzhonghu** [comment]
FYI: https://github.com/istio/istio/pull/19496
`strict mTLS does not work since passthrough cluster is using ORIGIN_DST cluster type, thus we don't have TLS config on client side.`

**Comment by hzxuzhonghu** [comment]
We need to fix it.

**Comment by hzxuzhonghu** [comment]
BTW, I think you are using istio 1.4, this is caused by autoMTLS

**Comment by hzxuzhonghu** [comment]
autoMTLS https://istio.io/docs/tasks/security/authentication/auto-mtls/

Please try to test with #20301
