### ISSUE TITLE
Mongo Proxy added as first filter in filter chain in bookinfo application

### ISSUE THREAD

**Issue by gargnupur** [istio/istio#20203]
**Bug description**
Currently, when you follow task https://istio.io/docs/tasks/observability/metrics/tcp-metrics/ Mongo Proxy is added as first filter in envoy filter chain in bookinfo application. This doesn't seem like the right thing as mongo proxy is a terminal filter .

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by howardjohn** [comment]
Attempting to fix this and see `      "details": "Error: non-terminal filter envoy.mongo_proxy is the last filter in a network filter chain."`

Where do you see that its a terminal filter?

**Comment by gargnupur** [comment]
I was told that this is a terminal filter.. didn't see it anywhere..
