### ISSUE TITLE
Support multiple CRDs with the same type internally

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#20208]
Kubernetes is adding a "Gateway" object. We reference our CRDs by the type (eg "Gateway") in about 10000 places in our codebase. We need to update these to reference by GroupVersionKind (or at least GroupKind)

**Comment by incfly** [comment]
The point of this issue is to disambuigiate for us to introduce k8s gateway, essentially?

**Comment by howardjohn** [comment]
Yes. And maybe future conflicts, but that is the immediate one. We cannot support it unless we disambiguate or you run into weird cases where your code randomly has the wrong type (I learned the hard way :slightly_frowning_face: )
