### ISSUE TITLE
Istio 1.4.3 installation breaks network cluster operator on OCP 4.2

### ISSUE THREAD

**Issue by FilipB** [istio/istio#20202]
After installation of istio 1.4.3 on OCP 4.2 cluster the network cluster operator is in degraded state because of failing readinessProbe for all openshift-sdn pods.

readinessProbe on sdn pods:
```
readinessProbe:
        exec:
          command:
            - test
            - '-f'
            - /etc/cni/net.d/80-openshift-network.conf
```
It's expecting /etc/cni/net.d/80-openshift-network.conf file which is gone after istio installation.
Content of the /etc/cni/net.d/ before istio installation:
```
sh-4.2# ls /etc/cni/net.d
80-openshift-network.conf  80-openshift-network.conflist
```
after istio installation:
```
sh-4.2# ls /etc/cni/net.d/
80-openshift-network.conflist  ZZZ-istio-cni-kubeconfig
```

80-openshift-network.conf file is missing -> readinessProbe is failing -> cluster operator gets into degraded state.

**Expected behavior**
Installation does not break OCP

**Steps to reproduce the bug**

1. `oc adm policy add-scc-to-group anyuid system:serviceaccounts -n istio-system`
2. install istio via:
`istioctl manifest apply --set profile=default --set values.kiali.enabled=false --set values.kiali.tag=latest --set values.tracing.enabled=true --set values.grafana.enabled=true --set values.global.mtls.enabled=false --set values.global.controlPlaneSecurityEnabled=false --set values.gateways.istio-egressgateway.enabled=true --set cni.enabled=true --set cni.components.cni.enabled=true --set cni.components.cni.namespace=kube-system --set values.cni.cniBinDir=/var/lib/cni/bin --set values.cni.cniConfDir=/var/run/multus/cni/net.d --set telemetry.components.telemetry.k8s.resources.requests.memory=100Mi --set telemetry.components.telemetry.k8s.resources.requests.cpu=50m`
3. `oc -n istio-system expose svc/istio-ingressgateway --port=80`

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
./istioctl version --remote
client version: 1.4.3
control plane version: 1.4.3
data plane version: 1.4.3 (21 proxies)

OpenShift Version
    4.2.13
Kubernetes Version
    v1.14.6+a8d983c

**How was Istio installed?**
`istioctl manifest apply --set profile=default --set values.kiali.enabled=false --set values.kiali.tag=latest --set values.tracing.enabled=true --set values.grafana.enabled=true --set values.global.mtls.enabled=false --set values.global.controlPlaneSecurityEnabled=false --set values.gateways.istio-egressgateway.enabled=true --set cni.enabled=true --set cni.components.cni.enabled=true --set cni.components.cni.namespace=kube-system --set values.cni.cniBinDir=/var/lib/cni/bin --set values.cni.cniConfDir=/var/run/multus/cni/net.d --set telemetry.components.telemetry.k8s.resources.requests.memory=100Mi --set telemetry.components.telemetry.k8s.resources.requests.cpu=50m`
**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by luksa** [comment]
The Istio CNI installer pod renames the `.conf` file to `.conflist` because it needs to add a chained CNI plugin to the existing CNI plugin. Chained plugins are not supported in `.conf` files, hence the need to rename. 

The Istio CNI installer can't know if there are any other components referencing the `.conf` file. It thus can't reconfigure the readiness probe. Whoever installs the Istio CNI has to fix the references manually (they could also rename the file to `.conflist` first, fix all references to it, and only then deploy Istio CNI).

Note: in Maistra, we require Multus CNI to be the main CNI plugin in the cluster. This helps avoid the issue described here, as well as other issues due to race conditions when multiple components all try to modify the same CNI config file.

**Comment by FilipB** [comment]
Does it mean that it's just a documentation issue? Anyone following current istio docs will hit this issue.

**Comment by jwendell** [comment]
It's not just the docs. It's *also* the docs. After the PR fixing this gets merged I'll update the docs.

**Comment by FilipB** [comment]
No longer visible on istio 1.5.0
