### ISSUE TITLE
Envoy 1.13 hard deprecations

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#20219]
**ORIGINAL_DST_LB**: ok, https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/cluster.go#L1358

**tls_context**: ok, we never use this

**extension_protocol_options**: ok, we never use this

**use_http2**: ok, we never use this

**allow_origin** regex: ACTION REQUIRED: We ARE using this: https://github.com/istio/istio/blob/48ec8ebe5abbb0982fbc4b8c833ab49786393139/pilot/pkg/networking/core/v1alpha3/route/route.go#L684. Fix: https://github.com/istio/istio/pull/20220

**pattern**, **method**: ok, we never use this

regex_match: ACTION REQUIRED only set if safe regex is disabled. We must make safe regex required. Fixed https://github.com/istio/istio/pull/20221

**value**: ACTION REQUIRED: we are using this https://github.com/istio/istio/blob/48ec8ebe5abbb0982fbc4b8c833ab49786393139/pilot/pkg/networking/core/v1alpha3/route/route.go#L634. Fixed https://github.com/istio/istio/pull/20223

from http_connection_manager.proto: **operation_name**: ok, not used
from trace.proto: **HTTP_JSON_V1**: ok, not used

from string.proto: regex: ACTION REQUIRED. We are using in some places, like https://github.com/istio/istio/blob/e8620edf512fda88c5c89a6edc91b64a43332679/pilot/pkg/security/authz/model/principal.go#L218

**Comment by howardjohn** [comment]
All of these have been fixed except the authz stuff. @yangminzhu are you still working on this? This will block us from updating Envoy

**Comment by yangminzhu** [comment]
@howardjohn Sorry for the delay, I was waiting for the other two XL PRs for the AuthZ merged to minimize the code conflicts for this one, sent out the PR for review https://github.com/istio/istio/pull/20382.

**Comment by howardjohn** [comment]
This is fixed as far as I know. If not, we may find some issues pop up once we import 1.13 and can easily track them down
