### ISSUE TITLE
Add statsInclusion annotation to Gateways for configuring Envoy metrics

### ISSUE THREAD

**Issue by irl-segfault** [istio/istio#20216]
The pod annotations "sidecar.istio.io/statsInclusion[Prefixes|Suffixes]" can be used to configure sidecar Envoys to emit additional metrics beyond those enabled by default.

Summary:
The annotation is not respected when used with Gateways (i.e, hard coded into the Deployment template for the Gateway).  Now, these Pod labels do eventually cause the `ISTIO_METAJSON_LABELS` env variable to be set, so we could put this information directly into this env variable.  However, this is brittle and liable to break in future Istio versions.  It would be nice if there was a similar annotation that the Gateway controller could observe and take action on.

Alternatives Considered:
- Fork the Gateway chart and augment the `ISTIO_METAJSON_LABELS`
- Build a layer on top of the `proxyv2` image, augmenting the envoy bootstrap config to directly add this configuration

[X ] Configuration Infrastructure
[X ] Policies and Telemetry

**Comment by howardjohn** [comment]
> ISTIO_METAJSON_LABELS

This is the recommended way for now

I guess we could get them from the downward API though

**Comment by nicktrav** [comment]
@irl-segfault - did you mean `ISTIO_METAJSON_ANNOTATIONS` instead?

**Comment by irl-segfault** [comment]
both work
