### ISSUE TITLE
OCP 4.2 left broken after istio 1.4.3 uninstall

### ISSUE THREAD

**Issue by FilipB** [istio/istio#20238]
**Bug description**
When the istio is removed from OCP 4.2 it leaves the cluster in broken state and newly started pods fail with:
(combined from similar events): Failed create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_registry-puller-89bd55495-8qc6s_registry-puller_b0cf5e01-383d-11ea-93d2-fa163ee5acb3_0(d93218e9cc51c4a6ed1a49829e9983d01ba0071bea5bb55dfadbac9345aa3996): Multus: Err adding pod to network "k8s-pod-network": Multus: error in invoke Conflist add - "k8s-pod-network": error in getting result from AddNetworkList: failed to find plugin "istio-cni" in path [/var/lib/cni/bin /opt/multus/bin]

Problem is fixed when sdn and multus pods are restarted e.g. via:
```
oc delete pods -l app=sdn -n openshift-sdn
oc delete pods -l app=multus -n openshift-multus
```

Also when the istio is installed again the errors go away.

**Expected behavior**
Uninstallation of istio does not break the cluster.

**Steps to reproduce the bug**
1. `oc adm policy add-scc-to-group anyuid system:serviceaccounts -n istio-system`
2. install istio via
`istioctl manifest apply --set profile=default --set values.kiali.enabled=false --set values.kiali.tag=latest --set values.tracing.enabled=true --set values.grafana.enabled=true --set values.global.mtls.enabled=false --set values.global.controlPlaneSecurityEnabled=false --set values.gateways.istio-egressgateway.enabled=true --set cni.enabled=true --set cni.components.cni.enabled=true --set cni.components.cni.namespace=kube-system --set values.cni.cniBinDir=/var/lib/cni/bin --set values.cni.cniConfDir=/var/run/multus/cni/net.d --set telemetry.components.telemetry.k8s.resources.requests.memory=100Mi --set telemetry.components.telemetry.k8s.resources.requests.cpu=50m`
3. `oc -n istio-system expose svc/istio-ingressgateway --port=80`
4. uninstall istio via:
`istioctl manifest generate --set profile=default --set values.kiali.enabled=false  --set values.tracing.enabled=false --set values.grafana.enabled=false --set values.global.mtls.enabled=false --set values.global.controlPlaneSecurityEnabled=false --set values.gateways.istio-egressgateway.enabled=true --set cni.enabled=true --set cni.components.cni.enabled=true --set cni.components.cni.namespace=kube-system --set values.cni.cniBinDir=/var/lib/cni/bin --set values.cni.cniConfDir=/var/run/multus/cni/net.d --set telemetry.components.telemetry.k8s.resources.requests.memory=100Mi --set telemetry.components.telemetry.k8s.resources.requests.cpu=50m  | kubectl delete -f -`

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
./istioctl version --remote
client version: 1.4.3
control plane version: 1.4.3
data plane version: 1.4.3 (1 proxies)

OpenShift Version
4.2.13
Kubernetes Version
v1.14.6+a8d983c

**How was Istio installed?**
`istioctl manifest apply --set profile=default --set values.kiali.enabled=false --set values.kiali.tag=latest --set values.tracing.enabled=true --set values.grafana.enabled=true --set values.global.mtls.enabled=false --set values.global.controlPlaneSecurityEnabled=false --set values.gateways.istio-egressgateway.enabled=true --set cni.enabled=true --set cni.components.cni.enabled=true --set cni.components.cni.namespace=kube-system --set values.cni.cniBinDir=/var/lib/cni/bin --set values.cni.cniConfDir=/var/run/multus/cni/net.d --set telemetry.components.telemetry.k8s.resources.requests.memory=100Mi --set telemetry.components.telemetry.k8s.resources.requests.cpu=50m`

**Environment where bug was observed (cloud vendor, OS, etc)**
OpenShift Version
4.2.13
Kubernetes Version
v1.14.6+a8d983c

**Comment by jwendell** [comment]
This looks like another symptom of https://github.com/istio/istio/issues/20202

**Comment by FilipB** [comment]
No longer visible on istio 1.5.0
