### ISSUE TITLE
locality aware routing metrics strange format

### ISSUE THREAD

**Issue by Stono** [istio/istio#20235]
**Bug description**
The format of the locality aware envoy metrics are a bit odd, and make it difficult to work with in prometheus, and doesn't fit the typical model of exposing cardinality in the labels rather than the metric name

As an example, why is this:
```
envoy_cluster_zone_europe_west4_c_europe_west4_a_upstream_rq_time_sum{cluster_name="outbound|80||app.search-one.svc.cluster.local"} 48534298.75
```

Not just a label on the existing metric, like this:
```
envoy_cluster_upstream_rq_time_sum{source_zone="europe-west4-c", destination_zone="europe-west4-a", cluster_name="outbound|80||app.search-one.svc.cluster.local"} 48534298.75
```

**Expected behavior**
Metrics to expose their cardinality in labels, rather than in the metric name.

**Steps to reproduce the bug**
Enable http metrics on envoy

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.4.3

**How was Istio installed?**
Helm

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE 1.15

**Comment by howardjohn** [comment]
I don't think we have any control over this as it's an envoy metric?

**Comment by brianwolfe** [comment]
Stats are parsed out in the bootstrap configuration to create the tags. An additional field in the bootstrap should work to parse those stats out to tags correctly: https://github.com/istio/istio/blob/master/tools/packaging/common/envoy_bootstrap_v2.json#L21-L24

The zone format is specified here: https://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_stats.html?highlight=stats%20zone#per-service-zone-dynamic-http-statistics

**Comment by howardjohn** [comment]
Ah very cool, I didn't realize that config existed

**Comment by ckcd** [comment]
@Stono

**Comment by ckcd** [comment]
Hi @Stono 

> `envoy_cluster_zone_europe_west4_c_europe_west4_a_upstream_rq_time_sum`

just want to know how to generate this metrics in istio 1.4 ?  I'm using below in `meshConfig` and cannot get this metrics in istio-proxy. I already using `sidecar.istio.io/statsInclusionPrefixes: cluster` to allow generate metrics.

```
    localityLbSetting:
      distribute:
      - from: "cn-shanghai/cn-shanghai-e"
        to:
          "cn-shanghai/cn-shanghai-e": 80
          "cn-shanghai/cn-shanghai-f": 20
      enabled: true
```

**Comment by howardjohn** [comment]
not stale

**Comment by Stono** [comment]
These metrics (in an invalid format) seem to be enabled by default now in 1.7.  Is that intentional?  Does anyone know how to turn them off?

**Comment by douglas-reid** [comment]
not stale.

**Comment by Stono** [comment]
Another example of this is metrics recently introduced with 1.12:

```
# TYPE envoy_server_worker_0_watchdog_mega_miss counter
envoy_server_worker_0_watchdog_mega_miss{} 0

# TYPE envoy_server_worker_0_watchdog_miss counter
envoy_server_worker_0_watchdog_miss{} 0

# TYPE envoy_server_worker_1_watchdog_mega_miss counter
envoy_server_worker_1_watchdog_mega_miss{} 0

# TYPE envoy_server_worker_1_watchdog_miss counter
envoy_server_worker_1_watchdog_miss{} 0
```

Really, they should be `evoy_server_worker_watchdog_miss{worker="1"} 0` etc

**Comment by douglas-reid** [comment]
@Stono argh, we definitely need to fix those. just to clarify do you want the watchdog metrics? Or should `watchdog_mega_miss` and `watchdog_miss` be filtered _in addition to_ us catching the new tags ?

**Comment by douglas-reid** [comment]
@Stono see: https://github.com/envoyproxy/envoy/issues/11767#issuecomment-651388515.
