### ISSUE TITLE
istioctl ServicesReady false negative on clusters without LoadBalancer

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#20253]
https://github.com/istio/istio/blob/2d137b1d5106efb5292f041f8247d4ad76a59639/operator/pkg/manifest/installer.go#L714

This will hang forever if installed on a cluster without a LB like Kind, since LB endpoint is not set. I can see that technically its not "fully ready", but at this point it seems its ready enough... maybe we should remove this check?

**Comment by ostromart** [comment]
Rather than completely removing this check I suggest checking the provider and making it conditional on this being GKE.

**Comment by howardjohn** [comment]
I don't see why we even want to wait for it. Does any other software do this?

It can take quite some time to provision a LB... 

also you can have a LB on kind, or you could not have a LB on kind. Its not tied to provider necesarily.

This code is already removed btw, the issue is stale. So if you do want it maybe we should change this to be "add this back"?
