### ISSUE TITLE
PassthroughCluster doesn't support gRPC

### ISSUE THREAD

**Issue by sisinduku** [istio/istio#20257]
**Bug description**

when a request inside the mesh tries to go outside the mesh by default it will go through PassthroughCluster.  This gRPC request is failing and envoy log says

`HTTP/2" 200 UC "-" "-" 807 0 2 - "-" "grpc-go/1.25.0" "081edcb4-ff81-4a61-9a06-ec610533cfb3" "mygrpc.mydomain.com:80" "192.168.1.123:80" PassthroughCluster - 192.168.1.123:80 172.28.71.32:55762 - -`

It is working properly when disabling Istio proxy. Also, the HTTP request is working properly

**Expected behavior**

PassthroughCluster cluster should support this since it is TCP proxy

**Steps to reproduce the bug**

Make a gRPC request to outside the mesh

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
➜ istioctl version --remote
client version: 1.4.0
citadel version: 1.4.0
galley version: 1.4.0
ingressgateway version: 1.4.0
pilot version: 1.4.0
pilot-ingressgateway version:
sidecar-injector version: 1.4.0
data plane version: 1.4.0 (22 proxies)
```
```
➜ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:41:55Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.7-gke.23", GitCommit:"81c87c699557fed991e292cd328b2129c2f242a2", GitTreeState:"clean", BuildDate:"2019-11-07T19:23:23Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
```
```
➜ helm version
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```

**How was Istio installed?**
Using Helm with Istio multicluster shared control plane (single-network) setup

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE 1.14

**Comment by howardjohn** [comment]
that's really weird because it's just a pure tcp proxy. do other services work just not this grpc one? maybe try another grpc service like https://grpcb.in/?

**Comment by sisinduku** [comment]
We have multiple services which have gRPC call but all of them are
accessing another service inside the mesh except for this one

Accessing gRPC server inside the mesh is working fine

Let me try another gRPC call to outside the mesh

**Comment by howardjohn** [comment]
Were you able to get an example we can reproduce?

**Comment by sisinduku** [comment]
@howardjohn sorry for the late response

I have tested with different service and it was returning the same error in the `PassthroughCluster`

`[2020-05-16T05:28:42.247Z] "POST /proto.CustomerService/AddPerson HTTP/2" 200 UC "-" "-" 19 0 2 - "-" "grpc-python/1.19.0 grpc-c/7.0.0 (linux; chttp2; gold)" "0eb5422b-4fb8-419c-9181-02a19a5ad81a" "othergrpc.example.com:80" "172.28.102.239:80" PassthroughCluster - 172.28.102.239:80 172.28.70.122:50428 - -`

One thing that I notice is that this is failing only if the target port is 80 but when I tested with other port (e.g. 9090) it was working fine. So to reproduce this you can create gRPC server outside the mesh which listen to port 80 and try to deploy a client to access that server inside a mesh with istio-proxy sidecar

**Comment by howardjohn** [comment]
I am fairly sure https://github.com/istio/istio/pull/24712 will fix this. Would be great if you can try it

**Comment by sisinduku** [comment]
Hey, thank you for this! Can you point me to the doc where we can use the Istio setup in the master branch?

**Comment by howardjohn** [comment]
you can download the latest builds from https://github.com/istio/istio/wiki/Dev%20Builds

**Comment by howardjohn** [comment]
Did you get a chance to try this out?

**Comment by howardjohn** [comment]
I have tested this myself so I will assume its resolved. If you did get a chance to test it and see issues still, please reopen,

**Comment by lut777** [comment]
Hi, I also have this problem in istio 1.6.7....
While my scenario is a little different. I send a GRPC stream to a clusterIP with a "wrong destination url". In this case, the "wrong destination url" means url in http is not "service.namespace.svc.cluster.local" or just in short "service.namespace".

So as I understand it, the grpc stream is listened to by the clusterIP listener. But since the domain doesn't match in the router, the stream will be intercepted by allow_any and processed by passthroughputcluster. 
However, an error will occur. According to the client logs, gprc http2 is converted to http1.1. 

For comparison, in the same scenario, there is no problem with using http1.1 to transfer data.

I see that you have fixed the default passthroughcluster grpc transmission problem, can you please tell me if the same problem exists in the passthroughcluster of the router with a allow_any route after listened by a listener on a cluterIP?
