### ISSUE TITLE
The nodeSelector override does not work

### ISSUE THREAD

**Issue by anupash147** [istio/istio#20255]
My helm command goes as
helm install --name net --namespace istio-system  \
    --values=${MYDIR}/values.yaml \
    --set-string global.NodeSelector."node-role\.kubernetes\.io\/system-worker"="yes" \
    istio.io/istio

or

helm install --name net --namespace istio-system  \
    --values=${MYDIR}/values.yaml \
    --set global.NodeSelector."node-role\.kubernetes\.io\/system-worker"="yes" \
    istio.io/istio

this is suppose to add nodeSelector for the node labelled as system-worker but i keep getting the same error for either of the tries

`
Error: release net failed: Deployment in version "v1" cannot be handled as a Deployment: v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Affinity: v1.Affinity.NodeAffinity: v1.NodeAffinity.RequiredDuringSchedulingIgnoredDuringExecution: v1.NodeSelector.NodeSelectorTerms: []v1.NodeSelectorTerm: v1.NodeSelectorTerm.MatchExpressions: []v1.NodeSelectorRequirement: v1.NodeSelectorRequirement.Values: []string: ReadString: expects " or n, but found t, error found in #10 byte of ...|values":[true]}]}]}}|..., bigger context ...|etes.io/system-worker","operator":"In","values":[true]}]}]}}},"containers":[{"command":["/usr/local/|...
`

**Bug description**

**Expected behavior**
Expected behaviour would be to install istio pods to the required node

**Steps to reproduce the bug**
Try out those commands

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istioctl version --remote . -> 1.4.2
kubectl version
`
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:34Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-c0eccc", GitCommit:"c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2", GitTreeState:"clean", BuildDate:"2019-12-22T23:14:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
`

**How was Istio installed?**
AS HELM

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
is this because "yes" means a true Boolean in yaml maybe?

**Comment by anupash147** [comment]
i did try putting a different string as well, it did not work.. Another thing i observed that istio templates have only provision for values; what it means is if I have to use true/boolean the operator used is exists.

**Comment by blhagadorn** [comment]
@anupash147 I tried your helm commands doing a `--debug` and piping it to a file.  Your version gave me this: 
```
global:
  NodeSelector:
    node-role:
      kubernetes:
        io/system-worker: "yes" 
```

However when I did it like this, with escape, `--set-string global.defaultNodeSelector."node-role\.kubernetes\.io/system-worker"="yes"`
I ended up with this:
```  
defaultNodeSelector:
    node-role.kubernetes.io/system-worker: "yes"
```
This seems like a Helm syntax issue.  Let me know if you can get it working using the new syntax, see https://stackoverflow.com/questions/56008728/istio-1-1-4-helm-setup-set-global-defaultnodeselector-sample and for more information.

**Comment by anupash147** [comment]
@blhagadorn : Thank you for the response, i had already tried it and verified. It does not put all the components of Istio helm package on the intended nodes.

**Comment by esnible** [comment]
@morvencao This code was added by you in https://github.com/istio/istio/pull/10123 .  Can you investigate?

**Comment by morvencao** [comment]
@anupash147 
Try to escape the nodeSelector key as @blhagadorn mentioned.
Which component is not scheduled to desired node after you set `defaultNodeSelector`?

**Comment by anupash147** [comment]
@morvencao https://github.com/istio/istio/issues/20255#issuecomment-578831674

**Comment by howardjohn** [comment]
Have you tried using the k8s settings? https://preliminary.istio.io/docs/setup/install/istioctl/#customize-kubernetes-settings

**Comment by anupash147** [comment]
I did not use all but tried the node selector and tolerations only.

**Comment by sayan-sarkar** [comment]
After setting **"servicemesh=true"** as labels on node.  Following worked fine.
istio-install:
>global:
>>defaultNodeSelector:`
>>>servicemesh: '**"true"**'

**Comment by howardjohn** [comment]
I have verified this works:
```
apiVersion: operator.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio
  namespace: istio-operator
spec:
  components:
    pilot:
      k8s:
        nodeSelector:
          foo: bar
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        nodeSelector:
          foo: bar
```
