### ISSUE TITLE
Mixer has an excessive number of disk writes impacting overall performance

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#2025]
@jnativio commented on [Wed Dec 06 2017](https://github.com/istio/issues/issues/134)

**Is this a BUG or FEATURE REQUEST?:**

**Did you review existing epics or issues to identify if this already being worked on?** (please try to add the correct labels and epics):

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version: 0.2.12
kubectl version: v1.7.4-2+eb9172c211dc41
```

**Is Istio Auth enabled or not ?**
istio.yaml was installed.

**What happened**:
I installed istio.yaml 0.2.12  as is initially and then I changed some properties in order to minimize the performance impact on the workload. Even with all known tuning options it was observed a large number of disk writes during the load as well large CPU usage, causing the throughput to be a fraction of what obtained without the mixer.

**What you expected to happen:**
Less performance impact.

**How to reproduce it:**
Drive some workload to a microservices app using Istio with and without the mixer to compare the performance impact. 

**Feature Request:**
N

**Describe the feature:**

**Comment by ldemailly** [comment]
cc @jnativio - I added you to the org so you can create/work on issues directly in istio/istio
(istio/issues/issues is for users)

**Comment by ozevren** [comment]
@jnativio, could you give more detailed repro steps & configuration changes you've made?

**Comment by suryadu** [comment]
Here is the document that has all the details of our Istio Performance with some low level data

[Istio 0.2.12 Performance Measurements.pdf](https://github.com/istio/istio/files/1576491/Istio.0.2.12.Performance.Measurements.pdf)

**Comment by ozevren** [comment]
Great, thank you!

**Comment by mandarjog** [comment]
@suryadu It looks like the graphana dashboard does not record disk IO, only records CPU/memory. Did I miss something?

**Comment by suryadu** [comment]
@mandarjog  We developed a custom grafana dashboard for performance analysis of Istio where we could get the disk IO as well as shown below. The worker node .130 has only Istio components like Mixer and as you can see the disk IO changes from 7 MB/sec to less than 2 MB/sec when we disabled the mixer all together. We have not dissected the 2 containers (mixer and statsd) disk IO from mixer POD which we will next as we discussed in our WG call today.
![image](https://user-images.githubusercontent.com/13684010/34227525-11312fb8-e593-11e7-86b5-91b0f55a68cc.png)

**Comment by geeknoid** [comment]
Has there been follow-up on this problem?

**Comment by ldemailly** [comment]
Yes, and it is also one of the areas for the perf swat team to dig further. @mandarjog is on point for that part.

**Comment by geeknoid** [comment]
@douglas-reid has a PR that introduces sampled output to the stdio logger. Is that part of addressing this issue?

We could also put a buffering layer in front of zap. I believe every log statement in zap is pushed all the way out with no intermediary buffering. Adding just a few ks of buffer would go a long way.
