### ISSUE TITLE
Pilot gets cpu throttled because GOMAXPROCS not set

### ISSUE THREAD

**Issue by fcantournet** [istio/istio#20264]
**Bug description**

Pilot gets throttled by the linux CFS if cpu limits are set on the pod spec.

**Expected behavior**

Pilot doesn't get throttled

**Steps to reproduce the bug**

Run pilot with a cpu limit and add load.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

1.3.5

**How was Istio installed?**

Helm charts (official)

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE 1.14.8

This is due to the fact that the go runtime isn't cgroup aware and doesn't GOMAXPROCS is therefore set to the number of CPU of the nodes and not the limits of the pod.

General good practice to run go in containers on big nodes is to either set the environment variable GOMAXPROCS (to an interger <= cpu.limits in my experience).

Alternatively we could just use https://github.com/uber-go/automaxprocs
I've used this at previous company where all backend services were in go, with good success, eliminating cpu throttling entirely.

**Comment by howardjohn** [comment]
you can add this to the template. there is no universal value that applies to everyone so it is hard to see how we would make a default. note pilot has no cpu limit by default

**Comment by howardjohn** [comment]
the auto proc thing may be useful though, thanks for the link

**Comment by fcantournet** [comment]
I agree, don't see a good general solution from Helm templating either.
I think the best solution to this is in the code via uber's automaxprocs.

There is on-going discussion(IIRC), about making this directly in the go runtime, but it's pretty complicated because you have to parse the cgroups stuff from `runtime` i.e essentially in assembly.

**Comment by howardjohn** [comment]
automaxprocs seems good to me. I would love to see some real numbers from a large Pilot deployment to see if it makes a tangible difference though. I'll try it out myself if I find some time

**Comment by fcantournet** [comment]
I can provide numbers for pilot & telemetry on 1.4.3 soon from our production cluster (~ 1000 pods, 200 services)
What metrics would be most important do you reckon ?
I mean besides system metrics, we mostly look at the convergence time of pilot for evaluating the performance of the control plane.

**Comment by howardjohn** [comment]
I would say Pilot CPU usage (may need to average it over 10+ minutes since its pretty spike), the CPU throttled stat, and convergence time should be good
