### ISSUE TITLE
Downgrade 1.4.3 -> 1.4.2 doesn't work with istioctl experimental upgrade

### ISSUE THREAD

**Issue by paweloczadly** [istio/istio#20263]
**Bug description**

Downgrade 1.4.3 -> 1.4.2 doesn't work with `istio experimental upgrade -f istio-control-plane.yaml`. The output looks as follow:

```
$ ~/istio-1.4.2/bin/istioctl experimental upgrade -f istio-control-plane.yaml
Client - istioctl version: 1.4.0

Error: the target version 1.4.2 is not supported by istioctl 1.4.0, please download istioctl 1.4.2 and run upgrade again
```

According to the official doc: https://istio.io/docs/setup/upgrade/istioctl-upgrade/#downgrade-to-istio-1-4-and-higher-versions-steps, it should work this way. 

It is only possible to downgrade by using `istioctl manifest apply -f istio-control-plane.yaml`.

- [ ] Configuration Infrastructure
- [ ] Docs
- [x] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [x] User Experience
- [ ] Developer Infrastructure

**Expected behavior**

Control plane is downgraded to 1.4.2.

**Steps to reproduce the bug**

* Bootstrap the control plane in v1.4.3
* Download istioctl v1.4.2
* Run `istio experimental upgrade -f istio-control-plane.yaml istio-control-plane.yaml`.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

* istioctl:

```
$ ~/istio-1.4.2/bin/istioctl version
client version: 1.4.2
control plane version: 1.4.3
data plane version: 1.4.3 (70 proxies), 1.4.2 (3 proxies)
```

* Kubernetes:

```
$ kubectl version --short
Client Version: v1.17.0
Server Version: v1.14.9-gke.2
```

**How was Istio installed?**

istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**

* GKE
* Mac OS X

**Comment by elfinhe** [comment]
yes, this is fixed with https://github.com/istio/istio/pull/20187

**Comment by esnible** [comment]
@elfinhe Can we close this?
