### ISSUE TITLE
Performance test Galley `enableAnalysis` on a large cluster

### ISSUE THREAD

**Issue by sushicw** [istio/istio#20275]
To make sure we understand the performance implications of the currently-experimental `enableAnalysis` flag, we should do perf testing on a large cluster with and without it and measure the difference. 

https://github.com/istio/istio/issues/17863 might make this easier.

**Comment by therealmitchconnors** [comment]
Is there a particular metric we would like to test against?  What does success or failure look like?

**Comment by sushicw** [comment]
Good questions! Also, currently open ones. 

I'm not sure what metrics we currently pay attention to, but the ones that come to mind for me are latency (are we slowing Galley's critical-path operation down?) and CPU (are we consuming significant cluster resources?) 

This issue is framed as "understand the impact", so the success criteria is being confident that we know what the impact of this feature is on a large cluster. Depending on the size of the impact, we may or may not have follow up work to mitigate and/or document it.
