### ISSUE TITLE
gencheck issue for operator test output

### ISSUE THREAD

**Issue by richardwxn** [istio/istio#20270]
Not sure whether it is the gen check's issue or the update-goldens logic issue. 

Some of the operator test output files didn't include all the output but with just the objects we are select to compare, but now this would lead to failure of the make check-clean-repo check as it believes all the output of manifest generate command should be written to output.

**Comment by ostromart** [comment]
It's really a update goldens issue. We should stick with having the smallest possible golden output - this means running the generate goldens through the same select/ignore filter we have for comparing the golden outputs.

**Comment by howardjohn** [comment]
I don't think this is applicable now with the gen changes
