### ISSUE TITLE
Make `istioctl x post-install webhook` commands work with istiod

### ISSUE THREAD

**Issue by ayj** [istio/istio#20289]
`istioctl x post-install webhook` assumes the webhooks use key/certs from a k8s secret. Istiod generates its owns certs. istioctl needs to be updated to handle this case.

**Comment by esnible** [comment]
@howardjohn @ostromart @sdake Are these commands still needed?

If so, as part of this work we should add examples to `istioctl x post-install webhook`.

Note that it is very unclear when and how to use this command:

```
$ istioctl x post-install webhook status
...
Error: error when displaying validation webhook configuration: error getting ValidatingWebhookConfiguration istio-galley: validatingwebhookconfigurations.admissionregistration.k8s.io "istio-galley" not found
$ istioctl x post-install webhook disable
Are you sure to delete webhook configuration(s)?
y
Error: error when disabling validation webhook configuration: validatingwebhookconfigurations.admissionregistration.k8s.io "istio-galley" not found
$ istioctl x post-install webhook enable
Error: --namespace <namespace-of-webhook-secret> is required
$ istioctl x post-install webhook enable --namespace istio-system
Error: --validation-path <yaml-file> is required for the validation webhook configuration
```

**Comment by sdake** [comment]
@esnible this was added in commit: 04e758e76bbf4cb00614709672aa5f51614ded4a

Looking at the commit, the PR was https://github.com/istio/istio/pull/17288 and the issue is: https://github.com/istio/istio/issues/17061.

@lei-tang @incfly is this functionality still necessary after the transition to istiod?

Cheers,
-steve

**Comment by sdake** [comment]
@lei-tang @incfly last call before I make the suggestion for removal of these operations.

I have never seen them used not documented, and if we can reduce the footprint of the CLI, we should do so.

Cheers,
-steve

**Comment by lei-tang** [comment]
The documentation for this command and the motivation behind this work can be found at https://istio.io/v1.4/docs/tasks/security/webhook/ and https://istio.io/latest/blog/2019/webhook/. 

In short, the motivation behind this work is to enhance Istio security by letting the operator manage the webhooks, which still applies to istiod. However, the plan for updating this work to stay current with the latest istiod is TBD. Any helps from the community are welcome and appreciated.

**Comment by esnible** [comment]
@lei-tang @sdake `istioctl x post-install webhook` is deprecated in 1.8 and will be removed in 1.9.  Please don't work on it.  `webhook` was the only command in `post-install` and it is likely that `istioctl x post-install` will be removed at the same time.
