### ISSUE TITLE
AddonComponent issues of new operator API

### ISSUE THREAD

**Issue by richardwxn** [istio/istio#20316]
There are couples issues regarding addoncomponents of new operator API, for example: https://github.com/istio/istio/issues/20207, https://github.com/istio/istio/issues/20137.

For the enablement part, part of it would be addressed by: https://github.com/istio/istio/pull/20244. Besides that, look at the code, seems like the AddonComponent is treated as one component and thus has only one helmrender pointing to one charts subdir location, this doesn't seems correct based on existing charts structure. Are we going to move all addon components' templates into one subdir? If not, we should update the codes to handle AddonComponent differently, otherwise it would not work

**Comment by dgn** [comment]
I agree with changing AddonComponents to work like normal Components. Also, it seems that there is not a single component that works with the default helmSubDir, the values must all be taken from the translation yamls

**Comment by dgn** [comment]
I will take a shot at making addonComponents work like normal components

**Comment by dgn** [comment]
See https://github.com/istio/istio/pull/20352
