### ISSUE TITLE
1.5 operator fails to prune resources created by 1.4.x operator

### ISSUE THREAD

**Issue by irisdingbj** [istio/istio#20329]
This is to cover the upgrade path in istio operator.

1. have istio operator and related icp crd and crs installed at version 1.4.3
2. Update istio operator to latest master build and deploy iop crd and cr  to master
3. The old deployment will not be deleted if it is not part of current iop due to annotation changes.

**Comment by timmyers** [comment]
Related to this is trying to delete the ICP CR itself after the above upgrade flow, since it has a finalizer which is not implemented by the new operator image.
