### ISSUE TITLE
Deprecate duplicate bookinfo E2E tests

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#20334]
Motivation for this is to migrate our testing over istioctl, which is easier to do with the new test framework, and reduce number of tests we have with duplicated coverage. All of these can/should/might be covered by istio.io testing

The test currently covers:
* [ ] TestVersionRouting - this is routing based on version. It tests the routing for user "jason". As far as I know we currently have no coverage of this. Could be done by an istio.io test of https://istio.io/docs/tasks/traffic-management/request-routing/
* [ ] TestFaultDelay - tests a fault injection of latency. No existing coverage. Could be covered by https://github.com/istio/istio/issues/18283
* [x] TestVersionMigration tests traffic shifting, which is triple covered: tests/integration/pilot/traffic_shifting_test.go and tests/integration/istioio/trafficmanagement/traffic_shifting_test.go
* [ ] TestDbRoutingMongo - this is just doing standard routing, but specifically to mongodb. I don't think we have existing test of routing to mongo
* [ ] TestDbRoutingMysql - same as mongo
* [x] TestVMExtendsIstio - always skipped, no action needed
* [ ] TestExternalDetailsService - call external https application with tls origination. I think we have this covered but not the tls origination part.

cc @brian-avery

**Comment by brian-avery** [comment]
Created https://github.com/istio/istio/issues/18235 to track the request routing istio.io test

**Comment by howardjohn** [comment]
done
