### ISSUE TITLE
IOP API different levels of override inconsistent

### ISSUE THREAD

**Issue by richardwxn** [istio/istio#20345]
There are different types of customization we can do using IOP: via the operator API, values.yaml pass through or overlay the k8s object directly, and they can be defined in file or using --set override.  

However there are some inconsistency when using them. For example: https://github.com/istio/istio/issues/20153, overriding the k8s settings via values.yaml pass through would have no effect as it would be overrode by k8s spec defined in operator API at the end. 

We may need to better document the priority order and what can be customized or not, or fix the bug if there is issue.

**Comment by ostromart** [comment]
It's a similar case to enablement where user overrides should always take effect, even if they are going through the passthrough values API.

**Comment by richardwxn** [comment]
@ostromart I think we have to fix the k8s override part, as you said, user overrides should always take effect even if they are provided via values API. 

But now it is not the case, now many settings provided via values API would be ignored because they are overrode by the IOP k8s spec defined in the profile at last step.
