### ISSUE TITLE
Standalone Operator Install should include more expected output and completion checks

### ISSUE THREAD

**Issue by esnible** [istio/istio#20358]
This issue is based on Erin Gannon’s deck on friction encountered by new users installing Istio in a cluster that already had applications.
https://youtu.be/nGnKkyltm9w?t=284

Erin's user felt

-steps without ‘expected output’ created guesswork.  Errors printed even when the command was successful.
- There were Manual steps that should be automatic.  The user had to count on his fingers that the services were the same that he saw in the instructions
- No clear confirmation when installation is complete
- User stopped and restarted more than once because unsure when done

Docs were unclear about what to do in the case of omitted services when confirming installation

Note that we have an `istioctl verify-install` that should be able to tell when the install is complete.
Note that the expected output we do show, such as the `kubectl get svc -n istio-system`, only makes sense if the user installed the demo profile.  They won't have lot of these services if they installed a different profile.  We need to help them to understand that.

After the operator has installed and started the control plane if this is a brownfield deployment the operator may need to enable auto-injection on namespaces and restart pods to "install" the sidecars that make up the data plane.  Should the operator instructions include that step?

After the data plane is up they can check their work using istioctl dashboard grafana and friends.
Should we also add a line or two of documentation telling the user what to do once the control plane is active?

**Comment by esnible** [comment]
Can @istio/wg-docs-maintainers suggest someone to work with me on the docs for operator install?

https://preliminary.istio.io/docs/setup/install/standalone-operator/ is confusing because it does not explain the version of Istio that will be installed.  Currently it is installing `gcr.io/istio-testing/pilot:1.4-dev`.

To get the status of an install, I have been doing `kubectl -n istio-operator get IstioControlPlane example-istiocontrolplane -o yaml` which produces YAML output that is hard to understand.  I either need to work with Docs to explain how to do that, or with someone from @istio/wg-environments-maintainers about how to extend istioctl or provide a script to better show the status.

It would also be good if the Istio version (the disk image tag, perhaps) was included in the .Status field of the IstioControlPlane.

**Comment by adammil2000** [comment]
Hi Ed,

We can help with the doc changes, but it seems best to pursue a design change as you suggested first, and use docs as the fallback. That UX has a few rough edges and the docs won't resolve that, if anything they will just highlight it even more.

Will this feature still be experimental when we release 1.5?

Thanks!
