### ISSUE TITLE
Pods of Bookinfo failed to startup

### ISSUE THREAD

**Issue by tiaroy** [istio/istio#20350]
**Bug description**
Install k8s with 3 nodes
install istio with demo profile
install bookInfo with "kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml"
Then, all pods of bookInfo is not startup.
The error message in Replica Sets are below:
"Error creating: Internal error occurred: failed calling webhook "sidecar-injector.istio.io": Post https://istio-sidecar-injector.istio-system.svc:443/inject?timeout=30s: context deadline exceeded"
"Error creating: Internal error occurred: failed calling webhook "sidecar-injector.istio.io": Post https://istio-sidecar-injector.istio-system.svc:443/inject?timeout=30s: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"

Source: replicaset-controller

**Expected behavior**
BookInfo is running normally

**Steps to reproduce the bug**
1.Install k8s with 3 nodes
2.install istio with demo profile
3.install bookInfo with "kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml"

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istioctl version --remote
client version: 1.4.3
control plane version: 1.4.3
data plane version: 1.4.3 (2 proxies)

kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-14T21:04:32Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-14T20:56:50Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

No helm

**How was Istio installed?**
istioctl manifest apply --set profile=demo

**Environment where bug was observed (cloud vendor, OS, etc)**
OS: centos7

**Comment by tiaroy** [comment]
kubectl get all -o wide -n istio-system
NAME                                          READY   STATUS    RESTARTS   AGE   IP            NODE     NOMINATED NODE   READINESS GATES
pod/grafana-6b65874977-8zkq5                  1/1     Running   0          53m   10.244.1.29   knode1   <none>           <none>
pod/istio-citadel-f78ff689-7vxr4              1/1     Running   0          53m   10.244.2.18   knode2   <none>           <none>
pod/istio-egressgateway-7b6b69ddcd-l6f5k      1/1     Running   0          53m   10.244.2.19   knode2   <none>           <none>
pod/istio-galley-69674cb559-pl44l             1/1     Running   0          53m   10.244.1.31   knode1   <none>           <none>
pod/istio-ingressgateway-649f9646d4-q4gbq     1/1     Running   0          53m   10.244.2.24   knode2   <none>           <none>
pod/istio-pilot-7989874664-tl2gp              1/1     Running   0          53m   10.244.2.21   knode2   <none>           <none>
pod/istio-policy-5cdbc47674-92rzz             1/1     Running   0          53m   10.244.2.22   knode2   <none>           <none>
pod/istio-sidecar-injector-7dd87d7989-lzh5g   1/1     Running   0          53m   10.244.1.30   knode1   <none>           <none>
pod/istio-telemetry-6dccd56cf4-rwj44          1/1     Running   0          53m   10.244.2.20   knode2   <none>           <none>
pod/istio-tracing-c66d67cd9-5zh9x             1/1     Running   0          53m   10.244.2.17   knode2   <none>           <none>
pod/kiali-8559969566-mpjr2                    1/1     Running   0          53m   10.244.1.28   knode1   <none>           <none>
pod/prometheus-66c5887c86-vzpsd               1/1     Running   0          53m   10.244.2.23   knode2   <none>           <none>

NAME                             TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                                                                                                                      AGE   SELECTOR
service/grafana                  ClusterIP      10.98.2.64       <none>        3000/TCP                                                                                                                     53m   app=grafana
service/istio-citadel            ClusterIP      10.99.58.112     <none>        8060/TCP,15014/TCP                                                                                                           53m   app=citadel
service/istio-egressgateway      ClusterIP      10.102.84.220    <none>        80/TCP,443/TCP,15443/TCP                                                                                                     53m   app=istio-egressgateway
service/istio-galley             ClusterIP      10.100.101.204   <none>        443/TCP,15014/TCP,9901/TCP,15019/TCP                                                                                         53m   istio=galley
service/istio-ingressgateway     LoadBalancer   10.108.226.232   <pending>     15020:31843/TCP,80:32105/TCP,443:32355/TCP,15029:32417/TCP,15030:30863/TCP,15031:31980/TCP,15032:30599/TCP,15443:31915/TCP   53m   app=istio-ingressgateway
service/istio-pilot              ClusterIP      10.99.111.220    <none>        15010/TCP,15011/TCP,8080/TCP,15014/TCP                                                                                       53m   istio=pilot
service/istio-policy             ClusterIP      10.108.136.84    <none>        9091/TCP,15004/TCP,15014/TCP                                                                                                 53m   istio-mixer-type=policy,istio=mixer
service/istio-sidecar-injector   ClusterIP      10.106.109.106   <none>        443/TCP                                                                                                                      53m   istio=sidecar-injector
service/istio-telemetry          ClusterIP      10.100.48.208    <none>        9091/TCP,15004/TCP,15014/TCP,42422/TCP                                                                                       53m   istio-mixer-type=telemetry,istio=mixer
service/jaeger-agent             ClusterIP      None             <none>        5775/UDP,6831/UDP,6832/UDP                                                                                                   53m   app=jaeger
service/jaeger-collector         ClusterIP      10.98.84.63      <none>        14267/TCP,14268/TCP,14250/TCP                                                                                                53m   app=jaeger
service/jaeger-query             ClusterIP      10.109.71.95     <none>        16686/TCP                                                                                                                    53m   app=jaeger
service/kiali                    ClusterIP      10.104.209.180   <none>        20001/TCP                                                                                                                    53m   app=kiali
service/prometheus               ClusterIP      10.111.133.98    <none>        9090/TCP                                                                                                                     53m   app=prometheus
service/tracing                  ClusterIP      10.111.82.13     <none>        80/TCP                                                                                                                       53m   app=jaeger
service/zipkin                   ClusterIP      10.109.91.200    <none>        9411/TCP                                                                                                                     53m   app=jaeger

NAME                                     READY   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS                 IMAGES                                    SELECTOR
deployment.apps/grafana                  1/1     1            1           53m   grafana                    grafana/grafana:6.4.3                     app=grafana
deployment.apps/istio-citadel            1/1     1            1           53m   citadel                    docker.io/istio/citadel:1.4.3             istio=citadel
deployment.apps/istio-egressgateway      1/1     1            1           53m   istio-proxy                docker.io/istio/proxyv2:1.4.3             app=istio-egressgateway,istio=egressgateway
deployment.apps/istio-galley             1/1     1            1           53m   galley                     docker.io/istio/galley:1.4.3              istio=galley
deployment.apps/istio-ingressgateway     1/1     1            1           53m   istio-proxy                docker.io/istio/proxyv2:1.4.3             app=istio-ingressgateway,istio=ingressgateway
deployment.apps/istio-pilot              1/1     1            1           53m   discovery                  docker.io/istio/pilot:1.4.3               istio=pilot
deployment.apps/istio-policy             1/1     1            1           53m   mixer                      docker.io/istio/mixer:1.4.3               istio=mixer,istio-mixer-type=policy
deployment.apps/istio-sidecar-injector   1/1     1            1           53m   sidecar-injector-webhook   docker.io/istio/sidecar_injector:1.4.3    istio=sidecar-injector
deployment.apps/istio-telemetry          1/1     1            1           53m   mixer                      docker.io/istio/mixer:1.4.3               istio=mixer,istio-mixer-type=telemetry
deployment.apps/istio-tracing            1/1     1            1           53m   jaeger                     docker.io/jaegertracing/all-in-one:1.14   app=jaeger
deployment.apps/kiali                    1/1     1            1           53m   kiali                      quay.io/kiali/kiali:v1.9                  app=kiali
deployment.apps/prometheus               1/1     1            1           53m   prometheus                 docker.io/prom/prometheus:v2.12.0         app=prometheus

NAME                                                DESIRED   CURRENT   READY   AGE   CONTAINERS                 IMAGES                                    SELECTOR
replicaset.apps/grafana-6b65874977                  1         1         1       53m   grafana                    grafana/grafana:6.4.3                     app=grafana,pod-template-hash=6b65874977
replicaset.apps/istio-citadel-f78ff689              1         1         1       53m   citadel                    docker.io/istio/citadel:1.4.3             istio=citadel,pod-template-hash=f78ff689
replicaset.apps/istio-egressgateway-7b6b69ddcd      1         1         1       53m   istio-proxy                docker.io/istio/proxyv2:1.4.3             app=istio-egressgateway,istio=egressgateway,pod-template-hash=7b6b69ddcd
replicaset.apps/istio-galley-69674cb559             1         1         1       53m   galley                     docker.io/istio/galley:1.4.3              istio=galley,pod-template-hash=69674cb559
replicaset.apps/istio-ingressgateway-649f9646d4     1         1         1       53m   istio-proxy                docker.io/istio/proxyv2:1.4.3             app=istio-ingressgateway,istio=ingressgateway,pod-template-hash=649f9646d4
replicaset.apps/istio-pilot-7989874664              1         1         1       53m   discovery                  docker.io/istio/pilot:1.4.3               istio=pilot,pod-template-hash=7989874664
replicaset.apps/istio-policy-5cdbc47674             1         1         1       53m   mixer                      docker.io/istio/mixer:1.4.3               istio=mixer,istio-mixer-type=policy,pod-template-hash=5cdbc47674
replicaset.apps/istio-sidecar-injector-7dd87d7989   1         1         1       53m   sidecar-injector-webhook   docker.io/istio/sidecar_injector:1.4.3    istio=sidecar-injector,pod-template-hash=7dd87d7989
replicaset.apps/istio-telemetry-6dccd56cf4          1         1         1       53m   mixer                      docker.io/istio/mixer:1.4.3               istio=mixer,istio-mixer-type=telemetry,pod-template-hash=6dccd56cf4
replicaset.apps/istio-tracing-c66d67cd9             1         1         1       53m   jaeger                     docker.io/jaegertracing/all-in-one:1.14   app=jaeger,pod-template-hash=c66d67cd9
replicaset.apps/kiali-8559969566                    1         1         1       53m   kiali                      quay.io/kiali/kiali:v1.9                  app=kiali,pod-template-hash=8559969566
replicaset.apps/prometheus-66c5887c86               1         1         1       53m   prometheus                 docker.io/prom/prometheus:v2.12.0         app=prometheus,pod-template-hash=66c5887c86

NAME                                                  REFERENCE                    TARGETS         MINPODS   MAXPODS   REPLICAS   AGE
horizontalpodautoscaler.autoscaling/istio-telemetry   Deployment/istio-telemetry   <unknown>/80%   1         5         1          53m

**Comment by howardjohn** [comment]
This generally indicates a networking issue in your K8s setup. The apiserver needs to access the injector pod. You may have firewall, etc

See https://istio.io/docs/ops/common-problems/injection/

**Comment by howardjohn** [comment]
Closing in favor of https://github.com/istio/istio/issues/21058. Thanks
