### ISSUE TITLE
"istioctl install precheck"

### ISSUE THREAD

**Issue by esnible** [istio/istio#20355]
Currently the command `istioctl verify-install` is used to both see if a Kubernetes cluster without Istio is compatible with Istio (a precheck), and to see if a Kubernetes cluster with Istio is running with the original install configuration.

This is confusing.

This work item tracks the proposal https://docs.google.com/document/d/1x7eFR7e7yw_M1KB0ds5XUQPqai7HeSlnNEUyq8dpFeI/edit which is to break the `verify-install` command into two different commands so that it is easier for users to understand that two different functions are provided.

Although the current code checks Kubernetes version, does it check feature flags and cloud features?  For example, some vendors don't support Istio's SDS profile.  If the user does `istioctl install precheck --profile=sds`, it would be great if they could be told that profile will not install.

**Comment by craigbox** [comment]
It would also be good to have an "istioctl install postcheck", to see that the control plane is running correctly.

**Comment by esnible** [comment]
The 1.6 work will be introducing the command "istioctl experimental precheck", and moving the current Kubernetes cluster compatibility check out of "istioctl verify install".

The new cluster compatibility features in the proposal will not be imlpemented in 1.6.0.
