### ISSUE TITLE
TestTrafficShifting test flakes

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#20359]
This fails really often: https://testgrid.k8s.io/istio_istio#integ-istioio-k8s-tests_istio&width=20

Unfortunately, because this is an istio.io test written in bash, we cannot use our existing deflaking approaches that we use on all of our other tests

@brian-avery @nmittler

**Comment by howardjohn** [comment]
This is the #1 flake, suggest we disable it if no one takes ownership in a few days

**Comment by nmittler** [comment]
@howardjohn  I'm fine with that

@starizard can you take a look?

**Comment by howardjohn** [comment]
Seems like wait did not fix this @brian-avery @therealmitchconnors https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/20573/integ-istioio-k8s-tests_istio/3973

**Comment by brian-avery** [comment]
That seems to be a different failure. 

The VirtualService timed out propagating in the environment. 

 virtualservice.networking.istio.io/productpage created
        virtualservice.networking.istio.io/reviews created
        virtualservice.networking.istio.io/ratings created
        virtualservice.networking.istio.io/details created
        virtualservice.networking.istio.io/reviews configured
        Error: timeout expired before resource VirtualService/default/reviews became effective on all sidecars

The last reviews entry is the one to add the traffic shifting.

**Comment by brian-avery** [comment]
Looking at the test run history, this test has been pretty stable for a while. @howardjohn is this ok to close now?
