### ISSUE TITLE
Telemetry V2: Support request classification

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#20369]
Istio has had a frequent FeatureRequest of using `request.path` as a metric dimension.
Simply using `request.path` directly is not recommended as that dimension has unbounded cardinality.

The more approachable way of adding `request.path` information is to classify the request so as to have bounded cardinality. A regex match, prefix match are ways assign requests to classes and then use the classes as dimensions.

Istio standard telemetry has an attribute called `request.method`. This attribute is set to the grpc method in case of grpc traffic. For plain http, the methods as simple HTTP methods `GET|POST|PUT` etc.

We should be able to populate `request.method` from other specification like OpenAPI Spec. The request pattern should be classified using standard OpenAPISpec.

```yaml
/pets/{id}:
    get:
      description: Returns a user based on a single ID, if the user does not have access to the pet
      operationId: getPetById
```
In the above example we would like the `request.method` to be populated using the `operationId` property.

Classification is used in other places as well, without supporting OpenAPISpec.

---
1. Add prefix classification
2. Add regexs pattern classification
OpenAPI Spec already does this so it is desirable to align with it.

---- 2020-04-01 ---
The list is deliberately narrow from a user's perspective. The first thing we deliver will make adding request.method easy. The underlying filter has more capabilities.

- [x] Create an Wasm/NullSB filter for request classification. It will be loosely based on the Filter API in the design doc.
- [ ] Add `request.method` label to grafana standard metrics.
- [ ] Update Stats filter to accept `request.method` as a filterstate value and populate a new field.
- [ ] Update per service grafana dashboard to add a panel showing request.method if available
- [ ] Add `istioctl x classify_requst --open_api service_spec.yaml` This will output an EnvoyFilter configuration, that *must* be inserted before stats. This should configure the specific attribute `request.method` based on `operationId`
- [ ] Check with Kiali, if and how they want to start using this label
- [ ] Add documentation for `istioctl x classify_request path`
- [ ] Update `istioctl x monitor metrics` to use `request.method`

@douglas-reid @kyessenov @nrjpoddar @jmazzitelli

**Comment by mandarjog** [comment]
@douglas-reid @gargnupur

**Comment by mandarjog** [comment]
@nrjpoddar

**Comment by mandarjog** [comment]
Doc: [https://tinyurl.com/istio-telemetry-api](https://tinyurl.com/istio-telemetry-api)

**Comment by douglas-reid** [comment]
I know that this is implied, but I'd explicitly add the following tasks:
- [ ] robust set of http(s) tests
- [ ] robust set of grpc tests

**Comment by mandarjog** [comment]
Attribute generation plugin: https://github.com/istio/proxy/pull/2801

**Comment by mandarjog** [comment]
Automatic doc generation: https://github.com/istio/proxy/pull/2803

**Comment by mandarjog** [comment]
Still work in progress.

**Comment by jacob-delgado** [comment]
cc @mandarjog What is the status of this? This will have to be in a release post 1.6.0 if you are still working on this feature.

**Comment by mandarjog** [comment]
Not stale.

**Comment by Ignas** [comment]
I would really love to see request.method in grafana metrics, so I could start defining different SLAs for http POST/GET requests.

**Comment by jmazzitelli** [comment]
FYI: Kiali supports this request classifications feature - each classification can be visualized using the new "operation node" - see https://kiali.io/documentation/latest/features/#_graph_operation_nodes

**Comment by bianpengyuan** [comment]
@Ignas If you are only looking for adding HTTP method into the metric, you should already be able to do it via metric customization: https://istio.io/latest/docs/tasks/observability/metrics/customize-metrics/. You can reference https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/security/rbac_filter#condition for available envoy attributes. Also fwiw, in 1.7 release, we are going to have a cleaner way to install metric customization with istioctl: https://preliminary.istio.io/latest/docs/tasks/observability/metrics/customize-metrics/

**Comment by mandarjog** [comment]
In order to take this to beta without adding new functions we need the following.
- [ ] Intgration tests in istio-proxy 
- [ ] integration tests in istio/istio for http.
- [ ] integration tests in istio/istio for grpc.
- [ ] Documented API reference
- [ ] HOW to doc

**Comment by mandarjog** [comment]
@richardwxn are we able to promote this to Beta as is, what is the status?

**Comment by richardwxn** [comment]
@mandarjog I think it is ok to promote it to Beta considering that we have the above items done

**Comment by mandarjog** [comment]
Sounds good! Update the docs to claim beta and add a release note. @douglas-reid anything else we need to do?

**Comment by mandarjog** [comment]
@richardwxn @douglas-reid this is on the list for 1.9, what remains?
I don;t think we will be able to get any openapi spec processed this release.

**Comment by douglas-reid** [comment]
With testing and docs, we can probably call it Beta. I think we were also supposed to have a standalone Beta graduation plan doc, but that doesn't seem necessary to retroactively generate.

Post 1.9, we should start work on a GA graduation doc.

**Comment by howardjohn** [comment]
This is launched
