### ISSUE TITLE
pilotCertProvider=citadel requires trustworthy jwt

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#20389]
To reproduce, install from master with `--set values.global.istiod.enabled=false`. You will see we don't have the citadel ca cert configmap created, blocking ingress from starting up. This is because we exit early here:

https://github.com/istio/istio/blob/57d82c21aa090c9dfe5ac312276524fc95ac5832/pilot/pkg/bootstrap/istio_ca.go#L156

**Comment by incfly** [comment]
How is this resolved as release shiped..?

**Comment by howardjohn** [comment]
I think this has been resolved

**Comment by lei-tang** [comment]
It has been resolved: https://github.com/istio/istio/pull/20401
