### ISSUE TITLE
istioctl should check K8s version (server, kubectl) before applying changes into clusters 

### ISSUE THREAD

**Issue by elfinhe** [istio/istio#20390]
**Describe the feature request**

`istioctl` should check K8s version (server, kubectl) before applying changes into clusters.
Otherwise, users will get a broken Istio install that the manifests are partially applied, e.g., https://github.com/istio/istio/issues/20290, https://github.com/istio/istio/issues/20089.

**Describe alternatives you've considered**
Adding version check logic in `istioctl manifest apply`'s logic.

**Additional context**
https://github.com/istio/istio/issues/20290, https://github.com/istio/istio/issues/20089.

**Comment by howardjohn** [comment]
related: https://github.com/istio/operator/pull/699
