### ISSUE TITLE
"make docker" command fails

### ISSUE THREAD

**Issue by lei-tang** [istio/istio#20400]
**Bug description**
When running "GOOS=linux GOARCH=amd64  make docker", there is an error: 
make: *** No rule to make target /Users/leitang/go/src/istio.io/istio/out/linux_amd64/release/metadata-exchange-filter.wasm', needed by docker.proxyv2'.  Stop.

Based on the PR https://github.com/istio/istio/pull/20259, metadata-exchange-filter.wasm should be generated when the make command is executed. Since the make fails, this generation mechanism does not work.

[ ] Configuration Infrastructure
[ ] Docs
[X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ X] Developer Infrastructure

**Expected behavior**
"make docker" command succeeds

**Steps to reproduce the bug**
1. OS: MacOS. 
2. run "GOOS=linux GOARCH=amd64  make docker".

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**
MacOS.

**Comment by howardjohn** [comment]
@bianpengyuan this is exactly what I was seeing that led to https://github.com/istio/istio/pull/20372

**Comment by bianpengyuan** [comment]
Ack I am working on a fix.
