### ISSUE TITLE
Request rewrite recursively with regex

### ISSUE THREAD

**Issue by vinodloha** [istio/istio#20412]
**Bug description**
with uri regex the /g flag doesn't seem to be working, i need to rewrite part of a URL recursively.

"/(\/digital\/app[\/?])/g"

Above regex Doesn't work and only rewrites the match once, leaving the recurring instances as is.I am using v1alpha3. 

**Expected behavior**
Should be able to match and rewrite all instances in the request.

**Comment by howardjohn** [comment]
We use RE2 which I think does not support this. I could be wrong though, please fact check me :slightly_smiling_face: https://github.com/google/re2/wiki/Syntax

**Comment by howardjohn** [comment]
Closing as this is workign as intended per ^
