### ISSUE TITLE
istio-ify fortio performance application

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#2041]
- [x] deploy fortio in semi permanent cluster with ingress access
- [x] perf.istio.io sub domain with certs
- [ ] mixer rules for user auth - perf WG can modify, anyone can read/browse results

**Comment by ldemailly** [comment]
first 2 are done but not yet

> mixer rules for user auth - perf WG can modify, anyone can read/browse results

need to look into single signon/jwt

**Comment by louiscryan** [comment]
is this stale? if so can you close it

**Comment by ldemailly** [comment]
It's in the same state as mentioned last; which is user authorization through istio isn't not there but will close as the reporting app is running istio in prod since late december
