### ISSUE TITLE
BUILD_WITH_CONTAINER=1 remaining problems

### ISSUE THREAD

**Issue by sdake** [istio/istio#20413]
**Bug description**
BUILD_WITH_CONTAINER=1 has some minor leftover problems from 2019 which need a resolution.

[X] Test and Release
[X] Developer Infrastructure

**Comment by sdake** [comment]
Reserved for list of issues.

**Comment by sdake** [comment]
Reserved for PRs related to list of issues.

**Comment by sdake** [comment]
- [ ] [Fix an error in Mixer test](https://github.com/istio/istio/pull/20315)

**Comment by sdake** [comment]
A different technique for obtaining docker credentials. Worth an experiment. WIll do this today: https://github.com/istio/istio/pull/19322#issuecomment-562325385

**Comment by howardjohn** [comment]
I am fine with `make istioctl-install` not working btw

**Comment by sdake** [comment]
`BUILD_WITH_CONTAINER=1 make test.integration.pilot.local`

some selected failures:

```
2020-01-22T23:54:27.794395Z	info	source	[fs-0] Discovered file: "/tmp/outbound-traffic-policy-allow-any-/TestOutboundTrafficPolicyAllowAny/galley-workdir041743715/config/config_istio_io_attributemanifest_istio-system_istioproxy-1.yaml"
--- FAIL: TestOutboundTrafficPolicyAllowAny (49.09s)
    helper.go:160: 2 errors occurred:
        	* failed waiting for Echo container client.app-7ec001ca-26b7-4ad2-9e79-643bcda47a9c.svc.cluster.local: timeout while waiting (last error: readiness probe failed for pilot agent: Get http://127.0.0.1:39881/healthz/ready: dial tcp 127.0.0.1:39881: connect: connection refused)
        	* failed waiting for Echo container destination.app-7ec001ca-26b7-4ad2-9e79-643bcda47a9c.svc.cluster.local: timeout while waiting (last error: readiness probe failed for pilot agent: Get http://127.0.0.1:45030/healthz/ready: dial tcp 127.0.0.1:45030: connect: connection refused)
        
        
FAIL
FAIL	istio.io/istio/tests/integration/pilot/outboundtrafficpolicy/allowany	49.708s
```

```
2020-01-22T23:53:50.229598Z	info	mcp	Watch(): created watch 21 for istio/networking/v1alpha3/serviceentries from group "default", version "istio/networking/v1alpha3/serviceentries/1"
2020-01-22T23:53:50.245901Z	error	mcp	Error receiving MCP resource: rpc error: code = Canceled desc = context canceled
2020-01-22T23:53:50.246016Z	error	mcp	Error receiving MCP response: rpc error: code = Canceled desc = context canceled
2020-01-22T23:53:50.246060Z	info	transport: loopyWriter.run returning. connection error: desc = "transport is closing"
2020-01-22T23:53:50.246211Z	error	mcp	MCP: connection {addr=127.0.0.1:55564 id=2}: TERMINATED with errors: rpc error: code = Canceled desc = context canceled
```

**Comment by ericvn** [comment]
`BUILD_WITH_CONTAINER=1 make test` on a Mac fails in a number of places with errors like:
```
tcp_filter_test.go:163: Failed to setup test: fork/exec /work/out/darwin_amd64/envoy: exec format error
```
This is due to the tests trying to run **ISTIO_OUT/envoy** which is a Mac binary. 

I am working on a fix so that when running a *test* target in the build container, the binaries will be linux and created in and executed from the linux tree. With this fix, I am still seeing one failure:
```
...
--- FAIL: TestEnvoy (11.03s)
    xds_test.go:114: Failed to setup test: envoy not live. Server State: PRE_INITIALIZING
2020-01-23T20:08:07.889424Z	info	Registry Aggregator terminated
2020-01-23T20:08:07.889609Z	info	Stopped listening on [::]:41411
2020-01-23T20:08:07.889860Z	warn	http: Server closed
FAIL
FAIL	istio.io/istio/pilot/pkg/proxy/envoy/v2	48.515s
...
```

**Comment by sdake** [comment]
> `BUILD_WITH_CONTAINER=1 make test` on a Mac fails in a number of places with errors like:
> 
> ```
> tcp_filter_test.go:163: Failed to setup test: fork/exec /work/out/darwin_amd64/envoy: exec format error
> ```
> 
> This is due to the tests trying to run **ISTIO_OUT/envoy** which is a Mac binary.
> 
> I am working on a fix so that when running a `*test*` target in the build container, the binaries will be linux and created in and executed from the linux tree. With this fix, I am still seeing one failure:
> 
> ```
> ...
> --- FAIL: TestEnvoy (11.03s)
>     xds_test.go:114: Failed to setup test: envoy not live. Server State: PRE_INITIALIZING
> 2020-01-23T20:08:07.889424Z	info	Registry Aggregator terminated
> 2020-01-23T20:08:07.889609Z	info	Stopped listening on [::]:41411
> 2020-01-23T20:08:07.889860Z	warn	http: Server closed
> FAIL
> FAIL	istio.io/istio/pilot/pkg/proxy/envoy/v2	48.515s
> ...
> ```

IMO, this problem would be much simpler if instead of having `make test` run Mac binaries, it ran Linux binaries all the time. Docker for Mac always runs a Linux VM, so `make test` on Mac doesn't make sense to test a darwin binary... (with exception of `istioctl`). I am not sure why the feature creep happened related to building Mac, but it has caused significant confusion within BTR.

Can we define the use cases under which Mac binaries are helpful? `make test` is meant to run on Linux - all the time - atleast when `BUILD_WITH_CONTAINER=1` is set.

Cheers
-steve

**Comment by sdake** [comment]
A new problem: https://github.com/istio/istio/issues/20526

**Comment by sdake** [comment]
`BUILD_WITH_CONTAINER=1 make test.integration.pilot.kube` does not work correctly in a container. Several tests fail. I have included a log.
[typescript.txt](https://github.com/istio/istio/files/4113494/typescript.txt)

**Comment by sdake** [comment]
@nmittler can you take a look at https://github.com/istio/istio/issues/20413#issuecomment-578501622? I am not really clear why all of the connectivity fails. I suspect IPv6 may be involved as there is a bind to [::] which IIRC docker does not support IPv6.

Cheers
-steve

**Comment by nmittler** [comment]
@sdake are you running on linux? If so, you'll need to follow the instructions [here](https://docs.docker.com/network/bridge/#enable-forwarding-from-docker-containers-to-the-outside-world)

**Comment by ericvn** [comment]
Looking at the changes @howardjohn made in #20125 there are even more failures when running locally in a container (more tests run now when doing a `make test`) when one's kube context is set to IBM IKS clusters. At least I'm seeing errors like:
```
        authz_test.go:237: unexpected error: failed to get the k8s service definitions: failed to create the Kubernetes client: invalid configuration: unable to read certificate-authority /Users/ericvn/.bluemix/plugins/container-service/clusters/istio-1-bo52iidw0vqakrhok5o0/ca-wdc04-istio-1.pem for istio-1/bo52iidw0vqakrhok5o0 due to open /Users/ericvn/.bluemix/plugins/container-service/clusters/istio-1-bo52iidw0vqakrhok5o0/ca-wdc04-istio-1.pem: no such file or directory
```
because of no access to the .pem.

**Comment by sdake** [comment]
@ericvn - you mentioned the latest status of the build container is A-OK. Are we good to close this plan out?

If so, feel free to do so, or identify what remains.

Cheers
-steve

**Comment by sdake** [comment]
@nmittler I am running on Linux. With your suggestion and a small PR incoming, I have functional unit tests...

```
sdake@beast-01:~/go/src/istio.io/istio$ make test.integration.pilot.kube
docker.io/sdake/build-tools:master-latest
go test -p 1  ./tests/integration/pilot/... -timeout 30m \
--istio.test.env kube \
 --istio.test.work_dir=/work/out/linux_amd64 --istio.test.hub=docker.io/sdake --istio.test.tag=sdake --istio.test.kube.config=/home/sdake/.kube/config \
2>&1 | tee >(/usr/bin/go-junit-report > /work/out/linux_amd64/junit.xml)
ok  	istio.io/istio/tests/integration/pilot	216.347s
...
```

**Comment by sdake** [comment]
@ericvn removal of https://github.com/istio/istio/pull/20125/files#diff-96d0b051996f0bb52d47eec3edcb27abL415 was correct. There needs to be a corresponding change to counteract that removal however. Thanks for digging us out of this 👍

**Comment by sdake** [comment]
Does `make test` pass? with #23068 :

- [X] Linux + local K8s
- [X] Linux without KUBECONIFG environment see
- [X] Mac with Docker Desktop running K8s
- [X] Mac with Docker Desktop without KUBECONFIG set
- [X] Mac with Docker Desktop with KUBECONFIG to to a K8s instance on IBM Cloud
- [ ] Linux + K8s Instance on GKE
- [ ] Mac + K8s Instance on GKE (@nmittler can you verify these last two?)

**Comment by sdake** [comment]
> @ericvn removal of https://github.com/istio/istio/pull/20125/files#diff-96d0b051996f0bb52d47eec3edcb27abL415 was correct. There needs to be a corresponding change to counteract that removal however. Thanks for digging us out of this 👍

@ericvn I think your solution to KUBECONFIG not being set is fine. It would be nice to generalize this a bit more so all of the individual targets would run correctly - perhaps by setting it in the `Makefile.core.mk` directly rather than under a specific target.
