### ISSUE TITLE
Too difficult to import istio

### ISSUE THREAD

**Issue by erdun** [istio/istio#20419]
Go mod performs poorly with complex dependencies

imported istio with error:

unknown revision v0.0.0
unknown revision src/envoy/tcp/metadata_exchange/config/v0.0.0

**Comment by esnible** [comment]
Do you need all of Istio?  If you are calling Istio you can get away with using just https://github.com/istio/client-go

**Comment by howardjohn** [comment]
This particular import is a hack until https://github.com/istio/istio/issues/20395 is fixed
