### ISSUE TITLE
Update Egress Examples to use Istio Authorization Policy instead of RBAC

### ISSUE THREAD

**Issue by GregHanson** [istio/istio#20410]
**Describe the feature request**
Update Egress Examples on istio.io to use Istio Authorization Policy instead of RBAC where present

[ ] Configuration Infrastructure
[ X ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by manuelbuil** [comment]
Could you clarify where do you see the Istio Authorization Policy being used in the egress examples? I can't find it and I am wondering if perhaps this is an outdated issue
