### ISSUE TITLE
telemetry and policy pods are getting crashloopback in kubernetes 1.16.3

### ISSUE THREAD

**Issue by nik786** [istio/istio#20422]
Kubernetes version
 v1.16.3

CNI

canal

 istio-1.4.3 has been deployed.

telemetry and policy pods are getting crashloopback

**Comment by howardjohn** [comment]
Please add more info... at least logs from the deployments, and how you installed, etc.

Also generally those crashlooping is because of issues in galley, so logs from that is useful as well
