### ISSUE TITLE
Operator: Allow for multiple ingress gateways

### ISSUE THREAD

**Issue by marshallford** [istio/istio#20471]
**Describe the feature request**

Within a single `IstioControlPlane` installation it would be nice to be able to create more than one ingress gateway or to disable/rename the default gateway (`istio-ingressgateway`). In the same vein, the docs are unclear on if the `KubernetesResourcesSpec` entity found on the path `spec.gateways.components:ingressGateway.k8s` is applied just to the default ingress gateway or to all ingress gateways.

Thank you for your time.

**Describe alternatives you've considered**

Use multiple `IstioControlPlane` installations within a single cluster and live with the duplicated services (Pilot, Citadel, etc).

**Additional context**

k8s: `1.17.1`
istio: `1.4.3`

**Comment by howardjohn** [comment]
in 1.5 we are revving the API a bit and adding support for this

**Comment by marshallford** [comment]
Is this functionality still on track for 1.5? I took a look at the prelim docs site and don't see any mention of multiple gateways. Thanks.

**Comment by esnible** [comment]
@howardjohn Milestone for this?

**Comment by howardjohn** [comment]
I thought it was, assigned @ostromart to verify

**Comment by howardjohn** [comment]
Please see https://preliminary.istio.io/docs/setup/install/istioctl/#configure-gateways. Thanks!
