### ISSUE TITLE
telemetry v2 request + response size buckets inverted?

### ISSUE THREAD

**Issue by Stono** [istio/istio#20476]
**Bug description**
Hi, 
I'm testing out telemetry v2 at the moment and it seems like the buckets are inverted when it comes to request and response sizes.

You can see on this graph (the gap in the middle is where i switched over):

<img width="915" alt="Screenshot 2020-01-24 at 09 02 19" src="https://user-images.githubusercontent.com/1486729/73057007-5160e380-3e88-11ea-9fd9-680b1e8795e2.png">

The queries i'm using are:
request-size:
`histogram_quantile(0.95, sum(irate(istio_request_bytes_bucket{reporter="source", destination_app="istio-test-app-1"}[1m])) by (le))`

response-size:
`histogram_quantile(0.95, sum(irate(istio_response_bytes_bucket{reporter="source", destination_app="istio-test-app-1"}[1m])) by (le))`

It's the v1 metrics that are correct (request size is smaller than response)

**Expected behavior**
I would expect these metrics to be the same across these versions. 

**Steps to reproduce the bug**
Switch to v2 metrics

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.4.3

**How was Istio installed?**
Helm

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by douglas-reid** [comment]
Some initial debugging:

1. with v2, i setup a ns with `sleep` and `httpbin`.
1. from `sleep`, i executed: `curl -v httpbin:8000/bytes/9000 -s -o /dev/null`.
1. Request p95: `histogram_quantile(0.95, sum(irate(istio_request_bytes_bucket{reporter="source", destination_app="httpbin"}[1m])) by (le, destination_app))`: `0.47500000000000003`
1. Response p95: `histogram_quantile(0.95, sum(irate(istio_response_bytes_bucket{reporter="source", destination_app="httpbin"}[1m])) by (le, destination_app))`: `9750`

This is as expected. More investigation needed.

**Comment by Stono** [comment]
Been debugging with @douglas-reid and we've actually discovered that this is down to the very different buckets that envoy uses to report sizes vs mixer!  It just manifested as a flipped graph.

It's worth calling out for anyone that comes here post v2 switch, your metric differences are likely just down to the bucketing.  v2 is _not_ a direct replacement for the _v1_ buckets.

**Comment by Stono** [comment]
Please can we reopen this, as I still think something is wrong after rolling this out to another cluster.

I set up a scrape for `sauron-graphql-server` and noticed this:

Why is `sauron-graphql-server` logging metrics with a `destination_app=sauron-graphql-server` and a reporter of `source`?  Surely this should be destination?

```
istio_response_bytes_bucket{RESTARTED_ON="1579705536",app="ingress-nginx-internal",connection_security_policy="unknown",destination_app="sauron-graphql-server",destination_principal="spiffe://cluster.local/ns/sauron-graphql-server/sa/default",destination_service="app.sauron-graphql-server.svc.cluster.local",destination_service_name="app",destination_service_namespace="sauron-graphql-server",destination_version="unknown",destination_workload="sauron-graphql-server",destination_workload_namespace="sauron-graphql-server",instance="10.194.45.14:15090",job="envoy-stats-test",le="25",namespace="ingress-nginx",permissive_response_code="none",permissive_response_policyid="none",pod_name="ingress-nginx-internal-controller-5f4ccfdcf9-j7f9x",pod_template_hash="5f4ccfdcf9",purpose="ingress-nginx",reporter="source",request_protocol="http",response_code="200",response_flags="-",security_istio_io_tlsMode="istio",source_app="ingress-nginx-internal",source_principal="spiffe://cluster.local/ns/ingress-nginx/sa/nginx-ingress-serviceaccount",source_version="8270ab693b",source_workload="ingress-nginx-internal-controller",source_workload_namespace="ingress-nginx",version="8270ab693b"}
```

**Comment by Stono** [comment]
There was actually a problem here.  The request size differences were absolutely to do with the buckets as previously mentioned however the response sizes are broken.  I've raised https://github.com/istio/istio/issues/20536 for this
