### ISSUE TITLE
TestCNIReachability test flakes

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#20487]
https://prow.istio.io/view/gcs/istio-prow/logs/integ-pilot-k8s-tests_istio_postsubmit/1220
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/20458/integ-pilot-k8s-tests_istio/6910
https://prow.istio.io/view/gcs/istio-prow/logs/integ-pilot-k8s-tests_istio_postsubmit/1220

**Comment by howardjohn** [comment]
Another one, but missing init container logs: https://prow.istio.io/view/gcs/istio-prow/logs/integ-pilot-k8s-tests_istio_postsubmit/1253

**Comment by stewartbutler** [comment]
@howardjohn I'll take it if you want to assign it to me

**Comment by howardjohn** [comment]
This is 100% reproducible locally and in CI on k8s 1.14/1.15. Bumping to release blocker to either fix or remove the validation

**Comment by stewartbutler** [comment]
Still WIP, had some other things come up that required my attention. I am working to create a PR to add the repair daemonset stuff to istioctl installations, and will then iterate on this test to get it working.

CC @fpesce

**Comment by howardjohn** [comment]
Still flaking now with the wait, presumably still the race. https://prow.istio.io/view/gcs/istio-prow/logs/integ-k8s-116_istio_postsubmit/1262. Are we turnign on the pod fixer by default in master?

**Comment by howardjohn** [comment]
Fixed, the issue was a mismatch in the container name on validator
