### ISSUE TITLE
Update required stats prefixes to match v2 telemetry

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio#20489]
The current set of required stats inclusion prefixes is:

`cluster_manager,listener_manager,http_mixer_filter,tcp_mixer_filter,server,cluster.xds-grpc`

https://github.com/istio/istio/blob/2afd4c35f11a49eeac6596238abd543663a1594b/pkg/bootstrap/config.go#L50

I believe that we probably want to update this to match the transition to v2 (drop http_mixer_filter and tcp_mixer_filter). This likely involves updating e2e tests, etc. to match.

/cc @mandarjog @kyessenov @bianpengyuan 

[ X ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ X ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by bianpengyuan** [comment]
not stale, we still need to this to track removing mixer stats prefix match.

**Comment by douglas-reid** [comment]
This was just closed by the Mixer removal PR.
