### ISSUE TITLE
Need to stop generating 10k lines for every single manifest-generate test

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#20512]
For example: https://github.com/istio/istio/pull/20461/files#diff-753efa6dce607bb68afe60e259075f5bR1

These tests are WAY too verbose. its so annoying to rebase, review, etc so much changes. We really need to isolate these down. At the very least we don't need to generate the CRDs or something.. or just show the component we care about specifically

**Comment by richardwxn** [comment]
I think this is resolved now after: https://github.com/istio/istio/pull/20622
