### ISSUE TITLE
Mixer - adapter did not close all the scheduled daemons

### ISSUE THREAD

**Issue by rnkhouse** [istio/istio#20513]
**Bug description**

I am getting below error from mixer when I deploy given yaml file.

    2020-01-24T22:49:56.001075Z	info	Publishing 20 events
    2020-01-24T22:49:56.005459Z	info	Built new config.Snapshot: id='7'
    2020-01-24T22:49:56.009938Z	info	Cleaning up handler table, with config ID:6
    2020-01-24T22:50:05.764135Z	info	Publishing 20 events
    2020-01-24T22:50:05.768234Z	info	Built new config.Snapshot: id='8'
    2020-01-24T22:50:05.783462Z	info	Cleaning up handler table, with config ID:7
    2020-01-24T22:50:06.014829Z	error	adapters	adapter did not close all the scheduled daemons	{"adapter": "quotahandler.istio-system"}

**Expected behavior**

It should deploy the configuration successfully.

**Steps to reproduce the bug**

Apply this yaml file:

    apiVersion: config.istio.io/v1alpha2
    kind: handler
    metadata:
      name: quotahandler
      namespace: istio-system
    spec:
      compiledAdapter: memquota
      params:
        quotas:
        - name: requestcountquota.instance.istio-system
          maxAmount: 5
          validDuration: 10s
          # The first matching override is applied.
          # A requestcount instance is checked against override dimensions.
          overrides:
          # The following override applies to 'reviews' regardless
          # of the source.
          #- dimensions:
          #    destination: example-api
          #  maxAmount: 1
          #  validDuration: 5s
          # The following override applies to 'productpage' when
          # the source is a specific ip address.
          - dimensions:
              destination: example-cp
              source: "14.12.09.10"
            maxAmount: 5
            validDuration: 30s
          # The following override applies to 'productpage' regardless
          # of the source.
          - dimensions:
              destination: example-cp
            maxAmount: 1
            validDuration: 30s
    ---
    apiVersion: config.istio.io/v1alpha2
    kind: instance
    metadata:
      name: requestcountquota
      namespace: istio-system
    spec:
      compiledTemplate: quota
      params:
        dimensions:
          source: request.headers["x-forwarded-for"] | "unknown"
          destination: destination.labels["app"] | destination.service.name | "unknown"
          destinationVersion: destination.labels["version"] | "unknown"
    ---
    apiVersion: config.istio.io/v1alpha2
    kind: QuotaSpec
    metadata:
      name: request-count
      namespace: istio-system
    spec:
      rules:
      - quotas:
        - charge: 1
          quota: requestcountquota
    ---
    apiVersion: config.istio.io/v1alpha2
    kind: QuotaSpecBinding
    metadata:
      name: request-count
      namespace: istio-system
    spec:
      quotaSpecs:
      - name: request-count
        namespace: istio-system
      services:
      - name: example-cp
        namespace: default
        #  - service: '*'  # Uncomment this to bind *all* services to request-count
    ---
    apiVersion: config.istio.io/v1alpha2
    kind: rule
    metadata:
      name: quota
      namespace: istio-system
    spec:
      # quota only applies if you are not logged in.
      # match: match(request.headers["cookie"], "user=*") == false
      match: destination.labels["app"] == "example-cp"
      actions:
      - handler: quotahandler
        instances:
        - requestcountquota

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

kubectl:
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4", GitTreeState:"clean", BuildDate:"2019-12-13T18:46:24Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

istio:
1.4.3

**How was Istio installed?**
Helm template

**Environment where bug was observed (cloud vendor, OS, etc)**
AKS

**Comment by av-silva** [comment]
Having the exact same issue today.

**Comment by av-silva** [comment]
@rnkhouse did u made any progress regarding this issue?

**Comment by douglas-reid** [comment]
With Mixer being deprecated and quota functionality being moved over to Envoy features, I think we should close this issue. The message was never truly an error message (it was misleading), and the resolution would involve significant changes to Mixer.
