### ISSUE TITLE
Watch root certificate changes on Galley

### ISSUE THREAD

**Issue by virajrk** [istio/istio#20520]
**Describe the feature request**
Galley is not a rotating root certificate. When the root certificate got rotated, the pilot was waiting for configuration from galley. Connection got refused and the pilot couldn’t sync with galley. This ended up crashing the control plane component pod.

Here is a reference I found in the code that does reload of certificate and key but not root cert.
https://github.com/istio/istio/blob/15e80846d004e2eee4a6a198060be9cdefb1cbd8/pkg/webhooks/validation/server/server.go#L143.

**Describe alternatives you've considered**
To resolve this issue we had to restart galley pods manually so it will honor new root certificate and communication between pilot and galley got restored.

Another option is to put Envoy (istio-proxy sidecar) in front of galley and it will take care of certificate rotation and mTLS.

**Additional context**
We use our internal certificate delivery which delivers workload certificate, root certificate and key. We rotated our root certificate, and the new root certificate got delivered to the galley pod but it was refusing mTLS connection with other istio components like pilot.

**Comment by virajrk** [comment]
CC : @jwebb49 @aattuluri

**Comment by ayj** [comment]
Which version of Istio are you testing? The code you referenced above is in master/1.5 (not released).

The galley server should only watch it's own cert/key. It doesn't use the root cert directly. We do watch the root cert to patch the webhook configuraiton, but that shouldn't affect Pilot-to-Galley mTLS.

**Comment by virajrk** [comment]
@ayj, Thanks for looking into. I am using 1.4.3. 

Sorry for providing wrong link. Try this - 
https://github.com/istio/istio/blob/17f6bfc3d7121ad527c2d617ffc27c758d6a7241/galley/pkg/crd/validation/webhook.go#L206

Let me know if you need more information.

**Comment by virajrk** [comment]
Hello @ayj , More context

We observed mTLS from galley and pilot was not working. I verified connection via openssl from discovery container [pilot pod] to galley svc endpoint. And openssl was failing. Unfortunately I don't have output at this movement. Also can you please let us know where is the root certificate located. I found this but not sure whether this is right place - 
https://github.com/istio/istio/blob/17f6bfc3d7121ad527c2d617ffc27c758d6a7241/galley/pkg/config/processor/transforms/ingress/common.go#L24

openssl s_client -connect istio-galley.istio-system.svc:9001 -key key.pem -cert cert-chain.pem -CAfile root-cert.pem

Added few more logs statements found in galley pod

2020-01-31T08:30:57.557926Z	warn	validation	Cert/Key reload error: tls: private key does not match public key
2020-01-31T08:30:57.559102Z	info	validation	istio-galley validatingwebhookconfiguration (re)loaded: 

Another logs statement found in my notes - 
2019-12-31T23:03:49.953959Z	info	Configuration not synced: first push for [istio/networking/v1alpha3/sidecars istio/rbac/v1alpha1/servicerolebindings istio/networking/v1alpha3/envoyfilters istio/config/v1alpha2/httpapispecs istio/mixer/v1/config/client/quotaspecs istio/authentication/v1alpha1/meshpolicies istio/rbac/v1alpha1/rbacconfigs istio/rbac/v1alpha1/clusterrbacconfigs istio/networking/v1alpha3/virtualservices istio/config/v1alpha2/httpapispecbindings istio/rbac/v1alpha1/serviceroles istio/security/v1beta1/authorizationpolicies istio/networking/v1alpha3/gateways istio/networking/v1alpha3/destinationrules istio/mixer/v1/config/client/quotaspecbindings istio/authentication/v1alpha1/policies istio/networking/v1alpha3/serviceentries] not received

Let us know if you need more information.

**Comment by virajrk** [comment]
Also, any pointers would be appreciated and we are open to contributing once the issue is found.

**Comment by ayj** [comment]
Galley has two different servers: a simple TLS for serving k8s validation webhook requests and a gRPC with mTLS for serving MCP to Pilot. It looks like you're seeing an error in both paths?

The webhook server is in istio/galley/pkg/crd/validation/webhook.go. `reloadKeyCert()` reloads the server's key and cert. It doesn't use the root cert.

The MCP server is in galley/pkg/server/components/processing2.go (~line 152). This periodically polls the local key, cert, and root files watching for changes. The key/cert are updated at runtime through  `tls.Config.GetCertificate()`. The root (ClientCAs) is loaded once at server startup but doesn't seem to be updated. It looks like we might need to use `GetConfigForClient()` to reload the root at runtime.

**Comment by ayj** [comment]
Galley has an envoy sidecar in Istio 1.4 which should be handling the mTLS. The sidecar agent should be handling rotation. Do you see any errors or messages about certs in the istio-proxy container logs?

**Comment by ayj** [comment]
Correction to my previous comment: Galley installed with istioctl has a sidecar. Galley installed with charts does not.

**Comment by howardjohn** [comment]
I think this is no longer applicable on master as Galley has been removed
