### ISSUE TITLE
make gen is broken

### ISSUE THREAD

**Issue by sdake** [istio/istio#20526]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
`make gen` generates errors.

```
sdake@beast-01:~/go/src/istio.io/istio$ export BUILD_WITH_CONTAINER=1
sdake@beast-01:~/go/src/istio.io/istio$ make gen
Building with the build container: gcr.io/istio-testing/build-tools:master-2020-01-18T00-45-13.
Using docker credential directory /home/sdake/.docker.
Using gcr credential directory /home/sdake/.config/gcloud.
Using local Kubernetes configuration /home/sdake/.kube
stat /go/src/istio.io/api/annotation/cmd/gen/main.go: no such file or directory
api/annotation/annotations.gen.go:4: running "go": exit status 1
stat /go/src/istio.io/api/annotation/cmd/gen/main.go: no such file or directory
api/annotation/cmd/gen/main.go:39: running "go": exit status 1
```

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[X] Developer Infrastructure

**Expected behavior**
No errors in the annotation code.

**Steps to reproduce the bug**
clone master @ commit be06f47a22af254ea6adaf17b1659f9af286a3ac
`make gen`

**Comment by sdake** [comment]
This PR broke `make gen` on January 14th: https://github.com/istio/api/commit/7f5243e44d9e866b11cb26652c3120caf76199e3

**Comment by sdake** [comment]
This post-submit job failed: https://storage.googleapis.com/istio-prow/logs/gencheck_api_postsubmit/72/build-log.txt

**Comment by sdake** [comment]
The build is using my $ISTIO/api clone from July:
```
sdake@beast-01:~/go/src/istio.io/istio/api/annotation/cmd/gen$ ls -l
total 8
-rwxr-xr-x 1 sdake sdake 5423 Jul 25  2019 main.go
```

The make system should not be importing code from my local filesystem in this way.

**Comment by howardjohn** [comment]
I am curious how it uses code from your local filesystem, don't we only mount `istio` repo not all of the GOPATH?

**Comment by sdake** [comment]
yup - I admit, I am stumped too.

**Comment by sdake** [comment]
mount line: https://github.com/istio/istio/blob/master/Makefile#L115

and `$(PWD)` is: https://github.com/istio/istio/blob/master/Makefile#L66

but then again, I am not sure how this target works: https://github.com/istio/istio/blob/master/Makefile.overrides.mk#L37...

**Comment by sdake** [comment]
I just double-checked my work.

```
sdake@beast-01:~/go/src/istio.io/istio$ BUILD_WITH_CONTAINER=1 make gen
Building with the build container: docker.io/sdake/build-tools:master-2020-01-25T12-59-00.
Using docker credential directory /home/sdake/.docker.
Using gcr credential directory /home/sdake/.config/gcloud.
Using local Kubernetes configuration /home/sdake/.kube
stat /go/src/istio.io/api/annotation/cmd/gen/main.go: no such file or directory
api/annotation/annotations.gen.go:4: running "go": exit status 1
stat /go/src/istio.io/api/annotation/cmd/gen/main.go: no such file or directory
api/annotation/cmd/gen/main.go:39: running "go": exit status 1
```

Perhaps the credential loading is causing some problem - as $HOME/go is where my source code is stored.

**Comment by sdake** [comment]
this issue is old and the code is morphed significantly. Closing.
