### ISSUE TITLE
Installer: Pilot configmap values unclear and inconsistent

### ISSUE THREAD

**Issue by bplotnick** [istio/istio#20521]
**Bug description**
It is currently hard to distinguish between configuration _for_ Pilot vs configuration served _by_ Pilot lies. In the [istio-control/istio-discovery/values.yaml](https://github.com/istio/installer/blob/master/istio-control/istio-discovery/values.yaml) file, there's a general separation into the `pilot` sections vs the `mixer` and `telemetry` sections. However, even in the `pilot` section, there is a `policy.enabled` value that (incorrectly) [mentions](https://github.com/istio/installer/blob/master/istio-control/istio-discovery/values.yaml#L107) : `Will not define mixerCheckServer and mixerReportServer`. This actually applies to the same values in the `mixer` section. The value in the `pilot` section does not seem used.

More critically, in the `ConfigMap` [template](https://github.com/istio/installer/blob/master/istio-control/istio-discovery/templates/configmap.yaml), there is an intermingling of global config, pilot config, mixer config, and telemetry config. Only pilot config is output to the `values.yaml` [field](https://github.com/istio/installer/blob/master/istio-control/istio-discovery/templates/configmap.yaml#L20).

Even though this is a code hygiene bug, it makes it difficult to understand the ramifications of seemingly small, but large effect changes like this one: https://github.com/istio/installer/pull/596.

One thought for improving the cleanliness is to bring the mixer and telemetry config out to the global namespace. It doesn't appear dependent on anything specific in the pilot config.

**Comment by howardjohn** [comment]
everything you said is 100% right, out values config has grown to be very unwieldy and poorly structured.

We are hoping that as we move towards the istiod architecture a lot of this gets cleaned up organically, but if it doesn't we may need some more action here. Part of the challenge is this is sort of an API but is not always treated as an API, which makes it hard to change (other than adding more and more things)
