### ISSUE TITLE
automator fails gen-check

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#20534]
https://github.com/istio/istio/pull/20533

I didn't look into if gen-check is calling more than gen, or if automated is not properly calling gen

**Comment by clarketm** [comment]
This is what we are running. I will see what it needs to be for istio/istio.

https://github.com/istio/test-infra/blob/2a08caaefdfb9ea37b786fd19ad5fd578f0edbe2/prow/config/jobs/api.yaml#L35

**Comment by howardjohn** [comment]
make gen is what we want, so the bug is in istio/istio.

**Comment by howardjohn** [comment]
Interestingly, I ran `make gen` locally and it updated as expected.. not sure how that happens

**Comment by clarketm** [comment]
ref: https://github.com/istio/test-infra/pull/2310
