### ISSUE TITLE
mtls_first-party-jwt test keep failing after enabling egressgateway

### ISSUE THREAD

**Issue by richardwxn** [istio/istio#20535]
Link to the test: https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/20244/integ-security-k8s-tests_istio/7219.

As background, this PR: https://github.com/istio/istio/pull/20244 tries to address the enablement of components issue(including egress-gateway), and the mtls_first-party-jwt test kept failing with this change because of unavailable egress-gateway. I skipped the test to check in the PR now.

Can you PTAL what's the issue about the egress-gateway? @lei-tang

**Comment by howardjohn** [comment]
I think the problem is egress does not support gateway SDS but we are accidentally enabling it

**Comment by howardjohn** [comment]
We need to either make pilot support egress SDS or make pilot-agent support file mount
