### ISSUE TITLE
istio:istio Investigate removing KUBECONFIG from the Makefile.core.mk

### ISSUE THREAD

**Issue by ericvn** [istio/istio#20563]
**Bug description**

Is is possible to remove the KUBECONFIG variable from the Makefile.core.mak along with the pointed to file? The standard tests should not require a KUBECONFIG while the integration tests have parameters to set which KUBECONFIG to use.

Simply removing the value and file results in failures:
```
go test  -race ./istioctl/...
--- FAIL: TestAuthZConvert (0.90s)
    --- FAIL: TestAuthZConvert/simple (0.06s)
        authz_test.go:237: unexpected error: failed to get the k8s service definitions: failed to create the Kubernetes client: invalid configuration: unable to read certificate-authority /Users/ericvn/.bluemix/plugins/container-service/clusters/istio-1-bo52iidw0vqakrhok5o0/ca-wdc04-istio-1.pem for istio-1/bo52iidw0vqakrhok5o0 due to open /Users/ericvn/.bluemix/plugins/container-service/clusters/istio-1-bo52iidw0vqakrhok5o0/ca-wdc04-istio-1.pem: no such file or directory
    --- FAIL: TestAuthZConvert/wildcard (0.06s)
        authz_test.go:237: unexpected error: failed to get the k8s service definitions: failed to create the Kubernetes client: invalid configuration: unable to read certificate-authority /Users/ericvn/.bluemix/plugins/container-service/clusters/istio-1-bo52iidw0vqakrhok5o0/ca-wdc04-istio-1.pem for istio-1/bo52iidw0vqakrhok5o0 due to open /Users/ericvn/.bluemix/plugins/container-service/clusters/istio-1-bo52iidw0vqakrhok5o0/ca-wdc04-istio-1.pem: no such file or directory
    --- FAIL: TestAuthZConvert/multiple-rules (0.05s)
        authz_test.go:237: unexpected error: failed to get the k8s service definitions: failed to create the Kubernetes client: invalid configuration: unable to read certificate-authority /Users/ericvn/.bluemix/plugins/container-service/clusters/istio-1-bo52i
```
.....

In this scenario I had a local kubecontext set (pointing to an IKS cluster which has a reference to a .pem file) and was running in a build container. The build container could not reference the pem file from inside the container. 

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by sdake** [comment]
On IKS, to reference the pem file correctly according to @kramvan1 - the solution (to be documented upstream in IKS documentation) is:
```
ic ks cluster config -c <cluster> --yaml
```
This should work with the conditional mounts already in the system as the above command consolidates all credentials into one yaml file instead of spreading them around on the filesystem.

**Comment by sdake** [comment]
@eric4545 do your original question, I don't think it is wise to remove `KUBECONFIG` from `Makefile.core.mk`. The ability to support a custom `KUBECONFIG` is valuable. We may be able to execute a shared bind mount for all entries in KUBECONFIG as part of `setup_env.sh`. I will investigate this approach further for viability.

Cheers
-steve
