### ISSUE TITLE
istio-start.sh needs owner/tests

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#20566]
This script often breaks and doesn't keep up with changes. For example, the version has been "1.3.0" in master, when we are on 1.5 now.

**Comment by mkoppanen** [comment]
This script looks broken in 1.4.5 (installed via debian package).

Symptoms look like the script doesn't make it to the line where it would actually start the envoy proxy. I'll debug further in the next days and report back.

**Comment by howardjohn** [comment]
This is now tested in local integ tests
