### ISSUE TITLE
Namespace controller for ca needs leader election

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#20583]
Right now we will write to the same config map for each instance of istiod. This means we will have namespace*replica writes per second, which is likely to blow up large clusters. Note that large clusters often have 100s of istiods and 1000s of namespaces

**Comment by myidpt** [comment]
What's the largest number of Pilot replicas and namespaces so far we see? I agree that leader election is the ultimate solution, but I'm just asking if this is a blocker for 1.5. Note that we do have another blocker that we need to work on - istio agent writing secret into file to support Prometheus.

**Comment by howardjohn** [comment]
I agree its not a release blocker. I have heard of multiple people running 100 pilots + 1000 namespaces. Its "only" 100x worse than citadel (assuming you had 1 citadel), but I think we also have a much faster update rate?

**Comment by myidpt** [comment]
Cool. Thanks John. FYI, Lei is working on https://github.com/istio/istio/pull/20560 right now. We will work on this one after that feature is implemented.

**Comment by howardjohn** [comment]
this is done
