### ISSUE TITLE
1.4 -> 1.5 non-istiod broken by "udpa.type.v1.TypedStruct"

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#20582]
In the istiod upgrade case, we are doing all webhook validation in the new 1.5 Istiod, because we specifically add some workarounds to fix races with Galley. When istiod is disabled, Galley 1.4 will still be doing validation of the 1.5 install config. In particular, the Envoyfilters will fail, since they are using types that are not known to 1.4 Galley. This leads to these errors on upgrade:'

```

Error from server: error when creating "STDIN": admission webhook "pilot.validation.istio.io" denied the request: configuration is invalid: Envoy filter: unknown message type "udpa.type.v1.TypedStruct" (repeated 1 times)
Error from server: error when creating "STDIN": admission webhook "pilot.validation.istio.io" denied the request: configuration is invalid: 3 errors occurred: (repeated 2 times)
        * Envoy filter: unknown message type "udpa.type.v1.TypedStruct" (repeated 6 times)
Error from server: error when creating "STDIN": admission webhook "pilot.validation.istio.io" denied the request: configuration is invalid: 2 errors occurred: (repeated 1 times)
        * Envoy filter: unknown message type "envoy.tcp.metadataexchange.config.MetadataExchange" (repeated 2 times)

```

@kyessenov @ayj

**Comment by kyessenov** [comment]
Galley cannot use future proto definitions. UDPA typed struct is the only way to reliably propagate those protos through Galley.

**Comment by howardjohn** [comment]
The problem is that galley itself doesn't know about the protos. Although this is a pretty niche case of "1.4 with telemetry v2 -> 1.5 with telemetry v2 without istiod" - perhaps the answer here is we do not support that

**Comment by kyessenov** [comment]
I take it as galley baking-in an assumption that no new protos will ever be introduced in the future.
So it's a bug that probably needs to be fixed for 1.5.

**Comment by howardjohn** [comment]
That is a good point actually, this applies even to 1.5 Istiod validation

**Comment by kyessenov** [comment]
Situation is worse due to the fact galley is using gogoproto. We can't be generating and linking gogoproto for every envoy proto out there.

**Comment by howardjohn** [comment]
How are we even getting XDS protos to work here? very confused how this ever worked https://github.com/istio/istio/blob/4170e2e2bd27e4d5b6e585fde8bfe9cce9d45ce5/pkg/config/xds/xds.go#L68

**Comment by kyessenov** [comment]
I don't know. I'm not familiar with galley code base.

**Comment by howardjohn** [comment]
nevermind, it's golang proto. I don't think we have a way around requiring all though protos

**Comment by kyessenov** [comment]
What I don't understand is where does Any come from in Galley? It takes a JSON from k8s and returns some JSON? Where is it reading protobuf bytes?

**Comment by howardjohn** [comment]
I think the flow is galley reads kubernetes json and creates an EnvoyFilter proto message (gogo). That proto has a struct with the config. Inside of pilot, we take that struct and convert it to a golang proto Message (linked above)

**Comment by ayj** [comment]
What @howardjohn sounds about right. Galley and Pilot use gogo for Istio APIs and golang for xDS. GogoStructToMessage is converting from gogo to golang via unmarshal/marshal. 

Putting aside validation for a moment, its not clear how this works for a 1.4 Pilot processing an already persisted 1.5 EnvoyFilter. Presumably it would have the same problem?

**Comment by howardjohn** [comment]
Pilot is not expected to be forward compatible so I think it's more or less fine to have it not work with a 1.5 EnvoyFilter. I would prefer if it did but it's not really a  hard requirement. We are the same issues with new APIs (a really bad example - you switch all your rbac config over to some new rbac API then rollback to an old pilot that doesn't support that API and suddenly you have no rbac

**Comment by howardjohn** [comment]
also @rshriram 

To me, there is nothing here that is P0 for 1.5 release but something that may require more long term thought

**Comment by howardjohn** [comment]
I have not experienced this in later upgrade testing with our new webhook approach
