### ISSUE TITLE
validation and injection webhook controllers need leader election

### ISSUE THREAD

**Issue by ayj** [istio/istio#20596]
The validation and injection wehbook controllers reconcile the validating and mutating webhook configuration. We previously only a few instances of each controller which resulted in minimal load on the kube-apiserver. Now that we've bundled this with istiod, which can scale to higher number of replicas, we should explicitly elect one leader to manage the configuration. istiod with injection/validation disabled should not be candidates for leader.

**Comment by howardjohn** [comment]
related https://github.com/istio/istio/issues/20583

**Comment by howardjohn** [comment]
this is done
