### ISSUE TITLE
Dynamic HTTP header for outbound traffic

### ISSUE THREAD

**Issue by c0c0n3** [istio/istio#20602]
### Context
I'm trying to add a dynamically generated HTTP header to requests originating from a service in my Istio mesh and directed to a remote service outside of the mesh. Whenever the mesh service, call it `O`, makes an HTTP request `r` to the external target service `T`, I need to add an extra header `h` to the original request `r` so that `T` eventually receives `r+h`. Schematically,

    ------------------
    | Istio mesh     |
    |                |
    |  O ---> ? ---> o ---> T
    |  r     r+h     |     r+h
    |                |
    ------------------

The catch is that `h` gets generated for each `r` by another process in the mesh so it can't be hard-coded in Istio routing configuration.

### Question
Is there any way of setting up Istio so that each `r` can be intercepted, the process generating `h` gets called, `h` gets added to `r` and then `r+h` gets forwarded to `T`?

### My failed attempt
I've implemented a custom adapter to generate the header but can't manage to use its output as a value for the header. In fact, it looks like the adapter never gets called during the routing process even though I have a rule matching any request. Here's my adapter-related config (some fields omitted for the sake of brevity):

    kind: handler
    metadata:
      name: orionadapter-handler
      namespace: istio-system
    spec:
      adapter: orionadapter
      connection:
        address: "orionadapterservice:43210"

    kind: instance
    metadata:
     name: oriondata-instance
     namespace: istio-system
    spec:
      template: oriondata
      params:
        source_uid: source.uid | ""

    kind: rule
      metadata:
        name: orionadapter-rule
        namespace: istio-system
    spec:
      actions:
      - handler: orionadapter-handler.istio-system
      instances:
      - oriondata-instance
        name: adapter_response
      requestHeaderOperations:
      - name: header-to-add
        values: [ adapter_response.output.header_value ]

I set up my Istio cluster with the demo profile which comes with, among other things, an egress gateway. Below is my test egress routing config (again, shrunk down for the sake of brevity):

    kind: ServiceEntry
      metadata:
        name: external-httpbin
    spec:
      hosts:
      - httpbin.org
      location: MESH_EXTERNAL
      ports:
      - number: 80
        name: http
        protocol: HTTP

    kind: VirtualService
      metadata:
        name: outbound-connector
    spec:
      gateways:
        - istio-egressgateway
        - mesh
      hosts:
        - httpbin.org
      http:
        - route:
          - destination:
              host: httpbin.org

With this configuration, if I get a shell on the pod hosting my service `O` (i.e. where requests `r` should originate) and e.g.

    $ curl -v http://httpbin.org

I can see the `curl` request being routed from the Envoy sidecar, through the egress gateway, to `httpbin.org` which echoes the headers back to me. Also, I can configure the virtual service above with a "static" header, e.g.

      http:
        - route:
          - destination:
              host: httpbin.org
          headers:
            request:
              add:
                silly: billy

and the header gets added to the request that eventually hits the external target service, `httpbin` in this example.

But, like I said, my adapter never gets called by the Mixer even though the above rule has no `matches` clause so the rule's actions should actually be executed on every request?

I'd greatly appreciate if any of you Istio gurus could help...

Many thanks!

**Comment by c0c0n3** [comment]
Oh forgot to mention. If this isn't possible at the moment but it isn't too hard to implement, I'll definitely consider contributing to the development of this feature.

**Comment by xiao1dian** [comment]
any update? I have same question.

**Comment by howardjohn** [comment]
This can be done with custom WASM or Lua: https://medium.com/@bryant.hagadorn/how-to-add-header-security-to-an-istio-application-with-an-envoy-wasm-filter-without-changing-a-a8adabcca27b, https://istio.io/latest/blog/2020/wasm-announce/, https://docs.solo.io/web-assembly-hub/latest/tutorial_code/getting_started/

I don't think we will implement anything beyond this, as these give the most flexibility needed. Thanks!

**Comment by c0c0n3** [comment]
> This can be done with custom WASM or Lua

WASM? Sorry I forgot to mention the Istio version I was battling with at the time was 1.4---1.5 wasn't out yet back then. My bad :-)
In the end we decided to put together a Lua based stopgap solution for 1.4 until we upgrade to 1.5 or 1.6. But thanks so much for the reference articles, I'll have a look when we switch to 1.6.

**Comment by GitHubAjit** [comment]
hi @c0c0n3 , did you finally find a solution to your problem.  I too have a similar requirement where I need to intercept the request from the mesh service and insert a header.  Please share more on what you ended up with.

**Comment by c0c0n3** [comment]
hi @GitHubAjit 

> did you finally find a solution to your problem

What we did was to use a Lua filter---Envoy runs the filter on every response and the filter adds the header. That was a few years back though and eventually we ditched the component I was working on.

> I too have a similar requirement where I need to intercept the request from the mesh service and insert a header

Did you look into WASM as @howardjohn suggested? If memory serves, you should be able to access the Envoy response object directly from your WASM plugin, but don't quote me on that :-)
