### ISSUE TITLE
Log in Kiali Unauthorized

### ISSUE THREAD

**Issue by fafg** [istio/istio#20617]
**Bug description**
Is not possible to log into kiali using username and pwd.

**Expected behavior**
user logged in using uersname and pwd

**Steps to reproduce the bug**
deploy the kiali secrect:
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Secret
metadata:
  name: kiali
  namespace: $NAMESPACE
  labels:
    app: kiali
type: Opaque
data:
  username: $KIALI_USERNAME
  passphrase: $KIALI_PASSPHRASE
EOF

setup istio using istioctl:
```shell
istioctl manifest apply --set telemetry.enabled=true --set values.grafana.enabled=true --set values.kiali.enabled=true --set "values.kiali.dashboard.grafanaURL=http://grafana:3000"
```
**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istioctl: 1..4.3
kubectl: 1.16
kubernetes cluster version: 1.15.7

**How was Istio installed?**
```shell
curl -L https://istio.io/downloadIstio | sh -
```
**Environment where bug was observed (cloud vendor, OS, etc)**
Azure AKS (azure kubernetes services)

![image](https://user-images.githubusercontent.com/9274235/73305111-c3835080-4219-11ea-942d-a603f01488e0.png)

![image](https://user-images.githubusercontent.com/9274235/73305221-f2012b80-4219-11ea-865a-f76aa6b45df0.png)

![image](https://user-images.githubusercontent.com/9274235/73305259-09401900-421a-11ea-9cbd-acb79712c5b4.png)

![image](https://user-images.githubusercontent.com/9274235/73305340-2f65b900-421a-11ea-9545-247417f4f929.png)

![image](https://user-images.githubusercontent.com/9274235/73305467-6fc53700-421a-11ea-8da6-9a33cd82ddc3.png)

![image](https://user-images.githubusercontent.com/9274235/73305515-8a97ab80-421a-11ea-8dbf-ac5c8e34174a.png)

![image](https://user-images.githubusercontent.com/9274235/73305542-95ead700-421a-11ea-9854-c26b4fe33e4e.png)

**Comment by fafg** [comment]
![image](https://user-images.githubusercontent.com/9274235/73306918-77d2a600-421d-11ea-89c6-1ffedbba8876.png)

**Comment by michaelschmit** [comment]
I was able to get this working with the latest version of kiali.  I would verify that your username and passphrase are base64 encoded.  Also, if you update your secret, I would make sure the kiali pods are restarted.  From experience, I think the secret is read on start-up of the pods.

**Comment by fafg** [comment]
I just got into another topic and understood my problem...

basic I updated the command from this:
```shell
cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1 | openssl dgst -sha224 | awk '{print $2}' | base64
```
to this:
```shell
cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1 | openssl dgst -sha224 | awk '{print $2}' | xargs echo -n  | base64
``` 

basic the ***echo -n*** fixed my issue

thank you very much for all the attention @michaelschmit
