### ISSUE TITLE
istioctl -? doesn't work

### ISSUE THREAD

**Issue by craigbox** [istio/istio#20611]
**Describe the feature request**

`istioctl -?` is actively less helpful than other commands.  Please make it a synonym for `istioctl -h`.

```
$ istioctl -?
Error: unknown shorthand flag: '?' in -?

$ istioctl flobadob
Error: unknown command "flobadob" for "istioctl"
Run 'istioctl --help' for usage.
```

**Comment by dgn** [comment]
While I agree that `istioctl -?` should show usage instructions like any other broken command, I don't think `-?` is a standard synonym for `-h`?

**Comment by dgn** [comment]
FWIW the inconsistency between `istioctl -?` and `istioctl flobadob` is an issue in the CLI library we're using and I submitted a PR to fix it: https://github.com/spf13/cobra/pull/102

**Comment by craigbox** [comment]
Thanks.  For some reason `-?` is my go-to for `--help`, perhaps because I grew up on MS-DOS and was used to `/?` :)

**Comment by esnible** [comment]
`kubectl -?` behaves as the requester asks.

**Comment by howardjohn** [comment]
> kubectl -? behaves as the requester asks.



```
$ kubectl '-?'
Error: unknown shorthand flag: '?' in -?
See 'kubectl --help' for usage.
```

Other common commands do not support this
```
$ ls '-?'
ls: invalid option -- '?'
Try 'ls --help' for more information.
```
```
$ helm '-?'
Error: unknown shorthand flag: '?' in -?
```
Personally, I don't think this is something we should do

**Comment by howardjohn** [comment]
Closing as there doesn't seem to be interest or consistency in similar tools
