### ISSUE TITLE
Istio agent support writing secrets to file for applications to consume

### ISSUE THREAD

**Issue by myidpt** [istio/istio#20623]
**Describe the feature request**
Istio agent needs to write the secrets to local files, so that the user's applications can consume it from file. This is needed for Prometheus (directly loads key&certs from file) and other applications that don't run with sidecars.

**Describe alternatives you've considered**
secret volume mount - but istiod doesn't plan to have permission to write to secrets in user's namespaces.

**Additional context**

**Comment by myidpt** [comment]
Our plan is to support passing a flag to the (Envoy+istio-agent) sidecar, indicating "write the SDS secret to file". In this case, istio agent will write the secret to the file. The file is shared between sidecar and the backend application via the emptyDir volume.

**Comment by incfly** [comment]
Seems done? I overheard this plan during 1.5 release, but can't know for sure.

**Comment by incfly** [comment]
feel free to reopen with a priority set.
