### ISSUE TITLE
Leftover citadel certs will be used with Istiod, which will eventually expire and not be valid anymore

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#20624]
If you have old citadel secrets sticking around and install Istiod, we will still use those certs. Eventually those will expire or otherwise no longer be valid, and all traffic will fail. There IS valid case for reading file mounted certs, but we need to make it opt in

**Comment by howardjohn** [comment]
fyi @myidpt this is not theoretical either, I ran into this

**Comment by myidpt** [comment]
The mounted workload certs are valid for at least 45 days. Users should reinject the sidecars when they migrate, which will get rid of the secret volume. I don’t know what use case you are having.

**Comment by howardjohn** [comment]
We are mounting the secrets even in 1.5 is the issue

**Comment by myidpt** [comment]
I don't like introducing another flag to control the volume mount, but seems like we need it in this case. Let's call the flag "custom_secret_volume_mount", we need to support:
1. With SDS enabled, by default, no secret volume mount
2. With SDS enabled, users can use the flag "custom_secret_volume_mount=true" to enable secret volume mount. Istio agent picks the secret and serves it through SDS.
3. Without SDS disabled, secret volume mount is used. No SDS.

**Comment by howardjohn** [comment]
> Without SDS disabled, secret volume mount is used. No SDS.

This no longer exists. SDS is always used.

Should we just have users use this? https://github.com/istio/istio/blob/caf16467cd407c63b546963ddbf50d1d36652c43/manifests/istio-control/istio-discovery/files/injection-template.yaml#L395-L400

**Comment by myidpt** [comment]
We still have the flag to disable SDS, no?

**Comment by howardjohn** [comment]
Not that I know of...

**Comment by myidpt** [comment]
You are right. We can rely on this annotation, then we need to tell users to specify that in annotation if they were using their only mounted secrets on /etc/certs. If we don't have many of these users, I think that's OK.

/cc @costinm

**Comment by myidpt** [comment]
Per offline discussion, we'll use a global flag to around the /etc/certs mounting, since for most of the use cases people are mounting the secrets on /etc/certs for internal mTLS.

**Comment by howardjohn** [comment]
Fixed by #20786
