### ISSUE TITLE
latest daily build on master fails to install istio via istioctl

### ISSUE THREAD

**Issue by incfly** [istio/istio#20636]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

```shell
istio-1.6-alpha.8f817062b73d110f81113363bbcaed67fdbb523c bin/istioctl manifest apply
```

```
This will install the default Istio profile into the cluster. Proceed? (y/N) y
Error: failed to generate and apply manifests, error: failed to generate manifest: could not read translateConfig file translateConfig/translateConfig-1.6.yaml: Asset translateConfig/translateConfig-1.6.yaml not found
```

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
Can we add a test to prevent this from happening again?

**Comment by elfinhe** [comment]
this should be addressed in https://github.com/istio/operator/pull/707/files
maybe it got partially reverted, let me take a look.

**Comment by elfinhe** [comment]
related: https://github.com/istio/istio/pull/20673

**Comment by ostromart** [comment]
I think this was resolved, @elfinhe please reopen if that's not the case.
