### ISSUE TITLE
Istio pilot not starting with params galley.enabled=false,global.useMCP=false

### ISSUE THREAD

**Issue by keerthig9** [istio/istio#20685]
Hi Team,

Am trying to update Istio from 1.1.5 to 1.4.3, We use helm to install istio with some custom config params. We disabled galley with Istio 1.1.5 using attributes galley.enabled=false, global.useMCP=false for Istio 1.1.5. Now ran same command and installed Istio 1.4.3, Istio pilot is not starting with readiness probe failure and looking into logs, i see it's trying to do something with CRD but we pass flag --disable-install-crds, so ideally istio pilot should not worry about CRD.

Platforms Used: Istio: 1.4.3, Kubernetes: 1.14

Helm command:
helm template install/kubernetes/helm/istio \
--name istio --namespace istio-system \
--set gateways.istio-ingressgateway.sds.enabled=true,global.proxy.resources.requests.cpu=100m,global.proxy.autoInject=disabled,global.disablePolicyChecks=true,global.mtls.enabled=false,global.enableTracing=false,global.defaultResources.requests.cpu=100m,\
gateways.istio-egressgateway.enabled=false,sidecarInjectorWebhook.enabled=false,\
gateways.istio-ingressgateway.autoscaleMin=5,gateways.istio-ingressgateway.autoscaleMax=100,gateways.istio-ingressgateway.resources=,gateways.istio-gateways.istio-ingressgateway.type=NodePort,\
pilot.autoscaleMin=5,pilot.autoscaleMax=50,\
mixer.istio-telemetry.autoscaleMin=5,mixer.istio-telemetry.autoscaleMax=50,\
prometheus.enabled=false,\
galley.enabled=false,global.useMCP=false,gateways.istio-ingressgateway.type=NodePort | > istio-1.4.3.yaml

Pilot Error:
2020-01-30T02:42:28.414573Z	info	controller "synthetic-service-entry" is syncing...
2020-01-30T02:42:28.432712Z	error	k8s.io/client-go@v11.0.1-0.20190409021438-1a26190bd76a+incompatible/tools/cache/reflector.go:98: Failed to list *crd.SyntheticServiceEntry: the server could not find the requested resource (get syntheticserviceentries.networking.istio.io)
2020-01-30T02:42:28.514087Z	info	controller "synthetic-service-entry" is syncing...
2020-01-30T02:42:28.514576Z	info	controller "synthetic-service-entry" is syncing...
2020-01-30T02:42:28.614053Z	info	controller "synthetic-service-entry" is syncing...
2020-01-30T02:42:28.614577Z	info	controller "synthetic-service-entry" is syncing...
2020-01-30T02:42:28.714052Z	info	controller "synthetic-service-entry" is syncing...

When i reinstalled Istio by removing parameters galley.enabled=false, global.useMCP=false with helm command, Istio components running fine.

Questions:
1) Why Istio 1.4 with galley.enabled=false, global.useMCP=false, trying to sync CRD SyntheticServiceEntry
2) How to disable galley for Istio 1.4?
3) Is galley mandatory for Istio 1.4?

**Comment by howardjohn** [comment]
I think I'm 1.4 you also need pilot.useMCP=false, I'll confirm later

**Comment by keerthig9** [comment]
I tried adding pilot.useMCP=false and also mixer.istio-telemetry.useMCP=false to helm command , but the output yaml has no difference.

**Comment by howardjohn** [comment]
I  think this was a bug with SSE. This has been removed in 1.5, so I think this is resolved
