### ISSUE TITLE
SDS proxy startup time impact

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#20697]
We need to measure the impact on proxy startup time relative to file mounts. Anecdotally, it seems to be much slower, with at least 5s to get ready vs ~2s with filemount

**Comment by JimmyCYJ** [comment]
Tentatively assign to Lei who is working on istio-agent for 1.5.

**Comment by howardjohn** [comment]
Escalating this to release blocker as this is a regression

**Comment by howardjohn** [comment]
I have built a custom proxy which dumps the response from the istiod CA to file and uses file mounts, it starts up in 2s

**Comment by lei-tang** [comment]
@howardjohn Thank you for the measurement data! As it starts up in 2s, it is of the same performance as ~2s with filemount. Thus, the startup time looks to be as expected.

**Comment by howardjohn** [comment]
@lei-tang, I am saying that if I use a file its 2s (pr: https://github.com/istio/istio/pull/21010). SDS is still 6s

**Comment by howardjohn** [comment]
Getting better numbers. Test method is starting a deployment of alpine with 0 replicas, running `k scale deployment --replicas=25 alpine` then running
```bash
for pod in $(kubectl get pods -oname); do
  lgs=$(kubectl logs $pod -c istio-proxy)
  d1=$(echo $lgs | head -n1 | cut -d$'\t' -f1)
  d2=$(echo $lgs | grep "Envoy proxy is ready" | cut -d$'\t' -f1)
  printf '%s - %s\n' "$(date -d "$d2" +%s.%N)" "$(date -d "$d1" +%s.%N)" | bc
done | sort
```

Once they have all started. This gives us the timestamp of istio being marked ready relative to the timestamp it was started.

Results:

Current master:
```
2.459802000
3.771399000
4.115780000
4.152314000
5.032177000
5.579571000
5.803938000
6.575770000
7.329616000
7.417766000
7.885780000
8.209819000
8.445739000
8.785946000
8.811388000
8.890914000
9.219137000
9.672352000
10.015282000
10.215891000
10.834100000
19.192689000
20.603949000
24.039269000
24.095259000
```

With my pr:
```
3.217891000
3.939035000
4.003271000
4.100023000
4.280574000
4.788611000
4.912006000
5.004672000
6.101732000
6.105428000
6.540842000
6.905254000
7.067601000
7.146414000
7.420899000
7.666339000
7.708749000
8.298464000
8.391050000
8.599406000
9.784732000
10.520801000
10.521051000
10.765647000
10.953887000
```


file | sds | measurement
-- | -- | --
6.98977516 | 9.64622588 | mean
10.520951 | 20.039445 | p90
2.355892683 | 5.97594061 | stddev

**Comment by howardjohn** [comment]
Note: my change is not even completely disabling SDS either, it still uses it for the connection to pilot

**Comment by howardjohn** [comment]
I made my change use full file based, even for pilot. New results:


  | full sds | control plane sds | no sds
-- | -- | -- | --
mean | 9.64622588 | 6.98977516 | 2.83622512
p90 | 20.039445 | 10.520951 | 3.9465842
stddev | 5.97594061 | 2.355892683 | 0.7519597506

conclusion: SDS is 3.4x slower in avg, and 5x slower in p90

<details>

full data:
```

1.698388
--
1.828273
1.951745
2.131568
2.175708
2.391258
2.459247
2.512265
2.514778
2.52549
2.528405
2.554655
2.605857
2.622094
2.707828
2.748156
2.987978
3.01939
3.058743
3.549781
3.6982
3.829457
4.024669
4.313821
4.467874


```

</details>

**Comment by howardjohn** [comment]
It seems to not scale with cluster size. I created 50 random services, and reran tests and got the same result

**Comment by howardjohn** [comment]
| istio 1.4 filemount | istio 1.4 SDS | full sds | control plane sds | no sds+csr | single envoy grpc
-- | -- | -- | -- | -- | -- | --
mean | 2.10517884 | 3.21930044 | 9.64622588 | 6.98977516 | 2.83622512 | 6.27448616
p90 | 2.8873124 | 4.0363788 | 20.039445 | 10.520951 | 3.9465842 | 9.8087938
stddev | 0.7011293784 | 1.476663513 | 5.97594061 | 2.355892683 | 0.7519597506 | 2.627812919

control plane SDS: an experimental change where just the xds cluster uses SDS, rest file mount
no sds: using file mount only, but fetch certs from istiod
single envoy grpc: an experimental change to make all SDS config share a single cluster

**Comment by lei-tang** [comment]
When a proxy starts, it will go through a few steps:
- k8s creates the container. When the container has volume mounts, the time consumed by this step also includes waiting the volumes to be mounted.
- Envoy requests for xDS config from Pilot.
- Envoy receives xDS config from Pilot.
- Envoy sends SDS request. 
- Envoy receives SDS response.

If we have timestamps for each of the steps, it will help us to figure out which step(s) cause the increased startup time.

**Comment by howardjohn** [comment]
The first step is not included, I am only considering the time when envoy starts running (the binary, not the whole container) to the time its marked as ready. The other steps I don't have measured right now, possibly could bump up the logging and extract it. Please note that there is actually 4 xds requests and 2 sds requests though. Given if we just turn of SDS it's 7x faster, I think we can safely assume it's the SDS part that is slow?

**Comment by howardjohn** [comment]
We are generating a `default` secret 3x during startup. Each of these seems to takes 1-2s

**Comment by howardjohn** [comment]
I think I have a fix, will update with more info after further testing

**Comment by myidpt** [comment]
Thanks @howardjohn

**Comment by howardjohn** [comment]
| full sds | single envoy grpc | read from cache | cache+single
-- | -- | -- | -- | --
mean | 9.64622588 | 6.27448616 | 3.53375364 | 3.20595752
p90 | 20.039445 | 9.8087938 | 4.957918 | 4.3712838
stddev | 5.97594061 | 2.627812919 | 1.099486165 | 0.9737513167

I have 2 optimizations. The first is to create a single cluster, "SDS", that is used for all sds connections, rather than having each one reference their own sds url (which is always the same). This changes from google_grpc to envoy_grpc which may be problematic - needs more investigation. This drops p50 from 9.6s -> 6.2s and p90 from 20s -> 9.8s

The other one, "read from cache" means we just do a CSR a single time, we don't generate the same secret repeatedly. This drops to 3.5s and 5s for p50/p90

If we apply both at once, we get down to 3.2s/4s, which is identical to what I saw with 1.4 SDS. There is still some regression over filemount (2.1s/2.9s)

**Comment by lei-tang** [comment]
My speculation for the startup difference between SDS (3.2s/4s) and file mount (2.1s/2.9s) is:
- For file mount, the private key and certificate have been generated and mounted to the pod through a secret volume. When Envoy starts, the private key and certificate are available already.
- In contrast, for SDS, the private key and certificate is generated after Envoy starts, which takes some time to complete (e.g., generate CSR, signing certificate, and etc).

**Comment by howardjohn** [comment]
@lei-tang yes I agree, the CSR seems to take roughly ~1s to create. I am planning to get a more exact number on that, but that seems to be the overhead. This also can play into envoy exponential back-off on the XDS connection, but generally I think with my change we are down to a reasonable number (https://github.com/istio/istio/pull/21038)

**Comment by howardjohn** [comment]
The above 3 changes make this time now 1.9s/2.3s, which is roughly the same as the 2.1/2.8s we see with 1.4 file mount (a bit faster, but likely there is some noise in the measurement)

**Comment by yangminzhu** [comment]
> The above 3 changes make this time now 1.9s/2.3s, which is roughly the same as the 2.1/2.8s we see with 1.4 file mount (a bit faster, but likely there is some noise in the measurement)

@howardjohn Thanks John, that's a really nice analysis and the improvement is great, good job!

**Comment by howardjohn** [comment]
The 3 fixes here are merged
