### ISSUE TITLE
"istioctl pc" config dump has no route type: istioctl version support (v2 vs v3 xds)

### ISSUE THREAD

**Issue by esnible** [istio/istio#20714]
```
istioctl pc bootstrap details-v1-78d78fbddf-d7t95
Error: config dump has no route type.googleapis.com/envoy.admin.v3.BootstrapConfigDump

istioctl pc cluster details-v1-78d78fbddf-d7t95
Error: config dump has no route type.googleapis.com/envoy.admin.v3.ClustersConfigDump

istioctl pc listener details-v1-78d78fbddf-d7t95
Error: config dump has no route type.googleapis.com/envoy.admin.v3.ListenersConfigDump

istioctl pc route details-v1-78d78fbddf-d7t95
Error: config dump has no route type.googleapis.com/envoy.admin.v3.RoutesConfigDump

istioctl pc secret details-v1-78d78fbddf-d7t95
Error: config dump has no route type.googleapis.com/envoy.admin.v3.SecretsConfigDump


```

`pc endpoint` and `pc log` work.

To reproduce, use the `istioctl` from Master against 1.5-alpha.

```
istioctl version
client version: 3a11e7f9901c73881cdceb854ecc76e8e0c803a7
control plane version: 1.5-alpha.78ca6d7b378fab625f0e4f06e3713e7c545859b7
data plane version: 1.5-alpha.78ca6d7b378fab625f0e4f06e3713e7c545859b7 (7 proxies)
```

To keep this from happening again, create an integration test.

**Comment by esnible** [comment]
Related: https://github.com/istio/istio/issues/19409

**Comment by howardjohn** [comment]
You are using an old proxy image. That commit is from 1/23, we updated envoy on 1/27: #20586

**Comment by esnible** [comment]
@howardjohn Is there an expectation that `istioctl proxy-config` will work with the previous version of Istio?  If istioctl 1.5.x cannot look at Istio 1.4.x sidecars it will be perceived as brittle, especially during upgrades when sidecars of both versions are running.

**Comment by howardjohn** [comment]
@esnible I don't know, probably a UX decision to make. Its already brittle (for devs), look at the PR I linked... we had to manually update 1000 lines of config dumps

**Comment by esnible** [comment]
Setting to "nebulous future" and adding to the agenda of UX meeting.

**Comment by PiotrSikora** [comment]
This should probably be fixed (i.e. `istioctl` should support `/config_dump` output from 1.4 and older proxies using Envoy API v2, and 1.5 and newer proxies using Envoy API v3) before we ship 1.5.

**Comment by esnible** [comment]
@PiotrSikora @howardjohn We will discuss `istioctl pc` compatibility with Istio 1.4 next Tuesday during UX.  I think we SHOULD support the previous version of Istio in the CLI.

To size the effort, I attempted to write code to look for either v2alpha or v3.  The Envoy code is doing something squirrely to `json.Unmarshal`.  If the "github.com/envoyproxy/go-control-plane/envoy/admin/v2alpha" packages is imported (using import `_ "github.com/envoyproxy/go-control-plane/envoy/admin/v2alpha"`, no code needs to use it) in _istioctl/pkg/util/configdump/cluster.go_ the system stops being able to deserialize the v3 protobufs.

I am sure some `init()` is the culprit.  I don't want to replicate Envoy v2alpha protobuf code.  At this point the only thing I can think of doing is writing an ad-hoc generic JSON map[] convert v2alpha to v3.  This seems extreme.  Thoughts?

// _ "github.com/envoyproxy/go-control-plane/envoy/admin/v2alpha"
adminapi "github.com/envoyproxy/go-control-plane/envoy/admin/v3"

**Comment by esnible** [comment]
Related: https://github.com/istio/istio/issues/19409

**Comment by esnible** [comment]
Similar problems with `istioctl x describe` from 1.4 not working with 1.5 and 1.6 control plane.

**Comment by howardjohn** [comment]
We may be able to do some proto magic as a workaround. See https://github.com/istio/istio/issues/19885. We can just swap out the type URL of v2 to v3 and since its wire compatible it will work for the most part
