### ISSUE TITLE
Implement Priority in VirtualService

### ISSUE THREAD

**Issue by Stono** [istio/istio#20717]
**Describe the feature request**
Weighting is great, however I would love to be able to specify a priority instead in https://istio.io/docs/reference/config/networking/virtual-service/#HTTPRouteDestination.

With the idea of being able to prioritise 100% of my traffic to certain instances if they're available, otherwise falling back to the 0%.

The reasoning I want this is I want to have some ephemeral local ssd backed versions of my service which aren't guaranteed to be available, and auto fallback to the slower, stateful ones if required.

Envoy exposes priorities: https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/priority

**Describe alternatives you've considered**
Couldn't work out a way to do this without this feature.

**Additional context**

**Comment by howardjohn** [comment]
I didn't realize priority is on route in envoy as well, I was thinking it was going to be major complications internally to get it working: https://github.com/envoyproxy/envoy/blob/621b346de9851422f92fd898ba0d9134eaff8d3a/api/envoy/api/v2/route/route_components.proto#L836. Seems trivial

**Comment by hzxuzhonghu** [comment]
Currently we have locality failover based on the envoy priority, I think to implement the HTTPRouteDestination priority is not so hard.

**Comment by Stono** [comment]
Any chance we could get this on the roadmap if it's trivial?  It solves a bit problem for us (priority routing to a known master)!

**Comment by ramaraochavali** [comment]
I do not think route level priority in Envoy will actually a select a different destination based on priority - I think that is what @Stono is looking for based on my read of his description.

What Envoy does with the priority in route is to select a different connection pool and allow to have different circuit breaking settings (like max allowed retries etc) based on priority - https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/http_routing#priority-routing

**Comment by Stono** [comment]
bump :)

**Comment by yann-soubeyrand** [comment]
We'd also be interested in being able to specify a fallback route.

**Comment by boundless-thread** [comment]
Also interested in this.  It seems there is no way to configure active-passives with Istio.

**Comment by bmistrapau** [comment]
We are also interested in active-standby support in istio. This issue should be reopened.

**Comment by bmistrapau** [comment]
Hi,

Is there a way to use priorities in istio, without locality load balancing ? I have a multi-cluster architecture (multi-primary different networks) and I want to send all the traffic from both clusters (redis clients) to the same k8s cluster (redis instance). In case the redis instance becomes unavailable in the active cluster, it should automatically failover to the other cluster.
Or can we use weights for this scenario with 0% and 100% values ? Right now, the minimum weight is 1%.
Please, reopen this issue in order to find a solution for active-standby scenario.

Thank you

**Comment by hzxuzhonghu** [comment]
@bmistrapau Please take a look at https://github.com/istio/api/pull/2002
