### ISSUE TITLE
istio.default secret not recreated when namespace is recreated

### ISSUE THREAD

**Issue by Nuru** [istio/istio#20723]
We often use temporary namespaces for trial deployments. When we are done, we delete the namespace, but later, we may re-create the namespace for a new trial. 

We are using automatic sidecar injection using the mutating webhook admission controller. We are not using SDS or mTLS. Nevertheless, the sidecar expects there to be TLS certificates at `/etc/certs/cert-chain.pem`, and these certificates are supposed to be provided by mounting the Kubernetes secret `istio.default` on `/etc/certs`. I don't understand how this secret is supposed to be created, but I see one in almost all of our namespaces.

However, it appears that when we delete a namespace and then recreate it, the secret is not created and installed in the new namespace. This leads to the `istio-proxy` failing to proxy the service and the service therefore failing to come up.

```
[warning][config] [external/envoy/source/common/config/grpc_mux_subscription_impl.cc:81] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener(s) 100.96.0.56_5432: Invalid path: /etc/certs/cert-chain.pem, virtualInbound: Invalid path: /etc/certs/cert-chain.pem
```

If someone can point me to documentation about how/when/by what the `istio.default` secret is created and why it is needed in this case, I can perhaps figure out in more detail what the problem is. So far I have not found any information about it. My conjecture about this being about deleting and re-creating namespaces may be wrong and it might instead have something to do with something else.

**Expected behavior**
I would expect `isito.default` secret to be created when it does not exist as part of automatic sidecar injection, prior to the actual injection of the sidecar.

**Steps to reproduce the bug**
1. Deploy a service into a namespace with automatic sidecar injection, and without SDS or mTLS. 
1. Delete the namespace using `kubectl delete namespace <namespace> --ignore-not-found --cascade=true`
1. Again deploy the service into the namespace.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

istio version 1.3.4 for everything.
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
$ helm version
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}

```

**How was Istio installed?**
`helm`

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS

**Comment by JimmyCYJ** [comment]
When you re-create a namespace, did you re-create a service account as well? The Citadel creates istio.default and mounts that secret to every sidecar proxy.

**Comment by Nuru** [comment]
@JimmyCYJ wrote:
> When you re-create a namespace, did you re-create a service account as well? The Citadel creates istio.default and mounts that secret to every sidecar proxy.

When we (re-)create a namespace, we count on Kubernetes to automatically create the default service account. The failure we are seeing is due to the fact that although the sidecar proxy attempts to mount the `istio.default` secret, the secret does not exist and so the mount path is empty. 

`istoctl ps` shows `STALE (Never Acknowledged)` in the LDS column for the namespace.

**Comment by xiaozhongliu** [comment]
@Nuru, have you got it resolved? I encounter exactly the same issue on istio 1.4.3 now.

**Comment by 2ZZ** [comment]
Just hit this as well. Restarting Citadel caused the missing certs to be created.

**Comment by infa-ddeore** [comment]
restarting istiod in `1.5.1` doesn't create the cert in re-created namespace

new namespaces also dont have this secret, random old nameapces have it 

```
$ k get ns 
NAME                   STATUS   AGE
abc                    Active   9s
def                    Active   7s
default                Active   5d15h
istio-system           Active   23h
kube-node-lease        Active   5d15h
kube-public            Active   5d15h
kube-system            Active   5d15h
kubernetes-dashboard   Active   5d15h
monitoring                   Active   20h
```
secret presents in few namespaces only:

```
$ k get secret -A |grep istio\.def
default                istio.default                                                 istio.io/key-and-cert                 3      5d15h
kube-node-lease        istio.default                                                 istio.io/key-and-cert                 3      5d15h
kube-public            istio.default                                                 istio.io/key-and-cert                 3      5d15h
kube-system            istio.default                                                 istio.io/key-and-cert                 3      5d15h
kubernetes-dashboard   istio.default                                                 istio.io/key-and-cert                 3      5d15h
```

**Comment by howardjohn** [comment]
istio.default secret is no longer ever created in istio 1.5+, so I don't think there is any fix needed here

**Comment by c4m4** [comment]
I am using istio 1.5.2 and I still have this problem :(

**Comment by satishmane** [comment]
Hi @howardjohn 
if istio.default is no longer created, can you please suggest how do we make istio certs available to  Prometheus operator. thanks

**Comment by bobbui** [comment]
it still happens on istio 1.9

**Comment by howardjohn** [comment]
https://istio.io/latest/news/support/announcing-1.5-eol-final/ please upgrade
