### ISSUE TITLE
Option to exclude creation of istio-namespace

### ISSUE THREAD

**Issue by ericjohansson89** [istio/istio#20728]
**Describe the feature request**
I would like the option to opt-out of the creation of the namespace for example:

```
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  defaultNamespace: disabled
```

Currently I have a setup that generates the namespace beforehand and stores it as a state.
If for some reason I want to add additional labels or prehaps remove istio it will disrupt the correct state of the namespace.

**Describe alternatives you've considered**

**Additional context**

**Comment by howardjohn** [comment]
We should just create the namespace if it doesn't exist, and otherwise do not touch it

**Comment by howardjohn** [comment]
If the namespace is created previously we will no longer tamper with it. Thanks for the suggestion!
