### ISSUE TITLE
istioctl apply --dry-run bogus message "failed to get k8s server version"

### ISSUE THREAD

**Issue by esnible** [istio/istio#20729]
If `istioctl manifest apply` is run with `--dry-run` it complains that it couldn't get the Kubernetes server version.

This is not true.  It doesn't even try to retrieve the kubectl version.

To reproduce: `istioctl manifest apply --set values.global.tag=latest --set values.global.sds.enabled=false --dry-run`

During a `--dry-run` we don't want to make changes but it is OK to check configuration.  I propose operator/pkg/kubectlcmd.Version() should clear dryRun option before invoking `c.kubectl()`, and restore it after the version string has been retrieved.  That will make the Operator behavior during dry-run more like the actual behavior.

I further propose Error returns in operator/pkg/manifest spell "Kubernetes" instead of "k8s" to follow the Istio style guide if there is any chance the message will surface to the user. https://istio.io/about/contribute/style-guide/

**Comment by elfinhe** [comment]
thanks ed, I will fix this today.
