### ISSUE TITLE
istio:istio `make clean <some other target` no longer works locally (MacOS only?)

### ISSUE THREAD

**Issue by ericvn** [istio/istio#20731]
**Bug description**

In the past, I was able to do a `make clean init build docker` to do a clean and start building. I no longer can do that:
```
make clean init build 
Building with your local toolchain.
rm -rf /Users/ericvn/work/go/src/istio.io/istio/out/darwin_amd64 /Users/ericvn/work/go/src/istio.io/istio/out/linux_amd64
rm -f  install/consul/istio.yaml install/kubernetes/istio-auth.yaml install/kubernetes/istio-citadel-plugin-certs.yaml install/kubernetes/istio-citadel-with-health-check.yaml install/kubernetes/istio-one-namespace-auth.yaml install/kubernetes/istio-one-namespace-trust-domain.yaml install/kubernetes/istio-one-namespace.yaml install/kubernetes/istio.yaml samples/bookinfo/platform/consul/bookinfo.sidecars.yaml
make: *** No rule to make target `/Users/ericvn/work/go/src/istio.io/istio/out/darwin_amd64', needed by `/Users/ericvn/work/go/src/istio.io/istio/out/darwin_amd64/istio_is_init'.  Stop.
```

The work-around is to do a `make clean` before doing the `make docker` or use the build container (BUILD_WITH_CONTAINER=1) (defaults to that soon, but once there, overriding back with BUILD_WITH_CONTAINER=0 will fail).

**Expected behavior**

I should be able to add the _clean_ target to the list of targets as was possible previously.

**Steps to reproduce the bug**

Setup a development environment. Try `BUILD_WITH_CONTAINER=0 make clean init`

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

_master_ branch

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

MacOS

**Comment by sdake** [comment]
Once we are in `BUILD_WITH_CONTAINER=1` perhaps @howardjohn can do a bit of rework on https://github.com/istio/common-files/pull/172 which I believe either will fix this problem, or enable the fixing of this problem. PR https://github.com/istio/common-files/pull/172 will need a bit of change though to deal with the final changes of `BUILD_WITH_CONTAINER=1`.
