### ISSUE TITLE
Confusing verbiage in istioctl manifest

### ISSUE THREAD

**Issue by esnible** [istio/istio#20743]
I am hoping to get a docs person or installer person to work with me on the vocabulary used by `istioctl`.  The code generates https://istio.io/docs/reference/commands/istioctl/ and the help text output by the CLI.

```
istioctl manifest versions -h
List the versions of Istio recommended for use or supported for upgrade by this version of the operator binary.
...
  -u, --versionsURI string   URI for operator versions to Istio versions map
```

We don't define "operator binary" anywhere.  We need to use a different phrase.  Either "istioctl" or dynamically choose between "istioctl" and the name the operator has when it runs in a pod (`mesh`?)

We don't define `--versionURI`.  In https://preliminary.istio.io/pt-br/docs/reference/commands/istioctl/ we give the default.  Why would a user set it?

**Comment by esnible** [comment]
`istioctl manifest migrate` needs an `Example`.  I don't know how to use it.  The error message did not help:

```
istioctl manifest migrate ./install/kubernetes/helm/istio/values.yaml
proto: tag has too few fields: "-"
Error: error creating values.yaml translator: no value.yaml translator available for version 1.5
```

**Comment by esnible** [comment]
`istioctl manifest versions`

```
Operator version is 1.5.0.

The following installation package versions are recommended for use with this version of the operator:
  1.5.0

The following installation package versions are supported for upgrade by this version of the operator:
  >=1.4.0
   <1.6
```

Should we change this text when `manifest versions` is run in the context of `istioctl`?  The user will not know what "Operator versions" means.

**Comment by mt-inside** [comment]
This may not be the right place for this comment, but it seems related to both this issue and #21999 (or may be a simple bug). `istioctl` 1.6.2 and 1.6.3 both say they're going to install istio `1.6.0`. `istioctl upgrade` similarly says `1.6.0 -> 1.6.0.` This is *really* confusing.

**Comment by esnible** [comment]
@ostromart Can you assign someone to this?

**Comment by esnible** [comment]
Closing because there is no longer an `istioctl manifest versions` subcommand.  It was removed by https://github.com/istio/istio/pull/23512
