### ISSUE TITLE
Gateways options for labels not applied when generating or applying manifest

### ISSUE THREAD

**Issue by marcusportmann** [istio/istio#20754]
The **gateways.istio-ingressgateway.labels.app** and **gateways.istio-ingressgateway.labels.istio** gateways options are not applied correctly when generating or applying the manifest.

For example, when executing the generate command:

/usr/bin/istioctl manifest generate --set profile=demo --set values.gateways.istio-ingressgateway.labels.app=xxx-ingressgateway --set values.gateways.istio-ingressgateway.labels.istio=xxx-ingressgateway

The following Deployment is generated, which includes the default values instead of the specified values:

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: **istio-ingressgateway**
    istio: **ingressgateway**
    release: istio
  name: istio-ingressgateway
  namespace: istio-system
spec:

[ ] Configuration Infrastructure
[ ] Docs
[ X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
The specified values should replace the default values for the labels for the ingress gateway.

**Steps to reproduce the bug**
/usr/bin/istioctl manifest generate --set profile=demo --set values.gateways.istio-ingressgateway.labels.app=xxx-ingressgateway --set values.gateways.istio-ingressgateway.labels.istio=xxx-ingressgateway

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

root@devops:~# istioctl version --remote
client version: 1.4.3
control plane version: 1.4.3
data plane version: 1.4.3 (2 proxies)

root@devops:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.9", GitCommit:"2e808b7cb054ee242b68e62455323aa783991f03", GitTreeState:"clean", BuildDate:"2020-01-18T23:33:14Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.9", GitCommit:"2e808b7cb054ee242b68e62455323aa783991f03", GitTreeState:"clean", BuildDate:"2020-01-18T23:24:23Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
Using istioctl.

**Environment where bug was observed (cloud vendor, OS, etc)**
Kubernetes 1.15.9 on Ubuntu 18.04

**Comment by richardwxn** [comment]
there was a fix merged already in master: https://github.com/istio/istio/commit/50aa2a89c8b1f65d71d0ca34ad72494bbfe549e8 after 1.4.3, should be available for next release.
