### ISSUE TITLE
Need Node watchers for split horizon routing via nodePort gateways

### ISSUE THREAD

**Issue by rshriram** [istio/istio#20751]
For split horizon routing, between two clusters, today Pilot watches the k8s api server for gateway's load balancer IPs (if the gateway service is of type LoadBalancer). All these IPs are added as endpoints for the envoy clusters pertaining to k8s services from that cluster, when using split horizon routing. Similar mechanism applies between vm and k8s as well when VMs talk to K8S via gateways 

In several enterprise environments, LoadBalancer service types are not available. People tend to use NodePort services. In such a scenario, Pilot needs to watch for the kubernetes nodes, and automatically update the endpoint IPs in respective clusters when new nodes come up or nodes go down. The relevant code insertion point is https://github.com/istio/istio/blob/master/pilot/pkg/serviceregistry/kube/conversion.go#L118 (for adding node IPs). 

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by rshriram** [comment]
cc @hzxuzhonghu / @howardjohn - can you guys think of any downsides to adding a node watcher? Knowing the node IPs has several advantages

**Comment by hzxuzhonghu** [comment]
Pure watching isn't much expensive. But there are other complications i can think of:

1. The node numbers can be huge, so the lb endpoints are too many.

1. the lb weight is not well respected

**Comment by rshriram** [comment]
So we can restrict to just 5-6 nodes and not all the nodes right? Because node port is still doing load balancing across all pods in all nodes.
In terms of the LB weight, why is it not respected? If I have 3 clusters, each with 5 nodes, then in a client envoy, we can setup EDS such that it has 15 endpoints where each set of 5 endpoints has one weight corresponding to the locality/etc. right?

**Comment by rshriram** [comment]
cc @vikaschoudhary16 who is interested in contributing..

**Comment by hzxuzhonghu** [comment]
>So we can restrict to just 5-6 nodes and not all the nodes right? Because node port is still doing load balancing across all pods in all nodes.

It depends, when the `service.spec.ExternalTrafficPolicy` is set to "Local", it will route to node local pods


For the lb weight, it is a little complex to handle such case too.
