### ISSUE TITLE
upgrading istio to 1.4 fails with proxy-init issues

### ISSUE THREAD

**Issue by dhineshbabuelango** [istio/istio#20764]
When i upgrade my instances from istio 1.3.3 to istio 1.4 version, all pods are failing with the below error, I saw the istio document that init containers are removed, but existing pods while restarting still looks for this init containers. any way to fix this 

![image](https://user-images.githubusercontent.com/51995628/73584312-6c5bd500-44d2-11ea-9c1e-b64fbab5ef4c.png)

**Comment by howardjohn** [comment]
you need to use proxyv2 image as discussed on slack
