### ISSUE TITLE
Consider having pilot-agent directly mount mesh config

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#20772]
Right now ~60% of the injection template is just passing a bunch of stuff frm mesh config to flags/environment variables just to map it back to some approximation of the real mesh config. It would be a whole lot simpler to just give it the real mesh config.

One way of doing this is to re-use the per-namespace configmap writing we implemented for distributing the ca cert

cc @mandarjog @costinm @lei-tang

**Comment by howardjohn** [comment]
The one downside to this is it locks us into the "write a configmap to each namespace pattern". We can avoid this today when using k8s DNS cert signing. If we do want to get rid of it, we could start reading mesh config from pilot though, so I guess its not too bad

**Comment by mandarjog** [comment]
@ostromart this is what we have been talking about wrt the per namespace config.

**Comment by howardjohn** [comment]
This does make multiple control plane a bit harder. Probably need to make the key `mesh-<revision>` in the config map. Each control plane can share one configmap but use a different key? or we could do a config map each but that may be a bit excessive

**Comment by rshriram** [comment]
who is creating the config map in each namespace? istiod?

**Comment by rshriram** [comment]
Also, think of the upgrades when I update the global mesh config. The propagation delay to copy out this data to each namespace in the system will lead to inconsistencies. The old way mayhave been clunky but it was still centralized (sidecar injector would spit out a bunch of stuff). Old sidecars wont change but new sidecars will all be consistent across namespaces as they are all derived out of the same injector. In this copy-to-each-namespace model (if that is waht is happening), update propagation is tricky isn't it? Overwriting old mesh config, forcing all existing sidecars to reload with potentially bad side effects, etc.

**Comment by howardjohn** [comment]
@rshriram we already have a new "namespace controller" that is writing the ca certificate to each namespace in a configmap, so we are just adding another entry to that configmap. If we didn't have that, I would say that its probably too much overhead.

> Old sidecars wont change but new sidecars will all be consistent across namespaces as they are all derived out of the same injector.

We should still maintain this behavior, aside from the slight chance of race conditions between namespaces? I am be misinterpreting this though.

> Overwriting old mesh config, forcing all existing sidecars to reload with potentially bad side effects, etc.

We do not reload existing sidecars, they will just read at startup. This is the same model as today - when meshconfig changes, the injector will start injecting with that mesh

**Comment by hzxuzhonghu** [comment]
How could this work for non-pod scenario? 

>we already have a new "namespace controller" that is writing the ca certificate to each namespace in a configmap, so we are just adding another entry to that configmap. If we didn't have that, I would say that its probably too much overhead.

I would argue that the namespace controller is a little tricky for me.

**Comment by howardjohn** [comment]
When you say non-pod scenario are you talking about VMs or something? In that case its is very simple, you just pass it the meshconfig.yaml file.

I would say the namespace controller is a bit complex, but its complexity we already have. So adding this to it doesn't make things more complicated?

**Comment by hzxuzhonghu** [comment]
>When you say non-pod scenario are you talking about VMs or something? In that case its is very simple, you just pass it the meshconfig.yaml file.

Ah, i missed it.

>I would say the namespace controller is a bit complex, but its complexity we already have. So adding this to it doesn't make things more complicated?

Yes, there will be duplicate configmaps across the whole cluster.  Most users will worry more about the istio control-plane cost.(I have seen many complains about similar views from social media)

**Comment by howardjohn** [comment]
Well if we want to get rid of the config map per namespace we need to come up with another solution to distribute the ca cert

**Comment by hzxuzhonghu** [comment]
IMO, istiod can serve as cert endpoint and all pilot-agents watch from it.

**Comment by howardjohn** [comment]
obsolete by https://github.com/istio/istio/issues/21222
