### ISSUE TITLE
Filtering HTTP traffic

### ISSUE THREAD

**Issue by Hmr-ramzi** [istio/istio#20776]
**Describe the feature request**
Is it possible to redirect HTTP based on Response not Request ? 
**Describe alternatives you've considered**

**Additional context**

**Comment by howardjohn** [comment]
I am not sure how this works. Isn't to too late to redirect if you have the response? Or are we sending two requests here?

**Comment by howardjohn** [comment]
Closing this as it appears answered/abandoned
