### ISSUE TITLE
istio.io test TestTCPTrafficShifting test flake

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#20771]
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/20770/integ-istioio-k8s-tests_istio/4303

cc @brian-avery

**Comment by su225** [comment]
While working on other tests I made that observation - Maybe some more `sleep` (delay) required to give some time for Pilot to propagate new rules? There is already `sleep 1` before firing `nc`. 

Or is there a better way to check if Pilot has propagated the rules? 

When it was just 10 requests, I noticed this and increased it to 20 while writing tests.

**Comment by brian-avery** [comment]
I haven't had the chance to look into this yet, but it's better to use the following to wait for resources to propagate:

`istioctl experimental wait --for=distribution VirtualService reviews.default`

**Comment by su225** [comment]
@brian-avery - Thanks. I'll incorporate this change and raise a PR

**Comment by brian-avery** [comment]
No problem.

**Comment by brian-avery** [comment]
Note that there currently seems to be issues with `istioctl experimental wait` on 1.5. I created an issue here to track it: https://github.com/istio/istio/issues/21277

**Comment by su225** [comment]
@brian-avery - Shouldn't this be moved to istio/istio.io repo as this is related to an istio-io test?

**Comment by ericvn** [comment]
Currently the flakiness has become a 100% failure after upgrading to kind 0.8.0.

**Comment by howardjohn** [comment]
fixed by https://github.com/istio/istio.io/pull/7308
