### ISSUE TITLE
Duplicated cert code in pilot bootstrap

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#20779]
https://github.com/istio/istio/blob/d2682c6a5e1dc0628f36e7aee2b81dd1453f9d50/pilot/pkg/bootstrap/certcontroller.go#L169
https://github.com/istio/istio/blob/ad167bfb124dcad9e6644551a0f42b5ade5da93a/pilot/pkg/bootstrap/istio_ca.go#L378

we run the exact same code here, seems likely a bug

**Comment by lei-tang** [comment]
https://github.com/istio/istio/pull/20801
