### ISSUE TITLE
Configuring Fallback for Circuit Breaker, Timeout and Retry

### ISSUE THREAD

**Issue by krishnaputhran** [istio/istio#20778]
I am currently using Istio for one of application, and mean time I was trying Fault Tolerance patterns. I have used Resilience4j library and it provides few fault tolerance patterns like Circuit Breaker, Retry, RateLimiter, BulkHead. One of the good thing about Resilience4j is that, it allows me to configure fallback implementations as part of these patterns. For eg: whenever the calls are monitored through CircuitBreaker and if there is trip, then I can send a default response through the fallback method instead of error message. This fallback invocation would be managed by CircuitBreaker, where in I just need to tell Circuit Breaker which is my fallback method. But the bad part of Resilinece4j is that, i need to change my existing code for injecting these patterns into my existing application. 
Since my application is cloud based and based on micro services architecture, Istio is the right fit, and I can configure fault tolerance such as circuit breaker without adding any additional code to my existing application. But I don't see any way to configure fallback's to this, like I have in Resilience4j library. Is this is not supported by Istio or am I missing something to configure here. 

Thanks
Krishna

**Comment by hzxuzhonghu** [comment]
Based on this dochttps://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/circuit_breaking#arch-overview-circuit-break, envoy does not support it.

**Comment by arcturuscom** [comment]
i don't think that istio support the fallback logic because it's up to you to customize the fallback.
i'm using Istio as a circuit Breaker and i handle my fallbacks internally in my app when i receiving 503 error.
