### ISSUE TITLE
Istio-proxy build fails on PowerPC (ppc64le) architecture

### ISSUE THREAD

**Issue by aishwaryabk** [istio/istio#20788]
I am building Istio proxy on rhel:7.6 - ppc64le architecture. I am on branch 1.4.3. I have built dependencies Cmake v-3.7.2, git-2.17.1, go v1.13.6, AdoptOpenJDK11, ninja v1.8.2 and bazel v0.25.0. However the build fails as it is unable to find repositories.

`bash-4.2# sed -i '33a else ifeq ($(LOCAL_ARCH),ppc64le)' Makefile`
`bash-4.2#  sed -i '34a TARGET_ARCH ?= ppc64le' Makefile`
`bash-4.2# make`
`Building with your local toolchain.`
`Starting local Bazel server and connecting to it...`
`DEBUG: /root/.cache/bazel/_bazel_root/b9d32296525d70e9f5a5a3e973772245/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:9:
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.`
`DEBUG: /root/.cache/bazel/_bazel_root/b9d32296525d70e9f5a5a3e973772245/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:125:9: rbe_ubuntu_clang not using checked in configs; Bazel version 1.2.1 was picked/selected but no checked in config was found in map {"0.29.1": ["clang", "clang_libcxx", "gcc"], "1.1.0": ["clang", "clang_libcxx", "gcc"]}`
`DEBUG: /root/.cache/bazel/_bazel_root/b9d32296525d70e9f5a5a3e973772245/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:9:
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.`
`DEBUG: /root/.cache/bazel/_bazel_root/b9d32296525d70e9f5a5a3e973772245/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:125:9: rbe_ubuntu_clang_libcxx not using checked in configs; Bazel version 1.2.1 was picked/selected but no checked in config was found in map {"0.29.1": ["clang", "clang_libcxx", "gcc"], "1.1.0": ["clang", "clang_libcxx", "gcc"]}`
`DEBUG: /root/.cache/bazel/_bazel_root/b9d32296525d70e9f5a5a3e973772245/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:9:
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.`
`DEBUG: /root/.cache/bazel/_bazel_root/b9d32296525d70e9f5a5a3e973772245/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:125:9: rbe_ubuntu_gcc not using checked in configs; Bazel version 1.2.1 was picked/selected but no checked in config was found in map {"0.29.1": ["clang", "clang_libcxx", "gcc"], "1.1.0": ["clang", "clang_libcxx", "gcc"]}`
`export PATH=/usr/lib/llvm-9/bin:/source_root/glide-0.13.3:/opt/rh/python27/root/usr/bin:/opt/rh/devtoolset-7/root/usr/bin:/source_root/jdk-11.0.6+10/bin:/source_root/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/glide-0.13.3:/source_root/bin:/usr/local/bin/protoc:/source_root/go/bin:/usr/local/bin/luajit:/usr/bin/gcc:/usr/local/bin/cmake:/source_root/ninja/build.ninja:/source_root/protobuf:/source_root/bin CC=/opt/rh/devtoolset-7/root/usr/bin/gcc CXX=/opt/rh/devtoolset-7/root/usr/bin/g++ && bazel  build  --config=libc++ //...`
`DEBUG: /root/.cache/bazel/_bazel_root/b9d32296525d70e9f5a5a3e973772245/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:9:
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.`
`DEBUG: /root/.cache/bazel/_bazel_root/b9d32296525d70e9f5a5a3e973772245/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:125:9: rbe_ubuntu_clang not using checked in configs; Bazel version 1.2.1 was picked/selected but no checked in config was found in map {"0.29.1": ["clang", "clang_libcxx", "gcc"], "1.1.0": ["clang", "clang_libcxx", "gcc"]}`
`DEBUG: /root/.cache/bazel/_bazel_root/b9d32296525d70e9f5a5a3e973772245/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:9:
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.`
`DEBUG: /root/.cache/bazel/_bazel_root/b9d32296525d70e9f5a5a3e973772245/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:125:9: rbe_ubuntu_clang_libcxx not using checked in configs; Bazel version 1.2.1 was picked/selected but no checked in config was found in map {"0.29.1": ["clang", "clang_libcxx", "gcc"], "1.1.0": ["clang", "clang_libcxx", "gcc"]}`
`DEBUG: /root/.cache/bazel/_bazel_root/b9d32296525d70e9f5a5a3e973772245/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:9:
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.`
`DEBUG: /root/.cache/bazel/_bazel_root/b9d32296525d70e9f5a5a3e973772245/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:125:9: rbe_ubuntu_gcc not using checked in configs; Bazel version 1.2.1 was picked/selected but no checked in config was found in map {"0.29.1": ["clang", "clang_libcxx", "gcc"], "1.1.0": ["clang", "clang_libcxx", "gcc"]}`
`INFO: Call stack for the definition of repository 'bionic' which is a container_pull (rule definition at /root/.cache/bazel/_bazel_root/b9d32296525d70e9f5a5a3e973772245/external/io_bazel_rules_docker/container/pull.bzl:203:18):`
 `/source_root/proxy/WORKSPACE:105:1`
`ERROR: An error occurred during the fetch of repository 'bionic':
   Pull command failed: /root/.cache/bazel/_bazel_root/b9d32296525d70e9f5a5a3e973772245/external/go_puller_linux/file/downloaded: /root/.cache/bazel/_bazel_root/b9d32296525d70e9f5a5a3e973772245/external/go_puller_linux/file/downloaded: cannot execute binary file`
 `(/root/.cache/bazel/_bazel_root/b9d32296525d70e9f5a5a3e973772245/external/go_puller_linux/file/downloaded -directory /root/.cache/bazel/_bazel_root/b9d32296525d70e9f5a5a3e973772245/external/bionic/image -os linux -os-version  -os-features  -architecture amd64 -variant  -features  -name index.docker.io/library/ubuntu@sha256:3e83eca7870ee14a03b8026660e71ba761e6919b6982fb920d10254688a363d4)`
`ERROR: /source_root/proxy/tools/docker/BUILD:30:1: //tools/docker:envoy_ubuntu depends on @bionic//image:image in repository @bionic which failed to fetch. no such package '@bionic//image': Pull command failed: /root/.cache/bazel/_bazel_root/b9d32296525d70e9f5a5a3e973772245/external/go_puller_linux/file/downloaded: /root/.cache/bazel/_bazel_root/b9d32296525d70e9f5a5a3e973772245/external/go_puller_linux/file/downloaded: cannot execute binary file`
 `(/root/.cache/bazel/_bazel_root/b9d32296525d70e9f5a5a3e973772245/external/go_puller_linux/file/downloaded -directory /root/.cache/bazel/_bazel_root/b9d32296525d70e9f5a5a3e973772245/external/bionic/image -os linux -os-version  -os-features  -architecture amd64 -variant  -features  -name index.docker.io/library/ubuntu@sha256:3e83eca7870ee14a03b8026660e71ba761e6919b6982fb920d10254688a363d4)`
`ERROR: Analysis of target '//tools/docker:push_envoy_ubuntu' failed; build aborted: no such package '@bionic//image': Pull command failed: /root/.cache/bazel/_bazel_root/b9d32296525d70e9f5a5a3e973772245/external/go_puller_linux/file/downloaded: /root/.cache/bazel/_bazel_root/b9d32296525d70e9f5a5a3e973772245/external/go_puller_linux/file/downloaded: cannot execute binary file`
 `(/root/.cache/bazel/_bazel_root/b9d32296525d70e9f5a5a3e973772245/external/go_puller_linux/file/downloaded -directory /root/.cache/bazel/_bazel_root/b9d32296525d70e9f5a5a3e973772245/external/bionic/image -os linux -os-version  -os-features  -architecture amd64 -variant  -features  -name index.docker.io/library/ubuntu@sha256:3e83eca7870ee14a03b8026660e71ba761e6919b6982fb920d10254688a363d4)
INFO: Elapsed time: 17.132s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (100 packages loaded, 491 targets configured)
    currently loading: @io_opencensus_cpp//opencensus/exporters/stats/stackdriver ... (2 packages)
    Fetching @local_config_cc; Restarting.
    Fetching @com_google_absl; fetching
    Fetching @distroless_cc; Restarting.
    Fetching @com_github_google_go_containerregistry; Restarting.
    Fetching @bazel_gazelle_go_repository_config; fetching
    Fetching @com_github_pkg_errors; Restarting.
    Fetching @com_github_golang_protobuf; Cloning 6c65a5562fc06764971b7c5d05c76c75e84bdbf7 of https://github.com/golang/protobuf
make: *** [Makefile.core.mk:58: build] Error 1`

Would like some help on understanding the cause for the same . I am running it on a High end VM with good connectivity.

**Comment by aishwaryabk** [comment]
Additional Errors that are encountered :

ERROR:
`/root/.cache/bazel/_bazel_root/e6cd818c4181fd260a733653db283064/external/bazel_tools/tools/jdk/BUILD:465:14: Configurable attribute "actual" doesn't match this configuration: Could not find a JDK for host execution environment, please explicitly provide one using --host_javabase.`

**Comment by amitsadaphule** [comment]
I was facing similar issue. While building istio-proxy tag 1.4.3 on RHEL 7 ppc64le, with a minor change to the Makefile to add support for ppc64le, I passed BUILD_WITH_CONTAINER with value 0 to the make command as: make BUILD_WITH_CONTAINER=0 build. The corresponding message from the Makefile (Building with your local toolchain) was printed on the console too. However, the bazel build was still trying to resolve docker_dependencies and was failing to fetch those (Please see the log below).

```
[root@558a425a2860 proxy]# make BUILD_WITH_CONTAINER=0 build
Building with your local toolchain.
DEBUG: /root/.cache/bazel/_bazel_root/95196be6aea138945979c78212a284bc/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:9:
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: /root/.cache/bazel/_bazel_root/95196be6aea138945979c78212a284bc/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:125:9: rbe_ubuntu_clang not using checked in configs; Bazel version 1.2.1 was picked/selected but no checked in config was found in map {"0.29.1": ["clang", "clang_libcxx", "gcc"], "1.1.0": ["clang", "clang_libcxx", "gcc"]}
DEBUG: /root/.cache/bazel/_bazel_root/95196be6aea138945979c78212a284bc/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:9:
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: /root/.cache/bazel/_bazel_root/95196be6aea138945979c78212a284bc/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:125:9: rbe_ubuntu_clang_libcxx not using checked in configs; Bazel version 1.2.1 was picked/selected but no checked in config was found in map {"0.29.1": ["clang", "clang_libcxx", "gcc"], "1.1.0": ["clang", "clang_libcxx", "gcc"]}
DEBUG: /root/.cache/bazel/_bazel_root/95196be6aea138945979c78212a284bc/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:9:
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: /root/.cache/bazel/_bazel_root/95196be6aea138945979c78212a284bc/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:125:9: rbe_ubuntu_gcc not using checked in configs; Bazel version 1.2.1 was picked/selected but no checked in config was found in map {"0.29.1": ["clang", "clang_libcxx", "gcc"], "1.1.0": ["clang", "clang_libcxx", "gcc"]}
export PATH=/usr/lib/llvm-9/bin:/usr/local/bin:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.el7_7.ppc64le/bin:/opt/rh/devtoolset-7/root/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/rh/devtoolset-7/root/bin:/root/istio_build/gn/out:/usr/local/go/bin CC=/opt/rh/devtoolset-7/root/usr/bin/gcc CXX=/opt/rh/devtoolset-7/root/usr/bin/g++ && bazel  build --host_javabase=@local_jdk//:jdk --verbose_failures --copt "-DENVOY_IGNORE_GLIBCXX_USE_CXX11_ABI_ERROR=1" --cxxopt=-Wimplicit-fallthrough=0  //...
DEBUG: /root/.cache/bazel/_bazel_root/95196be6aea138945979c78212a284bc/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:9:
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: /root/.cache/bazel/_bazel_root/95196be6aea138945979c78212a284bc/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:125:9: rbe_ubuntu_clang not using checked in configs; Bazel version 1.2.1 was picked/selected but no checked in config was found in map {"0.29.1": ["clang", "clang_libcxx", "gcc"], "1.1.0": ["clang", "clang_libcxx", "gcc"]}
DEBUG: /root/.cache/bazel/_bazel_root/95196be6aea138945979c78212a284bc/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:9:
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: /root/.cache/bazel/_bazel_root/95196be6aea138945979c78212a284bc/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:125:9: rbe_ubuntu_clang_libcxx not using checked in configs; Bazel version 1.2.1 was picked/selected but no checked in config was found in map {"0.29.1": ["clang", "clang_libcxx", "gcc"], "1.1.0": ["clang", "clang_libcxx", "gcc"]}
DEBUG: /root/.cache/bazel/_bazel_root/95196be6aea138945979c78212a284bc/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:9:
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: /root/.cache/bazel/_bazel_root/95196be6aea138945979c78212a284bc/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:125:9: rbe_ubuntu_gcc not using checked in configs; Bazel version 1.2.1 was picked/selected but no checked in config was found in map {"0.29.1": ["clang", "clang_libcxx", "gcc"], "1.1.0": ["clang", "clang_libcxx", "gcc"]}
WARNING: /root/.cache/bazel/_bazel_root/95196be6aea138945979c78212a284bc/external/remote_java_tools_linux/BUILD:675:1: in hdrs attribute of cc_library rule @remote_java_tools_linux//:combiners: Artifact 'external/remote_java_tools_linux/java_tools/src/tools/singlejar/zip_headers.h' is duplicated (through '@remote_java_tools_linux//:transient_bytes' and '@remote_java_tools_linux//:zip_headers'). Since this rule was created by the macro 'cc_library', the error might have been caused by the macro implementation
INFO: Call stack for the definition of repository 'bionic' which is a container_pull (rule definition at /root/.cache/bazel/_bazel_root/95196be6aea138945979c78212a284bc/external/io_bazel_rules_docker/container/pull.bzl:203:18):
 - /root/istio_build/proxy/WORKSPACE:105:1
ERROR: An error occurred during the fetch of repository 'bionic':
   Pull command failed: /root/.cache/bazel/_bazel_root/95196be6aea138945979c78212a284bc/external/go_puller_linux/file/downloaded: /root/.cache/bazel/_bazel_root/95196be6aea138945979c78212a284bc/external/go_puller_linux/file/downloaded: cannot execute binary file
 (/root/.cache/bazel/_bazel_root/95196be6aea138945979c78212a284bc/external/go_puller_linux/file/downloaded -directory /root/.cache/bazel/_bazel_root/95196be6aea138945979c78212a284bc/external/bionic/image -os linux -os-version  -os-features  -architecture amd64 -variant  -features  -name index.docker.io/library/ubuntu@sha256:3e83eca7870ee14a03b8026660e71ba761e6919b6982fb920d10254688a363d4)
ERROR: /root/istio_build/proxy/tools/docker/BUILD:30:1: //tools/docker:envoy_ubuntu depends on @bionic//image:image in repository @bionic which failed to fetch. no such package '@bionic//image': Pull command failed: /root/.cache/bazel/_bazel_root/95196be6aea138945979c78212a284bc/external/go_puller_linux/file/downloaded: /root/.cache/bazel/_bazel_root/95196be6aea138945979c78212a284bc/external/go_puller_linux/file/downloaded: cannot execute binary file
 (/root/.cache/bazel/_bazel_root/95196be6aea138945979c78212a284bc/external/go_puller_linux/file/downloaded -directory /root/.cache/bazel/_bazel_root/95196be6aea138945979c78212a284bc/external/bionic/image -os linux -os-version  -os-features  -architecture amd64 -variant  -features  -name index.docker.io/library/ubuntu@sha256:3e83eca7870ee14a03b8026660e71ba761e6919b6982fb920d10254688a363d4)
ERROR: Analysis of target '//tools/docker:push_envoy_ubuntu' failed; build aborted: no such package '@bionic//image': Pull command failed: /root/.cache/bazel/_bazel_root/95196be6aea138945979c78212a284bc/external/go_puller_linux/file/downloaded: /root/.cache/bazel/_bazel_root/95196be6aea138945979c78212a284bc/external/go_puller_linux/file/downloaded: cannot execute binary file
 (/root/.cache/bazel/_bazel_root/95196be6aea138945979c78212a284bc/external/go_puller_linux/file/downloaded -directory /root/.cache/bazel/_bazel_root/95196be6aea138945979c78212a284bc/external/bionic/image -os linux -os-version  -os-features  -architecture amd64 -variant  -features  -name index.docker.io/library/ubuntu@sha256:3e83eca7870ee14a03b8026660e71ba761e6919b6982fb920d10254688a363d4)
INFO: Elapsed time: 2.667s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (17 packages loaded, 469 targets configured)
    Fetching @distroless_cc; fetching
    Fetching @com_github_google_go_containerregistry; Restarting.
    Fetching @bazel_gazelle_go_repository_config; Restarting.
    Fetching @com_github_pkg_errors; Restarting.
    Fetching @bazel_gazelle_go_repository_tools; Restarting.
make: *** [Makefile.core.mk:58: build] Error 1
```

In order to overcome that, I removed all docker dependencies from WORKSPACE file and removed the file tools/docker/BUILD post which the build succeeded after a few hiccups. Is this patch (or conditionally adding those packages to .bazelignore for ppc64le) the correct way to resolve the issue or did I miss some parameter that needs to be passed to make? Would appreciate some suggestions/pointers on this.

**Comment by howardjohn** [comment]
Lets consolidate into https://github.com/istio/istio/issues/20836, it is hard to track so many split issues. Thanks!

**Comment by muraliinformal** [comment]
> I was facing similar issue. While building istio-proxy tag 1.4.3 on RHEL 7 ppc64le, with a minor change to the Makefile to add support for ppc64le, I passed BUILD_WITH_CONTAINER with value 0 to the make command as: make BUILD_WITH_CONTAINER=0 build. The corresponding message from the Makefile (Building with your local toolchain) was printed on the console too. However, the bazel build was still trying to resolve docker_dependencies and was failing to fetch those (Please see the log below).
> 
> ```
> [root@558a425a2860 proxy]# make BUILD_WITH_CONTAINER=0 build
> Building with your local toolchain.
> DEBUG: /root/.cache/bazel/_bazel_root/95196be6aea138945979c78212a284bc/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:9:
> Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
> DEBUG: /root/.cache/bazel/_bazel_root/95196be6aea138945979c78212a284bc/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:125:9: rbe_ubuntu_clang not using checked in configs; Bazel version 1.2.1 was picked/selected but no checked in config was found in map {"0.29.1": ["clang", "clang_libcxx", "gcc"], "1.1.0": ["clang", "clang_libcxx", "gcc"]}
> DEBUG: /root/.cache/bazel/_bazel_root/95196be6aea138945979c78212a284bc/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:9:
> Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
> DEBUG: /root/.cache/bazel/_bazel_root/95196be6aea138945979c78212a284bc/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:125:9: rbe_ubuntu_clang_libcxx not using checked in configs; Bazel version 1.2.1 was picked/selected but no checked in config was found in map {"0.29.1": ["clang", "clang_libcxx", "gcc"], "1.1.0": ["clang", "clang_libcxx", "gcc"]}
> DEBUG: /root/.cache/bazel/_bazel_root/95196be6aea138945979c78212a284bc/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:9:
> Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
> DEBUG: /root/.cache/bazel/_bazel_root/95196be6aea138945979c78212a284bc/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:125:9: rbe_ubuntu_gcc not using checked in configs; Bazel version 1.2.1 was picked/selected but no checked in config was found in map {"0.29.1": ["clang", "clang_libcxx", "gcc"], "1.1.0": ["clang", "clang_libcxx", "gcc"]}
> export PATH=/usr/lib/llvm-9/bin:/usr/local/bin:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.el7_7.ppc64le/bin:/opt/rh/devtoolset-7/root/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/rh/devtoolset-7/root/bin:/root/istio_build/gn/out:/usr/local/go/bin CC=/opt/rh/devtoolset-7/root/usr/bin/gcc CXX=/opt/rh/devtoolset-7/root/usr/bin/g++ && bazel  build --host_javabase=@local_jdk//:jdk --verbose_failures --copt "-DENVOY_IGNORE_GLIBCXX_USE_CXX11_ABI_ERROR=1" --cxxopt=-Wimplicit-fallthrough=0  //...
> DEBUG: /root/.cache/bazel/_bazel_root/95196be6aea138945979c78212a284bc/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:9:
> Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
> DEBUG: /root/.cache/bazel/_bazel_root/95196be6aea138945979c78212a284bc/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:125:9: rbe_ubuntu_clang not using checked in configs; Bazel version 1.2.1 was picked/selected but no checked in config was found in map {"0.29.1": ["clang", "clang_libcxx", "gcc"], "1.1.0": ["clang", "clang_libcxx", "gcc"]}
> DEBUG: /root/.cache/bazel/_bazel_root/95196be6aea138945979c78212a284bc/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:9:
> Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
> DEBUG: /root/.cache/bazel/_bazel_root/95196be6aea138945979c78212a284bc/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:125:9: rbe_ubuntu_clang_libcxx not using checked in configs; Bazel version 1.2.1 was picked/selected but no checked in config was found in map {"0.29.1": ["clang", "clang_libcxx", "gcc"], "1.1.0": ["clang", "clang_libcxx", "gcc"]}
> DEBUG: /root/.cache/bazel/_bazel_root/95196be6aea138945979c78212a284bc/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:9:
> Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
> DEBUG: /root/.cache/bazel/_bazel_root/95196be6aea138945979c78212a284bc/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:125:9: rbe_ubuntu_gcc not using checked in configs; Bazel version 1.2.1 was picked/selected but no checked in config was found in map {"0.29.1": ["clang", "clang_libcxx", "gcc"], "1.1.0": ["clang", "clang_libcxx", "gcc"]}
> WARNING: /root/.cache/bazel/_bazel_root/95196be6aea138945979c78212a284bc/external/remote_java_tools_linux/BUILD:675:1: in hdrs attribute of cc_library rule @remote_java_tools_linux//:combiners: Artifact 'external/remote_java_tools_linux/java_tools/src/tools/singlejar/zip_headers.h' is duplicated (through '@remote_java_tools_linux//:transient_bytes' and '@remote_java_tools_linux//:zip_headers'). Since this rule was created by the macro 'cc_library', the error might have been caused by the macro implementation
> INFO: Call stack for the definition of repository 'bionic' which is a container_pull (rule definition at /root/.cache/bazel/_bazel_root/95196be6aea138945979c78212a284bc/external/io_bazel_rules_docker/container/pull.bzl:203:18):
>  - /root/istio_build/proxy/WORKSPACE:105:1
> ERROR: An error occurred during the fetch of repository 'bionic':
>    Pull command failed: /root/.cache/bazel/_bazel_root/95196be6aea138945979c78212a284bc/external/go_puller_linux/file/downloaded: /root/.cache/bazel/_bazel_root/95196be6aea138945979c78212a284bc/external/go_puller_linux/file/downloaded: cannot execute binary file
>  (/root/.cache/bazel/_bazel_root/95196be6aea138945979c78212a284bc/external/go_puller_linux/file/downloaded -directory /root/.cache/bazel/_bazel_root/95196be6aea138945979c78212a284bc/external/bionic/image -os linux -os-version  -os-features  -architecture amd64 -variant  -features  -name index.docker.io/library/ubuntu@sha256:3e83eca7870ee14a03b8026660e71ba761e6919b6982fb920d10254688a363d4)
> ERROR: /root/istio_build/proxy/tools/docker/BUILD:30:1: //tools/docker:envoy_ubuntu depends on @bionic//image:image in repository @bionic which failed to fetch. no such package '@bionic//image': Pull command failed: /root/.cache/bazel/_bazel_root/95196be6aea138945979c78212a284bc/external/go_puller_linux/file/downloaded: /root/.cache/bazel/_bazel_root/95196be6aea138945979c78212a284bc/external/go_puller_linux/file/downloaded: cannot execute binary file
>  (/root/.cache/bazel/_bazel_root/95196be6aea138945979c78212a284bc/external/go_puller_linux/file/downloaded -directory /root/.cache/bazel/_bazel_root/95196be6aea138945979c78212a284bc/external/bionic/image -os linux -os-version  -os-features  -architecture amd64 -variant  -features  -name index.docker.io/library/ubuntu@sha256:3e83eca7870ee14a03b8026660e71ba761e6919b6982fb920d10254688a363d4)
> ERROR: Analysis of target '//tools/docker:push_envoy_ubuntu' failed; build aborted: no such package '@bionic//image': Pull command failed: /root/.cache/bazel/_bazel_root/95196be6aea138945979c78212a284bc/external/go_puller_linux/file/downloaded: /root/.cache/bazel/_bazel_root/95196be6aea138945979c78212a284bc/external/go_puller_linux/file/downloaded: cannot execute binary file
>  (/root/.cache/bazel/_bazel_root/95196be6aea138945979c78212a284bc/external/go_puller_linux/file/downloaded -directory /root/.cache/bazel/_bazel_root/95196be6aea138945979c78212a284bc/external/bionic/image -os linux -os-version  -os-features  -architecture amd64 -variant  -features  -name index.docker.io/library/ubuntu@sha256:3e83eca7870ee14a03b8026660e71ba761e6919b6982fb920d10254688a363d4)
> INFO: Elapsed time: 2.667s
> INFO: 0 processes.
> FAILED: Build did NOT complete successfully (17 packages loaded, 469 targets configured)
>     Fetching @distroless_cc; fetching
>     Fetching @com_github_google_go_containerregistry; Restarting.
>     Fetching @bazel_gazelle_go_repository_config; Restarting.
>     Fetching @com_github_pkg_errors; Restarting.
>     Fetching @bazel_gazelle_go_repository_tools; Restarting.
> make: *** [Makefile.core.mk:58: build] Error 1
> ```
> 
> In order to overcome that, I removed all docker dependencies from WORKSPACE file and removed the file tools/docker/BUILD post which the build succeeded after a few hiccups. Is this patch (or conditionally adding those packages to .bazelignore for ppc64le) the correct way to resolve the issue or did I miss some parameter that needs to be passed to make? Would appreciate some suggestions/pointers on this.

I'm also facing the same issue with istio-proxy-1.15.7 build (building outside the container). I exported BUILD_WITH_CONTAINER=0, still its trying to pull bionic image.
