### ISSUE TITLE
consistentHash based on QueryString parameter

### ISSUE THREAD

**Issue by gferreux** [istio/istio#20794]
**Describe the feature request**
Is it possible to use consistentHash based on a queryString parameter ?
eg: `/route?parameter=stickyMe`

**Describe alternatives you've considered**
Maybe possible to use an envoy filter to copy an arg to an httpHeader or request cookie ?

[X ] Networking

Thanks for your help,

**Comment by hzxuzhonghu** [comment]
Currently, envoy does not support this feature.

**Comment by gferreux** [comment]
v1.13.0 seems ready
https://www.envoyproxy.io/docs/envoy/v1.13.0/api-v3/config/route/v3/route_components.proto#config-route-v3-routeaction-hashpolicy-queryparameter

**Comment by hzxuzhonghu** [comment]
Thanks, good to know that. Will be a simple feature.

**Comment by gferreux** [comment]
Nice, thanks for the PRs.
