### ISSUE TITLE
Istio-api build fails PowerPC (ppc64le) architecture

### ISSUE THREAD

**Issue by aishwaryabk** [istio/istio#20792]
Hi,
I am building Istio-api on rhel:7.6 - ppc64le architecture. I have built dependencies Cmake v-3.7.2, git-2.17.1, go v1.13.6, AdoptOpenJDK11, ninja v1.8.2 and bazel v0.25.0. However the build fails :

`ERROR:
Building with the build container: gcr.io/istio-testing/build-tools:master-2020-01-18T00-45-13.
standard_init_linux.go:178: exec user process caused "exec format error"
make: *** [default] Error 1`

Is there a dockerfile for building "istio-testing/build-tools" on PowerPC? Since I had checked on docker hub however it had no such image for Power.

**Comment by ericvn** [comment]
As a work-around you might be able to add a `BUILD_WITH_CONTAINER=0" which will run the build locally.

**Comment by aishwaryabk** [comment]
Yes, that worked. However I am facing another error while running make:

ERROR:
`Building with your local toolchain.
protoc-gen-gogofast: program not found or is not executable
Please specify a program using absolute path or make sure the program is available in your PATH system variable
--gogofast_out: protoc-gen-gogofast: Plugin failed with status code 1.
make[1]: *** [type/v1beta1/selector.pb.go] Error 1
make: *** [default] Error 2`

I have protobuf v3.11.2 installed.

**Comment by ericvn** [comment]
I'm not sure how to configure your local system to satisfy the additional build constraints. That's part of the reason to use the build container, one only needs to install _docker_ and _make_.

**Comment by aishwaryabk** [comment]
I have installed bazel-0.25.0, go-1.13.6, cmake-3.7.2, AdoptOpenJDK11, ninja v1.8.2, protobuf v3.11.2 and docker-1.13.1. GOPATH, GOBIN and PATH variables are also set, however the error remains the same.

**Comment by aishwaryabk** [comment]
> Yes, that worked. However I am facing another error while running make:
> 
> ERROR:
> `Building with your local toolchain. protoc-gen-gogofast: program not found or is not executable Please specify a program using absolute path or make sure the program is available in your PATH system variable --gogofast_out: protoc-gen-gogofast: Plugin failed with status code 1. make[1]: *** [type/v1beta1/selector.pb.go] Error 1 make: *** [default] Error 2`
> 
> I have protobuf v3.11.2 installed.

The above error was solved by cloning gogo/protobuf repository and updating protoc-gen-gogofast dependency. However I am getting another error as follows:

ERROR:
`CONFLICT: "E" is re-using name: "Field1", a reserved field name [protobuf/test/embedconflict/ee.proto]
make[1]: *** [Makefile.core.mk:141: type/v1beta1/selector.pb.go] Error 1
make: *** [Makefile:106: default] Error 2`

**Comment by aishwaryabk** [comment]
> Yes, that worked. However I am facing another error while running make:
> 
> ERROR:
> `Building with your local toolchain. protoc-gen-gogofast: program not found or is not executable Please specify a program using absolute path or make sure the program is available in your PATH system variable --gogofast_out: protoc-gen-gogofast: Plugin failed with status code 1. make[1]: *** [type/v1beta1/selector.pb.go] Error 1 make: *** [default] Error 2`
> 
> I have protobuf v3.11.2 installed.

I ran the following commands due to which I encountered another error.

`bash-4.2# git clone https://github.com/gogo/protobuf`
`Cloning into 'protobuf'..`
`remote: Enumerating objects: 29169, done.`
`remote: Total 29169 (delta 0), reused 0 (delta 0), pack-reused 29169`
`Receiving objects: 100% (29169/29169), 38.86 MiB | 29.28 MiB/s, done.`
`Resolving deltas: 100% (20837/20837), done.`
`bash-4.2# cd protobuf/`
`bash-4.2# go get github.com/gogo/protobuf/protoc-gen-gogofast`
`bash-4.2# cd ..`
`bash-4.2# cd api/`
`bash-4.2# make`
`Building with your local toolchain.`
`protoc-gen-jsonshim: program not found or is not executable`
`Please specify a program using absolute path or make sure the program is available in your PATH system variable`
`--jsonshim_out: protoc-gen-jsonshim: Plugin failed with status code 1.`
`make[1]: *** [Makefile.core.mk:142: type/v1beta1/selector.pb.go] Error 1`
`make: *** [Makefile:106: default] Error 2`

Would like some help on this.

**Comment by aishwaryabk** [comment]
> I'm not sure how to configure your local system to satisfy the additional build constraints. That's part of the reason to use the build container, one only needs to install _docker_ and _make_.

The make command runs fine by updating the packages. Are there any tests that are to be run?

**Comment by ericvn** [comment]
To answer one of your earlier questions, the Dockerile for building build tools can be found at: https://github.com/istio/tools/blob/master/docker/build-tools/Dockerfile

The build tools image is Linux, but should be outputting files into directories under the `out` directory that match you local environment. It also build Linux versions of things in the `out/linux_amd64` directory. It will use those artifacts if it needs to run them as they should be the correct linux for he container.

I did have to make a number of changes when the host was a Mac because of similar `exec format` errors when the container was trying to run files under the darwin directory.  You may have to make sure that things work for powerpc in a similar fashion.

**Comment by aishwaryabk** [comment]
> To answer one of your earlier questions, the Dockerile for building build tools can be found at: https://github.com/istio/tools/blob/master/docker/build-tools/Dockerfile
> 
> The build tools image is Linux, but should be outputting files into directories under the `out` directory that match you local environment (example on my Mac is `out/darwin_amd64). It also builds Linux versions of artifacts in the `out/linux_amd64` directory. It will use those artifacts if it needs to run them as they should be the correct linux for the container.
> 
> I did have to make a number of changes when the host was a Mac because of similar `exec format` errors when the container was trying to run files under the darwin directory. You may have to make sure that things work for powerpc in a similar fashion.

Thanks.

**Comment by howardjohn** [comment]
Lets consolidate into https://github.com/istio/istio/issues/20836, it is hard to track so many split issues. Thanks!
