### ISSUE TITLE
remove manifest/global.yaml in favor of the default profile

### ISSUE THREAD

**Issue by ayj** [istio/istio#20811]
istioctl and the operator use the default profile (default.yaml) for default chart values. They do not use `manifest/global.yaml`.  This duplication leads to maintenance confusion (which file do I update?). global.yaml in its current form may needed by helm, however it could be generated from the default profile values.

**Comment by howardjohn** [comment]
I suggest we do what you mentioned and generate one or the other, so helm will continue to work

**Comment by howardjohn** [comment]
still desired
