### ISSUE TITLE
Galley MVP.

### ISSUE THREAD

**Issue by gjwestlife** [istio/istio#2082]
Galley is the name of the Istio component that will be responsible for config ingestion/management and distribution.

The main tenets for Galley v1 are:
- A stable Galley component that gets deployed as part of Istio
- Act as the main config ingestion point for other components
- Support the current configuration model (i.e. current tooling & CRDs) without any changes
- Minimal impact on Istio v1 glidepath

**Comment by ozevren** [comment]
Adding this for milestone v1 as we'd like to get it in as an alpha component.
