### ISSUE TITLE
Support PowerPC (ppc64le) architecture 

### ISSUE THREAD

**Issue by aishwaryabk** [istio/istio#20836]
Hi,
I was able to build Istio on rhel:7.6/ppc64le by making power specific changes in the Makefile; however it has test failures.

ERROR:
`info	Envoy 'envoy' (epoch 0) starting with command: [/source_root/istio/out/linux_ppc64le/envoy --log-format [ENVOY][%Y-%m-%d %T.%e][%t][%l][%n] %v --config-path /tmp/TestStartTwiceShouldDoNothing899878978/TestStartTwiceShouldDoNothing.json --base-id 31943]
info	Failed freeing BaseID for Envoy 'envoy' (epoch 0): error deleting Envoy base ID 31943 shared memory /dev/shm/envoy_shared_memory_319430: remove /dev/shm/envoy_shared_memory_319430: no such file or directory
info	Envoy 'envoy' (epoch 0) starting with command: [/source_root/istio/out/linux_ppc64le/envoy --log-format [ENVOY][%Y-%m-%d %T.%e][%t][%l][%n] %v --config-path /tmp/TestStartTwiceShouldDoNothing899878978/TestStartTwiceShouldDoNothing.json --base-id 31943]`

`2020-02-12T10:23:45.607260Z     info    Envoy 'envoy' (epoch 0) Aborting: context canceled`
`--- FAIL: TestConfigDump (0.27s)`
    `instance_test.go:411:`
    `    Expected`
         `   <*errors.errorString | 0xc00081e330>: {`
               ` s: "unknown message type \"envoy.admin.v2alpha.BootstrapConfigDump\"",`
      `      }
        to be nil`
`FAIL    istio.io/istio/pkg/envoy        10.222s`

`instance_test.go:408: fork/exec /source_root/istio/out/linux_ppc64le/envoy: exec format error`

Would like some help on understanding the cause for the same . I am running it on a High end VM with good connectivity.

**Comment by howardjohn** [comment]
you need some envoy binary for power pc not sure that exists

**Comment by aishwaryabk** [comment]
I have built ninja-v1.8.2, boringssl, go v1.13.6. I have cloned envoy repository and made power specific changes to its files. Are there any steps to build envoy?

**Comment by junawaneshivani** [comment]
Hi All

I am trying to build istio/proxy on power architecture. I made below changes to the Makefile.
```
diff --git a/Makefile b/Makefile
index c8754ad..c6a0202 100644
--- a/Makefile
+++ b/Makefile
@@ -45,6 +45,8 @@ else ifeq ($(LOCAL_ARCH),aarch64)
     TARGET_ARCH ?= arm64
 else ifeq ($(shell echo $(LOCAL_ARCH) | head -c 4),armv)
     TARGET_ARCH ?= arm
+else ifeq ($(LOCAL_ARCH),ppc64le)
+    TARGET_ARCH ?= ppc64le
```

And then tried to proceed with non-containerized build which is failing for me..

`make BUILD_WITH_CONTAINER=0 build`
```
ang_libcxx", "gcc"]}
INFO: Call stack for the definition of repository 'emscripten_toolchain' which is a http_archive (rule definition at /home/user4/.cache/bazel/_bazel_user4/8177169a1ff0fd69216900ea52964b8c/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
 - /home/user4/.cache/bazel/_bazel_user4/8177169a1ff0fd69216900ea52964b8c/external/envoy_api/bazel/envoy_http_archive.bzl:17:5
 - /home/user4/.cache/bazel/_bazel_user4/8177169a1ff0fd69216900ea52964b8c/external/envoy/bazel/repositories.bzl:16:5
 - /home/user4/.cache/bazel/_bazel_user4/8177169a1ff0fd69216900ea52964b8c/external/envoy/bazel/repositories.bzl:766:5
 - /home/user4/.cache/bazel/_bazel_user4/8177169a1ff0fd69216900ea52964b8c/external/envoy/bazel/repositories.bzl:153:5
 - /home/user4/Shivani/istio/proxy/WORKSPACE:68:1
ERROR: An error occurred during the fetch of repository 'emscripten_toolchain':
   Traceback (most recent call last):
        File "/home/user4/.cache/bazel/_bazel_user4/8177169a1ff0fd69216900ea52964b8c/external/bazel_tools/tools/build_defs/repo/http.bzl", line 83
                patch(ctx)
        File "/home/user4/.cache/bazel/_bazel_user4/8177169a1ff0fd69216900ea52964b8c/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 165, in patch
                fail(<1 more arguments>)
Error applying patch command ./emsdk install 1.39.6-upstream:
Warning: unknown machine architecture ppc64le
```
From the error it looks like emscripten is a dependency not supported on power. But I could not find the code snippet where it is getting downloaded/installed..  Any pointers for this issue may help !

**Comment by sonia-garudi** [comment]
I tried to build istio/proxy on RHEL8 and encountered the same error :
```
$ make -f Makefile.core.mk BUILD_WITH_CONTAINER=0 build
.
.
.
Error applying patch command ./emsdk install 1.39.6-upstream:
Warning: unknown machine architecture ppc64le
Error: 'sdk-releases-upstream-967836071d96d9b7894e492382f5fcb96423fc07-64bit' is only provided for 64-bit OSes.
```
The error is introduced in istio/proxy since it switched from https://github.com/istio/envoy to https://github.com/envoyproxy/envoy-wasm in WORKSPACE. 
```
ENVOY_ORG = "envoyproxy"

ENVOY_REPO = "envoy-wasm"

# To override with local envoy, just pass `--override_repository=envoy=/PATH/TO/ENVOY` to Bazel or
# persist the option in `user.bazelrc`.
http_archive(
    name = "envoy",
    sha256 = ENVOY_SHA256,
    strip_prefix = ENVOY_REPO + "-" + ENVOY_SHA,
    url = "https://github.com/" + ENVOY_ORG + "/" + ENVOY_REPO + "/archive/" + ENVOY_SHA + ".tar.gz",
)
```
This repo has a dependency on https://github.com/emscripten-core/emsdk. emscripten doesn't provide support for power.
istio/proxy provides option to use local envoy instead of pulling for upstream using --override_repository. I built envoyproxy/envoy-wasm locally and used the above flag. However, it still tried to pull from upstream. Any pointers on what command istio/proxy uses to build envoy? Thanks.

**Comment by sonia-garudi** [comment]
I was able to use the local envoy-wasm repository. However, it just uses the code and ends up with same failure as mentioned above. Any pointers will be helpful!
