### ISSUE TITLE
Provision a key and certificate to Prometheus through Istio Agent

### ISSUE THREAD

**Issue by lei-tang** [istio/istio#20831]
**Describe the feature request**
Citadel provisions a key and certificate for Prometheus through a secret mount mechanism. When there is no Citadel file-mounted certificate for Prometheus (e.g., in the environments there is no Citadel), we need a different mechanism to provision a key and certificate for Prometheus. This feature provisions a key and certificate to Prometheus through Istio Agent. The provisioned key and certificate are shared with Prometheus through memory-mount.

**Describe alternatives you've considered**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[X ] Policies and Telemetry
[X ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by incfly** [comment]
https://docs.google.com/document/d/1TTeN4MFmh4aUYYciR4oDBTtJsxl5-T5Tu3m3mGEdSo8/edit#heading=h.tbuedekn7hc6
better take a look

**Comment by incfly** [comment]
Already done via the bypassing sidecar design.
