### ISSUE TITLE
injection version analyzer produces no messages for an old sidecar version when istiod is used

### ISSUE THREAD

**Issue by selmanj** [istio/istio#20858]
**Bug description**
The injection version analyzer is looking for a pod with the name `sidecar-injector-webhook` to determine the sidecar version. This pod won't exist when istiod is in use.

Instead it should look at the MutatingWebhookConfiguration for sidecar injection to determine the pod name to look up.

**Comment by ayj** [comment]
Why does it need the injector pod to get the sidecar version? Shouldn't it look in the injector configmap?

**Comment by selmanj** [comment]
True, solving it via https://github.com/istio/istio/issues/18302 would be a better solution, although it requires parsing templates/injected values (or maybe we could hardcode that logic?). 

The configmap defines the image as:

```
  {{- if contains "/" (annotation .ObjectMeta `sidecar.istio.io/proxyImage` .Values.global.proxy.image) }}
    image: "{{ annotation .ObjectMeta `sidecar.istio.io/proxyImage` .Values.global.proxy.image }}"
  {{- else }}
    image: "{{ .Values.global.hub }}/{{ .Values.global.proxy.image }}:{{ .Values.global.tag }}"
  {{- end }}
```
In the past, we've been discouraged against relying on helm templates. Are we willing to rely on that here, or will that end up being fragile as well?

**Comment by howardjohn** [comment]
You just want the version of the sidecar? how does getting the injector solve that? the only true source of truth for the version is the ISTIO_VERSION environment variable in the proxy image

**Comment by selmanj** [comment]
@howardjohn The analyzer checks to see if any of the sidecar versions differ from what should be injected, as a common issue is a user upgrades their control plane but forgets to redeploy their control plane. Previously we made the assumption that the sidecar version should match the version of the sidecar-injector-webhook. This assumption could break (for example when applying the sidecar.istio.io/proxyImage annotation), but at the time we decided to make this assumption rather than implement a complex solution that parses/understands how the injector works

**Comment by howardjohn** [comment]
Oh so we aren't looking at "version" but rather "image" (technically not the same - but image is right in this case). Doing a reverse lookup from mutatingwebhook will be hard since its a Service there, not a pod, so you would do a double reverse lookup basically. I don't get why you need the pod though, don't you want this? `kubectl -n istio-system get cm istio-sidecar-injector -ojsonpath='{.data.values}' | jq '.global.hub+.global.tag'`

**Comment by selmanj** [comment]
Yeah, that'll work, and that's sorta what I was hinting at with #18302 (although technically #18302 would generate the entire template and warn if any config differs, so it would catch more than just sidecar image).

Note that to correctly do this, we'll have to match the logic of the template I pasted above rather than just append global.hug and global.tag (e.g. consider annotations for the sidecar). In the past we've been reluctant to write analyzers that depend on templates as we've expected these to change, but image/tag seems pretty stable (git history shows that it hasn't changed in the past ten months).
