### ISSUE TITLE
VirtualService Merge Slashes

### ISSUE THREAD

**Issue by armsnyder** [istio/istio#20859]
**Describe the feature request**

I would like for the VirtualService route matching rules to support collapsing/merging multiple slashes. Envoy already supports this in the HttpConnectionManager with the boolean field `merge_slashes`. See here: https://github.com/envoyproxy/envoy/blob/cb0342fe0c302f3f69a5ef18aa62f7d78da3f67b/api/envoy/config/filter/network/http_connection_manager/v2/http_connection_manager.proto#L486

Many webservers do this automatically, and HTTP clients have come to expect the capability. It would be good to support it in Istio.

**Describe alternatives you've considered**

A similar behavior could probably be accomplished using regex route matchers in the VirtualService, but would likely be less efficient and certainly less expressive.

EDIT: Regex matching doesn't work for cases where you want to do a path rewrite because path rewrite is unable to reference regex capture groups.

**Affected product area (please put an X in all that apply)**

[X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by howardjohn** [comment]
This can be configured by a https://istio.io/docs/reference/config/networking/envoy-filter/

**Comment by howardjohn** [comment]
Closing per ^
