### ISSUE TITLE
Ability to run ingress/egress gateways as non-root user

### ISSUE THREAD

**Issue by michaelbannister** [istio/istio#20853]
**Describe the feature request**
The principle of least privilege suggests that it would be more secure to run the ingress/egress gateway containers as a non-root user. Changes have already been made (see #20311) to run control-plane containers as user 1337, but the gateways are a bit more complicated as they want to bind to ports below 1024, so the envoy process would need to be granted the `CAP_NET_BIND_SERVICE` capability if not running as root.

**Additional context**
@rlenglet gave some useful pointers in [this comment on #20311](https://github.com/istio/istio/pull/20311#issuecomment-581204542).

**Comment by dgn** [comment]
Have a look at https://github.com/istio/istio/pull/20838 - you can now set the `targetPort` of the ingress-gateway svc to a port >1023, so you don't need elevated privileges anymore.

**Comment by michaelbannister** [comment]
@dgn that's great! I'm interested that in #20838 you mention "the multi-tenancy work" – is there anything public about this that I could take a look at? My team's considering implementing Istio on a multi-tenant cluster (company internal so not _very_ hard multi-tenancy) and I'm interested in how our current load-balancer-and-nginx-ingress-per-namespace setup might map to deployment(s) of Istio's ingress-gateway…

**Comment by dgn** [comment]
hey @michaelbannister, we implemented soft multi-tenancy (ie multiple, isolated control planes) as part of the [Maistra](https://github.com/maistra) project, which is the open source upstream of [OpenShift Service Mesh](https://www.openshift.com/learn/topics/service-mesh). We're currently in the process of contributing our changes back upstream

**Comment by dgn** [comment]
@michaelbannister This should now work as of https://github.com/istio/istio/pull/23174 - make sure to set the gateway to `runAsRoot: false` like so:

`istioctl manifest apply --set values.gateways.istio-ingressgateway.runAsRoot=false`

**Comment by dgn** [comment]
Closing this as it has been merged to both `master` and `release-1.6`
