### ISSUE TITLE
Stackdriver tracing env variable is malformed

### ISSUE THREAD

**Issue by bianpengyuan** [istio/istio#20851]
After enabling Stackdriver tracer, malformed env variable is injected:
```
    - name: STACKDRIVER_TRACING_MAX_NUMBER_OF_ANNOTATIONS
      value: '&Int64Value{Value:200,XXX_unrecognized:[],}'
    - name: STACKDRIVER_TRACING_MAX_NUMBER_OF_ATTRIBUTES
      value: '&Int64Value{Value:200,XXX_unrecognized:[],}'
    - name: STACKDRIVER_TRACING_MAX_NUMBER_OF_MESSAGE_EVENTS
      value: '&Int64Value{Value:200,XXX_unrecognized:[],}'
```

Seems like it is because injection template https://github.com/istio/istio/blob/4e3cd418a56c328cad553f3ff646d2220ca9d8f3/manifests/istio-control/istio-discovery/files/injection-template.yaml#L300 does not work along with the Stackdriver tracing proto https://github.com/istio/istio/blob/4e3cd418a56c328cad553f3ff646d2220ca9d8f3/pkg/bootstrap/config.go#L287

**Comment by gargnupur** [comment]
@bianpengyuan : Where did you see these values? I am seeing following:
tracing:
  stackdriver:
    debug: true
    maxNumberOfAnnotations: "200"
    maxNumberOfAttributes: "200"
    maxNumberOfMessageEvents: "200"

**Comment by bianpengyuan** [comment]
They are proxy container's env variables.
