### ISSUE TITLE
Upgrade/Downgrade from 1.4 to 1.5 and back

### ISSUE THREAD

**Issue by costinm** [istio/istio#20861]
When attempting to re-deploy 1.4 (assuming something is broken in 1.5, user will need to rollback),
I get:

The CustomResourceDefinition "destinationrules.networking.istio.io" is invalid: status.storedVersions[1]: Invalid value: "v1beta1": must appear in spec.versions

**Comment by jasonwzm** [comment]
@costinm are you following this for the downgrade https://istio.io/docs/setup/upgrade/istioctl-upgrade/ ?

**Comment by jasonwzm** [comment]
fix merged to 1.5. marking it as fixed.
