### ISSUE TITLE
Race condition hit in unit test

### ISSUE THREAD

**Issue by stewartbutler** [istio/istio#20862]
**Bug description**

Hit a data race condition in this test while working on https://github.com/istio/istio/pull/20715: 

https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/20715/unit-tests_istio/8097

It doesn't appear related to my changes, so opening a bug.

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
probably need to shallow copy the list somewhere

**Comment by hzxuzhonghu** [comment]
It is because we pass a pointer of model.PushRequest to the pushqueue, and every proxy share the same pointer, so there is definitely a race when real push in `doSendPushes` is slower than the push reuqest.
