### ISSUE TITLE
istio-init fails at iptables config

### ISSUE THREAD

**Issue by richardwxn** [istio/istio#20863]
The perf benchmark pipeline failed for last two days when deploying fortio, checked the istio-init container log for fortio pod and found this error. It is using the latest master.

error log:
```
iptables-restore --noflush --table=mangle --table=nat /tmp/iptables-rules-1580868424640193215.txt100769180
iptables-save --table=mangle --table=nat
panic: fork/exec /sbin/iptables-restore: errno 0

goroutine 1 [running]:
istio.io/istio/tools/istio-iptables/pkg/dependencies.(*RealDependencies).RunOrFail(0xd819c0, 0x9739cb, 0x10, 0xc0000b2ec0, 0x4, 0x4)
	istio.io/istio@/tools/istio-iptables/pkg/dependencies/implementation.go:58 +0x96
istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).executeIptablesRestoreCommand(0xc000137d30, 0x7f62de722001, 0x0, 0x0)
	istio.io/istio@/tools/istio-iptables/pkg/cmd/run.go:483 +0x3c1
istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).executeCommands(0xc000137d30)
	istio.io/istio@/tools/istio-iptables/pkg/cmd/run.go:498 +0x45
istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).run(0xc000137d30)
	istio.io/istio@/tools/istio-iptables/pkg/cmd/run.go:438 +0x24e2
istio.io/istio/tools/istio-iptables/pkg/cmd.glob..func1(0xd5c740, 0xc000028800, 0x0, 0x10)
	istio.io/istio@/tools/istio-iptables/pkg/cmd/root.go:56 +0x14e
github.com/spf13/cobra.(*Command).execute(0xd5c740, 0xc00001e130, 0x10, 0x11, 0xd5c740, 0xc00001e130)
	github.com/spf13/cobra@v0.0.5/command.go:830 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0xd5c740, 0x40574f, 0xc0000c8058, 0x0)
	github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v0.0.5/command.go:864
istio.io/istio/tools/istio-iptables/pkg/cmd.Execute()
	istio.io/istio@/tools/istio-iptables/pkg/cmd/root.go:284 +0x2d
main.main()
	istio.io/istio@/tools/istio-iptables/main.go:22 +0x20
```

**Comment by howardjohn** [comment]
we found this yesterday, Romain is working on a fix. We use gke for this Romain

**Comment by rlenglet** [comment]
For the record, this happens when the worker node's filesystem doesn't support xattrs / capabilities.
The fix will be to make running with UID 0 the default, and make running with UID 1337 optional with a flag.

**Comment by dgn** [comment]
I created a revert PR (https://github.com/istio/istio/pull/20872) for now

**Comment by sdake** [comment]
@rlenglet 

The binary setpcap should never be used in any dockerfile, ever. It is not portable as xattrs are different among different filesystems and even the same filesystem is different among different distros are incompatible. Complicating matters,  xattrs can even be incompatible between different versions of the same filesystem. This most often appears as if you create this image on Ubuntu, and run it on CentOS, it will implode. Visa-versa is also the same deal.

I have previously left this comment several times in these 1337/revert/1337/revert PRs that have happened multiple times. Seems like it was used again: https://github.com/istio/istio/pull/20872/files#diff-9c2395ac0f2d29083a562d83f28cc3c4L39

There are two options.
- passwordless sudo
- A different (less secure) approach is to use a tool such as `su-exec`.

Neither option is great, although `setpcap` and friends should just be considered a non-starter - independent of whatever configuration flags are used.

Please avoid the use of filesystem capabilities in Dockerfiles in the fut-ure.

Cheers
-steve

**Comment by howardjohn** [comment]
fixed

**Comment by howardjohn** [comment]
by a revert
