### ISSUE TITLE
kubernetes istio 15s timeout 

### ISSUE THREAD

**Issue by johangyu** [istio/istio#20869]
version : istio-1.3.5 
install :  kubectl create -f istio-1.3.5/install/kubernetes/istio-demo.yaml

There is a pod for httpproxy in Kubernetes, and when called with service of this pod
External-> kubernetes Service-> Pod-> External routing.

It seems that it takes 15s timeout at the pod-> external routed outside, and this external service is only accessible by ip.

For example, when calling 
curl http: // kubernetesmaster:serviceport/alivecheck from the outside, 

For pod internal container, we route to http://172.11.111.111/alivecheck using proxyHTTP (url) .ServeHTTP (res, req) which is a feature of golang echo framework.

Please help me how to configure serviceentry and virtualserver in this case.

example:
https://archive.istio.io/v1.3/docs/reference/config/networking/v1alpha3/virtual-service/

All documentation is explained in dns only.
Explain how to go to ip instead of dns

thanks

**Comment by howardjohn** [comment]
you can create a service entry for the ip and route to that. or turn on ALLOW_ANY mode and it should just work

**Comment by johangyu** [comment]
container -> http://172.11.111.111/alivecheck is timerate 16s  -> status 504 error
container -> http://172.11.111.111/alibecheck2 is timerate 10s  -> status 200 

I don't know how to configure serviceentry.
Here is my setup

apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-svc-test
spec:
  hosts:
  - gogate.service 
  addresses:
  - 172.11.111.111/24 
  ports:
  - number: 80
    name: http
    protocol: HTTP
  location: MESH_EXTERNAL
  resolution: STATIC
  endpoints:
  - address: 172.11.111.111

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: gogate-vs-external
spec:
  hosts:
  - gogate.service
  http:
  - timeout: 5s
    route:
    - destination:
        host: gogate.service

The result I want is alivecheck2 takes 10 seconds
Since we added timeout 5s
It should be 504. But 200 is rising
My setup is wrong.

Also I want to configure status 200 even after 60 seconds.
The final form I want is this: 
container -> http://172.11.111.111/alivecheck is timerate 61s  -> status 504 error
container -> http://172.11.111.111/alivecheck is timerate 59s  -> status 200
