### ISSUE TITLE
Overrides are broken in the operator

### ISSUE THREAD

**Issue by dgn** [istio/istio#20875]
The way we're currently doing overrides wrt legacy helm API vs. new IOP API is very confusing. For example, we disable most components explicitly in the helm part of `default.yaml` (which always takes precedence), so in order to enable components, we have to enable them both in the new and in the old API (if you look at our profiles, we're doing that everywhere).

I'd say it's counter-intuitive to force our users to set `enabled: true` in both parts of the YAML. We should either:

- Make the new API override the old one, always or
- Not explicitly set `enabled: false` in the old API fields of the profiles. That way, users can enable them using just the new API

**Comment by richardwxn** [comment]
For enablement, user can specify override in either legacy helm API or IOP API, it is essentially the same. I don't think we are doing that in both places in default profile, core component enablement defined only in IOP and addon components defined only in helm path.

I think for your suggestion, we can move the addon enablement path from the helm API part to IOP. 

Also for some other shared parts between helm API and IOP API(namespace, k8s settings), we should all move it to IOP for consistency.

**Comment by richardwxn** [comment]
this PR cleaned up the enablement part for addons in default profile: https://github.com/istio/istio/pull/20947

**Comment by dgn** [comment]
> this PR cleaned up the enablement part for addons in default profile: #20947

Thank you, that's a good start
