### ISSUE TITLE
Recent commit [Run istio-init with non-root UID #20380] does not build on OSX Mohave 10.14.6 (darwin). 

### ISSUE THREAD

**Issue by JonBergevin** [istio/istio#20878]
**Bug description**
We have been looking into Mixer Out Of Process Adapter in the hopes of building a custom one, following this guide:
https://github.com/istio/istio/wiki/Mixer-Out-Of-Process-Adapter-Walkthrough#before-you-start

Using `make mixs` command from the `before-you-start` section of the document above, after cloning the repository produces build error (Error 2) on MacOS. We were able to build mixs prior to this commit.  

Looks like there is a revert PR in the queue of open PR's. 
https://github.com/istio/istio/pull/20872

**Expected behavior**
`make mixs` builds without error.

**Steps to reproduce the bug**
I am running `go version go1.13.7 darwin/amd64`

`git clone https://github.com/istio/istio && cd istio && make mixs`
produces this error:
`tools/istio-iptables/pkg/dependencies/implementation.go:41:3: unknown field 'AmbientCaps' in struct literal of type syscall.SysProcAttr`

**How was Istio installed?**
Cloned the repository.

**Environment where bug was observed (cloud vendor, OS, etc)**
local machine

This page: https://golang.org/pkg/syscall/#SysProcAttr
Indicates that golang using AmbientCaps in SysProcAttr is only supported on Linux.

We were able to build prior to this commit from 2/3/2020 by @rlenglet 
https://github.com/istio/istio/commit/0996b80fd41dc9ac92e6d2129a78a83c68aff76a

From what I can see, golang for darwin, won't support the AmbientCaps struct in 
`tools/istio-iptables/pkg/dependencies/implementation.go`

**Full error information**
`Building with the build container: gcr.io/istio-testing/build-tools:master-2020-01-30T23-36-53.Using docker credential directory /Users/jonbergevin/.docker.Using local Kubernetes configuration /Users/jonbergevin/.kubemkdir -p /work/out/darwin_amd64/logsmkdir -p /work/out/darwin_amd64/releaseSTATIC=0 GOOS=darwin GOARCH=amd64 LDFLAGS='-extldflags -static -s -w' common/scripts/gobuild.sh /work/out/darwin_amd64/ ./istioctl/cmd/istioctl ./pilot/cmd/pilot-discovery ./pilot/cmd/pilot-agent ./sidecar-injector/cmd/sidecar-injector ./mixer/cmd/mixs ./mixer/cmd/mixc ./mixer/tools/mixgen ./galley/cmd/galley ./security/cmd/node_agent ./security/cmd/node_agent_k8s ./security/cmd/istio_ca ./security/tools/sdsclient ./pkg/test/echo/cmd/client ./pkg/test/echo/cmd/server ./mixer/test/policybackend ./tools/istio-iptables ./tools/istio-clean-iptables ./operator/cmd/operator# istio.io/istio/tools/istio-iptables/pkg/dependenciestools/istio-iptables/pkg/dependencies/implementation.go:41:3: unknown field 'AmbientCaps' in struct literal of type syscall.SysProcAttrreal	0m5.568suser	0m3.529ssys	0m3.965sMakefile.core.mk:289: recipe for target 'build' failedmake: *** [build] Error 2`

**Comment by ericvn** [comment]
You no longer need `Golang` installed since that's now in the build container.

I just pulled the latest from `master`, 9af5f511459cbb4151cb0ecb369f04543a966572, did a `make clean` followed by the `make mixs` on my Mac and this failed as well.

**Comment by ericvn** [comment]
@rlenglet It looks like you added `AmbientCaps` which is not part of the Darwin **SysProcAttr**

**Comment by ericvn** [comment]
After the change was reverted, I tried this again and things are working.

@howardjohn Didn't we recently have a Mac build as part of the pipeline? I recall some of this was removed recently. I'm thinking it might have caught the original change going in.

**Comment by howardjohn** [comment]
to be fair this change broke on almost every platform including gke. But I am not sure if we had Mac, we do have it for the proxy repo

**Comment by howardjohn** [comment]
working now with https://github.com/istio/istio/pull/20872
