### ISSUE TITLE
Create a new istioctl subcommand to produce control plane configuration by feature

### ISSUE THREAD

**Issue by ZackButcher** [istio/istio#2087]
We want a new subcommand on `istioctl` responsible for producing control plane configuration. This command should accept a flag that describes the set of Istio features the user wants (e.g. "auth", or "ingress,routing") and produces the (minimum) set of k8s deployments of the Istio control plane to achieve those features.

Then we can shift to using this tool to produce all of the yamls we package up in the Istio installation bundle, instead of the scripts we use to produce it today.

**Comment by ayj** [comment]
There's also been some suggestion to use Helm instead of scripts to generate install files. See https://github.com/istio/istio/pull/2030#issuecomment-350807429.

**Comment by kyessenov** [comment]
Cc @andraxylia who was strongly against this back in summer

**Comment by andraxylia** [comment]
I am not convinced this functionality belongs to istioctl

**Comment by andraxylia** [comment]
Istoctl is a config client to the config store, not a script for install. Please create a separate tool or let's use helm if it already supports. We do need the ability to customize installation profiles.

**Comment by ZackButcher** [comment]
`istioctl` is how the user interacts with Istio. The fact that today that only occurs via writing config is an implementation detail. It's a pretty horrendously bad UX to say "download `foobar` to generate the control plane configuration you want, then download `istioctl` to configure it".

I'm happy having such a command generate the variables required for the helm install, but until we have a blessed installation method, the same tool should be able to generate raw deployments too.

**Comment by costinm** [comment]
Istioctl is one way user interacts with Istio - kubectl is another, so is
using the k8s APIs from custom programs.

Istioctl is not a required for using Istio - nor should it be, most users
will use the webhooks for injection and a real
UI for configuration (and the UI will not exec istioctl ).

Helm and launcher are using templates and are checked in - not generated by
tools, I'm not aware of any other
application that is using an executable to generate configs for helm.

**Comment by ZackButcher** [comment]
In the helm case, what we'd generate is the `values.yaml` file required to fill in helm template parameters. Helm would still be responsible for rendering the final configuration.

**Comment by costinm** [comment]
So instead of user editing a values.yaml ( with comments around each
parameter ), or using a UI that presents the options in a
nice way - they would run a native CLI ? Is it based on user feedback, and
do we expect most users will like CLI instead
of config files or UI for Istio ?

**Comment by costinm** [comment]
Also we are moving to per-service / per-namespace config - for example mTLS
already has per-service settings. Would
the per-service config use istioctl ( with kube-inject like behavior ) ? Or
different ways for service, namespace and global config
of same setting ?

**Comment by ldemailly** [comment]
istioctl would be a lot more convenient than nothing at all - specially to switch between the many options we have

**Comment by andraxylia** [comment]
If the alternative is nothing at all, istioctl is of course preferable. Go ahead and add it, it can always be split later once we have a better understanding.

**Comment by smawson** [comment]
Is there a strawman of the devex we want?  What is the proposed set of "features" the user can enable/disable? I care about the experience more than the underlying code :)

**Comment by ZackButcher** [comment]
@smawson today the features are: "mtls", "telemetry", "routing", "ingress", "policy", "initializer". Final names TBD, we want them to match the names used in the APIs.

The experience I'm shooting for is something like:
```sh
kubectl apply -f <(istioctl gen-deployment --features telemetry,initializer)
```

@costinm has been pushing for a more file-based approach, where the user edits the Helm chart's `values.yaml` file, and we use that to render YAML in the tool. It looks something like:
```sh
kubectl apply -f <(istioctl gen-deployment --values path/to/values.yaml)
```

The current WIP PR supports both flags and `values.yaml`.

Finally, we can produce a `values.yaml` file based on flags, which can then be used by the tool to render final YAML, or fed to Helm directly:
```sh
istioctl gen-deployment --features mtls,routing -o helm
```

**Comment by smawson** [comment]
Some questions:
1) Does telemetry include installing prometheus, grafana, and service graph?
2) Does mtls turn on mtls, or just make it available (and rolling it out is separate)
3) Do we actually want to make initializer optional or instead just configure which namespaces to roll it out to?
4) Should we have a command that generates the deployment and installs? istioctl install --values path/to/values.yaml. If we have that, is there any difference between doing it that way vs. just using helm directly?  Maybe we hide helm and have it be istioctl install --config path/to/config.yaml where config.yaml doesn't leak helm details (maybe existing values.yaml doesn't either?).

**Comment by ZackButcher** [comment]
1. As yet I have not touched the addon files, so no not yet. We should decide if we want that or not. The other option would be to add "prometheus", "grafana", etc "features".
2. Creates a deployment containing a CA and enables mTLS
3. The initializer still requires a non-standard k8s cluster to work so I've kept it off by default. AFAIK @louiscryan was in favor of on-by-default.
4. By default we spit out regular old k8s deployments, which we get by rendering our helm charts locally in the CLI. The biggest difference is that we don't require an actual helm server to be running, because Istio templates are simple enough for us to totally render on the client side. I'm not sure how feasible it is to hide helm details. I will be trying to make the `values.yaml` higher level than it is today, though (so it talks in terms of features too, [rather than individual components like it does today](https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/values.yaml)).

**Comment by kyessenov** [comment]
my 2c: it would be great to have telemetry and routing by default. Routing IMHO is a pre-requisite for everything else (not rules, just basic sidecar + pilot). It's a short step to Envoy-based telemetry from there.

**Comment by ZackButcher** [comment]
That's the plan: by default the tool spits out deployments for the entire control plane, ingress proxies, and enables mTLS.

**Comment by kyessenov** [comment]
If we want to expose helm templates, I think it would be best to advise to use helmc itself with its large and evolving plugin eco-system. Certain things, like helm generate or helm ksonnet, are best left to helm to implement.

If we want to encapsulate helm templates, then we should capture enough variation with tool flags, and be ready to extend as many as flags as needed to customize those templates.

**Comment by kyessenov** [comment]
mTLS is a separate feature. It's disruptive to the rest of the cluster since you cannot communicate with non-istio pods.

**Comment by ZackButcher** [comment]
Sure - none of the code is checked in so feel free to comment in the PR about what the defaults actually should be. I think it'd be very reasonable to have mTLS off by default too.

**Comment by kyessenov** [comment]
We need CA even with mTLS is off to secure sidecar-pilot channel. So the
only optional pieces are mixer, ingress, and any mixer addons/plugins.

**Comment by ZackButcher** [comment]
AFAIK communication works fine without CA, we just wind up with clear-text between sidecars and Pilot, so it's not strictly required, right?

**Comment by kyessenov** [comment]
It's required (non-optional). Otherwise, we need to have another set of installation templates.

**Comment by ZackButcher** [comment]
@louiscryan @smawson thoughts on supporting an installation that's clear text between side cars and Pilot for a smaller install footprint in use cases where the operator doesn't want/need other Istio security features?

IMO we make the "Istio is a monolith" perception worse as we add tight couplings like "you must run CA to run Pilot".

**Comment by kyessenov** [comment]
I think Mixer should definitely require CA and probably mTLS for any
reasonably safe policy enforcement.
Depending how much we value trust between proxy/pilot, we should be careful
to make it plain-text.

To avoid monolith perception, we should look into using k8s CA instead of
shipping our own CA, or using network isolation using co-deployed pilot or
UDS.

**Comment by ZackButcher** [comment]
Again, it's not strictly required - we just think it's the correct default based on the security model we work in (that the network is compromised). Many users have different security models (for better or worse) that assume the network is safe, so in their mind mTLS between side-cars and Mixer is not strictly required.

We need to be very clear about the difference between the minimum viable deployment (e.g. Mixer w/o CA, clear text between sidecars and control plane), the default deployment we ship, and the deployment we recommend users run (IMO the default should be the recommended deployment).

**Comment by smawson** [comment]
re: enabling mtls, we should have mtls off by default, not on by default, since it is dangerous to deploy into existing cluster (will break live traffic). mtls to pilot and mixer seems reasonable. So what we really want is the default state to be auth is installed and ready, but the default is that it is off for all services, and explicitly enabled for pilot and mixer services.

I think it is _reasonable_ to offer a mode where there is no auth installed at all, and pilot/mixer traffic are unsecured, but that shouldn't be the default.

re: installation, not sure I got an answer to whether we could offer: istioctl install --config path/to/config.yaml, which would generate the deployments and also call kubectl to install them.

Sure you can do it with a kubectl apply -f (...) but nice if we offered a simpler one-liner.

Oh we should also figure out how to make it clear that this is a kubernetes install, so something like gen-kube-deployment and install-kube rather than gen-deployment and install, since we'll also want to offer installation for other environments, ideally using the same configuration file.

**Comment by ldemailly** [comment]
I believe we have or soon will have mtls “preferred” mode so we should ship that way rather than without mtls (preferred means try mtls and fallback if it doesn’t work)

**Comment by yusuoh** [comment]
+1 for using gen-kube-deployment for this new subcommand as it is specific to Kubenetes environment. 

For installation, we should have a install sub-command which is more general, which can directly install the system onto different environments.

**Comment by ZackButcher** [comment]
> re: installation, not sure I got an answer to whether we could offer: istioctl install --config path/to/config.yaml, which would generate the deployments and also call kubectl to install them.

Ah, I didn't understand that's what you were asking for. Yes, we can do that, and I think that's where we introduce the stuff @yusuoh's been thinking about.

> +1 for using gen-kube-deployment for this new subcommand as it is specific to Kubenetes environment.
>
> For installation, we should have a install sub-command which is more general, which can directly install the system onto different environments.

Do we expect to support more than just Kubernetes? If so, lets structure the tool so that each platform is a subcommand, i.e. `istioctl gen-deploy kube`. That structure works more nicely if we pull out `gen-deploy` into its own binary, and I think makes a nice code structure too (e.g. Istio wide flags on the `gen-deploy` command and kubernetes specific flags on the `kube` subcommand, etc).

**Comment by ZackButcher** [comment]
And `install` can mirror the same structure, `istioctl install kube ...` (which is convenient for all the same reasons as `gen-deploy`).

**Comment by ZackButcher** [comment]
So to summarize so for:

- [ ] Structure command as `istioctl gen-deploy kube`
- [ ] Command for installation will be `istioctl install`
        - @yusuoh can you file an issue for this? IMO it's important these are two separate things, and we not conflate generating deployments with the logistics of figuring out how to do upgrades etc. in the same place.
- [ ] Default installation (`istioctl gen-deploy kube`, no flags) will generate a deployment with the full control plane, ingress proxies, no initializer, and mTLS disabled. This mirrors the main `istio.yaml` Kube install we have today.
- [ ] We can add configs to support simpler minimum deployments (e.g. clear-text control plane so routing can be achieved with only Pilot and sidecars, etc.)
        - I think this is desirable but not really important in the short term. As I'm refactoring the helm charts to align with our existing templates, I keep an eye on making this easy, but not go out of my way to write extra config to allow it.

**Comment by cmluciano** [comment]
@ZackButcher will your gen-deploy also generate sidecar deployment files?

**Comment by ZackButcher** [comment]
Don't plan to since we have `kube-inject`; we only use the proxy version here for the proxies that run in front of the control plane, and in configuring the initializer.

**Comment by costinm** [comment]
You may want to sync with Jason and the people working on 'template based
injection', for consistency (including on using the same
input file and naming).

Few comments on mtls:  right now (0.4) mtls is installed by default and is
used for pilot/mixer, and any app with the right annotation,
and for 1.0 if the P1 'transparent mtls' is implemented it will be in
'enforce' or 'allow' mode.

It is no longer 'off' or 'on', and we certainly don't want to ship an
'always on'/enforce mode until we solve the headless use case.
In addition the 'zero-vpn' requires mtls (can be in permissive mode),
currently there is no option (or plan) to allow zero-vpn without
crypto.

Finally - some of the options for zero-vpn using 3p gateway termination
will not actually use mtls - but plain tls with JWT for client(mutual) auth.
I'm not sure if what Quic uses can be called mtls either - my point is I'm
not sure if the term is future-proof.

**Comment by sdake** [comment]
Just a quick clarification on Helm functionality after reading through this issue.  There may be a misunderstanding in this issue tracker that to modify helm configuration options, one must modify the `values.yaml` file and rebuild the chart.

While that mechanism works, the preferred method is to use `--set` or `--values` flags to helm install.

e.g.::
`helm install istio -name istio --set istio.ingress.usenodeport=true`

while `--set` overrides the defaults (provided by `values.yaml`).  The other runtime configuration option is called `--values` which takes a YAML file and overrides multiple options.

**Comment by ZackButcher** [comment]
The goal with Helm is that we can do:
`helm install istio -name istio --values <(istioctl gen-deploy --features foo,bar --out helm)`

We shouldn't need to write the `values.yaml` do disk or rebuild the chart, it should all work at runtime.

**Comment by costinm** [comment]
The feature seems to be done - however the feature and helm part are not working and don't appear to be needed, the helm templates already have a feature system in place ( with --set), and values.yaml need to be updated.

We will need additional polish and testing - and since helm and gen-deploy are the only good way
to customize production settings I think this is a (top) P1.

**Comment by yusuoh** [comment]
For the webhook auto-inject feature, which involves cert creation and bundling CA to the template, can they also be supported by Helm? It seems easier to do those in istioctl.

**Comment by sdake** [comment]
@yusuoh this is a good question to which I don't have a good answer.  The helm charts today can deploy the sidecar-injector pod, however, the workflow on this page (under automatic injection):

https://istio.io/docs/setup/kubernetes/sidecar-injection.html

seem incomplete.  I'm not sure helm has sufficient workflow features to execute this work, although it may be possible to put that specific workflow in a bare-bones container, the purpose of which is to configure the sidecar injection, or as you note - use istioctl directly to execute these more complex workflows.

Cheers
-steve

**Comment by costinm** [comment]
I think best place to put this istio-ca - which can generate certificates and has proper permissions.

I wouldn't add another component that signs certs. 

I will file a separate bug for this.
