### ISSUE TITLE
Customizing the configuration in istio is replacing previous state

### ISSUE THREAD

**Issue by pawanyoda** [istio/istio#20871]
**Bug description**
I have installed Istio through manifest and if I adding a new feature on Istio and it is removing the previous one. Like I have installed Grafana and jaeger after that I have added Zipkin and its removing Grafana and Jaeger. If I adding again jaeger, Grafana its removing Zipkin or sometimes both Zipkin and Jaeger are not working.

[X ] Configuration Infrastructure
[ ] Docs
[ X] Installation
[ X] Networking
[ X] Performance and Scalability
[X ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ X] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**
`istioctl dashboard jaeger`
Error: no Jaeger pods found
`istioctl dashboard zipkin`
Error: no Zipkin pods found

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
 `istioctl version --remote` :`client version: 1.4.3, control plane version: 1.4.3, data plane version: 1.4.3 (21 proxies)`
`kubectl version`: `Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-15T15:50:38Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-c0eccc", GitCommit:"c0eccca51d70b3b2f163dd8d534ffeb2f7a2", GitTreeState:"clean", BuildDate:"2019-12-22T23:14:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}`
`helm version` : `version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}`

**How was Istio installed?**
`istioctl manifest apply --set profile=default --set values.global.disablePolicyChecks=false --set values.kiali.enabled=true --set values.grafana.enabled=true --set values.tracing.enabled=true --set "values.kiali.dashboard.jaegerURL=http://jaeger-query:16686"  --set "values.kiali.dashboard.grafanaURL=http://grafana:3000" --set values.pilot.traceSampling=100 --set values.global.proxy.tracer="lightstep"  --set values.global.tracer.lightstep.address="collector-grpc.lightstep.com:443" --set values.global.tracer.lightstep.accessToken="#######2242jDKG" --set values.global.tracer.lightstep.secure=true --set values.global.tracer.lightstep.cacertPath="/etc/lightstep/cacert.pem"`

**Environment where bug was observed (cloud vendor, OS, etc)**
**AWS EKS**

**Comment by howardjohn** [comment]
you have to pass all the config to istioctl at once or it will remove stuff no longer desired. You maybe prefer to use a config file with -f since you have do many settings

**Comment by howardjohn** [comment]
This is working as expected
