### ISSUE TITLE
Node agent process still exists when istio-auth-node-agent.service has been stopped

### ISSUE THREAD

**Issue by ingvar-goryainov** [istio/istio#20895]
After istio-auth-node-agent.service has been stopped and the service is inactive, Node agent process is still running.
helm version - 2.14.2
istio version - 1.3.8
Istio was installed by Helm chart

**Comment by irisdingbj** [comment]
in Istio 1.5, we have removed istio-auth-node-agent.service.

**Comment by howardjohn** [comment]
Closing as this is no longer applicable
