### ISSUE TITLE
istioctl analyze shows EnvoyFilter errors

### ISSUE THREAD

**Issue by rvennam** [istio/istio#20896]
```
~/istio-1.4.3 🏎  $ istioctl x analyze --use-kube
Error [IST0106] (EnvoyFilter tcp-stats-filter-1.5.default) Schema validation error: Envoy filter: unknown message type "udpa.type.v1.TypedStruct"
Error [IST0106] (EnvoyFilter tcp-stats-filter-1.5.default) Schema validation error: Envoy filter: unknown message type "udpa.type.v1.TypedStruct"
Error [IST0106] (EnvoyFilter tcp-stats-filter-1.5.default) Schema validation error: Envoy filter: unknown message type "udpa.type.v1.TypedStruct"
Warn [IST0102] (Namespace default) The namespace is not enabled for Istio injection. Run 'kubectl label namespace default istio-injection=enabled' to enable it, or 'kubectl label namespace default istio-injection=disabled' to explicitly mark it as not needing injection
Error: Analyzer found issues.
```

**Bug description**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ X ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
I do not expect to see any errors

**Steps to reproduce the bug**
Run `istioctl x analyze --use-kube` with 1.4.3 Istio

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
client version: 1.4.3
control plane version: 1.4.3
data plane version: 1.4.3 (5 proxies)

**How was Istio installed?**
Managed Istio on IKS

**Environment where bug was observed (cloud vendor, OS, etc)**
IKS

**Comment by howardjohn** [comment]
How did you get a 1.5 envoy filters in 1.4 cluster?

**Comment by rvennam** [comment]
user error - contamination from an old install. Thanks
