### ISSUE TITLE
"istioctl describe" does not detect client/server mismatch

### ISSUE THREAD

**Issue by esnible** [istio/istio#20898]
"istioctl describe" MUST report a problem if the server is STRICT and the client speaks HTTP.  However, `describe` feels the client protocol is merely "unspecified".

```
$ istioctl x describe pod productpage-v1-5d67f9c9f7-wzj8k
Pod: productpage-v1-5d67f9c9f7-wzj8k
   Pod Ports: 9080 (productpage), 15090 (istio-proxy)
--------------------
Service: productpage
   Port: http 9080/HTTP targets pod port 9080
Pod is STRICT, client protocol unspecified
```

auto mTLS is off:

```
kubectl -n istio-system get configmap istio -o jsonpath="{.data.mesh}" | grep enableAutoMtls
enableAutoMtls: false
```

The problem seems to be that Pilot's /debug/authenticationz endpoint is reporting clients as `-`, not `HTTP`.  The tool thought this meant auto mTLS, but it doesn't always mean that.

cc @rvennam @GregHanson

**Comment by esnible** [comment]
In addition, if the server speaks only HTTP, we will see `Pod is DISABLE, client protocol unspecified`.

The meaning are given in _destination_rule.pb.go_, and DISABLE means no TLS.  The output of `describe` should make that readable.

**Comment by esnible** [comment]
https://github.com/istio/istio/pull/21268 will provide Pilot with the ability to detect the problem.  Once that merges a follow-up to istioctl will be needed.

**Comment by esnible** [comment]
The PR will have this logic:

If client is `None`, and status is `OK` @GregHanson says
PERMISSIVE case, status=OK and since there is no destination rule saying otherwise, client will attempt to use HTTP
STRICT case: if automtls=false and no DR, traffic should be istioMTLS by default (edited)

**Comment by GregHanson** [comment]
>STRICT case: if automtls=false and no DR, traffic should be istioMTLS by default (edited)

to clarify, in the case of `--set values.global.mtls.enabled=true --set values.global.mtls.auto=false` there is still a global destination rule

```
$ ix describe pod productpage-v1-85b9bf9cd7-xk8w5
Pod: productpage-v1-85b9bf9cd7-xk8w5
   Pod Ports: 9080 (productpage), 15090 (istio-proxy)
--------------------
Service: productpage
   Port: http 9080/HTTP targets pod port 9080
DestinationRule: default.istio-system for "*.local"
   Traffic Policy TLS Mode: ISTIO_MUTUAL
Pod is STRICT and clients are ISTIO_MUTUAL
```

**Comment by esnible** [comment]
Currently the tool expects Pilot to tell us if there is a client/server mismatch.

Pilot gets it wrong sometimes ( https://github.com/istio/istio/issues/21821 ).  I prefer to fix Pilot rather than introducing compensating logic in istioctl.
