### ISSUE TITLE
istio/tools: make perf pipeline stable

### ISSUE THREAD

**Issue by carolynhu** [istio/istio#20907]
Currently, out perf pipeline is not stable. We need to decoupling it from boskos for easier to debug and handle cluster related changes.

**Comment by howardjohn** [comment]
Why do you think boskos is the issue? It seems to work fine for Kubernetes, they do load testing on boskos

**Comment by carolynhu** [comment]
the title may not be that much good, yeah, there are lots of reasons cause perf pipeline not stable today. I just want to make the tests running on my own cluster for debugging purpose, since it's gonna under our own control.
