### ISSUE TITLE
New Performance Benchmark Testing Framework

### ISSUE THREAD

**Issue by richardwxn** [istio/istio#20908]
TODO tasks include:

For refactoring existing perf framework (@richardwxn @carolynhu )
- [x] 1. Refactor the benchmark script to be more modular and less hacky 
- [ ] 2. Create templates and different overlay values.yaml for runtime config 
- [x] 3. Refactor the config file format and directory structure 

For running time reductions and stability:
- [ ] 4. Investigate running multiple tests concurrently in different namespace @carolynhu 
- [ ] 5. Make each test with different configs of the same branch independent. @richardwxn 

Others:
- [ ] 6. control plane tests @richardwxn @carolynhu

**Comment by carolynhu** [comment]
@richardwxn i'm not taking over the refactoring and running in multiple namespace thing. just letting you know.
