### ISSUE TITLE
Using Istio on Terraformed kubernetes_replication_controller

### ISSUE THREAD

**Issue by crisarceramos** [istio/istio#2092]
Is it possible to use Istio on terraform-kubernetes resources like kubernetes_replication_controller? 
Example is we deploy containers via terraform kubernetes_replication_controller. 
Thanks.

**Comment by linsun** [comment]
should be transparent to you if you use automatic side car injection.  If you use manual injection, you may need to write a small terraform resource adapter to do the proxy side car injection.

**Comment by crisarceramos** [comment]
@linsun thanks for your reply. we tried terraform apply and it's not injecting the sidecard with auto-injection enabled. it works with kubectl, but not via terraform. 
:(

**Comment by crisarceramos** [comment]
i think i know the reason it's not working. terraform is directly using the K8S api lib and not kubectl. I think Istio is intercepting request from Kubectl that's why.

**Comment by ayj** [comment]
Automatic injection is server-side. The use of kubectl vs. k8s api-lib shouldn't affect the behavior.  Replication-controller directly is not directly supported with current initializer. We plan to switch to pod-level injection soon which should address this problem. See https://docs.google.com/document/d/1f61uHoPvozoVhlut6TG66L2XQ_DvFQWUUeFjHJeypHQ/edit#bookmark=id.r9vnshs9e4w2.

**Comment by ayj** [comment]
Automatic sidecar injection supports pod-level injection. *all* pods, regardless of the controller, should have the sidecar injected if the webhook namespace scope and injection policy allows for it.
