### ISSUE TITLE
discoveryAddress = 15010 causes pilot to generate config for file mounts, not SDS

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#20924]
Pass `--discoveryAddress="istio-pilot.istio-system.svc:15010"` and you will end up with rejected configs because pilot sends config for file mounted.

Not 100% sure if we want/need to support plaintext going forward?

**Comment by myidpt** [comment]
John to check if it's fixed :)

**Comment by howardjohn** [comment]
verified this is fixed
