### ISSUE TITLE
DNS type Cluster with no endpoint will block Envoy init

### ISSUE THREAD

**Issue by ydh926** [istio/istio#20933]
**Bug description**
strict_dns cluster with no endpoints will block envoy,
see 
https://github.com/envoyproxy/envoy/issues/9963

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Steps to reproduce the bug**
1. create a serviceentry with stict_dns type
2. create a destinationrule for the se, but it cannot selector any endpoint
3. restart pilot, then pilot cannot recive cds or lds from envoy, for envoy has been block 

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by ydh926** [comment]
we should ignore cluster with no endpoint here:
```
	if discoveryType == apiv2.Cluster_STATIC || discoveryType == apiv2.Cluster_STRICT_DNS {
		cluster.LoadAssignment = &apiv2.ClusterLoadAssignment{
			ClusterName: name,
			Endpoints:   localityLbEndpoints,
		}
	}
```

**Comment by howardjohn** [comment]
isn't there a initial fetch timeout of 15s after which it will unblock? or does that not apply here

**Comment by ydh926** [comment]
The reason why envoy is blocked, please see this issue：https://github.com/envoyproxy/envoy/issues/9963
