### ISSUE TITLE
TestAnalyzeNamespaceMessageHasNoResource test flake

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#20936]
https://prow.istio.io/view/gcs/istio-prow/logs/unit-tests_istio_postsubmit/1397

**Comment by jasonwzm** [comment]
I could not reproduce the test failure. I suspect it may be due to resource contention on the test machine. Maybe we can change the test assertion to `Eventually` to mitigate the flake. @selmanj wdyt?

**Comment by selmanj** [comment]
Eventually sounds like a good idea; the fact that it flaked on nil vs empty list definitely sounds like a timing issue.

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gcs/istio-prow/logs/unit-tests_istio_postsubmit/1499 this seems to fail with the wait still
