### ISSUE TITLE
JWT error during manifest apply

### ISSUE THREAD

**Issue by ostromart** [istio/istio#20946]
```bash
$ go run istioctl/cmd/istioctl/main.go manifest apply
This will install the default Istio profile into the cluster. Proceed? (y/N) y
Error: failed to generate and apply manifests, error: failed to generate manifest: failed to determine JWT policy support. Use the --force flag to ignore this: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request
exit status 1
```
This is with a 1.14 cluster. Not sure if it's a k8s version problem because the k8s version check claims that >=1.14 is supported. Regardless, this message is fine for logging but not suitable as a high level user message.

**Comment by ostromart** [comment]
Also happens on 1.15 clusters.

**Comment by howardjohn** [comment]
Is your k8s cluster is broken in some way? Does `kubectl api-resources` work? Basically if one api is down the whole command breaks. is this gke?

**Comment by howardjohn** [comment]
We might be able to get info about some api-resources and then ignore the error. needs more investigation. We only care about one, so if random ones fail we don't need to block

**Comment by dosten** [comment]
we are facing the same error, we are using AKS and the metrics server is very unstable, if I install using the `--force` flag has mentioned in the error the installation also fails because the `istiod` pod cannot be created because there is a missing `istio-token` SA

**Comment by howardjohn** [comment]
OK let me see if we can ignore the error

**Comment by howardjohn** [comment]
The fact it fails after `--force` suggests it was going to autodetect the non-default setting on your cluster maybe? Try it manually with https://preliminary.istio.io/docs/ops/best-practices/security/#configure-third-party-service-account-tokens

**Comment by dosten** [comment]
thanks @howardjohn, I will test it now, after using the `--force` flag I was expecting Istio default to first party tokens

**Comment by dosten** [comment]
just to be sure: even if I manually set if should use third-party or first-party tokens I need to set the `--force` flag, right?

**Comment by howardjohn** [comment]
The default is to assume the more secure option. Which is a bit of a
tradeoff since it may not work (likely what happened in your case). I have
a change out to add a link to that doc when it fails, and i'll see if I can
make it robust to the error you saw.

**Comment by howardjohn** [comment]
I think so, but we should be able to skip it if you manually set it, ill
look into that as well.

**Comment by NicklasWallgren** [comment]
We have also encountered this in a k3s cluster. How do we proceed? 

K3s: 1.17.3+k3s1

Without `--force` flag
Error: failed to apply manifests: failed to generate manifest: failed to determine JWT policy support. Use the --force flag to ignore this: Get https://127.0.0.1:6443/api?timeout=32s: x509: certificate signed by unknown authority

With force flag
Component Base - manifest apply returned the following errors:
Error: resources not ready after 5m0s: Get https://127.0.01:6443/api/v1/namespaces/istio-system: x509: certificate signed by unknown authority

**Comment by howardjohn** [comment]
That means we cannot connect to API server. Can you file an issue? with more info about your setup

**Comment by NicklasWallgren** [comment]
@howardjohn Will do, thanks.

**Comment by bommavj** [comment]
failed to determine JWT policy support. Use the --force flag to ignore this: Get http://localhost:8080/api?timeout=32s: dial tcp [::1]:8080: connect: connection refused
- Applying manifest for component Base...
2020-04-15T01:18:06.052645Z	error	installer	error running kubectl: exit status 1
2020-04-15T01:18:06.052927Z	error	installer	error running kubectl: exit status 1
2020-04-15T01:18:06.056420Z	error	installer	error running kubectl: exit status 1
2020-04-15T01:18:06.115318Z	error	installer	error running kubectl: exit status 1
2020-04-15T01:18:06.119314Z	error	installer	error running kubectl: exit status 1
- Applying manifest for component Pilot...
2020-04-15T01:18:10.231287Z	error	installer	error running kubectl: exit status 1
2020-04-15T01:18:10.316055Z	error	installer	error running kubectl: exit status 1
✘ Finished applying manifest for component Pilot.
2020-04-15T01:18:12.335764Z	error	installer	Failed to wait for resource: resources not ready after 10m0s: Get http://localhost:8080/apis/apps/v1/namespaces/istio-system/deployments/istiod: dial tcp [::1]:8080: connect: connection refused

- Applying manifest for component EgressGateways...
- Applying manifest for component IngressGateways...
2020-04-15T01:18:12.559786Z	error	installer	error running kubectl: exit status 1
2020-04-15T01:18:12.570712Z	error	installer	error running kubectl: exit status 1
2020-04-15T01:18:12.648236Z	error	installer	error running kubectl: exit status 1
- Applying manifest for component AddonComponents...
2020-04-15T01:18:12.681215Z	error	installer	error running kubectl: exit status 1
2020-04-15T01:18:12.689402Z	error	installer	error running kubectl: exit status 1
2020-04-15T01:18:14.473451Z	error	installer	error running kubectl: exit status 1
✘ Finished applying manifest for component EgressGateways.
2020-04-15T01:18:14.494713Z	error	installer	error running kubectl: exit status 1
✘ Finished applying manifest for component IngressGateways.
2020-04-15T01:18:14.740080Z	error	installer	error running kubectl: exit status 1
2020-04-15T01:18:14.856800Z	error	installer	error running kubectl: exit status 1
✘ Finished applying manifest for component AddonComponents.

Component AddonComponents - manifest apply returned the following errors:
Error: error running kubectl: exit status 1

Error detail:

unable to recognize "STDIN": Get http://localhost:8080/api?timeout=32s: dial tcp [::1]:8080: connect: connection refused (repeated 5 times)

unable to recognize "STDIN": Get http://localhost:8080/api?timeout=32s: dial tcp [::1]:8080: connect: connection refused (repeated 28 times)






Component Base - manifest apply returned the following errors:
Error: error running kubectl: exit status 1

Error detail:

error: unable to recognize "STDIN": Get http://localhost:8080/api?timeout=32s: dial tcp [::1]:8080: connect: connection refused (repeated 1 times)





Component Citadel - manifest apply returned the following errors:
Error: error running kubectl: exit status 1

Error detail:

The connection to the server localhost:8080 was refused - did you specify the right host or port? (repeated 1 times)





Component EgressGateways - manifest apply returned the following errors:
Error: error running kubectl: exit status 1

Error detail:

unable to recognize "STDIN": Get http://localhost:8080/api?timeout=32s: dial tcp [::1]:8080: connect: connection refused (repeated 4 times)





Component Injector - manifest apply returned the following errors:
Error: error running kubectl: exit status 1

Error detail:

The connection to the server localhost:8080 was refused - did you specify the right host or port? (repeated 1 times)





Component SidecarInjector - manifest apply returned the following errors:
Error: error running kubectl: exit status 1

Error detail:

The connection to the server localhost:8080 was refused - did you specify the right host or port? (repeated 1 times)





Component NodeAgent - manifest apply returned the following errors:
Error: error running kubectl: exit status 1

Error detail:

The connection to the server localhost:8080 was refused - did you specify the right host or port? (repeated 1 times)





Component IngressGateways - manifest apply returned the following errors:
Error: error running kubectl: exit status 1

Error detail:

unable to recognize "STDIN": Get http://localhost:8080/api?timeout=32s: dial tcp [::1]:8080: connect: connection refused (repeated 8 times)





Component Galley - manifest apply returned the following errors:
Error: error running kubectl: exit status 1

Error detail:

The connection to the server localhost:8080 was refused - did you specify the right host or port? (repeated 1 times)





Component CertManager - manifest apply returned the following errors:
Error: error running kubectl: exit status 1

Error detail:

The connection to the server localhost:8080 was refused - did you specify the right host or port? (repeated 1 times)





Component Cni - manifest apply returned the following errors:
Error: error running kubectl: exit status 1

Error detail:

The connection to the server localhost:8080 was refused - did you specify the right host or port? (repeated 1 times)





Component Pilot - manifest apply returned the following errors:
Error: error running kubectl: exit status 1

Error detail:

The connection to the server localhost:8080 was refused - did you specify the right host or port? (repeated 1 times)

The connection to the server localhost:8080 was refused - did you specify the right host or port? (repeated 1 times)






Component Policy - manifest apply returned the following errors:
Error: error running kubectl: exit status 1

Error detail:

The connection to the server localhost:8080 was refused - did you specify the right host or port? (repeated 1 times)





Component Telemetry - manifest apply returned the following errors:
Error: error running kubectl: exit status 1

Error detail:

The connection to the server localhost:8080 was refused - did you specify the right host or port? (repeated 1 times)






✘ Errors were logged during apply operation. Please check component installation logs above.

**Comment by jbilliau5668** [comment]
I'm having the exact same issue @bommavj and @NicklasWallgren , did you ever figure this out?

**Comment by NicklasWallgren** [comment]
@jbilliau5668 Yes, have a look at https://github.com/istio/istio/issues/22875
