### ISSUE TITLE
Set up upgrade tests for Istio releases

### ISSUE THREAD

**Issue by JimmyCYJ** [istio/istio#20954]
**Describe the feature request**
There are parameters in configmap or root certificate which may vary among different releases, we need upgrade tests that cover all Istio releases, to make sure an upgrade does not cause issues to data plane. The upgrade test should test old version such as Istio 1.0. 

This upgrade tests are needed when we build a new release.

**Describe alternatives you've considered**

**Additional context**

**Comment by ericvn** [comment]
Same as #23631 ?

**Comment by JimmyCYJ** [comment]
Yes, we can close this one.
