### ISSUE TITLE
ingress-sds holding lots of memory on bulk apply of k8s secrets 

### ISSUE THREAD

**Issue by jcetkov** [istio/istio#20958]
**Bug description**
When applying k8s secrets in bulk, the memory consumption of ingress-sds container shoots up, to a point of being killed on OOM

Filing this based on slack discussion with members of the istio team, will update more information once the experiment is concluded (if the memory drops eventually etc.)

**Expected behavior**
sds memory management can deal with bulk secret update

**Steps to reproduce the bug**

While trying to reproduce issue in different cluster, I took a bulk dump of various resources in one cluster and applied them in another cluster.
Starting with ingress secrets (the file had ~2000 of them), the ingress-sds was OOMKilled on 512 Mi limit and was crash looping; increasing the limit seems to 2G mitigated the issue 

EDIT:
I applied only the secrets when I saw it; no gateways, no vs etc. so envoy had no way of knowing about them.

It is possible the issue has to do with specific/malformed secret, as I was not able to reproduce the same with script-generated secrets.

```
cat secret_dev_a2_all.yaml | grep 'type: istio.io/ingress-key-cert' | wc -l
    2040
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.4.3

**How was Istio installed?**
custom pipeline

**Environment where bug was observed (cloud vendor, OS, etc)**
custom k8s installation over azure nodes

**Comment by howardjohn** [comment]
cc @JimmyCYJ

**Comment by JimmyCYJ** [comment]
cc @myidpt

**Comment by jcetkov** [comment]
So far the memory doesn't seem to drop. could be caused by no gateways matching those secret were applied yet. (Note that the gap in the graph is the time when the container was crash looping, before the mem limit increase)


<img width="2347" alt="Screen Shot 2020-02-07 at 2 53 19 PM" src="https://user-images.githubusercontent.com/6686220/74071820-cfa9a380-49b9-11ea-9921-bd3862a8a65a.png">

**Comment by JimmyCYJ** [comment]
I just noticed a fixed issue in gRPC bidi-stream, that leads to high memory consumption  https://github.com/istio/istio/issues/18557.
I am not clear if that is related, needs some investigation. cc @lambdai

**Comment by lambdai** [comment]
If we are hunting for the memory bump,  #18557 is not related: That one is slowly leaking due to improper retry.

**Comment by lambdai** [comment]
Is this one related to the known and fixed issue that sds server immediately push another secret though SDS, once envoy respond `fail to apply the sds" response?
To see if it is correlated: 
`cluster.sds-grpc.update*` metrics would be helpful. The time series is nice to have, in the same graph as the memory usage

**Comment by jcetkov** [comment]
If this translates to `envoy_cluster_update_*{cluster_name="xds-grpc"}` there doesn't seem to be anything interesting; most of them are empty, `_attempts` and `_success` keeps rising steadily regardless of the timeframe
I don't see any cluster `sds-grpc` I assume that's typo?

**Comment by lambdai** [comment]
I was wrong: sds-grpc is introduced in 1.5

**Comment by zhanggbj** [comment]
We have the same issue that Istio ingressgateway consumes about 1 G MEM with following configurations

- Knative 0.13
- Istio 1.4.7
- Gateway https entries and Secret 500+

After I deleted secret and Gateway SDS from 500+ to 100+, MEM decreased to 200+M, much more reasonable.
<img width="1339" alt="Screen Shot 2020-06-07 at 23 08 01" src="https://user-images.githubusercontent.com/4181847/83988322-7bb5c800-a975-11ea-9347-7a0f79df737f.png">

**Comment by howardjohn** [comment]
Interesting on master, my tests are showing envoy using far more memory than the istio-agent - envoy using 400mb and agent only 40mb for 500 secrets

**Comment by jcetkov** [comment]
I believe it's not an issue with amount of secretes, rather than some malformed one (some element missing?) - we weren't able to trigger this with with 20 000 script generated secret, but were able to trigger by replying a state of offending cluster and saw this happen in dev clusters (with lots of stale, user created config) on at least two different occasions.
