### ISSUE TITLE
Add support for EnvoyRatelimit service for HTTP

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#20952]
Mixer V1 supports memquota / redisQuota rate limits. When MixerV1 is deprecated, this function should be provided by Istio thru other means.

Istio is adding this support for [thrift](https://github.com/istio/istio/pull/19852/files)

- This potentially involves API design
- Documentation
- Equivalence or otherwise between Mixer ratelimits and Envoy.

**Comment by alecor191** [comment]
I noticed that the milestone for this work used to be "1.6", but got then de-prioritized to "backlog". Are you able to share any information on potential release schedule for this feature?

**Comment by mandarjog** [comment]
We are adding it to 1.7 .

**Comment by alecor191** [comment]
@mandarjog as this topic got closed due to inactivity, I was wondering if it is still scheduled to be released as part of 1.7?

**Comment by jgreens** [comment]
@mandarjog  – just reaching out to get an update here. Is support for HTTP still on track to be in 1.8?

If not, I will use one of the suggested workarounds.

Thanks in advance.

**Comment by mandarjog** [comment]
@jgreens we do not have an Istio API for it (yet?), however we have tests and examples of how to do it.

@gargnupur can you point to the PRs that you have done to document how to do it?

**Comment by jgreens** [comment]
Thank you @mandarjog! I really appreciate it.

I'm guessing that the version I need to upgrade to will be apparent in the examples. I am on 1.6.4 now.

**Comment by gargnupur** [comment]
We have a pr for tests currently: https://github.com/istio/istio/pull/28888 

Will add the PR for documentation soon and will post it here too...

@jgreens : You should be able to use global rate limiting on 1.6.4

**Comment by jgreens** [comment]
Thank you @gargnupur!

**Comment by hzxuzhonghu** [comment]
I have designed an API, appreciate if anyone can leave your comments
https://docs.google.com/document/d/1628LHcwuCvTRFhk8rsQKQUmgCxnY6loPFSxliADQDIc/edit#

**Comment by gargnupur** [comment]
Documentation PR: https://github.com/istio/istio.io/pull/8537

**Comment by alecor191** [comment]
I'm trying to understand the rate limiting strategy for Istio moving forward: We used to leverage Istio rate limits in Istio <1.4. Since it got deprecated, we don't use rate limits anymore, but we would really like to/need them.

Is the decision being made that Istio will not provide an API for it, but instead Istio solutions should use Envoy rate limits as described in [Enabling Rate Limits using Envoy](https://istio.io/latest/docs/tasks/policy-enforcement/rate-limit/)?

Or are there still ongoing efforts to design/implement an Istio API (wrapping Envoy rate limits) to make it easier to configure for Istio users?

**Comment by mandarjog** [comment]
We do intend to provide an Istio api to wrap Envoy rate limit.
@hzxuzhonghu has the api doc linked above. Please take a look and comment there.

**Comment by alecor191** [comment]
@mandarjog would it be possible to keep this item "open" to track progress and expected ETA? I understand there is the design doc @hzxuzhonghu shared. However, it would be nice to track it also in GitHub.

**Comment by hzxuzhonghu** [comment]
not stale
