### ISSUE TITLE
Istio operator controller can't be built

### ISSUE THREAD

**Issue by morvencao** [istio/istio#20966]
**Bug description**

Encounter the following errors while building the operator controller:
```
# make controller -f Makefile.core.mk
STATIC=0 GOOS= GOARCH= LDFLAGS='-extldflags -static -s -w' common/scripts/gobuild.sh /istio-operator ./cmd/manager
can't load package: package ./cmd/manager: cannot find package "." in:
	/root/go/src/istio.io/istio/operator/cmd/manager

real	0m0.109s
user	0m0.172s
sys	0m0.064s
Makefile.core.mk:73: recipe for target 'controller' failed
make: *** [controller] Error 1
```

[ ] Configuration Infrastructure
[ ] Docs
[ X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by sdake** [comment]
This file is dead and should be removed. All make operations should have been integrated into the top level `Makefile` or `operator.mk`.

Cheers
-steve

**Comment by ostromart** [comment]
File is removed, closing this.
