### ISSUE TITLE
Stackdriver Adapter - Metrics data not visible on Stack Driver Monitoring

### ISSUE THREAD

**Issue by nikhilbalekundargi** [istio/istio#20987]
We are installing Istio 1.4.0 Manually using helm on GKE. We want the istio metrics on Stackdriver Monitoring on GCP. Followed below steps but the metrics are not showing on Stackdriver Monitoring -

- Created GKE cluster with beloe oauth scopes
 "https://www.googleapis.com/auth/logging.write",
      "https://www.googleapis.com/auth/monitoring",
      "https://www.googleapis.com/auth/devstorage.read_only",
      "https://www.googleapis.com/auth/servicecontrol",
      "https://www.googleapis.com/auth/service.management.readonly",
      "https://www.googleapis.com/auth/trace.append",
      "https://www.googleapis.com/auth/cloud-platform",

- Installed Istio 1.4.0 using helm 

kubectl create serviceaccount --namespace kube-system tiller || true
kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller || true
helm init --upgrade --service-account tiller --wait
helm repo add istio.io https://storage.googleapis.com/istio-release/releases/1.4.0/charts/
helm repo update
kubectl create ns istio-system || true
helm install --name istio-init --namespace istio-system istio.io/istio-init --wait
kubectl -n istio-system wait --for=condition=complete job --all
kubectl get crds | grep 'istio.io\|certmanager.k8s.io' | wc -l
helm install --name istio --namespace istio-system --set global.mtls.enabled=true --set grafana.enabled=true --set servicegraph.enabled=true --set tracing.enabled=true --set kiali.enabled=true --set prometheus.enabled=true --set gateways.istio-ingressgateway.enabled=true --set gateways.istio-ingressgateway.sds.enabled=true  istio.io/istio
kubectl label namespace default istio-injection=enabled
kubectl get namespace -L istio-injection
kubectl create clusterrolebinding cluster-admin-binding --clusterrole=cluster-admin --user="$(gcloud config get-value core/account)"

- wget https://raw.githubusercontent.com/GoogleCloudPlatform/istio-samples/master/stackdriver-metrics/istio-stackdriver-metrics.yaml

- kubectl apply -n istio-system -f istio-stackdriver-metrics.yaml 

When we check the istio metrics on Stackdriver metrics explorer for istio.io/service/client/request_count on kubernetes pods.

We can see below error in Istio-Telemetry Pod 
error adapter series was sent and Stackdriver returned: rpc error: code = PermissionDenied desc = Permission monitoring.timeSeries.create denied (or the resource may not exist).

Below events are seen in Istio-telemetry pod-
![image](https://user-images.githubusercontent.com/32267777/74143875-a2f7c500-4c21-11ea-9d62-0cb51f902cff.png)

Am I missing anything here?

**Comment by bianpengyuan** [comment]
Based on the config, the adapter should just use the default application credential available on the GKE cluster. Did you enable GKE workload identity (https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity) when creating the cluster?

**Comment by EvertonSA** [comment]
If your intent is to use Stackdriver with OSS istio, you will need some additional steps: 
1.  read https://github.com/istio/istio/tree/master/mixer/adapter/stackdriver
2. create SA with permissions (This is the step that i'm currently working on, exactly this moment)
3. add SA key.json to istio-system as a secret
4. change mixer pod to have a volumeMount and mixer deployment to have a volume from that secret 
5. helm template as mentioned in the docs with new parameters

Helm template is hard... you will need the global.YAML applied at the beginning of your istio installation. If you work in a corporate env like me, you will need to double-check the global values.

**Comment by EvertonSA** [comment]
> Based on the config, the adapter should just use the default application credential available on the GKE cluster. Did you enable GKE workload identity (https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity) when creating the cluster?

Will Workload Identity naturally integrate mixer to Stackdriver? I have not found any clues of this info in the documentation. By naturally, I mean using google default handlers at https://raw.githubusercontent.com/GoogleCloudPlatform/istio-samples/master/stackdriver-metrics/istio-stackdriver-metrics.yaml

**Comment by nikhilbalekundargi** [comment]
> Based on the config, the adapter should just use the default application credential available on the GKE cluster. Did you enable GKE workload identity (https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity) when creating the cluster?

Yes, workload identity is enabed on the cluster. But we should bind  KSA (Kubernetes Service Account) with GSA(Google Service Account). Can you clarify which KSA we should bind with GSA? 

One more confusion here is - as per the [workload identity documentation](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity), last point in limitations says GKE logging and monitoring agents will continue to use the Node's Service Account. I have added Monitoring admin role to Compute Engine Default GSA but not getting the metrics on Stackdriver.

**Comment by nikhilbalekundargi** [comment]
> If your intent is to use Stackdriver with OSS istio, you will need some additional steps:
> 
> 1. read https://github.com/istio/istio/tree/master/mixer/adapter/stackdriver
> 2. create SA with permissions (This is the step that i'm currently working on, exactly this moment)
> 3. add SA key.json to istio-system as a secret
> 4. change mixer pod to have a volumeMount and mixer deployment to have a volume from that secret
> 5. helm template as mentioned in the docs with new parameters
> 
> Helm template is hard... you will need the global.YAML applied at the beginning of your istio installation. If you work in a corporate env like me, you will need to double-check the global values.

There is no clarity in documentation on adding the SA key or using Workload identity.

**Comment by nikhilbalekundargi** [comment]
@bianpengyuan I have tried adding api key (with Stackdriver Loggin API, Monitoring API and Trace API permission) but not luck. I can see below error and warning -

error adapters Stackdriver logger failed with: rpc error: code = PermissionDenied desc = The caller does not have permission {"adapter": "stackdriver.istio-system"}

warn	adapters	API Key is no longer supported by gRPC client. Use ServiceAccountPath instead.	{"adapter": "stackdriver.istio-system"}

**Comment by nikhilbalekundargi** [comment]
Resolved the issue by Workload Identity. Below are the steps - 

- Enable workload identity on the cluster and node pool

- Create a google service account with permissions for metrics and logs writing
- Create binding between GSA and istio-mixer-service-account KSA in istio-system name space 
gcloud iam service-accounts add-iam-policy-binding \
  --role roles/iam.workloadIdentityUser \
  --member "serviceAccount:[PROJECT_ID].svc.id.goog[[K8S_NAMESPACE]/[KSA_NAME]]" \
  [GSA_NAME]@[PROJECT_ID].iam.gserviceaccount.com

-  Annotate KSA 
kubectl annotate serviceaccount \
  --namespace [K8S_NAMESPACE] \
  [KSA_NAME] \
  iam.gke.io/gcp-service-account=[GSA_NAME]@[PROJECT_ID].iam.gserviceaccount.com
