### ISSUE TITLE
how can we verify that istio retries is working?

### ISSUE THREAD

**Issue by rahul0403** [istio/istio#20983]
Please explain with an example

**Comment by shamsher31** [comment]
There is plenty of information filled on the Istio website.

Ref: 
https://istio.io/docs/concepts/traffic-management/#retries
https://istio.io/docs/reference/config/networking/virtual-service/#HTTPRetry

I agree that there is no dedicated page available to explain how retries work. But you can use bookinfo sample to try it out.

All you need to do is to configure `VirtualService` and add `retries` attempts in combination with `timeouts`.

```yaml
    retries:
      attempts: 3
      perTryTimeout: 3s
    timeout: 8s
```
1. The request has a timeout of 8 seconds.
2. We attempt 3 times
3. An attempt is marked as failed if it takes longer than 3 seconds.

You can use [Fault Injection](https://istio.io/docs/tasks/traffic-management/fault-injection/) guide to test retries by injecting an HTTP abort fault.

**Comment by rahul0403** [comment]
got it. can you give any suggestion for circuit-breaker that i can test that circuit is open .

**Comment by shamsher31** [comment]
You can identify if the circuit is open using [circuit breaker statistics](https://www.envoyproxy.io/docs/envoy/v1.13.0/configuration/upstream/cluster_manager/cluster_stats#circuit-breakers-statistics).

I think you need to setup fortio as mentioned in the [istio circuit breaker](https://istio.io/docs/tasks/traffic-management/circuit-breaking/#tripping-the-circuit-breaker) example.

Also see this [thread to see what other info ](https://github.com/istio/istio/issues/18110#issuecomment-544543020)is available. Look for `cx_open` in the logs.

Please close this issue if it answers your question. You can also join [Istio Slack channel](https://discuss.istio.io/t/istio-slack-channel/1527) if you have more queries.

**Comment by rahul0403** [comment]
One more question: 
in retries you have mentioned timeout as well, so what is precedence ? which one will work first?

**Comment by shamsher31** [comment]
`retries => timeout`, the timeout will always work last.
