### ISSUE TITLE
Istio in multi-arch kubernetes cluster

### ISSUE THREAD

**Issue by DhruvM1994** [istio/istio#20993]
**Describe the feature request**

I am trying to install istio in a kubernetes cluster containing of an UbuntuVM (Windows 10 as host OS) as the master and a Raspberry Pi as a worker node. I would like to know whether istio can be installed on the above system.

**Comment by esnible** [comment]
Istio works by adding an Envoy container to application pods.  I don't believe the Envoy container we use is compatible with Raspberry Pi.  See https://github.com/envoyproxy/envoy/issues/1861

**Comment by howardjohn** [comment]
We have a couple issues open regarding this. Lets consolidate into #21094. As mentioned, we are constrained by envoy mostly
