### ISSUE TITLE
mesh pod can not connect to pod in same mesh: Connection reset by peer

### ISSUE THREAD

**Issue by robinbraemer** [istio/istio#20991]
**Bug description**
I have pod A and B with istio injected.
Pod A and pod B are in differenct namespaces.
global mTLS mode is `STRICT`.
When A tries to call a gRPC on pod B it fails with error `readAddress(..) failed: Connection reset by peer`

istioctl describe:
```
$ istioctl experimental describe pod A

Pod: A
   Pod Ports: 25565 (A), 15090 (istio-proxy)
Suggestion: add 'app' label to pod for Istio telemetry.
Suggestion: add 'version' label to pod for Istio telemetry.
--------------------
Service: A
   Port: tcp-minecraft 25565/TCP targets pod port 25565
Pod is PERMISSIVE, client protocol unspecified


$ istioctl experimental describe pod B

Pod: B
   Pod Ports: 8443 (B), 15090 (istio-proxy)
Suggestion: add 'app' label to pod for Istio telemetry.
Suggestion: add 'version' label to pod for Istio telemetry.
--------------------
Service: B
   Port: grpc 443/GRPC targets pod port 8443
Pod is PERMISSIVE, client protocol unspecified```

```
<sub>[View in Slack](https://istio.slack.com/archives/C37A4KAAD/p1581345404014400)</sub>

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Pod A shoud be able to connect to Pod B

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
client version: 1.4.3
control plane version: 1.4.3
data plane version: 1.4.3 (5 proxies)
```
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-21T22:17:28Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
Using rancher UI.

**Comment by esnible** [comment]
Can you add the output of `istioctl x analyze --use-kube`?

**Comment by robinbraemer** [comment]
```
$ istioctl x analyze --use-kube
✔ No validation issues found.
```

**Comment by esnible** [comment]
I see you are using TCP.  Some of the auto MTLS and permissive MTLS struggles with TCP connections.  Try using Istio to set server and client STRICT or plain HTTP.

Try following the requirements at https://istio.io/docs/ops/deployment/requirements/ .  When you choose the "name" for your 443 port on B service, try `https` if `grpc` doesn't work.

**Comment by robinbraemer** [comment]
Tested it and apparently all my gRPC services with  port naming `grpc` are only reachable when renaming the `Service` port name to one of `https, http2, tcp tls, udp` or not having a protocol prefix letting istio  [auto select](https://istio.io/docs/ops/configuration/traffic-management/protocol-selection/#automatic-protocol-selection-experimental) the protocol.

Should we close this and open a new issue for "Service with gRPC protocol not reachable" or other title?

**Comment by esnible** [comment]
Do you think this problem is the same as https://github.com/istio/istio/issues/16282 ?

**Comment by robinbraemer** [comment]
It is!
