### ISSUE TITLE
sds_citadel_control_plane_auth_disabled broken on 1.5

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#20995]
https://prow.istio.io/view/gcs/istio-prow/logs/integ-k8s-115_istio_release-1.5_postsubmit/78
https://prow.istio.io/view/gcs/istio-prow/logs/integ-k8s-115_istio_release-1.5_postsubmit/79

**Comment by howardjohn** [comment]
https://storage.googleapis.com/istio-prow/logs/integ-k8s-114_istio_release-1.5_postsubmit/85/artifacts/sds-citadel-flow-control-plane-auth-disabled-test-/_suite_context/istio-state-978706646/istio-ingressgateway-7848684c7c-tmklj-istio-proxy.log is one example log

**Comment by myidpt** [comment]
Those are legacy tests that are still using Citadel and node agent. We will update them.

**Comment by lei-tang** [comment]
@howardjohn The log "Deploy Istio (via Helm Template)" in https://storage.googleapis.com/istio-prow/logs/integ-k8s-115_istio_release-1.5_postsubmit/78/build-log.txt shows that Istio is installed through Helm. But https://github.com/istio/istio/pull/20847 "remove Helm support from test framework".  Has https://github.com/istio/istio/pull/20847 been cherrypicked into release-1.5 branch? 

https://github.com/istio/istio/pull/20239 "get security integration tests running on istioctl" has code to get sds_citadel_control_plane_auth_disabled running on istioctl. If https://github.com/istio/istio/pull/20847 is cherrypicked into release-1.5 branch, sds_citadel_control_plane_auth_disabled should be able to run on istioctl based on https://github.com/istio/istio/pull/20239.

**Comment by howardjohn** [comment]
those are on master only I think, we support helm in 1.5. but the log is
wrong, it said helm always , you should look at the full logs to make sure
it is actually helm

**Comment by lei-tang** [comment]
The lack of "istioctl manifest apply" installation command in the log file and the following log show that helm installs Istio in these integration tests.

2020-02-10T12:06:38.398835Z	info	ci	Wrote out istio deployment files at: /tmp/sds-citadel-flow-control-plane-auth-disabled-test-/_suite_context/istio-deployment-291229228
2020-02-10T12:06:38.811911Z	info	ci	Applying YAML: kubectl apply --kubeconfig=/home/.kube/config  -f /tmp/sds-citadel-flow-control-plane-auth-disabled-test-/_suite_context/istio-deployment-291229228/crd.yaml
2020-02-10T12:06:39.738727Z	info	ci	Applying YAML: kubectl apply --kubeconfig=/home/.kube/config -n istio-system -f /tmp/sds-citadel-flow-control-plane-auth-disabled-test-/_suite_context/env-kube-829806017/istio-kube-accessor-313878427/istio-install-only_namespaces_and_crds.yaml874885694
2020-02-10T12:06:39.956644Z	info	ci	Applying YAML: kubectl apply --kubeconfig=/home/.kube/config -n istio-system -f /tmp/sds-citadel-flow-control-plane-auth-disabled-test-/_suite_context/env-kube-829806017/istio-kube-accessor-313878427/istio-install-only_misc.yaml166959237

**Comment by lei-tang** [comment]
Based on discussion with John, for this issue, we will fix the sds_citadel_control_plane_auth_disabled test , which uses the helm installation method during the test.

**Comment by lei-tang** [comment]
The following error log in https://storage.googleapis.com/istio-prow/logs/integ-k8s-115_istio_release-1.5_postsubmit/99/artifacts/sds-citadel-flow-control-plane-auth-disabled-test-/_suite_context/istio-state-384262619/istio-ingressgateway-6f66cb98d6-8z4bz-istio-proxy.log shows that there are certificate path errros in cluster configuration received by ingress gateway Envoy from Pilot:

[Envoy (Epoch 0)] [2020-02-13 22:55:48.861][23][warning][config] [external/envoy/source/common/config/grpc_subscription_impl.cc:87] gRPC config for type.googleapis.com/envoy.api.v2.Cluster rejected: Error adding/updating cluster(s) outbound|443||kubernetes.default.svc.cluster.local: Invalid path: /etc/certs/cert-chain.pem, outbound|53||kube-dns.kube-system.svc.cluster.local: Invalid path: /etc/certs/cert-chain.pem, outbound|9153||kube-dns.kube-system.svc.cluster.local: Invalid path: /etc/certs/cert-chain.pem, outbound|443||metrics-server.kube-system.svc.cluster.local: Invalid path: /etc/certs/cert-chain.pem, outbound|7070||norewrite-fail.healthcheck.svc.cluster.local: Invalid path: /etc/certs/cert-chain.pem, outbound|8080||norewrite-fail.healthcheck.svc.cluster.local: Invalid path: /etc/certs/cert-chain.pem, outbound|7070||rewrite-success.healthcheck.svc.cluster.local: Invalid path: /etc/certs/cert-chain.pem, outbound|8080||rewrite-success.healthcheck.svc.cluster.local: Invalid path: /etc/certs/cert-chain.pem, outbound|8060||istio-citadel.istio-system.svc.cluster.local: Invalid path: /etc/certs/cert-chain.pem, outbound|15014||istio-citadel.istio-system.svc.cluster.local: Invalid path: /etc/certs/cert-chain.pem, outbound|443||istio-galley.istio-system.svc.cluster.local: Invalid path: /etc/certs/cert-chain.pem, outbound|15014||istio-galley.istio-system.svc.cluster.local: Invalid path: /etc/certs/cert-chain.pem, outbound|9901||istio-galley.istio-system.svc.cluster.local: Invalid path: /etc/certs/cert-chain.pem, outbound|15020||istio-ingressgateway.istio-system.svc.cluster.local: Invalid path: /etc/certs/cert-chain.pem, outbound|80||istio-ingressgateway.istio-system.svc.cluster.local: Invalid path: /etc/certs/cert-chain.pem, outbound|443||istio-ingressgateway.istio-system.svc.cluster.local: Invalid path: /etc/certs/cert-chain.pem, outbound|31400||istio-ingressgateway.istio-system.svc.cluster.local: Invalid path: /etc/certs/cert-chain.pem, outbound|15029||istio-ingressgateway.istio-system.svc.cluster.local: Invalid path: /etc/certs/cert-chain.pem, outbound|15030||istio-ingressgateway.istio-system.svc.cluster.local: Invalid path: /etc/certs/cert-chain.pem, outbound|15031||istio-ingressgateway.istio-system.svc.cluster.local: Invalid path: /etc/certs/cert-chain.pem, outbound|15032||istio-ingressgateway.istio-system.svc.cluster.local: Invalid path: /etc/certs/cert-chain.pem, outbound|15443||istio-ingressgateway.istio-system.svc.cluster.local: Invalid path: /etc/certs/cert-chain.pem, outbound|15010||istio-pilot.istio-system.svc.cluster.local: Invalid path: /etc/certs/cert-chain.pem, outbound|15011||istio-pilot.istio-system.svc.cluster.local: Invalid path: /etc/certs/cert-chain.pem, outbound|8080||istio-pilot.istio-system.svc.cluster.local: Invalid path: /etc/certs/cert-chain.pem, outbound|15014||istio-pilot.istio-system.svc.cluster.local: Invalid path: /etc/certs/cert-chain.pem, outbound|9091||istio-policy.istio-system.svc.cluster.local: Invalid path: /etc/certs/cert-chain.pem, outbound|15004||istio-policy.istio-system.svc.cluster.local: Invalid path: /etc/certs/cert-chain.pem, outbound|15014||istio-policy.istio-system.svc.cluster.local: Invalid path: /etc/certs/cert-chain.pem, outbound|443||istio-sidecar-injector.istio-system.svc.cluster.local: Invalid path: /etc/certs/cert-chain.pem, outbound|15014||istio-sidecar-injector.istio-system.svc.cluster.local: Invalid path: /etc/certs/cert-chain.pem, outbound|9091||istio-telemetry.istio-system.svc.cluster.local: Invalid path: /etc/certs/cert-chain.pem, outbound|15004||istio-telemetry.istio-system.svc.cluster.local: Invalid path: /etc/certs/cert-chain.pem, outbound|15014||istio-telemetry.istio-system.svc.cluster.local: Invalid path: /etc/certs/cert-chain.pem, outbound|42422||istio-telemetry.istio-system.svc.cluster.local: Invalid path: /etc/certs/cert-chain.pem, outbound|9090||prometheus.istio-system.svc.cluster.local: Invalid path: /etc/certs/cert-chain.pem

**Comment by lei-tang** [comment]
The testgrid https://testgrid.k8s.io/istio_release-1.5_istio_postsubmit#integ-k8s-115_istio_release-1.5_postsubmit shows that sds_citadel_control_plane_auth_disabled starts to fail after the PR
https://github.com/istio/istio/pull/20959 is merged into release 1.5 branch.
Thus, likely the changes in https://github.com/istio/istio/pull/20959 breaks ingress gateway in the sds_citadel_control_plane_auth_disabled test.

**Comment by dgn** [comment]
Tbh I don't think we'll require code changes as this works with istioctl -- because of this, I think the issue can be solved in the charts.

**Comment by dgn** [comment]
Test is passing now, thank you @howardjohn
