### ISSUE TITLE
Citadel does not export stats to Grafana correctly

### ISSUE THREAD

**Issue by JimmyCYJ** [istio/istio#21004]
**Bug description**
Citadel does not report stats correctly, this is found by perf test on 1.3.7+ 
![image](https://user-images.githubusercontent.com/28548492/74190798-c7df3e80-4c07-11ea-85b3-7f2bc3c06b84.png)

**Expected behavior**
`CSR requests` and `Certificates Issued` should be non-zero.

**Steps to reproduce the bug**
Deploy Istio and port forward to Grafana to monitor stats

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.3.7

**Comment by myidpt** [comment]
Thanks for reporting. Does this work with 1.3.6?

**Comment by JimmyCYJ** [comment]
I am not clear, I didn't test 1.3.6.

**Comment by Monkeyanator** [comment]
I don't have a cluster to test this on at the moment but I recall [this related PR](https://github.com/istio/istio/pull/15784). Are you able to port-forward to the Prometheus port on Citadel instance and check the `/metrics` route?

**Comment by myidpt** [comment]
We discontinued support for 1.3. Is this also true for 1.4?

**Comment by howardjohn** [comment]
No longer relevant as citadel is gone
