### ISSUE TITLE
Istioctl does not accept istioControlPlane configuration via STDIN

### ISSUE THREAD

**Issue by zimmertr** [istio/istio#21015]
**Bug description**

When attempting to provide an `IstioControlPlane` configuration to `istioctl manifest apply -f -`, Istioctl fails to recognize the configuration _file_ being presented to it.

**Expected behavior**

Istioctl should accept the STDIN as configuration if it has valid syntax.

**Steps to reproduce the bug**

1) Define an `istioControlPlane` configuration and `cat` & `|` it into Istioctl. 
2) Istioctl produces an error message:

```
$> cat ~/Desktop/example.yml | envsubst | istioctl manifest apply -f -
Failed to generate and apply manifests, error: failed to generate manifest: could not read values from file -: open -: no such file or directory
```

If  you change the operator from `-f -` to `-f <()`, Istioctl doesn't complain. However, it DOES simply ignore the configuration entirely and just deploys the Default profile.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

*Istio:* 1.4.3
*Kubernetes:* 1.17.0

**How was Istio installed?**

I used the scary recommended method of piping the internet into my shell. 

**Environment where bug was observed (cloud vendor, OS, etc)**

Local `kubeadm` based cluster.

**Comment by zimmertr** [comment]
This issue was discovered due to the fact that Istioctl doesn't support environment variable expansion at runtime. This is documented in this separate issue [here](https://github.com/istio/istio/issues/21014).

**Comment by esnible** [comment]
In most places _istioctl_ accepts `-f -` but not in `manifest apply` nor `manifest generate`.

**Comment by bishtawi** [comment]
Is this still a bug? I see the PR https://github.com/istio/istio/pull/21612 which claims to re-add support for istioctl manifest to read from stdin to version 1.5 but its not listed in the [1.5 change log](https://istio.io/news/releases/1.5.x/announcing-1.5/change-notes/). The only thing remotely related there is `Added support for analyzing content passed via stdin to istioctl analyze` which is talking about the `analyze` feature not the `manifest` feature.

**Comment by ayj** [comment]
It is working for me with the 1.5.0 release. I forgot to add it to the release notes.

```bash
cat  install/kubernetes/operator/profiles/minimal.yaml | bin/istioctl manifest generate -f - 
```
