### ISSUE TITLE
istio-policy restart causes pods to restart due to liveness probe

### ISSUE THREAD

**Issue by miracle-jia** [istio/istio#21029]
Does any proccess on this issue?
We use the 1.3.0 version and restart the istio-policy, our service cannot be access.

Here is our issue:
Our deployment is configured a liveness probe to health check every 3 or 5 second. When the istio-policy restarted, during the restart, the pod envoy cannot connect to policy, all of request will be delayed 5 seconds. While the health check request is deplayed 5 second, the liveness probe failed always and then the pod will be restart, eventually leads to service cannot be access during the pod restart.

similar to #7334 

Does anyone knows?

**Comment by miracle-jia** [comment]
does any one meet the issue?

**Comment by idouba** [comment]
@hzxuzhonghu

**Comment by hzxuzhonghu** [comment]
We have set the default retryon policy for telemetry and policy route

```
                     "route": {
                            "cluster": "outbound|9091||istio-telemetry.istio-system.svc.cluster.local",
                            "timeout": "0s",
                            "retryPolicy": {
                                "retryOn": "connect-failure,refused-stream,unavailable,cancelled,resource-exhausted,retriable-status-codes",
                                "numRetries": 2,
                                "retryHostPredicate": [
                                    {
                                        "name": "envoy.retry_host_predicates.previous_hosts"
                                    }
                                ],
                                "hostSelectionRetryMaxAttempts": "5",
                                "retriableStatusCodes": [
                                    503
                                ]
                            },
                            "maxGrpcTimeout": "0s"
                        },

```

@miracle-jia Could you check if this exist, and does it take effect

**Comment by howardjohn** [comment]
As we have deprecated Istio policy so we are unlikely to make any changes, this is on an unsupported version, and there hasn't been any activity for months after asking for followup debug info, I think we can close this. Please reopen if you are still seeing issues. Thanks!
