### ISSUE TITLE
operator does not prune telemetry v2 envoyfilters

### ISSUE THREAD

**Issue by richardwxn** [istio/istio#21037]
When user upgrade from telemetry v2 enabled to v2 disabled(either no telemetry or v1 mixer telemetry) , the previously applied metadata exchange and stats/sd filter would not be pruned. I think the reason is that right now the istioctl pruning logic is done on basis of component level

**Comment by howardjohn** [comment]
Envoyfilter is not in the prune whitelist

**Comment by richardwxn** [comment]
@howardjohn do you know whether exist a place to add that or we have to pass in --prune-whitelist for Envoyfilter during apply
