### ISSUE TITLE
The installation option for telemetry is too complex

### ISSUE THREAD

**Issue by richardwxn** [istio/istio#21048]
Right now for IstioOperator spec, we have these following options and default value for 1.5 related to telemetry functionality enablement

1. components.telemetry.enabled: controls mixer related resources installation
    default: false
2. values.telemetryv1.enabled: controls mixerReportServer setting in istio configMap
   default: false
3. values.telemetryv2.enabled: controls v2 related envoyfilters
   default: true
4. values.telemetry.enabled: gating for 2 and 3 together
   default: true

specifically, the 1. and 4. field is quite confusing for user because the values look contradictory. Also if user want to change from default v2 to back to mixer, then override like this have to be supplied: components.telemetry.enabled=true, values.telemetryv1.enabled=true

**Comment by howardjohn** [comment]
we should move the filters to a different component (base?) this is needed for multiple control plane as well

or maybe it's time to implement this in pilot

**Comment by sdake** [comment]
@richardwxn agree too complex.

For the 1.5 release would you consider filing an issue in istio.io's issue tracker documenting the transition from mixerv1 to mixerv2 and how to revert the defaults to the 1.4 mixer defaults? This will provide the documentation team an opportunity to prepare a transition page for the 1.5 release 1.5.

**Comment by richardwxn** [comment]
@sdake we have a guide for how to use the telemetry v2: https://istio.io/docs/ops/configuration/telemetry/in-proxy-service-telemetry/, but not a fully migration guide. And I think there are many other places that are still referencing the old mixer v1 stuff. @douglas-reid Are you doing some doc work related to that?

**Comment by douglas-reid** [comment]
I am working on improving the v2 docs.

**Comment by esnible** [comment]
Is there an issue for logic to look at IstioOperator and produce warnings when there are incompatible settings?

For example, if should be a warning to set `values.galley.enableAnalysis=true` without also setting 
`components.galley.enabled=true`?

If such logic existed it could be connected to `istioctl validate` and perhaps `analyze`, and the operator could log warnings.

**Comment by richardwxn** [comment]
there is such validation function exists: https://github.com/istio/istio/blob/master/operator/pkg/apis/istio/v1alpha1/validation/validation.go#L48

**Comment by esnible** [comment]
Related: https://github.com/istio/istio/pull/21644 and https://github.com/istio/istio/issues/20730

**Comment by ostromart** [comment]
Since this issue has no owner for a while I'm going to throw the original reporter under the bus and tentatively assign to @richardwxn - feel free to deal with this as you see fit. My 2c - it seems reasonable to resolve this through some combination of validation / documentation.

**Comment by esnible** [comment]
Another user did not realize there was a problem because the enabling options are not checked: https://github.com/istio/istio/issues/21988

I am happy to implement validation for IstioOperator setting incompatibility.  However, I don't know what the flag dependency is.  Do we have a table somewhere that I can use?  Or should I get started on gathering a table myself based on Issues being filed?

**Comment by richardwxn** [comment]
@esnible I don't think we have a table documenting the dependency between flags in documentation or in codebase. We can create config file and the validation logic can use that.
