### ISSUE TITLE
istio_mcp_message_sizes_bytes_bucket doesn't reflect mcp response

### ISSUE THREAD

**Issue by jcetkov** [istio/istio#21049]
**Bug description**
the metric `istio_mcp_message_sizes_bytes_bucket` seems to only contain the request payload size, which is fixed and not too interesting value
the response of mcp, which keeps growing with resources applied in cluster and can cause disruption of operations if breaching pilot's configured mcpMaxMsgSize is not captured

**Expected behavior**
it is possible to monitor mcp response size and alert on it if it approaches configured `mcpMaxMsgSize`

**Steps to reproduce the bug**
use prometheus to observe `istio_mcp_message_sizes_bytes_bucket` 
create larger amount of resource of certain type gw, vs .., in the cluster
observe no changes in the metric  

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.4.3

**How was Istio installed?**
custom helm pipeline

**Environment where bug was observed (cloud vendor, OS, etc)**
custom k8s over azure nodes

**Comment by howardjohn** [comment]
Fixed in 1.4.5
