### ISSUE TITLE
[pilot] Add Metrics to Pilot

### ISSUE THREAD

**Issue by nmittler** [istio/istio#2104]
Add some basic metrics to Pilot to support monitoring with [Prometheus](https://prometheus.io/). We can use mixer as an example.

To start discussion, here are some potential metrics:

- Per cache:
-- cache hit/miss
-- cache size
- ListAllEndpoints
-- Call count
-- Error count
-- Service count
- ListEndpoints
-- Call count
-- Error count
-- Endpoint count
- AvailabilityZone
-- Call count
-- Error count
-- Instance count
- ListClusters
-- Call count
-- Error count
-- Cluster count
- ListListeners
-- Call count
-- Error count
-- Listener count
- ListRoutes
-- Call count
-- Error count
-- Route count 

We'll also add more detailed logging for returned resource count per cache key.

**Comment by nmittler** [comment]
cc @ZackButcher

**Comment by ZackButcher** [comment]
I think a lot of the per-request stuff (domain, node type, IP, etc) is likely too granular and I don't think would provide much value. In my experience a distribution recording number of results returned by each of the `List*` methods would be valuable.

**Comment by kyessenov** [comment]
This issue is not going to be solved at once. I suggest we invest into plumbing:
- picking monitoring framework (prometheus?)
- writing through basic dataflow
- setting basic metrics

Then let the interested parties contribute metrics that they care about. This makes it a great on-boarding project.

**Comment by nmittler** [comment]
> - picking monitoring framework (prometheus?)

I assume this has already happened ... mixer is already using prometheus.  +@ZackButcher

> - writing through basic dataflow
> - setting basic metrics

I assume that we can agree on a reasonable set of basic metrics in this issue.  The workflow should be no different than mixer.

> Then let the interested parties contribute metrics that they care about. This makes it a great on-boarding project.

Again, this is laying the foundation with prometheus ... adding additional metrics going forward should be trivial.

**Comment by kyessenov** [comment]
We haven't chosen a metrics pipeline AFAIK. Prometheus sounds reasonably.
Do we want integration through Mixer for Pilot metrics? Do metrics travel
to Mixer using prometheus or some other protocol, and then mixer translate
that to whatever is needed?

**Comment by mandarjog** [comment]
All components should produce metrics that Prometheus can consume.Mixer and envoy already do this. 
Producing metrics using Prometheus client library  is simple. You can just pick a few metrics that make sense and add those. This can serve as a template for people that want to add new metrics. I don’t think there is any more design involved here.

@nmittler
We should also add metrics related to memory consumption.

**Comment by kyessenov** [comment]
Envoy still uses statsd in production. I think we should just use
prometheus, and hope things eventually converge, with enough shimming in
front and behind Mixer.

**Comment by nmittler** [comment]
@mandarjog @kyessenov @ZackButcher Thanks, guys ... SGTM.

I've updated the list of metrics in the description.  PTAL.

**Comment by ZackButcher** [comment]
Updated description LGTM.

Per our in person discussion, we want a distribution metric recording number of elements returned in each list query, with no cache key dimension. We can log a line recording the cache key and number of elements returned for that key. That way the number-of-elements metric acts as a rough tell of abnormal results, and you can look at logging to debug specific outlier requests.

**Comment by mandarjog** [comment]
@wattli when this PR drops, we need to exclude the port from istio-security. Mixer uses `http-health, 9093:/metrics` for this purpose we should be consistent.

**Comment by ZackButcher** [comment]
In addition to moving to use the same port for /metrics as Mixer, we'll also need to update the Prometheus scrape config we currently use to scrape the `istio-pilot` service.

**Comment by nmittler** [comment]
@ZackButcher should the remaining work be gated on the on-going task for standardizing *z pages?  I.e. should we close this issue and address it as part of the larger, Istio-wide work?

**Comment by ZackButcher** [comment]
No, lets go ahead and do this now, it's pretty easy and provides immediate value.

- Add a flag for the port to run metrics on, set the default to the same as Mixer's (`9093`)
- The Prometheus config is very easy to change, just add another block here:
https://github.com/istio/istio/blob/28c158b02dff2c6d6a8d30c63a7b683bc3b0e67b/install/kubernetes/addons/prometheus.yaml#L2-L35
