### ISSUE TITLE
 Istio-Envoy Test failures on PowerPC (ppc64le)

### ISSUE THREAD

**Issue by aishwaryabk** [istio/istio#21057]
Hi,
I was able to build Istio-envoy on rhel:7.6/ppc64le. I have cmake3 v3.13.4, bazel v1.2.1, gcc-8.2.1, go 1.13.6 linux/ppc64le, jdk11 installed. I have also used power specific LuaJIT. However I get some test failures

ERROR: 
`/envoy/test/test_common/BUILD:176:1: Linking of rule '//test/test_common:global_test' failed (Exit 1) gcc failed: error executing command /opt/rh/devtoolset-8/root/usr/bin/gcc @bazel-out/ppc-fastbuild/bin/test/test_common/global_test-2.params`

`Use --sandbox_debug to see verbose messages from the sandbox`
`/opt/rh/devtoolset-8/root/usr/bin/ld.gold: error: cannot find -latomic`
`collect2: error: ld returned 1 exit status`

Would like some help. I am building envoy as a dependency requires by other Istio repositories.

**Comment by howardjohn** [comment]
Lets consolidate into https://github.com/istio/istio/issues/20836, it is hard to track so many split issues. Thanks!
