### ISSUE TITLE
Missing the scripts in samples/multicluster

### ISSUE THREAD

**Issue by clyang82** [istio/istio#21054]
**Bug description**

The `setup-bookinfo.sh` and `setup-mesh.sh` are missed in samples/multicluster dir for [Istio 1.5.0-beta.1](https://github.com/istio/istio/releases/tag/untagged-e927792f03470f745667). is this by design?

**Comment by ayj** [comment]
Thanks for pointing this out. We should remove `https://preliminary.istio.io/docs/setup/install/multicluster/simplified` was an experiment that has run its course. I would be surprised if it worked with 1.5.

**Comment by ayj** [comment]
@nmittler , wdyt ?

**Comment by nmittler** [comment]
yeah let's remove
