### ISSUE TITLE
VirtualOutboundListener does not have http inspector

### ISSUE THREAD

**Issue by rshriram** [istio/istio#21053]
We setup the HTTP inspector on every listener in a sidecar except for the virtualOutboundListener. This listener is the catch all listener for any unknown traffic. We need to have the HTTP inspector here (and set the upstream to blackhole or allow_any accordingly). This way, the sniffing logic is consistent across all outbound.

**Comment by rshriram** [comment]
cc @ramaraochavali / @howardjohn / @hzxuzhonghu what do you guys think? Today, unknown http connections (in REGISTRY_ONLY) mode will be dropped. But when we add a HCM to the virtualOutbound, we will be returning a 404 instead. So this is something to consider.

**Comment by howardjohn** [comment]
> But when we add a HCM to the virtualOutbound, we will be returning a 404 instead. So this is something to consider.

We can make it return a 502, then it is consistent with how it behaves today when you match an existing http listener

**Comment by hzxuzhonghu** [comment]
what is the use case for `But when we add a HCM to the virtualOutbound.`?

**Comment by rshriram** [comment]
telemetry and also egress gateway
