### ISSUE TITLE
in-cluster operator fails to deploy default control plane

### ISSUE THREAD

**Issue by dgn** [istio/istio#21062]
It works with `istioctl` built from the same code.

**Bug description**
the istiod and ingressgateway pods never come up

[x] Installation

**Expected behavior**
control plane is deployed without error

**Steps to reproduce the bug**
```
istioctl operator init
kubectl create ns istio-system
kubectl apply -f samples/operator/default-install.yaml
```

Pods fail to come up with
```
MountVolume.SetUp failed for volume "citadel-ca-cert" : configmap "istio-ca-root-cert" not found
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.5.0-beta.1

**Environment where bug was observed (cloud vendor, OS, etc)**
minikube

**Comment by ostromart** [comment]
@dgn could you attach logs?

**Comment by ostromart** [comment]
ping @dgn

**Comment by dgn** [comment]
sorry @ostromart, was busy working on other things.. Will provide logs on Monday, but IIRC it was related to the operator not deploying a secret (istio-ca-root-cert I believe). It was easily reproducable with the steps above- it might have been fixed by your jsonmerge PR. Will verify on Monday.

**Comment by dgn** [comment]
This was user error- it's caused by https://github.com/istio/istio/issues/21463
