### ISSUE TITLE
Develop e2e test for operator

### ISSUE THREAD

**Issue by sdake** [istio/istio#21069]
**Bug description**
Please see this issue thread: https://github.com/istio/istio/issues/21063#issuecomment-585378472

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
cc @dgn

**Comment by sdake** [comment]
closing in favor of a different contributor to reimplement this work: https://github.com/istio/istio/issues/21468
