### ISSUE TITLE
in-cluster operator attempts to overwrite immutable fields in k8s services

### ISSUE THREAD

**Issue by dgn** [istio/istio#21063]
```
2020-02-12T14:43:04.454812Z	error	Service "prometheus" is invalid: spec.clusterIP: Invalid value: "": field is immutable
2020-02-12T14:43:04.977653Z	error	Service "istio-ingressgateway" is invalid: spec.clusterIP: Invalid value: "": field is immutable
2020-02-12T14:43:05.276778Z	error	Service "istio-pilot" is invalid: spec.clusterIP: Invalid value: "": field is immutable
2020-02-12T14:43:05.294929Z	error	Service "istiod" is invalid: spec.clusterIP: Invalid value: "": field is immutable
```

**Comment by sdake** [comment]
@dgn thank you for the report. I am unsurprised that immutable fields are not filtered in a manifest update. I am surprised to see that cllusterIP is set to `None`. i am surprised to see clusterIP used for these services -> :https://github.com/istio/istio/blame/master/manifests/base/templates/services.yaml#L23...

I am curious why `clusteriP` is set at all.  @howardjohn any insight?

**Comment by sdake** [comment]
@dgn if you are willing to take a spin at fixing this, plmk - otherwise will find someone to solve this problem. IMO this (appears) like a blocker for 1.5.

Cheers
-steve

**Comment by howardjohn** [comment]
>  IMO this (appears) like a blocker for 1.5.

is the operator promoted to beta yet?

**Comment by sdake** [comment]
@howardjohn - there was a discussion on this topic in either a PR or issue that @ostromart was involved with, which I can't find. I had the impression from the discussion that there were no further concerns with the stand-alone operator and it was ready for beta.

A PR was submitted to istio.io to implement this change: https://github.com/istio/istio.io/pull/6425

Unfortunately this PR didn't link the discussion so the context of the decision is (temporarily) lost until hopefully, @ostromart can find the issue discussion at hand.

This does raise the issue of how we execute feature promotion. What was done was a bit ad-hoc, this is typically how I have seen features promoted in the past in the Istio project.

Cheers
-steve

**Comment by howardjohn** [comment]
I thought we had a policy that Beta features require proper testing? Given
the large amount of reports of operator not building, not installing the
default profile, etc, I think it's pretty clear we do not meet that bar
yet. I do not see any statement of testing on
https://istio.io/about/feature-stages/ but I feel like it should be added,
and the PR to promote operator reverted until we have such testing.

**Comment by dgn** [comment]
Note that this happens only in later reconcile iterations, not the first one. The service is laid down just fine, the error looks cosmetic to me, so not a release blocker. #21062 is a release blocker

**Comment by ostromart** [comment]
To me beta means the code is production ready and operator hasn't had enough attention this release - probably because folks are understandably more attracted to working on new features than testing and fixing bugs. It's fundamentally not in bad shape because it hasn't had any new features added since 1.4, but it needs a concerted effort to get it to beta quality. The main gap is testing:
1. Istio tests should also run with operator install. This should not be very hard since operator/istioctl manifest generation is the same code and istioctl tests are working. It's more test infra work than operator.
2. We need a real e2e test where the full operator is installed and exercised. We have some tests around the controller but the k8s server is stubbed out and this has led to regressions in the code.
It's really a question of available cycles. If the above items are addressed we can probably call it beta, at least it's in the discussion, otherwise it should likely stay alpha.
btw. I'm working on a fix for the immutable issue (https://github.com/istio/istio/issues/21047) and should have a fix today.

**Comment by sdake** [comment]
> I thought we had a policy that Beta features require proper testing? Given the large amount of reports of operator not building, not installing the default profile, etc, I think it's pretty clear we do not meet that bar yet. I do not see any statement of testing on https://istio.io/about/feature-stages/ but I feel like it should be added, and the PR to promote operator reverted until we have such testing.

Agreed. I had thought we had e2e testing for the (standalone) operator. There was no stubbing taking place in the e2e testing. The e2e testing was run against a kind cluster. It appears this e2e test was lost during the monorepo transition.

@irisdingbj this thread may be of interest to you.
Cheers
-steve

**Comment by ostromart** [comment]
Duplicate of https://github.com/istio/istio/issues/21047, fixed in https://github.com/istio/istio/pull/21083.

**Comment by ostromart** [comment]
Maybe something didn't get carried over from the operator repo - @sdake or @irisdingbj could you send a pointer?
I'm only aware of https://github.com/istio/istio/blob/9fdbf4f32acb6edd967340930dd54a7cb2730f8e/operator/pkg/controller/istiocontrolplane/istiocontrolplane_controller_test.go#L67 so when I said stubbing this is what I was talking about. But I may well have missed some other CI test running elsewhere in which case we should port that over.

**Comment by sdake** [comment]
> @howardjohn - there was a discussion on this topic in either a PR or issue that @ostromart was involved with, which I can't find. I had the impression from the discussion that there were no further concerns with the stand-alone operator and it was ready for beta.
> 
> A PR was submitted to istio.io to implement this change: [istio/istio.io#6425](https://github.com/istio/istio.io/pull/6425)
> 
> Unfortunately this PR didn't link the discussion so the context of the decision is (temporarily) lost until hopefully, @ostromart can find the issue discussion at hand.
> 
> This does raise the issue of how we execute feature promotion. What was done was a bit ad-hoc, this is typically how I have seen features promoted in the past in the Istio project.
> 
> Cheers
> -steve

For further reference, the statement that prompted the promotion PR: https://docs.google.com/document/d/1wI7n6J-QKhSRU2vRSGJlWTcglHYzw1Ox4qEiTr98K4Y/edit?ts=5e46ee8f#

@istio/wg-environments-maintainers We should consider the action in the future to ensure promotions of features follow a thorough working group discussion followed by a vote.

Cheers
-steve

**Comment by sdake** [comment]
> Maybe something didn't get carried over from the operator repo - @sdake or @irisdingbj could you send a pointer?
> I'm only aware of
> 
> https://github.com/istio/istio/blob/9fdbf4f32acb6edd967340930dd54a7cb2730f8e/operator/pkg/controller/istiocontrolplane/istiocontrolplane_controller_test.go#L67
> 
> so when I said stubbing this is what I was talking about. But I may well have missed some other CI test running elsewhere in which case we should port that over.

@ostromart the e2e testing (was) here: https://github.com/istio/operator/blob/master/Makefile.core.mk#L90-L91. This didn't make it through the monorepo purge. Not a significant problem - e2e testing can be added in 1.6.
