### ISSUE TITLE
OPERATOR:   Controller base image Ubuntu not up to date

### ISSUE THREAD

**Issue by kramvan1** [istio/istio#21078]
**Bug description**

The operator controller Docker file https://github.com/istio/operator/blob/master/build/Dockerfile#L1
uses the Ubuntu 16.04 as the base image for the operator controller.
```
FROM ubuntu:xenial as base_os_context
```

Several issues with this
- Need to keep the base OS image up to date with security issues (CVEs). Currently 10 issues.
- Controller that has no dependencies, why the need for all the extra base packages?

**Expected behavior**

Much smaller operator controller image (Alpine?, Ubuntu 18.04 ) or even a scratch image to allow for faster downloads and more importantly,  reduce footprint for possible security issues (CVEs). 
Add a step to the Docker file to update to the latest packages to pick up latest security fixes:
```
apt update
apt upgrade
```

**Steps to reproduce the bug**

Look at Dockerfile.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

Master

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
This is fixed on master https://github.com/istio/istio/blob/b2d580ebb3a88d8e11eb311a6482beac0ae6e314/operator/docker/Dockerfile.operator#L8

**Comment by sdake** [comment]
@kramvan1 https://github.com/istio/operator master is deprecated as a result of the mono-repo merge.

I think the link you are searching for is the 1.4 branch - which is where operator maintenance happens:
https://github.com/istio/operator/blob/release-1.4/build/Dockerfile#L1

This Dockerfilewould benefit from a backport of the fix in master. I'm unclear if the builder could handle such a backport as is, or if it needs additional work. The fact that Istio's latest stable branch uses a deprecated (Ubuntu 16.04 is EOL) distro is a problem. Ubuntu distros have been known to not have very good CVE coverage.

**Comment by kramvan1** [comment]
@sdake thx, understand the 16.04 EOL.  We might have to take a different path for this till 1.5.
