### ISSUE TITLE
Allow using a type `kubernetes.io/tls` or `istio.io/key-and-cert` secret for SDS

### ISSUE THREAD

**Issue by dhermes** [istio/istio#21076]
**Describe the feature request**

All the [docs][1] (and [third party docs][2]) recommend storing a secret with keys `key` and `cert`:

```
$ kubectl create -n istio-system secret generic httpbin-credential \
>   --from-file=key=httpbin.example.com/3_application/private/httpbin.example.com.key.pem \
>   --from-file=cert=httpbin.example.com/3_application/certs/httpbin.example.com.cert.pem
$
$ kubectl create -n istio-system secret generic frontend-credential  \
>   --from-file=key=frontend.foocorp.com/3_application/private/frontend.foocorp.com.key.pem \
>   --from-file=cert=frontend.foocorp.com/3_application/certs/frontend.foocorp.com.cert.pem \
>   --from-file=cacert=frontend.foocorp.com/2_intermediate/certs/ca-chain.cert.pem
```

**Describe alternatives you've considered**

The only game in town is to use a `generic` secret with `key`, `cert` and `cacert` as the keys.

[1]: https://istio.io/docs/tasks/traffic-management/ingress/secure-ingress-sds/
[2]: https://istiobyexample.dev/secure-ingress/

**Comment by rcreasey** [comment]
This would make cert-manager provisioned secrets much more feasible for mTLS gateway certificate checking.  As it stands now, cert-manager will create a secret off a certificate with `tls.crt`, `tls.key` and `ca.crt` keys.  In my use case, client certificates are signed with the same intermediate CA as the one that's signing the server certificate.  

In the current state of SDS and mTLS, it requires the caCertificate to be in a separate Opaque secret with the same name, just suffixed with `-cacert`.

It would be nice if this were configurable (as I know there's the possibility that some mTLS authentication could have separate intermediates) or just have this be a fallback if it's not discovered in the separate Opaque secret.

**Comment by howardjohn** [comment]
We are supporting the k8s certs: https://github.com/istio/istio/blob/fa1b6b048909bc68ac2f94c61bcdce6d51776fea/tests/integration/security/sds_ingress/util/util.go#L47. I don't think we are creating istio.io/key-and-cert types in 1.5 so I am not sure there is a use case for that?

So it sounds like we probably want to support reading a `ca.crt` key as well instead of the coupled `-cacert` secret as well?

**Comment by rcreasey** [comment]
> So it sounds like we probably want to support reading a ca.crt key as well instead of the coupled -cacert secret as well?

This would be my preference, yes.  It's less dependencies to deal with (one secret versus two) to manage.

**Comment by howardjohn** [comment]
I think that makes sense. The closest thing to a spec I can find is https://kubernetes.io/docs/concepts/services-networking/ingress/#tls which of course doesn't have the `ca.crt` key. do you have any reference to where cert-manager defines this? If we are going off the path of Kubernetes "official" API I want to make sure we are making the right choices and can reference why we used `ca.crt`

**Comment by dhermes** [comment]
> So it sounds like we probably want to support reading a `ca.crt` key as well instead of the coupled `-cacert` secret as well?

This is less of a concern for me; we plan on using SDS for certs signed by a public CA, so bundling the CA cert isn't necessary.

**Comment by howardjohn** [comment]
@dhermes so your case should be solved, right? Or is there more? Not sure what version that was added though

**Comment by dhermes** [comment]
> so your case should be solved, right?

Yes. Also doing a migration from the old cert wasn't **that big of a hassle**, just unnecessary since `cert-manager` was already managing those certs for us and storing them in a canonical format.

**Comment by howardjohn** [comment]
@JimmyCYJ any concern with adding support for ca.crt?

**Comment by rcreasey** [comment]
@howardjohn There appears to have been much discussion around this when it was implemented back in https://github.com/jetstack/cert-manager/pull/848.

**Comment by dhermes** [comment]
@istio-testing Thanks for closing. Is there a link to updated documentation on this newly added support?

(Coincidentally, I just updated all of our clusters today to use `kubernetes.io/tls` secrets, so thanks for the feature! It allowed me to delete a painful cron job that was manually copying over a secret managed by `cert-manager`.)

**Comment by howardjohn** [comment]
Sorry for auto closed by the pr merge, probably should keep this open to ensure properly documented. If it wasn't clear the above pr added ca.crt so you don't need a separate -cacert secret

**Comment by dhermes** [comment]
Ooooh nice! Thanks for the update

**Comment by rcreasey** [comment]
🎉 Thanks for the update!

**Comment by howardjohn** [comment]
https://github.com/istio/istio.io/pull/7025 is the doc update

**Comment by howardjohn** [comment]
Ok I think this is fully done and documented now. if there is any followups feel free to open another issue. Thanks for all the feedback
