### ISSUE TITLE
enableAnalysis doesn't work with 1.5 galley

### ISSUE THREAD

**Issue by esnible** [istio/istio#21074]
To reproduce, using Master, `istioctl manifest generate --set values.galley.enableAnalysis=true | grep -i analysis`.  There will be no `--enableAnalysis` output.

The Istiod deployment does not get the `--enableAnalysis=true` flag.

The Installer _operator/pkg/vfs/assets.gen.go_ is generated from _install/kubernetes/helm/istio/charts/galley/templates/deployment.yaml_ which does include the flag generation, but only for the istio-galley Deployment.  The Istiod Deployment does not have it.

**Comment by ayj** [comment]
`--enableAnalysis` was [experimental in 1.4](https://istio.io/docs/ops/diagnostic-tools/istioctl-analyze/#enabling-validation-messages-for-resource-status) and off by default. Since its still experimental (we didn't have sufficient time to benchmark and stress test at scale) it wasn't included in istiod in 1.5.x. Maybe we can get this into 1.6 which would require completing the necessary testing plus minimal integration of galley's analysis controller into istiod.

**Comment by esnible** [comment]
@ayj Is it possible to deploy Galley with 1.5?

**Comment by ayj** [comment]
You'll need to revert to the non-istiod micro-service deployments.

**Comment by therealmitchconnors** [comment]
This feature was expected to be on by default in 1.6 after performance testing in off-by-default mode in 1.5... What needs to be done to re-add this feature to the project?  Were there any other features which have been removed for istiod?

**Comment by howardjohn** [comment]
> Were there any other features which have been removed for istiod?

Yes, all of Galley was disabled by default, aside from validation which was moved over. As far as I know this means status/analysis and MCP source.

The feature is still around as off-by-default, you can deploy Galley with the flag enabled still.

**Comment by esnible** [comment]
Should we close this?  I was able to get Galley ready to deploy with analysis.

```
istioctl manifest generate --set components.galley.enabled=true --set values.galley.enableAnalysis=true | grep -i analysis
```

I couldn't actually deploy Galley.  See https://github.com/istio/istio/issues/21635 .

**Comment by esnible** [comment]
I was able to get Galley up and running using `./istioctl manifest apply --set components.galley.enabled=true --set values.galley.enableAnalysis=true --set values.global.controlPlaneSecurityEnabled=false`

No statuses appear on the Istio resources, and although the logs for Galley say many analyzers are disabled some are running.

```
...
2020-02-28T20:12:50.604560Z	info	analysis	Skipping analyzer "annotations.K8sAnalyzer" because collection k8s/core/v1/namespaces is disabled.
2020-02-28T20:12:50.604578Z	info	analysis	Skipping analyzer "injection.JwtAnalyzer" because collection k8s/core/v1/services is disabled.
2020-02-28T20:12:50.604586Z	info	analysis	Skipping analyzer "auth.MTLSAnalyzer" because collection k8s/core/v1/pods is disabled.
...
2020-02-28T20:12:50.911633Z	info	source	Starting status controller...
2020-02-28T20:12:54.422861Z	info	processing	Publishing snapshot for group: default
```

**Comment by therealmitchconnors** [comment]
After conversations with the networking team, it sounds like getting this feature working in istiod will be a priority over the next few weeks, and the plan is to release it with 1.5.1 as a bug fix.  For now, I am tracking the work under #21341

**Comment by howardjohn** [comment]
@therealmitchconnors can you please point to where this agreement was made?

**Comment by therealmitchconnors** [comment]
@howardjohn this was in the UX Working group meeting on 2/25, but further conversations have cast doubt on the plan.  What do you think?  This is not a new feature, and it was not intentionally dropped from 1.5, so I can understand the argument that it is a bug fix.  Alternatively, it would be a fairly large change to 1.5.x...

**Comment by howardjohn** [comment]
You can still use analysis if you ship Galley, and we intentional made this decision to ship with Galley disabled by default given what features we ported over to Istiod in 1.5. Re-enabling is far too large of a change for 1.5.x in my opinion

**Comment by hzxuzhonghu** [comment]
Could anyone provide a doc about what does it actually analyze?

**Comment by therealmitchconnors** [comment]
Background Analysis runs the same code as `istioctl analyze` and outputs its results to the status field of the relevant resource.   For more information on analyzers, see our announcement [blog post](https://istio.io/blog/2019/introducing-istioctl-analyze/), or the relevant istio.io [page](https://istio.io/docs/ops/diagnostic-tools/istioctl-analyze/).
