### ISSUE TITLE
istioctl apply with --wait hides errors

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#21088]
If there is an error during apply (for example, CRD apply), and --wait flag is passed, then we will never see any error message. For example: https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/21052/integ-conformance-k8s-tests_istio/1430

tentatively assigning to @ostromart since he was working on the --wait stuff. You can also see that you can't tell what is being waited on

**Comment by shamsher31** [comment]
I'm also seeing same issue in #20598  PR. `--wait` always timeouts. Unfortunately, it works on `minikube` and `kind` cluster. 

https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/20598/integ-istioio-k8s-tests_istio/4732

**Comment by ostromart** [comment]
yes, i'll take this one. i was going to try to fix it quickly but there are a few other must-fix issues for community testing on tue so most likely this will fall into next week unless we can find someone else to work on it today.
