### ISSUE TITLE
Replace `VerifySubjectAltName` with `MatchSubjectAltNames`

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#21096]
xref: https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/cert.proto.html?highlight=downstreamtlscontext#extensions-transport-sockets-tls-v3-certificatevalidationcontext

The VerifySubjectAltName is deprecated, will do it after #21024

**Comment by howardjohn** [comment]
#22822
