### ISSUE TITLE
Implement pure go build + make system

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#2109]
Prerequisites
- [ ] Convert Mixer bazel genrules to go:generate based code gen for Mixer Adapter and Templates. [WIP PR by doug](https://github.com/istio/istio/pull/2073)
- [ ] Make googleapis protos available in gogo compiled form in an istio repo. [why?](https://github.com/istio/api/pull/269.)
- [x] Mixer, Security and Broker use bazel based docker image generation. Switch to using direct docker builds based on scratch. Pilot already does this.

Doc
- [ ] Update developer documentation to use go/make

Tests
- [x] e2e tests use `bazel query`, find something equivalent. 

Repeatable build
- [x] Pin appropriate go prereq versions with `Gopkg.lock`
- [ ]  Ensure that all external dependencies are captured and properly versioned. WORKSPACE has all this.
       go version
       protoc version
       gogo version etc.

Part II .
- [ ] Define standard make targets
    Most of them are already there, they need to be formalized.
- [ ] Recursive make. Every top level component will have its own Make file, it is upto the components owners to maintain the component make files using the standard template.

**Comment by mandarjog** [comment]
@sebastienvas @hklai @Brian-Xincheng-Zhang Please add high level test/release items.
Thanks.

**Comment by Brian-Xincheng-Zhang** [comment]
everyone: please hold on the actual code change before the concrete execution plan is reviewed and approved. The plan will be out tomorrow.

**Comment by rshriram** [comment]
This is great. With respect to make files, until we need the complexity, can we just have one top level makefile that is just a placeholder for invoking go build commands, Docker commands. Codegen scripts can be under bin. There is a lot of other consolidation that can be done later.

**Comment by mandarjog** [comment]
@ldemailly

**Comment by hklai** [comment]
We have drafted a plan:
https://docs.google.com/document/d/1NE-cqziSu91BDUECqaIckInoelVqkbtWpYCYV0W6kDw/edit#heading=h.7zgnj8bwqfld

PTAL. The next step is to have steering committee review and approve the plan.

**Comment by rshriram** [comment]
@sbezverk (cisco) @rosenhouse (pivotal) @vbatts (redhat) @Nino-K (suse/cf) ^^^

**Comment by kyessenov** [comment]
Something that popped-up - bazel/rules_go mishandle go:generate annotations. For the transitional step, we need to be careful with using bazel and go generate at the same time.

**Comment by douglas-reid** [comment]
yeah. once we add `go:generate` we need to remove the bazel generation bits and have bazel point at the generated files directly.

**Comment by kyessenov** [comment]
I'm referring to gazelle/auto-BUILD not playing nice with go:generate.

**Comment by mandarjog** [comment]
https://github.com/istio/istio/pull/2220

**Comment by mandarjog** [comment]
https://github.com/istio/istio/pull/2216

**Comment by sdake** [comment]
subscribe

**Comment by sdake** [comment]
https://github.com/istio/istio/pull/2375

**Comment by rshriram** [comment]
#2370

**Comment by rshriram** [comment]
I think this issue can be safely closed now.
