### ISSUE TITLE
Unable to add envoy csrf filter

### ISSUE THREAD

**Issue by lpamlie** [istio/istio#21105]
**Bug description**

[x ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Expected behaviour is that csrf filter is added to the envoy config

Nothing is added to the envoy config.

Apply this config
![image](https://user-images.githubusercontent.com/34286235/74448014-873b2b80-4e7a-11ea-85d7-6029042ad2f6.png)

client version: version.BuildInfo{Version:"1.1.6", GitRevision:"04850e14d38a69a38c16c800e237b1108056513e", User:"root", Host:"1844d064-72cc-11e9-a0d5-0a580a2c0304", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.5-11-g04850e1"}
citadel version: version.BuildInfo{Version:"1.2.9", GitRevision:"b399bbd5a40f0a295a7ae729b6be14a0954d31fc-dirty", User:"root", Host:"831fb6fb-ff63-11e9-a693-3ec0efaaa1c8", GolangVersion:"go1.12.12", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.2.8-3-gb399bbd"}
galley version: version.BuildInfo{Version:"1.2.9", GitRevision:"b399bbd5a40f0a295a7ae729b6be14a0954d31fc-dirty", User:"root", Host:"831fb6fb-ff63-11e9-a693-3ec0efaaa1c8", GolangVersion:"go1.12.12", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.2.8-3-gb399bbd"}
ingressgateway version: version.BuildInfo{Version:"1.2.9", GitRevision:"b399bbd5a40f0a295a7ae729b6be14a0954d31fc", User:"root", Host:"831fb6fb-ff63-11e9-a693-3ec0efaaa1c8", GolangVersion:"go1.12.12", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.2.8-3-gb399bbd"}
pilot version: version.BuildInfo{Version:"1.2.9", GitRevision:"b399bbd5a40f0a295a7ae729b6be14a0954d31fc-dirty", User:"root", Host:"831fb6fb-ff63-11e9-a693-3ec0efaaa1c8", GolangVersion:"go1.12.12", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.2.8-3-gb399bbd"}
pilot version: version.BuildInfo{Version:"1.2.9", GitRevision:"b399bbd5a40f0a295a7ae729b6be14a0954d31fc-dirty", User:"root", Host:"831fb6fb-ff63-11e9-a693-3ec0efaaa1c8", GolangVersion:"go1.12.12", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.2.8-3-gb399bbd"}
pilot version: version.BuildInfo{Version:"1.2.9", GitRevision:"b399bbd5a40f0a295a7ae729b6be14a0954d31fc-dirty", User:"root", Host:"831fb6fb-ff63-11e9-a693-3ec0efaaa1c8", GolangVersion:"go1.12.12", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.2.8-3-gb399bbd"}
pilot version: version.BuildInfo{Version:"1.2.9", GitRevision:"b399bbd5a40f0a295a7ae729b6be14a0954d31fc-dirty", User:"root", Host:"831fb6fb-ff63-11e9-a693-3ec0efaaa1c8", GolangVersion:"go1.12.12", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.2.8-3-gb399bbd"}
pilot version: version.BuildInfo{Version:"1.2.9", GitRevision:"b399bbd5a40f0a295a7ae729b6be14a0954d31fc-dirty", User:"root", Host:"831fb6fb-ff63-11e9-a693-3ec0efaaa1c8", GolangVersion:"go1.12.12", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.2.8-3-gb399bbd"}
sidecar-injector version: version.BuildInfo{Version:"1.2.9", GitRevision:"b399bbd5a40f0a295a7ae729b6be14a0954d31fc-dirty", User:"root", Host:"831fb6fb-ff63-11e9-a693-3ec0efaaa1c8", GolangVersion:"go1.12.12", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.2.8-3-gb399bbd"}
telemetry version: version.BuildInfo{Version:"1.2.9", GitRevision:"b399bbd5a40f0a295a7ae729b6be14a0954d31fc-dirty", User:"root", Host:"831fb6fb-ff63-11e9-a693-3ec0efaaa1c8", GolangVersion:"go1.12.12", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.2.8-3-gb399bbd"}

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"c83d931fb9bece427bc63a02349755e0f8696d3e", GitTreeState:"clean", BuildDate:"2020-01-31T20:09:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

Istio was installed using istoctl

The bug was observed in AKS

**Comment by esnible** [comment]
@lpamlie Please attach your Istio EnvoyFilter as plain text or a file, not as a screenshot.

Possibly related: https://github.com/istio/istio/issues/21265

**Comment by lpamlie** [comment]
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: csrf-filter
  namespace: test
spec:
  configPatches:
    - applyTo: HTTP_ROUTE
      match:
        routeConfiguration:
          vhost:
            route:
              name: default
        context: SIDECAR_INBOUND
      patch:
        operation: MERGE
        value:
          per_filter_config:
            envoy.csrf:
              filter_enabled:
                default_value:
                  numerator: 100
                  denominator: HUNDRED

**Comment by lpamlie** [comment]
Hi

Thanks for looking into this.  I had some problems with the yaml formatting, hence the screenshot but now I attached the yaml

**Comment by howardjohn** [comment]
Can you try something like? per filter config will not work anymore

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: csrf-filter
spec:
  configPatches:
    - applyTo: HTTP_ROUTE
      patch:
        operation: MERGE
        value:
          typed_per_filter_config:
            envoy.csrf:
              "@type": type.googleapis.com/envoy.extensions.filters.http.csrf.v3.CsrfPolicy
              filter_enabled:
                default_value:
                  numerator: 100
                  denominator: HUNDRED
```

I have tested this

**Comment by howardjohn** [comment]
Based on the above I think this is working now. Please reopen if you see issues on recent versions
