### ISSUE TITLE
istio make coverage seems not to work

### ISSUE THREAD

**Issue by gnirodi** [istio/istio#2111]
https://github.com/istio/istio/blob/master/DEV-GUIDE.md#getting-coverage-numbers

make coverage
make: *** No rule to make target `coverage'.  Stop.

It's possible the instructions are missing some steps.

**Comment by jmuk** [comment]
Seems `make coverage` has been dropped since monorepo. I found `bin/parallel-codecov.sh` script. Will add.

**Comment by jmuk** [comment]
ah, there's `bin/codecov.sh` as well...

**Comment by sdake** [comment]
Closing - works on master after native build tooling rework.

```
sdake@falkor-07:~/go/src/istio.io/istio$ make kubelink
ln -fs ~/.kube/config pilot/platform/kube/
sdake@falkor-07:~/go/src/istio.io/istio$ make coverage
bin/parallel-codecov.sh pilot
Code coverage test
+ set +x
+ go test -coverprofile=/tmp/coverage/istio.io-istio-pilot-adapter-config-aggregate.txt istio.io/istio/pilot/adapter/config/aggregate
+ set +x

... lots of output ...

?   	istio.io/istio/broker/cmd/brks	[no test files]
?   	istio.io/istio/broker/cmd/brkcol	[no test files]
ok  	istio.io/istio/broker/pkg/platform/kube/crd	5.338s	coverage: 60.7% of statements
sdake@falkor-07:~/go/src/istio.io/istio$ 
```

The `make kubelink` step is a little clunky and depends on a functional Kubernetes deployment in order to run coverage tests.  without `make kubelink` the coverage tests fail.
