### ISSUE TITLE
SDS does not follow XDS protocol: NACKs are not processed, leading to infinite loops

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#21111]
XDS protocol specifies how NACKs should be handled: https://www.envoyproxy.io/docs/envoy/latest/api-docs/xds_protocol#nack

This is ignored by our SDS implementation. If a request is NACKed, we will immediately send the same exact response again, which will be NACKed, ... repeat infinity.

There are other places where we are not following the protocol as well, but this issue is scoped to this one

cc @JimmyCYJ @costinm

**Comment by JimmyCYJ** [comment]
Thanks, @howardjohn I filed an [issue](https://github.com/istio/istio/issues/15850) to track the error_detail but didn't have a chance to look into it. We need to fix the sds agent to handle this case correctly.

**Comment by JimmyCYJ** [comment]
cc @myidpt

**Comment by duderino** [comment]
1.5 release blocker because we are turning SDS on by default for 1.5 and this is a regression relative to 1.4 secret mount implementation

**Comment by myidpt** [comment]
I'll fix this.

**Comment by myidpt** [comment]
Update: I got the PR almost out. Still working on the tests. I will send out the PR tonight.

**Comment by duderino** [comment]
Thanks @myidpt!  @lambdai suspects but hasn't been able to prove yet that this is the root cause of some high Envoy memory usage reports we have received.

**Comment by myidpt** [comment]
I think this is more likely to be triggered on the ingress gateway, when invalid key/certs are received, Envoy will be busy re-sending the NACK requests. Not sure for the sidecars - unless the Envoy considers the key/certs generated by CA to be invalid. But I'd like to learn more about the observation @lambdai .
