### ISSUE TITLE
Working patterns of TimeOut and Retry patterns in Istio. Some unexpected behavior's while used in combination

### ISSUE THREAD

**Issue by krishnaputhran** [istio/istio#21137]
Hi,
I like to understand how retry and Time Out patterns will work when applied on the same service. I'll first explain what I have tried and how it behaved.  For eg:
	
Case-1: My service "member" takes 7s to resond for any request received. When I tried to apply a pattern "timeOut" 2s as shown below for the service as shown below...

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: retry-member
spec:
  hosts:
  - member
  http:
  - route:
    - destination:
        host: member
    timeout: 2s 

Now the behavior is as expected and the request timed out in 2s and no issues.

=========================================================================
Case-2: My service "member" takes 7s to resond for any request received. When I tried to apply a pattern "retry" along with "TimeOut" with timeOut=2s as shown below.

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: retry-member
spec:
  hosts:
  - member
  http:
  - route:
    - destination:
        host: member
    retries:
      attempts: 3
    timeout: 2s 
	
Here the caller got timed-out response in 2s and retry never got control. I didn't observe retries after the timeOut period is over. I appreciate if someone can explain me this behavior as what's the precedence. I feel, when both "timeOut" and "retries" are applied on the same pattern, timeOut takes precedence. Hope this is the expected behavior

	  
=========================================================================
Case-3: My service "member" takes 7s to resond for any request received. When I tried to apply a pattern "retry" along with "TimeOut" with timeOut=2s, and for retry::perTryTimeout: 1s as shown below

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: retry-member
spec:
  hosts:
  - member
  http:
  - route:
    - destination:
        host: member
    retries:
      attempts: 5
      perTryTimeout: 1s
	  retryOn: 5xx	  
    timeout: 2s 

My first request gets failed 5xx error so that retry gets triggered. After the first error ( which I simulate), I get the retry attempt message. And the retry sends 2 requests one after the other, as it gets perTryTimeout within 1s. The member service receives only 2 retry requests and caller gets the time out response after 2 retries. Here after 2 attempts the "timeout" limit of 2s is exceeded, so remaining 3 attempts from the retries is not tried. Here I hope the combination is working as expected. 

=========================================================================
Case-4: My service "member" takes 7s to resond for any request received. When I tried to apply a pattern "retry" along with retry::perTryTimeout: 1s as shown below

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: retry-member
spec:
  hosts:
  - member
  http:
  - route:
    - destination:
        host: member
    retries:
      attempts: 3
      perTryTimeout: 1s
	  retryOn: 5xx

My first request to member service, gets failed 5xx error so that retry gets triggered. After the first error ( which I simulate), I get the retry attempt message. But with perTryTimeout:1s, I expected the retry to attempt all the 3 attempts and respond the caller with time out error. But observed behavior is that, the first retry attempt waits till the application responds ( thats with 7s delay) and gets the success response. Here my perTryTimeout is not taken into consideration and retry waits till the application responds.

**Comment by krishnaputhran** [comment]
Also please note that, my yml posting is incorrectly aligned in the display. If I try and edit, it shows the correct alignment. Please note, the ordering of yml is correctly maintained in my deployment.

**Comment by esnible** [comment]
It might be better to ask questions in https://discuss.istio.io

Github comments use markdown; to preserve formatting put three backticks above and below a code snippet.
