### ISSUE TITLE
Istio components are not getting installed on a private GKE cluster

### ISSUE THREAD

**Issue by MeghanaSrinath** [istio/istio#21138]
I'm trying to install Istio on a private GKE cluster. I have downloaded the version 1.4.3 of Istio and then applied the default profile. But not all the components are getting installed from the manifest. Below are the error logs.
```
$ istioctl manifest apply

This will install the default Istio profile into the cluster. Proceed? (y/N) y
- Applying manifest for component Base...
✔ Finished applying manifest for component Base.
- Applying manifest for component Pilot...
- Applying manifest for component Policy...
- Applying manifest for component Galley...
- Applying manifest for component Citadel...
- Applying manifest for component IngressGateway...
- Applying manifest for component Prometheus...
- Applying manifest for component Telemetry...
- Applying manifest for component Injector...
✘ Finished applying manifest for component Pilot.
✘ Finished applying manifest for component Telemetry.
✔ Finished applying manifest for component Prometheus.
✔ Finished applying manifest for component Citadel.
✔ Finished applying manifest for component Galley.
✔ Finished applying manifest for component Policy.
✔ Finished applying manifest for component Injector.
✔ Finished applying manifest for component IngressGateway.

Component Pilot - manifest apply returned the following errors:
Error: error running kubectl: signal: killed


Component Kiali - manifest apply returned the following errors:
Error: error running kubectl: exit status 1

Error detail:

Unable to connect to the server: dial tcp 192.168.0.2:443: i/o timeout (repeated 1 times)


apiVersion: v1
items: []
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""



Component Grafana - manifest apply returned the following errors:
Error: error running kubectl: exit status 1

Error detail:

Unable to connect to the server: dial tcp 192.168.0.2:443: i/o timeout (repeated 1 times)


apiVersion: v1
items: []
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""



Component Telemetry - manifest apply returned the following errors:
Error: error running kubectl: exit status 1

Error detail:

Unable to connect to the server: net/http: request canceled (Client.Timeout exceeded while awaiting headers) (repeated 1 times)






✘ Errors were logged during apply operation. Please check component installation logs above.

Failed to generate and apply manifests, error: errors were logged during apply operation

```

Also, the ingress gateway is not getting created from any of the sample applications (helloworld, bookinfo). Below is the error:
```
$ kubectl apply -f samples/bookinfo/networking/bookinfo-gateway.yaml

Error from server (Timeout): error when creating "samples/bookinfo/networking/bookinfo-gateway.yaml": Timeout: request did not complete within requested timeout 30s
Error from server (Timeout): error when creating "samples/bookinfo/networking/bookinfo-gateway.yaml": Timeout: request did not complete within requested timeout 30s

```
However, I tried to use istio along with GKE on the same private cluster by following the guide [here](https://cloud.google.com/istio/docs/istio-on-gke/installing#creating_a_cluster_with_istio_on_gke)

This worked and all the components are installed successfully, along with the ingress gateway.
I have enabled the ports 80,8080,1000-2000,22,443 on the network as well.
Can please someone tell us what would be the issue causing this error.

Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.12-gke.25", GitCommit:"654de8cac69f1fc5db6f2de0b88d6d027bc15828", GitTreeState:"clean", BuildDate:"2020-01-14T06:01:20Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
```
Istio version:
```
client version: 1.4.3
control plane version: 1.4.3
data plane version: 1.4.3 (1 proxies)
```
Platform: GKE

OS: Ubuntu

**Comment by MeghanaSrinath** [comment]
I have now installed Istio v1.2.10 on the same private GKE cluster and all the Istio components/ ingress gateways are getting installed correctly. Is there a reason why this is not working from v1.3+ onwards?

**Comment by bbhuston** [comment]
Having exact same issue with a fresh istio operator (istio 1.5) install on a private gke v14.7 cluster.  If you pass the `--request-timeout 50s` flag to kubectl when you create istio CRs (i.e., gateways, virtualservices, etc), then the resources will create.  Still a pain though.

`kubectl apply -f example-virtualservice.yaml --request-timeout 50s` # this should work

**Comment by MeghanaSrinath** [comment]
Thanks to this [post](https://github.com/istio/istio/issues/19532), I was able to get Istio 1.4.5 installed on GKE version 1.14+ by enabling port 9443 on the master node's firewall.
But this is not documented in the Istio installation guide. If this can be highlighted somewhere in their documents, it'd be better. Or if there is any other workaround, we could follow that.

**Comment by haf** [comment]
Opening port 15017 as well as 9443 on private GKE clusters worked for me for 1.5.2 (as per https://github.com/istio/istio/issues/19532#issuecomment-595769193 and (too long) https://github.com/istio/istio/issues/22944#issuecomment-614938014)

**Comment by howardjohn** [comment]
This is now documented in https://preliminary.istio.io/docs/setup/platform-setup/gke/ and tracking improving the UX in https://github.com/istio/istio/issues/19532#issuecomment-595769193. Thanks!

**Comment by upodroid** [comment]
I think we can close this out. https://istio.io/docs/setup/platform-setup/gke/ has instructions for amending the firewall for private gke clusters.
