### ISSUE TITLE
If istio-sidecar-injector workload is removed or crashes, no pods can be scheduled to run

### ISSUE THREAD

**Issue by baabel** [istio/istio#21147]
**Bug description**
In GKE I deleted one of my Node Pools in the cluster. As part of the removal, GKE removed workloads from the nodes in the pool. The sidecar injector pod was one of the workloads removed. When the istio-sidecar-injector pod was deleted by kubernetes all subsequent pod operations fail because kubernetes attempts to call the controller webhook that is not running. Can't start the sidecar workload for the same reason (catch-22): no endpoints available

describe any pod:
Internal error occurred: failed calling webhook "sidecar-injector.istio.io": Post https://istio-sidecar-injector.istio-system-datach-npe.svc:443/inject?timeout=30s: no endpoints available for service "istio-sidecar-injector"	0/1
Serving pods

At this point I had to delete the controller webhook config:
kubectl   delete  MutatingWebhookConfiguration istio-sidecar-injector

and re-run the istio manifests.

Although this happened during a node pool delete, I have seen the same behavior if the sidecar crashes or can't be scheduled.

**Expected behavior**
Able to recover from sidecar-injector workload restart or crash 

**Steps to reproduce the bug**
Delete the sidecar-injector pod.

**Version 1.3.8 (also in 1.3.6)

**How was Istio installed?**
Helm + kubectl

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE:  1.14.8-gke.33

Workaround:
delete the controller webhook config:
kubectl   delete  MutatingWebhookConfiguration istio-sidecar-injector
re-run istio manifests

**Comment by ayj** [comment]
By default MutatingWebhookConfiguration is opt-in and only targets namespaces labeled istio-injection=enabled. Did you add this label istio-system? Alternatively, if you changed MutatingWebhookConfiguration to be opt-out you'll need to add the istio-injection=disabled label to istio-system.

**Comment by baabel** [comment]
Understood, only my app namespace has that label. The problem is kubernetes
expects the webhook workload to be running, which it is not... I believe
the logic around the label is in the sidecar injector which is not running.
If admission webhook workload is not running kubernetes "throws" this error.

Thanks,
Brian

**Comment by baabel** [comment]
Ok I see, it's part of the match label on the mutatingwebhookconfiguration.
I looked at the labels on the wrong istio namespace, we have multiple in
same cluster and yes the one where it happenes has the namespace
label...thanks and sorry about that.

Brian.
