### ISSUE TITLE
Possible to use one appliaction LB (AWS) for istio and Traefik?

### ISSUE THREAD

**Issue by SCLogo** [istio/istio#21140]
Hello team,

It is just a question. Can I use one load balancer for istio and traefik? If yes, could you please give me documents how to reach this goal ? 

Thanks
Balazs

**Comment by leaderwolfpipi** [comment]
6666

**Comment by howardjohn** [comment]
Kubernetes LoadBalancer type applies to a single service. So I think you cannot do this, at least without doing some weird things. 

If you can, please take a look at https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/. This is purely Kubenetes configuration, not Istio, as Istio just receives the traffic from the LB. Thanks!
