### ISSUE TITLE
Pilot deployment not pruned on istioctl upgrade from 1.4 to 1.5

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#21159]
Repro steps:

```
~/istio/istio-1.4.4/bin/istioctl manifest apply --set values.grafana.enabled=true
~/istio/master/bin/istioctl manifest apply -y --set values.grafana.enabled=true
```

You will find pilot instance remains. This is likely caused by `--prune-whitelist=envoyfilter` making it not prune deployments

Likely broken by https://github.com/istio/istio/pull/21055#discussion_r378061346

**Comment by ostromart** [comment]
I verified that is indeed the case. Prune replaces the default whitelist, not adds to it. From kubectl help:
```
 --prune-whitelist=[]: Overwrite the default whitelist with <group/version/kind> for --prune
```
So we need to pass the entire list here, not just envoyfilter. Also let's create a test since this should've been caught in the original PR.

**Comment by richardwxn** [comment]
oh ok believed it was additive when I did testing, I would create a fix to add the previous whitelisted types
