### ISSUE TITLE
location header not generated correctly when running make gen

### ISSUE THREAD

**Issue by ostromart** [istio/istio#21152]
Istio.io proto scraper is here: https://github.com/istio/istio.io/blob/master/scripts/grab_reference_docs.sh
example location tags are here: https://github.com/istio/api/blob/00efe7317328e74d4ae0fb2213e45c6d61e7713c/mesh/v1alpha1/config.proto#L22
this should generate HTML like this:
https://github.com/istio/api/blob/00efe7317328e74d4ae0fb2213e45c6d61e7713c/mesh/v1alpha1/istio.mesh.v1alpha1.pb.html#L2
In the case of operator, it generates vanilla header, seemingly missing the location header there:
https://github.com/istio/api/blob/00efe7317328e74d4ae0fb2213e45c6d61e7713c/operator/v1alpha1/istio.operator.v1alpha1.pb.html#L2

**Comment by therealmitchconnors** [comment]
Is the problem here that 'make gen' is generating an incorrect html file, or that grab_reference_docs.sh is not copying the file to the correct directory?

**Comment by ostromart** [comment]
to expand on this, the doc generation plugin is not working correctly. the proto header looks correct and protoc is outputting the right go structs, but the docs header is not being generated in the plugin.

**Comment by richardwxn** [comment]
@jasonwzm Do you have any idea why the location tag would not be generated in the html file only for operator proto? I looked at the htmlGenerator's code and didn't find anything suspicious.
