### ISSUE TITLE
TestStsCache test flake

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#21153]
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/20915/unit-tests_istio/8616

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/21293/unit-tests_istio/8861

**Comment by JimmyCYJ** [comment]
This is duplicated of https://github.com/istio/istio/issues/19918,
By checking test grids, this one is deflaked now.
https://testgrid.k8s.io/istio_istio#unit-tests_istio
