### ISSUE TITLE
There is no istio-egress after install 0.3.0

### ISSUE THREAD

**Issue by gyliu513** [istio/istio#2116]
In the document here https://istio.io/docs/setup/kubernetes/quick-start.html#verifying-the-installation , it is claiming there is a service named as `istio-egress`, but after installation of 0.3.0, there is no such service and I also checked the source code, there is no such service. Am I missing anything? @rshriram @linsun 

```
  NAME            CLUSTER-IP      EXTERNAL-IP       PORT(S)                       AGE
  istio-egress    10.83.247.89    <none>            80/TCP                        5h
  istio-ingress   10.83.245.171   35.184.245.62     80:32730/TCP,443:30574/TCP    5h
  istio-pilot     10.83.251.173   <none>            8080/TCP,8081/TCP             5h
  istio-mixer     10.83.244.253   <none>            9091/TCP,9094/TCP,42422/TCP   5h

```

**Comment by rshriram** [comment]
Ooh.. good catch.. can you update the documentation? We no longer have istio-egress.

**Comment by jmuk** [comment]
The same thing was questioned in stackoverflow, so I reported as https://github.com/istio/istio.github.io/issues/792. Let me close this since it's a doc issue.
