### ISSUE TITLE
istio-sidecar-injector should not operate in kube-system namespace

### ISSUE THREAD

**Issue by desek** [istio/istio#21172]
**Bug description**

The MutatingWebhookConfiguration for Automatic Istio Injection is not namespaced and is operating in the kube-system namespace ~~even with label `istio-injection=disabled`~~.  
This can cause Kubernetes with CNI enabled (i.e. Calico) to transfer into a limbo state due to failing to connect to istio-sidecar-injector service which in turn fails creation of CNI Pods for cluster networking.

An example of the error message that can occur:

```bash
Warning  FailedCreate  32m (x27 over 18h)  replicaset-controller  Error creating: Internal error occurred: failed calling webhook "sidecar-injector.istio.io": Post https://istio-sidecar-injector.istio-system.svc:443/inject?timeout=30s: context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

[ ] Configuration Infrastructure  
[ ] Docs  
[X] Installation  
[X] Networking  
[X] Performance and Scalability  
[X] Policies and Telemetry  
[ ] Security  
[ ] Test and Release  
[X] User Experience  
[ ] Developer Infrastructure  

**Expected behavior**

Automatic Sidecar Injection mutating webhook not operating in kube-system namespace, i.e. the webhook to istio-sidecar-injector is never sent in kube-system namespace.

This should be easy to achieve with adding `kube-system` to the list of namespaces in `namespaceSelector` in the `istio-sidecar-injector` MutatingWebhookConfiguration and change `scope` from `*` to `namespaced`.

For more information refer the official docs: https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#avoiding-operating-on-the-kube-system-namespace

**Steps to reproduce the bug**

1. Deploy Istio with automatic sidecar injection disabled
2. Deny network access from kube-system namespace to istio-system namespace
3. Deploy a pod in kube-system namespace

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```bash
# istioctl version --remote
client version: unknown
control plane version: 1.4.3

# kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:42:50Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"c83d931fb9bece427bc63a02349755e0f8696d3e", GitTreeState:"clean", BuildDate:"2020-01-31T20:09:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

# helm version
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
```

**How was Istio installed?**

Via Helm chart with `global.mtls.enabled=true` and `global.proxy.autoInject=enabled`.

**Environment where bug was observed (cloud vendor, OS, etc)**

Azure Kubernetes Service with Calico.

**Comment by jeffgriffith** [comment]
I ran into this as well. I didn't realize it was operating on kube-system until yesterday Microsoft decided to update AKS. some pods like calico, dns, and tunnelfront could not come back because the API was inaccessible. we have several other pre-installed components from our infrastructure that get affected as well that we'll need to label, but i guess that's the price of having it automatic injection.

**Comment by howardjohn** [comment]
Is there any reason you cannot add istio-injection=disabled to kube-system? While kube-system is generally a special case I am a bit hesitant to make it impossible to inject there, given we already have a mechanism to avoid injection there.

I don't think scope helps here - seems like its about whether the resource is cluster scope or namespace scoped, and we only select pods so it will not change anything. That is how I interpreted

>   scope        <string>
>      scope specifies the scope of this rule. Valid values are "Cluster",
>      "Namespaced", and "*" "Cluster" means that only cluster-scoped resources
>      will match this rule. Namespace API objects are cluster-scoped.
>      "Namespaced" means that only namespaced resources will match this rule. "*"
>      means that there are no scope restrictions. Subresources match the scope of
>      their parent resource. Default is "*".

At least

**Comment by desek** [comment]
How about making excluded namespaces configurable? I.e. adding namespaces to the list at;

https://github.com/istio/istio/blob/a671e62bd1ca3e6fd09bd0fbe03545c136b0f3f5/manifests/charts/istio-control/istio-discovery/templates/mutatingwebhook.yaml#L32-L35
