### ISSUE TITLE
go build failed for https://github.com/istio/istio/wiki/Mixer-Out-Of-Process-Adapter-Walkthrough#step-3-link-adapter-config-with-adapter-code-and-add-business-logic

### ISSUE THREAD

**Issue by mengxu2018** [istio/istio#21173]
I am referring the doc https://github.com/istio/istio/wiki/Mixer-Out-Of-Process-Adapter-Walkthrough#step-3-link-adapter-config-with-adapter-code-and-add-business-logic to create the adapter.

But in the step 3, when I execute the 'go build ./...', it will fail
```
[root@localhost mygrpcadapter]# go build ./...
go: finding istio.io/istio/pkg/log latest
go: finding istio.io/istio/pkg latest
build command-line-arguments: cannot load istio.io/istio/pkg/log: no matching versions for query "latest"
```
note: in the step1, step2, I also ran the 'go build' successfully, but in step3, after paste the large piece of code to 'mygrpcadapter.go', it failed.

**Comment by douglas-reid** [comment]
@mengxu2018 I'm sorry that the docs appear to be broken. Mixer is deprecated. 1.7 will be the last release in which it is included in Istio. It has been entirely removed from the codebase. I'm going to close this issue. Future Istio extensions should be built with proxy-wasm.
