### ISSUE TITLE
How to upgrade if the istio old verison was installed using helm template?

### ISSUE THREAD

**Issue by sanigo** [istio/istio#21171]
The istio old verison was installed using helm template. 
There are no accordingly upgrade-guide for it?

**Comment by JacksChoco** [comment]
I usually upgrade istio version by `kubectl apply --force`. I think no best solution.

**Comment by richardwxn** [comment]
You can try istioctl manifest migrate command to generate the new IstioOperator file from helm values.yaml: https://github.com/istio/istio/blob/master/operator/README.md#migration-from-valuesyaml, which then you can use istioctl to install with

**Comment by sanigo** [comment]
so, I think I should use helm install to perform the  deployment.

**Comment by esnible** [comment]
Is anyone from @istio/wg-docs-maintainers able to take over this item?

**Comment by esnible** [comment]
@frankbu Can you triage this from the Docs point of view?  Does it belong here or in istio.io repo?

**Comment by frankbu** [comment]
@esnible The think @istio/wg-environments-maintainers needs to figure out what the upgrade story is for all possible previous installations, before it can be documented.

**Comment by howardjohn** [comment]
This can be handled with https://preliminary.istio.io/docs/setup/upgrade/#canary-upgrades
