### ISSUE TITLE
Pilot Ledger memory leak/excessive usage

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#21186]
![2020-16-02_13-57-18](https://user-images.githubusercontent.com/623453/74613568-61a16280-50c4-11ea-8477-ff9af0b6a20d.png)

After running in a medium sized cluster for a week or so, memory looks like this. I believe its constantly growing as well

**Comment by therealmitchconnors** [comment]
Is this on Istio 1.5?  Which build, and what sort of perf scenario was being run?

**Comment by howardjohn** [comment]
This was 1.4.5. I have 15 namespaces and each one I change a virtual service every 10s or so. I ran it for maybe a week

**Comment by therealmitchconnors** [comment]
ok, thanks, will investigate...

were you by chance using one of the reproducible scenarios in the tools repo?  I'd like to try and attach a debugger to investigate.

**Comment by howardjohn** [comment]
Yeah I just had 15 instances of the `load` test

**Comment by mdhume** [comment]
@howardjohn @therealmitchconnors Was there any update on this? We had a pilot memory leak issue recently. We are using istio 1.4.6. Unfortunately the pilot pods got OOM killed before we could get a heap dump so we don't have a lot of additional information at this time. So far not able to reproduce the issue.

**Comment by howardjohn** [comment]
Not stale

**Comment by howardjohn** [comment]
consider this a duplicate of https://github.com/istio/istio/issues/28015
