### ISSUE TITLE
Multi-version CRDs

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#2119]
Ref: https://kubernetes.io/docs/concepts/api-extension/custom-resources/

CRDs do not support multiple versions per group-kind. This is noted as a decision point in the doc above to choose between CRDs and aggregated API server. Since Istio is now adding v1alpha2 version of config, we need to accommodate it somehow in our config model:
- wait until k8s adds version conversions to CRDs
- implement a custom API server with our own storage
- (hack) encode version in kind

cc @rshriram @ijsnellf

**Comment by kyessenov** [comment]
I raised this concern to @rshriram who's eager to have both versions together for route rules.
I'm also OK completely removing v1alpha1 without much thought, but that will annoy anyone who's looking to use Istio seriously and started writing config. 

I don't have much confidence that CRDs will be first-class in k8s sooner than 6 months out.

**Comment by rshriram** [comment]
I don't want to have both simultaneously. I just wanted a global option that would allow people to pick v1alpha1 or v1alpha2. But in retrospect, that seems like more hassle than use, since we have to update templates, etc.

Keep in mind that we will have this issue irrespective of routing. If I want to add new stuff to route rules, do make it v1beta2 and stop supporting v1beta1 ? That seems unreasonable. Since we are not in beta, we have time to sort this out.

**Comment by ayj** [comment]
That gives us ~3 months to sort this out assuming Routing API goes beta end of Q1.

**Comment by gjwestlife** [comment]
K8s is considering to prioritize this versioning support in CRD as Service catalog has the same request for them. I will confirm their timeline.

**Comment by ozevren** [comment]
This is an external dependency issue. I reassigned to myself to follow through on this.

**Comment by irisdingbj** [comment]
starting from kubernetes 1.11, crds has multiple version support. So we should add this support for istio as well in 1.2

**Comment by ozevren** [comment]
We can use multi-version CRDs at this point, so long as the schema for both versions stays the same:
https://docs.google.com/document/d/1lpTU96_TFKcRWF6-yO4cgt3eqglaaF5KVeRKpnkzXAA/edit

Moving to 1.3

**Comment by ozevren** [comment]
@jasonwzm I am assigning this to you, to verify https://docs.google.com/document/d/1lpTU96_TFKcRWF6-yO4cgt3eqglaaF5KVeRKpnkzXAA We should be able to support multi-version CRDs now, as long as they have the same schema.

(Additionally there will be work on a conversion webhook for conversion coming up).

**Comment by esnible** [comment]
@jasonwzm Do we expect this in 1.6?  How does it relate to https://github.com/istio/istio/issues/14330 ?

**Comment by howardjohn** [comment]
This is done
