### ISSUE TITLE
endpoint of service entry does not work as expected

### ISSUE THREAD

**Issue by pandagodyyy** [istio/istio#21194]
**Bug description**
I have a service entry as below
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: google
  namespace: zqiao
spec:
  hosts:
    - ooo
  location: MESH_INTERNAL
  ports:
    - number: 80
      name: http
      protocol: HTTP
  resolution: DNS
  endpoints:
    - address: www.google.com
I expect when application trigger http://ooo, the request will go to "www.google.com".
However it return host is not resolved, it seems endpoint does not take affect.

I use curl to trigger http://ooo, it got same result, whatever I set HTTP_PROXY=http://localhost/,

**Expected behavior**
want to learn example from
https://istio.io/docs/reference/config/networking/service-entry/
**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**
   istio default profile, version = 1.4
**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
a service entry does not add any DNS addresses, so that its why it fails to resolve.

**Comment by pandagodyyy** [comment]
@howardjohn, do you mean reconfigure as below ?
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: google
  namespace: zqiao
spec:
  hosts:
    - ooo
  addresses: www.google.com
  location: MESH_EXTERNAL
  ports:
    - number: 80
      name: http
      protocol: HTTP
  resolution: DNS
  endpoints:
    - address: www.google.com

**Comment by howardjohn** [comment]
when you run `curl ooo` it will try to resolve the `ooo` address which fails. If you instead did `curl localhost -h "Host: ooo" it should work

**Comment by pandagodyyy** [comment]
@howardjohn ,I tried # curl -v -H "HOST: ooo" http://localhost
still failed with below error
* Immediate connect fail for ::1: Address not available
* Failed to connect to localhost port 80: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost port 80: Connection refused

**Comment by howardjohn** [comment]
@pandagodyyy can you post a config dump? https://github.com/istio/istio/wiki/Troubleshooting-Istio
