### ISSUE TITLE
Derive sd tracer project from cluster metadata

### ISSUE THREAD

**Issue by bianpengyuan** [istio/istio#21193]
Currently Stackdriver tracer project id is derived from GCE default credential, which will not be available if Workload identity is enabled:
https://github.com/istio/istio/blob/9b0c55e43d6bc500f8c765e77b3102c4eedfef9b/pkg/bootstrap/config.go#L283

Instead, it should derive project id from cluster metadata:
https://github.com/istio/istio/blob/9b0c55e43d6bc500f8c765e77b3102c4eedfef9b/mixer/adapter/stackdriver/stackdriver.go#L87

**Comment by gargnupur** [comment]
@bianpengyuan : will cluster metadata be always there? then we can get rid of deriving from GCE default credential?

**Comment by bianpengyuan** [comment]
Yes it should always be there.
