### ISSUE TITLE
Whether istio support jwt revoke (in case hacker get token)

### ISSUE THREAD

**Issue by johnzheng1975** [istio/istio#21192]
**Describe the feature request**
Whether istio support jwt revoke? If not, is there any best practice if I need implement jwt revoke by myself.
You know, it is useful to avoid hacker, or user log out.
Thanks.

**_Note_**: I am using istio jwt verify like below.
```
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "jwt-example"
spec:
  targets:
  - name: httpbin
  origins:
  - jwt:
      issuer: "testing@secure.istio.io"
      jwksUri: "https://raw.githubusercontent.com/istio/istio/release-1.4/security/tools/jwt/samples/jwks.json"
  principalBinding: USE_ORIGIN
``



**Additional context**

**Comment by johnzheng1975** [comment]
I will use istio mixer adapt to handle this.

**Comment by dudash** [comment]
was curious about this same thing - did you find an answer?
