### ISSUE TITLE
upstream connect error or disconnect/reset before headers. reset reason: connection termination

### ISSUE THREAD

**Issue by shahid-mushtaq** [istio/istio#21200]
Hi , i am new to istio , i have ran into this bug 

"upstream connect error or disconnect/reset before headers. reset reason: connection termination"

let' say my website is running on mydomain.com

in my website i have routed traffic on static ip  let's say 192.168.0.1
port 80 is being forward to 32285
and port 40 is being forward to 31970

when i visit my website http://www.mydomain.com it displays proper web page
but when i visit my website https://www.mydomain.com it displays above mentioned error.

if i m logged into ssh using root and run following command

curl -v -HHost:mydomain.com http://192.168.0.1:32285/

it outputs 

*   Trying 192.168.0.1...
* Connected to 192.168.0.1 (192.168.0.1) port 32285 (#0)
> GET / HTTP/1.1
> Host:mydomain.com
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 200 OK
< server: istio-envoy
< content-type: text/html; charset=UTF-8
< x-powered-by: PHP/7.3.14
< cache-control: no-cache, private
< and so o

and displays rest of the web page which is good so far

and when i run following command 

curl -HHost:mydomain.com --resolvemydomain.com:31970:127.0.0.1 -k https://mydomain.com:31970/

it also displays the web page which makes me assumes that my certificates are properly installed

problem only occurs when i m using domain name in browser.

here is my gateway and virtual service for ingress gateway

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: nginx-gateway
  namespace: myapp
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 443
      name: https-web
      protocol: HTTPS
    tls:
      mode: SIMPLE    
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
    hosts:
    - "mydomain.com" 
  - port:
      number: 80
      name: http-web
      protocol: HTTP
    hosts:
    - "mydomain.com" 
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginx
  namespace: myapp  
spec:
  hosts:
  - "mydomain.com"
  gateways:
  - nginx-gateway
  http:
  - route:
    - destination:
        host: nginx
        port:
          number: 80

any help would be appreciated.
thanks

**Comment by howardjohn** [comment]
@shahid-mushtaq I do not understand the when the failure actually occurs, can you be more explicit about what succeeds and what fails, and capture access logs (https://github.com/istio/istio/wiki/Troubleshooting-Istio)? I am confused by your Gateway being on 443 but requesting on a different port

**Comment by howardjohn** [comment]
Without more info we are unable to troubleshoot this further. If you still experience this issue, please reopen with the requested information. Thanks again!
