### ISSUE TITLE
Support istio CA across multiple k8s clusters

### ISSUE THREAD

**Issue by brianwolfe** [istio/istio#21205]
**Describe the feature request**

When deploying Istio with a [shared control plane across multiple kubernetes clusters](https://istio.io/docs/setup/install/multicluster/shared-vpn/), Istio CA needs to run in all clusters. To run Istio CA, we need to provide a certificate authority signing key to each individual cluster. This differs from service discovery, where a single deployment can manage service discovery across multiple clusters.

There is already [some support for out-of-cluster OIDC public keys](https://github.com/istio/istio/blob/7bcc71e51b87098bbd3da1523dcf6e9a94dbb5a3/pilot/pkg/bootstrap/istio_ca.go#L196-L218) in istiod, but we could actually validate against multiple kubernetes clusters from a single global istiod deployment with a few small extensions.

1. Read the "issuer" field from each token we validate.
2. If that "issuer" is a known kubernetes cluster (e.g. "https://kubernetes.default.svc" or "https://my-awesome-k8s-api-server.internal.dns"), we validate against that issuer using the istiod service account (instead of assuming a single k8s api-server and issuer).

This allows us to separate the trust domain of the Istio control plane cluster (which we strongly restrict since it has access to the CA signing key) from the trust domain of the managed clusters (where we restrict the namespaces/service accounts created, but otherwise allow users to manage more privileged access).

**Describe alternatives you've considered**

We modify istiod to accept third-party public keys & issuers, building off of [this](https://github.com/istio/istio/blob/7bcc71e51b87098bbd3da1523dcf6e9a94dbb5a3/pilot/pkg/bootstrap/istio_ca.go#L243) section.

Another alternative would be to make authenticators fully pluggable so that users could add their own service account authenticators based on the context. This is nearly the case already, but there are not good examples 

**Additional context**

**Comment by incfly** [comment]
Something on the road map of multi cluster. @myidpt @ayj fyi. it will be great if we can dup this one with an existing one.

**Comment by brianwolfe** [comment]
This was fixed.
