### ISSUE TITLE
Unable to install ISTIO 1.4.4 on MacOSX Catalina

### ISSUE THREAD

**Issue by shivaspk** [istio/istio#21203]
**Bug description**
Unable to run istioctl on mac OS Catalina.
```
$ istioctl version
dyld: Symbol not found: 
  Referenced from: /Users/xxx/Downloads/k8sdd/istio-1.4.4/bin/istioctl
  Expected in: flat namespace

```
Abort trap: 6

[ ] Configuration Infrastructure
[ ] Docs
[ x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
istioctl should run and display version currently unable to install istio
**Steps to reproduce the bug**
curl -L https://istio.io/downloadIstio | sh -
**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.4.4
**How was Istio installed?**
It was using the following command:
```
curl -L https://istio.io/downloadIstio | sh -
export PATH="$PATH:/Users/xxx/Downloads/k8sdd/istio-1.4.4/bin"
istioctl version
```
**Environment where bug was observed (cloud vendor, OS, etc)**
MacOS Catalina

**Comment by ericvn** [comment]
I can't even run the executable:
![Screen Shot 2020-02-17 at 12 19 36 PM](https://user-images.githubusercontent.com/10537847/74678170-d1c0ee80-517f-11ea-9aae-296646449399.png)

**Comment by ericvn** [comment]
If I use the `curl` command as originally noted, I do see that same error.

**Comment by ericvn** [comment]
I did some additional playing with downloading the .tar in Chrome. The `bin/isitioctl` in the unitard directory still fails, and copying it to a bunch of places resulted in that failing as well. For some reason, copying it over an existing istioctl executable in usr/local/bin seems to work. I'm suspecting the the Apple signing had already approved that image/location at some point so putting a new one over inseams OK. I wouldn't be surprised if Apple would fix this at some point.

**Comment by ericvn** [comment]
Kubernetes client has a similar issue:
```tar -xvf ~/Downloads/kubernetes-client-darwin-amd64.tar.gz                                                                                                                                           
x kubernetes/client/
x kubernetes/client/bin/
x kubernetes/client/bin/kubectl
./kubernetes/client/bin/kubectl                                                                                                                                                                      
[1]    12207 killed     ./kubernetes/client/bin/kubectl```
I normally use `brew` to install it instead of downloading and extracting the tar so haven't seen the issue.

**Comment by ericvn** [comment]
@shivaspk My comment might be hidden above. Can you verify that you are actually running the new `istioctl` by running `which istioctl`. I note that you put the istio directory on the end of your path.

**Comment by ericvn** [comment]
I found https://discourse.brew.sh/t/code-signing-installed-executables/2131/15 which at the bottom talks about quarantine flags being set by the browsers and being placed on the untar'd files as well. I did find that to be true. If I remove the quarantine flags things work. I believe the curl isn't setting the quarantine flag and then things work fine.

**Comment by ericvn** [comment]
Some quick googling suggests that this error possibly has something to do with the version of xcode command line tools installed compared to your osx version. 

I try `xcode-select -v` and got  _xcode-select version 2373._ on my Mac.

**Comment by shivaspk** [comment]
@ericvn 
```
$which istioctl
/Users/xxx/Downloads/k8sdd/istio-1.4.4/bin/istioctl
```

Surprisingly have the same version of Xcode:

```
$ xcode-select -v
xcode-select version 2373.
```

**Comment by ericvn** [comment]
I've done some more looking around, and don't really see anything. We may have to file an issue with the Golang team.

Have you tried this on other Macs? Does it fail on all of them?
Have you done something with MacPorts on the Mac(s)? It seems that is listed at least one in the issues.
What about doing something with the C(++) libraries on the Mac? Also seems to cause issues since Golang is looking for specific entries and isn't finding them on that machine.
Have you tried with an earlier version, 1.4.2 or 1.4.3? I'm not sure exactly when we might have updated Golang versions but wonder if we could trace it back to a particular Istio version and then maybe look at Go versions?
Are you able to try and build istioctl from the source yourself? Might be interesting if it's just the one executable or maybe it's an overall Golang issue on the machine.

**Comment by shivaspk** [comment]
A upgrade to 1.4.5 fixed the issue. Thanks for your support.
