### ISSUE TITLE
Ingress ISTIO virtualhost based routing doesn't work

### ISSUE THREAD

**Issue by luccks** [istio/istio#21208]
**Bug description**

[x ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

ISTIO ingress virtual host based routing doesn't work

Steps to reproduce:

* Deploy simple echo service apple.yaml

kind: Pod
apiVersion: v1
metadata:
  name: apple-app
  labels:
    app: apple
spec:
  containers:
    - name: apple-app
      image: hashicorp/http-echo
      args:
        - "-text=apple"

---

kind: Service
apiVersion: v1
metadata:
  name: apple-service
spec:
  selector:
    app: apple
  ports:
    - port: 5678 # Default port for image

Create http gateway:

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: http-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
        - "*"

Create host based routing  apple_virtual_svc.yaml

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "apple-service"
spec:
  hosts:
  - "apple.example.domain.org"
  gateways:
  - http-gateway
  http:
   - route:
     - destination:
        host: "apple-service"
        port:
          number: 5678

When I tried get host apple.example.domain.org istio ingress returns 404 error code:

--2020-02-18 11:24:16--  http://apple.example.domain.org:32324/
Resolving apple.example.domain.org (apple.example.domain.org)... 10.10.136.33
Connecting to apple.example.domain.org (apple.example.domain.org|10.10.136.33|:32324... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-18 11:24:16 ERROR 404: Not Found.

When I reconfigure virtual service for use prefix based routing with following config:

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "apple-service"
spec:
  hosts:
  - "*"
  gateways:
  - http-gateway
  http:
  - match:
    - uri:
        prefix: /apple
    route:
    - destination:
        host: "apple-service"
        port:
          number: 5678
    

Everything work as expected

**Version

istioctl version --remote
client version: 1.4.2
control plane version: 1.4.2
data plane version: 1.4.2 (5 proxies)

kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:26:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

helm version   
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}

**How was Istio installed?**

    Using standard recommended way install:
    istioctl verify-install --kubeconfig ~/.kube/config.my 
    istioctl manifest apply --set profile=demo --kubeconfig ~/.kube/config.my

**Environment where bug was observed (cloud vendor, OS, etc)**
    Ubuntu 18.04

[bug_demo_config.zip](https://github.com/istio/istio/files/4218697/bug_demo_config.zip)

**Comment by howardjohn** [comment]
I tried this locally and could not reproduce. I suggest running `istioctl analyze`, checking https://istio.io/latest/docs/tasks/traffic-management/ingress/, upgrading Istio, and if none of those resolve this posting a config dump from ingress: https://github.com/istio/istio/wiki/Troubleshooting-Istio

**Comment by howardjohn** [comment]
I was unable to reproduce and there isn't enough information here to move forward. If you still see issues feel free to reopen. Thanks!
