### ISSUE TITLE
Node agent support for Secret Discovery Service

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#2120]
Add Pilot support for Secret Discovery Service and remove the need to restart envoy every hour for certificates rotation.

This is dependent on Envoy v2 APIs, since SDS is only available in v2.

**Comment by rshriram** [comment]
there is no SDS implementation in Envoy yet. :). Its just a spec.

**Comment by rshriram** [comment]
Tangentially, we might still need the agent (as an initial startup process, because agent has to fetch the availability zone of the pod from Pilot). It could fork/exec envoy after that, which would simplify things.

**Comment by costinm** [comment]
There are also security implications for SDS - if pilot exposes this
service it needs strict ACLs on who can get what secrets.

An alternative is to have SDS implemented in the node agent, on 127.0.0.1 (
and it has its own rolling/provisioning mechanisms).
We might also combine the node (security/spiffe) agent with the envoy agent
- and use the UDS capability of envoy to reduce
the risk even further..

**Comment by costinm** [comment]
A simpler alternative is to combine node agent with pilot agent, and have
the node agent handle the restart - it doesn't need
to watch the secrets, since it knows when they expire and when it got the
new version. This doesn't require SDS.

At the same time we can discuss increasing the expiration from 1h - in
particular for raw VMs, where disconnect for
> 1 h results in loss of provisioning.

**Comment by ZackButcher** [comment]
IMO this service should be implemented on the Istio CA binary, not on Pilot. If this is implemented in Pilot then we need to safely transfer certs minted by the CA to Pilot to then forward to Envoy instances. I don't think there's a need for this indirection, and overall we'd be better off sending certs directly from the CA. This would also be valuable for enabling an Istio installation providing mTLS with totally transparent proxying, i.e. no Pilot needs to be deployed.

**Comment by kyessenov** [comment]
We still need secure naming in addition to CA and certificate persistence
which CA does not provide.

**Comment by ZackButcher** [comment]
Ah, of course: I keep forgetting that secure naming lives in Pilot. I know that depends on service discovery, but I do think it'd be nice if that could live in the security binary too.

**Comment by costinm** [comment]
Secure naming and cert provisioning don't need to be in the same service.

Either node agent or Istio CA should handle certification issuance and
renewal - and could implement SDS.

Pilot is not the right place to issue certificates or store secrets.

The 'secure naming' is provisioned by pilot - but it's very different from
signing certificates and handling
private keys.

**Comment by andraxylia** [comment]
My understanding is Envoy will talk with istio-ca for SDS  @PiotrSikora can you please shed some light?

**Comment by PiotrSikora** [comment]
@andraxylia Envoy will talk to local node agent, which in turn will talk to Istio CA.

The whole point of SDS is to separate delivery of secrets from LDS & CDS, so Pilot is not the place to implement it (also, we could simply deliver certificates using LDS & CDS from Pilot).

**Comment by wattli** [comment]
SDS will be implemented in node agent, and once we have that working, we don't need pilot agent any more. The protobuf is defined here: 
https://github.com/envoyproxy/data-plane-api/blob/master/api/sds.proto

**Comment by wattli** [comment]
@saumoh , FYI

**Comment by linsun** [comment]
+ @gyliu513 who is interested in helping this from IBM team

**Comment by larryrun** [comment]
Hi, @gyliu513 what's the status of this feature for now? Has it been implemented?

**Comment by wattli** [comment]
It's ready to use https://preliminary.istio.io/docs/tasks/security/auth-sds/ for service-to-service communication.

**Comment by larryrun** [comment]
@wattli thanks for sharing the info!

**Comment by incfly** [comment]
I think we can close this issue now. Feel free to reopen.
