### ISSUE TITLE
Mac OS Catalina - binaries if downloaded via browser fail to run.

### ISSUE THREAD

**Issue by ericvn** [istio/istio#21204]
**Bug description**

On Mac OS Catalina, if one downloads one for the Mac OS release tar files in a browser, extracts it, and then tries to run one of the binaries, they may get a pop-up like:

![Screen Shot 2020-02-17 at 12 19 36 PM](https://user-images.githubusercontent.com/10537847/74687107-11e09b00-5199-11ea-9b04-27848caca416.png)

**Expected behavior**

Binaries should run after the release is downloaded and expanded.

**Steps to reproduce the bug**
- In a browser, go to `https://github.com/istio/istio/releases` and download a MacOS tar like: `https://github.com/istio/istio/releases/download/1.4.4/istio-1.4.4-osx.tar.gz`
- Locally expand this tar file:
   tar -xvf ~/Downloads/istio-1.4.4-osx.tar.gz
- Try and run the binary `./istio-1.4.4/bin/istioctl version`
- you should see the pop-up

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

N/A

**How was Istio installed?**
Browser download of archives

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by ericvn** [comment]
Some investigation on this:

If I download the tar file using `curl` and expand, for example using: `curl -sL https://istio.io/downloadIstioctl | sh -` the executable works.

This is one workaround. We do have to worry if someone hacks what we have for available builds, but that is irrespective of what we have here.

Apple (with Catalina) is now requiring the notarization of the apps and I suspect none of the apps are being notarized. I've quickly tried some older versions of the apps and hitting the same issue. If I make istioctl and run that, I am fine.

https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution

I found https://discourse.brew.sh/t/code-signing-installed-executables/2131/15 which at the bottom talks about quarantine flags being set by the browsers and being placed on the untar'd files as well. I did find that to be true. If I remove the quarantine flags things work. I believe the curl isn't setting the quarantine flag and then things work fine.

Workaround #2 could be to have people remove the flags. Not so good if someone was able to put something bad on our servers and we tell people how to get around the signing issue and they had issues. I don't link this one.

The Kubernetes client has a similar issue (I get the pop-up and select cancel and then get the killed process) if downloading the tar in a browser, expand it, and try to run the binary.
```
tar -xvf ~/Downloads/kubernetes-client-darwin-amd64.tar.gz 
x kubernetes/client/
x kubernetes/client/bin/
x kubernetes/client/bin/kubectl
./kubernetes/client/bin/kubectl                                                                                                                                                                      
[1]    12207 killed     ./kubernetes/client/bin/kubectl
```

I normally use brew to install it instead of downloading and extracting the tar so haven't seen the issue.

**Comment by esnible** [comment]
Our install instructions https://preliminary.istio.io/docs/setup/getting-started/#download don't use the browser.  `kubectl` has the same behavior.  I don't want our install to do something unexpected.

I expect the user could do `xattr -d com.apple.quarantine <name-of-tar>` or `<name-of-executable>` to deal with this problem.  Do you think the `xattr` command belongs on Istio FAQ https://istio.io/faq/ or the getting started pages?

In theory we could notarize our builds but we do a lot of point releases and the builds are all automated.

**Comment by ericvn** [comment]
@esnible I don't think we should document the `xattr` for the reasons I stated above. If they google and find it on their own, then they are responsible for verifying what they are running.

I think we will need to notarize our builds at some point in the future since Apple seems to be going in that direction.  For now, since the other somewhat related tools are not, we are probably fine.

Also, I think we are fine using the install instructions. I don't know if we should have a warning for those downloading via the web. It doesn't appear they do for `kubectl`, so I'm inclined to say no.
