### ISSUE TITLE
Unable to connect to the server: http: server gave HTTP response to HTTPS client

### ISSUE THREAD

**Issue by lchb369** [istio/istio#2121]
when exec:
kubectl apply -f istio-0.3.0/install/kubernetes/istio.yaml

display errors:
 Unable to connect to the server: http: server gave HTTP response to HTTPS client
what means?

I following this docs
http://zhaohuabing.com/2017/11/04/istio-install_and_example/#启动rancher-server

>kubectl cluster-info
Kubernetes master is running at https://192.168.2.10:8081/r/projects/1a12/kubernetes

**Comment by RiRomain** [comment]
Hi @lchb369,
I'm facing the same issue, how did you resolve it?
Thanks in advance.
