### ISSUE TITLE
Ability to gradually warm services

### ISSUE THREAD

**Issue by Stono** [istio/istio#21228]
**Describe the feature request**
We write a lot of applications that rely heavily on JIT/Hot spot code compilation.  As a result, they require a certain amount of warming before they're really good to serve load.

The typical kubernetes rollout brings in new instances, and then istio (and kubernetes in general) will almost immediately send a fair percentage of traffic to that instance.   This is an issue as it means a large amount of requests will hit a cold pod and the overall service will encounter a nice latency spike.

It would be brilliant if that percentage was ramped up over a short window, say 15 seconds, rather than firehosed, which means only a smaller amount of traffic is used to "warm" the pod minimising consumer impact during rollouts or traffic switching.

EG:
application has instances 1, 2, 3, 4 - each getting 25% load.
#5 comes online, instead of the weighting going to 20/20/20/20/20 as fast as possible, it'd be great if #5 was gradually ramped up to 20.

**Describe alternatives you've considered**
Complicated deployment strategies and using traffic mirroring.  However then i'm using "fake" traffic which would need to be excluded from key business metrics (hard).

Convincing my entire organisation to write in other languages (unlikely).

Readiness probes that send a few fake requests at the service before it becomes ready, but they're not really doing a decent job (giving enough variance), and also require maintenance.

**Additional context**
It'd be a nice added differentiator for Istio, to also improve deployments! 

Red line indicates deployment:
<img width="808" alt="Screenshot 2020-02-18 at 22 13 09" src="https://user-images.githubusercontent.com/1486729/74782700-e09cc380-529b-11ea-8582-7b080bb99395.png">

**Comment by hzxuzhonghu** [comment]
Don't u have readiness probe? It can work in this case.

**Comment by Stono** [comment]
Yes of course we do, it doesn’t help.  As I explained in the “alternatives we have considered”

**Comment by BradErz** [comment]
We have the same problem @Stono, we are looking into deploying https://github.com/weaveworks/flagger so that we can do automated gradual rollouts of the new version starting with like 1,5,10% of traffic etc to warm up the code path before giving all the traffic.

(We haven't deployed it to prod yet but we are evaluating it)

**Comment by BradErz** [comment]
Ah ok yes i misunderstood sorry.

**Comment by zhongfox** [comment]
as described in https://github.com/istio/istio/issues/28271, some user already hack istio, use simple strategy to warm up: increase weight of endpoint by ready-time.

any change we add the new feature to DR?

```
kind: DestinationRule
spec:
  host: fox
  trafficPolicy:
    timeWeight:
        max: 90 # weight upper limit
        init: 1      # init weight 
        evaluate_interval：10
    loadBalancer
```
istio will calculate periodically，and push weight change （EDS）to data plane. 

this proposal is not about traffic mirroring. this is general endpoint weight strategy, user still can use traffic mirroring with this time weight strategy.

**Comment by zhaohuabing** [comment]
I would like to take this issue if there is no other people working on it.

**Comment by Stono** [comment]
@zhaohuabing I would be extremely interested in helping you test this, if you do :)

**Comment by zhaohuabing** [comment]
@Stono great!

**Comment by howardjohn** [comment]
@zhaohuabing can you look into implementing it in Envoy? I do not think its great for pilot to be "stateful" like this would require. I realize it can be implemented without literally maintaining external state but still

**Comment by ramaraochavali** [comment]
https://github.com/envoyproxy/envoy/issues/11050 -  There is an issue in Envoy already

**Comment by zhaohuabing** [comment]
@howardjohn  It looks that the envoy guys have already made a good process: https://github.com/envoyproxy/envoy/pull/13176.

Let's wait until they finish it and then add the necessary piece to Pilot to make this feature in Istio.

**Comment by nightmareze1** [comment]
Support for progressive traffic increase for new Pods (slow start mode) is very important :)
https://aws.amazon.com/about-aws/whats-new/2018/05/application-load-balancer-announces-slow-start-support/

+1

**Comment by hzxuzhonghu** [comment]
not stale

**Comment by ryanlewis** [comment]
This would be awesome if it one day makes its way in.

**Comment by ryan4yin** [comment]
@zhaohuabing any updates here? 
some of our services used to run on AWS ECS and strongly relied on the `slow_start` function of AWS ALB,
but we cannot find any usable replacement of this function in the istio world now.

**Comment by ramaraochavali** [comment]
@ryan4yin I am working on proposing an API as we also need this feature. Will submit  api PR shortly.

**Comment by hzxuzhonghu** [comment]
Fixed by 	#37583

**Comment by ldemailly** [comment]
Sorry to necro this but... I have a question:

Does this (warmupDurationSecs in LB section of DR) work for pods coming up or only for new service being rolled?

Our (and I don't think it's unique) use case is that as HPA kicks in, or other pod disruption brings in new pods; the fresh pod just after they pass the readiness gate can't handle the full traffic % at once- so the question is how to spread the ramp up of new _pods_ (not services)

**Comment by hzxuzhonghu** [comment]
Yes, It works for pods coming up, not for service

**Comment by Xemuel** [comment]
How will `PILOT_SEND_UNHEALTHY_ENDPOINTS` affects the behaviour of warm up?
Can't find description in PR and istio docs of warm up and this feature flag so I think I just gonna ask here.

Will a unhealthy / unready endpoints start receiving traffic if it is configured warm up / slow start mode? If not, what is the point of sending unhealthy endpoints?

Thank you!

**Comment by ramaraochavali** [comment]
> Will a unhealthy / unready endpoints start receiving traffic if it is configured warm up / slow start mode? If not, what is the point of sending unhealthy endpoints?

No they wont

That flag was added to not warm services again when readiness flips from ready -> unready -> ready.

**Comment by Xemuel** [comment]
> > Will a unhealthy / unready endpoints start receiving traffic if it is configured warm up / slow start mode? If not, what is the point of sending unhealthy endpoints?
> 
> No they wont
> 
> That flag was added to not warm services again when readiness flips from ready -> unready -> ready.

I see. Thank you for quick response!

I am planning to use the warm up feature on a java service.
However, I got confused to use it with kubernetes rolling update.

For example, I have 5 instances of same application, and I configured them to warm up for 1 min.
An instance will start -> ready -> enter slow start mode and start receiving weighted traffic for ~ 1min -> exit slow start mode.

Ideally, kubernetes should regard this instance is available and start deploy the next instance when it finishes warm up. However, kubernetes will start deploy the next instance when the instance is ready, before the warm up finish.
That will finally cause all new instance of the service are in warm up mode, all old instance terminated. In this case, the warm up thing will not work properly.

Do you know how to deal with this?

**Comment by ramaraochavali** [comment]
I do not know of any better solution during rolling upgrade except setting larger value of `minReadySeconds` in the rolling upgrade strategy. I have n't tried it though. @howardjohn  any ideas?

**Comment by howardjohn** [comment]
+1 to minReadySeconds
