### ISSUE TITLE
Istio deployment on Openshift 3.7 of Prometheus/Grafana

### ISSUE THREAD

**Issue by cmoulliard** [istio/istio#2123]
Some of the apps, used by Istio to report telemetry data, such as Prometheus or Grafana dashboard can't be started on Openshift 3.7 (Kubernetes v1.7.6+a08f5eeb62)

Problems are certainly related to the fact that the UID doesn't has the rights to save the data on the disk -> https://github.com/openshift/origin/issues/4078

Prometheus

```
time="2017-12-13T08:09:11Z" level=info msg="Starting prometheus (version=1.1.1, branch=release-1.0, revision=ab312a075f810e2ed124783c46d68674af071293)" source="main.go:73" 
time="2017-12-13T08:09:11Z" level=info msg="Build context (go=go1.6.3, user=root@8ab14ddb4898, date=20160907-09:37:01)" source="main.go:74" 
time="2017-12-13T08:09:11Z" level=info msg="Loading configuration file /etc/prometheus/prometheus.yml" source="main.go:221" 
time="2017-12-13T08:09:11Z" level=error msg="Error opening memory series storage: mkdir data: permission denied" source="main.go:158" 
```

Grafana

```
chown: changing ownership of '/data/grafana': Operation not permitted
chown: changing ownership of '/var/log/grafana': Operation not permitted
```

Questions:

- As deployment of istio on openshift is a bit different from deployment on k8s, are we gonna to create separate yaml files to resolve issues like this ?
- Is there a processus in place to verify if the docker image that we deliver as addon are working on Docker, Kubernetes, Openshift, .... ?

**Comment by douglas-reid** [comment]
We do not currently have any process in place to verify working of add-on docker images across all environments. This would be a great "help wanted" area.

**Comment by douglas-reid** [comment]
@geoand would you be able to write-up documentation on what is needed to get it working on OpenShift for the website guides?  That would be really helpful, as I have no experience with OpenShift.

**Comment by geoand** [comment]
@douglas-reid I have already submitted a PR that improves the installation instruction for Openshift. See [this](https://github.com/istio/istio.github.io/pull/856).

Were you thinking something along those lines or perhaps a new entry under `/docs/guides/`?

**Comment by douglas-reid** [comment]
@geoand Oh cool, thanks! I had not seen that PR yet.

**Comment by geoand** [comment]
You are welcome!

**Comment by geoand** [comment]
You are welcome!
