### ISSUE TITLE
Protocol Detection breaking H2 traffic to gateway

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#21230]
https://github.com/istio/istio/commit/fd29fd362b7e0b6561734fd64444651baab43f2d introduced a change to use USE_DOWNSTREAM_PROTOCOL if sniffing is enabled. This seems to break gateway traffic.

Relevant configs:

443 listener:
```json
 {
     "version_info": "2020-02-18T18:34:05Z/3",
     "listener": {
      "name": "0.0.0.0_443",
      "address": {
       "socket_address": {
        "address": "0.0.0.0",
        "port_value": 443
       }
      },
      "filter_chains": [
       {
        "filter_chain_match": {
         "server_names": [
          "*.mydomain"
         ]
        },
        "tls_context": {
         "common_tls_context": {
          "alpn_protocols": [
           "h2",
           "http/1.1"
          ],
          "tls_certificate_sds_secret_configs": [
           {
            "name": "ingressgateway-wildcard-certs",
            "sds_config": {
             "api_config_source": {
              "api_type": "GRPC",
              "grpc_services": [
               {
                "google_grpc": {
                 "target_uri": "unix:/var/run/ingress_gateway/sds",
                 "stat_prefix": "sdsstat"
                }
               }
              ]
             }
            }
           }
          ]
         },
         "require_client_certificate": false
        },
        "filters": [
         {
          "name": "envoy.http_connection_manager",
          "typed_config": {
           "@type": "type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager",
           "stat_prefix": "outbound_0.0.0.0_443",
           "http_filters": [
            {
             "name": "envoy.cors"
            },
            {
             "name": "envoy.fault"
            },
            {
             "name": "envoy.router"
            }
           ],
           "http_protocol_options": {},
           "server_name": "istio-envoy",
           "idle_timeout": "300s",
           "access_log": [
            {
             "name": "envoy.file_access_log",
             "typed_config": {
              "@type": "type.googleapis.com/envoy.config.accesslog.v2.FileAccessLog",
              "path": "/dev/stdout",
              "format": "[%START_TIME%] \"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% \"%DYNAMIC_METADATA(istio.mixer:status)%\" \"%UPSTREAM_TRANSPORT_FAILURE_REASON%\" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(X-FORWARDED-FOR)%\" \"%REQ(USER-AGENT)%\" \"%REQ(X-REQUEST-ID)%\" \"%REQ(:AUTHORITY)%\" \"%UPSTREAM_HOST%\" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME%\n"
             }
            }
           ],
           "use_remote_address": true,
           "forward_client_cert_details": "SANITIZE_SET",
           "set_current_client_cert_details": {
            "subject": true,
            "cert": true,
            "dns": true,
            "uri": true
           },
           "upgrade_configs": [
            {
             "upgrade_type": "websocket"
            }
           ],
           "stream_idle_timeout": "0s",
           "normalize_path": true,
           "rds": {
            "config_source": {
             "ads": {}
            },
            "route_config_name": "https.443.https-demo-wildcard.istio-autogenerated-k8s-ingress.gke-system"
           }
          }
         }
        ]
       }
      ],
      "listener_filters": [
       {
        "name": "envoy.listener.tls_inspector"
       }
      ],
      "traffic_direction": "OUTBOUND"
     },
     "last_updated": "2020-02-18T18:34:31.197Z"
    },
```

Cluster that is being routed to:
```json
  {
     "version_info": "2020-02-18T18:34:05Z/3",
     "cluster": {
      "name": "outbound|80||service2.default.svc.cluster.local",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {}
       },
       "service_name": "outbound|80||service2.default.svc.cluster.local"
      },
      "connect_timeout": "10s",
      "circuit_breakers": {
       "thresholds": [
        {
         "max_connections": 4294967295,
         "max_pending_requests": 4294967295,
         "max_requests": 4294967295,
         "max_retries": 4294967295
        }
       ]
      },
      "http2_protocol_options": {
       "max_concurrent_streams": 1073741824
      },
      "protocol_selection": "USE_DOWNSTREAM_PROTOCOL"
     },
     "last_updated": "2020-02-18T18:34:31.195Z"
    },
```

Gateway:
```yaml
   port:
      name: https-demo-wildcard
      number: 443
      protocol: HTTPS
    tls:
      credentialName: ingressgateway-wildcard-certs
      mode: SIMPLE
 ```

Looks like we hit this code path: https://github.com/istio/istio/blob/134c006dcfc37452d9a8ae3818732f32e47a0ef1/pilot/pkg/networking/core/v1alpha3/cluster.go#L1265

This seems to assume sniffing has occurred, but this is not the case at the gateway.

This was reported on 1.4.4 (as a regression from a 1.2 upgrade). Disabling protocol sniffing solved this issue. A `curl --http1.1` also fixes this.

cc @yxue @PiotrSikora @duderino

**Comment by yxue** [comment]
It seems that the gateway routes the HTTP/2 traffic to some HTTP/1.1 service on port 80 and the service on port 80 is defined without port name. 

Since protocol sniffing is disabled on gateway, if the port is unnamed, the traffic should use TCP proxy, not the HTTP proxy. Do we have some magic on port 80?

The quick fix is adding the sidecar vs gateway check and long term fix is supporting H2 upgrade in Envoy. @incfly

**Comment by howardjohn** [comment]
I am not sure why the port name for the cluster matters here? For the gateway, isn't all of the config determines by Gateway not the Service?

**Comment by howardjohn** [comment]
protocol name really shouldn't matter for gateway because you can use istio as an ingress only mode (no sidecar). If you do that, it doesn't make any sense to require pods to configure their port name

**Comment by yxue** [comment]
Cluster is used to build the connection to the destination service. The
configuration in the cluster determines the connection to use http/1.1 or
http/2 or tcp proxy. I thought the gateway determines the configuration
based on the service port, no?

**Comment by howardjohn** [comment]
>  The configuration in the cluster determines the connection to use http/1.1 or http/2 or tcp proxy.

I thought tcp vs HTTP was determined at the listener level?

**Comment by howardjohn** [comment]
The service port should not matter for gateway other than determining h1 vs h2 as far as I know

**Comment by yxue** [comment]
>> The configuration in the cluster determines the connection to use http/1.1 or http/2 or tcp proxy.

> I thought tcp vs HTTP was determined at the listener level?

Yeah. HTTP vs TCP was determined at the listener level. The cluster configuration determines h1 vs h2. 

If the service port name for port 80 is not defined. How will the gateway generate outbound listener? The outbound listener should use TCP proxy, right?

**Comment by howardjohn** [comment]
The listener is based on VS/Gateway. For example, this config

```
cat <<EOF | kaf -
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookinfo
spec:
  hosts:
  - "*"
  gateways:
  - gateway
  http:
  - match:
    - uri:
        prefix: /httpbin
    rewrite:
      uri: /
    route:
    - destination:
        host: httpbin
        port:
          number: 80
EOF
```

should create http traffic regardless of what protocol for the service `httpbin` is. Because we have explicitly configured to use HTTP by the virtual service

**Comment by yxue** [comment]
Got it! The outgoing protocol (TCP vs HTTP) is determined at the listener level. If the HTTP filter chain is used, the router will select h1 vs h2 based on the cluster configuration; if TCP proxy is used, the TCP proxy will used TCP proxy regardless of the configuration of the cluster. Port name doesn't matter here. 

I have another question. How will the cluster be configured with h2 configuration? Is it based on the port name and protocol?

**Comment by incfly** [comment]
There're some H2 specific options in DestinationRule, not sure if that's
the only source of the truth.

**Comment by hzxuzhonghu** [comment]
By declaring the service port name with http2/grpc.

**Comment by yxue** [comment]
When I am adding check in the gateway to disable `use_downstream_protocol`, I am thinking that for http2/grpc service, if we don't declare the service port name and we use `curl --http1.1`, I think the request will still fail without `use_downstream_protocol`. I think the right fix would be supporting h2c/h2 upgrade.

**Comment by yxue** [comment]
But anyway, since protocol detection is not applied to gateway, removing `use_downstream_protocol` from gateway cluster rmakes sense.
