### ISSUE TITLE
`istioctl proxy-config secret` broken by Envoy v3 updates

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#21236]
```
$ ik pc secret `kp httpbin`
Error: failed building warming secret default: mismatched message type: got "envoy.extensions.transport_sockets.tls.v3.Secret" want "envoy.api.v2.auth.Secret"
```

This impacts 1.5+

cc @incfly @esnible

**Comment by esnible** [comment]
I suspect this is related to https://github.com/istio/istio/issues/20714 .  I will research it.

**Comment by howardjohn** [comment]
Yeah it should be the same issue or at least same root cause of changing API in envoy
