### ISSUE TITLE
istiod/citadel read root CA directly from secret

### ISSUE THREAD

**Issue by rshriram** [istio/istio#21235]
**Describe the feature request**

Today, istiod supports the ability to read the root CA from a file mount in the pod (this file mount is from the secret or what not). Some end users with much more paranoid security teams feel this is not so secure given that the pod filesystem on a EC2 VM can be accessed by any malicious entity on the VM.

It would be nice to load the secret directly from K8S using the secrets API (as well as watch for these secrets) to eliminate the file mount dependency. This is very similar to how we obtain the secrets in case of the gateways.

**Additional context**

**Comment by incfly** [comment]
I'm reading https://kubernetes.io/docs/concepts/configuration/secret/#risks for a list of security flaws on secrets, quite some of them are generic to secret itself, not necessary of using "mount".

so, it's unclear to me how will use secret API benefit us from certain risk condition? Mind sharing more details @rshriram , wondering the details.

**Comment by incfly** [comment]
> Some end users with much more paranoid security teams feel this is not so secure given that the pod filesystem on a EC2 VM can be accessed by any malicious entity on the VM.

hmm, i login-ed to a node, and did a `ls` on the pods, it seems the filesystem path storing secret can't be read by none root user? (plz correct me if im wrong)

```
sudo ls -lart /var/lib/kubelet/
total 48
-rw-r--r--  1 root root  440 Mar 17 03:25 bootstrap-kubeconfig
-rw-------  1 root root  517 Mar 17 03:26 kubeconfig
-rw-------  1 root root   62 Mar 17 03:26 cpu_manager_state
drwx------  2 root root 4096 Mar 17 03:26 plugin-containers
drwxr-x---  2 root root 4096 Mar 17 03:26 pod-resources
drwxr-x---  2 root root 4096 Mar 17 03:26 plugins_registry
drwxr-x---  2 root root 4096 Mar 17 03:26 plugins
drwxr-xr-x  9 root root 4096 Mar 17 03:26 .
drwxr-xr-x  2 root root 4096 Mar 17 03:26 pki
drwxr-xr-x  2 root root 4096 Mar 23 19:34 device-plugins
drwxr-x--- 19 root root 4096 Mar 23 19:34 pods
drwxr-xr-x 18 root root 4096 Mar 27 05:00 ..
```
