### ISSUE TITLE
Cert rotation broken on Istio 1.5

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#21239]
Steps to reproduce:

* Set `SECRET_TTL` to some low value. I chose 1m
* Wait `SECRET_TTL` seconds. Notice nothing in pilot-agent logs about SDS pushes
* All traffic is now broken, since the cert is expired but not rotated

**Comment by howardjohn** [comment]
@lei-tang @myidpt

**Comment by howardjohn** [comment]
I bump this up to 10min and rotation still did not occur, so that rules out my theory that 1min is so short that it breaks something

/certs output:
```
  {
   "ca_cert": [
    {
     "path": "\u003cinline\u003e",
     "serial_number": "d6be877145ed117f62f70bf83385d92d",
     "subject_alt_names": [],
     "days_until_expiration": "3649",
     "valid_from": "2020-02-18T23:59:54Z",
     "expiration_time": "2030-02-15T23:59:54Z"
    }
   ],
   "cert_chain": [
    {
     "path": "\u003cinline\u003e",
     "serial_number": "1432a156c600e5c645856693bd83c70b",
     "subject_alt_names": [
      {
       "uri": "spiffe://cluster.local/ns/default/sa/default"
      }
     ],
     "days_until_expiration": "0",
     "valid_from": "2020-02-19T01:01:09Z",
     "expiration_time": "2020-02-19T01:11:09Z"
    }
   ]
  },
```

I captured this at 01:14, so 3 min after expiration

**Comment by myidpt** [comment]
Please help to take a look, Lei. Thanks!

**Comment by howardjohn** [comment]
I have heard that Envoy will request a new secret when its close to expiration (as this was the whole motivation for running Envoy as prometheus sidecar) but the Envoy docs seem to suggest otherwise? "With SDS, a central SDS server will push certificates to all Envoy instances. If certificates are expired, the server just pushes new certificates to Envoy instances, Envoy will use the new ones right away without re-deployment." from https://www.envoyproxy.io/docs/envoy/latest/configuration/security/secret

**Comment by myidpt** [comment]
Oh, we have 3 different flags to configure for the cert rotation:
https://github.com/istio/istio/blob/master/pkg/istio-agent/sds-agent.go#L68
Also L69, L70. You need to configure shorter graceperiod and rotation interval (the running interval for the cert ttl check thread) in order to have istioagent detect and rotate the certs.

**Comment by myidpt** [comment]
I think having 3 flags here is a little cumbersome. We need to improve this.

**Comment by howardjohn** [comment]
Ah yeah. At the very least we should make it

```
	secretTTLEnv                       = env.RegisterDurationVar(secretTTL, 24*time.Hour, "").Get()
	secretRefreshGraceDurationEnv      = env.RegisterDurationVar(SecretRefreshGraceDuration, secretTTLEnv/2, "").Get()
```

So its automatically changed when you change the TTL.

**Comment by howardjohn** [comment]
I thought the whole reason we ran envoy for prometheus was because envoy was triggering the cert rotation so we didn't need to run the (very minimal) amount of code to do the cert rotation? I am really not sure why we run it now.. outside the scope of this PR though

**Comment by howardjohn** [comment]
Its still broken even if you configure those correctly. We do not configure eviction duration, so https://github.com/istio/istio/blob/445524dfeb7441f78e470a997d78c56e2ac6ad56/security/pkg/nodeagent/cache/secretcache.go#L544 always kicks in and then the cert is never rotated

**Comment by howardjohn** [comment]
Once that is fixed, https://github.com/istio/istio/blob/445524dfeb7441f78e470a997d78c56e2ac6ad56/security/pkg/nodeagent/cache/secretcache.go#L554 always returns true, resulting in the SDS connection dropping instead of a new cert being pushed cleanly. I am fairly sure we don't need this, we should just re-read the JWT token before we call generate secret

**Comment by lei-tang** [comment]
The PR https://github.com/istio/istio/pull/21258 is created to fix this issue. @howardjohn can you try it to see if it fixes the problem?

**Comment by fpesce** [comment]
@howardjohn seeeing you're reopenning that one, is it correct to consider https://github.com/istio/istio/pull/21300 to address this in 1.5 ?

**Comment by howardjohn** [comment]
Yes please merge it, but its not entirely fixed yet. That fixes one aspect of this. The cert rotates but the SDS connection is broken every time it rotates. I think this has a large perf impact on envoy

**Comment by myidpt** [comment]
I created another bug to track the reconnection issue: https://github.com/istio/istio/issues/21680
