### ISSUE TITLE
istioctl analyze: Detect connectivity between specified Pods

### ISSUE THREAD

**Issue by t-ide** [istio/istio#21249]
**Describe the feature request**

It would be useful if "istioctl analyze" could detect connectivity of specified Pods such as:

```sh
$ istioctl analyze connect --from <PodA> --to <PodB>
---
Connection: Available
Conditions:
  src:
    mtls: ISTIO_MUTUAL
  dst:
    mtls: STRICT
    ports: 9000
    labels:
      version: v1
  from:
  - source:
      namespaces: ["test"]
  to:
  - operation:
      methods: ["GET"]
      paths: ["/info*"]
  when:
  - key: request.headers[User-Agent]:
    values: ["Mozilla/*"]
```

**Background**

Currently, we are using Istio in a production environment.  
When a communication failure occurs in the system, it is necessary to determine whether this issue is caused by some error in an Istio manifest ASAP.  
However, the connectivity between the Pods depends on routing, authentication and authorization. We have to check various of manifests such as DestinationRule, VirtualService, Policy, PolicyMesh, AuthorizationPolicy to find out the detailed reason. The whole analysis process can be quite complicated.

**Describe alternatives you've considered**

List all Pods which are accessible from PodA

```sh
$ istioctl analyze connect --from <PodA>
```

List all Pods which are accessible to PodB

```sh
$ istioctl analyze connect --to <PodB>
```

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [x] User Experience
- [ ] Developer Infrastructure

**Comment by hzxuzhonghu** [comment]
cc @istio/wg-user-experience-maintainers

**Comment by esnible** [comment]
Does `istioctl x describe pod` help with this problem?

It is not the same as analyze, and it does not take two pods, but let me know if it is close to what you need.

**Comment by t-ide** [comment]
Thank you for your comment. I will check it.

**Comment by esnible** [comment]
@jasonwzm Are you working on this?  @rvennam asked about this functionality.  He was especially interested to know if the data was flowing as TLS or plain.

I would be happy to collaborate with you on a doc.

**Comment by liamawhite** [comment]
We are also interested in this.

**Comment by rvennam** [comment]
+1 this would be useful. Verbose options could include TLS settings, latency, headers, pod IP etc. 

Would you test proxy to proxy? Ideally, you would test user container to container, but I'm not sure that's possible. Can you use an ephemeral debug container?

**Comment by esnible** [comment]
> +1 this would be useful. Verbose options could include TLS settings, latency, headers, pod IP etc.
> 
> Would you test proxy to proxy? Ideally, you would test user container to container, but I'm not sure that's possible. Can you use an ephemeral debug container?

There are two sides, the client/sender and the server/receiver.

One implementation idea is to use an EnvoyFilter with WASM OnTick() that attempts to transmit on the client, and another EnvoyFilter that tracks receives.

Alternately, ephemeral containers could be use to transmit and receive.

If an ephemeral container is used the connectivity test tool could collect the information from the pod.  If EnvoyFilters are used another pod or Prometheus would need to be ready to receive reports from the filter WASM.

**Comment by rvennam** [comment]
I'm worried using EnvoyFilters won't be a proper test if the user is debugging issues with config. I guess that depends on where in the filter chain the test runs.
