### ISSUE TITLE
methods of configure metrics in mixer exists forever

### ISSUE THREAD

**Issue by ckcd** [istio/istio#21257]
**Describe the feature request**

I want to set all metrics generated by mixer be exists forever and never expired, but i found that for now the config of `metricsExpirationPolicy` in [here](https://github.com/douglas-reid/istio/blob/84f3b8ff576125a6c3cab667bb213c65768f68a3/install/kubernetes/helm/istio/charts/mixer/templates/config.yaml#L658):

```
params:
    metricsExpirationPolicy:
      metricsExpiryDuration: "{{ .Values.adapters.prometheus.metricsExpiryDuration }}"
```

and with this code in [here](https://github.com/istio/istio/blob/7197e6528be472987c996bac0c195e2be5a4ce08/mixer/adapter/prometheus/prometheus.go#L218):

```
if cfg.MetricsExpirationPolicy != nil {
		checkDuration := cfg.MetricsExpirationPolicy.ExpiryCheckIntervalDuration
		if checkDuration == 0 {
			checkDuration = cfg.MetricsExpirationPolicy.MetricsExpiryDuration / 2
		}
		expiryCache = cache.NewTTLWithCallback(
			cfg.MetricsExpirationPolicy.MetricsExpiryDuration,
			checkDuration,
			deleteOldMetrics)
	}
```

I found that there are no any elegant method to make the metrics be exists forever.

So can we changes the [config.yaml](https://github.com/douglas-reid/istio/blob/84f3b8ff576125a6c3cab667bb213c65768f68a3/install/kubernetes/helm/istio/charts/mixer/templates/config.yaml#L658) to something like:

```
params:
    ...
    {{ if gt .Values.adapters.prometheus.metricsExpiryDuration 0 }}
    metricsExpirationPolicy:
      metricsExpiryDuration: "{{ .Values.adapters.prometheus.metricsExpiryDuration }}"
    {{ end -}}
```
so that we can use a non-positive number to indicated that i want to make the metrics exists forever.

**Comment by douglas-reid** [comment]
Mixer was deprecated and now completely removed from the codebase. Metrics expiry has not been implemented in V2, so I'm going to close this issue.
