### ISSUE TITLE
isito initializer template do not include `includeIPRange`

### ISSUE THREAD

**Issue by gyliu513** [istio/istio#2125]
Now the istio initializer template configMap here https://github.com/istio/istio/blob/master/install/kubernetes/templates/istio-initializer.yaml.tmpl#L1-L21 do not have the parameter of `includeIPRange`, this caused the auto-injected containers cannot access external services. 

I think we should add this parameter by default, but the problem is how to define the value of this parameter for istio release as different cluster may have different values.

My current thinking is that we may need to update the document to ask customer update the file manually before they deploy the istio initializer, comments?

/cc @ayj @rshriram @linsun

**Comment by linsun** [comment]
+1 i think that is reasonable.  Now, this will be mesh wide configuration, and if users need per-service configuration, they would need to use kube-inject.

**Comment by ayj** [comment]
@cmluciano, your PR for template'd sidecar configuration should address this requirement. Do you have an ETA for https://github.com/istio/istio/pull/1895?

**Comment by cmluciano** [comment]
@ayj I just pushed up some changes on that PR. I can include this in there as well.

**Comment by ayj** [comment]
Great - thanks!

**Comment by cmluciano** [comment]
Should this parameter be excluded entirely ? The template PR would not preclude someone from adding their own arguments to support this, but I'm not sure if we want to add it to the actual template.

**Comment by ayj** [comment]
Good point. The underlying template should allow for custom parameters. We can decide later whether we map that to a flag in kube-inject for template generation, or whether we proceed with deprecating the flags and relying on some other mechanism for template generation, e.g. jsonnet.

**Comment by cmluciano** [comment]
fixed in #1895
