### ISSUE TITLE
sample routerule not work

### ISSUE THREAD

**Issue by James-Dao** [istio/istio#2126]
k8s version: 1.8.5
istio: 0.3

istioctl create -f samples/bookinfo/kube/route-rule-all-v1.yaml

err:

Error: configuration is invalid: 1 error occurred:

* name or service is mandatory for a service reference

**Comment by James-Dao** [comment]
it looks like that match miss name ?

match:
       # Limit this rule to istio ingress pods only
       source:
         labels:
           istio: ingress

**Comment by GregHanson** [comment]
route rule has been updated in more recent releases, please use istio version 0.5.1 or later
