### ISSUE TITLE
MemQuota Rate-limiting works but RedisQuota Rate-limiting doesn't work on bookinfo.

### ISSUE THREAD

**Issue by gnshkumrwork** [istio/istio#21262]
**Bug description**
MemQuota Rate-limiting works but RedisQuota Rate-limiting doesn't work on bookinfo example.

**Steps to reproduce the bug**
Setup Minikube on ubuntu 18.04.
Installed Istio using helm chart.
Setup bookinfo example as given in istio docs.

Followed all setups including setting disablepolicychecks to false given in the link:- https://istio.io/docs/tasks/policy-enforcement/rate-limiting/#rate-limits

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

Istioctl version:-1.4.4
kubectl version:-1.17.2
helm version:-2.16.0
Redis chart=10.4.4

**How was Istio installed?**
Istio installed using helm

**Environment where bug was observed (cloud vendor, OS, etc)**
Minukube on Ubuntu 18.04

Have also tried replacing redisServerUrl with my-release-redis-master, redis, clusterIP of redis. Still no effect.

istio-1.4.4/samples/bookinfo/policy/mixer-rule-productpage-redis-quota-fixed-window.yaml
apiVersion: config.istio.io/v1alpha2
kind: handler
metadata:
  name: redishandler
  namespace: istio-system
spec:
  compiledAdapter: redisquota
  params:
    redisServerUrl: my-release-redis-master.default.svc.cluster.local:6379
    connectionPoolSize: 10
    quotas:
    - name: requestcountquota.instance.istio-system
      maxAmount: 2
      validDuration: 10s
      rateLimitAlgorithm: FIXED_WINDOW
      # The first matching override is applied.
      # A requestquotacount instance is checked against override dimensions.
     
---
apiVersion: config.istio.io/v1alpha2
kind: instance
metadata:
  name: requestcountquota
  namespace: istio-system
spec:
  compiledTemplate: quota
  params:
    dimensions:
      source: source.labels["app"] | "unknown"
      sourceVersion: source.labels["version"] | "unknown"
      destination: destination.labels["app"] | "unknown"
      destinationVersion: destination.labels["version"] | "unknown"
---
apiVersion: config.istio.io/v1alpha2
kind: QuotaSpec
metadata:
  name: request-count
  namespace: istio-system
spec:
  rules:
  - quotas:
    - charge: 1
      quota: requestcountquota
---
# Note: change the default namespace to the namespace of the bookinfo app
apiVersion: config.istio.io/v1alpha2
kind: QuotaSpecBinding
metadata:
  name: request-count
  namespace: istio-system
spec:
  quotaSpecs:
  - name: request-count
    namespace: istio-system
  services:
  - name: ratings
    namespace: default
  - name: reviews
    namespace: default
  - name: details
    namespace: default
  - name: productpage
    namespace: default
  - name: istio-ingressgateway
    namespace: istio-system
---
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: quota
  namespace: istio-system
spec:
  match: (destination.labels["app"]|"unknown") == "productpage"
  actions:
  - handler: redishandler
    instances:
    - requestcountquota

Screen Shot of Redis service
![Screenshot from 2020-02-19 15-59-16](https://user-images.githubusercontent.com/61225889/74825992-d678d480-5330-11ea-9c55-644c87fd709c.png)

Also One more thing, first time i apply the yaml file i get an output like this. After that it becomes ratelimiting does'nt work again.
![Screenshot from 2020-02-19 16-15-21](https://user-images.githubusercontent.com/61225889/74827365-51db8580-5333-11ea-9e29-970abd645775.png)
![Screenshot from 2020-02-19 16-15-42](https://user-images.githubusercontent.com/61225889/74827376-556f0c80-5333-11ea-8d2b-78bc11b47388.png)

**Comment by gnshkumrwork** [comment]
Hey guys 
Thanks for your contribution resolved this issue
Had to disable password for redis during setup
Worked fine then .

**Comment by howardjohn** [comment]
Closing as this has been resolved by password ^
