### ISSUE TITLE
ERROR: logging before flag.Parse

### ISSUE THREAD

**Issue by ijsnellf** [istio/istio#2127]
This message shows up in the Pilot logs:
`ERROR: logging before flag.Parse: <log msg>`

I wonder if this was accidentally introduced during some of the recent refactoring of the cmds. @nmittler?

**Comment by ijsnellf** [comment]
Sounds like a problem with glog?: https://github.com/kubernetes/kubernetes/issues/17162

**Comment by ldemailly** [comment]
i see a lot of those in pilot and pilot agent logs (only)

**Comment by nmittler** [comment]
I'll be migrating pilot over to istio logging soon (https://github.com/istio/istio/issues/2174).  I suspect this will be resolved then.

**Comment by jmuk** [comment]
FYI: mixer has a hack of suppressing this warning (see https://github.com/istio/istio/blob/master/mixer/cmd/mixs/cmd/root.go#L47), similar to a comment in the kubernetes issue.

Even if the entire pilot code base stops using glog, some dependencies (like kubernetes client library) might use it, which could cause the same problem.
