### ISSUE TITLE
remote profile is broken on 1.5.0-beta.2

### ISSUE THREAD

**Issue by btoonk** [istio/istio#21281]
**Bug description**
When installing the istio 1.5.0-beta.2 release with the remote profile the only thing thats installed is the istio-ingressgateway. No istiod or citadel/sidecar-injector is deployed.

In the file install/kubernetes/operator/profiles/remote.yaml all the components (except ingressGateways) are disabled (also with istioctl profile dump remote or istioctl manifest generate --set profile=remote ).

[x ] Configuration Infrastructure
[ ] Docs
[ x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
An istiod or citadel/sidecar-injector deployment and services.

**Steps to reproduce the bug**
istioctl manifest apply --set profile=remote

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

1.5.0-beta.2

**How was Istio installed?**
istioctl manifest apply --set profile=remote

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by linsun** [comment]
I don't think you need citadel or sidecar-injector in remote cluster.  BTW, there is an endpoint issue i fixed in https://github.com/istio/istio/pull/21372

**Comment by linsun** [comment]
If certProvider=citadel, do you need citadel in the remote cluster?   I am thinking no as long as the remote cluster is using the same CA as local cluster. @costinm @howardjohn @ayj please share your thoughts.

**Comment by ayj** [comment]
We need the sidecar-injector in remote clusters in 1.5. This could be run remotely but would require additional config changes and testing.

cc @lei-tang @myidpt for citadel requirements with remote clusters. IIUC, we still need to run citadel (istiod) in each cluster because citadel doesn't yet perform OIDC discovery with remote kube-apiserver authenticating remote workloads.

**Comment by linsun** [comment]
https://github.com/istio/istio/pull/21534

**Comment by ayj** [comment]
This should be fixed by https://github.com/istio/istio/pull/21534.
