### ISSUE TITLE
go-client API server transaction rate should be increased

### ISSUE THREAD

**Issue by ostromart** [istio/istio#21286]
The initial deployment is still quite slow, about 30s. There's no reason that object adds/updates can't be sent faster to the API server; how long the API server takes is not in our control but at least our operator controller will appear more responsive. 
A naive increase in kube config for QPS 5->50 and Burst 10->100 doesn't improve performance so either some different setting is required or API server updates can be split per component into go routines.

**Comment by ostromart** [comment]
https://github.com/istio/istio/pull/21288/files didn't work.

**Comment by howardjohn** [comment]
this was done
