### ISSUE TITLE
How can I monitor the service's frequency or called total numbers of  the Circuit Breaking and Rate limit that service access entry is ingressgateway?

### ISSUE THREAD

**Issue by zhangxingdeppon** [istio/istio#21291]
**Describe the feature request**
Hi, buddies, I  want to monitor the service's frequency of  the Circuit Breaking and Rate Limits about service. how can I get it?  which metric I can search the service's frequency or called total numbers of  the Circuit Breaking and Rate limit?   I have checked the the stats of istio-ingressgateway, but no relevant information about it, 
through the official document, the envoy in pod client have the relevant stats, details below:
<pre><code>
[root@ecs-5274-0318460 ~]#  kubectl exec  fortio-deploy-6454d8c4ff-g6rb9 -n test-istio -c istio-proxy -- pilot-agent request GET stats | grep httpbin |grep pending
cluster.outbound|8000||httpbin.test-istio.svc.cluster.local.circuit_breakers.default.rq_pending_open: 0
cluster.outbound|8000||httpbin.test-istio.svc.cluster.local.circuit_breakers.high.rq_pending_open: 0
cluster.outbound|8000||httpbin.test-istio.svc.cluster.local.upstream_rq_pending_active: 0
cluster.outbound|8000||httpbin.test-istio.svc.cluster.local.upstream_rq_pending_failure_eject: 0
cluster.outbound|8000||httpbin.test-istio.svc.cluster.local.upstream_rq_pending_overflow: 144
cluster.outbound|8000||httpbin.test-istio.svc.cluster.local.upstream_rq_pending_total: 256
You have new mail in /var/spool/mail/root
[root@ecs-5274-0318460 ~]#  kubectl exec  fortio-deploy-6454d8c4ff-g6rb9 -n test-istio -c istio-proxy -- pilot-agent request GET stats | grep httpbin |grep 429
cluster.outbound|8000||httpbin.test-istio.svc.cluster.local.external.upstream_rq_429: 320
cluster.outbound|8000||httpbin.test-istio.svc.cluster.local.upstream_rq_429: 320

</code></pre>

but the istio-ingressgateway don't have this infomation, see below, 

<pre><code>
[root@ecs-5274-0318460 ~]#  kubectl exec  istio-ingressgateway-f8787fcc4-p6ch4  -n istio-system  -c istio-proxy -- pilot-agent request GET stats |grep pending
cluster.xds-grpc.circuit_breakers.default.rq_pending_open: 0
cluster.xds-grpc.circuit_breakers.high.rq_pending_open: 0
cluster.xds-grpc.upstream_rq_pending_active: 0
cluster.xds-grpc.upstream_rq_pending_failure_eject: 523
cluster.xds-grpc.upstream_rq_pending_overflow: 0
cluster.xds-grpc.upstream_rq_pending_total: 524

</code></pre>

could you give me some ideas? it’s very important for me, thank you.

**Describe alternatives you've considered**

**Additional context**

**Comment by zhangxingdeppon** [comment]
@bianpengyuan  could you give me some ideas?  I think you maybe good at it,  thank you very much.

**Comment by zhangxingdeppon** [comment]
I knew the flag `UO` that means the request was `circuit breaking` and the flag `RL`  that means the request was ratelimited locally in the envy official document  , but in the istio prometheus, I can't find request with the flag `RL`, when I set ratelimited to service, the request just has the flag `UAEX: The request was denied by the external authorization service` or `-` , is there something I missed?

![image](https://user-images.githubusercontent.com/16789841/75057743-a427cc80-5514-11ea-8376-d218a8ad6bbd.png)

**Comment by bianpengyuan** [comment]
Istio proxy only expose a subset of envoy stats for performance reason https://istio.io/docs/ops/configuration/telemetry/envoy-stats/. You can annotation your workload to instrument envoy to expose more stats. Please take a look at https://istio.io/docs/reference/config/annotations/. There are three available annotations: `sidecar.istio.io/statsInclusionPrefixes`, `sidecar.istio.io/statsInclusionRegexps` and `sidecar.istio.io/statsInclusionSuffixes`

**Comment by zhangxingdeppon** [comment]
@bianpengyuan I have set the `sidecar.istio.io/statsInclusionPrefixes: cluster.outbound,cluster_manager,listener_manager,http_mixer_filter,tcp_mixer_filter,server,cluster.xds-grpc`, it also didn't work, maybe I set it fault, could  you give me a example?  thank you.

I  saw the default envoy configuration already have the parameters,
<pre><code>
[root@ecs-5274-0318501 httpbin]# kubectl exec httpbin-867cbdf97b-hjnpz -i -t -c istio-proxy -n istio-test -- curl localhost:15000/config_dump > /tmp/httpbin-config.tct
[root@ecs-5274-0318501 httpbin]# vim /tmp/httpbin-config.tct

    "stats_config": {
     "stats_tags": [
      {
       "tag_name": "cluster_name",
       "regex": "^cluster\\.((.+?(\\..+?\\.svc\\.cluster\\.local)?)\\.)"
      },
      {
       "tag_name": "tcp_prefix",
       "regex": "^tcp\\.((.*?)\\.)\\w+?$"
      },
      {
       "tag_name": "response_code",
       "regex": "_rq(_(\\d{3}))$"
      },
      {
       "tag_name": "response_code_class",
       "regex": "_rq(_(\\dxx))$"
      },
      {
       "tag_name": "http_conn_manager_listener_prefix",
       "regex": "^listener(?=\\.).*?\\.http\\.(((?:[_.[:digit:]]*|[_\\[\\]aAbBcCdDeEfF[:digit:]]*))\\.)"
      },
      {
       "tag_name": "http_conn_manager_listener_prefix",
       "regex": "^listener(?=\\.).*?\\.http\\.(((?:[_.[:digit:]]*|[_\\[\\]aAbBcCdDeEfF[:digit:]]*))\\.)"
      },
      {
       "tag_name": "http_conn_manager_prefix",
       "regex": "^http\\.(((?:[_.[:digit:]]*|[_\\[\\]aAbBcCdDeEfF[:digit:]]*))\\.)"
      },
      {
       "tag_name": "listener_address",
       "regex": "^listener\\.(((?:[_.[:digit:]]*|[_\\[\\]aAbBcCdDeEfF[:digit:]]*))\\.)"
      },
      {
       "tag_name": "mongo_prefix",
       "regex": "^mongo\\.(.+?)\\.(collection|cmd|cx_|op_|delays_|decoding_)(.*?)$"
      }
     ],
    "use_all_default_tags": false,
     "stats_matcher": {
      "inclusion_list": {
       "patterns": [
        {
         "prefix": "cluster_manager"
        },
        {
         "prefix": "listener_manager"
        },
        {
         "prefix": "http_mixer_filter"
        },
        {
         "prefix": "tcp_mixer_filter"
        },
        {
         "prefix": "server"
        },
        {
         "prefix": "cluster.xds-grpc"
        }
       ]
      }
</code></pre>

**Comment by howardjohn** [comment]
Need this step https://github.com/istio/istio/wiki/Envoy-native-telemetry#ingress-gateway

@bianpengyuan maybe should add that to the doc?

**Comment by howardjohn** [comment]
Or we can implement the code to do this in istio-agent, we have access to the annotations now

**Comment by bianpengyuan** [comment]
@howardjohn thanks! I completely forgot we have such a way to specify env var.

Make sense to me to implement it by reading annotation with istio-agent. I will implement that.

**Comment by howardjohn** [comment]
Ok sounds good. It's in some readPodAnnotations function or similar
currently, I don't think we call it in the metadata code path currently but
we could

**Comment by bianpengyuan** [comment]
Now think about it, it is actually better to just add stats inclusion configuration to proxy config. Close this in favor of https://github.com/istio/istio/issues/26546.
