### ISSUE TITLE
Pod creation failure when using global SDS together with sidecar userVolume annotation

### ISSUE THREAD

**Issue by emike922** [istio/istio#21308]
**Bug description**
The injection-template.yaml does not add user volumes from the sidecar.istio.io/userVolume annotation to sidecar containers if global.sds.enabled is set to false. User volumeMounts defined by the sidecar.istio.io/userVolumeMount annotation, on the other hand, are being added to the containers regardless of global.sds.enabled.
This can result in Pod creation failures when user volumeMounts refer to user volumes which were not added to the container.

**Expected behavior**
The annotations sidecar.istio.io/userVolume and sidecar.istio.io/userVolumeMount should be treated in the same fashion. If one is honored, the other should too, and vice versa.
If the behavior is to be based/conditional on global.sds.enabled, this should be described in documentation.

**Steps to reproduce the bug**
Deploy Istio with global.sds.enabled = true
Create Deployment with both sidecar.istio.io/userVolume and sidecar.istio.io/userVolumeMount annotations

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
Istio 1.4.4, Kubernetes 1.16.2, Helm 2.15.1

**How was Istio installed?**
Regular helm install but setting global.sds.enabled flag

**Environment where bug was observed (cloud vendor, OS, etc)**
Minikube

**Comment by howardjohn** [comment]
I think this is fixed now in 1.5+ and we have a test case covering this: https://github.com/istio/istio/blob/9dd64b43f7fd7750eca86c940bd13c8255fb29ab/tests/integration/pilot/tls_test.go#L87

Thanks for reporting!
