### ISSUE TITLE
SDS: control plane still relies upon istio-certs secrets

### ISSUE THREAD

**Issue by cmanzi** [istio/istio#21312]
**Bug description**
Perhaps this is a misunderstanding on my part, but I was under the impression that when operating with SDS enabled, no components should require the TLS cert secrets generated by Citadel (as they simply request them from Citadel).

However, the default deployment of Istio 1.4.5 (Helm) still includes these optional volumes, and Citadel is still configured to issue secrets (no --server-only flag). i did an experiment and removed these volume mounts, deleted the TLS secrets, and added the --server-only flag. The control plane nodes that still have these volumes (which I removed) now cannot function, as they seem to rely on these certificate mounts.

My question is, what is the design reason for this, and is there no way for the control plane to operate without secret-mounted certs? It seems to render the (theoretical) security benefits of SDS ineffective - since Citadel is still going to issue the secrets regardless (and seemingly the control plane requires them). 

**Expected behavior**
When operating in SDS mode, no Istio components require secret-mounted certificates. 

**Steps to reproduce the bug**
Install Istio 1.4.5 using Helm, with SDS enabled. Try setting Citadel to --server-only and deleting any Istio certs generated.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istio: 1.4.5\
kube: 1.15.7

**How was Istio installed?**
Helm template

**Environment where bug was observed (cloud vendor, OS, etc)**
aws - kops

**Comment by incfly** [comment]
Things change a lot in 1.5 I lost the clear track of this. Helm and istiod. @myidpt to take a look, potentially already solved.

**Comment by howardjohn** [comment]
As of istio 1.6 all components are using SDS
