### ISSUE TITLE
Low cert TTL has large impact on proxy CPU usage

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#21316]
![2020-20-02_09-38-51](https://user-images.githubusercontent.com/623453/74962485-d88c7300-53c4-11ea-88f2-abc4da95e3aa.png)

Cluster wide CPUs on proxy went from 28 -> 36 after I dropped TTL down to 1 min for certs. Obviously this is excessively low, but the extra CPU usage seems larger than expected.

@myidpt not closing the SDS connection may help here?

**Comment by howardjohn** [comment]
I will investigate if https://github.com/istio/istio/pull/21330 impacts this. and I will drop down to 10m TTL which is less excessively low

**Comment by myidpt** [comment]
Thanks for the investigation, John. Yes I think 1 min TTL is extremely low that dropping the SDS connection will very likely to bring quite noticeable overhead.

**Comment by howardjohn** [comment]
Fix the connection dropping didn't help much, maybe reduced it from 36 -> 35 cpu (its hard to tell without a long 12hr average since it fluctuates). pilot-agent itself uses a bit of CPU, but probably envoy is using more as well. I am not concerned its increased, but its a bit higher than I expected. If its still high with a more reasonable TTL (I feel like 10min? is that reasonable? obviously not for production, but for stress testing), then I would say this is likely a non-issue

**Comment by myidpt** [comment]
Yes, could you test with 10 min and 1 hr TTL and see what happens? I would be surprised if it's not close to 28.

**Comment by howardjohn** [comment]
With 10m it seems close to 28 min. I'll use that for my testing.

This is running with my change to not close the connection though, but based on 1m that may not impact much anyways. So I think we can close this
