### ISSUE TITLE
controlz/versionz is broken

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#21342]
http://localhost:9876/versionz/ gives error `template: base:28:18: executing "content" at <.User>: can't evaluate field User in type *version.BuildInfo`. This is because we trimmed down the version info

**Comment by esnible** [comment]
http://localhost:61206/procz/ also fails.

```
template: base:38:18: executing "content" at <.Gid>: can't evaluate field Gid in type *topics.procInfo
```

**Comment by esnible** [comment]
Closing in favor of duplicate https://github.com/istio/istio/issues/21959 which has an active PR.
