### ISSUE TITLE
Proxy readiness probe through envoy to ensure worker threads are ready

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#21345]
Currently readiness probe goes to pilot-agent -> admin API. This only exercises the main thread of Envoy. We should instead be hitting the worker threads in some way.

One possibly idea is for this to go from envoy -> pilot-agent -> admin API or pilot-agent -> envoy -> admin API (with some bootstrap config modifications), but others may work as well

cc @Stono

**Comment by mandarjog** [comment]
We have the Prometheus stats scraper that goes thru a worker thread already, something similar works.

**Comment by howardjohn** [comment]
done by #21488
