### ISSUE TITLE
1.5-beta.2. tools/gen_istio_image_list.sh broken

### ISSUE THREAD

**Issue by kramvan1** [istio/istio#21356]
**Bug description**

For 1.5, looks like the format of the `istio-docker.mk` has changed and has broken the tools/gen_istio_image_list.sh tool.

Also the tool does NOT support the beta tags `1.5.0-beta.2` the regex's are wrong, should be something like: `TAG_REGEX="[0-9].[0-9].[0-9][-]?[beta.]?[0-9]?"`

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by kramvan1** [comment]
cc @linsun

**Comment by linsun** [comment]
@johnma14 can you take a look at this?  Thanks.
