### ISSUE TITLE
Configure standard prometheus annotations for Istio scraping

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#21366]
Here is the idea:
We put standard annotations on control plane/ingress like `prometheus.io/port`. This gives us scraping out of the box without requiring users to use our custom scraping configs
For sidecars, the problem is the user application may also have metrics. We don't want to just mangle their annotations. Instead, we can have an aggregation layer in pilot-agent. The idea is we configure prometheus to scrape :15020/stats through annotations. If the use had these labels already set, we add these as env vars on the pod. When :15020/stats is called, we will take :15000/stats, the user defined application metrics, and pilot-agent metrics (not currently exposed), and merge them into one response to prometheus.

Benefits:
* We no longer need to maintain a custom prometheus scraping config. Users can just install Istio, and their existing prometheus config will start scraping out of the box
* Reduce the load on prometheus. Currently prometheus is calling the same pod 2x, one for envoy metrics and one for application metrics
* Expose pilot-agent metrics. Currently we do not do this
* Resolve the strict mTLS issue. Out of the box we will use plaintext for prometheus scraping even if strict mTLS is used. This won't work for all users needs, so for those cases we can also lock this down (then the user would be required to set up the certs for prometheus)

Risks:
* This may change the shape of metrics that are reported to Prometheus
* Unclear if there is a safe way to merge prometheus metrics
* Need to ensure we don't up a security hole by trampolining off pilot-agent to application, bypassing rbac, etc.
* This idea is mentioned in a design doc here: https://docs.google.com/document/d/1S6O1czHtjR2DGfK2zeZDLr88wxyLRXB2JpH5g7YM1J8/. It is regarded a a bad idea.
* The `prometheus.io` labels are just a standard practice, they are not a part of prometheus - what happens if user uses different configs? Will we break them? will we lose metrics?

**Comment by haf** [comment]
Isn't the "latest and greatest" from Prom land, to use `ServiceMonitors` instead of scrape annotations? As such, is it smart to assume that a user-supplied annotation is safe to feed into the monitoring pipeline (or; would this feature ever be anything but opt-in?) Furthermore, since the Prom annotation you mention is discouraged, how do you know that the app doesn't supply GDPR/sensitive data for some "legacy" prometheus it's got configured?

Perhaps it's not a good idea to assume too much about what the client app does.

**Comment by howardjohn** [comment]
@haf there are many folks using ServiceMonitors, and for those we can/do provide those to hook into there integration. There are also a large number of users who do not use the prom operator, and we need a solution for everyone. The scraping annotation certainly isn't legacy. I think most users than install some out-of-the-box prometheus, from Helm or from some prepackaged setup like GCP marketplace will have config to scrape based on `prometheus.io/scrape` labels. For the few that don't, I think they are likely advanced users who are ok with customizing things a bit. I will need to validate my assumptions here before going any further though, of course.

Also, my understanding is the prometheus operator is a 3p application and not supported at all by the prometheus team, so I am not sure the promethues annotation is discouraged?

**Comment by haf** [comment]
You may be right, and I hope you are, because I liked the annotations. I've been asking around though and this was the conclusion I had. I'd really like to hear what their plans are, going forward.

**Comment by howardjohn** [comment]
My understanding (and I only started looking into this recently, so I may be completely off here) is that the annotations are just a convention. Even if they decided they were a horrible idea, you could still use them, just they wouldn't be configured out of the box

**Comment by haf** [comment]
>that the annotations are just a convention.

My main complaint here is that their definitions is almost a regular-expression programming language; the pro with CRDs for it, is that it's very clear what gets monitored and how and by what selectors (and also, what labels the measurements/metrics have)

**Comment by kramvan1** [comment]
@howardjohn   This would be great for IKS I believe.   Today with 1.4 we want to have managed Istio support SysDig out of the box.   To enable that, we add the prometheus.io/port 42422 and scrape annotations to the telemetry pod with overlays in the operator ICP.

I'm still trying to figure out how this should work with 1.5 with telemetry v2 and the telemetry pod is disabled by default.     Do I need to add annotations to all the pods I'm interested in?    Or can I just re-enable the telemetry pod and do single scrape from there?

**Comment by howardjohn** [comment]
@kramvan1 the idea is that the injector will automatically add this label to all sidecrs

**Comment by linsun** [comment]
@howardjohn so this WI is to eliminate the need for users to manually annotate their deployments with prometheus.io annotation as described here - https://istio.io/faq/metrics-and-logs/#prometheus-application-metrics.  Am I correct?

@kramvan1 for your case, I don't think you would need the annotation with telemetry v2 as the mixer-telemetry is gone.  It would be up to each user to add the prometheus.io annotation to their microservices that they want to have istio generate telemetry for them.  What John is proposing here is to simply automate that process for our users via side car injection.

**Comment by howardjohn** [comment]
@linsun there will be a design doc soon(ish) with more details, this is pretty early. 

But that is not exactly right. There are two metrics we scrape for - application metrics from the user, if they configure the annotation as linked, and Envoy metrics. Currently we always scrape Envoy metrics, but only scrape application metrics if those annotations are present (since they may not have metrics, may have different ports, etc).

The WI here is to make it so that we have a single annotation that will scrape both the application metrics as well as the envoy metrics.

In doing so, users can use default promtheus configuration (which handles the prometheus.io annotations), rather than relying on our bespoke prometheus scraping configurations, so if they install Istio into a cluster with prometheus* it will just work.

*technically scraping prometheus.io annotations is not a core part of prometheus, but its an incredibly common practices such that all prometheus installs I have seen are configured this way by default

**Comment by linsun** [comment]
@howardjohn thanks for the clarification!  So with the new model, user can opt out of the envoy metrics via that single annotation, while it is always on for the user today as long as telemetry is enabled?

**Comment by howardjohn** [comment]
I suppose we could make it so the user can opt out of envoy metrics, but that is not the intent of this. The main goal is so we can integrate with out-of-the-box prometheus installations without requiring custom config just to scrape istio metrics

**Comment by linsun** [comment]
possibly if user has request for it... which i haven't seen any.  Agreed with your intent, good idea!

**Comment by howardjohn** [comment]
I set up a quick prototype of everything except the hard part (aggregating the users metrics): https://github.com/howardjohn/istio/tree/prometheus/standard-annotations

Everything seems to work pretty well aside from the dashboards that have queries with `job=...` where we have changed

**Comment by howardjohn** [comment]
I have an E2E working demo of this, including rewriting the users annotations and merging them in the agent. Seems to work fine (in the happy path, at least)

**Comment by howardjohn** [comment]
related https://github.com/istio/istio/issues/20011

**Comment by Shashankft9** [comment]
@howardjohn do we have an example servicemonitor to keep on scraping from the 15020 port of all the istio-proxy containers? like the one we have for 15020 port here: https://github.com/istio/istio/blob/release-1.7/manifests/charts/istio-telemetry/prometheusOperator/templates/servicemonitors.yaml#L42-L72

I removed this segment since in the istio-proxy container, this port is associated with the 15090 port.  
```
- sourceLabels: [__meta_kubernetes_pod_container_port_name]
      action: keep
      regex: '.*-envoy-prom'
```

**Comment by dntosas** [comment]
@Shashankft9 did you found any workaround for this ?

**Comment by dntosas** [comment]
a little bit related --> https://github.com/istio/istio/issues/27328

**Comment by Shashankft9** [comment]
@dntosas I was able to find a workaround but it involves a bit of hardcoding which I have mentioned in the above issue that you mentioned.

**Comment by dntosas** [comment]
@Shashankft9 check this --> https://github.com/prometheus-operator/prometheus-operator/issues/3354#issuecomment-693214165

I am trying to do something similar to that, no results yet ^^
