### ISSUE TITLE
TelemetryV2: Stackdriver Edges Sampling

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#21362]
For Stackdriver edges API, which tracks number of peers connecting to a given pod, we can have 10k peers in the worst case. Consider not adding an edge if an edge already exists to a given workload. 
1. We will add 5 (?) edges per workload 
2. If we get another peer from the same workload, we will not add that edge.
3. Control this sampling by percentage, or any other means.

**Comment by douglas-reid** [comment]
Can you clarify your intention here?

We already don't add traffic assertions when we've seen a peer previously:

https://github.com/istio/proxy/blob/master/extensions/stackdriver/edges/edge_reporter.cc#L106-L110

**Comment by mandarjog** [comment]
If we have 1000 peers connecting to a pod that belong with the same deployment, we are not adding additional value by adding more assertions. If we sample that at 10% that would still provide meaningful data.

**Comment by douglas-reid** [comment]
I'm not sure about "not adding addition value". The existing contract is to capture *all* workload instance to workload instance edges. topK + sampling could result in unstable results and noisy renderings over time.

**Comment by mandarjog** [comment]
If we are to show instance to instance connections then I agree with the contract. However if we never specified or commited to that assertion with be comprehensive then we can sample. If the recall is on rolled up workload dimensions, it will still work. 

Your other PR works too, that changes the batch size, however we should consider sampling .
