### ISSUE TITLE
Telemetry v2 envoy needs metric expiry

### ISSUE THREAD

**Issue by Stono** [istio/istio#21377]
**Bug description**
Mixer in telemetry v1 had the concept of metric expiry, from memory it was 10 mins (any series not seen in 10 minutes were dropped).

That automatically cleaned up things that no longer exit.  We have a cluster continually running tests with workloads that reflect those tests.

In v2, these never get cleaned up and envoys keep reference to them until those envoys are restarted:

<img width="1612" alt="Screenshot 2020-02-22 at 08 49 04" src="https://user-images.githubusercontent.com/1486729/75089418-7eb8b400-5550-11ea-9282-83bda1d20c8b.png">

cc. @douglas-reid @mandarjog 

**Expected behavior**
Metrics should expire like they used to do in v1.

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.4.5

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by Stono** [comment]
Makes me sad that this is a 1.6 milestone doug :-( means i'm going to have to implement cronjobs to restart things in dev environments!

**Comment by Stono** [comment]
@howardjohn this one is a bit of a stinker, would be nice to see it being prioritised in a `1.5.x` release?

**Comment by douglas-reid** [comment]
@Stono My concern with targeting 1.5.x is that it isn't clear exactly (to me, at least) how easy it is to accomplish this task, despite it seeming simple enough. It is possible that we finish it early in the 1.6 cycle and cherry-pick it back, however.

**Comment by mandarjog** [comment]
Yes, we will fix in master first, but I think we should be able to backport without causing too many issues.

**Comment by bianpengyuan** [comment]
not stale, target release for this is 1.7.

**Comment by Stono** [comment]
This would solve https://github.com/istio/istio/issues/24058

**Comment by Stono** [comment]
This isn't stale @howardjohn @douglas-reid @mandarjog

**Comment by nrjpoddar** [comment]
@Stono it is not stale and clearly I'm losing the fight with the lifecycle manager bot.

**Comment by mandarjog** [comment]
@Stono do you track tests by generation number ?
If not this issue is similar to the cardinality due to cronjobs.

We will have generic expiry, but this seems like a more specific solution would do using configurable metrics?
@kyessenov do we support string functions thru cel yet?

**Comment by Stono** [comment]
@mandarjog no this is different.  The CronJob issue I believe @douglas-reid got to the bottom of.  In my OP unfortunately these tests (which ironically are testing istio) deploy into their own namespace with an app representing the build number, so you get:

```
namespace-build:
  app-build-number:
```

So there's no bug here, purely an extreme example of high churn workload names

**Comment by kyessenov** [comment]
CEL has limited string functions. I'm not sure if it would help here, unless it's possible to conflate many apps as one app.

**Comment by Stono** [comment]
No we wouldn't want to do that - they are separate apps

**Comment by rakesh-garimella** [comment]
Hi @douglas-reid @mandarjog @howardjohn  just curious what if this is still a priority since this would be an issue for the use cases where people want to use it on production and over a period of time the prometheus scraping metrics from envoy pods wont scale anymore.

**Comment by skhalash** [comment]
Hi @douglas-reid @mandarjog @howardjohn @kyessenov! Are there any plans in the nearest future to implement the metric expiry feature? In case it has not been planned yet, what would be the place to start looking at if I want to contribute?

**Comment by douglas-reid** [comment]
@bianpengyuan can we provide some details around approaches here?  I'm gonna bump this to 1.11 for now.

**Comment by bianpengyuan** [comment]
There are some work arounds documented at https://istio.io/latest/faq/metrics-and-logs/#metric-expiry. We'd probably move this to backlog until someone could take the work at Envoy side.

**Comment by ryantking** [comment]
Moving to 1.12 due to recent inactivity

**Comment by chaudyg** [comment]
Hum. This would be very useful feature indeed.

What kind of work is needed here? Does this involve some work on Envoy? Or only on the stats filter?

**Comment by bianpengyuan** [comment]
> What kind of work is needed here? Does this involve some work on Envoy? Or only on the stats filter?

Yes this needs support at Envoy stats system.

**Comment by mathetake** [comment]
Here's Envoy side issue for tracking this; https://github.com/envoyproxy/envoy/issues/14070

**Comment by mathetake** [comment]
I don't think we could make it in 1.12 as this requires a relatively large change in Envoy first.

**Comment by juwatanabe** [comment]
Any updates? Definitely having the same issue and would be great to have the expiry on v2.

**Comment by kyessenov** [comment]
I rewrote the stats filter without wasm, so it should be possible to manage stat scopes manually by simple rotation with some gradual transition delay.

**Comment by hzxuzhonghu** [comment]
cc @zirain

**Comment by vvxxvvxx** [comment]
We got the issue that the scraped metrics keep growing and caused the scrape target down.  [slack thread](https://istio.slack.com/archives/C37A4KAAD/p1672909326405409)

`
Hello Istio team, we scrape the istio metrics through port 15090 /stats/prometheus but encountered several time promscrape.maxScrapeSize exceeded issue on istio-ingressgateway endpoint, so we have to increase this maxScrapeSize to mitigate the issue.
But the question is,  even if our pods with istio proxy injected were terminated, the metrics/time series from these old pods/endpoints were still kept in the scraped metrics and contribute to the scrape size, right?
If so, if our istio-ingressgateway pods are not restarted, then the number of time series exposed from the istio-ingressgateway will grow over time, is there any mechanism in istio to control the scrape size keeping growing like this?
`

Hi @howardjohn , do you know when this "metric expiry" feature can be implemented?

**Comment by RichardWLaub** [comment]
I believe this issue is causing our ingress-gateways to be OOMKilled. We are showing a linear increase in both memory usage and transmit bandwidth on our ingress gateways over a roughly 2-month period resulting in an OOMKill. This is a similar pattern shown in https://github.com/istio/istio/issues/24058. `curl`ing the /stats/prometheus endpoint on one of our ingress gateways showed metrics for literally every workload that has run in the cluster since the gateway has existed. Here is the pattern we are seeing: 

<img width="1726" alt="Screenshot 2023-01-09 at 1 53 15 PM" src="https://user-images.githubusercontent.com/19522571/211430438-0215a96b-3944-4259-a748-d65d1078ff9d.png">

<img width="1723" alt="Screenshot 2023-01-05 at 2 36 08 PM" src="https://user-images.githubusercontent.com/19522571/211430451-91e74b0c-c047-482a-b2a8-e1e8e3ff9d10.png">

Is there any progress on this issue being solved?

**Comment by kyessenov** [comment]
I think I know how to solve this with the new native stats filter but it hasn't been prioritized.

**Comment by kyessenov** [comment]
https://github.com/istio/proxy/pull/4597 is the fix PR.

12h is the default which seems reasonable enough to cover long-running proxies.

**Comment by zirain** [comment]
fixed by https://github.com/istio/istio/pull/44605
release in v1.18
