### ISSUE TITLE
502's when host contains port

### ISSUE THREAD

**Issue by Stono** [istio/istio#21384]
**Bug description**
Hey, 
I've noticed some people requesting some of our services with a port on the end of the host header, for example `https://www.some-service.com:443`,  this translates to having a `Host: some-service.com:443`.

Envoy is then rejecting this (we have REGISTRY_ONLY) with a 502.

I've tried adding `some-service.com:443` to the `VirtualService` hosts, but it doesn't work.

I could start looking at rewriting the host header to remove it at our edge, but would be easier if this worked in the VirtualService?

Thoughts?

**Expected behavior**
Adding `some-host.com:443` to the `VirtualService` hosts, should make it routable.

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.4.5

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
Usually we set up virtual hosts with and without the port included. I think there may be some situations where that doesn't happen though, the logic is fairly complicated. Can you post the route snippet?

**Comment by Stono** [comment]
<img width="1083" alt="Screenshot 2020-02-23 at 16 12 43" src="https://user-images.githubusercontent.com/1486729/75115545-61bad880-5657-11ea-988e-c407d5341e74.png">

So my setup might be causing this, but so we're very clear we see this:

`user` -- `https://www-preprod.autotrader.co.uk:443` --> `nginx` -- `http://app.some-app with Host: www-preprod.autotrader.co.uk:443` -- `envoy` --> 502.

**Comment by Stono** [comment]
And I'm not able to add the `443` to the virtualservice:
```
Error: 1 error occurred:
        * VirtualService/consumer-gateway/consumer-gateway-app: domain name "autotrader.co.uk:443" invalid (label "uk:443" invalid)
```

**Comment by howardjohn** [comment]
Ah got it, so the mismatch is because we have a different port in the host than the routes, not just that it contains the port. Thanks!

**Comment by Stono** [comment]
I probably need to mutate it at my edge then!

**Comment by Stono** [comment]
Interestingly @howardjohn this doesn't register in the metrics as a `BlackHoleCluster`, despite it 502'ing

**Comment by Stono** [comment]
FYI in investigating this; I've stumbled on the fact with telemetry v2, blackholecluster metrics no longer work: https://github.com/istio/istio/issues/21385

**Comment by Stono** [comment]
Closing as I've solved this at our edge with nginx (linked issue)
