### ISSUE TITLE
TestAnalyzeNamespaceMessageHasOriginWithNoNamespace test flake

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#21389]
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/21388/unit-tests_istio/9021

**Comment by zerobfd** [comment]
Here's the invocation I had to use to get any repros:

go test -run TestAnalyzeNamespaceMessageHasOriginWithNoNamespace -race -cpu 1,2,3,4 -count 10000

Looking at the last ~20 test failures on prow, it looks like this one failed once. Another test from the same suite (analyzingdistributor_test.go) also failed once. Both failures were from timing out. A quick look at the file suggests that it may be some locking issue.

**Comment by zerobfd** [comment]
It seems like an actual issue--even if I bump the timeout to something ridiculous (20s) it still times out:

```
>>> go test -run TestAnalyzeNamespaceMessageHasOriginWithNoNamespace -race -cpu 4 -count 10000 -failfast
--- FAIL: TestAnalyzeNamespaceMessageHasOriginWithNoNamespace (20.00s)
    analyzingdistributor_test.go:226: 
        Timed out after 20.000s.
        Expected
            <diag.Messages | len:0, cap:0>: nil
        to have length 1
FAIL
exit status 1
FAIL	istio.io/istio/galley/pkg/config/processing/snapshotter	48.538s
```

**Comment by howardjohn** [comment]
Another one: https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/22040/unit-tests_istio/9952
Should we skip this whole suite of tests, they all flake quite often. Ref https://github.com/istio/istio/issues/22042

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gcs/istio-prow/logs/unit-tests_istio_postsubmit/1728

I suggest we skip

**Comment by howardjohn** [comment]
lets consolidate with https://github.com/istio/istio/issues/20936
