### ISSUE TITLE
multicluster installation error: bad path=value: autoInjection.enabled=true 

### ISSUE THREAD

**Issue by rvennam** [istio/istio#21386]
**Bug description**
Error while installing remote Istio on cluster 2. I'm following this guide: https://preliminary.istio.io/docs/setup/install/multicluster/shared-gateways/#setup-cluster-2
```
(⎈ |mc2/bp8qqkmd0rgc3c2i62rg:default)
~/istio-1.5-alpha.176548fffbdcb928ae14c7b5335b42538793cef6 🏎  $ ./bin/istioctl manifest apply --context=$CTX_CLUSTER2 \
>   --set profile=remote \
>   --set values.global.mtls.enabled=true \
>   --set values.gateways.enabled=true \
>   --set values.security.selfSigned=false \
>   --set values.global.createRemoteSvcEndpoints=true \
>   --set values.global.remotePilotCreateSvcEndpoint=true \
>   --set values.global.remotePilotAddress=${LOCAL_GW_ADDR} \
>   --set values.global.remotePolicyAddress=${LOCAL_GW_ADDR} \
>   --set values.global.remoteTelemetryAddress=${LOCAL_GW_ADDR} \
>   --set values.gateways.istio-ingressgateway.env.ISTIO_META_NETWORK="network2" \
>   --set values.global.network="network2" \
>   --set values.global.multiCluster.clusterName=${CLUSTER_NAME} \
>   --set autoInjection.enabled=true
Error: failed to generate and apply manifests, error: failed to generate tree from the set overlay, error: bad path=value: autoInjection.enabled=true
```

I'm able to move past this if I remove the `--set autoInjection.enabled=true` flag

[ ] Configuration Infrastructure
[ ] Docs
[X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**
https://preliminary.istio.io/docs/setup/install/multicluster/shared-gateways/#setup-cluster-2

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.5-alpha.176548fffbdcb928ae14c7b5335b42538793cef6

**How was Istio installed?**
Dev build: https://gcsweb.istio.io/gcs/istio-build/dev/1.5-alpha.176548fffbdcb928ae14c7b5335b42538793cef6

**Environment where bug was observed (cloud vendor, OS, etc)**
IKS 1.16

**Comment by richardwxn** [comment]
this is a doc issue,I can fix that

**Comment by rvennam** [comment]
@richardwxn thanks. Another maybe doc issue...
I removed the `autoInjection.enabled=true` flag and the install completed, but there is no Citadel.
```
(⎈ |mc2/bp8qqkmd0rgc3c2i62rg:default)
~/istio-1.5-alpha.176548fffbdcb928ae14c7b5335b42538793cef6 🏎  $ ./bin/istioctl manifest apply --context=$CTX_CLUSTER2 \
>   --set profile=remote \
>   --set values.global.mtls.enabled=true \
>   --set values.gateways.enabled=true \
>   --set values.security.selfSigned=false \
>   --set values.global.createRemoteSvcEndpoints=true \
>   --set values.global.remotePilotCreateSvcEndpoint=true \
>   --set values.global.remotePilotAddress=${LOCAL_GW_ADDR} \
>   --set values.global.remotePolicyAddress=${LOCAL_GW_ADDR} \
>   --set values.global.remoteTelemetryAddress=${LOCAL_GW_ADDR} \
>   --set values.gateways.istio-ingressgateway.env.ISTIO_META_NETWORK="network2" \
>   --set values.global.network="network2" \
>   --set values.global.multiCluster.clusterName=${CLUSTER_NAME}
proto: tag has too few fields: "-"
- Applying manifest for component Base...
✔ Finished applying manifest for component Base.
- Applying manifest for component IngressGateways...
✔ Finished applying manifest for component IngressGateways.

✔ Installation complete
```
```
(⎈ |mc2/bp8qqkmd0rgc3c2i62rg:default)
~/istio-1.5-alpha.176548fffbdcb928ae14c7b5335b42538793cef6 🏎  $ kubectl get pods -n istio-system
NAME                                    READY   STATUS              RESTARTS   AGE
istio-ingressgateway-864fb7876f-7gbbl   0/1     ContainerCreating   0          28m
```

**Comment by richardwxn** [comment]
@rvennam I think the standalone citadel component is disabled for 1.5, the functionality is part of istiod now

**Comment by rvennam** [comment]
Found the existing issue for missing citadel in remote: #21281

**Comment by howardjohn** [comment]
These docs have been completely revamped for 1.6 so I think these issues are resolved now. Thanks!
