### ISSUE TITLE
Remove specific knowledge of TCP attributes from Mixer

### ISSUE THREAD

**Issue by geeknoid** [istio/istio#2139]
Right now, the Mixer has specific knowledge of TCP attributes for context selection. Mixer should be agnostic to specific attributes, so the TCP stuff needs to be expressed through config instead.

**Comment by douglas-reid** [comment]
I believe we discussed that this involves updating the yaml templates to avoid labels and prefer `context.protocol == tcp` expressions.

**Comment by wora** [comment]
One server can handle multiple protocols at the same time, so the concept
of context is vague. It should be part of a connection or a session or a
request. A standalone context at top-level doesn't seem proper.

**Comment by geeknoid** [comment]
This is a per-request context. Is this request about a TCP event, and HTTP
event, a mySQL event, etc...

**Comment by douglas-reid** [comment]
each check or report to mixer is about a specific operation. request.* is http centric, connection.* is tcp centric. having a common way to identify the protocol of the "event" being checked/reported to mixer was important.

we had a design doc around this issue and a long discussion/debate about the name of the attribute before. i'd rather not re-litigate that in the scope of updating the YAMLs to eliminate the problematic labels.

**Comment by wora** [comment]
Now I understand the `context` better. :)

We do have an interesting problem now: Envoy doesn't agree with Istio
attribute namespace. Istio request maps to Envoy request.http, very likely
Istio connection maps to Envoy request.tcp. We need to find a way to keep
the mapping sane. I wish we had converged the attributes from start. Now it
is much harder.

**Comment by mandarjog** [comment]
There are two issues involved here.
1. Very localized problem of context.protocol attribute (which is an enum) and specific code to preparse it out of selector expressions.
That problem can be solved by externalizing the notion of contexts.

2. More longer term issue is, is the request abstraction the best way to represent this information.  Or request.http.* request.tcp.* are better at representing this information.
Request.http.* request.redis.* naturally lets us write expressions without an external notion of context.

#2 we should discuss later at length.
#1 we already have a plan to add contexts.

**Comment by douglas-reid** [comment]
@mandarjog I'm not sure I agree with your characterization of the problem.

The issue, as I understand it, is that there is config in istio/istio uses the short-lived `istio-protocol` label. That config needs to be updated to transfer the logic to `match:` clauses.

There should not be an issue in using `match` clauses with any attribute -- and it should not require any specific preprocessing code.  The existing logic for dealing with `match` clause evaluation should work just fine -- and we can strip out all of the specialized code.

If we want to later add some other externalization of context for attributes, that's grand, but I don't see it as strictly required to close this issue out.

I think we should be very careful how we approach adding this notion of contexts, as we have been burned by this thinking before (and it left us in the "istio-protocol" mess being discussed here).

**Comment by geeknoid** [comment]
I think what Mandar is suggesting with his #2 is that instead of having a
specific context.protocol attribute, we could 'scope' other attributes such
that the operator is always implicitly working in a protocol-specific world
based on the attributes that are used. So there's no need to have a
specific match clause for the protocol.

**Comment by douglas-reid** [comment]
I believe this has been resolved, based on recent PRs from @bianpengyuan .
