### ISSUE TITLE
Communication issues from mesh cluster to VM using mesh expansion

### ISSUE THREAD

**Issue by Docteur-RS** [istio/istio#21398]
## Bug description
Communication between the mesh service in kubernetes and a VM with mesh expansions scripts installed is not working.

**The main problem identified is that the iptables are not set.**

On Kubernetes:
* Installed Istio 1.4.3
* Enabled mesh expansion
* Enabled MTLS cluster wide
* Applied a serviceEntry
* Integrated the mapping with our own DNS system using `istioctl`

On the VM:
* Installed the .deb package using `dpkg`
* Extracted the systemd config to the right path
* CSR signing using node_agent is ok
* Envoy has started

## What has been tested
**Connectivity status**
* Connectivity from Host using ip address of service with no sidecar => ❌ 
* Connectivity from pod using service name (DNS résolution) and sidecar injection => ❌  

I guess the last one is normal procedure as we are asked to deploy a service entry...

On the VM the traffic seems to be intercepted by Envoy as seen on the admin console.  
From outside the VM the Envoy server doesn't seem to expose any external ports (8080)  

**Identified problem**
On the VM, even when executing the `/usr/local/bin/istio-iptables.sh` manualy, no iptables are created.
Checking `sudo iptables -L` returns nothing:
```
Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
``` 
With no rules set, incomming requests can't be redirected to Envoy. Is this normal ?  

## Expected behavior
Communication from a pod using the service name should reach the service on the VM.

## Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)
```shell
$ istioctl version --remote
client version: 1.4.3
control plane version: 1.4.3
data plane version:  (1 proxies), 1.4.3 (6 proxies)
```
## How was Istio installed?
Kubernetes: Using Helm  
VM: Using `dpkg`  

## Environment where bug was observed (cloud vendor, OS, etc)
On premise

Kubernetes : CentOs 7  
VM : Ubuntu 14.04 (CSR signing is not working on Debian 9)

**Comment by howardjohn** [comment]
dupe https://github.com/istio/istio/issues/21399
