### ISSUE TITLE
Installing istioctl via documentation fails

### ISSUE THREAD

**Issue by ahmetb** [istio/istio#214]
https://istio.io/docs/tasks/installing-istio.html this doc says

```
source ../../istio.VERSION
curl ${ISTIOCTL_URL}/istioctl-osx > /usr/local/bin/istioctl
```

the second step fails as I'm not root/sudo.

I recommend changing this command to:

```
sudo wget -qO /usr/local/bin/istioctl ${ISTIOCTL_URL}/istioctl-osx
```

**Comment by ahmetb** [comment]
chmod +x /usr/local/bin/istioctl

also needs `sudo`

**Comment by ldemailly** [comment]
I fixed it to use the tar with all the binaries
(the sudo depends on where you put the binary, added a comment about anywhere in the $PATH)

**Comment by ahmetb** [comment]
@ldemailly I think the docs should just provide instructions that work. /usr/local/bin/ probably fine for Mac/Linux users.

**Comment by ldemailly** [comment]
@ahmetb sudo isn't always necessary and I think we expect our users to be able to handle a "permission denied" on their own if needed (tell me if that's a wrong assumption). Possibly in the future we can have an installer that takes cares of this, probably not changing istioctl globally on the machine but leaving it local to the version being installed/tested
