### ISSUE TITLE
1.4.5 w/ istio-validation causing pod hangups

### ISSUE THREAD

**Issue by haf** [istio/istio#21409]
**Bug description**

After upgrading from 1.4.3 to 1.4.5, there was a new component "istio-validation" which crashes some pods.

Trying the hello-world sample sometimes fails in long running clusters with this error message:

```
$ k logs helloworld-v1-7fdd67766b-s5p26 -c istio-validation --previous
in new validator: 10.40.1.2
Listening on 127.0.0.1:15001
Listening on 127.0.0.1:15006
Error connecting to 127.0.0.6:15002: dial tcp 127.0.0.1:0->127.0.0.6:15002: connect: connection refused
Error connecting to 127.0.0.6:15002: dial tcp 127.0.0.1:0->127.0.0.6:15002: connect: connection refused
Error connecting to 127.0.0.6:15002: dial tcp 127.0.0.1:0->127.0.0.6:15002: connect: connection refused
Error connecting to 127.0.0.6:15002: dial tcp 127.0.0.1:0->127.0.0.6:15002: connect: connection refused
Error connecting to 127.0.0.6:15002: dial tcp 127.0.0.1:0->127.0.0.6:15002: connect: connection refused
Error connecting to 127.0.0.6:15002: dial tcp 127.0.0.1:0->127.0.0.6:15002: connect: connection refused
... etc until the pod reinitialises
```

**Expected behaviour**:
Istio-validation should not crash my pods

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
$ istioctl version --remote
client version: 1.4.5
citadel version: 1.4.5
egressgateway version: 1.4.5
egressgateway version: 1.4.5
galley version: 1.4.5
ingressgateway version: 1.4.5
ingressgateway version: 1.4.5
nodeagent version:
nodeagent version:
nodeagent version:
pilot version: 1.4.5
pilot version: 1.4.5
policy version: 1.4.5
policy version: 1.4.5
sidecar-injector version: 1.4.5
telemetry version: 1.4.5
telemetry version: 1.4.5
data plane version: 1.4.5 (22 proxies)
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.8-gke.3", GitCommit:"2ccf2c797713077f4a3d0f87c4b4bae725362326", GitTreeState:"clean", BuildDate:"2020-01-29T19:27:22Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}

```

**Steps to reproduce the bug**:
The hello-world example, 3 machines with CNI, with pods spread evenly via anti-affinity rules and pre-emtible GKE nodes; sometimes — because deleting the pod often makes it work again.

**Anything else we need to know?**:

**Environment details:**: GKE
- Kubernetes version (e.g. v1.10.2): 1.15
- Cloud-provider/provisioner (e.g. GKE, kops AWS, etc): GKE
- Install method (e.g. helm or static manifests): istioctl — you should update this question

**How was Istio installed?**: istioctl

**Comment by lambdai** [comment]
@haf 
I am curious if istio-validation actually prevent the outrage.
Istio-validation is supposed to catch the race condition of pod creation prior to istio-cni is `ready`.
As far as I know this race condition is likely to happen when node is newly provisioned. "pre-emtible GKE nodes" does ring the bell.

Please check if label [`cni.istio.io/uninitialized=true` is set ](https://github.com/istio/installer/blob/release-1.4/istio-cni/values.yaml#L43-L44cni.istio.io/uninitialized) on that crash looping pod. That is what 1.4.5 could do. 

You can choose to delete pod with that label, or
Since 1.5 you can opt-in istio-cni daemonset to delete the crashing pod for you.

**Comment by haf** [comment]
@lambdai It's hard to reproduce. I'm not sure what that annotation/label would mean? Even if it's set, `istio-validator` stops the pod from starting? Isn't there a deeper problem being indicated here?

**Comment by lambdai** [comment]
@haf 
> I'm not sure what that annotation/label would mean? 
That's one of the istio-cni daemonset 's reaction, to expose the problem.

>  Even if it's set, istio-validator stops the pod from starting? 
Actually istio-validator stops the owned pod from starting and the label is the consequence. That label acts as an alert. 
istio-validator as a *preinit* container with low privilege, istio-validator cannot repair by itself. The only legit move is crash looping the pod and hope other k8s controller fix the problem. And in istio 1.5 istio-cni with the role of that "controller" provides the option to delete the pod as what you do.

If you choose to roll back to 1.4.3 you are actually jeopardizing the pod. Please don't unless you fully understand the risk! See 1.4.5 release notes here: https://istio.io/news/releases/1.4.x/announcing-1.4.5/

**Comment by haf** [comment]
@lambdai I see — so in summary, by skimming the issues linked from the news;

- CNI and Calico and istio-proxy race
- This could be solved using a dependency graph, but there exists none
- So we work around it with a new controller that deletes broken pods
- Hence, it's unsafe to downgrade to 1.4.3 and we should either manually keep watch on broken pods or hurry with the upgrade to 1.5.0.

**Comment by lambdai** [comment]
@haf Thank you for the summary! 
I think we are on the same page and I am closing this issue
