### ISSUE TITLE
Enable Secret Discovery Service (SDS) - "istio-citadel" is invalid: spec.template.metadata.labels: Invalid value

### ISSUE THREAD

**Issue by JCzz** [istio/istio#21403]
I have installed Knative via kubectl and not Helm from here: https://knative.dev/docs/install/knative-with-gke/

Trying to enable Secret Discovery Service (SDS)  to be able to use Knative and Istio with tls:
https://knative.dev/docs/serving/using-auto-tls/

Tried to enable SDS from this: https://istio.io/docs/tasks/traffic-management/ingress/secure-ingress-sds/

I then get:
```
...
deployment.apps/istio-telemetry configured
poddisruptionbudget.policy/istio-telemetry created
service/istio-telemetry configured
serviceaccount/istio-mixer-service-account configured
The Deployment "istio-citadel" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"app":"citadel", "istio":"citadel"}: `selector` does not match template `labels`
```

And:

curl https://autoscale-go.default.mydomain.com
curl: (7) Failed to connect to autoscale-go.default.mydomain.com port 443: Connection refused

**Comment by howardjohn** [comment]
Was this from running 

```
$ istioctl manifest generate \
--set values.gateways.istio-egressgateway.enabled=false \
--set values.gateways.istio-ingressgateway.sds.enabled=true > \
$HOME/istio-ingressgateway.yaml
$ kubectl apply -f $HOME/istio-ingressgateway.yaml
```

If so, what version of istioctl?

**Comment by JCzz** [comment]
Yes, it was from running "istioctl manifest generate \..."

istioctl version is: 

client version: 1.4.5
control plane version: 68f98140be68503c83765a93047d5afe95e910cc-dirty
data plane version: 1.2.10-gke.1 (8 proxies)

**Comment by howardjohn** [comment]
I see you have
```
control plane version: 68f98140be68503c83765a93047d5afe95e910cc-dirty
data plane version: 1.2.10-gke.1 (8 proxies)
```

Are you installing this into a cluster with istio already present? Maybe that is conflicting here

**Comment by JCzz** [comment]
Hmm yes, Istio is already installed via Knative. Is there no way to enable SDS in an existing installation?

**Comment by howardjohn** [comment]
You need to install it in the same way though. It looks like you are trying
to go from Istio on GKE 1.2 to 1.4 installed with 1.4 which is not a
supported upgrade path. As far as I know upgrade from Istio on GKE to OSS
istio is not supported

**Comment by JCzz** [comment]
I updated kubernetes engine to `1.15.9-gke.9` after installing knative, do you think this can cause this?

**Comment by howardjohn** [comment]
No, it is just related to how your previous installation was done.  The GKE
addon for istio does not support customization

**Comment by JCzz** [comment]
Do you know how to enable Istio SDS in an existing installation - like with Knative?

**Comment by JCzz** [comment]
Ahh ok, no customization - hmm, then no tls I guess. Strange though

**Comment by howardjohn** [comment]
You installed https://cloud.google.com/istio/docs/istio-on-gke/overview.
This is not compatible with customization. Please see the docs there, I
think you will need to uninstall that first then install OSS Istio. The
product you installed is a GCP product, not managed by the istio/istio
github project

>

**Comment by JCzz** [comment]
Thanks, I will try again with an OSS Istio.

Something like:
1. Install Knative
2. delete istio-system namespace
3. And then find an OSS Istio installation

**Comment by howardjohn** [comment]
I think if you do that, it will reinstall the old Istio after step 2
automatically. You need to disable the Istio addon from the gcloud command
or GKE UI

**Comment by howardjohn** [comment]
Closing this as this was a result of Istio on GKE so is working as expected.
