### ISSUE TITLE
TCP metadata propagation

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#2142]
Metadata is propagated between client side and server side envoys thru http request headers.
source.uid is an example of this meta data. The client side envoy places it in private headers and the server side envoy uses the information to call mixer.

We do not have an equivalent mechanism to propagate metadata over a tcp connection.

**Comment by mandarjog** [comment]
@costinm @jasminejaksic @kyessenov

**Comment by mandarjog** [comment]
Potentially something like https://github.com/aporeto-inc/trireme-lib

**Comment by mandarjog** [comment]
Potentially use TCP stream over H2 streams. @PiotrSikora we could use this to propagate metadata.
What are the performance implications ? Would be nice to do TCP over H2 over mtls.

**Comment by PiotrSikora** [comment]
Indeed :) See https://github.com/envoyproxy/envoy/issues/1630 and https://github.com/envoyproxy/envoy/issues/2394.
