### ISSUE TITLE
Use release-builder on a Mac to build master

### ISSUE THREAD

**Issue by ericvn** [istio/istio#21449]
**Bug description**

I'm running into a few issues trying to run release-builder locally on my Mac on the _master_ branch.

1:
```
time (docker save -o /work/out/linux_amd64/release/docker/install-cni.tar docker.io/ericvn/install-cni:build-test && gzip /work/out/linux_amd64/release/docker/install-cni.tar)

real	0m21.267s
user	0m9.626s
sys	0m1.271s
2020-02-24T21:06:10.617965Z	info	Running command: mkdir -p /tmp/tmp.dulNdLvzYq/build/out
Error: failed to build: failed to build Docker: failed to package docker images: open /tmp/tmp.dulNdLvzYq/build/work/out/linux_amd64/release/docker: no such file or directory
exit status 1
```

** In this case there are no files to copy. Add an if check to this as well **

2.
```
Created package {:path=>"/work/out/linux_amd64/release/istio-sidecar.deb"}
2020-02-24T22:20:38.413653Z	info	Copying /tmp/tmp.dulNdLvzYq/build/work/src/istio.io/istio/out/linux_amd64/release/istio-sidecar.deb -> /tmp/tmp.dulNdLvzYq/build/out/deb/istio-sidecar.deb
Error: failed to build: failed to build Debian: failed to package istio-sidecar.deb: failed to open file /tmp/tmp.dulNdLvzYq/build/work/src/istio.io/istio/out/linux_amd64/release/istio-sidecar.deb to copy: open /tmp/tmp.dulNdLvzYq/build/work/src/istio.io/istio/out/linux_amd64/release/istio-sidecar.deb: no such file or directory
exit status 1
```

```
cd /
find . -name istio-sidecar.deb
...
./work/out/linux_amd64/release/istio-sidecar.deb
```
** The file is not in the Repo out directory, but where it's trying to be copied. **

**Expected behavior**

release-builder should run locally on the master branch

**Steps to reproduce the bug**

Run release-builder locally. Steps will be in the README.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

_master_ 

**How was Istio installed?**
N/A

**Environment where bug was observed (cloud vendor, OS, etc)**

MacOS

**Comment by howardjohn** [comment]
Are you running within a docker container or directly from your mac?

**Comment by ericvn** [comment]
@howardjohn I am running inside a docker container.

Basic steps (this is what I am documenting)
 - Get the docker run command that is run in the makefile (confirm image is the same as used in prow) and modify to simply run `sh` at the moment
 - Create a manifest file
 - Run a container and at the command prompt:
  - mkdir the directory specified in the manifest
  - run `go run main.go build --manifest manifest`

**Comment by ericvn** [comment]
OK. I think I can resolve all the issues with tweaks to the `docker run`. Closing for now.
