### ISSUE TITLE
Stop running Envoy during prometheus sidecar

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#21457]
Right now we have a very complex setup just to get prometheus a certificate. We run Envoy, then envoy connects to pilot, then pilot sends SDS config for secret `default`, then envoy sends an SDS requests to the agent, then the agent fetches the secret and writes it to a file.

This is incredibly complicated just to fetch a file and write it to disk. All we need to do is

```
callCsr()
writeToDisk()
go func() {
  every once and a while {
     refresh cert
   }
}
```

The installation can be as simple as 
```
- name: istio-proxy
image: proxyv2
command: agent --only-dump-cert
```

rather than the huge amount of yaml config we provide today

**Comment by lei-tang** [comment]
Design document: https://docs.google.com/document/d/1d1uLpVJzBcXELb5ew-dj5PyN5wQz9mbTUBgLcLebR48
