### ISSUE TITLE
Postsubmit test failures of TestWebhook and TestWebhookManagement with https://github.com/istio/istio/commit/c54e05a625806fc8b5a260487c3b197b3d88e019

### ISSUE THREAD

**Issue by lei-tang** [istio/istio#21455]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
According to https://testgrid.k8s.io/istio_release-1.5_istio_postsubmit#integ-k8s-116_istio_release-1.5_postsubmit, postsubmit tests TestWebhook and TestWebhookManagement begin to fail after  https://github.com/istio/istio/commit/c54e05a625806fc8b5a260487c3b197b3d88e019 is merged into the release-1.5 branch.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[X ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Tests pass.

**Steps to reproduce the bug**
View the test results on
https://testgrid.k8s.io/istio_release-1.5_istio_postsubmit#integ-k8s-116_istio_release-1.5_postsubmit

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
Not sure the exact PR but this is fixed now
