### ISSUE TITLE
https://istio.io/downloadIstioctl script doesn't detect failure to download

### ISSUE THREAD

**Issue by esnible** [istio/istio#21464]
To reproduce,

```
$ curl -sL https://istio.io/downloadIstioctl | ISTIO_VERSION=dummy sh -
Downloading istioctl-dummy-osx.tar.gz from https://github.com/istio/istio/releases/download/dummy/istioctl-dummy-osx.tar.gz ... 
istioctl-dummy-osx.tar.gz download complete!
tar: Error opening archive: Unrecognized archive format
mv: /tmp/istioctl.0749jg/istioctl: No such file or directory

Add the istioctl to your path with:
  export PATH=$PATH:$HOME/.istioctl/bin 

Begin the Istio pre-installation verification check by running:
	 istioctl verify-install 
```

The output should not say "download complete!" and offer additional instructions if the installation fails.

**Comment by johnma14** [comment]
Once [this fix](https://github.com/istio/istio/pull/21496) gets cherry picked to 1.5, we can close this issue. Thanks Ed.

**Comment by dgn** [comment]
> Once [this fix](https://github.com/istio/istio/pull/21496) gets cherry picked to 1.5, we can close this issue. Thanks Ed.

Cherry-pick: https://github.com/istio/istio/pull/21764
