### ISSUE TITLE
Stand-alone istioctl has no OSX or Win versions in beta3

### ISSUE THREAD

**Issue by esnible** [istio/istio#21462]
Visit https://github.com/istio/istio/releases/tag/1.5.0-beta.3

See that the Linux stand alone istioctl is there, but not OSX or Win.

beta.2 had both.

**Comment by johnma14** [comment]
Closing this issue as it was because there was a GitHub outage that prevented the OSX and Windows artifacts from getting uploaded. If this issue persists in the next beta build, we can reopen this again
