### ISSUE TITLE
in-cluster operator fails to deploy grafana

### ISSUE THREAD

**Issue by dgn** [istio/istio#21470]
**Bug description**
When following https://preliminary.istio.io/docs/setup/install/standalone-operator/ the operator never deploys grafana.

**Expected behavior**
Grafana is deployed successfully

**Steps to reproduce the bug**
https://preliminary.istio.io/docs/setup/install/standalone-operator/

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.5.0-beta.3

**Comment by ostromart** [comment]
This is because cherry-pick https://github.com/istio/api/pull/1301 was missed. I verified it's fixed now.
