### ISSUE TITLE
updating VirtualService will not affect sidecar proxy until pod restart

### ISSUE THREAD

**Issue by mstrYoda** [istio/istio#21477]
**Bug description**
When we update a VirtualService to add timeout it does not affect the sidecar proxy until we restart the pod. I don't know if is this the expected behavior.

**Expected behavior**
Sidecar proxy affects from VirtualService changes immediately.

**Steps to reproduce the bug**
Create VirtualService and then update it.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
This is not expected. Does this always happen? Can you reproduce it?

It would be helpful to look at the config dump before and after to see if it changes - https://github.com/istio/istio/wiki/Troubleshooting-Istio for more info. You can also run `istioctl ps POD` to see if the config matches in control plane and data plane. Thanks

**Comment by mstrYoda** [comment]
Hi @howardjohn I will try to reproduce it (if possible) as soon as I become available. May be (probably) I did something wrong.

**Comment by howardjohn** [comment]
We have testing for this and have never experienced this, and there is no further info on how to debug. For now I will close, if we can get some more info we can investigate further. Thanks
