### ISSUE TITLE
Frequent merge conflicts in assets.gen.go and golden files

### ISSUE THREAD

**Issue by ostromart** [istio/istio#21502]
Frequent chart changes lead to frequent updates to operator/pkg/assets.gen.go. 
Frequent operator code changes can also lead to updates to the goldens in operator/cmd/mesh/testdata. 
Both of these are likely to occur around release time.
Because git doesn't know how to correctly resolve either of these, it means that merging or rebasing will lead to frequent conflicts. 
It's too late to do anything about it in 1.5, but here's a recipe to make the merges less painful. If you're working on a branch and need to merge from (say) master:

```bash
git pull upstream master
<conflicts one or both of the above>
# Regenerate the assets and goldens
make gen-charts refresh-goldens
# Check that there are no other merge conflicts
git diff --name-only --diff-filter=U
# If nothing shows up, proceed, otherwise git mergetool
git add .
git commit
```
As long as the charts don't have any conflicts you can't perform the above steps without thinking or worrying about it. There's no need to resolve any conflicts in these generated files manually.
We'll be streamlining this process post 1.5, including possibly removing assets.gen.go completely, pruning back the golden file outputs etc.

**Comment by mandarjog** [comment]
I think this is also a time to re-evaluate if go-bindata should be used at all. I generally think that hidden configuration should be avoided. I understand that this makes the initial install experience easy, but the chance of inadvertently applying the wrong config is too risky.

I think one way to maintain Simple user experience is to add a fetch-manifest command that will get it From the release site.

**Comment by mandarjog** [comment]
The other alternative is not to check-in this file but use go generate to create it during make.

**Comment by howardjohn** [comment]
The problem with merge conflicts is that you need to redo your PR. It doesn't matter any commands you can run locally to fix it, if GitHub cannot automatically do it then I need to redo my PR multiple times per day

**Comment by mandarjog** [comment]
They use go generate and never check it in., but not having baked in data files is preferred.

**Comment by howardjohn** [comment]
I was most referring to the golden files in my comment. I don't think go supports on the fly generation though?

**Comment by mandarjog** [comment]
`go build` does not, but we can do whatever we want with `make` and use go generate.

**Comment by howardjohn** [comment]
I would love to not break `go build`

**Comment by mandarjog** [comment]
For prod or developer use?

go build for developer use can be easily maintained. Checking a file with
static content and then place it in .gitignore.
If you care about the currency of those contents, then you *will* run go
generate.
Official build *will* run go generate.

**Comment by howardjohn** [comment]
This will break anyone importing Istio, running go get, go install, etc. If
we are going through this many hacks lets just remove the generation

**Comment by ostromart** [comment]
I think this is in a sufficiently good state now it can be closed.
