### ISSUE TITLE
Request for istioctl subcommand to get Envoy version in use on pod

### ISSUE THREAD

**Issue by yanniszark** [istio/istio#21517]
**Describe the feature request**

Get the envoy version used by the Istio proxy.
Currently, the [latest version of Istio Docs](https://istio.io/docs/ops/diagnostic-tools/proxy-cmd/#what-envoy-version-is-istio-using) instruct the user to do:

```console
$ kubectl exec -it PODNAME -c istio-proxy -n NAMESPACE pilot-agent request GET server_info
```

However, that returns the commit from envoy/proxy.
We want to get the version of the Envoy proxy running, that is a commit on envoyproxy/envoy or istio/envoy.

**Use Case**

Given an issue in envoyproxy/envoy and a PR that fixes it, we want a straightforward way of checking if the PR's commits are inside the Istio proxy that is running.

**Describe alternatives you've considered**

Currently, to do that, we have to go to istio/proxy, open the WORKSPACE file and get the ENVOY_SHA used, as well as Envoy's repo.

There is an old issue: https://github.com/istio/istio/issues/6572
and PR: https://github.com/istio/istio/pull/11524
which are supposed to add this information to labels on the Docker images.
However, it seems that this isn't the case:

```console
$ docker inspect -f '{{json .Config.Labels }}' istio/proxyv2:1.1.6
null

$ docker inspect -f '{{json .Config.Labels }}' istio/proxyv2:1.3.1
{"envoy-vcs-ref":"","istio-api-vcs-ref":""}

$ docker inspect -f '{{json .Config.Labels }}' istio/proxyv2:1.4.5
null
```

[X] Docs
[X] User Experience
[X] Developer Infrastructure

This is mainly @dimara's work, I'm just opening the issue.
/cc @dimara @elevran

**Comment by esnible** [comment]
How about `istioctl proxy-config  bootstrap <pod> | jq .bootstrap.node.hiddenEnvoyDeprecatedBuildVersion` as a work-around?

The output would be

```
"524cfb2be117f343fd25c609bdd622eca7c2b4f5/1.13.1-dev/Clean/RELEASE/BoringSSL"
```

`jq` is a common command line tool for parsing JSON, see https://stedolan.github.io/jq/

**Comment by esnible** [comment]
@yanniszark does this resolve your issue?

**Comment by yanniszark** [comment]
@esnible thanks for your answer.
I will try that out asap.
In any case, I believe we should document this in the docs, because this is a valid use case.
I would propose amending the current section to reflect that.
What do you think?

**Comment by esnible** [comment]
We have a command `istioctl proxy-config bootstrap <pod>` which outputs the JSON configuration for Envoy.  The other troubleshooting commands, `proxy-config listeners`, `routes`, `clusters`, `secrets` have option for short output or full JSON output.

I did not create an easy-to-use summary output for `bootstrap` because I did not know which Envoy bootstrap values were meaningful for troubleshooting configuration problems.

Do you have any insight on which Envoy global settings would make use in a troubleshooting summary command?

**Comment by yanniszark** [comment]
@esnible in our case, the question we want to answer is:

We know Envoy has a bug, documented in issue X.
We know issue X is fixed by PR Y.
Are the commits of PR Y inside the Envoy I'm running?

To check this, we have to know the commit version of the Envoy running inside the Istio proxy Pod.
This is why I think it should be documented explicitly.

**Comment by esnible** [comment]
@istio/wg-networking-maintainers-data-plane Would it be useful to provide a troubleshooting command to show the Envoy version running in a pod?  Should it be implemented by getting a config_dump and looking at the bootstrap info, similar to my work-around above?

**Comment by esnible** [comment]
@istio/wg-networking-maintainers-data-plane Would it be useful to provide a troubleshooting command to show the Envoy version running in a pod? Should it be implemented by getting a config_dump and looking at the bootstrap info, similar to my work-around above?

**Comment by howardjohn** [comment]
When envoy shows

```
            "userAgentBuildVersion": {
                "version": {
                    "majorNumber": 1,
                    "minorNumber": 14,
                    "patch": 1
                },
                "metadata": {
                        "build.type": "RELEASE",
                        "revision.sha": "12cfbda324320f99e0e39d7c393109fcd824591f",
                        "revision.status": "Clean",
                        "ssl.version": "BoringSSL"
                    }
            },

```

the SHA is istio/proxy sha not istio/envoy SHA which is what is requested here.

However, we are now based on Envoy releases not random SHAs, so using userAgentBuildVersion.version is actually probably pretty close

**Comment by abhide** [comment]
@esnible @howardjohn Just to make sure I understand this correctly; the fix would to have something like 
`istioctl proxy-config bootstrap --version` output Istio Version + envoy's userAgentBuildVersion?

**Comment by esnible** [comment]
@yanniszark when we build the istio/proxy image, the `istio.io/proxy/WORKSPACE` file contains the Envoy-WASM SHA.   Is that SHA sufficient for you or do you need the SHA of base Envoy?  We do have the Envoy version, in my case 1.16, which should be enough to let users know which Envoy version to look up in https://www.envoyproxy.io/docs .

@howardjohn As a first step, printing the Envoy version (1.16) is a good start for the CLI.  How can we get the Envoy SHA into the metadata?  Envoy itself doesn't know it.  `kubectl exec -it deployment/httpbin -c istio-proxy -- /usr/local/bin/envoy --version` reports the same istio/proxy SHA as we see in the metadata.  Do we need someone from @istio/wg-test-and-release-maintainers to change the build to incorporate that SHA into the image?

Would it make sense for the output of `istioctl pc bootstrap <pod>` to say something like

```
Istio Proxy Version: 1.8-alpha.165c5ccd74e319eff194cd13fddfeefa2c027d09 (SHA 74d763048fa1d983999e4d875b4146e53ea3ca17)
Envoy Version: 1.16.0-dev/Clean/RELEASE/BoringSSL
```

@abhide I am using a daily build of the 1.8 data plane.  When I run `istioctl pc bootstrap`, I see

```
                    "ISTIO_PROXY_SHA": "istio-proxy:74d763048fa1d983999e4d875b4146e53ea3ca17",
                    "ISTIO_VERSION": "1.8-alpha.165c5ccd74e319eff194cd13fddfeefa2c027d09",
```

and

```
            "userAgentBuildVersion": {
                "version": {
                    "majorNumber": 1,
                    "minorNumber": 16
                },
                "metadata": {
                        "build.label": "dev",
                        "build.type": "RELEASE",
                        "revision.sha": "74d763048fa1d983999e4d875b4146e53ea3ca17",
                        "revision.status": "Clean",
                        "ssl.version": "BoringSSL"
                    }
            },
```

**Comment by howardjohn** [comment]
Soon envoy-wasm will be upstreamed so I think we don't need to worry about
that distinction? I think the SHA (vs version) is mostly on useful on the
master branch.

**Comment by abhide** [comment]
Thanks @esnible I will make the changes to `istioctl pc bootstrap` command output and submit a PR.

**Comment by esnible** [comment]
@abhide Are you working on this?  If not, let's unassign you.

**Comment by ryantking** [comment]
I'm interested in taking this one

**Comment by ryantking** [comment]
This feature is added by https://github.com/istio/istio/pull/33359

Users can now access quick version info as follows:

```
$ istioctl proxy-config bootstrap -o short <POD>
Istio Version:       1.10.0
Istio Proxy Version: 436f365a8007cd8a13a9f1321e7cce94bcc8883e
Envoy Version:       1.18.3/Clean/RELEASE/BoringSSL
```

Closing this
