### ISSUE TITLE
IstioOperator InstallStatus serialization

### ISSUE THREAD

**Issue by esnible** [istio/istio#21518]
I followed the instructions to install using the operator from https://preliminary.istio.io/docs/setup/install/standalone-operator/

After I did the `kubectl apply` to create the demo profile, I did `kubectl -n istio-system describe istiooperator example-istiocontrolplane`

The status output was confusing:

```
Status:
  Component Status:
    Addon Components:
      Status:  3
    Base:
      Status:  3
    Egress Gateways:
      Status:  3
    Ingress Gateways:
      Status:  3
    Pilot:
      Status:  3
  Status:      3
```

According to https://istio.io/docs/reference/config/istio.operator.v1alpha12.pb/#InstallStatus-Status the possible statuses are the enum `NONE`, `UPDATING`, `HEALTHY`, `ERROR`, and `RECONCILING`.  I see `3` and I don't know what it means.

Can we force the status to serialize the enum as a string rather than an int?

Can we add to the InstallStatus-Status some information that would let me know the meaning of these fields (e.g. that `NONE` means not installed), and if we can't serialize as a string then would let me know which one is `3`?

**Comment by richardwxn** [comment]
same issue reported here:https://github.com/istio/istio/issues/21554
