### ISSUE TITLE
Istio 1.5-beta.3 pulls in Kiali 1.9.1 in demo profile

### ISSUE THREAD

**Issue by mtho11** [istio/istio#21526]
**Bug description**
An older version of Kiali is installed in the Istio 1.5.beta.3 build. It installs 1.9.1 and should be 1.13 instead.

![Kiali_Console_-_Firefox_Developer_Edition](https://user-images.githubusercontent.com/1312165/75371208-31538400-587b-11ea-94a8-5d6548dd7a45.png)

**Expected behavior**
It is expected to pull in Kiali 1.13 instead of the older 1.9.1

Related Kiali 1.13 PR: https://github.com/istio/istio/pull/20866

**Steps to reproduce the bug**
`istioctl dashboard kiali`
Then in Kiali click on the question mark in the upper right of the screen, then there will be an `About` menu item that will take you to the Kiali about page with version info.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
~/istio-1.5.0-beta.3 istioctl version                                                                   09:32:59
client version: 1.5.0-beta.3
control plane version: 1.5.0-beta.3
data plane version: 1.5.0-beta.3 (15 proxies)
```

**How was Istio installed?**
`istioctl manifest apply --set profile=demo`

**Comment by jmazzitelli** [comment]
I'm about to submit a PR for this
