### ISSUE TITLE
istioctl --installPackagePath not working like before - how to test local manifest changes?

### ISSUE THREAD

**Issue by jmazzitelli** [istio/istio#21530]
**Bug description**

After making some changes to the manifests/, I'd like to locally test those changes, but since the monorepo work finished, the `istioctl --installPackagePath` option isn't working for me (I can't just point to my local repo anymore and get istioctl to install with my local changes).

How do you now test istioctl with local changes?

[ ] Configuration Infrastructure
[ ] Docs
[x ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Be able to run "istioctl" but yet have it pull in local changes to my manifests/ so I can test locally before submitting PRs.

**Steps to reproduce the bug**

Make changes to a manifest/, run `make gen` to do whatever else you need to submit a PR to make changes to the istioctl stuff.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

1.5.0.beta3

**How was Istio installed?**

It isn't. That's what I'm trying to test - changes to istioctl manifests.

**Environment where bug was observed (cloud vendor, OS, etc)**

n/a

**Comment by hb-chen** [comment]
Release version `1.5.0`,  with `--set installPackagePath={charts-path}` to use external charts.
But it doesn't work.

```
istioctl manifest generate \
--set installPackagePath={charts-path} \
> generate-default.yaml
```

**Comment by hb-chen** [comment]
> Release version `1.5.0`, with `--set installPackagePath={charts-path}` to use external charts.
> But it doesn't work.
> 
> ```
> istioctl manifest generate \
> --set installPackagePath={charts-path} \
> > generate-default.yaml
> ```

Should use  replace `installPackagePath ` with `install_package_path`.
And must set `profile` at the same time, or while get error:
```
Error: open {install_package_path}/profiles/default.yaml: no such file or directory
```

Use it correctly like this:
```
istioctl manifest generate \
--set profile=$PWD/install/kubernetes/operator/profiles/default.yaml \
--set install_package_path=$PWD/install/kubernetes/operator/charts \
> gen.yaml
```
