### ISSUE TITLE
TCP metrics for BlackHole clusters does not work with Telemetry v2

### ISSUE THREAD

**Issue by jacob-delgado** [istio/istio#21566]
**Bug description**

This is related to https://github.com/istio/istio/issues/21385, but is considered a separate issue.

TCP metrics for BlackHoleClusters are not created when a listener is not matched and `virtualOutbound` listener is used.

**Expected behavior**

The stats filter used in Telemetry V2 should create TCP metrics with labels containing BlackHoleClusters when no listener is matched and `virtualOutbound` is used.

**Steps to reproduce the bug**

1. `kubectl apply -f <(istioctl kube-inject -f samples/sleep/sleep.yaml)`
2. `kubectl apply -f <(istioctl kube-inject -f samples/httpbin/httpbin.yaml)`
3. Run `kubectl exec $(kubectl get pod -l app=sleep -o jsonpath={.items..metadata.name}) -c sleep -- curl -v httpbin:8001/status/200` a few times
4. Port forward envoy from the sleep pod, `kubectl port-forward $(kubectl get pod -l app=sleep -o jsonpath={.items..metadata.name}) 15000`
5. Open http://localhost:15000/stats/prometheus
6. There are no metrics for tcp connections that contain labels with BlackHoleCluster

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

client version: 1.5.0-beta.3
control plane version: 1.5.0-beta.3
data plane version: 1.5.0-beta.3 (4 proxies)

Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-13T18:06:54Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.9", GitCommit:"2e808b7cb054ee242b68e62455323aa783991f03", GitTreeState:"clean", BuildDate:"2020-01-18T23:24:23Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**

`istioctl manifest apply --set values.global.outboundTrafficPolicy.mode=REGISTRY_ONLY`

**Environment where bug was observed (cloud vendor, OS, etc)**

Kops created cluster on AWS running K8s v1.15.9.

**Comment by jacob-delgado** [comment]
cc @nrjpoddar

**Comment by nrjpoddar** [comment]
@mandarjog @douglas-reid @bianpengyuan assigned this bug to Nupur, we should add this also as a blocker for 1.5. Thanks!

**Comment by gargnupur** [comment]
@jacob-delgado , @nrjpoddar : can I get a config dump of the proxy pod?

**Comment by jacob-delgado** [comment]
[proxy-config.tar.gz](https://github.com/istio/istio/files/4259668/proxy-config.tar.gz)

@gargnupur is this enough?

**Comment by gargnupur** [comment]
@jacob-delgado : do you see TCP metrics? The config looks right to me, so looks like a label issue then...

**Comment by gargnupur** [comment]
@jacob-delgado , @nrjpoddar : even this looks relevant. https://github.com/istio/istio/issues/15867 -> in Telemetry V2, metadata exchange starts on onData calls, but if envoy sees it as BlackHoleCluster , then it should get reported atleast at source/destination side..

**Comment by gargnupur** [comment]
Also Mixer did special casing to add BlackHoleCluster in destination service name in "addVirtualDestinationServiceAttributes" function.
Is HTTP working fine?

**Comment by jacob-delgado** [comment]
> @jacob-delgado : do you see TCP metrics? The config looks right to me, so looks like a label issue then...

I did not see any related TCP metrics on the source (sleep) side. 

> Also Mixer did special casing to add BlackHoleCluster in destination service name in "addVirtualDestinationServiceAttributes" function.
> Is HTTP working fine?

HTTP metrics are broken and more info can be found at https://github.com/istio/istio/issues/21385.

**Comment by kyessenov** [comment]
So @gargnupur investigated deeper into this, and it looks like a change in how envoy treats empty clusters. It effectively considers them unhealthy and immediately stops proxying. That means filter cannot distinguish between blackhole cluster encoding and any other cluster that has no hosts, has no healthy hosts, has overflown, or has retried too often.

**Comment by gargnupur** [comment]
Verified metrics are there with destination_service_name set to BlackHoleCluster

# TYPE istio_tcp_sent_bytes_total counter
istio_tcp_sent_bytes_total{reporter="source",source_workload="sleep",source_workload_namespace="default",source_principal="unknown",source_app="sleep",source_version="unknown",destination_workload="unknown",destination_workload_namespace="unknown",destination_principal="unknown",destination_app="unknown",destination_version="unknown",destination_service="unknown",destination_service_name="BlackHoleCluster",destination_service_namespace="unknown",request_protocol="tcp",response_flags="UH",connection_security_policy="unknown",source_canonical_service="sleep",destination_canonical_service="unknown",source_canonical_revision="latest",destination_canonical_revision="latest"} 0
# TYPE istio_tcp_received_bytes_total counter
istio_tcp_received_bytes_total{reporter="source",source_workload="sleep",source_workload_namespace="default",source_principal="unknown",source_app="sleep",source_version="unknown",destination_workload="unknown",destination_workload_namespace="unknown",destination_principal="unknown",destination_app="unknown",destination_version="unknown",destination_service="unknown",destination_service_name="BlackHoleCluster",destination_service_namespace="unknown",request_protocol="tcp",response_flags="UH",connection_security_policy="unknown",source_canonical_service="sleep",destination_canonical_service="unknown",source_canonical_revision="latest",destination_canonical_revision="latest"} 0
# TYPE istio_tcp_connections_opened_total counter
istio_tcp_connections_opened_total{reporter="source",source_workload="sleep",source_workload_namespace="default",source_principal="unknown",source_app="sleep",source_version="unknown",destination_workload="unknown",destination_workload_namespace="unknown",destination_principal="unknown",destination_app="unknown",destination_version="unknown",destination_service="unknown",destination_service_name="BlackHoleCluster",destination_service_namespace="unknown",request_protocol="tcp",response_flags="UH",connection_security_policy="unknown",source_canonical_service="sleep",destination_canonical_service="unknown",source_canonical_revision="latest",destination_canonical_revision="latest"} 2
# TYPE istio_tcp_connections_closed_total counter
istio_tcp_connections_closed_total{reporter="source",source_workload="sleep",source_workload_namespace="default",source_principal="unknown",source_app="sleep",source_version="unknown",destination_workload="unknown",destination_workload_namespace="unknown",destination_principal="unknown",destination_app="unknown",destination_version="unknown",destination_service="unknown",destination_service_name="BlackHoleCluster",destination_service_namespace="unknown",request_protocol="tcp",response_flags="UH",connection_security_policy="unknown",source_canonical_service="sleep",destination_canonical_service="unknown",source_canonical_revision="latest",destination_canonical_revision="latest"} 2

@jacob-delgado , @nrjpoddar , @mandarjog : Am closing the bug, but please re-open if something doesn't look right...
