### ISSUE TITLE
Routing rule sleepWindow clarification

### ISSUE THREAD

**Issue by vadimeisenbergibm** [istio/istio#2156]
According to https://istio.io/docs/reference/config/traffic-rules/destination-policies.html#simplecircuitbreakerpolicy 

> any host that fails 7 consecutive times with 5XX error code will be ejected for 15 minutes.

That means that the circuit will be opened = no new connections for 15 minutes.

> Minimum time the circuit will be **closed**.

Is the intention that the circuit will be open = no new connections?

**Comment by rshriram** [comment]
this was fixed
