### ISSUE TITLE
Debug interface `ConfigDump`  data race

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#21575]
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/21391/unit-tests_istio/9253

There is very little possibility, but not critical even r/w races. Just open this to trace.

**Comment by howardjohn** [comment]
Another failure, not a data race: https://prow.istio.io/view/gcs/istio-prow/logs/unit-tests_istio_postsubmit/1587
