### ISSUE TITLE
Support for Helm 3

### ISSUE THREAD

**Issue by hazcod** [istio/istio#21572]
**Bug description**
Helm 3 is not officially supported according to the docs: https://istio.io/docs/setup/install/helm/#prerequisites

[ ] Configuration Infrastructure
[ ] Docs
[X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Use latest & greatest version of Helm, which is used in e.g. terraform-helm provider.

**Steps to reproduce the bug**
Install istio.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
latest

**Comment by Stratouklos** [comment]
Has anyone actually tried? I just installed Istio 1.5.1 using the Terraform helm provider which is using helm3, I literally had to change nothing for our setup to work. I imagine there's a ton of corner cases when upgrading but for us just getting the cluster bootstrapped consistently from nothing is enough.

**Comment by Stratouklos** [comment]
See [this post](https://discuss.istio.io/t/istios-helm-support-in-2020/5535) for more information on what's happening with Helm and Istio

**Comment by howardjohn** [comment]
Helm 3 is unofficially supported now: https://github.com/istio/istio/blob/master/manifests/charts/README-helm3.md

**Comment by howardjohn** [comment]
Not stale

**Comment by howardjohn** [comment]
This is added in https://preliminary.istio.io/latest/docs/setup/install/helm/! For 1.8.

https://github.com/istio/istio/issues/27147 tracks promoting this to beta. Thanks everyone
