### ISSUE TITLE
All external HTTPS traffic are blocked abnormally and no access log when REGISTRY_ONLY is used

### ISSUE THREAD

**Issue by morvencao** [istio/istio#21579]
**Bug description**

This issue is not similar to https://github.com/istio/istio/issues/16458
1. Deploy istio-1.4.5 with `REGISTRY_ONLY` outboundTrafficPolicy mode and open access log for istio sidecar.
```
istioctl manifest apply --set values.global.proxy.accessLogFile="/dev/stdout" --set values.global.outboundTrafficPolicy.mode="REGISTRY_ONLY"
```

2. Then deploy sleep app in namespace with label `istio-injection=enabled`(enable auto-injection):
```
# kubectl -n istio-lab get pod
NAME                    READY   STATUS    RESTARTS   AGE
netshoot                2/2     Running   0          17m
sleep-f8cbf5b76-96559   2/2     Running   0          6m47s
```

3. Try to access external HTTPs service, the traffic is blocked and no entry in access log of istio sidecar:
```
# kubectl -n istio-lab exec -it sleep-f8cbf5b76-96559 -c sleep -- sh
/ # curl -v https://www.google.com/
* Expire in 6 ms for 1 (transfer 0x56195987f680)
*   Trying 172.217.1.132...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x56195987f680)
* Connected to www.google.com (172.217.1.132) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to www.google.com:443
* Closing connection 0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to www.google.com:443
```

4. But if I access the HTTP service, it return `502` and there will be new entry in access log of istio sidecar:
```
# kubectl -n istio-lab exec -it sleep-f8cbf5b76-96559 -c sleep -- sh
/ # curl -v http://httpbin.org/
* Expire in 0 ms for 6 (transfer 0x5634dec88680)
* Expire in 7 ms for 1 (transfer 0x5634dec88680)
*   Trying 34.230.193.231...
* TCP_NODELAY set
* Expire in 149988 ms for 3 (transfer 0x5634dec88680)
* Expire in 200 ms for 4 (transfer 0x5634dec88680)
* Connected to httpbin.org (34.230.193.231) port 80 (#0)
> GET / HTTP/1.1
> Host: httpbin.org
> User-Agent: curl/7.64.0
> Accept: */*
>
< HTTP/1.1 502 Bad Gateway
< location: http://httpbin.org/
< date: Thu, 27 Feb 2020 11:57:39 GMT
< server: envoy
< content-length: 0
<
* Connection #0 to host httpbin.org left intact
```

access logs only have HTTP traffic:
```
2020-02-27T11:51:43.100175Z	info	Envoy proxy is ready
[2020-02-27T11:57:39.883Z] "GET / HTTP/1.1" 502 - "-" "-" 0 0 0 - "-" "curl/7.64.0" "60b63a38-165d-4bee-9d48-4f7caf9a44ac" "httpbin.org" "-" - - 34.230.193.231:80 10.244.0.13:41528 - -
```

I found an issue:  https://github.com/istio/istio/issues/16458
But this should not similar to that, and I double checked all the services in my cluster, no `443` port with name prefix `http`.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

I thought that HTTPS and HTTP traffic should share the same behavior: return `502` status code if no service entry defined, but it seems HTTPS traffic is blocked by others. 
Besides, for the failing HTTPS traffic, it should also be shown in access log of istio sidecar, just like HTTP traffic.

**Steps to reproduce the bug**
See description above.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
# istioctl version
client version: 1.4.5
control plane version: 1.4.5
data plane version: 1.4.5 (3 proxies)
```
**How was Istio installed?**
```
istioctl manifest apply --set values.global.proxy.accessLogFile="/dev/stdout" --set values.global.outboundTrafficPolicy.mode="REGISTRY_ONLY"
```

**Environment where bug was observed (cloud vendor, OS, etc)**

Kind

**Comment by howardjohn** [comment]
can you post config dump

**Comment by howardjohn** [comment]
There is no guarantee that a 502 response code will be returned in HTTP, its only if there happens to already be config on that port. Send a request to another port like 4567 or something and I think youll see the same. In order to handle this we would need to add sniffing on virtual outbound @rshriram @yxue

**Comment by morvencao** [comment]
Correct, send to traffic on other ports will also get 502, and we can see the request and response in the access log.

**Comment by howardjohn** [comment]
Can you test this with master? I am pretty sure this is fixed now. See https://github.com/istio/istio/issues/16458. If not please reopen
