### ISSUE TITLE
Webhook integration tests are failing on release-1.5

### ISSUE THREAD

**Issue by dgn** [istio/istio#21574]
See https://prow.istio.io/view/gcs/istio-prow/logs/integ-k8s-115_istio_release-1.5_postsubmit/185 for an example.

The cause seems to be this PR: https://github.com/istio/istio/pull/21245, but the nature of failures has changed over time with @ayj attempting to (and partially successfully) fix it

Note that these tests are run against the helm charts in `install/`

fyi @ayj

**Comment by ayj** [comment]
cc @maasen

**Comment by dgn** [comment]
They're passing since my PR was merged. Closing
