### ISSUE TITLE
Fix non-ascii characters which are written accidentally

### ISSUE THREAD

**Issue by gavinfish** [istio/istio#21581]
**Bug description**

Some non-ascii characters are accidentally introduced into codebase.

**Expected behavior**

No unnecessary non-ascii characters.

**Steps to reproduce the bug**

Step to detect possible affected files like:
```
$ file operator/**/**
operator/cmd/mesh/manifest-apply.go: UTF-8 Unicode text
......
```

Step to check whether the no-ascii characters are introduced by accident.
```
$ iconv -c -f UTF-8 -t ASCII operator/cmd/mesh/manifest-apply.go > manifest-apply.go
$ diff operator/cmd/mesh/manifest-apply.go manifest-apply.go
```

Correct the characters if necessary.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
I have confirmed the only occurrences now are two intentional ones:

```
$ file manifests/**/** | rg UTF
manifests/charts/istio-telemetry/grafana/dashboards/istio-service-dashboard.json:            UTF-8 Unicode text, with very long lines
manifests/charts/istio-telemetry/grafana/dashboards/istio-workload-dashboard.json:           UTF-8 Unicode text, with very long lines
```

thanks for the tip!
