### ISSUE TITLE
ingress-gateway takes very long to become ready

### ISSUE THREAD

**Issue by dgn** [istio/istio#21585]
**Bug description**
The ingress-gateway pod takes ~90s to become ready after deploying a control plane using the legacy helm charts

**Expected behavior**
ingress-gateway pod becomes ready quicker, comparable with istioctl install

**Steps to reproduce the bug**
Installing using helm charts under `install/`

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.5.0-beta.3

**How was Istio installed?**
Installing using helm charts under `install/`

**Environment where bug was observed (cloud vendor, OS, etc)**
kind

**Comment by howardjohn** [comment]
k8s takes a while to update file mounts. This is only at installation, right? if you start a new instances later it comes up quickly?

If so it's not regression, this is one of the motivations for istiod

**Comment by howardjohn** [comment]
That's my guess at least, it could always be something new

**Comment by dgn** [comment]
yeah only at first startup. it's fixed by making the secret mount required, so have ingress-gateway wait for the secret, no istiod required
