### ISSUE TITLE
Strange looking envoy build metrics

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#21589]
I am not sure if this is expected, it looks pretty weird? The gateway is reporting metrics like:
```
envoy_6_alpha_587f118ac5da159d492712a5880e7948494bf532___istio_build{component="proxy",tag="1"} 1
```

**Comment by douglas-reid** [comment]
@howardjohn regex issue. i assume the tag is something like `1.6.alpha.587f118ac5da159d492712a5880e7948494bf532` ?

**Comment by howardjohn** [comment]
Yeah its `1.6-alpha.587f118ac5da159d492712a5880e7948494bf532`.

**Comment by douglas-reid** [comment]
I think this is a one character fix. just trying to confirm before I send the PR.
