### ISSUE TITLE
TestProxyConfig test flake

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#21591]
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/21559/integ-pilot-k8s-tests_istio/8893 is one example, I have seen this a few times. Somehow the pod is not found, yet if you look at the artifacts it seems like the pod should be there?

**Comment by esnible** [comment]
I have a working theory.  The `--namespace` CLI option sets a module-level variable.  The test has `RunParallel()`.  It is possible that another test changed the namespace out from under `proxy-config` after the pod was created but before we look it up.

I was unable to reproduce this when we discussed this a few weeks ago using my test clusters.

I propose that I add a bit of logging that will show the problem, and is there a way to mark the test as not failing the integration if it fails during this collection period?

If that is the problem, I see three possible mitigations.

- I can change the `RunParallel()` to `Run()`.  That seems like it would slow everyone down.
- I can have `proxy-config` use a local variable for the namespace.
- The ideal mitigation is to refactor the package-level `namespace` CLI field out of `"istio.io/istio/istioctl/cmd` but that will require changing nearly every CLI command.

Which would you recommend?

**Comment by howardjohn** [comment]
2 seems like a weird special case just to fix this, but I am not that familiar with the code. 1 seems reasonable for the short term (or, maybe, the "short" term :slightly_smiling_face:), most tests are already not run in parallel.

I have thought about the same where a test runs but doesn't actually fail but I haven't found a way to actually get it working. You can always remove the `t.Error` stuff though but its not a great solution

**Comment by howardjohn** [comment]
Ill send a quick fix for 1 in the meantime since this is failing fairly often
