### ISSUE TITLE
Document the required cluster size to execute the bookinfo demo

### ISSUE THREAD

**Issue by ahmetb** [istio/istio#216]
I had a 3-instance (default machine-size) GKE cluster and started to see scheduling failures after deploying:

- istio and grafana by copy-pasting https://istio.io/docs/tasks/installing-istio.html
- bookinfo app: https://istio.io/docs/samples/bookinfo.html

I was seeing

```
Events:
  FirstSeen	LastSeen	Count	From						SubObjectPath				Type		Reason			Message
  ---------	--------	-----	----						-------------				--------	------			-------
  11m		2m		36	default-scheduler									Warning		FailedScheduling	No nodes are available that match all of the following predicates:: Insufficient cpu (3)
```

I had to increase the node count to 4 to accommodate.

It would be preferable if the tutorial started with a "Before you begin" section telling me exactly what I need. I had to figure this out myself.

**Comment by kyessenov** [comment]
ref https://github.com/istio/manager/issues/608

**Comment by andraxylia** [comment]
Fixed in istio/istio.github.com#198
