### ISSUE TITLE
Data race in TestConfigDump/dumps_most_recent_proxy_with_200 

### ISSUE THREAD

**Issue by stewartbutler** [istio/istio#21606]
Race condition encountered in TestConfigDump/dumps_most_recent_proxy_with_200  in the unit tests of https://github.com/istio/istio/pull/21531 (Run https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/21531/unit-tests_istio/9309).

It looks like that test was modified yesterday in https://github.com/istio/istio/pull/21509. I'm assigning to @hzxuzhonghu for triage.

**Bug description**

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by hzxuzhonghu** [comment]
fixed
