### ISSUE TITLE
NET_RAW requirement

### ISSUE THREAD

**Issue by chenwng** [istio/istio#21625]
**Bug description**

In RPs related to #17318, NET_RAW was added in the capabilities list. But in https://istio.io/docs/ops/deployment/requirements/, it is still only NET_ADMIN listed as required. Can anyone please clarify why we need NET_RAW here? 

Thanks.

**Comment by howardjohn** [comment]
I think this may have always been needed but was not documented @rlenglet may be able to elaborate on this

**Comment by rlenglet** [comment]
Yes, `CAP_NET_RAW` was always needed. It is one of the capabilities added by default by Docker and any container runtime, cf. https://github.com/moby/moby/blob/38f52c9fec820cece6c51d65a161648347fb2ee1/oci/caps/defaults.go#L11.
When we dropped `ALL` capabilities, we had to re-add `CAP_NET_RAW` explicitly.

**Comment by rlenglet** [comment]
I will submit a PR to update the docs. Thanks!

**Comment by chenwng** [comment]
Thanks!
