### ISSUE TITLE
analyzer_test is failing in postsubmit tests on release-1.5

### ISSUE THREAD

**Issue by dgn** [istio/istio#21633]
Example: https://prow.istio.io/view/gcs/istio-prow/logs/integ-k8s-115_istio_release-1.5_postsubmit/205

The failing tests were introduced as part of this PR: https://github.com/istio/istio/pull/21561/

Note that we're running the postsubmit tests using the helm charts in `install/` - they seem to pass when deploying using `istioctl`.

fyi @selmanj

**Comment by dgn** [comment]
Looks like the helm charts will always create MeshPolicy resources. Not sure how this is compatible with us deprecating MeshPolicy

**Comment by dgn** [comment]
Working on a fix

**Comment by selmanj** [comment]
Is the fix to remove MeshPolicy resources? I was under the impression that new installs of 1.5 wouldn't create MeshPolicy resources.

IMO, if MeshPolicy resources will exist, we should revert #21561

**Comment by selmanj** [comment]
CC @diemtvu

**Comment by diemtvu** [comment]
Helm installation is also expected to be deprecated, that's why we didn't make the change there.

**Comment by dgn** [comment]
@selmanj @diemtvu I submitted PRs now to suppress the warning in case of deployments using helm charts.

**Comment by dgn** [comment]
Postsubmits are passing now
