### ISSUE TITLE
Testing framework docker supports multi workloads in docker env

### ISSUE THREAD

**Issue by incfly** [istio/istio#21656]
This is a TODO item in the introducing of the workloads in a single echo instance as part of https://github.com/istio/istio/pull/21369.

I'll log the specific error message once i got it here.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ X] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by ericvn** [comment]
Has anything been done for this? If not, what needs to be done?

**Comment by howardjohn** [comment]
We have removed docker env
