### ISSUE TITLE
Inconsistent default discovery ports

### ISSUE THREAD

**Issue by ijsnellf** [istio/istio#2168]
The default discovery port values are different between Pilot discovery and agent:
https://github.com/istio/istio/blob/master/pilot/proxy/context.go#L138
https://github.com/istio/istio/blob/master/pilot/cmd/pilot-discovery/main.go#L88

The ports should be consistent so that the default configuration could work.

**Comment by ijsnellf** [comment]
May have contributed to https://github.com/istio/istio/issues/2168

**Comment by GregHanson** [comment]
intended design is to always have an instance of envoy proxy running with a hardcoded config in front of pilot-discovery listening on port 15003 and forwarding calls to the discovery server on port 8080 to handle the possibility of mTLS between the pilot-agent instances and pilot-discovery. Related design doc: https://docs.google.com/document/d/1LE7dbCQrhuvbxJuyV5sKlYLCtv0g9jfhteFIL06XCbI/edit#heading=h.x9snb54sjlu9
