### ISSUE TITLE
Istio Agent shouldn't close connection when rotating cert.

### ISSUE THREAD

**Issue by myidpt** [istio/istio#21680]
**Bug description**
Istio Agent shouldn't close connection when rotating the workload cert. This was needed for Node Agent when Node Agent retrieved the JWT remotely via the SDS reconnection. Now we can remove it, since reconnection has performance impact.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ X ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
https://github.com/istio/istio/pull/21330 is a start, not sure if it covers all cases

**Comment by howardjohn** [comment]
not stale
