### ISSUE TITLE
TestRenewToken test flake

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#21684]
https://prow.istio.io/view/gcs/istio-prow/logs/unit-tests_istio_postsubmit/1626

**Comment by JimmyCYJ** [comment]
The root cause is the same as https://github.com/istio/istio/issues/21626. Need to fix the racing condition to deflake both tests.

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gcs/istio-prow/logs/unit-tests_istio_postsubmit/2028

**Comment by JimmyCYJ** [comment]
This is still the SSL handshake issue. I am trying to reproduce it. 
E0406 21:47:08.948987820    8236 ssl_transport_security.cc:1246] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
