### ISSUE TITLE
istioctl backwards compatibility not working (stack trace)

### ISSUE THREAD

**Issue by Stono** [istio/istio#21683]
**Bug description**
As per https://preliminary.istio.io/docs/setup/install/istioctl/, it says:

> For backwards compatibility, the previous Helm installation options are also fully supported. To set them on the command line, prepend the option name with “values.”. For example, the following command overrides the pilot.traceSampling Helm configuration option:

However if i edit my `1.5.0-beta.4/install/kubernetes/helm/istio/values.yaml` and nest everything under a `values:` block as it suggests, I get a stack trace:

```
❯ ./1.5.0-beta.4/bin/istioctl manifest generate -f 1.5.0-beta.4/install/kubernetes/helm/istio/values.yaml
proto: tag has too few fields: "-"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x88 pc=0x29726b6]

goroutine 1 [running]:
istio.io/istio/operator/pkg/validate.CheckIstioOperatorSpec(0x0, 0xc000463300, 0x0, 0x0, 0x6)
        istio.io/istio@/operator/pkg/validate/validate.go:41 +0x26
istio.io/istio/operator/pkg/validate.ValidIOP(0xc000463380, 0x1114, 0xc000463380)
        istio.io/istio@/operator/pkg/validate/common.go:294 +0x38
istio.io/istio/operator/cmd/mesh.parseYAMLFiles(0xc00077cac0, 0x1, 0x1, 0x3640a00, 0xc000a95d48, 0xc0001b4fc0, 0xc0001b51c0, 0xc0001b5220, 0x3640a78, 0x39365e0, ...)
        istio.io/istio@/operator/cmd/mesh/profile-common.go:91 +0xd3
istio.io/istio/operator/cmd/mesh.GenerateConfig(0xc00077cac0, 0x1, 0x1, 0x0, 0x0, 0xc000a95c00, 0x0, 0xc000a95d48, 0x0, 0x0, ...)
        istio.io/istio@/operator/cmd/mesh/profile-common.go:59 +0x73
istio.io/istio/operator/cmd/mesh.GenManifests(0xc00077cac0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0xc000a95d48, 0x0, 0x16da802, ...)
        istio.io/istio@/operator/cmd/mesh/manifest-generate.go:125 +0x9a
```

**Expected behavior**
To be able to use istioctl with my existing helm values as per the doco.

**Steps to reproduce the bug**
Can provide my installation config on slack - ping me.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.5.0-beta4

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
i think @esnible had PR out to fix this this? Might be  different one though

**Comment by esnible** [comment]
Should be fixed by https://github.com/istio/istio/pull/21653

Merged to master 2 days ago, waiting for https://github.com/istio/istio/pull/21666

**Comment by Stono** [comment]
Closing, this doesn't stack trace for me any more with 1.5.0-beta5
