### ISSUE TITLE
istio/proxy: ability to expose custom attributes from peer node metadata with Telemetry V2

### ISSUE THREAD

**Issue by martonsereg** [istio/istio#21698]
**Describe the feature request**

Per the documentation of [Configurable V2 Metrics](https://github.com/istio/istio/wiki/Configurable-V2-Metrics#expressions-used-for-values), along the standard Envoy attributes, a few extra attributes are exposed that can be used in metrics label values. 
From that list I’m missing any custom attributes regarding peer node metadata.

For us, this would come in handy to expose cluster information as metric labels when using V2 telemetry in a multi-cluster environment, so we could see *cluster-level metrics* of service-to-service communication.

From the code it seems that there’s a customizable `PLATFORM_METADATA` field among the Envoy node metadata that we could use for these purposes.
It gets marshalled to proto during `metadata exchange` along with other info like what was the peer pod. Because of that, if I understand correctly, `PLATFORM_METADATA` should be available in the `stats plugin` where the proxy code builds the metric dimensions, so it could quite “easily” be added as an attribute for custom metrics.

It’d be great if it could be exposed as a configurable attribute for Metrics V2 as something like `peer_platform_metadata`.

**Describe alternatives you've considered**

I couldn't really see any other way of exposing cluster info as metric labels, other than fork the stats plugin and code it ourselves, but we'd rather avoid having to maintain a fork.

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [X] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Additional context**

We're providing cluster-level metric information for shared control plane multi-cluster meshes as part of the Banzai Cloud Backyards product with Telemetry V1, but want to have the same information available with Telemetry V2.

We'd also be happy to contribute back and open a PR, if we could decide what would be the proper way of implementing it.

**Comment by kyessenov** [comment]
/cc @kyessenov 
This is the issue about protobuf preventing easy inspection into peer metadata. We are considering [flatbuffers](https://github.com/istio/proxy/pull/2673) instead.

**Comment by douglas-reid** [comment]
@kyessenov do we intend on having accessors to `peer_metadata` at the top-level, or to individual components of that metadata (`peer.platform_metadata["gcp_gke_cluster_name"]`, `peer.labels["foo"]`) ?

**Comment by mandarjog** [comment]
This is needed to make configurable telemetry feature complete compared with v1. So we do need to provide it.

**Comment by kyessenov** [comment]
Ref https://github.com/istio/proxy/pull/2794

**Comment by kyessenov** [comment]
This is in 1.7 and 1.8. Use "upstream_peer" and "downstream_peer" attributes.
