### ISSUE TITLE
Missing unit tests

### ISSUE THREAD

**Issue by ostromart** [istio/istio#21692]
- [ ] HPA spec in overlay (regression in 1.5 was missed)
- [ ] Supported/meaningful combinations of --set flags (also warn about unsupported combos?)
- [ ] charts/profiles in local file system
- [x] operator manifest generation parity with istioctl for all manifest generate test cases
- [ ] delete, recreate istio

**Comment by esnible** [comment]
Regarding "All combinations of --set flags", there are a lot of combinations that should be discouraged.  For example setting enabled=false for a component while customizing it.

There is an issue about that https://github.com/istio/istio/issues/20730

When you say "all combinations" do you mean all meaningful combinations?  If so, is anyone one working on determining what the valid combos are?

**Comment by esnible** [comment]
Related: https://github.com/istio/istio/issues/19458

**Comment by ostromart** [comment]
Yes I meant reasonable combinations but perhaps we should also go further and test that unsupported combinations are also rejected. We made a small start to this with the semantic validation framework and some example validations but there are probably lots of other meaningful validations that could be done here.

**Comment by ostromart** [comment]
Moving this to an epic: https://github.com/istio/istio/issues/21887
