### ISSUE TITLE
Telemetry v2 TCP metrics do not show up until connection closes

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#21690]
Not sure if this behavior is in Mixer as well. Basically my setup is:

fortio -> Gateway (TCP) -> application (HTTP)

![2020-01-03_16-54-41](https://user-images.githubusercontent.com/623453/75637821-85dd6300-5bdd-11ea-99a7-f172f3b07425.png)

You can see the blue/red lines are not increasing for 1 minute, then suddenly jump up. This corresponds with exactly when `fortio` exits and closes the connections.

This causes the dashboard tests to fail if we remove the TCP filter: https://github.com/istio/istio/blob/51bdcde7f3a4f65b3ba15fc64b5b307d39f327ab/tests/integration/telemetry/dashboard_test.go#L71

**Comment by howardjohn** [comment]
Full metrics (from another run)

```

istio_tcp_received_bytes_total{connection_security_policy="mutual_tls",destination_app="server",destination_canonical_revision="v1",destination_canonical_service="server",destination_principal="spiffe://cluster.local/ns/dashboard-1-16291/sa/default",destination_service="server.dashboard-1-16291.svc.cluster.local",destination_service_name="server",destination_service_namespace="dashboard-1-16291",destination_version="v1",destination_workload="server-v1",destination_workload_namespace="dashboard-1-16291",instance="10.244.0.16:15090",job="envoy-stats",namespace="dashboard-1-16291",pod_name="server-v1-548b4d6db7-cktl7",reporter="destination",request_protocol="tcp",response_flags="-",source_app="istio-ingressgateway",source_canonical_revision="latest",source_canonical_service="istio-ingressgateway",source_principal="spiffe://cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account",source_version="unknown",source_workload="istio-ingressgateway",source_workload_namespace="istio-system"} | 2180
-- | --
istio_tcp_received_bytes_total{connection_security_policy="none",destination_app="server",destination_canonical_revision="v1",destination_canonical_service="server",destination_principal="unknown",destination_service="mgmtCluster",destination_service_name="mgmtCluster",destination_service_namespace="dashboard-1-16291",destination_version="v1",destination_workload="server-v1",destination_workload_namespace="dashboard-1-16291",instance="10.244.0.16:15090",job="envoy-stats",namespace="dashboard-1-16291",pod_name="server-v1-548b4d6db7-cktl7",reporter="destination",request_protocol="tcp",response_flags="-",source_app="unknown",source_canonical_revision="latest",source_canonical_service="unknown",source_principal="unknown",source_version="unknown",source_workload="unknown",source_workload_namespace="unknown"} | 17967
istio_tcp_received_bytes_total{connection_security_policy="unknown",destination_app="server",destination_canonical_revision="v1",destination_canonical_service="server",destination_principal="spiffe://cluster.local/ns/dashboard-1-16291/sa/default",destination_service="server.dashboard-1-16291.svc.cluster.local",destination_service_name="server",destination_service_namespace="dashboard-1-16291",destination_version="v1",destination_workload="server-v1",destination_workload_namespace="dashboard-1-16291",instance="10.244.0.13:15090",job="envoy-stats",namespace="istio-system",pod_name="istio-ingressgateway-7d8db467bb-plk7r",reporter="source",request_protocol="tcp",response_flags="-",source_app="istio-ingressgateway",source_canonical_revision="latest",source_canonical_service="istio-ingressgateway",source_principal="spiffe://cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account",source_version="unknown",source_workload="istio-ingressgateway",source_workload_namespace="istio-system"} | 2180
```

1st and 3rd are from gateway, 2nd is the one from workload.

Why is `destination_service_name="mgmtCluster"`?

**Comment by gargnupur** [comment]
+ @bianpengyuan 
@howardjohn : For how long are connections run for? Default ticker timer for tcp metrics is 15s. Otherwise, they are all logged on connection close.

For destination_service_name, what is expected? This is the logic used to get destination service name:
Get destination service host and name based on destination cluster name and
// host header.
// * If cluster name is one of passthrough and blackhole clusters, use cluster
//   name as destination service name and host header as destination host.
// * If cluster name follows Istio convention (four parts separated by pipe),
//   use the last part as destination host; Otherwise, use host header as
//   destination host. To get destination service name from host: if destination
//   host is already a short name, use that as destination service; otherwise if
//   the second part of destination host is destination namespace, use first
//   part as destination service name. Otherwise, fallback to use destination
//   host for destination service name.

So looks like it's getting cluster name...

**Comment by howardjohn** [comment]
I am fairly sure it's not going through a cluster named mgmtCluster but I can investigate that more

As for the timing j had this for multiple minutes and it never ticked until the connection closed, so sounds like that is unexpected?

**Comment by gargnupur** [comment]
Yeah, what version are you on?
There was a timer fix... that went in.. : https://github.com/istio/proxy/pull/2733
Not sure if this has reached master

**Comment by howardjohn** [comment]
this was on master from Friday I think

**Comment by howardjohn** [comment]
I think it had that pr, let me try this again to make sure since it was updated around the same time I tried this

**Comment by gargnupur** [comment]
okay please let me know what you find...

**Comment by mandarjog** [comment]
@gargnupur regardless of the timing we should investigate why it is going thru the management cluster.

**Comment by howardjohn** [comment]
Ill verify its fixed and see if I can figure out the mgmtcluster

**Comment by howardjohn** [comment]
mgmtCluster = readiness probe, so that is expected (if we expect to get metrics here?). Access logs show the same thing, so the traffic is really going there.

I do still see the issue though with the metrics not appearing until connection close

**Comment by gargnupur** [comment]
This is fixed after https://github.com/istio/proxy/pull/2742
Logs from test: https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/21783/integ-telemetry-k8s-tests_istio/9195

**Comment by howardjohn** [comment]
This is fixed as proven by https://github.com/istio/istio/pull/21775
