### ISSUE TITLE
istiod CA does not support plugging in a CA certificate

### ISSUE THREAD

**Issue by lei-tang** [istio/istio#21696]
**Bug description**
When trying https://preliminary.istio.io/docs/tasks/security/citadel-config/plugin-ca-cert/, running "istioctl manifest apply --set values.global.mtls.enabled=true --set values.security.selfSigned=false" will not update the istiod deployment to read the plugged-in CA certificate. The istiod implementation in release-1.5 branch does not take the values.security.selfSigned parameter.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
"istioctl manifest apply --set values.global.mtls.enabled=true --set values.security.selfSigned=false" should update the istiod CA to read the plugged-in CA certificate.

**Steps to reproduce the bug**
https://preliminary.istio.io/docs/tasks/security/citadel-config/plugin-ca-cert/

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
Istio release 1.5 beta 4.

**How was Istio installed?**
istioctl in the Istio 1.5 release.

**Environment where bug was observed (cloud vendor, OS, etc)**
MacOS.

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by ayj** [comment]
cc @linsun

**Comment by linsun** [comment]
Thanks @ayj!  

@lei-tang because istiod auto discovers if the signing key file (ca-key.pem) exists so no need for user to configure security.selfSigned flag.

**Comment by myidpt** [comment]
You are right @linsun  I asked Lei to test if the following flow works:
1) Create the `istio-system` namespace
2) Generate a root key cert pair, and inject into the secret `cacert.istio-system`.
3) Deploy Istio control plane, and verify that the workloads are using the injected root.

**Comment by myidpt** [comment]
I think we need to give caveat that if the customer was using "istio-ca-secret" in 1.4, they need to copy it to "cacert", otherwise the upgrade will break their cluster, since istiod is no longer watching "istio-ca-secret".

**Comment by lei-tang** [comment]
https://preliminary.istio.io/docs/tasks/security/citadel-config/plugin-ca-cert/ is outdated. 
I am working on a PR to update the document of plugging in a CA cert https://preliminary.istio.io/docs/tasks/security/citadel-config/plugin-ca-cert/. The plugged in CA cert will be mounted to /etc/cacerts and I have tested it for Istio 1.5 beta 4. The PR will be created today for review.

**Comment by lei-tang** [comment]
https://github.com/istio/istio.io/pull/6644 is created to address this issue.
