### ISSUE TITLE
 Istio Policy Bot closes issues for lack of activity the moment I start working on them

### ISSUE THREAD

**Issue by esnible** [istio/istio#21703]
(I am filing this in istio/istio because https://github.com/istio/bots doesn't have an Issue tracker.  If this is the wrong place, let me know.)

Today I went to https://github.com/istio/istio/issues/18932 and changed the milestone.  Within 1 second the bot closed the issue "due to not having had activity from an Istio team member since 2019-11-13."  It isn't true ... just 1 second earlier there was activity.  I have had the same experience on other issues as well.

**Comment by brian-avery** [comment]
Hey @esnible are you still seeing this?

**Comment by esnible** [comment]
No.
