### ISSUE TITLE
Please don't report spans for mirror traffic

### ISSUE THREAD

**Issue by Stono** [istio/istio#21700]
**Bug description**
Hey, 
Please can we record spans for mirror traffic?   We use istios mirroring to warm some services which generates loads of noise in Jaeger:

<img width="1230" alt="Screenshot 2020-03-02 at 13 59 27" src="https://user-images.githubusercontent.com/1486729/75687278-76215580-5c95-11ea-99ce-57b7e1bdb946.png">

Metrics aren't recorded for mirror'd traffic so I don't think spans should be either.

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
Without thinking about it too in depth, it seems to me we actually would want all telemetry recorded (with some tag k suppose). Is the concern the mismatch with metrics or would you not like metrics for mirror traffic either?

I have no clue if it's feasible to add to mirror by the way just thinking about the expected behavior here

**Comment by Stono** [comment]
I don't want (and we currently don't get) metrics for mirror'd traffic.

https://istio.io/docs/tasks/traffic-management/mirroring

> Also, it is important to note that these requests are mirrored as “fire and forget”, which means that the responses are discarded.

Happy for metrics to be recorded as long as they're easy to exclude.  As a say, we use mirror to test or warm apps so wouldn't want our live consumer metrics (and traces) affected.

**Comment by kyessenov** [comment]
This is just how envoy does it. There are no extensions applied to mirrored traffic at all.
I think it's fair to add tracing span propagation at the very least, but that change has to go through envoy first.

**Comment by kyessenov** [comment]
Do you _want_ or _not want_ tracing spans for mirrored traffic? I think what happens is that the span headers are just verbatim copied, which is not what we want anyways.

**Comment by Stono** [comment]
I want to be able to disable them @kyessenov as they are pointless for us.   Copying is even worse haha so definitely fix that
