### ISSUE TITLE
Use file adapter in the Eureka sample

### ISSUE THREAD

**Issue by ijsnellf** [istio/istio#2170]
Use the file adapter for the Eureka sample and remove the k8s apiserver. This will simplify the sample and make setup easier and lighter weight. Update the sample and the docs.

**Comment by kyessenov** [comment]
Awesome. In the ideal world, we would have a matrix in three dimensions:
- registry (k8s, consul, eureka)
- config (k8s, file)
- feature (http/1.1, h2 routing)

We should be spin up a test across three dimensions, and get some reasonably functional coverage this way. For example, we could get consul/file/h2 tests gating pre-submit. Doing all possible combinations would be a non-goal, I think.
