### ISSUE TITLE
istioctl describe fails non-gracefully if pod is not part of the mesh

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#21710]
```
$ ~/istio/istio-1.5.0-beta.5/bin/istioctl x describe pod tiller-deploy-597765d7c-n5wkf.kube-system
Pod: tiller-deploy-597765d7c-n5wkf.kube-system
   Pod Ports: 44134 (tiller), 44135 (tiller)
WARNING: tiller-deploy-597765d7c-n5wkf.kube-system is not part of mesh; no Istio sidecar
--------------------
Error: failed to execute command on sidecar: error execing into tiller-deploy-597765d7c-n5wkf/kube-system istio-proxy container: container istio-proxy is not valid for pod tiller-deploy-597765d7c-n5wkf
```
It exits with error code 1

I was following the steps in https://preliminary.istio.io/docs/ops/diagnostic-tools/istioctl-describe/#verify-a-pod-is-in-the-mesh

**Comment by esnible** [comment]
@howardjohn `istioctl x describe` has a flag, `--ignoreUnmeshed`, which will suppress all of the message related to unmeshed pods.  The default is to return $? `1` when run on unmeshed pods.

Not a regression; the tool has always done this.

It is easy to suppress the second message and the `1` return, but should I?  I previously used that behavior to find problems with injection.  I could change the default of `--ignoreUnmeshed` to true and get the behavior you want.

Option?

**Comment by howardjohn** [comment]
> Not a regression; the tool has always done this.

In the docs, the output shows a warning. I don't have a strong opinion on the desired behavior, we should just make the doc represent what the tool is doing I guess. Failing with exit code `1` seems reasonable
