### ISSUE TITLE
Add post-install verification that control plane is functional

### ISSUE THREAD

**Issue by ostromart** [istio/istio#21715]
Currently, the operator and istioctl manifest apply --wait report healthy when resources have been applied/reconciled, they don't check that pods are in a healthy state and service state is as expected. This feature would check the health of the control plane in more detail.

**Comment by ayj** [comment]
cc @backward-compatible

**Comment by esnible** [comment]
We have the logic already in `istioctl verify-install -f $HOME/istio.yaml`.  It would be good to connect `appy` with `verify-install`.  There are some missing pieces as `verify-install` wants a manifest, and `apply` wants an ICP.

**Comment by esnible** [comment]
Also related is Erin Gannon's user interface study result, that users don't know exactly when they can start using Istio and what is available.  https://github.com/istio/istio/issues/20377

**Comment by esnible** [comment]
Now that we have a variant of `version` that uses XDS to determine the version, it would be trivial to put that into `manifest apply --wait` and `verify-install` to ensure that the XDS endpoint is functioning correctly.

The other common failure points are the webhooks.  Any thoughts on how we should test them?

**Comment by esnible** [comment]
@ostromart Is this on the Environments roadmap?
We put it on the UX roadmap.

It isn't clear if this work item is finished when Istiod reaches RUNNING, or if we should query XDS (similar to `experimental proxy-config`) to see if the control plane is serving XDS.

**Comment by esnible** [comment]
@howardjohn In addition to the current "Status verifier" (that the pods are present and running) I believe this requires a "liveness verifier".

It is easy to tell if the pods are live if I can exec or port-forward into them.  That seems insufficient for where we are headed with remote control planes.  Would it make sense for the implementation of a liveness test to dry-run a pod injection?  To look for XDS and ask it for config?  Or does this item not make sense in an external control plane environment?

**Comment by howardjohn** [comment]
For pods - if they are `Ready` that is a liveness check, I don't think we need anything beyond that (if we do, our readiness probe should be improved, not istioctl).

Trying to contact an external one is reasonable I suppose. You probably want to do the minimal possible, like a validation request or injection
