### ISSUE TITLE
no regex validation for negative lookahead

### ISSUE THREAD

**Issue by albertleung-da** [istio/istio#21717]
An existing `VirtualService` that had a negative lookahead regex caused the `RouteDiscoveryService` in pilot to fail. None of the routes were getting discovered, so service couldn't be accessed.

**Expected behavior**
Prior to finding out that Envoy has a new regex engine, I didn't expect route discovery in pilot to fail. This is because negative lookahead is supported in older versions of Istio on GKE. However, would also have appreciated a message in the logs that the configuration of the `VirtualService` was rejected.

Per a short exchange with @howardjohn on Slack, potentially may be useful to have validation of the regex that's submitted. (And thanks for the help!)

**Steps to reproduce**
Have a virtual service with the following regex inside a match rule:
```
 - match:
    - uri:
        regex: ^(?!.<path to match here>.).*
    retries:
      attempts: 3
      perTryTimeout: 2s
      retryOn: gateway-error,connect-failure,refused-stream
```

This results in the following error within the `discovery` container in pilot:

```
warn	ads	ADS:RDS: ACK ERROR <redacted connection ID> <redacted pod name> Internal:invalid perl operator: (?!
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
Kubectl versions:
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.9-gke.9", GitCommit:"a9973cbb2722793e2ea08d20880633ca61d3e669", GitTreeState:"clean", BuildDate:"2020-02-07T22:35:02Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```

Istio versions:
```
client version: 1.4.0
control plane version: 1.4.0
data plane version: 1.4.0 (1 proxies)
```

**How was Istio installed?**
I followed the documentation for installing Istio's default profile.
```
1. curl -L https://istio.io/downloadIstio | ISTIO-VERSION=1.4.0 sh -
2. cd into the istio directory
3. istioctl manifest apply 
```
Additionally this also exists in `1.4.5`

**Environment where bug was observed (cloud vendor, OS, etc)**
This is on GKE. The Istio addon was turned off before the manual installation.

**Comment by esnible** [comment]
If @istio/wg-networking-maintainers can give me guidance I can add validation so that `istioctl analyze` and/or `istioctl validate` issue warnings for Virtual Service regexs that are not compatible with Istio 1.5.

**Comment by howardjohn** [comment]
We can probably add a validation step to the webhook proper. I *think* golang regex is the same as envoy now (RE2) but not sure

**Comment by esnible** [comment]
@howardjohn I tried experiments using the valid regex `[A-Z]`, the invalid regex `[A-Z`, and the poster's regex `^(?!.<path to match here>.).*`.

Our webhook, `istioctl validate`, and `istioctl analyze` do not see this.  We SHOULD create validation for Virtual Service regexes.

regexp.MustCompile("^(?!.<path to match here>.).*")` panics with "error parsing regexp: invalid or unsupported Perl syntax".  That looks similar to the error reported here, so I am tempted to just have Go check the syntax for the initial MVP of the validation.

`istioctl proxy-status` correctly reported problems when using `^(?!.<path to match here>.).*`.  It seemed not to notice when using `[A-Z`, which is not expected, and deserves independent confirmation.  (Maybe I made some other mistake).

**Comment by esnible** [comment]
On the Networking Working Group today I learned that Istio's regexps now follow re2 syntax (see https://github.com/google/re2/wiki/Syntax )

Our documentation (e.g. https://preliminary.istio.io/docs/reference/config/networking/virtual-service/ ) says Istio uses "ECMAscript style regex".  Created https://github.com/istio/istio.io/issues/6749 to address the documentation.
