### ISSUE TITLE
update to golang protobuf v2

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#21729]
See https://blog.golang.org/a-new-go-api-for-protocol-buffers

**Comment by howardjohn** [comment]
Anything particularly useful? Looks like jsonpb interface improved a bit, but nothing else that impacts us too much. I am not suggesting we shouldn't update, just wondering if I missed anything

**Comment by kyessenov** [comment]
Dynamicpb could replace all the hand-written protobuf code we have in mixer. The important bit is that v1 is a dead-end and all the new development moves to v2.

**Comment by sdake** [comment]
We have a depreciation notice in 1.5 with a 6 month depreciation period. Is
this a problem?

**Comment by howardjohn** [comment]
protobuf v1 is still supported, should be no problem if there is security
vulns, etc that come up in the next 6 months
