### ISSUE TITLE
test framework: mixing of `t` and `ctx` leads to duplication and incorrect tests

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#21725]
Right now our tests have lot of nesting of tests. For example:

```go
	framework.
		NewTest(t).
		RequiresEnvironment(environment.Kube).
		Run(func(ctx framework.TestContext) {
				ctx.NewSubTest(c.name).Run(func(ctx framework.TestContext) {
```

There are many different `testing.T` and `framework.TestContext` in scope here, making it quite hard to figure out which one should be used. Generally tests just use a random one, which leads to bugs like selecting the parent `t`, causing issues.

We should refactor this in a way such that its hard to do the wrong thing. We also end up passing the same flag multiple times: `ingress.NewOrFail(ctx, ctx, c.ingressConfig)`, which could be fixed

**Comment by notpad** [comment]
I'll take this one
