### ISSUE TITLE
operator controller stuck in reconcile loop

### ISSUE THREAD

**Issue by ostromart** [istio/istio#21723]
Since 3/1 I'm seeing the controller get stuck reconciling the following resources:

2020-03-02T20:08:30.066093Z	info	The following objects differ between generated manifest and cache: 
 - CustomResourceDefinition::instances.config.istio.io
 - CustomResourceDefinition::handlers.config.istio.io

When I dump out the objects, the difference is that the CRD in the cluster has a validation field (OpenAPI schema) which is missing in the generated manifest. But it's not clear where this could be coming from. The sync fails because the objects are otherwise identical, which means that an overlay patch will not remove the schema fields.

**Comment by howardjohn** [comment]
related https://github.com/istio/istio/pull/21719

**Comment by ostromart** [comment]
Morven's change https://github.com/istio/istio/pull/21719 fixes the issue above, but this is only part of the problem. Even with the error above fixed in the PR, the controller is still stuck in the reconcile loop. Looking at the CR, it shows:
status:
  componentStatus:
    AddonComponents:
      status: 2
which I think is reconciling. So I think this problem is probably related to https://github.com/istio/istio/pull/21618.
