### ISSUE TITLE
Add support for configuring domain name suffix for cross cluster communication

### ISSUE THREAD

**Issue by aattuluri** [istio/istio#21721]
**Describe the feature request**
Currently, with multi-cluster installation of Istio (using values-istio-multicluster-intuit.yaml), the plumbing is set up to allow accessing services across the cluster with `global` suffix in istiocoredns, multicluster gateway & Envoy filter
The feature request is to make this configurable via values file using a single value(s).

**Describe alternatives you've considered**
Manually changing the files which requires editing a few places

**Additional context**
This request is for use cases from Intel and Intuit

**Comment by aattuluri** [comment]
@rshriram @howardjohn I would like to work on this if this makes sense.

**Comment by aattuluri** [comment]
@itohan-uk

**Comment by itohan-uk** [comment]
@aattuluri Is there a way to do this manually currently. I am currently trying to do this in my setup by modifying the rules but it does not work

**Comment by aattuluri** [comment]
@itohan-uk 
I have added the steps and the configuration to this gist:
https://github.intuit.com/gist/aattuluri/fd7f17776ba4248afdc6e74dcf03b91b

Try those steps and if you see errors, post them here.

**Comment by itohan-uk** [comment]
> @itohan-uk
> I have added the steps and the configuration to this gist:
> https://github.intuit.com/gist/aattuluri/fd7f17776ba4248afdc6e74dcf03b91b
> 
> Try those steps and if you see errors, post them here.

@aattuluri I cannot access the link. I see "The site can't be reached"

**Comment by aattuluri** [comment]
This was fixed with https://github.com/istio/istio/pull/27427
