### ISSUE TITLE
Remotely accessing telemetry results in error indications in Prometheus

### ISSUE THREAD

**Issue by sdake** [istio/istio#21720]
**Bug description**
I executed the task here: https://preliminary.istio.io/docs/tasks/observability/gateways/ (only the HTTP portion). While HTTP worked, it appears as though Prometheus has some form of error.

**Expected behavior**

No errors reported within Prometheus.

**Steps to reproduce the bug**

Follow the task. Open Chrome to port 15031 of the ingress gateway. Select `Status->Targets`.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.5.0 beta 5

**How was Istio installed?**
via standalone operator

**Environment where bug was observed (cloud vendor, OS, etc)**
K8s 1.17.2 Bare Metal + Metallb 0.8.3 + calico 3.8 via kubeadm

screenshot:
<img width="1440" alt="Screen Shot 2020-03-02 at 12 29 30 PM" src="https://user-images.githubusercontent.com/755849/75710315-98a97380-5c81-11ea-8ce3-f51d1a1f30a3.png">

PDF of prometheus page: 
[PrometheusTargets.pdf](https://github.com/istio/istio/files/4277487/PrometheusTargets.pdf)

**Comment by richardwxn** [comment]
seems like related: https://github.com/istio/istio/pull/20832?

**Comment by sdake** [comment]
The root cause of this is discussed in more detail in this thread: https://github.com/istio/istio/issues/21762#issuecomment-594026530

**Comment by sdake** [comment]
@dgn is this prioritized properly? This appears to be a regression in behavior. Istio 1.4 had no sidecar for Prometheus.
