### ISSUE TITLE
Various (related) issues with remote clusters in 1.5.0-beta.5

### ISSUE THREAD

**Issue by taylorreece** [istio/istio#21730]
**Bug description**
I'm following documentation in https://preliminary.istio.io/docs/setup/install/multicluster/shared-vpn/, and ran into various issues, both with documentation, and with deployment of a remote cluster in the same VPC/network as the control-plane cluster.  This might need to be broken into multiple tickets, but many of these issues seem related.

1. The `--set gateways.enabled=false` variable appears to be depricated, or at least `istioctl` spits out `Error: failed to generate tree from the set overlay, error: bad path=value: gateways.enabled=false`.  Setting `values.gateways.enabled=false` appears to be accepted by `istioctl`, but the ingressgateway is still created.  What key/value pair needs to be set to *not* create an ingress gateway?
2. Documentation references a remote pilot address, policy address, and telemetry address, but that should probably be consolidated into a single istiod address, right?  For now I'm using the control cluster's istiod pod IP address for all three values.
3. Despite the `--set values.global.createRemoteSvcEndpoints=true` and `--set values.global.remotePilotCreateSvcEndpoint=true` flags being set, the `istio-pilot.istio-system service` fails to create after doing an `istioctl manifest apply`.  Doing an `istioctl manifest generate` and running the output through `kubectl apply -f` yields the issue: `The Service "istio-pilot" is invalid: spec.clusterIP: Invalid value: "": field is immutable`.  Looking at the yaml,  it appears that the `istio-pilot.istio-system` is defined twice, once as a headless service for `istiod` from manifests/base/templates/services, and once from manifests/istio-control/istio-discovery/templates/service.yaml.
4. The `istiod` pod doesn't ever come up properly, but for other reasons.  It loops over an error like this
```
Error: failed to create discovery service: mesh: 1 error occurred:
	* invalid discovery address: unable to split "10.234.43.201": address 10.234.43.201: missing port in address
```
I believe this is because manifests/istio-control/istio-discovery/templates/configmap.yaml:284 (or so) reads something like `discoveryAddress: {{ .Values.global.remotePilotAddress }}` and should have a port at the end... something like 
```
      {{- if .Values.global.controlPlaneSecurityEnabled }}
      discoveryAddress: {{ .Values.global.remotePilotAddress }}:15011
      {{- else }}
      discoveryAddress: {{ .Values.global.remotePilotAddress }}:15010
      {{- end }}
```
Maybe?

**Expected behavior**
A functional remote cluster?

**Steps to reproduce the bug**
Follow https://preliminary.istio.io/docs/setup/install/multicluster/shared-vpn/

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
$ ./bin/istioctl version --remote
client version: 1.5.0-beta.5
control plane version: 1.5.0-beta.5
data plane version: 1.5.0-beta.5 (2 proxies)
```
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-502bfb", GitCommit:"502bfb383169b124d87848f89e17a04b9fc1f6f0", GitTreeState:"clean", BuildDate:"2020-02-07T01:31:02Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
Via `istioctl`

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS, but also seen in GCP.

Thanks in advance to anyone who pokes at this!

**Comment by howardjohn** [comment]
mentioning the usual suspects @ayj @nmittler

**Comment by richardwxn** [comment]
for your question 1, you can use --set values.gateways.istio-ingressgateway.enabled=false, or preferably run istioctl manifest apply -f with below
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
   components:
     ingressGateways:
      - name: istio-ingressgateway
        enabled: false
```
