### ISSUE TITLE
[pilot] Add Tracing to Pilot

### ISSUE THREAD

**Issue by nmittler** [istio/istio#2173]
I suspect it would be sufficient for now to add tracing to the Pilot discovery requests.

We're using [opentrace](http://opentracing.io/) throughout Istio for tracing of gRPC requests. Once we move to the Envoy v2 APIs, we will be able to leverage gRPC, but for now Envoy uses HTTP to poll the Pilot discovery service.

We'll have to investigate to see if there is an HTTP library available for context propagation. If not, we may defer this until the Envoy v2 APIs (and therefore gRPC) land.

Completion of this issue will also require documentation of pilot telemetry.

**Comment by nmittler** [comment]
@andraxylia @ZackButcher how close are we to switching to the v2 APIs? Should we defer this?

**Comment by ZackButcher** [comment]
We're only swapping over to LDSv2 pre-1.0, so this still needs to be done.

**Comment by nmittler** [comment]
@ZackButcher and I discussed a bit more offline...

As it stands, the only added value for tracing discovery requests would be a span for each xDS get method (not particularly helpful WRT debuggability). To get more detailed information, we'd have to plumb the tracing context throughout the pilot discovery service. Since the discovery service will effectively be rewritten once we move to the v2 APIs (and gRPC), we're thinking that we should punt on this for now until v2 lands (possibly post-1.0).

@jasminejaksic @andraxylia thoughts?

**Comment by andraxylia** [comment]
sgtm, let's punt this to post 1.0.
