### ISSUE TITLE
TCP v2 telemetry: metrics not updated for 5 mins

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#21749]
Build gcr.io/istio-testing/proxyv2:1.5-alpha.8d5fde1d919784a0789d44a4e1edc751106cec67
From March 2, 2020

TCP metrics appear and vanish.  There is constant traffic.

0 bytes
<img width="986" alt="Screen Shot 2020-03-02 at 11 40 07 PM" src="https://user-images.githubusercontent.com/800375/75753231-34b59800-5cdf-11ea-92bc-25886599ae41.png">

some non zero a few mins later
<img width="990" alt="Screen Shot 2020-03-02 at 11 39 11 PM" src="https://user-images.githubusercontent.com/800375/75753173-0c2d9e00-5cdf-11ea-873e-efd19a2397f5.png">

**Comment by mandarjog** [comment]
<img width="560" alt="Screen Shot 2020-03-02 at 11 55 06 PM" src="https://user-images.githubusercontent.com/800375/75754312-5e6fbe80-5ce1-11ea-8206-b07fa1fbc375.png">

**Comment by mandarjog** [comment]
@kyessenov we tried changing `tcp_reporting_duration: "0.1s"` and other values but that does not help.

**Comment by kyessenov** [comment]
Have you changed all counters? I think since there is only one timer, it could be that the last write wins.

**Comment by gargnupur** [comment]
https://github.com/istio/istio/issues/21690 and this one kinda looks similar...

**Comment by mandarjog** [comment]
[proxy_log.zip](https://github.com/istio/istio/files/4284587/proxy_log.zip)
@gargnupur client and server logs

**Comment by mandarjog** [comment]
closing with #21690
