### ISSUE TITLE
Mixer duplicating `Set-Cookie` headers in response when rule has multiple `APPEND` operations using same header

### ISSUE THREAD

**Issue by sirajmansour** [istio/istio#21744]
**Bug description**

i have a rule with `responseHeaderOperations` as follows : 

```  
responseHeaderOperations:
    - name: Set-Cookie
      values: [ a1.output.sessionCookie ]
      operation: APPEND
    - name: Set-Cookie
      values: [ a1.output.markerCookie ]
      operation: APPEND
```

and my adapter sets them as follows (they're called mt_sid & mt_mk)

```
return &authnz.HandleAuthnZResponse{
			Result: &v1beta1.CheckResult{Status: status.WithMessage(rpc.OK, "User is authenticated")},
			Output: &authnz.OutputMsg{
				Authorization: strings.Join([]string{bearer, tokens.AccessToken, tokens.IdentityToken}, " "),
				SessionCookie: cookie.String(), //mt_sid
				MarkerCookie: cookieTwo.String(), //mt_mk
			},
		}
```

however upon inspecting the response in the browser, the set-cookie header is set twice for each cookie

![image](https://user-images.githubusercontent.com/5779938/75741512-f2cc3680-5d5e-11ea-922f-9e26338faeb6.png)

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Its expected to append the set-cookie header only one time for each APPEND operation

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**istioctl version --remote :**

```
client version: 1.3.3
citadel version: 1.4.3
galley version: 1.4.3
ingressgateway version: 1.4.3
nodeagent version: 
... //many duplicate empty "nodeagent version: "
nodeagent version: 
pilot version: 1.4.3
policy version: 1.4.3
sidecar-injector version: 1.4.3
telemetry version: 1.4.3
```

**kubectl version**

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-502bfb", GitCommit:"502bfb383169b124d87848f89e17a04b9fc1f6f0", GitTreeState:"clean", BuildDate:"2020-02-07T01:31:02Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

Helm

**Environment where bug was observed (cloud vendor, OS, etc)**

AWS EKS

**Comment by douglas-reid** [comment]
I'm sorry that this did not get any attention. Mixer was deprecated and is now deleted. I'm going to close this issue as result. Feel free to re-open if you believe this should be fixed in the 1.7 release branch.
