### ISSUE TITLE
[pilot] Add Logging to Pilot

### ISSUE THREAD

**Issue by nmittler** [istio/istio#2174]
At a bare minimum, we should swap all of pilot over to the standard Istio logging.

Using this issue for discussion of addition logging.

**Comment by nmittler** [comment]
@ZackButcher @kyessenov @rshriram Any thoughts on additional logging for Pilot?

**Comment by kyessenov** [comment]
The logging is coming from k8s, not sure how you are going to swap that :D

**Comment by nmittler** [comment]
@kyessenov I think this issue refers to the additional logging done by the Pilot discovery service (i.e. glog).

**Comment by kyessenov** [comment]
Can you make a task to also convert library logging to Istio logging? The
reason why we used glog is that k8s heavily relies on it, and we need to
observe library behavior to understand what PIlot does.

**Comment by ZackButcher** [comment]
This issue is about converting pilot to use the standard Istio logging instead of glog.

**Comment by nmittler** [comment]
@kyessenov as I noted in the description, that's this task as well.  And if we want additional logging, this is a forum for that discussion.

**Comment by rshriram** [comment]
Need to have logs be friendly for ingestion into various systems directly. I suggest logrus. It’s easily configurable to send logs to any in-house system. 

We need more structured logging and strict discipline on what we log at various levels. The glog thing is not really helping with integer log levels.

In terms of what to log, we might need both positive and negative logs (fetched info from Consul, created configs, served to sidecar Id zzzx, etc). 


Though I think we get a better idea by looking over our mailing lists to see what people have been trying to get from pilot. 

Tangential thought: open a Unix domain socket to pilot, provide a cli to inspect state (sidecar, registry, etc). Might be a cool thing.

**Comment by ZackButcher** [comment]
We already picked [`Zap` to do logging](https://github.com/istio/istio/tree/master/pkg/log), changing the logger to something else is out of scope of this task. We'll use the library, and if the impl changes underneath then fine.

W.r.t. inspecting state, that's being tracked in #882.

**Comment by nmittler** [comment]
The work to swap over to istio logging has already been done.  I'm going to just close this issue for now. If we have specific items that we want to log, we can address them separately.
