### ISSUE TITLE
suddenly failed checking application ports. listeners in istio-proxy

### ISSUE THREAD

**Issue by zhangxingdeppon** [istio/istio#21758]
**Bug description**
hi. buddies, I met a problem, suddenly failed checking application ports. listeners in istio-proxy, below is the istio-envoy's log:
<pre><code>
[2020-03-03T08:18:59.738Z] "POST /ls000001-14tnj8kd-serving/service HTTP/1.1" 200 - "-" "-" 1340 108 34 34 "172.29.62.99" "-" "07fda42e-89e0-4ddc-844a-df2a42111952" "172.29.62.9:36666" "127.0.0.1:8888" inbound|8888|http-serving|ls000001-14tnj8kd-serving.aipaas-modelserving.svc.cluster.local - 10.222.77.75:8888 172.29.62.99:0 -
[2020-03-03T08:19:03.133Z] "POST /ls000001-14tnj8kd-serving/service HTTP/1.1" 200 - "-" "-" 1391 109 35 34 "172.29.62.99" "-" "48bf6e7b-3b9a-46f3-bb38-40c937dcd293" "172.29.62.9:36666" "127.0.0.1:8888" inbound|8888|http-serving|ls000001-14tnj8kd-serving.aipaas-modelserving.svc.cluster.local - 10.222.77.75:8888 172.29.62.99:0 -
2020-03-03T08:19:06.599844Z     info    Envoy proxy is NOT ready: 2 errors occurred:
        * failed checking application ports. listeners="0.0.0.0:15090"
        * envoy missing listener for inbound application port: 8888

2020-03-03T08:19:08.599875Z     info    Envoy proxy is NOT ready: 2 errors occurred:
        * failed checking application ports. listeners="0.0.0.0:15090"
        * envoy missing listener for inbound application port: 8888

2020-03-03T08:19:10.600017Z     info    Envoy proxy is NOT ready: 2 errors occurred:
        * failed checking application ports. listeners="0.0.0.0:15090"
        * envoy missing listener for inbound application port: 8888
</code></pre>

through above details, after `2020-03-03T08:19:03.133Z`, the Envoy proxy was always not ready, and the relevant pod status is below: 
`ls000001-14tnj8kd-serving-v1029fixed-5f598bbdc6-89x7s   0/2     Running   0          84d     10.222.77.75     d21015u11-62-100   <none>           <none>`
<pre><code>
[root@D21114U24-61-149 bin]# kubectl get pod -n aipaas-modelserving -o wide 
NAME                                                    READY   STATUS    RESTARTS   AGE     IP               NODE               NOMINATED NODE   READINESS GATES
amgxoilixvankflg-serving-v1-68968d7fb-nts4m             0/2     Running   0          19d     10.222.77.91     d21015u11-62-100   <none>           <none>
bigscreen-gimodakj-serving-v1-687ff57f74-j656k          2/2     Running   0          68d     10.222.232.60    d21014u04-62-97    <none>           <none>
bkcardocr-ih7m2m9t-serving-v1-6c8b47ccd-pk65w           0/2     Running   0          82d     10.222.77.123    d21015u11-62-100   <none>           <none>
bocr-z33tyi0b-serving-version1-78d5b65ddd-bkbgt         2/2     Running   0          50d     10.222.19.79     d21016u04-62-101   <none>           <none>
businessv2-vs0a9a8q-serving-version2-8bdcd4f48-lg8fw    0/2     Running   0          43d     10.222.77.68     d21015u11-62-100   <none>           <none>
detescreen-d2t1pra8-serving-v2-56775d5c4-gcvr8          2/2     Running   0          8d      10.222.208.85    d21015u04-62-99    <none>           <none>
detescreen-d2t1pra8-serving-v3-549764c7b6-qrrlm         2/2     Running   0          10d     10.222.136.229   d21012u04-62-93    <none>           <none>
enterocrmc-v6qn09mr-serving-v1-cf7485d4-6pb74           2/2     Running   0          5d16h   10.222.206.91    d21014u11-62-98    <none>           <none>
facede-plggwxi9-serving-v1-7bb5bffd9c-69p6r             2/2     Running   0          68d     10.222.19.126    d21016u04-62-101   <none>           <none>
facemix1-b3790d9d-serving-v1-7c99c854c8-nknk9           2/2     Running   0          68d     10.222.208.78    d21015u04-62-99    <none>           <none>
fqzcommon-7d6wx5hg-serving-fqzdkm1-c4bd7576c-dg5bm      1/2     Running   0          90d     10.222.77.71     d21015u11-62-100   <none>           <none>
frvwvdudwtpjasqh-serving-v1-578d5b7794-kdn55            2/2     Running   0          5d20h   10.222.136.236   d21012u04-62-93    <none>           <none>
fwdpzpihimkandgi-serving-v01beta-7d7dfb657b-w5r5d       2/2     Running   0          103m    10.222.134.21    d21013u04-62-95    <none>           <none>
idcardgen-euwikisb-serving-v1-74486bcb77-zsxz5          2/2     Running   0          68d     10.222.250.166   d21013u11-62-96    <none>           <none>
idcardocr1-s7u6rog7-serving-v1-756f975df-xr68c          2/2     Running   0          41d     10.222.232.33    d21014u04-62-97    <none>           <none>
ls000001-14tnj8kd-serving-hotfixv11-bd77d7dc-whgq4      2/2     Running   0          5d16h   10.222.134.26    d21013u04-62-95    <none>           <none>
ls000001-14tnj8kd-serving-v1029fixed-5f598bbdc6-89x7s   0/2     Running   0          84d     10.222.77.75     d21015u11-62-100   <none>           <none>
ls000001-14tnj8kd-serving-v1029fixed-5f598bbdc6-lf4wb   2/2     Running   0          89d     10.222.208.102   d21015u04-62-99    <none>           <none>
mixpayv1-yb9kzgif-serving-mixpayv1-55df7f97f7-mxhth     2/2     Running   0          11d     10.222.208.84    d21015u04-62-99    <none>           <none>
ps-o2yowumj-serving-v4-869f9658d6-8zhdv                 2/2     Running   0          25d     10.222.208.113   d21015u04-62-99    <none>           <none>
ps-o2yowumj-serving-v4-869f9658d6-9dfnp                 2/2     Running   0          25d     10.222.19.96     d21016u04-62-101   <none>           <none>
svdeyzxmfekscmqz-serving-v2-6d47499f57-kt9h4            2/2     Running   0          5d23h   10.222.134.48    d21013u04-62-95    <none>           <none>
whiteblack-fpz42zdo-serving-v5-69cbb8fc7f-xnxcl         2/2     Running   0          74d     10.222.232.23    d21014u04-62-97    <none>           <none>
wxnxzueloouqdmjs-serving-v1-775f84946d-dc627            2/2     Running   0          4d1h    10.222.134.18    d21013u04-62-95    <none>           <none>

</code></pre>

 in addition,  the command `istioctl  proxy-status` lost the istio-proxy `ls000001-14tnj8kd-serving-v1029fixed-5f598bbdc6-89x7s `'s relevant informations:
<pre><cpde>
[root@D21114U24-61-149 bin]# ./istioctl  proxy-status
NAME                                                                          CDS        LDS        EDS               RDS          PILOT                            VERSION
bigscreen-gimodakj-serving-v1-687ff57f74-j656k.aipaas-modelserving            SYNCED     SYNCED     SYNCED (50%)      SYNCED       istio-pilot-86f884f66b-kfkwm     1.2.2
bocr-z33tyi0b-serving-version1-78d5b65ddd-bkbgt.aipaas-modelserving           SYNCED     SYNCED     SYNCED (50%)      SYNCED       istio-pilot-86f884f66b-kfkwm     1.2.2
bryantest-6c4ccdfbcd-qdvr7.test-istio                                         SYNCED     SYNCED     SYNCED (50%)      SYNCED       istio-pilot-86f884f66b-kfkwm     1.2.2
detescreen-d2t1pra8-serving-v2-56775d5c4-gcvr8.aipaas-modelserving            SYNCED     SYNCED     SYNCED (50%)      SYNCED       istio-pilot-86f884f66b-kfkwm     1.2.2
detescreen-d2t1pra8-serving-v3-549764c7b6-qrrlm.aipaas-modelserving           SYNCED     SYNCED     SYNCED (50%)      SYNCED       istio-pilot-86f884f66b-kfkwm     1.2.2
enterocrmc-v6qn09mr-serving-v1-cf7485d4-6pb74.aipaas-modelserving             SYNCED     SYNCED     SYNCED (50%)      SYNCED       istio-pilot-86f884f66b-kfkwm     1.2.2
facede-plggwxi9-serving-v1-7bb5bffd9c-69p6r.aipaas-modelserving               SYNCED     SYNCED     SYNCED (50%)      SYNCED       istio-pilot-86f884f66b-kfkwm     1.2.2
facemix1-b3790d9d-serving-v1-7c99c854c8-nknk9.aipaas-modelserving             SYNCED     SYNCED     SYNCED (50%)      SYNCED       istio-pilot-86f884f66b-kfkwm     1.2.2
flaskapp-v1-584b694fd4-fv4g2.test-istio                                       SYNCED     SYNCED     SYNCED (50%)      SYNCED       istio-pilot-86f884f66b-kfkwm     1.2.2
flaskapp-v2-588679c8fb-6skxq.test-istio                                       SYNCED     SYNCED     SYNCED (50%)      SYNCED       istio-pilot-86f884f66b-kfkwm     1.2.2
frvwvdudwtpjasqh-serving-v1-578d5b7794-kdn55.aipaas-modelserving              SYNCED     SYNCED     SYNCED (50%)      SYNCED       istio-pilot-86f884f66b-kfkwm     1.2.2
fwdpzpihimkandgi-serving-v01beta-7d7dfb657b-w5r5d.aipaas-modelserving         SYNCED     SYNCED     SYNCED (50%)      SYNCED       istio-pilot-86f884f66b-kfkwm     1.2.2
idcardgen-euwikisb-serving-v1-74486bcb77-zsxz5.aipaas-modelserving            SYNCED     SYNCED     SYNCED (50%)      SYNCED       istio-pilot-86f884f66b-kfkwm     1.2.2
idcardocr1-s7u6rog7-serving-v1-756f975df-xr68c.aipaas-modelserving            SYNCED     SYNCED     SYNCED (50%)      SYNCED       istio-pilot-86f884f66b-kfkwm     1.2.2
istio-egressgateway-66794b7556-2v89n.istio-system                             SYNCED     SYNCED     SYNCED (100%)     NOT SENT     istio-pilot-86f884f66b-kfkwm     1.2.2
istio-egressgateway-66794b7556-bf8ks.istio-system                             SYNCED     SYNCED     SYNCED (100%)     NOT SENT     istio-pilot-86f884f66b-kfkwm     1.2.2
istio-egressgateway-66794b7556-bjczm.istio-system                             SYNCED     SYNCED     SYNCED (100%)     NOT SENT     istio-pilot-86f884f66b-kfkwm     1.2.2
istio-egressgateway-66794b7556-npj6r.istio-system                             SYNCED     SYNCED     SYNCED (100%)     NOT SENT     istio-pilot-86f884f66b-kfkwm     1.2.2
istio-ingressgateway-56bccf6b64-4jdck.istio-system                            SYNCED     SYNCED     SYNCED (100%)     SYNCED       istio-pilot-86f884f66b-kfkwm     1.2.2
istio-ingressgateway-56bccf6b64-l9pkf.istio-system                            SYNCED     SYNCED     SYNCED (100%)     SYNCED       istio-pilot-86f884f66b-kfkwm     1.2.2
istio-ingressgateway-56bccf6b64-nlhl9.istio-system                            SYNCED     SYNCED     SYNCED (100%)     SYNCED       istio-pilot-86f884f66b-kfkwm     1.2.2
istio-ingressgateway-56bccf6b64-qwgk6.istio-system                            SYNCED     SYNCED     SYNCED (100%)     SYNCED       istio-pilot-86f884f66b-kfkwm     1.2.2
istio-ingressgateway-56bccf6b64-zd2ws.istio-system                            SYNCED     SYNCED     SYNCED (100%)     SYNCED       istio-pilot-86f884f66b-kfkwm     1.2.2
ls000001-14tnj8kd-serving-hotfixv11-bd77d7dc-whgq4.aipaas-modelserving        SYNCED     SYNCED     SYNCED (50%)      SYNCED       istio-pilot-86f884f66b-kfkwm     1.2.2
ls000001-14tnj8kd-serving-v1029fixed-5f598bbdc6-lf4wb.aipaas-modelserving     SYNCED     SYNCED     SYNCED (50%)      SYNCED       istio-pilot-86f884f66b-kfkwm     1.2.2
mixpayv1-yb9kzgif-serving-mixpayv1-55df7f97f7-mxhth.aipaas-modelserving       SYNCED     SYNCED     SYNCED (50%)      SYNCED       istio-pilot-86f884f66b-kfkwm     1.2.2
ps-o2yowumj-serving-v4-869f9658d6-8zhdv.aipaas-modelserving                   SYNCED     SYNCED     SYNCED (50%)      SYNCED       istio-pilot-86f884f66b-kfkwm     1.2.2
ps-o2yowumj-serving-v4-869f9658d6-9dfnp.aipaas-modelserving                   SYNCED     SYNCED     SYNCED (50%)      SYNCED       istio-pilot-86f884f66b-kfkwm     1.2.2
sleep-v1-565db489cc-dnwj8.test-istio                                          SYNCED     SYNCED     SYNCED (50%)      SYNCED       istio-pilot-86f884f66b-kfkwm     1.2.2
svdeyzxmfekscmqz-serving-v2-6d47499f57-kt9h4.aipaas-modelserving              SYNCED     SYNCED     SYNCED (50%)      SYNCED       istio-pilot-86f884f66b-kfkwm     1.2.2
whiteblack-fpz42zdo-serving-v5-69cbb8fc7f-xnxcl.aipaas-modelserving           SYNCED     SYNCED     SYNCED (50%)      SYNCED       istio-pilot-86f884f66b-kfkwm     1.2.2
wxnxzueloouqdmjs-serving-v1-775f84946d-dc627.aipaas-modelserving              SYNCED     SYNCED     SYNCED (50%)      SYNCED       istio-pilot-86f884f66b-kfkwm     1.2.2

</code></pre>
the isti-proxy  CPU & Memory resource was lower than limit, just a little.
![image](https://user-images.githubusercontent.com/16789841/75768610-a2190580-5d7f-11ea-8dc0-5110ba5ab3a8.png)

the pilot's log didn't have any information about it, and I have saw the details https://github.com/istio/istio/issues/16125 and https://github.com/istio/istio/issues/16189, but I can't find the usefull information to resolve it, why did it cause it?  how can I resolve this problem or reduce the happend  frequency ? if  want more details, I'm pleasure to provide it, it's very important for us, thank you very much.

**Expected behavior**
thie problem can be resolved 
**Steps to reproduce the bug**
it's just accidental.
**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
<pre><code>
[root@D21114U24-61-149 bin]# ./istioctl version --remote
client version: 1.2.2
citadel version: 1.2.2
egressgateway version: 1.2.2
egressgateway version: 1.2.2
egressgateway version: 1.2.2
egressgateway version: 1.2.2
egressgateway version: 1.2.2
galley version: 1.2.2
ingressgateway version: 1.2.2
ingressgateway version: 1.2.2
ingressgateway version: 1.2.2
ingressgateway version: 1.2.2
ingressgateway version: 1.2.2
pilot version: 1.2.2
policy version: 1.2.2
sidecar-injector version: 1.2.2
telemetry version: 1.2.2

</code></pre>

**How was Istio installed?**
according to the official document.
**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by zhangxingdeppon** [comment]
when I delete the pod `ls000001-14tnj8kd-serving-v1029fixed-5f598bbdc6-89x7s` , it's still not ready,
<pre><code>

[root@D21114U24-61-149 ~]# kubectl delete pod ls000001-14tnj8kd-serving-v1029fixed-5f598bbdc6-89x7s  -n aipaas-modelserving 
pod "ls000001-14tnj8kd-serving-v1029fixed-5f598bbdc6-89x7s" deleted


[root@D21114U24-61-149 ~]# kubectl get pod -n aipaas-modelserving -o  wide 
NAME                                                    READY   STATUS    RESTARTS   AGE     IP               NODE               NOMINATED NODE   READINESS GATES
amgxoilixvankflg-serving-v1-68968d7fb-nts4m             0/2     Running   0          19d     10.222.77.91     d21015u11-62-100   <none>           <none>
bigscreen-gimodakj-serving-v1-687ff57f74-j656k          2/2     Running   0          68d     10.222.232.60    d21014u04-62-97    <none>           <none>
bkcardocr-ih7m2m9t-serving-v1-6c8b47ccd-pk65w           0/2     Running   0          82d     10.222.77.123    d21015u11-62-100   <none>           <none>
bocr-z33tyi0b-serving-version1-78d5b65ddd-bkbgt         2/2     Running   0          50d     10.222.19.79     d21016u04-62-101   <none>           <none>
businessv2-vs0a9a8q-serving-version2-8bdcd4f48-lg8fw    0/2     Running   0          43d     10.222.77.68     d21015u11-62-100   <none>           <none>
detescreen-d2t1pra8-serving-v2-56775d5c4-gcvr8          2/2     Running   0          8d      10.222.208.85    d21015u04-62-99    <none>           <none>
detescreen-d2t1pra8-serving-v3-549764c7b6-qrrlm         2/2     Running   0          10d     10.222.136.229   d21012u04-62-93    <none>           <none>
enterocrmc-v6qn09mr-serving-v1-cf7485d4-6pb74           2/2     Running   0          5d17h   10.222.206.91    d21014u11-62-98    <none>           <none>
facede-plggwxi9-serving-v1-7bb5bffd9c-69p6r             2/2     Running   0          68d     10.222.19.126    d21016u04-62-101   <none>           <none>
facemix1-b3790d9d-serving-v1-7c99c854c8-nknk9           2/2     Running   0          68d     10.222.208.78    d21015u04-62-99    <none>           <none>
fqzcommon-7d6wx5hg-serving-fqzdkm1-c4bd7576c-dg5bm      1/2     Running   0          90d     10.222.77.71     d21015u11-62-100   <none>           <none>
frvwvdudwtpjasqh-serving-v1-578d5b7794-kdn55            2/2     Running   0          5d21h   10.222.136.236   d21012u04-62-93    <none>           <none>
fwdpzpihimkandgi-serving-v01beta-7d7dfb657b-w5r5d       2/2     Running   0          150m    10.222.134.21    d21013u04-62-95    <none>           <none>
idcardgen-euwikisb-serving-v1-74486bcb77-zsxz5          2/2     Running   0          68d     10.222.250.166   d21013u11-62-96    <none>           <none>
idcardocr1-s7u6rog7-serving-v1-756f975df-xr68c          2/2     Running   0          41d     10.222.232.33    d21014u04-62-97    <none>           <none>
ls000001-14tnj8kd-serving-hotfixv11-bd77d7dc-whgq4      2/2     Running   0          5d17h   10.222.134.26    d21013u04-62-95    <none>           <none>
ls000001-14tnj8kd-serving-v1029fixed-5f598bbdc6-lf4wb   2/2     Running   0          89d     10.222.208.102   d21015u04-62-99    <none>           <none>
ls000001-14tnj8kd-serving-v1029fixed-5f598bbdc6-n25lj   0/2     Running   0          92s     10.222.77.118    d21015u11-62-100   <none>           <none>
mixpayv1-yb9kzgif-serving-mixpayv1-55df7f97f7-mxhth     2/2     Running   0          11d     10.222.208.84    d21015u04-62-99    <none>           <none>
ps-o2yowumj-serving-v4-869f9658d6-8zhdv                 2/2     Running   0          25d     10.222.208.113   d21015u04-62-99    <none>           <none>
ps-o2yowumj-serving-v4-869f9658d6-9dfnp                 2/2     Running   0          25d     10.222.19.96     d21016u04-62-101   <none>           <none>
svdeyzxmfekscmqz-serving-v2-6d47499f57-kt9h4            2/2     Running   0          5d23h   10.222.134.48    d21013u04-62-95    <none>           <none>
whiteblack-fpz42zdo-serving-v5-69cbb8fc7f-xnxcl         2/2     Running   0          74d     10.222.232.23    d21014u04-62-97    <none>           <none>
wxnxzueloouqdmjs-serving-v1-775f84946d-dc627            2/2     Running   0          4d2h    10.222.134.18    d21013u04-62-95    <none>           <none>

</pre></code>

**Comment by howardjohn** [comment]
Istio 1.2 is not supported any longer. Please update to a newer version. This code has entirely changed since then
