### ISSUE TITLE
Add Ability to Set CPU and Memory Resource Limits on Istio-Proxy

### ISSUE THREAD

**Issue by gjtempleton** [istio/istio#21757]
**Describe the feature request**

Users currently have the ability to use annotations to override the default resource *requests* of the injected proxy container, however they have no ability to override the resource limits:

https://github.com/istio/istio/blob/f27f66bafb01f68628b952c492d66188ba0339ad/manifests/istio-control/istio-discovery/files/injection-template.yaml#L282-L294

This means that if users in a namespace with a ResourceQuota on both resource requests and limits wants to override the resource requests of the proxy they will no longer be able to successfully schedule pods as they will fail the quota validation.

My proposal is to add the ability to use 2 new annotations to allow users to also override the cluster defaults for resource limits:

```
sidecar.istio.io/proxyCPULimit
sidecar.istio.io/proxyMemoryLimit
```

These would be added to the existing logic linked above where overrides of the default resource limits/requests only take place if one or more of the annotations is set.

**Describe alternatives you've considered**

Defaulting to the limits set on a global level for the mesh - this still wouldn't allow users to increase (or decrease) the resource limits for a given deployment's inject proxy.

**Additional context**

This is related to #21240

**Comment by howardjohn** [comment]
Fixed by #22395. Thanks!
