### ISSUE TITLE
Istio Bot Policy

### ISSUE THREAD

**Issue by DrFertility** [istio/istio#21752]
I raised an issue #16099 that has been closed automatically by the Istio Bot Policy.

Surely the bot should not close issues unless someone from the Istio team has accessed the issue.

I believe #16099 is an issue and definitely does not behave as stated in the documention.

You will lose valuable issue reports if the bot blindly closes issues due to inactivity

**Comment by howardjohn** [comment]
Thanks for the issue! We are tracking changes/experience with the bot in https://github.com/istio/istio/issues/19111
