### ISSUE TITLE
Pilot Telemetry Collection (Logging, Monitoring)

### ISSUE THREAD

**Issue by nmittler** [istio/istio#2175]

**Comment by nmittler** [comment]
@jasminejaksic @douglas-reid @mandarjog what has been done elsewhere WRT documentation for tracing, logging, and monitoring for each component? Is this something that needs to be documented?

**Comment by douglas-reid** [comment]
@nmittler Not much else has been documented -- at least explicitly. Just having something describing explicitly how (at the moment) tracing is configured and where/how envoy metrics are sent and how to access envoy logs would be a big step forward.  Happy to discuss in more detail.

**Comment by nmittler** [comment]
@douglas-reid ok thanks.  I suspect just being consistent is good enough for now.

@jasminejaksic so it sounds like doing nothing for documentation here is at least consistent across components. For logging in particular, I don't think documentation makes sense (it's a lot and it's always going to be in flux). Metrics/tracing could be documented, but spending cycles updating istio.io probably isn't beneficial to many people and we'd have to do it consistently across components.

So no extra docs here ... does that sound reasonable?

**Comment by linsun** [comment]
So for this WI, I'm interested in understanding how to view pilot telemetry information.  It is not obvious to me at the moment.

**Comment by andraxylia** [comment]
Tracing moved to post 1.0.
