### ISSUE TITLE
Distributed Tracing overview refers to istio-pilot deployment

### ISSUE THREAD

**Issue by esnible** [istio/istio#21769]
https://preliminary.istio.io/docs/tasks/observability/distributed-tracing/overview/ instructs the user to change the trace sampling rate using `kubectl -n istio-system edit deploy istio-pilot`.

The is no longer valid, the user could use `istiod` instead of `istio-pilot`.

Better might be to not even tell the user they can edit an active Deployment but expand the section that tells them to set `values.pilot.traceSampling` with instructions to use `istioctl manifest apply ... --set values.pilot.traceSampling=...`

**Comment by howardjohn** [comment]
I have verified this is no longer present on  https://preliminary.istio.io/docs/tasks/observability/distributed-tracing/overview/
