### ISSUE TITLE
[1.5] Prometheus scraping pods shouldn't be reported in Istio telemetry

### ISSUE THREAD

**Issue by jotak** [istio/istio#21762]
**Bug description**

Previously, the telemetry resulting from prometheus scraper was intentionally ignored: see this old PR: https://github.com/istio/istio/pull/12251

With telemetry v2, the same problem is reappearing. When prometheus is configured to scrape the user app' pods, this traffic is being reported in istio/envoy telemetry. For the same reasons as we did one year ago (it was screwing up kiali graph), it would be great to ignore this traffic. Or perhaps do something to better identify its origin, so that we can act in Kiali.

I suspect the same issue could arise with traffic generated by k8s probes although I didn't test it, but there was also a user-agent check for this.

The old Mixer rule that isn't valid anymore with telemtry v2 is:
` match: (context.protocol == "http" || context.protocol == "grpc") && (match((request.useragent | "-"), "kube-probe*") == false) && (match((request.useragent | "-"), "Prometheus*") == false)`

**Steps to reproduce the bug**

- Configure Prometheus & applications to scrape pods, e.g: via job `kubernetes-pods` and/or `kubernetes-pods-istio-secure`

- Check telemetry in prometheus and/or via Kiali, see traffic that originates from "Unknown"

Example in Kiali:
![Capture d’écran de 2020-03-03 12-35-14](https://user-images.githubusercontent.com/2153442/75774201-b5ac7800-5d4f-11ea-9d44-f469fc9c312a.png)

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
client version: 1.5.0-beta.5
control plane version: 1.5.0-beta.5
data plane version: 1.5.0-beta.5 (10 proxies)
```

**How was Istio installed?**

via `istioctl manifest apply --set profile=demo`

Note, I had also to modify prometheus configmap to re-activate app' pods scraping. It seems like prom's configmap is not exactly similar to the one used for helm chart installation.

**Environment where bug was observed (cloud vendor, OS, etc)**

minikube

**Comment by mandarjog** [comment]
@jotak @jmazzitelli @douglas-reid 
We can fix it in 1.5.1

**Comment by douglas-reid** [comment]
@mandarjog this has come up in other contexts (including the AWS demo, etc.).  can we repurpose / expand the access log filter functionality here?

**Comment by sdake** [comment]
Referencing: https://github.com/istio/istio.io/pull/6554

As I understand the situation, the problem is introduced by adding a sidecar to SDS. That was done to enable SDS certificate creation in prometheus.

Filtering may be appropriate as we don't have a clear answer to how to upgrade without a sidecar present. Maybe it is straightforward, in which case 1.5.1 is fine. If it is not straightforward to upgrade a minor release with a sidecar to one without, then we should consider the proposal here: https://github.com/istio/istio/issues/21762#issuecomment-594066744.

**Comment by sdake** [comment]
> @jotak @jmazzitelli @douglas-reid
> We can fix it in 1.5.1

@mandarjog my initial reaction is to agree this is solvable in a z-stream. This does appear to be a regression in behavior as discussed here: https://github.com/istio/istio/issues/21720#issuecomment-594160100. We need to determine if this regression is worth an exception to our no regressions in releases policy.

**Comment by jotak** [comment]
Hi / update,
I've tested with 1.6, on minikube, and I still see the problem (not sure if it was meant to be fixed in 1.6).

**Comment by douglas-reid** [comment]
@mandarjog thoughts on this issue and how to move forward?

**Comment by jotak** [comment]
Not sure what changed but I don't see the problem anymore in 1.7
For me then, it's fine to close.

**Comment by douglas-reid** [comment]
Closing, per https://github.com/istio/istio/issues/21762#issuecomment-692506260

**Comment by gadiener** [comment]
Hello everyone, I'm facing the same problem with the datadog agent with Istio 1.9.1, is there any workaround for that?

![Screenshot 2021-03-25 at 11 54 01](https://user-images.githubusercontent.com/8479033/112489441-b9f26b80-8d7e-11eb-902b-6408dc8d1ca2.png)

Here the original comment https://github.com/kiali/kiali/issues/2477#issuecomment-806558068

**Comment by bianpengyuan** [comment]
So the datadog agent scrapes metrics from application container? Have you tried to add a sidecar to the datadog agent?

**Comment by gadiener** [comment]
Hey @bianpengyuan yes more or less as prometheus does. 

Nope but I will try tomorrow and I will let you know, thanks!

**Comment by bianpengyuan** [comment]
One easiest option to avoid the issue is using prometheus metric merging: https://istio.io/latest/docs/ops/integrations/prometheus/#option-1-metrics-merging That way scraping request won't go through the sidecar and thus no metric will be generated for scraping traffic.

**Comment by gadiener** [comment]
Hi @bianpengyuan, unfortunately this is not an option. Datadog has a specific integration for Istio that has a different pricing (cheaper) than the custom metric so we have to treat them differently. Also in a soft multi-tenant environment, it is possible that someone is using envoy directly in the application (and I have no control on it), so I don't want to risk losing metrics during the merge.

**Comment by bianpengyuan** [comment]
Sorry, I am not sure I follow the reasoning. IIUC you'd need to somehow scrape application and istio metrics separately?

**Comment by gadiener** [comment]
@bianpengyuan yes exactly. Adding the sidecar on the Datadog Agent the problem is fixed (I'm also using mTLS in this way). Thanks!
