### ISSUE TITLE
Demo profile Zipkin icon missing

### ISSUE THREAD

**Issue by esnible** [istio/istio#21766]
I installed Istio using 1.5.0 beta 5 and `istioctl manifest apply --set profile=demo --set values.global.mtls.enabled=true --set addonComponents.tracing.enabled=true --set values.tracing.enabled=true --set values.tracing.provider=zipkin`

I followed the instructions at https://preliminary.istio.io/docs/tasks/observability/distributed-tracing/zipkin/ to bring up Zipkin.

The icon with the Zipkin logo is just a question mark.  The icon comes from https://zipkin.io/public/img/zipkin-logo-200x119.jpg which no longer holds it.

This is a minor image, but it suggests the Zipkin we package is drifting.

**Comment by howardjohn** [comment]
Yeah its pretty old, I updated to 2.20 in #21686 (in master)

**Comment by howardjohn** [comment]
I have verified this is fixed in 1.6 by zipkin upgrade
