### ISSUE TITLE
"istioctl upgrade" requires the same settings used to install Istio, but doesn't take `--set` parameter

### ISSUE THREAD

**Issue by esnible** [istio/istio#21778]
What I did:

Deleted `istio-system` namespace
`./istio-1.4.5/bin/istioctl manifest apply --set profile=demo --set values.global.mtls.enabled=true`
Waited a few minutes
`./istio-1.5.0-beta.5/bin/istioctl x upgrade`

```
./istio-1.5.0-beta.5/bin/istioctl version
client version: 1.5.0-beta.5
egressgateway version: 1.4.5
ingressgateway version: 1.5.0-beta.5
pilot version: 1.5.0-beta.5
data plane version: 1.5.0-beta.5 (2 proxies), 1.4.5 (1 proxies)
```

The egressgateway should be at the same version as the ingressgateway.

**Comment by howardjohn** [comment]
You need to pass the same settings to upgrade

**Comment by esnible** [comment]
@howardjohn I can't pass the settings to `istioctl upgrade`

```
./istio-1.5.0-beta.5/bin/istioctl upgrade --set profile=demo --set values.global.mtls.enabled=true
Error: unknown flag: --set
```

**Comment by howardjohn** [comment]
I don't know why but you can only use `-f`

**Comment by esnible** [comment]
@howardjohn I feel the syntax SHOULD be the same, so I have added the `enhancement` tag to the Issue.

**Comment by richardwxn** [comment]
I think we should update istioctl upgrade to take also the --set command, /CC @elfinhe

**Comment by elfinhe** [comment]
Based on the feedback I read from this discussion, I think we need to add --set to istioctl upgrade.

**Comment by esnible** [comment]
@richardwxn I have made this an **Enhancement** and set the milestone for 1.6.  Let's track this for 1.6.

**Comment by maplebeats** [comment]
why upgrade can't  automatically recognize the current configuration to update :(

**Comment by esnible** [comment]
@maplebeats I also believe Istio should recognize the current configuration.  Please add a thumbs-up or celebration vote to https://github.com/istio/istio/issues/20000 , or comment there.

**Comment by esnible** [comment]
Verified this works in Master.
