### ISSUE TITLE
"Getting Envoy's Access Logs" task shows incorrect output

### ISSUE THREAD

**Issue by esnible** [istio/istio#21774]
The page https://preliminary.istio.io/docs/tasks/observability/logs/access-log/ shows the output of `istioctl manifest apply`:

```
$ istioctl manifest apply --set profile=demo --set values.global.proxy.accessLogFile="/dev/stdout"
configmap "istio" replaced
```

The `apply` command never says `configmap "istio" replaced`.  It actually says

```
- Applying manifest for component Base...
✔ Finished applying manifest for component Base.
- Applying manifest for component Pilot...
✔ Finished applying manifest for component Pilot.
- Applying manifest for component EgressGateways...
- Applying manifest for component IngressGateways...
- Applying manifest for component AddonComponents...
- Pruning objects for disabled component Telemetry...
✔ Finished pruning objects for disabled component Telemetry.
✔ Finished applying manifest for component EgressGateways.
✔ Finished applying manifest for component IngressGateways.
✔ Finished applying manifest for component AddonComponents.
```

The incorrect response appears twice on the page.

**Comment by esnible** [comment]
Note that I did not attach this Issue to the Community Testing Days spreadsheet because I didn't want it to look like that task didn't work.  The task works, it just isn't easy to understand if the user is doing the task correctly because the output doesn't match the expected output.

**Comment by howardjohn** [comment]
I confirmed https://preliminary.istio.io/docs/tasks/observability/logs/access-log/ is fixed
