### ISSUE TITLE
Upgrade client-go for k8s version 1.9

### ISSUE THREAD

**Issue by ayj** [istio/istio#2177]
k8s version 1.9.x adds support for `admission.k8s.io/v1beta1 Kind=AdmissionReview`, e.g. mutating webhooks. We intend to use this feature for automatic proxy injection. It will eventually replace the alpha initializer mechanism. This requires updating the k8s client-go libraries to 1.9. 

Unfortunately, client-go 1.9 does not support the v1alpha1 webhook currently used for server-side configuration validation. I propose that we drop support for server-side config validation with v1alpha1 webhooks and recommend upgrading to k8s 1.9.x for beta-quality config validation and proxy injection. We can maintain alpha initializer for the time being until sufficient userbase adopts k8s 1.9 and/or initializer API is removed.

k8s 1.9 has been released but none of our testing infrastructure supports it yet, e.g. GKE, IBM, minikube. We can defer this client-go update and alpha webhook deprecation until 1.9 is more widely available.

/cc @jmuk @gjwestlife @linsun @cmluciano @mandarjog

**Comment by kyessenov** [comment]
In theory, client-go 1.9 should be backwards compatible with k8s 1.8; in practice, breakages slip through peer-review. It would be good start testing, however, client-go 1.9 against 1.8 k8s since users will run into the issues until k8s 1.8 is out of use.

**Comment by ayj** [comment]
The various admission and admission registration APIs for webhooks graduated from alpha to beta.  See https://github.com/kubernetes/kubernetes/commit/951962512b9cfe15b25e9c715a5f33f088854f97#diff-bbf294b0c56922b810fe35f877f7a441). v1alpha1 webhook API doesn't exist in client-go 1.9.

client-go 1.9 should be backwards compatible for everything else (in theory), so we should certainty test early and with k8s. But we shouldn't switch until our test infrastructure can run the new server-side webhook tests. Otherwise we risk going a month+ without proper e2e test coverage of our admission controllers.

**Comment by cmluciano** [comment]
> In theory, client-go 1.9 should be backwards compatible with k8s 1.8; 

This unfortunately has not been the case between releases of k8s mainline and client-go since their repository split. This might have to do with the changes of k8s mainline APIs graduating from alpha -> beta with each release.

**Comment by cmluciano** [comment]
I agree that we should deprecate the initializer and move forward with mutating webhooks for 1.9. Since initializers are still alpha, k8s API policy provides no guarantee of backwards-compatibility or long-term support.

**Comment by costinm** [comment]
+1 - we should add a release note and maybe send an email that 0.4 is the last version to support initializer.

It's more important to get 1.9 and the new features - and also to cleanup the code and testing infra.
Assuming the new webhook injection can be configured per-namespace I would hope to have a single
testing environment to worry about - with both kube-inject and webhook tests in different ns.

**Comment by cmluciano** [comment]
In that case, can I delete initializer code so that I can merge #1895 sooner?

**Comment by ayj** [comment]
Initializer is unaffected by client-go 1.9 update. The alpha initialized
API is still present and upgrading shouldn’t break anything AFAIK.

The webhook API that we’re using for pilot and mixer config validation
changed from alpha to beta and will break with upgrade. You need (1) update
config validiton code to use the new API and (2) update
GKE/minikube/api-server to k8s version 1.9.

(2) may not be available yet in which case you would need to disable some
validation unit tests that invoke the beta we hook API.

**Comment by costinm** [comment]
I would assume the tests will just skip if version is <1.9.

Maybe I'm a bit confused here - isn't webhook supposed to also replace the
auto-injection,
or is it a different API ? I was hoping we can simplify the test infra - is
there any long
term plan or reason to continue to maintain/test the initializer ? I assume
we'll not mark it
stable, any reason a user will continue to use it once webhooks are ready ?

**Comment by ayj** [comment]
Mutating webhook and initializer are different k8s APIs. The plan is for
mutating webhook to replace initializer as mechanism for auto-injection.

Removing initializer shouldn’t make upgrading to client-go 1.9 any easier.
We can remove initializer mechanism and only support auto-injection on k8s
>= 1.9.x. 1.7.x/1.8.x would need to use manual methods, e.g. kube-inject.

**Comment by costinm** [comment]
Is there any value in maintaining the 'initializer' and having it in 0.5,
if the plan
is for mutating webhook  in 1.9+, and kube-inject in <1.9 ?  Even if it is
not
related to client-go 1.9.

+1 on stopping the validation with the alpha API, and focusing on the beta,
it
seems the best option, we must upgrade to 1.9 and move forward.

**Comment by mangelov95** [comment]
If `initializer` is not maintained does this mean that release 0.5 won't be compatible with use cases of automatic sidecar injection on IBM Bluemix (since that only supports Kubernetes 1.7.4 I think, and not yet 1.9)?

**Comment by ayj** [comment]
Yes, `initializer` would be dropped from 0.5 and the only supported method for automatic sidecar injection would be mutating webhooks (k8s >= 1.9.x).

cc @rshriram @linsun for IBM support questions

**Comment by linsun** [comment]
Thank you @ayj!  @mangelov95 ibm cloud container service (btw, we had a rebranding late last year) currently supports 1.7.4 and 1.8.  We are working on 1.9.

@ayj could you help me understand if Istio 0.5 works on k8s 1.7.4 or 1.8 at all?  Could it work without the auto side car injection?

**Comment by ayj** [comment]
Istio 0.5 should continue to work on k8s 1.7/1.8 and can use `kube-inject` for manual proxy injection. Users can upgrade to 1.9 for automatic server-side sidecar injection and config validation.

**Comment by linsun** [comment]
@ayj thanks for confirming that.  So this doesn't change the istio general requirement for k8s, which is still 1.7 or 1.7+, however, if user needs auto side car injection, user must move to k8s 1.9.

**Comment by linsun** [comment]
re config validation, are you referring to additional config validation beyond what is provided in istioctl?  @ayj

**Comment by ayj** [comment]
istioctl provides client-side validation for some resources (e.g. pilot, mixerclient). AFAIK, mixer config validation is only available server-side. cc @jmuk

**Comment by mangelov95** [comment]
Thank you for the info @linsun & @ayj! A question which is a little bit off-topic, but do you have an idea when would IBM Cloud CS start offering k8s 1.9? My use case involves deploying an application as a helm chart, so it seems that my only reasonable option to use Istio is with automatic sidecar injection, so that means that IBM Cloud CS stops being an environment option for me at Istio 0.5. 😢  

(Based on kubernetes/helm#2596 & kubernetes/helm#2554 the only way to inject sidecars into helm chart currently is by using the auto injection functionality, I hope you can prove me wrong 😃 )

**Comment by ayj** [comment]
You could play around with trying to patch an already deployed app. You could teach `kube-inject` to emit a JSON patch of injected containers/volumes and `kubectl patch` the live deployment. Adding a dummy non-existent volume dependency to the helm chart and removing it as part of the `kubectl patch` that contains the injected resources would avoid creating any pods without the injected sidecar.

**Comment by costinm** [comment]
Probably I shouldn't mention this - but would the sidecar initializer from
0.4 continue to work ? The actual injection should be compatible and
didn't change - of course mixing different versions is dangerous, but for a
short time it may be an option.

Costin

**Comment by ayj** [comment]
:) Reusing 0.4 initializer with 0.5 is a temporary option assuming the underlying sidecar configuration doesn't change in incompatible ways.

**Comment by mangelov95** [comment]
No, I was just generally concerned with how auto injection from ver. 0.4 to 0.5 would be handled for older versions of k8s. Keeping version 0.4 for the time being is a good option for me.

**Comment by ayj** [comment]
k8s.io/client-go was upgraded to 1.9 in https://github.com/istio/istio/pull/2396
