### ISSUE TITLE
Multicluster with Replicated Control Planes not working

### ISSUE THREAD

**Issue by mbanikazemi** [istio/istio#21784]
**Bug description**

Following the instructions at https://preliminary.istio.io/docs/setup/install/multicluster/gateways/
cannot access the remote service on Istio 1.5.0-beta.4.
The curl receives a "503 Service Unavailable"

**Expected behavior**

Should be able to reach service on a second cluster.

**Steps to reproduce the bug**

Follow instructions on https://preliminary.istio.io/docs/setup/install/multicluster/gateways/

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

$ istioctl version
client version: 1.5.0-beta.4
control plane version: 1.5.0-beta.4
data plane version: 1.5.0-beta.4 (4 proxies)

**How was Istio installed?**

As instructed at https://preliminary.istio.io/docs/setup/install/multicluster/gateways/

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by esnible** [comment]
The Ingress seems unable to reach its own remote pod:

```
kubectl --context $CTX_CLUSTER2 -n istio-system exec -it istio-ingressgateway-59855767df-4hllz -- curl httpbin.bar:8000/headers
curl: (56) Recv failure: Connection reset by peer
command terminated with exit code 56
```

The remote pod itself is health:

```
$ kubectl --context $CTX_CLUSTER2 -n bar exec -it httpbin-64776bf78d-9zwvl -c istio-proxy -- curl localhost:80/headers
{
  "headers": {
    "Accept": "*/*", 
    "Host": "localhost", 
    "User-Agent": "curl/7.58.0"
  }
}
```

**Comment by ayj** [comment]
This looks like a dup of https://github.com/istio/istio/issues/21676.

**Comment by mbanikazemi** [comment]
@ayj yes it is a duplicate.
