### ISSUE TITLE
Documentation/Support on envoy metrics to monitor Locality Lb

### ISSUE THREAD

**Issue by Stono** [istio/istio#21781]
**Describe the feature request**
Whilst LocalityLb can be enabled very easily, it would be good to have some focus around observability to help the operator do things like:

 - Monitor traffic weightings
 - Detect imbalanced load (due to workloads being in the same region) 

When people have been working on this feature, are there any particular envoy or istio metrics that have helped debug/monitor/observe?  (I know of https://github.com/istio/istio/issues/20235 which needs to be fixed to make them useful)

Thanks!

**Describe alternatives you've considered**

**Additional context**

**Comment by jdotjdot** [comment]
This has been a large problem for us as well
