### ISSUE TITLE
1.5 beta.5 Prometheus Target list shows DOWN endpoint

### ISSUE THREAD

**Issue by kramvan1** [istio/istio#21786]
**Bug description**

1.5-beta.4 using Default profile

![image](https://user-images.githubusercontent.com/5861591/75817075-fdd19780-5d5b-11ea-8399-d08db21fae7a.png)

Prometheus is trying to scrape itself.    I think the addition of the side-car proxy to the prometheus pod has something to do with this.    

Should be able to change the Prometheus configmap filter to avoid this endpoint in the target list.

**Expected behavior**

No DOWN endpoints in Prometheus target list.

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by kramvan1** [comment]
cc @linsun @sdake

**Comment by sdake** [comment]
seems like a duplicate of https://github.com/istio/istio/issues/21786 which is discussed in more detail here: https://github.com/istio/istio/issues/21762#issuecomment-594026530

**Comment by kramvan1** [comment]
yup, dup closing.
