### ISSUE TITLE
meshConfig does not unmarshal in operator controller

### ISSUE THREAD

**Issue by ostromart** [istio/istio#21794]
There was a PR a while back that changes snake_case json Go struct tags to camelCase, to allow regular yaml unmarshal to be used in the controller, rather than jsonpb: https://github.com/istio/api/pull/1277.
This PR did not cover MeshConfig proto, which is in another directory. Therefore, spec.meshConfig fields are ignored in the controller (although it still works fine for istioctl which still uses jsonpb).
Possible solutions would be to run the fixup code on the generated structs to change the struct tags in MeshConfig, or go back to using jsonpb to unmarshal in the controller.

**Comment by ostromart** [comment]
cc @morvencao

**Comment by ostromart** [comment]
Actually after thinking about this for a bit, we have a workaround, which is not great but acceptable until we can patch - we can advise the users to use snake_case if they need to set anything in the meshConfig field.

**Comment by morvencao** [comment]
Not sure if changing the json tags of MeshConfig will have some impact to the networking components, if no, we can do that, right?

**Comment by ostromart** [comment]
i doubt anything in networking is relying on those tags. istio components like pilot read and use meshconfig settings so if snake case is required to do this it will show up very quickly in various test failures. yes, i think it is a safe change.
