### ISSUE TITLE
istioctl kube-inject: unhelpful error message

### ISSUE THREAD

**Issue by ahmetb** [istio/istio#218]
I accidentally executed 

    istioctl kube-inject -f bookinfo.yaml

in the wrong directory (the yaml in subject doesn't exist here). Got error:

    Error: specify --hub or define MANAGER_HUB

It's cryptic and not particularly helpful.

**Comment by mukundha** [comment]
I have the yaml in the directory, but get the same error

**Comment by andraxylia** [comment]
Can you please source the file istio.VERSION ?

**Comment by ahmetb** [comment]
@andraxylia It's not clear in BookInfo Tutorial (https://istio.io/docs/samples/bookinfo.html) (or anywhere else) that the `istio.VERSION` file should be sourced in the shell at all times.

If this is a requirement, please document it.

**Comment by andraxylia** [comment]
Fixed the doc in istio/istio.github.io#151
