### ISSUE TITLE
Remove use of direct pod IP usage from multicluster configuration and docs

### ISSUE THREAD

**Issue by ayj** [istio/istio#21817]
The single-network multicluster configuration and documentation recommends using pod IPs to expose Istio services to remote clusters. This is a bad practice that we should not recommend to users. 

Quoting @costinm,

> Using the pod IPs should not even be mentioned in any doc. It's bad even for demos.
> 
> I think we should just link to the K8S Service documentation, and let people manage the Service, Gateway and VirtualService explicitly, as they do for their own applications. We just need to document the labels and ports that the Service must use to select istio:gateway deployments.
> 
> From operational perspective, users should not need to reinstall istio ( istioctl apply with cluster privs) if they just need to expose a port or create internal load balancer. Fortunately this kind of operation is well known to users, all we need is explain the ports and integration points.

**Comment by howardjohn** [comment]
cc @nmittler @tbarrella I think this is either done or will be done soon by one of you

**Comment by tbarrella** [comment]
Yeah, looking at https://istio.io/latest/docs/setup/install/multicluster/shared/ it looks like not using pod IPs is done (unless this is recommended in other docs)

For the second part of what costinm said, yeah this is being tracked in #25933

**Comment by howardjohn** [comment]
Thanks! lets close since its a duplicate
