### ISSUE TITLE
Istio 1.4 Operator Controller deleting all Istio CRDs when ICP is deleted

### ISSUE THREAD

**Issue by kramvan1** [istio/istio#21827]
**Bug description**

Istio 1.4 Operator Controller deleting all Istio CRDs when ICP is deleted.
This will cause ALL the customers Istio based resources to also be deleted.

The Istio 1.5 Operator Controller does not seem to delete the CRDs when the IOP is deleted.

**Expected behavior**

Always leak CRDs.

**Steps to reproduce the bug**

- Install Istio with Operator Controller pod with default profile in ICP.
- `kubectl get crd` all the Istio CRDs are there
- `kubectl delete icp -A -all` delete the ICP
- `kubectl get crd` all the Istio CRDs are gone along with any resources based upon those.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by kramvan1** [comment]
cc @sdake @linsun

**Comment by linsun** [comment]
@kramvan1 I discussed this issue on environment WG extensively yesterday.

1. Could you try upgrading operator to 1.5 first then apply the new istio operator yaml?  You should be able to use istioctl operator cmd to install the new operator.   

2. you can use `istioctl manifest migrate` cmd to migrate your prior ICP resource to IO resource.

3. Apply that new IO resource.  The IO resource should be delta of the new default profile assuming your old 1.4's ICP is delta of the 1.4 default profile.

4. The IO operator should clean up old resources.  Please let us know how that goes.

cc @ostromart @howardjohn @sdake pls correct me if I'm off here based on the discussion.

**Comment by kramvan1** [comment]
@linsun   Humm, we are using the normal operator controller pod upgrade path via OLM.   This is all controller pod based, there is no `istioctl` CLI or manual commands involved in this upgrade process.

Our process is something like this:
- OLM subscription is to the istio 1.4 channel (will get all 1.4.x operator updates)
- existing istio 1.4 operator controller pod is running 
- existing istio 1.4 ICP is present
- 1.4 control plane is up
- upgrade triggered via OLM subscription to new 1.5 channel.  This tells OLM to switch to use the new 1.5 istio operator.     At same time, the our custom istio 1.5 IOP is created.
- The 1.4 ICP is deleted **CAUSES CRDs TO BE DELETED**
- The 1.4 operator controller pod is terminated
- The 1.5 operator controller pod is started
- the 1.5 operator controller pod see the IOP and updates control plane to 1.5.

Everything works except for the the 1.4 operator controller bug where it's deleting CRDs and therefore customer resource data based upon those CRDs.

Since this serious bug was fixed in 1.5, I assume it can be back ported to 1.4.   I would you think that not just the upgrade path is broken here, but ANY time the ICP is deleted, the customer will potentially lose data.

**Comment by linsun** [comment]
The 1.4 ICP is deleted CAUSES CRDs TO BE DELETED - is this not an update behavior but a delete behavior because we are using OLM?

cc @brian-avery @dgn @rcernich for input

**Comment by linsun** [comment]
@kramvan1 what if you don't do this step?
```The 1.4 ICP is deleted```

We are hoping the 1.5 operator will clean up 1.4 deployments.

**Comment by kramvan1** [comment]
@linsun the 1.5 operator does not cleanup 1.4 deployments, unless they overlap.
If we don't delete the 1.4 ICP, the 1.4 operator will not delete the 1.4 resources.

OLM only handles the operator pods, not the operator CRs (ICP, IOP).    The 1.4 operator is doing the delete of the CRDs when it see the ICP being deleted.    Deleting the ICP is a normal step when the operator changes it's CRD (ICP to IOP) and the new operator does not handle the old CR (ICP in this case).

**Comment by linsun** [comment]
Thank you @kramvan1 to confirm that.

Upon further discussion with @sdake and @kramvan1 we think we should backport the change from 1.5 to 1.4 that allows CRD not cleaned up upon ICP deletion because CRD is cluster wide.

@sdake started a backport PR on this https://github.com/istio/operator/pull/768

cc @ostromart

**Comment by howardjohn** [comment]
fixed in https://github.com/istio/operator/commit/3bf9ba540a4eedcda733279e4087a86c80913c10
