### ISSUE TITLE
Remove citadel deployment

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#21831]
The security WG has decided we will remove citadel in favor of Istiod in 1.6.

Blocker: https://github.com/istio/istio/issues/21824, mixer+galley still depend on Citadel for control plane security.

**Comment by esnible** [comment]
cc @mbanikazemi

**Comment by howardjohn** [comment]
https://github.com/istio/istio/pull/21837 is WIP that does this to see what breaks

**Comment by howardjohn** [comment]
done
