### ISSUE TITLE
Remove file mounted certificates in 1.6

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#21834]
Security WG has decided we will remove support for file mounted certs directly by envoy. Certs will be read from local files an served over SDS to support external CA cases.

This does NOT apply to dest rule/gateway certs, which are currently an entirely different code path. See https://github.com/istio/istio/issues/21833 for that issue

**Comment by esnible** [comment]
cc @mbanikazemi

**Comment by JimmyCYJ** [comment]
cc @myidpt

**Comment by howardjohn** [comment]
This is done
