### ISSUE TITLE
Serve Destination rule/gateway file mounted certificates over SDS

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#21833]
Currently if certs are used as mounted files for destination rule or Gateway, they are loaded as files. This means if they are changed Envoy will not notice.

We have two options:
* Do the same rotation we do with the workload certs. This is complicated as the files are dynamic, and we are moving away from file mounted certs
* Translate the files to SDS config which are served locally

The 2nd seems preferable. There is some complexity here, as we need some way to map the file name referenced in the config to the secret name in envoy (maybe its as simple as literally using the file path). We also need to consider any security implications here, if any

**Comment by howardjohn** [comment]
This is actually pretty much a pre-req for https://github.com/istio/istio/issues/21834, otherwise we are going to break ALS and `envoy_metrics_service`

**Comment by incfly** [comment]
If I read correctly, do you mean without this, in 16 DestinationRule file referenced file is broken to be used? I think they're totally separated stuff. Customer manage their external certs mouting, what WG trying to deprecated (II think correctly), is the internal spiffe cert?

Just confused about the need of doing this transformation...

**Comment by howardjohn** [comment]
This is trying to solve

* DestinationRule file mounts have no cert rotation, since they are file mounted and dynamic, so we don't watch for them
* Other things like ASL have rotation, but are using file mounted rotation, so we need to keep around all of the hot restart logic for them

**Comment by incfly** [comment]
ASL, access logging service, what tls cert options we provide to them? I
searched and only see
https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/accesslog/v2/als.proto

How user configure them today in Istio to get the rotatable key/cert pair
for ALS?

**Comment by howardjohn** [comment]
In mesh config https://github.com/istio/api/blob/master/mesh/v1alpha1/proxy.proto#L221

**Comment by ramaraochavali** [comment]
Discussed this with @howardjohn offline, adding it here for reference

In addition to destination rules and gateway, file mounted certs can also be specified via `ISTIO_META_***` env vars for both client and server. They get captured in [Metadata](https://github.com/istio/istio/blob/master/pilot/pkg/model/context.go#L389) . Currently the main use case for them is the client certs can be specified in Destination Rules (used to build upstream TLS context for [clusters](https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/cluster.go#L1012)) and Server Certs  are used to build TLS context for [Ingress Listener](https://github.com/istio/istio/blob/master/pilot/pkg/security/model/authentication.go#L175).

Prior this PR, https://github.com/istio/istio/pull/22107 the files specified using those env vars, are watched and Envoy is hot restarted when they change. We need to fix that as well along with Destination Rule and Gateway certs.

**Comment by SuleimanWA** [comment]
I think this is a nice idea.

also one question here: regarding destination rule cert mount, when service A talk to B, And I created DR for service B with tls, where should I mount the cert? to which pod? so DR can read it
