### ISSUE TITLE
Error while sidecar injection and gateway creation

### ISSUE THREAD

**Issue by bharat-gadde** [istio/istio#21852]
**Bug description**
During the pod creation creating: Internal error occurred: failed calling webhook "sidecar-injector.istio.io": Post https://istio-sidecar-injector.istio-system.svc:443/inject?timeout=30s: dial tcp 10.100.205.227:443: connect: no route to host.
During gateway creation: error when creating "test_httpgw.yaml": Internal error occurred: failed calling webhook "pilot.validation.istio.io": Post https://istio-galley.istio-system.svc:443/admitpilot?timeout=30s: dial tcp 10.100.12.36:443: connect: no route to host

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istioctl version --remote -> 
client version: 1.4.6
control plane version: 1.4.6
data plane version: 1.4.6 (3 proxies)

kubectl version ->
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
istioctl manifest apply --set profile=demo

**Environment where bug was observed (cloud vendor, OS, etc)**
On prem kubernetes cluster setup using kubeadm

[istio-system-pods.txt](https://github.com/istio/istio/files/4293594/istio-system-pods.txt)
[kube-apiserver.log](https://github.com/istio/istio/files/4293598/kube-apiserver.log)

**Comment by howardjohn** [comment]
This means the api server cannot reach the pods. This may be from firewall rules, networking issues, etc

**Comment by howardjohn** [comment]
https://github.com/istio/istio/wiki/Troubleshooting-Istio#diagnostics has extensive help on this issue. Please follow the steps there and reopen if you still have issues
