### ISSUE TITLE
in-cluster operator never break reconciling loop 

### ISSUE THREAD

**Issue by morvencao** [istio/istio#21850]
**Bug description**

Deployed the in-cluster operator and create the operator CR, found that operator keep the reconcile, and the status are always `RECONCILING`

```
# kubectl get iop -n istio-system
NAME                        AGE
example-istiocontrolplane   9m29s
# kubectl get iop example-istiocontrolplane  -n istio-system -o yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"install.istio.io/v1alpha1","kind":"IstioOperator","metadata":{"annotations":{},"name":"example-istiocontrolplane","namespace":"istio-system"},"spec":{"profile":"demo"}}
  creationTimestamp: "2020-03-05T08:38:28Z"
  finalizers:
  - istio-finalizer.install.istio.io
  generation: 1
  name: example-istiocontrolplane
  namespace: istio-system
  resourceVersion: "4178"
  selfLink: /apis/install.istio.io/v1alpha1/namespaces/istio-system/istiooperators/example-istiocontrolplane
  uid: 4084d2b4-bf1e-4ff8-a2ee-dc7cd3d8b843
spec:
  profile: demo
status:
  componentStatus:
    AddonComponents:
      status: RECONCILING
    Base:
      status: RECONCILING
    EgressGateways:
      status: RECONCILING
    IngressGateways:
      status: RECONCILING
    Pilot:
      status: RECONCILING
  status: RECONCILING
```

Check the operator logs, looks like that the reconciling loop is always triggered by some others resources, maybe resources created by operator.

[ ] Configuration Infrastructure
[ ] Docs
[ X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by ostromart** [comment]
Fixed in https://github.com/istio/istio/pull/21780.
