### ISSUE TITLE
Do not inject a pod if its already been injected

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#21862]
`istioctl` does this, but not the webhook. This will prevent us from having negative impacts if we accidentally set up overlapping labels with multiple control planes

**Comment by musaprg** [comment]
Hi, is anyone already working on this? If not, I would like to try.

**Comment by howardjohn** [comment]
@musaprg I don't think anyone is, thanks! We should see if we can use the same logic that `istioctl kube-inject` uses so those code bases do not diverge more

**Comment by musaprg** [comment]
Thanks @howardjohn , I will start investigating. At first, let me confirm that I got it correctly, 
- currently `istioctl kube-inject` don't care if sidecar pod is already injected to the target Pod.
- It will impact in some cases, so it should be fixed.

**Comment by howardjohn** [comment]
Yeah I think today the kube-inject command just checks for the presence of
istio-proxy container and does nothing if it's already there. And it
shouldn't ever be double injected in normal cases, but there may be
misconfigurations that cause it. For example, using kube-inject then
deploying to a injection-enabled namespace

**Comment by weibohe** [comment]
FYI this has been addressed in https://github.com/istio/istio/pull/28800
