### ISSUE TITLE
upstream connect error or disconnect/reset before headers when testing bookinfo

### ISSUE THREAD

**Issue by James-Dao** [istio/istio#2187]
k8s: 1.8.5
docker :1.12.6
centos: 7.3
istio: 0.3

when using "kubectl apply -f <(istioctl kube-inject -f samples/bookinfo/kube/bookinfo.yaml)" to testing istio, all deployments are running successful and all serivces is ok, but access the <nodeip>:<ingress-nodeport>/productpage, it return "upstream connect error or disconnect/reset before headers "

**Comment by GregHanson** [comment]
@James-Dao are you still having problems with this issue in istio version 0.5.1 or later?

**Comment by GregHanson** [comment]
closing issue until is can be reproduced in istio 0.5.1 or later
