### ISSUE TITLE
Improve test coverage in operator/pkg/util

### ISSUE THREAD

**Issue by ostromart** [istio/istio#21884]
Currently at 26.7%.

**Comment by kanapuli** [comment]
@ostromart Hi, I can take this up and write tests

**Comment by adiprerepa** [comment]
I wrote some tests in pull request #22920, but It's giving me a lint error for something I have never encountered before. Would someone look at it?

**Comment by Prassud** [comment]
@kanapuli, Shall i pick up this task if this is still open

**Comment by adiprerepa** [comment]
I think coverage is pretty good now.

**Comment by adiprerepa** [comment]
But if you can find stuff, go ahead.

**Comment by kanapuli** [comment]
@Prassud Please go ahead, if you find something can be improved

**Comment by Prassud** [comment]
Thanks @kanapuli @adiprerepa
