### ISSUE TITLE
Consider cleanup global cache `edsClusters`

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#21913]
**Describe the feature request**

As global isolation is enabled for long, and now `pushEds` generates ClusterLoadAssignment from the cached IstioEndpoint directly, and can not use that in `edsClusters` anymore. 

So we should cleanup it, and this will 
1. save a lot of memory. 
2. no need updating this cache anymore each time pushing eds, definitely saves cpu usage

**Describe alternatives you've considered**

**Additional context**

**Comment by hzxuzhonghu** [comment]
cc @rshriram @howardjohn @ramaraochavali

**Comment by howardjohn** [comment]
I tried a while back and wasn't successful, but would be great to see

**Comment by howardjohn** [comment]
No reason it can't be done, I just wasn't able to get everything working right

**Comment by hzxuzhonghu** [comment]
OK, i am working on a draft to see if anything wrong. I have found one point: currently, we donot check service existence when calling edsUpdate.
