### ISSUE TITLE
AuthorizationPolicy for source IP does not work

### ISSUE THREAD

**Issue by catman002** [istio/istio#21916]
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

In istio 1.5.0, using AuthorizationPolicy to configure the attribute "from. Source. Ipblocks" for istio-ingressgateway does not work, because the real IP of the customer cannot be obtained. 

The specific configuration is as follows:
```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
Metadata:
name: ingress-policy
namespace: istio-system
Spec:
Selector:
MatchLabels:
app: istio-ingressgateway
action: ALLOW
Rules:
- from:
- source:
ipBlocks: ["172.0.0.0/8","192.0.0.0/8"]
To:
- operation:
methods: ["POST"]
paths: ["/api/istiotools/*"]
```
How can I solve it  ？ thanks

**Comment by Mokto** [comment]
You should use `externalTrafficPolicy: Local` on your loadbalancer to see the origin IP.

But will not work if you use a classic AWS load balancer.

**Comment by catman002** [comment]
@Mokto 

#### I have configured "external traffic policy: local", but I still can't get the real IP: 
 
######  bash> kubectl edit svc istio-ingressgateway -n istio-system

```
apiVersion: v1
kind: Service
Metadata:
Annotations:
...
...
Spec:
clusterIP: 10.245.161.119
externalTrafficPolicy: Local
Ports:
- name: status-port
nodePort: 23089
Port: 15020
```

**Comment by Mokto** [comment]
How is your kubernetes cluster deployed ?

**Comment by yangminzhu** [comment]
Does the task https://istio.io/docs/tasks/security/authorization/authz-ingress/ work for you? If not, I guess somehow the client IP address is not preserved in your environment.

**Comment by Mokto** [comment]
It does for me.
Note: I had to add my VPC CIDR (10.0.0.0/8)

**Comment by yangminzhu** [comment]
@catman002  It looks like the client IP is not preserved in your environment and the task (https://istio.io/docs/tasks/security/authorization/authz-ingress/) is working as expected. I'm closing this issue as we cannot do much in istio side, feel free to reopen if you found anything else, thanks.
