### ISSUE TITLE
Istio helm installation still uses microservices

### ISSUE THREAD

**Issue by StrongMonkey** [istio/istio#21928]
**Bug description**

Istio helm installation still uses microservices

[ X] Configuration Infrastructure
[X ] Docs
[ X] Installation
[ X] Networking
[ X] Performance and Scalability
[ X] Policies and Telemetry
[ X] Security
[ X] Test and Release
[X ] User Experience
[ X] Developer Infrastructure

**Expected behavior**

From the release doc, starting from istio 1.5 it will be using istiod as one single controlplane instead of splitting into micro-services.

**Steps to reproduce the bug**

Follow docs in https://istio.io/docs/setup/install/helm/ and install istio.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

1.5

**How was Istio installed?**

helm

**Environment where bug was observed (cloud vendor, OS, etc)**

k3s on laptop

**Comment by howardjohn** [comment]
Istiod is only available using the new installation methods (istioctl)
