### ISSUE TITLE
Add completion command to istioctl

### ISSUE THREAD

**Issue by voroniys** [istio/istio#21921]
**Describe the feature request**

Add a completion command to istioctl, same as it is in kubectl

**Describe alternatives you've considered**

To get completion file now I need to download full istio tarball to get it from tools directory. If completion command will be added it would be possible to download istioctl only and setup completion with it.

[ ] Configuration Infrastructure
[ ] Docs
[ X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by esnible** [comment]
This feature already exists but is undocumented.

If you do `istioctl collateral --bash` it will generate _istioctl.bash_ in the current directory.  There are other options.

I had a PR to make it visible, https://github.com/istio/istio/pull/12637 , but I was encouraged to keep it hidden.  I see no reason not to make `istioctl completion bash` output to stdout just like `kubectl`.  However, the previous PR making the existing command visible was rejected.

Please vote :+1: or :-1: on this issue; if there are a lot of up votes I will get this approved and implement it.
