### ISSUE TITLE
All links in 1.4 archive went invalid

### ISSUE THREAD

**Issue by elfinhe** [istio/istio#21935]
All links in 1.4 archive site are missing v1.4 path.

For example, in https://archive.istio.io/v1.4/docs/setup/

Actual:
`https://archive.istio.io/docs/setup/getting-started/`

Expected:
`https://archive.istio.io/v1.4/docs/setup/getting-started/`
 

**Bug description**

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by frankbu** [comment]
Doc issues should be opened in the istio/istio.io repo, but this one not needed anyway, since we already have an issue for the problem: https://github.com/istio/istio.io/issues/6788
