### ISSUE TITLE
Addon components strategy for install / operator API

### ISSUE THREAD

**Issue by ostromart** [istio/istio#21932]
https://docs.google.com/document/d/1LHy4fUDlhQWjsgUC4G4r_SuiBkgRNU_iUr_iJxWwgo8/edit#heading=h.xw1gqgyqs5b
- Document installing from external sources (@howardjohn)
- Evaluate if integration can be done external to istio/istio (@howardjohn, @dgn, others)
- If above two points pass, remove addon charts and addonComponents from API

**Comment by howardjohn** [comment]
Related: https://github.com/istio/istio/issues/21541 https://github.com/istio/istio/issues/21366

If we finish both of these we can get "zero config" integration with Istio

**Comment by dgn** [comment]
currently pending approval: https://docs.google.com/document/d/1jJ4kkALCUPWIlz_Ldu6jpeelMNxyY_SZDMaZmeSpfkM/edit

**Comment by dgn** [comment]
Docs part moved to https://github.com/istio/istio/issues/22785 - the remainder of this issue is not P0 for 1.6
