### ISSUE TITLE
Dual control plane upgrade support

### ISSUE THREAD

**Issue by ostromart** [istio/istio#21934]
Umbrella issue to capture work to support dual control plan upgrade. Some work will be in the installer charts, some UX changes may also be appropriate. Pending a more detailed design for 1.6.
https://docs.google.com/document/d/1d1z5PC8wvh9QiR3NesAaPm6w2HnE4-KIfjB7GB-_Wf8/edit#heading=h.qlmnvhzb2ib2
https://docs.google.com/document/d/1yxoQNfWgNFFPgyGHGvpTMN_Xy6KAoq57O2U8Wx0Nv8A/edit#heading=h.qex63c29z2to
Actual work items should refer back to this issue.

**Comment by esnible** [comment]
In the approved "Multiple Control Planes" document a workflow involving `--set global=true` is shown:

```
$ apply istio-1.5.0 --set revision stable --set global=true
...
# Because I made this the "global" deployment, I also get service: istiod.
```

During one of the UX working groups I asked if this field was in IstioOperatorSpec and I learned it was not yet present.  Can someone from Environments **Create an Issue in istio/api** to create that field?

(I am not thrilled with the `global` key name; we use `global` elsewhere, and it is hard to search for `global` in docs.  Please consider using `--set default-istio=false`, or `--set master-istio-controlplane=false`.  (The default should be true, and the name should be chosen for understandability/searchability)).

**Comment by esnible** [comment]
@ostromart I notice that when I supply `--set revision=foo` the name `foo` makes it into the Ingress through _manifests/gateways/istio-ingress/templates/deployment.yaml_ doing `service.istio.io/canonical-revision: {{ .Values.revision }}`

To support multiple control planes the troubleshooting subcommands of _istioctl_ need to find the correct Pilot.  That means we need to label Istiod.  I did not see anything to set the revision in _manifests/istio-control/istio-discovery/files/gen-istio.yaml_.  Is there a work item?

**Comment by howardjohn** [comment]
Its added by istioctl at runtime

**Comment by howardjohn** [comment]
We may need to change that to include it in the templates though, but thats
how it works for now.

**Comment by esnible** [comment]
Related: https://github.com/istio/istio/issues/19860

**Comment by esnible** [comment]
@howardjohn The Istiod I created from master today did not have these labels.  Has this been merged?  Is this part of https://github.com/istio/istio/pull/22056 ?

**Comment by esnible** [comment]
@ostromart My comment https://github.com/istio/istio/issues/21934#issuecomment-598754147 .  Is there API support for selecting the "global" control plane?

**Comment by esnible** [comment]
@ostromart 
The "Istio Installer Experience" doc is pretty old, replace it with [UX For Multiple Control Planes](https://docs.google.com/document/d/1ecMIxUBgp5VDFqrBuu1ofyTHCwDKU1hWSLhewNKWIi4/edit#).

**Comment by esnible** [comment]
Is there a Docs issue for dual control plane?

I tried https://preliminary.istio.io/docs/setup/additional-setup/sidecar-injection/ today and it won't work if `revision` is set.

cc @istio/wg-docs-maintainers

**Comment by howardjohn** [comment]
I think this can be considered complete in 1.6
