### ISSUE TITLE
Get HTTP/1.1 to Beta

### ISSUE THREAD

**Issue by nmittler** [istio/istio#2194]
Applicable criteria for Beta (from [Istio Schedule: Phase Definition tab](https://docs.google.com/spreadsheets/d/1mUIrX82Z8mRuhNWyl5D_sd_Evg3KzeNotzRorPzQMko/edit?ts=5a03f88d#gid=44562378)):

Stability
-----------

- **Description**
  - "Code is well tested. Enabling the feature is considered safe. Enabled by default."
- **Approach:**
  - Create (or identify existing) e2e/integration test that:
    - Runs on k8s (GKE?)
    - Uses a client and server that both communicate over HTTP/1.1
    - Verify that the expected attributes are sent to mixer
    - Test that L4 and L7 route rules work when used together

Performance
-----------------
- **Description**
  - "Performance and scalability are characterized, but may have performance caveats."
- **Approach**
  - **TBD:** Need to identify the following:
    - Who will do this work? (@ldemailly any thoughts?)
    - What will we measure? With vs without mixer? Tcp rules vs http rules vs both?

Documentation
--------------------
- **Description**
  - "Complete feature documentation published to istio.io. In addition to the basic alpha-level documentation, beta documentation includes samples, tutorials, glossary entries, etc."
- **Approach**
  - **TBD:** Need to identify completion criteria for documentation.  For example, is just enumerating the list of supported protocols on the homepage sufficient? Regardless, some update will need to be made to the [feature status page](https://istio.io/about/feature-stages.html).

Add @jasminejaksic as approver for resulting PRs.

When this issue is resolved, update the [Istio Schedule](https://docs.google.com/spreadsheets/d/1mUIrX82Z8mRuhNWyl5D_sd_Evg3KzeNotzRorPzQMko/edit?ts=5a03f88d#gid=351491887) accordingly.

**Comment by nmittler** [comment]
@smawson Could you provide an example of testing L4 and L7 route rules together?  More specifically, could you provide an example of which rules might be used and how the system might be set up to test the combination?

**Comment by kyessenov** [comment]
Btw, as I mentioned multiple times, Envoy treats http/1.1 and h2c exactly the same. It's the same library. I'd actually expect h2c be better tested in production at lyft.

**Comment by ldemailly** [comment]
http1.1 and h2 are very different so even if one is converted to the other inside envoy, that doesn't mean they work the same for the services

re performance test, yes characterizing h1.1 is what the WG is doing first

**Comment by smawson** [comment]
I didn't mean l4/l7 route rules, I meant other types of rules.

I.e. can I set a per-connection acl and also set a per-request rate limit, does that work properly?

What about collecting per-connection metrics as well as per-request metrics?

Things like that.

**Comment by nmittler** [comment]
@douglas-reid any thoughts on how we might verify attributes sent to Mixer?  Would it be easiest to use a fake mixer?  Perhaps you have some sample tests handy?

**Comment by kyessenov** [comment]
There's a fake mixer I wrote
https://github.com/istio/old_pilot_repo/tree/master/test/mixer
It got removed as part of mono-repo move since it was causing build
problems, but you can take it as a starting point.

**Comment by douglas-reid** [comment]
There is also an AttributesServer mixer somewhere in the mixer/ subdirectory (it has been moved a few times). It was created for istio/proxy's integration testing.

**Comment by qiwzhang** [comment]
istio/proxy is using fake mixer server from mixer/pkg/mockapi

Its integration tests in src/envoy/mixer/integration_test are testing attributes send to mixer

**Comment by nmittler** [comment]
> There is also an AttributesServer mixer somewhere in the mixer/ subdirectory (it has been moved a few times). It was created for istio/proxy's integration testing.

Ok cool ... that sounds promising, thanks!

To make these true e2e tests, would it be possible to use a real mixer, but have its output sent to a webserver running within the test class? I assume that would require egress rules, etc. ... but is it feasible? I imagine this sort of thing could be useful for all of our e2e tests?

**Comment by nmittler** [comment]
Alternatively, the output of mixer could be a webserver that supports scraping the mixer output.

**Comment by kyessenov** [comment]
Depends on how much you want to test in one-go. If you want envoy +
kubernetes + real mixer + backends, that would be the entire system, and
you'll have to deal with all the flakiness. If you just want to test the
protocol, then using envoy + fake mixer seems like the right approach.

**Comment by nmittler** [comment]
@kyessenov makes sense. Do you suggest using k8s at all or just running everything locally?

**Comment by ldemailly** [comment]
the idea (I believe) behind http 1.1 beta is beta in [real] k8s; with no 404/503 during normal operations. I don't think tests without the real components would demonstrate/achieve that

**Comment by nmittler** [comment]
@ldemailly sgtm, thanks!

**Comment by kyessenov** [comment]
Right, k8s, being a loosely coupled and non-det system, needs to be modeled
correctly in your tests. It might be easier to just run real k8s instead of
modeling.

**Comment by nmittler** [comment]
@qiwzhang Thanks for the reference to istio/envoy!  Just for book keeping, here's what you're referring to: https://github.com/istio/proxy/blob/master/src/envoy/mixer/integration_test/mixer_server.go

**Comment by qiwzhang** [comment]
It is Istio/proxy.    

Yes, that mixer_server is using the mock mixer server from
https://github.com/istio/istio/blob/master/mixer/pkg/mockapi/server.go
