### ISSUE TITLE
Get HTTP/2 to Beta

### ISSUE THREAD

**Issue by nmittler** [istio/istio#2195]
Applicable criteria for Beta (from [Istio Schedule: Phase Definition tab](https://docs.google.com/spreadsheets/d/1mUIrX82Z8mRuhNWyl5D_sd_Evg3KzeNotzRorPzQMko/edit?ts=5a03f88d#gid=44562378)):

Stability
-----------

- **Description**
  - "Code is well tested. Enabling the feature is considered safe. Enabled by default."
- **Approach:**
  - Create (or identify existing) e2e/integration test that:
    - Runs on k8s (GKE?)
    - Uses a client and server that both communicate over HTTP/2
    - Verify that the expected attributes are sent to mixer
    - Test that L4 and L7 route rules work when used together

Performance
-----------------
- **Description**
  - "Performance and scalability are characterized, but may have performance caveats."
- **Approach**
  - **TBD:** Need to identify the following:
    - Who will do this work? (@ldemailly any thoughts?)
    - What will we measure? With vs without mixer? Tcp rules vs http rules vs both?

Documentation
--------------------
- **Description**
  - "Complete feature documentation published to istio.io. In addition to the basic alpha-level documentation, beta documentation includes samples, tutorials, glossary entries, etc."
- **Approach**
  - **TBD:** Need to identify completion criteria for documentation.  For example, is just enumerating the list of supported protocols on the homepage sufficient?  Regardless, some update will need to be made to the [feature status page](https://istio.io/about/feature-stages.html).

Add @jasminejaksic as approver for resulting PRs.

When this issue is resolved, update the [Istio Schedule](https://docs.google.com/spreadsheets/d/1mUIrX82Z8mRuhNWyl5D_sd_Evg3KzeNotzRorPzQMko/edit?ts=5a03f88d#gid=351491887) accordingly.

**Comment by ldemailly** [comment]
for perf: https://github.com/istio/istio/issues/452

**Comment by louiscryan** [comment]
In general we think HTTP2 works pretty well end to end. Certainly well enough for regular usage
