### ISSUE TITLE
Get gRPC to Beta

### ISSUE THREAD

**Issue by nmittler** [istio/istio#2196]
Applicable criteria for Beta (from [Istio Schedule: Phase Definition tab](https://docs.google.com/spreadsheets/d/1mUIrX82Z8mRuhNWyl5D_sd_Evg3KzeNotzRorPzQMko/edit?ts=5a03f88d#gid=44562378)):

Stability
-----------

- **Description**
  - "Code is well tested. Enabling the feature is considered safe. Enabled by default."
- **Approach:**
  - Create (or identify existing) e2e/integration test that:
    - Runs on k8s (GKE?)
    - Uses a client and server that both communicate over gRPC
    - Verify that the expected attributes are sent to mixer
    - Test that L4 and L7 route rules work when used together

Performance
-----------------
- **Description**
  - "Performance and scalability are characterized, but may have performance caveats."
- **Approach**
  - **TBD:** Need to identify the following:
    - Who will do this work? (@ldemailly any thoughts?)
    - What will we measure? With vs without mixer? Tcp rules vs http rules vs both?

Documentation
--------------------
- **Description**
  - "Complete feature documentation published to istio.io. In addition to the basic alpha-level documentation, beta documentation includes samples, tutorials, glossary entries, etc."
- **Approach**
  - **TBD:** Need to identify completion criteria for documentation.  For example, is just enumerating the list of supported protocols on the homepage sufficient?  Regardless, some update will need to be made to the [feature status page](https://istio.io/about/feature-stages.html).

Add @jasminejaksic as approver for resulting PRs.

When this issue is resolved, update the [Istio Schedule](https://docs.google.com/spreadsheets/d/1mUIrX82Z8mRuhNWyl5D_sd_Evg3KzeNotzRorPzQMko/edit?ts=5a03f88d#gid=351491887) accordingly.

**Comment by ldemailly** [comment]
for perf: https://github.com/istio/istio/issues/526

**Comment by ldemailly** [comment]
for grpc and https https://github.com/istio/admin-sites/pull/54

**Comment by liukgg** [comment]
How about this issue now?

**Comment by ldemailly** [comment]
fortio 0.9 (released last week) has a lot of improvements related to grpc testing that can be used for functional testing in addition to the performance ones

**Comment by liukgg** [comment]
Thanks for your reply. I'll have a look at fortio. 👍

**Comment by louiscryan** [comment]
Generally speaking GRPC works well with Istio. A number of fixes have gone into Envoy and changes to how we deliver config have eliminated much instability.

We'd like some more test coverage but that is the primary gap today. Dropping to P1
