### ISSUE TITLE
Istio Vault integration

### ISSUE THREAD

**Issue by lei-tang** [istio/istio#21961]
**Describe the feature request**
Since Istio 1.3 uses a new Kubernetes JWT, Istio Vault integration is no longer supported. We plan to add the support of Vault integration to Istio (the timeline is to be determined).

Please feel free to share your use cases for Vault integration. We hope to collect use cases of Vault integration and provide a solution meeting the requirements of representative use cases.

**Describe alternatives you've considered**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by richardmcsong** [comment]
We've automated our multicluster meshing strategy with istio, and we're looking to include cross cluster mTLS. We would like our shared root CA to be vault, and we would like the certs to be provisioned on runtime via a vault API call.

**Comment by hobbytp** [comment]
Is there any roadmap to support this integration? in 1.6 or 1.7? thanks

**Comment by lei-tang** [comment]
> @lei-tang Is there any plan to support this integration? as in 1.6 or 1.7? thanks

cc @myidpt

**Comment by myidpt** [comment]
I think we will discuss the support for this in the security WG meeting this week.

**Comment by infa-ddeore** [comment]
private CA cert and keys will remain in vault which is more secured compared to storing the same in k8 istio-system/cacerts secret

**Comment by tmshort** [comment]
We use Vault for SDS in 1.4 and 1.5, and use Vault to provide cross-cluster and outside-of-cluster CAs.

**Comment by infa-ddeore** [comment]
> We use Vault for SDS in 1.4 and 1.5, and use Vault to provide cross-cluster and outside-of-cluster CAs.

how are you using vault with istio?

**Comment by tmshort** [comment]
> how are you using vault with istio?

Vault is our CA for istio, via SDS. It maintains the private keys for the CA, and signs CSRS. Similar to what you responded with. Users external to istio use vault to get application/personal certificate to authenticate themselves to istio.

**Comment by emike922** [comment]
> Vault is our CA for istio, via SDS. It maintains the private keys for the CA, and signs CSRS. Similar to what you responded with. Users external to istio use vault to get application/personal certificate to authenticate themselves to istio.

May I ask how you configured Istio to use Vault as its CA? Are you already using the Istiod-based 1.5?

**Comment by tmshort** [comment]
We currently deploy istio 1.5 with the "legacy" helm charts. The instructions can be found in the istio 1.4 documentation, which still apply with the legacy helm charts, and may still work with the `values` section in the istio operator (although we haven't tried). We've been using the same SDS/Vault configuration since istio 1.3.6. We are looking to move to the operator in 1.6, but have not made that leap yet.

**Comment by tmshort** [comment]
There are definitely tests for vault integration, and they pass per the build. See:
https://github.com/istio/istio/tree/release-1.6/security/pkg/nodeagent/caclient/providers/vault
https://github.com/istio/istio/tree/release-1.6/security/pkg/adapter/vault
https://github.com/istio/istio/tree/release-1.6/tests/integration/security/sds_vault_flow

 They seem to want "nodeagent" configuration, which fails validation in the IstioOperator config. See:

https://github.com/istio/istio/blob/2511ab8c8c59a203e77bb804846593c3690fcf4a/tests/integration/security/sds_vault_flow/main_test.go#L81

**Comment by tmshort** [comment]
I have since discovered that the istio 1.6 `pilot-agent` code does not pull in any certificate provider code other than Citadel. This means that Vault and Google CAs no longer work. We have Vault working with 1.5, and cannot migrate to 1.6 because of the lack of Vault support.

**Comment by k** [comment]
Is this resolved in 1.7? @tmshort

**Comment by tmshort** [comment]
We have just moved to 1.6, and have not tried 1.7 yet, which won't be for a while.

**Comment by tmshort** [comment]
Is there documentation anywhere that I can at least look at?

**Comment by myidpt** [comment]
@tmshort Here's the design for Istio to integrate with custom CAs: https://docs.google.com/document/d/1KAw8-0FivdYQAcWMVTMl-JYvVCn2fpNTbu6Ya3y9d1E/edit#heading=h.se6wjxq9mtpk
For Vault, the basic idea is that you can develop an adapter to implement the Istio CSR proto and interacts with Vault. Or you can choose to leverage the K8s CSR API / cert-manager (in the future) for the integration.

**Comment by tmshort** [comment]
Scanning through the document, it does not appear to be an API spec and is still "In Review". There is still a "Proposed Integration Model" section that has not been whittled down to the actual integration model.
I have to say that the istio.io documentation has gone downhill; it is not being kept up-to-date as much as it should (there still seems to be a lot of old references about citadel, etc.). And the definitions of kubernetes resources provide field-by-field information in tables, but don't really provide a good starting point to understand the resources. I fear that this API will not be documented on istio.io well.

**Comment by tmshort** [comment]
> Is this resolved in 1.7? @tmshort

Considering that I apparently have to write my own connector, and that 1.7 was released last week, I really haven;t had the time to even attempt to do try this.

**Comment by jonmoter** [comment]
My understanding is there's no officially supported integration between Istio and Vault, the way there was in Istio 1.2 and earlier.  There's some work being done, and it's probably possible to cobble together an integration, but it's not supported end-to-end.

FWIW, we're taking an approach where we're storing the Root CA for Istio in Vault, and then have scripts that use Vault's API to generate an intermediate CA from the Root CA, and store that intermediate CA's private key as a Kubernetes secret that istiod can use.

That's not ideal, and we'd prefer a strategy where the CA's private key only exists in Vault, and Vault handles signing the certs via API.  But that's the compromise we've taken for now.

**Comment by tmshort** [comment]
@jonmoter who is "we"? Are you talking istio or your own organization?

We have used the vault integration in istio from 1.3 through 1.5. In 1.6, we hacked back the vault integration code (since it basically exists in the tree) in a manner similar to the GoogleCa within the pilot-agent.

Our current vault setup has a root CA within vault that also have an intermediate CA that stays on vault that signs the CSRs provided by istio. Our preferred integration would be to not require a signing intermediate on kubernetes, but prefer to have all that done on vault so that all certificates can be tracked/logged/audited there. Our vault instances does not sign a certificate that is marked as an (intermediate) CA; only a leaf certificate.

This is how prior vault integrations with istio worked (i.e. root and intermediate were kept on vault), and it would be a loss of functionality (and in some people's minds, security) to have a signing CA within the cluster.

**Comment by myidpt** [comment]
@tmshort instead of hacking the istio-agent code to support Vault integration, I think a better model would be developing an adapter that can consume the Istio CSR API https://github.com/istio/api/blob/master/security/v1alpha1/ca.proto and then converts the requests to Vault-specific. Then the adapter will be stable since the Isito CSR API is stable. You just need to configure the endpoint of the upstream CA on the istio-agent.

**Comment by tmshort** [comment]
> @tmshort instead of hacking the istio-agent code to support Vault integration, I think a better model would be developing an adapter that can consume the Istio CSR API https://github.com/istio/api/blob/master/security/v1alpha1/ca.proto and converts the requests to Vault-specific. Then the adapter will be stable since the Isito CSR API is stable. You just need to configure the endpoint of the upstream CA to be the adapter on the istio-agent.

Um, by definition a v1alpha1 API is not stable. When will it become a v1betaX API?

**Comment by misiektoja** [comment]
Hi,

We're trying to find a way to integrate an external CA with Istio to provide workload certificates. The main problem which has been raised by some of our customers is related to the fact CA private keys are not stored securely and expectation is to have it on HSMs. We already developed external issuer for cert-manager which gets all the certificates from HSM-secured CAs, but I have hard time finding any supporting documentation to do sth similar for Istio Envoy sidecars. The only lead is the Vault CA integration guide I found on Istio webpage and this thread (+ some discussions on cert-manager github). I sent request to access the design document referenced earlier, would appreciate it is accepted, however has anybody considered integration with cert-manager ? Point is it already supports so many external issuers (Vault included) and it is somehow becoming a standard to provide certificates in k8s. Plus coming up with your own external issuer is rather easy. I can see cert-manager team was actually discussing this (issues 2377, 2456, 2894), but it does not seem to progress. Was there any discussion between Istio & cert-manager teams on this ? Point is if Istio is integrated with cert-manager it automatically opens it to all of the CA issuers supported there. Any thoughts on this ?

**Comment by incfly** [comment]
Re-route to @shankgan since he's working on external CA integration. We just need a plan of recorded here to indicate how we plan to support Vault integration.

**Comment by shankgan** [comment]
One of the challenges with external CA integration has been finding a **common way** to integrate with multiple external Certificate Authorities (Let's encrypt/Vault/Venafi etcetera) that negate the need to maintain private signing keys in the K8s Cluster. Maintaining separate code for integration in each case is a challenging ordeal. Would be interested to hear of any common API/protocols that are currently in use by multiple enterprise + web CAs ?

There are RFCs that have attempted to standardize the interaction protocol with CAs (Refer https://tools.ietf.org/html/rfc8555). However, implementing them is not very useful until they are widely adopted by a majority of CA's.

In addition to what @myidpt mentioned above (building adaptors between the Istio CSR API and the external CA), 
there is an experimental feature that will be released in Istio 1.8 that allows signing of  Istio workload certificates by custom CA's that interface with the Kubernetes CSR API - https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/. However, this does require *Kubernetes version >= 1.8*. With this feature, external CA's will need to build a Kubernetes Controller to read and sign CSR Requests. One such reference implementation that allows integration with venafi appears to be available here - https://github.com/cert-manager/signer-venafi.

**Comment by shankgan** [comment]
Keeping this issue open at-least until we find a satisfactory way of integrating with custom CA's using Istiod as an RA

**Comment by agrawroh** [comment]
We have a similar use-case where we don't want to mount our Root CA certificate & keys in the `istio-system` namespace and would like to get all our workload certificates issued via vault instead.
