### ISSUE TITLE
istio 1.5 manifest generation vs manifest apply, with generated manifest pods will not be created...

### ISSUE THREAD

**Issue by prageethw** [istio/istio#21968]
**Bug description**
`istioctl manifest apply` and `istioctl manifest generate` create inconsistent results, pods stuck in create state claiming volume mounting issue.

[ x] Configuration Infrastructure
[ x] Docs
[x ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
I expects both the above commands to create a consistent istio control panel, pods should be up and running in control panel in both methods.

**Steps to reproduce the bug**
install istio in k8s cluster using,

`istioctl manifest apply --set profile=demo`

```
kubectl get po -n istio-system
NAME                                   READY   STATUS    RESTARTS   AGE
grafana-78bc994d79-4z9xk               1/1     Running   0          20s
istio-egressgateway-7c9f7d5bd6-qndt8   1/1     Running   0          40s
istio-ingressgateway-f9b47d445-nz2nz   1/1     Running   0          39s
istio-tracing-c7b59f68f-jw8x8          1/1     Running   0          19s
istiod-5745bd5f6b-dqglw                1/1     Running   0          55s
kiali-57fb5bb5c6-xlhwz                 1/1     Running   0          18s
prometheus-78f785fc6b-9dvtj            2/2     Running   0          17s
```

install istio in k8s using,
```
istioctl manifest generate --set profile=demo>istio-demo-profile.yaml
kubectl apply -f istio-demo-profile.yaml
```

```
kubectl get po -n istio-system

grafana-78bc994d79-5hlpq                1/1     Running             0          6m49s
istio-egressgateway-56ff7d69f-h5vd9     0/1     ContainerCreating   0          7m35s
istio-ingressgateway-85b4b55bd6-dr7xb   0/1     ContainerCreating   0          7m29s
istio-tracing-c7b59f68f-xxlvj           1/1     Running             0          6m38s
istiod-5965b484f5-jrgw9                 0/1     ContainerCreating   0          7m18s
kiali-57fb5bb5c6-sxkgg                  1/1     Running             0          6m41s
prometheus-868cf4cb84-4sznh             0/2     ContainerCreating   0          6m38s

kubectl get events -n istio-system

52s         Warning   FailedMount              pod/prometheus-868cf4cb84-2mwwt                  MountVolume.SetUp failed for volume "istiod-ca-cert" : configmap "istio-ca-root-cert" not found
11m         Warning   FailedMount              pod/prometheus-868cf4cb84-2mwwt                  MountVolume.SetUp failed for volume "prometheus-token-grc4z" : couldn't propagate object cache: timed out waiting for the condition
11m         Warning   FailedMount              pod/prometheus-868cf4cb84-2mwwt                  MountVolume.SetUp failed for volume "config-volume" : couldn't propagate object cache: timed out waiting for the condition
4m53s       Warning   FailedMount              pod/prometheus-868cf4cb84-2mwwt                  MountVolume.SetUp failed for volume "istio-token" : failed to fetch token: the server could not find the requested resource
6m47s       Warning   FailedMount              pod/prometheus-868cf4cb84-2mwwt                  Unable to mount volumes for pod "prometheus-868cf4cb84-2mwwt_istio-system(7f2afdf8-604d-4e05-965f-12a1ecd8db92)": timeout expired waiting for volumes to attach or mount for pod "istio-system"/"prometheus-868cf4cb84-2mwwt". list of unmounted volumes=[istio-token istiod-ca-cert]. list of unattached volumes=[config-volume istio-certs istio-envoy istio-token istiod-ca-cert prometheus-token-grc4z]
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
istioctl version --remote
client version: 1.5.0
control plane version: 1.5.0
data plane version: 1.5.0 (3 proxies)
```
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-13T18:08:14Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.9", GitCommit:"2e808b7cb054ee242b68e62455323aa783991f03", GitTreeState:"clean", BuildDate:"2020-01-18T23:24:23Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

refer above

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
please see https://istio.io/docs/ops/best-practices/security/#configure-third-party-service-account-tokens

**Comment by RichardKnowles** [comment]
So to run on minikube, where istioctl falls back to third party jwt, we need:

```
istioctl manifest generate --set profile=demo --set values.global.jwtPolicy=third-party-jwt
```

**Comment by RichardKnowles** [comment]
For running on minikube for testing, setting first party jwt is working:

```
istioctl manifest generate --set profile=demo --set values.global.jwtPolicy=first-party-jwt
```

**Comment by howardjohn** [comment]
Yes, that should do it

**Comment by prageethw** [comment]
> please see https://istio.io/docs/ops/best-practices/security/#configure-third-party-service-account-tokens

Thanks @howardjohn @RichardKnowles

**Comment by harpratap** [comment]
@howardjohn Shouldn't the demo profile at least be consistent? Why should `istioctl manifest apply --set profile=demo` give different cluster state from `istioctl profile dump demo > demo.yaml && istioctl manifest apply -f demo.yaml` ? It's not good for developer experience

**Comment by howardjohn** [comment]
@harpratap good question. `manifest apply` requires access to the cluster so it can do inspection of the k8s cluster. `generate` may be generated with a different kube context than it is applied to, so we cannot safely inspect the cluster to determine defaults

**Comment by DickChesterwood** [comment]
I think the real bug here, and the reason this is jarring, is that the message given is misleading:

> Detected that your cluster does not support third party JWT authentication. **Falling back to less secure first party JWT**. See https://istio.io/docs/ops/best-practices/security/#configure-third-party-service-account-tokens for details.

But it doesn't fall back to first party JWT, at least when doing a "istioctl manifest generate", or if you're doing "istioctl manifest apply -f". 

It does seem to work ok if you're just doing a bare "istioctl manfest apply" with no input file however.

**Comment by DickChesterwood** [comment]
Sorry I was working with 1.5.0. It seems the message is no longer displayed in 1.5.1, but it is still necessary to force first-party-tls, otherwise the pods stick as before.
