### ISSUE TITLE
Get TCP to Beta

### ISSUE THREAD

**Issue by nmittler** [istio/istio#2197]
Applicable criteria for Beta (from [Istio Schedule: Phase Definition tab](https://docs.google.com/spreadsheets/d/1mUIrX82Z8mRuhNWyl5D_sd_Evg3KzeNotzRorPzQMko/edit?ts=5a03f88d#gid=44562378)):

Stability
-----------

- **Description**
  - "Code is well tested. Enabling the feature is considered safe. Enabled by default."
- **Approach:**
  - Create (or identify existing) e2e/integration test that:
    - Runs on k8s (GKE?)
    - Uses a client and server that both communicate with some custom protocol over TCP
    - Verify that the expected attributes are sent to mixer

Performance
-----------------
- **Description**
  - "Performance and scalability are characterized, but may have performance caveats."
- **Approach**
  - **TBD:** Need to identify the following:
    - Who will do this work? (@ldemailly any thoughts?)
    - What will we measure? With vs without mixer? Tcp rules vs http rules vs both?

Documentation
--------------------
- **Description**
  - "Complete feature documentation published to istio.io. In addition to the basic alpha-level documentation, beta documentation includes samples, tutorials, glossary entries, etc."
- **Approach**
  - **TBD:** Need to identify completion criteria for documentation.  For example, is just enumerating the list of supported protocols on the homepage sufficient? Regardless, some update will need to be made to the [feature status page](https://istio.io/about/feature-stages.html).

Add @jasminejaksic as approver for resulting PRs.

When this issue is resolved, update the [Istio Schedule](https://docs.google.com/spreadsheets/d/1mUIrX82Z8mRuhNWyl5D_sd_Evg3KzeNotzRorPzQMko/edit?ts=5a03f88d#gid=351491887) accordingly.

**Comment by ldemailly** [comment]
for perf: https://github.com/istio/istio/issues/454

**Comment by louiscryan** [comment]
Expectation is that once the new integration test framework is in place we'll improve coverage here

**Comment by loewenstein** [comment]
@nmittler this should probably not have been closed, right? Not sure about timelines, but eventually TCP will get to beta I suppose.

**Comment by loewenstein** [comment]
@nmittler we might be able to help pushing TCP forward. The description here is a bit vague though. Is it really more a matter of testing (functional and performance) and documentation? We are working on an e2e that involves gateways, i.e. workload -> sidecar -> egress gw -> ingress gw -> sidecar -> workload, would that be a good start?

**Comment by loewenstein** [comment]
@nmittler pr for the TCP traffic through egress and Ingress gateway integration test is up https://github.com/istio/istio/pull/11414, if you want to have a look.

It could need an ok to test, although it will currently fail because of https://github.com/istio/istio/issues/9659.

**Comment by nmittler** [comment]
@loewenstein thanks  - I just took a look and left a  comment.
