### ISSUE TITLE
Improve protocol testing coverage

### ISSUE THREAD

**Issue by nmittler** [istio/istio#2198]
Improve test coverage for protocols. In particular we should leverage new integration test framework as means to validate

**Comment by rshriram** [comment]
I already hid the page in istio.io (the feature stages doc). I don't know what it takes to consider a protocol as a Beta or alpha. Does having a test magically promote it to beta? Does Envoy's 1-2yr production history with HTTP2 matter at all? (fwiw, H2 is marked as alpha, while H1 is beta!, yet we have full integration tests for h2, grpc, websockets, h1).

**Comment by nmittler** [comment]
@rshriram the beta criteria has already been defined [here](https://docs.google.com/spreadsheets/d/1mUIrX82Z8mRuhNWyl5D_sd_Evg3KzeNotzRorPzQMko/edit?ts=5a03f88d#gid=44562378)

This is just an Epic issue ... see the child issues for details on the beta criteria for each.

**Comment by andraxylia** [comment]
@rshriram for H2 and GRCP we miss testing them with long running connections.

**Comment by andraxylia** [comment]
[Istio Networking Feature Matrix](https://docs.google.com/spreadsheets/d/1ajTgdiqIV6pqZiYx4X8DZq2v7Mf7TRhpq9gLmRYc0Q8/edit#gid=0) contains what kind of tests exist for each protocol or nw feature.

**Comment by jordanjennings** [comment]
Is there a way to provide read-only access to the linked documents for those of us not directly involved but following this issue?

**Comment by andraxylia** [comment]
Istio docs are shared with the istio-dev community, but you can request access to a specific doc, there should be a button for it.

**Comment by rshriram** [comment]
Per this email thread https://groups.google.com/forum/#!topic/istio-environments/3SZaZGhPk0U, seems @gnirodi , @sdake and co are taking up all the multi-cloud work and rewriting most parts of pilot. So, I would suggest assigning this work to them, since they are best positioned to add tests, and ensure the stability of the system during the rewrite.

**Comment by nmittler** [comment]
@rshriram that seems reasonable.

@gnirodi @sdake do you want to take on the protocol testing as part of this work?

**Comment by sdake** [comment]
@nmittler no - sorry for the confusion on this topic.  Read below for more detail.

@rshriram I'm going to reassign this work back to you, as I don't feel confident I have the wisdom nor knowledge necessary to meet the goals of this piece of work.  I also have zero intent of rewriting pilot.  I haven't spent the last 1+ years writing it as you and others have and understanding it in detail.  I also don't want  to disrupt the flow of the Istio project.

I understand why you have indicated a pilot rewrite is in the cards with multicloud.  The fact is with what has merged related to multicloud already, I think we have a decent alpha story for 1.0 and can possibly tackle whatever serious rework is needed once 1.0 is released.

I would prefer to assist as much as possible in pilot, but as I (in a naive sense) understand multicloud involves a whole lot of pilot refactoring or rewriting, I'd prefer to take that on when I really have a holistic understanding of the pilot code and we can work more closely together on making that happen in an iterative way.

I will be getting more involved in Pilot, hopefully not in a raise all the cities sort of way.  Looking for your guidance and coaching.

Regards
-steve
