### ISSUE TITLE
v2 telemetry duration metrics format change

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#21980]
https://github.com/weaveworks/flagger/issues/478

did we properly document this change in metrics?

**Comment by ckcd** [comment]
oh I met this issue too ..

> did we properly document this change in metrics?

No, I think not. we already use old metrics name in here:
https://istio.io/docs/reference/config/telemetry/metrics/

**Comment by howardjohn** [comment]
1.5 and mixer have came and gone.. seems like this is not needed anymore
