### ISSUE TITLE
Http2 performance issue with some browser

### ISSUE THREAD

**Issue by jsenon** [istio/istio#21994]
**Bug description**

When we test an upload some images with different browser we can't see same performance.
With an input of 2MB:
- can take 2s with Firefox 73.01 (20200217142647) on MacOS
- can take 2s with latest Chrome on Linux Ubuntu
- can take 200ms with latest Chrome (80.0.3987.132) on MacOS

We use HTTP2.

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istio 1.4.2

**How was Istio installed?**
Helm templeting

**Environment where bug was observed (cloud vendor, OS, etc)**
Cloud Provider: AWS
Mutual TLS deactivated

```spec:
  servers:
    - hosts:
        - xxx.com
      port:
        name: http
        number: 80
        protocol: HTTP
    - hosts:
        - xxx.com
      port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        credentialName: xxx-tls
        mode: SIMPLE
  selector:
    app: istio-ingressgateway```

**Comment by howardjohn** [comment]
Do you have any reason to believe this is an Istio issue? If you do not go through Envoy, is performance impacted?

**Comment by jsenon** [comment]
I ve just miss the flow:

client (HTTP 2) -> AWS Classical LB -> istio envoy (HTTP 2) -> svc (HTTP 1.1) -> Endpoint (HTTP 1.1)

If I disable http2 in Firefox browser, I have better performance (with istio)

**Comment by howardjohn** [comment]
> client (HTTP 2) -> AWS Classical LB -> istio envoy (HTTP 2) -> svc (HTTP 1.1) -> Endpoint (HTTP 1.1)

If you test client (HTTP 2) -> AWS Classical LB ->  svc (HTTP 1.1) -> Endpoint (HTTP 1.1)

is it slow?

Otherwise it could just be a firefox issue or something else at another point in the stack

**Comment by jsenon** [comment]
I don't know how to force browser to use http2 for an upstream service in http1.1

**Comment by jsenon** [comment]
We have found a workaround in firefox by setting network.buffer.cache.size to 327680 instead of 32768. https://github.com/webcompat/web-bugs/issues/49950
