### ISSUE TITLE
Reactivating providerURL feature for Istio 1.5

### ISSUE THREAD

**Issue by linuxbsdfreak** [istio/istio#21993]
**Describe the feature request**

The previous version of Istio had a mixer configuration of providerURL 
https://raw.githubusercontent.com/istio/istio/release-1.5/samples/bookinfo/policy/mixer-rule-deny-ip.yaml

Which is not present at the moment

**Describe alternatives you've considered**

I was investigating `AuthorizationPolicy` provided by Istio. However the deny rule is not working.

[ ] Configuration Infrastructure
[X ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

 I have a long list of IP ranges that i need to block. Is there something similar to `providerURL`  in Istio 1.5 for externalizing the IP ranges in a file?

**Comment by incfly** [comment]
Please provide **exact** config snip of the miminmal reproducing steps: 

- cmd to install istio
- config yaml to apply
- expected behavior does not show.

**Comment by yangminzhu** [comment]
@incfly this is a feature request for adding the `providerURL` support in authZ policy so that it can get data directly from a URL into the policy, we don't really need to reproduce anything here.

@linuxbsdfreak thanks for filing the FR, I think we won't be able to do this for 1.6, it requires some big changes to the API, @liminw let me know wdyt.

**Comment by incfly** [comment]
Thanks for explaining! I thought it was a regression before, sorry about that.

Now I take a closer look at the usage of policyURL, which `fetched asynchronously using the providerUrl`, basically does that mean the old mixer filter really send request to resolve the indirection? which AFAIK, rbac filter does not do any sort of those things?

or could it be similar to jwt, where control plane make the request and we translate to resolved list via rbac filter config?

**Comment by linuxbsdfreak** [comment]
@incfly . I have a large list of Blacklist IP ranges hosted on a HTTP server which i would like to use for filtering traffic. 

This was provided in the older istio release
https://istio.io/docs/tasks/policy-enforcement/denial-and-list/#ip-based-whitelists-or-blacklists
