### ISSUE TITLE
Enable Tracing in 1.5 causes errors in CDS

### ISSUE THREAD

**Issue by sakajunquality** [istio/istio#22006]
**Bug description**
In 1.5.0 enabling tracing by option tracing.enabled=true causes errors in CDS. And istio-proxy does not start working.

**Expected behavior**

Safely installed and readiness healthcheck of sidecar istio-proxy success.

**Steps to reproduce the bug**
1. install istio with istioctl
istioctl manifest apply --set values.tracing.enabled=true

2. deploy apps
any apps in namespaces labeled with istio-injection: enabled

3. check istioctl proxy-status
istioctl proxy-status
All the CDS is `STALE (Never Acknowledged) `

4. check isito-proxy logs

Envoy does not receive cds collectly

```
2020-03-09T17:44:48.471943Z info Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 0 successful, 3 rejected; lds updates: 3 successful, 0 rejected
```

5. check istiod logs

Check Istiod logs

```
warn	ads	ADS:CDS: ACK ERROR 10.23.2.16:59654 sidecar~10.23.2.16~echo-5774899fcc-b6kr7.echo-staging~echo-staging.svc.cluster.local-46 Internal:Error adding/updating cluster(s) outbound|14250||jaeger-collector-headless.istio-system.svc.cluster.local: cluster manager: cluster provided LB specified but cluster 'outbound|14250||jaeger-collector-headless.istio-system.svc.cluster.local' did not provide one. Check cluster documentation.
```

6. disable tracing (temp solution)
Solved when I disable tracing

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
istioctl version --remote
client version: 1.5.0
control plane version: 1.5.0
data plane version: 1.5.0 (24 proxies)
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.9-gke.12", GitCommit:"4dde8f42b43042db3e662cdd2e707c0f922cae6e", GitTreeState:"clean", BuildDate:"2020-02-13T18:39:12Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

istioctl manifest apply with the following options

**Environment where bug was observed (cloud vendor, OS, etc)**

GCP 1.15.9-gke.12

**Comment by howardjohn** [comment]
I could not reproduce this. I ran `~/istio/istio-1.5.0/bin/istioctl manifest apply --set values.tracing.enabled=true -y` then spun up a pod with injection, and things were fine. Were there any additional steps you ran?

**Comment by sakajunquality** [comment]
@howardjohn I will check it again!

**Comment by sakajunquality** [comment]
Looks like I had an error with Service Entry

**Comment by UmaGovindaraj** [comment]
@sakajunquality , can u mention what is that error you made in service entry. I am facing the same issue now. I have service entry and the CDS goes STALE. Thanks in advance !!

**Comment by sakajunquality** [comment]
Hello @UmaGovindaraj ,
What happened to me is that when I created ServiceEntry for external http service, I got this error. So I solved it by deleting it. As the service was not used any more, it was fine. However when I created another ServiceEntry, I got similar error. Practically my issue is not solved.

Which version are you using?
