### ISSUE TITLE
istioctl does not run on OSX High Sierra

### ISSUE THREAD

**Issue by Dakuan** [istio/istio#2200]
Installed in path, then try to run the bit from the tutorial:

```
$ istioctl create -f new_telemetry.yaml

Bus error: 10
```

**Comment by cmluciano** [comment]
Are there any open bugs for high sierra and Go? cc @istio/release-engineers

**Comment by kyessenov** [comment]
I haven't been brave enough to update to High Sierra on corporate machine, due to the root login issue. Our CI/CD unfortunately, does not have mac build machines.

**Comment by mattdelco** [comment]
Corp warned people to avoid High Sierra (this was even before the root login issue), though I don't know if they'll be proactive enough to tell me/us when they've worked out the kinks.  I only run "istioctl version", which initially didn't work properly on any OS when we were trying to get a viable 0.3.0 release.

**Comment by Dakuan** [comment]
is there an alternative to using the istio cli?

**Comment by mandarjog** [comment]
In most cases you can use kubectl.

**Comment by ldemailly** [comment]
it’s odd. you could build it from source

**Comment by mattdelco** [comment]
A basic version check seems to work okay for me on 10.13.3.  When I previously did a search on the error most comments suggested it was a system-specific corruption.

<pre>./istioctl version
Version: 0.5.0
GitRevision: c9debceacb63a14a9ae24df433e2ec3ce1f16fc7
User: root@211b132eb7f1
Hub: docker.io/istio
GolangVersion: go1.9
BuildStatus: Clean
</pre>

**Comment by ldemailly** [comment]
k so false alarm
