### ISSUE TITLE
Remove or simplify PR template

### ISSUE THREAD

**Issue by nmittler** [istio/istio#2201]
The current PR template contains quite a bit of boilerplate that seems generally unnecessary.

More specifically:

- Description: this is just the standard description of the issue.  Having a separate section called out does not add anything.

- Fixes: This is a separate section that calls out fixes, when a standard '#fixes...` somewhere in the PR description is sufficient and more idiomatic for github.

- Special notes: I've never seen this section used and I'm not sure anyone knows what it's for.

- Release notes: It's currently unclear to me what the purpose of this section is.  In most (if not every) PR I've seen so far, this section is either omitted or empty.  I would suggest removing it until we have identified (and better documented) what the purpose of this section is and how it is used by the system.

I propose eliminating the template altogether for now.  If at some point in the future (or now) we can justify any of these sections, then we can expand the PR description requirements as-needed (with more thought put into making the developer's task simpler).

**Comment by nmittler** [comment]
CC @hklai

**Comment by hklai** [comment]
Some of these are used to generate release notes automatically.
@yutongz has more context.

**Comment by nmittler** [comment]
I'm confident that we can figure out a way to generate release notes without much of this boilerplate.  Especially since most people aren't currently following it.

**Comment by yutongz** [comment]
For release-note part, please take a look at this: https://github.com/istio/test-infra/blob/master/mungegithub/README.md#release-note-1

For other part of the template, cc @gyliu513

**Comment by nmittler** [comment]
> For release-note part, please take a look at this: https://github.com/istio/test-infra/blob/master/mungegithub/README.md#release-note-1

Is the release notes section absolutely required by Mungegithub or only in the way we use it?

**Comment by geeknoid** [comment]
I also strongly believe that the template is a burden.

I have hand-produced the official release notes on istio.io by going through our commit logs. The templates are a pain in this process, they cause a lot of noise and redundancy.

The auto-produced release notes are incomplete, inconsistent and misleading. They only contain a subset of the actual changes, they are either too low-level (fixed a comment) or too broad without context (added a whole new feature).

We need hand-authored holistic release notes which provide context, useful links, elide minutia, etc. If people want details, they can then look at the commit history.

@rshriram

**Comment by kyessenov** [comment]
I think we are not at the scale, where we need automatic release note bot.
It works great for k8s, but for us it's more work than hand-crafting
release notes.

**Comment by ZackButcher** [comment]
+1 I'm in favor of dumping the template. Especially because Martin has been the one actually producing our release notes and doesn't use them.

**Comment by hklai** [comment]
FYI. The 0.3 release note was generated. 
I don't believe we want a human to stand by and create release notes manually every month. We do want to make monthly releases as automatic as possible.

Having said that, the generation and extraction mechanism is up for discussion.

**Comment by hklai** [comment]
Also, we have agreed to separate monthly releases and marketing releases. Monthly releases are supposed to be fully automatic, while marketing releases will have more detailed information about new features and changes. I supposed the marketing release notes (or additional documentation) will be more carefully curated.

**Comment by geeknoid** [comment]
I am a human and I wrote the 0.3 release notes on istio.io:

https://istio.io/docs/welcome/notes/0.3.html

The auto-generated notes on GitHub aren't interested for the reasons I
mentioned.

**Comment by yutongz** [comment]
If we think we prefer to manually generate release-note every time, I am totally fine with it. But we need to remove a tool just because we are not using it in the right way, it seems not super convincing for me.

cc @ldemailly @fejta @BenTheElder @cjwagner

**Comment by hklai** [comment]
Thanks for the clarification, Martin, We were talking about different
things.
Are you comfortable to continue writing release notes like that every
month? We need someone who fully understand the whole system and the
changes.


On Fri, Dec 15, 2017 at 12:45 PM, Martin Taillefer <notifications@github.com

**Comment by BenTheElder** [comment]
> Is the release notes section absolutely required by Mungegithub or only in the way we use it?

It should not be required if you're only using mungegithub for merging.

We also hope to help migrate mungegithub users to `Tide` for merges and `Prow` plugins for other functionality, but we want to make sure the UX gets a little bit more polish first. @cjwagner and I were just discussing what needs to happen on that front. A number of projects are already using Tide as is though, FWIW.

**Comment by geeknoid** [comment]
Yes, that is my plan.

To that end, improving the quality of our commit history would go a long
way. Right now, the overwhelming majority of what ends up in our commit
logs is boilerplate stuff from the template, dependency updates from the
robots, and auto-merge noise. Having clean commit logs devoid of
machine-generated stuff would make understanding our source tree and
produce release notes quite a bit easier.

**Comment by nmittler** [comment]
> But we need to remove a tool just because we are not using it in the right way, it seems not super convincing for me.

@yutongz Your logic seems inverted to me.  Why would we continue to incorporate a tool (something that adds a significant amount of complexity) if we're not going to use it?

**Comment by yutongz** [comment]
@nmittler  Yeah, if we have some people commit to create release-note, sure, I am ok to remove this tool.

**Comment by rshriram** [comment]
I said it earlier and I will say again.. IF we have a running log of release notes for monthly release in a wiki, people have time and incentive to curate and properly describe why the change they made is important. If its not important (non functional change or tweaking scripts, etc), I don't want to see it on the release note. Even if its a monthly release note, I am happy if all I see is bug fixes and performance improvements, instead of something unintelligible like "ParseHostName now uses source instances instead of generic struct" .

**Comment by geeknoid** [comment]
Yes, I really like the Wiki idea. Folks can learn to have stuff in there,
and we can do a monthly pass to make sure it contains everything we need
and doesn't contain goofy thing. That would strike a reasonable balance.

The large majority of commits into the source base are not worthy of being
mentioned in release notes.

**Comment by hklai** [comment]
Agreed that the generated release notes are not that readable and useful.

If that is the only use case why we needed the template, we may as well just remove it. @yutongz, could you look into that?

@geeknoid Martin, could you add/replace the release note links on https://github.com/istio/istio/releases after you are done with the release notes every month?

**Comment by yutongz** [comment]
We safe to remove the release-note part. Not sure about others.

**Comment by kyessenov** [comment]
Can we disable it for a few months, and enable it only when we hit the scale of contributions that k8s gets? It's not the right time, I think, but hopefully good for the future.

**Comment by geeknoid** [comment]
I've updated the Wiki to point to istio.io. I'll do this every month as I
publish the monthly release notes.

**Comment by ldemailly** [comment]
I would prefer we have a scalable, complete process for raw release notes in addition to the curated one on the website. that was the point of the difference between the website (where there is only 1 0.1 release note) vs the wiki (where each release can have exact PR and bug fixed)

But I guess we'll get back to that once we reach that scale and/or start making patch releases and fix bugs

**Comment by nmittler** [comment]
@ldemailly agreed ... automated release notes would be great. It just doesn't seem to be clear ATM how to do it in such a way that the end result is a clear, cohesive list (without a lot of spam from minor commits).

**Comment by nmittler** [comment]
@hklai It seems that we're all in agreement.  Can we pull the trigger on this?

**Comment by ldemailly** [comment]
it’s actually pretty clear, if a change is minor the author puts none as release notes... but that would take a modicum of discipline and education which apparently we can’t do

**Comment by hklai** [comment]
@ldemailly I think the other argument is that even if we have that discipline, most PRs are not that interesting in release notes. Having someone that have a holistic view on a release to prepare release notes is clearly better.

I think we all are in agreement that we can look into automatic release notes generation when:
1. The community grows bigger and we have more PRs in monthly releases.
2. Nobody can  or is willing to curate release notes every month.

At that time, we can see how we can design and implement the generation better.

@yutongz, please help disable PR template for now.
