### ISSUE TITLE
istio 1.5 Pod SecurityContext break volumeMount

### ISSUE THREAD

**Issue by ckcd** [istio/istio#22025]
**Bug description**
my pod has a volume mount which is a NFS(pv+pvc) and their are about 100 thousand files in this volume. when using istio 1.5, I find it's very slow to init the pod :

```
Warning  FailedMount  39s   kubelet, cn-shanghai.10.98.5.213  Unable to mount volumes for pod "ubuntu-deploy-1-677f474ff9-bq5gd_backend(e3a8ffc4-61d3-11ea-a85d-aa30c59d7048)": timeout expired waiting for volumes to attach or mount for pod "backend"/"ubuntu-deploy-1-677f474ff9-bq5gd". list of unmounted volumes=[mypd]. list of unattached volumes=[mypd default-token-flkq5]
```
it takes about 30min to finish the mount.

with some debug in it, I found the reason is: istio 1.5 inject a pod SecurityContext: `fsGroup: 1337`, and kubelet will use this fsGroup to configure my volume, which means do `chomd` and `chown` for any files in the volume, in my case it's 100 thousand files, so it's very very slow.

I find https://github.com/istio/istio/pull/20428 add the pod SecurityContext but I'm a little confused why we must set a pod SecurityContext rather than a container SecurityContext.

And I think it may affects not only NFS but also any volumeMount.

**Expected behavior**
the inject configure should NOT affect volume mount of my container.

**Steps to reproduce the bug**
1. create pv + pvc which use NFS with a large number of file.
2. setup a pod using this pvc as a volume.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
$ ./istioctl version --remote
client version: 1.5.0
control plane version: 1.5.0
data plane version: 1.5.0 (575 proxies)
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-aliyun.1", GitCommit:"a4182a8", GitTreeState:"", BuildDate:"2019-08-27T06:03:13Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
`istioctl`

**Environment where bug was observed (cloud vendor, OS, etc)**
`aliyun`

**Comment by ckcd** [comment]
@howardjohn @rlenglet please take a look for this issue, thanks !

**Comment by ckcd** [comment]
Seems like in istio 1.5 istiod set a default value for sdsUdsPath: https://github.com/istio/istio/blob/81230d4d95f77fe0e4b8fd0c38a33f1dc91e2a2e/manifests/istio-control/istio-discovery/templates/configmap.yaml#L147

and injector modify the pod securityContext when sdsUdsPath is not nil.

**Comment by rlenglet** [comment]
> I find #20428 add the pod SecurityContext but I'm a little confused why we must set a pod SecurityContext rather than a container SecurityContext.

`fsGroup` can only be set in a [PodSecurityContext](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#podsecuritycontext-v1-core), because it applies to all the volumes in the pod. Volumes are defined at the pod spec level. That can't be controlled at the volume mount level, or per-volume. That's an unfortunate limitation of the pod spec API.

**Comment by rlenglet** [comment]
> and injector modify the pod securityContext when sdsUdsPath is not nil.

That's the bug. We should not do that anymore in 1.5.

**Comment by rlenglet** [comment]
cc @myidpt

**Comment by ckcd** [comment]
> That's the bug. We should not do that anymore in 1.5.

so you means that if we fix this bug, then injector will NOT change the pod SecurityContext ?

**Comment by rlenglet** [comment]
Yes, the SDS UDS is not used anymore, there should be no reason to ever change the `fsGroup` in injected pods anymore.

**Comment by rlenglet** [comment]
@ckcd this is the code that does this:
https://github.com/istio/istio/blob/9c1a352bb74588076f7f69e3c1e5571182c2fa00/pkg/kube/inject/inject.go#L746-L755

BTW, a quick workaround for you is to just remove that `sdsUdsPath` setting.

**Comment by ckcd** [comment]
> BTW, a quick workaround for you is to just remove that sdsUdsPath setting or just set it explicitly to an empty string.

Cool. I was intend to do this but I'm not sure the effects. Will try this.

Thanks a lot !!!

**Comment by rlenglet** [comment]
@myidpt @lei-tang I'd suggest removing this `sdsUdsPath ` setting from mesh config and the according code in the injector altogether. WDYT?

**Comment by ckcd** [comment]
> BTW, a quick workaround for you is to just remove that sdsUdsPath setting or just set it explicitly to an empty string.

@rlenglet 
how to change this value when using `istioctl` ? I find the `sdsUdsPath: "unix:/etc/istio/proxy/SDS"` only in `install/kubernetes/operator/charts/istio-control/istio-discovery/templates/configmap.yaml` but there are no any changes when I modify here.

**Comment by ckcd** [comment]
and when I direct modify the `istio` configMap and restart `istiod` after install istio normally, my pod failed in start and istio-proxy errors:

```
Invalid path: /etc/certs/root-cert.pem, outbound|50050||oasis-oasis-web-envoy.platform.svc.cluster.local: Invalid path: /etc/cer
ts/root-cert.pem
2020-03-10T06:44:24.667685Z     info    Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 0 successful, 1 rejected; lds updates: 0 successful, 0 rejected
[Envoy (Epoch 0)] [2020-03-10 06:44:24.985][29][warning][config] [external/envoy/source/common/config/grpc_subscription_impl.cc:87] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/up
dating listener(s) 10.98.77.22_50066: Invalid path: /etc/certs/root-cert.pem
virtualInbound: Invalid path: /etc/certs/root-cert.pem

2020-03-10T06:44:26.667377Z     info    Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 0 successful, 1 rejected; lds updates: 0 successful, 1 rejected
2020-03-10T06:44:28.667460Z     info    Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 0 successful, 1 rejected; lds updates: 0 successful, 1 rejected
2020-03-10T06:44:30.668719Z     info    Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 0 successful, 1 rejected; lds updates: 0 successful, 1 rejected
2020-03-10T06:44:32.667585Z     info    Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 0 successful, 1 rejected; lds updates: 0 successful, 1 rejected
2020-03-10T06:44:34.668431Z     info    Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 0 successful, 1 rejected; lds updates: 0 successful, 1 rejected
2020-03-10T06:44:36.667414Z     info    Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 0 successful, 1 rejected; lds updates: 0 successful, 1 rejected
```

**Comment by lei-tang** [comment]
The code https://github.com/istio/api/blob/master/mesh/v1alpha1/config.proto#L216 shows that sds_uds_path has been deprecated in MeshConfig.

The code https://github.com/istio/istio/blob/release-1.5/pkg/istio-agent/sds-agent.go#L226 shows that SDS UDS path is configured from LocalSDS instead, as "unix:/etc/istio/proxy/SDS".

**Comment by ckcd** [comment]
@lei-tang so whether the pod SecurityContext should be injected?

**Comment by lei-tang** [comment]
@ckcd how do you install Istio 1.5 (e.g., the commands and the steps you used to install Istio 1.5)?

**Comment by lei-tang** [comment]
According to the comment on https://github.com/istio/istio/blob/release-1.5/pkg/kube/inject/inject.go#L742, the pod SecurityContext is needed for istio-proxy to read the k8s service account token.

**Comment by ckcd** [comment]
@lei-tang 
use `istioctl manifest generate -f ./profile.yaml` and then `kubectl apply -f xxx`

the `profile.yaml` is:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  addonComponents:
    grafana:
      enabled: false
    kiali:
      enabled: false
    prometheus:
      enabled: false
    tracing:
      enabled: false
  components:
    base:
      enabled: true
    citadel:
      enabled: false
    ingressGateways:
    - enabled: false
    egressGateways:
    - enabled: false
    galley:
      enabled: false
    ingressGateways:
      - enabled: false
    policy:
      enabled: false
    sidecarInjector:
      enabled: false
    telemetry:
      enabled: false
  values:
    global:
      mtls:
        enabled: false
      enableTracing: false
      jwtPolicy: first-party-jwt
      proxy_init:
        image: __PROXY_IMAGE__
      proxy:
        image: __PROXY_IMAGE__
        accessLogFile: "/dev/stdout"
        includeIPRanges: "192.168.0.0/16"
        resources:
          limits:
            cpu: 2000m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
```

**Comment by lei-tang** [comment]
As indicated by the comment on https://github.com/istio/istio/blob/release-1.5/pkg/kube/inject/inject.go#L742 that the pod SecurityContext is needed for istio-proxy to read the k8s service account token, applying the pod SecurityContext is an intended behavior.

**Comment by howardjohn** [comment]
You still need the SDS uds path, we just probably can remove that code changing the fsGroup now. I think Pilot is reading the mesh config for backwards compatibility

**Comment by howardjohn** [comment]
Also UDS path is still used, its just only used within a local container not a hostpath mount if that wasn't clear above

**Comment by ckcd** [comment]
> we just probably can remove that code changing the fsGroup now.

@howardjohn so if I delete the fsGroup code here: https://github.com/istio/istio/blob/9c1a352bb74588076f7f69e3c1e5571182c2fa00/pkg/kube/inject/inject.go#L746-L755 and build a istiod image then updatee it in my cluster, will it cause any compatibility problem ?

**Comment by howardjohn** [comment]
I think it would work.. but obviously have not tested this

**Comment by ckcd** [comment]
> but obviously have not tested this

hha.. will have a try.

**Comment by howardjohn** [comment]
Without this we get `2020-03-16T16:23:01.183276Z     error   sds     Failed to get credential token: open ./var/run/secrets/tokens/istio-token: permission denied`

**Comment by howardjohn** [comment]
Its actually not about the UDS socket as well, thats just a way we detect whether the token is needed. The problem is just the token is mounted with read only for root

**Comment by ckcd** [comment]
> The problem is just the token is mounted with read only for root

got your point, seems that the issue in https://github.com/kubernetes/kubernetes/issues/89153 only occurs for `serviceAccountToken` ? cause I use `first-party-jwt` rather than `third-party-jwt` and when I delete the fsGroup in injector, it works well.

**Comment by myidpt** [comment]
@rlenglet so we set fsGroup only becuase it's required to make the 3rd party jwt working? If so, kubernetes/kubernetes#89153 seems to be the right path.

**Comment by rlenglet** [comment]
That is correct. This bug has existed for a long time: https://github.com/kubernetes/kubernetes/issues/57923.

**Comment by mgxian** [comment]
We can not do anything about this ? So I should downgrade to istio 1.4 in order to use volume mount

**Comment by mgxian** [comment]
Can we add some flags and args or automatic disable fsGroup inject when user use first-party-token ?

**Comment by devlinyvonne** [comment]
Are the only solutions currently to either downgrade to 1.4 or pull down the Istio code and compile a version of the istio image that removes the offending code from istio/pkg/kube/inject/inject.go? Will there be a PR made to fix this for the next release? Or is 1.5.6 the last release for 1.5?

**Comment by rlenglet** [comment]
This can't be properly fixed until https://github.com/kubernetes/kubernetes/issues/57923 is fixed.

**Comment by FrimIdan** [comment]
> Can we add some flags and args or automatic disable fsGroup inject when user use first-party-token ?

@howardjohn @rlenglet asking again because no answer was made. If the user choose to use first party token why fsGroup is injected? This can be a good solution for customers with keys that are volume mounted.. Currently no solution is available.

**Comment by rlenglet** [comment]
@FrimIdan as you already know, this is a known bug in upstream Kubernetes. This can't be fixed until kubernetes/kubernetes#57923 is fixed.

**Comment by FrimIdan** [comment]
@rlenglet thanks for the answer.
I don't want/can fix it, I do want that Istio injector will not set the fsGroup to 1337 if Istio is running in first part jwt mode.
This way we can tell customers to set jwt policy to first party and problem solved, currently no WA is available.

**Comment by FrimIdan** [comment]
We need the fsGroup change only for third party jwt so why changing it when running first party jwt?

**Comment by shortwavedave** [comment]
Hello @rlenglet , I think I am hitting this issue with istio - is there any workaround in the shortterm? 

```
Unable to attach or mount volumes: unmounted volumes=[pvc-scratch2], unattached volumes=[default-token-hfdlr pvc-scratch2 istiod-ca-cert istio-data istio-envoy istio-token istio-podinfo]: timed out waiting for the condition
```

**Comment by rlenglet** [comment]
@shortwavedave no, there is no workaround.
