### ISSUE TITLE
Testing patterns

### ISSUE THREAD

**Issue by rosenhouse** [istio/istio#2202]
Comments in https://github.com/istio/istio/pull/2022 have raised the question of what our patterns and expectations are for Golang testing patterns, specifically around standardization within the Istio project.

As a contributor, I'd like to understand what the expectations are in advance, so that I don't waste time writing tests in a style that maintainers reject.

I'd also like the chance to discuss the relative merits of different testing patterns.  We each have our own preferences, I'm sure.

**Comment by rosenhouse** [comment]
cc @kyessenov @ZackButcher @geeknoid

**Comment by ZackButcher** [comment]
So I don't have a strong opinion about which set of frameworks or patterns we use across the project; my one concern is that we pick a small subset and use them consistently everywhere. My overriding concern is that we not increase the maintenance burden on the project's maintainers by proliferating different patterns across the codebase.

**Comment by geeknoid** [comment]
I'm also fairly agnostic to the specific choice, I want consistency and
convergence.

Now, given different frameworks, I find the built-in go stuff pretty
rudimentary and lacking in features. But the table-driven test model we're
using in most places is reasonably concise and easy to understand and
extend. And the integration with GoLand is very nice.

Bottom line for me is that there is inertia in how we're done things. To
warrant spending resources on changing to a new test framework for the
project would need to demonstrate a substantial qualitative improvement
over the status quo.
