### ISSUE TITLE
istio 1.5.0 Mixer Report failed with: UNAVAILABLE:Cluster not available

### ISSUE THREAD

**Issue by Henrike42** [istio/istio#22029]
What does the error message in the logs of a k8s service istio-proxy container indicate?

````2020-03-10T08:55:14.104171Z     info    Envoy proxy is ready
[Envoy (Epoch 0)] [2020-03-10 08:55:29.313][29][warning][filter] [src/istio/mixerclient/report_batch.cc:110] Mixer Report failed with: UNAVAILABLE:Cluster not available
````
The corresponding k8s service is also no longer accessible, neither from within the cluster nor from outside. It returns 503. 

````
HTTP/2 503 
content-length: 33
content-type: text/plain
server: istio-envoy

UNAVAILABLE:Cluster not available
````

This starts to occur with istio 1.5.0, with istio 1.4.5 everything worked nicely.

The istio-system pod logs don't show any errors.

**Comment by AceHack** [comment]
I'm having the same issue did you find a fix
