### ISSUE TITLE
LocalityLoadBalancer Distribute needs to have a weight greater than 0

### ISSUE THREAD

**Issue by maruina** [istio/istio#22030]
**Bug description**

Hello, looking at https://istio.io/docs/reference/config/networking/destination-rule/#LocalityLoadBalancerSetting-Distribute we say
```
Any locality not assigned a weight will receive no traffic.
```
But I don't understand how you can set it.

Looking at https://github.com/istio/istio/blob/ef12959963cf6bdde25c04e9e2b2307d9347a1a0/pilot/pkg/networking/core/v1alpha3/loadbalancer/loadbalancer.go#L120 it seems that everything <= 0 gets ignored, but if I try to set 0 I get a validation error.

The error is

```
2020-03-09T16:06:42.362304Z    warn    failed to read mesh configuration, using default: 1 error occurred:
    * locality weight must not be in range [1, 100]
```

and it's coming from https://github.com/istio/istio/blob/16043a07a51cd58ddd94b8cad32bb266968ecf72/pkg/config/validation/validation.go#L2767

My question is: is it possible to keep a locality entry without sending any traffic to it?

[x] Configuration Infrastructure
[x] Docs

**Expected behavior**

You should be able to have a locality not assigned a weight in the Mesh ConfigMap.

**Steps to reproduce the bug**

Any of the following setting will produce an error in Pilot

```
localityLbSetting:
  enabled: true
  distribute:
  - from: "*"
    to:
      "foo": 100
      "bar": 0
```
or
```
localityLbSetting:
  enabled: true
  distribute:
  - from: "*"
    to:
      "foo": 100
      "bar": 
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-23T14:21:36Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.9", GitCommit:"500f5aba80d71253cc01ac6a8622b8377f4a7ef9", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:04Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
```
❯ istioctl version --remote
client version: 1.4.3
defaultgateway version:
defaultgateway version:
defaultgateway version:
defaultgateway version:
citadel version: 1.4.3
citadel version: 1.4.3
galley version: 1.4.3
galley version: 1.4.3
pilot version: 1.4.3
pilot version: 1.4.3
policy version: 1.4.3
policy version: 1.4.3
sidecar-injector version: 1.4.3
sidecar-injector version: 1.4.3
telemetry version: 1.4.3
telemetry version: 1.4.3
data plane version: 1.4.3 (128 proxies)
```

**How was Istio installed?**

Helm chart

**Environment where bug was observed (cloud vendor, OS, etc)**

AWS, KOPS cluster.

**Comment by esnible** [comment]
The error message is incorrect, it should be `locality weight must be in range [1, 100]`.  The word `not` does not belong.  I will make a PR for the message.

Your issue may be a duplicate or related to  https://github.com/istio/istio/issues/15157 .

Several places in Istio's API can't distinguish between a user skipping setting this field and explicitly setting it to 0.  I don't know if this can be fixed in the API.

When researching 15157 I spoke with some folks in @istio/wg-networking-maintainers who suggested that Istio would not allow hosts to be disabled setting weight to 0.  Users should write rules without the host, rather than setting its weight to 0.

**Comment by maruina** [comment]
Looking at the `load_balancing_weight` in https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/endpoint/endpoint_components.proto#envoy-api-msg-endpoint-localitylbendpoints, I thought Istio was following Envoy's behavior.

We're going to remove the entry for the time being, thanks for your answer.
