### ISSUE TITLE
Refactor grafana dashboard for Istiod

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#22054]
Right now we have citadel, galley, etc dashboards that aren't very useful anymore with Istiod. We also have a confusing "Pilot" dashboard. I propose that:

* We keep mesh, service, and workload dashboards untouched
* We redesign the perf and pilot dashboards to take advantage of the new architecture

## Istio Control Plane dashboard

This will consist of:

Version

Memory | CPU | Goroutines

XDS Pushes | Xds Push Errors | XDS Push Times
XDS Clients | XDS Push Reasons | XDS Conflicts

CSR information

Validation success/fail | injection success/fail

This is basically the current pilot dashboard, with more things added. Additionally, we are removing the Envoy metrics

## Istio Data Plane dashboard

This will consist of

Proxy Memory | Proxy CPU - some sort of drop down menu to filter by namespace, gateways, global, etc?
Same as ^ but relative to traffic RPS

Envoy XDS Connection information  - currently on Pilot dashboard

This basically replaces the performance dashboard. I think we can keep the same info here but make it data plane specific. We can throw in Pilot CPU metrics as well if desired, but I don't think its necessarily personally.

Very open to hearing others opinions on what stats we should show and in what format

**Comment by rolandkool** [comment]
For multi-cluster setups, it makes sense to have a separate dashboard for Citadel, as that component runs in every cluster. Perhaps same for Galley.

Another improvement I'd love to see on the dashboards is a mesh and/or cluster filter. Again, useful for multi-cluster setups and environments. This may require a change on the service monitors or metrics to include this data in the metrics.

**Comment by howardjohn** [comment]
Citadel has been deleted and Galley will be soon as well. The functionality is integrated into Istiod. I agree on the filters though, other filters may be useful as well

**Comment by rolandkool** [comment]
The citadel/galley metrics still exist, so putting them on a separate dashboard (or keeping the current one) makes sense, I think. That way, you won't have an half empty dashboard when looking at a remote cluster (as all the pilot metrics won't be there).

**Comment by howardjohn** [comment]
We did the first half. Second half will be 1.7 I think

**Comment by douglas-reid** [comment]
@esnible for visibility

**Comment by esnible** [comment]
This is marked P1 for 1.7 yet no one is assigned to it.  I thought `telemetry` was doing it.  Can we retarget for 1.8?  For 1.8, which working groups need it on their roadmap?

**Comment by douglas-reid** [comment]
There was some work done on this, but it did not get fully completed in this cycle.

**Comment by howardjohn** [comment]
This is still valid. `CSR information` could be useful for istiod dashboard

Everything in "Istio Data Plane dashboard" part has not been done
