### ISSUE TITLE
istioctl does not give enough control over registries 

### ISSUE THREAD

**Issue by VariableDeclared** [istio/istio#22077]
**Describe the feature request**
Change the manifests to allow the all images to be pulled from a private registry.

**Describe alternatives you've considered**
Using helm - but this is deprecated in the docs.

istioctl

**Additional context**

When using the `tag` option given with `istioctl manifest apply` control is only given over specifically isitio images. For example pilot.

Other images such as kaili are still referring to docker.io.

**Comment by esnible** [comment]
Use `--set values.kiali.hub=example.com/kiali` `--set values.kiali.tag=experimental`

The default (for master, I didn't try on 1.5.0) is `quay.io/kiali/kiali:v1.14`.  With these overrides it becomes `example.com/kiali/kiali:experimental`.  You can also supply these in an IstioOperator CR if you are using the Istio Operator.

Unless you are on the demo profile, you will also need `--set values.kiali.enabled=true`

**Comment by howardjohn** [comment]
Closing as this is answered by ^
