### ISSUE TITLE
Can't set loadBalancerSourceRanges on ingressGateways in IstioOperator

### ISSUE THREAD

**Issue by seeruk** [istio/istio#22088]
**Bug description**

I'm trying to port over the Helm values we have at Icelolly to move over to using `istioctl`. We have 3 ingress gateways; the default one, one that uses an internal load balancer, and one that uses a public load balancer that only allows access from our office IP.

This is the configuration extract:

```
spec:
  components:
    ingressGateways:
    - name: istio-ingressfirewalledgateway
      enabled: true
      k8s:
        env:
        - name: ISTIO_META_ROUTER_MODE
          value: sni-dnat
        hpaSpec:
          minReplicas: 2
          maxReplicas: 5
          metrics:
          - resource:
              name: cpu
              targetAverageUtilization: 80
            type: Resource
          scaleTargetRef:
            apiVersion: apps/v1
            kind: Deployment
            name: istio-ingressfirewalledgateway
        nodeSelector: {}
        podAnnotations: {}
        resources:
          limits:
            cpu: 2000m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        service:
          loadBalancerSourceRanges:
          - 12.34.56.78/32
        serviceAnnotations:
          service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "600"
```

(12.34.56.78/32 is replaced with our office IP in reality, but the format is the same otherwise).

When I use the above configuration, I get this output from `istioctl`:

```
$ istioctl upgrade --dry-run -f ./operator-staging.yaml
proto: tag has too few fields: "-"
2020-03-11T17:29:39.583599Z	info	Error: failed to generate IOPS from file [./operator-staging.yaml], error: validation errors (use --force to override):
validate path Components.K8S.Service, value: 12.34.56.78/32, expected ptr, got string

Error: failed to generate IOPS from file [./operator-staging.yaml], error: validation errors (use --force to override):
validate path Components.K8S.Service, value: 12.34.56.78/32, expected ptr, got string
```

I've run into #21938 and #20033 also during this process (seems like maybe the process of generating the configuration is also broken and outputting invalid configuration - I also came across an issue where if certManager was included in the `addonComponents` section it would fail saying some assets were missing too even though it was set to disabled).

I can see that the Helm chart has been removed in the master branch, and despite being on Istio 1.5.0 now via Helm it doesn't look like we'll be able to go further than that unless many issues with `istioctl` are resolved. We also don't seem to be able to benefit from `istiod` until we can use `istioctl` too.

**Expected behavior**

`istioctl` should accept service configuration and generate the correct output.

**Steps to reproduce the bug**

See bug description.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
$ istioctl version --remote
client version: 1.5.0
citadel version: 1.5.0
citadel version: 1.5.0
galley version: 1.5.0
galley version: 1.5.0
ilbgateway version: 1.5.0
ilbgateway version: 1.5.0
ingressfirewalledgateway version:
ingressfirewalledgateway version:
ingressgateway version: 1.5.0
ingressgateway version: 1.5.0
pilot version: 1.5.0
pilot version: 1.5.0
policy version: 1.5.0
policy version: 1.5.0
sidecar-injector version: 1.5.0
sidecar-injector version: 1.5.0
telemetry version: 1.5.0
telemetry version: 1.5.0
data plane version: 1.5.0 (87 proxies)
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-13T18:08:14Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-502bfb", GitCommit:"502bfb383169b124d87848f89e17a04b9fc1f6f0", GitTreeState:"clean", BuildDate:"2020-02-07T01:31:02Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

```
$ helm version
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
```

**How was Istio installed?**

Using Helm, but I've taken our Helm values and used `manifest migrate` with an older version of `istioctl` to get a control plane config, then used 1.5.0's `istioctl` to generate an operator config from that. 

(Is this process correct? I found a little bit of documentation in a blog post about it, but nothing about having to upgrade the output using different versions of `istioctl`, but it didn't work any other way I tried).

**Environment where bug was observed (cloud vendor, OS, etc)**

AWS EKS

**Comment by cdmurph32** [comment]
Looks like it was fixed.
https://github.com/istio/istio/pull/22067

**Comment by xadhatter** [comment]
Using `--force` option appears to get pass the error and the source ranges are properly propogated to the service spec.
```
$ istioctl upgrade --force --dry-run -f ./operator-staging.yaml
```

... while we wait for `1.5.2`, https://github.com/istio/istio/pull/22691
