### ISSUE TITLE
PodAntiAffinity under Mixer is applied to both Policy and Telemetry

### ISSUE THREAD

**Issue by jizh6311** [istio/istio#22087]
**Describe the feature request**
When istio-policy and istio-telemetry both have two replica count, their two pods can be scheduled to different nodes, but one policy and one telemetry can be scheduled to the same node. 

PodAntiAffinity under Mixer is currently applied to both Policy and Telemetry so policy and telemetry can not be on the same node.

**Describe alternatives you've considered**
- Put PodAntiAffinity under Policy and Telemetry but not under Mixer
- Maybe another workaround in the existing configurations?

**Additional context**

**Comment by douglas-reid** [comment]
Unless @jacob-delgado is planning on adding this to 1.7, I believe this issue has unfortunately been overcome by events. Mixer is now deleted from the codebase. Closing this issue. Please re-open if work is planned for 1.7.
