### ISSUE TITLE
Stop creating Istio configuration as part of Installation

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#22095]
Currently, we install a few Istio configurations during install. This has a number of issues:

* It overloads the install phase to include configuration of the mesh, making it confusing for a user to understand when they should reinstall and when they should configure some CR
* It makes users re-install for things like changing mTLS, which should be done through a configuration instead
* It makes the installation more complicate, especially with validation webhook ordering
* It moves away from the "zero config" install experience we want

We have configs for:

mTLS: https://github.com/istio/istio/pull/22086 starts this effort to remove these
Gateway: we install default gateways like https://github.com/istio/istio/blob/80fc771a52ec5ca90e37267a9822de3d95e41a69/manifests/gateways/istio-ingress/templates/gateway.yaml#L4, which cause confusion AND break some people by causing conflicts with no way to disable
EnvoyFilter: telemetry v2 is all configured via EnvoyFilter
Mesh expansion: a bunch of stuff like https://github.com/istio/istio/blob/2fcbf311508dd9db75febaf0712eda3a81fbe264/manifests/gateways/istio-ingress/templates/meshexpansion.yaml#L2
Certs: we even have certmanager CRs: https://github.com/istio/istio/blob/80fc771a52ec5ca90e37267a9822de3d95e41a69/manifests/gateways/istio-ingress/templates/certificate.yaml#L22

We should begin the process of cleaning these up (and ensuring appropriate corresponding documentation exist)

cc @costinm

**Comment by howardjohn** [comment]
For envoyfilters, things are a bit more complicated, as I would image the UX/P&T group does not want an extra step for the user to manually apply these filters to get telemetry (?). Some rough possible ideas:

* Create a separate chart, so they are at least isolated from istiod core install
* Ship a telemetryv2.yaml file that users can manually apply to their cluster after install
* Have native support for v2 without configuring EnvoyFilters
* Have Istiod come bundled with a set of default configurations as files. These can be overridden with a configmap mounted on the deployment if customization is needed

**Comment by rshriram** [comment]
We also have bunch of templates under the gateway to autogenerate Istio gateway and virtual services based on the hosts!!!! This needs to be removed. Its utterly brittle

**Comment by howardjohn** [comment]
@rshriram https://github.com/istio/istio/pull/22256 should take care of that one

**Comment by nak3** [comment]
On 1.5.2, istioctl still creates `Gateway` but in this time it has the same name with `ingressGateway`'s name. It is the final fix? Or can we completely remove the Gateway in the future?

**Comment by howardjohn** [comment]
@nak3 1.6 will remove it completely. I am not sure it was the right move to not remove it in 1.5.2, but we are hesitant to make changes like that in patch releases - although apparently we renamed it, I was not aware of that. Sorry for any pain this is causing

**Comment by howardjohn** [comment]
This is pretty much done other than mesh expansion

**Comment by howardjohn** [comment]
@tbarrella is working on the mesh expansion stuff

**Comment by howardjohn** [comment]
remaining work:
Envoy filters - https://docs.google.com/document/d/1f_emnIfPX3i_rLFzNYmUQvsKxuUknXWv_qJZ3RYBn9U/edit
Mesh expansion - https://github.com/istio/istio/issues/25933

**Comment by howardjohn** [comment]
not stale until EnvoyFilter is gone

**Comment by howardjohn** [comment]
not stale until EnvoyFilter is gone

**Comment by howardjohn** [comment]
Old issue, but as of https://github.com/istio/istio/pull/47892 this is finally 100% done. Yay
