### ISSUE TITLE
IstioOperator "revision" field non-empty suppresses install of istiod

### ISSUE THREAD

**Issue by esnible** [istio/istio#22091]
https://istio.io/docs/reference/config/istio.operator.v1alpha1/#IstioOperatorSpec documents the `revision` field as "Identify the revision this installation is associated with. This option is currently experimental."

Installing with `istioctl manifest apply --set revision=rev1` reports "✔ Finished applying manifest for component Pilot." but `kubectl -n istio-system get deployments` shows no istiod deployment.

If there is another work item for this, let me know and I will close this as a duplicate.  For me, being able to install two control planes is key to doing all of the istioctl troubleshooting command changes for 1.6.

Support for `--set revision=rev1` is key for https://github.com/istio/istio/issues/21934 and https://github.com/istio/istio/issues/21118

`istioctl profile dump | grep -i revision` produces no output.

**Comment by howardjohn** [comment]
this will be fixed by https://github.com/istio/istio/pull/22056
