### ISSUE TITLE
manifest generate test coverage

### ISSUE THREAD

**Issue by richardwxn** [istio/istio#22094]
I found out we do not have enough coverage of the manifest generate test, some of the issues I found:
1. many of the k8s setting override are not tested, many user complaints actually came from failure to do k8s override.
2. There are override in the test input file, but the selection to compare from output is not correct, e.g. there is test input with override of serviceannotations but the test does not select the service object to compare.

**Comment by howardjohn** [comment]
We have been discussing whether these auto generated golden file tests are a good idea at all. Can we add test coverage without relying on golden files?

**Comment by esnible** [comment]
Related: https://github.com/istio/istio/issues/21770

**Comment by howardjohn** [comment]
We have added a number of tests here. I think this can be considered resolved. If not, we have many testing issues open for specific areas
