### ISSUE TITLE
--set addonComponents.<component>.enabled is case-sensitive

### ISSUE THREAD

**Issue by esnible** [istio/istio#22092]
To reproduce, notice that
`istioctl manifest generate --set components.base.enabled=false --set components.pilot.enabled=false --set addonComponents.prometheus.enabled=false --set components.ingressGateways[0].enabled=false` produces only comments, but if we use `--set addonComponents.Prometheus.enabled=false` we still get a Prometheus.

The names are checked, e.g. `--set addonComponents.promethios.enabled=false` will fail with "Asset charts/addons/promethios not found".

Either the chart checking should be case sensitive or the disabling should be case insensitive.

**Comment by morvencao** [comment]
Looks like only addon components have such issue. For core component, such as pilot, validation will return error:
```
istioctl manifest generate --set components.Pilot.enabled=false -o istio-manifests
Error: validation errors (use --force to override):
error unmarshaling JSON: unknown field "Pilot" in v1alpha1.IstioComponentSetSpec:
```
