### ISSUE TITLE
make fails with `multiple target patterns` on mac

### ISSUE THREAD

**Issue by richardwxn** [istio/istio#22096]
Tried multiple make command on mac all failed with "Makefile.overrides.mk:26: *** multiple target patterns.  Stop." It happened for both container build or local build.

**Comment by esnible** [comment]
There are two ways to build on a Mac, with `BUILD_WITH_CONTAINER=1` and without/`BUILD_WITH_CONTAINER=0`.  Which are you using?

I am able to `make istioctl` with both variants.  I may have installed a few GNU utilities on my Mac.  These are some things I had to do at one point to build Istio; now that I have done them I don't know if they are still needed.

```
brew install shellcheck
brew upgrade bazel
xcode-select --install
brew install yamllint
brew install findutils
ln -s /usr/local/Cellar/findutils/4.7.0/bin/gxargs /usr/local/bin/xargs
```

**Comment by richardwxn** [comment]
I tried both container and local build and they had the same error.

I didn't change my mac environment setup and the make command worked well before. So I am wondering whether it is introduced by some recent change of build system.
