### ISSUE TITLE
Add pre-submit job for perf test

### ISSUE THREAD

**Issue by carolynhu** [istio/istio#22109]
To make it more efficient and avoid waiting another day to find some perf pipeline issues introduced by new commits. We need to add small/short runs pre-submit job for our perf test. It means that when a new PR includes changes related to perf test (like modifying runner.py), we can find the issue and block the merge. 

/cc @mandarjog @richardwxn @howardjohn

**Comment by richardwxn** [comment]
I think at lease it should cover the parts of: required: cluster setup, istio installation, application setup and optional: if new configs added(run the installation and setup script there and run a short period of time for benchmark)

**Comment by richardwxn** [comment]
Next step I would switch to use Kind instead of boskos for the presubmit job

**Comment by richardwxn** [comment]
Closing it as the presubmit job is stable now
