### ISSUE TITLE
Istiod may fail to validate xds client cert when using custom CAs

### ISSUE THREAD

**Issue by myidpt** [istio/istio#22103]
**Bug description**
In V1.5, the istiod XDS server is verifying client cert if given:
https://github.com/istio/istio/blob/release-1.5/pilot/pkg/bootstrap/server.go#L692
Envoys have the XDS configured to always conduct mTLS to istiod:
https://github.com/istio/istio/blob/release-1.5/tools/packaging/common/envoy_bootstrap_v2.json#L276

If Envoys get key/cert from custom CAs (through istio-agent), istiod doesn't know the root CA. This results in istiod failing to authenticate the client through mTLS.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ X ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
When using custom CA, Envoy should not do mTLS to istiod, instead, it should do TLS.

**Steps to reproduce the bug**
Configure istio-agent to retrieve certificates from custom CAs, such as Vault.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.5

**How was Istio installed?**
istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by incfly** [comment]
Sounds like the plumbing of customized root cert is not properly done in istiod side. An integration test of using customized CA/root feature can & should help catch this.
