### ISSUE TITLE
Support RTDS ??

### ISSUE THREAD

**Issue by zengyuxing007** [istio/istio#22119]
Envoy provides the rtds interface （https://github.com/envoyproxy/data-plane-api/blob/master/envoy/service/discovery/v2/rtds.proto）,  through which you can dynamically configure some runtime configuration.such as global switches for ratelimit filter;
Does the pilot support this interface?

[* ] Configuration Infrastructure

**Comment by howardjohn** [comment]
No, we do not currently implement this. Can you explain your use case for this API?

**Comment by Eneminemoe** [comment]
I'd be interested in this too. Especially I'd like to set [envoy release notes](https://www.envoyproxy.io/docs/envoy/latest/intro/version_history) 
Search for:
"http: blocks unsupported transfer-encodings. Can be reverted temporarily by setting runtime feature envoy.reloadable_features.reject_unsupported_transfer_encodings to false"
`envoy.reloadable_features.reject_unsupported_transfer_encodings`
Is there another possibility to so?

**Comment by howardjohn** [comment]
If you need to do this you can do it in bootstrap: https://github.com/istio/istio/blob/03e89d4fb372c5e29773c0aedbe05d229dad3dc7/tools/packaging/common/envoy_bootstrap.json#L24

See samples/custom-bootstrap for overriding this.

I don't think we have any plans to expose these low level details as part of our first class API.
