### ISSUE TITLE
Need one more node to install Security when podAntiAffinity applied

### ISSUE THREAD

**Issue by jizh6311** [istio/istio#22128]
**Bug description**
If podAntiAffinity is applied, Security will always require one more node as `istio-security-post-install` pod is also under the same AntiAffinity: https://github.com/istio/istio/blob/release-1.5/install/kubernetes/helm/istio/charts/security/templates/create-custom-resources-job.yaml#L101. If nodes are not sufficient, `istio-security-post-install`will get into crashloopbackoff and istio install will finally get:
```
Error: timed out waiting for the condition
```

But this pod will be deleted after successful istio install. Is it really necessary? 

[X] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[] Developer Infrastructure

**Expected behavior**
Istio Install can be successful without one more node

**Steps to reproduce the bug**
1. Add a podAntiAffinity to Security.
2. Create a Kube Cluster with the same number of nodes as Security Replica count
3. Install Istio

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
Helm v2.16.1 (should be in version 3 as well)

**How was Istio installed?**
Helm

**Environment where bug was observed (cloud vendor, OS, etc)**
All

**Comment by howardjohn** [comment]
This job has been removed in master already, so I don't think there is any action we need to take here

**Comment by jizh6311** [comment]
@howardjohn Thanks good to know that!
