### ISSUE TITLE
"istioctl x describe" reports incorrect ingress port number

### ISSUE THREAD

**Issue by esnible** [istio/istio#22125]
`istioctl x describe service productpage`

reports

```
...
Exposed on Ingress Gateway http://169.61.18.10:8080
...
```

The actual port is 80.  Using IBM Cloud

Istio installed with default profile, daily build latest, and `--set values.global.pilotCertProvider=kubernetes`

**Comment by howardjohn** [comment]
We change this so 8080 is the application port, 80 is the service port. So it should show :80 as you mentioned

**Comment by esnible** [comment]
@howardjohn The port is suppressed from the output if it is 80.

**Comment by esnible** [comment]
Closing because https://github.com/istio/istio/pull/22129 fixed it.
