### ISSUE TITLE
Istio 1.5 inaccurate telemetry due to rogue consumer in control panel (may be)

### ISSUE THREAD

**Issue by prageethw** [istio/istio#22144]
I used istio telemetry to enable custom metrics and feed into HPA to enabled auto-scaling.It was working great in 1.4.x, but it seems some issues in 1.5.

**Bug description**
Random unusual numbers showing in Prometheus, for example, even when there is no traffic from a real consumer at all it still shows unusual traffic still directed at pods, further analysis shows some rogue consumer being generated when I enable sidecar proxies, my feeling is this is coming from istio control panel.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[x ] Performance and Scalability
[x ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Expected behavior**
When there is no real traffic generated, there should no rogue consumer creating traffic to pods.
**Steps to reproduce the bug**

- Install istio demo profile
- Enable sidecar proxies and install app.
- Generate some traffic to app.
- Stop traffic and wait for some time
- Check kiali and you will still see some rogue consumer sending traffic to pods.
- Run a query in Prometheus you will see the same.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
istioctl version --remote
client version: 1.5.0
control plane version: 1.5.0
data plane version: 1.5.0 (9 proxies)
```
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-13T18:08:14Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.9", GitCommit:"2e808b7cb054ee242b68e62455323aa783991f03", GitTreeState:"clean", BuildDate:"2020-01-18T23:24:23Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
**How was Istio installed?**
istioctl generate manifest

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS KOPS

refer to the image.

<img width="781" alt="Screen Shot 2020-03-13 at 10 44 20 am" src="https://user-images.githubusercontent.com/24377789/76577193-9f08dc80-6518-11ea-9c8d-bf9647cca884.png">

**Comment by bianpengyuan** [comment]
One difference between mixer based telemetry in 1.4.x and telemetry v2 in 1.5 is that liveness/readiness check is captured (which is the unknown source in kiali graph). Can you confirm you have liveness/readiness prober set up for your go-demo? Does the metric make your HPA overprovision?

**Comment by prageethw** [comment]
@bianpengyuan Thanks for confirming the behavior, yep it does have health checks, closing this as this is expected behavior.
