### ISSUE TITLE
Update old dependencies

### ISSUE THREAD

**Issue by costinm** [istio/istio#2214]
The new go dep build system pulls most dependencies automatically, however we still have few 
old that have been pinned since more recent versions don't seem to work.

We need to investigate and fix the code, to use current version (and possibly remove the dep
on blackfriday, it doesn't seem needed). All seem related to pilot.

[[constraint]]
  name = "google.golang.org/grpc"
  revision = "f92cdcd7dcdc69e81b2d7b338479a19a8723cfa3"

[[constraint]]
  name = "k8s.io/client-go"
  revision = "7c69e980210777a6292351ac6873de083526f08e"

[[constraint]]
  name = "k8s.io/ingress"
  revision = "0c6f15e372c831de52fcc393932540bb3a6d51b5"

[[constraint]]
  name = "github.com/russross/blackfriday"
  revision = "4048872b16cc0fc2c5fd9eacf0ed2c2fedaa0c8c"

**Comment by andraxylia** [comment]
The blackfriday is used only when the build is on a MAC system, but we still needed, it's an indirect dependency from another library.

**Comment by ayj** [comment]
> name = "k8s.io/client-go"
> revision = "7c69e980210777a6292351ac6873de083526f08e"

`7c69e98` of `k8s.io/client-go` corresponds to k8s version 1.8. Moving to master brings in 1.9 support and removes some of the alpha API we're using for validation. See https://github.com/istio/istio/issues/2177 for details.

**Comment by andraxylia** [comment]
Fixed by multiple commits.
