### ISSUE TITLE
Istio 1.5 proxy cannot talk to 1.4 proxy after upgrade

### ISSUE THREAD

**Issue by kramvan1** [istio/istio#22143]
**Bug description**

After upgrade to 1.5, existing 1.4 mesh pods get 503's, logs show a CERTIFICATE_VERIFY_FAILED

[proxy.log](https://github.com/istio/istio/files/4326632/proxy.log)

1.4 Default profile,  did not have SDS or mtls auto disabled
1.5 Default profile, SDS enabled and mtls auto enabled

**Expected behavior**

A existing mesh pod with the 1.4.x proxy should be working with 1.5 control plane.

**Steps to reproduce the bug**

- Install 1.4.6 with default profile
- setup bookinfo sample
```
  kubectl label namespace default istio-injection=enabled
  kubectl apply -f ${ISTIO_ROOT_PATH}/samples/bookinfo/platform/kube/bookinfo.yaml
  kubectl apply -f ${ISTIO_ROOT_PATH}/samples/bookinfo/networking/bookinfo-gateway.yaml
  kubectl apply -f ${ISTIO_ROOT_PATH}/samples/bookinfo/networking/destination-rule-all.yaml
```
- check bookinfo sample
```
export INGRESS_HOST=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
export INGRESS_PORT=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="http2")].port}')
export GATEWAY_URL=$INGRESS_HOST:$INGRESS_PORT
curl -o /dev/null -s -w "%{http_code}." http://$GATEWAY_URL/productpage

200
```
- Upgrade to istio 1.5
- Check bookinfo sample
```
curl -o /dev/null -s -w "%{http_code}." http://$GATEWAY_URL/productpage
```

If I restart the bookinfo pods, it starts working again.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

Start at 1.4.6
Upgrade to 1.5.0

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by kramvan1** [comment]
cc @howardjohn @linsun @rvennam 

@GregHanson could you add more details that were discussed  today?

**Comment by howardjohn** [comment]
```
[Envoy (Epoch 0)] [2020-03-12 21:07:00.165][31][debug][pool] [external/envoy/source/common/http/http1/conn_pool.cc:95] creating a new connection
[Envoy (Epoch 0)] [2020-03-12 21:07:00.165][31][debug][client] [external/envoy/source/common/http/codec_client.cc:34] [C40] connecting
[Envoy (Epoch 0)] [2020-03-12 21:07:00.165][31][debug][connection] [external/envoy/source/common/network/connection_impl.cc:698] [C40] connecting to 172.30.71.11:9080
[Envoy (Epoch 0)] [2020-03-12 21:07:00.165][31][debug][connection] [external/envoy/source/common/network/connection_impl.cc:707] [C40] connection in progress
[Envoy (Epoch 0)] [2020-03-12 21:07:00.165][31][debug][pool] [external/envoy/source/common/http/conn_pool_base.cc:55] queueing request due to no available connections
[Envoy (Epoch 0)] [2020-03-12 21:07:00.182][31][debug][connection] [external/envoy/source/common/network/connection_impl.cc:570] [C40] connected
[Envoy (Epoch 0)] [2020-03-12 21:07:00.182][31][debug][connection] [external/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc:191] [C40] handshake expecting read
[Envoy (Epoch 0)] [2020-03-12 21:07:00.184][31][debug][connection] [external/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc:198] [C40] handshake error: 1
[Envoy (Epoch 0)] [2020-03-12 21:07:00.184][31][debug][connection] [external/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc:226] [C40] TLS error: 67108971:RSA routines:OPENSSL_internal:BLOCK_TYPE_IS_NOT_01 67109000:RSA routines:OPENSSL_internal:PADDING_CHECK_FAILED 184549382:X.509 certificate routines:OPENSSL_internal:public key routines 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
[Envoy (Epoch 0)] [2020-03-12 21:07:00.184][31][debug][connection] [external/envoy/source/common/network/connection_impl.cc:192] [C40] closing socket: 0
[Envoy (Epoch 0)] [2020-03-12 21:07:00.184][31][debug][client] [external/envoy/source/common/http/codec_client.cc:91] [C40] disconnect. resetting 0 pending requests
[Envoy (Epoch 0)] [2020-03-12 21:07:00.184][31][debug][pool] [external/envoy/source/common/http/http1/conn_pool.cc:136] [C40] client disconnected, failure reason: TLS error: 67108971:RSA routines:OPENSSL_internal:BLOCK_TYPE_IS_NOT_01 67109000:RSA routines:OPENSSL_internal:PADDING_CHECK_FAILED 184549382:X.509 certificate routines:OPENSSL_internal:public key routines 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
[Envoy (Epoch 0)] [2020-03-12 21:07:00.184][31][debug][pool] [external/envoy/source/common/http/http1/conn_pool.cc:166] [C40] purge pending, failure reason: TLS error: 67108971:RSA routines:OPENSSL_internal:BLOCK_TYPE_IS_NOT_01 67109000:RSA routines:OPENSSL_internal:PADDING_CHECK_FAILED 184549382:X.509 certificate routines:OPENSSL_internal:public key routines 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
[Envoy (Epoch 0)] [2020-03-12 21:07:00.184][31][debug][router] [external/envoy/source/common/router/router.cc:990] [C38][S11520787698384007696] upstream reset: reset reason connection failure
[Envoy (Epoch 0)] [2020-03-12 21:07:00.184][31][debug][router] [external/envoy/source/common/router/router.cc:1357] [C38][S11520787698384007696] performing retry
[Envoy (Epoch 0)] [2020-03-12 21:07:00.257][31][debug][pool] [external/envoy/source/common/http/http1/conn_pool.cc:95] creating a new connection
[Envoy (Epoch 0)] [2020-03-12 21:07:00.257][31][debug][client] [external/envoy/source/common/http/codec_client.cc:34] [C41] connecting
[Envoy (Epoch 0)] [2020-03-12 21:07:00.257][31][debug][connection] [external/envoy/source/common/network/connection_impl.cc:698] [C41] connecting to 172.30.71.11:9080
[Envoy (Epoch 0)] [2020-03-12 21:07:00.257][31][debug][connection] [external/envoy/source/common/network/connection_impl.cc:707] [C41] connection in progress
[Envoy (Epoch 0)] [2020-03-12 21:07:00.257][31][debug][pool] [external/envoy/source/common/http/conn_pool_base.cc:55] queueing request due to no available connections
[Envoy (Epoch 0)] [2020-03-12 21:07:00.258][31][debug][connection] [external/envoy/source/common/network/connection_impl.cc:570] [C41] connected
[Envoy (Epoch 0)] [2020-03-12 21:07:00.258][31][debug][connection] [external/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc:191] [C41] handshake expecting read
[Envoy (Epoch 0)] [2020-03-12 21:07:00.260][31][debug][connection] [external/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc:198] [C41] handshake error: 1
[Envoy (Epoch 0)] [2020-03-12 21:07:00.260][31][debug][connection] [external/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc:226] [C41] TLS error: 67108971:RSA routines:OPENSSL_internal:BLOCK_TYPE_IS_NOT_01 67109000:RSA routines:OPENSSL_internal:PADDING_CHECK_FAILED 184549382:X.509 certificate routines:OPENSSL_internal:public key routines 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
[Envoy (Epoch 0)] [2020-03-12 21:07:00.260][31][debug][connection] [external/envoy/source/common/network/connection_impl.cc:192] [C41] closing socket: 0
[Envoy (Epoch 0)] [2020-03-12 21:07:00.260][31][debug][client] [external/envoy/source/common/http/codec_client.cc:91] [C41] disconnect. resetting 0 pending requests
[Envoy (Epoch 0)] [2020-03-12 21:07:00.260][31][debug][pool] [external/envoy/source/common/http/http1/conn_pool.cc:136] [C41] client disconnected, failure reason: TLS error: 67108971:RSA routines:OPENSSL_internal:BLOCK_TYPE_IS_NOT_01 67109000:RSA routines:OPENSSL_internal:PADDING_CHECK_FAILED 184549382:X.509 certificate routines:OPENSSL_internal:public key routines 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
[Envoy (Epoch 0)] [2020-03-12 21:07:00.260][31][debug][pool] [external/envoy/source/common/http/http1/conn_pool.cc:166] [C41] purge pending, failure reason: TLS error: 67108971:RSA routines:OPENSSL_internal:BLOCK_TYPE_IS_NOT_01 67109000:RSA routines:OPENSSL_internal:PADDING_CHECK_FAILED 184549382:X.509 certificate routines:OPENSSL_internal:public key routines 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
[Envoy (Epoch 0)] [2020-03-12 21:07:00.260][31][debug][router] [external/envoy/source/common/router/router.cc:990] [C38][S11520787698384007696] upstream reset: reset reason connection failure
[Envoy (Epoch 0)] [2020-03-12 21:07:00.260][31][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:1417] [C38][S11520787698384007696] Sending local reply with details upstream_reset_before_response_started{connection failure,TLS error: 67108971:RSA routines:OPENSSL_internal:BLOCK_TYPE_IS_NOT_01 67109000:RSA routines:OPENSSL_internal:PADDING_CHECK_FAILED 184549382:X.509 certificate routines:OPENSSL_internal:public key routines 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED}
[Envoy (Epoch 0)] [2020-03-12 21:07:00.260][31][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:1615] [C38][S11520787698384007696] encoding headers via codec (end_stream=false):
':status', '503'
'content-length', '91'
'content-type', 'text/plain'
'date', 'Thu, 12 Mar 2020 21:06:59 GMT'
'server', 'envoy'

```

relevant part of the logs ^

**Comment by howardjohn** [comment]
Probably want to compare the certs on 1.4 to 1.5. I think `istioctl pc secret` is the easiest way to do that, might only work for the 1.5 pod. For 1.4 you can get it from /etc/certs

**Comment by kramvan1** [comment]
@howardjohn how would 1.4 pod have access to new secrets?    I think it's the new 1.5 ingress secrets that are causing the issue, 1.4 pod to 1.4 pod is ok.      How would the new 1.5 ingress work with the 1.4 pod?

**Comment by howardjohn** [comment]
They (should) have compatible certs, they are just delivered differently

**Comment by howardjohn** [comment]
Is this broken in 100% of 1.4 -> 1.5 cases for you? I have tested this and no one else has mentioned this so I am wondering if it may be something specific you are doing in your environment?

**Comment by rvennam** [comment]
How can we check if they are compatible?

1.5 pod:
```
./istioctl pc secret sleep-f8cbf5b76-d4jk6
RESOURCE NAME     TYPE           STATUS     VALID CERT     SERIAL NUMBER                               NOT AFTER                NOT BEFORE
default           Cert Chain     ACTIVE     true           224501391991402673498800554151344660684     2020-03-13T20:57:04Z     2020-03-12T20:57:04Z
ROOTCA            CA             ACTIVE     true           32831152148052248768876811106665469281      2030-03-10T20:46:00Z     2020-03-12T20:46:00Z
```
1.4 pod:
```
kubectl exec -it productpage-v1-596598f447-p5twj -c istio-proxy -- ls /etc/certs
cert-chain.pem	key.pem  root-cert.pem
```

**Comment by kramvan1** [comment]
Yes, for our upgrade path, it's always broken.    Restarting the old 1.4 pods or DISABLE mtls auto in the destination rule will allow the traffic.

**Comment by kramvan1** [comment]
My 1.4 pod
```
$ kubectl exec -it productpage-v1-85b9bf9cd7-t8stv  -c istio-proxy -- ls /etc/certs
ls: cannot access '/etc/certs': No such file or directory
command terminated with exit code 2
```

**Comment by howardjohn** [comment]
@incfly @myidpt what is the best method to troubleshoot cert issues? Do we have any docs?

**Comment by incfly** [comment]
i haven't been able to repro this issue myself (using default istio 1.4.6 to 1.5.0). here are some info if anyone want to go further, roughly

- 1.5, bin/istioctl pc secret <pod-id> -ojson
  - in the "default" secret, inline_bytes section, copy paste that 
  - echo 'LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRakNDQWlxZ0F3SUJBZ0lSQU5hK09uZ1ZySVlITmlmdHhZQk56VGN3RFFZSktvWklodmNOQVFFTEJRQXcKR0RFV01CUUdBMVVFQ2hNTlkyeDFjM1JsY2k1c2IyTmhiREFlRncweU1EQXpNVEl5TWpBM01USmFGdzB5TURBegpNVE15TWpBM01USmFNQUF3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRREpPUWZWCkNrREYxbHRGUHZrY3VlRCtNQ0FxTGEvMGlwL3lIUFF3WXhWNEN4SVhaSVJNYXc1aDdMSlBQVmJhbS9hSDhrYkwKeTRKV0VGU01oMldqRVU1dEVaVkpFQ2tNb1lINmRqMitES2V0bEFKcjluY1hZNXdyQnFJY3ZVN002K3dodzlMagppUjNkdG03dEFaUEJYRkdLaENmUUZKUWhMUkhTazloblhKQWZLdXZlQU40WW5aSC9kV3RNbVg4QmVsKzBEMXVjCmdQcEl2ZG9nKzFRRklLQmN3eXRYQk5oRnp5c2YvQXhwNW1TRDVuZytnNzY5NkZhcDlMWjZNTlZUd0c4SFBtVngKM3NBcXVuVTZqdW5peWNJK21ZMjFxdmpQQldPUTJQRHBITFVIaE5xQmJWSm81ajJVVHhxY2hucnVmeStRWTRYZgp0M1Mwdy81dlZQQmIxMUNKQWdNQkFBR2pnWjR3Z1pzd0RnWURWUjBQQVFIL0JBUURBZ1dnTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQU1Gd0dBMVVkRVFFQi93UlMKTUZDR1RuTndhV1ptWlRvdkwyTnNkWE4wWlhJdWJHOWpZV3d2Ym5NdmFYTjBhVzh0YzNsemRHVnRMM05oTDJsegpkR2x2TFdsdVozSmxjM05uWVhSbGQyRjVMWE5sY25acFkyVXRZV05qYjNWdWREQU5CZ2txaGtpRzl3MEJBUXNGCkFBT0NBUUVBUkRMMHJkU2lIdjl3Zzk3Ym13MlpibWFrRXJlN3FaRmh5YkJValpHTlNGYnFuaEtiTXArWWRUOUMKUzlYZVdHbWx2dklBTkpFalJUU0t4NHpndkY4ZG9LTjkzTVZYdUtjMjRQaVczNzhsOS9ZbmpERkhOUmtLclo1SAovYVFrTEpEMXI2SGlTQTBkMXVQcHUwRGdLWmdnLzJqZmtZdHdNRGp0R3M2VnY0MEFzRDFvS0ZXbXV5bi9ySW9sCnNESzBFa1pSbUV0UDBoZ2dCWEYyd0tPSUVDaUErbmxOT1NLbWUrdy9lNnJkb3RGd1RkS2NudkZDUm1jM3pUVEoKZndiTDhSSEF4bDZQcGJmM29TZHZMUVROZU1RYVdPc0QweDZWY1JVcDdhSzRvYXlFT1BjbEZjcmtLNWIxcDZEdAphOWt4ZWlXaUJqQlk5YXNLdXNjZm5YN05PQzNpa3c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDM2pDQ0FjYWdBd0lCQWdJUkFKOEVzTG5IR2Y2WlIwcmdQaXpicGdZd0RRWUpLb1pJaHZjTkFRRUxCUUF3CkdERVdNQlFHQTFVRUNoTU5ZMngxYzNSbGNpNXNiMk5oYkRBZUZ3MHlNREF6TVRJeU1qQXpORGhhRncwek1EQXoKTVRBeU1qQXpORGhhTUJneEZqQVVCZ05WQkFvVERXTnNkWE4wWlhJdWJHOWpZV3d3Z2dFaU1BMEdDU3FHU0liMwpEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUNmbE9YQ1JPdXBjaEZWbkFFZTlheDFKVVRlUzJYUG1MSGwxZk1TCllRYitBZ3NVTWt3VjNycDkwNm5vbWlISFZFQ1hNSUIwWUdILzFzZ3BrNEFyUTRnLzJGWW8wWS9PdDRxZmk4RWUKLzQwSTlxcENSR1gyQVVndVg3MXVwUkI2QkM3clpVVytCMjcrY1dOUk5pUWJxQ3VwZW9PYXpsd2k3TkVFM1p1QgpCUlFxSjF6RTNocS8yTjZ3WDVSNzAvMTZNL0lWZ3ZXSFJRdnlKaXFMUlkrUEtpaW5GSWtoWUNScUpuRktpNUh3ClNhWjZnZDNnMG1TQ25xRGlHT3RvaEhmRWpJciszMkNPVlptYU9QUGY4c25CTWxDeUtIdHFSVCtRc0NGT2J1aUgKWVNnQVpnMGdJMy9UMmVNZ2lmd1lDa2lHK1hTOGNNSlUvN0RDN3ZJT2cyWTJYcjkvQWdNQkFBR2pJekFoTUE0RwpBMVVkRHdFQi93UUVBd0lDQkRBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCCkFRQ0RsdlZQK01CL3ZCTy9FTzdxV09KS2dQQm5heVRJRWFUbWo4MmxzVGdxdWtDNkFGVFZTNHUwWXJXMWdaajgKZFpkdU5qVnZRb0pnajVITnh1Q1BpUGFyWm13dGF0dktvSmY1YU5FdC9mR0tpS2hoUjh6ajlIbjJlNHh2WHN6Rgoxays2a2dROTgweVl0bDF1RHRpTHB4RVY0WE9BQUNpUUU0TmlJZFAvYi9rZ2N3cHhST2FINDJNendORjg1NU44CnZlNVNPR2FUSE4yYTltN0xObWV5RVN4UzR5dThUckN4UlBEdzRUWm82NmlNbzdZOFBPRW1mYmR4T2wyUURGdDQKVnZNTlR0azdJOFRJRUNMckFHZjZIQTlkUUcvSlVpSWw4b2pUUEoveUhxcmJHMWhyelh3OElzSWNxcng0MFpaTApjeUF6VjFteGwyY29IQWx2QldoRlBoOHMKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo' | base64 --decode > cert-1.5.pem
  - now get 1.4 root cert, `k exec -it pod -c istio-proxy -- cat /etc/certs/root.pem > root-1.4.pem`
  - use `openssl verify` to verify the cert-1.5.pem against root-1.4.pem.

maybe vice versa as well. using 1.5 root to verify 1.4 cert.

if above turns valid, we might need to look into envoy internal, see what's going on...

**Comment by incfly** [comment]
tentatively assign to @myidpt for now. anyone impacted by the issue can also explore my steps above.

**Comment by incfly** [comment]
sidenote, we probably indeed need a better way of doing this comparison, don't know if istioctl support -ojsonpath, will be much better if so.

**Comment by howardjohn** [comment]
`-ojson | jq ...` is good enough for many things in the mean time

**Comment by myidpt** [comment]
I think the instructions provided by @incfly is the best way to verify. @kramvan1 @rvennam Please post your 1.4 and 1.5 certs here if you can't figure out why.

**Comment by kramvan1** [comment]
@myidpt thx, looks like our 1.4 ca cert is not maintained, will check on fixing that.
