### ISSUE TITLE
Update Homebrew formula for OSX install

### ISSUE THREAD

**Issue by esnible** [istio/istio#22158]
See https://github.com/Homebrew/homebrew-core/pull/51193

See also https://formulae.brew.sh/formula/istioctl

This isn't something we fix in https://github.com/istio/istio , we must fix it in Homebrew.

**Comment by rytswd** [comment]
As v1.5.1 was released, I have created a new PR with v1.5.1 Homebrew/homebrew-core/pull/52150.
(Homebrew/homebrew-core#51193 has been closed for that reason.)

It seems there was some build process change introduced with v1.5+, and thus required some fix on the script on Homebrew side.
This would mean that v1.5.0 won't be available on Homebrew archive - I suppose as long as the latest minor version (v1.5.1 as of now) is available, it wouldn't be a huge concern?

**Comment by esnible** [comment]
@rytswd Thank you!

1.5.x should be compatible with 1.5.0.  We shouldn't need back-level CLIs on Homebrew.

**Comment by rytswd** [comment]
This has been merged with https://github.com/Homebrew/homebrew-core/commit/429cae217243e964c3718a019027d3adf8afd6d2.

I'm not too familiar with the steps for closing issue tickets like this, but as I understand the scope of this ticket is complete, I'm closing this ticket. If I have missed any details, extra information, etc., please do let me know and reopen as necessary!
