### ISSUE TITLE
Unclear what can be customized in ingress settings

### ISSUE THREAD

**Issue by esnible** [istio/istio#22156]
I tried to install Istio with `istioctl manifest apply --set hub=gcr.io/istio-testing --set tag=latest
  --set components.ingressGateways[0].k8s.service.ports[0].port=51555` to see if I could customize the port for troubleshooting an issue.  Setting the port here caused the Ingress to vanish.

I also tried `istioctl profile dump | yq '.spec.components.ingressGateways[0].k8s.service'` and got null

My thought is that the default profile should be holding settings for these so that values can be modified without triggering "tpath" code to create new structures.  However, this should also work if ingressGateways[1] is used, and there is no default.  I suspect this implies that something should be supplying initial values to structures created by tpaths that implicitly extend lists.

**Comment by ostromart** [comment]
At first glance I think what is happening is the new gateway overlay done with set is not correctly merged with the default ingressgateway values. I seems to be overwriting the existing defaults for the ingress rather than merging.

**Comment by ostromart** [comment]
btw. I think this affects only --set.

**Comment by esnible** [comment]
@ostromart are there defaults for `k8s.service`?

`istioctl profile dump | yq '.spec.components.ingressGateways[0].k8s'` doesn't show service, and `istioctl profile dump | yq '.spec.components.ingressGateways[0].k8s.service'` gets `null`.

**Comment by ostromart** [comment]
@esnible there were no services before but they were added in https://github.com/istio/istio/pull/22328.
The service problem is likely fixed as a result but I feel like there's still some lingering issue here that I can't put my finger on.
