### ISSUE TITLE
Kubernetes DNS cert signing using Kubernetes API in unsupported way

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#22161]
See https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/20190607-certificates-api.md for context.

The API is explicitly NOT intended to be used the way we currently use it. There are multiple issues.

The first, which we already knew, is

> Distribution of trust happens out of band for these signers. Any trust outside of those described above are strictly coincidental. For instance, some distributions may honor kubernetes.io/legacy-unknown as client-certificates for the kube-apiserver, but this is not a standard. None of these usages are related to ServiceAccount token secrets .data[ca.crt] in any way. That ca-bundle is only guaranteed to verify a connection the kube-apiserver using the default service.

This means this may break at any time and will only work on some Kubernetes providers that just so happen to use the same CA for both. We already know this is not the case for many.

The other issue is expecting the Kubernetes CA to accept our CSRs in the first place. Look at https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/20190607-certificates-api.md#signers, these are intended for internal usage, not what we are doing. See the signer names like `kubernetes.io/kube-apiserver-client-kubelet`. We get away with this by using `kubernetes.io/legacy-unknown`, which happens to sort of work but is likely to be **removed** in the `v1` API.

The intent of this API is to allow *other* signers, like cert-manager, to sign certs. It is not meant to be used the way we use it.

cc @costinm @linsun @myidpt

**Comment by mikedanese** [comment]
> The API is explicitly NOT intended to be used the way we currently use it.

This isn't quite right. The problem outlined in the quoted text is that the API didn't have any definition about what should work and what shouldn't. Nothing about it is explicit. That's what we're trying to fix.

While we haven't figured out everything that's going to be required to fix these issues, we are committed to making sure we have a path forward for existing users of the API. The signers currently defined in the KEP are just phase 1 to migrate Kubernetes internal usage of the Certs API to the dedicated signer model. It's still very much a living document.

**Comment by howardjohn** [comment]
@mikedanese thanks for the clarification. The issue I was pointing out with the first as specifically

> None of these usages are related to ServiceAccount token secrets .data[ca.crt] in any way. That ca-bundle is only guaranteed to verify a connection the kube-apiserver using the default service.

Which we are relying on today. So I think for that part, we are not using things as intended, but for 2nd part of whether Kubernetes will even continue to support signing our CSRs, that is still not solidified yet. Is that correctly?

**Comment by mikedanese** [comment]
I still think "unintended" is the wrong characterization because nothing was intentional. If you've never gotten a bug report about this and you only noticed this because of the KEP, then I suspect the distributions of k8s that you care about set things up how the original OSS reference deployment set things up, how GKE sets things up. As far as the API, your usage is in a UB grey area, sure. But the responsibility to maintain compatibility extends beyond API compatibility. I'm trying to make it very clear that we aren't going to pull the rug out from under anyone.

We have a goal to support Istio (as well as other projects that want to build on k8s core certificates infrastructure) so we should approach this from the opposite direction. What are the Istio requirements? How can we shape the KEP so that Istio can dependably run on all conformant k8s clusters?

**Comment by howardjohn** [comment]
For the 1st issue, we have gotten some issues about this before. Ultimately if its not supported on ~all distributions, its hard to make it the only option, and supporting two methods to do the same thing isn't ideal. In reality we don't really need to support every single possible setup of Kubernetes, but it would be ideal to - at the very least all the major distros are required. There was also some concern about relying on an implementation detail of GKE/others that may change in the future, although I am not sure how valid this concern is.

The fact that we now use a signer name that is `kubernetes.io/legacy-unknown` makes it sound pretty unsupported, even if that isn't the reality. This was the part that I noticed from the KEP after setting things up to work on k8s 1.18 (#22084).

Hopefully this is accurate, I am a bit new to this area, but here is how things work for Istio:

(1) Pod starts up, connects to Istio control plane to get workload certs
(2) Pods use workload certs to connect to other workloads using mTLS
(3) We also have some webhooks, so we need to provide a cert for that

For (1), we need to authenticate the Istio control plane. To do that today, we have two methods: using self signed certs and writing the ca cert to a configmap in each namespace which is then mounted in the pods, OR using the k8s cert api, and then using the ca cert mounted under `serviceaccount/ca.crt`. I don't think we particularly care how we authenticate the istio control plane, we just need some way for the control plane to get some certs and some way to distribute the ca certs. Another idea considered was to make an APIService so its proxied through the api server but I don't remember too much of the details there.

For (2), we are using our own CA for this. I don't know too much about this but I think we potentially would be interested in using the k8s signing if it supports all of our needs (SPIFFEE, not sure anything else?)

**Comment by lei-tang** [comment]
From Istio perspective, one item coming to my mind is that Istio needs a Kubernetes API to obtain the CA certificate of Kubernetes CA. The CA certificate is needed for authenticating a certificate issued by Kubernetes CA. AFAIK, such API is not available from Kubernetes yet.

**Comment by howardjohn** [comment]
@lei-tang @myidpt any info on the future direction of this? What we do here impacts networking/Environments plans

**Comment by lei-tang** [comment]
To verify a certificate signed by k8s CA, a k8s API to obtain the k8s CA certificate is needed. Currently in Istio implementation, the k8s CA certificate is obtained from a well-known path, not  through a k8s API, which may raise a concern of whether this way of retrieving the k8s CA certificate is supported and future proof. Therefore, to address such concerns, for future directions, a k8s API to obtain the k8s CA certificate should be prioritized.

**Comment by howardjohn** [comment]
Basically the part I would like to understand is long term, will we need to keep a config map in each namespace populated with info (currently we have the root cert). So if k8s adds such an API and we are responsible for distributing it, sounds like we would have such a config map. If they distribute it through other means (auto mounted in pod, for example), then we do not. That will impact other decisions, as we may want to utilize this config map for other purposes

**Comment by myidpt** [comment]
In the long term, we hope K8s CSR API can continuously support signing certs for user workloads. I'm OK with istiod populating the root of trust via configmap, although it's not ideal.

Actually seeing the [goal](https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/20190607-certificates-api.md#goals) of the certs API proposal, it's covering our use case, but it doesn't resolve our issues. I think there are two things for the K8s team  to answer:
1. `kubernetes.io/legacy-unknown` may not be a good name for customer workload cert signing. As I understand the K8s team want to continuously support it. Is that correct, does the K8s team have any plan?
2. AFAIK, the K8s CSR signing cert can be different from the K8s root cert (it can be configured in newer K8s versions). Unlike the K8s root cert which is mounted on each pod, there's no way for a pod to retrieve that signing cert. Workloads in Istio need that signing cert to authenticate to istiod. An API to retrieve the signing cert is the baseline requirement, if the cert can be propagated via file mount on each pod, that would be better.

@mikedanese @liggitt

**Comment by mikedanese** [comment]
Sorry for radio silence. This issue remains on top of my stack as we plan the GA.

> Ultimately if its not supported on ~all distributions, its hard to make it the only option, and supporting two methods to do the same thing isn't ideal.

Yep, I absolutely agree with this take and empathize with your situation right now.

> (1) Pod starts up, connects to Istio control plane to get workload certs

> For (1), we need to authenticate the Istio control plane. To do that today, we have two methods: using self signed certs and writing the ca cert to a configmap in each namespace which is then mounted in the pods, OR using the k8s cert api, and then using the ca cert mounted under `serviceaccount/ca.crt`.

This unfortunately lands in the territory of the undefined right now. Essentially, we are working towards breaking specific usages out of legacy-unknown. Assuming these are KRM APIs and extensions, I believe this use case is covered by https://github.com/kubernetes/kubernetes/issues/54960. Is that a correct assumption?

> (2) Pods use workload certs to connect to other workloads using mTLS

> For (2), we are using our own CA for this. I don't know too much about this but I think we potentially would be interested in using the k8s signing if it supports all of our needs (SPIFFEE, not sure anything else?)

This use case is fully supported by the certificates API.

> Basically the part I would like to understand is long term, will we need to keep a config map in each namespace populated with info (currently we have the root cert).

I'm discussing https://github.com/kubernetes/kubernetes/issues/63726 with @happinesstaker to solve trust bundle distribution. I'd like to make produce a proposal in the nearish term.

**Comment by mikedanese** [comment]
> 1. As far as I see, the K8s team want to continuously support customer workload cert signing, (although `kubernetes.io/legacy-unknown` may not be a good signer name). Is that correct, does the K8s team have any plan to evolve the feature?

We want to break up `legacy-unknown` into a set of core signers that solve the use cases we intend to support.

> 2\. AFAIK, the K8s CSR signing cert can be different from the K8s root cert (it can be configured in newer K8s versions). Unlike the K8s root cert which is mounted on each pod, there's no way for a pod to retrieve that signing cert. Workloads in Istio need that signing cert to authenticate to istiod. An API to retrieve the signing cert is the baseline requirement, if the cert can be propagated via file mount on each pod, that would be better.

Yes this is correct. Multiple CAs can back the API. The API is intended to be partitioned using distinct signers:

https://github.com/kubernetes/kubernetes/blob/f9532e46632f487363d8e1b499f92c854b905189/pkg/apis/certificates/types.go#L45-L49

e.g. one signer for kubelets, another for Istio mTLS. Each signer can have distinct roots. Signers can also share roots with other signers.

**Comment by howardjohn** [comment]
Thanks @mikedanese 

> e.g. one signer for kubelets, another for Istio mTLS. Each signer can have distinct roots. Signers can also share roots with other signers.

Will Kubernetes itself provide a signer that will sign Istio mTLS (as we are doing today with legacy-unknown)? Otherwise, as far as I understand it, there isn't much value for us to use the API, at least as the primary mechanism, as we would just sign our own certs as we do today. I believe (and I may be wrong here) is our requirement is that we do not have hard dependencies on other CAs. So it may be useful to use the CSR api to integrate with whatever other applications implement it one day, but if core Kubernetes won't sign our certs we will always need to be able to sign our own certs still.

So I guess the primary question here is are we are 

> This unfortunately lands in the territory of the undefined right now. Essentially, we are working towards breaking specific usages out of legacy-unknown. Assuming these are KRM APIs and extensions, I believe this use case is covered by kubernetes/kubernetes#54960. Is that a correct assumption?

These are neither KRM APIs or extensions. We have 2 webhooks (validation/mutating) and then a gRPC streaming API - as far as I know these would not be covered by that issue (?)


>> I think we potentially would be interested in using the k8s signing if it supports all of our needs (SPIFFEE, not sure anything else?)
>
> This use case is fully supported by the certificates API.

Are there any plans to do any automation about certificate distribution? In an ideal world for us a pod would start with a spiffee cert already present that is rotated automagically, etc. I don't think I have seen anything about this, just wondering if it was something that was thought about at all or anything

> I'm discussing kubernetes/kubernetes#63726 with @happinesstaker to solve trust bundle distribution. I'd like to make produce a proposal in the nearish term.

Sounds great! If you point some of us on this thread to any designs that come up we would be happy to give some feedback

**Comment by munnerz** [comment]
> Otherwise, as far as I understand it, there isn't much value for us to use the API, at least as the primary mechanism, as we would just sign our own certs as we do today.

From the cert-manager side, one major motivation for Istio adopting the in-built CSR API is to allow users to switch out Istio's in-built signing capability with one backed by some kind of enterprise CA/external signing capability.

We are intending to port across our Venafi, Vault, 'CA', SelfSigned and ACME implementations to support the in-built CSR API, and this (combined with some kind of solution to the root of trust distribution problem) would allow us to become a certificate provider for a mesh.

> Are there any plans to do any automation about certificate distribution? In an ideal world for us a pod would start with a spiffee cert already present that is rotated automagically, etc. I don't think I have seen anything about this, just wondering if it was something that was thought about at all or anything

We have built https://github.com/jetstack/cert-manager-csi to do exactly this (albeit currently using cert-manager's own 'CertificateRequest' type, not the in-built CSR API yet). This achieves what you're looking for through 'in-line CSI volumes'.

**Comment by howardjohn** [comment]
> From the cert-manager side, one major motivation for Istio adopting the in-built CSR API is to allow users to switch out Istio's in-built signing capability with one backed by some kind of enterprise CA/external signing capability.

Yeah I think "isn't much value" was not right here. There is a lot of value in it being an integration point with external CAs which is great. For the time being, I don't think we would introduce a hard dependency on any other systems though, so we would still need to maintain our implementation as well most likely. It seems feasible that if k8s provided the CA we could expect that to be there and remove our implementation, but forcing users to install cert-manager (despite it being great) would probably be avoided. Maybe it would be the "recommended" deployment though. Take all of this with a grain of salt though, I don't work on this part of Istio too much.

> cert-manager-csi 

This seems pretty cool, I have been meaning to try this out but haven't had a chance

By the way, currently we only use the CSR API for the control plane certs. Workload certs are still handled through our own API (for now?)

**Comment by liggitt** [comment]
hoisting discussion with @howardjohn from https://github.com/kubernetes/enhancements/issues/1513#issuecomment-625988395:

@howardjohn:
 
> @liggitt makes sense, so the API will allow extension for our use case in general, but without extension we would not be supported, as `legacy-unknown` is removed. I am assuming using a signer like `kubernetes.io/kube-apiserver-client` for our own purposes is frowned upon as well? So if we want to continue to use this with v1, we should submit some proposals for this? Is that accurate?
> 
> Note - while we will possibly want to do our full spiffe mTLS certificate stuff with this stuff in the future, our current usage is actually just to create certificates to validate the identity of the Istio control plane to retrieve the mTLS certs (essentially for bootstrapping). We just create a DNS cert for `istiod.istio-system.svc` and "distribute" the root cert by using the `serviceaccount/ca.crt` mounted in the pod (which we understand is a hack).
> 
> Thanks for your help

If the allowed usages and trust characteristics of a `kubernetes.io/kube-apiserver-client` client certificate (as defined in https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/20190607-certificates-api.md#signers) works for your use case, it's fine to use.

The main issue I see with your use is trust distribution... there is definitely no guarantee the ca.crt injected into pods for verifying the kube-apiserver's serving certificate will contain trust roots for client certificates signed by the CSR API (that has always been the case, and any overlap was distribution-specific/coincidental).

**Comment by howardjohn** [comment]
@liggitt I would agree, trust distribution is the main thing that held us back from making this our default option (currently we self sign a cert and distribute the root cert via a config map to every namespace).

Yes, this is a serving cert. Basically:

* `istiod` (the control plane) will create a CSR for `istiod.istio-system.svc` using legacy-unknown, and will start serving using this cert
* When workload pods come up, they will connect to  `istiod.istio-system.svc`, They will send the projected service account token to authenticate  and use the `serviceaccount/ca.crt` as the ca cert for this connection (by relying on platform specific implementation details).
* Once they are connected, we do our own Istio certificate distribution. The workload then can connect to other workloads using the certs we acquire. In the future this maybe would be controlled by the CSR API and we can stop being a CA.

**Comment by costinm** [comment]
And if CertManager fixes 2 bugs / feature requests - policy and signing K8S
CRD - we can fallback to CertManager if k8s distro doesn't work.

Or at least provides a way to disable annotations and other uncontrollable
paths for signing.

We can also fallback to CertManager CertificateRequest - but better to have
a single crd to deal with.

**Comment by costinm** [comment]
Btw - trust distribution shouldn't require api change - just have to full
chain returned.

**Comment by enj** [comment]
As anecdotal evidence, OpenShift uses distinct roots of trust for the CSR API and `serviceaccount/ca.crt` [1].

[1] https://github.com/openshift/cluster-kube-controller-manager-operator/pull/150

---

On the `istiod.istio-system.svc` serving cert bit:

Recently I have been thinking about having Kube itself provide a built-in short lived, auto rotated CA for the service network (similar to https://github.com/openshift/service-ca-operator but more deeply integrated without the use of annotations).  I will not try to go into specifics here, but basically the goal would be to provide trust distribution for this short lived CA and allow a service to request a serving cert for itself which a pod would then mount.  Basically, it should be trivial for every service on Kube cluster to always use TLS without needing to install cert-manager.  You should be able to set up a webhook that uses `clientConfig.service` or an API service that uses `spec.service` without having to fuss around with serving certs (other than tell your code "use this file as the serving cert and make sure to reload it").

**Comment by myidpt** [comment]
@liggitt @mikedanese 
Hi folks, thanks for the discussion.

We noticed the CertificateSigningRequest API is promoted to v1 in V1.19 and disallow the `kubernetes.io/legacy-unknown` signers.
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.19.md#api-change-1

The code that is using the CSR API is here:
https://github.com/istio/istio/blob/master/security/pkg/k8s/chiron/utils.go#L192
You can see its usage.

We need to have a plan for the migration, maybe with some auto-detection for the availability of the v1beta1 CSR API. Can you quickly answer the following questions:
(1) with which version the v1beta1 CSR API will be removed?
(2) what signers can we use to replace `kubernetes.io/legacy-unknown`?

**Comment by munnerz** [comment]
Re (1), as it was only deprecated in 1.19, I think the earliest it could be
removed is 1.22? I’m not sure what the overall timeline from sig-auth is
for removal and I do not see a scheduled removal date as a lifecycle marker
in the API package.

Re (2), there is no built in signer which will accommodate this - instead,
you’ll need to write a signer that watches for CSR objects and
approves/signs them accordingly. We have created
https://github.com/cert-manager/signer-ca and
https://github.com/cert-manager/signer-venafi which will (once istio
supports setting the signerName field) allow istio users to integrate with
whatever CA they choose.

These could either be taken as-is, and run alongside istio components, or
built into istio with the option to disable it so users can ‘bring their
own’ signer.

There’s a few recommendations in the Certificates KEP too regarding what
the author of a signer should expect about their certificates:
https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/20190607-certificates-api.md#signers

/cc @wallrj @meyskens @JoshVanL

**Comment by liggitt** [comment]
> Re (1), as it was only deprecated in 1.19, I think the earliest it could be removed is 1.22? I’m not sure what the overall timeline from sig-auth is for removal and I do not see a scheduled removal date as a lifecycle marker in the API package.

certificates.k8s.io/v1beta1 is targeting removal in 1.22:

https://github.com/kubernetes/api/blob/master/certificates/v1beta1/zz_generated.prerelease-lifecycle.go#L45-L49

**Comment by myidpt** [comment]
Thank you for the info, @munnerz and @liggitt. I think there are two things we should do:
1. Istiod will be explicitly set the signers (can be configured by admin, for integration with cert-manager, etc.) in the CSRs.
2. Istio will automatically detect the availability of v1 CSR API, and fail over to v1beta1 CSR API for lower versions.
We should get these done before K8s 1.22 is out. (1) is also needed for better cert-manager integration. I think we will ship this in Istio V1.18 - V1.19.

**Comment by liggitt** [comment]
> Istio will automatically detect the availability of v1 CSR API, and fail over to v1beta1 CSR API for lower versions.

I'm not sure if you're using the client-go RequestCertificate / WaitForCertificate methods, but if you are, those will do a v1 -> v1beta1 fallback for you in v0.19.0+ versions

**Comment by howardjohn** [comment]
not stale

**Comment by myidpt** [comment]
Reassign to @shankgan 
Hi Shankar, let's sync up and get this done in Istio 1.9.

**Comment by sandeep1699** [comment]
Hi @howardjohn  @myidpt  
Could you please suggest, Is it supported to Use k8s CA as a signing authority for workload proxies using chiron?

**Comment by shankgan** [comment]
@sandeep1699 - Note that this (experimental) feature is available in Istio 1.8. Refer https://preliminary.istio.io/latest/docs/tasks/security/cert-management/custom-ca-k8s/ for further information. 
However, could you elaborate on what you mean by Kubernetes CA? Were you planning to use the same CA that we use for signing DNS certificates? Usage of that particular CA (kubernetes.io/legacy-unknown) is being deprecated and we would not recommend using it. We are planning to move away from it as well. 
Are you planning to use any other signer? (ex **kubernetes.io/kube-apiserver-client**)

**Comment by shankgan** [comment]
Just following up on this thread to discuss the immediate Istio 1.9 goals - 

(1) Change Istio's K8s CSR API usage to use the v1 api. (given that Beta API will be removed shortly)
(2) Find a way to use any signer other than **kubernetes.io/legacy-unknown** to sign Istiod DNS certificates. Here, I have two   follow up questions  - 
         
     (a) None of the signers that are currently supported appear to satisfy our requirements for the Istiod DNS cert. The Istiod DNS certificate needs to be used for both client and server authentication. All the standard signers listed (https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/) can be used for either client OR server cert. @mikedanese Any suggestions for which signer can create certificates with both key Usages? 

    (b) Regardless of the signer used, we still need an API to fetch the trust-bundle corresponding to the signer. @mikedanese would you know if this has been implemented/If there is any plan to implement it in the near future? As discussed in detail above, we CANNOT rely on our existing implementation to work across all platforms. 

Without resolving (2.a) and (2.b), the only changes that can be made to Istio 1.9 will be (1).

**Comment by howardjohn** [comment]
I think (2) is a blocker for (1), legacy-unknown does not work with v1 AFAIK.

**Comment by howardjohn** [comment]
Also we cannot do (1) for a long time most likely. It was added in 1.19, right? We support Kubernetes 1.15+ (unfortunately), so it will be a very long time until we can move off of that.

**Comment by liggitt** [comment]
> Also we cannot do (1) for a long time most likely. It was added in 1.19, right? We support Kubernetes 1.15+ (unfortunately), so it will be a very long time until we can move off of that.

If you use the k8s.io/client-go/util/certificate/csr#RequestCertificate/WaitForCertificate helper methods, those will use the v1 API if available and fall back to the v1beta1 API.

That would let you focus on resolving item 2, moving off the legacy-unknown signer

**Comment by shankgan** [comment]
Reg Item 2.(a), when browsing through the list of inbuilt signers available here - (https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/#kubernetes-signers), it looks like all these signers are custom-built to sign certificates for k8s components.
 Does K8s have any recommendations to decide which signer to use for non-k8s infrastructure components? For instance, Istiod could theoretically use the "kubernetes.io/kubelet-serving" signer for its DNS certificates (based on the usage restrictions etcetera), but this doesn't feel right.
Given that "legacy-unknown" was the only signer that allowed for a wide variety of key-Usages, is there a plan to provide an equivalent signer once this has been deprecated?

**Comment by munnerz** [comment]
No - Kubernetes does not provide any generic certificate signing functionality for _workloads_ (e.g. Istio).

It provides the API format that allows client to request certificates (i.e. the CertificateSigningRequest resource), but it is up to integrators to write their own signing controllers (and also bare in mind that your end users may want to swap out which signing controllers are used for a particular signerName, e.g. some organisations may want to utilise their own external API for signing certificates, which could be achieved by allowing an alternate signerName to be used or an alternate implementation of the an `istio.io/control-plane`, `Istio.io/workload` signerName.

**Comment by shankgan** [comment]
Based on the discussions above, it appears that there is no in-built K8s signer (currently or in the near future) that is a good fit to provision certificates that satisfy Istiod's requirements. We will probably continue to use the "legacy-unknown" option until it gets removed. Following that, the user will have the option of using self-signed certs OR explicitly configuring a K8s signer to sign the DNS cert - This assumes the K8s signer points to an external CA that is deployed on the K8s platform. Have written a proposal summarizing some solutions to phase out "legacy/uknown" signer - https://docs.google.com/document/d/1kvmZgJ-QZByMlhqZDTdoxwHtJQxsrl5kj2-4HB4ip80/edit?ts=6001f139&resourcekey=0-OcIivFMxKkGxRB5KRPcGvg#heading=h.qlmnvhzb2ib2

**Comment by howardjohn** [comment]
Nots tale

**Comment by ryantking** [comment]
@howardjohn @mikedanese @Monkeyanator What's the status on this issue? Should we push this back to the 1.12 milestone?

**Comment by howardjohn** [comment]
No, this is broken in Kubernetes1.22 which is an officially supported version for 1.11 I believe. So this does belong in the 1.11 milestone.

Most of the work is just documenting that this does not work as it did before though. I think @shankgan is taking that on (?)

**Comment by shwsingh** [comment]
@shankgan : ETA for doc please

**Comment by shankgan** [comment]
> @shankgan : ETA for doc please
This [RFC](https://docs.google.com/document/d/1kvmZgJ-QZByMlhqZDTdoxwHtJQxsrl5kj2-4HB4ip80/edit?resourcekey=0-OcIivFMxKkGxRB5KRPcGvg#heading=h.qlmnvhzb2ib2) already documents this
