### ISSUE TITLE
Order of execution of Istio Authentication Policy and Mixer-based authorization : Istio 1.3

### ISSUE THREAD

**Issue by ashishksingh** [istio/istio#22162]
I have an Istio 1.3 cluster with an end-user JWT Authentication policy attached to a microservice. I also have an Authorization Mixer adapter setup for runtime authorization check. 

I would expect that the authentication policy kicks in first, followed by authorization. But the reverse seems to be happening , and if a client sends a request without any credentials, client gets a 403(mixer-authorization-denied error) , whereas they should receive a 401 Authentication Denied error. 

This has other ramifications, because since the authorization happens before authentication, the authorization request.auth.principal attribute is not set . Setting this attribute requires authentication to take place first.

**Comment by ashishksingh** [comment]
Hi , 
Any comment would be really helpful. I am basically trying to find what determines the order of execution in Envoy. If I have a JWT Authentication command and a mixer-authorization forward in place as well, then what determines the order of execution ?

**Comment by bianpengyuan** [comment]
Could you check proxy config dump to make sure mixer filter is before jwt filter? I think In 1.3, filter order is decided here, where authn filter is before mixer filter:
https://github.com/istio/istio/blob/3db95dfc23ffc081803b42549934915ba3b0a3d5/pilot/pkg/networking/plugin/registry/registry.go#L29-L32

cc @yangminzhu @kyessenov

**Comment by ashishksingh** [comment]
Thanks @bianpengyuan  . I will check this and get back to you shortly. 

Would you happen to know what's decides the order in Istio 1.4 ?

**Comment by bianpengyuan** [comment]
should be the same place.

**Comment by ashishksingh** [comment]
Hi @bianpengyuan , @yangminzhu , @kyessenov , 
. So I finally tested this out in detail in a vanilla 1.4.0 environment with a Helloworld microservice, a JWT authentication policy and a mixer authorization adapter. 

I tried various combinations of adding authentication policy followed by authorization rule/handler/instance, vice versa etc. , the end result was that whether authentication filter chain executes first or authorization is really sporadic and it is not dependent on the order of filter chain in the envoy proxy. 

I also noticed that in the filter chain the authentication policy is always the before mixer invocation , consistent with the order in the registry.go file above. And, the order of execution of the two filter chains seems independent of the order in which they appear in the proxy config dump. 

I have attached the proxy config dump here where seemingly authentication should take place before authorization, but that's not what I see in practice when I invoke the API externally..

**Comment by kyessenov** [comment]
Are you doing any kind of re-routing maybe?

**Comment by ashishksingh** [comment]
![Postman Response](https://user-images.githubusercontent.com/5232903/77798727-723ce500-7041-11ea-899a-a4218ec0208a.png)

[config_dump.json.txt](https://github.com/istio/istio/files/4395850/config_dump.json.txt)

**Comment by ashishksingh** [comment]
I have one Gateway instance defined and one virtual service for the hello-world API. I don't think I am doing any re-routing.

**Comment by bianpengyuan** [comment]
If you remove mixer filter (by setting both mixerCheckServer and mixerReportServer to empty string), would istio-authn filter itself work properly?

**Comment by ashishksingh** [comment]
Testing this today.

**Comment by ashishksingh** [comment]
I was finally able to test this . 

If I remove mixer filter by setting both mixerCheckServer and mixerReportServer meshconfig to empty string, then the istio-authn filter itself works as expected. It gives 401 if the JWT token is not there or invalid, and 200 if the token is valid.

**Comment by douglas-reid** [comment]
Is this still being investigated?  It appears to have been untouched for 3 months now, and references older versions of Istio. I'm going to close for now, pending a signal that this should still be open.
