### ISSUE TITLE
istioctl: Don't use xDS api's in a way that breaks on upgrade

### ISSUE THREAD

**Issue by gargnupur** [istio/istio#22164]
Currently, some of the json unmarshaling in pilot fails whenever xDS API's upgrades.
Use it in a way, we are safe from them.

EX: PR: https://github.com/istio/istio/pull/22145
Test that breaks: https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/22145/integ-pilot-k8s-tests_istio/9722 because it needs https://github.com/envoyproxy/envoy/pull/10109/files change.

**Comment by kyessenov** [comment]
cc @howardjohn -- this is preventing us from picking up proxy changes for older control planes.

**Comment by howardjohn** [comment]
cc @esnible we should at least ignore unknown fields possibly?

This is istioctl by the way, not Pilot.

**Comment by esnible** [comment]
@howardjohn Do you think this a duplicate of https://github.com/istio/istio/issues/20714 ?

**Comment by howardjohn** [comment]
Yes, we can consolidate
