### ISSUE TITLE
generateKeyCertFromExistingFiles is not handling cert reloading

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#22174]
See https://github.com/istio/istio/blob/110cc21e5c6bc7201fd6d2ccb3f4200740e06afe/security/pkg/nodeagent/cache/secretcache.go#L244

Because we are not storing this in the secret cache, we don't check it in rotate().

The impact here is that if users are mounting their own certs, they will never be reloaded even if they expire/are changed

**Comment by lei-tang** [comment]
Currently there is a comment for this feature on https://github.com/istio/istio/blob/master/security/pkg/nodeagent/cache/secretcache.go#L237:
	// TODO (lei-tang): if updating files are supported, add a file watcher for
	// the files under the well known path.

If we decide to add the support of updating files, a file watcher is needed. Before that, if the certificate files change, similar to the approach that Pilot Agent restarts Envoy when secret-mounted certificates change, the sidecar can be restarted to load the changed certificate files.

**Comment by howardjohn** [comment]
It's not the same as pilot agent restarting envoy because that is automatically detected file change and restarts. in this case when the cert is changed nothing happens so it will expire

**Comment by howardjohn** [comment]
So basically if you are using file mounted certs that are short lived things will not work - only certs that live longer than the pod lifetime

**Comment by lei-tang** [comment]
https://github.com/istio/istio/pull/23417 added file watcher support.
