### ISSUE TITLE
pilot-integration-auth, pilot-integration-noauth, istio-presubmit possibly failing infrastructure tests

### ISSUE THREAD

**Issue by gnirodi** [istio/istio#2218]
Seeing ambiguous errors of the kind from:

- https://circleci.com/gh/istio/istio/8390
- https://circleci.com/gh/istio/istio/8391

=================== Tearing down infrastructure =====================
....
E1217 03:27:18.282666    8409 driver.go:175] 
=================== Failed infrastructure tests! =====================
27 errors occurred:

----------------------------------------------------------------------------
Not sure if these are related but FWIW:

- https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/2191/istio-presubmit/1460/

....
W1217 02:55:19.617] ERROR: /home/bootstrap/go/src/istio.io/istio/mixer/docker/BUILD:30:1: no such package '@libssl1.0.0//file': dpkg_parser command failed: Traceback (most recent call last):
.....
I1217 02:57:53.909] FAIL! (1)
I1217 02:57:53.909] Makefile:150: recipe for target 'push' failed
.....
E1217 02:57:53.909] Build failed
I1217 02:57:53.909] process 516 exited with code 2 after 10.9m
E1217 02:57:53.910] FAIL: istio-presubmit

**Comment by jmuk** [comment]
Looks like a flake, since other runs of for this pilot-integration-auth / noauth succeed.

The istio-presubmit failure is seen a few times, but actually that's also a flake. Please rerun that test. Let me know if this happens consistently -- filed as https://github.com/istio/istio/issues/2219

**Comment by gnirodi** [comment]
This was indeed a flake
