### ISSUE TITLE
TestV1beta1_TCP failing 100% of time

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#22189]
This started after https://github.com/istio/istio/pull/22185 was merged, but that PR passed the test -- so it might be an unrelated change made at the same time

Last success was `2020-03-14 08:56:52 +0000 UTC`

I suspect this was a result of upgrading the prow cluster to GKE 1.15, which was around this time?

**Comment by howardjohn** [comment]
fyi @ramaraochavali since I see your PR is failing

**Comment by howardjohn** [comment]
Reproducible locally on GKE 1.15, not sure about other platforms

**Comment by howardjohn** [comment]
locally in kind I only get one failure:
```
--- FAIL: TestV1beta1_TCP (101.37s)
    --- PASS: TestV1beta1_TCP/a->b:http-8090/data[deny] (0.02s)
    --- PASS: TestV1beta1_TCP/a->b:http-8091/data[allow] (0.02s)
    --- PASS: TestV1beta1_TCP/a->b:tcp/data[allow] (0.01s)
    --- PASS: TestV1beta1_TCP/a->c:http-8090/data[deny] (0.02s)
    --- PASS: TestV1beta1_TCP/a->c:http-8091/data[allow] (0.02s)
    --- PASS: TestV1beta1_TCP/a->c:tcp/data[allow] (0.00s)
    --- FAIL: TestV1beta1_TCP/a->d:tcp/data[deny] (30.24s)
        util.go:118: retry.UntilSuccessOrFail: timeout while waiting (last error: a to d:tcp/data: expect deny with EOF error, got: error: <nil>)
    --- PASS: TestV1beta1_TCP/b->d:tcp/data[allow] (0.03s)
    --- PASS: TestV1beta1_TCP/c->d:tcp/data[allow] (0.03s)
    --- PASS: TestV1beta1_TCP/x->a:tcp/data[allow] (0.03s)
    --- PASS: TestV1beta1_TCP/x->d:tcp/data[deny] (6.33s)
    --- PASS: TestV1beta1_TCP/a->e:http-8090/data[allow] (0.05s)
    --- PASS: TestV1beta1_TCP/a->e:http-8091/data[allow] (0.02s)
    --- PASS: TestV1beta1_TCP/a->e:tcp/data[deny] (29.51s)

```

but still failing. And a success suspiciously took 30s ` --- PASS: TestV1beta1_TCP/a->e:tcp/data[deny] (29.51s)`

**Comment by ramaraochavali** [comment]
@howardjohn Thank you. Will wait for your skip fix to be merged.

**Comment by yangminzhu** [comment]
It's very strange that the GKE version is affecting this test, need some more investigations.
