### ISSUE TITLE
Deploy of an application in a cluster from another cluster

### ISSUE THREAD

**Issue by matty111** [istio/istio#22196]
Hi,

With istio is it possible to deploy microservices from a main cluster?
For example:
I have two cluster cluster kubernetes joined with istio shared control plane (a cluster on-prem and a cluster in google/azure). When i have to deploy an application in the google cluster i would like to be in the cluster on prem without to change context.
For example the command can be **kubectl apply -f app.yaml -n namespace -c cluster-google**
For the authorization policy this method is possible yet because the policy is applied to namespace level, but to deploy i think no.

**Comment by howardjohn** [comment]
No, this is not something Istio supports or intends to support. If you want to do this type of configuration management you will need to use other tools, we do not manage application deployments
