### ISSUE TITLE
Add examples of installing with multiple gateways in the doc

### ISSUE THREAD

**Issue by richardwxn** [istio/istio#22199]
It seems like we are still getting many issues related to how to enable multiple gateways, I think as we already fix the naming issue, we need to add some examples to the doc about how to use it and also mention it was not supported with the old IstioControlPlane API, probably here: https://istio.io/docs/setup/install/istioctl/?

**Comment by ostromart** [comment]
I'll take this issue since I'm working on a couple of GW issues.

**Comment by rvennam** [comment]
I believe the doc should cover:
1. Deploying gateway in user namespaces for isolation
2. Customizing the gateway service using annotations (private IP)
3. Mounting certs for TLS termination

**Comment by esnible** [comment]
With 1.5.1 you'll be able to install like this

```
istioctl manifest apply \
   --set components.ingressGateways[0].enabled=true \
   --set components.ingressGateways[1].enabled=true \
   --set components.ingressGateways[1].name=my-second-gateway
```

and remove it like this:

```
istioctl manifest apply
```

(With 1.5.0 the `--set` notation doesn't work; users need to supply IstioControlPlane CR.)

@ostromart Although `components.ingressGateways[0].enabled=true` is the default it doesn't work in my personal build of 1.6.0.  I think setting the second ingress disables the default values for the first ingress.

@ostromart Write the docs and I will try them out...

**Comment by ostromart** [comment]
https://istio.io/docs/setup/install/istioctl/#configure-gateways
At least docs are there, so closing this bug, but we may still have some lingering issues with --set notation @esnible so maybe another issue is required for that work?
Feel free to reopen this if anything is still missing in the docs.

**Comment by rvennam** [comment]
@ostromart , Thank you for the examples in the doc: https://istio.io/docs/setup/install/istioctl/#configure-gateways Very helpful!

If users want to deploy the custom gateways in the same istio-system namespace, they would need to have custom labels on the gateways so they can select the Gateway they want right? How do you provide the label for a gateway in IstioOperator ?
