### ISSUE TITLE
Preventing 301 Http redirect for ACME validation

### ISSUE THREAD

**Issue by secoldPrivate** [istio/istio#22194]
I'm trying to setup automated certificate renewal with cert-manager 0.13.
Most of the system works.

The current setup is like this:

1 Ingress-controller-pod (envoy that came with istio).
1 gateway controller (gateway-A) responding to all hosts '*' on port 80 only.
1 gateway controller (gateway-B) responding ONLY the domain i'm setting up myweb.com both 80 and 443. 80 being redirected to 443.

I've got a set of deployment files that deploy the second gateway, virtual service, destination rule etc.

Sometimes it works. Certificates get generated without an issue, and the routing is perfect.
Sometimes it fails. The Certificate gets stuck pending. The challenge says connection reset. The envoy logs show a 301 redirect.

In the case that it fails, I can make it succeed by modifying the https-redirect on gateway-B, to false... letting the ACME not get 301'd and then, once the certificate is setup... turning it back to true.  But that means when the certificate renews later.. It needs this manual step again.

What's happening is obvious. There are two gateways that can field the HTTP call (gateway A and B).. If gateway A gets it... then the whole thing works.
If gateway B gets it.. it 301's which breaks the ACME.

My question is this. How can I make it that all ACME requests go to a specific gateway. I understand that virtualservices can achieve this, and at the moment I'm using a virtual service on gateway B to SPLIT acme traffic to the acme response pod that certmanager generates, and application traffic to the application pod, and that works fine. It's just the 301 redirect that messes it up.

But I need to do this on the GATEWAY level, because by the time it gets to a virtual-service.. the gateway has already https redirected and the acme has failed.

**Comment by howardjohn** [comment]
When you say sometimes it works, do you mean if you did 10 requests in a row 5 would fail or so? Or for a few hours everything works, then a few hours everything fails?

It would be useful to get a config dump (https://github.com/istio/istio/wiki/Troubleshooting-Istio) to see what is going on here

**Comment by howardjohn** [comment]
We cannot debug this without more information. Please reopen if you can provide more info. Thanks!
