### ISSUE TITLE
Does Litmus support istio based system?

### ISSUE THREAD

**Issue by chenhy97** [istio/istio#22191]
Litmus is a chaos injection tool. 
Does the proxy component of Istio support Litmus?

**Comment by ksatchit** [comment]
Hi @chenhy97 ! Noticed this quite late. Support for istio is planned & in the roadmap for Litmus. Please feel free to add your thoughts to these issues or create a new one. Thank you!! 

- https://github.com/litmuschaos/litmus/issues/1474
- https://github.com/litmuschaos/litmus/issues/1473
