### ISSUE TITLE
setting values.gateways.istio-ingressgateway.autoscaleMin not work

### ISSUE THREAD

**Issue by woodsmur** [istio/istio#22192]
**Bug description**

Either `gateways.istio-ingressgateway.autoscaleMin` or `gateways.istio-ingressgateway.autoscaleMax` is set using `istioctl manifest generate --set gateways.istio-ingressgateway.autoscaleMin=3 --set gateways.istio-ingressgateway.autoscaleMax=5 > generated-manifest.yaml` in the generated manifest file. I also notice that the following settings can not be set, but both `--set values.pilot.autoscaleMin=3` and `--set values.pilot.autoscaleMax=5 ` can.

```
--set values.gateways.istio-ingressgateway.resources.requests.cpu=1500m \
--set values.gateways.istio-ingressgateway.resources.requests.memory=2048Mi \
--set values.gateways.istio-ingressgateway.resources.limits.cpu=2000m \
--set values.gateways.istio-ingressgateway.resources.limits.memory=2048Mi \
```

**Version**
```
$:~/.bin/istio$ istioctl version --remote
client version: 1.5.0
control plane version: 1.5.0
data plane version: 1.5.0 (2 proxies)
$:~/.bin/istio$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.10", GitCommit:"1bea6c00a7055edef03f1d4bb58b773fa8917f11", GitTreeState:"clean", BuildDate:"2020-02-11T20:13:57Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.10-eks-bac369", GitCommit:"bac3690554985327ae4d13e42169e8b1c2f37226", GitTreeState:"clean", BuildDate:"2020-02-26T01:12:54Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
```

istioctl manifest generate \
  --set values.gateways.istio-ingressgateway.autoscaleMin=3 \
  --set values.gateways.istio-ingressgateway.autoscaleMax=5 \
  > generated-manifest.yaml

kubectl apply -f generated-manifest.yaml
```

**Environment where bug was observed (cloud vendor, OS, etc)**

eks

**Comment by richardwxn** [comment]
this is a known issue: https://github.com/istio/istio/issues/20345. I think we have to fix it, @ostromart

**Comment by richardwxn** [comment]
@woodsmur we are updating the doc to reflect that k8s settings via helm api is not supported anymore, so please use IstioOperator API path directly via set override or yaml file override: https://istio.io/docs/setup/install/istioctl/#customize-kubernetes-settings

**Comment by howardjohn** [comment]
Closing as the doc is updated and we are trackng this in #20345
