### ISSUE TITLE
operator support validate item of slice

### ISSUE THREAD

**Issue by morvencao** [istio/istio#22207]
**Bug description**

relevant to https://github.com/istio/istio/issues/22137
For field of slice type, eg. 
```
	IngressGateways      []*GatewaySpec     
	EgressGateways       []*GatewaySpec
```
https://github.com/istio/api/blob/master/operator/v1alpha1/component.pb.go#L37-L38
In order to validate each item of the slice, we need to support path like `jsonpath`, eg.
```
Components.IngressGateways[i]
```

We should also support `*` for all matching items, so that if we want to validate the name of IngressGateways, we just need to add validation function for path:
```
Components.IngressGateways[*].Name
```

[ X ] Installation

**Comment by esnible** [comment]
Related: https://github.com/istio/istio/issues/21473

It would be great if we could make IstioOperator part of Istio and also use it for the analyzer.  Please comment on PR https://github.com/istio/istio/pull/22166
