### ISSUE TITLE
Enable Pilot data sharding

### ISSUE THREAD

**Issue by seflerZ** [istio/istio#22208]
**Describe the feature request**
We all know that currently Pilot hold entire system's services in it memory. This makes it impossible to do expansion when out of memory encountered. We can only increase the host's memory, but the memory can not be expanded forever.

Here I'm suggesting a solution to shard the data into Pilot sectors like the following design shows.
![image](https://user-images.githubusercontent.com/2093588/76733305-80fede80-679b-11ea-85cc-ca3d1cc3d81c.png)

We have 4 critical points to meet here:
1. The first is how we can partially load the services from registry. Today, no matter MCP or K8s adapter accepts the whole services and doesn't have any on demand implementations. Since K8s is bounded to platform, here I suggest to have MCP support on demand service loading. It won't be a much complex modification since we only need to add resource names while requesting. This has been proposed by issue [#19796](https://github.com/istio/istio/issues/19796).
1. Another question is how we generate the Sidecar CRD for each Pilot sector. This will introduce a component which is may be called as "Pilot-Controller". This depends on the sidecar's dependencies. There will be a challenge on how we can collect each sidecar's dependencies. The most simple solution is to have the user exporting service dependency declarations before publishing the service. The more appropriate one is having the sidecar send on demand service dependencies to a persistent storage. After that, controller can cluster the target services into sectors with any clustering algorithm(Such as K-Means). Another responsibility of the controller is generating the Sidecar CRD for each sector by the result of above clustering.
1. There should be another module within the "Pilot-Controller" which acts as name service for each sidecar. After sharding, the sidecar should connect to the correct Pilot sector in order to get xDS resources.
1. The last is that the Pilot-Controller would returns cluster IP according to the sidecar's provided attributes(such as identifiers). Since today we still have static Pilot address configuration. We can generate the configurations for different sidecars and place them in YAML in advance. This is the jod of Name Service of Pilot Controller. As a result of that, sidecars of each services will connect to different sectors. The cluster IP also enables the expansion within a sector. That is to say, if any Pilot Pod's load within in a sector is heavy, we can increase the Pod number of Pilot within the sector to ease the connection pressure from sidecars.

As a result of that, we can use sector expansion to hold the service explosion and do Pod expansion within a specified sector to hold the connection explosion. This will makes the whole Pilot system of Istio more robust and resilience.

_This is an early proposal and may be lack of consideration under certain circumstances. I'm happy to see any other opinions or feedback._

@howardjohn @lizan @hzxuzhonghu 

**Describe alternatives you've considered**
None at present.

**Additional context**

**Comment by hzxuzhonghu** [comment]
cc @rshriram @ramaraochavali

**Comment by hzxuzhonghu** [comment]
This is really crazy. I have two question:

1.  It needs a component `pilot-controller` to control sidecar:  which pilot to connect. **How to achieve this?**
2. `Pilot-Controller` also controls pilot to care only about specific services/pods/other config, and you are saying it is from `Sidecar`, not sure which sidecar you mean? The current API or something else?

**Comment by seflerZ** [comment]
1. As we know the sidecar's connected Pilot address configuration is currently configured through K8s CRD statically. We just need to generate different configurations for each sidecar.
2. Didn't catch your question. Would you please quote the words I've said?

**Comment by hzxuzhonghu** [comment]
>As we know the sidecar's connected Pilot address configuration is currently configured through K8s CRD statically. We just need to generate different configurations for each sidecar.

I think you mean meshConfig.DiscoveryAddress, but i am asking how you can know which service the proxy depends on. 

>Didn't catch your question. Would you please quote the words I've said?

<The controller gathers the services within the K8s platform through the API and analyzes the service dependencies of each. It can cluster the target services into sectors with any clustering alogorithm(Such as K-Means).>

 In most cases, users do not set anything even `Sidecar` api has been able to allow setting egress hosts.

**Comment by seflerZ** [comment]
1. Yes, here is the challenge. The most simple solution is to have the user exporting service dependency declarations before publishing the service. The more appropriate one is having the sidecar send on demand service dependencies to a persistent storage.

2. Well, this is much more like the first one. That is to say, we need collected each sidecar's service dependencies. This process acts as this: Suppose we've collected it and name it as "list_srv_deps".  We have the mapping, say "srvA -> {srvC, srvD, srvE}" (the services within the brackets are the srvA's dependencies). Then we've got a more complicated list:
* "srvA -> {srvC, srvD, srvE}"
* "srvB -> {srvE, srvD}"
* "srvC -> {srvF}"
Therefore in best case, we should cluster "srvA" and "srvB" together and have "srvC" in another sector. As a result of that, the Pilots in sector A have "srvC, srvD, srvE" and Polits in sector B have "srvF" which decrease the services loaded in memory.

_I've changed the text to express my idea more precisely._

**Comment by howardjohn** [comment]
> Today, no matter MCP or K8s adapter accepts the whole services and doesn't have any on demand implementations.

I will respond more thoroughly to the rest later, but I don't think this is a goal for the project at this time. Kubernetes and etcd already both do not support sharding. It doesn't make sense, to me, to make pilot this hyper scale sharded system when the underlying system 99.9% of users are running is not. If kubernetes supports 10k services, we should support 10k services - not 100 million. This has a massive complexity cost for what is minimal gain.

Are you really seeing issues that pilot has too many services in memory? If you are, then you can do this yourself with no changes to Istio, if you write a smart MCP server that handles this, your way to direct proxies to the correct pilot, etc. But I don't think this belongs in Istio core.

**Comment by seflerZ** [comment]
Yes, we're running out of memory even with 32GiB capacity. Thanks John. I totally understand. The way to achieve this is to make an extension component to manage the Pilot and have the sectors totally transparent to current Pilot system. The extension can be out side of the Istio core, but the key point is "On Demand MCP" which makes it easier to manage each Pilot's resources. Besides, the "On Demand MCP" also aligns with "On demand xDS".

**Comment by howardjohn** [comment]
Makes sense to me. I am surprised it's using 32gb as well, we may be able
to optimize that a bit as well to help a bit

**Comment by hzxuzhonghu** [comment]
@seflerZ Do u mind providing your cluster scale? Like node/pod/service number

**Comment by seflerZ** [comment]
@hzxuzhonghu I'm sorry. We can't talk about this in public areas.
@howardjohn Thanks. We would also like to contribute to make Istio more robust and resilience. How do you think about adding on demand support in MCP protocol?

**Comment by rshriram** [comment]
One clarification: is the data plane also sharded by sectors such that sidecars in a sector talk only to other sidecars in the same sector?

**Comment by seflerZ** [comment]
No, the sidecars within the entire system can still talk to each other. They can find each other. It's not something like tenant. What I mean is that the all the services of a sidecar dependents are bound to a single sector. There is no need a sidecar need to talk to two Pilots within different sector.

**Comment by rshriram** [comment]
But isn’t that the same as what I said? If the sidecars in a sector only depend on services in that sector, the data plane is already partitioned nicely.

**Comment by YonkaFang** [comment]
> But isn’t that the same as what I said? If the sidecars in a sector only depend on services in that sector, the data plane is already partitioned nicely.

Actually we won't limit the sidecar in a sector to only access the services in this sector, but instead we place the sidecar to a sector with the most "compatibility" which means the existing services are most alike with the sidecar depends on, and also that means importing this sidecar will import least new services to relevant sector.

I'd like to clarify the concept of "services of sector". We determine the services serving by sectors rather than divide/separate services into sectors. That means the services of sectors may overlap and our algorithm will minimize that as far as possible.

**Comment by howardjohn** [comment]
Before we do anything related to perfomance improvements can we at least get a memory profile to understand what area of the code is actually too memory intensive for your use case?

**Comment by seflerZ** [comment]
Yes, the sidecar is partitioned nicely with the sector. However it doesn't mean isolation like the tenant. Let me explain with the following example.

We have 5 services(say s1-5) in the entire system and we'd like to part it into 2 sectors. In order to simplify the problem. Each service has only 1 sidecar. The dependence of each service is as follows:

s1 -> [s2, s4]
s2 -> [s1, s2, s4]
s3 -> [s1, s2]
s4 -> [s3, s5]
s5 -> [s3]

According to our design, we try to cluster the services having same dependencies by K-Means algorithm and the result could be: 

sectorA -> [s1, s2, s3] sidecars connect -> [s1, s2, s4] endpoints loaded
sectorB -> [s4, s5] sidecars connect -> [s3, s5] endpoints loaded

That is to say, sidecar of s1 needs only talk to Pilots within SectorA and it can access all its dependencies.

One draw back of this design is that the services of entire system wouldn't be partitioned into sectors evenly and duplicated endpoints may be present in different sectors. However, this is just a small part.

**Comment by YonkaFang** [comment]
> Before we do anything related to perfomance improvements can we at least get a memory profile to understand what area of the code is actually too memory intensive for your use case?

The memory issues we're facing mainly cover two points:

* static memory which are manly buffered data like endpoints

  We get a memory usage of about 650MB heap size for nealy 300 services and 660 thousands of endpoints in test env and 2.88GB for nealy 8000 services and 3.2 millions of endpoints in production env. And the eventual endpoints size is expected to reach tens of millions.
  From profile result we can see that most buffered data are edsClusters and service shards.

* dynamic memory which are allocated while applying changes(calculating and pushing)

  This case is event worse and a full-push (**to only one proxy**) in the data size of 660 thounsand endpoints will bring 1.25GB memory new allocations and each proxy increment will bring exta 390MB memory allocation increment. 
  Obviously there comes a big memory usage leap while performing full-push and that really challenges our system.

**Comment by mandarjog** [comment]
From the numbers above it seems that storing all the endpoints and services is not your direct problem yet.
32Gb should be able to hold 30m endpoints and 20k services.

It’s the concurrent pushes that consumes most of the memory. 1.2G for 660k endpoints sounds like a big number, but does , we should be normally pushing 5 x 2k ~ 10 k ep if sidecar resource is configured. Do you push all endpoints to all sidecars often?

With your numbers, 32Gb allocated to pilot, you will support ~30 concurrent full pushes in test, and far fewer in prod.

how many proxies is one pilot replica handling in your setup and with how much memory ?

**Comment by rshriram** [comment]
It seems like the number of endpoints is the bottleneck and not the number of services. Assuming you are using the Sidecar crd, and the K-Means clustering [which is a smart idea btw], if you had the ability to share the endpoints of a cluster computed by Pilot across multiple proxies in the same locality, wont it ease the memory pressure?

**Comment by hzxuzhonghu** [comment]
>It’s the concurrent pushes that consumes most of the memory. 

@mandarjog I donot think so, we do not push to all concurrently. @howardjohn Is that right, we control the number not very high.

**Comment by hzxuzhonghu** [comment]
Anyway, it is better if @seflerZ can provide a heap dump. So that we donot need to guess

**Comment by nrjpoddar** [comment]
@seflerZ how will the proxies be configured to talk to the correct Pilot in its sector? Is there a canonical xDS service which proxies requests to the correct pilot service?

**Comment by seflerZ** [comment]
> @seflerZ how will the proxies be configured to talk to the correct Pilot in its sector? Is there a canonical xDS service which proxies requests to the correct pilot service?

As we shard the pilot loads by services. There is another component named "Pilot-Controller" who has the system wide mapping. The proxy connects to it when starting and tell "Pilot-Controller" which service the proxy residents and then the "Pilot-Controller" send back the corrent Pilot address list to it.

**Comment by nrjpoddar** [comment]
If we have a component which maintains global mapping, we can just use it to distribute proxy connections to pilot using consistent hashing. Pilots can do lazy loading of endpoints based of proxies that are connecting and the Sidecar API attached to them, and have LRU caching for endpoints. Won’t that solve your use case?

**Comment by seflerZ** [comment]
> If we have a component which maintains global mapping, we can just use it to distribute proxy connections to pilot using consistent hashing. Pilots can do lazy loading of endpoints based of proxies that are connecting and the Sidecar API resource attached to them, and have LRU caching for endpoints. Won’t that solve your use case?

Well, that's the point. The consistent hash do achieved the shard but is lack of performance. As the issue describes, we'd like to put proxies with similar dependencies within the same sector. That's why we use K-Means. Consistent hash can do mapping directly from proxy to Pilot, but probably won't care about their dependencies. If we do not do that, with the growing of proxies, probably all Pilots will load all the same endpoints.

**Comment by YonkaFang** [comment]
> From the numbers above it seems that storing all the endpoints and services is not your direct problem yet.
> 32Gb should be able to hold 30m endpoints and 20k services.
> 
> It’s the concurrent pushes that consumes most of the memory. 1.2G for 660k endpoints sounds like a big number, but does , we should be normally pushing 5 x 2k ~ 10 k ep if sidecar resource is configured. Do you push all endpoints to all sidecars often?
> 
> With your numbers, 32Gb allocated to pilot, you will support ~30 concurrent full pushes in test, and far fewer in prod.
> 
> how many proxies is one pilot replica handling in your setup and with how much memory ?

The key point in this issue is that during full-push pilot needs to re-calculate all service-related data even in most cases it's triggered by an event related to a single service. This cost is proportional to services/endpoints size.

As u can see the capacity of a pilot is mainly subject the proxies connected or more accurately the endpoints size of all connected proxies. Then when we're performing horizontal scaling, we care about the memory usage of each pilot node and would not like to STORE UNNECESSARY data.
Maybe a graph is more visualized.

![pilot sharding](https://user-images.githubusercontent.com/14256206/77822910-fec6d080-7131-11ea-9171-8c272b65db63.png)

**Comment by rshriram** [comment]
1. Heap profile as Zhonghu requested
2. Some idea of what specific parts of pilot you would like to change and how, and in what sequence. So that the maintainers and your team can agree on the plan and help guide you properly.

**Comment by seflerZ** [comment]
I think the first step with least controversial is supporting lazy or on demand service loading on Pilot side.

**Comment by howardjohn** [comment]
The first step is to get a heap profile, please. We shouldn't do performance optimization if we don't know what we are optimizing - I'm not convinced that lazy load of services will help here without that.

**Comment by ramaraochavali** [comment]
+1 to what @howardjohn mentioned.  without data it is difficult to measure.

**Comment by seflerZ** [comment]
Okay. I'm on it.

**Comment by mandarjog** [comment]
@seflerZ many people are interested in this,  if you could share profile data that would be great.
