### ISSUE TITLE
prometheus + grafana + istio

### ISSUE THREAD

**Issue by crisarceramos** [istio/istio#2221]
Hi Team,
I know there is a blog about BookInfo sample but please can you help me.
I have 2 services deployed with Istio enabled on minikube. I just need to get the graph for traffic going in to these services. The services are configured for istio.
I tried the example config and hit the services but I can't get any lines appearing on the graphs of grafana istio dashboard. Do I need to create telemetry data config? Any idea please? Really appreciate. thanks.

**Comment by linsun** [comment]
a few things to check 
1) check your local time and server time in sync.  we recently added doc for this.
2) check your mixer configuration all exists.  You can find them in istio.yaml file.  There is a bug that missing mixer config will cause istio dashboard not working.   Workaround is to reinstall istio or mixer.

**Comment by douglas-reid** [comment]
Please see: https://istio.io/troubleshooting#where-are-the-metrics-for-my-service

**Comment by sdake** [comment]
And please see: https://istio.io/troubleshooting#no-grafana-output-when-connecting-from-a-local-web-client-to-istio-remotely-hosted

There are some general reports that minikube doesn't properly synchronize time with the server from which it runs.  May I suggest using kubeadm to deploy (and also correctly deploy NTP).

Step 1: Create kubeadm.conf in your home dir:
```
sdake@falkor-07:~$ cat kubeadm.conf
apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
apiServerExtraArgs:
  runtime-config: admissionregistration.k8s.io/v1alpha1
  feature-gates: AllAlpha=true
pod-network-cidr: 192.168.0.0/16

step two: create a deploy.sh script
```
sdake@falkor-07:~$ cat deploy.sh
#!/bin/bash

echo Deploying Kubernetes
sudo kubeadm init --config=$HOME/kubeadm.conf

echo Setting Credentials for kubectl access
mkdir -p $HOME/.kube
sudo -H cp /etc/kubernetes/admin.conf $HOME/.kube/config
sudo -H chown $(id -u):$(id -g) $HOME/.kube/config
kubectl taint nodes --all=true  node-role.kubernetes.io/master:NoSchedule-

echo Deploying Calico CNI
kubectl apply -f https://docs.projectcalico.org/v2.5/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml

# Deploy Istio
kubectl create -f $ISTIO/istio/install/kubernetes/istio.yaml
kubectl create -f $ISTIO/istio/install/kubernetes/addons/prometheus.yaml
kubectl create -f $ISTIO/istio/install/kubernetes/addons/grafana.yaml
kubectl create -f $ISTIO/istio/install/kubernetes/addons/servicegraph.yaml
kubectl create -f $ISTIO/istio/install/kubernetes/addons/zipkin.yaml
kubectl create -f $ISTIO/istio/install/kubernetes/istio-initializer.yaml

echo VERTICAL
sdake@falkor-07:~$ 
```

step 3:
run deploy.sh

Ensure your running as a regular user, not root.

Cheers
-steve

**Comment by douglas-reid** [comment]
Is there any further action that can be taken here, or can this issue be closed?

**Comment by douglas-reid** [comment]
Closing for now.
