### ISSUE TITLE
Implement one single outbound listener

### ISSUE THREAD

**Issue by lambdai** [istio/istio#22217]
placeholder. Will create an experimental PR
This is supposed to be an implementation detail without istio user facing API change.
The side effects may include
1 unit test broken, will be addressed at inline PR
2. Envoy metric structure change.
3. debugging knowledge base update 

Not longer block v2 to v3 because v3 supports bind_to_port by accident 
~~Blocks:~~
~~https://github.com/istio/istio/issues/16458~~
~~V2 -> V3 API migration~~

Progress
* envoy
  * listener filter disable predicate: allow istio disable sniffer on well known port such as 3306
 https://github.com/envoyproxy/envoy/pull/10389
  * listener improvement: avoid to drain all the connections when updating on fat outbound virtual outbound listener is  
https://github.com/envoyproxy/envoy/pull/10491
https://github.com/envoyproxy/envoy/pull/10528
https://github.com/envoyproxy/envoy/pull/10662

* istio
  * rewrite passthrough filter chain builder : https://github.com/istio/istio/pull/23071
  * set dst port in non-passthough filter chain: https://github.com/istio/istio/pull/23132
  * optional, build virtual outbound filter chain by aggregating bind_to_port virtual outbound listener
  * build virtual outbound listener from scratch

**Comment by lambdai** [comment]
CC @howardjohn Please link what issues could be affected, either making life easier to harder. Thanks!

**Comment by hzxuzhonghu** [comment]
@lambdai What's the motivation?

**Comment by lambdai** [comment]
> @lambdai What's the motivation?

Sorry for the late reply. The is the issue to track the last blocker for #10533

**Comment by lambdai** [comment]
Subtask: Add http sniffer on passthrough

**Comment by htuch** [comment]
FWIW the v2 API support is currently scheduled to be removed from Envoy in Q1. I think this is the main Istio issue that needs resolving before then.

**Comment by howardjohn** [comment]
not stale
