### ISSUE TITLE
Documentation on mesh expansion lacks detail

### ISSUE THREAD

**Issue by mkoppanen** [istio/istio#22224]
**Bug description**

Documentation on adding a production workload mesh expansion VM is confusing and lacking in detail.

[ ] Configuration Infrastructure
[ x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

I open documentation page and by following the instructions I am able to add mesh expansion VM. The documentation refers to: "There are many tools and procedures for managing certificates for VMs - Istio requirement is that the VM will get a certificate with an Istio-compatible SPIFEE SAN, with the correct trust domain, namespace and service account." 

However, this does not clarify what is istio-compatible SPIFEE SAN, how do deduct correct trust domain, namespace and service account. I would imagine such certificates can be generated using openssl command-line tool but again, the documentation is not clear on the requirements. 

This is specifically with version 1.5, as I was able to follow 1.4 documentation and have a cluster that I am trying to upgrade now.

**Steps to reproduce the bug**

Open page  https://istio.io/docs/examples/virtual-machines/single-network/ and try to reproduce steps described

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

1.5

**How was Istio installed?**

istioctl manifest apply but this is not relevant to the issue

**Environment where bug was observed (cloud vendor, OS, etc)**

Ubuntu mesh VM, baremetal kubernetes.

**Comment by irisdingbj** [comment]
doc already been updated
