### ISSUE TITLE
Istio agent should calculate the graceperiod based on the cert TTL, not client-side settings

### ISSUE THREAD

**Issue by myidpt** [istio/istio#22226]
**Bug description**
https://github.com/istio/istio/blob/master/security/pkg/nodeagent/cache/secretcache.go#L812
sc.configOptions.SecretRefreshGraceDuration is taken from the binary parameter.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ X ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Grace period should be calculated based on a ratio of the real certificate TTL.

**Steps to reproduce the bug**
Have the istio agent link to a CA that disrespects the lifetime setting in the request, the istio agent will have an improper grace period.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by incfly** [comment]
Seems mostly done in the PR? Maybe we can close? feel free to reopen.

**Comment by myidpt** [comment]
Still need to cherry-pick to 1.5.
