### ISSUE TITLE
Duplicate podinfo volume definitions with seldon-core

### ISSUE THREAD

**Issue by baracoder** [istio/istio#22246]
**Bug description**

We had a problem when testing seldon core with istio 1.5.0 with duplicate `podinfo` volume definitions. It works fine with 1.4.6 though.
Though there is a PR for a check for duplicate podinfo volumes in seldon
https://github.com/SeldonIO/seldon-core/pull/940

**Expected behavior**

istio 1.5.0 works with seldon core 1.0.2

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

install istio 1.5.0
install seldon 1.0.2

**How was Istio installed?**

```
istioctl manifest apply
```

**Environment where bug was observed (cloud vendor, OS, etc)**

google cloud - GKE v1.14.10-gke.17

**Comment by howardjohn** [comment]
ill rename it istio-podinfo

**Comment by adriangonz** [comment]
Thanks for the quick fix @howardjohn! Are you planning to release this with Istio `1.5.3`?

I can see that the PR was flagged to get cherry-picked to the `release-1.5` branch, but it seems there were some conflicts there.

**Comment by AndriiNeverov** [comment]
@howardjohn any chance these merge conflicts will be resolved and this fix makes it into the next 1.5.x release?
