### ISSUE TITLE
support generating and plugin cert when installing Istio service mesh

### ISSUE THREAD

**Issue by irisdingbj** [istio/istio#22245]
To address remaining part of https://github.com/istio/istio/pull/22075

- add code and a command to automate creation of a root CA (if user doesn't have one already)

- code to create intermediary cert in a form of a Secret ( automating the steps described in 'pre configured CA')

- upload the intermediary root cert in 'istioctl apply', before starting the cluster

- if possible, replicate kubeadm CLI args (https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/) and names

- add code to generate a second intemediary cert for other clusters in case of MC (or leave a TODO)

- generate an intermediary root CA dedicated to VMs

- generate VM certs from the VM root CA

**Comment by costinm** [comment]
Sounds good, my main question is what should we default to ? 

IMO 'istioctl apply' should by default pre-provision a root CA and intermediate CAs - if it doesn't already exists. It is easy to check if user already set a Secret with the given name, and create one.

So the options will be:
- user has a root CA already - they create the intermediary CA (according to the docs) and upload the secret containing intermediary CA as Secret before running istioctl apply
- user doesn't have an existing CA - istioctl will check the Secret is missing, and create a root CA ( possibly reuse the root CA previously auto-created by Citadel/Istiod ) AND generate the intermediary CA.

This will make all installs consistent - we'll use root CA + intermediary in ALL cases, the only difference will be that in 'self-managed' istioctl will handle the root CA and intermediary install. 

Upgrade is not an issue: existing workloads use the current root CA directly, and trusts it. 
After 1.6 upgrade - new workloads will have a chain containing the newly generated intermediate. CA, but still signed by the original root CA.

In addition, istioctl should generate the second intermediate CA for VMs - and possibly in future additional ones for multi-cluster, so each cluster can get certs signed by a different chain from the central istiod CA.

Of course, priority is consistency, VM support and using better practices for CA management by default.

We can provide some options to allow users to use 'offline' root CA - i.e. keep the real root CA on disk, assuming they have a way to not lose it. I'm not sure it's worth it - more useful would be to have some scripts to use Vault or cloud KMS for root CA and generate itermediate CA for istiod.   

I think cleaning up the startup process - so we always use the same scheme, root + intermediate - would be great.

**Comment by irisdingbj** [comment]
@costinm I have implemented the logic in PR #22384 , Can you please take a look?

**Comment by sdake** [comment]
@costinm The PR associated with this review was in plan for 1.6. @irisdingbj is on national holiday until May 10th. Is this work mandatory for 1.6? I can rebase the associated PR if need be as I am coverage for @irisdingbj while she is on holiday. I would like some understanding from the top level CODEOWNERS this work is needed in 1.6.

Cheers
-steve
