### ISSUE TITLE
Manual testing for 1.5.1 fixes

### ISSUE THREAD

**Issue by ostromart** [istio/istio#22259]
*Installation*

istioctl 
- [x] default profile with --wait, run bookinfo [ostromart] 
- [x] --set profile=demo for same install, run bookinfo [ostromart] 

controller
- [x] operator install with init/remove command[morvencao]
- [ ] operator install with helm charts in operator/data/operator-charts
- [x] operator install with kubectl -f https://istio.io etc.  [ostromart]
- [ ] run bookinfo 
- [ ] profile to demo for same install, run bookinfo  

*Enablement*

- [x] manifest apply with demo, then iterate through disabling, ingress gateway, prometheus, grafana and ensure resources are pruned. [ostromart]
- [x] same as above with controller

*API surface*

istioctl 
- [x] manifest apply k8s field partial override - ensure this is merged with the builtin defaults. both components and addonComponents [ostromart]
- [ ] ensure enum values can be passed in
- [x] k8s overlays of output manifest [ostromart] 

controller 
- [x] manifest apply k8s field partial override - ensure this is merged with the builtin defaults. both components and addonComponents. [ostromart] NOTE: addonComponents still WIP.
- [ ] ensure enum values can be passed in
- [x] k8s overlays of output manifest [ostromart] 

*Gateways*

- [x] Install three gateways in two namespaces, including ILB per example [ostromart] 
- [x] verify bugs in https://github.com/istio/istio/issues/22253 [ostromart]
- [ ] ensure user gateway overlays work for --set for both values and IOP [ostromart]
- [x] test included gateway config sample  [ostromart]

**Comment by elfinhe** [comment]
@elfinhe add to my mentioned list.

**Comment by sdake** [comment]
cc @istio/wg-environments-maintainers this is a great list for targeting integration testing with Istio 1.6.

**Comment by morvencao** [comment]
Manually test operator install with init/remove command, it is working, but found another issue about field unmarshal, see:  https://github.com/istio/istio/issues/22280
