### ISSUE TITLE
Gateway issues in 1.5.0

### ISSUE THREAD

**Issue by ostromart** [istio/istio#22253]
Tracker for gateways related issues.

**Comment by linuxbsdfreak** [comment]
@ostromart . Will this be part of the next release of Istio with some examples?

**Comment by ostromart** [comment]
Docs and features are now all working and part of 1.5+ with some minor exceptions.

**Comment by linuxbsdfreak** [comment]
@ostromart . Could  you please point me to the docs or samples for configuring multiple istio ingress GWs via the Operator method ?

**Comment by jurgenweber** [comment]
@linuxbsdfreak I found this; https://preliminary.istio.io/latest/docs/setup/install/istioctl/#configure-gateways

but https://github.com/istio/istio/issues/25642

:)
