### ISSUE TITLE
Istio manifests - Prometheus Operator - Add variables to install some of the service monitors

### ISSUE THREAD

**Issue by HugoPuntos** [istio/istio#22262]
**Describe the feature request**

While testing the templates to create the proper configuration to scrape Istio metrics within an existing Prometheus (thanks to the templates located in https://github.com/istio/istio/blob/master/manifests/istio-telemetry/prometheus-operator/templates), I noticed that some of the service monitors (kubelet and kubernetes-services-monitor) generate some configurations which will scrape some metrics already scraped by the Prometheus operator like node-exporters and kube-state-metrics related stuff.

Wouldn't it be a good idea to add some variables in the Helm chart to control the creation of these service monitors?

**Describe alternatives you've considered**

**Additional context**

**Comment by edenzhong7** [comment]
i saw that servicemonitor config for k8s and istio are both in one file, maybe can split in to two yaml and add to a variable to control create k8s's servicemonitor resource or not.
