### ISSUE TITLE
Intermittent error "Unknown error code 104 details Connection reset by peer"

### ISSUE THREAD

**Issue by panchn-n** [istio/istio#22265]
**Bug description**
We have a k8s cluster deployed on CentOS VMs. One of the pods run ansible in it, which has istio injection enabled. From this pod, we try to connect to different hardware components either via REST APIs or their own ansible modules. The k8s cluster is BlackHoleCluster so we create ServiceEntries to enable outbound traffic to those specific IPs. 

The challenge that we are facing is, majority of the times the outbound traffic goes smooth. All of the REST APIs are invoked without any issues. But there are times when the calls fail with error "Unknown error code 104 details Connection reset by peer". This issue is seen even when the BlackHoleCluster is changed to Passthrough cluster. However, the issue was not seen when the IP range was altogether excluded using annotation `traffic.sidecar.istio.io/excludeOutboundIPRanges`, indicating that there is an issue when the outbound traffic is intercepted by Istio.

As noted, this is an intermittent issue and happens rarely, but it does affect the functionality.

**Expected behavior**
Connection to external hosts should succeed every time.

**Steps to reproduce the bug**
Write an ansible task to invoke external service, HTTP in my case.
Create ServiceEntry for that ip and host.
Schedule this task to run for around 12 hours or so. 

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

./istioctl version --remote
`client version: 1.4.3
control plane version: 1.4.3
data plane version: 1.4.3 (23 proxies)`

kubectl version
`Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}`

**How was Istio installed?**
Using istio operator

**Environment where bug was observed (cloud vendor, OS, etc)**
k8s cluster deployed on CentOS VMs.

ServiceEntry Definition
`
{
  "apiVersion": "networking.istio.io/v1alpha3",
  "kind": "ServiceEntry",
  "metadata": {
    "creationTimestamp": "2020-03-17T17:25:29Z",
    "generation": 1,
    "name": "172.22.101.90-egress",
    "namespace": "test-ns",
    "resourceVersion": "300139",
    "selfLink": "/apis/networking.istio.io/v1alpha3/namespaces/test-ns/serviceentries/172.22.101.90-egress",
    "uid": "4c302e1f-6874-11ea-9f75-0200c0a8c8c8"
  },
  "spec": {
    "addresses": [
      "172.22.101.90/32"
    ],
    "hosts": [
      "ext-hardware"
    ],
    "location": "MESH_EXTERNAL",
    "ports": [
      {
        "name": "SSH",
        "number": 22,
        "protocol": "TCP"
      },
      {
        "name": "https",
        "number": 443,
        "protocol": "https"
      }
    ]
  }
}
`

Trace Logs from istio-proxy of the pod connecting to external hosts attached.
[istio-proxy.log](https://github.com/istio/istio/files/4345653/istio-proxy.log)

Unsure if this one is related bug, but the reporter seems to get the same error https://github.com/envoyproxy/envoy/issues/7775

**Comment by howardjohn** [comment]
`Connection reset by peer` suggests the backend you are hitting is closing the connection.

Are you certain it does not happen if you bypass the ip range? You mentioned it runs for 12hrs so it sounds very rare, is it possible it is just not detected during that time you bypass the iprange?

**Comment by howardjohn** [comment]
@panchn-n any update on ^?

**Comment by woodliu** [comment]
I found that issue, from app istio sidecar , can find the log like，cased by the incorrect CA 
```
2020-10-14T20:45:36.059355Z     debug   envoy connection        [C6102] handshake expecting read
2020-10-14T20:45:36.059460Z     debug   envoy connection        [C6102] handshake expecting read
2020-10-14T20:45:36.081259Z     debug   envoy connection        [C6102] handshake error: 1
2020-10-14T20:45:36.081366Z     debug   envoy connection        [C6102] TLS error: 268436504:SSL routines:OPENSSL_internal:TLSV1_ALERT_UNKNOWN_CA
2020-10-14T20:45:36.081385Z     debug   envoy connection        [C6102] closing socket: 0
2020-10-14T20:45:36.081718Z     debug   envoy conn_handler      [C6102] adding to cleanup list
2020-10-14T20:45:36.610251Z     debug   envoy conn_handler      [C6103] new connection
```
