### ISSUE TITLE
Does Mixerv2 support denier?

### ISSUE THREAD

**Issue by lurenjia528** [istio/istio#22289]
istio 1.4.2  
does mixerv2 support denier?

https://preliminary.istio.io/zh/docs/ops/configuration/telemetry/in-proxy-service-telemetry/

**Comment by yangminzhu** [comment]
The denier is replaced by the new authorization policy in 1.5. The mixer v1 denier is deprecated in 1.5. For mixer v2 (maybe you're actually referring to the WASM), I don't think it will support the mixer v1 denier, you can implement your own denier logic in WASM though.

**Comment by kyessenov** [comment]
There is no mixer v2 :) Telemetry v2 does not support authorization in either 1.4 or 1.5 (it's telemetry, not policy). Envoy upstream allows you to implement a custom extension for authorization flows that are not supported by istio (see for example, https://github.com/mandarjog/proxy/tree/jwt_header_sample/extensions/jwt_header).
