### ISSUE TITLE
"Istioctl manifest generate --set" error messages lack context

### ISSUE THREAD

**Issue by nikhilbalekundargi** [istio/istio#22286]
**Bug description**
I am trying to install istio using istioctl. I want all the components of default installation plus sds and stackdriver apater to be installed. Using below command to generate the manifest using istioctl -

istioctl manifest generate \
--set values.gateways.enabled=true \
--set values.gateways.istio-ingressgateway.enabled=true \
--set values.gateways.istio-ingressgateway.sds.enabled=true \
--set values.global.mtls.enabled=ture \
--set values.prometheus.enabled=true \
--set components.citadel.enabled=true \
--set components.galley.enabled=true \
--set components.pilot.enabled=true \
--set components.policy.enabled=true \
--set components.sidecarInjector.enabled=true \
--set components.telemetry.enabled=true \
--set values.mixer.adapters.stackdriver.enabled=true > istio-new.yaml

Error: validation errors (use --force to override): 
json: cannot unmarshal string into Go value of type bool

istioctl manifest generate --set values.mixer.adapters.stackdriver.enabled=true >  enable-telemetry-stackdriver-adapter.yaml works fine but few components like sidecarinjector, telemetry, policy, sds are missing.

[ ] Configuration Infrastructure
[ ] Docs
[X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Should generate yaml file.

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.17", GitCommit:"bdceba0734835c6cb1acbd1c447caf17d8613b44", GitTreeState:"clean", BuildDate:"2020-01-17T23:10:13Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
not relevant

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by esnible** [comment]
It is the `--set values.global.mtls.enabled=ture`.

`true` is mispelled.

Agreed the error message could be better!

**Comment by esnible** [comment]
I looked at improving the error message.

Istio calls https://godoc.org/github.com/golang/protobuf/jsonpb#Unmarshal passing in
```
  mtls:
    enabled: ture
```

The protobuf unmarshaler just returns "cannot unmarshal string into Go value of type bool".
I could output the context, in YAML or JSON, but it includes all of the parameters.

I couldn't find any way to get the protobuf unmarshaler to output which field it failed unmarshaling.

My hope is to produce a message "cannot unmarshal 'ture' into value of type bool at values.global/mts.enable" but I don't know how to make that happen.

**Comment by nikhilbalekundargi** [comment]
> It is the `--set values.global.mtls.enabled=ture`.
> 
> `true` is mispelled.
> 
> Agreed the error message could be better!

my bad. Thank you for pointing out.

**Comment by shamsher31** [comment]
> My hope is to produce a message "cannot unmarshal 'ture' into value of type bool at values.global/mts.enable" but I don't know how to make that happen.

Hey @esnible,  I was able to achieve a sort of static validation for boolean values, although the work is still in progress (need lot of improvements), here is [how it detects invalid bool values](https://github.com/istio/istio/pull/21210/files#diff-2405f93b84e56f54e6d8c6052b918e52R126) and output error messages.

```json
$ istioctl manifest apply 
   --set values.global.mtls.enabled=ture 
   --set values.gateways.enabled=0  
   --set values.gateways.istio-ingressgateway.enabled=1 
   --set components.policy.enabled=true 
```
```json
Error: failed to apply manifests: 
 Unsupported value: "ture", supported values for: "values.global.mtls.enabled" is [true false], 
 Unsupported value: "0", supported values for: "values.gateways.enabled" is [true false], 
 Unsupported value: "1", supported values for: "values.gateways.istio-ingressgateway.enabled" is [true false]
```

**Note**: This is a WIP for `manifest apply`.

**Comment by esnible** [comment]
@shamsher31 I like it.  The same logic will work with `manifest generate` and `istioctl upgrade` so it makes sense to add `--set` validation to those two commands or refactor it into `yamlFromSetFlags()`.

**Comment by shamsher31** [comment]
@esnible The PR https://github.com/istio/istio/pull/22799 was open from a long time.
