### ISSUE TITLE
Tracing microservices with Istio's Jaeger

### ISSUE THREAD

**Issue by medhedho** [istio/istio#22293]
Hello,

I deployed Istio to my AKS cluster. I want to trace my Spring microservices with Jaeger (zero instrumentation). The docs say that I must propagate the B3 trace headers, so I set the "JAEGER_PROPAGATION = b3" environment variable on my deployments.
Now, I see the traces but there is no hierarchy. Every trace is made of a single span. It is possible that the Envoy proxies are not tracing my services, so each time a request hits one of them it's considered as a new trace.
I switched from the default profile to the demo profile (which includes the egress gateway) and the result is the same.
Maybe the problem is in my microservices manifests. Here are the manifests of my discovery service.

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: discovery-server
  name: discovery-server
spec:
  ports:
  - name: "8761"
    port: 8761
    targetPort: 8761
  selector:
    io.kompose.service: discovery-server
status:
  loadBalancer: {}

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: discovery-server
  name: discovery-server
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: discovery-server
    spec:
      containers:
      - env:
        - name: JAEGER_SERVICE_NAME
          value: discovery-server
        - name: JAEGER_PROPAGATION
          value: b3
        image: medhedho/discovery_zi
        name: discovery-server
        ports:
        - containerPort: 8761
        resources: {}
      restartPolicy: Always
status: {}

**Comment by edenzhong7** [comment]
Is there any span context info in your http header?
