### ISSUE TITLE
how to enable sds on ingress gateway and cert-manager using istioctl

### ISSUE THREAD

**Issue by nikhilbalekundargi** [istio/istio#22306]
Please provide a command to enable SDS and cert-manager using istioctl. I know we can enable gateway using --set components.ingressGateways.enabled=true but how to add SDS? Is there any document with the details of options available?

**Comment by nikhilbalekundargi** [comment]
As per the link https://istio.io/docs/tasks/traffic-management/ingress/ingress-certmgr/ 
istioctl manifest apply \
  --set values.gateways.istio-ingressgateway.sds.enabled=true \
  --set values.global.k8sIngress.enabled=true \
  --set values.global.k8sIngress.enableHttps=true \
  --set values.global.k8sIngress.gatewayName=ingressgateway

Few question -

- if we use --set values.gateways.istio-ingressgateway.sds.enabled=true we dont have to use --set components.ingressGateways.enabled=true?  

- values.gateways.istio-ingressgateway.sds.enabled is helm installation option used in istioctl. Is there any option to enable sds which can be used using components.ingressGateways.enabled.

- do we need to use k8sIngress.enabled, k8sIngress.enableHttps and k8sIngress.gatewayName=ingressgateway? When using helm to install isitio we did not use these options. can anyone clarify the significance of k8sIngress?

**Comment by howardjohn** [comment]
https://preliminary.istio.io/docs/ops/integrations/certmanager/ may be useful as well

`k8sIngress.enabled` is needed to generate the `Gateway` object that makes things work. This is not needed in `master` but is in 1.5 and older versions

**Comment by nak3** [comment]
@howardjohn Does `values.gateways.istio-ingressgateway.sds.enabled` really work? The ingress-gateway does not deploy pod with `node-agent-k8s`,

Actually following commands do not have any diff:

```
istioctl manifest generate \
--set values.global.k8sIngress.enabled=true		      \
--set values.gateways.istio-ingressgateway.sds.enabled=true > tmp1
```
```
istioctl manifest generate \
--set values.global.k8sIngress.enabled=true		      \
--set values.gateways.istio-ingressgateway.sds.enabled=false > tmp2
```

No diff between tmp1 and tmp2.

```
$ diff tmp1 tmp2
$
```

**Comment by howardjohn** [comment]
SDS is always enabled now and does not use a different container, it all runs in istio-proxy

**Comment by nak3** [comment]
Oh, I see. Thank you. So, `--set values.global.k8sIngress.enabled=true` do not make sense actually. I think it should be removed from docs. (If so, I am happy to send the PR.)

**Comment by howardjohn** [comment]
Questions here are addressed and document so I will close this
