### ISSUE TITLE
postsubmit failure on "user: Current not implemented on linux/amd64"

### ISSUE THREAD

**Issue by jmuk** [istio/istio#2230]
See: https://k8s-gubernator.appspot.com/build/istio-prow/istio-postsubmit/242
https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/2225/e2e-smoke/808/

Several tests failed due to the same error: `user: Current not implemented on linux/amd64`. This would mean that the Go runtime on prow are built without cgo, and some info are missing: https://github.com/golang/go/blob/master/src/os/user/lookup_stubs.go#L21

Those tests want to get the current user's home directory for finding the kubernetes config file (typically in `~/.kube/config`).

The code has been there for a while, so this is very rare, but we should minimize its effect.

**Comment by jmuk** [comment]
`e2e-smoke` is also suffering from the same issue.

**Comment by jmuk** [comment]
@yutongz this is the issue we talked offline.

**Comment by jmuk** [comment]
some notes:
The error message highly likely comes from https://github.com/golang/go/blob/master/src/os/user/lookup_stubs.go#L57 this line.

This is already weird, since unix system should use cgo_lookup_unix.go file, I think.
Also this failure happens when it failed to obtain the current UID, or $USER or $HOME are not set. Still not known why this happens randomly.

**Comment by yutongz** [comment]
One update: $USER is not set in Prow. It would be fine if it uses `cgo_lookup_unix.go` instead of `lookup_stubs.go`

**Comment by bradfitz** [comment]
The os/user package didn't work with CGO_ENABLED=0 until Go 1.9 (https://golang.org/doc/go1.9#os/user).

So this means you're probably using Go 1.8 or below with CGO_ENABLED=0.

If you're not setting CGO_ENABLED=0 explicitly, that means it's getting set to 0 automatically because you're cross compiling and don't have the necessary configuration for a cross compilation with cgo.

**Comment by bradfitz** [comment]
Alternatively, it means your CI system doesn't have a C compiler.

**Comment by jmuk** [comment]
Thank you for the info.

We defer to bazel for setups of Go runtime,
- the Go version is 1.9.1 https://github.com/bazelbuild/rules_go/blob/9cf23e2aab101f86e4f51d8c5e0f14c012c2161c/go/toolchain/toolchains.bzl#L5
- `CGO_ENABLED=0` is always set https://github.com/bazelbuild/rules_go/blob/9cf23e2aab101f86e4f51d8c5e0f14c012c2161c/go/private/toolchain.bzl#L132

(by updating rules_go to the current HEAD, CGO_ENABLED seems to be set when compiling with cgo, see https://github.com/bazelbuild/rules_go/blob/329d8f4ad28265e73c98c4475d49fc9eff57286b/go/private/rules/stdlib.bzl#L88)

**Comment by jmuk** [comment]
Actually only the home directory is used (for getting `~/.kube/config` path for some tests), so instead of digging into the setup of Go runtime, I think we can fix our side to simply use `os.Getenv("HOME")` when `user.Current()` fails. That would be good enough.

**Comment by bradfitz** [comment]
Oh, sorry, I gave you the wrong information before.

The Go 1.9 change was only about looking up a user or group by name or id, and not about `Current`.  But Current will work on Go 1.9 or older Go versions on Unix even with CGO_ENABLED=0, if you have $HOME and $USER set in your environment. Does your CI system have those environment variables defined?

Note that using os.Getenv("HOME") is not correct on Windows, so you shouldn't use that, if you care about Windows users.

**Comment by yutongz** [comment]
We do have $HOME set, but not $USER

**Comment by jmuk** [comment]
okay, let's just set some user name.
Btw, what about Circle-CI? We do use Circle-CI too, right?

**Comment by yutongz** [comment]
Do we see the same issue in Circle-CI

**Comment by jmuk** [comment]
not mentioned in https://circleci.com/docs/1.0/environment-variables/. But seems we can add something on `.circleci/config.yml`

**Comment by bradfitz** [comment]
Or you could even just make your test code do:

```go
// Set a dummy $USER if blank, so os/user.Current works with CGO_ENABLED=0 on CI machines.
func init() {
     if os.Getenv("USER") == "" && os.Getenv("CI") == "true" {
          os.Setenv("USER", "ci")
    }
}
```

**Comment by jmuk** [comment]
circleCI tests doesn't look like suffering the issue; https://circleci.com/gh/istio/istio. Interesting, but maybe circle-ci is fine.

**Comment by yutongz** [comment]
We have multiple places (unit tests / e2e tests). I think I am just gone set $USER in prow script for now and see if we will have the same issue in circle-ci.

**Comment by jmuk** [comment]
agreed.

**Comment by yutongz** [comment]
Another interesting thing @mandarjog found is, although the prow image is installed go 1.9 https://github.com/istio/test-infra/blob/master/scripts/tools/linux-install-golang#L11, for some reason, when actually running tests, it's using go 1.8.

**Comment by yutongz** [comment]
Upgrade golang 1.8->1.9 in Prow and it should solve the actual problem.
https://github.com/istio/test-infra/pull/639

**Comment by jmuk** [comment]
Note that installation of golang is unrelated. IIRC, Bazel installs Go SDK and uses its own version, it does not rely on anything else. Since go version is not specified to `go_register_toolchains`, the default version (1.9.1) should be used.
