### ISSUE TITLE
Allow custom labels to be set on the istio-system namespace

### ISSUE THREAD

**Issue by rolandkool** [istio/istio#22313]
**Describe the feature request**
The current istioctl installation overwrites all labels set on the istio-system namespace. When custom labels are set, for example for use in a network policy, the labels are removed when istioctl is run to install/update Istio. It would be nice if there is an option to patch the istio-system namespace yaml file to include additional labels.

**Describe alternatives you've considered**
We can work around it using custom tool to wrap around istioctl.

**Additional context**

**Comment by howardjohn** [comment]
@ostromart can we just remove namespace from the charts and have istioctl create it if its not found, and do nothing if it is?
