### ISSUE TITLE
The modified configmap in "istio" does not take effect in  time

### ISSUE THREAD

**Issue by packyzbq** [istio/istio#22311]
**Bug description**
Hi, I enconter a problem when I use `kubectl edit cm istio -n istio-system` to modify an entry, for example the zipkin address. I found this modification took effect in the configuration file in istiod, while no changes in sidecar of productpage pod. By the way, I check the file in path `/etc/istio/proxy/envoy-rev0.json`. After I delete the productpage pod, the address changed.

My istio version is 1.5.0

**Expected behavior**

**Steps to reproduce the bug**
1. Use `kubectl edit cm istio -n istio-system` to modify entry
2. check `/etc/istio/proxy/envoy-rev0.json` in any sidecar.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**
`istioctl manifest apply --set profile=demo`

**Environment where bug was observed (cloud vendor, OS, etc)**
CentOS 7.3

**Comment by howardjohn** [comment]
This is working as expected. Its a bootstrap configuration, we cannot change it at runtime

**Comment by howardjohn** [comment]
Closing as this is working as expected
