### ISSUE TITLE
Issue with updating expired LetsEncrypt based certificate

### ISSUE THREAD

**Issue by adurai81** [istio/istio#22334]
**Bug description**
Renewed certs which were imported are not kicking in.

**Expected behavior**
Renewed cert update should have worked without issues.

**Steps to reproduce the bug**
Our Let's Encrypt certificate expired as of yesterday in one of our clusters.

The renewed certificate also has additional sub-domains added to it.

Now I'm trying to understand the right process to get the renewed certificates updated in my cluster.

I followed this page -
https://www.learncloudnative.com/blog/2019-11-30-setup_ssl_certs_with_istio_gateway_part_i/

and essentially did this -

```
kubectl delete istio-ingressgateway-certs -n istio-system
kubectl -n istio-system create secret tls istio-ingressgateway-certs --key privkey.pem --cert fullchain.pem
```

but then there is no effect. Check root still shows -

```
Fetching root cert from istio-system namespace...
Your Root Cert will expire after
   Dec 17 17:35:12 2029 GMT
Current time is
  Thu Mar 19 14:42:56 PDT 2020


=====YOU HAVE 3559 DAYS BEFORE THE ROOT CERT EXPIRES!=====
```

I later reviewed `root-transition.sh` & trying to fit it to the Let's encrypt 
https://archive.istio.io/v1.4/docs/ops/configuration/security/root-transition/

I've the following files were generated by Let's encrypt.
chain.pem
cert.pem
privkey.pem
README
fullchain.pem

kubectl -n istio-system delete secret istio-ca-secret
kubectl create -n istio-system secret generic istio-ca-secret --from-file=ca-key.pem=privkey.pem --from-file=ca-cert.pem=cert.pem --type=istio.io/ca-root
kubectl delete pod -l istio=citadel -n istio-system

kubectl exec pod/feed-api-f4bccc989-45st6 -c istio-proxy -n smc302-sales -- curl http://localhost:15000/certs | head -c 1000

It still shows my old date as "valid_from" for "ca_cert"

```
 "certificates": [
  {
   "ca_cert": [
    {
     "path": "/etc/certs/root-cert.pem",
     "serial_number": "baef924fbee4dc9e13663d39621899d5",
     "subject_alt_names": [],
     "days_until_expiration": "3559",
     "valid_from": "2019-12-20T17:35:12Z",
     "expiration_time": "2029-12-17T17:35:12Z"
    }
   ],
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14+unreleased", GitCommit:"", GitTreeState:"clean"}
```

**How was Istio installed?**
Helm template / kubectl 

**Environment where bug was observed (cloud vendor, OS, etc)**
Oracle Cloud Infrastructure

**Comment by adurai81** [comment]
Now it looks like the certs were propagated to the envoy. Shows today as "valid_from" for "ca_cert" which is correct. But still I can't hit the service.

```
{
 "certificates": [
  {
   "ca_cert": [
    {
     "path": "/etc/certs/root-cert.pem",
     "serial_number": "04e266a1c7bbd43d180cc609a3a546948e1a",
     "subject_alt_names": [
      {
       "dns": "*.armada.spctr.dev"
      },
      {
       "dns": "*.demo.spctr.dev"
      },
      {
       "dns": "*.earth.spctr.dev"
      },
      {
       "dns": "*.jupiter.spctr.dev"
      },
      {
       "dns": "*.mars.spctr.dev"
      },
      {
       "dns": "*.mercury.spctr.dev"
      },
      {
       "dns": "*.moon.spctr.dev"
      },
      {
       "dns": "*.neptune.spctr.dev"
      },
      {
       "dns": "*.pluto.spctr.dev"
      },
      {
       "dns": "*.saturn.spctr.dev"
      },
      {
       "dns": "*.spctr.dev"
      },
      {
       "dns": "*.sun.spctr.dev"
      },
      {
       "dns": "*.uranus.spctr.dev"
      },
      {
       "dns": "*.venus.spctr.dev"
      },
      {
       "dns": "*.vision.spctr.dev"
      }
     ],
     "days_until_expiration": "89",
     "valid_from": "2020-03-19T18:01:32Z",
     "expiration_time": "2020-06-17T18:01:32Z"
    }
   ],
```

**Comment by adurai81** [comment]
Trying to see if this helps to nail down. When I try editing the gateway I see this error -

```
error: gateways.networking.istio.io "spectra-istio-config-gateway" could not be patched: Internal error occurred: failed calling webhook "pilot.validation.istio.io": Post https://istio-galley.istio-system.svc:443/admitpilot?timeout=30s: x509: certificate signed by unknown authority (possibly because of "x509: invalid signature: parent certificate cannot sign this kind of certificate" while trying to verify candidate authority certificate "*.spctr.dev")
You can run `kubectl replace -f /var/folders/fw/fmnk_0g93s193v43_hdy6mkc0000gn/T/kubectl-edit-j7eys.yaml` to try this update again.
```

**Comment by JimmyCYJ** [comment]
Are you trying to update certs at ingress gateway or root cert for internal workloads?
root-transition.sh updates root cert for internal mesh, and ingress gateway needs the internal root cert to set up mTLS connection to internal service sidecar.
The external TLS key/certs are used by ingress gateway to terminate TLS/mTLS connection with a client. If you want to update cert for a particular ingress gateway, you can follow this https://istio.io/docs/tasks/traffic-management/ingress/
