### ISSUE TITLE
[security] Istio CA needs to support different cert TTL for different workloads

### ISSUE THREAD

**Issue by myidpt** [istio/istio#2233]
In some cases, users may want to have different cert TTL for different workloads. For example, the workloads on VMs may want to have longer TTL than K8s ones, for legacy reasons, limitations on network, or long workload downtime.

**Comment by Stono** [comment]
Hey,
I don't know if it helps others but I ended up signing my own 1yr cert against the istio CA to work around this.

https://gist.github.com/Stono/fe83ea90e912f878bf5e49cdd403cbbc

**Comment by myidpt** [comment]
Hi Stono, in your case you don't have a node agent to provision/rotate certs for your device, it makes sense to have a long lived cert.

I think for this issue, we want to support the use case that node agent provisions certs for the workloads. So maybe the node agents will get certs living for days/weeks (not too long, because node agents are still able able to talk to CA)

In the next step, we may support calling Istio CA to provision certs for a normal user using a command line tool. Maybe that will save you some manual work.

**Comment by myidpt** [comment]
We will allow the node agent to specify the target cert TTL when requesting for a new cert from CA. CA will have a max TTL for the certs it can issue. The target TTL should not be greater than the max TTL.

This gives the flexibility for node agents running on different platforms (K8s, onprem, etc) to configure differently, without having CA to differentiate them. In the future, we may have more complex config on CA.
