### ISSUE TITLE
Integrate istio-corends-plugin into either istio/istio or the main build system

### ISSUE THREAD

**Issue by sdake** [istio/istio#22344]
istio-ecosystem contains a coredns plugin that hasn't been rebuilt for a few years. That's a problem as there are over [400 CVEs with this specific plugin](https://github.com/istio/istio/issues/22321#issuecomment-601394612). 

We can either integrate this ecosystem project into the istio namespace, or directly into the istio repository. The code is not significant in scope. Some rework will need to be done to support go's latest module system.

A recommendation on how to integrate (as a new repo in istio org, or just integrate into istio/istio).

The challenge is this is this plugin could be argued as an extension, but also a mandatory component to make multicluster work.

Cheers
-steve

**Comment by sdake** [comment]
cc @ayj @istio/technical-oversight-committee

**Comment by sdake** [comment]
@douglas-reid @mandarjog do you care to take a position on whether this is an extension or not?

After more thought, I have a hard time convincing myself this is an extension, as this is an internal implementation detail that we could modify or remove at any time if a better implementation solution presents itself.

**Comment by douglas-reid** [comment]
I don't think of this as an extension. It certainly is unlike the other extensions that typically have been the purview of the P&T WG (aka extensions and telemetry).

**Comment by ayj** [comment]
cc @costinm who was also doing some DNS related work for 1.6

**Comment by incfly** [comment]
Sorry I am removing the area/security. I think we should create another label `area/prod-security` to distinguish security features vs istio own security vunlerabilties. I think this belongs to the latter case.

**Comment by mandarjog** [comment]
This is required for multi cluster, though any other. DNS  system would also work. The requirement is the function that it provides, not that it is coredns. @rshriram ?

**Comment by sdake** [comment]
@mandarjog I am not hung up on CoreDNS. Any equivalent implementation is fine by me. My requirements are simple:
1. Avoid any known K8s DNS issues (of which 6 /etc/resolv.conf enries+ is a problem)
1. make multicluster work well ;-)

Cheers
-steve

**Comment by sdake** [comment]
@douglas-reid will remove E&T thanks.

**Comment by howardjohn** [comment]
I think efforts are better invested into https://github.com/istio/istio/issues/25925

**Comment by sdake** [comment]
SGTM @howardjohn. I am closing this issue in favor of the Envoy solution.
