### ISSUE TITLE
Support forwarded remote IP address in authorization policy

### ISSUE THREAD

**Issue by yangminzhu** [istio/istio#22341]
**Describe the feature request**
Many customers have been using Istio Authorization Policy to enforce access control based on [source IP on ingress gateway](https://istio.io/docs/tasks/security/authorization/authz-ingress/):

https://discuss.istio.io/t/ingress-gateway-ip-whitelist-with-authorizationpolicy/5558
https://discuss.istio.io/t/istio-ingress-ip-whitelisting/2670
https://discuss.istio.io/t/ingressgate-cant-forward-the-header-x-forwarded-for/5543/5
https://discuss.istio.io/t/ip-whitelisting-trouble-ingress-gateway-is-always-seeing-the-cluster-ip/4436

One big limitation is the user has to set `externalTrafficPolicy: local` in order to preserve the real client side IP address in Kubernetes. This is not supported in all k8s platform and it also will affect the traffic load balancing and is probably not an option for some environments.

What's worse is if there are some external proxy sitting in front of ingress gateway, the source IP will always be the external proxy instead of the real client side IP address.

To improve this use case, it would be better to support the forward IP address in Envoy, and then it could support all the external proxy seamlessly and do not need to set `externalTrafficPolicy: local`.

Related links:
https://github.com/envoyproxy/envoy/issues/5267
https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers.html#x-envoy-external-address

**Describe alternatives you've considered**

**Additional context**

**Comment by yangminzhu** [comment]
A quick update: I have added the needed fields in Envoy: https://github.com/envoyproxy/envoy/pull/10460 and the next step is to add support in the AuthorizationPolicy. It's likely we need to add new fields or conditions to support this, we cannot change the existing source_ip field due to the backward compatibility issue.

**Comment by ludydoo** [comment]
That would be great, if we could authorize based on the original client id. As of now, I cannot restrict the traffic on the ingress gateway to our company's ip blocks because all I receive is the ALB's IP. I have to edit the security groups for the balancer. Would rather not... 
+1

**Comment by zufardhiyaulhaq** [comment]
You also can match based on header right? why don't just match based on the header?

**Comment by brianhussey** [comment]
> You also can match based on header right? why don't just match based on the header?

For us at least, the AuthorizationPolicy based on source IP allows the use of IP addresses or CIDRs. A match based on headers needs far more granular matching capability to be able to support an array of CIDRs (or full list of IP addresses), a wildcard based match is not appropriate for IP address allowlisting or blocklisting.

**Comment by vic614** [comment]
> > You also can match based on header right? why don't just match based on the header?
> 
> For us at least, the AuthorizationPolicy based on source IP allows the use of IP addresses or CIDRs. A match based on headers needs far more granular matching capability to be able to support an array of CIDRs (or full list of IP addresses), a wildcard based match is not appropriate for IP address allowlisting or blocklisting.

I agree, with headers condition, CIDR should be available for matching ip ranges.

**Comment by vic614** [comment]
source.ipBlocks can be applied on only gateways not a specific workload. Is this the current implementation?

**Comment by howardjohn** [comment]
@yangminzhu fixed by https://github.com/istio/istio/pull/27906 or needs more work?

**Comment by yangminzhu** [comment]
> @yangminzhu fixed by #27906 or needs more work?

This can be close now, the final PR adds the necessary documentation on istio.io: https://github.com/istio/istio.io/pull/8390, thanks @kylebevans !
