### ISSUE TITLE
Add Postsubmit Auto Deployment for Istio Performance Dashboard

### ISSUE THREAD

**Issue by carolynhu** [istio/istio#22356]
Currently, the Istio Performance Dashboard is deployed in GKE cluster and the source code is in istio/tools repo.

We need to add a `Google Cloud Build Trigger` to automate the deployment process after a related PR is submitted.

Some useful links can be referenced:
- https://cloud.google.com/cloud-build/docs/deploying-builds/deploy-gke
- https://cloud.google.com/python/django/kubernetes-engine

**Comment by howardjohn** [comment]
Can you sync with @clarketm ? We already have many other deployments that are doing the same thing, we should either re-use that or have a good reason now to
