### ISSUE TITLE
Prometheus adapter should allow operator to config namespace  and subsystem in adapter config

### ISSUE THREAD

**Issue by manlinl** [istio/istio#2236]
Prometheus supports namespace and subsystem for metrics. Today the adapter hard-coded namespace to "istio", and subsystem is not used. 

Instead, the adapter should make those configurable through adapter config.

**Comment by manlinl** [comment]
assigned to @geeknoid  to triage.

**Comment by douglas-reid** [comment]
This might be desirable, but has other implications making this not as simple as suggested. For instance, this will have to follow closely with dashboard generation and other concerns.

Re: subsystems -- i'm not sure of the use case. we are monitoring requests to a service. there really isn't a subsystem involved. what example subsystem is envisioned here?

**Comment by manlinl** [comment]
The adapter is general purpose. Prometheus has <namespace>_<subsystem>_<metric name> convention, why not expose all of them through config?
In long run, the adapter can monitor much more than service,  such as disk_io, network, etc. 

Could you elaborate more about the concerns?
