### ISSUE TITLE
Protocol Selection Snafu: HTTP-like ports create overly broad Envoy listener that makes the port unusable for non-HTTP traffic

### ISSUE THREAD

**Issue by dhermes** [istio/istio#22367]
## Bug description

Any Kubernetes Service port that opts into ["manual protocol selection"][2] for HTTP-like prefixes (`http-*`/ `http2-*` / `grpc-*`) results in an Envoy listener of the form `0.0.0.0_${PORT}`, i.e. match any IP. The **expected** behavior (and the one observed for other protocols like `tls-*`, `https-*` and plain `tcp-*`) is a listener of the form `${CLUSTER_IP}_${PORT}` (e.g. `10.101.20.10_13602`) where the `CLUSTER_IP` is from the underlying Kubernetes Service.

This listener has a very problematic filter for TCP / non-HTTP traffic

```json
{
  "name": "envoy.tcp_proxy",
  "typedConfig": {
    "@type": "type.googleapis.com/envoy.config.filter.network.tcp_proxy.v2.TcpProxy",
    "statPrefix": "BlackHoleCluster",
    "cluster": "BlackHoleCluster"
  }
}
```

which causes **all** outbound traffic on that port to fail if it isn't cleartext (e.g. HTTP-over-TLS fails); it applies to **all** IPs without a more specific rule since `0.0.0.0_${PORT}` uses the "any IPv4 address at all" IP.

## Affected product area (please put an X in all that apply)

- [ ] Configuration Infrastructure
- [ ] Docs
- [ ] Installation
- [x] Networking
- [x] Performance and Scalability
- [ ] Policies and Telemetry
- [ ] Security
- [ ] Test and Release
- [x] User Experience
- [ ] Developer Infrastructure

## Related Issues

- #16458 (this issue was solved for `443` via `PILOT_BLOCK_HTTP_ON_443`)
- #18110 (see [my comment][3] there)
- #20703
- #22150

## Expected behavior

If my Istio pods discover an internal HTTP Kubernetes Service port (e.g. port 8200 named `http-vault` on a `vault` service), this should **not** impact traffic to the outside internet on the same port (e.g. to `https://vault.acme.invalid:8200`).

## Steps to reproduce the bug

See a [gist][1] I have prepared (optimized for copy-paste to ease the burden on the Istio maintainers). It provides step-by-step instructions on how to reproduce (and dive deeper if desired). The high-level steps are as follows:

1.  Create a new isolated testbed [namespace][4]
1.  Create [`sleep` service][5] in the mesh
1.  Create [`Sidecar` resource][6] to limit discovered services to `istio-system` and the testbed namespace
    -   Quickly peek to see number of Envoy listeners from 468 to 15
1.  [Run a plain TCP listener][7] that we can monitor and expose via a public DNS name; note the port (in this case `13602`)
    - Ensure that plain TCP and HTTP requests to this service work from `sleep` pod
1.  [Create `break` service][8] in testbed namespace with port `13602` named `http-break`
    -   Observe newly added `0.0.0.0_13602` Envoy listener
1.  [Verify][9] that when this `0.0.0.0_13602` Envoy listener is active
    -   Plain TCP requests **do not** reach the external TCP listener
    -   HTTP requests **do** reach the TCP listener and have picked up many (internal) Envoy headers
1.  [Rename][10] port to `tcp-break`; which resolves the broken / hijacked port
    -   Observe `0.0.0.0_13602` has been replaced by `10.101.20.10_13602`
    -   Verify plain TCP requests **do** reach the external TCP listener
    -   Verify HTTP requests still reach the TCP listener; and do not carry any extra Envoy headers

Additionally, I've verified in a larger namespace that **every** `0.0.0.0_${PORT}` Envoy listener 
-   (A) has a filter that sends TCP traffic to `BlackHoleCluster` and 
-   (B) has a `${PORT}` that corresponds to a Service port in that namespace with one of
    -   `http-` prefix or named `http`
    -   `http2-` prefix or named `http2`
    -   `grpc-` prefix or named `grpc`
    -   A Service Cluster IP [**explicitly** set to `None`][12] (this can be overcome by prefixing the port name with `tcp-*`)

## Version

```
$ istioctl version --remote
client version: 1.5.0
control plane version: 1.5.0
data plane version: 1.5.0 (44 proxies)
$
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:47:40Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4", GitTreeState:"clean", BuildDate:"2019-12-11T12:34:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

## How was Istio installed?

Fairly standard 1.5.0 installation via `istioctl manifest apply --filename ./config.yml`

```yaml
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    global:
      jwtPolicy: first-party-jwt
      proxy:
        autoInject: disabled
    prometheus:
      enabled: false
    telemetry:
      v1:
        enabled: false
      v2:
        enabled: true
  components:
    pilot:
      k8s:
        env:
        - name: PILOT_SIDECAR_USE_REMOTE_ADDRESS
          value: 'true'
        replicaCount: 2
        hpaSpec:
          minReplicas: 2
    egressGateways: []
    ingressGateways: []
```

## Environment where bug was observed (cloud vendor, OS, etc)

Kubernetes 1.15.7 (not EKS) running on AWS. (I'm happy to provide more information if deemed necessary.)

## Cluster State

(I'm happy to provide [more information][11] if deemed necessary.)

[1]: https://gist.github.com/dhermes/fb95866e742f5d87864d26ee6e357d3c
[2]: https://istio.io/docs/ops/configuration/traffic-management/protocol-selection/#manual-protocol-selection
[3]: https://github.com/istio/istio/issues/18110#issuecomment-600355188
[4]: https://gist.github.com/dhermes/fb95866e742f5d87864d26ee6e357d3c#create-a-test-namespace
[5]: https://gist.github.com/dhermes/fb95866e742f5d87864d26ee6e357d3c#create-a-service-in-the-mesh
[6]: https://gist.github.com/dhermes/fb95866e742f5d87864d26ee6e357d3c#create-a-sidecar-to-limit-the-discovered-services
[7]: https://gist.github.com/dhermes/fb95866e742f5d87864d26ee6e357d3c#spin-up-raw-tcp-server
[8]: https://gist.github.com/dhermes/fb95866e742f5d87864d26ee6e357d3c#create-a-kubernetes-service-that-breaks-tcp_port
[9]: https://gist.github.com/dhermes/fb95866e742f5d87864d26ee6e357d3c#verify-tcp-traffic-gets-blackholed
[10]: https://gist.github.com/dhermes/fb95866e742f5d87864d26ee6e357d3c#using-a-non-http-protocol
[11]: https://istio.io/about/bugs/#generating-a-cluster-state-archive
[12]: https://gist.github.com/dhermes/fb95866e742f5d87864d26ee6e357d3c#service-with-clusteripnone

**Comment by howardjohn** [comment]
This is the same issue as https://github.com/istio/istio/issues/16458, right? Or is there something different here I am missing?

**Comment by dhermes** [comment]
> This is the same issue as #16458, right? 

My apologies, I had been thinking of that issue as the "443 gets hosed" / `PILOT_BLOCK_HTTP_ON_443` issue. That issue is more generic than I had been "imagining it".

However, it didn't feel great to read your initial reply. I did a ton of work narrowing in on this exact issue and eliminating the noise in the [gist][1] I made. (As someone who has been in the maintainer's shoes, I was trying to deliver an actionable and focused state that maintainers could put a cluster in.)

If you'd like, we can close this issue as a duplicate of #16458, but I hope the information doesn't get lost here. Having a port just get "claimed" for the entire mesh is a really scary proposition as my team rolls out `istio`.

> Or is there something different here I am missing?

This issue is intended to be focused on the narrow case of "(1) Kubernetes Service (2) known cluster IP (3) port name prefixed with `http-` / `http2-` / `grpc-`". I.e. it doesn't also include the (possibly related) issues of `ServiceEntry` or `Sidecar` entries that **also** cause listeners on `0.0.0.0`.

I sent #22380 as a possible way to spur discussion forward on this.

[1]: https://gist.github.com/dhermes/fb95866e742f5d87864d26ee6e357d3c

**Comment by howardjohn** [comment]
Fair enough, I think I personally grouped them together because the fix I envision applies to both, although they are not strictly the same issue. We can keep them separate if you prefer

**Comment by howardjohn** [comment]
And I do really appreciate the level of detail in the issue. Thank you!

**Comment by dhermes** [comment]
Moving the discussion from #22380 over here (for search / discoverability). I'm happy to hear that you guys have the "protocol sniffing snafu" on your radar and that you've got a plan:

> We will actually most likely go the other extreme and have a single listener: #22217

However, as I thought more about this since @howardjohn and I last discussed, ISTM that a fix like #22380 is needed (e.g. in a point-release like 1.5.1 and possibly backports like 1.4.7 / 1.3.9, AFAIK the issue wasn't present in the 1.2.x series). Right now the fact that an HTTP port gets "owned" is an issue of **correctness** while the single listener approach addressed not only correctness but also performance issues with the current approach.

ISTM correctness should be the first priority, then optimizations follow after, no?

**Comment by howardjohn** [comment]
I agree, I think that https://github.com/istio/istio/pull/17169 is a more suitable short term fix though and is much easier to backport since its a small change (#22380 is small in terms of lines of code, but a fairly substantial change in what config we generate). @yxue @lambdai any opinions here?

**Comment by dhermes** [comment]
SGTM. One thing to worry about for the approach in #17169 is that HTTP traffic still gets the internal-only headers (including the massive base64 encoded protobuf in `x-envoy-peer-metadata`), e.g. in my [Verify TCP Traffic Gets Blackholed][1] section, the HTTP request outgoing to `http://0.tcp.ngrok.io:13602` ended up passing this through to the other end:

```
nc -l 12892  # Server
# GET / HTTP/1.1
# host: 0.tcp.ngrok.io:13602
# user-agent: curl/7.64.0
# accept: */*
# pod: sleep-54c989bc97-lks72
# x-forwarded-for: 10.101.151.188
# x-forwarded-proto: http
# x-envoy-internal: true
# x-request-id: d9be301d-d90d-9f3b-afeb-aa9f7011fe78
# x-envoy-peer-metadata: CiAK...
# x-envoy-peer-metadata-id: sidecar~10.101.151.188~sleep-54c989bc97-lks72.dhermes-repro~dhermes-repro.svc.cluster.local
# x-b3-traceid: 875fdf0be92d99a619b41aa11660abcf
# x-b3-spanid: 19b41aa11660abcf
# x-b3-sampled: 1
# content-length: 0
#
```

[1]: https://gist.github.com/dhermes/fb95866e742f5d87864d26ee6e357d3c#verify-tcp-traffic-gets-blackholed

**Comment by howardjohn** [comment]
Hmm.. does #22380 avoid that? In both cases the traffic should go through a similar route internally, so if I had to guess I would have thought they both have that issue?

**Comment by dhermes** [comment]
> does #22380 avoid that

Tough to say as an outsider, but #22380 will make sure the listener matches the cluster IP, e.g.

```json
{
  "name": "10.101.20.10_13602",
  "address": {
    "socketAddress": {
      "address": "10.101.20.10",
      "portValue": 13602
    },
    ...
}
```

instead of just a catch-all

```json
{
  "name": "0.0.0.0_13602",
  "address": {
    "socketAddress": {
      "address": "0.0.0.0",
      "portValue": 13602
    }
    },
    ...
}
```

**Comment by dhermes** [comment]
@howardjohn I just noticed there are 3 `istio-pilot` port names that should probably be changed to avoid creating a black hole listener

Getting all the `istio-system` service ports from a cluster (slightly different than what I'd previously reported because this cluster has the default `istio-ingressgateway` enabled):

```
$ kubectl get services --namespace istio-system --output go-template='{{ range .items }}{{ $save := . }}{{ range .spec.ports }}{{ $save.metadata.namespace }}:{{ $save.metadata.name }}:{{ .name }}:{{ .port }}:{{ .protocol }}:{{ $save.spec.clusterIP }}{{ "\n" }}{{ end }}{{ end }}'
istio-system:istio-ingressgateway:status-port:15020:TCP:10.102.12.184
istio-system:istio-ingressgateway:http2:80:TCP:10.102.12.184
istio-system:istio-ingressgateway:https:443:TCP:10.102.12.184
istio-system:istio-ingressgateway:kiali:15029:TCP:10.102.12.184
istio-system:istio-ingressgateway:prometheus:15030:TCP:10.102.12.184
istio-system:istio-ingressgateway:grafana:15031:TCP:10.102.12.184
istio-system:istio-ingressgateway:tracing:15032:TCP:10.102.12.184
istio-system:istio-ingressgateway:tls:15443:TCP:10.102.12.184
istio-system:istio-pilot:grpc-xds:15010:TCP:10.102.16.170
istio-system:istio-pilot:https-xds:15011:TCP:10.102.16.170
istio-system:istio-pilot:https-dns:15012:TCP:10.102.16.170
istio-system:istio-pilot:http-legacy-discovery:8080:TCP:10.102.16.170
istio-system:istio-pilot:http-monitoring:15014:TCP:10.102.16.170
istio-system:istio-pilot:https-webhook:443:TCP:10.102.16.170
istio-system:istiod:https-dns:15012:TCP:10.102.30.243
istio-system:istiod:https-webhook:443:TCP:10.102.30.243
```

and we see three ports

```
istio-system:istio-pilot:grpc-xds:15010:TCP:10.102.16.170
istio-system:istio-pilot:http-legacy-discovery:8080:TCP:10.102.16.170
istio-system:istio-pilot:http-monitoring:15014:TCP:10.102.16.170
```

corresponding to blackhole listeners

```
./istio-1.5.0/bin/istioctl proxy-config listeners \
  --namespace "${NAMESPACE}" \
  "${POD_NAME}" \
  --output json \
  | jq '.[].name' -r
# 10.102.157.153_80
# 10.102.157.153_15020
# 10.102.30.243_15012
# 10.102.16.170_15012
# 10.102.16.170_15011
# 10.102.30.243_443
# 10.102.12.184_15443
# 10.102.16.170_443
# 10.102.12.184_443
# 10.102.12.184_15029
# 10.102.12.184_15032
# 10.102.12.184_15020
# 10.102.12.184_15031
# 10.102.12.184_15030
# 0.0.0.0_15014
# 0.0.0.0_15010
# 0.0.0.0_80
# 0.0.0.0_8080
# virtualOutbound
# virtualInbound
# null
```
