### ISSUE TITLE
Prometheus adapter should allow a metric template instance map to multiple Prometheus metrics

### ISSUE THREAD

**Issue by manlinl** [istio/istio#2237]
Current implementation the adapter only allows an template instance to map to a single native Prometheus metric. But sometimes, it is desirable to to map  e.g. requestcount.metric.istio-system to two Prometheus metrics: incoming_request_count for destination service, outgoing_request_count for source service?

Can we add such support?

I

**Comment by manlinl** [comment]
assign to @geeknoid  for triage.

**Comment by douglas-reid** [comment]
I think we should have a larger discussion here. I'm not sure I understand the use case fully.

Prometheus has dimensions for metrics.

`istio_request_count` includes both source and destination service labels. So, if you wanted to view counts from a source, you could craft a promql query for `istio_request_count` aggregated by source service (and similarly for destination service).

It is also possible to use Prometheus' own config to derive metrics from metrics, via recording rules.

What is the motivation to map into two or more metrics from one conceptual metric?

**Comment by manlinl** [comment]
Access control is the first thing under discussion. Physically creating two metric data streams, potentially allow applying different access control policies on two data streams., e.g. source service developer can query outgoing request to a destination service without accessing destination service's telemetry data. 

It appears  the current adapter config is rather easy to extend to support such model (though implementation requires bigger change).
