### ISSUE TITLE
Error in MAC configuration istioctl environment variable

### ISSUE THREAD

**Issue by zp19931128** [istio/istio#22379]
After I install istio on the macbook pro and configure the istionctl environment variable (~/.bash_profile), I run the command with error zsh: exec format error: istioctl. The release of istio version is 1.5.0

**Comment by howardjohn** [comment]
Did you download the OS X version?

**Comment by zp19931128** [comment]
> Did you download the OS X version?

The version of Linux I downloaded

I see. Thank you
