### ISSUE TITLE
Support dynamic set log level

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#22377]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

Many users have reported kinds of configs that do not take effect. There are kinds of reasons, maybe invalid config.  If we could provide changing the log level on the flight, it is better.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
You can already do this https://istio.io/docs/ops/diagnostic-tools/controlz/

**Comment by howardjohn** [comment]
and `istioctl pc logs` for proxy

**Comment by hzxuzhonghu** [comment]
Thanks for the info and i will have a try

**Comment by seflerZ** [comment]
Sure, it is.
