### ISSUE TITLE
istio-1.4.3: Healthy pod return error 503 for every request

### ISSUE THREAD

**Issue by 1hanymhajna** [istio/istio#22388]
After a regular deployment to our cluster, with scale of 4, one of the pods started on a machine (Let call it Machine A) that was marked by aws as have a hardware issue (it resolved by aws before the deployment). **we start see some connection reset when trying to call the service (directly or via the gateway).**

We saw that the pod that started on *Machine A* had a connection issue but still marked as healthy,
here is the response when the pod got the request:
```bash
(base) ip-xx-xx-xx-37:~ hany$ curl -v http://xxxxxxx/xxxx/health
*   Trying xx.xx.xx.xx:80...
* TCP_NODELAY set
* Connected to xxxxx.co (xx.xx.xx.xx) port 80 (#0)
> GET /xxxxxx/health HTTP/1.1
> Host: xxxxxx
> User-Agent: curl/7.65.3
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 503 Service Unavailable
< content-length: 91
< content-type: text/plain
< date: Sun, 22 Mar 2020 11:42:18 GMT
< server: istio-envoy
<
* Connection #0 to host xxxxx left intact
upstream connect error or disconnect/reset before headers. reset reason: connection failure
```

Here is the log of istio-sidecar in trace level:
[out.txt](https://github.com/istio/istio/files/4368537/out.txt)

*Please notice*:

1. we verified that new pods in the same machine working fine without any connection reset by peer errors
2. The same error we see in other outbound traffic in 1.4.3 (opened on istio before few days ago with the same error code (Unknow error code 104):
https://github.com/istio/istio/issues/22265
```
[Envoy (Epoch 0)] [2020-03-22 12:48:38.808][27][debug][misc] [external/envoy/source/common/network/io_socket_error_impl.cc:29] Unknown error code 104 details Connection reset by peer
```
3. Restart of the istio-proxy container does not resolve the issue
4. Restart of our container does not resolve the issue
5. Restart of the pod and starting it again make it work

**And the main issue that we worry about is how can we know if the pod is healthy? cause in our situation, Kubernetes API marked it as healthy and send traffic to it, but in fact, it wasn't**  

We are running on to istio-1.4.3 on eks 1.14,
Our main configuration: 
- MTLS ENABLED
- SDS DISABLED 
- rewriteAppHTTPProbe = true

**Comment by erdun** [comment]
I also meet the situation when envoy should proxy to http://xxx.xx.svc.cluster.local but it proxies to https://xxx.xx.svc.cluster.local and return witch code 503, it's unacceptable.

**Comment by 1hanymhajna** [comment]
Anyone can help with this, please we really need help here, it happened again and again and again, it sounds like not production ready

**Comment by howardjohn** [comment]
@1hanymhajna are you able to reproduce this in any way? From Istio perspective, it looks like health probes are passing. Since you restart container without fixing, I doubt it is some startup related issues. It seems like the remote backend you are hitting is having issues? Based on the `remote close` logs?

**Comment by howardjohn** [comment]
@1hanymhajna any more info? I suspect this is not Istio as the root cause
