### ISSUE TITLE
Parameterise grafana dashboard 's with datasource

### ISSUE THREAD

**Issue by rverma-jm** [istio/istio#22408]
**Describe the feature request**
Can we add a datasource filter in all the dashboards rather then specifying it while creating dashboard.
We are currently running a single grafana instance which is connecting with different clusters. Each cluster has istio-control pane and prometheus.

Wondering how the dashboards are utilised if we are using a multi-cluster mesh. 

**Describe alternatives you've considered**
Managing alternate dashboards which are parameterized.

**Additional context**
The dashboards can be defaulted to prometheus cluster specified while creating them. This will not break existing user experience.

**Comment by howardjohn** [comment]
We recently started publishing these with the datasource parameterized: https://gcsweb.istio.io/gcs/istio-prerelease/prerelease/1.6.0-alpha.0/grafana and are publishing to grafana.com. Is that what you are looking for?

**Comment by rverma-jm** [comment]
I tried to import this dashboard but its not something which I expected. 

<img width="1194" alt="Screenshot 2020-03-24 at 7 04 10 PM" src="https://user-images.githubusercontent.com/58203822/77431234-6a433200-6e02-11ea-9ca1-cb7a67673d6e.png">

I am expecting another drop down for a datasource.
I think currently DS_PROMETHEUS is an input variable, what I am proposing is making it as part of templating list as well.

**Comment by howardjohn** [comment]
Ah I get what you mean. Thanks for clarifying. Is this common in other dashboards @douglas-reid ?

**Comment by rverma-jm** [comment]
Workaround
Under this lines
```
"templating": {
      "list": [
```
insert this:
```
{
            "hide": 0,
            "label": "datasource",
            "name": "DS_PROMETHEUS",
            "options": [],
            "query": "prometheus",
            "refresh": 1,
            "regex": "",
            "type": "datasource"
          },
```

**Comment by douglas-reid** [comment]
I think this has been addressed now, correct?  Closing for now. Please re-open if it hasn't addressed your issue.
