### ISSUE TITLE
Support for Kubernetes Ingress with Multiple Istio Gateway Controllers

### ISSUE THREAD

**Issue by iusergii** [istio/istio#22400]
**Describe the feature request**
According to Docs I can use Istio Gateway Controller for standart Kubernetes Ingress using annotation with configured ingressClass. Something like: `kubernetes.io/ingress.class: istio`.

With multiple  gateway setup I'd like to have an option to configure which gateway should processes Ingress objects.  

**Describe alternatives you've considered**
We use multiple gateway for two main reason:
1. We terminate TLS on AWS Classic Load-Balancer and maintain multiple domains.  
2. Internal / External access. 

With first case we can migrate to Network Load-Balancere which is still lacking a lot of configuration from k8s side. Don't see workarounds for second case.

**Additional context**
We're planning migration to Istio and would like to get rid of current Ingress Controller.

**Comment by howardjohn** [comment]
I agree, I think we should add an annotation to select which one is used

**Comment by guyromb** [comment]
That works be awesome, @howardjohn 🔥

**Comment by jronak** [comment]
@howardjohn I would like to work on this issue.
Could you suggest an annotation name to select istio gateway controller?

**Comment by howardjohn** [comment]
Oh we actually implemented this already in 1.6+, https://github.com/istio/api/pull/1446. Let me know if that meets your needs

**Comment by IbraheemAlSaady** [comment]
@howardjohn, is there a documentation for that somewhere?

**Comment by IbraheemAlSaady** [comment]
@howardjohn I can't seem to find a way to set another gateway controller in the PR you shared
So something like this: `kubernetes.io/ingress.class: istio-internal`, possible?

**Comment by guyromb** [comment]
I implemented this @IbraheemAlSaady : https://github.com/istio/istio/pull/27326
However, not merged yet.

**Comment by IbraheemAlSaady** [comment]
Any updates on this issue?
@guyromb yeah I saw your PR
