### ISSUE TITLE
Incorrect links for Design-Docs in wiki

### ISSUE THREAD

**Issue by mmnelemane** [istio/istio#22420]
**Bug description**
Wiki points to same link for "Simpler Istio, Istiod" and "Istio Authentication rev2 - JWT" point to same document.

**Expected behavior**
"Simpler Istio, Istiod" should point to https://docs.google.com/document/d/1v8BxI07u-mby5f5rCruwF7odSXgb9G8-C9W5hQtSIAg.

**Steps to reproduce the bug**
Open the wiki link (https://github.com/istio/istio/wiki/Design-Doc-Links) and click on "Simpler Istio, Istiod". It opens up the document for JWT authentication

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
Master

**How was Istio installed?**
No installation required

**Environment where bug was observed (cloud vendor, OS, etc)**
Wiki

**Comment by howardjohn** [comment]
thanks! I have fixed this
