### ISSUE TITLE
TestTrafficShifting  flakes

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#22429]
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/22395/integ-pilot-k8s-tests_istio/10239

https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/22414/integ-pilot-k8s-tests_istio/10236

Maybe related to  https://github.com/istio/istio/pull/17169

**Comment by howardjohn** [comment]
Yeah I think its definite #17169 https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/21809/integ-pilot-k8s-tests_istio/10251 and https://prow.istio.io/view/gcs/istio-prow/logs/integ-pilot-k8s-tests_istio_postsubmit/1877 are some more failures. Ill take a look

**Comment by howardjohn** [comment]
My best guess is we are just overloading the test. We are sending 3700 calls and 4 of them fail

**Comment by hzxuzhonghu** [comment]
From the test grid, it seems this is fixed by #22433

**Comment by hzxuzhonghu** [comment]
Found a new failure [TestTrafficShifting ](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/38955/unit-tests_istio/1526377422532907008)
