### ISSUE TITLE
Add a dummy CSR server for local SDS integration test

### ISSUE THREAD

**Issue by JimmyCYJ** [istio/istio#22438]
**Describe the feature request**
With dummy CSR server, we can start Envoy, SDS agent and a dummy CSR server locally, and test corner and negative cases. This is similar as [STS integration test](https://github.com/istio/istio/tree/master/security/pkg/stsservice/test).  

**Describe alternatives you've considered**

**Additional context**

**Comment by incfly** [comment]
remove extra assignee.
