### ISSUE TITLE
Can envoy sidecar for ingress-nginx be upgraded to Istio Gateway?

### ISSUE THREAD

**Issue by kfiles** [istio/istio#22431]
We are developing a multitenant application. Due to the need for supporting multiple IDPs for authentication, we use ingress-nginx with an oauth2_proxy setup. Once a user is authenticated, nginx directs the request to a backend via one of several VirtualService routes. We are using multiple VirtualServices with the same host, as described in https://istio.io/docs/ops/best-practices/traffic-management/#split-virtual-services, to deal with routing to different tenant instances of the backend services.

However, due to the restriction that an Envoy sidecar cannot merge routes from multiple VirtualServices with one destination host, Nginx is unable to directly send traffic to the backend service. Instead, we have to introduce additional Istio Gateways, and direct requests to the gateway, which can then do the proper destination routing.

I am aware that a Gateway is just a special Envoy proxy. Is there any way to setup the Envoy sidecar on the nginx pod to have a gateway configuration, allowing it to merge routes from multiple VirtualServices, in order to avoid our current workaround?

This is the current request flow:
custAUser ---[req https://common-app]--> nginx[login via OIDC] ---> istio-gw ---> virtualservice[match auth hdr] ---> common-app-backend-custA

Desired flow:
custAUser ---[req https://common-app]--> nginx[login via OIDC] ---> virtualservice[match auth hdr] ---> common-app-backend-custA

**Comment by howardjohn** [comment]
You can just run the istio gateway as a container in the nginx pod. The only real benefitthen is that the nginx <-> gateway traffic is over localhost - if that is not a requirement I suggest splitting them out.

**Comment by howardjohn** [comment]
Closing as this has been answered. Thanks! Feel free to ask additional questions on slack or https://discuss.istio.io/
