### ISSUE TITLE
Proxy cannot get SDS push if SDS server is not ready and proxy sends out SDS requests already.

### ISSUE THREAD

**Issue by JimmyCYJ** [istio/istio#22443]
**Bug description**
SDS agent prints a [log](https://github.com/istio/istio/blob/0026a93bc914056c69dd0fa3573651f041a406e1/security/pkg/nodeagent/sds/server.go#L258) when it starts the SDS server, but we need a log indicating when the SDS server is ready. 

If SDS server is not ready, and Envoy sends SDS requests, then no secrets are pushed to Envoy. 
We can reproduce this by adding a delay before starting SDS server [here](https://github.com/istio/istio/blob/0026a93bc914056c69dd0fa3573651f041a406e1/security/pkg/nodeagent/sds/server.go#L265). 

If the [local SDS integration test](https://github.com/istio/istio/issues/22438) is ready, we can add more tests to cover negative cases and corner cases on SDS.

We may need a debug endpoint at SDS server, and make readiness probe to the endpoint before starting Envoy.

**Expected behavior**
Envoy gets key/cert via SDS

**Steps to reproduce the bug**
Add a delay before starting SDS server [here](https://github.com/istio/istio/blob/0026a93bc914056c69dd0fa3573651f041a406e1/security/pkg/nodeagent/sds/server.go#L265), check Envoy log/config and traffic.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.5

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by JimmyCYJ** [comment]
cc @myidpt @howardjohn

**Comment by howardjohn** [comment]
> We may need a debug endpoint at SDS server, and make readiness probe to the endpoint before starting Envoy.

you don't need a debug endpoint or readiness probe, just don't start up envoy. We are in control of everything. Right now our code looks like
```
go startSDS()
go startEnvoy()
```

It should be

```
go startSDS()
ensureSDSReady() // block until ready
go startEnvoy()
```

**Comment by howardjohn** [comment]
Good to know we can easily repro with the delay. is there anyway to have envoy realize no one is listening on the other end and reconnect? This would happen with TCP but not sure if UDS works differrent. That would be more robust, as the SDS server could break at some point I guess?

or we could have both

**Comment by mike1808** [comment]
Nice to see this resolved. We were having weird 503 and noticed that secrets in the sidecars are not initialized.

**Comment by howardjohn** [comment]
This is not resolved. @JimmyCYJ is there any update on this?

**Comment by JimmyCYJ** [comment]
I don't have any update on this, not clear how to reproduce it. @myidpt

**Comment by mike1808** [comment]
I could not reproduce this either. It only happened when I've created ~2000 deployments/service/virtual service/gateways and from time to time 4-5 pods have this issue.

**Comment by JimmyCYJ** [comment]
Originally I tried adding a sleep to delay the start of SDS server, during the sleep, Envoy is waiting for SDS push, and no error is seen. This is similar to the issue found in the perf test. But after the sleep, SDS server starts and accepts the SDS request, and the Envoy receives the SDS push after that. I couldn't reproduce it with local SDS integration test and in a real GKE cluster.

**Comment by mike1808** [comment]
@JimmyCYJ I'll try to deploy the same pods I have before to see if I can reproduce it.

**Comment by howardjohn** [comment]
Can detect with `count(envoy_cluster_client_ssl_socket_factory_ssl_context_update_by_sds{cluster_name!="xds-grpc"} == 0) by (pod)`

**Comment by howardjohn** [comment]
config:debug logs for a broken pod:
[broken-debug-config.log](https://github.com/istio/istio/files/4513050/broken-debug-config.log)

Notably missing:

```
[Envoy (Epoch 0)] [2020-04-21 23:34:44.053][29][debug][config] [external/envoy/source/common/config/grpc_mux_impl.cc:82] gRPC mux subscribe for type.googleapis.com/envoy.api.v2.auth.Secret
[Envoy (Epoch 0)] [2020-04-21 23:34:44.053][29][debug][config] [external/envoy/source/common/config/grpc_mux_impl.cc:39] No stream available to sendDiscoveryRequest for type.googleapis.com/envoy.api.v2.auth.Secret
[Envoy (Epoch 0)] [2020-04-21 23:34:44.053][29][debug][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:47] Establishing new gRPC bidi stream for rpc StreamSecrets(stream .envoy.api.v2.DiscoveryRequest) returns (stream .envoy.api.v2.DiscoveryResponse);
```

**Comment by howardjohn** [comment]
`listener_manager.lds.init_fetch_timeout: 0` - I am pretty sure this is a bug..
It should either block listener warming, or triggered initial fetch timeout?

**Comment by howardjohn** [comment]
Got full debug logs. Notable difference:

GOOD:
[full-logs.log](https://github.com/istio/istio/files/4513103/full-logs.log)

```
[Envoy (Epoch 0)] [2020-04-22 00:00:35.347][29][debug][init] [external/envoy/source/common/init/manager_impl.cc:20] added target SdsApi default to init manager Cluster outbound|15010||istio-pilot.istio-system.svc.cluster.local
[Envoy (Epoch 0)] [2020-04-22 00:00:35.347][29][debug][init] [external/envoy/source/common/init/manager_impl.cc:20] added target SdsApi ROOTCA to init manager Cluster outbound|15010||istio-pilot.istio-system.svc.cluster.local
[Envoy (Epoch 0)] [2020-04-22 00:00:35.402][29][debug][init] [external/envoy/source/common/init/target_impl.cc:15] init manager Cluster outbound|15010||istio-pilot.istio-system.svc.cluster.local initializing target SdsApi default
[Envoy (Epoch 0)] [2020-04-22 00:00:35.403][29][debug][init] [external/envoy/source/common/init/target_impl.cc:15] init manager Cluster outbound|15010||istio-pilot.istio-system.svc.cluster.local initializing target SdsApi ROOTCA
[Envoy (Epoch 0)] [2020-04-22 00:00:36.017][29][debug][init] [external/envoy/source/common/init/watcher_impl.cc:14] target SdsApi default initialized, notifying init manager Cluster outbound|15010||istio-pilot.istio-system.svc.cluster.local
[Envoy (Epoch 0)] [2020-04-22 00:00:36.239][29][debug][init] [external/envoy/source/common/init/watcher_impl.cc:14] target SdsApi ROOTCA initialized, notifying init manager Cluster outbound|15010||istio-pilot.istio-system.svc.cluster.local
```
BAD:
```
[Envoy (Epoch 0)] [2020-04-22 00:00:34.032][26][debug][init] [external/envoy/source/common/init/manager_impl.cc:20] added target SdsApi default to init manager Cluster outbound|53||kube-dns.kube-system.svc.cluster.local
[Envoy (Epoch 0)] [2020-04-22 00:00:34.032][26][debug][init] [external/envoy/source/common/init/manager_impl.cc:20] added target SdsApi ROOTCA to init manager Cluster outbound|53||kube-dns.kube-system.svc.cluster.local

**Comment by howardjohn** [comment]
The kube-dns vs istio-pilot cluster name is not relevant to ^, I have verified it varies on good pods as well

**Comment by howardjohn** [comment]
Here is a new one.. the `default` secret is fetched but ROOTCA is not:

```
2020-04-22T14:37:09.858051Z     info    sds     resource:default new connection
2020-04-22T14:37:10.581549Z     info    cache   Root cert has changed, start rotating root cert for SDS clients
2020-04-22T14:37:10.581611Z     info    cache   GenerateSecret default
2020-04-22T14:37:10.581770Z     info    sds     resource:default pushed key/cert pair to proxy
```

Running `1.6-alpha.81322fa1cba9fe98047bfcc275b0adeb82465fdd`

**Comment by pixystone** [comment]
how to workaround this? I met this 503 `TLS error: Secret is not supplied by SDS`

```
$istioctl pc s istio-ingressgateway-768db54bdb-v6598.istio-system
RESOURCE NAME       TYPE           STATUS      VALID CERT     SERIAL NUMBER                     NOT AFTER                NOT BEFORE
default                            WARMING     false
ROOTCA                             WARMING     false
https-certs-pre     Cert Chain     ACTIVE      true           34544361368060865268342148204     2020-12-26T12:11:01Z     2019-12-26T12:11:01Z
```

**Comment by pixystone** [comment]
I disabled the `auto mTLS` to workaround it.

```
values:
  global:
    mtls:
      enabled: false
      auto: false
```

**Comment by howardjohn** [comment]
on some versions just the ROOTCA is broken:

```
$ cat /tmp/root-missing | rg -i Secret
[Envoy (Epoch 0)] [2020-04-23 22:36:43.287][23][info][config] [external/envoy/source/server/configuration_impl.cc:62] loading 0 static secret(s)
[Envoy (Epoch 0)] [2020-04-23 22:36:43.323][23][debug][config] [external/envoy/source/common/config/grpc_mux_impl.cc:83] gRPC mux addWatch for type.googleapis.com/envoy.api.v2.auth.Secret
[Envoy (Epoch 0)] [2020-04-23 22:36:43.323][23][debug][config] [external/envoy/source/common/config/grpc_mux_impl.cc:40] No stream available to sendDiscoveryRequest for type.googleapis.com/envoy.api.v2.auth.Secret
[Envoy (Epoch 0)] [2020-04-23 22:36:43.323][23][debug][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:47] Establishing new gRPC bidi stream for rpc StreamSecrets(stream .envoy.api.v2.DiscoveryRequest) returns (stream .envoy.api.v2.DiscoveryResponse);
2020-04-23T22:36:43.514833Z     info    cache   GenerateSecret default
[Envoy (Epoch 0)] [2020-04-23 22:36:43.515][23][debug][config] [external/envoy/source/common/config/grpc_mux_impl.cc:137] Received gRPC message for type.googleapis.com/envoy.api.v2.auth.Secret at version 04-23 22:36:43.325
[Envoy (Epoch 0)] [2020-04-23 22:36:43.515][23][debug][config] [external/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc:631] Secret is updated.
[Envoy (Epoch 0)] [2020-04-23 22:36:43.518][23][debug][config] [external/envoy/source/common/config/grpc_subscription_impl.cc:67] gRPC config for type.googleapis.com/envoy.api.v2.auth.Secret accepted with 1 resources with version 04-23 22:36:43.325
```

full log: 
[root-missing.txt](https://github.com/istio/istio/files/4525677/root-missing.txt)

**Comment by howardjohn** [comment]
ae0ceeb13e0675f889dd7230b7659b5b149f0943 was the commit that fixed it. This update envoy and go-control plane.

Envoy diff:

```
* ca756fab "Nupur Garg" <37600866+gargnupur@users.noreply.github.com> 6 weeks ago
| Fix seg fault in mixer tcp after upgrading envoy-wasm sha (#2766)
* c0b5350d "Nupur Garg" <37600866+gargnupur@users.noreply.github.com> 6 weeks ago
| Add check for gRPC status in access log filter (#2685)
* cf701d93 "Nupur Garg" <37600866+gargnupur@users.noreply.github.com> 6 weeks ago
| Use  onLog  for TCP stats login (#2763)
* 57d429d4 "Nupur Garg" <37600866+gargnupur@users.noreply.github.com> 6 weeks ago
| Update Envoy-WASM SHA (#2762)
* f2f929ca "Travis Clarke" <clarketm@users.noreply.github.com> 6 weeks ago
| Add dummy "gen" target (#2759)
* 4b573fea "Pengyuan Bian" <bianpengyuan@google.com> 6 weeks ago
| add log entry fetch endpoint (#2757)
* b64bca9a "Istio Automation" <istio.testing@gmail.com> 7 weeks ago
| Automator: update common-files@master in istio/proxy@master (#2754)
* d51dfc0b "Travis Clarke" <clarketm@users.noreply.github.com> 7 weeks ago
| override image name (IMAGE_NAME) only (#2755)
* b336aab3 "Nupur Garg" <37600866+gargnupur@users.noreply.github.com> 7 weeks ago
| Add a test for TCP metrics for a long running TCP connection (#2753)
* e4984606 "Istio Automation" <istio.testing@gmail.com> 7 weeks ago
  add a fake stackdriver image for testing (#2606)
```

contains a couple envoy-wasm updates. Envoy-wasm diff: https://github.com/envoyproxy/envoy-wasm/compare/e64efd960cd8e97287764b9bae39b3a0def95046..e067c80e5cc43bd462aac6e69713913f1ad4c48d

**Comment by howardjohn** [comment]
Confirmed its the envoy update, no go control plane. So the fix is somewhere in the diff ^

**Comment by howardjohn** [comment]
134c006dcfc37452d9a8ae3818732f32e47a0ef1 was the commit that transitioned from both broken to just ROOTCA broken

**Comment by howardjohn** [comment]
Full bisect log:

```
bba7404c0d9f32bce93564967808044fde72d5a GOOD
d131b957a GOOD
ae0ceeb13e0675f889dd7230b7659b5b149f0943 good <--- fix
35642ef40 ROOTCA broken
81322fa1c ROOTCA broken
7197e6528be472987c996bac0c195e2be5a4ce08 ROOTCA broken
76f26ef5990a43c4ffccd80f3b74ceacbdda0613 ROOTCA broken
af19dc7e07dd3f0ff7d28404a69348f72a115126 ROOTCA broken
134c006dcfc37452d9a8ae3818732f32e47a0ef1  ROOTCA broken <--- partial fix
070fd343c7d161f7faa84af2a6fe685ee0322808 BOTH broken
1bbd08344888630cfcd86d1406b7a4e8112ad5c6 BOTH broken
69e5e8aa3e9a12e0edcb6d22024831ce845a3f31 BOTH broken
428b9095d0e6540c18bcb79f4dfa968b5f972d23 BOTH broken
```

Interesting, 134c006 is in 1.5. need to check if 1.5 is just rootca broken?

**Comment by howardjohn** [comment]
On 1.5.2 both are missing, yet it has the same 134c006dcfc37452d9a8ae3818732f32e47a0ef1... I am confused

**Comment by howardjohn** [comment]
1.5.2 + envoy from 1.6 is broken: gcr.io/howardjohn-istio/proxyv2:mismatch
1.6 + envoy from 1.5 is working: gcr.io/howardjohn-istio/proxyv2:mismatch-16-agent

conclusion: its purely on pilot-agent that we have broken this

**Comment by howardjohn** [comment]
I have run into the ROOTCA stuck warming error on master (gcr.io/istio-testing/proxyv2:1.6-alpha.b335aa12125dce539a60f1f52d59f3c896b9e9f1)

**Comment by incfly** [comment]
> I disabled auto mTLS to workaround.

Oh now I remembered that I have added a check in the pilot agent to ensure the secret are mounted before we start the envoy, when developing auto mTLS.

**Comment by howardjohn** [comment]
Update: if automtls is disabled, or we don't have ISTIO_MUTUAL destination rule, then this bug will not occur. Basically anything that gets secrets in clusters will cause this to occur.

In the process I found https://github.com/envoyproxy/envoy/issues/11120. It may be linked to the root cause

**Comment by howardjohn** [comment]
it seems the difference between 1.5 and 1.6 is that the client cert is sent in 1.6, but not 1.5. This linearizes the startup to enforce SDS is completed before XDS, which probably avoids some race condition inside envoy. I **think** its still possible to have the root cert still missing since we don't request it in the xds-grpc cluster, but probably much much more rare

**Comment by howardjohn** [comment]
This is mitigated now, droppign priority. This issue is now about tracking the root cause to get a proper fix

**Comment by myidpt** [comment]
Thanks John, we also need to change the istiod client auth strategy to make sure https://github.com/istio/istio/pull/23666 doesn't break the custom CA. Let me know if you want me to handle that.

**Comment by jullianoacqio** [comment]
I face this problem today.
I have two certificates generated by the cert-manager. istio-ingressgateway-certs, devops-ingressgateway-certs.
One of them the SDS is unable to load. Even forcing the service to restart, it is not possible to load the certificate.
This is the error I get:
```
2020-06-01T01:08:34.752053Z     info    ControlZ available at 127.0.0.1:9876
2020-06-01T01:08:34.787721Z     warn    secretfetcher   failed load server cert/key pair from secret datahub-gateway-privatekey: server cert or private key is empty
2020-06-01T01:08:34.787739Z     warn    secretfetcher   failed load server cert/key pair from secret dockercfg: server cert or private key is empty
2020-06-01T01:08:34.787743Z     warn    secretfetcher   failed load server cert/key pair from secret azuredns-config3333: server cert or private key is empty
2020-06-01T01:08:34.787752Z     warn    secretfetcher   failed load server cert/key pair from secret azuredns-config: server cert or private key is empty
2020-06-01T01:08:34.787759Z     warn    secretfetcher   failed load server cert/key pair from secret devops-ingressgateway-certs: server cert or private key is empty
2020-06-01T01:08:34.787768Z     warn    secretfetcher   failed load server cert/key pair from secret kiali: server cert or private key is empty
2020-06-01T01:08:34.787773Z     warn    secretfetcher   failed load server cert/key pair from secret devops-gateway-privatekey: server cert or private key is empty
2020-06-01T01:08:34.787788Z     warn    secretfetcher   failed load server cert/key pair from secret grafana: server cert or private key is empty
2020-06-01T01:08:34.853672Z     info    sds     SDS gRPC server for ingress gateway controller starts, listening on "/var/run/ingress_gateway/sds"

2020-06-01T01:08:34.853719Z     info    sds     Start SDS grpc server for ingress gateway proxy
2020-06-01T01:08:34.853800Z     info    citadel agent monitor has started.
2020-06-01T01:08:34.853905Z     info    monitor Monitor server started.
2020-06-01T01:08:37.776466Z     info    sds     node:router~10.23.1.12~istio-ingressgateway-59fb44d469-tx4b9.istio-system~istio-system.svc.cluster.local-1 resource:istio-ingressgateway-certs new connection
2020-06-01T01:08:37.780422Z     info    secretfetcher   Return secret istio-ingressgateway-certs found by direct api call
2020-06-01T01:08:37.785511Z     info    secretfetcher   Return secret istio-ingressgateway-certs found by direct api call
2020-06-01T01:08:37.785636Z     info    sds     node:router~10.23.1.12~istio-ingressgateway-59fb44d469-tx4b9.istio-system~istio-system.svc.cluster.local-1 resource:istio-ingressgateway-certs pushed key/cert pair to proxy
2020-06-01T01:08:37.785645Z     info    sds     node:router~10.23.1.12~istio-ingressgateway-59fb44d469-tx4b9.istio-system~istio-system.svc.cluster.local-1 resource:istio-ingressgateway-certs pushed secret
```
the devops-ingressgateray-certs certificate is mounted as secret and with the same structure as the istio-ingressgateway-certs.
I'm on version 1.5.4.

**Comment by lambdai** [comment]
`If SDS server is not ready, and Envoy sends SDS requests, then no secrets are pushed to Envoy.`

@JimmyCYJ Could you clarify? 
The expected scenario is, 
1. if the connection broken, xDS client should resend new request containing all required resources upon new connection;
2. If the connection is not broken but take long time to handshake: no single byte should be lost. Also it's not harmful to resend all requested resources at xds client.

**Comment by howardjohn** [comment]
> If SDS server is not ready, and Envoy sends SDS requests, then no secrets are pushed to Envoy.

This was proven to be incorrect as far as I know. We were unable to come up with a consistent reproducer. All we know for sure is that it happens ~0.1% of the time if the XDS cluster uses no certs, and it never happens if the cert is part of the XDS cluster

**Comment by lambdai** [comment]
Could you explain a little bit on the "certs of XDS cluster"? 
I think you are referring to https://github.com/istio/istio/pull/23666

I am wondering why would XDS connection survives in the 99.9%...

**Comment by howardjohn** [comment]
Yeah I mean that one. Basically my thought is that PR forced the SDS exchange to happen prior to any of the dynamic resources are fetched which somehow fixes things. Not sure if it's due to timing or static vs dynamic

**Comment by howardjohn** [comment]
@JimmyCYJ can we please invest some effort into fixing this in Envoy?

**Comment by tmshort** [comment]
We are running into this problem, seeing the "Secret is not supplied by SDS" for internal pods (i.e. not via the istio-gateway"). It seems that certificates are in the warming state:
```
istioctl pc secret pod-name-7c54fdfbcd-zxz95 -n pod-namespace
RESOURCE NAME     TYPE           STATUS      VALID CERT     SERIAL NUMBER                                        NOT AFTER                NOT BEFORE
default                          WARMING     false
ROOTCA                           WARMING     false
default           Cert Chain     ACTIVE      true           234171313849726017837196982763212874896295663136     2020-08-06T15:04:35Z     2020-07-30T15:04:05Z
ROOTCA            CA             ACTIVE      true           180845663255518971428985928369200633201796419410     2039-08-02T18:25:58Z     2019-08-02T18:25:58Z

**Comment by pbohman** [comment]
Hi, we're seeing the same sporadic 503 / "Secret is not supplied by SDS" messages with 1.5.7. Does the istioctl output below indicate that these 503s are related to this issue?
```
istioctl pc secret ...
RESOURCE NAME     TYPE           STATUS      VALID CERT     SERIAL NUMBER                                        NOT AFTER                NOT BEFORE
default                          WARMING     false
ROOTCA                           WARMING     false
default           Cert Chain     ACTIVE      true           234171313849726017837196982763212874896295663136     2020-08-06T15:04:35Z     2020-07-30T15:04:05Z
ROOTCA            CA             ACTIVE      true           180845663255518971428985928369200633201796419410     2039-08-02T18:25:58Z     2019-08-02T18:25:58Z
```

**Comment by tmshort** [comment]
We are running into this problem, seeing the "Secret is not supplied by SDS" causing 503 for internal communications via istio-enabled pods (i.e. not via the istio-gateway). It seems that certificates are in the warming state:
```
istioctl pc secret pod-name-7c54fdfbcd-zxz95 -n pod-namespace
RESOURCE NAME     TYPE           STATUS      VALID CERT     SERIAL NUMBER                                        NOT AFTER                NOT BEFORE
default                          WARMING     false
ROOTCA                           WARMING     false
default           Cert Chain     ACTIVE      true           234171313849726017837196982763212874896295663136     2020-08-06T15:04:35Z     2020-07-30T15:04:05Z
ROOTCA            CA             ACTIVE      true           180845663255518971428985928369200633201796419410

**Comment by tmshort** [comment]
> @JimmyCYJ can we please invest some effort into fixing this in Envoy?

Do we believe this is an envoy or istio issue?

**Comment by howardjohn** [comment]
@tmshort there is definitely an envoy bug involved, see https://github.com/envoyproxy/envoy/issues/11120. Whether fixing that is sufficient to fully resolve this, not sure. I hope/suspect so, but can't be certain.

**Comment by tmshort** [comment]
@howardjohn wrote:
>This is mitigated now, droppign priority. This issue is now about tracking the root cause to get a proper fix

What's the mitigation on the istio side? We need ISTIO_MUTUAL, so we can't really remove that.

**Comment by howardjohn** [comment]
@tmshort we request the certs as part of the bootstrap which seems to unblock it. If you still have issues its likely another bug?

**Comment by tmshort** [comment]
@howardjohn What commit/change enabled that? What version?

**Comment by howardjohn** [comment]
https://github.com/istio/istio/pull/23666

**Comment by tmshort** [comment]
Thanks @howardjohn. We have that already in 1.5.7, but are still experiencing this issue.

**Comment by williamaronli** [comment]
From howard. This mitigated in 1.6/1.7 using mTLS for XDS. It serializes the init flow, so that SDS is requested first. And the mitigation does not work in 1.8 as we are using  local UDS path

**Comment by williamaronli** [comment]
we need to wait for the https://github.com/envoyproxy/envoy/pull/13344 which fixes the envoy side issue

**Comment by williamaronli** [comment]
@linzhaoming could you also take a look at this https://github.com/envoyproxy/envoy/pull/13344 ? Thanks

**Comment by howardjohn** [comment]
we need to backport https://github.com/envoyproxy/envoy/pull/13344, and Ithink now requires runtime flag to enable

**Comment by howardjohn** [comment]
The backport PR, https://github.com/istio/envoy/pull/281, causes another bug which is more frequent: https://github.com/envoyproxy/envoy/issues/13874. @lambdai is looking into it

**Comment by howardjohn** [comment]
This is presumed fixed in 1.8 unless we hit it again

**Comment by lambdai** [comment]
Just for tracking if people see similar failure prior to 1.8. Another related fix is https://github.com/envoyproxy/envoy/pull/13997

**Comment by arief-hidayat** [comment]
with istio 1.7.3, our knative activator had this issue few months ago `upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: TLS error: Secret is not supplied by SDS`.

based on discussion here, we upgraded to 1.8.2. Disabling mTLS is not an option for us. 

However, this issue happens again in one of our prod clusters.

any specific istio version that have the complete fix?  @howardjohn . 
Perhaps the above envoy envoyproxy/envoy#13997 is only available in newer version? @lambdai

**Comment by winterTTr** [comment]
Same here, we are using 1.8.2, and we see this issue as well.

**Comment by emike922** [comment]
At a quick glance I was only able to find envoyproxy/envoy#13997 in the 1.9 and 1.10 releases, refer https://github.com/istio/envoy/commit/e9d85da91fcc504265b0cded8b4df101bc35603c
