### ISSUE TITLE
Provide istioctl install command

### ISSUE THREAD

**Issue by linsun** [istio/istio#22441]
**Describe the feature request**
Our install is un-intuitive to use without following docs.  I tweeted about this, and discussed on UX WG today too and it resonates with folks.

https://twitter.com/linsun_unc/status/1242272013814808581?s=20

Similar comments for uninstall were expressed at the UX WG mtg today as well.
If we could provide an alias `istioctl install` cmd to `istioctl manifest apply`, that would be helpful.

**Describe alternatives you've considered**
follow the doc each time

[ ] Configuration Infrastructure
[ ] Docs
[ x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by linsun** [comment]
cc @esnible @ayj @sdake @ostromart @nrjpoddar

**Comment by howardjohn** [comment]
:+1: for me, I think it makes more sense

**Comment by ayj** [comment]
Would we also document `istioctl install` as the standard method for installation, reconfiguration, and upgrades?

**Comment by ostromart** [comment]
Fixed in https://github.com/istio/istio/pull/22563.
