### ISSUE TITLE
Investigate perf_dashboard migration issue

### ISSUE THREAD

**Issue by carolynhu** [istio/istio#22454]
It seems that the latest tools repo's commit did not take effect on http://perf.dashboard.istio.io/ after our migration from http://perf.dashboard.qualistio.org/. We need to investigate the issue and give a fix.

**Comment by clarketm** [comment]
The issue appears to be a stale GCE health check (see: https://github.com/kubernetes/ingress-gce/issues/241) binded to the ingress. As mitigation until the fix can be verified http://perf.dashboard.istio.io/ traffic is being routed to the previous cluster this was deployed on.

**Comment by clarketm** [comment]
Recreating the ingress solved the problem. The cluster has been consistently healthy for 24+ hours. We should let it bake a bit more to be certain.

**Comment by clarketm** [comment]
This has been stable for 48+ hours. Going to switch back DNS to production cluster.
