### ISSUE TITLE
Incoming mTLS traffic termination with non-trusted CA signed certificates

### ISSUE THREAD

**Issue by Eneminemoe** [istio/istio#22469]
**Describe the feature request**
As my understanding it is only possible to use mTls for incoming traffic at istio gateway with certs signed by a trusted CA. I want to be able to use mTls with the client certificate not required to be signed by a trusted CA certificate and tls still be terminating. Reason is that I read the certs values and push them in a custom header.

This would go along with [nginx's ssl_verifiy_client optional_no_ca](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_verify_client) feature.

Am I totally missunderstanding conceptual thoughts of nginx's optional_no_ca?

**Describe alternatives you've considered**
- none

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**
sni passthrough is no option

**Comment by JimmyCYJ** [comment]
Do you need the ingress gateway to terminate the TLS connection, and forward the client cert as a header to your backend service?

**Comment by incfly** [comment]
It's not clear to me what case that "allowing client present a certificate to gateway, but it's okay to not be signed by a trusted CA" happen. The purpose of mTLS isn't it to provide a trusted client identity/attributes as part of the certificate?

Does `SIMPLE` mode in Gateway TLS work for your or not?

**Comment by Eneminemoe** [comment]
@JimmyCYJ 
That's what  I am (almost) trying to do. I'd like to enforce the client to send a cert and take some values from it an parse it into a custom header. The reason why I want it to terminate with a not trusted cert is for testing purposes. In production  certs will be signed by a CA, but in my testenvironment they aren't. I see nginx is able to terminate mTls correctly with not trusted certs as seen here [nginx's ssl_verifiy_client optional_no_ca](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_verify_client).

**Comment by Eneminemoe** [comment]
@incfly no, TKS mode simple does not work as I want the client to send a cert. Or am I missunderstanding some conecptional thoughts of tls/mtls. As I understand by using tls you tell the server to authenticate itself to the client only and mTls forces the client to authenticate back. Am I wrong?

**Comment by Eneminemoe** [comment]
Envoy recently added this feature. Updating to istio 1.5+ should do the trick.
See the [envoy github](https://github.com/envoyproxy/envoy/pull/9172) for further information.

**Comment by Eneminemoe** [comment]
Is there someone who could give an example of how to write an envoy filter to apply this setting? I cant get it work. :/

**Comment by Eneminemoe** [comment]
@incfly @JimmyCYJ do you know how to config an envoy filter? I'm still clueless. :/
