### ISSUE TITLE
Allow overlays of keys in configmaps

### ISSUE THREAD

**Issue by ostromart** [istio/istio#22473]
k8s considers configmap values to be text, even if those are (typically) YAML. As such, the entire YAML block is considered as one large block of text, which means that individual sub-paths can't be overlaid. 
This feature request is to add special handling for configmaps in k8s.overlays so that the yaml is merged rather than replaced. This is especially useful for large configmaps which currently require huge blocks of text to be overlaid.

**Comment by Pawan-Bishnoi** [comment]
Is this supported? This will be really useful to customise sidecar injector config etc which lives in configmaps.

**Comment by Pawan-Bishnoi** [comment]
@ostromart did you find a way to do this? I see this issue was auto-closed
