### ISSUE TITLE
Galley panic on analysis

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#22478]
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/22467/integ-galley-k8s-tests_istio/10301

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gcs/istio-prow/logs/integ-k8s-117_istio_postsubmit/289

**Comment by howardjohn** [comment]
highly related to https://github.com/istio/istio/issues/22480, probably root cause is deleted CRD

**Comment by esnible** [comment]
@therealmitchconnors I am making this a P1.  Please set a milestone.

**Comment by esnible** [comment]
@howardjohn May I close this?

**Comment by esnible** [comment]
@therealmitchconnors Are you working on this?

**Comment by howardjohn** [comment]
I think this will be obsolete once we move to Istiod code, unless we want
to fix for older versions
