### ISSUE TITLE
Using deprecated extensions/v1beta1 Ingress in k8s 1.18

### ISSUE THREAD

**Issue by rittneje** [istio/istio#22475]
The k8s 1.14 release notes say:

> Ingress resources are now available via networking.k8s.io/v1beta1. Ingress resources in extensions/v1beta1 are deprecated and will no longer be served in v1.18.

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.14.md

However, the deprecated version is still used in a few places, such as: https://github.com/istio/istio/blob/9d07e185b0dd50e6fb1418caa4b4d879788807e3/install/kubernetes/helm/istio/charts/kiali/templates/ingress.yaml#L2-L3

**Comment by howardjohn** [comment]
This is only true for manifests/istio-telemetry/prometheus/templates/ingress.yaml now. Thanks for pointing this out. All other usages have been fixed on master - Istio 1.6 will be the first version to support k8s 1.18.

I believe that not is incorrect anyhow, extensions/v1beta1 is still around in 1.18
