### ISSUE TITLE
Release notes links are broken

### ISSUE THREAD

**Issue by rittneje** [istio/istio#22474]
All of the release notes linked on the GitHub releases page are broken. https://github.com/istio/istio/releases

For example, it links to https://istio.io/news/announcing-1.4.6/ instead of https://istio.io/news/releases/1.4.x/announcing-1.4.6/

**Comment by howardjohn** [comment]
These work for me, there was a small period of time when 1.4.7 and 1.5.1 were broken as the website was updated. Can you confirm it works now?

**Comment by rittneje** [comment]
Yes, they are working now. I guess the redirect was broken.
