### ISSUE TITLE
Galley watcher panic

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#22480]
https://prow.istio.io/view/gcs/istio-prow/logs/integ-galley-k8s-tests_istio_postsubmit/1899

Tentatively assigning to @ayj since I don't know who else works in this area anymore

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/22481/integ-galley-k8s-tests_istio/10315

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gcs/istio-prow/logs/integ-k8s-115_istio_postsubmit/1150
https://prow.istio.io/view/gcs/istio-prow/logs/integ-k8s-116_istio_postsubmit/1799

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gcs/istio-prow/logs/integ-galley-k8s-tests_istio_postsubmit/1906
https://prow.istio.io/view/gcs/istio-prow/logs/integ-k8s-114_istio_postsubmit/1938

Seems like a major regression, bumping to "release blocker"

**Comment by howardjohn** [comment]
I think its because we are deleting CRDs now as of #22336. I'll fix that, but Galley probably shouldn't panic regardless

**Comment by ayj** [comment]
Thanks John. Can we keep this issue open to track the fix in Galley itself?

**Comment by howardjohn** [comment]
Yeah, I think that makes sense
