### ISSUE TITLE
upstream connect error or disconnect/reset before headers. reset reason: connection failure

### ISSUE THREAD

**Issue by andrijaperovic** [istio/istio#22482]
**Bug description**

We are seeing a upstream connect error with a 503 on istio-envoy when trying to access a context path on a Jetty/JDK 11 based service running inside our GKE On-Prem Kubernetes cluster: 
Previously SSL connections were working fine when running on both Tomcat JDK 9 and Jetty JDK 9 based container images (and were being terminated at the proxy level). 

We are seeing the following error in the istio-proxy sidecar logs on the service: 
```
{
  "original_message": "[Envoy (Epoch 0)] [2020-03-25 03:50:01.631][19][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:91] gRPC config stream closed: 13, "
}
```

We also have a istio-ingressgateway-external defined on our istio-system namespace and are using the Big-IP kubernetes controller to map all of the services to our Virtual F5 Loadbalancer. We see the following when enabling tracing on the istio-ingressgateway-external pod: 

```
[Envoy (Epoch 0)] [2020-03-25 19:23:10.048][27][debug][pool] [external/envoy/source/common/http/http1/conn_pool.cc:136] [C990786] client disconnected, failure reason: TLS error: 268435703:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER
[Envoy (Epoch 0)] [2020-03-25 19:23:10.048][27][debug][pool] [external/envoy/source/common/http/http1/conn_pool.cc:167] [C990786] purge pending, failure reason: TLS error: 268435703:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER
```

Response headers: 

```
content-length: 91
content-type: text/plain
date: Wed, 25 Mar 2020 21:02:40 GMT
server: istio-envoy
status: 503
```

Body:
```
upstream connect error or disconnect/reset before headers. reset reason: connection failure
```

**Expected behavior**

HTTP 200 response. 

**Steps to reproduce the bug**

Create a Gateway and VirtualService with a rule to route traffic based on context path to a Jetty Based Spring Boot Application running on JDK 11 (Kubernetes service and deployment). Create a corresponding Destination Rule of ISTIO_MUTUAL (mTLS). Create the following network policy at the namespace level: 

```
- apiVersion: authentication.istio.io/v1alpha1
  kind: Policy
  metadata:
    annotations:
      generation: 1
      name: mtls
      namespace: application-namespace
  spec:
    peers:
    - mtls: {}
    targets:
    - name: jetty-services
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

istioctl version --remote
client version: 1.4.6-asm.0
control plane version: 1.4.6-asm.0
data plane version: 1.4.6-asm.0 (22 proxies), 1.3.3 (3 proxies)

kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.8", GitCommit:"a89f8c11a5f4f132503edbc4918c98518fd504e3", GitTreeState:"clean", BuildDate:"2019-04-23T04:52:31Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.7-gke.24", GitCommit:"a9c61ae0b1b75106e960849079e243e8a054b580", GitTreeState:"clean", BuildDate:"2019-11-15T22:28:40Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}

Using jetty 9.4.19.v20190610 and OpenJDK 11 OpenJ9 based base image (adoptopenjdk/openjdk11-openj9:x86_64-alpine-jdk-11.0.6_10_openj9-0.18.1-slim). 

**How was Istio installed?**

Istio 1.4.6-asm.0 was installed using istioctl manifest. 

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE On-Prem running on VMWare/vCenter, k8s nodes running Ubuntu 18.04.3 LTS

**Comment by lambdai** [comment]
Sorry I accidentally linked my PR to this issue

**Comment by lambdai** [comment]
It doesn't make sense to me a sidecar proxy connect to another sidecar proxy would report error as `TLS error: 268435703:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER`
I see you have 1.3.3 proxies, is it possible that the errors occurs while a 1.4.6 sidecar or ingressgateway connecting to a 1.3.3 sidecar?

**Comment by howardjohn** [comment]
@andrijaperovic are you still experiencing this? See comment above

**Comment by thiagoleitetr** [comment]
Hi all !

I have the same error in springboot after I change meshconfig.enableAutoMtls: true. 
istio 1.6.5
k8s 1.18.6

**Comment by j0gsDev** [comment]
Use [Java Distroless](https://github.com/GoogleContainerTools/distroless/tree/master/java) as docker image base

**Comment by victorsens** [comment]
> Hi all !
> 
> I have the same error in springboot after I change meshconfig.enableAutoMtls: true.
> istio 1.6.5
> k8s 1.18.6

I'm having the same problem... using GCP - GKE... SpringBoot and java 11... Could you solve your problem?

**Comment by victorsens** [comment]
> Use [Java Distroless](https://github.com/GoogleContainerTools/distroless/tree/master/java) as docker image base

I did it, but I still with the same problem. Do you have more tips for me?

**Comment by howardjohn** [comment]
I think this was resolved outside of this issue - can you confirm @andrijaperovic ? And possibly indicate what the issue was if you remember.

**Comment by andrijaperovic** [comment]
@howardjohn since publishing this ticket we have decided to go with embedded tomcat on spring boot, currently don't have bandwidth to try it out on jetty again - however, I do believe this may have been a duplicate header issue which we fixed by removing `"Transfer-Encoding", "chunked"` from response headers in our servlet Filter implementation. 
Will go ahead and close this for now, and re-open if we observe the same issue at a point in time we uptake Jetty.

**Comment by omerfsen** [comment]
It maybe related with https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/#automatic-protocol-selection 

so either on your Service definiton use port.name like http-XXX or https-yyyy  or if you can't do that disable pilot outbound sniffing..

```
--set values.pilot.enableProtocolSniffingForOutbound=false
```
on your IstioOperator yaml file (or set it via istioctl --set values.pilot.enableProtocolSniffingForOutbound=false .... )
