### ISSUE TITLE
getting failed while installation through generated menifest

### ISSUE THREAD

**Issue by pawanyoda** [istio/istio#22493]
**Bug description**
I am experiencing an issue on istio installation through generated manifest.
It automatically stopped after few installations and shows `Error from server (NotFound): error when creating "generated_default_proile_manifest_1_5_1.yaml": namespaces "istio-system" not found`
after that, I have run it again and the problem is not coming on direct installation.

[X] Configuration Infrastructure
[X] Docs
[X] Installation
[ X] Networking
[ X] Performance and Scalability
[ X] Policies and Telemetry
[ X] Security
[ X] Test and Release
[ X] User Experience
[X ] Developer Infrastructure

**Expected behavior**
```
serviceaccount/istio-mixer-service-account created
Error from server (NotFound): error when creating "generated_default_proile_manifest_1_5_1.yaml": namespaces "istio-system" not found
Error from server (NotFound): error when creating "generated_default_proile_manifest_1_5_1.yaml": namespaces "istio-system" not found
[unable to recognize "generated_default_proile_manifest_1_5_1.yaml": no matches for kind "Policy" in version "authentication.istio.io/v1alpha1", unable to recognize "generated_default_proile_manifest_1_5_1.yaml": no matches for kind "Gateway" in version "networking.istio.io/v1alpha3", unable to recognize "generated_default_proile_manifest_1_5_1.yaml": no matches for kind "Sidecar" in version "networking.istio.io/v1alpha3", unable to recognize "generated_default_proile_manifest_1_5_1.yaml": no matches for kind "EnvoyFilter" in version "networking.istio.io/v1alpha3", unable to recognize "generated_default_proile_manifest_1_5_1.yaml": no matches for kind "attributemanifest" in version "config.istio.io/v1alpha2", unable to recognize "generated_default_proile_manifest_1_5_1.yaml": no matches for kind "instance" in version "config.istio.io/v1alpha2", unable to recognize "generated_default_proile_manifest_1_5_1.yaml": no matches for kind "handler" in version "config.istio.io/v1alpha2", unable to recognize "generated_default_proile_manifest_1_5_1.yaml": no matches for kind "rule" in version "config.istio.io/v1alpha2", unable to recognize "generated_default_proile_manifest_1_5_1.yaml": no matches for kind "DestinationRule" in version "networking.istio.io/v1alpha3"]

```
**Steps to reproduce the bug**
During installations

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
`istioctl version --remote`
```
client version: 1.4.6
control plane version: 1.5.1
data plane version: 1.5.1 (2 proxies)
```

`kubectl version`
kubectl version
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T23:41:24Z", GoVersion:"go1.14", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.10-eks-bac369", GitCommit:"bac3690554985327ae4d13e42169e8b1c2f37226", GitTreeState:"clean", BuildDate:"2020-02-26T01:12:54Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
`helm version`
`version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.14"}`

**How was Istio installed?**
```
istioctl manifest generate --set profile=default --set values.grafana.enabled=true --set addonComponents.grafana.enabled=true --set values.prometheus.enabled=true --set values.grafana.enabled=true --set values.tracing.enabled=true --set values.pilot.traceSampling=100 --set values.kiali.enabled=true --set "values.kiali.dashboard.jaegerURL=http://jaeger-query:16686" --set "values.kiali.dashboard.grafanaURL=http://grafana:3000" --set components.telemetry.enabled=true --set values.galley.enableAnalysis=true --set values.kiali.createDemoSecret=true --set values.global.proxy.accessLogFile="/dev/stdout" > generated_default_proile_manifest_1_5_1.yaml
k apply -f generated_default_proile_manifest_1_5_1.yaml
```

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS EKS

**Comment by nak3** [comment]
> after that, I have run it again and the problem is not coming on direct installation.

Yes, the `manifest generate` may have the transient errors due to the order. In your case, `istio-system` namespace must be created first. The docs mentions about it.

https://istio.io/docs/setup/install/istioctl/#generate-a-manifest-before-installation

> This command might show transient errors due to resources not being available in the cluster in the correct order.

You should be able to avoid the issue if you use `istioctl manifest apply`

**Comment by pawanyoda** [comment]
@nak3 
thanks for reply
I can't make it directly  like this ~~istioctl manifest apply or istioctl manifest  --set profile=demo apply~~
some feature will work for me, that's infra related not an Istio..
Can you please provide me also is there any proper docs for setup Istio with AWS internal load balancer.

**Comment by incfly** [comment]
> Can you please provide me also is there any proper docs for setup Istio with AWS internal load balancer.

seems separate discussion on discuss.istio.io or slack.
