### ISSUE TITLE
Support  for auto adding trace id for microservices  support

### ISSUE THREAD

**Issue by archerbj** [istio/istio#2249]
Hi, As we know we can do service distributed trace in istio service mesh. Istio-proxy is gonna send request trace to zipkin automatically. But user application has to add something like ["x-b3-traceid"] in their requests header to tell zipkin which requests belong to one microservice application and their dependencies relationship. 

This is slightly  but really is code injection. Is it possible to totally avoid this  ? Or will we do that ?

**Comment by douglas-reid** [comment]
Right now, there is no way to avoid having applications propagate some context, in this case trace headers. Fortunately, there are several client libraries than take care of this on behalf of applications.

Closing, as there is no further action here to resolve.
