### ISSUE TITLE
istioctl manifest apply with empty profile fails to install pilot due to missing istio-system namespace

### ISSUE THREAD

**Issue by nak3** [istio/istio#22492]
**Bug description**

When using `profile=empty` and `addonComponents.pilot.enabled=true`, it fails to due to missing istio-system namespace.

[X] Installation

**Expected behavior**

Following command deploys pilot without error.

```
istioctl manifest apply \
--set profile=empty      \
--set addonComponents.pilot.enabled=true
```

**Steps to reproduce the bug**

step-1. Run following command for brand-new cluster:

```
istioctl manifest apply \
--set profile=empty      \
--set addonComponents.pilot.enabled=true
```

step-2. You will see following error:

```
Error from server (NotFound): error when creating "STDIN": namespaces "istio-system" not found (repeated 9 times)
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
$ istioctl version --remote=false
1.5.1
```

**Additional Info**

This docs says it produces some error due to order issuer, but it is for `manifest generate`

https://istio.io/docs/setup/install/istioctl/#generate-a-manifest-before-installation

> This command might show transient errors due to resources not being available in the cluster in the correct order.

**Comment by nak3** [comment]
Please also refer to https://github.com/istio/istio/issues/22491. Same command fails due to another reason.

**Comment by howardjohn** [comment]
This one I actually think is not working as expected, we should create the namespace outside of the manifests themselves.
