### ISSUE TITLE
Envoy calling ClusterIP rather than Pod IPs

### ISSUE THREAD

**Issue by nicktrav** [istio/istio#22490]
**Bug description**

We occasionally see issues where some Envoy proxies are attempting to send traffic to the Cluster IP of a service rather than directly to Pod IPs for the given cluster. Performing a rolling restart of Pilot fixes the issue.

**Expected behavior**

Traffic should be routed directly to the Pod IP address, rather than to the Cluster IP.

**Steps to reproduce the bug**

Unfortunately, we don't yet have a reproducer.

The following is connection=debug level logging output from an Envoy having issues when connecting to a TCP service:

```
[Envoy (Epoch 0)] [2020-03-25 21:15:08.819][28][debug][connection] [external/envoy/source/common/network/connection_impl.cc:718] [C42] connecting to 10.240.14.157:5432
[Envoy (Epoch 0)] [2020-03-25 21:15:08.819][28][debug][connection] [external/envoy/source/common/network/connection_impl.cc:727] [C42] connection in progress
[Envoy (Epoch 0)] [2020-03-25 21:15:18.820][28][debug][connection] [external/envoy/source/common/network/connection_impl.cc:104] [C42] closing data_to_write=0 type=1
[Envoy (Epoch 0)] [2020-03-25 21:15:18.820][28][debug][connection] [external/envoy/source/common/network/connection_impl.cc:193] [C42] closing socket: 1
[Envoy (Epoch 0)] [2020-03-25 21:15:18.820][28][debug][connection] [external/envoy/source/common/network/connection_impl.cc:104] [C41] closing data_to_write=0 type=1
[Envoy (Epoch 0)] [2020-03-25 21:15:18.820][28][debug][connection] [external/envoy/source/common/network/connection_impl.cc:193] [C41] closing socket: 1
[2020-03-25T21:15:08.819Z] "- - -" 0 UF,URX "-" "-" 0 0 10000 - "-" "-" "-" "-" "10.240.14.157:5432" PassthroughCluster - 10.240.14.157:5432 10.72.10.3:46084 - -
```

The connection times out after 10 seconds. Note that the IP Envoy is trying to connect to in this case is a Cluster IP, on which nothing is listening:

```
$ kubectl -n print-operations get svc
NAME                              TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
print-operations-cloudsql-proxy   ClusterIP   10.240.14.157   <none>        5432/TCP   27d
``` 

During this time, the endpoint list for the given cluster shows a Pod IP present, but it is not being selected:

```
root@nickt-test-75c8887fcd-dr2r7:/# curl -s http://localhost:15000/clusters | grep print-operations | grep 5432
...
outbound|5432||print-operations-cloudsql-proxy.print-operations.svc.cluster.local::10.12.1.19:5432::cx_active::0
...
```

Performing a rolling restart of the Pilot deployment in our control plane cluster resolved the issue. Note the Pod IP is being selected now:

```
[Envoy (Epoch 0)] [2020-03-25 21:21:59.494][28][debug][connection] [external/envoy/source/common/network/connection_impl.cc:718] [C47] connecting to 10.12.1.19:5432
[Envoy (Epoch 0)] [2020-03-25 21:21:59.494][28][debug][connection] [external/envoy/source/common/network/connection_impl.cc:727] [C47] connection in progress
[Envoy (Epoch 0)] [2020-03-25 21:21:59.495][28][debug][connection] [external/envoy/source/common/network/connection_impl.cc:566] [C47] connected
[Envoy (Epoch 0)] [2020-03-25 21:21:59.506][28][debug][connection] [external/envoy/source/common/network/connection_impl.cc:534] [C47] remote close
[Envoy (Epoch 0)] [2020-03-25 21:21:59.506][28][debug][connection] [external/envoy/source/common/network/connection_impl.cc:193] [C47] closing socket: 0
[Envoy (Epoch 0)] [2020-03-25 21:21:59.506][28][debug][connection] [external/envoy/source/common/network/connection_impl.cc:104] [C46] closing data_to_write=0 type=0
[Envoy (Epoch 0)] [2020-03-25 21:21:59.506][28][debug][connection] [external/envoy/source/common/network/connection_impl.cc:193] [C46] closing socket: 1
[2020-03-25T21:21:59.494Z] "- - -" 0 - "-" "-" 113 14 12 - "-" "-" "-" "-" "10.12.1.19:5432" outbound|5432||print-operations-cloudsql-proxy.print-operations.svc.cluster.local 10.72.10.3:47698 10.240.14.157:5432 10.72.10.3:47878 - -
```

We've seen this once with 1.4.6 and once with 1.4.3. I initially thought that this might have been solved by #19025, but seeing this again today in 1.4.6 makes me think otherwise.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
$ ./bin/istioctl version --remote
control plane version: 1.4.6

$ helm version --server
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
```

**How was Istio installed?**

Helm

**Environment where bug was observed (cloud vendor, OS, etc)**

GKE

**Comment by howardjohn** [comment]
Interesting. Is the Service just a standard service (not headless or something else non-standard)?

When you listed the /clusters output, does it show only the pod IP (10.12.1.19) or the pod IP and the ClusterIP?

**Comment by nicktrav** [comment]
> Is the Service just a standard service

It's a vanilla Service. Nothing fancy.

```
$ kubectl -n print-operations get svc -o yaml print-operations-cloudsql-proxy
apiVersion: v1
kind: Service
metadata:
  labels:
    app: print-operations
    component: cloudsql-proxy
  name: print-operations-cloudsql-proxy
  namespace: print-operations
spec:
  clusterIP: 10.240.14.157
  ports:
  - name: tcp-postgres
    port: 5432
    protocol: TCP
    targetPort: postgres
  selector:
    component: cloudsql-proxy
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

> When you listed the /clusters output, does it show only the pod IP (10.12.1.19) or the pod IP and the ClusterIP?

Only the Pod IP.

This is a tricky one to debug. Pilot seems to get into this state _eventually_, but _nondeterministically_. Next time it happens, I'll make sure to capture more information. Is there anything specific that would help narrow it down (either in the Envoy logs or in the control plane)?

Mainly wanted to get this on the radar in case others had seen it, or if it was a known issue.

**Comment by howardjohn** [comment]
So the clusters shows only the pod IP, yet Envoy is connecting to the clusterIP? That seems really weird? Or is it a timing issue between when the clusterIP was used and when you looked at the /clusters output?

**Comment by nicktrav** [comment]
> So the clusters shows only the pod IP, yet Envoy is connecting to the clusterIP?

Yep. And restarting all Pilots fixes it immediately.

You can see in the two logs I pasted, from the same Envoy, either side of a Pilot reboot:

```
[Envoy (Epoch 0)] [2020-03-25 21:15:08.819][28][debug][connection] [external/envoy/source/common/network/connection_impl.cc:718] [C42] connecting to 10.240.14.157:5432
...
[Envoy (Epoch 0)] [2020-03-25 21:21:59.494][28][debug][connection] [external/envoy/source/common/network/connection_impl.cc:718] [C47] connecting to 10.12.1.19:5432
```

I would have thought that in the case there were no endpoints for a cluster, Envoy would NR the request immediately. I'm not sure how we came to be calling the cluster IP. That's what is resolved by cluster DNS, but not sure how / why Envoy ends up trying to connect to it.

**Comment by nicktrav** [comment]
Another datapoint. I collected the listeners from a test Pod with Envoy injected and I noticed that the ClusterIP of the service I was trying to call was missing (this happens for a number of TCP based services).

```
$ kubectl -n bolt get svc
NAME                       TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
bolt-grpc-cloudsql-proxy   ClusterIP   10.240.14.51   <none>        5432/TCP   6d21h

$ ./bin/istioctl proxy-config listeners nickt-test-75c8887fcd-6vkck.presto > listeners.before
$ grep 10.240.14.51 listeners.before
```

After a restart of Pilot, the endpoint was present, along with some other missing ClusterIPs.

```
$ ./bin/istioctl proxy-config listeners nickt-test-75c8887fcd-6vkck.presto > listeners.after
$ grep 10.240.14.51 listeners.after
10.240.14.51        5432      TCP
```

What is the expected behavior when the ClusterIP is missing from the list of listeners? Seems like it eventually ends up trying to connect to the ClusterIP at the network layer, but there's nothing behind that IP in this cluster (we run a multi-cluster setup), so the TCP connect attempt times out.

**Comment by howardjohn** [comment]
Ah ok what might be happening is normally we create a listener on clusterip_port. You send the request, it matches that listener, then gets forwarded to a pod ip. In your case, the listener is missing, so it doesn't match anything. In this case, it falls back to the passthrough cluster, which forwards the traffic as is (to the cluster IP). I think this is what happens here as you can see PassthroughCluser in the access log. 

so the behavior makes sense, the question now is why is the listener missing

**Comment by nicktrav** [comment]
>  In this case, it falls back to the passthrough cluster, 

Makes sense why it's falling through now. Missed that initially.

> the question now is why is the listener missing

Indeed. What's interesting is that Envoy will work for a period of time, and then it seems the listener is yanked, resulting in this situation. This points at something with Pilot.

I was going to see if I could isolate this to a specific instance of Pilot based on the Envoy that was connected to it and then trawl through some logs. Any other ideas on what would help diagnose this?

**Comment by howardjohn** [comment]
Yeah very likely to be pilot that is the issue here. So it goes from working -> broken, it never goes back to working? This sort of sounds like https://github.com/istio/istio/issues/20676 but should be fixed in 1.4.6. I don't really have any ideas about what might be the cause here, not really sure how this could happen. So maybe trawling the logs is the next step, I can help take a look as well

**Comment by nicktrav** [comment]
@howardjohn - I did some more digging here.

Comparing a broken pod to a working pod, they both have the same number of listeners for the port of interest (postgres - `5432`).

What's interesting is that if I map the listener IPs back to K8s Cluster IPs, and then to the K8s cluster they came from (we run multiple clusters), I see that for the pod(s) that are broken, the Cluster IPs in the listeners list are for _remote_ clusters. We have the Services installed in multiple clusters to allow for DNS resolution across cluster boundaries.

Concretely, here's the definition for the same Service in two clusters, A and B:

```
# Cluster A - the broken pod runs in this cluster
$ kubectl -n bolt get svc bolt-grpc-cloudsql-proxy
NAME                       TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)    AGE
bolt-grpc-cloudsql-proxy   ClusterIP   10.240.4.36   <none>        5432/TCP   12d

# Cluster B
$ kubectl -n bolt get svc bolt-grpc-cloudsql-proxy
NAME                       TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
bolt-grpc-cloudsql-proxy   ClusterIP   10.252.5.216   <none>        5432/TCP   15d
```

Looking at a working Pod in cluster A:

```
$ ./bin/istioctl proxy-config listeners presto-2b5ff53-worker-6d9cc58495-7rpwf.presto | sort | grep 5432
...
10.240.4.36         5432      TCP
...
```

We see that one of the IPs is for the cluster IP of the service in cluster A (i.e. `10.240.4.36`).

However, looking at the broken pod:

```
$ ./bin/istioctl proxy-config listeners presto-2b5ff53-worker-6d9cc58495-qnjsw.presto | sort | grep 5432
...
10.252.5.216        5432      TCP
...
```

This IP is the Cluster IP of the service in Cluster B (i.e. `10.252.5.216`).

So when the broken pod in cluster A resolves the Service, it gets the cluster IP `10.240.4.36` from Kube DNS, but there is no listener for this and it falls into the passthrough cluster, and attempts to connect to the Cluster IP directly, which fails.

This also seems to happens based on which Pilot instance a pod is connected to. I'm wondering if there's some non-determinism in the Cluster IP list that is generated to be sent down? Some pods get unlucky and connect to a Pilot with a different sort order.

I'm still digging around [`listener.go`](https://github.com/istio/istio/blob/1.4.6/pilot/pkg/networking/core/v1alpha3/listener.go) and [`listener_builder.go`](https://github.com/istio/istio/blob/1.4.6/pilot/pkg/networking/core/v1alpha3/listener_builder.go) to see what I can find. The issue might be higher up though, where the Services are stored / sorted.

**Comment by nicktrav** [comment]
Getting closer ...

Here's the response from `/debug/registryz` comparing two Pilot instances:

First, a Pilot instance for Envoy proxies that have the correctly scoped Cluster IP:

```
  {
...
    "hostname": "bolt-grpc-cloudsql-proxy.bolt.svc.cluster.local",
    "address": "10.240.4.36",
    "cluster-vips": {
      "gke_us-west2_data-cluster": "10.240.4.36",
      "gke_us-west2_services-cluster": "10.252.5.216"
    },
...
  },
```

And now a Pilot instance for Envoy's that end up falling through:

```
  {
...
    "hostname": "bolt-grpc-cloudsql-proxy.bolt.svc.cluster.local",
    "address": "10.252.5.216",
    "cluster-vips": {
      "gke_us-west2_data-cluster": "10.240.4.36",
      "gke_us-west2_services-cluster": "10.252.5.216"
    },
...
  },
  ```

Note that the `address` field is correct in the case of the former, while in the case of the latter, it's the Cluster IP from the remote K8s cluster.

It looks like the cluster VIPs are queried [here](https://github.com/istio/istio/blob/1.4.6/pilot/pkg/model/service.go#L655-L662), and if no entry is found, it falls back to the address:

```go
// GetServiceAddressForProxy returns a Service's IP address specific to the cluster where the node resides
func (s *Service) GetServiceAddressForProxy(node *Proxy) string {
	s.Mutex.RLock()
	defer s.Mutex.RUnlock()
	if node.ClusterID != "" && s.ClusterVIPs[node.ClusterID] != "" {
		return s.ClusterVIPs[node.ClusterID]
	}
	return s.Address
}
```

Seems like in the case that `node.ClusterID` is present (i.e. multi-cluster), then there should be no fallback to `s.Address`, as this doesn't seem to be deterministic. Even if it _were_, it doesn't really make sense to pick one.

**Comment by nicktrav** [comment]
Looks like this might be due to the workload not having an accompanying Service.

The `ClusterID` for a proxy `Node` is set when determining the Services for the node, here:
https://github.com/istio/istio/blob/1.4.6/pilot/pkg/serviceregistry/aggregate/controller.go#L234-L258

In the case that there is no accompanying Service, the `ClusterID` is not set. This results in the `GetServiceAddressForProxy` failing to fetch by ClusterID, and falling through to `s.Address`, which appears to be non-deterministic.

Is there no better way to infer the `ClusterID` for a `Node`? It seems weird that it's set in a seemingly unrelated responsible for fetching the associated service.

For now, I'll see about adding a Service for this workload and report back.

**Comment by howardjohn** [comment]
note stale

**Comment by howardjohn** [comment]
@stevenctl this might be related to what you are doing. Or maybe not
