### ISSUE TITLE
Uninstalling Istio 1.5.1 fails with "error converting YAML to JSON"

### ISSUE THREAD

**Issue by FilipB** [istio/istio#22496]
**Bug description**
Following was working fine in istio 1.5.0:
`istioctl manifest generate --set profile=default --set values.kiali.enabled=false --set values.tracing.enabled=false --set values.grafana.enabled=false --set values.global.mtls.enabled=false --set values.global.controlPlaneSecurityEnabled=false --set values.gateways.istio-egressgateway.enabled=true --set components.cni.enabled=true --set components.cni.namespace=kube-system --set values.cni.cniBinDir=/var/lib/cni/bin --set values.cni.cniConfDir=/etc/cni/multus/net.d --set values.cni.chained=false --set values.cni.cniConfFileName=istio-cni.conf --set 'values.sidecarInjectorWebhook.injectedAnnotations.k8s\.v1\.cni\.cncf\.io/networks=istio-cni' --set components.telemetry.k8s.resources.requests.memory=100Mi --set components.telemetry.k8s.resources.requests.cpu=50m | oc delete -f -`

but it fails with istio 1.5.1:
`error: error parsing STDIN: error converting YAML to JSON: yaml: mapping values are not allowed in this context`

[ ] Configuration Infrastructure
[ ] Docs
[X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**
run following command with istio 1.5.1:
`istioctl manifest generate --set profile=default --set values.kiali.enabled=false --set values.tracing.enabled=false --set values.grafana.enabled=false --set values.global.mtls.enabled=false --set values.global.controlPlaneSecurityEnabled=false --set values.gateways.istio-egressgateway.enabled=true --set components.cni.enabled=true --set components.cni.namespace=kube-system --set values.cni.cniBinDir=/var/lib/cni/bin --set values.cni.cniConfDir=/etc/cni/multus/net.d --set values.cni.chained=false --set values.cni.cniConfFileName=istio-cni.conf --set 'values.sidecarInjectorWebhook.injectedAnnotations.k8s\.v1\.cni\.cncf\.io/networks=istio-cni' --set components.telemetry.k8s.resources.requests.memory=100Mi --set components.telemetry.k8s.resources.requests.cpu=50m | oc delete -f -`

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istio 1.5.1

**Environment where bug was observed (cloud vendor, OS, etc)**
OCP 4.3.3

**Comment by FilipB** [comment]
This issue is caused by output of istioctl manifest generate  command which contains part of WARN log:
`2020-03-26T14:08:25.546250Z^Iwarn^Ifeature validation: security: auto mtls is enabled, but control plane security is not enabled`

1. run: `istioctl manifest generate --set profile=default --set values.kiali.enabled=false --set values.tracing.enabled=false --set values.grafana.enabled=false --set values.global.mtls.enabled=false --set values.global.controlPlaneSecurityEnabled=false --set values.gateways.istio-egressgateway.enabled=true --set components.cni.enabled=true --set components.cni.namespace=kube-system --set values.cni.cniBinDir=/var/lib/cni/bin --set values.cni.cniConfDir=/etc/cni/multus/net.d --set values.cni.chained=false --set values.cni.cniConfFileName=istio-cni.conf --set 'values.sidecarInjectorWebhook.injectedAnnotations.k8s\.v1\.cni\.cncf\.io/networks=istio-cni' --set components.telemetry.k8s.resources.requests.memory=100Mi --set components.telemetry.k8s.resources.requests.cpu=50m > istio-1_5_1.out`
2. check first line of istio-1_5_1.out, it contains:
`2020-03-26T14:08:25.546250Z^Iwarn^Ifeature validation: security: auto mtls is enabled, but control plane security is not enabled`

That line is causing failures when the output of the command is sent to `oc delete -f -`

**Comment by jmazzitelli** [comment]
> feature validation: security: auto mtls is enabled, but control plane security is not enabled

So that means the istioctl command is probably missing something it needs. When it says "control plane security is not enabled" - I do not know how to enable control plane security but I assume you can do it with some other `--set` option.

**Comment by howardjohn** [comment]
@richardwxn I thought we fixed logging to stdout? Is something weird going on here? I would think the logs go to stderr?
