### ISSUE TITLE
Not all inbound ports are redirected when CNI is enabled

### ISSUE THREAD

**Issue by btoonk** [istio/istio#22498]
**Bug description**

When using the CNI plugin not all inbound ports are redirected to the proxy.
Only the specified container port is redirected. 
This also means all other ports are unprotected when using authz policies.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
All inbound ports should be redirected to the proxy by default.
I think the sidecar injector should set some annotations on the pod (traffic.sidecar.istio.io/includeInboundPorts: "*") so CNI will redirect all ports.

**Steps to reproduce the bug**
Setup istio with CNI enabled and start a deployment/service (for example helloworld).
Setup authz policies.
Exec into pod and start a second service on a different port.
Try to connect to the pods IP/ second service port from a POD without sidecar enabled.
This should fail but it does not.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
Tried with 1.4.6 en 1.5.0 and latest daily build.

**How was Istio installed?**
istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

**Comment by btoonk** [comment]
I tried adding the podRedirectAnnot to the istio-sidecar-injector configmap (seems missing) but that did not solved the problem

**Comment by howardjohn** [comment]
@lambdai @stewartbutler I thought we used the same iptables logic now?
