### ISSUE TITLE
'istioctl kube-inject' faulty error message

### ISSUE THREAD

**Issue by esnible** [istio/istio#22501]
If the user has no Istio, and attempts to inject using configuration in a file, the error message is incorrect.  To reproduce:

```
# Uncomment for dual control plane
# REVISION=-global
kubectl -n istio-system get cm istio-sidecar-injector$REVISION -o yaml > inject-config.yaml
kubectl -n istio-system get configmap istio$REVISION -o=jsonpath='{.data.mesh}' > mesh-config.yaml
istioctl kube-inject --injectConfigFile /tmp/inject-config.yaml --meshConfigFile /tmp/mesh-config.yaml  -f samples/bookinfo/platform/kube/bookinfo.yaml
```

The output will include  `... configmaps "istio-sidecar-injector" not found - Use --injectConfigFile ... `.

This is not correct advice; the user **DID** use `--injectConfigFile`.

**Comment by dgn** [comment]
Note that I changed the milestone to 1.5 as this is in the process of being backported
