### ISSUE TITLE
FR(telemetry): Metadata exchange response headers should be returned only on requests from within the mesh

### ISSUE THREAD

**Issue by StefanCenusa** [istio/istio#22546]
**Describe the feature request**
This feature request is a follow-up to [this thread on istio slack](https://istio.slack.com/archives/C382V8Q92/p1585143701006300).

At the moment, when istio (1.5.1) is installed and telemetry v2 is enabled, every istio-proxy returns some metadata exchange headers which contain [potentially sensitive](https://cwe.mitre.org/data/definitions/200.html) information such as service names, internal ips, labels, namespaces, cluster name and more. This headers are required in order to enrich the stats produced by  istio proxy.
However, when making requests to istio injected services through NodePort or using other ingress controllers, the metadata exchange headers returned on response are most of the time useless for the client.

**Describe alternatives you've considered**
There should be an option to disable this behaviour on requests that do not provide metadata exchange headers, and only return metadata on those which do. Thus, transitioning to istio telemetry-v2 would not be blocked by adopting istio-ingresscontroller or writing EnvoyFilters to remove those headers. Moreover, I believe that docs should warn users about this headers being exchanged through the mesh when using telemetry v2.

**Additional context**

**cc**:  @kyessenov

**Comment by mandarjog** [comment]
@kyessenov we have a new annotation now that designates gateways as ingress / middle and egress . I think we can use it.

**Comment by kyessenov** [comment]
@mandarjog The issue is specifically for use cases that don't want to use gateways. They are addressing sidecars directly via node ports.
