### ISSUE TITLE
add request middleware or something similar

### ISSUE THREAD

**Issue by mstrYoda** [istio/istio#22541]
**Describe the feature request**
Is it possible to add a middleware mechanism for example request first routes to another container/endpoint and then routes or not routes to main container.

The purpose here is to add a cache layer in front of application container. We used to use load balancer cache but now we remove the load balancer and requests go between services directly.

**Describe alternatives you've considered**
There is a pr for envoy : https://github.com/envoyproxy/envoy/pull/10536

Also envoy has a feature called lua filter: https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/lua_filter#currently-supported-high-level-features

It has a capability :

“Performing a direct response and skipping further filter iteration. For example, a script could make an upstream HTTP call for authentication, and then directly respond with a 403 response code.”

Does istio support it? Or can support it? Or go version of this can be implemented?

**Additional context**

**Comment by howardjohn** [comment]
https://istio.io/docs/reference/config/networking/envoy-filter/ Is the way to add lua, we also have alpha support for wasm (see recent blog posts on istio.io)

**Comment by mstrYoda** [comment]
> https://istio.io/docs/reference/config/networking/envoy-filter/ Is the way to add lua, we also have alpha support for wasm (see recent blog posts on istio.io)

Thank you for your response. I also found that it can be used with EnvoyFilter custom resource. 
We are waiting for wasm support it sounds promising. Thank you 👍

**Comment by howardjohn** [comment]
Closing as this has been addressed by ^. Thanks
