### ISSUE TITLE
DNS interception and upgrade to DNS-over-TLS

### ISSUE THREAD

**Issue by costinm** [istio/istio#22547]
RFC: https://docs.google.com/document/d/1zQjrg9SAyFbFObuhykpqkvGF3C3FNcl5rXw2ZF0PYQc

For 1.6, the minimum is to allow redirection of plain text DNS-over-UDP requests from applications
to a secure DNS-over-TLS server. 

Optional - in 1.6 or later - we can add support for .global ( or equivalent multi-cluster zone ), and 
optimize resolution by using Istiod multi-cluster view of cluster IPs, to remove the DNS setup pains
for MC. 

**Describe the feature request**

**Describe alternatives you've considered**

**Additional context**

**Comment by nrjpoddar** [comment]
PR in progress related to this effort: https://github.com/istio/istio/pull/22369
