### ISSUE TITLE
A missing CRD causes istiod to not properly start-up

### ISSUE THREAD

**Issue by jacob-delgado** [istio/istio#22560]
**Bug description**

When an expected CRD is missing, istiod fails to start and repeatedly issues a log similar to `2020-03-27T23:19:19.485207Z	info	controller "security.istio.io/v1beta1/AuthorizationPolicy" is syncing...`

**Expected behavior**

1. Either istio reports that a CRD is missing and cannot start succesfully 

or

2. istiod starts, logs a warning that a CRD is missing and continues on

**Steps to reproduce the bug**

1. Install istio 1.5+
2. `kubectl delete crd authorizationpolicies.security.istio.io`
3. `kubectl delete pod -n istio-system $(kubectl get pod -n istio-system -l app=istiod -o jsonpath='{.items[0].metadata.name}')`
4. Wait a few seconds until the new pod appears
5. `kubectl logs -n istio-system $(kubectl get pod -n istio-system -l app=istiod -o jsonpath='{.items[0].metadata.name}')`

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

client version: 1.5.0
control plane version: 1.5.0
data plane version: none

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-26T06:16:15Z", GoVersion:"go1.14", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.9", GitCommit:"2e808b7cb054ee242b68e62455323aa783991f03", GitTreeState:"clean", BuildDate:"2020-01-18T23:24:23Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**

istioctl manifest apply --set values.global.outboundTrafficPolicy.mode=REGISTRY_ONLY --set values.telemetry.v1.enabled=true --set values.telemetry.v2.enabled=false --set components.telemetry.enabled=true --set components.citadel.enabled=true --set values.gateways.istio-egressgateway.enabled=true

**Environment where bug was observed (cloud vendor, OS, etc)**

AWS on a K8s cluster created by kops.

**Comment by jacob-delgado** [comment]
Duplicate of https://github.com/istio/istio/pull/22557

**Comment by sdake** [comment]
@jacob-delgado reading @howardjohn 's PR for this issue, he had said it is reasonable to not expect CRDs present if they are not planned to be used.

My question is, what drove you to execute step 2?

I do agree with @howardjohn; istiod shouldn't block because a CRD name is missing.

I also believe that it may be warranted to just disable the entire group if one CRD is missing. I think the complexity of turning on/off an entire group if one CRD is missing is not desirable (this is not what John's PR does, btw).

A follow-up question for you. The **Expected Behavior** field is missing from your issue report. Can you improve the issue by adding what you think the expected behavior should be?

**Comment by jacob-delgado** [comment]
@sdake This was actually seen when I was doing development. I had a version of istioctl that did not contain the WorkloadEntry CRD, but had pushed images to docker hub that did. That's not entirely reproducible and isn't really indicative of user behavior so I was able to re-create it using istio 1.5.

As far as leaving expected behavior empty, I actually didn't know what to expect. I've updated it, but I'm skeptical about option (2) as a user may not know how to  fix the underlying issue unless they were do a a `kubectl get crds` or equivalent command. Better error messages are a good start at a minimum.

**Comment by jacob-delgado** [comment]
cc @howardjohn 

Verified with istio 1.6.0-alpha.1

Logs were looping, but contained the following:
```
istiod-5459687ff-8b7f7 discovery 2020-04-07T18:26:53.465291Z	error	authorization	failed to initialize authorization policies: missing type "security.istio.io/v1beta1/AuthorizationPolicy"
istiod-5459687ff-8b7f7 discovery 2020-04-07T18:26:53.465318Z	error	authorization	failed to initialize authorization policies: missing type "security.istio.io/v1beta1/AuthorizationPolicy"
istiod-5459687ff-8b7f7 discovery 2020-04-07T18:26:53.465324Z	warn	ads	Error reading config missing type "security.istio.io/v1beta1/AuthorizationPolicy"
istiod-5459687ff-8b7f7 discovery 2020-04-07T18:26:53.465736Z	info	transport: loopyWriter.run returning. connection error: desc = "transport is closing"
```

Feel free to close this issue

**Comment by howardjohn** [comment]
ill investigate that, thanks
