### ISSUE TITLE
Can istio 1.5.1 run on kubernetes 1.17. X？

### ISSUE THREAD

**Issue by catman002** [istio/istio#22579]
**Describe the feature request**

**Describe alternatives you've considered**

**Additional context**
Can istio 1.5.1 run on kubernetes 1.17. X?

**Environment version:**
Kubernetes 1.17.0 (haproxy as load balancing)
Istio1.5.1

**Istio installation is OK**:
[root@node0 ~]# kubectl get pods  -n istio-system
```
NAME                                      READY   STATUS      RESTARTS   AGE
istio-citadel-f5974cc7d-crll7             1/1     Running     0          3d19h
istio-galley-79bf89757d-njv9k             1/1     Running     0          3d19h
istio-ingressgateway-85b98d7b69-f4vt7     2/2     Running     0          3d19h
istio-init-crd-all-1.5.1-t54hw            0/1     Completed   0          3d19h
istio-init-crd-mixer-1.5.1-bhwjh          0/1     Completed   0          3d19h
istio-pilot-5474d4d5d-q6kt9               2/2     Running     0          3d19h
istio-policy-778865cf96-4q52r             2/2     Running     0          3d19h
istio-sidecar-injector-5d97f8cb99-8ddth   1/1     Running     0          3d19h
istio-telemetry-84df7bf466-55ftv          2/2     Running     0          3d19h
prometheus-c8fdbd64f-5j284                1/1     Running     0          3d19h
```
But there is an error in deploy gateway, virtrualService and DestinationRule, similar to:
Post https://172.16.80.191:6444/apis/networking.istio.io/v1alpha3/namespaces/istio-system/envoyfilters: read tcp 172.16.80.139:55170->172.16.80.191:6444: read: connection reset by peer。

**Comment by howardjohn** [comment]
where is the error from? kubectl? Seems like connectivity issues to API server possibly but I am not sure why the whole deployment wouldn't fail then

**Comment by catman002** [comment]
@howardjohn 
Error when publishing virtualservice or destinationrule or gateway:
Post https://172.16.80.191:6444/apis/networking.istio.io/v1alpha3/namespaces/istio-system/envoyfilters: read tcp 172.16.80.139:55170->172.16.80.191:6444: read: connection reset by peer。

If it's kubernetes 1.16. X, no problem

**Comment by howardjohn** [comment]
As a test, can you remove the validation webhook and see if it works that way? `kubectl delete validatingwebhookconfigurations.admissionregistration.k8s.io istio-galley` will likely do this

**Comment by catman002** [comment]
@howardjohn 

Tested:
Istio 1.5.1 needs to be installed on k8s1.17.0 and k8s1.17.2, and the publishing application needs to execute:
"Kubectl delete validatingwebhookconfigurations.admissions registration.k8s.io istio-valley" to publish successfully.

Install istio 1.5.1 on k8s1.17.4, and you do not need to delete “galley” .
Thank you!
