### ISSUE TITLE
istio 1.5.0 Mixer Report failed with: UNAVAILABLE:Cluster not available

### ISSUE THREAD

**Issue by AceHack** [istio/istio#22574]
I'm having this issue.

https://github.com/istio/istio/issues/22029

What does it affect? and how can I fix it?

**Comment by Henrike42** [comment]
The issue was on my side, that I still wanted to use the deprecated mixer and an out of process mixer adapter. This setup didn't work anymore. I solved the issue by disabling the mixer feature (default with istioctl 1.5.x) and using envoy filters instead of a mixer adapter.

**Comment by AceHack** [comment]
I'm using Knative, is this why I'm getting the issue?

**Comment by AceHack** [comment]
I spoke with Knative and they said, mixer is not a requirement for them.  Is this something we can just turn off?  Will we lose any Istio features?  How do I fix it?

**Comment by Henrike42** [comment]
When you use the istioctl version 1.5.x, mixer is automatically turned off. Which values/parameters are you setting in regards to istioctl? I am also using istio 1.5.1 in combination with knative serving.

**Comment by aniketd** [comment]
I'm having this same issue.

**Comment by widdix123** [comment]
I am having the same issues on `v1.5.1` and the pods are continuously restarting. There is no error in `telemetry` logs. Should i downgrade to a lower version for istio ? 

It is a blocker for me. Any suggestions? 

![image](https://user-images.githubusercontent.com/38529736/79072674-e513b480-7cff-11ea-8d45-7e03182391f8.png)

**Comment by brijchavda** [comment]
I am facing the same Error with 1.6.2. Does anyone have solution?

**Comment by blhagadorn** [comment]
@brijchavda Is your istioctl version in lien with your remote version of Istio on the cluster as well as your proxies?

**Comment by widdix123** [comment]
You need to keep the below components and the error goes away

```
istio-egressgateway-85f46c7774-5hg84    1/1     Running   0          4d10h
istio-ingressgateway-85576dff98-vmj2x   1/1     Running   0          4d10h
istio-tracing-8584b4d7f9-9b8hc          1/1     Running   0          4d10h
istiod-5cbfb7db8f-52kxk                 1/1     Running   0          4d10h
kiali-696bb665-9pcrv                    1/1     Running   0          4d10h
```

**Comment by brijchavda** [comment]
> @brijchavda Is your istioctl version in lien with your remote version of Istio on the cluster as well as your proxies?

client version: 1.6.0
control plane version: 1.6.2
data plane version: 1.6.2 (148 proxies)

I am not using istioctl to do anything. How does client version matter.?

**Comment by brijchavda** [comment]
> You need to keep the below components and the error goes away
> 
> ```
> istio-egressgateway-85f46c7774-5hg84    1/1     Running   0          4d10h
> istio-ingressgateway-85576dff98-vmj2x   1/1     Running   0          4d10h
> istio-tracing-8584b4d7f9-9b8hc          1/1     Running   0          4d10h
> istiod-5cbfb7db8f-52kxk                 1/1     Running   0          4d10h
> kiali-696bb665-9pcrv                    1/1     Running   0          4d10h
> ```

I have everything except egressgateway, Which we disabled purposefully.

**Comment by douglas-reid** [comment]
The warning message itself is fairly innocuous. It means that your proxies are configured to report to Mixer, but aren't successfully finding Mixer. So, I wouldn't worry about it other than it filling up your logs. Mixer restart loops, which are also mentioned here, were typically triggered by missing configuration (partial installs).

Mixer is deprecated and has been disabled by default since 1.5. 1.7 will be the last release in which it is packaged with Istio. Disabling it should not cause any harm unless you are fully trying to use some of its features.

**Comment by jurgenweber** [comment]
ok, I need Mixer on, as we have an 'out of process' adapter, what config do I need?

I don't have citadel on, is this required?

**Comment by douglas-reid** [comment]
@jurgenweber what is the context for your question? are you seeing issues with your OOP adapter? Note that 1.7 should now ship with a Mixer-based shim for maintaining functionality of OOP adapters. It should work for the next set of releases (with a bit of special configuration), but with the 1.8 release, moving over to Wasm-based Envoy extensions will be the recommendation.

**Comment by jurgenweber** [comment]
no, I am seeing the error in the OP and I am just stating that turning it off is not a solution for us, I need it on.

**Comment by douglas-reid** [comment]
how did you install?  do you have unhealthy pods?  can you open a different issue covering setup and issues and impact?

**Comment by jurgenweber** [comment]
Hi @douglas-reid as requested; https://github.com/istio/istio/issues/26815

**Comment by douglas-reid** [comment]
Closing in favor of the 1.6.8 report.
