### ISSUE TITLE
PSP  sample is dangling in website

### ISSUE THREAD

**Issue by incfly** [istio/istio#22577]
**Bug description**

After 1.5 do we still need the sidecar-psp config for SDS? I think this is used to protect host file mount from being modified by other pods, but how is it done today? is it redudant?

I'm trying to read some docs based on the links in the sample file, but that page is gone.
https://github.com/istio/istio/blob/master/samples/security/psp/sidecar-psp.yaml#L2

We need either remove this file or update the doc link, maybe doc itself as well.

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by yangminzhu** [comment]
cc @samprit some doc cleanup.

**Comment by myidpt** [comment]
We don't need the PSP instructions in the security tasks, but we want to write a section in FAQ for the users that want to set up PSP when using Istio - it can still be tricky for them, although SDS is not a problem any more.
For the PSP files with dangling links, we can simply remove them for now.

**Comment by myidpt** [comment]
Samprit, please feel free to help in this issue.
