### ISSUE TITLE
How to change the log time zone of each component of Istio to CST format？

### ISSUE THREAD

**Issue by kuaiwenwu** [istio/istio#22582]
May I ask if the log time area of ​​each component of Istio can be changed to CST format, so that we can use it for log collection and analysis.

**Comment by hzxuzhonghu** [comment]
https://serverfault.com/questions/683605/docker-container-time-timezone-will-not-reflect-changes

**Comment by rainmetersjtu** [comment]
> https://serverfault.com/questions/683605/docker-container-time-timezone-will-not-reflect-changes

Is there any config we can use to change timezone for istio-proxy (envoy) accesslog ? it will be a lot of work to do if change timezone for sidecar image. thank you

**Comment by shalk** [comment]
I think change timezone of image will not take any effect. 

https://github.com/envoyproxy/envoy/issues/3546

**Comment by rainmetersjtu** [comment]
yes，after try change image timezone, it seems timezone doesn't work in accesslog

**Comment by howardjohn** [comment]
Following envoy guidance, as we want consistent logs: https://github.com/envoyproxy/envoy/issues/3546#issuecomment-394786436

**Comment by helloord** [comment]
> May I ask if the log time area of ​​each component of Istio can be changed to CST format, so that we can use it for log collection and analysis.

Is this problem solved?

**Comment by helloord** [comment]
> yes，after try change image timezone, it seems timezone doesn't work in accesslog

Is this problem solved?
