### ISSUE TITLE
possible typo in EnvoyFilter-Samples

### ISSUE THREAD

**Issue by mstrYoda** [istio/istio#22585]
**Bug description**

**Expected behavior**
The example at https://github.com/istio/istio/wiki/EnvoyFilter-Samples#adding-a-http-lua-filter is have typo on line:

```
typed_config:
   "@type": "type.googleapis.com/envoy.config.filter.http.lua.v2.Lua"
  inlineCode: |
```
@type has one additional space I think because when we apply that example directly it gives the error:

> error: error parsing envoylua.yaml: error converting YAML to JSON: yaml: line 27: did not find expected key

**Steps to reproduce the bug**
Copy paste the given example and run kubectl apply -f envoyfilter.yaml.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
Thanks, I have updated the page

**Comment by mstrYoda** [comment]
Typo on site fixed by https://github.com/istio/api/pull/1362
