### ISSUE TITLE
Example task throwing a SSL error: Plugging in existing CA Certificates

### ISSUE THREAD

**Issue by manuelbuil** [istio/istio#22587]
**Bug description**
I have been running the Security example tasks and all have worked perfectly but I keep seeing an error in the "Plugging in existing CA Certificates" task when executing step 2 [link](https://istio.io/docs/tasks/security/plugin-ca-cert/#verifying-the-certificates):
```
2. Retrieve the certificate chain of httpbin:
kubectl exec $(kubectl get pod -l app=sleep -n foo -o jsonpath={.items..metadata.name}) -c istio-proxy -n foo -- openssl s_client -showcerts -connect httpbin.foo:8000 > httpbin-proxy-cert.txt
```
The command returns an error:
```
depth=2 C = US, ST = California, L = Sunnyvale, O = Istio, OU = Test, CN = Root CA, emailAddress = testrootca@istio.io
verify error:num=19:self signed certificate in certificate chain
139945834082752:error:1409445C:SSL routines:ssl3_read_bytes:tlsv13 alert certificate required:../ssl/record/rec_layer_s3.c:1528:SSL alert number 116
command terminated with exit code 1
```
When I open `httpbin-proxy-cert.txt` I see the three certificates and I can continue the task without any problem, so that error does not impact the end result.

**Expected behavior**
Command executing without any error

**Steps to reproduce the bug**
`curl -L https://istio.io/downloadIstio | sh -`
`cd istio-1.5.1`
`export PATH=$PWD/bin:$PATH`
`kubectl create namespace istio-system`
`kubectl create secret generic cacerts -n istio-system --from-file=samples/certs/ca-cert.pem \
    --from-file=samples/certs/ca-key.pem --from-file=samples/certs/root-cert.pem \
    --from-file=samples/certs/cert-chain.pem`
`istioctl manifest apply --set profile=demo --set values.global.mtls.enabled=true`
`kubectl create ns foo`
`kubectl apply -f <(istioctl kube-inject -f samples/httpbin/httpbin.yaml) -n foo`
`kubectl apply -f <(istioctl kube-inject -f samples/sleep/sleep.yaml) -n foo`
`kubectl exec $(kubectl get pod -l app=sleep -n foo -o jsonpath={.items..metadata.name}) -c istio-proxy -n foo -- openssl s_client -showcerts -connect httpbin.foo:8000 > httpbin-proxy-cert.txt`

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
client version: 1.5.1
control plane version: 1.5.1
data plane version: 1.5.1 (5 proxies)
```
**How was Istio installed?**
Through istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**
Baremetal, openSUSE

**Comment by incfly** [comment]
@lei-tang would you be able to take a look? I think you recently add some test on this.

**Comment by lei-tang** [comment]
The example CA cert is a self signed cert. Hence the error  “error:num=19:self signed certificate in certificate chain”. This does not impact the end result, i.e, retrieving the certificate chain from the sidecar.

**Comment by manuelbuil** [comment]
ok! thanks Lei-tang
