### ISSUE TITLE
Missing labels in Envoy telemetry (telemetry v2)

### ISSUE THREAD

**Issue by jotak** [istio/istio#22584]
**Bug description**

Previously, telemetry from proxies (envoy-stats job) did include pod labels. They have been removed with the intention to reduce metrics cardinality (https://github.com/istio/istio/pull/21555).

However, I don't think it had any impact on cardinality, because `pod_name` is still written anyway, so the cardinality is still bound to one metric per pod. With the previous `labelmap`ing that was removed, cardinality was already one per pod.

The drawback of this change is that, removing `labelmap` breaks some correlation that we could previously do between workloads and metrics. For instance, Kiali was able to show some Envoy metrics [1], but now it can't anymore unless users change their prometheus config

[1] https://discuss.istio.io/t/poll-should-we-make-envoy-dashboards-in-kiali-more-visible/5267/4

**Expected behavior**

Have pods labels back, such as `app` and `version` or whatever is defined on pods, so that correlation with metrics is possible.

**Steps to reproduce the bug**

Just let the mesh generate some metrics and look at them in Prometheus; all metrics prefixed with `envoy_` are concerned.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

1.5

**How was Istio installed?**

`istioctl manifest apply --set profile=demo`

**Environment where bug was observed (cloud vendor, OS, etc)**

Minikube

**Comment by Stono** [comment]
I agree it doesn’t impact cardinality but it does impact storage and network IO.

I’d be keen to see something in the middle perhaps, a (configurable) whitelist of acceptable labels (app, version?) rather than all.

**Comment by jotak** [comment]
@Stono yes perhaps something in the middle would be fine. Storage and network are impacted by a constant factor, so I would say it isn't "that bad" to have more labels, depends on the level of optimization that is needed. Perhaps that could be something managed from profiles: demo profile could keep labels whereas production-ready profiles wouldn't ?

**Comment by douglas-reid** [comment]
v2 telemetry is the only way this was even possible, and the PR that removed the labelmapping was prior to their promotion as a default in 1.5, so I don't think this can be viewed as a regression. It was never a fully-supported feature.

however, the correlation between workloads and metrics can still be achieved: `instance` and `pod_name` label, which offer direct correlation, are still being added to metrics, if you want to do the direct correlation in Prometheus.

If you want to do correlation via kubeapi, `*_canonical_service`, `*_canonical_revision`, `*_app`, and `*_version` labels exist on the `istio_*` metrics.

Prometheus configuration can be tailored to individual use cases easily. The trick is picking a default set for demo and other purposes that is broadly useful.

I don't think making it ultra configurable is going to be aligned with the env wg push to eliminate all add-on mgmt from Istio purview.

Happy to chat more in the next P&T WG meeting about this more.

**Comment by jotak** [comment]
Sorry @douglas-reid , it wasn't clear, I'm talking about envoy metrics (from envoy-stats job)
