### ISSUE TITLE
istioctl vm-bootstrap based on workload entry

### ISSUE THREAD

**Issue by rshriram** [istio/istio#22596]
**Describe the feature request**

With workload entry, operators can now describe the properties of a workload (service account, IP, labels, port mapping, etc.). But they still need to copy the certs from kubernetes, and start the sidecar on the VM (with or without IPtables traffic capture). 

If we assume a base case model where the VM does not want iptables traffic capture (i.e. users will create Sidecar api to forward traffic and add a HTTP proxy env var to the tomcat JVM to forward all outbound traffic via the sidecar), and if the VM has docker installed, then we can envision the UX to bootstrap a sidecar on VM as follows:

1. Operator creates service account for the VM service
2. Operator creates workload entry for the VM with all details in a specific namespace (say config is called vm1/ns1)
3. operator runs `istioctl vm-bootstrap vm1/ns1`

istioctl can read the workload entry, talk to istiod to get a bootstrap certificate for the service account mentioned in the workload entry, `scp` the certificate to the VM on a pre-defined path like /var/run/istio or something, start the istio proxy docker container on the VM with appropriate env vars (pod name, namespace, etc. as well as an env var that points to the bootstrap certificate). Alternatively, if we decide to use long lived tokens instead of long lived bootstrap certificates as both seem to have same properties in this specific scenario, we wont even need to scp certs to VMs. istioctl can obtain the token from the service account, start the istio-proxy container on the VM with the token as an input.

Note that creating a workload entry via istioctl is another option but it may be unwieldy as users have to specify IP, port mappings to the service, labels for the VM without with service entries wont select, service account names, and the namespace where the VM is being onboarded. 

cc @smawson / @esnible / @howardjohn 
@SecurityInsanity from our team has volunteered to build this feature into istioctl.

**Describe alternatives you've considered**

**Additional context**

**Comment by howardjohn** [comment]
cc @costinm @irisdingbj

**Comment by smawson** [comment]
cc @liminw

**Comment by smawson** [comment]
For step 3, how would istioctl know where to scp to? Ask the user? Or bake that into the command?

I wonder if the vm-bootstrap command can optionally bundle the results locally, so a user with a CD system could run it to provision a bundle that goes onto the VM? Maybe as part of building the VM image?

**Comment by rshriram** [comment]
The workload entry has the vm ip right? So istioctl can read it from the workload entry.

The bundling part - we can have a cli arg to spit out the certs. But traditional vcenter vms are very generic. They don’t have an image for each service. It’s just one standard Rhel with tomcat in several cases. So we can’t escape scp in those cases.

**Comment by irisdingbj** [comment]
@rshriram We are now working to plugin cert automatically when bootstrapping Istio and generate intermediate CAs for use of VM and multi-cluster, https://github.com/istio/istio/pull/22384 is for this. We will also provide `istioctl x gen-key-cert` to help generate the cert for VMs from the intermediate CA. 

So for workload on VMs, we will not rely on the related service account and token. We will use client cert for authentication with istiod. User can plugin cert via `PROV_CERT`. 

Is this approach satisfy the scenario you listed above? 

@costinm In case you have any comments on this.

**Comment by rshriram** [comment]
>So for workload on VMs, we will not rely on the related service account and token. We will use client cert for authentication with istiod. User can plugin cert via PROV_CERT.

This is not in line with the WorkloadEntry API that just got merged. That API explicitly lists a k8s service account that will bootstrap the VM. Not a custom CA generated cert as that is much harder to trace/audit, etc.

**Comment by linsun** [comment]
@rshriram I'm not sure this would be acceptable to most users:

```Alternatively, if we decide to use long lived tokens instead of long lived bootstrap certificates as both seem to have same properties in this specific scenario,```

I think the JWT token associated with the service account needs to be 3p.  I believe @irisdingbj started with that approach (a couple of us thought was a great idea @liminw @smawson ) to use the 3p JWT token to bootstrap VM to get the key/certs for the service on VM, however @costinm had security concerns with that approach.  I'll defer to @costinm to highlight his security concern.

**Comment by irisdingbj** [comment]
@rshriram The other thing is we will need a pod pre-exists to get one 3P JWT token although we may  call k8s API server to generate one. This will be still painful.

**Comment by howardjohn** [comment]
We should not grab it from a pod, there is a kubernetes API that can be
called

**Comment by howardjohn** [comment]
@myidpt how do we handle token refresh if we just the jwt token? if we do this we will need the agent calling the k8s API to get a token, and then it needs a way to authenticate itself?

**Comment by irisdingbj** [comment]
yep, it then need a way to authenticate itself when calling k8s API, So this is the reason why we think plug in cert directly instead of using tokens.

**Comment by rshriram** [comment]
That’s the idea behind this cli command. when the user runs this command once to get a long lived jwt from k8s. The user starts the vm Sidecar with the jwt. The agent on the vm can then use the jwt just like we do with pods. There is no automatic way for the agent to obtain bootstrap certs or jwt. It is always through the user provisioning manually unless the vm node attestation can be coupled with k8s (this isn’t going to happen anytime soon in oss ). 

We actually use this cli method with our enterprise customers to bootstrap their VMs and it has worked pretty decently as long as the vm has docker installed (well we used to get certs from the k8s secrets using this cli, but now with recent changes, this can become 3p jwt).

**Comment by liminw** [comment]
I shared a [proposal](https://docs.google.com/document/d/1-612Sgz_skeoX44dw3MU6Z8ONgq1f29wLUI9zggyLec) on VM identity provisioning. The idea is to exchange VM's existing credential for a k8s credential, and k8s RBAC is used to authorize the exchange.

**Comment by smawson** [comment]
Quick note on that proposal, it solves a slightly different problem, for cases where the VM already has identity. It should not be considered a proposal for solving cases where the VM does not have any identity available to it (as this issue is addressing).

**Comment by esnible** [comment]
Closing because we have `istioctl x sidecar-bootstrap`.
