### ISSUE TITLE
SDS Enabled even when values.global.sds.enabled=false

### ISSUE THREAD

**Issue by whitleykeith** [istio/istio#22591]
**Bug description**
SDS seems to be enabled even when it's set to disabled in values.global.sds.enabled=false

**Expected behavior**
When I set values.global.sds.enabled=false I expect sds to be disabled
I also have the controlPlaneSecurityEnabled=false as well. 
**Steps to reproduce the bug**
Install with the above values
Check sidecar logs to see that SDS is enabled

example:
info    sds    Start SDS grpc server
info    sds    node:sidecar~10.1.69.218~zk-zookeeper-application-0.solr-test~solr-test.svc.cluster.local-2 resource:default pushed key/cert pair to proxy

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

1.5.1

**How was Istio installed?**
Standalone operator

**Environment where bug was observed (cloud vendor, OS, etc)**

Local (docker-desktop, Mac)
AWS (EKS 1.15)

**Comment by howardjohn** [comment]
SDS is now the default and only option. `values.global.sds.enabled=false` is no longer supported

**Comment by esnible** [comment]
@howardjohn @ostromart We don't have an analyzer or validator for this.

Should I make `istioctl` reject `values.global.sds.enabled=false` without `--force`?

**Comment by howardjohn** [comment]
@esnible we don't need a special analyzer/validator, we just need to remove it from the values proto and it will be rejected, similar to https://github.com/istio/istio/pull/22576 I think

**Comment by AceHack** [comment]
So how do you turn off security and SDS?  We would like to completely disable it.

**Comment by howardjohn** [comment]
@AceHack why? SDS should be an implementation detail.

**Comment by AceHack** [comment]
Because since it's been forced on in 1.5 I get errors a lot of the time on startup related to
https://github.com/istio/istio/issues/22590

It's very random

**Comment by incfly** [comment]
Thats a separate issue. Closing this one since you already filed #22590
