### ISSUE TITLE
error initializing configuration '/etc/envoy/envoy-rev0.json': invalid ipv4 address ''

### ISSUE THREAD

**Issue by saturnism** [istio/istio#226]
Installed istio in default namespace, which I also have other services running, including headless service. Headless service has no cluster IP, thus istio proxy sidecar produced error:

```
03:40:00.800][32][critical][main] error initializing configuration '/etc/envoy/envoy-rev0.json': invalid ipv4 address ''
```

Should at least ignore headless service.

**Comment by kyessenov** [comment]
Fixed by https://github.com/istio/manager/commit/3debc8753580f6282832af5e3397b6ee3c616d95
