### ISSUE TITLE
Missing package 

### ISSUE THREAD

**Issue by dosten** [istio/istio#22601]
**Bug description**

Hi, we are stick to v1.1.5, the `istio/tools` dep is trying to make `go get istio.io/fortio@v1.1.0` but that link started throwing a `404`.

Example:

https://istio.io/istio?go-get=1 OK
https://istio.io/tools?go-get=1 OK
https://istio.io/fortio?go-get=1 FAIL

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
We have drop this dependency in isto/tools so I think this is fixed. Let me know if not

**Comment by dosten** [comment]
Currently we moved to go modules, so now we use the `replace` directive to replace `istio.io/fortio` by `fortio.org/fortio`.

But this will affect to anyone stick to `dep` and using an older version of `istio/tools`

**Comment by howardjohn** [comment]
So my understanding is this is fixed in master, but not in older versions. But we cannot really change older versions now? So I think there is nothing we can do here; if people run into this they can update or use the replace? Am I understanding correctly?

**Comment by howardjohn** [comment]
This is fixed on later versions
