### ISSUE TITLE
Remove v1alpha1 authentication policy API

### ISSUE THREAD

**Issue by diemtvu** [istio/istio#22602]
This is a tracking bug for v1alpha1 [authentication API](https://github.com/istio/api/tree/master/authentication/v1alpha1)

[x] Ignore v1alpha1 resources in Pilot (https://github.com/istio/istio/pull/22275, https://github.com/istio/istio/pull/22419)
[x] Remove v1alpha1 resources from push context (https://github.com/istio/istio/pull/22446)
[] Remove/deprecated tools that checking v1alpha1 (https://github.com/istio/istio/pull/22407)
[] Remove corresponding CRDs
[] Remove API

**Additional context**

**Comment by esnible** [comment]
As part of this work we need an analyzer that warns if v1alpha1 policy CRs are present in the cluster.

**Comment by jasonwzm** [comment]
> As part of this work we need an analyzer that warns if v1alpha1 policy CRs are present in the cluster.

Related https://github.com/istio/istio/issues/19355

**Comment by brian-avery** [comment]
Can you please update this?

**Comment by esnible** [comment]
Is this still planned for 1.6?  Is this a P1, P2, or P>2?

**Comment by diemtvu** [comment]
It's done.
