### ISSUE TITLE
Istio does not return WWW-Authenticate header when JWT policy validation fails

### ISSUE THREAD

**Issue by mhite** [istio/istio#22610]
**Bug description**

Istio correctly returns a 401 to clients when JWT policy validation fails. However, it does not return the "WWW-Authenticate" header in the response or accompanying diagnostic information.

For example, using this policy:

```
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: mhite-elbgateway-jwt
  namespace: istio-system
spec:
  targets:
  - name: mhite-elbgateway
  origins:
  - jwt:
      issuer: "https://accounts.google.com"
      audiences:
      - 407408718192.apps.googleusercontent.com
      jwksUri: "https://www.googleapis.com/oauth2/v3/certs"
      - excludedPaths:
        - exact: "/"
  principalBinding: USE_ORIGIN
```

When I send an expired token in a request, I see a 401 response like the following:

```
< HTTP/2 401 
< content-length: 29
< content-type: text/plain
< date: Mon, 23 Mar 2020 18:33:07 GMT
< server: istio-envoy
< via: 1.1 google
< alt-svc: clear
< 
Origin authentication failed.
```

Unfortunately the response does not include the expected `WWW-Authenticate` header.[1]

[1] - https://tools.ietf.org/html/rfc6750#section-3

It would be fantastic to support errors here, too. IE:

```
HTTP/1.1 401 Unauthorized
  WWW-Authenticate: error="invalid_token",
    error_description="The Access Token expired"
```

Specifically, it would be nice to propagate these error codes:

https://github.com/google/jwt_verify_lib/blob/master/src/status.cc

(Envoy uses jwt_verify_lib)

Right now, to even see these, you have to turn on Istio DEBUG logs. This makes troubleshooting issues with users somewhat impossible in production due to log volume.

**Expected behavior**

401 responses due to JWT policy failure should include the WWW-Authenticate header:

```
HTTP/1.1 401 Unauthorized
  WWW-Authenticate: error="invalid_token",
    error_description="The Access Token expired"
```

**Steps to reproduce the bug**

Inspect the output of a JWT policy validation. Notice the response does not include a WWW-Authenticate header, nor does it include details about the failure reason.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
$ istioctl version --remote
client version: unknown
accounts-mp-ilbgateway version:
accounts-mp-ilbgateway version:
commerce-elbgateway version:
commerce-elbgateway version:
etnc-prototype-ilbgateway version:
etnc-prototype-ilbgateway version:
citadel version: 1.4.6
galley version: 1.4.6
galley version: 1.4.6
pilot version: 1.4.6
pilot version: 1.4.6
pilot version: 1.4.6
pilot version: 1.4.6
pilot version: 1.4.6
pilot version: 1.4.6
pilot version: 1.4.6
pilot version: 1.4.6
pilot version: 1.4.6
pilot version: 1.4.6
policy version: 1.4.6
policy version: 1.4.6
policy version: 1.4.6
policy version: 1.4.6
policy version: 1.4.6
policy version: 1.4.6
policy version: 1.4.6
policy version: 1.4.6
policy version: 1.4.6
policy version: 1.4.6
sidecar-injector version: 1.4.6
sidecar-injector version: 1.4.6
telemetry version: 1.4.6
telemetry version: 1.4.6
telemetry version: 1.4.6
telemetry version: 1.4.6
telemetry version: 1.4.6
telemetry version: 1.4.6
telemetry version: 1.4.6
telemetry version: 1.4.6
telemetry version: 1.4.6
telemetry version: 1.4.6
telemetry version: 1.4.6
telemetry version: 1.4.6
telemetry version: 1.4.6
telemetry version: 1.4.6
telemetry version: 1.4.6
telemetry version: 1.4.6
telemetry version: 1.4.6
telemetry version: 1.4.6
telemetry version: 1.4.6
telemetry version: 1.4.6
m-prototype-ilbgateway version:
m-prototype-ilbgateway version:
m-prototype-ilbgateway version:
m-prototype-ilbgateway version:
m-prototype-ilbgateway version:
m-prototype-ilbgateway version:
m-prototype-ilbgateway version:
m-prototype-ilbgateway version:
m-prototype-ilbgateway version:
m-prototype-ilbgateway version:
mhite-elbgateway version:
mhite-elbgateway version:
mhite-elbgateway version:
mhite-ilbgateway version:
mhite-ilbgateway version:
monolith-ilbgateway version:
monolith-ilbgateway version:
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-13T11:51:44Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.17", GitCommit:"bdceba0734835c6cb1acbd1c447caf17d8613b44", GitTreeState:"clean", BuildDate:"2020-01-17T23:10:13Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

We install Istio using helm charts.

**Environment where bug was observed (cloud vendor, OS, etc)**

We are running open source Istio 1.4.6 on Google Kubernetes Engine (GKE).

**Comment by yangminzhu** [comment]
> Unfortunately the response does not include the expected WWW-Authenticate header.[1]
>
> [1] - https://tools.ietf.org/html/rfc6750#section-3
>
> It would be fantastic to support errors here, too. IE:
>
> HTTP/1.1 401 Unauthorized
>  WWW-Authenticate: error="invalid_token",
>    error_description="The Access Token expired"

The RFC applies to OAuth 2.0 but I think the Envoy JWT filter is only doing a general JWT token verification, which is not equivalent to OAuth?


> Specifically, it would be nice to propagate these error codes:
>
>  https://github.com/google/jwt_verify_lib/blob/master/src/status.cc
>
> (Envoy uses jwt_verify_lib)
> Right now, to even see these, you have to turn on Istio DEBUG logs. This makes troubleshooting issues with users somewhat impossible in production due to log volume.

I think there was a recent update in Envoy JWT filter to propagate these error right in the HTTP response? cc @qiwzhang

**Comment by mhite** [comment]
> > Unfortunately the response does not include the expected WWW-Authenticate header.[1]
> > [1] - https://tools.ietf.org/html/rfc6750#section-3
> > It would be fantastic to support errors here, too. IE:
> > HTTP/1.1 401 Unauthorized
> > WWW-Authenticate: error="invalid_token",
> > error_description="The Access Token expired"
> 
> The RFC applies to OAuth 2.0 but I think the Envoy JWT filter is only doing a general JWT token verification, which is not equivalent to OAuth?

I can certain understand its absence, especially if the intent is really a "minimum viable" implementation. I'm viewing this from the lens of using it in a larger OIDC and OAuth framework and it would be great to surface other related headers when a 401 is returned. Right now we'd don't really have any options to bring it into specification to frameworks which utilize JWT.

> > Specifically, it would be nice to propagate these error codes:
> > https://github.com/google/jwt_verify_lib/blob/master/src/status.cc
> > (Envoy uses jwt_verify_lib)
> > Right now, to even see these, you have to turn on Istio DEBUG logs. This makes troubleshooting issues with users somewhat impossible in production due to log volume.
> 
> I think there was a recent update in Envoy JWT filter to propagate these error right in the HTTP response? cc @qiwzhang

That would be fantastic. Any pointers to this? Much appreciated.

**Comment by yangminzhu** [comment]
> Yes, it would be great if you share the link to this update in Envoy JWT filter. I am facing the same problem as well, just that I am using Istio v1.5.1 to test the JWT Authorization feature (using OAuth2 protocol). If an invalid token is used, I get Error 401 Unauthorized, but the WWW-Authenticate header is missing in the HTTP Response.
> 
> FYI : Envoy version 1.13.1 is being used in the sidecar proxy.

Oh, the jwt filter doesn't set the "WWW-Authenticate" header, see https://github.com/envoyproxy/envoy/blob/master/source/extensions/filters/http/jwt_authn/filter.cc#L92-L97 for the 401 response.

**Comment by sha-rath** [comment]
Oh ok, it is quite crucial for me. @yangminzhu do you have any idea how soon this could be fixed? 
Thanks.

**Comment by yangminzhu** [comment]
@mhite  The error message is returned in the body: https://github.com/envoyproxy/envoy/blob/2026ec2e3969c473662daeb775b1daecbbdf67e5/source/extensions/filters/http/jwt_authn/filter.cc#L98-L100

@sha-rath  I'm not sure if we should add the `WWW-Authenticate` header to the JWT filter but as this needs to be done in Envoy, can you open the issue in Envoy? thanks.

**Comment by nrjpoddar** [comment]
@yangminzhu this feature seems to be a blocker for offloading JWT validation in many use cases. Do you have any updates to share?

**Comment by yangminzhu** [comment]
> @yangminzhu this feature seems to be a blocker for offloading JWT validation in many use cases. Do you have any updates to share?

Oh, I'm actually not working on this but as I mentioned in previous response, I'm not sure if this should be added to the RequestAuthentication (or the jwt filter). The RequestAuthentication (or the jwt filter) is only doing general JWT token validation which is not the necessary the OAuth flow, even we add it in the JWT filter (cc @qiwzhang for opinions from Envoy side), we probably still shouldn't make this the default behavior in Istio.

**Comment by nrjpoddar** [comment]
It is not an OAuth specific feature but a part of [HTTP spec](https://en.m.wikipedia.org/wiki/Basic_access_authentication) afaik. Thanks for the update.

**Comment by sha-rath** [comment]
When I checked with the Envoy community, I was pointed to Local Reply Modification: https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/local_reply. So, I thought I could use EnvoyFilter to add the necessary header for the response that returns status 401. Maybe this is an option for now until is made the default behaviour?
