### ISSUE TITLE
pre-commit hook not functional

### ISSUE THREAD

**Issue by danehans** [istio/istio#2262]
According to the [dev guide](https://github.com/istio/istio/blob/master/DEV-GUIDE.md#enable-pre-commit-hook), the pre commit hook is not functional. Will this issue be fixed or will the pre commit hook be removed? The current state causes confusion for dev on-boarding.

**Comment by danehans** [comment]
@sdake It's good to know the hook works for you. This issue to to get clarification on the following text from the dev guide:

> NOTE: The precommit hook is not functional as of 11/08/2017 following the repo reorganization. It should come back alive shortly.

Since the guide states the above, I did not install the hook. If you have verified the hook works, do you want to submit a PR to update the dev guide?

**Comment by sdake** [comment]
I haven't verified the hook works when submitting; simply when installing.  Either the guide needs to change (if it has been resolved) or the pre-commit hook needs to be fixed.  Can you please validate that the pre-commit hook is broken on commit.

Cheers
-stedve

**Comment by danehans** [comment]
I'll test on my next commit.

**Comment by hklai** [comment]
Obsolete in favor of the new issue.
