### ISSUE TITLE
istio 1.5.1 operator creates PodDisruptionBudgets with wrong release matchLabel

### ISSUE THREAD

**Issue by zenvdeluca** [istio/istio#22636]
installed istio 1.5.1 using the standalone operator and the PodDisruptionBudget resources are being created with wrong release matchLabels

see here:

```
$ kubectl describe pdb -n istio-system istiod
Name:           istiod
Namespace:      istio-system
Min available:  1
Selector:       app=istiod,istio=pilot,release=istio
Status:
    Allowed disruptions:  0
    Current:              0
    Desired:              1
    Total:                0
Events:
  Type    Reason  Age                  From               Message
  ----    ------  ----                 ----               -------
  Normal  NoPods  2m (x282 over 142m)  controllermanager  No matching pods found
```

```
$ kubectl get pods -l app=istiod,istio=pilot,release=istio -n istio-system
No resources found in istio-system namespace.
```
```
$  kubectl get pods -l app=istiod,istio=pilot -n istio-system
NAME                      READY   STATUS    RESTARTS   AGE
istiod-7796df689b-gszpm   1/1     Running   0          146m
istiod-7796df689b-t856f   1/1     Running   0          168m
istiod-7796df689b-wj52x   1/1     Running   0          176m
```

**Expected behavior**
PodDisruptionBudgets should properly match istiod, citadel and ingressgateway labels

**Steps to reproduce the bug**
install istio 1.5.1 using standalone operator
`kubectl describe pdb -n istio-system istiod`
verify pdb has no matching pods found

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istio-1.5.1

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS, Ubuntu / Kubernetes / aws-cni plugin

cc: @uthark

**Comment by howardjohn** [comment]
https://github.com/istio/istio/pull/22291 should fix this

**Comment by howardjohn** [comment]
Going under the assumption that #22291 fixes this, please reopen if this is not the case. Thanks!
