### ISSUE TITLE
ControlPlaneAuthPolicy always TLS even when --set meshConfig.defaultConfig.controlPlaneAuthPolicy=NONE

### ISSUE THREAD

**Issue by wangfakang** [istio/istio#22640]
**Bug description**
`ControlPlaneAuthPolicy` always `TLS` even when` --set meshConfig.defaultConfig.controlPlaneAuthPolicy=NONE`.

**To reproduce**

istioctl  manifest apply  --set meshConfig.defaultConfig.controlPlaneAuthPolicy=NONE

then generate config `/etc/istio/proxy/envoy-rev0.json`  as follows：

```
   {
        "name": "xds-grpc",
        "type": "STRICT_DNS",
        "dns_refresh_rate": "300s",
        "dns_lookup_family": "V4_ONLY",
        "connect_timeout": "10s",
        "lb_policy": "ROUND_ROBIN",

        "tls_context": {
          "common_tls_context": {
            "alpn_protocols": [
              "h2"
            ],

             "tls_certificate_sds_secret_configs":[
              {
                "name":"default",
                "sds_config":{
                  "api_config_source":{
                    "api_type":"GRPC",
                    "grpc_services":[
                      {
                        "envoy_grpc":{
                          "cluster_name": "sds-grpc"
                        }
                      }
                    ]
                  }
                }
              }
            ],
            "validation_context": {
              "trusted_ca": {

                "filename": "./var/run/secrets/istio/root-cert.pem"

              },
              "verify_subject_alt_name": ["istio-pilot.istio-system.svc"]
            }

          },
        },
```
**istio version**
1.5.0

**Comment by howardjohn** [comment]
Very likely the same root cause as https://github.com/istio/istio/issues/22347

**Comment by howardjohn** [comment]
Closing as a duplicat of https://github.com/istio/istio/issues/22347. We are hoping to have a fix for this soon

**Comment by wangfakang** [comment]
@howardjohn This problem still exists in istio-1.5.2.

**Comment by wangfakang** [comment]
Same issue in istioctl-1.6.0-alpha.2.
```
master $ ./istioctl  version
client version: 1.6.0-alpha.2
control plane version: 1.6.0-alpha.2
data plane version: 1.6.0-alpha.2 (2 proxies)
```

**Comment by howardjohn** [comment]
@wangfakang if the discovery address port is 15012, we will automatically set up TLS settings, because pilot listens on TLS for port 15012. I have verified with  `--set meshConfig.defaultConfig.controlPlaneAuthPolicy=NONE --set meshConfig.defaultConfig.discoveryAddress=istiod.istio-system.svc:15010` this works. Can you test that out? Did you have some other use case?

**Comment by wangfakang** [comment]
@howardjohn It works in `istio-1.6.x`, But `Istio-1.5.x` still not works.
BTW, Why the discovery's port is not depend on the value of ` controlPlaneAuthPolicy`?

**Comment by wangfakang** [comment]
ping @howardjohn
