### ISSUE TITLE
Set resource limit when using sidecar.istio.io/proxyCPU

### ISSUE THREAD

**Issue by ckcd** [istio/istio#22644]
**Describe the feature request**
For now in injector, we only set `resources.request` for istio-proxy when using `sidecar.istio.io/proxyCPU` and `sidecar.istio.io/proxyMemory` annotations. And no any `resources.limit`.

This will make some metrics miss, e.g. `container_spec_memory_limit_bytes` which makes trouble in monitor.

So can we add `resources.limit` in this situation? 

**Describe alternatives you've considered**
two methods:

1. using two new annotations, maybe `sidecar.istio.io/proxyCPULimit` & `sidecar.istio.io/proxyMemoryLimit` or whatever;
2. reuse `sidecar.istio.io/proxyCPU` and `sidecar.istio.io/proxyMemory` to set both `resources.request` and `resources.limit`.

**Comment by hzxuzhonghu** [comment]
This is done recently #22395
