### ISSUE TITLE
5% Pilot CPU regression on vhost validation

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#22648]
https://github.com/envoyproxy/envoy/pull/10093 added some regex validation to vhost, which we then call at https://github.com/istio/istio/blob/master/pilot/pkg/proxy/envoy/v2/rds.go#L60, which leads to about 5% of pilot CPU spent on this. This validation is pretty not useful, as we just increment a metric then send it to Envoy which rejects it, which we then increment a "rejected" metric. So even the metric isn't really useful?

Seems like we should just stop validating and let Envoy do it?

cc @kyessenov @hzxuzhonghu any thoughts?

**Comment by kyessenov** [comment]
Why do we need to validate more than once? Just skip it the second time.

**Comment by howardjohn** [comment]
We only validate once, then we send it to envoy which also validates and sends a NACK. At least I think thats how it works

**Comment by kyessenov** [comment]
So there're two things wrong:
1. We shouldn't send invalid config to Envoy. There's just no point in that, unless you're trying to crash them or add more CPU usage.
2. Pilot should validate once per resource and not whenever xDS is requested.

**Comment by howardjohn** [comment]
> Pilot should validate once per resource and not whenever xDS is requested.

Pilot doesn't do any caching, every request generates a new response. maybe that's a broader issue, but not specifically something that can just be fixed for validation

As far as I not sending them, I am not sure the context behind this. Seems reasonable.. we used to panic in pilot which was clearly wrong. Although I am not sure we want to do validation on pilot side and not envoy side, as the go-control-plane library may not match the connected proxy

**Comment by kyessenov** [comment]
Ok, but I think it's incorrect to blame the validation for performance degradation. There are basic flaws in pilot implementation that make any additional work done for xDS amplified. It's not the extra work that's the issue.

**Comment by howardjohn** [comment]
I am not making a claim that envoy did something wrong by changing the validation or anything like that. Just that we have a 5% perf regression that we should probably fix

**Comment by hzxuzhonghu** [comment]
@howardjohn IMO, as the validate in pilot does nothing except recording a metric, we can leave the validation to envoy.  And that is what we do with other xds now.

**Comment by hzxuzhonghu** [comment]
More what we can do is add  test cases covering validation

**Comment by ramaraochavali** [comment]
I think we should skip validation in Pilot and let Envoy validate it and only have rejected metric incremented. I do not see a value of `rdsBuildErrPushes` which would always be equal to the xdsRejects

We can call validate in tests as @hzxuzhonghu as one of the additional pass criteria in the test.

**Comment by ramaraochavali** [comment]
I will fix this and add tests etc.
