### ISSUE TITLE
Make config controllers compatible with each other

### ISSUE THREAD

**Issue by seflerZ** [istio/istio#22663]
Today we initialize config controllers with mutual exclusion. That is to say, if we have one "ConfigSource" configured, we do not initialize others. I don't think it's good because sometimes, we do want to initialize more than one kind.

How about removing the "if-else" clause and make an aggregate config controller for them?

```go
func (s *Server) initConfigController(args *PilotArgs) error {
	meshConfig := s.environment.Mesh()
	if len(meshConfig.ConfigSources) > 0 {
		// Using MCP for config.
		if err := s.initMCPConfigController(args); err != nil {
			return err
		}
	} else if args.Config.FileDir != "" {
		store := memory.Make(collections.Pilot)
		configController := memory.NewController(store)

		err := s.makeFileMonitor(args.Config.FileDir, configController)
		if err != nil {
			return err
		}
		s.ConfigStores = append(s.ConfigStores, configController)
	} else {
		configController, err := s.makeKubeConfigController(args)
		if err != nil {
			return err
		}
		s.ConfigStores = append(s.ConfigStores, configController)
		if features.EnableServiceApis {
			s.ConfigStores = append(s.ConfigStores, gateway.NewController(s.kubeClient, configController))
		}
		if features.EnableAnalysis {
			if err := s.initInprocessAnalysisController(args); err != nil {
				return err
			}
		}
	}
...
```

**Comment by hzxuzhonghu** [comment]
IIRC, we do support multiple mcp sources previously. Not quite sure now

**Comment by hzxuzhonghu** [comment]
https://github.com/istio/istio/blob/504e17395450b26d26f322c5b197771f09d21e21/pilot/pkg/bootstrap/configcontroller.go#L154-L183

@seflerZ  It is still there.

**Comment by seflerZ** [comment]
I know, but it's the MCP kind. Suppose I want to use both the fileDir and MCP kind. How to do that?

**Comment by seflerZ** [comment]
The code now already appends ConfigStore to a list named "s.ConfigStores". I think we simply need to remove the "if-else" clause.
