### ISSUE TITLE
MeshExpansion - VM Reboot destroys expanded mesh

### ISSUE THREAD

**Issue by peter-fe** [istio/istio#22665]
**Bug description**
A VM added to the mesh is not able to reconnect after reboot.
The reason is that the istio.service looks up the /var/run/secrets/istio/root-cert.pem path during startup.
/var/run is a tempfs that gets cleared during a reboot.

**Expected behavior**
The expanded mesh also survives reboots of VMs

**Steps to reproduce the bug**
After a successful single mesh expansion restart the VM running the istio.service

```
cat /var/log/istio/istio.err.log 
[Envoy (Epoch 0)] [2020-04-02 10:36:04.222][1256][critical][main] [external/envoy/source/server/server.cc:96] error initializing configuration '/etc/istio/proxy/envoy-rev0.json': Invalid path: ./var/run/secrets/istio/root-cert.pem
Invalid path: ./var/run/secrets/istio/root-cert.pem
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
client version: 1.5.1
control plane version: 1.5.1
data plane version: 1.5.1 (2 proxies)
```

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.9-gke.22", GitCommit:"9bae7fcacb520dfee658b26cc1a9643bf787dfc3", GitTreeState:"clean", BuildDate:"2020-02-27T18:43:37Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
`istioctl manifest apply -f values.yaml`
[https://istio.io/docs/examples/virtual-machines/single-network/](https://istio.io/docs/examples/virtual-machines/single-network/)

**Environment where bug was observed (cloud vendor, OS, etc)**
GCP/GKE

**Comment by irisdingbj** [comment]
This has been fixed in latest upstream, you can put required certs, eg: root-certs, cert-chain, etc  
via `PROV_CERT` via `sidecar.env`

**Comment by peter-fe** [comment]
@irisdingbj 

Do you have some more detail on this? Commit, pull or merge request?

My best guess would be, regarding the information you provided, that I can override the default folder path (/var/run/secrets) with something else using PROV_CERT in sidecar.env?

Why isn't /etc/certs enough as location as in previous versions?
