### ISSUE TITLE
Diff rendered manifest changes with a make target.

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#22660]
https://github.com/istio/istio/pull/22565 disconnects golden files from installation templates. This ensures that every change in template does not lead  to a merge conflict.
Doing so we have lost to ability to visually inspect changes to templates.

Requirement
Give reviewers the ability to inspect changes in rendered template during PR review.

1. run `make gen` or equivalent and produce rendered templates in post submit.
   Make these available as build artifacts.
2. Create a `make gen-diff`  that runs `make gen` locally and diffs it against the base revision of the PR. These contents should be available due to step 1.
3. Post the diff back to PR, similar to how code review posts back.

**Comment by mandarjog** [comment]
cc @ostromart @howardjohn @costinm

**Comment by howardjohn** [comment]
related: https://github.com/kubernetes/test-infra/issues/17056
