### ISSUE TITLE
Kiali pod status ImagePullBackOff

### ISSUE THREAD

**Issue by anoophp777** [istio/istio#22672]
**I'm trying to install Istio and access Kiali in my local Mac on Docker Kubernetes. Kiali pod status is ImagePullBackOff. 

`kubectl get pods -n istio-system
NAME                                    READY   STATUS             RESTARTS   AGE
grafana-78bc994d79-zdr25                1/1     Running            0          27m
istio-egressgateway-5b5d88f7ff-j6cgc    1/1     Running            0          27m
istio-ingressgateway-75877dc5bf-v9szn   1/1     Running            0          27m
istio-tracing-c7b59f68f-kp2zj           1/1     Running            0          27m
istiod-6b69865db8-6n68l                 1/1     Running            0          27m
kiali-7ff568c949-r8f9k                  0/1     ImagePullBackOff   0          27m
prometheus-584757d974-t2qbb             2/2     Running            0          27m`

**

**Kiali Dashboard visible and Pod is Running**

**Follow the steps to install Istio latest version from https://istio.io/docs/setup/getting-started/**

**1.5.1**

**istioctl**

**Mac OS**

**Comment by howardjohn** [comment]
Please run `kubectl describe` on the pod so we can see what image its pulling

**Comment by anoophp777** [comment]
I get this:

```
kubectl describe pod kiali-7ff568c949-t47l9  
Error from server (NotFound): pods "kiali-7ff568c949-t47l9" not found
```

**Comment by anoophp777** [comment]
I get this:

```
kubectl describe pod kiali-7ff568c949-t47l9  -n istio-system
Name:               kiali-7ff568c949-t47l9
Namespace:          istio-system
Priority:           0
PriorityClassName:  <none>
Node:               docker-desktop/192.168.65.3
Start Time:         Fri, 03 Apr 2020 16:58:48 +0530
Labels:             app=kiali
                    pod-template-hash=7ff568c949
                    release=istio
Annotations:        kiali.io/runtimes: go,kiali
                    prometheus.io/port: 9090
                    prometheus.io/scrape: true
                    scheduler.alpha.kubernetes.io/critical-pod: 
                    sidecar.istio.io/inject: false
Status:             Pending
IP:                 10.1.0.244
Controlled By:      ReplicaSet/kiali-7ff568c949
Containers:
  kiali:
    Container ID:  
    Image:         quay.io/kiali/kiali:v1.15
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      /opt/kiali/kiali
      -config
      /kiali-configuration/config.yaml
      -v
      3
    State:          Waiting
      Reason:       ErrImagePull
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:      10m
    Liveness:   http-get http://:20001/kiali/healthz delay=5s timeout=1s period=30s #success=1 #failure=3
    Readiness:  http-get http://:20001/kiali/healthz delay=5s timeout=1s period=30s #success=1 #failure=3
    Environment:
      ACTIVE_NAMESPACE:  istio-system (v1:metadata.namespace)
    Mounts:
      /kiali-cert from kiali-cert (rw)
      /kiali-configuration from kiali-configuration (rw)
      /kiali-secret from kiali-secret (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kiali-service-account-token-2sq6c (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  kiali-configuration:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      kiali
    Optional:  false
  kiali-cert:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  istio.kiali-service-account
    Optional:    true
  kiali-secret:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kiali
    Optional:    true
  kiali-service-account-token-2sq6c:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kiali-service-account-token-2sq6c
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason       Age                   From                     Message
  ----     ------       ----                  ----                     -------
  Normal   Scheduled    36m                   default-scheduler        Successfully assigned istio-system/kiali-7ff568c949-t47l9 to docker-desktop
  Warning  FailedMount  36m                   kubelet, docker-desktop  MountVolume.SetUp failed for volume "kiali-configuration" : couldn't propagate object cache: timed out waiting for the condition
  Normal   Pulling      35m (x4 over 36m)     kubelet, docker-desktop  Pulling image "quay.io/kiali/kiali:v1.15"
  Warning  Failed       35m (x4 over 36m)     kubelet, docker-desktop  Failed to pull image "quay.io/kiali/kiali:v1.15": rpc error: code = Unknown desc = Error response from daemon: Get https://quay.io/v2/: remote error: tls: handshake failure
  Warning  Failed       35m (x4 over 36m)     kubelet, docker-desktop  Error: ErrImagePull
  Normal   BackOff      11m (x108 over 36m)   kubelet, docker-desktop  Back-off pulling image "quay.io/kiali/kiali:v1.15"
  Warning  Failed       106s (x153 over 36m)  kubelet, docker-desktop  Error: ImagePullBackOff
```

**Comment by howardjohn** [comment]
If i run `docker pull quay.io/kiali/kiali:v1.15` it works, so seems like an issue with your cluster (or maybe quay.io had some outage?).

>  remote error: tls: handshake failure

seems to be the relevant error

**Comment by anoophp777** [comment]
Yes. If I do docker pull, I'm getting this.

```
docker pull quay.io/kiali/kiali:v1.15
Error response from daemon: Get https://quay.io/v2/: remote error: tls: handshake failure
```

Is there a workaround you can suggest @howardjohn?

**Comment by howardjohn** [comment]
I am not sure, I believe this is an issue with your k8s cluster or quay,
neither of which I am an expert in

**Comment by anoophp777** [comment]
@howardjohn I used helm to install Istio and its working perfectly fine. But the version 1.5.1 is acting up. Version 1.1.11 seems to be very stable. 

I hope helm 1.5.1 is fixed in the next iteration.

**Comment by howardjohn** [comment]
`docker pull quay.io/kiali/kiali:v1.15` works on my machine as well as most users clusters (as others run Kiali fine). This seems very likely a weird issue with your Kubernetes cluster (or quay). In either case, I am not sure the istio team can help here. Thanks!

**Comment by alexichepura** [comment]
quay.io outages
https://status.quay.io/history

**Comment by mhus** [comment]
I have the same problem:

docker pull quay.io/kiali/kiali:v1.15
Error response from daemon: Get https://quay.io/v2/kiali/kiali/manifests/v1.15: received unexpected HTTP status: 500 Internal Server Error

**Comment by mhus** [comment]
And the server is offline again ....

**Comment by djamaile** [comment]
Ah server is offline, I already thought what is going on

**Comment by ForrestSu** [comment]
And the server is offline again ....

**Comment by boguima** [comment]
I'm having a similar problem. Can you please help me?

`Name:         kiali-699f98c497-rm6cz
Namespace:    istio-system
Priority:     0
Node:         minikube/192.168.49.2
Start Time:   Mon, 11 Apr 2022 22:46:36 -0300
Labels:       app=kiali
              app.kubernetes.io/instance=kiali
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=kiali
              app.kubernetes.io/part-of=kiali
              app.kubernetes.io/version=v1.45.0
              helm.sh/chart=kiali-server-1.45.0
              pod-template-hash=699f98c497
              sidecar.istio.io/inject=false
              version=v1.45.0
Annotations:  checksum/config: 0b7a16e51830df3ef2ff816eb3d43341a23c822b38fea95050b3707ba2ca119e
              kiali.io/dashboards: go,kiali
              prometheus.io/port: 9090
              prometheus.io/scrape: true
Status:       Pending
IP:           172.17.0.12
IPs:
  IP:           172.17.0.12
Controlled By:  ReplicaSet/kiali-699f98c497
Containers:
  kiali:
    Container ID:  
    Image:         quay.io/kiali/kiali:v1.45
    Image ID:      
    Ports:         20001/TCP, 9090/TCP
    Host Ports:    0/TCP, 0/TCP
    Command:
      /opt/kiali/kiali
      -config
      /kiali-configuration/config.yaml
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Limits:
      memory:  1Gi
    Requests:
      cpu:      10m
      memory:   64Mi
    Liveness:   http-get http://:api-port/kiali/healthz delay=5s timeout=1s period=30s #success=1 #failure=3
    Readiness:  http-get http://:api-port/kiali/healthz delay=5s timeout=1s period=30s #success=1 #failure=3
    Environment:
      ACTIVE_NAMESPACE:       istio-system (v1:metadata.namespace)
      LOG_LEVEL:              info
      LOG_FORMAT:             text
      LOG_TIME_FIELD_FORMAT:  2006-01-02T15:04:05Z07:00
      LOG_SAMPLER_RATE:       1
    Mounts:
      /kiali-cabundle from kiali-cabundle (rw)
      /kiali-cert from kiali-cert (rw)
      /kiali-configuration from kiali-configuration (rw)
      /kiali-secret from kiali-secret (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-vn8fp (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  kiali-configuration:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      kiali
    Optional:  false
  kiali-cert:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  istio.kiali-service-account
    Optional:    true
  kiali-secret:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kiali
    Optional:    true
  kiali-cabundle:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      kiali-cabundle
    Optional:  true
  kube-api-access-vn8fp:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                 From               Message
  ----     ------     ----                ----               -------
  Normal   Scheduled  31m                 default-scheduler  Successfully assigned istio-system/kiali-699f98c497-rm6cz to minikube
  Normal   Pulling    24m (x4 over 31m)   kubelet            Pulling image "quay.io/kiali/kiali:v1.45"
  Warning  Failed     23m (x4 over 29m)   kubelet            Error: ErrImagePull
  Warning  Failed     23m (x7 over 29m)   kubelet            Error: ImagePullBackOff
  Warning  Failed     10m (x7 over 29m)   kubelet            Failed to pull image "quay.io/kiali/kiali:v1.45": rpc error: code = Unknown desc = Error response from daemon: Get https://quay.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  Normal   BackOff    54s (x83 over 29m)  kubelet            Back-off pulling image "quay.io/kiali/kiali:v1.45"`
  
  
  Already the docker image downloads successfully.
  `quay.io/kiali/kiali                          v1.15                  f631a10671d2   24 months ago   154MB`

I suspect the outbound traffic is compromised, either by istio or minikube! But I don't know how to check.

**Comment by zirain** [comment]
try `docker pull quay.io/kiali/kiali:v1.45` on you node or something, I don't think that istio will block kebelet pull image.

**Comment by boguima** [comment]
@zirain thanks for replying!
I'm running local minikube on OS, linux. How do I ask to run node docker command from within node?
Apologies for the lack of skills.

**Comment by boguima** [comment]
See what you can collect from the ingress pod:

> bruno@bruno-ThinkPad-E14:~$ kubectl exec -n istio-system istio-ingressgateway-54776864bd-zg5j6 -it /bin/bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
istio-proxy@istio-ingressgateway-54776864bd-zg5j6:/$ curl quay.io/kiali/kiali:v1.45
^C
istio-proxy@istio-ingressgateway-54776864bd-zg5j6:/$ curl -vvv quay.io/kiali/kiali:v1.45
* Could not resolve host: quay.io
* Closing connection 0
curl: (6) Could not resolve host: quay.io
istio-proxy@istio-ingressgateway-54776864bd-zg5j6:/

Here's what I can collect from my local machine:

> bruno@bruno-ThinkPad-E14:~/Downloads/istio$ curl quay.io/kiali/kiali:v1.45
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
</body>
</html>


Não diz muito mais, mas, pode servir como comparação

**Comment by boguima** [comment]
@zirain indeed istio was not blocking the kubelet.
After the tests above realize that the problem was on my node!

Here is the resolution, when using minikube:
https://minikube.sigs.k8s.io/docs/handbook/addons/ingress-dns/

Thank you very much. Hope the comment helps the next one!
