### ISSUE TITLE
cni enabled: InitContainer fails pod security policy with readOnlyRootFilesystem=false

### ISSUE THREAD

**Issue by wandrar** [istio/istio#22695]
**Bug description**
Fresh install of kubernetes on GKE with pod security policies enabled. Installed Istio 1.5.1 with cni enabled as per instructions (including platform setup firewall change):-

istioctl manifest apply --set values.cni.cniBinDir=/home/kubernetes/bin \
    --set components.cni.enabled=true \
    --set components.cni.namespace=kube-system

My pod security policy for app pods has restriction of readOnlyRootFilesystem=true.

Deployed app fails to start with..

pods "load-68b699c7bb-" is forbidden: unable to validate against any pod security policy: [spec.initContainers[0].securityContext.readOnlyRootFilesystem: Invalid value: false: ReadOnlyRootFilesystem must be set to true]

On face of it, looks like istio-validation initcontainer has readOnlyRootFilesystem: false.

**Expected behavior**

With cni enabled, I expected the initcontainer not to require elevated permissions.

**Steps to reproduce the bug**

See above

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

istioctl...

client version: 1.5.1
control plane version: 1.5.1
data plane version: 1.5.1 (2 proxies)

kubectl...

Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.27", GitCommit:"145f9e21a4515947d6fb10819e5a336aff1b6959", GitTreeState:"clean", BuildDate:"2020-02-21T18:01:40Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**

istioctl 1.5.1 on Windows 10 in powershell window. Also tried in GKE CloudShell.

**Environment where bug was observed (cloud vendor, OS, etc)**

Client: Windows 10 and GKE CloudShell. against GKE

**Comment by howardjohn** [comment]
cc @lambdai I think you were working on a similar issue? Or @rlenglet

**Comment by rlenglet** [comment]
@wandrar can you please post a comment with the pod spec of one failing pod?

**Comment by rlenglet** [comment]
The `istio-proxy` always had [`readOnlyRootFilesystem: false`](https://github.com/istio/istio/blob/release-1.5/manifests/istio-control/istio-discovery/files/injection-template.yaml#L348).
But the `istio-init` container was never set with that setting.

The change to inject `istio-init` when Istio CNI is enabled is a recent change to work around Istio CNI not being ready sometimes when a pod starts.

So the fix would be to add `readOnlyRootFilesystem: false` to `istio-init`, at least when Istio CNI is enabled since the container does very little in that case, and doesn't need to write into the filesystem.

**Comment by rlenglet** [comment]
Hmmm that's weird. In the `release-1.5` branch, this is already OK: https://github.com/istio/istio/blob/release-1.5/manifests/istio-control/istio-discovery/files/injection-template.yaml#L68

**Comment by rlenglet** [comment]
Keeping this issue open until the cherrypick into `release-1.5` is merged: https://github.com/istio/istio/pull/22736.
