### ISSUE TITLE
[Istio 1.5.1] Ingress/Egress gateway Readiness probe keeps on failing 

### ISSUE THREAD

**Issue by guyromb** [istio/istio#22697]
**Bug description**

Istio Ingress/Egress gateway ready probe is returning 503.

Gateway errors:
```
info Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 7 successful, 0 rejected; lds updates: 0 successful, 0 rejected
```

Removing the probe, making it obviously green, but also the error disappears (not sure if this errors is triggered only when calling 15020:/healthz/ready).

When changing values.global.k8sIngress.gatewayName it seems like Ingress becomes green again. Removing and istio-system namespace and re-installing sometimes fix the problem, but problem comes back after sometime.

No errors in Pilot (everything is green and functional). It seems like it is trying to Push LDS to gateway. But since gateway readiness probe is failing it does not accept any traffic, and gateway is failing because it didn't get an even from the Pilot. It looks like some kind of a cascaded failure to me. But I am not sure.

**Expected behavior**

Ingress/Egress gateway functional after fresh installation

**Steps to reproduce the bug**

Install Istio 1.5.1 with istioctl
```
istioctl manifest apply -f values-istio-multicluster-gateways.yaml --set values.kiali.enabled=true  --set values.global.tracer.zipkin.address=jaeger-collector.default:14268  --set values.pilot.traceSampling=1  --set values.global.proxy.accessLogFile="/dev/stdout"  --set values.gateways.istio-ingressgateway.sds.enabled=true  --set values.global.k8sIngress.enabled=true  --set values.global.k8sIngress.enableHttps=true  --set values.global.k8sIngress.gatewayName=ingressgateway --set values.grafana.enabled=false --set values.prometheus.enabled=false
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)** 1.5.1

**How was Istio installed?** istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

Related to https://github.com/istio/istio/issues/22309

**Comment by howardjohn** [comment]
> not sure if this errors is triggered only when calling 15020:/healthz/ready).

It is.


> It seems like it is trying to Push LDS to gateway.

Do you see a log like `LDS: PUSH for gateway....`? I suspect you see `CDS: PUSH for gateway` but not LDS? Can you add the logs?

**Comment by guyromb** [comment]
@howardjohn , it seems like it is fully solved when changing the k8singress name to something else than istiogateway. But now I am getting some weird 503. Here is how I install it: https://github.com/istio/istio/issues?q=is%3Aissue+is%3Aopen+internal

**Comment by SmartsYoung** [comment]
Can you procide the values-istio-multicluster-gateways.yaml?

**Comment by accountgit** [comment]
Same it's happening to me, empty cluster with the demo profile with istio 1.5.1 and 1.5.2 with a bare metal cluster made with kubespray with calico cni.
    istioctl manifest apply -w --log_output_level all:debug --set values.global.logging.level="all:debug" --set values.global.proxy.logLevel="debug" --set values.global.k8sIngress.enableHttps=true --set values.gateways.istio-ingressgateway.sds.enabled=true --set values.global.k8sIngress.enabled=true --set values.global.k8sIngress.gatewayName=ingressgateway --set values.tracing.enabled=true --set values.tracing.provider=jaeger --set profile=demo

with values.global.k8sIngress.gatewayName=ingressgateway change to values.global.k8sIngress.gatewayName=ingressgateway1 for example works correctly.

Is there something that I can make to debug the issue? 
It's my first time using istio.
