### ISSUE TITLE
Changing envoy zipkin bit tracing

### ISSUE THREAD

**Issue by michael-lancaster** [istio/istio#22702]
The 128 bit tracing of zipkin is interfering with one of my applications. Is there a way to change it to 64 bit?

**Comment by esnible** [comment]
I believe the only configuration option for Zipkin is the address of the Zipkin.
https://preliminary.istio.io/docs/reference/config/istio.mesh.v1alpha1/#Tracing-Zipkin

How is 128 bit tracing interfering with your app, and why will 64 bit fix it?

**Comment by michael-lancaster** [comment]
@esnible I'm working with Confluence and it isn't compatible with 128 bit tracing only 64 bit.

**Comment by objectiser** [comment]
@michael-lancaster This is currently hardcoded in the bootstrap config: https://github.com/istio/istio/blob/master/tools/packaging/common/envoy_bootstrap_v2.json#L600

**Comment by howardjohn** [comment]
you could use https://github.com/istio/istio/tree/master/samples/custom-bootstrap

**Comment by howardjohn** [comment]
Proper api is tracked in https://github.com/istio/istio/issues/24287. Workaround is mentioned above. I think we can close this. Thanks!
