### ISSUE TITLE
Istio support on arm64 architecture (namely to be used in a Raspbery Pi 4B cluster)

### ISSUE THREAD

**Issue by marouanabbessi** [istio/istio#22728]
Dear Istio Folks 

Thanks a lot for this great tool . 

I wonder if there is any document with clear steps around building Istio for arm64 architectures.

I know that there were few discussions around this topic , but it feels like there is no real willingness to officially support arm64 architectures .

Could you please supports us on this with clear well defined steps on how we can help in building this using our rbpi devices ? 

Thanks in advance for your help and dedication

**Comment by howardjohn** [comment]
Thanks for the interest, theres lots of discussion/ongoing work around this on https://github.com/istio/istio/issues/21094. Lets keep the conversation going there
