### ISSUE TITLE
Anonymized report on Istio feature use: istioctl x config_report

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#22723]
We would like to know which specific features of Istio are in use by an Istio deployment.
High level:
1. Know current feature use
2. Create anonymized report
3. Optionally upload the report to an istio / gcs bucket.

There are many benefit of knowing snapshots of current feature use.
1.  Measure feature uptake
2. Helpful during migration discussions
3. Helpful for CVEs 

UX:
*  `istioctl config_report --generate -f report.yaml`
Just like `istioctl analyze`, works on a directory or cluster. 
*  `istioctl config_report --upload --f report.yaml`
Uploads the generated report.

Options:
Count field presence of (important?) fields and their counts. 

Examples
 * How many `subsets` does a `virtual service` use?
 * How many `regex matches` does a `virtualservice use`
 * What type of patching the envoy filter use? INSERT_FIRST, INSERT_LAST etc.
 * How many `AuthorizationPolicy` use `deny` action

**Comment by mandarjog** [comment]
@costinm @nrjpoddar @diemtvu @richardwxn

**Comment by nrjpoddar** [comment]
Thanks @mandarjog for filing this enhancement. Few thoughts:

* Phone home feature is always useful and traditional proxies (and infra products) have added him in the past. One option would be to have constant monitoring via in-cluster component like "istiod/pilot/new addon component". Downside of that is, it's more invasive and won't work in air-gapped systems. Upside is it's very clear for any customer if they are sending any reports.
* Using "istioctl" based command which explicitly captures user's intent/permission is less invasive but at the same time might not give us the diversity and quantity of data we need. Using a tool command like this shifts the burden of phone home from an organizational permission to a user/operator level control which might not be acceptable to many users.

Overall I understand the intent and this feature is useful. Placing it in the correct component would be key specially for vendors where some customers might be ok to send their data to vendors based on agreement but will not agree on sending data to a public location however anonymized.

Last point is do you think putting this in 1.6 milestone is feasible given all the other features we have signed up for?

**Comment by mandarjog** [comment]
Moved it to 1.7, however, if we deliver it as `istioctl x` command we may be able to deliver it earlier.
