### ISSUE TITLE
Not receiving traffic on host name mismatch in url and header

### ISSUE THREAD

**Issue by rajarathnabalan** [istio/istio#22727]
I have few micro services say service1, service2, service3.
I am deploying these micro services in AKS with istio-1.4.4 for service mesh. I deployed each service on different pods. From pod of service1 I created a http request equivalent to below curl cmd

`curl 'http://service2/v1/url' --header 'Host: service3'`

Note: In this http request unfortunately I set wrong value for header 'Host'.

When I run this request, I am not receiving any traffic on service2 pod and also no error logs. But got empty response body with status code 404.
When I remove header 'Host' or set it to correct host name(service2), I am receiving traffic on service2 pod.
It seems like if host name in url differs from host name in header the request is getting dropped. 

Without proper response body and error log I had hard time to find the issue.

[ X] Networking

**Expected behavior**

Giving back proper response body or logging the error or both

**Version**
```
$ istioctl version --remote
client version: 1.4.4
control plane version: 1.4.4
data plane version: 1.4.4 (42 proxies)

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"c52f59bbba5fbf21fbb18e9a06f96e563fe4c20a", GitTreeState:"clean", BuildDate:"2020-01-31T20:00:26Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
[Following AKS istio install link](https://docs.microsoft.com/en-us/azure/aks/servicemesh-istio-install?pivots=client-operating-system-linux)

**Comment by howardjohn** [comment]
Http routing is based on the host header not the url

**Comment by rajarathnabalan** [comment]
> Http routing is based on the host header not the url

Then, I should receive traffic on service3 pod. But I am not receiving any traffic there too.

**Comment by howardjohn** [comment]
@rajarathnabalan plese post a config dump (https://github.com/istio/istio/wiki/Troubleshooting-Istio) and the Service for service2 and service3

**Comment by howardjohn** [comment]
I do not think we can proceed with debugging this issue without the info above. Please reopen if you can provide this. Thanks!
