### ISSUE TITLE
Fix the TestCertRotation flakes

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#22729]
https://prow.istio.io/view/gcs/istio-prow/logs/unit-tests_istio_postsubmit/2012

this has failed on other PRs as well, please skip this ASAP

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gcs/istio-prow/logs/unit-tests_istio_postsubmit/2063

**Comment by JimmyCYJ** [comment]
In https://prow.istio.io/view/gcs/istio-prow/logs/unit-tests_istio_postsubmit/2063, the test fails at verification  "rotation_test.go:81: Number of SDS updates at inbound listener should be greater than one, get 1"

The mTLS connection is configured to allow only one request, so number of requests is equal to number of mTLS connections. 
The cert rotation interval is 1 second, and the test keeps sending requests for 2 second, which is to ensure that cert is rotated and new cert will be used for setting mTLS connections.

From the test log, the flow is like this:
17:06:45.510944Z	info	sds	resource:inbound-sds new connection
17:06:47.065845Z	info	cache	GenerateSecret inbound-sds
17:06:47.066248Z	info	sds	resource:inbound-sds pushed key/cert pair to proxy
<The first SDS push for inbound-sds takes about 2 seconds>
17:06:47.121274Z	info	sds	resource:inbound-sds connection is terminated. <--closed by cert rotation
 17:06:47.225786Z	info	sds	resource:inbound-sds new connection
......
17:06:49.096086Z	info	ca	send back CSR success response
17:06:49.097628Z	info	cache	GenerateSecret outbound-sds
17:06:49.097982Z	info	sds	resource:outbound-sds pushed key/cert pair to proxy
17:06:49.210166Z	info	sds	resource:outbound-sds new connection
17:06:49.956055Z	info	ca	send back CSR success response
17:06:49.957922Z	info	cache	GenerateSecret outbound-sds
17:06:49.958260Z	info	sds	resource:outbound-sds pushed key/cert pair to proxy
......
17:06:50.124037Z     TestCertRotation fetches Envoy stats

The second SDS push is not finished yet and test verification is done. 
One option is to send more requests to let the second SDS push complete.

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/23194/unit-tests_istio/12280

**Comment by JimmyCYJ** [comment]
Oh, I removed the sds update stats in https://github.com/istio/istio/pull/23016, that breaks the test verification. I will skip this test for now.
