### ISSUE TITLE
pin Istio to validated Kubernetes versions

### ISSUE THREAD

**Issue by sdake** [istio/istio#22740]
A minimum pin is insufficient for `verify-install`. Instead, we should be pinning Kubernetes between a range of validated ranges.

**Comment by esnible** [comment]
@sdake Will this make it into 1.6.0?  1.6.x?

**Comment by esnible** [comment]
@sdake Will this make it into 1.7?

**Comment by sdake** [comment]
@esnible I'm afraid not. I have other commitments, and while this is a nice to have, I don't think it is a P0.

Cheers,
-steve

**Comment by howardjohn** [comment]
Fixed by https://github.com/istio/istio/pull/26145
