### ISSUE TITLE
Different integration test results when running in CI/CD versus running locally

### ISSUE THREAD

**Issue by lei-tang** [istio/istio#22746]
**Bug description**
The plugin_ca_key_cert_test in integ-security-k8s-tests_istio of https://github.com/istio/istio/pull/22671 passes on both minikube and GKE platforms when running locally. However, this integration test fails on the CI/CD pipeline with the following error:

=== FAILED: Setup: 'plugin_ca_key_cert_test' (failed deploying control plane to cluster 0: manifest apply failed: failed to apply manifests: failed to apply manifest with kubectl client: resources not ready after 5m0s: timed out waiting for the condition
Deployment/istio-system/istio-ingressgateway) ===

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[X ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
The running results (running locally through "go test" on minikube and GKE versus running on CI/CD) should be the same.

**Steps to reproduce the bug**
Running the plugin_ca_key_cert_test in integ-security-k8s-tests_istio locally through "go test -p 1 -v ./tests/integration/security/plugin_ca_key_cert/... -log_output_level=all:debug,tf:debug -timeout 30m --istio.test.env kube --istio.test.ci --istio.test.pullpolicy=Always --istio.test.kube.minikube --istio.test.hub=$HUB --istio.test.tag=$TAG --istio.test.nocleanup
" passes on both minikube and GKE platforms. However, this integration test fails on the CI/CD pipeline with the following error:

=== FAILED: Setup: 'plugin_ca_key_cert_test' (failed deploying control plane to cluster 0: manifest apply failed: failed to apply manifests: failed to apply manifest with kubectl client: resources not ready after 5m0s: timed out waiting for the condition
Deployment/istio-system/istio-ingressgateway) ===

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
Lastest master.

**How was Istio installed?**
"go test" installs Istio.

**Environment where bug was observed (cloud vendor, OS, etc)**
minikube, GKE

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
if you run `go test -p 1 -v ./tests/integration/security/plugin_ca_key_cert/...` its not going to do anything, it will default to the `native` environment and your test says `RequireEnvironment(environment.Kube).`, meaning if environment is `native` it will skip.

Try adding `--istio.test.env=kube`.

Additionally if you want to run exactly what is run in CI, including cluster creation, you can. On the log page look at "Prow Job Yaml" and you can see the command: ` prow/integ-suite-kind.sh test.integration.security.kube.presubmit` in this case

**Comment by howardjohn** [comment]
additionally yo can get the logs and see there are cert errors: https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/22671/integ-security-k8s-tests_istio/11076/artifacts/plugin-ca-key-cert-test-022b59e/_suite_context/istio-state-cluster-0-993626176/istio-ingressgateway-7f45d44c8b-w5wrq-istio-proxy.log From that "Artifacts" page

**Comment by lei-tang** [comment]
I have run the following test with "--istio.test.env kube" and it passes on minikube, kind, and GKE platforms but fails in CI/CD.

go test -p 1 -v ./tests/integration/security/plugin_ca_key_cert/... -log_output_level=all:debug,tf:debug -timeout 30m --istio.test.env kube --istio.test.ci --istio.test.pullpolicy=Always --istio.test.kube.minikube --istio.test.hub=$HUB --istio.test.tag=$TAG --istio.test.nocleanup

I have also tried to run "prow/integ-suite-kind.sh test.integration.security.kube.presubmit" locally, which has the following errors. Thus, I am not able to reproduce locally the errors in that  "Artifacts" page. 

2020-04-06T12:26:53.621804Z     info    ci      === FAILED: Deploy Istio [Suite=security] ===
2020-04-06T12:26:53.621859Z     error   ci      === Dumping Istio Deployment State...
2020-04-06T12:26:53.622259Z     error   ci      Error getting pods list via kubectl: Get https://127.0.0.1:32772/api/v1/names
paces/istio-system/pods: dial tcp 127.0.0.1:32772: connect: connection refused

**Comment by howardjohn** [comment]
@lei-tang I have also tried and I see the same issue that it passes locally but fails in CI. A common case for this is that in CI, before a job is run the PR will be rebased against master. When I do this localy, I see "CA certificate root-cert.pem found" error

**Comment by lei-tang** [comment]
@howardjohn Thank you! I have rebased the PR multiple times but the test results are still different (i.e., running locally succeeds versus running in CI fails).

In CI, after finishing running an integration test, does CI delete and recreate the cluster before running the next integration test? If not, CI may leave some resources of the previous test in the cluster, which may impact the running result of next tests.

Other than that, it is unclear to me why running "go test -p 1 -v ./tests/integration/security/plugin_ca_key_cert/... -log_output_level=all:debug,tf:debug -timeout 30m --istio.test.env kube --istio.test.ci --istio.test.pullpolicy=Always --istio.test.kube.minikube --istio.test.hub=$HUB --istio.test.tag=$TAG --istio.test.nocleanup" locally versus in CI generates different test results.

**Comment by howardjohn** [comment]
It doesn't delete the full cluster (and it should not, the tests would take forever if we did this). But it does (attempt) to clean everything up that was created during the tests. Its possible it doesn't fully clean things up as you mentioned though

**Comment by lei-tang** [comment]
Thank you for confirming that the cluster is not recreated for an integration test! 
When I run this test locally, to make sure the test is conducted in a clean environment, the test is running in a newly created cluster. Using an existing cluster versus using a newly created cluster may be related to the different running results. 

Suppose we have an experiment in CI that runs this integration test in a newly created cluster (for a clean test environment) and it passes, then such experiment will prove that CI's cleanup doesn't fully clean up the previous test and the left-over resources from the previous test impact the next test. I am not familiar with customizing CI to do such experiments though.

**Comment by howardjohn** [comment]
https://github.com/istio/istio/blob/cafade60a34389b78bd54db30a519b58d1d11284/tests/integration/tests.mk#L74

Replace ` ./tests/integration/$(subst .,/,$*)/...` with the test you want, and it will only run that one. So ` ./tests/integration/security/plugin_ca_key_cert/...`

**Comment by lei-tang** [comment]
@howardjohn Thank you! I have created the PR https://github.com/istio/istio/pull/22751 to do such experiment. I will update here when the experiment result comes out.

**Comment by lei-tang** [comment]
TestPluginCaKeyCert passes in https://github.com/istio/istio/pull/22751.
There is no difference for TestPluginCaKeyCert in https://github.com/istio/istio/pull/22751 and https://github.com/istio/istio/pull/22671. The only difference between https://github.com/istio/istio/pull/22751 and https://github.com/istio/istio/pull/22671 is that https://github.com/istio/istio/pull/22751 will create a clean test cluster for running TestPluginCaKeyCert whereas https://github.com/istio/istio/pull/22671 will reuse a cluster created for running a previous test.
The passing of TestPluginCaKeyCert in https://github.com/istio/istio/pull/22751 shows that the test failure of TestPluginCaKeyCert in https://github.com/istio/istio/pull/22671 is caused by CI not completely cleaning up the test cluster before running the test TestPluginCaKeyCert.

**Comment by lei-tang** [comment]
The test failure in https://github.com/istio/istio/pull/22671 is caused by CI not cleaning up a configmap (istio-ca-root-cert) left by a previous integration test. Based on discussion, https://github.com/istio/istio/pull/22671 is revised to clean up the configmap istio-ca-root-cert before running the test TestPluginCaKeyCert. With the revision, TestPluginCaKeyCert passes in https://github.com/istio/istio/pull/22671.
