### ISSUE TITLE
Support TLS setting for tracer Zipkin

### ISSUE THREAD

**Issue by hanahmily** [istio/istio#22741]
**Describe the feature request**
In some scenarios, users should set up TLS to encrypt the communication between isito-proxy and zipkin-server. If users use a self-signed CA, there's no chance to set it to cluster's tlscontext of Envoy. 

I would like to contribute this feature, and my current plan is to follow lightstep to add https://github.com/istio/istio/blob/master/manifests/global.yaml#L250-L251 to zipkin config. 

**Describe alternatives you've considered**

Another option is to copy https://github.com/istio/istio/blob/master/manifests/global.yaml#L185-L192, which looks like more functional than lightstep.

**Additional context**

**Comment by howardjohn** [comment]
> , and my current plan is to follow lightstep to add

This is not the right path I think, we do not want more vendor specific settings, instead we should have generic ones. There is also samples/custom-bootstrap. @mandarjog @douglas-reid any other ideas on how this should be configured? If not following the ALS stuff seems reasonable. We could even make this `tracingTlsSettings` or something instead of having ZipkinTlsSettings, LightStepTlsSettings, .... since you can only have one anyways (?)

**Comment by dio** [comment]
FWIW, https://github.com/envoyproxy/envoy/issues/9998 it tracks changes for making configuration of a tracing provider dynamic.

**Comment by hanahmily** [comment]
@howardjohn stackdirver is different from other tracers. It opts to `google_grpc` instead of a static cluster. We can't config TLS setting for it because its collector is a local agent that loads a pre-mounted CA file. I think it's why we didn't merge all of the addresses into a single one. So it looks like "ZipkinTlsSettings, LightStepTlsSettings, ...." is a more reasonable choice for now. 

@dio Thanks for your update. I think we can switch to a dynamic tracer after it's merged.

**Comment by hanahmily** [comment]
After some investigation about stackdriver(https://cloud.google.com/traffic-director/docs/configure-stackdriver), it should be combined with TrafficDirector. I find we don't have to set TLS for it:
 - If STS(Security token service) is disabled, stackDriver envoy plugin will take care of the connection between envoy and Trace service.
 - Else STS is enabled, the static bootstrap template will use a CA from `/etc/ssl/certs/ca-certificates.crt`. 
In the above two scenarios, users can't or haven't to set up SSL/TLS parameters. So I intend to add a tracing generic TLS node which affects most of the tracers except for the stackDriver. In another word, stackDriver tracer will ignore the generic TLS setting.
