### ISSUE TITLE
`make gen` issue when using clang (vs. gcc)

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio#22756]
**Bug description**

When using the following env vars on a Linux system, I was not able to run `make gen`:

```
CC="clang"
CXX="clang++"
```

This resulted in:

```
# runtime/cgo
exec: "clang": executable file not found in $PATH
Makefile.core.mk:339: recipe for target 'go-gen' failed
make[1]: *** [go-gen] Error 2
make: *** [Makefile:46: gen] Error 2
```

If I instead run: `CC=gcc Cxx=g++ make gen`, everything seems to work.

[ X ] Developer Infrastructure

**Expected behavior**

Works regardless with `clang`.

**Steps to reproduce the bug**

`$ CC=clang CXX=clang++ make gen`

**Environment where bug was observed (cloud vendor, OS, etc)**

`Linux <redacted> 5.2.17-1rodete3-amd64 #1 SMP Debian 5.2.17-1rodete3 (2019-10-21 > 2018) x86_64 GNU/Linux`

**Comment by howardjohn** [comment]
@sdake @ericvn we can probably just filter out those two env vars? not sure if ther is a better fix

**Comment by ericvn** [comment]
Makes sense to filter them to me.
