### ISSUE TITLE
tracing withnot-root-span

### ISSUE THREAD

**Issue by fujianan** [istio/istio#22766]
![image](https://user-images.githubusercontent.com/22000011/78642564-85736e80-78e5-11ea-861e-02bf4288311b.png)

I dont't know how to resolv it

**Comment by objectiser** [comment]
Hi

This would occur if your trace started in a previous service, but the
tracing data from that service was not reported. In this situation, the
root span (i.e. the initial span for the trace instance) is not available
when constructing the trace instance in the UI.

Regards
Gary
