### ISSUE TITLE
istio 1.5.1 can't recognize relative installPackagePath

### ISSUE THREAD

**Issue by jenningsloy318** [istio/istio#22768]
**Bug description**
```
istioctl manifest --verbose  generate  --force \
     --set installPackagePath=./istio-${ISTIO_VERSION}/install/kubernetes/operator/charts/ 
``` 
got error 
```
json: cannot unmarshal string into Go value of type []json.RawMessage, invalid value InstallPackagePath: ./istio-1.5.1/install/kubernetes/operator/charts/
Error: generated config failed semantic validation: json: cannot unmarshal string into Go value of type []json.RawMessage
```

**Expected behavior**
```
export ISTIO_VERSION=1.5.1
istioctl manifest --verbose  generate  --force \
     --set installPackagePath=./istio-${ISTIO_VERSION}/install/kubernetes/operator/charts/  
```
can genterate the manifest

**Steps to reproduce the bug**
```
istioctl manifest --verbose  generate  --force \
     --set installPackagePath=./istio-${ISTIO_VERSION}/install/kubernetes/operator/charts/ 
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istioctl: 1.5.1 

**How was Istio installed?**
not installed yet

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by esnible** [comment]
I tried to reproduce this and get a different message:

```
/tmp/istio-1.5.1/bin/istioctl manifest --verbose  generate  --force    --set installPackagePath=/tmp/istio-${ISTIO_VERSION}/install/kubernetes/operator
Error: stat /tmp/istio-1.5.1/install/kubernetes/operator/base: no such file or directory
```

I couldn't get the 1.6.0-alpha.0 to download, but I built from source and it DOES work in the code that will become 1.6.0

```
~/go/src/istio.io/istio/out/darwin_amd64/istioctl manifest --verbose  generate  --force    --set installPackagePath=/tmp/istio-${ISTIO_VERSION}/install/kubernetes/operator
```

**Comment by jenningsloy318** [comment]
Found out that we can't use relative path, should use full path 
```
manifest  generate --verbose  --force       --set installPackagePath=`pwd`/istio-${ISTIO_VERSION}/install/kubernetes/operator/charts      --set profile=`pwd`/istio-${ISTIO_VERSION}/install/kubernetes/operator/profiles/default.yaml
```

**Comment by esnible** [comment]
@jenningsloy318 This did work for me: `/tmp/istio-1.5.1/bin/istioctl manifest --verbose  generate  --force    --set installPackagePath=/tmp/istio-${ISTIO_VERSION}/install/kubernetes/operator/charts/ --set profile=/tmp/istio-${ISTIO_VERSION}/install/kubernetes/operator/profiles/default.yaml`

I had tried using `charts` following your example, but I hadn't explicitly test the `profile`, which turns out to be needed.

@ostromart The installation code was first developed for the stand alone operator, which doesn't have a notion of relative paths.  Would you recommend the istioctl command making the path absolute and passing it to the operator code?  That seems better than allowing the operator to take relative paths.

**Comment by ajitchahal** [comment]
Additionally: If the profile file is not provided explicitly isstioctl is not able to find profile in path:

```bash
istioctl manifest apply  
--set installPackagePath=$HOME/istio-1.5.1/install/kubernetes/operator/charts 

Error: failed to apply manifests: failed to generate manifest: 
open $HOME/istio-1.5.1/install/kubernetes/operator/**charts**/profiles/default.yaml: 
no such file or directory
```
The profile actually exists in following path of a unzipped istio release:
```bash
/Users/d069900/istio-1.5.1/install/kubernetes/**operator/profiles**/default.yaml
```
