### ISSUE TITLE
global in the resolve.conf affecting dns

### ISSUE THREAD

**Issue by nadeemhussain** [istio/istio#22763]
when istio is installed the /etc/resolv.conf is updated  and another search path is added which is  "global", which I think i required for service entry / multicluster logic,

but due to this global been there and also .global been a top-level domain, impact the system 
now app A can't talk to app B , using  B.namespace.svc.cluster.local 
as this is not a FQDN so as per our ndots this is first searched using our search paths in /etc/resolve.conf, where when its added with global it becomes ( B.namespace.svc.cluster.local.global) .

And since global is a tld local.global exists and thus it goes out to public service.

work around is to either user the full FQDN by using dot(.) at the end or just he svc name without svc.cluster.local 

now com.global don't exists currently so we are good but if someone buys that all our .com requests will go to them first.

[ ] Configuration Infrastructure
[ ] Docs
[] Installation
[X] Networking
[X] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Since global is top-level domain  we should opt out to some other keyword

**Steps to reproduce the bug**
1. dig a.svc.cluster.local   not the FQDN ( without dot at end), this will point to outside

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

istio version:

client version: 1.5.1
citadel version: 1.5.1
egressgateway version: 1.5.1
galley version: 1.5.1
ingressgateway-com version:
ingressgateway-internal version:
ingressgateway-kul version:
ingressgateway-sivvi version:
ingressgateway-team version:
policy version: 1.5.1
sidecar-injector version: 1.5.1
telemetry version: 1.5.1
pilot version: 1.5.1
data plane version: 1.5.1 (202 proxies)

kubectl version:

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.6", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"clean", BuildDate:"2020-01-18T23:31:31Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.9-gke.24", GitCommit:"39e41a8d6b7221b901a95d3af358dea6994b4a40", GitTreeState:"clean", BuildDate:"2020-02-29T01:24:35Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**
gcp

**Comment by hzxuzhonghu** [comment]
What is your /etc/resolv.conf look like?

**Comment by nadeemhussain** [comment]
this issue happens if you started to deploy multi cluster but missed the DNS step stub , https://istio.io/latest/docs/setup/install/multicluster/gateways/#setup-dns

the  /etc/resolv.conf  will contain the .global in it.

so for each dns request which is not FQDN  when the system try to resolve all combination in the  /etc/resolv.conf  , the .global  one will not get capture by coredns/kubedns  and will go out and gets resolved and .global is a TLD  and someone ones local.global 

for a request to svcA ,  the svcA.svc.default.cluster.local will become svcA.svc.default.cluster.local.global and gets resolved outside.

**Comment by hzxuzhonghu** [comment]
So it seems this is because of missing setup

**Comment by FrimIdan** [comment]
@hzxuzhonghu can you point me to where istio is modifying `/etc/resolve.conf`?
Is there a way to disable `/etc/resolve.conf` modification when running in multi-cluster mode?
