### ISSUE TITLE
Istio 1.5.0 metrics on stackdriver - mixerless telemetry

### ISSUE THREAD

**Issue by nikhilbalekundargi** [istio/istio#22769]
Istio version 1.5.0

Now that stackdriver adapter is deprecated in istio 1.5 can you help me with documentation of exporting istio metrics to stackdriver dashboard on GCP. I found a document for 1.4 https://github.com/istio/istio/wiki/Mixerless-Stackdriver-HTTP-Telemetry. Any details/document for istio 1.5?

**Comment by bianpengyuan** [comment]
I just created a wiki page for the instruction, please follow the instruction to enable proxy based stackdriver telemetry. Thanks! https://github.com/istio/istio/wiki/Proxy-Based-Stackdriver-Telemetry

**Comment by nikhilbalekundargi** [comment]
> I just created a wiki page for the instruction, please follow it to enable proxy based stackdriver telemetry. Thanks! https://github.com/istio/istio/wiki/Proxy-Based-Stackdriver-Telemetry

What will be the values for enabling metrics and logs. Like we have --set values.global.enableTracing=true --set values.global.proxy.tracer=stackdriver for tracing. Do we have similar option for logs and metrics?

**Comment by bianpengyuan** [comment]
@nikhilbalekundargi I updated the instruction with the command line options.

**Comment by spacejam101** [comment]
is it still maintained now?

**Comment by bianpengyuan** [comment]
Yeah it is and will be maintained for long term.

**Comment by mirobertod** [comment]
> I just created a wiki page for the instruction, please follow it to enable proxy based stackdriver telemetry. Thanks! https://github.com/istio/istio/wiki/Proxy-Based-Stackdriver-Telemetry

Hi, there is no mention in the wiki page about permissions.
Do we need to add some permission to the service account? Our nodes on GKE have already the role to write metrics and logging to stackdriver.

**Comment by bianpengyuan** [comment]
@mirobertod If the default credential is able to write to stackdriver, you should not need any more set up for service account. Yeah, they are not the same log entry, but many information in them will be duplicated.
