### ISSUE TITLE
istioctl manifest migrate error has incorrect URL

### ISSUE THREAD

**Issue by ericvn** [istio/istio#22775]
**Bug description**
Created a yaml and tried to run `istioctl manifest migrate` against it. The URL has `releaese` instead of `release`
```
istioctl manifest migrate istio-lean.yaml                                                                                                    
proto: tag has too few fields: "-"
Error: the input values.yaml fail validation: unknown field "kind" in v1alpha1.Values
check against https://github.com/istio/istio/blob/releaese-1.5/operator/pkg/apis/istio/v1alpha1/values_types.proto for schema
or run the command with --force flag to ignore the error
```

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
istioctl version
client version: 1.5.1
control plane version: 1.5.1
data plane version: none
```

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by esnible** [comment]
This was fixed in https://github.com/istio/istio/pull/21747/files but the PR was not flagged to back-port to 1.5.

@shamsher31 Can you cherry-pick your PR for release-1.5 branch?

**Comment by shamsher31** [comment]
/cherrypick/release-1.5

**Comment by shamsher31** [comment]
Sure

**Comment by shamsher31** [comment]
I don't have access to cherry-pick :(
@ericvn can you please do cherry-pick of https://github.com/istio/istio/pull/21747 PR.

**Comment by ericvn** [comment]
Looks like it was done in https://github.com/istio/istio/pull/22829 and that is merged now.  Thanks.
