### ISSUE TITLE
Provide documentation on how to integrate addons 

### ISSUE THREAD

**Issue by dgn** [istio/istio#22785]
See also https://docs.google.com/document/d/1jJ4kkALCUPWIlz_Ldu6jpeelMNxyY_SZDMaZmeSpfkM

**Comment by dgn** [comment]
fyi @istio/wg-docs-maintainers

**Comment by howardjohn** [comment]
All of the components are closed now, except Kiali which needs minor changes to the doc. Dropping to p1 as a result

**Comment by howardjohn** [comment]
Closing as all associated issues are closed
