### ISSUE TITLE
Istio ingress gateway support tls without SNI

### ISSUE THREAD

**Issue by lyambem-sflake** [istio/istio#22795]
When trying to use AWS Network Load Balancer (NLB) and terminate external tls traffic on NLB, the NLB does not send any SNI information to the Istio Gateway.  This causes HTTPs requests to fail on Istio Gateway which is set up with self-signed certificate. 
In our case we have NLB associated with AWS certificate and tls request terminating on NLB. On the istio side we have a self-signed certificate associated with the gateway. The NLB is not sending any SNI information to the Istio gateway and this is causing https request on Istio Gateway to fail . We want to use https for the internal traffic to achieve end to end encryption, but is not able to use NLB because of this issue. 
**Describe the feature request**
Enable Istio Gateway to support tls request without SNI

**Describe alternatives you've considered**
Use wildcard ("*") for hostname so that Istio does not have to verify the SNI. However this is not secure and restricts us from scaling the platform and utilizing other applications like external-dns which do not accept wildcard domains. 

**Additional context**

**Comment by dontreboot** [comment]
@rshriram You proposed to use '*" on https://github.com/istio/istio/issues/18223. With '*', we basically won't be able to present different certs based on SNI. How do we configure istio gateway such that it presents a default certificate when there is no SNI but when SNI is present, it can use different certificates?

**Comment by rshriram** [comment]
can't you have different Gateway resources? one with *, while others with SNI+custom certs? Envoy's filter chain match will automatically pick the most specific match. If it is a question of Istio disallowing * in SNI when there are other gateways, then we can fix it easily.

**Comment by lyambem-sflake** [comment]
We were able to solve this by setting up separate gateway resourcs one with * and other with SNI + custom cert as suggested by @rshriram

**Comment by sabinayakc** [comment]
@sfc-gh-lyambem Could you share your gateway and NLB config? 

I am facing similar issue. Trying to terminate TLS at NLB and re-originate (if possible) to the Gateway.
