### ISSUE TITLE
Ingress gateway service port 15030 with name prometheus return connection refused

### ISSUE THREAD

**Issue by hisarbalik** [istio/istio#22801]
**Bug description**
After upgrading istio to version 1.4.6, metrics from ingress gateway over port 15030 with name prometheus returns "connection refused"

**Expected behavior**
Configured port is accessible and prometheus can scrape metrics for ingress gateway service over configured port

**Steps to reproduce the bug**
install istio with version 1.4.6 and install prometheus operator 0.38.0
Prometheus operator can discover all istio services but istio ingress gateway over port 15030
**Version 
istio version 1.4.6

**How was Istio installed?**
istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**
Tested on GCP and Azure

**Comment by howardjohn** [comment]
Hi, we have changed the instructions for remote access. Please see https://preliminary.istio.io/latest/docs/tasks/observability/gateways/#configuring-remote-access for more info. thanks!
