### ISSUE TITLE
 Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?) after enable SDS

### ISSUE THREAD

**Issue by hqms** [istio/istio#22800]
**Bug description**
I've tried to enable SDS on the ingress-gateway (https://istio.io/docs/tasks/traffic-management/ingress/ingress-certmgr/), but the istio-ingressgateway pod always on unready state 

I describe the pod and found :
` Warning  Unhealthy  37s (x1051 over 35m)  kubelet, gke-horus-k8s-default-pool-07043ff0-1f8z  Readiness probe failed: HTTP probe failed with statuscode: 503
`

and log:
`Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 2 successful, 0 rejected; lds updates: 0 successful, 2 rejected
`

**Expected behavior**

**Steps to reproduce the bug**
- Install istio with demo profile
- enable the sds (https://istio.io/docs/tasks/traffic-management/ingress/ingress-certmgr/)

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
./bin/istioctl version --remote
client version: 1.5.1
control plane version: 1.5.1
data plane version: 1.5.1 (13 proxies)
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-gke.1", GitCommit:"aa93664bafe74f3c051e021b27a64e28ac34ab40", GitTreeState:"clean", BuildDate:"2020-03-18T22:49:35Z", GoVersion:"go1.12.17b4", Compiler:"gc", Platform:"linux/amd64"}
```

```
 helm version
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

**Comment by hqms** [comment]
i've just scrolled to logs .. and found 

`[Envoy (Epoch 0)] [2020-04-08 09:24:05.945][13][warning][config] [external/envoy/source/common/config/grpc_subscription_impl.cc:87] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener(s) 0.0.0.0_443: Invalid path: /etc/istio/ingressgateway-certs/tls.crt
`
right before the error occured

**Comment by howardjohn** [comment]
> could it be the culprit?

Yes


Possibly missing the patch step at https://istio.io/docs/tasks/traffic-management/ingress/ingress-certmgr/#configuring-dns-name-and-gateway? (note: this doc is pretty bad - `patch` is not a great solution... in `master` we have improved this quite a bit.

**Comment by rajivml** [comment]
@howardjohn am using istio 1.5.2 and the same problem over there, how do you recommend setting up the same in prod

**Comment by brijchavda** [comment]
Had the same issue. But one of my istio gateway was pointing to the cert, which did not exist, which caused the ingress pod crash.

**Comment by sebnyberg** [comment]
I was re-installing istio and an old gateway resource was referencing the a non-existent cert in the default ingress. Removing the gateway made the installation go through.
