### ISSUE TITLE
Add more check for operator controller to declare healthy status

### ISSUE THREAD

**Issue by richardwxn** [istio/istio#22815]
Now the controller would update the cr status to be HEALTHY after it process and apply the manifest correctly. Actually we should add more check, like checking pods readiness, endpoint readiness before declaring its status to be HEALTHY.

**Comment by richardwxn** [comment]
actually if running via istoctl operator init with --wait flag, it is supposed to wait for the resources to be ready, but some logic is missing there. If we do not consider other cases that user may use the controller, then I think updating the wait logic is fine, we don't need to update the logic in reconciler

**Comment by brian-avery** [comment]
@richardwxn is this complete?
