### ISSUE TITLE
Add jwt analyzer for RequestAuthentication/Authorization policy

### ISSUE THREAD

**Issue by jacob-delgado** [istio/istio#22813]
**Describe the feature request**

There used to exist a jwt analyzer that checked v1alpha1/Policy resources specifying jwt had a properly prefixed port in the associated k8s Service resource. See https://github.com/istio/istio/issues/17535

However, with the new v1beta1/RequestAuthentication api and the removal of the v1alpha1/Policy api the previous analyzer was removed (https://github.com/istio/istio/pull/22706).

To maintain parity, we should make sure that RequestAuthentication resources is defined when there is an AuthorizationPolicy specifying the usage jwt.

**Describe alternatives you've considered**

None.

**Additional context**

**Comment by jacob-delgado** [comment]
cc @ayj @diemtvu @yangminzhu

Let's add the requirements necessary for this analyzer (or close it if it doesn't make sense).

Diem does raise the issue that this cannot easily be done with the framework of the analyzers at the moment https://github.com/istio/istio/pull/22706#issuecomment-608635897

**Comment by yangminzhu** [comment]
May need some update to the analyzer framework but I think the requirement still makes sense. cc @samprit

**Comment by yangminzhu** [comment]
@samprit will look into this, currently I couldn't assign it in github, probably because he is not in the istio github org yet.
