### ISSUE TITLE
Inbound bind address is unstable with sidecar ingress listener without bind address

### ISSUE THREAD

**Issue by robertpanzer** [istio/istio#22830]
**Bug description**

When running istio-proxy on a VM with multiple IPs in the INSTANCE_IPS node metadata, ingress listeners configured in a sidecar resource with capture mode IPTABLES and without bind address istio-proxy changes the IP address it eventually "virtually binds" to over time.

**Expected behavior**

**Steps to reproduce the bug**

I configure a Sidecar resource with an ingress listener with capture mode IPTABLES:
```yaml
  ingress:
  - captureMode: IPTABLES
    defaultEndpoint: 127.0.0.1:8086
    port:
      name: in-4142
      number: 4142
      protocol: HTTP
```
The bootstrap config has 2 addresses in the INSTANCE_IPS metadata:
```
 `"INSTANCE_IPS": "192.168.99.111,192.168.99.110"` 
```
Looking at the listeners after the initial push and after a second push after updating the sidecar resource on some unrelated field shows that the listener first binds to `192.168.99.111` and then binds to `192.168.99.110` after the second push.
This makes the ingress listener unavailable after the second push for clients that assume to find the listener on the first address.

Apparently the ips are sorted lexicographically after the first push so that the second push changes the order of IPS.

Discussed this issue already with @howardjohn.
**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
Tested on Istio 1.4.6 on OSX.
Istio 1.5.1 should show the same behavior.
I think 1.6/master does not show this, even if I haven't tested it.

**How was Istio installed?**
We reproduced this with a helm installation, and I also reproduced it while running Galley and Pilot locally on OSX.

**Environment where bug was observed (cloud vendor, OS, etc)**
Local OSX.

**Comment by howardjohn** [comment]
Should be fixed by #22831
