### ISSUE TITLE
 //pilot/proxy/envoy:go_default_test fialure with exec format error

### ISSUE THREAD

**Issue by kadamvandita** [istio/istio#2283]
The test case  //pilot/proxy/envoy:go_default_test fails with exec format error on x86 system.

The log shows watcher_test.go:235: fork/exec /home/test/.cache/bazel/_bazel_test/5da62891b5776882300f42bdf07800a1/bazel-sandbox/9110482688586916072/execroot/io_istio_istio/bazel-out/s390x-fastbuild/bin/pilot/proxy/envoy/linux_s390x_stripped/go_default_test.runfiles/io_istio_istio/pilot/proxy/envoy/envoy: exec format error.

Any inputs on this?

**Comment by rshriram** [comment]
We are moving away from Bazel. Please test without bazel. The DEV-GUIDE has been updated.

**Comment by kyessenov** [comment]
The test is gone after bazel removal, so the problem is gone with it :)
