### ISSUE TITLE
Istio 1.4.7 to 1.5.1 default profile with egress upgrade failure, 1.4 proxy pods for egress broken

### ISSUE THREAD

**Issue by kramvan1** [istio/istio#22842]
**Bug description**

After upgrade from 1.4.7 to 1.5.1, existing 1.4 proxy pods that are using egress gateway have connection failures.   503 for http and reset for https.

Same thing with **demo profile works**.

**Expected behavior**

Existing 1.4 mesh pods can still connect via the egress gateway.

**Steps to reproduce the bug**

- download 1.4.7
- istioctl manifest --set profile=default --set gateways.components.egressGateway.enabled=true
- deploy egress sample defined https://istio.io/docs/tasks/traffic-management/egress/egress-gateway and check the traffic and logs as in the example.
- download 1.5.1
- modify default profile to have egress enabled
- istioctl upgrade -f <path to 1.5.1 default profile with egress> --force
- check the traffic and logs as in the example.
    - http fails with 503
    - https fails with connection reset

sleep proxy logs
```
[2020-04-09T16:27:33.123Z] "GET /politics HTTP/1.1" 503 UF,URX "-" "-" 0 91 3031 - "-" "curl/7.64.0" "84a66110-e563-42d0-af3b-b3ce4efefb51" "edition.cnn.com" "172.30.61.81:80" outbound|80|cnn|istio-egressgateway.istio-system.svc.cluster.local - 151.101.1.67:80 172.30.159.166:32778 - -
[2020-04-09T16:27:37.566Z] "- - -" 0 UF,URX "-" "-" 0 0 1002 - "-" "-" "-" "-" "172.30.61.81:443" outbound|443|cnn|istio-egressgateway.istio-system.svc.cluster.local - 151.101.65.67:443 172.30.159.166:44000 - -
[Envoy (Epoch 0)] [2020-04-09 16:27:56.175][19][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:91] gRPC config stream closed: 14, upstream connect error or disconnect/reset before headers. reset reason: connection failure
[Envoy (Epoch 0)] [2020-04-09 16:28:12.953][19][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:91] gRPC config stream closed: 14, upstream connect error or disconnect/reset before headers. reset reason: connection failure
```
**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

1.4.7 and 1.5.1

**How was Istio installed?**

istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**

IKS

**Comment by kramvan1** [comment]
@linsun @rvennam

**Comment by kramvan1** [comment]
[_logs-pilot-1.5.1.txt](https://github.com/istio/istio/files/4457517/_logs-pilot-1.5.1.txt)
full piot logs

**Comment by linsun** [comment]
@kramvan1 does your egress gateway change ip before and after upgrade?  The reason I'm asking is if the endpoint has changed and proxy can't connect to istiod (the other https://github.com/istio/istio/issues/22841) then it will attempt to connect to the prior endpoint which can be wrong.

cc @GregHanson

**Comment by howardjohn** [comment]
might be the same as https://github.com/istio/istio/issues/22841 if demo works, or similar

**Comment by kramvan1** [comment]
@howardjohn yes, PR #22848 seems to fix this.   will test again once it's merged. thx.

**Comment by kramvan1** [comment]
Verified with latest 1.5-dev
