### ISSUE TITLE
Istio 1.4.7 to 1.5.1 default profile upgrade failure, 1.4 proxy pods no longer in mesh

### ISSUE THREAD

**Issue by kramvan1** [istio/istio#22841]
**Bug description**

After upgrade from 1.4.7 to 1.5.1, existing 1.4 proxy pods are no longer showing up in
`istioctl ps` or `istioctl version --short=false`.   Something appears to be wrong with the certificate used for the pilot grpc connection. 

Same thing with **demo profile works**.

after upgrade, istiod logs have (ip is one of the mesh pods with 1.4 proxy)

```
2020-04-09T16:28:28.233401Z	info	http: TLS handshake error from 172.30.114.223:43748: remote error: tls: unknown certificate
```

and 1.4 proxy pods have:

```
[Envoy (Epoch 0)] [2020-04-09 16:28:28.233][20][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:91] gRPC config stream closed: 14, upstream connect error or disconnect/reset before headers. reset reason: connection failure
```

before upgrade:
```
istioctl ps | grep -v gateway
NAME                                                  CDS        LDS        EDS        RDS        PILOT                            VERSION
httpbin-779c54bf49-bj94s.default                      SYNCED     SYNCED     SYNCED     SYNCED     istio-pilot-684c85c678-7vsn4     1.4.7
sleep-f8cbf5b76-wx2t7.default                         SYNCED     SYNCED     SYNCED     SYNCED     istio-pilot-684c85c678-7vsn4     1.4.7
```
after upgrade:
```
istioctl ps | grep -v gateway
NAME                                                   CDS        LDS        EDS        RDS        PILOT                       VERSION
```

**Expected behavior**

Existing 1.4 mesh pods can still connect and be part of the mesh.

**Steps to reproduce the bug**

- download 1.4.7
- istioctl manifest --set profile=default
- deploy sleep and bookinfo tests, or any other mesh pod with autoinjection. Mine are all in default namespace
- check mesh with istioctl ps or istioctl version --short=false
- download 1.5.1
- istioctl upgrade -f <path to 1.5.1 default profile> --force
- check mesh with istioctl ps or istioctl version --short=false
    - list does not contain the 1.4 proxy pods.
    - only after a restart of those pods and get the 1.5 proxy, do they appear.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

1.4.7 and 1.5.1

**How was Istio installed?**

istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**

IKS

**Comment by kramvan1** [comment]
@linsun @rvennam

**Comment by kramvan1** [comment]
A difference from the pilot logs:
working case:
```
2020-04-09T16:12:50.583421Z	info	pkica	The Citadel's public key is successfully written into configmap istio-security in namespace istio-system.
2020-04-09T16:12:50.583474Z	info	rootcertrotator	Set up back off time 9m8s to start rotator.
2020-04-09T16:12:50.583498Z	info	Generating K8S-signed cert for [istiod.istio-system.svc istiod-remote.istio-system.svc istio-pilot.istio-system.svc]
2020-04-09T16:12:50.585726Z	info	rootcertrotator	Jitter is enabled, wait 9m8s before starting root cert rotator.
2020-04-09T16:12:50.908985Z	info	Certificates created in ./var/run/secrets/istio-dns
2020-04-09T16:12:50.910078Z	info	Generating a certificate for secure gRPC (istiod-service-account/istio-system)
```
broken case:
```
2020-04-09T16:24:50.869227Z	info	pkica	The Citadel's public key is successfully written into configmap istio-security in namespace istio-system.
2020-04-09T16:24:50.869256Z	info	rootcertrotator	Set up back off time 43m43s to start rotator.
2020-04-09T16:24:50.869292Z	info	Generating Citadel-signed cert for [istiod.istio-system.svc istiod-remote.istio-system.svc istio-pilot.istio-system.svc]
2020-04-09T16:24:50.869329Z	info	rootcertrotator	Jitter is enabled, wait 43m43s before starting root cert rotator.
2020-04-09T16:24:51.429485Z	info	No plugged-in cert at etc/cacerts/ca-key.pem; self-signed cert is used
2020-04-09T16:24:51.430222Z	info	Certificates created in ./var/run/secrets/istio-dns
2020-04-09T16:24:51.431395Z	info	Generating a certificate for secure gRPC (istiod-service-account/istio-system)
202
```

The diff line being:
```
2020-04-09T16:24:51.429485Z	info	No plugged-in cert at etc/cacerts/ca-key.pem; self-signed cert is used
```
going to reset my env and try again to dbl check these results.

**Comment by linsun** [comment]
@elfinhe @howardjohn @ostromart thoughts?  It is not clear why demo profile would work for the same test and default could not.  The error does indicate the 1.4 proxy unable to connect to istiod which I'd assume it is on port 15011 with 1.4's proxy.

**Comment by howardjohn** [comment]
I can reproduce this. I am certain this was working from 1.4 -> 1.5.0, investigating if its a 1.5.1 regression

**Comment by linsun** [comment]
Thank you much @howardjohn !

**Comment by howardjohn** [comment]
hmmm seems like serviceAccount got changed at some point. Replacing serviceaccount: istiod to istio-pilot on the deployment fixes this

**Comment by linsun** [comment]
@howardjohn yes, confirmed in master we have istio-pilot-service-account as the service account but istiod in 1.5.x.  Seems this would be an issue with 1.5 also.  Do you plan to submit a PR for changing it to be the same as master's?  I'd be happy to if you aren't.

**Comment by howardjohn** [comment]
I will send a PR. I think I see what happened, we change the SA, realized it was a bad idea and reverted back to istio-pilot, but didn't backport the revert

**Comment by linsun** [comment]
Awesome, much appreciated @howardjohn !

**Comment by howardjohn** [comment]
What I don't know is how this was missed in testing... I tested this exact thing many times and we even have automated upgrade testing (clearly not enough coverage from this one). Ill send the pr today

**Comment by elfinhe** [comment]
Thanks John for figuring it out!

**Comment by kramvan1** [comment]
Ref to the SA issue?   
And can it be manually fixed after upgrade?    
Any idea why it works with Demo profile?

**Comment by howardjohn** [comment]
demo profile connects to pilot over plaintext so the cert mismatch doesn't matter. breaking commit: https://github.com/istio/istio/commit/a17ee65bcc82314257a7d0146118338c3ac25734. Yes it can be fixed manually, rename the service account, like in the PR https://github.com/istio/istio/pull/22848

**Comment by howardjohn** [comment]
@kramvan1 any chance you could verify the above PR (manually or otherwise)? I have done it myself but doesn't hurt to have 2 people try it

**Comment by linsun** [comment]
@howardjohn can you point out where demo profile is confuguring to use the plain traffic to pilot?  This used to be the controlplane security flag.

**Comment by howardjohn** [comment]
https://github.com/istio/operator/blob/release-1.4/data/profiles/demo.yaml#L69

**Comment by linsun** [comment]
Ah i have been looking at 1.5 or master's demo.yaml.  now it all makes sense now :)

**Comment by kramvan1** [comment]
@howardjohn yes, I'll give it a try, thx

**Comment by kramvan1** [comment]
@howardjohn  Yes, that PR change worked for me.      And yes I also seems to have fixed egress issue as well.  https://github.com/istio/istio/issues/22842

**Comment by sdake** [comment]
The cross-version upgrade test case was removed in this commit: d54f020b5c2642e42ff25dc04001a65eb0c8d0aa.

Hence the regression.

I am struggling to find any replacement in release-1.5 branch or master.

**Comment by howardjohn** [comment]
Its just moved to istio/tools:
https://prow.istio.io/job-history/istio-prow/logs/istio-upgrade-using-istioctl-1.4_latest-1.5_latest.
note the recent failures are due to infra issue, it didn't start catching
this bug. The test does not sufficiently cover upgrade issues

**Comment by kramvan1** [comment]
Yes would like to see more coverage in the upgrade tests.

Verify this issue is fixed in 15-dev
