### ISSUE TITLE
Performance Regression of Istio master/release-1.6 

### ISSUE THREAD

**Issue by carolynhu** [istio/istio#22845]
Our performance test run (http://perf.dashboard.istio.io/benchmarks/latency_vs_connection/) has detected Istio master/release-1.6 regression since around Feb 18. 

For tracing back and debugging: our performance test labels changed a lot since last month, you cannot see those plotted data for that date. But you can check the test `.csv` data from the artifacts page: http://perf.dashboard.istio.io/artifacts/

Here is the graph I plotted for **P99**:
- [release-1.5/Feb-13] https://gcsweb.istio.io/gcs/istio-build/perf/benchmark_data-release-1.5.20200213-08.9672b2c/
![istio_1_5_p99_feb_13](https://user-images.githubusercontent.com/29208297/78956912-ab8d4000-7a98-11ea-8afc-f9f1ff570faf.png)
- [master/Feb-14] https://gcsweb.istio.io/gcs/istio-build/perf/benchmark_data-master.20200214-00.445524d 
![istio_1_6_p99_feb_14](https://user-images.githubusercontent.com/29208297/78930644-4ebe6500-7a59-11ea-96ca-a9755a723063.png)
- [release-1.5/Feb-19] https://gcsweb.istio.io/gcs/istio-build/perf/benchmark_data-release-1.5.20200219-08.3892338
![istio_1_5_p99_2_19](https://user-images.githubusercontent.com/29208297/78930653-53831900-7a59-11ea-9afd-df970cf9cc10.png)
- [master/Feb-18] https://gcsweb.istio.io/gcs/istio-build/perf/benchmark_data-master.20200218-00.c50c8a4
![istio_1_6_p99_feb_18](https://user-images.githubusercontent.com/29208297/78930659-567e0980-7a59-11ea-94df-6d27d2f93686.png)

**Comment by carolynhu** [comment]
cc @mandarjog @kyessenov @bianpengyuan

**Comment by carolynhu** [comment]
a proxy sha change happened on Feb 18: https://github.com/istio/istio/pull/21226

**Comment by carolynhu** [comment]
I will rerun the test locally for Feb-14 both release-15 and master to make sure this is not related to changes of our test runner.

**Comment by carolynhu** [comment]
cc @qfel @jplevyak

**Comment by bianpengyuan** [comment]
If I read correctly, `non-both`, which means both client and server have sidecar injected with no istio filter, already shown regression at 2/14, right? Which means there is already a regression from upstream envoy repo from that day instead of 2/18. Do we know if 2/14 the first day that master became slower than 1.5?

**Comment by carolynhu** [comment]
@bianpengyuan the none-both for release-1.5 might be not correct for 2/14.

When you compare the release-1.5 perf number we published: https://istio.io/docs/ops/deployment/performance-and-scalability/
This is P99-release-1.5:
<img width="844" alt="Screen Shot 2020-04-09 at 1 09 16 PM" src="https://user-images.githubusercontent.com/29208297/78936414-5e42ab80-7a63-11ea-81f7-519172f52062.png">

There is no much different compared to 2/14 master. But since from around 2/18, master started has obvious differences on those numbers.

**Comment by kyessenov** [comment]
Proxy diff https://github.com/istio/proxy/compare/f71ceb04a3ec1dd1a11e26e473bf91784b0321e4...9272abc1fcf3526e6bedd1b7c589a536360b3841

**Comment by bianpengyuan** [comment]
And envoy diff https://github.com/envoyproxy/envoy-wasm/compare/5b10e3402e68c44b2caba14e944011b925c96671...d6ebd6366d55bb6125cda311d6a719e124d9239a which is contained in proxy diff.

**Comment by lambdai** [comment]
drive by: is it possible that the checkshutdown and finishShutdown is called many times? https://github.com/envoyproxy/envoy-wasm/pull/405
I don't see guarded flag to call it at most once.

**Comment by lambdai** [comment]
@carolynhu 
Why `non-both` has higher latency than `mixer-both` in the first pic?

**Comment by carolynhu** [comment]
@lambdai I think that is wrong, you can ignore it, since after that like release-1.5 Feb-19 is the correct order. I guess that might because either test label is incorrect or not being parsed correctly. Since we made some changes on adjusting test labels.

**Comment by mandarjog** [comment]
Thanks Carolyn. Can you please remove the incorrectly labeled image in the description? It is likely to cause more questions. Also please mention if it is p99 or p90.

**Comment by carolynhu** [comment]
I updated the release-1.5 data to use Feb-13, which is less confusing. Also, all the perf number plotted in the graph is for P99.

**Comment by bianpengyuan** [comment]
Is it possible to run perf test on a commit? It would be nice to run the test on https://github.com/istio/istio/commit/7197e6528be472987c996bac0c195e2be5a4ce08 and its parent commit https://github.com/istio/istio/commit/cd414cb0678fb4d5b08f6ae081536219e1c177cf to make sure 2/18 proxy sha update indeed was causing problem. The envoy diff and proxy diff seems harmless and is unlikely to cause performance issue.

**Comment by carolynhu** [comment]
Perf test label meanings/explanations can be found here: http://perf.dashboard.istio.io/benchmarks/configs_measurements/

**Comment by carolynhu** [comment]
@bianpengyuan I think we can run perf test against a Istio release with git_sha/commit as long as we can build the istioctl binary for a specific commit, I can run that perf test.

**Comment by mandarjog** [comment]
@bianpengyuan configdumps are available with all these runs so if you would like to verify that it is not the 1.6 config that is causing the regression, you can.

**Comment by carolynhu** [comment]
Update:
1. rerun lastest 1.5, similar results as what we published in istio.io for P99:

![istio_1_5_p99](https://user-images.githubusercontent.com/29208297/79291980-e3bfc480-7e84-11ea-8e5b-4c02db37dfc6.png)

2. rerun feb-18 master, the perf number shows regression:
![istio_1_6_p99](https://user-images.githubusercontent.com/29208297/79292039-03ef8380-7e85-11ea-928f-31b7e4a3ec4b.png)

3. Next step: bisect rerun to locate the place/date which causes the regression

**Comment by carolynhu** [comment]
Update: after bisect and rerun. I found the latency regression happens from https://github.com/istio/istio/pull/21162

But by checking with @howardjohn and @bianpengyuan , they are not able to pinpoint anywhere that might cause regression from that PR. 

Next step: run benchmark against Nighthawk. (fortio might has lots of noises).

**Comment by bianpengyuan** [comment]
Looks like somehow after #21162, `sidecar.istio.io/proxyCPU: 1000m` annotation, which is used by load test, causes a side effect that makes sidecar concurrency drop to 1 and thus the regression. @howardjohn any idea about this?

**Comment by howardjohn** [comment]
Looking into this now

**Comment by bianpengyuan** [comment]
Looks like proxy request cpu dictates the concurrency now. Raising it to 3000m will increase concurrency to 3.

**Comment by mandarjog** [comment]
nice find @bianpengyuan !

**Comment by carolynhu** [comment]
Yes, confirmed the regression by 2nd run. The 2nd perf run for https://github.com/istio/istio/pull/20891 shows no regression, which is a previous commit of https://github.com/istio/istio/pull/21162. But the 2nd perf run for https://github.com/istio/istio/pull/21162 do have a large jump on latency. I have sent those rawdata, config_dump and cluster info with @bianpengyuan and @howardjohn.

**Comment by bianpengyuan** [comment]
@carolynhu Please add pod spec to the perf pipeline dump as well. (kubectl get pod -o yaml)

**Comment by howardjohn** [comment]
omg... we have some hidden magic in the sidecar injector: https://github.com/istio/istio/blob/45a3140ac532029747aa8433f67744744bf1c782/pkg/kube/inject/concurrency.go#L76-L93. Its actually parsing the injection template, looking for `--concurrency`, and if its not present using the CPU requests!. In 21162 we removed the flag because there is no need for it: we read from proxy config directly in the agent rather than flags.

**Comment by carolynhu** [comment]
@bianpengyuan yes, that would be helpful. Will do!

**Comment by howardjohn** [comment]
followup: https://github.com/istio/istio/issues/23470
