### ISSUE TITLE
Proxy not releasing memory after RPS goes to zero

### ISSUE THREAD

**Issue by clarkmcc** [istio/istio#22849]
**Bug description**
I tested one of our services with about 800 RPS (gRPC unary traffic), here is the grafana results for the test. You can see that the CPU usage reflects the increase and decrease in RPS but the memory usage increases and doesn't decrease. Is this expected? Is there a way to minimize the amount of resource used when we're not getting any requests?

![Screen Shot 2020-04-03 at 4 53 09 PM](https://user-images.githubusercontent.com/6639685/78940546-4541f680-7a73-11ea-91e0-3b62ce1b475b.png)

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[*] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Memory usage would increase and decrease based on RPS similar to how the CPU usage works.

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
**Istio**
client version: 1.5.0
control plane version: 1.5.0
data plane version: 1.5.0 (27 proxies)
**kubectl**
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-gke.3", GitCommit:"71631703d37fb1b4b333abd427deae839aeb2032", GitTreeState:"clean", BuildDate:"2020-03-24T18:54:48Z", GoVersion:"go1.12.17b4", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
Using the `backyards install` cli

**Environment where bug was observed (cloud vendor, OS, etc)**
GCP

I don't have one because this screenshot is from last week, but I'd be happy to hit my services again and provide more information.

**Comment by howardjohn** [comment]
My guess is that Envoy is allocating enough memory during the spike that it needs to grow the heap. Once the traffic is done it de-allocates most of its memory but the heap size remains the same and this is what is reported. It might also be useful to compare envoy_server_memory_allocated and envoy_server_memory_heap_size metrics, which should show this. If you don't have those for whatever reason its also found at `:15000/metrics`

Note that your application behaves the same, although to a lesser degree

**Comment by clarkmcc** [comment]
Thanks for the info, I'll do some more poking around then.
