### ISSUE TITLE
Increased sidecar memory usage in Istio 1.5

### ISSUE THREAD

**Issue by silverlyra** [istio/istio#22851]
**Bug description**

<img width="1589" alt="Istio 1.4 vs. 1.5" src="https://user-images.githubusercontent.com/25393735/78939968-ee83ef00-7a69-11ea-9edb-4528c84814ec.png">

We recently upgraded from Istio 1.4.2 to 1.5. We do Kubernetes and Istio upgrades by creating new clusters and migrating traffic from the old to the new, which lets us easily compare performance before and after.

Above is a plot of the per-pod memory usage of Istio sidecar proxies in some of our production namespaces (but they all look similar):

```promql
container_memory_usage_bytes{id!="/", namespace=~"$namespace", name!="", container="istio-proxy", cluster=~"[1.4 or 1.5]"}
```

This is showing a time window where 50% of our traffic was going to the 1.4-powered clusters and 50% to 1.5, although this new memory consumption pattern doesn't seem to vary much with load.

We discovered this when sidecars started hitting the 256MiB memory limit we had configured for them (a comfortable limit under 1.4). I didn't find an existing issue about this and I'm wondering if this was an expected change.

We are using the new in-proxy telemetry both in the 1.4 and 1.5 clusters (and it works much better in 1.5).

**Expected behavior**

Either 1.5 proxies don't use ~2x the memory of 1.4, or if this behavior was known to the Istio maintainers, it was called out in the release notes.

**Steps to reproduce the bug**

Upgrade your production clusters I guess 🤷‍♀️ 

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

<details>
<summary>Istio 1.4 clusters</summary>
<pre><code>❯ istioctl --context [1.4] version --remote
client version: 1.5.1
citadel version: 1.4.2
galley version: 1.4.2
pilot version: 1.4.2
pilot version: 1.4.2
private-ingressgateway version:
private-ingressgateway version:
private-ingressgateway version:
public-ingressgateway version:
sidecar-injector version: 1.4.2
data plane version: 1.4.2 (286 proxies)</code></pre>

<pre><code>❯ kubectl --context [1.4] version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-23T14:21:54Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-502bfb", GitCommit:"502bfb383169b124d87848f89e17a04b9fc1f6f0", GitTreeState:"clean", BuildDate:"2020-02-07T01:31:02Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}</code></pre>

<pre><code>❯ helm version
version.BuildInfo{Version:"v3.0.3", GitCommit:"ac925eb7279f4a6955df663a0128044a8a6b7593", GitTreeState:"clean", GoVersion:"go1.13.7"}</code></pre>
</details>

<details>
<summary>Istio 1.5 clusters</summary>
<pre><code>❯ istioctl --context [1.5] version --remote
client version: 1.5.1
citadel version: 1.5.0
galley version: 1.5.0
pilot version: 1.5.0
private-ingressgateway version:
private-ingressgateway version:
private-ingressgateway version:
public-ingressgateway version:
sidecar-injector version: 1.5.0
data plane version: 1.5.0 (275 proxies)</code></pre>

<pre><code>❯ kubectl --context [1.5] version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-23T14:21:54Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-502bfb", GitCommit:"502bfb383169b124d87848f89e17a04b9fc1f6f0", GitTreeState:"clean", BuildDate:"2020-02-07T01:31:02Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}</code></pre>

<pre><code>❯ helm version
version.BuildInfo{Version:"v3.0.3", GitCommit:"ac925eb7279f4a6955df663a0128044a8a6b7593", GitTreeState:"clean", GoVersion:"go1.13.7"}</code></pre>
</details>

**How was Istio installed?**

via Helm

**Environment where bug was observed (cloud vendor, OS, etc)**

AWS EKS

**Comment by howardjohn** [comment]
> We do Kubernetes and Istio upgrades by creating new clusters and migrating traffic from the old to the new, which lets us easily compare performance before and after.

Very nice.

The application/Istio config between the two clusters should the same, right? it would be interesting to see a difference in the config of two of the same app in each cluster. either a full config dump https://github.com/istio/istio/wiki/Troubleshooting-Istio#collecting-information-2 or even just `istioctl proxy-config` for listener, route, and cluster. If you do `istioctl pc clusters | wc -l` on both and see a big difference, that seems likely related.

It might also be useful to compare envoy_server_memory_allocated and envoy_server_memory_heap_size as well if you have these metrics

**Comment by silverlyra** [comment]
Thanks for the quick reply!

> The application/Istio config between the two clusters should the same, right?

They should be very nearly the same. One change we made between the old and new clusters was switching some HTTP routes from prefix host matches to a regular expression, but we rolled that change back and the proxies’ memory usage didn’t change. We deleted all the application pods after changing that back just to be sure, and the new pods’ sidecars still had the same memory consumption.

Our Istio 1.4 prod clusters are now scaled down, but there are a few application pods still running. I pulled the Envoy `config_dump`s of a Pod from the same app in the old and new clusters:

```sh
❯ wc -l *_clean.json
   45714 config_dump_v1.4_clean.json
   53622 config_dump_v1.5_clean.json
```

(The `_clean` is just me sorting the JSON keys with `jq -S` to get cleaner diffs.)

The bootstrap config now has [a list of extensions](https://gist.github.com/silverlyra/f5a6cde3c7a95b1cfb4545fe363245c3#file-bootstrap-diff) but is otherwise similar.

Clusters has [only minor changes](https://gist.github.com/silverlyra/f5a6cde3c7a95b1cfb4545fe363245c3#file-clusters-diff); if I exclude fields that definitively changed like `@type` and `last_updated`, I basically see only the actual changes we made to set of services we run in these clusters (we deployed kubecost and no longer run metacontroller) as well as a new `filter_metadata` field. The diff of routes is similar; one new service and two ones we shut down, and we made some changes to hostnames, but there are no other changes. I’m not seeing any red flags.

Most of the size change in the overall config dump is in the listeners, which seems to be an entirely different structure? The actual set of listeners [is similar](https://gist.github.com/silverlyra/f5a6cde3c7a95b1cfb4545fe363245c3#file-listeners_no_ips-diff) if I exclude IP addresses – port `10250` is our `prometheus-operator-kubelet` service, and the difference in count there is due to me getting the config dump after we'd scaled down the old cluster and it doesn't have a full complement of nodes anymore.

Other than the prefixes → regex change I mentioned which we rolled back, we at least weren’t trying to make any Istio configuration changes.

> It might also be useful to compare envoy_server_memory_allocated and envoy_server_memory_heap_size as well if you have these metrics

We don’t, unfortunately; we’ve got a pretty short whitelist of metrics we scrape from the proxies, but I can add these two tomorrow and take a look.

**Comment by howardjohn** [comment]
If you don't have the metrics you can get a point in time view from
localhost:15000/metrics on the pod. That's for the details, I'll take a
closer look soon.

If you are able to experiment it may be useful to see if the memory usage
is smaller if you disable telemetry v2, just to minimize variables

**Comment by silverlyra** [comment]
> you can get a point in time view

ah, right! Here’s the current values from the pods whose configs I dumped earlier:

| Metric  | Version | Value |
| ------------- | ------------- | ------------- |
| envoy_server_memory_allocated | v1.4 | 20572968 |
| envoy_server_memory_allocated | v1.5 | 100279088 |
| envoy_server_memory_heap_size | v1.4 | 38797312 |
| envoy_server_memory_heap_size | v1.5 | 173998080 |

> If you are able to experiment it may be useful to see if the memory usage is smaller if you disable telemetry v2, just to minimize variables

Well, to be clear, turning off telemetry v2 in the new clusters would introduce a variable, because we were using it in 1.4 as well. 😅But since the new memory size doesn’t seem to be traffic-dependent, we could create a non-Istio-injected namespace for testing and manually create pods there with sidecars in different configurations, if there’s things you want to rule out.

**Comment by silverlyra** [comment]
Also, I want to say that overall we’re very happy with Istio 1.5! Mixerless telemetry now works well and produces counters that match our services’ own Prometheus request metrics, and we’ve seen a marked improvement in the tail latency for the service that’s our largest single deployment.

**Comment by howardjohn** [comment]
> Well, to be clear, turning off telemetry v2 in the new clusters would introduce a variable, because we were using it in 1.4 as well

If the memory of 1.5 with v2 was high and 1.5 without v2 was low it would mostly prove v2 is to blame here. The main reason I suspect (or at least want to rule this out) is because as far as I know that code has changed the most from 1.4 -> 1.5.

Another change that can be done is spinning up a pod with the `sidecar.istio.io/proxyImage: istio/proxyv2:1.4.7` annotation in the 1.5 cluster. Then we can compare a 1.4 proxy with a 1.5 control plane to a 1.5 proxy with a 1.5 control plane. You can also do the opposite. We don't properly test 1.5 proxy with 1.4 control plane by the way, so while it will probably work I recommend doing it on a dummy deployment.

You can also try to get a heap profile: https://github.com/istio/istio/wiki/Analyzing-Istio-Performance#memory-profile

Right now its hard to say whats going on so the best path forward is trying to change things and see if we can rule things out to narrow down the root cause

In our own testing we have not seen similar regressions, so its likely there is some aspect of your cluster (size, certain configs, etc) that is triggering something unexpected

**Comment by silverlyra** [comment]
We’ll try a pod with a 1.4 proxy. Is there a way I can launch a single 1.5 proxy with telemetry v2 disabled?

I tried the heap profile instructions for Istio < 1.6, but it seems like I have no way to make the `/var/log/envoy` directory:

```
istio-proxy@pod:/$ mkdir /var/log/envoy
mkdir: cannot create directory '/var/log/envoy': Read-only file system
istio-proxy@pod:/$ sudo mkdir /var/log/envoy
sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
istio-proxy@pod:/$ id
uid=1337(istio-proxy) gid=1337(istio-proxy) groups=1337(istio-proxy)
```

**Comment by silverlyra** [comment]
I went back to the [heap profile instructions](https://github.com/istio/istio/wiki/Analyzing-Istio-Performance#data-plane), but this time I scrolled up and saw the _Prerequisites_ section 🤦‍♀️.

I turned on `enableCoreDump`. I still had to make the `/var/log/envoy` directory in the `proxyv2` image itself, but at long last, we have heap dumps:

<img width="1744" alt="Screen Shot 2020-05-13 at 11 57 53 AM" src="https://user-images.githubusercontent.com/25393735/81853257-0fc87700-9511-11ea-8103-e2985366126e.png">

What should we do now? Would you like a copy?

**Comment by howardjohn** [comment]
that looks like we might be missing some symbols or something @lambdai how do wd get those?  Did you include the PPROF_BINARY_PATH=/tmp/envoy/lib part?

It may be helpful to upload the profile and maybe we can get the symbols as well

**Comment by silverlyra** [comment]
I did set `PPROF_BINARY_PATH`. `go tool pprof` wouldn’t resolve the symbols, but I installed `github.com/google/pprof` directly and for whatever reason, that works much better:

<img width="1754" alt="Screen Shot 2020-05-13 at 12 37 06 PM" src="https://user-images.githubusercontent.com/25393735/81857029-7ac87c80-9516-11ea-9191-db69729d44bf.png">

[profile001.pdf](https://github.com/istio/istio/files/4624282/profile001.pdf)
[tree.txt](https://github.com/istio/istio/files/4624284/tree.txt)
[envoy.prof.0002.heap.gz](https://github.com/istio/istio/files/4624285/envoy.prof.0002.heap.gz)

**Comment by howardjohn** [comment]
Thanks! That is super useful, looks like its part of RDS. @lambdai I think I recall you making changes to some memory usage aspects of RDS, any ideas?

**Comment by silverlyra** [comment]
Is there anything we can do on our end to dig deeper and find a cause?

**Comment by lambdai** [comment]
Sorry for super late reply.
I made the changes in RDS so that listeners share the C++ internal config if these listeners referring the same name of RDS. That's is landed before 1.5 so there is no low hanging fruit.

The memory introduced in 1.5 is the transition from xDS v2(istio pilot) to xDS v3(envoy) at envoy.

In istio 1.6 envoy will do a garbage collection-ish operation after config update. It may return some memory to OS.
In istio 1.7 xDS v3 config is introduced so less transition is need.
Both should help to reduce the memory usage.


Sorry but I don't think we are going to back port to 1.5

**Comment by silverlyra** [comment]
ah, thanks for the explanation @lambdai! Am I understanding right; there’s a runtime memory cost associated with the xDS transition period, but the transition will be done in Istio 1.7?

I’ll close this issue then since there’s no need to track it separately. We’ve learned it’s generally good to track the latest `1.x` release pretty closely – no need to backport. Thank you again!

**Comment by lambdai** [comment]
> ah, thanks for the explanation @lambdai! Am I understanding right; there’s a runtime memory cost associated with the Envoy xDS API transition period, but the transition will be done in Istio 1.7?

Exactly! The next time we see the cost will be the time when envoy introduce next generation xDS (xDS v4). No hard timeline yet but won't happen until 5 months from now.
