### ISSUE TITLE
Header ADD Operation in Virtual Service Cannot add to Content-Type because of Comma Separation

### ISSUE THREAD

**Issue by nprabala** [istio/istio#22850]
**Bug description**

**Expected behavior**
I set an add header operation for Content-Type with standard key:val. Most pages have that header already. I expect it to append the string I have for val directly with no modification. Because it comma separates values by default (even if I just set a single charset-utf8), this puts an invalid IANA ",charset=utf8" in my headers.  Content-Type is one of the headers that only accepts semicolon as a delimiter, not commas.
**Steps to reproduce the bug**
In a virtual service, put an add header operation of type:

headers:
  response:
    add:
      Content-Type: charset=utf-8

In the pages served by that VS, you will see the invalid Content Type served. This can break services that rely on properly formatted headers of that type. 

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```Kubectl: Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-502bfb", GitCommit:"502bfb383169b124d87848f89e17a04b9fc1f6f0", GitTreeState:"clean", BuildDate:"2020-02-07T01:31:02Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
```
Helm: Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
```

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
> (even if I just set a single charset-utf8)

I cannot reproduce this part specifically, maybe it has changed and you are on an older version though. 

As for the rest - 

if you don't want a comma separated list you should use `set` not `add`. This is how envoy works anyways, so we don't really have a choice: https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/core/base.proto#envoy-api-msg-core-headervalueoption. I think envoy behavior is correct here per http spec, comma separated is how you have a list of headers: https://stackoverflow.com/questions/3096888/standard-for-adding-multiple-values-of-a-single-http-header-to-a-request-or-resp. The problem you face here is you are not actually adding to Content-Type, which is not a list, you are trying to modify it. Essentially you are looking for a header rewrite, which is not supported in Envoy as far as I can tell: https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route.proto#envoy-api-msg-routeconfiguration

**Comment by nprabala** [comment]
You're right, I don't think rewrite is supported in Envoy (although that would be amazing if it were). I guess my confusion is that when I think about adding to a header, I think about tacking something onto it.  And headers like content-type might not be lists, but they have multiple values -- ie,  a MIME type and a charset, which  aren't required to be set. My issue is that  I have a resource that returns application/json without setting a specific charset. I want to set that charset. But set overwrites the entire header, and add throws in a comma which causes the whole thing to be unrecognizable. Using comma delimiters as a default removes a lot of functionality from header operations. If it just appended the string to that header, then users would have the option of setting semicolons vs commas as they thought best.

**Comment by howardjohn** [comment]
What is being asked here is essentially host header rewrite. We cannot support this unless Envoy does, so this would need to be moved to an Envoy feature request I think. In the mean time, it IS possible to do this with lua (and soon wasm) filter: https://blogs.sap.com/2019/02/11/kubernetes-security-secure-by-default-headers-with-envoy-and-istio/
