### ISSUE TITLE
option to create application container after envoy is ready

### ISSUE THREAD

**Issue by rokrokss** [istio/istio#22860]
**Describe the feature request**

User can choose to create the application container "after" the envoy is ready.

I've been developing a service that sends requests to dynamic config stores(which we use additional etcd for) on their initial steps.
But since that timing is earlier than envoy's ready state, the traffic sent gets lost.
I think the real problem is that traffic is not observable, which opposes to the core value of service mesh making all traffic observable.

I wanted to contribute to the source but I'm not 100% sure about this opinion or if there's no right solution currently.

**Comment by howardjohn** [comment]
see https://github.com/istio/istio/issues/11130. basically it's hard without a change to kubernetes

**Comment by rokrokss** [comment]
Thanks
