### ISSUE TITLE
Support more accurate line number in analyzer messages

### ISSUE THREAD

**Issue by jasonwzm** [istio/istio#22872]
This is treated as a follow-up issue of https://github.com/istio/istio/issues/17349. Initial work to indicate yaml chunk line number is done in https://github.com/istio/istio/pull/22824.

To be more accurate in the analysis message, a more accurate line number inside the yaml chunk would be preferable.

**Comment by esnible** [comment]
@jasonwzm What is needed to finish this?

**Comment by brian-avery** [comment]
Can this be closed? We have it listed in the 1.8 release notes.

**Comment by esnible** [comment]
@jasonwzm Can this be closed? ^^^

**Comment by esnible** [comment]
@jasonwzm Can this be closed? ^^^
