### ISSUE TITLE
MeshConfig reworking ideas

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#22871]
This is mostly just a brain dump of some ideas so we don't forget

Current config experience:
* MeshConfig is injected as env var to sidecars.
* Gateways mount meshconfig directly as file.
* There is a single meshconfig (per revision) - cannot override for specific proxies.
* Proxyconfig is nested within MeshConfig.

Issues:
* ProxyConfig is coupled to MeshConfig. This adds some confusion because we are configuring settings in meshconfig and passing them to the proxy which probably do nothing. There are however, some benefits to this, as if we decide a "mesh" setting needs to be a "proxy" setting, we have access to that information. So I think the current approach is more flexible, but a decoupled approach is more "correct".
* Gateways need to mount the meshconfig, so if its in another namespace this causes problems
* Its hard to override settings per proxy. There are some annotations for specific overrides (eg `sidecar.istio.io/discoveryAddress`), but no generic mechanism. This is a pretty common ask.

There have also been related discussions around [GatewayClass](https://docs.google.com/document/d/1JJXvQSINaAww-Hl_cdfs1QnkvfaIb6omNqzg4RXcQRY/edit#) for gateways to configure "deployment level" settings for gateways. There is also a somewhat corresponding Sidecar resource which could be the home for these settings, but would need to be duplicated into GatewayClass as well. It is feasible to move the proxyconfig out to a ProxyClass resource as well. In absence of using these objects to configure, the alternative for per-proxy config would be annotations - either a generic `proxyconfig` annotation, or many annotations for every option (not recommended),

A challenging problem with these configurations is that ideally these settings are not just runtime settings but also install options. For example, CPU resources. This is easy on the sidecar, as the injector handles it, its more challenging for the gateway, which is currently installed by helm/istioctl/other. To truly have some CRD controlling the gateway deployment we would need to completely rework how we deploy Gateways.

@costinm @nrjpoddar

**Comment by howardjohn** [comment]
Costin: we can have values.yaml pass Proxyconfig through to gateway. Then we can send the full proxyconfig as node metadata. This will allow future proofing+support for the new gateway settings.

me: I think we should configure it as an annotation. The gateway will load this through downward API, sidecar injector will do its own magic for this. For VMs, they can still use Env (which is needed for injector support). The alternative is to use annotation for sidecar and env for gateway, which is simpler but a less consistent API for users

Louis: one way to mimic classes without creating CRD's is to allow their creation inside mesh-config as named things, then reference them from Gateway via annotation or field

**Comment by seflerZ** [comment]
I agree with decoupling. The MeshConfig has become a mess. Many components(Pilot, Sidecar, Gateway) depends on this and it's not responsibility clear.

**Comment by costinm** [comment]
I think the key to ProxyConfig is to move it out of MeshConfig - keep in mind MeshConfig has the _default_ only. 

We already allow sidecars to specify the ProxyConfig as an annotation  - which works if you have control over the deployment. I think the right change is a combination of:
1. Make ProxyConfig a proper CRD - there is no reason not to do it that I'm aware. It'll need a selector like EnvoyFilter and Sidecar
2. Include ProxyConfig as a field in Sidecar and Gateway - with clear indication the fields are 
'alpha' and subject to change ( we had many discussions about evolving the 'stable' APIs without 
having new fields expected to be beta immediately)
3. Include ProxyConfig as a field in EnvoyFilter - i.e. escape path
4. Continue to support ProxyConfig as a config map, with some way to mount it in gateways and pods - like well-known name ( istio-REV). But it has to be in the namespace of the sidecar or gateway, not istio-system.

The main requirement to me is to allow this to have parity with the annotation - i.e. modified by the 
gateway / sidecar owner, not by istio-system owner.

**Comment by howardjohn** [comment]
> We already allow sidecars to specify the ProxyConfig as an annotation

If it wasn't clear, this works for GW as well

> Make ProxyConfig a proper CRD - there is no reason not to do it that I'm aware. It'll need a selector like EnvoyFilter and Sidecar

This will require Gateway reading the CR directly. If we use the same global "config namespace" as other selector based resources it wil also need access to that - should be fine though, can be done with two Roles instead of ClusterRole.

> Include ProxyConfig as a field in Sidecar and Gateway - with clear indication the fields are
'alpha' and subject to change ( we had many discussions about evolving the 'stable' APIs without
having new fields expected to be beta immediately)

I think this is problematic for GW as GW is not 1:1 with a deployment as we discussed many times on Neeraj's GW topology doc.

---

In my opinion, the annotation is good enough. What benefit do all of these new options raise?

**Comment by costinm** [comment]
> > We already allow sidecars to specify the ProxyConfig as an annotation
> 
> If it wasn't clear, this works for GW as well

How ? Users don't directly annotate the GW. I know GW can read the env variable - but it's
usually an install option in values. 


> 
> > Make ProxyConfig a proper CRD - there is no reason not to do it that I'm aware. It'll need a selector like EnvoyFilter and Sidecar
> 
> This will require Gateway reading the CR directly. If we use the same global "config namespace" as other selector based resources it wil also need access to that - should be fine though, can be done with two Roles instead of ClusterRole.

Not really - both Gateway and Sidecars can read the CR from their own namespace, certainly 
not the 'config namespace'.  Just like annotation, it should be possible with only permissions
in the namespace where the workload is running. 

For Sidecars - the injector would read it.

Once we have the XDS client code in agent - the Gateway and Sidecar only need the URL
(and cert) of the discovery server, and Istiod can push the ProxyConfig.

> 
> > Include ProxyConfig as a field in Sidecar and Gateway - with clear indication the fields are
> > 'alpha' and subject to change ( we had many discussions about evolving the 'stable' APIs without
> > having new fields expected to be beta immediately)
> 
> I think this is problematic for GW as GW is not 1:1 with a deployment as we discussed many times on Neeraj's GW topology doc.

You are right, it would map better to GatewayClass. 

I think Sidecar is not a bad fit, but maybe ProxyConfig can be a standalone or just part of GatewayClass ( that can also be used for sidecars).

> 
> In my opinion, the annotation is good enough. What benefit do all of these new options raise?

The critical problem is Pods created using K8S API directly, by code - like CertManager or Skaffold.
In such cases we can't 'annotate' without making code changes to the apps, which is quite 
inconvenient - hardcoding config in code is not pretty, and in some cases you can't change the 
binaries. The only workaround I found is to use a separate control plane revision with a different ProxyConfig.
 
Many of the ProxyConfig settings can be implemented without a pod restart/reinject - including
discoveryAddress, so some of the 'move to different revision' or 'fallback' use cases would be better handled. It can go even as far as hot swap of envoy binary without reinject.

**Comment by howardjohn** [comment]
For gateway we read annotations in the agent via downward API and apply those. Not sure why you say users cannot annotate the gateway, there are helm values to do so and kustomize, etc can always patch it

**Comment by dgn** [comment]
What I don't like about annotating the gateways is that it's very static, whereas ProxyConfig can change anytime. So I'd prefer the CRD approach, where gateways can actually watch ProxyConfig and react to changes immediately.

**Comment by dgn** [comment]
I'm currently looking at removing `Values` from the injection template, which includes moving a bunch of config options into MeshConfig and ProxyConfig. But I'd prefer it if this solution also worked for Gateways (ie immediate apply of new MeshConfig/ProxyConfig to the injector + gateways)

**Comment by hzxuzhonghu** [comment]
> So I'd prefer the CRD approach, where gateways can actually watch ProxyConfig and react to changes immediately.

We have all got a consensus, istio-agent and also proxies should connect to its istio control plane, not to mess up with kubernetes control plane.

**Comment by dgn** [comment]
> > So I'd prefer the CRD approach, where gateways can actually watch ProxyConfig and react to changes immediately.
> 
> We have all got a consensus, istio-agent and also proxies should connect to its istio control plane, not to mess up with kubernetes control plane.

I see. How will MeshConfig be propagated to the proxies?

**Comment by hzxuzhonghu** [comment]
https://github.com/istio/istio/blob/master/pilot/cmd/pilot-agent/config.go#L124 This is the current way.

**Comment by dgn** [comment]
> https://github.com/istio/istio/blob/master/pilot/cmd/pilot-agent/config.go#L124 This is the current way.

I know how it works currently, but this process has its issues:

- You cannot mount the istio configmap if the proxy is running in another namespace than the control plane
- The MeshConfig that is injected by the sidecar-injector is static and quickly outdated
- The annotations are only meant for overrides

So there's currently no way to propagate MeshConfig changes automatically to the proxies outside of the control plane namespace (which is why I was suggesting CRDs that could be watched). Another way would be an MCP-like protocol that sends it over the wire from istiod to the istio-agents.

**Comment by sdake** [comment]
@howardjohn I am not certain this discussion is finished, so I marked this issue as staleproof and reopened it. If you wish to close it, feel free to do so.

Cheers,
-steve

**Comment by howardjohn** [comment]
Most of these are addressed, rest are handled by https://github.com/istio/istio/issues/31400
