### ISSUE TITLE
Debug inject not work

### ISSUE THREAD

**Issue by dominicqi** [istio/istio#22870]
**Bug description**
The `InitDebug` method called before InitWebhook. So then `/debug/inject` endpoint always return 404.
https://github.com/istio/istio/blob/4214ab3cda249ea64b927adc687fb5bed844cbc2/pilot/pkg/bootstrap/server.go#L250-L269

https://github.com/istio/istio/blob/4214ab3cda249ea64b927adc687fb5bed844cbc2/pilot/pkg/bootstrap/server.go#L453

**Expected behavior**
Show the right inject template.

**Comment by hzxuzhonghu** [comment]
Thanks for the report, let me try if i can fix
