### ISSUE TITLE
namespace issue of running `operator init`

### ISSUE THREAD

**Issue by richardwxn** [istio/istio#22887]
if following the guide: https://istio.io/docs/setup/install/standalone-operator/ to run `istioctl operator init` command, with no -f flag provided, then the operator recourses would be installed into istio-opeartor namespace, but no istio namespace would be created, so later steps would be failing because of no istio namespace. So we have to manually create namespace, e.g. istio-system first then run`kubectl apply -f cr.yaml`.

We may need to add this missing part in to the doc or we should create istio-system ns when running `opeartor init` command with no CR provided.

@ostromart @morvencao

**Comment by morvencao** [comment]
Currently we have enhanced doc to guide user create `istio-system` namespace after `operator init...`, see: https://github.com/istio/istio/tree/master/operator#controller-in-cluster

**Comment by richardwxn** [comment]
oh great, but it is not added in the istio.io instruction actually
