### ISSUE TITLE
istiod always fails to start when useMCP is enabled

### ISSUE THREAD

**Issue by nak3** [istio/istio#22896]
[x] Installation

**Bug description**

When `useMCP` is enabled, istiod pod fails to start.

```
$ kubectl get pod -n istio-system   istiod-6548b95486-g7pzc
NAME                      READY   STATUS    RESTARTS   AGE
istiod-6548b95486-g7pzc   0/1     Running   0          7m30s
```

In istiod pod's log, it keeps printing this log:

```
2020-04-13T01:22:21.963171Z	error	mcp	Failed to create a new MCP sink stream: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:15019: connect: connection refused"
```

**Steps to reproduce the bug**

Install istio with this istiooperator: https://gist.github.com/nak3/cabf0aa3d98b69143be5a3daf03e8534

**Version**

- istio 1.5.1

**Side note**

- I do not stick to useMCP, but just use galley for the validation. MCP is necessary as per https://github.com/knative/serving/pull/7414#discussion_r407207266
- I checked `demo` profile, but useMCP is not enabled even `demo` profile. It would be great if we could get some reference config.

**Comment by seflerZ** [comment]
Galley is now part of istiod, it's not necessary to use MCP any more, I suppose.

**Comment by nak3** [comment]
Yeah, I was also advised to not enable galley in https://github.com/knative/serving/pull/7414#discussion_r407287914
So if use MCP is broken and not used anymore, the config itself should be removed from code?

**Comment by melvinRlabelbox** [comment]
I am going to reference this to https://github.com/istio/istio/issues/21991

as I believe its related on the validationwebhook, if istiod gets restarted port 15017 disappears. and MCP is not enabled. It seems that its being reference inside istiod.
