### ISSUE TITLE
Constrain integration tests with build tags

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#22903]
Currently we have many test targets like `mixer-test` `galley-test` and then combine them with `test`. This adds reliance on our makefiles, rather than standard go tooling (`go test ./galley/...`). Additionally, I think its a bit slower since it isn't properly parallelized

I suggest we instead add build tag to integration tests:

```
// +build integ
```

Then to run these tests you would run `go test -tag=integ`. To run all unit tests, you can just run `go test ./...`, and avoid makefiles. Any thoughts?

**Comment by ericvn** [comment]
Pros:
  - Would like to see a tag for those tests that don't alter the control plane (can be run with `--istio.test.kube.deploy=false`). This might help with running tests on immutable infrastructures. So maybe we could publish a set of common tags.

Cons:
  - Removes the running of tests from the makefile which means that one would do a `make shell` and then run the tests there, or run them locally outside the build container. Does this make it a little more complex?

**Comment by howardjohn** [comment]
> Removes the running of tests from the makefile 

We can still keep them if we want. This just makes it more flexible for people using `go test` directly. Also you can do `./common/scripts/run.sh go test ./...`. But for the most part I think all unit tests work on pretty much all platforms? Maybe some of rthe envoy ones do not on osx though
