### ISSUE TITLE
Auto doc gen for istio-proxy

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#22909]
Istio-proxy extensions contain protos which should be documented just like istio/api protos.

1. Add doc gen to istio-proxy ci/cd
2. Publish the artifacts to istio.io

The general pipeline for that is to set up the make file for such generation in istio-proxy. You can mimic what is currently there in other APIs. Things to edit are the make file and proto files. There are three things that are important inside the proto file: 

 *  The front matter annotations, e.g. [here](https://github.com/istio/api/blob/master/networking/v1alpha3/destination_rule.proto#L22) 
 *  The overview section is added right above the package definition of the proto 3. The description of each field is right above the field itself. Once it is done, the generated files need to be added in istio.io repo to be included in the website.

**Comment by mandarjog** [comment]
cc @jasonwzm

**Comment by kyessenov** [comment]
FYI I'm trying to remove protobuf from stats filter. As part of that I'd need to get rid of its config proto.

**Comment by howardjohn** [comment]
Any reason these cannot/should not just be in the istio/api repo?

**Comment by mandarjog** [comment]
Unnecessary coupling with istio/api , multi repo hops.
I am ok copying out to istio/api
