### ISSUE TITLE
Istiod to issue certificate to a remote cluster

### ISSUE THREAD

**Issue by myidpt** [istio/istio#22918]
**Describe the feature request**
Istiod needs to be able to issue certificate to workloads in a remote cluster. This enables using a single istiod for multiple clusters.

**Describe alternatives you've considered**
Deploying istiod in the remote cluster.

**Additional context**

**Comment by linsun** [comment]
@myidpt Would need hand holding for sure, can you provide more details in the issue on what is exactly needed?

**Comment by irisdingbj** [comment]
@linsun @myidpt THis is exactly what https://github.com/istio/istio/pull/22384 aimed to do. I am waiting further review now.

**Comment by linsun** [comment]
@irisdingbj can you elaborate how #22384 would cover this?  I took a quick look and it is not obvious as #22384 seems to plugin existing cert which we already do share the same root cert for shared control plane multicluster model.

**Comment by hzxuzhonghu** [comment]
@myidpt What is the gap now? Can't istio-agent within remote cluster communicate with istiod in the primary cluster?

**Comment by irisdingbj** [comment]
with the change in #22384, we will generate root cert and two intermidiate CA cert for use of multi-cluster and VM.:
eg: `istioctl manifest apply --cert-dir=/etc/certs` if `/etc/certs` is empty it will generate root cert and two intermidate CA key and certs and save them under `/etc/certs` .   If `/etc/certs` have related root cert, ca cert and key already, will use it as the same behaviour  described in https://istio.io/docs/tasks/security/plugin-ca-cert/

**Comment by myidpt** [comment]
Any help on the implementation from the community is greatly appreciated. Otherwise it's risky to get this delivered in 1.6.
The implementation needs to touch istiod, enabling it to authenticate the JWTs from external clusters.
Currently the authentication is done by:
https://github.com/istio/istio/blob/1d3b136325a5592511f72a9b041ea396bdbd5180/security/pkg/k8s/tokenreview/k8sauthn.go#L135
The API server address is defined here:
https://github.com/istio/istio/blob/1d3b136325a5592511f72a9b041ea396bdbd5180/security/pkg/server/ca/server.go#L43
So it validates the JWT by calling the TokenReview API on the local cluster.

We need to enable it to be able to call the apiserver on a remote cluster.
I believe today, with shared control plane setup, istiod is able to access the resources from other clusters. We can do the same for the TokenReview feature.

**Comment by myidpt** [comment]
@irisdingbj It seems your PR is trying to build multi-level PKI - it's another angle to solve the multicluster PKI problem.
This issue is focusing on using a single CA to issue certs for workloads in multiple clusters.

**Comment by linsun** [comment]
@myidpt thanks, I think I got it at a high level.  Basically the main cluster has access to remote cluster via the secret (e.g. istio-remote-secret-remote0 ).  When istio-agent in remote cluster calls the main cluster to authenticate the JTW token used for CSR, the main cluster's istiod need to use that secret (e.g. istio-remote-secret-remote0) to call the remote cluster's API server to validate if the JWT token is valid.  If it is valid, then grant the CSR thus the certificates can be issued to istio-agent at remote cluster.

Please let me know if this aligns what you think.

cc @GregHanson

**Comment by myidpt** [comment]
@linsun Yes, that's correct.

**Comment by hzxuzhonghu** [comment]
Very clear, so it seems a simple fix can achieve that

**Comment by myidpt** [comment]
@hzxuzhonghu Hey Zhonghu, are you going to help on this? :)

**Comment by linsun** [comment]
@myidpt thank you!  I talked to @GregHanson he is interested in helping out.  @irisdingbj is also interested to help.  I'm going to remove community help needed.   Would appreciate @myidpt and @hzxuzhonghu's help for review.

**Comment by irisdingbj** [comment]
> @irisdingbj It seems your PR is trying to build multi-level PKI - it's another angle to solve the multicluster PKI problem.
> This issue is focusing on using a single CA to issue certs to workloads in multiple clusters.

Thanks! clear to me now.

**Comment by myidpt** [comment]
Thank you everyone. Added @GregHanson and @irisdingbj ass assignees now.

**Comment by myidpt** [comment]
Hey @irisdingbj we need to add this approach to the multi-cluster setup UG. Can you send me your Email address so that I can add you as an editor to a doc we are working on?

**Comment by irisdingbj** [comment]
@myidpt both `dingsj@cn.ibm.com` and `irisdingbj@gmail.com` works

**Comment by myidpt** [comment]
Thanks. Added you to the doc editor @irisdingbj

**Comment by irisdingbj** [comment]
@myidpt where can I find the doc you shared? Thanks!

**Comment by sdake** [comment]
@myidpt I am covering for @irisdingbj while she is on holiday. Please add me to the document `steven.dake@gmail.com`. I need this information for the WG leads meeting tomorrow to address: https://github.com/istio/istio/pull/22384

It is clear to me that this PR is needed. As we punted complete automation of multicluster to 1.7 or later, it is unclear if @irisdingbj 's PR needs a rebase, review, and merge, or not.

Cheers
-steve

**Comment by myidpt** [comment]
Shared with you, Steven. #22384 is a good automation, though the PR itself requires improvements. Making it available in 1.7 makes sense to me.

**Comment by linsun** [comment]
Closing this now, my thanks to @irisdingbj @hzxuzhonghu @myidpt for the help in delivering/providing consultation to this feature.  I've validated it today (with https://github.com/istio/istio/pull/23942) and it works nicely.
