### ISSUE TITLE
Envoy filter name inconsistency

### ISSUE THREAD

**Issue by Shikugawa** [istio/istio#22926]
**Describe the feature request**
I think that istio/proxy envoy filter name has inconsistency.
https://github.com/istio/proxy/blob/master/src/envoy/utils/filter_names.cc

**Describe alternatives you've considered**
I prefer to use names easier to understand.

```
const char IstioFilterName::kJwt[] = "envoy.istio.jwt_auth";
const char IstioFilterName::kAuthentication[] = "envoy.istio.authn";
const char IstioFilterName::kAlpn[] = "envoy.istio.alpn";
```
It seems that it is difficult to migrate seamlessly. So in my design, 
1) To accept old/new filter names on control-plane
2) Destroy old name from istio/proxy
3) To accept new filter name only

**Additional context**

**Comment by kyessenov** [comment]
@Shikugawa the filter names do not have to be used via xDS, so there is no need to keep them readable. The names don't include "envoy" because some could be compiled against nginx at some early point.
