### ISSUE TITLE
Namespaced Prometheus components created before namespace

### ISSUE THREAD

**Issue by uhinze** [istio/istio#22936]
**Bug description**
When installing Istio with the default profile, the following error is shown 4 times:
```
Error from server (NotFound): error when creating "STDIN": namespaces "istio-system" not found
```

This is likely due to Prometheus components being listed in the `manifest generate` output before the namespace.

**Expected behavior**
Resources are created in correct order.

**Steps to reproduce the bug**
`istioctl manifest generate | kubectl apply -f -`

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
$ istioctl version --remote
client version: 1.5.1
control plane version: 1.5.1
data plane version: 1.5.1 (2 proxies)

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.27", GitCommit:"145f9e21a4515947d6fb10819e5a336aff1b6959", GitTreeState:"clean", BuildDate:"2020-02-21T18:01:40Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by uhinze** [comment]
Found another issue that fixes this #18844, but it's again present in 1.5.1

**Comment by morvencao** [comment]
It is recommended to use `istioctl manifest apply...` if you 're trying to deploy istio, since it will handle all the dependency issues.

`istioctl manifest generate | kubectl apply -f -` will not care about the object order.

**Comment by uhinze** [comment]
Thanks for the reply @morvencao. Can confirm that `manifest apply` directly will work, will switch to that now.

However, the namespace is still in the `generate`d manifest:
```
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    istio-operator-managed: Reconcile
    istio-injection: disabled
```

**Comment by morvencao** [comment]
@uhinze Looks like you're on 1.5.x, the namespace will be removed from `istioctl manifest generate` in master branch.
