### ISSUE TITLE
Unable to access the "builds inside containers" google doc

### ISSUE THREAD

**Issue by naveensrinivasan** [istio/istio#22943]
**Bug description**
I am unable to access the google doc [builds inside containers](https://docs.google.com/document/d/1vBEt4RyHu2Ywqx6CQk8pHm6wrJCIi4UNLw3xrJdHFtA
) mentioned in section https://github.com/istio/istio/wiki/Preparing-for-Development#setting-up-docker. I am getting Access Denied. 

I would hope that it should be open to everyone.

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
You need to join the google group. See https://istio.io/about/community/join/. You should be autoapproved.

**Comment by naveensrinivasan** [comment]
Sounds good. Thanks
