### ISSUE TITLE
Incorrect Quotes in the documentation is causing the builds to fail

### ISSUE THREAD

**Issue by naveensrinivasan** [istio/istio#22945]
**Bug description**
https://github.com/istio/istio/wiki/Preparing-for-Development-Mac#setting-up-environment-variables has reference to `export HUB=“docker.io/${USER}”` which is evaluating to `“docker.io/anagramsylvan”` instead of `docker.io/anagramsylvan`. The `export HUB=“docker.io/${USER}”` has incorrect quotes that are causing issues. It should be `export HUB="docker.io/${USER}"`.

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
thanks, fixed
