### ISSUE TITLE
Enabling AccessLog Sampling filter results in misconfiguration failures

### ISSUE THREAD

**Issue by gargnupur** [istio/istio#22952]
**Bug description**
Enabling AccessLog Sampling filter along with other filters results in misconfiguration failures 

**Expected behavior**
No error

**Steps to reproduce the bug**
Enable accesslog sampling filter at the time of installation of Istio along with stackdriver and metadata exchange filter.
This results in misconfiguration from envoy-wasm that "stackdriver filter has been configured incorrectly"

**Comment by jplevyak** [comment]
Can you attach the SHA for istio/istio that you are using and the profile ?

**Comment by gargnupur** [comment]
@jplevyak : This is on latest branch of istio/istio(kinda any SHA from last 2 weeks for sure).  
I was running using integration test framework but should repro with default profile with following values set:
1) "telemetry.enabled" = "true"
2) "telemetry.v1.enabled" = "false"
3) "telemetry.v2.enabled" = "true"
4) "telemetry.v2.stackdriver.enabled" = "true"
5) "telemetry.v2.stackdriver.logging" = "true"
# I added following here: https://github.com/istio/istio/compare/master...gargnupur:nup_add_filter_option?expand=1
6) "telemetry.v2.accessLog.enabled" = "true"
7) "telemetry.v2.accessLog.logWindowDuration" = "43200s"

**Comment by jplevyak** [comment]
Are you using the demo app?    The applying what configuration?

**Comment by jplevyak** [comment]
How do I repro with the integration test framework ?
