### ISSUE TITLE
[Envoy Filter] how to add http header with source service name, source namespace?  [lua]

### ISSUE THREAD

**Issue by johnzheng1975** [istio/istio#22961]
**Describe the feature request**
[Envoy Filter] how to add http header with source service name, source namespace?

For each http request, I hope add below in http header
* Source http request's service name
* Source http request's namespace

Thanks a lot.

**Describe alternatives you've considered**

**Additional context**

**Comment by johnzheng1975** [comment]
Seems does not support.
Work around is:
Add envoyfilter based on namespace (workload), then add namespace exact name (hard code)

**Comment by johnzheng1975** [comment]
I reopen this feature request:
My requirements: for each http/mtls request, server need know which is source namespaces. (add source namespace in http header)

The upper workaround is ugly.
In a cluster which has 20 namespaces, I need add 20 enovyfilter for each namespace.

Is there any better way to implement this? This is a basic requirement I think.

**Comment by johnzheng1975** [comment]
Can enovyfilter lua script read source.namespace? Thanks.
https://istio-releases.github.io/v0.1/docs/reference/config/mixer/attribute-vocabulary.html

**Comment by prai-lbg** [comment]
@johnzheng1975 i had a similar requirement where we needed some source namespace information on istio access logs. Managed to get some info of the downstream service using x-envoy-downstream-service-cluster header - https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#x-envoy-downstream-service-cluster  

`apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: custom-header-filter
  namespace: istio-system
spec:
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        context: SIDECAR_OUTBOUND
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
      patch:
        operation: MERGE
        value:
          typed_config: 
            "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
            add_user_agent: true`

`apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    extensionProviders:
      - name: envoy
        envoyFileAccessLog:
          path: /dev/stdout
          logFormat:
            labels:
              src_ns_1: "%REQ(X-ENVOY-DOWNSTREAM-SERVICE-CLUSTER)%"
              src_ns_2: "%REQ(X-ENVOY-DOWNSTREAM-SERVICE-NODE)%"`


After sending a request, i could see on the access logs on the destination service: `{"src_ns_1":"curl.default","src_ns_2":"sidecar~10.124.2.36~curl-deployment-75d76f99f4-wxwpb.default~default.svc.cluster.local"}`

Hope this helps in some way. I'm still looking at other methods but if you have a better working solution, then pls share. Thanks
