### ISSUE TITLE
validatingwebhookconfiguration does not have correct ownerRef

### ISSUE THREAD

**Issue by XanderStrike** [istio/istio#22966]
**Bug description**

We are intermittently experiencing the issue described in [this comment](https://github.com/istio/istio/issues/19164#issuecomment-562379885) where the validatingwebhookconfiguration isn't cleaned up. We're using Kapp to deploy istio, and since the configuration doesn't have an owner reference it doesn't know to clean this up.

This was fixed and the previous issue was closed, but the fix was later reverted [here](https://github.com/istio/istio/pull/19750).

**Expected behavior**

Kapp and other tools can clean up Istio installations including resources created out of band.

**Steps to reproduce the bug**

Create an istio manifest with istioctl, apply it, delete it, observe resources left over

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

1.4.5

**How was Istio installed?**

Manifest generated from istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**

1.14.10-gke.27. 5 nodes. n1-standard-4

**Comment by howardjohn** [comment]
When you say "delete it" what are you doing?
