### ISSUE TITLE
Expand operator selector tests to cover gateways

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#22973]
Build upon https://github.com/istio/istio/issues/19458 which added for Istio. We should check selectors all line up for gateways. We can do this with the default gateway, as well as with a custom gateway which has custom labels applied

**Comment by adiprerepa** [comment]
I'm going to take a shot at this. @howardjohn What do you mean by selector?

**Comment by adiprerepa** [comment]
I'm going to take a shot at this.
