### ISSUE TITLE
Istio-tracing is giving CrashLoopBackOff

### ISSUE THREAD

**Issue by itsLucario** [istio/istio#22988]
**Bug description**
I have applied istio manifest using `istioctl manifest apply  --set values.grafana.enabled=true --set values.kiali.enabled=true --set values.prometheus.enabled=true --set values.tracing.enabled=true`

Once the setup completes. When I do kubectl get pods -n istio-system I see istio-tracing pod constantly restarting and I see event ingress-gateway ready status is 0/1.

NAME                                   READY   STATUS             RESTARTS   AGE
grafana-5f6f8cbf75-t55qp               1/1     Running            0          13m
istio-ingressgateway-c8464fbbf-vgctq   0/1     Running            0          13m
istio-tracing-9dd6c4f7c-hlvlm          0/1     CrashLoopBackOff   7          13m
istiod-646746688-mblsd                 1/1     Running            0          14m
kiali-869c6894c5-2wr52                 1/1     Running            0          13m
prometheus-c89875c74-p6wdq             1/2     Running            0          13m

Events in istio-tracing component 
Events:
  Type     Reason     Age                 From                Message
  ----     ------     ----                ----                -------
  Normal   Scheduled  <unknown>           default-scheduler   Successfully assigned istio-system/istio-tracing-9dd6c4f7c-hlvlm to ac-worker
  Normal   Created    20m (x2 over 21m)   kubelet, ac-worker  Created container jaeger
  Normal   Started    20m (x2 over 21m)   kubelet, ac-worker  Started container jaeger
  Warning  Unhealthy  20m (x6 over 21m)   kubelet, ac-worker  Liveness probe failed: HTTP probe failed with statuscode: 503
  Normal   Killing    20m (x2 over 21m)   kubelet, ac-worker  Container jaeger failed liveness probe, will be restarted
  Warning  Unhealthy  20m (x10 over 21m)  kubelet, ac-worker  Readiness probe failed: HTTP probe failed with statuscode: 503
  Normal   Pulled     20m (x3 over 21m)   kubelet, ac-worker  Container image "docker.io/jaegertracing/all-in-one:1.16" already present on machine
  Warning  BackOff    92s (x59 over 16m)  kubelet, ac-worker  Back-off restarting failed container

**Expected behavior**
All the istio components should startup successfully.

**Steps to reproduce the bug**
Setup istio using 
`istioctl manifest apply  --set values.grafana.enabled=true --set values.kiali.enabled=true --set values.prometheus.enabled=true --set values.tracing.enabled=true`
and check for the pod status

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
**istioctl version --remote**
client version: 1.5.1
control plane version: 1.5.1
data plane version: none

**kubectl version**
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:38:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:30:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
istioctl manifest apply  --set values.grafana.enabled=true --set values.kiali.enabled=true --set values.prometheus.enabled=true --set values.tracing.enabled=true

**Environment where bug was observed (cloud vendor, OS, etc)**
Ubuntu 18

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive
[istio-dump.tar.gz](https://github.com/istio/istio/files/4485879/istio-dump.tar.gz)
) by attaching
the dump file to this issue.

**Comment by Lucaarioo** [comment]
I noticed this is happening specifically when I run k8 with one master and one worker.
When I run it as a single control plane node without worker Istio works fine.
