### ISSUE TITLE
Istio is giving 503 error with no healthy upstream error message when pods get evicted and comes back up.

### ISSUE THREAD

**Issue by chandra210893** [istio/istio#22986]
**Bug description**
Ideally pods goes down and come up when there are lack of resources on individual nodes to other nodes. During this time when it happens across multiple times and incase if it is taking a while for pod to come up, istio is still giving “no healthy upstream” error on browser when the external url for the pod is hit. Can anyone help me with this. Do I need to add any external flag or do I need to do any application level change. One solution I found is virtualService have retry strategies like attempts and perTryTimeout. But I don’t feel this is the right way to be implemented in production, either it should be something can be implemented in istio-proxy or istio-ingressgateway to get ride of this.

**Affected product area**
Production

Istio ingressgateway and virtualservice

**Expected behavior**
When pods go to evicted state and comes back up istio should be able to route the traffic seamlessly.

**Steps to reproduce the bug**
When pods get evicted due to memory hike and new pod comes up. The istio shows an error **"no healthy upstream"** even though pod comes up successfully and application is running fine.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.4.2

**How was Istio installed?**
Istio is installed using helmchart

**Environment where bug was observed (cloud vendor, OS, etc)**
Cloud

**Comment by chandra210893** [comment]
@istio-policy-bot can you please provide an update regarding this issue. Our production systems are getting affected with on daily basis and we are holding them up with some temporary work arounds. Kindly do the needful at the earliest possible.

**Comment by chandra210893** [comment]
Team, Any update on this ?

**Comment by framled** [comment]
@chandra210893 did you fix this issue, I have the exactly same problem.
