### ISSUE TITLE
Why istio can‘t achieve istio-config self-canary

### ISSUE THREAD

**Issue by thinkin** [istio/istio#22992]
**Describe the feature request**
for example，there are service A accessing service B， now  i want change B'Loader balancer policy for A, but i want it canary，
first step：Take effect for  A pioneer instance
then：Take effect for all A instance

**Describe alternatives you've considered**

**Additional context**

**Comment by howardjohn** [comment]
Please see https://github.com/istio/istio/issues/7794 for more info. Thanks
