### ISSUE TITLE
Istio 1.5.1 provided root cert rotation not supported

### ISSUE THREAD

**Issue by EItanya** [istio/istio#22993]
---
name: Istio 1.5.1 provided root cert rotation not supported
about: istiod and new sds model does not support root cert rotation, specifically when using a provided root cert and CA
---

**Bug description**

Root cert rotation requires deleting both pilot, and the workloads as of istio > 1.5.0

Istiod (pilot) only picks up a provided Root CA when it is initially started up.
https://github.com/istio/istio/blob/master/pilot/pkg/bootstrap/istio_ca.go#L481
There is a cert rotator in the CA, but it is only turned on for self-signed CA. 
This means that istiod needs to be restarted to pick up a new Root Cert.

Secondly, the istio-agent now retrieves the Root Cert from pilot via the returned 
[Cert Chain](https://github.com/istio/istio/blob/502423c80c0a14b65de3172c359246af7c45aee6/security/pkg/nodeagent/cache/secretcache.go#L814). 
This means that the only time the Root Cert for a workload is updated is when it sends a CSR. 
And currently the istio-agent has no way to know when the Root Cert has been updated or changed.

The istio-agent does have a way of manually sending config SDS updates to envoy, but currently 
it is only used to rotate existing certs before they expire.

**Expected behavior**

When updating the Istio Root Cert and CA cert, it should be picked up and rolled out to the workloads.
In light of security concerns, it is often beneficial to rotate a root cert by temporarily using 2. Support
for this workflow would be ideal.

**Steps to reproduce the bug**

Install Istio, only need istiod (pilot)
```
istioctl manifest apply -f - <<EOF
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  profile: minimal
  values:
    global:
      pilotCertProvider: kubernetes
      controlPlaneSecurityEnabled: true
      mtls:
        enabled: true
    security:
      selfSigned: false
EOF
```

Label the default namespace for injection
```
kubectl label namespace default istio-injection=enabled
```

Deploy the 1.5 bookinfo app 
```
kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.5/samples/bookinfo/platform/kube/bookinfo.yaml
```

Generate and deploy a new Root Cert and intermediate CA using the [following instructions](https://github.com/istio/istio/tree/1.5.1/samples/certs).

This exposes the first part of the behavior which could be problematic. In order to rotate this cert we have to restart istiod. When citadel and pilot
were seperate this was less of a problem. However, restarting the control-plane seems like far from ideal behavior.

For demonstrations sake, let's restart the istiod pod.
```
kubectl delete pod -n istio-system -l app=istiod
```

At this point I would expect istiod to begin to roll out the new root cert to the workloads. However, as mentioned earlier that does not happen.
To check this run:
```
istioctl pc secret <pod-name of local product-page>  -ojson
```
It will not contain the Provided root cert from the instructions above.
However, if you delete the same pod, and then re-run the command, it will have the correct certs. 

As mentioned earlier, this is due to the fact that the workloads are not watcing for a root-cert change, and they are now the ones responsible for sending the 
CSR to pilot. In order to fix this, either the workloads need to be watching for root-cert changes, or pilot needs to alert them somehow.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**
Kubernetes ENV: KinD v1.17
OS: OSX Catalina

**Comment by JimmyCYJ** [comment]
Thanks @EItanya, this is a feature gap. Some design work is required. @myidpt

**Comment by myidpt** [comment]
Today the root cert rotation propagation will need to take up to the 1/2 - 1 TTL of the workload certs. I think this should be fine. We could improve it but it's not a high-priority task as I understand.

**Comment by nrjpoddar** [comment]
@myidpt I'm not following your comment above. The bug seems to suggest that in non self signed mode, rotations of intermediate certificates via `cacerts` secret are not monitored by istiod but that used to happen in Citadel.
