### ISSUE TITLE
istioctl version must show the tagged version number

### ISSUE THREAD

**Issue by ahmetb** [istio/istio#230]
```
Version: stable-621b2c4
GitRevision: 621b2c4
GitBranch: master
User: jenkins@ubuntu-16-04-build-97adf01b50c17
GolangVersion: go1.8
```

It looks like git revision is there however the tag number isn't.

You can use `git describe --always --tags --dirty` to stamp the version number.

**Comment by sebastienvas** [comment]
Thanks. We did this release a little fast so we did not rebuild the binary just tagged them.

**Comment by sebastienvas** [comment]
/istioctl version
Version: 0.1.2-6dbd19d
GitRevision: 6dbd19d
GitBranch: master
User: jenkins@ubuntu-16-04-build-b25b61f1c46e2
GolangVersion: go1.8.1
