### ISSUE TITLE
iptables-restore v1.6.1: iptables-restore: unable to initialize table 'nat' 

### ISSUE THREAD

**Issue by danpilch** [istio/istio#23009]
**Bug description**

When istio starts it fails with `iptables-restore v1.6.1: iptables-restore: unable to initialize table 'nat'`

`istio-init` startup log:

```
Environment:
------------
ENVOY_PORT=
INBOUND_CAPTURE_PORT=
ISTIO_INBOUND_INTERCEPTION_MODE=
ISTIO_INBOUND_TPROXY_MARK=
ISTIO_INBOUND_TPROXY_ROUTE_TABLE=
ISTIO_INBOUND_PORTS=
ISTIO_LOCAL_EXCLUDE_PORTS=
ISTIO_SERVICE_CIDR=
ISTIO_SERVICE_EXCLUDE_CIDR=

Variables:
----------
PROXY_PORT=15001
PROXY_INBOUND_CAPTURE_PORT=15006
PROXY_UID=1337
PROXY_GID=1337
INBOUND_INTERCEPTION_MODE=REDIRECT
INBOUND_TPROXY_MARK=1337
INBOUND_TPROXY_ROUTE_TABLE=133
INBOUND_PORTS_INCLUDE=*
INBOUND_PORTS_EXCLUDE=15090,15020
OUTBOUND_IP_RANGES_INCLUDE=*
OUTBOUND_IP_RANGES_EXCLUDE=
OUTBOUND_PORTS_EXCLUDE=
KUBEVIRT_INTERFACES=
ENABLE_INBOUND_IPV6=false

Writing following contents to rules file:  /tmp/iptables-rules-1587065958218530124.txt999895894
* nat
-N ISTIO_REDIRECT
-N ISTIO_IN_REDIRECT
-N ISTIO_INBOUND
-N ISTIO_OUTPUT
-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-port 15001
-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-port 15006
-A PREROUTING -p tcp -j ISTIO_INBOUND
-A ISTIO_INBOUND -p tcp --dport 22 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15090 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15020 -j RETURN
-A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT
-A OUTPUT -p tcp -j ISTIO_OUTPUT
-A ISTIO_OUTPUT -o lo -s 127.0.0.6/32 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --gid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
-A ISTIO_OUTPUT -j ISTIO_REDIRECT
COMMIT

iptables-restore --noflush /tmp/iptables-rules-1587065958218530124.txt999895894
iptables-restore v1.6.1: iptables-restore: unable to initialize table 'nat'

Error occurred at line: 1
Try `iptables-restore -h' or 'iptables-restore --help' for more information.
iptables-save
panic: exit status 2

goroutine 1 [running]:
istio.io/istio/tools/istio-iptables/pkg/dependencies.(*RealDependencies).RunOrFail(0xd819c0, 0x9739b8, 0x10, 0xc000084bc0, 0x2, 0x2)
        istio.io/istio@/tools/istio-iptables/pkg/dependencies/implementation.go:44 +0x96
istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).executeIptablesRestoreCommand(0xc0000f7d30, 0x7f88e067a601, 0x0, 0x0)
        istio.io/istio@/tools/istio-iptables/pkg/cmd/run.go:474 +0x3aa
istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).executeCommands(0xc0000f7d30)
        istio.io/istio@/tools/istio-iptables/pkg/cmd/run.go:481 +0x45
istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).run(0xc0000f7d30)
        istio.io/istio@/tools/istio-iptables/pkg/cmd/run.go:428 +0x24e2
istio.io/istio/tools/istio-iptables/pkg/cmd.glob..func1(0xd5c740, 0xc0000b0900, 0x0, 0x10)
        istio.io/istio@/tools/istio-iptables/pkg/cmd/root.go:56 +0x14e
github.com/spf13/cobra.(*Command).execute(0xd5c740, 0xc000098010, 0x10, 0x11, 0xd5c740, 0xc000098010)
        github.com/spf13/cobra@v0.0.5/command.go:830 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0xd5c740, 0x40574f, 0xc00006a058, 0x0)
        github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v0.0.5/command.go:864
istio.io/istio/tools/istio-iptables/pkg/cmd.Execute()
        istio.io/istio@/tools/istio-iptables/pkg/cmd/root.go:284 +0x2d
main.main()
        istio.io/istio@/tools/istio-iptables/main.go:22 +0x20
                                                                                                                                     83,1-8        Bot
```

**Expected behavior**
istio-init should start properly and setup network.

**Steps to reproduce the bug**
```
#install istio (description of installation provided below)
kubectl create namespace test
kubectl label namespace test istio-injection=enabled
kubectl -n test create deployment nginx --image=nginx
#deployment will fail to start on init
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
#istio
client version: 1.5.1
control plane version: 1.5.1
data plane version: 1.5.1 (3 proxies)

#kubectl
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:38:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:30:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

#cni: weave v2.6.2

```

**How was Istio installed?**
```
istioctl manifest apply \
  --set profile=demo \
  --set values.gateways.istio-ingressgateway.sds.enabled=true \
  --set values.global.k8sIngress.enabled=true \
  --set values.global.k8sIngress.enableHttps=true \
  --set values.global.k8sIngress.gatewayName=ingressgateway
```

**Environment where bug was observed (cloud vendor, OS, etc)**
```
Virtualbox VM cluster 
1x master
3x worker
installed with kubeadm v1.18
CentOS 8.1 (SELinux enabled)
```

Possible conflicts could be due to SELinux being enabled and the iptables-legacy package.

Thanks in advance.

**Comment by danpilch** [comment]
I was able to overcome the iptables nat issue by enabling CNI with:

```
istioctl manifest apply \
  --set profile=demo \
  --set components.cni.enabled=true \
```

I think the iptables issue could maybe have something to do with my k8s setup/container permissions...  I haven't tested that though.

**Comment by littleroad** [comment]
Did you add any parameters when using kubeadm init? I  fresh install a new 1.18 kubernetes by kubeadm, and followed your steps to reproduce, but did not encounter any problems.

**Comment by danpilch** [comment]
@littleroad  No I used a pretty basic kubeadm init. I think the issue lies with centos 8 and selinux. I will perform a test without CNI enabled and check

**Comment by littleroad** [comment]
Centos 8 seems to have replaced iptables-legacy with iptables (nf_tables). I think maybe the version of iptables in the proxy_v2 image is different from the version of iptables in Centos 8, resulting in different results between initcontainer and istio-cni.

**Comment by dominicqi** [comment]
do you resolved this ? i have the same problem in centos 7 and disable selinux .

> Environment:
> ------------
> ENVOY_PORT=
> INBOUND_CAPTURE_PORT=
> ISTIO_INBOUND_INTERCEPTION_MODE=
> ISTIO_INBOUND_TPROXY_MARK=
> ISTIO_INBOUND_TPROXY_ROUTE_TABLE=
> ISTIO_INBOUND_PORTS=
> ISTIO_LOCAL_EXCLUDE_PORTS=
> ISTIO_SERVICE_CIDR=
> ISTIO_SERVICE_EXCLUDE_CIDR=
> 
> Variables:
> ----------
> PROXY_PORT=15001
> PROXY_INBOUND_CAPTURE_PORT=15006
> PROXY_UID=1337
> PROXY_GID=1337
> INBOUND_INTERCEPTION_MODE=REDIRECT
> INBOUND_TPROXY_MARK=1337
> INBOUND_TPROXY_ROUTE_TABLE=133
> INBOUND_PORTS_INCLUDE=*
> INBOUND_PORTS_EXCLUDE=15090,15021,15020
> OUTBOUND_IP_RANGES_INCLUDE=*
> OUTBOUND_IP_RANGES_EXCLUDE=
> OUTBOUND_PORTS_EXCLUDE=
> KUBEVIRT_INTERFACES=
> ENABLE_INBOUND_IPV6=false
> 
> Writing following contents to rules file:  /tmp/iptables-rules-1592296074383225840.txt951403454
> * nat
> -N ISTIO_REDIRECT
> -N ISTIO_IN_REDIRECT
> -N ISTIO_INBOUND
> -N ISTIO_OUTPUT
> -A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001
> -A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006
> -A PREROUTING -p tcp -j ISTIO_INBOUND
> -A ISTIO_INBOUND -p tcp --dport 22 -j RETURN
> -A ISTIO_INBOUND -p tcp --dport 15090 -j RETURN
> -A ISTIO_INBOUND -p tcp --dport 15021 -j RETURN
> -A ISTIO_INBOUND -p tcp --dport 15020 -j RETURN
> -A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT
> -A OUTPUT -p tcp -j ISTIO_OUTPUT
> -A ISTIO_OUTPUT -o lo -s 127.0.0.6/32 -j RETURN
> -A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECT
> -A ISTIO_OUTPUT -o lo -m owner ! --uid-owner 1337 -j RETURN
> -A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN
> -A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --gid-owner 1337 -j ISTIO_IN_REDIRECT
> -A ISTIO_OUTPUT -o lo -m owner ! --gid-owner 1337 -j RETURN
> -A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN
> -A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
> -A ISTIO_OUTPUT -j ISTIO_REDIRECT
> COMMIT
> 
> iptables-restore --noflush /tmp/iptables-rules-1592296074383225840.txt951403454
> iptables-restore: line 2 failed
> iptables-save
> # Generated by iptables-save v1.6.1 on Tue Jun 16 08:27:54 2020
> *nat
> :PREROUTING ACCEPT [244803:14688180]
> :INPUT ACCEPT [244803:14688180]
> :OUTPUT ACCEPT [488281:45747377]
> :POSTROUTING ACCEPT [488292:45748037]
> :ISTIO_INBOUND - [0:0]
> :ISTIO_IN_REDIRECT - [0:0]
> :ISTIO_OUTPUT - [0:0]
> :ISTIO_REDIRECT - [0:0]
> -A PREROUTING -p tcp -j ISTIO_INBOUND
> -A OUTPUT -p tcp -j ISTIO_OUTPUT
> -A ISTIO_INBOUND -p tcp -m tcp --dport 22 -j RETURN
> -A ISTIO_INBOUND -p tcp -m tcp --dport 15090 -j RETURN
> -A ISTIO_INBOUND -p tcp -m tcp --dport 15021 -j RETURN
> -A ISTIO_INBOUND -p tcp -m tcp --dport 15020 -j RETURN
> -A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT
> -A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006
> -A ISTIO_OUTPUT -s 127.0.0.6/32 -o lo -j RETURN
> -A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECT
> -A ISTIO_OUTPUT -o lo -m owner ! --uid-owner 1337 -j RETURN
> -A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN
> -A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -m owner --gid-owner 1337 -j ISTIO_IN_REDIRECT
> -A ISTIO_OUTPUT -o lo -m owner ! --gid-owner 1337 -j RETURN
> -A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN
> -A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
> -A ISTIO_OUTPUT -j ISTIO_REDIRECT
> -A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001
> COMMIT
> # Completed on Tue Jun 16 08:27:54 2020
> panic: exit status 1
> 
> goroutine 1 [running]:
> istio.io/istio/tools/istio-iptables/pkg/dependencies.(*RealDependencies).RunOrFail(0x3bcfec8, 0x22de673, 0x10, 0xc000338640, 0x2, 0x2)
> 	istio.io/istio/tools/istio-iptables/pkg/dependencies/implementation.go:44 +0x96
> istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).executeIptablesRestoreCommand(0xc000abfd68, 0x22d4401, 0x0, 0x0)
> 	istio.io/istio/tools/istio-iptables/pkg/cmd/run.go:482 +0x387
> istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).executeCommands(0xc000abfd68)
> 	istio.io/istio/tools/istio-iptables/pkg/cmd/run.go:489 +0x45
> istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).run(0xc000abfd68)
> 	istio.io/istio/tools/istio-iptables/pkg/cmd/run.go:436 +0x25ef
> istio.io/istio/tools/istio-iptables/pkg/cmd.glob..func1(0x3b7d1c0, 0xc0001a2f00, 0x0, 0x10)
> 	istio.io/istio/tools/istio-iptables/pkg/cmd/root.go:64 +0x148
> github.com/spf13/cobra.(*Command).execute(0x3b7d1c0, 0xc0001a2e00, 0x10, 0x10, 0x3b7d1c0, 0xc0001a2e00)
> 	github.com/spf13/cobra@v1.0.0/command.go:846 +0x29d
> github.com/spf13/cobra.(*Command).ExecuteC(0x3b7d460, 0x0, 0x0, 0x0)
> 	github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
> github.com/spf13/cobra.(*Command).Execute(...)
> 	github.com/spf13/cobra@v1.0.0/command.go:887
> main.main()
> 	istio.io/istio/pilot/cmd/pilot-agent/main.go:504 +0x2d

**Comment by danpilch** [comment]
@dominicqi no I didn't fix it with iptables. I resolved it by replacing iptables with [IPVS](https://en.wikipedia.org/wiki/IP_Virtual_Server)

You can see how I did this [here](https://github.com/danpilch/easy-kubeadm/blob/master/roles/kubernetes/tasks/ipvs_config.yaml#L2) and enabling cni:

```
istioctl manifest apply \
    --set components.cni.enabled=true 
```

**Comment by dominicqi** [comment]
> @dominicqi no I didn't fix it with iptables. I resolved it by replacing iptables with [IPVS](https://en.wikipedia.org/wiki/IP_Virtual_Server)
> 
> You can see how I did this [here](https://github.com/danpilch/easy-kubeadm/blob/master/roles/kubernetes/tasks/ipvs_config.yaml#L2) and enabling cni:
> 
> ```
> istioctl manifest apply \
>     --set components.cni.enabled=true 
> ```

Thanks for you advise ,buti m use  IPVS already.  not enable cni . I use centos-7. only some node have this problem.

**Comment by lambdai** [comment]
We saw issues when user manually delete/clean up containers. 
Istio-init cannot recover from this state.

**Comment by zackzhangkai** [comment]
modprobe br_netfilter ; modprobe nf_nat ; modprobe xt_REDIRECT ; modprobe xt_owner; modprobe iptable_nat; modprobe iptable_mangle; modprobe iptable_filter。

**Comment by themowski** [comment]
We encountered this issue when deploying Kubeflow v1.3.1 and v1.4.1 through its manifests deployment method, which injects Istio sidecars. Our target environment is a downstream Kubernetes v1.21.9 cluster that is deployed by Rancher v2.6.3-patch1. Each node in our cluster has AlmaLinux 8.5 (one of the CentOS 8 derivatives) as its OS. SELinux and firewalld are both disabled on our nodes.

The kernel module loading approach suggested by @zackzhangkai above (and quoted here) was what fixed this issue for us:

> istio use iptables to intercept traffic , by adding nat rules . Linux should enable netfix linux kernel modules. In all hosts do the command to enable.
> 
> ```shell
>  modprobe br_netfilter ; modprobe nf_nat ; modprobe xt_REDIRECT ; modprobe xt_owner; modprobe iptable_nat; modprobe iptable_mangle; modprobe iptable_filter
> ```

We ran this command to load these modules on all of our nodes in the downstream Kubernetes cluster that have the `worker` role. In order to get the module loads to persist across reboots, we created a file -- `/etc/modules-load.d/99-istio-modules.conf` -- on each `worker` node with the following contents:

```text
# These modules need to be loaded on boot so that Istio (as required by
# Kubeflow) runs properly.
#
# See also: https://github.com/istio/istio/issues/23009

br_netfilter
nf_nat
xt_REDIRECT
xt_owner
iptable_nat
iptable_mangle
iptable_filter
```

This workaround is great, and we've documented it internally, but it would be really nice if this issue could be fixed at the Istio level, especially since we encountered it while trying to install a separate piece of software that happens to depend upon / use Istio.

**Comment by MentosL** [comment]
> I occured this problem on arm system

Did you solve the problem of macos under the arm architecture? I also have this problem

**Comment by 23hp** [comment]
> > I occured this problem on arm system
> 
> Did you solve the problem of macos under the arm architecture? I also have this problem



> I occured this problem on arm system

I replaced the customized image from the cloud provider with the official one, and then the problem was gone.

**Comment by tkellen** [comment]
On OCI/OKE, tested only on `Oracle-Linux-8.9-2024.01.26-0-OKE-1.28.2-679`, the only addition needed is:
```
modprobe ip_tables
```

Of note, istio works out of the box using the OKE's istio "addon" because the addon runs custom OKE containers out of their own public registries. Presumably they've baked some workaround into those containers. I've requested that the OCI team simply include this in their base images so vanilla installs work out of the box.

**Comment by stanyzra** [comment]
On same topic about OCI/OKE on `Oracle-Linux-8.9-aarch64-2024.04.19-0-OKE-1.29.1-693`, the workaround I'm using is to write a [custom node initialization script](https://docs.oracle.com/en-us/iaas/Content/ContEng/Tasks/contengusingcustomcloudinitscripts.htm) in the node pool configuration to provide the required command. My file is as follows:

```bash
#!/bin/bash
curl --fail -H "Authorization: Bearer Oracle" -L0 http://169.254.169.254/opc/v2/instance/metadata/oke_init_script | base64 --decode >/var/run/oke-init.sh
bash /var/run/oke-init.sh
modprobe ip_tables
echo "ip_tables" > 99-istio-modules.conf
sudo mv 99-istio-modules.conf /etc/modules-load.d/
```

It seems to work for both new nodes and restarted nodes because of the `99-istio-modules.conf` file (it will only work after the custom script is injected in the node pool configuration, of course).

**Comment by ashishmahamuni21** [comment]
i also had same issue with my istio installation with **helm** chart where my 
**ns is : istio-injection=enabled**
and i have **kubernetes version: 1.29**
and **istio: 1.22.2**

and resolved this by edit the helm chart for istiod and set the value of **cni.enabled: false to TRUE**
my values.yaml is

`defaults:
  pilot:

    cni:
      enabled: true
      provider: default`
