### ISSUE TITLE
istioctl segmentation fault if kubectl context doesn't exist

### ISSUE THREAD

**Issue by tillig** [istio/istio#23000]
**Bug description**

If you provide a context to `istioctl` using the `--context` parameter and the context doesn't exist, you not only get an error message indicating the context doesn't exist, but also a segmentation fault.

```text
Checking the cluster to make sure it is ready for Istio installation...

#1. Kubernetes-api
-----------------------
Failed to initialize the Kubernetes client: context "ctx" does not exist.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x290127c]

goroutine 1 [running]:
istio.io/istio/istioctl/pkg/install.installPreCheck(0x35235e6, 0xc, 0x39a4720, 0xc000646370, 0x391cc60, 0xc00000e020, 0x9, 0xc0006b2f58)
	istio.io/istio@/istioctl/pkg/install/pre-check.go:66 +0x34c
istio.io/istio/istioctl/pkg/install.verifyInstall(0xc0005b9901, 0x35235e6, 0xc, 0x39a4720, 0xc000646370, 0x52e32c0, 0x0, 0x0, 0x0, 0x0, ...)
	istio.io/istio@/istioctl/pkg/install/verify.go:49 +0x178
istio.io/istio/istioctl/pkg/install.NewVerifyCommand.func1(0xc0005b9900, 0xc000308860, 0x0, 0x2, 0x0, 0x0)
	istio.io/istio@/istioctl/pkg/install/verify.go:203 +0x20e
github.com/spf13/cobra.(*Command).execute(0xc0005b9900, 0xc0003087e0, 0x2, 0x2, 0xc0005b9900, 0xc0003087e0)
	github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002d2780, 0x3, 0x3, 0xc0002d2780)
	github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
	istio.io/istio@/istioctl/cmd/istioctl/main.go:29 +0x76
```

**Expected behavior**

I expect the error message to be there but not the segmentation fault.

**Steps to reproduce the bug**

Run this command:

`istioctl verify-install --context thisisnotacontext`

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

`istioctl` v1.5.1

**How was Istio installed?**

It's not installed yet. Discovered this during `verify-install` as I was getting set up and fat-fingered the name of the context.

**Environment where bug was observed (cloud vendor, OS, etc)**

MacOS

**Comment by zillani** [comment]
issued PR 
https://github.com/istio/istio/pull/23927
