### ISSUE TITLE
VM Testing Epic

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#23006]
This discusses the current state of VM testing and changes we can make to improve our coverage.

Currently our integration tests have 2 modes: Kubernetes, which deploys everything in a k8s cluster. in CI this runs in kind. The vast majority of our tests run exclusively in this mode. Some of this is because it is k8s specific (such as testing `Ingress`, although I suppose that could even work without k8s in theory), but many are due to deficiencies in the native mode (see below).

The native tests try to run the same set of tests, but without kubernetes. This involves running the control plane directly through the go code (in the same process as the test), and spin up the data plane as docker containers. The docker container is a loose approximation of what VMs are doing, as its built upon the sidecar.deb. There are a few problems with this:
* Majority of tests are not running these
* Not everything is supported. Previously this was citadel, now it may just be the addons (prometheus, etc)
* Coverage is extremely minimal, so much so that all tests passed despite iptables rules not working: https://github.com/istio/istio/issues/22402
* The environment doesn't match any real deployment - its doing weird things with ServiceEntries, still using MCP, etc
* Its either native or k8s - there is no hybrid mesh expansion setup possible

To add VM testing, we have a few options. We probably want to improve the native environment so its more realistic as a first step. If we want to be able to test things like jwt provisioning, we may also need to have a hybrid mode.

The other option is to do real VM testing and set up real GCE instances. I think we need to do this, but probably not something we want in presubmit due to flakyness, reproduciblity, and cost. However, its something that we could add as part of the release qual or as part of a periodic job possibly.

The above is just a dump of some info in my mind right now. We will probably want to split this off into tangible work items and discuss the direction we want to move in

**Comment by howardjohn** [comment]
cc @smawson @liminw @irisdingbj just getting this discussion started

**Comment by smawson** [comment]
I wonder if we can get some of the VM tests working using kubernetes? We couldn't test some of the authentication flow but we could at least test the workloadentry part I think. Basically we have pods that don't have labels and are not part of services, then we register their endpoints as WorkloadEntry with appropriate labels to get them selected into a service entry.

Another option would be to use nested virtualization and actually run a VM in a pod (kubevirt style). Depending on how much control we have over the VM's environment we could test most of the VM support that way.

**Comment by howardjohn** [comment]
That is a good idea, I think its pretty likely we can do VMs as pods. Especially with some of the options in Kubernetes like not mounting service account token, etc so that we aren't "cheating".

**Comment by incfly** [comment]
please consider testing the env/setup discrepancies as a requirement.

Not sure if we still ask customer to modify /etc/hosts for DNS, and pod file system is not modifiable. how do you install deb package?

**Comment by howardjohn** [comment]
> pod file system is not modifiable

Why not? We already have a docker image that builds `FROM ubunutu` and installs the deb package. Then we can run that in the pod

**Comment by incfly** [comment]
Putting into Docker image sounds like a good idea. In fact, couldn't we
even make the whole VM pre-setup thing as part of Docker build? /etc/host
editing, key/cert copying, etc.

**Comment by howardjohn** [comment]
Yep, thats exactly what we are doing to day: https://github.com/istio/istio/blob/2f448c3784d6c23e75a5d5f15826138e29653d03/pkg/test/echo/docker/Dockerfile.app_sidecar#L24. The problem with this approach currently is we don't have any tests connecting that docker image to a k8s cluster - we just have that docker image to a "native" pilot. It also probably doesn't follow the same practices as we are documenting, but its pretty close

**Comment by howardjohn** [comment]
VM testing is implemented

**Comment by howardjohn** [comment]
Implementation is in #24166 primarily
