### ISSUE TITLE
File based SDS does not watch files for cert rotation

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#23001]
Currently in the code we look for existing cert files: https://github.com/istio/istio/blob/502423c80c0a14b65de3172c359246af7c45aee6/security/pkg/nodeagent/cache/secretcache.go#L267

However, if these files change, we won't update. We do check for expiration, but the certs may be changed at any time before expiration, which is not handled. We need to add some sort of file watched here to trigger a push when they change (just like k8s secrets handles this)

@ramaraochavali

**Comment by myidpt** [comment]
Lei, can you fix it:
https://github.com/istio/istio/blob/502423c80c0a14b65de3172c359246af7c45aee6/security/pkg/nodeagent/cache/secretcache.go#L259

**Comment by myidpt** [comment]
Are there customers using it? This requires medium amount of work, if not many customers are using it, we will keep this one as P2.

**Comment by ramaraochavali** [comment]
We (Salesforce use it) and also once we merge https://github.com/istio/istio/pull/22019, we expect the certs specified in DR's are watched. We plan to implement this once https://github.com/istio/istio/pull/22019 is merged

**Comment by lei-tang** [comment]
> We (Salesforce) use it. See this [#21833 (comment)](https://github.com/istio/istio/issues/21833#issuecomment-615169432) and also once we merge #22019, we expect the certs specified in DR's are watched. We plan to implement this once #22019 is merged

@ramaraochavali Thanks! As you plan to implement this once #22019 is merged, I have changed the issue assignee to you.

**Comment by ramaraochavali** [comment]
Sure. Thanks. Will do

**Comment by myidpt** [comment]
Bump it to P1

**Comment by howardjohn** [comment]
fixed in https://github.com/istio/istio/pull/23417
