### ISSUE TITLE
Retain proxy coredump when container restarts: Use emptyDir volume

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#23011]
Since Istio 1.4(?) if the proxy coredumps, the container is restarted.
This is an issue because the coredump is destroyed with the container.

 - [ ] Use EmptyDir volume mounted at `/var/lib/istio/cores`
 - [ ] Update config-dump init container to update core pattern = `/var/lib/istio/cores/core.proxy`
 - [ ] For backwards compatibility, maintain a link from `/var/lib/istio/core.proxy ->   /var/lib/istio/cores/core.proxy`

**Comment by richardwxn** [comment]
@mandarjog this should work, but trying to understand the rationale, 1. why should we need to do this if we can add preStop lifecycle hook 2. why we need to maintain a link, if we change the injection configmap, then the newly created proxy would have this new pattern

**Comment by incfly** [comment]
This seems miss the changes for ingress-gateway? I used a 1.6.4 gateway, and looking at the config, seems like there's no changes you did in this PR (empty dir mount into `/var/lib/istio/istio-data`) 

sidecar does have that.

Should we add it there as well? Or gateway is already covered with some tricks that I don't know?

**Comment by richardwxn** [comment]
@incfly yep I only added it for sidecar in the injection template, I think we can add that to ingress as well, let me do that then
