### ISSUE TITLE
istio/tools: integration with Nighthawk leftover

### ISSUE THREAD

**Issue by carolynhu** [istio/istio#23017]
This ticket is to track the Todo tasks after our integrating with Nighthawk into Istio performance pipeline:

- [ ] Figure out which nighthawk docker image version we should use for gathering consistent test results
- [ ] Fix error handling issue in run_nighthawk()
- [ ] Make traffic sending via grpc success, currently, it is broken, and we got the following error log:

```
[19:45:46.839668][1][E] [source/client/remote_process_impl.cc:51] Failure while communicating with the remote service
```
the above: [full failure log](https://github.com/carolynhu/service-mesh-cmp/blob/master/nighthawk_debugging/remote_comm_failure/terminal_log_remote_comm_failure.txt)

- [ ] enable `--jitter` flag back?
- [ ] debugging single sidecar failures
- [ ] `--burst-size` flag reconsideration (https://github.com/istio/tools/pull/933)
- [ ] make perf presubmit job `benchmark_check_tools` to be able to test `nighthawk` as well

**Comment by carolynhu** [comment]
cc @oschaaf  @mandarjog @howardjohn

**Comment by oschaaf** [comment]
Thanks @carolynhu for filing this. I've initiated work on shipping a release based on the latest version of NH. We need a few small tweaks to materialize that, but it is in motion and will be sorted soon.

As for the error handling, I had a question about the current state of master / planned direction, I'll be in touch on Slack about that.
