### ISSUE TITLE
QUIC for Envoy proxy

### ISSUE THREAD

**Issue by ccccbjcn** [istio/istio#23018]
**Describe the feature request**
Per envoyproxy/envoy code, I notice it has supported QUIC feature, whether istio/proxy envoy feature aligns with envoyproxy/envoy on QUIC?

**Describe alternatives you've considered**

**Additional context**

**Comment by howardjohn** [comment]
See also https://github.com/istio/istio/issues/1430

**Comment by ldemailly** [comment]
Can configuring terminating QUIC be an option before full UDP support? ie doing QUIC or h3 to envoy ingresses -> h2?

**Comment by howardjohn** [comment]
@ldemailly yes, I think that is a reasonable progression so we don't need to deal with redirection concerns
