### ISSUE TITLE
configure mutating webhooks in remote cluster to use main cluster's sidecar injector

### ISSUE THREAD

**Issue by linsun** [istio/istio#23028]
As part of #22934.   This will likely require changes to configure caBundle properly as currently istiod patches the MutatingWebhookConfiguration object to add caBundle  after it starts.

**Additional context**

**Comment by linsun** [comment]
Had a discussion on Friday with @costinm @howardjohn -- we agreed that this scenario only makes sense when certProvider is Istiod at the moment as we don't have proper way to get the root cert distributed to remote cluster currently.  

Further, the main cluster has remote cluster's *read* access token but not *write* thus It makes sense to have the mesh admin to configure the mutating web hook configuration properly when setting up the remote cluster.  I'll check what istioctl can do to simply the setup, assuming the mesh admin can provide a proper caBundle to use.

**Comment by linsun** [comment]
@costinm @howardjohn I ran into ingress gw won't start on remote cluster without istiod in remote cluster due to the following cm not existed in the istio-system namespace:

```
      - configMap:
          defaultMode: 420
          name: istio-ca-root-cert
        name: istiod-ca-cert
```

@howardjohn kindly pointed me some code in pilot to help populate the istio-ca-root-cert cm in each namespaces.  Does this mean we will still have to run a mini-istiod in the remote cluster?  Thoughts?

**Comment by howardjohn** [comment]
You need something to create that configmap in every namespace of the remote cluster. Whether that is the local cluster istiod, remote cluster istiod, or something else is an open question

**Comment by linsun** [comment]
Agreed, either we provide a lightweight istiod for just that purpose or have another service to do that work.

**Comment by linsun** [comment]
opened up a seperate issue for this. This current WI is blocked till https://github.com/istio/istio/issues/22874#issuecomment-617387697 is sorted out.

**Comment by linsun** [comment]
We had a few rounds of discussion on this today, unfortunately, this is not straightforward due to the fact that we introduced revision support in 1.6 and the way we supported mutating Webhook configuration with revision in 1.6 is that each revision has its own mutating Webhook configurations (they are differentiated based on the name including the revision id).  This is not the ideal model because mutating Webhooks configuration is supposed to be cluster wide but where we are today kinda prevents us from moving mutating webhook configurations into the base component properly.

It could be too risky to move mutating Webhooks configurations into the base component for 1.6 as it would require *not small* code changes in Istiod to be handle 1 mutating Webhooks configuration with multiple injection templates (as each revision has its own injection template).  This will require code to discover which revision should use which injection template.

cc @howardjohn @costinm @sdake @nrjpoddar please correct me if I missed anything else.

**Comment by linsun** [comment]
Very close to get a manual pass working for this but did find I need to add custom hostname so that the Webhooks server doesn't complain about certs from unknown host.

**Comment by linsun** [comment]
I think this is working nicely, with https://github.com/istio/istio/pull/23942 in.
