### ISSUE TITLE
[1.5] Istio CNI -- missing default prometheus excludeInboundPort on CNI injected proxies

### ISSUE THREAD

**Issue by stewartbutler** [istio/istio#23038]
**Bug description**
In current Istio 1.5 branch (not a release), prometheus scraping fails in CNI injected pods because the default excludeInboundPort configuration does not include port 15090. Non-CNI injected pods have this port added automatically by the injector template; however, that port is not passed in a way the CNI can understand.

Without a fix, this will probably break monitoring in existing 1.5 CNI deployments that upgrade to 1.5.2 unless they set the `traffic.sidecar.istio.io/excludeInboundPorts` parameter to exclude `15090` manually.

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by stewartbutler** [comment]
Also linked: https://github.com/istio/cni/pull/299 and https://github.com/istio/cni/pull/300

**Comment by howardjohn** [comment]
@stewartbutler is this fixed?

**Comment by stewartbutler** [comment]
Yes, though I need to go back and make the fix more general.

I'm going to close this issue though.
