### ISSUE TITLE
The "istio-certs" is still mount when enabled the global sds in ingressgateway

### ISSUE THREAD

**Issue by wsdlll** [istio/istio#23045]
**Bug description**

First, I make the global.sds.enabled = true.
The istio-certs is still mount in ingressgateway while not in sidecar.
So the ingressgateway restart-epoch when the istio.ingressgateway-service-account refresh every 45 Days.
Is there any reason for this.
Or just because this is missing 【else】.

[In Ingressgateway]
The deployment of ingressgateway is like:
          {{- if $.Values.global.sds.enabled }}
          - name: sdsudspath
            mountPath: /var/run/sds
            readOnly: true
          - name: istio-token
            mountPath: /var/run/secrets/tokens
          {{- end }}
          ... ...
          - name: istio-certs
            mountPath: /etc/certs
            readOnly: true
[In Sidecar]
It is like:
          {{- if .Values.global.sds.enabled }}
           - mountPath: /var/run/sds
            name: sds-uds-path
            readOnly: true
          - mountPath: /var/run/secrets/tokens
            name: istio-token
          ... ...
          {{- else }}
          - mountPath: /etc/certs/
            name: istio-certs
            readOnly: true
          {{- end }}

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istio 1.3.0 (same in 1.4 and 1.5)

**How was Istio installed?**
helm

**Comment by howardjohn** [comment]
> Istio 1.3.0

This version is no longer supported, so we would not patch this. You mentioned its the same in 1.5, but I don't see this. https://github.com/istio/istio/blob/release-1.5/manifests/gateways/istio-ingress/templates/deployment.yaml#L316 shows it is conditionally enabled (off by default)

**Comment by wsdlll** [comment]
Oh, thanks, it is conditionally enabled in 1.5.

If i enable the ".Values.global.mountMtlsCerts" for the in-cluster mTLS communications. 
The ingressgateway will restart-epoch when the istio.ingressgateway-service-account refresh?

**Comment by howardjohn** [comment]
Yes, only if that is enabled. This is meant only for if you want to use mounted certs. I recommend not enabling this if you use SDS (which is the default)

**Comment by wsdlll** [comment]
Thank you for your help.
I would close the issue. :)
