### ISSUE TITLE
//mixer/pkg/config/crd:go_default_test  and //pilot/platform/kube/admit:go_default_test  fails on x86

### ISSUE THREAD

**Issue by kadamvandita** [istio/istio#2305]
//mixer/pkg/config/crd:go_default_test  and //pilot/platform/kube/admit:go_default_test  fails on x86. The above mentioned TC fail on x86.

Any update on this?

**Comment by jmuk** [comment]
Can you copy&paste the test results?  Also which kubernetes environment are you using?

Some test cases (including those two) actually connect to a kubernetes cluster, and I see sometimes error happens during `error executing access token` when using GKE. In that case, running `kubectl get pods` will refresh the access token and retry tests.

**Comment by kadamvandita** [comment]
HI @jmuk ,

I tried the baove thing. STill the TC fails

the error details are seen below

exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
2017/12/22 17:33:44 http: TLS handshake error from [::1]:44774: remote error: tls: bad certificate
2017/12/22 17:33:44 http: TLS handshake error from [::1]:44776: remote error: tls: bad certificate
2017/12/22 17:33:44 http: TLS handshake error from [::1]:44778: remote error: tls: bad certificate
2017/12/22 17:33:44 http: TLS handshake error from [::1]:44780: remote error: tls: bad certificate
--- FAIL: TestServe (0.03s)
        admit_test.go:370: valid: Post(application/json, {"spec":{"kind":{"group":"","version":"","kind":""},"object":{"kind":"mock","metadata":{"name":"mock-config0","namespace":"watched"},"spec":{"foo":1}},"oldObject":null,"operation":"CREATE","resource":{"group":"","version":"","resource":""},"userInfo":{}},"status":{"allowed":false}}) failed Post https://[::1]:45928: x509: certificate is valid for 127.0.0.1, not ::1
        admit_test.go:370: invalid: Post(application/json, {"spec":{"kind":{"group":"","version":"","kind":""},"object":{"kind":"mock","metadata":{"name":"mock-config0","namespace":"watched"},"spec":{"foo":1}},"oldObject":null,"operation":"CREATE","resource":{"group":"","version":"","resource":""},"userInfo":{}},"status":{"allowed":false}}) failed Post https://[::1]:45928: x509: certificate is valid for 127.0.0.1, not ::1
        admit_test.go:370: wrong content-type: Post(application/yaml, {"spec":{"kind":{"group":"","version":"","kind":""},"object":{"kind":"mock","metadata":{"name":"mock-config0","namespace":"watched"},"spec":{"foo":1}},"oldObject":null,"operation":"CREATE","resource":{"group":"","version":"","resource":""},"userInfo":{}},"status":{"allowed":false}}) failed Post https://[::1]:45928: x509: certificate is valid for 127.0.0.1, not ::1
        admit_test.go:370: bad content: Post(application/json, ^@^A^B^C^D^E) failed Post https://[::1]:45928: x509: certificate is valid for 127.0.0.1, not ::1
FAIL

The kbernetes setup being used is of version 1.8.3

Any updates on this?

**Comment by jmuk** [comment]
Aah, I see. So the test client tries to connect through IPv6 address `[::1]`, which isn't covered by our test certificates.

This is a bug unrelated to kubernetes, we haven't been aware of it. I'll work on the fix. cc: @ayj
