### ISSUE TITLE
On kubernets, Ingress behaves differently when deployed via istioctl (1.5.1)

### ISSUE THREAD

**Issue by illidan80** [istio/istio#23063]
I have a system which running for about an year, composed of multiple services / virtual services / gateways and ingressgateway components.

Until now I was using a "helm template" deployment method (default profile) - everything was worked as expected.

When released 1.5.1, first I deployed Istio as always using "helm template" method. Everything worked.

Then I noticed a statement that "helm" method deprecated and "istioctl" method should be used instead. I removed everything and redeployed Istio from scratch using "istioctl" (again, used "default" profile). I used exactly the same all my yamls which I used previously. This time, although all pods are up & ready, I was not able to perform any https request from the outside (via ingress gateway). When I was trying to access any of exposed URLs via Chrome, I getting "unexpectedly closed the connection" error.

Performing same call via curl gets me:

`curl: (35) schannel: failed to receive handshake, SSL/TLS connection failed`

I removed everything again and redeployed again using "helm template" method (same istio version, same system yamls) - everything works back again.

So, despite same Istio version (1.5.1) and despite that all deployment yamls are exactly the same - there is a difference in deployed Istio using "helm" (which deploys old style multipod deployment) and Istio deployed using "istioctl" method (which deploys new style "istiod" pod).

I checked everything I could, everything looks well - but yet there is an issue with ingress. Inside mesh, communication between pods works as expected (I have a sidecar injected in each of my pods). Accessing system from the outside via NodePort works as well. 

Looks like the issue isolated to Ingress only.

Any idea? What could be the difference? Where I should look for troubleshooting this?

P.S. Maybe somehow helpful: this is my development environment, and I using a self signed certificate which expires at 19/04/2029 (exactly 9 years from today). Is it coincidence or maybe self signed certificates treated differently in new istiod deployment? Maybe there is a hard 1 year limit for certificate duration which ignores an actual valid period? I really lost here..  

Kubernetes 1.18 on local Microk8s, Ubuntu 18.04, Istio 1.5.1

**Comment by illidan80** [comment]
I figured it out.
When ingress deployed via helm, its TLS port is 31390, however when it deployed via istiod its port is 31360...

**Comment by illidan80** [comment]
I think you should update documentation, since it still says that the default is 31390

https://istio.io/docs/reference/config/installation-options/#gateways-options

**Comment by howardjohn** [comment]
That options list refers to the helm install method, not istioctl

**Comment by illidan80** [comment]
@howardjohn 

According to [documentation](https://istio.io/docs/setup/install/istioctl/):

> For backwards compatibility, the previous Helm installation options, with the exception of Kubernetes resource settings, are also fully supported. To set them on the command line, prepend the option name with “values.”.


Therefore, it was logical to assume (at least for me), that the default values are the same as well.

Where I can find documentation about options / default values for istioctl-based deployment?

**Comment by howardjohn** [comment]
Thats true, that page caused a lot of confusion. In 1.6 we are planning to remove it to help make things a bit simpler. The istioctl docs are at https://istio.io/docs/reference/config/istio.operator.v1alpha1/#IstioOperatorSpec. We are working a bit to make the format of this a bit easier to consume as well (it is auto generated)

**Comment by howardjohn** [comment]
Thats true, that page caused a lot of confusion. In 1.6 we are planning to remove it to help make things a bit simpler. The istioctl docs are at https://istio.io/docs/reference/config/istio.operator.v1alpha1/#IstioOperatorSpec. We are working a bit to make the format of this a bit easier to consume as well (it is auto generated)

**Comment by howardjohn** [comment]
Closing as this is a documentation issue and the confusing doc has since been removed in 1.6. Please try this out, thanks!
