### ISSUE TITLE
1.4.7 proxy crashed by 1.5.x config from Pilot during upgrade due to RBAC

### ISSUE THREAD

**Issue by chadlwilson** [istio/istio#23064]
**Bug description**

During an upgrade from Istio `1.4.7` to `1.5.1`, proxies still running `1.4.7` and with `AuthorizationPolicy` applied to them appeared to crash soon after control plane upgrade. The below `AuthorizationPolicy` appears to work fine on `1.4.7` (we have many similar policies running on production workloads).

```
[Envoy (Epoch 0)] [2020-04-19 16:18:18.379][14][warning][config] [external/envoy/source/common/protobuf/message_validator_impl.cc:28] Unknown field: type envoy.config.rbac.v2.Permission with unknown field set {10}
[Envoy (Epoch 0)] [2020-04-19 16:18:18.379][14][critical][assert] [external/envoy/source/extensions/filters/common/rbac/matchers.cc:32] panic: not reached
[Envoy (Epoch 0)] [2020-04-19 16:18:18.379][14][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:83] Caught Aborted, suspect faulting address 0x5390000000e
[Envoy (Epoch 0)] [2020-04-19 16:18:18.379][14][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:70] Backtrace (use tools/stack_decode.py to get line numbers):
[Envoy (Epoch 0)] [2020-04-19 16:18:18.379][14][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:71] Envoy version: aa9f6a9eadad401d8630be220af2ee8a033a2fdb/1.12.0/Clean/RELEASE/BoringSSL
[Envoy (Epoch 0)] [2020-04-19 16:18:18.380][14][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #0: __restore_rt [0x7f3a9cd41890]
[Envoy (Epoch 0)] [2020-04-19 16:18:18.386][14][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #1: Envoy::Extensions::Filters::Common::RBAC::OrMatcher::OrMatcher() [0x55bcfdf2fc9e]
```
Full crashlog on an auto-restarting proxy is [here](https://gist.github.com/chadlwilson/6520f0120a012440e2927eac125163ed)

One possible notable fact is that the `istio-ingressgateway` is not actually installed in this cluster; so the first rule refers to a `ServiceAccount` that doesn't exist.

Relevant RBAC
```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  creationTimestamp: "2020-01-23T02:14:24Z"
  generation: 2
  name: my-application
  namespace: services
  resourceVersion: "3155823"
  selfLink: /apis/security.istio.io/v1beta1/namespaces/services/authorizationpolicies/my-application
  uid: 133abf0f-3d86-11ea-914f-022e6c8f37c8
spec:
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account
    to:
    - operation:
        methods:
        - GET
        - OPTIONS
        paths:
        - '*'
  - to:
    - operation:
        ports:
        - "15090"
  selector:
    matchLabels:
      app.kubernetes.io/name: my-application
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: deny-all
  namespace: services
spec: {}
```

**Expected behavior**

Proxies running on `1.4.7` can connect to `1.5.1` pilot and keep working until they are rolled; certainly not crashing.....

Would also appreciate a workaround if there is something in our `AuthorizationPolicy` that is not well understood between the two versions that we can simplify to move forward with this upgrade.

**Steps to reproduce the bug**

Haven't tried for a minimal reprod at the moment; but this upgrade was done in a smaller/simpler representative environment.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

istioctl
```
citadel version: 1.5.1
galley version: 1.5.1
pilot version: 1.5.1
policy version: 1.5.1
sidecar-injector version: 1.5.1
sidecar-injector version: 1.5.1
telemetry version: 1.5.1
data plane version: 1.4.7 (1 proxies), 1.5.1 (1 proxies)
```

kubectl
```
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-502bfb", GitCommit:"502bfb383169b124d87848f89e17a04b9fc1f6f0", GitTreeState:"clean", BuildDate:"2020-02-07T01:31:02Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

helm
`Client: &version.Version{SemVer:"v2.16.6", GitCommit:"dd2e5695da88625b190e6b22e9542550ab503a47", GitTreeState:"clean"}`

**How was Istio installed?**

Via Helm; upgraded by `helm upgrade` (with some scripting to workaround the `ValidatingWebhookConfiguration` changes.

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS EKS

**Comment by rshriram** [comment]
@yangminzhu ^^^

**Comment by yangminzhu** [comment]
According to this line `[Envoy (Epoch 0)] [2020-04-19 16:18:18.379][14][warning][config] [external/envoy/source/common/protobuf/message_validator_impl.cc:28] Unknown field: type envoy.config.rbac.v2.Permission with unknown field set {10}`, I think it's actually due to a new field ([url_path](https://github.com/envoyproxy/envoy/blob/5b7d3afc7b0f190d39e6a065662e646460183511/api/envoy/config/rbac/v3/rbac.proto#L143)) we introduced in Envoy in 1.5 that doesn't exist in 1.4.

The `url_path` is an improvement to handle HTTP paths that strip the query and fragment string before matching, this make sure we don't mismatch on invalid paths with query and fragments. 

@chadlwilson Do you still see issues if you delete the current pods so that they start with the 1.5 Envoy sidecars?

**Comment by yangminzhu** [comment]
This should only happen if you are using `paths` in AuthorizationPolicy. To workaround this, you could temporarily change to use the `request.headers[:path]` and change it back after all your Envoys are updated to 1.5:
```yaml
when:
- key: request.headers[:path]
  values: ["/path1", "/path2"]
```

I also noted that your policy has `paths: ["*"]` which is not really enforcing anything, you can just remove this part.

**Comment by yangminzhu** [comment]
I sent out a PR to only use the `url_path` field in Envoy versions >= 1.5, it should be in 1.6 but it probably not worth another 1.5.2 just for this issue, please let me know if you have other thoughts, thanks.

**Comment by chadlwilson** [comment]
@yangminzhu 

> According to this line `[Envoy (Epoch 0)] [2020-04-19 16:18:18.379][14][warning][config] [external/envoy/source/common/protobuf/message_validator_impl.cc:28] Unknown field: type envoy.config.rbac.v2.Permission with unknown field set {10}`, I think it's actually due to a new field ([url_path](https://github.com/envoyproxy/envoy/blob/5b7d3afc7b0f190d39e6a065662e646460183511/api/envoy/config/rbac/v3/rbac.proto#L143)) we introduced in Envoy in 1.5 that doesn't exist in 1.4.

Thanks that explains it.

> The `url_path` is an improvement to handle HTTP paths that strip the query and fragment string before matching, this make sure we don't mismatch on invalid paths with query and fragments.

Ahh, that's a great improvement. The inclusion of the query fragment was a cause of much confusion (and potentially security problems if doing suffix matching or `/root/*/leaf` matching on the path) so this is a good step. 

> @chadlwilson Do you still see issues if you delete the current pods so that they start with the 1.5 Envoy sidecars?

The 1.5 sidecars did appear to start, however I have not done any active testing to make sure they are all working correctly; traffic getting through/blocked as expected. This was a sanity test upgrade and got blocked on this so didn't go deeper.

> This should only happen if you are using `paths` in AuthorizationPolicy. To workaround this, you could temporarily change to use the `request.headers[:path]` and change it back after all your Envoys are updated to 1.5:
> 
> ```yaml
> when:
> - key: request.headers[:path]
>   values: ["/path1", "/path2"]
> ```

Thanks for the suggested workaround; will give this a go. Does this approach work with wildcard matches as well as exact values?

> I also noted that your policy has `paths: ["*"]` which is not really enforcing anything, you can just remove this part.

Noted, we have generally chosen to keep them there so it's explicit to devs that they are allowing traffic on all paths, to trigger a bit of "are you sure that's what you want to do?".

> I sent out a PR to only use the `url_path` field in Envoy versions >= 1.5, it should be in 1.6 but it probably not worth another 1.5.2 just for this issue, please let me know if you have other thoughts, thanks.

I was inferring there was going to be a `1.5.2` for other reasons based on outstanding issues tagged to the `1.5` milestone, so if so I think it would be good for the community to backport this fix as part of that next release.

To my knowledge, and based on current docs, technically skip-upgrades are still not supported by Istio without dropping traffic, so I am a bit nervous about planning for `1.4` -> `1.6`. There are also quite a few changes in `1.5` that I would prefer to be able to incrementally move towards (and clean-up after, e.g removal of nodeagent, deprecation of `MeshPolicy`, auto-mtls, `controlPlaneSecurity`, mixer CRD removals, preparing for telemetry V2 etc). Having said this, I have noted the discussion in #22874 that seems to be suggesting a `1.4` -> `1.6` kind of upgrade path.

**Comment by yangminzhu** [comment]
> Thanks for the suggested workaround; will give this a go. Does this approach work with wildcard matches as well as exact values?

Yes, it works for both wildcard matches and exact values, but please note that `request.headers[:path]` uses the raw path in Envoy that doesn't strip the query string. So please remember to change back to use the normal `paths` field once your Envoy sidecar is updated to 1.5, sorry for the inconvenience.

> I was inferring there was going to be a 1.5.2 for other reasons based on outstanding issues tagged to the 1.5 milestone, so if so I think it would be good for the community to backport this fix as part of that next release.

I confirmed with @fpesce that we will have a 1.5.2 but unfortunately it is a bit too late to cherry-pick this to 1.5.2. I will still cherry-pick to 1.5 branch in case we will later have 1.5.3 release.

**Comment by chadlwilson** [comment]
> > Thanks for the suggested workaround; will give this a go. Does this approach work with wildcard matches as well as exact values?
> 
> Yes, it works for both wildcard matches and exact values, but please note that `request.headers[:path]` uses the raw path in Envoy that doesn't strip the query string. So please remember to change back to use the normal `paths` field once your Envoy sidecar is updated to 1.5, sorry for the inconvenience.

Thanks. After looking at this, it seems a bit painful and risky to me to refactor this across all our rules and services. We have many hybrid rules, like the below which seem difficult to express in the same way when using `condition`s without repeating the entire rule since we need the `method`s to be whitelisted as well.

```yaml
    - from:
      - source:
          principals:
            - principal-a
            - principal-b
            - principal-c
      to:
        - operation:
            methods: ["GET", "OPTIONS", "POST"]
            paths: ["/route1", "/route2", "/route3"]
        - operation:
            methods: ["GET"]
            paths: ["/route4*"]
        - operation:
            methods: ["POST", "OPTIONS"]
            paths: ["/route5"]
```
It feels like a not-so-good idea to me to make such changes over something as important as RBAC that I'm going to have to revert later.

> I confirmed with @fpesce that we will have a 1.5.2 but unfortunately it is a bit too late to cherry-pick this to 1.5.2. I will still cherry-pick to 1.5 branch in case we will later have 1.5.3 release.

I see `1.5.2` has been released. I think I shall really hope for a `1.5.3` in short order :-/

**Comment by chadlwilson** [comment]
`1.5.3` has been released - i believe this fix is in that, although not in release notes at https://istio.io/news/releases/1.5.x/announcing-1.5.3/ 

Haven't yet tested but will close this @yangminzhu - let me know if that's not appropriate.

**Comment by chadlwilson** [comment]
Confirmed that the issue seems to be gone now in `1.5.3/1.5.4` on my limited/small test cluster. Will proceed to more exhaustive testing with active traffic. Thanks!
