### ISSUE TITLE
Multiple filter chains with the same matching rules are defined - is a sanity check possible?

### ISSUE THREAD

**Issue by simox-83** [istio/istio#23073]
**Describe the feature request**
Hello,
recently I’ve been fighting with the following error:
Internal:Error adding/updating listener(s) 0.0.0.0_443: error adding listener '0.0.0.0:443': multiple filter chains with the same matching rules are defined

After digging into it I realized that a virtualservice was misconfigured - there was actually a conflict, with 2 different virtualservices, referencing the same host and rules, pointing to 2 different k8s services. That makes perfectly sense, Envoy doesn’t know how to route the traffic and complains about it.
What I don’t understand is why Istio LDS gets to stale. This is a big issue, because basically all the gateways and virtualservices created AFTER the problematic one, won’t take any effect - the listener table doesn’t get updated indeed.
Given that we are managing Kubernetes for the entire company, we have many gw and virtualservices, and that issue leads to:

Very difficult troubleshooting: finding the wrong virtualservice definition is very complicated (unless I am looking at the wrong place, but the pilot logs don’t tell you which virtualservice is causing the problem)
If someone creates gw/vs to expose her/his service after the LDS gets to stale, it won’t work (leading to people asking: why it’s not working? I copied that definition from docs etc…)
I think there is a way to get out of it and it’s a sanity check (or preflight) before deploying it - something that checks for conflicts in gw/vs definitions before applying those to K8s. I am wondering if Istio has a mechanism to do that or if I need to find an alternative way. I am basically looking for a way to proactively avoid this issue.

Ah, this has been tested in 1.2.7 and 1.4.6 with the same result.

**Describe alternatives you've considered**
- Using admission controllers (tbh I need to see if they fit the use case here)
- Write a controller that checks if there are already virtualservices defined the same way 
- Reactive but not too much: setup an alert to check when LDS goes to stale state and do a self-healing by removing the last virtualservice deployed

**Additional context**

**Comment by esnible** [comment]
Try `istioctl analyze`.  If it does not detect the problem we will want to add this feature there.  Can you attach the VirtualServices that exhibit this problem to this work item so that they may be used as a test case for `analyze` enhancement?

In 1.6.x Istio will have an option to set the Status field on VirtualServices that are in conflict.

It is better to prevent errors than to make them detectable.  It would be ideal to have the admission controller detect this problem and prevent adding a VirtualService that makes the system inconsistent.  The current design of the admission controller looks at each resource in isolation.  There is no current plan to allow the controller to consider the other Istio resources when admitting new ones.

**Comment by simox-83** [comment]
Ok so the first vs is defined as follows:
```apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginx
  namespace: containerhosting
spec:
  gateways:
  - mygateway
  hosts:
  - nginx-istiotest.k8s.cnqr.tech
  tls:
  - match:
    - port: 443
      sni_hosts:
      - nginx-istiotest.k8s.cnqr.tech
    route:
    - destination:
        host: my-nginx
        port:
          number: 443
```
the second is pretty much the same, except for the route destination:
```apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mysecondvs
  namespace: containerhosting
spec:
  gateways:
  - mygateway
  hosts:
  - nginx-istiotest.k8s.cnqr.tech
  tls:
  - match:
    - port: 443
      sni_hosts:
      - nginx-istiotest.k8s.cnqr.tech
    route:
    - destination:
        host: wrongservice
        port:
          number: 80
```

This will cause LDS to go to stale:
```istioctl proxy-status
NAME                                                   CDS        LDS                            EDS               RDS        PILOT                           VERSION
istio-ingressgateway-5cf9d78f47-8l42p.istio-system     SYNCED     STALE (Never Acknowledged)     SYNCED (100%)     SYNCED     istio-pilot-bc78c77ff-8k6mw     1.4.6
```
Yeah I agree with you, it's better to prevent errors rather than detect them so I am now looking into OPA (open policy agent) - basically I want to prevent the user to install a conflicting vs and it will be kubernetes rejecting the resource. 

I tried to use istioctl analyze and this is the answer I get:
```
istioctl analyze
Warn [IST0102] (Namespace default) The namespace is not enabled for Istio injection. Run 'kubectl label namespace default istio-injection=enabled' to enable it, or 'kubectl label namespace default istio-injection=disabled' to explicitly mark it as not needing injection
Warn [IST0104] (Gateway meshexpansion-gateway.default) The gateway refers to a port that is not exposed on the workload (pod selector istio=ingressgateway; port 15011)
Warn [IST0104] (Gateway meshexpansion-gateway.default) The gateway refers to a port that is not exposed on the workload (pod selector istio=ingressgateway; port 8060)
Error: Analyzers found issues when analyzing namespace: default.
```
Perhaps it would be good to catch these kind of situations.

Thanks for your help!

**Comment by simox-83** [comment]
Just to let you know that I am using OPA (Open Policy Agent) to prevent this and it seems to work.
Happy to share the details if needed.

**Comment by howardjohn** [comment]
Envoy issue to improve logs: https://github.com/envoyproxy/envoy/issues/11753

The main problem here is the result of this config is due to a bug in pilot config generation. So its hard to give a good error message, because if we knew what error message to log we would have fixed the bug :slightly_smiling_face: . Based on this I am not sure there is much we can do here, except report this specific error as in analyze. I've checked the current code and if we run into this case it will select one, not get rejected config

**Comment by simox-83** [comment]
FYI I kind of solved this by using OPA - the admission controller checks the virtualservices' chains and if it finds a conflict, it won't deploy the offending manifest.
But yeah @howardjohn if we could have also logs in istioctl analyze it would be great (we might setup also alerts based off that)
