### ISSUE TITLE
Unable to install bundled Prometheus with 1.5.1 Operator

### ISSUE THREAD

**Issue by AlexDHoffer** [istio/istio#23078]
**Bug description**

Attempting install the bundled Prometheus with 1.5.1 Operator fails out with an unusual looking error. The service is created, but the operator logs repeatedly fail to instantiate the Prometheus deployment since it says there is an issue with the config.

Here are the configs used for my profile that generated the issue:

<img width="167" alt="Screen Shot 2020-04-19 at 6 22 06 PM" src="https://user-images.githubusercontent.com/19369483/79773112-dfad0000-82e5-11ea-9855-5163c6007d81.png">

<img width="190" alt="Screen Shot 2020-04-19 at 6 22 21 PM" src="https://user-images.githubusercontent.com/19369483/79773120-e176c380-82e5-11ea-8320-e1048e62f951.png">

Here is what the Istio Operator reports:

<img width="764" alt="Screen Shot 2020-04-19 at 6 22 40 PM" src="https://user-images.githubusercontent.com/19369483/79773177-f05d7600-82e5-11ea-9829-b4bf8df428c5.png">

It also reports this:

`error prometheuses.monitoring.coreos.com "prometheus" is forbidden: User "system:serviceaccount:istio-operator:istio-operator" cannot get resource "prometheuses" in API group "monitoring.coreos.com" in the namespace "istio-system"`

**Expected behavior**

The bundled Prometheus instance should deploy.

**Steps to reproduce the bug**

Install the profile using the configs attached above, but with **telemetry and policy components disabled**. Also include configs for Lightstep (access token, etc.). Then, reinstall the profile with telemetry and policy components re-enabled. Observe there is now no running Prometheus instance in the istio-system namespace. Check the logs for the Operator.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

kubectl version 1.16.7
Istio version 1.5.1

**How was Istio installed?**

The manifests for the operator were installed. Then, the manifest for the profile was installed.

**Environment where bug was observed (cloud vendor, OS, etc)**

Azure Kubernetes Service

**Comment by howardjohn** [comment]
https://github.com/istio/istio/pull/23054 is the fix

**Comment by AlexDHoffer** [comment]
@howardjohn thanks, any idea when this would become available to me (e.g. image update)?

**Comment by howardjohn** [comment]
If https://github.com/istio/istio/pull/23090 merges, then the next 1.5.x release, otherwise 1.6

**Comment by johnma14** [comment]
Closing this as fixed by #23090. Thanks.
