### ISSUE TITLE
Upgrade to 1.5.1 using `helm template` causes sidecar errors for new pods

### ISSUE THREAD

**Issue by jaygorrell** [istio/istio#23101]
**Bug description**
My existing pods are fine, but after upgrading to 1.5.1 using `helm template` and the existing microservice deployment, I end up with a problem of new pods not becoming healthy:
```
2020-04-21T02:11:50.640656Z     info    JWT policy is third-party-jwt
2020-04-21T02:11:50.640689Z     warn    Missing JWT token, can't use in process SDS ./var/run/secrets/tokens/istio-tokenstat ./var/run/secrets/tokens/istio-token: no such file or directory
2020-04-21T02:11:50.640704Z     info    Monitored certs: []string{"/etc/certs/cert-chain.pem", "/etc/certs/key.pem", "/etc/certs/root-cert.pem"}
2020-04-21T02:11:50.640710Z     info    waiting 2m0s for /etc/certs/cert-chain.pem
2020-04-21T02:11:50.640723Z     info    waiting 2m0s for /etc/certs/key.pem
2020-04-21T02:11:50.640735Z     info    waiting 2m0s for /etc/certs/root-cert.pem
2020-04-21T02:11:50.640760Z     info    PilotSAN []string(nil)
2020-04-21T02:11:50.640777Z     info    Starting proxy agent
2020-04-21T02:11:50.640862Z     info    Opening status port 15020

2020-04-21T02:11:50.641000Z     info    Received new config, creating new Envoy epoch 0
2020-04-21T02:11:50.641048Z     info    Epoch 0 starting
2020-04-21T02:11:50.641114Z     info    watching /etc/certs for changes
2020-04-21T02:11:50.643637Z     warn    failed to read pod labels: open ./etc/istio/pod/labels: no such file or directory
2020-04-21T02:11:50.644177Z     info    Envoy command: [-c /etc/istio/proxy/envoy-rev0.json --restart-epoch 0 --drain-time-s 45 --parent-shutdown-time-s 60 --service-cluster nginx-redirect.default --service-node sidecar~10.40.164.245~nginx-redirect-6dfd456875-bb8mx.default~default.svc.cluster.local --max-obj-name-len 189 --local-address-ip-version v4 --log-format [Envoy (Epoch 0)] [%Y-%m-%d %T.%e][%t][%l][%n] %v -l warning --component-log-level misc:error --concurrency 2]
[Envoy (Epoch 0)] [2020-04-21 02:11:50.687][18][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:91] gRPC config stream closed: 14, no healthy upstream
[Envoy (Epoch 0)] [2020-04-21 02:11:50.687][18][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:54] Unable to establish new stream
2020-04-21T02:11:51.331741Z     info    Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 1 successful, 0 rejected; lds updates: 0 successful, 0 rejected
2020-04-21T02:11:53.331508Z     info    Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 1 successful, 0 rejected; lds updates: 0 successful, 0 rejected
[Envoy (Epoch 0)] [2020-04-21 02:11:55.068][18][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:91] gRPC config stream closed: 13, grpc: error while marshaling: proto: repeated field Resources has nil element
2020-04-21T02:11:55.334648Z     info    Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 1 successful, 0 rejected; lds updates: 0 successful, 0 rejected
[Envoy (Epoch 0)] [2020-04-21 02:11:55.438][18][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:91] gRPC config stream closed: 13, grpc: error while marshaling: proto: repeated field Resources has nil element
[Envoy (Epoch 0)] [2020-04-21 02:11:55.532][18][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:91] gRPC config stream closed: 13, grpc: error while marshaling: proto: repeated field Resources has nil element
[Envoy (Epoch 0)] [2020-04-21 02:11:55.771][18][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:91] gRPC config stream closed: 13, grpc: error while marshaling: proto: repeated field Resources has nil element
[Envoy (Epoch 0)] [2020-04-21 02:11:56.304][18][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:91] gRPC config stream closed: 13, grpc: error while marshaling: proto: repeated field Resources has nil element
```
Which results in 503s on the istio-proxy health checks.

My values.yaml:
```
global:
  # Enable mTLS for both Istio components as well as applications
  controlPlaneSecurityEnabled: true
  mtls:
    enabled: true

  proxy:
    # Adjust default sidecar claims
    resources:
      requests:
        cpu: 50m
        memory: 128Mi

    # Sidecar Logging
    accessLogFile: ""  # To Enable: /dev/stdout
    accessLogEncoding: JSON

    # Only send internal requests through the mesh
    includeIPRanges: "$((cidr)),172.20.0.0/16"

    # Use Datadog APM
    tracer: "datadog"

  # Disable default ALLOW_ANY outbound policy in favor of proxy.includeIPRanges method above
  outboundTrafficPolicy:
    mode: REGISTRY_ONLY

# Redirect health checks through the Pilot to work with mTLS
sidecarInjectorWebhook:
  rewriteAppHTTPProbe: true
  replicaCount: 2

# Component Configs
galley:
  replicaCount: 2

gateways:
  istio-ingressgateway:
    autoscaleMin: 2
    autoscaleMax: 5
    sds:
      enabled: true

mixer:
  policy:
    autoscaleMin: 2
    autoscaleMax: 5

pilot:
  autoscaleMin: 2
  autoscaleMax: 5
  traceSampling: 100.0

prometheus:
  enabled: false
```
I also tried `global.mtls.auto: false` just to mimic 1.4.x but had the same result.

**Expected behavior**
Helm `template` upgrades work as they usually do and don't cause cluster problems.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istio 1.5.1 (from 1.4.3)
kubectl 1.17.3
helm 2.11.0

**How was Istio installed?**
`helm template` starting around 1.2 and upgraded the same way ever since.

**Environment where bug was observed (cloud vendor, OS, etc)**
EKS

**Comment by jaygorrell** [comment]
For what it's worth, I just re-applied my `1.4.3` manifest with the same config and the failing pods instantly came up.

**Comment by howardjohn** [comment]
Interesting. Sounds like one of our responses is nil or something? Can you reproduce on a fresh install or just upgrade?

**Comment by jaygorrell** [comment]
So far I've only tried on upgrade but it sounds like others have installed 1.6 with no problems... I'd be surprised if _none_ of them were helm template but I could be wrong. It's also worth noting this happened in 2 of 2 clusters I tried it on... both have been around since about 1.2.

If this is upgrades only, it's sorta' related to that cleanup topic from the other day: https://github.com/istio/istio.io/issues/7111.

I'll see if I can find time to create a fresh environment and see if I hit the same problems but alternatively, if you have any ideas, it's a little easier for me to debug the current environments. Is there a way to find out what the nil may be from?

**Comment by jaygorrell** [comment]
Thanks to @howardjohn, we did a little debugging today and found the problem. Here is my understanding but he can add more technical detail if needed.

At some point in the past, istio-pilot had an environment variable `PILOT_DISABLE_XDS_MARSHALING_TO_ANY` set to `true`. That environment variable is no longer included as part of istio-pilot deployments and things default to a `false` behavior.

There are two things that cause the problem here:
1. Having that environment variable set to `true` will cause problems with 1.5.1 as described above.
2. Kubernetes does a merge when using `kubectl apply` on a manifest, which means removed environment variables will not be removed from an existing deployment.

The result of this is that users upgrading from a time when `PILOT_DISABLE_XDS_MARSHALING_TO_ANY` existed on istio-pilot will have a broken deployment on 1.5.1.

**Comment by jlcrow** [comment]
> Thanks to @howardjohn, we did a little debugging today and found the problem. Here is my understanding but he can add more technical detail if needed.
> 
> At some point in the past, istio-pilot had an environment variable `PILOT_DISABLE_XDS_MARSHALING_TO_ANY` set to `true`. That environment variable is no longer included as part of istio-pilot deployments and things default to a `false` behavior.
> 
> There are two things that cause the problem here:
> 
> 1. Having that environment variable set to `true` will cause problems with 1.5.1 as described above.
> 2. Kubernetes does a merge when using `kubectl apply` on a manifest, which seems to have some edge cases where environment variables are not removed.
> 
> The result of this is that users upgrading from a time when `PILOT_DISABLE_XDS_MARSHALING_TO_ANY` existed on istio-pilot will have a broken deployment on 1.5.1.

I believe we just ran into this exact issue going from 1.4.9 > 1.5.10, was there a way to resolve the upgrade or just up the creek without a paddle? @jaygorrell

**Comment by jlcrow** [comment]
> > Thanks to @howardjohn, we did a little debugging today and found the problem. Here is my understanding but he can add more technical detail if needed.
> > At some point in the past, istio-pilot had an environment variable `PILOT_DISABLE_XDS_MARSHALING_TO_ANY` set to `true`. That environment variable is no longer included as part of istio-pilot deployments and things default to a `false` behavior.
> > There are two things that cause the problem here:
> > 
> > 1. Having that environment variable set to `true` will cause problems with 1.5.1 as described above.
> > 2. Kubernetes does a merge when using `kubectl apply` on a manifest, which seems to have some edge cases where environment variables are not removed.
> > 
> > The result of this is that users upgrading from a time when `PILOT_DISABLE_XDS_MARSHALING_TO_ANY` existed on istio-pilot will have a broken deployment on 1.5.1.
> 
> I believe we just ran into this exact issue going from 1.4.9 > 1.5.10, was there a way to resolve the upgrade or just up the creek without a paddle? @jaygorrell

Nevermind, I guess you just remove the env from the values.yaml @jaygorrell
