### ISSUE TITLE
Allow istiod's sidecar-injector listener to be configured with custom certificates

### ISSUE THREAD

**Issue by shakti-das** [istio/istio#23112]
**Describe the feature request**
Istiod's sidecar-injector 443 listener doesn't support custom certificate configuration.

**Describe alternatives you've considered**
We (Salesforce) has it's own PKI infrastructure that handles cert expiration and rotation. There is no provision in istiod to provide those certificates to the injector webhook.

**Additional context**

**Comment by shakti-das** [comment]
@ramaraochavali Issue for configuring certs for sidecar-injector. I am working on the PR for the same.

**Comment by howardjohn** [comment]
@shakti-das is this done?

**Comment by ramaraochavali** [comment]
Yes. We can close this.
