### ISSUE TITLE
Allow configuring external SDS server with Istiod

### ISSUE THREAD

**Issue by shakti-das** [istio/istio#23115]
**Describe the feature request**
Istiod certificate configuration flow currently works with Istiod as CA or Kubernetes as CA or plugged-in CA. If we enhance the functionality to allow configuration with any SDS server then the SDS server can be implemented, owned and managed by a separate team and the SDS service address can be passed as a configuration parameter.

**Describe alternatives you've considered**
Using file mounted certificates the way it was working before 1.6 will work too.

**Additional context**

**Comment by shakti-das** [comment]
@ramaraochavali Configuration support for custom SDS.

**Comment by pparth** [comment]
In our case, we would like to run a custom SDS server as a sidecar as we like to generate short-lived certificates per service instance and not per service type, through Vault. This way, we link the lifetime of the certificate that has a short expiration date with the lifetime of the service instance. As we recycle all our service instances within a few days for security reasons, there is no need for revocation processes to be put in place. In case of a compromise, we just re-deploy the affected stacks and revoke the certificate immediately. 
A sidecar or init container acting as an SDS server that intercepts the requests from Envoy, goes to Vault to perform the necessary actions and return with a certificate to be used, seems like a solution, if i understand the specificities correct.
