### ISSUE TITLE
Monitoring kube-system and all containers

### ISSUE THREAD

**Issue by nixgadget** [istio/istio#2311]
Ive got few questions regarding istio and prometheus.

1. Is there any trickery to get metrics from `kube-system` ? Pulling things like cpu, mem info from master nodes and anything else in `kube-system`. I havent been able to find any documentation around this ?
2. If not how easy is it to disable the `mixer` and plug our own prometheus implementation such as CoreOS's prometheus-operator ? I assume the meshing will not be affected doing so.

**Comment by sdake** [comment]
#1. I'm not clear why Istio should have responsibility for providing metrics from kube-system.
#2. mixer is an optional component of Istio.  Mixer is only necessary if you desire metrics out of Istio itself.  Mixer feeds information to Istio's specific version of Prometheus.

Would you mind expanding on your use case?

**Comment by douglas-reid** [comment]
You can use cadvisor integration to monitor resource consumption for kube components. There is also kube-state-metrics (and heapster) for more monitoring options at the k8s-level. 

Prometheus ships as an add-on for Istio, with a default configuration. If you have your own Prometheus setup, you can disable the prometheus install, using helm to generate the appropriate yaml.

I'm going to close this issue, as there are no actionable items for resolution. Please feel free to follow-up on mailing-lists or rocket chat.
