### ISSUE TITLE
Developers checking in assets.gen 

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#23124]
Examples:
* https://github.com/istio/istio/pull/23104
* https://github.com/istio/istio/pull/23097

We need ways to prevent developers from checking these in - ideally by avoiding it completely, or at least failing tests if they do.

There was a check to ensure it doesn't change but it seems like it was reverted

**Comment by ostromart** [comment]
I'm going through fixing this. The check was reverted because I originally put it into the wrong place and it got blown away by an update to common.

**Comment by ostromart** [comment]
https://github.com/istio/istio/pull/23252
https://github.com/istio/istio/pull/23312
https://github.com/istio/istio/pull/23213
