### ISSUE TITLE
Multiple egress gateways

### ISSUE THREAD

**Issue by padzikm** [istio/istio#23133]
Hi, is it possible to create multiple egress gateways? My goal is to have strict control over which pods have access to which external services. As far as I understand external hosts are all specified in one gateway resource, so when any pod have access to egress gateway it has access to all external services, for which that egress gateway has defined access. As a result I want to create one egress gateway per one external service, so different pods can be routed to different egress gateways - how can I achieve this?

**Comment by esnible** [comment]
Yes, you can create multiple egress gateways.

Install Istio using a custom IstioOperator or add `--set components.egressGateways[1].enabled=true`, `--set components.egressGateways[2].enabled=true` etc.

I haven't actually done this recently.  You may need to set other things.

I recommend using a custom Istio Operator instead of `--set` because it is easy to screw up using complex `--set` options!

**Comment by padzikm** [comment]
'I haven't actually done this recently. You may need to set other things.' - this isn't the answer I can go to production environment with. I don't know istio's internals and with that I can't be sure (even after multiple tests) that everything is set up correctly in edge cases. Especially when there is unresolved discussion about setting up multiple ingress gateways with just setting parameters during operator install - both ingress and egress are gateways, so maybe there is some connection in this case.
Can someone provide strict answer that it can be done and how exactly?

**Comment by Laci21** [comment]
@padzikm, We encountered the same issue and solved it for ourselves, you can read more about it in this blog post: https://banzaicloud.com/blog/istio-multiple-gateways/. Please note, that this solution uses the open-source Banzai Cloud [Istio operator](https://github.com/banzaicloud/istio-operator) and not the official Istio operator by the Istio community.
