### ISSUE TITLE
Remote cluster without istiod - needs to create istio-ca-root-cert cm for each ns

### ISSUE THREAD

**Issue by linsun** [istio/istio#23138]
**Describe the feature request**

or run a lightweight istiod just for that purpose.   Based on some discussion from https://github.com/istio/istio/issues/23028#issuecomment-617409037
As part of #22934

**Describe alternatives you've considered**

**Additional context**

**Comment by linsun** [comment]
existing code - https://github.com/istio/istio/blob/9031d67e2917718079ac5d21fc3b26fd3bdb7507/pilot/pkg/bootstrap/namespacecontroller.go#L66

**Comment by linsun** [comment]
Had some discussion within environment WG today on this and some offline discussion as well.  The summary is that we have agreed the simple approach is to modify existing Istiod code to work with multiple k8s clients from each plane to check for namespaces and create the istio-ca-root-cert configmap for each namespace and watch for namespace updates.  The main cluster should already has access to each plane's k8s API servers via the istio-remote-secret.

**Comment by linsun** [comment]
Discussed with @irisdingbj and she kindly agreed to help with this.

**Comment by irisdingbj** [comment]
https://github.com/istio/istio/issues/22934

**Comment by linsun** [comment]
Close this as this has been working okay for me
