### ISSUE TITLE
金丝雀发布未按照虚拟服务规则权重进行流量转发canary deployment could not make traffic routing based on virtualservice weights setting rules.

### ISSUE THREAD

**Issue by yuenwah** [istio/istio#23145]
**Bug description**
canary deployment could not make traffic routing based on virtualservice weights setting rules
**Expected behavior**
![image](https://user-images.githubusercontent.com/34834139/79957300-f30dc600-84b3-11ea-9b04-9943cb93ce68.png)
This configuration should forward all traffic to the v1 version when accessing, but this is not the case
![image](https://user-images.githubusercontent.com/34834139/79957378-10429480-84b4-11ea-89c2-c214a5c1c778.png)

**Steps to reproduce the bug**
Modifying virtualservice rules does not take effect
**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
control plane version: 1.4.7
helm:v2.10.0
**How was Istio installed?**
rancher
**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by carolynhu** [comment]
@yuenwah for better communication and helping the istio engineers/contributors understand your problem. You may be supposed to translate your issue/bug into english? Thanks for your collaboration.

**Comment by yuenwah** [comment]
Will this rule apply only when entering from the istio-ingress gateway?

**Comment by esnible** [comment]
I have seen this error before.

The "weight" field is optional.  Istio cannot distinguish between a weight of 0 and an unset weight.  Setting the weight explicitly to 0 is the same as setting it to 100.

@istio/wg-networking-maintainers : is it too late to change the protobuf so that the default value for weight is deserialized as -1?  Then Istio could distinguish between unset and set-to-0 weights.  Unset weights could default to 100.  This question comes up every release.  I can't find the old discussion, but I know we have had it.

**Comment by howardjohn** [comment]
I am not sure if changing from `int` to `int wrapper` is a compatible change. If it is seems like a good idea

**Comment by howardjohn** [comment]
Seems like even if I have two hosts, one with `weight: 100` and one with no weight specified this is wrong behavior. Isn't weight supposed to add up to 100? Do we just throw out weights if a single item is missing a weight?

**Comment by esnible** [comment]
@yuenwah my previous comment might be mistaken!

I am not seeing `-` in your screenshot.  Maybe it is too small to see?  Follow the formatting of example _samples/bookinfo/networking/virtual-service-reviews-50-v3.yaml_ and have dashes before each `destination`.

**Comment by esnible** [comment]
@howardjohn I am not a protobuf guy and maybe my suggestion is foolish.  Also I was remembering 0.9 code and not 1.5.0 code.  I looked up the code now and it looks correct.

This VS is valid.  A VirtualService is valid with 0 weights as long as all the weights add up to 1:
https://github.com/istio/istio/blob/master/pkg/config/validation/validation.go#L2332

https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/route/route.go#L456 seems to skip clusters with 0 weight if are two destinations.  This example has **seems** to have two Destinations, but it doesn't, because of my comment https://github.com/istio/istio/issues/23145#issuecomment-618464706 .  Let's see what yuenwah confirms.

**Comment by yuenwah** [comment]
> @yuenwah my previous comment might be mistaken!
> 
> You may have a YAML formatting error. I am not seeing `-` in your screenshot. Maybe it is too small to see? Follow the formatting of example _samples/bookinfo/networking/virtual-service-reviews-50-v3.yaml_ and have dashes before each `destination`.

@esnible 
As shown, there is "-"
![image](https://user-images.githubusercontent.com/34834139/80168863-937bfb80-8616-11ea-8a48-4306cd491e19.png)

**Comment by hzxuzhonghu** [comment]
We can do a quick fix, do a more strict validation to intercept this invalid config.

Currently we have soem logic when building route 
```
			if dst.Weight == 0 {
				// Ignore 0 weighted clusters if there are other clusters in the route.
				// But if this is the only cluster in the route, then add it as a cluster with weight 100
				if len(in.Route) == 1 {
					weight.Value = uint32(100)
				} else {
					continue
				}
			}
```

Not sure why it does not work

@yuenwah Can you share your config dump of the client?

**Comment by yuenwah** [comment]
> We can do a quick fix, do a more strict validation to intercept this invalid config.
> 
> Currently we have soem logic when building route
> 
> ```
> 			if dst.Weight == 0 {
> 				// Ignore 0 weighted clusters if there are other clusters in the route.
> 				// But if this is the only cluster in the route, then add it as a cluster with weight 100
> 				if len(in.Route) == 1 {
> 					weight.Value = uint32(100)
> 				} else {
> 					continue
> 				}
> 			}
> ```
> 
> Not sure why it does not work
> 
> @yuenwah Can you share your config dump of the client?

@hzxuzhonghu 看你在杭州，我就用中文了，我没太明白是说要我共享什么

**Comment by yuenwah** [comment]
@esnible @howardjohn The current architecture is relatively simple, as shown in the figure, svc and virtualservices and destinationrules are as follows
![image](https://user-images.githubusercontent.com/34834139/80181887-4b6dd080-8638-11ea-90fe-45681679dc5a.png)
![image](https://user-images.githubusercontent.com/34834139/80181966-72c49d80-8638-11ea-9189-e2d95721a106.png)
![image](https://user-images.githubusercontent.com/34834139/80182028-912a9900-8638-11ea-9717-785b8d6b23c3.png)
![image](https://user-images.githubusercontent.com/34834139/80182043-9982d400-8638-11ea-932b-ef02bbfd58b2.png)

**Comment by hzxuzhonghu** [comment]
So from the above flow, i can tell that no outbound route takes effect, and the behavior is expected.

**Comment by yuenwah** [comment]
> So from the above flow, i can tell that no outbound route takes effect, and the behavior is expected.
@hzxuzhonghu Am I missing something here?

**Comment by hzxuzhonghu** [comment]
Yes, please understand that the route setting takes effect on the proxy's outbound direction. That is to say your traffic should be through a proxy.  So behind the nginx ingress, there should be istio's ingress gateway.

**Comment by yuenwah** [comment]
> Yes, please understand that the route setting takes effect on the proxy's outbound direction. That is to say your traffic should be through a proxy. So behind the nginx ingress, there should be istio's ingress gateway.

Do I need to go to the istio-gateway for calling within the service mesh?

![image](https://user-images.githubusercontent.com/34834139/80442499-9c830a80-893f-11ea-97a3-ccb5d3ec04ed.png)

**Comment by hzxuzhonghu** [comment]
>Do I need to go to the istio-gateway for calling within the service mesh?

It is not a must. But we recommend that for general users

**Comment by yuenwah** [comment]
> > Do I need to go to the istio-gateway for calling within the service mesh?
> 
> It is not a must. But we recommend that for general users

But the problem now is that the application calls in the grid do not follow the rules of virtual services. For example, application A calls application B. Application B is configured with virtual services, but the rules do not take effect
