### ISSUE TITLE
Istio 1.4.7 release does not contain ISTIO-SECURITY-2020-004 fix

### ISSUE THREAD

**Issue by ElliotPM** [istio/istio#23146]
The release notes for Istio 1.4.7 state that the security vulnerability relating to Kiali has been fixed; however, the commit to fix this is not present in the release.

I have installed Istio 1.4.7 using Helm with Kiali 1.15.2 (and other compatible Kiali versions) but the error seen in this issue remains: https://github.com/kiali/kiali/issues/2624

see commit: https://github.com/istio/istio/commit/38a90fd6760144382cf93611524b144afac4c47e

Which is present in the 1.5.1 release:
https://istio.io/news/releases/1.5.x/announcing-1.5.1/
https://github.com/istio/istio/compare/1.5.0...1.5.1

but not the 1.4.7 release:
https://istio.io/news/releases/1.4.x/announcing-1.4.7/
https://github.com/istio/istio/compare/1.4.6...1.4.7

Have I made a mistake, or has the security fix been accidentally left out of the 1.4.7 Istio release?

**Comment by jmazzitelli** [comment]
The istioctl installer was fixed. If you installed with the old helm charts, then it wasn't fixed there. I thought the helm charts were deprecated. In any event, add these two lines to the kiali configmap template in the helm chart:

```
login_token:
  signing_key: {{ randAlphaNum 10 | quote }}
```

I don't know where these helm charts are now - they appear to have been deleted from the install/ directory which is where they used to be.

**Comment by ElliotPM** [comment]
Thanks for the response. I see, we haven't tested using Istioctl but I can't see any commit between 1.4.6...1.4.7 which whould have resolved the issue?

I can see from the docs that Istio is in the process of deprecating using helm to install, but some pages refer to this as a work in process and others say it will happen in future, so we expected the security fix to be added there as well.

I understand that these things change quickly though; thank you for offering a potential solution. We will be migrating to use Istioctl shortly to avoid any future issues.

Thanks,


Elliot

**Comment by howardjohn** [comment]
Fixed by #23445

And https://istio.io/latest/news/support/announcing-1.4-eol-final/
