### ISSUE TITLE
Add observability to ledger

### ISSUE THREAD

**Issue by therealmitchconnors** [istio/istio#23160]
istio.io/pkg/ledger is difficult to introspec for debugging, and would be more useful with a GetFullGraphAtVersion which returns all key value pairs at that version, rather than just operating on one kv pair at a time

**Comment by esnible** [comment]
Shall we make this P2?  Which milestone?

**Comment by esnible** [comment]
@therealmitchconnors Can you triage this?  P2?

**Comment by esnible** [comment]
@therealmitchconnors Can you triage this? P2?

**Comment by therealmitchconnors** [comment]
This was done in pkg repo in the last few months.
