### ISSUE TITLE
Propose creating a Wasm extension repo

### ISSUE THREAD

**Issue by bianpengyuan** [istio/istio#23168]
Propose creating a wasm extension repo under Istio org, it has several roles:
* Hosts production extensions, including extensions migrated from `istio/proxy` repo (prometheus stats, metadata exchange, attribute generation, etc) and extensions to get parity with Mixer functionality. This follows the direction of using upstream envoy directly and removing `istio/proxy`.
* Hosts easy-to-consume example extensions which demonstrate essential Wasm ABI (http/grpc call out, timer, stats, log etc) as well as major use cases (policy, telemetry, and request mutation).
* Provides common utils and test framework that developer could import when writing out of tree Istio Wasm extensions. Provides doc, tips and best practice of developing, managing and deploying wasm extension.

Action items to reach the goal:
- [x] Clean up and untangle test framework in `istio/proxy` repo to make it importable from another repo.
- [x] Organize common functions such as node info and handy stream info access function into a base extension class, and use that extension class for the existing extensions in `istio/proxy`.
- [x] Create the repo, add example extensions and Mixer adapter equivalent extensions into it by referencing the framework and utils created in the first two tasks.

Items to move things off `istio/proxy`: 02/17/2021 editting: proxy migration is unlikely going to happen.
- [ ] ~~Move go test framework and the common extension class into the new repo.~~
- [ ] ~~After Wasm ABI/runtime is stabilized with upstreaming, and performance is improved, migrate existing production module (stats, metadata exchange, and stackdriver modules) from `istio/proxy` to the new repo and migrate from compiled in/wasm dual modes to wasm only.~~
- [ ] ~~Remove `istio/proxy` repo.~~

Estimated time line is creating the new repo with examples extensions by 1.7, move things off istio proxy by 1.8, or further if we cannot reach performance requirement.

@mandarjog @PiotrSikora @duderino @jplevyak @douglas-reid @kyessenov @gargnupur Feedback is really appreciated.

**Comment by kyessenov** [comment]
It's probably easier to fork istio/proxy and delete a bunch of stuff.
 We should also make sure the footprint is small in shared routines. E.g. do not import protobuf by default.

**Comment by bianpengyuan** [comment]
If fork, we need to nuke LOT of things except the test framework and some common utils? I don't think we want to have duplicated code of any extensions in two repos right? Also do we expect the new repo to still be in dual mode (Wasm + compiled in)? I would think of it as a Wasm only repo,  otherwise we will still need to maintain upstream envoy dependencies. If it is Wasm only, I don't think it makes sense to fork?

**Comment by mandarjog** [comment]
@bianpengyuan this differs from the previous doc in which we wanted a repo in the istio-ecosystem org.

I do see the need for 1st party istio extensions to be hosted in the istio org, but that is just the proxy repo today.

Should prod extensions and the common utils be in the same repo? Would it be better that that to be a separate repo?

**Comment by kyessenov** [comment]
Additionally, we need to decide what to do with the supporting infrastructure. Build system, testing framework(s) may belong outside of istio in proxy-wasm. There is an extra pain with the multi-repo set-up.

**Comment by bianpengyuan** [comment]
The original thought was istio-ecosystem, but I think it will need to be released together with Istio, so better just put it under istio org. As @kyessenov said, it is more efficient for us to just put common utils in the same repo. 3rd party developer experience won't be different whether plugins and utils are in the same repo or different ones. So either we just evolve in `istio/proxy` repo and (probably) rename to something Wasm when it is ready in the future, or creating a new wasm-extension repos to host common utils and various extensions and gradually migrate prod extensions from istio-proxy to the new repo. Latter seems to be cleaner to me.

Re supporting infrastructure, build system definitely belongs to the proxy-wasm. For other parts I'd rather just develop in Istio context and upstream if turns out to be generally useful and motivated.

**Comment by mandarjog** [comment]
What about non-core istio extensions?
Do we want to accept it in istio org? I don’t think so.
Installing an extension from istio repo should mean that it is reviewed and maintained by our team.
I agree we need a repo inside istio, but we also need a rep outside istio.

Timing
1. When do we need to do this ? We can make the switch at the beginning of 1.7
2. As long and we are shipping istio-proxy with null sandbox extensions, that repo should stay.
3. If the test fw moves to the new repo, will istio-proxy take that as a dependency?
4. Since examples are ready to go do they belong inside istio org or in the eco system?

**Comment by bianpengyuan** [comment]
Ok, make sense to me about the separation of examples from core extensions. Common and frameworks should always stay with core, so that they could be released together. Ecosystem will only have examples which takes `istio/proxy` as a dependency for now.

Timing wise, by 1.7 let's make common & frameworks ready in istio/proxy and add example wasm modules into ecosystem, which takes a dependency on istio/proxy. By 1.8 or later release after ABI stabilization / perf improvement, we could nuke and migration from `istio/proxy` to some new repo. wdyt?

**Comment by kyessenov** [comment]
Taking a dependency on istio/proxy SGTM. Later we can migrate to proxy-wasm or something new. I would generally prefer less big bang.

**Comment by bianpengyuan** [comment]
Done by https://github.com/istio-ecosystem/wasm-extensions
