### ISSUE TITLE
Consider exposing more envoy generated stats by default

### ISSUE THREAD

**Issue by bianpengyuan** [istio/istio#23166]
Back to Istio 1.1 release, we trimmed Envoy native stats to only collect control plane cluster stats due to excessive memory usage https://github.com/istio/istio/issues/7912. Lack of these low level signals sometimes makes it hard to debug proxy issues. Over time, Envoy has made improvement to the stats system especially its memory footprint, which makes it possible to enable envoy stats again. This issue is to track work items for that:

- [ ] Measure memory consumption when turning on all stats, especially memory usage from per peer cluster/service stats to understand impact on fan-in/fan-out service.
- [ ] Measure cpu/memory impact on prometheus, provide operation guide if it turns out to be a problem.
- [ ] if all stats is turned on by default, add mechanism or provide guide about how to limit impact on fan-in/fan-out service.

cc @mandarjog @douglas-reid @kyessenov

**Comment by bianpengyuan** [comment]
Related: https://github.com/istio/istio/issues/19335

**Comment by mandarjog** [comment]
@jmarantz cc

**Comment by douglas-reid** [comment]
@esnible for visibility

**Comment by esnible** [comment]
I agree.  Back in 1.0 days I had a tool, https://github.com/esnible/envizistion , which would output the number of success, failure, timeout, 40x, and 50x messages for a listener/cluster/endpoint.  It used Envoy.

The approach I've heard from the networking working group is that we shouldn't be asking Envoy to hold these, but should read them from Prometheus.  What I don't have is a list of the differences between the stats available to Envoy and the stats sent to Prometheus.  Do you have such a list?

**Comment by bianpengyuan** [comment]
I did some experiment on this, the test set up was:
* Apply gateway configuration which creates 200 clusters with round robin routing.
* Cap ingress gateway instance at 1.
* Send 1000 qps for half hour.

I ran the test three times with three different proxy image:
1) `gcr.io/istio-testing/proxyv2:1.8-alpha.c919b0b84ab9c8f322adf470e31f28fcf583e654` which is a dev build from https://github.com/istio/istio/commit/c919b0b84ab9c8f322adf470e31f28fcf583e654 and uses current default [stats_matcher](https://github.com/istio/istio/blob/e63ab2161fde82e84d03e5ab7736d715a5879276/tools/packaging/common/envoy_bootstrap.json#L96) with very limited [stats](https://github.com/istio/istio/blob/9939ad57ed0e7154df6637948bc7b2b3e0ce4201/pkg/bootstrap/config.go#L54).
2) A dev build based on https://github.com/istio/istio/commit/c919b0b84ab9c8f322adf470e31f28fcf583e654, with stats_matcher removed from bootstrap, which will make envoy expose all stats.
3) A dev build based on 2), and with symbol table turned off, by adding `--use-fake-symbol-table 1` to envoy command arg.

https://snapshot.raintank.io/dashboard/snapshot/gbD1ImNXfH60884atVmnyawYKe1X46Kc?orgId=2 has dashboard snapshot of these three runs, and here is a screen shot of it:
![2020-07-25](https://user-images.githubusercontent.com/34738376/88472183-0ff7d200-cec5-11ea-8a4c-aca6bfbf274f.png)

some observations:
1) When turned on all stats, envoy CPU usage grows about 20%~30%, memory usage grows more than 30%.
2) With all stats are turned on, when turning off symbol table, CPU usage reduces about 10%, while memory usage only increases slightly.
3) When all stats turned on, there is always a CPU spike during proxy start up.

Based on these observation, I think we still cannot turn on all Envoy stats by default. Instead, we still need to use inclusion list based approach to expose important ones.

@jmarantz I am wondering does this result meets with your expectation?

**Comment by mandarjog** [comment]
@bianpengyuan thanks for doing this.
What is the impact on sidecars? I expect it to be lower since they don't get so many clusters.

Can you measure that? We can have different defaults for sidecar and ingress.

**Comment by bianpengyuan** [comment]
> The approach I've heard from the networking working group is that we shouldn't be asking Envoy to hold these, but should read them from Prometheus. What I don't have is a list of the differences between the stats available to Envoy and the stats sent to Prometheus. Do you have such a list?

@esnible Sorry I missed your question before. I don't have such a list. [This](https://github.com/istio/istio/blob/9939ad57ed0e7154df6637948bc7b2b3e0ce4201/pkg/bootstrap/config.go#L54) has the list of stats prefix that we by default expose at envoy. The part we hide is mainly cluster stats and listener stats.

**Comment by bianpengyuan** [comment]
@mandarjog Sure I can measure it.

**Comment by bianpengyuan** [comment]
@mandarjog So to measure impact on sidecar, it is basically change the current test to use lower concurrency (2) and cluster number (~30), right? Or is there any other changes you can think of?

**Comment by mandarjog** [comment]
30 cluster is a namespace would be a high number. I think 20 is better estimate. Concurrency should not matter here, but we know it affects memory elsewhere .

I think if you enable all stts in one standard service graph namespace you can record the metrics for a few sidecars.

**Comment by bianpengyuan** [comment]
So I have done the test for sidecar, it runs the same test cases: current stats matcher with symbol table, all stats with symbol table, all stats w/o symbol table: https://snapshot.raintank.io/dashboard/snapshot/lCuOoIL18PWxz6Dpjv4vKXFFAhoz0d4S?orgId=2 It gets the similar result: After turning on all stats, memory grows about 30%, cpu usage increases a bit (less than 10%). When turning off symbol table with `--use-fake-symbol-table 1`, memory usage does not seem to be impacted much. It is understandable that gateway and sidecar tests gave the similar result, memory usage should roughly proportional to the number of clusters.

Based on sidecar numbers, it looks like still quite expensive to turn on all stats even with just 20~30 clusters at sidecar.

Also the graph in [gateway test](https://github.com/istio/istio/issues/23166#issuecomment-663938242) is a bit wrong. I accidentally enabled access log in the third case. Here is the new snapshot: https://snapshot.raintank.io/dashboard/snapshot/Rm8GLQCXVzARMGrMk1U6LoZGOy1Ke2Ns?orgId=2. Most observations there still applies, except that after turning off symbol table, envoy is no longer consuming less CPU.

**Comment by bianpengyuan** [comment]
As a step back, propose exposing stats with the following stats suffixes by default:

* Downstream connection stats, `downstream_cx_total`, `downstream_cx_active`, `downstream_cx_http1_total`, `downstream_cx_http2_total`, `downstream_cx_http1_active`, `downstream_cx_http2_active`, `downstream_cx_destroy`, `downstream_cx_destroy_remote`, `downstream_cx_destroy_local`, `downstream_cx_destroy_local_active_rq`, `downstream_cx_destroy_remote_active_rq`

* Upstream connection stats, `upstream_cx_total`, `upstream_cx_active`, `upstream_cx_destroy_local`, `upstream_cx_destroy_remote`, `upstream_cx_destroy_local_with_active_rq`, `upstream_cx_destroy_remote_with_active_rq`, `upstream_cx_close_notify`

* HTTP request route stats, `no_route`, `no_cluster`, `rq_redirect`, `rq_total`, `rq_direct_response`, `rq_reset_after_downstream_response_started`

* Lisener debug stats suffix  `no_filter_chain_match`, `downstream_pre_cx_timeout`

* TCP metadata exchange stats suffix `alpn_protocol_not_found`, `alpn_protocol_found`, `initial_header_not_found`, `header_not_found`, `metadata_added`

An experiment is performed with these stats created by default, CPU and memory usage diff is negligible: https://snapshot.raintank.io/dashboard/snapshot/21R8BjkvGQCNhevume5pShsJpbZD6Hbx

**Comment by douglas-reid** [comment]
@bianpengyuan what is the impact on the storage side?  @Stono thoughts on implications for your use cases?

**Comment by Stono** [comment]
Personally, I wouldn't want any additional metrics than those we're exposing now.  At the least even if you did decide to add a bunch more, we'd ideally want to be able to ensure we maintain the current setup by deterministically declaring what we use now.

I haven't done a comparison of your list vs what we use now, but if it helps we configure:

```
sidecar.istio.io/statsInclusionSuffixes: outlier_detection.ejections_active,outlier_detection.ejections_overflow,outlier_detection.ejections_enforced_total,upstream_cx_active,upstream_cx_total
```

Other users won't even want those.

When you're dealing with 400 workloads across as many namespaces, even the smallest metric increase can ddos prometheus and has to be done extremely carefully.  Something I've learned after weeks of fine tuning istio+prometheus is that it's like working in an extremely delicate glass house.

**Comment by mandarjog** [comment]
Do you not use any `downstream` stats at ingress? I think they are useful are ingress.

Alternatives are 
1. Just document the useful stats sets.
2. Add a short hand that encodes those sets, so that folks do not copy/paste wrong config.

**Comment by Stono** [comment]
@mandarjog no we don't but remember we don't use istio ingress, we use nginx (so get metrics from that).

I would personally advise keeping the base install minimal and making it super clear (either via documentation or toggles) how to build up on top of that.  Otherwise prepare yourself for a raft of "I've upgraded istio and prometheus has died" and "I've upgraded istio and the sidecar is using way more memory" type issues.

**Comment by douglas-reid** [comment]
> Do you not use any `downstream` stats at ingress? I think they are useful are ingress.
> 
> Alternatives are
> 
> 1. Just document the useful stats sets.
> 2. Add a short hand that encodes those sets, so that folks do not copy/paste wrong config.

I like the alternatives. I'm imagining a (tested and validated) Task that covers adding those stats, the implications on storage, and examples of how to use (in debugging, etc.)

**Comment by bianpengyuan** [comment]
Yeah I am working on gathering data to measure the storage impact of enabling these stats. Some of them are really cheap and it does not hurt to enable those by default. I will post the result here and probably a trimmed list of stats.

**Comment by Stono** [comment]
> Some of them are really cheap and it does not hurt to enable those by default

Every metric * dimensions on that metric * number of pods (in my case, 1000+)

I think you need to be careful when you say "really cheap".  I've invested an incredible amount of effort getting our metric scraping with istio under control at scale, any unexpected growth creeping in is unwelcome.

**Comment by kyessenov** [comment]
I wonder if there is a particular badly behaving subset of stats. The memory footprint points at some cardinality issue within Envoy. We definitely don't want to expose those stats.
