### ISSUE TITLE
run_upgrade_test.sh in istio/tools repository fails due to charts is no longer bundled in the release

### ISSUE THREAD

**Issue by lei-tang** [istio/istio#23172]
**Bug description**
run_upgrade_test.sh (https://github.com/istio/tools/blob/master/upgrade/run_upgrade_test.sh) in istio/tools repository fails due to charts is no longer bundled in the release.
The error message is as follows:
****************
istioctl upgrade istio using version 1.6-alpha.b8b73e85c1f83b93acde15d25f1fbf83719355f7 from to_dir.UkuznB/istio-1.6-alpha.b8b73e85c1f83b93acde15d25f1fbf83719355f7.
****************
Error: failed to generate Istio configs from file [], error: compiled in charts not found in this development build, use --charts with local charts instead or run make gen-charts

**Expected behavior**
https://github.com/istio/tools/blob/master/upgrade/run_upgrade_test.sh should succeed.

**Steps to reproduce the bug**
export SOURCE_TAG=1.5_latest; export TARGET_TAG=master; export INSTALL_OPTIONS=istioctl;
./run_upgrade_test.sh

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.6-alpha.b8b73e85c1f83b93acde15d25f1fbf83719355f7. The istioctl is installed through the test script and is from the latest master

**How was Istio installed?**
The Istio is installed through the test script. 

**Environment where bug was observed (cloud vendor, OS, etc)**
Linux

**Comment by JimmyCYJ** [comment]
cc @JimmyCYJ

**Comment by carolynhu** [comment]
This bug introduced by recent operator change. I can fix it! @lei-tang Thanks for filing this!

**Comment by lei-tang** [comment]
Before the final solution for this issue is merged, a workaround for this issue is added in: https://github.com/istio/tools/pull/912.
