### ISSUE TITLE
Determine Kubernetes version support range for 1.6

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#23184]
Currently 1.5 is 1.14-1.16. Per prior art of shifting by one, we are at 1.15-1.17. 

However, Kubernetes 1.18 has been out for a while and our CI runs on this version. We don't run release qual on 1.18 since we run on GKE and GKE doesn't support 1.18 yet - however we could use IKS or manually build a cluster. 

If we do support 1.18, we need to consider if we should support 4 versions at once, 1.15-1.18. If we do this, are we stuck on 4 versions forever?
If we don't support 4 versions, is it appropriate to drop 2 versions at once and support 1.16-1.18?

Note that we cannot feasibly support 1.16-1.19 due to https://github.com/istio/istio/issues/18838, which would impact our 1.7 support policy

**Comment by linsun** [comment]
Thank you @howardjohn for tracking this.  For 1.18, @ericvn is looking at qualification test with IKS.  I'll open a WI and link to this to track it properly.

**Comment by linsun** [comment]
My vote would be support 1.16-1.18 if we can qualify 1.18.

**Comment by howardjohn** [comment]
I am -1 on 1.16-1.18 because I don't think its fair to users to drop 2 versions without warning. many users are on 1.15 for now. I would rather support 4 versions than that personally

**Comment by nrjpoddar** [comment]
> I am -1 on 1.16-1.18 because I don't think its fair to users to drop 2 versions without warning. many users are on 1.15 for now. I would rather support 4 versions than that personally

1.15-1.17 or 1.15-1.18 if we can qualify it. Users shouldn't be penalized for our delays in releasing coupled with timely releases of K8s.

**Comment by linsun** [comment]
@howardjohn @nrjpoddar I'm good with 1.15 to 1.18 as well.

@knrc @dgn pls chime in from redhat service mesh perspective.

**Comment by linsun** [comment]
cc @sdake

**Comment by sdake** [comment]
@linsun four versions is documented in the [RFC Istio + Kubernetes Support Matrix](https://docs.google.com/document/d/14Xfe9V0vv8d7W75c21d-cY2XyK6xvRH0_Kg8j_zfh4Y/). Moving to four supported versions is not without its challenges. I have added to the T&R agenda for Tuesday where we can further discuss.

Cheers
-steve

**Comment by howardjohn** [comment]
In TOC we approved 1.15-1.18

**Comment by rmichela** [comment]
How will Istio behave when attempting to install on older versions of Kubernetes like 1.14? Will istioctl or the istio operator warn the user, or refuse to install altogether? Is there anything in Istio inherently incompatible with older versions of Kubernetes, or is it just that older versions are untested (use at own risk)?

**Comment by howardjohn** [comment]
It will not refuse but should warn. In general it's use at your own risk -
specifically for 1.6 though we use a field that is added in 1.15 for CRDs.
In the next release we will also upgrade to newer APIs introduced in k8s
1.16 so these minimum versions will be hard minimums

**Comment by rmichela** [comment]
I'm worried removing backwards compatibility with older kubernetes versions will negatively affect Istio adoption. Between dropping support for every N-2 Istio version and only supporting the latest three versions of kubernetes, you force Istio users to upgrade both their kubernetes cluster and Istio version at least twice a year. Both upgrades are a significant investment. Keeping on top of and stabilizing every upgrade is a full time job. Is there really no way to maintain backwards compatibility with older kubernetes versions, even if it means degraded Istio capabilities?

**Comment by rmichela** [comment]
Also worth considering is that the cloud vendors tend to lag behind kubernetes releases, sometimes drastically. As of today, the most recent supported kubernetes versions are:

Amazon EKS: 1.16.8
Azure AKS: 1.15.2
Google GKE: 1.16.8

According to your schedule, Istio 1.8 will require a minimum of kubernetes 1.17. Have you coordinated with all the major cloud vendors to ensure they will have 1.17 available by Q4, or are you OK alienating whole swaths of the public cloud?

**Comment by howardjohn** [comment]
Some background info: https://docs.google.com/document/d/14Xfe9V0vv8d7W75c21d-cY2XyK6xvRH0_Kg8j_zfh4Y
@rmichela I personally do not think its a major issue with our current positioning. Here is why:
* Kubernetes 1.14 is not currently supported by Kubernetes itself, and has not been for many months
* We are more leniant than surrounding products.
  * Knative supports 1.16+: https://github.com/knative/serving/releases
  * Tekton pipelines supports 1.15+: https://github.com/tektoncd/pipeline/releases/tag/v0.11.0
* Maintaining older version *does* have a substantial impact on complexity of Istio. For a while we were supporting a huge range of versions (unofficially). however, k8s has been rapidly removing deprecated APIs. For example, the CRD and webhook APIs we currently are using are shortly being removed, so we must jump to the new ones, meaning we lose support for older versions in the process.

If your goal is to use a supported version of Istio and Kubernetes, its not clear to me why Istio's Kubernetes support would be an issue, as we support Kubernetes versions months after they are officially unsupported by Kubernetes. 

FWIW, GKE supports 1.17 using release channels today, so I would assume many GKE users will be on 1.17 by EOY (cannot speak for other k8s providers, as I am not familiar with them as much nor their release process). Also users are under no obligation to upgrade to Istio 1.8 the same day it comes out - they can continue to use Istio 1.7, which full support, until ~March 2020 which to me seems like the real deadline.

Another thing to note is that we have pretty consistently supported 3 Kubernetes versions, as far as I know, since Istio 1.0, so there have been no changes here recently.
