### ISSUE TITLE
Install state CR not written to cluster

### ISSUE THREAD

**Issue by ostromart** [istio/istio#23187]
This is a regression, was previously written.

**Comment by esnible** [comment]
On success the CR state is written.  It fails if some of the components don't come up.

I will clear the milestone because the important functionality, having the CR on success, is working.

**Comment by ostromart** [comment]
Perhaps the idea here would be to write status as well @esnible? Otherwise if Istio is not successfully installed I'm not sure that writing the CR would be the correct action.

**Comment by esnible** [comment]
This was created in error ... I reported that the CR creation wasn't happening.  We can close it.

It would be desirable to write the status.  We have UX issues (e.g. https://github.com/istio/istio/issues/20377 ) about helping the user know when they may begin using Istio.
