### ISSUE TITLE
Installation page looks like a book

### ISSUE THREAD

**Issue by jwendell** [istio/istio#23181]
https://preliminary.istio.io/docs/setup/install/istioctl/

I found it to be too long, it could certainly be split into sub pages or point to other sections.

**Additional context**

**Comment by howardjohn** [comment]
related: https://github.com/istio/istio/issues/22950

Strongly agree!

**Comment by howardjohn** [comment]
Strongly agree - there is a few issues around this so I suggest we consolidate to simplify. Lets track in https://github.com/istio/istio/issues/22950
