### ISSUE TITLE
Jaeger UI instructions result in error from `manifest apply`

### ISSUE THREAD

**Issue by therealmitchconnors** [istio/istio#23197]
https://github.com/istio/istio.io/blob/master/content/en/docs/tasks/observability/distributed-tracing/jaeger/index.md#accessing-the-dashboard
recommends using `--set values.tracing.ingress.enabled=true` to enable ingress to the jaeger UI, but setting this value causes errors in `manifest apply`

```
Error: failed to apply manifests: validation errors (use --force to override):
unknown field "ingress" in v1alpha1.TracingConfig
```

**Comment by jacob-delgado** [comment]
cc @douglas-reid Is it fine for this to be in 1.6.1 due to code freeze of 1.6.0?

**Comment by douglas-reid** [comment]
i think this is a docs issue more than a release issue. i was able to complete this task w/o this step. I think we can remove it in the docs and keep the task correct.
