### ISSUE TITLE
Cannot login to Kiali dashboard.

### ISSUE THREAD

**Issue by ericvn** [istio/istio#23199]
Working through https://preliminary.istio.io/docs/setup/getting-started/ I get to `istioctl dashboard kiali` which brings up the dashboard in my browser (both Chrome and Safari). I see the _Log In_ button, but clicking it doesn't do anything.

The Documentation and Contribute links to open up in new tabs.

**Comment by jmazzitelli** [comment]
Details? What is your version of Istio and Kiali? What is the command you used to install? What do the Kiali pod logs say?

**Comment by ericvn** [comment]
1.6-alpha-2 install from dev testing day 1. I followed the steps as listed on the pages above. At this point I've moved on to many other tests so no logs at the moment.

**Comment by ericvn** [comment]
Working in #kiali, the Kiali CM that istioctl creates does not have an auth.strategy. It looks like it should be set:
```
./manifests/charts/istio-telemetry/kiali/templates/configmap.yaml: 
```
```     strategy: {{ .Values.kiali.dashboard.auth.strategy }} and the values.yaml has strategy: login # Can be anonymous, login, openshift, or ldap 
```

**Comment by jmazzitelli** [comment]
release-1.6 branch has the kiali values.yaml correctly setting this (this code hasn't changed between 1.5 and 1.6, so not sure why it isn't taking effect):

https://github.com/istio/istio/blob/release-1.6/manifests/charts/istio-telemetry/kiali/values.yaml#L42

**Comment by howardjohn** [comment]
https://github.com/istio/istio/blob/9550ee4a1084ded0df27e516930acf91a3bb8096/manifests/profiles/default.yaml#L599 is the breakage. Good thing we duplicate values.yaml in two places for extra confusion :slightly_smiling_face:

**Comment by treethought** [comment]
I'm 1.6.0--beta.0 and am still experiencing this issue.
