### ISSUE TITLE
istioctl.tar.gz binaries should have executable bits already (was Bumps in istioctl install)

### ISSUE THREAD

**Issue by erictune** [istio/istio#232]
I had to do a chmod +x after downloading the istioctl.tar.gz from https://github.com/istio/istio/releases/download/0.1.0/istioctl.tar.gz
It looks like the modes are not set in the archive.
I'm using a mac. 

Also, it might be nicer to have separate tars per platform, or put them in subdirs, so that all the binaries are named istioctl.

**Comment by ahmetb** [comment]
Related #214.

**Comment by ldemailly** [comment]
we're fixing the .tgz to have the x flag already
(my bad I didn't check they were when I updated the doc)

**Comment by ldemailly** [comment]
thx!
