### ISSUE TITLE
Cannot get Multi Cluster with the Bookinfo Application to work

### ISSUE THREAD

**Issue by jorenknieper** [istio/istio#23200]
Hi Istio 

I've a question. I'm following the guide on the istio website
https://istio.io/docs/setup/install/multicluster/gateways/
and 
https://istio.io/blog/2019/multicluster-version-routing/

So I'm trying to deploy the bookinfo application on 2 kubernetes clusters. GKE or on AKS. 

For GKE I'm using KubeDNS and AKS CoreDNS.

I'm following every step in the guide but if I login as user "jason" I get "service not availiable" on the ratings and reviews. 

I think it's a certification or routing problem. 

Is there something I'm not doing right or do I need to follow another guide? 

The .yaml files I use are the same as the file and the commands I'm running are exactly the same as the guide so I'm a bit stuck here. 

Hope you guys can help me out.

**Comment by jorenknieper** [comment]
I tried 1.4 and it worked in 1.4 but it's not working in 1.5. Any updates?

**Comment by elfgzp** [comment]
Same problem.

I can directly access through `reviews.default.global`.

```bash
curl -i http://reviews.default.global:9080/reviews/1
HTTP/1.1 200 OK
x-powered-by: Servlet/3.1
content-type: application/json
date: Thu, 07 May 2020 07:02:53 GMT
content-language: en-US
content-length: 375
x-envoy-upstream-service-time: 89
server: envoy

{"id": "1","reviews": [{  "reviewer": "Reviewer1",  "text": "An extremely entertaining play by Shakespeare. The slapstick humour is refreshing!", "rating": {"stars": 5, "color": "red"}},{  "reviewer": "Reviewer2",  "text": "Absolutely fun and entertaining. The play lacks thematic depth when compared to other plays by Shakespeare.", "rating": {"stars": 4, "color": "red"}}]}/ 
```

`istio-proxy logs`

```
[2020-05-07T06:46:38.833Z] "GET /reviews/1 HTTP/1.1" 200 - "-" "-" 0 375 73 72 "-" "curl/7.63.0" "b1f39777-3582-448d-ad08-18d759db4e9e" "reviews.default.global:9080" "34.97.254.15:15443" outbound|9080||reviews.default.global 10.28.3.14:50278 240.0.0.3:9080 10.28.3.14:41680 - default
```
---

But it's not accessible.

```bash
curl -v -i -H 'end-user:jason' http://reviews:9080/reviews/1
*   Trying 10.0.4.149...
* TCP_NODELAY set
* Connected to reviews (10.0.4.149) port 9080 (#0)
> GET /reviews/1 HTTP/1.1
> Host: reviews:9080
> User-Agent: curl/7.63.0
> Accept: */*
> end-user:jason
> 
< HTTP/1.1 503 Service Unavailable
HTTP/1.1 503 Service Unavailable
< content-length: 95
content-length: 95
< content-type: text/plain
content-type: text/plain
< date: Thu, 07 May 2020 07:05:47 GMT
date: Thu, 07 May 2020 07:05:47 GMT
< server: envoy
server: envoy

< 
* Connection #0 to host reviews left intact
upstream connect error or disconnect/reset before headers. reset reason: connection termination/ 
```

`istio-proxy logs`

```
[2020-05-07T06:46:38.274Z] "GET /reviews/1 HTTP/1.1" 503 UC "-" "-" 0 95 97 - "-" "curl/7.63.0" "33c1975a-65c7-4bcd-b968-a7fe18edba22" "reviews:9080" "34.97.254.15:15443" outbound|9080|v3|reviews.default.global 10.28.3.14:34688 10.0.4.149:9080 10.28.3.14:51224 - -
```

**Comment by ECuRyDIN** [comment]
@jorenknieper Were you able to figure it out? I am also facing the same issue..

**Comment by jorenknieper** [comment]
Hi ECuRyDIN,

Sadly no, I used it during my internship, I couldn't figure it out. I remember it worked on 1.4.8.

I'm sorry.
