### ISSUE TITLE
Overall should we use `istioctl install` or `istioctl manifest apply` in docs?

### ISSUE THREAD

**Issue by ericvn** [istio/istio#23206]
**Bug description**

Using the former will cause issues if we cherry-pick back to 1.5?

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by ericvn** [comment]
Question asked in Slack: https://istio.slack.com/archives/C50V5EATT/p1587958049126700

**Comment by shamsher31** [comment]
Closed with https://github.com/istio/istio.io/pull/7396
