### ISSUE TITLE
Publish non-root productpage image

### ISSUE THREAD

**Issue by sbueringer** [istio/istio#23219]
**Describe the feature request**

There was a change enabling productpage to be run as nonRoot: https://github.com/istio/istio/pull/16326

Apparently this version of productpage was never published to DockerHub. Would it be possible to publish this version? (so that I don't have to build it myself :))

Can be reproduced via:
```bash
docker run -it  istio/examples-bookinfo-productpage-v1:latest cat productpage.py
```

**Comment by howardjohn** [comment]
This is essentially the same as https://github.com/istio/istio/issues/23232,. lets track there. Thanks!
