### ISSUE TITLE
Use bazel to build Wasm plugins in istio proxy

### ISSUE THREAD

**Issue by bianpengyuan** [istio/istio#23215]
Currently Wasm modules in `istio/proxy` repo uses docker based build, this issue is to track the work to switch to bazel build.

This is part of the effort for https://github.com/istio/istio/issues/23168

@kyessenov @mandarjog @jplevyak @PiotrSikora fyi.

**Comment by lizan** [comment]
cc @Shikugawa has been working on authn migration and looked into this. I'm also working on some envoy-wasm to make wasm build easier / integrated.
