### ISSUE TITLE
Setting components doesnt work or is not well documented

### ISSUE THREAD

**Issue by jdomag** [istio/istio#23227]
**Bug description**
Can't set components via istioctl
Command: 
`./bin/istioctl manifest generate --set addonComponents.prometheus.enabled=false --set addonComponents.kiali.enabled=true --set addonComponents.tracing.enabled=true --set components.Galley.enabled=ture > generated-manifest.yaml`

Error: 
`Error: failed to generate tree from the set overlay, error: bad path=value: components.Galley.enabled=ture`

Got the same for IngressGateways. I couldn't find in the docs how to enable/disable those components and i took component names from: https://istio.io/docs/setup/install/istioctl/#identify-an-istio-component

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
Istioctl 1.5.2

**Comment by danquack** [comment]
@jdomag I noticed you have a typo: components.Galley.enabled=ture does changing components.Galley.enabled=true: `ture->true` fix your problem?
