### ISSUE TITLE
add excludeNamespace helm value to pilots namespace-controller

### ISSUE THREAD

**Issue by tobiasgiese** [istio/istio#23231]
**Describe the feature request**

We operate a managed kubernetes platform for several customers. So we're using [opa](https://github.com/open-policy-agent/opa) to i.e. restrict access to specific namespaces.
The pilot namespace-controller is deploying the istio-ca as a configmap `istio-ca-root-cert` to every namespace on startup.
Is it possible to add a similar key as `excludeNamespace` in `cni` to the istioctl helm chart?

**Comment by tobiasgiese** [comment]
@howardjohn could you please reopen this issue and add `lifecycle/staleproof `? Thanks

**Comment by howardjohn** [comment]
Lets track in https://github.com/istio/istio/issues/26679?
