### ISSUE TITLE
Istio analyzer - how to analyze against a namespace

### ISSUE THREAD

**Issue by linsun** [istio/istio#23234]
**Describe the feature request**

Either this feature already exists or I can't find them via help menu :)

I created a gw/vs/dr resource (mesh-expansion.yaml) and want to deploy it to Istio-system ns.  I want to validate if it is good.

I've tried a few commands:

istioctl analyze mesh-expansion.yaml

It didn't tell me it did analyze the Istio-system ns.  Then I found out -A can analyze all namespace.  However, the output didn't tell me if Istio-system is analyzed.  So I'm lost on if the yaml is good or not for that ns from the analyzer tool.  I think we need better msg to output a namespace if there is no issue.  Also, allow user to analyze a specific namespace if that is all they care about.

```$ istioctl analyze mesh-expansion.yaml -A
Warn [IST0102] (Namespace ibm-cert-store) The namespace is not enabled for Istio injection. Run 'kubectl label namespace ibm-cert-store istio-injection=enabled' to enable it, or 'kubectl label namespace ibm-cert-store istio-injection=disabled' to explicitly mark it as not needing injection
Warn [IST0102] (Namespace ibm-operators) The namespace is not enabled for Istio injection. Run 'kubectl label namespace ibm-operators istio-injection=enabled' to enable it, or 'kubectl label namespace ibm-operators istio-injection=disabled' to explicitly mark it as not needing injection
Warn [IST0102] (Namespace ibm-system) The namespace is not enabled for Istio injection. Run 'kubectl label namespace ibm-system istio-injection=enabled' to enable it, or 'kubectl label namespace ibm-system istio-injection=disabled' to explicitly mark it as not needing injection
Warn [IST0102] (Namespace kube-node-lease) The namespace is not enabled for Istio injection. Run 'kubectl label namespace kube-node-lease istio-injection=enabled' to enable it, or 'kubectl label namespace kube-node-lease istio-injection=disabled' to explicitly mark it as not needing injection
Warn [IST0102] (Namespace linsun) The namespace is not enabled for Istio injection. Run 'kubectl label namespace linsun istio-injection=enabled' to enable it, or 'kubectl label namespace linsun istio-injection=disabled' to explicitly mark it as not needing injection
Info [IST0121] (MeshPolicy default) The MeshPolicy resource is deprecated and will be removed in a future Istio release. Migrate to the PeerAuthentication resource.
Error: Analyzers found issues when analyzing all namespaces.
See https://istio.io/docs/reference/config/analysis for more information about causes and resolutions.
```
**Describe alternatives you've considered**
see steps above.  I ended up deploying it and retry the commands.

**Additional context**

**Comment by linsun** [comment]
@esnible @therealmitchconnors @jasonwzm The issue I mentioned on user experience slack yesterday, wanted to track it in GitHub.  Appreciate your looking into this.

**Comment by linsun** [comment]
Also, I think it is annoying to print warning for each namespace like this.  I think many are intentional not enabled for sidecar injector.  A summary for this is sufficient.

```
Warn [IST0102] (Namespace ibm-cert-store) The namespace is not enabled for Istio injection. Run 'kubectl label namespace ibm-cert-store istio-injection=enabled' to enable it, or 'kubectl label namespace ibm-cert-store istio-injection=disabled' to explicitly mark it as not needing injection
Warn [IST0102] (Namespace ibm-operators) The namespace is not enabled for Istio injection. Run 'kubectl label namespace ibm-operators istio-injection=enabled' to enable it, or 'kubectl label namespace ibm-operators istio-injection=disabled' to explicitly mark it as not needing injection
Warn [IST0102] (Namespace ibm-system) The namespace is not enabled for Istio injection. Run 'kubectl label namespace ibm-system istio-injection=enabled' to enable it, or 'kubectl label namespace ibm-system istio-injection=disabled' to explicitly mark it as not needing injection
Warn [IST0102] (Namespace kube-node-lease) The namespace is not enabled for Istio injection. Run 'kubectl label namespace kube-node-lease istio-injection=enabled' to enable it, or 'kubectl label namespace kube-node-lease istio-injection=disabled' to explicitly mark it as not needing injection
Warn [IST0102] (Namespace linsun) The namespace is not enabled for Istio injection. Run 'kubectl label namespace linsun istio-injection=enabled' to enable it, or 'kubectl label namespace linsun istio-injection=disabled' to explicitly mark it as not needing injection
```

**Comment by shamsher31** [comment]
Analyze on default namespace
```
$ ./out/linux_amd64/istioctl analyze
Info [IST0102] (Namespace default) The namespace is not enabled for Istio injection. Run 'kubectl label namespace default istio-injection=enabled' to enable it, or 'kubectl label namespace default istio-injection=disabled' to explicitly mark it as not needing injection.
```

If you want to analyze specific namespace use `-n`
```
$ ./out/linux_amd64/istioctl analyze -n redhat
Info [IST0102] (Namespace redhat) The namespace is not enabled for Istio injection. Run 'kubectl label namespace redhat istio-injection=enabled' to enable it, or 'kubectl label namespace redhat istio-injection=disabled' to explicitly mark it as not needing injection.
```
```
$ ./out/linux_amd64/istioctl analyze -n istio-system

✔ No validation issues found when analyzing namespace: istio-system.
```

If you want to run the analyzer on all the namespaces. Notice few improvements did via https://github.com/istio/istio/pull/27794 and https://github.com/istio/istio/pull/27846

```
$ ./out/linux_amd64/istioctl analyze -A
Info [IST0102] (Namespace default) The namespace is not enabled for Istio injection. Run 'kubectl label namespace default istio-injection=enabled' to enable it, or 'kubectl label namespace default istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace redhat) The namespace is not enabled for Istio injection. Run 'kubectl label namespace redhat istio-injection=enabled' to enable it, or 'kubectl label namespace redhat istio-injection=disabled' to explicitly mark it as not needing injection.
```
You can run validate on the file to check if it is having any issues.

> I created a gw/vs/dr resource (mesh-expansion.yaml) and want to deploy it to Istio-system ns. I want to validate if it is good.

```
istioctl validate -f mesh-expansion.yaml
```
`namespace` is provided as a global flag.
```
$ istioctl analyze -h 
Global Flags:
      --context string      The name of the kubeconfig context to use
  -c, --kubeconfig string   Kubernetes configuration file
  -n, --namespace string    Config namespace
```
https://github.com/istio/istio/blob/e403231eb242adfbebb2fac1736b37b2b645926d/istioctl/cmd/analyze.go#L129-L136

@linsun I hope this answers your question.

**Comment by linsun** [comment]
@shamsher31 Thanks!  Yep looks like -n is added to help menu.

One thing I'd ask for improvement is this:  can we change it to one msg and list all namespaces vs multiple messages?

> Also, I think it is annoying to print warning for each namespace like this. I think many are intentional not enabled for sidecar injector. A summary for this is sufficient.
> 
> ```
> Warn [IST0102] (Namespace ibm-cert-store) The namespace is not enabled for Istio injection. Run 'kubectl label namespace ibm-cert-store istio-injection=enabled' to enable it, or 'kubectl label namespace ibm-cert-store istio-injection=disabled' to explicitly mark it as not needing injection
> Warn [IST0102] (Namespace ibm-operators) The namespace is not enabled for Istio injection. Run 'kubectl label namespace ibm-operators istio-injection=enabled' to enable it, or 'kubectl label namespace ibm-operators istio-injection=disabled' to explicitly mark it as not needing injection
> Warn [IST0102] (Namespace ibm-system) The namespace is not enabled for Istio injection. Run 'kubectl label namespace ibm-system istio-injection=enabled' to enable it, or 'kubectl label namespace ibm-system istio-injection=disabled' to explicitly mark it as not needing injection
> Warn [IST0102] (Namespace kube-node-lease) The namespace is not enabled for Istio injection. Run 'kubectl label namespace kube-node-lease istio-injection=enabled' to enable it, or 'kubectl label namespace kube-node-lease istio-injection=disabled' to explicitly mark it as not needing injection
> Warn [IST0102] (Namespace linsun) The namespace is not enabled for Istio injection. Run 'kubectl label namespace linsun istio-injection=enabled' to enable it, or 'kubectl label namespace linsun istio-injection=disabled' to explicitly mark it as not needing injection
> ```

**Comment by linsun** [comment]
BTW, warn is changed to info which I like

```
Info [IST0102] (Namespace ibm-cert-store) The namespace is not enabled for Istio injection. Run 'kubectl label namespace ibm-cert-store istio-injection=enabled' to enable it, or 'kubectl label namespace ibm-cert-store istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace ibm-operators) The namespace is not enabled for Istio injection. Run 'kubectl label namespace ibm-operators istio-injection=enabled' to enable it, or 'kubectl label namespace ibm-operators istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace ibm-system) The namespace is not enabled for Istio injection. Run 'kubectl label namespace ibm-system istio-injection=enabled' to enable it, or 'kubectl label namespace ibm-system istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace istio-system) The namespace is not enabled for Istio injection. Run 'kubectl label namespace istio-system istio-injection=enabled' to enable it, or 'kubectl label namespace istio-system istio-injection=disabled' to explicitly mark it as not needing injection.
Info [IST0102] (Namespace istio2) The namespace is not enabled for Istio injection. Run 'kubectl label namespace istio2 istio-injection=enabled' to enable it, or 'kubectl label namespace istio2 istio-injection=disabled' to explicitly mark it as not needing injection.
```

**Comment by shamsher31** [comment]
> One thing I'd ask for improvement is this: can we change it to one msg and list all namespaces vs multiple messages?

AFAIK analyzer generates these messages dynamically so it's hard to combine them into one message.
https://github.com/istio/istio/blob/9a07550c196fc315c1b3c9406fc39d830a03a6e1/galley/pkg/config/analysis/msg/messages.yaml#L33-L42

**Comment by linsun** [comment]
Could we update the message to be one or more namespaces are not enabled for istio injection?
