### ISSUE TITLE
Add support for custom SECRET_TTL for istio-proxy using annotation

### ISSUE THREAD

**Issue by dahutu** [istio/istio#23246]
**Describe the feature request**
Different workloads within an Istio cluster may have different security requirements and warrants different cert validity length, or TTL. Currently there is no known way to customize SECRET_TTL for individual workloads. SECRET_TTL can be set globally during installation process by the following option:
`--set meshConfig.defaultConfig.proxyMetadata.SECRET_TTL=<duration>`
However currently there is no way to set it for a specific workload during manual sidecar injection.  It would be great I can set a specific value for SECRET_TTL during annotation for a deployment.

**Describe alternatives you've considered**
Currently I can use the following workaround:

- `istioctl kube-inject -f samples/sleep/sleep.yaml > sleep-injected.yaml`
- edit sleep-inject.yaml and add SECRET_TTL environment variable under `env:` with custom value, e.g., `SECRET_TTL = 10m`
- `kubectl apply -f sleep-injected.yaml`

This works but is manual and error prone.

**Additional context**

**Comment by howardjohn** [comment]
There is now a way to override anything in https://istio.io/docs/reference/config/istio.mesh.v1alpha1/#ProxyConfig with the istio.io/proxyConfig annotation starting in istio 1.6

**Comment by JimmyCYJ** [comment]
cc @williamaronli

**Comment by howardjohn** [comment]
you can just do

```
proxy.istio.io/config: |
  proxyMetadata:
    SECRET_TTL: 10m
```

and this will work in 1.6

**Comment by satishmane** [comment]
@howardjohn 
How big duration can assigned to SECRET_TTL? to avoid certificate expiry.

**Comment by thedebugger** [comment]
hi @howardjohn do you know how to configure this in the recent version of istio? I can't find any attribute in mesh config or annotation
