### ISSUE TITLE
Replicated control plane issues with docs

### ISSUE THREAD

**Issue by ericvn** [istio/istio#23255]
**Bug description**
Step says: `istioctl manifest apply \
    -f install/kubernetes/operator/examples/multicluster/values-istio-multicluster-gateways.yaml`

The install directory no longer exists. Replaced with manifests/examples/multicluster/values-istio-multicluster-gateways.yaml, and fails like #23253:
```
istioctl manifest apply \                                                                                                                                         
    -f manifests/examples/multicluster/values-istio-multicluster-gateways.yaml
Error: failed to apply manifests: validation errors (use --force to override):
unknown field "security" in v1alpha1.Values
```

**Comment by linsun** [comment]
this should be fixed by https://github.com/istio/istio/pull/23304

**Comment by linsun** [comment]
please reopen if the issue still exists.
