### ISSUE TITLE
MultiCluster issues with docs

### ISSUE THREAD

**Issue by ericvn** [istio/istio#23253]
**Bug description**

```
 istioctl --context=${MAIN_CLUSTER_CTX} manifest apply -f istio-main-cluster.yaml                                                                                  
Error: failed to apply manifests: validation errors (use --force to override):
unknown field "security" in v1alpha1.Values
```

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by linsun** [comment]
should be also fixed with https://github.com/istio/istio/pull/23304, if not, please reopen.
