### ISSUE TITLE
Move fault injection filter before Mixer

### ISSUE THREAD

**Issue by qiwzhang** [istio/istio#2327]
With this PR: https://github.com/istio/proxy/pull/771

Proxy can call Mixer report for any requests rejected by other filters regardless before or after Mixer filter.

It is better to move fault injection filter before Mixer Check so quota is not wasted if quota is enforced.

**Comment by kyessenov** [comment]
Should Mixer allow requests rejected by the fault filter?
Conversely, should the fault filter reject requests allowed by Mixer?
What about any other extensions filter like external auth one?
