### ISSUE TITLE
Network tcp stats filter cannot use semantic name

### ISSUE THREAD

**Issue by bianpengyuan** [istio/istio#23277]
After proxy sha update to envoy 1.14.1, network filter cannot use semantic name: https://github.com/istio/istio/pull/23265/files#diff-1e82666f6c50fc89b17fee45dfe8d289L1638. Specifically envoy complains: `Didn't find a registered implementation for name: 'istio.stats'`.

Not sure if this is an upstream envoy bug or we missed a related PR in istio/envoy 1.14.1.

**Comment by howardjohn** [comment]
Even before your Sha update merged I saw this error ij master sometimes. unfortunately I didn't record the exact images - very likely the install and proxy images where mismatched though.

I don't 100% understand the timeline of changes here but we should make sure that this never occurs in the 1.5 to 1.6 upgrade
