### ISSUE TITLE
Error: unknown command "manifest" for "istioctl"

### ISSUE THREAD

**Issue by fffffreedom** [istio/istio#23271]
**Bug description**

$ istioctl manifest apply
Error: unknown command "manifest" for "istioctl"

[ ] Configuration Infrastructure
[* ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

[ ] Multi Cluster
[* ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

$ istioctl manifest apply --set profile=demo
Detected that your cluster does not support third party JWT authentication. Falling back to less secure first party JWT
- Applying manifest for component Base...
✔ Finished applying manifest for component Base.
- Applying manifest for component Pilot...
✔ Finished applying manifest for component Pilot.
Waiting for resources to become ready...
- Applying manifest for component EgressGateways...
- Applying manifest for component IngressGateways...
- Applying manifest for component AddonComponents...
✔ Finished applying manifest for component EgressGateways.
✔ Finished applying manifest for component IngressGateways.
✔ Finished applying manifest for component AddonComponents.

✔ Installation complete

**Steps to reproduce the bug**
run command:
$ istioctl manifest apply --set profile=demo

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**
minikube

**Environment where bug was observed (cloud vendor, OS, etc)**
macos

**Comment by howardjohn** [comment]
I suspect you have an old version, can you run `istioctl version`?

**Comment by fffffreedom** [comment]
fffffreedom:minikube jonny$ istioctl version
Version: 1.0.2
GitRevision: d639408fded355fb906ef2a1f9e8ffddc24c3d64
User: root@66ce69d4a51e
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean

**Comment by howardjohn** [comment]
please update, that is almost 2 years old

**Comment by fffffreedom** [comment]
thks
