### ISSUE TITLE
Istio 1.5.1 is installed on the Alibaba server istio init. Initialization error

### ISSUE THREAD

**Issue by shinynz** [istio/istio#23288]
## Bug description

- k8s：v1.16.6-aliyun.1
- istio: v1.5.1

Istio 1.5.1 is installed on the Alibaba server istio init. Initialization error
use namespace injection sidecar

## Environment

```
------------
ENVOY_PORT=
INBOUND_CAPTURE_PORT=
ISTIO_INBOUND_INTERCEPTION_MODE=
ISTIO_INBOUND_TPROXY_MARK=
ISTIO_INBOUND_TPROXY_ROUTE_TABLE=
ISTIO_INBOUND_PORTS=
ISTIO_LOCAL_EXCLUDE_PORTS=
ISTIO_SERVICE_CIDR=
ISTIO_SERVICE_EXCLUDE_CIDR=
```

## Variables

```
PROXY_PORT=15001
PROXY_INBOUND_CAPTURE_PORT=15006
PROXY_UID=1337
PROXY_GID=1337
INBOUND_INTERCEPTION_MODE=REDIRECT
INBOUND_TPROXY_MARK=1337
INBOUND_TPROXY_ROUTE_TABLE=133
INBOUND_PORTS_INCLUDE=*
INBOUND_PORTS_EXCLUDE=15090,15020
OUTBOUND_IP_RANGES_INCLUDE=*
OUTBOUND_IP_RANGES_EXCLUDE=
OUTBOUND_PORTS_EXCLUDE=
KUBEVIRT_INTERFACES=
ENABLE_INBOUND_IPV6=false
```

Writing following contents to rules file:  `/tmp/iptables-rules-1587896609463992300.txt031496377`

```
* nat
-N ISTIO_REDIRECT
-N ISTIO_IN_REDIRECT
-N ISTIO_INBOUND
-N ISTIO_OUTPUT
-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-port 15001
-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-port 15006
-A PREROUTING -p tcp -j ISTIO_INBOUND
-A ISTIO_INBOUND -p tcp --dport 22 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15090 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15020 -j RETURN
-A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT
-A OUTPUT -p tcp -j ISTIO_OUTPUT
-A ISTIO_OUTPUT -o lo -s 127.0.0.6/32 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --gid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
-A ISTIO_OUTPUT -j ISTIO_REDIRECT
COMMIT

iptables-restore --noflush /tmp/iptables-rules-1587896609463992300.txt031496377
iptables-restore: line 2 failed
iptables-save 
# Generated by iptables-save v1.6.1 on Sun Apr 26 10:23:29 2020
*mangle
:PREROUTING ACCEPT [109941:361621593]
:INPUT ACCEPT [109941:361621593]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [103494:575994556]
:POSTROUTING ACCEPT [103494:575994556]
COMMIT
# Completed on Sun Apr 26 10:23:29 2020
# Generated by iptables-save v1.6.1 on Sun Apr 26 10:23:29 2020
*nat
:PREROUTING ACCEPT [3806:228360]
:INPUT ACCEPT [4032:241920]
:OUTPUT ACCEPT [797:56682]
:POSTROUTING ACCEPT [1119:76002]
:ISTIO_INBOUND - [0:0]
:ISTIO_IN_REDIRECT - [0:0]
:ISTIO_OUTPUT - [0:0]
:ISTIO_REDIRECT - [0:0]
-A PREROUTING -p tcp -j ISTIO_INBOUND
-A OUTPUT -p tcp -j ISTIO_OUTPUT
-A ISTIO_INBOUND -p tcp -m tcp --dport 22 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15090 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15020 -j RETURN
-A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT
-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006
-A ISTIO_OUTPUT -s 127.0.0.6/32 -o lo -j RETURN
-A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -m owner --gid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
-A ISTIO_OUTPUT -j ISTIO_REDIRECT
-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001
COMMIT
# Completed on Sun Apr 26 10:23:29 2020
# Generated by iptables-save v1.6.1 on Sun Apr 26 10:23:29 2020
*filter
:INPUT ACCEPT [109941:361621593]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [103494:575994556]
COMMIT
# Completed on Sun Apr 26 10:23:29 2020
panic: exit status 1

goroutine 1 [running]:
istio.io/istio/tools/istio-iptables/pkg/dependencies.(*RealDependencies).RunOrFail(0xd819c0, 0x9739b8, 0x10, 0xc00000cc00, 0x2, 0x2)
	istio.io/istio@/tools/istio-iptables/pkg/dependencies/implementation.go:44 +0x96
istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).executeIptablesRestoreCommand(0xc0000f5d30, 0x7f497dbc5001, 0x0, 0x0)
	istio.io/istio@/tools/istio-iptables/pkg/cmd/run.go:474 +0x3aa
istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).executeCommands(0xc0000f5d30)
	istio.io/istio@/tools/istio-iptables/pkg/cmd/run.go:481 +0x45
istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).run(0xc0000f5d30)
	istio.io/istio@/tools/istio-iptables/pkg/cmd/run.go:428 +0x24e2
istio.io/istio/tools/istio-iptables/pkg/cmd.glob..func1(0xd5c740, 0xc0000d4700, 0x0, 0x10)
	istio.io/istio@/tools/istio-iptables/pkg/cmd/root.go:56 +0x14e
github.com/spf13/cobra.(*Command).execute(0xd5c740, 0xc00001e130, 0x10, 0x11, 0xd5c740, 0xc00001e130)
	github.com/spf13/cobra@v0.0.5/command.go:830 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0xd5c740, 0x40574f, 0xc000082058, 0x0)
	github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v0.0.5/command.go:864
istio.io/istio/tools/istio-iptables/pkg/cmd.Execute()
	istio.io/istio@/tools/istio-iptables/pkg/cmd/root.go:284 +0x2d
main.main()
	istio.io/istio@/tools/istio-iptables/main.go:22 +0x20
```

**Comment by lambdai** [comment]
@shinynz 
The error indicates an error happens when istio-init create iptables chain at line `-N ISTIO_REDIRECT`
The latter iptables-save does dump the nat table has ISTIO_REDIRECT 

It's likely that istio-init created the iptables **prior to this attempt** but the pod failed somehow at initialization. Then the istio-init reruns and failed. Do you have the history of istio-init logs owned by the same pod but prior to this run?

BTW: to mitigate this pod failure, you can delete the pod and see if a new pod is recovered.

**Comment by shinynz** [comment]
@lambdai After deleting a pod, it will automatically regenerate into a new pod, but istio-init will still report an error

**Comment by lambdai** [comment]
Sorry to hear that. 
I cannot explain why the istio-expected iptables looks legit before "iptables-restore".

You may need to figure out what happened before istio-init pre init container executes.

I would guess 
1. there was a failure after istio-init, and all pre-init container are executed more than once. Istio-init reports error at the second execution
2. Or, there are somehow istio-init -ish pre-init container, the first one succeed and the second one failed.

If you have the pod spec we can move on.

**Comment by shinynz** [comment]
@lambdai  

{
  "kind": "Pod",
  "apiVersion": "v1",
  "metadata": {
    "name": "reviews-v3-67b4988599-4sgql",
    "generateName": "reviews-v3-67b4988599-",
    "namespace": "default",
    "selfLink": "/api/v1/namespaces/default/pods/reviews-v3-67b4988599-4sgql",
    "uid": "4b56c5e4-5b86-442c-b247-f83f23d84dad",
    "resourceVersion": "214884492",
    "creationTimestamp": "2020-04-28T02:33:38Z",
    "labels": {
      "app": "reviews",
      "pod-template-hash": "67b4988599",
      "security.istio.io/tlsMode": "istio",
      "service.istio.io/canonical-name": "reviews",
      "service.istio.io/canonical-revision": "v3",
      "version": "v3"
    },
    "annotations": {
      "kubernetes.io/psp": "ack.privileged",
      "sidecar.istio.io/status": "{\"version\":\"fca84600f9d5ec316cf1cf577da902f38bac258ab0fd595ee208ec0203dc0c6d\",\"initContainers\":[\"istio-init\"],\"containers\":[\"istio-proxy\"],\"volumes\":[\"istio-envoy\",\"podinfo\",\"istiod-ca-cert\"],\"imagePullSecrets\":null}"
    },
    "ownerReferences": [
      {
        "apiVersion": "apps/v1",
        "kind": "ReplicaSet",
        "name": "reviews-v3-67b4988599",
        "uid": "b0f8e6a3-b679-4a8a-9e71-ced7cf5cc1a5",
        "controller": true,
        "blockOwnerDeletion": true
      }
    ]
  },
  "spec": {
    "volumes": [
      {
        "name": "wlp-output",
        "emptyDir": {}
      },
      {
        "name": "tmp",
        "emptyDir": {}
      },
      {
        "name": "bookinfo-reviews-token-s7mv4",
        "secret": {
          "secretName": "bookinfo-reviews-token-s7mv4",
          "defaultMode": 420
        }
      },
      {
        "name": "istio-envoy",
        "emptyDir": {
          "medium": "Memory"
        }
      },
      {
        "name": "podinfo",
        "downwardAPI": {
          "items": [
            {
              "path": "labels",
              "fieldRef": {
                "apiVersion": "v1",
                "fieldPath": "metadata.labels"
              }
            },
            {
              "path": "annotations",
              "fieldRef": {
                "apiVersion": "v1",
                "fieldPath": "metadata.annotations"
              }
            }
          ],
          "defaultMode": 420
        }
      },
      {
        "name": "istiod-ca-cert",
        "configMap": {
          "name": "istio-ca-root-cert",
          "defaultMode": 420
        }
      }
    ],
    "initContainers": [
      {
        "name": "istio-init",
        "image": "registry.cn-hangzhou.aliyuncs.com/shinyn/proxyv2:1.5.2",
        "command": [
          "istio-iptables",
          "-p",
          "15001",
          "-z",
          "15006",
          "-u",
          "1337",
          "-m",
          "REDIRECT",
          "-i",
          "*",
          "-x",
          "",
          "-b",
          "*",
          "-d",
          "15090,15020"
        ],
        "resources": {
          "limits": {
            "cpu": "100m",
            "memory": "50Mi"
          },
          "requests": {
            "cpu": "10m",
            "memory": "10Mi"
          }
        },
        "volumeMounts": [
          {
            "name": "bookinfo-reviews-token-s7mv4",
            "readOnly": true,
            "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount"
          }
        ],
        "terminationMessagePath": "/dev/termination-log",
        "terminationMessagePolicy": "File",
        "imagePullPolicy": "IfNotPresent",
        "securityContext": {
          "capabilities": {
            "add": [
              "NET_ADMIN",
              "NET_RAW"
            ],
            "drop": [
              "ALL"
            ]
          },
          "privileged": false,
          "runAsUser": 0,
          "runAsGroup": 0,
          "runAsNonRoot": false,
          "readOnlyRootFilesystem": false,
          "allowPrivilegeEscalation": false
        }
      }
    ],
    "containers": [
      {
        "name": "reviews",
        "image": "docker.io/istio/examples-bookinfo-reviews-v3:1.15.0",
        "ports": [
          {
            "containerPort": 9080,
            "protocol": "TCP"
          }
        ],
        "env": [
          {
            "name": "LOG_DIR",
            "value": "/tmp/logs"
          }
        ],
        "resources": {},
        "volumeMounts": [
          {
            "name": "tmp",
            "mountPath": "/tmp"
          },
          {
            "name": "wlp-output",
            "mountPath": "/opt/ibm/wlp/output"
          },
          {
            "name": "bookinfo-reviews-token-s7mv4",
            "readOnly": true,
            "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount"
          }
        ],
        "terminationMessagePath": "/dev/termination-log",
        "terminationMessagePolicy": "File",
        "imagePullPolicy": "IfNotPresent"
      },
      {
        "name": "istio-proxy",
        "image": "registry.cn-hangzhou.aliyuncs.com/shinyn/proxyv2:1.5.2",
        "args": [
          "proxy",
          "sidecar",
          "--domain",
          "$(POD_NAMESPACE).svc.cluster.local",
          "--configPath",
          "/etc/istio/proxy",
          "--binaryPath",
          "/usr/local/bin/envoy",
          "--serviceCluster",
          "reviews.$(POD_NAMESPACE)",
          "--drainDuration",
          "45s",
          "--parentShutdownDuration",
          "1m0s",
          "--discoveryAddress",
          "istiod.istio-system.svc:15012",
          "--zipkinAddress",
          "zipkin.istio-system:9411",
          "--proxyLogLevel=warning",
          "--proxyComponentLogLevel=misc:error",
          "--connectTimeout",
          "10s",
          "--proxyAdminPort",
          "15000",
          "--concurrency",
          "2",
          "--controlPlaneAuthPolicy",
          "NONE",
          "--dnsRefreshRate",
          "300s",
          "--statusPort",
          "15020",
          "--trust-domain=cluster.local",
          "--controlPlaneBootstrap=false"
        ],
        "ports": [
          {
            "name": "http-envoy-prom",
            "containerPort": 15090,
            "protocol": "TCP"
          }
        ],
        "env": [
          {
            "name": "JWT_POLICY",
            "value": "first-party-jwt"
          },
          {
            "name": "PILOT_CERT_PROVIDER",
            "value": "istiod"
          },
          {
            "name": "CA_ADDR",
            "value": "istio-pilot.istio-system.svc:15012"
          },
          {
            "name": "POD_NAME",
            "valueFrom": {
              "fieldRef": {
                "apiVersion": "v1",
                "fieldPath": "metadata.name"
              }
            }
          },
          {
            "name": "POD_NAMESPACE",
            "valueFrom": {
              "fieldRef": {
                "apiVersion": "v1",
                "fieldPath": "metadata.namespace"
              }
            }
          },
          {
            "name": "INSTANCE_IP",
            "valueFrom": {
              "fieldRef": {
                "apiVersion": "v1",
                "fieldPath": "status.podIP"
              }
            }
          },
          {
            "name": "SERVICE_ACCOUNT",
            "valueFrom": {
              "fieldRef": {
                "apiVersion": "v1",
                "fieldPath": "spec.serviceAccountName"
              }
            }
          },
          {
            "name": "HOST_IP",
            "valueFrom": {
              "fieldRef": {
                "apiVersion": "v1",
                "fieldPath": "status.hostIP"
              }
            }
          },
          {
            "name": "ISTIO_META_POD_PORTS",
            "value": "[\n    {\"containerPort\":9080,\"protocol\":\"TCP\"}\n]"
          },
          {
            "name": "ISTIO_META_APP_CONTAINERS",
            "value": "[\n    reviews\n]"
          },
          {
            "name": "ISTIO_META_CLUSTER_ID",
            "value": "Kubernetes"
          },
          {
            "name": "ISTIO_META_POD_NAME",
            "valueFrom": {
              "fieldRef": {
                "apiVersion": "v1",
                "fieldPath": "metadata.name"
              }
            }
          },
          {
            "name": "ISTIO_META_CONFIG_NAMESPACE",
            "valueFrom": {
              "fieldRef": {
                "apiVersion": "v1",
                "fieldPath": "metadata.namespace"
              }
            }
          },
          {
            "name": "ISTIO_META_INTERCEPTION_MODE",
            "value": "REDIRECT"
          },
          {
            "name": "ISTIO_METAJSON_ANNOTATIONS",
            "value": "{\"kubernetes.io/psp\":\"ack.privileged\"}\n"
          },
          {
            "name": "ISTIO_META_WORKLOAD_NAME",
            "value": "reviews-v3"
          },
          {
            "name": "ISTIO_META_OWNER",
            "value": "kubernetes://apis/apps/v1/namespaces/default/deployments/reviews-v3"
          },
          {
            "name": "ISTIO_META_MESH_ID",
            "value": "cluster.local"
          },
          {
            "name": "ISTIO_KUBE_APP_PROBERS",
            "value": "{}"
          }
        ],
        "resources": {
          "limits": {
            "cpu": "2",
            "memory": "1Gi"
          },
          "requests": {
            "cpu": "10m",
            "memory": "40Mi"
          }
        },
        "volumeMounts": [
          {
            "name": "istiod-ca-cert",
            "mountPath": "/var/run/secrets/istio"
          },
          {
            "name": "istio-envoy",
            "mountPath": "/etc/istio/proxy"
          },
          {
            "name": "podinfo",
            "mountPath": "/etc/istio/pod"
          },
          {
            "name": "bookinfo-reviews-token-s7mv4",
            "readOnly": true,
            "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount"
          }
        ],
        "readinessProbe": {
          "httpGet": {
            "path": "/healthz/ready",
            "port": 15020,
            "scheme": "HTTP"
          },
          "initialDelaySeconds": 1,
          "timeoutSeconds": 1,
          "periodSeconds": 2,
          "successThreshold": 1,
          "failureThreshold": 30
        },
        "terminationMessagePath": "/dev/termination-log",
        "terminationMessagePolicy": "File",
        "imagePullPolicy": "IfNotPresent",
        "securityContext": {
          "capabilities": {
            "drop": [
              "ALL"
            ]
          },
          "privileged": false,
          "runAsUser": 1337,
          "runAsGroup": 1337,
          "runAsNonRoot": true,
          "readOnlyRootFilesystem": true,
          "allowPrivilegeEscalation": false
        }
      }
    ],
    "restartPolicy": "Always",
    "terminationGracePeriodSeconds": 30,
    "dnsPolicy": "ClusterFirst",
    "serviceAccountName": "bookinfo-reviews",
    "serviceAccount": "bookinfo-reviews",
    "nodeName": "cn-beijing.i-2ze58ac0kt41vuzgkh87",
    "securityContext": {
      "fsGroup": 1337
    },
    "schedulerName": "default-scheduler",
    "tolerations": [
      {
        "key": "node.kubernetes.io/not-ready",
        "operator": "Exists",
        "effect": "NoExecute",
        "tolerationSeconds": 300
      },
      {
        "key": "node.kubernetes.io/unreachable",
        "operator": "Exists",
        "effect": "NoExecute",
        "tolerationSeconds": 300
      }
    ],
    "priority": 0,
    "enableServiceLinks": true
  },
  "status": {
    "phase": "Running",
    "conditions": [
      {
        "type": "Initialized",
        "status": "False",
        "lastProbeTime": null,
        "lastTransitionTime": "2020-04-28T02:34:34Z",
        "reason": "ContainersNotInitialized",
        "message": "containers with incomplete status: [istio-init]"
      },
      {
        "type": "Ready",
        "status": "True",
        "lastProbeTime": null,
        "lastTransitionTime": "2020-04-28T02:34:34Z"
      },
      {
        "type": "ContainersReady",
        "status": "True",
        "lastProbeTime": null,
        "lastTransitionTime": "2020-04-28T02:34:34Z"
      },
      {
        "type": "PodScheduled",
        "status": "True",
        "lastProbeTime": null,
        "lastTransitionTime": "2020-04-28T02:33:38Z"
      }
    ],
    "hostIP": "192.168.7.250",
    "podIP": "172.24.3.32",
    "podIPs": [
      {
        "ip": "172.24.3.32"
      }
    ],
    "startTime": "2020-04-28T02:33:39Z",
    "initContainerStatuses": [
      {
        "name": "istio-init",
        "state": {
          "waiting": {
            "reason": "CrashLoopBackOff",
            "message": "back-off 1m20s restarting failed container=istio-init pod=reviews-v3-67b4988599-4sgql_default(4b56c5e4-5b86-442c-b247-f83f23d84dad)"
          }
        },
        "lastState": {
          "terminated": {
            "exitCode": 2,
            "reason": "Error",
            "startedAt": "2020-04-28T02:38:11Z",
            "finishedAt": "2020-04-28T02:38:12Z",
            "containerID": "docker://6f2875f458f3602801a383d530774e1916bd8b491751d801f0502ab6b47bf636"
          }
        },
        "ready": false,
        "restartCount": 0,
        "image": "registry.cn-hangzhou.aliyuncs.com/shinyn/proxyv2:1.5.2",
        "imageID": "docker-pullable://registry.cn-hangzhou.aliyuncs.com/shinyn/proxyv2@sha256:b569b3226624b63ca007f3252162390545643433770c79a9aadb1406687d767a",
        "containerID": "docker://6f2875f458f3602801a383d530774e1916bd8b491751d801f0502ab6b47bf636"
      }
    ],
    "containerStatuses": [
      {
        "name": "istio-proxy",
        "state": {
          "running": {
            "startedAt": "2020-04-28T02:34:32Z"
          }
        },
        "lastState": {},
        "ready": true,
        "restartCount": 0,
        "image": "registry.cn-hangzhou.aliyuncs.com/shinyn/proxyv2:1.5.2",
        "imageID": "docker-pullable://registry.cn-hangzhou.aliyuncs.com/shinyn/proxyv2@sha256:b569b3226624b63ca007f3252162390545643433770c79a9aadb1406687d767a",
        "containerID": "docker://96067bcafe1b5261544b8c2f634a0d0f73eb8d691300e279da24369a8b459661",
        "started": true
      },
      {
        "name": "reviews",
        "state": {
          "running": {
            "startedAt": "2020-04-28T02:34:32Z"
          }
        },
        "lastState": {},
        "ready": true,
        "restartCount": 0,
        "image": "istio/examples-bookinfo-reviews-v3:1.15.0",
        "imageID": "docker-pullable://istio/examples-bookinfo-reviews-v3@sha256:e454cab754cf9234e8b41d7c5e30f53a4c125d7d9443cb3ef2b2eb1c4bd1ec14",
        "containerID": "docker://b8210c53efc2122d08a81bd671a5d0152669f13fa29ee064a419837bd2e79702",
        "started": true
      }
    ],
    "qosClass": "Burstable"
  }
}

**Comment by lambdai** [comment]
istio-init looks good. 
Could you run a iptables-restore from in istio-init container to verify the privileges are good?

**Comment by shinynz** [comment]
@lambdai 
[root@iz2zed870nkxaeivsmd6t8z mnt]# kubectl exec reviews-v3-67b4988599-4sgql -c  istio-init  iptables-restore -n default
error: unable to upgrade connection: container not found ("istio-init")

**Comment by lambdai** [comment]
The istio-init exited immediately. You don't have a large window to run kubectl exec.
I think you have to 
1. disable auto injector in this namepace,
2.inject the deployment by yourself, substitute the entrypoint by bash 
3. run kubectl exec. You may also want run iptables-save before istio-iptables command runs.

BTW: I believe you have other pod beside review pod. Are those istio-init working well?

**Comment by abhide** [comment]
`istio-iptables` will print the contents of the rules file that is passed to `iptables-restore`. k
You will be able to get the contents on the rules file.

**Comment by shinynz** [comment]
All my services, istio-init, are started incorrectly
![image](https://user-images.githubusercontent.com/15795798/80450899-1e316300-8955-11ea-9c0e-59d0720725af.png)

**Comment by lambdai** [comment]
@shinynz As @abhide described, below is what should want to save to file and run iptables-restore manually.
Since the failure is consistent on all pods, it's probably a platform compatibility issue. 
@seflerZ Could you route to a person in alibaba cloud? The failure is that iptables-restore cannot set up the iptables correctly. My guess is the chain ISTIO_REDIRECT is already added to the iptables but I don't know why.

```
*nat
-N ISTIO_REDIRECT
-N ISTIO_IN_REDIRECT
-N ISTIO_INBOUND
-N ISTIO_OUTPUT
-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-port 15001
-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-port 15006
-A PREROUTING -p tcp -j ISTIO_INBOUND
-A ISTIO_INBOUND -p tcp --dport 22 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15090 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15020 -j RETURN
-A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT
-A OUTPUT -p tcp -j ISTIO_OUTPUT
-A ISTIO_OUTPUT -o lo -s 127.0.0.6/32 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --gid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
-A ISTIO_OUTPUT -j ISTIO_REDIRECT
COMMIT
```
