### ISSUE TITLE
Consider Istio Mesh Expansion on Azure's AKS

### ISSUE THREAD

**Issue by AceHack** [istio/istio#2328]
Please consider Istio Mesh Expansion on Azure's AKS managed kubernetes.

**Comment by ldemailly** [comment]
Can you elaborate on what you mean ?
Mesh expansion should work anywhere (within the current network/ilb constraints) - and contributions to the demo scripts for other environments are welcome

**Comment by AceHack** [comment]
The first step says
Setup Internal Load Balancers (ILBs) for Kube DNS, Pilot, Mixer and CA. This step is specific to each cloud provider, so you may need to edit annotations.

In the script provided it does not have azure specific setting.  Also AKS has the management nodes fully managed by Microsoft.

**Comment by ldemailly** [comment]
Yes, it would be great if someone from Azure or with good knowledge of AKS could contribute how to make it work similarly on AKS

**Comment by ahaeber** [comment]
For Azure AKS the k8s annotation to be added for ILB is:
`service.beta.kubernetes.io/azure-load-balancer-internal: "true"`

**Comment by costinm** [comment]
Not blocking for 1.0.
