### ISSUE TITLE
Minimal list of components necessary for logging to remote ELK

### ISSUE THREAD

**Issue by jiribaloun** [istio/istio#23287]
**Bug description**
I'm trying to install Istio with default profile. 
However, it doesn't work as expected.

Is there any detailed minimal list of components necessary to install for sending logs to remote ELK Stack?

**Expected behavior**
List of  "--set" following "istioctl manifest apply" to bring successful installation sending logs.

**Steps to reproduce the bug**
istioctl manifest apply <--set profile=default>

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.5.2

**How was Istio installed?**
istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**
CentOS 7.*
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:23:26Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:15:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by howardjohn** [comment]
Please take a look at https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-service-mesh-istio.html. If that doesn't solve your problem, can you give some more details on the issue? You mentioned it doesn't work but not what happens

**Comment by jiribaloun** [comment]
Thank you for taking a care of my case.

Procedure is simple.
I've followed guide on: https://istio.io/docs/setup/getting-started/ and installed istio with following command:
./istioctl manifest apply --set profile=default --set components.telemetry.enabled=true --set values.global.controlPlaneSecurityEnabled=true --set values.security.enabled=true --set addonComponents.prometheus.enabled=false

Then I've installed bookinfo app describe on "getting started page". Only difference is, that I've used different namespace named "bookinfo" (with istio-injection=enabled label).
Application works fine as expected:
 curl -s http://172.28.1.11:30209/productpage | grep -o "<title>.*</title>"
<title>Simple Bookstore App</title>

Then, I've installed ELK stack according: 
- https://istio.io/docs/tasks/observability/mixer/logs/fluentd/

Then, when load's been generated, using:
for i in `seq 1 100`; do curl -s http://172.28.1.11:30209/productpage | grep -o "<title>.*</title>" && sleep 3; done

No logs are being forwarded to elasticsearch server so far.

Attaching logs files:
[fluentd.log](https://github.com/istio/istio/files/4536308/fluentd.log)
[ingress-gateway.log](https://github.com/istio/istio/files/4536309/ingress-gateway.log)
[istiod.log](https://github.com/istio/istio/files/4536310/istiod.log)
[istio-telemetry.log](https://github.com/istio/istio/files/4536311/istio-telemetry.log)
[bookinfo-productpage.log](https://github.com/istio/istio/files/4536312/bookinfo-productpage.log)

Cheers

**Comment by adabuleanu** [comment]
Are there any docs for integrating ELK/EFK with istio 1.5? Since Mixer is deprecated in 1.5, the only doc that speaks of such an integration https://istio.io/docs/tasks/observability/mixer/logs/fluentd/ is not relevant anymore. Can you point to such doc for Istio 1.5?

Also, since Mixer functionality is moved into Envoy proxies there does not look like Istio 1.5 provides a centralized log location https://istio.io/docs/tasks/observability/logs/access-log/. In this case, such integration becomes mandatory if you want to go to production with Istio 1.5.

Thanks,
Adrian
