### ISSUE TITLE
istioctl get not working on windows

### ISSUE THREAD

**Issue by AceHack** [istio/istio#2329]
I get the following error even though kubectl is working just fine

PS D:\Kubernetes\kube-resources\istio\bin> kubectl.exe version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:38:10Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
PS D:\Kubernetes\kube-resources\istio\bin> .\istioctl.exe get
Error: kubernetes configuration file "/.kube/config" does not exist

**Comment by ldemailly** [comment]
you need to pass to istioctl the location of your .kube/config

ie istioctl.exe -c pathtoyourconfig

**Comment by jasonwzm** [comment]
This is a related issue #1788
