### ISSUE TITLE
Released Helm charts are not up to date

### ISSUE THREAD

**Issue by Stratouklos** [istio/istio#23317]
**Bug description**

The correct Helm charts to install Istio 1.5.2 are located in [manifests/charts](https://github.com/istio/istio/tree/0aa22424c2f73f2187a8a279ef6744f725a45277/manifests/charts).

But the [1.5.2 release ](https://gcsweb.istio.io/gcs/istio-release/releases/1.5.2/charts/) is releasing old charts.

**Expected behaviour**

The officially released charts should be up to date.

**Steps to reproduce the bug**
```
helm repo add istio.io https://storage.googleapis.com/istio-release/releases/1.5.2/charts/
kubectl create namespace istio-system
helm template install/kubernetes/helm/istio-init --name istio-init --namespace istio-system | kubectl apply -f -
kubectl -n istio-system wait --for=condition=complete job --all
helm template install/kubernetes/helm/istio --name istio --namespace istio-system | kubectl apply -f -
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:41:55Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
$ helm version
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

**How was Istio installed?**

Helm via Terraform

**Environment where bug was observed (cloud vendor, OS, etc)**

Unrelated

**Comment by howardjohn** [comment]
In 1.5 there are two sets of helm charts - one under manifests/ and other under install/. The install/ ones are legacy and removed in 1.6; this is what is published. The manifests/ ones are meant to be installed via https://istio.io/docs/setup/install/istioctl/

**Comment by Stratouklos** [comment]
Excellent! IMHO this should be noted in [the docs](https://istio.io/docs/setup/install/helm/) and if possible/easy can you please consider publishing the `manifests/` charts?

Is the idea that all installation methods will be deprecated soon in favour of `istioctl`, if so when? If helm is not to be supported anymore is there a link to the discussion where that decision was made?

I'm new to Istio and really trying to understand what I stand to gain by reworking my automation to use `istioctl` vs `helm`.

**Comment by Stratouklos** [comment]
I found answers to my questions @howardjohn sorry for asking before googling :(

[Timeline for helm deprecation](https://discuss.istio.io/t/timelines-for-helm-installation-deprecation/4709/5)
[To istioctl or to helm](https://discuss.istio.io/t/to-istioctl-or-to-helm/4498)
