### ISSUE TITLE
Analyzers should see but not validate namespace "istio.io/rev=default" injection label

### ISSUE THREAD

**Issue by esnible** [istio/istio#23319]
If I install Istio without `--set revision=` sometimes the revision is `default` and other times `""` and this is screwing up injection.

To reproduce

```
~/go/src/istio.io/istio/out/darwin_amd64/istioctl install --charts manifests --set hub=gcr.io/istio-testing --set tag=latest
// label looks empty
kubectl get istiooperator --all-namespaces
// label looks like "default"
kubectl -n istio-system get pods -l istio=pilot -o jsonpath="{.items[*].metadata.labels}"

kubectl label namespace default istio.io/rev=default
// doesn't inject
kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml
// warns that istio-proxy is missing
~/go/src/istio.io/istio/out/darwin_amd64/istioctl analyze

kubectl delete -f samples/bookinfo/platform/kube/bookinfo.yaml
// doesn't inject
kubectl label namespace default istio.io/rev= --overwrite
// Warns that the namespace is labeled to inject from "" but that namespace (sic) doesn't exist; I should run 'kubectl label namespace default istio.io/rev=default'
~/go/src/istio.io/istio/out/darwin_amd64/istioctl analyze
```

@ostromart I will fix the analyzer.  To do that I need to know what the intended value of the `istio.io/rev` label on Istiod.
I am hoping you can assign someone from environments to fix the injector to work using only the new label.
If the intention is that not setting the revision causes istiod to be labeled `istio.io/rev=default` should we put the string `default` into the IstioOperator we now create on the cluster?  My hope is that `kubectl get istiooperator --all-namespaces`, which now prints a REVISION column, tells the user what revisions are possible for the other commands.

**Comment by howardjohn** [comment]
@esnible istio.io/rev=default is currently a bit of an implementation detail. if you are not using a revision you would set the istio-injection=enabled label. We should probably change that though

**Comment by howardjohn** [comment]
I think we should support this, for consistency. https://github.com/istio/istio/pull/23323 implements this

**Comment by esnible** [comment]
@howardjohn For 1.6.0 should I change the analyzer to recommend the label `istio-injection=enabled` and never say to use `istio.io/rev=default`?

**Comment by howardjohn** [comment]
In my opinion, we should recommend istio-injection=enabled but support `istio.io/rev=default`, to keep changes minimal for 1.6. `istio-injection` has been around forever so I don't want to randomly change it and cause confusion. What do you think?

**Comment by esnible** [comment]
@howardjohn Currently the analysis does this if both labels are present:

```
Warn [IST0123] (Namespace default) The namespace has both new and legacy injection labels.
Run 'kubectl label namespace default istio.io/rev-' or 'kubectl label namespace default istio-injection-'
```

If the `default` revision has special semantics the message must not recommend `kubectl label namespace default istio-injection-`.  We would need a new message for this case.

If the injection label refers to an unknown revision analysis currently generates this message:

```
Warn [IST0124] (Namespace default) The namespace is labeled to inject from "potato" but that namespace (sic) doesn't exist. Run 'kubectl label namespace default istio.io/rev=<revision>' where <revision> is one of default
```

(I will fix the typo).  If the `default` revision has special semantics the message must not recommend `kubectl label namespace default istio.io/rev=default`.  We would need a new message for this case, recommending `istio-injection=enabled`.

I want to fix those messages today.  I need guidance on if the messages should change or if your in-progress PR will allow me to keep the current message.  (I will fix the typo).

**Comment by howardjohn** [comment]
I have realized with https://github.com/istio/istio/pull/23323 if you have both injection labels it will actually cause it to *not* be injected. In order to fix that we would need to add a 3rd webhook which seems awfully heavy weight. let me see if there is a better way to support `istio-injection=enabled || istio.io/rev=default`, and if we cannot come up with one add special handling for `default`?

**Comment by howardjohn** [comment]
@esnible can you take a look at https://github.com/istio/istio/pull/23342? it basically implements matching `istio-injection=enabled || istio.io/rev=default`. Slightly roundabout, as k8s doesn't natively support this, but from the user perspective it should work fine
