### ISSUE TITLE
Select authentication more smartly when PEER and JWT auth enabled simultaneously

### ISSUE THREAD

**Issue by pandagodyyy** [istio/istio#23329]
**Describe the feature request**
In the Istio 1.4 version, we use Policy to enable mtls and origin auth for a service A, I expose service A to the Internet, and one non-istio service B will have a call to A with the JWT token, then request will accepted by A. However a service C in the same istio also have a call to A, A reject the request because of "origin authentication failed", Is it possible let A accept requests from C since they use mtls and they do not need origin authentication anymore. 
**Describe alternatives you've considered**

**Additional context**

**Comment by emzhu06** [comment]
cc @yangminzhu

**Comment by JimmyCYJ** [comment]
@pandagodyyy could you upgrade your Istio to at least 1.6? 1.4 is old and EOF.

**Comment by yangminzhu** [comment]
this can be done with the new AuthorizationPolicy and RequestAuthenticaion. You configure the AuthZ policy of A to only require JWT if the request is not from C. See   https://istio.io/latest/docs/tasks/security/authentication/authn-policy/#require-valid-tokens-per-path for example.

**Comment by yangminzhu** [comment]
@pandaamanda  Feel free to reopen the issue if you have more questions.
