### ISSUE TITLE
Istiod - remote error: tls: expired certificate

### ISSUE THREAD

**Issue by widdix123** [istio/istio#23328]
**Bug description**
Envoy proxy is Not Ready on istio-proxy logs for any application . It works only if i restart istiod pods on istio-system

The error i  get is "remote error: tls: expired certificate" on istiod logs. This gets resolved once i delete the istiod pods.

**Expected behavior**
Envoy Proxy Ready

**Steps to reproduce the bug**
Install istioctl with mtls enabled and deploy few applications . The node group associated with EKS cluster is `t2.medium`

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.5.1

**How was Istio installed?**
istioctl command line

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS

**Comment by widdix123** [comment]
Can someone please suggest ?

**Comment by widdix123** [comment]
Any idea why do i need to restart istiod to get the Istio-proxy to be working ? 

I need to put this to production and this seems to be a major blocker ?

**Comment by bernardoVale** [comment]
Same problem here

**Comment by abhijitkubric** [comment]
Same problem here with Istio 1.5.10
