### ISSUE TITLE
Envoy Listeners wrong configuration intermittently

### ISSUE THREAD

**Issue by piyush0609** [istio/istio#23333]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
Listeners in envoy proxy config is listening on some random port against the pod IP.

Some pods were failing health checks on port 8080. This is the proxy config of one such pod
```
istioctl pc listener service-name.dev-internal | grep 'a.x.y.129'                                                               
a.x.y.129        8153      TCP
```
Pod for which health check was passing
```
istioctl pc listener service-name.dev-internal | grep 'a.x.y.245'
a.x.y.245        4001      TCP
a.x.y.245        8080      TCP
a.x.y.245        15020     TCP
```

Couldn't find anything out of ordinary in pilot and envoy proxy log

There were some of these logs but i have seen this logs for the pods with passing health checks
```
[**istio-pilot-discovery**] svc.cluster.local-6062 terminated rpc error: code = Canceled desc = context canceled

[**service-sidecar-proxy**] [Envoy (Epoch 0)] [2020-04-27 09:30:18.587][21][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:54] Unable to establish new stream
```
After this issue i have to exclude inbound traffic to my service ports as it was causing the above mentioned issue now and then

**Affected product area (please put an X in all that apply)**

[] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

**Steps to reproduce the bug**
I am not able to reproduce this bug consistently

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
client version: 1.4.3
control plane version: 1.4.3
data plane version: 1.4.3 (82 proxies)
helm version 3 but it was installed using helm template

**How was Istio installed?**
helm3 template and kubectl apply

**Environment where bug was observed (cloud vendor, OS, etc)**
Self hosted kubernetes cluster on AWS

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
could be https://github.com/istio/istio/issues/20676? Which is fixed in 1.4.5

**Comment by piyush0609** [comment]
@howardjohn We have upgraded to istio 1.4.5 now but we also excluded inbound port from mesh. The issue stopped after we did the latter.

**Comment by howardjohn** [comment]
I don't think excluding inbound port impacts the generated config, so I am assuming this is fixed by the above PR then. If I made a bad assumption let me know and we can try to debug this further.
