### ISSUE TITLE
Zipkin-to-Stackdriver Service Missing Namespace

### ISSUE THREAD

**Issue by garystafford** [istio/istio#2333]
The `/install/kubernetes/addons/zipkin-to-stackdriver.yaml` file is missing the `namespace` declaration for the Service. It now defaults to `default`. Assume it should be `namespace: istio-system`.

```bash
...
---
apiVersion: v1
kind: Service
metadata:
  name: zipkin-to-stackdriver
  namespace: istio-system # <-- missing namespace
spec:
  ports:
  - name: zipkin
    port: 9411
  selector:
    app: zipkin-to-stackdriver
---
```

**Comment by ldemailly** [comment]
seems like the fix was reverted

**Comment by douglas-reid** [comment]
@bianpengyuan can you send your fixing PR again?  it got caught up in some mass reversion of PRs.
