### ISSUE TITLE
The Bookinfo example does not seem to work for Istio 1.5.x

### ISSUE THREAD

**Issue by tariq1890** [istio/istio#23347]
**Bug description**
I have tried this several times, and I just can't seem to get bookinfo to work despite following the instructions here: https://istio.io/docs/examples/bookinfo/

The only way I can get bookinfo to work if the bookinfo pods, gateways and virtualservices are in the same namespace as that of Istio.

**Expected behavior**

Bookinfo should work even if its pods, virtualservices and gateways are installed in the `default` or any non-`istio-system` namespace.

**Steps to reproduce the bug**
Follow the instructions given in the link below with Istio 1.5.1
https://istio.io/docs/examples/bookinfo/

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by GregHanson** [comment]
Going to need more information here.  Please provide terminal outputs where possible.

1. How did you install istio? istioctl / helm / operator?
2. Which profile did you use to install istio, demo/default?
3. Where is istio installed, GKE / IKS / Minikube?
4. Bookinfo pods are all running and injected with sidecar?
5. What is the exact failure you are seeing?  Connection refused? 404's?

I just tried official 1.5.1 and 1.5.2 releases on IKS env.  Bookinfo pods deployed in default namespace.  `samples/bookinfo/networking/bookinfo-gateway.yaml` created in default namespace

**Comment by tariq1890** [comment]
Thanks for your response @GregHanson 

1. We are using a custom helm chart to deploy `istiod`. Please note that with this installation, I am able to get bookinfo to work if it is in the namespace as istio: `istio-system`
2. N/A. See the above point
3. What is IKS? This is Kubernetes on AWS
4. Yes, the Bookinfo pods are running fine. The Istio proxy sidecars are running too. I am using IstioCNI
5. When I try to route the traffic from istio-ingressgateway to bookinfo pods in another namespace, I just get an empty response.

**Comment by tariq1890** [comment]
I just need to know how to debug I don't know what is not working here. When I compare the Istio Ingressgateway envoy config dump (with bookinfo in different and the same namespace), I don't see unexpected differences/discrepancies.

**Comment by GregHanson** [comment]
@tariq1890 Can you share your chart or install command?  Being able to replicate would help.  

Also, can you clarify in which namespace things are created when they are not working for you?  Bookinfo pods are in default namespace and what about the Gateway and VirtualService? In your broken case, what does this output look like?
```
kubectl get gateways,virtualservices --all-namespaces
```

Define `empty response`, are you trying to access using curl or through a browser?  Can you include console output or a screenshot?

Do you have access logs enabled in your custom install? You can use the instructions [here](https://istio.io/docs/tasks/observability/logs/access-log/#enable-envoy-s-access-logging)
```
--set values.global.proxy.accessLogFile="/dev/stdout"
```
You can then check access logs of the ingress gateway after attempting a few calls to ingress gateway:
```
kubectl logs -n istio-system $(kubectl get pod -l istio=ingressgateway \
-n istio-system -o jsonpath='{.items[0].metadata.name}')
```
If you could add the access log entry from your request that would help with diagnosing.  `Connection refused` can come from missing or misconfigured Gateway rule, 404's are generally a problem with VirutalServices

You can also check access logs of the productpage pod, to see if the request is making it from ingress gateway to productpage:
```
kubectl logs $(kubectl get pod -l app=productpage -o jsonpath='{.items[0].metadata.name}') -c istio-proxy
```

You can also run `istioctl analyze -k -n <namespace>` on `default` and `Istio-system` to see if the tool picks up any misconfigurations.

**Comment by tariq1890** [comment]
@GregHanson Thanks again. I have enabled access logs. I seem to be getting `400 Bad Requests` actually

```
GET /productpage HTTP/1.1" 400 - "-" "-" 0 0 24 4 "10.2.8.52" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:75.0) Gecko/20100101 Firefox/75.0" "d1f05cd7-2bac-48bd-abef-f06a97dc2014" "aff84ac935eb447afa9b1f649a782b77-1672155039.us-east-1.elb.amazonaws.com" "10.244.65.85:9080" outbound|9080||productpage.default.svc.cluster.local 10.244.65.105:60994 10.244.65.105:80 10.2.8.52:5176 - -
[2020-04-28T23:02:50.983Z] "GET /productpage HTTP/1.1" 400 - "-" "-" 0 0 0 0 "10.2.8.52" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:75.0) Gecko/20100101 Firefox/75.0" "218d05a1-7627-4d63-a0e6-a46e87a9bf68" "aff84ac935eb447afa9b1f649a782b77-1672155039.us-east-1.elb.amazonaws.com" "10.244.65.85:9080" outbound|9080||productpage.default.svc.cluster.local 10.244.65.105:32784 10.244.65.105:80 10.2.8.52:5176 - -
[2020-04-28T23:02:52.515Z] "GET /productpage HTTP/1.1" 400 - "-" "-" 0 0 0 0 "10.2.8.52" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:75.0) Gecko/20100101 Firefox/75.0" "29d24187-43fa-4c61-a3fc-9a4b7e07a20f" "aff84ac935eb447afa9b1f649a782b77-1672155039.us-east-1.elb.amazonaws.com" "10.244.65.85:9080" outbound|9080||productpage.default.svc.cluster.local 10.244.65.105:32802 10.244.65.105:80 10.2.8.52:5176 - -
```

**Comment by tariq1890** [comment]
This is my Gateway. I am not sure what could be misconfigured here

```
apiVersion: v1
items:
- apiVersion: networking.istio.io/v1beta1
  kind: Gateway
  metadata:
    creationTimestamp: "2020-04-28T23:02:43Z"
    generation: 1
    name: bookinfo-gateway
    namespace: default
    resourceVersion: "3239164"
    uid: 60c4238b-4410-4e52-bbcf-7ec3e772d90a
  spec:
    selector:
      istio: ingressgateway
    servers:
    - hosts:
      - '*'
      port:
        name: http
        number: 80
        protocol: HTTP
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Comment by GregHanson** [comment]
Are there any k8s network policies in effect which limit ingress/egress communication between namespaces?  

Does `istioctl proxy-status` show anything as `NOT SENT`?

Do you have any DestinationRules, Policies, or PeerAuthentication rules in place?
```
kubectl get destinationrules,policies,peerauthentications --all-namespaces
```

**Comment by tariq1890** [comment]
i) We don't use network policies in our Kubernetes clusters as yet.

ii) Everything shows up as `SYNCED`

ii) I do have `destinationrules` 

```
default        destinationrule.networking.istio.io/details       details                                41h
default        destinationrule.networking.istio.io/productpage   productpage                            41h
default        destinationrule.networking.istio.io/ratings       ratings                                41h
default        destinationrule.networking.istio.io/reviews       reviews                                41h
istio-system   destinationrule.networking.istio.io/api-server    kubernetes.default.svc.cluster.local   7d15h
istio-system   destinationrule.networking.istio.io/details       details                                13d
istio-system   destinationrule.networking.istio.io/productpage   productpage                            13d
istio-system   destinationrule.networking.istio.io/ratings       ratings                                13d
istio-system   destinationrule.networking.istio.io/reviews       reviews                                13d
```

**Comment by tariq1890** [comment]
Raised a new GitHub issue with more details and clarity around this: https://github.com/istio/istio/issues/23401
