### ISSUE TITLE
Istiod tests: input events record / playback

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#23358]
Create a harness that records all Inputs to istiod so that they can be played back later.
This feature is similar to traffic mirroring. Record must contain all config and registry changes.

Options.
- Publish all incoming events to an event bus.
   - https://cloudevents.github.io/sdk-go supports kafka / NATS etc.
   - Write a cloud events subscriber to store events
   - write a cloud events consumer inside istiod to playback.
- Use well known format, but always store to disk in a log format.
   - Disk log consumer as an input source.

**Comment by howardjohn** [comment]
Do we have a use case for "replaying" or do we just need to take point in time snapshot?

**Comment by mandarjog** [comment]
not stale.

**Comment by mandarjog** [comment]
@howardjohn replay is a good way to test our state machine in a deterministic way.
