### ISSUE TITLE
Error: lookup failed for udp address: lookup istio-mixer on 172.19.0.10:53: no such host

### ISSUE THREAD

**Issue by murphyzh** [istio/istio#2336]
The current v0.3.0 version RUN kubectl apply -f install/kubernetes/istio.yaml
then kubectl get pods -n istio-system
istio-ca-555bbff478-j8rt7        1/1       Running            0          12m
istio-ingress-8559f9dc97-q6l4v   0/1       CrashLoopBackOff   7          12m
istio-mixer-559b684ff8-5hhdl     3/3       Running            3          12m
istio-pilot-8544445799-msvrj     2/2       Running            3          12m

i find logs from pod
ERROR: logging before flag.Parse: I1226 10:01:09.705478       1 main.go:68] Version root@24c944bda24b-0.3.0-24ec6a3ac3a1d592d1873d2d8198278a849b8301
ERROR: logging before flag.Parse: I1226 10:01:09.705577       1 main.go:109] Proxy role: proxy.Node{Type:"ingress", IPAddress:"", ID:"istio-ingress-8559f9dc97-q6l4v.istio-system", Domain:"istio-system.svc.cluster.local"}
ERROR: logging before flag.Parse: I1226 10:01:09.705613       1 resolve.go:35] Attempting to lookup address: istio-mixer
ERROR: logging before flag.Parse: I1226 10:01:09.712183       1 resolve.go:42] Finished lookup of address: istio-mixer
Error: lookup failed for udp address: lookup istio-mixer on 172.19.0.10:53: no such host

????

**Comment by eumji025** [comment]
hello
Have you solution this problem really?
I got the some question like you

```shell
ERROR: logging before flag.Parse: I1229 09:55:58.113174       1 main.go:68] Version root@24c944bda24b-0.3.0-24ec6a3ac3a1d592d1873d2d8198278a849b8301
ERROR: logging before flag.Parse: I1229 09:55:58.113330       1 main.go:109] Proxy role: proxy.Node{Type:"ingress", IPAddress:"", ID:"istio-ingress-85fb769c4d-x9prg.istio-system", Domain:"istio-system.svc.cluster.local"}
ERROR: logging before flag.Parse: I1229 09:55:58.113427       1 resolve.go:35] Attempting to lookup address: istio-mixer
ERROR: logging before flag.Parse: I1229 09:56:13.113665       1 resolve.go:42] Finished lookup of address: istio-mixer
Error: lookup failed for udp address: i/o timeout
Usage:
  agent proxy [flags]

ERROR: logging before flag.Parse: E1229 09:56:13.114195       1 main.go:267] lookup failed for udp address: i/o timeout

```

**Comment by murphyzh** [comment]
you can delete the original istio deployment (kubectl delete-f install / kubernetes / istio.yaml), modify istio.yaml, delete the following two lines, and then redeploy istio (kubectl apply-f install / kubernetes / istio.yaml.
         - --statsdUdpAddress
         - istio-mixer: 9125 .Official statement has no effect with no  statsd udp query

**Comment by eumji025** [comment]
thank you very much. it work

**Comment by jcmcken** [comment]
Also had this issue. Commenting out the statsd option also worked for me.

**Comment by mandarjog** [comment]
Is ingress otherwise able to connect to `istio-mixer.istio-system.svc.cluster.local`?

**Comment by jcmcken** [comment]
@mandarjog In my case, ``istio-ingress`` kept dying and getting restarted. I took that as a sign not to worry about the actual functionality until I could get it into a steady state. Commenting out the statsd option did that for me. I'm having other issues with ``kube-dns`` and ``minikube`` at the moment unrelated to Istio, so I can't answer if it's working now that it isn't constantly restarting.

**Comment by sandylss** [comment]
Hi,I also met this issue.Commenting out the statsd workd for the istio-ingree pods.
But when I use `kubectl apply -f <(istioctl kube-inject -f  nrf-istio-client.yaml`deploy a service ,the pods is keep restarting,then I use `kubectl logs -f pods/nrf-istio-clint-55d9fcd754-rbtpf -c istio-proxy`
the logs like this


> ERROR: logging before flag.Parse: I0125 09:26:34.560878       1 main.go:70] Version root@cc5c34bbd1ee-0.4.0-24089ea97c8d244493c93b499a666ddf4010b547-dirty
ERROR: logging before flag.Parse: I0125 09:27:04.561310       1 main.go:114] Error retrieving availability zone from pilot: Get http://istio-pilot.istio-system:15003/v1/az/istio-proxy/sidecar~172.19.78.24~nrf-istio-clint-55d9fcd754-rbtpf.default~default.svc.cluster.local: dial tcp: i/o timeout
ERROR: logging before flag.Parse: I0125 09:27:04.561372       1 main.go:124] Proxy role: proxy.Node{Type:"sidecar", IPAddress:"172.19.78.24", ID:"nrf-istio-clint-55d9fcd754-rbtpf.default", Domain:"default.svc.cluster.local"}
ERROR: logging before flag.Parse: I0125 09:27:04.561422       1 resolve.go:35] Attempting to lookup address: istio-mixer.istio-system
ERROR: logging before flag.Parse: I0125 09:27:19.561579       1 resolve.go:42] Finished lookup of address: istio-mixer.istio-system
Error: lookup failed for udp address: i/o timeout
Usage:
  agent proxy [flags]

> ERROR: logging before flag.Parse: E0125 09:27:19.562506       1 main.go:282] lookup failed for udp address: i/o timeout


`kubectl get all -n istio-system`

> NAME   DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/grafana             1         1         1            1           1d
deploy/istio-ca            1         1         1            1           1d
deploy/istio-ingress       1         1         1            1           1d
deploy/istio-initializer   1         1         1            1           1d
deploy/istio-mixer         1         1         1            1           1d
deploy/istio-pilot         1         1         1            1           1d
deploy/prometheus          1         1         1            1           1d
deploy/servicegraph        1         1         1            1           1d
deploy/zipkin              1         1         1            1           1d

> NAME                             DESIRED   CURRENT   READY     AGE
> rs/grafana-6fcf858855            1         1         1         1d
> rs/istio-ca-55b954ff7            1         1         1         1d
> rs/istio-ingress-7df7c46c7       1         1         1         1d
> rs/istio-initializer-6c84859cd   1         1         1         1d
> rs/istio-mixer-59cc756b48        1         1         1         1d
> rs/istio-pilot-55bb7f5d9d        1         1         1         1d
> rs/prometheus-65c97b8569         1         1         1         1d
> rs/servicegraph-59555d4c65       1         1         1         1d
> rs/zipkin-69897c5899             1         1         1         1d
> 
> NAME                       DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
> deploy/grafana             1         1         1            1           1d
> deploy/istio-ca            1         1         1            1           1d
> deploy/istio-ingress       1         1         1            1           1d
> deploy/istio-initializer   1         1         1            1           1d
> deploy/istio-mixer         1         1         1            1           1d
> deploy/istio-pilot         1         1         1            1           1d
> deploy/prometheus          1         1         1            1           1d
> deploy/servicegraph        1         1         1            1           1d
> deploy/zipkin              1         1         1            1           1d
> 
> NAME                             DESIRED   CURRENT   READY     AGE
> rs/grafana-6fcf858855            1         1         1         1d
> rs/istio-ca-55b954ff7            1         1         1         1d
> rs/istio-ingress-7df7c46c7       1         1         1         1d
> rs/istio-initializer-6c84859cd   1         1         1         1d
> rs/istio-mixer-59cc756b48        1         1         1         1d
> rs/istio-pilot-55bb7f5d9d        1         1         1         1d
> rs/prometheus-65c97b8569         1         1         1         1d
> rs/servicegraph-59555d4c65       1         1         1         1d
> rs/zipkin-69897c5899             1         1         1         1d
> 
> NAME                                   READY     STATUS    RESTARTS   AGE
> po/grafana-6fcf858855-6x6fj            1/1       Running   0          1d
> po/istio-ca-55b954ff7-zzgqp            1/1       Running   0          1d
> po/istio-ingress-7df7c46c7-tw9x8       1/1       Running   0          1d
> po/istio-initializer-6c84859cd-gzjrh   1/1       Running   0          1d
> po/istio-mixer-59cc756b48-srn7s        3/3       Running   0          1d
> po/istio-pilot-55bb7f5d9d-lfsjs        2/2       Running   0          1d
> po/prometheus-65c97b8569-pm9ww         1/1       Running   0          1d
> po/servicegraph-59555d4c65-n6bl8       1/1       Running   0          1d
> po/zipkin-69897c5899-42qld             1/1       Running   0          1d
> 
> NAME                TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                                                            AGE
> svc/grafana         ClusterIP      10.104.73.246    <none>        3000/TCP                                                           1d
> svc/istio-ingress   LoadBalancer   10.109.181.222   <pending>     80:31739/TCP,443:32675/TCP                                         1d
> svc/istio-mixer     ClusterIP      10.97.8.252      <none>        9091/TCP,15004/TCP,9093/TCP,9094/TCP,9102/TCP,9125/UDP,42422/TCP   1d
> svc/istio-pilot     ClusterIP      10.101.186.155   <none>        15003/TCP,443/TCP                                                  1d
> svc/prometheus      ClusterIP      10.106.126.169   <none>        9090/TCP                                                           1d
> svc/servicegraph    ClusterIP      10.100.26.152    <none>        8088/TCP                                                           1d
> svc/zipkin          ClusterIP      10.102.120.171   <none>        9411/TCP                                                           1d
> `

It seems still is the problem ,can you give some solutions?
