### ISSUE TITLE
Fields removed without deprecation (TracerLightStepConfig.cacertPath and secure)

### ISSUE THREAD

**Issue by esnible** [istio/istio#23376]
A PR yesterday, https://github.com/istio/istio/pull/23220 , removed `cacertPath` and `secure` from `v1alpha1.TracerLightStepConfig`.

I hadn't even looked at that pull... the name "Add TLS settings to tracer" did not make me think anything was going away.

This breaks our deprecation/upgrade policy.

I don't know how many users have a TracerLightStepConfig setting in their IOP file, so maybe 1.5.x users will not be affected.  No one who makes an IstioOperator from scratch will be affected.  Folks who created their "iop.yaml" file using `istioctl profile dump > iop.yaml` may be affected.

My problem is that users on 1.6.0-alpha who do the install have an IOP written to the cluster.  With my PR, users doing `istioctl upgrade` or `istioctl manifest apply` use the in-cluster IOP if it exists instead of the `default` profile, leading to 

```
Error: failed to apply manifests: unknown field "cacertPath" in v1alpha1.TracerLightStepConfig
```

This is because the IstioOperator contains `cacertPath: ""`.

**Comment by esnible** [comment]
More data.  In this example, _istioctl-1.6.0-alpha.1_ is just the _istioctl_ binary from 1.6.0-alpha.1.

`istioctl manifest apply --force -f <(istioctl-1.6.0-alpha.1 profile dump)` fails with
```
unknown field "galley" in v1alpha1.Values
```

`./bin/istioctl manifest generate --force -f <(istioctl-1.6.0-alpha.1 profile dump)` succeeds.

Without `--force`, generate fails with
```
Error: validation errors (use --force to override): 
unknown field "galley" in v1alpha1.Values
```

**Comment by ostromart** [comment]
A number of things here:
1. The profiles should be compatible with validation and TestValidateValuesFromProfile used to test that. It's being skipped and should be restored. That would take care of the output from profile dump being incompatible. (https://github.com/istio/istio/issues/23396)
2. --force appears to be not working as advertised in manifest apply (https://github.com/istio/istio/issues/23397).
3. We need a general strategy for upgrading and applying when the API changes. It's in general not easy to distinguish between bad field names and removed field names that were previously valid. Previously valid fields will come up during upgrade (which uses apply under the hood, so there could be a common solution here) and between versions of istioctl where the compiled in API has changed.

**Comment by esnible** [comment]
https://github.com/istio/istio/pull/23377 should take care of the problem with `--force`.
