### ISSUE TITLE
sample custom gateway yaml need be updated

### ISSUE THREAD

**Issue by irisdingbj** [istio/istio#23373]
https://preliminary.istio.io/docs/setup/install/istioctl/
Note that Helm values (spec.values.gateways.istio-ingressgateway/egressgateway) are shared by all ingress/egress gateways. If these must be customized per gateway, it is recommended to use a separate IstioOperator CR to generate a manifest for the user gateways, separate from the main Istio installation:

need to add `namespace: user-ingressgateway-ns` to align with the previous step. otherwise, it will create a new ilb-gateway in `istio-system` namespace
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: empty
  components:
    ingressGateways:
      - name: ilb-gateway
        enabled: true
        **namespace: user-ingressgateway-ns**
        # Copy settings from istio-ingressgateway as needed.
  values:
    gateways:
      istio-ingressgateway:
        debug: error
```

**Comment by therealmitchconnors** [comment]
Note that this issue refers to this section: https://preliminary.istio.io/docs/setup/install/istioctl/#configure-gateways
