### ISSUE TITLE
Need image for s390x for  gcr.io/istio-testing/pilot:3101ea9d82a5f83b699c2d3245b371a19fa6bef4

### ISSUE THREAD

**Issue by kadamvandita** [istio/istio#2337]
Need image for s390x for  gcr.io/istio-testing/pilot:3101ea9d82a5f83b699c2d3245b371a19fa6bef4.
If not image at least a sample docker file for the same would help

**Comment by sdake** [comment]
Check out https://github.com/istio/istio/blob/master/DEV-GUIDE.md.  I'm not sure there is any infrastructure in Istio to build s390x.
