### ISSUE TITLE
'istioctl manifest generate' producing incorrect yaml (master, not -beta.0)

### ISSUE THREAD

**Issue by esnible** [istio/istio#23389]
Using Master, `istioctl manifest apply --charts manifests --set hub=gcr.io/istio-testing --set tag=latest` works.  This doesn't:

```
istioctl manifest generate --charts manifests | kubectl apply -f -
...
error: error validating "STDIN": error validating data: [ValidationError(Deployment.spec.template.spec.securityContext): unknown field "allowPrivilegeEscalation" in io.k8s.api.core.v1.PodSecurityContext
```

`kubectl version` says I am running kubectl client 1.18.2, Kubernetes server 1.16.8

**Comment by ostromart** [comment]
I believe this was fixed - we'll reopen if it's seen during community testing 1.7.
