### ISSUE TITLE
Cannot set custom ingress labels

### ISSUE THREAD

**Issue by esnible** [istio/istio#23392]
Testing with 1.6.0-beta.0

```
kubectl create ns special-gw
istioctl install \
   --set components.ingressGateways[1].enabled=true \
   --set components.ingressGateways[1].namespace=special-gw \
   --set components.ingressGateways[1].label.foo=bar
```

The output is 
```
✘ Component IngressGateways encountered an error: Deployment.apps "istio-ingressgateway" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app":"istio-ingressgateway", "foo":"bar", "istio":"ingressgateway"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```

**Comment by rvennam** [comment]
+1 If there are public and private gateways, they need different labels for selection

**Comment by catper** [comment]
[there is a way around this](https://github.com/istio/istio/issues/19263#issuecomment-609094185) but it would be nice with something that wasn't so verbose

**Comment by kramvan1** [comment]
Need to be name based, not indexes.

**Comment by linsun** [comment]
Do you still have the need to set ingress labels if you put the 2 gateways in different namespaces?  I noticed we have this in https://github.com/istio/istio/blob/master/manifests/charts/README-helm3.md:

```
currently we don't support insalling multiple gateways in same
namespace - nor is it a good practice. Ingress secrets and access should be separated from control plane.
```

**Comment by ostromart** [comment]
This has drifted somewhat from the original bug, which relates to overriding by index selection. Labels do work for multiple gateways for 1.6, implemented in https://github.com/istio/istio/pull/22981. See the input test cases in that PR, the docs should be updated for 1.6 with labels though.
