### ISSUE TITLE
No k8s events for Istio-controlled ingresses

### ISSUE THREAD

**Issue by ahmetb** [istio/istio#234]
Making it hard to understand if ingress is set up correctly etc.

**Comment by kyessenov** [comment]
That's an interesting issue. Istio does not emit k8s events (apart from those from may come from kubernetes/ingress library), since it's designed to be extensible to non-k8s environments. We will need a common "events" framework to support both k8s-style events and generic raw/managed VMs.

**Comment by andraxylia** [comment]
This is not fixed, needs to be re-open.

**Comment by ldemailly** [comment]
can someone clarify what this is about, it's not clear to me

**Comment by kyessenov** [comment]
Try `kubectl get events` :) You'll realize that istio is not producing any
events.

**Comment by ayj** [comment]
> This is not fixed, needs to be re-open.

@andraxylia - what is the priority of this for Istio 1.0?

**Comment by kyessenov** [comment]
Let's wait for @andraxylia to respond. This is a valid feature request, not clear about the priority.

**Comment by kyessenov** [comment]
The scope applies to more than networking I think. But it's more apparent for the core components.

**Comment by andraxylia** [comment]
We are moving to Gateway, so closing this.
