### ISSUE TITLE
Option to configure JWKs public key refresh interval

### ISSUE THREAD

**Issue by mattwongsd** [istio/istio#23409]
Hi, I apologise in advance if this request is bad. I've tried to search for an alternative to this for a day now. Thank you for your patience.

> **Describe the feature request**

I understand the default JWKs public key refresh interval in Istio is 20 minutes. I was wondering if there was an option to modify this without modifying the source code of Istio. Could we possibly provide this option via the Global Mesh options when deploying Istio?

I'm not an advanced user/developer, but not sure how viable it is to provide an object so that we can configure the public key refresh period per jwks URI. But I suppose that will include an overhaul of the current jwks resolver.

Some strict environments require the jwks refresh interval to be much lesser (3 mins).

> **Describe alternatives you've considered**

Modify `https://github.com/istio/istio/blob/2458727a3e9ef60b99f646f082113a408a008a0a/pilot/pkg/model/jwks_resolver.go#L61` and build Istio from source.

**Comment by JimmyCYJ** [comment]
Assign to @yangminzhu for triage.

**Comment by yangminzhu** [comment]
This is not supported today, could be a good starter issues, cc @samprit

**Comment by Morriz** [comment]
bump

**Comment by Morriz** [comment]
@JimmyCYJ are you an istio core member? Can somebody at least respond and label this issue?

**Comment by smwyzi** [comment]
can i submit a pr to support configure the refresh period from env?

**Comment by yangminzhu** [comment]
> can i submit a pr to support configure the refresh period from env?

there is already a PR https://github.com/istio/istio/pull/30014

**Comment by xulingqing** [comment]
The [PR](https://github.com/istio/istio/pull/30014) is done. Later on, user can config the refresh interval with `istioctl install --set values.pilot.env.PILOT_JWT_PUB_KEY_REFRESH_INTERVAL=1m`
