### ISSUE TITLE
Regex negative lookahead not working in VirtualService HTTPMatchRequest

### ISSUE THREAD

**Issue by emrahcetiner** [istio/istio#23416]
when I use `^\/(api)\/.*$` it works as expected. allows only path starts with `/api/`

if i add negative lookahead in regex, it doesn't work. `^(?!\/(internal)\/?)(.*)$`

I check proxy-config with this command and I see that proxy-config is not updated.
`istioctl proxy-config -n istio-system route istio-ingressgateway-... -ojson`

I think if i use `?!` in regex something is working wrong.

how can i define negative route? allow all paths without starts with `/internal/ `

```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
...
spec:
  http:
  - match:
    - uri:
        regex: ^(?!\/(internal)\/?)(.*)$
...
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
$ istioctl version --remote
client version: 1.5.1
control plane version: 1.5.1
data plane version: 1.5.1 (23 proxies)
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-15T15:50:38Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.9-gke.24", GitCommit:"39e41a8d6b7221b901a95d3af358dea6994b4a40", GitTreeState:"clean", BuildDate:"2020-02-29T01:24:35Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
with istioctl

**Comment by howardjohn** [comment]
See https://github.com/istio/istio/issues/21717, Envoy uses RE2 regex which does not support this

**Comment by emrahcetiner** [comment]
@howardjohn You are right, a feature lost due to performance

https://github.com/google/re2/issues/156#issuecomment-328418340

**Comment by bfalese-navent** [comment]
Same problem here, moving from HAProxy to Istio, my fix was:

'^[^/internal/]/inter.*\.html

Checks that does not start with /intertal/ before moving with the rule's positive part.

Hope it helps.

**Comment by emrahcetiner** [comment]
> '^[^/internal/]/inter.*.html

this regex pattern is not formatted correctly

**Comment by bfalese-navent** [comment]
Maybe you need to escape final dot, i'm using this and it works on Istio 1.5. Sorry it did not help you.
