### ISSUE TITLE
Cannot build docker images on Mac OS X 

### ISSUE THREAD

**Issue by christian-posta** [istio/istio#2341]
Istio build defaults to building binaries for Linux:

https://github.com/istio/istio/blob/master/Makefile#L33

For non-linux host docker builds, we try to generate certificates (https://github.com/istio/istio/blob/master/security/cmd/generate_cert/main.go) but the binary cannot run on non-linux hosts because it's attempting to build as linux. 

Patch forthcoming.

**Comment by richardcase** [comment]
This issue persists when trying to build on osx even with the 'unset'. 

I manually changed the makefile to this:
`GOOS=darwin GOARCH=amd64 CGO_ENABLED=1 bin/gobuild.sh $@ istio.io/istio/pkg/version ./security/cmd/generate_cert`
