### ISSUE TITLE
Add prometheus rules

### ISSUE THREAD

**Issue by bcochofel** [istio/istio#23419]
Hi, how can I add the rules described [here](https://istio.io/docs/ops/best-practices/observability/) to the prometheus instance?

Thanks,
Bruno

**Comment by howardjohn** [comment]
The configs to add are found here: https://istio.io/docs/ops/best-practices/observability/#federation-using-workload-level-aggregated-metrics

The instructions here are meant to be implemented in a Prometheus deployment not created as part of the istio install, so it would be best to consult the docs for that, whether its helm stable/prometheus, prometheus operator, etc.

**Comment by bcochofel** [comment]
Hi @howardjohn , I thought those configurations are to be done on the Prometheus that comes with Istio, that way I can install Prometheus Operator and federate those metrics from the Prometheus on Istio, right?

Thanks,
Bruno

**Comment by bcochofel** [comment]
Hi, in order to solve this issue I've removed prometheus from istio deployment and create a new prometheus server instance, on the same namespace of istio (for all the kiali links to be ok), a new service monitor and prometheus rule to achieve the federation described in the link and it seems to be working ok.

Thanks,
Bruno
