### ISSUE TITLE
Policy and MeshPolicy CRDs are missing from base in latest master

### ISSUE THREAD

**Issue by shakti-das** [istio/istio#23414]
**Bug description**
Policy and MeshPolicy CRDs are missing from base in latest master.

https://github.com/istio/istio/blob/c09eb030dec8c90c6c10131b264adad242a73ae7/manifests/charts/base/files/gen-istio-cluster.yaml

**Expected behavior**
Expected to see the v1beta1 CRDs for Policy and MeshPolicy

**Steps to reproduce the bug**
- https://github.com/istio/istio/blob/c09eb030dec8c90c6c10131b264adad242a73ae7/manifests/charts/base/files/gen-istio-cluster.yaml
- Search for MeshPolicy

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
Latest master

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by shakti-das** [comment]
This was removed in https://github.com/istio/istio/pull/22972/files#diff-1146d828e0e5506de02a98f87a00ca7f. I expected `apiVersion: apiextensions.k8s.io/v1beta1` Policy and MeshPolicy to remain after the PR.

**Comment by sdake** [comment]
@shakti-das we should have two files. one are CRDs, one are the rest of the base manifest. The CRDs can be generated from the CRDs directly - but not using helm - instead using concatenation.

**Comment by shakti-das** [comment]
This bug isn't related to the #23413, both are independent issues.

**Comment by shakti-das** [comment]
What's the replacement of `Policy` and `MeshPolicy`? We didn't use `Policy` but we did use `MeshPolicy` to mandate mesh wide TLS.

**Comment by howardjohn** [comment]
https://istio.io/blog/2019/v1beta1-authorization-policy/ and https://istio.io/news/releases/1.5.x/announcing-1.5/upgrade-notes/#authentication-policy

**Comment by shakti-das** [comment]
Ah! Thank you @howardjohn. This section probably needs to be updated too if not done already: https://istio.io/docs/reference/config/security/istio.authentication.v1alpha1/#Policy
