### ISSUE TITLE
Regarding the sidecar automatic injection of job types, after the execution of the job is not exited

### ISSUE THREAD

**Issue by yuenwah** [istio/istio#23412]
**Bug description**
Regarding the sidecar automatic injection of job types, after the execution of the job is not exited

**Expected behavior**
![image](https://user-images.githubusercontent.com/34834139/80682083-6fc42400-8af4-11ea-87a4-08525b746e54.png)

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
control plane version: 1.4.7
helm:v2.10.0
**How was Istio installed?**
rancher
**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
Please see https://github.com/istio/istio/issues/11659 which has lots of info on workarounds + future plans

**Comment by yuenwah** [comment]
Is it possible to create a job-type pod without injecting a sidecar

**Comment by yuenwah** [comment]
> 请参阅[＃11659](https://github.com/istio/istio/issues/11659)，其中包含有关解决方法和未来计划的大量信息，谢谢！

Is it possible to create a job-type pod without injecting a sidecar
