### ISSUE TITLE
healthcheck return 426 http code

### ISSUE THREAD

**Issue by hillbun** [istio/istio#23411]
**Describe the feature request**

I have installed istio-1.4.7

I test a health check from one node:

curl -v -0 -I -H 'Host:www.xxxx.com' -X HEAD http://192.168.100.216:80

it return 426 HTTP code, not but 200 code:

* About to connect() to 192.168.100.216 port 80 (#0)
*   Trying 192.168.100.216...
* Connected to 192.168.100.216 (192.168.100.216) port 80 (#0)
> HEAD / HTTP/1.0
> User-Agent: curl/7.29.0
> Accept: */*
> Host:www.xxxx.com
> 
< HTTP/1.1 426 Upgrade Required
HTTP/1.1 426 Upgrade Required
< date: Thu, 30 Apr 2020 06:36:38 GMT
date: Thu, 30 Apr 2020 06:36:38 GMT
< server: istio-envoy
server: istio-envoy

< 
* Connection #0 to host 192.168.100.216 left intact

How to config and solve it?

**Describe alternatives you've considered**

**Additional context**

**Comment by mandarjog** [comment]
You are trying to send an HTTP/1.0 request which is not supported, so it is asking you to upgrade.
Do not use `curl -0`  unless you specifically want to use http1.0.

Please reopen if this is not the issue.

**Comment by hillbun** [comment]
is it possible to enable HTTP/1.0 supported?

my cloud provider load balance use HTTP 1.0 for healthcheck

**Comment by mandarjog** [comment]
Set 
Add the following to Pilot.env 
PILOT_HTTP10: "1"

Or you can add it to 
gateways:
  istio-ingressgateway:
    env:
      ISTIO_META_HTTP10: '"1"'

This will enable http 1.0
