### ISSUE TITLE
Ability to remove the sidecar injected in a pod or a namespace

### ISSUE THREAD

**Issue by sb1975** [istio/istio#23428]
**Describe the feature request**
Today we have the ability to inject sidecar containers into a pod or namespace using manual mechanism or automatic.
Ref: https://istio.io/docs/setup/additional-setup/sidecar-injection/
So the request is to build mechanism to remove the sidecar injected in a pod or a namespace (using either manual or automatic mechanism) without impacting the running pod or application.

**Describe alternatives you've considered**

So there should be a ability to remove the sidecar from a specific pod or from all pods in a namespace depending on the scenario based on which the sidecar was injected:

- that is  either for a specific pod using Annotation
- or to all pods in a namespace via the namespace label

So the removal should address irrespective of whether the sidecar was installed using manual sidecar injection or automatic sidecar injection.

**Additional context**

**Comment by howardjohn** [comment]
There are two components here:
* The container with the sidecar. This cannot be done by kubernetes 
* The iptables which impacts the traffic. In theory this might be possible using https://github.com/istio/cni but without CNI I don't think its possible

**Comment by sb1975** [comment]
So essentially I am suggesting that the way today we have" istioctl kube-inject " mechanism to inject a pod into any Application pod, can we enhance the istioctl with another module to remove the injected service proxy.
Something like "istioctl kube-remove .. " which will remove the injected service proxy but at the same time ensuring that end user continue to get served, maybe using the Rollingupdate and MaxUnavailable. I am thinking it will be helpful if we have this flexibility within istioctl rather than the application take care of this complexity.

**Comment by howardjohn** [comment]
There is a `istioctl x kube-uninject` command that may give you what you are interested in

**Comment by esnible** [comment]
If `kube-uninject` gives you the behavior you need please close this issue.

`kube-uninject` will apply an annotation to the Deployment's pod template, cause Kubernetes to restart the pods with a label that causes Istio to ignore them for the purpose of injecting proxies.
