### ISSUE TITLE
Envoy doesn't got notified about the updated header name used in consistent hash

### ISSUE THREAD

**Issue by knight42** [istio/istio#23434]
**Bug description**
The corresponding hash policy is not updated after the header name specified in `DestinationRule.trafficPolicy.loadBalancer.consistentHash.httpHeaderName` is changed.

**Expected behavior**
The hash policy of the route should be consistent with the spec of DestinationRule.

**Steps to reproduce the bug**
Create a DestinationRule shown as below, then change the `httpHeaderName` to `x-user-2`
<summary>
<details>
<pre>
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  labels:
    app: echo
  name: echo
  namespace: default
spec:
  host: echo
  subsets:
  - labels:
      app: echo
    name: default
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpHeaderName: x-user
</pre>
</details>
</summary>

After that run `istioctl pc route <pod> --name <name> -ojson|grep x-user` and we will find the `httpHeaderName` not changed.
```
...
                            "hashPolicy": [
                                {
                                    "header": {
                                        "headerName": "x-user"
                                    }
                                }
                            ],
...
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
$ istioctl version --remote
control plane version: 1.5.1
data plane version: 1.5.1 (13 proxies), 1.5.0 (2 proxies)

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.7", GitCommit:"be3d344ed06bff7a4fc60656200a93c74f31f9a4", GitTreeState:"clean", BuildDate:"2020-02-11T19:24:46Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
`$ istioctl manifest apply --set profile=default`

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
this will be in 1.5.3 and 1.6.0. As a workaround you can change a virtual service every time you change the destination rule - not a great solution just giving options

**Comment by knight42** [comment]
Great! Thanks for your information
