### ISSUE TITLE
The behavior of Kubernetes ExternalName service is different if ports are missing

### ISSUE THREAD

**Issue by nak3** [istio/istio#23463]
**Bug description**

[The docs(Kubernetes ExternalName service to access an external service)](https://istio.io/docs/tasks/traffic-management/egress/egress-kubernetes-services/#kubernetes-externalname-service-to-access-an-external-service), it works fine as expected.
But the behavior is completely different by the presence of port setting in the service.

[X] Networking

**Steps to reproduce the bug**

__NOTE:__ step 1-5 just shows the docs procedure could work fine. Please start step-6 if you have already known it.

#### 0. Before begin

```
$ kubectl apply -f <(istioctl kube-inject -f samples/sleep/sleep.yaml)
$ export SOURCE_POD=$(kubectl get pod -l app=sleep -o jsonpath={.items..metadata.name})
```

#### 1. Create an ExternalName svc

```
$ kubectl apply -f - <<EOF
kind: Service
apiVersion: v1
metadata:
  name: my-httpbin
spec:
  type: ExternalName
  externalName: httpbin.org
  ports:
  - name: http
    protocol: TCP
    port: 80
EOF
```

#### 2. Test curl (it fails as expected)

```
$ kubectl exec -it $SOURCE_POD -c sleep -- curl my-httpbin.default.svc.cluster.local/headers
upstream connect error or disconnect/reset before headers. reset reason: connection failure
```

#### 3. Disable tls

```
$ kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: my-httpbin
spec:
  host: my-httpbin.default.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
EOF
```

#### 4. Test it (it works as expected)

```
$ kubectl exec -it $SOURCE_POD -c sleep -- curl my-httpbin.default.svc.cluster.local/headers -s -o /dev/null -w "%{http_code}\n"
200
```

#### 5. Cleanup DestinationRule to disable TLS and svc

```
$ kubectl delete destinationrule my-httpbin
$ kubectl delete svc my-httpbin
```

#### 6. Create same svc but without ports

```
$ kubectl apply -f - <<EOF
kind: Service
apiVersion: v1
metadata:
  name: my-httpbin
spec:
  type: ExternalName
  externalName: httpbin.org
EOF
```

#### 7. Test it (it works unexpectedly)

```
$ kubectl exec -it $SOURCE_POD -c sleep -- curl my-httpbin.default.svc.cluster.local/headers -s -o /dev/null -w "%{http_code}\n"
200
```

In this time, the curl command works fine __without destinationrule__.

**Version**

- Istio v1.5.1

**How was Istio installed?**

By using [this operator config](https://github.com/knative/serving/blob/master/third_party/istio-1.5.1/istio-ci-mesh-operator.yaml).

**Expected behavior**

- Both w/ ports and w/o ports should have same behavior.
- The [K8S's example](https://kubernetes.io/docs/concepts/services-networking/service/#externalname) does not have the ports. So, ports are not mandatory and should not effect.
- Knative Serving does not add the ports for ExternaName service for now and consider to add it. But due to this different results, it will be a destructive change.

**Comment by dominicqi** [comment]
It looks like this?  https://github.com/istio/istio/pull/21987
