### ISSUE TITLE
Operator multiple control plane upgrade support

### ISSUE THREAD

**Issue by sdake** [istio/istio#23479]
**Describe the feature request**

The operator in 1.6 lacks support for multiple control planes. Add such support.

**Describe alternatives you've considered**

istioctl already has initial support. The (standalone) operator lacks this same support, although the CLI mode could be used in its place.

**Additional context**

**Comment by ostromart** [comment]
@sdake the operator does support multiple control planes. Let's discuss whatever you feel is missing.

**Comment by sdake** [comment]
@ostromart I am not sure why I wrote the original issue as I did. See [my youtube video demonstrating upgrades done right](https://developer.ibm.com/videos/istio-upgrades-reloaded-revisions-tech/). I had hoped istioctl/standalone operator would provide an easy way to manage different revisions. in Istio 1.6 the istioctl/operator code doesn't seem to. I am ok with that, but I think our HuOperator community would benefit from simpler usability, hence the enhancement request.

Am I missing something? Did you want me to clarify the title of the issue?

cheers
-steve

**Comment by sb1975** [comment]
Yeah I think more appropriate heading would be Istio Operator to support control plane upgrade.
There is no multiple control plane  to support multiple tenants being asked here but thats a valid need, let me add that as an issue.

**Comment by esnible** [comment]
@richardwxn I wish to make sure that `istioctl` has an option to handle control plane upgrade / retirement.  Is there a design or PR for your work?

**Comment by richardwxn** [comment]
@esnible I am doing some experiment locally and working on drafting a doc, will post a link here soon

**Comment by esnible** [comment]
@richardwxn 's document is at https://docs.google.com/document/d/199feuH0_a4xBkQWQB3LSEMzGOEUZ7br7k1N-vngIOYw/edit

**Comment by esnible** [comment]
I would like to test this.  When will it be ready for dev testing?

**Comment by esnible** [comment]
Is this working?  How do I test it?

**Comment by esnible** [comment]
@richardwxn @ostromart Can this issue be closed?

**Comment by richardwxn** [comment]
@esnible Sry just saw your previous messages here. It would be really helpful if you can help test it, you can refer to the doc update PR for more details about the change. Please let me know whether you find any issues during testing. Thanks!
