### ISSUE TITLE
Long running tests with infrastructure chaos

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#23471]
Objective
We had many reported issues that were based on chaos caused by pre-emptible nodes and node autoscaling. For example cni bypass issue came to fore due to pre-emptible nodes.

Long running tests should capture that.

Long running tests should create multiple node pools.

*  One nodepool should be based pre-emptible
*  One nodepool should be autoscaled.

Additionally investigate if a smaller test can also induce this type of chaos.
 * Is simply deleting the vm manually the same test?

**Comment by mandarjog** [comment]
This is still needed.

**Comment by richardwxn** [comment]
Can probably reuse some resources from: https://github.com/chaos-mesh/chaos-mesh
