### ISSUE TITLE
Concurrency setting on proxy

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#23470]
Current state:

Envoy has a flag, --concurrency. This controls the number of worker threads. If concurrency is set to 0, it will use all available CPU cores. This is problematic on Kubernetes as the container may have cpu limit set.

Istio has a proxyconfig.concurrency setting. This **mostly** maps 1:1 with envoys settings, but in the sidecar injector if concurrency==0 then we will automagically set concurrency based on cpu requests.

Problems with this approach:
1) Sidecar and gateway behave differently
2) There is no way to specify if we want Envoy behavior of "all cpus" today or instead "use requests". It is not 100% clear if we need to support both options

We can easily fix (1). For (2) we will need more discussion.

Possible ideas:
1) Make concurrency setting an IntWrapper. Unset == use requests. 0 == use all CPUs.
2) Always make 0 == all cpus
3) Always make 0 == use requests

**Comment by howardjohn** [comment]
Warning!! --concurrency=0 means 1 worker thread in envoy, unset means "use all CPUs". In agent we have:

```

	if e.Config.Concurrency > 0 {
		startupArgs = append(startupArgs, "--concurrency", fmt.Sprint(e.Config.Concurrency))
	}
```

so for us 0=all cpus

**Comment by howardjohn** [comment]
So we don't waste effort in implementation if I forget, I have a pr to make gateway behave the same as sidecar in my branch `perf/concurrency-setting` if we decide to do that

**Comment by nrjpoddar** [comment]
@howardjohn this is all quite complicated & error prone. Since, you have done rounds of testing, can you tell me the following for 1.5 & 1.6?

1. How can you set Envoy to use all available CPUs for both gateways & sidecars via Istio config?
1. How can you set Envoy to use all the cpu set allowed for both gateways & sidecars via Istio config?

**Comment by howardjohn** [comment]
@nrjpoddar the ideal end case:

* Setting concurrency=X will use X threads
* Setting concurrency=0 will use all CPUs available
* Not setting concurrency will use the pod resource requests
This behavior will be consistent on sidecar and gateway

---

The case today:

* Setting concurrency=X will use X threads
* Setting concurrency=0 or not setting concurrency will use the pod resource requests on sidecar
* Setting concurrency=0 or not setting concurrency will use all CPUs available on the gateway

**Comment by ktalg** [comment]
> This is problematic on Kubernetes as the container may have cpu limit set.

@howardjohn 
May I ask what exactly is the problem?According to [this questions](https://stackoverflow.com/q/53276398/14174215) on  SO, I know multithreading is working on Pod, so is the problem you are referring to that more workers will cause a lot of frequent switching of CPU contexts?
And is also this the reason why the number of workers is set according to the cpu limit?

**Comment by howardjohn** [comment]
Yes, IIUC we did tests in the past and saw degraded performance and large
memory cost of many workers
