### ISSUE TITLE
Kiali Dashboard login does not work

### ISSUE THREAD

**Issue by ston1th** [istio/istio#23483]
**Bug description**

The profiles are missing a value for `strategy`.
```
istioctl profile dump --config-path values.kiali.dashboard demo
auth:
  strategy: ""
...
```

Using `login` as value for `strategy` the demo login (admin/admin) works.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
client version: 1.6.0-beta.0
control plane version: 1.6.0-beta.0
data plane version: 1.6.0-beta.0 (3 proxies)
```

**How was Istio installed?**
```
istioctl manifest apply --set profile=demo
```

**Environment where bug was observed (cloud vendor, OS, etc)**
* Fresh kubeadm cluster

**Comment by howardjohn** [comment]
I think this is fixed:

```
~/go/src/istio.io/istio (release-1.6)
$ go run ./istioctl/cmd/istioctl manifest generate --set profile=demo -d manifests | rg auth: -C 5
      grafana: istio-system
      tracing: istio-system
      pilot: istio-system
      prometheus: istio-system
    istio_namespace: istio-system
    auth:
      strategy: login
    deployment:
      accessible_namespaces: ['**']
```

by #23325 which was after beta0.

Thanks for reporting!
