### ISSUE TITLE
istio 1.5.2: fail to run bookinfo sample on minikube

### ISSUE THREAD

**Issue by fffffreedom** [istio/istio#23486]
**Bug description**
the status of pod is in Init:0/1:
$ kubectl get  pod
NAME                              READY   STATUS     RESTARTS   AGE
details-v1-78d78fbddf-gzs2q       2/2     Running    0          16m
productpage-v1-85b9bf9cd7-lksl4   2/2     Running    0          16m
ratings-v1-6c9dbf6b45-bzd9r       2/2     Running    0          16m
reviews-v1-564b97f875-h9zjz       0/2     Init:0/1   0          16m
reviews-v2-568c7c9d8f-jdjz2       2/2     Running    0          16m
reviews-v3-67b4988599-pdrcp       2/2     Running    0          16m

and when deleted , the apiserver refuses to work, as shown below: 
 kubectl delete pod reviews-v1-564b97f875-h9zjz
pod "reviews-v1-564b97f875-h9zjz" deleted
**The connection to the server 192.168.99.101:8443 was refused - did you specify the right host or port?**

and i have to stop and start the minikube, but there are some pod in the Init status:
$ kubectl get pod
NAME                              READY   STATUS     RESTARTS   AGE
details-v1-78d78fbddf-gzs2q       0/2     Init:0/1   1          92m
productpage-v1-85b9bf9cd7-lksl4   0/2     Init:0/1   1          92m
ratings-v1-6c9dbf6b45-bzd9r       2/2     Running    2          92m
reviews-v1-564b97f875-wbdzd       2/2     Running    2          16m
reviews-v2-568c7c9d8f-jdjz2       2/2     Running    2          92m
reviews-v3-67b4988599-pdrcp       2/2     Running    2          92m

running describe command:
$ kubectl describe pod details-v1-78d78fbddf-gzs2q
Events:
  Type     Reason          Age    From            Message
  ----     ------          ----   ----            -------
  Warning  FailedMount     4m39s  kubelet, istio  MountVolume.SetUp failed for volume "istiod-ca-cert" : failed to sync configmap cache: timed out waiting for the condition
  Warning  FailedMount     4m39s  kubelet, istio  MountVolume.SetUp failed for volume "bookinfo-details-token-xzfl7" : failed to sync secret cache: timed out waiting for the condition
  Normal   SandboxChanged  4m33s  kubelet, istio  Pod sandbox changed, it will be killed and re-created.
  Normal   Pulled          4m30s  kubelet, istio  Container image "docker.io/istio/proxyv2:1.5.2" already present on machine
  Normal   Created         4m30s  kubelet, istio  Created container istio-init
  Normal   Started         4m28s  kubelet, istio  Started container istio-init

**Expected behavior**
all pods are in running status

**Steps to reproduce the bug**
minikube：
minikube start \
    --vm-driver=virtualbox \
    --iso-url=https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.7.3.iso \
    --image-mirror-country cn \
    --image-repository=registry.cn-hangzhou.aliyuncs.com/google_containers \
    --kubernetes-version=v1.17.3 \
    --registry-mirror=https://hub-mirror.c.163.com,https://docker.mirrors.ustc.edu.cn \
    --memory=4096 \
    --cpus=2 \
    -p istio

istio
https://istio.io/docs/setup/getting-started/

- istioctl manifest apply --set profile=demo
- kubectl label namespace default istio-injection=enabled
- kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
$ istioctl version --remote
client version: 1.5.2
control plane version: 1.5.2
data plane version: 1.5.2 (7 proxies)

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
- istioctl manifest apply --set profile=demo

**Environment where bug was observed (cloud vendor, OS, etc)**
minikube

[istio-dump.tar.gz](https://github.com/istio/istio/files/4569777/istio-dump.tar.gz)

**Comment by fffffreedom** [comment]
the pod doesn't report lack of resource,  but this problem is solved by adding more resource:
adding memory to 8192, and cpus to 4

**Comment by howardjohn** [comment]
These resource issues with minikube are documented at https://istio.io/docs/setup/platform-setup/minikube/, so I don't think there are any changes we need here?

**Comment by fffffreedom** [comment]
yes, i found the resource requirement for minikube， thks  @howardjohn
