### ISSUE TITLE
sideEffects is not configurable and is used default (Unknown) in MutatingWebhookConfiguration for istio-sidecar-injector

### ISSUE THREAD

**Issue by nak3** [istio/istio#23485]
**Bug description**

When deploying MutatingWebhookConfiguration istio-sidecar-injector by istio-operator, its [sideEffects](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#side-effects) is `Unknown` (=v1beta1's default).

```
$ kubectl get MutatingWebhookConfiguration istio-sidecar-injector -o yaml |grep sideEffects
  sideEffects: Unknown
```

Due to this, when we deploy another webhook for dryRun, it does not work.

[X] Installation

**Expected behavior**

The sideEffects in MutatingWebhookConfiguration for istio-sidecar-injector should be `None` or `NoneOnDryRun`. (Or at least it should be configurable by `istioctl`).
(Please note that the `admissionregistration.k8s.io/v1` must be set to `None` or `NoneOndryrun`.)

**Steps to reproduce the bug**

- Deploy another webhook for dryRun and use it.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

- Istio 1.5.1

**How was Istio installed?**

By using [this yaml](https://github.com/knative/serving/blob/fcba76930a908d1f4725392690966e1aec19a73a/third_party/istio-1.5.1/istio-ci-mesh-operator.yaml).

**Comment by nak3** [comment]
Any news for ths?
I think that it would be alright to add `sideEffects: None` like other validation webhook, but is there any problem?

**Comment by howardjohn** [comment]
I created a commit for this weeks ago but forgot to submit, sorry! https://github.com/istio/istio/pull/24109
