### ISSUE TITLE
x_forwarded_for field of access log multipul IPs

### ISSUE THREAD

**Issue by hillbun** [istio/istio#23481]
**Bug description**

I config istio-ingressgateway with nodeport and externalTrafficPolicy: Local to enable log client IP addresss.

But x_forwarded_for field of access log I get value like "47.105.214.136,100.116.235.233" with multipul IPs.

How to config to just log only client real IP of "47.105.214.136"?

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

CentOS 7.6

**Comment by howardjohn** [comment]
The format is configurable. The default can be found here: https://github.com/istio/istio/blob/e5095d6479a015afba73d932d19e387e23343c47/pilot/pkg/networking/core/v1alpha3/listener.go#L118-L124 and all of the format options at https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage

**Comment by hillbun** [comment]
@howardjohn 

How to set use_remote_address = true by command of istioctl ?

**Comment by howardjohn** [comment]
`--set values.pilot.env.PILOT_SIDECAR_USE_REMOTE_ADDRESS=true`? is that
what you are are looking for?

**Comment by hillbun** [comment]
--set values.pilot.env.PILOT_SIDECAR_USE_REMOTE_ADDRESS=true

if I add this flag, x_forwarded_for field of access log will just record client IP address "47.105.214.136",
not "47.105.214.136,100.116.235.233"?

@howardjohn

**Comment by kebe7jun** [comment]
Normally, x-forwarded-for header added by reverse proxy, it seems that you have multiple proxies before envoy. It has nothing to do with envoy and istio.

**Comment by hillbun** [comment]
@kebe7jun 

Yes, I have a load balance before istio by cloud provider.

Is it possible for me to just log IP of 47.105.214.136 (client browser)?

**Comment by kebe7jun** [comment]
If there is only one LB before istio, I think the suggestion is okay, you should have a try.

**Comment by howardjohn** [comment]
In 1.6 these types of settings will be configurable: https://deploy-preview-7242--preliminary-istio.netlify.app/docs/ops/configuration/traffic-management/network-topologies/

**Comment by howardjohn** [comment]
As far as I can tell all open issues here are resolved
