### ISSUE TITLE
Istio related docker images/Dockerfile's to test sample examples with kubernetes on s390x  

### ISSUE THREAD

**Issue by guirish** [istio/istio#2348]
We have build istioctl from source on s390x and tested all the UTC's. Now we are trying to run a sample example with Kuberenetes.
We have started Kubernetes local cluster using **kubeadm** (Version:1.8.3). 

To test Istio with Kuberentes we executed the prerequisite yaml, i.e
 `kubectl apply -f install/kubernetes/istio.yaml`
 
The YAML file refers to amd64 images as a result the required istio pods are down in our s390x cluster.
Could you'll please let us know if there are plans to push s390x specific docker images for below listed images, also if possible could you'll give us reference to the Dockerfile's from where we could build these images locally.
Images include:
1) gcr.io/istio-testing/proxy_debug
2) gcr.io/istio-testing/istio-ca
3) gcr.io/istio-testing/mixer
4) gcr.io/istio-testing/pilot

**Comment by GregHanson** [comment]
@guirish  Dockerfiles can be found in the following directories:

https://github.com/istio/istio/tree/master/pilot/docker
https://github.com/istio/istio/tree/master/mixer/docker
https://github.com/istio/proxy/tree/master/docker

**Comment by guirish** [comment]
Thanks @GregHanson for the information.
