### ISSUE TITLE
istio 1.5.2 How to add other metrics to Istio Standard Metrics

### ISSUE THREAD

**Issue by tony-liuliu** [istio/istio#23497]
I want to view the information sent by all containers to BlackHoleCluster, including the target IP and port.

Reference document address https://istio.io/blog/2019/monitoring-external-service-traffic/#using-the-augmented-metrics 
in case of a TCP proxy listener in order to see the IP address of the external service that is blocked or allowed via BlackHole or Passthrough cluster, you will need to add the destination_ip label to the istio_tcp_connections_closed_total metric.

The default indicators seen in current prometheus are as follows:
```yaml
istio_tcp_connections_closed_total {
connection_security_policy = "unknown",
destination_app = "unknown",
destination_canonical_revision = "latest",
destination_canonical_service = "unknown",
destination_principal = "unknown",
destination_service = "unknown",
destination_service_name = "BlackHoleCluster",
destination_service_namespace = "unknown",
destination_version = "unknown",
destination_workload = "unknown",
destination_workload_namespace = "unknown",
instance = "10.244.228.97:15090",
job = "envoy-stats",
namespace = "fst-prod-hlw",
pod_name = "contentsupport-7c7978d688-qgzkw",
reporter = "source",
request_protocol = "tcp",
response_flags = "UH",
source_app = "contentsupport",
source_canonical_revision = "v1",
source_canonical_service = "contentsupport",
source_principal = "unknown",
source_version = "v1",
source_workload = "contentsupport",
source_workload_namespace = "fst-prod-hlw"
}
```
I want to add destination_ip and destination_port for example:
```yaml
istio_tcp_connections_closed_total {
connection_security_policy = "unknown",
destination_app = "unknown",
destination_canonical_revision = "latest",
destination_canonical_service = "unknown",
destination_principal = "unknown",
destination_ip = "100.100.100.100",
destination_port = "7389",
destination_service = "unknown",
destination_service_name = "BlackHoleCluster",
...
}
```

How do I do this in istio 1.5.2 to achieve it.
I followed https://github.com/istio/istio/wiki/Configurable-V2-Metrics it does not work, I do n’t know if the document I referenced is incorrect, please help me thanks.

istio 1.5.2
kubernetes 1.15.6

**Comment by bianpengyuan** [comment]
That is the correct document for 1.5.2. Could you please paste your envoyfilter configuration here?

**Comment by tony-liuliu** [comment]
Thanks to @bianpengyuan  reply, the following is my reference to the official configuration, I do not know whether it is correct.

[root@k8s-node-46 ~]# cat tcp-stats-filter-1.5.yaml        
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: tcp-stats-filter-1.5
  namespace: istio-system
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: envoy.tcp_proxy
      proxy:
        proxyVersion: ^1\.5.*
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.network.wasm
        typed_config:
          '@type': type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.config.filter.network.wasm.v2.Wasm
          value:
            config:
              configuration: |
                {
                  "debug": "false",
                  "stat_prefix": "istio",
                  "metrics": [
                     {
                       "name": "requests_total",
                       "dimensions": {
                          "destination_port": "destination.port",
                          "request_host": "request.host"
                       }
                     }
                  ]
                }
              root_id: stats_inbound
              vm_config:
                code:
                  local:
                    inline_string: envoy.wasm.stats
                runtime: envoy.wasm.runtime.null
                vm_id: stats_inbound
  - applyTo: NETWORK_FILTER
    match:
      context: SIDECAR_OUTBOUND
      listener:
        filterChain:
          filter:
            name: envoy.tcp_proxy
      proxy:
        proxyVersion: ^1\.5.*
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.network.wasm
        typed_config:
          '@type': type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.config.filter.network.wasm.v2.Wasm
          value:
            config:
              configuration: |
                {
                  "debug": "false",
                  "stat_prefix": "istio",
                  "metrics": [
                     {
                       "name": "requests_total",
                       "dimensions": {
                          "destination_port": "destination.port",
                          "request_host": "request.host"
                       }
                     }
                  ]
                }
              root_id: stats_outbound
              vm_config:
                code:
                  local:
                    inline_string: envoy.wasm.stats
                runtime: envoy.wasm.runtime.null
                vm_id: stats_outbound
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.tcp_proxy
      proxy:
        proxyVersion: ^1\.5.*
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.network.wasm
        typed_config:
          '@type': type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.config.filter.network.wasm.v2.Wasm
          value:
            config:
              configuration: |
                {
                  "debug": "false",
                  "stat_prefix": "istio",
                  "metrics": [
                     {
                       "name": "requests_total",
                       "dimensions": {
                          "destination_port": "destination.port",
                          "request_host": "request.host"
                       }
                     }
                  ]
                }
              root_id: stats_outbound
              vm_config:
                code:
                  local:
                    inline_string: envoy.wasm.stats
                runtime: envoy.wasm.runtime.null
                vm_id: stats_outbound

**Comment by githubrotem** [comment]
Did you get any solution for destination_ip?
I always get "unknown"
