### ISSUE TITLE
istio-tracing status 0/1

### ISSUE THREAD

**Issue by hillbun** [istio/istio#23490]
**Bug description**

istio-1.4.7

some time after installation, istio-tracing status becomes 0/1

istio-system   istio-tracing-78548677bc-zwwpn             0/1     Running

kubectl describe pods istio-tracing-78548677bc-zwwpn   -n istio-system   
Name:           istio-tracing-78548677bc-zwwpn
Namespace:      istio-system
Priority:       0
Node:           node4/192.168.100.214
Start Time:     Sun, 03 May 2020 19:16:18 +0800
Labels:         app=jaeger
                pod-template-hash=78548677bc
                release=istio
Annotations:    prometheus.io/port: 14269
                prometheus.io/scrape: true
                sidecar.istio.io/inject: false
Status:         Running
IP:             10.233.105.139
Controlled By:  ReplicaSet/istio-tracing-78548677bc
Containers:
  jaeger:
    Container ID:   docker://6364516013d135078c42f9b504347cc1374eab324ef0ccd526453024c09a3b27
    Image:          docker.io/jaegertracing/all-in-one:1.14
    Image ID:       docker-pullable://jaegertracing/all-in-one@sha256:021aefafecbb5559078206996f1f4e8fc5907debab047f4fcc5c837689a66cfa
    Ports:          9411/TCP, 16686/TCP, 14250/TCP, 14267/TCP, 14268/TCP, 14269/TCP, 5775/UDP, 6831/UDP, 6832/UDP
    Host Ports:     0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/UDP, 0/UDP, 0/UDP
    State:          Running
      Started:      Mon, 04 May 2020 05:06:12 +0800
    Last State:     Terminated
      Reason:       Error
      Exit Code:    137
      Started:      Mon, 04 May 2020 05:05:17 +0800
      Finished:     Mon, 04 May 2020 05:06:10 +0800
    Ready:          False
    Restart Count:  57
    Requests:
      cpu:      10m
    Liveness:   http-get http://:14269/ delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:  http-get http://:14269/ delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      POD_NAMESPACE:               istio-system (v1:metadata.namespace)
      BADGER_EPHEMERAL:            false
      SPAN_STORAGE_TYPE:           badger
      BADGER_DIRECTORY_VALUE:      /badger/data
      BADGER_DIRECTORY_KEY:        /badger/key
      COLLECTOR_ZIPKIN_HTTP_PORT:  9411
      MEMORY_MAX_TRACES:           50000
      QUERY_BASE_PATH:             /jaeger
    Mounts:
      /badger from data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-zzvng (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  data:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  default-token-zzvng:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-zzvng
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                      From            Message
  ----     ------     ----                     ----            -------
  Warning  BackOff    5m36s (x940 over 4h41m)  kubelet, node4  Back-off restarting failed container
  Warning  Unhealthy  39s (x510 over 4h46m)    kubelet, node4  Readiness probe failed: HTTP probe failed with statuscode: 503

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by hillbun** [comment]
CPU resource of node that  istio-tracing is running become instable。

**Comment by hillbun** [comment]
I delete  istio-tracing-78548677bc-zwwpn and recreate again, and all problems become solved.

but after some times of running, it reproduce again

**Comment by objectiser** [comment]
@hillbun Can you try using a more recent version of Jaeger (e.g. 1.17)? `--set values.tracing.jaeger.tag=1.17`

**Comment by webjoel** [comment]
+1
