### ISSUE TITLE
Istio CNI plugin install with SELinux enabled not documented

### ISSUE THREAD

**Issue by jsalgado78** [istio/istio#23493]
**Describe the feature request**
Istio CNI plugin install and repair when SELinux is enabled and docker daemon is running with --selinux-enabled flag aren't documented.
install-cni container fails when it runs with SELinux enabled but SELinux requirements aren't documented to get Istio CNI plugin running without issues.

**Describe alternatives you've considered**
Add to Istio CNI plugin install documentation SELinux requirements to get Istio CNI plugin running without issues.

**Additional context**

**Comment by howardjohn** [comment]
Closing as a duplicate of https://github.com/istio/istio/issues/23605. Still valid though. Thanks!
