### ISSUE TITLE
Istio 0.4.0 Helm chart installation fails

### ISSUE THREAD

**Issue by eupestov** [istio/istio#2349]
When trying to install Istio 0.4 with the provided Helm chart on a fresh minikube or Tectonic sandbox:

$ cd istio-0.4.0/install/kubernetes/helm
$ helm install istio
Error: apiVersion "config.istio.io/v1alpha2" in Istio/charts/mixer/templates/istio-mixer.yaml is not available

$ helm install --set Istio.mixer_enabled=false istio
Error: release exiled-arachnid failed: namespaces "istio-system" not found

**Comment by eupestov** [comment]
Actually the first is a known issue of Helm https://github.com/kubernetes/helm/issues/2994

**Comment by AceHack** [comment]
Yeah, I had to run it twice to get it to work, but then it worked fine the 2nd time.

**Comment by Stono** [comment]
Yeah, 
I've modified my helm chart to be a 'two phased' run, with the first one having `--set init=true`, which just does the CRDs and then the second doing the rest

**Comment by sdake** [comment]
@eupestov The Istio community has taken responsibility for Helm charts as there are plans to use the helm charts in Istio to render any type of manifest needed.  To use master's version, this needs to merge first: https://github.com/istio/istio/pull/2242

**Comment by sdake** [comment]
cc @ZackButcher

**Comment by sbezverk** [comment]
@eupestov There is a PR almost merged which addresses certain ordering issues during istio installation. Unfortunately helm renders charts in non-deterministic order, like deployment may go first into the action before required CRD objects are created. 
Here is PR link: https://github.com/istio/istio/pull/2242

**Comment by sdake** [comment]
@eupestov you will also need this PR: https://github.com/istio/istio/pull/2461.  The patch is currently defective but should be relatively easy for the author to fix up.  Following the merge of that work, there will be full documentation submitted to istio.io for how to use the Helm charts.

Cheers
-steve

**Comment by sdake** [comment]
@eupestov The Helm charts are in good shape, minus missing the addons.  This can close in Istio 0.5.0.

**Comment by cmoulliard** [comment]
Deploying istio 0.5.1 also fails with helm version `v2.8.1`

```
 helm install ./istio --name istio --namespace=istio-system --debug
[debug] Created tunnel using local port: '55140'

[debug] SERVER: "127.0.0.1:55140"

[debug] Original chart version: ""
[debug] CHART PATH: /Users/dabou/Downloads/istio-0.5.1/install/kubernetes/helm/istio

Error: error unpacking initializer in istio: chart metadata (Chart.yaml) missing

ll istio 
total 32
-rw-r--r--@  1 dabou  staff   274B Feb 13 00:11 Chart.yaml
drwxr-xr-x@ 11 dabou  staff   352B Feb 13 00:11 charts
-rw-r--r--@  1 dabou  staff   904B Feb 13 00:11 requirements.yaml
drwxr-xr-x@  8 dabou  staff   256B Feb 13 00:11 templates
-rw-r--r--@  1 dabou  staff   5.4K Feb 13 00:11 values.yaml
```

**Comment by lqj679ssn** [comment]
I am facing the same issue as mentioned by @cmoulliard and @neeravarora  . Iam trying to deploy 0.5.1 with helm 2.8.1

**Comment by costinm** [comment]
This seems to be resolved in master and https://github.com/istio/istio/pull/3594, and is mostly 
compatible with istio.yaml.
