### ISSUE TITLE
istio Accessing External Services

### ISSUE THREAD

**Issue by dhineshbabuelango** [istio/istio#23523]
I am using istio 1.4.3, I have disabled the Envoy passthrough to external services, the mode is currently REGISTRY_ONLY but still I am able to access any services without service entry

kubectl get configmap istio -n istio-system -o yaml | grep -o "mode: REGISTRY_ONLY"
mode: REGISTRY_ONLY

**Comment by howardjohn** [comment]
any Service? or external ones like Google.com?

**Comment by dhineshbabuelango** [comment]
All external services. Since our cluster doesn't have internet access, we use a proxy server to reach internet. without creating service entry, I am able to reach the proxy server. Also to DB, KAFKA everything I am able to reach without creating service entry.

**Comment by howardjohn** [comment]
I cannot reproduce. Can you get a config dump from the client (https://github.com/istio/istio/wiki/Troubleshooting-Istio)?

**Comment by howardjohn** [comment]
Do you have a service entry for fp.dmz.app?

**Comment by dhineshbabuelango** [comment]
I have a service entry for fp.dmz.app in other namesapce and not in this namespace

**Comment by howardjohn** [comment]
That does not matter, by default you can access Service/ServiceEntry in any namespace. So this is working as expected

**Comment by dhineshbabuelango** [comment]
so there is no way to restrict the service entry to that particular namespace. Also there are DBs for which there is no service entry in any namespace and still it is working

**Comment by howardjohn** [comment]
See exportTo field: https://istio.io/docs/reference/config/networking/service-entry/#ServiceEntry

**Comment by dhineshbabuelango** [comment]
Thanks John but there are some DBs for which there is no service entry created in any namespace but still it is working and the istio configuration is REGISTRY_ONLY.

**Comment by howardjohn** [comment]
Please attach a config dump from the client and let me know what call specifically is failing. thanks!

**Comment by dhineshbabuelango** [comment]
I have uploaded the config dump by running the below command, the problem is I have updated the istio passthrough as REGISTRY_ONLY and now I dont have any service entry in the cluster still I am able to access all the DBs, servers outside of cluster and internet.
**Config Dump: kubectl exec $POD -c istio-proxy -- curl 'localhost:15000/config_dump' > config_dump.json**
[config_dump.json.gz](https://github.com/istio/istio/files/4584431/config_dump.json.gz)

**Comment by howardjohn** [comment]
This was resolved offline, seems like there was a stale ServiceEntry allowing access
