### ISSUE TITLE
openapi service spec integration

### ISSUE THREAD

**Issue by montmanu** [istio/istio#2352]
Are there any plans to support istio-native configuration using openapi specs? If not, would that be something the project is interested in supporting?

Our particular use case would be to effectively support a subset of the HTTP request-level validation features provided by google's [cloud endpoints](https://cloud.google.com/endpoints/) product. For example, given an service spec, does the current request:

1. match any specified paths?
2. match any of the HTTP methods supported by a matched path?
3. match a given operation's input requirements (if any)?

Not sure what the appropriate level of integration would be.. one potential idea would be to add an istioctl subcommand that accepted as input an openapi spec, and generated as output the istio-native route rules / policies? something like:

```bash
istioctl oapi2istio -f /path/to/openapi-spec.yaml -o /path/to/generated-rules.yaml
```

Also, are there any existing examples / documentation (other than [this](https://istio.io/docs/reference/config/mixer/adapters/svcctrl.html)) for the svcctrl adapter?

**Comment by xiaolanz** [comment]
Config format wise, we don't have a plan to support openAPI directly. We may use OpenAPI format inside our config to define API IDL but not the config itself. I expect "oapi2istio" to be a tool built on top of istio. 

@apicl can give you roadmap on supporting HTTP request validation thought API management.

@manlinl  may provide you more context on svcctrl adapter documentation.

**Comment by apicl** [comment]
During the development of Istio api management, we managed to translate openAPI spec into API config used to extract API attributes.

As the next step, we need to figure out how to fully support openAPI specs. Please join the API mgmt working group to contribute: https://github.com/istio/community/blob/master/WORKING-GROUPS.md#api-management
