### ISSUE TITLE
Consolidate Operator and Helm APIs

### ISSUE THREAD

**Issue by dgn** [istio/istio#23525]
Currently, the Helm values that are passed into the charts are different from the `IstioOperator.spec` which is used to install Istio when using the Operator. This issue proposes aligning the two APIs so that
- the operator implementation can be simpler. If no translations have to be made between fields and instead, they can just be passed through. This will greatly simplify the codebase.
- there will not be two competing APIs for installing Istio once we release helm3 support. 

The idea is to first get the Helm values to mirror the IstioOperator API as much as possible. The only problem I see are the generic K8s overlays which might have to be left as an operator-only feature, pointing users to a combination of `helm template | kubectl apply -k` for generic overlays when using helm directly. Once this is complete, we can develop the API further by iterating on the IstioOperator CRD, effectively now having a type-safe helm API. Eventually, we will then also remove the `values` and `unvalidatedValues` fields in the `IstioOperator.spec`.

Tasks to accomplish this (note that these are fairly fine-grained to avoid huge PRs - every change in the charts will need changes in the operator code, too):
- Implement `components.<name>.enabled` fields in helm charts
- Implement `components.<name>.k8sSettings` fields in helm charts
- Implement remainder of `<components.<name>.<field>` fields in helm charts
- Document usage of helm && kustomize for overlays
- Implement automation that verifies that all helm values are present in the IstioOperator CRD

Relevant RFC: https://docs.google.com/document/d/1OZZknerqlkQRNCsfn8Mr0b4zMGRcnHepsuSNr2F8ZDc/edit#

**Comment by howardjohn** [comment]
> Implement components.<name>.enabled fields in helm charts

Why not just change the operator API to have `pilot.xyz` instead of `components.pilot.xyz`? Then the helm api doesn't change. This makes more sense to me now that we have so few components now, and there is not a `components` vs `values` split anymore with your proposal (right?)

**Comment by ostromart** [comment]
I'd recommend keeping the path as is - it's a minor improvement at the hefty cost of an API change (we'd have to deprecate, possibly translate etc.) Also, I'm not sure this would actually be the right move: components are a list with a common type, we'd have to change to a strange oneof with other unrelated items to remove the components subpath.

**Comment by dgn** [comment]
> > Implement components..enabled fields in helm charts
> 
> Why not just change the operator API to have `pilot.xyz` instead of `components.pilot.xyz`? Then the helm api doesn't change. This makes more sense to me now that we have so few components now, and there is not a `components` vs `values` split anymore with your proposal (right?)

I agree that it makes more sense, but I think it should be tackled once we have alignment. IMO we should strive to get the helm API on par with what we have in IstioOperator first, and then make these changes. We can still get them in before we release the helm charts, but changing the CRD is IMO the bigger, more risky change. Ideally, we can create a new CRD version as part of 1.7 and already deprecate the current one, and then move things over with 1.8

**Comment by howardjohn** [comment]
I am not sure changing the helm api which has been stable since istio 0.x to match the alpha operator API which is brand new is the right compromise, especially because I don't think the operator API is in a great state today given the istiod refactorings, etc

**Comment by ostromart** [comment]
I think we are talking here primarily about the k8s spec stuff which needs a cleanup in values as it's quite inconsistent and not aligned with native k8s. If we agree that  [KubernetesResourcesSpec](https://github.com/istio/api/blob/8c8385e634758fcfc0589e1c0872e7894ba2c951/operator/v1alpha1/component.proto#L104)  is what we want for both cases then helm values API has to change anyway for that part. Then it seems to me there's little difference for Helm users to write components.pilot.k8s.newThing vs. pilot.k8s.newThing. otoh to drop components, we'd have to change operator API for the sake of saving a path element. 
If we don't agree that KubernetesResourcesSpec is what we want then I'm not sure what we're proposing as the basis.
