### ISSUE TITLE
How to disable all metrics 1.5.2 ?

### ISSUE THREAD

**Issue by previousdeveloper** [istio/istio#23529]
**We use Istio 1.5.2  with a minimal profile.**

**We want to disable all proxy and service metrics for the benchmark. We changed telemetry v2 IstioOperator value to false. But we still show metrics in the Kiali console**

**telemetry:
      enabled: false
      v1:
        enabled: false
      v2:
        enabled: false**

Istio
**client version: 1.5.1
control plane version: 1.5.2
data plane version: 1.5.2 (170 proxies), 1.5.1 (89 proxies)**

Kubernetes
**v1.12.7**

**We installed it with IstioOperator**

**Comment by howardjohn** [comment]
That should disable all telemetry. Can you verify you have no `istio-telemetry` pod and there are no EnvoyFilters?

See:
```
$ kubectl get envoyfilters  -n istio-system
NAME                        AGE
metadata-exchange-1.4       26m
metadata-exchange-1.5       26m
metadata-exchange-1.6       26m
metadata-exchange-1.7       26m
stats-filter-1.4            26m
stats-filter-1.5            26m
stats-filter-1.6            26m
stats-filter-1.7            26m
tcp-metadata-exchange-1.5   26m
tcp-metadata-exchange-1.6   26m
tcp-metadata-exchange-1.7   26m
tcp-stats-filter-1.5        26m
tcp-stats-filter-1.6        26m
tcp-stats-filter-1.7        26m
```

That should return empty if telemetry is properly disabled

**Comment by previousdeveloper** [comment]
I have still EnvoyFilters, but I don't have `istio-telemetry` pod. 

```
istio-ingressgateway-mghmh    1/1     Running   0          2d6h
istio-ingressgateway-qldrz    1/1     Running   0          2d6h
istio-ingressgateway-s5rsh    1/1     Running   0          2d6h
istio-ingressgateway-s6xbq    1/1     Running   0          2d6h
istio-ingressgateway-spv7h    1/1     Running   0          2d6h
istio-ingressgateway-w9tqf    1/1     Running   0          2d6h
istiod-d777776f4-4cj9z        1/1     Running   0          30h
istiod-d777776f4-5mllg        1/1     Running   0          30h
istiod-d777776f4-5zdlc        1/1     Running   0          30h
istiod-d777776f4-f4rvh        1/1     Running   0          30h
istiod-d777776f4-xz8qj        1/1     Running   0          30h
kiali-5f5755cc7b-8l595        1/1     Running   0          3d1h
prometheus-754484f8f6-pjxxv   2/2     Running   0          2d6h
```

```
metadata-exchange-1.4       11d
metadata-exchange-1.5       11d
stats-filter-1.4            11d
stats-filter-1.5            11d
tcp-metadata-exchange-1.5   11d
tcp-stats-filter-1.5        11d
```

**Comment by howardjohn** [comment]
`~/istio/istio-1.5.2/bin/istioctl manifest generate --set values.telemetry.v2.enabled=false` successfully shows no Envoyfilters. Is that the same as you were doing?

You can manually delete all of those as well but you should be able to get it working through the automation

**Comment by douglas-reid** [comment]
I'm gonna close this as the question appears to have been answered. If there are still lingering questions, please follow-up on discuss.istio.io.
