### ISSUE TITLE
istio-1.5.2 can not deploy istio-ingressgateway from deployment to daemonset

### ISSUE THREAD

**Issue by hillbun** [istio/istio#23524]
**Bug description**

I install  istio-1.5.2 with

./bin/istioctl manifest apply --set profile=demo \
--set values.gateways.istio-egressgateway.enabled=false \
--set values.gateways.istio-ingressgateway.type=NodePort \
--set values.gateways.istio-ingressgateway.sds.enabled=true \
--set values.pilot.env.PILOT_HTTP10=1 \
--set values.global.proxy.accessLogFile="/dev/stdout" \
--set values.global.proxy.accessLogEncoding="JSON" \
--set values.global.mtls.auto=false

running status  of istio-ingressgateway  is up ok.

istio-ingressgateway-6b9956f448-9gpn6   1/1     Running   

after installation, I change type of istio-ingressgateway from Deployment to DaemonSet

apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
    release: istio
  name: istio-ingressgateway
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
      istio: ingressgateway

But running status is down.

istio-ingressgateway-68bc4fc9f5-v75bm   0/1     ContainerCreating

error details:

Events:
  Type     Reason       Age                  From               Message
  ----     ------       ----                 ----               -------
  Normal   Scheduled    7m2s                 default-scheduler  Successfully assigned istio-system/istio-ingressgateway-gtn97 to node3
  Warning  FailedMount  49s (x11 over 7m1s)  kubelet, node3     MountVolume.SetUp failed for volume "istio-token" : failed to fetch token: the server could not find the requested resource
  Warning  FailedMount  26s (x3 over 4m59s)  kubelet, node3     Unable to mount volumes for pod "istio-ingressgateway-gtn97_istio-system(aec0b825-0926-491f-8dc1-09fcd08bd78a)": timeout expired waiting for volumes to attach or mount for pod "istio-system"/"istio-ingressgateway-gtn97". list of unmounted volumes=[istio-token]. list of unattached volumes=[istiod-ca-cert podinfo ingressgatewaysdsudspath istio-token ingressgateway-certs ingressgateway-ca-certs istio-ingressgateway-service-account-token-pfx49]

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by thiagoleitetr** [comment]
any plans to make it istio-ingressgateway available as deamonset?
