### ISSUE TITLE
"istioctl proxy-status" to use new debug/troubleshooting API

### ISSUE THREAD

**Issue by esnible** [istio/istio#23538]
This Issue tracks getting _istioctl_ to use the mechanism of https://github.com/istio/istio/issues/23537 instead of K8s Exec.

This includes explicitly specifying the endpoint (e.g., non-Kubernetes), using perhaps `--controlPlaneAddr <url>` or `--controlPlaneHost <ip:port>` to point to Istio exposed via HTTPS or SSH tunnel to in-cluster gRPC endpoint.

This also includes implicitly finding the endpoint.  For example, `istioctl proxy-status details-123456.default`, where default is under the `canary` revision control plane.

**Comment by therealmitchconnors** [comment]
I recommend we use Envoy's CSDS service to structure this API.  This would make us interoperable with tooling built for generic envoy. https://www.envoyproxy.io/docs/envoy/latest/api-v2/service/status/v2/csds.proto

**Comment by esnible** [comment]
@therealmitchconnors 
- Are you proposing someone from UX implement the CSDS server-side support or someone from Networking?
- Are you proposing this for 1.7 or 1.8?

**Comment by esnible** [comment]
Resolved by https://github.com/istio/istio/pull/25344
