### ISSUE TITLE
Debug / Troubleshooting API for istiod

### ISSUE THREAD

**Issue by esnible** [istio/istio#23536]
The current istioctl implementation uses K8s "exec" into istiod to GET /debug/X.

This doesn't work in multitenant or multicluster.  It requires too many permissions in the vanilla case.  It requires istioctl to know how many instances of istiod are running in a revision.

This work item is to replace the 2019 proposals and get a new approved proposal
https://docs.google.com/document/d/1g_ZGOtSJ-DqTlpkiEJHTK_U9JvvTnco3h6rsDK-sOvA/edit
https://docs.google.com/document/d/11P6OXlITExJvFqzsWfFu9WhFLjY6uqOcCUKqPVgSSoc/edit

**Comment by esnible** [comment]
The API MUST include the current GET /debug/* functionality used by istioctl
The API MUST present unsharded results
The API SHOULD include the pod /config_dump functionality used by istioctl
The API MUST work with remote control plane (e.g. multicluster) and VMs.

This means we need to be able to find the control plane, instead of just assuming all control planes are in istio-system istiod pods.

Currently the control plane address is passed to the proxy as an argument, that isn’t good enough.

**Comment by howardjohn** [comment]
@esnible how are you going to deal with the cases that currently require connecting to all Pilots?

**Comment by esnible** [comment]
The details will be in the linked document.  Probably there will be an internal API for per-shard, and a public API that gathers the current shard data with the sibling shards' data.

**Comment by howardjohn** [comment]
How are you even going to call Pilot at all from Istioctl? port-forward?

**Comment by esnible** [comment]
RFC at https://docs.google.com/document/d/1u0KxDY9R3-nwuAjccRRyefV3TToSCWqei3TMLVm1uSA/edit#

@howardjohn 
We don't want to port-forward because we want to be able to run in situations where the Istio user doesn't have rights to inventory pods and port-forward into the Istio control plane namespace.  We want a single Service or API that offers an unsharded view of Pilot.

**Comment by esnible** [comment]
@costinm proposes _istioctl_ use XDS Event reporting https://docs.google.com/document/d/1X7DmkP10x4nEcTGpikxmvLbBTTK59B0WL3liQzVy8Ms/edit# instead of @therealmitchconnors 's proposal.

**Comment by esnible** [comment]
Currently we have
an RFC from mitch on using Kubernetes API aggregation for the API
… but also a XDS event reporting mechanism proposed by costin that may be sufficient.  It will be alpha in 1.7.
The API MUST fully function as replacement of the current GET /debug/* functionality used by istioctl
The API MUST offer unsharded results
The API MUST work with remote control plane (multicluster and Central Istiod) and VMs.

**Comment by esnible** [comment]
Making this P2.  We may raise it for 1.8, but for 1.7 it is not a priority.

**Comment by howardjohn** [comment]
Note that while this new feature is not complete, the /debug/ API is now properly authenticated as of https://github.com/istio/istio/pull/31338

**Comment by nrjpoddar** [comment]
@howardjohn what's the impact of securing the debug API on istio.io documentation examples using istioctl and on users relying on istioctl commands?

**Comment by howardjohn** [comment]
Istioctl will authenticate to Istiod, so it should not be user facing
change for users of Istioctl. The only users impacted are users that are
directly sending HTTP requests to Istiod's pods (note - it must be the pod,
not Service, as we don't expose the port). Unfortunately Kiali is one of
these users, but we are working with them to update Kiali to query with
proper auth.

**Comment by howardjohn** [comment]
This is implemented and used by `istioctl x internal-debug`
