### ISSUE TITLE
Error reading current istio version on upgrade

### ISSUE THREAD

**Issue by michaeldduffield** [istio/istio#23531]
**Bug description**

Having followed the instructions for setting up an egress gateway with SNI proxy (https://archive.istio.io/v1.4/docs/tasks/traffic-management/egress/wildcard-egress-hosts/#setup-egress-gateway-with-sni-proxy), attempting to upgrade istio from 1.4.6 to 1.5.2 (using istioctl) results in the following error:

```
Error: failed to read the current Istio version, error: failed to retrieve Istio control plane version, error: tag not found in image: nginx, differrent versions of containers in the same pod:
```

**Expected behavior**

Upgrade should not fail with error

**Steps to reproduce the bug**
- Install istio 1.4.6
- Add egress gateway with SNI proxy (https://archive.istio.io/v1.4/docs/tasks/traffic-management/egress/wildcard-egress-hosts/#setup-egress-gateway-with-sni-proxy)
- Attempt to upgrade using istioctl

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

`istioctl version --remote`
```
client version: 1.5.2
citadel version: 1.4.6
egressgateway version: 1.4.6
egressgateway-with-sni-proxy version: 
galley version: 1.4.6
ingressgateway version: 1.4.6
nodeagent version: 
nodeagent version: 
nodeagent version: 
pilot version: 1.4.6
policy version: 1.4.6
sidecar-injector version: 1.4.6
telemetry version: 1.4.6
data plane version: 1.4.6 (6 proxies)
```
`kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.4-gke.10", GitCommit:"302b55804ee4a09c6ad5be81a380a3f333f72fcf", GitTreeState:"clean", BuildDate:"2020-04-14T17:30:11Z", GoVersion:"go1.13.8b4", Compiler:"gc", Platform:"linux/amd64"}
```
**How was Istio installed?**
Initially with helm, but then migrated to istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

**Comment by elfinhe** [comment]
Did you happen to have nginx installed in the same namespace with Istio?

**Comment by michaeldduffield** [comment]
Yes. The instructions setup a custom egressgateway (in the istio-system namespace) with an additional nginx container in the pod (latest version of instructions [here](https://istio.io/docs/tasks/traffic-management/egress/wildcard-egress-hosts/#setup-egress-gateway-with-sni-proxy))
