### ISSUE TITLE
traces w/ unexpected zone tag value

### ISSUE THREAD

**Issue by montmanu** [istio/istio#2353]
## Description

When viewing traces in jaeger, I've noticed the `zone` tag does not contain the expected value.. currently, the value always seems to be `AvailabilityZone couldn't find the given cluster node`, when `us-east1/d` was expected in this case.

## Environment

<details>
  <summary><code>istioctl version</code></summary>
  <pre><code>Version: 0.4.0
GitRevision: 24089ea97c8d244493c93b499a666ddf4010b547-dirty
GitBranch: 6401744b90b43901b2aa4a8bced33c7bd54ffc13
User: root@cc5c34bbd1ee
GolangVersion: go1.8</code></pre>
</details>

<details>
  <summary><code>kubectl version</code></summary>
  <pre><code>Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:28:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.4-gke.1", GitCommit:"04502ae78d522a3d410de3710e1550cfb16dad4a", GitTreeState:"clean", BuildDate:"2017-12-08T17:24:53Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}</code></pre>
</details>

## Steps to reproduce

1. Deploy istio, jaeger, bookinfo to GKE cluster

```bash
kubectl apply -f install/kubernetes/istio.yaml
kubectl apply -n istio-system -f https://raw.githubusercontent.com/jaegertracing/jaeger-kubernetes/master/all-in-one/jaeger-all-in-one-template.yml
kubectl apply -f <(istioctl kube-inject -f samples/bookinfo/kube/bookinfo.yaml)
kubectl apply -f samples/bookinfo/kube/route-rule-all-v1.yaml
```

2. Generate load on the productpage service

```bash
export GATEWAY_URL=$(kubectl get ing/gateway -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
watch -c curl -o /dev/null -s -w "%{http_code}" http://${GATEWAY_URL}/productpage
```

3. port-forward jaeger UI

```bash
kubectl port-forward -n istio-system $(kubectl get pod -n istio-system -l app=jaeger -o jsonpath='{.items[0].metadata.name}') 16686:16686
```

4. [open jaeger UI in brower](http://localhost:16686)

5. Navigate to a recent trace, expand trace tags, inspect `zone` tag value

![screen shot 2017-12-29 at 3 56 59 pm](https://user-images.githubusercontent.com/639255/34447370-34f6fef8-ecb1-11e7-9eea-d7139dfde7d0.png)

**Comment by rshriram** [comment]
cc @liamawhite who has been working on the AZs.
Is this the value of the service-zone flag from Envoy?

**Comment by montmanu** [comment]
not sure.. looks like thats what the DiscoveryService returns when it can't determine the AZ..

https://github.com/istio/istio/blob/b25c2e9d9a1ebbbf6d078a281b6f7ba4b5cd0032/pilot/proxy/envoy/discovery.go#L595 

https://github.com/istio/istio/blob/d1c939b5d6a23c496e0c1a9a1a02419b3837c93d/pilot/proxy/envoy/discovery_test.go#L841-L844

**Comment by rshriram** [comment]
Are your nodes annotated with teh availability zone information? IF not, this won't show up.

**Comment by rshriram** [comment]
This definitely seems like a bug.. @liamawhite ^^^

**Comment by liamawhite** [comment]
That is correct, the is the error that it returns if it can't work it out. We haven't been able to fully test this specific feature due to infrastructure limitations but it shouldn't be assigning that in the case of an error. I'll create a PR to fix that specific issue.

In terms of labels not being picked I'm not sure why that isnt working. I'll dig into it a bit more.

**Comment by montmanu** [comment]
Thanks!

**Comment by liamawhite** [comment]
@montmanu When merged the second PR will have it setting correctly, verified it manually.
