### ISSUE TITLE
Debug / Troubleshooting gRPC and HTTP endpoint for Istiod

### ISSUE THREAD

**Issue by esnible** [istio/istio#23537]
This will replace /debug/* endpoint in current Istiod.

This work item is to implement the API of https://github.com/istio/istio/issues/23536

**Comment by howardjohn** [comment]
> This will replace /debug/* endpoint in current Istiod.

With a gRPC endpoint? Please support http - its a must have for debugging

**Comment by esnible** [comment]
@howardjohn Agreed.  At the previous UX meeting, @liamawhite suggested we implement gRPC with bindings to additionally expose as HTTP.

**Comment by liamawhite** [comment]
For reference https://github.com/googleapis/googleapis/blob/master/google/api/http.proto#L45

**Comment by esnible** [comment]
Setting this to P>2 priority because the plan for 1.7 is to use XDS Events (e.g. https://github.com/istio/istio/pull/23833 )
