### ISSUE TITLE
`EgressRule` not applied to `externalName` for services of type `ExternalName`

### ISSUE THREAD

**Issue by montmanu** [istio/istio#2355]
## Description

When using services of type `ExternalName` and matching `EgressRule` configured for the external host name, Envoy always returns a 404 if using cluster's DNS. Would expect the `EgressRule` to be applied to service's corresponding `externalName`.

## Environment

<details>
  <summary><code>istioctl version</code></summary>
  <pre><code>Version: 0.4.0
GitRevision: 24089ea97c8d244493c93b499a666ddf4010b547-dirty
GitBranch: 6401744b90b43901b2aa4a8bced33c7bd54ffc13
User: root@cc5c34bbd1ee
GolangVersion: go1.8</code></pre>
</details>

<details>
  <summary><code>kubectl version</code></summary>
  <pre><code>Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:28:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.4-gke.1", GitCommit:"04502ae78d522a3d410de3710e1550cfb16dad4a", GitTreeState:"clean", BuildDate:"2017-12-08T17:24:53Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}</code></pre>
</details>

## Steps to reproduce

1. Deploy istio, bookinfo, `ExternalName` service, `EgressRule` to GKE cluster

```bash
kubectl apply -f install/kubernetes/istio.yaml
export CLUSTER_IPS=$(gcloud container clusters describe $CLUSTER_NAME --zone=$CLUSTER_ZONE --format='csv("clusterIpv4Cidr","servicesIpv4Cidr")' | tail -n1)
export APPLE_IPS='17.142.160.59/32,17.172.224.47/32,17.178.96.59/32'
kubectl apply -f <(istioctl kube-inject kube-inject --includeIPRanges=$CLUSTER_IPS,$APPLE_IPS -f samples/bookinfo/kube/bookinfo.yaml)
kubectl apply -f samples/bookinfo/kube/route-rule-all-v1.yaml
cat <<'EOF' | kubectl apply -f -
---
kind: Service
apiVersion: v1
metadata:
  name: appl
  namespace: default
spec:
  type: ExternalName
  externalName: apple.com
---
apiVersion: config.istio.io/v1alpha2
kind: EgressRule
metadata:
 name: appl-egress-rule
 namespace: default
spec:
  destination:
    service: apple.com
  ports:
    - port: 80
      protocol: http
    - port: 443
      protocol: https
EOF
```

2. Confirm bookinfo works as expected

```bash
export GATEWAY_URL=$(kubectl get ing/gateway -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
curl -vLo /dev/null http://${GATEWAY_URL}/productpage
```

3. Connect to any bookinfo pod

```bash
export PRODUCTPAGE_POD=$(kubectl get pods -l app=productpage -o jsonpath='{.items[0].metadata.name}')
kubectl exec -it $PRODUCTPAGE_POD -c productpage sh
```

4. Install networking utilities

```bash
apt-get update && apt-get install -y curl dnsutils
```

5. Test `ExternalName` DNS resolution

```bash
# expect A records w/ addresses included in above $APPLE_IPS CIDR
dig apple.com
# expect CNAME, A records matching previous dig output
dig appl.default.svc.cluster.local
```

6. Send test requests to each host

```bash
# expect 200, after redirect
curl -vLo /dev/null http://apple.com/
# expect 200, after redirect; getting 404s
curl -vLo /dev/null http://appl.default.svc.cluster.local/
```

**Comment by mandarjog** [comment]
This is a missing feature. I am planning on implementing it this month.

**Comment by rshriram** [comment]
I think we don't parse ExternalName services anymore. We used to, when we had a dedicated Egress Proxy. When EgressRules came in, we no longer needed these ExternalName services.

The problem is that compared to standard Kubernetes services, External name services require inline DNS resolution and a separate processing path in Pilot. Its not terribly hard to implement this, but the question is, do we need this? 

@montmanu, if you can access the external service with just the EgressRule, why would you want to create an external name service as well ?

**Comment by montmanu** [comment]
it simplifies how we manage configuration of destination addresses for external dependencies.. the application can simply refer to the cluster name without worrying about which host / address the cluster name resolves to. e.g., we can change what the cluster address resolves to without changing the running application's deployment / source. also less to update if / when that external dependency runs within the same cluster.

**Comment by montmanu** [comment]
so, may just be a misunderstanding on my part, but i thought that to enable features like RouteRule / DestinationPolicy targeting external services, an EgressRule was required.

**Comment by rshriram** [comment]
The two are mutually exclusive. If your application is using the internal name, i.e. app1.default.svc.cluster.local, then your route rules will be using the internal names as well. It would be like any other kubernetes service.

IF your application is using the externally visible names, like google.com, apple.com, then you need to use EgressRules to register these external services in Istio.

**Comment by montmanu** [comment]
Ah, got it. Thanks, will give that a try and follow up with any feedback.

**Comment by GregHanson** [comment]
@montmanu any followup questions on this or good to close?

**Comment by montmanu** [comment]
sorry, meant to follow up a while back.. we simply switched to consuming the external host name directly (no k8s Service abstraction) within the application in conjunction with an EgressRule.. that seemed to have resolved the networking issue.

**Comment by andrew-dinunzio** [comment]
I would like to see support for ExternalName services again. I have an external redis cache that I'd like to access, but EgressRules either only support HTTP/HTTPS (not the redis protocol) or (if I use a TCP EgressRule), I'd need to know the IP address/CIDR block. I don't have any stable IPs / CIDR block ranges for my redis cache - I have to access it by its DNS name.
