### ISSUE TITLE
Add k8s version compatibility check to install

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#23557]
This was added in https://github.com/istio/istio/commit/308fb59bf5208463db9791d923a20dd9bb52e937 and accidentally removed at some point in a refactoring

https://github.com/istio/istio/pull/22742 is very similar to this implementation

**Comment by sdake** [comment]
Newer Issue, Newer PR: 22742

**Comment by sdake** [comment]
I would much prefer to revive the code in 308fb59 as it has been backported into 1.5 already and has more field testing. If that isn't viable, I can proceed with https://github.com/istio/istio/pull/22742

**Comment by sdake** [comment]
@elfinhe if you have time, can you take a look at reviving https://github.com/istio/istio/pull/20391. If you don't have time, please let me know.

Cheers
-steve

**Comment by elfinhe** [comment]
probably won't get time this week.

And we've switched to use the K8S restful client, things may be different. This definitely need some time for testing.
