### ISSUE TITLE
istio security best practices: post 1.5

### ISSUE THREAD

**Issue by quixoticmonk** [istio/istio#23560]
**The best practice details mention isolating istio components by namespaces including citadel.
**
Document  : https://istio.io/docs/ops/best-practices/security/
If I am not wrong, istiod now handles the citadel and some other components in istio. So is the current best practices applicable for istio 1.5 onwards ? Are there any updated documentation that we can refer ?
**Affected product area **

[X ] Docs
[X ] Installation
[X] Security

**Comment by myidpt** [comment]
Yes, this doc needs update. Thanks for capturing it.

**Comment by justinpettit** [comment]
Thanks for the report.  This was addressed in the following PR: https://github.com/istio/istio.io/pull/7398
