### ISSUE TITLE
istioctl manifest: show likely keys in case of key failure.

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#23565]
If a user sets an incorrect key either on the command line or in the profile, istioctl does not offer any  useful help.

For example.
```bash
$ istioctl manifest generate --set Values.global.proxy.enableCoreDump=true
Error: failed to generate tree from the set overlay, 
error: bad path=value: Values.global.proxy.enableCoreDump=true
```

It would be useful to say
```bash
$ istioctl manifest generate --set Values.global.proxy.enableCoreDump=true
Error: failed to generate tree from the set overlay, 
error: bad path=value: Values.global.proxy.enableCoreDump=true
did you mean: values.global.proxy.enableCoreDump=true ?
```
This can be done is many different ways.
Generate and maintain a list of *all* keys at build time and do a nearest match in case of failure. This takes care of typos and incorrect capitalization like the example above. 

@richardwxn @ostromart

**Comment by howardjohn** [comment]
`kubectl` does this - 
```
$ kubectl gt
Error: unknown command "gt" for "kubectl"

Did you mean this?
        set
        get
        cp

Run 'kubectl --help' for usage.
```

we can probably follow whatever algorithm they use

**Comment by esnible** [comment]
This may be a duplicate of https://github.com/istio/istio/issues/22286 which is about "value failure" instead of "key failure".  Underlying probably may be the same.  Should I close one?  If we keep both open, I suggest whomever does this one look at solving both problems together.

**Comment by mandarjog** [comment]
@esnible agreed we should solve both issues.
