### ISSUE TITLE
Provide a shim to convert OOP adapter to use Envoy native API

### ISSUE THREAD

**Issue by bianpengyuan** [istio/istio#23580]
As part of efforts for Mixer deprecation, we need a way for current out of process (OOP) adapter user to migrate off Mixer template based API. The long term solution is to convert out of process adapter to a Wasm filter. However this process could be time consuming and requires Wasm runtime to be production ready, which is not guaranteed to happen on 1.7.

As an interim step, a shim could be provided so that OOP adapter user could compile that with their adapter, which:

- Consumes native Envoy extern-authz API for policy check and access log API for telemetry.
- Is generated based on given Mixer instances/handlers/template/rules/adapter.
- Does not support dynamic configuration.

Guide will be provided on istio.io about how to migrate off out of process adapter to use this shim generation tool. We also need to be very clear that this shim generator should only be considered as a short term solution for transition to Wasm and will only be supported until Wasm production ready release or the release after that.

@mandarjog @douglas-reid

**Comment by douglas-reid** [comment]
Remaining bits:

- [ ]  integration tests
- [ ] documentation for 1.7 AND 1.8 usage

**Comment by bianpengyuan** [comment]
Also one more item is to run a long running perf test with shim enabled.
