### ISSUE TITLE
Mirror/shadowing feature produces wrong cluster name

### ISSUE THREAD

**Issue by christian-posta** [istio/istio#2359]
Istio Mirroring rules create outbound clusters that don't match any cluster names because they're not created correctly. Outbound clusters start with out.* and have service/version identifiers appended. When these mirror rules fail, they affect the main request thread, not just failing on the shadow request. 

Related to: https://github.com/istio/istio/pull/1314

**Comment by rshriram** [comment]
Fixed by #2360
