### ISSUE TITLE
FR: Add span for Envoy proxy time

### ISSUE THREAD

**Issue by tbiddu** [istio/istio#23600]
We are evaluating Jaeger UI to do distributed tracing and istio for service mesh. Ideally it should trace all istio proxy timing as well. But Jaeger does not show the istio proxy tracing span.

I am not finding any settings which will show istio time span as well. Any guidance will do.

By changing EnvoyFilter I could add x-request-id header in all the requests. But it shows always one span - though I dont think it will work as mentioned in document there is no way to correlate between inbound and outbound connection. So stitching even app request will not work.

**Comment by douglas-reid** [comment]
@tbiddu are you asking for a span for the proxy time itself?

What we have:
- span (observed by proxy)
|- span (application)

What it sounds like you are hoping for:
- span (observed by proxy)
|- span (envoy handling)
|- span (application)

Is that correct?

**Comment by tbiddu** [comment]
You are correct.

**Comment by douglas-reid** [comment]
not stale
