### ISSUE TITLE
securityContext option to install istio-cni plugin

### ISSUE THREAD

**Issue by jsalgado78** [istio/istio#23605]
**Describe the feature request**

istio-cni plugin install / repair requires permission to read / write on directories /opt/cni/bin and /etc/cni/net.d but no securityContext option is defined to configure a SELinux label, for example. install-cni container fails when SELinux is enabled because of it requires high permission level to run but no securityContext is implemented and parameterized to define security options when istio-cni is installed.

**Describe alternatives you've considered**

Define optional securityContext section in istio-cni charts and support to define these values from an IstioOperator file or --set flag when install istio-cni.

**Comment by JimmyCYJ** [comment]
@justinpettit Could you take a look?

**Comment by jsalgado78** [comment]
I define the following SELinux CIL on RHEL to allow istio-cni container install or repair CNI plugin. I patch istio-cni-node daemonset later to use securityContext:

echo '(block ps-istio-cni
              (blockinherit container)
              (allow process var_lib_t ( dir ( getattr search open read lock ioctl ))) 
              (allow process var_lib_t ( file ( getattr read ioctl lock open  ))) 
              (allow process var_lib_t ( sock_file ( getattr read open  ))) 
              (allow process var_lib_t ( dir ( open read getattr lock search ioctl add_name remove_name write ))) 
              (allow process var_lib_t ( file ( getattr read write append ioctl lock map open create  ))) 
              (allow process var_lib_t ( sock_file ( getattr read write append open  ))) 
              (allow process var_lib_t ( dir ( open read getattr lock search ioctl add_name remove_name write ))) 
              (allow process var_lib_t ( file ( getattr read write append ioctl lock map open create  ))) 
              (allow process var_lib_t ( sock_file ( getattr read write append open  ))) 
              (allow process container_var_lib_t ( dir ( open read getattr lock search ioctl add_name remove_name write ))) 
              (allow process container_var_lib_t ( file ( getattr read write append ioctl lock map open create  ))) 
              (allow process container_var_lib_t ( sock_file ( getattr read write append open  ))) 
              (allow process bin_t ( dir ( open read getattr lock search ioctl add_name remove_name write ))) 
              (allow process bin_t ( file ( getattr read write append ioctl lock map open create  ))) 
              (allow process bin_t ( sock_file ( getattr read write append open  ))) 
              (allow process etc_t ( dir ( open read getattr lock search ioctl add_name remove_name write ))) 
              (allow process etc_t ( file ( getattr read write append ioctl lock map open create rename setattr unlink ))) 
              (allow process etc_t ( sock_file ( getattr read write append open  )))
              (allow process usr_t ( dir ( write remove_name add_name ))) 
              (allow process usr_t ( file ( unlink create write rename ))) 
              (allow process http_port_t ( tcp_socket (name_connect )))
              (allow process unlabeled_t ( process (fork)))
              (allow process unlabeled_t ( tcp_socket (read write create )))
              (allow process container_runtime_t ( fd ( use )))             
              (allow process container_file_t ( dir ( search )))             
              )' > /tmp/ps-istio-cni.cil

semodule -i /tmp/ps-istio-cni.cil /usr/share/udica/templates/base_container.cil

kubectl get daemonset istio-cni-node -n kube-system -o yaml > /tmp/patch-cni.yml

cat <<EOF >/tmp/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- /tmp/patch-cni.yml

patchesStrategicMerge:
- |-
  kind: DaemonSet
  apiVersion: extensions/v1beta1
  metadata:
    namespace: kube-system
    name: istio-cni-node
  spec:
    template:
      spec:
         securityContext:
            seLinuxOptions:
               type: ps-istio-cni.process

EOF

kustomize build /tmp | kubectl apply -f -

It could be interesting define an optional securityContext parameter in istio-cni installer when SELinux is enabled.
