### ISSUE TITLE
tpath code cleanup part2

### ISSUE THREAD

**Issue by ostromart** [istio/istio#23615]
We made a good start to cleaning up tpath in 1.6 but some things are still outstanding:
- Mixing reflect with type assertions to discover types. The latter leads to code duplication, where you have essentially identical code to handle map[string]interface{} vs. map[interface{}]interface{}
- Plenty of places where code can panic. You've discovered a couple, there are probably more. The solution is probably to use more helper functions in util that use reflect and are very careful about using that panicky reflect package.
- The code coverage is incomplete. We have reasonable state coverage for the positive test cases but very little for negative. Adding this tests will also reveal that the error reporting is very unhelpful in many cases.
- A particularly common and unhelpful message is `cannot unmarshal string into Go value of type map[string]json.RawMessage` which happens when the wrong field type is passed in.
- GetPathContext has an unfortunate feature where non-existing leaf nodes for maps are automatically created. This is useful to support a more intuitive syntax in k8s.overlays.path, but it makes that function not generally useful for tree traversal. Creating non-existing nodes when requested to do so is fine - this odd behavior is not and should be cleaned up.
- Related to the above, tpath.Find has a separate, parallel implementation for this reason. It could be eliminated if the above is fixed.
- Two implementations of Go struct tree traversal still exist: in tpath/struct.go and validate/validate.go. Should be consolidated.

**Comment by Azanul** [comment]
@ostromart is this a help wanted issue?

**Comment by howardjohn** [comment]
At this point I think this codebase is mostly frozen and we would probably prefer that no changes are made. I think this can probably just be closed. 

If you aren't familair we have this label: https://github.com/istio/istio/issues?q=is%3Aopen+is%3Aissue+label%3A%22community%2Fhelp+wanted%22 to find ones where help is wanted, and we plan to add a bunch more in the coming weeks
