### ISSUE TITLE
Plugin flag for istioctl manifest/apply

### ISSUE THREAD

**Issue by ostromart** [istio/istio#23627]
A couple of users have requested some way to customize installs without forking the code/charts. Some examples would be to generate custom resources based on the value of IstioOperator CR, or modify existing resources based on some external query logic (e.g. involving dynamic information about the cluster being installed into). 
istioctl and operator both share component based generation logic, where output manifest resources are grouped by component. A plugin could be a flag e.g. 
``` 
istioctl install --plugins=<path to a plugin binary>,<path to another plugin binary>
```
In this case, the generated manifests would be passed in some serialized format to the binary at the given path. The format could be a multi-part text file, or yaml that includes:
- IstioOperator CR values (after overlays have been applied)
- component name and the generated manifest for it
The plugin would return the object in the same format with any desired mutations.
The advantage of the external binary as the plugin format is it would not require forking Istio or the charts, and should be compatible with a wide range of istioctl versions, since the API would be very simple and likely very stable.

**Comment by howardjohn** [comment]
Can  we direct these users to https://helm.sh/? In my opinion this is *far* beyond the scope of what we should do. Remember - we are a service mesh, not a generic package manager
