### ISSUE TITLE
Pilot never expires query cache stats

### ISSUE THREAD

**Issue by asomya** [istio/istio#2362]
As reported in this issue: https://github.com/istio/istio/issues/1758

Pilot keeps the cache stats forever for deleted services and pods. This could potentially grow very large depending on the number of services, pods and endpoints created and deleted. We should delete the cache stats when the services or endpoints are deleted.

* Edited for clarity (02/19/2018)

**Comment by asomya** [comment]
Can this be assigned to me? Interested in working on it.

**Comment by rshriram** [comment]
we dont use the query cache anymore..
