### ISSUE TITLE
Automate new release branch cutting

### ISSUE THREAD

**Issue by ericvn** [istio/istio#23620]
What can we do to automate the steps used when cutting a new branch for a release.

An example Issue is here: https://github.com/istio/istio/issues/22078

**Comment by brian-avery** [comment]
Removing the needs escalation label here. This is scheduled for 1.7 and doesn't currently need escalation.

**Comment by ericvn** [comment]
From the wiki:
```
lifecycle/needs-escalation. A P0 or Release Blocker issue that hasn’t received any attention from an Istio team member in a few days.
```

**Comment by ericvn** [comment]
Work continuing in release 1.8.

**Comment by bianpengyuan** [comment]
Is this work done for 1.8? Last time I heard some of the processes are automated but not completely automated.

I moved this to 1.9 since this is not a release blocker for 1.8, let me know if this makes sense or not.

**Comment by ericvn** [comment]
@bianpengyuan A lot of the work is done in https://github.com/istio/release-builder/pull/439, but the work will likely continue into 1.9.

**Comment by ericvn** [comment]
Work done in https://github.com/istio/release-builder/pull/514.
