### ISSUE TITLE
installPackagePath https path regression 

### ISSUE THREAD

**Issue by ostromart** [istio/istio#23635]
```
ic manifest generate --set installPackagePath=https://github.com/istio/istio/releases/download/1.6.0-beta.0/istio-1.6.0-beta.0-linux-amd64.tar.gz
```
fails because the extracted dir has path /tmp/istio-install-packages/istio-1.6.0-beta.0/ instead of /tmp/istio-install-packages/istio-1.6.0-beta.0-linux/ as expected.

**Comment by ostromart** [comment]
Another config that doesn't work, with controller: 
```
istioctl152 operator init
kubectl create ns istio-system
kubectl apply -f - <<EOF
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-one
spec:
  installPackagePath: https://github.com/istio/istio/releases/download/1.5.2/istio-1.5.2-linux.tar.gz
  profile: default
EOF
```

**Comment by xzb** [comment]
> Another config that doesn't work, with controller:
> 
> ```
> istioctl152 operator init
> kubectl create ns istio-system
> kubectl apply -f - <<EOF
> apiVersion: install.istio.io/v1alpha1
> kind: IstioOperator
> metadata:
>   namespace: istio-system
>   name: istio-one
> spec:
>   installPackagePath: https://github.com/istio/istio/releases/download/1.5.2/istio-1.5.2-linux.tar.gz
>   profile: default
> EOF
> ```

Hi, I would like to know does this installation command work now? I tried on my end that setting remote URL only works when using istioctl apply to install, but failed when using above operator command.
