### ISSUE TITLE
"SignatureDoesNotMatch" when downloading istio-*.tar.gz

### ISSUE THREAD

**Issue by jstevans** [istio/istio#23633]
**Bug description**

Attempting to download [istio 1.4.8-linux](https://github.com/istio/istio/releases/tag/1.4.8) or [istio 1.3.8-linux](https://github.com/istio/istio/releases/tag/1.3.8) gives some XML with "SignatureDoesNotMatch" -- I downloaded istio-1.3.8 last week, so this seems like a new issue.

**Comment by esnible** [comment]
I am having good luck with `curl --location https://github.com/istio/istio/releases/download/1.4.8/istio-1.4.8-osx.tar.gz > istio-1.4.8-osx.tar.gz`.  What are you using to download?

**Comment by jstevans** [comment]
Seems like it was a transitive issue -- I was able to download it yesterday. At the time, `curl`, Firefox, and Chrome all weren't working. Thanks!
