### ISSUE TITLE
DestinationRule cannot correctly select the global serviceentry label

### ISSUE THREAD

**Issue by shawnho1018** [istio/istio#23639]
**Bug description**
I tried to follow this earlier blog to implement cross-cluster bookshelf workloads: https://istio.io/blog/2019/multicluster-version-routing/
I use a local sleep pod and it could successfully connect to the reviews.default.global. However, Kiali keeps reporting detecting failure of my destination rule, which has a match label (cluster: cluster2) with the global serviceentry.

**Expected behavior**
The destinationrules could successfully resolve the serviceentry. 
**Steps to reproduce the bug**
1. Install istio on 2 separate clusters using the "replicated control plane" method: https://istio.io/docs/setup/install/multicluster/gateways/
2. Place bookshelf apps onto two separate clusters following this blog: https://istio.io/blog/2019/multicluster-version-routing/
3. Apply a sleep pod in cluster 1 and use its curl to verify reviews.default.global/reviews/1 is successfully connected. 
4. istioctl dashboard kiali to use kiali to see the reviews-global destination rules has matching issues

<img width="1437" alt="Screen Shot 2020-05-08 at 10 49 16 AM" src="https://user-images.githubusercontent.com/28553789/81365102-d612fd00-9119-11ea-8923-380ba1f722df.png">

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
client version: 1.5.2
control plane version: 1.5.2
data plane version: 1.5.2 (9 proxies)

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
Does it actually not match or does kiali incorrectly report it doesn't match?

**Comment by shawnho1018** [comment]
I tested the cross cluster traffic does not work. I think the tag does not
match correctly.

John Howard <notifications@github.com> 於 2020年5月8日 週五 下午10:19寫道：

**Comment by howardjohn** [comment]
Can you provide more info? Showing the deployments/services you have, and what requests failed? In your original issue you said traffic *does* work but the dashboard shows errors. If its just the dashboard is wrong, please file an issue in the kiali/kiali repo.

**Comment by howardjohn** [comment]
@shawnho1018 any more info?
