### ISSUE TITLE
istio-cni-node crash with Istio CNI and COS_CONTAINERD in GKE

### ISSUE THREAD

**Issue by sho-abe** [istio/istio#23643]
**Bug description**

The istio-cni-node DaemonSet does not start when Istio CNI and COS_CONTAINERD are enabled on Google Kubernetes Engine (GKE).
As a result, pods with sidecar enabled will not also ready because pods wait for CNI initialization.

I considered the repair-cni container of istio-cni-node failed to start with the error below.

```
standard_init_linux.go:211: exec user process caused "permission denied"
```

**Expected behavior**

istio-cni-node starts correctly.

**Steps to reproduce the bug**

create GKE Cluster with COS_CONTAINERD.

```shell script
gcloud container clusters create istio-cni-test \
  --cluster-version latest \
  --machine-type=e2-standard-2 \
  --num-nodes 3 \
  --image-type=COS_CONTAINERD \
  --enable-network-policy \
  --tags=istio \
  --zone us-central1-b
```

download Istio.

```shell script
curl -L https://istio.io/downloadIstio | ISTIO_VERSION=1.4.8 sh -
```

install Istio with CNI plugin.

```shell script
istioctl manifest apply \
  --set cni.enabled=true \
  --set cni.components.cni.namespace=kube-system \
  --set values.cni.cniBinDir=/home/kubernetes/bin
```

check Pods's status.

```
$ kubectl get pods -n kube-system -l k8s-app=istio-cni-node
NAME                   READY   STATUS             RESTARTS   AGE
istio-cni-node-7pdd4   1/2     CrashLoopBackOff   5          4m39s
istio-cni-node-8xbrx   1/2     CrashLoopBackOff   5          4m39s
istio-cni-node-qhbn5   1/2     CrashLoopBackOff   5          4m39s
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
$ istioctl version --remote
client version: 1.4.8
control plane version: 1.4.8
data plane version: 1.4.8 (1 proxies)
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-gke.12", GitCommit:"fd078e6ed95d359cb2c9ca6561754806718c1c98", GitTreeState:"clean", BuildDate:"2020-04-20T22:33:20Z", GoVersion:"go1.12.17b4", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

* `istioctl manifest apply` with CNI plugin.

**Environment where bug was observed (cloud vendor, OS, etc)**

* Google Kubernetes Engine Cluster with COS_CONTAINERD

**Comment by stewartbutler** [comment]
I'm investigating this now.

**Comment by stewartbutler** [comment]
It looks like https://github.com/containerd/containerd/issues/4182 may be the cause. I'm creating a new CNI image that uses the listed workaround and testing it out.

**Comment by gael-jurin** [comment]
Same error after istio 1.5.3 upgrade on Kubernetes 1.16.0 environment.

`standard_init_linux.go:211:exec user process caused "permission denied" `

I have to disable sidecar injection on my namespace to have them running again.

**Comment by stewartbutler** [comment]
Still working on it. I've confirmed the issue is that the binaries are mounted in a volume with `noexec`. I'm testing a few alternate images to see if I can pin down a configuration which mounts the binaries in an executable location without too much change.
