### ISSUE TITLE
Issues related to Multi Cluster istio with Single Control Plane on multi network

### ISSUE THREAD

**Issue by Tharun-Sabbu** [istio/istio#23640]
**Bug description**

Cross Cluster routing not working 

[ ] Multi Control Plane

**Expected behavior**
Traffic should be routed to remote cluster applications

Istio Version: 1.5.2, helm way to setup with individual components instead of istiod

**Environment where bug was observed (cloud vendor, OS, etc)**

Using kops in  AWS environment

Detail Explanation of the Issue:

I was following multi cluster setup documentation, ingress gateway in remote cluster 2 was up and able to communicate with pilot. Pilot discovery container in control plane cluster 1 was able to get all endpoints of pods of remote cluster 2. Ingress gateway was also in ready state on cluster2, however I wasn't able to figure out what was the issue at this point. In the documentation, I see that cross cluster routing should work once ingress gateway in remote cluster is up but every time I send a request  with following

> kubectl exec --context=$CTX_CLUSTER1 -it -n sample -c sleep $(kubectl get pod --context=$CTX_CLUSTER1 -n sample -l app=sleep -o jsonpath='{.items[0].metadata.name}') -- curl helloworld.sample:5000/hello

It was always goes to the same cluster and wasn't able to connect to remote cluster hello world application. However, ingress configuration are propagated in remote cluster 2  when I updated the configuration in cluster 1 and was as even able to the see the routes in remote cluster using below command

> istioctl proxy-config routes <istio-ingressgateway-pod-name>.istio-system -o json

And more over I was able to send requests to both ingress gateways in both clusters with http and https. I'm getting response, but responses are of the same cluster never reaching to remote cluster application.

Not sure, if I'm doing something from myside

@taylorreece @hzxuzhonghu, please help, thank you.

**Comment by taylorreece** [comment]
Hey @Tharun-Sabbu - I've not done much with istio for a few months, but from what I gather from recent docs, two things are probably important to note:

1. `helm` install of Istio is discouraged, and might be deprecated in favor of `istioctl` installs.  I bet helm charts are outdated; you're probably better off turning to istioctl.  See the note on the top of https://istio.io/docs/setup/install/helm/
2. Probably more important - I'm not sure that the issues with multi-cluster have been ironed out yet for 1.5.*.  Docs seem to indicate that no one should upgrade to 1.5.0 until the issues noted are resolved: https://istio.io/news/releases/1.5.x/announcing-1.5/upgrade-notes/#multicluster-setup

**Comment by hzxuzhonghu** [comment]
cc @linsun @stevenctl maybe duplicate with what you have found

**Comment by Tharun-Sabbu** [comment]
Hey @taylorreece  - Thank you for the suggestions.

Yeah I've seen istioctl way for 1.5.2 however istiod component  with grafana dashboards doesn't play good I think as per the issues I've seen. However, I would love to move to istiod as the number of components will be reduced.

I was using istio 1.5.2, will that make any difference as I've seen those issues will be fixed in 1.5.1. Performance was really good on 1.5.x compared to 1.4.x versions, so I don't want to downgrade.

**Comment by hzxuzhonghu** [comment]
https://github.com/istio/istio/issues/23495

**Comment by Tharun-Sabbu** [comment]
@hzxuzhonghu Is this setup working in v1.5.1, please let me know. Also I've see a bug, when I was using AWS load balancer, load balancer's defined in the istio configmap for cluster 1 and cluster2, they are being resolved to ip's and were loaded into pilot. Problem was if the ip's get changed they are not being reflected immediately, not sure if this a bug or am I doing something wrong

**Comment by hzxuzhonghu** [comment]
https://github.com/istio/istio/issues/23495#issuecomment-624261918 However, i didn't do a verification.

**Comment by linsun** [comment]
Could you please try on 1.5.1 @Tharun-Sabbu?  It is unclear if your issue is a dup of #23495 as you didn't exactly describe how endpoints are used for pods in cluster 2.

**Comment by Tharun-Sabbu** [comment]
Hello @linsun ,
Here are the commands I ran on both clusters and was able to get endpoints

> kubectl --context=$CTX_CLUSTER1 -n sample get pod -l app=sleep -o name | cut -f2 -d'/' |     xargs -I{} istioctl --context=$CTX_CLUSTER1 -n sample proxy-config endpoints {} --cluster "outbound|5000||helloworld.sample.svc.cluster.local"
> ENDPOINT              STATUS      OUTLIER CHECK     CLUSTER
> 10.35.13.138:443      HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local
> 172.22.240.2:5000     HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local

> kubectl --context=$CTX_CLUSTER2 -n sample get pod -l app=sleep -o name | cut -f2 -d'/' |     xargs -I{} istioctl --context=$CTX_CLUSTER2 -n sample proxy-config endpoints {} --cluster "outbound|5000||helloworld.sample.svc.cluster.local"
> ENDPOINT              STATUS      OUTLIER CHECK     CLUSTER
> 10.35.13.194:443      HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local
> 172.21.224.2:5000     HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local

This is what you are asking right?
