### ISSUE TITLE
Use the domain suffix consistently

### ISSUE THREAD

**Issue by nmittler** [istio/istio#23652]
We currently have "cluster.local" scattered around the code base. Istiod is capable of overriding this domain suffix, but many areas of the code are hard-coded to "cluster.local".

We should go through the codebase and use the configured domain suffix consistently.  We'll also want better testing around the use of domain suffix.

**Comment by howardjohn** [comment]
Highly related: https://github.com/istio/istio/issues/28053 which essentially says "test this is not broken"
