### ISSUE TITLE
Istio 1.4 (installed by kubectl apply) cannot be upgrade to Isito 1.5

### ISSUE THREAD

**Issue by elfinhe** [istio/istio#23653]
**Bug description**
My Istio 1.4 was installed by piping `istioctl manifest generate` to `kubectl apply -f -`.

`istioctl148 manifest generate | kubectl apply -f -`

Then I use the manifest apply command to upgrade

`istioctl152 manifest apply`

Then I got this:

```
$ kubectl get pods -n istio-system

NAME                                      READY   STATUS    RESTARTS   AGE
istio-citadel-7f65bcf54-c5hx5             1/1     Running   0          12m
istio-galley-66f6f4cb59-7h4xf             2/2     Running   0          12m
istio-ingressgateway-865fb76f45-9btwq     1/1     Running   0          2m41s
istio-ingressgateway-865fb76f45-zvwt6     1/1     Running   0          2m46s
istio-pilot-6dffdf9587-76gxp              2/2     Running   0          11m
istio-pilot-6dffdf9587-q5gs2              1/2     *Error*     5          2m56s
istio-policy-5d67d8dcc-4smbf              2/2     Running   1          11m
istio-sidecar-injector-5bccdcc4d4-kx6hh   1/1     Running   0          11m
istio-telemetry-68859f7cb4-s8vvf          2/2     Running   1          11m
istiod-7c44f6d7f6-6sqs8                   1/1     Running   0          2m45s
istiod-7c44f6d7f6-8j4dj                   1/1     Running   0          3m1s
istiod-7c44f6d7f6-kf8p6                   1/1     Running   0          2m45s
prometheus-94bf459c9-g8lzl                2/2     Running   0          2m46s
```

Errors in pilot discovery container
```
2020-05-08T16:34:56.790646Z	error	failed to create discovery service: config controller: failed to register custom resources. customresourcedefinitions.apiextensions.k8s.io is forbidden: User "system:serviceaccount:istio-system:istio-pilot-service-account" cannot create resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
Error: failed to create discovery service: config controller: failed to register custom resources. customresourcedefinitions.apiextensions.k8s.io is forbidden: User "system:serviceaccount:istio-system:istio-pilot-service-account" cannot create resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope

```

**Expected behavior**
Upgrade succeeds. Only ingress and istiod were there.

**Steps to reproduce the bug**

`istioctl148 manifest generate | kubectl apply -f -`

`istioctl152 manifest apply`

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

related: https://github.com/istio/istio/pull/21355

**Comment by howardjohn** [comment]
This is sort of expected I think. kubectl apply doesn't prune, so the only pilot deployment stays around, but the clusterrole has changed. We expect the old pilot deployment to be removed

**Comment by elfinhe** [comment]
note that the upgrade command is `istioctl manifest apply` not kubectl, so I expect it would prune all not-needed components in 1.5.

**Comment by howardjohn** [comment]
I missed that. We support helm -> helm and apply -> apply, but I don't think we support generate -> apply (as noted here) until 1.6

**Comment by elfinhe** [comment]
Related: https://github.com/istio/istio/pull/21355

**Comment by vito-laurenza-zocdoc** [comment]
This actually breaks the mesh and services exposed via ingress are fully unavailable: `upstream connect error or disconnect/reset before headers. reset reason: connection failure`. Deleting the istio-pilot deployment nearly instantly fixes the issue.
