### ISSUE TITLE
Manually inject sidecar failed while Automatic inject successfully

### ISSUE THREAD

**Issue by woodliu** [istio/istio#23651]
**Bug description**
I use openshift 4.3, istio 1.5.2, and i install the istio CNI.
When automatic inject the sidecar, it is successful. But when i manually inject the sidecar ,it is failed, show error logs as:

> in new validator: 10.80.2.222
Listening on 127.0.0.1:15001
Listening on 127.0.0.1:15006
Error connecting to 127.0.0.6:15002: dial tcp 127.0.0.1:0->127.0.0.6:15002: connect: connection refused
Error connecting to 127.0.0.6:15002: dial tcp 127.0.0.1:0->127.0.0.6:15002: connect: connection refused
Error connecting to 127.0.0.6:15002: dial tcp 127.0.0.1:0->127.0.0.6:15002: connect: connection refused
Error connecting to 127.0.0.6:15002: dial tcp 127.0.0.1:0->127.0.0.6:15002: connect: connection refused
Error connecting to 127.0.0.6:15002: dial tcp 127.0.0.1:0->127.0.0.6:15002: connect: connection refused

I comprae the two kinds of pod spec(through `oc describe pod`), and found the difference as bellow
Manually inject:

- istioctl kube-inject -f sleep.yaml -o sleep-injected.yaml --injectConfigMapName istio-sidecar-injector

- oc create -f sleep-injected.yaml

>apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "openshift-sdn",
          "interface": "eth0",
          "ips": [
              "10.80.2.93"
          ],
          "dns": {},
          "default-route": [
              "10.80.2.1"
          ]
      }]
    openshift.io/scc: anyuid
    sidecar.istio.io/interceptionMode: REDIRECT
    traffic.sidecar.istio.io/excludeInboundPorts: "15020"
    traffic.sidecar.istio.io/includeOutboundIPRanges: '*'

Automatic inject：
>apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/networks: istio-cni
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "openshift-sdn",
          "interface": "eth0",
          "ips": [
              "10.80.2.94"
          ],
          "dns": {},
          "default-route": [
              "10.80.2.1"
          ]
      },{
          "name": "istio-cni",
          "dns": {}
      }]
    openshift.io/scc: anyuid

The only difference is the annotations `k8s.v1.cni.cncf.io/networks: istio-cni`. When I add the annotation to file sleep-injected.yaml, and manually inject again, it is Successful! So i think the command `istioctl kube-inject` may lost some configuration when it running.

**Expected behavior**

**Steps to reproduce the bug**
Every time when i manually inject sidecar 
**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**
Follow the instruction istio supplied
**Environment where bug was observed (cloud vendor, OS, etc)**
`# cat /etc/*-release
CentOS Linux release 7.4.1708 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.4.1708 (Core)
CentOS Linux release 7.4.1708 (Core)
`

**Comment by m-eaton** [comment]
The istioctl binary does not support the CNCF networks annotation in istio 1.5. The workaround is adding the `k8s.v1.cni.cncf.io/networks: istio-cni` annotation to the deployment manually before applying the output of `istioctl kube-inject` in CNI mode. See https://github.com/istio/istio/issues/24425
