### ISSUE TITLE
mixer should not use pods - service identity should come from pilot

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#2367]
This is the longer term part of #1302 

Mixer should stop using pods for figuring out service names, and not have a pod cache

It should also not rely on pod labels

And should not use k8s directly for anything but it's own config CRs / CRDs

**Comment by douglas-reid** [comment]
Better / fixed service name discovery is important and something we want to address.

I don't see anything fundamentally wrong with having a cache of data in a Mixer adapter.

Whether or not Mixer should go through Pilot or directly to the API server to provide environmental information is a reasonable question, but way back when, we decided to have it call the API server directly.

Pod labels are important for a number of use cases (version information, actual running instance of binary, etc.). I don't think we should declare that they shouldn't be available.

Perhaps this should be multiple issues.

**Comment by mandarjog** [comment]
My thinking has evolved to favor metadata sent by the Envoy when possible. This works very well for the pure service mesh case when only envoy calls mixer. This also works well when the source can assert it's own metadata using a certificate.

It does not work when services directly call Mixer, So we will have to continue supporting the Mixer env adapters.

**Comment by douglas-reid** [comment]
Right, so we should prefer info sent by Envoy. And the places where we are not doing that, we should file a bug. But any information not sent by Envoy needs to be retrieved somehow (direct api calls being an important case here). Switching to Pilot seems reasonable, provided we can get the same set of information that we can from the API server or elsewhere.

**Comment by kyessenov** [comment]
I like the approach of reusing pilot's service registry adapters instead of
writing clones in other systems. I'm not sure how much we want to integrate
the two though (should it be one binary, one service, an API, or a shared
stored object?)

**Comment by geeknoid** [comment]
If I understand correctly, we are considering calling Pilot from Mixer? If
so, this would introduce a data plane dependency (Mixer) on a control plane
component (Pilot) which doesn't seem wise.

**Comment by mandarjog** [comment]
We should *not* be calling Pilot from Mixer. 

1. Pilot sends metadata to Envoy (which it already does today), it should just send all the metadata.
and/OR
2. Create a separate Istio Service Registry service, which pilot, mixer or anyone else can call.

**Comment by kyessenov** [comment]
What do we do in the case of direct service call to mixer? This bypasses
pilot metadata infection, and we need an alternative derivation mechanism.
The dependency can also be inverted, by making pilot call out to mixer to
program its derivation algorithms.

**Comment by douglas-reid** [comment]
What would the Istio Service Registry service provide beyond what Pilot is providing to Envoy? I feel like that adds a complication that isn't needed.

Again, I think this should be separated into multiple issues.

Retrieving proper service names from k8s API server is a short-term do-able item. We basically had this in a reverted PR from way back. Let's do that first.

Having Pilot push all known metadata to Envoy is another issue that seems short-term solvable.

Writing a new / rewriting the env adapter to interact in some fashion with Pilot seems like another discussion.

**Comment by mandarjog** [comment]
Creation of a separate `Istio service registry` component addresses this issue. Mixer and Pilot both call this service. However in the pure service mesh environment, Mixer should never call this service.

**Comment by ldemailly** [comment]
This a new analysis:

https://groups.google.com/d/msgid/istio-config/CALuuQPAPo91QBpCgrtSp2G0crKOA2xikZ6346aN7qn4LhPbDBQ%40mail.gmail.com

**Comment by douglas-reid** [comment]
i don't know how to fully resolve this issue.

we've changed the attributes we are using and have stopped deriving service names. 

we still have issues around attribute derivations for VM workloads (mesh extension use cases).

Can we close this issue and open a more actionable set of issues?

**Comment by ldemailly** [comment]
go ahead if you want though it's already the 3rd round of close and reopen - but yes I guess the long thread about service/workload etc on the mailing list probably is the replacement for this

**Comment by andraxylia** [comment]
If mixer needs Services and Endpoints, it should use the MCP client, and we can decide later if the source is Pilot, Galley, or an out-of-process service registry. Please replace Pilot with Mixer in the Pilot Decomposition doc to get the picture: https://goo.gl/qAsEQx .

@ozevren might be interested in working on the MCP for mixer.
