### ISSUE TITLE
Provide integrations for the delopment environment with various editors

### ISSUE THREAD

**Issue by sdake** [istio/istio#23689]
**Describe the feature request**
Integrate the development environment with various editors including the ability to
- build the software using the build container
- debug software built in the build container
- support for Linux and macOS platforms
- support for ssh based filesystem (sshfs) if possible (this is a secondary goal)

**Describe alternatives you've considered**
Currently, there is no integration. The development environment is useful for developers that use tools such as vi, although many developers use GUIs and these developers have a hard time working with the development environment.

Some initial discussion brings out vscode and goland as potential integration points for editors as these seem to be highly popular among many existing Istio developers and the community in general.

[X] Development Environment

**Additional context**

**Comment by howardjohn** [comment]
What part of IDE functions do not work currently? You shouldnt need the build container system to run tests or compile, are there other things people are doing?

**Comment by sdake** [comment]
The development environment (which is a thin wrapper around the build container) is not required to run tests nor compile code nor debug, although it is helpful to have a consistent developer and CI behavior.

We do not wish developers to develop and test code on random variants of toolchains as this leads to inconsistent results when the source code is built by the same toolchain as is available in the prow to build and release environment.
