### ISSUE TITLE
Can't make HAProxy container working with Istio

### ISSUE THREAD

**Issue by emillg** [istio/istio#23680]
**Bug description**
I have a HAProxy container running in k8s. After injecting Envoy, it failed to send requests to another k8s service `mock-service`. The response code was 504 after 180s timeout.

Both the HAProxy and `mock-service` are running in the same namespace within the same cluster.

The HAProxy backend config looks like
```
global
    daemon
    log /dev/log local0 notice
    maxconn 500

defaults
    mode http
    log global
    timeout connect 5s
    timeout client 60s
    timeout server 180s
    retries 3
    option redispatch

frontend http-in
    mode http
    bind :8090
    log /dev/log local0 info
    
    default_backend mock_service

backend mock_service
    server mock_service mock-service:8090 check
```

**Expected behavior**
HAProxy can send requests to other k8s services successfully.

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
client version: 1.5.2
control plane version: 1.5.2
data plane version: 1.5.2
k8s version: 1.16

**How was Istio installed?**
istioctl manifest apply --set values.global.mtls.auto=false --set values.kiali.enabled=true

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by mhite** [comment]
Long shot, but can you rename your service without an underscore?

**Comment by emillg** [comment]
@mhite Sorry that was a typo when modifying the config. I have updated it.

In our env the HAProxy container works well. But after injecting Envoy, looks like it can not reach `mock-service`.

Both the HAProxy and `mock-service` are running in the same namespace within the same cluster.

**Comment by kenotsolutions** [comment]
Have you got any reply for this issue? I tested in my environment I got the same result.  Haproxy pod cannot send traffic to backend-servers with injecting Istio.

**Comment by emillg** [comment]
@kenotsolutions no reply yet

**Comment by howardjohn** [comment]
Please attach config dump from mock-service and haproxy and get access logs for the failed requests. thanks. See https://github.com/istio/istio/wiki/Troubleshooting-Istio for info

**Comment by howardjohn** [comment]
Can you provide more info @emillg ?
