### ISSUE TITLE
why not add back pressure function in Istio

### ISSUE THREAD

**Issue by huo4444** [istio/istio#23687]
why not add back pressure function in isito,such as ,based on response time and qps ,dynamic control the ingress perform action

**Comment by howardjohn** [comment]
We do provide a variety of backpresure mechanisms. See https://www.envoyproxy.io/learn/backpressure for example. You can set timeouts for example to back pressure on slow responses with various outlier detect rules

**Comment by howardjohn** [comment]
As far as I know this is answered. Please reopen, or preferably ask on discuss.istio.io or in envoy community if you need more info
