### ISSUE TITLE
How to deploy application without sidecar, when istio-injection=enabled in namespace

### ISSUE THREAD

**Issue by jmyung** [istio/istio#23695]
**Question the feature**

This is a question for _how to deploy application without sidecar, when `istio-injection=enabled` was already applied in namespace._
Is there any way to achieve this?

There must be application like helm tiller (installed in each namespace) which doesn't need sidecar proxy.

For example, the step would be like this. See below.

1. kubectl label namespace user01 istio-injection=enabled
2. kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml -n user01
3. kubectl apply -f tiller.yaml -n user01  **<- this doesn`t need sidecar**

**Comment by kebe7jun** [comment]
You should add a annotation for .spec.template.metadata.annotations with `sidecar.istio.io/inject: false`.
https://istio.io/docs/setup/additional-setup/sidecar-injection/#policy

**Comment by jmyung** [comment]
@kebe7jun Thanks you !!!
It works ! 😄
