### ISSUE TITLE
Proposal: Use Pilot to configure Mixer

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#2369]
The purpose of Pilot is to configure Istio data plane component(s).
Envoy is the primary data plane component therefore pilot configures all aspects of envoy.

Mixer  (Istio authz) is also a data path component. 
Specifically Mixer runtime code is executed inline with the request and header data traverses through Mixer. 

Mixer is also a bit different in that Mixer/pkg/runtime/controller implements the Mixer controller in-process. Creating a data plane control / control plan distinction would mean that 
1. Mixer uses an xDS/ADS like configuration API to fetch its configuration and stop communicating with API  server. This API will be tailer made for mixer.
2.  Mixer/pkg/runtime/controller or some variant thereof runs in Pilot. Pilot is responsible for synthesizing a proper configuration snapshot.

This way all Istio data path components are consistently configured by Pilot.

**Comment by mandarjog** [comment]
@kyessenov

**Comment by andraxylia** [comment]
It makes more sense if Mixer is configured with Galley. Please see Pilot decomposition and replace Pilot with Mixer

https://docs.google.com/document/d/1S5ygkxR1alNI8cWGG4O4iV8zp8dA6Oc23zQCvFxr83U/edit

cc @ozevren
