### ISSUE TITLE
Treat external name services pointing to k8s as standard internal services

### ISSUE THREAD

**Issue by rshriram** [istio/istio#23691]
**Describe the feature request**

The following is a pattern we observed in several enterprise environments (good or bad is a different question, but this is an existing k8s cluster without Istio):
 **Context**: Users have several environments in the same cluster. (e.g., prod-uat in ns1, ns2, ns3.. and prod-public in ns4, ns5, ns6). As part of the standard 12 factor design, all hostname references are externalized in the config file. E.g., if a productpage service in ns1 calls details in ns2, the location of the details service is externalized in app-specific config files like this DETAILS_SERVICE=details.ns2.svc.cluster.local. 

When this application is promoted from prod-uat to prod-public, users change all the configs in their applications to point to the services in the new namespaces, i.e. DETAILS_SERVICE=details.ns5.svc.cluster.local .

**Problem**: It seems the practice of embedding the exact location of the target service into application config files has resulted in a lot of outages and unnecessary complexity (one customer reported about 500+ config files per app that defined such env specific mappings!) as they have several cross namespace interactions across their fleet.

**Solution adopted by the end user**: What users have started doing is create an ExternalName services for all the cross namespace dependencies. For example, 

```yaml
apiVersion: v1
kind: Service
metadata:
  name: details
spec:
  type: ExternalName
  externalName: details.ns3.svc.cluster.local
```

so that the configuration for all consumers of this details service from ns1 can be DETAILS_SERVICE=details. When the application is promoted from uat to prod-public, there is no change to application configuration whatsoever. Only the external name services in each namespace have to be updated. 

```yaml
# in prod-public
apiVersion: v1
kind: Service
metadata:
  name: details
spec:
  type: ExternalName
  externalName: details.ns5.svc.cluster.local
```

**How does it pertain to Istio**: Unfortunately, with this pattern, we end up treating the external name services as external services. Or at the very least, we end up using the externalName as the service instance for this service rather than using all the pod IPs. As a result, mTLS to the externalName service now requires the end user to explicitly declare a destinationRule, defeating the purpose of auto-mTLS. Same applies to things like circuit breakers, subsets, etc.

**what can we do**:  We cannot solve this generically across service entries (with location mesh_internal) and kubernetes services. But we can certainly solve it within the context of kubernetes. We need to determine how though (esp when the user also creates configs for both services!)

cc @howardjohn / @ramaraochavali / @hzxuzhonghu / @diemtvu / @incfly 

**Describe alternatives you've considered**

**Additional context**

**Comment by incfly** [comment]
This seems just a normal traffic splitting problem right? And the reason VirtualService/DestianationRule can't work, is it because customers staging/prod division are across namespaces, and our API addressing & selection by host does not work well with that?

If that's the reason, will [hierarchical namespaces](https://github.com/istio/api/issues/1205) be relevant?

**Comment by hzxuzhonghu** [comment]
```
	// ServiceTypeExternalName means a service consists of only a reference to
	// an external name that kubedns or equivalent will return as a CNAME
	// record, with no exposing or proxying of any pods involved.
	ServiceTypeExternalName ServiceType = "ExternalName"
```

https://kubernetes.io/docs/concepts/services-networking/service/#externalname

It is not encouraged to use like this.  And also the tricky point is we have no way to know if this is an internal service wrapper.

**Comment by rshriram** [comment]
Can’t we know by looking at the hostname in the external service ? If it points to a k8s service then we treat it as internal. If not, we treat it as external.

**Comment by hzxuzhonghu** [comment]
There is no explicit difference between external and cluster service domain. Normally, internal service can be accessed with FQDN(`svcName.namespace.svc.cluster.local`), however it can be accessed by ``svcName.namespace.svc` or even `svcName` in some case.
