### ISSUE TITLE
httpbin: test commands are confusing

### ISSUE THREAD

**Issue by ahmetb** [istio/istio#237]
https://github.com/istio/istio/blob/master/demos/apps/httpbin/README.md

```
kubectl run -i --rm --restart=Never dummy --image=dockerqa/curl:ubuntu-trusty --command -- curl --silent httpbin:8000/html
kubectl run -i --rm --restart=Never dummy --image=dockerqa/curl:ubuntu-trusty --command -- curl --silent httpbin:8000/status/500
```

these commands just exit without printing anything and makes me think things aren't working (plus makes them both indistinguishable from each other).

Try doing `curl -sv`

**Comment by frankbu** [comment]
The first one `/html` should be printing out some html. If you're not seeing anything, it's not working. I see your point about the second one (`/status/500`), though.

Your suggestion of changing to `curl -sv` sounds like a good idea.

**Comment by ahmetb** [comment]
Looks like `/html` actually fails:

```
kubectl run -i --rm --restart=Never dummy --image=dockerqa/curl:ubuntu-trusty --command -- curl -v --silent httpbin:8000/html

* Hostname was NOT found in DNS cache
*   Trying 10.7.252.248...
* Connected to httpbin (10.7.252.248) port 8000 (#0)
> GET /html HTTP/1.1
> User-Agent: curl/7.35.0
> Host: httpbin:8000
> Accept: */*
>
* Recv failure: Connection reset by peer
* Closing connection 0
```

Here's what I did.
```
$ kubectl apply -f <(istioctl kube-inject -f httpbin.yaml)
service "httpbin" created
deployment "httpbin" configured
```

```
NAME                             READY     STATUS    RESTARTS   AGE
httpbin-1403355688-ds26s         2/2       Running   0          2h
```

```
$ kubectl get svc
NAME      CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
httpbin   10.7.252.248   <none>        8000/TCP   1m
```

**Comment by kyessenov** [comment]
The istio sidecar has to be present in the pod. If you run a container, it doesn't have the sidecar proxy to handle the connection to external name service.

**Comment by ahmetb** [comment]
@kyessenov I applied output of `istioctl kube-inject` as instructed in https://github.com/istio/istio/blob/master/demos/apps/httpbin/README.md. Am I doing it wrong?

**Comment by ahmetb** [comment]
@kyessenov then in that case the 

    kubectl run -i --rm --restart=Never dummy --image=dockerqa/curl:ubuntu-trusty --command -- curl -v --silent httpbin:8000/html


instruction on the httpbin/README.md is simply inaccurate?

**Comment by frankbu** [comment]
@ahmetb: is `/html` the only curl that is failing for you ... or do all 3 curls not work?

**Comment by ldemailly** [comment]
closing this. please reopen if it's still an issue with 0.2.6
