### ISSUE TITLE
istio-ca-root-cert configmaps not deleted when Istio is uninstalled

### ISSUE THREAD

**Issue by nea1** [istio/istio#23706]
**Bug description**
Istio creates a configmap `istio-ca-root-cert` in each namespace containing its root cert. When Istio is uninstalled these configmaps are *not* removed, and to completely remove Istio they must be manually deleted. Ideally Istio uninstallation should tidy up all of its resources without manual intervention.

**Expected behavior**

All Istio related resources should be removed when Istio is removed. Or at least the steps to manually remove them documented.

**Steps to reproduce the bug**

```
# install Istio
istioctl manifest apply --set profile=demo

# delete Istio
istioctl manifest generate --set profile=demo | kubectl delete -f -

# verify that Istio artifacts still remain
kubectl get configmap -A | grep istio

# resources must be manually purged
kubectl delete configmap -l istio.io/config=true -A
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

istioctl version --remote  
```
1.5.2
```

kubectl version
```
Client Version: 1.18.1
Server Version: 1.16.8
```

**How was Istio installed?**
See above - istioctl
Same issue occurs if using istio-operator

**Environment where bug was observed (cloud vendor, OS, etc)**
EKS

**Comment by howardjohn** [comment]
I think we can just document this as we don't actually have a proper `istioctl uninstall` command

**Comment by JimmyCYJ** [comment]
@lei-tang could you take a look?

**Comment by lei-tang** [comment]
Before the istioctl uninstall command deletes the configmap istio-ca-root-cert, a workaround is to manually delete it by running the following command for each namespace containing the configmap istio-ca-root-cert (replace $NAMESPACE with the namespace containing the configmap istio-ca-root-cert):

  kubectl delete configmap istio-ca-root-cert -n $NAMESPACE

**Comment by dedsm** [comment]
I'm having a similar issue with this, it seems the manifest that `istioctl manifest generate` produce doesn't include the configmaps with the ca-certs, so it's different than `istioctl manifest apply` in that sense, but the apply aborts if you don't have create namespace permissions as is my case.

**Comment by antonioberben** [comment]
`istio-ca-root-cert` is generated by `istiod`. So far, yes, you remove it manually. Pity... :(

In my case the configmap is generated in each namespace. Do you guys know how to avoid or specifically define which namespaces to avoid?

Thank you!

**Comment by lei-tang** [comment]
Since I will be OOO starting next week, assign this issue to @myidpt for triage.
