### ISSUE TITLE
k8s has restricted psp to deploy non root user but istio init container run as root 

### ISSUE THREAD

**Issue by yaminisridaran** [istio/istio#23705]
**Bug description**
Our k8s cluster has restricted psp to deploy non root user but istio init container run as root. Docker bench tool displays the complete pod runasroot warning. Can istio init container run as non root?

**Comment by esnible** [comment]
The init container needs special permissions because it does some networking things ordinary users cannot do.  There is a way to run Istio so the init container is not needed.  Try that instead.

https://istio.io/docs/setup/additional-setup/cni/

**Comment by yaminisridaran** [comment]
@esnible Thank You for your response. Is it possible to execute istio init container as non root?

**Comment by esnible** [comment]
Unless you set up CNI there will be an init container.  Istio's init container uses `iptables` to redirect pod traffic through Envoy.  `iptables` needs to run as root.  If your cluster does not allow init containers to run as root you'll need CNI to use Istio.

**Comment by yaminisridaran** [comment]
@ThankYou

**Comment by yaminisridaran** [comment]
@esnible Thank You

**Comment by YYashwanth** [comment]
@esnible I am using AWS EKS and I tried enabling Istio CNI but that messes up my EKS implementation. The worker nodes get marked **Not Ready** as soon as I enable Istio CNI and everything breaks. So, I use AWS VPC CNI which is the default installation for AWS EKS.

Is there any other way to get around the root user for Istio Init containers? I copied the istio configmap for sidecar-injector and tried changing the UID but when I do that, the init container fails stating it could not get iptables. But I am allowing capabilities like Net_raw and net_admin... shouldnt that give the container enough privs?

**Comment by hobbytp** [comment]
@YYashwanth there are some PRs try to use non-root in istio-init but finally failed. The main idea they tried is to use setpcaps in docker file to enable both NET_RAW and NET_ADMIN and then in istio-init container securityContext only left both NET_ADMIN & NET_RAW. This logic can work most case, but would failed in some case. The failure root case is here: https://github.com/istio/istio/issues/20863#issuecomment-582596655. 
So you could tried 2 things
1. Build your own docker image for proxyv2 to replace the community one, and then update the istio-injection configMap securityContext info and try if you meet the tricky problem as the comment said, if not, you are lucky.
2. Ask AWS support for your question, I hope they would already know your concern and give your solution (like new istio CNI etc)
Anyway, good luck for you, and if you fix it in future, please also share your solution if you get. :)

**Comment by gerassimos** [comment]
I am exactly in the same situation as @YYashwanth . Did anybody manage to run the initContainer as not root?

**Comment by YYashwanth** [comment]
@gerassimos I was not able to get this done as AWS EKS makes it pretty hard to use custom VPC plugin. So, I ended up exempting the istio-init container from OPA gatekeeper policies. I don't like it but I could not find any other way around this except for exempting istio-init containers.

**Comment by gerassimos** [comment]
@YYashwanth Thank you for the reply. I my case we have a PodSecurityPolicy in place that prevents to start a container as root. 

I am now considering the istio cni approach.
Our EKS cluster is using Calico for the CNI and from the documentation [here](https://istio.io/latest/docs/setup/additional-setup/cni/) I see that should work ok but actually it is not. The pods get terminated and I cannot understand why. There is no log/events available, maybe I miss something. Any advise is welcome

**Comment by YYashwanth** [comment]
Yep. I was using PSPs initially too but I switched to using OPA Gatekeeper
as they were more customisable. I had policies in place to prevent pods
from running as root and as privileged. Luckily Istio 1.8 stopped the
istiod and sidecar containers from running as privileged but they still
need to run as root.

If your pods are getting terminated with no logs/events, can you check the
system messages in the underlying host? I, often, find that helpful as you
get to know why a KILL signal was sent from the system to the container.

Do share your findings.

Best,
Yashwanth Yellapragada

**Comment by eumel8** [comment]
struggled about this issue which is still valid on istio init sidecar. Beside PSP we are using Gatekeeper now and need 3 exception for Capabilities, AllowedUsers und ReadOnlyRootFilesystem. On Gatekeeper this can be minimized with [exempt_images defintion in CRD](https://github.com/caas-team/use-cases/blob/main/gatekeeper/templates/caask8sallowedusers.yaml#L19), so this is only allowed for containers with a specific image, in this case proxyv2, which contains only the istio-iptables program, running as root to set iptable rules inside the POD.  This can be acceptable on a minimal security risk.
