### ISSUE TITLE
unknown field "galley" in v1alpha1.Values

### ISSUE THREAD

**Issue by ericvn** [istio/istio#23710]
**Bug description**

Trying to follow examples on https://preliminary.istio.io/docs/ops/diagnostic-tools/istioctl-analyze/ and one is  `Enabling validation messages for resource status` which has the command `istioctl manifest apply --set values.galley.enableAnalysis=true`

This returns:
```
Error: failed to apply manifests: validation errors (use --force to override):
unknown field "galley" in v1alpha1.Values
```

**Expected behavior**
No errors

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.6.0-beta.1
**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by shamsher31** [comment]
> istiod unifies functionality that Pilot, Galley, Citadel and the sidecar injector previously performed, into a single binary.


`Galley` is now a part of `istiod`. So `enableAnalysis` is moved from `Values` to [IstiodConfig](https://github.com/istio/istio/blob/release-1.6/operator/pkg/apis/istio/v1alpha1/values_types.proto#L556)

So this
```
$ istioctl manifest apply --set values.galley.enableAnalysis=true
```
becomes this
```
$ istioctl manifest apply --set values.global.istiod.enableAnalysis=true
```
