### ISSUE TITLE
[Istio 1.6] Issues with in place upgrade

### ISSUE THREAD

**Issue by brian-avery** [istio/istio#23726]
**Bug description**
The documentation for in place upgrades (https://preliminary.istio.io/docs/setup/upgrade/ ) links to the documentation for istioctl, which describes the `istioctl manifest` commands. It's not clear how to take these commands and use them with the upgrade instructions described in the document. `istioctl manifest apply --set profile=demo` (or any other profile) do not have any output. If you instead do an `istioctl manifest generate --set profile=demo`, then you get a YAML file, then the output of that is not an IstioOperator custom resource, and feeding that into the upgrade commands gives: 
```
istioctl manifest generate --set profile=demo > demoprofile.yaml
istioctl upgrade -f demoprofile.yaml

proto: tag has too few fields: "-"
2020-05-12T20:24:03.610279Z	info	Error: failed to generate IOPS from file [demoprofile.yaml], error: unknown field "data" in v1alpha1.IstioOperator:

YAML:
# Resources for AddonComponents grafana component

proto: tag has too few fields: "-"
2020-05-11T23:26:38.901428Z	info	Error: failed to generate IOPS from file [../demoprofile.yaml], error: unknown field "data" in v1alpha1.IstioOperator:
```

Also, the documentation explicitly says that upgrades are only compatible with `istioctl`, and therefore not `operator`. Is this correct?

**Expected behavior**
Either we should link to the docs related to the IstioOperator CRD () or we should describe how to take the istioctl manifest commands and make them usable in the upgrades. 

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

`istioctl manifest apply --set profile=demo`
I then went and followed the documentation. Istioctl manifest apply doesn't generate any output, so I instead used istioctl manifest generate to get a resulting YAML file. I then attempted to feed the YAML file to istioctl upgrade and get: 

Looking in the file, there's an IstioOperator CRD definition, but no actual CR content. There's no a clear way to generate a CR that's compatible with the documentation linked.

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by elfinhe** [comment]
Sounds like incorrect version of istioctl is used. 

What's the output of `istioctl version`

**Comment by brian-avery** [comment]
1.6.0-beta.1

**Comment by elfinhe** [comment]
mind trying this below?

```
istioctl profile dump demo > demoprofile.yaml
istioctl upgrade -f demoprofile.yaml
```

basically `isitoctl -f` only takes IsitoOperator CR file as input.

**Comment by brian-avery** [comment]
Looks like it mostly worked that way: 

```
istioctl profile dump demo > demoprofile.yaml
istioctl upgrade -f demoprofile.yaml
2020-05-12T20:39:56.114987Z	info	proto: tag has too few fields: "-"
2020-05-12T20:39:56.268599Z	info	proto: tag has too few fields: "-"
Control Plane - egressgateway pod - istio-egressgateway-b6d47b7b4-ttqjg - version: 1.6.0
Control Plane - ingressgateway pod - istio-ingressgateway-6c6c7b4598-z2b5x - version: 1.6.0
Control Plane - pilot pod - istiod-b5545bc59-zlqh8 - version: 1.6.0
Control Plane - istiod pod - istiod-canary-74bcd4758b-7xvmg - version: 1.6.0

2020-05-12T20:39:56.821344Z	warn	found 4 CRD of unsupported v1alpha1 security policy: [clusterrbacconfigs.rbac.istio.io rbacconfigs.rbac.istio.io servicerolebindings.rbac.istio.io serviceroles.rbac.istio.io]. The v1alpha1 security policy is no longer supported starting 1.6. It's strongly recommended to delete the CRD of the v1alpha1 security policy to avoid applying any of the v1alpha1 security policy in the unsupported version
Upgrade version check passed: 1.6.0 -> 1.6.0.

2020-05-12T20:39:57.236006Z	info	Error: failed to generate Istio configs from file [demoprofile.yaml] for the current version: 1.6.0, error: failed to fetch URL https://github.com/istio/istio/releases/download/1.6.0/istio-1.6.0-linux.tar.gz : 404 Not Found

Error: failed to generate Istio configs from file [demoprofile.yaml] for the current version: 1.6.0, error: failed to fetch URL https://github.com/istio/istio/releases/download/1.6.0/istio-1.6.0-linux.tar.gz : 404 Not Found
```

So a couple of questions: 
* Should the `proto: tag has too few fields: "-"` be present? 
* what's the best way to override for the 404 for testing of a beta? 

In terms of the docs: 
* Does this mean we support both istioctl and operator and not just istioctl?
* Can we document how to use this with istioctl?

**Comment by brian-avery** [comment]
@elfinhe any thoughts? Thanks.

**Comment by elfinhe** [comment]
sorry I got occupied by something this week.

> `proto: tag has too few fields: "-" `
@ostromart is this a regression in 1.6?

**Comment by elfinhe** [comment]
```
Error: failed to generate Istio configs from file [demoprofile.yaml] for the current version: 1.6.0, error: failed to fetch URL https://github.com/istio/istio/releases/download/1.6.0/istio-1.6.0-linux.tar.gz
```

maybe we should not support 1.6 -> 1.6 upgrade and give more helpful error. but this error will go away after we release 1.6.

**Comment by brian-avery** [comment]
Ah ok. I read the 404 error as being unable to download the content to upgrade to, not upgrade from. Thoughts on the docs? Is this what we want to support?

**Comment by brian-avery** [comment]
@ostromart @elfinhe Checking in on this. Do we need to update docs for 1.6 for in-place upgrades?

**Comment by brian-avery** [comment]
It looks like the functionality and docs are still broken #24029

**Comment by howardjohn** [comment]
Is upgrade really downloading from GitHub? this seems problematic in any serious environment

**Comment by brian-avery** [comment]
Yeah, it has a hardcoded path in the binary.

**Comment by brian-avery** [comment]
See:https://github.com/istio/istio/blob/975ff2f3224d6d5c31a0f63204730ea045455dd8/operator/cmd/mesh/upgrade.go#L59

**Comment by eperdeme** [comment]
We hit the same problem today. Did an upgrade from 1.5 -> 1.6 which didn't complete, can't run it again due to the above issue.

**Comment by howardjohn** [comment]
You can run just `istioctl manifest apply`, the upgrade command just does a few minor things like checking for changes to default configs etc
