### ISSUE TITLE
[Helm] gateway deployment doesn't support to configure `terminationGracePeriodSeconds` and `lifecycle`

### ISSUE THREAD

**Issue by kevinjom** [istio/istio#23749]
**Describe the feature request**
Add support for configuring `terminationGracePeriodSeconds` and `lifecycle` for gateway `deployement`
**Describe alternatives you've considered**
`kubectl patch`

**Additional context**

**Comment by howardjohn** [comment]
I would recommend taking a look at https://kustomize.io/ or overlays as part of istioctl install: https://preliminary.istio.io/docs/reference/config/istio.operator.v1alpha1/#K8sObjectOverlay for patching unsupported fields like this

**Comment by kevinjom** [comment]
Thanks @howardjohn for the reply. I think its still good to have native support for these things, as these two fields are quite frequently used for any non trivial applications.  I will prepare a PR some time this week if you are happy to merge it. At the moment, I will also look at the tools you mentioned 👍
