### ISSUE TITLE
When I use the domain name to access, I need to change the nodeport port and targerport on the ingress-gateway to be the same. Why? There is another problem. After modifying the nodeport, it can be accessed using the original nodeport. Is this a bug?

### ISSUE THREAD

**Issue by gongwei0921** [istio/istio#23750]
**Describe the feature request**

**Describe alternatives you've considered**

**Additional context**

**Comment by howardjohn** [comment]
Can you please fill out the issue template with how you installed, what commands you ran that failed, and what you changed that ddin't work as expected?

**Comment by gongwei0921** [comment]
My installation method in k8s is "istioctl manifest apply --set profile = demo". When I modify the nodeport in the ingressgateway of svc, I find that the original nodeport can also be accessed. You can also access it after trying it with other computers to eliminate session problems

**Comment by gongwei0921** [comment]
> Can you please fill out the issue template with how you installed, what commands you ran that failed, and what you changed that ddin't work as expected?

My installation method in k8s is "istioctl manifest apply --set profile = demo". When I modify the nodeport in the ingressgateway of svc, I find that the original nodeport can also be accessed. You can also access it after trying it with other computers to eliminate session problems

**Comment by tianvan** [comment]
I have same issue，https://github.com/istio/istio/issues/6319，istio‘s ingress does’t support that way,

**Comment by gongwei0921** [comment]
> I have same issue，[https://github.com/istio/istio/issues/6319，istio‘s](https://github.com/istio/istio/issues/6319%EF%BC%8Cistio%E2%80%98s) ingress does’t support that way,

thanks..  I take  a look

**Comment by howardjohn** [comment]
Can you add the config dump of the ingress and the request that failed? I suspect this is due to https://github.com/istio/istio/issues/25350

https://github.com/istio/istio/wiki/Troubleshooting-Istio for info on getting config dump

**Comment by howardjohn** [comment]
We don't have enough information to debug this. Please attach more info and reopen if this needs further investigation. Thanks!
