### ISSUE TITLE
why istio Round robin load balance not work as expect 

### ISSUE THREAD

**Issue by zziawan** [istio/istio#23752]
when Round robin load balance set a pod  responsed many requests  then turn  the next pod  .  it should not be a pod respose one request, then turn  the next  ?  can any one give a clue , thanks!

**Comment by howardjohn** [comment]
@zziawan I am not sure what you mean, can you give an example of the incorrect behavior?

**Comment by zziawan** [comment]
> @howardjohn 

for example， deploying a service with 2 pods, with round robin load balance.  when sending requests to the service with postman, traffic always the same pod, no traffic go to the other pod.  sending batch requests with jemeter,  you can see a certain num request responsed by the same pod  then the traffic go to the next pod. it shouldn't be one pod response only one request ? thanks ！

**Comment by ramaraochavali** [comment]
@zziawan Please refer to this FAQ https://www.envoyproxy.io/docs/envoy/latest/faq/load_balancing/concurrency_lb

**Comment by zziawan** [comment]
> @zziawan Please refer to this FAQ https://www.envoyproxy.io/docs/envoy/latest/faq/load_balancing/concurrency_lb
