### ISSUE TITLE
"x509: certificate signed by unknown authority" when not using default namespace istio-system

### ISSUE THREAD

**Issue by vincentserpoul** [istio/istio#23760]
**Bug description**

**Steps to reproduce the bug**

Install istio in a different namespace:

```
istioctl manifest apply \
   --set profile=minimal \
   --set components.pilot.enabled=true \
   --set addonComponents.ingressGateways.enabled=true \
   --set values.global.istioNamespace=ns-istio-system \
   --set values.global.mtls.enabled=true \
   --set values.global.mtls.auto=true \
   --set values.global.controlPlaneSecurityEnabled=true
```
Try to deploy any app, it will error with "x509: certificate signed by unknown authority" 
If you use the normal istio-system, it works.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

1.5.2

**How was Istio installed?**

see above

**Environment where bug was observed (cloud vendor, OS, etc)**

k3d

edited thanks to @howardjohn

**Comment by howardjohn** [comment]
Based on your command I am not sure where you are setting the different istio namespace?

**Comment by vincentserpoul** [comment]
> Based on your command I am not sure where you are setting the different istio namespace?

just fixed this, sorry, I copy pasted the fixed command

**Comment by howardjohn** [comment]
can you set `.Values.global.configNamespace` as well? To the same vlaue. We have improved this since then but looks like this is required in 1.5

**Comment by vincentserpoul** [comment]
same issue it seems (restarted from scratch cluster in k3d)
```istioctl manifest apply \
    --set profile=minimal \
    --set components.pilot.enabled=true \
    --set components.pilot.k8s.hpaSpec.minReplicas=2 \
    --set addonComponents.ingressGateways.enabled=true \
    --set addonComponents.ingressGateways.k8s.hpaSpec.minReplicas=2 \
    --set addonComponents.tracing.enabled=true \
    --set values.global.istioNamespace=ns-istio-system \
    --set values.global.configNamespace=ns-istio-system \
    --set addonComponents.prometheus.enabled=true \
    --set values.global.mtls.enabled=true \
    --set values.global.mtls.auto=true \
    --set values.global.controlPlaneSecurityEnabled=true
```
