### ISSUE TITLE
CNI causing 30-40s delay when starting new pods

### ISSUE THREAD

**Issue by rolandkool** [istio/istio#23770]
**Bug description**
With Istio CNI enabled, pods often experience a 30-40s delay before starting with the init container. 
The pod is created and shows a state of `Init:0/1` for 30 to 40s before continuing. The status of the init container is `PodInitializing`.

This delay affects our applications that need to rapidly scale up when load increases.

Looking at the Kubelet logs, the following is observed:

> May 07 20:42:17 internal-e34dfc9b-ppgj kubelet[1047]: {"level":"info","time":"2020-05-07T20:42:17.649806Z","msg":"nsenter args","nsenterArgs":["--net=/proc/1540604/ns/net","/home/kubernetes/bin/istio-iptables.sh","-p","1

And 40 seconds later:

> May 07 20:42:57 internal-e34dfc9b-ppgj kubelet[1047]: {"level":"info","time":"2020-05-07T20:42:57.746493Z","msg":"nsenter done: hostname: Host name lookup failure\nEnvironment:\n------------\nENVOY_PORT=\nINBOUND_CAPTURE......

**Expected behavior**
Pods should start almost instantly. The scripts done as part of CNI or the istio validation pod should execute quickly.

**Steps to reproduce the bug**
We've noticed the issue does not occur all the time, but in our environment (GKE 1.15 and Istio 1.5.2) it happens quite regularly.

**How was Istio installed?**
istioctl manifest apply

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE 1.15

**Comment by howardjohn** [comment]
Not an expert here, I wonder if `hostname: Host name lookup failure` is making something hang though. Might be intersting to compare the log of a fast pod to a slow pod?

**Comment by rolandkool** [comment]
Should have mentioned that, on a fast pod, the hostname error is not present.

> May 07 01:30:03 internal-e34dfc9b-ppgj kubelet[1047]: {"level":"info","time":"2020-05-07T01:30:03.794260Z","msg":"nsenter args","nsenterArgs":["--net=/proc/19640/ns/net","/home/kubernetes/bin/istio-iptables.sh","-p","150
01","-u","1337","-m","REDIRECT","-i","*","-b","*","-d","15020,15090","-o","15020","-x","","-k",""]}
May 07 01:30:03 internal-e34dfc9b-ppgj kubelet[1047]: {"level":"info","time":"2020-05-07T01:30:03.922107Z","msg":"nsenter done: Environment:\n------------\nENVOY_PORT=\nINBOUND_CAPTURE_PORT=\nISTIO_INBOUND_INTERCEPTION_M.....

In this case, the nsenter was done within a second.

**Comment by rolandkool** [comment]
The `istio-iptables.sh` script has a single `hostname` call: https://github.com/istio/cni/blob/master/tools/packaging/common/istio-iptables.sh#L267

**Comment by stewartbutler** [comment]
OK, I think it is safe to assume that the hostname lookup issue is related
to the source of the problem, then.

A few debugging questions:
1) How is DNS configured in your system?
2) Do you notice that the slow pods are correlated with cluster events
(e.g. do they appear only on newly started or restarted nodes)?
3) Are the slow pods isolated to a single node or set of nodes? Or are they
random?
4) Do nodes with slow pod startup times also have pods with fast startup
times? Or are all pod startups on those nodes slow?
5) Is your network ipv4? ipv6? Dual stack?

**Comment by rolandkool** [comment]
1) Our setup is GKE and no customizations are done on the nodes themselves. There are Cloud DNS zones active so I expect those zones to be hit by the DNS setup on GCE nodes. 
2) Slow startups are also observed on nodes that have been running for a while. Also both regular and pre-emptibles.
3) We have not checked. It seems random, but we can try to see if it could be related to for example a specific zone.
4) We need to verify this.
5) GKE, so IPv4 only

**Comment by rolandkool** [comment]
Hi

We did some more digging and managed to track down the cause of the delay. The issue is caused by the DNS server not being reachable due to a network policy that is blocking the IP address of the metadata server (169.254.169.254). As the metadata server can leak all kinds of sensitive data, access to it is blocked by default for all our applications. 
However, this IP address is also what is configured as the DNS server on each GKE node. As the DNS call (probably from the `hostname --ip-address` command) is being done from inside the pod (or sandbox?), restricted to its network namespace via nsenter, but using the hosts DNS server, it is not able to reach it and times out after some time (30 seconds?).

We can work around it by creating another network policy to allow this IP address but only for DNS calls. However, would it be a an option to adjust the script to retrieve the Pods IP address using different commands (maybe from /proc somewhere?)

**Comment by stewartbutler** [comment]
It looks like checking `/proc/net/if_inet6` may work for systems that have proc enabled. I'll throw together a prototype to see if that will work.
