### ISSUE TITLE
Component Introspection docs

### ISSUE THREAD

**Issue by esnible** [istio/istio#23779]
Using https://preliminary.istio.io/docs/ops/diagnostic-tools/controlz/

The doc says "Mixer, Pilot, and Galley all implement the ControlZ functionality" and this is confusing because there isn't really a mixer nor galley.  Everywhere it says "Mixer, Galley, Pilot" it should say "Istiod".

**Comment by howardjohn** [comment]
There is still a mixer, just not the others

**Comment by esnible** [comment]
Good point!  Should it say "mixers"?  Because there are two.  Maybe it should say "Telemetry Mixer and Policy Mixer"?

I installed with

```
istioctl install \
   --set components.telemetry.enabled=true \
   --set components.policy.enabled=true \
   && say installed || say failed
```

to get these mixers.
