### ISSUE TITLE
restore 'istioctl authn' and have Pilot provide this information

### ISSUE THREAD

**Issue by esnible** [istio/istio#23776]
Authn information was removed in https://github.com/istio/istio/pull/22407

This was removed in support of https://github.com/istio/istio/issues/21821 because the information was wrong because Pilot's debug endpoint was using the CRs that are no longer present.

The information is needed for 'istioctl x describe' #23388 .  The documentation at https://preliminary.istio.io/docs/ops/diagnostic-tools/istioctl-describe/ still shows `describe` saying things like "Pilot reports that pod enforces HTTP/mTLS and clients speak HTTP"

**Comment by esnible** [comment]
@myidpt @liminw Can Security Workgroup take on this issue?  Istiod SHOULD supply enough information that the authn troubleshooting command can be implemented.  I am happy to help with _istioctl_ but lack the knowledge of how to gather then information within the control plane and what the user expects to see as output.

**Comment by myidpt** [comment]
@esnible This is in our 1.8 release plan.

**Comment by esnible** [comment]
@myidpt Is there a PR I can test, or documents I can read to help on this item?

**Comment by liminw** [comment]
I don't think we have a doc or PR yet. But @yangminzhu can give more accurate update on it.

**Comment by esnible** [comment]
@yangminzhu is this on your 1.9 roadmap?

**Comment by liminw** [comment]
It is P1 on security WG 1.9 release plan.

**Comment by esnible** [comment]
@liminw @yangminzhu Could you also comment on https://github.com/istio/istio/issues/26123 ?  It would be great if some of the ideas raised in that issue could be incorporated into 'istioctl authn'

**Comment by hanxiaop** [comment]
@liwenhao0810 Is `authn` still a needed command in istioctl? I thought it's already provided in `istioctl x describe`. If yes, is it going to be similar to what we have done in `describe`?

**Comment by liwenhao0810** [comment]
Don't think so, IIRC `authn` was not agreed approach in the community and we added authn debug support in `describe`.

**Comment by hanxiaop** [comment]
> Don't think so, IIRC `authn` was not agreed approach in the community and we added authn debug support in `describe`.

Thanks for the info, we can probably close this now since the debug info is provided and unless there is a need for the command.
