### ISSUE TITLE
Envoy terminates if user follows "Customizing Istio Metrics"

### ISSUE THREAD

**Issue by esnible** [istio/istio#23782]
Using 1.6.0-beta.1 the instructions caused me to crash my pods and put them into a `CrashLoopBackOff` state.

Step 3 says to use a text editor and "locate the envoy.wasm.stats extension configuration."  I found three such examples.  I modified the first one.  After my step 4 changes, it looks like

```
        name: istio.stats
        typed_config:
          '@type': type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
          value:
            config:
              configuration: |
                {
                  "debug": "false",
                  "stat_prefix": "istio",
                  "metrics": [
                   {
                     "name": "requests_total",
                     "dimensions": {
                       "destination_port": "destination.port",
                       "request_host": "request.host"
                      }
                    }
                 ]
                }
```

(This was somewhat tricky because YAML requires extra spacing.  I believe I got it right.)

Step 6 is to apply an annotation "using the following command".  No command is given ... we see text to type into `kubectl edit deployment`.  I did use a command so that I could produce repeatable output for this Issue:

```
kubectl patch deployment productpage-v1 --type=json --patch='[{"op": "add", "path": "/spec/template/metadata/annotations", "value": {"sidecar.istio.io/extraStatTags": "destination_port,request_host"}}]'
```

After that the pods go into CrashLoopBackOff.  `kubectl logs` shows

```
2020-05-12T20:32:05.569257Z	critical	envoy main	[external/envoy/source/server/server.cc:97] error initializing configuration 'etc/istio/proxy/envoy-rev0.json': Tag name 'destination_port' specified twice.
Tag name 'destination_port' specified twice.
2020-05-12T20:32:05.573563Z	error	Epoch 0 exited with error: exit status 1
2020-05-12T20:32:05.573608Z	info	No more active epochs, terminating
```

**Comment by mandarjog** [comment]
@gargnupur can you take a look at this?

**Comment by gargnupur** [comment]
@esnible : Does this error go away if you don't do step 6 and still see the metrics?

**Comment by esnible** [comment]
https://preliminary.istio.io/docs/tasks/observability/metrics/customize-metrics/

OK, I deleted and recreated bookinfo but skipped step 6.  Bookinfo works.

I supplied some load and did `kubectl exec reviews-v1-5cddfdfd64-f54qf -c istio-proxy -- curl 'localhost:15000/stats/prometheus' | grep request_host`.  Also tried `grep destination_port`.  Neither had data.

There was lots of data if I did `grep istio`.  Repeated the curl/grep with productpage pod, same results.

**Comment by douglas-reid** [comment]
@esnible repeating what I added in the chat. please modify all three places in step 3.

**Comment by esnible** [comment]
OK, made the JSON change to all three places in step three.  I did this using a tricky `kubectl patch` but I believe I did it correctly.  HOWEVER, THE VALUES SENT TO PROMETHEUS ARE NOT WHAT I EXPECTED.

First, here is my configuration:
```
kubectl -n istio-system get envoyfilter stats-filter-1.6 -o jsonpath='{.spec.configPatches[0].patch.value.typed_config.value.config.configuration}'
// { "debug": "false", "stat_prefix": "istio", "metrics": [ { "name": "requests_total", "dimensions": { "destination_port": "destination.port", "request_host": "request.host" } } ] }
kubectl -n istio-system get envoyfilter stats-filter-1.6 -o jsonpath='{.spec.configPatches[1].patch.value.typed_config.value.config.configuration}'
// { "debug": "false", "stat_prefix": "istio", "metrics": [ { "name": "requests_total", "dimensions": { "destination_port": "destination.port", "request_host": "request.host" } } ] }
kubectl -n istio-system get envoyfilter stats-filter-1.6 -o jsonpath='{.spec.configPatches[2].patch.value.typed_config.value.config.configuration}'
// { "debug": "false", "stat_prefix": "istio", "disable_host_header_fallback": "true", "metrics": [ { "name": "requests_total", "dimensions": { "destination_port": "destination.port", "request_host": "request.host" } } ] }
```

Next, here is the output of `kubectl exec reviews-v1-5cddfdfd64-f54qf -c istio-proxy -- curl 'localhost:15000/stats/prometheus' | grep request_host`:

```
istio_requests_total{response_code="200",reporter="destination",source_workload="productpage-v1",source_workload_namespace="default",source_principal="spiffe://cluster.local/ns/default/sa/bookinfo-productpage",source_app="productpage",source_version="v1",destination_workload="reviews-v1",destination_workload_namespace="default",destination_principal="spiffe://cluster.local/ns/default/sa/bookinfo-reviews",destination_app="reviews",destination_version="v1",destination_service="reviews.default.svc.cluster.local",destination_service_name="reviews",destination_service_namespace="default",destination_port="x#",request_protocol="http",request_host="reviews:9080",response_flags="-",grpc_response_status="",connection_security_policy="mutual_tls",source_canonical_service="productpage",destination_canonical_service="reviews",source_canonical_revision="v1",destination_canonical_revision="v1"} 12
```

The problem is the `request_host="reviews:9080"` (request_host same as destination?) and the `destination_port="x#"` (I expected 9080, or at least an integer)

**Comment by douglas-reid** [comment]
what value did you expect for `request_host`?  that looks reasonable to me, assuming the client used a host header of `reviews:9080`.

`destination_port` indeed looks problematic. is it potentially a problematic UTF-8 encoding or something? what does it look like in prom? do all the `destination_port` values have `x#` or are they random strings?

**Comment by gargnupur** [comment]
`destination_port` doesn't look right... will try to repro this in istio/proxy..

**Comment by jacob-delgado** [comment]
I was able to replicate this. I've attached my filters and file I used to install (with MeshConfig)

I installed using `./istioctl manifest apply --set profile=default -f extra_stat_tags.yaml`
[filter-iop.tar.gz](https://github.com/istio/istio/files/4625226/filter-iop.tar.gz)

**Comment by gargnupur** [comment]
@jacob-delgado : what if you don't set extraStatTags? do you see the crash still?

**Comment by jacob-delgado** [comment]
@gargnupur If I only modify the `stats-filter-1.6` the pods continue to stage.

**Comment by gargnupur** [comment]
@jacob-delgado : and you see the configured attributes in istio_requests_total in prometheus right?
@mandarjog , @douglas-reid : I don't think we need the extraStatsTags option in documentation? We see the new attributes in prometheus without it and with it, it thinks that definition of the attribute is happening twice and thus crashes. 
And I think `destination_port` is coming up as random in prometheus, because in istio/proxy we see it as "___NO__________",

**Comment by esnible** [comment]
> what value did you expect for `request_host`? that looks reasonable to me, assuming the client used a host header of `reviews:9080`.

My misunderstanding?  I expected `request.host` to be the requesting host/workload, not the HOST header on the HTTP request.

> what does it look like in prom? do all the `destination_port` values have `x#` or are they random strings?

In the Prometheus web UI I see the same `destination_port="x#"` that I saw with _curl_.

**Comment by gargnupur** [comment]
@kyessenov 's suggestion works(https://github.com/istio/envoy/pull/215).. of changing it to string(int_value)

so, I think we should do following change in the doc:
1) Remove extraStatTag step for now
2) and change `destination_port` to `string(destination_port)` and add a note that for int values, add a string label above.
