### ISSUE TITLE
Istio blocking initContainer traffic (using Istio CNI)

### ISSUE THREAD

**Issue by Atreus-Technologies** [istio/istio#23802]
Hoping someone can help with this issue. I have a few initContainers which need to reach out to download various bits and pieces before my application containers spin up. 

Currently I'm getting errors trying to deal with any HTTP(S) traffic but IP layer traffic seems fine.

I have the CNI plugin running (rather than using Istio's traditional initContainer approach to configure IPTABLES).

E.g., in my initContainer -

- If I try to run `curl www.google.com` I get back `0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0curl: (7) Failed to connect to 2404:6800:4006:806::2004: Cannot assign requested address`
- If  I just run a simple `ping www.google.com` everything is fine and it finds the address.

I see similar behaviour on both Busybox and Alpine images, using both curl and wget. 

My versions are below - 

```
client version: 1.4.0
citadel version: 1.4-alpha.c4ec4b8c102da86d4d02f4b268f9af60a35dee1c
galley version: 1.4-alpha.ee4df7fb5e7a9069a6fc0c9de85b501a6c791c38
ingressgateway version: 1.4-alpha.c4ec4b8c102da86d4d02f4b268f9af60a35dee1c
pilot version: 1.4-alpha.400f9e3780af62b1742372085b45317d8fbe9810
policy version: 1.4-alpha.c4ec4b8c102da86d4d02f4b268f9af60a35dee1c
sidecar-injector version: 1.4-alpha.ee4df7fb5e7a9069a6fc0c9de85b501a6c791c38
data plane version: 1.4-alpha.1c963ed31062b56c866ac8a601df0e91edefc12d (4 proxies), 1.4-alpha.8e7ab73399db64fa37f3af190c6caa1a36e66586 (27 proxies), 1.4-alpha.c4ec4b8c102da86d4d02f4b268f9af60a35dee1c (12 proxies), 1.3.3 (4 proxies), 1.4-alpha.1df6a42f1f10b472fde05a13e588bdbf67927869 (17 proxies)
```

**Comment by howardjohn** [comment]
This is a limitation of CNI. Because it sets up iptables rules before init containers, the traffic will be redirected to Envoy which is not yet running. There are a few workarounds that you can use. You can run as UID 1337 in the init container, or disable iptables for specific port/ip ranges (https://istio.io/docs/reference/config/annotations/).

**Comment by howardjohn** [comment]
cc @lambdai @stewartbutler if my info is outdated

**Comment by stewartbutler** [comment]
That sounds accurate to me.

**Comment by Atreus-Technologies** [comment]
Thanks all, this is the info I needed. On reflection, this is probably a weakness of K8s, as it should probably support something like runlevels rather than a binary init/application container distinction.

Would it be worth someone (potentially me) updating the CNI docs to reflect that using it will break initContainer's usual behaviour? Running as 1337 would probably cause issues with PSPs, but it is a good workaround to have front and centre in the docs.

**Comment by michalzxc** [comment]
It is still a issue

```
~❯ kubectl --namespace dctest04 logs kimlexir-cron-9f6b66867-2xjv4 kimlexir-migrate
time="2020-10-05T16:16:59Z" level=error msg="failed to request new Vault token" app=vault-env err="Put \"https://vault.bootstrap:8200/v1/auth/kubernetes/login\": dial tcp 172.24.120.198:8200: connect: connection refused"
time="2020-10-05T16:17:03Z" level=error msg="failed to request new Vault token" app=vault-env err="Put \"https://vault.bootstrap:8200/v1/auth/kubernetes/login\": dial tcp 172.24.120.198:8200: connect: connection refused"
time="2020-10-05T16:17:08Z" level=error msg="failed to request new Vault token" app=vault-env err="Put \"https://vault.bootstrap:8200/v1/auth/kubernetes/login\": dial tcp 172.24.120.198:8200: connect: connection refused"
time="2020-10-05T16:17:13Z" level=error msg="failed to request new Vault token" app=vault-env err="Put \"https://vault.bootstrap:8200/v1/auth/kubernetes/login\": dial tcp 172.24.120.198:8200: connect: connection refused"
time="2020-10-05T16:17:18Z" level=error msg="failed to request new Vault token" app=vault-env err="Put \"https://vault.bootstrap:8200/v1/auth/kubernetes/login\": dial tcp 172.24.120.198:8200: connect: connection refused"
time="2020-10-05T16:17:23Z" level=error msg="failed to request new Vault token" app=vault-env err="Put \"https://vault.bootstrap:8200/v1/auth/kubernetes/login\": dial tcp 172.24.120.198:8200: connect: connection refused"
time="2020-10-05T16:17:28Z" level=error msg="failed to request new Vault token" app=vault-env err="Put \"https://vault.bootstrap:8200/v1/auth/kubernetes/login\": dial tcp 172.24.120.198:8200: connect: connection refused"
time="2020-10-05T16:17:33Z" level=error msg="failed to request new Vault token" app=vault-env err="Put \"https://vault.bootstrap:8200/v1/auth/kubernetes/login\": dial tcp 172.24.120.198:8200: connect: connection refused"
time="2020-10-05T16:17:37Z" level=error msg="failed to request new Vault token" app=vault-env err="Put \"https://vault.bootstrap:8200/v1/auth/kubernetes/login\": dial tcp 172.24.120.198:8200: connect: connection refused"
time="2020-10-05T16:17:42Z" level=error msg="failed to request new Vault token" app=vault-env err="Put \"https://vault.bootstrap:8200/v1/auth/kubernetes/login\": dial tcp 172.24.120.198:8200: connect: connection refused"
time="2020-10-05T16:17:48Z" level=error msg="failed to request new Vault token" app=vault-env err="Put \"https://vault.bootstrap:8200/v1/auth/kubernetes/login\": dial tcp 172.24.120.198:8200: connect: connection refused"
time="2020-10-05T16:17:52Z" level=error msg="failed to request new Vault token" app=vault-env err="Put \"https://vault.bootstrap:8200/v1/auth/kubernetes/login\": dial tcp 172.24.120.198:8200: connect: connection refused"
time="2020-10-05T16:17:57Z" level=error msg="failed to request new Vault token" app=vault-env err="Put \"https://vault.bootstrap:8200/v1/auth/kubernetes/login\": dial tcp 172.24.120.198:8200: connect: connection refused"
time="2020-10-05T16:18:02Z" level=error msg="failed to request new Vault token" app=vault-env err="Put \"https://vault.bootstrap:8200/v1/auth/kubernetes/login\": dial tcp 172.24.120.198:8200: connect: connection refused"
time="2020-10-05T16:18:07Z" level=error msg="failed to request new Vault token" app=vault-env err="Put \"https://vault.bootstrap:8200/v1/auth/kubernetes/login\": dial tcp 172.24.120.198:8200: connect: connection refused"
time="2020-10-05T16:18:11Z" level=error msg="failed to request new Vault token" app=vault-env err="Put \"https://vault.bootstrap:8200/v1/auth/kubernetes/login\": dial tcp 172.24.120.198:8200: connect: connection refused"
time="2020-10-05T16:18:16Z" level=error msg="failed to request new Vault token" app=vault-env err="Put \"https://vault.bootstrap:8200/v1/auth/kubernetes/login\": dial tcp 172.24.120.198:8200: connect: connection refused"
time="2020-10-05T16:18:21Z" level=error msg="failed to request new Vault token" app=vault-env err="Put \"https://vault.bootstrap:8200/v1/auth/kubernetes/login\": dial tcp 172.24.120.198:8200: connect: connection refused"
time="2020-10-05T16:18:25Z" level=fatal msg="failed to create vault clienttimeout [1m30s] during waiting for Vault token" app=vault-env
```

It seems like it is not even trying to enable networking for init container.

**Comment by howardjohn** [comment]
@michalzxc we are not because its impossible/very hard without https://github.com/kubernetes/enhancements/issues/753 which we are actively working with k8s to get solved.

**Comment by michalzxc** [comment]
I thought that problem is that init container starts before network is set
That is why I added long timeout and retry, but it is retrying 2-3 minutes and there is no point when network becomes available

Shouldn't making init container wait for network be enough ?

**Comment by howardjohn** [comment]
No, there will be no network until Envoy is running. Iptables rules will direct traffic to Envoy, but envoy is not there, so you get connection refused. Envoy only runs in normal container so its not around for init

**Comment by Atreus-Technologies** [comment]
@howardjohn, thanks for mentioning the parent issue on the K8s side, and thanks for the very cogent explanation of what's happening with this issue. That is one potentially huge area for K8s to be looking at, I'll be tracking that one myself to see how it turns out.

**Comment by ajohnstone** [comment]
@howardjohn Why/how does using UID 1337 in the init container work around this issue? I can't see a logical answer why that has any effect?
Its unclear to me whether to go down the route of using istio-cni? Or make init containers privileged to work with selinux.

**Comment by howardjohn** [comment]
With the iptables redirect, we need to make sure traffic from envoy itself
is not redirected, otherwise we end up with an infinite loop. So any
traffic from UID 1337 is not captured

**Comment by keithmattix** [comment]
So, now that the sidecar KEP is pretty much [dead in the water](https://github.com/kubernetes/enhancements/issues/753), is there any hope of solving this without a monkey patch?

**Comment by samarara** [comment]
We had an init container with rclone setup to retrieve some s3 artifacts that had this issue. I was able to get around by adding the following annotation to the pod spec: 
```
      traffic.sidecar.istio.io/excludeOutboundPorts: "443"
```
I need to see what the implications of this is though. Haven't investigated beyond this.

**Comment by wmashal** [comment]
> We had an init container with rclone setup to retrieve some s3 artifacts that had this issue. I was able to get around by adding the following annotation to the pod spec:
> 
> ```
>       traffic.sidecar.istio.io/excludeOutboundPorts: "443"
> ```
> 
> source: https://istio.io/latest/docs/reference/config/annotations/
> 
> I need to see what the implications of this is though. Haven't investigated beyond this.

@howardjohn can u confirm if this solution better that set runAsUser 1337 in the initContainer ?

**Comment by kingbj940429** [comment]
> We had an init container with rclone setup to retrieve some s3 artifacts that had this issue. I was able to get around by adding the following annotation to the pod spec:
> 
> ```
>       traffic.sidecar.istio.io/excludeOutboundPorts: "443"
> ```
> 
> source: https://istio.io/latest/docs/reference/config/annotations/
> 
> I need to see what the implications of this is though. Haven't investigated beyond this.

@samarara 
I think by setting it to `traffic.sidecar.istio.io/excludeOutboundPorts : "443"`,  outbound traffic is not redirected to envoy, it's straight out of the pod.

It's just my guess.

If init container forward to 80 port, `traffic.sidecar.istio.io/excludeOutboundPorts : "443"` doesn't work
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-init
  annotations:
    traffic.sidecar.istio.io/excludeOutboundPorts: "443"
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80

  initContainers:
    - name: init-check-google
      image: curlimages/curl:latest
      command:
        - "sh"
        - "-c"
        - "echo 'Checking connectivity to google.com...' && curl -sv http://www.google.com:80 && echo 'Google is reachable.'"

```
![Image](https://github.com/user-attachments/assets/ab40f004-1300-4736-a3af-92e56a3a32d8)


Anyway `traffic.sidecar.istio.io/excludeOutboundPorts : "443"` can be good solution

**Comment by dpfister-nice** [comment]
Looks like since the last comment in this thread the Sidecar KEP has been merged and graduated to stable. Can this be reopened to eventually get a patch or is this being tracked somewhere else now?

For now setting `runAsUser: 1337` has done the trick for us but it would be nice to not have to keep track of this and constantly train our various developer teams on this specific use case.
