### ISSUE TITLE
Istio 1.5.4 should be promoted as a release since people shouldn't use 1.5.3

### ISSUE THREAD

**Issue by metacosm** [istio/istio#23808]
**Bug description**
1.5.3 is still being promoted as the latest release which `curl -L https://istio.io/downloadIstio | sh -` to download it instead of 1.5.4

**Expected behavior**
1.5.4 should be downloaded

**Comment by howardjohn** [comment]
Thanks, sorry about that. Its published now: https://github.com/istio/istio/releases/tag/1.5.4
