### ISSUE TITLE
Accessing External Services document is out of date: outboundTrafficPolicy not found in istio configmap in istio-system namespace

### ISSUE THREAD

**Issue by jacob-delgado** [istio/istio#23803]
**Bug description**
Unsure if this is a docs bug or a bug in Istio.

Following https://preliminary.istio.io/docs/tasks/traffic-management/egress/egress-control/

when I run Step 1 ```kubectl get configmap istio -n istio-system -o yaml | grep -o "mode: ALLOW_ANY" | uniq``` nothing is returned.

When I look at the istio configmap in the istio-system namespace it is not present.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[X] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

```
meshConfig:
  outboundTrafficPolicy:
    mode: ALLOW_ANY
```

is in the configmap.

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

1.6.0-beta.1

**How was Istio installed?**

istioctl manifest apply

**Environment where bug was observed (cloud vendor, OS, etc)**

Kops cluster running on AWS

**Comment by jacob-delgado** [comment]
cc @howardjohn @ostromart Do either of you have any information?

**Comment by irisdingbj** [comment]
encounter same issue

**Comment by howardjohn** [comment]
Its a docs bug. The default is `ALLOW_ANY`. We are hoping to make the mesh config file just overrides for the defaults, so it should be empty for new installs in the future
