### ISSUE TITLE
ingress-gateway does not report a span for an inbound request

### ISSUE THREAD

**Issue by georgyturevich** [istio/istio#23815]
**Bug description**
Jaeger shows only one span for an ingress-gateway where the  `upstream_cluster` has the `outbound|9080||productpage.default.svc.cluster.local` when I send a request to ingress-gateway with the `x-client-trace-id` header

**Expected behavior**
I expect to see two spans in Jaeger where the first one has the `upstream_cluster` tag equal to `inbound|???`. For example, in the same trace, I can see both inbound and outbound spans for the `productpage.default` service.

I see that a comment with a similar problem was reported here https://github.com/istio/istio/issues/13508#issuecomment-490910575, and there is a suggestion to use `x-client-trace-id` header according to the Envoy documentation, but it did not help.

**Steps to reproduce the bug**
- Install Istio.
- Install Bookinfo application and a Gateway for it
```
kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml
kubectl apply -f samples/bookinfo/networking/bookinfo-gateway.yaml
```
- Send requests with `x-client-trace-id` headers to productpage
```
for i in `seq 1 20`; do curl -s -o /dev/null -H "x-client-trace-id: 4d4d2b99-f0d7-996c-a2e1-e119e6873000" http://$GATEWAY_URL/productpage; done
```
- Check traces in Jaeger

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
$ istioctl version --remote
client version: 1.5.3
control plane version: 1.5.3
data plane version: 1.5.3 (9 proxies)
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:47:22Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:39:02Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
Istio was installed with the help of the `istioctl`
```istioctl manifest apply --set profile=demo```
then the boo

**Environment where bug was observed (cloud vendor, OS, etc)**
minikube, I also see the same behavior in EKS

**Comment by verysonglaa** [comment]
@georgyturevich Did you solve this? I am still running into the same issue with 1.13.2

**Comment by zirain** [comment]
right now there's now inbound for gateway

**Comment by verysonglaa** [comment]
@objectiser I guess this is the same situation which was mentioned in https://github.com/envoyproxy/envoy/issues/7751#issuecomment-516554010 . I am just not sure if it has been resolved (so that you can create server and client spans for edge proxys). Do you know the current situation?

**Comment by objectiser** [comment]
@verysonglaa sorry haven't been involved in the project for some time, so don't know.

**Comment by msonnleitner** [comment]
@zirain Does this that there is in general no possibility to retrieve inbound traces from Gateways? If so, this should probably be reopened
