### ISSUE TITLE
Improve pilot debugging around multi-network

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#23828]
I have debugged 3 issues relating to networking in the past few weeks. All 3 times it was needle in haystack, we have very little visibility.

Example issues:
* ISTIO_META_REQUESTED_NETWORK_VIEW isn't as expected, so we miss endpoints
* `fromRegistry: kubernetes` instead of Kubernetes - we added `istioctl analyzer` for this
* ISTIO_META_NETWORK=default but endpoints network is `""` because meshNetworks was not configured

All of these were user errors, but they are extremely easy to make and extremely hard to debug. We need to add some more visibility around this, through istioctl analyze, debug endpoints, or changes to MC to make it hard to make mistakes

**Comment by su225** [comment]
@howardjohn - Is this still open? I'm interested to pick this up.

**Comment by stevenctl** [comment]
Not stale. 

For the `fromRegistry` stuff – maybe the analyzer should check that the value there is either equal to the cluster name or is the name of one of the clusters specified in remote-secrets. A debug endpoint to list the clusters a given istiod is watching could be helpful here.
