### ISSUE TITLE
Updating (Envoy to) Proxy to Istio

### ISSUE THREAD

**Issue by jacob-delgado** [istio/istio#23823]
**Describe the feature request**

When istio/envoy is updated, we have to wait for a build, manually update istio/proxy, wait again for that to build and then update istio/istio with the appropriate shas. This should be triggered by acceptance into istio/envoy.

There are also only times when istio/proxy needs to be updated (not istio/envoy) and that needs to be updated in istio/istio.

This makes it easy for human error to not update envoy or proxy in the same branch as it is time-consuming to validate.

**Describe alternatives you've considered**

**Additional context**

See https://github.com/istio/istio/pull/23811 based on https://github.com/istio/proxy/pull/2850 based on https://github.com/istio/envoy/pull/214

This can have complications if istio/envoy is not the source of envoy for the istio project. I believe it is, but that could change in the future. Thoughts @PiotrSikora @jplevyak @bianpengyuan @douglas-reid @mandarjog @kyessenov?

**Comment by mandarjog** [comment]
Updating istio/proxy --> istio/istio makes sense.
Updating istio/envoy --> istio/proxy involves API changes from time to time. But I am ok with it working auto magically, so long as it is not disruptive to dev flow.

**Comment by bianpengyuan** [comment]
Is the proposed automation to update proxy sha in istio/istio when envoy sha is updated in istio/proxy? That sounds reasonable to me.

**Comment by jacob-delgado** [comment]
Travis recently did some great work to have an issue created when /cherry-pick RELEASE fails. In the event of a failure it'd be great to have something similar. Another issue could be is that when envoy-wasm (and istio/envoy) get merged into upstream envoyproxy/envoy this workflow could break. I don't know what the horizon is for getting envoy-wasm merged into upstream envoyproxy/envoy is.

**Comment by ericvn** [comment]
I believe this is finished for proxy. There are a number of PRs involved, but lasted test-infra is https://github.com/istio/test-infra/pull/2808 and in istio https://github.com/istio/istio/pull/25651.

**Comment by ericvn** [comment]
Currently istio/proxy uses envoyproxy/envoy-wasm as as source and there isn't a way for adding automation for that change.

For now, I don't think there is any additional work we can do. Please feel free to reopen if I missed something or additional work is needed.
