### ISSUE TITLE
TLS origination for egress traffic gets 503

### ISSUE THREAD

**Issue by JimmyCYJ** [istio/istio#23821]
**Bug description**
I am following the user guide and testing this step
https://preliminary.istio.io/docs/tasks/traffic-management/egress/egress-tls-origination/#tls-origination-for-egress-traffic

$kubectl exec -it $SOURCE_POD -c sleep -- curl -sL -o /dev/null -D - http://edition.cnn.com/politics
HTTP/1.1 503 Service Unavailable
date: Wed, 13 May 2020 18:32:28 GMT
server: envoy
content-length: 0

curl to https succeeds
$kubectl exec -it $SOURCE_POD -c sleep -- curl -sL -o /dev/null -D - https://edition.cnn.com/politics
HTTP/2 200 
content-type: text/html; charset=utf-8
x-servedbyhost: ::ffff:127.0.0.1

**Expected behavior**
curl command should return 200

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
$istioctl version
client version: 1.6.0-beta.1
control plane version: 1.6.0-beta.1
data plane version: 1.6.0-beta.1 (3 proxies)

**How was Istio installed?**
$istioctl manifest apply

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

**Comment by nrjpoddar** [comment]
I think we need to address this and shouldn’t release with this regression. @jacob-delgado @brian-avery @costinm feels like a release blocker. Don’t have time today to test/triage it.

**Comment by jacob-delgado** [comment]
I confirmed that this does happen. I've attached all of my envoy configs to help make it easier.
[envoy-config.tar.gz](https://github.com/istio/istio/files/4632036/envoy-config.tar.gz)

**Comment by lambdai** [comment]
The listener and http conn manager looks good. HCM has the route and referring to cluster `outbound|443|tls-origination|edition.cnn.com` as expected.

**Comment by lambdai** [comment]
That cluster is originated from the virtual service. It is missing in envoy config.

**Comment by lambdai** [comment]
My latest finding is that pilot attempted to generate the cluster but somehow pilot cannot fill the hostname for that strict DNS cluster. 
The strict dns cluster with no endpoint is considered a invalid cluster config. Pilot won't push to envoy.

At my side these pilot logs are dumped:
```
        "outbound|443|tls-origination|edition.cnn.com": {
            "proxy": "sleep-6bdb595bcb-nbv4l.default",
            "message": "STRICT_DNS cluster without endpoints outbound|443|tls-origination|edition.cnn.com found while pushing CDS"
        },
        "outbound|80|tls-origination|edition.cnn.com": {
            "proxy": "sleep-6bdb595bcb-nbv4l.default",
            "message": "STRICT_DNS cluster without endpoints outbound|80|tls-origination|edition.cnn.com found while pushing CDS"
        }
```

**Comment by howardjohn** [comment]
https://github.com/istio/istio/commit/4591e5efbe40f1aa85e26ead850df7cd7901d395 is probably root cause

**Comment by howardjohn** [comment]
Suggest a fix similar to:

```diff
$ gd
diff --git a/pilot/pkg/networking/core/v1alpha3/cluster_builder.go b/pilot/pkg/networking/core/v1alpha3/cluster_builder.go
index 73d8e53cb..3ed0273d5 100644
--- a/pilot/pkg/networking/core/v1alpha3/cluster_builder.go
+++ b/pilot/pkg/networking/core/v1alpha3/cluster_builder.go
@@ -101,6 +101,8 @@ func (cb *ClusterBuilder) applyDestinationRule(proxy *model.Proxy, cluster *apiv
                var lbEndpoints []*endpoint.LocalityLbEndpoints
                if cluster.GetType() != apiv2.Cluster_EDS && len(subset.Labels) != 0 {
                        lbEndpoints = buildLocalityLbEndpoints(proxy, cb.push, proxyNetworkView, service, port.Port, []labels.Instance{subset.Labels})
+               } else if cluster.GetType() != apiv2.Cluster_EDS {
+                       lbEndpoints = buildLocalityLbEndpoints(proxy, cb.push, proxyNetworkView, service, port.Port, nil)
                }

                subsetCluster := cb.buildDefaultCluster(subsetClusterName, cluster.GetType(), lbEndpoints,
```

I need to head out though so won't be able to send out the PR/fully test

**Comment by lambdai** [comment]
Build endpoint regardless the label? Pretty sure it will gain more endpoint so looks like the right direction

**Comment by jacob-delgado** [comment]
Testing locally. Will report back.

**Comment by howardjohn** [comment]
The current code says "if there are labels select only those. If there are no labels select none"

The old code / spec / docs says " if there are labels select only those, if there are no labels select all endpoints."

if you look at the commit I linked you can see where this changed

**Comment by jacob-delgado** [comment]
Testing the code locally it works and the test case passes. Great work @howardjohn.

**Comment by mandarjog** [comment]
@howardjohn This is excellent work !  Now please do enjoy your time off.

**Comment by jacob-delgado** [comment]
Verified in 1.6.0-rc.3
