### ISSUE TITLE
Ingress in CrashLoopBackoff / Envoy backtrace on invalid EnvoyFilter

### ISSUE THREAD

**Issue by esnible** [istio/istio#23834]
Reproduced under 1.6.0 beta.1 trying to troubleshoot https://github.com/istio/istio/issues/23782

The instructions at https://preliminary.istio.io/docs/tasks/observability/metrics/customize-metrics/ have the user customizing EnvoyFilter.  While testing that page I damaged my EnvoyFilter such that the Ingress crashed and wouldn't restart.

It was my own fault, I left off a comma and quotes in some JSON that was embedded in some YAML.

After running the commands below to reproduce, the istio-system IngressGateway goes to CrashLoopBackoff and its logs say

```
2020-05-13T21:58:25.469327Z	warning	envoy wasm	[external/envoy/source/extensions/common/wasm/context.cc:1106] wasm log stats_outbound: [extensions/stats/plugin.cc:438]::onConfigure() cannot parse configuration as JSON: { "debug": "false", "stat_prefix": "istio", "disable_host_header_fallback": true "metrics": [ { "name": "requests_total", "dimensions": { "destination_port": "destination.port", "request_host": "request.host" } } ] }
2020-05-13T21:58:25.469567Z	critical	envoy main	[external/envoy/source/exe/terminate_handler.cc:13] std::terminate called! (possible uncaught exception, see trace)
```

To reproduce you need any bogus JSON.  Here is my script, which is missing a comma after `"disable_host_header_fallback": true`

```
cat > /tmp/section2.json <<EOF 
{
    "debug": "false",
    "stat_prefix": "istio",
    "disable_host_header_fallback": true
    "metrics": [
        {
            "name": "requests_total",
            "dimensions": {
                "destination_port": "destination.port",
                "request_host": "request.host"
            }
        }
    ]
}
EOF
SECTION=2
METRICS=$(cat /tmp/section$SECTION.json)
ESCAPED_METRICS=${METRICS//\"/\\\"}
PATCH='[{"op": "replace", "path": "/spec/configPatches/'${SECTION}'/patch/value/typed_config/value/config/configuration", "value": '\"${ESCAPED_METRICS}\"}]
CMD="kubectl -n istio-system patch envoyfilter stats-filter-1.6 --type=json --patch='"${PATCH}"'"
eval $CMD
```

**Comment by mandarjog** [comment]
@esnible this is the designed behaviour. The alternative is to not crash and the filter `does not work`, which makes debugging harder later.

The newer filters do not crash on bad input, and just stop working. We are planning to do this for all filters in 1.7.

**Comment by esnible** [comment]
@mandarjog I am happy to close this issue if the intended behavior is to crash the ingress to let the user know their EnvoyFilter is invalid.

Would it not make sense to have Istio's webhook also reject any EnvoyFilter where `.spec.configPatches[*].patch.value.typed_config.value.config.configuration` is not valid JSON?  If you agree, create an issue and assign it to me.

**Comment by howardjohn** [comment]
We cannot validate this, everything under patch.value is a generic blob

**Comment by mandarjog** [comment]
@esnible am closing this.
We can not validate it *yet*, so the only two options are crash or ignore. Since crash is in your face, users are likely to fix it right away in canary or similar.
