### ISSUE TITLE
Nignx-ingress-controller is not able to connect to api-server after Envoy is enabled

### ISSUE THREAD

**Issue by rishiraaz** [istio/istio#23848]
**Bug description** We are using istio service mesh (mtls), once envoy sidecar injection was enabled ingress controller went in crashloopback off

6 request.go:848] Got a Retry-After 1s response for attempt 9 to https://100.23.0.1:443/version?timeout=32s
I0514 05:21:52.474986 6 main.go:222] Unexpected error discovering Kubernetes version (attempt 0): an error on the server ("") has prevented the request from succeeding

**Expected behavior** it should be able to talk to api-server

**Steps to reproduce the bug** In a running cluster install ingress-controller, setup istio and enable mtls (create mesh policy and destination rule). Inject envoy side car. Check logs for ingress controller pod.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)** 
NGINX Ingress controller version: 1.34.3
Istio Version: 1.4.7
Kubernetes version (use kubectl version): 1.15.7

**How was Istio installed?** Helm

**Environment where bug was observed (cloud vendor, OS, etc)** AWS

**Comment by howardjohn** [comment]
Is it attempting to send mTLS to the k8s pod which doesn't speak mTLS? see https://istio.io/latest/docs/tasks/security/authentication/mtls-migration/ for info

You likely just need a destination rule disabling mTLS to k8s

Would be helpful to get config dump from client and access logs: https://github.com/istio/istio/wiki/Troubleshooting-Istio

**Comment by howardjohn** [comment]
We don't have enough info to debug this further. If you have more, please feel free to reopen. Thanks!
