### ISSUE TITLE
Update istio/cni sha in istio/istio when istio/cni is updated

### ISSUE THREAD

**Issue by jacob-delgado** [istio/istio#23840]
**Describe the feature request**

Similar to https://github.com/istio/istio/issues/23823

istio/cni repo merges for a release branch should have its SHA be updated in istio/istio istio.dep file. It is possible to not have the version of istio/cni ready for consumption in the next version of Istio. Automating this process would make it less error prone.

**Describe alternatives you've considered**

**Additional context**

**Comment by jwendell** [comment]
I think this now can be closed, since CNI is now merged into istio/istio?

**Comment by ericvn** [comment]
Agree that this can be closed as CNI is no longer in istio.dep
