### ISSUE TITLE
PeerAuthentication not working in Istio 1.5.2

### ISSUE THREAD

**Issue by scraly** [istio/istio#23845]
**Bug description**

**Expected behavior**

When we deploy PeerAuthentication object (for namespace-wide), it should activate mTLS in strict or permissive mide (depending on what we want).

**Steps to reproduce the bug**

1. Deploy PeerAuthentication object for a namespace:

`apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "default"
  namespace: "test"
spec:
  mtls:
    mode: PERMISSIVE`

or

`apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "default"
  namespace: "test"
spec:
  mtls:
    mode: STRICT`

2. Check with *istioctl authn* command

$ istioctl authn tls-check my-pod -n test

-->
all the SERVER column is "DISABLE" and AUTHN POLICY column is equals "None"

3. Check with a describe command for a pod display that mtls is DISABLE

Result:
Deploying PeerAuthentication object in istio 1.5.2 cluster do notihing. 
Deploying Policy object and DestinationRule, activate mTLS in strict or permissive mode.

**Version **

`$ istioctl version
client version: 1.5.2
ingressgateway version: 1.5.2
ingressgateway version: 1.5.2
ingressgateway version: 1.5.2
ingressgateway version: 1.5.2
ingressgateway version: 1.5.2
ingressgateway-internal version:
ingressgateway-internal version:
ingressgateway-internal version:
ingressgateway-internal version:
telemetry version: 1.5.2
telemetry version: 1.5.2
pilot version: 1.5.2
pilot version: 1.5.2
data plane version: 1.5.2 (48 proxies), 1.3.3 (2 proxies)`

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.6", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"clean", BuildDate:"2020-01-18T23:23:21Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**

Installed through operator

**Environment where bug was observed (cloud vendor, OS, etc)**

kubernetes cluster deployed in a on-prem cluster, in an AWS EC2

**Comment by hobbytp** [comment]
The same issue in istio 1.5.4, after do some testing, seems only the output of "istioctl authn tls-check" is wrong, the PeerAuthentication configuration work correctly.

And I also found that the output of "istioctl authn tls-check" will always aligned with MeshPolicy configuration. But it is only incorrect showing, not impact to the function which is aligned with PeerAuthentication configuration.

**Comment by hobbytp** [comment]
https://github.com/istio/istio/issues/22471

**Comment by howardjohn** [comment]
I think this bug is just about the istioctl tool not working, not the actual runtime behavior of traffic. If that is true, this is tracked in https://github.com/istio/istio/issues/23388. If not, please reopen, with info about the request that fails. Thanks!
