### ISSUE TITLE
Dumped demo-profile can't be deployed to minikube, but embedded into istioctl can

### ISSUE THREAD

**Issue by morozovcookie** [istio/istio#23857]
**Bug description**

I'm trying deploy istio with dumped profile (because I have a lot of change), but it does not works. Then I tried deploy istio with dumped demo-profile without any changes and got the same result. 

**Expected behavior**

Dumped profile should be deployed as an embedded profile. 

**Steps to reproduce the bug**

```bash
# create namespace and deploy istio
$ kubectl create namespace istio-system && istioctl manifest apply --set profile=demo

# Open dashboard and you can see that's all are green

# Remove namespace
$ kubectl delete namespaces istio-system

# Dump demo profile
$ istioctl profile dump demo > demo.profile.yaml

# Create namespace and deploy istio with demo.profile.yaml
$ kubectl create namespace istio-system && istioctl manifest apply -f demo.profile.yaml
```

As additional step you can generate manifest with embedded profile and with file demo.profile.yaml and compare it - no difference, except token keys.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```bash
# istioctl version
$ istioctl version --remote
client version: 1.5.4
control plane version: 1.5.4
data plane version: 1.5.4 (3 proxies)

# kubectl version
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

```bash
$ brew install istioctl
```

**Environment where bug was observed (cloud vendor, OS, etc)**

```bash
# minikube version
$ minikube version
minikube version: v1.10.1
commit: 63ab801ac27e5742ae442ce36dff7877dcccb278
```

I did attached two files: istio-dump-with-istioctl.tar.gz for deployment with embedded profile into istioctl and istio-dump-with-profile-dump.tar.gz for deployment with dummped demo profile.
[istio-dump-with-profile-dump.tar.gz](https://github.com/istio/istio/files/4629156/istio-dump-with-profile-dump.tar.gz)
[istio-dump-with-istioctl.tar.gz](https://github.com/istio/istio/files/4629158/istio-dump-with-istioctl.tar.gz)

**Comment by esnible** [comment]
@ostromart 
Using 1.6.0-beta.1 I did `diff <(istioctl manifest generate --set profile=demo) <(istioctl manifest generate -f <(istioctl profile dump demo))` and I see some differences.

Some of the differences look unimportant but this does not:
```
<         - name: GODEBUG
<           value: gctrace=1
18922,18924c18925
<           value: "100"
<         - name: CONFIG_NAMESPACE
<           value: istio-config
```

The GODEBUG and CONFIG_NAMESPACE are ENV vars on istiod.  Spooky that they are not present on one of these.

**Comment by esnible** [comment]
The reporter used 1.5.4.  I tried

diff <(istioctl-1.5.4 manifest generate --set profile=demo) <(istioctl-1.5.4 manifest generate -f <(istioctl-1.5.4 profile dump demo))

and the only difference I saw was the signing_key.

If this was reported against 1.6.0 I would believe the problem was these differences.  I am confused why I am not seeing differences with 1.5.4.

**Comment by morozovcookie** [comment]
@esnible 

I forget, that before reported an issue, I used version 1.5.2 and they did not work too. After I'm trying to use 1.5.4 and after few hours posted this issue :)

**Comment by howardjohn** [comment]
It's possible https://preliminary.istio.io/docs/ops/best-practices/security/#configure-third-party-service-account-tokens which is automatically detected at runtime if not configured?
