### ISSUE TITLE
Proxy all HTTP(s) calls to Auth0 through a virtual service in istio using redisquota adapter

### ISSUE THREAD

**Issue by kishor-tricon** [istio/istio#23856]
Hi,

We are using Auth0 universal login platform for managing user login, recently our auth0 API calls exhausted the maximum limit of 1000. To tackle this, we thought of proxying the auth0 endpoint through a virtual service within our cluster and using our own quota/rate limit on it. But redisquota is deprecated and I have no idea how to do this using telemetry v2.

I am new to istio so kinda hard to describe the things properly, let me if any more details needed

**Comment by howardjohn** [comment]
Support envoy native rate limiting is being tracked in https://github.com/istio/istio/issues/20952 and https://github.com/istio/istio/issues/22068. Please follow these issues. thanks!
