### ISSUE TITLE
Unwanted TCP telemetry [istio 1.6.0-rc.0 w/ CNI]

### ISSUE THREAD

**Issue by jshaughn** [istio/istio#23862]
Using Istio 1.6.0-rc.0 on OpenShift 4.4.3 (CNI) there is unwanted TCP traffic involving mgmtCluster.  This is not new in rc.0 but I don't know when it was introduced.   There is telemetry from unknown to destination_service_name "mgmtCluster" and to each destination_workload.  This is what I see with rc.0 using bookinfo with mongo. 

![image](https://user-images.githubusercontent.com/2104052/81967957-b84a0a00-95e9-11ea-82b3-b8087eea1b65.png)

For comparison, this is the same using 1.5.2, where the telemetry looks better:

![image](https://user-images.githubusercontent.com/2104052/81970309-4ffd2780-95ed-11ea-8426-538c78145d6e.png)

In both versions the traffic from ratings-v2 to mongo is not great, it's split as traffic from unknown to the mongo workload, and also as a request from ratings-v2 to the mongo service (but without  any workload).  It's likely a different issue, but letting you know just in case it's related.

**Expected behavior**

The unwanted traffic should be filtered (see the 1.5.2 screenshot).

**Steps to reproduce the bug**

Run bookinfo with 1.6.0-rc.0 and check the telemetry.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

See above.

**How was Istio installed?**

istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**

OpenShift 4.4.3 on AWS

This may be related to https://github.com/istio/istio/pull/23841

**Comment by jacob-delgado** [comment]
Is it possible for you to test with `1.6.0-beta.1`?

**Comment by jshaughn** [comment]
@jacob-delgado That is what I was running yesterday when I reported this issue in slack.  1.6.0-beta.1 did have this tcp problem, as well as the http problem with InboundPassthroughClusterIpv4.  The latter went away with rc.0.

**Comment by jacob-delgado** [comment]
I am able to replicate this with OpenShift 4.4.3. Going to test with vanilla k8s.

**Comment by nrjpoddar** [comment]
This might break other dashboards & alerting etc folks might have. Does anyone know what’s causing this?

**Comment by jshaughn** [comment]
1.6.0-rc.2 solves the `mgmtCluster` issue in my testing on OpenShift 4.4.3.

If necessary, I will open a separate issue to follow up on the way the mongo traffic is represented.

**Comment by jacob-delgado** [comment]
> 1.6.0-rc.2 solves the `mgmtCluster` issue in my testing on OpenShift 4.4.3.
> 
> If necessary, I will open a separate issue to follow up on the way the mongo traffic is represented.

Let's close this issue--I'll have you do it since you opened it--and open an new one to track. Thanks for verifying this.
