### ISSUE TITLE
Istioctl should be able to pick up context from a set of user-defined defaults (Think Kubens but for Istio)

### ISSUE THREAD

**Issue by tariq1890** [istio/istio#23868]
Edit: @esnible https://docs.google.com/document/d/1M_5Ji5A6MKRMFDUupwx3r1yQZDeIPvqHmFs-IAIxaak/edit# to was created for this request.

**Describe the feature request**

As a user of Istio in a different namespace, I would like `istioctl` to point to my custom istio namespace instead of having to use `-i` flag all the time

**Describe alternatives you've considered**

`istioctl analyze -i`

**Additional context**

**Comment by esnible** [comment]
Istio doesn't have a local config directory, such as ~/.istio/config.  Would it be sufficient to  do something like `export ISTIO_NAMESPACE=tariq1890-system` and have the value of $ISTIO_NAMESPACE override the default if present?

**Comment by tariq1890** [comment]
That would be a good start :)

**Comment by esnible** [comment]
I think this is a good idea.  I will see what others think at the June 7 UX working group meeting.  If there is interest I will implement something.

**Comment by esnible** [comment]
Created https://docs.google.com/document/d/1M_5Ji5A6MKRMFDUupwx3r1yQZDeIPvqHmFs-IAIxaak/edit# to discuss the UX of picking up defaults.

**Comment by tariq1890** [comment]
Thanks for fixing this @esnible
