### ISSUE TITLE
Telemetry V2 e2e with CNI

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#23867]
We have a problem arise late in 1.6 release cycle, where telemetry was broken with CNI.https://github.com/istio/istio/issues/23862

We are lacking end to end test with cni that would expose this telemetry behaviour.

@jshaughn @douglas-reid @nrjpoddar

**Comment by howardjohn** [comment]
We would not have caught this issue even if it was not cni with current tests I think, as we don't have negative test to ensure we don't produce extraneous metrics (I think?)

**Comment by mandarjog** [comment]
Whoever adds a test should ensure that negative tests are added.
