### ISSUE TITLE
Istiod fails to issue certificate to a remote cluster

### ISSUE THREAD

**Issue by irisdingbj** [istio/istio#23879]
In the scenario like https://github.com/istio/istio/issues/22918. I encounter an error on k8s 1.18 like below:

```
Authentication failed: Authenticator ClientCertAuthenticator at index 0 got error: no verified chain is found. Authenticator KubeJWTAuthenticator at index 1 got error: failed to validate the JWT: the service account authentication returns an error: [invalid bearer token, square/go-jose: error in cryptographic primitive]. Authenticator ClientCertAuthenticator at index 2 got error: no verified chain is found.
```
Looking through the codes, I do not find problem as the cluster ID and remote client all are there.  I also printed them out:

```
2020-05-15T08:10:46.403412Z     info    iris token eyJhbGciOiJSUzI1NiIsImtpZCI6IlBQUHVLQ0VMcDVyNHFtNDZfVVdtcFY1V1U0MHJnamtpNWhTVUpCTzM2OW8ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJpc3Rpby1zeXN0ZW0iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiaXN0aW8taW5ncmVzc2dhdGV3YXktc2VydmljZS1hY2NvdW50LXRva2VuLWs5eGdiIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImlzdGlvLWluZ3Jlc3NnYXRld2F5LXNlcnZpY2UtYWNjb3VudCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjcwNjA2YzE4LTNmYWMtNDAxZS1hMjllLWVlNjU0MDE5YTk2MiIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDppc3Rpby1zeXN0ZW06aXN0aW8taW5ncmVzc2dhdGV3YXktc2VydmljZS1hY2NvdW50In0.SvyMALm-fAkCrifFm7mKhJ1jZWukt3hIEO_GI0FBNkDtpP3Xs3XEAFdZepVINZTJW_7J8O4AFb2ADwcfG9Ce2WpysdgZigl71QsSOzy8uSCjNIaiczPiQE5QICAbBRMWSSRgkf4kj9YnPoZO8dEDh-Oo0CQLBfLc697T8SELxACkODQd6QZo4Jnhbp8mOry953IZ5Y-Lk2fkLjAefOgkDKHEEsL33DcMPYMQSRwiY5bo19aCMe5baRf6PUMBvM6X9wawB8SVA_WKqaglcq4KewlAdLdUjT7ZkP10MQgkOkBZi73dq9l23ykvode61eFU1gxJ9RtUpPHU6wvB1BKbkw
2020-05-15T08:10:46.403476Z     info    iris cluster id: remotecluster
2020-05-15T08:10:46.403486Z     info    iris incoming cluster id: remotecluster
2020-05-15T08:10:46.403493Z     info    iris current cluster id: maincluster
2020-05-15T08:10:46.403497Z     info    iris remote client is not nil
2020-05-15T08:10:46.406892Z     warn    serverca        Authentication failed: Authenticator ClientCertAuthenticator at index 0 got error: no verified chain is found. Authenticator KubeJWTAuthenticator at index 1 got error: failed to validate the JWT: the service account authentication returns an error: [invalid bearer token, square/go-jose: error in cryptographic primitive]. Authenticator ClientCertAuthenticator at index 2 got error: no verified chain is found.
```

I compared the token from log with the one in the ingress gatewway pod and they are exactly the same. 
 looks like :https://github.com/kubernetes/kubernetes/issues/72026 is related. But no other clue. 

@myidpt @hzxuzhonghu @linsun Appreciated if you can share some lights here.

**Comment by hzxuzhonghu** [comment]
One way to narrow down the issue scope is to verify your token by hand.
https://jpweber.io/blog/a-look-at-tokenrequest-api/

**Comment by linsun** [comment]
Thank you @hzxuzhonghu!  That is a good link.

I found out on my main cluster, I'm seeing 3 secrets with token (istio ingress GW SA's, Istiod SA's & reader SA) but not seeing token with the Istio-remote-secret.  This seems an issue and certainly was not created as part of create remote secret cmd.

Name:         istio-remote-secret-remote0
Namespace:    istio-system
Labels:       istio/multiCluster=true
Annotations:  istio.io/clusterContext: linistio10/7caab3af9f514f028081a8180c107b69

Type:  Opaque

Data
====
remote0:  4418 bytes

**Comment by myidpt** [comment]
Can you make sure this issue only exists on K8s 1.18?

**Comment by myidpt** [comment]
It seems like istiod isn't able to get authenticated to the remote apiserver. Is the remote cluster's JWT provisioned correctly to istiod?
@nmittler

**Comment by linsun** [comment]
@myidpt it also existed in my 1.16 k8s cluster.

I have the remote cluster's secrets set up in main istiod.

I think @hzxuzhonghu changed the code lately so it uses the remote cluster's k8s client to talk to remote cluster's API server with the service's bear token to do the token review.

**Comment by linsun** [comment]
We will have a quick debug session in 1 hour pls join if you are avail and interested.  (ping me on slack for url)

**Comment by linsun** [comment]
@myidpt and @nmittler and I had a quick meeting about this issue and discussed next step to debug this:

Manually validate the token extracted from the context is correct.  It should be the same token from the caller sidecar container's /var/run/secrets/tokens/istio-token.   We should be able to take the token to run through a manual test with the token review API server (Thanks to @myidpt for the instruction):

```
$ more file.json
{
"apiVersion": "authentication.k8s.io/v1",
"kind": "TokenReview",
"spec": {"token": "eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJpc3Rpby1zeXN0
ZW0iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiaXN0aW8tcGlsb3Qtc2VydmljZS1hY2NvdW50LXRva2VuLW1yNzlyIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNl
LWFjY291bnQubmFtZSI6ImlzdGlvLXBpbG90LXNlcnZpY2UtYWNjb3VudCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImNlZmY1ODRjLTBlZGYtMTFlOS1hNWUyLTQyMDEw
YTgwMDE1OSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDppc3Rpby1zeXN0ZW06aXN0aW8tcGlsb3Qtc2VydmljZS1hY2NvdW50In0.Umqh87eXj5L7-jnmKhRB8oTGu7S0b_ZIezJeVOIR4kF0P8JbNcJNafrnXaGt
frqsG1T5_CgXHq0MA6fCP2KL3qZWrh0sMCqZ6sMmjoqtR_T--RwUpgpbTC3KlitStWADNu3D4uhtKIKuFlczX2CJasPlv6q1RHNJduE0mt_frCuo7K-nXEESyDw9sBniZfiDYY69O-vbS2Fyaz5Wwhn-0R2bchbZcu1NLZ8w
Gg-sQRf-Q-219WMc2c_30xpSCy48FGFvxuU4L_05kbK1K7W_EbsaljHTRX2y0X_B8EYKSFPpgV6pff7SZJqxklJ7Ph4FU_DxMJdq0DPb9Be3pu98wg"
}
}
$ curl -i https://kubernetes.default.svc/apis/authentication.k8s.io/v1/tokenreviews --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -H "authorization: Bearer `more /var/run/secrets/kubernetes.io/serviceaccount/token`" -H "Content-Type: application/json" -d @file.json
```

Since we are accessing the istiod on main cluster via ingress gw, we need to ensure the token isn't modified by the ingress gw.  (Note: we are not currently configuring pass through on our gateway for 15012.)

@irisdingbj @hzxuzhonghu

**Comment by linsun** [comment]
Also @myidpt and @nmittler and I agreed this is a critical fix and we should get into 1.6.x ASAP when fix is avail.

**Comment by linsun** [comment]
@myidpt and I had more discussion, I think we have some idea what is wrong. @hzxuzhonghu, when you did the optimization for #23563, you changed the code to use remote k8s client to call remote k8s API with token review API... That would require a valid bear token (e.g. a service account JWT provisioned by some tooling from the remote cluster, with the privilege to call TokenReview API)... I think the code is missing that and uses the JWT token from my sleep service's sidecar (extracted from the context in https://github.com/istio/istio/blob/master/security/pkg/server/ca/authenticate/kube_jwt.go#L68) which won't have the permission to call TokenReview API.  @irisdingbj 's prior code didn't have this issue because it uses istiod's JWT token which we had granted the privilege to call token review API for both local and remote clusters.

As much as I love the optimization you attempted to make in #23563, for 1.6, I propose we revert #23563 till a proper fix is available.

@myidpt Please correct me if I'm wrong here.

cc @irisdingbj @nmittler

**Comment by myidpt** [comment]
>  I think the code is missing that and uses the JWT token from my sleep service's sidecar 
I think L68 is only extracting the cluster ID from the context. Actually istiod tries to use the right client to call the remote cluster:
https://github.com/istio/istio/blob/ab9afbebc3f12e517bbd48f1e2ec0e75af611f88/security/pkg/server/ca/authenticate/kube_jwt.go#L102

**Comment by linsun** [comment]
Ok thanks @myidpt!  Now the question is when the remote k8s client is calling the remote k8s API's with token review request, does it have the right bearer token that has the privilege to call TokenReview API:

```-H "authorization: Bearer `more /var/run/secrets/kubernetes.io/serviceaccount/token`"

**Comment by hzxuzhonghu** [comment]
@linsun I think it uses the certificate provided by multi-cluster secret.

`Authentication failed: Authenticator ClientCertAuthenticator at index 0 got error: no verified chain is found. Authenticator KubeJWTAuthenticator at index 1 got error: failed to validate the JWT: the service account authentication returns an error: [invalid bearer token, square/go-jose: error in cryptographic primitive]. Authenticator ClientCertAuthenticator at index 2 got error: no verified chain is found.
`  This is the authn error from apiserver, have nothing to do with clusterrole permission. If RBAC error occur, the response should be someth8ing similar to `xxx have no permission on xxx ops`

**Comment by irisdingbj** [comment]
@hzxuzhonghu I verified without your change in #23563 and it works. So I will revert your changes in #23563 and #23229.  I think your PR is good at optimization so we can investigate how to make them in afterwards.

**Comment by hzxuzhonghu** [comment]
I agree to revert if this is a bug. But i can not see from the above comments.

What i suggest is: compare the `clusterid` taken from istio-agent in the csr with the kubeClient got from `GetRemoteKubeClient`.  If they are consistent,  i can not imagine this should fail.

**Comment by irisdingbj** [comment]
The problem is the cluster id in my remote cluster is using the name of main cluster.  Based on this, changes in #23563  are good. @hzxuzhonghu I will not revert your changes and sorry for the confusion. 

@linsun We will need to modify the injection template for istiod-remote chart otherwise the injected deployment will use the main cluster name as the webhook is running on main cluster.

**Comment by linsun** [comment]
Nice job - thank you @irisdingbj !

I manually modified the istio-sidecar-injector cm on my remote cluster by updating with correct values in 2 places:

```
        - name: ISTIO_META_CLUSTER_ID
          value: "remote0"
        {{- if .Values.global.network }}
        - name: ISTIO_META_NETWORK
          value: "network2"
```

Then when I deploy the sleep pod, it still uses the ISTIO_META_CLUSTER_ID and ISTIO_META_NETWORK from main cluster.  It doesn't look the main cluster's istiod would read the istio sidecar injector ConfigMap on remote cluster right now.

**Comment by linsun** [comment]
Confirmed that if I modify the main cluster's istio-sidecar-injector cm, and restart istiod afterwards, then deploy sleep pod on the remote cluster with auto sidecar injector, the pod will come up nicely.  @hzxuzhonghu this confirms your change is okay but require us to configure the sidecar with proper cluster id in remote cluster.

**Comment by linsun** [comment]
```
  // The scheme must be "https"; the URL must begin with "https://".
  //
  // A path is optional, and if present may be any string permissible in
  // a URL. You may use the path to pass an arbitrary string to the
  // webhook, for example, a cluster identifier.
  //
  // Attempting to use a user or basic auth e.g. "user:password@" is not
  // allowed. Fragments ("#...") and query parameters ("?...") are not
  // allowed, either.
```

**Comment by linsun** [comment]
I'm working on a PR for this to allow users to pass in cluster name and network as part of the injectionURL.  should be out soon.

thanks all for your help in troubleshooting this!

**Comment by howardjohn** [comment]
I really don't think this URl approach is possible. What if I want to specify just one config and not the other? Or if I instead want to override discoveryAddress or some other arbitrary field?

Its disappointing there is not support for query parameters... we could possibly hack it like `istiod/inject/foo=bar/baz=something` and process as query parameters but that feels wrong
