### ISSUE TITLE
Istio 1.5 Ingress Gateway Proxy Crash when custom lua filter is applied 

### ISSUE THREAD

**Issue by lck0129** [istio/istio#23874]
**Bug description**

We’re having a problem with the IngressGateway Envoy Proxy crashing regularly on incoming requests when our custom lua filter is applied in a particular order (running Istio 1.5.0).

**Steps to reproduce the bug**

**keep pressing F5** to refresh the web browser after apply below lua scritps on ingress gateway:

	apiVersion: networking.istio.io/v1alpha3
	kind: EnvoyFilter
	metadata:
	  name: edge-lua-filter
	  namespace: istio-system
	spec:
	  workloadLabels:
	    app: istio-ingressgateway
	  configPatches:
	  - applyTo: LISTENER
	    ListenerMatch: 0.0.0.0_8080
	    patch:
	      operation: MERGE
	      value:
		per_connection_buffer_limit_bytes: 100000000
	  filters:
	  - listenerMatch:
	      listenerType: GATEWAY
	    filterName: envoy.lua
	    filterType: HTTP
	    filterConfig:
	      inlineCode: |
		function version()
		    return "v1"
		end

		function log(handle, value)
		    handle:logWarn(version() .. ": " .. value)
		end

		-- dump a lua object into a string for logging
		function dump(o)
		  if type(o) == 'table' then
		      local s = '{ '
		      for k,v in pairs(o) do
			if type(k) ~= 'number' then k = '"'..k..'"' end
			s = s .. '['..k..'] = ' .. dump(v) .. ','
		      end
		      return s .. '} '
		  else
		      return tostring(o)
		  end
		end

		function get_header(handle, header)
		    return handle:headers():get(header)
		end

		function string.starts(String, Start)
		    return string.sub(String, 1, string.len(Start)) == Start
		end

		function string.ends(String, End)
		    return End == "" or string.sub(String, -string.len(End)) == End
		end

		function envoy_on_request(request_handle)
		  path = get_header(request_handle, ":path")
		  local host = get_header(request_handle, ":authority")
		  -- this is to avoid login going through auth service
		  if path == '/login' or  host == 'dont.abc.com' then
		      do return end
		  end
		  -- for /api going through auth service
		  -- if string.starts(path, "/api/") and host == 'app-alpha.abc.com' then
		  if string.starts(path, "/api/") then
		      log(request_handle, "==========START DISPLAYING REQUEST HEADERS")
		      local log_headers = request_handle:headers()
		      for key, value in pairs(log_headers) do
			log(request_handle,  "header key: " .. dump(key) .. ", header value: " .. dump(value))
		      end
		      log(request_handle, "==========END DISPLAYING REQUEST HEADERS")

		      -- Build a request for our authenticaiton service before passing request upstream
		      local auth_host = "authentication.default.svc.cluster.local"
		      local auth_path = "/authentication/nginx/abc/auth"

		      local cluster = "outbound|80||" .. auth_host
		      local request_headers = {
			  [":method"] = "GET",
			  [":path"] = auth_path,
			  [":authority"] = host,
			  ["token"] = get_header(request_handle, "token"),
			  ["os"] = get_header(request_handle, "os"),
			  ["device"] = get_header(request_handle, "device"),
			  ["User-Agent"] = get_header(request_handle, "user-agent"),
			  ["X-Original-URI"] = path,
			  ["requestId"] = get_header(request_handle, "requestid"),
			  ["menu"] = get_header(request_handle, "menu"),
			  ["pointMenu"] = get_header(request_handle, "pointmenu"),
			  ["userId"] = get_header(request_handle, "userid"),
			  -- for app
			  ["appversion"] = get_header(request_handle, "appversion"),
			  ["workstation"] = get_header(request_handle, "workstation")
		      }

		      local request_body = ""
		      local timeout = 5000 --ms

		      log(request_handle, "Sending auth request, headers: " .. dump(request_headers) .. ", cluster: " .. cluster .. ", request_body: " .. request_body .. ", path: " .. path)

		      log(request_handle, "Sending request to auth service now")
		      response_headers, response_body = request_handle:httpCall(
			  tostring(cluster),
			  request_headers, 
			  request_body,
			  timeout
		      )

		      log(request_handle, "Received response from auth service now")
		      log(request_handle, "response_headers: " .. dump(response_headers))
		      log(request_handle, "response_body: " .. response_body)

		      -- If the response isn't 200, reject the request
		      if tonumber(response_headers[":status"]) ~= 200 then
			  log(request_handle, "-------------Authentication Failed-----------")
			  request_handle:respond(
				      {[":status"] = response_headers[":status"]},
				      response_body
				  )
			  do return end
		      else
		      -- end
		      -- if tonumber(response_headers[":status"]) == 200 then
			  log(request_handle, "----------Authentication Successed----------")
			  local json =  require 'cjson'
			  local jsondata = json.decode(response_body)
			  log(request_handle, jsondata.data.userId)
		      end
		  end
		end
		function envoy_on_response(response_handle)
		--   log(response_handle, "response updated from auth service")
		end

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

	[root@k8s ~]# istioctl version --remote
	client version: 1.5.0
	control plane version: 1.5.0
	data plane version: 1.5.0 (64 proxies)
	[root@k8s ~]# kubectl version
	Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
	Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

	CentOS Linux release 7.7.1908 (Core)

Here’s the backtrace from the crash:

	[Envoy (Epoch 0)] [2020-05-13 10:48:57.260][29][warning][lua] [external/envoy/source/extensions/filters/http/lua/lua_filter.cc:597] script log: v1: Sending request to auth service now
	[Envoy (Epoch 0)] [2020-05-13 10:48:57.505][29][critical][main] [external/envoy/source/exe/terminate_handler.cc:13] std::terminate called! (possible uncaught exception, see trace)
	[Envoy (Epoch 0)] [2020-05-13 10:48:57.505][29][critical][backtrace]  :70] Backtrace (use tools/stack_decode.py to get line numbers):
	[Envoy (Epoch 0)] [2020-05-13 10:48:57.505][29][critical][backtrace]  :71] Envoy version: 73f240a29bece92a8882a36893ccce07b4a54664/1.13.1-dev/Clean/RELEASE/BoringSSL
	[Envoy (Epoch 0)] [2020-05-13 10:48:57.529][29][critical][backtrace]  :75] #0: Envoy::TerminateHandler::logOnTerminate()::$_0::operator()() [0x56538f0f1dae]
	[Envoy (Epoch 0)] [2020-05-13 10:48:57.539][29][critical][backtrace]  :77] #1: [0x56538f0f1cb9]
	[Envoy (Epoch 0)] [2020-05-13 10:48:57.550][29][critical][backtrace]  :75] #2: std::__terminate() [0x56538f654a73]
	[Envoy (Epoch 0)] [2020-05-13 10:48:57.561][29][critical][backtrace]  :75] #3: std::__1::__function::__func<>::operator()() [0x56538d7ff728]
	[Envoy (Epoch 0)] [2020-05-13 10:48:57.572][29][critical][backtrace]  :75] #4: Envoy::Extensions::Common::Wasm::Context::onDone() [0x56538def3a67]
	[Envoy (Epoch 0)] [2020-05-13 10:48:57.582][29][critical][backtrace]  :75] #5: Envoy::Http::ConnectionManagerImpl::doDeferredStreamDestroy() [0x56538ee7569e]
	[Envoy (Epoch 0)] [2020-05-13 10:48:57.592][29][critical][backtrace]  :75] #6: Envoy::Http::ConnectionManagerImpl::ActiveStream::onResetStream() [0x56538ee7f339]
	[Envoy (Epoch 0)] [2020-05-13 10:48:57.601][29][critical][backtrace]  :75] #7: Envoy::Http::Http2::ConnectionImpl::onStreamClose() [0x56538ee95f2e]
	[Envoy (Epoch 0)] [2020-05-13 10:48:57.611][29][critical][backtrace]  :75] #8: Envoy::Http::Http2::ConnectionImpl::Http2Callbacks::Http2Callbacks()::$_12::__invoke() [0x56538ee993ac]
	[Envoy (Epoch 0)] [2020-05-13 10:48:57.621][29][critical][backtrace]  :75] #9: nghttp2_session_close_stream [0x56538eedf487]
	[Envoy (Epoch 0)] [2020-05-13 10:48:57.632][29][critical][backtrace]  :75] #10: nghttp2_session_on_rst_stream_received [0x56538eee2191]
	[Envoy (Epoch 0)] [2020-05-13 10:48:57.642][29][critical][backtrace]  :75] #11: nghttp2_session_mem_recv [0x56538eee541a]
	[Envoy (Epoch 0)] [2020-05-13 10:48:57.652][29][critical][backtrace]  :75] #12: Envoy::Http::Http2::ConnectionImpl::dispatch() [0x56538ee944f9]
	[Envoy (Epoch 0)] [2020-05-13 10:48:57.662][29][critical][backtrace]  :75] #13: Envoy::Http::Http2::ServerConnectionImpl::dispatch() [0x56538ee98150]
	[Envoy (Epoch 0)] [2020-05-13 10:48:57.672][29][critical][backtrace]  :75] #14: Envoy::Http::ConnectionManagerImpl::onData() [0x56538ee75eb1]
	[Envoy (Epoch 0)] [2020-05-13 10:48:57.686][29][critical][backtrace]  :75] #15: Envoy::Network::FilterManagerImpl::onContinueReading() [0x56538ec345db]
	[Envoy (Epoch 0)] [2020-05-13 10:48:57.696][29][critical][backtrace]  :75] #16: Envoy::Network::ConnectionImpl::onReadReady() [0x56538ec3104a]
	[Envoy (Epoch 0)] [2020-05-13 10:48:57.705][29][critical][backtrace]  :75] #17: Envoy::Network::ConnectionImpl::onFileEvent() [0x56538ec30b1d]
	[Envoy (Epoch 0)] [2020-05-13 10:48:57.716][29][critical][backtrace]  :75] #18: Envoy::Event::FileEventImpl::assignEvents()::$_0::__invoke() [0x56538ec2b5f0]
	[Envoy (Epoch 0)] [2020-05-13 10:48:57.727][29][critical][backtrace]  :75] #19: event_process_active_single_queue [0x56538ef5c9ab]
	[Envoy (Epoch 0)] [2020-05-13 10:48:57.739][29][critical][backtrace]  :75] #20: event_base_loop [0x56538ef5b23e]
	[Envoy (Epoch 0)] [2020-05-13 10:48:57.752][29][critical][backtrace]  :75] #21: Envoy::Server::WorkerImpl::threadRoutine() [0x56538ec21278]
	[Envoy (Epoch 0)] [2020-05-13 10:48:57.763][29][critical][backtrace]  :75] #22: Envoy::Thread::ThreadImplPosix::ThreadImplPosix()::$_0::__invoke() [0x56538f127953]
	[Envoy (Epoch 0)] [2020-05-13 10:48:57.763][29][critical][backtrace]  :75] #23: start_thread [0x7fc1fc69b6db]
	[Envoy (Epoch 0)] [2020-05-13 10:48:57.763][29][critical][backtrace]  :83] Caught Aborted, suspect faulting address 0x13
	[Envoy (Epoch 0)] [2020-05-13 10:48:57.763][29][critical][backtrace]  :70] Backtrace (use tools/stack_decode.py to get line numbers):
	[Envoy (Epoch 0)] [2020-05-13 10:48:57.763][29][critical][backtrace]  :71] Envoy version: 73f240a29bece92a8882a36893ccce07b4a54664/1.13.1-dev/Clean/RELEASE/BoringSSL
	[Envoy (Epoch 0)] [2020-05-13 10:48:57.763][29][critical][backtrace]  :75] #0: __restore_rt [0x7fc1fc6a6890]
	[Envoy (Epoch 0)] [2020-05-13 10:48:57.774][29][critical][backtrace]  :77] #1: [0x56538f0f1cb9]
	[Envoy (Epoch 0)] [2020-05-13 10:48:57.774][29][critical][backtrace]  :75] #2: std::__terminate() [0x56538f654a73]
	[Envoy (Epoch 0)] [2020-05-13 10:48:57.774][29][critical][backtrace]  :75] #3: std::__1::__function::__func<>::operator()() [0x56538d7ff728]
	[Envoy (Epoch 0)] [2020-05-13 10:48:57.774][29][critical][backtrace]  :75] #4: Envoy::Extensions::Common::Wasm::Context::onDone() [0x56538def3a67]
	[Envoy (Epoch 0)] [2020-05-13 10:48:57.774][29][critical][backtrace]  :75] #5: Envoy::Http::ConnectionManagerImpl::doDeferredStreamDestroy() [0x56538ee7569e]
	[Envoy (Epoch 0)] [2020-05-13 10:48:57.774][29][critical][backtrace]  :75] #6: Envoy::Http::ConnectionManagerImpl::ActiveStream::onResetStream() [0x56538ee7f339]
	[Envoy (Epoch 0)] [2020-05-13 10:48:57.774][29][critical][backtrace]  :75] #7: Envoy::Http::Http2::ConnectionImpl::onStreamClose() [0x56538ee95f2e]
	[Envoy (Epoch 0)] [2020-05-13 10:48:57.774][29][critical][backtrace]  :75] #8: Envoy::Http::Http2::ConnectionImpl::Http2Callbacks::Http2Callbacks()::$_12::__invoke() [0x56538ee993ac]
	[Envoy (Epoch 0)] [2020-05-13 10:48:57.774][29][critical][backtrace]  :75] #9: nghttp2_session_close_stream [0x56538eedf487]
	[Envoy (Epoch 0)] [2020-05-13 10:48:57.774][29][critical][backtrace]  :75] #10: nghttp2_session_on_rst_stream_received [0x56538eee2191]
	[Envoy (Epoch 0)] [2020-05-13 10:48:57.774][29][critical][backtrace]  :75] #11: nghttp2_session_mem_recv [0x56538eee541a]
	[Envoy (Epoch 0)] [2020-05-13 10:48:57.774][29][critical][backtrace]  :75] #12: Envoy::Http::Http2::ConnectionImpl::dispatch() [0x56538ee944f9]
	[Envoy (Epoch 0)] [2020-05-13 10:48:57.774][29][critical][backtrace]  :75] #13: Envoy::Http::Http2::ServerConnectionImpl::dispatch() [0x56538ee98150]
	[Envoy (Epoch 0)] [2020-05-13 10:48:57.774][29][critical][backtrace]  :75] #14: Envoy::Http::ConnectionManagerImpl::onData() [0x56538ee75eb1]
	[Envoy (Epoch 0)] [2020-05-13 10:48:57.774][29][critical][backtrace]  :75] #15: Envoy::Network::FilterManagerImpl::onContinueReading() [0x56538ec345db]
	[Envoy (Epoch 0)] [2020-05-13 10:48:57.774][29][critical][backtrace]  :75] #16: Envoy::Network::ConnectionImpl::onReadReady() [0x56538ec3104a]
	[Envoy (Epoch 0)] [2020-05-13 10:48:57.774][29][critical][backtrace]  :75] #17: Envoy::Network::ConnectionImpl::onFileEvent() [0x56538ec30b1d]
	[Envoy (Epoch 0)] [2020-05-13 10:48:57.774][29][critical][backtrace]  :75] #18: Envoy::Event::FileEventImpl::assignEvents()::$_0::__invoke() [0x56538ec2b5f0]
	[Envoy (Epoch 0)] [2020-05-13 10:48:57.774][29][critical][backtrace]  :75] #19: event_process_active_single_queue [0x56538ef5c9ab]
	[Envoy (Epoch 0)] [2020-05-13 10:48:57.774][29][critical][backtrace]  :75] #20: event_base_loop [0x56538ef5b23e]
	[Envoy (Epoch 0)] [2020-05-13 10:48:57.774][29][critical][backtrace]  :75] #21: Envoy::Server::WorkerImpl::threadRoutine() [0x56538ec21278]
	[Envoy (Epoch 0)] [2020-05-13 10:48:57.774][29][critical][backtrace]  :75] #22: Envoy::Thread::ThreadImplPosix::ThreadImplPosix()::$_0::__invoke() [0x56538f127953]
	[Envoy (Epoch 0)] [2020-05-13 10:48:57.774][29][critical][backtrace]  :75] #23: start_thread [0x7fc1fc69b6db]
	2020-05-13T10:48:57.829396Z     info    sds     node:router~10.244.2.64~istio-ingressgateway-6c447bd5db-j2phk.istio-system~istio-system.svc.cluster.local-2 resource:ROOTCA connection is terminated: rpc error: code = Canceled desc = context canceled
	2020-05-13T10:48:57.829451Z     error   sds     Remote side closed connection
	2020-05-13T10:48:57.829699Z     info    transport: loopyWriter.run returning. connection error: desc = "transport is closing"
	2020-05-13T10:48:57.829942Z     info    sds     node:router~10.244.2.64~istio-ingressgateway-6c447bd5db-j2phk.istio-system~istio-system.svc.cluster.local-1 resource:default connection is terminated: rpc error: code = Canceled desc = context canceled
	2020-05-13T10:48:57.829954Z     error   sds     Remote side closed connection
	2020-05-13T10:48:57.830887Z     error   Epoch 0 exited with error: signal: aborted (core dumped)
	2020-05-13T10:48:57.830917Z     info    No more active epochs, terminating
		
[Uploading istio-dump.tar.gz…]()

**Comment by snailbing** [comment]
This situation will occur when the http client quickly stops the http request;
<img width="1069" alt="WX20200515-181729@2x" src="https://user-images.githubusercontent.com/1305451/82040412-228da800-96d9-11ea-9723-7a52ba258cb4.png">

**Comment by snailbing** [comment]
This situation will occur when the http client quickly stops the http request;

<img width="1069" alt="WX20200515-181729@2x" src="https://user-images.githubusercontent.com/1305451/82041143-4a314000-96da-11ea-9e2c-8461bae474ae.png">

**Comment by lck0129** [comment]
更新到1.5.4就好了

**Comment by fandayrockworld** [comment]
Hi @lck0129 , there is a third party module `cjson` used in your yaml. But there was an error when I use: ` module 'cjson' not found`, would you like to show how it works?
