### ISSUE TITLE
Feature: Rewrite injector ConfigMaps to select control plane "master"

### ISSUE THREAD

**Issue by esnible** [istio/istio#23889]
THIS DESCRIPTION EDITED TO MATCH THE [1.8 Roadmap](https://docs.google.com/document/d/15J59Bz4ogsM5my1dtEycgPq8uOPB93uy8CU5-Ehv2qw/edit#).

Istio 1.6 offers control plane canarying but no recommendations or tools to help the user finish the job.
Istio 1.7 offers the `istioctl x uninstall` to remove a Canary version.

For 1.8 we want a command that
- Patches webhooks so that the `istio-injection=enabled` points to a different istio-sidecar-injector ConfigMap

1.8 stretch goal (requires discussion)
- Does a `kubectl rollout restart` or equivalent with the `istio-injection=enabled` namespaces after doing this.

Possibly we want to improve `istioctl install` so that it also does the restart, if the install is in-place.

**Comment by esnible** [comment]
I am thinking the flow to be something like:

```
istioctl install --revision canary
kubectl label default istio.io/rev=canary
// wait a few hours, look at metrics, etc
istioctl experimental promote-canary-to-master --revision=canary
kubectl label default istio-injection=enabled
// wait an hour or so
istioctl manifest uninstall --revision canary
```

**Comment by esnible** [comment]
This feature depends on https://github.com/istio/istio/issues/23479

**Comment by esnible** [comment]
@ostromart Is there a document for our most recent thoughts about this?

**Comment by sdake** [comment]
@esnible - I don't and am not aware of any. @howardjohn was a wg lead during the 1.8 series and @costinm has swapped from networking.

If the answer is no from the remaining wg leads in transition, and you have cycles to deliver the work, imo feel free.

**Comment by howardjohn** [comment]
I am strongly not in favor of restarting application pods.

I am also strongly not in favor of "patching", if you mean `kubectl patch`, as it violates every form of config management out there (helm, gitops, operator, etc).

I am in favor of allowing a revision to also match `istio-injection=enabled`. Note this will require changes to the pilot code base as well. I had some PR doing this a while back.

**Comment by howardjohn** [comment]
https://github.com/istio/istio/pull/23342 was the PR

**Comment by esnible** [comment]
@howardjohn What should be the next step on this?
Who has the skill to implement this?  I am happy to look at your previous PR and write code, we may need more agreement or and an implementor who is more skilled with the pilot code base than I.

**Comment by howardjohn** [comment]
@esnible I think we need to understand exactly what we want to do, in terms of the UX. And it must support gitops declarative style, not "patching". Then we can figure out the implementation details

**Comment by howardjohn** [comment]
https://docs.google.com/document/d/1k9V3D5jhZdFvEdJhw-T7mHCEIjkK0hFSdvtJIWEqIs0/ is a design for this

**Comment by Monkeyanator** [comment]
Note we also have [this design](https://docs.google.com/document/d/1k5phTcgJBis4cvPzJAZ5WtHlhWsTmkshMGZ5gca4DVs/edit?resourcekey=0-4Rb5MUYcHJ4rqKMgxc82MQ#) that talks about adding a "default" revision that would handle `istio-injection=enabled` namespaces.

Could also make this a subcommand or flag in `istioctl tag`, like `istioctl x tag set-default --revision foo`

**Comment by esnible** [comment]
WONT FIX
