### ISSUE TITLE
Better way to list useable Istio control planes

### ISSUE THREAD

**Issue by esnible** [istio/istio#23892]
**Unapproved** RFC for this: https://docs.google.com/document/d/1E4bda0RcmKQOpn7_h3dEcKBLCARK1MsbNZn3OUm-VSE/edit#

Currently the user can do `kubectl get istiooperator`, if they are running the Istio operator or their cloud provider gives them IOPs for managed install.

This lists the `revision` label now.

This item is to make it prettier and make sure it works with *External Istiod*.

External Istiod doesn't know about what other control plans might be working on the user's cluster.  There are three possible strategies:
- ~~Expect every cluster to have a (possibly meaningless) IOP on their managed clusters to serve as a "Bill of Materials" for what was installed.~~
  - ~~Possible the user could edit this for vendor-approved changes, but probably it is read-only~~
- This tool could read the Istio Injectors for a cluster, and list the possible injectors that namespaces can be configured for, along with which namespaces use which injectors.

The second approach seems reasonable.

Istio can be configured to handle ALL namespaces w/o injection.  The MutatingWebHook knows this according to @costinm

**Comment by esnible** [comment]
@ostromart I did a test implementation of this.  It looks really nice when the istioctl version is the same as the installed version.  For example, using master:

```
istioctl install --manifests manifests --set hub=gcr.io/istio-testing --set tag=latest --set values.global.imagePullPolicy=Always
istioctl manifest list --manifests manifests
REVISION PROFILE   CUSTOMIZATIONS                  PODS AGE
<master> <default> hub="gcr.io/istio-testing"      1    2d7h
                   installPackagePath="manifests/"      
                   tag="latest"  
                   values.global.imagePullPolicy="Always"                       
```

It looks **bad** when done across versions:

```
istioctl-1.7.3 install
istioctl manifest list --manifests manifests
REVISION PROFILE   CUSTOMIZATIONS                                                      PODS AGE
<master> <default> components.ingressGateways[0].k8s.service.ports[3].name="tls"       1    2d7h
                   components.ingressGateways[0].k8s.service.ports[3].port=15443            
                   components.ingressGateways[0].k8s.service.ports[3].targetPort=15443      
                   hub="docker.io/istio"                                                    
                   installPackagePath="manifests/"                                          
                   tag="1.7.3"                                                              
                   values.gateways.istio-ingressgateway.applicationPorts=""                 
                   values.gateways.istio-ingressgateway.debug="info"                        
                   values.gateways.istio-ingressgateway.domain=""                           
                   values.global.controlPlaneSecurityEnabled=true                           
                   values.global.enableHelmTest=false                                       
                   values.global.tracer.datadog.address="$(HOST_IP):8126"                   
                   values.global.tracer.lightstep.accessToken=""                            
                   values.global.tracer.lightstep.address=""                                
                   values.global.tracer.stackdriver.debug=false                             
                   values.global.tracer.stackdriver.maxNumberOfAnnotations=200              
                   values.global.tracer.stackdriver.maxNumberOfAttributes=200               
                   values.global.tracer.stackdriver.maxNumberOfMessageEvents=200            
                   values.global.tracer.zipkin.address=""                                   
                   values.pilot.configNamespace="istio-config"                              
                   values.sidecarInjectorWebhook.injectLabel="istio-injection"              
                   values.version=""                                           
```

Obviously the user didn't customize all those things. The output represents the different defaults between 1.7.3 and master.  I am not sure how to deal with that without baking in the profiles of the previous Istio versions.

**Comment by esnible** [comment]
@costinm has suggested https://github.com/istio/istio/pull/27849#issuecomment-706493189 a followup PR for the injector listing.

**Comment by esnible** [comment]
@therealmitchconnors should we backport https://github.com/istio/istio/pull/27849 to 1.8?

**Comment by esnible** [comment]
Re-opening because one of the two items is not merged.

**Comment by costinm** [comment]
How about helm ?

I think the best option is to list config maps - and look for istiod.*
We know that istioctl kube-inject requires a config map to find
discoveryAddress - so regardless of install method, if kube-inject is
supported we'll
have a config map.

The operator-specific configs are not reliable way to detect non-operator
installs.

**Comment by esnible** [comment]
> How about helm ? I think the best option is to list config maps - and look for istiod.*

@costinm We already have, merged in master, `istioctl x injector list` which lists all Istio versions using the injector.
We want some way to show the user the IOP options they installed using _istioctl_ or the operator.  Helm users have `helm list` to see what they installed.

**Comment by esnible** [comment]
@su225 I like your comment https://github.com/istio/istio/pull/27737#issuecomment-736596666 and the one in the unapproved RFC.

The current approach for listing IOPs is based on tree comparison.  You are correct, this can be quite verbose.

You propose listing the components.  This simplifies the output, but sometimes the user has customized just a few settings and this hides it.  For example, when I install Istio, I do 

```
  --set values.global.imagePullPolicy=Always \
  --set meshConfig.accessLogFile="/dev/stdout" \
  --set values.global.istiod.enableAnalysis=true \
  --set values.global.proxy.holdApplicationUntilProxyStarts=true
```

I'd like to find a home for showing the user all of their changes.  What do you think about putting logic in `istioctl profile diff` to let the user compare an installed control plane with the settings built into _istioctl_?

**Comment by su225** [comment]
@esnible - The main idea is to give a summary of revisions (number of revisions would be very small - most commonly 2?). That is where listing components enabled/statuses and some important and commonly customized fields (like hub and tag fields to begin with) are shown along with number of pods pointing to a revision.

The user can then drill down on a given revision and here verbose output is ok. To start with we could either list customizations there (the `CUSTOMIZATIONS` column) or show diffs in YAML like you proposed. We could also refine per revision drill-down output by incorporating https://github.com/istio/istio/pull/27737#issuecomment-721422456 from @ostromart

**Comment by esnible** [comment]
Assigning this item to @su225 because https://github.com/istio/istio/pull/29713 seems like a great way to list control planes.

Note that https://docs.google.com/document/d/13IGuJg8swtLdNGW5cpF7ZdVkgge8voNp9DWBD93Wb1Q/edit , _Flexible Revision Labels_, is now related to this.  This function must list not only the control planes, but the indirect revision labels that can be used to configure injection for a plane.

**Comment by su225** [comment]
Can we close this as the PR is merged?
