### ISSUE TITLE
Apply only changed resources when istioctl apply is called

### ISSUE THREAD

**Issue by ostromart** [istio/istio#23893]
Right now, the entire manifest is re-applied to the cluster. Usually this is fairly quick but it could be speeded up even further by checking the saved in-cluster IOP that reflects the installed state, and pre-populating the helmreconciler cache with values generated from it before calling Reconcile(). The code will only update the values that change, as it does in the operator controller use case.

**Comment by howardjohn** [comment]
I thought we already do this? not up front but before each object we do a get the  decide update or create call? Do we just need to skip if there is no change (if we are not already doing so)?
