### ISSUE TITLE
Test Coverage: add test for TLS origination for egress traffic

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#23899]
Add  integration / e2e test for https://github.com/istio/istio/issues/23821

https://github.com/istio/istio/pull/23898 does not add tests for expediency.

**Comment by howardjohn** [comment]
I am working on this

**Comment by JimmyCYJ** [comment]
cc @nschhina

**Comment by howardjohn** [comment]
This is done by https://github.com/istio/istio.io/pull/7367

**Comment by JimmyCYJ** [comment]
Thanks @howardjohn Is there any plan to add integration test for egress TLS origination?
I intend to let @nschhina to add integration test for https://preliminary.istio.io/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/

**Comment by howardjohn** [comment]
I added it for Egress sidecar not egress gateway, so we can add gateway as well

**Comment by nschhina** [comment]
I'll see if I can get to it- Egress File Mount integration tests are missing but the plan is to enable sds for egress gateway and writing integration tests for egress gateway sds will take priority over file mount integration tests

**Comment by nschhina** [comment]
#24647 PR for Egress Gateway Origination Tests(Integration)

**Comment by nschhina** [comment]
Closing this issue as egress traffic TLS origination integration tests were already added
