### ISSUE TITLE
Istio envoy sidecar does not update IP incase the destination LB IP changes

### ISSUE THREAD

**Issue by parthshah86** [istio/istio#23905]
**Bug description**
We use the istio sidecar within our pods with main container to manage traffic to external services. Let's say the container makes a call to server X via an AWS LB. The request goes through the sidecar to the LB and eventually to the server. One pattern which we see is that in-case the LB switches Network interfaces and gets a new IP, the sidecar still keeps pointing to the OLD IP address and returns 503 for the request. The Deployed container does not recover unless the pod is restarted.

**Expected behavior**
DNS should be refreshed and istio sidecar should point to the new IP address.

**Version (include the output of istioctl version --remote and kubectl version and helm version if you used Helm)**
istioctl version --remote
client version: 1.4.5
control plane version: 1.5.2
data plane version: 1.5.2 (101 proxies), 1.4.3 (9 proxies)

kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}

helm version
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}

Environment where bug was observed (cloud vendor, OS, etc)
EKS

**Comment by howardjohn** [comment]
Is this service configured by a DNS service entry? I'd so it will follow the TTL from the DNS response

**Comment by parthshah86** [comment]
We review our services set up and turned out it was DNS caching in the urllib3 python library which was creating the problem. We figured out a way to reset the request to refresh the DNS, which seems to have resolved the problem. 

Thanks @howardjohn for the response and sorry for the delay.
