### ISSUE TITLE
Clean up TCP stats for passthrough cluster

### ISSUE THREAD

**Issue by bianpengyuan** [istio/istio#23901]
**Bug description**

In the TCP there are lots of connection open/closed stats which only has passthrough filled in as destination service and all other metadata label being `unknown`, e.g.
```
istio_tcp_received_bytes_total{connection_security_policy="unknown",destination_app="unknown",destination_canonical_revision="latest",destination_canonical_service="unknown",destination_principal="unknown",destination_service="unknown",destination_service_name="PassthroughCluster",destination_service_namespace="unknown",destination_version="unknown",destination_workload="unknown",destination_workload_namespace="unknown",instance="10.56.0.15:15090",job="envoy-stats",namespace="service-graph03",pod_name="svc03-0-2-7dc8cb9d9b-6hfhg",reporter="source",request_protocol="tcp",response_flags="-",source_app="svc03-0-2",source_canonical_revision="v1",source_canonical_service="svc03-0-2",source_principal="unknown",source_version="v1",source_workload="svc03-0-2",source_workload_namespace="service-graph03"}
```

And the corresponding tcp sent/received bytes stats for them are all zero.

We need to figure out why those closed/open stats gets collected. Is it a real application connection or something else. Based on outcome, either enrich the label of the stats or stop recording them.

**Comment by mandarjog** [comment]
A bug fix in 1.6.x would be better.

**Comment by gargnupur** [comment]
We don't get any destination labels because in case of PassthroughCluster there is noone to exchange metadata exchange with..
what did we see in mixer v1 for this?

**Comment by bianpengyuan** [comment]
What I am really wondering is this a real connection or some other random behavior, because the bytes sent/read are all 0, which does not make sense to me. I don't recall that we see the similiar thing with mixer v1

**Comment by bianpengyuan** [comment]
The same fix in https://github.com/istio/istio/issues/24379 applies here, after increasing proto sniffing to a long time, mysterious time series with passthrough edges disappeared, since connection just closed before sniffing timeout without data transferred. So track this issue there.
