### ISSUE TITLE
Custom CA: mutual TLS failure (CERTIFICATE_VERIFY_FAILED & SSLV3_ALERT_CERTIFICATE_UNKNOWN) 

### ISSUE THREAD

**Issue by drzdbd1** [istio/istio#23916]
In order to support multi-cluster scenario, we plugged in an existing custom CA. In most of the cases mTLS worked fine but some clusters are having mTLS failures between pods.

**Symptom**:
Pilot cannot talk to Galley and we found below errors from log.

_From caller (Pilot):   [Envoy (Epoch 0)] [2020-05-05   15:00:58.846][25][debug][connection]   [external/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc:226]   [C35242] TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED_

_From callee (Galley):   [Envoy (Epoch 0)] [2020-05-05   17:54:08.356][33][debug][connection]   [external/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc:226]   [C146750] TLS error: 268436502:SSL routines:OPENSSL_internal:SSLV3_ALERT_CERTIFICATE_UNKNOWN_

**Environment and deployment approach**

- Azure Kubernetes
- IstioCtl with 1.4.7

**Troubleshooting:**
Dump cert-chain.pem, root-cert.pem and key.pem from /etc/certs folder from Pilot and Galley pod and show cert chain, and they look fine.

openssl crl2pkcs7 -nocrl -certfile <pem> | openssl pkcs7 -print_certs -text -noout

- **root-cert.pem** contains our **self signed** root CA

_Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            c4:5b:53:8a:ed:bf:49:4c
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN=commerce-mesh, O=Microsoft
        Validity
            Not Before: Oct  5 01:14:59 2019 GMT
            Not After : Nov 16 01:14:54 2029 GMT
        Subject: CN=commerce-mesh, O=Microsoft
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
            RSA Public Key: (4096 bit)
...
            X509v3 extensions:
            X509v3 Basic Constraints: critical
                CA:TRUE
            X509v3 Subject Key Identifier:
                A5:E2:96:F7:78:FE:E6:46:1E:F0:CA:C3:AF:8D:01:98:8F:B6:05:58
            X509v3 Key Usage: critical
                Digital Signature, Non Repudiation, Key Encipherment, Certificate Sign_

- **cert-chain.pem** contains 3 certs: Pilot (or Galley), cluster CA cert and root CA cert

_Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            ed:0d:f6:ed:45:8a:70:af:9b:b5:61:7f:ed:fc:ad:49
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: L=mdpcs-int-aks-wus2-000
        Validity
            Not Before: May 17 03:43:17 2020 GMT
            Not After : Aug 15 03:43:17 2020 GMT
        Subject:
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
            RSA Public Key: (2048 bit)
...
X509v3 Subject Alternative Name: critical
                URI:spiffe://cluster.local/ns/istio-system/sa/istio-pilot-service-account_

_Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: -1465514380 (-0x5759f98c)
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN=commerce-mesh, O=Microsoft
        Validity
            Not Before: Dec 16 17:40:37 2019 GMT
            Not After : Jan 29 17:40:32 2021 GMT
        Subject: L=mdpcs-int-aks-wus2-000
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
            RSA Public Key: (4096 bit)_

_Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            c4:5b:53:8a:ed:bf:49:4c
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN=commerce-mesh, O=Microsoft
        Validity
            Not Before: Oct  5 01:14:59 2019 GMT
            Not After : Nov 16 01:14:54 2029 GMT
        Subject: CN=commerce-mesh, O=Microsoft
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
            RSA Public Key: (4096 bit)_
- **key.pem** contains the RSA key, which looks good

**Also tried logging into contain and run:**

**openssl s_client -connect istio-galley.istio-system.svc.cluster.local:15019 -CAfile root-cert.pem -cert cert-chain.pem -key key.pem -msg**

Got similar error:

Acceptable client certificate CA names
CN = commerce-mesh, O = Microsoft
Requested Signature Algorithms: ECDSA+SHA256:RSA-PSS+SHA256:RSA+SHA256:ECDSA+SHA384:RSA-PSS+SHA384:RSA+SHA384:RSA-PSS+SHA512:RSA+SHA512:RSA+SHA1
Shared Requested Signature Algorithms: ECDSA+SHA256:RSA-PSS+SHA256:RSA+SHA256:ECDSA+SHA384:RSA-PSS+SHA384:RSA+SHA384:RSA-PSS+SHA512:RSA+SHA512
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits

SSL handshake has read 4477 bytes and written 1873 bytes
Verification error: permitted subtree violation

New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 2048 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 47 (permitted subtree violation)

<<< ??? [length 0005]
    17 03 03 00 13
<<< TLS 1.3 [length 0001]
    15
<<< **TLS 1.3, Alert [length 0002], fatal unknown_ca**
    02 30
139830488281536:error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca:../ssl/record/rec_layer_s3.c:1528:SSL alert number 48

**Surprisingly TLS1.2 worked:**

**openssl s_client -connect istio-galley.istio-system.svc.cluster.local:15019 -CAfile root-cert.pem -cert cert-chain.pem -key key.pem -msg -tls1_2**

New, TLSv1.2, Cipher is ECDHE-RSA-CHACHA20-POLY1305
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-CHACHA20-POLY1305
    Session-ID:
    Session-ID-ctx:
    Master-Key: 953ED888EEDFB96DAD9546EE3D810CC099D9C331E94CFC6198F4664FC7FFE085081F58F69E13FDAB6AA3CE81C35E5417
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1589731196
    Timeout   : 7200 (sec)
    Verify return code: 47 (permitted subtree violation)
    Extended master secret: yes

**And dumped Envoy config from Galley:**
![image](https://user-images.githubusercontent.com/21187075/82153626-743f4b00-981d-11ea-8d04-6b7b18557419.png)

**Questions**

- Where else can I look? I'm pretty much stuck here.
- From Envoy [doc](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/security/ssl), this error would happen in below case, what does it mean and how I could fix it?

SSLV3_ALERT_CERTIFICATE_UNKNOWN: Peer certificate is not in config specified SPKI.

- This issue sometimes can be fixed by deleting Pilot/Galley secrets under "isto-system" namespace and their pods, but is not guaranteed. And I wasn't able to figure out the correct sequence so far.

- "trusted_ca" field in config dump is set to "root-cert.pem" which only contains the root CA (commerce-mesh) but not the intermediate CA from the cluster (mdpcs-int-aks-wus2-000), would it be an issue?

Thanks!

**Comment by drzdbd1** [comment]
Quick update: the issue seems to be certs minted from Citadel violate the "URL name constraint" set in intermediate CA cert.

![image](https://user-images.githubusercontent.com/21187075/82161502-22fd7e80-9852-11ea-9b16-a266dda3d3c5.png)
![image](https://user-images.githubusercontent.com/21187075/82161503-27299c00-9852-11ea-8b89-785b67951698.png)

I wonder whether this is related to #17111?

**Comment by costinm** [comment]
The good news: envoy is checking the name constraints !!

We should probably start using them more - and also respect them when
generating certs.
Do you have any control over what constraints are defined in the
intermediate CA ?

**Comment by drzdbd1** [comment]
Yes we do, we developed a service that creates the intermediate CA cert and sets the name constraints.

We figured out the root cause, for some reason we missed the change from #17111 in our custom 1.4.7 citadel image so the generated certs from citadel violated the name contasints.

Envoy does check name constraints, which caused mTLS to fail.
