### ISSUE TITLE
Disable istio citadel to stop rotation of certs and envoy hot restarts

### ISSUE THREAD

**Issue by piyush0609** [istio/istio#23922]
**Bug description**
I am using istio 1.4.3 helm charts for istio installation. It has an option to disable security and install istio components. But when i do that all other components are going into crashback loop because certs are not being created for them because citadel is not present

**Expected behavior**
We are using istio to control our cluster egress traffic and not using mutual TLS feature of istio so ideally we dont want these certs to rotated in the first place.
According to this issue https://github.com/istio/istio/issues/16222 we don't want our egress traffic to be affected because of cert rotation

**Steps to reproduce the bug**
Install istio with `security.enabled` as false
**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
client version: 1.4.3
control plane version: 1.4.5
data plane version: 1.4.5 (87 proxies)
```
**How was Istio installed?**
Using helm according to the documentation provided by istio

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
@myidpt do we support plaintext only mode in 1.4?

@piyush0609 in 1.5+ there is no more hot reload during cert rotation if you are able to update

**Comment by piyush0609** [comment]
@howardjohn is there any possible way we could disable citadel for our usecase?

**Comment by howardjohn** [comment]
In 1.4 you can use the minimal profile to disable everything that requires certs. In 1.5+ there is no more citadel or hot restarts. Since we only support 1.5+ now, I think this canbe closed https://istio.io/latest/news/support/announcing-1.4-eol-final/
