### ISSUE TITLE
sidecar injection cm change requires istiod restart

### ISSUE THREAD

**Issue by linsun** [istio/istio#23933]
**Bug description**

While testing remote cluster and mutating webhook configuration, I found out sidecar injection cm change does require istiod to restart to pick up the change.  It would be great if this isn't required.

The change I did for testing: https://github.com/istio/istio/issues/23879#issuecomment-630268528

**Expected behavior**
restart istiod should not be required
**Steps to reproduce the bug**
modify something in the sidecar injector cm (for example ISTIO_META_CLUSTER_ID) and check if it is picked up by deploying a new pod with auto sidecar injector.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.6 rc.0

**Comment by howardjohn** [comment]
I don't think it does unless it recently regressed. It should be automatically updated.

However, kubernetes configmaps are incredibly slow to update for some reason - takes 30-60s

**Comment by howardjohn** [comment]
I think this is a regression. `curl 0:8080/debug/inject` shows the update but injection calls use the old one

**Comment by howardjohn** [comment]
Actually nevermind, its just slow :slightly_smiling_face: at least for me, it seems to update

**Comment by hzxuzhonghu** [comment]
https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#mounted-configmaps-are-updated-automatically  

```
When a ConfigMap already being consumed in a volume is updated, projected keys are eventually updated as well. Kubelet is checking whether the mounted ConfigMap is fresh on every periodic sync. However, it is using its local ttl-based cache for getting the current value of the ConfigMap. As a result, the total delay from the moment when the ConfigMap is updated to the moment when new keys are projected to the pod can be as long as kubelet sync period (1 minute by default) + ttl of ConfigMaps cache (1 minute by default) in kubelet. You can trigger an immediate refresh by updating one of the pod’s annotations.
```

**Comment by linsun** [comment]
@howardjohn @hzxuzhonghu thank you very much for your comments!  This makes sense, and I have validated it does take 2 mins to pick up the change without restart.
