### ISSUE TITLE
Fix Mixer lint issues

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio#2393]
As reported by the circleci lint job, there are the following lint issues in the //mixer portion of the codebase:

```
mixer/pkg/perf/client.go:1::error: file is not goimported (goimports)
mixer/pkg/perf/request.go:1::error: file is not goimported (goimports)
mixer/pkg/perf/request_test.go:1::error: file is not goimported (goimports)
mixer/pkg/perf/run.go:1::error: file is not goimported (goimports)
mixer/pkg/perf/setup_test.go:1::error: file is not goimported (goimports)
mixer/pkg/perf/standard.go:1::error: file is not goimported (goimports)
```

We need to run the `fmt` script over the `perf` package.

**Comment by ozevren** [comment]
Not sure what is going on, but when I run fmt.sh (in a branch synced to
upstream/master as of 30 seconds ago), I don't see any changes being done
to mixer/pkg/perf/... Instead, I get this:




modified:   ../../../broker/pkg/controller/controller.go
modified:   ../../../broker/pkg/model/config/store.go
modified:   ../../../broker/pkg/platform/kube/crd/client.go
modified:   ../../../broker/pkg/server/broker.go
modified:   ../../../broker/pkg/testing/util/kubernetes.go
modified:   ../../../broker/pkg/version/version.go
modified:   ../../../pilot/adapter/config/crd/client.go
modified:   ../../../pilot/adapter/config/crd/controller.go
modified:   ../../../pilot/adapter/config/crd/conversion.go
modified:   ../../../pilot/adapter/config/file/monitor.go
modified:   ../../../pilot/adapter/config/ingress/controller.go
modified:   ../../../pilot/adapter/config/ingress/conversion.go
modified:   ../../../pilot/adapter/config/ingress/status.go
modified:   ../../../pilot/adapter/config/ingress/status_test.go
modified:   ../../../pilot/cmd/istioctl/inject.go
modified:   ../../../pilot/cmd/istioctl/register.go
modified:   ../../../pilot/cmd/pilot-agent/main.go
modified:   ../../../pilot/cmd/pilot-discovery/main.go
modified:   ../../../pilot/cmd/pilot-discovery/server/monitoring.go
modified:   ../../../pilot/cmd/pilot-discovery/server/server.go
modified:   ../../../pilot/cmd/sidecar-initializer/main.go
modified:   ../../../pilot/platform/consul/controller.go
modified:   ../../../pilot/platform/consul/conversion.go
modified:   ../../../pilot/platform/consul/monitor.go
modified:   ../../../pilot/platform/eureka/controller.go
modified:   ../../../pilot/platform/eureka/conversion.go
modified:   ../../../pilot/platform/kube/client.go
modified:   ../../../pilot/platform/kube/controller.go
modified:   ../../../pilot/platform/kube/controller_test.go
modified:   ../../../pilot/platform/kube/queue.go
modified:   ../../../pilot/platform/kube/register.go
modified:   ../../../pilot/proxy/agent.go
modified:   ../../../pilot/proxy/context.go
modified:   ../../../pilot/proxy/envoy/config.go
modified:   ../../../pilot/proxy/envoy/ingress.go
modified:   ../../../pilot/proxy/envoy/mixer.go
modified:   ../../../pilot/proxy/envoy/resources.go
modified:   ../../../pilot/proxy/envoy/watcher.go
modified:   ../../../pilot/proxy/resolve.go
modified:   ../../../pilot/test/integration/access.go
modified:   ../../../pilot/test/integration/egress_rules.go
modified:   ../../../pilot/test/integration/ingress.go
modified:   ../../../pilot/test/integration/routing.go
modified:   ../../../pilot/test/integration/routingToEgress.go
modified:   ../../../pilot/test/util/kubernetes.go
modified:   ../../../pilot/test/util/shell.go
modified:   ../../../security/cmd/generate_cert/main.go
modified:   ../../../security/cmd/generate_csr/main.go
modified:   ../../../security/cmd/istio_ca/main.go
modified:   ../../../security/cmd/node_agent/main.go
modified:   ../../../security/cmd/node_agent/na/nafactory.go
modified:   ../../../security/cmd/node_agent/na/nodeagent.go
modified:   ../../../security/cmd/node_agent/na/nodeagent_test.go
modified:   ../../../security/integration/main.go
modified:   ../../../security/integration/utils/kubernetes.go
modified:   ../../../security/pkg/pki/ca/ca.go
modified:   ../../../security/pkg/pki/ca/controller/secret.go
modified:   ../../../security/pkg/pki/ca/generate_cert.go
modified:   ../../../security/pkg/registry/registry.go
modified:   ../../../security/pkg/server/grpc/server.go
modified:   ../../../tests/e2e/framework/appManager.go
modified:   ../../../tests/e2e/framework/istioctl.go
modified:   ../../../tests/e2e/framework/kubernetes.go
modified:   ../../../tests/e2e/tests/bookinfo/demo_test.go
modified:   ../../../tests/e2e/tests/mixer/mixer_test.go
modified:   ../../../tests/e2e/tests/simple/simple1_test.go
modified:   ../../../tests/util/commonUtils.go
modified:   ../../../tests/util/kubeUtils.go
modified:   ../../../tests/util/retry.go
modified:   ../../../tests/util/wrk.go

**Comment by douglas-reid** [comment]
yikes. that I can't explain.

looking at the files in `//mixer/pkg/perf`, the imports section looks correct.

@jmuk any ideas here?

**Comment by mandarjog** [comment]
potentially docker image uses a different version of `go/gofmt` than what is locally installed.

**Comment by douglas-reid** [comment]
I think this has been resolved now. Closing.
