### ISSUE TITLE
Improved AWS documentation

### ISSUE THREAD

**Issue by jmdamato** [istio/istio#23939]
**Describe the feature request**
When going through the getting started guide on AWS, the istio-ingressgateway EXTERNAL-IP remains pending. The docs pretty much say your SOL in that case and to use the Node Port.

I am looking for information on how to get this working or how to manually assign the aws load balancer so that I can get ingress traffic.

**Describe alternatives you've considered**
I have manually created an application load balancer and a network balancer on port 80, but when I go to http://<load_balancer>/productpage nothing loads.

**Additional context**

**Comment by howardjohn** [comment]
Are you using EKS or self run k8s on ec2? I thought EKS supports LB out of box (https://docs.aws.amazon.com/eks/latest/userguide/load-balancing.html)?

**Comment by jmdamato** [comment]
Sorry I should have clarified, yes I saw that guide, but I have to use strait up k8s on ec2.

**Comment by howardjohn** [comment]
I don't think its inside the scope of Istio documentation to tell users how to configure Kubernetes. Our docs do explain how to use Istio if your environment supports LB, and what to do if it doesn't. Figuring out how to get LB is in the scope of AWS/k8s documentation.
