### ISSUE TITLE
Using istiod as an RA

### ISSUE THREAD

**Issue by myidpt** [istio/istio#23948]
**Describe the feature request**
Today, istiod can be used as a CA or RA for K8s CA. We need to extend this to make istiod can be used as an RA for other CAs.

**Describe alternatives you've considered**

* Having istio-agent directly integrate with custom CAs. This has the limitation that the custom CA needs to support the fine-grained authn and authz of the request.
* Having Envoy directly integrate with custom CAs. This is a long term effort. It is feasible if WASM can be leveraged, otherwise Envoy has much less flexibility to add new adapters.

**Additional context**

**Comment by howardjohn** [comment]
Other alternatives is to integrate with 1/2 APIs, the k8s CSR api or cert-manager CSR api (soon cert manager will implement k8s CSR anyways though). Then we can leverage one API and use any CA that has a controller for that. cert-manager has venafi and vault support at the very least, possibly more
