### ISSUE TITLE
Move Analysis Framework to Istiod

### ISSUE THREAD

**Issue by jasonwzm** [istio/istio#23943]
`istioctl analyze` can remain use the existing framework. Merge with distribution status controller is also good to have.

**Comment by howardjohn** [comment]
Any updates on this? Just wasted an hour digging through 100s of callbacks and async processes

**Comment by jasonwzm** [comment]
Still WIP. You mean debugging the processing pipeline?

**Comment by howardjohn** [comment]
Yes, I am interested in this issue so we can delete all of this code and never have to debug it again :slightly_smiling_face:

**Comment by jasonwzm** [comment]
I am hoping to do it soon. I will likely refocus on this later this week. Why do you have to do debug galley code? It is just running analysis.

**Comment by howardjohn** [comment]
https://github.com/istio/istio/issues/25893 is the issue

**Comment by jasonwzm** [comment]
ok. do you have an idea on how to fix it or you are waiting for the code to be removed.

**Comment by howardjohn** [comment]
not stale

**Comment by howardjohn** [comment]
is this planned for 1.9?

**Comment by jasonwzm** [comment]
No, likely 1.10, design in 1.9.

**Comment by jasonwzm** [comment]
not stale

**Comment by howardjohn** [comment]
Not stale

**Comment by howardjohn** [comment]
this is done!
