### ISSUE TITLE
Timeouts being caused due to the DestinationRule configuration to propagate to the envoy sidecars

### ISSUE THREAD

**Issue by tasdikrahman** [istio/istio#23956]
**Describe the feature request**

Not very clear here [https://istio.io/docs/ops/best-practices/traffic-management/#avoid-503-errors-while-reconfiguring-service-routes](https://istio.io/docs/ops/best-practices/traffic-management/#avoid-503-errors-while-reconfiguring-service-routes) on how long should one wait after updating the destination rule with the new subset, before going forward with updating the virtualservice. 

The same applies for how long should one wait ideally, after updating the VirtualService to modify the DestinationRule to remove the older subset. 

What is the ideal wait time here? Any API to check with the istio client-go whether all the proxy sidecars have gotten the updated config (not sure if this possible as you mention that this propagation of config to proxy sidecar by pilot is an eventual consistent problem, CMIIW)? So that the VirtualService updation can be only done after the propagation is done. 

**Describe alternatives you've considered**

**Additional context**

- we are using istio's client-go to create/modify the DestinationRule and VirtualService, the order in which we are modifying the resources are DestinationRule and then VirtualService. 

Let me know if you need me to add any other details. 
- The error which we get on the client gets a 503 response code when there is an ongoing deployment with the steps and the order in which we do DestinationRule and VirtualService updation

**Comment by therealmitchconnors** [comment]
Hi Tasdik,

The good news is this is just the kind of feature the User Experience working group has been focused on for a few releases now.  In 1.4, we added `istioctl experimental wait`, which blocks until the specified resource has been distributed.  This is probably where I'd recommend starting, as it's enabled by default and available today.  Two caveats are that 1.6 has some known issues (#23998) related to wait, which may also exist in 1.5 (we haven't tested there yet), and that this is an experimental interface which may undergo breaking changes in the future.

The 1.6 release includes [Distribution Status](https://preliminary.istio.io/docs/reference/config/config-status/), which will update the CRD Status field when a resource has been propagated to all envoys.  This will allow you to use more traditional tools, like `kubectl wait` or a watch in your favorite kubernetes client to monitor resource readiness.  The downside to this feature is that is disabled by default, and Alpha-level in 1.6, so you'll need to explicitly enable it at install or upgrade time to take advantage of it.

Also, this is an area that the UX Working group has been very interested in hearing user feedback around.  Would you be willing to sit down and discuss the specifics of your use case?  This will help us justify further investment in this area moving forward.

**Comment by tasdikrahman** [comment]
Thanks for replying back @therealmitchconnors 

A bit more about our setup, 
- istio: 1.4.0
- multi-cluster setup, with single control plane and multiple remote clusters

How we are doing crud operations on the istio resources
- using istio client-go

```
	istio.io/api v0.0.0-20200117194847-776c2d7b730b
	istio.io/client-go v0.0.0-20200107185429-9053b0f86b03
```

### Operation which we are doing when we get the timeouts

The orchestration steps which we are doing at the moment(in order)
- create/update destinationRule 
- create/update Virtualservice
- cleanup DestinationRule for redundant subsets

### Specific reason why we raised the issue
While doing weighted traffic flow to our service making use of the above resources, we were noticing a few 5xx errors while the above orchestration was happening, on digging further which made us look at [https://istio.io/docs/ops/best-practices/traffic-management/#avoid-503-errors-while-reconfiguring-service-routes](https://istio.io/docs/ops/best-practices/traffic-management/#avoid-503-errors-while-reconfiguring-service-routes)

### The current hack which we are doing as of now to get this working without timeouts

As of now, we are having something like this in the orchestration steps. 
- create/update destinationRule 
- sleep for a predefined time
- create/update Virtualservice
- sleep for a predefined time
- cleanup DestinationRule for redundant subsets
 
the time is defined at 2seconds at this moment, although we feel this is really hacky(but is working in our test setup so far), we also noticed there is something called `pilot_proxy_convergence_time` mentioned here [https://istio.io/docs/reference/commands/pilot-discovery/#metrics](https://istio.io/docs/reference/commands/pilot-discovery/#metrics), on checking this metric, I am not very sure what should be the right way to check what is the max time in seconds which a resource is taking to get propagated to the cluster, I tried plotting this `histogram_quantile(0.999, sum(rate(pilot_proxy_convergence_time_bucket[1m])) by (le))` but I am not sure what does the value mean here. Sorry for my limited prometheus knowledge, but I couldn't figure out what should I check to come at a value to be set for the sleep operation, which is why I went with 2 seconds for the moment

### Proposal 

If I may suggest, since we already have operations like Create, Update, etc on the istio-client go, it would be helpful if you folks start exposing the status of the resource as you have mentioned here https://preliminary.istio.io/docs/reference/config/config-status/

>  The status field of the Reconciled type condition is initialized to False to indicate the resource is still in the process of being distributed to all the proxies. When finished reconciling, the status will become True. The status field might transition to True instantaneously, depending on the speed of the cluster.

So for an end-user perspective, someone can keep polling that particular value to be `True`, using client-go with the resource specified for example as `IstioClient.NetworkingV1alpha3().DestinationRules(dr.Namespace).Get(dr.Name, metav1.GetOptions{})`. 

This would remove the need to sleep, and place the logic to polling the status of the object, after when the status is `True`, someone can proceed to the next set of orchestration. 

I am not sure what the status of stability for a multi-cluster setup for istio with remote cluster and single control plane is at the moment for the newest versions, but would be great if we can somehow propagate the change which you mentioned of exposing the status of the resource object to 1.4.x releases. 

On another note, the metric `pilot_proxy_convergence_time`, maybe we can improve on the doc on what one should do to get at an average value, if their are using kubectl to apply such resources if they are not using client-go for istio, as it's not very clear if someone does not have prior prometheus knowledge on which of the metrics to pick out of, agreed this might be trivial for someone with prior knowledge, but just putting it out there in case you folks feel we can add something which would be immediately usable in the doc here [https://istio.io/docs/ops/best-practices/traffic-management/#avoid-503-errors-while-reconfiguring-service-routes](https://istio.io/docs/ops/best-practices/traffic-management/#avoid-503-errors-while-reconfiguring-service-routes)

```
pilot_proxy_convergence_time_bucket
pilot_proxy_convergence_time_count
pilot_proxy_convergence_time_sum
```

Please let me know if you need more information or if you need anything to discuss, we would be more than happy to participate. I am @tasdikrahman on istio's slack. Feel free to ping me there and we can discuss further.

**Comment by tasdikrahman** [comment]
Also noticed that the poll function that you were mentioning here https://github.com/istio/istio/blob/120d9ff04920f1c9a1db943052dd210dd5644dea/istioctl/pkg/kubernetes/client.go#L166, you are using it here in istioctl x wait  https://github.com/istio/istio/blob/master/istioctl/cmd/wait.go#L178-L184, what exactly happens when someone does a wait like `istioctl x wait VirtualService fooservice`, will this be waiting till the values are synced, after which it would give bask and exit status 0 and exit out? CMIIW, do you feel we can use this poll instead of sleep for our use case in 1.4.x?

**Comment by therealmitchconnors** [comment]
There's a lot of great information and questions here, so I'll address them each in a different response for clarity.  First, let's discuss the availability of distribution focused features in Istio's supported releases.

| Release          | Wait | DistributionStatus |
| ------------- | ------------- |-|
| 1.4.x  | Alpha, enabled by default  | N/A |
| 1.5.x  | Broken  | N/A |
| 1.6.x. | Fixed in 1.6.1, hopefully | Alpha, Disabled by default, not in go-client |
| 1.7.x (planned)  | Beta | Beta, enabled by default, added to go-client |

We do not usually backport features to previous releases, but I can take a look at fixing `wait` in the next 1.5 patch release, if it's something you're interested in using.  I would also be happy to work with you to write a go function which performs the equivalent of `istioctl wait` for you to use in 1.4 (and 1.5's next patch).  Once you are on 1.6 or later, you can use a kubernetes `watch` to wait for distribution to complete, much like you would to wait on a deployment or pod to become ready.

**Comment by therealmitchconnors** [comment]
Regarding the convergence metric, this is represented in a Prometheus instance as a [Histogram](https://prometheus.io/docs/concepts/metric_types/).  To develop a reasonable timeout, I would recommend using grafana or some other system to track the query you provided over a day, or perhaps a week, and take the max value as your timeout.  This should keep the incidence of 503's to a bare minimum until you are able to leverage one of the distribution features above.

**Comment by therealmitchconnors** [comment]
`istioctl wait` calls an internal facing debug API on Pilot, passing the resource name, type, and namespace as a parameter, and pilot returns the resourceVersion that each of its proxies has received for that object.  Because pilot can scale horizontally, each pilot instance must be queried in order to get a comprehensive view of the mesh.  For multi-cluster, if only one cluster has a control plane, and other clusters' proxies connect to that central control plane, that is the control plane which `wait` should be run against.  If you have multiple control planes sharing a single config plane (also know as replicated control planes), you will need to run `wait` against each control plane's pilot instances to get a comprehensive view of all proxies in the mesh.

**Comment by therealmitchconnors** [comment]
Once you have upgraded to 1.6, you will be able to read distribution information directly from the status field of the resource in question.  This works well in scenarios where you have a 1:1 mapping between control planes and kube api servers.  For instance, if you have three clusters, but only cluster 1 has a control plane, cluster1's api server will contain status information for your entire mesh.  If on the other hand each cluster has its own control plane, and all control planes are watching cluster1's api server, you have multiple control planes pointing to one api server, and there is no way to reconcile status between the three control planes.  You will need to pick one control plane to write status data, and either ignore the distribution in the other control planes, or use another mechanism like 'wait' to interact with them.

**Comment by therealmitchconnors** [comment]
I'm closing this for now, feel free to ping me with any additional questions.

**Comment by id-id-id** [comment]
Is there any other method of the question in https://istio.io/latest/docs/ops/best-practices/traffic-management/#avoid-503-errors-while-reconfiguring-service-routes.

We use istio-1.16.4, and find that [Distribution Status](https://preliminary.istio.io/docs/reference/config/config-status/) is just alpha
