### ISSUE TITLE
[1.6] TCP traffic reported in disparate prometheus time-series

### ISSUE THREAD

**Issue by jshaughn** [istio/istio#23963]
I think there is an issue with TCP telemetry but perhaps it's intended this way with Telemetry V2.  In short, a request is being reported in two parts.  Using bookinfo with the mongo option, we can see in the Kiali graph below that TCP requests from ratings-v2 to mongodb are reported in two parts:  from ratings -> mongo host, and then unknown -> mongo service/workload.

![image](https://user-images.githubusercontent.com/2104052/82359259-aabfc600-99d5-11ea-8beb-a3d0dbf0e570.png)

In the past  this was shown as expected, with a single path from ratings-v2 -> mongodb and had nothing to do with unknown.

This is derived from istio_tcp_bytes_sent_total and we can see the time-series here:

{
destination_service="mongodb.bookinfo.svc.cluster.local",
destination_service_name="mongodb",destination_workload="mongodb-v1",
destination_workload_namespace="bookinfo",
instance="10.128.2.18:15090",
source_workload="unknown"
}
{
destination_service="mongodb.bookinfo.svc.cluster.local",
destination_service_name="mongodb.bookinfo.svc.cluster.local",
destination_workload="unknown",
destination_workload_namespace="unknown",
instance="10.130.2.8:15090",
source_workload="ratings-v2"}

**Expected behavior**
TCP requests should be reported in a single time-series, lending to a more intuitive rendering.

**Steps to reproduce the bug**
Run bookinfo w/ mongo option

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istio 1.6.0-rc.2

**How was Istio installed?**
istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**
OpenShift 4.4.3 (CNI enabled)

**Comment by bianpengyuan** [comment]
I cannot reproduce this on a non-cni cluster. So probably related to CNI. Can I get a config dump from your ratings-v2 and mongodb pod?

**Comment by bianpengyuan** [comment]
This is not expected. The metrics indicate TCP metadata exchange does not happen.

**Comment by jshaughn** [comment]
ratings-v2 Pod:
===========
ind: Pod
apiVersion: v1
metadata:
  generateName: ratings-v2-65fdc4b4f6-
  annotations:
    k8s.v1.cni.cncf.io/networks: istio-cni
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "openshift-sdn",
          "interface": "eth0",
          "ips": [
              "10.130.2.8"
          ],
          "dns": {},
          "default-route": [
              "10.130.2.1"
          ]
      },{
          "name": "istio-cni",
          "dns": {}
      }]
    openshift.io/scc: anyuid
    sidecar.istio.io/status: >-
      {"version":"d36ff46d2def0caba37f639f09514b17c4e80078f749a46aae84439790d2b560","initContainers":["istio-validation"],"containers":["istio-proxy"],"volumes":["istio-envoy","istio-data","istio-podinfo","istio-token","istiod-ca-cert"],"imagePullSecrets":null}
  selfLink: /api/v1/namespaces/bookinfo/pods/ratings-v2-65fdc4b4f6-gb945
  resourceVersion: '48875'
  name: ratings-v2-65fdc4b4f6-gb945
  uid: e169c4f5-4322-4ff4-8fcd-7117c04b31df
  creationTimestamp: '2020-05-19T14:55:01Z'
  namespace: bookinfo
  ownerReferences:
    - apiVersion: apps/v1
      kind: ReplicaSet
      name: ratings-v2-65fdc4b4f6
      uid: 036dda62-4da6-4edc-9d37-8e9f4cae0aac
      controller: true
      blockOwnerDeletion: true
  labels:
    app: ratings
    istio.io/rev: default
    pod-template-hash: 65fdc4b4f6
    security.istio.io/tlsMode: istio
    service.istio.io/canonical-name: ratings
    service.istio.io/canonical-revision: v2
    version: v2
spec:
  restartPolicy: Always
  initContainers:
    - resources:
        limits:
          cpu: 100m
          memory: 50Mi
        requests:
          cpu: 10m
          memory: 10Mi
      terminationMessagePath: /dev/termination-log
      name: istio-validation
      env:
        - name: DNS_AGENT
      securityContext:
        capabilities:
          drop:
            - ALL
            - MKNOD
        privileged: false
        runAsUser: 1337
        runAsGroup: 1337
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
      imagePullPolicy: Always
      volumeMounts:
        - name: bookinfo-ratings-v2-token-7rfz7
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePolicy: File
      image: 'docker.io/istio/proxyv2:1.6.0-rc.2'
      args:
        - istio-iptables
        - '-p'
        - '15001'
        - '-z'
        - '15006'
        - '-u'
        - '1337'
        - '-m'
        - REDIRECT
        - '-i'
        - '*'
        - '-x'
        - ''
        - '-b'
        - '*'
        - '-d'
        - '15090,15021,15020'
        - '--run-validation'
        - '--skip-rule-apply'
  serviceAccountName: bookinfo-ratings-v2
  imagePullSecrets:
    - name: bookinfo-ratings-v2-dockercfg-2kz9p
  priority: 0
  schedulerName: default-scheduler
  enableServiceLinks: true
  terminationGracePeriodSeconds: 30
  nodeName: ip-10-0-136-233.us-west-1.compute.internal
  securityContext:
    seLinuxOptions:
      level: 's0:c25,c15'
    fsGroup: 1337
  containers:
    - resources: {}
      terminationMessagePath: /dev/termination-log
      name: ratings
      env:
        - name: MONGO_DB_URL
          value: 'mongodb://mongodb:27017/test'
      securityContext:
        capabilities:
          drop:
            - MKNOD
      ports:
        - containerPort: 9080
          protocol: TCP
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: bookinfo-ratings-v2-token-7rfz7
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePolicy: File
      image: 'docker.io/istio/examples-bookinfo-ratings-v2:1.15.0'
    - resources:
        limits:
          cpu: '2'
          memory: 1Gi
        requests:
          cpu: 10m
          memory: 40Mi
      readinessProbe:
        httpGet:
          path: /healthz/ready
          port: 15021
          scheme: HTTP
        initialDelaySeconds: 1
        timeoutSeconds: 1
        periodSeconds: 2
        successThreshold: 1
        failureThreshold: 30
      terminationMessagePath: /dev/termination-log
      name: istio-proxy
      env:
        - name: JWT_POLICY
          value: third-party-jwt
        - name: PILOT_CERT_PROVIDER
          value: istiod
        - name: CA_ADDR
          value: 'istiod.istio-system.svc:15012'
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: INSTANCE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.serviceAccountName
        - name: HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: CANONICAL_SERVICE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: 'metadata.labels[''service.istio.io/canonical-name'']'
        - name: CANONICAL_REVISION
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: 'metadata.labels[''service.istio.io/canonical-revision'']'
        - name: PROXY_CONFIG
          value: |
            {"proxyMetadata":{"DNS_AGENT":""}}
        - name: ISTIO_META_POD_PORTS
          value: |-
            [
                {"containerPort":9080,"protocol":"TCP"}
            ]
        - name: ISTIO_META_APP_CONTAINERS
          value: |-
            [
                ratings
            ]
        - name: ISTIO_META_CLUSTER_ID
          value: Kubernetes
        - name: ISTIO_META_INTERCEPTION_MODE
          value: REDIRECT
        - name: ISTIO_METAJSON_ANNOTATIONS
          value: |
            {"openshift.io/scc":"anyuid"}
        - name: ISTIO_META_WORKLOAD_NAME
          value: ratings-v2
        - name: ISTIO_META_OWNER
          value: 'kubernetes://apis/apps/v1/namespaces/bookinfo/deployments/ratings-v2'
        - name: ISTIO_META_MESH_ID
          value: cluster.local
        - name: DNS_AGENT
        - name: ISTIO_KUBE_APP_PROBERS
          value: '{}'
      securityContext:
        capabilities:
          drop:
            - ALL
            - MKNOD
        privileged: false
        runAsUser: 1337
        runAsGroup: 1337
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
      ports:
        - name: http-envoy-prom
          containerPort: 15090
          protocol: TCP
      imagePullPolicy: Always
      volumeMounts:
        - name: istiod-ca-cert
          mountPath: /var/run/secrets/istio
        - name: istio-data
          mountPath: /var/lib/istio/data
        - name: istio-envoy
          mountPath: /etc/istio/proxy
        - name: istio-token
          mountPath: /var/run/secrets/tokens
        - name: istio-podinfo
          mountPath: /etc/istio/pod
        - name: bookinfo-ratings-v2-token-7rfz7
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePolicy: File
      image: 'docker.io/istio/proxyv2:1.6.0-rc.2'
      args:
        - proxy
        - sidecar
        - '--domain'
        - $(POD_NAMESPACE).svc.cluster.local
        - '--serviceCluster'
        - ratings.$(POD_NAMESPACE)
        - '--proxyLogLevel=warning'
        - '--proxyComponentLogLevel=misc:error'
        - '--trust-domain=cluster.local'
        - '--concurrency'
        - '2'
  serviceAccount: bookinfo-ratings-v2
  volumes:
    - name: bookinfo-ratings-v2-token-7rfz7
      secret:
        secretName: bookinfo-ratings-v2-token-7rfz7
        defaultMode: 420
    - name: istio-envoy
      emptyDir:
        medium: Memory
    - name: istio-data
      emptyDir: {}
    - name: istio-podinfo
      downwardAPI:
        items:
          - path: labels
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels
          - path: annotations
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.annotations
        defaultMode: 420
    - name: istio-token
      projected:
        sources:
          - serviceAccountToken:
              audience: istio-ca
              expirationSeconds: 43200
              path: istio-token
        defaultMode: 420
    - name: istiod-ca-cert
      configMap:
        name: istio-ca-root-cert
        defaultMode: 420
  dnsPolicy: ClusterFirst
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/memory-pressure
      operator: Exists
      effect: NoSchedule
status:
  containerStatuses:
    - restartCount: 0
      started: true
      ready: true
      name: istio-proxy
      state:
        running:
          startedAt: '2020-05-19T14:56:08Z'
      imageID: >-
        docker.io/istio/proxyv2@sha256:d61b8b1071d801403687d92d5e07e81d7d9573a240244bae95385c7fecf0f3e3
      image: 'docker.io/istio/proxyv2:1.6.0-rc.2'
      lastState: {}
      containerID: 'cri-o://7a281293d407138466d6dfc03cb2c84545af364780a1ae42ab677923fda37a44'
    - restartCount: 0
      started: true
      ready: true
      name: ratings
      state:
        running:
          startedAt: '2020-05-19T14:56:07Z'
      imageID: >-
        docker.io/istio/examples-bookinfo-ratings-v2@sha256:7a547eaedf7c0f7e5f35ed7c8cf2823f60f9fffe7837e5571ad4f0387d830a83
      image: 'docker.io/istio/examples-bookinfo-ratings-v2:1.15.0'
      lastState: {}
      containerID: 'cri-o://1abb7acc56c87d155c2e6a3af5dac00f7c99d96d652cd159df96426624e25f4d'
  qosClass: Burstable
  podIPs:
    - ip: 10.130.2.8
  podIP: 10.130.2.8
  hostIP: 10.0.136.233
  startTime: '2020-05-19T14:55:01Z'
  initContainerStatuses:
    - name: istio-validation
      state:
        terminated:
          exitCode: 0
          reason: Completed
          startedAt: '2020-05-19T14:55:28Z'
          finishedAt: '2020-05-19T14:55:28Z'
          containerID: >-
            cri-o://e57dce9dc381c3aaf2731178b7f0ebe92000e77cad7f4d5298ca05403b571258
      lastState: {}
      ready: true
      restartCount: 0
      image: 'docker.io/istio/proxyv2:1.6.0-rc.2'
      imageID: >-
        docker.io/istio/proxyv2@sha256:d61b8b1071d801403687d92d5e07e81d7d9573a240244bae95385c7fecf0f3e3
      containerID: 'cri-o://e57dce9dc381c3aaf2731178b7f0ebe92000e77cad7f4d5298ca05403b571258'
  conditions:
    - type: Initialized
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2020-05-19T14:55:28Z'
    - type: Ready
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2020-05-19T14:56:12Z'
    - type: ContainersReady
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2020-05-19T14:56:12Z'
    - type: PodScheduled
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2020-05-19T14:55:01Z'
  phase: Running

mongodb-v1 Pod:
=============
kind: Pod
apiVersion: v1
metadata:
  generateName: mongodb-v1-799b9d7f66-
  annotations:
    k8s.v1.cni.cncf.io/networks: istio-cni
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "openshift-sdn",
          "interface": "eth0",
          "ips": [
              "10.128.2.18"
          ],
          "dns": {},
          "default-route": [
              "10.128.2.1"
          ]
      },{
          "name": "istio-cni",
          "dns": {}
      }]
    openshift.io/scc: anyuid
    sidecar.istio.io/status: >-
      {"version":"d36ff46d2def0caba37f639f09514b17c4e80078f749a46aae84439790d2b560","initContainers":["istio-validation"],"containers":["istio-proxy"],"volumes":["istio-envoy","istio-data","istio-podinfo","istio-token","istiod-ca-cert"],"imagePullSecrets":null}
  selfLink: /api/v1/namespaces/bookinfo/pods/mongodb-v1-799b9d7f66-8pqrv
  resourceVersion: '48756'
  name: mongodb-v1-799b9d7f66-8pqrv
  uid: 9f2c76c3-d69d-4edd-bcda-16098d772dc5
  creationTimestamp: '2020-05-19T14:54:59Z'
  namespace: bookinfo
  ownerReferences:
    - apiVersion: apps/v1
      kind: ReplicaSet
      name: mongodb-v1-799b9d7f66
      uid: b1f3a065-a1b0-4485-b852-0abbec07054d
      controller: true
      blockOwnerDeletion: true
  labels:
    app: mongodb
    istio.io/rev: default
    pod-template-hash: 799b9d7f66
    security.istio.io/tlsMode: istio
    service.istio.io/canonical-name: mongodb
    service.istio.io/canonical-revision: v1
    version: v1
spec:
  restartPolicy: Always
  initContainers:
    - resources:
        limits:
          cpu: 100m
          memory: 50Mi
        requests:
          cpu: 10m
          memory: 10Mi
      terminationMessagePath: /dev/termination-log
      name: istio-validation
      env:
        - name: DNS_AGENT
      securityContext:
        capabilities:
          drop:
            - ALL
            - MKNOD
        privileged: false
        runAsUser: 1337
        runAsGroup: 1337
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
      imagePullPolicy: Always
      volumeMounts:
        - name: default-token-z4jss
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePolicy: File
      image: 'docker.io/istio/proxyv2:1.6.0-rc.2'
      args:
        - istio-iptables
        - '-p'
        - '15001'
        - '-z'
        - '15006'
        - '-u'
        - '1337'
        - '-m'
        - REDIRECT
        - '-i'
        - '*'
        - '-x'
        - ''
        - '-b'
        - '*'
        - '-d'
        - '15090,15021,15020'
        - '--run-validation'
        - '--skip-rule-apply'
  serviceAccountName: default
  imagePullSecrets:
    - name: default-dockercfg-2v95k
  priority: 0
  schedulerName: default-scheduler
  enableServiceLinks: true
  terminationGracePeriodSeconds: 30
  nodeName: ip-10-0-146-20.us-west-1.compute.internal
  securityContext:
    seLinuxOptions:
      level: 's0:c25,c15'
    fsGroup: 1337
  containers:
    - resources: {}
      terminationMessagePath: /dev/termination-log
      name: mongodb
      securityContext:
        capabilities:
          drop:
            - MKNOD
      ports:
        - containerPort: 27017
          protocol: TCP
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: data-db
          mountPath: /data/db
        - name: default-token-z4jss
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePolicy: File
      image: 'istio/examples-bookinfo-mongodb:1.15.0'
    - resources:
        limits:
          cpu: '2'
          memory: 1Gi
        requests:
          cpu: 10m
          memory: 40Mi
      readinessProbe:
        httpGet:
          path: /healthz/ready
          port: 15021
          scheme: HTTP
        initialDelaySeconds: 1
        timeoutSeconds: 1
        periodSeconds: 2
        successThreshold: 1
        failureThreshold: 30
      terminationMessagePath: /dev/termination-log
      name: istio-proxy
      env:
        - name: JWT_POLICY
          value: third-party-jwt
        - name: PILOT_CERT_PROVIDER
          value: istiod
        - name: CA_ADDR
          value: 'istiod.istio-system.svc:15012'
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: INSTANCE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.serviceAccountName
        - name: HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: CANONICAL_SERVICE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: 'metadata.labels[''service.istio.io/canonical-name'']'
        - name: CANONICAL_REVISION
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: 'metadata.labels[''service.istio.io/canonical-revision'']'
        - name: PROXY_CONFIG
          value: |
            {"proxyMetadata":{"DNS_AGENT":""}}
        - name: ISTIO_META_POD_PORTS
          value: |-
            [
                {"containerPort":27017,"protocol":"TCP"}
            ]
        - name: ISTIO_META_APP_CONTAINERS
          value: |-
            [
                mongodb
            ]
        - name: ISTIO_META_CLUSTER_ID
          value: Kubernetes
        - name: ISTIO_META_INTERCEPTION_MODE
          value: REDIRECT
        - name: ISTIO_METAJSON_ANNOTATIONS
          value: |
            {"openshift.io/scc":"anyuid"}
        - name: ISTIO_META_WORKLOAD_NAME
          value: mongodb-v1
        - name: ISTIO_META_OWNER
          value: 'kubernetes://apis/apps/v1/namespaces/bookinfo/deployments/mongodb-v1'
        - name: ISTIO_META_MESH_ID
          value: cluster.local
        - name: DNS_AGENT
        - name: ISTIO_KUBE_APP_PROBERS
          value: '{}'
      securityContext:
        capabilities:
          drop:
            - ALL
            - MKNOD
        privileged: false
        runAsUser: 1337
        runAsGroup: 1337
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
      ports:
        - name: http-envoy-prom
          containerPort: 15090
          protocol: TCP
      imagePullPolicy: Always
      volumeMounts:
        - name: istiod-ca-cert
          mountPath: /var/run/secrets/istio
        - name: istio-data
          mountPath: /var/lib/istio/data
        - name: istio-envoy
          mountPath: /etc/istio/proxy
        - name: istio-token
          mountPath: /var/run/secrets/tokens
        - name: istio-podinfo
          mountPath: /etc/istio/pod
        - name: default-token-z4jss
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePolicy: File
      image: 'docker.io/istio/proxyv2:1.6.0-rc.2'
      args:
        - proxy
        - sidecar
        - '--domain'
        - $(POD_NAMESPACE).svc.cluster.local
        - '--serviceCluster'
        - mongodb.$(POD_NAMESPACE)
        - '--proxyLogLevel=warning'
        - '--proxyComponentLogLevel=misc:error'
        - '--trust-domain=cluster.local'
        - '--concurrency'
        - '2'
  serviceAccount: default
  volumes:
    - name: data-db
      emptyDir: {}
    - name: default-token-z4jss
      secret:
        secretName: default-token-z4jss
        defaultMode: 420
    - name: istio-envoy
      emptyDir:
        medium: Memory
    - name: istio-data
      emptyDir: {}
    - name: istio-podinfo
      downwardAPI:
        items:
          - path: labels
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels
          - path: annotations
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.annotations
        defaultMode: 420
    - name: istio-token
      projected:
        sources:
          - serviceAccountToken:
              audience: istio-ca
              expirationSeconds: 43200
              path: istio-token
        defaultMode: 420
    - name: istiod-ca-cert
      configMap:
        name: istio-ca-root-cert
        defaultMode: 420
  dnsPolicy: ClusterFirst
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/memory-pressure
      operator: Exists
      effect: NoSchedule
status:
  containerStatuses:
    - restartCount: 0
      started: true
      ready: true
      name: istio-proxy
      state:
        running:
          startedAt: '2020-05-19T14:55:54Z'
      imageID: >-
        docker.io/istio/proxyv2@sha256:d61b8b1071d801403687d92d5e07e81d7d9573a240244bae95385c7fecf0f3e3
      image: 'docker.io/istio/proxyv2:1.6.0-rc.2'
      lastState: {}
      containerID: 'cri-o://8ab936cca8257adc6661cc47fc6e95ce5524be488a3a1bef1678f54f85152119'
    - restartCount: 0
      started: true
      ready: true
      name: mongodb
      state:
        running:
          startedAt: '2020-05-19T14:55:53Z'
      imageID: >-
        docker.io/istio/examples-bookinfo-mongodb@sha256:f3364ec2d76d7db28b15f74eab2b4fd4c1b46cfa7dc0c12561648fbe3db687e9
      image: 'docker.io/istio/examples-bookinfo-mongodb:1.15.0'
      lastState: {}
      containerID: 'cri-o://fe78ca1c453782c0e67fb69b13638da24fbd7a055e9ed4ce9d1ad7b1b6aa8d8f'
  qosClass: Burstable
  podIPs:
    - ip: 10.128.2.18
  podIP: 10.128.2.18
  hostIP: 10.0.146.20
  startTime: '2020-05-19T14:54:59Z'
  initContainerStatuses:
    - name: istio-validation
      state:
        terminated:
          exitCode: 0
          reason: Completed
          startedAt: '2020-05-19T14:55:32Z'
          finishedAt: '2020-05-19T14:55:33Z'
          containerID: >-
            cri-o://e0cc6dc8278cc68bae7a5c5062bd353b65382bc81b94b038a70bc4ad16c9a77b
      lastState: {}
      ready: true
      restartCount: 0
      image: 'docker.io/istio/proxyv2:1.6.0-rc.2'
      imageID: >-
        docker.io/istio/proxyv2@sha256:d61b8b1071d801403687d92d5e07e81d7d9573a240244bae95385c7fecf0f3e3
      containerID: 'cri-o://e0cc6dc8278cc68bae7a5c5062bd353b65382bc81b94b038a70bc4ad16c9a77b'
  conditions:
    - type: Initialized
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2020-05-19T14:55:33Z'
    - type: Ready
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2020-05-19T14:55:58Z'
    - type: ContainersReady
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2020-05-19T14:55:58Z'
    - type: PodScheduled
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2020-05-19T14:54:59Z'
  phase: Running

**Comment by jshaughn** [comment]
Sorry, @bianpengyuan, here are the dumps you wanted.  Feel free to delete the above comment if you like.

[dump_mongov1_json.txt](https://github.com/istio/istio/files/4653200/dump_mongov1_json.txt)
[dump_ratingsv2_json.txt](https://github.com/istio/istio/files/4653201/dump_ratingsv2_json.txt)

**Comment by bianpengyuan** [comment]
Ah, do you turned off mtls or auto-mtls? TCP stats will require mtls in order to be fully populated. It relies on ALPN to make sure both sides have sidecar and they are capable for exchange metadata.

**Comment by gargnupur** [comment]
Even if mtls is on, I think this would be another case of https://github.com/istio/istio/issues/23907 -> UpstreamTlsContext doesn't have `istio-peer-exchange` alpn as the cluster has http2_protocol_options specified.

**Comment by bianpengyuan** [comment]
@gargnupur That does not apply here. Mongo db in bookinfo has its port named and proto sniffing is not enabled here.

**Comment by jshaughn** [comment]
@bianpengyuan I think mTLS was the problem.  It was off in my original test.  When I turn it on I'm not seeing the disconnected telemetry.  So, if this is the expected telemetry I guess we can close this issue.

**Comment by bianpengyuan** [comment]
@jshaughn Thanks!

**Comment by whitleykeith** [comment]
I have a very similar issue that was resolved *partially* by turning mTLS on, but I still have issues with some TCP services like Zookeeper even with mTLS active.

**Comment by gargnupur** [comment]
@whitleykeith : can you share the config_dump of istio-proxy of your pods with us?

**Comment by whitleykeith** [comment]
[config.txt](https://github.com/istio/istio/files/4668535/config.txt)
