### ISSUE TITLE
Blocking one microservice to send requests to other microservices

### ISSUE THREAD

**Issue by Shashankft9** [istio/istio#23967]
I went through the documentation and examples but failed to achieve this use case: 
Lets say there is a namespace `test`, and it has two microservices `test-1` and `test-2`. And there is another namespace` target`. How can I make sure that my `test-1` microservice can send requests to the `target` ns microservices while the other microservice `test-2` can't?

Sidecar CRD can do the blocking of complete namespace but can I achieve this fine tuning within the namespaces as well?
Please point me to the documentation if I have missed something there.

**Comment by howardjohn** [comment]
Take a look at our authorization APIs: https://istio.io/docs/tasks/security/authorization/

**Comment by Shashankft9** [comment]
@howardjohn thanks for the quick response. So, if I let the `selector` in `spec` be empty and just mention the rules as: 
```
rules:
  - from:
    - source:
        principals: test-1 sa
    to:
    - operation:
        methods: ["POST"]
```
the policy applies on the complete namspace, allows `test-1` to POST while stops `test-2` to do the same, is it? 
Anyway, I am going to try this hands on as well, currently installing Istio in our infra, thanks a lot!
