### ISSUE TITLE
Look again at support for W3C Trace Context for distributed tracing

### ISSUE THREAD

**Issue by jnovick** [istio/istio#23960]
**Describe the feature request**

There previously was an issue for this but it got closed due to inactivity and was wondering whether it should be re-examined again. You can look at it for more details: https://github.com/istio/istio/issues/16703

**Describe alternatives you've considered**

**Additional context**

I see W3C support in Envoy: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/trace/v3/opencensus.proto.html?highlight=w3c#enum-config-trace-v3-opencensusconfig-tracecontext

**Comment by alx13** [comment]
For us it's real pain because we are using NewRelic monitoring, and NR monitoring agent is supporting W3C headers, but not supporting B3. So spans within application are not connected with spans in istio.

Very hacky solution for 1.5.4: I hijacked [envoy_bootstrap_v2.json#L579](https://github.com/istio/istio/blob/1.5.4/tools/packaging/common/envoy_bootstrap_v2.json#L579)

Replacing in my docker image it with
```json
  {{ if .zipkin }}
  ,
  "tracing": {
    "http": {
      "name": "envoy.tracers.opencensus",
      "config": {
      "zipkin_exporter_enabled": true,
      "zipkin_url":  "http://{{ .zipkin.address }}/api/v2/spans",
      "stdout_exporter_enabled": false,
      "incoming_trace_context": ["CLOUD_TRACE_CONTEXT", "TRACE_CONTEXT", "GRPC_TRACE_BIN", "B3"],
      "outgoing_trace_context": ["CLOUD_TRACE_CONTEXT", "TRACE_CONTEXT", "GRPC_TRACE_BIN", "B3"],
      "trace_config":{
        "constant_sampler":{
          "decision": "ALWAYS_PARENT"
        },
        "max_number_of_annotations": 50,
        "max_number_of_attributes": 50,
        "max_number_of_message_events": 100,
        "max_number_of_links": 200
       }
     }
  }}
```

In that case envoy will use OpenCensus tracer but will send data to zipkin/jaeger.

Other hacks to consider — in envoy 1.14 we can mitigate this with EnvoyFilter. Adding NETWORK_FILTER with [jaeger](https://github.com/envoyproxy/envoy/blob/v1.14.1/examples/jaeger-tracing/front-envoy-jaeger.yaml) to use OpenCensus tracing.

So from Istio POV quick solution for this is to just to make OpenCensus configurable with IstioOperator, not only Stackdriver.

**Comment by verysonglaa** [comment]
Second that Feature Request, also there was another discussion here:
https://discuss.istio.io/t/configurable-trace-header-proposal/4085

**Comment by yvespp** [comment]
We have the same problem as @alx13 but with Azure Application Insights. It uses W3C headers and Istio traces are not integration into application traces.

Maybe an easy option would be to add another [EnvoyFilter.ApplyTo](https://istio.io/latest/docs/reference/config/networking/envoy-filter/#EnvoyFilter-ApplyTo) section to be able to overwrite the envoy tracing configuration completely?

**Comment by techgeek03** [comment]
We have the exact same problem as @yvespp 

Is there any update on this or any possible workaround or documentation?

**Comment by jnovick** [comment]
Any update?

**Comment by bianpengyuan** [comment]
There is work going on to add API for opencensus agent, which supports configurable tracing context: https://github.com/istio/api/pull/1563

I am wondering though would that solve most use cases, or would it also be necessary to provide configurability on zipkin tracer to use Opecensus implementation for configurable trace context? It would be great to get your input on this.

**Comment by verysonglaa** [comment]
Great that there is work going on in order to use W3C Trace Context! Right now we use the same config as @alx13 and forward traces to OpenTelemetry Collector.
Configurable Trace Context for zipkin would be another options since this is the only reason we had to switch to opencensus.

**Comment by bianpengyuan** [comment]
@verysonglaa dummy question: would opencensus-agent tracer work along with opentelemetry collector, so that you can remove the bootstrap hack?

**Comment by kyessenov** [comment]
Re: Envoy's zipkin driver supporting other headers -- that would be neat, but the way they are written assumes the driver's responsibility to propagate headers. If we could share more code of open* with envoy's drivers, we could reuse the header propagation.

I think we could just add another header to the mix. The drawback is one extra header (it's unconditional, as it doesn't correlate what was received to what needs to be sent).

**Comment by bianpengyuan** [comment]
@kyessenov opencensus tracer already supports zipkin exporter, so we already have a way to achieve this instead of updating zipkin driver.

**Comment by verysonglaa** [comment]
@bianpengyuan There is a minor Issue in envoy (https://github.com/envoyproxy/envoy/issues/12538) but apart from that it works. We use OpenCensus tracer with OpenTelemetry-Collector and even OpenTelemetry azuremonitor exporter from the contrib repository.

**Comment by cudneys** [comment]
We're also seeing issues similar to what @alx13 is seeing with New Relic.  Given the time this has been open and the number of people asking for resolution, would it be possible to prioritize this issue?

**Comment by jnovick** [comment]
I believe it would be a poor decision to close this issue given the number of interested individuals. Please take action to prevent the bot from closing this issue automatically.

**Comment by bianpengyuan** [comment]
We have opencensus agent support now, which can use w3c trace context: https://github.com/istio/api/blob/8779b36cec99337f1b7dbd5f84a6b0e963aba0cb/mesh/v1alpha1/proxy.proto#L141

Will this suffice the need?

**Comment by jnovick** [comment]
I think that it will, but since Envoy supports W3C, I still feel like Istio should, but if OpenCensus allows W3C and when OpenTelemetry gets added, it will too then I guess it is fine for now. How do others feel?

**Comment by verysonglaa** [comment]
W3C Header support with OpenCensus works for us too.
Exporting it to Azure Monitor still requires a workaround because of https://github.com/envoyproxy/envoy/issues/12538

**Comment by bianpengyuan** [comment]
@jnovick @verysonglaa Thanks a lot for the information! I will close this issue for now, please reopen if you think more action is needed here.

**Comment by Vijay-Nirmal** [comment]
How to use OpenCensusAgent?

I have installed the below configuration, but still doesn't recognize `traceparent` header that is passed in the request.

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    global: 
      proxy: 
        tracer: openCensusAgent
```

When I check in jagger, it shows it's still using zipkin

![image](https://user-images.githubusercontent.com/24755596/122373070-d3badd80-cf7e-11eb-9ea5-04ccb0bf3507.png)

**Comment by SubhadeepSen** [comment]
@verysonglaa I've trying to use OpenCensus tracer with OpenTelemetry-Collector but I'm facing challenges when mTLS is enabled. Could you please help.
https://github.com/istio/istio/issues/35274
