### ISSUE TITLE
istioctl function review and validation for central istiod

### ISSUE THREAD

**Issue by linsun** [istio/istio#23978]
**Describe the feature request**

We need to understand what istioctl cmds are working and not working for central istiod, particularly for remote cluster (see scenario 1  - https://github.com/istio/istio/issues/23182#issuecomment-631196102)

I've found `istioctl ps` is broken.

`istioctl kube-inject` is also broken.
**Describe alternatives you've considered**

**Additional context**

**Comment by linsun** [comment]
@esnible appreciate you have this as an 1.7 item for UX roadmap

cc @irisdingbj

**Comment by esnible** [comment]
istioctl commands that port-forward into Istiod pods:

`proxy-status`
- GET /debug/syncz

`proxy-status <pod>`
- GET /debug/config_dump?proxyID=%s.%s

version
- GET /debug/syncz
- (Gets the versions of the istio-proxy sidecars)

`experimental wait`
- /debug/config_distribution?resource=%s

`experimental describe`
- Currently does not use /debug
- /debug/authenticationz?proxyID=%s.%s used until PR 22407
- We’d like to restore the the UI lost by the PR, telling us if clients will use HTTP or HTTPS

**Comment by esnible** [comment]
I should point out we already did much of this work for https://github.com/istio/istio/issues/23538 .  The two Issues should be linked.
