### ISSUE TITLE
Istio 1.5.1 periodically reports high inbound traffic latencies

### ISSUE THREAD

**Issue by AlexDHoffer** [istio/istio#23973]
**Bug description**

An upgrade to Istio 1.5.1 seems to have caused the istio_request_duration_milliseconds_bucket to periodically report very high p95 latencies, specifically when the window of the metric is low (~1 minute).

Specifically, the following metric:

``sum(rate(istio_request_duration_milliseconds_bucket{reporter="destination",destination_app!~"unknown|telemetry", cluster=~"$Cluster"}[**1m**])) by (le, cluster)))``

... occasionally yields the following:

![image](https://user-images.githubusercontent.com/19369483/82389278-976e2400-99f0-11ea-9950-751f915c0e78.png)

... but if we tweak this metric to instead be a 3 minute window, e.g.:

``sum(rate(istio_request_duration_milliseconds_bucket{reporter="destination",destination_app!~"unknown|telemetry", cluster=~"$Cluster"}[**3m**])) by (le, cluster)))``

we get:

![image](https://user-images.githubusercontent.com/19369483/82389353-cdaba380-99f0-11ea-9be2-5aa4981f677b.png)

**Expected behavior**

We expect the 1 minute reporting window to not report a far higher latency than the 3 minute reporting window.

**Steps to reproduce the bug**

- install Istio 1.5.1 mixerless with only istiod and istio-ingressgateway
- create a Prometheus query with the query listed above
- toggle the 1m to 3m reporting window for the metric listed above and see the value alternate wildly

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

Istio 1.5.1

**How was Istio installed?**

Using the Operator

**Environment where bug was observed (cloud vendor, OS, etc)**

Azure Kubernetes Service 1.16.7

**Comment by bianpengyuan** [comment]
So is it possible that your service is actually responding occasionally with 10s latency? You can check it by enabling tracing, or access log on the problematic workload (https://github.com/istio/istio/wiki/EnvoyFilter-Samples#tracing-and-access-logging).

Your observation would make sense if the service indeed could take 10s to response, in which cases 1 min might not have enough requests, so 95p would be dedicated by outliers.
