### ISSUE TITLE
Installing istio with istioctl version 1.5.2 fails during applying manifest

### ISSUE THREAD

**Issue by Adharsh-Muraleedharan** [istio/istio#23990]
**Bug description**
Installing Istio on our EKS cluster via istioctl fails while applying manifest.
note: if i rerun it again it get deployed

**Expected behavior**
Should be correctly deployed without erroring out

**Steps to reproduce the bug**
Below are the shell commands used to install istio via istioctl:

curl -L https://git.io/getLatestIstio | ISTIO_VERSION=1.5.2 sh -

export PATH=$PWD/istio-1.5.2/bin:$PATH

istioctl manifest generate      --set values.gateways.istio-ingressgateway.type=NodePort      --set values.grafana.enabled=true      --set values.tracing.enabled=true      --set values.kiali.enabled=true      --set values.prometheus.enabled=true      --set values.global.proxy.accessLogFile="/dev/stdout"      --set values.kiali.dashboard.jaegerURL=http://jaeger-query:16686      --set values.kiali.dashboard.grafanaURL=http://grafana:3000 > $HOME/install_istio.yml

kubectl apply -f $HOME/install_istio.yml

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS cloud provider

**LOGS when running the manifest**

clusterrole.rbac.authorization.k8s.io/kiali configured
clusterrole.rbac.authorization.k8s.io/kiali-viewer configured
clusterrolebinding.rbac.authorization.k8s.io/kiali configured
clusterrole.rbac.authorization.k8s.io/prometheus-istio-system configured
clusterrolebinding.rbac.authorization.k8s.io/prometheus-istio-system configured
clusterrole.rbac.authorization.k8s.io/istio-reader-istio-system configured
clusterrolebinding.rbac.authorization.k8s.io/istio-reader-istio-system configured
customresourcedefinition.apiextensions.k8s.io/meshpolicies.authentication.istio.io configured
customresourcedefinition.apiextensions.k8s.io/policies.authentication.istio.io configured
customresourcedefinition.apiextensions.k8s.io/httpapispecs.config.istio.io configured
customresourcedefinition.apiextensions.k8s.io/httpapispecbindings.config.istio.io configured
customresourcedefinition.apiextensions.k8s.io/quotaspecs.config.istio.io configured
customresourcedefinition.apiextensions.k8s.io/quotaspecbindings.config.istio.io configured
customresourcedefinition.apiextensions.k8s.io/destinationrules.networking.istio.io configured
customresourcedefinition.apiextensions.k8s.io/envoyfilters.networking.istio.io configured
customresourcedefinition.apiextensions.k8s.io/gateways.networking.istio.io configured
customresourcedefinition.apiextensions.k8s.io/serviceentries.networking.istio.io configured
customresourcedefinition.apiextensions.k8s.io/sidecars.networking.istio.io configured
customresourcedefinition.apiextensions.k8s.io/virtualservices.networking.istio.io configured
customresourcedefinition.apiextensions.k8s.io/attributemanifests.config.istio.io configured
customresourcedefinition.apiextensions.k8s.io/handlers.config.istio.io configured
customresourcedefinition.apiextensions.k8s.io/instances.config.istio.io configured
customresourcedefinition.apiextensions.k8s.io/rules.config.istio.io configured
customresourcedefinition.apiextensions.k8s.io/clusterrbacconfigs.rbac.istio.io configured
customresourcedefinition.apiextensions.k8s.io/rbacconfigs.rbac.istio.io configured
customresourcedefinition.apiextensions.k8s.io/serviceroles.rbac.istio.io configured
customresourcedefinition.apiextensions.k8s.io/servicerolebindings.rbac.istio.io configured
customresourcedefinition.apiextensions.k8s.io/authorizationpolicies.security.istio.io configured
customresourcedefinition.apiextensions.k8s.io/peerauthentications.security.istio.io created
customresourcedefinition.apiextensions.k8s.io/requestauthentications.security.istio.io created
customresourcedefinition.apiextensions.k8s.io/adapters.config.istio.io configured
customresourcedefinition.apiextensions.k8s.io/templates.config.istio.io configured
namespace/istio-system created
serviceaccount/istio-reader-service-account created
horizontalpodautoscaler.autoscaling/istio-ingressgateway created
deployment.apps/istio-ingressgateway created
gateway.networking.istio.io/istio-ingressgateway created
poddisruptionbudget.policy/ingressgateway created
role.rbac.authorization.k8s.io/istio-ingressgateway-sds created
rolebinding.rbac.authorization.k8s.io/istio-ingressgateway-sds created
service/istio-ingressgateway created
serviceaccount/istio-ingressgateway-service-account created
sidecar.networking.istio.io/default created
horizontalpodautoscaler.autoscaling/istiod created
clusterrole.rbac.authorization.k8s.io/istio-galley-istio-system configured
clusterrole.rbac.authorization.k8s.io/istio-pilot-istio-system configured
clusterrole.rbac.authorization.k8s.io/istiod-istio-system created
clusterrolebinding.rbac.authorization.k8s.io/istio-pilot-istio-system configured
clusterrolebinding.rbac.authorization.k8s.io/istiod-istio-system created
configmap/pilot-envoy-config created
configmap/istio created
deployment.apps/istiod created
configmap/istio-sidecar-injector created
mutatingwebhookconfiguration.admissionregistration.k8s.io/istio-sidecar-injector configured
poddisruptionbudget.policy/istiod created
service/istio-pilot created
service/istiod created
serviceaccount/istio-pilot-service-account created
envoyfilter.networking.istio.io/metadata-exchange-1.4 created
envoyfilter.networking.istio.io/stats-filter-1.4 created
envoyfilter.networking.istio.io/metadata-exchange-1.5 created
envoyfilter.networking.istio.io/tcp-metadata-exchange-1.5 created
envoyfilter.networking.istio.io/stats-filter-1.5 created
envoyfilter.networking.istio.io/tcp-stats-filter-1.5 created
validatingwebhookconfiguration.admissionregistration.k8s.io/istiod-istio-system created
validatingwebhookconfiguration.admissionregistration.k8s.io/istio-galley created
Error from server (NotFound): error when creating "/home/ec2-user/install_istio.yml": namespaces "istio-system" not found
Error from server (NotFound): error when creating "/home/ec2-user/install_istio.yml": namespaces "istio-system" not found
Error from server (NotFound): error when creating "/home/ec2-user/install_istio.yml": namespaces "istio-system" not found
Error from server (NotFound): error when creating "/home/ec2-user/install_istio.yml": namespaces "istio-system" not found
Error from server (NotFound): error when creating "/home/ec2-user/install_istio.yml": namespaces "istio-system" not found
Error from server (NotFound): error when creating "/home/ec2-user/install_istio.yml": namespaces "istio-system" not found
Error from server (NotFound): error when creating "/home/ec2-user/install_istio.yml": namespaces "istio-system" not found
Error from server (NotFound): error when creating "/home/ec2-user/install_istio.yml": namespaces "istio-system" not found
Error from server (NotFound): error when creating "/home/ec2-user/install_istio.yml": namespaces "istio-system" not found
Error from server (NotFound): error when creating "/home/ec2-user/install_istio.yml": namespaces "istio-system" not found
Error from server (NotFound): error when creating "/home/ec2-user/install_istio.yml": namespaces "istio-system" not found
Error from server (NotFound): error when creating "/home/ec2-user/install_istio.yml": namespaces "istio-system" not found
Error from server (NotFound): error when creating "/home/ec2-user/install_istio.yml": namespaces "istio-system" not found
Error from server (NotFound): error when creating "/home/ec2-user/install_istio.yml": namespaces "istio-system" not found
Error from server (NotFound): error when creating "/home/ec2-user/install_istio.yml": namespaces "istio-system" not found
Error from server (NotFound): error when creating "/home/ec2-user/install_istio.yml": namespaces "istio-system" not found
Error from server (NotFound): error when creating "/home/ec2-user/install_istio.yml": namespaces "istio-system" not found
Error from server (NotFound): error when creating "/home/ec2-user/install_istio.yml": namespaces "istio-system" not found
Error from server (NotFound): error when creating "/home/ec2-user/install_istio.yml": namespaces "istio-system" not found
Error from server (NotFound): error when creating "/home/ec2-user/install_istio.yml": namespaces "istio-system" not found
Error from server (NotFound): error when creating "/home/ec2-user/install_istio.yml": namespaces "istio-system" not found
Error from server (NotFound): error when creating "/home/ec2-user/install_istio.yml": namespaces "istio-system" not found
Error from server (NotFound): error when creating "/home/ec2-user/install_istio.yml": namespaces "istio-system" not found
Error from server (NotFound): error when creating "/home/ec2-user/install_istio.yml": namespaces "istio-system" not found
Error from server (NotFound): error when creating "/home/ec2-user/install_istio.yml": namespaces "istio-system" not found
Error from server (NotFound): error when creating "/home/ec2-user/install_istio.yml": namespaces "istio-system" not found
Error from server (NotFound): error when creating "/home/ec2-user/install_istio.yml": namespaces "istio-system" not found

**Comment by Adharsh-Muraleedharan** [comment]
@ramaraochavali - Could you please help us with this ?
Also we would like to know what is the best way to upgrade istio from one version to another without any traffic loss in prod setup ?

Thanks in Advance

**Comment by howardjohn** [comment]
You need to create the istio-system namespace prior to kubectl apply

**Comment by VinothChinnadurai** [comment]
Thanks @howardjohn . We also would want best practice of istio degradation for production clusters without losing any traffic. if we have any document. Kindly suggest

**Comment by howardjohn** [comment]
This is documented under https://preliminary.istio.io/latest/docs/setup/install/istioctl/#generate-a-manifest-before-installation. Thanks!
