### ISSUE TITLE
Istio 1.2.10 TLS connection issues with GCP Cloud NAT, under load

### ISSUE THREAD

**Issue by nareshbaliga** [istio/istio#23996]
**Bug description**
When an external HTTPS endpoint is accessed through the istio-proxy and GCP Cloud NAT, TLS connection issues start getting reported after a certain requests/sec rate is crossed.

I have a curl script that executes within a container and hits an externally located HTTPS endpoint. The endpoint is a randomly chosen asset on cnn.com, but the issue presents itself with any HTTPS endpoint.  

I don't have an Egress gateway set up, nor do I have Istio ServiceEntry resources created. Therefore Envoy rightly reports this endpoint as a *PassThroughCluster*.

The exact error curl returns is: 
> CURLE_SSL_CONNECT_ERROR (35)
> A problem occurred somewhere in the SSL/TLS handshake. You really want the error buffer and read the message there as it pinpoints the problem slightly more. Could be certificates (file formats, paths, permissions), passwords, and others.

When I examine the stats on the Envoy proxy, for the PassThroughCluster, I see cx_connect_fail errors reported.

The behavior & scenario is as follows:
- there is no other traffic other than the curl script.
- the curl script generate a load of 25 requests/second.
- GCP Cloud NAT with 2048 minimum ports per VM.
- intermittent failures start occurring. That is, once the traffic has ramped up for about 4 minutes, the errors start occurring, but they aren't continuous.

From the GCP metrics, the issue seems to coincide with the [nat/open_connections](https://cloud.google.com/monitoring/api/metrics_gcp) metric hovering around or exceeding the *nat/allocated_ports* metric.

Normally, I would conclude that this is either a GCP issue or a miscalculation on the NAT IP and ports provisioned.

However, the reason I thought I should ask the question in this forum is that, if I deploy the container with the curl script *without* Envoy, and still go through the NAT, I don't see any errors at that 25 requests/sec rate.

I have to bump up the traffic to 50 requests/sec before I start seeing errors and they occur at a much lower frequency. 

It looks as though connections established by Envoy through the NAT "linger" around longer?

The Cloud NAT has a  2 minute period before it can return a used connection back to the pool, however that is the same irrespective whether the connection was through Envoy or not.
   

**Expected behavior**
Applications issuing outbound HTTPS calls through Envoy and Cloud NAT, should have similar success rates than without Envoy. 

**Steps to reproduce the bug**
1. Create a private GKE cluster and install Istio using the Istio AddOn feature. 

2. Configure a Cloud NAT and configure such that access to external endpoints go through the NAT. Specify 2048 minimum ports per VM while configuring the NAT.

3. Have a simple shell script that executes a curl GET against say, https://widgets.outbrain.com/nanoWidget/externals/cookie/put.html  

4. Deploy a simple container into an istio enabled namespace. I used: https://raw.githubusercontent.com/istio/istio/release-1.5/samples/sleep/sleep.yaml

5. Copy the shell script into the sample container and execute multiple instances (I used about 5 and it generated approximately 25 request/sec).

6. Observe that the curl command will start reporting return code 35 errors about 4 minutes into the scenario. One can observe the _nat/open_connections_

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
`client version: version.BuildInfo{Version:"1.1.7", GitRevision:"eec7a74473deee98cad0a996f41a32a47dd453c2", User:"root", Host:"341b3bf0-76ac-11e9-b644-0a580a2c0404", GolangVersion:"go1.10.4", DockerHub:"docker.io/istio", BuildStatus:"Clean", GitTag:"1.1.6-6-geec7a74"}
citadel version: version.BuildInfo{Version:"c834c448a92e691d71b42a966d94fb1822ac10e1-dirty", GitRevision:"c834c448a92e691d71b42a966d94fb1822ac10e1-dirty", User:"root", Host:"8c5fc6a5f8f7", GolangVersion:"go1.12.12", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.2.10-gke.2-1-gc834c44"}
galley version: version.BuildInfo{Version:"c834c448a92e691d71b42a966d94fb1822ac10e1-dirty", GitRevision:"c834c448a92e691d71b42a966d94fb1822ac10e1-dirty", User:"root", Host:"8c5fc6a5f8f7", GolangVersion:"go1.12.12", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.2.10-gke.2-1-gc834c44"}
ingressgateway version: version.BuildInfo{Version:"c834c448a92e691d71b42a966d94fb1822ac10e1-dirty", GitRevision:"c834c448a92e691d71b42a966d94fb1822ac10e1-dirty", User:"root", Host:"8c5fc6a5f8f7", GolangVersion:"go1.12.12", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.2.10-gke.2-1-gc834c44"}
pilot version: version.BuildInfo{Version:"c834c448a92e691d71b42a966d94fb1822ac10e1-dirty", GitRevision:"c834c448a92e691d71b42a966d94fb1822ac10e1-dirty", User:"root", Host:"8c5fc6a5f8f7", GolangVersion:"go1.12.12", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.2.10-gke.2-1-gc834c44"}
policy version: version.BuildInfo{Version:"c834c448a92e691d71b42a966d94fb1822ac10e1-dirty", GitRevision:"c834c448a92e691d71b42a966d94fb1822ac10e1-dirty", User:"root", Host:"8c5fc6a5f8f7", GolangVersion:"go1.12.12", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.2.10-gke.2-1-gc834c44"}
sidecar-injector version: version.BuildInfo{Version:"c834c448a92e691d71b42a966d94fb1822ac10e1-dirty", GitRevision:"c834c448a92e691d71b42a966d94fb1822ac10e1-dirty", User:"root", Host:"8c5fc6a5f8f7", GolangVersion:"go1.12.12", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.2.10-gke.2-1-gc834c44"}
telemetry version: version.BuildInfo{Version:"c834c448a92e691d71b42a966d94fb1822ac10e1-dirty", GitRevision:"c834c448a92e691d71b42a966d94fb1822ac10e1-dirty", User:"root", Host:"8c5fc6a5f8f7", GolangVersion:"go1.12.12", DockerHub:"docker.io/istio", BuildStatus:"Modified", GitTag:"1.2.10-gke.2-1-gc834c44"}
`

**How was Istio installed?**
GKE's Istio AddOn feature.

GKE version 1.14.10-gke.36
Istio version 1.2.10

**Environment where bug was observed (cloud vendor, OS, etc)**
Cloud Vendor: GCP
OS: Container-Optimized OS from Google

**Comment by nareshbaliga** [comment]
I bumped the nat/allocated_ports for the Cloud NAT instance to 4096 to give it more head room.

I'm still seeing about 0.2% failure rate when the traffic goes through Envoy with the same SSL related return code from curl. Possibly the 

I've investigated the Envoy stats to see whether the circuit breaker was being tripped, and the count was always 0.

**Comment by howardjohn** [comment]
I tried this locally. What I found is that without envoy, all connections are closed; after curl netstat shows nothing. With envoy, we have 1 connection opened at a time as reported by `server.total_connections` from envoy, but a TIME_WAIT connection for a bit after

**Comment by nareshbaliga** [comment]
The issue was caused due to non-connection pooling for HTTPS connections. There is connection pooling in Envoy for HTTP, so the issue does not occur for plain connections.

We worked around the issue by introducing connection pooling for HTTPS in the business application. Not ideal but that was the only solution.

**Comment by howardjohn** [comment]
@nareshbaliga thanks for the update! I think since this is an Envoy level issue this would need to be a feature request there and we would automatically pick it up if implemented. Thanks!
