### ISSUE TITLE
istio logging level missing a level between info and debug or need to move a lot of logging to debug - logger

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#2400]
istio logging level missing a level between info and debug or need to move a lot of logging to debug:

moving the discussion from #2240 here

The idea is that the out of the box level of logging for istio components - Info - isn't flooding the logs with per request information (otherwise istio generates too many IOs)

But we merged the glog V(1), V(2) and Info into a single level

We should either add a Verbose level for V1,V2 (debug being V3+) or examine each Info to move per request logging to Debug... (which will get mixed with super floody Debug...)

cc @ZackButcher @geeknoid @mandarjog

**Comment by geeknoid** [comment]
The logging system we are now using supports only debug, info, warning,
error and it's not extensible. We can't just slide in a new level.

The approach we need to use is to introduce specific command-line flags to
enable specific additional output. So instead of -V=2 that enables some
random output in your component, you'd do --log_my_feature to turn on extra
logging for the specific feature you care about.

**Comment by kyessenov** [comment]
Another deficiency of the new log is not having ability to filter by source
code file. In glog, you can specify levels per source, allowing module- or
feature-level logging customization.
How do we do with the new log system?

**Comment by geeknoid** [comment]
The current log functionality doesn't support per-source filtering. Unlike
adding a log level, I do think we could overlay support for filtering out
requests from particular source files if this is a high-value feature.

**Comment by kyessenov** [comment]
I think this feature would restore the ability to apply higher verbosity to modules/features, that was available prior to switch away from glog.

**Comment by geeknoid** [comment]
I think #4939 addresses this overall issue nicely. I'm closing this, please open specific issues if we want more features added to scopes.
