### ISSUE TITLE
Validate PDB and HPA settings are compatible

### ISSUE THREAD

**Issue by ostromart** [istio/istio#24000]
autoscaling enabled causes PDBs to be installed, but there's no enforcement of minReplicas to be compliant with PDB which means that if the value is too low pods can be completely prevented from restarting, blocking rescheduling, upgrade etc. 
This feature would at least validate that the settings are correct.

**Comment by howardjohn** [comment]
It's not just about validating they are correct, right? Our current defaults are "wrong" so we would need to change those

**Comment by adiprerepa** [comment]
where are the current defaults even located? is this a k8s issue?

**Comment by tariq1890** [comment]
Yes the default are "wrong". If we are enabling PodDisruptionBudgets by default, then we must raise the minReplicas of HPA to 2

**Comment by sdake** [comment]
Hi gang,

For the PR associated with this issue, there is alot of context here: https://github.com/istio/istio/issues/12602#issuecomment-489449657. The defaults are definitely busted. 👍

**Comment by ostromart** [comment]
we should modify the defaults but the correct value must be conditional on whether PDBs are enabled or not, so that would have to be wrapped up in some logic.

**Comment by Vaccano** [comment]
Not sure if it matters, but as a person fairly new to istio, this has been a huge stumbling block to my adoption.  There is no guidance (that I can find) on how to increase the HPA min count.  And I can't drain my node because of the PDB.  Catch 22.  My only option is to uninstall Istio, drain and upgrade my nodes, then re-install Istio. (Yuck)

**Comment by benjaminxie** [comment]
@Vaccano I was about to reply to you with your own post over at [unable to drain k8s node running istio-policy pod
#12602](https://github.com/istio/istio/issues/12602#issuecomment-840936217)

But if anyone is here and hadn't found the above thread yet, that comment links to a istio-operator manifest that might help.
