### ISSUE TITLE
istioctl: pilot-agent request port is hardcoded to 15000

### ISSUE THREAD

**Issue by yjbdsky** [istio/istio#24004]
**Bug description**
When I modify the envoy adminPort, the istio pc command is not available because the pilot-angent request port is hardcoded to 15000
![image](https://user-images.githubusercontent.com/20083081/82517722-4b39f580-9b50-11ea-9199-eef1a8861322.png)

**Expected behavior**
Modify adminPort in istio-sidecar-injector configmap
**Steps to reproduce the bug**
istioctl pc cluster -n istio-system podName
**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
all version
**How was Istio installed?**
Custom installation
**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by esnible** [comment]
I believe Istio's install does not provide a mechanism to customize the proxyAdminPort.

The port can be customized by editing the istio-system/istio ConfigMap, and therefore it makes sense to allow _istioctl_ to work with other ports.

Can you give us some background on why you have modified this value?  I cannot recall anyone else doing so.

The mechanism of https://github.com/istio/istio/pull/24003 , parsing _/etc/istio/proxy/envoy-rev0.json_ , seems to introduce dependencies on the current Envoy config.  It might be better to solve this another way.

One possibility is to introduce `--proxyAdminPort <port>` to the _istioctl_ commands that talk to Envoy's admin port.  These commands are `proxy-config`, `proxy-status`, `version`, `experimental describe`, and `experimental authz`.  `<port>` would default to 15000, or perhaps default to the value of `$ISTIO_PROXY_ADMIN_PORT` if defined.

Another possibility is to have _istioctl_ fetch the `istio` ConfigMap and extract the proxy admin port from it.

@istio/wg-user-experience-maintainers Do we have any opinions?  I am inclined to the former?

**Comment by howardjohn** [comment]
The other option is to have the agent automatically determine the port, but not from envoy-rev0.json. Instead use the same info we use to set it to 15000 in the first place (reading the proxy config)

**Comment by esnible** [comment]
@howardjohn It makes sense to read 15000 from the config map by default.  Perhaps the user should be able to override it for non-K8s scenarios.

For 1.7 _istioctl_ may also talk to Envoy on :15090 and 15090 is not stored in the config map.  What approach do you recommend for that?

**Comment by howardjohn** [comment]
15090 is hardcoded and not configurable so shouldn't be an issue

I am not suggesting we read the config map directly - the agent already
reads the mesh config through a variety of mechanisms. When you kubectl
exec do you retain the pods Environments variables, and volume mounts? if
so we can read those, if not maybe it won't work

**Comment by yjbdsky** [comment]
thks
The background of modifying adminPort is: reserve 10000-12000 ports for istio to prevent conflicts with users' application ports
I read the code of the pilot-angent proxy, the proxy has multiple ways to obtain the mesh config.
Is it possible to interact through environment , pilot-angent proxy sets an environment variable when writing envoy-rev0.json, and pilot-angent request uses this variable to obtain the configuration file path?

> I believe Istio's install does not provide a mechanism to customize the proxyAdminPort.
> 
> The port can be customized by editing the istio-system/istio ConfigMap, and therefore it makes sense to allow _istioctl_ to work with other ports.
> 
> Can you give us some background on why you have modified this value? I cannot recall anyone else doing so.
> 
> The mechanism of #24003 , parsing _/etc/istio/proxy/envoy-rev0.json_ , seems to introduce dependencies on the current Envoy config. It might be better to solve this another way.
> 
> One possibility is to introduce `--proxyAdminPort <port>` to the _istioctl_ commands that talk to Envoy's admin port. These commands are `proxy-config`, `proxy-status`, `version`, `experimental describe`, and `experimental authz`. `<port>` would default to 15000, or perhaps default to the value of `$ISTIO_PROXY_ADMIN_PORT` if defined.
> 
> Another possibility is to have _istioctl_ fetch the `istio` ConfigMap and extract the proxy admin port from it.
> 
> @istio/wg-user-experience-maintainers Do we have any opinions? I am inclined to the former?

**Comment by esnible** [comment]
@howardjohn We use port-forwarding now, not exec.  This improves performance and lets us improve security.

It would be ideal not to exec into the pod just to find out the admin port.  We know it from the ConfigMap.  The pod metadata does not have it.  I don't see it with exec and `PRINTENV`.

**Comment by howardjohn** [comment]
Mesh config is injected as an environment variable. This likely I'd the
same as configmap but may not be. And `pilot-agent request` is a binary on
the sidecar so it can only be run by exec I think - however, istioctl is no
longer using this itself as you mentioned.

So there is actually two different problems, supporting istioctl and
supporting pilot-agent request

**Comment by esnible** [comment]
We now use --xds-port or --xds-address to let Istioctl use alternate XDS ports, and ~/.istio/config to default the value.

I propose we target 1.8 for this, and use --sidecar-port as the flag name.

These commands contact Envoy: `proxy-config`, `proxy-status`, `x authz` and `x describe`.  All of these commands would get the new flag.

**Comment by Yorkerrr** [comment]
I have same issue with connecting to custom admin port with istioctl, is there any way so I can configure istioctl to work with non 15000 port?

**Comment by esnible** [comment]
@Yorkerrr it isn't much work, but few have asked for it.  Feel free to re-open this issue, but we are short on volunteers who would do the work.
