### ISSUE TITLE
istio use http1.1 instead of http2 which should be

### ISSUE THREAD

**Issue by xzhao1** [istio/istio#24011]
**Bug description**
We have application, if not deployed on kubernets,  the request from one service to another is HTTP2 had no problem. but after deployed to kubernets with istio(with sidecar),  in the wireshark, the protocol was changed to HTTP1.1 for the request msg.  we should expect http2 instead of http1.1.

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istio 1.4.6

**How was Istio installed?**
installed with Helm install.

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by mandarjog** [comment]
@xzhao1 can you add config dumps from the client and the server?
1. Is mtls enabled?
2. Are the service ports named correctly? For example are they named `http2-*` or `grpc-*` ?

**Comment by xzhao1** [comment]
Hello Sir, 

would you please let me know which config I need to dump?  or which command to do the dump?
since I am new to istio.

Thanks,
Eric.

**Comment by xzhao1** [comment]
can anyone answser my question?
egress:

  - name: http2
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  - name: tls
    port: 15443
    protocol: TCP
    targetPort: 15443


ingress:
 ports:
  - name: status-port
    nodePort: 32737
    port: 15020
    protocol: TCP
    targetPort: 15020
  - name: http2
    nodePort: 31380
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    nodePort: 31624
    port: 443
    protocol: TCP
    targetPort: 443

**Comment by travisgroth** [comment]
@xzhao1 does your request Host/Authority header match the Istio service name?  For example, if the target Kubernetes service is `foo.default.svc.cluster.local`, is your client sending a request with `foo.default.svc.cluster.local` as the target hostname?

**Comment by xzhao1** [comment]
@travisgroth 

this request is sending to an external application running on a linux server(10.76.83.41:8082) from a kubernetes pod.

The following is the content:

Hypertext Transfer Protocol
    PUT /endpoints/nnrf-nfm/v1/nf-instances/60a3b25a-3bd7-4082-8a83-42acb8cb1ff9 HTTP/1.1\r\n
    host: 10.76.83.41:8082\r\n
    accept: application/json\r\n
    user-agent: Jersey/2.29 (OkHttpClient)\r\n
    content-type: application/json\r\n
    content-length: 486\r\n
    accept-encoding: gzip\r\n
    x-forwarded-proto: http\r\n
    x-request-id: 42a11aa2-2ee7-407d-ba9c-0ecc354bd99d\r\n
    x-istio-attributes: CjAKGGRlc3RpbmF0aW9uLnNlcnZpY2UubmFtZRIUEhJQYXNzdGhyb3VnaENsdXN0ZXIKPgoKc291cmNlLnVpZBIwEi5rdWJlcm5ldGVzOi8vc3BzLWNoYXJnaW5nLTViOTVmZjRiZjQtajdmZjQuc3Bz\r\n
    x-envoy-expected-rq-timeout-ms: 15000\r\n
    x-b3-traceid: 0ee96243af254236e987351032acfbfb\r\n
    x-b3-spanid: e987351032acfbfb\r\n
    x-b3-sampled: 0\r\n
    \r\n
    [Full request URI: http://10.76.83.41:8082/endpoints/nnrf-nfm/v1/nf-instances/60a3b25a-3bd7-4082-8a83-42acb8cb1ff9]
    [HTTP request 1/2]
    [Response in frame: 1068]
    [Next request in frame: 1812]
    File Data: 486 bytes

**Comment by howardjohn** [comment]
@xzhao1 please add config dump and access logs (https://github.com/istio/istio/wiki/Troubleshooting-Istio). May be releated to https://github.com/istio/istio/pull/24712

**Comment by howardjohn** [comment]
Closing as we do not have the required info
