### ISSUE TITLE
IstioIngress should supply default values for Content-Security-Policy, X-Content-Type-Options, and X-XSS-Protection headers

### ISSUE THREAD

**Issue by esnible** [istio/istio#24012]
I recently ran a 3rd party scanner on Bookinfo Productpage and got warnings about lack of Content-Security-Policy, X-Content-Type-Options, and X-XSS-Protection headers.

I noticed an SAP blogger suggested these and a few other headers in https://blogs.sap.com/2019/02/11/kubernetes-security-secure-by-default-headers-with-envoy-and-istio/ and proposed using EnvoyFilter to add them.

Would it make sense to configure these as defaults for Istio installs?

cc @GregHanson

**Comment by howardjohn** [comment]
I do not think we should do this. This is far too opinionated. We provide APIs that expose knobs to tweak response headers.

**Comment by esnible** [comment]
Would it make sense to provide this as a _sample_?

**Comment by howardjohn** [comment]
Seems reasonable if you want to add one

**Comment by howardjohn** [comment]
Closing as there is no plans to add these. Users can add them  through existing APIs if they want
