### ISSUE TITLE
`ServiceEntry` to be applied to only 1 service

### ISSUE THREAD

**Issue by nerusnayleinad** [istio/istio#24019]
Honestly, I am not sure if this is possible already, but there is this scenario, that I seem to not be able to go through.

So, we have a cluster with Istio, and I need one of the services to have certain restrictions within the mesh as well, and to talk to one external endpoint. Through `Sidecar` object, I should be able to set the restrictions internally, but I don't know how to restrict to one external endpoint.

I can set the external endpoint in the Sidecar object as well, but I have to create a `ServiceEntry` anyways, in which case all the services can talk to that external endpoint.

It seems that what I need is to set a `ServiceEntry` for one specific service, but this is not possible. Is there any other way to achieve this?

I tried through `AuthorizationPolicy`, as someone suggested in SO, but it didn't work. Actually I was not able to get neither **ALLOW** nor **DENY** to work under no circumstances. I am wondering if to make `AuthorizationPolicy` to work, if I need to enable any admission controller. Doesn't seem to be the case.

**Comment by howardjohn** [comment]
There is an `exportTo` field that can restrict this to just pods in the same namespace. We are considering extending this to finer grain as you requested here as well.However, for security purposes if you need to block external traffic for security purposes you may want to use https://preliminary.istio.io/docs/tasks/traffic-management/egress/egress-control/ - this is the only secure way to do this

cc @nrjpoddar @rshriram use case for exportTo ^

**Comment by nerusnayleinad** [comment]
That will work for us. thank you. We can put that one service in a difference namespace.

Would be nice though to have a field to restrict the `ServiceEntry` to a specific workload.

**Comment by howardjohn** [comment]
Closing this as this has been addressed and longer term solution of finer grain exportTo is being tracked elsewhere. Thanks!

**Comment by maxforasteiro** [comment]
hey @howardjohn do you have a link to where I can follow-up the exportTo finer grain control? We have the exact same use case and although splitting in a different namespace is a possibility we would love to control this by application

**Comment by howardjohn** [comment]
You can do `exportTo=<namespacename>`, and import (via Sidecar.spec.egress.hosts) a specific service (`ns/hostname`). Those are the two controls really
