### ISSUE TITLE
Allow users to configure preStop per pod

### ISSUE THREAD

**Issue by linsun** [istio/istio#24018]
**Describe the feature request**

In 1.6, we introduced a global config .global.proxy.lifecycle where user can specify preStop info in there.  However this is not per pod and doesn't help users who need to configure this on a per pod basis and who can't use manual sidecar injector.   We also introduced proxy.istio.io/ProxyConfig support in 1.6, which allows users to tweet these proxy configs per pod https://preliminary.istio.io/docs/reference/config/istio.mesh.v1alpha1/#ProxyConfig, however lifecycle preStop isn't part of it.  In summary, there is no easy way to configure this per pod with automatic sidecar injector.

cc @costinm @howardjohn @nrjpoddar @irisdingbj please correct me if I missed something.

**Describe alternatives you've considered**

**Additional context**

**Comment by howardjohn** [comment]
Just wondering, why do you want it per pod?

**Comment by linsun** [comment]
We had a user using stateful set and wants to configure it specifically for that stateful set else envoy shutdown too early and stateful set can't gracefully shutdown.

**Comment by udaymadu** [comment]
Is any one assigned to it to work on as dont see any activity since May 21.

@istio-policy-bot

**Comment by udaymadu** [comment]
Can we make this issues has priority and can get it started.

**Comment by udaymadu** [comment]
@howardjohn Is there a timeline for when this will get looked at?
Please pass it right member if you are not the correct one .

**Comment by udaymadu** [comment]
Is anyone actively working on it.

**Comment by udaymadu** [comment]
can you reopen it as we haven't seen solution yet.

**Comment by udaymadu** [comment]
lifecycle/needs-escalation

**Comment by howardjohn** [comment]
This is already fixed, just need to document it. We have another issue tracking that, see design in https://docs.google.com/document/d/1Rmp9B3DDypgMCau-YAqidx_r3qvKLZj6jUX-t22zj84/edit?ts=5fa915aa#heading=h.xw1gqgyqs5b

**Comment by linsun** [comment]
Hi @howardjohn could you explain how this can be used at pod level for 1.8?  I don't see anything related to stop or prestop in https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#ProxyConfig.

**Comment by howardjohn** [comment]
https://github.com/istio/istio/blob/cf657ff502e296ab9638248456e3ad7af2715e2e/pkg/kube/inject/testdata/inject/proxy-override.yaml#L43 is an example. you just define an `istio-proxy` container in the pod

**Comment by linsun** [comment]
I see, that is overwritten the istio-proxy container.  I had thought users could use annotation for this without providing istio-proxy container along with their app container.

**Comment by howardjohn** [comment]
@linsun the new injector allows overriding arbitrary fields in the istio-proxy container. It is not overwritting it - its merged with the injected container. For example,  a minimal one:
```yaml
      containers:
        - name: hello
          image: "fake.docker.io/google-samples/hello-go-gke:1.0"
        - name: istio-proxy
          image: auto
          lifecycle:
            preStop:
              exec:
                command: ["sleep", "10"]
```

**Comment by linsun** [comment]
Very cool!  Saw it in the proxy-override.yaml.injected now.  Thanks @howardjohn - I agree this can be closed. :)

**Comment by aayush-harwani** [comment]
is it possible to achieve it via annotations ?
