### ISSUE TITLE
Confusing istiod.istio-system port name

### ISSUE THREAD

**Issue by esnible** [istio/istio#24010]
Using master.

The docs at https://preliminary.istio.io/docs/ops/deployment/requirements/#ports-used-by-istio say 

```
15010 | GRPC | Istiod | XDS and CA services (plaintext)
15012 | GRPC | Istiod | XDS and CA services (TLS)
```

yet `kubectl -n istio-system get svc istiod -o jsonpath="{.spec.ports}"` shows port 15012 has the name `https-dns`.  I don't think DNS is in the picture here.

**Comment by howardjohn** [comment]
Its a DNS based cert instead of SPIFFE. Agreed it should jst be called `https` though or something

**Comment by howardjohn** [comment]
we used to have `https-spiffe` I think so it made more sense then
