### ISSUE TITLE
TestReachability test flakes

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#24028]
https://prow.istio.io/view/gcs/istio-prow/logs/integ-distroless-k8s-tests_istio_postsubmit/1258
https://prow.istio.io/view/gcs/istio-prow/logs/integ-distroless-k8s-tests_istio_postsubmit/1259

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/24119/integ-security-k8s-tests_istio/13487

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/24121/integ-security-k8s-tests_istio/13493

This used to be stable I think

**Comment by incfly** [comment]
use one of the logs as an example, https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/24119/integ-security-k8s-tests_istio/13487/build-log.txt

All the failures are in a pattern

`a or b -> headless serivce`, expected fail, got success.

This is introduced in @hzxuzhonghu recent fix about headless, https://github.com/istio/istio/pull/21987/files#diff-83466b7faf0989f35faa6d8af2ff20e8R114

The logic seems reasonable though: if you don't set the transport socket matches for headless service, plus those service enabled mTLS (based on the config), we should expect failure. It's very weird that this is flaky rather than fail or success all the time...

It could be some Pilot changes that's not deterministic, or the config push delay.

@hzxuzhonghu would you mind taking a look?

**Comment by howardjohn** [comment]
This was backported to 1.6, which seems very unsafe given the above. I suggest we revert it until we can track this down

**Comment by hzxuzhonghu** [comment]
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/24228/integ-security-k8s-tests_istio/13644

**Comment by hzxuzhonghu** [comment]
There are three kinds of failed cases under `beta-mtls-partial-automtls`:
1. a--> headless 
2. b->headless
3. naked-->others

And as @incfly pointed, all cases are failed ` expected fail, got success`, so  definitely the  `PeerAuthentication` does not sync to the proxies when testing.

**Comment by hzxuzhonghu** [comment]
Failures after reverted

https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/24234/integ-distroless-k8s-tests_istio/6668

**Comment by howardjohn** [comment]
That failure looks different though I think? Still concerning though..

**Comment by hzxuzhonghu** [comment]
Newly found: https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/24225/integ-distroless-k8s-tests_istio/6759

**Comment by incfly** [comment]
@howardjohn I used this [script](https://gist.githubusercontent.com/incfly/8e79f86efd3fc2989e7c0cda3f36796c/raw/233750d3d44904ce8953d7e3478a730ca4eabec6/prow-checker.py) to check the flakes, as you mentioned the past runs are not avaiable in testgrid.

I found, all failures happen on distroless suite, and the security post submit does not have this issue at any time, (before or after zhonghu's PR)

I attached the result of both distroless and non distro normal security postsubmit test suite in the gist,
https://gist.github.com/incfly/8e79f86efd3fc2989e7c0cda3f36796c

**Comment by incfly** [comment]
Seems like it could be policies enforcement indeed went flaky as @hzxuzhonghu mentioned, server side not configure mtls. however, i'm not famliar with distro myself and think of any reason that can contribute to this. @howardjohn any ideas?

**Comment by howardjohn** [comment]
I suspect the distroless vs non distroless is not actually about debian vs distroless, but rather the fact that security tests run a bunch of tests before TestReachability and distroless just runs TestReachability. Just a guess though

**Comment by howardjohn** [comment]
example non distroless failure: https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/24517/integ-security-k8s-tests_istio/14019/build-log.txt

**Comment by howardjohn** [comment]
I am guessing this is actually about the config applying rather than TLS code. I bet we somehow get into a state where config isn't deleted properly or applied or something

**Comment by incfly** [comment]
`Config apply` you mean the test code that coordinating the test sequence,
not istiod part, right?

**Comment by howardjohn** [comment]
I mean this part: https://github.com/istio/istio/blob/8e617f715ae8886ebeb2abac041ed2b9c736cb0b/tests/integration/security/util/reachability/context.go#L142-L149. I think its somehow getting broken here. I don't know why or have much evidence yet... looking into it. But yes the test code

**Comment by howardjohn** [comment]
```
2020-06-22T20:12:03.057038Z     info    tf      Deleting YAML file: /logs/artifacts/security-be23d9358cae44b78511b7/_suite_context/env-kube-165446167/istio-kube-accessor-201350241/accessor_785875625
2020-06-22T20:12:03.057054Z     info    tf      Applying YAML file: /logs/artifacts/security-be23d9358cae44b78511b7/_suite_context/env-kube-165446167/istio-kube-accessor-201350241/accessor_873699828
2020-06-22T20:12:03.070963Z     debug   tf      Applied config: ns: reachability-1-26863
apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "default"
  annotations:
    test-suite: "automtls-partial-dr-disable"
spec:
  mtls:
    mode: STRICT
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "multiversion-route"
  annotations:
    test-suite: "automtls-partial-dr-disable"
spec:
  hosts:
  - "multiversion"
  http:
  - name: "vistio-route"
    match:
    - uri:
        prefix: "/vistio"
    route:
    - destination:
        host: "multiversion"
        subset: "vistio"
  - name: "legacy-by-default"
    route:
    - destination:
        host: "multiversion"
        subset: "vlegacy"
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: "multiversion"
  annotations:
    test-suite: "automtls-partial-dr-disable"
spec:
  host: "multiversion"
  subsets:
  - name: "vistio"
    labels:
      version: "vistio"
    trafficPolicy:
      tls:
        mode: DISABLE
  - name: "vlegacy"
    labels:
      version: "vlegacy"
    trafficPolicy:
      tls:
        mode: DISABLE
  trafficPolicy:
    tls:
      mode: DISABLE


    TestReachability/automtls-partial-sidecar-dr-disable-1: context.go:152: [automtls-partial-sidecar-dr-disable] [2020-06-22 20:12:03.071006773 +0000 UTC m=+49.113155939] Wait for config propagate to endpoints...
2020-06-22T20:12:03.083991Z     debug   tf      Deleted config: ns: reachability-1-26863
apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "default"
  annotations:
    test-suite: "automtls-partial-dr-disable"
spec:
  mtls:
    mode: STRICT
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "multiversion-route"
  annotations:
    test-suite: "automtls-partial-dr-disable"
spec:
  hosts:
  - "multiversion"
  http:
  - name: "vistio-route"
    match:
    - uri:
        prefix: "/vistio"
    route:
    - destination:
        host: "multiversion"
        subset: "vistio"
  - name: "legacy-by-default"
    route:
    - destination:
        host: "multiversion"
        subset: "vlegacy"
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: "multiversion"
  annotations:
    test-suite: "automtls-partial-dr-disable"
spec:
  host: "multiversion"
  subsets:
  - name: "vistio"
    labels:
      version: "vistio"
    trafficPolicy:
      tls:
        mode: DISABLE
  - name: "vlegacy"
    labels:
      version: "vlegacy"
    trafficPolicy:
      tls:
        mode: DISABLE
  trafficPolicy:
    tls:
      mode: DISABLE
```

from https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/24873/integ-distroless-k8s-tests_istio/7702/build-log.txt

Look at the logs.. they are out of order. We should delete and then apply, but in reality it ends up applying *then* deleting

**Comment by howardjohn** [comment]
Yeah the cleanup happens async when RunParallel is used. I am pretty sure this is the problem. Will see how easy it is to fix

**Comment by stevenctl** [comment]
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/25378/integ-distroless-k8s-tests_istio/8978

Don't think its the same cause as above, fails waiting for istio-proxy for echo. Possibly introduced in #25096

**Comment by knight42** [comment]
This test is still flaky https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/26011/integ-distroless-k8s-tests_istio/10683

**Comment by hzxuzhonghu** [comment]
https://github.com/istio/istio/pull/26061

**Comment by incfly** [comment]
https://testgrid.k8s.io/istio_istio#integ-security-k8s-tests_istio&include-filter-by-regex=TestReachability
seems stable.
