### ISSUE TITLE
xds stable identifiers: reduce node metadata usage

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#24024]
As part of https://docs.google.com/document/d/1Is8sW322wC5vzjWJaqYJSnY_frSAYXRFl0xZaS0Q8tU/edit#, we will create stable identifiers for XDS objects. This means source dependent changes will need to be explicitly declared; currently we just read whatever we want from node metadata.

This issue aims to track current usage and analyze where we can cleanup and where we will need to encode as part of the identifier

https://github.com/istio/istio/blob/c388beea34eceee03c8561454cb26d327f563f82/pilot/pkg/model/context.go#L367 for reference

---

* ProxyConfig

This literally sends the entire proxy config over. This was the biggest move in the opposite direction. Currently used for gateway topology and tracing; more to come in the future most likely.

While this is a complex field, the vast majority of proxies are likely to ahve the same options here. We likely can have references to the proxy config rathe than encoding directly in the identifier

* IstioVersion

Very commonly used for capability detection. Also used for EnvoyFilter matching.

* Labels

Very commonly used to match configuration. Similar to proxy config in that we will likely need to have a reference as this is a complex type, but differs because this is generally unique per Deployment. Small enough to feasibly base64 encode?

* InstanceIPs

Determine IP to bind to, ipv4/6 support.
Used to lookup labels if not present in meta (this shouldn't happen now), as well as management ports.
Used to skip duplicate inbound/outbound listener for headless services
Used to find ServiceInstances by reverse lookup of pod

This seems pretty un-avoidable to include. Additionally, its going to be 1:1 with pods, which will destroy cache-ability

* ConfigNamespace, Namespace

We have both for legacy reasons: https://github.com/istio/istio/issues/24023.

Used extensively for config scoping. Easy to encode

* InterceptionMode, RouterMode

Impacts how listener are generated. Easy to encode.

* ServiceAccount, PodPorts

Used only for metadata based pod lookup fallback. SA is easy to encode, pod ports is less easy

* ClusterID, Network, RequestedNetworkView

Used extensively, especially for endpoints. Easy to encode

* ExchangeKeys, PlatformMetadata, InstanceName, WorkloadName, Owner, StatsInclusionPrefixes, StatsInclusionRegexps, StatsInclusionSuffixes, ExtraStatTags

not used by pilot

* TLSServerCertChain, TLSServerKey, TLSServerRootCert, TLSClientCertChain, TLSClientKey, TLSClientRootCert, IdleTimeout, PolicyCheck, PolicyCheckRetries, PolicyCheckBaseRetryWaitTime, PolicyCheckMaxRetryWaitTime, SdsBase, InsecurePath, MeshID

Minor config overrides

* SdsEnabled, HTTP10

feature flag

* Generator

feature flag/control client type. Easy to encode

* Raw

We copy literally the raw node metadat and use it for envoyfilter

**Comment by howardjohn** [comment]
Based on this, its seems problematic to cache based on stable identifiers, and it seems extremely hard to actually simply encode all of this information. While we can trim down the list a bit, there are still some major issues, namely labels, ip address, proxyconfig, and raw.

Some ideas:

---

We could have many things derived just from the ip address. This would remove:
* Namespace
* Labels
* SA
* Pod ports
Which would be looked up from the pod based on IP address. This won't work with VMs though, and also re-introduces a major race condition in pilot. This doesn't seem viable as a result.

**Comment by howardjohn** [comment]
cc @costinm @louiscryan

**Comment by costinm** [comment]
Based on our chat: 

https://github.com/istio/istio/blob/f0297eeb810163d56744713e02164e23b232c683/pilot/pkg/networking/core/v1alpha3/listener.go#L1087

We should identify all non-cacheable, pod specific entries - and evaluate if they can be 'patched' locally.

**Comment by costinm** [comment]
The other problem with labels is that in many cases pods get a lot of labels - from helm, etc - the full set of labels will break the hit-ratio for any cache and create update latencies.

However - we can easily identify (per namespace) a set of 'active' label keys, used in any config in that workspace. It is per NS because workload selectors work on namespace, and that's everything we need for the local overrides. 

Based on the sorted list of active labels - we can create a semi-stable identifier for the pods. If new configs are added that start using other labels - we'll need to re-generate the cache for that namespace, but that's fine - today we regenerate everything.

Based on the semi-stable label, we could populate a memcache or use groupcache (or some plugin - we can even store in k8s/etcd in a new 'istio-xds-cache' CRD).  Assuming we also implement the 'istio-master' - a high-priv Istio that handles the CA and k8s write, with other revisions handling 
connections - we can have very efficient XDS generation and populating the cache, and then push to cache keys ( via 'api-style XDS') to all connection-handling Istiod instances.

**Comment by costinm** [comment]
Yes, absolutely - full XDS response is clearly not viable IMO. 

We should also assume that the common case is using the server-defined settings without client overrides.

We may need to cache not only XDS, but also some 'synthetic' data - like the set of 'active' labels per namespace, set of active labels that impact client-side overrides, etc. 
The 'synthetic' data might also be useful for debug/analyze/other tools.

**Comment by costinm** [comment]
We should also not think of this as simply a 'cache' ( i.e. non-durable ). While the design should work with memcache or in-memory groupcache - i.e. tolerate loss - it should also work with durable storage, like using some internal CRDs that store pre-generated XDS fragments and synthetic metadata.  This will allow 'central cluster' to fallback to low-privilege local istiod, and better handle restarts. Will also allow the translation to be driven off-line ( CI/CD, etc ), further reducing Istiod footprint.

**Comment by howardjohn** [comment]
Also I think we need to decouple the pilot metadata from the proxy metadata. Currently they share a struct. Pilot's should be a subset though of just what it uses. That way we can add more metadata for wasm or local purposes without making it freely available in pilot code gen. We can of course add it to pilot metadata later, but it makes it clear what should and shouldn't be used for gen and we can be more explicit
