### ISSUE TITLE
Backoff on pilot debouncing

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#24021]
Currently pilot debounces every 100ms. This has a few problems

* There is a small, but potentially impactful delay for applying a single object
* Even tight loops of `kubectl apply` may be have greater than 100ms delays. This means a `kubectl apply` of a large file can cause massive amounts of pushes. Similar applies to large scale up events on cluster

I feel like we can solve both of these by having dynamic debounce durations. For example:
* Config is applied -> push immediately
* Config is applied again within Xs -> debounce for 100ms 
* Config is applied again within Xs -> debounce for 200ms 
* Config is applied again within Xs -> debounce for 400ms 
* Config is applied again within Xs -> debounce for 800ms 

This way, we still have fast pushes for a few changes, but slowly back off. Ultimately, longer debouncing times may actually lead to faster pushes in the end, as the load may increase from too many concurrent pushes and slow everything down anyways.

**Comment by howardjohn** [comment]
https://github.com/istio/istio/issues/20123 would make this super easy to test to see what settings provide optimal performance

**Comment by jronak** [comment]
I would like to work on this issue, if no one is actively working on it

**Comment by ramaraochavali** [comment]
@jronak https://github.com/istio/istio/pull/24230 - There is an active PR. We put it on hold because we want to have the perf test built for this to validate

**Comment by howardjohn** [comment]
Related discussion in https://github.com/istio/istio/issues/25685
