### ISSUE TITLE
crd.ConvertObject is very inefficient

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#24020]
https://github.com/istio/istio/blob/16043a07a51cd58ddd94b8cad32bb266968ecf72/pilot/pkg/config/kube/crd/conversion.go#L79

We convert from a `map` -> yaml -> interface -> json -> proto.Message.

We could instead just go map -> json -> proto.message I think

**Comment by adiprerepa** [comment]
Should this be closed?

**Comment by howardjohn** [comment]
Fixed by #24511 and #24032
