### ISSUE TITLE
used istio1.5.1,but no mixer 

### ISSUE THREAD

**Issue by liyin37** [istio/istio#24034]
run command:
 istioctl manifest apply --set profile=demo 
then use sidecar ，but in kiali，there are not Data of service traffic
how to enable mixer or how to do this ?

**Comment by mandarjog** [comment]
1.5.1 does not need or use mixer for grafana and kiali to work.
There must be something else wrong.

**Comment by douglas-reid** [comment]
I feel like this issue is better handled in [user forums](discuss.istio.io) or in slack. Closing this issue now.
