### ISSUE TITLE
Lost access to .Release.name when using operator

### ISSUE THREAD

**Issue by tmshort** [istio/istio#24048]
When using helm and the "legacy" charts, the documentation always specified that the release value should be "istio". However, release could be any value, and would permit a relatively long string and could be used by deployers to indicate a specific configuration or deployment version. This release label can be seen easily via `kubectl get <object> -n <namespace> -L release`.

With 1.6, this option was taken away, and it defaults to "istio" in the operator. The .Release.Name is still in the charts, but the operator code sets it to "istio" without any way to specify it otherwise:

https://github.com/istio/istio/blob/5908abe46aba6ff7e0487f59b0efcf238bcd7848/operator/pkg/helm/helm.go#L105,L109

While this functionality has been partially restored via the `--set revision=abcd` option to istioctl; that value is used as part of the K8S API names, and is limited in what the value can contain.

**Expected behavior**

"release" label is set to something other than "istio"
`kubectl get pods -n istio-system -L release`

**Steps to reproduce the bug**

Deploy istio 1.5 or earlier as described below with the helm release parameter set to something other than "istio".
Use `kubectl get pods -n istio-system -L release` to see the release label.
With 1.6, there is no way to specify anything, and it defaults to "istio".

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

Any version of istio 1.5 or ealier.
Any version of supported kubernetes
Any version of helm (although we use 3)

**How was Istio installed?**
Via helm 3 (although helm 2 can be used with the right option for specifying release)

```
RELEASE=istio-1.5.2-special-sauce-1.1
helm template "$RELEASE" istio-init --values=$VALUES | kubectl apply -f -
helm template "$RELEASE" istio --values=$VALUES | kubectl apply -f -
```

**Environment where bug was observed (cloud vendor, OS, etc)**

Private kubernetes cluster v1.17

**Comment by tmshort** [comment]
This is also an issue with the 1.5 operator, but the legacy helm charts were still available there. The legacy helm charts are no longer available in 1.6.

**Comment by howardjohn** [comment]
This makes sense but I am wondering what the actual use case for this is? Why do you need it to be labelled differently?

**Comment by tmshort** [comment]
So we can identify releases of our own istio deployments. We might deploy istio 1.5.4, but have incremental improvements in the code deploying istio or with istio.

**Comment by tmshort** [comment]
This is different, albeit similar, to the canary deployments (i.e. revision), but we might want to override an existing deployment, and know it's been updated, rather than being deployed next to it.
