### ISSUE TITLE
kiali shows requests (with 4xx errors) from istio-ingressgateway to productpage deployment (not SVC!) on EKS

### ISSUE THREAD

**Issue by Cajga** [istio/istio#24042]
**Bug description**

**Expected behavior**
Bookinfo demo from "getting started" works without bad requests on EKS.

**Steps to reproduce the bug**
* create and EKS cluster
* setup your kubectl properly
* curl -L https://istio.io/downloadIstio | sh -
* cd istio-1.6.0
* ./bin/istioctl manifest apply --set profile=demo
* kubectl label namespace default istio-injection=enabled
* kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml
* kubectl apply -f samples/bookinfo/networking/bookinfo-gateway.yaml
* generate traffic with a browser to your AWS CLB
* istioctl dashboard kiali
* open the link in your browser, click on graph and enable the default and istio-system namespaces to see the kiali graph (see example screenshots at the end of the report)

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
$ ./bin/istioctl version --remote
client version: 1.6.0
control plane version: 1.6.0
data plane version: 1.6.0 (9 proxies)
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

```

**How was Istio installed?**
```
$ curl -L https://istio.io/downloadIstio | sh -
$ cd istio-1.6.0
$ ./bin/istioctl manifest apply --set profile=demo
```

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS EKS latest

![kiali_issue_full](https://user-images.githubusercontent.com/781079/82673539-54a38a80-9c42-11ea-92ea-cb74ffb4e618.png)
![kiali_issue_drilled](https://user-images.githubusercontent.com/781079/82673546-5705e480-9c42-11ea-8e96-56f2ff38472b.png)

[k8s_resources_yaml.txt](https://github.com/istio/istio/files/4668306/k8s_resources_yaml.txt)
[istio-system_secrets.txt](https://github.com/istio/istio/files/4668307/istio-system_secrets.txt)
[istio-system_pilot_discovery.log](https://github.com/istio/istio/files/4668311/istio-system_pilot_discovery.log)
[istio-system_config_map_yaml.txt](https://github.com/istio/istio/files/4668312/istio-system_config_map_yaml.txt)
[istio_configuration_artifacts.txt](https://github.com/istio/istio/files/4668313/istio_configuration_artifacts.txt)

**Comment by mandarjog** [comment]
@ jshaughn please triage, probably telemetry issue.

**Comment by jshaughn** [comment]
@mandarjog That's unusual and not something I have seen before.  It would be good to see the Prometheus telemetry for this one, it would seem that there may be failed request time-series with destination_workload set but no destination_service_name.  Not sure.

@Cajga Does this failed traffic go away quickly from the graph, or is the request count going up?

**Comment by Cajga** [comment]
@jshaughn the bad requests (4xx) taking up about 14-15% of the traffic when I am reloading the page (ctrl+F5) in the browser according to kiali. But, the site is working well, no bad request in the network tab of the browser's debug mode (apart from favicon.ico which is not the problem here I guess)

![kiali_errors_included](https://user-images.githubusercontent.com/781079/82697255-da3a3100-9c68-11ea-91b8-a21e90db85f5.png)

**Comment by Cajga** [comment]
So, yes it was the favicon.ico...
I created an empty favicon.ico file under the static folder in the productpage container and extended the bookinfo virtualservice with the following config and it is all green now:
```
  - match:
    - uri:
        prefix: /favicon.ico
    rewrite:
      uri: /static/favicon.ico
    route:
    - destination:
        host: productpage
        port:
          number: 9080
```

So, in order to avoid new users (like me) panicing maybe you could make sure that the browser finds the favicon.ico in the bookinfo app/demo.

**Comment by jshaughn** [comment]
Wow, nice find @Cajga .  By the way, if you had clicked the problem edge and looked at the Hosts tab on the side-panel, I wonder if it would have given you a clue about the problem.  The good news here is it seems Kiali did alert you to an actual issue.

**Comment by Cajga** [comment]
This is what I see there (404 could be helpful but unknown is not really... having the uri would help a lot :) ):
![hosts](https://user-images.githubusercontent.com/781079/82700901-69e2de00-9c6f-11ea-96ad-b3ab3dfcac65.png)

Yes, Kiali did point out that there was a problem. Interestingly, I could not find these requests in jaeger (I must say that I did not find too much time and that was my first time seeing the tool :/)

**Comment by Cajga** [comment]
@jshaughn it would be nice if kiali could show the traffic going to a "no destination" object or something like this in the graph.
As mentioned, the bookinfo virtualservice does not have a matching uri for /favicon.ico. So, it did not have a destination at all. In case Kiali could point this out somehow, that would be awesome.

**Comment by jshaughn** [comment]
@Cajga the fact that the Host was "unknown" was sort of clue, I guess.  Perhaps we could add a hover or something in that situation.  Actually, did you check the Flags tab?  Maybe there was some indicator in there.   Kiali is limited somewhat by the telemetry provided by Istio, so I'm not sure if there is more we can do.  I'll think about it.  It's interesting that we have not seen this issue, but I also typicall deploy bookinfo with a script, maybe I'm bypassing the problem.  Maybe @mandarjog has an idea.

**Comment by mandarjog** [comment]
Where did the 404 come from? Did ingress respond with the 404 or did the application respond with 404?

Can you show access logs from ingress and product page?

**Comment by Cajga** [comment]
@jshaughn So you would need to generate the traffic from a browser in order to get the favicon.ico request. For example curl does not do it by default. Maybe this is the reason why you overlooked it till now?! Unfortunately flags also does not provide more info from the missing match in the virtual service:
![flags](https://user-images.githubusercontent.com/781079/82725731-3dff4100-9cdf-11ea-9c42-a4f9ced181c0.png)

@mandarjog The ingress responds with 404. Here are the logs (from two separate terminal) when I reproduce the 404:
```
 $ kubectl logs istio-ingressgateway-5d869f5bbf-rj4mm -n istio-system -f|grep favicon.ico
[2020-05-23T08:07:48.824Z] "GET /favicon.ico HTTP/1.1" 404 NR "-" "-" 0 0 0 - "10.10.210.84" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0" "259635c4-58be-9126-ba11-d353a26b043f" "ab8dbd410f5324e87b1f38addfdc1da2-730055530.eu-west-1.elb.amazonaws.com" "-" - - 10.10.202.119:8080 10.10.210.84:39368 - -

$ kubectl logs -l app=productpage -c istio-proxy -f|grep favicon.ico
```
And just to cross-check, here are the logs when I server an empty file from the productpage container (see above how I extended the bookinfo virtualservice with a rewrite and created an empty file in the productpage container ):
```
kubectl logs istio-ingressgateway-5d869f5bbf-rj4mm -n istio-system -f|grep favicon.ico
[2020-05-23T08:15:31.694Z] "GET /favicon.ico HTTP/1.1" 200 - "-" "-" 0 0 2 2 "10.10.210.84" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0" "ccd46a43-4fa1-983e-aada-15462059ed79" "ab8dbd410f5324e87b1f38addfdc1da2-730055530.eu-west-1.elb.amazonaws.com" "10.10.199.190:9080" outbound|9080||productpage.default.svc.cluster.local 10.10.202.119:37944 10.10.202.119:8080 10.10.210.84:39834 - -

kubectl logs -l app=productpage -c istio-proxy -f|grep favicon.ico
[2020-05-23T08:15:31.694Z] "GET /favicon.ico HTTP/1.1" 200 - "-" "-" 0 0 2 1 "10.10.210.84" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0" "ccd46a43-4fa1-983e-aada-15462059ed79" "ab8dbd410f5324e87b1f38addfdc1da2-730055530.eu-west-1.elb.amazonaws.com" "127.0.0.1:9080" inbound|9080|http|productpage.default.svc.cluster.local 127.0.0.1:50600 10.10.199.190:9080 10.10.210.84:0 outbound_.9080_._.productpage.default.svc.cluster.local default
```

**Comment by mandarjog** [comment]
404 NR at ingress is indeed the correct behaviour.
So from raw telemetry side I think everything looks good. The question for kiali is that why is the red arrow painted from ingress to productpage when the request was not mapped to the product page?

**Comment by mandarjog** [comment]
@Cajga the NR is flags tells you that this was not generated by the back end, but it is a proxy generated error.

**Comment by jshaughn** [comment]
@Cajga If you hover over the Flag you get a string description,  In this case the tooltip would have said, "'No route configured (check DestinationRule or VirtualService)".   I'm not sure that's really helpful but it's just an FYI for using the Flags tab in the future.

@mandarjog The config for for bookinfo-gateway uses ingressgateway and, iirc, routes all hosts to productpage.  @Cajga hasn't posted the time-series but I expect that it is actually reporter=destination and has destination_service_name set=productpage, destination_app=productpage, destination_workload=productpage-v1.

**Comment by Cajga** [comment]
@jshaughn, thanks for the hint about the tooltip when I hover over the NR string in the flags tab. That really explains what NR means :)
FYI: you are correct, the gateway has host  "*" as well as the virtual server.  
In case you need it and tell me how can I get you the "time-series" data then I am happy to help (I can reproduce the issue for few more days).

**Comment by jshaughn** [comment]
@Cajga The Kiali graph drives off of the metrics collected in the Prometheus DB.  Prometheus stores a bunch of time-series data.  To see the raw data you can use the Prometheus UI:

`> istioctl dashboard prometheus`

From there enter the following query:

`istio_requests_total{source_workload="istio-ingressgateway",response_code="404"}`

Capture and post the results and @mandarjog and I can take a look from both the Istio and Kiali perspectives.

**Comment by Cajga** [comment]
@jshaughn @mandarjog here we are:

```
istio_requests_total{connection_security_policy="unknown",destination_app="productpage",destination_canonical_revision="v1",destination_canonical_service="productpage",destination_principal="unknown",destination_service="unknown",destination_service_name="unknown",destination_service_namespace="default",destination_version="v1",destination_workload="productpage-v1",destination_workload_namespace="default",instance="10.10.223.45:15090",job="envoy-stats",namespace="istio-system",pod_name="istio-ingressgateway-5d869f5bbf-wsdhs",reporter="source",request_protocol="http",response_code="404",response_flags="NR",source_app="istio-ingressgateway",source_canonical_revision="latest",source_canonical_service="istio-ingressgateway",source_principal="unknown",source_version="unknown",source_workload="istio-ingressgateway",source_workload_namespace="istio-system"} | 17
-- | --
istio_requests_total{connection_security_policy="unknown",destination_app="unknown",destination_canonical_revision="latest",destination_canonical_service="unknown",destination_principal="unknown",destination_service="unknown",destination_service_name="unknown",destination_service_namespace="unknown",destination_version="unknown",destination_workload="unknown",destination_workload_namespace="unknown",instance="10.10.223.45:15090",job="envoy-stats",namespace="istio-system",pod_name="istio-ingressgateway-5d869f5bbf-wsdhs",reporter="source",request_protocol="http",response_code="404",response_flags="NR",source_app="istio-ingressgateway",source_canonical_revision="latest",source_canonical_service="istio-ingressgateway",source_principal="unknown",source_version="unknown",source_workload="istio-ingressgateway",source_workload_namespace="istio-system"} | 12
```

**Comment by jshaughn** [comment]
@Cajga OK, it's pretty much as I expected  although I was confused about the reporter=destination.  reporter=source makes more sense because as @mandarjog mentioned earlier this is a failure on the sending side.   Kiali is showing what we'd expect given the telemetry.  @mandarjog asked why we show the red edge to productpage but the telemetry answers that question, because `destination_version="v1",destination_workload="productpage-v1",destination_workload_namespace="default"`  are set, even though it's a failure on the client side.  I'm not sure that's wrong.

There is also traffic from ingress to uknown with a 404 response.  That looks like bad telemetry and Kiali filtered it out.

So I'd say there isn't really an issue here in Kiali.  I'll let Mandar decide if there is a problem with the generated telemetry.

**Comment by jshaughn** [comment]
@mandarjog @Cajga, anything else for this or perhaps it can be closed?
