### ISSUE TITLE
Fictitious Protocol (ionic://) not allowed in corsPolicy: allowOrigin

### ISSUE THREAD

**Issue by rbgran** [istio/istio#24041]
allowOrigin of corsPolicy not allowing a protocol of "ionic://" or "capacitor://" (probably any fictitious protocol)

`Error: UPGRADE FAILED: cannot patch "webappui-dev-virtualservice" with kind VirtualService: admission webhook "validation.istio.io" denied the request: configuration is invalid: port in CORS Allow Origin is not a number: //xxxxxx.com`

"ionic://" and "capacitor://" are "protocols" used by Ionic:  https://ionicframework.com/docs/troubleshooting/cors

**Expected behavior**
The  protocols to be allowed.  This seems like Istio is just being too strict on it's validation, as I don't believe the corsPolicy: allowOrigin is used server side.

**Steps to reproduce the bug**

Add an ionic://xxxxxx.com line to allowOrigin and upgrade a VirtualService.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

  Image:         docker.io/istio/pilot:1.5.4

% kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-10T21:53:51Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

helm version
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}

**How was Istio installed?**
kubectl --kubeconfig config apply --filename charts/istio/

**Environment where bug was observed (cloud vendor, OS, etc)**

AWS EKS

**Comment by jfspencerJN** [comment]
Ionic exposes the ability to set any string as the protocol. Being able to manually make exceptions on the protocol name would be helpful.

**Comment by esnible** [comment]
Can you add your webappui-dev-virtualservice .yaml (or something very similar to your actual) so that we can create a test case around it?

**Comment by rbgran** [comment]
@esnible 
Result of dumping the yaml, rather than the helm template.  

There was just a place holder previously of "jobnimbus.com" in the allowOrigin list. I replaced with ionic://jobnimbus.com.

kubectl get virtualservice webappui-dev-virtualservice -n dev -o yaml

`apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  creationTimestamp: "2020-04-21T01:39:52Z"
  generation: 16
  labels:
    app.kubernetes.io/instance: webappui-dev
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: webappui
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: webappui-0.1.0
  name: webappui-dev-virtualservice
  namespace: dev
  resourceVersion: "30116107"
  selfLink: /apis/networking.istio.io/v1beta1/namespaces/dev/virtualservices/webappui-dev-virtualservice
  uid: ff1d0926-8370-11ea-a6d0-02e2a4467c44
spec:
  gateways:
  - default/gateway
  hosts:
  - dev.jobnimbus.com
  http:
  - match:
    - uri:
        prefix: /files
    rewrite:
      uri: /api1/files
    route:
    - destination:
        host: nodeapi-dev.dev.svc.cluster.local
        port:
          number: 80
  - match:
    - uri:
        prefix: /auth/
    rewrite:
      uri: /api1/auth/
    route:
    - destination:
        host: nodeapi-dev.dev.svc.cluster.local
        port:
          number: 80
  - match:
    - uri:
        prefix: /intstats/
    rewrite:
      uri: /api1/intstats/
    route:
    - destination:
        host: nodeapi-dev.dev.svc.cluster.local
        port:
          number: 80
  - corsPolicy:
      allowCredentials: true
      allowHeaders:
      - DNT
      - X-CustomHeader
      - Keep-Alive
      - User-Agent
      - X-Requested-With
      - If-Modified-Since
      - Cache-Control
      - Content-Type
      - Authorization
      - accept
      - origin
      - referer
      - x-csrf-token
      - Range
      - JN-Version
      - JNAuth
      - jnVersion
      - manufacturer
      - device
      - platform
      - osversion
      - appversion
      - appbuild
      - jnconf.auth_cookie_name
      - jnconf.auth_share_cookie_name
      - csrf-token
      - withCredentials
      - content-transfer-encoding
      - custom-header-1
      - x-accept-content-transfer-encoding
      - x-accept-response-streaming
      - x-user-agent
      - grpc-timeout
      - x-grpc-web
      allowMethods:
      - GET
      - PUT
      - POST
      - OPTIONS
      - HEAD
      - DELETE
      - PATCH
      allowOrigin:
      - https://dev.jobnimbus.com
      - https://dev-web.jobnimbus.com
      - http://localhost:8080
      - http://localhost:4743
      - ionic://jobnimbus.com
      maxAge: 600s
    match:
    - uri:
        prefix: /
    route:
    - destination:
        host: webappui-dev.dev.svc.cluster.local
        port:
          number: 80
      headers:
        response:
          set:
            Cache-Control: max-age=86400
          `

**Comment by esnible** [comment]
Removing `networking` because the VirtualService with considered valid by _istioctl_ and by the webhook.  Manually adding `ionic://xxxxxxx.com` and `ionic://123456.com` also didn't trigger validation rejection.  (I tested with istioctl 1.5.4 and 1.6.0 and with webhook on Master.)

@rbgran What command are you typing that triggers the message?

**Comment by rbgran** [comment]
@esnible Haven't made the move to istioctl yet, is this a helm deprecation  issue?

+ helm upgrade --install webappui-dev -n dev -f webappui/values.yaml -f webappui/values-dev.yaml -f overwrite.yaml --set 'image.repository=821440580259.dkr.ecr.us-west-2.amazonaws.com/webappui-dev' --set 'image.tag=d53c1696967b6e596b987c28cafeda71bcd9235a' webappui
Error: UPGRADE FAILED: cannot patch "webappui-dev-virtualservice" with kind VirtualService: admission webhook "validation.istio.io" denied the request: configuration is invalid: port in CORS Allow Origin is not a number: //123456.com

**Comment by esnible** [comment]
It is not a _helm_ issue.  I tracked down why I can't reproduce it.  A change made in April, https://github.com/istio/istio/pull/22947 eliminated some CORS validation.  That's good, because the validation was only correct for http and https.  Unfortunately the old code is in 1.5.x.  (I am not sure why I couldn't see it with 1.5.4 istioctl.)

**Comment by angelovopsan** [comment]
@rbgran, does that mean that corsPolicy allowOrigin works for you on that version, meaning if I try to request with a custom Origin that is not one of the listed, you get the request denied?

**Comment by rbgran** [comment]
1.6.0 resolves this CORS issue.
