### ISSUE TITLE
istio1.6 install error!

### ISSUE THREAD

**Issue by ckgmg** [istio/istio#24056]
安装不成功

![image](https://user-images.githubusercontent.com/49260651/82724970-4fab0d80-9d0c-11ea-8aba-2d2858778bad.png)

**Comment by ckgmg** [comment]
[root@111 httpbin]# istioctl manifest apply --set profile=demo
Detected that your cluster does not support third party JWT authentication. Falling back to less secure first party JWT. See https://istio.io/docs/ops/best-practices/security/#configure-third-party-service-account-tokens for details.
? Istio core installed                                                                                                                                                                                       
? Istiod installed                                                                                                                                                                                           
? Egress gateways encountered an error: failed to wait for resource: resources not ready after 5m0s: timed out waiting for the conditiont/istio-system/istio-ingressgateway, Deployment/istio-system/istio...
Deployment/istio-system/istio-egressgateway                          
? Ingress gateways encountered an error: failed to wait for resource: resources not ready after 5m0s: timed out waiting for the conditiontio-tracing, Deployment/istio-system/prometheus                     
Deployment/istio-system/istio-ingressgateway                        
? Addons encountered an error: failed to wait for resource: resources not ready after 5m0s: timed out waiting for the condition                                                                              
Deployment/istio-system/istio-tracing
Deployment/istio-system/prometheus       
- Pruning removed resources                                                                                                                                                                                  Error: failed to apply manifests: errors occurred during operation
[root@itdtk8s01130131 httpbin]# kubectl get pod -n istio-system
NAME                                    READY   STATUS    RESTARTS   AGE
grafana-54b54568fc-l4wqk                1/1     Running   0          6m11s
istio-egressgateway-5cbb74b6d-jggmr     0/1     Running   0          6m12s
istio-ingressgateway-74cb7595bd-8nr7z   0/1     Running   0          6m12s
istio-tracing-9dd6c4f7c-bxjxd           0/1     Running   6          6m11s
istiod-6b8bf87986-d88hr                 1/1     Running   0          6m16s
kiali-d45468dc4-k8sqw                   1/1     Running   0          6m11s
prometheus-5c84c494dd-8lm94             1/2     Running   0          6m11s

**Comment by ckgmg** [comment]
> [root@111 httpbin]# istioctl manifest apply --set profile=demo
> Detected that your cluster does not support third party JWT authentication. Falling back to less secure first party JWT. See https://istio.io/docs/ops/best-practices/security/#configure-third-party-service-account-tokens for details.
> √ Istio core installed
> √ Istiod installed
> X Egress gateways encountered an error: failed to wait for resource: resources not ready after 5m0s: timed out waiting for the conditiont/istio-system/istio-ingressgateway, Deployment/istio-system/istio...
> Deployment/istio-system/istio-egressgateway
> X Ingress gateways encountered an error: failed to wait for resource: resources not ready after 5m0s: timed out waiting for the conditiontio-tracing, Deployment/istio-system/prometheus
> Deployment/istio-system/istio-ingressgateway
> X Addons encountered an error: failed to wait for resource: resources not ready after 5m0s: timed out waiting for the condition
> Deployment/istio-system/istio-tracing
> Deployment/istio-system/prometheus
> 
> * Pruning removed resources                                                                                                                                                                                  Error: failed to apply manifests: errors occurred during operation
>   [root@111 httpbin]# kubectl get pod -n istio-system
>   NAME                                    READY   STATUS    RESTARTS   AGE
>   grafana-54b54568fc-l4wqk                1/1     Running   0          6m11s
>   istio-egressgateway-5cbb74b6d-jggmr     0/1     Running   0          6m12s
>   istio-ingressgateway-74cb7595bd-8nr7z   0/1     Running   0          6m12s
>   istio-tracing-9dd6c4f7c-bxjxd           0/1     Running   6          6m11s
>   istiod-6b8bf87986-d88hr                 1/1     Running   0          6m16s
>   kiali-d45468dc4-k8sqw                   1/1     Running   0          6m11s
>   prometheus-5c84c494dd-8lm94             1/2     Running   0          6m11s

**Comment by erdun** [comment]
This is waiting for resources and timeout, not istio error, make sure your network can pull images from docker.io

**Comment by ckgmg** [comment]
![image](https://user-images.githubusercontent.com/49260651/82744182-897d2200-9da7-11ea-8eef-57b1c934e43b.png)
the images is download,The mistake is still the same

**Comment by ckgmg** [comment]
![image](https://user-images.githubusercontent.com/49260651/82744373-f98ca780-9da9-11ea-989b-36a5111d054d.png)

**Comment by tuongaz** [comment]
Check your cluster, does it has enough resource? RAM/CPU....

**Comment by ckgmg** [comment]
my cluster server is 64C 128G 4Tdisk,

**Comment by bianpengyuan** [comment]
`kubectl describe <your-istio-tracing-pod> -n istio-system` and the output should indicate why it crashloops.

**Comment by ckgmg** [comment]
![image](https://user-images.githubusercontent.com/49260651/83948045-56c63580-a84d-11ea-83d2-6218750cf632.png)
Does this prove that the installation is successful?

**Comment by howardjohn** [comment]
@ckgmg looks like its all running well now?

**Comment by howardjohn** [comment]
Closing as this looks solved. thanks

**Comment by oldthreefeng** [comment]
i meet same problem in istio-1.6.8. all images had  download to local. but when start prometheus,  it look s like no images in my machine , confused me..
