### ISSUE TITLE
Linear memory growth on istio-proxy

### ISSUE THREAD

**Issue by Stono** [istio/istio#24058]
**Bug description**
Hi, 
I'm observing a very linear memory growth on some apps `istio-proxy`, for example:

<img width="1655" alt="Screenshot 2020-05-23 at 14 10 52" src="https://user-images.githubusercontent.com/1486729/82731794-15883e80-9d01-11ea-9507-39d8e8f5b78e.png">

The drops are where the application was restarted due to a deployment.

This is something relatively new, so my gut is that it's related to `telemtryv2` metrics that build up, and never expire.  The reason I believe this is because the above application is hit by a cronjob every 30 minutes, which makes a lot of requests.  Another application, which is handles similar ops/sec, but no cronjob, does not exhibit these symptoms:

<img width="809" alt="Screenshot 2020-05-23 at 14 24 47" src="https://user-images.githubusercontent.com/1486729/82731838-5e3ff780-9d01-11ea-824b-8d15a0fc0b48.png">

The `prometheus` metrics for this application, are large, currently sitting at `10M` on an instance which has been running for 2 days.

[prometheus.tar.gz](https://github.com/istio/istio/files/4671829/prometheus.tar.gz)

In here you can see many `source_workload="cache-warm-1590071400"` style entries, from the cronjobs.

**Expected behavior**
I have raised a feature request for metrics expiry in telemetry v2 some time ago: https://github.com/istio/istio/issues/21377, if the growth is related to metrics, this would solve it.

Another workaround would be if i could annotate cronjobs in such a way the `workload` label could be overridden.

**Steps to reproduce the bug**
Create a workload that's hit by a cronjob frequently

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.5

**How was Istio installed?**
Helm

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

**Comment by Stono** [comment]
I've done more digging and there is a 100% correlation between the proxies which are growing linearly and cronjob metrics.

<img width="1629" alt="Screenshot 2020-05-23 at 14 36 03" src="https://user-images.githubusercontent.com/1486729/82732048-be836900-9d02-11ea-976f-d9d8f7e0264a.png">

This app has been running 22 days and its prometheus metrics are 60mb! 

[prometheus.tar.gz](https://github.com/istio/istio/files/4671839/prometheus.tar.gz)

**Comment by douglas-reid** [comment]
@Stono v2 Metrics Expiry is a P0 item for 1.7, and I think we have at least two identified paths towards solving it. @kyessenov and @bianpengyuan are the current owners of that work, and I'm assigning them to this issue (and the linked request) to that end.

**Comment by Stono** [comment]
Bah, 1.6 has only just been released, it's going to be some time before we're on 1.7 - and this is a bug we're facing right now.

As a temporary work around, is there any way (or could we add some way), perhaps with a pod annotation, to force the workload name?

The cardinality at the moment comes from the fact the workload name is coming from the pod name, so `some-cron-123456`, if i could do `sidecar.istio.io/workloadName: some-cron`, the problem would go away

**Comment by douglas-reid** [comment]
@Stono I agree that 1.7 is a long way away. We wanted to get to it for 1.6, with a backport for 1.5, but that just didn't happen unfortunately. I expect the solution to be fully cherry-picked back as soon as possible, but I don't have a firm timeline on when that will be.

As for the cron job, the WORKLOAD_NAME should be coming from the cron job name field and not the pod name. If that isn't the case, that's a bug that we definitely can address immediately. There are tests for the injection with cronjobs that demonstrate that behavior, but perhaps they aren't sufficient?

**Comment by Stono** [comment]
Something is certainly going wrong there then.  If you check those two metrics files you'll see the `app` is `cache-warm` but the `source_workload` is the cronjob

```
istio_response_bytes_bucket{response_code="200",reporter="destination",source_workload="cache-warm-1589500800",source_workload_namespace="forecourt-service",source_principal="spiffe://cluster.local/ns/forecourt-service/sa/default",source_app="cron-cache-warm",source_version="unknown",destination_workload="retailer-group-service",destination_workload_namespace="retailer-group-service",destination_principal="spiffe://cluster.local/ns/retailer-group-service/sa/default",destination_app="retailer-group-service",destination_version="unknown",destination_service="app.retailer-group-service.svc.cluster.local",destination_service_name="app",destination_service_namespace="retailer-group-service",request_protocol="http",response_flags="-",grpc_response_status="",connection_security_policy="mutual_tls",source_canonical_service="cache-warm-1589500800",destination_canonical_service="retailer-group-service",source_canonical_revision="latest",destination_canonical_revision="latest",le="1"} 0
```

**Comment by douglas-reid** [comment]
@Stono indeed. I would definitely classify that as a bug, as that is not the intended behavior. It will be a few days before I can look into this further, but I suspect that we can patch this behavior across all current versions.

If you have a chance, would you be ok posting the source config and the resulting config post-injection (with private details removed)?

**Comment by bianpengyuan** [comment]
Seems like there is no indication in pod spec about the suffix appended to the `cronjob` name (e.g. `1589500800` of `cache-warm-1589500800`). It is hard to derive cronjob name from job name in sidecar injector, which only knows about pod spec. We can probably heuristically remove the ten digits numeric string from the job name for deployment name, but apparently it is not reliable.

I think Mixer has the same behavior? It might be not exposed because of metric expiration. so we probably still need v2 metric expiration to solve this issue ultimately.

**Comment by Stono** [comment]
[cronjob.yaml.tar.gz](https://github.com/istio/istio/files/4673106/cronjob.yaml.tar.gz)

It's attached, my initial thoughts were the `canonical-name` is `service.istio.io/canonical-name: cron-beam-listings`, why can't that be used for `source_workload`?   Or why could we not add a `service.istio.io/canonical-workload-name`, which I can set in my cron spec?

Another idea in terms of inference, you could look for this block:
```
  ownerReferences:
  - apiVersion: batch/v1
    blockOwnerDeletion: true
    controller: true
    kind: Job
    name: beam-listings-1590305580
```

And consistently remove the ten `-1590305580` to get the CronJob name.

> I think Mixer has the same behavior? It might be not exposed because of metric expiration. so we probably still need v2 metric expiration to solve this issue ultimately. 

agreed, but we **need** a temporary workaround, this is a nasty issue.

**Comment by Stono** [comment]
OK I have a hacky work around, in the sidecar injection template you can replace:

```

**Comment by douglas-reid** [comment]
@Stono silly question, circling back: you sidecar injected the cronjob itself, correct? i'm trying to square your observations with the test at: https://github.com/istio/istio/blob/master/pkg/kube/inject/testdata/inject/cronjob.yaml.injected

**Comment by Stono** [comment]
Not sure what you mean @douglas-reid - it's injected like any other pod, with the injection webhook

**Comment by Stono** [comment]
Whilst we have a workaround for this, it's certainly a problem for anyone using Istio with Cronjobs so should be addressed

**Comment by homeles** [comment]
@Stono I tried the workaround you mentioned, and the `source_workload` looks good now, but I'm still getting the random job name in the `source_canonical_service` field, is there anything else you did to work around this?
```
source_workload=.=my-job-manager-manager ... source_canonical_service=.=my-job-manager-1596554160; 
```

**Comment by bdschaap** [comment]
I'm experiencing the same issue with source_canonical_service and have the same question.
