### ISSUE TITLE
istio-proxy sidecar does not work with custom clusterrole configured to particular policy

### ISSUE THREAD

**Issue by yaminisridaran** [istio/istio#24054]
**Bug description**
istio-proxy sidecar does not work with custom clusterrole configured to particular policy. istio-proxy works fine with cluster-admin (or) clusterrole with all api (*) and all resources (*) and all verbs(*) configured.

[ ] Security

**Expected behavior**
istio-proxy sidecar should work with clusterrole configured to a particular psp.

**Comment by yaminisridaran** [comment]
Works fine as expected.

**Comment by hzxuzhonghu** [comment]
It seems not a problem of istio

**Comment by yaminisridaran** [comment]
Found that it is not an issue with istio. I am closing this issue.
