### ISSUE TITLE
'istioctl verify-install' no longer does precheck

### ISSUE THREAD

**Issue by yangvipguang** [istio/istio#24068]
**Bug description**
Now I am trying to use Istio 1.6.0. But, When I run the command: istioctl verify-install . Then, It occurs some errors like this: Error: **could not load IstioOperator from cluster: the server could not find the requested resource.  Use --filename**。
**But Istio 1.5 is ok without error like above。**
![11111111110200525111256](https://user-images.githubusercontent.com/11416887/82774921-bea57500-9e78-11ea-924d-f90fdbc92fd1.png)

My K8S information：
Version: 1.16

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
It looks like you are using a new istioctl version but in your cluster you have an old Istio installed. We recommend using the same version of istioctl as the installed version

**Comment by yangvipguang** [comment]
@howardjohn  yes 。I have an  old version(1.4.6) istioinstalled in my cluster。 just now, I have uninstall the old one。But, i have the same issue。
<img width="671" alt="bbbb00525233609" src="https://user-images.githubusercontent.com/11416887/82826934-96516100-9ee0-11ea-96fd-80fa1c434131.png">

**Comment by esnible** [comment]
Starting with 1.6.0, `istioctl verify-install` looks for an IstioOperator resource.  If present, `verify-install` will verify the pods and services that IOP mandates are present.

(This new feature doesn't work without Istio 1.6.0-rc.0 or higher being installed.)

Before 1.6, `verify-install` always required a filename of an Istio deployment yaml.  For Istio 1.3.x, I installed Istio like this:

```
helm template --namespace istio-system install/kubernetes/helm/istio > ~/istio.yaml
kubectl apply -f ~/istio.yaml
istioctl verify-install -f ~/istio.yaml
```

**Comment by bdschaap** [comment]
I had previously used `istioctl verify-install` to verify compatibility with my current version of Kubernetes.   I received the same error message.  After a little research I discovered that the functionality was moved to `istioctl experimental precheck`.  I found it under [Commands](https://istio.io/docs/reference/commands/istioctl/#istioctl-experimental-precheck) in the docs but not in the [Istio 1.6 release notes](https://istio.io/news/releases/1.6.x/announcing-1.6/upgrade-notes/).  Here was the [commit](https://github.com/istio/istio/pull/23087).

**Comment by yangvipguang** [comment]
@bdschaap  yes，it worked ， thanks a lot。but i  am still  so confusing with this change . after all the command istioctl verify-install retains。

**Comment by tillig** [comment]
I just found this, too, in 1.6.4. [The docs on the command](https://github.com/istio/istio/blob/312ac4e0c37f0339c4f6b1608ee594d059ff7944/istioctl/pkg/install/verify.go#L256) say

> If you do not specify installation file it will perform pre-check for your cluster
> and report whether the cluster is ready for Istio installation.

However, without specifying a file [it goes straight into looking for the IstioOperator](https://github.com/istio/istio/blob/312ac4e0c37f0339c4f6b1608ee594d059ff7944/istioctl/pkg/install/verify.go#L278). Perhaps it's an issue of updating the command docs to point to the new precheck command?

**Comment by ericvn** [comment]
#26174 was my Issue from today. Sounds like we may need to update docs?
