### ISSUE TITLE
Prometheus not scraping app metrics (no mtls)

### ISSUE THREAD

**Issue by jotak** [istio/istio#24075]
**Bug description**

Following this FAQ entry ( https://istio.io/faq/metrics-and-logs/#prometheus-application-metrics ), I can't make prometheus scrape app metrics for non-mtls workloads (perhaps it works for mtls, I haven't tried).

FAQ says:

> The kubernetes-pods job collects application metrics from pods in environments without mutual TLS. The kubernetes-pods-istio-secure job collects metrics from application pods when mutual TLS is enabled for Istio.

But I need to do some tweaks on the prometheus configmap to make it work. Basically, the problem is that non-mtls pods are supposed to fall under `kubernetes-pods` job, but that job drops all pods with istio sidecar:

```yaml
  - source_labels: [__meta_kubernetes_pod_annotation_sidecar_istio_io_status]
    action: drop
    regex: (.+)
```

So it cannot work.

More than a year ago I did a PR to fix the exact same problem: https://github.com/istio/istio/pull/10492/files but these changes are not used now that istio is installed using `manifest apply`.

So I wonder, should I repeat the same PR, or am I doing something wrong?

PS: here's the annotations I used on my pods:

```yaml
  template:
    metadata:
      annotations:
#        prometheus.io/scheme: "http"
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
```

And here's the error when prometheus tries to scrape: `Get https://172.17.0.16:8080/metrics: http: server gave HTTP response to HTTPS client` (so, this is under `kubernetes-pods-istio-secure` job whereas I would expect the job `kubernetes-pods` to be used, as per the FAQ entry)

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

Istio 1.5.0 to 1.6.0, kube v1.16.2 (minikube)

**How was Istio installed?**

`istioctl manifest apply --set profile=demo` on minikube

**Comment by jotak** [comment]
PS: I can see in yaml files prom's configmap depends on `Values.prometheus.provisionPrometheusCert` and `Values.meshConfig.enablePrometheusMerge`.

So, I guess if I install istio with `enablePrometheusMerge` , that should work. If so, it should probably be mentioned in the FAQ entry, as it doesn't work out of the box as FAQ suggests.

**Comment by howardjohn** [comment]
For the merge option, this is documented here https://preliminary.istio.io/docs/ops/integrations/prometheus/#option-2-metrics-merging. I wasn't aware of the FAQ, I'll need to update that

**Comment by sachinsaju** [comment]
@jotak  In my case, I have given annotations in the deployment and service yamls and my application prometheus metrics is in http.Mtls is disabled.I expect the metrics targets to be in kubernetes-pods job but it is not showing there.Instead It is shown under kubernetes-pods-istio-secure job and the targets are down due to the same reason you have(http: server gave HTTP response to HTTPS client).

What changes should I make inorder to get these metrics (in the kubernetes-pods)?

**Comment by sachinsaju** [comment]
Is this actually a bug or misconfiguration?

**Comment by jotak** [comment]
@sachinsaju so, if you have istio 1.6 you can install it with metrics merging enabled, which should fix this problem (e.g.: `istioctl manifest apply --set meshConfig.enablePrometheusMerge=true --set profile=demo)`

Prior to 1.6 I had to tweak the prometheus configmap in the same way that was done in this patch: https://github.com/istio/istio/pull/10492/files . If you don't want at all https scraping you can even completely remove the `kubernetes-pods-istio-secure` job and modify the `kubernetes-pods` to remove the following 'drop' rule:

```
      - source_labels: [__meta_kubernetes_pod_annotation_sidecar_istio_io_status]
        action: drop
        regex: (.+)
```

That should work

**Comment by jotak** [comment]
This is solved in 1.7 so for me issue can be closed, unless you plan some backporting to 1.6.x

**Comment by aaftio** [comment]
> @sachinsaju so, if you have istio 1.6 you can install it with metrics merging enabled, which should fix this problem (e.g.: `istioctl manifest apply --set meshConfig.enablePrometheusMerge=true --set profile=demo)`
> 
> Prior to 1.6 I had to tweak the prometheus configmap in the same way that was done in this patch: https://github.com/istio/istio/pull/10492/files . If you don't want at all https scraping you can even completely remove the `kubernetes-pods-istio-secure` job and modify the `kubernetes-pods` to remove the following 'drop' rule:
> 
> ```
>       - source_labels: [__meta_kubernetes_pod_annotation_sidecar_istio_io_status]
>         action: drop
>         regex: (.+)
> ```
> 
> Just do this change in prometheus config map and restart prometheus. That should work.

I am using istio 1.6 and add the **`meshConfig.enablePrometheusMerge=true`** config , it works now, thank you.

**Comment by Shahard2** [comment]
Having this issue in Istio 1.9,


`2021-04-11T13:49:15.082305Z	error	failed scraping application metrics: error scraping http://localhost:80/metrics: Get "http://localhost:80/metrics": dial tcp 127.0.0.1:80: connect: connection refused`


Any solution ??

**Comment by Shahard2** [comment]
> Having this issue in Istio 1.9,
> 
> `2021-04-11T13:49:15.082305Z error failed scraping application metrics: error scraping http://localhost:80/metrics: Get "http://localhost:80/metrics": dial tcp 127.0.0.1:80: connect: connection refused`
> 
> Any solution ??


Anyone found solution ?

**Comment by taitelman** [comment]
having the issue in 1.11.5:
```
 istio-proxy error failed scraping application metrics: error scraping http://localhost:80/metrics: Get "http://localhost:80/metrics": dial tcp [::1]:80: connect: connection refused
```
and the pod shouting it has prometheus.io POD annotations:
```
metadata:
  annotations:
    prometheus.io/path: /stats/prometheus
    prometheus.io/port: "15020"
    prometheus.io/scrape: "true"
```

**Comment by pranavgangrade** [comment]
@Shahard2 Did you get any solution for this

**Comment by pranavgangrade** [comment]
ok
