### ISSUE TITLE
pilot OutlierDetection minHealthPercent=0 cannot send to envoy

### ISSUE THREAD

**Issue by ethanhanjiahao** [istio/istio#24077]
In our production scenario，we use envoy as our api gateway.  we use Destination Rule OutlierDetection to control traffic not send to the error pods. 

Cause of when i set outlier.MinHealthPercent=0, pilot do not send the config to envoy。
![image](https://user-images.githubusercontent.com/10829448/82807150-ce917900-9eb9-11ea-8d7b-4766c230fff3.png)

But cause of envoy make the default value of healthy_panic_threshold to 50%， so we can not remove all the error pods. 
![image](https://user-images.githubusercontent.com/10829448/82806828-309dae80-9eb9-11ea-8801-b0bc2829da23.png)

Can we modify the judge statement to “outlier.MinHealthPercent >= 0”，then can send the config to envoy.

**Comment by hzxuzhonghu** [comment]
I think you are using an old release. The recent releases have already been fixed in #15609

**Comment by ethanhanjiahao** [comment]
> I think you are using an old release. The recent releases have already been fixed in #15609

thanks for you , i saw it in release1.3.  i close the issue
