### ISSUE TITLE
pilot OutlierDetection minHealthPercent=0 cannot deliver to envoy

### ISSUE THREAD

**Issue by ethanhanjiahao** [istio/istio#24076]
In our production scenario，we use envoy as our api gateway.  we use Destination Rule OutlierDetection to control traffic not send to the error pods. 

Cause of when i set outlier.MinHealthPercent=0, pilot do not send the config to envoy。
![image](https://user-images.githubusercontent.com/10829448/82806696-e61c3200-9eb8-11ea-9135-c51dbb4b26f2.png)

But cause of envoy make the default value of healthy_panic_threshold to 50%， so we can not remove all the error pods. 
![image](https://user-images.githubusercontent.com/10829448/82806828-309dae80-9eb9-11ea-8801-b0bc2829da23.png)

Can we modify the judge statement to “outlier.MinHealthPercent >= 0”，then can send the config to envoy.

**Comment by howardjohn** [comment]
GitHub opened this issue twice so I'll close this one
Thanks
