### ISSUE TITLE
no matches for kind "Gateway" and "VirtualService" in version "networking.istio.io/v1alpha3"

### ISSUE THREAD

**Issue by NextZeus** [istio/istio#24085]
root@nextzeus ~/istio-1.5.1# kubectl apply -f samples/bookinfo/networking/bookinfo-gateway.yaml
unable to recognize "samples/bookinfo/networking/bookinfo-gateway.yaml": no matches for kind "Gateway" in version "networking.istio.io/v1alpha3"
unable to recognize "samples/bookinfo/networking/bookinfo-gateway.yaml": no matches for kind "VirtualService" in version "networking.istio.io/v1alpha3"
root@nextzeus ~/istio-1.5.1 [1]# kubectl get gateway
error: the server doesn't have a resource type "gateway"

# Here is pods, services image:
https://github.com/NextZeus/k8s-deploy-nodejs-app/blob/master/book-info-application.png

# Here is bookinfo-gateway.yaml content:

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: bookinfo-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookinfo
spec:
  hosts:
  - "*"
  gateways:
  - bookinfo-gateway
  http:
  - match:
    - uri:
        exact: /productpage
    - uri:
        prefix: /static
    - uri:
        exact: /login
    - uri:
        exact: /logout
    - uri:
        prefix: /api/v1/products
    route:
    - destination:
        host: productpage
        port:
          number: 9080

**Comment by hzxuzhonghu** [comment]
can you show the result of `kubectl get crd`? Does it include gateway and virtualservice?

**Comment by NextZeus** [comment]
@hzxuzhonghu Sorry , Istio was installed failed. I reinstall it and everything is ok now.

**Comment by joeyism** [comment]
A bit late, but when I ran into this error, I checked that my `istio` was installed properly. What fixed it for me was also running
```bash
istioctl install --set profile=demo -y
```
