### ISSUE TITLE
istiod service cannot be created when type is set to LoadBalancer

### ISSUE THREAD

**Issue by rolandkool** [istio/istio#24081]
**Bug description**
In Istio 1.6.0 the definition for the `istiod` service has changed and some DNS related ports got added. As DNS can be used via both UDP and TCP, there is a mix of protocols defined in the service. This does not seem to work when the service is set to `type: LoadBalancer`. In our case, we have set it to `LoadBalancer` for our multi-cluster setup. Also, the documentation (https://istio.io/docs/setup/install/multicluster/shared/#main-cluster) shows how to set it to LoadBalancer, as it is one of the two options to make istiod remotely available for the other clusters. The other option being the ingress gateways.

**Expected behavior**
The service should be created. However, this seems to be a limitation in Kubernetes/GKE, so Istio can possibly fix this by splitting the DNS ports off onto a different service. These ports were not exposed on Istio 1.5.

**Steps to reproduce the bug**
Set `type: LoadBalancer` on the istiod service and run istioctl to apply the manifests.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
Istio 1.6.0

**How was Istio installed?**
istioctl install

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

**Comment by howardjohn** [comment]
if we are already modifying the Service to `type: LoadBalancer` we could also just change the ports while we are at it? https://istio.io/docs/setup/install/istioctl/#configure-gateways shows an example

**Comment by rolandkool** [comment]
What breaks if we were to remove the DNS related ports? Those are newly introduced and are causing our upgrade issue.
As a workaround, we create a second service with only the two ports required for remote clusters to talk to the control plane cluster.

**Comment by howardjohn** [comment]
Nothing should break unless you are using the new DNS features (if you don't know about them, you are not - they are disabled by default)

**Comment by rolandkool** [comment]
No we're probably not. However, removing them will just put us in this situation again if we need or want to use this feature in the future. Wouldn't it be an option to put these DNS ports onto a separate Kubernetes service resource?

**Comment by rolandkool** [comment]
Just tested your suggestion to omit the DNS ports and just configure other ports on the service, but that does not seem to work. I looks like the ports are merged with the existing ones and not overwritten.

**Comment by costinm** [comment]
We can put them in a separate service - but it's not trivial since we'll also need to use a separate DNS cert. 

I think the simplest solution is to just remove the UDP port with an option ? Easy to fix.

**Comment by rolandkool** [comment]
As long as it does not break future functionality where you need to have the UDP port.

**Comment by costinm** [comment]
The UDP port was added mostly for debugging and latency testing ( to measure the overhead of intercepted DNS + DoT with UDP). And the plan is to move the 'zone' to the agent, so even the TCP port may go away. 

I'll start a PR next week, not sure when 1.6.1 freeze is.

**Comment by howardjohn** [comment]
UDP port was removed
