### ISSUE TITLE
Gateway and virtual services can not work on top of k8s ingress.

### ISSUE THREAD

**Issue by salimuddin87** [istio/istio#24086]
**I have running k8s ingress with contour in my cluster and trying to integrate istio. 
I have created a simple gateway and virtual service but always getting error: Referenced host not found.
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: com-gateway
  namespace: istio-dev
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: grpc
      protocol: GRPC
    hosts:
    - com-istio-dev.com

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: com-vs
  namespace: istio-dev
spec:
  hosts:
  - com-istio-dev.com
  gateways:
  - com-gateway
  http:
  - route:
    - destination:
        host: com-istio-dev.com
        port:
            number: 80
      weight: 100
**

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
I am pretty sure this is the same as https://github.com/istio/istio/issues/24061 (but http2 vs grpc). Can you try changing your gateway protocol to HTTP?

**Comment by salimuddin87** [comment]
$ istioctl analyze -n istio-dev
Error [IST0101] (VirtualService com-vs.istio-dev) Referenced host not found: "com-istio-dev.com"
Trying work flow gateway-> ingress-> service->pod. Because we already have work flow ingress-> service->pod. which I don't want to disturb.

**Comment by salimuddin87** [comment]
I have a k8s cluster with kubernetes-ingress. Now I am trying to integrate istio in that cluster without loadbalancer(using nodeport). Is it possible??

**Comment by howardjohn** [comment]
Yes please follow https://istio.io/docs/tasks/traffic-management/ingress/

**Comment by salimuddin87** [comment]
@howardjohn Thanks
