### ISSUE TITLE
istio-pilot service in 1.6 not removed

### ISSUE THREAD

**Issue by rolandkool** [istio/istio#24083]
**Bug description**
The `istio-pilot` service is not cleaned up after upgrading from 1.5 to 1.6.
The istio tar.gz for 1.6 does not seem to contain any istio-pilot service reference, so if it is not required, it should be removed or it should be documented that it can be removed. If it cannot be removed, it should be included in the installation and documented what it is used for.

**Expected behavior**
Unused resources should be removed.

**Steps to reproduce the bug**
Upgrade from 1.5 to 1.6

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.6.0

**How was Istio installed?**
istioctl install

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

**Comment by hzxuzhonghu** [comment]
For old proxies, i think they still need istio-pilot service.

**Comment by rolandkool** [comment]
So if we only have proxies with version of 1.5 or higher, we can safely remove it?

**Comment by rolandkool** [comment]
We found in the logs that Istio 1.5.x proxies use that address to connect to Citadel on the same cluster. So it can be removed once all proxies are upgrade to a 1.6 version.

**Comment by tillig** [comment]
Just ran into this today. It also leaves all the corresponding services, configmaps, poddisruptionbudgets, serviceaccounts, secrets, and everything else. No idea which of those things may still be required (i.e., referenced from istiod but with the old name). I was able to finally delete the deployments and services, but I'm unclear which configmaps and so on are actually required. Likely I'll need to go create a separate cluster, do a clean 1.6.4 install, and do a full diff to manually figure it out.
