### ISSUE TITLE
Requests are not getting routed as desired

### ISSUE THREAD

**Issue by sahilmalav** [istio/istio#24095]
**Bug description**
I've deployed two very simple services in a namespace with istio injection enabled. Both the services are hosting a flask application on port 6666 which listens for a number. The first service returns the square of the number and the second service returns the cube of the number. I've deployed it on an on-prem kubernetes cluster by appropriately creating a Service, two Deployments, a VirtualService and a DestinationRule (screenshots of each yaml attached below). I've mentioned the weights as 0 and 100 respectively for first and second service in the VirtualService yaml, but the routing seems to follow a round-robin schema, thus completely ignoring the desired routing rules. 

![Screenshot from 2020-05-26 17-14-32](https://user-images.githubusercontent.com/41611365/82897123-c21e2680-9f74-11ea-8779-843a58ad53be.png)
![Screenshot from 2020-05-26 17-14-55](https://user-images.githubusercontent.com/41611365/82897128-c3e7ea00-9f74-11ea-8724-5cdb988b379b.png)
![Screenshot from 2020-05-26 17-15-12](https://user-images.githubusercontent.com/41611365/82897129-c4808080-9f74-11ea-93e9-3964e8fdb560.png)
![Screenshot from 2020-05-26 17-16-12](https://user-images.githubusercontent.com/41611365/82897132-c4808080-9f74-11ea-957d-5ce95e21b6c2.png)
![Screenshot from 2020-05-26 17-16-30](https://user-images.githubusercontent.com/41611365/82897134-c5191700-9f74-11ea-93dc-7538a428ffe2.png)

**Expected behavior**
All the requests should have been routed to the second service.

**Steps to reproduce the bug**
YAML screenshots attached.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istio version - the one installed with Kubeflow 0.6 (I think it is 1.1)
kubectl version output: 
_Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}_

**How was Istio installed?**
As a by-product of Kubeflow 0.6

**Environment where bug was observed (cloud vendor, OS, etc)**
On-prem Linux

**Comment by esnible** [comment]
FYI when pasting Istio rules it is better to add them as text rather than screenshots.  It is difficult to attempt to reproduce without text.

```
If you put three backticks before and after text it shows up like this
```

**Comment by sahilmalav** [comment]
@esnible : Attaching text files for each screenshot. Hope this helps. 

[deployment_file_svc2.txt](https://github.com/istio/istio/files/4682378/deployment_file_svc2.txt)
[deployment_file_svc1.txt](https://github.com/istio/istio/files/4682383/deployment_file_svc1.txt)
[destinationrules.txt](https://github.com/istio/istio/files/4682388/destinationrules.txt)
[virtualsvc.txt](https://github.com/istio/istio/files/4682394/virtualsvc.txt)
[servicefile.txt](https://github.com/istio/istio/files/4682407/servicefile.txt)

**Comment by howardjohn** [comment]
Can you paste a config dump of the client? You can follow https://github.com/istio/istio/wiki/Troubleshooting-Istio

**Comment by sahilmalav** [comment]
@howardjohn : I'm assuming you mean the config dump of the two pods running as a part of my deployment. Please let me know otherwise. Attaching the dump below. 
[config_dump.zip](https://github.com/istio/istio/files/4687197/config_dump.zip)

**Comment by howardjohn** [comment]
can you turn on access logs (its in the guide above) and paste the logs? Based on config I would expect 100% to go to `cu`

**Comment by sahilmalav** [comment]
@howardjohn : Attaching the logs of the istio-proxy container in the the two pods running as a part of my deployment. 
[logs.zip](https://github.com/istio/istio/files/4690038/logs.zip)

**Comment by howardjohn** [comment]
The logs are empty  Ithink?

**Comment by sahilmalav** [comment]
@howardjohn : sorry, uploaded the wrong folder. Please find it below. 
[istio-proxy-logs.zip](https://github.com/istio/istio/files/4690103/istio-proxy-logs.zip)

**Comment by howardjohn** [comment]
You do not seem to have access logs enabled though? Can you follow the
steps in troubleshooting guid to enable? if you do have it enabled then
this means no traffic is going through Envoy

**Comment by sahilmalav** [comment]
@howardjohn : The steps given to enable access logs include the use of "istioctl", but I don't have it installed since I installed istio through kubeflow 0.6. Is there any other way to enable the logs?

**Comment by howardjohn** [comment]
you can modify the `istio` configmap in istio-system directly

**Comment by sahilmalav** [comment]
This is my istio configmap currently. 

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: istio
  namespace: istio-system
  selfLink: /api/v1/namespaces/istio-system/configmaps/istio
  uid: 9d32f514-9bf2-476a-8a2f-79ec1f7ab459
  resourceVersion: '16487593'
  creationTimestamp: '2020-01-16T09:20:54Z'
  labels:
    app: istio
    chart: istio
    heritage: Tiller
    release: istio
data:
  mesh: >-
    # Set the following variable to true to disable policy checks by the Mixer.

    # Note that metrics will still be reported to the Mixer.

    disablePolicyChecks: false


    # Set enableTracing to false to disable request tracing.

    enableTracing: true


    # Set accessLogFile to empty string to disable access log.

    accessLogFile: "/dev/stdout"


    # If accessLogEncoding is TEXT, value will be used directly as the log
    format

    # example: "[%START_TIME%] %REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%
    %PROTOCOL%\n"

    # If AccessLogEncoding is JSON, value will be parsed as map[string]string

    # example: '{"start_time": "%START_TIME%", "req_method": "%REQ(:METHOD)%"}'

    # Leave empty to use default log format

    accessLogFormat: ""


    # Set accessLogEncoding to JSON or TEXT to configure sidecar access log

    accessLogEncoding: 'TEXT'

    mixerCheckServer: istio-policy.istio-system.svc.cluster.local:9091

    mixerReportServer: istio-telemetry.istio-system.svc.cluster.local:9091

    # policyCheckFailOpen allows traffic in cases when the mixer policy service
    cannot be reached.

    # Default is false which means the traffic is denied when the client is
    unable to connect to Mixer.

    policyCheckFailOpen: false

    # Let Pilot give ingresses the public IP of the Istio ingressgateway

    ingressService: istio-ingressgateway


    # Default connect timeout for dynamic clusters generated by Pilot and
    returned via XDS

    connectTimeout: 10s


    # DNS refresh rate for Envoy clusters of type STRICT_DNS

    dnsRefreshRate: 5s


    # Unix Domain Socket through which envoy communicates with NodeAgent SDS to
    get

    # key/cert for mTLS. Use secret-mount files instead of SDS if set to empty. 

    sdsUdsPath: 


    # This flag is used by secret discovery service(SDS). 

    # If set to true(prerequisite:
    https://kubernetes.io/docs/concepts/storage/volumes/#projected), Istio will
    inject volumes mount 

    # for k8s service account JWT, so that K8s API server mounts k8s service
    account JWT to envoy container, which 

    # will be used to generate key/cert eventually. This isn't supported for
    non-k8s case.

    enableSdsTokenMount: false


    # This flag is used by secret discovery service(SDS). 

    # If set to true, envoy will fetch normal k8s service account JWT from
    '/var/run/secrets/kubernetes.io/serviceaccount/token' 

    #
    (https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/#accessing-the-api-from-a-pod) 

    # and pass to sds server, which will be used to request key/cert
    eventually. 

    # this flag is ignored if enableSdsTokenMount is set.

    # This isn't supported for non-k8s case.

    sdsUseK8sSaJwt: false


    # The trust domain corresponds to the trust root of a system.

    # Refer to
    https://github.com/spiffe/spiffe/blob/master/standards/SPIFFE-ID.md#21-trust-domain

    trustDomain: 


    # Set the default behavior of the sidecar for handling outbound traffic from
    the application:

    # ALLOW_ANY - outbound traffic to unknown destinations will be allowed, in
    case there are no

    #   services or ServiceEntries for the destination port

    # REGISTRY_ONLY - restrict outbound traffic to services defined in the
    service registry as well

    #   as those defined through ServiceEntries  

    outboundTrafficPolicy:
      mode: ALLOW_ANY

    localityLbSetting:
      {}
      

    # The namespace to treat as the administrative root namespace for istio

    # configuration.    

    rootNamespace: istio-system

    configSources:

    - address: istio-galley.istio-system.svc:9901


    defaultConfig:
      #
      # TCP connection timeout between Envoy & the application, and between Envoys.  Used for static clusters
      # defined in Envoy's configuration file
      connectTimeout: 10s
      #
      ### ADVANCED SETTINGS #############
      # Where should envoy's configuration be stored in the istio-proxy container
      configPath: "/etc/istio/proxy"
      binaryPath: "/usr/local/bin/envoy"
      # The pseudo service name used for Envoy.
      serviceCluster: istio-proxy
      # These settings that determine how long an old Envoy
      # process should be kept alive after an occasional reload.
      drainDuration: 45s
      parentShutdownDuration: 1m0s
      #
      # The mode used to redirect inbound connections to Envoy. This setting
      # has no effect on outbound traffic: iptables REDIRECT is always used for
      # outbound connections.
      # If "REDIRECT", use iptables REDIRECT to NAT and redirect to Envoy.
      # The "REDIRECT" mode loses source addresses during redirection.
      # If "TPROXY", use iptables TPROXY to redirect to Envoy.
      # The "TPROXY" mode preserves both the source and destination IP
      # addresses and ports, so that they can be used for advanced filtering
      # and manipulation.
      # The "TPROXY" mode also configures the sidecar to run with the
      # CAP_NET_ADMIN capability, which is required to use TPROXY.
      #interceptionMode: REDIRECT
      #
      # Port where Envoy listens (on local host) for admin commands
      # You can exec into the istio-proxy container in a pod and
      # curl the admin port (curl http://localhost:15000/) to obtain
      # diagnostic information from Envoy. See
      # https://lyft.github.io/envoy/docs/operations/admin.html
      # for more details
      proxyAdminPort: 15000
      #
      # Set concurrency to a specific number to control the number of Proxy worker threads.
      # If set to 0 (default), then start worker thread for each CPU thread/core.
      concurrency: 2
      #
      tracing:
        zipkin:
          # Address of the Zipkin collector
          address: zipkin.istio-system:9411
      #
      # Mutual TLS authentication between sidecars and istio control plane.
      controlPlaneAuthPolicy: NONE
      #
      # Address where istio Pilot service is running
      discoveryAddress: istio-pilot.istio-system:15010
  meshNetworks: 'networks: {}'

```

Correct me if I'm wrong, but I think that access logs are already enabled.

**Comment by sahilmalav** [comment]
@howardjohn : Also, below is a small snippet from the logs. I think access logs are there. 

```
[2020-05-27 07:05:38.944][17][warning][misc] [external/envoy/source/common/protobuf/utility.cc:174] Using deprecated option 'envoy.api.v2.Listener.use_original_dst' from file lds.proto. This configuration will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/intro/deprecated for details.
[2020-05-27 07:05:55.299][28][warning][filter] [src/istio/mixerclient/report_batch.cc:106] Mixer Report failed with: UNAVAILABLE:Server is currently overloaded. Please try again.
[2020-05-27T07:05:41.663Z] "POST /operate HTTP/1.1" 0 DC "-" 13 0 10481 - "-" "curl/7.58.0" "7797e6c3-e625-9a52-a185-690cb04d97f7" "172.16.3.51:32354" "127.0.0.1:6666" inbound|6666|http|istio-mesh.istio-testing.svc.cluster.local - 10.244.2.136:6666 10.244.0.0:34052 -
[2020-05-27T07:05:58.124Z] "POST /operate HTTP/1.1" 200 - "-" 13 23 9 4 "-" "curl/7.58.0" "b4183feb-abf9-9adf-aa68-817aec8af7cb" "172.16.3.51:32354" "127.0.0.1:6666" inbound|6666|http|istio-mesh.istio-testing.svc.cluster.local - 10.244.2.136:6666 10.244.0.0:34100 -
[2020-05-27T07:05:59.493Z] "POST /operate HTTP/1.1" 200 - "-" 13 23 4 4 "-" "curl/7.58.0" "11d24dd4-7484-983d-ae51-132b884c8d61" "172.16.3.51:32354" "127.0.0.1:6666" inbound|6666|http|istio-mesh.istio-testing.svc.cluster.local - 10.244.2.136:6666 10.244.0.0:34142 -
2020-05-27T07:06:24.540998Z	info	watchFileEvents: "/etc/certs/cert-chain.pem": MODIFY|ATTRIB
2020-05-27T07:06:24.541049Z	info	watchFileEvents: "/etc/certs/key.pem": MODIFY|ATTRIB
2020-05-27T07:06:24.541062Z	info	watchFileEvents: "/etc/certs/root-cert.pem": MODIFY|ATTRIB

```

**Comment by howardjohn** [comment]
Do you have it from the client though? that would be useful.

**Comment by sahilmalav** [comment]
> Do you have it from the client though? that would be useful.
I'm sorry, can you please elaborate? I'm not sure I understand it completely. 
To clarify, I used the following command to generate these logs (similar for the second pod): 
`kubectl log svc-1--istio-mesh-f9d87d6b4-vzd7b -c istio-proxy -n istio-testing > proxy-svc-1.log`

should I have done something different?

**Comment by howardjohn** [comment]
We need the logs from the person who is calling the `istio-mesh` - those logs are from `istio-mesh`. Ie we need outbound logs, not inbound logs. Also you are running a super deprecated version, can you upgrade? https://istio.io/blog/2019/announcing-1.1-eol/

**Comment by howardjohn** [comment]
Closing as we have not enough info
