### ISSUE TITLE
Call mutating webhook failed

### ISSUE THREAD

**Issue by panpanli521** [istio/istio#24091]
**Bug description**
After installing Istio 1.4.6, when I create pod, sidecar inject is failed and  pod does not exist. The apiserver log as follows:
![image](https://user-images.githubusercontent.com/15307422/82888642-2c869500-9f7c-11ea-9b8a-8f65140467d6.png)

Plus, I installed flannel on k8s. Does something wrong with the communication between apiserver and pod? How can I resolve this problem? Thanks!
 

**Expected behavior**
Pod is created and sidecar is injected simultaneously.
**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
k8s version:
![image](https://user-images.githubusercontent.com/15307422/82888841-71123080-9f7c-11ea-8300-ada23b46c3b2.png)
helm version:
![image](https://user-images.githubusercontent.com/15307422/82888780-5b9d0680-9f7c-11ea-89ad-9950dbe679e8.png)

**How was Istio installed?**
I install istio based on this guide: https://knative.dev/docs/install/installing-istio/#installing-istio-with-sidecar-injection
**Environment where bug was observed (cloud vendor, OS, etc)**
The local cluster I set up.

**Comment by esnible** [comment]
Often this means the Galley or Istiod pod is not running.  If you do `kubectl -n istio-system get pods` are all of the pods `Running`?

**Comment by howardjohn** [comment]
It can also indicate no connectivity from api server to the pod. This may be from firewall rules for example

**Comment by panpanli521** [comment]
@esnible 
`kubectl -n istio-system get pods`
![image](https://user-images.githubusercontent.com/15307422/82976138-e4658200-a010-11ea-9a38-d90d3285fa34.png)
and after I execute the command: `kubectl describe pod istio-galley-6755c887f4-rvshj -n istio-system` , one warning event is as follows:
`MountVolume.SetUp failed for volume "certs" : secret "istio.istio-galley-service-account" not found`. Does this matter?

**Comment by panpanli521** [comment]
Sometimes, when I uninstalled istio and reinstalled it, the similar errors occured.
![image](https://user-images.githubusercontent.com/15307422/82976672-4b376b00-a012-11ea-85e2-378abadca5d8.png)

**Comment by howardjohn** [comment]
See https://istio.io/docs/ops/common-problems/injection/#automatic-sidecar-injection-fails-if-the-kubernetes-api-server-has-proxy-settings maybe?

**Comment by panpanli521** [comment]
@howardjohn   no proxy in apiserver and pod, but the pods istio-galley-6755c887f4-vgxcp and istio-sidecar-injector-7f6cc8b997-l2ccv have problem like this:
`MountVolume.SetUp failed for volume "certs" : secret "istio.istio-sidecar-injector-service-account" not found`
`MountVolume.SetUp failed for volume "certs" : secret "istio.istio-galley-service-account" not found`

**Comment by howardjohn** [comment]
Is that message temporary though? it may happen at install and go away
shortly after. You may also try Istio 1.6 which is a bit simpler

**Comment by howardjohn** [comment]
You may also have firewall rules, see https://istio.io/docs/setup/platform-setup/gke/. This is for GKE but may apply to others as well, not sure what k8s provider you use

**Comment by howardjohn** [comment]
Closing as there has not been any activity or followup on the questions. Please reopen if still seeing issues. Thanks
