### ISSUE TITLE
Envoy listens only on IPv4 in dual-stack environment

### ISSUE THREAD

**Issue by sandhose** [istio/istio#24099]
**Bug description**

In a Kubernetes dual-stack environment, `pilot-agent` generates the config with IPv4 wildcards (`0.0.0.0`), not IPv6 ones (`::`).
This breaks prometheus, as the stats listener only listens on IPv4, while Prometheus's service discovery might pick up the IPv6 Pod IP.

**Expected behavior**

The stats listener should listen on both IPv4 and IPv6 in a dual-stack environment

**Steps to reproduce the bug**

- setup a dual-stack Kubernetes cluster. Unfortunately, I don't think there is an easy way to do that right now, but kubeadm with the IPv6DualStack feature gate with cilium on bare-metal kinda works.
- install istio with the prometheus component
- prometheus should not be able to scrap envoy containers (connection refused)

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```sh
# istioctl version --remote
client version: 1.5.4
ingressgateway version: 1.5.4
pilot version: 2c244644e51765a4939afc7ab5e71bca2ecc384d-dirty # basically 1.5.4, because I used Cilium's integration
data plane version: 1.5.4 (2 proxies)

# kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"archive", BuildDate:"1970-01-01T00:00:01Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

Via `(cilium-)istioctl manifest`

**Environment where bug was observed (cloud vendor, OS, etc)**

Bare metal installation with Kubeadm in dual-stack configuration with Cilium on Ubuntu 20.04.

**Additional informations**

The generated envoy config looks like this:
``` 
root@details-v1-6fc55d65c9-v6hxr:/# grep -A 8 listeners /etc/istio/proxy/envoy-rev0.json
    "listeners":[
      {
        "address": {
          "socket_address": {
            "protocol": "TCP",
            "address": "0.0.0.0",
            "port_value": 15090
          }
        },
```

The address should probably be set to `::`. Looking at the code and the bootstrap template, it seems like it is because the `wildcard` variable is set to [`WildcardIPv4`](https://github.com/istio/istio/blob/327d9b5afb8d57b12692ed3da3f1329db1130575/pkg/bootstrap/option/instances.go#L35) and not `WildcardIPv6`. Same goes for the LocalhostValue and DNSLookupFamilyValue.

The detection is done here: https://github.com/istio/istio/blob/c24438d1706e4db7ffdacd2f686223f7a6c104c0/pkg/bootstrap/config.go#L145-L155
The problem is that [`isIPv6Proxy`](https://github.com/istio/istio/blob/c24438d1706e4db7ffdacd2f686223f7a6c104c0/pkg/bootstrap/config.go#L375-L388), despite of its name, returns true if and only if all the node IPs are IPv6. If a single one of them (e.g. in a dual-stack configuration) is an IPv4, it returns false.

Please note that there is another `isIPv6Proxy` function that does the same [here](https://github.com/istio/istio/blob/82f68aa330e017a57cf4d151e73f0c1f1bfe8dcb/pkg/envoy/proxy.go#L236-L249).

**Comment by uablrek** [comment]
This problem does not occur if Calico is used. Only IPv4 addresses are published, yes, but Calico uses the ipv4 addresses.

The problem when `Cilium` is used is that the PODs get's `podIP` set to an IPv6 address. Please see; https://github.com/kubernetes/kubernetes/issues/95251.

**Comment by Shashankft9** [comment]
@uablrek do you have a working setup with k8s dual stack with ipv4 as default and istio ingress? I see in your PR here : https://github.com/istio/istio/pull/29076#issuecomment-732761849, you mention 
> This happens to work in my K8s dual-stack cluster with IPv4 as default family, probably most out of luck. (note the singular "pod's IP address" in the comment)

Currently we are evaluating the istio ingress with dual stack or ipv6-only mode, and there arent many docs available and the dilemma being the fact that istio says dual stack is unsupported at this point. Your observations will really help here.

**Comment by uablrek** [comment]
Yes, I get un-altered istio (v1.7.4 and v1.8.0) to work on K8s dual-stack with ipv4 as default family. But only for ipv4 of course.

But as you have seen it works only because an ipv4 address happens to be first-found in the istio sidecar startup. Another CNI-plugin might cause an ipv6 address to be listed first and then is would not work. However this is not random (I think) so if it works for one POD it will work for all.

For ipv6-only I have no problems, but for dual-stack with ipv6 as default it doesn't work for various reasons.

But if you build istio from source and apply https://github.com/istio/istio/pull/29076.patch then it works.

However, as the istio maintainers point out, it will not work if you control istio in one K8s cluster from _another_ K8s cluster that uses a _different default family_ as the first. A pretty odd configuration IMHO.

**Comment by uablrek** [comment]
Here is a quick and incomplete instruction how to build the 2 necessary images;
```
export HUB=your.registry.here/istio
export TAG=your-user
git clean -dxf
make BUILD_WITH_CONTAINER=0 docker.proxyv2
make BUILD_WITH_CONTAINER=0 docker.pilot
docker push .....
# Install with;
istioctl install --set profile=demo --set tag=your-user --set hub=your.registry.here/istio
```

**Comment by Shashankft9** [comment]
Whats the calico version that you are using? I was trying to find what's the PodStatus.PodIPs[0] (which would basically come up as the first-found address I think for istio) that calico assigns to the the pod - ipv4 or ipv6, but I am guessing if its ipv4 for one pod then it is going to be the same for other pods as well.

**Comment by uablrek** [comment]
Please see; https://github.com/kubernetes/kubernetes/issues/95251

Calico always sets ipv4 first. Even in a dual-stack cluster with K8s using ipv6 as default. This is perfectly fine from a CNI-plugin point of view.

If you apply my PR it will not matter since all listeners will use ipv4_compat and listen on both families.

**Comment by uablrek** [comment]
Oh, and I use `calico/cni:v3.16.0`

**Comment by Shashankft9** [comment]
okay thanks! I will try to replicate this in my dev environment :)

**Comment by umeshbhandari** [comment]
Calico version: v3.18.4
Kube version: v1.20.10
Istio Version 1.7.0
Dual-Stack Environment


Could someone help in this as I am facing an issue while deploying Istio side-car?

While deploying the stateful set, I am getting the below error::
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
_Events:
Type Reason Age From Message

Warning FailedCreate 15m (x8 over 3h28m) statefulset-controller create Pod kafka-0 in StatefulSet kafka failed error: Internal error occurred: failed calling webhook "namespace.sidecar-injector.istio.io": Post "https://istiod.istio-system.svc:443/inject?timeout=10s": dial tcp [fd00:10:1616:2222::9b4a]:443: i/o timeout_
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++



![image](https://user-images.githubusercontent.com/26440075/132554914-c71f022d-55e7-428f-b565-c59ec3a23f93.png)


I found that the istiod expose only IPV4 network

istio-system istiod-7d8cd94d6c-xjvfc 1/1 Running 0 3h32m 10.244.1.129 k8s-asm-umesh-test-worker-03

As it is dual stack, pod is having both IPV4and IPV6 n/w.
Netcat output for both IP's
![image](https://user-images.githubusercontent.com/26440075/132555008-3d28bf22-e624-46af-81c9-2a70ca63ac9a.png)
