### ISSUE TITLE
Deprecated CRDs still being installed by Istio 1.6.0

### ISSUE THREAD

**Issue by rolandkool** [istio/istio#24097]
**Bug description**
`(cluster)rbacconfigs` and `servicerole(binding)s` CRDs still being added by Istio 1.6 installer (even with a fresh install).
The [upgrade documentation mentions](https://istio.io/news/releases/1.6.x/announcing-1.6/upgrade-notes/#support-ended-for-v1alpha1-security-policy) these CRDs are no longer used and can be removed.

**Expected behavior**
CRDs should not be added if these are deprecated and when documentation mentions these can be removed.

**Steps to reproduce the bug**
Do a fresh Istio 1.6 installation

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.6.0

**How was Istio installed?**
istioctl install

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

**Comment by howardjohn** [comment]
I think this was removed in #23668 and missed the 1.6 release

**Comment by howardjohn** [comment]
I think this was removed in #23668 which didn't make 1.6

**Comment by yangminzhu** [comment]
Right, the CRD is removed for 1.7 and I don't think we will backport it to 1.6.

The upgrade doc probably should be fixed to not to delete the RBAC CRD in 1.6 to avoid spamming the istiod logs, closing this one and addressing it in https://github.com/istio/istio/issues/24035.
