### ISSUE TITLE
Istio 1.6.0 -  sidecar injection prevents pods from starting

### ISSUE THREAD

**Issue by monshyn** [istio/istio#24101]
[istio-dump.tar.gz](https://github.com/istio/istio/files/4682721/istio-dump.tar.gz)
I installed Istio v1.6.0 demo profile for testing. I applied the label to the default namespace to enable sidecar auto injection. I deployed the bookstore app and it fails to start the pods. If I remove the label the app deploys successfully. I uploaded the dump_kubernetes.sh for your review.
 
Don

**Comment by howardjohn** [comment]
Looks like the istio-init contain is crashing. The dump script unfortunately doesn't grab these logs. Can you add them? try `kbuectl logs POD -c istio-init`

**Comment by monshyn** [comment]
Thanks for helping!
I attached the output for kubectl -n ops logs details-v1-6b9884764f-5v255 -c istio-init
[bookinfo.txt](https://github.com/istio/istio/files/4689570/bookinfo.txt)

**Comment by howardjohn** [comment]
```
goroutine 1 [running]:
istio.io/istio/tools/istio-iptables/pkg/dependencies.(*RealDependencies).RunOrFail(0x38e0918, 0x21a3e72, 0x10, 0xc00012d640, 0x2, 0x2)
        istio.io/istio/tools/istio-iptables/pkg/dependencies/implementation.go:44 +0x96
istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).executeIptablesRestoreCommand(0xc00073fd68, 0x2199a01, 0x0, 0x0)
        istio.io/istio/tools/istio-iptables/pkg/cmd/run.go:482 +0x387
istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).executeCommands(0xc00073fd68)
        istio.io/istio/tools/istio-iptables/pkg/cmd/run.go:489 +0x45
istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).run(0xc00073fd68)
        istio.io/istio/tools/istio-iptables/pkg/cmd/run.go:436 +0x25ef
istio.io/istio/tools/istio-iptables/pkg/cmd.glob..func1(0x388e180, 0xc0005c2f00, 0x0, 0x10)
        istio.io/istio/tools/istio-iptables/pkg/cmd/root.go:64 +0x148
github.com/spf13/cobra.(*Command).execute(0x388e180, 0xc0005c2e00, 0x10, 0x10, 0x388e180, 0xc0005c2e00)
        github.com/spf13/cobra@v1.0.0/command.go:846 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x388e420, 0x0, 0x0, 0x0)
        github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
        istio.io/istio/pilot/cmd/pilot-agent/main.go:504 +0x2d
```

iptables command fails: `iptables-restore: line 24 failed`

**Comment by erdun** [comment]
Hi, please check whether remove the init container, if you removed it, kubelet will recreate one and   failed

**Comment by monshyn** [comment]
Sorry, I'm still a bit of a newbie with k8s. I'm not certain how to remove a container. I did delete the details pod and the pod was recreate. It also failed. I uploaded a new dump file.
# k -n ops delete po details-v1-6b9884764f-5v255
pod "details-v1-6b9884764f-5v255" deleted
# k -n ops get po
NAME                              READY   STATUS                  RESTARTS   AGE
details-v1-6b9884764f-vhfbh       0/2     Init:Error              2          22s

[bookinfo-dump-2.txt](https://github.com/istio/istio/files/4695814/bookinfo-dump-2.txt)
# kubectl -n ops logs details-v1-6b9884764f-zztbg -c istio-init
iptables-restore: line 24 failed

I can disable istio-injection to prevent the init container sidecar to be created and the pods will start successfully. 
# kubectl label namespace ops  istio-injection=disabled --overwrite
# k get po -n ops details-v1-6b9884764f-blnkm
NAME                          READY   STATUS    RESTARTS   AGE
details-v1-6b9884764f-blnkm   1/1     Running   0          13s

**Comment by lambdai** [comment]
I copy paste the iptables content from your log line 31-54. And I can run `iptables-restore --noflush <savediptablesfile>` on my machine.
So the content of the iptables rules are legit.
I suspect there is previlege problem on your cni env or iptables extension missing at your node.

The implementation of iptables-restore is that the failure is normally reported at the COMMIT statement, which is your case. So I cannot tell which line is the culprit.

**Comment by lambdai** [comment]
@monshyn
The way you can debug is 
1. access the node
2. find the network space of a failing pod
3. run iptables and apply rule by rule in bookinfo-dump-2.txt line 31-54

You will locate which exact rule failing the whole iptables-restore

**Comment by monshyn** [comment]
@lambdai 
Thank you for the response. After reading your post and notice  it was working for you, I did some additional troubleshooting. While reviewing the SELinux audit logs on the nodes. I found denies for comm="iptables-restor". I put SELinux into permissive mode and re-installed the bookinfo app and the istio-init container started successfully. I reviewed the logs while in permissive mode and it was still receiving the denies. I used apply2allow to make the policy change to SELinux and that appeared to fix the issue

[root@worker2 ~]# cat /var/log/audit/audit.log | audit2allow -w -a |grep denied
node=worker2.richmond.edu type=AVC msg=audit(1590985305.704:643766): avc:  denied  { module_request } for  pid=11550 comm="iptables-restor" kmod="ipt_owner" scontext=system_u:system_r:container_t:s0:c130,c717 tcontext=system_u:system_r:kernel_t:s0 tclass=system permissive=0
node=worker2.richmond.edu type=AVC msg=audit(1590985305.705:643767): avc:  denied  { module_request } for  pid=11550 comm="iptables-restor" kmod="ipt_owner" scontext=system_u:system_r:container_t:s0:c130,c717 tcontext=system_u:system_r:kernel_t:s0 tclass=system permissive=0
node=worker2.richmond.edu type=AVC msg=audit(1590985305.706:643768): avc:  denied  { module_request } for  pid=11550 comm="iptables-restor" kmod="ipt_REDIRECT" scontext=system_u:system_r:container_t:s0:c130,c717 tcontext=system_u:system_r:kernel_t:s0 tclass=system permissive=0

[root@worker2 ~]# cat /var/log/audit/audit.log |grep 'comm="iptables-restor"' | audit2allow -a -M allow-iptables-restor

[root@worker2 ~]# cat allow-iptables-restor.te
module allow-iptables-restor 1.0;
require {
        type kernel_t;
        type container_t;
        class system module_request;
}
#============= container_t ==============
#!!!! This avc can be allowed using the boolean 'domain_kernel_load_modules'
allow container_t kernel_t:system module_request;

[root@worker2 ~]# semodule -i allow-iptables-restor.pp

**Comment by obailiumingo** [comment]
thank you  very very much，i had been confused by this problem for a whole week。
