### ISSUE TITLE
pilot-agent proxy with dns-tls & capturing all DNS traffic, error: too many open files

### ISSUE THREAD

**Issue by i-prudnikov** [istio/istio#24104]
**Bug description**
Using pilot-agent on VM to expand service mesh. istiod is running in k8s cluster, and accessed via 
ELB.  Looks like socket/connection leak. 

**Expected behavior**
DNS queries are properly served.
**Steps to reproduce the bug**
 1. Expand mesh to VM (follow the steps in https://istio.io/docs/setup/install/virtual-machine/
 2.Add into `cluster.env` the following lines:
``` bash
export DNS_AGENT="DNS-TLS"
export DNS_CAPTURE="true"
```
3. After starting istio (systemctl start istio), 
nslookup to not *.cluster.local, or *.global zones are failed:
```bash
nslookup www.google.com
Server:		127.0.1.1
Address:	127.0.1.1#53

** server can't find www.google.coml: NXDOMAIN
```
In `/var/log/istio/istio.log`, the following is observed, when trying to query DNS:
```
;; QUESTION SECTION:
;www.google.com.	IN	 A
 dial udp 127.0.1.1:53: socket: too many open files
2020-05-26T13:40:54.614374Z	debug	DNS error ;; opcode: QUERY, status: NOERROR, id: 13375
;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
```
nslookup to *.global and *.svc.cluster.local are successfully resolved 

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
$ istioctl version --remote
client version: 1.6.0
control plane version: 1.6.0
data plane version: 1.6.0 (2 proxies)

$kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-13T18:06:54Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```
**How was Istio installed?**
```
istioctl manifest apply --set profile=manifests/profiles/default.yaml -f manifests/examples/vm/values-istio-meshexpansion-gateways.yaml
```
**Environment where bug was observed (cloud vendor, OS, etc)**
OS: Ubuntu 16.04

**Comment by costinm** [comment]
Thanks for testing this ! I'll debug it - but I'm also working to replace how we handle the requests, most likely for 1.7 we'll use the faster method ( i.e. resolve locally )
