### ISSUE TITLE
[release 1.6.0] Unable to find charts under googleapis url

### ISSUE THREAD

**Issue by amitsehgal** [istio/istio#24112]
**Bug description**
Unable to locate where the charts are deployed for istio-operator, istio or istio-init

Error: failed to fetch https://storage.googleapis.com/istio-release/releases/1.6.0/charts/index.yaml : 404 Not Found

**Expected behavior**
install istio-operator through helm
**Steps to reproduce the bug**
deploy istio-operator 1.6.0 using helm
**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.6.0
**How was Istio installed?**
resource "helm_release" "istio_operator" {
  count      = var.istio_operator["enabled"] ? 1 : 0
  name       = "istio-operator"
  namespace  = kubernetes_namespace.istio-system[count.index].metadata[0].name
  repository = data.helm_repository.istio-repository[count.index].metadata[0].name
  chart      = "istio-operator"
  version    = "1.6.0"
}

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS EKS

**Comment by darkstarmv** [comment]
It will be great if `1.6.0` release is published to helm repo:
```
 helm repo add istio.io https://storage.googleapis.com/istio-release/releases/1.6.0/charts/
Error: looks like "https://storage.googleapis.com/istio-release/releases/1.6.0/charts/" is not a valid chart repository or cannot be reached: failed to fetch https://storage.googleapis.com/istio-release/releases/1.6.0/charts/index.yaml : 404 Not Found
```

**Comment by razorsk8jz** [comment]
seeing same issue even tho documentation says its available

https://istio.io/pt-br/docs/setup/install/helm/

**Comment by adrianRiobo** [comment]
same for [helm charts 1.6.1](https://storage.googleapis.com/istio-release/releases/1.6.1/charts/index.yaml)  [documentation point there](https://istio.io/pt-br/docs/setup/install/helm/#helm-chart-release-repositories) but get 404

**Comment by ostromart** [comment]
@amitsehgal, you can find the helm charts under manifests/charts in the istio/istio repo and release tarball. We currently don't have a helm repo set up but it is on the list of TODOs. 
https://github.com/istio/istio/tree/master/manifests

**Comment by darkstarmv** [comment]
if anyone is interested, I added ability to install from git release tar file to our helm deployment plugin that we use with drone. https://github.com/target/impeller#deploying-release-from-tar-file

**Comment by amitsehgal** [comment]
i use terraform helm provider...was wondering if anyone installed using terraform helm provider ?

**Comment by naphta** [comment]
@ostromart Is there a trackable issue for adding in the helm repo once more? Happy to manually add the chart in for the time being but for things like this I tend to leave a TODO comment to refer back to a github issue (or similar) so it can be fixed.

**Comment by amitsehgal** [comment]
any movement on this ?
