### ISSUE TITLE
MergeGateway refactor Servers field

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#24118]
The Servers field seems not great here. We pick an arbitrary Server (rather than all of them), then reference it:
* Get the protocol with `servers[0].Port.Protocol`
* Get the route name with `RouteNamesByServer[servers[0]]`
* Get SNI hosts from .Hosts. This probably only happens on TLS which possibly isn't impacted by the above, or it might have a bug

Using only the first one and picking an arbitrary one seems like an abuse of the field. Perhaps we should refactor this a bit - I would not be surprised if this is hiding bugs; as part of this work we should also

Here we do not append but instead set: https://github.com/istio/istio/blob/454fe74759b6e58f9b34ff77c88e37f5944f6a90/pilot/pkg/model/gateway.go#L194

**Comment by JasonRD** [comment]
Hi, is anyone already working on this? If not, I would like to try.

**Comment by howardjohn** [comment]
@JasonRD I don't think so

**Comment by adiprerepa** [comment]
@howardjohn need some clarification on some things.

in `istio/pilot/pkg/model/gateway.go`, we set to the `servers` map the `tlsServers` and `plainTextServers` objects. Is the issue here that if they have the same key, one might overwrite the other?

**Comment by jronak** [comment]
Servers is holding port->server mapping
if two servers (tls and non-tls) try to listen on the same port, then only one type of server can be setup on that port which is correct, right?
Also, I didn't understand the last part of the issue description could you please elaborate?

**Comment by howardjohn** [comment]
not stale

**Comment by howardjohn** [comment]
Not stale
