### ISSUE TITLE
Can we add a default vagrant  file? 

### ISSUE THREAD

**Issue by linsheng9731** [istio/istio#2412]
Can not run `make build` in Mac os. I think if we could add a default vagrant  file will be better.

**Comment by linsheng9731** [comment]
Or add a docker dev box ?

**Comment by rshriram** [comment]
We would be open to that. Better option would be to fix the build on Mac.

**Comment by christian-posta** [comment]
@jwendell and I have hacked up some Dockerfiles in the past to do builds like this. Would that work? Or do you have a Vagrant setup you'd like to contribute @linsheng9731 ? Also... the build works great for me on Mac OS X right now -- care to try again on latest master?

**Comment by linsheng9731** [comment]
@christian-posta I'm happy to contribute it.

**Comment by linsheng9731** [comment]
see https://github.com/istio/istio/pull/2646

**Comment by hklai** [comment]
make build should run on macos now.

Also we added a vagrant file to run e2e tests.
See https://github.com/istio/istio/blob/master/tests/e2e/README.md#using-a-local-vm
