### ISSUE TITLE
istioctl experimental precheck incorrectly reports Istio 1.6 is compatible with Kubernetes 1.14

### ISSUE THREAD

**Issue by bdschaap** [istio/istio#24132]
**Bug description**
`istioctl experimental precheck` incorrectly reports that Istio 1.6 is compatible with a Kubernetes 1.14 cluster.  Applying Istio 1.6 on a Kubernetes 1.14 cluster will return errors for CRD's that reference preserveUnknownFields and x-kubernetes-preserve-unknown-fields.  preserveUnknownFields was introduced in Kubernetes 1.15.  The documentation also does not state that Istio 1.16 is no longer compatible with Kubernetes 1.14.

**Expected behavior**
`istioctl experimental precheck` should state that Kubernetes 1.14 clusters are incompatible.  The documentation should also mention this.
**Steps to reproduce the bug**
Run `istioctl experimental precheck` on a Kubernetes 1.14 cluster.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istioctl version
no running Istio pods in "istio-system"
1.6.0

Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:39:02Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
I was trying out the feature on a new minikube cluster with 1.14.7.  Running a precheck said that 1.14.7 was compatible but applying the CRD's returned errors.

**Environment where bug was observed (cloud vendor, OS, etc)**
minikube

**Comment by howardjohn** [comment]
Thanks for the report! The docs do mention this at https://istio.io/docs/setup/platform-setup/. I would be interested to hear any feedback on a better location for that as it's currently being discussed moving it

**Comment by bdschaap** [comment]
Thanks I see it now.  I would suggest placing it in a prerequisites section.  It would also help for it to be in the release notes.

**Comment by FrimIdan** [comment]
@howardjohn Istio 1.6 can't work on K8s 1.14 or not tested on?
```
Istio 1.6 has been tested with these Kubernetes releases: 1.15, 1.16, 1.17, 1.18.
```
Sounds a bit like it might work, but basically CRDs are not compatible and even if we are skipping the CRD validation istiod runs with the following error:
```
warn	k8s.io/client-go@v0.18.0/tools/cache/reflector.go:125: watch of *v1.PartialObjectMetadata ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode watch event: no kind \"Node\" is registered for version \"v1\" in scheme \"pkg/runtime/scheme.go:101\"") has prevented the request from succeeding
```

**Comment by howardjohn** [comment]
@FrimIdan generally if you use a version outside that range, and there are bugs we will likely not fix them, we won't ensure compatibility, etc. So it *might* work outside the range but no guarantees. In the past it has, but in this case 1.14 will not work due to the CRDs.

Although that error seems potentionally different?

**Comment by brian-avery** [comment]
I like the idea of listing this on the major release notes. I think it's also a good idea to list this on both the getting started and pages for the different installation types. The platforms content listing isn't the first place I'd think of looking. Probably worth it to bring this up with the docs working group or open a separate issue tagged with docs to see what their thoughts are.
