### ISSUE TITLE
Possibly unnecessary additional `Listeners` for inbound traffic

### ISSUE THREAD

**Issue by jkbschmid** [istio/istio#24147]
**Bug description**
When debugging envoy config, Istio creates "a virtual listener per service IP, per each non-HTTP for outbound TCP/HTTPS traffic" (see ["Debugging Envoy and Istiod"](https://istio.io/docs/ops/diagnostic-tools/proxy-cmd/#deep-dive-into-envoy-configuration)). However, since Istio 1.4, there is a `FilterChain` on the "virtualInbound"-listener for each open port that directly contains a `Route` to the correct `Cluster`.

Therefore, it seems as though inbound traffic is not distributed to these "SidecarInboundListeners" anymore (that's how they're called in the code).

(This very cool [DeepDive](https://zhaohuabing.com/post/2018-09-25-istio-traffic-management-impl-intro/#virtual-listener) by @rootsongjc also describes this behaviour and gives some examplary envoy config that is very similar to the one I saw.)

Is there a reason why Istio still creates "SidecarInboundListeners" or can these be removed?

**Steps to reproduce the bug**
Deploy bookinfo and look at envoy config.

**Version**
Istio 1.4+

**Comment by howardjohn** [comment]
This should be fixed on 1.6 by https://github.com/istio/istio/pull/22788

**Comment by jkbschmid** [comment]
Great to hear, thanks for the quick response!
