### ISSUE TITLE
Istio init container crash

### ISSUE THREAD

**Issue by erdun** [istio/istio#24148]
istio init container crash

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

client version: 1.6.0
pilot version: 1.5.0
istiod version: 1.6.0
data plane version: 1.5.0 (8 proxies), 1.6.0 (3 proxies)

**How was Istio installed?**

version 1.5.0:
istioctl manifest apply

version 1.6.0:
istioctl install --set revision=canary -f values.yaml

**Environment where bug was observed (cloud vendor, OS, etc)**

CentOS Linux release 7.7.1908 (Core)

init container logs
```
Environment:
------------
ENVOY_PORT=
INBOUND_CAPTURE_PORT=
ISTIO_INBOUND_INTERCEPTION_MODE=
ISTIO_INBOUND_TPROXY_MARK=
ISTIO_INBOUND_TPROXY_ROUTE_TABLE=
ISTIO_INBOUND_PORTS=
ISTIO_LOCAL_EXCLUDE_PORTS=
ISTIO_SERVICE_CIDR=
ISTIO_SERVICE_EXCLUDE_CIDR=

Variables:
----------
PROXY_PORT=15001
PROXY_INBOUND_CAPTURE_PORT=15006
PROXY_UID=1337
PROXY_GID=1337
INBOUND_INTERCEPTION_MODE=REDIRECT
INBOUND_TPROXY_MARK=1337
INBOUND_TPROXY_ROUTE_TABLE=133
INBOUND_PORTS_INCLUDE=*
INBOUND_PORTS_EXCLUDE=15090,15021,15020
OUTBOUND_IP_RANGES_INCLUDE=*
OUTBOUND_IP_RANGES_EXCLUDE=
OUTBOUND_PORTS_EXCLUDE=
KUBEVIRT_INTERFACES=
ENABLE_INBOUND_IPV6=false

Writing following contents to rules file:  /tmp/iptables-rules-1590592535343591764.txt532247932
* nat
-N ISTIO_REDIRECT
-N ISTIO_IN_REDIRECT
-N ISTIO_INBOUND
-N ISTIO_OUTPUT
-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001
-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006
-A PREROUTING -p tcp -j ISTIO_INBOUND
-A ISTIO_INBOUND -p tcp --dport 22 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15090 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15021 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15020 -j RETURN
-A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT
-A OUTPUT -p tcp -j ISTIO_OUTPUT
-A ISTIO_OUTPUT -o lo -s 127.0.0.6/32 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --gid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
-A ISTIO_OUTPUT -j ISTIO_REDIRECT
COMMIT

iptables-restore --noflush /tmp/iptables-rules-1590592535343591764.txt532247932
iptables-restore: line 2 failed
iptables-save
# Generated by iptables-save v1.6.1 on Wed May 27 15:15:35 2020
*mangle
:PREROUTING ACCEPT [1076136:140933167]
:INPUT ACCEPT [1076136:140933167]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [915772:172731597]
:POSTROUTING ACCEPT [915772:172731597]
COMMIT
# Completed on Wed May 27 15:15:35 2020
# Generated by iptables-save v1.6.1 on Wed May 27 15:15:35 2020
*raw
:PREROUTING ACCEPT [1076136:140933167]
:OUTPUT ACCEPT [915772:172731597]
COMMIT
# Completed on Wed May 27 15:15:35 2020
# Generated by iptables-save v1.6.1 on Wed May 27 15:15:35 2020
*nat
:PREROUTING ACCEPT [28633:1717980]
:INPUT ACCEPT [94041:5119196]
:OUTPUT ACCEPT [48620:4173884]
:POSTROUTING ACCEPT [48620:4173884]
:ISTIO_INBOUND - [0:0]
:ISTIO_IN_REDIRECT - [0:0]
:ISTIO_OUTPUT - [0:0]
:ISTIO_REDIRECT - [0:0]
-A PREROUTING -p tcp -j ISTIO_INBOUND
-A OUTPUT -p tcp -j ISTIO_OUTPUT
-A ISTIO_INBOUND -p tcp -m tcp --dport 22 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15090 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15021 -j RETURN
-A ISTIO_INBOUND -p tcp -m tcp --dport 15020 -j RETURN
-A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT
-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006
-A ISTIO_OUTPUT -s 127.0.0.6/32 -o lo -j RETURN
-A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT ! -d 127.0.0.1/32 -o lo -m owner --gid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
-A ISTIO_OUTPUT -j ISTIO_REDIRECT
-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001
COMMIT
# Completed on Wed May 27 15:15:35 2020
# Generated by iptables-save v1.6.1 on Wed May 27 15:15:35 2020
*filter
:INPUT ACCEPT [1076136:140933167]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [915772:172731597]
COMMIT
# Completed on Wed May 27 15:15:35 2020
panic: exit status 1

goroutine 1 [running]:
istio.io/istio/tools/istio-iptables/pkg/dependencies.(*RealDependencies).RunOrFail(0x38e0918, 0x21a3e72, 0x10, 0xc0003dba80, 0x2, 0x2)
	istio.io/istio/tools/istio-iptables/pkg/dependencies/implementation.go:44 +0x96
istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).executeIptablesRestoreCommand(0xc000653d68, 0x2199a01, 0x0, 0x0)
	istio.io/istio/tools/istio-iptables/pkg/cmd/run.go:482 +0x387
istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).executeCommands(0xc000653d68)
	istio.io/istio/tools/istio-iptables/pkg/cmd/run.go:489 +0x45
istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).run(0xc000653d68)
	istio.io/istio/tools/istio-iptables/pkg/cmd/run.go:436 +0x25ef
istio.io/istio/tools/istio-iptables/pkg/cmd.glob..func1(0x388e180, 0xc000155600, 0x0, 0x10)
	istio.io/istio/tools/istio-iptables/pkg/cmd/root.go:64 +0x148
github.com/spf13/cobra.(*Command).execute(0x388e180, 0xc000155500, 0x10, 0x10, 0x388e180, 0xc000155500)
	github.com/spf13/cobra@v1.0.0/command.go:846 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x388e420, 0x0, 0x0, 0x0)
	github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	istio.io/istio/pilot/cmd/pilot-agent/main.go:504 +0x2d
```

**Comment by howardjohn** [comment]
Seems similar to https://github.com/istio/istio/issues/24101

**Comment by shinynz** [comment]
@erdun 这个问题我也遇到了，找了很久才发现是我清理了docker容器命令造成的istio-init重启

**Comment by erdun** [comment]
This is caused by the init container cleaned

**Comment by lambdai** [comment]
> @erdun 这个问题我也遇到了，找了很久才发现是我清理了docker容器命令造成的istio-init重启

Thank you for the update! I saw user reported istio-restore report failure at line 2 in the past. 
This line is supposed to create the chain `ISTIO_REDIRECT` but I wasn't able to find why istio-init is running on a pod which has istio iptables setup prior to istio-init.

**Comment by bydeath** [comment]
> > @erdun 这个问题我也遇到了，找了很久才发现是我清理了docker容器命令造成的istio-init重启
> 
> Thank you for the update! I saw user reported istio-restore report failure at line 2 in the past.
> This line is supposed to create the chain `ISTIO_REDIRECT` but I wasn't able to find why istio-init is running on a pod which has istio iptables setup prior to istio-init.

It happens when the container `istio-init` is removed and restarted, the iptables rules has been set at this scenario, I can reproduce it by remove the container `istio-init`.
I am wondering why iptables rules restoring fails when rules are existing?

**Comment by zhaohuabing** [comment]
Could we remove the chains first to prevent the panic reported by istio-init container?

**Comment by willemm** [comment]
According to K8S devs, init containers need to be reentrant:

https://github.com/kubernetes/kubernetes/issues/90271#issuecomment-616238111

**Comment by ydp** [comment]
> > > @lambdai  这个问题我也遇到了，找了很久才发现是我清理了docker容器命令造成的istio-init重启
> > 
> > 
> > Thank you for the update! I saw user reported istio-restore report failure at line 2 in the past.
> > This line is supposed to create the chain `ISTIO_REDIRECT` but I wasn't able to find why istio-init is running on a pod which has istio iptables setup prior to istio-init.
> 
> It happens when the container `istio-init` is removed and restarted when the pod is running, the iptables rules has been set when the pod is created and `istio-init` is initialized at firstly time.
> I can reproduce it by remove the container `istio-init` when the status is `Running` and condition is `Ready` of pods.

Could you please help tell me how to remove the container `istio-init`?  I used docker kill on host, but it did not reproduce. Thanks.

**Comment by lambdai** [comment]
> I ran into the same issue . Could we remove the chain when it already exists to prevent the panic reported by istio-init container?

@zhaohuabing @willemm There is no well-guaranteed approach. But yes I think we can deduct whether the istio rules are injected already from the existing iptables rules.

**Comment by lambdai** [comment]
> > > > @lambdai  这个问题我也遇到了，找了很久才发现是我清理了docker容器命令造成的istio-init重启
> > > 
> > > 
> > > Thank you for the update! I saw user reported istio-restore report failure at line 2 in the past.
> > > This line is supposed to create the chain `ISTIO_REDIRECT` but I wasn't able to find why istio-init is running on a pod which has istio iptables setup prior to istio-init.
> > 
> > 
> > It happens when the container `istio-init` is removed and restarted when the pod is running, the iptables rules has been set when the pod is created and `istio-init` is initialized at firstly time.
> > I can reproduce it by remove the container `istio-init` when the status is `Running` and condition is `Ready` of pods.
> 
> Could you please help tell me how to remove the container `istio-init`? I used docker kill on host, but it did not reproduce. Thanks.

I am not fully sure but my guess is either `docker container rm` or `docker container prune`. Manually running docker cmd on the node acts as a backdoor of kubelet. Not an expert but I believe it's undefined behavior to k8s.
