### ISSUE TITLE
getting failed multiple times installing through manifest generated file

### ISSUE THREAD

**Issue by pawanyoda** [istio/istio#24140]
I am using with generated manifest and it fails multiple times and I have to run again multiple times.
here is generated manifest:
```
istioctl manifest generate --set profile=default --set values.grafana.enabled=true --set addonComponents.grafana.enabled=true --set values.prometheus.enabled=true --set values.grafana.enabled=true --set values.tracing.enabled=true --set values.pilot.traceSampling=100 --set values.kiali.enabled=true --set "values.kiali.dashboard.jaegerURL=http://jaeger-query:16686" --set "values.kiali.dashboard.grafanaURL=http://grafana:3000" --set components.telemetry.enabled=true --set values.kiali.createDemoSecret=true --set meshConfig.accessLogFile="/dev/stdout" > generated_default_profile_manifest_1_6_0.yaml 
```

Is there a way to hold if any process tracking a longer time.

**Comment by esnible** [comment]
Please add the error message and the output of `istioctl version`.

**Comment by howardjohn** [comment]
Please add the failures too. You need to run `kubectl create namespace istio-system` as well by the way, I just updated the doc to add that step

**Comment by pawanyoda** [comment]
after create namespace I applied generated YAML. Now I have tried also on another staging env, same issue happening.

Error getting while installation:

> ..........
> horizontalpodautoscaler.autoscaling/istio-telemetry created
> clusterrole.rbac.authorization.k8s.io/istio-mixer-istio-system created
> clusterrolebinding.rbac.authorization.k8s.io/istio-mixer-admin-role-binding-istio-system created
> configmap/telemetry-envoy-config created
> deployment.apps/istio-telemetry created
> poddisruptionbudget.policy/istio-telemetry created
> service/istio-telemetry created
> serviceaccount/istio-mixer-service-account created
> unable to recognize "generated_default_profile_manifest_1_6_0.yaml": no matches for kind "PeerAuthentication" in version "security.istio.io/v1beta1"
> unable to recognize "generated_default_profile_manifest_1_6_0.yaml": no matches for kind "EnvoyFilter" in version "networking.istio.io/v1alpha3"
> unable to recognize "generated_default_profile_manifest_1_6_0.yaml": no matches for kind "EnvoyFilter" in version "networking.istio.io/v1alpha3"
> unable to recognize "generated_default_profile_manifest_1_6_0.yaml": no matches for kind "attributemanifest" in version "config.istio.io/v1alpha2"
> unable to recognize "generated_default_profile_manifest_1_6_0.yaml": no matches for kind "attributemanifest" in version "config.istio.io/v1alpha2"
> unable to recognize "generated_default_profile_manifest_1_6_0.yaml": no matches for kind "instance" in version "config.istio.io/v1alpha2"
> unable to recognize "generated_default_profile_manifest_1_6_0.yaml": no matches for kind "handler" in version "config.istio.io/v1alpha2"
> unable to recognize "generated_default_profile_manifest_1_6_0.yaml": no matches for kind "rule" in version "config.istio.io/v1alpha2"
> unable to recognize "generated_default_profile_manifest_1_6_0.yaml": no matches for kind "rule" in version "config.istio.io/v1alpha2"
> unable to recognize "generated_default_profile_manifest_1_6_0.yaml": no matches for kind "handler" in version "config.istio.io/v1alpha2"
> unable to recognize "generated_default_profile_manifest_1_6_0.yaml": no matches for kind "rule" in version "config.istio.io/v1alpha2"
> unable to recognize "generated_default_profile_manifest_1_6_0.yaml": no matches for kind "rule" in version "config.istio.io/v1alpha2"
> unable to recognize "generated_default_profile_manifest_1_6_0.yaml": no matches for kind "instance" in version "config.istio.io/v1alpha2"
> unable to recognize "generated_default_profile_manifest_1_6_0.yaml": no matches for kind "DestinationRule" in version "networking.istio.io/v1alpha3"
