### ISSUE TITLE
IstioOperator MeshConfig.proxyListenPort doesn't configure the iptables redirection

### ISSUE THREAD

**Issue by shakti-das** [istio/istio#24169]
**Bug description**
Configuring IstioOperator MeshConfig.proxyListenPort to a value other than 15001 does not take effect because the istio-iptables do not use this value. The injection-template has 15001 hardcoded instead of reading from MeshConfig.proxyListenPort (https://github.com/istio/istio/blob/85075d3e22422c48da103991945ae2f10c46c1e4/manifests/charts/istio-control/istio-discovery/files/injection-template.yaml#L18)

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Expected MeshConfig.proxyListenPort to also configure the port in istio-iptables args.

**Steps to reproduce the bug**
1. Set proxyListenPort to something other than 15001 via IstioOperator spec.
2. Run istioctl command and check the injection-template.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
$ istioctl version --remote
no running Istio pods in "istio-system"
e12a938f76ea48aae85c63f17609b732295bcd24-dirty
```

**How was Istio installed?**
Via Operator

**Environment where bug was observed (cloud vendor, OS, etc)**
Any k8s cluster.

**Comment by howardjohn** [comment]
@shakti-das do you have a use case for changing the port or just something you noticed?

**Comment by shakti-das** [comment]
We had another existing service listening on port 15001, so we tried changing the `proxyListenPort` to a different one. That's when I noticed this issue. The other service was also owned by our team, so as a quick fix, we moved the other service to a different port. Kept this issue open for tracking so that can come back and fix it.

**Comment by howardjohn** [comment]
@shakti-das cool, makes sense. Thanks for the info. If we provide the option it should definitely work, was just curious.
