### ISSUE TITLE
WorkloadEntry bootstrapping automation

### ISSUE THREAD

**Issue by S-Chan** [istio/istio#24160]
**Describe the feature request**

WorkloadEntry corresponds roughly to Pods, and many WorkloadEntries are typically selected by one ServiceEntry. I'm interested in an agent that can either run on VMs or detect VMs that start up and want to join a mesh and bootstrap a corresponding WorkloadEntry. Ideally, this agent could also bootstrap VM identity (making it more likely to run on each connected VM directly) and perform some healthchecks and/or heartbeats described in https://github.com/istio/istio/issues/24159.

**Describe alternatives you've considered**

Platform specific VM agents could be implemented, but it seems beneficial to have a reference/centralized implementation in Istio.

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by rshriram** [comment]
There are security implications for this.. The agent running on the VMs will now need to have direct access to k8s apis to be able to write the workload entry objects. To be able to access the k8s apis, it needs to have some form of authorized access to k8s. How this is going to be granted is the hard problem here (the VM identity you mentioned). In addition, properties like labels, ports on which the VM is listening, etc. cannot be auto detected.

**Comment by S-Chan** [comment]
It might be useful to break the features apart and discuss them separately. Here's what I'm thinking:
1) There should be some agent that updates workload entry health check and heartbeat status. I can see arguments for running them on or off VMs, but the functionality doesn't necessarily depend on allowing VMs to access the k8s API.
2) There should be some agent (not necessarily the same as the health checking one) that handles creation of the workload entry upon creation of a VM that wants to join a mesh and deletion upon the VM's teardown. I agree that some fields of workload entries cannot be auto detected and will need to be passed in by an admin or some other API. However, there are some labels which could be added and which would provide value - for example, failure domains and other instance metadata.

As I understand, there is active discussion around how to bootstrap VM identity and automate it. Some of the details about where an agent runs, exactly what it can/should do, depend on how those discussions shape out. However, it's still possible to discuss whether the above two features should live in the core Istio project, or how external components should interface with Istio to provide them.

**Comment by sdake** [comment]
There is significant activity in this area in the team drive. If you use the search feature for "virtual machine", you will see many active threads of discussion. I'd encourage you to attend a few environments WG meetings to learn how we develop RFCs, which is what I'd suggest for your work.

Securely implementing virtual machine workload integration without adding constraints on the rest of the Istio architecture (e.g. need to read/write from kubeapi) are a chief concern.

Cheers,
-steve

**Comment by howardjohn** [comment]
https://docs.google.com/document/d/1BuwOX6D30Yy6lTvj4RHwLzcUoaAu61pAdtKnLx312ec/edit?ts=5ec5b5c9  and https://docs.google.com/document/d/1-612Sgz_skeoX44dw3MU6Z8ONgq1f29wLUI9zggyLec/edit?ts=5ecd59ef are the relevant docs around this one

**Comment by jack2684** [comment]
Thanks @howardjohn ! Would you please grant us access request?

**Comment by S-Chan** [comment]
https://docs.google.com/document/d/10TyPy-6bOs0_7JljGpc2RneDdsaR9GktjwwaaVbz6fs/edit# looks like it maps extremely closely to what I'm interested in here, with Pilot (rather than an agent sitting on the VM) as the entity that healthchecks and creates WorkloadEntries, though it's not clear from the doc whether the healthchecks should be implemented as API fields in WorkloadEntry (proposed in 24159)

**Comment by howardjohn** [comment]
We have thought about the idea of having workload entry automatically
created based on XDS connections. This also implements a loose fork of
health check (xds connection broken == unhealthy). I've done some
prototypes and it's theoretically feasible but will take some work to get
right.

Better health check will also likely be required as the xds connection
being present may not indicate the VM is actually healthy - mostly just
means it's running

**Comment by S-Chan** [comment]
> Better health check will also likely be required as the xds connection
being present may not indicate the VM is actually healthy - mostly just
means it's running

+1.

> Securely implementing virtual machine workload integration without adding constraints on the rest of the Istio architecture (e.g. need to read/write from kubeapi) are a chief concern.

If communication between VMs and the registry backend (k8s, consul, etc) is not desired, that seems to imply healthcheck info would be passed between Pilot Agent and Pilot?

**Comment by costinm** [comment]
First step is to merge the 'authenticate calls from agent' - and check the namespace in the metadata matches. Once that is in place - we should merge and enable ( with a flag ) the auto creation/deletion of WorkloadEntry and see how it scales. The alternative - in case the rate of change is too high for K8S - is to use the newly added 'XDS events' to sync the 'connected pods' across Istiods, so we can handle them without relying on a save in k8s (in-memory only).

Re. health check: I am working on having istio-agent connect to Istiod via XDS - initially to sync ServiceEntries for local DNS resolution, but will also be able to do additional features, including some health checking and other reporting (mostly pending on a proposal to add payload to DiscoveryRequest as part of UDPA).

**Comment by rshriram** [comment]
cc @SecurityInsanity
