### ISSUE TITLE
kubelet 1.7.3 comptiable with which version of istio?

### ISSUE THREAD

**Issue by naruto1990** [istio/istio#24171]
**Describe the feature request**

**Describe alternatives you've considered**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
Please see https://preliminary.istio.io/docs/setup/platform-setup/ which has version compatibility. If you are talking about Kubernetes 1.7, which is years old, the answer is to upgrade Kubernetes :slightly_smiling_face:
