### ISSUE TITLE
Elasticsearch curator unable to reach elasticsearch with istio 

### ISSUE THREAD

**Issue by aggarwalShivani** [istio/istio#24176]
I am trying to run elasticsearch with istio in kubernetes environment.
Elasticsearch-oss: 7.0.1
Istio 1.5.2
Istio sidecars are ingested into elasticsearch pods (master, data nodes) and elasticsearch-curator pod.

The elasticsearch cluster formation is happening fine,  cluster health is green and the elasticsearch REST api keeps responding.
Curator is configured to run as a k8s cronjob every 5 min to delete old indices. We observe at times, curator is able to reach ES and delete indices as expected - resulting in jobs to succeed.
But a lot of times, it fails to reach ES with this error msg -
```
2020-05-27 01:01:36,036 ERROR     HTTP N/A error: HTTPConnectionPool(host='elasticsearch', port=9200): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0c41220dd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2020-05-27 01:01:36,037 CRITICAL  Curator cannot proceed. Exiting.
```

Curator with debug logs  (failed case) - 
[curator-error.log](https://github.com/istio/istio/files/4695388/curator-error.log)
Curator with debug logs  (success case) - 
[curator-success.log](https://github.com/istio/istio/files/4695397/curator-success.log)

I triggered a script that continuously contacts Elasticsearch REST api on 9200 (_cat/nodes) every 5 seconds while curator tries to contact ES. The service was responsive & reachable all the time.
When the same chart & configurations are installed without istio enabled in the namespace, curator works fine.

Can someone help to find the root cause of the issue? Are any additional configurations required?

**Comment by aggarwalShivani** [comment]
Can someone help to find the root cause of the issue? And how I could debug this? 
The connection issue is happening intermittently.
Acc to curator logs analysis, Curator is unable to connect not because the target remote is unavailable, but that it is refusing to permit Curator to connect.

**Comment by howardjohn** [comment]
See https://github.com/istio/istio/issues/20234 - may need to apply the patch there

**Comment by howardjohn** [comment]
Closing as we don't have additional info. If you are able to try out https://github.com/istio/istio/issues/20234#issuecomment-668845648 and still have issues we can investigate further.

**Comment by aggarwalShivani** [comment]
We noticed the issue when istio sidecar proxy took a bit longer to become ready, while the curator container had already started and tried contacting elasticsearch k8s svc. As a result, curator failed intermittently. One way to resolve is ensuring that curator container starts after istio proxy is fully ready.
