### ISSUE TITLE
Cant Install istio 1.6 using generated manifest yaml file

### ISSUE THREAD

**Issue by mstinglin** [istio/istio#24180]
**Bug description**
I am trying to install Istio through a generated manifest deployment file ->> istioctl manifest generate >deployment.yam and then kubectl apply -f deployment.yaml but pods are not running. seems like is something related to token, certificates and so on.

Unable to attach or mount volumes: unmounted volumes=[istio-token istiod-ca-cert], unattached volumes=[istio-token ingressgatewaysdsudspath istiod-ca-cert podinfo ingressgateway-certs istio-ingressgateway-service-account-token-gds5s config-volume ingressgateway-ca-certs istio-envoy]: timed out waiting for the condition

Unable to attach or mount volumes: unmounted volumes=[istio-token istiod-ca-cert], unattached volumes=[podinfo config-volume istio-envoy istio-token istiod-ca-cert ingressgateway-certs ingressgatewaysdsudspath ingressgateway-ca-certs istio-ingressgateway-service-account-token-gds5s]: timed out waiting for the condition

MountVolume.SetUp failed for volume "istio-token" : failed to fetch token: the server could not find the requested resource

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Be able to install using a generated file just like if I was using istioctl manifest apply

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
When using the offline generation we cannot auto detect some settings and configure accordingly. So you may need to follow the steps in https://preliminary.istio.io/docs/ops/best-practices/security/#configure-third-party-service-account-tokens

**Comment by mstinglin** [comment]
Thank for the reply @howardjohn . I was able to generate and install the manifest offline passing jwt first party toke open when creating it.

manifest generate --set values.global.jwtPolicy=first-party-jwt -f deployment.yaml
