### ISSUE TITLE
Mixer is called on the outbound traffic.

### ISSUE THREAD

**Issue by qiwzhang** [istio/istio#2418]
By design, mixer should not be called on the out-bound traffic,  only the in-bound traffic.

In the v1 envoy mixer filter config,  it is controlled by the per-route opague attributes

mixer_check:  on|off
mixer_report:  on|off

By default, they are both off.

With v2 envoy mixer filter config,  proxy is not reading these per-route data anymore.  It only uses the one in the service_configs map.

Fix:  Change Pilot to set this flag in the service_configs properly.

**Comment by kyessenov** [comment]
Since we eventually want to upstream mixerclient, we should follow the conventions of Envoy by putting HTTP-level config into HTTP routes rather than listeners. That would require the use of opaque metadata attached to routes, rather than having a big listener-level config for all routes. The situation is only going to get worse once we start using filter chains, so please make sure this gets fixed in the mixerclient.

**Comment by ayj** [comment]
Is there a tracking issue or design doc around upstreaming mixerclient?

**Comment by ayj** [comment]
cc @mandarjog

**Comment by qiwzhang** [comment]
I think the scalability  issue @kyessenov brought up has nothing to do with mixerclient upstream or not.

In order for service config coming from per-route opaque metadata, we need to wait for v2 api.

For v1,  we have two options:
1) put pre-route service_config in a base64 encoded serialized proto binary.
or
2) keep the current way of using a huge service_configs map in the enovy_mixer_filter config.

**Comment by kyessenov** [comment]
Yes, listener update triggers connection draining. Route updates are much more lightweight.
Once we have listeners with 1000 TCP/HTTP routes, we should not be touching the listener config unless the config affects all 1000 routes. The new v2 API _may_ in fact use one giant listeners for all proxy config if we use filter chains.

**Comment by kyessenov** [comment]
according to @costinm we hedge on potentially releasing with v1 xDS API, so the solution must be compatible with v1.

**Comment by qiwzhang** [comment]
@ayj  How about this?

* Pilot start to write per-route service_config into opaque data as "mixer_service_config" (based64 encoded  proto in json format for easy debugging, proto binary is not easy to decode it).
* Proxy will check this attribute, if exist,  use it,  not to use service_configs map.  Otherwise, use the one from service_configs map for backward compatibilty

**Comment by ayj** [comment]
Populating `service_config` per-route is a possibility. I'd still like to better understand what future plans are for upstreaming mixerclient and other filters (e.g. JWT) as that may effect the filter config itself.

**Comment by qiwzhang** [comment]
We may upstream auth filter sooner than mixer filter. 

For Mixer filter,  we may just upstream the Envoy related code in proxy repo src/envoy/mixer.   But still keep mixerclient repo in Istio.

mixerclient code will still use the filter config from istio/api repo.   mixer/v1/config/client.

The only benefits of such upstream is whenever Envoy change code,  they needs to fix mixer filter too.
