### ISSUE TITLE
Remove finalizer in operator

### ISSUE THREAD

**Issue by ostromart** [istio/istio#24197]
There are ongoing user complaints about finalizer behavior in the operator:
- if deletion steps are not followed exactly and user just deletes all resources, they can be left with not being able to delete istio-system namespace and no way to debug it. The recovery from this situation is painful - users have created topics about this in discuss.istio.io
- finalizer implementation is not very robust. for example a conflict error is sometimes reported, but the code does not force update or deletion per kubernetes docs. 

The finalizer is not needed. It just keeps the IstioOperator CR around while the resources are being deleted. This does prevent the small chance of leaked resources if the controller crashes while deleting but this has never been observed and is easily resolved by the user with a manual delete. The costs of the finalizer outweigh the benefits.

**Comment by kramvan1** [comment]
+1
