### ISSUE TITLE
New certificate Makefile missing documentation

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#24192]
`make -f ~/go/src/istio.io/istio/install/tools/certs/Makefile default-certs-selfSigned`

results in 

```
intermediate.conf
key.pem
root-cert.pem
selfSigned-ca-cert-chain.pem
selfSigned-ca-cert.pem
selfSigned-ca-key.pem
selfSigned-cluster-ca.csr
selfSigned-workload-cert-chain.pem
selfSigned-workload-cert.pem
workload.conf
workload.csr
```

These files are not obvious what they are for, as they are not documented and they do not correspond to common file naming in Istio. For example, what is `key.pem`? Is it the ca key or the workload? 

I am trying to add testing for this and cannot figure it out so I assume our users will struggle as well.

It would be very useful to have an explaination of what these are. This may just mean updating https://preliminary.istio.io/docs/setup/install/virtual-machine/ to use the new file names

**Comment by irisdingbj** [comment]
@howardjohn intermediate.conf
key.pem - private key for the workload

will update the docs in master.

**Comment by tanjunchen** [comment]
@irisdingbj  the document is updated?

**Comment by irisdingbj** [comment]
@tanjunchen here is the draft PR: https://github.com/istio/istio.io/pull/7664
