### ISSUE TITLE
rewriteAppHTTPProbe drops startupProbe

### ISSUE THREAD

**Issue by tigran-a** [istio/istio#24203]
**Bug description**
In short, rewriteAppHTTPProbe does not cover startupProbe, but only livenessProbe and readinessProbe 

[X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

[ ] Multi Cluster
[ ] Virtual Machine
[] Multi Control Plane

**Expected behavior**
startupProbe is rewritten the same way as livenessProbe and readinessProbe

**Steps to reproduce the bug**

When:
Set up istio with
 - MTLS enabled,  
 - a namespace is labeled: istio-injection=enabled
 - sidecarInjectorWebhook: has rewriteAppHTTPProbe: true

Having a deployment with http liveness probe, readiness probe and startup probe, after auto-rewriting the deployment, startupProbe disappears.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istioctl version --remote
client version: 1.5.0
control plane version: 1.5.0
data plane version: 1.5.0 (16 proxies)

kubectl: client  1.17 gitversion v1.17.2
server: 1.16 git v1.16.7  commit: e2d9f8... go1.13.6 linux/amd64

**How was Istio installed?**
Manifest
**Environment where bug was observed (cloud vendor, OS, etc)**
AKS

**Comment by howardjohn** [comment]
https://github.com/istio/istio/pull/24440
