### ISSUE TITLE
mixer rules involving headers should auto lowercase the keys

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#2420]
Despite the actual header being say "X-Forwarded-Proto: http"

if you write 

match: request.headers["X-Forwarded-Proto"] == "http"
it doesn't match

As http headers are semantically case insensitive we should auto lowercase or at least document we do lowercase match

**Comment by mandarjog** [comment]
@bianpengyuan Please take this one.
It involves several moving parts.
1. `request.header` is a string map. Default string maps are case sensitive. We need to decide  how to attach extra meaning to a specific string map.
2. In the config, `toLower()` `request.headers` before use.

**Comment by ldemailly** [comment]
this will affect customers

**Comment by kyessenov** [comment]
It's OK to document that keys are envoy-coded as lower-case-with-dashes.

**Comment by kyessenov** [comment]
AI should be to document that keys are envoy-coded. That's better than case insensitive map I think (cheaper on performance side).

**Comment by amitsinha11** [comment]
Istio is forwarding request headers in lower case to pods even when I'm sending with camel casing to my service, what should I do?

**Comment by douglas-reid** [comment]
not stale.

@kyessenov or @bianpengyuan can we add a relevant FAQ entry and then close out this issue?

**Comment by ldemailly** [comment]
how about fixing it in addition to documenting the current behavior ?

**Comment by kyessenov** [comment]
sent an FAQ.
I don't think there is anything wrong with canonicalizing input data. Probably better for security not to special case upper/lower all the time.

**Comment by ldemailly** [comment]
While it's great to document the limitation/bug until it is fixed, not fixing it I believe is a big usability and user experience issue that will trip many people unnecessarily.  Security is not an argument here or rather an argument for fixing it: I may be writing a deny rule based on headers that won't apply because the istio proxy changes the headers - ie I could have add an app with some app code applying a rule and working, when I try to move the rule outside of the code into istio it will stop working because istio (envoy) changes the header behavior wrt to case.

**Comment by kyessenov** [comment]
HTTP does not guarantee casing is _preserved_ in transport. If you send "x: a" on the client, the server should not expect "x: a", since it may very well be "X: a". The application code should take into account that all variants of casing are possible. It happens that Golang has a different canonical form than Envoy. As long as we are clear what makes a canonical form for case-insensitive strings (and we chose Envoy), I think it is pretty clear what Istio rules should be.

**Comment by ldemailly** [comment]
it can be fixed so easily that I wonder why we're arguing about it - do canonalize the rules internally so they work with the implementation without having the user worry/figure out the hard way which it is ? (computer tolower() vs human brain/headache, isn't that what operability and usability is about ?)

**Comment by douglas-reid** [comment]
Unfortunately, there is no work scheduled for enhancements to Mixer (large or small). As this has not been addressed to-date, it is time to close the issue.

**Comment by about-cloud** [comment]
**Although HTTP field names are not case sensitive, it is rude to change upper case to lower case without the permission of the user. Have you considered other case sensitive languages? This deviated from the concept of openness and inclusiveness**
