### ISSUE TITLE
linter failures are ignored by istio-auto-merge-robot

### ISSUE THREAD

**Issue by jmuk** [istio/istio#2421]
I believe that istio-auto-merge-robot *ignores* failures on Circle-CI. Since linters are only running Circle-CI, auto-merging does happen regardless of lint errors.  I see a few lint errors are already merged into master.

The bot should stop auto-merging if lint failures happen.

**Comment by yutongz** [comment]
Nice catch, it is a problem. Can we run linter also in Prow? If I understand correctly, one of the reasons we move to pure go from bazel is to make go linter work. I am a little concern about using circleCI to replace Prow.

**Comment by jmuk** [comment]
I've heard that now cicle-ci is required by auto-merge (cc @chxchx), so effectively this isn't a problem anymore.
It should be pretty easy to run linters in prow though. Just running `./bin/linters.sh`.

**Comment by yutongz** [comment]
https://github.com/istio/test-infra/blob/master/mungegithub/deployment/istio/configmap.yaml#L17

/close
