### ISSUE TITLE
Prometheus annotations doesn't work anymore? 

### ISSUE THREAD

**Issue by ashish235** [istio/istio#24210]
Hi, with 1.6 release, does the annotations to scape application metrics work? If not then what's the the correct way to scrape them?

I am using these annotations in my pod manifest and it's not working. 

```
    prometheus.io/path: /metrics
    prometheus.io/port: "5001"
    prometheus.io/scrape: "true"
```

**Comment by howardjohn** [comment]
Hmm I don't think this should have changed in 1.6. The best way to debug this would be to go to the "targets" page in Prometheus. Then you can see if it's not being matched as a target, if it's failing to scrape, etc

**Comment by howardjohn** [comment]
It would also be useful to indicate if you are using strict mtls or not and how you installed

**Comment by howardjohn** [comment]
You can also try out https://istio.io/docs/ops/integrations/prometheus/#option-2-metrics-merging and the rest of the doc may be useful in general
