### ISSUE TITLE
Docs for configuring istio cert lifetime are incorrect

### ISSUE THREAD

**Issue by XanderStrike** [istio/istio#24221]
**Bug description**

https://istio.io/faq/security/#cert-lifetime-config refers to `workload-cert-ttl` and `max-workload-cert-ttl` which no longer exist as of 1.5, despite the docs supposedly referring to 1.6.

Searching through the code it looks like all mentions of this flag were removed in 1.5, and I believe Citadel itself went away with the istiod migration.

[X] Configuration Infrastructure
[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[X] Developer Infrastructure

**Expected behavior**

Docs correctly explain how to configure certificate lifetime.

**Comment by myidpt** [comment]
This is about out-dated doc clean up. Thanks for spotting it.

**Comment by tcdowney** [comment]
@myidpt @lei-tang 

In the meantime, how does one configure these properties in Istio 1.5+? Is it done through the `DEFAULT_WORKLOAD_CERT_TTL` and `MAX_WORKLOAD_CERT_TTL` environment variables?

**Comment by christian-posta** [comment]
In the meantime, you use SECRET_TTL on the workload's istiod-agent https://github.com/istio/istio/blob/993550ffd4ced016eddbb8e3da7210c784981af6/pkg/istio-agent/sds-agent.go#L107

**Comment by howardjohn** [comment]
fixed
