### ISSUE TITLE
istioctl installation using demo profile times out

### ISSUE THREAD

**Issue by quixoticmonk** [istio/istio#24232]
**Bug description**
istio installation using below commands  results in a timeout error on the grafana.
- `istioctl manifest generate --set profile=demo  > $HOME/generated-manifest.yaml`
- `kubectl apply -f $HOME/generated-manifest.yaml`
**- The stage on a retry completes the installation.**
- istio version : 1.5.4
- K8s version : 1.16

Error messages from the logs:
```
unable to recognize "/root/generated-manifest.yaml": no matches for kind "Policy" in version "authentication.istio.io/v1alpha1"
unable to recognize "/root/generated-manifest.yaml": no matches for kind "Gateway" in version "networking.istio.io/v1alpha3"
unable to recognize "/root/generated-manifest.yaml": no matches for kind "Sidecar" in version "networking.istio.io/v1alpha3"
unable to recognize "/root/generated-manifest.yaml": no matches for kind "EnvoyFilter" in version "networking.istio.io/v1alpha3"
unable to recognize "/root/generated-manifest.yaml": no matches for kind "EnvoyFilter" in version "networking.istio.io/v1alpha3"
Error: Istio installation failed, incomplete or does not match "/root/generated-manifest.yaml" - waiting for deployment "grafana" rollout to finish: 0 of 1 updated replicas are available
```

[X] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
-  Expecting the istio installation into a cluster to manage the timedelays if there are any for individual components.

**Steps to reproduce the bug**
Install istio using the below commands:
- kubectl create ns istio-system --dry-run -o yaml | kubectl apply -f -
- istioctl manifest generate --set profile=demo  > $HOME/generated-manifest.yaml
- kubectl apply -f $HOME/generated-manifest.yaml

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

- Using istioctl 
- istioctl manifest generate --set profile=demo  > $HOME/generated-manifest.yaml
- kubectl apply -f $HOME/generated-manifest.yaml

**Environment where bug was observed (cloud vendor, OS, etc)**
- EKS , kubernetes version 1.16

**Comment by morvencao** [comment]
Is it possible that the issue is caused by the apply order of generated yaml.
You can try to use 
```
istioctl manifest apply --set profile=demo
```

instead of
```
istioctl manifest generate --set profile=demo > $HOME/generated-manifest.yaml
kubectl apply -f $HOME/generated-manifest.yaml
```

The operator will handle apply order for `manifest apply` command to make sure CRDs are created in cluster before creating CRs.

**Comment by quixoticmonk** [comment]
Let me try that and comment back. Question though : does the demo profile related yamls get pulled on the basis of the ISTIO_VERSION by any chance or is it a pull the latest ?

**Comment by morvencao** [comment]
- `istioctl manifest apply` is similar to `istioctl manifest generate` except that it try to apply the generated resources into the cluster.
- For released version, it will pull the ISTIO_VERSION.

**Comment by quixoticmonk** [comment]
Tested this. Can be closed.
