### ISSUE TITLE
TestLDSEnvoyFilterWithWorkloadSelector flake

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#24236]
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/24234/unit-tests_istio/13955

There is a data race

**Comment by adiprerepa** [comment]
I think this also applies to:
`TestLDSWithSidecarForWorkloadWithoutService`
`TestLDS`
`TestLDSWithIngressGateway`
`TestLDSWithDefaultSidecar`
... and many more.

How is this passing in CI? Did we disable it? 
Can others confirm that this isnt passing for them too? Maybe my computer is too slow.

When did this start failing?

**Comment by hzxuzhonghu** [comment]
This is fixed in #24341
