### ISSUE TITLE
NodePort changed after istioctl manifest apply 

### ISSUE THREAD

**Issue by AEGQ** [istio/istio#24245]
**Bug description**

> ### istioctl manifest --log_output_level=debug  apply -f istio.yaml
![image](https://user-images.githubusercontent.com/16302289/83345498-565a0600-a346-11ea-8378-809c818c6c84.png)
> ####  because parameter nodeport not assigned ？

>  ###  NodePort changed after I rerun  "istioctl manifest apply "
![image](https://user-images.githubusercontent.com/16302289/83345526-b2bd2580-a346-11ea-82d2-c017a3473bc9.png)

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

> ### NodePort Don't change 

**Steps to reproduce the bug**
 1、istioctl install

 2、kubectl edit svc -n istio-system  prometheus
> ClusterIP -> NodePort

3、istioctl install
.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
> ![image](https://user-images.githubusercontent.com/16302289/83345519-a33ddc80-a346-11ea-91e1-27f615643920.png)

**How was Istio installed?**

> istioctl install

**Environment where bug was observed (cloud vendor, OS, etc)**

> kubernetes v1.15.12 (virturlbox)

**Comment by sdake** [comment]
nodeport is dynamic. Istio does not deliver any guarantee that services will be exported via a specific nodeport.

Further Istio heavily relies on service type load balancers to expose services (or Istio Ingress in the case of addons such as proemtheus) to avoid this exact issue.

Would you be kind enough to point out the documentation which references the use of nodeport?

Cheers
-steve

**Comment by AEGQ** [comment]
> ### I was testing with the official documents and found this problem.
https://istio.io/docs/setup/getting-started/#determining-the-ingress-ip-and-ports
![image](https://user-images.githubusercontent.com/16302289/83348891-dd1cdc00-a362-11ea-8a3f-e19643bf871f.png)

> ### LoadBalancer -> NodePort
![image](https://user-images.githubusercontent.com/16302289/83349022-17d34400-a364-11ea-824f-8a17aae44a39.png)

> ### istioctl manifest apply -f istio.yaml
![image](https://user-images.githubusercontent.com/16302289/83349032-2a4d7d80-a364-11ea-9fe4-6a55e4ead7b9.png)

**Comment by tanjunchen** [comment]
see https://github.com/istio/istio/issues/22538

**Comment by AEGQ** [comment]
@tanjunchen thanks :)
