### ISSUE TITLE
Unable to create 2 Istio Control Plane using Istio Operator

### ISSUE THREAD

**Issue by sb1975** [istio/istio#24243]
**Bug description**
When I try to create two Istio Control PLane using IStio Operator it does not work.

[ ] Configuration Infrastructure
[X ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

istioctl operator init

 $kubectl create ns istio-system-mobility-gn
 $kubectl create ns istio-system-mobility-oam
 $ kubectl apply -f - <<EOF
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system-mobility-gn
  name: mobility-gn-istiocontrolplane
spec:
  profile: demo
  components:
    pilot:
      k8s:
        resources:
          requests:
            memory: 3072Mi

---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system-mobility-oam
  name: mobility-oam-istiocontrolplane
spec:
  profile: demo
  components:
    pilot:
      k8s:
        resources:
          requests:
            memory: 3072Mi
EOF

$ kubectl get all -n istio-system-mobility-gn
No resources found in istio-system-mobility-gn namespace.

$ kubectl get all -n istio-system-mobility-oam
No resources found in istio-system-mobility-oam namespace.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
$ istioctl version
no running Istio pods in "istio-system"
1.6.0

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:38:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:30:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**

istioctl operator init

**Environment where bug was observed (cloud vendor, OS, etc)**
Ubuntu 18.04
Nested Virtualization enabled VM

**Comment by morvencao** [comment]
By default in-cluster operator just watch iop instance in `istio-system` namespace, you can change this by adding `--istioNamespace=<IOP_NAMESPACE>` to `istioctl operator init` command. Since you 're create iop instances in other namespaces, please try add `--istioNamespace=""` to `istioctl operator init` command, so that in-cluster operator will watch all namespace for iop instance you created.

**Comment by morvencao** [comment]
However, I think it will not work for your case, because the istio components are by default installed in `istio-system` namespace, so there will be some conflict with resources created by different iop instances.

**Comment by ostromart** [comment]
Operator currently cannot watch multiple namespaces, but it will watch multiple IOPs in the designated namespace. Created https://github.com/istio/istio/issues/24682 to track.

**Comment by sb1975** [comment]
@ostromart , first of all appreciate your response, based on the comment for the new issue that you have created : "Currently operator only watches one namespace. The code supports multiple, but only a single one can be passed in via istioctl operator init."

What this means is the Istio Operator will not support 2 or more IOPs (Each creating its own Istio Control Plane).

The issue is closed without addressing the main requirement. :(

**Comment by dgn** [comment]
We're currently discussing this as part of the ongoing multi-tenancy work

**Comment by sb1975** [comment]
https://docs.google.com/document/d/14ZCWMfEV9MPDYrjhKYMErVXHTZrSwJNMm1ztKo8efPw/edit#
Discuss the issue[Sudeep Batra] : https://github.com/istio/istio/issues/24243
Would like 2 different control planes
Wants 2 completely separate service meshes side-by-side in the cluster
ostromart  did write a PR to allow operator to watch different namespaces...but it does not meet the use case of 2 completely separate meshes
Concerned that the whole issue has not been fixed
Reason: each vendor has its own implementation of control plane -- want to share a cluster but have completely different service meshes (different config, lifecycle, etc).
Recommendation: Sudeep come to the Environments Working group meeting (Ericsson)

**Comment by sdake** [comment]
@sb1975 - imo `istioctl operator init` is one of a few approaches you could take. While I tend to agree @ostromart could add functionality to enable multiple IOPs per namespace, if you are interested in investigating a short term solution, you can use helm to deploy two separate operators. I am uncertain if this will work correctly for Istio, I suspect not.

Here is the operator helm chart:
https://github.com/istio/istio/tree/master/manifests/charts/istio-operator

**Comment by ostromart** [comment]
Going over old bugs, I believe this is fully fixed at this time. Operator supports all combinations of multiple CRs in same namespace, watching different namespaces, or multiple operators partitioned to multiple CRs.
