### ISSUE TITLE
cm配置问题

### ISSUE THREAD

**Issue by gongwei0921** [istio/istio#24255]
我测试的是1.6版本，,我想咨询一下，istio-system中的kiali的configmap是不是配置写错了
原配置是
\ grafana:\n    url:  \n    in_cluster_url: http://grafana:3000\n   发现grafana会报警
后面改为\ grafana:\n    url:  \n    in_cluster_url: http://grafana.istio-system:3000\n 就可以获取数据了。。。。
以下为谷歌翻译：
I tested version 1.6, and I want to ask if the configuration of kiali in istio-system is wrong.
The original configuration is
\ grafana: \ n url: \ n in_cluster_url: http: // grafana: 3000 \ n Find grafana will alarm
Then change to \ grafana: \ n url: \ n in_cluster_url: http: //grafana.istio-system: 3000 \ n to get the data. . . .

**Comment by helight** [comment]
You should use English here.

**Comment by howardjohn** [comment]
Can you reopen in english? Thanks!
