### ISSUE TITLE
Probe rewrite fails if path does not start with "/"

### ISSUE THREAD

**Issue by piotrmsc** [istio/istio#24260]
**Bug description**

If you define livness probe where path does not start with `/` istio-proxy fails to rewrite probe requests from kubelet with en error :  
```
error	Failed to create request to probe app parse "http://localhost:8001foo": invalid port ":8001foo" after host, original url /app-health/liveness-http/livez
```

[x] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Probe rewrite succeeds, container does not get restarted.
According to [k8s](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#httpgetaction-v1-core) path does not need to start with `/`. Without sidecar it works, kubelet handles such requests.
 
**Steps to reproduce the bug**
I have used livness-http example from probe rewrite docs, but I've modified the path : 

```apiVersion: v1
kind: Service
metadata:
  name: liveness-http
  labels:
    app: liveness-http
spec:
  ports:
  - name: http
    port: 8001
  selector:
    app: liveness-http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: liveness-http
spec:
  selector:
    matchLabels:
      app: liveness-http
      version: v1
  template:
    metadata:
      labels:
        app: liveness-http
        version: v1
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      containers:
      - name: liveness-http
        image: docker.io/istio/health:example
        ports:
        - containerPort: 8001
        livenessProbe:
          httpGet:
            path: foo
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 5
```
**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```istioctl version --remote                                                                                                                                                                                     
client version: 1.6.0
cluster-local-gateway version:
pilot version: 1.6.0
data plane version: 1.6.0 (5 proxies)
```

**How was Istio installed?**
`istioctl manifest apply --set profile=demo --set values.global.mtls.enabled=true  --set values.gateways.istio-ingressgateway.sds.enabled=true --set values.sidecarInjectorWebhook.rewriteAppHTTPProbe=true`

**Environment where bug was observed (cloud vendor, OS, etc)**
GCP

**Comment by esnible** [comment]
Discussion for @piotrmsc and @istio/wg-user-experience-maintainers 

I propose Istio treat `foo` as `/foo`.

That seems better than skipping the rewrite or trying to block the deployment with a validation.

Thoughts?

**Comment by howardjohn** [comment]
Interesting, does k8s implicitly add a `/`? if so we should of course do the same

**Comment by piotrmsc** [comment]
In general, it's a minor, if you have control over resources applied it's easy to add this `/`. I found it when running dapr and its sidecar, dapr sidecar injector does not provide this [slash](https://github.com/dapr/dapr/blob/master/pkg/injector/pod_patch.go#L423), however, IMO it's not a bid deal to change it ;-) I will ask them about it. 

@howardjohn  When it comes to kubelet, after [parsing url](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/prober/prober.go#L175)  missing `/` is added.

👍 for me to adopt this in istio like @enis mentioned.

**Comment by howardjohn** [comment]
https://github.com/istio/istio/pull/24412
