### ISSUE TITLE
EnvoyFilters not working for istio v1.6.0

### ISSUE THREAD

**Issue by Prashansa-K** [istio/istio#24266]
I made a simple Envoy Filter which was working for v1.5.4
When I downloaded the new release of istio 1.6.0, the same filter stopped working. The docs of both the versions show no difference in configuring envoy filters.

Need urgent help on this.

**Comment by ramaraochavali** [comment]
Please share your Envoy filter possible. Please note Envoy Filter are not guaranteed to work across depending on how they are written. Please refer to NOTE1 in this doc https://istio.io/docs/reference/config/networking/envoy-filter/

**Comment by Prashansa-K** [comment]
`apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: payload-check
spec:
  filters:
  - listenerMatch:
      listenerType: SIDECAR_INBOUND
      listenerProtocol: HTTP
    filterName: envoy.lua
    filterType: HTTP
    filterConfig:
      inlineCode: |
        function envoy_on_request(request_handle)
          local body_size = request_handle:body():length()
          if body_size > 1000 then  
              request_handle:respond({[":status"] = "413"},"Request Body Too Large")
          end
        end`

**Comment by howardjohn** [comment]
You are using deprecated fields in Envoyfilter. Please upgrade following https://istio.io/docs/reference/config/networking/envoy-filter/ docs for info

**Comment by Prashansa-K** [comment]
I have upgraded the envoy filter script as per latest version. 
Few more queries:
1) Why did a minor version upgrade break the backward compatibility? 
2) Will this happen with future upgrades too - New minor upgrades would need change in envoy filter changes?

**Comment by ramaraochavali** [comment]
> Why did a minor version upgrade break the backward compatibility?

1.5.4 -> 1.6.0 , Envoy proxy has been upgraded which removed support for deprecated fields. 

> Will this happen with future upgrades too - New minor upgrades would need change in envoy filter changes?

This would not typically happen for every Istio release. But as I mentioned earlier, it is better to test envoy filters before you rollout to production after upgrade.

**Comment by dev-cr-ka** [comment]
Would be a good idea, to throw an exception if deprecated fields are in use. Currently the filter is created but doesn't work without any warning.

**Comment by howardjohn** [comment]
@esnible I thought `istioctl validate` would warn on deprecated fields. Is that incorrect, or it is in general but we haven't properly annotated these as deprecated somewhere?

**Comment by esnible** [comment]
@howardjohn 
Neither `istioctl validate` nor `istioctl analyze` detect the current deprecated EnvoyFilter fields.

There is an Issue for this: https://github.com/istio/istio/issues/24743 .  If it deserves attention help me target it.

You removed the EnvoyFilter deprecation warnings in https://github.com/istio/istio/commit/7792cef71c2f20cc1800a78667a3fff7fea5802c#diff-451241f3c7d83ec589390e95c2d2b90a

**Comment by howardjohn** [comment]
Closing in favor of https://github.com/istio/istio/issues/24743 - will move discussion there
