### ISSUE TITLE
Upgrade from 1.4.9 to 1.5.4 Left egress gateway on 1.4.9

### ISSUE THREAD

**Issue by adamcarter81** [istio/istio#24262]
Maybe not so much of a bug report but a request for understanding / assistance - I upgraded Istio from 1.4.9 to 1.5.4 but it left the egress-gateway on 1.4.9:

![image](https://user-images.githubusercontent.com/17292024/83410733-da77c080-a40e-11ea-9758-7d854740d6e9.png)

I am trying to work out how to upgrade just this component to 1.5.4 - can anyone assist me to troubleshoot?

Apologies, I am new to Istio and this is my first upgrade, so I'm trying to learn rapidly..

Thanks

**Expected behavior**
All components upgrade and show the same version

**Steps to reproduce the bug**
Install 1.4.x upgrade to to 1.4.9, upgrade to 1.5.4

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**
pass - inherited system
I believe with istioctl and specifying a basic manifest file which I have

**Environment where bug was observed (cloud vendor, OS, etc)**
Azure

**Comment by adamcarter81** [comment]
I think if my understanding is correct - it got installed in the upgrade / deployment 1.4.9, but then is not specified in the 1.5.4 - so I should be good to delete everything related to it (we don't use it, and it is only a lab environment)

**Comment by esnible** [comment]
Istio doesn't remember the IstioOperator or `--set` options used when Istio was installed.

It is best if you install Istio using an IstioOperator YAML to describe the optional features you desire.  Re use that YAML file when upgrading.  In a punch you can install with `--set values.gateways.istio-egressgateway.enabled=true` to get an Egress installed.

Istio's philosophy is that admins should install Istio in an explicitly declared way and not have the same command behave differently depending on previous installs.  Sometimes people do forget how they installed, and https://github.com/istio/istio/issues/23443 is where we are discussing how to make `upgrade` support preserving the options used by previous installs in a safe way.

**Comment by adamcarter81** [comment]
Thank you! This makes sense - one suggestion could be to dump out the declaration used to install, or the current running declaration of enabled components to be used to declare for the upgrade?

Anyway, I deleted it as we weren't using it - but thank you for the clarification

**Comment by howardjohn** [comment]
Closing since this is resolved and action to improve this is tracked in https://github.com/istio/istio/issues/23443. Thanks for the feedback!
