### ISSUE TITLE
"istioctl profile dump" new output format "--output=flags"

### ISSUE THREAD

**Issue by esnible** [istio/istio#24271]
This is an idea.  If more details are needed I will write it up as an RFC.

Currently `istioctl profile dump` only supports JSON and YAML output.  Neither works well with grep, and neither makes it easy to see how to set options.

I propose that `istioctl profile dump --output=flags` produce values that can be passed to `istioctl install --set <x>`  This would let me do things like

```
istioctl profile dump --output=flags | grep egress
components.egressGateways.enabled=true
components.egressGateways[0].k8s.resources.requests.cpu=10m
components.egressGateways[0].k8s.resources.requests.memory=40mi
components.egressGateways[0].name=istio-egressgateway
values.gateways.istio-egressgateway.autoscaleEnabled=false
values.gateways.istio-egressgateway.name=istio-egressgateway
values.gateways.istio-egressgateway.secretVolumes.mountPath=/etc/istio/egressgateway-certs
values.gateways.istio-egressgateway.secretVolumes.name=egressgateway-certs
values.gateways.istio-egressgateway.secretVolumes.secretName=istio-egressgateway-certs
values.gateways.istio-egressgateway.type=ClusterIP
```

(Alternately we could use "config-path" or some other word instead of "flags".)

cc @ostromart

**Comment by esnible** [comment]
This would also be useful for `istioctl profile diff`

Related: https://github.com/istio/istio/issues/23443#issuecomment-632665043 which describes basically do things for the diff between a profile and an installed IstioOperator.

**Comment by esnible** [comment]
IDEA: Example of using `istioctl profile diff` with `--output=flags` to see how Istio was installed:

```
istioctl profile diff <$(kubectl -n istio-operator get istiooperator master) <$(istioctl profile dump default) --output=flags
hub=gcr.io/istio-testing
tag=latest
values.global.imagePullPolicy=Always
components.telemetry.enabled=true
```

I could also imagine shorthand: `istioctl profile diff --profile-from-cluster --builtin-profile`.

Also `istioctl profile diff --profile-from-cluster=canary --builtin-profile=demo`

**Comment by ostromart** [comment]
SGTM. Hopefully we can do it without yet another tree traversal implementation :-)
