### ISSUE TITLE
Telemetry V2 Metrics Missing

### ISSUE THREAD

**Issue by bdschaap** [istio/istio#24278]
I installed Istio 1.5.4 using the demo profile but was unable to find any Istio metrics in Prometheus such as istio_requests_total. 

istioctl manifest apply --set profile=demo

However, when I revert to the Mixer based Telemetry then I'm able to find those metrics.

Are those metrics still available in Telemetry V2?

**Comment by douglas-reid** [comment]
@bdschaap those metrics are available in v2. did your install include an envoyfilter named stats-filter-1.5 in the istio-system namespace ?

**Comment by bdschaap** [comment]
Yes I see that EnvoyFilter.  I have tried on both minikube (K8s 1.14.7) and AKS (K8s 1.15.11).  

```
kubectl get envoyfilter -n istio-system

NAME                        AGE
metadata-exchange-1.4       151m
metadata-exchange-1.5       151m
stats-filter-1.4            151m
stats-filter-1.5            151m
tcp-metadata-exchange-1.5   151m
tcp-stats-filter-1.5        151m
```

Is the envoy-stats job supposed to scrape those metrics?  I noticed that the istio-mesh job scraped them when I reverted to Telemetry v1.

**Comment by douglas-reid** [comment]
Yes. The `envoy-stats` job should be pulling in those metrics.

**Comment by douglas-reid** [comment]
We have full integration tests for v2 telemetry, both null vm and wasm. v2 has been the default since 1.5. Without more information, I'm not sure how to make progress on this issue. Closing for now.
