### ISSUE TITLE
Pilot-agent should not restart Envoy if encryption is disabled

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#2427]
Pilot-agent should not restart Envoy if encryption is disabled, even if istio-ca is present and certificates are refreshed. Until support for SDS istio/istio#2120 will make envoy restart completely unnecessary, we need to fix this, and update the workaround in istio/istio.github.io#835.

Istio currently supports both encrypted and un-encrypted services in the same cluster. Users should not have to manually disable istio-ca and in turn affect their encrypted services, just to have their un-encrypted services work.

**Comment by kdillane** [comment]
Not sure if this is related to Envoy restarts, but we see some periodic increase in latency across our cluster when Istio-CA is running: https://github.com/istio/issues/issues/138.  Does Istio-CA only cause Envoy to restart when encryption is toggled, or when a "certificate refresh" is executed?

**Comment by andraxylia** [comment]
Right now Envoy restarts every time a certificate is refreshed, regardless of encryption, and this is a bug.

**Comment by kdillane** [comment]
Is it anticipated that an Envoy restart would cause 500s in the cluster?

We saw this issue related to Istio-CA where every hour a spike of 500s would occur (along with increased latency).  If this is caused by Envoy restarting, that's a big concern for availability.

**Comment by andraxylia** [comment]
Let's follow up on the latency in istio/istio#2090.
 @ldemailly can we measure the penalty introduced by Envoy restart?

**Comment by myidpt** [comment]
This is a dup of https://github.com/istio/issues/issues/169. It should be fixed by https://github.com/istio/istio/pull/2761.

**Comment by andraxylia** [comment]
It's viceversa.
