### ISSUE TITLE
Provide extension distribution mechanism design and implementation

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio#24281]
**Describe the feature request**
Need support for Wasm-based extensions distribution.

[ X ] Policies and Telemetry

**Comment by bianpengyuan** [comment]
@kyessenov Are we still aiming 1.8 for ecds based extension distribution?

**Comment by kyessenov** [comment]
@bianpengyuan It's unlikely to make it 1.8. There are more challenges now with xDS proxying and not having xDS dedicated endpoints in pilot. See https://github.com/istio/istio/pull/27686

**Comment by bianpengyuan** [comment]
We now have a extension distribution mechanism now: https://istio.io/latest/docs/ops/configuration/extensibility/wasm-module-distribution/

Tentatively close this. Please reopen if you think there are other work that needs to be tracked here.
