### ISSUE TITLE
Finalize approach on Tracing/Logging APIs

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio#24287]
In 1.6, we introduced some tracing controls as part of MeshConfig. We need to complete the work to support annotations and decide if we want this to be the primary API mechanism.

[ X ] Policies and Telemetry

**Comment by nrjpoddar** [comment]
Extensions API is currently orthogonal to the tracing API, as extensions only configure extra filters where as tracing settings are embedded within HCM. Our options to mature this API are:

* Use EnvoyFilter
* Keep using MeshConfig like we have in 1.6
* Add yet another API to only configure tracing
* Augment extensions API proposal to also configure built-in HCM filters.

@douglas-reid @mandarjog does that sound right?

**Comment by douglas-reid** [comment]
I'd expand your third option to at least include access logging (not only tracing). @bianpengyuan had suggested in earlier conversations that this could even include rate-limiting.

We should also think about how we could incorporate bootstrap aspects into whatever API we land on.

I wonder how much of the Wasm API layering discussion is also relevant here.

**Comment by bianpengyuan** [comment]
Yeah, I am viewing this as an opportunity to promote highly demand xds patches that user typically do via envoyfilter to first class citizen API, which only only including tracing, logging, but also extern authz, rate limiting, and default metric classification & configuration (https://github.com/istio/istio/issues/24286). All these seem to be general enough to have specialized API.

**Comment by howardjohn** [comment]
Telemetry API is now "v1". Yay
