### ISSUE TITLE
Design long-term Telemetry APIs

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio#24284]
Epic: Design long-term Telemetry APIs

**Comment by ryantking** [comment]
Moving to 1.12 milestone due to inactivity

**Comment by douglas-reid** [comment]
@Kmoneal yes. we've been continually working on this. we expect to have some features in 1.12, and "full" support in 1.13, then follow the feature promotions process.

**Comment by howardjohn** [comment]
These are shipped
