### ISSUE TITLE
"istioctl manifest generate" panic on invalid index

### ISSUE THREAD

**Issue by esnible** [istio/istio#24291]
To reproduce, using 1.6.0, `istioctl manifest generate --set components.ingressGateways[-1].name=dummy`

1.5.x is also affected.  1.4.6 gives a "bad path error".

**Comment by adiprerepa** [comment]
So the expected behavior is to display an error? On it.

**Comment by adiprerepa** [comment]
On istioctl 1.5.4, any negative index other than -1 gives bad path, but -1 gives a panic?

**Comment by esnible** [comment]
@adiprerepa I see the same as you, -1 gives panic on 1.5.x, 1.6.x, and master.  -2 is fine.

There may be special case handling in Istio or Go to make `[-1]` mean "append".  It may be that code is broken.  I have not looked at this code recently.

cc @ostromart

**Comment by esnible** [comment]
@adiprerepa Do you want me to assign this issue to you?

**Comment by adiprerepa** [comment]
@esnible yes please. I'll work on it this today.

**Comment by adiprerepa** [comment]
@esnible sorry, how do you run istioctl on master? do you build it locally?
