### ISSUE TITLE
Sample addons: add istio-system namespace

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#24294]
Currently `-n istio-system` must be passed when installing the sample addons because of references in the objects. We should just make this hardcoded. This cannot be done as part of the helm install so we can post-process it.

**Comment by howardjohn** [comment]
part of https://github.com/istio/istio/issues/23583

**Comment by shamsher31** [comment]
Must be fixed by https://github.com/istio/istio/pull/26072 and https://github.com/istio/istio.io/pull/7847 ?
