### ISSUE TITLE
Citadel managed secret formats are not supported in Gateway resource

### ISSUE THREAD

**Issue by nrjpoddar** [istio/istio#24292]
**Bug description**

Citadel managed certificates for mTLS have `cert-chain.pem`, `key.pem` & `root-cert.pem` as keys in the secrets which is not one of the supported formats as described [here](https://istio.io/docs/tasks/traffic-management/ingress/secure-ingress/#configure-a-mutual-tls-ingress-gateway).

This is the list of Gateway supported formats:

* A TLS Secret with keys tls.key and tls.crt, as described above. For mutual TLS, a ca.crt key can be used.
* A generic Secret with keys key and cert. For mutual TLS, a cacert key can be used.
* A generic Secret with keys key and cert. For mutual TLS, a separate generic Secret named <secret>-cacert, with a cacret key. For example, httpbin-credential has key and cert, and httpbin-credential-cacert has cacert.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Users can use the Citadel generated secrets for Gateway resources.

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
Versions 1.5 and earlier.

**How was Istio installed?**
N/A

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by nrjpoddar** [comment]
cc @jacob-delgado @cyran-ryan

**Comment by nrjpoddar** [comment]
The use case here is customer's want to use DNS certificates minted by Citadel using existing capabilities in 1.5/16. The customer wants to use Citadel as CA and wants to connect legacy clients which don't understand SPIFFE certificates via Ingress GW.

This needs to be cherry-picked in release-1.5/release-1.6. Thanks!

**Comment by costinm** [comment]
If we fix it in older versions ( and I think it's reasonable to do so ): the safest fix is to change the code that generates the secret to save the private key and cert twice, so both old and standard names are present in the cert. 

It would be great to do the same thing for the self-generated root CA - so it can be used as a Issuer in CertManager for full flexibility

**Comment by incfly** [comment]
/cc @myidpt @JimmyCYJ 
we don't have secret mount as file anymore, why we need to add this to gateway?

**Comment by incfly** [comment]
oh i see, customers are using DNS certificate in gateway and using citadel to mint that. I don't think we are planning to support that. @costinm suggestion is better IMO.

@myidpt please chime in a

**Comment by incfly** [comment]
And why this requires to be cherrypicked to 1.5/1.6? I don't think it's a regression or bug fix, right?

**Comment by nrjpoddar** [comment]
@incfly it's a bug or oversight to be honest so it's worth patching in earlier releases. We will make sure that the implementation is backwards compatible i.e. preserve old secret keys and add news ones.

**Comment by costinm** [comment]
Let's fix it in master first -we can backport or not, separate issue. 

While we do have a solution now with Istiod - there are still use cases for provisioning certs for Gateway. We may 
want to terminate the Istiod connection in gateway, and route based on version, or still allow users to have only one revision
of istiod with access to the 'master CA'.

What we have now with each Istiod revision generating its own DNS certs by accessing the root CA is clearly not ideal, just simple and convenient.
