### ISSUE TITLE
Performance with Lots of Incoming SSE Connections

### ISSUE THREAD

**Issue by webercoder** [istio/istio#24307]
We’re planning to deploy a service to our mesh that will serve 1 million+ concurrent, persistent SSE connections. During initial load testing, our sidecars died with out-of-memory errors after handling around 100 connections each under the default sidecar resource allocation and pretty light load.

While we can increase our sidecar resources with annotations (thanks for #22395 and hopefully eventually #23053), we’re wondering if it might be better to deploy this particular service outside the mesh.

Have you guys heard of anybody deploying a similar service in their mesh with a high number of persistent SSE connections, or any type of persistent TCP connections? Very interested in your thoughts, thanks.

**Comment by howardjohn** [comment]
cc @mandarjog @lambdai

**Comment by lambdai** [comment]
What are the protocol you are using?
Under light load, each connection in envoy uses under 20k memory usage at user space. Per sidecar has limitation in terms of the number of connections, limited by ephemeral ports range. However, we sdhould not see OOM.

I see no reason to OOM a sidcar proxy under light load. The light load is to exclude the possibility that sidecar proxy is buffering payload. Can you confirm the memory usage following https://github.com/istio/istio/wiki/Analyzing-Istio-Performance#memory ?

**Comment by webercoder** [comment]
Thank you for the response. Apologies but there was a miscommunication on our end. We only start seeing instability at **~1000** connections, not 100, and we start getting OOM errors at ~1300 connections. 

That still seems low given that 1300 * 20k per connection = ~26MiB and the default proxy memory limit is 128MiB. I'll run the suggested memory performance command and get back to you guys, thanks.
