### ISSUE TITLE
Support customization of buckets for distributions

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio#24303]
Istio prom stats filter currently does not support customization of buckets used. We need to add support for customizing how distributions are bucketized.

[ X ] Policies and Telemetry

**Comment by douglas-reid** [comment]
Not stale.

**Comment by douglas-reid** [comment]
not stale

**Comment by zirain** [comment]
e2e test can be found [here](https://github.com/istio/istio/pull/43032), need a user face doc.

**Comment by zirain** [comment]
fixed by https://github.com/istio/istio/pull/45368
