### ISSUE TITLE
Document Prometheus Alerting and HPA

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio#24310]
We should provide documentation on how to use the Istio service and control plane metrics for:

- alerting
- horizontal pod autoscaling

[ X ] Policies and Telemetry
[ X ] User Experience

**Comment by fktkrt** [comment]
Regarding alerting, I'm currently experimenting alerting on the following ones:

- Istio components availability 
- Increased push errors (to detect STALE and NOT SENT proxy-statuses, or is there a better way?)
- `istio_requests_total` increase/decrease
- Increased `istio_requests_total` 4xx/5xx errors

Should be more covered additionally?
Are you planning to incorporate Prometheus alerting rules as well?

**Comment by douglas-reid** [comment]
@fktkrt those sound like a decent first start. For the alerting part, the primary goal is to have documentation on useful Prom alerting rules for both mesh metrics and control plane metrics. There have been several threads on places like discuss.istio.io that mention some alert rules that various users have found useful. I'd like to collect those in an intentional way to add as production guidance on the istio.io site.

Perhaps the first step would be to start a doc in the community drive that we could circulate for input, etc. ?

**Comment by fktkrt** [comment]
After browsing trough the drive, it should be under Working Groups / Policies & Telemetry, right?
Is there any templates to compose an initial version for such a brainstorming?

**Comment by fktkrt** [comment]
@douglas-reid I've started to compose a document for brainstorming on this matter, how can I add it to the aforementioned folder?

**Comment by douglas-reid** [comment]
All that should be required is to create the document and then move it into the folder, via the docs menu. I believe anyone that has access to that drive should be able to do it.

**Comment by fktkrt** [comment]
As discussed in private, the brainstorming is available here: https://docs.google.com/document/d/1VFoHfL0ZzeNx0hv3b1NM9pMccpXB043ScFMgHt2aPsE/edit?skip_itp2_check=true#heading=h.szb2apn7cyd

Could you please advertise it to reach a broader audience?

**Comment by fktkrt** [comment]
Just added some example expressions and cleaned up the docs a bit. Could you please review them?
Tagging @howardjohn, as he had some comments already there.

**Comment by fktkrt** [comment]
Can we re-open this?
I think basic maintained rules could be really useful as a starting point for others.
