### ISSUE TITLE
Istio-release 1.7 istioctl installation got unknown field "enabled" in v1alpha1.SDSConfig 

### ISSUE THREAD

**Issue by carolynhu** [istio/istio#24315]
This occurs on May 31st master builds. Before that day, all things are running well.

Here is the error log:

```
+ /home/prow/go/src/istio.io/tools/perf/istio-install/tmp/istio-1.7-alpha.709dcf449c838d56071cf4a27e7dbd530937d1c0/bin/istioctl manifest apply --skip-confirmation -d /home/prow/go/src/istio.io/tools/perf/istio-install/tmp/istio-1.7-alpha.709dcf449c838d56071cf4a27e7dbd530937d1c0/manifests -f istioctl_profiles/default-overlay.yaml
Error: failed to apply manifests: validation errors (use --force to override): 
unknown field "enabled" in v1alpha1.SDSConfig
```

**Comment by carolynhu** [comment]
cc @JimmyCYJ you might know something changes in SDS side?

cc @esnible @ostromart

**Comment by esnible** [comment]
I can reproduce this using master but not 1.6.0:

```
istioctl manifest generate -f ../tools/perf/istio-install/istioctl_profiles/default-overlay.yaml
Error: validation errors (use --force to override): 
unknown field "udsPath" in v1alpha1.SDSConfig
```

**Comment by howardjohn** [comment]
These fields have been removed as they are now obsolete. SDS is always enabled now, and cannot be disabled

**Comment by carolynhu** [comment]
@howardjohn yes, compared with the master default.yaml profile https://github.com/istio/istio/blob/master/manifests/profiles/default.yaml there is not those fields. I'm going to remove them in the overlay yaml. Thanks!

**Comment by howardjohn** [comment]
we removed it yesterday

**Comment by carolynhu** [comment]
i see, by git blame, it shows to me 7 months ago...

**Comment by esnible** [comment]
@carolynhu Those fields were added back six months ago:
https://github.com/istio/tools/commit/16d007a6a0c303c81617d74cfd9b66f21247e4e7#diff-9c8d366ba43060e97fdd28ffe065a3c8R152

**Comment by carolynhu** [comment]
Yea, Thanks @esnible !  I removed then now.
