### ISSUE TITLE
istioctl manifest apply : Asset profiles/default.yaml not found

### ISSUE THREAD

**Issue by shamsher31** [istio/istio#24323]
**Bug description**
In master: running `istioctl manifest apply` throws error.
```
$ $GOPATH/src/istio.io/istio/out/linux_amd64/istioctl manifest apply
This will install the default Istio profile into the cluster. Proceed? (y/N) y
Error: failed to apply manifests: Asset profiles/default.yaml not found
```

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Should install istio successfully.

**Steps to reproduce the bug**
on master build
$ make build

Run `istioctl manifest apply` 

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.7.0

**How was Istio installed?**
1) $ istioctl manifest apply
2) $ $GOPATH/src/istio.io/istio/out/linux_amd64/istioctl manifest apply
3) Press Y

**Environment where bug was observed (cloud vendor, OS, etc)**
minikube version: v1.9.2
kind v0.8.1
Red Hat Enterprise Linux release 8.0 (Ootpa)
Linux 4.18.0-80.11.2.el8_0.x86_64 x86_64

**Comment by erdun** [comment]
You should run `BUILD_WITH_CONTAINER=0 make gen-charts` before making binary.

Charts will compile to code when releasing

**Comment by shamsher31** [comment]
Thanks @erdun , I tried with `BUILD_WITH_CONTAINER=0 make gen-charts` and `istiod` failed and Ingress gateways stuck...

```
$ BUILD_WITH_CONTAINER=0 make gen-charts
$ make build

$ $GOPATH/src/istio.io/istio/out/linux_amd64/istioctl manifest apply
This will install the default Istio profile into the cluster. Proceed? (y/N) y

Detected that your cluster does not support third party JWT authentication. Falling back to less secure first party JWT. See https://istio.io/docs/ops/best-practices/security/#configure-third-party-service-account-tokens for details.

✔ Istio core installed                                                                           
✘ Istiod encountered an error: failed to wait for resource: resources not ready after 5m0s: timed out waiting for the condition
Deployment/istio-system/istiod
✔ Addons installed                                                                               
- Processing resources for Ingress gateways. Waiting for Deployment/istio-system/istio-ingress..
```

**Comment by shamsher31** [comment]
The error message is not really helpful and does not indicate what to do next.
```
Error: failed to apply manifests: Asset profiles/default.yaml not found
```
Previously, I used to get this message.
```
Error: failed to apply manifests: failed to generate manifest: 
compiled in charts not found in this development build, 
use --charts with local charts instead or run make gen-charts
``` 
Ref: https://github.com/istio/istio/issues/23135

**Comment by esnible** [comment]
Agreed this is a problem.

First, when you compile yourself, things get compiled in that aren't pullable.  If you compile istioctl yourself, you can do
```
~/go/src/istio.io/istio/out/darwin_amd64/istioctl manifest apply \
   --set hub=gcr.io/istio-testing \
   --set tag=latest
```

Also this works:
```
export HUB=docker.io/istio
export TAG=1.6.0
istioctl manifest apply --set hub=$HUB --set tag=$TAG
```

@ostromart The message `Error: failed to apply manifests: Asset profiles/default.yaml not found` is not making sense to developers who compile _istioctl_ themselves.

- Can we restore the error message from @shamsher31 's comment?
- If the directory _profiles_ doesn't exist should we use _manifest/profiles_ or _$GOPATH/src/istio.io/istio/manifest/profiles_ instead?

**Comment by howardjohn** [comment]
@esnible once the error message is fixed, you will pass --charts or compile in the profiles. Either of those will make the `missing default.yaml` error go away I think. So the issue is just we hit that error before we hit the "compiled in charts" warning

**Comment by shamsher31** [comment]
Closed by https://github.com/istio/istio/pull/24744
