### ISSUE TITLE
"istioctl version" to use XDS events instead of /debug

### ISSUE THREAD

**Issue by esnible** [istio/istio#24331]
Currently _istioctl_ does the equivelement of

```
kubectl -n istio-system exec deployment/istiod -- /usr/local/bin/pilot-discovery version
version.BuildInfo{Version:"d3f90d30af70e81fb1a1de57fd0b7ebdd97010fc", GitRevision:"d3f90d30af70e81fb1a1de57fd0b7ebdd97010fc", GolangVersion:"go1.14.2", BuildStatus:"Clean", GitTag:"1.6.0-alpha.2-284-gd3f90d30a"}
```

In the old Microservices version it used other commands.  We don't check the IngressGateway version, so Istiod is the only one used today for control plane version.

For data plane version we use `/debug/syncz`.  That will be replaced by typeURL `istio.io/connections`.

**Comment by howardjohn** [comment]
Not sure how XDS events handles this? You should just call `:15014/version` on pilot and then `istioctl ps` already handles the sidecar versioning right? Then we can just stop caring about legacy stuff like mixer since its going away

**Comment by howardjohn** [comment]
15014 won't be exposed in the Service so probably cannot reach it. I am not sure XDS has a way to encode metadata about the server in the response which would be useful here

**Comment by howardjohn** [comment]
I don't think there is a concept of "peer istiods" today. What does it mean to be a peer to someone? is istiod in another cluster a peer? In another revision?

**Comment by esnible** [comment]
_[XDS Event reporting](https://docs.google.com/document/d/1X7DmkP10x4nEcTGpikxmvLbBTTK59B0WL3liQzVy8Ms/edit# )_ section "Aggregation of events" has a picture of Three Istiod in a cloud.  It says "An Istiod instance will have a connection to all other instances in the same network or reachable VMs"

When I say "peer Istiods" I am thinking of that.  I imagine myself as admin of a K8s cluster with an Istio Deployment with two Istiod pods, both on version 1.7.1, and a second Deployment on the same Service on version 1.7.2-snible-build.  Example: 50 Sidecars are connected to istiod-99db899b5-nfxk6, 49 sidecars are connected to istiod-99db899b5-abcde, and 48 sidecars on istiod-0123456789-012345.

Perhaps cloud providers don't want to reveal the number of Istiod instances they are using to serve XDS for a customer.  We can re-envision how `istioctl version` works.  For example:

```
$ istioctl version
Your istioctl supports Istio https://istio.io/
Your Istio provider supports Istio https://archive.istio.io/v1.5/
You are running
- 97 sidecars supporting https://archive.istio.io/v1.5/
- 1 sidecar supporting https://archive.istio.io/v1.4/
```

Currently when I run `istioctl version` this is what I get:
```
$ istioctl version
client version: 1.6.0
control plane version: d3f90d30af70e81fb1a1de57fd0b7ebdd97010fc
data plane version: 1.7-dev (8 proxies)
```

Do you think that any of those fields should be deprecated from the output of `version`?  Should anything be added?
