### ISSUE TITLE
Add Telemetry e2e tests with CNI

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio#24337]
Need tests that validate telemetry function in CNI scenarios.

[ X ] Policies and Telemetry

**Comment by jwendell** [comment]
@douglas-reid Is this a dupe of https://github.com/istio/istio/issues/23867 ?

**Comment by douglas-reid** [comment]
@jwendell it looks like it. good find. I was adding issues quickly to match 1.7 roadmap. I'll close this one and use the existing one.
