### ISSUE TITLE
Improve UX of getting needed metadata in place for VMs

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio#24350]
For telemetry, we have a need to get a bunch of "extra" information in place for VMs, including mesh uids, owner info, canonical service labels, etc. We need a better workflow that manual updates per install. We also need one that is flexible for different VM envs (not just GCP).

[ X ] Configuration Infrastructure
[ X ] Policies and Telemetry
[ X ] User Experience
[ X ] Virtual Machine

**Comment by howardjohn** [comment]
Is this manual? Or automated from metadata servers?

FWIW we do already have existing environment variables (can be set normally or via sidecar.env) and files we grab labels from. So we just need a good UX for the user to stick stuff there

**Comment by douglas-reid** [comment]
@howardjohn yes, right now there are some manual components -- would be great if this went hand-in-hand with WorkloadEntry and other metadata servers (fetch mesh id in the agent and make it an env?). and yes, we have some mechanisms to take the information once it is in the right places. this is about making getting it in the right places easy (as you note).

**Comment by esnible** [comment]
Is this in plan for 1.7?

**Comment by douglas-reid** [comment]
It is actively being worked, but I'm nervous about completion for 1.7.

**Comment by bianpengyuan** [comment]
@douglas-reid is this addressed by https://github.com/istio/istio/pull/25892 Or it there any thing more that we'd need to address here?

**Comment by douglas-reid** [comment]
I think the P0 for 1.8 has been met.
