### ISSUE TITLE
Add integration test for request classification

### ISSUE THREAD

**Issue by bianpengyuan** [istio/istio#24358]
In 1.6 we introduces request classification as an experimental feature: https://istio.io/docs/tasks/observability/metrics/classify-metrics/. An integration test needs to be added to cover that feature. It will also cover metric customization feature as well https://istio.io/docs/tasks/observability/metrics/customize-metrics/.

xref: https://github.com/istio/istio/issues/20369

**Comment by bianpengyuan** [comment]
The test has already been added as unimplemented: https://github.com/istio/istio/blob/153b6f6bf1ba7407062a545a8ac403538540ede9/tests/integration/telemetry/requestclassification/requestclassification_test.go#L29 This tracks implementation for that.

**Comment by bianpengyuan** [comment]
cc @jgkogan

**Comment by howardjohn** [comment]
https://github.com/istio/istio/blob/1aca7a67afd7b3e1d24fafb2fbfbeaf1e41534c0/tests/integration/telemetry/stats/prometheus/customizemetrics/customize_metrics_test.go
