### ISSUE TITLE
missing racetest target

### ISSUE THREAD

**Issue by linsun** [istio/istio#2435]
in our dev-guide.md: https://github.com/istio/istio/blob/master/DEV-GUIDE.md#race-detection-tests

_bash-3.2$ make racetest
make: *** No rule to make target `racetest'.  Stop._

I'm not able to find any history for this target or script.   I welcome input from others who can shed some light on this.  This seems a good target to have:  https://blog.golang.org/race-detector

**Comment by sdake** [comment]
@linsun one of my co-workers had mentioned this to me Thursday.  I implemented the targets today (sorry - didn't see you had filed an issue on it).  The PR is here: https://github.com/istio/istio/pull/2479

**Comment by linsun** [comment]
That is great, thank you for submitting a PR for it!

**Comment by sdake** [comment]
@2479 merged, so closing this issue.
