### ISSUE TITLE
Broken link in pilot/doc/design.md referring to configuration-flow.md

### ISSUE THREAD

**Issue by al3xandru** [istio/istio#2437]
`pilot/doc/design/md` includes a link to `configuration-flow.md` which looks to have been removed in the commit 238eec2ffc674bef08c02acc43c5989f09c60c4f#diff-7ededb7c32142221a5c20ed5f5f64eb4

**Comment by christian-posta** [comment]
Yah seems related to this https://github.com/istio/istio/commit/238eec2ffc674bef08c02acc43c5989f09c60c4f#diff-0bf1e3e19574963fdf511247da316b61

I've sent a PR to fix

**Comment by rshriram** [comment]
fixed
