### ISSUE TITLE
Unexplained telemetry involving passthrough and unknown

### ISSUE THREAD

**Issue by jshaughn** [istio/istio#24379]
We have a demo app called "travel agency" that when run against Istio 1.6 is generating the expected telemetry but also unexpected telemetry.  Initial telemtry looks good and generates an expected Kiali graph.  But quickly we see an unexpected TCP edge leading to PassthroughCluster, and then again from Unknown to a destination service.  After a few minutes we eventually see these additional TCP edges leading to Passthrough and then from unknown.  It seems sort of like an intermittent leak of internal traffic.  Here is a short video (using Kiali replay) that shows the issue.  At the very beginning you see the expected, all green, all http traffic,  Quickly we see some of the unexpected (blue) TCP telem.  And as I skip forward and advance the frames the remaining edges show up:

![travel-bad-telemetry](https://user-images.githubusercontent.com/2104052/83649665-71668900-a585-11ea-8891-22a99142bc38.gif)

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[x] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
The TCP edges to PassthroughCluster, and from unknown, should not show up, which means that Istio should not generate the underlying Prometheus time-series.

**Steps to reproduce the bug**
The travel-agency app is found here: https://github.com/lucasponce/travel-comparison-demo

There is a script to install the app here: https://github.com/jmazzitelli/test/tree/master/deploy-
travel-agency

This will install travel agency on minikube:

`$ CLIENT_EXE=minikube bash <(curl -L https://raw.githubusercontent.com/jmazzitelli/test/master/deploy-travel-agency/deploy-travel-agency-demo.sh)
`

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
This has been recreated on both 1.6.0 and 1.6.1 pre-release, using default (V2) telem.

**How was Istio installed?**
istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**
This has been recreated on Minikube and OpenShift, both on bare metal and AWS.

cc @jmazzitelli @lucasponce

**Comment by jmazzitelli** [comment]
> There is a script to install the app here: https://github.com/jmazzitelli/test/tree/master/deploy-
> travel-agency

That link is incomplete, and wrapped and thus cut-off. The full link to install the demo script used to replicate this problem is here:

https://github.com/jmazzitelli/test/blob/master/deploy-travel-agency/deploy-travel-agency-demo.sh

To install on minikube, run this:

```
CLIENT_EXE=kubectl bash <(curl -L https://raw.githubusercontent.com/jmazzitelli/test/master/deploy-travel-agency/deploy-travel-agency-demo.sh)```

**Comment by lucasponce** [comment]
I can confirm the same behaviour and add more data:

![image](https://user-images.githubusercontent.com/1662329/83655358-9fb48a80-a5be-11ea-8560-00229c8b1f05.png)

Basically the travels-v1 workload invokes hotels,insurances,flights,cars services and those invoke discount ones.

Debugging istio-proxies I can collect info where PassthroughCluster requests are reported:

```
2020-06-03T10:44:13.406466597Z [2020-06-03T10:43:57.181Z] "- - -" 0 - "-" "-" 6351 15841 10273 - "-" "-" "-" "-" "10.111.31.203:8000" PassthroughCluster 172.17.0.24:41840 10.111.31.203:8000 172.17.0.24:41830 - -
2020-06-03T10:44:13.406477201Z [2020-06-03T10:44:07.421Z] "GET /travels/rome HTTP/1.1" 200 - "-" "-" 0 444 33 32 "-" "Go-http-client/1.1" "f9c92a5f-d036-9252-8ca7-ab987126f72d" "travels.travel-agency:8000" "127.0.0.1:8000" inbound|8000|http|travels.travel-agency.svc.cluster.local 127.0.0.1:42166 172.17.0.24:8000 172.17.0.26:52808 outbound_.8000_._.travels.travel-agency.svc.cluster.local default
2020-06-03T10:44:13.406488197Z [2020-06-03T10:44:07.689Z] "GET /travels/paris HTTP/1.1" 200 - "-" "-" 0 446 15 14 "-" "Go-http-client/1.1" "aab65bc6-47bc-96e5-939d-b77ba056f13c" "travels.travel-agency:8000" "127.0.0.1:8000" inbound|8000|http|travels.travel-agency.svc.cluster.local 127.0.0.1:42166 172.17.0.24:8000 172.17.0.27:43774 outbound_.8000_._.travels.travel-agency.svc.cluster.local default
2020-06-03T10:44:13.406499833Z [2020-06-03T10:44:07.703Z] "GET /travels/rome HTTP/1.1" 200 - "-" "-" 0 444 44 43 "-" "Go-http-client/1.1" "73452650-d18e-9482-b5d7-db26729ec3fc" "travels.travel-agency:8000" "127.0.0.1:8000" inbound|8000|http|travels.travel-agency.svc.cluster.local 127.0.0.1:42960 172.17.0.24:8000 172.17.0.28:59326 outbound_.8000_._.travels.travel-agency.svc.cluster.local default
2020-06-03T10:44:13.406511054Z [2020-06-03T10:44:07.800Z] "GET /travels/paris HTTP/1.1" 200 - "-" "-" 0 448 15 14 "-" "Go-http-client/1.1" "41965fab-3cec-9edd-b139-2749fbdaa661" "travels.travel-agency:8000" "127.0.0.1:8000" inbound|8000|http|travels.travel-agency.svc.cluster.local 127.0.0.1:38028 172.17.0.24:8000 172.17.0.29:55414 outbound_.8000_._.travels.travel-agency.svc.cluster.local default
2020-06-03T10:44:13.406522084Z [2020-06-03T10:43:44.869Z] "- - -" 0 - "-" "-" 19380 49781 23117 - "-" "-" "-" "-" "10.102.42.131:8000" PassthroughCluster 172.17.0.24:60356 10.102.42.131:8000 172.17.0.24:60352 - -
2020-06-03T10:44:13.40653199Z [2020-06-03T10:44:07.965Z] "GET /travels/london HTTP/1.1" 200 - "-" "-" 0 451 42 40 "-" "Go-http-client/1.1" "83f94115-49ad-9187-ace1-ad124991995e" "travels.travel-agency:8000" "127.0.0.1:8000" inbound|8000|http|travels.travel-agency.svc.cluster.local 127.0.0.1:38644 172.17.0.24:8000 172.17.0.30:40244 outbound_.8000_._.travels.travel-agency.svc.cluster.local default
2020-06-03T10:44:13.40654304Z [2020-06-03T10:44:07.948Z] "GET /travels/london HTTP/1.1" 200 - "-" "-" 0 452 60 57 "-" "Go-http-client/1.1" "40e46a83-436e-9876-be8d-051c3f4e81be" "travels.travel-agency:8000" "127.0.0.1:8000" inbound|8000|http|travels.travel-agency.svc.cluster.local 127.0.0.1:38028 172.17.0.24:8000 172.17.0.31:60750 outbound_.8000_._.travels.travel-agency.svc.cluster.local default
2020-06-03T10:44:13.406584607Z [2020-06-03T10:44:07.544Z] "- - -" 0 - "-" "-" 648 1618 476 - "-" "-" "-" "-" "10.111.31.203:8000" PassthroughCluster 172.17.0.24:42160 10.111.31.203:8000 172.17.0.24:42156 - -
```

```
2020-06-03T10:44:13.406466597Z [2020-06-03T10:43:57.181Z] "- - -" 0 - "-" "-" 6351 15841 10273 - "-" "-" "-" "-" "10.111.31.203:8000" PassthroughCluster 172.17.0.24:41840 10.111.31.203:8000 172.17.0.24:41830 - -

10.111.31.203:8000 -> flights service
172.17.0.24:41840 -> travels endpoint
172.17.0.24:41830 -> travels endpoint

2020-06-03T10:44:13.406522084Z [2020-06-03T10:43:44.869Z] "- - -" 0 - "-" "-" 19380 49781 23117 - "-" "-" "-" "-" "10.102.42.131:8000" PassthroughCluster 172.17.0.24:60356 10.102.42.131:8000 172.17.0.24:60352 - -

10.102.42.131:8000 -> cars service
172.17.0.24:60356 -> travels endpoint
172.17.0.24:60352 -> travels endpoint

2020-06-03T10:44:13.406584607Z [2020-06-03T10:44:07.544Z] "- - -" 0 - "-" "-" 648 1618 476 - "-" "-" "-" "-" "10.111.31.203:8000" PassthroughCluster 172.17.0.24:42160 10.111.31.203:8000 172.17.0.24:42156 - -

10.111.31.203:8000 -> flights service
172.17.0.24:41840 -> travels endpoint
172.17.0.24:41830 -> travels endpoint
```

There are no strange traffic, it looks some requests are missed from the telemetry report.

**Comment by lucasponce** [comment]
Adding more proxy-config logs of this scenarios just in case it helps to diagnose:

[log-proxy-config-listeners.txt](https://github.com/istio/istio/files/4724404/log-proxy-config-listeners.txt)
[log-proxy-config-routes.txt](https://github.com/istio/istio/files/4724405/log-proxy-config-routes.txt)

**Comment by douglas-reid** [comment]
@bianpengyuan @nrjpoddar can you take a look at this issue?

**Comment by bianpengyuan** [comment]
Will take a look.

**Comment by bianpengyuan** [comment]
Likely a dup of https://github.com/istio/istio/issues/23901

**Comment by jshaughn** [comment]
BTW, I have also now seem this using bookinfo.  On that one I did not get the edges from "unknown" but did get unwanted edges to Passthrough from some (not all) of the workloads.  It seems there is some sort of internal telemetry "leak".

**Comment by bianpengyuan** [comment]
@jshaughn Could you please dump `istio_tcp_received_bytes_total` and `istio_tcp_sent_bytes_total` from prometheus? I cannot reproduce what you saw with travel app, where all workload has unknown source and passthrough cluster as destination and consistent tcp bytes sent or received. Though I am not using CNI, so I am wondering whether it is because of CNI again this time.

I can only reproduce what you mentioned in https://github.com/istio/istio/issues/24379#issuecomment-640685790, that some idle connections to passthrough cluster.
```
istio_tcp_received_bytes_total{app="insurances",connection_security_policy="unknown",destination_app="unknown",destination_canonical_revision="latest",destination_canonical_service="unknown",destination_principal="unknown",destination_service="unknown",destination_service_name="PassthroughCluster",destination_service_namespace="unknown",destination_version="unknown",destination_workload="unknown",destination_workload_namespace="unknown",instance="10.56.2.178:15020",istio_io_rev="default",job="kubernetes-pods",namespace="travel-agency",pod_name="insurances-v1-554dc5f9cb-ssk5p",pod_template_hash="554dc5f9cb",reporter="source",request_protocol="tcp",response_flags="UF,URX",security_istio_io_tlsMode="istio",service_istio_io_canonical_name="insurances",service_istio_io_canonical_revision="v1",source_app="insurances",source_canonical_revision="v1",source_canonical_service="insurances",source_principal="unknown",source_version="v1",source_workload="insurances-v1",source_workload_namespace="travel-agency",version="v1"}
```
I still need to dig why idle connection to passthrough cluster is happening, likely it is because of http inspector timeout.

**Comment by bianpengyuan** [comment]
I can reproduce it in a cluster with cni enabled.

**Comment by jshaughn** [comment]
@bianpengyuan I don't think the main issue is CNI related as we have seen this issue on non-CNI/minikube envs as well, but in this particular bookinfo case, where I am seeing only the passthrough destination edges, it is CNI.  So perhaps this is not the same issue, but here is the bookinfo time-series dump:

[istio24379.txt](https://github.com/istio/istio/files/4748611/istio24379.txt)

**Comment by bianpengyuan** [comment]
The non-cni environment is the place you run bookinfo? Can you only see ghost passthrough edges which does not have any data sent/received, or the unknown source as well? I think what we see with CNI and the ghost passthrough edges with non-CNI env are separated issue... Anyway I can reproduce both now, will dig more.

**Comment by jshaughn** [comment]
The travel example has been reproduced with and without CNI and has both the unknown source edges as well as the passthrough destination edges.

The bookinfo data from today is with CNI and showed only the unwanted passthrough destination edges.

Sorry if I confused things but really glad you have been able to reproduce.

**Comment by Mengkzhaoyun** [comment]
#24501 

the same issue with `Istio v1.6.1 TCP telemetry unknown & passthroughcluster #24501` ?

i don't think so , because i can not see the metrics correct at begin , it always go to the wrong metrics , it can not collect the completion  tcp metrics as one.

i can see the normal tcp metrics split to two part and did not know each other , as blow 

that one metrics from ratings-v2-mogodb , it did not known the dest 
```bash
istio_tcp_received_bytes_total{connection_security_policy="unknown", destination_app="unknown", destination_canonical_revision="latest", destination_canonical_service="unknown", destination_principal="unknown", destination_service="unknown", destination_service_name="PassthroughCluster", destination_service_namespace="unknown", destination_version="unknown", destination_workload="unknown", destination_workload_namespace="unknown", instance="10.2.2.162:15090", job="envoy-stats", namespace="istio-samples", pod_name="ratings-v2-mongodb-7cdd894b4b-82wxg", reporter="source", request_protocol="tcp", response_flags="-", source_app="ratings", source_canonical_revision="v2-mongodb", source_canonical_service="ratings", source_principal="unknown", source_version="v2-mongodb", source_workload="ratings-v2-mongodb", source_workload_namespace="istio-samples"}
```

one  is mogodb-v1 it did not known the source 
```bash
istio_tcp_received_bytes_total{connection_security_policy="none", destination_app="mongodb", destination_canonical_revision="v1", destination_canonical_service="mongodb", destination_principal="unknown", destination_service="mongodb.istio-samples.svc.cluster.local", destination_service_name="mongodb", destination_service_namespace="istio-samples", destination_version="v1", destination_workload="mongodb-v1", destination_workload_namespace="istio-samples", instance="10.2.0.25:15090", job="envoy-stats", namespace="istio-samples", pod_name="mongodb-v1-5d68dcf7f4-wrwnv", reporter="destination", request_protocol="tcp", response_flags="-", source_app="unknown", source_canonical_revision="latest", source_canonical_service="unknown", source_principal="unknown", source_version="unknown", source_workload="unknown", source_workload_namespace="unknown"}
```

**Comment by bianpengyuan** [comment]
@jshaughn @lucasponce Does `travels` workload always send requests to a destination service in the same way? I am observing some weird behavior that for traffic from travels to other workloads (and other workloads to discount app too), that some of the requests do not have source metadata exchanged. So I am wondering, does travels app always call other app in a consistent way, or does it somehow use two different ways to call a destination service, which introduces this weird behavior.

**Comment by lucasponce** [comment]
@bianpengyuan the `travels` workload it's pretty "hello world", it's always working on the same way:

https://github.com/lucasponce/travel-comparison-demo/blob/master/travel_agency/travel_agency.go#L245

So, it's just a simple GET request to the others services using the http go library.

So, all telemetry should be similar.

**Comment by mandarjog** [comment]
Do the total number of requests (bad edges + good edges) match what you expect the client to send?

**Comment by bianpengyuan** [comment]
After increasing outbound proto sniffing timeout, unknown edge disappeared. Could you try to set `--set meshConfig.protocolDetectionTimeout=1s` in installation and see if it fixes your problem too? We might need to consider increasing timeout of outbound listener sniffing.

**Comment by mandarjog** [comment]
That is great sleuthing.

@lambdai @PiotrSikora 
Can this be disabled when we know the other side is http? Or is it now on by default and unchangeable ?

**Comment by jshaughn** [comment]
Not really expecting a change because I don't see any fix merged, just an FYI that this is still happening in 1.6.2.

**Comment by howardjohn** [comment]
We rely on sniffing now for correctness of traffic.. it's pretty hard to avoid at this point. Otherwise outbound allow any https/tcp traffic breaks if you have a http service on the same port.

The timeout has been nothing but trouble, I really think we should change it back to infinite as default and allow explicitly setting the timeout for server first ports

**Comment by bianpengyuan** [comment]
I can raise this in the next networking wg meeting to draw a conclusion.

**Comment by mandarjog** [comment]
@nrjpoddar what was the conclusion of sniffing and timeouts debate?

**Comment by jshaughn** [comment]
Hi guys, any update on this one?

**Comment by bianpengyuan** [comment]
@jshaughn I will try to get a conclusion from tomorrows networking group meeting.

**Comment by jshaughn** [comment]
I will test this when 1.6.4 is released.

**Comment by naphta** [comment]
I'm getting this issue on 1.6.3 with protocolDetectionTimeout set to 2s. Traffic is promethus on port 15020. I'm scraping from prometheus-operator with the bundled prometheus turned off.

**Comment by jshaughn** [comment]
@bianpengyuan @douglas-reid , Please re-open, I'm not seeing any change in 1.6.5.  This is getting serious as the telemetry looks horrible in 1.6.  With the new 1.6.5 release:

![image](https://user-images.githubusercontent.com/2104052/87173459-c9d72780-c2a3-11ea-9ba9-e2f2825c4f43.png)

**Comment by bianpengyuan** [comment]
@jshaughn Would you mind to try out install istio with `--set meshConfig.protocolDetectionTimeout=3600s` and see if it fixes the issue? We raised it to `5s` in 1.6.5 but maybe it still not enough for the application. I was also seeing an unknown passthrough edge with my 1.6.5 installation. I raised the time out to `3600s`, so far I don't see any extra edge in my graph.
<img width="1322" alt="Screen Shot 2020-07-10 at 9 43 57 AM" src="https://user-images.githubusercontent.com/34738376/87178910-c1c2bc00-c292-11ea-8cab-1e12cbb79046.png">

**Comment by naphta** [comment]
Upgraded to 1.6.5 and raised the protocolDetectionTimeout to 3600s and I'm still seeing unknown/passthroughcluster traffic.

![Screenshot 2020-07-14 at 10 03 12](https://user-images.githubusercontent.com/6709831/87406961-686fcb00-c5b9-11ea-8645-e95b88d7ffb2.png)

**Comment by jshaughn** [comment]
Thanks @naphta, I have not had the time to try that change from 5s to 6s.  It seems the timeout approach may not be a sufficient fix but I'm not familiar with the underlying code/issue.  I continue to use the Kiali graph-hide expression of "node=unknown OR service^=Pass" to clean up the graph, at the expense of seeing the correct traffic totals.

**Comment by bianpengyuan** [comment]
@naphta did you rollout restart your deployments and prometheus after changing timeout to 3600s? kiali edges are from proxy metrics, which persist across proxy and prometheus's life time. You will need to restart to proxy to get rid of stale ones.

**Comment by naphta** [comment]
Pretty sure I did @bianpengyuan but I've restarted them (for sure) and spun up a fresh prometheus so it's not working from old any data. Actually looks a bit worse now, only been up for around 2-3 minutes as of the screenshot.

![Screenshot 2020-07-14 at 16 44 18](https://user-images.githubusercontent.com/6709831/87446566-59a50a80-c5f1-11ea-93fd-44cdd49a8b42.png)

**Comment by bianpengyuan** [comment]
Can I get a config dump (k exec pod-name curl localhost:15000/config_dump) from your management or delivery proxy? Also want to make sure all traffic is normal HTTP and does not have anything special such as server first protocol right?

**Comment by naphta** [comment]
I've sent the management pod here. It listens on HTTP and gRPC for Prometheus and service respectively, although only gRPC is exposed via Istio virtual services. My cluster config is below, and I've also added the config dump as requested.

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  annotations:
    meta.helm.sh/release-name: istio-operator-manifest
    meta.helm.sh/release-namespace: istio-system
  labels:
    app: raw
    app.kubernetes.io/managed-by: Helm
    chart: raw-0.2.3
    heritage: Helm
    release: istio-operator-manifest
  name: istio-cluster
  namespace: istio-system
spec:
  addonComponents:
    grafana:
      enabled: false
    kiali:
      enabled: false
    prometheus:
      enabled: false
    prometheusOperator:
      enabled: false
  components:
    egressGateways:
    - enabled: true
      name: istio-egressgateway
    ingressGateways:
    - enabled: true
      name: istio-ingressgateway
    sidecarInjector:
      enabled: true
  meshConfig:
    accessLogEncoding: TEXT
    accessLogFile: /dev/stdout
    enablePrometheusMerge: true
    protocolDetectionTimeout: 3600s
  profile: default
  values:
    global:
      istiod:
        enableAnalysis: true
      priorityClassName: critical
    pilot:
      enableProtocolSniffingForInbound: true
      enableProtocolSniffingForOutbound: true
    sidecarInjectorWebhook:
      enableNamespacesByDefault: false
status:
  componentStatus:
    Pilot:
      status: HEALTHY
  status: HEALTHY
```
[scratch_5.txt](https://github.com/istio/istio/files/4924345/scratch_5.txt)

**Comment by jshaughn** [comment]
@bianpengyuan @naphta , I tried installing Istio with basically an unlimited timeout (meshConfig.protocolDetectionTimeout=3600000s) and actually, things look good.  I have no idea what the downside is to removing the timeout, but my initial observation is that it seems to resolve the issue.

![image](https://user-images.githubusercontent.com/2104052/87881820-d2c5a880-c9c9-11ea-8a2c-f292d4cb5e5d.png)

**Comment by mandarjog** [comment]
The downside is that server first protocols will fail.

And from code and talking to @lambdai it seems that labeling port correctly with the protocol *does not* disable outbound Sniffing. This is only applicable for tcp ports.

If there is another way to opt-out specific ports/ip ranges for outbound sniffing then keeping detect timeout to ~infinity is the proper solution. 

Whether there is an opt-out now, we will ensure that there is an opt-out in 1.7

**Comment by howardjohn** [comment]
I am surprised you had issues with 5s timeout. My general opinion is we need to get to a point where there is infinite timeout to avoid all issues, but 5s is super high and would suggest the connection establishment is taking really long - there may be some other network issues going on

**Comment by jshaughn** [comment]
@howardjohn The 5s change made no difference to my setup, which is a straightforward OpenShift setup.  I don't know what it is about the travel demo but it shows the problem quite easily, and across various cluster types, minikube, OS, etc.  Bookinfo does not show the issue, which is a good reason to not run only bookinfo.  For @naphta the change to 6s did not solve the problem.  It seems to me that there must be something at play that is not yet understood.

**Comment by bianpengyuan** [comment]
@naphta To make sure your issue is around proto sniffing, could you try to turn it off and see if it is fiexed? https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/#automatic-protocol-selection Please make sure that your deployment does not rely on proto sniffing for correctness before turning it off (i.e. service port has proper protocol prefix, No TCP service and HTTP service share the same port).

**Comment by naphta** [comment]
@bianpengyuan I can turn it off to see if there's any change but specifically in my case I am using the prometheus scrape annotations, and the unknown traffic is the prometheus scraping as far as I can tell.

**Comment by jshaughn** [comment]
@bianpengyuan I tested some more using Istio 1.6.5 and found one odd thing.  When running 1.6.5 defaults I see the problem like I ususally do, as in the original video and screenshots above.

When I install Istio 1.6.5 with an explicit ` --set meshConfig.protocolDetectionTimeout=5s` I actually saw better behavior.  I still see some bad traffic but less often.  It makes me wonder whether the default is properly set in 1.6.5.  But it may just be a fluke because I then tried an explicit 8s and again, less bad traffic but not eliminated.  Without setting a huge timeout the problem still seems to manifest.  is there any chance the units are confused and we're not getting the timeout we expect?

If  disabling proto-sniffing completely via `values.pilot.enableProtocolSniffingForInbound=false` and `values.pilot.enableProtocolSniffingForOutbound=false` then I see only the good/expected telemetry.

For whatever reason it seems proto-sniffing, or its timeout, is not working as expected.

**Comment by bianpengyuan** [comment]
I need to double check, but the reason should be that the option controls both inbound and outbound timeout, while the default setting in 1.6.5 only update the default at outbound.

**Comment by jshaughn** [comment]
Hi guys, Is there a final fix planned for 1.7?

**Comment by bianpengyuan** [comment]
Turns out, in release-1.6, the 5s timeout was overridden by the global installation value: https://github.com/istio/istio/blob/4e6e7f49375d84bb35ee614c6b7d38b6c2fd3e7b/manifests/charts/global.yaml#L127

This is not a problem for release-1.7 because this default global value has already been removed in [master and release-1.7](https://github.com/istio/istio/commit/a0d483a26e3e8e604c18fc6f37ff222db607cce8#diff-bc1ebec4e1403e51a450d3ef58179c22L127). That is the reason I did not notice it when making the change to master, and cherry-pick to release-1.6 automatically without updating that global value. @jshaughn you could probably try out [1.7.0 alpha build](https://github.com/istio/istio/releases/tag/1.7.0-alpha.2), since 1.6 currently is in freeze due to a security fix and could take some time to get that fix in.

**Comment by jshaughn** [comment]
@bianpengyuan I will check out 1.7 apha-2 tomorrow and let you know, thanks.

**Comment by JimmyCYJ** [comment]
@jshaughn is there any update on this issue?

**Comment by jshaughn** [comment]
@JimmyCYJ @bianpengyuan Sorry for the delay, it was my first time navigating the install changes with 1.7.  The new approach to addons means Kiali and Prometheus are now installed separately.  But I do now have 1.7-alpha.2 running and I can report that the issue is **not** fixed.  It may have been the case that the 5s default was not honored in 1.6, but I'm not surprised the problem remains because, as mentioned above, the issue was not fixed when manually using `--set meshConfig.protocolDetectionTimeout=5s`. 

This is still a serious issue as the telemetry is simply not being reported correctly, users will not be able to easily understand their traffic.

**Comment by bianpengyuan** [comment]
@jshaughn Can I get a config dump from your proxy?

**Comment by bianpengyuan** [comment]
@jshaughn Actually nvm, I wanted to check whether the timeout is really applied, but I think it should have been, and I'd be really surprised if envoy is not handling the timeout correctly because it is so fundamental and lots of security feature depends on this as well, such as tls sniffing.

I cannot think of a work around here with current configurability. tbh, 5s should be long enough for 99% of set up. We cannot just set timeout longer or even infinity since it is going to cause trouble for server first protocol like mysql and we don't have a way to opt-out a port from proto sniffing right now. Also proto sniffing needs to be turned on by default now because people are relying on it to distinguish type of traffic when a port is used by both http and tcp.

Sorry about that.. but I'd suggest to either debug why 5s is not sufficient for this app with tcpdump or turn off sniffing for this demo app.

**Comment by jmazzitelli** [comment]
> Sorry about that.. but I'd suggest to either debug why 5s is not sufficient for this app with tcpdump or turn off sniffing for this demo app.

If I recall, its not just this one app. We had heard from at least one other person (completely different app) that sees the same behavior.

**Comment by bianpengyuan** [comment]
@jmazzitelli not sure if the other app has tried out new build with default 5s time out? It is understandable that the original timeout was too short (0.1s) and would cause this issue, but 5s is really long enough that normal app should just work fine with it.

**Comment by jmazzitelli** [comment]
> @jmazzitelli not sure if the other app has tried out new build with default 5s time out? It is understandable that the original timeout was too short (0.1s) and would cause this issue, but 5s is really long enough that normal app should just work fine with it.

I believe @naphta was someone who saw this - would need to see if he tried with the latest 1.7 build.

**Comment by bianpengyuan** [comment]
Yeah, I think @naphta mentioned that is because of prometheus scraping instead of proto sniffing. although have not got a confirmation on that.

**Comment by bianpengyuan** [comment]
I don't think this is a 1.7 blocking issue, as the default timeout should satisfy most cases. I am going to close this. https://github.com/istio/istio/issues/24998 tracks long term fix to remove dependency on proto sniffing.

**Comment by FL3SH** [comment]
I am wondering if this issue may cause a problem with mTLS?
<img width="1649" alt="Screenshot 2020-08-06 at 11 35 03" src="https://user-images.githubusercontent.com/9084725/89528602-9f698300-d7eb-11ea-95b2-7b4a5dd92eb6.png">

If I set `spec.mtls.mode: STRICT` for my namespace my app is no longer able to connected to MongoDB.
Did I misconfigured something or shouldn't it just work?
Same issue for `1.6.7` and `1.7.0-beta.1`.

**Comment by naphta** [comment]
> Yeah, I think @naphta mentioned that is because of prometheus scraping instead of proto sniffing. although have not got a confirmation on that.

It does appear that raising the proto sniffing doesn't resolve my problem, and the ports in question are the ones scraped by Prometheus. My problem might be related to using prometheus-direct scraping, although it seems odd to me that the sidecar wouldn't understand where it's coming from.

**Comment by jshaughn** [comment]
Looks like no fix is coming in 1.7 and so if affected then part of your telemetry will be reported incorrectly, coming from `unknown` or going to `PassthroughCluster`.   To improve the Kiali graph I can only recommend disabling proto-sniffing completely if your app doesn't need it [1], or hiding the unwanted traffic by entering `node=unknown OR service^=Pass` in the Kiali graph hide. 

[1] Disable proto-sniffing by setting values.pilot.enableProtocolSniffingForInbound=false and values.pilot.enableProtocolSniffingForOutbound=false.

I'm not sure if @howardjohn has any other recommendation, I suggest pushing on https://github.com/istio/istio/issues/24998 to be fixed ASAP.

@FL3SH , your graph in particular is pretty wild.  I'm not sure I've seen 2 PassthroughCluster nodes, I'm not sure how that happens.

**Comment by lucasponce** [comment]
> I'm not sure if @howardjohn has any other recommendation, I suggest pushing on #24998 to be fixed ASAP.

I stand @jshaughn on this suggestion.

**Comment by FL3SH** [comment]
I was able cleanup my graph quite a bit.
<img width="1500" alt="Screenshot 2020-08-06 at 16 32 14" src="https://user-images.githubusercontent.com/9084725/89579282-cba8f200-d833-11ea-9b65-d9f35cbe93c3.png">

- removed virutalservices for redis and mongo
- fixed all prefixes for ports - I was missing `tcp-` or `http-` for [protocol selection](https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/#manual-protocol-selection)
- added `version` labels for pods, services, and sts to remove kiali warnings
- add missing `app` labels for pods, services, and sts for kiali to group them together

**Comment by FL3SH** [comment]
After seting `values.pilot.enableProtocolSniffingForInbound=false` and `values.pilot.enableProtocolSniffingForOutbound=false` nothing really has changed.

Is it an expected result?

<img width="854" alt="Screenshot 2020-08-07 at 10 18 33" src="https://user-images.githubusercontent.com/9084725/89625127-9afaa400-d897-11ea-8100-1c630b36cc34.png">

**Comment by FL3SH** [comment]
Can this issue have an impact on `AuthorizationPolicy`?

**Comment by bianpengyuan** [comment]
You graph looks normal to me. In your point of view, which part of your graph is wrong?

**Comment by FL3SH** [comment]
`unknow` -> `mongo-mongod`

I thought my traffic would go from `myapp` pod to `mongo-mongod` service direct without this strange `mongo-mongod.defal.svc.cluster.local` service.

**Comment by bianpengyuan** [comment]
Oh I see. yes, MTLS has to be enabled in order to make both client and server sidecar get peer's workload metadata, which is needed to connect kiali graph.

**Comment by FL3SH** [comment]
In conclusion, this is how this graph should looks?

**Comment by bianpengyuan** [comment]
@FL3SH yes.

**Comment by FL3SH** [comment]
Thank you for your explanation.

**Comment by lucasponce** [comment]
This is closed but I can see it in a different version of the demo app:
![image](https://user-images.githubusercontent.com/1662329/93115402-13852980-f6bc-11ea-841a-c1427bc9c30d.png)

https://github.com/kiali/demos/tree/master/travels

**Comment by bianpengyuan** [comment]
Yeah there is no change between 1.6.x to 1.7.1. This issue still relies on the work around to increase proto sniffing timeout and [this comment](https://github.com/istio/istio/issues/24379#issuecomment-666688526) still applies to your demo app. FWIW, the long term effort to make timeout infinite is in progress and hopefully it can make 1.8.
