### ISSUE TITLE
Sidecar tunnel to Istiod XDS

### ISSUE THREAD

**Issue by esnible** [istio/istio#24394]
istioctl will contact Istiod **indirectly**.  istioctl will port-forward to a workload pod on a special port.

The workload pod will expose a port that, with proper security, "tunnels" to Istiod XDS.  istioctl will use this tunnel to do XDS Event queries against Istiod.

The XDS Event document is https://docs.google.com/document/d/1X7DmkP10x4nEcTGpikxmvLbBTTK59B0WL3liQzVy8Ms/edit#heading=h.xw1gqgyqs5b

**Comment by therealmitchconnors** [comment]
Is this issue addressed by https://github.com/istio/istio/pull/24398
