### ISSUE TITLE
Create multiple Istio Control plane per tenant network(in seperate namespace) within same Kubernetes Cluster

### ISSUE THREAD

**Issue by sb1975** [istio/istio#24401]
**Describe the feature request**

My use Case is to create Multiple Mesh within the same K8s Cluster using manual steps . Each Mesh needs to manage a particular Customer Network because each vendor is coming with their own instance of Service Mesh within their network and their own separate namespace . I do not need any operator for this, I just need a manual way to do this. This can be pictorially represented as this diagram..

https://drive.google.com/file/d/1G-FmwtY0JR05U5jkrkABSRHPIgX-NF6-/view?usp=sharing

Each tenant should have ability to deploy his own service Mesh Control Plane.
He should be able to define and use his own control plane components with the namespaces he owns. (so RBAC should restrict him within his own namespaces).

Support  separate IPPools for each namespace and still the Istio Control plane is able to successfully implement the Routing, traffic control, sidecar-injection , observability to its own namespaces only.

Proper documentation and steps to be able to do that.

**Describe alternatives you've considered**

Multiple Istio Control Plane for each Tenants. There is a older blog for this in the Istio Website but it doesnt work. https://istio.io/blog/2018/soft-multitenancy/

I think it is possible in Maistra - https://github.com/Maistra/istio-operator however thats specific to Openshift deployment.

[ ] Configuration Infrastructure
[x ] Docs
[x ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x ] Security
[ ] Test and Release
[x ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by sb1975** [comment]
Created two different manifest files using cmds below:
istioctl manifest generate -i istio-system1 --set profile=demo > $HOME/generated-manifest-1.yaml
updated all namespaces to istio-system1

Executed kubectl apply -f generated-manifest-1.yaml

created another generated-manifest-2.yaml with all namespaces to istio-system2
Executed kubectl apply -f generated-manifest-2.yaml

The pods stay in ContainerCreating STATUS.

$ kubectl get pods -n istio-system1
NAME                                    READY   STATUS              RESTARTS   AGE
grafana-66bb6bd59b-lj82w                1/1     Running             0          30m
istio-egressgateway-54fcd6d5d6-2z8bf    0/1     ContainerCreating   0          29m
istio-ingressgateway-69bb9684dc-mqnqk   0/1     ContainerCreating   0          29m
istio-tracing-9dd6c4f7c-k2jdv           1/1     Running             0          29m
istiod-77ffb4478c-5vf8b                 0/1     ContainerCreating   0          29m
kiali-d45468dc4-v96xb                   1/1     Running             0          29m
prometheus-6b4d656587-rf5rj             0/2     ContainerCreating   0          29m

$ kubectl get pods -n istio-system2
NAME                                   READY   STATUS              RESTARTS   AGE
grafana-58575cd5cf-clbgm               1/1     Running             0          27m
istio-egressgateway-598c5f8897-bt8k7   0/1     ContainerCreating   0          27m
istio-ingressgateway-8f89494dc-pzqpp   0/1     ContainerCreating   0          27m
istio-tracing-9dd6c4f7c-kvdjn          1/1     Running             0          27m
istiod-54f568797f-scqqx                0/1     ContainerCreating   0          12m
istiod-77cf9c99ff-28wm2                0/1     ContainerCreating   0          27m
kiali-d45468dc4-jpdkk                  1/1     Running             0          27m
prometheus-5cc5d9d66-xvtjk             0/2     ContainerCreating   0          27m

$ kubectl describe pod istiod-77ffb4478c-5vf8b -n istio-system1
Name:           istiod-77ffb4478c-5vf8b
Namespace:      istio-system1
Priority:       0
Node:           istio-multi/10.128.0.20
Start Time:     Thu, 04 Jun 2020 21:34:42 +0000
Labels:         app=istiod
                istio=pilot
                istio.io/rev=default
                pod-template-hash=77ffb4478c
Annotations:    sidecar.istio.io/inject: false
Status:         Pending
IP:
IPs:            <none>
Controlled By:  ReplicaSet/istiod-77ffb4478c
Containers:
  discovery:
    Container ID:
    Image:         docker.io/istio/pilot:1.6.0
    Image ID:
    Ports:         8080/TCP, 15010/TCP, 15017/TCP, 15053/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP, 0/TCP
    Args:
      discovery
      --monitoringAddr=:15014
      --log_output_level=default:info
      --domain
      cluster.local
      --trust-domain=cluster.local
      --keepaliveMaxServerConnectionAge
      30m
      appNamespace=ns1
..
Events:
  Type     Reason       Age                    From                  Message
  ----     ------       ----                   ----                  -------
  Warning  FailedMount  48m (x7 over 105m)     kubelet, istio-multi  Unable to attach or mount volumes: unmounted volumes=[istio-token], unattached volumes=[cacerts inject istiod-service-account-token-nkvrl config-volume istio-token local-certs]: timed out waiting for the condition
  Warning  FailedMount  39m (x6 over 103m)     kubelet, istio-multi  Unable to attach or mount volumes: unmounted volumes=[istio-token], unattached volumes=[config-volume istio-token local-certs cacerts inject istiod-service-account-token-nkvrl]: timed out waiting for the condition
  Warning  FailedMount  28m (x7 over 107m)     kubelet, istio-multi  Unable to attach or mount volumes: unmounted volumes=[istio-token], unattached volumes=[istiod-service-account-token-nkvrl config-volume istio-token local-certs cacerts inject]: timed out waiting for the condition
  Warning  FailedMount  19m (x6 over 82m)      kubelet, istio-multi  Unable to attach or mount volumes: unmounted volumes=[istio-token], unattached volumes=[inject istiod-service-account-token-nkvrl config-volume istio-token local-certs cacerts]: timed out waiting for the condition
  Warning  FailedMount  14m (x9 over 96m)      kubelet, istio-multi  Unable to attach or mount volumes: unmounted volumes=[istio-token], unattached volumes=[local-certs cacerts inject istiod-service-account-token-nkvrl config-volume istio-token]: timed out waiting for the condition
  Warning  FailedMount  3m55s (x60 over 109m)  kubelet, istio-multi  MountVolume.SetUp failed for volume "istio-token" : failed to fetch token: the API server does not have TokenRequest endpoints enabled

**Comment by sb1975** [comment]
ok modified the steps as below 👍 
$istioctl manifest generate --set profile=demo --set values.global.jwtPolicy=first-party-jwt > ~/generated-manifest-1.yaml

$kubectl create secret generic cacerts -n istio-system1     --from-file=samples/certs/ca-cert.pem     --from-file=samples/certs/ca-key.pem     --from-file=samples/certs/root-cert.pem     --from-file=samples/certs/cert-chain.pem
$kubectl create secret generic cacerts -n istio-system2     --from-file=samples/certs/ca-cert.pem     --from-file=samples/certs/ca-key.pem     --from-file=samples/certs/root-cert.pem     --from-file=samples/certs/cert-chain.pem

updated the manifest file - all namespace from istio-system to istio-system1
and similarly another manifest file to istio-system2
Link : https://drive.google.com/file/d/1TxN4s2zF-i-CL8LOhZKhVDCG76HZ9qFK/view?usp=sharing, https://drive.google.com/file/d/1mA-7Dz7Qy65dy-yIjYncfq4h7Mg3XpjE/view?usp=sharing

kubectl apply -f ~/generated-manifest-2.yaml -n istio-system2
kubectl apply -f ~/generated-manifest-1.yaml -n istio-system1

The pods are not fully functional
$ kubectl get pod -n istio-system2
NAME                                   READY   STATUS    RESTARTS   AGE
grafana-58575cd5cf-vshmg               1/1     Running   0          3h29m
istio-egressgateway-5db8b84f8c-mfnc7   0/1     Running   0          3h29m
istio-ingressgateway-bd9479589-dgd2c   0/1     Running   0          3h29m
istio-tracing-9dd6c4f7c-z5t5h          1/1     Running   0          3h29m
istiod-6d4d84f6b5-tfsgp                1/1     Running   0          3h29m
kiali-d45468dc4-dhwsq                  1/1     Running   0          3h29m
prometheus-7ffcc6dc9c-gcnc2            1/2     Running   0          3h29m

$ kubectl get pod -n istio-system1
NAME                                    READY   STATUS    RESTARTS   AGE
grafana-66bb6bd59b-gvk4b                1/1     Running   0          3h29m
istio-egressgateway-96476596-4zbmf      0/1     Running   0          3h29m
istio-ingressgateway-58bcd7bb85-jshgb   0/1     Running   0          3h29m
istio-tracing-9dd6c4f7c-xvh7l           1/1     Running   0          3h29m
istiod-67b76fdb68-8w9gv                 1/1     Running   0          3h29m
kiali-d45468dc4-m2ggn                   1/1     Running   0          3h29m
prometheus-6789b47c7d-xjcnb             1/2     Running   0          3h29m

$ kubectl describe pod istio-ingressgateway-58bcd7bb85-jshgb -n istio-system1
Name:         istio-ingressgateway-58bcd7bb85-jshgb
Namespace:    istio-system1
Priority:     0
Node:         istio/10.128.0.22
Start Time:   Sun, 07 Jun 2020 21:44:38 +0000
Labels:       app=istio-ingressgateway
              chart=gateways
              heritage=Tiller
              istio=ingressgateway
              pod-template-hash=58bcd7bb85
              release=istio
              service.istio.io/canonical-name=istio-ingressgateway
              service.istio.io/canonical-revision=latest
Annotations:  cni.projectcalico.org/podIP: 192.168.193.229/32
              cni.projectcalico.org/podIPs: 192.168.193.229/32
              sidecar.istio.io/inject: false
Status:       Running
IP:           192.168.193.229
IPs:
  IP:           192.168.193.229
Events:
  Type     Reason     Age                      From            Message
  ----     ------     ----                     ----            -------
  Warning  Unhealthy  3m4s (x6426 over 3h37m)  kubelet, istio  Readiness probe failed: HTTP probe failed with statuscode: 503

$ kubectl describe pod istio-ingressgateway-bd9479589-dgd2c -n istio-system2
Name:         istio-ingressgateway-bd9479589-dgd2c
Namespace:    istio-system2
Priority:     0
Node:         istio/10.128.0.22
Start Time:   Sun, 07 Jun 2020 21:44:16 +0000
Labels:       app=istio-ingressgateway
Events:
  Type     Reason     Age                       From            Message
  ----     ------     ----                      ----            -------
  Warning  Unhealthy  4m53s (x6427 over 3h39m)  kubelet, istio  Readiness probe failed: HTTP probe failed with statuscode: 503

Kiali gives the below error after logging in the portal. (Kiali svc exposed by NodePort)
Could not fetch namespace list: namespaces is forbidden: User "system:serviceaccount:istio-system2:kiali-service-account" cannot list resource "namespaces" in API group "" at the cluster scope
7 in a minute

In general what are the configurations that need to be changed and where do they need to be defined in istio 1.6.1 please :
1. Does all ClusterRole need to be modified ?
2. Does all the secrets generated for new Istio Control Plane need to be modified ?
3. Do any of the ports of the Istiod needs to be changed ?
4. Does all the MutatingWebhookConfiguration and ValidatingWebhookConfiguration needs to be changed ?
5. Does listened-namespaces need to be modified to tell each Control plane which data plane namespace is part of it (or is a member) ?

Probably we need a CRD like MultiMesh

But at least for immediate can we have some hack or suggestion to make this work please ?

**Comment by jmazzitelli** [comment]
I don't know how Istio supports multi-tenancy today (if it does, or does not, I do not know), but I can tell you how Kiali can be deployed in a multi-tenant scenario - below is how it works when deployed inside Maistra (which does support multi-tenancy - and hence Kiali must work within that environment as well). This is how it will be done when upstream Istio supports multi-tenancy.

Install the Kiali Operator - you only install one operator in your cluster (as is typical of most Kubernetes operators). The operator will be able to install/manage/uninstall multiple installations of Kiali (across all tenants). If you have OLM installed, OLM will be able to install the operator for you, otherwise, install the operator yourself in some namespace and make sure you tell the operator to ["watch all namespaces"](https://github.com/kiali/kiali-operator/blob/v1.18.0/deploy/deploy-kiali-operator.sh#L405-L407) (e.g. `-own '""`').

When installing Kiali in a tenant, create a [Kiali CR](https://github.com/kiali/kiali-operator/blob/v1.18.0/deploy/kiali/kiali_cr.yaml) in the tenant's Istio control plane namespace (e.g. istio-system). The Kiali CR has a configuration setting called `spec.deployment.accessible_namespaces`. When normally installed in Istio today (i.e. in a single-tenant-per-cluster scenario), you set this to `['**']` to indicate Kiali is to be given access to all namespaces in the cluster. If you are in a multi-tenant environment, however, you instead set this value to a list of namespaces (i.e. the namespaces in the tenant - a tenant is assumed to have one or more namespaces that make up its mesh). With this information, the Kiali Operator will create the necessary roles that provide Kiali access to only those namespaces thus limiting access to Kiali to that tenant only.

Note that the namespace where you deploy Kiali (by default, this is where you put the Kiali CR) is assumed by default to be the Istio control plane namespace (e.g. istio-system). This is where Kiali expects to see some Istio components like Prometheus, which will be expected to contain the tenant's telemetry.

That's basically all you need to install Kiali in an Istio multi-tenant environment.

**Comment by sb1975** [comment]
Yes, thanks for the details on Kiali, but I am looking for the direction and steps from Istio Community for the control plane please.

**Comment by therealmitchconnors** [comment]
These docs address canarying istio control planes, which is intended as a temporary scenario, but you might find the steps apply to running two different control planes in the same cluster: https://istio.io/latest/blog/2020/multiple-control-planes/

**Comment by sb1975** [comment]
that doesnt help unfortunately.
First it installs two control plane within same namespace.
Secondly I think it uses same certificates and changing the namespace for each control plane brings us back to the start of the problem I have listed above. So thanks, but this doesnt help.

**Comment by myidpt** [comment]
@sb1975 I think you need to make sure all the global config should be avoided, and every config with control plane namespace "istio-system" alternated. Did you use auto sidecar injection? If so, that may be an issue, you may need to manually inject the sidecars to point to the designated control planes.

**Comment by myidpt** [comment]
cc @costinm

**Comment by sb1975** [comment]
You mean not use istio-system namespace at all ? that's what I did, I used different namespaces. Can you please elaborate what you mean by the global config.
Now reg. auto side car injection, I had a commmunity discussion on this (and there is this issue https://github.com/istio/istio/issues/15619) and what I understand is - you can restrict sidecar-injection in a specific pod annotation but you cannot selectively annotate a pod and do manual sidecar injection- We had discussion on this in the Community Meeting and everybody had same opinion. Ref: https://docs.google.com/document/d/14ZCWMfEV9MPDYrjhKYMErVXHTZrSwJNMm1ztKo8efPw/edit#
Date: 2020-06-11

**Comment by bdschaap** [comment]
Is this a supported scenario (multiple control planes on a single cluster)?  I saw that this was listed as [Done](https://github.com/orgs/istio/projects/6#card-44924385) but don't see it in a release.
