### ISSUE TITLE
Error creating the istiocontrolplane in a different namespace

### ISSUE THREAD

**Issue by sb1975** [istio/istio#24413]
**Bug description**
When I just modify the namespace in the IstioOperator CR, it does not create the Control plane components in any other namespace other than the istio-system.

There should be simple mechanism to change the namespace.

$ kubectl apply -f - <<EOF
> apiVersion: install.istio.io/v1alpha1
> kind: IstioOperator
> metadata:
>   namespace: istio-system-mobility-gn
>   name: istiocontrolplane-gn
> spec:
>   profile: demo
> EOF
istiooperator.install.istio.io/istiocontrolplane-gn created
esudbat@istio-multitenancy:~$ kubectl get ns
NAME                       STATUS   AGE
default                    Active   15m
istio-operator             Active   14m
istio-system-mobility-gn   Active   13m
kube-node-lease            Active   15m
kube-public                Active   15m
kube-system                Active   15m
esudbat@istio-multitenancy:~$ kubectl get all -n istio-system-mobility-gn
No resources found in istio-system-mobility-gn namespace.
esudbat@istio-multitenancy:~$
esudbat@istio-multitenancy:~$
esudbat@istio-multitenancy:~$ kubectl get all -n istio-system-mobility-gn
No resources found in istio-system-mobility-gn namespace.

[ ] Configuration Infrastructure
[x] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by erdun** [comment]
The namespace operator to watch is determined by env `WATCH_NAMESPACE` default value is `istio-system`,  or you can run `istioctl operator init --istioNamespace ${namesapce}`

**Comment by sb1975** [comment]
that doesnt work either
$ istioctl operator init --istioNamespace istio-system1
Using operator Deployment image: docker.io/istio/operator:1.6.0
✔ Istio operator installed
✔ Installation complete
$ kubectl get all -n istio-system1
No resources found in istio-system1 namespace.
$ cat samples/operator/default-install.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system1
  name: istio-operator
spec:
  profile: default

$ kubectl get all -n istio-system
No resources found in istio-system namespace.
$ kubectl get all -n istio-system1
No resources found in istio-system1 namespace.

**Comment by erdun** [comment]
Sorry, istiocontrolplane's namespace is defined by global.istioNamespace in IstioOperator

**Comment by sb1975** [comment]
This one is also related https://github.com/istio/istio/issues/24450
