### ISSUE TITLE
Support CNCF networks annotation for non chained CNI

### ISSUE THREAD

**Issue by knrc** [istio/istio#24425]
**Describe the feature request**

At present non-chained CNI is used to configure multus integration, this PR adds support for the CNCF networks annotation and enables the application deployments to specify multiple networks with istio CNI being appended to the list.

Note the documentation for installing with CNI current requires overriding cni.chained to false and specifying sidecarInjectorWebhook.injectedAnnotations to include the networks annotation, the second part will no longer be required after this issue is addressed.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by brian-avery** [comment]
@knrc Is this waiting for something? I see it's still open but the PR is merged.

**Comment by knrc** [comment]
@brian-avery I have no objections to closing this, I'm not aware of anything which would still be outstanding.

**Comment by knrc** [comment]
@brian-avery sorry, just realised that an update will be required for the OpenShift installation docs so it's worth keeping this open until that has been submitted

**Comment by nrjpoddar** [comment]
@knrc looks like 1.5 cherry-pick failed: https://github.com/istio/istio/issues/24478

**Comment by knrc** [comment]
@nrjpoddar I think the backport to 1.5 needs to be discussed with @sdake, he recommended against doing this

**Comment by howardjohn** [comment]
@knrc is this done now?

**Comment by knrc** [comment]
@howardjohn I didn't get the 1.5 changes in as we went back and reworked the changes to support both the flat and JSON formats.  We should submit a new PR to have these put upstream.

**Comment by howardjohn** [comment]
is that covered by #25746 or something else?

**Comment by knrc** [comment]
@howardjohn Yes it is, @luksa beat me to it :)

**Comment by knrc** [comment]
There may still be docs changes required for the OpenShift side, do you want to handle that here or on a separate issue?

**Comment by howardjohn** [comment]
I am fairly sure the docs are  fixed by #28076

**Comment by sdake** [comment]
> @nrjpoddar I think the backport to 1.5 needs to be discussed with @sdake, he recommended against doing this

If so I don't remember why. It may have been that 1.5 was leaving support soon and it wasn't worth the trouble, and updating the documentation in 1.5 couldn't be done once 1.6 was out as we used a frozen archive.

**Comment by sdake** [comment]
@howardjohn the profile was based upon istio.io docs which state to include this annotation. From my parsing of the issue, this annotation is no longer required as of 1.6, so shouldn't apply to 1.8.

@hickeyma can you test without the annotation, and if things are working well, submit a small PR to he profile? (and even istio.io if you want:)

Cheers,
-steve

**Comment by hickeyma** [comment]
@sdake I tested by removing the [annotations](https://github.com/istio/istio/blob/master/manifests/profiles/openshift.yaml#L18-L20) from the [OpenShift profile](https://github.com/istio/istio/blob/master/manifests/profiles/openshift.yaml) and the sample bookinfo app is failing:

```console
$ kubectl get pods
NAME                              READY   STATUS        RESTARTS   AGE
details-v1-5974b67c8-mk87g        0/2     Init:Error    0          9s
productpage-v1-64794f5db4-dkxgr   0/2     Terminating   1          16s
productpage-v1-64794f5db4-dvqcn   0/2     Init:0/1      0          8s
ratings-v1-c6cdf8d98-k7wsh        0/2     Init:Error    0          10s
reviews-v1-7f6558b974-4p4xv       0/2     Terminating   1          14s
reviews-v1-7f6558b974-kchts       0/2     Init:0/1      0          3s
reviews-v2-6cb6ccd848-4rp66       0/2     Terminating   1          12s
reviews-v2-6cb6ccd848-kmf5f       0/2     Init:0/1      0          3s
reviews-v3-cc56b578-84xpb         0/2     Terminating   1          12s
reviews-v3-cc56b578-ncb7h         0/2     Init:0/1      0          3s
```

It looks like it needs those annotations.
