### ISSUE TITLE
End user authn: add suport HMACSHA algorithm JWT

### ISSUE THREAD

**Issue by AtarisMio** [istio/istio#24421]
**Describe the feature request**

I'd like to use existing JWTs with `alg=HS512` or `alg=HS256` with Istio's end user authentication policies. Currently, the JWT authn filter will reject all JWTs with key type outside of ['EC', 'RSA'].

**Describe alternatives you've considered**

I found a repo [jwt_verify_lib](https://github.com/google/jwt_verify_lib) which implements many algorithms of JWT verification. Maybe we can use this repo as an external lib.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by incfly** [comment]
Feel free to look into JWT filter and proposes some solution (via a RFC doc documented in communtiy) if you want to drive this feature.

**Comment by incfly** [comment]
Not famliar with HS256 based JWT. I read the RFC and HMAC, so basically we are requiring a HMAC key obtained from Istiod to distribute to Envoy? How does typical your app distrubte pre-shared key used for hashing?

Current Istio distrubte JWK mostly for RSA public key. so it's not confidential data.

Also, I took a look of jwt_lib that is exactly what Envoy is using. And it seems not supporting HS256/512. There's very little we can do if so.

**Comment by skydoctor** [comment]
Can we please re-open this. This will benefit in RFC compliance. Envoy seems to support HS256, HS512 as per info here: https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/jwt_authn_filter. Can someone with more insight comment what is needed for istio to support these algos?

**Comment by mukeshkhattar** [comment]
+1 We need this feature as well. 

@skydoctor / @AtarisMio - I wonder if how you have solved this until we get Istio support. Any insights would be great!

> Can we please re-open this. This will benefit in RFC compliance. Envoy seems to support HS256, HS512 as per info here: https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/jwt_authn_filter. Can someone with more insight comment what is needed for istio to support these algos?

**Comment by skydoctor** [comment]
@mukeshkhattar, we haven't been able to solve this unfortunately.

**Comment by quaekr** [comment]
This is exceptionally useful as istio, when it receives *any* authorization headers at all, it will *always* evaluate them against a RequestAuthentication and even without one set, which will always return you:

```
JWT issuer is not configured
```

beyond annoying when you expect istio to be transparent.

**Comment by Kampe** [comment]
This is exceptionally useful as istio, when it receives any authorization headers at all, will always evaluate Authorization headers against a RequestAuthentication and even without one set, which in turn will always return you:
```
JWT issuer is not configured
```
beyond annoying when you expect istio to be transparent.

**Comment by CooperWolfe** [comment]
+1, I need this feature as well to use the same JWT's I use in my REST API as my gRPC API.

**Comment by fedyiv** [comment]
Hi! Are there any plans to implement this feature?
