### ISSUE TITLE
Distributed tracing docs - discuss app-based reporting

### ISSUE THREAD

**Issue by maflaven** [istio/istio#24436]
**Describe the feature request**
While the docs do mention [trace context population within apps](https://istio.io/docs/tasks/observability/distributed-tracing/overview/#trace-context-propagation), they don't mention how an app can integrate directly with `istio-tracing`. In-app use cases include:
- starting/ending spans
- adding tracer tags

It would be helpful to include examples of, or at least point to, jaeger client integration that mentions the need for something like a jaeger-agent sidecar to be able to report trace info within an app (since envoy isn't capable of receiving that info via app-sourced request?). Additionally, if Istio were to use the Jaeger operator, the [jaeger-agent could be injected automatically](https://www.jaegertracing.io/docs/1.18/operator/#auto-injecting-jaeger-agent-sidecars). Some tracing clients can report to a jaeger collector endpoint directly, so at least mentioning this would point users in the right direction.

**Describe alternatives you've considered**

[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Comment by dedsm** [comment]
yes please, I'm trying to figure out how to make it and finding info on this is particularly difficult.
