### ISSUE TITLE
central istiod: remote cluster 's Istio resources need to be propagated to sidecars

### ISSUE THREAD

**Issue by linsun** [istio/istio#24430]
When using #22934 to manage remote plane and user doesn't have access to the cluster istiod runs, user won't be able to apply any istio resources and get the resources recognized by central istiod and pushed to the sidecars.

In this model when the istiod cluster is reserved for running the control plane without any data plane, user is expecting the same experience where they apply istio resources to the cluster and expect the resource to be translated with the configs for sidecars, without the need to applying the istio resources to the istiod cluster (they won't have permission either).

I propose we need to allow istiod to consume the remote cluster's istio resources in this case.  possibly starting with a simple configuration to specify consume the remote k8s cluster istio configs (instead of the current cluster where istiod runs).

cc @howardjohn @costinm @irisdingbj @GregHanson @esnible @nmittler @hzxuzhonghu thoughts?

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by hzxuzhonghu** [comment]
One thing I am concerned about is that users may create conflicted configs in different clusters,  like gateway.

So in order to support this we may need to be able to specify cluster local configs, maybe extend `ExportTo`

**Comment by irisdingbj** [comment]
is `ExportTo` supported by all of our customer resources? If not, need another way to solve this...
Or I am thinking can we just support 1 central istiod  vs 1 remote cluster? In this way no conflict existed.

**Comment by nmittler** [comment]
@linsun I don't think I agree that this is a problem, in fact it's what we want. We just need to make it clear through our docs that configuration should only applied to "master" clusters (i.e. clusters that have a control plane). The fact that we've removed the control plane entirely from remote clusters just makes this more clear.

Overall, this is a good thing.

**Comment by linsun** [comment]
@nmittler I agree this is fine if users will be deploy workloads to both master and remote clusters and apply istio resources.  This won't work when the istiod cluster is administered by admin A and user B is deploying microservices and apply istio resources to remote cluster while not having any access to the istiod cluster.

**Comment by nmittler** [comment]
@linsun it feels like we need an RFC for this and to move the discussion there.

My initial thought is that if a team decided to architect the system this way, configuration changes should likely involve the admin.  For example:

- Is the config being applied to a user namespace or `istio-system`?
  - If a user namespace, perhaps the admin need only confirm the creation of the namespace in the master cluster and grant permission to user B?
  - If `istio-system`, perhaps config should be sent to the admin for review and then ultimately applied by the admin?

**Comment by linsun** [comment]
@nmittler this was covered in this [doc](https://docs.google.com/document/d/1r58al52otp1uvB7YFHh8ifA_78hYeyd0hNLq4qPDSUM/edit), scenario 2 where there is no workload deployed in the istiod cluster.   I would be happy to resurface this for discussion in an upcoming env WG mtg if you still have questions.

We plan to leverage this to provide a solution for our users where users don't need to worry about upgrading control planes.  They won't ask us for permissions when they apply for istio resources.  The istio resources can be applied to their users' namespaces and namespace admin within the users' org will be able to create namespaces.  Configs may be sent for review within the admin of the remote cluster but won't be needed to the admin of the istiod cluster.

**Comment by therealmitchconnors** [comment]
I am in favor of this idea.  I'd like to point out that we will need to request read privileges for istiod on the Remote Cluster, along with update privileges to the Status subresource on all istio resources.

**Comment by linsun** [comment]
@therealmitchconnors thanks for the input!  We already have read privilege on remote cluster by default for multicluster deployment (excluding replicated control plane model) and when centralIstiod is enabled, we are currently giving update privilege to a few things such as patching web hooks, and create istio ca root cert ConfigMap in each namespace.  Would be reasonable to extend that to status, if the community plans to continue track/record the status for istio resources.

**Comment by howardjohn** [comment]
I agree with Nate. There are two cases:

* "Single cluster" central Istiod, where Istiod runs in a different cluster but there is *one* associated workload cluster, which has config. For this case, we are NOT really multicluster, we are just "a different cluster", and we pass a single kubeconfig file and use the single cluster path. This is the same as running on your laptop for example
* True multicluster, where what Nate says above applies

In both cases these changes aren't really needed?

**Comment by linsun** [comment]
@nmittler sorry I missed your comment earlier. You are correct that it would be an organization who is operating the mesh control plane for users, and there could still be mesh admin role just to manage data plane and approve istio configurations.  So the organization boundary is:
- control plane (istiod): managed by org A
- data plane: managed by org B, which includes mesh admin and devOps, secOps team etc.

I agree with @howardjohn 's two cases, single cluster central istiod and multicluster central istiod where in this case you could also dedicate central istiod control cluster not running any workloads, or allow workloads.  I think both cases are covered in the updated design doc linked from #22934.

I'm closing this WI as we don't really need it for now with the newly updated design doc.
