### ISSUE TITLE
Central istiod: Remote clusters need access to control plane configmap (kube-inject)

### ISSUE THREAD

**Issue by PatrickDuncan** [istio/istio#24438]
**Describe the feature request**

Hi! With the [central istiod/remote control plane setup](https://github.com/istio/istio/wiki/Central-Istiod-manages-remote-data-plane) it's not possible to use `istioctl kube-inject` because the istio configmap lives in the control plane.

This blocks the data plane from manually injecting Envoy with deployments.

> Error: could not read valid configmap "istio" from namespace "istio-system": configmaps "istio" not found - Use --meshConfigFile or re-run kube-inject with `-i <istioSystemNamespace> and ensure valid MeshConfig exists

https://github.com/istio/istio/blob/65bd2ac632cbd6ec8e3fd85bb9874f685aea0cfd/istioctl/cmd/kubeinject.go#L201-L268

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**
To fix this I think either:
1. When installing Istio, the necessary configmaps/resources need to be copied over to the remote clusters
2. `kube-inject` pulls from the central control plane

**Comment by linsun** [comment]
While user can use `istioctl Kube-inject` cmd by passing the mesh config file, it is not obvious to figure it out, neither it is obvious to get the Istio mesh config file without accessing to the istiod cluster.

I suggest we install istio cm as part of istiod-remote chart to fix this.   We can do it similarly as how we install the injection template.

**Comment by howardjohn** [comment]
This is now part of the chart
