### ISSUE TITLE
istioctl kube-inject: Pull YAML from URL

### ISSUE THREAD

**Issue by PatrickDuncan** [istio/istio#24439]
**Describe the feature request**

It would be great if something like `istioctl kube-inject -f https://raw.githubusercontent.com/istio/istio/master/samples/httpbin/httpbin.yaml` worked the same as `kubectl apply -f <URL>`. Currently it only handles local files:

> Error: open https://raw.githubusercontent.com/istio/istio/master/samples/httpbin/httpbin.yaml: no such file or directory

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Comment by howardjohn** [comment]
Is there any compelling reason to do this rather than `curl ...|istioctl`? I get kubectl does it so it's sort of consistent there but wasn't sure if there was more motivation

**Comment by PatrickDuncan** [comment]
There's no greater reason, I just thought it would be nice to have and consistent. Basically, I was surprised URLs were not supported
