### ISSUE TITLE
Istioctl manifest generate no longer produces a namespace in 1.6.0

### ISSUE THREAD

**Issue by XanderStrike** [istio/istio#24447]
**Bug description**

When attempting to apply yaml produced by `istioctl manifest generate` with a namespace set, it fails.

[X] Configuration Infrastructure
[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Steps to reproduce the bug**

`istioctl manifest generate -f values.yaml` where values is

```
apiVersion: install.istio.io/v1alpha2
kind: IstioOperator
spec:
  namespace: istio-system
```

Attempt to apply the manifest.

**Observed Behavior:**
It fails because the istio-system namespace does not exist

**Desired Behavior:**
The istio-system namespace is created and the install succeeds.

This used to work in 1.4, but it no longer works in 1.6. This change is not mentioned in the changelogs or upgrade notes for 1.5 or 1.6, so I must assume it is a bug.

I did find that a line was added to [this section](https://istio.io/docs/setup/install/istioctl/#generate-a-manifest-before-installation) to create the namespace, but it's not particularly noticeable nor does it explain why that's changed.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.6

**How was Istio installed?**
N/A

**Environment where bug was observed (cloud vendor, OS, etc)**
N/A

**Comment by howardjohn** [comment]
It was intended. See https://github.com/istio/istio/pull/22549

Sorry it was missed in the release notes

**Comment by howardjohn** [comment]
> - ***Changed*** the Istio installation to no longer manage the installation namespace, allowing more flexibility.

This is in the release notes, maybe not as explicit as it could be though

**Comment by XanderStrike** [comment]
Thanks for the response, yeah we definitely missed that. I think the reasoning is sound.

I find this strange though:

> The user experience here is not impacted, as we will create the namespace if it doesn't exist.

Which seems like a direct contradiction of the sentence before it:

> Managing a namespace is outside of the scope of an Istio installation.

In any case, it'd be great if [the docs](https://istio.io/docs/reference/commands/istioctl/#istioctl-manifest-generate) or the help text for manifest generate would list the things it doesn't do that `istioctl install` does. If that exists I'd love a pointer to it.

**Comment by howardjohn** [comment]
> The user experience here is not impacted, as we will create the namespace if it doesn't exist.

This is only for `istioctl install`, meant for backwards compatibility only. I sent https://github.com/istio/istio.io/pull/7485 to also clarify it doesn't auto detect settings

**Comment by XanderStrike** [comment]
Awesome, closing this issue in favor of that docs change. Thanks!
