### ISSUE TITLE
Generated manifest should be stable

### ISSUE THREAD

**Issue by esnible** [istio/istio#24442]
The output of `istioctl manifest generate` is not "stable".

To reproduce, run `diff <(istioctl manifest generate) <(istioctl manifest generate)` a few times.  Sometimes there will be a difference.  The difference isn't functional.  It is the order of the CRDs.  (They could be sorted to eliminate the instability.)

This isn't a bug and it isn't necessary.  It would be helpful to fix.

Motivation: I ran into it testing various options like this: `diff <(istioctl manifest generate) <(istioctl manifest generate --set values.global.imagePullPolicy=Always)`.  Having stable output makes it much easier to understand how differences in input affect output.

**Comment by howardjohn** [comment]
Interesting, I thought we did some efforts to make it stable. Maybe that was only done for tests? this is definitely useful if people are checking this into ci

**Comment by esnible** [comment]
@howardjohn The only thing moving is the IstioOperator CRD, which was added after the other CRDs.  I suspect it missed those efforts.

**Comment by adiprerepa** [comment]
Interesting, I wrote a script to run it 50 times and I didnt get any diff? weird. this is on istioctl 1.5.4.

**Comment by esnible** [comment]
@adiprerepa @howardjohn @ostromart I can confirm 1.5.4 does not have the problem.  1.6.x does.

I'm seeing something I can't explain.  Tested with 1.6.0 and 1.6.1.

If I use Istio 1.6.0 or 1.6.1 binary, on Mac, I see the unstable manifest problem:
```
cd /tmp
curl -L https://git.io/getLatestIstio | ISTIO_VERSION=1.6.1 sh -
cd istio-1.6.1
diff <(bin/istioctl manifest generate) <(bin/istioctl manifest generate)
```

If I use `--charts`, I **don't** see it:
```
// this output is stable:
diff <(bin/istioctl manifest generate --charts ~/go/src/istio.io/istio/manifests) <(bin/istioctl manifest generate --charts ~/go/src/istio.io/istio/manifests)
```

I couldn't reproduce the problem on my own builds, because I always use `--charts`.

**Comment by ostromart** [comment]
We do want the output to be stable (for folks that want to text diff output manifests) so this is a regression. There is a test to catch this and I wonder if it's just getting ignored as a flake.
