### ISSUE TITLE
Error installing Istio using istioctl(to change default istio-system namespace)

### ISSUE THREAD

**Issue by sb1975** [istio/istio#24450]
**Bug description**
Error installing Istio using istioctl for IStio 1.6.

Error from server (NotFound): error when creating "/home/esudbat/generated-manifest.yaml": the server could not find the requested resource (post peerauthentications.security.istio.io)

Executed below steps :
istioctl manifest generate --set profile=demo > $HOME/generated-manifest.yaml
kubectl apply -f $HOME/generated-manifest.yaml

configmap/istio-grafana-configuration-dashboards-istio-mesh-dashboard created
configmap/istio-grafana-configuration-dashboards-istio-performance-dashboard created
configmap/istio-grafana-configuration-dashboards-istio-service-dashboard created
configmap/istio-grafana-configuration-dashboards-istio-workload-dashboard created
configmap/istio-grafana-configuration-dashboards-mixer-dashboard created
configmap/istio-grafana-configuration-dashboards-pilot-dashboard created
configmap/istio-grafana created
deployment.apps/grafana created
service/grafana created
clusterrole.rbac.authorization.k8s.io/kiali created
clusterrole.rbac.authorization.k8s.io/kiali-viewer created
clusterrolebinding.rbac.authorization.k8s.io/kiali created
configmap/kiali created
secret/kiali created
deployment.apps/kiali created
service/kiali created
serviceaccount/kiali-service-account created
clusterrole.rbac.authorization.k8s.io/prometheus-istio-system created
clusterrolebinding.rbac.authorization.k8s.io/prometheus-istio-system created
configmap/prometheus created
deployment.apps/prometheus created
service/prometheus created
serviceaccount/prometheus created
deployment.apps/istio-tracing created
service/jaeger-query created
service/jaeger-collector created
service/jaeger-collector-headless created
service/jaeger-agent created
service/zipkin created
service/tracing created
clusterrole.rbac.authorization.k8s.io/istiod-istio-system created
clusterrole.rbac.authorization.k8s.io/istio-reader-istio-system created
clusterrolebinding.rbac.authorization.k8s.io/istio-reader-istio-system created
clusterrolebinding.rbac.authorization.k8s.io/istiod-pilot-istio-system created
serviceaccount/istio-reader-service-account created
serviceaccount/istiod-service-account created
validatingwebhookconfiguration.admissionregistration.k8s.io/istiod-istio-system created
customresourcedefinition.apiextensions.k8s.io/httpapispecs.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/httpapispecbindings.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/quotaspecs.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/quotaspecbindings.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/destinationrules.networking.istio.io created
customresourcedefinition.apiextensions.k8s.io/envoyfilters.networking.istio.io created
customresourcedefinition.apiextensions.k8s.io/gateways.networking.istio.io created
customresourcedefinition.apiextensions.k8s.io/serviceentries.networking.istio.io created
customresourcedefinition.apiextensions.k8s.io/sidecars.networking.istio.io created
customresourcedefinition.apiextensions.k8s.io/virtualservices.networking.istio.io created
customresourcedefinition.apiextensions.k8s.io/workloadentries.networking.istio.io created
customresourcedefinition.apiextensions.k8s.io/attributemanifests.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/handlers.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/instances.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/rules.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/clusterrbacconfigs.rbac.istio.io created
customresourcedefinition.apiextensions.k8s.io/rbacconfigs.rbac.istio.io created
customresourcedefinition.apiextensions.k8s.io/serviceroles.rbac.istio.io created
customresourcedefinition.apiextensions.k8s.io/servicerolebindings.rbac.istio.io created
customresourcedefinition.apiextensions.k8s.io/authorizationpolicies.security.istio.io created
customresourcedefinition.apiextensions.k8s.io/peerauthentications.security.istio.io created
customresourcedefinition.apiextensions.k8s.io/requestauthentications.security.istio.io created
customresourcedefinition.apiextensions.k8s.io/adapters.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/templates.config.istio.io created
customresourcedefinition.apiextensions.k8s.io/istiooperators.install.istio.io created
deployment.apps/istio-egressgateway created
poddisruptionbudget.policy/istio-egressgateway created
service/istio-egressgateway created
serviceaccount/istio-egressgateway-service-account created
deployment.apps/istio-ingressgateway created
poddisruptionbudget.policy/istio-ingressgateway created
role.rbac.authorization.k8s.io/istio-ingressgateway-sds created
rolebinding.rbac.authorization.k8s.io/istio-ingressgateway-sds created
service/istio-ingressgateway created
serviceaccount/istio-ingressgateway-service-account created
configmap/istio created
deployment.apps/istiod created
configmap/istio-sidecar-injector created
mutatingwebhookconfiguration.admissionregistration.k8s.io/istio-sidecar-injector created
poddisruptionbudget.policy/istiod created
service/istiod created
envoyfilter.networking.istio.io/metadata-exchange-1.4 created
envoyfilter.networking.istio.io/stats-filter-1.4 created
envoyfilter.networking.istio.io/metadata-exchange-1.5 created
envoyfilter.networking.istio.io/tcp-metadata-exchange-1.5 created
envoyfilter.networking.istio.io/stats-filter-1.5 created
envoyfilter.networking.istio.io/tcp-stats-filter-1.5 created
envoyfilter.networking.istio.io/metadata-exchange-1.6 created
envoyfilter.networking.istio.io/tcp-metadata-exchange-1.6 created
envoyfilter.networking.istio.io/stats-filter-1.6 created
envoyfilter.networking.istio.io/tcp-stats-filter-1.6 created
Error from server (NotFound): error when creating "/home/esudbat/generated-manifest.yaml": the server could not find the requested resource (post peerauthentications.security.istio.io)

Many pods stay in ContainerCreating STATUS

NAME                                        READY   STATUS              RESTARTS   AGE
pod/grafana-54b54568fc-mxzf2                1/1     Running             0          8m6s
pod/istio-egressgateway-f97cf498c-v9mcb     0/1     ContainerCreating   0          8m3s
pod/istio-ingressgateway-7d8cdc4ddc-g5w5l   0/1     ContainerCreating   0          8m2s
pod/istio-tracing-9dd6c4f7c-dgpvk           1/1     Running             0          8m5s
pod/istiod-85d7db7d57-mj24h                 0/1     ContainerCreating   0          8m2s
pod/kiali-d45468dc4-5l757                   1/1     Running             0          8m4s
pod/prometheus-5bb9c77d74-sz42k             0/2     ContainerCreating   0          8m4s

$ kubectl describe pod istiod-85d7db7d57-mj24h -n istio-system
Events:
  Type     Reason       Age                   From                   Message
  ----     ------       ----                  ----                   -------
  Normal   Scheduled    8m35s                 default-scheduler      Successfully assigned istio-system/istiod-85d7db7d57-mj24h to istio-multi2
  Warning  FailedMount  8m34s                 kubelet, istio-multi2  MountVolume.SetUp failed for volume "istiod-service-account-token-xjjj5" : failed to sync secret cache: timed out waiting for the condition
  Warning  FailedMount  8m34s                 kubelet, istio-multi2  MountVolume.SetUp failed for volume "inject" : failed to sync configmap cache: timed out waiting for the condition
  Warning  FailedMount  8m34s                 kubelet, istio-multi2  MountVolume.SetUp failed for volume "cacerts" : failed to sync secret cache: timed out waiting for the condition
  Warning  FailedMount  6m32s                 kubelet, istio-multi2  Unable to attach or mount volumes: unmounted volumes=[istio-token], unattached volumes=[local-certs cacerts inject istiod-service-account-token-xjjj5 config-volume istio-token]: timed out waiting for the condition
  Warning  FailedMount  4m15s                 kubelet, istio-multi2  Unable to attach or mount volumes: unmounted volumes=[istio-token], unattached volumes=[config-volume istio-token local-certs cacerts inject istiod-service-account-token-xjjj5]: timed out waiting for the condition
  Warning  FailedMount  117s                  kubelet, istio-multi2  Unable to attach or mount volumes: unmounted volumes=[istio-token], unattached volumes=[istiod-service-account-token-xjjj5 config-volume istio-token local-certs cacerts inject]: timed out waiting for the condition
  Warning  FailedMount  18s (x12 over 8m33s)  kubelet, istio-multi2  MountVolume.SetUp failed for volume "istio-token" : failed to fetch token: the API server does not have TokenRequest endpoints enabled

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)*
Istio 1.6
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:38:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:30:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
istioctl manifest generate --set profile=demo > $HOME/generated-manifest.yaml
kubectl apply -f $HOME/generated-manifest.yaml
**Environment where bug was observed (cloud vendor, OS, etc)**
ubuntu 18.04

**Comment by esnible** [comment]
Use `istioctl install` or `istioctl manifest apply` instead of `istioctl generate | kubectl apply`.

Your method should still work... IF you `kubectl apply` more than once.  (When everything is `apply` -ed in a single step the resources may appear out-of-order and custom resources may attempt to install before the resource description.)

**Comment by howardjohn** [comment]
Adding doc in https://github.com/istio/istio.io/pull/7485

**Comment by dkirrane** [comment]
Tried `istioctl manifest apply` and it works.
Is there an option to set the `jwtPolicy` in the IstioOperator manifest so that generate will work too?

**Comment by howardjohn** [comment]
Yep, in https://preliminary.istio.io/docs/ops/best-practices/security/#configure-third-party-service-account-tokens we document `--set values.global.jwtPolicy=first-party-jwt`. Which would correlate to

```
values:
  global:
    jwtPolicy: first-party-jwt
```

in the IOP manifest

**Comment by sb1975** [comment]
istioctl -i and -n are not honored, whats the difference really ? Its not clear - whats the purpose.. Anyway these dont work.

esudbat@istio:~/istio-1.6.1$ istioctl manifest apply -i istio-system1 -n istio-system1 --set profile=demo --set values.global.jwtPolicy=first-party-jwt
Detected that your cluster does not support third party JWT authentication. Falling back to less secure first party JWT. See https://istio.io/docs/ops/best-practices/security/#configure-third-party-service-account-tokens for details.
✔ Istio core installed
✔ Istiod installed
✔ Egress gateways installed
✔ Ingress gateways installed
✔ Addons installed
✔ Installation complete                                                                                                                                 esudbat@istio:~/istio-1.6.1$ kubectl get all -n istio-system1
No resources found in istio-system1 namespace.
esudbat@istio:~/istio-1.6.1$ kubectl get all -n istio-system
NAME                                        READY   STATUS    RESTARTS   AGE
pod/grafana-54b54568fc-pndc8                1/1     Running   0          109s
pod/istio-egressgateway-77f5cd5497-vgcbm    1/1     Running   0          110s
pod/istio-ingressgateway-6956964b69-trq64   1/1     Running   0          110s
pod/istio-tracing-9dd6c4f7c-pxv9z           1/1     Running   0          109s
pod/istiod-74f67f75d5-sbbc9                 1/1     Running   0          2m5s
pod/kiali-d45468dc4-7rwd9                   1/1     Running   0          109s
pod/prometheus-5767f54db5-v9kkx             2/2     Running   0          109s

NAME                                TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                                                                      AGE
service/grafana                     ClusterIP      10.108.28.136    <none>        3000/TCP                                                                     109s
service/istio-egressgateway         ClusterIP      10.100.105.197   <none>        80/TCP,443/TCP,15443/TCP                                                     110s
service/istio-ingressgateway        LoadBalancer   10.97.153.216    <pending>     15020:31998/TCP,80:31470/TCP,443:30917/TCP,31400:31525/TCP,15443:32344/TCP   110s
service/istiod                      ClusterIP      10.111.209.60    <none>        15010/TCP,15012/TCP,443/TCP,15014/TCP,53/UDP,853/TCP                         2m5s
service/jaeger-agent                ClusterIP      None             <none>        5775/UDP,6831/UDP,6832/UDP                                                   109s
service/jaeger-collector            ClusterIP      10.106.241.8     <none>        14267/TCP,14268/TCP,14250/TCP                                                109s
service/jaeger-collector-headless   ClusterIP      None             <none>        14250/TCP                                                                    109s
service/jaeger-query                ClusterIP      10.109.188.48    <none>        16686/TCP                                                                    109s
service/kiali                       ClusterIP      10.103.126.241   <none>        20001/TCP                                                                    109s
service/prometheus                  ClusterIP      10.109.176.252   <none>        9090/TCP                                                                     109s
service/tracing                     ClusterIP      10.108.64.0      <none>        80/TCP                                                                       109s
service/zipkin                      ClusterIP      10.103.117.38    <none>        9411/TCP                                                                     109s

NAME                                   READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/grafana                1/1     1            1           110s
deployment.apps/istio-egressgateway    1/1     1            1           110s
deployment.apps/istio-ingressgateway   1/1     1            1           111s
deployment.apps/istio-tracing          1/1     1            1           109s
deployment.apps/istiod                 1/1     1            1           2m5s
deployment.apps/kiali                  1/1     1            1           109s
deployment.apps/prometheus             1/1     1            1           109s

NAME                                              DESIRED   CURRENT   READY   AGE
replicaset.apps/grafana-54b54568fc                1         1         1       109s
replicaset.apps/istio-egressgateway-77f5cd5497    1         1         1       110s
replicaset.apps/istio-ingressgateway-6956964b69   1         1         1       111s
replicaset.apps/istio-tracing-9dd6c4f7c           1         1         1       109s
replicaset.apps/istiod-74f67f75d5                 1         1         1       2m5s
replicaset.apps/kiali-d45468dc4                   1         1         1       109s
replicaset.apps/prometheus-5767f54db5             1         1         1       109s

**Comment by sb1975** [comment]
Also the commands to clean up needs to be simplified please.
https://github.com/istio/istio/issues/24497

**Comment by hbeffge** [comment]
Seems like I'm missing something.

FYI:
- `basis.yaml` contains all control plane relevant config
- `gw*.yaml` contains one gateway with individual config
- both of `kind: IstioOperator`

Here the workflow I used so far:
1. install istio via `istioctl manifest apply -f basis.yaml`
2. add a gateway via `istioctl manifest generate -f gw1.yaml | kubectl apply -f -`
3. repeat step 2 after a new gateway is required

This does not work like described above.

Changed my workflow to the following:
1. install istio via `istioctl install -f basis.yaml`
2. add a gateway via `istioctl install -f basis.yaml -f gw1.yaml`
3. repeat adding step 2. (adding new `-f gw*.yaml`) for each new gateway

=> This results in removal of all gateways before the last

I guess my question is: I am missing in the docs a best practice to incrementaly add/change only certain parts of istio.
Is this OK here or should I create a new issue in the istio.io repo?

**Comment by hustshawn** [comment]
This is quite annoying when getting the error whenever I wanna customize the istio config.
```
 MountVolume.SetUp failed for volume "istio-token" : failed to fetch token: the API server does not have TokenRequest endpoints enabled
```
So what exactly the problem is? how come this issue is resolved?

**Comment by hustshawn** [comment]
It's easy to reproduce the stuck scenario.
```
bin/istioctl profile dump  > customize.yaml 

# Even if you change nothing on the customize.yaml
bin/istioctl install -f customize.yaml   
```
```
Detected that your cluster does not support third party JWT authentication. Falling back to less secure first party JWT. See https://istio.io/docs/ops/best-practices/security/#configure-third-party-service-account-tokens for details.
✔ Istio core installed                                                                                              
- Processing resources for Istiod. Waiting for Deployment/istio-system/istiod    
```
The new istiod pod would be stuck at `ContainerCreating` stage. 
```
NAME                                        READY   STATUS              RESTARTS   AGE
pod/istio-ingressgateway-859fdf8486-s62ct   1/1     Running             0          18m
pod/istiod-5c7446f47d-gmtmh                 1/1     Running             0          14m
pod/istiod-7744bc8dd7-6jtg4                 0/1     ContainerCreating   0          3m20s
```

**Comment by howardjohn** [comment]
See the mentioned link in the error message: https://istio.io/docs/ops/best-practices/security/#configure-third-party-service-account-tokens. It explains the issue and mitigation steps

**Comment by hustshawn** [comment]
@howardjohn Thanks for your hint. I added these lines in the `customize.yaml` and it works now.
```
  values:
    global:
      jwtPolicy: first-party-jwt
```
