### ISSUE TITLE
 Make proxyv2 image building operations universal

### ISSUE THREAD

**Issue by wangfakang** [istio/istio#24457]
**Describe the feature request**

The current build script for the `proxyv2` image has some logic hardcoded, such as https://github.com/istio/istio/blob/master/bin/init.sh#L220. I hope this script could more general, for example, it can be via parameter specifies the name of the sidecar, which is convenient for compiling other data planes.

**Describe alternatives you've considered**

As mentioned above.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
https://github.com/istio/istio/pull/25146
