### ISSUE TITLE
Istio support of envoy ext_authz (external authorisation) doesn't support per route configuration

### ISSUE THREAD

**Issue by Vkamnev** [istio/istio#24462]
The[ envoy.ext_authz](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/ext_authz_filter#config-http-filters-ext-authz) is very powerful and usefull feature, but in most of the cases user needs to add an exceptions, so some "operations" should be allowed to bypass it. In my case it is health check and liveness probe enpoints which should remain "public".

Below my example of envoy filter which is working (istion version 1.4.X):
<pre>
`apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ext-e2e
  namespace: hsbc-shpe-shpss-sct
spec:
  workloadLabels:
    app.kubernetes.io/instance: shp-mi-logging--zz-0 #target application
  filters:
    - filterConfig:
        http_service:
          server_uri:
            uri: http://platform-e2e-auth-1.hsbc-shpe-shpss-sct.svc.cluster.local
            cluster: outbound|80||platform-e2e-auth-1.hsbc-shpe-shpss-sct.svc.cluster.local
            timeout: 1s
            failure_mode_allow: false
          authorization_request:
            allowed_headers:
              patterns:
                - prefix: X-HSBC
          path_prefix: "/auth"
          include_peer_certificate: true
      insertPosition:
        index: FIRST
      listenerMatch:
        listenerType: SIDECAR_INBOUND
        listenerProtocol: HTTP
      filterType: HTTP
      filterName: envoy.ext_authz
`
</pre>
The only thing - there is no way to add an exception during the filter creationm like in case of AuthorizationPolicies for example.
The thing become even more compliated if i will try to "patch" an existing filter(the one above) to add "per route configuration". I've tried different approaches like the one below:
<pre>
`apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: skip-routes
  namespace: hsbc-shpe-shpss-sct
spec:
  workloadLabels:
    app.kubernetes.io/instance: shp-mi-logging--zz-0
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: "envoy.http_connection_manager"
              subFilter:
                name: "envoy.ext_authz"
      patch:
        operation: MERGE
        value:
          per_filter_config:
            envoy.ext_authz:
              disabled: true`
</pre>
To disable it at all for example - it doesn't work, i looked for example on "envoy" itself, but the schemas looks to be very different (envoy and istio), so the envoy ones doesn't even compiles.
I've tried to apply it not only to HTTP filter, but to VIRTUAL_HOST, ROUTE_CONFIGURATION etc, with the same negative outcome

The solution proposed [here](https://discuss.istio.io/t/envoy-filter-per-filter-config/4219/5) doesn't even compile
**Describe alternatives you've considered**
Alternative will be to provide operations to exclude ext_authz in teh same way they are configured in Authorisation policies:
-HTTP method(s)
-path(s)
to exclude, so the respective jaml section will be translated into JSON configuration of envoy filter created.

If someone knows how to set up ext_authz per route on istio version 1.4.X 1.5.X - any help will be appreciated

Envoy
**Additional context**
External authorisation

**Comment by mstrYoda** [comment]
Is there an update about this issue? We need to disable ext_authz for some paths.

**Comment by mfamador** [comment]
This would be very useful because right now or have to associate it to the whole gateway or to the workloads. 
In the first case, all the requests go through the ext_authz app, even if we don't want to use the auth ervice, and in the second case, we need to figure out if the request came from the gateway or from another internal service, in which case we wouldn't want to use authorization service, for instance.

**Comment by mstrYoda** [comment]
> This would be very useful because right now or have to associate it to the whole gateway or to the workloads.
> In the first case, all the requests go through the ext_authz app, even if we don't want to use the auth service for a particular virtual service, and in the second case, we need to figure out if the request came from the gateway or from another internal service, in which case we wouldn't want to use authorization service, for instance.

In another issue, I found this answer useful, we are waiting for that pr's to be merged: https://github.com/istio/istio/issues/26805#issuecomment-693615388

**Comment by mfamador** [comment]
Thank you @mstrYoda!
