### ISSUE TITLE
Prepare Release-1.7 branches

### ISSUE THREAD

**Issue by jacob-delgado** [istio/istio#24473]
This issue aims to track all steps needed to prepare the release 1.7 branches/builds.

Please add all steps taken here so we can document for future releases

-  [x] Set up release manager team (owner: JimmyCYJ) - Make sure the new team has write access to the repositories.  
- [x] Update dependencies. This must be done **before branching** so that PRs can be easily backported later. (owner: JimmyCYJ https://github.com/istio/istio/pull/25707)
  Run the following command in istio/istio `UPDATE_BRANCH=master ./bin/update_deps.sh; make gen`
- [x] Adjust istio/proxy to correct version of istio/envoy (https://github.com/istio/proxy/pull/2938)
- [x] Create a `release-1.7` branch in every Istio repo - run commands `export org=xyz ; export repo=xyz ; (git clone git@github.com:${org}/${repo}.git && cd $repo && git checkout -b release-1.7 && git push --set-upstream origin release-1.7)`.
  - [x] istio/istio
  - [x] istio/pkg
  - [x] istio/api
  - [x] istio/proxy
  - [x] istio/envoy
  - [x] istio/client-go
  - [x] istio/tools
  - [x] istio/common-files
  - [x] istio/gogo-genproto
  - [x] istio/release-builder
  - [x] Explicitly skipped: istio-releases/pipeline, istio/tests, istio/istio.io, istio/test-infra
- [x] Set up prow on release branches (owner: howardjohn) `go run generate.go branch 1.7` https://github.com/istio/test-infra/pull/2821
- [x] Set up branch protection (owner: howardjohn). Modify prow/config.yaml in test-infra to add release manages as owners for branch. https://github.com/istio/test-infra/pull/2820
- [x] Update all repos that point to master branch of another repo to point to the release branch. `master-latest-daily` -> `1.7-dev` (see https://discuss.istio.io/t/deprecation-notice-daily-builds/3991), `latest` -> `1.7-dev`, `git clone master` to `git clone release-1.5`, etc. Commit a PR into every `release-1.7` branch to modify every `CODEOWNERS` to contain only the release managers for this release. Command: `export org=xyz ; export repo=xyz ; (git clone git@github.com:${org}/${repo}.git && cd $repo && git checkout release-1.7 && git checkout -b release-1.7-codeowners && echo '* @istio/release-managers-1-7' > CODEOWNERS && git add CODEOWNERS && git commit -m 'Set release managers as CODEOWNERS for release-1.7' && git push --set-upstream origin release-1.7-codeowners)`.
  - [x] istio/istio (https://github.com/istio/istio/pull/25715)
  - [x] istio/pkg (https://github.com/istio/pkg/pull/195)
  - [x] istio/api (https://github.com/istio/api/pull/1544)
  - [x] istio/envoy (https://github.com/istio/envoy/pull/239)
  - [x] istio/proxy (https://github.com/istio/proxy/pull/2932)
  - [x] istio/client-go (https://github.com/istio/client-go/pull/206)
  - [x] istio/tools (https://github.com/istio/tools/pull/1097)
  - [x] istio/common-files (https://github.com/istio/common-files/pull/285)
  - [x] istio/gogo-genproto (https://github.com/istio/gogo-genproto/pull/112)
  - [x] istio/release-builder (https://github.com/istio/release-builder/pull/324)
  - [x] istio/release-builder branch change in build.sh too! (https://github.com/istio/release-builder/pull/325)
- [x] Update common-files in _new release_. You first have to manually update the _common/Makefile.common.mk_ *update-common* target to point to the _new release_ and then run 'make update-common'. It may be that this step could be combined in the prior step in the 'make update-common' was done before the branch.
  - [x] istio/common-files should have the branch updated above. (https://github.com/istio/common-files/pull/286)
  - [x] istio/istio (https://github.com/istio/istio/pull/25759)
  - [x] istio/pkg (https://github.com/istio/pkg/pull/196)
  - [x] istio/api (https://github.com/istio/api/pull/1547)
  - [x] istio/envoy (not needed)
  - [x] istio/client-go (https://github.com/istio/client-go/pull/208)
  - [x] istio/gogo-genproto (https://github.com/istio/gogo-genproto/pull/113)
  - [x] istio/proxy (https://github.com/istio/proxy/pull/2940)
  - [x] istio/release-builder (https://github.com/istio/release-builder/pull/325)
  - [x] istio/tools (https://github.com/istio/tools/pull/1098)
- [x] Bump master to version 1.8 (https://github.com/istio/istio/pull/25742)
- [x] Stop publishing `latest` tags (owner: JimmyCYJ https://github.com/istio/istio/pull/25764)
- [x] Add new label: cherrypick/release-1.8 (https://github.com/istio/bots/pull/237)
- [x] Run the long-running tests on the dev builds (owner: richardwxn)
- [x] Send an announcement on Discuss (https://discuss.istio.io/t/1-7-release-branch-cut/7610)
- [ ] Add release lock for release 1.7 in master branch of API repo. (https://github.com/istio/api/pull/1551)
- [x] Update build tools
  - [x] Update istio/tools to build with release-1.7 build image (owner: JimmyCYJ https://github.com/istio/tools/pull/1098)
  - [x] Update istio/common-files to set release-1.7 build image (owner: JimmyCYJ https://github.com/istio/common-files/pull/286, https://github.com/istio/common-files/pull/287)
- [x] Publish an alpha release 
  - [x] Trigger a 1.7 alpha build (JimmyCYJ: https://github.com/istio/release-builder/pull/328)
  - [x] Publish a 1.7 alpha release (JimmyCYJ: https://github.com/istio/release-builder/pull/329, https://github.com/istio/release-builder/pull/330)

**Comment by jacob-delgado** [comment]
See https://github.com/istio/istio/issues/22078 for the 1.6 release branch

**Comment by SecurityInsanity** [comment]
FWIW for future release managers creating the branches can be done with:

```bash
REPOS=(istio pkg api proxy client-go tools common-files gogo-genproto release-builder)
ORGS=(istio)
for organization in "${ORGS[@]}"; do
  for repository in "${REPOS[@]}"; do
    export org=${organization}
    export repo=${repository}
    echo "Release for: [${org}/${repo}] ?"
    read -p "Do you wish to continue?" yn
    case $yn in
      [Yy]* ) true;;
      [Nn]* ) break;;
    esac
    git clone git@github.com:${org}/${repo}.git
    cd ${repo}
    git checkout -b release-1.7
    git push --set-upstream origin release-1.7
    read -p "Do you wish to continue?" yn
    cd ..
    case $yn in
      [Yy]* ) continue;;
      [Nn]* ) break;;
    esac
  done
done
```

This will go one by one, and let you stop both before and after cloning each so you can validate the branches are being created correctly.

**Comment by jwendell** [comment]
There's an automation process being written for 1.8. It was planned for 1.7 but it didn't make it in time for today.

**Comment by ericvn** [comment]
And as @jwendell noted, any comments about short-comings in the list above would be good (and update the list with comments). We will be looking at the list to do the automation.

**Comment by ericvn** [comment]
Can we close this issue?

**Comment by jwendell** [comment]
@ericvn  We had kept this open because there's one issue that's still pending: https://github.com/istio/api/pull/1551
