### ISSUE TITLE
More logs/metrics on endpoint workflow for production readiness

### ISSUE THREAD

**Issue by jack2684** [istio/istio#24479]
**Describe the feature request**
Excited to see the newly-released WorkloadEntry and plan to adopt for our VMs. On the other hand having more logs/metrics would help us on adoption and future production operation. 

Here are a breakdown on what we think can be added. (correct me if I'm wrong)

**Metrics coverage in WorkloadEntry workflow**:
```
|———0. out of scope for now———||———————1. missing———————||————2. covered————|
workload-agent -> WLEntry in Kube -> ServiceController (Pilot) -> istio-proxy
                          |———————————(current scope of istio)——————————————|
```
**Metrics coverage in conventional kube pod workflow**:
```
|———3. covered———||—————4. missing—————||———————5. covered——————|
kubelet-> pod in Kube -> ServiceController (Pilot) -> istio-proxy
               |————————————(current scope of istio)————————————|
```
1. This is what we think is missing
2. Example: pilot [xdsPushTime](https://github.com/istio/istio/blob/65bd2ac632cbd6ec8e3fd85bb9874f685aea0cfd/pilot/pkg/proxy/envoy/v2/monitoring.go#L120-L123)
3. Example: Kubelet [PodWorkerDuration](https://github.com/kubernetes/kubernetes/blob/323f34858de18b862d43c40b2cced65ad8e24052/pkg/kubelet/metrics/metrics.go#L102-L113)
4. Seems to be missing too.
5. (Same as point No.2)

**Describe alternatives you've considered**
N/A

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[x] Performance and Scalability
[x] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
Just to make sure we are all on the same page, what metrics exactly would you like to see?

**Comment by jack2684** [comment]
Thanks for swift response @howardjohn . 

One example is, the duration between "when the WorkloadEntry is created in kube resource" and "when the receive the event and handle it". In case a new workload is reported, but not pushed to istio-proxy promptly, this metrics can help us narrow down the cause.

**Comment by howardjohn** [comment]
I don't know how we can do that. "when the receive the event and handle it" is the very first time Istio is aware of the config at all. I guess we can look at the CreationTimestamp but I am not sure if thats a safe usage of that field?

**Comment by jack2684** [comment]
Yes! We are also considering to use `CreationTimestamp` , [which is a metadata field auto generated for all kube object](https://kubernetes.io/docs/reference/using-api/api-concepts/#generated-values).
