### ISSUE TITLE
IstioOperator values for prometheus ignored

### ISSUE THREAD

**Issue by ericjohansson89** [istio/istio#24470]
**Bug description**
Setting values
```
values:
  prometheus:
    enabled: false
```
Disables prometheus server in 1.5.4 but in 1.6.0 switching between enabled: false/true makes no difference in 1.6.0

[ x ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Prometheus server should be deployed for enabled: true and not deployed for enabled: false
but this is not the case
**Steps to reproduce the bug**
Install istio version 1.5.4 and toggle between enabled: true/false
```
values:
  prometheus:
    enabled: true / false
```

Upgrade to 1.6.0 do the same and it has no effect.
**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
client version: 1.6.0
control plane version: 1.6.0

**How was Istio installed?**
Standalone operator
**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by esnible** [comment]
Use `addonComponents.prometheus.enabled=false` from _istioctl_ or 

```
addonComponents:
  prometheus:
    enabled: false
```

in the operator.

@therealmitchconnors @ostromart I feel we might want to add an "analyzer" so `istioctl analyze` detects this and the IOP's .Status field is set. This will require making IstioOperator be the same kind of collection as the other .protos.

**Comment by ericjohansson89** [comment]
Seems to work, but the `addonComponents.prometheus.enabled=true/false` does not seem to work on 1.5.x

**Comment by therealmitchconnors** [comment]
Analyzing addons or install commands sounds like a great idea to me, and it fits well with what the ToC has requested for warning about breaking changes on upgrade.  Architecturally, there may be a good deal of work to do in order to get this working, but conceptually I think it's a good plan.

**Comment by laurentiuspurba** [comment]
> Seems to work, but the `addonComponents.prometheus.enabled=true/false` does not seem to work on 1.5.x
Hi @ericjohansson89,

I am having similar issue on `addonComponents.istiocoredns.enabled: false`, for some reason setting it to `false` does not remove `istiocredns`.

Do you mind sharing your `istioctl` command(s)? Appreciate your help on this.
