### ISSUE TITLE
Need to add tool to detect and warn about Mixer usage

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio#24471]
We need to provide proactive notifications to users that rely on Mixer that Mixer will be removed entirely from Istio in the 1.8 release. This notification should primarily focus on Mixer usage for policy scenarios. It should point to proper documentation on how to transition for allow/deny lists, rate limits, header manipulation, and custom-shim tooling.

This could be in the form of `istioctl analyze` and/or in `manifest apply/generate` (when Mixer-based policy is enabled).

We've previously discussed this for upgrades only. But we need to cover all cases and ensure there is proper warning.

[ X ] Configuration Infrastructure
[ X ] Docs
[ X ] Installation
[ X ] Policies and Telemetry
[ X ] User Experience

**Comment by douglas-reid** [comment]
This was specifically requested by the TOC in our discussion of the Mixer Removal Plan.

**Comment by esnible** [comment]
`istioctl analyze` is intended to warn about deprecated fields and CRDs.  Unfortunately for 1.6 we did not keep up with the changes.  https://github.com/istio/istio/issues/19355 is the 1.7 work item to bring the analysis up to date.

The current deprecation analyzer is manually created.  It is unclear if we will have a way to flow the `$hide_from_docs` and `Deprecated` comments in the .proto down to the analyzer in 1.7.  Please reference either this work item or https://github.com/istio/istio/issues/19355 on any Issues or PRs on istio/api that deprecate mixer types and fields.

**Comment by richardwxn** [comment]
So I assume for manifest apply/generate this would be check would be applied to in cluster configs?

**Comment by douglas-reid** [comment]
For `upgrade`, we should validate existing configs. For `generate` or `apply`, I imagine we'd check to see if any Mixer-specific values were being set. `analyze` should share the undrlying same logic, it seems.

**Comment by richardwxn** [comment]
Then for generate/apply, I think we can just issue warnings if they try to enable any mixer related settings from the IstioOperator configs? like mixer telemetry component, policy component enablement.

And for upgrade we check specific mixer related resources in the cluster

**Comment by esnible** [comment]
I'd like `istioctl analyze` to detect as many deprecated things as possible.

It only handles resources that Galley used to know about that have an entry in _pkg/config/schema/collections/collections.gen.go_.

- The PRs deprecated some fields in _IstioMeshV1Alpha1MeshConfig_.  I could warn about these, but does anyone still have a MeshConfig in their cluster?  I do not.
- Two collections mention the mixer, `IstioMixerV1ConfigClientQuotaspecbindings` and `IstioMixerV1ConfigClientQuotaspecs`.  Are these mixer configs that are going away or do they just have old names?
- There are many telemetry examples in _samples/bookinfo/telemetry_.  Stuff in config.istio.io/v1alpha2. 
 These are staying?
- There are many policy examples in _samples/bookinfo/policy_.  I see these are deprecated.  I will start on a PR for them.

**Comment by douglas-reid** [comment]
@esnible those mixer configs are going away. the stuff in the `samples/` is going away, per the Mixer removal plan. Please do not start a PR. We need to hit certain objectives before proceeding with that PR (which has already been drafted).

**Comment by esnible** [comment]
@douglas-reid The `analyze` PR should do the work.  Please review https://github.com/istio/istio/pull/25694 .  If you like it I will get someone in UX to review it.

**Comment by douglas-reid** [comment]
@esnible it seems like everything is in place. I think we are OK to close?
