### ISSUE TITLE
Istio Service Mesh Extended for Event Driven Messaging

### ISSUE THREAD

**Issue by nathanawmk** [istio/istio#24489]
To reduce the moving parts and complexity in my microservices setup, instead of using Kafka, am thinking if Istio Service Mesh can be extended for Event Driven Messaging?

Nathan Aw (Singapore)

SOURCE: https://stackoverflow.com/questions/62163619/can-i-use-my-service-mesh-for-event-driven-messaging/62168409#62168409

**Comment by howardjohn** [comment]
Hey @nathanawmk , can you expand more on what this would look like? It sounds like you want Istio to replace Kafka which doesn't seem in the scope of the project but I may he misunderstanding

**Comment by howardjohn** [comment]
Its not clear what the request is, and seems out of scope. Based on this, I will close
