### ISSUE TITLE
istioctl with net/http: TLS handshake timeout Error

### ISSUE THREAD

**Issue by idefav** [istio/istio#24483]
**Bug description**

When I use istioctl to execute the command, it will report ssl error, the certificate is a self-signed certificate
![image](https://user-images.githubusercontent.com/6405415/83937689-9cf5a780-a801-11ea-8b9f-4acbf4c4f523.png)

![image](https://user-images.githubusercontent.com/6405415/83937717-cadaec00-a801-11ea-8a19-c063c00bf385.png)

Is there any way to ignore this certificate error?

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
Interesting, this is  just using the kubernetes client-go so I am surprised kubectl works but istioctl doesn't? Is it possible you can run `kubectl get pods -v9` and compare?

**Comment by idefav** [comment]
Kubectl can connect but istioctl does not work, report certificate error
