### ISSUE TITLE
Installation differences between helm and istioctl

### ISSUE THREAD

**Issue by jshum2479** [istio/istio#24484]
Hi, I am new to istio and I have a question regarding installation.  At 1.5.4 or before,  there are options of using helm or istioctl.   When I use helm, I see a lot more isto pods/services in the namespace e.g. gallery, citadel, sidecar-injector, mixer, pilot, policy, crd .. , but if I use istioctl to install 
'istioctl install', I don't see the those pods and services - instead less pods.

Am I missing some features or do I have to use more steps to install citadel, gallery, pilot and policy?

**Comment by howardjohn** [comment]
This is expected, see https://istio.io/blog/2020/istiod/. see also the upgrade notes which explains how to migrate

**Comment by jshum2479** [comment]
Thanks Howard
