### ISSUE TITLE
How to modify request body like spring cloud zuul filter?

### ISSUE THREAD

**Issue by cokuehuang** [istio/istio#24485]
In spring cloud zuul's filter, we can get and modify request's body(request parameters) ,and pass new request's body to the next filter or service. Now we begin to user Istio gateway to replace zuul , can EnvoyFilter modify request's body ?

**Comment by rverma-jm** [comment]
Much needed feature, @cokuehuang did you found any solution?

**Comment by howardjohn** [comment]
Introspection/modification of request body can be done via WASM or lua. See https://istio.io/latest/docs/concepts/wasm/ for more info
