### ISSUE TITLE
Does Istio support a distributed multi-cloud service mesh setup cutting across the different clouds (AWS, Azure and GCP)? i.e., not just Istio on GCP, not just Istio on Azure, not just Istio on AWS but Istio across the 3 clouds - a single pane view

### ISSUE THREAD

**Issue by nathanawmk** [istio/istio#24488]
Does Istio support a distributed multi-cloud service mesh setup cutting across the different clouds (AWS, Azure and GCP)? i.e., not just Istio on GCP, not just Istio on Azure, not just Istio on AWS but Istio across the 3 clouds - a single pane view

Nathan Aw (Singapore)

SOURCE: https://stackoverflow.com/questions/62207367/is-there-a-distributed-multi-cloud-service-mesh-solution-thats-available-somet/62218292#62218292

**Comment by howardjohn** [comment]
Yes, there is nothing restricting you from doing this. There have been a few demos previous of multicloud deployments you may be able to find on YouTube - I think @sdake  did one
