### ISSUE TITLE
istioctl AWS NLB for ingress gateway

### ISSUE THREAD

**Issue by quixoticmonk** [istio/istio#24496]
**Describe the feature request**
Requesting an update on the AWS nlb configuration for istio ingress with istioctl.
**Path** : https://istio.io/blog/2018/aws-nlb/
**Describe alternatives you've considered**
I haven't looked at altnertatives. Would the below work ?
- Can we patch the istio installation with nlb annotation for ingress gateway ?
- I am running this on a CI server and I was advised to use "istoctl manifest apply " than generate the yaml to ensure that the order expected is preserved.
https://github.com/istio/istio/issues/24232#issuecomment-636425365

[ ] Configuration Infrastructure
[X ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**
- Installation of istio into an EKS cluster with istioctl binary.
- istio version : 1.5.4

**Comment by howardjohn** [comment]
https://preliminary.istio.io/latest/docs/setup/install/istioctl/#configure-gateways has an example for a GB ILB. You can do the same for NLB, just replace the annotation

**Comment by yiyan-wish** [comment]
Does aws nlb for istio production ready ?
