### ISSUE TITLE
istioctl delete -f option

### ISSUE THREAD

**Issue by sb1975** [istio/istio#24497]
**Describe the feature request**
There should be a simple option to specify istioctl delete -f.
The commands are too complex and also if a user dont remember the previous commands used, can he not delete it cleanly ?

There should be a simple command as below :

istioctl delete -f <manifest-file-name>

**Describe alternatives you've considered**

[ ] Configuration Infrastructure
[x ] Docs
[x ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by morvencao** [comment]
See discussion for this in https://github.com/istio/istio/issues/18900

**Comment by esnible** [comment]
Closing as a duplicate of #18900
