### ISSUE TITLE
Istio v1.6.1 TCP telemetry unknown & passthroughcluster

### ISSUE THREAD

**Issue by Mengkzhaoyun** [istio/istio#24501]
**Bug description**

when i running into the bookinfo samples , the tcp telemetry can not find the source_workload or dest_workload , both side.

![image](https://user-images.githubusercontent.com/6711398/83989592-778ba980-a979-11ea-8d33-a543fa9a0062.png)

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

The TCP edges to PassthroughCluster, and from unknown, should not show up.

**Steps to reproduce the bug**

Deploy Kubernetes v1.18.2
Deploy Cilium v1.7.4
Deploy Istio v1.6.1
Deploy bookinfo v1

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```bash
[root@centos-1 ~]# istioctl version --remote
client version: 1.6.1
control plane version: 1.6.1
data plane version: 1.6.1 (10 proxies)
[root@centos-1 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.2", GitCommit:"9239143dc108931720b3db1b4a7c2ee33b1b5d0e", GitTreeState:"clean", BuildDate:"2020-04-28T07:22:02Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.2", GitCommit:"9239143dc108931720b3db1b4a7c2ee33b1b5d0e", GitTreeState:"clean", BuildDate:"2020-04-28T07:19:27Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
[root@centos-1 ~]# helm version
version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

**How was Istio installed?**
istioctl manifest generate 
kubectl apply

**Environment where bug was observed (cloud vendor, OS, etc)**
CentOS Linux release 7.7.1908 (Core) - 5.6.14-1.el7.elrepo.x86_64

**Comment by bianpengyuan** [comment]
Dup of https://github.com/istio/istio/issues/24379. Close in favor of that issue since it has more context.
