### ISSUE TITLE
logAsJson global value missing in the documentation

### ISSUE THREAD

**Issue by MarianZoll** [istio/istio#24504]
**Bug description**

For ops setup, we required to send logs to an external ops stack (in our case Azure Monitor, Log Analytics, App Insights). JSON messages should be used. 

We followed the configurations and tried to configure it using `meshConfig`, k8s patches and `overlays`. After some time, we checked the Helm templates and figured out, that everything we have to do is to add `global.logAsJson: true` to the operator configuration. 

[ ] Configuration Infrastructure
[ X ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

We guess it would be great to have it documented somewhere in the documentation as this is a flag that probably everyone needs to flip when running Istio in production. 

https://istio.io/docs/reference/config/istio.mesh.v1alpha1/ might be a good place to put it.

**Steps to reproduce the bug**

- Install istio

**Version (include the output of `istioctl version --remote` and `kubectl version`**

```
$ istioctl version --remote                                                                                                                                                                       
client version: 1.5.0
control plane version: 1.5.0
data plane version: 1.5.0 (13 proxies)
```

**How was Istio installed?**

`istioctl`

**Environment where bug was observed (cloud vendor, OS, etc)**

- AKS

**Comment by MarianZoll** [comment]
The `meshConfig` works vor v1.6.1. Going to close the issue. `global.logAsJson: true` is the solution for v1.5.0

**Comment by Ghazgkull** [comment]
@MarianZoll We just upgraded from Istio 1.8 to 1.9 and in reviewing my IstioOperator config, I see we still have `values.global.logAsJson: true`. I just looked at the `meshConfig` spec and I don't see anything about configuring the mesh to log as JSON. There's an option to set the `accessLogEncoding`, but I assume that's only for access logging. Do you know how to configure Istio to write all logs in JSON format in the current release? And is this documented somewhere?

**Comment by Ghazgkull** [comment]
For what it's worth, here's the relevant snippet from my IstioOperator manifest. I'd love to get rid of any old `values` settings like `logAsJson`:
```  meshConfig:
    defaultConfig:
      tracing:
        sampling: 100.0
    enablePrometheusMerge: false
    accessLogFile: /dev/stdout
    accessLogEncoding: JSON
    accessLogFormat: |
      {
        "accessLogFormat": "{\"traceId\": \"%REQ(x-b3-traceid)%\",\"protocol\": \"%PROTOCOL%\",\"upstream_service_time\": \"%REQ(x-envoy-upstream-service-time)%\",\"upstream_local_address\": \"%UPSTREAM_LOCAL_ADDRESS%\",\"duration\": \"%DURATION%\",\"upstream_transport_failure_reason\": \"%UPSTREAM_TRANSPORT_FAILURE_REASON%\",\"route_name\": \"%ROUTE_NAME%\",\"downstream_local_address\": \"%DOWNSTREAM_LOCAL_ADDRESS%\",\"user_agent\": \"%REQ(USER-AGENT)%\",\"response_code\": \"%RESPONSE_CODE%\",\"response_flags\": \"%RESPONSE_FLAGS%\",\"start_time\": \"%START_TIME%\",\"method\": \"%REQ(:METHOD)%\",\"request_id\": \"%REQ(X-REQUEST-ID)%\",\"upstream_host\": \"%UPSTREAM_HOST%\",\"x_forwarded_for\": \"%REQ(X-FORWARDED-FOR)%\",\"requested_server_name\": \"%REQUESTED_SERVER_NAME%\",\"bytes_received\": \"%BYTES_RECEIVED%\",\"istio_policy_status\": \"-\",\"bytes_sent\": \"%BYTES_SENT%\",\"upstream_cluster\": \"%UPSTREAM_CLUSTER%\",\"downstream_remote_address\": \"%DOWNSTREAM_REMOTE_ADDRESS%\",\"authority\": \"%REQ(:AUTHORITY)%\",\"path\": \"%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%\"}"
      }
  values:
    global:
      logAsJson: true
      defaultPodDisruptionBudget:
        enabled: false
      proxy:
        includeIPRanges: '10.100.0.0/16'
        resources:
          requests:
            cpu: 50m
```

**Comment by MarianZoll** [comment]
Hm which of the components are still logging in `TEXT` format? Then we can also check on the source level.

https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/ is a good starting point, but most of the settings seem to be in your snippet.

**Comment by Ghazgkull** [comment]
Thanks for the quick reply. The only property documented for mesh config log format is `accessLogEncoding`, which only affects access logs. All other logging is in plain text unless `values.global.logAsJson` is set. If there's another property which can tell Istio to do all logging in JSON - something outside the `values` section - I would love to use it.

I think there are two issues/questions:
1. Is there any way to configure Istio containers to log in JSON format other than `values.global.logAsJson` using the IstioOperator?
2. If the answer to #1 is yes, is it documented anywhere? Is the `values.global.logAsJson` property documented? I don't recall how I originally found the `values.global.logAsJson` property, but I can't find it anywhere in the docs now.

**Comment by Ghazgkull** [comment]
Here's an example of the logs from istio-ingressgateway with only `accessLogEncoding` configured:

```
  meshConfig:
    accessLogFile: /dev/stdout
    accessLogEncoding: JSON
```


```
...
2021-02-12T22:21:09.399804Z	info	cache	generated new workload certificate	latency=222.533297ms ttl=23h59m59.600204751s
2021-02-12T22:21:09.399849Z	info	cache	returned delayed workload certificate from cache	ttl=23h59m59.600153762s
2021-02-12T22:21:09.400151Z	info	sds	SDS: PUSH	resource=default
2021-02-12T22:21:09.490920Z	info	sds	SDS: PUSH	resource=ROOTCA
2021-02-12T22:21:09.491160Z	info	sds	SDS: PUSH	resource=ROOTCA
2021-02-12T22:21:11.626619Z	info	Initialization took 2.480687684s
2021-02-12T22:21:11.626637Z	info	Envoy proxy is ready
{"accessLogFormat":"{\"traceId\": \"-\",\"protocol\": \"HTTP/1.1\",\"upstream_service_time\": \"-\",\"upstream_local_address\": \"-\",\"duration\": \"0\",\"upstream_transport_failure_reason\": \"-\",\"route_name\": \"-\",\"downstream_local_address\": \"172.30.217.172:8080\",\"user_agent\": \"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0\",\"response_code\": \"301\",\"response_flags\": \"-\",\"start_time\": \"2021-02-12T22:33:38.354Z\",\"method\": \"POST\",\"request_id\": \"b8ac5a12-5c7a-923e-be42-1bf3c6b60c75\",\"upstream_host\": \"-\",\"x_forwarded_for\": \"172.30.212.69\",\"requested_server_name\": \"-\",\"bytes_received\": \"0\",\"istio_policy_status\": \"-\",\"bytes_sent\": \"0\",\"upstream_cluster\": \"-\",\"downstream_remote_address\": \"172.30.212.69:26135\",\"authority\": \"44.228.152.83:80\",\"path\": \"/boaform/admin/formLogin\"}"}```

And here's what you get with both `accessLogEncoding` and `values.global.logAsJson`

```
  meshConfig:
    accessLogFile: /dev/stdout
    accessLogEncoding: JSON
  values:
    global:
      logAsJson: true
```

```
...
{"level":"info","time":"2021-02-12T22:46:33.813273Z","scope":"cache","msg":"generated new workload certificate","latency":192090018,"ttl":86399186730459}
{"level":"info","time":"2021-02-12T22:46:33.813415Z","scope":"cache","msg":"returned delayed workload certificate from cache","ttl":86399186597197}
{"level":"info","time":"2021-02-12T22:46:33.813731Z","scope":"sds","msg":"SDS: PUSH","resource":"default"}
{"level":"info","time":"2021-02-12T22:46:33.925013Z","scope":"sds","msg":"SDS: PUSH","resource":"ROOTCA"}
{"level":"info","time":"2021-02-12T22:46:33.925284Z","scope":"sds","msg":"SDS: PUSH","resource":"ROOTCA"}
{"level":"info","time":"2021-02-12T22:46:35.710634Z","msg":"Initialization took 2.120093856s"}
{"level":"info","time":"2021-02-12T22:46:35.710653Z","msg":"Envoy proxy is ready"}
```

**Comment by MarianZoll** [comment]
@Ghazgkull Sorry for replying that late. I think this property is not available in the docs, but only in the Helm values of previous versions or the Operator source code: 

https://github.com/istio/operator/blob/f408beefc360a5eb4b592a0d8147f8989041ea25/data/profiles/default.yaml#L200

The configuration triggers a start up argument to be set which you might se in one of the generated manifests of the Operator which are applied to K8s. 

https://github.com/istio/operator/blob/f408beefc360a5eb4b592a0d8147f8989041ea25/cmd/mesh/testdata/manifest-generate/output/pilot_k8s_settings.yaml#L953-L955

I think it would be wise to standardise the logging options as I do see this to be very valuable for day-2 ops. But I would also assume that this is a lot of effort as it touches different components, the way they log and the way SW is deployed. But might be worth to add it at least to some backlog.

In case you do agree, we can bring this up with the OSS team again.

**Comment by Ghazgkull** [comment]
The title of this issue is "logAsJson global value missing in the documentation" and that issue still exists... so I would suggest that this ticket be reopened. Improving the way logging is configured sounds great, but in the meantime I think the current method should at least be documented.

**Comment by MarianZoll** [comment]
@howardjohn As we a couple of other people reached out regarding the setting and the documentation to questions towards the core team: 

1. Do you see any chance to work on more standardised logging of all components including generalising the configuration,
2. Shall we add the `values.global.logAsJson` somewhere in the docs? I know this links back to some Helm configuration which is not longer updated in the docs. So maybe we want to move it to `meshConfig` and make it configurable. 

In case you don't see any value or the team is already working on something else feel free to close the ticket again.
