### ISSUE TITLE
Traces are not load balances across available zipkin endpoints

### ISSUE THREAD

**Issue by Stono** [istio/istio#24513]
**Bug description**
I've noticed imbalanced load on my zipking receivers, and it looks like that's because the `istio-proxy` is not sending data across the available endpoints.

You can see I have lots of pods:
```
❯ kis get pods -l app=jaeger -o wide
NAME                            READY   STATUS    RESTARTS   AGE   IP              NODE                                                  NOMINATED NODE   READINESS GATES
istio-tracing-98c5fdc49-4sw96   1/1     Running   0          20m   10.194.11.229   gke-delivery-platform-normal-20191114-f41693d5-v2i3   <none>           <none>
istio-tracing-98c5fdc49-74mv4   1/1     Running   0          20m   10.194.69.128   gke-delivery-platform-normal-20191114-f41693d5-7fil   <none>           <none>
istio-tracing-98c5fdc49-8ch25   1/1     Running   0          19m   10.194.59.64    gke-delivery-platform-normal-20191114-ee1d5f81-qdpy   <none>           <none>
istio-tracing-98c5fdc49-94x2m   1/1     Running   0          19m   10.194.68.164   gke-delivery-platform-normal-20191114-ee1d5f81-6oaj   <none>           <none>
istio-tracing-98c5fdc49-9gcd2   1/1     Running   0          19m   10.194.63.182   gke-delivery-platform-normal-20191114-a94d4b99-4aar   <none>           <none>
istio-tracing-98c5fdc49-f4vcr   1/1     Running   0          20m   10.194.23.107   gke-delivery-platform-normal-20191114-ee1d5f81-zmp7   <none>           <none>
istio-tracing-98c5fdc49-k2kjl   1/1     Running   0          20m   10.194.17.97    gke-delivery-platform-normal-20191114-a94d4b99-x8rm   <none>           <none>
istio-tracing-98c5fdc49-qh85d   1/1     Running   0          19m   10.194.43.135   gke-delivery-platform-normal-20191114-f41693d5-ch9j   <none>           <none>
istio-tracing-98c5fdc49-sgj88   1/1     Running   0          20m   10.194.24.140   gke-delivery-platform-normal-20191114-a94d4b99-0xts   <none>           <none>
istio-tracing-98c5fdc49-spw5h   1/1     Running   0          20m   10.194.32.160   gke-delivery-platform-normal-20191114-ee1d5f81-3m2m   <none>           <none>
```

Here's a quick dump of the destination ips from `tcpdump port 9411 and src 10.194.1.136 | awk '{print $5}' > 1`

```
root@gke-delivery-platform-normal-20191114-a94d4b99-lzul:~# cat 1 | sort | uniq -c
      1 1
      2 10.194.24.140.9411:
   1020 10.194.32.160.9411:
      1 10.194.59.64.9411:
      1 10.194.69.128.9411:
```

You can see the traffic is overwhelmingly going to a single pod.

Now across all services on the mesh, you may well get an even distribution of connection (proxy -> jaeger pod), however if some of those services are significantly more chatting, you can land yourself with the chatty connections on a single pod.

I had a nosey in the bootstrap cluster and it seems like the zipkin cluster is defined as round robin:

```
      {
        "name": "zipkin",
        "type": "STRICT_DNS",
        "dns_refresh_rate": "300s",
        "dns_lookup_family": "V4_ONLY",
        "connect_timeout": "1s",
        "lb_policy": "ROUND_ROBIN",
        "hosts": [
          {
            "socket_address": {"address": "zipkin.istio-system", "port_value": 9411}
          }
        ]
      }
```

So not sure what else is going on

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[x] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Traffic to be distributed evenly across the end points

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.5.4

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

**Comment by howardjohn** [comment]
Its round robin over the IPs returned by dns lookup for `zipkin.istio-system` which is a single IP (the Service IP). So it would follow k8s randomize iptables "load balancing" not Envoy LB

**Comment by Stono** [comment]
Ah,
That makes sense.  It does a bad job.

Is there any reason we couldn’t leverage envoys load balancing instead?

**Comment by howardjohn** [comment]
I think Envoy requires the tracing to be a part of bootstrap, which is changing soon (or maybe already did). However I think we *can* do EDS as part of a cluster in bootstrap.. so I think no, there is no real blocker?

**Comment by Stono** [comment]
If that’s a quick thing, it’d really help me.  We have some pods doing 500ops and others doing 5, so need request based balancing to be more efficient than it currently is!

**Comment by howardjohn** [comment]
Is the connection long lived? That would explain why k8s does a bad job balancing. If so maybe a low tech short term solution may be to set some max num of requests per connection or something?

You may also be able to make the change as bootstrap-only change... I'll try it out

**Comment by howardjohn** [comment]
You can try this out:

```diff
diff --git a/tools/packaging/common/envoy_bootstrap_v2.json b/tools/packaging/common/envoy_bootstrap_v2.json
index 6df1757faa..94f66375d9 100644
--- a/tools/packaging/common/envoy_bootstrap_v2.json
+++ b/tools/packaging/common/envoy_bootstrap_v2.json
@@ -295,9 +295,14 @@
         {{ if .tracing_tls }}
         "transport_socket": {{ .tracing_tls }},
         {{ end }}
-        "type": "STRICT_DNS",
-        "respect_dns_ttl": true,
-        "dns_lookup_family": "{{ .dns_lookup_family }}",
+        "type": "EDS",
+        "eds_cluster_config": {
+          "eds_config": {
+            "ads": {},
+            "resource_api_version": "V3"
+          },
+          "service_name": "outbound|9411||zipkin.istio-system.svc.cluster.local"
+        },
         "connect_timeout": "1s",
         "lb_policy": "ROUND_ROBIN",
         "load_assignment": {
```

caveat: I tested this for approx 1 minute.

Remove the `+            "resource_api_version": "V3"` line if you are on anything other than `master`.

**Comment by Stono** [comment]
I've been thinking about this more and I can't decide what's better...

Kubernetes connection based load balancing and potentially slightly imbalanced load, or Envoy load balancing but that'll mean every pod makes a connection to every jaeger instance (might bring its own load problems) 🤷

**Comment by Stono** [comment]
I'm going to close this, we're just going to leave it to kubernetes.
