### ISSUE TITLE
PassthroughCluster using HTTP/1.1 instead of HTTP/2

### ISSUE THREAD

**Issue by sha-rath** [istio/istio#24525]
**Bug description**

I have a service deployment (protocol specified as http2) with 2 replicas. Both the pods have a sidecar container running. Assume one of the pods to be the master and other, the slave. When I trigger a HTTP/2 service request from the slave to the master using the master pod IP, PassthroughCluster is used and on the inbound I see the protocol being changed from HTTP/2 to HTTP/1.1. 

Here is the log from the sidecar on the slave pod:
`[2020-06-08T20:39:42.106Z] "GET / HTTP/2" 200 - "-" "-" 0 612 3 2 "-" "curl/7.52.1" "4510cd78-8428-99b6-9906-0364e6b34e0c" "172.17.0.16:8200" "172.17.0.16:8200" PassthroughCluster 172.17.0.15:34076 172.17.0.16:8200 172.17.0.15:34074 - allow_any`

And this is the log from the sidecar on the master pod:
`[2020-06-08T20:39:42.106Z] "GET / HTTP/1.1" 200 - "-" "-" 0 612 1 0 "-" "curl/7.52.1" "4510cd78-8428-99b6-9906-0364e6b34e0c" "172.17.0.16:8200" "127.0.0.1:8200" inbound|8200|http2|my-nginx.default.svc.cluster.local 127.0.0.1:53072 172.17.0.16:8200 172.17.0.15:34076 - default`

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
PassthroughCluster to use HTTP/2. It should not downgrade the request to HTTP/1.1 and therefore, I expect the sidecar on the master pod to forward HTTP/2 request to the service container.

**Steps to reproduce the bug**
1. Deploy a service with 2 replicas (with sidecar)
2. Exec into the service container of one of the pods
3. Trigger a HTTP/2 request to the service, something like `curl -v --http2-prior-knowledge http://172.17.0.16:8200`, where 172.17.0.16 is the master pod IP
4. Check the logs on both the sidecars. You will see logs similar to what I have mentioned in the description

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

istioctl version --remote
client version: 1.4.6
control plane version: 1.6.0
data plane version: 1.6.0 (5 proxies)

kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

helm version
Client: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}

**How was Istio installed?**
istioctl install --set profile=demo

**Environment where bug was observed (cloud vendor, OS, etc)**
Minikube

**Comment by howardjohn** [comment]
@sha-rath we are tracking this in https://github.com/istio/istio/issues/24706, I am actively looking into this and I think I know a fix. I was able to reproduce the issue, thanks for the help. We will continue updates in that issue. Thanks!
