### ISSUE TITLE
Error when tearing down istio test framework

### ISSUE THREAD

**Issue by niwatorrri** [istio/istio#24524]
**Bug description**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[x] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

I was writing a test framework for istio.io. Normally there'd be no errors when setting up and tearing down the istio test framework. However, an error appeared after istio 1.6.1 was released so I suspect there might be a connection.

**Steps to reproduce the bug**

1. Set environment variables. More details in this [makefile](https://github.com/istio/istio.io/blob/master/Makefile.core.mk).
```bash
export HUB=gcr.io/istio-testing
export TAG=1.7-alpha.b5d6aeed94550848279425513a1d0b9e229c5720
```
2. Create a file `bug_test.go` with the following content:
```go
package bug

import (
	"testing"

	"istio.io/istio/pkg/test/framework"
	"istio.io/istio/pkg/test/framework/components/istio"
	"istio.io/istio/pkg/test/framework/resource/environment"
)

var inst istio.Instance

func TestMain(m *testing.M) {
	framework.
		NewSuite("bug_test", m).
		SetupOnEnv(environment.Kube, istio.Setup(&inst, nil)).
		Run()
}
```
3. Create some kind of k8s cluster (I launched a GKE and connected to the master) and run `go test bug_test.go -v --istio.test.env=kube`, which gives
```bash
2020-06-08T22:01:36.802855Z     info    tf      Test run dir: /tmp/bug-test-892101d8c7f4421980edf6

- Processing resources for Istio core.
✔ Istio core installed
- Processing resources for Istiod.
- Processing resources for Istiod. Waiting for Deployment/istio-system/istiod
✔ Istiod installed
- Processing resources for Ingress gateways.
- Processing resources for Ingress gateways. Waiting for Deployment/istio-system/istio-ingressgateway
✔ Ingress gateways installed
- Pruning removed resources
✔ Installation completetesting: warning: no tests to run
PASS
2020-06-08T22:03:06.072053Z     error   tf      Error during close: 1 error occurred:
        * configmaps "istio-status-leader" not found


ok      command-line-arguments  91.806s
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

Output from `istioctl version --remote`:
```
client version: 1.6.0
control plane version: 1.7-alpha.b5d6aeed94550848279425513a1d0b9e229c5720
data plane version: 1.7-alpha.b5d6aeed94550848279425513a1d0b9e229c5720 (1 proxies)
```
Output from `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.9-gke.2", GitCommit:"4751ff766b3f6dbf6c6a63394a909e8108e89744", GitTreeState:"clean", BuildDate:"2020-05-08T16:44:50Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

It is installed by istio test framework itself.

**Environment where bug was observed (cloud vendor, OS, etc)**

The GKE cluster I tested against was created using
```
gcloud container clusters create $CLUSTER_NAME \
  --cluster-version latest \
  --machine-type=$M_TYPE \
  --num-nodes 4 \
  --zone $ZONE \
  --project $PROJECT_ID
```

**Comment by howardjohn** [comment]
We should either ignore the error or not clean it up. Basically it's only created in some cases but we always try to clean it up and then log an error when it's not there
