### ISSUE TITLE
Test and fix IPv6 and IPv6 dual-stack support

### ISSUE THREAD

**Issue by nrjpoddar** [istio/istio#24538]
We need to test/fix IPv6 and dual stack support in Istio. Update docs in collaboration with docs WG.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by nrjpoddar** [comment]
cc @knrc

**Comment by howardjohn** [comment]
https://github.com/istio/istio/issues/23473 tracks the CI part

**Comment by howardjohn** [comment]
https://github.com/istio/istio/issues/24099
https://github.com/istio/istio/issues/24538

**Comment by sha-rath** [comment]
Not stale..there are a couple of issues to be addressed wrt IPv6 and dual-stack. Can we pls keep this issue open and continue to work on it?

**Comment by devenderkamble2101** [comment]
Kubernetes internal network is dual stack, Does Istio proxies tolerate dual stack configuration even if Istio does not support dual stack.
