### ISSUE TITLE
Unify CNI implementations for startup race

### ISSUE THREAD

**Issue by nrjpoddar** [istio/istio#24539]
Unify CNI implementations for startup race across different forks/distributions of Istio

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by nrjpoddar** [comment]
This is a P1 item for 1.7, @knrc you had suggested that Marko Luksa from Redhat would be interested in this but I don't have this Github handle so assigning it to you for visibility.

**Comment by jwendell** [comment]
@nrjpoddar his GH handle is @luksa . That said, he seemed to have volunteered for another task in the CNI Beta doc. Let's let him speak up :)

**Comment by knrc** [comment]
@nrjpoddar I'll talk with @luksa about this

**Comment by knrc** [comment]
@nrjpoddar It looks as if @luksa was able to join the call today, I'll follow up with him early next week in any case

**Comment by JimmyCYJ** [comment]
Setting this issue to P1 per https://github.com/istio/istio/issues/24539#issuecomment-640992142
