### ISSUE TITLE
Better transport security for HTTP

### ISSUE THREAD

**Issue by nrjpoddar** [istio/istio#24540]
**Describe the feature request**
Better transport security for HTTP as described by the [design doc](https://docs.google.com/document/d/1TARjqHylJPEkEo8XCTGygHk-4PygN4KnTZRJy_HyTFc/edit#)

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by lambdai** [comment]
The major 
DR could actually turns the http traffic to TLS traffic when [`ClientTLSSettings.TLSmode` ](https://istio.io/latest/docs/reference/config/networking/destination-rule/#ClientTLSSettings-TLSmode) is imported.

This traffic is not handled correctly without the envoy infrastructure which is supposed to carry tcp traffic.

Will switch to BTS for tcp and return to this topic.

**Comment by lambdai** [comment]
depends on bug https://github.com/envoyproxy/envoy/issues/12236
