### ISSUE TITLE
`make build_wasm` failed when set `BUILD_WITH_CONTAINER=1`

### ISSUE THREAD

**Issue by dozer47528** [istio/istio#24546]
**Bug description**

In the `Makefile.core.mk`, `build_wasm` will run the script `scripts/build_wasm.inc` which will build wasm in docker.

```
build_wasm() {
    root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
    workspace=${root}/WORKSPACE
    wasm_sdk_tag="$(grep -Pom1 "^ENVOY_SHA = \"\K[a-zA-Z0-9]{40}" "${workspace}")"
    wasm_sdk_image=${WASM_SDK_IMAGE:=gcr.io/istio-testing/wasmsdk}

    docker run -e uid="$(id -u)" -e gid="$(id -g)" -v $PWD:/work -w /work -v $(realpath $PWD/../../extensions):/work/extensions ${wasm_sdk_image}:${wasm_sdk_tag} bash /build_wasm.sh
    rmdir extensions
}
```

Project location in Host: `/project/proxy/extensions/metadata_exchange`

Project location in `gcr.io/istio-testing/build-tools`: `/work/extensions/metadata_exchange`

When I set `BUILD_WITH_CONTAINER=1` and run `make build_wasm`, the script try to get the project location by `$PWD` which is `/work/extensions/metadata_exchange`. But this is a docker in docker issue. Actually, the Host will run this docker command and the path `/work/extensions/metadata_exchange` for Host is wrong. The correct path should be `/project/proxy/extensions/metadata_exchange`

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[x] Developer Infrastructure

**Expected behavior**

run `make build_wasm` successfully

**Steps to reproduce the bug**

```
git clone https://github.com/istio/proxy.git
cd proxy
BUILD_WITH_CONTAINER=1 make build && make build_wasm
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

1.6.1

**Environment where bug was observed (cloud vendor, OS, etc)**

Ubuntu 20.04

**Comment by ericvn** [comment]
A couple comments:
-  istio/proxy defaults to BUILD_WITH_CONTAINER=0 (see the Makefile.overrides.mk file).
- Thus I'm not sure that this repo was ever confirmed to work using a build container.

It looks like the build image being used is not current: https://console.cloud.google.com/gcr/images/istio-testing/GLOBAL/build-tools-proxy?gcrImageListsize=30

**Comment by bianpengyuan** [comment]
Yeah, as @ericvn mentioned BUILD_WITH_CONTAINER is not well supported in istio/proxy. If you only want to build Wasm modules, you could just run `make build_wasm` which already happens in a container and should require no dep from environment.

Also just fyi master branch has gotten rid of docker based wasm build and uses bazel to build wasm now. If you just want to try it out, maybe master branch would be easier for you.

**Comment by dozer47528** [comment]
It works in master branch, will investigate the source code based on master branch.
