### ISSUE TITLE
Securely provision VM mesh identity based on VM's platform identity

### ISSUE THREAD

**Issue by liminw** [istio/istio#24555]
Design doc: https://docs.google.com/document/d/1-612Sgz_skeoX44dw3MU6Z8ONgq1f29wLUI9zggyLec

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by incfly** [comment]
@liminw ideally we should set the priority and label it as enhancement in future for feature or progress work, thanks!
