### ISSUE TITLE
Securely bootstrap VM identities

### ISSUE THREAD

**Issue by liminw** [istio/istio#24554]
Design doc: https://docs.google.com/document/d/1BuwOX6D30Yy6lTvj4RHwLzcUoaAu61pAdtKnLx312ec

This is required for VMs without existing identities. However, the same approach can also be applied to any VMs, to bootstrap them using a k8s identity. 

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by incfly** [comment]
We should add `kind/enhancement` so that we can exclude this during bug scrubbing, thanks!

**Comment by liminw** [comment]
@williamaronli

**Comment by williamaronli** [comment]
thanks limin. Will take it

**Comment by williamaronli** [comment]
A PR to test server side code of authenticator: https://github.com/istio/istio/pull/25034

**Comment by williamaronli** [comment]
an implementation of the rotation https://github.com/istio/istio/pull/25408/commits
