### ISSUE TITLE
Kiali endpoint is broken when using istio canary version. 

### ISSUE THREAD

**Issue by dileep-p** [istio/istio#24559]
**Bug description**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

when upgrading the istio with canary version the service name for istiod will be something like istiod-${canary-name}. however in the kiali config i am not able to find any option to modify this value
```
external_services:
  istio:
    url_service_version: http://istiod.istio-system:15014/version
```
This need to be like
```
external_services:
  istio:
    url_service_version: http://istiod-canary.istio-system:15014/version
```

https://github.com/istio/istio/blob/master/manifests/charts/istio-telemetry/kiali/templates/configmap.yaml#L36

Here the istiod need to be picked up from the revision or null if its not set. 

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by brian-avery** [comment]
Hey @dileep-p. Can this be closed?

**Comment by dileep-p** [comment]
Closing.
