### ISSUE TITLE
Make Istio CA API public in istio/api

### ISSUE THREAD

**Issue by myidpt** [istio/istio#24553]
**Describe the feature request**

**Describe alternatives you've considered**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ X ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
https://github.com/istio/api/pull/1520
