### ISSUE TITLE
Issue with 1.6.1 packaging

### ISSUE THREAD

**Issue by illidan80** [istio/istio#24577]
Trying to download latest version:

`curl -L https://istio.io/downloadIstio | sh -`

Getting:

```
root@user:~# curl -L https://istio.io/downloadIstio | sh -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   107  100   107    0     0    143      0 --:--:-- --:--:-- --:--:--   143
100  3896  100  3896    0     0   3429      0  0:00:01  0:00:01 --:--:-- 3804k
Downloading istio-1.6.1 from https://github.com/istio/istio/releases/download/1.6.1/istio-1.6.1-linux.tar.gz ...Failed.

Trying with TARGET_ARCH. Downloading istio-1.6.1 from https://github.com/istio/istio/releases/download/1.6.1/istio-1.6.1-linux-amd64.tar.gz ...
```

... and stuck

You can see that is not adding architecture to the file name:

`...nload/1.6.1/istio-1.6.1-**linux.tar.gz** ...Failed.`

I can't find anything in the [download guide](https://istio.io/docs/setup/getting-started/#download) about "TARGET_ARCH"

**Comment by brian-avery** [comment]
Hi @illidan80. I just tried and it worked for me. Looking at the logs:

```
curl -L https://istio.io/downloadIstio | sh -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   107  100   107    0     0    351      0 --:--:-- --:--:-- --:--:--   350
100  3896  100  3896    0     0   7792      0 --:--:-- --:--:-- --:--:--  7792
Downloading istio-1.6.8 from https://github.com/istio/istio/releases/download/1.6.8/istio-1.6.8-linux.tar.gz ...Failed.

Trying with TARGET_ARCH. Downloading istio-1.6.8 from https://github.com/istio/istio/releases/download/1.6.8/istio-1.6.8-linux-amd64.tar.gz ...
```

It first tries without the architecture in the URL. If that fails, then it tries with the architecture in the URL. Looking at your output, I see that the TARGET_ARCH request did attempt to use the architecture, but don't see what happened on your system after that.

```
 https://github.com/istio/istio/releases/download/1.6.1/istio-1.6.1-linux-amd64.tar.gz
```

TARGET_ARCH will be set automatically to the processor architecture of the system you're running the script from. It can be overridden to x86_64, armv8*, aarch64*, armv*, amd64, or arm64.

**Comment by illidan80** [comment]
@brian-avery Hey, seems like you right. I had issue related to Hyper-V networking, which was causing for some reason for slow downloads. As soon as I fixed it - everything works as normal. Thank you
