### ISSUE TITLE
"istioctl analyze" and analysis framework support exportTo

### ISSUE THREAD

**Issue by esnible** [istio/istio#24572]
https://github.com/istio/istio/pull/24443 was approved and is merging.

I believe it introduces a new class of mistake.  References from one CR to another CR might work in some namespaces but not others because each CR might have different exportTo.

See https://github.com/istio/istio/pull/24443#issuecomment-641660339

**Comment by rshriram** [comment]
I think you can reuse some of the logic in the push context to determine if the subsets are visible to the virtual service.

**Comment by hanxiaop** [comment]
I think this should have been fixed by several PRs which fixed the `exportTo` issue.
