### ISSUE TITLE
Convert Pilot Integration Tests to use multicluster

### ISSUE THREAD

**Issue by stevenctl** [istio/istio#24581]
As part of #23618 we will convert all tests under [tests/integration/pilot](https://github.com/istio/istio/tree/master/tests/integration/pilot) to utilize however many clusters are provided by the test framework. 

Test conversions:
- [X] Traffic (sniffing, virtual service, etc.)
- [X] Mirroring
- [ ] TCP flakes (that occur for single cluster) are frequent in multicluster
- [X] sniffing flakes
- [ ] shifting flakes
- [ ] Locality

Other tasks:
- [X] Create prow job
- [ ] Make prow job blocking (blocked by flakes)

**Comment by stevenctl** [comment]
The last thing blocking us from making this job required are flakes in traffic shifting like this:

https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27795/integ-pilot-multicluster-tests_istio/2259

**Comment by stevenctl** [comment]
As well as failing to call naked service:
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27786/integ-pilot-multicluster-tests_istio/2627

**Comment by bianpengyuan** [comment]
I downgrade this issue to P1 since I don't think this is a blocking issue for 1.8. please let me know if otherwise. thanks!

**Comment by stevenctl** [comment]
We have this job marked as required. There are a handful of skipped tests with their own issues to track them.
