### ISSUE TITLE
Refactor istioctl to seperate lib from command

### ISSUE THREAD

**Issue by stevenctl** [istio/istio#24583]
Code in istioctl/cmd needs to be refactored to get rid of some shared global state and isolate library functionality from istioctl command specific code. This came up in https://github.com/istio/istio/pull/24523 as running istioctl code from within tests doesn't work concurrently. 

* Split things apart a bit to separate the library code from the commands.
* Allow the kube clients to be provided directly, rather than istioctl creating them from kubeconfig files.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[X] Test and Release
[ ] User Experience
[X] Developer Infrastructure

**Additional context**

**Comment by esnible** [comment]
@stevenctl are you working on this?
@therealmitchconnors are you working on this?

**Comment by esnible** [comment]
@stevenctl are you working on this?  If not, please unassign yourself.
