### ISSUE TITLE
Sidecar-specific access log configuration

### ISSUE THREAD

**Issue by nicktrav** [istio/istio#24591]
**Describe the feature request**

Currently, the access log file descriptor is defined mesh-wide, in [`MeshConfig`](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig).

These access logs are useful for debugging and troubleshooting, but in large meshes, the logging output can be excessive (and indirectly expensive when running in cloud-based environments).

Consider exposing the ability to tune both the access logging file descriptor as well as the logging format for each workload.

`Sidecar` seems like a decent place to put this, given that this could potentially be used as a "per-sidecar" configuration.

**Describe alternatives you've considered**

Our current workaround is editing the ConfigMap and performing a `kubectl -n istio-system rollout restart deployment/pilot` to pick up the change.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by bianpengyuan** [comment]
Adding tracing/logging config to sidecar was proposed before but got pushed back. @douglas-reid Would have more context. Anyway https://github.com/istio/istio/issues/24287 should cover this feature request and it is top of the list for 1.7. Would you mind to close this one and track there? thanks!

**Comment by nicktrav** [comment]
Thanks @bianpengyuan - I take it you're talking about this comment?

> I'd expand your third option to at least include access logging (not only tracing).

If that's the case, then I'll close this now in favor of #24287.

**Comment by bianpengyuan** [comment]
Thanks! Yeah, it will for sure include both logging and tracing. Issue title also suggests that.
