### ISSUE TITLE
istioctl manifest apply cannot add log_output_level=ads:debug to "only" istiod

### ISSUE THREAD

**Issue by nak3** [istio/istio#24595]
**Bug description**

[x] Installation

**Expected behavior**

- `istioctl` can add `--log_output_level=ads:debug` to istiod only.

**Steps to reproduce the bug**

- Currently logging level is only supported by `values.global.logging.level` like `--set values.global.logging.level="ads:debug"`.
- It allows to add the log level to istiod but it also adds it to ingressgateway and other component. Hence istio-ingressgateway fails to start.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

istio-1.6.1

**How was Istio installed?**

#### 1. Install istio with `--set values.global.logging.level="ads:debug"`

```
istioctl manifest apply  --set values.global.logging.level="ads:debug"
```

#### 2. istio-ingressgateway fails to start.

```
$ kubectl get pod -n istio-system 
NAME                                    READY   STATUS              RESTARTS   AGE
istio-ingressgateway-549ddc68d8-zjksr   0/1     CrashLoopBackOff    1          11s
```

This is due to invlaid log option.

```
$ kubectl -n istio-system  logs istio-ingressgateway-549ddc68d8-zjksr
  ...
Error: unknown scope 'ads' specified
2020-06-11T02:30:59.044768Z	error	unknown scope 'ads' specified
```

**Comment by morvencao** [comment]
This is an issue, we should validate the user input for this global logging level.

The control plane has different scopes depending on component, but can configure default log level across all components.

**Comment by taitelman** [comment]
pls validate log config line
