### ISSUE TITLE
Document on how to remove istiod canary version

### ISSUE THREAD

**Issue by cober** [istio/istio#24603]
**Describe the feature request**
Reading https://istio.io/latest/docs/setup/upgrade/#canary-upgrades
we found out how to install istiod canary release via `istioctl install --set revision=canary`, however we can't find a solution how to remove it from the cluster.

**Describe alternatives you've considered**

[x] Configuration Infrastructure
[x] Docs
[x] Installation
[] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by Kampe** [comment]
Yeah, is there a way?

**Comment by esnible** [comment]
Closing as a duplicate of https://github.com/istio/istio/issues/18900
