### ISSUE TITLE
Istiod output enourmously spammed from validationServer

### ISSUE THREAD

**Issue by cober** [istio/istio#24602]
**Bug description**
We are seeing an enourmous amount of these kind of logs in Istiod:
`2020-06-11T10:41:01.446310Z    info    validationServer    unrecognized type MeshPolicy                                                                                                                                                   ││ 2020-06-11T10:41:01.452462Z    info    validationServer    unrecognized type MeshPolicy                                                                                                                                                   ││ 2020-06-11T10:41:01.597236Z    info    validationServer    unrecognized type MeshPolicy                                                                                                                                                   ││ 2020-06-11T10:41:01.603483Z    info    validationServer    unrecognized type MeshPolicy                                                                                                                                                   ││ 2020-06-11T10:41:01.794295Z    info    validationServer    unrecognized type MeshPolicy                                                                                                                                                   ││ 2020-06-11T10:41:01.798215Z    info    validationServer    unrecognized type MeshPolicy                                                                                                                                                   ││ 2020-06-11T10:41:01.994113Z    info    validationServer    unrecognized type MeshPolicy                                                                                                                                                   ││ 2020-06-11T10:41:02.010717Z    info    validationServer    unrecognized type MeshPolicy                                                                                                                                                   ││ 2020-06-11T10:41:02.194687Z    info    validationServer    unrecognized type MeshPolicy                                                                                                                                                   ││ 2020-06-11T10:41:02.198839Z    info    validationServer    unrecognized type MeshPolicy                                                                                                                                                   ││ 2020-06-11T10:41:02.394301Z    info    validationServer    unrecognized type MeshPolicy                                                                                                                                                   ││ 2020-06-11T10:41:02.398096Z    info    validationServer    unrecognized type MeshPolicy                                                                                                                                                   ││ 2020-06-11T10:41:02.594239Z    info    validationServer    unrecognized type MeshPolicy                                                                                                                                                   ││ 2020-06-11T10:41:02.598070Z    info    validationServer    unrecognized type MeshPolicy                                                                                                                                                   ││ 2020-06-11T10:41:02.794075Z    info    validationServer    unrecognized type MeshPolicy                                                                                                                                                   ││ 2020-06-11T10:41:02.798265Z    info    validationServer    unrecognized type MeshPolicy                                                                                                                                                   ││ 2020-06-11T10:41:02.995469Z    info    validationServer    unrecognized type MeshPolicy                                                                                                                                                   ││ 2020-06-11T10:41:02.999218Z    info    validationServer    unrecognized type MeshPolicy                                                                                                                                                   ││ 2020-06-11T10:41:03.194129Z    info    validationServer    unrecognized type MeshPolicy                                                                                                                                                   ││ 2020-06-11T10:41:03.197993Z    info    validationServer    unrecognized type MeshPolicy                                                                                                                                                   ││ 2020-06-11T10:41:03.394005Z    info    validationServer    unrecognized type MeshPolicy                                                                                                                                                   ││ 2020-06-11T10:41:03.398075Z    info    validationServer    unrecognized type MeshPolicy                                                                                                                                                   ││ 2020-06-11T10:41:03.594068Z    info    validationServer    unrecognized type MeshPolicy                                                                                                                                                   ││ 2020-06-11T10:41:03.597973Z    info    validationServer    unrecognized type MeshPolicy                                                           `

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Expected behavior**
It's really hard for end-user to debug these kind of messages, since we have no any idea where to start from as well as what is the impact of these messages.

**Steps to reproduce the bug**
Not known, last what we were trying is to use istioctl to generate an user defined ingressonly and apply that one to another namespace, where all components get deployed as well with new svc IP, but ingressgateway was returning 404 no matter what, could be related something to that.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
Istio 1.6.1

**How was Istio installed?**
Istioctl install

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE 1.16.9-gke.2

`istioctl analyze -n ab
✔ No validation issues found when analyzing namespace: ab.`

**Comment by cober** [comment]
In addition:
what we could see is no matter if we try to hit the application through that new IP of istio-ingressgateway (which supposed to be a part of AB test), we always ended up in currently working one, that is running on production.

I believe that user defined ingress gateway was for some reason not properly registered in Istio mesh, maybe? (this was done via same working host as on production - if we put a totally new host, we would get 404 response)

**Comment by howardjohn** [comment]
That error suggests you are using the mesh policy resource which is removed (see upgrade notes for migration). You can see all of them in the cluster with `kubectl get meshpolicy -A`

**Comment by cober** [comment]
thanks @howardjohn 

this has fixed our issue, closing this one now.
