### ISSUE TITLE
Move CNI repo to Istio/istio

### ISSUE THREAD

**Issue by jwendell** [istio/istio#24610]
Part of https://github.com/istio/istio/issues/24416

Steps:
- [x] Copy/Merge CNI files into cni subdir and make sure it builds and passes the tests (https://github.com/istio/istio/pull/24692)
- [x] Update CODEOWNERS (https://github.com/istio/istio/pull/24692)
- [x] Remove duplicate files like LICENSE, CONTRIBUTING (https://github.com/istio/istio/pull/24692)
- [x] Update README.md on CNI repo to declare deprecation (https://github.com/istio/cni/pull/343)
- [x] Use docker.mk instead of custom stuff (https://github.com/istio/istio/pull/24724)
- [x] Remove `cni@master` jobs on Prow (https://github.com/istio/test-infra/pull/2712)
- [x] Remove references for CNI in `istio/release-builder` repo (https://github.com/istio/release-builder/pull/281)
- [x] Remove references for CNI in `istio.deps` and `update_deps.sh` (https://github.com/istio/istio/pull/24727)
- [x] Update integration tests that refer to old location (https://github.com/istio/istio/pull/24755)
- [x] (Bonus) Replace CNI's iptables.sh with istio-iptables golang implementation (https://github.com/istio/istio/pull/24759)
- [ ] Block automatic merges on `cni@master` - Is it possible?
- [ ] Update operator charts to reflect new location - I think it's not needed
- [ ] Remove all test-infra, makefile, etc stuff and use the main one (where possible) - All done?

**Comment by howardjohn** [comment]
* Update CODEOWNERS
* Remove duplicate files like LICENSE, CONTRIBUTING
* Use docker.mk instead of custom stuff
* Remove all test-infra, makefile, etc stuff and use the main one (where possible)

**Comment by stewartbutler** [comment]
- [ ] Remove CNI SHA from istio.deps
- [ ] Remove CNI SHA setter from update_deps.sh

**Comment by jwendell** [comment]
Closing as I believe this is done. I don't think the last 3 items are an issue.

**Comment by howardjohn** [comment]
Thank you! This is great
