### ISSUE TITLE
Istio logo broken in Grafana

### ISSUE THREAD

**Issue by brian-avery** [istio/istio#24618]
**Bug description**
The Istio logo currently points at https://istio.io/img/istio-logo.svg. It should point at https://istio.io/latest/img/istio-logo.svg. It looks like there are also other references on istio.io that are broken as well. There's a pointer to https://istio.io/img/logo.png that should point to https://istio.io/latest/img/logo.png on the istio.io homepage. 

[ ] Configuration Infrastructure
[x ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by ldemailly** [comment]
for some reason this is still broken with 1.7

**Comment by shamsher31** [comment]
Closed by https://github.com/istio/istio/pull/27573

**Comment by brianwolfe** [comment]
OOC, why pull the image from the net instead of embedding it? The istio logo is a pretty small svg.
