### ISSUE TITLE
Support locality aware routing for non-mesh workloads

### ISSUE THREAD

**Issue by Stono** [istio/istio#24631]
**Describe the feature request**
Locality aware routing doesn't work when your destination kubernetes service does not have sidecars.  I'm guessing this is because it is the responsibility of the destination sidecar to tell proxy its zone.

Technically this information would be available in the kubernetes API, so pilot could probably calculate it instead, which would add support for locality load balancing on non-istio workloads.

**Describe alternatives you've considered**
If my assumption about metadata is correct, could I add a sidecar to the destination with:

 - traffic.sidecar.istio.io/includeOutboundPorts: ""
 - traffic.sidecar.istio.io/includeInboundPorts: ""

To have it start with a sidecar, report metadata allowing clients to do locality routing, but not intercept the requests?

(The decision to exclude this target from any istio request interception was a technical one we don't want to revisit) 

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[x] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by Stono** [comment]
update: I tried adding a sidecar configured with those annotations as like a metadata-only thing and localitylb still didn't work 🤔

**Comment by howardjohn** [comment]
I'm surprised this doesn't work actually, I would expect it to.. we do get the locality from k8s currently for destinations. Will need to take a closer look

**Comment by Stono** [comment]
@howardjohn me too :s it's probably something specific about my service setup.  If you're free at some point ping me on slack and we can debug it together, it'll be more effective than github tennis :D

**Comment by Stono** [comment]
I figured this out, it was human error - since then @howardjohn has made istioctl stricter to error at unknown fields - which would have caught my error.  Closing this
