### ISSUE TITLE
Investigate add-ons for central Istiod

### ISSUE THREAD

**Issue by linsun** [istio/istio#24636]
**Describe the feature request**
for #22934, we need to check if telemetry works for central istiod on what deployment model we can recommend or even allow.  Things to think about:
- can I run add on (prometheus, Grafana, zipkin & Kiali) on main cluster?
- do I run these add-on on remote cluster if that is the only cluster that serves workloads?
- How are user accessing them?
- Is the connection secured from the add-on to the sidecars?
- Any consideration for upgrade?  I assume we don't support multi-revisions for add-ons.

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
Is this still relevant given we do not install and manage addons?
