### ISSUE TITLE
ClusterLoadAssignment for istiod not working in-cluster

### ISSUE THREAD

**Issue by esnible** [istio/istio#24639]
To reproduce, make sure you have at least two Istiod pods.  Port forward to one of them.  Ask for ClusterLoadAssignment.  Should get back address of each pod.

```
kubectl -n istio-system patch horizontalpodautoscaler istiod --type=json --patch='[{"op": "replace", "path": "/spec/minReplicas", "value": 2 }]'
kubectl -n istio-system port-forward $(kubectl -n istio-system get pods -l istio=pilot -o jsonpath="{.items[0].metadata.name}") 15010
grpcurl -d @ -plaintext localhost:15010 envoy.service.discovery.v2.AggregatedDiscoveryService/StreamAggregatedResources <<EOM
{
   "node": {
      "id": "sidecar~1.1.1.1~debug~cluster.local"
   },
   "typeUrl": "type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment",
   "resourceNames": [
      "outbound|15012||istiod.istio-system.svc.cluster.local"
   ]
}
EOM
```

Assigning to John Howard because of our Wednesday conversation.  If this is invalid please close.

**Comment by howardjohn** [comment]
```
grpcurl -d @ -plaintext localhost:15010 envoy.service.discovery.v2.AggregatedDiscoveryService/StreamAggregatedResources <<EOM
{
   "node": {
      "id": "sidecar~1.1.1.1~debug~cluster.local",
      "metadata": {
          "CLUSTER_ID": "Kubernetes"
      }
   },
   "typeUrl": "type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment",
   "resourceNames": [
      "outbound|15012||istiod.istio-system.svc.cluster.local"
   ]
}
EOM
```

Try this

@nmittler this is cause by cluster local svc. we may need some more debug-ability around this area maybe? Or, maybe we should make it so if cluster id is not specified it gets all endpoints, even if they are cluster local?

**Comment by nmittler** [comment]
@howardjohn would there be any consequence of just making it ignore cluster-local for this call?

**Comment by howardjohn** [comment]
None that I can think of, but probably :slightly_smiling_face:. It does seem like `clusterid==""` should mean "give me stuff for any cluster" rather than "give me nothing" though?

**Comment by nmittler** [comment]
Sounds reasonable to me ... maybe just try it and see if anything breaks?
