### ISSUE TITLE
Allow numbers for ports in authorization policies

### ISSUE THREAD

**Issue by haines** [istio/istio#24633]
**Describe the feature request**

When specifying ports in authorization policy [operations](https://istio.io/latest/docs/reference/config/security/authorization-policy/#Operation), they need to be strings.

In most other places that ports are specified (e.g. gateway [ports](https://istio.io/latest/docs/reference/config/networking/gateway/#Port), virtual service [port selectors](https://istio.io/latest/docs/reference/config/networking/virtual-service/#PortSelector)), they are uint32s.

It's a fairly minor quibble because there is a good error message when running `kubectl apply`
>The AuthorizationPolicy "..." is invalid: spec.rules.to.operation.ports: Invalid value: "int64": spec.rules.to.operation.ports in body must be of type string: "int64"

But it has tripped me up a couple of times now so I wonder if it would be possible to change it to be consistent?

**Describe alternatives you've considered**

Not changing it 😄 

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Comment by incfly** [comment]
This seems a reasonable UX improvement. I think we can use the same proto field, and add new field in Authz policy to make it backward compatabile.

Feel free to drive (discuss on security working group) and own the implementation.
