### ISSUE TITLE
Use Kubernetes clients/informers consistently

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#24640]
Right now we have a huge mess of components taking in kubeconfig file, restconfig, or kubernetes.Interface, spinning up their own interfaces, etc. We should really consolidate.

I think the best practice would be to create a single shared informer at the top level, but we should check how k8s controller-manager is implemented as it is likely following best practices

**Comment by howardjohn** [comment]
https://github.com/projectcontour/contour/tree/360a1b2ce6969bf35499d87e375409321aa4bf27/internal/k8s looks like a pretty good reference as well

**Comment by jronak** [comment]
@howardjohn you can assign this to me, I'll start working on it

**Comment by howardjohn** [comment]
Example from k8s:
controller takes in informer and client: https://github.com/kubernetes/kubernetes/blob/25651408aeadf38c3df7ea8c760e7519fd37d625/pkg/controller/certificates/rootcacertpublisher/publisher.go#L46 (client for writes)

informer is built specifically for this controller: https://github.com/kubernetes/kubernetes/blob/e8b5781499dfb35809c4ede091fc9718f142265e/cmd/kube-controller-manager/app/certificates.go#L151 from a shared factory
client is just the same shared client with a different user agent

informer factory has a single top level start called: https://github.com/kubernetes/kubernetes/blob/15c844031f26d49a115ea9f4c174f3fb1215a5f8/cmd/kube-controller-manager/app/controllermanager.go#L237

factory creation: https://github.com/kubernetes/kubernetes/blob/15c844031f26d49a115ea9f4c174f3fb1215a5f8/cmd/kube-controller-manager/app/controllermanager.go#L481

cert-manager suggest we probably need one factory for each client: https://github.com/jetstack/cert-manager/blob/ba33c823a3aafab99e6045395e01691e0027213f/cmd/controller/app/controller.go#L225

**Comment by bison** [comment]
It looks like these last few PRs linked to this issue undo the work in #23961 to allow scoping Istio's operation to a set of namespaces. Is that right? Is that intentional, and is there a plan to enable this use-case?

**Comment by howardjohn** [comment]
@bison I did not intend to revert any support features we offer, rather to move towards Kubernetes best practices (for performance as well, not just "code style"). I had thought I had covered all cases as the tests passed, do we not have any tests covering this?

I think this should get things working again (I thought this was in the original PR.. must have accidentally reverted it at some point):  https://github.com/istio/istio/pull/25244

**Comment by bison** [comment]
Unfortunately, there weren't really tests, no. My plan was to follow up and add tests as well as moving the list of namespaces to the MeshConfig and a few other bits, but I was just now getting a chance to start on that. The only test was in `testPodCache` but it was removed in #25031.

It looks like #25244 would allow scoping to a single namespace, but not a set of namespaces. Informers over a set of namespaces are not something the client libraries support currently, which is why the `MultiNamespaceListerWatcher` was being used. Though, ultimately that should absolutely be replaced. I actually wanted to propose a replacement for that similar to what's used in controller-runtime's [multiNamespaceCache](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/cache/multi_namespace_cache.go#L72-L83).

Maybe we should discuss this in one of the WG calls. What's the appropriate one?

**Comment by howardjohn** [comment]
Its sort of cross-Istio issue... could be Environments or Networking. Maybe Env since it aligns more with multitenancy I suppose.

Thanks for the link to multiNamespaceCache, that is useful. I was thinking of a similar thing.

I think the requirements are:

* There is a single shared client used throughout the codebase (this is what my PR does). This includes sharing informers, which is especially important to not have redundant watches on the api-server, especially for cases where we want to do very minimal lookups (like lookup Service in Ingress controller), so these can be low cost.
* A user can specify a list of namespaces to watch, and only requires RBAC for those namespaces (this was implemented, now the option exists but is broken)
  * This has e2e testing
* Optional: namespace list moves to mesh config
* Optional: namespace list is dynamic
* Really optional, but nice to have: crd client maintains current typed interface (ie `informers.CoreV1().Pods()` rather than `informers.ForResource(GVR{pod})`)

Does that align with your expectations?

**Comment by bison** [comment]
I think that's exactly it, yeah.

I'd personally really like to see the namespace list moved to the mesh config, and for it to be dynamic, but that's definitely kind of secondary.

I think the hardest part is coming up with something for the informers. It's pretty easy to just maintain a list of shared informers, and add event handlers to each, but handling the places that are then reaching into the informer's cache directly is maybe a little trickier.

**Comment by tbarrella** [comment]
Any thoughts about using controller-runtime more? I noticed the istiocontrolplane controller uses it. It removes a lot of the boilerplate around creating informers and workqueues. It also seems to encourage level-triggered reconciliation logic, which could help prevent syncing issues

**Comment by noah8713** [comment]
for istio 1.7.4 too watching limited namespace is broken as https://github.com/istio/istio/pull/23961 is reverted. As a result , using comma separated namespaces with ```-a="foo,bar,car"``` and ```
oneNamespace: false``` doesnt take any effect. 

In addition, this causes noisy logs in istiod continuously as below as we don't want to watch on all ns(~10k ns) and all such ns are added to queue again for retry
```
2020-11-10T00:35:46.590078Z	info	Work item handle failed (error when creating configmap istio-ca-root-cert: configmaps "istio-ca-root-cert" is forbidden: exceeded quota: object-counts, requested: configmaps=1, used: configmaps=0, limited: configmaps=0), retry after delay 1s
2020-11-10T00:35:52.190341Z	info	Work item handle failed (error when creating configmap istio-ca-root-cert: configmaps "istio-ca-root-cert" is forbidden: exceeded quota: object-counts, requested: configmaps=1, used: configmaps=0, limited: configmaps=0), retry after delay 1s
2020-11-10T00:36:48.490297Z	info	Work item handle failed (error when creating configmap istio-ca-root-cert: configmaps "istio-ca-root-cert" is forbidden: exceeded quota: object-counts, requested: configmaps=1, used: configmaps=0, limited: configmaps=0), retry after delay 1s
2020-11-10T00:37:21.540204Z	info	Work item handle failed (error when creating configmap istio-ca-root-cert: configmaps "istio-ca-root-cert" is forbidden: exceeded quota: object-counts, requested: configmaps=1, used: configmaps=0, limited: configmaps=0), retry after delay 1s
```
@howardjohn @bison : Is this WIP or still in discussion?
Seems doc needs to be updated because current 1.7.4 doesn't support filtering on namespace for namespace controller.

**Comment by bison** [comment]
Yes, I think limiting things to a set of namespaces unfortunately does not work in 1.7 or 1.8, and the docs and/or help output should probably be fixed.

I was working on this, but got distracted. I'm very much still interested seeing it fixed, and have something I've been meaning to propose. Basically an updated version of #25692 -- I will try to push that soon.
