### ISSUE TITLE
Support minimal deployments of Istio

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#24655]
* [x] Allow running without all (or any Istio CRDs). Done: we detect CRDs
* [x] Allow running without Validation webhook permissions. Done: `VALIDATION_WEBHOOK_CONFIG_NAME=""`
* [x] Allow running without creating CA. Done: `ENABLE_CA_SERVER="false"`
* [ ] Allow running without secret permission. TODO: currently multicluster controller always needs secret access.
* [ ] Allow running without Istio CRD RBAC, if CRDs are not installed. TODO: validate if that works, if not document what is broken
* [ ] Allow running Gateway SDS without workload certificates. Currently we need to completely disable SDS, which ends up breaking the gateway SDS
* [ ] Automatically disable auto mtls if we don't have certificates mounted/SDS enabled.

cc @costinm

**Comment by costinm** [comment]
Why does MC controler need secret ? Doesn't make sense, that's a huge permission. 

I'm not sure disabling CA is sufficient - last I tried we still generate clusters with mTLS. There is a setting to configure the pilot plugins, if you disable auth it'll work without CAs. That's for the last item.

For Gateweay (and sidecar) - we still want to run SDS, but if 'control plane auth policy' is off or port 15010 it should not 
ask for workload certs. But still need to support loading certs if defined explicitly - it can be from filesystem only.
