### ISSUE TITLE
pilot /debug/configz should output in Kubernetes format

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#24651]
Right now we output a model.Config which cannot easily be copy+pasted into a kubernetes resource. We should use the same spec as we k8s so we can easily view/copy them

**Comment by adiprerepa** [comment]
@howardjohn where is the instance of this? The closest thing I could find is `pkg/mcp/configz/client/configz.go`, which is not in pilot? Please point me to the right instance so I can fix it.

**Comment by howardjohn** [comment]
There is a v2/debug.go file under pilot which should have this one

**Comment by adiprerepa** [comment]
Oh it was an endpoint. Got it thanks. Note to self: https://github.com/istio/istio/blob/d858d423f1877ce2a1eb3553c074257e2bffcc18/pilot/pkg/proxy/envoy/v2/debug.go#L349
