### ISSUE TITLE
istio ingress elb provisioning - aws private subnet

### ISSUE THREAD

**Issue by devaraj-avx** [istio/istio#24663]
**Bug description**
We are trying to provision complete kubernetes cluster in AWS private subnet for the security reasons. Using KOPS for provisioning the K8S cluster and using istio for the mesh and the traffic routing (ingress, egress, etc). 

Normally when we tried provisioning the **_Dev env (AWS public subnet)_** - istio provisioned elb on the public subnet and we were able to access the cluster using the ingress ELB. While we define private subnet for the cluster creation, istio is not provisioned the elb on the private subnet. 

The status of the service see as "pending" with the kubectl output. ELB has NOT created in AWS - 
_istio-ingressgateway        LoadBalancer   100.71.180.200   <pending>     15020:32419/TCP,80:31607/TCP,443:31426/TCP,31400:31097/TCP,15443:31829/TCP   3d18h_

[ X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
ISTIO ingress ELB to be provisioned in private subnet.

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
# istioctl version
client version: 1.6.1
control plane version: 1.6.1
data plane version: 1.6.1 (15 proxies)

# kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.10", 

**How was Istio installed?**
$ curl -L https://istio.io/downloadIstio | sh -
$ istioctl install --set profile=demo

**Environment where bug was observed (cloud vendor, OS, etc)**
Cloud - AWS

**Comment by howardjohn** [comment]
This is not configured by Istio. We simple create Service of type=LoadBalancer, the rest is up to the Kubernetes install. Please refer to upstream Kubernetes or AWS documentation on how to configure this. Thanks!
