### ISSUE TITLE
Move Gateway SDS to Istiod

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#24667]
Currently, Ingress secrets are read by the ingressgateway deployment. This is based on the original [design doc](https://docs.google.com/document/d/1agtVQADCk32mLwot8iygVGhHcP1Lna7G1Cne4Zwllgg/edit#). We are also adding Egress gateway SDS, which may also include for sidecars which are doing TLS origination.

These secrets read only within the same namespace to reduce permissions. This causes issues where users want cross namespace references of certs (as require by the [Ingress spec](https://kubernetes.io/docs/concepts/services-networking/ingress/), for example).

In the original design doc, we consider only reading secrets in nodeagent or in the gateway deployment. I propose we do a third option, and move it to Istiod.

What this would involve:
* Remove Ingress SDS reader from gateway
* Pilot sends SDS configuration pointing to the xds-grpc cluster rather than sds-grpc cluster, which will cause Envoy to start sending SDS request to Pilot instead of locally
* Pilot will implement the SDS type. It will follow similar logic as the agent, looking up secrets on requests and pushing relevant secrets on updates.
* Secret format will change from `<k8s-secret-name>` to `kubernetes|<secret-name>.<secret-namespace>` to support future changes
* `certificateName` field will be changed to `namespace/name`. If the old `name` format is used, we will default to the namespace of the deployment for backwards compatibility.
* We can offer an option to disable cross namespace references in `certificateName`, *and* limiting the namespaces Pilot actually watches/has permissions to for multitenancy/security lock down - this will need some consideration to do properly.

Pros:
* Potentially lower attack surface. As the gateways are public internet facing, they are a much larger target for attacks
* Lower permissions. Currently, Istiod requests clusterwide secret R/W, and gateway requests local read. With this change, we can modify gateway to require no k8s access, and Istiod will retain the same permissions. Note - Istiod currently *should not* be R/W to all namespaces; it should just be R/W to istio-system. With this change we would require read access to the cluster, or for locked down scenarios just `<ingress-deployment-namespace>` (to read certificates) and `istio-system` (to manage CA secret).
* Much better ability to support SDS secret fetching for sidecars. There is ongoing effort to support secret fetching for egress and/or sidecars (https://github.com/istio/api/pull/1468). The primary issue with sidecars is how we handle the permissions (what namespace are the secrets in, and how do we delegate permissions, etc). These issues all go away here, as Istiod is already privileged. However, we do need a way to ensure that users cannot escalate write access to DestinationRule to get Istiod to send them secrets they should not have access to.
* Less dependency on api-server. This allows running gateways without access to k8s, which can be useful for VMs and reduces load on the api-server.
* Simpler code. All of pilot is designed around serving XDS; adding secrets is trivial and can benefit from the years of work invested in the xds serving pipeline. This will avoid bugs we have seen in SDS such as failing to update, infinite loops, improper xds handling, etc.
  * As a further step, we can completely eliminate in process SDS if desired. There is no hard dependency on SDS for workload certs; we can do hot reloads of certificates now so the agent can just manage some files on the (memory mounted) disk rather than serving SDS. This is not required for the rest of the proposal however.
* Easier to integrate with other systems
  * Users can more easily point to an alternative SDS implementation if they have one
  * If we want to integrate fetching secrets from something other than k8s (vault, KMS, etc), we can easily do so without bloating istio-agent further
* Debloat istio-agent. Currently the binary is pretty large by including all of k8s apis. By removing this we can trim things down quite a bit

Neutral:
* Security of secrets in transit is unchanged. In both Ingress and Pilot we would transfer secrets over the wire. For ingress, this is k8s -> istio-agent. For Pilot, this is k8s -> pilot -> envoy.

Cons:
* Potentially larger attack surface. Ingress SDS is served over UDS so we don't have any authn/authz required. The Ingress threat model therefor primarily involves an attacker gaining access to the pod. However istiod we will serve SDS externally, which opens a potential attack vector, where a user bypasses auth and gains access to secrets it should not have permission to access. However, an attacker gaining access to Istiod pod does not have much more priviledge compared to today, where they can currently access the root secret *and* have extremely high privileges to access k8s cluster-wide.
* Some implementation effort required to move things over

(note - this is my thoughts only, has not been discussed wider)

**Comment by costinm** [comment]
The main issue is the autn and authz in istiod.


In reality we load the secrets over https using a k8s token - from
apiserver. It's not so different from doing the same from istiod, as long
as istiod has solid authz.

Clearly istiod can do additional checks - we could even allow
cross-namespace in some cases ( maybe with some extra requirement - like
label or name convention so we can restrict what secrets we access ).

Having the SDS grpc in istiod with the same authn we use for workloads is
not hard. But we can't anyone pretending to be a gateway load any secrets
from anywhere.

**Comment by howardjohn** [comment]
Agreed. This is certainly dependent on the baseline auth we are planning to add to check ns/sa, but we will also probably need some explicit checks. We can't treat Gateway as the auth check either (as in only return secrets referenced in Gateway) since you can still impersonate, so likely need some extra check. I'll think this part over a bit

**Comment by howardjohn** [comment]
cc @nschhina @JimmyCYJ

**Comment by JimmyCYJ** [comment]
cc @myidpt

**Comment by nschhina** [comment]
Like discussed during the security wg meeting- we cannot get this feature out by 1.7. There's ongoing efforts for DestinationRule reading k8s secrets using CredentialName at the egress gateway:https://github.com/istio/istio/issues/14039. [Design Doc](https://docs.google.com/document/d/1--c7Y4MR5CL-q6Fl5UlYLzluQpAlRcdyJ1gOUB98Njg) 
There's one major concern, which is DR is used for direct sidecar tls origination and sidecars can't read istio-system namespace secrets which means that the DR API handles egress gateway case differently. Moving to istiod would solve this concern, but given there's not enough time before 1.7 release, I think we should proceed with this change in DR API for egress gateway and can later integrate this change to support direct sidecar tls origination using CredentialName. 

There's another proposal for CredentialName for DR as well as Gateway API which allows users to specify a directory for the CredentialName field where the users can mount their TLS certs and later we can use file based SDS to read secrets from that directory specified in sidecar/gateway or "fallback" to reading the k8s secret for the CredentialName specified at the Egress Gateway. This would make use of CredentialName more consistent for direct origination from sidecar and also through egress gateway. This approach would be very structured but brings more consistency and we could slowly encourage using CredentialName over specifying file paths in DR as well as Gateway API. I'll work on this RFC soon.  

cc: @howardjohn @costinm

**Comment by ramaraochavali** [comment]
We need to consider the case of people specifying file paths when we move this to Istiod or this intended to be applied for only for other cases?

**Comment by howardjohn** [comment]
Related doc: https://docs.google.com/document/d/1nwTh2g7FgdkC8suc3SHZ5le_4Rkm8YvLY8Cgah4cm-I

**Comment by howardjohn** [comment]
This is implemented and shipped in 1.8
