### ISSUE TITLE
Enabling PodDisruptionBudget for Istio Kiali

### ISSUE THREAD

**Issue by zufardhiyaulhaq** [istio/istio#24672]
**Describe the feature request**
Enable user to setup Pod Disruption Budget for Kiali. Currently, the istio-telemetry/kiali chart doesn't have Pod Disruption Budget

**Describe alternatives you've considered**
The workaround for this is to create PDB for Kiali deployment.

[X] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
Given our impending plans for addons (https://istio.io/latest/blog/2020/addon-rework/), I don't think this makes sense to add. If you need customization of Kiali, please install from https://kiali.io/.

**Comment by howardjohn** [comment]
Closing per ^
