### ISSUE TITLE
Enabling PodDisruptionBudget for Istio CoreDNS

### ISSUE THREAD

**Issue by walbertus** [istio/istio#24671]
**Describe the feature request**
Enable user to setup PodDisruptionBudget for Istio CoreDNS

**Describe alternatives you've considered**
The workaround for this is to create external PDB and specify the CoreDNS labels.

[X] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
Given the deprecation of istiocoredns and since we do not backport features to old versions, I do not think this will be done. Thanks. See https://istio.io/latest/blog/2020/addon-rework/ for more info
