### ISSUE TITLE
Install instructions link displayed in the CLI is broken

### ISSUE THREAD

**Issue by avinashdesireddy** [istio/istio#24679]
**Bug description**
I used the command ``` curl -L https://istio.io/downloadIstio | sh - ``` to download and install istio. 
After successful install, the following console message is pointing to invalid URLs

```
Istio 1.6.2 Download Complete!

Istio has been successfully downloaded into the istio-1.6.2 folder on your system.

Next Steps:
See https://istio.io/docs/setup/kubernetes/install/ to add Istio to your Kubernetes cluster.

To configure the istioctl client tool for your workstation,
add the /home/admin/istio-1.6.2/bin directory to your environment path variable with:
	 export PATH="$PATH:/home/admin/istio-1.6.2/bin"

Begin the Istio pre-installation verification check by running:
	 istioctl verify-install

Need more information? Visit https://istio.io/docs/setup/kubernetes/install/
```

[ ] Configuration Infrastructure
[X] Docs
[X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Either this link [https://istio.io/docs/setup/kubernetes/install/](https://istio.io/docs/setup/kubernetes/install/) should be valid or the output of the CLI should be updated accordingly.

**Steps to reproduce the bug**
Run the command ``` curl -L https://istio.io/downloadIstio | sh - ```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
Istio - 1.6.2

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**
MacOS

**Comment by avinashdesireddy** [comment]
Can I work on this & submit a pull request? 

Going to update the script to reflect the following
```
Istio 1.6.2 Download Complete!

Istio has been successfully downloaded into the istio-1.6.2 folder on your system.

Next Steps:
See https://istio.io/latest/docs/setup/install/ to setup Istio based on the needs and platform.

To configure the istioctl client tool for your workstation,
add the /home/admin/istio-1.6.2/bin directory to your environment path variable with:
	 export PATH="$PATH:/home/admin/istio-1.6.2/bin"

Begin the Istio pre-installation verification check by running:
	 istioctl verify-install

Need more information:
Architecture: https://istio.io/latest/docs/ops/deployment/architecture/
CLI Reference: https://istio.io/latest/docs/reference/commands/istioctl/
```

**Comment by esnible** [comment]
For me, there is a 301 redirect thus the link seems to work.

**Comment by avinashdesireddy** [comment]
it works not. Yesterday I noticed a 404. Looks like a redirect is implemented. 

Closing this issue.
