### ISSUE TITLE
Sidecar proxy resources change

### ISSUE THREAD

**Issue by rnkhouse** [istio/istio#24683]
**Bug description**
Sidecar proxy resources change is not updating with new values.

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
It should update with given resources specs.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
client version: 1.6.2
control plane version: 1.6.2
data plane version: 1.6.2 (10 proxies)

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"ec831747a3a5896dbdf53f259eafea2a2595217c", GitTreeState:"clean", BuildDate:"2020-05-29T19:56:10Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
using istioctl menifest

    ---
    apiVersion: install.istio.io/v1alpha1
    kind: IstioOperator
    spec:
      profile: default
      components:
        sidecarInjector:
          k8s:
            resources:
              requests:
                cpu: 10m
                memory: 10Mi
              limits:
                cpu: 100m
                memory: 50Mi

I also tried adding with:

    proxy:
      k8s:
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
          limits:
            cpu: 100m
            memory: 50Mi

And global values:

    global:
        proxy:
            init:
              resources:
                limits:
                  cpu: 100m
                  memory: 50Mi
                requests:
                  cpu: 10m
                  memory: 10Mi

**Environment where bug was observed (cloud vendor, OS, etc)**
AKS

**Comment by kppullin** [comment]
Have you tried removing `init:` from your `global` config block?

```
global:
    proxy:
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 10Mi
```

**Comment by rnkhouse** [comment]
Such a silly mistake. Thanks for identifying it. @kppullin
