### ISSUE TITLE
TestProxySDS test flake - SKIPPED

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#24680]
https://prow.istio.io/view/gcs/istio-prow/logs/unit-tests_istio_postsubmit/2688

cc @williamaronli @JimmyCYJ

**Comment by williamaronli** [comment]
TestProxySDS fails will take a look the root cause

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gcs/istio-prow/logs/unit-tests_istio_postsubmit/2920

**Comment by JimmyCYJ** [comment]
@williamaronli could you take a look? I don't see a SDS push error. It seems that the proxy initialization timeout is not sufficient for the SDS push.

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gcs/istio-prow/logs/unit-tests_istio_postsubmit/3028

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gs/istio-prow/logs/unit-tests_istio_postsubmit/3316

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gs/istio-prow/logs/unit-tests_istio_postsubmit/3415

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gs/istio-prow/logs/unit-tests_istio_postsubmit/3477

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gs/istio-prow/logs/unit-tests_istio_postsubmit/3487

**Comment by williamaronli** [comment]
is that possible we add some retry logic to mitigate this issue?

**Comment by incfly** [comment]
```
2020-06-15T16:32:55.099448Z	error	cache	JWT expiration checking error: token contains an invalid number of segments: 1, expected: 3. Consider as expired.
```

All the failures I see this error is logged. Which is pretty weird, if you look at the code, that comes from [`parseJwtClaims`](https://github.com/istio/istio/blob/2c81d37a8627ed2b880ee8dd961f7982b94ab1d2/security/pkg/util/jwtutil.go#L116).

```golang
parts := strings.Split(token, ".")
	if len(parts) != 3 {
		return nil, fmt.Errorf("token contains an invalid number of segments: %d, expected: 3", len(parts))
	}
```

I can't think of why a JWT would have only one part after splitting with `.`

@williamaronli maybe you can add some instrmentation there? and if that error occurs, print out the token see what that is?

When you mentioned you can't reproduce it locally, not sure if that's related to CI environment. You  can create a dummy PR and keep using `/test xxx` to obtain a reproduce as well.

**Comment by howardjohn** [comment]
its very easy to reproduce with https://godoc.org/golang.org/x/tools/cmd/stress

**Comment by myidpt** [comment]
If this caused the flakiness, I think it should be easier to fix.

**Comment by williamaronli** [comment]
> ```
> 2020-06-15T16:32:55.099448Z	error	cache	JWT expiration checking error: token contains an invalid number of segments: 1, expected: 3. Consider as expired.
> ```
> 
> All the failures I see this error is logged. Which is pretty weird, if you look at the code, that comes from [`parseJwtClaims`](https://github.com/istio/istio/blob/2c81d37a8627ed2b880ee8dd961f7982b94ab1d2/security/pkg/util/jwtutil.go#L116).
> 
> ```go
> parts := strings.Split(token, ".")
> 	if len(parts) != 3 {
> 		return nil, fmt.Errorf("token contains an invalid number of segments: %d, expected: 3", len(parts))
> 	}
> ```
> 
> I can't think of why a JWT would have only one part after splitting with `.`
> 
> @williamaronli maybe you can add some instrmentation there? and if that error occurs, print out the token see what that is?
> 
> When you mentioned you can't reproduce it locally, not sure if that's related to CI environment. You can create a dummy PR and keep using `/test xxx` to obtain a reproduce as well.

@incfly this is for test TestTokenFetchFailureOne. but in our test is TestProxySDS. They are independently tests

**Comment by howardjohn** [comment]
Still flaky: https://prow.istio.io/view/gs/istio-prow/logs/unit-tests_istio_postsubmit/1326073046062075904
