### ISSUE TITLE
Change grpc_status from string to int32 in fault abort

### ISSUE THREAD

**Issue by ckcd** [istio/istio#24698]
**Describe the feature request**
In [virtual_service.proto](https://github.com/istio/api/blob/master/networking/v1alpha3/virtual_service.proto#L1816) we set `grpc_status` as `string` (and it's `hide_from_docs` for now). It's a little confused why it's `string` rather than `int32`. Maybe a `int32` in `0-16` range is more efficient.

And envoy support grpc_status in v3, see: [PR](https://github.com/envoyproxy/envoy/pull/10841) and [proto](https://github.com/envoyproxy/envoy/blob/master/api/envoy/extensions/filters/http/fault/v3/fault.proto#L46), and it set grpc_status as a `int32`.

BTW don't know whether it's some compatibility issues if we do this change.

**Describe alternatives you've considered**

1. Change `grpc_status` from string to int32 in fault abort protos.
2. Implement this feature after we move to envoy v3.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by ckcd** [comment]
@howardjohn @rshriram please take a look, thanks~

**Comment by howardjohn** [comment]
Does seem weird given https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/fault/v3/fault.proto#extensions-filters-http-fault-v3-faultabort is an int

**Comment by ckcd** [comment]
> Does seem weird given https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/fault/v3/fault.proto#extensions-filters-http-fault-v3-faultabort is an int

(: yes and so we need to do a transform from `string` to `uint32`.

BTW,  does our upgrade of envoy v2 -> v3 completed? if yes can I achieve this grpc_status in faultInjection?

**Comment by howardjohn** [comment]
Yes Istio 1.7 will use XDS v3

**Comment by ckcd** [comment]
actually I find that golang also use `int` for grpc status code: https://godoc.org/google.golang.org/grpc/codes#Code

@howardjohn so can we change to `int` rather than `string` ?

**Comment by ckcd** [comment]
for now the http abort:

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
...
spec:
  hosts:
  - ratings
  http:
  - fault:
      abort:
        httpStatus: 500
        percentage:
          value: 100
```

and for grpc, we should use int32 too:
```
  - fault:
      abort:
        grpcStatus: 4
```

if uses string, it looks a little confused and it's hard to limit a format.

```
  - fault:
      abort:
        grpcStatus: DeadlineExceeded ( or deadline_exceeded ? ) 
```

cc @howardjohn
