### ISSUE TITLE
Can kubernetes 1.12.4 install istio 1.5.4

### ISSUE THREAD

**Issue by jinnery** [istio/istio#24695]
my kubernets version is 1.12.4 .   So Can kubernetes 1.12.4 install istio 1.5.4?

**Comment by howardjohn** [comment]
No, see https://istio.io/v1.5/docs/setup/platform-setup/

**Comment by shamsher31** [comment]
You can also run [`precheck`](https://istio.io/latest/docs/reference/commands/istioctl/#istioctl-experimental-precheck) to see if your cluster is compatible with specific Istio version.
```
$ istioctl experimental precheck
```

**Comment by jinnery** [comment]
> 您还可以运行[`precheck`](https://istio.io/latest/docs/reference/commands/istioctl/#istioctl-experimental-precheck)以查看您的群集是否与特定的Istio版本兼容。
> 
> ```
> $ istioctl experimental precheck
> ```

thank you @shamsher31 .  "istioctl experimental precheck" command just chek yaml file,It's not an check kubernetes cluster

**Comment by jinnery** [comment]
> 不，请参阅https://istio.io/v1.5/docs/setup/platform-setup/

thank you @howardjohn 。I read the manual, but I don't want to upgrade kubernets cluster.  I'am install istio1.5.4 at kubernetes 1.12.4.  I will continue to test

**Comment by aroundthecode** [comment]
Hi there, 
I've more or less the same problem, I'm on K8 1.12.6 and istio 1.0.5 but i'm unable to figure out most recent working version.

I've tried 1.6 but istiod told me minimum version is 1.13

It would be really useful a compatibility matrix k8-istio versions in docs without having to download and try every version setup (supposing older version would run such check)

**Comment by howardjohn** [comment]
See https://istio.io/v1.5/docs/setup/platform-setup/ and you can replace the version with older versions as well. We are considering adding a table you suggested but the pr isn't approved

**Comment by aroundthecode** [comment]
by the way, I ended up using prechek against all versions: **the oldest one supporting kubernetes 1.12.x is Istio 1.2.x**

All versions 1.3+ state they need at least kubernetes 1.13 to work properly (I suppose it's related to CRD management).

Hope this may come in handy waiting for a real compatibility matrix (by the way the statement "tested with" and "working with" are not the same :) )
