### ISSUE TITLE
Failed to download 1.6.2

### ISSUE THREAD

**Issue by yaakov-berkovitch** [istio/istio#24700]
**Bug description**
Use the standard procedure to install istio as described here (https://istio.io/latest/docs/setup/getting-started/#download), and it stuck in the downloading process.

```
curl -L https://istio.io/downloadIstio | sh -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   107  100   107    0     0     90      0  0:00:01  0:00:01 --:--:--    90
100  3896  100  3896    0     0   2264      0  0:00:01  0:00:01 --:--:-- 3804k
Downloading istio-1.6.2 from https://github.com/istio/istio/releases/download/1.6.2/istio-1.6.2-linux.tar.gz ...Failed.

Trying with TARGET_ARCH. Downloading istio-1.6.2 from https://github.com/istio/istio/releases/download/1.6.2/istio-1.6.2-linux-amd64.tar.gz ...

Unable to download Istio 1.6.2 at this moment!
Please verify the version you are trying to download.

```
[ ] Configuration Infrastructure
[ ] Docs
[X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Installer to be downloaded.

**Steps to reproduce the bug**

curl -L https://istio.io/downloadIstio | sh -

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

1.6.2

**How was Istio installed?**

curl -L https://istio.io/downloadIstio | sh -

**Environment where bug was observed (cloud vendor, OS, etc)**

Centos 7.8

**Comment by esnible** [comment]
Works for me (OSX).

**Comment by yaakov-berkovitch** [comment]
this morning the issue disappeared, and it works for me too...
