### ISSUE TITLE
 "unsharded" view of XDS

### ISSUE THREAD

**Issue by esnible** [istio/istio#24703]
For Istio 1.7, Central Istiod will be a key feature.

The _istioctl_ commands documented in https://github.com/istio/istio/issues/23978 , `proxy-status`, `version`, `wait`, and `describe` currently contact all of the Istiod pods.  This is not possible without Istiod running in a cluster the user has admin access to.

@costinm suggested using ClusterLoadAssignment to get all of the XDS endpoints.  This works (see discussion at https://github.com/istio/istio/issues/24639 ) but unless there is a flat network it will not be possible to contact the endpoints returned by Cluster Load Assignment.

This work item tracks the implementation of a way that the `istio.io/connections`, `/nacks`, and other XDS Event typeURLs can be fetched for the entire mesh via *any* XDS endpoint.

cc @costinm , @howardjohn

**Comment by costinm** [comment]
https://github.com/istio/istio/pull/26573
