### ISSUE TITLE
istioctl analyze error on overlapping matches

### ISSUE THREAD

**Issue by ceastman-ibm** [istio/istio#24707]
**Describe the feature request**
Have "istioctl analyze" error on overlapping matches in virtual services or matches that would never happen due to the ordering of entries in the virtual service yaml

**Describe alternatives you've considered**

[X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**
for instance in this virtual service yaml: the path /apis would never get traffic

- match:
    - uri:
        prefix: /api
  route:
    - destination:
        host: api_microservice
        port:
          number: 80
- match:
    - uri:
        prefix: /apis
  route:
    - destination:
        host: apis_microservice
        port:
          number: 80

**Comment by howardjohn** [comment]
Very similar to MatchesAnalyzer, although MatchesAnalyzer is not this sophisticated (yet?)

**Comment by carolynhu** [comment]
Currently we only support exact match duplication errors out like: 
```istioctl analyze
Info [IST0131] (VirtualService bookinfo.default) VirtualService rule #1 match #1 is not used (duplicates a match in rule #0).
Info [IST0131] (VirtualService bookinfo.default) VirtualService rule #1 match #2 is not used (duplicates a match in rule #0).
Info [IST0131] (VirtualService bookinfo.default) VirtualService rule #1 match #3 is not used (duplicates a match in rule #0).
Info [IST0131] (VirtualService bookinfo.default) VirtualService rule #1 match #4 is not used (duplicates a match in rule #0).
Error: Analyzers found issues when analyzing namespace: default.
See https://istio.io/v1.8/docs/reference/config/analysis for more information about causes and resolutions.```

**Comment by zhlsunshine** [comment]
Hi @howardjohn & @esnible ,  analyzer of `RegexAnalyzer` under `virtualservice` has handled such `match` properties, including uri section. So I will enhance this analyzer to achieve detection on overlapping matches error.
I am working on this issue.

**Comment by esnible** [comment]
@zhlsunshine The problem is caused by https://github.com/istio/istio/blob/f21e2c94a2e663f5a3fdec8d8fd8cd0babc14915/pkg/config/validation/validation.go#L1964

I wrote that code.  It compares matches by comparing their JSON serialization for exact equality.  This catches empty matches and simple matches but misses detecting when two matches are similar.  To improve the matching write `analyzeUnreachableHTTPRules()` and perhaps the other two, to see if any `match` is a already handled by a previous match.

It is not easy code to write, which is why it was never implemented.

**Comment by zhlsunshine** [comment]
@esnible Thank you so much for your information! I will check it and focus on it!
