### ISSUE TITLE
XDS Event ack, nack or nacks

### ISSUE THREAD

**Issue by esnible** [istio/istio#24705]
This issue is to track the XDS Event `istio.io/nack` or `nacks`.

The document is at https://docs.google.com/document/d/1X7DmkP10x4nEcTGpikxmvLbBTTK59B0WL3liQzVy8Ms/edit 

The `istio.io/nacks` type was added by https://github.com/istio/istio/pull/23833 but I haven't been able to get a working query out of it.  Maybe I am doing something wrong?

Will there be a list of the istio.io/* typeURIs that will be supported in 1.7?  I found some places the URI was /nack and other places /nacks.  I also see an event istio.io/disconnect.

**Comment by costinm** [comment]
The intent is to allow new typeURL to be introduced - and put the
infrastructure in place for different types of events (and status).

The specifics for each event type will need to be decided separately - and
I expect UX to have most interest in how nack and status are structured.

Pretty much like envoy operates - new types are added based on use cases.

I think Mitch mentioned envoy has a status proto now, it may be a starting
point.

A second topic is the feedback on using k8s events - it is relatively easy
to push the events there as well, just please make sure the code is in the
same place. We may also support cncf events natively - xds is just one
transport, the design is about using messaging/pubsub for event
distribution with xds as default/first protocol, not exclusive xds.

**Comment by esnible** [comment]
@therealmitchconnors and I propose solving this with Envoy Client Status Discovery Request as suggested at https://github.com/istio/istio/issues/23538#issuecomment-647524868
