### ISSUE TITLE
Trying to make sense of Istio service mesh

### ISSUE THREAD

**Issue by nitinkapur** [istio/istio#24711]
**Bug description**

I am confused with some of the mesh connections in Kiali. For example if you look at the picture below 

![image](https://user-images.githubusercontent.com/10778343/84800072-3aec2d80-afcb-11ea-8ef8-446dc62b9471.png)

A is my Ingress Gateway, C is the virtual service which points to E that is the Pod for the virtual service. I do not have any route defined that virtual service C is pointing to  pod D.

But I don't know why that connection shows up. I tried deleting that connection in Prometheus there is just one entry there and it goes away for a second but then again comes back. This is a fresh deployment and no one is using these services right now. So I don't know why virtual service C keep pointing to pod D. There should be no connections between them. I might have had an old entry somewhere when I was experimenting but that should have been deleted by clearing prometheus data right?

I also see the Ingress Gateway directly calling two pods which is again strange the routes are defined between gateway A  the virtual service B but not the pod C.

In the picture below. The route from ingress gateway A to virtual service B to pod C is defined. But why do I also see a connection between Ingress Gateway A and pod C directly??

See the Grey line above the red line to show you that connection.

![image](https://user-images.githubusercontent.com/10778343/84800133-548d7500-afcb-11ea-8ed5-120c2c41b531.png)

**Comment by esnible** [comment]
Perhaps ask this question in https://github.com/kiali/kiali/issues .  This repo does not cover Kiali visualizations.

**Comment by howardjohn** [comment]
closing per https://github.com/istio/istio/issues/24711#issuecomment-668728070
