### ISSUE TITLE
TestStreamSecretsForWorkloadSds test flake

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#24714]
https://prow.istio.io/view/gcs/istio-prow/logs/unit-tests_istio_postsubmit/2703

@williamaronli @JimmyCYJ

**Comment by JimmyCYJ** [comment]
@williamaronli could you take a look?

**Comment by williamaronli** [comment]
Thanks I will take a look. Thanks

**Comment by williamaronli** [comment]
From the error and info log
these codes has been touched:
https://github.com/istio/istio/blob/master/security/pkg/nodeagent/sds/sdsservice.go#L695
and the status is  codes.Canceled or err == io.EOF, which leads to an error:
https://github.com/istio/istio/blob/master/security/pkg/nodeagent/sds/sdsservice.go#L241

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/25662/unit-tests_istio/17113

**Comment by howardjohn** [comment]
This is still failnig: https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/29281/unit-tests_istio/1333543649044074496

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gcs/istio-prow/pr-logs/directory/unit-tests_istio/1333510483059150848

**Comment by williamaronli** [comment]
can I just skipped it for future research?

**Comment by howardjohn** [comment]
test is removed
