### ISSUE TITLE
Setting status.sidecar.istio.io/port to 0 causes istio-init container to fail (1.5.4)

### ISSUE THREAD

**Issue by brantlk** [istio/istio#24722]
**Bug description**

I'm working on switching from istio 1.4 to 1.5 and found some pods failed to start and went into Init:CrashLoopBackOff. The pods that failed all set the `status.sidecar.istio.io/port: "0"` annotation.

According to the documentation https://istio.io/latest/docs/reference/config/annotations/ this is a valid value: "If zero, the sidecar will not provide status."

The reason the pods failed to start is because the istio-init container was passed an invalid argument. The -d option was passed `15090,` (the empty string after the , was used in the iptables and so generated a bad iptables command).

In istio 1.4 the command has "" for the argument to -d.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Pods annotated with `status.sidecar.istio.io/port: "0"` should start and the sidecar will not provide status.

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

istio 1.5.4 on kubernetes 1.18.2.

**How was Istio installed?**

The istio helm chart that deploys the operator.

**Environment where bug was observed (cloud vendor, OS, etc)**

Internal.

**Comment by brantlk** [comment]
I think the reason that we have this annotation on the pods is to work around a previous issue where the istio-proxy sidecar wouldn't start when the pod didn't have an associated Service. From testing, looks like that issue is fixed and we can work around this problem by not adding the annotation.

**Comment by stevenctl** [comment]
Replicated this on 1.6.3 using bookinfo, modified details-v1 deployment to use `status.sidecar.istio.io/port: "0"`

<details>
<summary>istio-init args</summary>

<pre>
  initContainers:
  - args:
    - istio-iptables
    - -p
    - "15001"
    - -z
    - "15006"
    - -u
    - "1337"
    - -m
    - REDIRECT
    - -i
    - '*'
    - -x
    - ""
    - -b
    - '*'
    - -d
    <b>- 15090,15021,</b>
</pre>

</details>

<details>

<summary>istio-init logs</summary>

```
Environment:
------------
ENVOY_PORT=
INBOUND_CAPTURE_PORT=
ISTIO_INBOUND_INTERCEPTION_MODE=
ISTIO_INBOUND_TPROXY_MARK=
ISTIO_INBOUND_TPROXY_ROUTE_TABLE=
ISTIO_INBOUND_PORTS=
ISTIO_LOCAL_EXCLUDE_PORTS=
ISTIO_SERVICE_CIDR=
ISTIO_SERVICE_EXCLUDE_CIDR=

Variables:
----------
PROXY_PORT=15001
PROXY_INBOUND_CAPTURE_PORT=15006
PROXY_UID=1337
PROXY_GID=1337
INBOUND_INTERCEPTION_MODE=REDIRECT
INBOUND_TPROXY_MARK=1337
INBOUND_TPROXY_ROUTE_TABLE=133
INBOUND_PORTS_INCLUDE=*
INBOUND_PORTS_EXCLUDE=15090,15021,
OUTBOUND_IP_RANGES_INCLUDE=*
OUTBOUND_IP_RANGES_EXCLUDE=
OUTBOUND_PORTS_EXCLUDE=
KUBEVIRT_INTERFACES=
ENABLE_INBOUND_IPV6=false

Writing following contents to rules file:  /tmp/iptables-rules-1593103450491842833.txt091730875
* nat
-N ISTIO_REDIRECT
-N ISTIO_IN_REDIRECT
-N ISTIO_INBOUND
-N ISTIO_OUTPUT
-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001
-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006
-A PREROUTING -p tcp -j ISTIO_INBOUND
-A ISTIO_INBOUND -p tcp --dport 22 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15090 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15021 -j RETURN
-A ISTIO_INBOUND -p tcp --dport  -j RETURN
-A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT
-A OUTPUT -p tcp -j ISTIO_OUTPUT
-A ISTIO_OUTPUT -o lo -s 127.0.0.6/32 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --gid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
-A ISTIO_OUTPUT -j ISTIO_REDIRECT
COMMIT

iptables-restore --noflush /tmp/iptables-rules-1593103450491842833.txt091730875
iptables-restore v1.6.1: invalid port/service `-j' specified
Error occurred at line: 12
Try `iptables-restore -h' or 'iptables-restore --help' for more information.
iptables-save
# Generated by iptables-save v1.6.1 on Thu Jun 25 16:44:10 2020
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
COMMIT
# Completed on Thu Jun 25 16:44:10 2020
panic: exit status 2

goroutine 1 [running]:
istio.io/istio/tools/istio-iptables/pkg/dependencies.(*RealDependencies).RunOrFail(0x3baee68, 0x22cef13, 0x10, 0xc00000da00, 0x2, 0x2)
	istio.io/istio/tools/istio-iptables/pkg/dependencies/implementation.go:44 +0x96
istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).executeIptablesRestoreCommand(0xc00066fd68, 0x22c4c01, 0x0, 0x0)
	istio.io/istio/tools/istio-iptables/pkg/cmd/run.go:482 +0x387
istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).executeCommands(0xc00066fd68)
	istio.io/istio/tools/istio-iptables/pkg/cmd/run.go:489 +0x45
istio.io/istio/tools/istio-iptables/pkg/cmd.(*IptablesConfigurator).run(0xc00066fd68)
	istio.io/istio/tools/istio-iptables/pkg/cmd/run.go:436 +0x25ef
istio.io/istio/tools/istio-iptables/pkg/cmd.glob..func1(0x3b5c460, 0xc0000ff900, 0x0, 0x10)
	istio.io/istio/tools/istio-iptables/pkg/cmd/root.go:64 +0x148
github.com/spf13/cobra.(*Command).execute(0x3b5c460, 0xc0000ff800, 0x10, 0x10, 0x3b5c460, 0xc0000ff800)
	github.com/spf13/cobra@v1.0.0/command.go:846 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x3b5c700, 0x0, 0x0, 0x0)
	github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	istio.io/istio/pilot/cmd/pilot-agent/main.go:504 +0x2d
```

</details>

**Comment by Zeka13** [comment]
bug still exists for version 1.10.0

**Comment by xiazemin** [comment]
Normal   Started    28m (x5 over 30m)    kubelet            Started container istio-init
  Warning  BackOff    15s (x140 over 30m)  kubelet            Back-off restarting failed container
