### ISSUE TITLE
How to redirect http://domain.com to http://www.domain.com ?

### ISSUE THREAD

**Issue by hillbun** [istio/istio#24726]
How to redirect http://domain.com to http://www.domain.com ?

**Comment by helight** [comment]
https://istio.io/latest/docs/reference/config/networking/gateway/

**Comment by hillbun** [comment]
@helight 

it should be:
redirect http://domain.com to http://www.domain.com

**Comment by helight** [comment]
they are no difference。

**Comment by helight** [comment]
> @helight
> 
> it should be:
> redirect http://domain.com to http://www.domain.com

they are no difference。

**Comment by hillbun** [comment]
@helight 

sorry, I can not find it.
which part in that document?
please advice.

**Comment by esnible** [comment]
Use the Authority field of HTTPRedirect.  https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPRedirect

**Comment by howardjohn** [comment]
This is supported by https://istio.io/latest/docs/reference/config/networking/gateway/#ServerTLSSettings httpsRedirect
