### ISSUE TITLE
Discussion about Istio enablement on Arm64 platform

### ISSUE THREAD

**Issue by Jingzhao123** [istio/istio#24732]
**Discussion about Istio enablement on Arm64 platform**

In this request, I want to discuss about how to enable Istio on Arm64 platform. I know, so far, there are some difficulties on Istio enablement on Arm64. Could we discuss it for further development on Arm64? 

**Potential issues for enablement**
1. Dependent repositories are not supported arm64
Although most of dependent repositories have support arm64 platform, there are still some repo do not support. For those issues, could we temporarily walk around and use the private repository to replace until official supported.
2. How to build CI environments?
As far as i know, the Prow in Istio is running on Google cloud. It does not support arm64 environment. But the similar issue about it has been raised in [Kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/16588). After this issue resolved, i think the istio could use the similar architect for building Arm CI environments. 
2. How to verify code
In my opinion, we could firstly enable Istio  native build on Arm64. In this phase, it only verifies code on x86 platform. In next phases, we could build Istio Arm64 CI environments. Finally, build all the feature of Istio on Arm CI environments:
Phase1: Enable Istio native build on arm64 platform.
Phase2: Build Istio Arm64 CI environments.
Phase3: Enable all features on Arm64

**What is your opinion about it?**

**Comment by Jingzhao123** [comment]
@hzxuzhonghu

**Comment by hzxuzhonghu** [comment]
@istio/wg-environments-maintainers

**Comment by howardjohn** [comment]
We have a lot of information about this tracked in https://github.com/istio/istio/issues/21094, let's move the discussion there? Thanks!
