### ISSUE TITLE
debian pkgs not uploaded to `istio-artifacts` on gcs in postsubmit

### ISSUE THREAD

**Issue by chxchx** [istio/istio#2473]
Say the istio/istio master is at `1c498e7712badd8f3e885fbe3b77e4d2d3621843` (01/08/2018).
Visiting https://storage.googleapis.com/istio-artifacts/auth/1c498e7712badd8f3e885fbe3b77e4d2d3621843/artifacts/debs gives you "key does not exist" error instead of downloading the deb file. This is also true for **pilot** and **proxy** (although proxy uses its own sha as it is not part of istio/istio). 

These debs are required to install istio on the VM that expends the service mesh. This problem was uncovered when I was trying to activate tests on the VM expansion feature (https://github.com/istio/istio/pull/2444). Maybe the debs upload steps were missed during the migration off bazel, as I don't see upload commands in either 
https://github.com/istio/istio/blob/master/prow/istio-postsubmit.sh
or 
 https://github.com/istio/istio/blob/master/bin/push

**Comment by ldemailly** [comment]
is this still and issue ? if so can you solve it ?
(or do you have specific questions / need help with ? maybe @mattdelco can help you too)

**Comment by mattdelco** [comment]
I think it's still an issue (the push of debs by bin/push [and now "make push" was mostly deleted during the shift to a single monolithic dep) but it should be addressed as part of https://github.com/istio/istio/pull/2444 .

**Comment by costinm** [comment]
Is it still a problem ? Can you update and close ?

**Comment by chxchx** [comment]
https://github.com/istio/istio/pull/2444 should have fixed it. Closing it now.
