### ISSUE TITLE
Sidecar API selector matching

### ISSUE THREAD

**Issue by costinm** [istio/istio#24741]
According to the spec:
"NOTE 1: Each namespace can have only one Sidecar configuration without any workloadSelector that specifies the default for all pods in that namespace. It is recommended to use the name default for the namespace-wide sidecar. The behavior of the system is undefined if more than one selector-less Sidecar configurations exist in a given namespace. The behavior of the system is undefined if two or more Sidecar configurations with a workloadSelector select the same workload instance."

If we have a deployment "app=foo", and a second deployment "app=foo,canary=true" - it is impossible to write Sidecar for both deployments. The first has a single label - so will have workload selector 'app=foo', matching both deployments. A more specific selector for second deployment will 
result in the second deployment having 'undefined behavior'.

I think 'most specific match' would be a better behavior - i.e. sort the matching list by the number of labels matched, and pick the largest. In case of conflict - we should apply the 'oldest wins' rule
we use in other places. 

As an alternative: we should allow Sidecar to be more specific and select a workload by name, using the deployment name explicitly, so a Sidecar with the name 'xyz' will be picked for the 
deployment 'xyz' if multiple labels are matching ( or we can use an explicit field in workloadSelector).  

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[*] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by costinm** [comment]
(reported by @mandarjog )

**Comment by howardjohn** [comment]
Interesting point... does k8s have any examples of singletons that are using workload selectors? I cannot think of any - probably because of this issue

**Comment by mandarjog** [comment]
I stumbled upon this while exploring how extensions attached to a sidecar resource can be canaried. I also think that most specific wins makes sense. That does leave the multiple inheritance problem open. And if we add "workload name" or similar as override specific condition then the user always has the ability to break ties.

I think this behaviour is needed to have a functioning forward reference API for extensions.
@kyessenov

**Comment by costinm** [comment]
The 'workload name' is also related to the 'stable identifiers in XDS'/better caching discussion we are having in separate context. 

If a workload shows up and we have a sidecar with an explicit 'workload name' - we can use that name as stable identifier and avoid the label matching - labels are not a great cache key. The workload might also be safer from unrelated workload changes. So at least users who want to 
be precise will have some benefits, while users who want full dynamic matching will get their way too.

**Comment by howardjohn** [comment]
btw, if you are experiencing this issue you can probably select on `pod-template-hash` assuming you have a Deployment.

**Comment by rshriram** [comment]
>I think 'most specific match' would be a better behavior - i.e. sort the matching list by the number of labels matched, and pick the largest. 

this is a fairly simple fix here https://github.com/istio/istio/blob/master/pilot/pkg/model/push_context.go#L678

**Comment by costinm** [comment]
The fix is not hard - but this is an API change, and I think we should bikeshed a bit, in particular around having 'exact' match by stable identifier :-)

**Comment by costinm** [comment]
AFAIK it's not an immediate problem - Mandar is trying to use the Sidecar for extension config (or just having fun with Sidecar), for future versions. I suspect if we use Sidecar to load a WASM or 
extension into a workload it's better to be as precise as possible...

**Comment by rshriram** [comment]
I am not sure of using workload names in apis.. But we can easily fix the impl bug (and backport) without any api change to achieve the behavior you suggested (the largest label match).

**Comment by hzxuzhonghu** [comment]
If we change the semantics, it will break the common sense that users learned from k8s label selector.
We could expand the `WorkloadSelector` instead of breaking the labels selector.

**Comment by howardjohn** [comment]
The semantics are already broken, in k8s there is no object that will apply only one matched object, it always merges (multiple service can select a pod) but for us we pick one randomly. The suggestion is to still pick 1, but do it in a deterministic manner

**Comment by mandarjog** [comment]
Not stale.

**Comment by hzxuzhonghu** [comment]
not resolved
