### ISSUE TITLE
K8s ingress with istio without sidecar

### ISSUE THREAD

**Issue by vbottu** [istio/istio#24750]
Is it possible to use k8s ingress with ingress gateway for an application without injecting sidecar into the applicationor the namespace where the ingress is created? I mean is it possible to just use istio ingress gateway just like any other ingress controller like nginx ingress controller?

I have gateway svc as loadbalancer and has a domain name and static ip attached to it from the metallb load balancer
Environment:
k8s version: 1.15.5
istio version : 1.4.0
on prem

**Comment by ryan4yin** [comment]
In order to save resources, we are using istio ingressgateway without sidecar in out development cluster for a while, it works well.

without sidecar, istio just act as a ingress gateway, no service mesh here.

we only enable istio-injection in our production environment.

**Comment by howardjohn** [comment]
Yes, this is supported. See https://istio.io/latest/docs/tasks/traffic-management/ingress/kubernetes-ingress/ for more info. Sidecar is only needed for service to service features, mtls, server side telemetry, auth, etc. But you can do basic Ingress without it

**Comment by rklhui** [comment]
@howardjohn I went ahead and try your suggestion to test out the use of istio with k8s ingress, for basic ingress it works fine, but if my service only accept a HTTPS connection, it seems that I have no way to configure the ingress this way. I have tried using the tls option of ingress, but the tls only terminated at the ingress, so the connection to the service is still HTTP. Would you have any idea how I might configure this just using istio and k8s ingress? Or i need to setup nginx and use nginx ingress controller afterall...

Any help is much appreciated. Thanks in advanced.

**Comment by howardjohn** [comment]
Connection to the upstream service is NOT part of the Ingress spec. You can use destination rule to configure this.

**Comment by rklhui** [comment]
My reason of wanting to use istio without the sidecar is the same as @ryan4yin, to save resource for some of my services. If I opt to use destination rule, then i would have to inject the sidecar back in, right? @howardjohn If I just want to connect to the backend service via k8s ingress via https with istio, can I set up as https://istio.io/latest/docs/tasks/traffic-management/ingress/kubernetes-ingress/ suggest, and let istio do the tls termination, and then deploy nginx ingress controller for the https connection from ingress to backend service? Do you think this would be an overkill?

**Comment by howardjohn** [comment]
No. You do not need a sidecar for Ingress, even with destinationrule. Also, if your only goal is to not use sidecars, you can still use Gateway/VirtualService, you don't _need_ Ingress

> Do you think this would be an overkill?

Yes

**Comment by rklhui** [comment]
@howardjohn Thanks for the tip, just to clarify when you say Ingress, you mean the k8s Ingress (https://kubernetes.io/docs/concepts/services-networking/ingress/) right?

So now my current setup is basically like this:
public network --> gateway (with tls SIMPLE for a wildcard domain) --> virtual service (for reverse proxy to specific backend service) + destinationRule (for make sure it connect to backend service via 443 with tls)

For the above setup, do i not need a sidecar?

I tried removing the sidecar injection before, but i faces some occasional `upstream connect error or disconnect/reset before headers.` error, that is why I thought the sidecar is a must.

**Comment by howardjohn** [comment]
Yes, no sidecar is required for that.

**Comment by NComandini** [comment]
@rklhui I'm facing a similar issue with the same architecture setup : Use the Istio Ingress Gateway to route request to pod that listen in https.
@howardjohn Have you some recommendation/requirement about the certificate configuration on the backend ? 
Have you solve you problem ? Could you show me the DestinationRule ?

**Comment by manojtr** [comment]
> In order to save resources, we are using istio ingressgateway without sidecar in out development cluster for a while, it works well.
> 
> without sidecar, istio just act as an ingress gateway, no service mesh here.
> 
> we only enable istio-injection in our production environment.

@ryan4yin What is the thinking behind you enabled sidecar in production instead of going without sidecar, same as in your development cluster?

**Comment by ryan4yin** [comment]
@manojtr just as I said before:

```
without sidecar, istio just act as an ingress gateway, no service mesh here.
```

sidecar is useful while you need service mesh.
for example, if service A need to call Service B:

```mermaid
graph LR
  Client --> LoadBalancer --> igw[Istio Gateway]
  subgraph Kubernetes
    igw --> s_a[Service A] --> s_b[Service B]
  end
```

with Service A's Sidecar, you can do a lot of L7 operations  on the traffic from A to B, such as traffic split:

```mermaid
graph LR
  Client --> LoadBalancer --> igw[Istio Gateway]
  subgraph Kubernetes
    igw --> s_a[Service A] -- 90%  --> s_b1[Service B v1]
    s_a[Service A]    -- 10% -->  s_b2[Service B v2]
  end
 
```

and others like http status_code/latency monitoring, fault injection, etc...

**Comment by yingwg** [comment]
Hi,
If I need to setup DestinationRule to enable least requests load balancing policy for the upstream service, without sidecar running on the pod, how does istio be able to track the number of active requests on each pod?
