### ISSUE TITLE
Isitoctl creates istio-system namespace without label "name: istio-system"

### ISSUE THREAD

**Issue by vitaliy-zinchenko** [istio/istio#24756]
**Bug description**
I am working on migration cluster deployment from Helm to istioctl.

When I install istio with istioctl it creates a istio-system namespace for me:
```
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    istio-operator-managed: Reconcile
    istio-injection: disabled
```
But the issue is that I expect this namespace to have a label "name: istio-system" but it doesn't have one. I need this label on order to setup NetworkPolicy.

How can I either specify additional labels to the namespace or disable istioctl to create istio-system namespace?

More details:

How it worked before migration, with Helm:
- create istio-system namespace, with "name: istio-system" label in place
- set up NetworkPolicy for istio-system namespace
- deploy istio with helm (it didn't create istio-system before)

How it works now, with istioctl:
- create istio-system namespace, with "name: istio-system" label in place
- set up NetworkPolicy for istio-system namespace
- deploy istio with istioctl, and in this case it updates the namespaces and removes label
- sometimes (probably because of race conditions), deploy fails as istio-ingressgateway-* can't start, because it can't connect to Pilot (see error below), because the NetworkPolicies are misconfigured as the namespace doesn't have label which NetworkPolicy expect to have

Error during connection to Pilot: (Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 0 successful, 0 rejected; lds updates: 0 successful, 0 rejected)

I tried to add label after istioctl run, but as I said above istioctl fails during execution. 

So, the questions:
 - How can I either specify additional labels to the namespace?
 - or disable istioctl to create istio-system namespace?
 - also, where is the code which creates this namespace, at least I want to try to patch it to prove my assumptions.

[ ] Configuration Infrastructure
[ ] Docs
[ X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
What version is this? At least in 1.6+ we will only create a namespace if one doesn't already exist so you can create the namespace then install istio

**Comment by vitaliy-zinchenko** [comment]
@howardjohn this is 1.5.4 version of Istio (client and server). That is good news that in 1.6+ it will create namespace if one is absent. 
What work around can you suggest for now, until we migrate to  1.6+?

**Comment by howardjohn** [comment]
I suppose you can add the label after you install?

**Comment by vitaliy-zinchenko** [comment]
I ended up with workaround until we upgrade to 1.6: (1) temporarily create network permissions for istio pods before installation; (2) install istio; (3) add label to istio-system; (4) remove temporary network permissions.
