### ISSUE TITLE
Add support for regex match in authorization policy

### ISSUE THREAD

**Issue by mcieplak** [istio/istio#24762]
**Describe the feature request**
It looks like the current codebase does not support using the `HeaderMatcher_RegexMatch` in the block used to parse the http path here:
https://github.com/istio/istio/blob/master/pilot/pkg/security/authz/matcher/header.go#L24-L56.

Could we add support for the full regex here as well? The virtual service supports using regex in a couple of different fields, this could be potentially made consistent across both resources.

**Describe alternatives you've considered**
The alternative without supporting regex is defining more explicit policies which can quickly grow in size.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by myidpt** [comment]
I believe we have discussed this before. @yangminzhu may advice.

**Comment by joberdick-rcd** [comment]
@myidpt  @yangminzhu do we have a decision on supporting more flexible matches for authorization policies? I also ran into use cases where we can't apply properly. Example Path: /something/*/something
