### ISSUE TITLE
Enabling HorizontalPodAutoscaler for Istiocoredns for Multicluster setup

### ISSUE THREAD

**Issue by zufardhiyaulhaq** [istio/istio#24769]
**Describe the feature request**
Enable user to setup HorizontalPodAutoscaler for istiocoredns component when using multicluster that need istiocoredns to resolv .global FQDN.

**Describe alternatives you've considered**
The workaround for this is to create external HPA for istiocoredns.

[X] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by shamsher31** [comment]
@zufardhiyaulhaq Does this https://github.com/istio/istio/pull/25201 solve the issue?

**Comment by zufardhiyaulhaq** [comment]
@shamsher31 need to take a look for that.

**Comment by shamsher31** [comment]
I think this is closed by https://github.com/istio/istio/pull/25201, feel free to re-open if it doesn't fix the issue.
