### ISSUE TITLE
prometheus open /etc/istio-certs/root-cert.pem: no such file or directory"

### ISSUE THREAD

**Issue by yangvipguang** [istio/istio#24768]
**Bug description**
 I have installed the istio of  default profile  with kiali enabled 。But the log from prometheus pod occurs some issues like  below 
![image](https://user-images.githubusercontent.com/11416887/84999428-b5f84400-b183-11ea-9d76-d9130096b2b6.png)
 
But you can see， the root-cert.pem file exists in the directory  /etc/istio-certs。 I have instaled two times，the resule is same。

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
Istio:1.6.2
![image](https://user-images.githubusercontent.com/11416887/84999979-623a2a80-b184-11ea-82bf-a58967ddb010.png)

**How was Istio installed?**
1 、istio profile dump  > istio-default.yaml
2、edit the istio-default.yaml file with  kiali enabled
3、istio install -f  istio-default.yaml --set values.global.jwtPolicy=first-party-jwt
**Environment where bug was observed (cloud vendor, OS, etc)**
Alicloud

**Comment by maciejqantas** [comment]
@shahidhs-ibm have you solved the issue? can you share how?

**Comment by yangvipguang** [comment]
@maciejqantas   No  I have gave up .

**Comment by shahidhs-ibm** [comment]
> 
> 
> @shahidhs-ibm have you solved the issue? can you share how?

I deployed using following command which worked for me:
`istioctl manifest apply --set values.global.jwtPolicy=first-party-jwt --set profile=demo`

You could try adding `--set meshConfig.enablePrometheusMerge=true` option in above command if it didn't worked.

**Comment by maciejqantas** [comment]
@shahidhs-ibm 
thanks for sharing! 

It happened to me while installing Prometheus from scratch, but didn't when I was upgrading Istio from a previous version. I've yet to figure out why that was the case.
