### ISSUE TITLE
the pilot reporter.distributionEventQueue default length wrong as "100_000"

### ISSUE THREAD

**Issue by houwengang** [istio/istio#24776]
**Bug description**
the pilot reporter.distributionEventQueue default length is "100_000"，but it should be a integer number. 
wrong code:
r.distributionEventQueue = make(chan distributionEvent, **100_000**)

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
AS mentioned in the PR this is identical to 100000
