### ISSUE TITLE
Pod to Pod communication not working for HTTPS pod in isito

### ISSUE THREAD

**Issue by dhineshbabuelango** [istio/istio#24773]
I have a pod in istio enabled namespace, the application container runs only on port 443, istio mTLS is enabled globally. When I try to reach that pod(pod A) from other pod(pod B)using the service name I m getting below error

curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to app-container:443

But If I login to the istio proxy of Pod B, i am able to reach the PodA application container.
Even If I login to the istio-proxy of PodA, I am able to reach PodA application container.

The problem is happening only if I try to establish from app container of PodB, I am getting the below error but the connections are reaching the istio proxy of PodA.
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to app-container:443.

connections in the istio-proxy log:
[2020-06-18T11:46:33.005Z] "- - -" 0 - "-" "-" 233 1242 35 - "-" "-" "-" "-" "100.66.39.113:443" InboundPassthroughClusterIpv4 127.0.0.6:56493 100.66.39.113:443 100.66.67.121:34088 outbound_.443_._.app-container.apps.svc.cluster.local -

When I add a destinationrule to disable the TLS, its working
But I have other https applications and they all are working fine.

**Comment by howardjohn** [comment]
Please get a config dump from pod a and pod b and the service, DR, peerauthentication in your cluster: https://github.com/istio/istio/wiki/Troubleshooting-Istio

**Comment by howardjohn** [comment]
We don't have enough information to make any progress on this issue
