### ISSUE TITLE
Fix e2e results: TestRateLimit

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio#2478]
With the recent changes, the e2e test for Mixer Rate Limits has broken. This needs to be resolved ASAP.

- Build grid: https://k8s-testgrid.appspot.com/istio#e2e-suite-rbac-no_auth
- Example run: https://k8s-gubernator.appspot.com/build/istio-prow/e2e-suite-rbac-no_auth/338

cc: @jasminejaksic @hklai

**Comment by jasminejaksic** [comment]
Mandar, are you working on this?
What's causing the issue? And do we have an approx ETA for the fix?

**Comment by mandarjog** [comment]
This is fixed now.
