### ISSUE TITLE
Istio K8s ingress is not following redirects

### ISSUE THREAD

**Issue by darkstarmv** [istio/istio#24785]
**Bug description**
if `path: /` is defined in ingress, istio K8s ingress is not following redirects
 

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Istio K8s ingress should follow redirects
 
**Steps to reproduce the bug**
1. Deploy Istio K8s ingress
2. Deploy Prometheus and configure ingress resource:
```
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  creationTimestamp: "2020-06-18T16:54:39Z"
  generation: 1
  labels:
    app: prometheus-operator-prometheus
    chart: prometheus-operator-6.18.1
    heritage: Tiller
    release: prom-system
  name: prom-system-prometheus-ope-prometheus
  namespace: kube-system
  resourceVersion: "227226952"
  selfLink: /apis/extensions/v1beta1/namespaces/kube-system/ingresses/prom-system-prometheus-ope-prometheus
  uid: d1b3d4cf-4621-4bb7-9fab-5bfddb567ef6
spec:
  rules:
  - host: prometheus.mydomain.com
    http:
      paths:
      - backend:
          serviceName: prom-system-prometheus-ope-prometheus
          servicePort: 9090
        path: /
  tls:
  - secretName: default-tls
status:
  loadBalancer: {}
```

3. open  prometheus in the browser and observe error:

```
No webpage was found for the web address: https://prometheus.mydomain.com/graph
HTTP ERROR 404
```

curl returns:

```
curl -vv http://prometheus.mydomain.com
* Rebuilt URL to: http://prometheus.mydomain.com/
*   Trying XX.XX.XX.XX...
* TCP_NODELAY set
* Connected to prometheus.mydomain.com (XX.XX.XX.XX) port 80 (#0)
> GET / HTTP/1.1
> Host: prometheus.mydomain.com
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 302 Found
< content-type: text/html; charset=utf-8
< location: /graph
< date: Thu, 18 Jun 2020 17:03:16 GMT
< content-length: 29
< x-envoy-upstream-service-time: 0
< server: istio-envoy
< X-Content-Type-Options: nosniff
<
<a href="/graph">Found</a>.

* Connection #0 to host prometheus.mydomain.com left intact
```

4. delete `path: /' from k8s ingress object and now everything works in the browser and curl returns same response as above
 
**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
istioctl version --remote
client version: 1.6.2
control plane version: 1.7-alpha.06ea60ac3da305b43480cae75f215724adc3e820
data plane version: 1.7-alpha.06ea60ac3da305b43480cae75f215724adc3e820 (1 proxies)
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"d94a81c724ea8e1ccc9002d89b7fe81d58f89ede", GitTreeState:"clean", BuildDate:"2020-03-12T21:08:59Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"d94a81c724ea8e1ccc9002d89b7fe81d58f89ede", GitTreeState:"clean", BuildDate:"2020-03-12T21:00:06Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

```
helm version
version.BuildInfo{Version:"v3.2.3", GitCommit:"8f832046e258e2cb800894579b1b3b50c2d83492", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

**How was Istio installed?**
Istio was installed with `helm3`
**Environment where bug was observed (cloud vendor, OS, etc)**
- BYO k8s on baremetal and GCE

**Comment by howardjohn** [comment]
The path is an exact match. See https://istio.io/latest/docs/tasks/traffic-management/ingress/kubernetes-ingress/#specifying-path-type for more info

**Comment by darkstarmv** [comment]
Thank you @howardjohn, i missed that update.  
I have a few more questions:

1. Is there a way to configure Istio routing in a way that mimics other k8s ingress controllers? I would like to avoid asking all application teams to add `/*` when I migrate to Istio K8s ingress.
2. How can I setup default backend with the custom page for `404` response code when there is no defined ingress?
3. How to configure default TLS configuration, so Istio Controller terminates SSL similar to [nginx controller](https://kubernetes.github.io/ingress-nginx/examples/tls-termination/)

**Comment by howardjohn** [comment]
1) you can configure match type with k8s 1.18+
2) use Gateway/VirtualService
3) same as 2

Our Ingress implementation is intentionally far less customizable than others like nginx as we have our own apis

**Comment by darkstarmv** [comment]
Thank you @howardjohn , any examples for 2 and 3?

**Comment by howardjohn** [comment]
There is no default TLS configuration or default backend supported, you will need to use Istio gateway. See https://istio.io/docs/tasks/traffic-management/ingress/
