### ISSUE TITLE
Security Test is Flaky

### ISSUE THREAD

**Issue by GregHanson** [istio/istio#24789]
**Bug description**

https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/24779/integ-security-k8s-tests_istio/14503

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ X ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by nschhina** [comment]
Duplicate of: https://github.com/istio/istio/issues/24028
closing this issue
