### ISSUE TITLE
Istio Operator to follow Kubernetes Operator pattern

### ISSUE THREAD

**Issue by sb1975** [istio/istio#24794]
**Describe the feature request**
Just as a Kubernetes controller (operator) watches for CR creation requests (assuming the CRD is already added to the Kubernetes database) and is able to seamlessly create multiple CR in different namespaces.

Istio Operator (Controller) should also provide ability to create multiple Istio Control plane seamlessly in any namespace.

**Describe alternatives you've considered**

[ ] Configuration Infrastructure
[x ] Docs
[x ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[x ] Test and Release
[x ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by myidpt** [comment]
@costinm

**Comment by sb1975** [comment]
The ability to create iop cr and each cr creates a seperate istio control plane in its own ns, something like the below does not work.
https://github.com/istio/istio/issues/25208

**Comment by JimmyCYJ** [comment]
@costinm could you please take a look? Thanks!
