### ISSUE TITLE
Monitor and Manage Event-Driven Messaging

### ISSUE THREAD

**Issue by majbilou** [istio/istio#24805]
Hi,

Istio Excel in managing and Monitoring Microservices using direct messaging (a.k.a (a)synchronous service-to-service communication)

Is there any plan to support Event-Driven Messaging in the future when a Messaging Broker is introduced in the architecture (Kafka, Pub/Sub...) as a medium of communication between services

Like monitor ans control messages sent to the broker, messages consumed from the Broker, ...

Thank you in advance

**Comment by howardjohn** [comment]
What features are you interested in specifically? You can use any TCP based services, including Kafka with Istio. See https://banzaicloud.com/blog/kafka-on-istio-benefits/ for some info about this

**Comment by majbilou** [comment]
Thank you @howardjohn, I will check that out
