### ISSUE TITLE
transport: loopyWriter.run returning. connection error: desc = "transport is closing"

### ISSUE THREAD

**Issue by yangvipguang** [istio/istio#24800]
**Bug description**
Istiod  logs  ：kubectl logs -f istiod-7f74fc9945-sk7d8  -n istio-system
![image](https://user-images.githubusercontent.com/11416887/85087498-4a0fed00-b210-11ea-86fb-dbb59d8d0d09.png)

Is the error  normal ？

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
![image](https://user-images.githubusercontent.com/11416887/85087595-79bef500-b210-11ea-9fc7-5432d21a858a.png)

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**
Alicloud K8s

**Comment by AceHack** [comment]
I'm having the same issue with latest istio 1.6.x installed with cli on AWS

**Comment by yangvipguang** [comment]
@AceHack   
This does not seem to be an error, it is just a printing problem. This place should be more friendly.

**Comment by fgather** [comment]
I see this issue on a kubespray cluster as well and it seems to happen sporadically if the target of the grpc calls is redeployed. However, in some cases it is not possible to recover from that and the pods initiating the grpc calls are never again able to communicate to the grpc service until restarted.

**Comment by howardjohn** [comment]
This is not a bug, the connections will close occasionally, see https://github.com/istio/istio/wiki/Troubleshooting-Istio#common-issues. We have also disabled these logs as they cause confusion, so I think there is no action on this issue required.
