### ISSUE TITLE
mTLS: encrypted alert and TCP RST

### ISSUE THREAD

**Issue by mgxian** [istio/istio#24806]
**Bug description**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

istio 1.5.4

k8s 1.14.8

I use mTLS mode permissve for my istio cluster, when capture traffic from ingressgateway I got follow tcp flow.
![image](https://user-images.githubusercontent.com/10857630/85126818-caf6d500-b260-11ea-970b-3c4d49d67930.png)

why there are too many `encrypted alert` and `TCP RST` ?

**Comment by myidpt** [comment]
This is interesting. @lizan do you know anyone from Envoy community can help investigate?

**Comment by myidpt** [comment]
Is this the traffic from the ingressgateway to a cluster internal workload?

**Comment by mgxian** [comment]
yes. ingressgateway to my web service

**Comment by yann-soubeyrand** [comment]
Hi,

I'm also seeing TCP RST with an external service for which TLS origination is configured.

![wireshark-screenshot](https://user-images.githubusercontent.com/8511577/98439846-f0dc2380-20f4-11eb-95f6-d55fec62e3c8.png)

Could we reopen this issue?
