### ISSUE TITLE
No visibility into bad IOP yaml

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#24819]
Apply yaml like

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  profile: default
  revision: 16
```

note: revision is an int not a string

IOP gets no status.

Only info about this is operator logs showing
```
2020-06-19T17:07:21.829451Z     error   k8s.io/client-go@v0.18.0/tools/cache/reflector.go:125: Failed to list *v1alpha1.IstioOperator: v1alpha1.IstioOperatorList.ListMeta: v1.ListMeta.TypeMeta: Kind: Items: []v1alpha1.IstioOperator: v1alpha1.IstioOperator.Spec: unmarshalerDecoder: json: cannot unmarshal number into Go value of type string, error found in #10 byte of ...|":false}}}}],"kind":|..., bigger context ...|tyEnabled":true}},"prometheus":{"enabled":false}}}}],"kind":"IstioOperatorList","metadata":{"continu|...
```

**Comment by adiprerepa** [comment]
Ideal visibility is an error message?

**Comment by esnible** [comment]
@adiprerepa ideal visibility would be the webhook rejecting it.

`istioctl validate -f ` reports `* IstioOperator/istio-system/issue24819: could not unmarshal: json: cannot unmarshal number into Go value of type string` and the webhook should have a message at least as good as that.

**Comment by esnible** [comment]
@ostromart Is this still P0 targetting 1.7?

**Comment by Jeskz0rd** [comment]
I'm also able to see it in 1.6.8 with Bool.

```yaml
	k8s.io/client-go@v0.18.0/tools/cache/reflector.go:125: Failed to list *v1alpha1.IstioOperator: v1alpha1.IstioOperatorList.ListMeta: v1.ListMeta.TypeMeta: Kind: Items: []v1alpha1.IstioOperator: v1alpha1.IstioOperator.Spec: unmarshalerDecoder: json: cannot unmarshal bool into Go value of type string, error found in #10 byte of ...|ch.io"}}}}}],"kind":|..., bigger context
```

**Comment by esnible** [comment]
There are fixes for bad IOP in https://github.com/istio/istio/pull/26308 .  **PLEASE** review.

The current IOP parsing using protobufs.  We should consider a pure JSON parse.  Here is (lightly tested) code for non-protob parse:
```
jb, err := yaml.YAMLToJSON([]byte(iopYAML))
	if err != nil {
		fmt.Printf("%q YAMLToJSON failed; err=%v\n", title, err)
		return
	}
	ik := crd.IstioKind{}
	err = json.Unmarshal(jb, &ik)
	if err != nil {
		fmt.Printf("%q IstioKind Unmarshal failed; err=%v\n", title, err)
		return
	}
	b, err := json.Marshal(ik.Spec)
	if err != nil {
		fmt.Printf("%q IstioKind remarshal spec failed; err=%v\n", title, err)
		return
	}
	iopSpec := v1alpha1.IstioOperatorSpec{}
	err = json.Unmarshal(b, &iopSpec)
	if err != nil {
		fmt.Printf("%q IstioKind unmarshal spec failed; err=%v\n", err)
		return
	}
	iop := operator_istio_v1alpha1.IstioOperator{
		Kind:       ik.Kind,
		ApiVersion: ik.APIVersion,
		ObjectMeta: ik.ObjectMeta,
		TypeMeta:   ik.TypeMeta,
		Spec:       &iopSpec,
	}
```

@ostromart and I will see if we can convert the utility method to use a technique like this.

**Comment by howardjohn** [comment]
To clarify: the original intent of this issue is nothing to do with the error. The problem is when there is any error, the user has no way of understanding what went wrong. We should never have to look at operator logs.

**Comment by ostromart** [comment]
This is not a trivial problem to solve because the errors we are getting are coming from dependencies. Short of writing our own YAML parser, we can probably get some more useful locality info by feeding in the bad manifest gradually until an error is hit - but that's still very difficult because partial YAMLs are often invalid. It's a longer term task, handing over to @su225 to investigate further.

**Comment by su225** [comment]
Just experimented with `gopkg.in/yaml.v2` and `gopkg.in/yaml.v3`. It seems that we **do get line number in error message**
For the following YAML, I get the following error message
**NOTE**: These YAMLs are random and has nothing to do with `IstioOperator` CR.
```
"yaml: line 4: mapping values are not allowed in this context"
```
```yaml
name: xyz
revision: a
  major: x
```
I tried one more more and there is a difference between `v2` and `v3`.
```yaml
name: xyz
revision:
  major: 1
  rev: a
```
Here `rev` field is not in the struct. In `v2` when I tried with `UnmarshalStrict` - I get an error. However, in `v3` and `v2`, with `Unmarshal` it will just ignore fields which are not present in struct. There are other ways like `Decoder` which I haven't yet explored.

But there are many caveats though - for the example @howardjohn  mentioned, integer is interpreted as string by the library where as the other way around is not possible for obvious reasons. If it has some fields missing, then it does not raise an error.

**Comment by bianpengyuan** [comment]
Per https://github.com/istio/istio/issues/24819#issuecomment-707900293 I don't think it is feasible to address this by 1.8. Move this to 1.9.

**Comment by shamsher31** [comment]
The error does look a little better with invalid revision.

```yaml
# iop.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  profile: default
  revision: 18
```

```
$ ./out/linux_amd64/istioctl install -f iop.yaml --set hub=gcr.io/istio-testing -d manifests/
Error: failed to get profile and enabled components: failed to read profile:
json: cannot unmarshal number into Go value of type string:

YAML:
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  profile: default
  revision: 18
```

I have a partial fix to handle invalid revision https://github.com/istio/istio/pull/28745, maybe a hack is required to translate a number into a string before unmarshalling into jsonpb [here](https://github.com/istio/istio/blob/c5ad10c525289c1ed89458ea04776ad87755f6ef/operator/pkg/validate/common.go#L288)?

**Comment by su225** [comment]
Or how about not parsing directly to `IstioOperator`? We could parse it to `Unstructured` or `map[string]interface{}`. Then with something like `tpath` we can pick the fields and validate. That way, we can give the user context and avoid printing huge YAML. As we have given the field name, we don't have to show that in YAML.

**Comment by esnible** [comment]
I agree with @su225 and my own comment https://github.com/istio/istio/issues/24819#issuecomment-676375377 .  I am willing to tackle this but I got frustrated that I couldn't get a review https://github.com/istio/istio/pull/26308 which I wanted to merge first.

@ostromart Can we put this on BOTH the Environments and UX roadmap for 1.9?  This is a P0 and deserves tracking.

**Comment by shamsher31** [comment]
> Or how about not parsing directly to IstioOperator? We could parse it to Unstructured or map[string]interface{}.

We are already doing that.

> Then with something like tpath we can pick the fields and validate. 

I think we can try this but I'm more interested in doing something like the following before unmarshlling to `IstioOperator`.

https://github.com/istio/istio/blob/d5893dc37b2c1ab9d05d839173017b35990c8e92/operator/pkg/validate/validate.go#L33-L42

**Comment by su225** [comment]
@shamsher31 - Yup. That was what I meant in my comment. Probably, bringing `tpath` was confusing. In simple words - walk the path in the given `map[string]interface{}` (is there a library for this already? This looks generic) and apply validation.
