### ISSUE TITLE
Consider using μpb (micro protobuf) for Wasm

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#24810]
Micro protobuf has a much smaller footprint than full proto and is widely used. It I used as a dependency of grpc.

https://github.com/grpc/grpc/tree/master/third_party/upb

Consider using it as proto impl.

@lizan @jplevyak @kyessenov

**Comment by kyessenov** [comment]
UPB and protobuf are not compatible, so all the downstream dependencies would have to take on UPB. I think it's also missing many protobuf features (reflection, json, etc), and it's really C not C++.

**Comment by lizan** [comment]
What do you mean by "not compatible", source level? It does have json and some of C++ wrapper.

**Comment by kyessenov** [comment]
I mean using any Google library with upb would require a rewrite. This is an ongoing discussion with CEL-CPP, for example. It's not a simple swap. If we're going to rewrite, then might as well use non-protobuf libraries.

**Comment by lizan** [comment]
Well yeah, but at least it is wire compatible comparing to other libraries. It's more a mechanical rewrite than a semantically rewrite.

**Comment by kyessenov** [comment]
Yeah, it's worth investigating. What concerns me is the claim that fully optimized upb (JITted and so on) is only competitive with regular protobuf in terms of performance (e.g. it's not much faster). It doesn't seem like it's going to give us better Wasm performance. Upb might give a bit of space savings at the cost of locking us out of all libraries that use regular protobuf.
