### ISSUE TITLE
Pilot / appNamespaces | cannot unmarshal string into Go value of type map[string]json.RawMessage

### ISSUE THREAD

**Issue by antonioberben** [istio/istio#24827]
**Bug description**
Trying to setup an IstioOperator libe below, it show an error:
```
json: cannot unmarshal string into Go value of type map[string]json.RawMessage
```
IstioOperator definition:
```
[...]
    pilot:
      appNamespaces:
        - my-name-space
[...]
```

[X] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

The installation succeeds without error

**Steps to reproduce the bug**

After dumping, for example, demo profile
```
$ istioctl profile dump demo > operator.yaml
```

Then, adding the change:

```
[...]
spec:
  [...]
  values:
    pilot:
      appNamespaces:
        - my-namespace
[...]
```

Fially, try to output parsed yamls:
```
istioctl manifest generate -f operator.yaml -o out
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

1.6.3

**How was Istio installed?**

Not needed since it fails already when parsing to yaml

**Environment where bug was observed (cloud vendor, OS, etc)**

Local

**Comment by esnible** [comment]
appNamespaces is a slice of Map.

This is valid: `istioctl manifest generate --set values.pilot.appNamespaces[0].ns=my-name-space`

I must admit I don't know what appNamespaces does and couldn't find it in the docs.  I can't advise you on what it should look like.  But try this:

```
    pilot:
      appNamespaces:
        - my-key: my-namespace
```

**Comment by antonioberben** [comment]
Hi @esnible . You are right in the shape of the expected yaml.

The problem comes when the whole helm chart, operator, etc., expects that to be a simple array.

Otherwise, in your case, what would it be `my-key`?

**Comment by antonioberben** [comment]
Debuggin the code tourned out the the `appNamespaces` is not used anymore. Instead, a new attrbute is use called `oneNamespace` which sets the value of `appNamespaces` to the very same namespace istio is installed on.

Here the line of code:
https://github.com/istio/istio/blob/25bf46237382f5e6de7c3b8f1cfa8958ec0f9f28/manifests/charts/istio-control/istio-discovery/templates/deployment.yaml#L79

I will close this issue

**Comment by xulingqing** [comment]
When I tried customize Stackdriver installation, I met the same error. I solve by passing command like 
```
./out/linux_amd64/istioctl install --set hub=$HUB --set tag=$TAG --set values.telemetry.v2.stackdriver.enabled=true --set values.telemetry.v2.stackdriver.logging=true --set values.telemetry.v2.stackdriver.topology=true --set values.telemetry.v2.stackdriver.configOverride.enable_xxx_log=true
```
It seems `configOverride.enable_xxx_log=true` this is the right way for command if your want to pass value to map. Thanks.
