### ISSUE TITLE
Add regression tests for past CVEs

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#24826]
For most CVEs we create scripts to reproduce and validate the fixes are applied. This is critical to ensuring the patches are correctly applied.

It may be useful to keep these as part of the repo in CI such that we can always run them. This ensures that in some mixup of private releases (easy to happen) we don't accidentally revert a patch.

At the very least just having some "mega script" that runs all the other scripts against some docker image would be useful

**Comment by daixiang0** [comment]
Is it still help wanted?

**Comment by zhlsunshine** [comment]
It seems that this issue need to be moved to 1.12

**Comment by howardjohn** [comment]
Currently no progress has been made on this but it does seem desirable.

**Comment by oxr463** [comment]
Can you point me in the right direction for previous CVEs so I can put together a list of regression tests that will need to be added?

**Comment by oxr463** [comment]
This is a good place to start:

- https://istio.io/latest/news/security
