### ISSUE TITLE
istio log not showing up

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#2483]
the default for istio log should be stderr so it shows automatically when go tests are failing

right now we have PRs failing and nowhere to be found why

for instance:
https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/2430/e2e-smoke/1202/
from #2430

**Comment by geeknoid** [comment]
The default output is stdout. Shouldn't we be capturing stdout as well in the test running environment?

**Comment by jasonwzm** [comment]
no test failure logs seen in stdout. looks like test logs are exported to --test_logs_path=/home/bootstrap/go/src/istio.io/istio/_artifacts

**Comment by geeknoid** [comment]
Yep, you can dig 'em out there.

**Comment by ldemailly** [comment]
the out of the box / default config of the istio logger should be such as running go test or go services in k8s get logs out of the box - it's important; the burden is not on the infrastructure to collect logs from new unexpected places

**Comment by sebastienvas** [comment]
Fixed by #2593
