### ISSUE TITLE
How to config service to http://IP:path ?

### ISSUE THREAD

**Issue by hillbun** [istio/istio#24840]
I need to config 
service frontend to http://192.168.0.1/
service api1 to http://192.168.0.1/api1
service api2 to http://192.168.0.1/api2

how to config it?

**Comment by hillbun** [comment]
no domain name is required.

**Comment by howardjohn** [comment]
See https://istio.io/latest/docs/reference/config/networking/virtual-service/, there are many examples of path based routing. You can allow host=`*`

**Comment by hillbun** [comment]
@howardjohn 

is host=192.168.0.1  allowed to config?

**Comment by howardjohn** [comment]
Yes
