### ISSUE TITLE
Adding new dimension to existing metric creates a new metric instead (istio 1.6.1)

### ISSUE THREAD

**Issue by jackfrost02** [istio/istio#24844]
**Bug description**
Adding new dimension to existing metric in stats-filter-1.6.yaml file creates a few new envoy metrics instead.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
added dimension shows up in defined metric.

**Steps to reproduce the bug**
I tried to add a new dimension to istio_requests_total metric by following the doc (I added request_path instead of destination_port) -> ref: https://istio.io/latest/docs/tasks/observability/metrics/customize-metrics/.
my stats-filter-1.6.yaml attached.
[stats-filter-1.6.yaml.gz](https://github.com/istio/istio/files/4808623/stats-filter-1.6.yaml.gz)

I also added the following annotations to my deployment
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bookstore
  name: bookstore
  namespace: default
  annotations:
    sidecar.istio.io/extraStatTags: request_host,request_path
```
I kubectl apply the stats-filter-1.6.yaml file and restarted my deployment. When I exec into the pod istio-proxy container, I got a few new metrics prefixed with 'envoy_request_path____' instead: 
```
# TYPE envoy_request_path____listbooks____istio_requests_total counter
envoy_request_path____listbooks____istio_requests_total{response_code="200"...
# TYPE envoy_request_path____latest_meta_data_iam_security_credentials_____istio_requests_total counter
envoy_request_path____latest_meta_data_iam_security_credentials_____istio_requests_total{response_code="200"....
```
[output1.txt](https://github.com/istio/istio/files/4808627/output1.txt)

I was expecting to see the request_path dimension would be in requests_total metric itself rather than its own metric. 

On the other hand, request_host dimension is added properly.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
bin/istioctl version --remote
client version: 1.6.1
control plane version: 1.6.1
data plane version: 1.6.1 (3 proxies)
```
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.10-eks-bac369", GitCommit:"bac3690554985327ae4d13e42169e8b1c2f37226", GitTreeState:"clean", BuildDate:"2020-02-21T23:37:18Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
```
bin/istioctl manifest generate --set values.global.controlPlaneSecurityEnabled=true  --set addonComponents.grafana.enabled=true --set components.policy.enabled=true --set components.telemetry.enabled=true > istioinstall.yaml
then
kubectl apply istioinstall.yaml
```
**Environment where bug was observed (cloud vendor, OS, etc)**
```
aws eks version 1.15 on amazon-linux
```

**Comment by bianpengyuan** [comment]
You need to add `path` tag annotation in order to make metrics parsing correctly. See step 6 in https://istio.io/latest/docs/tasks/observability/metrics/customize-metrics/.

**Comment by jackfrost02** [comment]
I added the following annotations to my deployment
```sidecar.istio.io/extraStatTags: request_host,request_path```
so my deployment looks like the following:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bookstore
  name: bookstore
  namespace: default
  annotations:
    sidecar.istio.io/extraStatTags: request_host,request_path
```
pls note that I'm using apiVersion apps/v1 instead of extensions/v1beta1

Did i miss anything? can you explain what you meant by ```path``` tag annotation?

**Comment by bianpengyuan** [comment]
Ah sorry, I miss read the metrics.

So these annotations should be added to your pod template (i.e. add to spec.template.metadata.annotations), instead of deployment metadata. The current documentation has misleading indentation, which causes misunderstanding here I think. Sorry about this and I will make a fix for that.

`request_host` could be extracted fine because it is part of default tag list: https://github.com/istio/istio/blob/1e8c62baad31c829c5993235c429248f36a85478/pkg/bootstrap/config.go#L188

**Comment by jackfrost02** [comment]
Yes, you're correct bianpengyuan. I put the annotations to my pod template with the correct indentation and the dimension showed up correctly. Thank you.

**Comment by Virinchi2595** [comment]
@jackfrost02 
Can you please tell me all the changes you have done for this to work?
I am trying in Istio 1.18 but unable to understand where to modify following the documentation.

Thanks.

**Comment by jackfrost02** [comment]
just to note, I did this in 1.6. Haven't tried 1.8 yet (I assume that's the version you tried?)
- I exported stats-filter to a file (kubectl -n istio-system get envoyfilter stats-filter-1.6 -o yaml > something.yaml)
- modify that file (something.yaml) and add the new dimension in whichever context you need, for my case it's SIDECAR_INBOUND context. Add the following inside configuration block so it reads the following
```configuration: |
                {
                  "debug": "false",
                  "stat_prefix": "istio",
                  "metrics": [
                      {
                          "name": "request_duration_milliseconds",
                          "dimensions": {
                              "request_path": "request.path"
                          }
                      }
                  ]
                }
```
- Deploy the modified envoy filter (kubectl apply)
- add extraStatTags to my deployment like the following
```
  template:
    metadata:
      annotations:
        sidecar.istio.io/extraStatTags: request_path
```
- Re-deploy the app
- restart istio-ingressgateway (kill the pod)
- verify the new dimension shows up under request_duration_milliseconds metric(s)

Hope that helps.

**Comment by Virinchi2595** [comment]
@jackfrost02 
Thank you for replying.

I followed the steps you mentioned.

please see attached video 
let me know if I am doing anything wrong.

https://drive.google.com/file/d/1Uzm-rGTtmkKIYoIFXnYUAC7MyA-DY58Z/view?usp=sharing

Thank you.

**Comment by Virinchi2595** [comment]
@jackfrost02 
I tried same thing in Istio 1.6 it seems to be working fine
not sure why it fails in Istio 1.8
