### ISSUE TITLE
TCP traffic routing based on client ip address

### ISSUE THREAD

**Issue by hyogyunbang** [istio/istio#24852]
**Describe the feature request**
HTTP traffic can be routed based on client ip address using headers field in Virtual Service, otherwise there is no way to route TCP traffic based on client ip address even if proxy protocol is enabled on external LB. I researched how to route TCP traffic with Envoy Filter for several days but I couldn't resolve it. This feature would be useful for many people so that I request the feature that enable TCP traffic routing based on client ip address.

**Describe alternatives you've considered**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
I think this can be done with destinationSubnets? https://istio.io/latest/docs/reference/config/networking/virtual-service/#L4MatchAttributes

**Comment by esnible** [comment]
In the past I have done this with ServiceEntry `addresses`.

See https://github.com/istio/istio/blob/master/samples/external/github.yaml for an example.

**Comment by honillusion** [comment]
How can I apply a condition statement for client ip address? In case of HTTP, it works with the below manifest.
`
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: app-vservice
  namespace: test
spec:
  hosts:
  - "app-service"
  http:
  - match:
    - headers:
        x-forwarded-for:
          exact: 123.123.123.123
    route:
    - destination:
        host: app-service
        subset: v2
  - route:
    - destination:
        host: app-service
        subset: v1
`

**Comment by OnlyPiglet** [comment]
> I think this can be done with destinationSubnets? https://istio.io/latest/docs/reference/config/networking/virtual-service/#L4MatchAttributes

not des but src
