### ISSUE TITLE
Change outputkeycerttodir to be a move instead of writing

### ISSUE THREAD

**Issue by snuggie12** [istio/istio#24850]
**Describe the feature request**
We are using gloo as an api gateway and followed [these instructions](https://docs.solo.io/gloo/latest/guides/integrations/service_mesh/gloo_istio_mtls/#istio-15x) to set it up (I also set up a cluster that uses SDS looking at the cert/key.) However, after the certificate expires we get errors connecting to the upstream saying it is expired. If you check `/etc/istio-certs` you'll see that istio-proxy indeed updated the files.

However, based on [this](https://github.com/istio/istio/blob/120c9b053de0ddea3cfd1830363491d39217e200/security/pkg/nodeagent/util/util.go#L75-L79) I believe istio-proxy is just writing to the file. Based on envoy's documentation [here](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/core/config_source.proto#core-configsource) (read the second note under `path`) I believe that a move is required instead of writing over the content of the file. I tested this by exec'ing to the container, copying the files (e.g. `cp /etc/istio-certs/cert-chain.pem /etc/istio-certs/cert-chain.pem.bak`) and then moving the copies into the original location (e.g. `mv /etc/istio-certs/cert-chain.pem.bak /etc/istio-certs/cert-chain.pem`) and the upstreams started to work again.

**Describe alternatives you've considered**
Some sort of code change could be made on the gloo side and some sort of gRPC SDS could be setup to work with istio. Or something could watch for a checksum change to the file and then do the mv.

**Affected product area (please put an X in all that apply)**

[X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**
It's also possible you and solo are working on some tighter integration and this would not need to go into istio-agent and if so I welcome that solution as well.

Currently using istio 1.5.4 and gloo enterprise 1.3.8.

**Comment by JimmyCYJ** [comment]
@lei-tang is OOO, assign to @myidpt to triage the issue.

**Comment by JimmyCYJ** [comment]
cc @williamaronli

**Comment by myidpt** [comment]
Assigning to Lei. This should be a simple fix.

**Comment by howardjohn** [comment]
This is done in 1.9. Thanks!
