### ISSUE TITLE
Missing affinity section in istio-discovery deployment manifest

### ISSUE THREAD

**Issue by SandeepVaman** [istio/istio#24854]
Current manifests for installing Istiod (Istio-discovery) deployment does not have affinity section defined because of which Istiod pods are getting scheduled in a random node pool.
I have raised a PR to fix this. Please review this.

https://github.com/istio/istio/pull/24853

[ ] Configuration Infrastructure
[ ] Docs
[ X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Istiod pod should get scheduled in the assigned node pool.

**Steps to reproduce the bug**
Install Istio with .Values.global.defaultNodeSelector or .Values.pilot.nodeSelector selector set to one nodepool label.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istioctl version --remote
client version: 1.6.2
control plane version: 1.6.2
data plane version: 1.6.2 (XXX proxies)

**How was Istio installed?**
Istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

**Comment by lukeplausin** [comment]
lifecycle/needs-triage
