### ISSUE TITLE
The default namespace for istioctl is not properly computed

### ISSUE THREAD

**Issue by christian-posta** [istio/istio#2486]
If I run istioctl without specifying a namespace, in a namespace other than default, istioctl will take the liberty to just stash my routerules/destinationpolicy into the `default` namespace. This gets confusing. I'd like istioctl to behave similar to kubectl and just default to the namespace in which i'm currently. 

https://github.com/istio/istio/blob/master/pilot/cmd/istioctl/main.go#L757

Related:

https://github.com/istio/issues/issues/110

**Comment by ldemailly** [comment]
this was supposed to have been fixed in
https://github.com/istio/old_pilot_repo/pull/1373

**Comment by christian-posta** [comment]
Yah, seems it was sorted with that PR, except this commit introduced the bug i'm seeing:

https://github.com/istio/istio/commit/618f6ab424b089f6c619e8433a7351fde9cfbb5f

My fix returns the proper default namespace if one exists.
