### ISSUE TITLE
istioctl upgrade --dry-run fails

### ISSUE THREAD

**Issue by ostromart** [istio/istio#24865]
Trying to upgrade to 1.6.3 from 1.5.5 but need to test the upgrade first. So basically I use dry-run to check the installation process.

But in Istioctl 1.6.3, the dry-run checking the remote component version, and make it fail.

istioctl upgrade -f cluster.yaml --force --skip-confirmation --dry-run 
.
✔ Istio core installed                                                                                                                                                       
✔ Istiod installed                                                                                                                                                           
✔ Ingress gateways installed                                                                                                                                                 
✔ Addons installed                                                                                                                                                           
✔ Installation complete                                                                                                                                                      ..........
Control Plane - ingressgateway pod - istio-ingressgateway-585bd46745-895l5 - version: 1.5.5 does not match the target version 1.6.3
Control Plane - ingressgateway pod - istio-ingressgateway-585bd46745-r2hs9 - version: 1.5.5 does not match the target version 1.6.3
Control Plane - ingressgateway pod - istio-ingressgateway-585bd46745-r52jv - version: 1.5.5 does not match the target version 1.6.3
Control Plane - pilot pod - istiod-79cd4cbb44-4dk5t - version: 1.5.5 does not match the target version 1.6.3
Control Plane - pilot pod - istiod-79cd4cbb44-6rts2 - version: 1.5.5 does not match the target version 1.6.3
Control Plane - pilot pod - istiod-79cd4cbb44-7wlpd - version: 1.5.5 does not match the target version 1.6.3
..........
Control Plane - ingressgateway pod - istio-ingressgateway-585bd46745-895l5 - version: 1.5.5 does not match the target version 1.6.3
Control Plane - ingressgateway pod - istio-ingressgateway-585bd46745-r2hs9 - version: 1.5.5 does not match the target version 1.6.3
Control Plane - ingressgateway pod - istio-ingressgateway-585bd46745-r52jv - version: 1.5.5 does not match the target version 1.6.3
Control Plane - pilot pod - istiod-79cd4cbb44-4dk5t - version: 1.5.5 does not match the target version 1.6.3
Control Plane - pilot pod - istiod-79cd4cbb44-6rts2 - version: 1.5.5 does not match the target version 1.6.3
Control Plane - pilot pod - istiod-79cd4cbb44-7wlpd - version: 1.5.5 does not match the target version 1.6.3
When upgrading directly without dry-run, it works fine. But we need to implement istioctl on CI and cannot upgrade directly (must check first with dry-run).

Any solution to this?

**Comment by mhdramzeen** [comment]
Facing the same issue, while trying to upgrade from 1.5.0 to 1.6.4

istioctl upgrade --force -f values.yaml

..........
Control Plane - citadel pod - istio-citadel-7b77bd75cc-j6vrf - version: 1.5.0 does not match the target version 1.6.4
Control Plane - galley pod - istio-galley-7d96648cc6-vtmqx - version: 1.5.0 does not match the target version 1.6.4
Control Plane - pilot pod - istio-pilot-cd776c4d5-dglpg - version: 1.5.0 does not match the target version 1.6.4
Control Plane - policy pod - istio-policy-7b85b7ccb4-w5x9p - version: 1.5.0 does not match the target version 1.6.4
Control Plane - sidecar-injector pod - istio-sidecar-injector-847f7f9956-jpzq9 - version: 1.5.0 does not match the target version 1.6.4
Control Plane - telemetry pod - istio-telemetry-7768cb7778-pr7rp - version: 1.5.0 does not match the target version 1.6.4
..........

Can you please provide a solution on this....thanks

**Comment by zufardhiyaulhaq** [comment]
@elfinhe can we push this to the next patch since this will block the --dry-run upgrade?

**Comment by elfinhe** [comment]
which minor version?

**Comment by zufardhiyaulhaq** [comment]
last time I check on 1.6.3, let me check again in 1.6.5, I made a PR since there is no code change.

**Comment by elfinhe** [comment]
Now the fix is in master. I am working on a cherry-pick into release-1.6.

**Comment by elfinhe** [comment]
cherry-pick is created here: https://github.com/istio/istio/pull/25425

**Comment by elfinhe** [comment]
The fix should be released into next 1.6 patch version - 1.6.6, and the minor version 1.7.0

**Comment by elfinhe** [comment]
Thanks so much for the fix. @zufardhiyaulhaq

**Comment by elfinhe** [comment]
Fixed by https://github.com/istio/istio/pull/25425

**Comment by zufardhiyaulhaq** [comment]
@elfinhe did this already apply in 1.6.5?
