### ISSUE TITLE
Istio with jaeger-operator [minikube] : Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert istio-token]

### ISSUE THREAD

**Issue by dumindu** [istio/istio#24866]
**Bug description**
`Kubectl describe po istio-ingressgateway-5855454469-xj4xs`

```
kubelet, minikube  Unable to attach or mount volumes: unmounted volumes=[istiod-ca-cert istio-token],
unattached volumes=[podinfo istiod-ca-cert ingressgateway-certs ingressgateway-ca-certs istio-ingressgateway-service-account-token-pm6hf config-volume istio-token ingressgatewaysdsudspath istio-envoy]: timed out waiting for the condition

kubelet, minikube  MountVolume.SetUp failed for volume "istiod-ca-cert" : configmap "istio-ca-root-cert" not found
kubelet, minikube  MountVolume.SetUp failed for volume "istio-token" : failed to fetch token: the server could not find the requested resource
```

- Installation

- Virtual Machine

**Expected behavior**
- Should not get this error

**Steps to reproduce the bug**

- Istio : v1.6.3 / k8s: v1.16.10 (both client and server)/ minikube 1.11.0

- `minikube start --memory=16384 --cpus=4 --kubernetes-version=v1.16.10` && `minikube addons enable ingress`

- Install `jaeger-operator` according to https://github.com/jaegertracing/jaeger-operator
```
kubectl create namespace observability
kubectl create -n observability -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/crds/jaegertracing.io_jaegers_crd.yaml
kubectl create -n observability -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/service_account.yaml
kubectl create -n observability -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/role.yaml
kubectl create -n observability -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/role_binding.yaml
kubectl create -n observability -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/operator.yaml

kubectl create -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/cluster_role.yaml
kubectl create -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/cluster_role_binding.yaml

kubectl apply -n observability -f - <<EOF
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simplest
EOF
```

- Adding ingress for Jaeger collector by applying following yaml
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: simplest-collector-ingress
  namespace: observability
spec:
  rules:
  - host: test.com
    http:
      paths:
      - backend:
          serviceName: simplest-collector
          servicePort: 9411
```
> `kubectl get ingress -n observability`
> ![Screenshot 2020-06-23 at 12 21 50 AM](https://user-images.githubusercontent.com/1280428/85311366-ecb5bd80-b4e7-11ea-8ff2-9da70311ad08.png)

- Create istio manifest and apply
```
istioctl manifest generate \
--set values.grafana.enabled=true \
--set values.tracing.enabled=true \
--set values.global.tracer.zipkin.address=192.168.39.240.observability:9411 > ./istio-manifest.yaml
```

> manifest.yaml : https://gist.github.com/dumindu/200053ef458716bc39b40a0aa78cfde6
> `describe istio-system istio-ingressgateway-5855454469-xj4xs` : https://gist.github.com/dumindu/2d7dee3caed9a798df73167f51d06f66

Istio pods stuck at `ContainerCreating` status
![Screenshot 2020-06-23 at 12 29 10 AM](https://user-images.githubusercontent.com/1280428/85312205-128f9200-b4e9-11ea-8765-30b19656d736.png)

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
- Istio : v1.6.3 / k8s: v1.16.10 (both client and server)/ minikube 1.11.0

**How was Istio installed?**
`curl -L https://istio.io/downloadIstio | sh -` add bin path the PATH

**Environment where bug was observed (cloud vendor, OS, etc)**
Fedora / minikube 1.11.)

- Istio : v1.6.3 / k8s: v1.16.10 (both client and server)/ minikube 1.11.0

**Comment by howardjohn** [comment]
Its because istiod is not running, so you should look there first. My guess is due to https://preliminary.istio.io/latest/docs/ops/best-practices/security/#configure-third-party-service-account-tokens

**Comment by dumindu** [comment]
@howardjohn with reference https://istio.slack.com/archives/CME8W56RW/p1592853896119600

We can reproduce the error even with following command,
```
istioctl manifest generate \                                                                                                                                               
--set values.grafana.enabled=true > ./istio-manifest.yaml
```

Don't you think that Istio should not give this error for above command?

**Comment by howardjohn** [comment]
@dumindu please see the link above,   there are additional steps required if your cluster doesn't support 3p jwt tokens

**Comment by dumindu** [comment]
Got it. Let me check.
Thanks

**Comment by dumindu** [comment]
For minikube, we need to create another manifest including `--set values.global.jwtPolicy=first-party-jwt`. Ex.

- For production(eks)
```
istioctl manifest generate \                                                                                                                                               
--set values.grafana.enabled=true > ./istio-manifest.yaml
```

- For Minikube
```
istioctl manifest generate \ 
--set values.global.jwtPolicy=first-party-jwt \                                                                                                                                       
--set values.grafana.enabled=true > ./istio-manifest.yaml
```

**Comment by stevek-pro** [comment]
! values.grafana.enabled is deprecated; use the samples/addons/ deployments instead
! addonComponents.grafana.enabled is deprecated; use the samples/addons/ deployments instead
