### ISSUE TITLE
IstioOperator - meshConfig envoyMetricsService location

### ISSUE THREAD

**Issue by PatrickDuncan** [istio/istio#24872]
**Bug description**

I want to set `envoyMetricsService` and it appears that the parameter has moved around quite a bit. Every location in the IstioOperator I've tried has failed the validation

Can't seem to find the correct location in:
https://github.com/istio/istio/search?q=envoyMetricsService&unscoped_q=envoyMetricsService
https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#ProxyConfig
https://godoc.org/istio.io/api/mesh/v1alpha1

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Not sure if this quantifies as a bug, but I'm assuming some changes are required.

I've tried to set `envoyMetricsService` in the following locations with `IstioOperator - install.istio.io/v1alpha1`
```
spec.meshConfig.envoyMetricsService
spec.meshConfig.proxy.envoyMetricsService
spec.meshConfig.proxyConfig.envoyMetricsService
spec.values.meshConfig.envoyMetricsService
spec.values.meshConfig.proxy.envoyMetricsService
spec.values.meshConfig.proxyConfig.envoyMetricsService
spec.values.proxyConfig.envoyMetricsService

# Deprecated message says: "! global.proxy.envoyMetricsService is deprecated; use meshConfig.envoyMetricsService instead"
spec.values.global.proxy.envoyMetricsService
```

Where exactly is envoyMetricsService supposed to be defined?

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
client version: 1.6.1
control plane version: 1.6.1
data plane version: 1.6.1 (2 proxies)

Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"e0fccafd69541e3750d460ba0f9743b90336f24f", GitTreeState:"clean", BuildDate:"2020-04-16T11:44:03Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6+IKS", GitCommit:"43e4e6c4d0732364dff505878c79211999c58e04", GitTreeState:"clean", BuildDate:"2020-05-20T20:29:26Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by esnible** [comment]
`--set meshConfig.defaultConfig.envoyMetricsService.address=baz:1234` works.

I knew `meshConfig` was there and I poked around in https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#RemoteService to figure out the path to reach it.

**Comment by PatrickDuncan** [comment]
@esnible Thank you, that makes a lot of sense. I can see how to effectively use the reference now. I think the deprecation message should change to:
```
! global.proxy.envoyMetricsService is deprecated; use meshConfig.defaultConfig.envoyMetricsService instead
```

For future readers...
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    defaultConfig:
      envoyMetricsService:
          address: <ADDRESS>
```

**Comment by esnible** [comment]
@ostromart Re-opening and labelling as `area/environments`.  I am looking for a PR that just fixes the typo `meshConfig.envoyMetricsService` with the correct name as mentioned in https://github.com/istio/istio/issues/24872#issuecomment-647707032
