### ISSUE TITLE
TestExtractRootCertExpiryTimestamp test failure

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#24871]
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/24863/unit-tests_istio_release-1.6/366

**Comment by williamaronli** [comment]
flaky issue moves to tech-debt

**Comment by howardjohn** [comment]
Why do we need a tech debt label when we already have a label dedicated to test failures?

**Comment by williamaronli** [comment]
it seems a PR from this : https://github.com/istio/istio/pull/23076. yangmin gives some comments on it. Assign it to yangmin

**Comment by yangminzhu** [comment]
@williamaronli  please do not assign the issue to me, I only did a general code review of the PR and not sure about the test failing.

**Comment by yangminzhu** [comment]
cc @lucasvmiguel who changed the test in the original PR.

**Comment by williamaronli** [comment]
@howardjohn @lucasvmiguel  as the code has been changed is it still flaky ?

**Comment by howardjohn** [comment]
I think its fixed
