### ISSUE TITLE
TestSDSAgentStreamWithCacheAndConnectionCleaned test flake

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#24870]
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/24862/unit-tests_istio/14983

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gcs/istio-prow/logs/unit-tests_istio_postsubmit/2760

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/24549/unit-tests_istio/15088

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/29372/unit-tests_istio/1336431207356829696

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gs/istio-prow/logs/unit-tests_istio_postsubmit/1336791196063764480

**Comment by williamaronli** [comment]
how about we skipped it?

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/29529/unit-tests_istio/1344326763026583552

**Comment by howardjohn** [comment]
test removed
