### ISSUE TITLE
Externalname Service Not available when namespace is locked to Strict mtls mode

### ISSUE THREAD

**Issue by satishmane** [istio/istio#24886]
**Bug description**

When namespace is locked to strict mtls mode, call to any service in it using externalName from another namespace which has permissive mtls mode enabled fails with 503 - Service Not available. 

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ X ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Istio should resolve external name service type and call service in another namespace having peerauthentication mode set to strict

**Steps to reproduce the bug**
1. Create a namespace foo
2. Deploy a service x in namespace foo on port say http 8080
3. Create peerauthetication at namespace level with tls mode set to strict

4. Create another namespace bar
5. Deploy a service y in namespace bar or deploy any pod having curl command installed
6. Ensure namespace bar is in permissive mode. Just ensure there is no peerauthentication in it. leave as is AutoMtls on
7. Create kubernetes externalname type service (say test-service) in namespace bar pointing to service x.foo.svc.cluster.local. 

8. execute curl http://test-service:8080

it fails as below
HTTP/1.1 503 Service Unavailable

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

client version: 1.5.4
control plane version: 1.5.4
data plane version: 1.5.4 (26 proxies)

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-18T17:02:08Z", GoVersion:"go1.13.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.36", GitCommit:"34a615f32e9a0c9e97cdb9f749adb392758349a6", GitTreeState:"clean", BuildDate:"2020-04-06T16:33:17Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**

istioctl apply manifest

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

**Comment by howardjohn** [comment]
I think you'll need to configure a destination rule , it won't auto detect tls because it doesn't know if the external name destination is in the cluster or not

**Comment by satishmane** [comment]
@howardjohn 
thanks for the reply

I tried that already. I created below rule in foo namespace where my destination lies.

kubectl apply -n foo -f - <<EOF
apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "spc-mtls"
  namespace: foo
spec:
  mtls:
    mode: STRICT
EOF

kubectl apply -n foo -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: testmtls
  namespace: foo
spec:
  host: x.foo.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
EOF

I have below external name service in bar namespace pointing to x service in foo namespace.

kubectl apply -n bar -f - <<EOF
apiVersion: v1
kind: Service
metadata:
  name: testx
  namespace: bar
spec:
  externalName: x.foo.svc.cluster.local
  type: ExternalName
  selector:
    app: x
EOF

kubectl exec -it pods/sleep-74dfb4fbc4-99sfq -n bar -c sleep -- sh
/ # curl "http://testx:8080/helloworld"
upstream connect error or disconnect/reset before headers. reset reason: connection termination/ # 
/ # 
/ # curl -v "http://testx:8080"
*   Trying 172.19.51.149:8080...
* Connected to mts (172.19.51.149) port 8080 (#0)
> GET /helloworld HTTP/1.1
> Host: testx:8080
> User-Agent: curl/7.69.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 503 Service Unavailable
< content-length: 95
< content-type: text/plain
< date: Tue, 23 Jun 2020 06:09:52 GMT
< server: envoy
< 
* Connection #0 to host mts left intact
upstream connect error or disconnect/reset before headers. reset reason: connection termination

**Comment by satishmane** [comment]
Yes, destination rule resolved. I was applying destination rule to destination clusterIP service instead of externalname type service in source namespace. Below rule solved, i.e. destination rule applied to externalname service in foo namespace.

kubectl apply -n foo -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
name: testmtls
namespace: foo
spec:
host: testx.foo.svc.cluster.local
trafficPolicy:
tls:
mode: ISTIO_MUTUAL
EOF

As per documentation says, peerauthentication at namespace level does not need destination rule and automtls takes care of detecting. So I was not sure destination rule would resolve it.

But as you suggested, I tried destination rule on external name type service... it worked..

**Comment by howardjohn** [comment]
automtls only works when the destination is part of the cluster. With external name we do not know it is, it could be going to google.com for all we know, so you need to do it manually
