### ISSUE TITLE
why is destinationRule designed for server side

### ISSUE THREAD

**Issue by wansuiye** [istio/istio#24890]
In SDK usage, each client’s config may be different, even though requesting the same upstream, such as the circuit breakers params or connection pool params. Although destinationRule works on the client side, the destinationRule is server oriented and is designed to be a generic configuration. If clients use different config, one subset needs to be created for each client, while the labels are all the same. so i don’t think destinationRule has considered this scene. 

**Describe the feature request**

**Describe alternatives you've considered**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
I am not sure what you mean. If you have a service in namespace foo and a client in namespace bar, you can just define a destination rule in namespace bar to configure settings for connecting the the service. You do not need subsets to define client overrides

**Comment by wansuiye** [comment]
> I am not sure what you mean. If you have a service in namespace foo and a client in namespace bar, you can just define a destination rule in namespace bar to configure settings for connecting the the service. You do not need subsets to define client overrides
"define a destination rule in namespace bar to configure settings for connecting the the service." it is not very flexible, each client in a same namespace may need different settings.
the discussion is here：https://discuss.istio.io/t/circuit-breaker-client-vs-server-side/2720/3
