### ISSUE TITLE
istioctl version - remove exec dependency from istio-system pods

### ISSUE THREAD

**Issue by infa-ddeore** [istio/istio#24899]
**Describe the feature request**
`istioctl version` discovers the istio-system pods and exec into each of them to get the control plane versions.
Most of the k8 environments are restricted to the users for specific namespaces, such users need to be given access to exec inside istio-system pods, this is a concern from the security team because then users can exec into pod, list/ cat the directories and can get the root key and certs.

Also doing exec into each istio-system pods makes it slower.

**Describe alternatives you've considered**
I am not completely sure about this but if istiod.istio-system service can expose this information then istioctl can do port-forward and get the details.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[x] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by esnible** [comment]
This is a duplicate of https://github.com/istio/istio/issues/24331 and will be delivered in 1.7.
