### ISSUE TITLE
Redis 104, log report UO

### ISSUE THREAD

**Issue by inewlife** [istio/istio#24892]
**Bug description**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Normal use

**Steps to reproduce the bug**
Create a deployment containing python connection redis , After running online for a few days，python raise Exception ConnectionError: Error while reading from socket: (104, 'Connection reset by peer;

Then I saw the UO flag from the sidecar log 

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istio 1.3    istio-proxyv2:1.3.0
**How was Istio installed?**
helm 
**Environment where bug was observed (cloud vendor, OS, etc)**
Ubuntu

**Comment by howardjohn** [comment]
UO means circuit breaker was tripped, we will need more information about your configuration and environment. Do you have circuit breaking configured

**Comment by howardjohn** [comment]
Oh you are in a deprecated Istio version that has it enabled by default. Can you please upgrade to a supported version?

**Comment by inewlife** [comment]
I don't set route config the outside redis, 
Does istio have a global circuit breaker

**Comment by inewlife** [comment]
I found a lot of CLOSE_WAIT in the istio-proxy container
![image](https://user-images.githubusercontent.com/13137254/86730877-8d1bee00-c061-11ea-925a-ae508ff0c611.png)

**Comment by howardjohn** [comment]
Yes as mentioned, this is fixed in latest supported versions (see https://istio.io/latest/news/support/announcing-1.3-eol-final/). There is a default in older versions. See https://istio.io/latest/docs/reference/config/networking/destination-rule/ for overriding this, or upgrade please. Thanks!
