### ISSUE TITLE
Change upstream in Lua Filter

### ISSUE THREAD

**Issue by dozer47528** [istio/istio#24895]
**Describe the feature request**

As an Edge Routier, we have Lua script which will decide the upstream by HTTP headers, path, etc.

In Nginx we can write Lua script like this: `ngx.var.upstream = "new_upstream";`

In envoy, there is an alternative solution which can implement this: https://medium.com/safetycultureengineering/edge-routing-with-envoy-and-lua-621f3d776c57

So how can we implement this by using Istio?

**Describe alternatives you've considered**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
Istio supports configuring Lua filters - see https://istio.io/latest/docs/reference/config/networking/envoy-filter/ which has an example

In the future, please open questions at https://discuss.istio.io/, the issues page is for bugs/feature requests.
