### ISSUE TITLE
Support replace kubeconfig for istiod

### ISSUE THREAD

**Issue by irisdingbj** [istio/istio#24897]
This is to support scenario that istiod on cluster 1 will mange cluster 2 directly. In this case, we can point istiod's KUBECONFIG to cluster2.

Proposed steps:
1. create cm from cluster 2's kubeconfig  in cluster 1
2. mount this cm into istiod pod in cluster 1 
3. add logic to use this as kubeconfig if the mount path specified in step 2 exists 

@linsun @howardjohn  any comments for this approach?

**Comment by linsun** [comment]
Seems reasonable to me.  @howardjohn @costinm thoughts?

Background: this is an attempt to simplify https://github.com/istio/istio/pull/24503 as we don't want istiod to listen to any workloads or istio resources on cluster 1.

**Comment by howardjohn** [comment]
1) you should make it a secret
2) you should not require any code changes to do this, it's already configurable via the operator API I think

But yes sgtm
