### ISSUE TITLE
CredentialName is not valid option for ClientTLSSettings

### ISSUE THREAD

**Issue by axsaucedo** [istio/istio#24908]
**Bug description**
When creating a Destination rule with a Traffic policy containing a ClientTLSSettings, the CRD outlines an option to provide CredentialName. However when this option is provided, the validation webhook rejects the creation of the resource.

More specifically, the [ClientTLSSettings struct](https://github.com/istio/api/blob/master/networking/v1alpha3/destination_rule.pb.go#L1784) has a [CredentialName](https://github.com/istio/api/blob/master/networking/v1alpha3/destination_rule.pb.go#L1812) attribute that is not currently taken as a valid attribute.

[ X ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

When providing CredentialName inside a ClientTLSSettings attribute, the validation webhook shouldn't error.

**Steps to reproduce the bug**

If you try to create a destination rule with a credentialName it will error out:

```
kind: DestinationRule
metadata:
  name: destrule-name
spec:
  host: somehost.namespace.svc.cluster.local
  trafficPolicy:
    tls:
      mode: SIMPLE
      credentialName: secretname-cert
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

client version: 1.6.3
control plane version: 1.6.3
data plane version: 1.6.3 (2 proxies)

**How was Istio installed?**

With `istioctl install`

**Environment where bug was observed (cloud vendor, OS, etc)**

Linux env, Kubernetes 1.16 - `kubectl version` output:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:47:40Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:18:29Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by nschhina** [comment]
`CredentialName` is not a feature that's supported yet. Please look at https://github.com/istio/istio/issues/14039. It was added recently to add support to implementing this feature which should be out by 1.7 release

**Comment by nschhina** [comment]
Also please note that unless the specific "field" is specified on istio.io it's probably not supported. In short istio.io is the source of truth

**Comment by axsaucedo** [comment]
Right, ok makes sense @nschhina thank you for the clarification. Often with k8s projects checking CRDs and code is the usual way of navigating through quite a few kubernetes frameworks and projects so it's good to get clarification this feature (and any others not mentioned in the docs) are not enabled. THanks!
