### ISSUE TITLE
Elasticsearch 7.7.1 Not Working with Istio 1.5.4

### ISSUE THREAD

**Issue by ethai** [istio/istio#24904]
**Bug description**

Elasticsearch will not come up healthy when sidecar proxy gets added to the helm installation.

[ ] Configuration Infrastructure
[ ] Docs
[x ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Elasticsearch installs and both elasticsearch and istio-proxy starts and runs successful. 

**Steps to reproduce the bug**

- run istio-injection labeling against the namespace

- run helm install of elasticsearch with default values

- installation is a hit and miss i might have gotten.  i've intermittently got a few installation of elasticsearch + istio to work, but i'm completely stumped to make it a more repeatable process.

I've also tried applying this but still no luck

https://istio.io/latest/faq/applications/#elasticsearch

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

Helm 3.2
kubectl -
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-gke.15", GitCommit:"9cabee15e0922c3b36724de4866a98f6c2da5e6a", GitTreeState:"clean", BuildDate:"2020-05-01T21:47:04Z", GoVersion:"go1.13.8b4", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**

As part of the GKE add-on feature

**Environment where bug was observed (cloud vendor, OS, etc)**

GKE

**Comment by ethai** [comment]
I've tried some previous reported issues and thought it may have been fixed, but with no luck

[1] https://github.com/istio/istio/issues/14662#issuecomment-552094406

**Comment by howardjohn** [comment]
@ethai we need more information. Right now your issue just says "elasticsearch does not work" but does not have any info, logs, etc about what is going wrong. it also does not specify which Istio version you are using - I suspect an EOL'd version which we cannot support here: https://istio.io/latest/news/support/announcing-1.4-eol-final/

**Comment by ethai** [comment]
@howardjohn , my apologies on the lack of clarity info here.  Ultimately, I learned Elasticsearch specifically required the following annotations to be included in order for it to work in the mesh. 

traffic.sidecar.istio.io/excludeInboundPorts
traffic.sidecar.istio.io/excludeOutboundPorts

**Comment by howardjohn** [comment]
Thanks for the update!
