### ISSUE TITLE
istioctl: Add server version output to istioctl version

### ISSUE THREAD

**Issue by metacosm** [istio/istio#2491]
One way to currently retrieve the installed istio version is to run: `kubectl get deployment istio-pilot -o yaml -n istio-system | grep image:`. It would be, however, more intuitive to get that information when running `istioctl version`.

**Comment by ayj** [comment]
Image version can be dimensioned by component (e.g. pilot, mixer, ca) and workload instance (e.g. multiple image versions may be in-flight during Istio runtime upgrade). There may also be cases where the control plane is not running in a k8s cluster. An explicit source for version information (e.g. mesh properties CRD or HTTP endpoint) may be preferable over inferred version from various image names.

**Comment by christian-posta** [comment]
Yah, +1 to having a explicit source for version info

**Comment by metacosm** [comment]
It would also be interesting if that version output would also output which version of Envoy is being used.

**Comment by NicoXcc** [comment]
This was really helpful thanks :
kubectl get deployment istio-pilot -o yaml -n istio-system | grep image: | cut -d ':' -f3 |  head -1

**Comment by jwendell** [comment]
try istioctl version --remote
