### ISSUE TITLE
perf: do not increment push triggers one by one

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#24915]
https://github.com/istio/istio/blob/b0620237499985147dc86026148a1691aa2750be/pilot/pkg/proxy/envoy/v2/monitoring.go#L168-L172

If we have many duplicates here, its slow for opencensus. We can pre-aggregate it possibly?

Profile shows ~3% of cpu spent here

**Comment by knight42** [comment]
I would like to work on this.

/assign

**Comment by howardjohn** [comment]
after a closer look I think it may not be the issue of this loop, rather we record it for each proxy * each push which may he a very high number. We have the same issue for the eds stats

**Comment by knight42** [comment]
@howardjohn do you think it is feasible to change the type of [`Reason` field of `PushRequest`](https://github.com/istio/istio/blob/b0620237499985147dc86026148a1691aa2750be/pilot/pkg/model/push_context.go#L221-L225) to `map[TriggerReason]int` so that we can do aggregation and get the total trigger counts of each reason easily?

**Comment by jronak** [comment]
I see at most one reason part of the TriggerReason list, could we keep the same behaviour and listen on buffered channel in recordPushTriggers?
Although this won't immediately bring down the cpu, we could unblock the push (most of the time).

Also, could you share or point me to the cpu profile of this section?

**Comment by howardjohn** [comment]
![2020-03-11_17-28-38](https://user-images.githubusercontent.com/623453/98058624-0baf4f00-1dfa-11eb-858f-2a006fb60c2b.png)
example of VERY extreme case where I close 10k connections at once. We are spending 3 CPU and 3 minutes JUST recording the push triggers.

So probably 99.99% of the time we record one, but in rare cases we record 100ks and it gets horrible
