### ISSUE TITLE
istioctl dashboard exits immediately on master

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#24914]
This might be my environment - more testing needed

I noticed this is now exiting immediately, so it doesn't actually work since the port forward is closed. Might be due to @nmittler or @esnible or my own recent work in port forward

**Comment by esnible** [comment]
@nmittler I see the same thing and it is caused by https://github.com/istio/istio/pull/24650

**Comment by esnible** [comment]
@nmittler The original blocked using `<-fw.StopChannel` until the use pressed control-C.  The new version does not.

`istioctl dashboard` lacked a non-mock test.  Created https://github.com/istio/istio/issues/24943 for that.
