### ISSUE TITLE
Kiali traffic graph broken in 1.5.5

### ISSUE THREAD

**Issue by cbron** [istio/istio#24924]
**Bug description**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Install istio 1.5.5, add bookinfo app, traffic in kiali. 

**Steps to reproduce the bug**

```
<Setup cluster, download istio 1.5.5 and cd to it>
k create ns istio-system
helm install ./istio-init --name istio-init --namespace istio-system
helm install ./istio      --name istio      --namespace istio-system  --set kiali.enabled=true
<install bookinfo app and send traffic to it on loop>
<create kiali secret>
istioctl dashboard kiali
```

You can fix the issue by changing kiali version to 1.18, everything works then, but 1.18 is not meant for 1.5.x. 

When you check logs on kiali pod you get: 

```
W0623 23:57:34.495836       1 istio.go:217] Skipping {destination_service="reviews.default.svc.cluster.local", destination_service_name="reviews", destination_service_namespace="default", destination_workload="reviews-v3", destination_workload_namespace="default", request_protocol="http", response_code="200", response_flags="-", source_workload="productpage-v1", source_workload_namespace="default"}, missing expected TS labels

W0623 23:57:34.496552       1 istio.go:217] Skipping {destination_service="details.default.svc.cluster.local", destination_service_name="details", destination_service_namespace="default", destination_workload="details-v1", destination_workload_namespace="default", request_protocol="http", response_code="200", response_flags="-", source_workload="productpage-v1", source_workload_namespace="default"}, missing expected TS labels
```

This same Kiali version works with 1.4.x, so something in 1.5.x is breaking it. Guessing the metrics have changed. 

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

control plane version: 1.5.5
helm: v2.16.1

**How was Istio installed?**

Helm

**Related** 

https://github.com/kiali/kiali/issues/1007#issuecomment-646314467

**Comment by aavileli** [comment]
Missing metrics from istio 1.5.x for kiali 1.15.x `expected` TS labels` is there a set of metrics that are needed kiali wants ?

**Comment by cbron** [comment]
Kiali stopped publishing to dockerhub and then apparently started again. [1.17 exists in quay](https://quay.io/repository/kiali/kiali?tab=tags) but [not in dockerhub](https://hub.docker.com/r/kiali/kiali/tags?page=1&name=1.17). I never tested this issue with it though, only 1.15 and 1.18.

**Comment by aavileli** [comment]
@cbron I think they fixed it in 1.17 they have a boolean flag that detects which version of the v1 or v2 metrics is getting used https://github.com/kiali/kiali/issues/2950. As 1.18 fixes the issue but is not supposed to be used with istio 1.5 as the crds have changed and validation features in kiali will not work. I am facing the same issue in our rancher cluster.

**Comment by courcelm** [comment]
The graph is working with quay.io/kiali/kiali:v1.17,  Istio 1.5.8 on Rancher 2.4.5

**Comment by CarlosPerdomo** [comment]
> The graph is working with quay.io/kiali/kiali:v1.17, Istio 1.5.8 on Rancher 2.4.5

This work for me with Kiali v1.18.1 from Docker Hub

**Comment by CarlosPerdomo** [comment]
Istio: 1.5.8
Rancher Server: 2.4.5.

For me work with Kiali v1.18.1. But show this warnings.

![image](https://user-images.githubusercontent.com/5383188/89534091-09693480-d7ba-11ea-9d25-1f9d67c44002.png)
Cluster Info.
![image](https://user-images.githubusercontent.com/5383188/89534147-1d149b00-d7ba-11ea-94e9-e33a379537f0.png)

**Comment by haimari** [comment]
Same issue,
using Kiali 1.17 with Istio 1.5.8 (rancher 2.45) works for me.

**Comment by aavileli** [comment]
have tested version quay.io/kiali/kiali:v1.17 and works with Rancher now

**Comment by cbron** [comment]
This has been resolved *in Rancher* with 1.5.9. Please use [the linked Rancher issue](https://github.com/rancher/rancher/issues/28109) to further comment on anything surrounding it, or open a new Rancher issue.
I will leave this issue open to handle the Istio case, please restrict any further comments to that.

**Comment by douglas-reid** [comment]
I think it is fair to say that this is a kiali issue (that was resolved in subsequent kiali releases). @jshaugn is updating the default values to point at 1.17 or 1.18 in the 1.5 branch the best way forward here?

**Comment by howardjohn** [comment]
Given https://istio.io/latest/news/support/announcing-1.5-eol-final/ I think there is no action here. Users can upgrade kiali themselves though, or preferably update Istio as well.
