### ISSUE TITLE
Modify control plane logging levels with istioctl

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#24922]
Currently we have `istioctl pc log` for Envoy. It would be useful to have this for Istiod as well (through controlz interface)

**Comment by piotrkpc** [comment]
I'd like to work on this if possible and if this is not urgent. Still learning the project so it might take some time.

**Comment by howardjohn** [comment]
Sure, sounds great. One thing I realized is that the `proxy-config` subcommand is for proxy configuration.. which Istiod is not. Not sure how we should organize it. @esnible ?

But basically the implementation is to hit the localhost:9867 endpoint and then I *think* there is some endpoint there that will allow this through the API - currently there is just a UI

**Comment by howardjohn** [comment]
`curl localhost:9876/scopej/ads -X PUT -d '{"output_level":"debug"}'` is the api

**Comment by piotrkpc** [comment]
> `curl localhost:9876/scopej/ads -X PUT -d '{"output_level":"debug"}'` is the api

Yep, I think I have all I need. I'll post some code during the weekend (not working on Istio fulltime). Thanks.

**Comment by esnible** [comment]
For 1.8, the ControlZ :9876 port will be protected by JWT and TLS.
This means this command should use the pattern of `experimental proxy-status` and generate and use a token.

**Comment by piotrkpc** [comment]
> For 1.8, the ControlZ :9876 port will be protected by JWT and TLS.
> This means this command should use the pattern of `experimental proxy-status` and generate and use a token.

@esnible do you refer to this PR https://github.com/istio/istio/pull/26726 ?

**Comment by esnible** [comment]
At a recent meeting, someone (@costinm ?) said that port 9876 would not be exposed plaintext.  We need to coordinate with the control plane.  The changes should go into the servers and _istioctl_ at around the same time.

It is your choice if we should add a `--plaintext` flag, they way we do in the PR you mention, to allow us to invoke control-z on 1.7 and 1.8-pre-alpha control planes.  We probably don't need this, as it is a rarely-used feature.

**Comment by howardjohn** [comment]
I do not agree @esnible . Unlike other debugging tools, this one should be touched exclusively by the istiod owner. This means, for a "out of cluster istiod", this command would never be used. Exposing 9867 on TLS/JWT doesn't make sense to me -- its already `localhost`, and should continue to be.

**Comment by esnible** [comment]
@howardjohn Should this item be part of milestone 1.8?  Let's assume port :9867 is not exposed, how should istioctl modify control plane log levels?

**Comment by howardjohn** [comment]
@esnible I am a bit confused. AFAIK this is done: https://github.com/istio/istio/pull/25276. It works exactly how I would expect. What work do you think should be done for 1.8?
