### ISSUE TITLE
SIMPLE TLS Origination not using file based SDS

### ISSUE THREAD

**Issue by nschhina** [istio/istio#24921]
File-based SDS featured introduced in https://github.com/istio/istio/pull/22019 Issue Ref: https://github.com/istio/istio/issues/21833
does not do file-based SDS for root cert during SIMPLE TLS origination but uses file-based SDS for MUTUAL and ISTIO_MUTUAL modes. Integration tests for file based rotation are also missing, how much test coverage do we have? If feature is already production grade, it's missing task/security example for istio.io

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by nschhina** [comment]
cc: @myidpt  @JimmyCYJ

**Comment by JimmyCYJ** [comment]
Thanks for filing this issue. @nschhina 
@howardjohn @ramaraochavali

**Comment by howardjohn** [comment]
https://github.com/istio/istio/pull/25028 done
