### ISSUE TITLE
feat(dashboard): need to design a dashboard for monitoring Envoy extensions

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio#24920]
**Describe the feature request**
As we transition to an ecosystem for extensions (Wasm) deployed to proxies as part of Istio, we should have a way to monitor their function within a mesh - how many are active, configured, available, failed, etc.

This request is for a design + implementation of such a dashboard. It could be included in an existing dashboard, or separate.

**Describe alternatives you've considered**
N/A

[ X ] Policies and Telemetry
[ X ] User Experience

**Additional context**

**Comment by esnible** [comment]
@douglas-reid Can you retarget or assign someone?

**Comment by esnible** [comment]
Let's retarget this for 1.8.

Do you have thoughts about what it would look like?

It would be good to have something that combines a view of EnvoyFilter, proxy-status going stale, and logging produced by Envoy for WASM extensions.

**Comment by douglas-reid** [comment]
@esnible we need to see what metrics get exported when the dust settles. I don't know that we want to expose anything re: envoy filters, but perhaps. I was more thinking proxy-wasm info on success/errors in loading extensions, number of invocations of extensions, etc.

@mandarjog thoughts here?

**Comment by carolynhu** [comment]
close this issue, as this is a duplication of issue 25843
