### ISSUE TITLE
ISTIO Sidecar proxy not able to inject in pod for kubernetes 1.18.4

### ISSUE THREAD

**Issue by a2z-ice** [istio/istio#24934]
I'm getting error logs from istiod:
<pre><code>
2020-06-24T10:12:33.287279Z     info    validationController    Reconcile(enter): retry dry-run creation of invalid config
2020-06-24T10:13:03.294601Z     info    validationController    Not ready to switch validation to fail-closed: dummy invalid config not rejected
2020-06-24T10:13:03.295098Z     info    validationController    validatingwebhookconfiguration istiod-istio-system (failurePolicy=Ignore, resourceVersion=40984) is up-to-date. No change required.
2020-06-24T10:13:03.295146Z     info    validationController    Reconcile(enter): retry dry-run creation of invalid config
2020-06-24T10:13:33.301584Z     info    validationController    Not ready to switch validation to fail-closed: dummy invalid config not rejected
2020-06-24T10:13:33.302056Z     info    validationController    validatingwebhookconfiguration istiod-istio-system (failurePolicy=Ignore, resourceVersion=40984) is up-to-date. No change required.
</code></pre>

ISTIO pods, service and deployment details:
<pre><code>
NAME                                        READY   STATUS    RESTARTS   AGE
pod/istio-ingressgateway-5c48fdd978-q8bff   1/1     Running   0          14m
pod/istiod-646f7dc6b5-g6czq                 1/1     Running   0          14m
pod/prometheus-5bc697c5ff-5mfpn             2/2     Running   0          14m

NAME                           TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                                                                                                                                      AGE
service/istio-ingressgateway   LoadBalancer   10.102.92.213   <pending>     15020:30986/TCP,80:31413/TCP,443:32499/TCP,15029:31449/TCP,15030:31161/TCP,15031:31391/TCP,15032:32341/TCP,15443:30191/TCP,31400:30072/TCP   14m
service/istio-pilot            ClusterIP      10.111.71.228   <none>        15010/TCP,15011/TCP,15012/TCP,8080/TCP,15014/TCP,443/TCP                                                                                     14m
service/istiod                 ClusterIP      10.105.64.65    <none>        15012/TCP,443/TCP                                                                                                                            14m
service/prometheus             ClusterIP      10.107.220.77   <none>        9090/TCP                                                                                                                                     14m

NAME                                   READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/istio-ingressgateway   1/1     1            1           14m
deployment.apps/istiod                 1/1     1            1           14m
deployment.apps/prometheus             1/1     1            1           14m

NAME                                              DESIRED   CURRENT   READY   AGE
replicaset.apps/istio-ingressgateway-5c48fdd978   1         1         1       14m
replicaset.apps/istiod-646f7dc6b5                 1         1         1       14m
replicaset.apps/prometheus-5bc697c5ff             1         1         1       14m

NAME                                                       REFERENCE                         TARGETS         MINPODS   MAXPODS   REPLICAS   AGE
horizontalpodautoscaler.autoscaling/istio-ingressgateway   Deployment/istio-ingressgateway   <unknown>/80%   1         5         1          14m
horizontalpodautoscaler.autoscaling/istiod 

K8S Cluster details:
NAME             STATUS   ROLES    AGE     VERSION   INTERNAL-IP     EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION                CONTAINER-RUNTIME
cent-master140   Ready    master   4h48m   v1.18.4   192.168.0.140   <none>        CentOS Linux 7 (Core)   3.10.0-1127.13.1.el7.x86_64   docker://19.3.12
cent-node141     Ready    <none>   4h45m   v1.18.4   192.168.0.141   <none>        CentOS Linux 7 (Core)   3.10.0-1127.13.1.el7.x86_64   docker://19.3.12
</code></pre>

**Comment by Fryuni** [comment]
Just got the exact same thing. Fresh installed istio using `istioctl manifest apply -w -s profile=default` on GKE Rapid Channel

**Comment by howardjohn** [comment]
Do you have firewall rules set up blocking communication from the master? Can you run the steps in https://github.com/istio/istio/wiki/Troubleshooting-Istio#diagnostics?

**Comment by Fryuni** [comment]
Looks like that was the problem on my case. Was following another guide without the note about Private GKE Clusters

**Comment by howardjohn** [comment]
Closing as this seems fixed by firewall
