### ISSUE TITLE
Istio 1.5.4 istio-root-ca-cert not getting created

### ISSUE THREAD

**Issue by rajivml** [istio/istio#24931]
HI, 

creating an other issue since  https://github.com/istio/istio/issues/22463 was closed without any resolution, we are facing the same problem, in version 1.5.4, but istiod restart fixed the problem. before restart even though multiple namespaces were created, configmap was not created in those namespaces

If you see the below screenshot, as soon as we killed/restart the istiod pod, the cert got injected into all the namespaces

![Capture](https://user-images.githubusercontent.com/65596254/85501083-47dbd300-b602-11ea-94b7-ab8010a42407.PNG)

_Originally posted by @Mdirfan6 in https://github.com/istio/istio/issues/22463

**Comment by howardjohn** [comment]
This should be fixed in 1.5.6, can you please upgrade? Thanks! See  https://github.com/istio/istio/issues/22463

**Comment by rajivml** [comment]
Thanks for the update @howardjohn , we will check that
