### ISSUE TITLE
Istio Pilot reports "Endpoint without pod xx.xx.xx.xx <pod-name>.<pod-namespace>" when there is huge deployment churn.

### ISSUE THREAD

**Issue by nishanth-pinnapareddy** [istio/istio#24950]
**Bug description**
We have a deployment that exposes multiple ports (6) and HPA attached to this deployment. When HPA scales up the deployment to 500 replicas and scales down ~50 replicas within a span of 5 min, Istio pilots reports multiple errors "Endpoint without pod xx.xx.xx.xx <pod-name>.<pod-namespace>" and struck in this state. After this pilots are not pushing new config to sidecars and not even handling any other events. When this happens many services in mesh failed to communicate due to stale endpoints. To mitigate the issue we have to bounce pilot pods and everything comes back to a normal state.  

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ X] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Expected to pilot to handle the above scenario and recover by itself instead of processing events.

**Steps to reproduce the bug**
To reproduce the above scenario. Follow the below steps.
-  Create a deployment that exposes at least 2 ports with a lower replica count say 10.
-  Edit the deployment and set the replicas 500 and give it 5 min.
-  After 5 min, bring back the replicas 10.
-  Now you should see a lot of "Endpoint without pod ip" errors. 

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
Istio Version: 1.4.9
Kubectl version
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.10", GitCommit:"575467a0eaf3ca1f20eb86215b3bde40a5ae617a", GitTreeState:"clean", BuildDate:"2019-12-11T12:32:32Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
Helm version: v2.14.1

**How was Istio installed?**
Helm charts

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS, Ubuntu

**Comment by sureshvis** [comment]
we ran into exact issue
