### ISSUE TITLE
Service entry for one service works only in resolution: STATIC mode

### ISSUE THREAD

**Issue by dklsaw** [istio/istio#24968]
Issue description:
For some reasons service entry for service works only if resolution is set to STATIC, but at the same time service entry for another services into the same cluster works well with DNS resolution 

pods placement by clusters: 
cluster0 - productpage, details
cluster1 - reviews, ratings

Clusters configuration:
both clusters are on AWS EC2 instances, replicated control plane (coredns into kube-system)
istio 1.5.6

Issue was not reproduced on GKE+GKE clusters replicated control plane (kube-dns into kube-system).

Issue was reproduced on cluster-on-AWS-EC2-instances+GKE (GKE from above, just configured SE to use service on GKE).
in this case SE for ratings-test was configured to connect to GKE cluster were ratings-test is up and running

======================
resolution: DNS to GKE cluster

kubectl --kubeconfig gke_aws_default_cluster-0.conf get se ratings-test -o yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.istio.io/v1alpha3","kind":"ServiceEntry","metadata":{"annotations":{},"name":"ratings-test","namespace":"default"},"spec":{"addresses":["240.0.0.100"],"endpoints":[{"address":"asm20.bsdh.net","network":"external","ports":{"http1":15443}},{"address":"istio-egressgateway.istio-system.svc.cluster.local","ports":{"http1":15443}}],"hosts":["ratings-test.default.global"],"location":"MESH_INTERNAL","ports":[{"name":"http1","number":9080,"protocol":"http"}],"resolution":"DNS"}}
  creationTimestamp: "2020-06-25T09:03:40Z"
  generation: 1
  name: ratings-test
  namespace: default
  resourceVersion: "2778095"
  selfLink: /apis/networking.istio.io/v1beta1/namespaces/default/serviceentries/ratings-test
  uid: f0e94a91-b3b6-47ed-9979-f42b52657eb8
spec:
  addresses:
  - 240.0.0.100
  endpoints:
  - address: asm20.bsdh.net
    network: external
    ports:
      http1: 15443
  - address: istio-egressgateway.istio-system.svc.cluster.local
    ports:
      http1: 15443
  hosts:
  - ratings-test.default.global
  location: MESH_INTERNAL
  ports:
  - name: http1
    number: 9080
    protocol: http
  resolution: DNS

nslookup asm20.bsdh.net
Server:         169.254.169.254
Address:        169.254.169.254#53

Non-authoritative answer:
Name:   asm20.bsdh.net
Address: 35.205.32.60

root@details-v1-74f858558f-7zn57:/opt/microservices# curl -vvv  ratings-test.default.global:9080/health
*   Trying 240.0.0.100...
* TCP_NODELAY set
* Connected to ratings-test.default.global (240.0.0.100) port 9080 (#0)
> GET /health HTTP/1.1
> Host: ratings-test.default.global:9080
> User-Agent: curl/7.52.1
> Accept: */*
> 
< HTTP/1.1 503 Service Unavailable
< content-length: 91
< content-type: text/plain
< date: Thu, 25 Jun 2020 08:45:23 GMT
< server: envoy
< 
* Curl_http_done: called premature == 0
* Connection #0 to host ratings-test.default.global left intact
upstream connect error or disconnect/reset before headers. reset reason: connection failure
======================

The same service from same GKE cluster
resolution: STATIC

kubectl --kubeconfig gke_aws_default_cluster-0.conf get se ratings-test -o yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.istio.io/v1alpha3","kind":"ServiceEntry","metadata":{"annotations":{},"name":"ratings-test","namespace":"default"},"spec":{"addresses":["240.0.0.100"],"endpoints":[{"address":"35.205.32.60","network":"external","ports":{"http1":15443}},{"address":"10.1.240.197","ports":{"http1":15443}}],"hosts":["ratings-test.default.global"],"location":"MESH_INTERNAL","ports":[{"name":"http1","number":9080,"protocol":"http"}],"resolution":"STATIC"}}
  creationTimestamp: "2020-06-25T08:46:47Z"
  generation: 1
  name: ratings-test
  namespace: default
  resourceVersion: "2774218"
  selfLink: /apis/networking.istio.io/v1beta1/namespaces/default/serviceentries/ratings-test
  uid: 20d1235f-91c9-49b0-89fa-b39fa465a977
spec:
  addresses:
  - 240.0.0.100
  endpoints:
  - address: 35.205.32.60
    network: external
    ports:
      http1: 15443
  - address: 10.1.240.197
    ports:
      http1: 15443
  hosts:
  - ratings-test.default.global
  location: MESH_INTERNAL
  ports:
  - name: http1
    number: 9080
    protocol: http
  resolution: STATIC

root@details-v1-74f858558f-7zn57:/opt/microservices# curl -vvv  ratings-test.default.global:9080/health
*   Trying 240.0.0.100...
* TCP_NODELAY set
* Connected to ratings-test.default.global (240.0.0.100) port 9080 (#0)
> GET /health HTTP/1.1
> Host: ratings-test.default.global:9080
> User-Agent: curl/7.52.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< content-type: application/json
< date: Thu, 25 Jun 2020 08:46:54 GMT
< x-envoy-upstream-service-time: 636
< server: envoy
< transfer-encoding: chunked
< 
* Curl_http_done: called premature == 0
* Connection #0 to host ratings-test.default.global left intact
{"status":"Ratings is healthy"}

======================

But another service works well with service entry with DNS resolution enabled.

kubectl --kubeconfig gke_aws_default_cluster-0.conf get se reviews -o yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  creationTimestamp: "2020-06-24T15:23:49Z"
  generation: 1
  name: reviews
  namespace: default
  resourceVersion: "2534713"
  selfLink: /apis/networking.istio.io/v1beta1/namespaces/default/serviceentries/reviews
  uid: e58a53cc-7548-4b5c-8751-ec39e4e65f93
spec:
  addresses:
  - 240.0.0.20
  endpoints:
  - address: xxxxxxxxxxxxxxxxxxxxxxxxxx-xxxxxxxxx.us-west-2.elb.amazonaws.com
    ports:
      http1: 15443
  - address: istio-egressgateway.istio-system.svc.cluster.local
    ports:
      http1: 15443
  hosts:
  - reviews.default.global
  location: MESH_INTERNAL
  ports:
  - name: http1
    number: 9080
    protocol: http
  resolution: DNS

root@details-v1-74f858558f-7zn57:/opt/microservices# curl -vvv  reviews.default.global:9080/health
*   Trying 240.0.0.20...
* TCP_NODELAY set
* Connected to reviews.default.global (240.0.0.20) port 9080 (#0)
> GET /health HTTP/1.1
> Host: reviews.default.global:9080
> User-Agent: curl/7.52.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< x-powered-by: Servlet/3.1
< content-type: application/json
< date: Thu, 25 Jun 2020 09:00:19 GMT
< content-language: en-US
< content-length: 32
< x-envoy-upstream-service-time: 41
< server: envoy
< 
* Curl_http_done: called premature == 0
* Connection #0 to host reviews.default.global left intact

The same (HTTP/1.1 200 OK) if point this service entry to GKE cluster (using resolution DNS)

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by sk-ss** [comment]
I had the same issue with my application, but it was placed on kubernetes clusters on our DC, so this issue is not related to clouds or infrastructure.
