### ISSUE TITLE
Consider/investigate an issues REPO for public filed issues

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#250]
per k8s:
"""
I noticed that you made access to github issue creation open to the public.  Github recommends that you make a separate repo for public-filed issues.  Public-filed issues can get copied to internal issues once triaged by developers.  This works better with Githubs permission system.  We ignored this advice for Kubernetes, and regret it. 
"""

**Comment by mandarjog** [comment]
@ldemailly @mandarjog

**Comment by ldemailly** [comment]
cc @geeknoid

**Comment by ldemailly** [comment]
it's there: https://github.com/istio/issues/issues
