### ISSUE TITLE
Users unable to access service through Ingress controller without a RequestAuthentication resource

### ISSUE THREAD

**Issue by rolandkool** [istio/istio#25024]
**Bug description**
Not sure if this is a bug or working as designed, but here goes:

Situation:
An NGINX Ingress controller with a vhost (ingress) that opens up access to deploymentX.
deploymentX has a service and an authorization policy selecting it an allowing all access from the namespace it runs in and the namespace the NGINX Ingress controller runs in. Access is done via a namespace filter.
There is *no* request authentication in place.

When a *user* accesses deploymentX through a browser via the NGINX Ingress controller, a `RBAC denied` message is returned. I could work around this by allowing the user via a User-Agent header rule.

Why is this? How is a request coming from a user vs from a service discovered?

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Because there is no RequestAuthentication, I would expect the user be able to reach the service because the NGINX controller itself is allowed.

**Steps to reproduce the bug**
See the bug description.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.6.1

**How was Istio installed?**
istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

**Comment by howardjohn** [comment]
I think the namespace information comes from the mTLS exchange, so possibly if you have no RequestAuthentication there is no mTLS and therefor no namespace info?

**Comment by howardjohn** [comment]
Oh wait that is PeerAuthentication - but probably the same applies
