### ISSUE TITLE
Reference documentation seems to be incomplete

### ISSUE THREAD

**Issue by rolandkool** [istio/istio#25023]
**Bug description**
With the release of Istio 1.6, the former Helm chart options have been removed from the reference documentation page.
However, some parameters that still seem to be valid are now no longer documented in any of the remaining reference documentation pages. The settings do show up in other parts of the documentation.

For example, settings like:
- `values.global.defaultNodeSelector`
- `values.global.remotePilotAddress`
- `values.global.meshId`
- `values.global.sidecarInjectorWebhook.rewriteAppHTTPProbe`
- `values.global.multiCluster.clusterName`

There could be more, but the settings above are currently in use in our setup.

[ ] Configuration Infrastructure
[X] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by rolandkool** [comment]
Other example: `values.global.proxy.image` (got that one from looking at the injector template)

**Comment by shamsher31** [comment]
> With the release of Istio 1.6, the former Helm chart options have been removed from the reference documentation page.
> However, some parameters that still seem to be valid are now no longer documented in any of the remaining reference documentation pages.

Installing Istio with Helm is deprecated and removed.  You can still refer to it in the archived docs. https://istio.io/v1.5/docs/reference/config/installation-options/

**Comment by rolandkool** [comment]
I know and we're not using that. However, some parameters that were documented there, are now no longer documented anywhere. Digging through archived docs is not very user friendly.
