### ISSUE TITLE
Support for regex in paths in an AuthorizationPolicy

### ISSUE THREAD

**Issue by rolandkool** [istio/istio#25021]
**Describe the feature request**
Currently, in a rule within an AuthorizationPolicy, paths can use wildcards, but only at the start, end or whole string. Would be nice to support more complex path expressions like `/path/*/morepath`

See https://istio.io/latest/docs/reference/config/security/authorization-policy/#Rule

**Describe alternatives you've considered**
Alternative is to write out a large list of paths that are allowed and need to keep updating if new paths are added.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by JimmyCYJ** [comment]
@yangminzhu could you please take a look?

**Comment by yangminzhu** [comment]
@rolandkool thanks for creating the feature request, there have been several requests for adding regex support to the authorization policy and I think that is a valid use cases that we should support.

I'm working on a design for a update to the authorization policy to support this and some other use cases for more flexibility and extensibility more generally, will share the proposal once it's ready.

Please let me know if you have any suggestions on the design of the regex support. (we will need some API update to allow specifying the regex and maintain the backward compatibility), thanks.

**Comment by jerry153fish** [comment]
hello @yangminzhu for the `X-Forwarded-For` header can you make specifical case for the cidr, so that user can pass in something like `x.x.x.x/17` instead of `x.x./^(12[0-7]|1[01][0-9]|[1-9]?[0-9])$/` ?

**Comment by yangminzhu** [comment]
@rolandkool , we already have design for this but currently we're putting this on hold to get more feedback about if full regex is really needed.
Your example `/path/*/morepath` can be supported by just wildcard (or glob) matching, I'm wondering do you have any other examples that you think it can only be supported with regex? and do you plan to use it in fields other than just `path` (e.g. headers)? thanks

**Comment by dblackhall-tyro** [comment]
Not rolandkool here, but I'm happy to share my feedback. Glob matching would be suitable for what we want to do. And yes we would only be using path matching.

**Comment by rolandkool** [comment]
@yangminzhu besides the pattern described in the description, I've seen a `/*.js` kind of pattern. I assume this is supported as well?

**Comment by zhranklin** [comment]
@yangminzhu Consider the AntPathMatcher syntax. It's easy to use and satisfies most scenes:

- `?` matches one character
- `*` matches zero or more characters
- `**` matches zero or more directories in a path

e.g.

- com/t?st.jsp — matches com/test.jsp but also com/tast.jsp or com/txst.jsp
- com/*.jsp — matches all .jsp files in the com directory
- com/**/test.jsp — matches all test.jsp files underneath the com path
- org/springframework/**/*.jsp — matches all .jsp files underneath the org/springframework path
- org/**/servlet/bla.jsp — matches org/springframework/servlet/bla.jsp but also org/springframework/testing/servlet/bla.jsp and org/servlet/bla.jsp

References: 

- <https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/util/AntPathMatcher.html>
- The "glob" syntax in: <https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/nio/file/FileSystem.html#getPathMatcher%28java.lang.String%29>

**Comment by zhranklin** [comment]
@yangminzhu And another problem: I think the path to be matched should not contain query string. But istio compares the pattern with the whole path including query string. This is now an issue in our Production use.

**Comment by magoon** [comment]
@yangminzhu wildcard matching, without regex, is sorely needed and will satisfy almost all use cases I can think of for today's modern APIs, e.g. /order/201933/fulfill - please add my vote, and thank you!

**Comment by lechen26** [comment]
@yangminzhu also +1 for the wildcard matching. currently we are struggling with enabling authorizationpolicy for basic endpoints which used basic modern API as @magoon mentioned docs/123/activate  
10x!

**Comment by mstrYoda** [comment]
Is there any update for matching patterns? We are also struggling with path matching for example: "/api/somepath/*/anotherpath"

Is there any workaround for this?

**Comment by zhranklin** [comment]
@mstrYoda We've already been using our custom compiled version with support for regex.

**Comment by nmehlei** [comment]
@zhranklin Is this custom version available somewhere? That would be very helpful

**Comment by zhranklin** [comment]
@nmehlei Our implementation is not graceful enough(though useful) and we are using 1.3 version while the rbac api has changed in versions above 1.5. I think a feasible modification in version 1.5+ would be as follows, just for your reference:

insert the code:

```go
case strings.HasPrefix(v, "regex:"):
    return StringMatcherRegex(v[6:])
```

before `default` clause in function `StringMatcherWithPrefix`:

https://github.com/istio/istio/blob/e658eb6eb69d1887424075edc343952e38f471e5/pilot/pkg/security/authz/matcher/string.go#L60-L72

This means a string with prefix "regex:" will be treated as a regex. e.g. `regex:/x/.*` matches `/x/y`. It's not tested. You can compile and test by your self.

**Comment by nmehlei** [comment]
@yangminzhu Is there any update on this? This seems like an absolute must-have feature for basically any basic REST-based API.

**Comment by bilalahmad99** [comment]
any update on this? we are also looking to include regex in our authorization policy otherwise our list of paths become too long and needs to be added everytime to policy e.g.
```apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: app-authz
spec:
  action: CUSTOM
  provider:
    name: sample-ext-authz-grpc
  rules:
  - to:
    - operation:
        notPaths:
        - /grpc.health.v1.*
        - /xxx.*.v1.*```

**Comment by Jeskz0rd** [comment]
Hey @yangminzhu , any chance to review and maybe update the milestone of this feature?

**Comment by yangminzhu** [comment]
I'm afraid there haven't been too much progress on this, I will unassign myself for now as I'm not working on it.

It looks pretty clear that there are strong community demands for this feature, @liminw I think we should take this into consideration in the next security WG plan. However the 1.12 plan has already completed so the next plan would be 1.13.

Also cc @liwenhao0810 if you are interested in taking this.

**Comment by mstrYoda** [comment]
> I'm afraid there haven't been too much progress on this, I will unassign myself for now as I'm not working on it.
> 
> It looks pretty clear that there are strong community demands for this feature, @liminw I think we should take this into consideration in the next security WG plan. However the 1.12 plan has already completed so the next plan would be 1.13.
> 
> Also cc @liwenhao0810 if you are interested in taking this.

Can you involve me to this please? I am also interestin this too: https://github.com/istio/istio/issues/16585#issuecomment-877011324

**Comment by yangminzhu** [comment]
closed in favor of https://github.com/istio/istio/issues/16585
