### ISSUE TITLE
VM test framework: add envoy logs

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#25037]
Currently when a test fails we dump the logs and some other info. In VMs, `kubectl logs` only shows the logs from iptables/the app. The envoy and agent logs are written to a file, so we don't include them. See https://gcsweb.istio.io/gcs/istio-prow/logs/integ-pilot-k8s-tests_istio_postsubmit/2806/artifacts/pilot-vm-0dd19c60311644e8a4588b/TestVmOSPost/virtual-machine-2-20990-state560341944/ for reference

We should extend the dumping logic to include these if the pod is a VM

**Comment by ZhengzheYang** [comment]
Could you please direct me to the location where the dumping logic is? Is it within the tests or some prow configuration?

**Comment by howardjohn** [comment]
its in the test : https://github.com/istio/istio/blob/e82b8cf7651d2f061b4f7044a4c70128755625df/pkg/test/framework/components/namespace/kube.go#L59

**Comment by howardjohn** [comment]
Done by #25047
