### ISSUE TITLE
Use the ISTIO_VERSION for the envoy version string for istio/proxy: e.g. istio-1.6.3

### ISSUE THREAD

**Issue by jplevyak** [istio/istio#25036]
**Describe the feature request**

**Describe alternatives you've considered**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**
istio/proxy modifies the underlying envoy source, so the version string should represent the istio version.  There is a mapping from istio version to underlying envoy version in the WORKSPACE so that information is not lost.

**Comment by howardjohn** [comment]
How will you know the version when we build it? The version is determined after its been pushed to istio/proxy and istio/istio

**Comment by howardjohn** [comment]
We would probably need to use the istio/proxy SHA maybe? unless you can change the version dynamically after its built, but I assumed it was baked into the binary

**Comment by jplevyak** [comment]
Is the version available from the Envoy bootstrap or some other configuration file?  I would assume that it was required for reporting telemetry. @mandarjog

**Comment by jplevyak** [comment]
AFAICT it is in the client node metadata.  Is that an acceptable place to retrieve it from?

**Comment by howardjohn** [comment]
Yeah its in the bootstrap, under metadata.ISTIO_VERSION. And we use it pretty extensively so its stable

**Comment by jplevyak** [comment]
Unfortunately it looks like, at least for envoy-static --version  the options and the string is returned before the bootstrap is loaded, so this is a non-starter for that use case.   I created this issue in response to https://github.com/envoyproxy/envoy-wasm/issues/553 but for that use-case I do have access to the node metadata.  Closing this.
