### ISSUE TITLE
Add `VM` to features.yaml?

### ISSUE THREAD

**Issue by ZhengzheYang** [istio/istio#25043]
Currently, [features.yaml](https://github.com/istio/istio/blob/master/pkg/test/framework/features/features.yaml) does not have a field for VM testing. However, we are extending an increasing number of tests involving VM testing (See #24166, #24757, and #24879). This issue would track the discussion about whether or not we should add a VM feature to the features.yaml file, or keep the VM as a scenario (such as traffic.routing.vm) while extending tests.

**Comment by ZhengzheYang** [comment]
cc @maasen @howardjohn @therealmitchconnors

**Comment by nschhina** [comment]
Don't see why VM should be core feature at the same level as `observability` , `telemetry`, `security`, `traffic` etc. I think infrastructure umbrella suits best for this

**Comment by howardjohn** [comment]
We can probably have it at the same level as whatever multicluster is at

**Comment by maasen** [comment]
IMO we need to be able to answer two questions:

1. How much have we exercised the VM related code
1. How many features have we tested VMs alongside (security, telemetry, mutlicluster) to make sure they successfully participate

Setting to a similar level as multicluster would make sense since that is also following a similar pattern. However if using scenarios can also provide those answers then that may be sufficient. Can we take a look at what the dashboards/analysis provides?

**Comment by ZhengzheYang** [comment]
> Don't see why VM should be core feature at the same level as `observability` , `telemetry`, `security`, `traffic` etc. I think infrastructure umbrella suits best for this

Thanks for your input! I agree that those suits well with the current infra. I think putting with the same level as multicluster definitely makes sense as well.

**Comment by ZhengzheYang** [comment]
> IMO we need to be able to answer two questions:
> 
> 1. How much have we exercised the VM related code
> 2. How many features have we tested VMs alongside (security, telemetry, mutlicluster) to make sure they successfully participate
> 
> Setting to a similar level as multicluster would make sense since that is also following a similar pattern. However if using scenarios can also provide those answers then that may be sufficient. Can we take a look at what the dashboards/analysis provides?

Yes, let's do more research about how VM-related Istio code is being used and how many features are being tested with VMs. I think for now scenario could work, but in the future when we add more VM-specific tests (other than extending the existing ones), it could be beneficial to have a separate VM feature.
