### ISSUE TITLE
istio to DB connection getting failed intermitently.

### ISSUE THREAD

**Issue by dhineshbabuelango** [istio/istio#25056]
My performance test to DB from pod is filing intermittently with the below errors only if I enable istio sidecar. From default namespace where istio injection is not enabled, it is working fine.

"HikariPool-1 - Connection com.mysql.cj.jdbc.ConnectionImpl@17baf65d marked as broken because of SQLSTATE(08S01), ErrorCode(0)",
"HikariPool-2 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@5f37ca9f (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.

**Comment by howardjohn** [comment]
duplicate of https://github.com/istio/istio/issues/24856
