### ISSUE TITLE
Support Jwt OR client certificate authentication

### ISSUE THREAD

**Issue by drzdbd1** [istio/istio#25067]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

Due to legacy reasons, a lot of teams used to only use client certificate auth are moving to Jwt so we are in a hybrid situation that teams have to authenticate end user requests by either Jwt or client certificate, because not all teams could move at the same time.

Afaik, the only way for Istio to authenticate by client certificate is to enable mTLS on ingress gateway, but mTLS is NOT optional and would block requests with Jwt token but client certificate.

**Describe alternatives you've considered**

Options we can think of so far:

- Use TLS SIMPLE on ingress gateway, but pass along the "x-forwarded-client-cert" header to backend service so service code can validate the client cert. Today this header is not forwarded unless mTLS is configured
- Use TLS SIMPLE on ingress gateway, and "RequestAuthentication" can accept client certificate as a method to set principals ( SN/thumbprint/SAN from the cert), so then "AuthorizationPolicy" would be able to auth the principal as it does for Jwt today
- Implement "optional" mTLS on ingress gateway, that would still allow client requests to pass through even without client cert

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by drzdbd1** [comment]
Looks like this is already supported in Envoy per this PR? https://github.com/envoyproxy/envoy/pull/9914

**Comment by incfly** [comment]
option 1 seems the best to me. I don't see any reason we can't forward the client certificate when `SIMPLE` mode is used.
option 2 requires significant api design change, a higher bar.

Simple mode doc: https://github.com/istio/api/blob/master/networking/v1alpha3/gateway.proto#L623

Envoy level this only requires to set ` forward_client_cert_details`  in the http connection manager. https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#x-forwarded-client-cert

@PiotrSikora @costinm  do you see any concern if we enable this for Gateway's TlsMode == SIMPLE?

**Comment by howardjohn** [comment]
If we always request client cert won't that impact browsers by prompting for the cert every time they visit? Even if its optional
