### ISSUE TITLE
503 Error from Ingress GW to POD

### ISSUE THREAD

**Issue by dhineshbabuelango** [istio/istio#25062]
I am using istio 1.4.3, I have enabled global mTLS in istio but when ingress GW tries to send request to one particular pod I am getting the below error. This is not only from ingress GW, even if I try from any pod, the error log looks same. This is happening for sometime and goes away. The workaround now is to restart the istio-pilot deployment.

 503 UF,URX "-" "TLS error: 268435703:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER"

**Comment by howardjohn** [comment]
Please get a config dump from ingress and pod and the service, DR, peerauthentication in your cluster: https://github.com/istio/istio/wiki/Troubleshooting-Istio

**Comment by dhineshbabuelango** [comment]
Closing this issue as i dont have the suffice log to upload
