### ISSUE TITLE
TestCEXLCompatibility test flake

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#25063]
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/25052/unit-tests_istio/15408

I'm surprised this can be flaky suddenly - this is the second time I've seen it fail this week

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/25042/unit-tests_istio/15701

**Comment by howardjohn** [comment]
I think #25065 may have made this worse? haven't look into it much https://prow.istio.io/view/gcs/istio-prow/logs/unit-tests_istio_postsubmit/2892

**Comment by nschhina** [comment]
Got it again on https://github.com/istio/istio/pull/25202

**Comment by douglas-reid** [comment]
I think this has been resolved??

**Comment by howardjohn** [comment]
Resolved by deletion I think
