### ISSUE TITLE
Bare-Metal kubernetes-Cluster is unable to handle TLS-termination with istios 1.6.2

### ISSUE THREAD

**Issue by teatreeoilchocolate** [istio/istio#25066]
**Bug description**
Creating a simple Hello-World container with http returning only a textfile will be accessible via http `curl --verbose http://domain.com` will yield the text-file-content.
Trying this with https leads to a preemptive termination. IMHO The SSL-Cert is not found.

This is a new cluster so I will give the setupsets here as well.
From Kiali it looks like the https-requests are neither arriving at the pod nor appears there to be a route.

> % istioctl install --set values.gateways.istio-ingressgateway.sds.enabled=true --set components.telemetry.enabled=true --set addonComponents.grafana.enabled=true --set values.grafana.enabled=true --set values.kiali.enabled=true --set "values.kiali.dashboard.grafanaURL=http://grafana:3000"  --set components.citadel.enabled=true --set components.citadel.enabled=true && 
kubectl apply -f https://raw.githubusercontent.com/cilium/cilium/master/install/kubernetes/quick-install.yaml &&
kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.3.6/components.yaml && 
kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.9.3/manifests/namespace.yaml && 
kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.9.3/manifests/metallb.yaml &&
kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)" &&
kubectl create secret tls domain-wildcard --key=domain.com.pem.key --cert=domain.com.pem.crt -n istio-system

> % kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"archive", BuildDate:"2020-06-20T07:41:29Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

> % istioctl version --remote
client version: 1.6.2
control plane version: 1.6.2
data plane version: 1.6.2 (2 proxies)

Pod-VirtualService-Service-Gateway-configuration

> apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: httpdtest
  labels:
    run: httpdtest
spec:
  replicas: 1
  serviceName: "httpdtest-service"
  selector:
    matchLabels:
      run: httpdtest
  template:
    metadata:
      labels:
        run: httpdtest
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: httpd
          image: domain/httpdhelloworld:1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      dnsConfig:
        searches:
          - default.svc.cluster.local
          - svc.cluster.local
          - cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: httpdtest-service
  labels:
    name: httpdtest-service
spec:
  selector:
    run: httpdtest
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
  - protocol: TCP
    port: 443
    targetPort: 80
    name: https
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: mygateway
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: domain-wildcard # must be the same as secret
    hosts:
    - "*"
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*" #wildcard or the correct domains does not matter
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpd
spec:
  hosts:
  - "domain"
  gateways:
  - mygateway
  http:
    - name: httpdtest-http
      route:
      - destination:
          port:
            number: 80
          host: httpdtest-service
    - name: httpdtest-https
      route:
      - destination:
          port:
            number: 443
          host: httpdtest-service

Curl commands

> % curl --verbose domain.com      
*   Trying xxx.xxx.xxx.xxx:80...
* Connected to domain.com (xxx.xxx.xxx.xxx) port 80 (#0)
> GET / HTTP/1.1
> Host: domain.com
> User-Agent: curl/7.70.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< date: Sat, 27 Jun 2020 21:54:23 GMT
< server: istio-envoy
< last-modified: Sat, 27 Jun 2020 05:58:55 GMT
< etag: "d-5a90a855105c0"
< accept-ranges: bytes
< content-length: 13
< content-type: text/html
< x-envoy-upstream-service-time: 22
< 
	HELLO WORLD
* Connection #0 to host domain.com left intact

> % curl --verbose https://domain.com
*   Trying xxx.xxx.xxx.xxx:443...
* Connected to domain.com (xxx.xxx.xxx.xxx) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to domain.com:443 
* Closing connection 0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to domain.com:443

SSL-Certificate
>  % echo | openssl s_client -showcerts -servername domain.com -connect domain.com:443 2>/dev/null | openssl x509 -inform pem -noout -text                             :(
unable to load certificate
139678901523776:error:0909006C:PEM routines:get_name:no start line:crypto/pem/pem_lib.c:745:Expecting: TRUSTED CERTIFICATE

Documentation is talks about 2 different creation for tls-secrets as well.
It talks about a generic secret here https://istio.io/latest/docs/reference/config/networking/gateway/#ServerTLSSettings
But here https://istio.io/latest/docs/tasks/traffic-management/ingress/secure-ingress/#configure-a-tls-ingress-gateway-for-a-single-host it uses a regular tls-secret.

[X] Configuration Infrastructure
[X] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
I would expect https://domain.com to yield the same result as http://domain.com with above configuration.

**Steps to reproduce the bug**

Follow above steps and execute curl against the https-endpoint.
It also appears that the steps here https://archive.istio.io/v1.5/pt-br/docs/tasks/traffic-management/ingress/secure-ingress-mount/ : creating a secret in namespaces istio-system so that it will be mounted is not working either(at least the result for curl is the same). The secrets are mounted alright, I also restarted the gateway and the corresponding pod, but I still cannot gain access to the pod via https.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
client version: 1.6.2
control plane version: 1.6.2
data plane version: 1.6.2 (2 proxies)

**How was Istio installed?**
istioctl install --set components.telemetry.enabled=true --set addonComponents.grafana.enabled=true --set values.grafana.enabled=true --set values.kiali.enabled=true --set "values.kiali.dashboard.grafanaURL=http://grafana:3000"  --set components.citadel.enabled=true --set components.citadel.enabled=true

**Environment where bug was observed (cloud vendor, OS, etc)**
Debian 4.19.118-2+deb10u1, regular server.

**Comment by howardjohn** [comment]
Can you post the config dump and access logs on the ingress? I could not reproduce this. See https://github.com/istio/istio/wiki/Troubleshooting-Istio for info

**Comment by teatreeoilchocolate** [comment]
I have long since switched ingress, since it was still not a completely setup cluster and a new one, without requirements, at that.
I thought about attaching the configuration, but, if memory serves me right, I found that it was also containing my ssl-certificates, which I am more than reluctant to post.
