### ISSUE TITLE
Add horizontal scaling / auto-scaling for pilot

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#2506]

**Comment by sdake** [comment]
@andraxylia do you believe significant code change to pilot is needed, or is this more of a change the manifests around?

Cheers
-steve

**Comment by andraxylia** [comment]
It's a change in the yaml files + testing.

**Comment by andraxylia** [comment]
not stale.

@costinm is working on it.

**Comment by costinm** [comment]
1.0 has it, options in helm.

**Comment by andraxylia** [comment]
Can you point to the helm option or an example? This will need to be added to docs to be considered done.
