### ISSUE TITLE
Inconsistent name rules across different entities

### ISSUE THREAD

**Issue by FWiesner** [istio/istio#25072]
`idcs-ddeba14a21d74e72baf5a26c65900c12-identity-c9dev2-oc9qadev-com` is a valid name for at least service entries and destination rules, but creation of a `Gateway` with the same name fails with a generic name validation error. Shortening the gateway name to a 15 characters DNS-format string solves the problem, but breaks the idea of simple correlation between `ServiceEntry`, `DestinationRule`, `Gateway` and `VirtualService`

Error message (I'm using the snowdrop Java client for Istio):
```io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://10.175.80.197:6443/apis/networking.istio.io/v1beta1/namespaces/dx4c-prod/gateways. Message: admission webhook "validation.istio.io" denied the request: configuration is invalid: invalid gateway name: "idcs-ddeba14a21d74e72baf5a26c65900c12-identity-c9dev2-oc9qadev-com". Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=admission webhook "validation.istio.io" denied the request: configuration is invalid: invalid gateway name: "idcs-ddeba14a21d74e72baf5a26c65900c12-identity-c9dev2-oc9qadev-com", metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=null, status=Failure, additionalProperties={}).```

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
All names that are valid names in Kubernetes should be accepted on Istio entities. Where the naming has to be more strict compared to base Kubernetes, the validity rules for Istio entities should at least be the same.

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
istioctl version --remote
client version: 1.6.2
cluster-local-gateway version:
telemetry version: 1.6.2
pilot version: 1.6.2
data plane version: 1.6.2 (20 proxies)
```

**How was Istio installed?**
via `istioctl`

**Environment where bug was observed (cloud vendor, OS, etc)**
Kubernetes 1.18.4 installed via `kubeadm`

**Comment by esnible** [comment]
I confirm this is happening, and can be reproduced with `istioctl validate -f <filename>`.  Istio insists the Kubernetes name of a Gateway be a valid [RFC-1123](https://tools.ietf.org/html/rfc1123) hostname.  This does not seem correct.

Our documentation https://istio.io/latest/docs/reference/config/networking/gateway/ does not mention this limitation, nor discuss the Kubernetes name of the Gateway resource at all.

The code is in _pkg/config/validation/validation.go_.  I don't know if there are any circumstances in which this check is needed.

**Comment by howardjohn** [comment]
We do not want dots, but length can be long I think: https://github.com/istio/istio/issues/13211
