### ISSUE TITLE
Documentation for Azure Application gateway Ingress controller for TLS

### ISSUE THREAD

**Issue by shubhammicrosoft1** [istio/istio#25085]
The bookinfo application is working fine & we have hosted the same on HTTP , however we cannot find any documentation to move it  to TLS based directly using Azure Application gateway ingress controller

**Comment by shubhammicrosoft1** [comment]
Hi All,

Is there a way to integerate Istio with Azure Application Gateway Ingress controller or NGINX ingress for mTLS

**Comment by howardjohn** [comment]
If you want to use other Ingress controllers, you just use normal sidecar injection. See https://www.tetrate.io/blog/using-istio-with-other-ingress-proxies/ for detailed walkthrough
