### ISSUE TITLE
Having multiple envoyfilters to istio ingressgatway doesnt follow the actual order in which its applied

### ISSUE THREAD

**Issue by Adharsh-Muraleedharan** [istio/istio#25111]
**Bug description** 
When we are applying multiple envoyfilters to the istio ingressgateway we are not seeing the filters taking precedence in the same order in which they are applied. Even reversing the order in which they are applied doesnt impact on which one happens first.

we have two envoyfilters applied to our istio ingressgateway. One is with a lua filter which we use for Authentication calls and another is ratelimitting filter. Both the authentication server and the ratelimitting servers are outside the cluster. we would want the requests entering the ingress gateway to first hit the ratelimitting server and then the authentication server.

We have applied the ratelimitting filter first and then the authentication filter but the authentication filter is happening first rather than the ratelimitting call. Even if we reverse the order in which the filters are applied it still works in the same way.

Can you please help up fix this ordering ?

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
The filters should work in the order that they are applied

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
**ISTIO VERSION**
client version: 1.5.0
control plane version: 1.5.0
data plane version: 1.5.0 (17 proxies)

**KUBECTL VERSION**
Client Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.10-eks-bac369", GitCommit:"bac3690554985327ae4d13e42169e8b1c2f37226", GitTreeState:"clean", BuildDate:"2020-02-21T23:37:18Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-f459c0", GitCommit:"f459c0672169dd35e77af56c24556530a05e9ab1", GitTreeState:"clean", BuildDate:"2020-03-18T04:24:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
using istioctl manifests

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS EKS clusters

The istio config dump is placed here : this is after applying the ratelimit filter and then the authentication filter
https://gist.github.com/Adharsh-Muraleedharan/5d57a8bf49d53ecc928304c7f7bd62c5

**Comment by mandarjog** [comment]
Can you add your actual istio configuration including the creation time of both resources?

**Comment by mandarjog** [comment]
As an aside we are working on new API, which is geared more directly to Filter configuration only and it is not a generic XDS patch APi.  The key point in the new api is that you specify the exact order of filters you want to insert. Ptal: https://tinyurl.com/istio-extension-api

**Comment by Adharsh-Muraleedharan** [comment]
> Can you add your actual istio configuration including the creation time of both resources?

how do you want me to generate this ?
I had applied them one after the other. First the ratelimiting filter and then the authentication lua filter.

**Comment by Adharsh-Muraleedharan** [comment]
> As an aside we are working on new API, which is geared more directly to Filter configuration only and it is not a generic XDS patch APi. The key point in the new api is that you specify the exact order of filters you want to insert. Ptal: https://tinyurl.com/istio-extension-api

I have requested access to this. can you please provide it ?
