### ISSUE TITLE
Update to Kubernetes 1.19 client libraries

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#25119]
This issue tracks updating to 1.19 client libraries

**Comment by howardjohn** [comment]
TODO: move custom pods/proxy, as this is native now: https://github.com/kubernetes/kubernetes/issues/90768

**Comment by shamsher31** [comment]
> TODO: move custom pods/proxy, as this is native now: [kubernetes/kubernetes#90768](https://github.com/kubernetes/kubernetes/issues/90768)

Does this means we need to upgrade `client-go` version to 1.19 (which is not yet released) in order for new `ProxyGet` func to work which is recently merged in k8 master ?

**Comment by howardjohn** [comment]
Yes but it's not a big deal - we just direct API call today so it's just a code cleanup we aren't missing any functionality

**Comment by fpesce** [comment]
FYI: how outdated is https://docs.google.com/document/d/14Xfe9V0vv8d7W75c21d-cY2XyK6xvRH0_Kg8j_zfh4Y/edit#heading=h.xw1gqgyqs5b ?

**Comment by howardjohn** [comment]
That doc is up to date
