### ISSUE TITLE
format: make import order deterministic

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#25129]
We often get people in PRs randomly changing import order and people in PRs complaining about import order - neither of these should happen, it should be managed by the tooling

**Comment by daixiang0** [comment]
Is there any rules about it? I would like to implement this tool but i do not know istio's import rule.

**Comment by hzxuzhonghu** [comment]
IMO: we should split the import libs in 4 groups:


1. standard go libs
1. other dependencies from other projects
1. istio.io/xxx (xxx not equals istio)
1. istio.io/istio

**Comment by howardjohn** [comment]
I personally do not care at all what it is as long as it's deterministic to avoid diff in PR and reviewers complaining

**Comment by ericvn** [comment]
Investigate the linter enforcing the order.

**Comment by carolynhu** [comment]
run "goimports"?

**Comment by howardjohn** [comment]
Solved by GCI
