### ISSUE TITLE
Failed to exec command with istioctl compiled by myself

### ISSUE THREAD

**Issue by thefuckingcode** [istio/istio#25148]
**Bug description**
I failed to exec this command `istioctl manifest generate --set profile=demo --set components.kiali.enabled=true` with istioctl compiled by myself. The output is ‘Error: compiled in charts not found in this development build, use --charts with local charts instead or run make gen-charts’. There are some configuration missing that casuse this error. What should i do

**Expected behavior**
print the istio manifest

**Steps to reproduce the bug**
1.  clone git repo
2. git checkout 1.6.4
3. compile istioctl
4. run command `istioctl manifest generate --set profile=demo --set components.kiali.enabled=true`
5. get error : 'Error: compiled in charts not found in this development build, use --charts with local charts instead or run make gen-charts'

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
tag 1.6.4

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
You need to either run `make gen-charts` before building, or pass the flag `--charts manifests/` , as the error indicates

**Comment by shamsher31** [comment]
See more details on the Advance Install customization guide.
https://istio.io/latest/docs/setup/install/istioctl/#advanced-install-customization
