### ISSUE TITLE
Interception mode 'NONE' results in failing sidecar readiness probes

### ISSUE THREAD

**Issue by benwh** [istio/istio#25156]
**Bug description**

_Disclaimer: I'm not sure whether this is a bug, expected behaviour, lack of documentation or combination of these._

If I set a pod annotation of `sidecar.istio.io/interceptionMode: "NONE"`, then my pod correctly does not receive the iptables rules redirecting connections to Envoy, but the pod is never marked as ready because the `istio-proxy` container's readiness probes are failing.

This is possibly related to the fact that I see this message being repeated in the `istio-proxy` logs:
```
warn    Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 1 successful, 0 rejected; lds updates: 0 successful, 1 rejected
```

I can work around this by setting `status.sidecar.istio.io/port: "0"`, which seems to result in the [probe being removed](https://github.com/istio/istio/blob/576649f1c97e3972092eb3f73197607b0b84ae2a/manifests/charts/istio-control/istio-discovery/files/injection-template.yaml#L256-L264). I'm not sure whether it's expected behaviour that I'd need to set this annotation too though (potentially if the interception mode is set to `NONE` then that could disable probing), or whether there's another way to fix the rejected LDS updates.

---

Why am I trying to use `interceptionMode: NONE` in the first place?...

This is to setup a Prometheus instance which can scrape pods which are running under a STRICT mTLS mode: I want the istio-proxy sidecar present so that I have the client certificates present and usable by Prometheus, but don't want the Prometheus pod's requests to be handled by the sidecar as this appears to introduce other issues.

**Affected product area**

[X] Configuration Infrastructure
[X] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behaviour**

Istio does not mutate the pod in a way that leaves it broken (not being marked as ready) - either the istio-proxy still functions correctly with `interceptionMode: NONE`, or my pod is rejected by the webhook.

**Steps to reproduce the bug**

```bash
kubectl run prometheus-noninjected --rm -i --tty --image ubuntu --overrides='
{
  "apiVersion": "v1",
  "metadata": {
    "annotations": {
      "sidecar.istio.io/interceptionMode": "NONE"
    }
  }
}' -- /bin/bash
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
client version: 1.6.0
control plane version: 1.6.2
data plane version: 1.6.2 (31 proxies), 1.6.1 (6 proxies)
```

**How was Istio installed?**

Istio Operator

**Environment where bug was observed (cloud vendor, OS, etc)**

n/a

**Comment by howardjohn** [comment]
NONE mode will result in attempting to bind listeners to low ports which will likely fail permissions. You likely see logs like
```
 warning envoy config    gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) 127.0.0.1_53: cannot bind '127.0.0.1:53': Permission denied
127.0.0.1_443: cannot bind '127.0.0.1:443': Permission denied
127.0.0.1_80: cannot bind '127.0.0.1:80': Permission denied
127.0.0.1_853: cannot bind '127.0.0.1:853': Permission denied

```

There is a `sidecar.istio.io/capNetBindService=true` annotation to give permissions, but will then run into `gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) 127.0.0.1_15021: cannot bind '127.0.0.1:15021': Address already in use
`.

If you restrict the scoping you can make things start up:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: sidecar
spec:
  egress:
  - hosts:
    - ./*
```

But clearly some improvements needed here
