### ISSUE TITLE
The maximum number of connections for deployment injected by isto system is only 256

### ISSUE THREAD

**Issue by ckgmg** [istio/istio#25175]
Why is there only 256 concurrent connections in the injected pod

**Comment by howardjohn** [comment]
This is not a constraint in Istio. If you are experience this, please provide all the information about what happens after 256 connections, a config dump (see https://github.com/istio/istio/wiki/Troubleshooting-Istio), and any DestinationRule settings.

And please ensure this is not a limitation of your application

**Comment by howardjohn** [comment]
We do not have enough information to move forward with this
