### ISSUE TITLE
Better Helm v3 support 

### ISSUE THREAD

**Issue by jacob-delgado** [istio/istio#25184]
**Describe the feature request**
The current charts found under manifests/ allow for Helm v3 support, but there are things left desired. This issue will be used to track better Helm v3 support.

The goal is to have this be a Beta feature for Istio 1.7.

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

Tasks remaining:
- [ ] Have charts not rely on `globals.yaml`
  -  [x] discovery https://github.com/istio/istio/pull/25186/
  -  [x] cni https://github.com/istio/istio/pull/25187
  -  [x] gateways https://github.com/istio/istio/pull/25260
  -  [ ] istiocoredns 
- [ ] Support canaries for gateways
- [ ] Add integration tests which use manifests/ charts
- [ ] Document install and upgrade on istio.io
- [ ] Make sure defaults in code reflect defaults in charts (see https://github.com/istio/istio/pull/25402#discussion_r454638814)
- [ ] Make sure api docs are in agreement with defaults in charts (see https://github.com/istio/istio/pull/25402#pullrequestreview-448458956)

**Comment by jacob-delgado** [comment]
cc @costinm Thoughts? We may not be able to get everything done for Istio 1.7. Modify the set of tasks. There is more work than I've identified.

**Comment by costinm** [comment]
I would prioritize test and docs, based on what we have now. If global.yaml is late for 1.7 - we'll have it in 1.8.

**Comment by jacob-delgado** [comment]
Closing this issue as @howardjohn and @nrjpoddar have done the work necessary to get this into 1.8.
