### ISSUE TITLE
Implementing Jaeger Tracing in Istio Telemetry V2

### ISSUE THREAD

**Issue by varun-krishna** [istio/istio#25198]
**Bug description**

With Telemetry V2 in place  and depreciation of Mixer , would like to Understand implication on Jaeger implementation . Any leads here would really help.

[ ] Configuration Infrastructure
[X] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by objectiser** [comment]
I don't believe there is any implication on tracing information being collected using Jaeger. Could you elaborate on your concerns?

**Comment by dinesh4747** [comment]
@objectiser  - To set the context - we are currently using istio-1.5.2 deployed in GKE and by default we have enabled zipkin for tracing wherein our zipkin pods are running in istio-system namespace 

**Goal** - we wanted to implement Jaeger in a complete scalable productionistic deployment on GCP and wanted to export zipkin traces to Jaeger collector and store it in Cassandra and visualize via Jaeger UI 

**Concerns:**

1. We are not really sure on where do we run jaeger collector as in-cluster pods on GKE or a stateful instance on GCE and transport the data from zipkin pods in istio-system namespace to Jaeger collector 

2. Also How do we export trace/spans over HTTP header across the micro services deployed in GKE (I am under the impression that istio-proxy/envoy ships the data across each services over a HTTP header and in-turn ships the data to zipkin pods running on istio-system ) Please do re-correct If I am on the different page

3. Does istio-proxy takes care of everything out of the box as documented or do  we need to propagate any specific cluster level changes to get discover traces/spans across the application services running on different language runtimes 

Any Help or pointers on my understanding would ideally help in a great way 

Thanks in Anticipation
Dinesh

**Comment by objectiser** [comment]
Can't answer your question about GKE vs GCE - possibly others have experience with them. But in terms of reporting the tracing data/spans to Jaeger, have you looked at the docs: https://istio.io/latest/docs/tasks/observability/distributed-tracing/jaeger/

The information passed between services is the trace context. This can be in various formats, but when using the Zipkin tracer in Istio/envoy, it uses the B3 format.

You should also read this section on trace context propagation: https://istio.io/latest/docs/tasks/observability/distributed-tracing/overview/

**Comment by douglas-reid** [comment]
This conversation should probably be moved to the [forums](discuss.istio.io). I believe @objectiser has provided good guidance on trace configuration. Please feel free to reopen if the documentation does not work, or if there are gaps.
