### ISSUE TITLE
Instructions for generating certs equivalent to sample certs

### ISSUE THREAD

**Issue by rverma-jm** [istio/istio#25190]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
In replicated control pane setup it's instructed to use self generated root-cert and intermediate ca cert/key.
Is it possible to provide/document generation steps for the same.

**Describe alternatives you've considered**
Tried this, but it sounds too complex.
https://roll.urown.net/ca/ca_root_setup.html
https://roll.urown.net/ca/ca_intermed_setup.html

**Affected product area (please put an X in all that apply)**

[X] Configuration Infrastructure
[ ] Docs
[X] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[X] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[X] Multi Cluster
[ ] Virtual Machine
[X] Multi Control Plane

**Additional context**

**Comment by zufardhiyaulhaq** [comment]
you can use step certificate for doing this
```
step certificate create istio-root-ca root-cert.pem root-key.pem --profile root-ca  --kty RSA --no-password --insecure --not-after 87600h
step certificate create istio-intermediate-ca ca-cert.pem ca-key.pem --profile intermediate-ca --kty RSA --ca ./root-cert.pem --ca-key ./root-key.pem --no-password --insecure --not-after 43800h 
step certificate bundle ca-cert.pem root-cert.pem cert-chain.pem
```

**Comment by rverma-jm** [comment]
nice this worked, thank you soo much.
