### ISSUE TITLE
The resources of EnvoyFilter works globally only within namespace istio-system

### ISSUE THREAD

**Issue by shaoyifeng1013** [istio/istio#25191]
**Description of the problem**
Normally, EnvoyFilter should work globally if it is the same namespace as the pilot，but we just tested it and found that there's works globally only within NS istio-system，We are not sure whether it is design or issue，please answer 

**Example**
pilot deployed in namespace istio-main
envoyfilter deployed in namespace istio-main
but envoyfilter is not be found in envoy config

**The current environment**
istio 1.6.4
kubernetes 1.17.3

**Comment by howardjohn** [comment]
https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/ see rootNamespace
