### ISSUE TITLE
virtualService add delegate,web can not be visited ,showes no healthy upstream

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#25204]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
```
[root@master01 virtualservice]# kubectl get vs bookinfo -o yaml -n istio
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.istio.io/v1beta1","kind":"VirtualService","metadata":{"annotations":{},"name":"bookinfo","namespace":"istio"},"spec":{"exportTo":["*"],"gateways":["bookinfo-gateway"],"hosts":["*"],"http":[{"delegate":{"name":"productpage","namespace":"istio"},"match":[{"uri":{"exact":"/productpage"}},{"uri":{"prefix":"/static"}},{"uri":{"exact":"/login"}},{"uri":{"exact":"/logout"}},{"uri":{"prefix":"/api/v1/products"}}]}]}}
  creationTimestamp: "2020-07-02T04:50:17Z"
  generation: 15
  name: bookinfo
  namespace: istio
  resourceVersion: "2685002"
  selfLink: /apis/networking.istio.io/v1beta1/namespaces/istio/virtualservices/bookinfo
  uid: 1c02e129-66c0-4f5e-bc14-a0c1bca400c6
spec:
  exportTo:
  - '*'
  gateways:
  - bookinfo-gateway
  hosts:
  - '*'
  http:
  - delegate:
      name: productpage
      namespace: istio
    match:
    - uri:
        exact: /productpage
    - uri:
        prefix: /static
    - uri:
        exact: /login
    - uri:
        exact: /logout
    - uri:
        prefix: /api/v1/products
[root@master01 virtualservice]# kubectl get vs -n istio
NAME          GATEWAYS             HOSTS           AGE
bookinfo      [bookinfo-gateway]   [*]             2d1h
details                            [details]       23h
productpage                        [productpage]   23h
ratings                            [ratings]       23h
reviews                            [reviews]       23h
```

```
no healthy upstream
```

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
[root@master01 virtualservice]# istioctl version --remote
client version: 1.6.1
control plane version: 1.6.1
data plane version: 1.6.1 (14 proxies)
```
```
[root@master01 virtualservice]# kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2020-05-12T09:28:18Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"linux/amd64"}
```
**How was Istio installed?**
istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by 13567436138** [comment]
no healthy upstream
the webpage showes this error

**Comment by 13567436138** [comment]
[2020-07-05T04:10:53.210Z] "GET /productpage HTTP/1.1" 503 UH "-" "-" 0 19 0 - "172.20.0.1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36" "0131a6a2-69fc-9521-a60d-48f442b621ca" "bookinfo.demo" "-" - - 172.20.0.164:8080 172.20.0.1:52502 - -

**Comment by howardjohn** [comment]
Can you give more info about all of your config so we can reproduce this, and add a config dump (https://github.com/istio/istio/wiki/Troubleshooting-Istio)?

**Comment by howardjohn** [comment]
Any more info?

**Comment by 13567436138** [comment]
the vs config I had showed to you,you can validate it on your system.and bookinfo demo you have.

**Comment by hzxuzhonghu** [comment]
@13567436138 Not sure what you met, could you provide any useful info

**Comment by howardjohn** [comment]
We don't have enough information to troubleshoot this further
