### ISSUE TITLE
“istio-egress”  is absent

### ISSUE THREAD

**Issue by meelody** [istio/istio#2520]
When I execute the command  “kubectl get pods -n istio-system”，Can't find “istio-egress”.And I can't find "egress" in "install/kubernetes/istio-auth.yaml".But has “EgressRule”.When was this updated, or I installed the problem.

**Comment by christian-posta** [comment]
That's not used anymore; we use egress rules now: https://istio.io/docs/reference/config/traffic-rules/egress-rules.html

**Comment by sdake** [comment]
@meelody I'm not sure when this change was made.  Do you need that information specifically?  If not, can you close this issue tracker.

Cheers
-steve

**Comment by linsun** [comment]
@meelody yes, we had it in 0.2 but removed now... there may be some old doc reference.  Is this something we need to fix in the doc?

**Comment by meelody** [comment]
Thanks.I should have seen the old document.I'm just afraid the installation is wrong. I'll close the issue.

**Comment by sdake** [comment]
thanks @christian-posta.
