### ISSUE TITLE
Virtualservice response headers with redirect are missing

### ISSUE THREAD

**Issue by torstenwerner** [istio/istio#25206]
Setting response headers together with redirect in VirtualService does not send the headers

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

I expect that the configured header gets send with the redirect (301) response.

**Steps to reproduce the bug**

Install istio following https://istio.io/latest/docs/setup/getting-started/#download
Extend the VirtualService for bookinfo with

```
  - match:
    - uri:
        exact: "/"
    redirect:
      uri: "/productpage"
    headers:
      response:
        set:
          Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
```

Test with curl

```
$ curl -v http://$GATEWAY_URL
* Rebuilt URL to: http://192.168.64.3:30864/
*   Trying 192.168.64.3...
* TCP_NODELAY set
* Connected to 192.168.64.3 (192.168.64.3) port 30864 (#0)
> GET / HTTP/1.1
> Host: 192.168.64.3:30864
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< location: http://192.168.64.3:30864/productpage
< date: Sat, 04 Jul 2020 13:37:59 GMT
< server: istio-envoy
< content-length: 0
```

The redirect works but the header Strict-Transport-Security is missing. That is a problem because the header
Strict-Transport-Security with preload must be sent in the redirect and not only in following redirected response.
See https://hstspreload.org/ for more information.
I did not find any hint in the documentation why the header is not sent and that is why it looks like a bug to me.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
$ istioctl version --remote
client version: 1.6.4
control plane version: 1.6.4
data plane version: 1.6.4 (9 proxies)
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:34:25Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.4-1+6f17be3f1fd54a", GitCommit:"6f17be3f1fd54a88681869d1cf8bedd5a2174504", GitTreeState:"clean", BuildDate:"2020-06-23T21:17:52Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

following the instructions at https://istio.io/latest/docs/setup/getting-started/#download

**Environment where bug was observed (cloud vendor, OS, etc)**

MicroK8s

[istio-dump.tar.gz](https://github.com/istio/istio/files/4872946/istio-dump.tar.gz)

**Comment by knight42** [comment]
I have filed #25444 to fix this problem.
