### ISSUE TITLE
Why the istio-proxy inbound make all http headers name to lowercase?

### ISSUE THREAD

**Issue by Hinsteny** [istio/istio#25216]
**Bug description**
When we do websocket proxy, , then the spring-cloud-gateway will get http protocol by `SEC_WEBSOCKET_PROTOCOL = "Sec-WebSocket-Protocol"` when do the websocket route. It can't get protocol because the istio-proxy had make all http headers name to lowercase just like `sec-websocket-protocol: xxx`;

[X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
I need to config istio to not change http headers to lowercase, so the spring-cloud-gateway will routing websocket correctly; 

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istio 1.6.1

**How was Istio installed?**
`istioctl manifest apply --set profile=demo`

**Environment where bug was observed (cloud vendor, OS, etc)**
k8s 1.5

**Comment by ramaraochavali** [comment]
https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/header_casing#http-1-1-header-casing related doc

**Comment by Hinsteny** [comment]
> https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/header_casing#http-1-1-header-casing related doc
Thanks, But i how to config this with istio?

**Comment by ramaraochavali** [comment]
You can configure it using EnvoyFilter

**Comment by esnible** [comment]
> You can configure it using EnvoyFilter

Is there an example?

**Comment by hellojqk** [comment]
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: normalize-headers
spec:
  configPatches:
    - applyTo: CLUSTER
      match:
        context: SIDECAR_OUTBOUND # SIDECAR_INBOUND
      patch:
        operation: MERGE
        value:
          http_protocol_options:
            header_key_format:
              proper_case_words: {}

istio 1.6.4  k8s v1.18.3
it can work when OUTBOUND
https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#

**Comment by ramaraochavali** [comment]
Since example given above, I am closing this. Please reopen if you need any additional info.

**Comment by mingyuanzhu** [comment]
> ```yaml
> apiVersion: networking.istio.io/v1alpha3
> kind: EnvoyFilter
> metadata:
>   name: normalize-headers
> spec:
>   configPatches:
>     - applyTo: CLUSTER
>       match:
>         context: SIDECAR_OUTBOUND # SIDECAR_INBOUND
>       patch:
>         operation: MERGE
>         value:
>           http_protocol_options:
>             header_key_format:
>               proper_case_words: {}
> ```
> 
> istio 1.6.4 k8s v1.18.3
> it can work when OUTBOUND
> https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#

Hi, when I apply the config to our cluster, the istio proxy-status change to `STALE`. And I does not work. Do you config any other things?
