### ISSUE TITLE
Setup docs and examples should use namespaces and FQDNs to avoid future k8s misconfigurations

### ISSUE THREAD

**Issue by kriswuollett** [istio/istio#25222]
Similar to feature request at https://github.com/istio/istio/issues/23235, the analyzer should also try to detect `Service` `targetPort` mapping issues. It seems like that could be in scope of ensuring that all `VirtualService`s can get traffic all the way to the open port on the pod.

It took about a days worth of time to figure out that I had swapped the `port` and `targetPort` in my `Service`. Some of the steps I took to try debug:

* Read through quite a few Istio debugging guides/articles and using `describe` on just about everything in the `istio-system` namespace
* analyzer said there was no problems for app namespace
* other web server services were routing fine
* could `curl` it within the pod via localhost
* could not `curl` it from the `istio-ingressgateway` pod via SVC.NAMESPACE.svc:PORT
* double checked my service config with a previous pre-Istio version and realized I just retyped the ports wrong
* recreated the virtualservice and then the above tests along with curl via DOMAIN worked

**Affected product area (please put an X in all that apply)**

[X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

* Current level of experience with Kubernetes is only about a few weeks
* Chose to 
* Installed Istio with:
  ```shell
  istioctl install
  istioctl install --set addonComponents.grafana.enabled=true
  ```
* Using `cert-manager` with Let's Encrypt http01 challenges. Happy that I didn't have to manually create `VirtualService`s for the challenges that I read some earlier thread(s) about. Ran into `Gateway`s sharing `Certificate` SSL 404 errors issue, ended up just creating one `Gateway` for the cluster.

**Comment by howardjohn** [comment]
am I understanding this correctly that this is strictly about the mapping from Service to pod with target Port? It would help to show an example incorrect config to verify.

If so, I think this is outside of scope (pure k8s issue not Istio) and not actually possible (we have no way of knowing what is or isn't a correct targetPort)

Please let me know if I understand correctly

**Comment by kriswuollett** [comment]
Hi @howardjohn, thanks for getting back to me. Yes, I this is probably out of scope as you describe. I think I did not pay enough attention that [VirtualService](https://istio.io/latest/docs/reference/config/networking/virtual-service/#VirtualService)::host is simply a host name. There is even a special note there in the docs about how the short name gets combined with the namespace of the rule to form `httpbin.default.svc.cluster.local` as in the example of [httbin](https://github.com/istio/istio/blob/8a95f8efb41663bd1a39ec6ef8a7d7f993d5602c/samples/httpbin/httpbin-gateway.yaml#L28) when in the `default` namespace.

So in this case I think it will be worthwhile to rename this issue to repurpose it as a suggestion that the Istio getting started doc (k8s) examples that use `httpbin` and `bookinfo` should specify a namespace, perhaps via an environment variable in the scripts, along with the FQDN for the virtual service host. Perhaps that would catch this kind of mistake early in the onboarding process?

**Comment by kriswuollett** [comment]
... when I went through getting started docs I explicitly used a namespace so I could easily clean up the examples when finished with them. It's unfortunate I didn't realize the FQDN part earlier.

**Comment by esnible** [comment]
Agreed that the analyzers can be improved to cover more things.  They are mostly written for Istio problem detecting, not K8s problems.

The samples do not include namespaces so that the user can use `-n <namespace>` to apply them to their own test namespaces.  This is easy to miss.  I have several thoughts

- Docs and _samples_ files should have explicit namespace in all YAML
- Keep them as they are, but add commented-out `# uncomment namespace: my-namespace` fields to remind people to use them
- Keep them as they are

I prefer the 2nd option.  I am not sure what the @istio/wg-docs-maintainers prefer.
