### ISSUE TITLE
ServiceEntry for an external Apache ActiveMQ is not working

### ISSUE THREAD

**Issue by tvdinh** [istio/istio#25239]
**Bug description**
Consider the following setup:
- A pod with an ActiveMQ client installed running inside the Istio Service Mesh
- An external (to the Mesh) Apache ActiveMQ with SSL enabled, on port 61616, server is using a self-signed certificate.

Goal: Be able to send a message from the pod to the ActiveMQ instance.

I'm facing the following issue:
- Without the istio proxy sidecar, by that I mean using the annotation `"sidecar.istio.io/inject":"false"`: I'm able to send a message initiated from the pod:
```
activemq_client_run -U <user> -P <password> -p"Hello World From Pod" -
b ssl://external.activemq.mydomain.com:61616 queue
Message sent
Operation completed in 12ms (excluding connect)
```
Note it's also working for a client running in different environment, say my laptop, as long as the server's cert is installed in the client's truststore.
- BUT, with the istio proxy sidecar, `"sidecar.istio.io/inject":"true"`: not able to send a message:
```
activemq_client_run -U <user> -P <password> -p"Hello World From Pod" -
b ssl://external.activemq.mydomain.com:61616 queue
...
ActiveMQ Transport: ssl://external.activemq.mydomain.com/192.168.10.10:61616, called closeSocket()
main, handling exception: java.net.SocketException: Connection reset
ActiveMQ Task-1, called close()
ActiveMQ Task-1, called closeInternal(true)
javax.jms.JMSException: Could not connect to broker URL: ssl://external.activemq.mydomain.com:61616. Reason: java.net.SocketException: Connection reset
	at org.apache.activemq.util.JMSExceptionSupport.create(JMSExceptionSupport.java:36)
	at org.apache.activemq.ActiveMQConnectionFactory.createActiveMQConnection(ActiveMQConnectionFactory.java:374)
	at org.apache.activemq.ActiveMQConnectionFactory.createConnection(ActiveMQConnectionFactory.java:252)
	at co.nordlander.a.A.connect(A.java:374)
	at co.nordlander.a.A.run(A.java:189)
	at co.nordlander.a.A.main(A.java:157)
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:154)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
	at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:750)
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123)
	at org.apache.activemq.transport.tcp.TcpBufferedOutputStream.flush(TcpBufferedOutputStream.java:115)
	at java.io.DataOutputStream.flush(DataOutputStream.java:123)
	at org.apache.activemq.transport.tcp.TcpTransport.oneway(TcpTransport.java:194)
	at org.apache.activemq.transport.AbstractInactivityMonitor.doOnewaySend(AbstractInact
```
It seems it doesn't even reach the server as it doesn't represent the cert yet, or it's connection is getting terminated at the `sidecar` or the `egress gateway`

The external service entry configuration:

```
Name:         activemq-external
Namespace:    istio-system
Annotations:  API Version:  networking.istio.io/v1alpha3
Kind:         ServiceEntry
Metadata:
  Creation Timestamp:  2020-07-06T02:38:45Z
  Generation:          1
  Resource Version:    41066455
  Self Link:           /apis/networking.istio.io/v1alpha3/namespaces/istio-system/serviceentries/activemq-external
  UID:                 cfebe000-bf31-11ea-9faf-02f174b32bd6
Spec:
  Hosts:
    external.activemq.mydomain.com
  Location:  MESH_EXTERNAL
  Ports:
    Name:      tls-external-activemq
    Number:    61616
    Protocol:  TLS
  Resolution:  NONE
Events:        <none>
```

Does anyone spot a problem with the configuration ? Otherwise, is ISTIO TLS not working with ActiveMQ Apache SSL ?

Thanks,
T

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ x] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by tvdinh** [comment]
Hi @howardjohn , thanks for getting back.

I eventually got it working by adding this 

```
  Endpoints:
    Address:  external.activemq.mydomain.com
```
to the `serviceentry`. I know from `istio` doc, that endpoints here are just a set of servers for load balancing purpose. But for some reason, it starts working by adding this config.

There are also other configurations like `DestinationRule` or `VirtualService` in the system that may affect this. What I am saying is that I may not be able provide the complete picture here. Anyway, it's no longer a blocker for me, so happy to close the ticket.

**Comment by howardjohn** [comment]
Thanks!

**Comment by jtnz** [comment]
Sorry @howardjohn to hijack this closed issue, but it looks entirely relevant to our problem. We're using AmazonMQ (ActiveMQ) and EKS, and have the same problem but cannot find any solution that works (other than just bypassing the proxy). We have tried to recreate @tvdinh 's solution but that did not work. Without a mesh everything works fine. Other external services work fine (e.g. Couchbase and Kafka).

We're using k8s 1.17, and Istio 1.6.7.

Our ActiveMQ client connection URL looks like this (as provided by AWS):
`failover:(ssl://HASH-1.mq.eu-central-1.amazonaws.com:61617,ssl://HASH-2.mq.eu-central-1.amazonaws.com:61617)`

And this is the latest `ServiceEntry` config we tried, based on this issue:
```apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: activemq-1
spec:
  hosts:
    - HASH-1.mq.eu-central-1.amazonaws.com
  ports:
    - number: 61617
      name: tls
      protocol: TLS
  resolution: DNS
  location: MESH_EXTERNAL
  endpoints:
    - address: HASH-1.mq.eu-central-1.amazonaws.com
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: activemq-2
spec:
  hosts:
    - HASH-2.mq.eu-central-1.amazonaws.com
  ports:
    - number: 61617
      name: tls
      protocol: TCP
  resolution: DNS
  location: MESH_EXTERNAL
  endpoints:
    - address: HASH-2.mq.eu-central-1.amazonaws.com```

We've also tried:
- No `ServiceEntry`
- TLS `ServiceEntry`
- TCP `ServiceEntry`

I've also attached a sample of the envoy [access_logs.log](https://github.com/istio/istio/files/5072058/access_logs.log).

Any help would be appreciated.

**Comment by gmbeneva** [comment]
@jtnz : We had the same issue and the problem was that since we were in a active/passive mode, if for example node 2 was currently the master node, the application would first try on node 1 and would be redirected to node 2 by that first node and istio would not allow it. We had to add the endpoint addresses of each node to each service entry to allow redirects. It would then allow to directly contact each node and also to be redirected by those nodes to the master node. :

`apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: activemq-se-1
spec:
  endpoints:
  - address: activemq-node1.ssq.local
  - address: activemq-node2.ssq.local
  exportTo:
  - .
  hosts:
  - activemq-node1.ssq.local
  location: MESH_EXTERNAL
  ports:
  - name: tcp
    number: 61616
    protocol: TCP
  resolution: DNS
  
---

apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: activemq-se-2
spec:
  endpoints:
  - address: activemq-node1.ssq.local
  - address: activemq-node2.ssq.local
  exportTo:
  - .
  hosts:
  - activemq-node2.ssq.local
  location: MESH_EXTERNAL
  ports:
  - name: tcp
    number: 61616
    protocol: TCP
  resolution: DNS`

**Comment by bitorange** [comment]
Maybe you can try to apply a DestinationRule. Here is the [doc](https://istio.io/latest/docs/tasks/traffic-management/egress/egress-kubernetes-services/#use-a-kubernetes-service-with-endpoints-to-access-an-external-service). 

> In this case, the workload send HTTPS requests (open TLS connection) to the activemq-node1.mycompany.com. The traffic is already encrypted by the workload so you can safely disable Istio’s mutual TLS:

```
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: my-rule
spec:
  host: activemq-node1.mycompany.com
  trafficPolicy:
    tls:
      mode: DISABLE
EOF
```
