### ISSUE TITLE
Istio leading to 3x latency 

### ISSUE THREAD

**Issue by Prashansa-K** [istio/istio#25240]
We are shifting our services from Beanstalk environments to AWS EKS. We have deployed istio to handle the routing of requests.
General Flow:
Client Request --> ALB --> (Associated EKS Nodes) istio-ingressgateway --> Gateway resource --> Virtual Service  --> Service  --> Application Pod

Normally on beanstalk environments, request took 10-20 ms. With the current istio setup, it is taking about 30-80 ms. What can be the possible reasons for this?

Mixer policies are disabled. mTLS is disabled.
HPA is configured properly for both. ingressgateway and application pods to handle load.

**Comment by bianpengyuan** [comment]
Could you provide more info about your installation? (i.e. istio version, install option and profile, etc). Here are the expected number of latency overhead for the latest release: https://istio.io/latest/docs/ops/deployment/performance-and-scalability/. 

Mixer policy should not need explicit disabling in recent releases, which leads me to think you might be using older releases with mixer filter injected. That could contribute a lot to latency overhead.
