### ISSUE TITLE
'istioctl verify-install' fails (master)

### ISSUE THREAD

**Issue by esnible** [istio/istio#25247]
`istioctl verify-install` fails with

```
Error: compiled in charts not found in this development build, use --manifests with local charts instead (e.g. istioctl install --charts manifests/) or run make gen-charts and rebuild istioctl
```

Unfortunately the message is incorrect; `--manifests` and `--charts` don't work with `verify-install`.  `make gen-charts` is sufficient to get past the message.  Simply adding those options to the CLI seems insufficient and may have something to do with how overlays are being handled.

This does not occur on 1.6.x.

Getting past this message isn't enough.  RenderManifest() is not generating a manifest on Master when called by verify-install.  Discovered while troubleshooting https://github.com/istio/istio/issues/25194 and it may have to do with how profiles are handled.  `verify-install` doesn't overlay profiles and expected the in-cluster operator to be full and not just a profile.

**Comment by esnible** [comment]
@ostromart When I try today I get a new error:

```
~/go/src/istio.io/istio/out/darwin_amd64/istioctl verify-install
Error: could not load IstioOperator from cluster: unknown field "citadel" in v1alpha1.IstioComponentSetSpec.  Use --filename
```

This is on Master.  It seems bad.

@knight42 You recently changed the code to use `convertToIstioOperator()` instead of `UnmarshalIstioOperator()`.  I am worried the new version is more strict about unknown fields.  These commands should be tolerant of what was there.

We may need a test protocol where we create a unit test for parsing the IstioOperator for every Istio version that _istioctl_ promises to support for upgrade, and make sure that we can parse them.  We may also need to hide fields rather than removing them from IstioOperatorSpec.

**Comment by knight42** [comment]
@esnible I am really sorry that I don't realize we should tolerate unknown fields, and I have confirmed that `convertToIstioOperator` does become more strict about unknown fields. I am afraid we have to revert #25913.

**Comment by esnible** [comment]
@knight42 Instead of reverting can you figure out how to relax it?

**Comment by knight42** [comment]
@esnible It is not quite obvious to me how to relax it, may need some time to investigate.

**Comment by knight42** [comment]
@esnible it turns out that if we could set the field `AllowUnknownFields` of `github_com_golang_protobuf_jsonpb.Unmarshaler` to true at https://github.com/istio/api/blob/899a8094976e205c42178d6903bd290bba470e56/operator/v1alpha1/operator_json.gen.go#L57, we could tolerate unknown fields, but that seems a bit tricky as this file is auto generated.

**Comment by esnible** [comment]
Closing because this was fixed by the Revert "refactor: convert IstioOperator from Unstructured more efficiently" #26011
