### ISSUE TITLE
sidecar injection using annotation

### ISSUE THREAD

**Issue by sb1975** [istio/istio#25252]
**Bug description**
Reg the topic of selective sidecar injection to a specific pod in a namespace. 
(Ref: https://istio.io/latest/docs/ops/configuration/mesh/injection-concepts/ )

I suppose below is possible :

1.  label the namespace(with istio-injection=enabled) 
2.  modify the configmap istio-sidecar-injector( with config: |-     policy: disabled)
3.  and Annotate the pod (with annotations: sidecar.istio.io/inject: "true"). 

But why do I get Readiness probe error when I describe a pod which was injected with the sidecar ?

  Normal   Started    42s                kubelet, kubernetes  Started container productpage
  Normal   Pulling    42s                kubelet, kubernetes  Pulling image "docker.io/istio/proxyv2:1.6.4"
  Normal   Pulled     41s                kubelet, kubernetes  Successfully pulled image "docker.io/istio/proxyv2:1.6.4"
  Normal   Created    41s                kubelet, kubernetes  Created container istio-proxy
  Normal   Started    41s                kubelet, kubernetes  Started container istio-proxy
  Warning  Unhealthy  30s (x5 over 38s)  kubelet, kubernetes  Readiness probe failed: Get http://192.168.192.120:15021/healthz/ready: dial tcp 192.168.192.120:15021: connect: connection refused

What additional configuration is needed please?

[ ] Configuration Infrastructure
[ x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[x ] Test and Release
[x ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**
1.6.4
**Environment where bug was observed (cloud vendor, OS, etc)**
ubuntu 18.04
Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive
) by attaching
the dump file to this issue.
[istio-dump.tar.gz](https://github.com/istio/istio/files/4880658/istio-dump.tar.gz)

**Comment by howardjohn** [comment]
We will need the logsfrom the pod failing readiness please

**Comment by howardjohn** [comment]
We don't have enough info to diagnose this further. Please reopen if you can provide it. Thanks!
