### ISSUE TITLE
mixer client service config should be in per-route opaque data

### ISSUE THREAD

**Issue by qiwzhang** [istio/istio#2527]
service config in the mixer client is a global map in the mixer filter config.  Each time when routes are changed,  need to update that map, which means it need to update the listener config.

Here is the proposal:

* Pilot start to write per-route service_config into opaque data as "mixer_service_config" (based64 encoded proto in json format for easy debugging, proto binary is not easy to decode it).

* Proxy will check this attribute, if exist, use it, not to use service_configs map. Otherwise, use the one from service_configs map for backward compatibilty

**Comment by qiwzhang** [comment]
Please see detail discussion in https://github.com/istio/istio/issues/2418

**Comment by mandarjog** [comment]
This also makes `egress` mixer configuration more natural. We should be able to specify it as opaque metadata on the route or the vhost.

**Comment by rshriram** [comment]
This will be evolved per recent Envoy PR to support route local info
