### ISSUE TITLE
VMs failing IPV6 integration test 

### ISSUE THREAD

**Issue by ZhengzheYang** [istio/istio#25289]
**Bug description**
After #24919 is merged, VM could now send requests to the pods in the cluster and the DNS could be automatically resolved. However, VMs seem to fail under ipv6 settings. More specifically, it's failing `integ-ipv6-k8s-tests_istio` for all connections from VMs to other pods. It would fail a small number of cases in `integ-distroless-k8s-tests_istio` as well (not failing all cases). 

This is just for tracking purpose. cc @howardjohn @rshriram 

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[X] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Not fail `integ-ipv6-k8s-tests_istio` test. 

**Steps to reproduce the bug**
Send requests from a VM to a regular pod under ipv6 setting.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/25096/integ-ipv6-k8s-tests_istio/1583
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/25096/integ-distroless-k8s-tests_istio/8661

**Comment by howardjohn** [comment]
This may allow us to enable it for the ipv6 one but doesn't fix it yet since the test isn't enabled I think
