### ISSUE TITLE
VM testing with first-party-jwt and certs provided by kubernetes

### ISSUE THREAD

**Issue by ZhengzheYang** [istio/istio#25286]
#25096 tries to enable the `meshExpansion` for [`security/mtls_first_party_jwt/TestMtlsStrictK8sCA`](https://github.com/istio/istio/blob/master/tests/integration/security/mtls_first_party_jwt/strict_test.go) and [`security/mtlsk8sca/TestMtlsStrictK8sCA`](https://github.com/istio/istio/blob/master/tests/integration/security/mtlsk8sca/strict_test.go) so that they could build the test instances including a VM by calling CreateContext() from [`security/util/reachability/context.go`](https://github.com/istio/istio/blob/master/tests/integration/security/util/reachability/context.go#L70). 

However, current VM setup does not support first-party-jwt and the certs provided by kubernetes ([VM deployment yaml](https://github.com/istio/istio/blob/master/pkg/test/framework/components/echo/kube/deployment.go#L193))

This issue aims to track the progress of the development of VM support in issuing certificates and using first-party-jwt. 

cc @yangminzhu @lei-tang @howardjohn

**Comment by howardjohn** [comment]
#26140

**Comment by kailun-qin** [comment]
Reopening this one as it seems that the current testing VM setup still does not support first-party-jwt and the certs provided by K8s yet according to [vmDeploymentYaml](https://github.com/istio/istio/blob/master/pkg/test/framework/components/echo/kube/deployment.go#L284), though `meshExpansion` was deprecated. cc @howardjohn

**Comment by howardjohn** [comment]
I don't think we should support this. All recent Kubernetes version support third party, so there is not a good reason to invest time here IMO.

**Comment by howardjohn** [comment]
I am pretty sure you can do it if you really want to, anyhow, just our tooling/tests don't handle it
