### ISSUE TITLE
automate creation of release tar.gz

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#253]
repurposing this issue/task to clean up
https://github.com/istio/istio/releases/download/${ISTIO_VERSION}/istio.tar.gz

cc @sebastienvas

**Comment by ldemailly** [comment]
https://github.com/istio/istio.github.io/pull/180

**Comment by ldemailly** [comment]
I think the tar should have the directory name
also we should prune all the unnecessary dot and mac files (probably because @rshriram did the latest on manually on a mac ?)

-rw-r--r--  0 shriram staff      120 May 11 09:41 istio/install/._.DS_Store
-rw-r--r--  0 shriram staff     6148 May 11 09:41 istio/install/.DS_Store
-rwxr-x---  0 shriram staff      222 May 10 21:49 istio/install/._kubernetes
...

**Comment by sebastienvas** [comment]
@rshriram created that tar. What do you mean by "the tar should have the directory name"?

**Comment by ldemailly** [comment]
Sorry my comment was not clear, updated

As we chatted with @andraxylia and @sebastienvas :

- we'll put just the yaml and no mac specific or other extra files
- we'll put istioctl binary in a bin/ subdirectory
- the top level directory will be istio-X.Y.Z (aka have the version)
- the archive names will be istio-osx.tar.gz istio-linux.tar.gz and istio_win.zip (with the version being in the parent directory of the url - ie : https://github.com/istio/istio/releases/download/${ISTIO_VERSION}/istio-${OSEXT}.tar.gz (PR #266 )


note: it may be good to repeat the version in the filename of the archive too if we ever have the releases in a single directory like usually done

**Comment by ldemailly** [comment]
to set the owner/group in the tar (can be any string) : 
```
tar --owner=releng --group=releng -c -v -z -f  /tmp/blah.tar.gz ....
```
