### ISSUE TITLE
Add config for disable control plane security

### ISSUE THREAD

**Issue by dozer47528** [istio/istio#25315]
**Describe the feature request**

We want to analysis some xDS issues by tcpdump. But with control plane security it's very hard to do that.

Based on the Istio 1.5 release note, it looks that the control plane security is always on since Istio 1.5: https://istio.io/latest/news/releases/1.5.x/announcing-1.5/upgrade-notes/#control-plane-security

[x] Networking

**Comment by howardjohn** [comment]
This can be done by setting discovery address to 15010 and controlPlaneAuthPolicy to NONE (with caveat the 1.7 alphas are broken - see https://github.com/istio/istio/issues/25503)
