### ISSUE TITLE
istio 1.6.3 imagePullSecrets prometheus Not in force

### ISSUE THREAD

**Issue by xiaowujee** [istio/istio#25310]
**istio 1.6.3 imagePullSecrets prometheus Not in force**

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**set global.imagePullSecrets,promethrus deployment use imagePullSecrets**

**Steps to reproduce the bug**
1. create istioOperator, reference demo,update  global.imagePullSecrets、 global.hub、prometheus.hub
2. set global.imagePullSecrets
3. implement `istioctl install -f ***.yaml`
4. prometheus can not install

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.6.3

**How was Istio installed?**
istioctl  use custom configuration
`istioctl install -f ***.yaml`

**Environment where bug was observed (cloud vendor, OS, etc)**

centos

**Comment by morvencao** [comment]
Do you mean the `global.imagePullSecret` doesn't work for prometheus deployment?

**Comment by xiaowujee** [comment]
> 您是说`global.imagePullSecrets`不适用于Prometheus部署吗？

yes

prometheus charts  deployment.yaml not use `global.imagePullSecrets`

**Comment by morvencao** [comment]
Please append your istioOperator yaml that is used to deploy istio.
