### ISSUE TITLE
Istio 1.6.4 multicluster shared control plane configuration does not work on AWS EKS

### ISSUE THREAD

**Issue by serrien** [istio/istio#25325]
**Bug description**

Multicluster shared control plane require IPs.

Multicluster shared control plane does not work on AWS for two reasons.

First, the `remotePilotAddress` field for the remote cluster mesh configuration require a valid IP address but on AWS, Loadbalancer (used to expose istiod on the master cluster) don't have a unique IP. There is 3 IPs which are mutable so we can't use them since it can break at any time. 
The deployment failed if we set the dns name of the loadbalancer for `remotePilotAddress` field.

Secondly, in the master cluster mesh configuration, the gateway configuration require a field `address` in addition to the fields
`registry_service_name` and  `port` (even if the documentation doesn't mention it). The value for the `address` field must be an IP, which is a problem.
If this field is not populate, applications can't make request from one cluster to the other because endpoints are not created on the other cluster

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
 The `remotePilotAddress` field for the remote cluster mesh configuration should accept a dns name (possibly referencing multiple IPs).

In the master cluster mesh configuration, the gateway configuration must work as describe int the documentation, without `address` field in the mesh configuration.

**Steps to reproduce the bug**

1. Create two EKS private clusters
2. Deploy Istio on master cluster
3. Deploy Istio on remote cluster including the following configuration : 

  values:
    pilot:
      traceSampling: 0.1
    sidecarInjectorWebhook:
      rewriteAppHTTPProbe: true
    global:
      # The remote cluster's name and network name must match the values specified in the
      # mesh network configuration of the main cluster.
      multiCluster:
        clusterName: remote1
      network: network1

      # Replace ISTIOD_REMOTE_EP with the the value of ISTIOD_REMOTE_EP set earlier.
      remotePilotAddress: xxxxxxxxxx-xxxx.elb.eu-west-3.amazonaws.com

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

Istio : 1.6.4
kubectl : 1.18.0 (client) and v1.16.8-eks-e16311 (server) 

**How was Istio installed?**

istioctl install -f my-istio-operator-v1alpha1.yaml

**Environment where bug was observed (cloud vendor, OS, etc)**

AWS EKS 1.16

**Comment by kenerwin88** [comment]
This is still an issue, and a blocker for using Istio in multi cluster environments on AWS.
