### ISSUE TITLE
Sidecar deb file missing telemetry wasm filters

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#25338]
I am pretty sure we don't package the .wasm files into the .deb we ship. I did not verify this myself, just looking at the build code

cc @douglas-reid

**Comment by douglas-reid** [comment]
We do not package the `.wasm` files. Is this a request to ship them? This feels like something that should be covered by the forthcoming extensions API. @mandarjog thoughts?

**Comment by howardjohn** [comment]
We package them for the docker images though right? Seems like it should be consistent? This is not really a request necessarily, I just noticed it and figured it was not intended - happy to be told its working as expected

**Comment by mandarjog** [comment]
We should add our own extensions to the deb package for consistency with the docker build.

Bit distribution will be orthogonal.

**Comment by douglas-reid** [comment]
Consistency is fine. How is this orthogonal to bit distribution though? At best, this is a special casing for blessed extensions. Getting Wasm extensions to the VMs needs a general solution.

**Comment by mandarjog** [comment]
I agree bit distribution needs to be solved for vms and k8s.

**Comment by kyessenov** [comment]
It would be clean to have istio docker image to be just `dpkg -i proxy.deb`. If we don't align, then the default install configs probably break on VMs under some options.

**Comment by howardjohn** [comment]
Fixed by https://github.com/istio/istio/blob/07232fcb2989492f68b76f92c4ac24c3ff986f1f/tools/packaging/packaging.mk#L41. We have tests for this now too.
