### ISSUE TITLE
Remove initial_fetch_timeout from SDS clusters for workload

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#25339]
Unlikely gateway, where a secret may legitimately not exist in the cluster, we expect to always fetch the `default` and `ROOTCA` cert. As a result, we should remove the initial_fetch_timeout so we wait indefinitely for it.

cc @lambdai @JimmyCYJ

**Comment by lambdai** [comment]
> we expect to always fetch the default and ROOTCA cert.

FWIK the fallback on timeout is a predefined "thing" (forgive me I don't know the exact behavior), definitely not the `default`.

Is `default` better than that "thing"?

**Comment by JimmyCYJ** [comment]
`default` and `ROOTCA`  are the predefined SDS resource names, `default` is the resource for key/cert and `ROOTCA` is the one for root cert. Shall we just set it to 0 [here](https://github.com/istio/istio/blob/7b7a581c0297da7f90c019460e5d1ac16aca12de/pilot/pkg/security/model/authentication.go#L128) , to let workload proxy to wait for the resources without a timeout?

**Comment by howardjohn** [comment]
That's what I was suggesting Jimmy, yeah.

**Comment by williamaronli** [comment]
@adiprerepa thanks for your fix and  thanks howard for the test and confirmed it is fixed
