### ISSUE TITLE
Mixer removal tracking

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#25333]
Track efforts for https://docs.google.com/document/d/1abYN18B8JyV64EFHtNm0uSIM4DNRX8JddJiwacNBoHg/edit

**Comment by howardjohn** [comment]
PR | Repo | Artifact | Outcome
-- | -- | -- | --
todo | istio/api | mixer/ subdirectory | Removed
todo | istio/api | policy/ subdirectory | Removed
todo | istio/api | MeshConfig fields:mixer_check_servermixer_report_serverdisable_policy_checksdisable_mixer_http_reportspolicy_check_fail_opensidecar_to_telemetry_session_affinitymixer_addressdisable_report_batchreport_batch_max_entriesreport_batch_max_time | Removed (field numbers reserved)
todo | istio/api | annotations/annotations.yaml:All policy.istio.io/* annotations | Removed
todo | istio/proxy | include/istio/utilsEverything but status.hsrc/istio/utilsattribute_names.cclocal_attributes.cclogger.cclogger.hlogger_test.ccprotobuf.ccsimple_lru_cache_test.cc | Removed
todo | istio/proxy | include/istiocontrol/mixerclient/prefetch/quota_config/src/istiocontrol/mixerclient/prefetch/quota_config/ | Removed
todo | istio/proxy | src/envoy/http/mixer/ subdirectory | Removed
todo | istio/proxy | src/envoy/tcp/mixer/ subdirectory | Removed
todo | istio/proxy | test/integration/ subdirectory | Removed
todo | istio/istio | mixer subdirectory | Removed
todo | istio/istio | tests/integration/mixerpolicy packagecheck_test.goreport_test.gotelemetry/logs package | Removed
todo | istio/istio | tests/integration/mixer/outboundtrafficpolicyall but v2 package (and deps) | Removed
todo | istio/istio | tests/integration/mixer/telemetry/metricsistioctl_metrics_test.gotests/integration/mixer/outboundtrafficpolicy/v2 package | Moved to new location (tests/integration/telemetry)
todo | istio/istio | tests/integration/mixer/telemetry/metricsnew_metric_test.goscenarios_test.go | Removed
todo | istio/istio | manifests/charts/istio-policy | Removed
todo | istio/istio | manifests/charts/istio-telemetry/mixer-telemetry | Removed
todo | istio/istio | manifests/charts/base/crds | Removed
todo | istio/istio | manifests/charts/global.yamldisablePolicyCheckspolicyCheckFailOpenremotePolicyAddressremoteTelemetryAddress | Removed (and dependent charts updated)
todo | istio/istio | manifests/charts/istio-telemetry/prometheusmanifests/charts/istio-telemetry/prometheusOperator all references to istio-telemetry, istio-policy, mixer | Removed
todo | istio/istio | manifests/profiles/All references to telemetry.v1, policy, mixer | Removed (and dependent charts updated)
todo | istio/istio | manifests/charts/istio-telemetry/grafana/dashboardsmixer_dashboard.json | Removed
todo | istio/istio | pilot/pkg/networking/plugin/mixer/client package | Removed
todo | istio/istio | pilot/pkg/networking/plugin/mixer package | Removed (with config metadata annotation functionality moved to a different plugin, as needed)
todo | istio/istio | pkg/test/framework/components/mixer | Removed
todo | istio/istio | bin/mixer_codegen.sh | Removed
todo | istio/istio | README.md | Updated to remove all mention of Mixer
todo | istio/istio.io | *All* content mentioning Mixer and Adapters except:Blog postsRelease notes | Removed (links to Mixer pages removed from blog posts, release notes)
todo | istio/test-infra | All references to Mixer tests | Removed
todo | istio/tools | perf_dashboard tooling for Mixer | Removed
todo | istio/installer | (see istio/istio manifest package actions) | (see istio/istio manifest package actions)
todo | istio/release-builder | References to mixer_dashboard.json. | Removed

**Comment by howardjohn** [comment]
https://github.com/istio/test-infra/pull/2761
https://github.com/istio/release-builder/pull/307

**Comment by howardjohn** [comment]
The last thing I have found is `manifests/addons/dashboards/istio-performance-dashboard.json`

**Comment by douglas-reid** [comment]
@howardjohn can we close this now?

**Comment by howardjohn** [comment]
I think so

**Comment by howardjohn** [comment]
Nice work everyone!

**Comment by craigbox** [comment]
Release note says "For more details, please refer the docs on istio.io." but I can't find such docs on prelim.

**Comment by douglas-reid** [comment]
@craigbox Perhaps this is the doc you are looking for: https://github.com/istio/istio/wiki/Enabling-Envoy-Authorization-Service-and-gRPC-Access-Log-Service-With-Mixer
