### ISSUE TITLE
kubectl explain envoyfilter is empty

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#25348]
**Bug description**
```
[root@master01 envoyfilter]# kubectl explain envoyfilter
KIND:     EnvoyFilter
VERSION:  networking.istio.io/v1alpha3

DESCRIPTION:
     <empty>
```

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
[root@master01 envoyfilter]# istioctl version
client version: 1.6.1
control plane version: 1.6.1
data plane version: 1.6.1 (14 proxies)
```
```
[root@master01 envoyfilter]# kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2020-05-12T09:28:18Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"linux/amd64"}
```
**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by jasonwzm** [comment]
Thanks for raising the issue.

This is a known issue. It is empty because we could not produce a structural schema for EnvoyFilter. I am working on a fix for it.
