### ISSUE TITLE
Mixer 0.4.0 memory usage grows steadly when stdio adapter is enabled

### ISSUE THREAD

**Issue by jnativio** [istio/istio#2534]
I have noticed that the memory used by the Mixer pod grows continuously as load is driven to the microservices under Istio 0.4.0. I have not seen this in previous releases.

![image](https://user-images.githubusercontent.com/18554027/34792401-e78e9540-f615-11e7-9b7b-fd26e0aa494e.png)

When disabling the stdio adapter (kubectl -n istio-system delete rule stdio), the memory used by the Mixer grows modestly during the run:

![image](https://user-images.githubusercontent.com/18554027/34792682-d0557924-f616-11e7-9104-6f263f066d0e.png)

To reproduce the issue, drive some significant load into Istio 0.4.0 with the stdio rule enabled (default), while monitoring the memory usage by the Mixer container (e.g., docker stats).

Environment:
OS version:
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"

Kube version:
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:55:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.4-2+eb9172c211dc41", GitCommit:"eb9172c211dc4108341c0fd5340ee5200f0ec534", GitTreeState:"clean", BuildDate:"2017-11-16T08:13:08Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

Istio version:
Version: 0.4.0
GitRevision: 24089ea97c8d244493c93b499a666ddf4010b547
GitBranch: 6401744b90b43901b2aa4a8bced33c7bd54ffc13
User: root@cc5c34bbd1ee
GolangVersion: go1.9.1

**Comment by douglas-reid** [comment]
@geeknoid any thoughts?

**Comment by geeknoid** [comment]
No idea. It could be mixer proper doing something dumb, it could be the adapter, or it could be zap.

Given that Mixer's memory consumption continues to increase when the adapter is disabled, just slower, I'm inclined to think this is something in zap.

**Comment by mandarjog** [comment]
@jnativio any change in this with 0.5pre builds?

**Comment by jnativio** [comment]
I have not observed this behavior in the latest builds. There is an light increase of memory usage during the load, but nothing like before.
![image](https://user-images.githubusercontent.com/18554027/35294331-4677604a-0044-11e8-90c3-4a5af3d02825.png)

**Comment by geeknoid** [comment]
Well, that's good and bad. It's good that it seems to be working. It's bad
that I have no idea what changed to make it work :-( Let's leave the bug
open until I can delve into it.

**Comment by geeknoid** [comment]
Let's mark this as not repro and keep an eye out for recurrence.
