### ISSUE TITLE
Istio service dashboard in grafana has no metrics 

### ISSUE THREAD

**Issue by 4dithya** [istio/istio#25351]
**Bug description**
In one of our older istio installations(v1.1.8) the grafana istio service dashboard has no data. However few other dashboards do have data.

Grafana pod logs is filled with these lines

>2020/07/08 07:17:54 http: proxy error: context canceled
t=2020-07-08T07:17:54+0000 lvl=info msg=“Request Completed” logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/1/api/v1/query_range status=502 remote_addr=192.168.9.120 time_ms=1501 size=0 referer=https://example.com/d/LJ_uJAvmk/istio-service-dashboard

and telemetry pods logs
>
    2020-07-08T09:50:36.017416Z error api Report failed: 1 error occurred:

        failed to report all values: 4 errors occurred:
        * could not find metric info from adapter config for requestcount.instance.istio-system
        * could not find metric info from adapter config for requestduration.instance.istio-system
        * could not find metric info from adapter config for requestsize.instance.istio-system
        * could not find metric info from adapter config for responsesize.instance.istio-system

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
All data about deployed services to be available on the istio service dashboard.

**Steps to reproduce the bug**
Accessing the istio service dashboard, grafana

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
>client version: 1.4.3
citadel version: 1.1.8
citadel version: 1.4.3
galley version: 1.1.8
ingressgateway version: 1.1.8
ingressgateway version: 1.1.8
ingressgateway version: 1.1.8
pilot version: 1.1.8
pilot version: 1.1.8
policy version: 1.1.8
policy version: 1.1.8
sidecar-injector version: 1.1.8
telemetry version: 1.1.8
telemetry version: 1.1.8
data plane version:  (32 proxies)

>Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.10", GitCommit:"37d169313237cb4ceb2cc4bef300f2ae3053c1a2", GitTreeState:"clean", BuildDate:"2019-08-19T10:44:49Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
helm

**Environment where bug was observed (cloud vendor, OS, etc)**
centos 7.5, kubeadm cluster 

>NAME                                                 TYPE                                  DATA   AGE
default-token-sjs9r                                  kubernetes.io/service-account-token   3      236d
istio-ca-secret                                      istio.io/ca-root                      2      176d
istio-citadel-service-account-token-5mb67            kubernetes.io/service-account-token   3      236d
istio-cleanup-secrets-service-account-token-k2k9l    kubernetes.io/service-account-token   3      236d
istio-egressgateway-service-account-token-lxhz4      kubernetes.io/service-account-token   3      236d
istio-galley-service-account-token-ll9pt             kubernetes.io/service-account-token   3      236d
istio-grafana-post-install-account-token-5rvnt       kubernetes.io/service-account-token   3      236d
istio-ingressgateway-service-account-token-ffcxm     kubernetes.io/service-account-token   3      236d
istio-init-service-account-token-cdcc6               kubernetes.io/service-account-token   3      163d
istio-mixer-service-account-token-s48v5              kubernetes.io/service-account-token   3      236d
istio-multi-token-st2h9                              kubernetes.io/service-account-token   3      176d
istio-pilot-service-account-token-7w9dk              kubernetes.io/service-account-token   3      236d
istio-policy-service-account-token-hchk5             kubernetes.io/service-account-token   3      162d
istio-reader-service-account-token-ltcm2             kubernetes.io/service-account-token   3      162d
istio-security-post-install-account-token-jv7kk      kubernetes.io/service-account-token   3      176d
istio-sidecar-injector-service-account-token-s2dwv   kubernetes.io/service-account-token   3      236d
istio.default                                        istio.io/key-and-cert                 3      162d
istio.istio-citadel-service-account                  istio.io/key-and-cert                 3      162d
istio.istio-cleanup-secrets-service-account          istio.io/key-and-cert                 3      162d
istio.istio-egressgateway-service-account            istio.io/key-and-cert                 3      162d
istio.istio-galley-service-account                   istio.io/key-and-cert                 3      162d
istio.istio-grafana-post-install-account             istio.io/key-and-cert                 3      162d
istio.istio-ingressgateway-service-account           istio.io/key-and-cert                 3      162d
istio.istio-init-service-account                     istio.io/key-and-cert                 3      162d
istio.istio-mixer-service-account                    istio.io/key-and-cert                 3      162d
istio.istio-multi                                    istio.io/key-and-cert                 3      162d
istio.istio-pilot-service-account                    istio.io/key-and-cert                 3      162d
istio.istio-policy-service-account                   istio.io/key-and-cert                 3      162d
istio.istio-reader-service-account                   istio.io/key-and-cert                 3      162d
istio.istio-security-post-install-account            istio.io/key-and-cert                 3      162d
istio.istio-sidecar-injector-service-account         istio.io/key-and-cert                 3      162d
istio.prometheus                                     istio.io/key-and-cert                 3      162d
prometheus-token-sfg2v                               kubernetes.io/service-account-token   3      236d

>galley-envoy-config                                                  1      162d
injector-mesh                                                        1      162d
istio                                                                2      236d
istio-crd-10                                                         1      163d
istio-crd-11                                                         1      163d
istio-crd-14                                                         1      163d
istio-galley-configuration                                           1      236d
istio-grafana                                                        2      176d
istio-grafana-configuration-dashboards-citadel-dashboard             1      163d
istio-grafana-configuration-dashboards-galley-dashboard              1      176d
istio-grafana-configuration-dashboards-istio-mesh-dashboard          1      176d
istio-grafana-configuration-dashboards-istio-performance-dashboard   1      176d
istio-grafana-configuration-dashboards-istio-service-dashboard       1      176d
istio-grafana-configuration-dashboards-istio-workload-dashboard      1      176d
istio-grafana-configuration-dashboards-mixer-dashboard               1      176d
istio-grafana-configuration-dashboards-pilot-dashboard               1      176d
istio-grafana-custom-resources                                       2      236d
istio-ingress-controller-leader-istio                                0      236d
istio-mesh-galley                                                    1      162d
istio-security                                                       1      236d
istio-security-custom-resources                                      2      236d
istio-sidecar-injector                                               1      236d
istio-statsd-prom-bridge                                             1      236d
pilot-envoy-config                                                   1      162d
policy-envoy-config                                                  1      162d
prometheus                                                           1      236d
telemetry-envoy-config                                               1      162d

**Comment by howardjohn** [comment]
Istio 1.1 has not been supported for well over a year: https://istio.io/blog/2019/announcing-1.1-eol/. Please upgrade to a supported version, and if you still have issues we can address then. Thanks!
