### ISSUE TITLE
1.6 Upgrade - Warn found CRD of unsupported v1alpha1 security policy

### ISSUE THREAD

**Issue by adamcarter81** [istio/istio#25353]
**Bug description**
I have had this warning message for the last few minor upgrades, but I can't find what is causing it:

`2020-07-09T09:05:45.390180Z     warn    found 4 CRD of unsupported v1alpha1 security policy: [clusterrbacconfigs.rbac.istio.io rbacconfigs.rbac.istio.io servicerolebindings.rbac.istio.io serviceroles.rbac.istio.io]. The v1alpha1 security policy is no longer supported starting 1.6. It's strongly recommended to delete the CRD of the v1alpha1 security policy to avoid applying any of the v1alpha1 security policy in the unsupported version
Upgrade version check passed: 1.6.3 -> 1.6.4.`

Every check shows no resources found:

```
PS C:\repos\aks-lab-001\istio-1.6.4> kubectl get policies.authentication.istio.io --all-namespaces
error: the server doesn't have a resource type "policies"
PS C:\repos\aks-lab-001\istio-1.6.4> kubectl get meshpolicies.authentication.istio.io --all-namespaces
error: the server doesn't have a resource type "meshpolicies"
PS C:\repos\aks-lab-001\istio-1.6.4> kubectl get rbacconfigs.rbac.istio.io --all-namespaces
No resources found
PS C:\repos\aks-lab-001\istio-1.6.4> kubectl get clusterrbacconfigs.rbac.istio.io --all-namespaces
No resources found
PS C:\repos\aks-lab-001\istio-1.6.4> kubectl get serviceroles.rbac.istio.io --all-namespaces
No resources found
PS C:\repos\aks-lab-001\istio-1.6.4> kubectl get servicerolebindings.rbac.istio.io --all-namespaces
No resources found

```
This installation has been upgraded from 1.4 -> 1.5 -> 1.6 and I thought  I had upgraded previous CRDs to allow the 1.6 upgrade to pass, but I keep getting this and I can't work out what/where the security policies are - how can I find them?

Thanks

**Comment by esnible** [comment]
It is complaining about CRDs, not use of the cRDs.

Use `kubectl delete crd <type>` to get rid of them.

**Comment by adamcarter81** [comment]
Ah of course, I remember doing this on the 1.6 upgrade - thanks for your help!
