### ISSUE TITLE
TestCreatePluggedCertCA test flake

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#25362]

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gcs/istio-prow/logs/unit-tests_istio_postsubmit/2928

**Comment by JimmyCYJ** [comment]
@myidpt Could you please take a look and find someone to get it fixed?

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/25275/unit-tests_istio/16279

**Comment by knight42** [comment]
I have filed #25446 to address this issue.
