### ISSUE TITLE
Additional metadata in stackdriver logging telemetry v2 extension

### ISSUE THREAD

**Issue by rsalmond** [istio/istio#25375]
**Describe the feature request**

The `httpRequest.requestUrl` field presently reported by the stackdriver logging extension represents the resulting URL after any virtualservice rewrite rules have been applied at the request source proxy. We would specifically like to log the pre-rewrite URL in context with the other data captured at the target proxy, and in general we're missing the flexibility of field customization afforded by the rules and instances model of telemetry v1.

**Describe alternatives you've considered**

Since envoy access logs can extract headers we are going to rely on the `X-ENVOY-ORIGINAL-PATH` header for the time being but this is inconvenient as it adds an extra step to correlate the envoy access log entry with the one emitted to stackdriver by the extension.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

cc @mandarjog

**Comment by bianpengyuan** [comment]
This particualr field has been added by https://github.com/istio/proxy/pull/2949
