### ISSUE TITLE
Use "allowlist"/"denylist" instead of exclusionary language

### ISSUE THREAD

**Issue by tbarrella** [istio/istio#25381]
**Describe the feature request**
Replace "whitelist" with "allowlist" and "blacklist" with "denylist" throughout Istio APIs and code

Also see https://github.com/envoyproxy/envoy/issues/11596 which discusses formalizing a policy around this. Maybe it would be helpful for us to establish one as well?

**Describe alternatives you've considered**
Potentially other terms, such as "blocklist." Using "allowlist" and "denylist" would be consistent with Envoy, for example

**Details**
Repos that need to be updated include
- [x] api
- [x] common-files
- [x] istio
- [x] proxy
- [x] release-builder
- [x] test-infra
- [x] tools

Searching for `(white|black).?list`, the only public API that I've found so far is the `blacklist` field in the [List Mixer adapter](https://istio.io/latest/docs/reference/config/policy-and-telemetry/adapters/list/), although it appears that this is deprecated

license-lint uses `whitelisted_modules` for configuration; if necessary we could stage the change for this

**Comment by costinm** [comment]
Can we just use allow: and 'deny' ? We don't use the suffix 'list' on everything that is a list.

**Comment by tbarrella** [comment]
Makes sense to me depending on the context. For me, allowlist has a more specific meaning that can be less ambiguous by indicating exceptional behavior

**Comment by tbarrella** [comment]
I think this is basically done for now. Using
```sh
rg -i '(white|black).?($|list)'
```
the remaining occurrences are one of

- Usages of non-Istio APIs, e.g. `awesome_bot --white-list`
- Generated by non-Istio code, e.g. comments in `common-protos/`
- Historical records, e.g. the changelog in `test-infra/prow/genjobs/README.md`
- Directly related to Mixer, which is being removed (#25333)

In addition to the repos in the initial comment, I checked other non-deprecated repos (bots, client-go, cri, gogo-genproto, pkg). For the istio.io repo, it seems like that will be ok once 1.7 docs are generated and Mixer is removed

Note that there are a couple occurrences in the proxy repo but both in common/, so they should be removed once a newer version of common-files is pulled in

**Comment by tbarrella** [comment]
Thanks to Mixer code being removed now, this should be done
