### ISSUE TITLE
Use /var/run/gateway/ as SDSUdsPath for Gateways

### ISSUE THREAD

**Issue by nschhina** [istio/istio#25395]
Currently, we use `/var/run/ingress_gateway` for sdsudspath. With https://github.com/istio/istio/issues/25369, we should no longer have "ingress gateways" or "egress gateways" differentiated anywhere visible to the end user. Changing the path to `/var/run/gateway/` is definitely more correct as we don't have any "ingress_gateway" entity.

**Comment by JimmyCYJ** [comment]
Thanks for filing this issue!

**Comment by howardjohn** [comment]
I don't think this is worth the pain, to be honest. There is real cost associated with changing it, and no real user benefit.

if we merged it with the workload SDS stuff then maybe, but that is moving to istiod anyways most likely now

**Comment by nschhina** [comment]
Sure, but I'll leave this open for future reference as this is something that should be done some time in the future, but can be handled during move to istiod.

**Comment by howardjohn** [comment]
Superseded by https://github.com/istio/istio/issues/24667
