### ISSUE TITLE
Adapter config SHA1 signature logic is likely to produce poor results.

### ISSUE THREAD

**Issue by ozevren** [istio/istio#2539]
We're using a SHA1 signature to detect if an adapter's config has changed or not, and decide to reuse the adapter based on that.

The signature code uses serialized proto form of the configuration for this purpose. However, this can potentially yield poor results, especially when config pieces include maps:
https://play.golang.org/p/Afqx-kG5s34

**Comment by kyessenov** [comment]
Oh no, another protobuf serialization as a hash bug.

**Comment by kyessenov** [comment]
/cc @bianpengyuan @mandarjog @douglas-reid 
Found this while reviewing code in this area...

**Comment by douglas-reid** [comment]
@kyessenov am I right in assuming that this is no longer a priority and not likely to be patched at this point?

**Comment by kyessenov** [comment]
Yes, it remains a known issue, but hopefully it's not correctness bug. I think this may cause unnecessary config reload which is OK.

**Comment by douglas-reid** [comment]
Closing, based on understanding of impact and unlikely attention (given forthcoming known shift in architecture).
