### ISSUE TITLE
Istio sidecar not mounting certs from k8s secret

### ISSUE THREAD

**Issue by JacobSMoller** [istio/istio#25417]
**Bug description**
After upgrading istio with istioctl, to both 1.5.0, 1.5.7 and latest 1.6.5, previously we used helm templates and kubectl apply, my istio sidecars are no longer mounting certs in /etc/certs. 

We run an envoy proxy ourself, which is used as the backend for a google ingress. However the envoy expects to be able to find certs in /etc/certs, which are no longer present on the sidecars. 

[ ] Configuration Infrastructure
[ ] Docs
[x ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
mount certs from k8s secret in the namespace. 
**Steps to reproduce the bug**
install istio using istioctl and some standard operator configuration.
**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```bash
client version: 1.6.5
control plane version: 1.6.5
data plane version: 1.6.5 (29 proxies),  (4 proxies)
```

```bash
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-19T13:57:45Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.9-gke.24", GitCommit:"39e41a8d6b7221b901a95d3af358dea6994b4a40", GitTreeState:"clean", BuildDate:"2020-02-29T01:24:35Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```
**How was Istio installed?**
istioctl install -f istio-operator.yaml

istio-opeator.yaml was generated using 
```bash
istioctl manifest migrate values.yaml > istio-operator.yaml
```

**Environment where bug was observed (cloud vendor, OS, etc)**
Pods are run on GKE in linux containers running go binaries.
Local os is MacOS catalina 10.15.5 (19F101)

**Comment by howardjohn** [comment]
This is no longer how cert provisioning works. See https://istio.io/latest/blog/2020/istiod/ and https://istio.io/latest/news/releases/1.5.x/announcing-1.5/upgrade-notes/ for more info
