### ISSUE TITLE
Do not enable mTLS if server is already used TLS

### ISSUE THREAD

**Issue by diemtvu** [istio/istio#2542]
Istio mTLS does not work with existing TLS. At the moment, it's required that customers disable it manually (via service annotation). However, it could be better that Istio do not setup mTLS if knowing TLS is used (e.g based on port name prefix).

**Comment by diemtvu** [comment]
Probably not an issue.

**Comment by kyessenov** [comment]
mTLS is used to pass information reliably from source to destination using TLS metadata.
It is useful even if the app already uses mTLS for this reason.
