### ISSUE TITLE
Consider reducing webhook timeout

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#25436]
https://github.com/kubernetes/kubernetes/pull/74562 adds support for custom timeout. 30s is probably 10x larger than what we need. This would make some error cases a bit faster.

cc @jasonwzm @hzxuzhonghu

**Comment by jasonwzm** [comment]
It also mentions that for v1 webhook config the default is 10s. Let's see how that works out. I don't see any issues with that.

**Comment by howardjohn** [comment]
Oh I missed that. SGTM

**Comment by howardjohn** [comment]
Lets just wait for v1
