### ISSUE TITLE
May I ask when I can upgrade envoy in istio to version 1.15.0

### ISSUE THREAD

**Issue by tony-liuliu** [istio/istio#25445]
May I ask when I can upgrade envoy in istio to version 1.15.0, we very much need the local_reply feature in version 1.15.0. Because we will use it to rewrite custom error messages. This way we don’t need to add nginx in front of the gateway Or haproxy to rewrite the error.

**Comment by howardjohn** [comment]
This will be in Istio 1.7. We track 1:1 with Envoy versions (ie Istio 1.6 == Envoy 1.14, istio 1.5 == envoy 1.13)

**Comment by tony-liuliu** [comment]
@howardjohn ok thank you very much。
