### ISSUE TITLE
@robert-blackman You should enable vs delegation by set env `PILOT_ENABLE_VIRTUAL_SERVICE_DELEGATE=true`

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#25448]
@robert-blackman You should enable vs delegation by set env `PILOT_ENABLE_VIRTUAL_SERVICE_DELEGATE=true`

_Originally posted by @hzxuzhonghu in https://github.com/istio/istio/issues/24368#issuecomment-638826358_

can i use delegate in 1.4.10

**Comment by hzxuzhonghu** [comment]
No, the feature is started from 1.6 release
