### ISSUE TITLE
istio upgrade

### ISSUE THREAD

**Issue by yangvipguang** [istio/istio#25453]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
command istio upgrade  does't work well .
![image](https://user-images.githubusercontent.com/11416887/87262048-16607400-c4eb-11ea-82ed-9f62cad4e961.png)
Now the latest version is 1.6.5 .But why istio still upgrade to the current version when i run the command istio upgrade.

**Comment by morvencao** [comment]
Please download the latest istio package and then upgrade with latest `istioctl` binary.

**Comment by yangvipguang** [comment]
@morvencao  thanks ，it works

**Comment by morvencao** [comment]
I'll close this, feel free to reopen it if you still have problem.
