### ISSUE TITLE
istioctl does not find custom profile

### ISSUE THREAD

**Issue by davesargrad** [istio/istio#25477]
This worked in a different way in 1.5. I'm trying to use a custom profile and custom charts.

I am following [these](https://istio.io/latest/docs/setup/install/istioctl/) instructions. These seem to suggest that --set profile=custom1.yaml should be adequate. Yet I see the error message "unsupported profile type"

The profile is seen in the following (with my name). I started by just making this a copy of the existing demo.yaml

![image](https://user-images.githubusercontent.com/48793689/87343124-5ee35600-c51a-11ea-8d47-8b893b051df7.png)

Why doesnt istioctl find my profile? "sargrad.yaml"

**Comment by davesargrad** [comment]
![image](https://user-images.githubusercontent.com/48793689/87344780-02ce0100-c51d-11ea-8278-27ff072834da.png)

**Comment by esnible** [comment]
You can only use `--set profile=` with choices from `istioctl profile list`.

To use the _sargrad.yaml_ file, use `--filename`.
