### ISSUE TITLE
Allow configuration of config/secrets namespace differently than istiod namespace

### ISSUE THREAD

**Issue by linsun** [istio/istio#25480]
**Describe the feature request**

We normally put these config and secrets in the same namespace as istiod.  However, in central istiod, given istiod may not run on the same cluster as config cluster, it is possible istiod is installed in ns1 while the config and secrets are not preferred in the same namespace (e.g. ns1) on the config cluster.  Would be good to allow admins to have such customization.   i think i need a config namespace for the config cluster (which is c2) in my case where it can hold all secrets/configs such as ca-secrets, istio-leader, namespace controller, webhook config and istio configmap etc.

cc @irisdingbj @howardjohn @costinm @sdake 

**Describe alternatives you've considered**
stick them to the same namespace on istiod and control cluster.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[x ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by linsun** [comment]
Possible avail for config https://github.com/istio/istio/blob/7eefa0202cd9e38bec134bd0cc3829ddf9f8d470/pilot/pkg/bootstrap/options.go#L59

**Comment by irisdingbj** [comment]
Do some investigation for this

1.  namespace used when we writing secret is coming from ```
	discoveryCmd.PersistentFlags().StringVarP(&serverArgs.Namespace, "namespace", "n", bootstrap.PodNamespaceVar.Get(),
		"Select a namespace where the controller resides. If not set, uses ${POD_NAMESPACE} environment variable")
```
But  I fail to define `POD-NAMESPACE` due to https://github.com/istio/istio/issues/25490.

2. `INJECTION_WEBHOOK_CONFIG_NAME` in istiod need some tweak as well. Now it depends on the istiod namespace other than the one from `istiod-remote`

wondering whether we need add a new var to define control this.

**Comment by linsun** [comment]
Closing this as we don't have a requirement to make it differently at the moment, will reopen if the need arises.
