### ISSUE TITLE
rbac: utilize ECDS to optimize listener draining

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#25484]
Implement ECDS in Pilot.
Generate RBAC config out-of-band.
Guard HCM with ECDS config source for RBAC.
/cc @yangminzhu

**Comment by yangminzhu** [comment]
Thanks Kuat! Note this is based on the new filter config discovery service in Envoy: https://github.com/envoyproxy/envoy/issues/7867

**Comment by kyessenov** [comment]
@howardjohn How does one go about adding another discovery server? Do we need ADS or ECDS separately? Do we run a separate goroutine or piggy back on pilot?

Preferably, the change should be self-contained to be cherry-pickable across releases.

**Comment by howardjohn** [comment]
Ideally its in ADS and then its pretty easy. https://github.com/istio/istio/pull/25438 is an example adding non-ADS, https://github.com/istio/istio/commit/73f451dfeae0da93e25bd33f127ad17330b5cf44 is an example of adding something over ADS.

> Preferably, the change should be self-contained to be cherry-pickable across releases.

I am pretty concerned about this.. why are we backporting a completely new discovery service?

**Comment by kyessenov** [comment]
ADS is not ideal since we need this to ship multi-megabyte binaries so blocking EDS because of that seems problematic.

**Comment by howardjohn** [comment]
Is there a design doc for this? I don't think anyone has discussed making Pilot a binary distribution system in networking WG

**Comment by kyessenov** [comment]
1. Binary distribution is for Wasm. Wasm binaries need to be distributed one way or another. I'm fine running a distinct server, hence the question. There are several design docs floating around Wasm distribution.
2. If ECDS is separate, then it can run against other control planes (or versions of istio).

**Comment by kyessenov** [comment]
OK, it looks like this needs a design doc. Will get to it eventually (until someone from networking does it first).

**Comment by hzxuzhonghu** [comment]
If it is for wasm distribution, [wasm hub](https://webassemblyhub.io/) seems a good choice

**Comment by kyessenov** [comment]
@hzxuzhonghu webassembly hub relies on `wasme` tool, which is a k8s operator that has a cache, push/pull, and various adapters to inject filter configs. For Istio, is uses an unsupported [EnvoyFilter](https://github.com/solo-io/wasme/blob/master/pkg/deploy/istio/istio_provider.go#L402) API. It could certainly use ECDS to optimize its deployment of Wasm code. This issue is specifically for istio though, while wasme works with gloo and other control planes. Istio can either serve ECDS directly and then wasme would just feed the config to istio, or istio can allow injecting a federated control plane hook, where wasme can plug-in. @yuval-k

**Comment by mandarjog** [comment]
@kyessenov if we can experiment with this thru federation without touching pilot that would be great.
May have to make minimal change to pilot to enable ecds federation.

Also Ecds does not lock us into inline bytes delivery. We can still use url fetch and other byte delivery mechanisms.

**Comment by yuval-k** [comment]
hi, a few notes here:
- webassembly hub doesn't strictly rely on wasme as it uses standard OCI images. I think supporting OCI images is good idea for istio as well.
- we would love to work with you to make sure wasm-hub can work seamlessly with istio in a supported way.
- the operator currently caches because of issues using HTTP transport (even with recent versions; we can provide more details). we plan to change that once envoy-wasm stabilizes.
- both options @kyessenov suggested sound good: wasme to configure istio or istio offer a hook - make a lot of sense to me.

would it make sense to set-up a meeting to discuss how's best to move forward?
I would love to share some insights from the community feedback we got.

**Comment by mandarjog** [comment]
@yuval-k @kyessenov let's setup a call specifically for Wasm.
This thread is about ECDS which is broader.

**Comment by kyessenov** [comment]
@yangminzhu @howardjohn is this something you want to work on in the near future? We need an ECDS server implementation in istiod, unless we're OK ADS'ing it.

**Comment by howardjohn** [comment]
Is there any benefit to *not* using ADS? For WASM its possible a bit different since we would push giant binaries, but for RBAC config I don't know if there are benefits?

**Comment by kyessenov** [comment]
We don't want to special case Wasm. If ADS is fine, then we'll ship Wasm through ADS.
