### ISSUE TITLE
demo error.  registry-1.docker.io server misbehaving

### ISSUE THREAD

**Issue by NeGnail** [istio/istio#2549]
I'm running a demo according to https://istio.io/docs/guides/bookinfo.html。My reviews-v1，reviews-v2，reviews-v3 are in the ErrImagePull state.
log shows:"Warning Failed 1m (x3 over 3m) kubelet, minikube Failed to pull image "istio/examples-bookinfo-reviews-v2:0.2.8": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.64.1:53: server misbehaving".
How can I solve this problem?

**Comment by sdake** [comment]
Can you try again?  The docker hub suffers transient failures that exhibit with the results you see.  Also the global Internet has been a bit flakey as a result of all of the mass patching going on related to CPU security vulnerabilities.

If that isn't the problem:

@meelody docker hub appears to have the image:
https://hub.docker.com/r/istio/examples-bookinfo-reviews-v2/tags/

docker pull seems to work:
```
sdake@falkor-07:~$ docker pull docker.io/istio/examples-bookinfo-reviews-v2:0.2.8
0.2.8: Pulling from istio/examples-bookinfo-reviews-v2
9fb6c798fa41: Already exists 
3b61febd4aef: Already exists 
9d99b9777eb0: Already exists 
d010c8cf75d7: Already exists 
7fac07fb303e: Already exists 
e40ffc91f806: Already exists 
7a8cecd2b3ad: Already exists 
03dbaf76abf7: Already exists 
b41061b2ca78: Already exists 
72170b9361d0: Already exists 
68345e0876d8: Already exists 
77c55e4e4313: Already exists 
07ddfff18bd5: Already exists 
46658aeda46b: Already exists 
bbd62328437c: Already exists 
f62e32acd5a8: Already exists 
2358ee9c7699: Already exists 
2267bc0a550a: Already exists 
Digest: sha256:22499d5f75f79bfca97827b1c0792eb10051e8e768b544a0fd6e8c2aa43d694b
Status: Downloaded newer image for istio/examples-bookinfo-reviews-v2:0.2.8
```

Can you verify you receive the same results in docker pull (i.e. take minikube out of the equation)?  Often firewalls can be a problem with docker (and require specific docker configuration).

Can you specify how you deployed with minikube so I can try to reproduce your issue?

**Comment by meelody** [comment]
I'm just beginning to get into this, and some things are not very clear. I've tried many times. I've failed. Performing "docker pull" means that I have to install a docker first.

**Comment by meelody** [comment]
I simply execute the following two commands to deploy the application.

minikube start --vm-driver=xhyve
kubectl apply -f samples/bookinfo/kube/bookinfo.yaml

**Comment by meelody** [comment]
This is ok


liangendeMacBook-Pro:docker liangen$ docker pull docker.io/istio/examples-bookinfo-reviews-v2:0.2.8
0.2.8: Pulling from istio/examples-bookinfo-reviews-v2
9fb6c798fa41: Pull complete 
3b61febd4aef: Pull complete 
9d99b9777eb0: Pull complete 
d010c8cf75d7: Pull complete 
7fac07fb303e: Pull complete 
e40ffc91f806: Pull complete 
7a8cecd2b3ad: Pull complete 
03dbaf76abf7: Pull complete 
b41061b2ca78: Pull complete 
72170b9361d0: Pull complete 
68345e0876d8: Pull complete 
77c55e4e4313: Pull complete 
07ddfff18bd5: Pull complete 
46658aeda46b: Pull complete 
bbd62328437c: Pull complete 
f62e32acd5a8: Pull complete 
2358ee9c7699: Pull complete 
2267bc0a550a: Pull complete 
Digest: sha256:22499d5f75f79bfca97827b1c0792eb10051e8e768b544a0fd6e8c2aa43d694b
Status: Downloaded newer image for istio/examples-bookinfo-reviews-v2:0.2.8
liangendeMacBook-Pro:docker liangen$

**Comment by sdake** [comment]
@meelody have you deployed the istio control plane (istio.yaml)?  If not, the bookinfo sample won't work correctly as it depends on istio.yaml and istio-initializer.yaml being run.

Are you using master or a specific released version?

For minikube, this worked for me at one point:
https://github.com/sdake/istio-tools/blob/master/deploy-mk.sh

**Comment by meelody** [comment]
My complete command is this.

minikube start --vm-driver=xhyve
kubectl apply -f install/kubernetes/istio.yaml
kubectl apply -f install/kubernetes/istio-initializer.yaml
kubectl apply -f samples/bookinfo/kube/bookinfo.yaml

But failed.My firewall has also been closed.Whether minikube's network needs special configuration.

**Comment by sdake** [comment]
@meelody no idea how to get things to work with lab firewalls and minikube.  I don't use minikube but instead use kubeadm on a linux machine.  A google search may hold the answers for you regarding minikube and firewall workarounds.  The fact that docker works outside minikube means that the images and docker are functional.

Cheers
-stevve

**Comment by meelody** [comment]
@sdake   Thank you.  I'm thinking about kubeadm.

**Comment by GregHanson** [comment]
@NeGnail were you able to get things working with minikube or did you switch to kubeadm?

**Comment by GregHanson** [comment]
closing issue until more info is provided
