### ISSUE TITLE
Consider internal IPs for all addons  by default

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#255]
From Hackathon feedback:
"
Before telling the user to install the addons, warn that they use an external IP (which costs money and puts a web page on the internets?
"

Use kubectl port-forward or kubectl proxy to access the addons unless you requests an external port.

**Comment by ayj** [comment]
For example, the following command would access the grafana _service_ (not pod) via apiserver proxy.
```bash
$ kubectl proxy
Starting to serve on 127.0.0.1:8001

# Separate shell (or run kubectl proxy in background)
curl http://localhost:8001/api/v1/namespaces/default/services/grafana:3000/proxy/dashboard/db/istio-dashboard
```

**Comment by douglas-reid** [comment]
Removed all load-balancers from addons. Updated docs accordingly.
