### ISSUE TITLE
Allow XDS extensions to return error codes

### ISSUE THREAD

**Issue by esnible** [istio/istio#25507]
Currently there is no way for XDS extensions to return error codes.  (Or, I couldn't find an example of how to do it.)

The XdsResourceGenerator interface has a generate method `Generate(proxy *Proxy, push *PushContext, w *WatchedResource, updates XdsUpdates) Resources` with no `error` return.

Working on the extension to request the configuration for a specific pod (for `istioctl proxy-status <pod>`), I wanted to send a 404 if the client requested a non-existent pod configuration, and a 400 if the client did not supply a pod ResourceName.  I could not figure out how to return anything.

cc @therealmitchconnors

**Comment by howardjohn** [comment]
I don't think we want to return errors. An error here does not mean "something failed to generate" it means "everything is broken, break the entire connection, terminate everything".

If you want a "404" you should return it as part of a response

**Comment by esnible** [comment]
> If you want a "404" you should return it as part of a response

Example or pseudo-code please.

**Comment by howardjohn** [comment]
@esnible we don't have any examples of doing this because the concept doesn't exist in any current XDS resources. But you can send whatever you want as part of a response as long as the type you are sending has an error field or similar

**Comment by howardjohn** [comment]
Closing as I think this is addressed
