### ISSUE TITLE
Add/use network as a label for pods.

### ISSUE THREAD

**Issue by costinm** [istio/istio#25500]
Original design and implementation of multi-network support allowed the use of a 'magic' label added to 
endpoints and containing the network they belong to.

In the early prototype the user would add both a node metadata (using the annotation) and the label - the
first would be used by Pilot to generate the right response, the label would be used to compute/filter the EDS 
response.

After various refactoring we lost this ability: 

1. injector can now add the metadata, based on the Istiod revision settings ( from global.network ), but it doesn't add the label. 
We need a small change to template to do this as well, including restoring the ability for the user to 'annotate' or set it explicitly.

2. The Endpoint builder sets network using the IP range in mesh config. It needs an extra check if the label is set, before
consulting the IP ranges.

This will also simplify multi-network testing - by annotating pods in the local testing framework or in single cluster Kind testing we can test the multi-network feature.

Another benefit is for cases where a namespace in the cluster is restricted by NetworkPolicy (or requirements) from directly talking with other pods, and instead needs to use ingress or egress Gateway as an intermediary.

**Describe the feature request**

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by costinm** [comment]
Jason/Nate - this is related to our chat yesterday. I checked with Shriram and he didn't have objections.

**Comment by ayj** [comment]
If network is used to enforce policy (i.e. NetworkPolicy), is it safe to trust the proxy to self-report the network it belongs to?

**Comment by stevenctl** [comment]
> If network is used to enforce policy (i.e. NetworkPolicy), is it safe to trust the proxy to self-report the network it belongs to?
IIUC this would make a policy allowing pod-to-gateway also allow pod-to-mesh.

**Comment by nmittler** [comment]
@costinm any thoughts? ^^

**Comment by costinm** [comment]
Not sure what is the problem - we are 'zero trust', we do not rely on whatever pod claims for anything. 

Both NetworkPolicy and Istio security Policy are used to enforce 'trust'. Pods can configure itself whoever they want - if NetworkPolicy is in place they won't be able to break it. 

Same if network boundaries are enforced with Istio Policy ( allow from gateway, deny directly from workloads). 

The current mechanism to determine network membership - Pod IP matched against a range - is not a secure element,
IPs are not considered secure.

**Comment by stevenctl** [comment]
Would we also allow VMs to specify their network by setting `ISTIO_META_NETWORK`?

**Comment by costinm** [comment]
> Would we also allow VMs to specify their network by setting `ISTIO_META_NETWORK`?

Of course - in particular for VMs it is important to do that. For Pods there is some level of uniformity on IP allocation - the current mechanism of setting the IP ranges may work. For VMs - you don't want to worry about changing mesh config to update the IPs.

AFAIK ISTIO_META_NETWORK is already a requirement for VMs - I don't remember any code to infer it from IP range, 
last I checked Istiod generates the EDS response based on the info from node metadata (injected in pods, manually set for VM). If this changed - we'll also need to adjust that code.

**Comment by stevenctl** [comment]
Ah I think I misunderstood how endpoints were built for VMs. In that case https://github.com/istio/istio/pull/25554 should be a working first pass at implementing this.

**Comment by stevenctl** [comment]
Seems like a better ux for the multi-tenant + NetworkPolicy use-case (and others) to allow users to set this at the Namespace level. The order of precedence would be Pod > Namespace > Mesh Config. WDYT? @costinm @nmittler
