### ISSUE TITLE
Control the push timing of xds configuration instead of real-time push in gateway mode 

### ISSUE THREAD

**Issue by k807** [istio/istio#25525]
**Describe the feature request**
We use envoy as our gateway and istio as envoy’s control plane in the production environment.But there are the following problems: 

1. We have made customized development, but once there are small features that are not compatible with envoy, the entire xds configuration will be rejected by envoy.
2. crd configuration such as virtualservice, destinationrule will be affected in real time if it is misused or deleted, resulting in online service 503 or 404
3. Pilot OOM is caused when the online endpoint changes on a large scale. At this time, pilot is pushing the xds configuration, and the xds configuration is updated partly, causing envoy to go down

I think The gateway is important and stable, and it should not change configuration frequently. And the problem of the control plane should not affect the data plane, the control plane and the data plane should be isolated.

We are willing to exchange endpoint inconsistencies at certain intervals in exchange for stability.

Therefore, I envisage expanding the functionality of gateway crd and adding configuration synchronization policy fields. It has the following strategies:

- Real-time synchronization
- Timed interval synchronization
- User triggered synchronization

User triggered synchronization can be triggered by an external custom trigger. For example, when changing the production environment, the user can suspend the synchronization of the pilot configuration by implementing a custom trigger. Different logical gateways decide the timing of synchronization configuration according to the strategy.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
> User triggered synchronization

This doesn't make sense to me. If you don't want the Gateway/VirtualService pushed to the proxies, then why did you even create it? Just create it when you want it

> Timed interval synchronization

This is already supported to some extent, see PILOT_DEBOUNCE_AFTER
