### ISSUE TITLE
"Secret is not supplied by SDS" causes 503 to upstreams in istio-ingressgateway pods

### ISSUE THREAD

**Issue by iandyh** [istio/istio#25528]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
```
"GET / HTTP/1.1" 503 UF,URX "-" "TLSrror: Secret is not supplied by SDS" 0 91 67 - 
```
After we restart the deployment of istio-ingressgateway, we had such issue. Although we are not using TLS anywhere in the cluster. But still we we had lots of 503 to the upstream.
After deleting the pod, the issue is gone.

**Affected product area (please put an X in all that apply)**

[X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
1. Ingressgateway pod should get the secret for the upstream connections.
2. If for some reason it cannot get the secret from `istiod` through SDS, then it should NOT become ready and serve the traffic.

**Steps to reproduce the bug**
It's difficult to reproduce. 

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
Control plane: 1.6.3
Istio ingressgateway: 1.6.2

**How was Istio installed?**
istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
On your gateway, what secrets are present? Can see it at the bottom of config dump or `istioctl pc secret`. If its just default and ROOTCA, the fact it becomes ready is a bug tracked in https://github.com/istio/istio/issues/22443

**Comment by iandyh** [comment]
@howardjohn Thanks for the reply. Yes, I can only see the two secrets. I'll follow that issue instead.
