### ISSUE TITLE
How can I update new changes by istioctl without overwriting current configuration?

### ISSUE THREAD

**Issue by shudhanshh** [istio/istio#25535]
When applying new global configurations by:

istioctl manifest apply --set global.config="value" 

This overwrites the current configuration and sets the default config. I want to apply new changes without overwriting older configurations.

**Comment by esnible** [comment]
There is no obvious way to do this.  See https://github.com/istio/istio/issues/23443 for a proposal.

You **might** be able to do `istioctl manifest apply -f <(kubectl -n istio-system get iop installed-state -o yaml) --set global.config="value"` but this is not supported.

**Comment by esnible** [comment]
Closing in favor of https://github.com/istio/istio/issues/23443
