### ISSUE TITLE
GRPC issue with Load Balancer

### ISSUE THREAD

**Issue by xubofei1983** [istio/istio#25555]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
I have a GRPC service (implemented with Akka Grpc), which is not tls encrypted.

The behavior is very wierd:

If I set the service port name as grpc-xxx (or http2-xxxx),  then I cannot access it from external via load balancer with below error:
Error: UNAVAILABLE: upstream connect error or disconnect/reset before headers. reset reason: connection termination

If I set the service port name as http-xxx, then I can access it from external via load balancer. However, I see warning msgs:
```
| 2020/07/15 19:49:21.059 | 3,190.357 | WARN  | akka.actor.ActorSystemImpl                       | Sending an 2xx 'early' response before end of request for http://xxxxx received... Note that the connection will be closed after this response. Also, many clients will not read early responses! Consider only issuing this response after the request data has been completely read!
```
Also,  some client(in cluster)  throw errors.

```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  annotations:
    type: ingressgateway-protected-http2
  creationTimestamp: "2020-07-15T22:23:11Z"
  generation: 1
  name: xxxx-external-gateway
  namespace: default
  resourceVersion: "337629"
spec:
  selector:
    istio: ingressgateway-protected-http2
  servers:
  - hosts:
    - xxxx.kariusdx.com
    port:
      name: http
      number: 80
      protocol: HTTP
```

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  creationTimestamp: "2020-07-15T22:23:11Z"
  generation: 1
  name: xxxx-external
  namespace: default
  resourceVersion: "337634"
spec:
  gateways:
  - xxx-external-gateway
  hosts:
  - xxx.kariusdx.com
  http:
  - retries:
      attempts: 3
      perTryTimeout: 5s
      retryOn: gateway-error,connect-failure,refused-stream
    route:
    - destination:
        host: xxxx
        port:
          number: 80
```

```
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-07-15T22:23:11Z"
  labels:
    app: xxxx   heritage: Tiller
    release: xxx
  name: xxxx
  namespace: default
  resourceVersion: "337623"
spec:
  clusterIP: 172.20.16.83
  ports:
  - name: grpc-port
    port: 80
    protocol: TCP
    targetPort: grpc-port
  selector:
    app: xxxxx
    release: xxxx
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
It should support GRPC service well.

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
client version: 1.6.5
ingressgateway-private version:
ingressgateway-protected-http2 version:
ingressgateway-protected-https version:
telemetry version: 1.6.5
pilot version: 1.6.5
data plane version: 1.6.5 (12 proxies)

**How was Istio installed?**
istio-operator

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS 

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by xubofei1983** [comment]
gateway config in istio operator

```
- enabled: true
      k8s:
        env:
        - name: ISTIO_META_IDLE_TIMEOUT
          value: 600s
        - name: ISTIO_META_ROUTER_MODE
          value: sni-dnat
        hpaSpec:
          maxReplicas: 5
          metrics:
          - resource:
              name: cpu
              targetAverageUtilization: 80
            type: Resource
        resources:
          requests:
            cpu: 200m
        service:
          externalTrafficPolicy: Local
          ports:
          - name: http2
            port: 80
            targetPort: 80
          type: LoadBalancer
        serviceAnnotations:
          service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http2
      label:
        app: istio-ingressgateway-protected-http2
        istio: ingressgateway-protected-http2
      name: istio-ingressgateway-protected-http2
      namespace: istio-system
```

**Comment by xubofei1983** [comment]
I also tried below gateway config, get same error when access from external ingress
 ```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  annotations:
    type: ingressgateway-protected-http2
  creationTimestamp: "2020-07-15T22:23:11Z"
  generation: 3
  name: xxxx-external-gateway
  namespace: default
  resourceVersion: "354626"
spec:
  selector:
    istio: ingressgateway-protected-http2
  servers:
  - hosts:
    - xxx.kariusdx.com
    port:
      name: http2
      number: 80
      protocol: HTTP2
```

**Comment by johnzheng1975** [comment]
Similar issue: https://github.com/istio/istio/issues/25573
