### ISSUE TITLE
Build using "USE_LOCAL_PROXY=1 make docker.proxyv2" fails

### ISSUE THREAD

**Issue by Vivek-anand-jain** [istio/istio#25572]
**Bug description**
When I build istio using "USE_LOCAL_PROXY=1 make docker.proxyv2", the build process fails:
```
root@node0:/mnt/go/src/istio.io/istio# USE_LOCAL_PROXY=1 make docker.proxyv2
mkdir -p /work/out/linux_amd64/logs
mkdir -p /work/out/linux_amd64/release
mkdir -p /work/out/linux_amd64/docker_build/proxyv2
cp  /envoy
cp: missing destination file operand after '/envoy'
Try 'cp --help' for more information.
tools/istio-docker.mk:68: recipe for target '/envoy' failed
make[1]: *** [/envoy] Error 1
Makefile:46: recipe for target 'docker.proxyv2' failed
make: *** [docker.proxyv2] Error 2
```

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[x] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

**Steps to reproduce the bug**
Step 0: Set following environment variable:
```
export HUB=docker.io/my-docker-hub
export TAG=latest
export ISTIO=$GOPATH/src/istio.io
```

Step 1: Clone istio and proxy in `$GOPATH/src/istio.io`
```
git clone https://github.com/istio/istio
git clone https://github.com/istio/proxy
```

Step 2: Go to proxy directory and build it using container
```
cd $GOPATH/src/istio.io/proxy
BUILD_WITH_CONTAINER=1 make build
```

Step 3: Go to istio directory and build it
```
cd $GOPATH/src/istio.io/istio
make build
```

Step 4: create docker image for istio with local proxy
```
USE_LOCAL_PROXY=1 make docker.proxyv2
```

**It fails saying:**
```
root@node0:/mnt/go/src/istio.io/istio# USE_LOCAL_PROXY=1 make docker.proxyv2
mkdir -p /work/out/linux_amd64/logs
mkdir -p /work/out/linux_amd64/release
mkdir -p /work/out/linux_amd64/docker_build/proxyv2
cp  /envoy
cp: missing destination file operand after '/envoy'
Try 'cp --help' for more information.
tools/istio-docker.mk:68: recipe for target '/envoy' failed
make[1]: *** [/envoy] Error 1
Makefile:46: recipe for target 'docker.proxyv2' failed
make: *** [docker.proxyv2] Error 2
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**
OS: Ubuntu 18.04.1 LTS

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by myshkin5** [comment]
Hi @Vivek-anand-jain! I just got this working this morning and I agree — something isn’t right here.

I had to do three "workarounds" to get `USE_LOCAL_PROXY` to work. Also I did this on a branch off of 1.5.7. If you are working on something newer or older, YMMV.

1. Define `ISTIO_ENVOY_LOCAL` and `ISTIO_ENVOY_LOCAL_PATH` both pointing at the locally-built envoy binary
1. Copy the .wasm files in `$GOPATH/out/linux_amd64/release` to the directory containing the envoy binary
1. Make the envoy binary writable — the scripts copy the file as unwritable then fail on subsequent copies

Hope this helps!

**Comment by Vivek-anand-jain** [comment]
@sdake tagging you for the notification since I don't have enough permission to assign the issue.

**Comment by Vivek-anand-jain** [comment]
Thanks @myshkin5 for the detailed steps, I will try these and let you know the status.

**Comment by sdake** [comment]
I have built envoy and found the envoy output is not built locally with BUILD_WITH_CONTAINER=1. To speed up development, I have added /home/.cache which bezel depends on to build software. This reduces the build time from 20 minutes to 6-12 seconds on my gear.

Cheers,
-steve

**Comment by sdake** [comment]
@myshkin5 in newer version of Istio, the build system has evolved and improved in ways that make what you have done just not work :(.

Part of the problem is nobody ever put the proxy container on the container build plan. Its a real shame that hasn't happened yet, well better late than never. I'll take a look when I have time.

Cheers
-steve

**Comment by sdake** [comment]
@Vivek-anand-jain as you can see, proxy in the latest istio doesn't build an output at all. All I see are symlinks in the /work directory of the container. I am fixing this shortly - hopefully- so that output files are copied as part of the build to the host  filesystem.

Cheers,
-steve

**Comment by sdake** [comment]
envoy, along with 3 wasm files is built and output. istio/istio may not properly import it with env vars set. I'll see what I can do to get istio/istio to use the envoy shared build cache for local builds with an env var set.

**Comment by poussa** [comment]
Hi,

I am quite close to getting my local proxy build to work but it is failing on the last step.

```bash
export HUB=docker.io/$USER
export TAG=latest
export ISTIO=$GOPATH/src/istio.io
export ISTO_ENVOY_LOCAL=$ISTIO/proxy/out/linux_amd64/envoy
export ISTIO_ENVOY_LOCAL_PATH=$ISTIO/proxy/out/linux_amd64
cd $GOPATH/src/istio.io/proxy
BUILD_WITH_CONTAINER=1 make build_envoy
BUILD_WITH_CONTAINER=1 make build_wasm
BUILD_WITH_CONTAINER=1 make exportcache
cd $GOPATH/src/istio.io/istio
make build
USE_LOCAL_PROXY=1 make docker.proxyv2
```

The last step is failing since it is not finding the wasm files (which are in `$ISTIO/proxy/out/linux_amd64` dir).

The error is 

```bash

time (mkdir -p /work/out/linux_amd64/docker_build/docker.proxyv2 && cp -r metadata-exchange-filter.compiled.wasm /work/tools/packaging/common//envoy_bootstrap.json /work/tools/packaging/common//gcp_envoy_bootstrap.json envoy /work/out/linux_amd64/pilot-agent pilot/docker/Dockerfile.proxyv2 pilot/docker/envoy_policy.yaml.tmpl stats-filter.wasm stats-filter.compiled.wasm metadata-exchange-filter.wasm /work/out/linux_amd64/docker_build/docker.proxyv2 && cd /work/out/linux_amd64/docker_build/docker.proxyv2 && chmod 755 envoy pilot-agent && docker build --build-arg proxy_version=istio-proxy:2cc54e006a6d7178aa89ea516a44c7f5cebf40af --build-arg istio_version=1.8-dev --build-arg BASE_VERSION=1.8-dev.0 --build-arg SIDECAR=envoy --build-arg BASE_DISTRIBUTION=default -t docker.io/spoussa/proxyv2:spoussa -f Dockerfile.proxyv2 . );
cp: cannot stat 'metadata-exchange-filter.compiled.wasm': No such file or directory
cp: cannot stat 'stats-filter.wasm': No such file or directory
cp: cannot stat 'stats-filter.compiled.wasm': No such file or directory
cp: cannot stat 'metadata-exchange-filter.wasm': No such file or directory
```

How can I teach the build system where the wasm files are (or where to copy them)?

Thanks, Sakari
