### ISSUE TITLE
[test framework] Consolidate control-plane components

### ISSUE THREAD

**Issue by stevenctl** [istio/istio#25577]
We can consolidate the [pilot](https://github.com/istio/istio/tree/master/pkg/test/framework/components/pilot) and [ingress](https://github.com/istio/istio/tree/master/pkg/test/framework/components/ingress) components into the [Istio](https://github.com/istio/istio/tree/master/pkg/test/framework/components/istio) component. 

This reduces some repetitive code in tests, especially when there are multiple clusters involved. The istio component is aware of the control-plane topology and methods like `CallDiscovery` for a remote cluster should be hitting the istiod for it's primary/control-plane cluster. 

The usage might look something like this:

```go
i := istio.GetOrFail(ctx)
// pilot
i.ServiceDiscovery(cluster).CallDiscovery(...)
// ingress
i.Ingress(cluster).TCPAddress()
```

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[X] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by stevenctl** [comment]
cc @nmittler

**Comment by nmittler** [comment]
It would also be good to create an interface (`istio.Instance`) as well. This will make it more consistent with the other components.
