### ISSUE TITLE
Telemetry V2: istio.io/service/server/request_count is missing when the client is istio-ingressgateway

### ISSUE THREAD

**Issue by cagataygurturk** [istio/istio#25571]
**Bug description**

We have a `service A` behind `istio-ingressgateway`. Istio is configured to publish metrics to Stackdriver with Telemetry v2.

If we send requests from public load balancer to **Service A**, `istio.io/service/client/request_count` metric is reported by `istio-ingressgateway` but `istio.io/service/server/request_count` is not reported by **Service A**. (Occasionally 1-2 requests are reported but it does not reflect the reality.)

When **Service B** sends requests to **Service A**, then both services report correct metrics under the category of `istio.io/service/client/request_count` and `istio.io/service/server/request_count`, respectively.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

1.6.5

**Environment where bug was observed (cloud vendor, OS, etc)**

GKE

**Comment by bianpengyuan** [comment]
Probably the same issue as https://github.com/istio/istio/issues/25274. Could you try out the debug image listed in https://github.com/istio/istio/issues/25274#issuecomment-655871226 with option `--set values.global.proxy.image=gcr.io/mixologist-142215/proxyv2:1.6.4-p0` and see if it fixes the issue?

**Comment by cagataygurturk** [comment]
Hello @bianpengyuan unfortunately your debug version did not make the trick also. I have enabled Prometheus and checked the /stats/prometheus endpoint and confirmed that `istio_requests_total` metric is not produced by the sidecar when istio-ingressgateway sends the request. Requests from other services show up in that metric, so now we know that it is not a Stackdriver specific issue.

**Comment by bianpengyuan** [comment]
Could you disable protosniffing and see if it fixes the issue? https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/#automatic-protocol-selection Make sure your service port is properly named with protocol prefix.

**Comment by cagataygurturk** [comment]
> Could you disable protosniffing and see if it fixes the issue? https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/#automatic-protocol-selection Make sure your service port is properly named with protocol prefix.

Disabling protosniffing fixed the issue!

I was also comparing my installation values with the `asm-gcp.yaml` bundled with Anthos Service Mesh deployment and I had noticed that protosniffing was disabled there also.

What is the recommendation now? Is there bug to be fixed and should we keep protosniffing off until the fix?

**Comment by bianpengyuan** [comment]
Yeah this is a known issue. See https://github.com/istio/istio/issues/24379 for more context. We will try to increase the proto sniffing timeout to infinity in 1.7. Let me know if we can close this and track this in #24379.

**Comment by cagataygurturk** [comment]
Sure we can close this if this is already known. Thanks!
