### ISSUE TITLE
auto mtls for VMs

### ISSUE THREAD

**Issue by btoonk** [istio/istio#25570]
**Bug description**

We're experimenting with mesh expansion with VMs in our DC.
We noticed that the auto mtls feature does not seem to work for VMs.

We see unencrypted traffic coming in from an istio enabled pod to a service (with istio sidecar) running on a VM.
With a DestinationRule setting the tls trafficpolicy to ISTIO_MUTUAL mtls is working between the pod and the VM.

Is auto mtls supported on VMs and does this require some additional configuration ?

[ ] Configuration Infrastructure
[ x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Auto mtls also work on VMs.

**Steps to reproduce the bug**

We use the hipstershop to test mesh expansion, currently we have the currencysvc running on a VM in our DC.
* Create a VM with the istio-proxy (we have specified ISTIO_NAMESPACE=currencysvc and ISTIO_INBOUND_PORTS=7000 in the /var/lib/istio/envoy/cluster.env)
* Create a kubernetes service for the currencyservice
* Create a workloadentry for the VM
* Configure the other hipstershop components to use this new service for the currencyservice

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

1.6.3

**How was Istio installed?**

With istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**

GKE and a VM on vmware running rhel7

**Comment by howardjohn** [comment]
You need to specify the ServiceAccount field in workload entry actually, not the label. Or the label works as well actually, https://github.com/istio/istio/blob/7124d7d2e90c4f35b09e3f4912e2d5e7f12626bc/pilot/pkg/serviceregistry/serviceentry/conversion.go#L328

**Comment by btoonk** [comment]
After adding the label `security.istio.io/tlsMode: istio` to the workload entry mtls does indeed work.
But the source pod did not automatically pick up this change, it had to be restarted (Istio 1.6.5).

**Comment by howardjohn** [comment]
@btoonk do you intend to switch the label at runtime, or was it just because it was initially not setup? This label doesn't change at runtime in k8s so I am not too surprised if we don't have the logic to handle this dynamic update

**Comment by btoonk** [comment]
No, currently we don't need to switch this at runtime.

**Comment by JimmyCYJ** [comment]
@incfly can I assign to you as you have context on the auto mTLS feature? Feel free to reassign. Are there any changes to the code to support auto mTLS without restarting pods?
