### ISSUE TITLE
client-go should support install.istio.io/v1alpha1

### ISSUE THREAD

**Issue by esnible** [istio/istio#25584]
client-go should allow handling of IstioOperator.

**Comment by esnible** [comment]
@nrjpoddar I created this Issue here because client-go doesn't have an Issue Tracker.  I was not sure how to label this Issue.  `area/networking`?  A new label `area/networking/client-go`?

**Comment by nrjpoddar** [comment]
Not sure, you can add area/networking but client-go is a cross WG concern.

Solution is simple though you need to add these annotations (comments) on proto files for client-go to pick them up automatically:

https://github.com/istio/api/blob/master/networking/v1beta1/destination_rule.proto#L189

**Comment by nrjpoddar** [comment]
It looks like the annotations are there in operator proto, there's probably some filter in client-go side.

**Comment by nrjpoddar** [comment]
Created https://github.com/istio/client-go/pull/209/

**Comment by nrjpoddar** [comment]
There's an underlying issue https://github.com/istio/istio/issues/24829 which will prevent us from adding Operator CRDs in client-go

**Comment by esnible** [comment]
Labeling as `area/networking`; if this is incorrect let me know.

**Comment by esnible** [comment]
Not stale.  Adding `area/user experience` because UX merged with the config and must own config issues.

**Comment by nrjpoddar** [comment]
I don't know. It's good question for @jasonwzm.

**Comment by jasonwzm** [comment]
@jahvon Yes, it is still an issue. client-go relies on DeepCopy method working. I am following up in the blocking issue.
