### ISSUE TITLE
Inquiry About the Microservice Architecture Employed by `istio`

### ISSUE THREAD

**Issue by research-sudo** [istio/istio#25586]
I am a researcher investigating the open source projects that are designed by the microservice architectural style (https://martinfowler.com/microservices/). My preliminary investigation shows that the **_istio_** project (https://github.com/istio/istio) is designed by the microservice architectural style.

Can you please **_confirm_** if my interpretation that this project is designed by following the microservice architectural style is correct? Note that if the projects (e.g., frameworks or tools) support the development of microservices-based systems but themselves are not designed by following the microservice architectural style, please also clarify it?
If my interpretation is correct, what **_features_** or **_characteristics_** of the architecture of this open source project show that the microservice architectural style has been used?
**Optional Question**: Do you know any other open-source projects that are designed by following the microservice architectural style?
I would be greatly appreciative if you can kindly answer the three questions above.

**Comment by howardjohn** [comment]
If you take a look at https://istio.io/latest/docs/concepts/what-is-istio/ this should answer all your questions

**Comment by research-sudo** [comment]
Thank you for your answer.
I'm confused, Is this project designed by the microservice architectural style or control all network communication between microservices? or both?
I need you to confirm the project as a key contributor.

**Comment by howardjohn** [comment]
The project is designed to support microservices architecture, it itself is
not a microservice (anymore - it used to be)

**Comment by research-sudo** [comment]
Thank you so much @howardjohn
