### ISSUE TITLE
Clean up StatNameLength in proxy config

### ISSUE THREAD

**Issue by bianpengyuan** [istio/istio#25595]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
Envoy has deprecated `max-obj-name-len` option: https://github.com/envoyproxy/envoy/issues/10111, the corresponding StateNameLength option in proxy config should also be cleaned up. 

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by shamsher31** [comment]
Closed by https://github.com/istio/istio/pull/25594

**Comment by bianpengyuan** [comment]
This is to track clean up of `StateNameLength` in ProxyConfig, which is not done yet.
