### ISSUE TITLE
Extend action field in AuthorizationPolicy for audit

### ISSUE THREAD

**Issue by davidraskin** [istio/istio#25591]
We propose to extend the "action" field in AuthorizationPolicy to support use cases like "audit" , in which case, the matching condition in AuthorizationPolicy can be used to determine when an audit log is generated. It will set a new boolean attribute e.g. 'istio.audit', which can be read by telemetry plugins to determine whether to log based on its value.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ X] Policies and Telemetry
[ X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

cc @louiscryan @smawson @liminw @mandarjog

**Comment by brian-avery** [comment]
@xulingqing Can this be closed? Based on the last comment here, I believe yes. Thanks.
