### ISSUE TITLE
1.5.x helm template update fails when Datadog tracer is enabled

### ISSUE THREAD

**Issue by nagypeterjob** [istio/istio#25606]
**Bug description**

When updating from 1.4.5 to 1.5.8 with helm template, gateways installation fails when Datadog tracer is enabled due to duplicate ENV var in _install/kubernetes/helm/istio/charts/gateways/templates/deployment.yaml_.

Details:
The gateways deployment has **HOST_IP** set by default:
```
 #line 226
- name: HOST_IP
   valueFrom:
     fieldRef:
       apiVersion: v1
       fieldPath: status.hostIP
```
During update, when **--set global.proxy.tracer=datadog** is used, the deployment wants to set **HOST_IP** once again: 
```
#line 266
{{- if eq $.Values.global.proxy.tracer "datadog" }}
- name: HOST_IP
   valueFrom:
     fieldRef:
       fieldPath: status.hostIP
{{- end }}
```

The duplicate environment variable conflicts during three way merge patching. A very similar issue: https://github.com/istio/istio/issues/23950 

As a workaround I have commented out the Datadog related part starting from line 266 as **HOST_IP** is already set by default => the update was successful.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

**HOST_IP** should be set only once for gateways during install / update, hence the installation should be successful without merge conflicts.

**Steps to reproduce the bug**
Install Istio 1.4.5 with the following flags:
```
helm template install/kubernetes/helm/istio --name istio --namespace istio-system \
--set pilot.traceSampling=100.0 \
--set global.proxy.tracer=datadog \
--set tracing.enabled=true \
--set gateways.istio-egressgateway.enabled=true \
--set global.proxy.accessLogFile="/dev/stdout" | kubectl apply -f -
```

Update Istio with the following commands:
```
kubectl apply -f install/kubernetes/helm/istio-init/files/

helm template install/kubernetes/helm/istio --name istio --namespace istio-system \
--set pilot.traceSampling=100.0 \
--set global.proxy.tracer=datadog \
--set tracing.enabled=true \
--set gateways.istio-egressgateway.enabled=true \
--set global.proxy.accessLogFile="/dev/stdout" | kubectl apply -f -

```
The following error will be present:
```
warning: error calculating patch from openapi spec: The order in patch list:
[map[name:HOST_IP valueFrom:map[fieldRef:map[apiVersion:v1 fieldPath:status.hostIP]]] map[name:HOST_IP valueFrom:map[fieldRef:map[fieldPath:status.hostIP]]] map[name:ISTIO_METAJSON_LABELS value:{"app":"istio-ingressgateway","chart":"gateways","heritage":"Tiller","istio":"ingressgateway","release":"istio"}
] map[name:ISTIO_AUTO_MTLS_ENABLED value:true] map[name:ISTIO_META_ROUTER_MODE value:standard]]
 doesn't match $setElementOrder list:
[map[name:NODE_NAME] map[name:POD_NAME] map[name:POD_NAMESPACE] map[name:INSTANCE_IP] map[name:HOST_IP] map[name:SERVICE_ACCOUNT] map[name:ISTIO_META_WORKLOAD_NAME] map[name:ISTIO_META_OWNER] map[name:ISTIO_META_POD_NAME] map[name:ISTIO_META_CONFIG_NAMESPACE] map[name:ISTIO_METAJSON_LABELS] map[name:ISTIO_META_CLUSTER_ID] map[name:SDS_ENABLED] map[name:ISTIO_AUTO_MTLS_ENABLED] map[name:HOST_IP] map[name:ISTIO_META_ROUTER_MODE]]
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
$ istioctl version
client version: 1.5.8
control plane version: 1.5.8

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

$ helm version
Client: &version.Version{SemVer:"v2.16.7", GitCommit:"5f2584fd3d35552c4af26036f0c464191287986b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.7", GitCommit:"5f2584fd3d35552c4af26036f0c464191287986b", GitTreeState:"clean"}

```

**How was Istio installed?**

```
helm template install/kubernetes/helm/istio --name istio --namespace istio-system \
--set pilot.traceSampling=100.0 \
--set global.proxy.tracer=datadog \
--set tracing.enabled=true \
--set gateways.istio-egressgateway.enabled=true \
--set global.proxy.accessLogFile="/dev/stdout" | kubectl apply -f -
```

**Environment where bug was observed (cloud vendor, OS, etc)**
EKS, AWS Amazon Linux,

**I would have fixed the issue myself, but I can't find any trace of the mentioned yaml snippet in istio/istio repository. I am confident that this has been already fixed on master branch, but as the 1.5.8 installation fails I felt its better if I open an issue.**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by morvencao** [comment]
The legacy helm chart `install/kubernetes/helm` was completed removed from istio/istio repo from 1.6.x, please use operator to install istio, the operator used build-in chart at https://github.com/istio/istio/tree/master/manifests/charts to generate istio manifests.

**Comment by nagypeterjob** [comment]
Thank you for the insight @morvencao. I get that, but for the lot of us migrating to 1.6 and istioctl is a tedious and complex task and util we are ready to do it, 1.5.x is a safe way to have a relatively up-to-date deployment. I am not sure how long 1.5.x is still supported, but in my opinion issues like this should be resolved until then. If it is already deprecated, then I am sorry and I will close the issue right away!
