### ISSUE TITLE
Istio envoy lack of prom stats istio_tcp_connection*

### ISSUE THREAD

**Issue by packyzbq** [istio/istio#25600]
Hi, I compile the istio-proxy from source on arm64, however the following stats are missing:
```
istio_tcp_connections_opened_total
istio_tcp_connections_closed_total
istio_tcp_received_bytes_total
istio_tcp_sent_bytes_total
....
```
In addition to the above stats, others beginning with istio seem to be missing.

Actually, I only compile the envoy binary. Do I also need to recompile wasm？ I just copy the wasm from x86 images to arm64 images by the way.

My compile process is as below:
```
git clone https://github.com/istio/istio.git && git checkout 1.5.7 
make build # then I get the istioctl pilot-agent binary for istio-proxy
```
I use morlay/istio-proxy-build-env:latest-arm64 to build istio-proxy.
```sh
git clone https://github.com/istio/proxy.git && git checkout 1.5.7
wget https://github.com/istio/envoy/archive/f62504cb94e5af3069322f71cf8302eaffa9d05a.tar.gz && tar -xzvf f62504cb94e5af3069322f71cf8302eaffa9d05a.tar.gz

# patch envoy/bazel/external/wee8.genrule_cmd to support arm64

# patch proxy/WORKSPACE
+#http_archive(
+local_repository(
+   name = "envoy",
+    #sha256 = ENVOY_SHA256,
+    #strip_prefix = ENVOY_REPO + "-" + ENVOY_SHA,
+    #url = "https://github.com/" + ENVOY_PROJECT + "/" + ENVOY_REPO + "/archive/" + ENVOY_SHA + ".tar.gz",
+    path = "the path of envoy",
)

make build_envoy # In this step I got envoy binary.
```

istio version: 1.5.7
envoy sha:  f62504cb94e5af3069322f71cf8302eaffa9d05a

**Comment by bianpengyuan** [comment]
You will need to make L4 connection in order to make envoy generate tcp metrics, for example https://istio.io/v1.5/docs/tasks/observability/metrics/tcp-metrics/. Wasm is not required to generate TCP metrics.

**Comment by bianpengyuan** [comment]
> In addition to the above stats, others beginning with istio seem to be missing.

Do you mean you cannot see any istio prefixed metrics, or just the tcp ones?

**Comment by packyzbq** [comment]
> > In addition to the above stats, others beginning with istio seem to be missing.
> 
> Do you mean you cannot see any istio prefixed metrics, or just the tcp ones?

Actually I can't find any istio prefixed metrics except istio_build

**Comment by bianpengyuan** [comment]
How do you install istio?

**Comment by packyzbq** [comment]
> How do you install istio?

I compile the istioctl binary and then use command `istioctl manifest apply` to install istio. By the way  the istiod runs normally and I didn't see any error log.

**Comment by packyzbq** [comment]
I wonder when and how istio prefixed metrics are put in the code. I can't find anything in istio project or proxy project when using `find . -type f|xargs grep istio_`

**Comment by bianpengyuan** [comment]
They are generated by stats filter: https://github.com/istio/proxy/tree/master/extensions/stats. if istio_build metrics are generating, that means stats filter is compiled and working properly. 
https://github.com/istio/proxy/blob/c51fe751a17441b5ab3f5487c37e129e44eec823/extensions/stats/plugin.cc#L415

Have you sent any traffic to your deployment? Istio metrics will only be generated after requests going through proxy.

**Comment by packyzbq** [comment]
I finally solve this problem. I didn't set the ISTIO_VERSION and ENVOY_VERSION when I build the envoy image. But it is strange that these two args will affect the istio prefixed metrics. 
Thanks @bianpengyuan very much.
