### ISSUE TITLE
Scope pushes to PeerAuthentication

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#25616]
https://github.com/istio/istio/pull/25430 adds scoping for some types, PeerAuthentication is still different though, as we look in the namespace of the destination as well: https://github.com/istio/istio/blob/b576237ad1280f5abc17291d84b1a913032b7183/pilot/pkg/model/authentication.go#L198

We can add some scoping here possibly by looking at the set of namespaces or similar

cc @incfly

**Comment by stevenctl** [comment]
not stale

**Comment by stevenctl** [comment]
@incfly is this actually possible to implement? 

If I understand correctly, any changes to PeerAuthentication would affect client-side configuration for the entire mesh regardless of namespace. The only sort of filtering out we could do is finding if the current sidecar can even access the namespace affected by the CR.
