### ISSUE TITLE
LoadBalancerSettings.ConsistentHashLB.HTTPCookie Add option to disable automatic Cookie generation

### ISSUE THREAD

**Issue by jdamour98** [istio/istio#25621]
**Describe the feature request**
From the Istio Docs:  
https://istio.io/latest/docs/reference/config/networking/destination-rule/#LoadBalancerSettings-ConsistentHashLB-HTTPCookie
> Describes a HTTP cookie that will be used as the hash key for the Consistent Hash load balancer. **If the cookie is not present, it will be generated.**

Add option to disable cookie generation. If cookie does not exist, default to RoundRobin LB. Do not use ConsistentHash for Sticky Session unless cookie already exists. If it does exist, do not override it

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by hzxuzhonghu** [comment]
https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route_components.proto#route-routeaction-hashpolicy-cookie

According to envoy doc, it seems this is impossible

**Comment by howardjohn** [comment]
This is not feasible right now. If you are interested, please submit a feature request to Envoy. Thanks!
