### ISSUE TITLE
fatal error: concurrent map writes in multicluster istiod tests

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#25625]
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/25363/integ-multicluster-k8s-tests_istio/6921#1:build-log.txt%3A3141

This was probably fixed but then reverted by https://github.com/istio/istio/commit/7915c7326a2f9659915d0f233fa5efa27d8babbd? Looks like the cobra stuff cannot be called in parallel

**Comment by nschhina** [comment]
This makes all multicluster test fail all the time, can a fix be deployed ASAP? It's blocking PRs for 1.7 release

**Comment by nschhina** [comment]
https://testgrid.k8s.io/istio_istio#integ-multicluster-k8s-tests_istio

**Comment by adiprerepa** [comment]
this just means add a `sync.Mutex`?

**Comment by adiprerepa** [comment]
is the issue [https://github.com/istio/istio/blob/master/pkg/test/framework/scope.go#L66](url)?

It seems like it already has a mutex. Is there a way to get better visibility into where the faliure is happening

**Comment by stevenctl** [comment]
Should be fixed by https://github.com/istio/istio/pull/25633 - seems like a PR made it in without finishing MC tests. `viper. SetDefault` is the culprit.

**Comment by stevenctl** [comment]
Is anyone still seeing this? MC tests are passing on new PRs.
