### ISSUE TITLE
Demo profile not using 15021 as status port 1.6.x

### ISSUE THREAD

**Issue by coryasilva** [istio/istio#25626]
**Bug description**
The `demo` profile still has 15020 as the status port while the `default` profile has the new 15021 port.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
15020 status port was changed to 15021. 
https://istio.io/latest/news/releases/1.6.x/announcing-1.6/change-notes/

**Steps to reproduce the bug**
istioctl profile dump demo | grep 15020

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.6.x

**How was Istio installed?**
ansible

**Environment where bug was observed (cloud vendor, OS, etc)**
aws

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

```bash
❯ istioctl version
1.6.5

❯ istioctl profile dump demo | grep "port: 15020" -C 3 -n
48-        service:
49-          ports:
50-          - name: status-port
51:            port: 15020
52-            targetPort: 15020
53-          - name: http2
54-            port: 80

❯ istioctl profile dump default | grep "port: 15020" -C 3 -n

```

**Comment by shamsher31** [comment]
Closed by https://github.com/istio/istio/pull/25635
