### ISSUE TITLE
Readiness systematic error and error count

### ISSUE THREAD

**Issue by vincentserpoul** [istio/istio#25643]
When I deploy a service with istio injection enabled, I systematically get:

    Readiness:  http-get http://:15021/healthz/ready delay=1s timeout=1s period=2s #success=1 #failure=30

Inside the describe of the istio-proxy pod.

Is that expected?

**Affected product area (please put an X in all that apply)**

[X] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[x] Multi Cluster
[x] Virtual Machine
[x] Multi Control Plane

**Expected behavior**
No error

**Steps to reproduce the bug**
Deploy any service, in any cluster.
Istio installed with default profile.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.6.* 

**How was Istio installed?**
istioctl manifest apply \
    --set profile=default

**Environment where bug was observed (cloud vendor, OS, etc)**
k3d, aks

**Comment by howardjohn** [comment]
Yes this is the readiness probe for the sidecar container

**Comment by vincentserpoul** [comment]
So it's normal to systematically have **#failure=30**, whatever the deployment?

**Comment by howardjohn** [comment]
That doesn't mean there has been a failure it means it will be marked not
ready if the prohe fails 30x in a row

**Comment by vincentserpoul** [comment]
Thanks for your prompt response @howardjohn !

As I read it, it would mean that:
After **1s (delay)**
the ready endpoint of istio-proxy was probed **every 2s (period)** for **30 times (#failures)**

That would mean a starting time of **more than 1mn**, which is not the actual starting time (the pod is readt within a few seconds).
Adding to that, this 30 failures appear right at the beginning of the deployment, when I "describe" it, not 1mn later, as I would expect.

That said, the only question that matter to me is: **does everyone see that 30 failures, 100% of the time (not 32, not 16, not 2, but 30)?**

**Comment by howardjohn** [comment]
That number is describing the spec of the pod, it's not dynamically
changing. The It takes 1 success to become ready, but 30 failures to become
not ready
