### ISSUE TITLE
istioctl version doesn't return a value on master

### ISSUE THREAD

**Issue by christian-posta** [istio/istio#2567]
Looks like when we moved away from Bazel, we've possibly broken the version injection stuff?

For istioctl on master right now, when we do a build, we don't see version info when running `istioctl version`. 

Looks like we intend for it though:

https://github.com/christian-posta/istio/blob/4398a447128012f9b6bc065df22245248e82d881/Makefile#L183

And here we try build the `-ldflags -X`:

https://github.com/christian-posta/istio/blob/aaf54b09fa40dea8e67fc59abf672d36d4991b09/bin/gobuild.sh#L56

But i'm not quite groking where the input to the SYMBOL/VALUE is on this line: https://github.com/christian-posta/istio/blob/aaf54b09fa40dea8e67fc59abf672d36d4991b09/bin/gobuild.sh#L57

Maybe that's intended for releases somehow? Would love some help and I can try fix it!

**Comment by ayj** [comment]
What environment/platform are you building on?

The input is the list of key/value environment variables emitted by `bin/get_workspace_status`. Have you verified that `bin/get_workspace_status` is producing expected output, e.g. raw version info? Maybe add an echo ${LD_VERSIONFLAGS}` after the referenced loop.

**Comment by christian-posta** [comment]
building on darwin.

Thanks @ayj that's the key i was looking for. There's some bug in here, i'll find it and submit a PR.

**Comment by christian-posta** [comment]
nm. i was doing the build wrong. no bug here.
