### ISSUE TITLE
error unmarshalling config dump response from Envoy

### ISSUE THREAD

**Issue by jdomag** [istio/istio#25695]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
I follow the canary upgrade procedure described [here](https://istio.io/latest/docs/setup/upgrade/), however i've used profile to generate istio manifest. I'm upgrading from 1.5.2 to 1.6.5 My profile:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  addonComponents:
    grafana:
      enabled: true
      k8s:
        podAnnotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    kiali:
      enabled: true
      k8s:
        podAnnotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
  components:
    ingressGateways:
      - enabled: true
        k8s:
          replicaCount: 2
          podAnnotations:
            cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    pilot:
      k8s:
        hpaSpec:
          minReplicas: 2
        replicaCount: 2
        podAnnotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
  meshConfig:
    accessLogEncoding: JSON
    accessLogFile: "/dev/stdout"
    accessLogFormat: |
      {
        "log_type": "access_log",
        "start_time": "%START_TIME%",
        "route_name": "%ROUTE_NAME%",
        "method": "%REQ(:METHOD)%",
        "path": "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%",
        "original_url": "%REQ(X-ENVOY-ORIGINAL-URL)%",
        "response_code": "%RESPONSE_CODE%",
        "response_flags": "%RESPONSE_FLAGS%",
        "bytes_received": "%BYTES_RECEIVED%",
        "bytes_sent": "%BYTES_SENT%",
        "duration": "%DURATION%",
        "upstream_service_time": "%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%",
        "x_forwarded_for": "%REQ(X-FORWARDED-FOR)%",
        "x_credential_username": "%REQ(X-CREDENTIAL-USERNAME)%",
        "x_request_id": "%REQ(X-REQUEST-ID)%",
        "user_agent": "%REQ(USER-AGENT)%",
        "request_id": "%REQ(X-REQUEST-ID)%",
        "authority": "%REQ(:AUTHORITY)%",
        "upstream_host": "%UPSTREAM_HOST%",
        "upstream_cluster": "%UPSTREAM_CLUSTER%",
        "upstream_local_address": "%UPSTREAM_LOCAL_ADDRESS%",
        "downstream_local_address": "%DOWNSTREAM_LOCAL_ADDRESS%",
        "downstream_remote_address": "%DOWNSTREAM_REMOTE_ADDRESS%",
        "requested_server_name": "%REQUESTED_SERVER_NAME%",
        "istio_policy_status": "%DYNAMIC_METADATA(istio.mixer:status)%",
        "upstream_transport_failure_reason": "%UPSTREAM_TRANSPORT_FAILURE_REASON%"
      }
    defaultConfig:
      proxyMetadata:
        TERMINATION_DRAIN_DURATION_SECONDS: "60"
    enableAutoMtls: false

  values:
    global:
      proxy:
        excludeIPRanges: "10.60.1.0/24,10.40.10.0/24"
      tracer:
        zipkin:
          address: "jaeger-operator-jaeger-collector.monitoring:9411"

    pilot:
      keepaliveMaxServerConnectionAge: 40m
      traceSampling: 10

```

Command to generate manifest:
```
./bin/istioctl manifest generate --set profile=default --set revision=v165 -f my_profile.yaml > manifest_1_6_5.yaml
kubectl apply -f manifest_1_6_5.yaml
```
When i label my namespace as follows:
`$ kubectl label namespace test-ns istio-injection- istio.io/rev=v165`

and restart one pod i try to check if upgrade worked with command:

`istioctl proxy-config endpoints ${pod_name}.test-ns --cluster xds-grpc -ojson | grep hostname`

And i get following error:

`Error: error unmarshalling config dump response from Envoy: unknown field "locality" in envoy_admin_v3.HostStatus`

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
See istio revision reference

**Steps to reproduce the bug**
Described above 

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```

/bin/istioctl version --remote
client version: 1.6.5
pilot version: 1.5.2
pilot version: 1.5.2
istiod version: 1.6.5
istiod version: 1.6.5
data plane version: 1.6.5 (3 proxies), 1.5.2 (33 proxies)
```
```
kubectl version                                 
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"ec6eb119b81be488b030e849b9e64fda4caaf33c", GitTreeState:"clean", BuildDate:"2020-03-12T21:00:06Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"ec6eb119b81be488b030e849b9e64fda4caaf33c", GitTreeState:"clean", BuildDate:"2020-03-12T20:52:22Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

```

**How was Istio installed?**
With manifest generated via istioctl 

**Environment where bug was observed (cloud vendor, OS, etc)**
k8s installed via kops 

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by jdomag** [comment]
uhhh i used istioctl 1.5.2 to execute the command "istioctl proxy-config endpoints" that's why it was broken. When i switched to istioctl v1.6.5 it returns correct output.

**Comment by esnible** [comment]
I see the same thing.  It works with master (future 1.7) and 1.6.4.  When I tried with 1.5.4 client it didn't work.

We strive to make _istioctl_ backwards and forwards compatible by a version with data planes.  It isn't always possible or easy to make the CLI flexible enough to work with future versions.  Unless you object I will close this and suggest the 1.5.x CLI will not work with 1.6.x sidecar.
