### ISSUE TITLE
install-cni should use standard base images

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#25693]
Currently install-cni use ubuntu:xenial as the base image. It should likely use istio/base and/or distroless like all of our other images.

Also it may consider using a precompiled `jq` (https://github.com/stedolan/jq/releases) since apt is super slow

cc @bcheung @stewartbutler

**Comment by stewartbutler** [comment]
I don't think we have a dependency on `jq` anymore, with the installer converted to go. One of the motivations for making that transition was to allow us to run in a distroless binary. I'll pick this up and move the install-cni image over.

**Comment by bcheung** [comment]
One thing to note, I used jq in the install-cni e2e tests to remove Istio CNI's config from the CNI config file. https://github.com/istio/istio/blob/master/cni/deployments/kubernetes/install/test/data/remove_istio_cni.sh
