### ISSUE TITLE
Suspicious envoy warning: Unable to use runtime singleton for feature envoy.reloadable_features.activate_fds_next_event_loop

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#25700]
Running proxy always shows this warning: `Unable to use runtime singleton for feature envoy.reloadable_features.activate_fds_next_event_loop`.

Need to figure out if its a real issue or not.

**Comment by JimmyCYJ** [comment]
Tentatively assign to @howardjohn as this is a release blocker and @howardjohn has the context, please feel free to reassign.

**Comment by howardjohn** [comment]
I have no context, needs an Envoy expert

**Comment by ramaraochavali** [comment]
I think this is not a problem. I suspect this to be a dependency ordering problem where file event is created before `Runtime::LoaderSingleton::getExisting()` is created - but it will pick up the default value (which is enabled correctly).

tagging @antoniovicente who made this change in Envoy to confirm.

**Comment by howardjohn** [comment]
Happens on latest plain envoy:
```
$ docker run envoyproxy/envoy-dev
[2020-07-27 14:51:32.484][7][warning][runtime] [source/common/runtime/runtime_features.cc:20] Unable to use runtime singleton for feature envoy.reloadable_features.activate_fds_next_event_loop
[2020-07-27 14:51:32.484][7][info][main] [source/server/server.cc:297] initializing epoch 0 (base id=0, hot restart version=11.104)
[2020-07-27 14:51:32.484][7][info][main] [source/server/server.cc:299] statically linked extensions:
```

**Comment by lambdai** [comment]
activate_fds_next_event_loop is an envoy internal feature flag.
AFAIK envoy would work in any context.

**Comment by howardjohn** [comment]
Will close an reopen in envoy side

**Comment by lambdai** [comment]
If istio need to disable it if there is sever impact, we can either 
1. update istioproxy binary, or
2. introduce runtime layer in bootstrap to inject the required runtime layer.
