### ISSUE TITLE
Prometheus with Istio Proxy not scraped metrics from all Pods

### ISSUE THREAD

**Issue by SU34** [istio/istio#25706]
We have ***Prometheus*** in ***OpenShift*** in one **namespace** (for example: "**TestNamespace**"), which is scraped metrics from ***two or more*** **PODs** of something *Application* (named **TestApp** for example) in the same **namespace**. 
Prometheus scrape metrics in the mode: "***service***" ("**role: service**" - in the file: "**prometheus.yaml**"), as result it scraped by **round-robin** from the **PODs**, but we need to scrape from all PODs.

***Note***: **Prometheus** and **TestApp** used **Istio Proxy** - thats why we choose "**role: service**" in **Prometheus** now, becаuse if we turn on the "**endpoints**" mode (that is in **prometheus.yaml**: "**role: endpoints**") we get error: "**502 Bad Gateway**" in **Prometheus**, metrics not scraped. 

We tried solution: **headless services** from there: https://dev.to/kaoskater08/building-a-headless-service-in-kubernetes-3bk8

As result from that solution:

`    ip address by service/test-app-service: 172.30.81.196`

and ip addresses by **headless-service**:

```
    test-app-1-7d6hv  2/2  Running 10.128.38.24    some-host-0027.vm.com
    test-app-1-jhcdm  2/2  Running 10.128.36.240   some-host-0025.vm.com
```

then, if do:

```
    ##    requests to 172.30.81.196 (created by regular service.yaml)

    #http-request from the Prometheus POD: 
    wget -qO- http://172.30.81.196:8080  -> result success
    #http-request from the side-car "istio-proxy" in Prometheus POD: 
    curl http://172.30.81.196:8080  -> result success
```

 
No problems there.
But, if 

```
    ##    reqeusts to 10.128.38.24 (headless-service)

    #http-request from the side-car istio-proxy in Prometheus POD: 
    curl http://10.128.38.24:8080  -> result success
    #http-request from the Prometheus POD: 
    wget -qO- http://10.128.38.24:8080  -> 502 Bad Gateway
```

or next ip:

```
    ##   reqeusts to 10.128.36.240 (headless-service)   

    #http-request from the side-car istio-proxy in prometheus POD: 
    curl http://10.128.36.240:8080  -> result success

    #http-request from the Prometheus POD: 
    wget -qO- http://10.128.36.240:8080  -> 502 Bad Gateway
```

So, there we get already problems in the POD's Prometheus: **502 Bad Gateway**. Prometheus not scraped metrics in result, it has this errors, which we can to see also in section: "targets" of Prometheus UI.

**But** there are no problems, if do from terminal custom http-request in the POD's Prometheus **with header**:

`    wget -qO- http://10.128.38.24:8080 --header="Host: {service_name_in_openshift}:{service_port}" -> resulted success.`

So, how we can to fix the Prometheus to scrape metrics from **all** PODs of application? What is the best way to solve it?

**Comment by ZhengzheYang** [comment]
Did you reference this [sample configuration](https://github.com/istio/istio/blob/master/samples/addons/prometheus.yaml)? I think the rules consists of service, pods, endpoints, etc.
