### ISSUE TITLE
istio/tools: investigate istio-proxy memory usage for perf benchmark test

### ISSUE THREAD

**Issue by carolynhu** [istio/istio#25709]
Context: 
https://github.com/istio/tools/pull/1093

and we already restart proxy between each test https://github.com/istio/tools/blob/master/perf/benchmark/run_benchmark_job.sh#L290
it seems that a restart will not kill memory

@lambdai  if there is any shared memory that is help between quitquitquit initiated restarts?

**Comment by carolynhu** [comment]
@lambdai please take a look

**Comment by lambdai** [comment]
quitquitquit kill the envoy process. The memory is absolutely returned to OS

**Comment by lambdai** [comment]
Meeting record:

Base line: start envoy, receive config from pilot but doesn't carry traffic. So base line is not supposed to be 0 memory usage.

**Comment by carolynhu** [comment]
I will try to switch to query from envoy: localhost:15000/memory endpoint
```
istio-proxy@sleep-6bdb595bcb-tbmwb:/$ curl localhost:15000/memory { "allocated": "17729472", "heap_size": "33554432", "pageheap_unmapped": "0", "pageheap_free": "2392064", "total_thread_cache": "3601096", "total_physical_bytes": "36306944" }
```

where the current measure of container memory is approximately equals "heap_size": "33554432", 
and we can use “allocated” memory, which is the allocated usage.

memory allocator: “heap_size” - “allocated”

**Comment by lambdai** [comment]
The major concern is that allocator's usage is unpredictable. It may impact your linear regression calculation.
