### ISSUE TITLE
Addon transition - provide an option for operator to clean up addons

### ISSUE THREAD

**Issue by linsun** [istio/istio#25701]
**Describe the feature request**

In 1.8, Addons are going to be removed.  We had discussed operator not to do anything about the addons installed by operator in prior release by default so that users have chance to install addons themselves and clean up at the right time.

There is an desire from our team to have an option to remove these operator installed addons in case users already have addon replacement ready during 1.8 install time, by setting an option like removeAddons=true

cc @ostromart @howardjohn @morvencao @irisdingbj @sdake @rvennam @kramvan1 

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[x ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by kramvan1** [comment]
+1

**Comment by sdake** [comment]
cleaning up the addons is not impossible but difficult. As the deployments are labeled by app=`addon`, they are easy to remove. I am not sure if the configmaps and other things installed with the addons are also labeled. Will take some time to dig through the repo to answer this question.

The real question is a flag really needed? This will require a change to the API repo. I don't have a strong opinion, although I think there should be a better way to do this then add an API that then will need deprecation.

If we can gain agreement on the API model, I can do the implementation work.

**Comment by linsun** [comment]
Thank you @sdake!  I put it in env WG agenda today to discuss and gather feedback on this.

**Comment by kramvan1** [comment]
Isn't one options to just freeze the addon charts and then only allow an `enable: false` for the existing Addon IOP section and mark it as deprecated.   Seems like very small change to handle this properly.

**Comment by linsun** [comment]
Discussed in today's env WG, in 1.7, server side operator will support multiple revisions.  So user could send an operator yaml with addon disabled to 1.7's operator, then install istio using 1.8's operator.  Pending validation.

@sdake @ostromart let me know if this is a good summary!

**Comment by ostromart** [comment]
Sounds good Lin.

**Comment by richardwxn** [comment]
Seems like no code change needed? Only validation and doc work needed

**Comment by bianpengyuan** [comment]
@richardwxn Any work planned for 1.8? Do you think this is a blocking issue?

**Comment by richardwxn** [comment]
I don't think it is a blocking issue, added a PR to fail hard when user try to enabling the fully deprecated addons. For the transition work, the workaround is mentioned above: apply IOP with addon disabled with 1.7 operator so the addons can be removed, then install with 1.8. This can be added to istio.io doc.

**Comment by bianpengyuan** [comment]
Ok I will move this to 1.9 then, thanks!

**Comment by linsun** [comment]
Thank you @ richardwxn!  Fail hard is good when user tries to enable it.  We have asked our users to transition out of addon so our original requirement is no longer needed. Closing this out.
