### ISSUE TITLE
Fix needed: thrift rate limiting based on deprecated Mixer client config APIs

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio#25725]
As part of removing Mixer entirely from the Istio codebase, I discovered that the Thrift rate limiting integration that was added awhile back was depending on deprecated Mixer APIs. In removing those APIs from the codebase, we will break thrift rate-limiting support. By doing the Mixer removal at the beginning of this dev cycle, we should have plenty of time to discover a workaround for restoring the behavior (previously available via `EnvoyFilter`, iirc).

I'm filing this issue to placehold the test skip i'm adding in the massive remove mixer pr (https://github.com/istio/istio/pull/25669) currently in development.

/cc @pnovotnak 

[ X ] Networking
[ X ] Policies and Telemetry

**Comment by howardjohn** [comment]
I bumped this to a P0 for 1.8, mostly to ensure we don't forget about this and ship a regression because we forgot about it :slightly_smiling_face:

**Comment by bianpengyuan** [comment]
Since there is no response, I believe this feature is unlikely being used. @gargnupur is working on rate limiting integration based on Envoy rate limit filter so I believe we have a replacement for 1.8. @pnovotnak please reopen if you think otherwise. thanks!
