### ISSUE TITLE
No graceful way to add custom recording-rule to default installed prometheus?

### ISSUE THREAD

**Issue by sanigo** [istio/istio#25728]
In the best practice document: [Observability Best Practices](https://istio.io/latest/docs/ops/best-practices/observability/#workload-level-aggregation-via-recording-rules).
I have studied the istio installation document and yamls, to find out that currently there is no graceful way to do that. 
The version is **1.6.5**
Have I missed something?

**Comment by douglas-reid** [comment]
You haven't missed anything.

There are two parts of the equation:

Istio is moving away from providing management of Prometheus installs ([related doc](https://docs.google.com/document/d/1jJ4kkALCUPWIlz_Ldu6jpeelMNxyY_SZDMaZmeSpfkM/edit#heading=h.qlmnvhzb2ib2)). So, part one is reducing the complexity of the add-on install to a default/demo level, which means no real customization.

Part two is that there isn't really a one-size-fits-all approach to those recording rules. They provide guidance on how to reduce some of data sizes and labels, but there can be issues depending on how they are intended to be used (for instance, if you need rates of the metrics in dashboards or alerts, the suggested recording rules can [cause issues](https://www.robustperception.io/rate-then-sum-never-sum-then-rate), as they sum first).

We do need to do more in this area in terms of guidance and easing use, however.

**Comment by sanigo** [comment]
I have manually installed a prometheus in istio-system namespace, and add the scrape_config from the istio installation files.I thinks it is the only way currently.

**Comment by stevehipwell** [comment]
It'd be really useful to have this documented either way; the current documents are incomplete/incorrect.

**Comment by stevehipwell** [comment]
@sanigo do you have the config that you used to get this working correctly?
