### ISSUE TITLE
istio_total_requests not generated when Isitio 1.6.5 is installed(using demo profile) in a non-default namespace

### ISSUE THREAD

**Issue by mk23w-vmware** [istio/istio#25727]
**Bug description**

The istio_total_requests metric is not generated for Bookinfo services when Isitio 1.6.5 is installed (using demo profile) in a non-default namespace.

I installed Istio 1.6.5 using the demo profile but install it in the mikes-istio-services namespace instead of in istio-system, then install the BookInfo demo in the default namespace using these instructions:
https://istio.io/latest/docs/setup/getting-started/

The issue is the Kiali->Graph view shows an empty graph (see attached Kiali image).
The broken graph seems to be because the istio_requests_total metrics are not being generated for the bookinfo service requests (see attached Prometheus image). 

Istio Telemetry v2 seems broken for non istio-system namespaces.

If I update  istio.yaml (generated by "istioctl manifest generate ...") and replace mikes-istio-services with istio-system everything works fine which makes me think using a non-default (non istio-system) namespace is causing this problem.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[] Installation
[ ] Networking
[ ] Performance and Scalability
[x ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

istio_total_requests should be generated for bookinfo services.

**Steps to reproduce the bug**

This is consistently reproducible.

Follow these instructions: https://istio.io/latest/docs/setup/getting-started/
But make the following changes:
* Generate Istio 1.6.5 manifest (eg istio.yaml) using demo profile, writing to istio.yaml
* Change all instances of istio-system in istio.yaml with another namespace name like mikes-istio-services
* kubectl apply -f istio.yaml
* Install bookinfo sample application 
* Issue: Kiali shows the Graph View does not have any BookInfo service graphs.
* Issue: Prometheus shows no istio_requests_total metrics were  generated for the BookInfo service requests. I believe this is why the Kiali Graph page is not showing any BookInfo service graphs.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

$ ./bin/istioctl  -c ~/d/d/coreos-ansible/kubeconfigs/default-superuser.yml  -i mikes-istio-services version --remote
client version: 1.6.5
control plane version: 1.6.5
data plane version: 1.6.5 (8 proxies)

$ kubectl --kubeconfig ~/d/d/coreos-ansible/kubeconfigs/default-superuser.yml version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:51:13Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:41:55Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**

See "Steps to reproduce the bug" section for details.

Summary:
* Followed these steps: https://istio.io/latest/docs/setup/getting-started/ to install the Demo Istio Profile.
* Generated Istio manifest, modified it to use mikes-istio-services namespace.
* Then kubectl apply the manifest.

**Environment where bug was observed (cloud vendor, OS, etc)**

* Istio 1.6.5
* Kubernetes 1.15.4 nodes running in CoreOS 2079.4.0.
* These K8s nodes run inside of VMware VMs running vSphere 6.5.x.

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching the dump file to this issue.

[istio-dump.tar.gz](https://github.com/istio/istio/files/4957264/istio-dump.tar.gz)

<img width="1303" alt="Screen Shot 2020-07-21 at 10 10 26 AM" src="https://user-images.githubusercontent.com/65002399/88121884-e9136600-cb7b-11ea-8f53-4a3a9445ed0b.png">

<img width="1303" alt="Screen Shot 2020-07-21 at 10 14 29 AM" src="https://user-images.githubusercontent.com/65002399/88121889-ec0e5680-cb7b-11ea-927f-055ea60a4a0f.png">

**Comment by bianpengyuan** [comment]
Looks like rootNamespace is still set to `istio-system` in your deployment. You will need to set it to your namespace (`--set meshConfig.rootNamespace=your-namespace`) in order to make telemetry v2 configuration in that namespace take effect.

**Comment by mk23w-vmware** [comment]
This worked. Thank you @bianpengyuan!
