### ISSUE TITLE
UDP protocol support 

### ISSUE THREAD

**Issue by dengqian** [istio/istio#25730]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
We are using Mosn as data plane and added udp_proxy feature to Mosn. So I want to know can istio support transport protocol config in LDS and udp_proxy CRD, or if there is any plan to support it? Thanks a lot.

**Comment by esnible** [comment]
Closing as a duplicate of https://github.com/istio/istio/issues/1430
