### ISSUE TITLE
upstream connect error or disconnect/reset before headers

### ISSUE THREAD

**Issue by colt-rex** [istio/istio#25734]
**Bug description**
Large requests over http frequently give an error `upstream connect error or disconnect/reset before headers. reset reason: connection termination`. With the bookinfo application but no sidecar, sending a 3MB file fails roughly 3% of the time. With the sidecar proxy enabled, sending the same 3MB file fails roughly 10% of the time.

The detailed output from curl on a failed request is:
```*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 80 (#0)
> POST /ping HTTP/1.1
> Host: 127.0.0.1
> User-Agent: curl/7.64.1
> Accept: */*
> Content-Length: 3003470
> Content-Type: multipart/form-data; boundary=------------------------77da1766c94965aa
> Expect: 100-continue
> 
< HTTP/1.1 100 Continue
< HTTP/1.1 503 Service Unavailable
< content-length: 95
< content-type: text/plain
< date: Wed, 22 Jul 2020 04:56:56 GMT
< server: istio-envoy
< connection: close
< 
* we are done reading and this is set to close, stop send
* Closing connection 0
upstream connect error or disconnect/reset before headers. reset reason: connection termination
```

**Affected product area (please put an X in all that apply)**
[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ X ] Networking
[ X ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
The expected behavior is that I should be able to send a file to an API a thousand times in a row with zero errors. When I run the API without istio's functionality, I can do that.

**Steps to reproduce the bug**
The easiest way to reproduce the bug is using the standard "bookinfo" application.
1. Run `istioctl install --set profile=demo`
2. Run `kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml; kubectl apply -f samples/bookinfo/networking/bookinfo-gateway.yaml`
3. Repeatedly run `curl -F 'foo=@/path/to/large/file' ${GATEWAY_URL}/productpage`, where you pass in some large file of a few MB's. Some will succeed and some will fail. **NOTE***

I ran the above experiment 1,000 times WITHOUT sidecar injection enabled. In that experiment, 29 of the 1,000 requests failed to complete and returned the`upstream connect error`. 

I ran the experiment 1,000 times WITH sidecar injection enabled. Interestingly, the error rate INCREASED with the proxy enabled: 96 of 1,000 requests failed to go through; and the other 904 returned the expected response (in this case, a 405).

***NOTE: A "successful" request here should return a 405 response, as we are POSTing to a GET-only endpoint. A failure is when we get the upstream connection error. I know it's not proper to test this way; but it's the easiest way to replicate. Just pretend for a minute that a 405 is like a 200, and trust (or verify) that if you want to, you can replicate the same behavior with a POST endpoint—but you'll have to deploy a different container.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```(base) (⎈ |docker-desktop:default)->istioctl version --remote
client version: 1.6.3
control plane version: 1.6.3
data plane version: 1.6.3 (3 proxies), 1.7-dev (1 proxies)

(base) (⎈ |docker-desktop:default)->kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-16T00:04:31Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:18:29Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
Istio was installed as per documentation: https://istio.io/latest/docs/setup/getting-started/

**Environment where bug was observed (cloud vendor, OS, etc)**
Docker-Desktop on MacOS

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by colt-rex** [comment]
Additional information:

The bug seems to be a race condition of some sort. The bug only surfaces when I send a large request and the API that receives the request decides to respond and then close the connection before the entire request body has passed through the gateway. In this case, I _think_ that the upstream host sends its response, then closes the connection; but the gateway continues sending the rest of the request data to the upstream host (causing a write to a closed connection --> the gateway reports back to the client that there was a 503 service unavailable).

**Comment by tariq1890** [comment]
@colt-rex Can you check this comment? This might probably help you
