### ISSUE TITLE
It is not possible to use the istioctl upgrade command in an offline environment that does not have access to github

### ISSUE THREAD

**Issue by nickperry** [istio/istio#25741]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
It is not possible to use the istioctl upgrade command in an offline environment that does not have access to github.

The command attempts to retrieve the release tarball from github for the version your are upgrading FROM.

I am including IstioOperator yaml files with -f arguments. Istioctl upgrade seems to need the profiles from the previous release tarball in order to process them... 

`2020-07-21T23:19:16.103890Z	info	Error: failed to generate Istio configs from file [values/istio-ingressgateway-istiooperator.yaml values/istio-egressgateway-istiooperator.yaml] for the current version: 1.6.5, error: Get "https://github.com/istio/istio/releases/download/1.6.5/istio-1.6.5-osx.tar.gz": dial tcp 140.82.114.4:443: i/o timeout`

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

I should be able to use istioctl upgrade in an environment that does not have access to github.

**Steps to reproduce the bug**

My exact commandline was:

istioctl upgrade -y -f some-istioOperator-config.yaml -set hub="ourlocalserver/mirrors/docker.io/istio" --set tag="${ISTIO_VERSION}" --set values.kiali.contextPath="/" --set values.kiali.dashboard.viewOnlyMode=true --set values.global.proxy.excludeIPRanges=${APP_NETWORK} --set values.kiali.hub="ourlocalserver/mirrors/docker.io/kiali" --set values.kiali.tag="v${KIALI_VERSION}" --set values.prometheus.hub="ourlocalserver/mirrors/docker.io/prom" --set values.prometheus.tag="v${PROM_VERSION}"

I think the critical factors are to include some istioOperator config yaml files with -f and run the upgrade command in an offline environment (without access to github).

**Version**

1.6.5

**How was Istio installed?**

istioctl install

**Environment where bug was observed (cloud vendor, OS, etc)**

Private data centre. Linux.

**Comment by andrewisplinghoff** [comment]
We've just encountered the same issue using a recent daily build of the 1.7 branch in a tightly locked down GKE cluster without internet access.

Are you maybe supposed to pass in the local path of the manifests folder using `--manifests` to the `istioctl upgrade` command to prevent having these downloaded again?

**Comment by vincent-chan-mox** [comment]
we are having the same problem.  any solution yet?

**Comment by krsri** [comment]
Hi @vincent-chan-mox Were you able to fix the upgrade issue? if yes please share the steps you followed. Thanks

**Comment by brianplexxi** [comment]
Is it possible to have this issue opened again - we are seeing the same happen in our environment : 

I installed istio using ->  istioctl install --set profile=default and all was fine as part of my upgrade I use -> istioctl upgrade --set profile=default --skip-confirmation --dry-run but I am getting the the following error:   2021-05-20T17:25:20.816688Z	info	proto: tag has too few fields: "-"
Control Plane - istio-ingressgateway pod - istio-ingressgateway-758985db4f-cjmnh - version: 1.9.0
Control Plane - istiod pod - istiod-7c9c9d46d4-rt8pk - version: 1.9.0
Upgrade version check passed: 1.9.0 -> 1.9.5.
2021-05-20T17:25:51.025000Z	info	Error: failed to generate Istio configs from file [] for the current version: 1.9.0, error: Get "https://github.com/istio/istio/releases/download/1.9.0/istio-1.9.0-osx.tar.gz": dial tcp 140.82.112.4:443: i/o timeout
Error: failed to generate Istio configs from file [] for the current version: 1.9.0, error: Get "https://github.com/istio/istio/releases/download/1.9.0/istio-1.9.0-osx.tar.gz": dial tcp 140.82.112.4:443: i/o timeout


I dont really understand the info	Error:                 failed to generate Istio configs from file [] for the current version: 1.9.0, error: Get "https://github.com/istio/istio/releases/download/1.9.0/istio-1.9.0-osx.tar.gz": dial tcp 140.82.112.4:443: i/o timeout. (edited) 
as I am trying to upgrade to 1.9.5 ?

**Comment by sridharan-ksec** [comment]
We have one open issue for this .
https://github.com/istio/istio/issues/32689

**Comment by nickperry** [comment]
> I dont really understand the info Error: failed to generate Istio configs from file [] for the current version: 1.9.0, error: Get "https://github.com/istio/istio/releases/download/1.9.0/istio-1.9.0-osx.tar.gz": dial tcp 140.82.112.4:443: i/o timeout. (edited)
> as I am trying to upgrade to 1.9.5 ?

@brianplexxi It's because the upgrade process needs to generate your configs for both the version you are upgrading FROM and TO.

**Comment by brianplexxi** [comment]
> > I dont really understand the info Error: failed to generate Istio configs from file [] for the current version: 1.9.0, error: Get "https://github.com/istio/istio/releases/download/1.9.0/istio-1.9.0-osx.tar.gz": dial tcp 140.82.112.4:443: i/o timeout. (edited)
> > as I am trying to upgrade to 1.9.5 ?
> 
> @brianplexxi It's because the upgrade process needs to generate your configs for both the version you are upgrading FROM and TO.
@nickperry  thanks for the quick response - appreciated
