### ISSUE TITLE
Where is the envoy-build-ubuntu image Dockerfile?

### ISSUE THREAD

**Issue by jwendell** [istio/istio#25743]
Envoy prow jobs uses `piotrsikora/envoy-build-ubuntu` as the image to run the tests.

1. Where are the sources for it?
1. Can we move them (if not already) to Istio org?
1. Can we push them under the istio hub on docker hub, using our automated tools?

**Comment by jwendell** [comment]
cc @PiotrSikora @howardjohn

**Comment by howardjohn** [comment]
It's an envoy image not istio

**Comment by jwendell** [comment]
I see.

The motivation for this issue was the fact the we are having failures on 1.7 envoy prow jobs due to the lack of the `bzip2` binary in the images we are using. AFAICT envoy upstream is using the `envoyproxy/envoy-build-ubuntu` images, which works fine.

Can we switch to that upstream image in our prow jobs for 1.7 then?

**Comment by jwendell** [comment]
I think we can close this one since we moved to using upstream image for 1.7 jobs in https://github.com/istio/test-infra/pull/2829
