### ISSUE TITLE
'kubectl explain' support for IstioOperator CRD

### ISSUE THREAD

**Issue by esnible** [istio/istio#25760]
If the IstioOperator CRD can be expressed as a schema it could be documented by `kubectl explain`.

Compare the output of `kubectl explain virtualservice.spec` with `kubectl explain istiooperator`.

This functionality would be useful on its own.  I can also imagine combining the output of `istioctl profile dump -o flags` with `kubectl explain <flag>` so that we can produce a document showing the default values and their meanings for every "leaf" in the IstioOperator for the default profile.

cc @ostromart What do you think?

This issue inspired by https://github.com/istio/istio/issues/25683 where a user wonders how to turn off scaling of the IngressGateway.

**Comment by esnible** [comment]
@jasonwzm Could we at least improve `kubectl explain istiooperator.spec ` so that it points to Istio doc, not Kubernetes doc?

**Comment by jasonwzm** [comment]
@esnible Do you mean the description here? https://github.com/istio/istio/blob/master/manifests/charts/base/crds/crd-operator.yaml

Substituting the doc links is easy. I wonder how helpful is that vs showing all the nested fields.

**Comment by esnible** [comment]
> Substituting the doc links is easy. I wonder how helpful is that vs showing all the nested fields.

I don't think we can show all the nested fields, `kubectl explain` can't handle 'any'.  Just pointing to our docs should be enough.

**Comment by esnible** [comment]
@jasonwzm any interest in taking this on?

**Comment by howardjohn** [comment]
I don't think we will do this. the CRD is only used for in-cluster operator, and is on the way out
