### ISSUE TITLE
Istio 1.4.9 - DestinationRule idle timeout - Doc clarification

### ISSUE THREAD

**Issue by MatteoMori** [istio/istio#25789]
Hello All,

apologies for what may sound like a stupid question.

I was reading the [Istio 1.4 DR documentation](https://archive.istio.io/v1.4/docs/reference/config/networking/destination-rule/) and I have some doubts about the HTTP ***idle timeout*** section

The document states:
> If not set, there is no idle timeout.

What does this actually mean?
* Will Istio never expire an idle connection? Therefore the value can be considered "very big"
* Is Idle timeout equivalent to 0s? 

thank you!

Matteo

**Comment by ramaraochavali** [comment]
Yes. The idle timeout is not enforced i.e. connection will never be closed based idle ness. In recent version this has been changed to 1 hour.

**Comment by MatteoMori** [comment]
Hey @ramaraochavali,

thank you very much for your reply! :-)
