### ISSUE TITLE
istioctl create_named_ports_list

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#25807]
A big advantage of outbound protocol sniffing is that we do not need to declare ports.
It comes with some additional moving parts and some a potential for things to go wrong due to incorrect detection and timeout.

We can help a user label ports
1. Enable protocol sniffing for a short duration.
2. Collects metrics
3. Use metrics to create a labeled list of ports to help the user.

Create an istioctl tool that can read from prometheus, (and or stackdriver) to read metrics and produce a list services / ports and their labels.

Alternatively, enable access logging for a short time and use the output from access logs to determine the same information.

cc @douglas-reid @carolynhu

**Comment by douglas-reid** [comment]
Is your vision for this purely user-in-the-loop suggestion-style?

**Comment by mandarjog** [comment]
Yes, "suggestion style" is safer. We can output it yaml files that can be consumed by customize for example."
