### ISSUE TITLE
Content-length: 0 header inserted in Websocket connection upgrade response

### ISSUE THREAD

**Issue by sameerbhadouria** [istio/istio#25814]
I am seeing "content-length: 0" header in the response (status code is 101 Switching protocols)  to our Websocket connection upgrade request. 

We have Istio version 1.6.3 which uses Envoy version 1.4.1
I believe this should have been fixed - at least based on https://github.com/envoyproxy/envoy/issues/5554 

Do I need to enable any flags for this to work?

The main issue I am debugging is that the initial websocket connection stays up only for a few minutes and then it gets terminated. Thereafter, all subsequent websocket requests are almost immediately terminated after getting a response to the request. We use the GCP Kubernetes Ingress as the Load balancer and one theory we have is that the load balancer might be terminating the connections after seeing "content-length: 0" header.

_Originally posted by @sameerbhadouria in https://github.com/istio/istio/issues/10783#issuecomment-660762981_

**Comment by sameerbhadouria** [comment]
Looks like this is fixed in Envoy proxy version 1.15.0 while Istio 1.6.* uses the proxy 1.14.*

Any chance this will be updated in Istio 1.6 releases?

**Comment by minho-comcom-ai** [comment]
Istio 1.7.0 is using Envoy 1.15.0
```yaml
$ kubectl exec -it istio-ingressgateway-75bf9c5cff-kmjpw -c istio-proxy -n istio-system pilot-agent request GET server_info
{
  "version": "262253d9d066f8ef7ed82fd175c28b8f95acbec0/1.15.0/Clean/RELEASE/BoringSSL"
}
```

**Comment by mstrYoda** [comment]
What is the status of this issue? We have same issue about websockets. Connections are immediately closes when we enable istio injection.

**Comment by wlhee** [comment]
I think the connections closing issue is due to envoy auto-inserts content-length: 0 header into *request*, I opened https://github.com/envoyproxy/envoy/issues/15049

**Comment by mstrYoda** [comment]
We resolved our issue by removing - mesh gateway definition from VirtualService. It is weird, but issue disappeared.

**Comment by skk2142** [comment]
@mstrYoda Same for me!! I'm still waiting for the fix. I tried using the latest release of istio (Istio 1.10.0-alpha.0) but that didn't change anything. https://github.com/istio/istio/issues/30146#issuecomment-792886844

**Comment by foshantiger** [comment]
> We resolved our issue by removing - mesh gateway definition from VirtualService. It is weird, but issue disappeared.
Can you please give some code? Thanks!
