### ISSUE TITLE
istioctl gen-deploy: add common tag for all images

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#2582]
The build pushes all images with a common tag.

Currently istioctl gen-deploy allows to specify the hub for all images, but a separate tag must be provided for pilot, mixer, ca.

As a separate sub-task, it would be good to change the location where the command is looking for templates, from the current dir to "install/kubernetes/helm", so the command can be run from the root of istio.

**Comment by tomgeorge** [comment]
Could I pick this up?

**Comment by andraxylia** [comment]
You bet! PRs are welcome, thanks for contributing. Please make a request to join the Istio organization, so you can assign the issue to you.

**Comment by tomgeorge** [comment]
@andraxylia, thanks!  I enabled two-factor authentication and have added access keys, but I'm not sure where to go to request to join the istio org.

**Comment by andraxylia** [comment]
@geeknoid can you please add @tomgeorge to the Istio organization so he can work on this issue?

**Comment by tomgeorge** [comment]
Sorry, I am not 100% sure what work this task is describing, and I have a couple questions about the acceptance criteria of this.  Do you want to add an option to istioctl e.g. `--tag=0.4.0`?  

Or do you want this to be a change to the behavior of the build per the first line of the task?
>The build pushes all images with a common tag.

It looks like istioctl gen-deploy uses a common tag by default?

```
$ istioctl gen-deploy
global:
  namespace: istio-system
  sidecar-injector:
    enabled: false
  proxy:
    hub: gcr.io/istio-testing
    tag: 0.4.0
    debug: false
  pilot:
    enabled: true
    hub: gcr.io/istio-testing
    tag: 0.4.0
  security:
    enabled: true
    hub: gcr.io/istio-testing
    tag: 0.4.0
  mixer:
    enabled: true
    hub: gcr.io/istio-testing
    tag: 0.4.0
  ingress:
    use_nodeport: false
    nodeport_port: 0
  hyperkube_hub: quay.io/coreos/hyperkube
  hyperkube_tag: 0.4.0
```

and I see `defaultInstallation()` in `pilot/cmd/istioctl/gendeployment/cmd.go` uses this tag:

```go
func defaultInstall() *installation {
    return &installation{
        Mixer:       true,
        Pilot:       true,
        CA:          true,
        Ingress:     true,
        Initializer: false,

        Namespace: "istio-system",
        Debug:     false,
        NodePort:  0,

        Hub:      "gcr.io/istio-testing",
        MixerTag: defaultTag,
        PilotTag: defaultTag,
        CaTag:    defaultTag,
        ProxyTag: defaultTag,

        HyperkubeHub: "quay.io/coreos/hyperkube",
        HyperkubeTag: defaultHyperkubeTag,
    }
}
```

**Comment by costinm** [comment]
I have a PR changing the helm templates to use a single tag, and I will propose we 
stop generating helm values.yaml ( there is too much stuff in there, the simple config won't work ).

I think the main remaining issue for this issue is to make sure istioctl gen-deploy with hub/tag
parameters is putting the values in the right place. 

Normally with helm template  we woud use a '--set' - it would be great if gen-deploy had ability
to also set/override arbitrary configs, not only the tag.

**Comment by costinm** [comment]
Closing it for now - we may reopen if the helm plan doesn't work out.
