### ISSUE TITLE
Cannot apply peer authentication policy to any namespace by seeing error "admission webhook "pilot.validation.istio.io" denied the request: unrecognized type PeerAuthentication"

### ISSUE THREAD

**Issue by siluo** [istio/istio#25825]
**Bug description**
I am currently using istio 1.4.9 and I have been practicing the examples about how to apply the authentication policy on https://istio.io/latest/docs/tasks/security/authentication/authn-policy/.

However, when I tried commands listed from https://istio.io/latest/docs/tasks/security/authentication/authn-policy/#auto-mutual-tls

`$ kubectl exec $(kubectl get pod -l app=sleep -n foo -o jsonpath={.items..metadata.name}) -c sleep -n foo -- curl http://httpbin.foo:8000/headers -s | grep X-Forwarded-Client-Cert`

I could not get anything.

In addtion to that, when i tried to apply the commands from https://istio.io/latest/docs/tasks/security/authentication/authn-policy/#globally-enabling-istio-mutual-tls-in-strict-mode

`$ kubectl apply -f - <<EOF
apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "default"
  namespace: "istio-system"
spec:
  mtls:
    mode: STRICT
EOF`

I got an error saying "
 admission webhook "pilot.validation.istio.io" denied the request: unrecognized type PeerAuthentication"

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

**Steps to reproduce the bug**
Follow the setup steps and commands on https://istio.io/latest/docs/tasks/security/authentication/authn-policy/

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
% istioctl version --remote
client version: 1.4.9
citadel version: 1.4.9
egressgateway version: 1.4.9
egressgateway version: 1.4.9
galley version: 1.4.9
ingressgateway version: 1.4.9
ingressgateway version: 1.4.9
pilot version: 1.4.9
policy version: 1.4.9
sidecar-injector version: 1.4.9
telemetry version: 1.4.9
private-ingressgateway version: 
data plane version: 1.4.9 (12 proxies)
```

 ```
% kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.9", GitCommit:"e09f5c40b55c91f681a46ee17f9bc447eeacee57", GitTreeState:"clean", BuildDate:"2019-05-27T16:08:57Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:08:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

```
% helm version
Client: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.6", GitCommit:"dd2e5695da88625b190e6b22e9542550ab503a47", GitTreeState:"clean"}
```

**How was Istio installed?**
Running `curl -L https://istio.io/downloadIstio | ISTIO_VERSION=1.4.9 sh -` directly.
**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by morvencao** [comment]
You should follow 1.4 doc instead of latest one, because you have installed istio 1.4.
If I remember correct, `PeerAuthentication` was introduced since istio 1.5.

**Comment by siluo** [comment]
We are going to upgrade to 1.5 to see if it is gonna solve the issue. thank you @morvencao
