### ISSUE TITLE
Upgrading from 1.4.3 to 1.6.5 - "fail validation: unknown field"

### ISSUE THREAD

**Issue by thiagoleitetr** [istio/istio#25820]
**Bug description**
I'm following the guide to upgrade to version 1.6.5 in:
https://istio.io/latest/docs/setup/upgrade

I installed istio 1.4.3 using helm, so now in order to upgrade to 1.6.5 the first step is to convert my values.yaml file to IstioOperator CR format:
https://istio.io/latest/docs/setup/upgrade/#upgrading-from-helm-installations

**How I installed the version 1.4.3**
1) download 
```
curl -L https://istio.io/downloadIstio | sh -
cd istio-1.4.3

```
3) update CRDs
```
kubectl apply -f install/kubernetes/helm/istio-init/files/
kubectl -n istio-system wait --for=condition=complete job --all

```
4) update templates:
`helm template install/kubernetes/helm/istio --name istio --namespace istio-system --set gateways.istio-ingressgateway.type=NodePort --set kiali.enabled=true --set kiali.contextPath="/" --set kiali.ingress.enabled=true --set kiali.ingress.hosts[0]="kiali.mydomain.com" --set kiali.dashboard.auth.strategy=anonymous --set kiali.dashboard.grafanaURL=https://grafana.mydomain.com --set kiali.prometheusAddr=https://prometheus.mydomain.com --set prometheus.enabled=false --set tracing.enabled=true   --set tracing.ingress.enabled=true --set sidecarInjectorWebhook.enabled=false --set global.disablePolicyChecks=false | kubectl apply -f -
`

**Upgrade process --> generate iop file**
1) download
```
curl -L https://istio.io/downloadIstio | sh -
...
export PATH=$PWD/bin:$PATH
which istioctl
~/istio-1.6.5/bin/istioctl

```
2) create values.yaml file
```
cat values.yaml 
gateways.istio-ingressgateway.type: NodePort
kiali.enabled: true
kiali.ingress.enabled: true
kiali.ingress.hosts:
  - kiali.agibank-dev.in
kiali.dashboard.auth.strategy: anonymous
kiali.dashboard.grafanaURL: https://grafana.mydomain.com
kiali.prometheusAddr: https://prometheus.mydomain.com
prometheus.enabled: false
tracing.enabled: true
tracing.ingress.enabled: true
sidecarInjectorWebhook.enabled: false
global.disablePolicyChecks: false

```
3) Every time that I try to generate the file I have a different error:

```
istioctl manifest migrate values.yaml > iop.yaml
Error: the input values.yaml fail validation: unknown field "gateways.istio-ingressgateway.type" in v1alpha1.Values
check against https://github.com/istio/istio/blob/release-1.6/operator/pkg/apis/istio/v1alpha1/values_types.proto for schema
or run the command with --force flag to ignore the error

istioctl manifest migrate values.yaml > iop.yaml
Error: the input values.yaml fail validation: unknown field "kiali.dashboard.auth.strategy" in v1alpha1.Values
check against https://github.com/istio/istio/blob/release-1.6/operator/pkg/apis/istio/v1alpha1/values_types.proto for schema
or run the command with --force flag to ignore the error

```
Note: I tried to put the word "values." before de properties in values.yaml file, but it still didnt work.

[ X ] Installation

**Environment where bug was observed (cloud vendor, OS, etc)**
- AWS EC2 servers
- Kubernetes v1.18.3
- OS Amazon Linux 2 (client)
- OS 18.04.4 LTS (K8S)

**Comment by howardjohn** [comment]
I think it needs to be yaml, like
```
kiali:
  dashboard:
     ....
```

**Comment by thiagoleitetr** [comment]
hum...maybe I'm doing something wrong, but still it doesnt work:

```
istioctl manifest migrate values2.yaml > iop.yaml
Error: the input values.yaml fail validation: unknown field "ingress" in v1alpha1.TracingConfig
check against https://github.com/istio/istio/blob/release-1.6/operator/pkg/apis/istio/v1alpha1/values_types.proto for schema
or run the command with --force flag to ignore the error

which istioctl
~/istio-1.6.5/bin/istioctl


cat values2.yaml 
gateways: 
  istio-ingressgateway: 
    type: NodePort
global: 
  disablePolicyChecks: false
kiali: 
  enabled: true
  ingress: 
    dashboard: 
      auth: 
        strategy: anonymous
      grafanaURL: "https://grafana.mydomain.com"
    enabled: true
    hosts: 
      - kiali.mydomain.com
  prometheusAddr: "https://prometheus.mydomain.com"
prometheus: 
  enabled: false
tracing: 
  enabled: true
  ingress: 
    enabled: true
```

**Comment by gudeyang1** [comment]
got the same problem upgrading istio 1.5.8 to 1.6.5 using the default helm values.yaml
```
[root@localhost istio-1.6.5]# ./bin/istioctl manifest migrate /root/istio-1.5.8/install/kubernetes/helm/istio/values.yaml
Error: the input values.yaml fail validation: unknown field "includeInboundPorts" in v1alpha1.ProxyConfig
check against https://github.com/istio/istio/blob/release-1.6/operator/pkg/apis/istio/v1alpha1/values_types.proto for schema
or run the command with --force flag to ignore the error

```
and the `--force` not working
```
[root@localhost istio-1.6.5]# ./bin/istioctl manifest migrate /root/istio-1.5.8/install/kubernetes/helm/istio/values.yaml --force
Error: the input values.yaml fail validation: unknown field "dnsRefreshRate" in v1alpha1.ProxyConfig
check against https://github.com/istio/istio/blob/release-1.6/operator/pkg/apis/istio/v1alpha1/values_types.proto for schema
or run the command with --force flag to ignore the error
```
 BTW,  does istio support skip-level upgrades from 1.4 to 1.6?  From https://istio.io/latest/news/releases/1.6.x/announcing-1.6/upgrade-notes/  i notice istio doesn't support  skip-level upgrades, but from  https://istio.io/latest/docs/setup/upgrade/, seems it's supported, this is really confusing me
