### ISSUE TITLE
Update grafana dashboard with Wasm metrics

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#25843]
Wasm already shows

wasm.envoy.wasm.runtime.null.active: 18
wasm.envoy.wasm.runtime.null.created: 18
wasm_filter.stats_filter.cache.hit.metric_cache_count: 408405500
wasm_filter.stats_filter.cache.miss.metric_cache_count: 945
wasm_vm.envoy.wasm.runtime.null.active: 18
wasm_vm.envoy.wasm.runtime.null.cloned: 0
wasm_vm.envoy.wasm.runtime.null.created: 18

And newly added wasm config metrics: https://github.com/istio/proxy/pull/2939/files

In addition add: container_cpu_cfs_throttled_seconds_total. for istio-proxies to ensure that cpu is not being throttled.

**Comment by douglas-reid** [comment]
Duplicate of #24920 ?

**Comment by carolynhu** [comment]
Follow up issues: 
- https://github.com/istio/istio/issues/28240

**Comment by carolynhu** [comment]
Todo: add a release grafana dashboard ID
