### ISSUE TITLE
XDS: HTTP ECDS ExtensionConfigDiscoveryService

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#25859]
[Extension Config discovery service](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/extension.proto#envoy-v3-api-msg-config-core-v3-extensionconfigsource) addresses several key issues while loading Wasm Extensions. It is not limited to Wasm.

1. It ensures that named bits are fetched only once per named extension config. This is important for Wasm where a module can be several MB and the same extension is loaded in several different listeners.
2. Loading a new version of extension does not cause a listener drain.

We may be able to get this into istio-proxy 1.7 and then experiment with in the main branch.

**Comment by mandarjog** [comment]
cc @PiotrSikora

**Comment by kyessenov** [comment]
xref: #25484

**Comment by kyessenov** [comment]
First attempt https://github.com/istio/istio/pull/27686

**Comment by hzxuzhonghu** [comment]
Fixed by #29990 and #30086
