### ISSUE TITLE
Tag istio envoy repo at release publishing

### ISSUE THREAD

**Issue by bianpengyuan** [istio/istio#25866]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Propose tag istio/envoy the same as other deps. Several potential ways to do this:
1) Bring back istio.deps in istio/proxy, and add presubmit check into istio/proxy to make sure envoy sha there is the same as the one in Workspace file.
2) Add another dep type into release-builder, such as proxy_workspace, which instructs release builder to parse envoy sha from prixy workspace file.

I think 1) is a better option.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[x] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by bianpengyuan** [comment]
cc @howardjohn

**Comment by howardjohn** [comment]
I prefer 2 personally. I would rather have complexity in the tool than in manual developer action. I don't really work in this area much though so maybe I don't have enough context though, 1 would work as well
