### ISSUE TITLE
Citadel: Certificate is NOT authorized to sign other certificate 

### ISSUE THREAD

**Issue by pavan-kumar-99** [istio/istio#25872]
I have followed the steps given in this https://istio.io/latest/docs/tasks/security/cert-management/plugin-ca-cert/
After generating my self signed certificates I get the following error saying that **Error: failed to create discovery service: failed to create CA: failed to create an istiod CA: certificate is not authorized to sign other certificates** 
Can you also document the openssl commands used to generate the certificate?

**Comment by christian-posta** [comment]
It checks for the Basic Constraints cert extension:

https://www.pkisolutions.com/basic-constraints-certificate-extension/

You may be able to use something like this to do it:
https://stackoverflow.com/questions/36920558/is-there-anyway-to-specify-basicconstraints-for-openssl-cert-via-command-line

FWIW, I'm a big fan of the `step` utility which can create root certs and intermediates. I have some demos (https://blog.christianposta.com/diving-into-istio-1-6-certificate-rotation/) for which you can find the scripts here: https://github.com/christian-posta/istio-demos/blob/master/cert-rotation/setup.sh#L20

**Comment by infa-pavakuma** [comment]
I was able to generate the certificates using these commands. I am not sure if this is the correct way to do them. After following these steps my istiod was able to sign the workloads with my own CA. After this, I followed the steps given in this page https://istio.io/latest/docs/tasks/security/cert-management/plugin-ca-cert/

  

    CONFIG="
      [req]
      distinguished_name=dn
      [ dn ]
      [ ext ]
      basicConstraints=CA:TRUE,pathlen:0
      "
    openssl req -config <(echo "$CONFIG") -new -newkey rsa:2048 -nodes \
      -subj "/C=IN/O=dEVOPS/OU=DevOps/ST=RJ/CN=cluster.local/emailAddress=test.kumar@gmail.com" -x509 -extensions ext -keyout root-key.pem -out root-cert.pem
    cp root-cert.pem ca-cert.pem
    cp root-key.pem ca-key.pem
    cp ca-cert.pem cert-chain.pem

**Comment by pavan-kumar-99** [comment]
I was able to generate the certificates using these commands. I am not sure if this is the correct way to do them. After following these steps my istiod was able to sign the workloads with my own CA. After this, I followed the steps given in this page https://istio.io/latest/docs/tasks/security/cert-management/plugin-ca-cert/

CONFIG="
  [req]
  distinguished_name=dn
  [ dn ]
  [ ext ]
  basicConstraints=CA:TRUE,pathlen:0
  "
openssl req -config <(echo "$CONFIG") -new -newkey rsa:2048 -nodes \
  -subj "/C=IN/O=dEVOPS/OU=DevOps/ST=RJ/CN=cluster.local/emailAddress=test.kumar@gmail.com" -x509 -extensions ext -keyout root-key.pem -out root-cert.pem
cp root-cert.pem ca-cert.pem
cp root-key.pem ca-key.pem
cp ca-cert.pem cert-chain.pem

**Comment by yangminzhu** [comment]
can you run `openssl x509 -text -noout -in ca-cert.pem` to double check the generated `ca-cert.pem` has `CA: true`?

**Comment by pavan-kumar-99** [comment]
Yes, @yangminzhu  I can see it. And I have another question. How do I generate certificates for the same purpose when I have a scenario like this 
 Parent CA 
Intermediate CA 
Actual CA -> These should be used for signing the envoy certs

**Comment by pavan-kumar-99** [comment]
Hi @christian-posta It is a really wonderful article. I am kind of new to step utility. Could you please provide the openssl commands for the same scenarios that you have show in your blog ?

**Comment by JimmyCYJ** [comment]
Given that this is not a bug in Citadel, I am going to close this issue. Please feel free to reopen it. Thanks!
