### ISSUE TITLE
[1.7.0-alpha1] simplified addons yaml fail to be applied

### ISSUE THREAD

**Issue by jmazzitelli** [istio/istio#25889]
Trying 1.7.0-alpha1's [simplified addons install method](https://github.com/istio/istio/issues/23583). Fails to install Kiali and Prometheus.

Prometheus error:

```
for: "samples/addons/prometheus.yaml": Deployment.apps "prometheus" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app":"prometheus", "component":"server", "release":"prometheus"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```

Kiali error:

```
unable to recognize "samples/addons/kiali.yaml": no matches for kind "Kiali" in version "kiali.io/v1alpha1"
```

I know what the Kiali problem is, and it will be difficult to fix with the way the simplified method does things. `gen.sh` just builds a yaml and is to be applied via `kubectl apply -f`. However, any operator-based addon (Kiali is one) will have a problem because you need to add CRDs to the system before you can create the operator CR (the Kiali CR which is of kind kialis.kiali.io). But because the all-in-one yaml has everything in it (CRDs as well as the Kiali CR with all the rest) this will fail - you need to give the cluster a few seconds to bring the CRDs online before you can create resources of the CRD types.

Workaround - run the `kubectl apply -f samples/addons/kiali.yaml` a second time, after a few seconds pause.

[Kiali is introducing a Helm Chart](https://github.com/kiali/kiali-operator/pull/93) and there is an [istio PR](https://github.com/istio/istio/pull/25886) to pull that in once released, and if you install using helm, it just works. But using an all-in-one will be a problem (that includes one produced via helm template). At minimum, we'll need 2 yamls - one with the CRDs and a second one that installs the Operator and the Kiali CR. Or, fallback and use helm to install the addons. Provide a simple script users can use to install the helm charts.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Steps to reproduce the bug**

```
$ kubectl apply -f samples/addons -n istio-system
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

These are the samples/addons found in the 1.7.0-alpha1 release here: https://github.com/istio/istio/releases/tag/1.7.0-alpha.1

**Environment where bug was observed (cloud vendor, OS, etc)**

Minikube 1.9.2

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by jmazzitelli** [comment]
We'll also want to make sure we ship Istio 1.7 with Kiali v1.21 minimum.

**Comment by howardjohn** [comment]
This is about upgrade only for the prometheus issue. Basically migration from istioctl to samples will need some more. Possible fix is `--force`, need to sync with some other work on this area though (https://github.com/istio/istio/issues/25701).

For the kiali issue - agree on your assessment, I think it must happen more on minikube/kind which is much faster on apply, I never saw it on GKE but just hit it on kind. We may just have to document to rerun it I suppose...

**Comment by jmazzitelli** [comment]
> We may just have to document to rerun it I suppose...

I think that's a fair workaround. This is for quick demo'ing and kick-the-tires anyway. A more formal solution would get more complex and start introducing scripts and then it will slowly grow out of hand as people ask for more features in that script ("Well, you already have a script, can't you make it do \<fill in the blank for the next shiny thing\>, too?")

**Comment by howardjohn** [comment]
We can also just have a step process (`kubectl apply kiali.yaml; kubectl apply kiali-cr.yaml`), although I suspect many people will just run `kubectl apply samples/addons/` and get everything. I am about to work on making sure istio.io is up to date with all of this so I'll play around with this a bit
