### ISSUE TITLE
Pod to Pod Connection failed with  503 Service unavailable

### ISSUE THREAD

**Issue by dhineshbabuelango** [istio/istio#25882]
**Bug description**
I have istio installed in EKS, Not able to reach one particular pod from any other pod in any other namespace, getting 503 service unavailable. 

* Mark bundle as not supporting multiuse
< HTTP/1.1 503 Service Unavailable
< date: Mon, 27 Jul 2020 12:05:46 GMT
< server: envoy
< content-length: 0

**The source pod istio proxy logs shows below** 

**"response_flags":"NR"**

2020-07-27T11:52:51.455783358Z {"duration":"0","downstream_local_address":"172.20.198.23:80","upstream_transport_failure_reason":"-","route_name":"-","response_code":"503","user_agent":"curl/7.29.0","response_flags":"NR","start_time":"2020-07-27T11:52:47.877Z","method":"GET","request_id":"168de523-4c9b-965a-870d-66d70a6e09e3","upstream_host":"-","x_forwarded_for":"-","requested_server_name":"-","bytes_received":"0","istio_policy_status":"-","bytes_sent":"0","upstream_cluster":"-","downstream_remote_address":"100.95.17.182:59330","authority":"app-1","path":"/http/verify","protocol":"HTTP/1.1","upstream_service_time":"-","upstream_local_address":"-"}

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

Pod to Pod communication should work fine.

**Steps to reproduce the bug**
Not able to reproduce this issue, the same config working fine in other environments.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istio: 1.4.10

**How was Istio installed?**
Helm

**Environment where bug was observed (cloud vendor, OS, etc)**
Linux

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by christian-posta** [comment]
Is there a valid route for this service? `istioctl proxy-config routes` to check

**Comment by howardjohn** [comment]
503 NR usually indicates the route is referring to a cluster that doesn't exist. Can you give more info like a config dump https://github.com/istio/istio/wiki/Troubleshooting-Istio
Also see https://istio.io/latest/news/support/announcing-1.4-eol-final/

**Comment by dhineshbabuelango** [comment]
@howardjohn  @christian-posta The 503 NR was due to a duplicate virtual service, after I remove that It is working fine.
Thank you.
