### ISSUE TITLE
Fluentd support for telemetry v2

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#25888]
Mixer supports fluentd with a uniformly configurable log entry.
https://istio.io/v1.6/docs/tasks/observability/mixer/logs/fluentd/

With v2 we need to explore all options including
1. Use native envoy json output and send it to fluentd.
2. Write a fluentd sync using Wasm json output
3. Add upstream support in envoy for fluentd sync

@douglas-reid @gargnupur

**Comment by douglas-reid** [comment]
Do we want it to be as configurable as the Mixer version?  When this work was suggested at a ToC meeting, there was some pushback. What is the priority here?

**Comment by mandarjog** [comment]
Uniform configurability and abstract logEntry had the push back.
As we frequently do, we can forgo the Istio wide API at least in the Wasm implementation case.

**Comment by mandarjog** [comment]
not-stale

**Comment by mandarjog** [comment]
Not stale.
