### ISSUE TITLE
Why healthy_panic_threshold configured in OutlierDetection

### ISSUE THREAD

**Issue by ethanhanjiahao** [istio/istio#25883]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**HealthyPanicThreshold configured in OutlierDetection**
health_panic_threshold is a configuration to set CommonLbConfig for cluster.  Default to 50. 
As the concept in envoy: The panic threshold is used to avoid a situation in which host failures cascade throughout the cluster as load increases.
But in Istio, the configuration is in DestinationRule, minHealthPercent in OutlierDetection.
The Istio code is:
![image](https://user-images.githubusercontent.com/10829448/88542971-dc928000-d049-11ea-9ad4-6876a94c6135.png)

**Can we extract a common configuration**
Cause of, we add  configuration in DestinationRule to add active health check. If we want to make the active health check, and set healthyPanicThreshold to 0.  At the same time,  it will influence the OutlierDetection minHealthPercent. 

I want know，why we cannot extract a common configuration to config the health_panic_threadThreshold in CommonLbConfig.

- [x] Networking
- [x] Policies and Telemetry
- [x] User Experience

**Comment by christian-posta** [comment]
It was originally added so we could mimic behavior with Envoy's outlier detection and other library-based circuit breaker implementation. 

So under the covers this gets set on Envoy's CommonLBConfig as you pointed out. Are you asking to make the API not be outlier-detection specific?

**Comment by ethanhanjiahao** [comment]
> It was originally added so we could mimic behavior with Envoy's outlier detection and other library-based circuit breaker implementation.
> 
> So under the covers this gets set on Envoy's CommonLBConfig as you pointed out. Are you asking to make the API not be outlier-detection specific?

Yes. Because we add active_health_check configuration such as 
![image](https://user-images.githubusercontent.com/10829448/88619396-0c836700-d0ce-11ea-8ed1-f5b0b0dd4e7e.png)
To config Envoy's core.HealthCheck.   

But because the Envoy's CommonLBConfig is only one config. I think Istio should extract the common config for panic_threshold.
If not, unless we modify the code in Istio, some configuration will influence each other between outlier-detection configuration and active_health_check.

**Comment by ramaraochavali** [comment]
Sorry. I may be not following you fully - How does it matter where it lives in Istio API section, when it is finally applied CommonLBConfig in Envoy?

**Comment by howardjohn** [comment]
Can you clarify the issue?

**Comment by howardjohn** [comment]
I don't see why we would change the destination rule api given we don't actually support active health check?

**Comment by ethanhanjiahao** [comment]
> I don't see why we would change the destination rule api given we don't actually support active health check?

Thank you for your apply. I agree it. 
But in our scenes, if we change the destination rule api, we can make it easier to expand the active health. Also it will also correspond with envoy's config.

**Comment by howardjohn** [comment]
> But in our scenes, if we change the destination rule api, we can make it easier to expand the active health. Also it will also correspond with envoy's config.


I don't think we have any desire to change the API to align with a hypothetical feature which we do not support, nor is it a goal for our APIs to closely represent Envoy.

**Comment by howardjohn** [comment]
Closing as we do not intended to mirror Envoy's api. you may want to follow https://github.com/istio/istio/issues/10537
