### ISSUE TITLE
Analysis pipeline doesn't properly shut down 

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#25893]
Example failure in CI: https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/25854/integ-pilot-k8s-tests_istio/17059

Basically the issue is if the processing is still running in a goroutine after `analyze` exits, and attempts to process a new CRD event from the next test. This leads to a panic.

In theory we could also just fix the panic

**Comment by esnible** [comment]
@howardjohn I can't figure this one out!  My eyeball analysis of the code suggests this problem can't manifest.

Would you accept a PR that is just logging and `if != null` around that line?

**Comment by esnible** [comment]
@jasonwzm Are you available to take this one?

**Comment by howardjohn** [comment]
I think this will be obsolete once we move to Istiod code
