### ISSUE TITLE
unable to create gateway and virtualservice as part of bookinfo app installation.

### ISSUE THREAD

**Issue by chilu49** [istio/istio#25904]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
kubectl apply -f samples/bookinfo/networking/bookinfo-gateway.yaml
unable to recognize "samples/bookinfo/networking/bookinfo-gateway.yaml": no matches for kind "Gateway" in version "networking.istio.io/v1alpha3"
unable to recognize "samples/bookinfo/networking/bookinfo-gateway.yaml": no matches for kind "VirtualService" in version "networking.istio.io/v1alpha3"

**Affected product area (please put an X in all that apply)**
istio 1.6.5
[ ] Configuration Infrastructure
kuberntes
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
client version: 1.6.5
control plane version: 1.6.5
data plane version: 1.6.5 (9 proxies)

Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"e0fccafd69541e3750d460ba0f9743b90336f24f", GitTreeState:"clean", BuildDate:"2020-04-16T11:44:03Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5+vmware.1", GitCommit:"f8b685623a975d20a9b35685c24611c44d464b3b", GitTreeState:"clean", BuildDate:"2020-05-01T21:32:30Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
istioctl install --set profile=demo
**Environment where bug was observed (cloud vendor, OS, etc)**
[istio-dump.tar.gz](https://github.com/istio/istio/files/4985128/istio-dump.tar.gz)

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by morvencao** [comment]
What's the output of `kubectl get crd | grep networking.istio.io`? Is there log for `istioctl install --set profile=demo`?

**Comment by esnible** [comment]
Did you install Istio on your cluster with `istioctl install`?  What was the output?

**Comment by howardjohn** [comment]
@chilu49 any more info?

**Comment by howardjohn** [comment]
Closing as we have no updates and I think this is an install mistake
