### ISSUE TITLE
Istio install waiting for ever, problem persistent.

### ISSUE THREAD

**Issue by AlejandroITOP** [istio/istio#25916]
I am installing the istio in my kubernete the problem is that it never goes through the istioctl step manifest apply --set profile = demo, I have used the installation verification command ("istioctl verify-install") it indicates that everything is correct and ready to install but during the installation process it shows me an error on the screen when installing and waiting time
![image](https://user-images.githubusercontent.com/50695114/88683471-c0dfb600-d0eb-11ea-8438-eb6b4462e58a.png)

Containers do not start:

![image](https://user-images.githubusercontent.com/50695114/88683336-92fa7180-d0eb-11ea-8741-98373994d0ac.png)

The result of the describe is:

![image](https://user-images.githubusercontent.com/50695114/88684157-714dba00-d0ec-11ea-9316-2268fdc5408b.png)

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by howardjohn** [comment]
This seems very unlikely to be an Istio problem and looks more like and issue with your kubernetes cluster. can you even start any pods at all?

**Comment by AlejandroITOP** [comment]
Hello, you were right it was a problem of kubernetes and it is already solved but I now have another problem, when doing the demo installation I get this:
![image](https://user-images.githubusercontent.com/50695114/88981365-aa895400-d2bd-11ea-8ba3-d49312dfc34a.png)


When I do a kubectl logs it shows me the following:
![image](https://user-images.githubusercontent.com/50695114/88981423-d0aef400-d2bd-11ea-9752-f3017dc10a0a.png)

If you can guide me.

**Comment by howardjohn** [comment]
pass `-c istio-init`

**Comment by howardjohn** [comment]
Any more info?

**Comment by AlejandroITOP** [comment]
No, thanks
