### ISSUE TITLE
Enable more analyzers in Istiod

### ISSUE THREAD

**Issue by esnible** [istio/istio#25917]
13 of config analysers don't work using gcr.io/istio-testing latest.  It was 10 in 1.6.4.

I installed with `values.global.istiod.enableAnalysis=true`.  The istiod logs show

```
info	analysis	Skipping analyzer "annotations.K8sAnalyzer" because collection k8s/core/v1/namespaces is disabled.
info	analysis	Skipping analyzer "auth.AuthorizationPoliciesAnalyzer" because collection k8s/core/v1/namespaces is disabled.
info	analysis	Skipping analyzer "deployment.MultiServiceAnalyzer" because collection k8s/core/v1/services is disabled.
info	analysis	Skipping analyzer "deprecation.DeprecationAnalyzer" because collection k8s/apiextensions.k8s.io/v1/customresourcedefinitions is disabled.
info	analysis	Skipping analyzer "gateway.IngressGatewayPortAnalyzer" because collection k8s/core/v1/pods is disabled.
info	analysis	Skipping analyzer "gateway.SecretAnalyzer" because collection k8s/core/v1/pods is disabled.
info	analysis	Skipping analyzer "injection.Analyzer" because collection k8s/core/v1/namespaces is disabled.
info	analysis	Skipping analyzer "injection.ImageAnalyzer" because collection k8s/core/v1/namespaces is disabled.
info	analysis	Skipping analyzer "meshnetworks.MeshNetworksAnalyzer" because collection istio/mesh/v1alpha1/MeshNetworks is not in the snapshot(s).
info	analysis	Skipping analyzer "service.PortNameAnalyzer" because collection k8s/core/v1/services is disabled.
info	analysis	Skipping analyzer "sidecar.SelectorAnalyzer" because collection k8s/core/v1/pods is disabled.
info	analysis	Skipping analyzer "virtualservice.DestinationHostAnalyzer" because collection k8s/core/v1/services is disabled.
info	analysis	Skipping analyzer "schema.ValidationAnalyzer.MeshNetworks" because collection istio/mesh/v1alpha1/MeshNetworks is not in the snapshot(s).
```

cc @therealmitchconnors

**Comment by therealmitchconnors** [comment]
Most of these look correct to me.  enableAnalysis writes its output to the status field, so any analyzers which report errors referring to kubernetes objects have nowhere to write to until the troubleshooting API is complete.  There are a few that seem like they might write status to Istio objects, but with K8s objects as inputs, and I don't think those should be disabled.

cc @jasonwzm

**Comment by jasonwzm** [comment]
This looks suspicious that the collections are deemed disabled. I don't see those in local istioctl logs though.

**Comment by esnible** [comment]
`istioctl` and Istiod have different sets of collections they enable.  `istioctl` enables all of the ones needed for analysis (or it should if it doesn't.)

If Istiod lacks a collection needed for an analyzer that analyzer won't run and the only output is in the logs.  This only effects users who install with `--set values.global.istiod.enableAnalysis=true`.  Probably Istiod should watch additional collections if it is launched with the analysis flag turned on.

**Comment by esnible** [comment]
In addition to enabling the full set of analyzers, analysis should indicate that it ran and did not find a problem with the CRD.  Currently if no analyzer reported a problem there is no `Status` and no `validationMessages:`.  Probably there should be a `success` message or at least an empty list when a CRD is deemed correct by analysis.

**Comment by jasonwzm** [comment]
I see... We can add the collections in the default snapshot to make it work. But eventually we will move away from the snapshot model.

**Comment by esnible** [comment]
Not stale.

I'd like to target 1.10 for this.  We can handle it with docs, adding a note to every error code page if that analyzer that produces it only works with istioctl.  Better would be to enable these analyzers, unless there are performance penalties.
