### ISSUE TITLE
Sidecar injection should be idempotent

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#25931]
This will allow cases where  people may need re-entrant mutating webhooks, as well as potential issues around double injection (double rewrite app probe -> infinite loop, etc)

**Comment by knight42** [comment]
I would like to solve this.

**Comment by knight42** [comment]
@howardjohn I noticed that webhook server would remove injected containers/volumes/imagePullSecrets https://github.com/istio/istio/blob/324b3e098fd75e051a2cc8a82fe86b594aa48909/pkg/kube/inject/webhook.go#L508-L513, but looks like it does not check if app probe has been rewritten, do we only need to check that?
