### ISSUE TITLE
Deprecate the meshExpansion installation option

### ISSUE THREAD

**Issue by tbarrella** [istio/istio#25933]
**Describe the feature request**
As part of #22095, it would be beneficial to move the work done by `meshExpansion` from an installation-time option to user-applied config
- [x] Copy the associated Gateway/VirtualService/DestinationRule from the installer chart to a code sample
- [x] Modify tests to use the sample instead of `meshExpansion`
- [x] Add documentation for using the sample
- [x] Add port 15012 to the default value for `components.ingressGateways[name=istio-ingressgateway].k8s.service.ports`
- [x] Designate `meshExpansion`/`meshExpansionPorts` as deprecated
- [ ] Evaluate feedback on the sample documentation
- [ ] (In the future) Remove `meshExpansion`/`meshExpansionPorts`

**Describe alternatives you've considered**
- Keeping things as is: Users need to decide whether to enable multicluster at install time; if this decision is changed later, Istio must be reinstalled
- Don't expose ingress Service port 15012 by default: Exposing it seems to be a sensible default for most people, i.e. where there's no cost to having another port. As long as there's no Gateway for the port, nothing should be listening at the port, so it doesn't seem to be a security issue. If a user really needs to not expose 15012, they can still override the default

Note that this is related to the general, larger-scope problem of istiod being able to dynamically manage ingress Service ports based on Gateway config

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[X] Multi Cluster
[X] Virtual Machine
[ ] Multi Control Plane

**Additional context**
The `meshExpansion` option
- Adds `meshExpansionPorts` (by default 15012 and 8853 -> 853) to the ingress Service
- Creates a Gateway, VirtualService, and DestinationalRule for directing gateway ports 15012 and 15017 to istiod

This is so that istiod's xDS port (15012) and webhook port (15017) can be accessed from outside the cluster. Port 8853 -> 853 doesn't appear to be used within Istio code...

cc @nmittler

**Comment by costinm** [comment]
Replace "move" with "copy" on second item.

We don't want to destabilize the existing users - deprecate but don't remove.

**Comment by linsun** [comment]
FYI, i have some gw/vs config in step 5 of https://github.com/istio/istio/wiki/Central-Istiod-single-cluster-steps that may be useful for you.

**Comment by tbarrella** [comment]
A note about modifying Helm values...

If 15012 is added to `ports`, if `meshExpansion=true`, this duplicates port 15012 by default in the Deployment and Service yaml. if 15012 is removed from `meshExpansionPorts`, then this does still break things for people who have custom `meshExpansionPorts`, or who have custom `ports` and `meshExpansion=true`

Maybe it's possible with Helm templating to have the install merge `ports` and `meshExpansionPorts` while favoring the port name in `meshExpansionPorts`, but this would also need to keep the first port as the first port for any load balancer health checks...

Because of all of this, adding 15012 to `ports` needs to be done at the same time as deprecating `meshExpansion`/`meshExpansionPorts`, after docs are ready

**Comment by nmittler** [comment]
@tbarrella maybe we shouldn't expose 15012 on ingress by default? Instead, could we just have the sample yaml just patch the ingress deployment?

**Comment by tbarrella** [comment]
That would work. I think I'd feel uncomfortable seeing that as a user though, mixing declarative and imperative config for the ports. It seems like that might not work very well if the install were run again later (or the standalone operator were used), or at least it would be confusing

**Comment by nmittler** [comment]
Yeah it's a bit icky, however the additional port is (hopefully) temporary anyway. And yes, if Istio were re-installed it would be overwritten, but this is just sample. I don't think it's a major concern.

**Comment by tbarrella** [comment]
Keeping this open for now (the option isn't removed yet)

**Comment by howardjohn** [comment]
Is the plan to just remove this now for Istio 1.9? Or anything else we need to do?

**Comment by tbarrella** [comment]
Yeah, I think it should be safe to just remove, unless that's against the deprecation policy or something (although it doesn't work anyway in most cases...)
