### ISSUE TITLE
istioctl latest install error: unknown flag: --skip-confirmation

### ISSUE THREAD

**Issue by carolynhu** [istio/istio#25935]
install using latest 1.8 istioctl binary got the following error:

```
istio-1.8-alpha.a92e2a5ad60ca5038bb1c416fde0ae8a7b0e0fd7/bin/istioctl manifest apply --skip-confirmation
Error: unknown flag: --skip-confirmation
```

**Comment by carolynhu** [comment]
cc @ostromart

**Comment by richardwxn** [comment]
It might not be the reason of --skip-confirmation flag, which is still in 1.8, can you try changing to run with `istioctl install xxx` instead? `manifest apply` was deprecated

**Comment by carolynhu** [comment]
@richardwxn thanks, i see. Just verified: `istioctl install` works. 

So, for this issue, the error/info message needs to be fixed when user using `istioctl manifest` (with or without `--skip-confirmation`), it should pop up information like `use istioctl install instead since from 1.8`?

cc @ostromart
