### ISSUE TITLE
Istio performance test

### ISSUE THREAD

**Issue by satishmane** [istio/istio#25937]
**Bug description**

1. app 1 is internal load balancer (3 replicas) which accepts mqtt connection from external GCP load balancer
2. app 2 is broker (3 replicas) which accepts mqtt connection from app1.

At 300K connection, 1000 request per connection per second without istio injected works fine.

I injected istio proxy in permissive mode in both pods above. Basic sanity tests - connection and publishing works fine.

When I start load gradually for example, make connections at 400 connection over 30secs and increase gradually to total 300k connections, 80% of new connection starts failing when it reaches 200k mark. 

When total 300k connection reach, I start publishing data on these connections. By this time, both connections and publishing fails at 100% rate.

App1 sidecar proxy is assigned resources : cpu : 1000m and memory : 1024Mi 
App2 sidecar proxy is assigned resources : cpu : 2000m and memory : 1024Mi

None of the pod crashes under such high load. No errors observed in both app logs and proxy logs

Can you please guide me how much cpu and memory, I should allocate to pass my regression test

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[X] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
After increasing side car proxy cpu and memory, it should work fine

**Steps to reproduce the bug**

Described in the bug description

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

istio : 1.6.3
kubernetes : 1.14 GKE

**How was Istio installed?**

using istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**

Google Cloud GKE

**Comment by howardjohn** [comment]
Each connection has 1k requests per second? So in total you have 3million requests per second on a single pod? This seems like an awful lot of data... how big is each request?

I don't think anyone can tell you an exact number of resources you will need for this, as it's highly dependant on the exact set up. Why don't you just overscales it an give each one plenty of resources and see how it works then? 

Do you have any logs on the connection failures?

**Comment by satishmane** [comment]
@howardjohn 

I realized my mistake of typing.. let me correct my numbers

app1 (load balencers) - 3 pods - each pod side car proxy cpu is 1000m and memory 1024Mi
app2 - (message broker ) - 3 pods - each pod side car proxy cpu is 2000m and memory 1024Mi

payload size is 1k
No of mqtt connections are 300K
Publishing rate is 400 per second on 400 live mqtt connections at any given point of time

**Comment by howardjohn** [comment]
Is it 400 per second on each 400 connection? So 16k rps total or just 400?

**Comment by satishmane** [comment]
@howardjohn 

At any point in the test after 300k mqtt connect and mqtt connack, 30k/s mqtt pub packets are going towards load balancer.

The istio suggested numbers are talking about using http. With http the connections are short lived, so connectsetup+request+response+tear down

We do the mqtt connection setup once, send requests thereafter

So 300k connection remain alive without tear down.. but across 300k connections, we spread 30k/s pubslish rate.

**Comment by satishmane** [comment]
Increased no of pods, cpu and memory solved issues
