### ISSUE TITLE
High memory consumption in istio-pilot

### ISSUE THREAD

**Issue by fmaslennikov** [istio/istio#25942]
**Bug description**
We had installed istio controlplane with ingressgateway into our kube cluster and discovered incredibly large memory consumpiton of pilot.

Now we have cluster with ~3500 kube services and ~2500 kube endpoints. At the same time pilot have ~12.5GiB rss.

We tried to investigate this issue and found a major memory usage during `DiscoveryServer.Push`.
![image](https://user-images.githubusercontent.com/43143230/88793969-60fa1580-d1a6-11ea-9a5a-72cb2291b9e2.png)

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[X] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Resource consumption as specified in the [docs](https://archive.istio.io/v1.4/docs/ops/deployment/performance-and-scalability/)

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
Istio version
```
client version: 1.4.9
citadel version: 1.4.9
galley version: 1.4.9
pilot version: 1.4.9
policy version: 1.4.9
sidecar-injector version: 1.4.9
telemetry version: 1.4.9
sds-secret-sync version: 
data plane version: 1.4.9 (3 proxies)
```
Kubernetes version
```
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:31:35Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
Manually with our custom specs

**Environment where bug was observed (cloud vendor, OS, etc)**
Openstack

**Comment by ramaraochavali** [comment]
There have been lot of changes and improvements after 1.4. Please try latest versions and see if this is still reproducible. Also please note https://istio.io/latest/news/support/announcing-1.4-eol-final/

**Comment by stormobile** [comment]
> There have been lot of changes and improvements after 1.4. Please try latest versions and see if this is still reproducible. Also please note https://istio.io/latest/news/support/announcing-1.4-eol-final/

Yep, but it seems that 1.4.x series is the last that supports K8s 1.11 so if possible we'd like to get some insight into how we can debug further

**Comment by howardjohn** [comment]
@fmaslennikov we cannot help without upgrading to a newer version. When you do, if you still experience issues, please post the full profile not just a screenshot. Thanks!
