### ISSUE TITLE
Sidecar injection exclude list for kube system namespaces

### ISSUE THREAD

**Issue by kramvan1** [istio/istio#25955]
**Describe the feature request**

Allow Istio Operator option to list namespaces where Sidecar injection should never happen, default with `kube-system`.   In our case, IBM Cloud, there are several additional namespaces (ibm-system, ibm-operators) that control vital pods for the cluster to operate correctly.  Those namespaces are managed by IBM and should never have sidecar injection.    If the user accidentally adds the sidecar inject enable label, the cluster will usually start to crash when any pod management is done in that namespace.

**Describe alternatives you've considered**

Doc to users does not seem to be working well, they are still enabling sidecar injection in namespaces like `kube-system`

[x] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by morvencao** [comment]
Currently this can be implemented by setting legency helm values parameter for sidecarInjectorWebhook
```
sidecarInjectorWebhook:
  neverInjectSelector: []
  alwaysInjectSelector: []
```

**Comment by howardjohn** [comment]
I don't see why we would add yet another configuration option for this. We literally have am explicit label to declare a namespace to be injected. If a user chooses to do this to kube-system, that's there fault - we can't stop everyone that wants to shoot themselves in the foot. If the docs don't make it clear it's a bad idea then we should fix that but let's not make everyone else more confused by yet another option

**Comment by kramvan1** [comment]
@howardjohn I guess I would disagree with the kube-system use case here, that should always be off limits (hardcoded in for something like this).  As for adding option for more, yeah, I can see that as over complication.

@morvencao I believe those only apply to pod labels, not namespaces.

**Comment by howardjohn** [comment]
@kramvan1 why should kube-system be off limits? I don't feel its my position to tell users what they *cannot* do. If they **explicitly** declare kube-system as injected, it would not be very respectful of the user to not allow it.

**Comment by kramvan1** [comment]
@howardjohn Sure, I can see that point.   From our IBM Cloud view, trying to keep the Master part of the cluster running 24/7 is critical, and some parts of the master control plane need to run in cluster in the kube-system namespace, so playing with that it very bad.    Trying to figure out how to prevent that "shot to the foot" in our use case.  Since we already lock down the Istio Operator/Config, was asking for some way to allow this, even if it left wide open in the default case.

**Comment by howardjohn** [comment]
@kramvan1 if your goal is to prevent users from tampering with kube-system, why do they have access to the namespace at all? They can just as easily do `kubectl delete --all -n kube-system`?

**Comment by kramvan1** [comment]
@howardjohn actually doing a delete in kube-system is ok, the cluster will recovery from that, that's the whole idea, full recovery from mistakes like this.  Unfortunately, it's harder to track all the possible unwanted webhooks that might get in the way of that recovery from being done.    Since webhooks are scoped at the pod or namespace label selector level, we don't get much control over trying to just simple just exclude kube-system in this case.  I have not found a suitable workaround for this yet, hence the reason to ask for some help.

**Comment by howardjohn** [comment]
@kramvan1 if you want to protect kube-system from your users shooting themselves, you should not given them access to add the injection label in kube-system (or any write access either). They can always `kubectl edit` the pod or `istioctl kube-inject | kubectl apply -f -` otherwise

**Comment by costinm** [comment]
Agree with John, however I also think it would be useful to provide additional MeshConfig settings to be used by injector 
to whitelist/blacklist namespaces, and possibly allow additional inject controls ( like selecting the template  to use, or
forwarding to another injector, etc). That's all long-term - but we should structure the MeshConfig so we can extend it.

I think the agreement was to migrate functionality from helm values/global to MeshConfig - and make sure we do a 
proper review. But it certainly shouldn't be operator/install/helm option.
