### ISSUE TITLE
envoyMetricsService Histograms are Missing +Inf Upper Bound

### ISSUE THREAD

**Issue by PatrickDuncan** [istio/istio#25977]
**Bug description**

This is a problem with istio/proxyv2

With a normal sidecar/Kiali/Prometheus setup the Istio histogram metrics (ex. `istio_request_duration_milliseconds_bucket`) include the `+Inf` bucket.

With the metrics received by the gRPC envoyMetricsService the +Inf bucket is missing. This is a major issue for the [histogram_quantile](https://prometheus.io/docs/prometheus/latest/querying/functions/#histogram_quantile) Prometheus function.
>The highest bucket must have an upper bound of +Inf. (Otherwise, NaN is returned.)

For now I'll just convert the highest upper bound to +Inf in my metrics service.

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

It should include the `+Inf` bucket. Here's what I receive right now:

>[histogram:<sample_count:3 sample_sum:2565 bucket:<cumulative_count:0 upper_bound:0.5 > bucket:<cumulative_count:0 upper_bound:1 > bucket:<cumulative_count:0 upper_bound:5 > bucket:<cumulative_count:0 upper_bound:10 > bucket:<cumulative_count:0 upper_bound:25 > bucket:<cumulative_count:0 upper_bound:50 > bucket:<cumulative_count:0 upper_bound:100 > bucket:<cumulative_count:0 upper_bound:250 > bucket:<cumulative_count:0 upper_bound:500 > bucket:<cumulative_count:3 upper_bound:1000 > bucket:<cumulative_count:3 upper_bound:2500 > bucket:<cumulative_count:3 upper_bound:5000 > bucket:<cumulative_count:3 upper_bound:10000 > bucket:<cumulative_count:3 upper_bound:30000 > bucket:<cumulative_count:3 upper_bound:60000 > bucket:<cumulative_count:3 upper_bound:300000 > bucket:<cumulative_count:3 upper_bound:600000 > bucket:<cumulative_count:3 upper_bound:1.8e+06 > bucket:<cumulative_count:3 upper_bound:3.6e+06 > > timestamp_ms:1595617404646 ]

**Steps to reproduce the bug**

Run a gRPC envoy metrics service and print the metrics received.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
client version: 1.6.4
control plane version: 1.6.4
data plane version: 1.6.4 (12 proxies)

Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"e0fccafd69541e3750d460ba0f9743b90336f24f", GitTreeState:"clean", BuildDate:"2020-04-16T11:44:03Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9+IKS", GitCommit:"dbe4e8a5c169e0a6a8a9b7b183561fa61e161985", GitTreeState:"clean", BuildDate:"2020-07-16T01:30:57Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

Operator

**Environment where bug was observed (cloud vendor, OS, etc)**

IBM Cloud

Thanks!

**Comment by bianpengyuan** [comment]
Seems to be an envoy issue. Could you raise this to envoy instead?

**Comment by PatrickDuncan** [comment]
@bianpengyuan Sure thing, I thought you guys forked Envoy for proxyv2

**Comment by bianpengyuan** [comment]
Yes, but we are using envoy stats system to generate those stats.
