### ISSUE TITLE
TLS handshake error between istiod and apiserver

### ISSUE THREAD

**Issue by gautvenk** [istio/istio#25976]
**Bug description**
Istio installation via istioctl failed. I do see TLS handshake errors in api server logs and TLS handshake timeout errors in istiod logs. Thank you for your help.

noiro@opflex-1:~/istio-1.6.6$ istioctl install --set profile=demo
Detected that your cluster does not support third party JWT authentication. Falling back to less secure first party JWT. See https://istio.io/docs/ops/best-practices/security/#configure-third-party-service-account-tokens for details.
_ Istio core installed
  Processing resources for Istiod. Waiting for Deployment/istio-system/istiod                             Processing re_ Istiod encountered an error: failed to wait for resource: resources not ready after 5m0s: timed out waiting for the c
ondition
Deployment/istio-system/istiod
- Processing resources for Addons, Egress gateways, Ingress gateways. Waiting for Deployment/istio-system/grafana, D...
_ Egress gateways encountered an error: failed to wait for resource: resources not ready after 5m0s: timed out waiting for the condition
Deployment/istio-system/istio-egressgateway
_ Ingress gateways encountered an error: failed to wait for resource: resources not ready after 5m0s: timed out waiting for the condition
Deployment/istio-system/istio-ingressgateway
_ Addons encountered an error: failed to wait for resource: resources not ready after 5m0s: timed out waiting for the condition
Deployment/istio-system/grafana
Deployment/istio-system/prometheus
- Pruning removed resources                                                                                            Error: failed to apply manifests: errors occurred during operation
noiro@opflex-1:~/istio-1.6.6$

Pod status:
istio-system   grafana-b54bb57b9-qjh4c                     0/1     ContainerCreating   0          8h
istio-system   istio-egressgateway-94dc79cb6-xzm8s         0/1     ContainerCreating   0          8h
istio-system   istio-ingressgateway-6c5c854fbc-lm7xw       0/1     ContainerCreating   0          8h
istio-system   istio-tracing-9dd6c4f7c-pjdbc               1/1     Running             0          8h
istio-system   istiod-5d8d9dd979-d8ccs                     0/1     Running             0          8h
istio-system   kiali-d45468dc4-fs46h                       1/1     Running             0          8h
istio-system   prometheus-9c4967f7d-4nv7x                  0/2     ContainerCreating   0          8h

Istiod logs:
noiro@opflex-1:~$ kubectl logs -n istio-system istiod-5d8d9dd979-d8ccs -f
2020-07-30T07:21:54.410383Z     info    FLAG: --appNamespace=""
2020-07-30T07:21:54.410411Z     info    FLAG: --caCertFile=""
2020-07-30T07:21:54.410414Z     info    FLAG: --clusterID="Kubernetes"
2020-07-30T07:21:54.410417Z     info    FLAG: --clusterRegistriesNamespace="istio-system"
2020-07-30T07:21:54.410419Z     info    FLAG: --configDir=""
2020-07-30T07:21:54.410422Z     info    FLAG: --consulserverURL=""
2020-07-30T07:21:54.410424Z     info    FLAG: --ctrlz_address="localhost"
2020-07-30T07:21:54.410428Z     info    FLAG: --ctrlz_port="9876"
2020-07-30T07:21:54.410432Z     info    FLAG: --disable-install-crds="true"
2020-07-30T07:21:54.410434Z     info    FLAG: --domain="cluster.local"
2020-07-30T07:21:54.410437Z     info    FLAG: --grpcAddr=":15010"
2020-07-30T07:21:54.410439Z     info    FLAG: --help="false"
2020-07-30T07:21:54.410441Z     info    FLAG: --httpAddr=":8080"
2020-07-30T07:21:54.410444Z     info    FLAG: --httpsAddr=":15017"
2020-07-30T07:21:54.410448Z     info    FLAG: --keepaliveInterval="30s"
2020-07-30T07:21:54.410450Z     info    FLAG: --keepaliveMaxServerConnectionAge="30m0s"
2020-07-30T07:21:54.410452Z     info    FLAG: --keepaliveTimeout="10s"
2020-07-30T07:21:54.410455Z     info    FLAG: --kubeconfig=""
2020-07-30T07:21:54.410467Z     info    FLAG: --log_as_json="false"
2020-07-30T07:21:54.410469Z     info    FLAG: --log_caller=""
2020-07-30T07:21:54.410471Z     info    FLAG: --log_output_level="default:info"
2020-07-30T07:21:54.410473Z     info    FLAG: --log_rotate=""
2020-07-30T07:21:54.410477Z     info    FLAG: --log_rotate_max_age="30"
2020-07-30T07:21:54.410479Z     info    FLAG: --log_rotate_max_backups="1000"
2020-07-30T07:21:54.410482Z     info    FLAG: --log_rotate_max_size="104857600"
2020-07-30T07:21:54.410484Z     info    FLAG: --log_stacktrace_level="default:none"
2020-07-30T07:21:54.410488Z     info    FLAG: --log_target="[stdout]"
2020-07-30T07:21:54.410491Z     info    FLAG: --mcpInitialConnWindowSize="1048576"
2020-07-30T07:21:54.410493Z     info    FLAG: --mcpInitialWindowSize="1048576"
2020-07-30T07:21:54.410496Z     info    FLAG: --mcpMaxMsgSize="4194304"
2020-07-30T07:21:54.410498Z     info    FLAG: --meshConfig="/etc/istio/config/mesh"
2020-07-30T07:21:54.410501Z     info    FLAG: --monitoringAddr=":15014"
2020-07-30T07:21:54.410503Z     info    FLAG: --namespace="istio-system"
2020-07-30T07:21:54.410506Z     info    FLAG: --networksConfig="/etc/istio/config/meshNetworks"
2020-07-30T07:21:54.410514Z     info    FLAG: --plugins="[authn,authz,health,mixer]"
2020-07-30T07:21:54.410517Z     info    FLAG: --profile="true"
2020-07-30T07:21:54.410522Z     info    FLAG: --registries="[Kubernetes]"
2020-07-30T07:21:54.410525Z     info    FLAG: --resync="1m0s"
2020-07-30T07:21:54.410527Z     info    FLAG: --tlsCertFile=""
2020-07-30T07:21:54.410529Z     info    FLAG: --tlsKeyFile=""
2020-07-30T07:21:54.410532Z     info    FLAG: --trust-domain="cluster.local"
2020-07-30T07:21:54.413425Z     info    mesh configuration: {
    "disableMixerHttpReports": true,
    "proxyListenPort": 15001,
    "connectTimeout": "10s",
    "protocolDetectionTimeout": "0.100s",
    "ingressClass": "istio",
    "ingressService": "istio-ingressgateway",
    "ingressControllerMode": "STRICT",
    "enableTracing": true,
    "accessLogFile": "/dev/stdout",
    "defaultConfig": {
        "configPath": "./etc/istio/proxy",
        "binaryPath": "/usr/local/bin/envoy",
        "serviceCluster": "istio-proxy",
        "drainDuration": "45s",
        "parentShutdownDuration": "60s",
        "discoveryAddress": "istiod.istio-system.svc:15012",
        "proxyAdminPort": 15000,
        "statNameLength": 189,
        "concurrency": 2,
        "tracing": {
            "zipkin": {
                "address": "zipkin.istio-system:9411"
            }
        },
        "envoyAccessLogService": {

        },
        "envoyMetricsService": {

        },
        "proxyMetadata": {
            "DNS_AGENT": ""
        },
        "statusPort": 15020
    },
    "outboundTrafficPolicy": {
        "mode": "ALLOW_ANY"
    },
    "sdsUdsPath": "unix:/etc/istio/proxy/SDS",
    "enableAutoMtls": true,
    "trustDomain": "cluster.local",
    "trustDomainAliases": [
    ],
    "defaultServiceExportTo": [
        "*"
    ],
    "defaultVirtualServiceExportTo": [
        "*"
    ],
    "defaultDestinationRuleExportTo": [
        "*"
    ],
    "rootNamespace": "istio-system",
    "localityLbSetting": {
        "enabled": true
    },
    "dnsRefreshRate": "5s",
    "reportBatchMaxEntries": 100,
    "reportBatchMaxTime": "1s",
    "certificates": [
    ],
    "thriftConfig": {

    },
    "serviceSettings": [
    ],
    "enablePrometheusMerge": false
}
2020-07-30T07:21:54.413446Z     info    version: 1.6.6-4e6e7f49375d84bb35ee614c6b7d38b6c2fd3e7b-dirty-Modified
2020-07-30T07:21:54.413904Z     info    flags:
2020-07-30T07:21:54.414006Z     info    mesh networks configuration: {
   "networks": {
   }
}
2020-07-30T07:21:54.414038Z     info    No certificates specified, skipping K8S DNS certificate controller
2020-07-30T07:21:54.414682Z     info    CRD controller watching namespaces ""
2020-07-30T07:22:04.416516Z     error   failed to list CRDs: Get "https://10.96.0.1:443/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions": net/http: TLS handshake timeout
2020-07-30T07:22:15.417816Z     error   failed to list CRDs: Get "https://10.96.0.1:443/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions": net/http: TLS handshake timeout
2020-07-30T07:22:27.419139Z     error   failed to list CRDs: Get "https://10.96.0.1:443/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions": net/http: TLS handshake timeout
2020-07-30T07:22:41.420741Z     error   failed to list CRDs: Get "https://10.96.0.1:443/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions": net/http: TLS handshake timeout

API server logs:
I0730 15:42:32.167794       1 log.go:172] http: TLS handshake error from 11.3.56.46:60160: EOF
I0730 15:43:42.169182       1 log.go:172] http: TLS handshake error from 11.3.56.46:60258: EOF
I0730 15:44:52.171831       1 log.go:172] http: TLS handshake error from 11.3.56.46:60358: EOF

Istiod Pod description:
noiro@opflex-1:~/istio-1.6.6/manifests/deploy$ kubectl describe -n istio-system pod istiod-5d8d9dd979-d8ccs
Name:         istiod-5d8d9dd979-d8ccs
Namespace:    istio-system
Priority:     0
Node:         opflex-2/192.168.43.20
Start Time:   Thu, 30 Jul 2020 07:21:53 +0000
Labels:       app=istiod
              istio=pilot
              istio.io/rev=default
              pod-template-hash=5d8d9dd979
Annotations:  sidecar.istio.io/inject: false
Status:       Running
IP:           11.3.56.46
IPs:
  IP:           11.3.56.46
Controlled By:  ReplicaSet/istiod-5d8d9dd979
Containers:
  discovery:
    Container ID:  docker://3e440ad196c33782ca6446c7ec9a220f7de5114873bb7095e7abe86dfb79cab4
    Image:         docker.io/istio/pilot:1.6.6
    Image ID:      docker-pullable://istio/pilot@sha256:253a4f9a169b41d1dcf15925bbb9f94c3b1c6f542afc941d09dd0a6194b4909b
    Ports:         8080/TCP, 15010/TCP, 15017/TCP, 15053/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP, 0/TCP
    Args:
      discovery
      --monitoringAddr=:15014
      --log_output_level=default:info
      --domain
      cluster.local
      --trust-domain=cluster.local
      --keepaliveMaxServerConnectionAge
      30m
    State:          Running
      Started:      Thu, 30 Jul 2020 07:21:54 +0000
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:      10m
      memory:   100Mi
    Readiness:  http-get http://:8080/ready delay=1s timeout=5s period=3s #success=1 #failure=3
    Environment:
      REVISION:                                     default
      JWT_POLICY:                                   first-party-jwt
      PILOT_CERT_PROVIDER:                          istiod
      POD_NAME:                                     istiod-5d8d9dd979-d8ccs (v1:metadata.name)
      POD_NAMESPACE:                                istio-system (v1:metadata.namespace)
      SERVICE_ACCOUNT:                               (v1:spec.serviceAccountName)
      PILOT_TRACE_SAMPLING:                         100
      CONFIG_NAMESPACE:                             istio-config
      PILOT_ENABLE_PROTOCOL_SNIFFING_FOR_OUTBOUND:  true
      PILOT_ENABLE_PROTOCOL_SNIFFING_FOR_INBOUND:   true
      INJECTION_WEBHOOK_CONFIG_NAME:                istio-sidecar-injector
      ISTIOD_ADDR:                                  istiod.istio-system.svc:15012
      PILOT_ENABLE_ANALYSIS:                        false
      CLUSTER_ID:                                   Kubernetes
      CENTRAL_ISTIOD:                               false
    Mounts:
      /etc/cacerts from cacerts (ro)
      /etc/istio/config from config-volume (rw)
      /var/lib/istio/inject from inject (ro)
      /var/run/secrets/istio-dns from local-certs (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from istiod-service-account-token-dkjpb (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  local-certs:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  cacerts:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  cacerts
    Optional:    true
  inject:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      istio-sidecar-injector
    Optional:  true
  config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      istio
    Optional:  false
  istiod-service-account-token-dkjpb:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  istiod-service-account-token-dkjpb
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Warning  Unhealthy  23s (x10200 over 8h)  kubelet, opflex-2  Readiness probe failed: Get http://11.3.56.46:8080/ready: dial tcp 11.3.56.46:8080: connect: connection refused

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Expected to see istio installation go through with all the PODs in ready state.

**Steps to reproduce the bug**
Steps mentioned above.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
noiro@opflex-1:~/istio-1.6.6/manifests/deploy$ istioctl version --remote
client version: 1.6.6
control plane version: 1.6.6

noiro@opflex-1:~/istio-1.6.6/manifests/deploy$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
https://istio.io/latest/docs/setup/getting-started/
istioctl install --set profile=demo

**Environment where bug was observed (cloud vendor, OS, etc)**
Ubuntu 18.04.4 LTS

**Comment by cober** [comment]
We are also seeing same issue since we updated it to 1.6.6

**Comment by gautvenk** [comment]
I also see these errors in api-server just before TLS handshake errors: 
I0730 17:08:15.088126       1 client.go:361] parsed scheme: "endpoint"
I0730 17:08:15.088160       1 endpoint.go:68] ccResolverWrapper: sending new addresses to cc: [{https://127.0.0.1:2379  <nil> 0 <nil>}]
W0730 17:08:15.402688       1 dispatcher.go:128] Failed calling webhook, failing open validation.istio.io: failed calling webhook "validation.istio.io": Post https://istiod.istio-system.svc:443/validate?timeo
ut=30s: Service Unavailable


This might be because istiod isnt ready due to TLS handshake errors:
noiro@opflex-1:~$ kubectl describe endpoints -n istio-system istiod
Name:         istiod
Namespace:    istio-system
Labels:       app=istiod
              install.operator.istio.io/owning-resource=installed-state
              install.operator.istio.io/owning-resource-namespace=istio-system
              istio=pilot
              istio.io/rev=default
              operator.istio.io/component=Pilot
              operator.istio.io/managed=Reconcile
              operator.istio.io/version=1.6.6
              release=istio
Annotations:  endpoints.kubernetes.io/last-change-trigger-time: 2020-07-30T17:08:01Z
Subsets:
  Addresses:          <none>
  NotReadyAddresses:  11.3.56.54

**Comment by howardjohn** [comment]
Duplicate of https://github.com/istio/istio/issues/25974, see the comments for details. We will have a patch release shortly to fix this

**Comment by gautvenk** [comment]
Hi @howardjohn, I got the same errors with istio 1.5.2 and 1.6.5 as well. I will try with 1.6.5 again and report the details.

**Comment by howardjohn** [comment]
@gautvenk sorry was way to quick to close - this is likely a different error

**Comment by gautvenk** [comment]
Thank you. Do u have any suggestions for this error?

**Comment by gautvenk** [comment]
Adding more logs:
export CA_CERT=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
export TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
export NAMESPACE=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)

curl -v --cacert $CA_CERT -H "Auth$ orization: Bearer $TOKEN" "https://10.96.0.1/api/v1/namespaces/$NAMESPACE/services/"$ $ $
*   Trying 10.96.0.1...
* TCP_NODELAY set
* Connected to 10.96.0.1 (10.96.0.1) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
<-- Stuck here.

noiro@opflex-1:~/istio-1.6.6$ kubectl describe secrets -n istio-system istiod-service-account-token-5lc5s
Name:         istiod-service-account-token-5lc5s
Namespace:    istio-system
Labels:       <none>
Annotations:  kubernetes.io/service-account.name: istiod-service-account
              kubernetes.io/service-account.uid: aa88d165-03d1-414e-a877-b1f2bd20719b

Type:  kubernetes.io/service-account-token

Data
====
ca.crt:     1025 bytes
namespace:  12 bytes
token:      eyJhbGciOiJSUzI1NiIsImtpZCI6IkkxY19adFNvakJlT3IwMW9FYUgtaW1pbFBNcGRleThzaXZCaDJ5RElZQ00ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJpc3Rpby1zeXN0ZW0iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiaXN0aW9kLXNlcnZpY2UtYWNjb3VudC10b2tlbi01bGM1cyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJpc3Rpb2Qtc2VydmljZS1hY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiYWE4OGQxNjUtMDNkMS00MTRlLWE4NzctYjFmMmJkMjA3MTliIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmlzdGlvLXN5c3RlbTppc3Rpb2Qtc2VydmljZS1hY2NvdW50In0.mMKceY1x5XB-T1s8s7cXFq3_rXPA73I1xAjqZVl0tf1xknrk5RGFlsJ8rNN0dzXe-s5FE-9G1Q9hajBwUFx6rZ2SM35hMPokDXRD3jkfTAO8jNgzrYDuHqe0WzUO8vp7hsYrnSvGBJbSSOtaIJpc28rFxcgKVCQxJ8TMbFnuOD-379VCelyKKkEqZ4gfeYY82hq5xfkpkRu5JlYRe3vavt-zeqmw7uwIVakkf88hqMwxG2qkxPcgiACgcf339ySATGBQYwntEYjlmH87wcn6U7PBYY0lKADreXAQcmtwuOmpXJlYnBOXOwTJ8cTPjKqeF20kxqb4pphMEre7mfR2gw

**Comment by gautvenk** [comment]
The problem was because TLS pkts are huge and the overlay Vxlan pkts made the total size exceed path MTU in the network. Fix was to reduce container MTU to a much lower value than path MTU. Learnt this the hard way.

**Comment by anthonyvk** [comment]
> 
> 
> The problem was because TLS pkts are huge and the overlay Vxlan pkts made the total size exceed path MTU in the network. Fix was to reduce container MTU to a much lower value than path MTU. Learnt this the hard way.

@gautvenk , can you let us know how did you perform that?

**Comment by gautvenk** [comment]
> > The problem was because TLS pkts are huge and the overlay Vxlan pkts made the total size exceed path MTU in the network. Fix was to reduce container MTU to a much lower value than path MTU. Learnt this the hard way.
> 
> @gautvenk , can you let us know how did you perform that?

@anthonyvk MTU setting will be CNI specific. Either you can do at a POD level or enable path MTU if the CNI supports it.

**Comment by anthonyvk** [comment]
@gautvenk  Hi gautvenk , Thanks for responding.
We are using calico controller. We increased the MTU value to 8000, we are still seeing the issue.
Any inputs from your end?

**Comment by anthonyvk** [comment]
> Either you can do at a POD level

Would be great if you can forward me instructions on how to do it. Thanks.
