### ISSUE TITLE
Update Istio Helm charts to enable Helm adoption of existing resources

### ISSUE THREAD

**Issue by rodalli** [istio/istio#25992]
**Describe the feature request**

Several Istio users that I work with, including myself, still use Helm to manage Istio deployments. A frequent problem that we run into after failed installations is Helm complaining about resources that already exist and refusing to adopt or overwrite them (understandably). There can be a lot of root causes...maybe something is wrong in a values file, or you forgot to set an option that you wanted/used the wrong values file. Maybe because of it, one component didn't come up healthy, so the Helm install errored out and is in a "failed" status.

In this case, you would just want to correct your values file and do another install over the top of the failed one to fix it. Now, because Helm doesn't adopt those failed resources, you may have orphans. You now have to completely uninstall everything and try again, or delete the offending resources one by one if you can't uninstall completely.

This has always been an issue with Helm in general with being unable to adopt resources. Well, Helm 3 finally fixed it using a certain set of annotations and labels in the deployed resources. See here: https://github.com/helm/helm/pull/7649. It doesn't work with hook resources at the moment (likely a bug/oversight), but seems to work well for everything else.

Adding these annotations/labels to Istio's Helm charts to allow Helm to adopt resources left behind by failed (and other) deployments would be beneficial to us, and make the deployment/upgrade experience much smoother for users.

**Describe alternatives you've considered**

Adding hooks and hook-delete-policies to all resources, but this is something users would have to do after the fact in their own fork of Istio. This is also something that would be better implemented within the Istio project itself, rather than users having to edit and maintain their own charts. I believe the requested solution leveraging the new Helm functionality is more elegant.

[X] Configuration Infrastructure
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
@nrjpoddar can you take a look?

**Comment by esnible** [comment]
@nrjpoddar Shall we retarget this to 1.9?

**Comment by nrjpoddar** [comment]
yes, let me assign it to @jacob-delgado so he has this in his sight. Not sure if this becomes a blocker for promotion but he can evaluate that too.
