### ISSUE TITLE
TestRerun test flake

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#25995]
https://prow.istio.io/view/gs/istio-prow/logs/unit-tests_istio_postsubmit/3214

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gs/istio-prow/logs/unit-tests_istio_postsubmit/3218

**Comment by stevenctl** [comment]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/26015/unit-tests_istio/17877

**Comment by adiprerepa** [comment]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/26001/unit-tests_istio/17883
