### ISSUE TITLE
The pod istio-cni not do well in openshift .

### ISSUE THREAD

**Issue by pantianying** [istio/istio#26002]
openshift 4.5
k8s version 1.18
istio 1.6.6
![image](https://user-images.githubusercontent.com/20589945/89010287-dd286080-d340-11ea-93eb-46240d4e2a48.png)

**Bug description**
When I installed isto in opensfit, due to a permission problem. Isto CNI must be installed. According to the installation method on the official website, when starting the pod of isto CNI node, an error is reported as follows:
`WARNING: Configured CNI config file "/host/etc/cni/net.d/istio-cni.conf" preempted by "10-canal.conflist".`
The screenshot is as follows
![image](https://user-images.githubusercontent.com/20589945/89010576-72c3f000-d341-11ea-8faa-caa62de18ed5.png)
Our openshift uses canal as the CNI of k8s.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[X] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**How was Istio installed?**
use istioctl install

this is my cni-annotations.yaml file:

![image](https://user-images.githubusercontent.com/20589945/89011581-2aa5cd00-d343-11ea-961c-74ef8428b0ba.png)

Different from the official website, here I changed cniconfdir to the directory in our actual machine. I also want to know why the configuration directory on the official website is inconsistent with my actual situation.

can somebody tell me how to fix it .😭

**Comment by pantianying** [comment]
should I delete 10-canal.conflist ?

**Comment by morvencao** [comment]
@pantianying What's your environment's `--cni-conf-dir` setting, I mean the args for the kubelet. It should be same to that one, or kubelet will not pick up the istio-cni configuration.

**Comment by pantianying** [comment]
> --cni-conf-dir

my --cni-conf-dir is /var/run/multus/cni/net.d,but when i  configure  --cni-conf-dir=/var/run/multus/cni/net.d,it show that 
`(combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_details-v1-558b8b4b76-2xjtm_istio-project_093943e2-27fe-4504-9a2e-c6f82fe3a599_0(92ff94202f401de64962f35005a2cdce89caa7df952250cf48eb4e2b525d6e96): Multus: [istio-project/details-v1-558b8b4b76-2xjtm]: error loading k8s delegates k8s args: TryLoadPodDelegates: error in getting k8s network for pod: GetNetworkDelegates: failed getting the delegate: GetCNIConfig: err in GetCNIConfigFromFile: No networks found in /etc/cni/multus/net.d`

**Comment by pantianying** [comment]
it seem that my kubelet find  istio-cni configuration in /etc/cni/multus/net.d,find ZZZ-istio-cni-kubeconfig in /var/run/multus/cni/net.d.but my istio-cni-node  will only put both in the same directory（/etc/cni/multus/net.d or /var/run/multus/cni/net.d）。

**Comment by morvencao** [comment]
Why does kubelet still try to find istio-cni conf in `/etc/cni/multus/net.d` when you set `--cni-conf-dir=/var/run/multus/cni/net.d`? can you try to find if the cni pod mount the host dir(`/var/run/multus/cni/net.d`) correctly.

**Comment by pantianying** [comment]
> Why does kubelet still try to find istio-cni conf in `/etc/cni/multus/net.d` when you set `--cni-conf-dir=/var/run/multus/cni/net.d`? can you try to find if the cni pod mount the host dir(`/var/run/multus/cni/net.d`) correctly.

This is also my doubts, as if '-- CNI conf dir = / var / run / Multus / CNI / net. D' doesn't work
this is my daemonSet of istio-cni-node 

kind: DaemonSet
apiVersion: apps/v1
metadata:
  annotations:
    deprecated.daemonset.template.generation: '24'
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"apps/v1","kind":"DaemonSet","metadata":{"annotations":{},"labels":{"install.operator.istio.io/owning-resource":"installed-state","install.operator.istio.io/owning-resource-namespace":"istio-system","k8s-app":"istio-cni-node","operator.istio.io/component":"Cni","operator.istio.io/managed":"Reconcile","operator.istio.io/version":"1.6.6","release":"istio"},"name":"istio-cni-node","namespace":"kube-system"},"spec":{"selector":{"matchLabels":{"k8s-app":"istio-cni-node"}},"template":{"metadata":{"annotations":{"scheduler.alpha.kubernetes.io/critical-pod":""},"labels":{"k8s-app":"istio-cni-node"}},"spec":{"containers":[{"command":["/install-cni.sh"],"env":[{"name":"CNI_CONF_NAME","value":"istio-cni.conf"},{"name":"CNI_NETWORK_CONFIG","valueFrom":{"configMapKeyRef":{"key":"cni_network_config","name":"istio-cni-config"}}},{"name":"CNI_NET_DIR","value":"/var/run/multus/cni/net.d"},{"name":"CHAINED_CNI_PLUGIN","value":"false"}],"image":"docker.io/istio/install-cni:1.6.6","imagePullPolicy":"Always","name":"install-cni","volumeMounts":[{"mountPath":"/host/opt/cni/bin","name":"cni-bin-dir"},{"mountPath":"/host/etc/cni/net.d","name":"cni-net-dir"}]},{"command":["/opt/cni/bin/istio-cni-repair"],"env":[{"name":"REPAIR_NODE-NAME","valueFrom":{"fieldRef":{"fieldPath":"spec.nodeName"}}},{"name":"REPAIR_LABEL-PODS","value":"true"},{"name":"REPAIR_DELETE-PODS","value":"false"},{"name":"REPAIR_RUN-AS-DAEMON","value":"true"},{"name":"REPAIR_SIDECAR-ANNOTATION","value":"sidecar.istio.io/status"},{"name":"REPAIR_INIT-CONTAINER-NAME","value":"istio-validation"},{"name":"REPAIR_BROKEN-POD-LABEL-KEY","value":"cni.istio.io/uninitialized"},{"name":"REPAIR_BROKEN-POD-LABEL-VALUE","value":"true"}],"image":"docker.io/istio/install-cni:1.6.6","imagePullPolicy":"Always","name":"repair-cni"}],"hostNetwork":true,"nodeSelector":{"beta.kubernetes.io/os":"linux"},"priorityClassName":"system-cluster-critical","serviceAccountName":"istio-cni","terminationGracePeriodSeconds":5,"tolerations":[{"effect":"NoSchedule","operator":"Exists"},{"key":"CriticalAddonsOnly","operator":"Exists"},{"effect":"NoExecute","operator":"Exists"}],"volumes":[{"hostPath":{"path":"/var/lib/cni/bin"},"name":"cni-bin-dir"},{"hostPath":{"path":"/var/run/multus/cni/net.d"},"name":"cni-net-dir"}]}},"updateStrategy":{"rollingUpdate":{"maxUnavailable":1},"type":"RollingUpdate"}}}
  selfLink: /apis/apps/v1/namespaces/kube-system/daemonsets/istio-cni-node
  resourceVersion: '5539850'
  name: istio-cni-node
  uid: 49ca410b-3761-43aa-84db-bc1296fcd1d9
  creationTimestamp: '2020-07-31T09:00:18Z'
  generation: 24
  managedFields:
    - manager: istioctl
      operation: Update
      apiVersion: apps/v1
      time: '2020-08-03T08:28:23Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:deprecated.daemonset.template.generation': {}
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
          'f:labels':
            .: {}
            'f:install.operator.istio.io/owning-resource': {}
            'f:install.operator.istio.io/owning-resource-namespace': {}
            'f:k8s-app': {}
            'f:operator.istio.io/component': {}
            'f:operator.istio.io/managed': {}
            'f:operator.istio.io/version': {}
            'f:release': {}
        'f:spec':
          'f:revisionHistoryLimit': {}
          'f:selector':
            'f:matchLabels':
              .: {}
              'f:k8s-app': {}
          'f:template':
            'f:metadata':
              'f:annotations':
                .: {}
                'f:scheduler.alpha.kubernetes.io/critical-pod': {}
              'f:labels':
                .: {}
                'f:k8s-app': {}
            'f:spec':
              'f:volumes':
                .: {}
                'k:{"name":"cni-bin-dir"}':
                  .: {}
                  'f:hostPath':
                    .: {}
                    'f:path': {}
                    'f:type': {}
                  'f:name': {}
                'k:{"name":"cni-net-dir"}':
                  .: {}
                  'f:hostPath':
                    .: {}
                    'f:path': {}
                    'f:type': {}
                  'f:name': {}
              'f:containers':
                'k:{"name":"install-cni"}':
                  'f:image': {}
                  'f:volumeMounts':
                    .: {}
                    'k:{"mountPath":"/host/etc/cni/net.d"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                    'k:{"mountPath":"/host/opt/cni/bin"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                  'f:terminationMessagePolicy': {}
                  .: {}
                  'f:resources': {}
                  'f:command': {}
                  'f:env':
                    .: {}
                    'k:{"name":"CHAINED_CNI_PLUGIN"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"CNI_CONF_NAME"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"CNI_NETWORK_CONFIG"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:configMapKeyRef':
                          .: {}
                          'f:key': {}
                          'f:name': {}
                    'k:{"name":"CNI_NET_DIR"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                  'f:terminationMessagePath': {}
                  'f:imagePullPolicy': {}
                  'f:name': {}
                'k:{"name":"repair-cni"}':
                  'f:image': {}
                  'f:terminationMessagePolicy': {}
                  .: {}
                  'f:resources': {}
                  'f:command': {}
                  'f:env':
                    'k:{"name":"REPAIR_DELETE-PODS"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"REPAIR_SIDECAR-ANNOTATION"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"REPAIR_INIT-CONTAINER-NAME"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"REPAIR_NODE-NAME"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:fieldRef':
                          .: {}
                          'f:apiVersion': {}
                          'f:fieldPath': {}
                    'k:{"name":"REPAIR_BROKEN-POD-LABEL-KEY"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"REPAIR_LABEL-PODS"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    .: {}
                    'k:{"name":"REPAIR_RUN-AS-DAEMON"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"REPAIR_BROKEN-POD-LABEL-VALUE"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                  'f:terminationMessagePath': {}
                  'f:imagePullPolicy': {}
                  'f:name': {}
              'f:dnsPolicy': {}
              'f:tolerations': {}
              'f:priorityClassName': {}
              'f:serviceAccount': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:hostNetwork': {}
              'f:nodeSelector':
                .: {}
                'f:beta.kubernetes.io/os': {}
              'f:terminationGracePeriodSeconds': {}
              'f:serviceAccountName': {}
              'f:securityContext': {}
          'f:updateStrategy':
            'f:rollingUpdate':
              .: {}
              'f:maxUnavailable': {}
            'f:type': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2020-08-03T08:30:14Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:currentNumberScheduled': {}
          'f:desiredNumberScheduled': {}
          'f:numberAvailable': {}
          'f:numberReady': {}
          'f:observedGeneration': {}
          'f:updatedNumberScheduled': {}
  namespace: kube-system
  labels:
    install.operator.istio.io/owning-resource: installed-state
    install.operator.istio.io/owning-resource-namespace: istio-system
    k8s-app: istio-cni-node
    operator.istio.io/component: Cni
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.6.6
    release: istio
spec:
  selector:
    matchLabels:
      k8s-app: istio-cni-node
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: istio-cni-node
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
      restartPolicy: Always
      serviceAccountName: istio-cni
      schedulerName: default-scheduler
      hostNetwork: true
      terminationGracePeriodSeconds: 5
      securityContext: {}
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: install-cni
          command:
            - /install-cni.sh
          env:
            - name: CNI_CONF_NAME
              value: istio-cni.conf
            - name: CNI_NETWORK_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: istio-cni-config
                  key: cni_network_config
            - name: CNI_NET_DIR
              value: /var/run/multus/cni/net.d
            - name: CHAINED_CNI_PLUGIN
              value: 'false'
          imagePullPolicy: Always
          volumeMounts:
            - name: cni-bin-dir
              mountPath: /host/opt/cni/bin
            - name: cni-net-dir
              mountPath: /host/etc/cni/net.d
          terminationMessagePolicy: File
          image: 'docker.io/istio/install-cni:1.6.6'
        - name: repair-cni
          image: 'docker.io/istio/install-cni:1.6.6'
          command:
            - /opt/cni/bin/istio-cni-repair
          env:
            - name: REPAIR_NODE-NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: REPAIR_LABEL-PODS
              value: 'true'
            - name: REPAIR_DELETE-PODS
              value: 'false'
            - name: REPAIR_RUN-AS-DAEMON
              value: 'true'
            - name: REPAIR_SIDECAR-ANNOTATION
              value: sidecar.istio.io/status
            - name: REPAIR_INIT-CONTAINER-NAME
              value: istio-validation
            - name: REPAIR_BROKEN-POD-LABEL-KEY
              value: cni.istio.io/uninitialized
            - name: REPAIR_BROKEN-POD-LABEL-VALUE
              value: 'true'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      serviceAccount: istio-cni
      volumes:
        - name: cni-bin-dir
          hostPath:
            path: /var/lib/cni/bin
            type: ''
        - name: cni-net-dir
          hostPath:
            path: /var/run/multus/cni/net.d
            type: ''
      dnsPolicy: ClusterFirst
      tolerations:
        - operator: Exists
          effect: NoSchedule
        - key: CriticalAddonsOnly
          operator: Exists
        - operator: Exists
          effect: NoExecute
      priorityClassName: system-cluster-critical
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  revisionHistoryLimit: 10
status:
  currentNumberScheduled: 5
  numberMisscheduled: 0
  desiredNumberScheduled: 5
  numberReady: 5
  observedGeneration: 24
  updatedNumberScheduled: 5
  numberAvailable: 5

**Comment by pantianying** [comment]
thk for your reply， I've reloaded istio , now there are a new problem 😂😂

![image](https://user-images.githubusercontent.com/20589945/89182458-58e80e80-d5c8-11ea-977d-486a9ffd8f4b.png)

Boss, are you familiar with this ~~ @morvencao

**Comment by pantianying** [comment]
It seem that my problem has been solved. It seems to be caused by the previous isto installation failure and not deleting all the files on the machine. Do istio have any specific steps to uninstall isto CNI

**Comment by morvencao** [comment]
Great to you resolve that.

For the istio-cni uninstall, it should just remove corresponding yaml manifests.
Are you saying that the istio-cni binary and configuration are leaked into the host nodes after uninstall? If yes, this should be an issue.

**Comment by alonsocamaro** [comment]
> It seems to be caused by the previous isto installation failure and not deleting all the files on the machine. Do istio have any specific steps to uninstall isto CNI

Can you please elaborate?

**Comment by christianh814** [comment]
I'm also experiencing this problem on a brand new install
