### ISSUE TITLE
redis-cli erroneously connecting with istio sidecar

### ISSUE THREAD

**Issue by ceastman-ibm** [istio/istio#26007]
**Bug description**
/redis # redis-cli -h 8.8.8.8 -p 6379 PING
PONG
/redis # 

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
to receive an error that the connection was refused

the following was done on a microservice without a side car:
/redis # redis-cli -h 172.30.31.243 -p 6379 PING
PONG
/redis # redis-cli -h 172.30.31.242 -p 6379 PING
Could not connect to Redis at 172.30.31.242:6379: Connection refused

.243 has a running redis server
.242 doesn't exist

**Steps to reproduce the bug**
Install redis-cli - apt-get install redis-tools

/redis # redis-cli -h <<any ip address>> -p 6379 PING
PONG

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
client version: 1.6.5
control plane version: 1.6.5
data plane version: 1.6.5 (548 proxies)

Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.7", GitCommit:"b4455102ef392bf7d594ef96b97a4caa79d729d9", GitTreeState:"clean", BuildDate:"2020-06-17T11:39:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9+IKS", GitCommit:"dbe4e8a5c169e0a6a8a9b7b183561fa61e161985", GitTreeState:"clean", BuildDate:"2020-07-16T01:30:57Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
IBM managed istio addon

**Environment where bug was observed (cloud vendor, OS, etc)**
IBM

**Comment by ceastman-ibm** [comment]
This looks to be related to my service entry for redis:
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.istio.io/v1beta1","kind":"ServiceEntry","metadata":{"annotations":{},"name":"redis","namespace":"ondeck"},"spec":{"hosts":["redis.redis.svc.cluster.local","redis-0.redis.redis.svc.cluster.local","redis-1.redis.redis.svc.cluster.local","redis-2.redis.redis.svc.cluster.local"],"location":"MESH_INTERNAL","ports":[{"name":"redis-server","number":6379,"protocol":"REDIS"},{"name":"redis-sentinel","number":26379,"protocol":"REDIS"}],"resolution":"NONE"}}
  creationTimestamp: "2020-07-30T15:39:31Z"
  generation: 1
  name: redis
  namespace: ondeck
  resourceVersion: "64384775"
  selfLink: /apis/networking.istio.io/v1beta1/namespaces/ondeck/serviceentries/redis
  uid: 900b3684-31df-4dc5-9d5b-e9a131c1606e
spec:
  hosts:
  - redis.redis.svc.cluster.local
  - redis-0.redis.redis.svc.cluster.local
  - redis-1.redis.redis.svc.cluster.local
  - redis-2.redis.redis.svc.cluster.local
  location: MESH_INTERNAL
  ports:
  - name: redis-server
    number: 6379
    protocol: REDIS
  - name: redis-sentinel
    number: 26379
    protocol: REDIS
  resolution: NONE

I tried switching resolution to DNS but the same erroneous behavior happens. when i delete the service entry the redis-cli appears to work correctly (fails to connect to non existent hosts)

**Comment by howardjohn** [comment]
Please post config dump and access logs: https://github.com/istio/istio/wiki/Troubleshooting-Istio

**Comment by ceastman-ibm** [comment]
[redis-0-config-dump.gz](https://github.com/istio/istio/files/5024329/redis-0-config-dump.gz)
[redis-0-proxy-log.gz](https://github.com/istio/istio/files/5024330/redis-0-proxy-log.gz)

**Comment by howardjohn** [comment]
```
$ ik pc l --file redis-0-config-dump --port 6379
ADDRESS      PORT MATCH DESTINATION
0.0.0.0      6379 ALL   Non-HTTP/Non-TCP
172.21.21.60 6379 ALL   Non-HTTP/Non-TCP
```

There is a route matching all traffic going to `redis.redis.svc.cluster.local`

This is likely because of your service entry. a ServiceEnrty without a VIP (specified in address) will listen on 0.0.0.0 and match all traffic. I think this is working as expected.
