### ISSUE TITLE
Istio Operator deploys istio-cni-node pods without privileged permissions

### ISSUE THREAD

**Issue by rhrazdil** [istio/istio#26003]
**Bug description**
When installing Istio by following the Standalone Operator install flow, the `istio-cni-node` DaemonSet specifies two containers:
 `install-cni` and `repair-cni`.
The `install-cni` container don't have specified serviceAccount, but the `/install-cni.sh` which the `install-cni` container runs requires privileged permissions.

Without privileged permissions, the `install-cni` fails with:
```
$ kubectl logs istio-cni-node-fnkmg -n istio-system -c install-cni
/host/opt/cni/bin is non-writable, skipping
/host/secondary-bin-dir is non-writable, skipping
Cleaning up and exiting.
Removing istio-cni config from CNI chain config in /host/etc/cni/net.d/10-calico.conflist
/install-cni.sh: line 185: /host/etc/cni/net.d/istio-cni.conf.tmp: Permission denied
/install-cni.sh: line 108: /host/etc/cni/net.d/10-calico.conflist: Permission denied
```

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[x ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
`install-cni` should run with privileged permissions.
Or it should use a distinct serviceAccount and it should be documented that users may need to provide pod security policy allowing privileged.
It shouldn't be using the default serviceAccount.

**Steps to reproduce the bug**
```
$ istioctl operator init
$ kubectl create ns istio-system
$ kubectl apply -f - <<EOF
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: example-istiocontrolplane
spec:
  components:
    cni:
      enabled: true
  profile: demo
  values:
    cni:
      chained: true
      cniBinDir: /opt/cni/bin
      cniConfDir: /etc/cni/net.d
      cniConfFileName: 10-calico.conflist
      excludeNamespaces:
      - istio-system
      - kube-system
      logLevel: info
    sidecarInjectorWebhook:
      injectedAnnotations:
        k8s.v1.cni.cncf.io/networks: istio-cni
EOF

```
**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

client version: 1.6.5
control plane version: 1.6.5
data plane version: 1.6.5 (3 proxies)

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
Standalone Operator
**Environment where bug was observed (cloud vendor, OS, etc)**
Docker
CentOS Linux release 8.1.1911 (Core) 

[istio-dump.tar.gz](https://github.com/istio/istio/files/5005639/istio-dump.tar.gz)

**Comment by morvencao** [comment]
istio-cni doesn't use `default` serviceaccount, it uses `istio-cni` serviceaccount, see: https://github.com/istio/istio/blob/1.6.5/operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-cni/templates/daemonset.yaml#L47

**Comment by rhrazdil** [comment]
@morvencao Hello, thanks for your response. Indeed, I misread the yaml, I thought that the `istio-cni` serviceaccount is only used by the `repair-cni`. Thanks!

My question is then, shouldn't there be a podSecurityPolicy created by the IstioOperator for the `istio-cni` serviceaccout that allows privileged?
Or shouldn't the daemonset have:
```
securityContext:
            privileged: true
```

I'm new to istio, so please, correct me if I'm missing something obvious.

**Comment by morvencao** [comment]
@rhrazdil Yes, there is one psp, see: https://github.com/istio/istio/blob/1.6.5/operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-cni/templates/clusterrolebinding.yaml#L35

**Comment by rhrazdil** [comment]
Interesting, I don't have this rolebinding created 
```
$ kubectl get rolebinding -A | grep istio
istio-system             istio-ingressgateway-sds                            Role/istio-ingressgateway-sds                         20h
```

**Comment by rhrazdil** [comment]
@morvencao Could the IstioOperator be missing creating this resource?

**Comment by morvencao** [comment]
By default it is disabled. Try:
```
$ cat <<EOF > istio-cni.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    cni:
      enabled: true
  values:
    cni:
      psp_cluster_role: enabled
      excludeNamespaces:
       - istio-system
       - kube-system
      logLevel: info
EOF
$ istioctl install -f istio-cni.yaml
```

**Comment by rhrazdil** [comment]
Hello, Thanks for the example. Indeed specifying the `psp_cluster_role` with a non empty value creates a roleBinding. It's worth mentioning that the value is used to point to a clusterRole.

Unfortunately, this didn't solve the issue. I may have mislead you but mentiong the missing PodSecurityPolicy, because I didn't understand the concept correctly. I thought that adding clusterRole or podSecurityPolicy would grant the istio-cni-node pods the `privileged` permission, but that is apparently not the case.

So I'm still not sure if there is a way to run the istio-cni-node pods as privileged without manually editing the daemonset
