### ISSUE TITLE
Ingress Canary: Canary controlplane install upgrades ingress in-place

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#26019]
Installing a new istio revision changes the ingress proxy in-place.
It changes the most externally visible component right away, while the documentation and expectation is that the the canary controlplane upgrade is safe and it will just sit there until called upon to do something.
This should be fixed.

Before canary
```bash 
$ kubectl --namespace istio-system get pods
NAME                                    READY   STATUS    RESTARTS   AGE
grafana-bf459c987-qnxgl                 1/1     Running   0          10d
istio-egressgateway-6d8d678547-4zkn5    1/1     Running   0          7d2h
istio-ingressgateway-6d7fd949df-5hhvf   1/1     Running   0          6d23h
istiod-5c7d7864b7-8x9kl                 1/1     Running   0          7d2h
kiali-operator-77dc5699ff-whpzf         1/1     Running   0          10d
prometheus-67d4f9f4cd-5cq74             2/2     Running   0          10d
```
Canary install

```bash
$ ./istioctl-1.8-alpha.79957a364a7dfcf65e4637809b7ec6d03e489b37 install --set revision=canary
✔ Istio core installed
✔ Istiod installed
✔ Ingress gateways installed
✔ Installation complete
```

Updates to ingress
```bash
$ kubectl --namespace istio-system get pods
NAME                                    READY   STATUS        RESTARTS   AGE
grafana-bf459c987-qnxgl                 1/1     Running       0          10d
istio-egressgateway-6d8d678547-4zkn5    1/1     Running       0          7d2h
istio-ingressgateway-6c6c8d748c-wqq6j   1/1     Running       0          19s
istio-ingressgateway-6d7fd949df-5hhvf   0/1     Terminating   0          6d23h
istiod-5c7d7864b7-8x9kl                 1/1     Running       0          7d2h
istiod-canary-6c7ddbcdd-k4574           1/1     Running       0          29s
kiali-operator-77dc5699ff-whpzf         1/1     Running       0          10d
prometheus-67d4f9f4cd-5cq74             2/2     Running       0          10d
```

@louiscryan @costinm

**Comment by yan-dblinf** [comment]
@mandarjog I encountered the exact same case when upgrading istio from 1.5 to 1.6. Moreover, we have multiple ingress gateways running in namespaces other than istio-system, which is also rolling-updated to use `docker.io/istio/proxyv2:1.6.8` at once during the canary upgrade; however, the xds-grpc server it's connecting to is still the old istiod service. 

The main incompatibility of canary upgrade and customized iggw is that canary upgrade will rolling-update iggw deployment with a new config that asks the iggw pod to load the canary xds-grpc server URL from configmap istio-1-6-0. This mechanism works on istio-ingressgateway (the default built-in iggw) as it’s running in istio-system namespace, where the configmap exists. But as our customized iggws are running in app namespace(s), it will access the old istiod as the indicated configmap is not accessible. 

+ @esnible @howardjohn

**Comment by ostromart** [comment]
This is a documentation issue, tracked here: https://github.com/istio/istio/issues/27511
