### ISSUE TITLE
Error loading config file "/etc/istio/config/kubeconfig"

### ISSUE THREAD

**Issue by meelody** [istio/istio#2602]
I did it according to this document. https://istio.io/docs/setup/consul/quick-start.html.
I have a mistake.

 istio/pilot:0.4.0 state is Exited when I type in the 'docker ps -a' command.

The log display error is as follows:
failed to create discovery service: failed to connect to Kubernetes API. Error loading config file "/etc/istio/config/kubeconfig": read /etc/istio/config/kubeconfig: is a directory.

Expect solutions.

**Comment by lzyowen** [comment]
Hi @NeGnail i met same issue with you ,did you fixed it ?

**Comment by GregHanson** [comment]
@lzyowen This issue can be resolved by switching to the most recent version of istio (0.5.1 or later) by following the steps here: https://istio.io/docs/setup/kubernetes/quick-start.html OR by creating the kubeconfig file https://github.com/istio/istio/blob/master/install/consul/kubeconfig in install/consul or install/eureka depending on your setup.

**Comment by anastayaa** [comment]
I have the same error here, is there any solution?
