### ISSUE TITLE
Ingress gateway with custom revision cannot connect to pilot

### ISSUE THREAD

**Issue by githubrotem** [istio/istio#26041]
**Bug description**
I
Istio version: 1.6.5

When installing Istio with a revision (lets say prod), and installing ingress gateway on a separated CR with the same revision, the ingress gateway cannot contact pilot.

In the logs we see: **Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?)**

When checking "kubectl describe pod ingressgateway" I can see the the revision is added to some parts, however the  **xds-grpc and discoveryAddress**  are pointing to istiod service **without the added revision in the address.**

Please advise  

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

ingress gateway will contact the correct pilot in the revision

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

1.6.5

**How was Istio installed?**
istioctl 
**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
Can you give more info on how you installed, the logs of the pod and kubectl describe?

**Comment by howardjohn** [comment]
Any more info?

**Comment by mfmbarros** [comment]
Did you find out what was the root cause? I have the same issue
