### ISSUE TITLE
istio/proxy_init:0.4.0 , iptables: Chain already exists 

### ISSUE THREAD

**Issue by NeGnail** [istio/istio#2605]
I did it according to this document. https://istio.io/docs/setup/consul/quick-start.html.
I have a mistake.

istio/proxy_init:0.4.0 status is "Exited",when I type in the 'docker ps -a' command.
This shows "iptables: Chain already exists." when I type in the 'docker logs' command.

How should I solve this problem?

**Comment by cmluciano** [comment]
@istio/proxy-hackers

**Comment by GregHanson** [comment]
@NeGnail the behavior of the init container is to run once - it creates an iptables rule and then exits.  Restarting the container multiple time will result in the `Chain already exists` error message.  If you were experiencing another problem and attempting to debug, I recommend moving to istio version 0.5.1 or later as this fixes two known problems in the consul example.  Steps to fix both are addressed here: https://github.com/istio/istio/issues/2433
