### ISSUE TITLE
When will the AMPQ be supported?

### ISSUE THREAD

**Issue by xutsing** [istio/istio#26056]
HI,

I think it is a big gift for our developers using micro services architecture.  but I have a feature request below.

When will the AMPQ be supported in istio?

Thanks a lot.

Best

**Comment by howardjohn** [comment]
What specifically are you looking for? Istio supports all TCP based protocols, which AFAIK AMPQ is based on TCP?

**Comment by xutsing** [comment]
I mean if the message passed by the mq can be catched by the Istio.  Thanks a lot

**Comment by howardjohn** [comment]
What do you want to do when istio catches them? Telemetry? Routing? apply policies?

**Comment by xutsing** [comment]
Sorry, I did not make my question clear above.
Telemetry is my point.
