### ISSUE TITLE
DNS filter's inline dns table may be too huge

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#26055]
https://github.com/istio/istio/blob/84c1a1d359abcd651ebbba29dc89773cf6607ef3/pilot/pkg/networking/core/v1alpha3/dns_listener.go#L101

Now we generate the dns table for every service, and then it is pushed to each proxy, I am concerned this is less efficient and may exceed the max grpc message(have no proof now).

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by hzxuzhonghu** [comment]
cc @rshriram

**Comment by howardjohn** [comment]
I don't think there is a max gRPC message size. Btw, we already push a cluster for every service, dns is only 2x that at most, its not n^2 or anything

**Comment by hzxuzhonghu** [comment]
It is 3*N, but N can be very large(65535). And it is in dns filter, which then makes lds response very huge. 

>I don't think there is a max gRPC message size.

Isn't there a 4MB limit by default?

**Comment by howardjohn** [comment]
that max grpc size was self imposed on mcp, not impacted on xds connection

**Comment by hzxuzhonghu** [comment]
https://godoc.org/google.golang.org/grpc#MaxRecvMsgSize

```
MaxRecvMsgSize returns a ServerOption to set the max message size in bytes the server can receive. If this is not set, gRPC uses the default 4MB.
```

What does this mean?

**Comment by hzxuzhonghu** [comment]
NVM, this is the server side option

**Comment by hzxuzhonghu** [comment]
@ramaraochavali Can you confirm if envoy side config the MaxCallRecvMsgSize

**Comment by howardjohn** [comment]
I am not certain but I think it's unlimited. It's definitely way more than 4mb,I have seen much larger responses

**Comment by ramaraochavali** [comment]
I think there is no max message size enforced. I have also seen messages way more than 4 MB

**Comment by hzxuzhonghu** [comment]
It should be unlimited.

**Comment by rshriram** [comment]
Also remember that there will be N entries, one for each service. and most services will have ONLY ONE IP. Headless services will have m IPs where m == num pods of headless. Thats all there is in the DNS table, compared to a listener that has lot more configs. 

Now, if N is 65535, we are talking about 64K k8s services.. Wont we have other problems here ? lds/cds/rds responses will be huge no matter what in this case.

**Comment by howardjohn** [comment]
I don't think we have seen issues with this, as Shriram said its far small than clusters. Should we close?

**Comment by hzxuzhonghu** [comment]
Reopen when we find issues
