### ISSUE TITLE
gateways.istio-ingressgateway.autoscaleMin/autoscaleMax ignored while installing.

### ISSUE THREAD

**Issue by sanigo** [istio/istio#26051]
I am trying to set the minimum instances of istio-ingressgateway, but the autoscaleMin is ignored even if the autoscaleEnabled is true.
The minReplicas is alway 1.

The istio version is 1.6.7

**Comment by esnible** [comment]
Could this be a duplicate of https://github.com/istio/istio/issues/22192 ?

**Comment by sanigo** [comment]
Yes , the same as #22192.
