### ISSUE TITLE
TestController_ExternalNameService flake

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#26063]
https://testgrid.k8s.io/istio_istio#unit-tests_istio

https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/26061/unit-tests_istio/17984

**Comment by howardjohn** [comment]
`8363 runs so far, 0 failures` running locally, seems very very rare

**Comment by howardjohn** [comment]
Actually got one, takes a while due to test timeout. Fails here: https://github.com/istio/istio/blob/d049debcf2cec6861d552fe70ee980affcb98738/pilot/pkg/serviceregistry/kube/controller/controller_test.go#L1285

**Comment by hzxuzhonghu** [comment]
Yeah, the ci failed here too.

**Comment by hzxuzhonghu** [comment]
I think this should be fixed, no failure now
