### ISSUE TITLE
Filter Chain Match Trie logic leads to unexpected matches leading to various bugs

### ISSUE THREAD

**Issue by tariq1890** [istio/istio#26079]
**Bug description**

We find that Istio seems to cause outbound HTTPS traffic issues in some of our Kubernetes clusters.  For eg:- We have an application that makes HTTPS calls to the NewRelic and AWS API. The behaviour is inconsistent in that the outbound HTTPS call works in some of our Kubernetes clusters. We are trying to understand what the root cause is. 

In an effort to find the root cause, we are trying to compare the istio proxy configs from Kubernetes clusters that have and don't have this issue. Since the istio-proxy config dumps are huge JSONs. we request help to narrow down on the relevant JSON fields/structs for configuring outbound HTTPS requests.

```
 time="2020-07-30T23:11:49Z" level=error msg="RequestError: send request failed\ncaused by: Get \"https://route53.amazonaws.com/2013-04-01/hostedzone\": http: server gave HTTP response to HTTPS client"    
```

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

Just inject istio-proxy to these pods that make outbound HTTPS calls

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

v1.6.3

**How was Istio installed?**

Helm

**Environment where bug was observed (cloud vendor, OS, etc)**

AWS

**Comment by tariq1890** [comment]
It would be helpful to understand what in envoy is causing the HTTPS outbound request to be intercepted and forwarded as an HTTP call to the server.

I've done a fair bit of reading on this. From my understanding, we have `ALLOW_ANY` as the mode and it creates 'PassthroughClusters' which is supposed to forward the outgoing HTTPS requests directly. I have verified that the envoy proxy config has `PassthroughClusters` configured but it still fails.

**Comment by tariq1890** [comment]
I have enabled trace logs and access Logs. Strangely, an access log is never created for the outbound https call to `collector.newrelic.com`

```
2020-08-06T04:19:34.972583Z	debug	envoy filter	[external/envoy/source/extensions/filters/listener/original_dst/original_dst.cc:18] original_dst: New connection accepted
2020-08-06T04:19:34.972671Z	debug	envoy filter	[external/envoy/source/extensions/filters/listener/tls_inspector/tls_inspector.cc:78] tls inspector: new connection accepted
2020-08-06T04:19:34.972682Z	trace	envoy filter	[external/envoy/source/extensions/filters/listener/tls_inspector/tls_inspector.cc:171] tls inspector: recv: -1
2020-08-06T04:19:34.972740Z	trace	envoy filter	[external/envoy/source/extensions/filters/listener/tls_inspector/tls_inspector.cc:171] tls inspector: recv: 292
2020-08-06T04:19:34.972771Z	debug	envoy filter	[external/envoy/source/extensions/filters/listener/tls_inspector/tls_inspector.cc:148] tls:onServerName(), requestedServerName: collector.newrelic.com
2020-08-06T04:19:34.972782Z	trace	envoy filter	[external/envoy/source/extensions/filters/listener/tls_inspector/tls_inspector.cc:192] tls inspector: done: true
2020-08-06T04:19:34.972788Z	debug	envoy filter	[external/envoy/source/extensions/filters/listener/http_inspector/http_inspector.cc:37] http inspector: new connection accepted
2020-08-06T04:19:34.972795Z	trace	envoy filter	[external/envoy/source/extensions/filters/listener/http_inspector/http_inspector.cc:45] http inspector: cannot inspect http protocol with transport socket tls
2020-08-06T04:19:34.972842Z	debug	envoy conn_handler	[external/envoy/source/server/connection_handler_impl.cc:411] [C14] new connection
2020-08-06T04:19:34.972852Z	trace	envoy main	[external/envoy/source/common/event/dispatcher_impl.cc:163] item added to deferred deletion list (size=1)
2020-08-06T04:19:34.972855Z	trace	envoy main	[external/envoy/source/common/event/dispatcher_impl.cc:79] clearing deferred deletion list (size=1)
2020-08-06T04:19:34.972862Z	trace	envoy connection	[external/envoy/source/common/network/connection_impl.cc:493] [C14] socket event: 3
2020-08-06T04:19:34.972865Z	trace	envoy connection	[external/envoy/source/common/network/connection_impl.cc:581] [C14] write ready
2020-08-06T04:19:34.972870Z	trace	envoy connection	[external/envoy/source/common/network/connection_impl.cc:531] [C14] read ready
2020-08-06T04:19:34.972878Z	trace	envoy connection	[external/envoy/source/common/network/raw_buffer_socket.cc:25] [C14] read returns: 292
2020-08-06T04:19:34.972890Z	trace	envoy connection	[external/envoy/source/common/network/raw_buffer_socket.cc:39] [C14] read error: Resource temporarily unavailable
2020-08-06T04:19:34.972913Z	trace	envoy http	[external/envoy/source/common/http/http1/codec_impl.cc:486] [C14] parsing 292 bytes
2020-08-06T04:19:34.972925Z	trace	envoy connection	[external/envoy/source/common/network/connection_impl.cc:429] [C14] writing 66 bytes, end_stream false
2020-08-06T04:19:34.972954Z	debug	envoy http	[external/envoy/source/common/http/conn_manager_impl.cc:284] [C14] dispatch error: http/1.1 protocol error: HPE_INVALID_METHOD
2020-08-06T04:19:34.972961Z	debug	envoy connection	[external/envoy/source/common/network/connection_impl.cc:109] [C14] closing data_to_write=66 type=2
2020-08-06T04:19:34.972965Z	debug	envoy connection	[external/envoy/source/common/network/connection_impl_base.cc:30] [C14] setting delayed close timer with timeout 1000 ms
```

cc @GregHanson

**Comment by rshriram** [comment]
please provide config dump of the 0.0.0.0:443 listener on the failing cluster

**Comment by tariq1890** [comment]
@rshriram Here it is

```
 {
     "name": "0.0.0.0_443",
     "active_state": {
      "version_info": "2020-08-05T19:53:52Z/2",
      "listener": {
       "@type": "type.googleapis.com/envoy.api.v2.Listener",
       "name": "0.0.0.0_443",
       "address": {
        "socket_address": {
         "address": "0.0.0.0",
         "port_value": 443
        }
       },
       "filter_chains": [
        {
         "filter_chain_match": {
          "application_protocols": [
           "http/1.0",
           "http/1.1",
           "h2c"
          ]
         },
         "filters": [
          {
           "name": "envoy.http_connection_manager",
           "typed_config": {
            "@type": "type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager",
            "stat_prefix": "outbound_0.0.0.0_443",
            "rds": {
             "config_source": {
              "ads": {}
             },
             "route_config_name": "443"
            },
            "http_filters": [
             {
              "name": "istio.metadata_exchange",
              "typed_config": {
               "@type": "type.googleapis.com/udpa.type.v1.TypedStruct",
               "type_url": "type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm",
               "value": {
                "config": {
                 "vm_config": {
                  "runtime": "envoy.wasm.runtime.null",
                  "code": {
                   "local": {
                    "inline_string": "envoy.wasm.metadata_exchange"
                   }
                  }
                 },
                 "configuration": "{}\n"
                }
               }
              }
             },
             {
              "name": "istio.alpn",
              "typed_config": {
               "@type": "type.googleapis.com/istio.envoy.config.filter.http.alpn.v2alpha1.FilterConfig",
               "alpn_override": [
                {
                 "alpn_override": [
                  "istio-http/1.0",
                  "istio"
                 ]
                },
                {
                 "upstream_protocol": "HTTP11",
                 "alpn_override": [
                  "istio-http/1.1",
                  "istio"
                 ]
                },
                {
                 "upstream_protocol": "HTTP2",
                 "alpn_override": [
                  "istio-h2",
                  "istio"
                 ]
                }
               ]
              }
             },
             {
              "name": "envoy.cors",
              "typed_config": {
               "@type": "type.googleapis.com/envoy.config.filter.http.cors.v2.Cors"
              }
             },
             {
              "name": "envoy.fault",
              "typed_config": {
               "@type": "type.googleapis.com/envoy.config.filter.http.fault.v2.HTTPFault"
              }
             },
             {
              "name": "istio.stats",
              "typed_config": {
               "@type": "type.googleapis.com/udpa.type.v1.TypedStruct",
               "type_url": "type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm",
               "value": {
                "config": {
                 "root_id": "stats_outbound",
                 "vm_config": {
                  "vm_id": "stats_outbound",
                  "runtime": "envoy.wasm.runtime.null",
                  "code": {
                   "local": {
                    "inline_string": "envoy.wasm.stats"
                   }
                  }
                 },
                 "configuration": "{\n  \"debug\": \"false\",\n  \"stat_prefix\": \"istio\"\n}\n"
                }
               }
              }
             },
             {
              "name": "envoy.router",
              "typed_config": {
               "@type": "type.googleapis.com/envoy.config.filter.http.router.v2.Router"
              }
             }
            ],
            "tracing": {
             "client_sampling": {
              "value": 100
             },
             "random_sampling": {
              "value": 1
             },
             "overall_sampling": {
              "value": 100
             }
            },
            "access_log": [
             {
              "name": "envoy.file_access_log",
              "typed_config": {
               "@type": "type.googleapis.com/envoy.config.accesslog.v2.FileAccessLog",
               "path": "/dev/stdout",
               "format": "[%START_TIME%] \"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% \"%DYNAMIC_METADATA(istio.mixer:status)%\" \"%UPSTREAM_TRANSPORT_FAILURE_REASON%\" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(X-FORWARDED-FOR)%\" \"%REQ(USER-AGENT)%\" \"%REQ(X-REQUEST-ID)%\" \"%REQ(:AUTHORITY)%\" \"%UPSTREAM_HOST%\" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME%\n"
              }
             }
            ],
            "use_remote_address": false,
            "generate_request_id": true,
            "upgrade_configs": [
             {
              "upgrade_type": "websocket"
             }
            ],
            "stream_idle_timeout": "0s",
            "normalize_path": true
           }
          }
         ]
        }
```

**Comment by rshriram** [comment]
need complete dump of that listener with all filter chains and listener filters

**Comment by tariq1890** [comment]
I've corrected this. Thanks

**Comment by lizan** [comment]
@rshriram What's happening here is

a. Client initiates a HTTPS request, which Envoy cannot terminate its TLS
b. The first filter chain ` "application_protocols": ["http/1.0",  "http/1.1", "h2c"]` matches because TLS inspector fills `application_protocols` with ALPN (which include `http/1.1`)
c. The filter chain respond HTTP with response (because it has HCM)

while in case of a. the connection should go to `PassthroughFilterChain`. The filter chain match for plaintext http should specific about plaintext.

**Comment by rshriram** [comment]
>The first filter chain "application_protocols": ["http/1.0", "http/1.1", "h2c"] matches because TLS inspector fills application_protocols with ALPN (which include http/1.1)

This is news!!! Thanks lizan. How do we make it be specific about plaintext?

**Comment by lizan** [comment]
https://github.com/envoyproxy/envoy/blob/6a71f16c664f2e3a874d2a991262d49e6ed485c8/api/envoy/api/v2/listener/listener_components.proto#L134 use `raw_buffer` in transport_protocol

**Comment by rshriram** [comment]
Per @lizan ,
to match only on plaintext http, 

```
application_protocols: http/1.0, http/1.1, h2c
transport_protocols: raw_buffer
```

to match on non-TLS traffic,

```
transport_protocols: raw_buffer
```

So we have to fix our passthrough listener generation logic to use the raw buffer transport protocols. I wonder if we need to update other aspects of the sniffing logic to not assume that empty transport protocol + only application protocols mean no tls.

**Comment by tariq1890** [comment]
I changed the port name of another service from `http` to `https` and that took out the `0.0.0.0:443` listener completely from the istio-proxy config

**Comment by tariq1890** [comment]
@rshriram Could you point out where the logic for `port.Name` is being used here? Trying to understand how the port Naming affects listener creation

**Comment by howardjohn** [comment]
port.Name very early on becomes server.Protocol which is handled
differently in listener.go

**Comment by tariq1890** [comment]
I just want to add that this is rather concerning. The customer workload which had this bad port naming was not even meant to be a part of the service mesh (no istio-injection enabled in its namespace) and yet it broke the entire mesh. This speaks to the fragility of the Istio service mesh network. We can't afford to have such a mishap in production especially given its likely due to envoy's hot reloads.

I see two problems here

i) Why should just ONE service workload that's not istio-meshed bring down the service network?
ii) `port.Name` is intended to be largely informational and not of much consequence Kubernetes-wise. Why is Istio's proxy configuration so reliant on this field `port.Name`.

**Comment by howardjohn** [comment]
@tariq1890 we need a way to identify the protocol for a service. Until Kubernetes 1.18 (see appProtocol in https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/#manual-protocol-selection) we had no way of doing this other than either relying on port name, or relying on a special annotation on the Service. For better or worse, we chose to use port name rather than annotation.

> i) Why should just ONE service workload that's not istio-meshed compromise the entire service network?

It shouldn't, its a bug.

> its likely due to envoy's hot reloads.

Not sure what you mean by this - we *never* do hot reload anymore

**Comment by tariq1890** [comment]
Thanks for your response. I can see why you chose the port name approach. But sadly, in our not-ideal world, there will always be some sort of typos or hacks and misconfigurations by K8s users.

At the very least, we should have an `istioctl analyze` warning/error. But I am not sure if non-meshed components fall under the scope of `istioctl analyze`.

> It shouldn't, its a bug.

Sure happy to help and contribute a fix in any way I can

> Not sure what you mean by this - we never do hot reload anymore

Oh, I thought hot reloads were an instrinsic feature of `envoy`. If istio-proxy overrides that, please disregard :)

**Comment by howardjohn** [comment]
Opened envoy bug: https://github.com/envoyproxy/envoy/issues/12572

**Comment by howardjohn** [comment]
Found another bug on inbound match

See a declared port:
```
{"destinationPort":9090,"applicationProtocols":["istio","istio-http/1.0","istio-http/1.1","istio-h2"]}
{"destinationPort":9090}
```
vs undeclared:
```
{"prefixRanges":[{"addressPrefix":"0.0.0.0","prefixLen":0}],"transportProtocol":"tls","applicationProtocols":["istio-peer-exchange","istio"]}
{"prefixRanges":[{"addressPrefix":"0.0.0.0","prefixLen":0}],"transportProtocol":"tls","applicationProtocols":["http/1.0","http/1.1","h2c","istio-http/1.0","istio-http/1.1","istio-h2"]}
```

Two issues here:
1) A TLS request with no alpn set (or not matching any listed above) will not match any filter chain
2) A TLS request with ALPN set to http (not istio mTLS!) will match the istio mtls filter chain, and fail

(1) is just broken because we didn't realize how FCM works I guess. (2) is there for backwards compatibility with 1.3- Istio versions that do not set `istio-*` ALPN

cc @gargnupur if you are interested in this rabbit hole...

**Comment by gargnupur** [comment]
I think there are 2 in the undeclared one above for tcp and http traffic separately...

**Comment by howardjohn** [comment]
@gargnupur see https://github.com/envoyproxy/envoy/issues/12572 for details. tl;dr we all misunderstood how FCM works, if you send TLS traffic it will *never* match those other 2

**Comment by yann-soubeyrand** [comment]
As I understand, this bug is not fixed yet, right? Could we then remove the lifecycle/stale label?

**Comment by yann-soubeyrand** [comment]
Also, is there a known workaround (other than not using ALPN)?

**Comment by gargnupur** [comment]
@howardjohn : If you disable TCP telemetry, that should help too?

**Comment by howardjohn** [comment]
@yann-soubeyrand the original issue of http port blocking https IS fixed - in 1.8+. As a workaround you should not have an http port on 443 (probably shouldn't do this anyways), or you can not set ALPN I suppose.

The longer term issue that the FCM logic is super confusing and may lead to potential bugs, which is why this is still open

**Comment by saitejapakalapati1** [comment]
any workaround for this. not working after renaming port as well

**Comment by yonwon01** [comment]
after having http port on 443, still all the external traffic was blocked.

**Comment by pbohman** [comment]
We saw an issue upgrading from 1.7.3 to 1.8.2 where 1.7.3 proxies configured by a 1.8.2 control plane could not access a TCP service with an unrecognizable port name (eg, foo). The proxy access logs report `filter_chain_not_found`:

```
[2021-02-12T18:24:58.184Z] "- - -" 0 "filter_chain_not_found" NR "-" "-" 0 0 0 - "-" "-" "-" "-" "-" - - 10.3.0.189:9000 172.23.152.25:48670 - -
```

The 1.7.3 proxy filterchain matches look like the example in the envoy bug above
```
{
  "transportProtocol": "raw_buffer",
  "applicationProtocols": [
    "http/1.0",
    "http/1.1",
    "h2c"
  ]
}
null
```
Whereas 1.8.2 adds a `default_filter_chain` for the tcp proxy configuration instead of a null match for a catch all.

The connection works fine when the control plane and proxy are both 1.7.3 or 1.8.2.

Could this failed connection be a symptom of the bugs described in this issue? If so, is there a better workaround than requiring tenants to correctly name their TCP ports before the upgrade?
