### ISSUE TITLE
'istioctl verify-install' doesn't work with dev builds

### ISSUE THREAD

**Issue by esnible** [istio/istio#26070]
(using _istioctl_ from _~/go/src/istio.io/istio/out/darwin_amd64_

```
$ istioctl verify-install
Error: stat manifests/charts/addons/grafana: no such file or directory
$ istioctl verify-install -f /tmp/issue25848.yaml 
Error: compiled in charts not found in this development build, use --manifests with local charts instead (e.g. istioctl install --manifests manifests/) or run make gen-charts and rebuild istioctl
$ istioctl verify-install -f /tmp/issue25848.yaml  --manifests manifests/
Error: compiled in charts not found in this development build, use --manifests with local charts instead (e.g. istioctl install --manifests manifests/) or run make gen-charts and rebuild istioctl
```

It looks like two different problems.  The first and last error messages are the problems.

**Comment by ericvn** [comment]
@esnible Did you run `make gen-charts` before you did your dev build (built Istioctl)?

**Comment by esnible** [comment]
@ericvn As usual I did `make istioctl`, screwed around, then did `make gen-charts`, then `make istioctl` again.  That path works.

This issue is that if `make gen-charts` wasn't done, the output says to use `--manifests` but that option no longer works.  We either need to fix `--manifests` or remove that output.

**Comment by ericvn** [comment]
I think it was @ostromart who setup the process to have to run `make gun-charts` first. This was because we had a lot of rebasing needed to get PRs is, so a slimmed down set of charts is used.

**Comment by esnible** [comment]
I thought about assigning @ostromart but it was @irisdingbj and myself who worked on `verify-install`.

The problem is we have no integration tests for `verify-install`.  If we expect it to work without `make gen-charts` we need to test that.

**Comment by jwendell** [comment]
This is using the latest 1.7.alpha.2 build:
```
$ ./bin/istioctl verify-install 
Error: could not load IstioOperator from cluster: the server could not find the requested resource.  Use --filename
```

Is it the same issue reported here or should I create a new one?

**Comment by jwendell** [comment]
hmm, looks like it's an old issue: https://github.com/istio/istio/issues/24068

**Comment by esnible** [comment]
Using the official 1.7.0 beta.1 build of _istioctl_, I am getting

```
istioctl verify-install
Error: stat /Users/snible/go/src/istio.io/istio/manifests/charts/istio-policy: no such file or directory
```

Istio was installed using Master and `go test ./tests/integration/pilot/... --istio.test.env kube -run TestDescribe`

[iss.yaml.txt](https://github.com/istio/istio/files/5043080/iss.yaml.txt)

**Comment by ericvn** [comment]
@esnible I thought `istioctl verify-install` is no longer a valid command (since 1.6) (replaced by istioctl x recheck?). I know there was a recent PR removing instructions about using no parameters would make it work like precheck.

**Comment by esnible** [comment]
@ericvn `istioctl verify-install` in 1.5 had two possible behaviors.

- In K8s clusters w/o Istio, it would tell if the cluster met the Istio requirements.
- In clusters with Istio, it would tell if the K8s objects making up the control plane were present.
  - In older versions the user was required to use `-f <yaml>`, in recent versions it defaults to the IOP.

This means that users w/o Istio should do `istioctl pre-check`, and users with Istio should do `istioctl verify-install`.  This issue effects users who do `verify-install` with no `-f` and expect the default of using the IOP.

**Comment by esnible** [comment]
Verified the `--manifests` flag is working on Master.
