### ISSUE TITLE
istiod not creating istio-ca-secret

### ISSUE THREAD

**Issue by therealmitchconnors** [istio/istio#26094]
Following [these](https://preliminary.istio.io/latest/docs/examples/virtual-machines/single-network/) instructions to create VM certificates, the generate_cert script expects istiod to have created a secret named "istio-ca-secret", but no such secret exists. 

```
~/istio-1.7.0-alpha.2$ go run istio.io/istio/security/tools/generate_cert \
      -client -host spiffee://cluster.local/vm/vmname --out-priv key.pem --out-cert cert-chain.pem  -mode citadel
kubectl -n istio-system get cm istio-ca-root-cert -o jsonpath='{.data.root-cert\.pem}' > root-cert.pem
2020-08-03T23:22:36.174245Z	info	Command failed error: exit status 1
, output
Error from server (NotFound): secrets "istio-ca-secret" not found
exit status 1

~/istio-1.7.0-alpha.2$ kubectl get secret -n istio-system
NAME                                               TYPE                                  DATA   AGE
cacerts                                            Opaque                                4      50m
default-token-m9c52                                kubernetes.io/service-account-token   3      56m
istio-ingressgateway-service-account-token-mr4dj   kubernetes.io/service-account-token   3      44m
istio-reader-service-account-token-nll7g           kubernetes.io/service-account-token   3      50m
istiod-service-account-token-qq5nn                 kubernetes.io/service-account-token   3      50m

~/istio-1.7.0-alpha.2$ kubectl get deployment -n istio-system istiod
NAME     READY   UP-TO-DATE   AVAILABLE   AGE
istiod   1/1     1            1           53m
```

**Comment by howardjohn** [comment]
I may have misled you, I think when cacerts is present its not there. So there will be either cacerts (provider certs by user) or istio-ca-secret (self signed)

**Comment by therealmitchconnors** [comment]
Does that make my change in https://github.com/istio/istio.io/pull/7815 correct?

**Comment by howardjohn** [comment]
No, because plugged in certs like the doc are cacerts secret. istio-ca-certs is where istio writes it own self signed certs to. We dont use self signed certs in that doc.

**Comment by therealmitchconnors** [comment]
So, there's definitely a problem somewhere, as the generate_cert script has the istio-ca-cert secret name hard-coded, but the steps in the doc use cacerts.  Do the docs need to change, or the script?

**Comment by matty111** [comment]
I have the same problem

**Comment by howardjohn** [comment]
generate_cert is no longer used in the doc so I think this is fixed
