### ISSUE TITLE
Provide HTTP2_PRIOR_KNOWLEDGE H2UpgradePolicy

### ISSUE THREAD

**Issue by scr-oath** [istio/istio#26097]
**Describe the feature request**

There are situations where you have a server that can only serve on HTTP/2 such as using python's [hyper-h2](https://github.com/python-hyper/hyper-h2) which performs very well.  As it does not support HTTP/1.1 or lower, it is not possible to issue the UPGRADE header.  Similar to curl's CLI flag `--http2-prior-knowledge` it would be very helpful to provide a [H2UpgradePolicy](https://istio.io/latest/docs/reference/config/networking/destination-rule/#ConnectionPoolSettings-HTTPSettings-H2UpgradePolicy) setting `HTTP2_PRIOR_KNOWLEDGE` which always uses HTTP/2 when communicating with the application, but without the `Upgrade: h2c`.

https://curl.haxx.se/docs/http2.html
> curl offers the --http2-prior-knowledge command line option to enable use of HTTP/2 without HTTP/1.1 Upgrade.

**Describe alternatives you've considered**
Serving the app with TLS and tunneling to it seems to allow the use of ALPN with a response of only `h2` but, of course, does not support 1.1 clients directly, and doesn't naturally support the notion of TLS-termination and other goodies such as "mTLS" AuthNZ (authentication + authorization).

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
Just to make sure I fully understand - is this for cases where the client will not send h2 with prior knowledge so envoy needs to upgrade, or does this also apply if the client is already sending h2?

**Comment by howardjohn** [comment]
cc @mandarjog

**Comment by mandarjog** [comment]
@scr-oath did you try the current behaviour? I think it already does what you are suggesting, in fact we cannot do h2c upgrade, we only do prior knowledge.

Please let me know if this is not happening and I  will investigate.

**Comment by scr-oath** [comment]
Hmm… I did a little trial and error, and it seems if you name the service port `http2` then it does the conversion (not "upgrade") to HTTP/2 - but then I really don't know what the intention of these settings is (https://istio.io/latest/docs/reference/config/networking/destination-rule/#ConnectionPoolSettings-HTTPSettings-H2UpgradePolicy) UPGRADE appears to try to connect HTTP/1.1 and issue the `Upgrade: h2c` - I haven't sniffed with tcpdump but the behavior is just that it gets disconnected abruptly, which hyper-h2 appears to do if not HTTP/2

**Comment by scr-oath** [comment]
@howardjohn - yes and no - regardless of what the client sends, the proxied connection appears to be 1.1 by default (with none of these setting adjustments made).  This is in a kubernetes set up with an istio ingress and the istio-proxy sidecar (envoy?) along with virtual service and destination rule.

**Comment by mandarjog** [comment]
`H2UpgradePolicy` comes into play when the destination port is **NOT** http2. This means that the destination service is not capable of receiving h2 traffic so the port **will not** be named as an http1 port.
Upgrade policy will still upgrade the http1.1 connection at the client sidecar, and the server sidecar will downgrade it back to http1.

If your service actually support h2, then this does not apply. Just naming the port as h2 or grpc will suffice.

If you are using outbound protocol sniffing, we use `USE_DOWNSTREAM_PROTOCOL` setting which I suspect is causing confusion here.

**Comment by scr-oath** [comment]
Hmm… so… this influences the outward/"downstream" upgrade policy; not the inward/"upstream" one… and only really influences how to respond to clients who request an ALPN for "h2" or "Upgrade: h2c" header? And the inward/"upstream" choice is made by the service's port.name?

If so, then we can close this, or convert it to a documentation bug to clarify that point and those semantics of which direction it influences and/or link from one (which may be found in search) to the other; since they're different mechanisms in different docs so find in page doesn't help understand how to control each behavior.

**Comment by scr-oath** [comment]
This doc seems to be the place to link to, possibly with description that it is how one alters the inward/"upstream" connection protocol https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/

**Comment by scr-oath** [comment]
https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/ seemed like the closest thing I could find to description of internal protocol but shows appProtocol, when it seems that merely the choice of service.port.name does the trick - at least in our cluster (there may be more choices made by our admins that I haven't examined).

**Comment by mandarjog** [comment]
@scr-oath it would be great if you can send a doc PR.

**Comment by scr-oath** [comment]
Yeah, this is pretty stale - for better or worse, I think I mistook the meaning of the upgrade policy to be directed at the app, when it's directed at the clients - I found another mechanism for forcing the protocol to the app to be http2 merely by naming the service portName http2.

Closing this as invalid to the original use of H2UpgradePolicy; if I get around to sending doc pr I'll either just make the PR or open a new issue
