### ISSUE TITLE
proxy config not synced when the istiod is high load but not dead

### ISSUE THREAD

**Issue by mgxian** [istio/istio#26109]
When my k8s cluster some node load is very high but not dead, just run so slow. If one istiod is running on this node, all pod that sidecar proxy connect to this istiod will stuck, and all proxy config will not update. contour user also encounter this issue, https://github.com/projectcontour/contour/issues/1523, and they decide add some keepalive config to xds cluster, see this issue https://github.com/projectcontour/contour/issues/1744 
I think we should add keepalive config in the envoy bootstrap config to avoid this. just like this :
```json
      {
       "name": "xds-grpc",
       "type": "STRICT_DNS",
       "connect_timeout": "10s",
       "hidden_envoy_deprecated_hosts": [
        {
         "socket_address": {
          "address": "istio-pilot.istio-system",
          "port_value": 15010
         }
        }
       ],
       "max_requests_per_connection": 1,
       "circuit_breakers": {
        "thresholds": [
         {
          "max_connections": 100000,
          "max_pending_requests": 100000,
          "max_requests": 100000
         },
         {
          "priority": "HIGH",
          "max_connections": 100000,
          "max_pending_requests": 100000,
          "max_requests": 100000
         }
        ]
       },
       "http2_protocol_options": {},
       "dns_refresh_rate": "300s",
       "dns_lookup_family": "V4_ONLY",
       "upstream_connection_options": {
        "tcp_keepalive": {
         "keepalive_time": 300,
         "keepalive_probes": 3,
         "keepalive_interval": 5,
        }
       }
      },
```

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by mgxian** [comment]
I found that when node is very high, ping is work very well, but pilot not push any update to envoy proxy,Maybe we should add GRPC health checking in the static envoy config.
[Envoy Health check Doc](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/health_check.proto#health-check)

**Comment by howardjohn** [comment]
What version are you running? we do ahve keepalive now: https://github.com/istio/istio/blob/2aba66143b90046a3846f89ea08936affa7c677e/tools/packaging/common/envoy_bootstrap.json#L345

**Comment by mgxian** [comment]
but 300 seconds is to too long. If at this period, we restart our pod, then the envoy is still the old endpoint, We will get 503

**Comment by howardjohn** [comment]
@ramaraochavali any thoughts on making it lower?

**Comment by ramaraochavali** [comment]
Sure. We can lower this - Should we make it 120s?

**Comment by mgxian** [comment]
I think that is not a good idea！I think we should make the envoy check the pilot's health more often. we can use envoy active health check. more info https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/core/health_check.proto
