### ISSUE TITLE
Istio 1.6.7 install from binary failed by x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by tringuyen-yw** [istio/istio#26100]
**Bug description**
Attempting to install istio 1.6.7 on Ubuntu 20.04. MicroK8s 1.18.6 already installed and the istio addon is NOT enabled (because it’s an old version 1.5.1).

Following the instructions on https://istio.io/latest/docs/setup/getting-started/#install

```
istio-1.6.7$ export PATH=$PWD/bin:$PATH

istio-1.6.7$ istioctl install --set profile=demo
Error: failed to apply manifests: Get "https://192.168.1.98:16443/api?timeout=32s": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "10.152.183.1")
```

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
It's an error connecting to API server can you do simple kubectl commands like kubectl apply?

**Comment by tringuyen-yw** [comment]
Oups, I had removed & reinstalled a brand new microk8s. My `~/.kube/config` was not updated with the authentication keys with the new microk8s cluster. Thanks you very much for your help.
