### ISSUE TITLE
Opendistro-es with istio

### ISSUE THREAD

**Issue by NickDatLe** [istio/istio#26134]
**Bug description**
When installing opendistro on kubernetes (server 1.17.3, client 1.16.6), kibana cannot communicate with elasticsearch. This seems to be an issue with the TLS that is enforced by opendistro (more details at the opendistro github: https://github.com/opendistro-for-elasticsearch/security/issues/37). Right now, TLS cannot be disabled in opendistro. I need other pods to be able to communicate with opendistro's master node

[ ] Docs
[ ] Installation
[ x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
For pods to be able to communicate with each other

**Steps to reproduce the bug**
Helm install opendistro-es (current version is 1.9) and try to make a curl call to elasticsearch from the kibana pod.
curl -k -u admin:PASSWORD https://opendistro-es-master-service:9200

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.6.5
**How was Istio installed?**
istioctl
**Environment where bug was observed (cloud vendor, OS, etc)**
AWS, Docker Desktop with kubernetes installed

**Comment by incfly** [comment]
I don't know anything about `Opendistro-es`. It will be better if the bug provide relevant information w.r.t Istio.

Though I do know we have issues with ElastricSearch see https://github.com/istio/istio/issues/22220. Mainly due to the fact their own cross node communication using pod IP can have an effect on the client side mTLS.

**Comment by OferPRTZ** [comment]
Someone know if this issue has been address or fixed by any mean? (can't find any other reference to this problem) thanks!
