### ISSUE TITLE
Istio prometheus is missing "kubernetes_node" label

### ISSUE THREAD

**Issue by papovyr** [istio/istio#26148]
I started to notice that community Grafana dashboards for node exporter will not work with istio prometheus as prometheus config is missing following `source_label` in `kubernetes-service-endpoints` job

```
- jobe_name: kubernetes-service-endpoints
.........
  - source_labels: [__meta_kubernetes_pod_node_name]
    separator: ;
    regex: (.*)
    target_label: kubernetes_node
    replacement: $1
    action: replace
```
This `source_labels: [__meta_kubernetes_pod_node_name]` will add additional label (`kubernetes_node`) which is used in many dashboards to build graphs 

Also there is no `prometheus` job which is monitoring for prometheus itself (inside metrics)
```
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 1m
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090)
```

Going forward it will be nice to see that prom helm config is merged with istio so it will provide same metrics and istio metrics on top of it.

How to reproduce
Install kube-state-metrics, node-exporter, prometheus-server with helm 
```
kubectl  create ns prometheus
helm upgrade --install prometheus -n prometheus stable/prometheus --set alertmanager.enabled=false --set pushgateway.enabled=false
```
Install istio (istio-1.6.5)
```
istioctl manifest apply --set profile=default
```
proxy to prometheus port which installed with helm 
```
kubectl port-forward  --address 0.0.0.0 -n prometheus  service/prometheus-server 2000:80
```
open url
```
http://127.0.0.1:2000/graph?g0.range_input=1h&g0.expr=avg%20by%20(kubernetes_node%20)%20(rate(node_cpu_seconds_total%5B2m%5D))&g0.tab=0
```

Now proxy port for istio prometheus 
```
kubectl port-forward  --address 0.0.0.0 -n istio-system  service/prometheus 2000:9090
```
open same url
```
http://127.0.0.1:2000/graph?g0.range_input=1h&g0.expr=avg%20by%20(kubernetes_node%20)%20(rate(node_cpu_seconds_total%5B2m%5D))&g0.tab=0
```

When you access url for first prometheus you will see all nodes and metrics associated with it 
with istio prometheus you will see only one metric as `kubernetes_node` label dose not exist

Please update prometheus config.

**Comment by howardjohn** [comment]
We will not be adding configurability or supporting installation of Prometheus any longer - see https://istio.io/latest/blog/2020/addon-rework/ for details. Note we will still integrate with Prometheus but won't manage installation. Thanks!

**Comment by papovyr** [comment]
@howardjohn  thank for clarifying that istio will not support addons installation moving forward
However it's not clear what path is taking prometheus. Is prometheus used by istiod/envoy to make features like circuit braking, fault injection available ?

Can I disable Istio prometheus, enable Prometheus Merge setting (--set meshConfig.enablePrometheusMerge=true --set values.prometheus.enabled=false) and install prometheus with helm?
Will this impact istio control plane features ?

**Comment by howardjohn** [comment]
Istio does not depend on Prometheus at all, it is purely additional for monitoring
