### ISSUE TITLE
istio-policy always crash

### ISSUE THREAD

**Issue by kengan** [istio/istio#26157]
I use  istioctl manifest apply --set profile=demo  to install istio 1.4.10 on my kubernetes 1.13.
After install, the pod Istio-policy alway crash. plesase see the following image
![55D~S_~IALW~%L4VH%9SIJR](https://user-images.githubusercontent.com/18627678/89394149-4db6ef00-d73e-11ea-99d6-0fa067e73e77.png)
the pod event show as following image 
![C)J(EPD8YYQO{5~F3}L~OJT](https://user-images.githubusercontent.com/18627678/89394261-6f17db00-d73e-11ea-9369-bd932e152617.png)

can you tell my how to solve this problem, thank you

**Comment by mandarjog** [comment]
@kengan istio 1.4 has reached end of life.
Please try it on a supported version of Istio. (1.5 +) at this time.
Please also include logs from the istio-policy pods. Thanks.
