### ISSUE TITLE
Aws eks on fargate suppport

### ISSUE THREAD

**Issue by SeliMeli** [istio/istio#26154]
**Describe the feature request**

AWS eks on fargate has some limitations that blocked istion sidecar injection. EKS on fargate dont allow privilege pod("NET_ADMIN") nor daemonset(CNI). 

**Describe alternatives you've considered**

AWS appmesh support fargate now.

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
Would be great to add this but it doesn't seem possible without AWS adding explicit support for Istio. Given they added support for app mesh, its clearly possible but the ball is in their court: https://github.com/aws/containers-roadmap/issues/682

**Comment by Dhua-v** [comment]
the NET_ADMIN is a priviliged user, whom even I wouldnt allow if fargate does. Hence, Istio now provides ISTIO-CNI, we need to use it. https://github.com/istio/istio/tree/master/cni

**Comment by howardjohn** [comment]
I don't think fargate supports cni either

**Comment by Dhua-v** [comment]
Was reading this article, https://aws.amazon.com/blogs/containers/under-the-hood-fargate-data-plane/
It was referring that fargate is utilizing CNI.

**Comment by howardjohn** [comment]
AWS is using CNI under the hood, but we cannot install a custom CNI plugin as far as I know

**Comment by Dhua-v** [comment]
thanks john to let us know that.
