### ISSUE TITLE
How to build istio image on arm64 plantform？

### ISSUE THREAD

**Issue by DrowringMan** [istio/istio#26155]
**Describe the feature request**

**Describe alternatives you've considered**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by wenyuangui** [comment]
any suggestion for arm64 docker images?

**Comment by howardjohn** [comment]
Closing as a duplicate of https://github.com/istio/istio/issues/26508 and/or https://github.com/istio/istio/issues/21094. We currently only support building istioctl on arm; other binaries are community supported. See the second issue especially, tons of info there. Thanks!
