### ISSUE TITLE
Make fails with `ld: unknown option: -no-as-needed` on Mac OS

### ISSUE THREAD

**Issue by MPV** [istio/istio#2615]
I'm trying to build istio/istio on a Mac, but the `make` fails (see output below). 

I've installed `go`, `bazel`, and `buildifier`. Are there any other dependencies I might need?

```
$ make
touch pilot/platform/kube/config
bazel  build  //...
............................................................
INFO: Analysed 467 targets (699 packages loaded).
INFO: Found 467 targets...
ERROR: /private/var/tmp/_bazel_vs/b8438b9e803187158de7bc8f3c91ecc6/external/com_github_google_protobuf/BUILD:265:1: Linking of rule '@com_github_google_protobuf//:js_embed' failed (Exit 1): cc_wrapper.sh failed: error executing command
  (cd /private/var/tmp/_bazel_vs/b8438b9e803187158de7bc8f3c91ecc6/execroot/io_istio_istio && \
  exec env - \
    PATH=/Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/bin:/usr/local/Homebrew/Library/Homebrew/shims/super:/usr/local/opt/go/bin:/usr/local/opt/bazel/bin:/usr/local/opt/buildifier/bin:/usr/bin:/bin:/usr/sbin:/sbin \
    PWD=/proc/self/cwd \
    TMPDIR=/tmp \
  external/local_config_cc/cc_wrapper.sh -o bazel-out/host/bin/external/com_github_google_protobuf/js_embed bazel-out/host/bin/external/com_github_google_protobuf/_objs/js_embed/external/com_github_google_protobuf/src/google/protobuf/compiler/js/embed.o -lstdc++ -lm -Wl,-no-as-needed -Wl,-z,relro,-z,now -undefined dynamic_lookup -headerpad_max_install_names -Wl,-S)

Use --sandbox_debug to see verbose messages from the sandbox
ld: unknown option: -no-as-needed
clang: error: linker command failed with exit code 1 (use -v to see invocation)
INFO: Elapsed time: 98,256s, Critical Path: 8,87s
FAILED: Build did NOT complete successfully
make: *** [build] Error 1
```

**Comment by MPV** [comment]
For anyone curious, this is for a Homebrew formula for Istio I've been drafting (https://github.com/Homebrew/homebrew-core/pull/22897/), hoping to make it easier to install on Mac. 😊

**Comment by christian-posta** [comment]
So for the latest master, we no longer need bazel. Have you been trying on latest master? Or on 0.4.0?

**Comment by MPV** [comment]
This was for 0.4.0 (sorry that I forgot to mention it).

I was thinking of trying with master, but as I was creating a Homebrew recipe it felt preferable to use a released version. :blush:

**Comment by christian-posta** [comment]
FWIW, i'd target the upcoming release. Bazel is a hassle in my experience and it's not part of the build going forward.

**Comment by MPV** [comment]
👍 Thanks. 

I might revisit when the next version is released (seemed like around Jan 27th?) as I'm under the assumption that Homebrew might be more open to merge in a Formula tied to a version, instead of following the master branch. :blush:

**Comment by robcresswell** [comment]
@MPV `0.5.0` is out now, if you wanted to try again 😃

**Comment by hklai** [comment]
mac build is more stable now. Please reopen if this is still an issue.
