### ISSUE TITLE
Making the mesh-wide default retry policy configurable

### ISSUE THREAD

**Issue by lainra** [istio/istio#26158]
Hi everyone, I think this is a long-lived topic but I bring it back again.

Is there any plan to make the [default retry policy](https://github.com/istio/istio/blob/7c2c22d3c978456cb2de6d8ccccf12375357cb94/pilot/pkg/networking/core/v1alpha3/route/retry/retry.go#L36-L52) configurable across the mesh? I don’t get why we should have a hardcoded configuration for it that affects any Kubernetes service reached by any Istio sidecar. It breaks the boundaries between Istio workloads and non-Istio workloads by forcing to setup a VirtualService with specific retry policy to configure the non-Istio managed Kubernetes service.
In the case you have 5% services using Istio (which forcibly happen in the start of the adoption), it is hard to argue having to create VirtualServices for the remaining 95%. (several hundreds)
We are considering to patch Istio to change the hardcoded value/make it configurable and run our own build to solve this but this is definitely not a happy outcome.

Few questions:

- Would you consider upstreaming that patch?
- Would you consider making the change by yourself and make it upstream?
- Is there any other possible way to avoid going that way?

I really enjoy using Istio and the community but this kind of forced submission to opinionated choices without a way to opt-out is saddening. Anyway, thank you very much for all the awesome support over the years :bow:

**Comment by Buffer0x7cd** [comment]
👍

**Comment by rshriram** [comment]
cc @louiscryan - pertains to the topic we discussed earlier.

**Comment by rshriram** [comment]
So there are a few ways to solve this.. Matter of fact, in our internal implementation at my company, we have an API explicitly meant for this purpose (one that allows setting the resilience settings [timeout, retry, outlier, etc.] at client-namespace level, such that it applies to all sidecars in that namespace, irrespective of the destination of that client. My preference would be to have a similar API in Istio, one that allows user to specify the resilience settings at the client namespace level, so that the settings in virtual services act as merely overrides (I wager that most would stop using the per virtual service settings).

Whether that API will be a separate CRD or will be part of the existing Sidecar CRD is a matter of debate. If its part of sidecar CRD, then it will result in some onerous copy-paste of global/namespace wide values as users customize the Sidecar per namespace/ per workload. If its a separate CRD, then it can apply independent of the presence of Sidecar or their overrides, but it will be yet another crd, with similar workload style semantics (global in config root namespace, namespace wide, per workload). What are your thoughts @lainra ?

**Comment by nrjpoddar** [comment]
@rshriram we should look at fixing this. It has come up a few times now and I know we sometimes point people to use EnvoyFilter which has its own issues.

**Comment by lainra** [comment]
@rshriram Thanks for the quick reply, really appreciate it!

The quick patch we're thinking of is to:
- change the hardcoded value to our fitting default (very opinionated, not for other users)
- add a [MeshConfig](https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPRetry) setting for each parameter from [HTTPRetry](https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPRetry)

The first is hardly portable so it would be our workaround until having a proper solution merged upstream.

The second is more portable but may conflict with the intended purpose of MeshConfig and what kind of configuration/how much configuration we need to add there.

The primary purpose is to counteract the hardcoded and non-changeable parameters (now only know about Default Retry Policy) but it could be expanded to other parameters if they exist and fit both statements. It would still open a path to get more and more settings into MeshConfig, which is probably not something the maintainers are happy to go with?

Having an external way as you mentioned to modify resilience settings based on the same model of Sidecar CRD with the same workload style semantics looks like a good idea.

I'd like to give pros and cons for each option:

## 1. Within same Sidecar CRD 

### Pros:
- Reuse existing CRD, limiting the cost of handling one more interface to configure the mesh
- Sidecar already has the purpose to define configuration based on location semantics

### Cons:
- The Sidecar CRD gets overloaded if we add all resilience settings there
- Need to clarify the Sidecar resource for users on what it is used for when we add new configuration, as even the current resource is quite confusing by its name and configuration for users

## 2. Within a new CRD

### Pros:
- Most flexible way to implement a new interface 

### Cons:
- Adding one more CRD will make an already complicated process even more 
- For a given sidecar configuration, some parameters will be set in Sidecar while others will be set in the new CRD, leading to more risks of getting things wrong and worse user experience. It may defeat the purpose of a new CRD.
- Need to handle the CRD lifecycle (release process, versioning...) 

@nrjpoddar Thanks for the follow-up, I didn't think about using EnvoyFilter but as you said, it brings its own issues and hard to justify adding one more filter to offset a default. The less filters we have by default the better, for various reasons, especially in environments that don't support them (i.e. Anthos Service Mesh).
Nonetheless, it would be great if could you elaborate more on how you would do that. 

Would it be setting the retry policy in the EnvoyFilter as overriding the default sidecar configuration? In this case, how would it identify things to override (default retry policy) and not to override (explicit retry policy)?

**Comment by howardjohn** [comment]
Very related design doc: https://docs.google.com/document/d/1hY-ShGY6sgwWUw0NGLvsDWXWm3wNLvhM4HHuRjFzRT0

**Comment by rshriram** [comment]
EnvoyFilter is not a filter. its a crd that modifies the generated xds config. And the reason for suggesting separate crd was so that gateways and sidecars will be equally configured using this. give me sometime and i can dump the envoyfilter crd we use for our purposes

**Comment by howardjohn** [comment]
We have a bunch of issues around defaults, lets consolidate into https://github.com/istio/istio/issues/6861 to clean things up. Please also see https://docs.google.com/document/d/1hY-ShGY6sgwWUw0NGLvsDWXWm3wNLvhM4HHuRjFzRT0/ which is a design doc for this being actively worked on.
