### ISSUE TITLE
Is it normal for an empty ClusterLoadAssignment to appear when calling EDS?

### ISSUE THREAD

**Issue by mjs0514** [istio/istio#26162]
![image](https://user-images.githubusercontent.com/9962834/89409141-89f94800-d75c-11ea-9994-07b944c24567.png)

This figure shows the log taken by the pilot when ADS is called to istio by directly implementing the grpc communication protocol between envoy and istio. (Total twice, No Cloud Cluster environment.)

When calling the EDS call, 13 resources were specified, 7 of which are empty. (empty:7)

When I checked the ClusterLoadAssignment that was actually empty on the client side, it looked like this:
cluster_name: "outbound|53||kube-dns.kube-system.svc.cluster.local"
cluster_name: "outbound|9153||kube-dns.kube-system.svc.cluster.local"
cluster_name: "outbound|15010||istiod.istio-system.svc.cluster.local"
cluster_name: "outbound|15012||istiod.istio-system.svc.cluster.local"
cluster_name: "outbound|443||istiod.istio-system.svc.cluster.local"
cluster_name: "outbound|15014||istiod.istio-system.svc.cluster.local"
cluster_name: "outbound|853||istiod.istio-system.svc.cluster.local"

I am wondering if this is normal or abnormal now, and I think it is abnormal.

The reason why I thought this is because when I searched the endpoint of envoy injected into the prometheus pod, ClusterLoadAssignment was not empty for the same clusterName.

 How can I analyze the cause of the problem?

* Istio version : 1.6.0
![image](https://user-images.githubusercontent.com/9962834/89410220-47d10600-d75e-11ea-8eed-a170bbe40ee1.png)

**Comment by howardjohn** [comment]
Does restart of istiod fix it? may be fixed by https://github.com/istio/istio/pull/26142

**Comment by mjs0514** [comment]
First of all, thank you so much for answering howardjohn.

I am using the built release version linked to the istio official homepage.

So when I checked the link, I saw that the merged commit is not in the latest release. I think you can test it out when a newer release or beta version comes out in the future.

If the release is too late, I'll build it myself, test it, and comment again.

**Comment by howardjohn** [comment]
Yes it has not been released yet. You can try it out from https://github.com/istio/istio/wiki/Dev%20Builds (something like https://storage.googleapis.com/istio-build/dev/1.8-alpha.cb64645ea84773de5177396fa25bcd307d9356a6/istio-1.8-alpha.cb64645ea84773de5177396fa25bcd307d9356a6-linux-amd64.tar.gz)

**Comment by mjs0514** [comment]
OMG. Thanks @howardjohn 

I tested it with this binary. Unfortunately, the same problem occurred.

To explain my situation in a little detail.
It is a Java Client Program, and it sends a request to a pilot. (generating Java Code of grpc service and envoy related proto.)

I called Aggregated Discovery Service according to the xds protocol. However, we are receiving 7 blank CLAs in our EDS request, and the cause cannot be determined at this time. (The dev binary uses v3 resources, so I changed them all accordingly.)

Could I get help?

**Comment by howardjohn** [comment]
Oh this is not Envoy? you are probably missing metadata. Specifically, the https://github.com/istio/istio/blob/cb64645ea84773de5177396fa25bcd307d9356a6/pilot/pkg/model/context.go#L454 field is likely missing

**Comment by mjs0514** [comment]
I'm sorry for the delay in responding.
I have not been able to test the issue due to other work.
As soon as you test, I will reply again.

**Comment by howardjohn** [comment]
Closing as this is assumed fixed and we haven't had any updates. If you get more info and still have issues let us know. Thanks
