### ISSUE TITLE
CorsPolicy allowOrigin example in reference docs using outdated format

### ISSUE THREAD

**Issue by jamesjwarren** [istio/istio#26160]
**Bug description**
CorsPolicy example in reference docs using outdated format for allowOrigin. According to the reference table`allowOrigin` should be `allowOrigins` and value should be of type `StringMatch[]` instead of `string[]`.
https://istio.io/latest/docs/reference/config/networking/virtual-service/#CorsPolicy

[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Expected the example config to work with the current istio version.

**Steps to reproduce the bug**

Applying the reference example doesn't work as expected, no cors origin policy applied.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

1.6.7 

**How was Istio installed?**

istioctl / IstioOperator

**Environment where bug was observed (cloud vendor, OS, etc)**

GKE

**Comment by howardjohn** [comment]
thanks, this is fixed now
