### ISSUE TITLE
Edit a workload entry leads to stale endpoints

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#26178]
```
$ ik pc endpoint `kp 65d` | rg vm
10.28.3.32:18080                 HEALTHY     OK                outbound|80||vm-a.echo.svc.cluster.local
10.28.3.33:18080                 HEALTHY     OK                outbound|80||vm-a.echo.svc.cluster.local
$ k get we
NAME                      AGE   ADDRESS
vm-a-v1-979ddcc48-58m7c   11m   10.28.3.33
```

After editing workload entry

**Comment by howardjohn** [comment]
I also see missing clusters sometimes. Maybe we don't do a full CDS push when a new WE is added

**Comment by hzxuzhonghu** [comment]
Not sure if it is same as https://github.com/istio/istio/issues/26098

**Comment by hzxuzhonghu** [comment]
What did you change to the wle?

**Comment by howardjohn** [comment]
the address

**Comment by hzxuzhonghu** [comment]
Ok, then it is not same. Let me have a look though this is not a normal use case.

**Comment by hzxuzhonghu** [comment]
This is similar to #25678, I am thinking if we should prohibit updating some fields of workloadentry? As pod, it is not allowed to update podip during pod lifecycle.
Other fields, like ports change may have unexpected behavior

**Comment by howardjohn** [comment]
Verified fixed
