### ISSUE TITLE
Webhook failing on k8s 1.16 and 1.17

### ISSUE THREAD

**Issue by nmittler** [istio/istio#26186]
**Bug description**
I am seeing the following error in the istiod logs resulting from attempts to perform webhook injection:

```
Could not decode body: no kind "AdmissionReview" is registered for version "admission.k8s.io/v1beta1" in scheme "pkg/runtime/scheme.go:101"
```

There appears to be a mis-match between k8s version and Istio. There have been recent changes in this area that may be suspect.

May be related to #24723

[ ] Docs
[x] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Steps to reproduce the bug**

Install Istio (as shown below) and then deploy any app to trigger webhook injection.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

Using the latest images from `gcr.io/istio-testing`, so master branch I assume.

**How was Istio installed?**

I'm deploying istio with the latest images:

```bash
istioctl --context=${CTX1} manifest apply -f \
    ${WORK_DIR}/${CLUSTER1}/install.yaml \
    --charts manifests \
    --set values.global.hub=gcr.io/istio-testing \
    --set values.global.tag=latest \
    --set values.global.imagePullPolicy=Always
```

**Environment where bug was observed (cloud vendor, OS, etc)**

GKE `1.16.13-gke.1`
GKE `1.17.9-gke.600`

**Comment by nmittler** [comment]
@tariq1890 I'm worried that this may be related to #24723. Could you take a look?

**Comment by tariq1890** [comment]
Ok
