### ISSUE TITLE
Create component files for installation on k8s

### ISSUE THREAD

**Issue by christian-posta** [istio/istio#2619]
Right now all of the installation components for running istio on k8s are merged into a single `istio.yaml` file. In a more controlled environment, we may install and version each component of istio separately -- it would be nice to diff/version each component separately. 

Would like a way to generate the individual component (mixer, pilot, ca, etc) installation files separate from the all-in-one.

**Comment by linsun** [comment]
cc @ZackButcher as I think the new istioctl is trying to solve this.  Further, the new helm install is also allow users to configure the installation via values.yaml to indicate which component to turn on.

**Comment by ZackButcher** [comment]
@christian-posta as others said, my stab at addressing this type of use case was the [`gen-deploy` subcommand in `istioctl`](https://github.com/istio/istio/tree/master/pilot/cmd/istioctl/gendeployment). It (and our helm charts) needs quite a bit more work, but the vision is that this tool address the use case of "I want only features X, Y, Z"; given the target feature set it produces the minimum Istio control plane required to implement them. Per-component config helps for operators trying to deploy only specific components, but the operator still needs to know which components are required for which features they want. The goal of the tool is to hide that complexity from operator too.

@sdake that is the long term plan (and I still need to draw up a doc outlining things), but that's unfortunately lower priority work than many of the other stuff on my plate at the moment. It'll be quite a while before I can really get around to tackling that (help on that front would be awesome!).
