### ISSUE TITLE
Performance for TLS

### ISSUE THREAD

**Issue by kentchenjh** [istio/istio#26200]
I have read the performance summary for istio 1.6.7(https://istio.io/latest/docs/ops/deployment/performance-and-scalability/). It seems the test didn't contain any comparsion between TLS and no TLS. Wanna know more about the cost of TLS, especially latency. Is there any report to show this, and seeking any helpful advice.

[ ] Docs
[ ] Installation
[ ] Networking
[X] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by carolynhu** [comment]
@kentchenjh thanks for your inquiry, we did some work on comparing tls vs non-tls from the latency perspective. However, we did not make it as a required data for publishing on the istio.io perf section. We probably could do it in istio-1.7 release or its minor releases (if time permits) or next istio release.

**Comment by kentchenjh** [comment]
@carolynhu thanks for your reply. A part of users worried about the cost of tls. Since they had a secure network across clusters, tls is not essential. However, as far as I know turning off tls would make across cluster invoking more tedious. So the data about tls latency is kind of important. plz let me know if there is any advance.

**Comment by carolynhu** [comment]
Hi @kentchenjh , update on this ticket, we've published our blog post regarding security policies effect on performance, which can be found here: https://istio.io/latest/blog/2020/large-scale-security-policy-performance-tests/
In which we compare the performance results of mtls vs. plaintext that you can reference to. Thanks!

**Comment by kentchenjh** [comment]
appreciate it! that's what I need.
