### ISSUE TITLE
istioctl ps fails when running on central Istiod single cluster scenario

### ISSUE THREAD

**Issue by irisdingbj** [istio/istio#26208]
```
istioctl ps helloworld-v2-776f74c475-49zg9.iris
Error: unable to find any Pilot instances
```

**Comment by irisdingbj** [comment]
@esnible @linsun

**Comment by linsun** [comment]
@therealmitchconnors do you know if the steps are documented?  I think Ed may still not have power yet.

**Comment by esnible** [comment]
My power came back!

@irisdingbj `istioctl ps` does the equivalent of `kubectl -n istio-system get pods --selector app=istiod --field-selector status.phase=Running`.  Do you see any pods for that query?

**Comment by kasarpolis** [comment]
I have the same problem.  Running `kubectl -n istio-system get pods --selector app=istiod --field-selector status.phase=Running` yields no pods due to the lack of a `app=istiod` label.

**Comment by esnible** [comment]
@kasarpolis my Istiod pods have

```
  labels:
    app: istiod
    istio: pilot
    istio.io/rev: default
    pod-template-hash: 6847d9bff
```

What do your pods have?  What does `istioctl version` show for you?
