### ISSUE TITLE
`upx --brute` can get a smaller binary

### ISSUE THREAD

**Issue by liuzheng** [istio/istio#26214]
```
istio/pilot/cmd/pilot-discovery(git:master)$ ll
total 256072
-rwxr-xr-x  1 liu_zheng  staff  111728788 Aug  6 17:33 main*
-rwxr-xr-x  1 liu_zheng  staff   15773712 Aug  6 17:36 main-strip*
-rw-r--r--  1 liu_zheng  staff       9690 Aug  6 17:02 main.go
-rw-r--r--  1 liu_zheng  staff       1276 Aug  6 17:02 request.go
```

**Describe the feature request**

**Describe alternatives you've considered**

[ ] Docs
[ ] Installation
[ ] Networking
[X] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
This has an impact on the startup performance and build times. I am against this. I suggest we take the same direction of our neighboring projects:
https://github.com/kubernetes/kubernetes/pull/28265#issuecomment-230375578
https://github.com/jaegertracing/jaeger/issues/1089

**Comment by ericvn** [comment]
I'm not for doing this as we have found occasions where running upx on a binary has made it so things segfault right away. Granted, we have tests so would find this right away, but would take time to debug and fix the failure or turn off upx at that point.

**Comment by ericvn** [comment]
We aren't going to do this.
