### ISSUE TITLE
In master branch , can't use mosn as sidecar without modification

### ISSUE THREAD

**Issue by pantianying** [istio/istio#26215]
**Bug description**
Through the documents on the official website, I know that isto can use sidecar other than envoy, and I will follow the instructions as follows：
build istio like that
` ISTIO_ENVOY_VERSION=v0.13.0 ISTIO_ENVOY_RELEASE_URL=https://github.com/GLYASAI/mosn/releases/download/0.13.0/mosn.tgz ISTIO_ENVOY_MACOS_RELEASE_URL=https://github.com/GLYASAI/mosn/releases/download/0.13.0/mosn-macos.tar.gz ISTIO_ENVOY_MACOS_RELEASE_NAME=mosn-0.13.0 SIDECAR=mosn make docker.proxyv2`
get error :
![image](https://user-images.githubusercontent.com/20589945/89525718-34cf3c00-d819-11ea-858c-11e4d3e30f34.png)

What are these. Wasm files for ？

I think this kind of operation will deepen the coupling between istio and sidecar.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[X] Developer Infrastructure

**Expected behavior**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
in the master code

**Comment by pantianying** [comment]
In addition, I would like to ask if there is any way to bypass this

**Comment by howardjohn** [comment]
Please open MOSN issues on https://github.com/mosn/mosn, it is not officially supported by Istio.

But that looks like a curl request is failing ,maybe you have some firewall blocking it or something

**Comment by xieziqiang** [comment]
I have the same problem. How did you solve it?
