### ISSUE TITLE
Add structured output for `istioctl x precheck` and `istioctl verify-install`

### ISSUE THREAD

**Issue by niwatorrri** [istio/istio#26220]
This is part of the effort for [unifying istioctl command output](https://docs.google.com/document/d/1_m3PRHjbSFy6NAOk4C4CvCu93q-QKRsW7WaiaY9Z1DQ/edit?usp=sharing).

Currently `istioctl x precheck` and `istioctl verify-install` print everything directly to the console and the output is hardly machine readable. We'd like to see structured output supported for these two commands in a way similar to `istioctl analyze`. This can be done by converting these direct output to Message objects (whose type is defined in `galley/pkg/config/analysis/diag`) and using standardized message formatting functions recently added to the package `istioctl/pkg/util/formatting` (related PR #25996).

PR #26218 is an initial attempt for precheck. A couple of things in the PR that might need some iterations:

- Newly added new message codes
  - A new code is added for precheck. Its name is "PrecheckFailed" temporarily and could use some improvement.
  - It's also possibly necessary to break it into separate codes, partly for potential reuse (?) and partly because not all messages might be of the same severity level.
- For each Message object there's an optional Resource field. We might want to fill this field in some cases and leave it empty otherwise.
- Agree on which are exceptions (non-zero exit codes) and which are messages. This is also related to the mock tests to be described later.
  - Previously anything that went wrong would count as an exception, but now we might want to see some of them as error messages instead. We should consider this from the perspective of what a post-processing tool would expect from the command.
  - As two examples, in the PR "failed to query the Kubernetes API Server" is now recognized as an exception, while "Kubernetes cluster deployed without MutatingAdmissionWebhook support" is produced as a message.
- Modify and/or expand the mock tests in `pre-check_test.go`
  - These tests were limited to checking whether an exception occurred. We might want to modify them to check the exact output from the command (including exceptions and messages), especially since we are now supporting json and yaml output formats.
  - Specific checks could include: if the number of messages returned is correct, if the content of these messages are correct, if a valid output is always produced whenever the command exits with code 0, if the json format is working properly, etc.

PR #26219 is an initial attempt for verify-install. Items listed above should be similarly considered for this PR as well.

**Comment by niwatorrri** [comment]
cc @maasen @jasonwzm @nmittler @davidhauck

**Comment by esnible** [comment]
@jasonwzm What priority do you want for this?  We put it as P1? on our roadmap.

**Comment by jasonwzm** [comment]
> @jasonwzm What priority do you want for this? We put it as P1 on our roadmap.

P1 is fine.

**Comment by esnible** [comment]
There is a new issue -- https://github.com/istio/istio/issues/28915 precheck analyzer .  It might be worthwhile to see what the current `istioctl precheck` does and move that code into the analyzer, then make `istioctl precheck` a facade for `istioctl analyze` that suppresses all but precheck related things.

Maybe not ... I am not sure if the things like Kubernetes version that `precheck` does can be rolled into an analyzer.

**Comment by esnible** [comment]
@jasonwzm Should we retarget for 1.10?

**Comment by esnible** [comment]
@jasonwzm Should we retarget for 1.11?
