### ISSUE TITLE
'istioctl dataplane namespace add'

### ISSUE THREAD

**Issue by esnible** [istio/istio#26267]
Users don't know which namespaces are configured for Istio or how to set them up for Istio.

@linsun points out that OSM solves it using `osm add namespace` cmd.  e.g.
```
$ bin/osm namespace add bookstore   
Namespace [bookstore] succesfully added to mesh [osm]
```

Commands to enable and list namespaces would help Istio, especially for users who did not install or adminster the control plane.

We probably need a `--revision` flag to deal with canary control planes.

Taking suggestions as to the syntax.

As part of this work the `istioctl analyze` message that tells users to do `kubectl lable ns ...` should also be changed.

**Comment by howardjohn** [comment]
Lets please note get too inspired by other meshes :slightly_smiling_face:. Its a label... everyone using kubernetes understands labels. Lets not take something so simple that everyone understands and somehow make it more complicated and abstracted.

**Comment by howardjohn** [comment]
Suggestions for syntax:
`kubectl label ns istio-injection=enabled`, `kubectl get ns -l istio-injection=enabled`
