### ISSUE TITLE
Istio-v1.4.3: Re-deploy the deployment, Envoy proxy is NOT ready 

### ISSUE THREAD

**Issue by herbguo** [istio/istio#26261]
Hello, everyone,

I have a Istio runtime problem. The version is 1.4.3
when I re-deploy my deployment ,the istio-proxy is not run successfully,the log is show : Envoy proxy is NOT ready
The detail log is :

> [Envoy (Epoch 0)] [2020-08-07 08:55:23.138][21][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:91] gRPC config stream closed: 14, upstream connect error or disconnect/reset before headers. reset reason: connection failure
2020-08-07T08:55:31.016496Z	info	Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 0 successful, 0 rejected; lds updates: 0 successful, 0 rejected
[Envoy (Epoch 0)] [2020-08-07 08:55:36.704][21][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:91] gRPC config stream closed: 14, upstream connect error or disconnect/reset before headers. reset reason: connection failure
2020-08-07T08:55:41.016294Z	info	Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 0 successful, 0 rejected; lds updates: 0 successful, 0 rejected

I saw the kube-dns VIP and the istio-proxy  /etc/resolv.conf file .

> root@asd-646dc78bf-n96s6:/# cat /etc/resolv.conf 
nameserver 11.254.0.10
search istio-system.svc.cluster.local svc.cluster.local cluster.local
options ndots:5

>[deployer@05g19m3219 ~]$ kubectl get svc -n kube-system
NAME             TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                  AGE
kube-dns         ClusterIP   11.254.0.10      <none>        53/UDP,53/TCP,9153/TCP   106d

It's the the same ip .

when i see the istio proxy-status, It's show:
>[deployer@05g19m3219 ~]$ istioctl ps |  grep asd
asd-bc7db84d6-78wp4.istio-system                                       SYNCED     SYNCED     SYNCED     SYNCED     istio-pilot-6c59f986d7-n2jtf     1.4.3

From the commad，It's the old pod, the new pod is not show , I think the pilot is not communicated with the new pod.

I have no idea what to do,please help me, thanks!

**Comment by howardjohn** [comment]
https://istio.io/latest/news/support/announcing-1.4-eol-final/

Please upgrade, this code has change substantially. If you still see the issue on newer versions we can investigate

**Comment by herbguo** [comment]
> https://istio.io/latest/news/support/announcing-1.4-eol-final/
> 
> Please upgrade, this code has change substantially. If you still see the issue on newer versions we can investigate

ok，thanks!
