### ISSUE TITLE
TestMeshNetworking unit test is Flaky

### ISSUE THREAD

**Issue by nschhina** [istio/istio#26287]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/26224/unit-tests_istio/18457

**Comment by nschhina** [comment]
cc: @stevenctl

**Comment by stevenctl** [comment]
Looks like a real race during kube controller's first `Run` that calls reload, then the handler on meshNetworks watcher. Fix here: https://github.com/istio/istio/pull/26290
