### ISSUE TITLE
Helmetize the addons for a complete Helm-native experience with Istio

### ISSUE THREAD

**Issue by sdake** [istio/istio#2629]
The helm charts are off to a great start thanks to the work of @sbezverk and @luisyonaldo and many reviewers in the community as well as a few other folks.  Could one or both of you work on adding the addons to the existing Helm charts?  There are no special ordering requirements on the addons that I am aware of.  I have launched them hundreds of times without ordering constraints using a bash script with no synchronization.
```

**Comment by linsun** [comment]
+1, yes, there is no specific ordering, this will be good to have.  Please be aware of some pending changes I have in https://github.com/istio/istio/pull/2557 which I'm trying to get it in asap.

**Comment by luisyonaldo** [comment]
I'll do it, but before that I'm working on a PR to standardize the chart and follow best practice to be able to do stuff like have multiple istio installation releases using the same chart (with current chart is not possible). After that I'll work with the add-ons. Community did a good work with the chart in the kubernetes incubator repo, so I'll take the add-on installation from there and adapt it to the chart.

**Comment by luisyonaldo** [comment]
Btw, did you guys plan to also host the charts as repo? So people can just add your istio helm repo and install istio without needing to pull the repo.

**Comment by linsun** [comment]
Thank you @luisyonaldo! your priority order sounds good.  We should look into host the charts in public repo, which I would really like to see after we straight out the version issue.

**Comment by sdake** [comment]
@luisyonaldo sounds good thanks for the commitment!  Keep in mind Istio 0.5 release is Jan 27th, so if you can't make that deadline, please LMK and I'll push out the target to 0.6.

Cheers
-steve

**Comment by sdake** [comment]
Would folks interested in this work (@sbezverk @luisyonaldo @linsun) review: https://github.com/istio/istio/issues/2630

I'd like to get some basic documentation merged first, and iterate after the adodns are sorted out.

Cheers
-steve

**Comment by luisyonaldo** [comment]
https://github.com/istio/istio/pull/2734

**Comment by sdake** [comment]
add-ons merged.
