### ISSUE TITLE
Consolidate and fix VM docs

### ISSUE THREAD

**Issue by jasonwzm** [istio/istio#26294]
We currently have 3 instructions on setting up VM:
https://preliminary.istio.io/latest/docs/setup/install/virtual-machine
https://preliminary.istio.io/latest/docs/examples/virtual-machines/single-network/
https://preliminary.istio.io/latest/docs/examples/virtual-machines/multi-network/

The setup is mostly identical and which should consolidate.

Also, none of the docs mentions instructions on relying on CSR to retrieve cert chain and key.

**Comment by JimmyCYJ** [comment]
@williamaronli please cover the support for cert rotation using existing cert in this user guide.

**Comment by JimmyCYJ** [comment]
@jasonwzm @williamaronli could you fix this issue as well? https://github.com/istio/istio.io/issues/7855
