### ISSUE TITLE
Integration Tests for Trust Domain Validation

### ISSUE THREAD

**Issue by nschhina** [istio/istio#26292]
Test Plan: https://docs.google.com/document/d/1FBwpRCNwABrr30vnzmt403tg7OPvQXaBs_S27DadGJU/edit?ts=5f2a55a0

Feature: https://github.com/istio/istio/pull/26224

Feature Design Doc: https://docs.google.com/document/d/1yfYFp2Pw3-pPACYGRWQQdrEtroAunCD3fjOF9ZGtcrU/edit#heading=h.n7k4m7emxj5z

**Comment by nschhina** [comment]
cc: @JimmyCYJ

**Comment by su225** [comment]
Can I pick this one?

**Comment by nschhina** [comment]
@su225 sure. This is a time critical requirement as we want to ensure this feature doesn't break anything. I'll be happy to work with you on this

**Comment by su225** [comment]
Oops. Sorry. I didn't know it was time critical. As I don't work full time, it may not be possible. I could work on parts which are not time-critical
