### ISSUE TITLE
Establish a rotation for first level support/answer questions

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#263]
For instance questions coming on istio-users

It would be duplicate efforts if everyone looks and answers (though if whoever is "on call" doesn't know how to answer they can pass it to someone else by asking on slack for instance)

**Comment by ldemailly** [comment]
Responsibilities:	Monitor and answer, or find someone to answer user issues on:	
	Target SLA: <24h ideally <4h during business hours	
	Also update FAQ / knowledge base so recurring questions take less time	
		Git hub issues
		istio-users@ mailing list
		Stackoverflow
		Twitter
	If time is available, work on improving continuous integration / releng	

https://docs.google.com/spreadsheets/d/1FaHwPpad3F3hva2suJweNeTnocjKtLnbgLkyMRPzgUY/

Please take a look/comment:
cc @jasminejaksic @zinuga @mandarjog @andraxylia @geeknoid

**Comment by ldemailly** [comment]
cc @frankbu @rshriram for IBM

**Comment by ldemailly** [comment]
will get a list from ibm and make a random rotation, people can check /swap / avoid vacation conflicts etc

**Comment by rshriram** [comment]
done

**Comment by ldemailly** [comment]
it's not done, the xls hasn't been updated since Aug - @sakshigoel12 is going to make it a real rotation (including working with @linsun for the IBM ones)

ps: don't close issues I just updated without asking ;-)

**Comment by sakshigoel12** [comment]
We have started with the first round of rotation this week, and have a confirmed list from IBM to include in the rounds. I am closing this issue and will open one to monitor stability and progress under 0.3 milestone.

Please review doc for details. https://docs.google.com/document/d/1nlzp6iBYfJ7KBzSQvHUYUoFqHpYKTOmOFnlPnfP_Sjk/edit#heading=h.exdawkz2gwg5
