### ISSUE TITLE
how to build metadata-exchange-filter.wasm and stats-filter.wasm?

### ISSUE THREAD

**Issue by DrowringMan** [istio/istio#26306]
i build istio on arm64 plantform，now i lost  metadata-exchange-filter.wasm and stats-filter.wasm，how to build this binary？

**Comment by bianpengyuan** [comment]
Those wasm modules are built by `build_wasm` target: https://github.com/istio/proxy/blob/master/Makefile.core.mk#L79

To build all artifacts from istio/proxy repo, you can use `push_release` target: https://github.com/istio/proxy/blob/master/Makefile.core.mk#L165

I am going to close this issue. Please reopen if you have further question. thanks!

**Comment by omigafu** [comment]
@bianpengyuan why I built wasm modules by `make build_wasm`, the artifacts is `metadata-exchange.wasm` not `metadata-exchange-filter.wasm`. But **Dockerfile.proxyv2** need `metadata-exchange-filter.wasm`, need to rename `metadata-exchange.wasm` to `metadata-exchange-filter.wasm`?
I don't know how to do it
