### ISSUE TITLE
Headless service exposed at gateway fails

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#26313]
If headless service, we skip EDS update: https://github.com/istio/istio/blob/bae28dde42cf54e213d4c6bcd9c930f8d9ee60c4/pilot/pkg/serviceregistry/kube/controller/endpointsdiscovery.go#L66

For sidecar, we then make original_dst cluster: https://github.com/istio/istio/blob/a302195f151b478c2003b8aec1acca1e3f801959/pilot/pkg/networking/core/v1alpha3/listener.go#L1078.

For GW, we generate an empty EDS cluster. Original dst will not work on gw, since the dest will the gateway IP.

Instead we probably want to use EDS cluster at GW, so may just need to make sure we keep Endpointshards up to date with headless service info as well.

This also indicates a big coverage gap - I have been meaning to add more gateway testing.

cc @therealmitchconnors  - this is why you mattermost thing is broken
cc @hzxuzhonghu

**Comment by hzxuzhonghu** [comment]
Also note: if the headless service has sidecar injected, we need to set the tls explicitly

**Comment by hzxuzhonghu** [comment]
I think you linked the wrong code, here it is
https://github.com/istio/istio/blob/c5ad10c525289c1ed89458ea04776ad87755f6ef/pilot/pkg/networking/core/v1alpha3/cluster.go#L424-L433

**Comment by howardjohn** [comment]
Fixed by https://github.com/istio/istio/pull/27096
