### ISSUE TITLE
Istio VM based Installation Not Working

### ISSUE THREAD

**Issue by Murudkar** [istio/istio#26314]
**Bug description**

[x] Docs
[x] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Istioctl should show LDS / RDS to be synced , for a VM based installation ?

**Steps to reproduce the bug**
Istio-start.sh on centos7, Proxy starts with following Warnings 
`protobuf WARNING external/com_google_protobuf/src/google/protobuf/text_format.cc:1944] Proto type type.googleapis.com/istio.envoy.config.filter.http.alpn.v2alpha1.FilterConfig not found`

![image](https://user-images.githubusercontent.com/40064888/89754537-4e3ae700-daaa-11ea-9e09-42d3b612dc72.png)

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
client version: 1.6.7
control plane version: 1.6.7
data plane version: 1.6.7 (15 proxies), 1.6.4 (1 proxies),  (1 proxies)

**How was Istio installed?**
istioctl install

**Environment where bug was observed (cloud vendor, OS, etc)**
CentOS7

**Comment by howardjohn** [comment]
This sounds like the wrong envoy binary is running. Can you look at /usr/local/bin/envoy, maybe run `/usr/local/bin/envoy --version`?

**Comment by howardjohn** [comment]
also centos7 isn't supported, so hopefully that isn't the VM OS. Otherwise this won't work anyways

**Comment by Murudkar** [comment]
CentOS7 is the OS VM.

We wont be able to use .deb, we converted .deb to rpm
Got the required CentOS envoy binary to make it work. 

This is the version of envoy binary we have : 

version: 923c4111bb48405ac96ef050c4f59ebbad3d7761/1.14.4/clean-getenvoy-2aa564b-envoy/RELEASE/BoringSSL

**Comment by howardjohn** [comment]
Where did you get the envoy binary? it needs to be from istio/proxy not
upstream envoy

**Comment by Murudkar** [comment]
Pulling it this way, from which location should the envoy binary picked from?

sudo yum install -y yum-utils
sudo yum-config-manager --add-repo https://getenvoy.io/linux/centos/tetrate-getenvoy.repo
yum install getenvoy-envoy-1.14.4.p0.g923c411-1p67.g2aa564b

**Comment by howardjohn** [comment]
Like I mentioned, we do not currently support centOS 7 binaries. The binaries used with istio must be built from istio/proxy, and we do not produce centos7 compatible binaries. Only debian or centos8

**Comment by Murudkar** [comment]
We can try building istio proxy on Centos 8. Wanted to be sure this is the doc to follow for that  - https://github.com/linux-on-ibm-z/docs/wiki/Building-Istio-Proxy#32-build-istio-proxy 

Thank you.

**Comment by howardjohn** [comment]
The binaries we publish are already centos8 compatible. We also publish RPMs in 1.7+: https://gcsweb.istio.io/gcs/istio-release/releases/1.7.0-beta.2/rpm/. That doc is probably very outdated

**Comment by Murudkar** [comment]
Thank you , is there a timeframe for 1.7 getting released. 
We don't not see binaries(envoy binary) for centos8 for 1.6.7.

**Comment by howardjohn** [comment]
Istio 1.7 is published, as are the RPMs along with it, so I think this is fixed: https://gcsweb.istio.io/gcs/istio-release/releases/1.7.0/rpm/. Thanks!
