### ISSUE TITLE
Unable to use existing CA certificates

### ISSUE THREAD

**Issue by ranjb** [istio/istio#26328]
**Bug description**
Unable to use a custom root CA and certificates as documented [here](https://istio.io/latest/docs/tasks/security/cert-management/plugin-ca-cert/). This could be a blocker for multicluster deployments via replicated control planes where we need to use a common root CA. See [here](https://istio.io/latest/docs/setup/install/multicluster/gateways/)

[X ] Docs
[X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
We are able to use a common Root CA and generate intermediate CA certs for each Istio deployment per cluster

**Steps to reproduce the bug**
Generate custom self-signed root and intermediate CA or use the ones provided under sample/certs. All attempts resulted in the following error in istiod logs:
`grpc: Server.Serve failed to complete security handshake from "100.127.29.112:40076": remote error: tls: unknown certificate authority`

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
Istio 1.6.x

`Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.12", GitCommit:"e2a822d9f3c2fdb5c9bfbe64313cf9f657f0a725", GitTreeState:"clean", BuildDate:"2020-05-06T05:17:59Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.12", GitCommit:"e2a822d9f3c2fdb5c9bfbe64313cf9f657f0a725", GitTreeState:"clean", BuildDate:"2020-05-06T05:09:48Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}`

**How was Istio installed?**
Via standalone operator

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS, Kubernetes installed via kops running flatcar OS

**Comment by juanmanuel-tirado** [comment]
Maybe this is related with some of the issues I'm experiencing when installing 1.6.5 in a multicluster environment. By following the tutorial and creating the certificates using

`kubectl create secret generic cacerts -n istio-system \
    --from-file=samples/certs/ca-cert.pem \
    --from-file=samples/certs/ca-key.pem \
    --from-file=samples/certs/root-cert.pem \
    --from-file=samples/certs/cert-chain.pem`

It seems that the cacerts secret is not correctly read by the components. In find the following warning:
`2020-08-12T14:04:21.077762Z	warn	secretfetcher	failed load server cert/key pair from secret cacerts: server cert or private key is empty`

This is the certificate from the samples folder. I can check the content of the secret, and it is already there.

Any guidance would be appreciated.

**Comment by hendrikhalkow** [comment]
I can confirm that the same issue exists with 1.7.0 when you follow the guide for [multi-cluster deployment with replicated control planes](https://istio.io/latest/docs/setup/install/multicluster/gateways/). Any workaround?

**Comment by codeMonkeysBe** [comment]
Was encountering the same issue, and for me it seemed to be a problem with missing newlines at the end of each .pem file (at least for me it was). Apparently there is a bug that requires each pem file to end with a newline:

Also see https://github.com/istio/istio/issues/24609

You can debug as follows -> 
`
kubectl exec -n $YOURPOD -c istio-proxy -- curl 'localhost:15000/config_dump' 
`
This will output long json and in there is a `certificate_chain` key.

I decoded this one and saw 

`-----END CERTIFICATE----------BEGIN CERTIFICATE-----`

The cert chain seem to be re-created by concatenating the certs without a newline, so resulting in invalid formatted PEM. 

Strange thing is if I take a look at the  `sample/certs` they seem fine, so not sure @ranjb or @hendrikhalkow  problems will be solved by this.

**Comment by hendrikhalkow** [comment]
Still no success here. I created the certificates [as written in the documentation](https://istio.io/latest/docs/setup/install/multicluster/gateways/) like this:

```sh
kubectl create secret generic cacerts -n istio-system \
    --from-file=samples/certs/ca-cert.pem \
    --from-file=samples/certs/ca-key.pem \
    --from-file=samples/certs/root-cert.pem \
    --from-file=samples/certs/cert-chain.pem
```

The ingresssgateway pod yields the following error message:

```txt
server cert or private key is empty
```

There is [exactly one place in the Istio code](https://github.com/istio/istio/blob/1.7.0/security/pkg/nodeagent/secretfetcher/secretfetcher.go#L243) where this message appears. Obviously, [extractCertAndKey](https://github.com/istio/istio/blob/1.7.0/security/pkg/nodeagent/secretfetcher/secretfetcher.go#L172) does not return a certificate. This method tries to retrieve certificate from [other keys](https://github.com/istio/istio/blob/1.7.0/security/pkg/nodeagent/secretfetcher/secretfetcher.go#L40) than the files in the command above: `cert`, `key`, `cacert`, `tls.crt`, `tls.key` and `ca.crt`. I added all these keys to the `cacert` secret via `kubectl edit`, which made the error go away. However, cross-cluster communication still doesn't work:

```sh
curl -I httpbin.bar.global:8000/headers
HTTP/1.1 503 Service Unavailable
content-length: 91
content-type: text/plain
date: Fri, 04 Sep 2020 03:24:37 GMT
server: envoy
```

Trying to establish a TLS connection to the ingress gateway NLB:

```sh
openssl s_client -connect xxxxxxxxxxxx.elb.eu-central-1.amazonaws.com:15443
CONNECTED(00000003)
write:errno=104
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 289 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID:
    Session-ID-ctx:
    Master-Key:
    Key-Arg   : None
    Krb5 Principal: None
    PSK identity: None
    PSK identity hint: None
    Start Time: 1599189920
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
```

Any more ideas to diagnose what's wrong?

**Comment by cotej** [comment]
I'm also encountering this issue with Istio 1.7.5.  The strange part is, I'm pretty sure I did this exact same thing last week for some other clusters and it seemed to work just fine...

**Comment by ranjb** [comment]
@myidpt Would you have any feedback on this or is there any testing we can help with?
