### ISSUE TITLE
got error 503 - CERTIFICATE_VERIFY_FAILED - randomly after new deployments

### ISSUE THREAD

**Issue by 1hanymhajna** [istio/istio#26324]
We are running with istio 1.4.7, on EKS v1.15,
 suddenly we start to get error 503 with `CERTIFICATE_VERIFY_FAILED` error in the client-side, and after restarting the pilot or the citadel the problem resolved and the service come to be reachable, but when we run new deployment it reproduced again!

Verified the xDS and all look fine, the EDS look ok and all in sync,
is there any chance you face this problem before? why this happened, and how can we make sure that the issue not reproduced again? cause from k8s API the deployment look ok (active healthcheck pass) but once we try to send other requests (via istio) we got error 503

Please help cause it really blocking us...

istio sidecar log:
```
[Envoy (Epoch 0)] [2020-08-10 07:51:42.368][34][debug][pool] [external/envoy/source/common/http/http1/conn_pool.cc:95] creating a new connection
[Envoy (Epoch 0)] [2020-08-10 07:51:42.368][34][debug][client] [external/envoy/source/common/http/codec_client.cc:31] [C588988] connecting
[Envoy (Epoch 0)] [2020-08-10 07:51:42.368][34][debug][connection] [external/envoy/source/common/network/connection_impl.cc:718] [C588988] connecting to 10.28.10.212:8080
[Envoy (Epoch 0)] [2020-08-10 07:51:42.368][34][debug][connection] [external/envoy/source/common/network/connection_impl.cc:727] [C588988] connection in progress
[Envoy (Epoch 0)] [2020-08-10 07:51:42.368][34][debug][pool] [external/envoy/source/common/http/conn_pool_base.cc:20] queueing request due to no available connections
[Envoy (Epoch 0)] [2020-08-10 07:51:42.368][34][debug][http2] [external/envoy/source/common/http/http2/codec_impl.cc:742] [C6] stream closed: 0
[Envoy (Epoch 0)] [2020-08-10 07:51:42.368][34][debug][connection] [external/envoy/source/common/network/connection_impl.cc:566] [C588988] connected
[Envoy (Epoch 0)] [2020-08-10 07:51:42.368][34][debug][connection] [external/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc:191] [C588988] handshake expecting read
[Envoy (Epoch 0)] [2020-08-10 07:51:42.370][34][debug][connection] [external/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc:198] [C588988] handshake error: 1
[Envoy (Epoch 0)] [2020-08-10 07:51:42.370][34][debug][connection] [external/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc:226] [C588988] TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
[Envoy (Epoch 0)] [2020-08-10 07:51:42.370][34][debug][connection] [external/envoy/source/common/network/connection_impl.cc:193] [C588988] closing socket: 0
[Envoy (Epoch 0)] [2020-08-10 07:51:42.370][34][debug][client] [external/envoy/source/common/http/codec_client.cc:88] [C588988] disconnect. resetting 0 pending requests
[Envoy (Epoch 0)] [2020-08-10 07:51:42.370][34][debug][pool] [external/envoy/source/common/http/http1/conn_pool.cc:136] [C588988] client disconnected, failure reason: TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
[Envoy (Epoch 0)] [2020-08-10 07:51:42.370][34][debug][pool] [external/envoy/source/common/http/http1/conn_pool.cc:167] [C588988] purge pending, failure reason: TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
[Envoy (Epoch 0)] [2020-08-10 07:51:42.370][34][debug][router] [external/envoy/source/common/router/router.cc:911] [C588982][S7458161559789993786] upstream reset: reset reason connection failure
[Envoy (Epoch 0)] [2020-08-10 07:51:42.370][34][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:1354] [C588982][S7458161559789993786] Sending local reply with details upstream_reset_before_response_started{connection failure,TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED}
[Envoy (Epoch 0)] [2020-08-10 07:51:42.370][34][debug][filter] [src/envoy/http/mixer/filter.cc:135] Called Mixer::Filter : encodeHeaders 2
[Envoy (Epoch 0)] [2020-08-10 07:51:42.370][34][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:1552] [C588982][S7458161559789993786] encoding headers via codec (end_stream=false):
':status', '503'
'content-length', '91'
'content-type', 'text/plain'
'date', 'Mon, 10 Aug 2020 07:51:41 GMT'
'server', 'istio-envoy'
```

pilot logs look ok, nothing special there

**Comment by christian-posta** [comment]
I would suggest compare the trusted certificates for the sidecar with the root CA for Istio citadel. You can grab the certs from the sidecar by hitting the `localhost:15000/certs` endpoint in the istio-proxy container

**Comment by 1hanymhajna** [comment]
Verified again the EDS table and look ok
```
ENDPOINT             STATUS      OUTLIER CHECK     CLUSTER
10.28.21.51:8080     HEALTHY     OK                outbound|80||my-bad-service.my-namespace.svc.cluster.local
```

@christian-posta verified that the client and the service have the same root CA as expected, I think it the same for citadel as well , ill verify it

**Comment by 1hanymhajna** [comment]
one more interesting things is when call pilot debug endpoint from the any sidecar in the cluster, i got this error:
```
istio-proxy@httpbin-7dc998658b-hg4lx:/$ curl -k --cert /etc/certs/cert-chain.pem --cacert /etc/certs/root-cert.pem --key /etc/certs/key.pem https://istio-pilot.istio-system:8080/debug/edsz
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
```

**Comment by jacob-koren-zooz** [comment]
We sniffed the tls handshake while making a request to this service, the client hello and server hello looks o.k., but the response to "server hello" is **"Certificate unknown"**.
For some reason, this service account is unknown in the mesh.

**Comment by 1hanymhajna** [comment]
- Entering into the istio sidecar container of a test pod, and making a mtls request with curl to the risk-live-payu pod works 
- Making the same call from the application container of the same pod doesn’t work and wireshark shows “unknown certificate”

The first conclusion we have is that the certificate is o.k. and passed correctly

**Comment by 1hanymhajna** [comment]
Is there anyway to know what is the secure naming map the pod got from the pilot? can we debug it?

**Comment by 1hanymhajna** [comment]
We found the main reason for why this happened, 
This is the scenario to reproduce it:
pre: create service and connect it to a pod
1: take a POD with service account: SA_1
2: redeploy it again but with different service account: SA_2

When we change the service account(SA_2) without changing the service name itself, the secure naming does not been pushed to the envoys although it has been changed, 
 
in the cluster discovery service (CDS) we saw that the spiffy value ( secure naming) still with the old value (SA_1) and this cause to handshake error and got error 503
The interesting thing is if we deployed the pods again with (SA_3) service account, it got the second service account spiffe value (SA_2), this means that the pilot already have the updated data, but not push them to the envoys as expected and keep them with wrong values

The best workaround we found is to create new service and this triggers the pilot to push the xDS tables to all the envoys with the correct values

**Comment by howardjohn** [comment]
@1hanymhajna thanks for the discovery!

@incfly this is on 1.4. I tested on master and it works. Do we have tests for this type of thing? If so, I think we can close?

**Comment by FENGXIANGLI** [comment]
@howardjohn you mean this is worked on 1.4? @howardjohn is his workaround ok to do the fix? or do we need to do any code change to mitigate this case?

**Comment by FENGXIANGLI** [comment]
need to add some tests to cover it.

**Comment by williamaronli** [comment]
@howardjohn you mean this is worked on 1.4? @howardjohn is his workaround ok to do the fix? or do we need to do any code change to mitigate this case?

need to add some tests to cover it.

**Comment by williamaronli** [comment]
@myidpt could you take a look ? which kind of test we need to add to cover this case?

**Comment by howardjohn** [comment]
I was unable to reproduce on multiple versions I tried. Since this was reported for a version far out of support (https://istio.io/latest/about/supported-releases/) I am assuming this has been fixed since then. if you see this on a recent version please do not hesitate to reopen/open a new issue. Thanks!

**Comment by SebTardif** [comment]
It's happening on:
control plane version: 1.12.5
data plane version: 1.12.5 (18 proxies)

**Comment by Jeskz0rd** [comment]
I can also confirm it is happening with `1.12.5-asm.0`.

**Comment by cacarico** [comment]
Same problem with `1.11.4`.

**Comment by neighbour-oldhuang** [comment]
v1.13.3  +1

**Comment by jangrewe** [comment]
Seeing this after updating from `1.12.6` to `1.12.8`.

**Comment by dimitarshenkov** [comment]
here with 1.14.2

**Comment by up-to-you** [comment]
Confirm with 1.14.3

**Comment by the-xentropy** [comment]
I fixed this by installing the CNI (sidecars were not working properly for me) and following the additional config instructions at https://ranchermanager.docs.rancher.com/integrations-in-rancher/istio/configuration-options/install-istio-on-rke2-cluster . I'm running k3s, and all my nodes are ubuntu.
