### ISSUE TITLE
Mixer CRD "kind" should be CamelCase

### ISSUE THREAD

**Issue by liminw** [istio/istio#2633]
Currently Kubernetes and Pilot use CamelCase for CRD kind. For example, 
* Kubernetes has "RoleBinding", "ClusterRole".
* Pilot has "RouteRule".

But Mixer uses lower case for CRD kind. For example, "attributemanifest", "listchecker". We need to fix the inconsistency.

**Comment by liminw** [comment]
cc @kyessenov @mandarjog @douglas-reid

**Comment by douglas-reid** [comment]
i believe we are heading in a different direction now for CRDs for Mixer. Closing for now.
