### ISSUE TITLE
use a label to set cluster for Pods

### ISSUE THREAD

**Issue by stevenctl** [istio/istio#26333]
**Describe the feature request**

Rather than relying on the clusterID set by in the kube controller (we usually get this from the Secret), pods could have the cluster ID injected as a label, along side the proxy meta. We'd be able to clean up a lot of code where this clusterID property of the kube service registry is used.

https://github.com/istio/istio/blob/1c7c2f1b020ae21188445e4c812f01c971a554af/pilot/pkg/xds/eds.go#L125-L126

https://github.com/istio/istio/blob/afa883b506b2684340418339b5af6ada5279e337/pilot/pkg/serviceregistry/kube/controller/pod.go#L205

Questions:
- If we were to purely rely on the label, this would affect non-injected pods? 
- Does this help with Services and Endpoints? Will we still need the registry-level clusterID? 

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

https://github.com/istio/istio/pull/25554 does something similar for Network

cc @nmittler @tbarrella

**Comment by tbarrella** [comment]
After discussing, it seems like we'd want to close this... the cluster a pod runs on must be known to be able to read the label. While this could make some code more convenient, it doesn't seem to be worth the denormalization and extra API surface area
