### ISSUE TITLE
istio-proxy Envoy use too much memory, make exportTo support envoy cluster

### ISSUE THREAD

**Issue by liuzheng** [istio/istio#26350]
**Describe the feature request**
`exportTo` can support envoy cluster.

**Describe alternatives you've considered**
As my test thousands of `VirtualService` and `ServiceEntry` configurations, Envoy use too much memory.
In common case, one pod does not need the hole configurations(I know Use namespace and Sidecar to split, but still have that case).
I found `exportTo` in `VirtualService` and `ServiceEntry` and `--serviceCluster` in sidecar start command many can solve my case. I want export some config to the specified envoy cluster.

Now `exportTo` only support namespace, I already edit source code let it support `.`, so I can set `myapp.mynamespace`.
The configmap `istio-sidecar-injector`
```
        - --serviceCluster
        {{ if ne "" (index .ObjectMeta.Labels "app") -}}
        - "{{ index .ObjectMeta.Labels `app` }}.$(POD_NAMESPACE)"
        {{ else -}}
        - "{{ valueOrDefault .DeploymentMeta.Name `istio-proxy` }}.{{ valueOrDefault .DeploymentMeta.Namespace `default` }}"
        {{ end -}}
```
So I defined my deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: mynamespace
spec:
  template:
    metadata:
      labels:
        app: myapp
...
```

I'm new in istio develop, so next is find where to select the configuations by cluster.

What you think that feature?

[ ] Docs
[ ] Installation
[ ] Networking
[X] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by liuzheng** [comment]
I read the code, and found in current design, this feature may not easy to come true.

**Comment by howardjohn** [comment]
I don't understand what you want to scope

> (I know Use namespace and Sidecar to split, but still have that case

Why does this not cover your use case?

**Comment by liuzheng** [comment]
We have tens of thousands of apps in one namespace(by design, there have dozens of namespace, the big one is for app services), it will have at least thousands of outbound rules, tens of thousands of inbound rules.
Each app may have many different inbound and outboud rules.

**Comment by howardjohn** [comment]
Sidecar allows explicitly selecting certain hostnames, it's not just namespace level

**Comment by liuzheng** [comment]
Thanks, I found the solution, I am misunderstood the `Sidecar`
