### ISSUE TITLE
istioctl plugin system

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#26377]
istioctl should support a plugin system like kubectl plugin https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/
This gives us a way to deploy vendor specific extensions using the same look and feel as istioctl. 

Use case
Google needs to have an extension to istioctl that interacts with google metrics system, it would be great to not put it in the istioctl binary.

**Comment by mandarjog** [comment]
cc @esnible

**Comment by ostromart** [comment]
I recently discussed a plugin format for istioctl install/manifest with @richardwxn - at least for that part we have a pretty good idea what would make sense. Not sure how that might fit in though into a more general plugin framework.
