### ISSUE TITLE
Author should be apply to apply release-notes-none tag on PR

### ISSUE THREAD

**Issue by nikita15p** [istio/istio#26375]
**Describe the feature request**
Apply label to be enabled for authors to prevent test failure eg for release-notes-none
**Describe alternatives you've considered**
Checked the documentation, but could not find a way where any author can apply label.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ X] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
You will need to join the org: github.com/istio/community

Users not in the org will not have access to any labels

**Comment by nikita15p** [comment]
@howardjohn I have raised the PR https://github.com/istio/community/pull/393. Can u please have a look.

**Comment by nikita15p** [comment]
Also I expected this to happen seamless for contributors for better experience.
eg istio-policy-bot should reply with "You will need to join the org: github.com/istio/community" similar to cla case i.e. It replies with  '📝 Please visit https://cla.developers.google.com/ to sign.'

**Comment by howardjohn** [comment]
It is *intended* that only developers who have been explicitly trusted can
set the label. Only these set of developers are able to make the judgement
call if a PR needs a release note or not. Note this should not obstruct you
in any way -  you need those same set of developers to approve your PR
anyways.

**Comment by nikita15p** [comment]
@howardjohn Thanks . I would expect bot to add default reviewers because new contributors may have to spend some time in looking for reviewers.

**Comment by howardjohn** [comment]
It will automatically assign reviewers based on the CODEOWNERs file

**Comment by howardjohn** [comment]
We added an option to the template, users can add `[X]` next to it and automatically add this, even when not in the org.
