### ISSUE TITLE
EnvoyFilter CRD definition confusion

### ISSUE THREAD

**Issue by eddycharly** [istio/istio#26410]
When comparing istio 1.2 and istio 1.6 definitions of the `EnvoyFilter` CRD:
- https://archive.istio.io/v1.2/docs/reference/config/networking/v1alpha3/envoy-filter/
- https://istio.io/latest/docs/reference/config/networking/envoy-filter/

They look quite different (`workloadLabels` vs `workloadSelector`, `filters` vs `configPatches`, etc..) though both use `apiVersion: networking.istio.io/v1alpha3` and `kind: EnvoyFilter`.

Is there some conversion involved somehow ? Or did the CRD changed without changing the GVK ?

Hope i'm not missing something obvious here as i feel a bit lost.

**Comment by howardjohn** [comment]
> Is there some conversion involved somehow ? Or did the CRD changed without changing the GVK ?

The latter - at the time we didn't have the infrastructure in place for multi version support unfortunately so made backwards incompatible changes and deprecated the old fields over a few releases

**Comment by eddycharly** [comment]
Ok, thanks. At least it explains the inconsistencies i observed. It would be nice to add a note in the docs too.

Is there something in place to take care of conversion now or is this going to happen again with upcoming releases ?

**Comment by howardjohn** [comment]
@eddycharly the old apis were deprecated over a year ago - there will definitely be no changes in this area in any upcoming releases
