### ISSUE TITLE
needs log summarization/highlights for our tests

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#2643]
When test (like pilot e2e) fail on circle ci the logs are unusable:

"Your build output is too large to display in the browser. Only the first 400000 characters are displayed."

for instance fro https://circleci.com/gh/istio/istio/16920

prow for instance highlights errors and skips sections without errors in the log to attempt to keep things readable/scrollable

cc @sebastienvas

**Comment by rshriram** [comment]
I am sorry, this is something we don't have control over,  to fix. The UI is owned by circleci. So fancy highlighting is out of scope. 

And as costin says, log summarization is not supported by Prow either. It just picks bits and pieces of logs that say error and spews them. That is not really summarizing. In fact, I could log the same issue for Prow :).

What we need is discipline to cut down the excessive logging we do in tests, and ensure that test output is easily decipherable when someone eyeballs over the output. This has the benefit of being universally applicable across all CI systems.

**Comment by ldemailly** [comment]
updating the subject, pilot-e2e tests are quite unusable it'd be nice to put a summary on circleci and the rest as artifact

**Comment by ldemailly** [comment]
still a problem, eg https://circleci.com/gh/istio/istio/64507
(on the other hand builds like https://circleci.com/gh/istio/istio/64510 report errors better so it's doable)

**Comment by hklai** [comment]
@nmittler, is it e2e-pilot specific?

**Comment by hklai** [comment]
@nmittler  Both https://circleci.com/gh/istio/istio/64510 (racetests) and https://circleci.com/gh/istio/istio/64507 (e2e-pilot) have over 400000 characters of log data.

However, racetests shows a useful test summary on the top, while e2e-pilot shows an empty test summary with a set up button. I assumed that was what @ldemailly meant by one reports errors better.

**Comment by nmittler** [comment]
Given that work is under way for a new test framework, I don't think any action will be taken at this time.  Closing this issue.

**Comment by ldemailly** [comment]
sounds good, but will the new framework address the issue? (of both having detailed logging when needed as well as fast way to pin point failure)

**Comment by nmittler** [comment]
It will have to. If it doesn't, this will continue to be a problem and will be addressed separately for the new framework.
