### ISSUE TITLE
bug (istio-operator): revisioned IstioOperator resources affect non-control-plane resources

### ISSUE THREAD

**Issue by vito-laurenza-zocdoc** [istio/istio#26443]
**Bug description**

When creating, updating, or deleting an `IstioOperator` resource with a `revision`, non-control-plane and non-revisioned resources are affected, e.g. ingressgateways are upgraded/downgraded/deleted

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Expected behavior**

`IstioOperator` resources with a `revision` should only install/manage control-plane resources, not the entire Istio installation.

**Steps to reproduce the bug**

```bash
istioctl install --set tag=1.5.8

istioctl operator init

kubectl apply -f - <<EOF
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: canary-control-plane
spec:
  profile: default
  revision: canary
EOF

# wait for istio-operator to finish reconciling

# notice that the ingressgateway deployment was updated to 1.6.8

kubectl -n istio-system delete istiooperator canary-control-plane

# wait for istio-operator to finish reconciling

# notice that the ingressgateway deployment and pods were deleted

```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
$ istioctl version --remote
client version: 1.6.8
pilot version: 1.5.8
pilot version: 1.5.8
istiod version: 1.6.8
data plane version: 1.6.8 (1 proxies)

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-26T06:17:09Z", GoVersion:"go1.14", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-30T20:19:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by vito-laurenza-zocdoc** [comment]
I now realize that a more correct way to create a canary control plane is with the following config:

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: canary-control-plane
spec:
  profile: empty
  revision: canary
  components:
    pilot:
      enabled: true
```

Instructing the operator to only manage the pilot resources creates a more true canary as it doesn't affect any existing installed resources. If the documentation was more specific in this regard it would have prevented a lot of trial and error on my part.

**Comment by shamsher31** [comment]
https://istio.io/latest/docs/setup/upgrade/#data-plane
> Unlike istiod, Istio gateways do not run revision-specific instances but are instead in-place upgraded to use the new control plane revision. 

I think this indicates what you are looking for, but I agree docs should provide more details and examples like you tried https://github.com/istio/istio/issues/26443#issuecomment-673612789

cc: @istio/wg-docs-maintainers

**Comment by vito-laurenza-zocdoc** [comment]
@shamsher31 thanks, I fully understand now. The issue that led to my misunderstanding was that on the 1.6 version of that page, there is no mention of the gateways: https://istio.io/v1.6/docs/setup/upgrade/#data-plane

**Comment by vito-laurenza-zocdoc** [comment]
I still think it's probably worth calling out in the documentation that you can create a revisioned `IstioOperator` from the `empty` profile which only installs the `pilot` component to achieve a true touches-the-control-plane-only revision.

**Comment by shamsher31** [comment]
> I still think it's probably worth calling out in the documentation that you can create a revisioned `IstioOperator` from the `empty` profile which only installs the `pilot` component to achieve a true touches-the-control-plane-only revision.

@istio/wg-docs-maintainers PTAL.

**Comment by frankbu** [comment]
Here's the current recommended way to handle this issue: https://preliminary.istio.io/latest/docs/setup/upgrade/gateways/

**Comment by vito-laurenza-zocdoc** [comment]
@frankbu that's excellent, thanks!
