### ISSUE TITLE
Istio1.6 - Kube-APIServer Requests from Pod with SidecarInjection doesn't work on Azure AKS

### ISSUE THREAD

**Issue by Crazyigor1987** [istio/istio#26448]
I've installed Istio1.6 on Azure using AKS. My deployed pod with enabled Istio Sidecar is not able to communicate to the kube-apiserver service. In this case, i cannot operate prometheus-operator with istio-sidecar enabled. On other Kubernetes Plattforms like Rancher, it works like a charm.

BADCASE on Azure AKS
```

root@webserver-versions-deployment-5947799c56-p2tkz:/# curl --cacert /run/secrets/kubernetes.io/serviceaccount/ca.crt https://kubernetes.default.svc.cluster.local/version
curl: (35) gnutls_handshake() failed: The TLS connection was non-properly terminated.




ISTIO-PROXY LOG ENTRY
[2020-08-12T11:36:58.829Z] "- - -" 0 UH "-" "-" 0 0 0 - "-" "-" "-" "-" "-" - - 10.0.0.1:443 10.240.0.138:39526 - -

```

GOODCASE on RANCHER RKE (Baremetal):
```

root@webserver-versions-deployment-57d4856c97-46br5:/# curl --cacert /run/secrets/kubernetes.io/serviceaccount/ca.crt https://kubernetes.default.svc.cluster.local/version
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}


ISTIO-PROXY LOG ENTRY
[2020-08-12T22:12:17.558Z] "- - -" 0 - "-" "-" 597 2019 405 - "-" "-" "-" "-" "10.5.2.21:6443" outbound|443||kubernetes.default.svc.cluster.local 10.42.9.152:43240 10.43.0.1:443 10.42.9.152:51644 - -

```

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

Install Kubernetes 1.15 on AZURE AKS + Istio 1.6. Create Namespace with automatic Sidecar Injection and run a pod. Try Access to kube-api service.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
IstioCTL
client version: 1.6.6
control plane version: 1.6.6
data plane version: 1.6.6 (21 proxies)

kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.10", GitCommit:"ba1ce4122d67b0f7399a41afbbd8a7258d22ecb8", GitTreeState:"clean", BuildDate:"2020-04-21T00:13:25Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**

istioctl manifest apply --namespace istio-system --set addonComponents.prometheusOperator.enabled=true --set meshConfig.accessLogFile="/dev/stdout" --set values.grafana.enabled=false --set values.grafana.ingress.enabled=false --set values.prometheus.enabled=true --set values.prometheusOperator.createPrometheusResource=true  --set values.kiali.enabled=true  --set values.gateways.istio-ingressgateway.type=LoadBalancer --set values.gateways.istio-ingressgateway.sds.enabled=true --set values.global.controlPlaneSecurityEnabled=true

**Environment where bug was observed (cloud vendor, OS, etc)**
Tested on Rancher RKE on Baremetal (works)
Tested on Azure AKS (defect)

**Comment by howardjohn** [comment]
Please upgrade to Istio 1.6.7, this was a bug that was fixed: https://istio.io/latest/news/releases/1.6.x/announcing-1.6.7/

**Comment by Crazyigor1987** [comment]
My bad, thank you. Problem solved!
