### ISSUE TITLE
The image of the Istio proxy running on the pod does not match the image defined in the injection configuration

### ISSUE THREAD

**Issue by seecsea** [istio/istio#26469]
**Bug description**

I modified the file manifests/profiles/default.yaml and set values.global.proxy.image to:
hub.itgay.com/library/istio/proxyv3:1.6.8
(is the same proxyv2:1.6.7 but different tag to debug configmap/istio-sidecar-injector)

install the istio 1.6.7
istioctl install --set profile=demo --charts=manifests/

and deploy a sample app helloworld in "hello" namespace

# istioctl analyze -n hello                                                                                 
Warn [IST0105] (Pod helloworld-v1-6f7b756bfc-g66mh.hello) The image of the Istio proxy running on the pod does not match the image defined in the injection configuration (pod image: hub.itgay.com/library/istio/proxyv3:1.6.8; injection configuration image: hub.itgay.com/library/istio/hub.itgay.com/library/istio/proxyv3:1.6.8:1.6.7). This often happens after upgrading the Istio control-plane and can be fixed by redeploying the pod.
Warn [IST0105] (Pod helloworld-v2-599cddcdf9-6shgd.hello) The image of the Istio proxy running on the pod does not match the image defined in the injection configuration (pod image: hub.itgay.com/library/istio/proxyv3:1.6.8; injection configuration image: hub.itgay.com/library/istio/hub.itgay.com/library/istio/proxyv3:1.6.8:1.6.7). This often happens after upgrading the Istio control-plane and can be fixed by redeploying the pod.
Error: Analyzers found issues when analyzing namespace: hello.
See https://istio.io/docs/reference/config/analysis for more information about causes and resolutions.

How can I set the right image URL in "injection configuration" when install istio use istioctl 
 install but not manifest generate the yam file?

I can do it manually by:
kubectl edit cm -n istio-system istio-sidecar-injector
global->hub：hub.itgay.com/library/istio          (old is:docker.io/istio)
global->proxy->image: proxyv2   (old is:hub.itgay.com/library/istio/proxyv3:1.6.8)
(hub.itgay.com/library/istio/proxyv2:1.6.7 is present)

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

# istioctl version --remote
client version: 1.6.7
control plane version: 1.6.7
data plane version: 1.6.7 (5 proxies)

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:47:40Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:37:43Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

CentOS 8.2 and in ipvs mode

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
You should do --set values.global.proxy.image=foo or pass `-f iop.yaml` with that set, not modify the profile

**Comment by seecsea** [comment]
[root@istio-master1:/usr/local/src/istio-1.6.7-andy]# istioctl install --set profile=demo --charts=manifests/ \
> --set values.global.proxy.image=hub.itgay.com/library/istio/proxyv3:1.6.8 \
> --set values.global.proxy_init.image=hub.itgay.com/library/istio/proxyv2:1.6.7
Detected that your cluster does not support third party JWT authentication. Falling back to less secure first party JWT. See https://istio.io/docs/ops/best-practices/security/#configure-third-party-service-account-tokens for details.
✔ Istio core installed                                                                                                                                                                                                                      
✔ Istiod installed                                                                                                                                                                                                                          
✔ Ingress gateways installed                                                                                                                                                                                                                
✔ Egress gateways installed                                                                                                                                                                                                                 
✔ Addons installed                                                                                                                                                                                                                          
✔ Installation complete                                                         

[root@istio-master1:/usr/local/src/istio-1.6.7-andy/samples/helloworld]# istioctl analyze -n hello
Warn [IST0105] (Pod helloworld-v1-6f7b756bfc-rggpc.hello) The image of the Istio proxy running on the pod does not match the image defined in the injection configuration (pod image: hub.itgay.com/library/istio/proxyv3:1.6.8; injection configuration image: docker.io/istio/hub.itgay.com/library/istio/proxyv3:1.6.8:1.6.7). This often happens after upgrading the Istio control-plane and can be fixed by redeploying the pod.
Warn [IST0105] (Pod helloworld-v2-599cddcdf9-d5l4m.hello) The image of the Istio proxy running on the pod does not match the image defined in the injection configuration (pod image: hub.itgay.com/library/istio/proxyv3:1.6.8; injection configuration image: docker.io/istio/hub.itgay.com/library/istio/proxyv3:1.6.8:1.6.7). This often happens after upgrading the Istio control-plane and can be fixed by redeploying the pod.
Error: Analyzers found issues when analyzing namespace: hello.
See https://istio.io/docs/reference/config/analysis for more information about causes and resolutions.

get the same reslut when use --set
I guess the istioctl do not right create the istio-sidecar-injector configmap
the proxy.image contains the completed URL (hub/ and :tag),but istioctl use hub+image+tag

**Comment by howardjohn** [comment]
can you post the istio-sidecar-injector configmap?

**Comment by howardjohn** [comment]
Oh wait. is it just the analysis message is wrong? but it actually uses the correct image?

**Comment by seecsea** [comment]
> Oh wait. is it just the analysis message is wrong? but it actually uses the correct image?

yes,all work ok,but istioctl analyze push warnning

**Comment by esnible** [comment]
The injector contains logic:

```
  - name: istio-proxy
  {{- if contains "/" (annotation .ObjectMeta `sidecar.istio.io/proxyImage` .Values.global.proxy.image) }}
    image: "{{ annotation .ObjectMeta `sidecar.istio.io/proxyImage` .Values.global.proxy.image }}"
  {{- else }}
    image: "{{ .Values.global.hub }}/{{ .Values.global.proxy.image }}:{{ .Values.global.tag }}"
  {{- end }}
```

The analyzer lacks this logic, it always uses the second case.

@howardjohn I'd like just to put the logic we see here in Go form into _galley/pkg/config/analysis/analyzers/injection/injection-image.go_ `getIstioProxyImage()`.  That is a much smaller change than trying to evaluate the injector from within an analyzer.  Do you concur?

**Comment by seecsea** [comment]
thanks a lot!

**Comment by derekcrovo** [comment]
I'd like to add a +1 for cherry-picking for the next release.  We customize the image names to add SHA digests for the security benefit it confers.  Maybe that's not as common a practice as I thought?  It's very noisy to have `istioctl analyze` alert for every pod.

Thanks for the PR!
