### ISSUE TITLE
mixer is deprecated,but bookinfo demo policy and telemetry resource are still base on mixer,can you add demo base on wasm and telemetry v2

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#26466]
**Describe the feature request**
mixer is deprecated,but bookinfo demo policy and telemetry resource are still base on mixer,can you add demo base on wasm and telemetry v2
**Describe alternatives you've considered**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by bianpengyuan** [comment]
1.6 demo profile should already by default using telemetry v2. I am closing this issue and please reopen if you have any more question. thanks!
