### ISSUE TITLE
TestWorkloadInstances test flakes

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#26465]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/25920/unit-tests_istio/18842
https://prow.istio.io/view/gs/istio-prow/logs/unit-tests_istio_postsubmit/3366

Likely regression by https://github.com/istio/istio/pull/26405? Or a coincidence

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gs/istio-prow/logs/unit-tests_istio_postsubmit/3372

**Comment by hzxuzhonghu** [comment]
I figured out it, 

```
	eventch := make(chan Event, 10)

	xdsUpdater := &FakeXdsUpdater{
		Events: eventch,
	}
```

In this test, we makes a buffered channel, and without clean it at all. So any xdsUpdate may block.

**Comment by hzxuzhonghu** [comment]
Fixed
