### ISSUE TITLE
will the resources of instance rule handler be deleted in future release as mixer will not be maintained after 1.7

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#26467]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)
will the resources of instance rule handler be deleted in future release as mixer will not be maintained after 1.7
**Describe the feature request**

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by bianpengyuan** [comment]
Mixer and its configuration will be removed in 1.8. Although in 1.7.x, likely 1.7.1, we will provide a Mixer shim layer which work with Envoy access log service and external authz service, which would make it possible to still run 1.7 Mixer with its configuration after upgrading other Istio components to 1.8. If you are interested in that, please watch the 1.7.x release note. Also note this is not recommended, and just a stop gap. It is still recommended to use telemetry v2 or Wasm extension for other types of extensions.

Let me if you have further questions, thanks!
