### ISSUE TITLE
istioctl manifest migrate returns proto: tag has too few fields: "-"

### ISSUE THREAD

**Issue by popopanda** [istio/istio#26473]
**Bug description**

Migrating from helm install to use the new istioctl by using  `istioctl manifest migrate` returns error
```
$ ./istioctl manifest migrate values.yaml > iop.yaml
2020-08-10T21:31:07.524233Z	info	proto: tag has too few fields: "-"
```

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

generates the expected output without error

**Steps to reproduce the bug**
Followed this documentation - https://istio.io/latest/docs/setup/upgrade/#upgrading-from-helm-installations

My helm values.yml - https://gist.github.com/popopanda/679bc16e3d30b77ed8009c6cfb711f03

ran the following:
```
$ ./istioctl manifest migrate values.yaml > iop.yaml
2020-08-10T21:31:07.524233Z	info	proto: tag has too few fields: "-"
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
currently on v1.5.8, upgrading to 1.6.7

**How was Istio installed?**
helm

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS EKS

**Comment by tanjunchen** [comment]
Similar to #26010

**Comment by tanjunchen** [comment]
see https://github.com/istio/istio/pull/26304

**Comment by popopanda** [comment]
Tried with v1.7.0 RC 

looks like the migrate command is removed?

```
$ istio-1.7.0-rc.1/bin/istioctl manifest migrate
The manifest subcommand generates, applies, diffs or migrates Istio manifests.

Usage:
  istioctl manifest [command]

Available Commands:
  diff        Compare manifests and generate diff
  generate    Generates an Istio install manifest
  install     Applies an Istio manifest, installing or reconfiguring Istio on a cluster.

Flags:
      --dry-run   Console/log output only, make no changes.
  -h, --help      help for manifest

Global Flags:
      --context string      The name of the kubeconfig context to use
  -c, --kubeconfig string   Kubernetes configuration file

Use "istioctl manifest [command] --help" for more information about a command.
```

**Comment by popopanda** [comment]
see https://github.com/istio/istio/pull/23353
