### ISSUE TITLE
Istio-operator's resource names hardcoded in helm chart

### ISSUE THREAD

**Issue by vhosakot** [istio/istio#26472]
**Bug description**

Istio-operator's resource names (names of pod, deployment and service) are hardcoded to `istio-operator` in helm chart https://github.com/istio/istio/tree/1.6.8/manifests/charts/istio-operator. Using istio `1.6.8`.

[x] Installation
[x] User Experience

**Expected behavior**

Would be nice if istio-operator's resource names (names of pod, deployment and service) use helm's release name (`{{ .Release.Name }}`) instead of hardcoding so we can change the resource names when installing using helm.

**Steps to reproduce the bug**

Used helm to install https://github.com/istio/istio/tree/1.6.8/manifests/charts/istio-operator.

```
git clone https://github.com/istio/istio.git
cd istio
git checkout 1.6.8

helm install my-istio-operator manifests/charts/istio-operator

$ helm ls -A
NAME              	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART                                        	APP VERSION
my-istio-operator	default      	1       	2020-08-13 19:00:08.637505297 +0000 UTC	deployed	istio-operator-1.6.0

# see hardcoded resource name istio-operator below
$ kubectl get all -A | grep istio-ope
istio-operator   pod/istio-operator-b87f5fdb5-vfrhr                                 1/1     Running   0          33m
istio-operator   service/istio-operator                 ClusterIP      10.111.70.95     <none>         8383/TCP                     33m
istio-operator   deployment.apps/istio-operator                 1/1     1            1           33m
istio-operator   replicaset.apps/istio-operator-b87f5fdb5                  1         1         1       33m
```

Would be nice if the istio-operator's resources were named (using helm's release name instead of hardcoding) as follows so they can be changed when installing using helm:

```
$ kubectl get all -A | grep istio-ope
istio-operator   pod/my-istio-operator-b87f5fdb5-vfrhr                                 1/1     Running   0          33m
istio-operator   service/my-istio-operator                 ClusterIP      10.111.70.95     <none>         8383/TCP                     33m
istio-operator   deployment.apps/my-istio-operator                 1/1     1            1           33m
istio-operator   replicaset.apps/my-istio-operator-b87f5fdb5                  1         1         1       33m
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
$ ./istio-1.6.8/bin/istioctl version --remote
no running Istio pods in "istio-system"
1.6.8

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:16:24Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:08:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

$ helm version
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

**How was Istio installed?**

Istio-operator was installed using helm, see steps under "**Steps to reproduce the bug**".

**Environment where bug was observed (cloud vendor, OS, etc)**

Kubernetes `v1.17.6` installed using `kubeadm` in Ubuntu `18.04.4` (Bionic Beaver).

**Comment by vhosakot** [comment]
@sdake This is just a cosmetic issue I think, not a functionality issue. Would be nice if istio-operator resources had customized/product-specific names.

Would be nice if the istio-operator's resources were named (using helm's release name instead of hardcoding `istio-operator`) as follows so they can be changed when installing using helm (see `my-product-` in the names below):

```
git clone https://github.com/istio/istio.git
cd istio
git checkout 1.6.8

helm install my-product-istio-operator manifests/charts/istio-operator

$ kubectl get all -A | grep istio-ope
istio-operator   pod/my-product-istio-operator-b87f5fdb5-vfrhr                                 1/1     Running   0          33m
istio-operator   service/my-product-istio-operator                 ClusterIP      10.111.70.95     <none>         8383/TCP                     33m
istio-operator   deployment.apps/my-product-istio-operator                 1/1     1            1           33m
istio-operator   replicaset.apps/my-product-istio-operator-b87f5fdb5                  1         1         1       33m
```

**Comment by sdake** [comment]
@ostromart @costinm any thoughts on if this would be a problem? are there not limits in certain resource fields?
