### ISSUE TITLE
how to build istioctl command on arm64 plantform？

### ISSUE THREAD

**Issue by DrowringMan** [istio/istio#26508]
i will use istio in arm64 plantform,im build istio image success,but build istioctl error

```
root@Kylin:~/testcase# istioctl version
client version: unknown
control plane version: 9d07e185b0dd50e6fb1418caa4b4d879788807e3-dirty
data plane version:  (3 proxies)
```

my istioctl version is unknown

**Comment by DrowringMan** [comment]
build method:
cd $GOPATH/src/istio/istioctl/cmd/istioctl && go build main.go

my istio code version:1.5.1

**Comment by howardjohn** [comment]
See https://github.com/istio/istio/blob/382a6feba24c9a31943d271c1ee359f7f475345c/Makefile.core.mk and the corresponding arm target. The version is populated by `common/scripts/report_build_info.sh`

**Comment by DrowringMan** [comment]
I compiled istioctl as you suggested，
```
make istioctl-install
root@Kylin:~/go/src/istio/istioctl/cmd/istioctl# istioctl version
client version: 9d07e185b0dd50e6fb1418caa4b4d879788807e3-dirty
control plane version: 9d07e185b0dd50e6fb1418caa4b4d879788807e3-dirty
data plane version:  (5 proxies)
```
@howardjohn 
this version in .git/HEAD and  .git/packed-refs

The reason why I want to compile istioctl is to solve the problem of kiali.
```
kiali error:
 Unknown Istio implementation version 9d07e185b0dd50e6fb1418caa4b4d879788807e3-dirty-9d07e185b0dd50e6fb1418caa4b4d879788807e3-dirty-Modified is not recognized, thus not supported.
```

My kiali unable to display traffic graph and monitoring

**Comment by howardjohn** [comment]
If Kiali has that error I think its from the actual version of Istiod used, not istioctl

> I compiled istioctl as you suggested，

No, you ran a different command then I meant (sorry, the link was wrong). You want `istioctl-all`. This produces a release build

**Comment by howardjohn** [comment]
Closing as this is answered. Thanks!
