### ISSUE TITLE
Istio release 1.5.9 is labeled as latest instead of 1.6.8

### ISSUE THREAD

**Issue by RobCannon** [istio/istio#26510]
**Bug description**
The latest label for the Istio releases page is applied to the wrong release.  It is applied to the 1.5.9 release instead of the 1.6.8 release.  This is breaking automation scripts for installing the latest release of istio.

[ ] Docs
[X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**
View Releases page:
https://github.com/istio/istio/releases

**Comment by howardjohn** [comment]
If I recall correctly, the issue is Github does not allow us to declare which release is latest. 1.5.9 is, chronologically, the latest release. I would not recommend using the latest indicator in scripts, our docs have a script to get the release latest: https://istio.io/latest/docs/setup/getting-started/#download

Please fact check me @fpesce

**Comment by fpesce** [comment]
> If I recall correctly, the issue is Github does not allow us to declare which release is latest. 1.5.9 is, chronologically, the latest release. I would not recommend using the latest indicator in scripts, our docs have a script to get the release latest: https://istio.io/latest/docs/setup/getting-started/#download
> 
> Please fact check me @fpesce

You are correct, https://istio.io/downloadIstio is the correct way to retrieve the latest version of istio.
This is a well known problem with github API (c.f. : https://developer.github.com/v3/repos/releases/#get-the-latest-release "_The latest release is the most recent non-prerelease, non-draft release, sorted by the created_at attribute. The created_at attribute is the date of the commit used for the release, and not the date when the release was drafted or published._ ")
During our latest security release, we pressed the "release" button faster on 1.6 than on 1.5, making 1.5.9 the latest released.
We can create a process to insure that the security releases won't create this problem anymore, and we could make sure non-security releases are ordered correctly if we would schedule cross-versions releases on a same day.

**Comment by RobCannon** [comment]
Even if you ensured the release were ordered correctly, there would be a tiny window where the "latest" version is referencing the older version.  But you probably want to do that to make sure the main GitHub page for the project does not show this:

![image](https://user-images.githubusercontent.com/189862/90276555-1deca300-de32-11ea-89f5-1e3f421d5e61.png)
