### ISSUE TITLE
[multi-network] Unreachable cross-network endpoints for non-sidecared pods. 

### ISSUE THREAD

**Issue by stevenctl** [istio/istio#26517]
**Bug description**

In a multinetwork setup, when a pod with a sidecar tries to reach a non-sidecar pod it causes `TLS error: 268435703:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER` 

We'd either need to 
1. terminate TLS for this scenario at the gateway
2. filter these endpoints out

This is problematic in a scenario where the non-sidecared service exists in both networks. We would loadbalance between endpoints we can reach and ones we cannot. It may be possible to do TLS termination for these endpoints at the gateway, but for now we should at least remove the unreachable endpoints.

https://github.com/istio/istio/pull/26486 fixes this but has shortcomings. 

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by nmittler** [comment]
@costinm @howardjohn WDYT? Do we just give up and filter out `naked` workloads from x-cluster multi-network scenarios?

**Comment by howardjohn** [comment]
>  Do we just give up and filter out naked workloads from x-cluster multi-network scenarios?

Well its certainly better than sending mTLS traffic to them. If we can find a way to make it work, that would be preferred but I cannot think of one.

@rshriram
