### ISSUE TITLE
Ingress using non-debug image failed to load cert

### ISSUE THREAD

**Issue by linsun** [istio/istio#2651]
While debugging for https://github.com/istio/istio/pull/2557, prow e2e-smoke kept failing when ingress uses non-debug proxy image.  Open this for further investigation.

The error is something like this:

[2018-01-12 14:07:42.857][17][critical][main] external/envoy/source/server/server.cc:78] error initializing configuration '/etc/istio/proxy/envoy-rev0.json': Failed to load certificate '/etc/certs/root-cert.pem'

**Comment by linsun** [comment]
https://storage.googleapis.com/istio-prow/pull/istio_istio/2557/e2e-smoke/1429/artifacts/demo-test-24d49ac683d44b1689ca7492237/istio-ingress-2183619444-hrhnc_container:istio-ingress.log

**Comment by ldemailly** [comment]
@kyessenov I thought /etc/certs are the ones deposited by the Istio CA and not the system ones

but do you know why would the non debug image behave differently ? or maybe it's missing some starter cert that the debug image does have ?

**Comment by ldemailly** [comment]
cc @qiwzhang  / @costinm too who may know how the image difference may explain this/or have seen this before from envoy

**Comment by kyessenov** [comment]
There are behavioral differences between debug and production builds of
Envoy, but usually it's the opposite - debug build is more likely to crash
since it enforces some invariants, rather than warning about them.

Sorry, this probably requires digging the root exception in envoy.

**Comment by linsun** [comment]
Ok, I believe this is caused by the fact that we are still using old envoy binary in the non-debug image used in our test.  I grabbed the yaml (https://storage.googleapis.com/istio-prow/pull/istio_istio/2669/e2e-smoke/1578/artifacts/istio.e2e.792543437/yaml/istio-one-namespace.yaml) we used in the test in https://github.com/istio/istio/pull/2669 and deployed it on my k8s:

$ kubectl exec -it istio-ingress-349199616-s914g -n simple-auth-test-2805bb2e5b2f4864a707 bash
root@istio-ingress-349199616-s914g:/# ls -al /usr/local/bin/envoy

If I use the non debug proxy image I built locally myself, and exec into the istio ingress pod, it has:

-r-xr-xr-x 1 root root 34099568 Jan  6 02:37 envoy

And I can run the bookinfo or simple ingress test manually successfully when using the yaml and image I built locally.

**Comment by linsun** [comment]
This can be closed via #2651
