### ISSUE TITLE
Server side telemetry does not log 403 response codes

### ISSUE THREAD

**Issue by davidraskin** [istio/istio#26520]
**Bug description**

The wasm stackdriver plugin will not log requests server-side that 403. Requests with a 200 response code are logged.
This issue seems to occur after this istio/proxy sha update commit on istio: https://github.com/istio/istio/commit/b31e8bf5d3182b20f3e8e424e0142d883cd8a786

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Both allowed and denied requests should be logged

**Steps to reproduce the bug**

Download the 1.7 pre-release of istio: https://github.com/istio/istio/releases/tag/1.7.0-rc.1.
Install istio with the stackdriver filter enabled.
Deploy bookinfo, and send a request to the productpage. All requests are logged.
Apply istio Authorization Policy to only allow requests to the productpage.
Only the 200 requests to the productpage pod will appear on the logs viewer, 403 requests to other pods will not appear.

This can also be reproduced in stackdriver integration tests, on a commit after the one specified above.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

istioctl version: 1.7.0-rc.1
kubectl client version: v1.18.3
kubectl server version: v1.16.11-gke.5

**How was Istio installed?**

`istioctl install --set profile=demo --set values.telemetry.v2.stackdriver.enabled=true --set values.telemetry.v2.stackdriver.logging=true --set values.telemetry.v2.stackdriver.topology=true`

**Environment where bug was observed (cloud vendor, OS, etc)**

Debian GNU/Linux rodete

**Comment by mandarjog** [comment]
Can you try this out with prometheus?

**Comment by mandarjog** [comment]
@JimmyCYJ @jwendell This is potentially release blocking if we can reproduce the problem with other log callbacks.

**Comment by davidraskin** [comment]
@gargnupur

**Comment by davidraskin** [comment]
Yes I can try it out

**Comment by mandarjog** [comment]
@davidraskin can you enable debug proxy logs and attach them here? Thanks.

**Comment by gargnupur** [comment]
[tmp.txt](https://github.com/istio/istio/files/5077112/tmp.txt) -> debug logs

**Comment by mandarjog** [comment]
Potentially localReply is no longer resulting in the `log` callback. @jplevyak @PiotrSikora

**Comment by mandarjog** [comment]
There is a change in behaviour at the commit specified here.
ClearDeferred list does result in calling access log handlerS.

**Comment by mandarjog** [comment]
Here is what we found so far.
https://github.com/envoyproxy/envoy-wasm/commit/ede27304cf02bf243c4d403240b65d9e1ed22957
 commit added a guard `http_request_started_` which is set in wasm `Context::decodeHeaders` and it is checked in wasm `Context::log`. `Context::log` does an early return.

**Comment by mandarjog** [comment]
https://github.com/envoyproxy/envoy-wasm/pull/621 Is under review to fix this problem.

**Comment by shwetaraghuvanshi** [comment]
What is the ETA to fix ?

**Comment by mandarjog** [comment]
The base envoy change has merged, we will get it into istio build EOD.

**Comment by mandarjog** [comment]
PR for review, @istio/release-managers PTAL https://github.com/istio/envoy/pull/260

**Comment by gargnupur** [comment]
PR for review, @istio/release-managers PTAL https://github.com/istio/proxy/pull/2990

**Comment by mandarjog** [comment]
Proxy PR under review: https://github.com/istio/proxy/pull/2989  <on main>

**Comment by mandarjog** [comment]
This is fixed in main and 1.7 is verified.
