### ISSUE TITLE
Istio.io Website Notification

### ISSUE THREAD

**Issue by heatherzheng** [istio/istio#26523]
This is part of the Website Notification which detects important events of istio.io and preliminary.istio.io and sends messages to the github issue.
Design docs are here: https://docs.google.com/document/d/18r1LV9HnU4ZflRG8qSfDAKeuxvc5iCfgIsHqk31Ugy0/edit?usp=sharing
Currently, we are waiting the service account to be added to the google analytics 
Related PR: [https://github.com/istio/bots/pull/254](url)
The rest of code that is not push is at: 
[https://github.com/heatherzheng/bots/tree/getAnalytics](url)

Newly added codes does:

- Get information from analytics including:

  1. if there’s continuously bad review 

  2. if pageview increase/decrease more than 30% compared to last week

  3. If there’s 404 page error

- Send daily report about 404 page error

- Send weekly report about bad reviews and pageview increase/decrease

The work needs to be done:

- After the service account get permission to the analytics, you can check if codes in getanalytics.go works

- Further steps to setup SA: [https://cloud.google.com/docs/authentication/production](url)
Account addr: istioioanalytics@istio-testing.iam.gserviceaccount.com

- Setup Cron job in GCP Kubernetes Engine, needs three cron jobs in total with hour/day/week timeFlag.

**Comment by heatherzheng** [comment]
@therealmitchconnors @davidhauck

**Comment by therealmitchconnors** [comment]
Thanks @heatherzheng, excellent work!
