### ISSUE TITLE
Update grafana "mesh dashboard" to fix missing galley metrics

### ISSUE THREAD

**Issue by infa-ddeore** [istio/istio#26535]
**Bug description**
Default istio mesh dashboards doesn't show metrics vs,dr,gw, and meshpolicies because galley_istio_networking_virtualservices, galley_istio_networking_destinationrules, galley_istio_networking_gateways, galley_istio_authentication_meshpolicies metrics are missing

![image](https://user-images.githubusercontent.com/39782583/90306290-29e76c00-dee9-11ea-91b7-6a850551f0a8.png)

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
missing metrics should appear to show the date on dashboard

**Steps to reproduce the bug**
install bookinfo app and view the Mesh dashboard 

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.5.8

**How was Istio installed?**
istioctl manifest apply -f <override.yaml>

**Environment where bug was observed (cloud vendor, OS, etc)**
EKS, minikube, docker-desktop

**Comment by mandarjog** [comment]
Galley metrics have been removed, but the dashboard should be updated.
I will update the title.

**Comment by infa-ddeore** [comment]
so there is no way to see vs,dr,gw etc. resources?

**Comment by mandarjog** [comment]
I think there are other metrics, but if not they are easy to add.

**Comment by infa-ddeore** [comment]
so the mesh dashboard will have galley graphs fixed or the graphs will be removed?

**Comment by mandarjog** [comment]
We will provide the same information, but it may not come from from those specific metrics.

**Comment by infa-ddeore** [comment]
do you know which metrics in 1.5 onwards contain this information? i can fix my existing dashboards

**Comment by douglas-reid** [comment]
Related issue: https://github.com/istio/istio/issues/24308

**Comment by carolynhu** [comment]
Follow up: https://github.com/istio/istio/issues/28129
