### ISSUE TITLE
Configure Envoy component log levels via a First Class API

### ISSUE THREAD

**Issue by Stono** [istio/istio#26547]
**Describe the feature request**
I'm on a mission to make istio more "debuggable" for some of first line engineers.

I would like the ability to enable access logs at runtime on a per service basis.  You can do it at a mesh level here https://istio.io/latest/docs/tasks/observability/logs/access-log/#enable-envoy-s-access-logging but that is extremely overkill when you're just debugging a single service.  (note: I've since been informed this is coming in 1.8 via first class api)

An extension to this is ideally we'd like to be able to configure any of the envoy component log levels at run time **without requiring a service reload**. 

I appreciate this can be done per pod with istioctl or port-forwarding 15000/logs, however when you're dealing with very horizontally scaled workloads this is quite a frustrating task.  

It also requires a cluster admin.  There are certain capabilities that we expose to aspects of our org through a control panel, eg:

![image](https://user-images.githubusercontent.com/1486729/90427822-f78d6880-e0ba-11ea-98f4-1aaa98ea589b.png)

We would really like to be able to add "Temporarily Enable Istio Debug Logs" there, at a workload level, to enable us to capture as much information as possible as and when we're having an issue, before (typically) restarting workloads to resolve the problem.

**Describe alternatives you've considered**
Distributing scripts and requiring sys admins to handle it, but I'd rather delegate 

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[x] Developer Infrastructure

**Additional context**

**Comment by ramaraochavali** [comment]
We discussed in the networking wg, we expect `1.8` to have first class API to do that and till such time the recommendation is to use EnvoyFilter to enable per service. Sample filter https://github.com/nrjpoddar/cncf_webinar_istio_debugging/blob/master/access_log_envoy_filter_workload.yaml

**Comment by Stono** [comment]
Ahhh great stuff, thank you @ramaraochavali

**Comment by Stono** [comment]
@ramaraochavali @nrjpoddar I don't suppose you know if I can configure the raw envoy logging level by an EnvoyFilter?

The access logs are useful but the http logs (showing request/response headers) in envoy are super useful.

**Comment by ramaraochavali** [comment]
AFAIK, that is not possible via Envoy filters. Only way I know of to control the Envoy raw logging is via annotations.

**Comment by nrjpoddar** [comment]
@Stono can you update the issue to say first class APIs for both access and component logs? As @ramaraochavali mentioned we don't have a good mechanism for turning on "debug" Envoy logging at a service/workload level especially in a auto-scale scenario without requiring restarts.

**Comment by Stono** [comment]
Aye Aye captain

**Comment by nrjpoddar** [comment]
cc @douglas-reid @mandarjog for visbility.

**Comment by douglas-reid** [comment]
@mandarjog tangentially, this is somewhat related to prior discussions around telemetry profiles and allowing a "debug this service" type of interaction (as opposed to turning on all different types of logs, traces, metrics, etc., independently).

**Comment by howardjohn** [comment]
Does envoy even support configuring log levels via XDS? perhaps with RTDS?
