### ISSUE TITLE
Circuit breaker does not work for interservice calls

### ISSUE THREAD

**Issue by vmasyagin** [istio/istio#26556]
I am trying to apply the Circuit Breaker for interservice calls that go through the Feign Client. Looked at the official documentation. Specifically https://istio.io/latest/docs/ops/common-problems/network-issues/, and can't seem to get the effect to work for interservice calls. Tell me, please, maybe somewhere it is described in detail how to handle this situation. Thank you in advance!

**Comment by howardjohn** [comment]
Please add more information about what you did, and what did not work. https://github.com/istio/istio/wiki/Troubleshooting-Istio can help explain how to get detailed config dumps as well

**Comment by vmasyagin** [comment]
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-test
spec:
  hosts:
  #- "*"
  - istiogateway.server
  - service.istio-test.svc.cluster.local
  - service2.istio-test.svc.cluster.local
  - service3.istio-test.svc.cluster.local
  gateways:
  - istio-test/istio-test-gateway
  - mesh
  http:
  - match:
    - uri:
        prefix: "/service/service"
      gateways:
      - istio-test/istio-test-gateway
    rewrite:
      uri: "/service"
    route:
    - destination:
        port:
          number: 8080
        host: service
        subset: v1
      weight: 100
    - destination:
        port:
          number: 8080
        host: service
        subset: v2
      weight: 0
    timeout: 2s
    retries:
      attempts: 3
      perTryTimeout: 2s
  - match:
    - uri:
        prefix: "/service2/service2"
      gateways:
      - istio-test/istio-test-gateway
    rewrite:
      uri: "/service2"
    route:
    - destination:
        port:
          number: 8080
        host: service2
  - match:
    - uri:
        prefix: "/service3/service3"
      gateways:
      - istio-test/istio-test-gateway
    rewrite:
      uri: "/service3"
    route:
    - destination:
        port:
          number: 8080
        host: service3
  - match:
    - uri:
        prefix: "/service"
      gateways:
      - mesh
    route:
    - destination:
        port:
          number: 8080
        host: service.istio-test.svc.cluster.local
        subset: v1
      weight: 100
    - destination:
        port:
          number: 8080
        host: service.istio-test.svc.cluster.local
        subset: v2
      weight: 0
  - match:
    - uri:
        prefix: "/service2"
      gateways:
      - mesh
    route:
    - destination:
        port:
          number: 8080
        host: service2.istio-test.svc.cluster.local
  - match:
    - uri:
        prefix: "/service3"
      gateways:
      - mesh
    route:
    - destination:
        port:
          number: 8080
        host: service3.istio-test.svc.cluster.local

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: service
spec:
  host: service
  subsets:
  - name: v1
    labels:
      version: v1
    trafficPolicy:
      connectionPool:
        http: {}
        tcp: {}
      loadBalancer:
        simple: RANDOM
      outlierDetection:
        baseEjectionTime: 15s
        consecutiveErrors: 1
        interval: 5s
        maxEjectionPercent: 100
  - name: v2
    labels:
      version: v2
    trafficPolicy:
      connectionPool:
        http: {}
        tcp: {}
      loadBalancer:
        simple: RANDOM
      outlierDetection:
        baseEjectionTime: 15s
        consecutiveErrors: 1
        interval: 5s
        maxEjectionPercent: 100

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-test-gateway
  namespace: istio-test
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
I set the specified settings. I have 1 pod of the service "service" version v1 running. Artificially spoil 1 request from the service "service" so that it returns 503 status. After that, rest-requests to the "service" service do not pass through the ingressgateway (no healthy upstream), which is correct. But if I call the service api "service3" through the Ingressgateway, which first calls the service api "service2" through the client, and that in turn calls the service api "service", then the service is available and no error occurs. Here I expected that the "service" service would be unavailable for both direct invocation through ingressgateway and inter-service invocation. Please help and point out what I am doing wrong and how to close the interservice calls.

**Comment by howardjohn** [comment]
You mentioned 3 different services. Do they all have sidecars injected?

It would help to get config dump and access logs from the gateway and service3, service2, and service 1. https://github.com/istio/istio/wiki/Troubleshooting-Istio has info on this. thanks

**Comment by anyyyy** [comment]
Hello, I have a question about `outlierDetection`. If the fuse is triggered and the service is evicted, I learned that the eviction time=`baseEjectionTime`*the number of evictions, then is there a maximum eviction time? If there is no maximum, does it mean that you will be evicted for an infinite period of time if the service is not stable enough? I did not find a detailed description of the maximum eviction time. Can you help me out?
