### ISSUE TITLE
Application container not receiving TCP packets in TPROXY mode

### ISSUE THREAD

**Issue by chandappa** [istio/istio#26569]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

Remote TCP packets not received at application only when TPROXY mode is enabled, otherwise, application container receives packets with source IP 127.0.01, i.e. 

+       #annotations:
+         #sidecar.istio.io/interceptionMode: TPROXY

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[x] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
Application container receives TCP packets and source IP is preserved.
**Steps to reproduce the bug**
Set side car interception mode to TPROXY.
**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
❯ istioctl version --remote
client version: 1.6.5
control plane version: 1.6.8
data plane version: 1.6.8 (7 proxies)

❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-16T00:04:31Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
istioctl install -f <istio-operator.yaml>

**Environment where bug was observed (cloud vendor, OS, etc)**
Mac OS 10.5.6
Parallels Desktop 14
1 Master & 2 Worker VMs running Ubuntu 18.04 
Kubernetes v1.18.6

❯ k get nodes -o wide
[NAME](url
[istio_issue_archive.zip](https://github.com/istio/istio/files/5085362/istio_issue_archive.zip)
)         STATUS   ROLES    AGE     VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION       CONTAINER-RUNTIME
k-master     Ready    master   5d12h   v1.18.6   10.211.55.14   <none>        Ubuntu 18.04.5 LTS   4.15.0-112-generic   docker://19.3.12
k-worker-1   Ready    <none>   5d12h   v1.18.6   10.211.55.11   <none>        Ubuntu 18.04.5 LTS   4.15.0-112-generic   docker://19.3.12
k-worker-2   Ready    <none>   5d12h   v1.18.6   10.211.55.15   <none>        Ubuntu 18.04.5 LTS   4.15.0-112-generic   docker://19.3.12

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by chandappa** [comment]
Attaching istio_proxy debug logs - working and not working. 

[logs.zip](https://github.com/istio/istio/files/5085413/logs.zip)

**Comment by snmvaughan** [comment]
I'm having the same issue running on version 1.6.8, on both a kind and kubeadm cluster.  Istio was installed using the Istio operator using the default profile.

**Comment by chandappa** [comment]
could this be duplicate of  #23369 ?

**Comment by gmemcc** [comment]
@chandappa  I can't tell from the logs,  was the ports of the container network namespace exhausted after sending a single request to the workload?

**Comment by chandappa** [comment]
> ntainer network namespace exhausted after

No, it wasn't the case.

**Comment by chandappa** [comment]
2020-08-31T19:46:28.772054Z	debug	envoy connection	[C158485] connecting to 10.244.1.247:50600
2020-08-31T19:46:28.775511Z	debug	envoy connection	[C158487] connecting to 10.244.1.247:50600
2020-08-31T19:46:28.778817Z	debug	envoy connection	[C158489] connecting to 10.244.1.247:50600
2020-08-31T19:46:28.783827Z	debug	envoy connection	[C158491] connecting to 10.244.1.247:50600
2020-08-31T19:46:28.788348Z	debug	envoy connection	[C158493] connecting to 10.244.1.247:50600
2020-08-31T19:46:28.792782Z	debug	envoy connection	[C158495] connecting to 10.244.1.247:50600
2020-08-31T19:46:28.798320Z	debug	envoy connection	[C158497] connecting to 10.244.1.247:50600
2020-08-31T19:46:28.802820Z	debug	envoy connection	[C158499] connecting to 10.244.1.247:50600
2020-08-31T19:46:28.807225Z	debug	envoy connection	[C158501] connecting to 10.244.1.247:50600
2020-08-31T19:46:28.811928Z	debug	envoy connection	[C158503] connecting to 10.244.1.247:50600
2020-08-31T19:46:28.817231Z	debug	envoy connection	[C158505] connecting to 10.244.1.247:50600
2020-08-31T19:46:28.821045Z	debug	envoy connection	[C158507] connecting to 10.244.1.247:50600
2020-08-31T19:46:28.825601Z	debug	envoy connection	[C158509] connecting to 10.244.1.247:50600
2020-08-31T19:46:28.830351Z	debug	envoy connection	[C158511] connecting to 10.244.1.247:50600


-

This is with ISTIO 1.7.0, after sending a single request. @gmemcc I see the pattern now.
Duplicate of #23369

**Comment by howardjohn** [comment]
This is fixed in https://github.com/istio/istio/pull/28457. Since this is tracked in a few places, lets consolidate on https://github.com/istio/istio/issues/5679. Thanks!
