### ISSUE TITLE
Bring back Helm deployment option

### ISSUE THREAD

**Issue by razvan-ig** [istio/istio#26575]
**Describe the feature request**
Helm (especially since v3) has a clean and well understood process for installation, upgrades (with a roll-back option) and (something not covered by istioctl at all yet) removal.
Please consider adding the option back in.

**Describe alternatives you've considered**
istioctl

**Affected product area (please put an X in all that apply)**

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by howardjohn** [comment]
@razvan-ig thanks for the interest! we are tracking this in https://github.com/istio/istio/issues/26575, please follow this issue and if there are any requirements not covered there feel free to comment. thanks!

**Comment by razvan-ig** [comment]
> @razvan-ig thanks for the interest! we are tracking this in #26575, please follow this issue and if there are any requirements not covered there feel free to comment. thanks!

Wrong dupe ID I think

**Comment by howardjohn** [comment]
Sorry! meant https://github.com/istio/istio/issues/25184
