### ISSUE TITLE
Automatic sidecar injection generates metrics, manual sidecar injection does not

### ISSUE THREAD

**Issue by ericvn** [istio/istio#26582]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

I'm trying to convert an existing application to istio, Bookinfo in this case, as part of the doc testing.
I do not see any metrics for those services that are converted to use Istio (using istioctl kube-inject).

I tried deploying Bookinfo using automatic sidecar injection and I do see metrics.
I then tried deploying Bookinfo using manual sidecar injection and I DO NOT see metrics.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

I should see metrics whether I use automatic or manual sidecar injection

**Steps to reproduce the bug**

Deploy Istio - `istioctl install --set profile=demo`
Deploy addons - `kubectl apply -f samples/addons`
Deploy Bookinfo using manual sidecar injection - `kubectl apply -f <(istioctl kube-inject -f samples/bookinfo/platform/kube/bookinfo.yaml)`
drive some traffic - `kubectl exec "$(kubectl get pod -l app=ratings -o jsonpath='{.items[0].metadata.name}')" -c ratings -- curl productpage:9080/productpage | grep -o "<title>.*</title>"`
Look at metrics. - `istioctl dashboard grafana` 
No workloads show up

If I use automatic sidecar injection (set the label in the namespace and just do a simple apply of the bookinfo yaml), I do see the workloads.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

1.7.0-rc1

**How was Istio installed?**

istioctl install --set profile=demo
k apply -f samples/addons/

**Environment where bug was observed (cloud vendor, OS, etc)**

IKS 1.18

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by ericvn** [comment]
After testing to see if this would be a regression from 1.6 (it is), and moving back to 1.7, I can’t recreate the problem again.

**Comment by ericvn** [comment]
When I cam back to 1.7, I had the namespace label for automatic injection so that's why it worked. If I unlabeled the namespace and tried again with manual sidecar injection, there were no metrics.

**Comment by mandarjog** [comment]
can you attach the following
1. post injection file from manual injection.
2. config_dump from the proxy that is manully injected.
3. config_dump from proxy that works fine.
4. output from proxy :15000/stats/prometheus

Thanks.

**Comment by mandarjog** [comment]
This is a regression, it should be fixed.

**Comment by ericvn** [comment]
Some differences between auto and manual:
```
>               service.istio.io/canonical-name=productpage
>               service.istio.io/canonical-revision=v1
12c14,16
<               sidecar.istio.io/interceptionMode: REDIRECT
---
>               prometheus.io/path: /stats/prometheus
>               prometheus.io/port: 15020
>               prometheus.io/scrape: true
15,17d18
<               traffic.sidecar.istio.io/excludeInboundPorts: 15020
<               traffic.sidecar.istio.io/includeInboundPorts: 9080
<               traffic.sidecar.istio.io/includeOutboundIPRanges: *
```
The prometheus.io missing in the manual seems to be the problem.

**Comment by ericvn** [comment]
@esnible also reproduced.

**Comment by bianpengyuan** [comment]
I see, proxy is generating the metrics, it is just that prometheus is not configured to scrape from it.

**Comment by ericvn** [comment]
From Ed in Slack:
```
Code to set these things was merged to the webhook four months ago: https://github.com/istio/istio/blame/master/pkg/kube/inject/webhook.go#L538
15:22
The same code was never added to istioctl.  Because the code was added as part of webhook.go, not inject.go, it didn’t change the behavior of istioctl.
```

**Comment by esnible** [comment]
The code path of `istioctl kube-inject` is to call inject.IntoResourceFile() which calls inject.IntoObject().
The code path of auto-injection is webhook.go calls inject.InjectionData() and createPatch().

The code paths are very different.  When creating PRs to change behavior both paths must be modified.  Any work to combine these two code paths and eliminate duplication would be a big help.  In early versions of Istio the same code was used; not sure why it divererged.

**Comment by nrjpoddar** [comment]
Do we have line of sight on when we can fix this regression @bianpengyuan ??

**Comment by bianpengyuan** [comment]
@nrjpoddar I am fixing it now.

**Comment by esnible** [comment]
@bianpengyuan

I installed bookinfo, captured the productpage pod YAML, did `kubectl label ns default istio-injection-`, did `kubectl apply -f <(istioctl kube-inject -f samples/bookinfo/platform/kube/bookinfo.yaml)`, and diff'ed the output.

The automatic one had
```
>     prometheus.io/path: /stats/prometheus
>     prometheus.io/port: "15020"
>     prometheus.io/scrape: "true"
>     service.istio.io/canonical-name: productpage
>     service.istio.io/canonical-revision: v1
...
>     - name: ISTIO_METAJSON_ANNOTATIONS
>       value: |
>         {"kubernetes.io/psp":"ibm-privileged-psp"}
```

The `kube-inject` one had
```
<     sidecar.istio.io/interceptionMode: REDIRECT
<     traffic.sidecar.istio.io/excludeInboundPorts: "15020"
<     traffic.sidecar.istio.io/includeInboundPorts: "9080"
<     traffic.sidecar.istio.io/includeOutboundIPRanges: '*'
```

**Comment by bianpengyuan** [comment]
This is fixed now. Left item is to converge auto injection and manual injection code path, which I believe @howardjohn is going to take on.
