### ISSUE TITLE
after apply virtualservice delegate, route info disappear

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#26599]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
```
[root@master01 delegate]# istioctl proxy-config route istio-ingressgateway-698f645c48-g9cdp.istio-system --name http.80
NOTE: This output only contains routes loaded via RDS.
NAME        DOMAINS     MATCH                 VIRTUAL SERVICE
http.80     *           /productpage          bookinfo.istio
http.80     *           /static*              bookinfo.istio
http.80     *           /login                bookinfo.istio
http.80     *           /logout               bookinfo.istio
http.80     *           /api/v1/products*     bookinfo.istio
http.80     *           /reviews*             bookreviews.istio
[root@master01 delegate]# kubectl apply -f vs-delegate.yaml -n istio
virtualservice.networking.istio.io/bookinfo configured
[root@master01 delegate]# istioctl proxy-config route istio-ingressgateway-698f645c48-g9cdp.istio-system --name http.80
NOTE: This output only contains routes loaded via RDS.
NAME        DOMAINS     MATCH         VIRTUAL SERVICE
http.80     *           /reviews*     bookreviews.istio
[root@master01 delegate]# ls

[root@master01 delegate]# cat vs-delegate.yaml 
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: bookinfo
spec:
  gateways:
  - bookinfo-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        exact: /productpage
    - uri:
        prefix: /static
    - uri:
        exact: /login
    - uri:
        exact: /logout
    - uri:
        prefix: /api/v1/products
    delegate:
      name: productpage
      namespace: istio
```

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
[root@master01 delegate]# istioctl version
client version: 1.7.0-beta.1
control plane version: 1.7.0-beta.1
data plane version: 1.7.0-beta.1 (13 proxies)

[root@master01 delegate]# kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2020-05-12T09:28:18Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by esnible** [comment]
Can you add the YAML for your _bookreviews.istio_?

I don't understand this YAML:
```
    delegate:
      name: productpage
      namespace: istio
```

Usually VirtualService has a route/destination.  I have not seen a delegate there.

Can you run `istioctl analyze` and let us know if the output includes any errors or warnings?
Can you run `istioctl validate` on your YAML and let us know if it complains?

**Comment by 13567436138** [comment]
bookreviews.istio has no problem ,the problem is bookinfo.istio

**Comment by hzxuzhonghu** [comment]
@13567436138 Can you show the `product` VS?

**Comment by hzxuzhonghu** [comment]
@13567436138 Definitely you should provide the two virtual services?

**Comment by howardjohn** [comment]
We don't have enough information to troubleshoot this further. Please open a new issue if you get this info. Thanks!
