### ISSUE TITLE
Generated duplicate inbound route

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#26604]
**Bug description**

When debugging, i find there are duplicate route generated

```
 istioctl pc route httpbin-66cdbdb6c5-rdl2p
NOTE: This output only contains routes loaded via RDS.
NAME                                                          VIRTUAL HOSTS
80                                                            3
istiod.istio-system.svc.cluster.local:853                     1
InboundPassthroughClusterIpv4                                 1
                                                              1
kube-dns.kube-system.svc.cluster.local:9153                   1
istio-ingressgateway.istio-system.svc.cluster.local:15021     1
InboundPassthroughClusterIpv4                                 1
inbound|8000|http|httpbin.default.svc.cluster.local           1
InboundPassthroughClusterIpv6                                 1
InboundPassthroughClusterIpv6                                 1
inbound|8000|http|httpbin.default.svc.cluster.local           1
8000                                                          2
15010                                                         2
15014                                                         2

``` 

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

client version: 1.7.0-alpha.0
control plane version: 1.7.0-alpha.0-37119973c952151e269110170f2fda8c6a34fb5e
data plane version: 1.7.0-alpha.0 (3 proxies)

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
It may be inline routes for different filter chains

**Comment by howardjohn** [comment]
These are inline routes, I think this is intended

**Comment by pantianying** [comment]
I have the same question. All inbound routes are double. I have compared the specific configurations of these routes, and they are all the same. I think it's a bug, or at least needs to be investigated. This problem still exists in version 1.15.
