### ISSUE TITLE
PassthroughCluster after listener doesn't support gRPC

### ISSUE THREAD

**Issue by lut777** [istio/istio#26603]
I see a similar problem in #20257 ,  however, my scenario is a little different.

I send a GRPC stream to a clusterIP with a "wrong destination url". In this case, the "wrong destination url" means url in http is not "service.namespace.svc.cluster.local" or just in short "service.namespace".

So as I understand it, the grpc stream is listened to by the clusterIP listener. But since the domain doesn't match in the router, the stream will be intercepted by "allow_any" and processed by passthroughputcluster.
However, an error will occur. According to the client logs, gprc http2 is converted to http1.1, which is the same in #20257 

For comparison, in the same scenario, there is no problem with using http1.1 to transfer data. This passthroughcluster works well.

So, I see that you have fixed the default passthroughcluster grpc transmission problem, can you please tell me if the same problem exists in the passthroughcluster of the router with a allow_any route after listened by a listener on a cluterIP?

Plus:  is there a way to modify the route (istioctl pc ROUTE)? I would like to customize the redirection rules, not just limited to the service naming conventions provided by k8s. I think it could be more agility for the federation of k8s clusters.

Env:
Istio 1.6.7 installed based on IstioOperatorSpec

**Comment by lut777** [comment]
problem solved.

**Comment by AEGQ** [comment]
@lut777 how do you solved the problem ? (你是怎么解决这个问题的？)
I seem to have a similar problem,grpc traffic suddenly processed by passthroughputcluster https://github.com/istio/istio/issues/28651
（我好像遇到类似的问题，grpc 流量突然走到了passthroughputcluster）
