### ISSUE TITLE
The memory consumption of envoy is too large 50~70MB

### ISSUE THREAD

**Issue by pantianying** [istio/istio#26605]
**Bug description**

just apply the bookinfo example: 
![image](https://user-images.githubusercontent.com/20589945/90507512-916f1700-e188-11ea-9fd0-8291d8be2c42.png)
Then we find out what's taking up memory，I don't know if it's my problem

![image](https://user-images.githubusercontent.com/20589945/90507584-b3689980-e188-11ea-9adc-c6b56132c606.png)

I also got some logs in istio-proxy, may help identify the problem。
![image](https://user-images.githubusercontent.com/20589945/90507744-f88ccb80-e188-11ea-80e4-bff1308ef844.png)

In addition, we have just tried istio, so only bookinfo demo in the whole cluster uses sidecar. However, we have 400 namespace, which is more.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[X] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[X] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istio 1.6.7 k8s 1.18
**How was Istio installed?**
istioctl install
**Environment where bug was observed (cloud vendor, OS, etc)**
openshift 4.5
Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
Istio by default sends configuration for the entire cluster, even if the pods do not have sidecars. If you have a large cluster and want to scope this down ,you can use https://istio.io/docs/reference/config/networking/sidecar/ to control this. For example, you can resitrct to only the same namespace:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: sidecar
spec:
  egress:
  - hosts:
    - ./*
```

**Comment by pantianying** [comment]
yes! I try this ,now istio-proxy consumes 50~70M of memory.
 
Is there any other way to optimize memory？

**Comment by mandarjog** [comment]
At present 50~70 is the standard memory consumption. There are not config options to reduce it further at present.
What is your acceptable memory usage?

**Comment by pantianying** [comment]
> At present 50~70 is the standard memory consumption. There are not config options to reduce it further at present.
> What is your acceptable memory usage?

Because the number of pods is very large, if which can reduce the memory a little bit, the impact will be huge (for example, turn off some functions that can't be used temporarily)。

**Comment by carolynhu** [comment]
@pantianying this is normal, as we observed the same usage as well. ref: https://github.com/istio/istio/issues/25709

@lambdai any mitigations you can think of?

**Comment by bianpengyuan** [comment]
Not sure if you are using [Istio telemetry](https://istio.io/latest/docs/reference/config/metrics/) or not, but that could be turned off and save you some memory with the cost of losing Istio metrics. You can turn it off with `--set values.telemetry.v2.enabled=false --set values.telemetry.v2.prometheus.enabled=false`.

**Comment by pantianying** [comment]
I found that there will be all the namespace on the page of kiali, which means that isto telemetered all the namespace, instead of specifying the namespace injected into the sidecar. Is there any way for isto to telemetry only the specified namespace.
@bianpengyuan @howardjohn @mandarjog

**Comment by pantianying** [comment]
> Not sure if you are using [Istio telemetry](https://istio.io/latest/docs/reference/config/metrics/) or not, but that could be turned off and save you some memory with the cost of losing Istio metrics. You can turn it off with `--set values.telemetry.v2.enabled=false --set values.telemetry.v2.prometheus.enabled=false`.

ths for reply, but we need the istio telemetry~

**Comment by pantianying** [comment]
> resitrct



> Istio by default sends configuration for the entire cluster, even if the pods do not have sidecars. If you have a large cluster and want to scope this down ,you can use https://istio.io/docs/reference/config/networking/sidecar/ to control this. For example, you can resitrct to only the same namespace:
> 
> ```yaml
> apiVersion: networking.istio.io/v1alpha3
> kind: Sidecar
> metadata:
>   name: sidecar
> spec:
>   egress:
>   - hosts:
>     - ./*
> ```

I try this config
`spec:
  egress:
  - hosts:
    - ./*
    - istio-system/*`

Memory is reduced, but why my traffic telemetry function can not work properly. The following problems will arise
https://github.com/kiali/kiali/issues/3138
