### ISSUE TITLE
CNI does not get podRedirectAnnot

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#26611]
See https://github.com/istio/istio/pull/26596/files#r472327509 for details

**Comment by nrjpoddar** [comment]
@howardjohn based on our testing after this PR https://github.com/istio/istio/pull/25750/files was merged CNI was honoring `podRedirectAnnot`. Appears to me that your PR https://github.com/istio/istio/pull/26596 might have removed that logic.

Is that correct? @Kmoneal from our team has been testing CNI with pod annotations overrides after PR 25750 went in and we don't want to break that functionality.

**Comment by howardjohn** [comment]
https://github.com/istio/istio/pull/25750/ was never merged as far as I can tell? I don't think it ever worked. I believe prior to #26596  it worked in `istioctl kube-inject` but not the webhook, which is essentially the same as "it never worked"; #26596 made kube-inject behave the same as the webhook

**Comment by nrjpoddar** [comment]
I see, we should fix it the correct way. Any objections to resurrecting and merging https://github.com/istio/istio/pull/25750/files ?
