### ISSUE TITLE
istioctl install got `Invalid value: must be unique` error

### ISSUE THREAD

**Issue by carolynhu** [istio/istio#26614]
When I local run perf benchmark script, I got the following error message:

```
+ /Users/carolynprh/tools/perf/istio-install/tmp/istio-1.7-alpha.b95950afe673141d1438311f152a8dcfb866c4dd/bin/istioctl install --skip-confirmation -d /Users/carolynprh/tools/perf/istio-install/tmp/istio-1.7-alpha.b95950afe673141d1438311f152a8dcfb866c4dd/manifests -f istioctl_profiles/default-overlay.yaml
✔ Istio core installed
✔ Istiod installed
- Processing resources for Egress gateways, Ingress gateways.                   2020-08-18T05:52:56.675350Z	error	installer	failed to create "Deployment/istio-system/istio-ingressgateway": Deployment.apps "istio-ingressgateway" is invalid: spec.template.spec.containers[0].volumeMounts[7].mountPath: Invalid value: "/etc/istio/ingressgateway-certs": must be unique
✔ Egress gateways installed
✘ Ingress gateways encountered an error: failed to create "Deployment/istio-system/istio-ingressgateway": Deployment.apps "istio-ingressgateway" is invalid: spec.template.spec.containers[0].volumeMounts[7].mountPath: Invalid value: "/etc/istio/ingressgateway-certs": must be unique
- Pruning removed resources                                                     Error: failed to install manifests: errors occurred during operation
```

this line is somehow duplicated: https://github.com/istio/tools/blob/master/perf/istio-install/istioctl_profiles/default-overlay.yaml#L75

**Comment by carolynhu** [comment]
cc @ostromart @sdake @esnible

**Comment by carolynhu** [comment]
perf side fix: https://github.com/istio/tools/pull/1177

**Comment by esnible** [comment]
@ostromart I suspect the user was expecting volumeMounts to merge differently, or uniquely.  Should the overlay functions merge by default, never merge, or have ad-hoc bespoke merge logic?

I accept we can never write IstioOperator analysis that always detects if Kubernetes will reject it, but should we attempt to write spot checks for common problems?  I am thinking of something declarative, like notUnique(<jsonpath>) -> “Volume mount directories must be unique, you have {{<jsonpath>}}“.
