### ISSUE TITLE
istio-proxy container is able to access external endpoints without a service entry

### ISSUE THREAD

**Issue by ramsateesh** [istio/istio#26615]
**Bug description**
After meshConfig.outboundTrafficPolicy.mode is set to REGISTRY_ONLY, I was able to curl to any external services and was getting below error as expected:
`command terminated with exit code 35`
But when I run the same curl command from the sidecar container I get a 200 OK response

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Even from the istio-proxy sidecare we should be getting similar response unless there is a servcieentry.
`command terminated with exit code 35`

**Steps to reproduce the bug**
Follow the steps @ https://istio.io/latest/docs/tasks/traffic-management/egress/egress-control/
Step 2 of [change-to-the-blocking-by-default-policy](https://istio.io/latest/docs/tasks/traffic-management/egress/egress-control/#change-to-the-blocking-by-default-policy)

Use below command to check:
```commandline
kubectl exec -it $SOURCE_POD -c sleep -- curl -I https://www.google.com | grep  "HTTP/"; kubectl exec -it $SOURCE_POD -c istio-proxy -- curl -I https://edition.cnn.com | grep "HTTP/"
```
Expected Output:
```
command terminated with exit code 35
command terminated with exit code 35
```
Actual Output:
```
command terminated with exit code 35
HTTP/1.1 200 OK
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
$ istioctl version --remote
client version: 1.5.7
control plane version: 1.5.7
data plane version: 1.5.7 (4 proxies)

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:18:29Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
istioctl manifest apply -f istio-operator.yaml

**Environment where bug was observed (cloud vendor, OS, etc)**
My Local env and AKS.

[istio-dump.tar.gz](https://github.com/istio/istio/files/5092961/istio-dump.tar.gz)

**Comment by howardjohn** [comment]
This is working as expected - iptables rules are not applied to the sidecar container
