### ISSUE TITLE
Supportable EnvoyFilter for filter management

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#26627]
EnvoyFilter API uses name relative filter insertion, which has the following drawbacks.

* Names may change and break users 
* Extra burden on users, to know ordering when many time they do not need to.
* An incorrect or deprecated inner field can cause a segfault like https://github.com/istio/istio/issues/26818

EnvoyFilter does not support REPLACE operations, which is crucial for overrides and canaries.

We need to do the following to get a safe and supportable EnvoyFilter API.
- [x] Define EnvoyFilter API PROXY_CLASS ENUMS to have supported insertion points.
- [x] Define REPLACE API operation.
- [ ] Implement REPLACE and ensure MERGE and REPLACE are identical exception for the last mile.
- [ ] Implement `PROXY_CLASS` enum support.
- [ ] Implement validation and rejection of inner protos, This potentially requires knowing multiple proto version.  https://github.com/istio/istio/issues/26818
- [ ] Introduce `REMOVE_ALL` enum.
- [ ] `istioctl envoyfilter` command to push users towards supportable API.  @therealmitchconnors @esnible 
- [ ]  Doc: Update examples that do not need to use name relative order to use new API.
- [ ] Doc: Blog post about promoting the new API.

**Comment by mandarjog** [comment]
cc @rshriram @nrjpoddar

**Comment by kyessenov** [comment]
Need to clarify that filter proto is restricted by istiod included API definitions. It is not possible to apply a filter config (or any xDS) which was not compiled into istiod. E.g. https://github.com/istio/istio/pull/26590 issue.

**Comment by kyessenov** [comment]
It should be a goal to ensure that a malformed supportable EnvoyFilter does not cause a mass Envoy death.

**Comment by esnible** [comment]
Related:

We have an Issue for more validation of EnvoyFilter, https://github.com/istio/istio/issues/26390
We have an issue for validating specifically the things that we documented that no longer work in recent Envoy, https://github.com/istio/istio/issues/24743
We have an issue that Envoy shouldn't panic, but merely go stale, https://github.com/istio/istio/issues/26119

**Comment by esnible** [comment]
@kyessenov When I try to apply a `envoy.extensions.filters.http.wasm.v3.Wasm` in an EnvoyFilter the inline_bytes goes on the wire as a `udpa.type.v1.TypedStruct` with the inline_bytes as a `Kind: &types.Value_StringValue{StringValue:"dummy"}` and not the `BytesValue` I had hoped for.

Are you suggesting Istiod could merely import all of the types we allow in EnvoyFilter patches and it would serialize?

**Comment by kyessenov** [comment]
@esnible I would expect TypedStruct to be used often with EnvoyFilter. Istiod does not have a protobuf definition of the Wasm filter configuration (since it hasn't been upstreamed), and we use a JSON-based wrapper around it. I wonder if the JSON translation is the culprit of the issue?

**Comment by esnible** [comment]
@kyessenov Envoy complains with `gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener(s) virtualInbound: Unable to parse JSON as proto (INVALID_ARGUMENT:(config.vm_config.code.local.inline_bytes): invalid value "..."`

The bytes themselves are now correct after https://github.com/istio/istio/pull/25927 .  The listener just doesn't know how to make them bytes again.

The patch itself has decided the inline_bytes are a string and not bytes by the time we reach _/pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go_ doListenerListOperation().

I tried

```
                  local:
                    inline_bytes:
                      '@type': type.googleapis.com/google.protobuf.BytesValue
                      value: !!binary |
                        AUkMYAJ/fwE=
```

which seemed logical, but that failed with `gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) virtualInbound: Unable to parse JSON as proto (INVALID_ARGUMENT:JSON transcoder produced invalid protobuf output.)`

**Comment by kyessenov** [comment]
Could you try running envoy directly with typed struct and inline bytes? I am not familiar with envoyfilter implementation. I wonder if it's envoy or istio mis-handling typedstruct.

**Comment by kyessenov** [comment]
I think just having raw value without @type or !!binary works:
```yaml
local:
  inline_bytes: <base64 encoded value>
```

**Comment by esnible** [comment]
When I was debugging inline_bytes Istio validation for https://github.com/istio/istio/pull/25927 I applied .json, not .yaml, so I could be sure it wasn't the YAML library.  I used `yq read <envoyfilteryaml> --tojson` to get the JSON.

I used _protoc_ to decode what Istio was supplying to Envoy

`echo Cj50eXBlLmdvb2dsZWFwaXMuY29tL2Vudm95LmV4dGVuc2lvbnMuZmlsdGVycy5odHRwLndhc20udjMuV2FzbRKJAgqGAgoGY29uZmlnEvsBKvgBCmEKDWNvbmZpZ3VyYXRpb24SUCpOCjoKBUB0eXBlEjEaL3R5cGUuZ29vZ2xlYXBpcy5jb20vZ29vZ2xlLnByb3RvYnVmLlN0cmluZ1ZhbHVlChAKBXZhbHVlEgcaBXdvcmxkChcKB3Jvb3RfaWQSDBoKYWRkX2hlYWRlcgp6Cgl2bV9jb25maWcSbSprChMKBXZtX2lkEgoaCG15ZmlsdGVyCjAKBGNvZGUSKComCiQKBWxvY2FsEhsqGQoXCgxpbmxpbmVfYnl0ZXMSBxoFZHVtbXkKIgoHcnVudGltZRIXGhVlbnZveS53YXNtLnJ1bnRpbWUudjg= | base64 -D | protoc --decode_raw` produces

``` protoc
                1: "code"
                2 {
                  5 {
                    1 {
                      1: "local"
                      2 {
                        5 {
                          1 {
                            1: "inline_bytes"
                            2 {
                              3: "dummy"
                            }
```

The error was still `Error adding/updating listener(s) virtualInbound: Unable to parse JSON as proto (INVALID_ARGUMENT:(config.vm_config.code.local.inline_bytes): invalid value ...`  It was at this point I gave up.

**Comment by kyessenov** [comment]
I think #27272 is a requirement for debuggability of EnvoyFilters. Envoy extensions should be able to expose their metrics.

**Comment by pisto** [comment]
cc

**Comment by mandarjog** [comment]
not state.

**Comment by baraeb92** [comment]
not state.
