### ISSUE TITLE
gRPC connection is getting automatically disconnected after the initial connection estabilished with Istio 1.6

### ISSUE THREAD

**Issue by singhdeepu** [istio/istio#26628]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
gRPC connection is getting disconnected after the initial connection is established with one pod while making RPC calls to the server the connection is getting lost and it is trying to connect to some other pod. This is happening only after enabling Istio.
**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ x] Networking
[x ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
gRPC connection should not be terminated after enabling istio.
**Steps to reproduce the bug**
Microservice A pod tries to make a grpc call to connect to Microservice B pod and once it gets the connection then pod of A tries to call RPC functions on pod of B server. At this time request will be load-balanced to another pod of MIcroservice B.

We tried as a workaround using PASSTHROUGH in DestinationRule but it is leading to some other performance issue as new gRPC calls are not getting load-balanced and the same pod is getting multiple requests and other pods are not getting utilized.
**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
**istioctl version --remote**
client version: 1.5.1
control plane version: 1.6.8
data plane version: 1.6.8 (97 proxies).
**kubectl version**
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"ec6eb119b81be488b030e849b9e64fda4caaf33c", GitTreeState:"clean", BuildDate:"2020-03-12T21:00:06Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.13+IKS", GitCommit:"ab90f016957ae913df1f5f1429668032af382053", GitTreeState:"clean", BuildDate:"2020-07-15T21:56:15Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
**How was Istio installed?**
IBM Managed Istio

**Environment where bug was observed (cloud vendor, OS, etc)**
IBM Cloud
Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
I am a bit confused what your exact desired behavior is. You seem to not want to disable load balancing, but also want to send all requests on the same connection which seem incompatible. Can you explain the expected behavior a bit more so we can understand your use case?

**Comment by singhdeepu** [comment]
@howardjohn  The main problem that we are getting is the grpc disconnection. if we solve the somehow the grpc disconnection problem then we do not need to disable the load balancer and we would be able to use it. The problem is happening when we are making a gRPC connection first with a pod and then we are trying to execute some RPC call then the request is going to some different pod as it is somehow losing the connection and Istio is treating it as fresh connection and sending it to a different pod.

**Comment by singhdeepu** [comment]
**Before**:
1. Client microservice A opens a gRPC connection to microservice B. Note: Microservice B is deployed as a service and has 12 pods(replicates).
2. Pod running microservice A(pod A1) occupies pod running microservice B(pod B1) in the first RPC call m1(). Note: Pod B1 will reject any new connection from other pods running microservice A(pod A2, A3 ..). Pod A2 will disconnect and try again to find an unoccupied pod in microservice B( pod B2)
3. Microservice A uses the gRPC connection to make RPC call m2(), m3()… on microservice B, in a stateful manner. Microservice A works with microservice B on this connection for a long time , in the order of 10’s of minutes. Note: Connection must be open for long time between the pod running  microservice A and the pod running microservice B.
4. Close gRPC connection
This scenario works very well before we introduce istio between microservice A and microservice B. 
Following Istio configuration..
   * PeerAuthentication
   * DestinationRules

**After**:
1. Client microservice A opens a gRPC connection to microservice B. PASSED
2. Pod running microservice A(pod A1) tries to occupy pod running microservice B(pod B1) in the first RPC call m1(). PASSED 
3. Pod running Microservice A(Pod A1) uses the gRPC connection to make RPC call m2(), m3()… on microservice B(Pod B1). ERROR: Invalid connection.

**Observation**: 
* After the initial RPC connection to pod B1, when the method m1() is invoked- it disconnects from pod B1 and tries to connect to different pod B2( due to load balancing). And subsequent RPC calls m2(), m3(), … are connecting to different pods. We observed a stateless connection behaviour. 
* This is not a desired behaviour and we need a stateful connection between the pod running microservice A and the pod running microservice B, until we explicitly close the connection. 
* We see this behaviour only after introducing Istio.

**Comment by singhdeepu** [comment]
We tried the following workaround:

We used the DestinationRule as described below:
```
trafficPolicy:
    loadBalancer:
      simple: PASSTHROUGH
    tls:
      mode: ISTIO_MUTUAL
```
We observed the following behaviour:
* The connection between Pod running microservice A(pod A1) and pod running microservice B(pod B1) seems to be stateful.
* However, another pod running microservice  A(pod A2) also tries to connect and occupy pod B1(same pod). Pod B1 will continuously  reject the occupation request from pod A2. 
* This is not the desired behaviour and  expected behaviour is  pod A2 connects and occupies a new pod B2(instead of trying to connect to pod B1 repeatedly)

**Comment by singhdeepu** [comment]
Below codes are getting used to make grpc function calls:
```
   wscmd.DialGrpc(grpcContext, thc)
   jobGrpcClient := pb.NewActionServiceClient(grpcConn)
   //on the jobGrpcClient, we make rpc calls.
  // example custom rpc call:
   initRes, initErr = jobGrpcClient.InitJob(thc.Context, &initActionRequest, grpcCallOption) 
 // for closing the connection
  err := grpcConn.Close()
