### ISSUE TITLE
Prometheus: how to configure an existent Prometheus instance

### ISSUE THREAD

**Issue by luiof** [istio/istio#26632]
From the doc  https://istio.io/latest/docs/ops/integrations/prometheus/#option-1-customized-scraping-configurations I can see that we have to provision a certificate to the external prometheus instance, but how? 
The doc talks about to deploy a sidecar on the instance only to provide a certificate. Is it correct? It is not clear how to do that. Have we to inject the sidecar with the istioctl (as a normal deploy)?

The strict mTLS is enabled and the apps are in a namespace as <namespace-test>.
For now, I can get metrics from the existent prometheus (in another namespace and I use a grafana to check the dashboard) but I cannot replicate the metrics that retrieve the istio grafana and istio prometheus. It seems that the existent prometheus lacks some metrics (as byte received from incoming traffic).

The docs suggests `To use an existing Prometheus instance, add the scraping configurations in prometheus/configmap.yaml to your configuration`, and so I add the correct scrape section to my configuration.

Query (from istio grafana) as `round(sum(irate(istio_tcp_received_bytes_total{reporter="source", connection_security_policy="mutual_tls", destination_service=~"$service", destination_workload=~"$dstwl", destination_workload_namespace=~"$dstns"}[1m])) by (destination_workload, destination_workload_namespace), 0.001)` works on the istio prometheus (replacing the variable with the correct values), but if I use that with the existent prometheus a cannot retrieve nothing.

Is there a way clear to configure prometheus with the istio mesh?

**Comment by ltdeoliveira** [comment]
I'm currently in the same boat, validating upgrade from 1.4.X and stumbled on that problem. The only documentation covering that is this [very unuseful blog post](https://istio.io/latest/blog/2020/proxy-cert/), which points to a giant manual proxy configuration.

Integrating with existing Prometheus seems to be such a common use case, how are we supposed to do it right?

**Comment by luiof** [comment]
Any news?

**Comment by bianpengyuan** [comment]
This is going to be fixed by https://github.com/istio/istio.io/pull/8354
