### ISSUE TITLE
istio_requests_total Indicator clear error

### ISSUE THREAD

**Issue by yuanyiran** [istio/istio#26637]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

**Affected product area (please put an X in all that apply)**

 Extensions and Telemetry

**Affected features (please put an X in all that apply)**

Physical machine

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

istio 1.2.2
kubernetes 1.14.2
helm 2.16.0

**How was Istio installed?**

helm install istio 1.2.2

**Environment where bug was observed (cloud vendor, OS, etc)**

Local physical machine kubernetes cluster istio no cluster deployment

**error describe**

I use this indicator ‘istio_requests_total’ to query the total number of calls to a service. At first, it is normal, and the counter is OK. But when there is no access for a period of time(about 15 minutes), the counter of this service will be cleared, and the number of calls to the service can not be queried, unless it is accessed again.

![image](https://user-images.githubusercontent.com/64528937/90619220-89c07880-e243-11ea-9585-72b4f955cbf3.png)

![image](https://user-images.githubusercontent.com/64528937/90619145-72818b00-e243-11ea-806b-d0fb43e4762a.png)

I want to know the reason for the mistake.Thanks.

**Comment by howardjohn** [comment]
This is intended to avoid unbounded load on that stats endpoint for rapidly changing environments. Also, the version you are using uses Mixer telemetry which is unsupported and deprecated: https://istio.io/news/support/announcing-1.2-eol/

**Comment by yuanyiran** [comment]
How can I count the total number of calls to a service?

**Comment by yuanyiran** [comment]
I use the chart I see in the dependencies menu of Jaeger UI. Is the number marked above the total number of service calls? How is it realized? Is it from Prometheus?

![image](https://user-images.githubusercontent.com/64528937/90761448-002dab00-e316-11ea-9bb8-499ccdb555e7.png)

**Comment by bianpengyuan** [comment]
Yes, in prometheus you are querying time series that is available at the moment. But the history counter value is already persistent in prometheus storage. If you query with `Sum`, you should be able to see the total_request_count. I am going to close this issue, since I believe the question is answer. Please try out newer Istio version, since 1.2 and Mixer was long deprecated. Thanks!

**Comment by yuanyiran** [comment]
Sorry, I'm sorry, I didn't learn very well, but I still don't know how to do it. I used this SQL query, and the result is different from Jaeger. Can you tell me the specific SQL?

sum by (destination_service_name) (istio_requests_total)

**Comment by bianpengyuan** [comment]
Please take a look at https://prometheus.io/docs/prometheus/latest/querying/basics/

**Comment by yuanyiran** [comment]
What I would like to know is, which index should I query, istio_requests_total? Or other indicators provided by isto?

**Comment by bianpengyuan** [comment]
If you want total number of requests, yes, you need to get sum of istio_requests_total.

**Comment by yuanyiran** [comment]
![image](https://user-images.githubusercontent.com/64528937/90847443-192d6f00-e39d-11ea-8be8-d527a16ef2ca.png)

This is my query result now. How can I query Jaeger's result? I read the Prometheus document and still have no clue. Can you give me some reference?
