### ISSUE TITLE
Label info missing in grafana/prometheus for services running outside kubernetes

### ISSUE THREAD

**Issue by kidiyoor** [istio/istio#2664]
In current architecture we use 'mixer adapter for Kubernetes' which generate additional attributes like labels for the given service by looking up POD description.
Since service that run outside Kubernetes say in VM expansion do not use POD, it is registered as endpoint objects and endpoint labels. 'Mixer adapter for Kubernetes' does not look up for endpoints object to generate label attributes ?

Bellow image - Find versions unknown

![screen shot 2018-01-17 at 5 18 51 pm](https://user-images.githubusercontent.com/6630096/35076763-d33b503a-fbae-11e7-858b-c5677e84c304.png)

If I am not wrong - the 'Mixer adapter for Kubernetes' will be replaced by 'pilot pushing necessary information to envoy' ? That might be right place to fix this issue ?

Is there a fix for this problem in current architecture ?

**Comment by kidiyoor** [comment]
@mandarjog @costinm @ldemailly

**Comment by kyessenov** [comment]
cc @mandarjog

**Comment by kidiyoor** [comment]
https://github.com/istio/istio/issues/2367
