### ISSUE TITLE
TestEvents test flake

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#26674]
https://prow.istio.io/view/gs/istio-prow/logs/unit-tests_istio_postsubmit/3441

I have seen other failures as well

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/29122/unit-tests_istio/1330909894945017856

**Comment by howardjohn** [comment]
will be obsolete by https://github.com/istio/istio/issues/23943

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gs/istio-prow/logs/unit-tests_istio_postsubmit/1348674467747860480

**Comment by howardjohn** [comment]
@istio/wg-user-experience-maintainers this is currently one of the flakiest unit test. Can we either prioritize https://github.com/istio/istio/issues/23943, skip the test, or fix it?

**Comment by howardjohn** [comment]
btw, this is probably broken due to https://github.com/kubernetes/kubernetes/issues/95372

**Comment by jasonwzm** [comment]
> @istio/wg-user-experience-maintainers this is currently one of the flakiest unit test. Can we either prioritize #23943, skip the test, or fix it?

migration is still on our plate. I will proceed with skipping it for now.

**Comment by howardjohn** [comment]
btw its not just TestEvents, but also TestEvents_***: https://prow.istio.io/view/gs/istio-prow/logs/unit-tests_istio_release-1.9_postsubmit/1349853372273922048. So probabl all suffer the same race
