### ISSUE TITLE
Istio 1.6.x ingress gateway routing never works

### ISSUE THREAD

**Issue by AceHack** [istio/istio#26709]
**Bug description**
When installing istio with the following config below ingress gateway never works, I can't find any errors in the logs anywhere just no virtual services ever route traffic.  If I use the exact same configuration with Istio 1.5.1 everything works.  Then surprisingly enough after upgrading to 1.6.8 from 1.5.1, 1.6.8 works fine.  Just not with a clean install.  The only difference I notice between a clean install and an upgrade is the istio-pilot services that points to istiod.  This service does not exist with a clean install of 1.6.8.  If I install 1.5.1 this service does exist and when upgrading to 1.6.8 it does not get removed.

[x ] Networking

**Expected behavior**
Istio Ingress and virtual services to work

**Steps to reproduce the bug**
Install istio 1.6.8 with the following config below.
Try to set up a virtual service, no routes will work.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istio 1.6.8
k8s 1.8.6
helm N/A

**How was Istio installed?**
Using istio operator
```
apiVersion: v1
items:
- apiVersion: install.istio.io/v1alpha1
  kind: IstioOperator
  metadata:
    creationTimestamp: "2020-08-20T21:52:03Z"
    finalizers:
    - istio-finalizer.install.istio.io
    generation: 1
    labels:
      operation: Update
      time: "2020-08-20T21:52:03Z"
    - apiVersion: install.istio.io/v1alpha1
      fieldsType: FieldsV1
      manager: operator
      operation: Update
      time: "2020-08-20T21:52:22Z"
    name: istio-control-plane
    namespace: istio-system
    resourceVersion: "4338"
    selfLink: /apis/install.istio.io/v1alpha1/namespaces/istio-system/istiooperators/istio-control-plane
    uid: fb7b1d14-fcb5-4ed3-b61c-d1ded57f2976
  spec:
    addonComponents:
      grafana:
        enabled: false
      istiocoredns:
        enabled: true
      kiali:
        enabled: false
      prometheus:
        enabled: false
      tracing:
        enabled: false
    components:
      base:
        enabled: true
      citadel:
        enabled: false
      cni:
        enabled: false
        namespace: kube-system
      egressGateways:
      - enabled: false
        name: egress
      galley:
        enabled: false
      ingressGateways:
      - enabled: true
        k8s:
          replicaCount: 1
        name: ingress-gateway
      nodeAgent:
        enabled: false
      pilot:
        enabled: true
        k8s:
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: GODEBUG
            value: http2server=0
          - name: PILOT_TRACE_SAMPLING
            value: "100"
          - name: CONFIG_NAMESPACE
            value: istio-system
          replicaCount: 1
          resources:
            requests:
              memory: 512Mi
      sidecarInjector:
        enabled: false
    hub: docker.io/istio
    namespace: istio-system
    tag: 1.5.1
    values:
      cni:
        excludeNamespaces:
        - istio-system
        - kube-system
        - 2269-prometheus
        - 2269-jaeger
        - 2269-kiali
      global:
        controlPlaneSecurityEnabled: false
        defaultResources:
          requests:
            cpu: 51m
            memory: 128Mi
        disablePolicyChecks: false
        enableHelmTest: false
        istioNamespace: istio-system
        mtls:
          auto: false
          enabled: false
        outboundTrafficPolicy:
          mode: ALLOW_ANY
        tracer:
          zipkin:
            address: jaeger-collector.2269-jaeger:9411
      istiocoredns:
        coreDNSImage: coredns/coredns
        coreDNSPluginImage: istio/coredns-plugin:0.2-istio-1.1
        coreDNSTag: 1.6.2
        enabled: true
      sidecarInjectorWebhook:
        enableNamespacesByDefault: true
  status:
    componentStatus:
      AddonComponents:
        status: HEALTHY
      Base:
        status: HEALTHY
      IngressGateways:
        status: HEALTHY
      Pilot:
        status: HEALTHY
    status: HEALTHY
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```
**Environment where bug was observed (cloud vendor, OS, etc)**
Docker Desktop Kubernetes and AWS EKS

**Comment by esnible** [comment]
Could this be the same issue as https://github.com/istio/istio/issues/26104 ?

**Comment by howardjohn** [comment]
Can you please psot the gw/vs configs that are not working and the config dump from ingress (https://github.com/istio/istio/wiki/Troubleshooting-Istio)?

**Comment by Adharsh-Muraleedharan** [comment]
@AceHack --> had a similar issue with routes not getting mapped after an istio update. it was coz there was a name change in the ingressgateway. The gateway name in version 1.5.1 was like "ingressgateway" but the newer version have it like "istio-ingressgateway". As my virtualservices were mapped to the gateway name my routes went missing. Updating the gateway name in virtualservices had fixed it for me. Something like below:

```
spec:
  gateways:
  - istio-ingressgateway.istio-system.svc.cluster.local
  hosts:
  - '*'
```

Not sure whether this is the issue you are facing. but just putting it out there

**Comment by howardjohn** [comment]
We haven't gotten any updates here so cannot debug further. That being said, I am almost certain you are missing a Gateway due to a change in the 1.6 upgrade notes: https://istio.io/latest/news/releases/1.6.x/announcing-1.6/upgrade-notes/#istio-configuration-during-installation. This would explain why upgrade works but new install does not.

**Comment by AceHack** [comment]
I will try to get our K8s team to add more info or validate this is our issue.
