### ISSUE TITLE
Support Apache Dubbo RPC protocol

### ISSUE THREAD

**Issue by zhaohuabing** [istio/istio#26712]
[Apache Dubbo](https://dubbo.apache.org/) is a widely used RPC protocol in the microservices ecosystem, which has already been supported by [Envoy proxy](https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/dubbo_proxy_filter). We need to support it in Istio as well because we already have some Dubbo use cases in the process of migrating to Istio service mesh.

What we need to do:
[] Support default route to the downstream Dubbo service  -- first priority
[] Support Telemetry (Tracing, Metrics, logging)
[] Support advanced routing (Virtual Service)
[] Support traffic policy(Destination Rule)

**Describe alternatives you've considered**
A better approach is to use a "meta protocol" as an abstract layer to represent the routing, traffic policy, and other aspects of different protocols, so we can reduce the work to support more RPC protocols, as [this proposal](https://docs.google.com/document/d/1g3AJNYwbh04-BVajshmcWpeLyGUanbRnihIXU6uIiOY/edit) suggests. However, while the general idea of this proposal is feasible, it needs massive change to the Istio API, codes, and the xDS protocol. So we might need a clearer design and take baby steps towards that direction. 

**Affected product area (please put an X in all that apply)**

[] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
I am concerned about the churn on our APIs adding this will bring. I think our efforts are better spent in a generic solution

**Comment by zhaohuabing** [comment]
@howardjohn No changes to APIs for the default route support as in PR #26713. 

If we were to add more advanced traffic management capabilities we do need to modify virtual service, destination rule, or maybe some other APIs.
