### ISSUE TITLE
virtualservice hosts *.com return 404

### ISSUE THREAD

**Issue by 13567436138** [istio/istio#26746]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
```
[root@master01 virtaulservice]# istioctl proxy-config route istio-ingressgateway-698f645c48-jjcrm.istio-system --name http.80
NOTE: This output only contains routes loaded via RDS.
NAME        DOMAINS     MATCH                 VIRTUAL SERVICE
http.80     *.com       /productpage          bookinfo.istio
http.80     *.com       /static*              bookinfo.istio
http.80     *.com       /login                bookinfo.istio
http.80     *.com       /logout               bookinfo.istio
http.80     *.com       /api/v1/products*     bookinfo.istio


[root@master01 virtaulservice]# kubectl get vs bookinfo -n istio -o yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.istio.io/v1alpha3","kind":"VirtualService","metadata":{"annotations":{},"name":"bookinfo","namespace":"istio"},"spec":{"gateways":["bookinfo-gateway"],"hosts":["*"],"http":[{"match":[{"uri":{"exact":"/productpage"}},{"uri":{"prefix":"/static"}},{"uri":{"exact":"/login"}},{"uri":{"exact":"/logout"}},{"uri":{"prefix":"/api/v1/products"}}],"route":[{"destination":{"host":"productpage.istio.svc.cluster.local","port":{"number":9080}}}]}]}}
  creationTimestamp: "2020-08-22T05:29:21Z"
  generation: 11
  name: bookinfo
  namespace: istio
  resourceVersion: "3878769"
  selfLink: /apis/networking.istio.io/v1beta1/namespaces/istio/virtualservices/bookinfo
  uid: 704b0bba-c457-4abd-8c2f-0f3df18d303e
spec:
  gateways:
  - bookinfo-gateway
  hosts:
  - '*.com'
  http:
  - match:
    - uri:
        exact: /productpage
    - uri:
        prefix: /static
    - uri:
        exact: /login
    - uri:
        exact: /logout
    - uri:
        prefix: /api/v1/products
    route:
    - destination:
        host: productpage.istio.svc.cluster.local
        port:
          number: 9080


[root@master01 virtaulservice]# kubectl get gw bookinfo-gateway -n istio -o yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.istio.io/v1alpha3","kind":"Gateway","metadata":{"annotations":{},"name":"bookinfo-gateway","namespace":"istio"},"spec":{"selector":{"istio":"ingressgateway"},"servers":[{"hosts":["*"],"port":{"name":"http","number":80,"protocol":"HTTP"}}]}}
  creationTimestamp: "2020-08-22T06:03:35Z"
  generation: 13
  name: bookinfo-gateway
  namespace: istio
  resourceVersion: "3878636"
  selfLink: /apis/networking.istio.io/v1beta1/namespaces/istio/gateways/bookinfo-gateway
  uid: 419e2ccb-9d3a-4e24-a5d4-b9cdeaa9e386
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP
```

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
[root@master01 virtaulservice]# istioctl version
client version: 1.7.0-beta.1
control plane version: 1.7.0-beta.1
data plane version: 1.7.0-beta.1 (17 proxies)

[root@master01 virtaulservice]# kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2020-05-12T09:28:18Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"linux/amd64"}
**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by 13567436138** [comment]
the config i have give you ,you can make tests on your own bookinfo demo

**Comment by howardjohn** [comment]
I am not able to reproduce this. This is extensively tested, and you will not give the required information, so I don't see how we can move forward with this issue. Please see https://istio.io/latest/docs/tasks/traffic-management/ingress/ingress-control/ for more information, you are likely not setting the host header

`curl 1.2.3.4/productpage -H "Host: example.com" -v`
