### ISSUE TITLE
DestinationRule certificate must be present on all sidecars or pods fail to startup

### ISSUE THREAD

**Issue by juanamat** [istio/istio#26741]
This is a 'bis repetita placent' of issue #9659
It was fixed by this PR: #9786 which was making the probe succeed even if there was a failure:

```
	CDSUpdated := s.CDSUpdatesSuccess > 0 || s.CDSUpdatesRejection > 0
	LDSUpdated := s.LDSUpdatesSuccess > 0 || s.LDSUpdatesRejection > 0
	if CDSUpdated && LDSUpdated {
		return nil
	}
```
So life was good in 1.4.

But then there was this PR in istio 1.5: #19749 which reverted this change.
The rationale was:
```
We are marking ourselves as ready when we are rejecting config. In my
opinion, this is wrong and dangerous. We depend on these readiness
probes to prove that we have recieved initial config -- including
critical configs like RBAC. If we reject these, then we have not
recieved them. So we should not be ready until we actually get a
successful config update. We do still query for rejects, but only to
make the logs informative.
```

Well in my case I have a DestinationRule configure with MUTUAL tls. Something like:
```
        tls:
          mode: MUTUAL
          caCertificates: /etc/my-certs/cacert
          clientCertificate: /etc/my-certs/cert
          privateKey: /etc/my-certs/key
```

This rule is used only by one pod for some external outgoing flow.
For this pod I do use the istio annotations to be able to mount those files on the sidecar.

The problem is that other unrelated pods in the same k8s namespace do not start then and in the sidecar logs I see something like (edited):
```
gRPC config for type.googleapis.com/envoy.api.v2.Cluster rejected: Error adding/updating cluster(s) outbound|port||host: Invalid path: /etc/my-certs/cacert, outbound|port|tls-originatio|shost: Invalid path: /etc/my-certs/cacert
```

I kind of understand the rationale of the revert but, at the same time, if we do not have a way to limit the scope of the DestinationRule besides the current namespace then reverting was premature in 1.5.x.

Having a separate namespace for this single pod that uses the DestinationRule is not a very practical solution.

**Comment by b4456609** [comment]
Same issue here

**Comment by lehoangnguyen** [comment]
We got the same issue and the only way is to set exportTo to the current namespace. However, we need the service available to all namespaces which the exportTo doens't work in our case. Anyway, I think it's a bug since all of sidecars would be failed with missing certs which they don't need at all

**Comment by lautou** [comment]
/reopen
Issue persists in RH OSSM 1.6 (Istio 1.6). Please re-open
