### ISSUE TITLE
Istio 1.7: Istiod reports wrong version in Prometheus metrics

### ISSUE THREAD

**Issue by cagataygurturk** [istio/istio#26740]
**Bug description**

On 1.7.0 release, Istiod reports its version as 1.7.0-rc.4 

Here is the output from metrics endpoint:

```
istio_build{component="pilot",tag="1.7.0-rc.4"} 1
```

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

control plane version: 1.7.0
data plane version: 1.7.0 (5 proxies)

**Comment by cagataygurturk** [comment]
The issue does not exist anymore.

**Comment by howardjohn** [comment]
```
$ pilot-discovery version
version.BuildInfo{Version:"1.7.0", GitRevision:"2022348138e47498c4b54995b4cb5a1656817c4e", GolangVersion:"go1.14.7", BuildStatus:"Clean", GitTag:"1.7.0-rc.4"}
```

Seems its still there - not sure what happened in your env that it isn't showing up. I suspect we have 2x tags on the same commit, and it picks the wrong one

**Comment by howardjohn** [comment]
```
~/go/src/istio.io/istio ((HEAD detached at 1.7.0-rc.4))
$ ./common/scripts/report_build_info.sh
istio.io/pkg/version.buildVersion=2022348138e47498c4b54995b4cb5a1656817c4e
istio.io/pkg/version.buildGitRevision=2022348138e47498c4b54995b4cb5a1656817c4e
istio.io/pkg/version.buildStatus=Clean
istio.io/pkg/version.buildTag=1.7.0
istio.io/pkg/version.buildHub=docker.io/istio
```

I still think its the double tag, but the script seems right...

**Comment by howardjohn** [comment]
@cagataygurturk did the metric change? I see rc4 in mine as well

**Comment by douglas-reid** [comment]
Can this be closed now?

**Comment by jwendell** [comment]
Yes, this was fixed by https://github.com/istio/common-files/pull/300
