### ISSUE TITLE
Ask to revert "Remove unneeded constructCSRHostName" 

### ISSUE THREAD

**Issue by hovonako** [istio/istio#26754]
Hi Istio Team,
According to the latest commit on Master Branch, SAN URI of Workload CSR was missed. We are using this identity to sign new Workload Certificate on custom External CA
Can I revert pull request "[Remove unneeded constructCSRHostName](https://github.com/istio/istio/pull/26084)" to keep this field ?

Thanks,
**Bug description**
**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[x] Multi Cluster
[] Virtual Machine
[] Multi Control Plane

**Expected behavior**
CSR from Citadel should have URI = spiffe://<identity>
**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by hovonako** [comment]
@howardjohn can you take a look?

**Comment by howardjohn** [comment]
done: https://github.com/istio/istio/blob/2be2ef65a57ac5652d6629e686c75bc4f51d25eb/security/pkg/nodeagent/cache/secretcache.go#L857
