### ISSUE TITLE
Question: about wasm

### ISSUE THREAD

**Issue by pantianying** [istio/istio#26757]
Istio 1.5 supports wasm plug-in, but it seems that it is rarely mentioned in 1.6 and 1.7 versions. I want to know about the performance and stability of wasm. Is it recommended to use this plug-in in in production environment? Will future versions of istio continue to support this feature？

**Comment by carolynhu** [comment]
@pantianying We will publish wasm perf number for release-1.7

**Comment by douglas-reid** [comment]
@pantianying Istio extensions via Wasm will continue to be supported moving forward in Istio. As @carolynhu relates, there were perf numbers published for 1.7 ([link](https://istio.io/latest/docs/ops/deployment/performance-and-scalability/)) and this will continue to be done for upcoming releases.

There is high-priority work for Wasm work underway for the 1.8 release (memory usage/lifecycle improvements). I would expect more information to be included in release notes and on the website.

I'm going to close this issue. For further discussion of Wasm stablity, please follow-up the discuss forum or via slack.
