### ISSUE TITLE
Request to customize HTTTRoute default settings

### ISSUE THREAD

**Issue by wangmeng** [istio/istio#26750]
**Describe the feature request**
As we have dozens of micro services in the same kube cluster, to have a unified and common configuration of VirtualService, is there any way that we can specify or customize some HTTTRoute default settings, like route level timeout setting, and also http match ignoreUriCase setting.

`virtualService->HTTPRoute->timeout`
https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPRoute

`virtualService->HTTPMatchRequest->ignoreUriCase`
https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPMatchRequest

We would like to:
1. Set route level timeout 30s as the default value for whole Istio, and also be able to overwrite the value in a specific VirtualService definition.   
2. Set ignoreUriCase to be true for whole Istio, and also be able to overwrite the behavior in a specific VirtualService definition.   

In this way, we don't need to specify these settings in each VirtualService, and it is also easier to maintain from operation aspect. 
I am aware that ignoreUriCase can only support `exact` and `prefix` URI matches, it would be still preferred to set at the istio level.  
Thanks.

**Describe alternatives you've considered**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
cc @linsun @GregHanson @nrjpoddar

**Comment by linsun** [comment]
Thanks @wangmeng!  We are currently working on an [RFC](https://docs.google.com/document/d/1hY-ShGY6sgwWUw0NGLvsDWXWm3wNLvhM4HHuRjFzRT0/edit?usp=sharing) for adjusting timeout globally, perhaps we can add `ignoreUriCase` in there as well.

@GregHanson thoughts?

**Comment by wangmeng** [comment]
For the backgroud info about regex & v2 API deprecation. Thanks.

https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route_components.proto.html?highlight=case_sensitive
```
regex
This field has been deprecated in favor of safe_regex as it is not safe for use with untrusted input in all cases.
```

https://www.envoyproxy.io/docs/envoy/latest/api/api_supported_versions
```
    v2 xDS API (deprecated, end-of-life EOY 2020). This API will not accept new features after the end of Q1 2020.

    v3 xDS API (active, end-of-life EOY 2021). Envoy developers and operators are encouraged to be actively adopting and working with v3 xDS.
```

@linsun

**Comment by howardjohn** [comment]
We have a bunch of issues around defaults, lets consolidate into https://github.com/istio/istio/issues/6861 to clean things up. Please also see https://docs.google.com/document/d/1hY-ShGY6sgwWUw0NGLvsDWXWm3wNLvhM4HHuRjFzRT0/ which is a design doc for this being actively worked on.
