### ISSUE TITLE
Remove gogo entirely from Istio

### ISSUE THREAD

**Issue by sdake** [istio/istio#26751]
removal of gogo. For many reasons.

**Comment by tanjunchen** [comment]
+1

**Comment by sdake** [comment]
PR: https://github.com/istio/istio/issues/26010
PR: https://github.com/istio/tools/pull/1183
PR: https://github.com/istio/common-files/pull/303
PR: https://github.com/istio/istio/pull/26769
PR: https://github.com/istio/api/pull/1607

**Comment by sdake** [comment]
I wasnt sure which WGs to tag for review. This set of PRs will have alot of impact across networking but also other areas. If your WG is not interested in reviewing this work, please remove your workaround from the list.

Cheers,
-steve

**Comment by zackzhangkai** [comment]
Does this have been fixed already?
