### ISSUE TITLE
1.7 If the default name "isto-ingressgateway" is changed, the isto-operator will not recognize the configuration

### ISSUE THREAD

**Issue by lihuixian001** [istio/istio#26758]
**Bug description**

If the default name "isto-ingressgateway" is changed, the isto operator will not recognize the configuration

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

kubectl apply -f ./istio-system.yaml

```
...
...
    ingressGateways:
    - name: istio-gateway
      enabled: false
      k8s:
        serviceAnnotations:
          service.beta.kubernetes.io/alibaba-cloud-loadbalancer-id: "xxxx"  
          service.beta.kubernetes.io/alibaba-cloud-loadbalancer-force-override-listeners: "true"  
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 2000m
            memory: 1024Mi
....
...
...
```

**How was Istio installed?**

Istio Operator Install

**Comment by howardjohn** [comment]
@lihuixian001 what is the expectation here? You have `enabled: false`, so no GW will be created. I tested with `enabled: true` and it looks right

**Comment by ostromart** [comment]
Yes, more info needed here about what output is produced and what you expect. I expect a new gateway called istio-gateway to be created, since you cannot change the name of istio-ingressgateway from the base profiles, you can only disable it and create a different gw with a different name.

**Comment by ostromart** [comment]
Please reopen with requested information if this is still an issue.
