### ISSUE TITLE
Retry attempted on already attempted host

### ISSUE THREAD

**Issue by MaheshGPai** [istio/istio#26760]
**Bug description**
On receiving 503 service unavailable error response from an upstream server which is down, istio retries the request to the same endpoint as per istio’s default retry behavior.
So calls are getting retried to the same server three times, which is not be required.

[ ] Docs
[ ] Installation
[ ] Networking
[X] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Istio should not retry to an already attempted host

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
K8S Version v1.17.4
Istio Version 1.3.6

**How was Istio installed?**
Helm

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by MaheshGPai** [comment]
This behaviour is seen inspite of the host predicate set to **envoy.retry_host_predicates.previous_hosts**
`"route": {
           "cluster": "outbound|8080||upstream-service.foo.svc.cluster.local",
           "timeout": "0s",
           "retry_policy": {
            "retry_on": "connect-failure,refused-stream,unavailable,cancelled,resource-exhausted,retriable-status-codes",
            "num_retries": 2,
            "retry_host_predicate": [
             {
              "name": "envoy.retry_host_predicates.previous_hosts"
             }
            ],
            "host_selection_retry_max_attempts": "5",
            "retriable_status_codes": [
             503
            ]
           },
           "max_grpc_timeout": "0s"
          },
          "decorator": {
           "operation": "upstream-service.foo.svc.cluster.local:8080/*"
          },
`

**Comment by MaheshGPai** [comment]
This behaviour is seen inspite of the host predicate set to **envoy.retry_host_predicates.previous_hosts**
`"route": {
           "cluster": "outbound|8080||upstream-service.foo.svc.cluster.local",
           "timeout": "0s",
           "retry_policy": {
            "retry_on": "connect-failure,refused-stream,unavailable,cancelled,resource-exhausted,retriable-status-codes",
            "num_retries": 2,
            "retry_host_predicate": [
             {
              "name": "envoy.retry_host_predicates.previous_hosts"
             }
            ],
            "host_selection_retry_max_attempts": "5",
            "retriable_status_codes": [
             503
            ]
           },
           "max_grpc_timeout": "0s"
          },
          "decorator": {
           "operation": "upstream-service.foo.svc.cluster.local:8080/*"
          },
`

**Comment by ramaraochavali** [comment]
How many endpoints does the service has?

**Comment by howardjohn** [comment]
this might be the same as https://github.com/istio/istio/issues/24512, although looks like this is not weighted cluster
