### ISSUE TITLE
support gRPC streaming message count in telemetry

### ISSUE THREAD

**Issue by ckcd** [istio/istio#26765]
**Describe the feature request**
For now the istio standard metrics (e.g. `istio_request_duration_milliseconds`) treat gRPC streaming(bidi) as one big request, this makes the latency very large and not useable.

So, can we add message count for long-running gRPC calls (bidi)? For now envoy support this in: https://github.com/envoyproxy/envoy/pull/8531

And I found a former try in https://github.com/istio/proxy/pull/2137 cc @kyessenov 

**Describe alternatives you've considered**
maybe change the behavior of current metrics, or add some new metrics, e.g. `request.grpc.message_count`, `response.grpc.message_count`.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by kyessenov** [comment]
Are you happy with the final bi-di count or you want interval reporting for long-living gRPC requests?

**Comment by mandarjog** [comment]
We want interval reporting.

**Comment by kyessenov** [comment]
What about long-living HTTP requests? This has been the contentious topic.

**Comment by mandarjog** [comment]
I think it is especially important for long-lived connections. Otherwise there is not visibility into what is happening in the interim.
When debugging an on-going issue, current counts are very important.

**Comment by kyessenov** [comment]
This is in 1.8 and supports interval reporting (just like TCP).
