### ISSUE TITLE
Promote "Gateway Network Topology" out of experimental

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#26783]
https://preliminary.istio.io/latest/docs/ops/configuration/traffic-management/network-topologies/ is currently marked as experimental. We should do any work required to move this to alpha/beta

@nrjpoddar @jacob-delgado

**Comment by linsun** [comment]
subscribe cc @rvennam

**Comment by linsun** [comment]
+1 to this.  I ran through the tasks in network topology today with master, it works fairly well.

**Comment by nrjpoddar** [comment]
We kept it experimental as Networking & TOC members weren't sure about Gateway class API from K8s coming down the line and requiring to deprecate this or give a migration path for our users. However, I think we can promote this API after following items are done:

1. Unhide the MeshConfig options from reference docs

**Comment by IGassmann** [comment]
@nrjpoddar is there an open issue for "1. Unhide the MeshConfig options from reference docs"?

**Comment by nrjpoddar** [comment]
> @nrjpoddar is there an open issue for "1. Unhide the MeshConfig options from reference docs"?

Nope but you can use this issue as reference instead of creating a new one. Your PRs towards this effort would be much appreciated, thanks!
