### ISSUE TITLE
Multicluster book-info version not routing 

### ISSUE THREAD

**Issue by ECuRyDIN** [istio/istio#26789]
I tried setting up multilcluster using replicated control planes and the version routing book-info example. I do not see black or red stars after gong through the entire tutorial. I am not sure what I am missing. It is showing this error:
Error fetching product reviews!
Sorry, product reviews are currently unavailable for this book.

**Bug description**
Black or red stars not showing up in product page and when after logging in as user 'jason'. It showing this error:
Error fetching product reviews!
Sorry, product reviews are currently unavailable for this book.

[x] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Black and red stars should show up in productpage

**Steps to reproduce the bug**
Follow the doc to setup multicluster + version routing:
https://istio.io/latest/blog/2019/multicluster-version-routing/
head over to http://$GATEWAY_URL/productpage,  black or red stars should show up when logged in as user jason

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istioctl version:
client version: 1.5.6
control plane version: 1.5.6
data plane version: 1.5.6 (6 proxies)

Kubectl version: Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.10", GitCommit:"89d8075525967c7a619641fabcb267358d28bf08", GitTreeState:"clean", BuildDate:"2020-06-23T02:52:37Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
Istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**
AKS

**Comment by alekodu** [comment]
I have the same issue with Istio 1.5.2.

**Comment by alekodu** [comment]
> I have the same issue with Istio 1.5.2. Did you find out what the problem is?

Anyone that could help with this issue?

**Comment by alekodu** [comment]
Anyone that could help? I have also tested with Istio 1.5.10 and keep getting the same problem.
