### ISSUE TITLE
TestTraffic/sniffing/auto-tcp_a->headless_from_cluster-0 flakes frequently

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#26798]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/26638/integ-pilot-k8s-tests_istio/18950

@howardjohn has some fix recently

**Comment by stevenctl** [comment]
I think this is fixed for single cluster, will wait a couple days now that it's re-enabled before closing this. 

We still get some failures on http/grpc in multicluster mode. I think we're hitting limits on our test infra, can't replicate in GKE clusters. 
```
=== RUN   TestTraffic/sniffing/auto-http_a->vm_from_cluster-1
2020-09-09T17:17:59.568511Z	info	tf	=== BEGIN: Test: 'pilot[TestTraffic/sniffing/auto-http_a->vm_from_cluster-1]' ===
    traffic.go:69: call for auto-http a->vm from cluster-1/0 failed, retrying: failed calling a->'http://vm.echo-1-70707.svc.cluster.local:81/': rpc error: code = Unknown desc = 20/20 requests had errors; first error: Get "http://vm.echo-1-70707.svc.cluster.local:81": read tcp 10.20.0.10:59864->10.255.20.200:81: read: connection reset by peer
```

**Comment by stevenctl** [comment]
We've disabled TCP sniffing tests so this passes but it isn't fixed yet. In the multicluster pilot job I see a lot of connection resets for http/grpc.

**Comment by stevenctl** [comment]
https://prow.k8s.io/view/gcs/istio-prow/pr-logs/directory/integ-pilot-multicluster-tests_istio/999

**Comment by howardjohn** [comment]
Not stale

**Comment by stevenctl** [comment]
Not stale
