### ISSUE TITLE
Can't able to connect to MS SQL server with istio envoy proxy

### ISSUE THREAD

**Issue by MANOHAR452** [istio/istio#26807]
I have meshConfig.outboundTrafficPolicy.mode=ALLOW_ANY, mTLS is disabled and from pod which has envoy proxy can't able to connect to MS Sql Server, but able to connect to other external services ex. https://www.google.com , I don't have any policies around it.
istio version: 1.6.2, it used to work before.

Tried connecting to MS SQL server with out envoy proxy, able to connect. Not sure where is the problem.

Can any one please help in finding the issue.

**Comment by esnible** [comment]
There are two closed issues about MySQL.  See https://github.com/istio/istio/issues/14743 for background.

**Comment by howardjohn** [comment]
This is documented in https://preliminary.istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/
