### ISSUE TITLE
Can the "istio control plane" only run in a k8s cluster?

### ISSUE THREAD

**Issue by lijiapengsa** [istio/istio#26800]
**Describe the feature request**
Check the documentation, I have to start in the k8s cluster `control plane`. 
But I don't have a k8s cluster. My environment is all virtual machines.

![image](https://user-images.githubusercontent.com/7970836/91160133-9f2e1a80-e6fb-11ea-979e-ab78069ee12d.png)

**Describe alternatives you've considered**
Can the "istio control plane" run directly on a virtual machine?
Then manage the data plane on the virtual machine.

Since you choose to embrace virtual machines, why not be thorough and fully support virtual machine deployment? Is this feature planned in the future?

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
We don't currently support running Istio without a connected api-server. I think the config in order to do this exists but its not something we test or document

**Comment by lijiapengsa** [comment]
Is there any plan to support it? Similar to https://kuma.io/ this solution. `control plane` supports RESTApi to update the configuration.
If istio supports it, I think istio will do better than kuma

**Comment by howardjohn** [comment]
We support reading config from file. But I haven't heard any discussion about making this an officially support deployment topology - it's mostly for testing

**Comment by huangwei2013** [comment]
@lijiapengsa   Agree with you ：）
 @howardjohn  Running from local binary may be useless for Production  Env, but a good way to study Istio (of source code).

**Comment by howardjohn** [comment]
@huangwei2013 there is an important distinction between running the binaries locally connected to an api-server, and running the binaries without any kubernetes involved. The former is perfectly fine, used by some in production and I personally nearly exclusively develop this way (https://gist.github.com/howardjohn/458f4f9416a3fa1a014feb168e9922ea for how I set it up)

**Comment by huangwei2013** [comment]
@howardjohn    thx a lot for sharing.

I run in this way(kind of similar with yours)：
`
[compiled]  pilot-discovery
[binary] envoy （from istio‘s source package）
[compiled]  pilot-agent （but mostly un-used）

And

[copied] pem etc. (from istio's source package)
[copied] envoy-rev0.json etc. (from a docker-run istio instance)
[install some other way] local K8S of single-node , and its configure files
`

**Comment by howardjohn** [comment]
https://blog.howardjohn.info/posts/local-gateway/ describes running a gateway outside of k8s
