### ISSUE TITLE
EnvoyFilter ext_authz disable routing for specific paths

### ISSUE THREAD

**Issue by mstrYoda** [istio/istio#26805]
**Describe the feature request**

I want to avoid routing requests to OPA authz sidecar for kubernetes healthcheck requests.

There is a feature on envoy described here: https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/ext_authz_filter#per-route-configuration

How can we implement it in Istio?

Here is our EnvoyFilter:

```
apiVersion: v1
items:
- apiVersion: networking.istio.io/v1alpha3
  kind: EnvoyFilter
  metadata:
    creationTimestamp: "2020-08-20T09:08:38Z"
    generation: 15
    name: nginx-ext-authz
    namespace: default
    resourceVersion: "971754"
    selfLink: /apis/networking.istio.io/v1alpha3/namespaces/default/envoyfilters/nginx-ext-authz
    uid: 22658dcb-9bdb-4f7a-99fc-fd7214fc5e5b
  spec:
    configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: envoy.http_connection_manager
              subFilter:
                name: envoy.router
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.ext_authz
          typed_config:
            '@type': type.googleapis.com/envoy.config.filter.http.ext_authz.v2.ExtAuthz
            grpc_service:
              google_grpc:
                stat_prefix: ext_authz
                target_uri: 127.0.0.1:9090
            status_on_error:
              code: ServiceUnavailable
            with_request_body:
              allow_partial_message: true
              max_request_bytes: 8192
    workloadSelector:
      labels:
        app: nginx
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

When I add another filter like below:

```
- applyTo: HTTP_ROUTE
      match:
        context: SIDECAR_INBOUND
        routeConfiguration:
          portNumber: 8080
          vhost:
            name: inbound|http|8080
      patch:
        operation: MERGE
        value:
          match:
            prefix: /headers
          typed_per_filter_config:
            envoy.ext_authz:
              '@type': type.googleapis.com/google.protobuf.Struct
              value:
                disabled: true
```

I can send request to /healthcheck path but all other requests are fails.

**Describe alternatives you've considered**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by carpenike** [comment]
Any chance you’ve gotten this further? I have a similar goal but I want to exclude external Auth for API endpoints in an app that has built in Auth there.

**Comment by mstrYoda** [comment]
Actually no, I asked in istio slack channel and got these answer: https://istio.slack.com/archives/C3TEGNZ7W/p1598339535006600

**Comment by carpenike** [comment]
Interesting... so would the work being done in Envoy via https://github.com/envoyproxy/envoy/issues/11832 solve it or would there also be work needed in Istio as well?

Have you considered integrating OPA into the flow as well?

**Comment by mstrYoda** [comment]
Well I do not know if it is requires a work in istio too.

But as a workaround I wrote a rego policy to allow healthcheck paths inside OPA.

**Comment by myidpt** [comment]
@yangminzhu Could you give update? Are you working on a related proposal?

**Comment by yangminzhu** [comment]
Using the `per_route` is theoretically possible but practically it is very hard (or impossible in some cases) because it needs a dedicated routing rule to override the ext_authz filter config.

The much better way is to add the matching API directly in the ext_authz filter as proposed in https://github.com/envoyproxy/envoy/issues/11832. I have an ongoing PR to implement this (https://github.com/envoyproxy/envoy/pull/12964).

The ongoing PR is temporarily put on hold because there is another proposal to solve this problem in a more general way by adding the matching API in FilterChain level so that it can be used by any filters (not only ext_authz). I have discussed this in Envoy side and we have reached agreements that I will (this week) investigate if the general proposal can be quickly done to meet the Istio 1.8 timeline, if not we will merge the ongoing PR as a short term solution and continue working on the general proposal as the long term solution.

**Comment by yckbilly1929** [comment]
after comparing the documentations, looks like we are very close to the solution, i think we can support conditionally enabling ext_authz if istio HTTPMatchRequest includes the field 'metadata'
https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPMatchRequest

should show up here in this field 'filter_metadata'
https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/base.proto#envoy-v3-api-msg-config-core-v3-metadata

and consumable here in this field 'filter_enabled_metadata'
https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_authz/v3/ext_authz.proto

**Comment by haf** [comment]
Related https://github.com/istio/istio/issues/29734 — @yckbilly1929 @mstrYoda — but at Gateway level

**Comment by howardjohn** [comment]
@yangminzhu is this fixed by the new ext authz stuff?

**Comment by TamasNeumer** [comment]
@yangminzhu The path based enablement of extAuth would be of my interest too. Any updates on this?

**Comment by yangminzhu** [comment]
@TamasNeumer this should now be supported by the new CUSTOM action in authorization policy, you can use the `path` field to conditionally trigger the ext-authz flow. See more in https://istio.io/latest/blog/2021/better-external-authz/ and https://istio.io/latest/docs/tasks/security/authorization/authz-custom/.

**Comment by johnzheng1975** [comment]
> 

@yangminzhu , Thanks for letting us know works for new "authorization policy". 
How about the previous ext-authz, does it supported “disable for specific path”? Thanks.

**Comment by johnzheng1975** [comment]
Reopen this issue to remind my question, sorry for that.
Then I will decide:  use new "authorization policy" **_OR_** keep using ext-authz? Thanks a lot.

**Comment by mstrYoda** [comment]
> > 
> 
> @yangminzhu , Thanks for letting us know works for new "authorization policy". How about the previous ext-authz, does it supported “disable for specific path”? Thanks a lot.

Can we add support for disabling ext_authz for specified paths to the old versions? I am volunteer to develop this improvement.

**Comment by johnzheng1975** [comment]
ok, I already used new version: authorization policy external authorization
I think this is great! 
- It had full function as envoyfilter ext-authz
- Both request and body can be forwarded to authz service
- It support "Path of healthcheck need not do authz"
- The definition is more friendly to user.
So I need not care old envoyfilter ext_authz, close it

**Comment by leefernandes** [comment]
Isn't the problem with using Authorization Policy that it does not support request body?

https://github.com/istio/istio/issues/28988

**Comment by leefernandes** [comment]
request body is now supported by AuthorizationPolicy, see here. https://github.com/istio/istio/issues/31182#issuecomment-1311735880
