### ISSUE TITLE
Support Pod enpoint's weight setting

### ISSUE THREAD

**Issue by l8huang** [istio/istio#26809]
WorkloadEntry provides a way to set non-Pod endpoint's weight:

```
apiVersion: networking.istio.io/v1beta1
kind: WorkloadEntry
metadata:
  name: foo
spec:
  address: 192.168.0.1
  weight: 8080
  labels:
    app: foo
```

As https://istio.io/latest/blog/2020/workload-entry/ said:

> Notice that the ServiceEntry can reference both Pods and WorkloadEntries, using the same selector. VMs and Pods can now be treated identically by Istio, rather than being kept separate.

But when we use a ServiceEntry to reference both Pods and WorkloadEntries,  and want to do traffic splitting by setting weight, currently Pod endpoint's weight can't be specified, the generated Envoy endpoint's wight is `1`:

```
          {
           "endpoint": {
            "address": {
             "socket_address": {
              "address": "192.168.0.100",
              "port_value": 8080
             }
            }
           },
           "load_balancing_weight": 1
          },
```

For making the traffic splitting case works, Istio should support Pod endpoint weight setting.

This case was mentioned in another issue's comment:

> For this, workloadentry allows setting weight, but i donot think we can do that for a pod. If we do have the use case, we can provide a way to do that.

_Originally posted by @hzxuzhonghu in https://github.com/istio/istio/issues/25898#issuecomment-676206810_

Affected product area (please put an X in all that apply)

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

Affected features (please put an X in all that apply)

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Comment by howardjohn** [comment]
What is the use case? Generally idea of weight is that we may not know the backing topology of a ServiceEntry since its external to the mesh. For pods, we know its backed by exactly one pod.

**Comment by l8huang** [comment]
The use case is we have multiple k8s clusters, each of them has Istio deployed, on one k8s cluster's ingress gateway we want to split a fixed ratio of traffics to another cluster's ingress gateway.

WorkloadEntry allows setting weight, IMHO setting pod's endpoint weight should also be supported.

**Comment by hzxuzhonghu** [comment]
We can always assume the pod weight=1 and set the workloadentry weight accordingly, doesn't it satisfy your need?

**Comment by howardjohn** [comment]
Seems more like use case for https://preliminary.istio.io/docs/ops/traffic-management/locality-load-balancing/

**Comment by l8huang** [comment]
> We can always assume the pod weight=1 ...
I'm afraid we can't assume the number of pod.

**Comment by l8huang** [comment]
Unfortunately, locality load balancing doesn't work for us, in our setup, Istio is scoped to one of the clusters, it doesn't aware pods in other clusters. And nodes in one cluster are belong to same 'region/zone/subzone'.

**Comment by hzxuzhonghu** [comment]
What you want is set a big weight for local cluster endpoints and small weight for remote clusters? something like local cluster takes priority?

**Comment by l8huang** [comment]
@hzxuzhonghu yes, local cluster endpoints take most of traffics.

**Comment by hzxuzhonghu** [comment]
We have `cluster local` service settings in `MeshConfig_ServiceSettings`, which can be used to config one service can be accessed from the same cluster. But if we want to support like 80% traffic redirected to local cluster and 20% to remote cluster, i think we need to expand the API like the `LocalityLoadBalancerSetting_Distribute`

**Comment by l8huang** [comment]
IMO, this is not a typical locality local balancing issues, the WorkloadEntry(remote cluster endpoint) is the VIP of the remote cluster's ingress gateway, in this case Envoy doesn't know the Pod endpoint's status in remote cluster. 

Looks like locality load balancing is a better solution when all endpoints in a Envoy load assignment are Pod's IP.

**Comment by hzxuzhonghu** [comment]
We never suggest making a gateway as the WLE. Not sure if this can work.  For multicluster, the gateway is set a weight according to the endpoints number behind.

**Comment by christian-posta** [comment]
This use case makes sense to me. @l8huang seem to want to make use of Envoy's weighted load balancing (without respect to locality)

**Comment by durd07** [comment]
Is there a plan to support Envoy's weighted load balancing (without respect to locality)?

**Comment by hzxuzhonghu** [comment]
I am still not aware of setting the weight  per pod.
