### ISSUE TITLE
Enable DNS resolution in sidecar Istio Agent

### ISSUE THREAD

**Issue by rshriram** [istio/istio#26826]
**Describe the feature request**

Allowing the sidecar to resolve the application's DNS requests is useful in a variety of scenarios:
1. in multi-cluster, cross cluster dns resolution will become easier - we will no longer need to create dummy k8s services in a cluster just to get dns resolution
2.  for service entries that do not have a VIP, we can allocate class E addresses (not routable in any network), and have the sidecar resolve the app's requests to these hosts to these addresses. The sidecar can then do proper dns resolution and forward traffic. This split resolution model, with fake VIPs will allow us to eliminate wildcard original dst listeners for tcp services (0.0.0.0:3306) that have been known to cause incorrect routing (e.g., if we have two mysql aws rds services on same port with resolution set to DNS, the sidecar will incorrectly forward traffic from the second service to the first, as it has only one listener on 3306 that forwards to the host specified by the first service).

This will also eliminate our dependency on the coredns plugin, eliminating the need for users to tinker with their k8s clusters' dns configs to forward to our plugin to resolve .global addresses (in many cases, mesh admins are unwilling/unable to change the cluster setups done by their k8s teams).

A preliminary work was done in https://github.com/istio/istio/pull/24919 and spectacularly failed due to the unstable dns implementation in Envoy. The plan of action is to attempt to do this in istio agent.

See https://docs.google.com/document/d/14g079QxTB0ZydbuYctwLHZfzTYOSOm5sNHxMFyg8FFE/edit for the larger context.
 
**Describe alternatives you've considered**

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by hzxuzhonghu** [comment]
cc

**Comment by pisto** [comment]
cc

**Comment by hzxuzhonghu** [comment]
https://github.com/istio/istio/pull/24919 has done this. I think it is not enabled yet

**Comment by rshriram** [comment]
This is complete. It is enabled in preview profile and will be enabled by default in 1.9
