### ISSUE TITLE
Bootstrap patch API

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#26830]
There has been frequent request to be able to patch boostrap in a generic way, ala `EnvoyFilterAPI for boostrap`

Use cases
1. Add new static clusters. (some clusters are `required` to be static)
2. Add/Update/modify stats configuration.
3. Add or update `runtime` configuration.

Existing solutions.

## sidecar.istio.io/bootstrapOverride ##

use `env=ISTIO_BOOTSTRAP_OVERRIDE` or `sidecar.istio.io/bootstrapOverride`  to point to custom_bootstrap.json
   The contents of `custom_bootstrap.json` are then merged into bootstrap proto.
    
    This solution cannot be used to change the defaults in an upgradeable way.
    It is possible to change the `istio-sidecar-injector` config map, but it does not survive upgrades.

## Overmount /var/lib/istio/envoy/envoy_bootstrap_tmpl.json ##
You can change the full bootstrap template, but even this is not upgrade safe.

Ideas
1. Sidecar injector watches EnvoyFilter#bootstrap or a new CR and sends the patches as `ENV` at the time of injection.
2. Istiod does boostrap generation where it can apply and validate bootstrap and send.

@kyessenov

**Comment by mandarjog** [comment]
cc @costinm @rshriram

**Comment by douglas-reid** [comment]
Do we have a list of the use case for bootstrap override?  Can this be achieved by Envoy-side changes to support dynamic config for traditional bootstrap values?

**Comment by kyessenov** [comment]
- Support for WasmService was requested. That is intentionally a singleton dis-associated from listeners.
- Any extension that uses envoy gRPC client requires a static cluster definition. E.g. `ext_authz`.

**Comment by mariopmartins** [comment]
Hey everyone. 
Do we have any updates on this feature request? Do we have a design or plan on how to do it? 
On our project, we have been planning on using this feature to deploy a WASM service to Envoy Sidecars and I wanted to be sure this will satisfy our needs.
Thanks, Mario

**Comment by mandarjog** [comment]
Not stale.

**Comment by mandarjog** [comment]
@kyessenov can we do something more focused for WasmService?

**Comment by kyessenov** [comment]
CC @howardjohn. There are typically two workarounds: 
1. Add some pod annotation that is injected verbatim into bootstrap. This doesn't work well on ingress, but can be fixed too.
2. Yet another meshconfig option.

**Comment by mariopmartins** [comment]
Hey guys, 
I'm trying to find ways that I help with this, but it is a little unclear how you guys want to approach it.
I was thinking that Wasm Service deployment should be done with another CRQ, just like what was done for Wasm Filters. Are there limitations on that?

**Comment by gxb5443** [comment]
Hey is there any update on this? I'm also interested in using WasmServices

**Comment by bianpengyuan** [comment]
Not stale

**Comment by kyessenov** [comment]
You can customize the static listeners by changing the bootstrap template. You can override the file either in the container, or mount another one and point the sidecar to use that instead.
