### ISSUE TITLE
[DOCS] Global DNS in examples .global

### ISSUE THREAD

**Issue by andreimc** [istio/istio#26837]
**Bug description**

.global is actually a valid TLD and by following your examples you essentially lose access to that TLD 

I would suggest someting like istioglobal as the TLD.

[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

not overwrite an existing TLD

**Steps to reproduce the bug**

https://preliminary.istio.io/latest/docs/setup/install/multicluster/gateways/

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.7.0

**How was Istio installed?**
istioctl
**Environment where bug was observed (cloud vendor, OS, etc)**
AWS EKS

**Comment by howardjohn** [comment]
The documentation no longer recommends this, see updated docs: https://preliminary.istio.io/latest/docs/setup/install/multicluster/. Thanks!
