### ISSUE TITLE
Upstream response time metric

### ISSUE THREAD

**Issue by dataviruset** [istio/istio#26848]
I haven't been able to find any metric in Prometheus that gives me the upstream response time for a certain service in Istio. According to the [documentation](https://istio.io/latest/docs/reference/config/metrics/), only `istio_request_duration_milliseconds` (request duration) is available. But this also includes the client request time, and will be high if there is a network delay on the public internet, for example, or if the client is uploading a big file. We wanna use this metric to configure alerts if our services in Istio are responding slowly.

Actually the name `istio_request_duration_milliseconds` doesn't match with what I found in Prometheus which is `istio_request_duration_seconds_bucket`, but maybe that can differ.

An alternative I considered was to scrape the Envoy request logs for more information there, but it would not be nearly as convenient as having the metrics in Prometheus just like the request duration.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by bianpengyuan** [comment]
`istio_request_duration_milliseconds` is captured at both client side and server side. See the `Reporter` label which tells you whether this time series is from source or destination. 

Which istio version are you using? The metric used to be `istio_request_duration_seconds` but the name and unit has been updated to `istio_request_duration_milliseconds` for quite a while (maybe two or three releases ago) after we migrated to telemetry v2.

**Comment by sanigo** [comment]
> `istio_request_duration_milliseconds` is captured at both client side and server side. See the `Reporter` label which tells you whether this time series is from source or destination.
> 
> Which istio version are you using? The metric used to be `istio_request_duration_seconds` but the name and unit has been updated to `istio_request_duration_milliseconds` for quite a while (maybe two or three releases ago) after we migrated to telemetry v2.

I don't think the istio_request_duration_milliseconds reported by destination is the same as X-ENVOY-UPSTREAM-SERVICE-TIME. The metric could be much higher than upsteam service time in access log.
We actually need to send a alert when X-ENVOY-UPSTREAM-SERVICE-TIME is high.

**Comment by bianpengyuan** [comment]
> The metric could be much higher than upsteam service time in access log.

Can you share more about your observation? How much difference did you see? request_duration metric tracks the duration between downstream request stream establishment and completion, which should be really close to the upstream request stream duration, since we'd expect that sidecar adds very little latency (1 to 2 milliseconds at tail).

**Comment by sanigo** [comment]
> > The metric could be much higher than upsteam service time in access log.
> 
> Can you share more about your observation? How much difference did you see? request_duration metric tracks the duration between downstream request stream establishment and completion, which should be really close to the upstream request stream duration, since we'd expect that sidecar adds very little latency (1 to 2 milliseconds at tail).


when the upstream service time is 2ms, the istio_request_duration_milliseconds reported by destination could be 1023ms.

**Comment by bianpengyuan** [comment]
It surprises me that upstream service time and duration would have such a big difference. upstream service time tracks the time between downstream request finishes and upstream response received. the duration metric tracks duration of the whole downstream request (from stream established to stream destroyed). The network has to be really slow to introduce such a big difference (1ms vs 1000ms). Does it always happen on every access log entry that you captured?

Alternative is that envoy generates an `upstream_rq_time` metrics, which should be close to `upstream_service_time`. You could probably consider make envoy expose that (https://istio.io/latest/docs/ops/configuration/telemetry/envoy-stats/) and build alerts based on that.

**Comment by akashjain971** [comment]
How can add custom tags to envoy metrics? I could not achieve that using the customMetric in Telemetry API.
