### ISSUE TITLE
503s caused by TLS secret not supplied by sds during 1.6.8 -> 1.7.0 upgrade

### ISSUE THREAD

**Issue by harpratap** [istio/istio#26844]
**Bug description**
We see a small blip of traffic disruption when upgrading istio control plane from 1.6.8 to 1.7.0 `"GET / HTTP/1.1" 503 UF,URX "-" "TLS error: Secret is not supplied by SDS"`

[ ] Docs
[x] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
To see no non-200 responses when upgrading

**Steps to reproduce the bug**
We have a step-by-step upgrade process, the controlplane + addons are installed in one step and the ingress gateway & sidecars have their own mechanism. 
Install 1.6.8 -
`istioctl-1.6.8 manifest apply -f `[controlplane_1.6.8.yaml](https://gist.github.com/harpratap/2fde477a388600269c545ed8419f63a6)
`istioctl-1.6.8 manifest generate -f `[gateway_1.6.8.yaml](https://gist.github.com/harpratap/9d42ee75f4537e92e24ea7e181f3f6b5) `| kubectl apply -f -`

Generate some load and check for network drops
upgrade controlplane to 1.7.0
`istioctl-1.7.0 install -f `[controlplane_1.7.0.yaml](https://gist.github.com/harpratap/36ae61b5d7747d2cad28c4790b6e6427)

![istio_503_shibuya](https://user-images.githubusercontent.com/5058823/91395954-066fda00-e876-11ea-964e-1f64f2cf733f.png)
client version: 1.6.8 & 1.7.0
control plane version: 1.6.8 & 1.7.0
data plane version: 1.6.8 (2 proxies)

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-27T00:38:11Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-30T20:19:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
Using istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**
Reproducible locally in Kind v0.8.1

**Comment by harpratap** [comment]
I think I have narrowed down this issue to `meshConfig.enableAutoMtls` 
1.6.8 autoMtls=false -> 1.7.0 autoMtls=true Traffic disruption
1.6.8 autoMtls=true -> 1.7.0 autoMtls=true Traffic disruption
1.6.8 autoMtls=false -> 1.7.0 autoMtls=false No traffic disruption

**Comment by harpratap** [comment]
Same issue with 1.6.8 autoMtls=true -> 1.7.1 autoMtls=true

**Comment by iandyh** [comment]
Looks like the real issue is when the cluster is turn on with `autoMTLS`.

**Comment by incfly** [comment]
@JimmyCYJ could you take a look? Even if the issue is demontrated when upgrade & enable auto mTLS, but from the error message, I think it's more of a SDS interaction timing issue.

**Comment by howardjohn** [comment]
Fixed by https://github.com/istio/istio/pull/28498
