### ISSUE TITLE
Add listener level access logs

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#26851]
We should add an access log filter on listeners. This allows us to capture things like:
* no filter chains matched
* Listener filter failure (ie protocol sniffing) (blocked by https://github.com/envoyproxy/envoy/issues/12809)

Consensus in WG: add the access log, with the same format as current. In parallel, we will work on getting listener filter failures. Requirement: must have no duplicate access logs.

Prototype: https://github.com/howardjohn/istio/pull/new/logs/listener-level-access-logs

**Comment by kyessenov** [comment]
Listener filter error capture should be fixed with https://github.com/envoyproxy/envoy/pull/12935.
We should validate that Wasm supports listener-level access logging  (@jplevyak).

**Comment by bianpengyuan** [comment]
I think this is fiexed.
