### ISSUE TITLE
Istio ingress gateways overflows under load when one worker node reboot

### ISSUE THREAD

**Issue by Asisranjan** [istio/istio#26868]
I am naive to ISTIO service mesh.

**Bug description**
when k8s worker node reboots during load to ingress gateway, ingress gateway overflows and return the response as below
upstream connect error or disconnect/reset before headers. reset reason: overflow

Can anyone please guide how to debug this issue.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by morvencao** [comment]
You can enable [PodDisruptionBudget](https://kubernetes.io/docs/tasks/run-application/configure-pdb/) to make sure your application is available during work node reboot.

**Comment by howardjohn** [comment]
Which version are you on? I think in old versions we have default https://istio.io/latest/docs/tasks/traffic-management/circuit-breaking/ configured, or if you are on a newer one perhaps you are configuring it too low. Please try upgrading or tuning this.
