### ISSUE TITLE
istiod auto-scaled pod sends bad CDS information to istio-proxies during short lifespan: istio 1.6.8

### ISSUE THREAD

**Issue by terickson** [istio/istio#26886]
**Bug description**
I noticed that sometimes for a short period some of my istio-proxies will give back 503 NR's for routes they should know and then later they will respond correctly.  I've tracked it down to sometimes when istiod auto-scales that new istiod instance will start giving bad CDS information to the istio proxies.  The other Istiod's will be giving good CDS information during this time making the bug seem very random.  Later the bad istiod will be auto-terminated fixing the issue.  I have screenshots from logs attached to this. 
![bug_1](https://user-images.githubusercontent.com/82548/91586841-90be4980-e91b-11ea-92ce-8afabcca8128.png)
![bug_2](https://user-images.githubusercontent.com/82548/91586907-ac295480-e91b-11ea-925e-dab3c3cf0038.png)
![bug_3](https://user-images.githubusercontent.com/82548/91586918-b0557200-e91b-11ea-90c3-2eeca2a25473.png)
![bug_4](https://user-images.githubusercontent.com/82548/91586945-b6e3e980-e91b-11ea-8ec4-3753a1eaf693.png)

[ ] Docs
[ ] Installation
[ ] Networking
[x] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**
It seems to happen randomly during auto-scaling of istiod

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istioctl version --remote
client version: 1.6.8
control plane version: 1.6.8
data plane version: 1.6.8 (157 proxies)

kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**
It was installed by istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**
On premise Rancher deployed kubernetes using Ubuntu as the OS on VMware Vms

**Comment by howardjohn** [comment]
Might be fixed by https://github.com/istio/istio/pull/26142? @stevenctl what do you think?

> I've tracked it down to sometimes when istiod auto-scales that new istiod instance will start giving bad CDS information to the istio proxies

Is the bad Istiod incorrect forever, or only at the start of its life?

**Comment by stevenctl** [comment]
The ordering issues #26142 solved could make istiod miss endpoints without any retry. I think this is the same issue.

**Comment by terickson** [comment]
This sounds very much like my problem.  In my case the autoscaler spun it up and then 6 minutes later spun it back down so I never saw it get back to right but it might of gotten back to right, given enough time.  So is this going to get backported to 1.6 or do we need to go to 1.7 to get this fix?
