### ISSUE TITLE
Istio Failing to Trust Custom CA Authority

### ISSUE THREAD

**Issue by IgorBrehm** [istio/istio#26884]
Hi everyone, I'm facing difficulties for a few days now and can't seem to find a solution. Because of this, I decided to open this issue hoping that someone will be able to give me some assistance and ideas of things for me to try out.

**Bug description**

The solution I have for authentication consists of a remote Keycloak server that provides authentication via JWT tokens. The server uses a leaf certificate, that I generated from a root certificate (that I also generated), using Smallstep. So I have in this way my own CA authority server, that I deployed for generating these certificates.
I wanted for Istio to be able to communicate to the remote Keycloak server, via RequestAuthentication and AuthorizationPolicy, so that I can enforce service-to-service authentication to certain services I deployed inside the service mesh of Istio (requests get to Istio Ingress Gateway, that then, using Virtual Services, delivers the requests to the services I deployed, etc).
I followed the steps at https://istio.io/latest/docs/tasks/security/cert-management/plugin-ca-cert/ ,in the hopes of having my custom CA being accepted as trusted by Istio, using that same root certificate I mentioned before. But to no avail, when I create the RequestAuthentication resource and then the AuthorizationPolicy, inside istiod pod's logs I can see an error message saying that it failed to establish connection to the specified address (certificate of remote server signed by unknown authority).
I don't think it would be a good idea for me to leave the communication with Keycloak server as HTTP instead of HTTPS, since it is outside the cluster, so I really need to find a solution for this situation, so that my certificate being used by Keycloak server can be accepted by Istio and the communication start to happen via HTTPS.

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

The certificate should have been accepted as valid, and connection to remote Keycloak server established succesfully via HTTPS.

**Steps to reproduce the bug**

- Deploy Istio following the extra steps from https://istio.io/latest/docs/tasks/security/cert-management/plugin-ca-cert/
- Create a leaf certificate for a remote server using the same root certificate used in the previous step
- Deploy the remote server using the leaf certificate for all HTTPS connections
- Attempt to connect with istiod pod to the remote server

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

- istioctl version --remote:
   * client version: 1.6.8
   * control plane version: 1.6.5
   * data plane version: 1.6.5 (9 proxies)
- kubectl version:
   * ```
        Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.12", 
        GitCommit:"17c50ce2d686f4346924935063e3a431360e0db7", GitTreeState:"clean", BuildDate:"2020-06-26T03:41:29Z", 
        GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
        Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.12", 
        GitCommit:"17c50ce2d686f4346924935063e3a431360e0db7", GitTreeState:"clean", BuildDate:"2020-06-26T03:33:27Z", 
        GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"} 
      ```

**How was Istio installed?**

Istio was installed by generating a yaml file using istioctl manifest generate --profile=demo, and applying it manually using kubectl.

**Environment where bug was observed (cloud vendor, OS, etc)**

- OS = Ubuntu Linux 18
- Network = Private network of the company I work for

**Comment by IgorBrehm** [comment]
If this is indeed a bug with Istio, I can try to help out and implement a fix for it myself, then opening a Pull Request later so that it can be merged. However I'm going to need some information and help first, anything you can give me is much appreciated!

**Comment by IgorBrehm** [comment]
Here is an example of what happens when, say, I try to connect to the remote server by executing curl inside the istiod pod:
```
kubectl exec -it istiod-694bc4cbd7-fszzd -n istio-system -- curl -v https://keycloak.mycorp.net:8443/auth/realms/myrealm/protocol/openid-connect/certs
*   Trying 15.8.142.135...
* TCP_NODELAY set
* Connected to keycloak.mycorp.net (15.8.142.135) port 8443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, Server hello (2):
* SSL certificate problem: self signed certificate in certificate chain
* stopped the pause stream!
* Closing connection 0
curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
command terminated with exit code 60
```

**Comment by IgorBrehm** [comment]
However, if I specify to curl the correct path where Istio mounted the certificate files from cacerts secret, the connection works as expected:
```
kubectl exec -it istiod-694bc4cbd7-fszzd -n istio-system -- curl -v --cacert /etc/cacerts/root-cert.pem https://keycloak.mycorp.net:8443/auth/realms/myrealm/protocol/openid-connect/certs                                                                             
*   Trying 15.8.142.135...
* TCP_NODELAY set
* Connected to keycloak.mycorp.net (15.8.142.135) port 8443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/cacerts/root-cert.pem
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=US; ST=Texas; L=Houston; O=My Corp; OU=PSSW; CN=keycloak.mycorp.net
*  start date: Aug 26 16:41:33 2020 GMT
*  expire date: Aug 25 16:41:33 2025 GMT
*  subjectAltName: host "keycloak.mycorp.net" matched cert's "keycloak.mycorp.net"
*  issuer: CN=mycorp.net
*  SSL certificate verify ok.
> GET /auth/realms/myrealm/protocol/openid-connect/certs HTTP/1.1
> Host: keycloak.mycorp.net:8443
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Cache-Control: no-cache
< X-XSS-Protection: 1; mode=block
< X-Frame-Options: SAMEORIGIN
< Date: Tue, 01 Sep 2020 18:26:29 GMT
< Connection: keep-alive
< Strict-Transport-Security: max-age=31536000; includeSubDomains
< X-Content-Type-Options: nosniff
< Content-Type: application/json
< Content-Length: 2914
<* Connection #0 to host keycloak.mycorp.net left intact
```

**Comment by yangminzhu** [comment]
istiod uses a different root CA when talking to your jwks server and has nothing to do with the https://istio.io/latest/docs/tasks/security/cert-management/plugin-ca-cert/. The plugin CA controls the root certificate used for the workload communications.

You could mount your extra root CA in `"/cacerts/extra.pem"` in istiod:
https://github.com/istio/istio/blob/bacafff4a18577b358b6514e97ea5f5a43e2f35c/pilot/pkg/model/jwks_resolver.go#L78-L79

**Comment by IgorBrehm** [comment]
Hi yangminzhu, thank you for your answer! By mounting my extra root CA you mean for me to edit the yaml file of istio deployment and manually insert an additional volume mount and so on?

**Comment by yangminzhu** [comment]
@IgorBrehm yes, that's correct.

**Comment by IgorBrehm** [comment]
I just tested your suggestion and it worked. Thank you for the help!
