### ISSUE TITLE
Configure Ingress pathType ImplementationSpecific behavior

### ISSUE THREAD

**Issue by Exagone313** [istio/istio#26883]
**Describe the feature request**

Kubernetes 1.18 added a `pathType` attribute for Ingress path definitions, which is set to `ImplementationSpecific` value by default. This means that Ingress that targets (or are kept compatible to) older Kubernetes versions will have this value.

[istio behavior](https://preliminary.istio.io/latest/docs/tasks/traffic-management/ingress/kubernetes-ingress/#specifying-path-type) is to *treat paths as exact matches, unless they end in `/*` or `.*`, in which case they will become prefix matches*, which differs from other Ingress that usually treat the default value as like `Prefix`.

My suggestion is to add a configuration setting  to choose `ImplementationSpecific` behavior (actual default vs Prefix by default).

**Describe alternatives you've considered**

I'm deploying GitLab using [their Helm charts](https://docs.gitlab.com/charts/) which is compatible with Kubernetes >= v1.13. Their Ingress definitions do not include `pathType` as this would break compatibility.

* Contributing to their charts to add a setting would add [unnecessary complexity](https://gitlab.com/gitlab-org/charts/gitlab/-/merge_requests/1502#note_402744604) as istio is not a supported Ingress.
* The result of `helm template` doesn't seem to produce a working yaml, thus patching the result is not a solution.
* Forking is too complex to maintain.
* Editing Ingress objects manually after each upgrades needs manual intervention (actual "solution").

[x] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[x] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

I looked at an IstioOperator definition but it seems complex to add a setting though...

**Comment by howardjohn** [comment]
> My suggestion is to add a configuration setting to choose ImplementationSpecific behavior (actual default vs Prefix by default).

The entire point of the new pathType field is you should explicitly declare the pathType you want. Configuring the default behavior, in my opinion, does not make sense and is not in the spirit of the Ingress v1 spec in my opinion. I would be against adding this.

**Comment by Exagone313** [comment]
I wasn't unable to find the response of a question by reading previous documentation versions: did Istio have Ingress support before Kubernetes 1.18 and if it did, how did it work without having the `pathType` property?

**Comment by howardjohn** [comment]
It did, and the default path type described above is what was used

**Comment by howardjohn** [comment]
btw, in Ingress v1 path type is a required field so it makes even less to do this.

**Comment by Exagone313** [comment]
Closing since it makes sense not to have this feature in istio.

**Comment by naphta** [comment]
Not to wake up an old issue, but @howardjohn, I have a scenario right now (in 1.8) where the default pathType (which is `ImplementationSpecific`) does not act as the default of prefix. I'm working with a 3rd party chart so putting `pathType` into the ingress resource is less straightforward. I've manually updated the ingress from `ImplementationSpecific` to `Prefix` and everything does begin to work as I'd expect.

**Comment by howardjohn** [comment]
@naphta I understand the behavior isn't great but:
* Its the behavior we have had ~forever, so we cannot change it.
* It is `ImplementationSpecific`, so we are free to have whatever bad behavior we want
Its not ideal, but not much we can do

The ingress API is fundamentally flawed. I would recommend using Istio Gateway or keeping an eye on the future https://github.com/kubernetes-sigs/gateway-api if you don't like the state of Ingress
