### ISSUE TITLE
large wasm memory consumption with a single worker

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#26894]
Using istio 1.7 and pre-compiled wasm file, we see the following memory scaling characteristics:

| concurrency |  total physical bytes  |   
| -- | -- |
| 1 | 64M |
| 2 | 64M |
| 4 | 61M |
| 8 | 61M |
| 16 | 61M |
| 32 | 71M |
| 1 (no wasm) |  12M |
| 32 (no wasm) | 13M |

The memory consumption does not seem to scale with the number of workers. It is not clear whether the shared memory is contended by multiple workers.

Envoy configuration: https://gist.github.com/kyessenov/16a09bf62ff679b98223e2322fef4982

/cc @mandarjog @jplevyak @PiotrSikora

**Comment by kyessenov** [comment]
As of today, this is worse. At startup, envoy + pre-compiled metadata exchange consumes 120MB total physical bytes with 1 or 32 workers.

**Comment by mandarjog** [comment]
Kuat can you update the previous description? I think this is the main branch, but would be good to clarify.

**Comment by marcusschiesser** [comment]
Is there a status update of this issue? I got similar values with Istio 1.8.1
