### ISSUE TITLE
TLSv1.2 protocol could not identify while sniffing using wireshark

### ISSUE THREAD

**Issue by JibinNajeeb** [istio/istio#26903]
Tested in mtls enabled cluster 

Steps taken:
```
$ kubectl apply -f <(istioctl kube-inject -f samples/sleep/sleep.yaml)
$ kubectl apply -f <(istioctl kube-inject -f samples/httpbin/httpbin.yaml)
$ kubectl get pods  -o wide
httpbin-6547d9b48d-64mdc   2/2     Running   0          113m   10.244.48.251   ip-172-31-10-100.us-west-2.compute.internal   
sleep-7ff6f95948-g5vgf     2/2     Running   0          114m   10.244.74.100   ip-172-31-0-93.us-west-2.compute.internal  
$ kubectl sniff httpbin-6547d9b48d-64mdc -o dump-mtls4.txt
$ kubectl exec -it $(kubectl get pod -l app=sleep -o jsonpath='{.items[0].metadata.name}') -c sleep -- curl -v httpbin:8000/status/418
```

Copied dump-mtls4.txt to wireshark. There is  no info regarding TLS between pod 10.244.48.251 and
 10.244.74.100

At line 33 we can see the message IM A TEAPOT. but there is no detail about TLSv1.2. How can I sniff TLS report?

[dump-mtls6.txt](https://github.com/istio/istio/files/5144875/dump-mtls6.txt)

**Comment by howardjohn** [comment]
It depends on the implementation of `kubectl sniff` and how its running. it may be intercepting the traffic between app and sidecar, before its encyrpted

**Comment by howardjohn** [comment]
Closing as working as intended. if you want to sniff the tls traffic you will need to sniff after the traffic has hit the sidecar. Thanks

**Comment by jitapichab** [comment]
Hello @howardjohn can you give me an example of that please :)
