### ISSUE TITLE
Accessing Kubernetes API server from Istio enabled application

### ISSUE THREAD

**Issue by blublinsky** [istio/istio#26907]
**Bug description**
When accessing Kubernetes API server from Istio enabled applications, the requests fail due to MTS. An approach to resolve this issue, described at https://istio.io/latest/faq/security/#accessing-non-istio-services does not work.

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[x] Test and Release
[ ] User Experience
[x] Developer Infrastructure

**Expected behavior**
As described https://istio.io/latest/faq/security/#accessing-non-istio-services, usage of the destination rule (https://github.com/blublinsky/akka-sample-cluster-kubernetes-scala/blob/master/kubernetes/destinationrule.yaml) should of resolve the issue, but it does not. THere are 2 ways to resolve the problem, each with its own drawback:
1. Include port 443 into excudedOutbound ports - see https://github.com/blublinsky/akka-sample-cluster-kubernetes-scala/blob/master/kubernetes/akka-cluster-443.yaml#L16
2 Excluding outbound IP ranges https://github.com/blublinsky/akka-sample-cluster-kubernetes-scala/blob/master/kubernetes/akka-cluster.yaml#L18
**Steps to reproduce the bug**
Deploying the project https://github.com/blublinsky/akka-sample-cluster-kubernetes-scala

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
bin/istioctl version --remote
client version: 1.6.6
control plane version: 1.6.6
data plane version: 1.6.6 (6 proxies)

kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.42", GitCommit:"42bef28c2031a74fc68840fce56834ff7ea08518", GitTreeState:"clean", BuildDate:"2020-06-02T16:07:00Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**

istioctl install --set profile=demo

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE:
kubectl get nodes
NAME                                        STATUS   ROLES    AGE   VERSION
gke-cloudstate-default-pool-442f7de2-0ljk   Ready    <none>   87d   v1.14.10-gke.36
gke-cloudstate-default-pool-442f7de2-7nx0   Ready    <none>   87d   v1.14.10-gke.36
gke-cloudstate-default-pool-442f7de2-c4zp   Ready    <none>   87d   v1.14.10-gke.36

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive
[istio-dump.tar.gz](https://github.com/istio/istio/files/5146199/istio-dump.tar.gz)
) by attaching
the dump file to this issue.

**Comment by blublinsky** [comment]
@sdake, please advice

**Comment by howardjohn** [comment]
This release has a bug as indicated in the notes: https://istio.io/latest/news/releases/1.6.x/announcing-1.6.6/./ please upgrade to 1.6.7+. Thanks!

**Comment by blublinsky** [comment]
Thanks @howardjohn for your fast reply, so it is supported in 1.6.7+, 1.7.x, what about 1.5.10, that was just released? Was it back ported there?

**Comment by howardjohn** [comment]
There was a single version - 1.6.6 - that had this bug. it was a regression
