### ISSUE TITLE
[1.5.4] External Redis instance giving "Connection Reset by Peer" on Sidecar Enabled pod

### ISSUE THREAD

**Issue by DandyDeveloper** [istio/istio#26914]
**Bug description**
My issue is similar to https://github.com/istio/istio/issues/21964 and may be considered a duplicate, but the scenario is different. 

I have an external Redis instance available over TCP 6379 in another k8s cluster. This is using standard non-TLS to connect. 

After enabling a sidecar on a service that points at the Redis instance, it errors out with the a "Connection reset by peer" error. 

If I disable `mtls.auto` by setting `False` that fixes things, but the issue is, that would disable mTLS for everything, which is not ideal. 

It may be that the logic in Istio is seeing an external service as though it's a headless service, and so the treatment suggested in #21964 is likely the same. However, I'd like to get some confirmation that this is the case. 

**Affected product area (please put an X in all that apply)**

[x] Networking

**Affected features (please put an X in all that apply)**

[x] Virtual Machine

**Expected behavior**

I'd expect Istio to treat external services like this as mTLS not needed unless explicitly set elsewhere in a CRD. 

**Steps to reproduce the bug**
On Istio 1.5.4 you can run Redis externally, with a standard Istio profile (mTLS.auto = enabled) and simply run sidecar injection in one namespace and disabled in another. Add a pod like so and you should be able to reproduce the issue: 

```
#### With mTLS Disabled
root@redis-ctl:/data# redis-cli -h XXX.XXX.XXX.XXX
XXX.XXX.XXX.XXX:6379> PING
PONG
XXX.XXX.XXX.XXX:6379> 
root@redis-ctl:/data# exit

## With mTLS auto enabled
dandy@DESKTOP-2GSHJ08:/istio-test/$ kubectl run redis-ctl --image=redis --restart=Never
pod/redis-ctl created
dandy@DESKTOP-2GSHJ08:/istio-test/$ kubectl exec -it redis-ctl bash
root@redis-ctl:/data# redis-cli 0h XXX.XXX.XXX.XXX
XXX.XXX.XXX.XXX:6379> PING
Error: Connection reset by peer
```

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
client version: 1.5.4
control plane version: 1.5.4
data plane version: 1.5.4 (44 proxies), 1.4.3 (4 proxies)
```
kubectl is version 1.14

**How was Istio installed?**
Istio Operator using a standard profile. 

**Environment where bug was observed (cloud vendor, OS, etc)**
Baremetal K8s

**Comment by esnible** [comment]
Check https://github.com/istio/istio/issues/14743 for suggestions?

**Comment by howardjohn** [comment]
Closing as no response for ^ and 1.5 is EOl and there have been changes in this area recently
