### ISSUE TITLE
Istio upgrade mess

### ISSUE THREAD

**Issue by Stono** [istio/istio#26924]
**Bug description**
Hi, 
We're currently on 1.5, using the microservice model - using templates generated by `helm template` as we have done since the start of istio which we post process into our own charts + ci process.

As part of our move to 1.6, we're naturally going to the `istiod` model, and we're having to move our templating over to `istioctl generate manifest` due to the deprecation of `helm` support.  We used `manifest migrate` on our old values, and after a chunk of time managed to get 1.6 templating, however:

**Problem 1**:
On 1.6, there's no `istio-pilot` service, so all of our existing `istio-proxies` will break if we deploy this in its current state.

Therefore after chatting with @howardjohn we decided to try and break down our upgrade into two steps:

1.  First change 1.5 to be the `istiod` model which apparently accounted for this
2.  Then upgrade to 1.6

**Problem 2**
`istioctl manifest generate` does not work on 1.5 with our values.yaml, errors like:

```
Error: error unmarshaling JSON: unknown value "OFF" for enum istio.mesh.v1alpha1.MeshConfig_IngressControllerMode:
Error: error unmarshaling JSON: unknown value "REGISTRY_ONLY" for enum istio.mesh.v1alpha1.MeshConfig_OutboundTrafficPolicy_Mode:
```

Therefore we're stuck between a rock and a hard place, once again the istio upgrade process is agonising.  The only path I see for us here is to deploy 1.6, but manually create the `istio-pilot` service to ensure backwards compatibility.

Is there anything else that way need to do in order to go from 1.5 -> 1.6, microservice -> monolith?

We _could_ run multiple control planes and migrate over 500+ services that way, but that's a significant change to how we deploy istio and will probably cause other issues - and we've done rolling updates of our control plane with helm since forever.

[x] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[x] Developer Infrastructure

**Expected behavior**
To be able to upgrade 

**Steps to reproduce the bug**
Attempt to go from 1.5 microservice, to 1.6 monolith

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**
1.5 = helm template
1.6 = istioctl generate manifest 

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE.

**Comment by howardjohn** [comment]
```
$ ~/istio/istio-1.5.10/bin/istioctl manifest generate -f /tmp/iop.yaml
Error: error unmarshaling JSON: unknown value "OFF" for enum istio.mesh.v1alpha1.MeshConfig_IngressControllerMode:

YAML:
apiVersion: operator.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio
  namespace: istio-operator
spec:
  meshConfig:
    ingressControllerMode: "OFF"
$ ~/istio/istio-1.6.8/bin/istioctl manifest generate -f /tmp/iop.yaml 
...
```

I think its a bug in the marshaling with istioctl 1.5

**Comment by Stono** [comment]
I'm closing this in favour of the other issues which more accurately reflect the issues we've faced during the upgrade process.    There's a specific bug in here with the 1.5 marshalling in the cli, which won't be fixed.
