### ISSUE TITLE
Enable holdApplicationUntilProxyStarts at pod level

### ISSUE THREAD

**Issue by linsun** [istio/istio#26923]
**Describe the feature request**

This is a dark launched feature in 1.7 (https://medium.com/@marko.luksa/delaying-application-start-until-sidecar-is-ready-2ec2d21a7b74), many of users indicate that they want this feature as they have been work around the startup prob themselves.  We need to evaluate what it takes to enable this by default in 1.8.

@GregHanson could you look into what it takes?  @luksa thoughts?

cc @rvennam @kramvan1 

[ ] Docs
[ ] Installation
[ x ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
I have concerns about making this default. We should be pushing for Sidecar KEP and get first class support. This solution, while great, is what I would consider likely permanent experimental due to relying on k8s implementation details.

**Comment by linsun** [comment]
I agree sidecar KEP is the strategic direction but it is not ready in 1.9 (https://github.com/kubernetes/enhancements/issues/753).  Not sure when it would be ready and then it will go through experimental, alpha beta phase so it is likely at least 6 months before Istio could use it.

We are not changing user's experience on how their services work with Istio regardless of we are using sidecar KEP or our own holdApplicationUntilProxyStarts so when we switch to sidecar KEP the change is transparent to users.

At the minimum, I would like to have a per service based config for this if there are strong objections to not enable this by default.

**Comment by howardjohn** [comment]
`holdApplicationUntilProxyStarts` has significant downsides and it is *not* transparent. It impacts any users using `kubectl log` or `kubectl exec`, including scripts, applications, and CI tools, by re-ordering the containers. It also relies on Kubernetes implementation details that may change at any time.

I also don't see how per-service config is related to default?

**Comment by howardjohn** [comment]
Not to mention, when the pod will not start it just sits there, in `PodInitializing`, with 0 logs exposed - its a horrible debugging experience. We have spent a lot of time on defining what it means to be "beta", including "supportability", and to me this clear does not meet the bar. I love the feature, I think its a great hack, but ultimately users do not expect hacks in stable Istio code - it must be opt in

**Comment by linsun** [comment]
per-service config is not related default, I was mentioning it as a fall back plan.

I think you are focusing on the perspective of debugging when sidecar is not starting up properly and its impact to `kubectl log` or `kubectl exec` etc commands?  The other perspective is users today spends a lot of time to trouble why their service stops working when sidecar is injected, which is also hard to troubleshooting.

**Comment by AlexGS74** [comment]
In addition to all said above, It seems that `holdApplicationUntilProxyStarts: true` makes all health checks to stop working if you use `rewriteAppHTTPProbe: true`. It seems no matter what initial delay for the checks is set on the main container, k8s hits the proxy with livenes check 2 times, gets errors and never attempts health checks again (or I see no more log entries in the istio-proxy log or the main app). After the fail threshold, k8s recycles the whole pod. With `holdApplicationUntilProxyStarts: false` I see no more issues with the healthchecks, but we have to 'delay' the main container start up on our own.

**Comment by howardjohn** [comment]
@AlexGS74 this is just a bug which has been fixed since https://github.com/istio/istio/issues/26873 so it likely will not impact our long term plans. Thanks!

**Comment by linsun** [comment]
Decision from networking WG mtg today: let's move to pod annotation first to allow users to easily configure it at pod level.

There is some brief discussion on mesh config and proxy config - https://github.com/istio/istio/pull/24737#issuecomment-645459510.   only proxy config supports pod level annotation today.

**Comment by linsun** [comment]
related PRs:  https://github.com/istio/istio/pull/27696
https://github.com/istio/api/pull/1670

**Comment by bianpengyuan** [comment]
This is done.
