### ISSUE TITLE
remove-from-mesh does not remove the init container when using IstioCNI

### ISSUE THREAD

**Issue by tariq1890** [istio/istio#26938]
**Bug description**

remove-from-mesh causes a failure state as it does not remove the injected init container when using Istio CNI.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

Enable Istio CNI 

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by esnible** [comment]
Closed by PR https://github.com/istio/istio/pull/26812
