### ISSUE TITLE
Fail istioctl install on explicitly empty revision

### ISSUE THREAD

**Issue by therealmitchconnors** [istio/istio#26940]
**Bug description**
istioctl install fails to distinguish between unset revision and empty string revision.  In both cases, an in-place upgrade is applied.  This can cause problems when the user has a typo in their bash session such as: 

```
export REVISION=1.6.4
istioctl install --revision $REVISION_NAME
```

In this case, the user expects a revision-based upgrade which poses no risk to the existing mesh, but because of their typo they get a destructive in-place upgrade.  When the revision flag is supplied, but an invalid value is associated with it (such as empty string, not sure if other scenarios exist), the command should fail, not fall back to in-place upgrade.  Users should have 100% certainty which sort of upgrade they are performing.

[ ] Docs
[ x ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ x ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Multi Control Plane upgrade fails.

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istio 1.6+

**Comment by esnible** [comment]
According to Kubernetes, "Valid label values must be 63 characters or less and must be empty or begin and end with an alphanumeric character ([a-z0-9A-Z]) with dashes (-), underscores (_), dots (.), and alphanumerics between."

As Istio stores the revision in a label value, there should not be a problem validating that the user's supplied value has those characteristics.

**Comment by howardjohn** [comment]
Does cobra distinguish unset vs empty flags if the default is `""`?

**Comment by therealmitchconnors** [comment]
Yes https://godoc.org/github.com/spf13/pflag#FlagSet.Changed
