### ISSUE TITLE
External Istiod: no need to restart istiod to pick up new k8s config

### ISSUE THREAD

**Issue by linsun** [istio/istio#26949]
**Describe the feature request**

The kubeconfig normally expired 2-3 weeks and requires a new config file using refresh token.  When this is about to expire, mesh operator can load up the new kubeconfig via the `istio-kubeconfig` secre. It is desired that mesh operator doesn't need to restart of Istiod to pick up the new kubeconfig via secret.  

@irisdingbj let me know if this already works.  Looking at the code, seems we only load up the kubeconfig at boot time of pilot.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[x ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by irisdingbj** [comment]
@linsun yep, I am worried it does not work because we only initialize the client when we bootstrapping. investigating..
