### ISSUE TITLE
klog shim broken by client-go 1.19

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#26953]
Now we get logs like 

```
I0831 21:47:38.033381       1 leaderelection.go:253] successfully acquired lease istio-system/istio-namespace-controller-election
2020-08-31T21:47:38.033514Z     info    Namespace controller started
I0831 21:47:42.260659       1 leaderelection.go:253] successfully acquired lease istio-system/istio-leader
2020-08-31T21:47:42.260784Z     info    Starting ingress controller

```

That do not use our standard logging libraries. We may need to update http://github.com/istio/klog or something.

**Comment by hacktron95** [comment]
hello @howardjohn , I can take this if no one is currently working on it,
please let me know if you have a suggested approach for how to solve this?

**Comment by howardjohn** [comment]
That would be great. I don't know what caused the issue so I'm not sure. I do know we have a fork of klog  and/or golog that pushes it through our own logging system so that seems like the best place to get started. See the go.mod for the replace

**Comment by hacktron95** [comment]
@howardjohn please assign me, I'll give it a try in a time box of 1 week.

**Comment by hacktron95** [comment]
hey @howardjohn I see this as a release blocker now, and I believe this will take me a lot of time to understand and try to replicate it and solve it. so I'll un-assign myself this time, sorry for that.

**Comment by howardjohn** [comment]
The release is not until like November so it's a very high priority but not
urgent really. If you are still interested it would be great - let us know

**Comment by hacktron95** [comment]
/assign
thanks for letting me know about that.

**Comment by howardjohn** [comment]
@hacktron95 are you still working on this? I think I remember you saying you were but maybe I made that up

**Comment by hacktron95** [comment]
hello @howardjohn, sorry I got busy and couldn't continue working on it.
I should've mentioned that earlier, Sorry for that.
