### ISSUE TITLE
Matching header with URI doesnt work with separate match config across virtualservices

### ISSUE THREAD

**Issue by pc-rshetty** [istio/istio#26965]
**Bug description**
Some context of the issue i had created a while ago https://github.com/istio/istio/issues/16959

Here is the scenario, i have 2 applications lets say admin and adam, they both use same ingress gateway. I would like both to use header based routing with a header called "test-user" which means 
1> header with "test-user" with URI match of /admin should go to the admin service container
2> header with "test-user" with URI match of /adam should go to the adam service container

Here is the virtualservice config for admin 

```spec:
  gateways:
  - mygateway.default.svc.cluster.local
  hosts:
  - '*'
  http:
  - match:
    - headers:
        test-user:
          exact: "true"
      uri:
        prefix: /admin
    route:
    - destination:
        host: admin-canary-service
        port:
          number: 8080
    timeout: 120s```


Here is the vitualservice config for adam 

```spec:
  gateways:
  - mygateway.default.svc.cluster.local
  hosts:
  - '*'
  http:
  - match:
    - headers:
        test-user:
          exact: "true"
      uri:
        prefix: /adam
    route:
    - destination:
        host: adam-canary-service
        port:
          number: 8080
    timeout: 120s```


While admin routing works the adam routing doesnt work since all requests are going to the admin canary


**Affected product area (please put an X in all that apply)**

[ X] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
The AND condition should work even if the match is distributed across virtualservices 
**Steps to reproduce the bug**
Config above should help reproduce
**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
1.4.7
**How was Istio installed?**
helm
**Environment where bug was observed (cloud vendor, OS, etc)**
EKS
Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by pc-rshetty** [comment]
This worked when i declared them in same file . I think this needs to be fixed to add all the rules comming from different virtualservice config file and append(AND) it to the rule

**Comment by pc-rshetty** [comment]
This is how it worked

gateways:
  - mygateway.default.svc.cluster.local
  hosts:
  - '*'
  http:
  - match:
    - headers:
        test-user:
          exact: "true"
      uri:
        prefix: /admin
    route:
    - destination:
        host: admin-canary-service
        port:
          number: 8080
    timeout: 120s
  - match:
    - headers:
        test-user:
          exact: "true"
      uri:
        prefix: /adam
    route:
    - destination:
        host: adam-canary-service
        port:
          number: 8080
    timeout: 120s

**Comment by pc-rshetty** [comment]
This works perfectly fine in one environment but doesnt work in another environment i check all configurations are same in both.

Env 1:
calling /adam routes traffic to adam-canary-service

Env 2:
calling /adam routes traffic to **admin-canary-service**

I need some guidance here @howardjohn !

How do i check whats wrong in the layer 7 routing in Env2 , any help appreciated

**Comment by howardjohn** [comment]
you should look at config dump: https://github.com/istio/istio/wiki/Troubleshooting-Istio and post here

**Comment by pc-rshetty** [comment]
there was a additional route for prefix "/" which was causing all traffic to go to adam canary service . closing this ticket
