### ISSUE TITLE
Summary of frictions encountered when upgrading to Istio 1.6

### ISSUE THREAD

**Issue by brianwolfe** [istio/istio#26975]
This is not really a feature request or a bug request. This is more a summary of frictions I had when upgrading a moderate-sized deployment to Istio 1.6.8. In particular, @howardjohn @smawson @rshriram asked for this summary.

## Setup

We run a a set of multicluster Istio setups in central Istiod mode, as described here https://github.com/istio/istio.io/pull/7978 and https://deploy-preview-7978--preliminary-istio.netlify.app/latest/blog/2020/new-deployment-model/

This is the first Istio upgrade we have done since onboarding any production services. We went from Istio 1.5.2 to Istio 1.6.8 using a [canary rollout](https://istio.io/latest/blog/2017/0.1-canary/), with the rev 1-6-8 (so the label `istio.io/rev: 1-6-8`).

The 1.5.2 deployment was a custom build https://github.com/airbnb/istio/tree/1.5.2-airbnb.v1alpha based on some early PRs for central Istiod that landed in 1.6. 1.6.8 is a standard build with all customizations accomplished through operator API specs.

## Issue summaries

The upgrade is going successfully without any production issues, but I ran into some friction along the way.

Please feel free to ask for more clarification or I can break anything that's actually of interest out into a separate issue. This is just a catalogue of issues I wrote that could be addressed in Istio itself.

- Istio Operator.
  - Not comfortable granting Istio Operator cluster admin privileges. The multitenancy effort is working to reduce the necessary RBAC, but it seemed like we wouldn't benefit much from using the operator for this upgrade.
  - It also has some sharp edges in lifecycle, I got it stuck creating an istiod deployment once and it took a bit of manual intervention to get it working.
- Proxy component usage in 1.6 was not obvious. Looks like it was removed in 1.7 anyway.
  - I spent some time looking for the right way to set default resource requests/limits for the proxy. I thought it would be in the proxy component, but I was wrong.
- Central Istiod setup was not very clear. This makes sense since it is still experimental in 1.6, but I ran into several difficulties around:
  - Migrating to the new injection webhook PATH, figuring out how to correctly specify the URL of the central deployment.
  - Our workload cluster validating webhook configuration failurePolicy was getting patched by central Istiod. Central Istiod and istiod 1.5 disagreed on whether to mark it up or down and they end up flapping the resource up and down very rapidly, enough that it is noticeable in the CPU utilization in both.
- CustomResourceDefinitions set preserveUnknownFields: false in 1.6. We have some resources in our cluster that were using JSON/snake_case formatting due to a serialization issue when pulling in the Istio API libraries (if you accidentally serialize using the default JSON serializer in Go instead of the protobuf json serializer, you can end up with the wrong field names). Deploying the updated CRDs broke most of our (test) mesh traffic since our trafficPolicy was rewritten as traffic_policy, which was no longer served. Definitely a bug on our side, but it was a bit unexpected.
- Rev for upgrading mostly works great aside aside from the singletons (validatingwebhook & crds).
  - We customized the injection selectors compared to production. Within Airbnb, we have a lot of tooling to do pod-level mutation for slow rollout of infrastructure components. To take advantage of this, we want to have a static label for namespaces (istio-injection: true) and a changing label for pods e.g.: istio.io/rev: 1-6-8. The existing options for object selector do not allow that. I haven't found an existing design doc for how all the selectors should ideally interact, so I'm not sure if it's incorrect or just a different use-case. I'm not sure if we just need to enumerate the injection models that people are likely to want and then pick selectors based on that instead of trying to infer it based on other options. Probably deserves a short design doc.
- CRDs are appearing out of order:
  - We use istioctl manifest generate to create & review the manifests for istio before applying them using spinnaker.
  - In 1.6.8, the CRDs in charts/base/crds were appearing in random order, so we would get diffs without configuration changes. The rest of the manifests are stable (which looks like the intent). I tracked down the issue to https://github.com/istio/istio/blob/master/operator/pkg/helm/helm.go#L146-L157 where the helm crdFiles are not getting sorted by name. I wasn't able to duplicate the error when building istioctl from source, but I didn't try too hard. We ended up not including the CRD updates in the initial rollout due to the above issue around preserveUnknownFields. We have to migrate all definitions to use the correct casing before updating the CRDs in production.
- Possible memory leak
  - There appears to be a very slow memory leak in our Istiod deployment. It appears to increase on order of 10MB increase per day when tracking the minimum memory usage that Go runtime reports. This increase is consistent over time (looks like a linear ramp up). With pprof, I see several MB of data corresponding to endpoint objects being stored even on a cluster, but it is not an operational risk. I have not investigated deeply. LMK if you want output from the heap profiles in our test cluster where I see this.

**Affected product area (please put an X in all that apply)**

[X] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[X] Multi Cluster

**Comment by howardjohn** [comment]
Thanks for posting this @brianwolfe !

> CustomResourceDefinitions set preserveUnknownFields: false in 1.6. We have some resources in our cluster that were using JSON/snake_case formatting due to a serialization issue when pulling in the Istio API libraries (if you accidentally serialize using the default JSON serializer in Go instead of the protobuf json serializer, you can end up with the wrong field names). Deploying the updated CRDs broke most of our (test) mesh traffic since our trafficPolicy was rewritten as traffic_policy, which was no longer served. Definitely a bug on our side, but it was a bit unexpected.

By broke, do you mean fields that were set were suddenly removed in etcd? So applying the new CRDs resulted in the existing DR trafficPolicy not taking effect? Or that you couldn't apply reapply the DR as it was rejected?



cc @therealmitchconnors @ostromart may find this interesting

**Comment by brianwolfe** [comment]
The values were still stored in etcd, but I believe the unknown fields are trimmed on retrieval when preserveUnknownFields goes to false, so our `traffic_policy` (sic) fields were all omitted in both 1.6.8 and 1.5.2, breaking a bunch of traffic across the cluster immediately. When we re-deployed the 1.5.2 CRDs, traffic was immediately restored.

**Comment by howardjohn** [comment]
@jasonwzm ^

**Comment by ramaraochavali** [comment]
Can you please share the heap profile for memory leak that you have observed?

**Comment by brianwolfe** [comment]
Inuse memory at the time is captured in the following graphs from pprof. LMK if there are details you particularly want.

![inuse_space](https://user-images.githubusercontent.com/1874252/92012672-98a63100-ed01-11ea-8e4b-2bf610cdb68e.png)

![inuse_objects](https://user-images.githubusercontent.com/1874252/92012658-947a1380-ed01-11ea-8a7f-8425606fe148.png)
