### ISSUE TITLE
Istiod RequestAuthentication failing while using internal jwksuri with internally signed certificate

### ISSUE THREAD

**Issue by rakeshbhatk** [istio/istio#26984]
I’ve been applying RequestAuthentication Policy to my service using JWT.
I have a internal OIDC  provider(CA7 gateway OTK) and the provider uses a internally signed CA. The RequestAuthentication is failing as istiod is not able to find the internal cert while communicating with jwksuri. 

How do I get istiod refer the internal certificate while connecting to internal jwksUri??

I followed the below guide in istio document : 
https://istio.io/v1.6/docs/tasks/security/authorization/authz-jwt/

######  My RequestAuthentication policy
    apiVersion: "security.istio.io/v1beta1"
    kind: "RequestAuthentication"
    metadata:
      name: "jwt-policy"
      namespace: myapp-ns
    spec:
      selector:
        matchLabels:
          app: my-app
      jwtRules:
      - issuer: "my-issuer"
        jwksUri: "https://my-oidc-provide/jwks.json"

I am applying the RequestAuthentication in same namespace where my service is running.

Tried all the options suggested in the below link.
https://discuss.istio.io/t/istio-jwt-verification-against-jwks-with-internally-signed-certificate/5408

###### Error in istiod logs : 
    failed to fetch public key from https://myapp/jwks.json context deadline exceeded (client.timeout excceded while awaiting headers) 
    proto constraint validation failed (JwtAuthenticationValidationError.Providers[key]: ["embedded message failed validation"] | caused by JwtProviderValidationError.LocalJwks: ["embedded message failed validation"]
      | caused by DataSourceValidationError.InlineString: ["value length must me least " '\x01' " by bytes"])

###### Below are the option we tried to make it work:
1. Certificate of OIDC server was mounted to istiod pod /cacerts/extra.pem
  as suggested in below link: 
  https://github.com/istio/istio/pull/17176/commits/b2e75632ffe490e7b35d0f6781bf3b5c2aeae6db

2. Also tried to place certificate under "jwksResolverExtraRootCA" in istio configmap 
as suggested in the below link : https://github.com/istio/istio/pull/17176

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

[ ] Multi Cluster
[X] Virtual Machine
[ ] Multi Control Plane

Istio version 1.6.4 Kubernetes version 1.16.9

How was Istio installed?
Using istioctl

**Comment by yangminzhu** [comment]
it looks like istiod failed to talk to your jwks server due to timeout: `failed to fetch public key from https://myapp/jwks.json context deadline exceeded  client.timeout excceded while awaiting headers`, I would expect some a different and explicit error message if it's caused by the self-signed certificate.

Could you double check if your istiod is able to talk to your jwks server, you can try this by sending some manual curl requests inside the istiod pod.

**Comment by SachinVarghese** [comment]
Found the same issue with Istio v1.7.3
```
0.0.0.0_8080: Proto constraint validation failed (JwtAuthenticationValidationError.Providers[key]: ["embedded message failed validation"] 
| caused by JwtProviderValidationError.LocalJwks: ["embedded message failed validation"] 
| caused by DataSourceValidationError.Inlin ││ eString: ["value length must be at least " '\x01' " bytes"])
```

**Comment by SachinVarghese** [comment]
@yangminzhu I am facing an issue with jwksuri with self-signed certificate as mentioned [above](https://github.com/istio/istio/issues/26984#issuecomment-745347235). My case doesn't have the `context deadline exceeded client.timeout exceeded while awaiting headers` as you suggested. Please reopen this issue/suggest possible solutions. Thanks.
