### ISSUE TITLE
USR1 signal should reopen pilot log

### ISSUE THREAD

**Issue by rowe0x** [istio/istio#26980]
When use  logrotate, istio don't handle USR1 propertly to reopen log file.
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Comment by howardjohn** [comment]
What is user defined logrotate?

**Comment by rowe0x** [comment]
> What is user defined logrotate?

use istio logratote instead of linux crontab

**Comment by howardjohn** [comment]
What is istio logrotate? Logs go to stdout I thought

**Comment by rowe0x** [comment]
> What is istio logrotate? Logs go to stdout I thought
We can log target to file like this
```
--log_target="./log/pilot.log" --log_output_level=all:info --registries=  --log_caller=all ...
```

**Comment by howardjohn** [comment]
wow, I had no clue we did that. Seems like a bad idea, kubernetes should always log to stdout...
