### ISSUE TITLE
Istioctl operator init with revision uses incorrect serviceaccount

### ISSUE THREAD

**Issue by WitoDelnat** [istio/istio#26991]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

We are experimenting with Istio operators to ease maintenance.

Our goal was to start the operator on our current version and upgrade to the latest.
This allows us to try the canary upgrade feature which is why we are making the switch.
The experiment was ran on Minikube on Kubernetes v1.17.5.

```
istio operator init --revision 1-6-2
```

The command fails with the following command:

>  Warning  FailedCreate  0s (x10 over 2s)  replicaset-controller  Error creating: pods "istio-operator-1-6-2-5f4d5b989f-" is forbidden: error looking up service account istio-operator/istio-operator: serviceaccount "istio-operator" not found

A quick look at the available service accounts in istio-operator shows that we have a service account with name: `istio-operator-1-6-2`. A workaround is to manually create a service account with the correct name. This is done by, for example, executing `kubectl create --namespace istio-operator serviceaccount istio-operator`. Afterwards the deployment continues as expected, otherwise it fails with a timeout after 5 minutes.

Note: This also happens with revision set to 1-7-0.

TLDR: It seems that initialising an operator with a specific revision incorrectly sets the serviceaccount.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

`istioctl operator init --revision 1-6-2` should correctly use the service account `istio-operator-1-6-2` instead `istio-operator`.

**Steps to reproduce the bug**

Install Istio with `istioctl operator init --revision 1-6-2`

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

```
▶ istioctl version --remote
client version: 1.7.0
control plane version: 1.6.2-70f86ede30e826dd18542e95d856255e9780a24f
data plane version: 1.6.2 (3 proxies)
```

```
▶ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-27T00:38:11Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"e0fccafd69541e3750d460ba0f9743b90336f24f", GitTreeState:"clean", BuildDate:"2020-04-16T11:35:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**

Through the command line `istioctl operator init --revision 1-6-2`.

**Environment where bug was observed (cloud vendor, OS, etc)**

Minikube

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

Note: It's my first time reporting an issue on an open source project. Feedback is welcome if I should've done something differently.

**Comment by howardjohn** [comment]
cc @richardwxn @ostromart

**Comment by morvencao** [comment]
This has been fixed in https://github.com/istio/istio/pull/26756 and the fix has been cherrypicked to `release-1.7`.

**Comment by WitoDelnat** [comment]
Thanks for looking into the problem! Should I close this?

**Comment by morvencao** [comment]
I'll close this, feel free to reopen if you still have problem.
