### ISSUE TITLE
[multi-cluster] Raise "HTTP/1.1 503 Service Unavailable" sometimes, when send request cross clusters.

### ISSUE THREAD

**Issue by johnzheng1975** [istio/istio#26990]
**Bug description**
[multi-cluster] Raise "HTTP/1.1 503 Service Unavailable" sometimes, when send request cross clusters.

- If I do not call one service more than 1 minutes, then call one api of this service again  (with servicename.namespacename.global), the fail rate is high: arrive 20 out of 1200.
- If I call the api of this service continually, each 2 seconds (with servicename.namespacename.global), the fail is very low: only 6 out of 100000.

Environment:
 (istio1.4.6,  replicate control panel,  AWS, Using Public NLB as ingressgateway service)

**Affected features (please put an X in all that apply)**

[x] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

 

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
istio 1.4.6

**How was Istio installed?**
istio multi-cluster

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS EKS1.16
 

---------------------------------
**Pre-condition**: Create two clusters, install with multi-cluster.
Step 1:  Create nginxclient in cluster1.
```
kubectl run --image=johnzheng/nginx nginxclient --generator=run-pod/v1
```
Step 2: Create nginx2 service in cluster2
```
kubectl run nginx2  --image=johnzheng/nginx --expose=true --port=80
```
Step 3: Create service entry for nginx2.default.global.
Step 4: Test pass `kubectl exec -ti nginxclient -- curl -i nginx2.default.global`
Step 5: Write script as below:
```
#!/bin/bash
for i in {1..200}; 
do
  date>> testresult.txt;
  kubectl exec -ti nginxclient -- curl -i nginx2.default.global/ >> testresult.txt;
  sleep 600;
done;
```
Test with `nohup ./hi.sh > /dev/null 2>&1 &`
Step 6: Summarize the test result:
```
cat testresult.txt |grep "HTTP/1.1 200 OK"|wc -l   #Pass Count
cat testresult.txt |grep "503"|wc -l   #Fail Count
```
You will find fail rate may over 20%

**Comment by johnzheng1975** [comment]
Is there anyone else meet such issue? Can you give some work arround? Thanks.

**Comment by shubhamitc** [comment]
I am also facing the same issue on istio version 1.7. Same setup was working fine for istio 1.6. 
Curl command failure
```sh
curl -H "Host: httpbin.bar.global"  httpbin.bar.global:8000 -I
HTTP/1.1 503 Service Unavailable
content-length: 91
content-type: text/plain
date: Wed, 02 Sep 2020 15:25:48 GMT
server: envoy
```

Kube-dns configmap
```yaml
apiVersion: v1
data:
  stubDomains: |
    {"global": ["10.100.141.243"]}
kind: ConfigMap
metadata:
  creationTimestamp: 2020-08-24T09:00:06Z
  name: kube-dns
  namespace: kube-system
```

Coredns configmap
```yaml

apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          upstream
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
    global:53 {
        errors
        cache 30
        forward . 10.100.141.243:53
    }
kind: ConfigMap
metadata:
  labels:
    eks.amazonaws.com/component: coredns
    k8s-app: kube-dns
  name: coredns
  namespace: kube-system
```
Istiodns address
```sh
$ kubectl get svc -n istio-system istiocoredns -o jsonpath={.spec.clusterIP}
10.100.141.243
```
From the same cluster
```sh
root@nginx-pod:/# nslookup httpbin.bar.global
Server:		169.254.20.10
Address:	169.254.20.10#53

** server can't find httpbin.bar.global: NXDOMAIN
```
From other clusters
```sh
nslookup httpbin.bar.global
Server:		169.254.20.10
Address:	169.254.20.10#53

Name:	httpbin.bar.global
Address: 240.0.0.2
** server can't find httpbin.bar.global: NXDOMAIN
```
SE entry
```yaml
apiVersion: v1
items:
- apiVersion: networking.istio.io/v1beta1
  kind: ServiceEntry
  metadata:
    generation: 2
    name: httpbin-bar
    namespace: foo
    resourceVersion: "948088"
    selfLink: /apis/networking.istio.io/v1beta1/namespaces/foo/serviceentries/httpbin-bar
    uid: 867a214e-2561-4a48-936d-0c41640dfafb
  spec:
    addresses:
    - 240.0.0.2
    endpoints:
    - address: a256e6f45146d41d5ac47dc62943fe15-c24bfa177ac58a99.elb.eu-west-1.amazonaws.com
      ports:
        http1: 15443
    hosts:
    - httpbin.bar.global
    location: MESH_INTERNAL
    ports:
    - name: http1
      number: 8000
      protocol: http
    resolution: DNS
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Comment by smawson** [comment]
Nate can you take a look at this?

**Comment by nmittler** [comment]
I think I may have replicated the issue with Istio 1.7 on GKE. It's been a bit slow-going since I had to remember how all of this works :). Still digging into it.

We're moving away from this method (.global) of configuring multi-primary. There are a lot of reasons for this (general complexity, odd load balancing behavior, loss of locality LB, etc.).  The new [installation instructions for 1.8](https://docs.google.com/document/d/1EZeTaoFb--Rr4EpJsjMBnRtm1VZT14mJpRbPJiJh37M/edit) use a simpler approach that lets `cluster.local` work across the mesh in the same way that it does for primary-remote. Load balancing works properly in this model as well, since each control plane has all of the actual endpoints from every cluster and can load balance evenly across them.

I haven't tried 1.6 yet, but I'll do that next week (off for the long weekend).

@stevenctl do you recall any changes post 1.6 that may have broken the old `.global` configuration for multi-primary?

**Comment by johnzheng1975** [comment]
Here is script, easy for your reproduce this issue:
```
for i in {1..60000}; 
do
  date>> dev_nginx2.txt;
  k exec -ti nginxnginx2 -- curl -i nginx2.default.global/ >> dev_nginx2.txt;
  sleep 2; #sleep 60;
done;
```

**Comment by zufardhiyaulhaq** [comment]
@nmittler the use cases may be different. I have the same setup as @johnzheng1975. Currently, in my cases, we don't want to load balance the traffic to another cluster (because separate of concern). We only want to automate mTLS communication between multiple clusters.

**Comment by shubhamitc** [comment]
I have the same requirement as @zufardhiyaulhaq

**Comment by johnzheng1975** [comment]
@nmittler , how about your test results for istio1.6? And, can you elaborate more details why this issue raise. Thanks a lot.

**Comment by stevenctl** [comment]
@zufardhiyaulhaq @shubhamitc 
> We only want to automate mTLS communication between multiple clusters.

Creating the `Service` in both the source/destination clusters should allow you to do this with `cluster.local`. 

@nmittler 
Nothing obvious that I can think of, although I'm not really familiar with the istiocoredns stuff.

**Comment by nmittler** [comment]
It turns out I had an issue with my initial coredns configuration, which I've resolved.  With that fix, this all seems to be working for me on gke with both Istio 1.6 and 1.7.

I've re-worked my test environment so that I only deploy HelloWorld to one cluster, so that it's more similar to the issue here. Here are the scripts I'm using:

- [Install Control Plane](https://gist.github.com/nmittler/6927d333c4b00b2c02cdbd9bf973dbd5).
- [Install Services](https://gist.github.com/nmittler/c7c8ee14db6923e7269690ac3f158f9c). This installs HelloWorld in cluster1 and the sleep service in both clusters. It also adds a ServiceEntry to each cluster. For the cluster that hosts HelloWorld, the SE refers to the service IP (rather than ingress). For the other cluster, it references the ingress.
- [Test](https://gist.github.com/nmittler/ea7c3b345edbf893b198f300b5d61078) calls the HelloWorld service from both clusters.

Example:

```bash
./install_control_plane.sh $CTX1
./install_control_plane.sh $CTX2
./install_services.sh $CTX1 $CTX2
./test.sh $CTX1 $CTX2
```

Take a look and maybe give it a run to see if this works for you.

**Comment by zufardhiyaulhaq** [comment]
@stevenctl it also will not works in my cases. when we communicate with the cluster.local, it will load balance between traffic in the local cluster and remote cluster right if we have the same service and namespace.

@nmittler can you do this following behaviour?

1. try to communicate with the other cluster service
2. wait for 2-10 minutes
3. try to communicate again with other cluster service

**Comment by stevenctl** [comment]
Ah so you want: 
```    
a ---> b (local cluster)
|
x
|
b (another cluster)   
```

This can be accomplished by setting up MeshConfig service settings ([doc](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig-ServiceSettings-Settings)) with something like:

```
serviceSettings: 
  - settings:
	  clusterLocal: true
	hosts:
	  - "b.ns.svc.cluster.local"
```

**Comment by zufardhiyaulhaq** [comment]
@stevenctl we still want to communicate with b service in another cluster from the local cluster (service a). that is why we cannot go with this solution.

**Comment by stevenctl** [comment]
You want to specifically choose when to hit the remote cluster and the local cluster, using `.global`? Just want to make sure I understand correctly.

**Comment by johnzheng1975** [comment]
@nmittler , are you testing "sleep 60" and "sleep 2", as below
```
for i in {1..60000}; 
do
  date>> dev_nginx2.txt;
  k exec -ti nginxnginx2 -- curl -i nginx2.default.global/ >> dev_nginx2.txt;
  sleep 2; #sleep 60;
done;
```
Can you tell me the fail rate for "sleep 60", and fail rate of "sleep 2"？ 
Note that you need at lease run 12 hours, to check issue exists or not on 1.6 and 1.7. Thanks.

**Comment by zufardhiyaulhaq** [comment]
@stevenctl in my use case, we have multiple clusters. I modify `.global` and change that to `.<cluster-name>`. Here is where things get complicated.

cluster A -> cluster B
cluster A -> cluster C
cluster A -> cluster D

both cluster B, C, and D have the same service name and namespace. So from cluster A, I call each service like this:
```
service.namespace.cluster-b
service.namespace.cluster-c
service.namespace.cluster-d
```

and from cluster A, using this feature, we won't load balance to multiple clusters. You can check this PR https://github.com/istio/istio/pull/25349 how we change `.global` to specific cluster name.

**Comment by shubhamitc** [comment]
> ```shell
> b_cluster2
> ```

Tried the scripts above, still the same problem in EKS with istio 1.7

 curl 172.25.70.123:8000/ip  -vv
*   Trying 172.25.70.123:8000...
* Connected to 172.25.70.123 (172.25.70.123) port 8000 (#0)
> GET /ip HTTP/1.1
> Host: 172.25.70.123:8000
> User-Agent: curl/7.69.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 503 Service Unavailable
< content-length: 91
< content-type: text/plain
< date: Fri, 11 Sep 2020 11:53:28 GMT
< server: envoy
< x-envoy-upstream-service-time: 0
<
* Connection #0 to host 172.25.70.123 left intact
upstream connect error or disconnect/reset before headers. reset reason: connection failure/ #

**Comment by nmittler** [comment]
I seem to be unable to replicate on gke. I updated my test script to wait 2 minutes between calls, but it seems to work fine. I don't have EKS environment to test on ATM. 

I'm running with coredns 1.7.0.

**Comment by shubhamitc** [comment]
let me try that in gke to verify.

**Comment by shubhamitc** [comment]
we are seeing the same issue on gke 1.6 and istio 1.7.1. We enabled the debug flag and below is the logs from ingress-gateway for istio 1.7.1 

```
istio-ingressgateway-8444796578-jfmq2 istio-proxy 2020-09-15T10:02:35.560187973Z 2020-09-15T10:02:35.559950Z    debug   envoy filter    tls inspector: new connection accepted
istio-ingressgateway-8444796578-jfmq2 istio-proxy 2020-09-15T10:02:35.560237748Z 2020-09-15T10:02:35.560012Z    debug   envoy filter    tls:onServerName(), requestedServerName: outbound_.8000_._.httpbin.bar.global
istio-ingressgateway-8444796578-jfmq2 istio-proxy 2020-09-15T10:02:35.560329863Z 2020-09-15T10:02:35.560092Z    debug   envoy filter    [C194] new tcp proxy session
istio-ingressgateway-8444796578-jfmq2 istio-proxy 2020-09-15T10:02:35.560344579Z 2020-09-15T10:02:35.560128Z    debug   envoy connection        [C194] closing data_to_write=0 type=1
istio-ingressgateway-8444796578-jfmq2 istio-proxy 2020-09-15T10:02:35.560351496Z 2020-09-15T10:02:35.560133Z    debug   envoy connection        [C194] closing socket: 1
```

While the same for EKS and istio 1.6.8 looks like below, which works
```
2020-09-15T10:17:59.967796Z     debug   envoy filter    [external/envoy/source/common/tcp_proxy/tcp_proxy.cc:251] [C814] new tcp proxy session
2020-09-15T10:17:59.967835Z     debug   envoy filter    [external/envoy/source/common/tcp_proxy/tcp_proxy.cc:395] [C814] Creating connection to cluster outbound_.8000_._.httpbin.bar.svc.cluster.local
2020-09-15T10:17:59.967958Z     debug   envoy conn_handler      [external/envoy/source/server/connection_handler_impl.cc:403] [C814] new connection
```

We have verified that istio-coredns version is 1.6.2 for both of them. Based on these logs it looks like EnvoyFilter is not being called in 1.7.1 to rewrite the requests from .global to .cluster.local. 

istio 1.7

* ingress gateway
```
+ kubectl get deployment istio-ingressgateway -n istio-system -o yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-09-15T09:29:42Z"
  generation: 1
  labels:
    app: istio-ingressgateway
    install.operator.istio.io/owning-resource: installed-state
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio: ingressgateway
    istio.io/rev: default
    operator.istio.io/component: IngressGateways
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.7.1
    release: istio
  name: istio-ingressgateway
  namespace: istio-system
  resourceVersion: "9246"
  selfLink: /apis/apps/v1/namespaces/istio-system/deployments/istio-ingressgateway
  uid: 0b410e61-65d2-45ef-965d-dbe4dbadebf0
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: istio-ingressgateway
      istio: ingressgateway
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: /stats/prometheus
        prometheus.io/port: "15090"
        prometheus.io/scrape: "true"
        sidecar.istio.io/inject: "false"
      creationTimestamp: null
      labels:
        app: istio-ingressgateway
        chart: gateways
        heritage: Tiller
        istio: ingressgateway
        release: istio
        service.istio.io/canonical-name: istio-ingressgateway
        service.istio.io/canonical-revision: latest
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
            weight: 2
          - preference:
              matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - ppc64le
            weight: 2
          - preference:
              matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - s390x
            weight: 2
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
      containers:
      - args:
        - proxy
        - router
        - --domain
        - $(POD_NAMESPACE).svc.cluster.local
        - --proxyLogLevel=warning
        - --proxyComponentLogLevel=misc:error
        - --log_output_level=default:info
        - --serviceCluster
        - istio-ingressgateway
        - --trust-domain=cluster.local
        env:
        - name: JWT_POLICY
          value: third-party-jwt
        - name: PILOT_CERT_PROVIDER
          value: istiod
        - name: CA_ADDR
          value: istiod.istio-system.svc:15012
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: INSTANCE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.serviceAccountName
        - name: CANONICAL_SERVICE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['service.istio.io/canonical-name']
        - name: CANONICAL_REVISION
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['service.istio.io/canonical-revision']
        - name: ISTIO_META_WORKLOAD_NAME
          value: istio-ingressgateway
        - name: ISTIO_META_OWNER
          value: kubernetes://apis/apps/v1/namespaces/istio-system/deployments/istio-ingressgateway
        - name: ISTIO_META_MESH_ID
          value: cluster.local
        - name: ISTIO_META_ROUTER_MODE
          value: sni-dnat
        - name: ISTIO_META_CLUSTER_ID
          value: Kubernetes
        image: docker.io/istio/proxyv2:1.7.1
        imagePullPolicy: IfNotPresent
        name: istio-proxy
        ports:
        - containerPort: 15021
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        - containerPort: 15443
          protocol: TCP
        - containerPort: 15090
          name: http-envoy-prom
          protocol: TCP
        readinessProbe:
          failureThreshold: 30
          httpGet:
            path: /healthz/ready
            port: 15021
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "2"
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/istio/proxy
          name: istio-envoy
        - mountPath: /etc/istio/config
          name: config-volume
        - mountPath: /var/run/secrets/istio
          name: istiod-ca-cert
        - mountPath: /var/run/secrets/tokens
          name: istio-token
          readOnly: true
        - mountPath: /var/run/ingress_gateway
          name: gatewaysdsudspath
        - mountPath: /etc/istio/pod
          name: podinfo
        - mountPath: /etc/istio/ingressgateway-certs
          name: ingressgateway-certs
          readOnly: true
        - mountPath: /etc/istio/ingressgateway-ca-certs
          name: ingressgateway-ca-certs
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1337
        runAsGroup: 1337
        runAsNonRoot: true
        runAsUser: 1337
      serviceAccount: istio-ingressgateway-service-account
      serviceAccountName: istio-ingressgateway-service-account
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: istio-ca-root-cert
        name: istiod-ca-cert
      - downwardAPI:
          defaultMode: 420
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels
            path: labels
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.annotations
            path: annotations
        name: podinfo
      - emptyDir: {}
        name: istio-envoy
      - emptyDir: {}
        name: gatewaysdsudspath
      - name: istio-token
        projected:
          defaultMode: 420
          sources:
          - serviceAccountToken:
              audience: istio-ca
              expirationSeconds: 43200
              path: istio-token
      - configMap:
          defaultMode: 420
          name: istio
          optional: true
        name: config-volume
      - name: ingressgateway-certs
        secret:
          defaultMode: 420
          optional: true
          secretName: istio-ingressgateway-certs
      - name: ingressgateway-ca-certs
        secret:
          defaultMode: 420
          optional: true
          secretName: istio-ingressgateway-ca-certs
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-09-15T09:30:03Z"
    lastUpdateTime: "2020-09-15T09:30:03Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-09-15T09:29:42Z"
    lastUpdateTime: "2020-09-15T09:30:03Z"
    message: ReplicaSet "istio-ingressgateway-6f59657d45" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
```

* envoyfilter
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.istio.io/v1alpha3","kind":"EnvoyFilter","metadata":{"annotations":{},"labels":{"app":"istio-ingressgateway","install.operator.istio.io/owning-resource":"installed-state","install.operator.istio.io/owning-resource-namespace":"istio-system","istio":"ingressgateway","istio.io/rev":"default","operator.istio.io/component":"IngressGateways","operator.istio.io/managed":"Reconcile","operator.istio.io/version":"1.7.1","release":"istio"},"name":"istio-multicluster-ingressgateway","namespace":"istio-system"},"spec":{"configPatches":[{"applyTo":"NETWORK_FILTER","match":{"context":"GATEWAY","listener":{"filterChain":{"filter":{"name":"envoy.filters.network.sni_cluster"}},"portNumber":15443}},"patch":{"operation":"INSERT_AFTER","value":{"config":{"cluster_pattern":"\\.global$","cluster_replacement":".svc.cluster.local"},"name":"envoy.filters.network.tcp_cluster_rewrite"}}}],"workloadSelector":{"labels":{"istio":"ingressgateway"}}}}
  creationTimestamp: "2020-09-15T09:29:41Z"
  generation: 1
  labels:
    app: istio-ingressgateway
    install.operator.istio.io/owning-resource: installed-state
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio: ingressgateway
    istio.io/rev: default
    operator.istio.io/component: IngressGateways
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.7.1
    release: istio
  name: istio-multicluster-ingressgateway
  namespace: istio-system
  resourceVersion: "9077"
  selfLink: /apis/networking.istio.io/v1alpha3/namespaces/istio-system/envoyfilters/istio-multicluster-ingressgateway
  uid: 586bb1aa-5ca6-411d-9f06-82904ef9e6b3
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.sni_cluster
        portNumber: 15443
    patch:
      operation: INSERT_AFTER
      value:
        config:
          cluster_pattern: \.global$
          cluster_replacement: .svc.cluster.local
        name: envoy.filters.network.tcp_cluster_rewrite
  workloadSelector:
    labels:
      istio: ingressgateway
```

**Comment by nmittler** [comment]
@shubhamitc thanks for the detail, that's helpful

@rshriram seems like something changed in 1.7 WRT DNS in multi-network scenarios ... Could you take a look?

**Comment by shubhamitc** [comment]
thanks @nmittler I will wait for further updates here.

**Comment by shubhamitc** [comment]
Any updates?

**Comment by Sathishkunisai** [comment]
In my case, I have two envoyfilters . first one is to change .global to .local and its a default one which gets created by enabling multicluster in the istio operator. Second one is have patter like the below 

          cluster_pattern: \.region.environment.global$
          cluster_replacement: .svc.cluster.local

It was working for a long time. But suddently .global to .local transform is broken and getting 503 error as highlighted in this thread.  Is there any way to re-register DNS entries? I have 1.6.7 istio running . any suggestion to upgrade to next version

* Mark bundle as not supporting multiuse
< HTTP/1.1 503 Service Unavailable
< content-length: 95
< content-type: text/plain
< date: Mon, 28 Sep 2020 17:56:26 GMT
< server: envoy
<

**Comment by rshriram** [comment]
there is no DNS in 1.7

**Comment by Sathishkunisai** [comment]
@rshriram. . Thanks. appreciate if any recommendation to resolve this issue in 1.6.7 installation

**Comment by Sathishkunisai** [comment]
> I think I may have replicated the issue with Istio 1.7 on GKE. It's been a bit slow-going since I had to remember how all of this works :). Still digging into it.
> 
> We're moving away from this method (.global) of configuring multi-primary. There are a lot of reasons for this (general complexity, odd load balancing behavior, loss of locality LB, etc.). The new [installation instructions for 1.8](https://docs.google.com/document/d/1EZeTaoFb--Rr4EpJsjMBnRtm1VZT14mJpRbPJiJh37M/edit) use a simpler approach that lets `cluster.local` work across the mesh in the same way that it does for primary-remote. Load balancing works properly in this model as well, since each control plane has all of the actual endpoints from every cluster and can load balance evenly across them.
> 
> I haven't tried 1.6 yet, but I'll do that next week (off for the long weekend).
> 
> @stevenctl do you recall any changes post 1.6 that may have broken the old `.global` configuration for multi-primary?

document is not accessible, please share steps to request access

**Comment by san360** [comment]
I am facing same issue in 1.7

**Comment by selfieblue** [comment]
I am facing same issue in 1.7.3
Ingress Access Log
```[2020-10-24T15:53:48.454Z] "- - -" 0 - "-" "-" 0 0 0 - "-" "-" "-" "-" "19.0.117.226:15012" outbound|15012||istiod.istio-system.svc.cluster.local 19.0.84.19:56012 19.0.84.19:15012 192.0.104.27:19730 - -
[2020-10-24T15:53:48.545Z] "- - -" 0 NR "-" "-" 0 0 0 - "-" "-" "-" "-" "-" - - 19.0.84.19:15443 192.0.97.71:54737 - -
[2020-10-24T15:53:48.553Z] "- - -" 0 NR "-" "-" 0 0 0 - "-" "-" "-" "-" "-" - - 19.0.84.19:15443 192.0.157.39:21818 - -
[2020-10-24T15:53:48.584Z] "- - -" 0 NR "-" "-" 0 0 0 - "-" "-" "-" "-" "-" - - 19.0.84.19:15443 192.0.183.190:33503 - -
[2020-10-24T15:53:48.585Z] "- - -" 0 - "-" "-" 0 0 0 - "-" "-" "-" "-" "19.0.117.226:15012" outbound|15012||istiod.istio-system.svc.cluster.local 19.0.84.19:56016 19.0.84.19:15012 192.0.157.39:17531 - -```

**Comment by jurschel** [comment]
@nmittler Do you have any idea what the solution to this problem might be short of wholesale upgrade? We are on the same version 1.4.6 in a multi-network, multi-cluster replicated control plane single mesh deployment and we can clearly provide logging that shows istio-coredns-plugin fails to resolve .global addresses sometimes and then nanoseconds later they resolve.  This results in 503 UC for my services... Anyone with any strange 503s and running the 1.4.6 version using .global namespace search for this in your logs "Could not find the service requested" and see if you find the same problem.

`2020-09-30T23:22:06.106848Z info adding DNS mapping: cdp.cdp.global.->[240.0.0.4]
2020-09-30T23:22:09.703372Z info DNS query ;; opcode: QUERY, status: NOERROR, id: 13547
;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;cdp.cdp.global. IN A
2020-09-30T23:22:09.703463Z info Query A record: cdp.cdp.global.->{cdp.cdp.global. 1 1}
2020-09-30T23:22:09.703499Z info Found cdp.cdp.global.->[240.0.0.4]
2020-09-30T23:22:09.703835Z info DNS query ;; opcode: QUERY, status: NOERROR, id: 18786
;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;cdp.cdp.global. IN AAAA
2020-09-30T23:22:09.703865Z info Could not find the service requested
2020-09-30T23:22:11.105402Z info Reading service entries at 2020-09-30 23:22:11.105369581 +0000 UTC m=+5537655.042185524
2020-09-30T23:22:11.106628Z info Have 5 service entries
2020-09-30T23:22:11.106707Z info adding DNS mapping: one-time-password.one-time-password.global.->[240.0.0.3]
2020-09-30T23:22:11.106719Z info adding DNS mapping: cdp.cdp.global.->[240.0.0.4]`

**Comment by Sathishkunisai** [comment]
@jurschel similar issue noticed in 1.6.11 as well, did upgrade from 1.6.2 to 1.6.8 and then to 1.6.11. issue remain same.

**Comment by nmittler** [comment]
@jurschel @Sathishkunisai This was never a well tested or maintained configuration, unfortunately. Starting in 1.8 multicluster is moving to Beta, but without the use of the `.global` hack ... we don't recommend or document this approach for beta.

I've heard some folks have had some amount of success with 1.7.3, so you could try upgrading. I think the best approach at this point, however, would be to upgrade to 1.8 when it's available and migrate to the new configuration.

**Comment by sagyvm** [comment]
@nmittler Even Istio 1.7.3 does not help. Still getting NR from Ingress gateway of remote cluster.

[2020-11-03T07:59:45.573Z] "- - -" 0 NR "-" "-" 0 0 0 - "-" "-" "-" "-" "-" - - 192.168.62.201:15443 192.168.5.201:49230 - -
[2020-11-03T07:59:49.995Z] "- - -" 0 NR "-" "-" 0 0 0 - "-" "-" "-" "-" "-" - - 192.168.62.201:15443 192.168.1.103:55900 - -
[2020-11-03T07:59:50.006Z] "- - -" 0 NR "-" "-" 0 0 0 - "-" "-" "-" "-" "-" - - 192.168.62.201:15443 192.168.5.201:24778 -

**Comment by zufardhiyaulhaq** [comment]
Hey, I think I found a solution, we can use `httpRetry` via Virtual Service. I have same error but with different use cases. This use cases is to automatically communicate mTLS with custom certificate (self signed CA / public CA). In the first cycle, I use this configuration to force using mTLS
```
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: <domain>-external-mtls-se
  namespace: <namespace>
spec:
  hosts:
  - <domain>
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
  exportTo:
  - "."
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: <domain>-external-mtls-dr
  namespace: <namespace>
spec:
  host: <domain>
  subsets:
  - name: tls-origination
    trafficPolicy:
      portLevelSettings:
      - port:
          number: 443
        tls:
          mode: MUTUAL
          clientCertificate: <path>/tls.crt
          privateKey: /<path>/tls.key
          caCertificates: <path>/ca.crt
          sni: <domain>
  exportTo:
  - "."
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: <domain>-external-mtls-vs
  namespace: <namespace>
spec:
  hosts:
  - <domain>
  http:
  - match:
    - port: 80
    route:
    - destination:
        host: <domain>
        subset: tls-origination
        port:
          number: 443
  exportTo:
  - "."
```
and adding certificate via annotation
```
    sidecar.istio.io/userVolumeMount: '[{"name":"<domain>-mtls-cert", "mountPath":"<path>", "readonly":true}]'
    sidecar.istio.io/userVolume: '[{"name":"<domain>-mtls-cert", "secret":{"secretName":"<domain>-mtls-cert"}}]
```
I analyze that it keep getting 503 connection termination/reset. I find out that we can use `HTTPRetry` to force retrying sending the packet. So the Virtual Service will look like this:
```
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: <domain>-external-mtls-vs
  namespace: <namespace>
spec:
  hosts:
  - <domain>
  http:
  - match:
    - port: 80
    route:
    - destination:
        host: <domain>
        subset: tls-origination
        port:
          number: 443
    retries:
      attempts: 3
      perTryTimeout: 2s
      retryOn: 5xx
  exportTo:
  - "."
```
