### ISSUE TITLE
flake: TestWorkloadInstances/Kubernetes_only:_endpoint_occur_earlier

### ISSUE THREAD

**Issue by stevenctl** [istio/istio#27003]
Caused by either: #26944 or #26918, possible race condition.

**Comment by stevenctl** [comment]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/26997/unit-tests_istio/19993
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/26995/unit-tests_istio/19991
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/26908/unit-tests_istio/19988

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27043/unit-tests_istio/20105 @hzxuzhonghu your PR did not fix it

**Comment by hzxuzhonghu** [comment]
I will take a look, but i did run 100 times without failure
