### ISSUE TITLE
Istio (1.5.1) ingress gateway (envoy) heap memory grows unbounded, causing OOM when memory limit is exceeded

### ISSUE THREAD

**Issue by VRanga000** [istio/istio#27005]
In Istio 1.5.1 , we are seeing what appears to be a very similar issue with istio ingressgateway memory usage linearly increasing ending in an OOM due to memory limit exceeded. The tcp connections seem to not grow with the memory. But envoy heap size seems to be increasing monotonously and never being reclaimed, eventhough the "allocated" memory shrinks down when connections to the gateway drop. 

![istio_gateway_envoy_heap_vs_allocated](https://user-images.githubusercontent.com/7152444/92032990-8c859800-ed30-11ea-8008-6004e0b07ebd.png)

I am seeing a few different suggestions to address this:
1) upgrade to istio 1.6 / 1.7 
2) configure envoy with `envoy.overload_actions.shrink_heap` as suggested [here](https://github.com/istio/istio/issues/14366#issuecomment-548141596)

Could someone please advise / provide some guidance ? 

Thank you.

_Originally posted by @VRanga000 in https://github.com/istio/istio/issues/25145#issuecomment-685978376_

**Comment by howardjohn** [comment]
@lambdai we added heap reclaim but is it only for XDS?

**Comment by howardjohn** [comment]
This is an older version without it which is why I was not sure
