### ISSUE TITLE
Need to specify SameSite (None) as one of the options while using cookie for sticky sessions

### ISSUE THREAD

**Issue by pc-rshetty** [istio/istio#27006]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
Currently this config can be used to make sticky session work with a cookie

`

ield | Type | Description | Required
-- | -- | -- | --
name | string | Name of the cookie. | Yes
path | string | Path to set for the cookie. | No
ttl | Duration | Lifetime of the cookie. | Yes

`

This works great when we are working on the same domain. When we iframe our web application within another application(salesforce) due to the samesite restrictions that browsers like chrome have put in, the cookie is not being passed over (even though its going back to our own application)

Please read following for more details https://blog.heroku.com/chrome-changes-samesite-cookie

We are kinda blocked now since cookie creation is not in our control and istio creates it and browser doesn't pass it over due to iframing. We need an ability to set SameSite=None so this could be an additional param we can add to the existing name,ttl,path config we already have.

The default could be Lax

We also need to add an option to add secure 

Some comparison AWSELB cookie has default samesite=None and is marked as secure

**Describe alternatives you've considered**

Tried using header to make it sticky but first time i need to set it when making a call and that is a problem
Tried rewriting the cookie with this attribute but for reason my application cant get the cookie in the request (may be its hidden)

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X ] Networking
[X ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[X ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
Seems like Envoy only supports the options we expose: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto.html?highlight=cookie#envoy-v3-api-msg-config-route-v3-routeaction-hashpolicy-cookie

**Comment by pc-rshetty** [comment]
@howardjohn  thanks. What are my options. Can i append SameSite=None if i intercept the response . I will try this out. 
Any other option ?

**Comment by pc-rshetty** [comment]
I have my destination rule set like this 

`  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpCookie:
          name: mycookie
          path: /app
          ttl: 0s`

In my response i specifically set this 

addHeader("Set-Cookie","mycookie=70b96a6898a89c9b; Path=/app; SameSite=None; HttpOnly");

but this is not taking effect , may be envoy proxy sets it after my application finishes processing ?

**Comment by pc-rshetty** [comment]
this doesnt work since the envoy proxy sets the cookie and application has no way to modify or know about it .

@howardjohn is there a way to intercept and add some processing logic after envoy proxy or is there a way istio can add a logic to override envoy ?

**Comment by pc-rshetty** [comment]
I have added a feature request in envoy https://github.com/envoyproxy/envoy/issues/12970

**Comment by pc-rshetty** [comment]
We wrote this Envoy Filter to fix this issue

`apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: secure-session-cookie-filter
  namespace: istio-system
spec:
  workloadLabels:
    app: myingressgateway
  filters:
    - listenerMatch:
        listenerType: GATEWAY
      filterType: HTTP
      filterName: envoy.lua
      filterConfig:
        inlineCode: |
          function envoy_on_response(response_handle)
            function set_cookie_header(rh)
              s = rh:headers():get("Set-Cookie")
              if string.find(s, "mycookie=" ) and not string.find(s, "SameSite") then
                s = s.."; SameSite=None; Secure"
              end
              return s
            end
            if response_handle:headers():get("Set-Cookie") then
              secure_cookie_header = set_cookie_header(response_handle)
              response_handle:headers():replace("Set-Cookie",secure_cookie_header)
            end
          end`

**Comment by pbn4** [comment]
See my solution here https://github.com/envoyproxy/envoy/issues/12970#issuecomment-872243474

**Comment by ramaraochavali** [comment]
You can now set https://www.envoyproxy.io/docs/envoy/v1.30.2/api-v3/config/route/v3/route_components.proto.html#envoy-v3-api-msg-config-route-v3-routeaction-hashpolicy-cookie - Additional attributes on the cookie
