### ISSUE TITLE
datadog tracing default address is wrong

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#27016]
Install with ` --set values.global.proxy.tracer=datadog`
```
   {
       "name": "datadog_agent",
       "type": "STRICT_DNS",
       "connect_timeout": "1s",
       "dns_lookup_family": "V4_ONLY",
       "load_assignment": {
        "cluster_name": "datadog_agent",
        "endpoints": [
         {
          "lb_endpoints": [
           {
            "endpoint": {
             "address": {
              "socket_address": {
               "address": "$(HOST_IP)",
               "port_value": 8126
              }
             }
            }
           }
          ]
         }
        ]
       },
       "respect_dns_ttl": true
      }
```
This seems wrong.. I think we were supposed to resolve `$(HOST_IP)` before passing it to envoy?

**Comment by dmarkey** [comment]
I've found that `apm.datadoghq.com/env: '{ "DD_ENV": "dave" }'` on a deployment does not work, could it be related?

**Comment by cgilmour** [comment]
@howardjohn where do you see this? Normally the variable gets expanded by kubernetes when the pod launches (after sidecar injection).
It's working as-intended on my latest cluster running 1.7.0 and automatic sidecar injection enabled.

**Comment by howardjohn** [comment]
This was on `master` I believe. How does kubernetes expand it?

**Comment by cgilmour** [comment]
It's covered in the docs with a [brief mention](https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#use-environment-variables-to-define-arguments) and a bit more detail [here](https://kubernetes.io/docs/tasks/inject-data-application/define-interdependent-environment-variables/#define-an-environment-dependent-variable-for-a-container).

But the bit you pasted looks like rendered envoy config without a replacement occurring.

**Comment by howardjohn** [comment]
I think the address is (now?) set in the istio configmap instead of the pod spec so it probably isn't expanded. I thought we did this a while ago though so I am surprised it was working in 1.7. Let me look into it

**Comment by cgilmour** [comment]
The default value in the configmap would typically be `"$(HOST_IP):8126"` (under `tracer.datadog.address`), with the expansion of `$(HOST_IP)` occurring when the pod launches.

For a bit more explanation, it's because the datadog agent typically runs as a daemonset and listens for tracing traffic on port 8126. A `hostPort` binding is used, so tracing traffic sent to the actual host IP on port 8126 reaches the agent pod.

In any case, it shouldn't end up as the value for `socket_address` in envoy's config - the expansion should have happened before that.

**Comment by bianpengyuan** [comment]
From reading the original PR that introduces this, I cannot tell host HOST_IP is replaced. https://github.com/istio/istio/commit/d6aeaa4be18042f6da6063aff0f9806a3cdc192d  @cgilmour  Could you help me understand a bit about this?

**Comment by howardjohn** [comment]
I think k8s does it : https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/

**Comment by bianpengyuan** [comment]
Then I guess it is just that you cannot use environment variable (HOST_IP) interpretation for another environment variable (proxyConfig)

**Comment by bianpengyuan** [comment]
It actually works for me. So the order of env var declaration matters here.

**Comment by howardjohn** [comment]
If you just set `--set values.global.proxy.tracer=datadog` does it show up in the env var? Also proxy config can come from other sources - gateways mount mesh config, that may be where i saw the failure.

**Comment by bianpengyuan** [comment]
Yeah it happens only on gateway. We probably need some custom interpretation for tracer address.
