### ISSUE TITLE
Using isto-inressgateway, the client's real IP cannot be obtained

### ISSUE THREAD

**Issue by yuanyiran** [istio/istio#27026]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

**Affected product area (please put an X in all that apply)**

[ ] Networking
[ ] Security

**Affected features (please put an X in all that apply)**

[ ] Physical machine

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

istio 1.2.2
kubernetes 1.14.2
helm 2.16.0

**How was Istio installed?**

helm install istio 1.2.2 in kubernetes 1.14.2

**Environment where bug was observed (cloud vendor, OS, etc)**

Local physical machine kubernetes cluster istio no cluster deployment

**error describe**

I use isto-inressgateway routing in kubernetes (I don't use the inress of kubernetes), but when I get the IP of the login user inside the container, I get the IP of the client.

pod ip.
![image](https://user-images.githubusercontent.com/64528937/92060530-9d80e880-edc6-11ea-8344-ce51cec47c52.png)

IP from client method inside container.
![image](https://user-images.githubusercontent.com/64528937/92060361-1a5f9280-edc6-11ea-8519-9e07b6166357.png)

After investigation, the IP address obtained inside the container is the docker virtual IP network segment generated by one of the node nodes.
![image](https://user-images.githubusercontent.com/64528937/92061071-f4d38880-edc7-11ea-8643-90be54cf15c8.png)

The IP of all work nodes is configured in isto-inressgateway.
![image](https://user-images.githubusercontent.com/64528937/92061363-aa9ed700-edc8-11ea-8dd4-a8a3827811a5.png)

I hope I can get the real access IP of browser client in my container. What should I do? My container is a java project, which is forwarded through virtualservice.

**Comment by howardjohn** [comment]
Duplicate of https://github.com/istio/istio/issues/21527

Also see https://istio.io/news/support/announcing-1.2-eol/, we cannot support this version
