### ISSUE TITLE
Question: Are there any sidecar configuration optimizations

### ISSUE THREAD

**Issue by pantianying** [istio/istio#27028]
Currently,istio distributes all the services in the cluster to Sidecar, which will cause a huge waste of sidecar resources. Of course, we can assign CR: Sidecar to deliver some service envoy to the designated envoy. However, in a complex and large clustered environment, it is difficult to determine which services are dependent on. Infrastructure teams are often unaware of the complex dependencies of business services. So Here I want to ask if istio has some configuration optimizations. Like subscription services, lazy loading, etc.?

thanks

**Comment by howardjohn** [comment]
The only mechanism we offer for this is Sidecar CR. We do not have lazy loading yet. Tracked in https://github.com/istio/istio/issues/19681

**Comment by howardjohn** [comment]
Closing as duplicate of https://github.com/istio/istio/issues/19681. thanks
