### ISSUE TITLE
Envoy under Istio does not preserve/respect charset= header value

### ISSUE THREAD

**Issue by shinynz** [istio/istio#27031]
Isto will change my request GBK character set to UTF-8 by default, resulting in garbled requests

**Comment by esnible** [comment]
@shinynz Can you provide instructions so that I can reproduce this?

**Comment by shinynz** [comment]
![微信图片_20200907142128 png](https://user-images.githubusercontent.com/15795798/92354746-76534f80-f115-11ea-8608-f6a6c4d26b8f.png)
@esnible

**Comment by shinynz** [comment]
I used GBK character to request through isto, and it became UTF-8 character

**Comment by esnible** [comment]
I tried this morning using Istio 1.7.0

I deployed httpbin and httpbin-gateway, so that I could see the headers arriving at my service.

From within the mesh the charset was preserved, as verified by `kubectl exec deploy/httpbin -c istio-proxy -- curl -v -H "Content-Type: application/json;charset=GBK" http://httpbin.default:8000/headers`

From outside the mesh the charset was preserved, as verified by 

```
export INGRESS_HOST=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
curl -v -H "Content-Type: application/json;charset=GBK" $INGRESS_HOST/headers
```

Is it possible you are looking at the response charset?  That is set by the server, I think.  Httpbin doesn't seem to support this but I believe you should try adding header `Accept: application/json;charset=GBK.`

**Comment by shinynz** [comment]
Oh, my application content-type is `application / XML; charset = GBK`, does isto support the character set of `application / XML`

**Comment by shinynz** [comment]
Our microservices need to call the external third-party interface, which uses GBK and XML format post data. In istio 1.7 or 1.6.7 environment, check our log request that there is no garbled code in the whole message < tbrname > JIANG Yunlong < / tbrname >, and at the same time, the content type charset = GBK of the header is forced, but the result returned by the other party is "?" If the operation is in a stand-alone k8s1.16.9 environment, the problem will not occur.  @esnible

**Comment by shinynz** [comment]
![截图录屏_选择区域_20200909184314](https://user-images.githubusercontent.com/15795798/92588976-67fb6400-f2cc-11ea-8362-d77edfa44c8f.png)
![lALPGpb_8FHGxaDNAqLNBmk_1641_674](https://user-images.githubusercontent.com/15795798/92588979-69c52780-f2cc-11ea-8817-fc9a929ba0fd.png)
@esnible

**Comment by esnible** [comment]
I don't know how to test this.  I don't know an XML server that supports `charset=`.

With Istio out of the picture, from my laptop, I did `curl -v -H "Accept-charset: utf-8" -H "Accept: text/xml;charset=utf-8" httpbin.org/xml` but the response was in `us-ascii`, not `utf-8`.

If I could get an XML test server running i the mesh that supported GBK and other charsets I could help triage this.  Do you know of one?

I will mark this as a data plane issue, to see if anyone on the networking team knows how to test this easily.

**Comment by howardjohn** [comment]
Any more info on how to reproduce?

**Comment by howardjohn** [comment]
Ping, any info?
