### ISSUE TITLE
istio proxy logs showing routes envory startup

### ISSUE THREAD

**Issue by satishmane** [istio/istio#27030]
**Bug description**

I see headless service routes logged at every 30m. ( --keepaliveMaxServerConnectionAge   - 30m ). As I understand pilot closes connection every 30m and reload configs. But how I do turn off printing these headless routes in proxy log

2020-09-03T05:37:48.056298Z	info	Channel Connectivity change to READY
{"bytes_sent":"276","upstream_cluster":"outbound|9092||*.infra-kafka-headless.infra.svc.cluster.local","downstream_remote_address":"172.18.3.18:50450","authority":"-","path":"-","protocol":"-","upstream_service_time":"-","upstream_local_address":"172.18.3.18:50452","duration":"540218","upstream_transport_failure_reason":"-","route_name":"-","downstream_local_address":"172.18.3.16:9092","user_agent":"-","response_code":"0","response_flags":"-","start_time":"2020-09-03T05:30:35.613Z","method":"-","request_id":"-","upstream_host":"172.18.3.16:9092","x_forwarded_for":"-","requested_server_name":"-","bytes_received":"30","istio_policy_status":"-"}
{"response_flags":"-","start_time":"2020-09-03T04:48:26.025Z","method":"-","request_id":"-","upstream_host":"127.0.0.1:9092","x_forwarded_for":"-","requested_server_name":"outbound_.9092_._.*.infra-kafka-headless.infra.svc.cluster.local","bytes_received":"434","istio_policy_status":"-","bytes_sent":"2846","upstream_cluster":"inbound|9092|kafka|infra-kafka-headless.infra.svc.cluster.local","downstream_remote_address":"172.18.3.15:42938","authority":"-","path":"-","protocol":"-","upstream_service_time":"-","upstream_local_address":"127.0.0.1:60076","duration":"3360504","upstream_transport_failure_reason":"-","route_name":"-","downstream_local_address":"172.18.3.18:9092","user_agent":"-","response_code":"0"}
{"upstream_cluster":"outbound|9092||*.infra-kafka-headless.infra.svc.cluster.local","downstream_remote_address":"172.18.3.18:58760","authority":"-","path":"-","protocol":"-","upstream_service_time":"-","upstream_local_address":"172.18.3.18:58762","duration":"1679393","upstream_transport_failure_reason":"-","route_name":"-","downstream_local_address":"172.18.3.15:9092","user_agent":"-","response_code":"0","response_flags":"-","start_time":"2020-09-03T05:22:02.806Z","method":"-","request_id":"-","upstream_host":"172.18.3.15:9092","x_forwarded_for":"-","requested_server_name":"-","bytes_received":"647","istio_policy_status":"-","bytes_sent":"1437"}
2020-09-03T05:55:20.110205Z	warning	envoy config	[bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:92] StreamAggregatedResources gRPC config stream closed: 13, 
{"requested_server_name":"-","bytes_received":"205","istio_policy_status":"-","bytes_sent":"1296","upstream_cluster":"outbound|9092||*.infra-kafka-headless.infra.svc.cluster.local","downstream_remote_address":"172.18.3.18:60710","authority":"-","path":"-","protocol":"-","upstream_service_time":"-","upstream_local_address":"172.18.3.18:60712","duration":"1920653","upstream_transport_failure_reason":"-","route_name":"-","downstream_local_address":"172.18.3.15:9092","user_agent":"-","response_code":"0","response_flags":"-","start_time":"2020-09-03T05:25:35.608Z","method":"-","request_id":"-","upstream_host":"172.18.3.15:9092","x_forwarded_for":"-"}
{"start_time":"2020-09-03T05:55:02.205Z","method":"-","request_id":"-","upstream_host":"172.18.3.15:9092","x_forwarded_for":"-","requested_server_name":"-","bytes_received":"30","istio_policy_status":"-","bytes_sent":"276","upstream_cluster":"outbound|9092||*.infra-kafka-headless.infra.svc.cluster.local","downstream_remote_address":"172.18.3.18:48602","authority":"-","path":"-","protocol":"-","upstream_service_time":"-","upstream_local_address":"172.18.3.18:48604","duration":"540218","upstream_transport_failure_reason":"-","route_name":"-","downstream_local_address":"172.18.3.15:9092","user_agent":"-","response_code":"0","response_flags":"-"}
2020-09-03T06:04:48.910597Z	info	Subchannel Connectivity change to CONNECTING
2020-09-03T06:04:48.910610Z	info	transport: loopyWriter.run returning. connection error: desc = "transport is closing"
2020-09-03T06:04:48.910876Z	info	pickfirstBalancer: HandleSubConnStateChange: 0xc0009529e0, {CONNECTING <nil>}
2020-09-03T06:04:48.910851Z	info	Subchannel picks a new address "istiod.istio-system.svc:15012" to connect
2020-09-03T06:04:48.911001Z	info	Channel Connectivity change to CONNECTING
2020-09-03T06:04:48.916925Z	info	Subchannel Connectivity change to READY
2020-09-03T06:04:48.916956Z	info	pickfirstBalancer: HandleSubConnStateChange: 0xc0009529e0, {READY <nil>}
2020-09-03T06:04:48.916963Z	info	Channel Connectivity change to READY
{"istio_policy_status":"-","bytes_sent":"1092","upstream_cluster":"outbound|9092||*.infra-kafka-headless.infra.svc.cluster.local","downstream_remote_address":"172.18.3.18:60304","authority":"-","path":"-","protocol":"-","upstream_service_time":"-","upstream_local_address":"172.18.3.18:60306","duration":"1680442","upstream_transport_failure_reason":"-","route_name":"-","downstream_local_address":"172.18.3.16:9092","user_agent":"-","response_code":"0","response_flags":"-","start_time":"2020-09-03T05:48:36.047Z","method":"-","request_id":"-","upstream_host":"172.18.3.16:9092","x_forwarded_for":"-","requested_server_name":"-","bytes_received":"170"}
{"protocol":"-","upstream_service_time":"-","upstream_local_address":"127.0.0.1:37044","duration":"1680239","upstream_transport_failure_reason":"-","route_name":"-","downstream_local_address":"172.18.3.18:9092","user_agent":"-","response_code":"0","response_flags":"-","start_time":"2020-09-03T05:49:26.536Z","method":"-","request_id":"-","upstream_host":"127.0.0.1:9092","x_forwarded_for":"-","requested_server_name":"outbound_.9092_._.*.infra-kafka-headless.infra.svc.cluster.local","bytes_received":"188","istio_policy_status":"-","bytes_sent":"1304","upstream_cluster":"inbound|9092|kafka|infra-kafka-headless.infra.svc.cluster.local","downstream_remote_address":"172.18.3.15:48138","authority":"-","path":"-"}
{"upstream_host":"127.0.0.1:9092","x_forwarded_for":"-","requested_server_name":"outbound_.9092_._.*.infra-kafka-headless.infra.svc.cluster.local","bytes_received":"434","istio_policy_status":"-","bytes_sent":"2846","upstream_cluster":"inbound|9092|kafka|infra-kafka-headless.infra.svc.cluster.local","downstream_remote_address":"172.18.3.15:35428","authority":"-","path":"-","protocol":"-","upstream_service_time":"-","upstream_local_address":"127.0.0.1:52566","duration":"3420317","upstream_transport_failure_reason":"-","route_name":"-","downstream_local_address":"172.18.3.18:9092","user_agent":"-","response_code":"0","response_flags":"-","start_time":"2020-09-03T05:26:14.743Z","method":"-","request_id":"-"}
2020-09-03T06:24:00.038089Z	warning	envoy config	[bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:92] StreamAggregatedResources gRPC config stream closed: 13,

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

I want to see only envoy log including it communication with istiod.

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

istio version : 1.6.8
kubernetes : 1.15.2 GKE

**How was Istio installed?**

Using Banzai istio operator

**Environment where bug was observed (cloud vendor, OS, etc)**

Google

**Comment by howardjohn** [comment]
Disable access logs if you do not want them: https://istio.io/latest/docs/tasks/observability/logs/access-log/

**Comment by satishmane** [comment]
@howardjohn 
Yes, finally did that. thanks
