### ISSUE TITLE
need a parameter of istioctl to specify imagePullSecret

### ISSUE THREAD

**Issue by nirvanatao** [istio/istio#27036]
I need to install istio from a private registry but didn't find a way to specify the image pull secrets

**Comment by howardjohn** [comment]
You can set `values.global.imagePullSecrets`

**Comment by esnible** [comment]
I don't think this information is in our docs.

@ostromart should there be a documentation item to add this?
@ostromart it would be great if `istioctl profile dump -o flags | grep -i secrets` would show this option.  I wonder if there is a way to make that happen?

**Comment by nirvanatao** [comment]
after looking into the chart and I found that "values.global.imagePullSecrets" can set imagePullSecret
