### ISSUE TITLE
TestMulticlusterReachability flakes

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#27033]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/26454/integ-multicluster-k8s-tests_istio/10038

cc @stevenctl @howardjohn maybe interested

**Comment by stevenctl** [comment]
I wonder if the refactoring within https://github.com/istio/istio/pull/25784 could have affected this.

**Comment by stevenctl** [comment]
Seems like this failure occurred before that merged.

**Comment by stevenctl** [comment]
I haven't seen this job flake at all in a while.
