### ISSUE TITLE
Expose grpc status code via attributes

### ISSUE THREAD

**Issue by rlguarino** [istio/istio#2704]
@douglas-reid , I'm not 100% sure what's required in the body of this ticket could you help me with the labels and administrative stuff?

We should support a way to plumb the grpc status code into attributes. 

Possible attributes:
1. Overwrite `response.attribute`
2. `response.grpc_status_code`
3. `response.status_code`

In some situations a grpc client will set the status code. In this case any metric that is generated using Mixer will not accurately reflect what a client sees.

**Comment by wora** [comment]
We need to decide whether `request` represents an HTTP request or a logical request. If we decide `request` represents a logical request, we could just put gRPC status code directly as `response.code`, and use `request.protocol` to differentiate HTTP vs gRPC.

Regardless how popular gRPC becomes, I don't think we should create a status code attribute for every popular protocol.

**Comment by douglas-reid** [comment]
i think using `response.code` and `request.protocol` is reasonable. we just need to make sure that this is documented and that the mixer client code is appropriately populating.

**Comment by qiwzhang** [comment]
response.code is "HTTP-status"; OK is 200.   grpc-status is "Status";  OK is 0
I believe gRPC has properly translated grpc-status to HTTP-status.  But some information may have lost.

**Comment by torbjornvatn** [comment]
What happened to this? I'm testing some grpc services in Istio now, and even though my services returns non-OK `codes.Error` grpc error codes they doesn't show up in the Prometheus metrics. There all the `istio_requests_total` entries for these services has response_code 200.

**Comment by douglas-reid** [comment]
@torbjornvatn new attributes were added at some point, including `response.grpc_status`. That should make it possible to edit the configuration for Mixer such that `istio_requests_total` either includes an additional field, or the `response_code` derivation is overridden when gRPC is used.  Does that help?

**Comment by torbjornvatn** [comment]
That was my first intuition to, but I'm having a hard time figuring out how to reconfigure the Mixer.
I tried editing the `istio-1.0.3/install/kubernetes/helm/istio/charts/mixer/templates/config.yaml` to include these attributes, but then it seemed like I didn't get any `istio_requests_total` metrics in Prometheus at all.
Isn't it a bit strange that the official helm chart doesn't expose pass these attributes? Since they're mentioned here: https://istio.io/docs/reference/config/policy-and-telemetry/attribute-vocabulary/

**Comment by torbjornvatn** [comment]
Aha, I found this: https://github.com/istio/istio/commit/07a6b84cd969e5b6158b6c60a23a8b8b641448f6
Seems like these attributes will be added in 1.1.0, but I guess I can just copy that `config.yaml` and get them now

**Comment by djazayeri** [comment]
@douglas-reid I'm interested in helping address this.
Do I understand correctly that now the attributes are available, and the remaining thing to do is to modify various config yaml files to use these?

**Comment by douglas-reid** [comment]
@djazayeri that's correct. I'll respond offline to your email, and we can update here when we've sorted it.

**Comment by djazayeri** [comment]
Stepping back, can we confirm the behavior we want to support here?

I propose:

(for logs)

* protocol => should be grpc for grpc traffic
* logicalResponseCode => new field (for all supported protocols, map response to the closes matching HTTP status)
    * e.g. `context.protocol == "grpc" ? grpcToHttp(response.grpc_status) : response.code`
* responseCode => do not change (literal http response code)
* grpcStatus => do not change

(for metrics)

* request_protocol => no change (this already supports grpc)
* response_code => no change (literal http response code)
* logical_response_code => new field (for all supported protocols, map response to the closes matching HTTP status)
    * e.g. `context.protocol == "grpc" ? grpcToHttp(response.grpc_status) : response.code`

**Comment by douglas-reid** [comment]
@djazayeri I'm not sure that we want a new label on the metrics. Do you mind writing up a small one-page doc on the options, which I see as follows:

1. Add `logical_response_code`
1. Update the expression for `response_code` to support `grpcToHttp` conversion in `grpc` cases

I just would like to see the pros/cons laid out there. Then we can discuss at the next P&T.
