### ISSUE TITLE
NATS server not working after upgrade from Istio 1.5 to 1.68

### ISSUE THREAD

**Issue by hniehus** [istio/istio#27041]
**Bug description**
Not sure if this a bug, or if we missed to configure something.
We have Istio running on AWS EKS. In the Mesh, we had a single node NATS server running (StatefulSet) with side car injected. NATS is exposed to AWS NLB IngressGateway and Clients were able to connect to NATS just fine. After upgrade of Istio to v1.6.8 the connection to the NATS however stopped working. After we rolled back to v1.5.10, NATS is connecting fine again.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
NATS Server is expected to behave the same way regardless of Istio version.

**Steps to reproduce the bug**
1. Install Istio 1.5.X
2. Deploy NATS (Statefulset + Gateway + VService)
3. Modify IngressGateway to allow TCP connections to NATS port
4. Telnet to NLB DNS on configured NATS port
5. Connection working fine :-)
6. Upgrade Istio to 1.6.X according Istio docs, with the same owerly file as in 1)
7. Telnet to NLB DNS on configured NATS port
8. Connection to NATS not working :-(

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**
```
istioctl version --remote
client version: 1.6.8
control plane version: 1.6.8
data plane version: 1.6.8 (20 proxies), 1.5.0 (1 proxies)
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-065dce", GitCommit:"065dcecfcd2a91bd68a17ee0b5e895088430bd05", GitTreeState:"clean", BuildDate:"2020-07-16T01:44:47Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

**How was Istio installed?**
Initial installed
`istioctl install -f ~/istio-system/eks-istio-system/istio-custom-install.yaml`
Upgrade to 1.6.8
`istioctl install --set revision=rev-168 -f ~/istio-system/eks-istio-system/istio-custom-install.yaml`

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS EKS, Kubernetes 1.15
NATS 2.1.7

**Istio and NATS config files**
[Istio-NATS bug.zip](https://github.com/istio/istio/files/5169020/Istio-NATS.bug.zip)

**Comment by howardjohn** [comment]
I can reproduce. The issue is the headless service doesn't end up in EDS.

```diff
diff --git a/pilot/pkg/serviceregistry/kube/controller/endpointcontroller.go b/pilot/pkg/serviceregistry/kube/controller/endpointcontroller.go
index 06278b9764..98d169f25e 100644
--- a/pilot/pkg/serviceregistry/kube/controller/endpointcontroller.go
+++ b/pilot/pkg/serviceregistry/kube/controller/endpointcontroller.go
@@ -75,7 +75,6 @@ func processEndpointEvent(c *Controller, epc kubeEndpointsController, name strin
                                        }: {}},
                                        Reason: []model.TriggerReason{model.EndpointUpdate},
                                })
-                               return nil
                        }
                }
        }
```

confirmed fixes this problem.

@hzxuzhonghu I remember fixing this already.. any idea what happened?

**Comment by hniehus** [comment]
Hi John,

Thanks for looking into this issue. Any ETA for the fix?

Thanks,
Harald

**Comment by hzxuzhonghu** [comment]
#26636 This is the fix, not sure if it is related. @howardjohn @hniehus Can you paste the xds configration of ingress gateway?

**Comment by howardjohn** [comment]
there are no endpoints for the cluster in the gateway pod

**Comment by hzxuzhonghu** [comment]
We donot need endpoints for headless svc cluster, it is original dest?

**Comment by hzxuzhonghu** [comment]
Is this also related to mtls?

**Comment by howardjohn** [comment]
Irs a gateway, it's not original dst

**Comment by howardjohn** [comment]
we will send eds to the gateway
