### ISSUE TITLE
Installation fails - incorrect check for whether istio-system namespace already exists 

### ISSUE THREAD

**Issue by jbrook** [istio/istio#27063]
Encountered with Istio 1.6.8.

Scenario:

1. OPA gatekeeper admission controller requires certain labels on every namespace.
2. Manually create istio-system namespace and add required labels.
3. Run `istioctl install`.
4. [createNamespace](https://github.com/istio/istio/blob/f23bb221697effd3506bc8f46e8ffa5e125504f4/operator/cmd/mesh/shared.go#L253) function returns an error because instead of being an "isAlreadyExists" error it is an admission control related error.

The namespace does already exist and Istio should simply be installed into it. Instead there is a misleading error message. For example:
```
Error: failed to apply manifests: failed to create namespace istio-system: admission webhook
"validation.gatekeeper.sh" denied the request: [denied by ns-must-have-labels] All namespaces
must have a `xxxx` and `yyyy` annotation
```

**Comment by howardjohn** [comment]
@adiprerepa interested in picking this up?

**Comment by adiprerepa** [comment]
@howardjohn sure

**Comment by adiprerepa** [comment]
yay github projects!

**Comment by luckoseabraham** [comment]
hey @howardjohn / @adiprerepa  - Would you guys be open to a PR to check if the namespace is already present before trying to create one ?
