### ISSUE TITLE
Support a way for Mixer to mutate a request's headers in flight

### ISSUE THREAD

**Issue by geeknoid** [istio/istio#2706]
@rlguarino commented on [Wed Sep 20 2017](https://github.com/istio/old_mixer_repo/issues/1333)

Mixer adapters should be capable of producing attributes which are sent back to the proxy and eventually propagated to the Upstream [defined here](https://envoyproxy.github.io/envoy/intro/arch_overview/terminology.html).

---

@rlguarino commented on [Thu Sep 21 2017](https://github.com/istio/old_mixer_repo/issues/1333#issuecomment-331196120)

@ZackButcher  I think I remember someone saying that a list of all attributes is sent back to the Envoy filter so it can make caching decisions. Was that just in theory or is that a reality at the moment?

---

@ZackButcher commented on [Thu Sep 21 2017](https://github.com/istio/old_mixer_repo/issues/1333#issuecomment-331200783)

[That does happen today](https://github.com/istio/api/blob/master/mixer/v1/check.proto#L105), though attribute values are not sent back.

The work for Mixer to mutate request headers is:
- In Mixer, formalize the concept of "return attributes". Today only `attributes` adapters can produce attributes, and they reside only in Mixer. We need a way for adapters to talk about attributes they inject into the request context, and implementation work to actually support that
- Update the [Mixer API](https://github.com/istio/api/blob/master/mixer/v1/check.proto#L58) to support returning attributes on `Check` responses.
- In [Istio's Envoy HTTP filter](https://github.com/istio/proxy/blob/master/src/envoy/mixer/http_filter.cc) we need support for reading attributes returned by `Check`s and attaching them to the request's header. There's likely some work here in mapping attribute names (`foo.bar.baz`) to HTTP headers (`X-foo-bar-baz` or similar) on top of just pushing the values into the header map.

---

@kyessenov commented on [Thu Sep 28 2017](https://github.com/istio/old_mixer_repo/issues/1333#issuecomment-333015967)

This belongs to the general area of "scripting proxy actions". Changing the header is one such action, and can be used to shape the traffic.

---

@rlguarino commented on [Fri Jan 19 2018](https://github.com/istio/old_mixer_repo/issues/1333#issuecomment-359021642)

@geeknoid  I don't think that this made it into the 0.3 release. Should this Issue be moved into the istio/istio repository?

**Comment by qiwzhang** [comment]
Proxy did hot hookup yet.  Here is the issue https://github.com/istio/proxy/issues/926 to track it.

**Comment by odino** [comment]
Hi everyone -- silly question: we would want to take a cookie and rewrite it as `Authorization` header, is this currently possible?

**Comment by kyessenov** [comment]
@odino No, but you may use native envoy ways, with custom filters or lua. We want to have a generic ability to control proxies from mixer, which is what this issue is about.

**Comment by BrendanBall** [comment]
We would need this for custom authentication workflow.

**Comment by ashwinphatak** [comment]
Would we be violating some design goals or scope of Mixer if we extended this concept to responses as well? 

For example, allowing an adapter to return 'response attributes', which get mapped to custom HTTP headers?

**Comment by mefarazath** [comment]
@geeknoid I have a similar requirement to inject a custom request header during the proxy communication. After reading through various forums it seems the best approach to do that would be to write a mixer plugin (instead of writing an envoy filter and building a mixer image). 

Even if we go along the path would we be able to inject a custom header into a request in the correct istio version?

**Comment by geeknoid** [comment]
At the moment, this feature is not supported. I'm guessing this might show up in the 1.2 timeframe which would be early in 2019.

**Comment by qiwzhang** [comment]
It has been implemented.  It is fully functional.  Mixer can return this field in Check response. 
https://github.com/istio/api/blob/master/mixer/v1/check.proto#L84

It allows mixer to add any http headers to the requests to the upstream. or to the response.

**Comment by geeknoid** [comment]
It's not supported by Mixer yet, so the fact Envoy has the needed bits is
not sufficient :-)

**Comment by itaysk** [comment]
Hi @geeknoid, at my company we are working on an integration with Istio that requires this feature and would love to pick this issue up and contribute this feature.

**Comment by brian-avery** [comment]
It might be important to be able to tell whether a header was generated internally or externally to the cluster. Especially when thinking about this in terms of authorization/authentication.

**Comment by kyessenov** [comment]
Our latest proposal lets the mesh operator control the header name and the producer for the header value. For example, if an external adapter `foo` produces a bunch values, then the operator uses the following config:
```yaml
request_header_operations:
- name: x-special-header
   values: ["foo.some_value"]
```

Does that satisfy the requirement on provenance of the header?

**Comment by brian-avery** [comment]
Yeah. I think so. The use case that I was thinking of is as follows:

Lets say someone creates an adapter that supports Oauth. Adapter takes a token and gets a set of scopes for the token and writes them to a header. Have a rule protecting access to certain services saying that x scope is required.  If the scope is provided, let the request continue, if it's not, deny it as unauthorized. In this case, it would be useful to be able to verify that that the scope header is generated internally to the cluster rather than coming from some external source. 

But if I understand your comment above correctly, the header foo.some_value would have to have come from internally to the cluster. 

Thanks,
Brian

**Comment by kyessenov** [comment]
Route directive proposal has been implemented. It satisfies the basic use-case of mutating headers with mixer adapters.

@brian-avery 

In the current model, the header value comes from the adapter. The rules define the operations using those values, e.g. removing or setting a header. The rule operations are only applied if the check succeeds. Please take a look at the example here https://github.com/istio/istio/wiki/Route-directive-adapter-development-guide for more hands-on details.

**Comment by kyessenov** [comment]
The feature to mutate request headers with external adapters has been implemented.
You can operate on headers in case of success (using rule header operations) and in the case of error (using error details in RPC status).
Please open a new focused issue regarding header sanitizing if there is more work to do.
