### ISSUE TITLE
Help: Is it possible to inject faults in Redis with Envoy Redis Proxy?

### ISSUE THREAD

**Issue by AjithPanneerselvam** [istio/istio#27064]
I see that Envoy Redis Proxy allows us to inject faults in Redis - https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/redis_proxy_filter#fault-injection

But, is the same enabled in Istio? I couldn't find any information for inducing faults with Envoy filters in Istio docs - https://istio.io/latest/docs/reference/config/networking/envoy-filter/ So, please educate me if I can inject faults in Redis with Redis proxy or by any other means.

**Comment by howardjohn** [comment]
We do not support this. You may be able to configure it with the break glass https://istio.io/docs/reference/config/networking/envoy-filter/ API, but its not officially supported.
