### ISSUE TITLE
dump_kubnernetes.sh has error dumping secrets

### ISSUE THREAD

**Issue by ericvn** [istio/istio#27076]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

dump_kubnernetes.sh has error dumping secrets
```
./dump_kubernetes.sh 
...
Retrieving Kubernetes resource configurations
error: a resource cannot be retrieved by name across all namespaces
Retrieving Istio resource configurations
...
```

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[x] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

No error

**Steps to reproduce the bug**

run ./dump_kubernetes.sh 

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

1.7.0

**How was Istio installed?**

istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**

kind

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by ericvn** [comment]
This seems to be related to:
```
  kubectl get --all-namespaces \
      secrets "${FULLSECRETS}" >> "${RESOURCES_FILE}"
```

**Comment by fpesce** [comment]
Do we really want to dump secrets anyway? Isn't dump_kubernetes.sh supposed to be sued to share the info in a gihub issue or with people external to user's company.
We might want ot remove the secret dump altogether

**Comment by shamsher31** [comment]
This should be resolved by the new `bug-report` tool at least from 1.8 and above.  https://github.com/istio/istio/pull/29185

**Comment by howardjohn** [comment]
https://github.com/istio/release-builder/pull/566

**Comment by ericvn** [comment]
Closing this as `dump_kubernetes` was removed from the English doc in 1.8, replaced by `bug-report`, and 1.7 will be EOL so not going to be fixed there.
