### ISSUE TITLE
pilot cert rotation documentation outdated

### ISSUE THREAD

**Issue by caitong93** [istio/istio#27087]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

When envoy hot restart, its memory usage doubles. If memory usage of istio-proxy > 50% memory limit, hot restart causes OOM. Even worse, certificate refreshing causes all sidecars hot restarted. Can we check memory usage and limit before hot restart ? For example, not perform hot restart if usage/limit > threshhold (default to 50%) , this may prevent many similar OOMs.

cc @howardjohn 

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[X] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

Hot restarting won't cause istio-proxy OOM

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

istio 1.3

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
We don't hot restart since istio 1.5

**Comment by caitong93** [comment]
> We don't hot restart since istio 1.5

Didn't find that in release notes https://istio.io/latest/news/releases/1.5.x/announcing-1.5/change-notes/ 

And the lastest doc seems need to be updated https://istio.io/latest/docs/ops/configuration/security/root-transition/ , it still says "Note that the Envoy instances will be hot restarted to reload the new root certificates"

**Comment by howardjohn** [comment]
Thanks, we will need to update the doc

**Comment by caitong93** [comment]
found hot restart to reload certs logic was removed in [this pr](d0541bc68daab406e7e353b527bf4086a9ccf274)

**Comment by myidpt** [comment]
Istio 1.5 is out of the maintenance window. Fixing the documentation doesn't benefit much. Closing this issue.
