### ISSUE TITLE
istio 1.6.8 - redis master / slave connection reconnect when peerauth is changed from permissive or strict or vice versa

### ISSUE THREAD

**Issue by satishmane** [istio/istio#27093]
**Bug description**

redis ha cluster forms successfully and my applications are able to connect in both permissive and mtls mode.

But why does Redis master / slave connection drops and reconnects when peerauthentications is changed from permissive or strict or vice versa and autoMtls is true always.

I observed same behavior for zookeeper too

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

When automtls is true and changing peerauthentication from mtls to permissive or vice versa should not disconnect master/slave and reconnect.

**Steps to reproduce the bug**

Deploy redis ha cluster. Change peerauthentication from permissive to mtls or vice versa. 

**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

**How was Istio installed?**
istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**
Google

Additional info - logs
Master log
========
1:M 06 Sep 2020 09:28:05.802 # Connection with replica 172.19.177.92:6379 lost.
1:M 06 Sep 2020 09:28:05.802 # Connection with replica 172.19.222.215:6379 lost.
1:M 06 Sep 2020 09:28:06.185 * Replica 172.19.177.92:6379 asks for synchronization
1:M 06 Sep 2020 09:28:06.185 * Partial resynchronization request from 172.19.177.92:6379 accepted. Sending 0 bytes of backlog starting from offset 498080.
1:M 06 Sep 2020 09:28:06.345 * Replica 172.19.222.215:6379 asks for synchronization
1:M 06 Sep 2020 09:28:06.345 * Partial resynchronization request from 172.19.222.215:6379 accepted. Sending 146 bytes of backlog starting from offset 498080.

Slave1 log
========

1:S 06 Sep 2020 09:28:05.887 # Connection with master lost.
1:S 06 Sep 2020 09:28:05.887 * Caching the disconnected master state.
1:S 06 Sep 2020 09:28:06.343 * Connecting to MASTER 172.19.53.15:6379
1:S 06 Sep 2020 09:28:06.343 * MASTER <-> REPLICA sync started
1:S 06 Sep 2020 09:28:06.343 * Non blocking connect for SYNC fired the event.
1:S 06 Sep 2020 09:28:06.344 * Master replied to PING, replication can continue...
1:S 06 Sep 2020 09:28:06.345 * Trying a partial resynchronization (request aea443649ac2ab53754c1b5c0f7185e054173914:498080).
1:S 06 Sep 2020 09:28:06.346 * Successful partial resynchronization with master.
1:S 06 Sep 2020 09:28:06.346 * MASTER <-> REPLICA sync: Master accepted a Partial Resynchronization.

Slave2 log
========

1:S 06 Sep 2020 09:28:05.876 # Connection with master lost.
1:S 06 Sep 2020 09:28:05.876 * Caching the disconnected master state.
1:S 06 Sep 2020 09:28:06.182 * Connecting to MASTER 172.19.53.15:6379
1:S 06 Sep 2020 09:28:06.182 * MASTER <-> REPLICA sync started
1:S 06 Sep 2020 09:28:06.182 * Non blocking connect for SYNC fired the event.
1:S 06 Sep 2020 09:28:06.184 * Master replied to PING, replication can continue...
1:S 06 Sep 2020 09:28:06.185 * Trying a partial resynchronization (request aea443649ac2ab53754c1b5c0f7185e054173914:498080).
1:S 06 Sep 2020 09:28:06.185 * Successful partial resynchronization with master.
1:S 06 Sep 2020 09:28:06.185 * MASTER <-> REPLICA sync: Master accepted a Partial Resynchronization.

**Comment by hzxuzhonghu** [comment]
#24319

**Comment by howardjohn** [comment]
Changing Istio configuration will result in draining, see https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/operations/draining. This is working as intended.
