### ISSUE TITLE
Istio-Config in kiali is empty

### ISSUE THREAD

**Issue by michaelkoro** [istio/istio#27109]
**Bug description**
While using kiali, when trying to list all istio configs in the cluster, a pop-up message reads - "Could not fetch Istio objects list: Gateway Time-out", and the "istio config" tab is empty.
kiali logs - 
`2020-09-07T11:50:49.854355040Z W0907 11:50:49.852819       1 istio_validations.go:620] GetClusterRbacConfigs validation failed due to insufficient permissions (probably Kiali doesn't have cluster permissions). Error: clusterrbacconfigs.rbac.istio.io is forbidden: User "system:serviceaccount:istio-system:kiali-service-account" cannot list resource "clusterrbacconfigs" in API group "rbac.istio.io" at the cluster scope
`
It is Important to note that this issue only started happening when we upgraded from istio 1.6.3 to 1.7.0
**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
kiali should have proper permissions when installed, to access istio-based resources.

**Steps to reproduce the bug**
using istioctl 1.7:
`
istioctl manifest install --set addonComponents.grafana.enabled=true --set addonComponents.kiali.enabled=true --set addonComponents.prometheus.enabled=true --set addonComponents.tracing.enabled=true --set values.gateways.istio-ingressgateway.type=NodePort --set values.kiali.createDemoSecret=true --set values.global.proxy.holdApplicationUntilProxyStarts=true
`
**Version (include the output of `istioctl version --remote` and `kubectl version` and `helm version` if you used Helm)**

Istio:

`
client version: 1.7.0
control plane version: 1.7.0
data plane version: 1.7.0 (9 proxies)
`

Kubernetes:

`
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
`

**How was Istio installed?**
Using the Istioctl binary
Also, kiali was installed as an addOnComponent of the stack.

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS EKS

**Comment by dntosas** [comment]
Kiali installation via `istioctl` is deprecated in `1.7` and is meant to be completely removed in `1.8` --> https://istio.io/latest/blog/2020/addon-rework/#timeline

We got same problem and decided to move Kiali deployment to separate process. We can take some ideas from here also  --> https://kiali.io/documentation/latest/installation-guide/#_installation

**Comment by howardjohn** [comment]
Despite it being deprecated it should ideally work until it's removed so would be good to get this fixed

**Comment by jmazzitelli** [comment]
> clusterrbacconfigs.rbac.istio.io is forbidden: User "system:serviceaccount:istio-system:kiali-service-account" cannot list resource "clusterrbacconfigs" in API group "rbac.istio.io" at the cluster scope

Sounds like the internal installation mechanism used by istioctl 1.7 is not creating the proper clusterrole.

Make sure istioctl creates [a clusterrole that looks like this](https://github.com/kiali/helm-charts/blob/master/kiali-server/templates/role.yaml
), see specifically [this](https://github.com/kiali/helm-charts/blob/v1.23.0/kiali-server/templates/role.yaml#L50-L63).

**Comment by jmazzitelli** [comment]
And, yes, it looks like istioctl internal helm chart for kiali is missing that permission. See:

https://github.com/istio/istio/blob/1.7.0/manifests/charts/istio-telemetry/kiali/templates/clusterrole.yaml

Specifically, it is missing apiGroup `rbac.istio.io` [here in the `kiali` clusterrole](https://github.com/istio/istio/blob/1.7.0/manifests/charts/istio-telemetry/kiali/templates/clusterrole.yaml#L47-L51) and missing it [here in the `kiali-viewer` clusterrole](https://github.com/istio/istio/blob/1.7.0/manifests/charts/istio-telemetry/kiali/templates/clusterrole.yaml#L113-L117).

Compare to the [correct clusterrole as shown here](https://github.com/kiali/helm-charts/blob/v1.23.0/kiali-server/templates/role.yaml#L50-L55).

**Comment by dntosas** [comment]
preparing a PR for this ^^

**Comment by JimmyCYJ** [comment]
@dntosas is this issue fixed? We are preparing 1.7.1 release note and there is concern regarding this fix here https://github.com/istio/istio.io/pull/8111#discussion_r485908628

**Comment by dntosas** [comment]
@JimmyCYJ yeap this issue seems to be fixed. Also made some manual tests with a fresh install and all worked as expected. If you think the release-note is not clear enough, we can change it accordingly ^^

**Comment by dntosas** [comment]
shall we close this @michaelkoro ?
