### ISSUE TITLE
fails to dryrun under multi-cluster

### ISSUE THREAD

**Issue by irisdingbj** [istio/istio#27113]
```
Not ready to switch validation to fail-closed: dummy invalid rejected for the wrong reason: gateways.networking.istio.io is forbidden: User "system:serviceaccount:istio-system:istio-reader-service-account" cannot create resource "gateways" in API group "networking.istio.io" in the namespace "istio-system"
```

**Comment by howardjohn** [comment]
I am confused, isn't the central istiod running with the full permission for the config cluster? I don't see how it would work otherwise, it would be missing tons of permission. The validation webhook is only in the config cluster?

**Comment by irisdingbj** [comment]
The architecture is like this:  one external control plane cluster with its KUBECONFIG point to the config cluster,   and  more than 1 remote cluster who gets config from the config cluster. 

This is used in remote cluster as we need create remote secret in the config cluster. So `istio-reader-service-accout`

**Comment by howardjohn** [comment]
why is there a validating webhook in the remote cluster? It doesn't have any configs.

**Comment by irisdingbj** [comment]
in remote cluster, we will have two webhook configurations and they will be used for workloads running within the cluster.

**Comment by howardjohn** [comment]
Why though? The validation webhook will validate configuration. We don't have config, so why would we have the webhook to validate the config? We don't even install the CRDs?

**Comment by irisdingbj** [comment]
make sense. we do not need crds and validating webhook configurations in remote cluster.  Now both of them are part of `base` components.  should we spilt them from base into a separate component eg `config`?  And any others should be spilt from `base`? 

 currently, we are instaling l base + istiodRemote in remote cluster and config cluster.  so we really need a way to split the unneeded resources.

**Comment by howardjohn** [comment]
I think you can turn off the CRDs and webhook. What do we need from base
anyways? just the service and endpoints?

**Comment by irisdingbj** [comment]
I think we need sa, role , clusterrole , bindings for `istio-reader`, services, endpoints.  It is easy to exclude others via existing flags.  For crds what is the better and easy way to exclude them?

**Comment by irisdingbj** [comment]
we already use copy and flag mix, right?  so this will not make the situation worse :)

**Comment by howardjohn** [comment]
Where is the mix?

**Comment by irisdingbj** [comment]
I mean we now have mutliple flags to control our install behaviour already, like: `enableCRDTemplates`, `configValidation`
and we have multiple charts at the same time. This is already a mix, right?
