### ISSUE TITLE
istio-proxy OOM with increased memory in 1.6.7

### ISSUE THREAD

**Issue by AEGQ** [istio/istio#27111]
**Bug description**
![image](https://user-images.githubusercontent.com/16302289/92404381-01f4cc80-f166-11ea-9f71-485d42d6ceaa.png)
![image](https://user-images.githubusercontent.com/16302289/92580886-89a31e00-f2c1-11ea-9f57-962810b993ff.png)
![image](https://user-images.githubusercontent.com/16302289/92581095-cbcc5f80-f2c1-11ea-8bec-3896f7fb0cdb.png)

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[X] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Memory doesn't grow linearly

**Steps to reproduce the bug**

Only one service in the cluster has this problem. This service accesses redis .

**Version**
istio: 1.6.7
k8s:  v1.16.13-eks-2ba888

**How was Istio installed?**

istioctl install 

**Environment where bug was observed (cloud vendor, OS, etc)**

AWS EKS

{
 "allocated": "361312704",
 "heap_size": "377634816",
 "pageheap_unmapped": "0",
 "pageheap_free": "827392",
 "total_thread_cache": "7356560",
 "total_physical_bytes": "382353408"
}

[envoy.prof.0005.heap.gz](https://github.com/istio/istio/files/5184005/envoy.prof.0005.heap.gz)

**Comment by howardjohn** [comment]
How many clusters does the proxy have? you can see with `istioctl pc cluster`. Also maybe take a look at the istiod logs and see how many cds pushes we send to this proxy

**Comment by AEGQ** [comment]
**istioctl pc cluster**
![image](https://user-images.githubusercontent.com/16302289/92425437-d4397300-f1b9-11ea-8eb8-820d55a0de68.png)

**istiod logs**
![image](https://user-images.githubusercontent.com/16302289/92425809-e23bc380-f1ba-11ea-9ba9-0c7816452f32.png)

@howardjohn  :)

**Comment by howardjohn** [comment]
Ok so its very small. Looks like a lot of memory spent in the cluster.Validate and/or config dump code though which is odd...

@ramaraochavali @lambdai will be able to help better than I can

**Comment by AEGQ** [comment]
duplicated https://github.com/istio/istio/issues/24720
