### ISSUE TITLE
Ensure any EDSCacheUpdate have a corresponding push call

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#27114]
We need to ensure any EDSCacheUpdate have a corresponding push call *with the correct ConfigKey for the endpoint set*, or the EDS cache invalidation will not work.

**Comment by hzxuzhonghu** [comment]
Can you describe more about the issue now?

**Comment by howardjohn** [comment]
Cache invalidation and ProxyNeedsPush are based on the Push Requests. So we need to make sure that we create PushRequests even if we do only a cache update. I don't know if it's a bug, just something we should validate

**Comment by bianpengyuan** [comment]
@howardjohn Ping on this, seems like a blocking issue for 1.8. Please prioritize this issue or push to 1.9 if you think otherwise, thanks!

**Comment by howardjohn** [comment]
I inspected the code, looks safe.
