### ISSUE TITLE
istioctl in daily build tgz references images that do not exist

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#2713]
istioctl for dailies should work

https://storage.googleapis.com/istio-prerelease/daily-build/0.5.0-pre20180118-03-15-00/TESTONLY-istio-0.5.0-pre20180118-03-15-00-osx.tar.gz

```
istio-0.5.0-pre20180118-03-15-00 $ bin/istioctl kube-inject -f samples/bookinfo/kube/bookinfo.yaml |grep image:|grep proxy|head -2
        image: docker.io/istio/proxy_debug:0.5.0-pre20180118-03-15-00
        image: docker.io/istio/proxy_init:0.5.0-pre20180118-03-15-00
```

should be gcr.io
(same issue whether using the TESTONLY- or not - which the more I think about it the less I understand why we have 2 - we should only have 1 set of tgz, the one that 'works' (ie references existing artifacts)

cc @hklai  - can we somehow setup something to test the artifacts we produce - if we did we'd realize we get
spec.initContainers{istio-init} Normal          BackOff                 Back-off pulling image "docker.io/istio/proxy_init:0.5.0-pre20180118-03-15-00"

**Comment by ldemailly** [comment]
I think we should add the HUB to
https://github.com/istio/istio/blob/master/bin/get_workspace_status
and 
https://github.com/istio/istio/blob/master/pilot/tools/version/version.go

instead of just the hardcoded default hub to be docker.io for all releases

**Comment by hklai** [comment]
Yes I think we test the artifacts we produce. Probably the tests cover only the images.
If so, we should add some tests for istioctl as well. (We had a plan to test istioctl version matches what we expect as well.)

**Comment by mattdelco** [comment]
Should be fixed by https://github.com/istio/istio/pull/2752 .
