### ISSUE TITLE
Simplify dual control plane upgrade

### ISSUE THREAD

**Issue by ostromart** [istio/istio#27138]
Outstanding items include:
- managing multiple binary/chart versions during upgrade. Need to at least test for binary version comaptibility. [P0]
- detecting which workloads and gw's are attached to which version on the control plane. [P1]
- ensure the rollover progresses smoothly and as expected (expose state to users). [P1]
- documentation. [P0]
- handling large version jumps. [P0]
- consistency with operator. [P0]
- gradual workload rollover (1/10/100%). [P1]
- interactive tool to handle entire upgrade. [P?]

**Comment by bianpengyuan** [comment]
@ostromart @richardwxn How much work is left for this issue? There is no PR linked here, so I guess there is not much progress yet? Looks like a big effort and it is hard to meet 1.8 cut date. I am going to push this to 1.9. Please update this back to 1.8 if you think this is blocking, thanks!
