### ISSUE TITLE
Properly maintain the release operator image

### ISSUE THREAD

**Issue by sdake** [istio/istio#27139]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
There is a helm chart for generating operators. There is also a hand-built operator. Remove the hand-built version, and generate from the helm chart.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[X] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by sdake** [comment]
https://github.com/istio/istio/pull/27112

**Comment by sdake** [comment]
https://github.com/istio/istio/pull/22982

**Comment by sdake** [comment]
https://github.com/istio/istio/pull/27112

**Comment by howardjohn** [comment]
Fixed by https://github.com/istio/istio/pull/27112
