### ISSUE TITLE
Support info tool

### ISSUE THREAD

**Issue by ostromart** [istio/istio#27146]
Tool for capturing enough information for support to be able to solve most problems without extra roundtrip requesting config and state information. Design doc [here](https://docs.google.com/document/d/1mpg90Ftz1df7jycnCHrA5RZ9Wru1ZYJ707AmFcAHc1E/)

**Comment by ostromart** [comment]
https://github.com/istio/istio/pull/26045

**Comment by ostromart** [comment]
https://github.com/istio/istio/pull/27025

**Comment by ostromart** [comment]
https://github.com/istio/istio/pull/26976

**Comment by bianpengyuan** [comment]
The bug report tool is mostly done right? @ostromart Shall we close this issue?

**Comment by bianpengyuan** [comment]
Lower to P1, as the things left is only testing now.
