### ISSUE TITLE
Helm v3 installation beta graduation

### ISSUE THREAD

**Issue by ostromart** [istio/istio#27147]
Outstanding tasks include documentation and testing.

**Comment by nrjpoddar** [comment]
Related PRs and changes:

1. https://github.com/istio/istio/pull/28385
1. https://github.com/istio/test-infra/pull/3021
1. https://github.com/istio/istio.io/pull/8283
1. https://github.com/istio/istio.io/pull/8350
1. https://github.com/istio/istio.io/pull/8373
