### ISSUE TITLE
multicluster topology includes external-istiod

### ISSUE THREAD

**Issue by stevenctl** [istio/istio#27155]
The current effort is to have a separate job for external istiod. 

Related PRs:
#27570 
#28181 

---

We already have a 5 cluster topology to cover combos of multi-network, multi-primary, primary-remote. We should also cover the external istiod model in our coverage as we convert tests (ex #25923)

From my conversation with @irisdingbj:

1. External Istiod (uses cluster 2 for config)
2. Remote/Config (uses cluster 1 for discovery)
3. Remote (uses cluster 2 for config, cluster 1 for discovery)
4. Primary (uses cluster-local istiod for discovery, uses config from same cluster)
5. Primary (uses cluster-local istiod for discovery, uses config from same cluster)
6. Remote (uses cluster 5 for config and discovery)
1,2,3 on a network, 4,5,6 on another network
That covers combos of multi-network/multi-primary/primary-remote/external-config/external-remote

We’d deploy workloads to everything but cluster 1
Config would be need to be pushed to clusters 2, 4, and 5.

We have `controlPlaneTopology` to decide where a remote gets xds from
We have `configTopology` to decide where to read istio configs from
We have `networkTopology` for networking

I’m not 100% that’s the best “golden” topology, we can iterate on that. But in general, if we can’t set this up via flags we need to change the framework to support it.

---

Code changes required
- [ ] When listing clusters, don't include "non-deployment" clusters/external istiod clusters. ([code](https://github.com/istio/istio/blob/1bbb39963f780740bb5a99eb5c33fb16350ed919/pkg/test/framework/components/environment/kube/kube.go#L78)) 
  - So that `ctx.Clusters()` can be used to spin up workloads on each cluster. Optionally, make a separate method for workload-clusters and make sure it's used in tests. 
- [ ] Setup a 5th cluster as part of "test-network-1" ([code](https://github.com/istio/istio/blob/1bbb39963f780740bb5a99eb5c33fb16350ed919/prow/lib.sh#L179))
  - [ ] Bonus: cleanup this code so we can just input a number of clusters instead of having several variables for each cluster
- [ ] Set topology flags to produce the topology above when prow topology is `MULTICLUSTER` ([code](https://github.com/istio/istio/blob/1bbb39963f780740bb5a99eb5c33fb16350ed919/prow/integ-suite-kind.sh#L135-L136))

cc @nmittler

**Comment by stevenctl** [comment]
If we don't do this, we will have to leave the existing multicluster job around to cover centralistiod until we can get that covered for all tests.

**Comment by nmittler** [comment]
I'm actually not sure we want to do this. Our golden 5-cluster topology is used to generate traffic from all clusters and tests that all combinations of control plane and network topologies behave normally from the perspective of each cluster in the mesh. If we make this also support the "external control plane" model, we'll lose a lot of test coverage due to the fact that in the "external" mode we would only run user workloads in remote clusters.

I think a better approach might be to make a one-off prow job for "external control plane" that runs through some subset of the pilot tests as a sanity check. It could even use fewer clusters if needed (3? ... 1 control plane and 2 remotes running user workloads). All we're testing here is having the control plane go somewhere else for config, it doesn't inherently test reachability, etc., so I think we shouldn't need more than this.

WRT the istiod-less remote clusters, we should just start using those by default and deprecate the old-style remote cluster altogether. That means the only part of "external control plane" that would have somewhat limited testing would be "config clusters", which I think is pretty reasonable.

@stevenctl @irisdingbj  WDYT?

**Comment by stevenctl** [comment]
We'd have a few classes of clusters:
A. Primary, workloads get XDS from the in-cluster istiod, Istio config is read from this cluster.
B. Config, workloads read XDS from an istiod outside the cluster, an external istiod reads Istio config from this cluster.
C. Remote, workloads read XDS from an istiod outside the cluster, that istiod is not getting Istio config from this cluster
D. External istiod, the control plane runs in this cluster, Istio config is read from another cluster. 

I don't think we'd lose coverage if we have something like:
```
    Network 1            Network 2

     A <- C              B->D<-C
        A
```

Network 1 has a primary, a remote and another independent primary. 

Network 2 has an external istiod, a config cluster that gets xds from the external istiod, and a remote cluster that reads xds from the external istiod.

**Comment by nmittler** [comment]
Wait, isn't that 6 clusters? You have 2 A's and C in network 1, and B, D, and C in network 2. I suspect we don't want to add more clusters at this point, given the impact on test times.

Also, I would just get rid of our classic remote altogether. We're alpha today and the type of remote isn't user facing, really.

**Comment by stevenctl** [comment]
I figured we'd need to add one to fit it all, but if we get rid of the "classic" that's great.

**Comment by irisdingbj** [comment]
for external istiod scenario, we needs only 3 clusters,  external control plane + config + remote. 
I am totally fine to combine them into our current multi-cluster topology that we will have six cluster as described by @stevenctl in the description.   We can set up these 6 cluster in one single main_test.go and kick off all the testing. 

But I am  not pretty sure whether all current pilot tests can be run smoothly or we need some tweak to remove some of them under external istiod mode.. If this is the case, I will prefer a new separate prow job for it and move parts of pilot test under this mode.

So would be glad to get your confirmation for this open concerns and we can decide whether to combine or to create a new prow job.

@nmittler @stevenctl ^^^

**Comment by stevenctl** [comment]
After our conversation today, I think it's best these live in separate jobs.
