### ISSUE TITLE
connection reset executing 

### ISSUE THREAD

**Issue by qijianbo010** [istio/istio#27169]
Service requests without sidecar injection during service grid access will cause connection reset for services injected with sidecar. Istio version is 1.4.6. Is this normal? What needs to be done. (is it OK after all sidecar is injected)

**Comment by howardjohn** [comment]
Are you configuring strict mTLS? if so, this is expected, as the clients will not send mtls

**Comment by qijianbo010** [comment]
kind: MeshPolicy
spec:
  targets: ~
  peers:
    - mtls:
        mode: PERMISSIVE

**Comment by qijianbo010** [comment]
is not configuring mTLS

**Comment by qijianbo010** [comment]
@howardjohn Any other suggestions?

**Comment by myidpt** [comment]
Can you be more explicit by "cause connection reset"? The connection can't be established at all from non-Istio services to Istio services, or some other issues?

**Comment by JimmyCYJ** [comment]
Could you please test with Istio 1.5-1.7? 1.4 is EOL.

**Comment by howardjohn** [comment]
We do not have enough info to debug this further and this is an EOL version. Please open a new issue with more details if you encounter this on recent versions. Thanks!
