### ISSUE TITLE
Istio sidecar is not working for multi-master setup

### ISSUE THREAD

**Issue by bond007007** [istio/istio#27168]
Hello all,
I need help!
K8s version : 1.18.8
Docker : 19.03.9
Calico : 3.16.0
Istio: 1.7

I have created a multi-master and multi-worker node k8s cluster with cidr : 194.168.0.0/16 . Istio is getting installed but sidecar injection is failing, with error like internal error occurred: failed calling webhook "sidecar-injector.istio.io" : Post https://istiod.inject?timeout=30s: context deadline exceeded

Same I tried with cidr : 10.244.0.0/16 in single node k8s cluster, istio is getting installed and sidecar also getting injected and everything thing is working fine in single node.

So my question is , 
1. Is stio doesn't work with 194.168.0.0/16 cidr series?
2. Is istio doesn't work with multi node cluster?

**Comment by howardjohn** [comment]
Please follow https://github.com/istio/istio/wiki/Troubleshooting-Istio#diagnostics and let us know the result

**Comment by bond007007** [comment]
The above issue is resolved with cidr 

But with multi-master nd multi-worker node still facing the issue, still sidecar in not injecting.

Please help in resolving the above issue and Let me know if u need more info on the same 

Thanks-

**Comment by howardjohn** [comment]
Please follow the steps and post the results.

**Comment by bond007007** [comment]
> Please follow the steps and post the results.

All the tests and checks are passed whatever mentioned in the document.

Still I can see only difference i show istio is working on single master and worker node cluster but on multi-master worker k8s cluster it is failing to inject sidecar, failed calling webhook "sidecar-injector.istio.io" : Post https://istiod.inject?timeout=30s: context deadline exceeded


Please let us know if any issue in installing istio in multi-master cluster environment.

Though I have tried many checks and debugged no success in injecting sidecar. Still getting the same error.

Please help with the help issue. Thanks.

**Comment by bond007007** [comment]
If I m using any proxy in api server then what are the prerequisites required to make side car injection work?
