### ISSUE TITLE
failed to create "EnvoyFilter/istio-system/stats-filter-1.7": namespaces "istio-system" not found

### ISSUE THREAD

**Issue by shamsher31** [istio/istio#27165]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

I was trying to reproduce https://github.com/istio/istio/issues/25498 and got the following error.

```
$ ./out/linux_amd64/istioctl install --set profile=minimal --set values.global.istioNamespace=istio1 --set hub=grc.io/istio-testing  -d manifests/
This will install the Istio profile into the cluster. Proceed? (y/N) y

✔ Istio core installed                                                                                                                                                                            
2020-09-09T10:42:09.832101Z     error   installer       failed to create "EnvoyFilter/istio-system/metadata-exchange-1.6": namespaces "istio-system" not found
2020-09-09T10:42:09.886275Z     error   installer       failed to create "EnvoyFilter/istio-system/metadata-exchange-1.7": namespaces "istio-system" not found
2020-09-09T10:42:09.939994Z     error   installer       failed to create "EnvoyFilter/istio-system/metadata-exchange-1.8": namespaces "istio-system" not found
2020-09-09T10:42:09.994269Z     error   installer       failed to create "EnvoyFilter/istio-system/stats-filter-1.6": namespaces "istio-system" not found
2020-09-09T10:42:10.048425Z     error   installer       failed to create "EnvoyFilter/istio-system/stats-filter-1.7": namespaces "istio-system" not found
2020-09-09T10:42:10.102391Z     error   installer       failed to create "EnvoyFilter/istio-system/stats-filter-1.8": namespaces "istio-system" not found
2020-09-09T10:42:10.156077Z     error   installer       failed to create "EnvoyFilter/istio-system/tcp-metadata-exchange-1.6": namespaces "istio-system" not found
2020-09-09T10:42:10.209545Z     error   installer       failed to create "EnvoyFilter/istio-system/tcp-metadata-exchange-1.7": namespaces "istio-system" not found
2020-09-09T10:42:10.262965Z     error   installer       failed to create "EnvoyFilter/istio-system/tcp-metadata-exchange-1.8": namespaces "istio-system" not found
2020-09-09T10:42:10.316949Z     error   installer       failed to create "EnvoyFilter/istio-system/tcp-stats-filter-1.6": namespaces "istio-system" not found
2020-09-09T10:42:10.371008Z     error   installer       failed to create "EnvoyFilter/istio-system/tcp-stats-filter-1.7": namespaces "istio-system" not found
2020-09-09T10:42:10.424881Z     error   installer       failed to create "EnvoyFilter/istio-system/tcp-stats-filter-1.8": namespaces "istio-system" not found
✘ Istiod encountered an error: failed to create "EnvoyFilter/istio-system/metadata-exchange-1.6": namespaces "istio-system" not found                                                             
failed to create "EnvoyFilter/istio-system/metadata-exchange-1.7": namespaces "istio-system" not found
failed to create "EnvoyFilter/istio-system/metadata-exchange-1.8": namespaces "istio-system" not found
failed to create "EnvoyFilter/istio-system/stats-filter-1.6": namespaces "istio-system" not found
failed to create "EnvoyFilter/istio-system/stats-filter-1.7": namespaces "istio-system" not found
failed to create "EnvoyFilter/istio-system/stats-filter-1.8": namespaces "istio-system" not found
failed to create "EnvoyFilter/istio-system/tcp-metadata-exchange-1.6": namespaces "istio-system" not found
failed to create "EnvoyFilter/istio-system/tcp-metadata-exchange-1.7": namespaces "istio-system" not found
failed to create "EnvoyFilter/istio-system/tcp-metadata-exchange-1.8": namespaces "istio-system" not found
failed to create "EnvoyFilter/istio-system/tcp-stats-filter-1.6": namespaces "istio-system" not found
failed to create "EnvoyFilter/istio-system/tcp-stats-filter-1.7": namespaces "istio-system" not found
failed to create "EnvoyFilter/istio-system/tcp-stats-filter-1.8": namespaces "istio-system" not found
- Pruning removed resources                                                                                                                                                                       Error: failed to install manifests: errors occurred during operation
```

**Affected product area (please put an X in all that apply)**

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

**Steps to reproduce the bug**
```
$ make build
$ ./out/linux_amd64/istioctl install --set profile=minimal --set values.global.istioNamespace=istio1 --set hub=grc.io/istio-testing  -d manifests/
```

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

```
$ ./out/linux_amd64/istioctl version --remote
no running Istio pods in "istio-system"
1.8-dev

$ kubectl version --short
Client Version: v1.18.2
Server Version: v1.18.2
```

**How was Istio installed?**
Istio was not installed

**Environment where bug was observed (cloud vendor, OS, etc)**
```
kind v0.8.1 go1.13.3 linux/amd64
RHEL-8
```

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by shamsher31** [comment]
Does this mean first Istio must be installed in `istio-system` namespace before we can install it in other namespaces?

**Comment by shamsher31** [comment]
Probably the issue is somewhere here.
https://github.com/istio/istio/blob/a60de5a2bcb0e796f2f61639c6ecc9b926d2ba84/manifests/charts/istiod-remote/templates/telemetryv2_1.7.yaml#L177-L185

@howardjohn It only check `meshConfig.rootNamespace`. I think it also needs one more condition to handle `--set values.global.istioNamespace`?

Same chart used with only version update. https://github.com/istio/istio/pull/25742#pullrequestreview-453353923

**Comment by howardjohn** [comment]
What is `.Release.Namespace` set to? istio-system or `istio1`?

**Comment by morvencao** [comment]
Duplicated with https://github.com/istio/istio/issues/26813
You have to set two extra namespaces vis old helm values:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system-test
  name: "example"
spec:
  namespace: istio-system-test
  values:
    global:
      istioNamespace: istio-system-test
    meshConfig:
      rootNamespace: istio-system-test
```

**Comment by shamsher31** [comment]
Thanks @morvencao .

> You have to set two extra namespaces vis old helm values:

That's what I found during debugging. I'm working on adding `values.global.istioNamespace` to metadata.

**Comment by howardjohn** [comment]
Why don't we just default rootNamespace when its not set?

**Comment by morvencao** [comment]
@howardjohn Currently the default value for `meshConfig.rootNamespace` is `istio-system`
See: https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/values.yaml#L166
that's why we have to override the default value if we are intent to install istio in other namespaces rather than `istio-system`.

We have three `namepace`s in spec:

1. spec.namespace
2. spec.values.global.istioNamespace
3. spec.values.meshConfig.rootNamespace

`spec.namespace` is the istio installation namespace, default `istio-system`, but end-users can set any arbitrary value.
Usually end-users don't need to set `spec.values.global.istioNamespace` and `spec.values.meshConfig.rootNamespace` as they have default value `istio-system`. But in case when end-users install istio in other namespaces, they have to override the `spec.values.global.istioNamespace` and `spec.values.meshConfig.rootNamespace`.

We may need figure out how namespace field in iop spec maps to istioNamespace and rootNamespace if we donot expect to set two extra namespaces vis old helm values.

**Comment by howardjohn** [comment]
Right I think that there are valid use cases for all 3 of them being
different. So it's ok to make the defaults dynamic such that all 3 are
changed when just spec.namespace is changed, I am not sure we can/should
remove the options.

It's also really confusing so we should probably clearly document the
various options

**Comment by shamsher31** [comment]
Thanks @morvencao for taking the time to explain in detail.
 

> It's also really confusing so we should probably clearly document the
> various options.
> 

We should document it probably here.
https://istio.io/latest/docs/reference/commands/istioctl/#istioctl-install%20Examples
https://istio.io/latest/docs/setup/install/istioctl/#customizing-the-configuration
