### ISSUE TITLE
cacerts need validate

### ISSUE THREAD

**Issue by cocotyty** [istio/istio#27193]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

When cacerts exist, istiod or istioctl should check the validity of the cacerts.
Now any bad cacerts will accpected by istio, it's had to figure out why istio not work .
For example , if cacerts's **extendedKeyUsage** only contains **serverAuth** , no **clientAuth**, envoy cannot connect to pilot , but there's no usefull log.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[*] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by JimmyCYJ** [comment]
cc @myidpt
