### ISSUE TITLE
Does istio v1.6 support latest version of Kiali v1.23

### ISSUE THREAD

**Issue by dinesh4747** [istio/istio#27219]
we are working on upgrading latest version of **kiali v1.23** and running with **istio mesh v1.6** and just wanted to check whether if its compatible

**Comment by guyromb** [comment]
I am able to work with Kiali 1.23 (also tested with Istio 1.7).
Note: they disabled the login auth, so you have to use anonymous or another method.

**Comment by dinesh4747** [comment]
@guyromb - Thanks for the quick response and we are currently using istio v1.6.8 and need to check whether Kiali v1.23 would be compatible 

Either ways - its good to have some compatibility matrix across the istio and its dependent runtime components which would help us position better in terms of upgrade

**Comment by bianpengyuan** [comment]
Please take a look at Kiali's doc about version compatibility: https://kiali.io/documentation/latest/installation-guide/
