### ISSUE TITLE
xdsproxy results in latent bug being exposed again

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#27211]
Context: https://github.com/istio/istio/issues/22443

Basically, if we don't reference the workload certs over SDS in the xds cluster, we can get into a race where they are never actually fetched (Envoy never sends request). This has been present since ~1.5, but no one worked on it since we worked around it by fetching the certs in the xds cluster (tl;dr hypothesis: this serializes the order so we avoid the race).

With xds-proxy we don't have sds in the xds cluster so this is broken again

Example failure:
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27184/integ-pilot-k8s-tests_istio/19860 -> https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/27184/integ-pilot-k8s-tests_istio/19860/artifacts/pilot-9eb2f26fc6644b6c83e55a473/TestIngress/_test_context/istio-state-cluster-0376469353/cluster-0/istio-ingressgateway-5b78c55c99-tjdrk_proxy-config.json certs are not loaded

**Comment by rshriram** [comment]
Can we delay envoy start until the XDS proxy has started?

**Comment by howardjohn** [comment]
@rshriram I don't think that will fix the issue. The problem is there is a bug in Envoy in SDS. My understanding is there is some issue (not sure what, probably related to https://github.com/envoyproxy/envoy/issues/11120) where if a dynamic cluster comes in requesting SDS we sometimes don't request SDS. Static cluster (xds-grpc) seems fine. If we have already fetched the secret with static clusters, it also seems fine. This is my understanding of the bug, but I don't think anyone has found a code white box explanation for what is happening

**Comment by bianpengyuan** [comment]
since ads is turned on by default now, are we confident that this issue will be fixed by 1.8? Tentative upstream fix is pending, can we reliably verify the fix?

**Comment by howardjohn** [comment]
@bianpengyuan I have tentatively explored the dummy cluster. Its not the same as the original behavior since it isn't serialized (XDS and SDS happen in parallel), it did *seem* to have improvement. Its hard to tell if its "fixed" though since it happens 1/1000 times. We should treat https://github.com/envoyproxy/envoy/issues/11120 as the #1 top priority though - we can ship without the xds proxy but its going to mean we disable most networking/environments feature we work on in 1.8...

**Comment by howardjohn** [comment]
I have verified https://github.com/envoyproxy/envoy/pull/13344 fixes the issue, we just need to get it into our branch.

**Comment by howardjohn** [comment]
Will close in favor of https://github.com/istio/istio/issues/22443 which is also marked as release blocker
