### ISSUE TITLE
I can't get the version field when I query using the isto metric

### ISSUE THREAD

**Issue by yuanyiran** [istio/istio#27210]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

**Affected product area (please put an X in all that apply)**

[ ] Extensions and Telemetry

**Affected features (please put an X in all that apply)**

[ ] Physical machine

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

istio 1.2.2
kubernetes 1.14.2
helm 2.16.0

**How was Istio installed?**

helm install istio 1.2.2

**Environment where bug was observed (cloud vendor, OS, etc)**

Local physical machine kubernetes cluster istio no cluster deployment

**error describe**

When I use the isto index to query, I can't get the version field, but when my version is V1, I can get it. If it's v1.0, I can't get the version field

![image](https://user-images.githubusercontent.com/64528937/92728318-18d43280-f3a3-11ea-920d-49343a25cafb.png)
![image](https://user-images.githubusercontent.com/64528937/92728361-2ab5d580-f3a3-11ea-9078-c177f3e8ddfe.png)

![image](https://user-images.githubusercontent.com/64528937/92728488-5d5fce00-f3a3-11ea-80b1-5c5b1c206a48.png)
![image](https://user-images.githubusercontent.com/64528937/92728517-6781cc80-f3a3-11ea-9467-89f405f6fe00.png)

Is it because the dot symbol is not recognized in the version? What should I do to get the version number?

**Comment by yuanyiran** [comment]
I can't get the version after I changed it to v2. How can I quickly upgrade from V1.2.2 to the latest isto version? Do you want to install the latest version of isto? Is the 1.6 version of isto available for deployment on kubernetes 1.14.2?

**Comment by howardjohn** [comment]
How does version even get populated from an environment variable? Shouldn't it be a label on the pod?

**Comment by yuanyiran** [comment]
> How does version even get populated from an environment variable? Shouldn't it be a label on the pod? Or was this some mixer feature?

I added the label tag of pod and defined version
![image](https://user-images.githubusercontent.com/64528937/92841292-b4ea5200-f414-11ea-9a57-4e937950a0f7.png)

**Comment by yuanyiran** [comment]
I found that if my query statement "reporter = source", I can see the target version number of the access service. Maybe I still don't understand the difference between source and destination.
![image](https://user-images.githubusercontent.com/64528937/92843606-81f58d80-f417-11ea-9cb4-29bd1b4ab981.png)

Now I want to query the statistics of all service visits from the ingress gateway to its configuration. Which one is my reporter?

**Comment by bianpengyuan** [comment]
> I can't get the version after I changed it to v2.

By upgrading to v2, I mean upgrade to Telemetry V2, which is a Istio feature to replace Mixer and is the default telemetry option since Istio 1.5.

> How can I quickly upgrade from V1.2.2 to the latest isto version?

You will need to upgrade Istio version by version 1.2->1.3->1.4... It is not supported or tested to do skip version upgrade.

> I found that if my query statement "reporter = source", I can see the target version number of the access service. Maybe I still don't understand the difference between source and destination.

Take a look at this: https://istio.io/latest/docs/reference/config/metrics/. Ingress gateway acts as outbound sidecar for world outside mesh and you should use `source` to query it.

Is your original issue resolved? Were you able to see `v1.1` version label with proper query? If so, would you mind closing this issue? thanks!

**Comment by yuanyiran** [comment]
Can I upgrade telemetry separately to V2?

**Comment by bianpengyuan** [comment]
No, it is feature only available since 1.4.

**Comment by bianpengyuan** [comment]
Also if you are able to see the desired version label, which means it is not a Mixer bug, then it is not a must to upgrade to use telemetry v2 to get the behavior that you want. However, telemetry v2 or newer Istio generally is more performant and easier to use, so upgrade is highly recommended.

**Comment by yuanyiran** [comment]
okay, thank you. I also need to verify that it can be closed temporarily.

**Comment by howardjohn** [comment]
Closing as this has been addressed
