### ISSUE TITLE
VMs without WorkloadEntry get "proxy is in cluster , but controller is for cluster Kubernetes"

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#27234]
I am not 100% sure no workload entry is the root cause, but seems like it is

**Comment by champly** [comment]
## env

istio 1.6.9

## desc

i meet same problem
```
* proxy is in cluster , but controller is for cluster Kubernetes
```

it looks like add with 1.6.9, use 1.6.8 not meet this problem

**Comment by yuzisun** [comment]
@howardjohn What's the WorkloadEntry? I am getting the same error in 1.7.2

**Comment by yuzisun** [comment]
seems to be this check
https://github.com/istio/istio/blob/dc633616b9eec883e8397fe54bc3286e8b507cca/pilot/pkg/serviceregistry/kube/controller/controller.go#L964

**Comment by yuzisun** [comment]
In istiod the clusterID is passed in as kubernetes.

2020-09-28T01:14:07.819501Z     info    FLAG: --appNamespace=""
2020-09-28T01:14:07.819535Z     info    FLAG: --caCertFile=""
2020-09-28T01:14:07.819539Z     info    FLAG: --clusterID="Kubernetes"

**Comment by champly** [comment]
> ## env
> istio 1.6.9
> 
> ## desc
> i meet same problem
> 
> ```
> * proxy is in cluster , but controller is for cluster Kubernetes
> ```
> 
> this pod working kubernetes cluster
> 
> it looks like add with 1.6.9, use 1.6.8 not meet this problem.

I will resolve my problem, because of my sidecar(MOSN) is not upload ClusterID.

**Comment by yuzisun** [comment]
> > ## env
> > istio 1.6.9
> > ## desc
> > i meet same problem
> > ```
> > * proxy is in cluster , but controller is for cluster Kubernetes
> > ```
> > 
> > 
> > this pod working kubernetes cluster
> > it looks like add with 1.6.9, use 1.6.8 not meet this problem.
> 
> I will resolve my problem, because of my sidecar(MOSN) is not upload ClusterID.

@champly what is ClusterID here? my case is ingress gateway pod.

**Comment by champly** [comment]
> > > ## env
> > > istio 1.6.9
> > > ## desc
> > > i meet same problem
> > > ```
> > > * proxy is in cluster , but controller is for cluster Kubernetes
> > > ```
> > > 
> > > 
> > > this pod working kubernetes cluster
> > > it looks like add with 1.6.9, use 1.6.8 not meet this problem.
> > 
> > 
> > I will resolve my problem, because of my sidecar(MOSN) is not upload ClusterID.
> 
> @champly what is ClusterID here? my case is ingress gateway pod.

Maybe we meet not same problem, my sidecar is MOSN instead of envoy.
