### ISSUE TITLE
istio cannot work with ed25519 alg cacerts

### ISSUE THREAD

**Issue by cocotyty** [istio/istio#27238]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
istiod print such logs:

```
Error: failed to create discovery service: error initializing DNS certs: x509: requested SignatureAlgorithm does not match private key type
```
this line [https://github.com/istio/istio/blob/b2590e46399a150c1496dc169ad3cccc87009179/security/pkg/pki/util/generate_cert.go#L309](https://github.com/istio/istio/blob/b2590e46399a150c1496dc169ad3cccc87009179/security/pkg/pki/util/generate_cert.go#L309) is wrong ! 
Cert's **Signature Algorithm** is not same as csr's **Signature Algorithm**!
Cert's **Signature Algorithm**  depends on **CA's** key algorithm !

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[*] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

**Steps to reproduce the bug**
Use a ed25519 root CA to create istio cluster.
Istiod will not work as expected.

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
istio 1.7.0
**How was Istio installed?**
installed by istio operator.
**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by cocotyty** [comment]
@bianpengyuan help wanted!

**Comment by howardjohn** [comment]
What is setting the SignatureAlgorithm in the CSR?

**Comment by cocotyty** [comment]
> What is setting the SignatureAlgorithm in the CSR?

CSR created by istiod.

**Comment by howardjohn** [comment]
Csr generated by istiod? I thought the agent creates a csr and sends it to istiod?

I could not find any code where we actually set this field in the CSR we send to istiod

**Comment by cocotyty** [comment]
> Csr generated by istiod? I thought the agent creates a csr and sends it to istiod?
> 
> I could not find any code where we actually set this field in the CSR we send to istiod

maybe here?
[https://github.com/istio/istio/blob/04c64e17ca151c7ebdeb3ad9b4453ae6c231bcf1/pilot/pkg/bootstrap/certcontroller.go#L146]()

**Comment by cocotyty** [comment]
> Csr generated by istiod? I thought the agent creates a csr and sends it to istiod?
> 
> I could not find any code where we actually set this field in the CSR we send to istiod

Actually, this field is not set by code ,it depends on key's algorithm.
See this code:
https://golang.org/src/crypto/x509/x509.go#L2600
