### ISSUE TITLE
How can I  get istio-proxy stat  when triggering circuit breaker?

### ISSUE THREAD

**Issue by hanzhc** [istio/istio#27237]
I am using the istio 1.2.5 to test the function of circuit breaker with fortio step by step according to the [document](https://istio.io/latest/docs/tasks/traffic-management/circuit-breaking/).But I get nothing when I run `kubectl exec "$FORTIO_POD" -c istio-proxy -- pilot-agent request GET stats | grep httpbin | grep pending`.I feel confused about it. Is there any other settings about fortio or istio? And I find the value of upstream_rq_pending_overflow is 0.

**Comment by bianpengyuan** [comment]
It is likely that doc for 1.7 is not working properly with 1.2 istio. Can you try to follow 1.2 doc https://istio.io/v1.2/docs/tasks/traffic-management/circuit-breaking/?

Also note, 1.2 is way out of support window, please consider upgrade to newer version of Istio. thanks.

**Comment by howardjohn** [comment]
Closing this as its on a very EOL version and there has been no updates for months. Thanks
