### ISSUE TITLE
Istiod discovery should validate its flags (panic)

### ISSUE THREAD

**Issue by esnible** [istio/istio#27257]
To reproduce, install Istio with `istioctl install --set values.pilot.keepaliveMaxServerConnectionAge="-30m"`

The logs show a **panic** and backtrace that does not include any Istio code.  A user would not be able to figure this out.  Istiod SHOULD fail on bad flag values, but it should log the reason and exit, not panic inside `google.golang.org/grpc/internal/transport.NewServerTransport(...)`

A related Issue to fix it so that the user gets this feedback from _istioctl_ or as a Status on the operator's IOP resource. https://github.com/istio/istio/issues/21473 .  This issue is just to make Pilot output meaningful logs when it is misconfigured.

I am willing to do this work if no one else wants it.  I prefer if someone from @istio/wg-networking-maintainers triages it with a Priority first.

**Comment by jhughes2112** [comment]
Hit this today while upgrading from 1.6.x to 1.7.1, using exactly the same command line to istioctl.

**Comment by jhughes2112** [comment]
I ran into this today.  Still working out a way to install via a stored manifest properly, but if you try this (after creating the namespace):
```
istioctl manifest generate --set values.global.jwtPolicy=first-party-jwt >istio.yaml
kubectl apply -f istio.yaml
```
You will get a crashloop every time.

**Comment by jhughes2112** [comment]
Looks like I get a crashloop with `istioctl install --set profile=default` straight out of the box, too.
Maybe 1.7.1 isn't fully baked?  I'm running on a bare metal Intel NUC with Ubuntu 18.04 LTS and Kubernetes 1.19.1 as the platform.  1.6.9 works fine, but 1.7.1 does not install at all.

**Comment by jhughes2112** [comment]
For the record, 1.7.0 installs just fine with either of the above methods for me.

**Comment by esnible** [comment]
@jhughes2112 1.7.1 should not crash with the defaults.  A crash with the defaults is probably not the issue here, which is incorrect customization.

What Kubernetes version are you running?  Does `kubectl -n istio-system logs deployment/istiod` show any interesting critical errors or panics?

**Comment by jhughes2112** [comment]
As stated directly above, Ubuntu 18.04LTS and Kubernetes 1.19.1.  Other than a massive dump of all the golang symbols, this is what is mentioned at the bottom:

```
fatal error: invalid runtime symbol table
runtime: panic before malloc heap initialized

runtime stack:
runtime.throw(0x31824fc, 0x1c)
        runtime/panic.go:1116 +0x72 fp=0x7fff23035b50 sp=0x7fff23035b20 pc=0x434b02
runtime.moduledataverify1(0x5420780)
        runtime/symtab.go:526 +0x5a2 fp=0x7fff23035c58 sp=0x7fff23035b50 pc=0x452f42
runtime.moduledataverify()
        runtime/symtab.go:491 +0x34 fp=0x7fff23035c78 sp=0x7fff23035c58 pc=0x452974
runtime.schedinit()
        runtime/proc.go:543 +0x56 fp=0x7fff23035cd0 sp=0x7fff23035c78 pc=0x4381e6
runtime.rt0_go(0x7fff23035d08, 0x9, 0x7fff23035d08, 0x0, 0x0, 0x9, 0x7fff2303778e, 0x7fff230377ad, 0x7fff230377b7, 0x7fff230377cf, ...)
        runtime/asm_amd64.s:214 +0x125 fp=0x7fff23035cd8 sp=0x7fff23035cd0 pc=0x465625
```

I can tell you, having actually gotten it to properly install and then fail again, it 100% has to do with trying to install Istio on a master-worker node.  If you create a single-node cluster that has NoSchedule taint on the master, istio has never installed properly, even in 1.6.x.  So my script removes the NoSchedule taint and installs Istio.  In 1.7.1, this is a panic with crashloop backoff.  In 1.7.0, it works.

As soon as I add a second machine, even with the master allowing workloads, it installs fine.  Fwiw, my master node is a 64Gb ram machine, but only has 2 cores.

**Comment by jhughes2112** [comment]
And yes, this is crash with this exact command line: `istio install`

**Comment by howardjohn** [comment]
@jhughes2112 that is aweird error. I have only seen references from many many years ago. This may help possibly? https://stackoverflow.com/questions/18549324/golang-panic-before-malloc-heap-initialized

**Comment by jhughes2112** [comment]
Also interesting... doing a standard install of 1.7.1 with a master + 2 worker nodes in bare metal did not actually create the envoyfilter.networking.istio.io CRD at all.  This prevented my cert-manager from completing its ACME requests, and also prevented me from getting to my services (but did do the http->https redirect since that's in virtual services).  

When I uninstalled 1.7.1 and installed 1.6.9, using exactly the same manifests for everything else, it works fine.
