### ISSUE TITLE
How to set the short name in the host in IngressGateway

### ISSUE THREAD

**Issue by kengan** [istio/istio#27266]
I have a ingress gate way setting as following:

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: caller-gateway
  namespace: testistio
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "caller"

but when I apply the yaml, I get error as following:
istio-rules.yaml": admission webhook "pilot.validation.istio.io" denied the request: configuration is invalid: short names (non FQDN) are not allowed

the host "caller" can not be modified. How can I solve this problem. Thank you!

**Comment by howardjohn** [comment]
This is not currently possible.

**Comment by esnible** [comment]
You can use

```
  hosts:
  - "*"
```
and have this gateway handle all hosts, including `caller`.

**Comment by howardjohn** [comment]
Closing as this is answered
