### ISSUE TITLE
Remove allowlist for envoy metrics or make it expandable

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#27272]
When using EnvoyFilters, it is difficult to understand whether it takes any effect, because istio hides majority of envoy metrics. For example, adding a new cluster, we don't get cluster metrics for it, so it's difficult to say whether the upstream cluster is healthy or not. Similarly, adding ECDS config to filters obfuscates any errors (e.g. making a typo in URI is entirely invisible).

The request is to expose all metrics from envoy, or at least make it easy to expand without restarts.

@howardjohn @ramaraochavali

**Comment by bianpengyuan** [comment]
Did some measurement here: https://github.com/istio/istio/issues/23166 Looks like it is still very expensive to expose all metrics, so it is unlikely to be a viable option. It might make more sense to expose the desired particular suffix by default.

**Comment by kyessenov** [comment]
I am specifically looking or xDS stats: <stat_prefix>.extension_config_discovery.<extension_config_name>, and xDS cluster stat (dynamically loaded one, not xds_cluster).

**Comment by esnible** [comment]
Istio supports the pod annotation `sidecar.istio.io/statsInclusionPrefixes` (and also `sidecar.istio.io/statsInclusionRegexps` and `sidecar.istio.io/statsInclusionSuffixes`).  The default is, I believe, `cluster_manager,listener_manager,server,cluster.xds-grpc,wasm`.  You should be able to your own.

**Comment by kyessenov** [comment]
@esnible That is certainly a work around. The problem is that it requires a restart (or pod redeployment), which is onerous to be able to apply EnvoyFilters.

**Comment by howardjohn** [comment]
Isn't this configured in bootstrap and would fundamentally require a
restart?

**Comment by kyessenov** [comment]
@howardjohn Yes. So this might need dynamic stats support in Envoy, or just not filter stats so aggressively.

**Comment by douglas-reid** [comment]
@kyessenov do you have any idea on the scope of work to support dynamic stats support?

**Comment by kyessenov** [comment]
I think it could use the existing hot-restart code path, but it should probably be discussed with envoy folks.
