### ISSUE TITLE
How to create istio-archive?

### ISSUE THREAD

**Issue by sikka** [istio/istio#27284]
@howardjohn - 
I see that [this commit ](https://github.com/istio/istio/commit/f3ce79e421353b38939e7951b61aa75b627b977f) got rid of the `istio-archive` target.
I tried finding a newer make target that generates `istio-1.7.1-linux-amd64.tar.gz`, but was not able to. How can I achieve this?

**Comment by howardjohn** [comment]
https://github.com/istio/release-builder has all the info and steps
