### ISSUE TITLE
Unable to add route_name as a label in the requests_total counter

### ISSUE THREAD

**Issue by softcane** [istio/istio#27281]
**Bug description**
According to 1.6 documentation, route_name is an extra attribute that can be added to the requests_total counter. However, It's been added as a prefix to the metric counter.
https://istio.io/v1.6/docs/tasks/observability/metrics/customize-metrics/

**stats-filter patched configuration:**

```  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.http_connection_manager
            subFilter:
              name: envoy.router
      proxy:
        proxyVersion: ^1\.6.*
    patch:
      operation: INSERT_BEFORE
      value:
        name: istio.stats
        typed_config:
          '@type': type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
          value:
            config:
              configuration: |
                {
                  "debug": "false",
                  "stat_prefix": "istio",
                  "disable_host_header_fallback": true,
                  "metrics": [{"name": "requests_total","dimensions": {"route_name": "route_name"}}]
                }
```

**Current behaviour:**
`envoy_route_name___test____istio_requests_total`

**Expected behaviour:**
`istio_requests_total{route_name="test"}`

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
1.6

**How was Istio installed?**
istioctl

**Comment by howardjohn** [comment]
Seems like a bad regex? @kyessenov @douglas-reid

**Comment by kyessenov** [comment]
Yeah, extraStatTags is required to introduce new metric label names, see https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/.

**Comment by softcane** [comment]
@kyessenov 
Isn't `proxyConfig.extraStatTags` is only applied to the sidecars? In my case, I want to add it in the ingress routes only.

**Comment by kyessenov** [comment]
I think it's applied everywhere. It doesn't hurt if you don't actually use the tag, just adds a bit of perf overhead for regex. If it's not, we probably need to fix it.

**Comment by kyessenov** [comment]
Confirmed `route_name` is not available in 1.8.  Seems like an envoy bug.

**Comment by kyessenov** [comment]
I think there might be a confusion about what route name refers to. Route name is the name of the individual route entry, not the route configuration. It seems to work per https://github.com/istio/proxy/pull/3042. I myself confused the two, but the individual entry name appears to work.

**Comment by fcantournet** [comment]
We use `route_name` on istio 1.6.12 & it works with extraStatsTags set in the istioOperator.
Both on gateways & mesh proxies

```
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_OUTBOUND
        proxy:
          proxyVersion: '^1\.6.*'
        listener:
          filterChain:
            filter:
              name: "envoy.http_connection_manager"
              subFilter:
                name: "envoy.router"
      patch:
        operation: INSERT_BEFORE
        value:
          name: istio.stats
          typed_config:
            "@type": type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
            value:
              config:
                root_id: stats_outbound
                configuration: |
                  {
                    "debug": "false",
                    "stat_prefix": "istio",
                    "metrics": [
                    {
                      "name": "requests_total",
                      "dimensions": {
                        "request_method": "request.method",
                        "request_route": "route_name"
                      }
                    }]
                  }
```


```
    defaultConfig:
      extraStatTags: ["request_method","request_route"]
```

**Comment by bianpengyuan** [comment]
@softcane Seems like this is working according to @fcantournet. I am going to close this, please reopen if this is still not working for you. Thanks!

**Comment by ediezh** [comment]
@bianpengyuan can we reopen this? I'm getting the exact same issue in istio 1.7. 

My IstioOperator config is as below:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    tcpKeepalive:
      time: 300s
    defaultConfig:
      extraStatTags:
        - request_path
  values:
    telemetry:
      v2:
        prometheus:
          configOverride:
            inboundSidecar:
              debug: false
              stat_prefix: istio
              metrics:
                - dimensions:
                    request_operation: "istio_operationId"
            outboundSidecar:
              debug: false
              stat_prefix: istio
              metrics:
                - dimensions:
                    request_operation: "istio_operationId"
                    request_path: "request.url_path"
            gateway:
              debug: false
              stat_prefix: istio
              disable_host_header_fallback: true
              metrics:
                - dimensions:
                    request_operation: "istio_operationId"
                    request_path: "request.url_path"
```

Instead of getting metrics like `istio_requests_total{request_path="/login"}`, I'm getting a whole bunch of new time series metrics with name like `envoy_request_path___login___istio_requests_total`.

pod annotation `sidecar.istio.io/extraStatTags` mentioned in this link https://istio.io/latest/docs/tasks/observability/metrics/customize-metrics/ gives me the same result.

**Comment by bianpengyuan** [comment]
Did you check the metrics on gateway? There is a known issue that extra tags might not work on gateway: https://github.com/istio/istio/issues/28424

**Comment by ediezh** [comment]
Hi @bianpengyuan the podAnnotation on ingress gateway is the first thing I tried which didn’t work, do I need to set the ISTIO_METAJSON_ANNOTATIONS  environment variable directly?

I’ll share some logs later.

**Comment by Janesee3** [comment]
Hi @ediezh, may I know how you managed to resolve this issue in the end? I am having the same issue as you on Istio 1.7.8 currently.

**Comment by ediezh** [comment]
Hi @Janesee3 in my case, the `proxyConfig.extraStatTags` works for istio sidecar proxy.
