### ISSUE TITLE
"upstream" and "downstream" terminology in istio

### ISSUE THREAD

**Issue by istionary** [istio/istio#27288]
Hello,

I am confused by the use of the terms "upstream" and "downstream" in istio documentation.

The glossary https://istio.io/latest/docs/reference/glossary/ uses the term to define _Source_ as _The downstream client of the Envoy proxy._ A similar wording is in https://istio.io/latest/docs/reference/config/networking/virtual-service/ _A downstream client calling a service._ 

This sounds like a client is always assigned the role of a downstream when calling a service. And consequently, a service always has the role of an upstream when called by a client.

However, for me upstream and downstream are message flow directions. A message is always flowing from upstream to downstream. For example, for a HTTP request the client is upstream, the server downstream. For the response this reverses. Then the server is upstream, the client is downstream. I understand this from RFC 7230 _Hypertext Transfer Protocol (HTTP/1.1): Message Syntax and Routing_ (https://tools.ietf.org/html/rfc7230#section-2.3):

> The terms "upstream" and "downstream" are used to describe
> directional requirements in relation to the message flow: all
> messages flow from upstream to downstream. 

I would like to learn the official definitions of the two terms in istio. And maybe the referenced documentation can be updated to add those definitions and a clarification with respect to RFC 7230?

Thanks
Thomas

**Comment by howardjohn** [comment]
https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/intro/terminology

and

https://discuss.hashicorp.com/t/why-does-hashicorp-seem-to-refer-to-upstream-downstream-as-the-opposite-of-everything-else-ive-read/8663

May be helpful here
