### ISSUE TITLE
Istio-proxy TLS connection errors (receiving RST packets)

### ISSUE THREAD

**Issue by astrikos** [istio/istio#27291]
**Bug description**
We use istio between our kubernetes namespaces and pods with mtls support. Sometimes we notice that a pod from one namespace that has istio enabled cannot reach another pod in a another namespace that is also istio enabled.
The error we get from inside the source pod is:
```
# curl serviceA.namespaceA
upstream connect error or disconnect/reset before headers. reset reason: connection failure/ 
```
Running tcpdumps from both the pods we see that the destination pod is sending an RST packet after source pod has established connection and has sent a single payload packet.
Enabling verbose logging on both `istio-proxy` sidecars we can see on the destination pod the following logs
```
13:25.947972Z     debug   envoy config    Create NotReadySslSocket
13:25.948000Z     debug   envoy conn_handler      [C8597] new connection
13:25.948015Z     debug   envoy connection        [C8597] closing socket: 0
13:25.948042Z     debug   envoy conn_handler      [C8597] adding to cleanup list
13:26.953240Z     debug   envoy conn_handler      [C8598] new connection
```
[That makes us believe this might be an TLS error](https://github.com/vadimeisenbergibm/envoy/blob/aae6a12decb5ace1010ba3402e499614a97421c1/source/common/ssl/ssl_socket.cc#L433), so by adding a destination rule that forces communication to destination go plain HTTP fixes the issue.
Also by restarting the istio-proxy container fixes the issue as well.
After some time that everything works as expected, the issue seems to come back again.

Another point to notice is that by hitting directly the IP of the pod we don't get that problem, it's only by hitting the kubernetes service name.

I am not sure if the info provided here are enough to be able to pin point where the error might be, but any hint on where to look and debug furthermore would be highly appreciated.

If you need any additional info let me know! A config dump is attached as well in case it helps.

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**
Unfortunately we haven't identified yet a concrete way to consistently reproduce it.
**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
`1.7.1`
**How was Istio installed?**
```
istioctl install --set values.global.outboundTrafficPolicy.mode=ALLOW_ANY \
                            --set values.global.proxy.holdApplicationUntilProxyStarts=true \
                            --set values.gateways.enabled=true \
                            --set values.global.istiod.enableAnalysis=true \
                            --set values.gateways.istio-ingressgateway.enabled=true \
                            --set meshConfig.enablePrometheusMerge=false \
                            --set values.sidecarInjectorWebhook.rewriteAppHTTPProbe=true
```
**Environment where bug was observed (cloud vendor, OS, etc)**
`AWS`, `ubuntu 20.04`, `kubernetes 1.18.6`

[istio-namespace-cm.yaml.gz](https://github.com/istio/istio/files/5217726/istio-namespace-cm.yaml.gz)

**Comment by m0ps** [comment]
Not sure for 100%, but probably this https://github.com/istio/istio/issues/26922#issuecomment-692570952 can be helpful.

**Comment by astrikos** [comment]
@m0ps thanks for the suggestions, unfortunately we use istio `1.7` and the `protocolDetectionTimeout` seems to be by [default](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig) 5s there. So I am not sure if that's the case :thinking:

**Comment by commixon** [comment]
Actually this seems similar to https://github.com/istio/istio/issues/13107

**Comment by howardjohn** [comment]
This slooks like it may be the same as https://github.com/istio/istio/issues/22443 by the  `NotReadySslSocket`

The way to be 100% sure its to run `istioctl pc secret` on the pod. if it shows WARMING it is the same issue. We (finally)have a fix open inside Envoy now but its not yet merged

**Comment by astrikos** [comment]
@howardjohn indeed that seems to be the issue. We noticed this week that non-healthy sidecars miss the following lines that healthy sidecars have (with default logging levels):
```
2020-10-21T12:19:34.777316Z     info    sds     resource:ROOTCA new connection
2020-10-21T12:19:34.777426Z     info    cache   Loaded root cert from certificate ROOTCA
2020-10-21T12:19:34.777545Z     info    sds     resource:ROOTCA pushed root cert to proxy
```
So it seems that non-healthy sidecars miss rootCA cert hence all the tls traffic is broken. After searching the issues we came up with the https://github.com/istio/istio/issues/22443 as you mentioned.

Doing the command you specified, validates indeed the theory that this is the issue.
```
RESOURCE NAME     TYPE           STATUS      VALID CERT     SERIAL NUMBER                               NOT AFTER                NOT BEFORE
ROOTCA                           WARMING     false
```
I see this is included in 1.8 milestone which has 10 Nov as due date. Would that be the date that new version is expected? Or at least around that time?

**Comment by howardjohn** [comment]
Yes, should be shipped Nov 10 per https://github.com/istio/istio/wiki/Istio-Release-1.8

**Comment by howardjohn** [comment]
Lets consolidate this with https://github.com/istio/istio/issues/22443. Thanks for confirming!
