### ISSUE TITLE
Log SPIFFE ids

### ISSUE THREAD

**Issue by olsaki** [istio/istio#27290]
**Describe the feature request**

- log the related SPIFFE id when a new certificate is signed by the Istio CA
- this information should be available on INFO log level

Nice to have:

- log the related SPIFFE id when a new certificate signing request is received by the Istio CA
- this information should be available on DEBUG log level

**Describe alternatives you've considered**

- inspecting DEBUG level log messages (not successful)
- getting the information from the istio-proxy logs of the particular service / pods (not successful)

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

When a certificate is created the general event can be found in the logs.

However, there is no mention of the related SPIFFE id when a new certificate (identity) is created. But especially this information would be useful (and is sometime even required) for audit logs.

**Comment by howardjohn** [comment]
I am not against adding logging but if you are trying to audit the identities created, this seems like the wrong approach. The logs are meant for debugging only. if we want to support auditing we really need a more secure solution.

**Comment by JimmyCYJ** [comment]
cc @myidpt @liminw

**Comment by williamaronli** [comment]
so @howardjohn @JimmyCYJ @olsaki do we comes to a consensus whether this audit debug log should be added or not?
