### ISSUE TITLE
More generic Kiali configmap deployment. 

### ISSUE THREAD

**Issue by abhioncbr** [istio/istio#27297]
**Describe the feature request**
Currently, Kiali ConfigMap deployment is not generic enough to handle different configs, for example, `accessible_namespace` value is hardcoded for all namespaces. 

```yaml
   deployment:
      accessible_namespace: ['**']
```

It should be configurable, and also there is no param for `exclude-namespace` like in `samples/addons/kiali.yaml`. I also noticed Kiali supports openID based authentication for Kiali however charts are not having such configs. It would be great, if we support such generic configs.

**Describe alternatives you've considered**
Manifests for charts should be updated to include all those generic configs.

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
samples/addons/kiali.yaml is a plain YAML with no customization available. This is meant as a starting point for users to get up and running, it is not intended as production grade fully configurable helm chart. You are more than welcome to make changes to it (locally) or switch to using the kiali helm chart or operator (not maintained by Istio team). See https://istio.io/latest/blog/2020/addon-rework/ for more info. Thanks
