### ISSUE TITLE
Selective EnvoyFilter inclusion for Multicluster installs

### ISSUE THREAD

**Issue by aattuluri** [istio/istio#27300]
**Describe the feature request**
If multiCluster is set to true, an envoy filter to translate *.global to *svc.cluster.local is included in the operator configuration. This should be configurable as i) There can be cluster suffixes which are not "svc.cluster.local" or ii) *.global could be directly addressable in remote cluster without any translation via a Service Entry.

**Describe alternatives you've considered**
Disable operator and delete the EnvoyFilter but that will defeat the purpose.

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by zenvdeluca** [comment]
I have to apply overlay patches in order to modify .global to another .custom.domain

see a mention of this fix in 1.7.4 changelog, but not sure if address my use case

**Comment by aattuluri** [comment]
This has been fixed with https://github.com/istio/istio/pull/27427

**Comment by zenvdeluca** [comment]
for posterity, the parameter I was looking for is multicluster.globalDomainSuffix

**Comment by aattuluri** [comment]
@zenvdeluca 
Yes, you can use `.Values.global.multiCluster.globalDomainSuffix` to configure a custom domain. However, this doesn't set up the DNS though. Meaning, you have to still update the dns lookup.
