### ISSUE TITLE
Allow for Istio Operator to be installed via Kustomize

### ISSUE THREAD

**Issue by Kampe** [istio/istio#27310]
There should be very little work to get this to a deployable state, before the operator was merged into the istio root repo, this was achievable by running 
`kustomize build github.com/istio/operator/deploy/`

Would allow others to install istio very simply, and for those who use gitops tooling to utilize the operator as a remote base and utilize the CRDs to deploy Istio via git. 

[X] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by Kampe** [comment]
@howardjohn is this by chance possible in the operators current form?

**Comment by Kampe** [comment]
This works, even if not intended to potentially as I see this is actively being worked on

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/istio/istio/master/manifests/charts/istio-operator/crds/crd-operator.yaml
  - https://raw.githubusercontent.com/istio/istio/master/manifests/charts/istio-operator/files/gen-operator.yaml
```

**Comment by samof76** [comment]
But is this the right way? Or is `istioctl` the highway?

**Comment by cslovell** [comment]
It would be good to know if this is supported long term, as it would allow Istio to be installed via gitops approaches using Argo / Flux.
