### ISSUE TITLE
Istiod restart seems to break `istioctl wait`

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#27330]
I restarted Istiod. Now `istioctl wait` results in logs like `error   ads     Unable to retrieve resource Gateway/default/istio-egressgateway at version oZ0CJ+DaE3I=: the trie node a19d0227e0da1372 is unavailable in the disk db, db may be corrupted`
cc @therealmitchconnors

**Comment by howardjohn** [comment]
```
$ ik ps
NAME                                                   CDS        LDS        EDS        RDS                            ISTIOD                      VERSION
istio-egressgateway-76c9c688cd-jftk4.istio-system      SYNCED     SYNCED     SYNCED     STALE (Never Acknowledged)     istiod-55c4b8f756-twp7x     1.8-alpha.9c7842669edde9fc697158ce6645e519a0904759
```

is also seen

**Comment by howardjohn** [comment]
not stale(?)

**Comment by zhlsunshine** [comment]
@istio-policy-bot Please do not close this issue, I can reproduce this case. So @howardjohn  could you please help to assign this issue for me? Thanks!

**Comment by zhlsunshine** [comment]
I have not reproduced this error message any more since I pull newest code from master branch yesterday. So I think there should be someone has already fixed it.
