### ISSUE TITLE
Can istio control flow by access IP

### ISSUE THREAD

**Issue by kengan** [istio/istio#27346]
I want to control the flow by the user access IP for example
If user call my restful api through the machine with the  IP 1.2.3.4, I want the user go to the version 2
If user call my restful api through the machine with the  IP 4.5.6.7, I want the user go to the version 1
How to use the istio to achieve this ? Thank you

**Comment by howardjohn** [comment]
https://istio.io/latest/docs/reference/config/networking/virtual-service/#L4MatchAttributes provides the routing options. You can control by destination IP but not source IP, so its mostly useful for sidecar. Please feel free to direct future questions to https://discuss.istio.io/. thanks!
