### ISSUE TITLE
Istioctl commands failing with unknown error in 1.7.1

### ISSUE THREAD

**Issue by casparrolfe** [istio/istio#27359]
**Bug description**

Unable to run debug commands against install of Istio 1.7.1 after upgrading from 1.4

```
istioctl version
6 errors occurred:
	* error port-forewarding into istio-policy-6f7cc759bd-5d2tl : an error on the server ("unknown") has prevented the request from succeeding (get pods istio-policy-6f7cc759bd-5d2tl:15014)
	* error port-forewarding into istio-policy-6f7cc759bd-lcmtt : an error on the server ("unknown") has prevented the request from succeeding (get pods istio-policy-6f7cc759bd-lcmtt:15014)
	* error port-forewarding into istio-telemetry-686669b49c-dtvxh : an error on the server ("unknown") has prevented the request from succeeding (get pods istio-telemetry-686669b49c-dtvxh:15014)
	* error port-forewarding into istio-telemetry-686669b49c-v8scb : an error on the server ("unknown") has prevented the request from succeeding (get pods istio-telemetry-686669b49c-v8scb:15014)
	* error port-forewarding into istiod-6d5d45d9f6-s2cs7 : an error on the server ("unknown") has prevented the request from succeeding (get pods istiod-6d5d45d9f6-s2cs7:15014)
	* error port-forewarding into istiod-6d5d45d9f6-tlkm4 : an error on the server ("unknown") has prevented the request from succeeding (get pods istiod-6d5d45d9f6-tlkm4:15014)


1.7.1
```

```
istioctl ps
Error: an error on the server ("unknown") has prevented the request from succeeding (get pods istiod-6d5d45d9f6-s2cs7:8080)
```

I am able to port forward an istiod pod on 8080 and receive a 200 response on `/ready`

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Version and proxy status should be printed

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

**How was Istio installed?**

`istioctl install`

**Environment where bug was observed (cloud vendor, OS, etc)**

EKS 1.16.13

**Comment by casparrolfe** [comment]
Please let me know what further information you need to diagnose the cause. There do not appear to be any logs in istiod indicating any kind of server error.

**Comment by richardwxn** [comment]
seems like a kubernetes issue, did you have any problem running other kubectl commands

**Comment by casparrolfe** [comment]
None that we have noticed. The role we are using has admin access to the cluster.

**Comment by howardjohn** [comment]
@casparrolfe can you run `kubectl get --raw '/api/v1/namespaces/istio-system/pods/istiod-5f4586ccd4-x4mmk:15014/proxy/debug' -v9`? Replace the pod with one you have. You can try it on 1.6 even if you rolled back. That is basically what the new istioctl command does, so that should give us some more info about what is going wrong.

**Comment by casparrolfe** [comment]
```
kubectl get --raw '/api/v1/namespaces/istio-system/pods/istiod-6d5d45d9f6-tlkm4:15014/proxy/debug' -v9
I0917 06:11:06.140687   53197 loader.go:375] Config loaded from file:  /root/.kube/config
I0917 06:11:06.141385   53197 round_trippers.go:423] curl -k -v -XGET  -H "User-Agent: kubectl/v1.16.13 (linux/amd64) kubernetes/39a145c" -H "Accept: application/json, */*" 'https://api.eks1.mydomain/api/v1/namespaces/istio-system/pods/istiod-6d5d45d9f6-tlkm4:15014/proxy/debug'
I0917 06:11:07.157327   53197 round_trippers.go:443] GET https://api.eks1.mydomain/api/v1/namespaces/istio-system/pods/istiod-6d5d45d9f6-tlkm4:15014/proxy/debug 500 Internal Server Error in 1015 milliseconds
I0917 06:11:07.157418   53197 round_trippers.go:449] Response Headers:
I0917 06:11:07.157449   53197 round_trippers.go:452]     Date: Thu, 17 Sep 2020 06:11:07 GMT
I0917 06:11:07.157468   53197 round_trippers.go:452]     Content-Type: application/json
I0917 06:11:07.157498   53197 round_trippers.go:452]     Content-Length: 134
I0917 06:11:07.157561   53197 round_trippers.go:452]     Server: nginx/1.19.1
I0917 06:11:07.157652   53197 round_trippers.go:452]     Audit-Id: 60247b1c-3069-4dc2-a95f-2630a3032980
I0917 06:11:07.157684   53197 round_trippers.go:452]     Cache-Control: no-cache, private
I0917 06:11:07.157740   53197 request.go:968] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"invalid upgrade response: status code 200","code":500}
I0917 06:11:07.159188   53197 helpers.go:199] server response object: [{
  "metadata": {},
  "status": "Failure",
  "message": "invalid upgrade response: status code 200",
  "code": 500
}]
```

I think this might be something to do with the NGINX proxy we have in front of the Kubernetes API. Will investigate a bit more. Thanks.

**Comment by casparrolfe** [comment]
Everything works when I bypass the reverse proxy. Unfortunately this isn't practical for our every day use, so we will need to figure out what is causing the issue there, but it certainly looks like istioctl is working as intended. 

Thanks for your help, @howardjohn !
