### ISSUE TITLE
Istio Operator should revive the Istio deployments once they are deleted

### ISSUE THREAD

**Issue by houshengbo** [istio/istio#27355]
**Bug description**
Using the latest code base or any version of istio operator to install istio, three deployments, istio-egressgateway, istio-ingressgateway and istiod are launched.

If we delete any of these deployments, they cannot be revived by the istio operator. Istio operator still indicate the deployment is in health status with CR status info.

[ ] Docs
[*] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Install Istio with Istio Operator.
After all the deployments are launched by creating the CR, delete any one deployment resource of istio.
The deleted deployment should be restored by the istio operator.

**Steps to reproduce the bug**
Install Istio with Istio Operator.
After all the deployments are launched by creating the CR, delete any one deployment resource of istio.

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
Latest, every istio operator version

**How was Istio installed?**
Via operator

**Environment where bug was observed (cloud vendor, OS, etc)**
All environments

**Comment by morvencao** [comment]
Are you using in-cluster operator or `istioctl` to deploy istio?

**Comment by morvencao** [comment]
Looks like the PR https://github.com/istio/istio/pull/25076 break this, in-cluster should be working before that PR.

**Comment by houshengbo** [comment]
I used in-cluster operator to deploy istio.
