### ISSUE TITLE
Incorrect regex in corsPolicy/allowOrigins causes all routes to 404

### ISSUE THREAD

**Issue by blankley** [istio/istio#27364]
A regex of '*' in the corsPolicy/allowOrigins causes all routes (not just the route defined by the given VirtualService) to return 404's:

```apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
  - "hostname"
  gateways:
  - internal-gateway
  http:
  - route:
    - destination:
        host: httpbin
        port:
          number: 8000
    corsPolicy:
      allowOrigins:
        - regex: '*'
      allowMethods:
        - POST
        - GET
        - PUT
        - DELETE
      allowHeaders:
        - "*"
      maxAge: 300s
      allowCredentials: true
```

Istio gives no errors, but ingress-gateway logs:

```warning	envoy config	gRPC config for type.googleapis.com/envoy.config.route.v3.RouteConfiguration rejected: no argument for repetition operator: *```

Ingress gateways keep accepting traffic until restarted (or scaled by hpa). Fresh pods return only 404 on all routes.

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Istio would log an error pointing to the incorrect corsPolicy

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

Istio 1.7.0 
k8s 1.17.11

**How was Istio installed?**

istioctl install

**Comment by howardjohn** [comment]
@esnible I think we added validation for regex's, did we just not include this one?

**Comment by esnible** [comment]
When I apply this corsPolicy _kubectl_ responds with
```
Error from server: error when creating "STDIN": admission webhook "validation.istio.io" denied the request: configuration is invalid: "corsPolicy.allowOrigins": error parsing regexp: missing argument to repetition operator: `*`; Istio uses RE2 style regex-based match (https://github.com/google/re2/wiki/Syntax)
```

If I use `regex: '.*'` for allowOrigins the application succeeds.  `"allow_headers": "*"` is placed into the Envoy configuration, and 404s do not happen.

404s happen for me if I use the exact `hosts` and `gateways` here.  I used the values from _samples/httpbin/httpbin-gateway.yaml_.  Yours may be correct for your system, check with _istioctl analyze_ and setting the host header.  I used
```
  hosts:
  - "*"
  gateways:
  - httpbin-gateway
```

I tested with _curl_, Safari, and Chrome.  I am not sure about your use of `allowHeaders: "*"`.  I have never used that field.  I did not find much helpful in https://istio.io/latest/docs/reference/config/networking/virtual-service/#CorsPolicy or https://www.w3.org/TR/2020/SPSD-cors-20200602/#access-control-allow-headers-response-header .  **Note that I tested by going to `<myhost>/status/418`.  I did not try setting up a web site to make a cross-site request to `<myhost>/status/418`, so I didn't actually test if Istio was emitting something that would let CORS do its job.

**Comment by esnible** [comment]
@blankley Any further analysis on your end?

**Comment by esnible** [comment]
Closing because cannot reproduce.

**Comment by blankley** [comment]
FYI, related to https://github.com/istio/istio/issues/28880. Validation was in Fail: Ignore because of canary upgrade.
