### ISSUE TITLE
Istio k8s Ingress fails to route to backend if k8s ingress is using named port

### ISSUE THREAD

**Issue by darkstarmv** [istio/istio#27377]
**Bug description**
Istio k8s Ingress fails to route to backend if k8s ingress is using named port

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Istio k8s Ingress is able to route to backend if k8s ingress is using named port

**Steps to reproduce the bug**
1. deploy [goldpingger](https://github.com/helm/charts/tree/master/stable/goldpinger) and enable ingress
2. test ingress:
```
curl -I http://goldpinger.mydomain
HTTP/1.1 404 Not Found
date: Wed, 16 Sep 2020 23:26:04 GMT
server: istio-envoy
transfer-encoding: chunked
X-Content-Type-Options: nosniff
```
3. Edit ingress resource and change `servicePort` from `http` to `80`:
```
....
spec:
  rules:
  - host: goldpinger.mydomain
    http:
      paths:
      - backend:
          serviceName: goldpinger
          servicePort: http
        path: /*
```
4. Test ingress:
```
curl -I http://goldpinger.mydomain
HTTP/1.1 200 OK
accept-ranges: bytes
content-length: 21108
content-type: text/html; charset=utf-8
last-modified: Wed, 08 Apr 2020 12:34:59 GMT
date: Wed, 16 Sep 2020 23:38:11 GMT
x-envoy-upstream-service-time: 1
server: istio-envoy
X-Content-Type-Options: nosniff
```

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
```
istioctl version --remote
client version: 1.6.7
control plane version: 1.6.7
data plane version: 1.6.7 (2 proxies)
```

```
kubectl version --short
Client Version: v1.15.12
Server Version: v1.15.12
```
```
 helm version
version.BuildInfo{Version:"v3.2.3", GitCommit:"8f832046e258e2cb800894579b1b3b50c2d83492", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

**How was Istio installed?**
using helm

**Environment where bug was observed (cloud vendor, OS, etc)**
BYO GCE K8s

**Comment by howardjohn** [comment]
#24843 this was added in Istio 1.7

**Comment by darkstarmv** [comment]
ok, thank you
