### ISSUE TITLE
OpenShift - istio-proxy injection error: Error creating: admission webhook "sidecar-injector.istio.io" denied the request - Executing "inject" at <gt .ProxyConfig.Concurrency 0>: error calling gt: invalid type for comparison

### ISSUE THREAD

**Issue by kozmod** [istio/istio#27386]
**Bug description**
When trying install Istio from a manifest (witch was generated using *istioctl*) get an error:
```
Generated from replicaset-controller

Error creating: admission webhook "sidecar-injector.istio.io" denied the request: template: inject:140:7: executing "inject" at <gt .ProxyConfig.Concurrency 0>: error calling gt: invalid type for comparison
```
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[X] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

**Steps to reproduce the bug**
I generated manifest to install Istio (for example minimal profile) to install in the OpenShift as service mesh.
Manifests were generated using *istioctl*:
```
istioctl manifest generate \
    --set profile=${profile} \
    --set hub=<SOME PRIVATE REGISTRY>/istio \
    --set tag=1.6.2 \
    \
    --set values.kiali.hub=<SOME PRIVATE REGISTRY> \
    --set values.kiali.image=quay.io/kiali/kiali \
    --set values.kiali.tag=v1.18 \
    \
    --set values.grafana.image.repository=<SOME PRIVATE REGISTRY>/grafana/grafana \
    --set values.grafana.image.tag=6.5.2 \
    \
    --set values.prometheus.hub=<SOME PRIVATE REGISTRY> \
    --set values.prometheus.image=prom/prometheus \
    --set values.prometheus.tag=v2.15.1 \
    \
    --set values.global.jwtPolicy=first-party-jwt >"${Istio-manifest}"
``` 

than I try to install useing *oc* (OpenShift command line tool):
```
oc create secret docker-registry ${PULL_SECRET_NAME} \
      --docker-server=${PULL_DOCKER_SERVER} \
      --docker-username=${login} \
      --docker-password=${pass}

 oc apply -f ${Istio-manifest}}
```
get the success installed Istio, but get the **error**.
I found the line 
```
      {{- if gt .ProxyConfig.Concurrency 0 }}
        - --concurrency
        - "{{ .ProxyConfig.Concurrency }}"
      {{- end -}}
```
If remove this 4 lines 👉🏻 all works

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
istioctl version --remote
```
client version: 1.6.2
control plane version: d11407739d22462d35fd64a725dd08bf3e7f6265-dirty
data plane version: 1.7-dev (2 proxies)
```
oc version
```
Server Version: 4.3.18
Kubernetes Version: v1.16.2
```
kubectl version --short
```
Client Version: v1.19.0
Server Version: v1.16.2
```
**How was Istio installed?**
Generate manifest using **istioctl** and install using **oc**

**Comment by jamsa2-rogBec-xahpuv** [comment]
https://www.knowyourotcs.org/wp-content/uploads/2015/03/72dpi--SafeMedicineDisposal_poster_v4r2.pdf

**Comment by howardjohn** [comment]
you must have a mismatch of something, such as istiod version and injection template. I see your control plane version is some random sha so seems like you are doing your own build and may have built the wrong version compare to the install template you are using?

**Comment by kozmod** [comment]
I have clone `release-1.6`, build docker images and use `istioctl 1.6.2`

**Comment by howardjohn** [comment]
@kozmod from your issue: `data plane version: 1.7-dev (2 proxies)` so clearly something is going wrong?

**Comment by kozmod** [comment]
Maybe, but I don't understand how `data plane version: 1.7-dev` matches with release/dev branches

**Comment by jamsa2-rogBec-xahpuv** [comment]
noreply@letfan.com

**Comment by howardjohn** [comment]
Sorry to close an unresolved issue, but we do not have the bandwidth for helping with issues that are not from product we ship, and this is a bug in your custom building. I would recommend you look at https://github.com/istio/release-builder/ if you want to do a custom build to match what we are doing. Thanks.

**Comment by egegunes** [comment]
@howardjohn it's not a custom build issue:

```
$ kubectl version --short
Client Version: v1.20.0
Server Version: v1.16.15-gke.4300

$ istioctl version
client version: 1.8.1
control plane version: 1.8.1
data plane version: 1.7.6 (44 proxies), 1.8.1 (2 proxies)

94s         Warning   FailedCreate        replicaset/*********-d6869cddf             Error creating: admission webhook "sidecar-injector.istio.io"
denied the request: template: inject:140:7: executing "inject" at <gt .ProxyConfig.Concurrency 0>: error calling gt: invalid type for comparison
```

I installed istio (1.6.3) with `istioctl`. Upgraded to 1.8.1 by first upgrading to 1.7.6 then 1.8.1 by `istioctl upgrade`.
