### ISSUE TITLE
TestClientTracing and TestProxyTracing regression

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#27391]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27105/integ-telemetry-k8s-tests_istio/20057
https://prow.istio.io/view/gs/istio-prow/logs/integ-telemetry-k8s-tests_istio_postsubmit/3722

Seems to have recently got worse - could be a real regression

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27312/integ-telemetry-k8s-tests_istio/20050
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27365/integ-telemetry-k8s-tests_istio/20047
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27335/integ-telemetry-k8s-tests_istio/20046
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27105/integ-telemetry-k8s-tests_istio/20045
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27362/integ-telemetry-k8s-tests_istio/20043

**Comment by douglas-reid** [comment]
Logs seem to have: `E0917 08:23:21.356753   91712 portforward.go:340] error creating error stream for port 46611 -> 9411: Timeout occured`

Did something change re: ports with the server?

**Comment by howardjohn** [comment]
Afaik the add-on deployment hasn't changed for quite some time - but possibly the port forwarding code did or the add-on is somehow crashing or something now?

I don't know exactly when this started but seems to be the last couple of days

**Comment by douglas-reid** [comment]
I'm seeing it in my PR now too. Something definitely broke. Seems to follow a pattern of zipkin taking ~30s to get ready and then immediate port-forward failures:

```
E0918 05:31:11.133763   52724 portforward.go:400] an error occurred forwarding 41155 -> 9411: error forwarding port 9411 to pod f075e86f3e9a79ac70968aeb37f4d54dfcceabc80a1f3019278ce9f487804eb7, uid : failed to execute portforward in network namespace "/var/run/netns/cni-55bd3b40-6467-08b4-fed3-6b53cdc636cd": failed to dial 9411: dial tcp4 127.0.0.1:9411: connect: connection refused
```

Did something change with the test infra?  The image itself hasn't been updated for months. Test grid only seems to have data for the last couple of runs.

**Comment by douglas-reid** [comment]
Weirder still: checking the logs of a PR that PASSED the test, I also see a failure to establish the port-forward.

```
=== RUN   TestClientTracing
2020-09-17T12:54:44.855892Z	info	tf	=== BEGIN: Test: 'telemetry_tracing_zipkin_clienttracing[TestClientTracing]' ===
    util.go:49: Sending traffic
...
E0917 12:54:44.877452   73123 portforward.go:400] an error occurred forwarding 42331 -> 9411: error forwarding port 9411 to pod a2aa093939873b1e0b0269e39d3c5e83769f84f1686f60622617b18e45a1e31d, uid : failed to execute portforward in network namespace "/var/run/netns/cni-0d208b8e-34ca-50e5-2e04-548efab28d92": failed to dial 9411: dial tcp4 127.0.0.1:9411: connect: connection refused
    util.go:49: Sending traffic
...
    tracing.go:119: got 0 child spans from, want 1 child spans, maybe trace has not be fully reported
    util.go:49: Sending traffic
...
2020-09-17T12:54:54.915071Z	info	tf	=== DONE (passed):  Test: 'telemetry_tracing_zipkin_clienttracing[TestClientTracing] (10.059172017s)' ===
--- PASS: TestClientTracing (10.06s)
```

**Comment by douglas-reid** [comment]
Seeing what adding a readiness probe might do to the tests: https://github.com/istio/istio/pull/27405

**Comment by howardjohn** [comment]
@douglas-reid we did upgrade to k8s 1.19 and kind 0.9.0 - could be related. I don't think anything else really changed though

**Comment by howardjohn** [comment]
Opened https://github.com/istio/test-infra/issues/2933 btw
