### ISSUE TITLE
Istio 1.7.1 unable to install Kiali addon

### ISSUE THREAD

**Issue by bseenu** [istio/istio#27417]
**Bug description**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[*] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**
/usr/local/istio-1.7.1/samples/addons  kubectl apply -f kiali.yaml                                                                                                                                                  
unable to recognize "kiali.yaml": no matches for kind "MonitoringDashboard" in version "monitoring.kiali.io/v1alpha1"
unable to recognize "kiali.yaml": no matches for kind "MonitoringDashboard" in version "monitoring.kiali.io/v1alpha1"
unable to recognize "kiali.yaml": no matches for kind "MonitoringDashboard" in version "monitoring.kiali.io/v1alpha1"
unable to recognize "kiali.yaml": no matches for kind "MonitoringDashboard" in version "monitoring.kiali.io/v1alpha1"
unable to recognize "kiali.yaml": no matches for kind "MonitoringDashboard" in version "monitoring.kiali.io/v1alpha1"
unable to recognize "kiali.yaml": no matches for kind "MonitoringDashboard" in version "monitoring.kiali.io/v1alpha1"
unable to recognize "kiali.yaml": no matches for kind "MonitoringDashboard" in version "monitoring.kiali.io/v1alpha1"
unable to recognize "kiali.yaml": no matches for kind "MonitoringDashboard" in version "monitoring.kiali.io/v1alpha1"
unable to recognize "kiali.yaml": no matches for kind "MonitoringDashboard" in version "monitoring.kiali.io/v1alpha1"
unable to recognize "kiali.yaml": no matches for kind "MonitoringDashboard" in version "monitoring.kiali.io/v1alpha1"
unable to recognize "kiali.yaml": no matches for kind "MonitoringDashboard" in version "monitoring.kiali.io/v1alpha1"
unable to recognize "kiali.yaml": no matches for kind "MonitoringDashboard" in version "monitoring.kiali.io/v1alpha1"
unable to recognize "kiali.yaml": no matches for kind "MonitoringDashboard" in version "monitoring.kiali.io/v1alpha1"
unable to recognize "kiali.yaml": no matches for kind "MonitoringDashboard" in version "monitoring.kiali.io/v1alpha1"
unable to recognize "kiali.yaml": no matches for kind "MonitoringDashboard" in version "monitoring.kiali.io/v1alpha1"
unable to recognize "kiali.yaml": no matches for kind "MonitoringDashboard" in version "monitoring.kiali.io/v1alpha1"
unable to recognize "kiali.yaml": no matches for kind "MonitoringDashboard" in version "monitoring.kiali.io/v1alpha1"
unable to recognize "kiali.yaml": no matches for kind "MonitoringDashboard" in version "monitoring.kiali.io/v1alpha1"
unable to recognize "kiali.yaml": no matches for kind "MonitoringDashboard" in version "monitoring.kiali.io/v1alpha1"
unable to recognize "kiali.yaml": no matches for kind "MonitoringDashboard" in version "monitoring.kiali.io/v1alpha1"

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
~  /usr/local/istio-1.7.1/bin/istioctl version --remote                                                                                                                                                             
client version: 1.7.1
control plane version: 1.7.1
data plane version: 1.7.1 (5 proxies)
 ~  kubectl version --short                                                                                                                                                                                 
Client Version: v1.18.0
Server Version: v1.17.9-eks-4c6976

**How was Istio installed?**
https://istio.io/latest/docs/setup/getting-started/

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS

**Comment by morvencao** [comment]
Can you reapply the yaml? the CRD is actually in the yaml file.

**Comment by ericvn** [comment]
I don't recall the specific error, but Kiali doesn't usually install with a single apply. See Info box on that page:
```
If there are errors trying to install the addons, try running the command again. There may be some timing issues which will be resolved when the command is run again.
```

**Comment by dwdraju** [comment]
Same on `1.7.3` also
```
:~/istio-1.7.3$ [master]$ kubectl apply -f samples/addons/kiali.yaml 
unable to recognize "samples/addons/kiali.yaml": no matches for kind "MonitoringDashboard" in version "monitoring.kiali.io/v1alpha1"
unable to recognize "samples/addons/kiali.yaml": no matches for kind "MonitoringDashboard" in version "monitoring.kiali.io/v1alpha1"
unable to recognize "samples/addons/kiali.yaml": no matches for kind "MonitoringDashboard" in version "monitoring.kiali.io/v1alpha1"
unable to recognize "samples/addons/kiali.yaml": no matches for kind "MonitoringDashboard" in version "monitoring.kiali.io/v1alpha1"
unable to recognize "samples/addons/kiali.yaml": no matches for kind "MonitoringDashboard" in version "monitoring.kiali.io/v1alpha1"
unable to recognize "samples/addons/kiali.yaml": no matches for kind "MonitoringDashboard" in version "monitoring.kiali.io/v1alpha1"
unable to recognize "samples/addons/kiali.yaml": no matches for kind "MonitoringDashboard" in version "monitoring.kiali.io/v1alpha1"
unable to recognize "samples/addons/kiali.yaml": no matches for kind "MonitoringDashboard" in version "monitoring.kiali.io/v1alpha1"
unable to recognize "samples/addons/kiali.yaml": no matches for kind "MonitoringDashboard" in version "monitoring.kiali.io/v1alpha1"
unable to recognize "samples/addons/kiali.yaml": no matches for kind "MonitoringDashboard" in version "monitoring.kiali.io/v1alpha1"
unable to recognize "samples/addons/kiali.yaml": no matches for kind "MonitoringDashboard" in version "monitoring.kiali.io/v1alpha1"
unable to recognize "samples/addons/kiali.yaml": no matches for kind "MonitoringDashboard" in version "monitoring.kiali.io/v1alpha1"
unable to recognize "samples/addons/kiali.yaml": no matches for kind "MonitoringDashboard" in version "monitoring.kiali.io/v1alpha1"
unable to recognize "samples/addons/kiali.yaml": no matches for kind "MonitoringDashboard" in version "monitoring.kiali.io/v1alpha1"
unable to recognize "samples/addons/kiali.yaml": no matches for kind "MonitoringDashboard" in version "monitoring.kiali.io/v1alpha1"
unable to recognize "samples/addons/kiali.yaml": no matches for kind "MonitoringDashboard" in version "monitoring.kiali.io/v1alpha1"
unable to recognize "samples/addons/kiali.yaml": no matches for kind "MonitoringDashboard" in version "monitoring.kiali.io/v1alpha1"
unable to recognize "samples/addons/kiali.yaml": no matches for kind "MonitoringDashboard" in version "monitoring.kiali.io/v1alpha1"
unable to recognize "samples/addons/kiali.yaml": no matches for kind "MonitoringDashboard" in version "monitoring.kiali.io/v1alpha1"
unable to recognize "samples/addons/kiali.yaml": no matches for kind "MonitoringDashboard" in version "monitoring.kiali.io/v1alpha1"
```

**Comment by ahowells** [comment]
I copied the CustomResourceDefinition from the samples/addons/kiali.yaml in  to the file samples/addons/crd.yaml and ran that in first:
crd.yaml content:
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: monitoringdashboards.monitoring.kiali.io
spec:
  group: monitoring.kiali.io
  names:
    kind: MonitoringDashboard
    listKind: MonitoringDashboardList
    plural: monitoringdashboards
    singular: monitoringdashboard
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true

Then ran the command kubectl apply -f samples/addons/crd.yaml
output: "customresourcedefinition.apiextensions.k8s.io/monitoringdashboards.monitoring.kiali.io created"
Then I reran kubectl apply -f samples/addons/kiali.yaml

**Comment by javajon** [comment]
Echoing @dwdraju. With the install:

`kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.7/samples/addons/kiali.yaml`

I see the same repeating error messages from Kiali with Istio version 1.7.0/1.7, 1.7.3/1,7 and 1.8.0-alpha.0/1.8

`unable to recognize "https://raw.githubusercontent.com/istio/istio/release-1.7/samples/addons/kiali.yaml": no matches for kind "MonitoringDashboard" in version "monitoring.kiali.io/v1alpha1"`

It worked back in August when I tested it with Istio 1.7.0/Kiali 1.7. 

However taking advice from @ahowells:

and submitting CustomResourceDefinition found in [khiali yaml](https://github.com/istio/istio/blob/master/samples/addons/kiali.yaml) seemed to work around the problem with Istio 1.7.3.

**Comment by howardjohn** [comment]
The getting started notes indicate that this may require running the command 2x. This is because of a long standing Kubectl bug/feature/quirk that applying a CRD and an instance of the CR may race. This is explicitly documented in https://preliminary.istio.io/latest/docs/setup/getting-started/#dashboard. I am not sure there is anything else we can do here beyond splitting it into 2 yaml files, which is the same result as running the command twice.

**Comment by kevinglasson** [comment]
Running the command 2x was not sufficient for me (I ran it many more than two times) I had to do as @ahowells suggested and split out the CRD and install that first.
