### ISSUE TITLE
Istio-operator build failed while building a docker image on mac without using the build-tools container.

### ISSUE THREAD

**Issue by abhioncbr** [istio/istio#27428]
**Bug description**
Istio-operator build failed while building a docker image on mac without using the build-tools container. It failed while copying the ` manifests` folder into the image. 
```bash
 % make docker.operator 

....
....
time (mkdir -p <path>/istio/out/linux_amd64/docker_build/docker.operator && cp -r <path>/istio/out/linux_amd64/operator manifests/ operator/docker/Dockerfile.operator <path>/istio/out/linux_amd64/docker_build/docker.operator && cd <path>/istio/out/linux_amd64/docker_build/docker.operator  && docker build --build-arg BASE_VERSION=1.8-dev.0 --build-arg BASE_DISTRIBUTION=default -t istio/operator:d503ee9143be98e2ef07d1392debafb69be2f5e6 -f Dockerfile.operator . ); 

Sending build context to Docker daemon  110.6MB
Step 1/9 : ARG BASE_DISTRIBUTION=default
Step 2/9 : ARG BASE_VERSION=latest
Step 3/9 : FROM docker.io/istio/base:${BASE_VERSION} as default
 ---> d2a19e18e853
Step 4/9 : FROM docker.io/istio/distroless:${BASE_VERSION} as distroless
 ---> a257d6bc8428
Step 5/9 : FROM ${BASE_DISTRIBUTION}
 ---> d2a19e18e853
Step 6/9 : COPY operator /usr/local/bin/
 ---> Using cache
 ---> 6482b739e5b4
Step 7/9 : COPY manifests/ /var/lib/istio/manifests/
COPY failed: stat /var/lib/docker/tmp/docker-builder304562813/manifests: no such file or directory

real    0m5.767s
user    0m1.021s
sys     0m0.841s
make: *** [docker.operator] Error 1
```

Did check the output folder and look like the `manifests` folder is missing however sub-folders of `manifests` are present in `docker.operator` folder. Attached is the image for reference. 

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[x] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
The docker operator image should be built without any error. 

**Steps to reproduce the bug**
1. change `BUILD_WITH_CONTAINER` value to any integer other than 1 in the file [Makefile.overrides.mk](https://github.com/istio/istio/blob/master/Makefile.overrides.mk#L21)
2. run command ` make docker.operator` on mac.

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**
MacOs

<img width="409" alt="make-docker-operator issue" src="https://user-images.githubusercontent.com/1076944/93717688-6f7d0180-fb45-11ea-8720-85f752b7fadd.png">

**Comment by abhioncbr** [comment]
Please assign this ticket to me as I am working on the fix.

**Comment by abhioncbr** [comment]
<img width="409" alt="make-docker-operator issue" src="https://user-images.githubusercontent.com/1076944/93717674-5bd19b00-fb45-11ea-9e87-fc5190cd5d4c.png">

**Comment by ericvn** [comment]
One just needs to remove the / at the end of the line: https://github.com/istio/istio/blob/master/tools/istio-docker.mk#L186

**Comment by abhioncbr** [comment]
Yeah, @ericvn. done with the changes, going to open the PR very soon. Thanks.
