### ISSUE TITLE
Implement “REPLACE" operation in the Envoyfilter API

### ISSUE THREAD

**Issue by zhaohuabing** [istio/istio#27425]
**Describe the feature request**

We want to use EnvoyFIlter API to add a Redis Proxy network filter in the listener, but it conflicts with the existing TCP proxy. Adding a "REPLACE" operation in the Envoyfilter API would solve this problem.

We can't use the Istio build-in Redis xDS implementation because it's too simple to support our Redis use case such as read policy and mirroring.

**Describe alternatives you've considered**

[ ] Docs
[ ] Installation
[*] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
#27426

**Comment by hzxuzhonghu** [comment]
@zhaohuabing What's the background of implementing Replace? Especially only for `NETWORK_FILTER` and `NETWORK_FILTER`, isn't `Remove` & `Add` satisfying you?

**Comment by zhaohuabing** [comment]
@hzxuzhonghu The original reason is the one in the description of this issue:

We want to use EnvoyFIlter API to add a Redis Proxy network filter in the listener, but it conflicts with the existing TCP proxy. Adding a "REPLACE" operation in the Envoyfilter API would solve this problem.

Basically, sometimes we need to replace the TCP proxy in the listener with a more specific filter.

**Comment by hzxuzhonghu** [comment]
Yeah, i understand it. What i am confused is can `Remove` and `Add` do that too?

**Comment by zhaohuabing** [comment]
The semantic of "Remove & Add" is not exactly the same as "Replace", because order matters in a filter chain.

**Comment by hzxuzhonghu** [comment]
Got it, how about InsertBefore/After

**Comment by zhaohuabing** [comment]
Might work. But then the "Replace" logic would depend on other filters in the filter chain. I prefer "Replace" because it‘s more elegant. Is there any reason we want to eliminate the "Replace" operation?

**Comment by zhaohuabing** [comment]
Currently, Aeraki is heavily using "Replace" operation to replace the default TCP filter with other filters to support other layer-7 protocols in Istion.

**Comment by hzxuzhonghu** [comment]
Not eliminate, just to be clear about the use case

**Comment by mandarjog** [comment]
@hzxuzhonghu replace is a cleaner version of merge, when you do not want merge semantics. Add-remove makes you handle handling, but replace does not.
