### ISSUE TITLE
Automatic injection function fails when the VM restart

### ISSUE THREAD

**Issue by ZhangJ-Roykin** [istio/istio#27439]
**Bug description**
Automatic injection function fails when the server machine restart

[ ] Docs
[*] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

[ ] Multi Cluster
[*] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

**Steps to reproduce the bug**

Step1 Turn off the machine and restart it, istio runs normally
$ kubectl get pods -n istio-system
NAME                                   READY   STATUS    RESTARTS   AGE
grafana-5f6f8cbf75-4jvx4               1/1     Running   4          29h
istio-egressgateway-8455c96498-dbhvr   1/1     Running   4          29h
istio-ingressgateway-c57d9d55-vb6l9    1/1     Running   4          29h
istio-tracing-9dd6c4f7c-5pgd8          1/1     Running   6          29h
istiod-79654b97c4-sdsnj                1/1     Running   0          31m
kiali-7fdddcb998-cj9vp                 1/1     Running   4          29h
prometheus-d78dbcffd-kqwrv             2/2     Running   8          29h

Step2 Enable automatic namespace injection
$ kubectl label namespace default istio-injection=enabled
namespace/default labeled

Step3 Check the pod status after a period of time
$ kubectl get pods
NAME                            READY   STATUS    RESTARTS   AGE
service-go-v2-dbd466685-whb2g   1/1     Running   0          11m

**Conclusion：The deployment service-go-v2 is not be injected the istio-proxy automatically**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
istioctl version：
$ istioctl version
client version: 1.5.0
control plane version: 1.5.0
data plane version: 1.5.0 (10 proxies)

kubectl version：v1.18.5

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**
HUAWEI CLOUD

**Comment by howardjohn** [comment]
Can you check with Kubernetes? I don't see how Istio could cause this - it seems more likely Kubernetes is not sending Istio the webhook request at all.

**Comment by howardjohn** [comment]
We do not have enough information to move forward with this.
