### ISSUE TITLE
can not install istio ok due to hpa invalid metrics

### ISSUE THREAD

**Issue by majorinche** [istio/istio#27450]
**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
istio version: 1.3

kubectl version --short
Client Version: v1.17.9
Server Version: v1.17.9

**How was Istio installed?**
installing istio in the process of kubeflow

```
[root@d0404 ~]# kubectl get hpa -n istio-system
NAME                    REFERENCE                          TARGETS         MINPODS   MAXPODS   REPLICAS   AGE
cluster-local-gateway   Deployment/cluster-local-gateway   unknown/80%   1         5         1          35m
istio-ingressgateway    Deployment/istio-ingressgateway    unknown/80%   1         5         1          35m
istio-pilot             Deployment/istio-pilot             unknown/80%   1         5         1          35m
istio-policy            Deployment/istio-policy            unknown/80%   1         5         1          35m
istio-telemetry         Deployment/istio-telemetry         unknown/80%   1         5         1          35m


[root@d0404 ~]# kubectl get pod -n istio-system | grep Con
istio-ingressgateway-7b5c9764b9-b8vlv    0/1     ContainerCreating   0          58m
istio-pilot-8579cdd889-nqdcs             0/2     ContainerCreating   0          58m
istio-policy-58c96c4b47-lzj4f            0/2     ContainerCreating   0          58m
istio-telemetry-6869488b54-4rml4         0/2     ContainerCreating   0          58m
```

it is always in ContainerCreating status, and find errors by kubectl get events

38m         Warning   FailedComputeMetricsReplicas   horizontalpodautoscaler/istio-telemetry                          invalid metrics (1 invalid out of 1), first error is: failed to get cpu utilization: unable to get metrics for resource cpu: no metrics returned from resource metrics API

**Comment by morvencao** [comment]
> no metrics returned from resource metrics API
Looks like this is more likely an issue of your metrics-server, not an istio issue, as a workaround you can disable HPA.

**Comment by howardjohn** [comment]
This should also not block container creation. Check `kubectl describe pod` on the containers spinning up to get more info. This version is no longer supported though, please reopen if you experience issues on 1.6+: https://istio.io/latest/news/support/announcing-1.4-eol-final/
