### ISSUE TITLE
grafana/prometheus crap out with multiple mixer

### ISSUE THREAD

**Issue by kidiyoor** [istio/istio#2746]
False data shown in Grafana dash board. The bellow continues dash is seen when only 2 APIs calls were made. 

<img width="1438" alt="screen shot 2018-01-22 at 4 12 11 pm" src="https://user-images.githubusercontent.com/6630096/35251221-0f0b3164-ff8f-11e7-809f-36e41ca5c206.png">

Ideally the 'Global Request Volume' should have subsided down to zero after the 2 API calls but it kept oscillating. 

I think this is because of multiple mixers and is related to https://github.com/istio/istio/issues/2531

**Comment by douglas-reid** [comment]
@kidiyoor can you try again with the recent updates to the prom config ? there should now be better HA mixer starting prom configuration in the repo (though the yaml files in the addon dir will need to be updated to point at the latest commits).

**Comment by kidiyoor** [comment]
I tried 0.6 Istio on k8s with multiple mixers and bookinfo sample. It looks like the issue is resolved in k8s.

However this solution - `https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/prometheus/templates/configmap.yaml` only works for k8s. For non k8s setup we might want to document how to change prometheus.yaml to make it work with multiple mixer.

**Comment by douglas-reid** [comment]
@kidiyoor agreed. what do you think the best way is to do that? in HA mixer docs? in a separate doc about metrics?  what makes the most sense to you?

I also want to start a doc on prom replication and grafana session-affinity.

**Comment by ldemailly** [comment]
cute subject :)

**Comment by kidiyoor** [comment]
Since there is no a one standard way of doing this outside k8s - **eg.** for consul something like this can be done - [link](https://www.robustperception.io/finding-consul-services-to-monitor-with-prometheus/). I think a separate doc that talk about the problem and 'reference to solution' or 'solution' while running Istio in 'popular platform' or while running in 'bare VM' should be good.

**Comment by douglas-reid** [comment]
I'm going to close this issue, as we have a working solution for k8s. We should track non-k8s environments separately, as there are likely a host of issues around deployment of add-ons etc.
