### ISSUE TITLE
Not coherent timestamps of istio-proxy compared to corresponding requests on upstream apps

### ISSUE THREAD

**Issue by vbontempi** [istio/istio#27469]
We are using Istio on IBM Cloud kubernetes cluster
We configured istio to manage incoming traffic through gateway/virtualservice routing to the expected service

Trying to investigate a failed HTTP request with HTTP 503 as response code I found that the timestamps of istio-proxy logs aren't synchronized with the related logs on the upstream application for the same request

For example:

```
Sep 22 16:09:17 ghost-api-754dd9d6dd-g5pj2ghost-api INFO traceRequest - starting request startTime 2020-09-22T14:09:17.900Z IP ::ffff:127.0.0.1 path /v2/resources/search?account_id=... method POST headers {
  ...
  "user-agent": "PlatformAPI/RestClient workflow-api-cloud-test-dal10-live:workflow-api-f76bc857f-4n9vt:2.0.1-20200916-125527-v2.8-547 add9fd4348954ad181c75fed607e0e9b:5b1e5fa97d516c51",
  "trace": "add9fd4348954ad181c75fed607e0e9b:5b1e5fa97d516c51",
  "x-global-transaction-id": "add9fd4348954ad181c75fed607e0e9b:5b1e5fa97d516c51",
  "x-request-id": "449c3ab4-76cb-4382-9034-835346090877",
  "x-transaction-id": "add9fd4348954ad181c75fed607e0e9b:5b1e5fa97d516c51",
 ...
  "x-envoy-external-address": "10.185.163.187",
  "x-envoy-attempt-count": "2",
  ...

Sep 22 16:09:18 ghost-api-754dd9d6dd-g5pj2 istio-proxy "POST /v2/resources/search?account_id=... HTTP/1.1" 200 - "-" "-" 113 1733 88 79 "...10.185.163.187" "PlatformAPI/RestClient workflow-api-cloud-test-dal10-live:workflow-api-f76bc857f-4n9vt:2.0.1-20200916-125527-v2.8-547 add9fd4348954ad181c75fed607e0e9b:5b1e5fa97d516c51" "449c3ab4-76cb-4382-9034-835346090877" ... inbound|3000|http-ghost-api-port|ghost-api-service.ghost.svc.cluster.local 127.0.0.1:57922 172.30.83.153:3000 10.185.163.187:0 outbound_.3000_._.ghost-api-service.ghost.svc.cluster.local default

Sep 22 16:09:19 istio-ingressgateway-7f989c955c-gmw5w istio-proxy "POST /v2/resources/search?account_id=... HTTP/1.1" 200 - "-" "-" 113 1733 170 161 "...10.185.163.187" "PlatformAPI/RestClient workflow-api-cloud-test-dal10-live:workflow-api-f76bc857f-4n9vt:2.0.1-20200916-125527-v2.8-547 add9fd4348954ad181c75fed607e0e9b:5b1e5fa97d516c51" "449c3ab4-76cb-4382-9034-835346090877" ... "172.30.83.153:3000" outbound|3000||ghost-api-service.ghost.svc.cluster.local 172.30.77.74:39318 172.30.77.74:8443 10.185.163.187:38705 ... -

Sep 22 16:09:23 ghost-api-754dd9d6dd-wb95w istio-proxy "POST /v2/resources/search?account_id=... HTTP/1.1" 503 UC "-" "-" 113 95 58 - "...10.185.163.187" "PlatformAPI/RestClient workflow-api-cloud-test-dal10-live:workflow-api-f76bc857f-4n9vt:2.0.1-20200916-125527-v2.8-547 add9fd4348954ad181c75fed607e0e9b:5b1e5fa97d516c51" "449c3ab4-76cb-4382-9034-835346090877" ... "127.0.0.1:3000" inbound|3000|http-ghost-api-port|ghost-api-service.ghost.svc.cluster.local 127.0.0.1:50868 172.30.162.29:3000 10.185.163.187:0 outbound_.3000_._.ghost-api-service.ghost.svc.cluster.local default

}
```

The log of the upstream application `ghost-api-service` has timestamp Sep 22 16:09:17 and as shown by the header `"x-envoy-attempt-count": "2"` is the second attempt of the istio-proxy to forward the request
But the istio-proxy logs have an earlier timestamp, even if we would expect to be processed in advance of the upstream one:
- Sep 22 16:09:18 is the timestamp of the second istio-proxy trace, the one that managed to reach the upstream service and returned HTTP 200 to the caller
- Sep 22 16:09:19 is the timestamp of the same on the istio-ingressgateway
- Sep 22 16:09:23 is the timestamp of the first attempt of the istio-proxy, getting HTTP 503 by the upstream with UC as response flag (`Upstream connection termination in addition to 503 response code`)

So summarising the first request going through the istio gateway has a timestamp of 5 seconds later the trace related with the second attempt of the istio-proxy to forward the request to the upstream
This makes uneasy to debug/investigate the flow of requests and we would like to understand if it is an expected behaviour or there is any misconfiguration in the way istio pods are synchronized with the other cluster pods.

**Comment by linsun** [comment]
First of all, this doesn't happen in normal cases when everything works.  The logs should reflect to the call sequences.

It would be helpful to get timestamp of when initial req and first req comes in. It is possible they both hit 503 but 503 comes later after some timeout thus retries are attempted.

**Comment by vbontempi** [comment]
The requestID 449c3ab4-76cb-4382-9034-835346090877 is the Id of the request set by istio and the logs I reported are the ones for this request.
Looking at the timestamps sequence my concern is on the trace of the HTTP 503 traced for the istio-proxy container: the response to the caller has been returned as HTTP 200 (log of 16:09:19 from istio-gateway) so it has been returned after the second attempt of the proxy to call the upstream; the first got the HTTP 503 and the proxy performed a further request with header `"x-envoy-attempt-count": "2"`
So the logs sequence according to the timestamps is correct and logic, with the exception of the first failed request that is traced with a timestamp of 5 seconds later something that has been triggered due to the failure of the same: I would like to understand if is an expected behaviour and if so why this happens, because the logic expectation would be to have the first failure with HTTP 503 traced with a timestamp older than the new attempt
Even if it timed out, I would expect the re-try to be triggered after the timeout.

How could we identify the very first trace of this request?
If I filter by the request ID 449c3ab4-76cb-4382-9034-835346090877 I get only the entries I am showing in this issue

**Comment by linsun** [comment]
Can you please supply all the relevant logs?  I think you are looking at ingress gw and the sidecar proxy log of your service (ghost-api)?

Also, please supply your gw/vs/dr resources as well.  Can you confirm your ghost-api service isn't doing any app-level timeout or retry?

If you have jaeger running (highly recommended), it would be best to view this request via Jaeger as it shows how times are spent on each trace spans.
