### ISSUE TITLE
Gateway 404: add NR flag

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#27471]
For sidecars without a match, we get a NR flag. For GW we do a direct 4040 so we do not get this:

```
      "virtual_hosts": [
       {
        "name": "blackhole:443",
        "domains": [
         "*"
        ],
        "routes": [
         {
          "match": {
           "prefix": "/"
          },
          "direct_response": {
           "status": 404
          },
          "name": "default"
         }
        ]
       }
      ],
```

We should see if we can manually add it, or maybe we can just send an empty route list and implicitly get it?

**Comment by howardjohn** [comment]
@kyessenov any thoughts?

**Comment by kyessenov** [comment]
Don't we get direct response flag?

**Comment by howardjohn** [comment]
I see `[2020-09-22T18:44:44.041Z] "GET / HTTP/2" 404 - "-" 0 0 0 - "10.244.0.1" "curl/7.72.0" "58826902-f269-4058-813b-8f888a8f3595" "172.17.0.2:31264" "-" - - 10.244.0.6:8443 10.244.0.1:30845 - default`

**Comment by mandarjog** [comment]
There is a PR to add `response_flag` to direct response. @gargnupur what is the status of that issue?

**Comment by mandarjog** [comment]
looks like https://github.com/envoyproxy/envoy/pull/10761 got closed ...

**Comment by howardjohn** [comment]
I think we can do it without that patch. I'll test it out

**Comment by gargnupur** [comment]
Need to revive envoyproxy/envoy#10761.. there were some proto versioning issues there...

**Comment by howardjohn** [comment]
I tested making https://github.com/istio/istio/blob/0e8aebca29dc1dd0df1af01e5701176f39fb7d43/pilot/pkg/networking/core/v1alpha3/gateway.go#L291 return empty list. Seems behavior is 404+NR. If there isn't any reason we should not do that, I will send a PR in a bit

**Comment by kyessenov** [comment]
Honestly, I have no idea why it was doing direct 404. It makes little sense to me.
