### ISSUE TITLE
http2MaxRequests seems incorrectly named

### ISSUE THREAD

**Issue by christian-posta** [istio/istio#27473]
In a destinationrule, we can control connection pool limits including things like max pending requests, etc. there is a setting called `http2MaxRequests` which limits the number of requests for H2 connections.  the code explicitly says this as well:

```
		if settings.Http.Http2MaxRequests > 0 {
			// Envoy only applies MaxRequests in HTTP/2 clusters
			threshold.MaxRequests = &wrappers.UInt32Value{Value: uint32(settings.Http.Http2MaxRequests)}
		}
```
https://github.com/istio/istio/blob/2f69299aafb4c720658ba3a7331eb4884dcffe21/pilot/pkg/networking/core/v1alpha3/cluster.go#L661

I see in the Envoy documentation, however, that `max_requests` for the circuit breaker thresholds (https://www.envoyproxy.io/docs/envoy/v1.15.0/api-v3/config/cluster/v3/circuit_breaker.proto#config-cluster-v3-circuitbreakers-thresholds) says:

```
The maximum number of parallel requests that Envoy will make to the upstream cluster. If not specified, the default is 1024.
```

Envoy doc doesn't say anything specifically about H2.

In my tests, indeed I see this `max_requests` field has implications for H1.1 requests as well.

Can someone please help me understand the discrepancy and why this config settings is explicitly called `http2` etc if it affects HTTP 1.1 as well?

**Comment by howardjohn** [comment]
@rshriram any idea? did this change in Envoy maybe?

**Comment by ramaraochavali** [comment]
Good catch @christian-posta 

Yes. Envoy implementation has changed to support both h1 and h2 https://github.com/envoyproxy/envoy/issues/9215 via this PR https://github.com/envoyproxy/envoy/pull/9668. 

May be we should deprecate `Http2MaxRequests` and rename it to `HttpMaxRequests`

**Comment by frittentheke** [comment]
@howardjohn @christian-posta  @ramaraochavali 

 I know this issue timed out quite a while ago ... but isn't it still valid to align the naming of these two options: 

- `http1MaxPendingRequests` -> `maxPendingRequests` (~ queue length)
- `Http2MaxRequests`  -> `maxRequests` (~ concurrency limit) (already proposed via https://github.com/istio/api/pull/1871)


since Envoy has removed the distinction between HTTP/1 and HTTP/2 with https://github.com/envoyproxy/envoy/issues/9215 years ago?

**Comment by ramaraochavali** [comment]
As discussed in the API PR, we have to support both the fields and deprecate the old one

**Comment by frittentheke** [comment]
> As discussed in the API PR, we have to support both the fields and deprecate the old one

@ramaraochavali do you have plans to start the renaming? I just had another occasion where the naming confused.

**Comment by ramaraochavali** [comment]
Yes. I can get to it later this week or early next week

**Comment by iankemp-CapitalOnTap** [comment]
> Yes. I can get to it later this week or early next week

Did you ever get to it?

**Comment by ramaraochavali** [comment]
Sorry I could not. If you have time, please propose the API
