### ISSUE TITLE
Connection to external service issue with istio in 1.5.2 till 1.7.1

### ISSUE THREAD

**Issue by nataraj24** [istio/istio#27487]
Opening this new thread as the issue #24575 got closed.  This issue persists from istio version 1.5.2 to 1.7.1.

**Comment by howardjohn** [comment]
Please post a config dump with more information about your setup, including if you use a ServiceEntry for the externasl service, what protocol is used, etc: https://github.com/istio/istio/wiki/Troubleshooting-Istio

**Comment by nataraj24** [comment]
Hi @howardjohn 

Please find attached config-dump json.  We arent using ServiceEntry in our deployment.  

We are using Kubernetes service and endpoint mechanism to connect to database which is outside kubernetes cluster
[config_dump.zip](https://github.com/istio/istio/files/5275731/config_dump.zip)

**Comment by howardjohn** [comment]
Can you attach the service spec? I think you need to define the protocol explicitly to be TCP and it should work: https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/#automatic-protocol-selection. Normally we can automatically detect but I think you are hitting a case where it doesn't work which we haven't yet documented (we are doing a major rehual of this doc in the next release).

**Comment by nataraj24** [comment]
Thank you prompt reply.  i am setting the protocol  below are yaml definitions of service and endpoint through which the database is getting connected

kind: Service
apiVersion: v1
metadata:
  name: "{{ db_svc_name }}" 
  namespace: "{{ ns_name }}"
spec:
  ports:
  - protocol: TCP
    port: {{ db_port }} 
    targetPort: {{ db_port }}

apiVersion: v1
kind: Endpoints
metadata:
 name: "{{ db_svc_name }}" 
 namespace: "{{ ns_name }}"
subsets:
 - addresses:
     - ip: {{ db_server_ip }} 
   ports:
     - port: {{ db_port }}

**Comment by howardjohn** [comment]
You are not setting the protocol for Istio - that is the k8s protocol which
is only tcp/udp. You need to set the port name to tcp. Take a look at the
doc I linked for more info.

**Comment by nataraj24** [comment]
Hi @howardjohn 

No its still not working.  i had specified the name as tcp in the service.  also i had reinstalled istio with --set values.pilot.enableProtocolSniffingForOutbound=false.

 ports:
  - name: tcp
    protocol: TCP
    port: {{ db_port }}
    targetPort: {{ db_port }}

**Comment by howardjohn** [comment]
this should work, can you get another config dump with the changes and post the envoy access logs maybe

**Comment by nataraj24** [comment]
[2020-09-25T03:17:51.120Z] "- - -" 0 UH "-" "-" 0 0 0 - "-" "-" "-" "-" "-" - - 10.97.156.145:6501 10.244.1.88:46808 - -
[2020-09-25T03:17:51.121Z] "- - -" 0 UH "-" "-" 0 0 0 - "-" "-" "-" "-" "-" - - 10.97.156.145:6501 10.244.1.88:46810 - -
[2020-09-25T03:17:51.121Z] "- - -" 0 UH "-" "-" 0 0 0 - "-" "-" "-" "-" "-" - - 10.97.156.145:6501 10.244.1.88:46812 - -
[2020-09-25T03:17:51.122Z] "- - -" 0 UH "-" "-" 0 0 0 - "-" "-" "-" "-" "-" - - 10.97.156.145:6501 10.244.1.88:46814 - -
[2020-09-25T03:17:51.123Z] "- - -" 0 UH "-" "-" 0 0 0 - "-" "-" "-" "-" "-" - - 10.97.156.145:6501 10.244.1.88:46816 - -
[2020-09-25T03:17:51.123Z] "- - -" 0 UH "-" "-" 0 0 0 - "-" "-" "-" "-" "-" - - 10.97.156.145:6501 10.244.1.88:46818 - -
[2020-09-25T03:17:51.124Z] "- - -" 0 UH "-" "-" 0 0 0 - "-" "-" "-" "-" "-" - - 10.97.156.145:6501 10.244.1.88:46820 - -
[2020-09-25T03:17:51.124Z] "- - -" 0 UH "-" "-" 0 0 0 - "-" "-" "-" "-" "-" - - 10.97.156.145:6501 10.244.1.88:46822 - -
[2020-09-25T03:17:51.125Z] "- - -" 0 UH "-" "-" 0 0 0 - "-" "-" "-" "-" "-" - - 10.97.156.145:6501 10.244.1.88:46824 - -
[2020-09-25T03:17:51.126Z] "- - -" 0 UH "-" "-" 0 0 0 - "-" "-" "-" "-" "-" - - 10.97.156.145:6501 10.244.1.88:46826 - -
[2020-09-25T03:17:51.126Z] "- - -" 0 UH "-" "-" 0 0 0 - "-" "-" "-" "-" "-" - - 10.97.156.145:6501 10.244.1.88:46828 - -
[2020-09-25T03:17:51.127Z] "- - -" 0 UH "-" "-" 0 0 0 - "-" "-" "-" "-" "-" - - 10.97.156.145:6501 10.244.1.88:46830 - -
[2020-09-25T03:17:51.127Z] "- - -" 0 UH "-" "-" 0 0 0 - "-" "-" "-" "-" "-" - - 10.97.156.145:6501 10.244.1.88:46832 - -
[config_dump-25092020.zip](https://github.com/istio/istio/files/5280514/config_dump-25092020.zip)

**Comment by howardjohn** [comment]
Looks like you have mTLS configurated for the DB, which I assume doesn't support it. You must have some Destinationrule for this that is incorrect.

**Comment by nataraj24** [comment]
Hi @howardjohn 

Still no luck.  Earlier i used create one destination rule "*.k8s.svc.cluster.local" now i am creating separate destination rules for each service and please find below dr for database

spec:
  host: db-svc.k8s.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE

its still giving same error in application and proxy access logs.

Please find attached config dump also
[config_dump-28092020.zip](https://github.com/istio/istio/files/5290069/config_dump-28092020.zip)

**Comment by howardjohn** [comment]
@nataraj24 is there any way we can reproduce this? 

One other thing to check is the `:15000/clusters` output (or `istioctl pc endpoint`). You should see the IP of the database there. if it doesn't show up, that is the issue.

**Comment by nataraj24** [comment]
Hi @howardjohn 

Its issue with any external service so it can be easily reproduced.  One can create simple service and endpoint with any database being outside.  In istio 1.6.x onwards this issue is coming even without mTLS enabled in istio.  

Also please find attached cluster information of the pod which has been requested and it didn't had database IP 

Below is the cluster information file which is retrieved from pod

outbound|6501||db-svc.k8s.svc.cluster.local::default_priority::max_connections::4294967295
outbound|6501||db-svc.k8s.svc.cluster.local::default_priority::max_pending_requests::4294967295
outbound|6501||db-svc.k8s.svc.cluster.local::default_priority::max_requests::4294967295
outbound|6501||db-svc.k8s.svc.cluster.local::default_priority::max_retries::4294967295
outbound|6501||db-svc.k8s.svc.cluster.local::high_priority::max_connections::1024
outbound|6501||db-svc.k8s.svc.cluster.local::high_priority::max_pending_requests::1024
outbound|6501||db-svc.k8s.svc.cluster.local::high_priority::max_requests::1024
outbound|6501||db-svc.k8s.svc.cluster.local::high_priority::max_retries::3
outbound|6501||db-svc.k8s.svc.cluster.local::added_via_api::true

[clusters.zip](https://github.com/istio/istio/files/5296278/clusters.zip)

**Comment by howardjohn** [comment]
ok well that is clearly the issue - no IPs.

Can you please provide the EXACT config to reproduce it?

I ran with:

```
kind: Service
apiVersion: v1
metadata:
  name: db-svc
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  name: db-svc
subsets:
- addresses:
  - ip: 34.194.129.11
  ports:
  - port: 80
```

(IP is httpbin.org IP), and everything works fine. So I think there is something specific about your configuration.

**Comment by nataraj24** [comment]
Hi @howardjohn 

Please find exact service and endpoint information for database which is used in the cluster.  Kindly let me know if you need any other details i will be able to provide to solve the issue.

[Configuration.zip](https://github.com/istio/istio/files/5303255/Configuration.zip)

**Comment by AEGQ** [comment]
![image](https://user-images.githubusercontent.com/16302289/94655262-e29a2b00-0330-11eb-9ef7-d4106b7d303b.png)
have a  try ?

**Comment by howardjohn** [comment]
I applied config:
```yaml
kind: Service
apiVersion: v1
metadata:
  name: db-svc
spec:
  ports:
  - protocol: TCP
    port: 6501
    targetPort: 6501
    name: tcp
---
apiVersion: v1
kind: Endpoints
metadata:
  name: db-svc
subsets:
- addresses:
  - ip: 52.47.209.216
  ports:
  - port: 6501
    protocol: TCP
    name: tcp
```

Then send curl: `curl db-svc:6501` and it works fine..

**Comment by nataraj24** [comment]
Hi @howardjohn 

Perfect.  its working now.  Can you please clarify on the two below points.

- its working only when we specify protocol in Endpoint definition.  Mentioning of protocol information for endpoint  is not there in k8s document as well.  what is the dependency of this in istio

- do we need to specify protocol when we create database service for ExternalName as well.  In AWS and Azure environments we are using ExternalName service. does istio depend on protocol for ExternalName.

Thanks,
Nataraj

**Comment by howardjohn** [comment]
```diff
  kind: Service
  apiVersion: v1
  metadata:
    name: db-svc
  spec:
    ports:
    - protocol: TCP
      port: 6501
      targetPort: 6501
      name: tcp
  ---
  apiVersion: v1
  kind: Endpoints
  metadata:
    name: db-svc
  subsets:
  - addresses:
    - ip: 52.47.209.216
    ports:
    - port: 6501
-     protocol: TCP
      name: tcp
```

You mean like this? that still seems to work for me.

We definitely depend on the *name* in Service: https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/. But shouldn't depend on the protocol. Unless we filter out unset protocol because we support only TCP and check `== TCP` somewhere instead of `!= UDP`, but like I mentioned it seemed to work for me so I was a bit confused which change broke things for you. Let me know, thanks!

**Comment by nataraj24** [comment]
Hi @howardjohn 

The change which has worked is name in Endpoint definition as mentioned below.  

subsets:
 - addresses:
     - ip: {{ db_server_ip }}
   ports:
     - port: {{ db_port }}
       **name: tcp**

**Comment by howardjohn** [comment]
The name in the endpoint has to match the name in the service. I will test if this is true without istio maybe our port matching logic is different. Thanks for the clarification

**Comment by nataraj24** [comment]
Hi @howardjohn 

can you please confirm why istio is expecting "- name: tcp" in endpoint definition.

**Comment by howardjohn** [comment]
This is how Kubernetes works. Try this snippet WITHOUT ISTIO:
```yaml
kind: Service
apiVersion: v1
metadata:
  name: db-svc
spec:
  ports:
  - protocol: TCP
    port: 6501
    targetPort: 6501
    name: tcp
---
apiVersion: v1
kind: Endpoints
metadata:
  name: db-svc
subsets:
- addresses:
  - ip: 52.47.209.216
  ports:
  - port: 6501
    protocol: TCP
``

(note the lack of name). 

The request will fail. Add name, and it works.

Closing as this is working as intended and follows kubernetes spec:
```
   name <string>
     The name of this port (corresponds to ServicePort.Name). Must be a
     DNS_LABEL. Optional only if one port is defined.
```
