### ISSUE TITLE
Support the holdApplicationUntilProxyStarts setting per deployment

### ISSUE THREAD

**Issue by rolandkool** [istio/istio#27508]
**Describe the feature request**
The recently added `holdApplicationUntilProxyStarts` feature (see https://github.com/istio/istio/pull/24737) can only be set globally and not per deployment. Our default approach is to use `scuttle`, but that does involve changing the image. This may not always be feasible so it would help to use this setting for specific deployments using images we can't modify.

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Comment by howardjohn** [comment]
related: https://github.com/istio/istio/issues/26923

**Comment by howardjohn** [comment]
fixed by https://github.com/istio/istio/issues/26923
