### ISSUE TITLE
Istio Ingress with AWS ELB result in backend connection errors

### ISSUE THREAD

**Issue by jdomag** [istio/istio#27505]
**Bug description**
I've deployed istio ingress gateway with AWS ELB and since then i observe a lot of "backend connection errors' on AWS ELB monitoring dashboard.

![image](https://user-images.githubusercontent.com/28705876/94147640-d6682680-fe75-11ea-99b3-af59ddd50d5a.png)

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
0 backend connection errors

**Steps to reproduce the bug**
Install k8s 1.16.15 with kops and istio 1.6.5 with ingress gateway 

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
```
istioctl version --remote                                                             
client version: 1.6.5
control plane version: 1.6.5
data plane version: 1.6.5 (67 proxies)

```
```
kubectl version                                               
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"ec6eb119b81be488b030e849b9e64fda4caaf33c", GitTreeState:"clean", BuildDate:"2020-03-12T21:00:06Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.15", GitCommit:"2adc8d7091e89b6e3ca8d048140618ec89b39369", GitTreeState:"clean", BuildDate:"2020-09-02T11:31:21Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
**How was Istio installed?**
istioctl with custom profile

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS

**Comment by howardjohn** [comment]
We need more info to debug this further, for example how to reproduce it, the logs from the pod (with access logs, see https://github.com/istio/istio/wiki/Troubleshooting-Istio), etc. Right now this issue is not possible to move forward.

**Comment by MatteoMori** [comment]
I am having the same problem
https://github.com/istio/istio/issues/29079
