### ISSUE TITLE
Global setting to exclude outbound traffic from sidecar

### ISSUE THREAD

**Issue by a8j8i8t8** [istio/istio#27510]
**Describe the feature request**
We're on Istio 1.7.2. We're getting database connection issue to external AWS RDS instance. We're getting SSL error `((psycopg2.OperationalError) SSL SYSCALL error: EOF detected)` randomly. When searched for a bit we stumbled upon [this thread.](https://github.com/istio/istio/issues/17139). We're still analysing the issue. But our initial assumption is Istio may be the reason for this error.

Is there a way to set `traffic.sidecar.istio.io/excludeOutboundPorts: 5432` globally for our mesh.

Cheers,
~Ajit
**Describe alternatives you've considered**

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by howardjohn** [comment]
Yes, `--set .values.global.proxy.excludeOutboundPorts` will configure the same globally
