### ISSUE TITLE
upstream connect error or disconnect/reset before headers. reset reason: connection termination

### ISSUE THREAD

**Issue by omerfsen** [istio/istio#27513]
**Bug description**

When I deploy a service after some point I am getting 

**upstream connect error or disconnect/reset before headers. reset reason: connection termination** error. It is random and i have found out that it only happens (not all the time) but if i got error it is definitely after this line connection is no more.

kubectl logs -n namespace $POD  -c istio-proxy 

```
2020-09-24T17:12:35.507004Z     warning envoy config    [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:92] StreamAggregatedResources gRPC config stream closed: 13, 
```

Also after getting this error and can't connect to my Istio endpoint/service, 30 minutes later (roughly) i get this line 

```
2020-09-24T17:43:49.473767Z     warning envoy config    [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:92] StreamAggregatedResources gRPC config stream closed: 13,
```

connection is reinstated and i can connect the service again. It does not happen all the time but when it happens it lasts 30 min exact time to be connection reinstated.

I made a curl test every 30 seconds and it starts at 2020-09-24-17-12 and finishes at 2020-09-24-17-43 

```
tracing-rest-checker-pg8hp tracing-rest-checker 2020-09-24-17-11
tracing-rest-checker-pg8hp tracing-rest-checker {"data":{"names":["proba"],"ndarray":[[0.39731466202150834]]},"meta":{}}
tracing-rest-checker-pg8hp tracing-rest-checker
tracing-rest-checker-pg8hp tracing-rest-checker ################################################################################
tracing-rest-checker-pg8hp tracing-rest-checker ################################################################################
tracing-rest-checker-pg8hp tracing-rest-checker 2020-09-24-17-12
tracing-rest-checker-pg8hp tracing-rest-checker {"data":{"names":["proba"],"ndarray":[[0.39731466202150834]]},"meta":{}}
tracing-rest-checker-pg8hp tracing-rest-checker
tracing-rest-checker-pg8hp tracing-rest-checker ################################################################################
tracing-rest-checker-pg8hp tracing-rest-checker ################################################################################
tracing-rest-checker-pg8hp tracing-rest-checker 2020-09-24-17-12
tracing-rest-checker-pg8hp tracing-rest-checker upstream connect error or disconnect/reset before headers. reset reason: connection termination
tracing-rest-checker-pg8hp tracing-rest-checker ################################################################################
tracing-rest-checker-pg8hp tracing-rest-checker ################################################################################
tracing-rest-checker-pg8hp tracing-rest-checker 2020-09-24-17-13
tracing-rest-checker-pg8hp tracing-rest-checker upstream connect error or disconnect/reset before headers. reset reason: connection termination
tracing-rest-checker-pg8hp tracing-rest-checker ################################################################################
tracing-rest-checker-pg8hp tracing-rest-checker ################################################################################
...
...
...
tracing-rest-checker-pg8hp tracing-rest-checker ################################################################################
tracing-rest-checker-pg8hp tracing-rest-checker 2020-09-24-17-42
tracing-rest-checker-pg8hp tracing-rest-checker upstream connect error or disconnect/reset before headers. reset reason: connection termination
tracing-rest-checker-pg8hp tracing-rest-checker ################################################################################
tracing-rest-checker-pg8hp tracing-rest-checker ################################################################################
tracing-rest-checker-pg8hp tracing-rest-checker 2020-09-24-17-43
tracing-rest-checker-pg8hp tracing-rest-checker upstream connect error or disconnect/reset before headers. reset reason: connection termination
tracing-rest-checker-pg8hp tracing-rest-checker ################################################################################
tracing-rest-checker-pg8hp tracing-rest-checker ################################################################################
tracing-rest-checker-pg8hp tracing-rest-checker 2020-09-24-17-43
tracing-rest-checker-pg8hp tracing-rest-checker upstream connect error or disconnect/reset before headers. reset reason: connection termination
tracing-rest-checker-pg8hp tracing-rest-checker ################################################################################
tracing-rest-checker-pg8hp tracing-rest-checker ################################################################################
tracing-rest-checker-pg8hp tracing-rest-checker 2020-09-24-17-44
tracing-rest-checker-pg8hp tracing-rest-checker {"data":{"names":["proba"],"ndarray":[[0.39731466202150834]]},"meta":{}}
tracing-rest-checker-pg8hp tracing-rest-checker
tracing-rest-checker-pg8hp tracing-rest-checker ################################################################################
tracing-rest-checker-pg8hp tracing-rest-checker ################################################################################
tracing-rest-checker-pg8hp tracing-rest-checker 2020-09-24-17-44
tracing-rest-checker-pg8hp tracing-rest-checker {"data":{"names":["proba"],"ndarray":[[0.39731466202150834]]},"meta":{}}
tracing-rest-checker-pg8hp tracing-rest-checker
tracing-rest-checker-pg8hp tracing-rest-checker ################################################################################
````

Based on the suggestion I also got the before and after proxy config dump with

```
 while true ; do  kubectl exec -n istio-system  $(kubectl get pods -n istio-system -l app=istiod -o name) -- curl 'localhost:8080/debug/config_dump?proxyID=tracing-and-logging-rest-tracing-0-model1-865b5596fd-jl2vp.emtech'  > after/after_config_dump.txt-$(date -d '1 hour ago' +%Y-%m-%d-%H-%M); sleep 300;  done
```

Details logs are attached

[istio-bug.zip](https://github.com/istio/istio/files/5278217/istio-bug.zip)

[ ] Docs
[ ] Installation
[ X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ X] User Experience
[ ] Developer Infrastructure

**Expected behavior**
To be able to connect endpoint all the time.

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
$ istioctl version --remote
client version: 1.6.8
control plane version: 1.6.8
data plane version: 1.6.8 (7 proxies)
$  kubectl version --short
Client Version: v1.18.6
Server Version: v1.16.13

**How was Istio installed?**
istioctl install 

**Environment where bug was observed (cloud vendor, OS, etc)**
I have seen this bug on 

AWS EKS 1.17 
Kind 1.17 Cluster (onprem)
Azure AKS 1.16

**Comment by omerfsen** [comment]
@howardjohn   as you requested on https://github.com/istio/istio/issues/19321  also @marziman  can be interested on this too

**Comment by omerfsen** [comment]
You can do


```
git diff after/after_config_dump.txt-2020-09-24-17-40  after/after_config_dump.txt-2020-09-24-17-45
```
to get what has changed to fix connection as connection is reinstated at 2020-09-24-17-43 at 49th seconds.

**Comment by omerfsen** [comment]
is related https://github.com/istio/istio/issues/19321

**Comment by marziman** [comment]
@howardjohn do you think we can get help in this new issue? As you requested to create a new one, @omerfsen was so kind to do so.
I know you are all busy, but it would be a big help if you guys take a look 🙏🏻
cc @chadlwilson

**Comment by marziman** [comment]
@puneetloya @a8j8i8t8 this shall be the right issue, as I saw you observed this too

**Comment by howardjohn** [comment]
> Every ca. 30minutes we have a TCP disconnect and our mongo database fails with exception (Got socket exception on connection )

Is it a 1 time disconnect, or is it broken for 30 mins then recovers? These are very different problems. Both of them it is useful to get a diff of the config berfore and after

**Comment by omerfsen** [comment]
> > Every ca. 30minutes we have a TCP disconnect and our mongo database fails with exception (Got socket exception on connection )
> 
> 
> 
> Is it a 1 time disconnect, or is it broken for 30 mins then recovers? These are very different problems. Both of them it is useful to get a diff of the config berfore and after

My issue was it is broken for 30 min then recovers and after some time it is down again for 30 min and recovers again

**Comment by omerfsen** [comment]
@christian-posta Can i get your opinion on this? Have you came across in the field?

**Comment by marziman** [comment]
Is someone looking into this from the maintainers? Can we help with any information. Just let us know please, how we could assist 🙏🏻

**Comment by omerfsen** [comment]
Any update ?

**Comment by omerfsen** [comment]
@leecalcote Can i also get your opinion on this ?

**Comment by marziman** [comment]
Ok let me also ask the status here.
Colleagues, are you going to do something with this issue or do you just keep it like this?

@howardjohn I think we provided all infos you asked us. Now it is your turn. Did anybody at all tried to reproduce it?

Thanks & BR

**Comment by omerfsen** [comment]
I have more debug input for this:

I set debugging on istio-proxy:


```bash
istioctl proxy-config log  tracing-rest-tracing-0-model1-68f4845d6-8hx46.prod --level grpc:debug,upstream:debug,config:debug
```

I am attaching the logs:

It started at **2020-10-08T16:24:58**

with

```
istio-proxy[0m 2020-10-08T16:24:58.173837Z	warning	envoy config	[bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:92] StreamAggregatedResources gRPC config stream closed: 13, 

```

[grpc_log.log](https://github.com/istio/istio/files/5349514/grpc_log.log)

**Comment by omerfsen** [comment]
I have checked the time with same grpc 13 error but no upstream error received and found out that when following happens it definitely breaks connection for 30 min. The log starts like following: (it is line 738 on attached grpc_log.log I have attached on my previous comment)

```

2020-10-08T20:04:45.166604Z	debug	envoy config	[external/envoy/source/server/listener_manager_impl.cc:412] use in place update filter chain update path for listener name=virtualInbound hash=13528217587319322972
2020-10-08T20:04:45.166649Z	debug	envoy config	[external/envoy/source/server/listener_manager_impl.cc:129]   filter #0:
2020-10-08T20:04:45.166656Z	debug	envoy config	[external/envoy/source/server/listener_manager_impl.cc:130]     name: envoy.listener.original_dst
2020-10-08T20:04:45.167268300Z 2020-10-08T20:04:45.166679Z	debug	envoy config	[external/envoy/source/server/listener_manager_impl.cc:137]   config: {
2020-10-08T20:04:45.167275000Z  "@type": "type.googleapis.com/envoy.config.filter.listener.original_dst.v2.OriginalDst"
2020-10-08T20:04:45.167281400Z }
2020-10-08T20:04:45.167287100Z 
2020-10-08T20:04:45.167292600Z 2020-10-08T20:04:45.166688Z	debug	envoy config	[external/envoy/source/server/listener_manager_impl.cc:129]   filter #1:
2020-10-08T20:04:45.167298800Z 2020-10-08T20:04:45.166691Z	debug	envoy config	[external/envoy/source/server/listener_manager_impl.cc:130]     name: envoy.listener.tls_inspector
2020-10-08T20:04:45.167305400Z 2020-10-08T20:04:45.166699Z	debug	envoy config	[external/envoy/source/server/listener_manager_impl.cc:137]   config: {
2020-10-08T20:04:45.167312000Z  "@type": "type.googleapis.com/envoy.config.filter.listener.tls_inspector.v2.TlsInspector"
2020-10-08T20:04:45.167335300Z }
2020-10-08T20:04:45.167342400Z 
2020-10-08T20:04:45.167348100Z 2020-10-08T20:04:45.166734Z	debug	envoy config	[external/envoy/source/server/listener_manager_impl.cc:129]   filter #2:
2020-10-08T20:04:45.167354600Z 2020-10-08T20:04:45.166738Z	debug	envoy config	[external/envoy/source/server/listener_manager_impl.cc:130]     name: envoy.listener.http_inspector
2020-10-08T20:04:45.167361200Z 2020-10-08T20:04:45.166746Z	debug	envoy config	[external/envoy/source/server/listener_manager_impl.cc:137]   config: {
2020-10-08T20:04:45.167367800Z  "@type": "type.googleapis.com/envoy.config.filter.listener.http_inspector.v2.HttpInspector"
 2020-10-08T20:04:45.167374300Z }
2020-10-08T20:04:45.167379600Z 
2020-10-08T20:04:45.174103800Z 2020-10-08T20:04:45.173850Z	debug	envoy config	[external/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc:678] Secret is updated.
2020-10-08T20:04:45.175023300Z 2020-10-08T20:04:45.174863Z	debug	envoy config [external/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc:678] Secret is updated.
.....

```

**Comment by omerfsen** [comment]
One thing i have found out that I have 2 virtualservers and when error happens it redirect traffic to :5001 port (which is grpc service)

```
kubectl get virtualservices.networking.istio.io -A |grep tracing-rest
prod        tracing-rest-grpc      [istio-system/seldon-gateway]   [*]     10h
prod        tracing-rest-http      [istio-system/seldon-gateway]   [*]     10h
```
When error happens traffic routed to :5001 (the one that runs grpc endpoint)

<img width="869" alt="upstream-error-starts" src="https://user-images.githubusercontent.com/29705627/95514691-44ebcf00-09b4-11eb-8160-00096f2b4716.PNG">

and then ~30 min later it goes back to normal (because traffic is routed to :8000)

<img width="885" alt="upstream-error-ends" src="https://user-images.githubusercontent.com/29705627/95514731-58973580-09b4-11eb-84db-e2422a852443.PNG">

**Comment by puneetloya** [comment]
@howardjohn and other istio developers can we please not mark this issue as stale? Is the above provided evidence by @omerfsen does not point to any issue? To me this issue seems like the only reason we are not able to run tcp proxies successfully with Istio. I mean to say it does work but with intermittent disconnectivity.

I have been using Kafka and Cassandra with Istio for the past few months but it does come down to the disconnections that happen and recover with every time envoy gets refreshed(every 30 mins), assuming that the refresh is flushing out all connections. 

The apps that connect to these Istio based statefulsets do not have a graceful way to connect back once they are in this state or atelast they stay in the failed state for a long time. Do you need more evidence? I can help out.

Also is this even a Istio issue or an envoy tcp proxy bug?

**Comment by ramaraochavali** [comment]
not statle

**Comment by pantelis-karamolegkos** [comment]
Could this be related / addressed by enabling TCP keep alive in the `DestinationRule` [config](https://istio.io/latest/docs/reference/config/networking/destination-rule/#ConnectionPoolSettings-TCPSettings-TcpKeepalive)?

Could the absence of the above setting be making envoy terminating TCP connections and thus disrupting HTTP persistent connections?

**Comment by puneetloya** [comment]
@pantelis-karamolegkos I have tried keep alives, let me experiment a little bit more with it. But according to you, does proxy sidecar not terminate all existing connections when istiod sends out an proxy update every half an hour?

**Comment by leorric** [comment]
Hi there, I met the same error when calling an external destination as service entry. It is also random - most of the times the call succeeds but sometimes it fails with such error. I checked the client side envoy proxy log but did not find something unusual.  And I am sure the request does not reach the external service. Any hint how can I proceed to investigate this issue ?

**Comment by JohnHaan** [comment]
Hi, I met the same error.
We have two external domain thosse are api-dev.-----.com / api-qa.-----.com
We can access api-dev.-----.com but cannot access api-qa.-----.com

api-dev api call: 
```
# curl https://api-dev.-----.com/-----/v2.0/version
{"return":0,"message":"OK","value":{"revision":"97b0ddc.202101250444","version":"v2.0"}}
```

api-qa api call:
```
# curl http://api-qa.-----.com/-----/v2.0/version
upstream connect error or disconnect/reset before headers. reset reason: local reset
```

istio-proxy error message:
```
{"response_flags":"LR","start_time":"2021-01-29T06:56:34.281Z","method":"GET","request_id":"f292923e-74d6-9638-a01a-66c3a7fbe85e","upstream_host":"/-----:80","x_forwarded_for":null,"requested_server_name":null,"bytes_received":0,"bytes_sent":84,"upstream_cluster":"outbound|80||api-qa.-----.com","downstream_remote_address":"-----:54600","authority":"api-qa.-----.com","path":"/-----/v2.0/version","protocol":"HTTP/1.1","upstream_service_time":null,"upstream_local_address":null,"duration":10000,"upstream_transport_failure_reason":null,"route_name":"default","downstream_local_address":"-----:80","user_agent":"curl/7.68.0","response_code":503}
```

Is this a bug of istio?

**Comment by ironpeak** [comment]
Hi, running into the same error for istio version 1.6.14

I've a multicluster installation, using serviceentries to communicate which fail at random with:

503, upstream connect error or disconnect/reset before headers. reset reason: connection termination

**Comment by susan-shu-c** [comment]
I've run into this recently - it was solved by checking the workloads on GCP and deleting ones that were taking so much resources that the one workload causing this issue didn't have enough resources (CrashLoopBackOff)

**Comment by manasmishra** [comment]
Hi @omerfsen Do you find any solution for this issue? Any help will be really greatful? Anyone who has fixed it may be with some work arounds?

**Comment by omerfsen** [comment]
> Hi @omerfsen Do you find any solution for this issue? Any help will be really greatful? Anyone who has fixed it may be with some work arounds?

It was about service name not starting with http though not %100 sure

**Comment by previousdeveloper** [comment]
Hi, running into the same error for istio version 1.8.5
We got local reset and connection termination randomly. Is there any solution to fix it?
503, upstream connect error or disconnect/reset before headers. reset reason: connection termination

**Comment by davidmortiz** [comment]
I see the same issue in 1.9.2

**Comment by zufardhiyaulhaq** [comment]
not stale

**Comment by rvillane** [comment]
Same here when using istio 1.10.

HTTP 503 - upstream connect error or disconnect/reset before headers. reset reason: connection termination

In envoy logs I see:
2021-08-23T17:00:32.627283Z	warning	envoy config	StreamAggregatedResources gRPC config stream closed: 14, transport is closing

**Comment by talzion12** [comment]
Why is this closed?

**Comment by praveenchandran** [comment]
In my case I was missing the ingress host in the `hosts` field for the VirtualService. After adding it, the proxy was able to route it to the target service. 

FYI im not using a gateway, but nginx ingress instead.

**Comment by ramakant-rawat** [comment]
Hi I am also facing the same issue can anyone give the solution to this 
![Screenshot from 2022-02-25 17-32-55](https://user-images.githubusercontent.com/84322996/155712470-3cc33248-6811-416c-9476-17ff5833290e.png)

**Comment by BenjaminHuang** [comment]
We're facing the same issue, randomly happened on production, with istio-1.7.3 deployed.

At fist, I though it's releated to
https://github.com/istio/istio/issues/17383 
https://github.com/istio/istio/issues/17139
which should have been fixed by https://github.com/istio/envoy/pull/109/commits

then I realized that istio-1.7.3 has istio/envoy:1.21.2 which already contains the fix, I think this issue should be re-opened and reconsidered.

**Comment by marziman** [comment]
@howardjohn @ramaraochavali 
Can you please re-open this issue?

It is now 2 years and many people face this issue in production. Can you please prioritize it, as this has bad implications on connections.

There were enough reports and if further info needed, I am sure we all can provide infos.

Thanks!

**Comment by sumit-joshi-mt** [comment]
facing same issue we are using istio version `1.13.0` and we are using nginx ingress not gateway.

**Comment by howardjohn** [comment]
Hey folks - understood the concerns when seeing errors like this. However, this issue is not going to be a helpful path forward. This is a very generic error message that basically means "the request did not work". Without specific context (in the form of `istioctl bug-report`, logs, configs, etc), its impossible to make forward progress.

So I am not trying to dismiss this entirely - but please open new issues with details about your case so we can help.

Also see https://istio.io/latest/blog/2021/upcoming-networking-changes/ since that is a fairly basic one that could trigger this.

Thanks!

**Comment by linhx** [comment]
We have faced this issue too. I've found the root cause in our case. Hope this will helps you guys.

Context:
We have two services `service-a` and `service-b`. They are Nestjs projects, running on Node 12. `service-a` requests HTTP to `service-b`.

`service-a` got 503 with error `upstream connect error or disconnect/reset before headers. reset reason: connection termination`. But `service-b` stills processed. it happens randomly.
After tracing the logs, we saw that the error occurs when the request from `service-a` to `service-b` took too long. 
I tried to config [Istio timeout](https://istio.io/latest/docs/concepts/traffic-management/#timeouts) but it didn't work.

I created 2 new sample services in local. Set `service-b` to response slowly. And I got `Error: socket hang up code ECONNRESET` after 2 minutes. That makes I think the root cause is the HTTP server, not Istio.
Focus on the error from Nodejs, I found out that Node HTTP server will disconnects the socket connection after amount of time. And that amount of time can be set via the option [timeout](https://nodejs.org/docs/latest-v12.x/api/http.html#http_server_timeout)
I increase the timeout value of `service-b` and it works. You could find the similar setting on your HTTP server.
```typescript
@Injectable()
export class AppService implements OnApplicationBootstrap {
  private readonly logger = new Logger(AppService.name);
  constructor(private readonly refHost: HttpAdapterHost<any>) {}

  onApplicationBootstrap() {
    const server: Server = this.refHost.httpAdapter.getHttpServer();
    server.timeout = 300000; // 3 minutes
  }
}
```
**REMEMBER** to increase the socket timeout of `service-a` if the flow is like the image below, because the HTTP request to `service-a` can be terminated too.
![Screenshot from 2022-07-17 12-25-48](https://user-images.githubusercontent.com/50461902/179385125-f88b3e73-89bb-4b98-a6cb-048af63c5c47.png)
------
Conclusion:
1. Increasing soket timeout is temporary solution. You should think about event base, or save the request state and use it for the retry request.
2. Istio timeout actually works. It effects when Istio's timeout is smaller than HTTP server socket timeout.

**Comment by IliaChi** [comment]
I just restarted my computer and it fixed it

**Comment by davidwangqing** [comment]
I also faced this issue with my homelab, not sure if it caused by daily computer shutdown.  I restarted istio gateway pod, and everything back to works again.

**Comment by TK777777** [comment]
I modified the "hub" address of kubectl edit configmap -n istio-system istio-sidecar-injector and it was restored. Hope it is useful to you!

**Comment by Dinhvanthai68** [comment]
upstream connect error or disconnect/reset before headers. retried and the latest reset reason: remote connection failure, transport failure reason: TLS_error:|268435758:SSL routines:OPENSSL_internal:KEY_USAGE_BIT_INCORRECT:TLS_error_end

**Comment by TAREKKAPSA** [comment]
2020-09-24T17:12:35.507004Z     warning envoy config    [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:92] StreamAggregatedResources gRPC config stream closed: 13,
