### ISSUE TITLE
Document separate gateway installation and upgrade

### ISSUE THREAD

**Issue by ostromart** [istio/istio#27511]
Gateways are currently upgraded first and in-place in the multi-control plane version scenario. This is undesirable because the gateway is the most important proxy and should be upgraded last. 
Although the functionality to manage gateways separately has been available for istioctl since 1.6 and operator since 1.7, this is not documented.

**Comment by ostromart** [comment]
https://github.com/istio/istio/pull/27601

**Comment by bianpengyuan** [comment]
I moved this to 1.9 as I don't think this could make 1.8.
