### ISSUE TITLE
Restore manifest generate functionality

### ISSUE THREAD

**Issue by ostromart** [istio/istio#27516]
There have been user requests for this. 
- Add labels to support kubectl --prune option
- Documentation

**Comment by carolynhu** [comment]
cc @carolynhu

**Comment by ostromart** [comment]
https://github.com/istio/istio/pull/21355
Earlier attempt - see for context/inspiration.

**Comment by bianpengyuan** [comment]
I pushed this to 1.9 as I don't think this blocks 1.8 release. Let me know if we should move it back, thanks!

**Comment by carolynhu** [comment]
Confirmed with @ostromart , this issue has been resolved.

**Comment by carolynhu** [comment]
https://github.com/istio/istio/pull/28039
