### ISSUE TITLE
Cannot get client IP address

### ISSUE THREAD

**Issue by pavanfhw** [istio/istio#27520]
**Bug description**
I know there are already some issues about this, but I can't get a definitive answer and a working solution.
I only have Isito ingress gateway and Istio sidecars on my cluster. The IP on the X-Forwarded-For header in the destination pod is of an Isito svclb-istio-ingressgateway pod.
External Traffic Policy in the service/istio-ingressgateway is already set to Local.
What configuration do I need to change for the client IP address to reach the destination pod and not be replaced by internal IPs?

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Setting some configuration like an EnvoyFilter or External Traffic Policy like suggested in other posts to be able to forward the client IP making the request to the destination pod.
**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
client version: 1.7.0
control plane version: 1.7.0
data plane version: 1.7.0 (15 proxies)

Client Version: v1.18.6+k3s1
Server Version: v1.18.6+k3s1

**How was Istio installed?**
istioctl install --set profile=default

**Environment where bug was observed (cloud vendor, OS, etc)**
K3OS cluster

**Comment by xulingqing** [comment]
Here a customer indicated there might be more than one client IP https://github.com/istio/istio/issues/26656#issuecomment-697210897

**Comment by howardjohn** [comment]
cc @rvennam I think you were writing a doc on this?

**Comment by rvennam** [comment]
Take a look at this doc https://preliminary.istio.io/latest/docs/ops/configuration/traffic-management/network-topologies/
