### ISSUE TITLE
Empty Cluster VIPs causing shared-control plane to give invalid config

### ISSUE THREAD

**Issue by stevenctl** [istio/istio#27526]
Not 100% what the impact yet, but after adding logging to GetServiceAddressForCluster (in https://github.com/istio/istio/pull/27493) I found that (at least in the cases we break, it is probably intermittent) I found that ClusterVIPs on the push context was always empty. This means we will give the k8s ClusterIP from one cluster to all clusters connected to istiod. 

[Added logging](https://github.com/stevenctl/istio/blob/d926af10ded2992a8f096761beea429bb8403183/pilot/pkg/model/service.go#L582-L597)
[Sample logs](https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/27493/integ-pilot-multicluster-tests_istio/1596/artifacts/pilot-endpointslice-7b80a9cf61b/_suite_context/istio-state-cluster-0-208224397/cluster-0/istiod-85ff6cd8fc-x49sx_discovery.log) (looking for regex `using (\d{1,3}\.?){4} for proxy` shows we never use the clustervips)

Don't know what this impacts completely, but I'd imagine we're not hitting kube-proxy because of it, or kube-proxy won't send traffic correctly. One thing that is breaking that is probably related is that pods in "remote" clusters (using another cluster's control plane) intermittently have connection issues with the test "vm" services.

**Comment by stevenctl** [comment]
Looks like in addition to DNS we build httproute and listeners using the service address.

**Comment by stevenctl** [comment]
It's possible that since the "vm" doesn't know that its in a cluster, it fails to get the right service address?

**Comment by stevenctl** [comment]
cc @ramaraochavali @howardjohn @nmittler

**Comment by stevenctl** [comment]
The echo service in cluster-1 has a lot of Service IPs from cluster-0's service subnet which seems in correct. 

https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/27493/integ-pilot-multicluster-tests_istio/1596/artifacts/pilot-endpointslice-7b80a9cf61b/_suite_context/echo-1-7855-state-425368636/cluster-1/a-v1-f5dcd8fdb-k82bh_proxy-config.json

**Comment by ramaraochavali** [comment]
Is somehow caching that was done as part of https://github.com/istio/istio/pull/27027 in PushContext affecting this? Not sure how it can - but there is a probability

**Comment by stevenctl** [comment]
I saw that there were a lot of paths leading to `continue` before they get added to that map. I tried moving the map above but I don't think it helped.

**Comment by stevenctl** [comment]
It's gotta have something to do with that caching. The cluster vip map on the Service instance has the right values.

**Comment by ramaraochavali** [comment]
@stevenctl  Please see if https://github.com/istio/istio/issues/27526 fixes it?

**Comment by stevenctl** [comment]
I think I found the issue - when we do `InitContext->UpdateContext` we skip generating this index if there are no changed services.

**Comment by stevenctl** [comment]
Fixed in #27608
