### ISSUE TITLE
Use server side apply library in operator/pkg/helmreconciler

### ISSUE THREAD

**Issue by ostromart** [istio/istio#27521]
Because of the need to support k8s 1.15, we do not use server side apply pkg in the operator/istioctl install but rather use go-client with our own apply implementation. 
This has generally worked ok but there are some subtle and important differences in how these work. The most important is that kubectl does not merge unset values with the current values in the cluster. This shows up in cases where the value is unset and dynamically generated/set in the API server (e.g. port value). 
The fact that unset is treated as default in helmreconciler package leads to this value being reset to the default in the cluster, regardless of its current value, since the apply logic does not differentiate between default and unset.

**Comment by sdake** [comment]
this is a dependency for a P0 roadmap item.

**Comment by richardwxn** [comment]
one of the issue met during testing: https://github.com/kubernetes-sigs/structured-merge-diff/issues/130. Seems like many existing charts need to define port with protocol, which is actually an optional field, otherwise the server-side apply would fail

**Comment by bianpengyuan** [comment]
Is this fixed? This is p0 for 1.8.

**Comment by bianpengyuan** [comment]
I think this is fixed and it actually leads to a release blocker https://github.com/istio/istio/issues/28189. Closing this and please reopen if you think this is not the case. @richardwxn
