### ISSUE TITLE
Logic error in Ingress status updates

### ISSUE THREAD

**Issue by polivbr** [istio/istio#27523]
**Bug description**

There is a logic error in the process that updates Ingress resources with the IP of the ingress gateway, which can cause it to take an incredibly long time for the resource to be updated.

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

The IP address of the Ingress resource is updated shortly after it is added to the cluster.

**Steps to reproduce the bug**

Add multiple Ingress resources. The more that are in the cluster, the more likely they are to not be updated.

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

Istio version: 1.7.2

**How was Istio installed?**

Istio Operator

**Environment where bug was observed (cloud vendor, OS, etc)**

On-prem

**Comment by polivbr** [comment]
The issue is in pilot/pkg/config/kube/ingress/status.go

In updateStatus(), when an ingress is skipped because there is no change:

```
		if ingressSliceEqual(status, curIPs) {
			log.Debugf("skipping update of Ingress %v/%v (no change)", currIng.Namespace, currIng.Name)
			return nil
		}
```

it is returning from the function, rather than moving on to the next ingress record.

The "return nil" should be replaced with "continue".

**Comment by shamsher31** [comment]
@polivbr If https://github.com/istio/istio/pull/27624 fixed your issue. Please close this.
