### ISSUE TITLE
StreamAggregatedResources gRPC config stream closed: 13

### ISSUE THREAD

**Issue by shinynz** [istio/istio#27532]
After upgrading to isto version 1.7.2, isto proxy always reports the warning of stream aggregated resources grpc config stream closed
![sendpix0](https://user-images.githubusercontent.com/15795798/94216139-365fdb00-ff11-11ea-911f-2873d3d0a50e.jpg)

**Comment by howardjohn** [comment]
This is expected: https://github.com/istio/istio/wiki/Troubleshooting-Istio#common-issues

**Comment by shinynz** [comment]
but The envoy request log is not printed @howardjohn

**Comment by howardjohn** [comment]
I am not sure what you mean. This exactly matches the expectations. There are no XDS request logs.
