### ISSUE TITLE
503 - unable to reach the service from client pod 

### ISSUE THREAD

**Issue by riyazmsm** [istio/istio#27550]
i have  a deployment,  once the  service is created client pods are unable to call the service or the app pod as the sidecar returns
 "503 upstream connect error or disconnect/reset before headers. reset reason: connection failure"
if i remove the service  able to reach the app pod. 
when i deploy this manifests to a namespace that does not have istio injection enabled it works without a issue and able to reach the service or  app pod

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
access the service ,app pod from client pods.
**Steps to reproduce the bug**

- **connecting to the service , app pod from curl container**

```
conn         ClusterIP   10.97.239.128   <none>        8082/TCP   19m

[ root@curl:/ ]$ curl -v http://conn:8082
> GET / HTTP/1.1
> User-Agent: curl/7.35.0
> Host: conn:8082
> Accept: */*
> 
< HTTP/1.1 503 Service Unavailable
< content-length: 91
< content-type: text/plain
< date: Fri, 25 Sep 2020 16:46:21 GMT
< server: envoy
< x-envoy-upstream-service-time: 42
< 
upstream connect error or disconnect/reset before headers. reset reason: connection failure[ root@curl:/ ]$ 
[ root@curl:/ ]$ curl http://172.18.0.14:8083
upstream connect error or disconnect/reset before headers. reset reason: connection failure[ root@curl:/ ]$ 
```
remove the service and connect to the app pod
```
[opc@fusionx-rnd-vm ~]$ k delete svc conn
service "conn" deleted
[opc@fusionx-rnd-vm ~]$ k exec -ti curl -- sh
Defaulting container name to curl.
Use 'kubectl describe pod/curl -n default' to see all of the containers in this pod.
sh: shopt: not found
[ root@curl:/ ]$ curl http://172.18.0.14:8083
{"version":"2.3.0","commit":"fc1aaa116b661c8a","kafka_cluster_id":"OSS"}[ root@curl:/ ]$ 
```

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
client version: 1.6.7
control plane version: 1.6.7
data plane version: 1.6.7 (6 proxies)

Client Version: v1.19.0
Server Version: v1.19.2

**How was Istio installed?**
istioctl manifest apply --set profile=demo   --set values.global.mtls.auto=false   --set values.global.mtls.enabled=false

**Environment where bug was observed (cloud vendor, OS, etc)**
minikube version: v1.13.11.6.7, kubernetes v1.19.0
OKE , v1.15.7

[deployment_manifest.zip](https://github.com/istio/istio/files/5284316/connqa.zip)
[istio-dump.tar.gz](https://github.com/istio/istio/files/5284283/istio-dump.tar.gz)

**Comment by howardjohn** [comment]
Does the connectorqa app listen on pod IP, localhost, or 0.0.0.0? You can see with `netstat -nl` from the pod (proxy container has it if your app does not)

**Comment by riyazmsm** [comment]
this is the output

```[opc@fusionx-rnd-vm ~]$ k get po -o wide -l app=connectorqa
NAME                          READY   STATUS    RESTARTS   AGE   IP            NODE       NOMINATED NODE   READINESS GATES
connectorqa-cc8b54bb9-gpktr   2/2     Running   701        26d   172.18.0.14   minikube   <none>           <none>


[opc@fusionx-rnd-vm ~]$ k exec connectorqa-cc8b54bb9-gpktr -c kcbackgrnd -- netstat -nl
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 0.0.0.0:15090           0.0.0.0:*               LISTEN     
tcp        0      0 172.18.0.14:8083        0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:15000         0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:15001           0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:34012           0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:15006           0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:15021           0.0.0.0:*               LISTEN     
tcp6       0      0 :::15020                :::*                    LISTEN     
Active UNIX domain sockets (only servers)
Proto RefCnt Flags       Type       State         I-Node   Path
unix  2      [ ACC ]     STREAM     LISTENING     288851   ./etc/istio/proxy/SDS

**Comment by howardjohn** [comment]
> 72.18.0.14:8083

This shows its listening on the Pod IP. Istio requires the app to listen on 0.0.0.0 or 127.0.0.1 currently. This is a very under documented area, which I am working on fixing, as well as an open PR to support this: https://github.com/istio/istio/pull/28178

**Comment by howardjohn** [comment]
Closing as this is working as expected; this wil be supported in newer versions (per api above). Thanks!
