### ISSUE TITLE
Need to validate that adapter goroutines have all been shutdown after handler.Close returns

### ISSUE THREAD

**Issue by geeknoid** [istio/istio#2755]
I'm seeing a recurring pattern where adapter authors are forgetting to terminate and cleanup goroutine when a handler is closed, thus leading to leaks and potential crashes.

We should count the number of goroutines started/terminated with the env.ScheduleXXX routines and ensure this number is 0 by the time handler.Close returns. If the value is !=0, log an error.

**Comment by guptasu** [comment]
Done https://github.com/istio/istio/pull/2816
