### ISSUE TITLE
Extending Self-Signed Certificate Lifetime documentation outdated

### ISSUE THREAD

**Issue by Sh1ftry** [istio/istio#27575]
**Bug description**
The [Extending Self-Signed Certificate Lifetime](https://istio.io/latest/docs/ops/configuration/security/root-transition/) page mentions that envoy sidecars may be hot restarted. However, in #23922 there is a comment stating, that since Istio 1.5 envoy proxies are no longer hot restarted, which means the steps presented in the documentation are not up to date.

[x ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by howardjohn** [comment]
Thanks, this is definitely wrong

**Comment by williamaronli** [comment]
@howardjohn  who should be the doc team to deal with the doc change. first assign it to you howard and you can assign back to other person who is reponsible for the doc change thanks

**Comment by howardjohn** [comment]
@istio/wg-security-maintainers

**Comment by lei-tang** [comment]
Assigned to @myidpt to triage.
