### ISSUE TITLE
Proto constraint validation failed (LuaValidationError.InlineCode

### ISSUE THREAD

**Issue by sergioteixeiraptc** [istio/istio#27580]
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

After updating from istio 1.6.7 to 1.7.2 my proxies dont get up with the following error:

nfig.listener.v3.Listener rejected: Error adding/updating listener(s) virtualInbound: Proto constraint validation failed (LuaValidationError.InlineCode: ["value length must be at least " '\x01' " bytes"]):

2020-09-28T10:01:56.137420Z	warn	Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 1 successful, 0 rejected; lds updates: 0 successful, 1 rejected

i do run custom envoyfilter with lua.

**Comment by sergioteixeiraptc** [comment]
simply had to update my envoyfilter config, nvm

**Comment by Ayush-Walia** [comment]
Hey, @sergioteixeirapt Can you tell what changes did you make in your envoyfilter config to resolve this?
