### ISSUE TITLE
feat(dashboards): consider switch to client metrics where appropriate

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio#27595]
The dashboards were originally developed before client-side telemetry was available. As a result, they are heavily biased towards server-side metrics. This can result in holes in the observability story provided by the dashboards (in the case of client-side faults, etc.).

We should review the existing dashboards for `reporter=destination` queries and consider if switching to `reporter=source` would be more inclusive.

[ X ] Extensions and Telemetry

**Comment by carolynhu** [comment]
Doc shared with the community: [Istio Grafana Dashboard Metrics Reporter Refinement](https://docs.google.com/document/d/1Nry-gyKMty-XaQ70p6Q0bbTLCunRSrI7R1mFlnDG8zQ/edit#heading=h.qd82wmvk3u1n)
