### ISSUE TITLE
Promote Virtual Service Delegation to Alpha

### ISSUE THREAD

**Issue by ericvn** [istio/istio#27599]
Virtual Service Delegation was introduced in release 1.6 with https://github.com/istio/istio/pull/22118. It was never placed in the [Feature List](https://istio.io/latest/about/feature-stages/). This issue is based on the[ Alpha Feature Requirements](https://github.com/istio/enhancements/blob/master/.github/ISSUE_TEMPLATE/alpha_feature.md).

# Alpha Feature Requirements

This page lists the requirements for promoting a feature to alpha. Please check off and document the steps as they are completed.

**Feature Name:**  Virtual Service Delegation

**RFC:** Design doc listed next

**Design doc:** https://docs.google.com/document/d/1TzXjvbEqeRKHQ7FonAY_yS1zHa8rVH2DIq4EM5BuDQ4/edit#

**Relevant Documentation:** https://istio.io/latest/docs/reference/config/networking/virtual-service/#Delegate

--- 

### Requirements: 

**Design**

- [ ] RFC has been approved describing the intention of the feature as well as the user stories behind the feature. 
_The Design Doc is still in review, but implementation was released in 1.6. _

**Config**

- [x] Explicit user action is required to enable this feature (e.g. a config field, config resource, or installation action). 
_The usage is controlled by use of **Delegate**. _

> Link to instructions for enabling
_https://istio.io/latest/docs/reference/config/networking/virtual-service/#Delegate_

**Docs**

- [x] Reference docs are published to preliminary.istio.io or the Istio wiki.
- [ ] Basic feature docs are published on preliminary.istio.io describing what the feature does, how to use it, and any caveats. 
- [x] Release notes entries added as appropriate
- [na] Upgrade notes entries added as appropriate

**Tests**

- [ ] Automated integration tests cover core use cases with the feature enabled. 
- [x] When disabled, the feature does not affect system stability or performance. 

**API**

- [x] Initial API review.  https://github.com/istio/api/pull/1209

**Approvals**

- [ ] The appropriate work group(s) have reviewed and approved promotion of the feature.
- [ ] The TOC has reviewed and approved promotion of the feature as part of the
	roadmap for a release.

**Comment by howardjohn** [comment]
I thought these issues would go in istio/enhancements?

**Comment by ericvn** [comment]
Good point John. I can't transfer there, but will close, open a new one.
