### ISSUE TITLE
Plugging in existing CA Certificates issue

### ISSUE THREAD

**Issue by SprintCT** [istio/istio#27605]
Hi,

I tried to Install CA certificate in ISTIO as per documentation. (https://istio.io/latest/docs/tasks/security/cert-management/plugin-ca-cert/)

1) ca-cert.pem - End-Entity certificate
2) ca-key.pem - RSA private key of End-Entity ceritifcate
3) cert-chain.pem - Intermediate --> root certificate
4) root-cert.pem  - root cert.

However i'm getting below error,

Error: failed to create discovery service: failed to create CA: failed to create an istiod CA: failed to create CA KeyCertBundle (failed to parse cert PEM: failed to parse X.509 certificate)

As per few blogs, I find that we have to use intermediate certificate for ca-cert.pem and private key of intermediate certificate, However third party certificate vendor are not providing intermediate cert and private key.

Kindly advise to install CA plugin in ISTIO.

**Comment by nmnellis** [comment]
have you validated that your certificates are valid (ie newlines etc), the error leads me to believe there is some textual issue with your secrets. validate them here first https://support.acquia.com/hc/en-us/articles/360004119234-Verifying-the-validity-of-an-SSL-certificate

**Comment by SprintCT** [comment]
Thank you, I will verify the certificate however kindly confirm whether shall we use End entity / server certificate or intermediate certificate in ca-cert.pem file for istio CA plugin

**Comment by nmnellis** [comment]
you will need a signing certificate. you can view the example certs istio uses here https://github.com/istio/istio/tree/master/samples/certs

**Comment by incfly** [comment]
Closing for now, assigned @lei-tang in case you found anything feel free to reopen.
