### ISSUE TITLE
New a way to disable crds from installation

### ISSUE THREAD

**Issue by irisdingbj** [istio/istio#27609]
we are now support helm3 and put all crds under `/crd` . since `/crd` does not support templates, there is currently not an easy to to disalbe crds from `base`.

One possible solution is to keep only crds under `base` and move all others under `istio-control/isito-discovery` since those sa, role binddings and cluster role bindings, validation webhook configuraiton will be used by istiod.

**Comment by irisdingbj** [comment]
@howardjohn @linsun WDYT about above solution?

As if we only change `helm.go` it will not support helm3 any way.

**Comment by irisdingbj** [comment]
@howardjohn I consult with helm team and get response like below:

```
Unfortunately, manifests only apply in the /crds directory and you would not have the templating for adding the enable/disable logic. You could put the CRDs in the template directory as long as there are no resources that use these CRDs in the chart. This may however circumvent API validation and not sure if it is an approved way to do it. You would also need to test this method against your chart to make sure it works as expected.
```

https://github.com/helm/helm/issues/8821


I moved crds under /templates and test this out via `helm3 isntall` it works well.   As we are in the case `You could put the CRDs in the template directory as long as there are no resources that use these CRDs in the chart.`

So suppose we are safe to move crds under /templates? 

Any known issues for this?

**Comment by irisdingbj** [comment]
cc / @sdake

**Comment by irisdingbj** [comment]
cc / @nmittler @stevenctl @linsun 

This is the item we discussed regarding to `Split crds and validation webhook configurations from base via a single flag to support remote-less cluster` I am stuck on a good solution here. Any suggestions you can offer?

By the way, I will be out until 10/10 so will get back to this when I am back.

**Comment by sdake** [comment]
> @howardjohn I consult with helm team @hickeyma and get response like below:
> 
> > Unfortunately, manifests only apply in the /crds directory and you would not have the templating for adding the enable/disable logic. You could put the CRDs in the template directory as long as there are no resources that use these CRDs in the chart. This may however circumvent API validation and not sure if it is an approved way to do it. You would also need to test this method against your chart to make sure it works as expected.
> 
> [helm/helm#8821](https://github.com/helm/helm/issues/8821)
> 
> I moved crds under /templates and test this out via `helm3 isntall` it works well. As we are in the case `You could put the CRDs in the template directory as long as there are no resources that use these CRDs in the chart.`
> 
> So suppose we are safe to move crds under /templates?
> 
> Any known issues for this?

The conditional here (as long as there are no resources that use these CRDs) is highly dangerous in my opinion. We have been completely cratered by past helm conditionals like this. I would encourage more exploration.

Cheers,
-steve

**Comment by sdake** [comment]
actually nevermind - too early - or late - brain still booting. We do not use CRs in any charts where we install CRDs. This leads to race conditions. This is why we have a base chart to install the CRDs. Other charts then may install CRs. I haven't looked at your specific PR, but will take a look when my day begins.

Cheers,
-steve

**Comment by linsun** [comment]
> we are now support helm3 and put all crds under `/crd` . since `/crd` does not support templates, there is currently not an easy to to disalbe crds from `base`.
> 
> One possible solution is to keep only crds under `base` and move all others under `istio-control/isito-discovery` since those sa, role binddings and cluster role bindings, validation webhook configuraiton will be used by istiod.

One potential issue with the possible solution is how it works with multiple control planes as some of these are cluster wide configurations such as cluster role.

**Comment by linsun** [comment]
> @howardjohn I consult with helm team @hickeyma and get response like below:
> 
> > Unfortunately, manifests only apply in the /crds directory and you would not have the templating for adding the enable/disable logic. You could put the CRDs in the template directory as long as there are no resources that use these CRDs in the chart. This may however circumvent API validation and not sure if it is an approved way to do it. You would also need to test this method against your chart to make sure it works as expected.
> 
> [helm/helm#8821](https://github.com/helm/helm/issues/8821)
> 
> I moved crds under /templates and test this out via `helm3 isntall` it works well. As we are in the case `You could put the CRDs in the template directory as long as there are no resources that use these CRDs in the chart.`
> 
> So suppose we are safe to move crds under /templates?
> 
> Any known issues for this?

@nrjpoddar @jacob-delgado are you aware of any known issue with this?  I'm leaning towards this approach atm.

**Comment by nrjpoddar** [comment]
I’m not completely following all the use case and what we are trying to achieve here. As far as I can tell we should keep CRDs under the CRD directory and let Helm manage the lifecycle of CRDs. This will cause behavioral changes for customers as I’m adding doc to support Helm3 in 1.8.

**Comment by linsun** [comment]
@nrjpoddar the user case is that we need to provide an option to disable CRDs install for remote cluster as they are not needed.  Only the config cluster needs the CRDs.  We don't find a good way to do this, a few options:
- move non crds out of base to istio-discovery.  This has implications for multi-revisions for istio-discovery.
- move crds to templates so we can add conditions.
- split base component to a dedicated component for crd, and another component for non-crds.

**Comment by nrjpoddar** [comment]
Thanks @linsun, what tool are you using to install Istio in remote cluster? If you're using `istioctl` or Operator you have other ways to accomplish this, correct?

**Comment by linsun** [comment]
Yes, we do plan to use istioctl or operator - are you suggesting we work around this issue via operator code? if so, helm user won't have it for remote cluster.

**Comment by nrjpoddar** [comment]
> Yes, we do plan to use istioctl or operator - are you suggesting we work around this issue via operator code? if so, helm user won't have it for remote cluster.

May be. There's no downside to installing CRDs in remote cluster afaict, so if folks want to use Helm for remote "istiod" setup, they can live with few CRDs or you can add a step to remove CRDs after installing the base chart which doesn't feel right but achieves what you want.

I'm also fine with other solutions around moving cluster resources inside istio-discovery chart as long as it works with canary upgrades.

**Comment by irisdingbj** [comment]
@nrjpoddar Thanks for looking at the issue!    Basically we want to a way to exclude CRDs when we have `base` enabled in the IOP file.  Now since crds are under /crd directory in `base' charts and it does not support templates, so there is no way to exclude crds..  

The scenario for this is we have a separate `config` cluster and all `remote` clusters will not need CRDs installed but the sa, role bindings are needed.

So no matter `helm` or `istioctl` , if there is good way to exclude CRDs from `base`?

Thanks!

**Comment by nrjpoddar** [comment]
I see, Helm install/upgrade provides an option `skip-crds’ option which should meet your needs.

**Comment by linsun** [comment]
@nrjpoddar Thanks, it is good to know helm has such an option. I think it would be reasonable for istioctl to also introduce an equivalent option.

cc @ostromart @irisdingbj
