### ISSUE TITLE
Long-lifetime JWT revocation list support

### ISSUE THREAD

**Issue by lindlof** [istio/istio#27618]
**Describe the feature request**

Long-lifetime JWT tokens can be thought of as a better version of typical API keys. However, like API keys they need a source of information to revoke the JWTs that have been compromised or denied access.

In `istio` it's certainly possible to control which JWTs can access a specific service. I would like to take it a step further and allow revocation of a JWT through a global list. It could either be a blacklist of revoked JWTs or a whitelist of non-revoked JWTs.

Currently the `jwksUri` option is used to specify URI of the issuer's key. There could be similar options e.g. `revocationUri`/`whitelistUri` for specifying URI of the list.

CAs provide [certificate revocation lists](https://en.wikipedia.org/wiki/Certificate_revocation_list) for certificates. I'm not aware of any standard for doing this with JWTs. I suggest a JSON which contains an array of objects which contain claims to match with JWT claims. For instance, the following JSON in `revocationUri` would deny access to all JWTs with `sub` claim value `"myservice.example"`:

```
[{ "sub": "myservice.example" }]
```

**Describe alternatives you've considered**

Better support for API keys in `istio`. There are many benefits for using JWTs, however. Long-lifetime JWTs can contain claims and often are sufficient and easy to start with even without this feature.

Services can implement reading revocation list themselves but this takes a bite in benefits of `istio`.

API consumers could use `Client Credentials Grant` OIDC flow to generate short-lifetime JWTs instead of long-lifetime JWTs. This would be a very "correct" solution but is an overhead for API consumers.

[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[x] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Additional context**

We are issuing long-lifetime JWTs with unique combinations of claims `sub` and `ver`. `ver` is a running number that can be easily used to identify a token given to a subject. We could then easily generate blacklists and whitelists based on deprecating all `ver` numbers from a certain point.

Whitelist would make more sense to me than a blacklist because we're generating JWTs that are valid for very long times and we might reject large amounts of JWTs over time, growing the list. However, if this feature is included I'd like to see both revocation and whitelisting options added.

**Comment by howardjohn** [comment]
I am not a jwt expert but this seems pretty suspicious to me given there is no standard, no envoy support, and the primary jwt providers (https://auth0.com/docs/tokens/revoke-tokens) do not support revocation. It seems the core problem is using long lived tokens rather than the recommended short tokens

**Comment by nmnellis** [comment]
This can easily be implemented in a custom envoy filter. In the past i have used them to call O.P.A to do similar tasks.

**Comment by lindlof** [comment]
@howardjohn There is no reason to use a third party provider for long-lifetime tokens. They are simple enough to sign yourself. OICD is more geared for user authentication than service authentication. I think Auth0 is concerned about logout flows in that page.

As I mentioned long-lifetime JWTs are not as "correct" at the first glance but if you compare them to normal API keys they are brilliant. You can whitelist/blacklist JWT metadata where an API key list will be confidential.

These are used in the industry but it's hard to come up with a source to prove their validity. isto can very well reject this suggestion based on lack of a standard but I'd suggest that someone with service authentication and JWT experience thinks this usecase through.

@nmnellis Yea forgot to mention lua filters. Been eying that possibility but wouldn't want to load the list on each request. I think to have decent performance it would need a service that loads the list and can then answer if token is revoked. Might be I've missed something with filters but also if this is a common issue this could be worth implementing.

**Comment by esnible** [comment]
@incfly What is the status of this?
