### ISSUE TITLE
restrict istio to use http1.1 for https

### ISSUE THREAD

**Issue by harishamurthy** [istio/istio#27615]
**Bug description**
The restriction to use http1.1 fro https is not working.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
The communication b/w client and istio to select http1.1 instead of h2.

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

**How was Istio installed?** Istio 1.4

**Environment where bug was observed (cloud vendor, OS, etc)** K8s

configuration used:
  port:
          name: http-secure
          number: 443
          protocol: HTTPS
        tls:
          mode: SIMPLE
          privateKey: /etc/istio/ingressgateway-certs/tls.key
          serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
    
this we expecting it uses http1.1 for communication with server.

curl command showing it selects h2.

curl -v --insecure https://<host>/path
*   Trying 144.25.101.19...
* TCP_NODELAY set
* Connected to ptpcoreapi-ptpcoreapi.oraclecorp.com (144.25.101.19) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-CHACHA20-POLY1305
* ALPN, server accepted to use h2

**Comment by howardjohn** [comment]
do you want h1 just to the gateway or also from gateway to application?

**Comment by harishamurthy** [comment]
Hi howard, we want mainly from gateway to application if possible, else even to client to gateway also fine.

**Comment by harishamurthy** [comment]
> do you want h1 just to the gateway or also from gateway to application?

Hi howard, we want mainly from gateway to application if possible, else even client to application also fine.
