### ISSUE TITLE
istioctl commands against istiod fail on port-forwarding

### ISSUE THREAD

**Issue by rolandkool** [istio/istio#27628]
**Bug description**
All istioctl commands that interact with the istiod pods fail because of an unknown port-forwarding error.

For example, the following command, run with active kubeconfig context set to cluster container istiod, fails:
`istioctl version`
outputs:
```
2 errors occurred:
	* error port-forewarding into istiod-6d64fc8788-hhtrz : unknown (get pods istiod-6d64fc8788-hhtrz:15014)
	* error port-forewarding into istiod-6d64fc8788-sbf2p : unknown (get pods istiod-6d64fc8788-sbf2p:15014)


1.7.2
```

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[X] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Command should return versions

**Steps to reproduce the bug**
Not sure, our environment has some clusters that have this issue and some that don't.

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
1.7.2 on controlplane and the istioctl binary.

**How was Istio installed?**
istioctl install

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

**Comment by howardjohn** [comment]
cc @esnible

**Comment by shamsher31** [comment]
Closed by https://github.com/istio/istio/pull/27436
