### ISSUE TITLE
How to view Istio CNI plugin logs ?

### ISSUE THREAD

**Issue by silencehe09** [istio/istio#27620]
@tiswanso 
For some reasons , I have to  install  istio-cni  on Openshift 4.5 (the version of  istio is 1.2.3 and the docker image of istio-cni is install-cni:1.2.3) 。 And I had followed the steps([Install Istio with istio CNI plugin](https://istio.io/v1.2/docs/setup/kubernetes/additional-setup/cni/)) to install istio CNI plugin , and the daemonset isito-cni-node-xxx pods seem to run with no errors。After I deploy an application ,  the sidecar container has been injected to the pod and  no init container  displays。 But when I check the iptables rules in  the pod , the rules are empty , so  inbound or outbound traffic can't be redirected to sidecar container。 

I had checked my istio-cni config many times ,  it seems OK.  How can I view the istio-cni logs  to troubleshoot the problem ? 
I did the following guide, but got nothing.  

> The CNI plugins are executed by threads in the kubelet process. The CNI plugins logs end up the syslog under the kubelet process. On systems with journalctl the following is an example command line to view the last 1000 kubelet logs via the less utility to allow for vi-style searching:

$ journalctl -t kubelet -n 1000 | less

**Comment by howardjohn** [comment]
If it's not showing up in kubelet logs then it's probably not running.

Your version of istio is far to old for us to help debug - cni has improved a lot since then. Please upgrade to a supported version and open an issue if you still have issues. See https://istio.io/latest/news/support/announcing-1.5-eol-final/

**Comment by silencehe09** [comment]
@howardjohn  Hi, I'm sorry to say that I still need your help to view istio cni logs. 
After I had upgraded istio version to  1.7.2  on Openshift 4.5, the istio cni plugin  works well.  And I had set the log level to debug,  but the logs of istio cni are not  showing  up  in kubelet logs  using _journalctl -t kubelet -n 1000 | less._   The logs are helpful for troubleshooting.
