### ISSUE TITLE
Donation of Ansible Playbook for Installing on Kubernetes / Openshift

### ISSUE THREAD

**Issue by geoand** [istio/istio#2763]
Hello,

I apologize beforehand if this is not the right place to open this issue.

As part of the work that the team I work on is doing, we have developed an Ansible Playbook that we use to install Istio on our clusters. You can view the work [here](https://github.com/snowdrop/istio-integration).

I am opening this ticket because we would like to donate / integrate this work into Istio so all users can benefit from it. A relevant discussion has already been started in the `istio-dev` list which you can find [here](https://groups.google.com/forum/#!searchin/istio-dev/ansible%7Csort:date/istio-dev/Pc2B9HmvfuQ/i7Ijde9YAQAJ).
We can of course make changes deemed necessary before contributing it to the Istio project

I am looking forward to hearing your thoughts on this.

Regards

**Comment by mandarjog** [comment]
This is great. Has it been tested on vanilla kubernetes ?

**Comment by geoand** [comment]
Yes we have tested it, but admittedly not as extensively as with Openshift.
We are currently in the process of having the tool used by more people so we get all the teething issues out of the way :).

**Comment by costinm** [comment]
I'm not sure this is an 'issue' - we can discuss it on the mailing list and
PR review.

**Comment by costinm** [comment]
Would you mind opening a PR ? I think istio/istio repo is the right place,
under install directory.

I think at this point the most critical part is an ansible script for
installing the raw VMs, for mesh expansion,
replacing the shell script we have. We also want to have a terraform or
other alternatives - but one way or another
I want to retire the script.

**Comment by geoand** [comment]
@costinm Thank you for the suggestion!

I'll open the PR tomorrow once we do some more testing and we can continue the discussion there as you mentioned

**Comment by andraxylia** [comment]
@geoand thanks for this work! Please add this to install/ansible. We will likely add ansible playbooks for VMs in the same directory. Maybe we can reuse the cluster_flavor variable, and add a list of VMs to the inventory.
Do you plan to work on the VM support as well?

**Comment by costinm** [comment]
To clarify: while ansible support for installing on k8s/openshift is nice, we have helm and 3 other solutions already. What is critically needed is ansible support for mesh expansion - installing the istio.deb and possibly dnsmasq deb, installing the config files, enabling the systemd and patching the dhcp config.
We currently do it with a script or manually.

**Comment by geoand** [comment]
Thank you for your comments!

Currently we don't have much experience with other VMs but that is something we could look into.
We'll also have to look into the Mesh expansion feature since it's something we haven't used at all.

**Comment by costinm** [comment]
Mesh expansion and 'other VMs' are the same. 

I would be happy to remove/deprecate the current hacked setup scripts for mesh expansion, and recommend using ansible for mesh expansion ( and teraform/etc when they become available ).

**Comment by costinm** [comment]
I believe this is done ?

**Comment by geoand** [comment]
Yes, they Ansible playbook has been Incorporated into Istio
