### ISSUE TITLE
wasm: stat prefix is hard-coded

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#27635]
Due to https://github.com/envoyproxy/envoy/pull/11808, stat prefix is now hardcoded to be "istio" in all istio extensions. Making it customizable again requires an ABI extension.

**Comment by douglas-reid** [comment]
Do we know if anyone is using this feature to use a prefix other than `istio`?

**Comment by kyessenov** [comment]
Wasm extensions are not stable, so I think it's OK to remove features. Of course, we don't want to break anyone, but I think there other way to customize the metric name.

**Comment by douglas-reid** [comment]
I think we were agreeing in different ways :). I'd be surprised if there was anyone out there customizing the metrics prefix.

I was looking at adding that to the proposal for a Telemetry API and decided that I can't imagine a common use case for needing to do that with Istio. It can always be done in Prom scrape config, etc.

**Comment by mandarjog** [comment]
Just to be clear, someone in the host code `registerPrometheusNamespace("istio")` is being called?
We need that control to go to the extension...

**Comment by kyessenov** [comment]
@mandarjog Correct. To give control to an extensions we need 1) ABI call, 2) make sure it's called on main once since the call not mutex protected.

**Comment by brianwolfe** [comment]
We are actually using this. Would it be accepted if we wanted to add this back in?

**Comment by mandarjog** [comment]
We definitely want to add the feature back. But previously it was based on convention and now we will need an additional abi call.
If you do what kuat suggested, or similar then we are good to go, but the change is in envoy first.

**Comment by mathetake** [comment]
fyi: if https://github.com/envoyproxy/envoy/pull/17357 lands, we can configure prometheus stats via foreign function calls from Wasm plugins.
