### ISSUE TITLE
Injection sidecar pod cannot access other services

### ISSUE THREAD

**Issue by JHDST** [istio/istio#27641]
After injecting sidecar， An error occurred while accessing other services through domain name inside the pod。
For example, pod1 passes through svc.cluster.local access pod2's servcie

**Comment by howardjohn** [comment]
Please give more info about your setup, what calls you are making, what is failing, the config, etc: https://github.com/istio/istio/wiki/Troubleshooting-Istio

**Comment by howardjohn** [comment]
Closing as we do not have enough info
