### ISSUE TITLE
istio/tools: add tcp load test for perf benchmark

### ISSUE THREAD

**Issue by carolynhu** [istio/istio#27647]
fortio's latest release added tcp load and echo, we could add this test in istio perf benchmark

**Comment by carolynhu** [comment]
cc @ldemailly @howardjohn @bianpengyuan

**Comment by daixiang0** [comment]
Details refer to [fortio release note](https://github.com/fortio/fortio/releases/tag/v1.8.0)

**Comment by ldemailly** [comment]
you can do also do fan out for both tcp and http now too 
https://github.com/fortio/fortio/releases/tag/v1.9.0
(and 1.9.1)

I just moved the latest_release to 1.11.2 let me know if that cause any issue with istio's automated tests
