### ISSUE TITLE
gen-eastwest-gateway.sh improvements

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#27644]
I recommend we switch the script to output an IstioOperator

This would help in cases where:
* Users want to use a binary other than `istioctl`, or customize the args. For example, I use a dev build of istioctl so I need to pass `--manifests`. Others may use `istioctl1.7.0`. Others may need to set an org profile with defaults (configuring custom CA, for example) (more on this later)
* Users can choose `manifest generate` or `install` or in cluster operator (I think this is working on since #27601)

I also recommend instead of using `profile: empty` we explicitly disable things. This will allow users to set a custom profile, but still have istiod/base disabled - this probably needs fixes in https://github.com/istio/istio/issues/27265 though to propogate the proxy config correctly.

cc @stevenctl @nmittler @tbarrella

**Comment by stevenctl** [comment]
Agree 100% on all points

**Comment by stevenctl** [comment]
Could it make sense to eventually have this as a component in the operator spec, users can simply have it set to `enabled`? Or is that too heavy.

**Comment by howardjohn** [comment]
> Could it make sense to eventually have this as a component in the operator spec, users can simply have it set to enabled? Or is that too heavy.

Wouldn't that just look like a user explicitly defining the output of the script? because they still have to fill in all the fields?

**Comment by stevenctl** [comment]
The values we pass to the script get used in multiple places in the final template. This would hide some of the implementation details like which env vars are set.

**Comment by nmnellis** [comment]
we are using the istio test framework and this script required us to download an istioctl binary. i would prefer if it used the istioctl in the test framework here https://github.com/istio/istio/tree/master/pkg/test/framework/components/istioctl

**Comment by nmittler** [comment]
@stevenctl perhaps we can split the script so that the generation of the `IstioOperator` CR is separate from the `istioctl` command? Then the test framework could just use the first part. WDYT?

**Comment by stevenctl** [comment]
Yeah. I think it makes it clearer to the user whats going on and gives those who want to further customize their gateway a good starting point.
