### ISSUE TITLE
Ansible playbook for Mesh Expansion and Multi-cloud

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#2765]
We need ansible playbook to automate the steps here:
https://istio.io/docs/setup/kubernetes/mesh-expansion.html

It can build on #2763 and re-use cluster_flavor, add ansible inventory/hosts.

**Comment by andraxylia** [comment]
cc @costinm

**Comment by howardjohn** [comment]
I don't think there are any plans to do this anymore
