### ISSUE TITLE
Istio manual protocol selection configuration is getting ignored

### ISSUE THREAD

**Issue by SwaminathAkella** [istio/istio#27661]
**Bug description**

We are working on configuring to support HTTPS support for our product. The flow we have is, Browser -> Istio -> NGNIX. We ran into to issues with the “Automatic Protocol Selection” of Istio, i.e., selecting HTTP 2.0 (which is resulting in failure in the upstream at NGNIX).

To resolve this issue, we are attempting to configure HTTP 1.1 (for switching to, “Manual Protocol Selection”).

Istio documentation referred: https://istio.io/v1.4/docs/ops/configuration/traffic-management/protocol-selection/

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[X] Developer Infrastructure

**Expected behavior**
- Protocol selected should change to HTTP 1.1, instead of HTTP 2.0 sent by the browser.

**Steps to reproduce the bug**
- Configure manual protocol selection, to select HTTP as following: 
Here’s the configuration done:
ports:
number: 443
name: http
protocol: HTTPS
tls:
mode: SIMPLE
privateKey: /etc/istio/ingressgateway-certs/tls.key
serverCertificate: /etc/istio/ingressgateway-certs/tls.crt

However, this configuration is getting ignored and protocol of HTTP 2.0 is still being selected

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
Istio 1.4.1
**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by esnible** [comment]
I tried to look at this, but I don't have my ingress set up for HTTPS.

What I did was install Istio, and the Httpbin sample.  Then from my laptop I did `curl -v <myip>/anything --http2-prior-knowledge`.  The httpbin pod's Envoy logged

```
[2020-10-01T14:01:03.037Z] "GET /anything HTTP/1.1" 200 - "-" 0 754 2 2 "10.73.71.199" "curl/7.64.1" "02a96643-35da-44c0-9566-719d7f9fde19" "169.61.18.12" "127.0.0.1:80" inbound|8000|http|httpbin.default.svc.cluster.local 127.0.0.1:39502 172.30.150.234:80 10.73.71.199:0 outbound_.8000_._.httpbin.default.svc.cluster.local default
```

However, I am using Istio pre-1.8 (master).  I see you are using Istio 1.4.  Can someone try this with HTTPS and Istio 1.4?

**Comment by howardjohn** [comment]
You have configured the port of the Gateway. This is for inbound traffic. The outbound traffic is determined byt the port name on `nginx`

**Comment by howardjohn** [comment]
This appears to be user error, not a bug. I recommend taking a look at https://preliminary.istio.io/latest/docs/ops/configuration/traffic-management/tls-configuration/
