### ISSUE TITLE
wasm: vm_ids are leaking

### ISSUE THREAD

**Issue by kyessenov** [istio/istio#27671]
Cycling vm_id in Wasm v8 filter every second, we are gaining about 10MB per minute. Something in v8 is leaking memory, since repeating the same experiment without vm_id cycling, keeps the memory stable:

Brief heap dump:
2482142.92kB 49.07% 49.07% 2482142.92kB 49.07%  std::allocator_traits::allocate
407524.99kB  8.06% 57.13% 407524.99kB  8.06%  wasm::vec::vec
334295.72kB  6.61% 63.74% 334295.72kB  6.61%  wasm::Module::serialize
329359.25kB  6.51% 70.25% 329359.25kB  6.51%  v8::internal::WeakObjects::WeakObjects
278653.38kB  5.51% 75.76% 1063271.25kB 21.02%  v8::internal::Isolate::Init
211263.11kB  4.18% 79.94% 211263.11kB  4.18%  v8::internal::BasicMemoryChunk::Initialize
131774.41kB  2.61% 82.54% 131774.41kB  2.61%  v8::internal::Isolate::InitializeCounters
127175.92kB  2.51% 85.06% 127175.92kB  2.51%  v8::internal::wasm::NativeModule::AddCodeWithCodeSpace
92470.85kB  1.83% 86.88% 92470.85kB  1.83%  v8::internal::AllocWithRetry
67090.24kB  1.33% 88.21% 67098.34kB  1.33%  std::_Rb_tree::_M_emplace_unique
56129.38kB  1.11% 89.32% 56129.38kB  1.11%  v8::internal::CodeObjectRegistry::RegisterNewlyAllocatedCodeObject
56053.08kB  1.11% 90.43% 56053.08kB  1.11%  v8::internal::MarkingWorklistsHolder::MarkingWorklistsHolder
   40134kB  0.79% 91.22%    40134kB  0.79%  v8::internal::ReadOnlyHeap::ExtendReadOnlyObjectCache
39495.31kB  0.78% 92.00% 43122.73kB  0.85%  v8::internal::SerializerDeserializer::Iterate
37454.20kB  0.74% 92.74% 37454.20kB  0.74%  Envoy::InlineStorage::operator new
33703.60kB  0.67% 93.41% 423458.98kB  8.37%  v8::internal::Heap::SetUp
28931.77kB  0.57% 93.98% 28931.77kB  0.57%  v8::internal::WasmInstanceObject::EnsureIndirectFunctionTableWithMinimumSize
13431.20kB  0.27% 94.25% 104478.28kB  2.07%  v8::internal::Heap::SetUpSpaces
 6018.52kB  0.12% 94.37% 30460.73kB   0.6%  wasm::Func::make
 4565.60kB  0.09% 94.46% 142133.35kB  2.81%  v8::internal::Isolate::Isolate
  885.59kB 0.018% 94.47% 386297.91kB  7.64%  v8::internal::MarkCompactCollector::MarkCompactCollector
  863.79kB 0.017% 94.49% 27618.25kB  0.55%  v8::internal::compiler::Pipeline::NewWasmHeapStubCompilationJob
  463.59kB 0.0092% 94.50% 41612.65kB  0.82%  v8::internal::NewSpace::NewSpace
  424.27kB 0.0084% 94.51% 1322646.80kB 26.15%  wasm::Store::make
  196.88kB 0.0039% 94.51% 61373.06kB  1.21%  v8::internal::ReadOnlyHeap::SetUp
  184.69kB 0.0037% 94.52% 51438.22kB  1.02%  v8::internal::compiler::NewJSToWasmCompilationJob
  118.97kB 0.0024% 94.52% 143397.66kB  2.84%  v8::internal::Isolate::New
  108.41kB 0.0021% 94.52% 106614.08kB  2.11%  std::vector::_M_realloc_insert
   98.39kB 0.0019% 94.52% 35458.40kB   0.7%  v8::internal::BackingStore::Allocate
   93.82kB 0.0019% 94.53% 3163891.79kB 62.55%  std::__shared_ptr::__shared_ptr
   93.56kB 0.0018% 94.53% 74930.35kB  1.48%  v8::internal::wasm::CompileJsToWasmWrappers
   71.02kB 0.0014% 94.53% 195055.55kB  3.86%  v8::internal::MemoryAllocator::AllocateChunk
   46.41kB 0.00092% 94.53% 3164543.78kB 62.56%  std::__shared_count::__shared_count
   24.22kB 0.00048% 94.53% 108516.61kB  2.15%  v8::internal::Heap::ReserveSpace
   15.93kB 0.00031% 94.53% 102128.37kB  2.02%  wasm::Module::deserialize
   15.48kB 0.00031% 94.53% 283297.92kB  5.60%  wasm::Instance::make
    7.81kB 0.00015% 94.53% 35360.01kB   0.7%  v8::internal::Heap::AllocateExternalBackingStore
    6.68kB 0.00013% 94.53% 283233.99kB  5.60%  v8::internal::wasm::InstantiateToInstanceObject
    4.92kB 9.7e-05% 94.53% 2306729.44kB 45.61%  Envoy::Config::GrpcMuxImpl::onDiscoveryResponse
    0.94kB 1.9e-05% 94.53% 194710.93kB  3.85%  v8::internal::compiler::CompileWasmCapiCallWrapper

[profile001.pdf](https://github.com/istio/istio/files/5313136/profile001.pdf)

**Comment by PiotrSikora** [comment]
Could you try with older version of V8? Alternatively, do you have a repro script that I could use?

**Comment by kyessenov** [comment]
See https://github.com/envoyproxy/envoy-wasm/issues/615.

Steps to reproduce: run three things in parallel from PR https://github.com/istio/proxy/pull/3032
1. bazel-bin/src/envoy/envoy -c tools/extensionserver/envoy.yaml (you can remove stats filter there)
2. make sure tools/extensionserver/testdata/metadata_exchange.yaml looks like the following:
```yaml
 extensions:
 - name: metadata_exchange
   path: mx.wasm # this is MX pre-compiled filter
   vm_id: id
   runtime: v8
   configuration:
     max_peer_cache_size: 60
```

Run auto-updater:
```
while true; do sed "s/  vm_id: .*/  vm_id: id$(date +%s%N)/" -i tools/extensionserver/testdata/metadata_exchange.yaml; sleep 1; done
```

3. Run the extension server:
```
go run tools/extensionserver/main/main.go -c tools/extensionserver/testdata/ -s 0
```

**Comment by PiotrSikora** [comment]
OK, I've spent the last few days trying to track this down... I've tried many versions of V8 (8.2 to 8.7), with and without cloning, with and without precompiled modules, with and without precise garbage collection in V8, and with various sanitizers, but I didn't locate the leak yet...

The good news is that WAVM doesn't leak memory... although, it's only usable with precompiled modules.

**Comment by PiotrSikora** [comment]
@mathetake could you take a look at this?

**Comment by mathetake** [comment]
OK, give me some time

**Comment by mathetake** [comment]
I spent a whole day today, and I'm now almost sure that this is the V8 side's issue, not the proxy-wasm-cpp-host. But I need more time to identify the root cause. Stay tuned!

**Comment by PiotrSikora** [comment]
@mathetake thanks for checking! Yeah, I'm positive it's in V8. I filled the issue with them: https://bugs.chromium.org/p/v8/issues/detail?id=11034.

**Comment by mathetake** [comment]
@PiotrSikora haha, I am about to submit an issue to V8 with the exactly the same script as you put in that issue :laughing: Thank you for submitting
