### ISSUE TITLE
Zipkin-to-Stackdriver issue

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio#2767]
Reported via: https://github.com/GoogleCloudPlatform/stackdriver-zipkin/issues/49

This needs investigation (and a mitigation plan).

**Comment by bianpengyuan** [comment]
I was able to collect tracing of sample bookinfo app through zipkin-to-stackdriver without any error logs. I am not sure how to reproduce it so I am asking the reporter of the linked issue there.
