### ISSUE TITLE
grpc xds client does not work

### ISSUE THREAD

**Issue by sky91** [istio/istio#27673]
**Affected product area**
[X] Networking

**Version**
1.7.3

**Steps to reproduce the bug**
Use grpc xds name resolver (go/java/c) to connect to istio-pilot xds server.

**Description**
Instead of envoy, we use [grpc xds name resolver](https://github.com/grpc/grpc-go/tree/master/xds) as xDS consumer. Due to [the implementation of grpc xds client](https://github.com/grpc/grpc-go/blob/v1.32.0/xds/internal/client/client_xds.go#L82), we really need [this change](https://github.com/istio/istio/commit/086f58f9c3db66327d8556fbfdd8d0c7f58f1f17#diff-f01d08efca9a422a89bb404447442aa0) from #25823. Could you please include it in next release.

**Comment by howardjohn** [comment]
If the PR is merged it will be in the next release.
