### ISSUE TITLE
Pods injected twice will fail to startup

### ISSUE THREAD

**Issue by pavanfhw** [istio/istio#27675]
**Bug description**

When restoring a backup of an istio injected namespace the istio-proxy container on the pods goes into CrashLoopBackOff because of the error:
`error	invalid prometheus scrape configuration: application port is the same as agent port, which may lead to a recursive loop. Ensure pod does not have prometheus.io/port=15020 label, or that injection is not happening multiple times`

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Pods recreation without crashes in istio-proxy

**Steps to reproduce the bug**
Install velero with restic support
Take a velero backup of a namespace with istio injection enabled
Delete the namespace
Make a restore of the namespace 

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
client version: 1.7.0
control plane version: 1.7.0
data plane version: 1.7.0 (35 proxies)

Client Version: v1.18.6+k3s1
Server Version: v1.18.6+k3s1

**How was Istio installed?**
istioctl install --set profile=default

**Environment where bug was observed (cloud vendor, OS, etc)**
K3OS cluster

The error says "Ensure pod does not have prometheus.io/port=15020 label". The pods does have that label as all other pods that are not crashing.
It also says to check if injection is not happening multiple times. But the namespace description is the same as all other namespaces with istio-injection.

**Comment by howardjohn** [comment]
Can you post the pod spec that is triggering this? 

Are you sure you are not doing `istioctl kube-inject` into an auto injected namespace?

Can you run `kubectl get mutatingwebhookconfigurations.admissionregistration.k8s.io`?

**Comment by pavanfhw** [comment]
Pod in CrashLoopBackOff description
```
Name:         mautic-75665fbdcc-pj9rt
Namespace:    backup
Priority:     0
Node:         1-k8w.vulca.cloud/158.69.53.139
Start Time:   Thu, 01 Oct 2020 14:41:16 +0000
Labels:       app=mautic
              istio.io/rev=default
              pod-template-hash=75665fbdcc
              security.istio.io/tlsMode=istio
              service.istio.io/canonical-name=mautic
              service.istio.io/canonical-revision=latest
              velero.io/backup-name=backup-test
              velero.io/restore-name=backup-test-20201001144118
Annotations:  backup.velero.io/backup-volumes: mautic-volume
              prometheus.io/path: /stats/prometheus
              prometheus.io/port: 15020
              prometheus.io/scrape: true
              sidecar.istio.io/status:
                {"version":"8e6e902b765af607513b28d284940ee1421e9a0d07698741693b2663c7161c11","initContainers":["istio-init"],"containers":["istio-proxy"]...
Status:       Running
IP:           10.42.11.67
IPs:
  IP:           10.42.11.67
Controlled By:  ReplicaSet/mautic-75665fbdcc
Init Containers:
  restic-wait:
    Container ID:  containerd://41d1a5bbe3f1d821722979d5cac20bdfafd84a5a2871a03497683d06b4baa4a1
    Image:         velero/velero-restic-restore-helper:v1.5.1
    Image ID:      docker.io/velero/velero-restic-restore-helper@sha256:a448e8ec2764742282ea5fa254660cfb164e84fe846fd26d9496c413b27ca528
    Port:          <none>
    Host Port:     <none>
    Command:
      /velero-restic-restore-helper
    Args:
      d1e4b98b-1e2f-40d4-baf0-45abc9343de7
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 01 Oct 2020 14:41:39 +0000
      Finished:     Thu, 01 Oct 2020 15:53:18 +0000
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  128Mi
    Requests:
      cpu:     100m
      memory:  128Mi
    Environment:
      POD_NAMESPACE:  backup (v1:metadata.namespace)
      POD_NAME:       mautic-75665fbdcc-pj9rt (v1:metadata.name)
    Mounts:
      /restores/mautic-volume from mautic-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-grhjg (ro)
  istio-init:
    Container ID:  containerd://35ed7a82c833bafa7ce0d50e9916c68ca7dd8b1da31e12aeec461adab34829a8
    Image:         docker.io/istio/proxyv2:1.7.0
    Image ID:      docker.io/istio/proxyv2@sha256:c1f1b45a4162509f86aa82d0148aef55824454e7204f27f23dddc9d7f4ae7cd1
    Port:          <none>
    Host Port:     <none>
    Args:
      istio-iptables
      -p
      15001
      -z
      15006
      -u
      1337
      -m
      REDIRECT
      -i
      *
      -x
      
      -b
      *
      -d
      15090,15021,15020
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 01 Oct 2020 15:53:19 +0000
      Finished:     Thu, 01 Oct 2020 15:53:19 +0000
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     2
      memory:  1Gi
    Requests:
      cpu:     10m
      memory:  10Mi
    Environment:
      DNS_AGENT:  
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-grhjg (ro)
Containers:
  mautic:
    Container ID:   containerd://5f01d55adcc44180025627dcfb56dd9538a4b633728ea636ad7b7949827d6307
    Image:          mautic/mautic:v3
    Image ID:       docker.io/mautic/mautic@sha256:6b7d0fb781ddfc9f39361c6495196f9d7c6cf2fdbd6b96fa9e6085e17ed9e37a
    Port:           80/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Fri, 02 Oct 2020 18:31:49 +0000
      Finished:     Fri, 02 Oct 2020 18:32:34 +0000
    Ready:          False
    Restart Count:  277
    Environment:
      MAUTIC_DB_HOST:          mautic-mysql
      MAUTIC_DB_USER:          mautic
      MAUTIC_DB_NAME:          mautic
      MAUTIC_DB_PASSWORD:      <set to the key 'MAUTIC_DB_PASSWORD' in secret 'mautic-mysql-secrets'>  Optional: false
      MYSQL_PORT_3306_TCP:     3306
      MAUTIC_RUN_CRON_JOBS:    true
      PHP_INI_DATE_TIMEZONE:   America/Sao_Paulo
      PHP_MEMORY_LIMIT:        1024M
      PHP_MAX_UPLOAD:          100M
      PHP_MAX_EXECUTION_TIME:  600
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-grhjg (ro)
      /var/www/html from mautic-volume (rw)
  istio-proxy:
    Container ID:  containerd://061f9cec558e99f87d0c8089388151b51ac00a8d011981d3d0bb42152e7fbf11
    Image:         docker.io/istio/proxyv2:1.7.0
    Image ID:      docker.io/istio/proxyv2@sha256:c1f1b45a4162509f86aa82d0148aef55824454e7204f27f23dddc9d7f4ae7cd1
    Port:          15090/TCP
    Host Port:     0/TCP
    Args:
      proxy
      sidecar
      --domain
      $(POD_NAMESPACE).svc.cluster.local
      --serviceCluster
      mautic.$(POD_NAMESPACE)
      --proxyLogLevel=warning
      --proxyComponentLogLevel=misc:error
      --trust-domain=cluster.local
      --concurrency
      2
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Fri, 02 Oct 2020 18:31:21 +0000
      Finished:     Fri, 02 Oct 2020 18:31:21 +0000
    Ready:          False
    Restart Count:  317
    Limits:
      cpu:     2
      memory:  1Gi
    Requests:
      cpu:      100m
      memory:   128Mi
    Readiness:  http-get http://:15021/healthz/ready delay=1s timeout=1s period=2s #success=1 #failure=30
    Environment:
      JWT_POLICY:                    third-party-jwt
      PILOT_CERT_PROVIDER:           istiod
      CA_ADDR:                       istiod.istio-system.svc:15012
      POD_NAME:                      mautic-75665fbdcc-pj9rt (v1:metadata.name)
      POD_NAMESPACE:                 backup (v1:metadata.namespace)
      INSTANCE_IP:                    (v1:status.podIP)
      SERVICE_ACCOUNT:                (v1:spec.serviceAccountName)
      HOST_IP:                        (v1:status.hostIP)
      CANONICAL_SERVICE:              (v1:metadata.labels['service.istio.io/canonical-name'])
      CANONICAL_REVISION:             (v1:metadata.labels['service.istio.io/canonical-revision'])
      PROXY_CONFIG:                  {"proxyMetadata":{"DNS_AGENT":""}}
                                     
      ISTIO_META_POD_PORTS:          [
                                         {"containerPort":80,"protocol":"TCP"}
                                         ,{"name":"http-envoy-prom","containerPort":15090,"protocol":"TCP"}
                                     ]
      ISTIO_META_APP_CONTAINERS:     mautic,istio-proxy
      ISTIO_META_CLUSTER_ID:         Kubernetes
      ISTIO_META_INTERCEPTION_MODE:  REDIRECT
      ISTIO_METAJSON_ANNOTATIONS:    {"backup.velero.io/backup-volumes":"mautic-volume","prometheus.io/path":"/stats/prometheus","prometheus.io/port":"15020","prometheus.io/scrape":"true","sidecar.istio.io/status":"{\"version\":\"8e6e902b765af607513b28d284940ee1421e9a0d07698741693b2663c7161c11\",\"initContainers\":[\"istio-init\"],\"containers\":[\"istio-proxy\"],\"volumes\":[\"istio-envoy\",\"istio-data\",\"istio-podinfo\",\"istio-token\",\"istiod-ca-cert\"],\"imagePullSecrets\":null}"}
                                     
      ISTIO_META_WORKLOAD_NAME:      mautic-75665fbdcc-pj9rt
      ISTIO_META_OWNER:              kubernetes://apis/v1/namespaces/backup/pods/mautic-75665fbdcc-pj9rt
      ISTIO_META_MESH_ID:            cluster.local
      DNS_AGENT:                     
      ISTIO_KUBE_APP_PROBERS:        {}
      ISTIO_PROMETHEUS_ANNOTATIONS:  {"scrape":"true","path":"/stats/prometheus","port":"15020"}
    Mounts:
      /etc/istio/pod from istio-podinfo (rw)
      /etc/istio/proxy from istio-envoy (rw)
      /var/lib/istio/data from istio-data (rw)
      /var/run/secrets/istio from istiod-ca-cert (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-grhjg (ro)
      /var/run/secrets/tokens from istio-token (rw)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  mautic-volume:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  mautic-volume-claim
    ReadOnly:   false
  default-token-grhjg:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-grhjg
    Optional:    false
  istio-envoy:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  istio-data:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  istio-podinfo:
    Type:  DownwardAPI (a volume populated by information about the pod)
    Items:
      metadata.labels -> labels
      metadata.annotations -> annotations
  istio-token:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  43200
  istiod-ca-cert:
    Type:        ConfigMap (a volume populated by a ConfigMap)
    Name:        istio-ca-root-cert
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
```
kubectl get mutatingwebhookconfigurations.admissionregistration.k8s.io
```
NAME                               WEBHOOKS   AGE
cert-manager-webhook     1                     71d
istio-sidecar-injector          1                     13d
```
About me doing `istioctl kube-inject` I don't think so. The problem occurs after the velero restore, I don't run any commands after this. Maybe velero creates an injected ns and the injects again... How can a double injection be indentified?

**Comment by howardjohn** [comment]
I am not familiar with `velero restore` but I bet this is what happens - you start a pod, it gets injected. Then valero runs essentially `kubectl get pods -oyaml | kubectl apply -f`. At this point, it is injected *again*

**Comment by pavanfhw** [comment]
Just to confirm, before `velero restore` there are no pods. The namespace was delete. You mean velero causes the first and second injection?

I think not backing up and restoring the pods, but only the deployment, could solve this. But I can't do it since the volumes backup are triggered by taking the pods backup.

**Comment by howardjohn** [comment]
Yeah I mean there is some time between `get pods` and `apply` - but valero is storing the injected state, so it gets injected twice.

**Comment by Samze** [comment]
We also encountered this, fortunately for us we could exclude the pod resources and this worked.

**Comment by pt-bhavsar** [comment]
Facing similar issue. Here is the log:

$ kubectl logs httpbin-54cb97745b-649fn istio-proxy
2020-10-12T03:03:19.538710Z	info	FLAG: --concurrency="2"
2020-10-12T03:03:19.538849Z	info	FLAG: --disableInternalTelemetry="false"
2020-10-12T03:03:19.539059Z	info	FLAG: --domain="default.svc.cluster.local"
2020-10-12T03:03:19.539325Z	info	FLAG: --help="false"
2020-10-12T03:03:19.539350Z	info	FLAG: --id=""
2020-10-12T03:03:19.539449Z	info	FLAG: --ip=""
2020-10-12T03:03:19.539477Z	info	FLAG: --log_as_json="false"
2020-10-12T03:03:19.539497Z	info	FLAG: --log_caller=""
2020-10-12T03:03:19.539522Z	info	FLAG: --log_output_level="default:info"
2020-10-12T03:03:19.539545Z	info	FLAG: --log_rotate=""
2020-10-12T03:03:19.539571Z	info	FLAG: --log_rotate_max_age="30"
2020-10-12T03:03:19.539598Z	info	FLAG: --log_rotate_max_backups="1000"
2020-10-12T03:03:19.539626Z	info	FLAG: --log_rotate_max_size="104857600"
2020-10-12T03:03:19.539653Z	info	FLAG: --log_stacktrace_level="default:none"
2020-10-12T03:03:19.539699Z	info	FLAG: --log_target="[stdout]"
2020-10-12T03:03:19.539724Z	info	FLAG: --meshConfig="./etc/istio/config/mesh"
2020-10-12T03:03:19.539746Z	info	FLAG: --mixerIdentity=""
2020-10-12T03:03:19.539845Z	info	FLAG: --outlierLogPath=""
2020-10-12T03:03:19.539863Z	info	FLAG: --proxyComponentLogLevel="misc:error"
2020-10-12T03:03:19.539885Z	info	FLAG: --proxyLogLevel="warning"
2020-10-12T03:03:19.539906Z	info	FLAG: --serviceCluster="httpbin.default"
2020-10-12T03:03:19.539923Z	info	FLAG: --serviceregistry="Kubernetes"
2020-10-12T03:03:19.539949Z	info	FLAG: --stsPort="0"
2020-10-12T03:03:19.539975Z	info	FLAG: --templateFile=""
2020-10-12T03:03:19.539998Z	info	FLAG: --tokenManagerPlugin="GoogleTokenExchange"
2020-10-12T03:03:19.540031Z	info	FLAG: --trust-domain="cluster.local"
2020-10-12T03:03:19.540114Z	info	Version 1.7.3-9686754643d0939c1f4dd0ee20443c51183f3589-Clean
2020-10-12T03:03:19.542354Z	info	Obtained private IP [10.1.0.243]
2020-10-12T03:03:19.542855Z	info	Apply proxy config from env {"proxyMetadata":{"DNS_AGENT":""}}

2020-10-12T03:03:19.548682Z	info	Effective config: binaryPath: /usr/local/bin/envoy
concurrency: 2
configPath: ./etc/istio/proxy
controlPlaneAuthPolicy: MUTUAL_TLS
discoveryAddress: istiod.istio-system.svc:15012
drainDuration: 45s
envoyAccessLogService: {}
envoyMetricsService: {}
parentShutdownDuration: 60s
proxyAdminPort: 15000
proxyMetadata:
  DNS_AGENT: ""
serviceCluster: httpbin.default
statNameLength: 189
statusPort: 15020
terminationDrainDuration: 5s
tracing:
  zipkin:
    address: zipkin.istio-system:9411

2020-10-12T03:03:19.550254Z	info	Proxy role: &model.Proxy{Type:"sidecar", IPAddresses:[]string{"10.1.0.243"}, ID:"httpbin-54cb97745b-649fn.default", Locality:(*envoy_config_core_v3.Locality)(nil), DNSDomain:"default.svc.cluster.local", ConfigNamespace:"", Metadata:(*model.NodeMetadata)(nil), SidecarScope:(*model.SidecarScope)(nil), PrevSidecarScope:(*model.SidecarScope)(nil), MergedGateway:(*model.MergedGateway)(nil), ServiceInstances:[]*model.ServiceInstance(nil), IstioVersion:(*model.IstioVersion)(nil), ipv6Support:false, ipv4Support:false, GlobalUnicastIP:"", XdsResourceGenerator:model.XdsResourceGenerator(nil), Active:map[string]*model.WatchedResource(nil), ActiveExperimental:map[string]*model.WatchedResource(nil), RequestedTypes:struct { CDS string; EDS string; RDS string; LDS string }{CDS:"", EDS:"", RDS:"", LDS:""}}
2020-10-12T03:03:19.550288Z	info	JWT policy is first-party-jwt
2020-10-12T03:03:19.550532Z	info	PilotSAN []string{"istiod.istio-system.svc"}
2020-10-12T03:03:19.550678Z	info	MixerSAN []string{"spiffe://cluster.local/ns/istio-system/sa/istio-mixer-service-account"}
2020-10-12T03:03:19.551433Z	info	sa.serverOptions.CAEndpoint == istiod.istio-system.svc:15012
2020-10-12T03:03:19.551476Z	info	Using user-configured CA istiod.istio-system.svc:15012
2020-10-12T03:03:19.551502Z	info	istiod uses self-issued certificate
2020-10-12T03:03:19.551662Z	info	the CA cert of istiod is: -----BEGIN CERTIFICATE-----
-----END CERTIFICATE-----

2020-10-12T03:03:19.679461Z	info	sds	SDS gRPC server for workload UDS starts, listening on "./etc/istio/proxy/SDS" 

**2020-10-12T03:03:19.679638Z	info	Prometheus scraping configuration: {true /stats/prometheus 15020}
2020-10-12T03:03:19.679720Z	error	invalid prometheus scrape configuration: application port is the same as agent port, which may lead to a recursive loop. Ensure pod does not have prometheus.io/port=15020 label, or that injection is not happening multiple times
Error: invalid prometheus scrape configuration: application port is the same as agent port, which may lead to a recursive loop. Ensure pod does not have prometheus.io/port=15020 label, or that injection is not happening multiple times**

**Comment by howardjohn** [comment]
To fix this we would need https://github.com/istio/istio/issues/25931

**Comment by bali2016** [comment]
I'm also encountered this issue with very similar logs above, so waiting for the fix ready.

**Comment by howardjohn** [comment]
@bali2016 this is not strictly a "bug" necessarily. Its 100% an invalid configuration on your side, you are double injecting the pod. https://github.com/istio/istio/issues/25931 will just make this something that is legal to do, although its still a sign you have misconfigured something

**Comment by bali2016** [comment]
The logs shows ```2020-10-15T13:16:21.532584Z	info	Prometheus scraping configuration: {true /stats/prometheus 15020}
Error: invalid prometheus scrape configuration: application port is the same as agent port, which may lead to a recursive loop. Ensure pod does not have prometheus.io/port=15020 label, or that injection is not happening multiple times```

So does it mean the Prometheus should not use 15020 port?

**Comment by howardjohn** [comment]
It means one of:
* You annotated your pod with `prometheus.io/port: 15020` (seems unlikely)
* Your pod went through auto injection twice

**Comment by pt-bhavsar** [comment]
> 
> 
> @bali2016 this is not strictly a "bug" necessarily. Its 100% an invalid configuration on your side, you are double injecting the pod. #25931 will just make this something that is legal to do, although its still a sign you have misconfigured something

You are right about double injecting the pod. I deleted my deployment and disabled auto injection and then enabled it again. I did kubectl apply -f deplyment.yaml. That resolved the issue for me.

**Comment by doughepi** [comment]
Running into this as well using Velero for pod backup and restores. We cannot exclude the pods from the restore because they have volumes that need to be restored. 

Although restoring with double injection (from the istio webhook and Velero) is a misconfiguration that #25931 would allow, Velero does not currently have functionality to exclude the istio injected resources in its backups. I believe that allowing injection idempotency and printing a warning message is still a better behavior than failing outright.

**Comment by nrb** [comment]
Maintainer on Velero chiming in here!

From Velero's point of view, we restore most annotations as-is, since we don't know exactly what effect removing them will have. The ones we remove are done very purposefully, and mostly have to do with PV/PVC binding.

However, that decision definitely has side effects in cases like this, where the controls are designed under the (reasonable) assumption that they're the only one modifying the objects.

From our side, we could have a `RestoreItemAction` plugin for pods that could remove that annotation, though it does get unwieldy to maintain all those special cases. Also, it wouldn't solve for anyone doing the equivalent of what Velero does manually (`kubectl get` the YAML/JSON on backup, then `kubectl apply` it on restore, in very basic terms) with Istio.

**Comment by howardjohn** [comment]
@nrb are you referring to the `prometheus.io` annotation? I think that is just a small symptom of this. The real root issue is when a Pod is created, istio will rewrite the pod spec, add annotations, add containers, tweak settings, all sorts of things. This process is not idempotent.

From the k8s docs:
> Mutating webhooks must be idempotent, able to successfully process an object they have already admitted and potentially modified. This is true for all mutating admission webhooks, since any change they can make in an object could already exist in the user-provided object, but it is essential for webhooks that opt into reinvocation.
https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#idempotence

So Istio violates this, because of the assumption that webhook will be invoked exactly one time due to `reinvocationPolicy=Never` ("the webhook must not be called more than once in a single admission evaluation"). This assumption of course fails in the velero (or `kubectl get | kubectl apply`) case.

https://github.com/istio/istio/issues/25931 would solve all of this
