### ISSUE TITLE
Doc Regarding "ability to run a pilot dedicated for the gateway"

### ISSUE THREAD

**Issue by victorrodriguez1984** [istio/istio#27689]
**Describe the feature request**
In a 1.7.2 Istio notes, describes 

"- ability to run a pilot dedicated for the gateway, isolated from the main pilot. This is more robust, safer on upgrades
and allows a bit more flexibility." but i did not found docs related, could anybody help me?

**Describe alternatives you've considered**

[X ] Docs
[X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
https://istio.io/latest/docs/setup/upgrade/canary/. It says "upgrades" but its a bit misleading, it can be used for this purpose sa well
