### ISSUE TITLE
Move WorkloadGroup/WorkloadEntry to core API group

### ISSUE THREAD

**Issue by liminw** [istio/istio#27682]
In "Mesh Expansion: VM security" [proposal](https://docs.google.com/document/d/1-612Sgz_skeoX44dw3MU6Z8ONgq1f29wLUI9zggyLec), we propose to use WorkloadGroup to decide the namespace part of VM identity (“spiffe://{trustdomain}/ns/{namespace}/sa/{serviceaccount}”). 

Currently WorkloadGroup/WorkloadEntry is added to "networking.istio.io" API group, which is not accurate because it is also a critical resource that is used by security admin to decide VM's identity. Because api group is often used in k8s RBAC to decide which resources an admin controls (e.g, a security admin control all resources under "security.istio.io"), it is important to put the resource in the right API group. 

WorkloadGroup/WorkloadEntry is analogous to k8s Deployment/Pod resources, which are in the "core" api group (https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#pod-v1-core). We can introduce a "core" or "core.istio.io" api group, and add WorkloadGroup/WorkloadEntry there. 

**Bug description**

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Comment by howardjohn** [comment]
I do not think we should push complexity/backwards incompatible changes onto our users and our developers for this.

ServiceEntry is also has ServiceAccount, should it also be core? DR and GW have SAN, are they "core"?

I don't see how the comparison of `core` in Kubernetes maps to Istio. I think `core` there mostly just means "it happened before we came up with group names".

**Comment by liminw** [comment]
ServiceEntry or DestinationRule is not used for IdentityFederation, i.e. it does not "decide" workloads' identities. But WorkloadGroup does. 

WorkloadGroup/WorkloadEntry are relatively new resources we added to support mesh expansion. It is better to update it early to prevent backwards incompatibility issues in the future.

**Comment by rshriram** [comment]
IMO core is overused and less understood. A lot of networking aPIs are core APIs, without which you cant derive any value in Istio.

I also think this statement is an over generalization
>Because api group is often used in k8s RBAC to decide which resources an admin controls (e.g, a security admin control all resources under "security.istio.io"), it is important to put the resource in the right API group.

because this is implying that people do not use finer grained acls to decide what resources are allowed to who. We can always provide documented examples on how to do this as part of our operations manual. Nor do I buy the argument that a security admin gets involved in bootstrapping each and every VM. Its is also done by application developers depending on the company. Practices vary with organizations. 

K8S has given people all the knobs to enforce finer grained authz. If people dont use it, its their choice.

**Comment by liminw** [comment]
Yes, k8s provides fine grained authorization. What I am concerned of is the confusion it brings when it comes to which admin is responsible for which API. I assume "apiGroup" is introduced to serve this purpose. We can certainly provide documentation that "Workload group is also used for identity federation, make sure your security admin is aware of it", but not all users read detailed documentation very carefully (we see a lot of security vulnerability issues caused by people not reading fine print documentation carefully). 

I am talking about namespace-level security admin. If the common use case is that there is only one admin responsible for everything in a namespace, I think it is not a big deal in terms of api group. 

Anyway, I just want to bring up my thought so that we can make a wise decision before mesh expansion APIs are widely adopted.
