### ISSUE TITLE
Perf dashboard latency quantiles returns server error 500

### ISSUE THREAD

**Issue by poussa** [istio/istio#27690]
**Bug description**

The Istio performance dashboard latency section gives you `server error 500`

https://perf.dashboard.istio.io/benchmarks/latency_vs_conn/
https://perf.dashboard.istio.io/benchmarks/latency_vs_qps/

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

You get the latency graphs similar to CPU and memory graphs.

**Steps to reproduce the bug**

1. Go to https://perf.dashboard.istio.io
2. Select "Benchnarks" form the left menu panel
3. Select Latency Quantiles
4 Select either of the two options

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

NA

**How was Istio installed?**

NA

**Environment where bug was observed (cloud vendor, OS, etc)**

NA

**Comment by carolynhu** [comment]
@poussa thanks for filing this! a duplicate ticket is https://github.com/istio/istio/issues/27610

I'm working on fixing it!

**Comment by poussa** [comment]
Working again. Thanks @carolynhu !
