### ISSUE TITLE
[Test Framework] East-west gateway fails to deploy for single-cluster

### ISSUE THREAD

**Issue by nmittler** [istio/istio#27693]
We're seeing this in the istio.io repository, which runs primarily single-cluster configurations.

For example: https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/8254/doc.test.profile_default_istio.io/232

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[x] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by nmittler** [comment]
Turns out this was an issue when running locally with pre-existing kind clusters.  Closing this now.

FYI @ericvn @frankbu

**Comment by xulingqing** [comment]
I met the issue `failed waiting for istio-eastwestgateway to become ready` and solved it by creating a new Kind cluster with this special config
```
kind create cluster --name istio-test --config prow/config/trustworthy-jwt.yaml
```

**Comment by ericvn** [comment]
@xulingqing Correct. This is documented in the istio/istio.io/tests/README. Maybe we need to add something in the istio.io/istio README.
