### ISSUE TITLE
--set values.base.enableCRDTemplates=false not working with istioctl

### ISSUE THREAD

**Issue by elfinhe** [istio/istio#27704]
**Bug description**

When looking at https://github.com/istio/istio/blob/0321da58ca86fc786fb03a68afd29d082477e4f2/manifests/charts/base/templates/crds.yaml, we think istioctl can also support --set values.base.enableCRDTemplates=false to disable the CRDTemplates.

However, `istioctl manifest generate  --set values.base.enableCRDTemplates=false` still generate all CRDs. Because istioctl import all crds in crds/ folder regardless the templates/crds.yaml: https://github.com/istio/istio/blob/master/operator/pkg/helm/helm.go#L146-L157

Currently, there is no negative impact on istio installation, but it will block us for supportinng CRDs templating in the future.

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
The flag is intended exclusively to support helm2, which ignores the crd/ directory. Just for some reference on why it behaves the way it does.

**Comment by elfinhe** [comment]
> The flag is intended exclusively to support helm2, which ignores the crd/ directory. Just for some reference on why it behaves the way it does.

so the root cause - inconsistent behavior between helm2 and helm3 in terms of including crds? Sorry i don't know the previous context, but I thought if we always respect templates/crds.yaml, `helm2`, `helm3`, and `istioctl` will work.

**Comment by howardjohn** [comment]
`helm2` has no `crd/` knowledge. `helm3` breaks on upgrades if CRDs are in `templates/`, since it won't do special processing of CRDs. istioctl doesn't care where they are

**Comment by elfinhe** [comment]
Closing....

This is the trade-off we made among helm2, helm3, and istioctl. Since now it works well for three of them. If we want CRD templating in `istioctl`, we can revive this issue, and do something similar to https://github.com/istio/istio/pull/27706/files
