### ISSUE TITLE
Implement VM Auto-Registration

### ISSUE THREAD

**Issue by stevenctl** [istio/istio#27701]
Tracking impl of this [design doc](https://docs.google.com/document/d/10TyPy-6bOs0_7JljGpc2RneDdsaR9GktjwwaaVbz6fs/edit). Will likely take pieces from https://github.com/istio/istio/pull/25434

- [X] Initial implementation (#27761)
- [ ] Heartbeat-based cleanup
- [ ] Update WorkloadEntry on WorkloadGroup change.

**Comment by adiprerepa** [comment]
I think this is implemented, appropriate to close?

**Comment by stevenctl** [comment]
@adiprerepa there are follow up items I'd like to track with this issue.

**Comment by stevenctl** [comment]
We've added a long-term cleanup (based on max-conn age), deleting the Group is now handled. We won't handle Updates to the group directly. 

A separate issue has been created for multi-cluster compat.
