### ISSUE TITLE
Update Virtual Machine docs for secret tokens

### ISSUE THREAD

**Issue by danielkwinsor** [istio/istio#27711]
**Bug description**
https://istio.io/latest/docs/setup/install/virtual-machine/ contains a step to create a secret token.  This step is not working on k8s 18.8 or 19.2.  It was working on k8s 16.3, and also the previous documentation from around 1.7.1 worked to create secrets, as in
`kubectl create secret generic cacerts -n istio-system \
    --from-file=samples/certs/ca-cert.pem \
    --from-file=samples/certs/ca-key.pem \
    --from-file=samples/certs/root-cert.pem \
    --from-file=samples/certs/cert-chain.pem`

[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
The current output of 
`Error from server (NotFound): the server could not find the requested resource`
Replaced with successful token.

**Steps to reproduce the bug**
`echo '{"kind":"TokenRequest","apiVersion":"authentication.k8s.io/v1","spec":{"audiences":["istio-ca"],"expirationSeconds":'$tokenexpiretime'}}' | kubectl create --raw /api/v1/namespaces/$VM_NAMESPACE/serviceaccounts/$SERVICE_ACCOUNT/token -f - | jq -j '.status.token' > "${WORK_DIR}"/istio-token`
as per https://istio.io/latest/docs/setup/install/virtual-machine/

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
istioctl version --remote
client version: 1.7.2
control plane version: 1.7.2
data plane version: 1.7.2 (7 proxies)
kubectl version --short  
Client Version: v1.19.2
Server Version: v1.19.2

**How was Istio installed?**
$ curl -L https://istio.io/downloadIstio | ISTIO_VERSION=1.7.2 TARGET_ARCH=x86_64 sh -

**Environment where bug was observed (cloud vendor, OS, etc)**
Mac OS

CC @williamaronli as I saw it was similar to #27691

**Comment by danielkwinsor** [comment]
In https://istio.io/latest/docs/setup/install/virtual-machine/#configure-the-virtual-machine , step 10 is redundant as part of step 4.

on my system, using usr/local/bin/istio-start.sh instead of systemctl, I had to mkdir -p /var/log/istio and add that to the chown -R istio-proxy otherwise no logs.

**Comment by douglas-reid** [comment]
@danielkwinsor have you looked at the experimental istioctl command for generating all of the VM's configs (including tokens) ?

**Comment by sandy0823** [comment]
It didn't work when I done an operation as https://istio.io/latest/docs/setup/install/virtual-machine/。The error (Error from server (NotFound): the server could not find the requested resource) still exists.

Version (include the output of istioctl version --remote and kubectl version --short and helm version if you used Helm)
istioctl version --remote
client version: 1.7.3
control plane version: 1.7.3
data plane version: 1.7.3 (8 proxies)
kubectl version --short
Client Version: v1.19.2
Server Version: v1.19.2
