### ISSUE TITLE
Reliability of Proxy containers with sudden change in number of endpoints

### ISSUE THREAD

**Issue by eightnoteight** [istio/istio#27723]
**Describe the feature request**
Google Cloud recently faced an incident where the gateway proxy memory utilisation exceeded with a sudden change in number of endpoints of a particular backend. I think istio should have similar safe guards to protect against such changes.

A few things that I could think of were to encourage `Sidecar` resource in performance and scalability section of the istio docs. a feature flag as a safe guard against this specific case i.e only to send a subset of endpoints to the gateway proxy if the number of endpoints in a single update is more than 3 times the last one or we can estimate average endpoint resource consumption and predict if it can exceed the memory utilization of the proxies

**Describe alternatives you've considered**
one possible solution is to keep such safeguards in envoy itself rather than making control plane intelligent and complex i.e in case of memory pressure, envoy can decide to only make connections to a subset randomly chosen upstream endpoints of a service rather than to make connections to all of them

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[x] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
So you except that if 100 pods spin up, we do not send envoy the endpoints? Or we delay sending them? is this a theoretical problem or have you seen real cases where too many endpoints causes envoy issues?

**Comment by howardjohn** [comment]
Any more info?

**Comment by howardjohn** [comment]
The use case here is not obvious to me and we haven't gotten any feedback in a while. If you have some more info we can discuss further, but until then I will close this. Thanks!
