### ISSUE TITLE
Request routing issue from browser to application service in istio 1.6.x to 1.7.x

### ISSUE THREAD

**Issue by nataraj24** [istio/istio#27727]
The requests arent getting routed from browser to application service.  as the issue  #23851 got closed opening this one.

In issue #8807 its mentioned as below

@krancour thanks for clearing that up. I will note that this is still not 100% fixed, we recently realized with wildcard hostnames its not quite right. Support in envoy is needed, see envoyproxy/envoy#12647

even though the there is "*" in place of port when compared to port 80 in earlier versions.  the requests arent passed from browser and we keep getting connection refused error.

Below is the error from curl command
* About to connect() to 10.73.123.211 port 30603 (#0)
*   Trying 10.73.123.211...
* Connection refused
* Failed connect to 10.73.123.211:30603; Connection refused
* Closing connection 0
curl: (7) Failed connect to 10.73.123.211:30603; Connection refused

if we edit the ingress-gateway svc and modify as below

  - name: http2
    nodePort: 30603
    port: 30603
    protocol: TCP
    targetPort: 30603

below is the curl output post modification

* About to connect() to 10.73.123.207 port 30603 (#0)
*   Trying 10.73.123.207...
* Connected to 10.73.123.207 (10.73.123.207) port 30603 (#0)

**Comment by howardjohn** [comment]
Hi @nataraj24 ,w need more info about the config you have, and the failing request. its helpfuil to get a config dump as well: https://github.com/istio/istio/wiki/Troubleshooting-Istio

The current state:
* 1.7.3 and older: any wildcard (`*.example.com`") with a port in the host header will fail
* 1.7.4+: any wildcard with a port in the host header that does NOT match the service will fail
* Ideal future, if envoy issue linked is fixed: everything works

**Comment by nataraj24** [comment]
Hi @howardjohn 

please find attached config dump.  below dump is of 1.6.12 for the application pod

[infra_dump.zip](https://github.com/istio/istio/files/5444803/infra_dump.zip)

**Comment by howardjohn** [comment]
this config only applies to gateway, the dump is from a sidecar.

Also need to know what request is sent that fails

**Comment by nataraj24** [comment]
Hi @howardjohn 

Let me know which configuration dump you are looking for I will generate the same and share it with you. 

If you send http request from browser or using curl command both fails.  It won’t reach application service. 

 If  you edit the ingress gateway svc port and give same value then it will go through

**Comment by howardjohn** [comment]
We need the config dump from the ingress gateway pod and the exact curl command that is failing

**Comment by nataraj24** [comment]
Hi @howardjohn 

Below is the curl command

curl http://k8s.ad.test.com:31128/infra/ui/infra.jsp

Below is the config dump of the ingress gateway pod.

[config_dump.zip](https://github.com/istio/istio/files/5559942/config_dump.zip)

**Comment by howardjohn** [comment]
@nataraj24 everything looks fine here. Can you try `curl http://k8s.ad.test.com:31128/infra/ui/infra.jsp -H "Host: k8s.ad.test.com"` as well to be sure?

In the original issue you mentioned two different error cases, which do you hit?

Can you attach the Service? I suspect the request is not even getting to the pod

**Comment by nataraj24** [comment]
Hi @howardjohn 

sorry i had given browser url.  Below is the exact curl url and its output

curl -v http://10.73.123.32:31128/infra/ui/infra.jsp

* About to connect() to 10.73.123.32 port 31128 (#0)
*   Trying 10.73.123.32...
* Connection refused
* Failed connect to 10.73.123.32:31128; Connection refused
* Closing connection 0
curl: (7) Failed connect to 10.73.123.32:31128; Connection refused

Below is the  service definition

apiVersion: v1
kind: Service
metadata:  
  name: infra-svc  
  labels:
    app: infra
spec: 
  type: "ClusterIP"
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080    
  selector:
    app: infra
  sessionAffinity: ClientIP

as mentioned earlier the call get routed properly after specifying port as below for ingress gateway svc 

name: http2
nodePort: 31128
port: 31128
protocol: TCP
targetPort: 31128

**Comment by howardjohn** [comment]
When you are calling the `nodePort` address you shouldn't call the Service IP, you need to call the node IP. SEe https://istio.io/latest/docs/tasks/traffic-management/ingress/ingress-control/#determining-the-ingress-ip-and-ports for more information

**Comment by nataraj24** [comment]
Hi @howardjohn 

I am using nodeip only in curl command Not using service ip

**Comment by howardjohn** [comment]
Hi @nataraj24 . It seems this issue is about issues with your Kubernetes setup or configuration. From Istio's side, everything is configured correctly but your request is not reaching the proxy, which is outside of Istio's ownership. https://kubernetes.io/docs/concepts/services-networking/service/#nodeport may help diagnose nodeport issues in Kubernetes. Thanks.
