### ISSUE TITLE
pilot-agent leak connections

### ISSUE THREAD

**Issue by uc-dang-tiki** [istio/istio#27726]
**Bug description**
pilot-agent leak health check connections.
Port 8080 is app health check port.
Pilot-agent create a lot of connection and dosen't close it all. (affect on istio 1.7.2, 1.7.3, but this issue not happen on 1.6.5)

```
istio-proxy@themis-5d6f5575df-7cgxj:/$ netstat -anp | grep pilot | wc -l
9933
istio-proxy@themis-5d6f5575df-7cgxj:/$ netstat -anp | grep pilot | more
tcp        0      0 10.42.13.221:58948      10.43.193.142:15012     ESTABLISHED 1/pilot-agent
tcp        0      0 127.0.0.1:33248         127.0.0.1:15090         ESTABLISHED 1/pilot-agent
tcp6       0      0 :::15020                :::*                    LISTEN      1/pilot-agent
tcp6       0      0 ::1:53226               ::1:8080                ESTABLISHED 1/pilot-agent
tcp6       0      0 ::1:56378               ::1:8080                ESTABLISHED 1/pilot-agent
tcp6       0      0 ::1:41860               ::1:8080                ESTABLISHED 1/pilot-agent
tcp6       0      0 ::1:46170               ::1:8080                ESTABLISHED 1/pilot-agent
tcp6       0      0 ::1:53409               ::1:8080                ESTABLISHED 1/pilot-agent
tcp6       0      0 ::1:34478               ::1:8080                ESTABLISHED 1/pilot-agent
tcp6       0      0 ::1:47808               ::1:8080                ESTABLISHED 1/pilot-agent
tcp6       0      0 ::1:36632               ::1:8080                ESTABLISHED 1/pilot-agent
tcp6       0      0 ::1:52130               ::1:8080                ESTABLISHED 1/pilot-agent
```

[ ] Docs
[ ] Installation
[ ] Networking
[x ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Pilot-agent close/finish all health check connections
**Steps to reproduce the bug**
1. Install istio 1.7.3
2. deploy Java app (spring) and enable health check on app
3. Inject istio to java app
4. wait 1h then type this command on: `netstat -anp | grep pilot | wc -l`    istio-proxy container of the java app.
**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
istioctl version --remote
client version: 1.7.3
control plane version: 1.7.3
data plane version: 1.7.3 (76 proxies), 1.6.5 (5 proxies), 1.7.2 (7 proxies)
kubectl version --short
Client Version: v1.17.0
Server Version: v1.16.8
**How was Istio installed?**
install by istio operator via istioctl.
**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by uc-dang-tiki** [comment]
Workaround: disable http probe rewrite. https://istio.io/latest/docs/ops/configuration/mesh/app-health-check/#disable-the-http-probe-rewrite-for-a-pod

**Comment by hzxuzhonghu** [comment]
This is because we recreate a new http client each time. The solution is to resue one I think
