### ISSUE TITLE
Trust Domain config confusion

### ISSUE THREAD

**Issue by costinm** [istio/istio#27734]
For install, We have 2 ways that TrustDomain: 
- MeshConfig.TrustDomain - the 'official' one.
- Values.global.trustDomain  - must be deprecated, since it duplicates MeshConfig

In Agent, we also have 2 ways:
- a CLI flag - --trustDomain, set by injector from Values.global
- an env variable 

Given how critical the trust domain is, I think we must fix this for 1.8. 

The correct and consistent behavior is:
- MeshConfig.TrustDomain must be what the users set
- injection template will use meshConfig.trustDomain to populate the env variable. 
- for 1.8, to avoid breaking existing code, we should continue to set the trustDomain flag - but from MeshConfig.trustDomain
- also for backward compat, we should make sure that if Values.global.trustDomain is set, it is populated in MeshConfig
- pilot agent should check if both flag and env are set, and give priority to the env variable ( most flags are now deprecated )

Docs should be update to reflect that MeshConfig is the supported way to set trustDomain and aliases.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by costinm** [comment]
FYI @howardjohn 

Oliver, I think this is P0, it impacts critical 'central Istiod' config.

**Comment by howardjohn** [comment]
100% agree

**Comment by incfly** [comment]
@shankgan would take a look and confirm what changes to be consolidated.

**Comment by shankgan** [comment]
discussed this with @howardjohn - the helm Values.global.TrustDomain has already been marked as deprecated in Istio 1.8. In Istio 1.9, will remove this configuration entirely

**Comment by jacob-delgado** [comment]
Per @shankgan we can close this issue as it is complete. Thanks!
