### ISSUE TITLE
Ingress objects are only registered in Ingress Gateway instance in `kube-system` when multiple ingress gateways are run in different namespaces

### ISSUE THREAD

**Issue by jeffherald** [istio/istio#27738]
**Bug description**
We've deployed ingress gateways into individual namespaces and have noticed that when Ingress objects are created, only the ingress gateway in `istio-system` gets updated about them. Looking at the configuration, it looks like running a setup like ours probably wasn't a scenario considered, as it only allows specification of a single ingress gateway. We have a workaround in using the Istio provided CRDs, which work fine, but wanted to raise the issue for awareness.

[ ] Docs
[ ] Installation
[ x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
```
$ istioctl version --remote
client version: 1.6.3
control plane version: 1.6.3
data plane version: 1.6.3 (53 proxies)
$ kubectl version --short
Client Version: v1.19.2
Server Version: v1.17.9-eks-4c6976
```

**How was Istio installed?**
Istio Operator
**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
Only a single gateway deployment will handle Ingress by design. This can be configured via IngressSelector/IngressService in mesh config (https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/, `istio` configmap), but only one may be selected

**Comment by jeffherald** [comment]
@howardjohn Ok, just wanted to verify that this was by design and not oversight, thank you for clarifying.
