### ISSUE TITLE
Story for Service Isolation

### ISSUE THREAD

**Issue by nmittler** [istio/istio#27735]
Now that we are no longer recommending using the `.global` config for multi-primary installations, we need to recommend a way for providing isolation between services.

Some use cases that we might want to consider:

- `Service A` can talk to `Service B`, but not to `Service C`.
  - Perhaps this is just auth policy?
  - Should we take a stronger stance and allow physical boundaries (e.g. cluster, network) to play a role as well? In other words, if `Service A` and `Service C` reside in different clusters, should Istio not program endpoints or even allow DNS lookup to succeed? Are there other options here? 
- Services in cluster `C1` only talk to `Service A` in `C1` (i.e. cluster-local services). Currently we have a MeshConfig setting for this, but it would be better to support it through more standard APIs.

**Describe alternatives you've considered**

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
I think the only thing that really makes sense is authz policy. We shouldn't be attempting enforcement on the clientside by things like not programming endpoints or DNS - the app can always get around it. We can do it as an optimization or additional measure, but nothing is complete without serverside enforcement.

**Comment by nmittler** [comment]
@howardjohn 

> I think the only thing that really makes sense is authz policy. We shouldn't be attempting enforcement on the clientside by things like not programming endpoints or DNS - the app can always get around it. We can do it as an optimization or additional measure, but nothing is complete without serverside enforcement.

Yeah agreed. I think that's the main thrust here  ... are we happy with authz as the *only* measure? If so, then we can just close this out.

FYI @smawson @linsun @vadimeisenbergibm

**Comment by smawson** [comment]
Totally agree, we should use authz policy for this. If users want to restrict access between clusters they should write an authz policy against an appropriate attribute (cluster, zone, region). But we should encourage users not to rely on cluster boundaries for authorization and instead rely on namespaces. We're missing a feature to make cluster tenancy work better but that's a longer discussion.

We do however need to give users control over locality for routing, prefer local, never go outside region, etc. Those controls make sense to include in a general way, as an optimization and not as an enforcement mechanism.

**Comment by nmittler** [comment]
@smawson agreed ... that sounds like the right way of looking at it. Using control plane topology was always a weak and error-prone form of isolation anyway.

So really, the improvement here then becomes the second bullet: improved control over locality. I'm already working on a couple of RFCs that should help here, so I think we can safely close this out.

**Comment by linsun** [comment]
For flat network, using istio authz makes sense given cross cluster service communication doesn't go through the east-west gw.

for non-flat network, the boundary of the cluster on what to expose is configured via the gateway resource, what services are exposed on the east-west gw.  istio authz could be used on top of this if needed assuming we carry the service identify over when traffic is transited through the east-west gw.  Not sure how well RBAC works with passthrough gw, as I recall @vadimeisenbergibm claimed it didn't work for him earlier.

**Comment by smawson** [comment]
> For flat network, using istio authz makes sense given cross cluster service communication doesn't go through the east-west gw.
> 
> for non-flat network, the boundary of the cluster on what to expose is configured via the gateway resource, what services are exposed on the east-west gw. istio authz could be used on top of this if needed assuming we carry the service identify over when traffic is transited through the east-west gw. Not sure how well RBAC works with passthrough gw, as I recall @vadimeisenbergibm claimed it didn't work for him earlier.

I'd like users to think of the cross-network gw as an implementation detail of how Istio works, and not use networks as a proxy for authorization. That is part of the broader push towards zero-trust networks, it doesn't matter what network you're on, the security model is the same.

Of course users do need physical isolation and that's why we had been exploring multi-mesh solutions, where a mesh is a strong isolation boundary and can be used to selectively expose services. I don't think we want networks act that way since there are many reasons for having multiple networks, not just isolation.

On authz if the cross-network gw is not supporting authz we should fix that, it should be a P0 release blocker.

**Comment by linsun** [comment]
I'm not proposing using networks as a proxy authorization.  AuthZ will be still achieved through istio authz policy however, the east-west gateway could be configured to only expose certain services to the other cluster(s), similarly as the service expose API in the k8s MCS API.  When the service expose API is implemented, I agree, east-west gateway could just be an implementation detail and users can use the service expose API to do that more elegantly.

@nmittler @smawson I think it would be great if we could develop some tasks/docs for this.  Users will need some guidance on how to use istio authz across clusters (do we need to leverage the new cluster label @nmittler is proposing for istio authz policy?) and we also need some validation ourselves to prove it works.  I would be happy to rerun the steps for multi-networks to see if it works.

**Comment by nmittler** [comment]
FYI @myidpt ^^^

**Comment by nmittler** [comment]
@linsun Are you fine closing this issue? We can always create a separate issue to add documentation ... I'd like to keep this focused on our general strategy for dealing with isolation with multicluster.
