### ISSUE TITLE
Kubernetes Ingress selector issues

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#27751]
https://github.com/istio/istio/blob/22d9a05c0f85a9da74e17211d50087a7dc713dc5/pilot/pkg/config/kube/ingress/conversion.go#L89

This should also check for `""` 

Also, the ingress status code is out of sync with this logic.

**Comment by SkySonR** [comment]
There are exist possibly to rewrite the IngressService parameter? 
I see comment like // Configurable by meshConfig.ingressSelector.
But how it must looks like in Ingress? How to pass the value to this parameter. For now any idea how to use custom istio ingress-gateway

**Comment by howardjohn** [comment]
@SkySonR its configured in `istio` configmap in istio-system (mesh config)

**Comment by Monkeyanator** [comment]
Fixed in #28279
