### ISSUE TITLE
Gateway SNI w/ and w/o TLS termination using only LDS v2

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#2775]
This is umbrella epic for all the work related to SNI and involves two parts:

- TLS termination in gateway #1424 and #4878 (required for 1.0)
- SNI sniffing/routing where gateway routes and proxies traffic based on the SNI value #5455 (not a 1.0)

**Comment by rshriram** [comment]
This is probably very much aligned with the rewrite that is happening. FYI @sdake , @gnirodi @baodongli ^^^.

**Comment by sdake** [comment]
@rshriram please see https://github.com/istio/istio/issues/2198#issuecomment-365599716 for details on reassignment.

**Comment by myidpt** [comment]
Is this blocked by Envoy V2 API?

**Comment by rshriram** [comment]
completed, some tests remain.. Gateway tests work

**Comment by andraxylia** [comment]
This is not yet done, there are outstanding issues open.

**Comment by rshriram** [comment]
Both of these are completed and actually available in 0.8. SNI based routing without TLS termination, and TLS termination/cert serving based on SNI headers.

**Comment by rshriram** [comment]
All relevant issues in this epic have been closed. So closing this issue accordingly. TLS sniffing is unrelated and pertains to incremental mTLS adoption.
