### ISSUE TITLE
Adding a dimension to existing metric

### ISSUE THREAD

**Issue by jackfrost02** [istio/istio#27764]
I have istio 1.6.1 deployed on aws eks 1.17 and am trying to add a dimension request.path to istio_request_duration_milliseconds_count metric.

my stats-filter-1.6.yaml file is attached.

I also added the following to my app spec template

  template:
    metadata:
      annotations:
        sidecar.istio.io/extraStatTags: request_path

I ran kubectl apply to stats-filter-1.6.yaml and reloaded my app.

I sent a few curl requests to my app then check the metric to see the new dimension by running this command

kubectl exec pod-name -c istio-proxy -- curl 'localhost:15000/stats/prometheus' | grep istio_request_duration_milliseconds_count | grep request_path

But I don't see the new dimension.

Did I miss anything?
[stats-filter-1.6.yaml.gz](https://github.com/istio/istio/files/5331570/stats-filter-1.6.yaml.gz)

Thank you.

**Comment by jackfrost02** [comment]
If I assigned the new dimension on istio_requests_total then it showed up correctly.

**Comment by bianpengyuan** [comment]
Should be `request_duration_milliseconds` instead of `request_duration_milliseconds_count`.

**Comment by jackfrost02** [comment]
Works like a charm. Thank you.
