### ISSUE TITLE
ACME integration with istio

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#2776]

**Comment by Stono** [comment]
Out of curiosity are you referring to kube-lego?

**Comment by andraxylia** [comment]
yes, kube-lego, the k8s for let's encrypt go which is the implementation of the ACME protocol.

@costinm and @ldemailly got something to work, but it needs more work to be productized, including testing, docs. Help is welcomed!

**Comment by Stono** [comment]
Yeah id actually been working on this today.
Would be interested to collaborate for sure!

**Comment by ldemailly** [comment]
cert-manager is working as mentioned, just need to document it
https://github.com/istio/istio.github.io/issues/868

closing this as it's a dup of #2310
