### ISSUE TITLE
Endpoints not visible in 1.7.2 multicluster on AWS

### ISSUE THREAD

**Issue by ecrousseau** [istio/istio#27769]
**Bug description**
I am having trouble with cross-cluster endpoints not showing up (i.e. not visible when running `istioctl proxy-config endpoints pod.namespace`). 

My configuration is:
* One mesh (mesh0)
* Two networks (network0 and network1)
* Two EKS clusters (cluster0 and cluster1)
* Istio 1.7.2 installed on both in a "shared control plane" model
* cluster0 in network0 runs the shared control plane
* cluster1 in network1 is in "remote pilot" mode with the local istiod issuing certificates
* A remote secret for cluster1 exists on cluster0

I can see using istioctl and by reviewing the istiod log on cluster0 that:
* Pods on both clusters can join the mesh
* Pods can talk to other pods on the same cluster

Finally, when I set the istiod log level to debug, I can see that cluster0 is able to query the apiserver for cluster1 and retrieve details about pods, services, and endpoints. I assume this means that pilot "knows about them", but they don't show up as endpoints for pods on cluster0 like I would have expected. They *do* show up as clusters and routes, for what that's worth.

Can anyone point me in the right direction in terms of what might be going wrong here? 

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
The endpoints would show up / work etc.

**Steps to reproduce the bug**
Deploy two EKS clusters, install Istio 1.7.2, configure according to the description above.

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
istioctl:
client version: 1.7.2
control plane version: 1.7.2
data plane version: 1.7.2 (6 proxies)

kubectl:
Client Version: v1.16.8-eks-e16311
Server Version: v1.16.13-eks-2ba888

**How was Istio installed?**
Using istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS/EKS using EKS managed nodes

Very happy to provide extra information if its required!

**Comment by hzxuzhonghu** [comment]
It is expected that the remote endpoints are not visible to local cluster, because pilot will transit these endpoints to the gateway address

**Comment by ecrousseau** [comment]
@hzxuzhonghu In my home lab (running Kubernetes in HyperV VMs instead of using EKS), with the same Istio configuration, pods do receive endpoint data for services running on other clusters, with the IP/port being the remote ingress gateway. What I'm trying to work out is why that isn't happening in my EKS clusters. I get that the Kubernetes endpoints i.e. the remote pod IPs are "hidden", but istiod knows about them - why isn't it creating Istio endpoints that point at the ingress gateway?

In the example below from the lab setup, 192.168.2.0/23 is the pod IP range for cluster0, and 192.168.1.40 is the load balancer for the ingress gateway of the remote cluster.
```
> istioctl proxy-config endpoints ubuntu-84ccbff7d9-q2ndz.default
ENDPOINT                         STATUS      OUTLIER CHECK     CLUSTER
10.96.141.90:15012               HEALTHY     OK                xds-grpc
127.0.0.1:15000                  HEALTHY     OK                prometheus_stats
127.0.0.1:15020                  HEALTHY     OK                agent
192.168.1.10:6443                HEALTHY     OK                outbound|443||kubernetes.default.svc.cluster.local
192.168.1.30:15012               HEALTHY     OK                outbound|15012||istiod-remote.istio-system.svc.cluster.local
192.168.1.40:443                 HEALTHY     OK                outbound|9080||details.default.svc.cluster.local
192.168.1.40:443                 HEALTHY     OK                outbound|9080||productpage.default.svc.cluster.local
192.168.1.40:443                 HEALTHY     OK                outbound|9080||ratings.default.svc.cluster.local
192.168.1.40:443                 HEALTHY     OK                outbound|9080||reviews.default.svc.cluster.local
192.168.2.64:53                  HEALTHY     OK                outbound|53||kube-dns.kube-system.svc.cluster.local
192.168.2.64:9153                HEALTHY     OK                outbound|9153||kube-dns.kube-system.svc.cluster.local
192.168.2.84:15010               HEALTHY     OK                outbound|15010||istiod.istio-system.svc.cluster.local
192.168.2.84:15012               HEALTHY     OK                outbound|15012||istiod.istio-system.svc.cluster.local
192.168.2.84:15014               HEALTHY     OK                outbound|15014||istiod.istio-system.svc.cluster.local
192.168.2.84:15017               HEALTHY     OK                outbound|443||istiod.istio-system.svc.cluster.local
192.168.2.84:15053               HEALTHY     OK                outbound|853||istiod.istio-system.svc.cluster.local
192.168.3.192:53                 HEALTHY     OK                outbound|53||kube-dns.kube-system.svc.cluster.local
192.168.3.192:9153               HEALTHY     OK                outbound|9153||kube-dns.kube-system.svc.cluster.local
192.168.3.216:8080               HEALTHY     OK                outbound|80||istio-ingressgateway.istio-system.svc.cluster.local
192.168.3.216:8443               HEALTHY     OK                outbound|443||istio-ingressgateway.istio-system.svc.cluster.local
192.168.3.216:15021              HEALTHY     OK                outbound|15021||istio-ingressgateway.istio-system.svc.cluster.local
192.168.3.216:15443              HEALTHY     OK                outbound|15443||istio-ingressgateway.istio-system.svc.cluster.local
192.168.3.217:8080               HEALTHY     OK                outbound|80||istio-egressgateway.istio-system.svc.cluster.local
192.168.3.217:8443               HEALTHY     OK                outbound|443||istio-egressgateway.istio-system.svc.cluster.local
192.168.3.217:15443              HEALTHY     OK                outbound|15443||istio-egressgateway.istio-system.svc.cluster.local
unix://./etc/istio/proxy/SDS     HEALTHY     OK                sds-grpc
```

**Comment by hzxuzhonghu** [comment]
> What I'm trying to work out is why that isn't happening in my EKS clusters. 

you can check the meshnetworks config

**Comment by john-a-joyce** [comment]
I am hitting something along the same lines,  but in my case I am not using a shared control plane but entirely separate control plane.   In my case there are endpoints assigned for all the services but the don't correctly point to the ingress ELB addresses EKS has assigned.   See this output:  
```13.33.163.116:15443              HEALTHY     OK                outbound|8000||httpbin.bar.global
13.33.163.116:15443              HEALTHY     OK                outbound|8000||httpbin.bar.svc.cluster3.global
13.33.163.18:15443               HEALTHY     OK                outbound|8000||httpbin.bar.global
13.33.163.18:15443               HEALTHY     OK                outbound|8000||httpbin.bar.svc.cluster3.global
13.33.163.3:15443                HEALTHY     OK                outbound|8000||httpbin.bar.global
13.33.163.3:15443                HEALTHY     OK                outbound|8000||httpbin.bar.svc.cluster3.global
13.33.163.90:15443               HEALTHY     OK                outbound|8000||httpbin.bar.global
13.33.163.90:15443               HEALTHY     OK                outbound|8000||httpbin.bar.svc.cluster3.global
root@bxb-ds-82:~/go/src/github.com/cisco-app-networking/wcm-system/system_topo# /tmp/istio-1.6.5/bin/istioctl proxy-config endpoints istio-ingressgateway-d8658c6d7-nwtst -n istio-system | grep httpb
18.217.16.154:15443              HEALTHY     OK                outbound_.8000_._.httpbin.bar.global
18.217.16.154:15443              HEALTHY     OK                outbound_.8000_._.httpbin.bar.svc.cluster3.global
18.217.16.154:15443              HEALTHY     OK                outbound|8000||httpbin.bar.global
18.217.16.154:15443              HEALTHY     OK                outbound|8000||httpbin.bar.svc.cluster3.global
3.129.161.229:15443              HEALTHY     OK                outbound_.8000_._.httpbin.bar.global
3.129.161.229:15443              HEALTHY     OK                outbound_.8000_._.httpbin.bar.svc.cluster3.global
3.129.161.229:15443              HEALTHY     OK                outbound|8000||httpbin.bar.global
3.129.161.229:15443              HEALTHY     OK                outbound|8000||httpbin.bar.svc.cluster3.global```
Note the first output is for a test pod which has incorrect endpoint addresses.  While the 2nd set of address come from the ingress which correctly point to the ingress IPs of the remote cluster.   
If you have discovered anything with this issue that might help explain that problem please let me know.
