### ISSUE TITLE
istioctl analyze - Fails on big clusters?

### ISSUE THREAD

**Issue by dntosas** [istio/istio#27772]
**Bug description**
We observe that running `istioctl analyze --all-namespaces --timeout 10000s` fails with the following error:
```yaml
error	k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125: Failed to list *v1.Secret: stream error when reading response body, may be caused by closed connection. Please retry. Original error: stream error: stream ID 11; INTERNAL_ERROR

error	k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125: Failed to list *v1.Secret: stream error when reading response body, may be caused by closed connection. Please retry. Original error: stream error: stream ID 13; INTERNAL_ERROR

error	k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125: Failed to list *v1.Secret: stream error when reading response body, may be caused by closed connection. Please retry. Original error: stream error: stream ID 15; INTERNAL_ERROR
```

[ ] Docs
[ ] Installation
[ ] Networking
[x] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Expected behavior**
To return the output of analyze command.

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
- Istioctl && Istio `1.7.3`
- Kubernetes `1.18.6`

**How was Istio installed?**
- Via `istioctl install`

**Environment where bug was observed (cloud vendor, OS, etc)**
- k8s-deployments: 900
- k8s-services: 1200
- k8s-pods: 2100
- k8s-pods-istio-injected: 650

**Comment by howardjohn** [comment]
How many secrets do you have? seems the error is from secrets.

This looks like an error coming from underlying kubernetes client-go so I am not sure if we need to configure it differently or what we can do here?
