### ISSUE TITLE
Gateway and Routing Rules New Specification

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#2777]
Epic for:
https://docs.google.com/document/d/10uzw4N11NY_vWxWu2l79Ag96fvPT6w-OGzD_buvILM0/edit

Definition of Done:
- [x] Code Complete
  - [x] Add API
  - [x] Add Gateway
- [x] UT
- [x] Integration
- [x] Docs

**Comment by andraxylia** [comment]
Definition of Done:
- [ ] Code
- [ ] UT
- [ ] Integration
- [ ] Docs

Feature status:
- [ ] Alpha-feature
- [ ] Beta
- [ ] Stable

**Comment by rshriram** [comment]
Seems @gnirodi , @sdake and some others are working on more optimized v1alpha2 implementation, v2 api implementation, and faster pilot in conjunction with all work on multi-cloud. (https://groups.google.com/d/msg/istio-environments/3SZaZGhPk0U/guFJJAfZAwAJ)

Since these rewrites involve all parts of pilot, they are better positioned to handle this.

**Comment by sdake** [comment]
@rshriram please see https://github.com/istio/istio/issues/2198#issuecomment-365599716 for details on reassignment.

**Comment by rshriram** [comment]
completed

**Comment by andraxylia** [comment]
@rshriram I see some of the issues for this epic are still open, we should not close the epic until everything is fixed, even if the big changes are in. Maybe we can close some of the them?

Gateway and Routing Rules New Specification is an Epic
5
of
12
Issues completed
0
of
0
Epic Points completed
New Issues
istio
#3063
Support for health-checking of Ingress/Gateway
Not estimated
api
#270
Revise DestinationPolicy
Not estimated
api
#305
ForeignServices cardinality issues
Not estimated
api
#312
DestinationRule tls settings ambiguity
Not estimated
P0
api
#314
Fix default tls mode for destination and add 80-443 mapping for ext svc
Not estimated
Closed
istio
#1925
Update Pilot to v1alpha3 routing API
0 epic points
2
of
4
issues completed
0
of
0
epic points completed
Show epic issues
api
#297
rename gateway to exposure for clarity
Not estimated
api
#309
Destination Rules: ports, (no)inheritance, and more
Not estimated

**Comment by andraxylia** [comment]
The only pending issue is health-check for Gateway, which can be handled as part of the HA epic.

So glad to be closing this!
