### ISSUE TITLE
Kubelet ServiceMonitor queries endpoint that is not available on some installations

### ISSUE THREAD

**Issue by guidoffm** [istio/istio#27792]
https://github.com/istio/installer/blob/master/istio-telemetry/prometheus-operator/templates/servicemonitors.yaml

The ServiceMonitor queries two endpoint which both have the "port" set to "http-metrics" and the "scheme" set to "http".

On some platforms these endpoints are no longer available. "port" should be set to "https-metrics" and "scheme" to "https".

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
1.7.3

**Comment by howardjohn** [comment]
https://github.com/istio/installer/blob/master/istio-telemetry/prometheus-operator/templates/servicemonitors.yaml is not supported. The istio/installer repo is archived and has not been used since Istio 1.4 or so.

**Comment by guidoffm** [comment]
> https://github.com/istio/installer/blob/master/istio-telemetry/prometheus-operator/templates/servicemonitors.yaml is not supported. The istio/installer repo is archived and has not been used since Istio 1.4 or so.

Yes, you are right. But I cannot find the code in the supported repositories and the files are included in the most recent installation package.
