### ISSUE TITLE
Revision based upgrade test plan

### ISSUE THREAD

**Issue by ostromart** [istio/istio#27818]
Required for beta status: https://github.com/istio/enhancements/issues/6

**Comment by Monkeyanator** [comment]
FYI been working on adding revision-based upgrade tests to the integration framework (initial work [here](https://github.com/istio/istio/pull/29007)). They're still incredibly naive at this point (currently just installs multiple revisions on multiple versions, relies on checked-in config, etc)

Planning on expanding them to actually test that traffic continues flowing during cutover to new revision (like the istio/tools tests already do), multicluster revision-based upgrades, etc.

cc @jacob-delgado @ericvn as discussed in meeting earlier this week

**Comment by Monkeyanator** [comment]
New overall design for revision-based upgrade testing effort [here](https://docs.google.com/document/d/1GOCwkrJ3_hYaS3IyUHqojUVuIKOTs0bEmZRh-fiVmEE/edit#)
