### ISSUE TITLE
istioctl analyze panic with `concurrent map writes`

### ISSUE THREAD

**Issue by nairb774** [istio/istio#27822]
**Bug description**

Running `istioctl analyze -A` paniced with `fatal error: concurrent map writes`

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

No concurrency bugs.

**Steps to reproduce the bug**

Happened while running `istioctl --context=$CLUSTER analyze -A`.

Full panic: [stack.gz](https://github.com/istio/istio/files/5344461/stack.gz)

Top of panic snippet:

```
$ istioctl --context=$CLUSTER analyze -A
fatal error: concurrent map writes

goroutine 1288 [running]:
runtime.throw(0x3f603b3, 0x15)
        runtime/panic.go:1116 +0x72 fp=0xc003bf1e68 sp=0xc003bf1e38 pc=0x1036b32
runtime.mapassign_faststr(0x395aca0, 0xc002935b00, 0xc00132a600, 0x30, 0x2000000010000)
        runtime/map_faststr.go:211 +0x3f1 fp=0xc003bf1ed0 sp=0xc003bf1e68 pc=0x1014631
istio.io/istio/galley/pkg/config/analysis/local.(*precedenceHandler).handleFullSync(0xc0015eaa30, 0x4, 0x43dbee0, 0xc000c584c0, 0x0)
        istio.io/istio/galley/pkg/config/analysis/local/source.go:81 +0x75 fp=0xc003bf1f18 sp=0xc003bf1ed0 pc=0x2f71475
istio.io/istio/galley/pkg/config/analysis/local.(*precedenceHandler).Handle(0xc0015eaa30, 0x4, 0x43dbee0, 0xc000c584c0, 0x0)
        istio.io/istio/galley/pkg/config/analysis/local/source.go:71 +0xbc fp=0xc003bf1f68 sp=0xc003bf1f18 pc=0x2f7133c
istio.io/istio/pkg/config/event.(*Handlers).Handle(0xc0015a1ae0, 0x4, 0x43dbee0, 0xc000c584c0, 0x0)
        istio.io/istio/pkg/config/event/handlers.go:28 +0x8d fp=0xc003bf1fb8 sp=0xc003bf1f68 pc=0x2f29b8d
runtime.goexit()
        runtime/asm_amd64.s:1374 +0x1 fp=0xc003bf1fc0 sp=0xc003bf1fb8 pc=0x106f321
created by istio.io/istio/galley/pkg/config/source/kube/apiserver.(*watcher).start
        istio.io/istio/galley/pkg/config/source/kube/apiserver/watcher.go:92 +0x68f
```

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

```
$ istioctl version --remote
client version: 1.7.3
control plane version: 1.7.3
data plane version: 1.7.0 (25 proxies), 1.7.3 (5 proxies)
$ kubectl version --short
Client Version: v1.19.2
Server Version: v1.17.9-eks-4c6976
```
**Note:** I had just started the 1.7.3 upgrade when this happened.

**How was Istio installed?**

Istio Operator 1.7.3

**Environment where bug was observed (cloud vendor, OS, etc)**

AWS EKS 1.17

**Comment by shamsher31** [comment]
> Happened while running istioctl --context=$CLUSTER analyze -A.

What is the value set for `--context=$CLUSTER`?

**Comment by esnible** [comment]
The conflict seems to be between two threads

**running** _galley/pkg/config/source/kube/apiserver/source.go_:81 is `ph.src.expectedCounts[col]--`
**runnable** _galley/pkg/config/source/kube/apiserver/source.go_:121 is `s.expectedResources[key] = r`

**Comment by nairb774** [comment]
> @nairb774 does this happen to you every time or rarely?

I've only seen it this one time, but given Go's detection of these things when not running with the race detector on is probabilistic at best I'd doubt there would be many occurrences.

That said, I re-built istioctl from the 1.7.3 tag with race enabled and ran it a couple of times without issue. It could be a fun heisen-bug, but looking at the code implicated, it is hard to know if it isn't a real bug, or not (tricky for new eyes to quickly follow).
