### ISSUE TITLE
Ensure EnvoyFilter doesn't patch shared structs

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#27826]
In Istio 1.4 I came across a bug where we mutated a shared struct from EnvoyFilter merge. It doesn't exist anymore, but we should ensure there are no similar bugs lurking in our code today.

cc @ramaraochavali @rshriram

**Comment by howardjohn** [comment]
not stale

**Comment by howardjohn** [comment]
Not stale, but hard to do without killing perf

**Comment by howardjohn** [comment]
not stale

**Comment by howardjohn** [comment]
not stale

**Comment by howardjohn** [comment]
Notstale

**Comment by vikaschoudhary16** [comment]
not stale

**Comment by yann-soubeyrand** [comment]
Hi @howardjohn, do you know if this issue has been fixed or not?

**Comment by howardjohn** [comment]
adhoc it has but not universally
