### ISSUE TITLE
missing samples/multicluster/gen-eastwest-gateway.sh

### ISSUE THREAD

**Issue by rvennam** [istio/istio#27838]
**Bug description**
https://preliminary.istio.io/latest/docs/setup/install/multicluster/ references `samples/multicluster/gen-eastwest-gateway.sh` but that file isn't included in the build:

<img width="668" alt="image" src="https://user-images.githubusercontent.com/5502967/95528677-d0f6fa00-09a6-11eb-95be-e9067ab9399c.png">

[X ] Docs
[X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
samples/multicluster/gen-eastwest-gateway.sh should exist 

**Steps to reproduce the bug**
Download latest dev build, for example: https://gcsweb.istio.io/gcs/istio-build/dev/1.8-alpha.ee6506b713583dd92da5f0f960a3dd8b53a1cd0e

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
1.8-alpha.4d6d0d49b30ef513eb9ef48c28ea3702f884e290

**How was Istio installed?**
https://gcsweb.istio.io/gcs/istio-build/dev/1.8-alpha.ee6506b713583dd92da5f0f960a3dd8b53a1cd0e

**Environment where bug was observed (cloud vendor, OS, etc)**
osx

**Comment by nmittler** [comment]
We should just include everything under `samples` in the distribution, if we're not already.

**Comment by sdake** [comment]
@ericvn or @brian-avery  can you add this to rb?

Cheers,
-steve

**Comment by sdake** [comment]
@nmittler release builder is designed to test for missing files, and also sometimes even ensure the files in the release are correct ahead of time.

I leave to T&R leads to sort it though 👍 
Cheers,
-steve

**Comment by brian-avery** [comment]
Looking at the release builder PR, we include quite a bit: 

```
includePatterns = []string{"*.yaml", "*.md", "*.sh", "cleanup.sh", "*.txt", "*.pem", "*.conf", "*.tpl", "*.json", "Makefile"}
```

@nmittler Given that these are all wildcards, what do you think would be missing?

**Comment by nmittler** [comment]
@brian-avery That should be everything. If we're recursively including all of those under `samples`, then it's not clear why this isn't not getting into the build.

**Comment by rvennam** [comment]
@nmittler .sh was added in that PR and it isn't merged yet
