### ISSUE TITLE
We need to minimally exercise/test the produced tgz releases

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#2784]
As a follow up on #2713 (and #672 and...):

We need to at minimum:
check that the tar file is usable/un tarrable, contains a working bin/istioctl for linux and ideally check also the mac version (and windows as a third priority)

and that using only that tar ball one can installs istio (kubectl -f install/kubernetes/istio-auth.yaml) and inject 1 service

**Comment by kyessenov** [comment]
Even better, why not just run tests with the produced artifacts?

**Comment by hklai** [comment]
Currently the images are functionally tested. We should add more tests like:

1. "istioctl version" and make sure it spits out the right version that we expect.
2. Image version check (Prevents https://github.com/istio/istio/issues/4266#issuecomment-374459516)
