### ISSUE TITLE
The ISTIO installation is missing some services

### ISSUE THREAD

**Issue by liwh1111** [istio/istio#27845]
Hello, why did I install ISTIO-1.7.3 according to the document? But there are only three PODS, such as Kiali. Isn't it through "profile=demo" that kiali and other related services will be deployed?
![image](https://user-images.githubusercontent.com/63097736/95560734-42d54f00-0a4c-11eb-9414-421c448f5a37.png)

**Comment by Liatat** [comment]
uhhh..I encountered the same problem as you when I installed istio1.7. Finally, I changed to version 1.5.10.

**Comment by liwh1111** [comment]
> uhhh..I encountered the same problem as you when I installed istio1.7. Finally, I changed to version 1.5.10.

Ok, thanks, I've taken a look at the latest ISTIO, and it seems like you have to configure yourself to enable these plug-ins

**Comment by hzxuzhonghu** [comment]
https://istio.io/latest/docs/setup/install/istioctl/#display-the-configuration-of-a-profile

**Comment by shamsher31** [comment]
@liwh1111 Demo profile doesn't come with addons.
https://istio.io/latest/docs/setup/additional-setup/config-profiles/

If you want to install `Kiali` which is provided as an add-on integration. You can configure using following,
https://istio.io/latest/docs/ops/integrations/kiali/
