### ISSUE TITLE
Metrics not working following 1.5 -> 1.6 upgrade

### ISSUE THREAD

**Issue by Stono** [istio/istio#27851]
**Bug description**
As I've [blogged about](https://karlstoney.com/2020/05/25/reduce-istio-sidecar-metric-cardinality/) - it's really important for us that we're able to reduce the cardinality of metrics at the `Sidecar`.

We did this using an `EnvoyFilter` configured with:
```
                {
                  "debug": "false",
                  "stat_prefix": "istio",
                  "metrics": {
                    "tags_to_remove": ["destination_canonical_service", "source_canonical_service", "destination_principal", "source_principal", "connection_security_policy", "grpc_response_status", "source_version", "destination_version", "request_protocol", "source_canonical_revision", "destination_canonical_revision"]
                  },
                  "metrics": {
                    "name": "request_duration_milliseconds",
                    "tags_to_remove": ["response_code", "response_flags"],
                  },
                  "metrics": {
                    "name": "request_bytes",
                    "tags_to_remove": ["response_code", "response_flags"],
                  },
                  "metrics": {
                    "name": "response_bytes",
                    "tags_to_remove": ["response_code", "response_flags"],
                  }
                }
```

This works fine on `1.5`, but on `1.6` we get no metrics at all.  Switching it back to the default:

```
                  {
                    "debug": "false",
                    "stat_prefix": "istio"
                  }
```

And we start getting metrics, but with all the dimensions we're not interested in.

I'm guessing something has changed about this config between 1.5 and 1.6 but I cannot see anything in documentation to tell me what/why.

It also really highlights how dangerous EnvoyFilters are for configuration rather than first class API's.

cc @howardjohn @douglas-reid 

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[x] Developer Infrastructure

**Expected behavior**
Metrics to work

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
1.6

**How was Istio installed?**
Helm

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by douglas-reid** [comment]
@kyessenov did anything change between 1.5 and 1.6 with respect to supporting the `repeated MetricsConfig metrics` or similar?

**Comment by Stono** [comment]
Modifying the configuration to:
```
                {
                  "debug": "false",
                  "stat_prefix": "istio",
                  "metrics": [
                    {
                      "tags_to_remove": ["destination_canonical_service", "source_canonical_service", "destination_principal", "source_principal", "connection_security_policy", "grpc_response_status", "source_version", "destination_version", "request_protocol", "source_canonical_revision", "destination_canonical_revision"]
                    },
                    {
                      "name": "request_duration_milliseconds",
                      "tags_to_remove": ["response_code", "response_flags"],
                    },
                    {
                      "name": "request_bytes",
                      "tags_to_remove": ["response_code", "response_flags"],
                    },
                    {
                      "name": "response_bytes",
                      "tags_to_remove": ["response_code", "response_flags"],
                    }
                  ]
                }
```

Resolved the issue.

@douglas-reid suggested https://github.com/istio/proxy/pull/2807, in particular https://github.com/istio/proxy/pull/2807/files#diff-db83bcb3df7f25cfb88ff0a20bbd5540 was likely the cause.

As a user - this was extremely difficult to debug.

**Comment by kyessenov** [comment]
@Stono Yes, the fix is right. I am entirely with you on the danger of EnvoyFilters.
RE: schema, I think we should do a better job in istio on enforcing JSON format. Protobuf is very lax so some gray areas like duplicate keys are accepted by protobuf parser, but not other common JSON parsers.

**Comment by douglas-reid** [comment]
@Stono is this OK to close now?

**Comment by Stono** [comment]
It depends, do we not want to tackle the UX issue here in some way?

**Comment by douglas-reid** [comment]
@kyessenov how hard would it be to write a validator / converter across the parsing regimes ?

**Comment by kyessenov** [comment]
@douglas-reid Do you mean a validator for EnvoyFilters? There is a long list of tasks to make EnvoyFilter between upgrades (see https://github.com/istio/istio/issues/26627). It's not even possible to do it completely, but we want to carve out a subset that's reasonable.

For this issue specifically, I'm not sure _where_ to put the tool. Istio does not have any custom code for extensions besides EnvoyFilters. The extension itself is not appropriate since we removed protobuf to make it smaller (the parser from protobuf easily takes a megabyte of binary, more than the extension itself).

**Comment by mandarjog** [comment]
I agree that this *was* a behaviour change.
@Stono I am curious, do you use proto json encoding elsewhere as well, or was it inadvertent use here?

**Comment by Stono** [comment]
This is the only place we use it

**Comment by ssuchter** [comment]
Should metrics not working be possible to consider as a failure, so that canary upgrades would cause a rollback?

**Comment by mandarjog** [comment]
Yes, In fact a traffic metrics based canary would automatically stop progress when it suddenly cannot find metrics.

**Comment by Stono** [comment]
@douglas-reid that's right, we only use `source` metrics.

Is there anything to do on this issue, or is it just a learning piece that we can close off?
