### ISSUE TITLE
Deprecated + remove `centralIstiod` flag in 1.9

### ISSUE THREAD

**Issue by irisdingbj** [istio/istio#27865]

**Comment by hzxuzhonghu** [comment]
Isn't this targeted in 1.8?

**Comment by irisdingbj** [comment]
The plan is  we will support both flag in 1.8.  Old flag will be deprecated in 1.9.

**Comment by linsun** [comment]
It is already deprecated (but still supported) in 1.8.  In 1.9, it can be removed. :)

**Comment by linsun** [comment]
@brian-avery @ericvn could you kindly create 1.9 milestone?

**Comment by ericvn** [comment]
@linsun Milestone created with https://github.com/istio/bots/pull/286.
