### ISSUE TITLE
gRPC-Web requests on Safari fail

### ISSUE THREAD

**Issue by pereslava** [istio/istio#27869]
**Bug description**

We have web-kit internal error during grpc-web requests using istio 1.7.3

There is issue of envoy-proxy.
This issue already fixed and merged to envoy repository.

The issue: https://github.com/envoyproxy/envoy/issues/10514
The pull request: https://github.com/envoyproxy/envoy/pull/12178

[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Safary should not crash

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
```
istioctl version --remote
client version: 1.7.3
control plane version: 1.7.3
data plane version: 1.7.3 (14 proxies)

kubectl version --short
Client Version: v1.19.2
Server Version: v1.18.8
```
**How was Istio installed?**
istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**
k8s, digitalocean

**Comment by Denis2017** [comment]
I have the same problem, exactly the same.
The problem with envoy-proxy.
Looking forward to the update!

**Comment by howardjohn** [comment]
Istio 1.8 will have Envoy 1.16, I think there is nothing additional we need to do?

**Comment by pereslava** [comment]
Thanks, this is exactly i expected to hear.
So can this issue be assigned to roadmap of 1.8?
Also will be great to have the clear way (documentation or cli) to know which version of each component used by istio, whether it can be controlled by user or no.

**Comment by howardjohn** [comment]
This will be included in https://github.com/istio/istio/wiki/Istio-Release-1.8 as part of our update of envoy to 1.16. Thanks!
