### ISSUE TITLE
1.8 Pilot regression: high CPU/memory usage from grpc.(*Server).useTransportAuthenticator

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#27877]
[pprof.pilot-discovery.samples.cpu.243.pb.gz](https://github.com/istio/istio/files/5362244/pprof.pilot-discovery.samples.cpu.243.pb.gz)
[pprof.pilot-discovery.alloc_objects.alloc_space.inuse_objects.inuse_space.100.pb.gz](https://github.com/istio/istio/files/5362246/pprof.pilot-discovery.alloc_objects.alloc_space.inuse_objects.inuse_space.100.pb.gz)

**Comment by howardjohn** [comment]
There is a connection leak. Might be related to xDS proxy?

I have 68984 open connections on one istiod which has only 200 open gRPC streams

**Comment by howardjohn** [comment]
A single proxy has ~600 open connections so seems pretty clearly we are leaking here

Logs:
```
2020-10-11T22:09:38.577050Z     warning envoy config    StreamAggregatedResources gRPC config stream closed: 14, transport is closing
2020-10-11T22:09:38.621050Z     info    xdsproxy        connecting to istiod.istio-system.svc:15012
```

repeated every 5min

**Comment by hzxuzhonghu** [comment]
Why would connection leak related to cpu usage? maybe two issues

**Comment by hzxuzhonghu** [comment]
The connection leak is because we dial a connection each time the previous stream closed

**Comment by hzxuzhonghu** [comment]
IC, the cpu usage is caused by the authentication for each new connection

**Comment by hzxuzhonghu** [comment]
@howardjohn If you haven't started, let me fix the connection issue

**Comment by howardjohn** [comment]
Thanks @hzxuzhonghu
