### ISSUE TITLE
"transport is closing" when pods get terminated

### ISSUE THREAD

**Issue by Stono** [istio/istio#27874]
**Bug description**
`istiod` has noisy logs that don't feel that important, but they're logged at an `error` level?  For example:

```
{"level":"warn","time":"2020-10-12T16:20:32.615897Z","scope":"ads","msg":"EDS: Send failure sidecar~10.206.6.254~tests-1602519600-68dtk.istio-test-app-1~istio-test-app-1.svc.cluster.local-23: rpc error: code = Unavailable desc = transport is closing"}
{"level":"warn","time":"2020-10-12T16:30:24.031208Z","scope":"ads","msg":"EDS: Send failure sidecar~10.206.6.2~tests-1602520200-x82t9.istio-test-app-1~istio-test-app-1.svc.cluster.local-24: rpc error: code = Unavailable desc = transport is closing"}
{"level":"warn","time":"2020-10-12T16:40:26.243810Z","scope":"ads","msg":"EDS: Send failure sidecar~10.206.2.130~tests-1602520800-fjshr.istio-test-app-1~istio-test-app-1.svc.cluster.local-25: rpc error: code = Unavailable desc = transport is closing"}
```

These happen when the pod terminates during a config push.  

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Expected behavior**
I have two trains of thought for this:

1. perhaps `istio-proxy` should gracefully shut down, eg - don't terminate the connection with `istiod` mid push
2. at the least, it doesn't feel like an `error` level, as there's nothing actionable and it's actually "normal" operation?

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
1.16.12

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by Stono** [comment]
Ignore me, I messed up my log config and thought it was on warn, it wasn't.

**Comment by Stono** [comment]
Reopened as I have updated the original post with examples of the `warn` push errors

**Comment by howardjohn** [comment]
I think this one is fixed by https://github.com/istio/istio/commit/ec05f73c8fddf2c85639febd967bf6048acd18d9 in 1.7

**Comment by howardjohn** [comment]
Closing as this is fixed in supported versions
