### ISSUE TITLE
Merged codes in PR #27319 are reverted on master

### ISSUE THREAD

**Issue by BbolroC** [istio/istio#27886]
Hello, 

I am writing here about what I found on `master` because I have no idea of where to ask.

The merged codes in `common/scripts/setup_env.sh` (see #27319) was reverted in the [commit](https://github.com/istio/istio/commit/0c0cf2d6fbca85beca0598de8817ff90107ddd0c#) by `istio-testing`.

It would be grateful to tell me why and point me out to an appropriate place to ask this question if this is not a correct place.

Thanks.

**Comment by sdake** [comment]
Things are reverted all the time, often for not a great reason, or as part of refactoring. I looked in the repository and found no actual revert. I am not sure what changed enough to remove the s390x work.

Our semi-official stance on other architectures is they are permitted. The istio project will not ship distributions on arch other than x86_64. The Istio project will, however, permit PRs that enable other architectures.

Would you mind resubmitting your work?

Cheers,
-steve

**Comment by BbolroC** [comment]
Understood, I will include them in my next PR. Thank you. I will close this.
