### ISSUE TITLE
istio DeleteCollection operation fails can't return error

### ISSUE THREAD

**Issue by tanjunchen** [istio/istio#27910]
**Bug description**
```
	clusterConfig, err := clientcmd.BuildConfigFromFlags("", Kubeconfig())
	if err != nil {
		fmt.Println(err)
	}
	istio, err := versionedclient.NewForConfig(clusterConfig)
	err = istio.NetworkingV1beta1().Gateways("test").DeleteCollection(context.TODO(), metav1.DeleteOptions{}, metav1.ListOptions{})
	fmt.Println("===>", err)
```
The DeleteCollection operation will not return an error regardless of whether the resource exists.

[ ] Docs
[ ] Installation
[] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[x] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

```
[root@test-10 xxx]# istioctl version --remote
client version: 1.6.0
control plane version: 1.6.0
data plane version: 1.6.0 (3 proxies)
```

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

operator installation.

**Comment by tanjunchen** [comment]
see  
```

// DeleteCollection deletes a collection of objects.
func (c *gateways) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("gateways").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}
```

**Comment by tanjunchen** [comment]
@howardjohn  
I am trying to delete a resource that does not exist, but no error is reported.

**Comment by howardjohn** [comment]
I think this is purely a Kubernetes issue. I am not even sure its unintended behavior, really. Lets track in https://github.com/kubernetes/kubernetes/issues/95537
