### ISSUE TITLE
correct protocol for port 15012 for istiod when traffic is terminated at gw

### ISSUE THREAD

**Issue by linsun** [istio/istio#27921]
**Bug description**
Through experiments documented in [external istiod install ](https://docs.google.com/document/d/1F-it0wfjqcgzJBiQEgu3bYpwRQLCYkO4DB-5cusHw9A/edit?ts=5f853fa4) doc, we are attempting to change 15012 and 15017 to terminate the connection at the istio gw and have TLS among istio gw to external istiod.  So the flow attempted is:

sidecar (sends tls/jwt) --- istio gw on external istiod cluster (terminates tls, sends tls/jwt)--- external istiod.

This flow has proved to work well for istiod as webhooks server running on port 443, using https/tls as the protocol, which eliminated the need to use custom_istiod_host when the istio ingress gw has a trustable domain and key/certs associated with it.

This flow has issues for istiod as XDS server running on port 15012.  When tls is used as the protocol, I will get 

```protocol error: http/1.1 protocol error: HPE_INVALID_CONSTANT```

when grpc is used as the protocol, I will get ingress gw and sidecar proxies reach running but seems not very stable.  For the past 70+ mins, there are 6-7 restarts with my pod.  

```
$ k get pod                                                                                         
NAME                              READY   STATUS    RESTARTS   AGE
httpbin-779c54bf49-pfhcq          2/2     Running   6          75m
sleep-f8cbf5b76-lmrn7             2/2     Running   7          79m

$ k get pod -n istio2      
NAME                                   READY   STATUS    RESTARTS   AGE
istio-ingressgateway-fd5f5f4bd-gd8df   1/1     Running   7          79m
```

In the proxy log, it also indicated connectivity issues:

```
2020-10-13T19:50:24.419750Z	info	Envoy proxy is ready
2020-10-13T19:50:41.103070Z	error	xdsproxy	failed to create upstream grpc client: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: read tcp 172.30.115.122:32960->169.60.80.54:15012: read: connection reset by peer"
2020-10-13T19:50:41.103954Z	warning	envoy config	StreamAggregatedResources gRPC config stream closed: 14, connection error: desc = "transport: authentication handshake failed: read tcp 172.30.115.122:32960->169.60.x.x:15012: read: connection reset by peer"
2020-10-13T19:50:41.233711Z	info	xdsproxy	connecting to istiod2.management-cluster-xx.us-east.containers.appdomain.cloud:15012
```

[ ] Docs
[ ] Installation
[ x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
connection is possible and stable.

**Steps to reproduce the bug**
follow the external istiod doc mentioned earlier.

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
latest master as of today.

**Comment by linsun** [comment]
@howardjohn please correct me if I'm wrong here.

cc @nmittler @stevenctl @irisdingbj latest update on custom_istiod_host

**Comment by howardjohn** [comment]
relatd: https://github.com/istio/istio/issues/16282

**Comment by nmittler** [comment]
@linsun not entirely sure if I'm conflating topics or not ... 

For regular multicluster, we're now using a dedicated east-west gateway and will be using port 15012 with TLS passthrough. For that case, we don't need this hack ... correct? In other words, we won't need it for multicluster beta?

**Comment by linsun** [comment]
@nmittler you are not :) this is related.  This is relevant to multicluster as well when you run single control plane.  Basically, we will terminate connection for 15017 but continue to use pass through for 15012 because only passthrough works for 15012 atm.

**Comment by howardjohn** [comment]
I think you can also set h2upgade on the DR instead of changing the Service btw. We should look into changing the service though.

**Comment by nmittler** [comment]
@linsun 

> @nmittler you are not :) this is related. This is relevant to multicluster as well when you run single control plane. Basically, we will terminate connection for 15017 but continue to use pass through for 15012 because only passthrough works for 15012 atm.

But for 1.8, we won't be using the TLS termination, correct? So this hack won't be needed for 1.8 as it stands. Or am I missing something?

**Comment by howardjohn** [comment]
@nmittler that is correct for our docs. But Lin is doing termination (which should be our recommended best practice in the future)

**Comment by nmittler** [comment]
@howardjohn yup, and that's were my aforementioned conflation comes in :).  I'm currently putting blinders on for 1.8 and want to make sure we're not using the hostname hack unless it's specifically needed (which it's not for 1.8).

**Comment by linsun** [comment]
@howardjohn any example on setting h2upgrade on DR?

**Comment by linsun** [comment]
@nmittler @howardjohn for shared control plane in 1.8, we won't need hostname env var.  We only need it for testing when there is no host name and trustable key/certs for the gw.  We'll just terminate the connection at the gw for webhooks in the case of shared control plane multicluster model or external istiod model.

**Comment by linsun** [comment]
Another update on this, h2 upgrade does seem to work fine, no restarts on pod so far, no error on connectivity to gw/ external istiod.  Config used - https://github.com/istio/istio/issues/27960#issue-721772949
