### ISSUE TITLE
Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 2 successful, 0 rejected; lds updates: 0 successful, 2 rejected

### ISSUE THREAD

**Issue by raviatsapient** [istio/istio#27939]
Hi,

I am getting this issue with sidecar, istio-proxy container not coming up. Getting logs continually 
Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 2 successful, 0 rejected; lds updates: 0 successful, 2 rejected

**Comment by raviatsapient** [comment]
istioctl-6.7 x describe pod echoserver-6f49c86d87-dk2t7.echoserver 
Pod: echoserver-6f49c86d87-dk2t7.echoserver
   Pod Ports: 8080 (echoserver), 15090 (istio-proxy)
WARNING: Pod echoserver-6f49c86d87-dk2t7.echoserver Container istio-proxy NOT READY
Suggestion: add 'version' label to pod for Istio telemetry.
--------------------
Service: echoserver.echoserver
   Port: http 9999/HTTP targets pod port 8080
WARNING: Proxy is stale; it references to non-existent destination rule default.istio-system
Skipping Gateway information (no ingress gateway pods)

**Comment by raviatsapient** [comment]
istioctl-6.7 proxy-config listeners echoserver-6f49c86d87-dk2t7.echoserver 
ADDRESS            PORT      TYPE
172.28.145.248     443       TCP
172.28.146.234     443       TCP
10.84.129.104      15012     TCP
172.28.145.157     443       TCP
172.28.145.124     15443     TCP
172.28.144.29      443       TCP
172.28.144.10      53        TCP
172.28.145.78      443       TCP
172.28.144.1       443       TCP
172.28.147.251     443       TCP
172.28.145.124     443       TCP
172.28.144.29      15012     TCP
172.28.146.233     443       TCP
172.28.146.159     443       HTTP+TCP
0.0.0.0            7979      HTTP
172.28.146.142     8118      HTTP+TCP
0.0.0.0            80        HTTP
172.28.145.249     9402      HTTP+TCP
0.0.0.0            20001     HTTP
0.0.0.0            9091      HTTP
0.0.0.0            15004     HTTP
0.0.0.0            15014     HTTP
172.28.145.124     15021     HTTP+TCP
172.28.147.179     42422     HTTP+TCP
172.28.145.27      44134     HTTP+TCP
0.0.0.0            9090      HTTP
172.28.145.235     5473      HTTP+TCP
172.28.144.29      853       HTTP+TCP
0.0.0.0            15010     HTTP
0.0.0.0            9999      HTTP
0.0.0.0            15001     UNKNOWN
0.0.0.0            15006     HTTP+TCP
0.0.0.0            15090     HTTP
0.0.0.0            15021     HTTP

**Comment by howardjohn** [comment]
Post the full log. It will show why it was rejected.

**Comment by howardjohn** [comment]
We cannot debug this without more info, please reopen if you can provide the logs. Thanks!
