### ISSUE TITLE
TestValidation and TestProxyStatus failures

### ISSUE THREAD

**Issue by stevenctl** [istio/istio#27950]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27949/integ-pilot-k8s-tests_istio/21703

In validation test, issues reaching istiod on 443. 
```
  validation_test.go:113: got unexpected unknown error for valid config: error when creating "/logs/artifacts/pilot-05736fffe9144bfe8bc1e47a9/TestValidation/networking-v1alpha3-Gateway-valid.yaml/_test_context/tmpyaml_796103670": Internal error occurred: failed calling webhook "validation.istio.io": Post "https://istiod.istio-system.svc:443/validate?timeout=30s": dial tcp 10.96.46.44:443: connect: connection refused: 
```

in proxy status test, looks like pretty much all virtual hosts on the envoy are missing in istiod. 

Assuming istiod is crashing or something, but not sure.

**Comment by stevenctl** [comment]
Don't see other examples on test grid, but this is suspicious because it occurred on a PR that only touches a readme: https://github.com/istio/istio/pull/27949

**Comment by stevenctl** [comment]
No idea if they're related, but also see some failures for TestAnalysisWritesStatus

https://prow.k8s.io/view/gcs/istio-prow/pr-logs/directory/integ-pilot-k8s-tests_istio/21705
https://prow.k8s.io/view/gcs/istio-prow/pr-logs/directory/integ-pilot-k8s-tests_istio/21698
https://prow.k8s.io/view/gcs/istio-prow/pr-logs/directory/integ-pilot-k8s-tests_istio/21693
https://prow.k8s.io/view/gcs/istio-prow/pr-logs/directory/integ-pilot-k8s-tests_istio/21692

**Comment by howardjohn** [comment]
```

      {
        "name": "discovery",
        "state": {
          "running": {
            "startedAt": "2020-10-14T18:33:04Z"
          }
        },
        "lastState": {
          "terminated": {
            "exitCode": 2,
            "reason": "Error",
            "startedAt": "2020-10-14T18:30:45Z",
            "finishedAt": "2020-10-14T18:33:02Z",
            "containerID": "containerd://9c3fa14a8f04271f5b9ca7e39f5a23ebdb469b49f8f99756fc5182a6a9694079"
          }
        },
        "ready": true,
        "restartCount": 1,
        "image": "localhost:5000/pilot:istio-testing",
        "imageID": "localhost:5000/pilot@sha256:df303c7298f97f7ab7880cdc83e6d895cbfdfcc797a8a38b2039c8925aeb48c7",
        "containerID": "containerd://a06025fe958fbf21582df875fc3030c15ea7426c6adc3699f71ffc9a1a224075",
        "started": true
      }
    ],
```

pilot crashed

I think we need to fetch the `-p` logs as well in the dump.

**Comment by stevenctl** [comment]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27954/integ-pilot-multicluster-tests_istio/2662 seems to have a pilot crash as well.

**Comment by howardjohn** [comment]
I will add logs for the crashes. we should probably also fail on crash.. I realize we do here but there are cases where we pass despite a crash

**Comment by howardjohn** [comment]
closing in favor of https://github.com/istio/istio/issues/27978
