### ISSUE TITLE
TestAnalysisWritesStatus test flakes

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#27951]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27948/integ-pilot-k8s-tests_istio/21698

Likely since https://github.com/istio/istio/pull/27937

cc @therealmitchconnors @nmittler

**Comment by nmittler** [comment]
@howardjohn Just sent a partial revert: https://github.com/istio/istio/pull/27952

@therealmitchconnors I raised https://github.com/istio/istio/issues/27953 and assigned to you to address the flake.
