### ISSUE TITLE
Move pilot analysis test

### ISSUE THREAD

**Issue by nmittler** [istio/istio#27953]
Now that the analysis test requires no custom configuration, we should move it to the top-level pilot tests so that we don't have to reinstall Istio (i.e. tests should run faster).

I previously tried doing this, but it resulted in the test flaking (#27951). Need to investigate why this test was flaky when run as a part of the main pilot tests.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[x] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/27949/integ-pilot-k8s-tests_istio/21703/artifacts/pilot-05736fffe9144bfe8bc1e47a9/_suite_context/istio-state-460661362/cluster-0/istiod-745b5f7c8b-gxzds_discovery.log shows lots of errors in istiod

**Comment by howardjohn** [comment]
Not stale
