### ISSUE TITLE
Add documentation on go:generate usage for Mixer adapters

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio#2797]

**Comment by gargnupur** [comment]
When all do we need to run go:generate? I know of following:
1) istio/api sha change: https://github.com/istio/istio/pull/6345 -> should take care of it? Can add documentation about this in Vendor FAQ once PR is approved
2) When building new adapter config and https://github.com/istio/istio/wiki/Mixer-Adapter-Walkthrough#step-2-write-adapter-configuration should cover that part of the documentation.

Are there any other scenarios for which we need this documentation?

**Comment by hklai** [comment]
@douglas-reid 
2018/06 Snapshot (pre 1.0) has passed. Should this remain P0 for 1.0?
