### ISSUE TITLE
How to set the pilot-discovery parameter when you install istio 1.6.0 cluster?

### ISSUE THREAD

**Issue by tanjunchen** [istio/istio#27981]
How to change the default parameter values  for pilot-discovery when installing istio 1.6.0 cluster? 

see https://istio.io/v1.6/docs/reference/commands/pilot-discovery/.

Can the parameters be set like this for pilot-discovery?

```
istioctl install --set values.global.controlPlaneSecurityEnabled=true
```

**Comment by howardjohn** [comment]
@tanjunchen these options are not configurable without patching. Generally these are all experimental options.
