### ISSUE TITLE
INJECTION_WEBHOOK_CONFIG_NAME defined in values.pilot.env will not be respected

### ISSUE THREAD

**Issue by irisdingbj** [istio/istio#27986]
we have below def for `INJECTION_WEBHOOK_CONFIG_NAME` :
 ```
         - name: INJECTION_WEBHOOK_CONFIG_NAME
          {{- if eq .Release.Namespace "istio-system" }}
            value: istio-sidecar-injector{{- if not (eq .Values.revision "") }}-{{ .Values.revision }}{{- end }}
          {{- else }}
            value: istio-sidecar-injector{{- if not (eq .Values.revision "") }}-{{ .Values.revision }}{{- end }}-{{ .Release.Namespace }}
          {{- end }}
```
This will make `INJECTION_WEBHOOK_CONFIG_NAME` always been defined even if you have below entry in your IOP:

```
  values:
    pilot:
      env:
        INJECTION_WEBHOOK_CONFIG_NAME: ""
```

It will have duplicate entry in generated manifest:
```
      - name: INJECTION_WEBHOOK_CONFIG_NAME
         value: ""
      - name: INJECTION_WEBHOOK_CONFIG_NAME
        value: istio-sidecar-injector-istio1
```

**Comment by linsun** [comment]
@irisdingbj wonder if it is better to use externalIstiod flag, e.g. 

if externalIstiod and no istiod_custom_host:
  // no patch needed
  INJECTION_WEBHOOK_CONFIG_NAME: ""
else:
  // continue patching

**Comment by irisdingbj** [comment]
> @irisdingbj how about this logic?
> 
> if istiod_custom_host:
> // patch
> if config cluster is local:
> // patch
> else:
> // no patch
> INJECTION_WEBHOOK_CONFIG_NAME: ""

Thanks @howardjohn for the suggestion in #27987 and it works perfectly.   @linsun PTAL, Thanks!
