### ISSUE TITLE
Add/update existing adapter docs on deployment for make push, etc.

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio#2799]

**Comment by gargnupur** [comment]
@douglas-reid , @geeknoid : Following doc covers deploying mixer using make push
https://github.com/istio/istio/wiki/Mixer-Using-a-Custom-Adapter 

Verified it works and edited it to change istio-mixer to istio-telemetry for deployments..

Please let me know if we should anything more to this...

**Comment by geeknoid** [comment]
Beautiful, thanks!
