### ISSUE TITLE
create istio-announce@ or remove reference to it; ditto for twitter account

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#280]
at the bottom of https://istio.io/blog/0.1-announcement.html
it says
"And follow @istio on Twitter or join istio-announce@ for key announcements regarding the project."

that group/list doesn't exist yet. once it exist it should be a hyperlink (probably so does the twitter link (happy to do the linking once it exists))

source is https://github.com/istio/istio.github.io/blob/master/_posts/2017-05-01-0.1-announcement.md

**Comment by ldemailly** [comment]
https://twitter.com/istio is someone else so we need to change that too

**Comment by geeknoid** [comment]
The group has been created and I linked to it from the docs.

I opened a separate issue to track the creation of a Twitter account, and adding it to a few spots in the docs. I also created an issue to track the completion of the release announcement blog post (what we have in the repo right now is just a snapshot of WIP)
