### ISSUE TITLE
kube-inject command confusing param on namespaces

### ISSUE THREAD

**Issue by linsun** [istio/istio#28005]
**Bug description**

```
Global Flags:
      --context string          The name of the kubeconfig context to use
  -i, --istioNamespace string   Istio system namespace (default "istio-system")
  -c, --kubeconfig string       Kubernetes configuration file
  -n, --namespace string        Config namespace
```

Runing kube-inject cmd on a system where istio-sidecar-injector is installed in ns istio2, took me a while to figure out not use `-n` but use `-i` instead.  What is the purpose of `-n`?  If no good reason, I recommend us enhance it to search for sidecar innjector cm in the `-n` ns.

```
$ istioctl kube-inject -n istio2 -f samples/httpbin/httpbin.yaml
Error: could not find valid configmap "istio-sidecar-injector" from namespace  "istio-system": configmaps "istio-sidecar-injector" not found - Use --injectConfigFile or re-run kube-inject with `-i <istioSystemNamespace> and ensure istio-sidecar-injector configmap exists
(⎈ |linistio10/7caab3af9f514f028081a8180c107b69:default)
~/go/src/istio.io/istio on  master! ⌚ 13:56:57
$ k get cm -n istio2
NAME                                   DATA   AGE
istio                                  2      2d15h
istio-ca-root-cert                     1      2d15h
istio-leader                           0      2d15h
istio-namespace-controller-election    0      2d15h
istio-sidecar-injector                 2      2d15h
istio-validation-controller-election   0      2d15h
```

cmd that worked:

```
$ go run "${GOPATH}"/src/istio.io/istio/istioctl/cmd/istioctl/main.go kube-inject -i istio2 -f samples/httpbin/httpbin.yaml 
```

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by linsun** [comment]
@esnible @therealmitchconnors

**Comment by esnible** [comment]
Good catch, @linsun 

I verified there is no output when `diff <(istioctl kube-inject -f samples/bookinfo/platform/kube/bookinfo.yaml) <(istioctl kube-inject -n foo -f samples/bookinfo/platform/kube/bookinfo.yaml)` is executed.

@shamsher31 This parameter is inherited from _root.go_ and should be removed from any command that doesn't use the value.
