### ISSUE TITLE
kube-injected yaml doesn't deploy well on ns with injection enabled

### ISSUE THREAD

**Issue by linsun** [istio/istio#28007]
**Bug description**

Injected yaml of httpbin doesn't deploy in my default ns that has injection enabled.  Had to disable auto injection to get it deployed.

There must be some duplicated injection we are doing or something. The log shows something related to Prometheus.
```
2020-10-15T18:15:46.956857Z	error	invalid prometheus scrape configuration: application port is the same as agent port, which may lead to a recursive loop. Ensure pod does not have prometheus.io/port=15020 label, or that injection is not happening multiple times
Error: invalid prometheus scrape configuration: application port is the same as agent port, which may lead to a recursive loop. Ensure pod does not have prometheus.io/port=15020 label, or that injection is not happening multiple times

```

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ x ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
https://github.com/istio/istio/issues/25931 is the fix for this. Or a hack by just adding a label, but the general solution is better
