### ISSUE TITLE
Add/update documentation on running a local mixer (remove bazel refs)

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio#2800]

**Comment by gargnupur** [comment]
Updated https://github.com/istio/istio/wiki/Mixer-Running-a-Local-Instance to use mixs and mixc.

https://github.com/istio/istio/wiki/Mixer-Adapter-Walkthrough was updated before to remove any bazel refs.

@douglas-reid , @geeknoid : Please see if this looks ok and we can close this item accordingly.

**Comment by geeknoid** [comment]
Looks good. Thanks!
