### ISSUE TITLE
StatusReporter memory leak

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#28015]
Two leaks:

First is around non core types. We do not properly deregister them

Second is a race. If we are currently processing a request: https://github.com/istio/istio/blob/9d42db66498efea3cb27ba84aafee8d64dfac495/pilot/pkg/xds/ads.go#L172 and proxy disconnected https://github.com/istio/istio/blob/9d42db66498efea3cb27ba84aafee8d64dfac495/pilot/pkg/xds/ads.go#L755, we will leak and event because we dergister everything on the disconnect, but then we register an event again which is never ACKed as we have disconnected

Possibly related: https://github.com/istio/istio/issues/21186

**Comment by howardjohn** [comment]
I will fix the first

**Comment by therealmitchconnors** [comment]
I'm thinking the way to fix this is to add the disconnect event to the queue like any other so that it can be processed in order.  Thoughts?

**Comment by howardjohn** [comment]
without digging into it the seems reasonable. Unless we can have sequence RegisterEvent, RegisterDisconnect, RegisterEvent which leaks. I am not sure if it does, just something to watch out for.

**Comment by howardjohn** [comment]
not stale
