### ISSUE TITLE
Add support for STRING_LIST value type

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio#2802]
FR: use case is authz template for "Group".

cc: @liminw

**Comment by jon-whit** [comment]
I'd be happy to do this for the Istio community as I have an immediate need for it in my work as well. However, I could use a quick outline of the things I'll need to do to introduce a new Value type. I've done quite a bit of searching through the codebase and it appears the primary sources that need to be modified (not including test files) are:
```
mixer/pkg/lang/externs.go
mixer/pkg/lang/compiler/compiler.go
mixer/tools/codegen/pkg/bootstrapgen/generator.go
```

Is that correct? Also, any quick tips to add a new value type would be useful :+1:

**Comment by douglas-reid** [comment]
I believe you will first need to introduce the new value type in the istio/api repo (https://github.com/istio/api/blob/master/policy/v1beta1/value_type.proto)

**Comment by jon-whit** [comment]
@douglas-reid I was just going to add that :)

Looks like `value_type.proto` in api/policy/v1beta1, correct?

**Comment by jon-whit** [comment]
@douglas-reid Do you want to assign this one to me? I'm thinking I'm going to tackle this and #6984 .

However, before I do so, I'd like to know what the plan is for RBAC in 1.0. I've heard some large changes are coming in 1.0 for the RBAC implementation, so I don't want to be contributing work that is irrelevant.

**Comment by douglas-reid** [comment]
I'm happy to assign to you, but it appears github limits my abilities there. I'll try via command.

/assign jon-whit

I can't speak directly to RBAC changes, but I think this feature would be relevant outside of the RBAC use case. We would likely want to introduce functions like `in()`, etc. to handle lists along with the support and that could pay benefits down the road.

**Comment by yangminzhu** [comment]
@jon-whit 
In Istio 1.0, RBAC is changed to use the upstream [Envoy RBAC filter](https://github.com/envoyproxy/envoy/tree/master/source/extensions/filters/http/rbac), you will need to add some additional support in upstream Envoy to make the RBAC filter to support list value type. This should be easy as we already have framework code in Envoy to help on this.

This could be done after you finished the work in mixer side, let me know if you need any help and thank you for helping on this!

**Comment by lei-tang** [comment]
https://github.com/istio/proxy/pull/1925

**Comment by patrickbadley** [comment]
This seems related if not identical to the issue I'm encountering, has this been coded?  My issue is that my token has a claim that holds an array of values, however when istio parses it, it doesnt not recognize the array value and ignores the claim.  If I change the claim value to be a string, it recognizes it.  Here are my raw claims:
fields {
      key: "request.auth.raw_claims"
      value {
        string_value: "{\"at_hash\":\"...\"family_name\":\"amAdmin\",\**"app_roles\":[\"Administrator\"]**,\"iat\":1543526958}"
      }
    }

**Comment by kyessenov** [comment]
Is there an interest in list of values beyond the strings?
Lists of ints? Lists of floats? Lists of IP addresses?

**Comment by patrickbadley** [comment]
> Is there an interest in list of values beyond the strings?
> Lists of ints? Lists of floats? Lists of IP addresses?

My use case only requires a list of strings, however, since JWTs support having multiple claims with the same key, presumably you should be able to have an array of any type that is supported as the value of a claim.  Does that make sense?  If claims with values of string, float, int, ip address (i would think this would just be a string, but following your example...) then arrays of all those values should be accepted as well.  Thanks!

**Comment by douglas-reid** [comment]
@kyessenov do you want to own resolving this (as it somewhat relates to the CEL work)?

**Comment by kyessenov** [comment]
Sure, happy to. Is this scheduled for some milestone?

**Comment by douglas-reid** [comment]
Well, theoretically 1.2, but that is very much up for debate. I don't think it is urgent, but if it is easy to add while doing the CEL work, it would be worth doing, imho.

**Comment by Arpeet-gupta** [comment]
https://blog.opstree.com/2020/04/07/preserve-source-ip-in-aws-classic-load-balancer-and-istios-envoy-using-proxy-protocol/
