### ISSUE TITLE
Mitigate dockerhub image rate limitting

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#28031]
https://docs.docker.com/docker-hub/download-rate-limit/

CI Impact:
* Base image is on docker.io, pulled each run
* Kind image is on docker.io, pulled each run
* buildkit image is on docker.io, pulled each run

User impact:
* May be limited in number of images they can pull, especially proxy image

**Comment by howardjohn** [comment]
For users: I think its pretty clear we should mirror images to 1 or more registries. I strongly recommend we mirror images to gcr.io/istio-release at a minimum, but its trivial to additionally mirror to another registry (I have heard quay mentioned) if we are interested

**Comment by howardjohn** [comment]
For CI, GCR is superior just because it runs in GCP so its faster:
* Base image can just be moved to GCR
* Kind image can be mirrored to GCR manually. I opened https://github.com/kubernetes-sigs/kind/issues/1895
* Buildkit: can be mirror to gcr manually

**Comment by ceastman-ibm** [comment]
@howardjohn Is there a possibility we could build our own proxy-image with a different base OS? like redhat's UBI

**Comment by howardjohn** [comment]
I am not sure how that is related to the docker rate limiting?

**Comment by ceastman-ibm** [comment]
The proxy image could be stored in a private repo so docker hub is getting pulled from. Just a thought.

**Comment by howardjohn** [comment]
We can store the final image wherever we want regardless of the base image we use I believe

**Comment by howardjohn** [comment]
I think once https://github.com/istio/istio/pull/28517 and https://github.com/istio/release-builder/pull/448 land this is done

**Comment by ericvn** [comment]
I think this satisfies the problems our pipeline will have, but do we have want to update so a customer install will pull from gcr.io. I think this just makes the images available there, but doesn't actually update the code so a customer install uses gcr.io. Or maybe I missed a PR.

**Comment by sdake** [comment]
@howardjohn I have the `istio` namespace on quay.io that I registered 3+ years ago when starting work on Istio. Thought it may come in handy at some point 👍 

I would like to mirror to quay please. @stewartbutler I will wait for your mirror PR to merge, and then setup quay.io as a second mirror.

Cheers,
-stee

**Comment by sdake** [comment]
> @howardjohn Is there a possibility we could build our own proxy-image with a different base OS? like redhat's UBI

@ceastman-ibm, the request you have made isn't related to the docker hub image rate limiting in this issue tracker. Please file a new enhancement request for such a feature.

The Istio tree supports multiple base images and could - in theory - support UBI in addition to Debian and distroless.

The real challenge with UBI is ensuring it has the proper set of base libraries to support Envoy.

If you open a separate enhancement request, the maintainers could evaluate the work required to enable UBI. In that enhancement request, you should answer `Why UBI` - how does the community of developers and vendors benefit from such action. Envoy will be the hardest component to build on UBI - the remaining containers should (in theory) be straightforward.

Cheers,
-steve

**Comment by sdake** [comment]
@ericvn I think at a minimum - we must change the image source for every released version of Istio as well as any maintenance releases. This is a lot of work - but I foresee a future, especially in high churn environments, where there are major complaints about Istio "not working" because the source hub is invalid.

While we all know docker hub should not be used in production, it certainly is used in the evaluation today, and sadly may be used in many production environments.

Cheers,
-steve

**Comment by ericvn** [comment]
From a user perspective, the can specify the hub on the install: `istioctl install --set profile=demo --set hub=gcr.io/istio-release` to pull from another repo (either gcr.io or one where they have the images)

**Comment by ericvn** [comment]
Closing this issue (the P0 portion for pipeline failures). We can open another issue, likely a P1, where we talk about the customer impacts. As noted, there is a way to specify a different hub for things like install, and we may want to update the defaults in the charts.
