### ISSUE TITLE
Istio zipkin distributed tracing UI doesn't show mixer

### ISSUE THREAD

**Issue by linsun** [istio/istio#2803]
Attaching a screen shot and some discussion on #mixer channel.  It is confusing that mixer is not in there because user is confused that mixer is not in the picture while it is expected to be and used to be.  @ZackButcher thinks this is caused by mixer client to record cache hits in the traces, which I would think user will want to see that too.

https://istio.slack.com/files/U3BDG8WLD/F8WUDRUBC/image.png

**Comment by objectiser** [comment]
This is strange, as Jaeger can see traces from the mixer (based on the same zipkin data) - although they are no longer part of the overall trace. For example, when doing a single bookinfo request, I can see multiple mixer traces:

![istio-jaeger-search-mixer](https://user-images.githubusercontent.com/164562/35400043-af71b3f2-01ed-11e8-9bd6-66a479aa887c.png)

These used to be an integral part of overall trace, but now seem to be orphaned - so the trace context is not being propagated through to the mixer.

An example of one of the mixer traces is now:

![istio-jaeger-mixer-trace](https://user-images.githubusercontent.com/164562/35400107-d6af6a22-01ed-11e8-8309-1ccc185e4b26.png)

with the application trace, starting at the ingress:

![istio-jaeger-ingress-trace](https://user-images.githubusercontent.com/164562/35400126-e0ffa762-01ed-11e8-9478-7e7448ae6d3e.png)

**Comment by douglas-reid** [comment]
I believe this has been fixed in the intervening time.
