### ISSUE TITLE
Add pprof endpoint to pilot-agent

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#28040]
To help debug performance issues, memory leaks, deadlocks, etc.

This can safely be added over localhost port 15020 - we already have far more dangerous quitquitquit there so no problem adding another admin endpoint.

Would match similar code in istiod:
```
pilot/pkg/xds/debug.go
150:            s.addDebugHandler(mux, "/debug/pprof/", "Displays pprof index", pprof.Index)
151:            s.addDebugHandler(mux, "/debug/pprof/cmdline", "The command line invocation of the current program", pprof.Cmdline)
152:            s.addDebugHandler(mux, "/debug/pprof/profile", "CPU profile", pprof.Profile)
153:            s.addDebugHandler(mux, "/debug/pprof/symbol", "Symbol looks up the program counters listed in the request", pprof.Symbol)
154:            s.addDebugHandler(mux, "/debug/pprof/trace", "A trace of execution of the current program.", pprof.Trace)
```

**Comment by daixiang0** [comment]
@howardjohn hi, i would like to do this, and i find that there are lots of ports to listen, is there a plan about it?

Or only need to implement GRPC server?

**Comment by howardjohn** [comment]
We should add here: https://github.com/istio/istio/blob/4e465fc12484a74fe26383eca726f48c34d35363/pilot/cmd/pilot-agent/status/server.go#L202 on port 15020. I think @carolynhu may be working on it already possibly

**Comment by carolynhu** [comment]
@daixiang0 I'm recently working on dashboard related stuff, haven't got a chance to look into much more about this. Sure, if you'd like to work on this ticket, I'm going to assign this to you. thanks.

**Comment by daixiang0** [comment]
@carolynhu i will do this :)
