### ISSUE TITLE
Change dns domain to not be cluster.local in tests

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#28053]
Can be done in kind with 

networking:
              dnsDomain: "${CLUSTER_SUFFIX}"

This will ensure our code does not make assumptions about cluster.local

**Comment by daixiang0** [comment]
@howardjohn do you mean add related config in `common/scripts/kind_provisioner.sh`?

**Comment by howardjohn** [comment]
Yes. The hard part will be making all the tests pass I would imagine :slightly_smiling_face:

**Comment by howardjohn** [comment]
not stale

**Comment by howardjohn** [comment]
Not stale

**Comment by zhlsunshine** [comment]
Hi @howardjohn & @zackzhangkai, shall we move this issue to 1.12?
