### ISSUE TITLE
subsets in isto is equivalent to subset concept in envoy?

### ISSUE THREAD

**Issue by mehdihadeli** [istio/istio#28051]
Hi,
Is subsets concept of istio equivalent to [subset concept](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/subsets) in envoy? or subsets in istio have different meaning?

**Comment by howardjohn** [comment]
Subsets in istio are different, they generate distinct clusters rather than subdividing a single cluster

**Comment by douglas-reid** [comment]
Closing, as this appears to have been answered.
