### ISSUE TITLE
Allow Mixer.Check  result to be combinational logic over adapter results

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#2806]
Mixer check call returns `ok` (`allow`) if all adapters dispatched during the request return `ok`
Adapter results are implicitly `ANDED`

Mixer should allow combinational logic over adapter results.

result = `( A &&  B ) || C`

---
Some issues to consider
1. How will an operator configure this?
    Operator needs to know which adapters will fire apriori and then keep the expression up to date with new adapters that are added. 
2. What will be the scope of such configuration? Service scope is reasonable.
3. As a potential simplification we could have a top level flag that will change `AND` behaviour to `OR`
4. An option: have a service scoped expression and and operator  (`AND or OR`)
    The final logic is  `expression operator rest_of_the_results'

**Comment by mandarjog** [comment]
@liminw

**Comment by kyessenov** [comment]
/assign @kyessenov

I'll take a look at this. I need this to expose routing directive.

**Comment by kyessenov** [comment]
Not stale.
