### ISSUE TITLE
With logAsJson enabled, some logs are still in the incorrect format

### ISSUE THREAD

**Issue by Stono** [istio/istio#28066]
**Bug description**
Pretty much as the title says, when we enable logAsJson, we still see some logs which aren't, for example:

```
{"level":"info","time":"2020-10-19T07:55:56.860235Z","msg":"pickfirstBalancer: HandleSubConnStateChange: 0xc000a65440, {READY <nil>}"}
{"level":"info","time":"2020-10-19T07:55:56.860243Z","msg":"Channel Connectivity change to READY"}
2020-10-19T07:55:56.904190Z	warning	envoy config	[bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:92] StreamAggregatedResources gRPC config stream closed: 14, no healthy upstream
2020-10-19T07:55:56.904275Z	warning	envoy config	[bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:54] Unable to establish new stream
2020-10-19T07:55:56.913492Z	warning	envoy main	[external/envoy/source/server/server.cc:475] there is no configured limit to the number of allowed active connections. Set a limit via the runtime key overload.global_downstream_max_connections
{"level":"info","time":"2020-10-19T07:55:56.917455Z","scope":"sds","msg":"resource:default new connection"}
{"level":"info","time":"2020-10-19T07:55:56.917569Z","scope":"sds","msg":"Skipping waiting for ingress gateway secret"}
```

Similar issue: https://github.com/istio/istio/issues/27873

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
Logs to be in json

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
1.6.12

**How was Istio installed?**
Helm

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
I cannot find a way to do this in envoy, opened https://github.com/envoyproxy/envoy/issues/13636.

Below diff gets us 90% of the way there:
```diff
diff --git a/pilot/cmd/pilot-agent/main.go b/pilot/cmd/pilot-agent/main.go
index a5570ba590..1cbaebec9d 100644
--- a/pilot/cmd/pilot-agent/main.go
+++ b/pilot/cmd/pilot-agent/main.go
@@ -368,6 +368,7 @@ var (
                                Config:              proxyConfig,
                                Node:                role.ServiceNode(),
                                LogLevel:            proxyLogLevel,
+                               LogAsJson:           loggingOptions.JSONEncoding,
                                ComponentLogLevel:   proxyComponentLogLevel,
                                PilotSubjectAltName: pilotSAN,
                                NodeIPs:             role.IPAddresses,
diff --git a/pkg/envoy/proxy.go b/pkg/envoy/proxy.go
index ff594be265..79f7db2386 100644
--- a/pkg/envoy/proxy.go
+++ b/pkg/envoy/proxy.go
@@ -47,6 +47,7 @@ type ProxyConfig struct {
        Config              meshconfig.ProxyConfig
        Node                string
        LogLevel            string
+       LogAsJson           bool
        ComponentLogLevel   string
        PilotSubjectAltName []string
        NodeIPs             []string
@@ -117,9 +118,17 @@ func (e *envoy) args(fname string, epoch int, bootstrapConfig string) []string {
                "--local-address-ip-version", proxyLocalAddressType,
                "--bootstrap-version", "3",
                "--log-format-prefix-with-location", "0",
+       }
+       if e.ProxyConfig.LogAsJson {
+               startupArgs = append(startupArgs,
+                       "--log-format-escaped", // Escape message, so json output is valid
+                       "--log-format",
+                       `{"level":"%l","time":"%Y-%m-%dT%T.%fZ","scope":"%n","msg":"%v"}`,
+               )
+       } else {
                // format is like `2020-04-07T16:52:30.471425Z     info    envoy config   ...message..
                // this matches Istio log format
-               "--log-format", "%Y-%m-%dT%T.%fZ\t%l\tenvoy %n\t%v",
+               startupArgs = append(startupArgs, "--log-format", "%Y-%m-%dT%T.%fZ\t%l\tenvoy %n\t%v")
        }

        startupArgs = append(startupArgs, e.extraArgs...)
```

**Comment by howardjohn** [comment]
When/if https://github.com/envoyproxy/envoy/pull/13832 merges we can pull this in. Seems likely to mean it may be until 1.9 though

**Comment by howardjohn** [comment]
https://github.com/envoyproxy/envoy/pull/13832 is merged, will pull it into master soon(ish)

**Comment by Stono** [comment]
Hey @howardjohn - on 1.8 we still see quite a few non-json warning from envoy, is this to be expected?

![Screenshot 2021-02-09 at 13 52 42](https://user-images.githubusercontent.com/1486729/107373144-19056500-6ade-11eb-8773-d2a7f4049d81.png)

**Comment by howardjohn** [comment]
Unfortunately the change (https://github.com/istio/istio/pull/29159) depends on a newer flag in envoy in 1.9. It looks like we actually backported it though: https://github.com/istio/envoy/commit/c658523104f0a55f56c7fa5f2a5cdda46f40c4ea, but didn't backport the change to use it.

So tl;dr is its expected but also could be fixed.

**Comment by howardjohn** [comment]
Cherrypick, but its still not going to be fully JSOn due to https://github.com/envoyproxy/envoy/issues/15020 unfortunately..
