### ISSUE TITLE
Add pilot-integration-test target to Makefile for circleci

### ISSUE THREAD

**Issue by ayj** [istio/istio#2807]
The `bin/pilot-integration-test` test parameters are currently hard coded in the `.circleci/config.yaml`. This would make it easier to update e2e tests without needing to touch circleci configuration. 

ref: https://github.com/istio/istio/pull/2796/files/520860e8db8b848180c5a6d4ee0e77fcabd6ec65?diff=unified#r163694959

**Comment by rshriram** [comment]
we have targets for everything in makefile now..
