### ISSUE TITLE
TCP Access Logging in Telemetry v2

### ISSUE THREAD

**Issue by FrimIdan** [istio/istio#28079]
**Describe the feature request**

Mixer had the ability to report log event with connection state (connection.event - open, continue, close), when moving to Telemetry v2 we lost the ability to get the connection state.
Currently Istio have access log for TCP only on Stackdriver.

The request is to be able to get TCP connection state when Telemetry v2 is on.

**Describe alternatives you've considered**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by FrimIdan** [comment]
@douglas-reid should it be closed?

**Comment by zhlsunshine** [comment]
Hi @mandarjog & @douglas-reid, shall we move this issue to 1.12? or close it?

**Comment by mandarjog** [comment]
Moved to 1.12.
