### ISSUE TITLE
Disabling CRD creation is broken

### ISSUE THREAD

**Issue by nmittler** [istio/istio#28087]
This was found in #28059

Setting `Values.base.enableCRDTemplates` seems to have no effect ... crds are installed anyway.

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by irisdingbj** [comment]
dup with https://github.com/istio/istio/issues/27609
