### ISSUE TITLE
Grafana service dashboard error: Template variables could not be initialized: Datasource named ${DS_PROMETHEUS} was not found

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#28092]
Happens when opening the service dashboard

Assign to myself to verify it happens on fresh install before marking release blocker

**Comment by howardjohn** [comment]
Happens on fresh install. cc @douglas-reid @carolynhu

**Comment by douglas-reid** [comment]
@carolynhu can you own this, as you've been looking into dashboard issues recently?

**Comment by carolynhu** [comment]
@douglas-reid yes, sure

**Comment by carolynhu** [comment]
@howardjohn I could not reproduce this error, here is the raintank: https://snapshot.raintank.io/dashboard/snapshot/Fcd154b4osooKzG6Fumcd6nqKWf2wi8U
