### ISSUE TITLE
Setting a revision generates a non-functioning hpa for deployment/istiod-<revision> 

### ISSUE THREAD

**Issue by totallyGreg** [istio/istio#28107]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
Taking a minimal profile and setting a revision=1-6-9 generates a pilot hpa that selects on Istiod instead of istiod-1-6-9 which causes it to fail to scale.  

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[X] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
If setting a revision, the hpaSpec.scaleTargetRef name should match the actual name of the deployment.  In this case 'istiod-1-6-9'

The only workaround I have found is to hand edit the hpa reference after the install.  
Setting the values in either components or values blocks fails to get propagated to the IstioOperator file when using profile dump.  Nor does it get propagated to manifests with manifest generate.  

**Steps to reproduce the bug**
```
cat operator-profiles/revision-patch.yml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  revision: 1-6-9

bin/istioctl-1.6.9 profile dump minimal > minimal-1.6.9.yml
2020-10-20T15:46:15.194255Z     info    proto: tag has too few fields: "-"
! global.mtls.auto is deprecated; use meshConfig.enableAutoMtls instead

bin/istioctl-1.6.9 profile dump -f minimal-1.6.9.yml -f revision-patch.yml > revision-test.yml

bin/istioctl-1.6.9 profile dump --config-path components.pilot.k8s.hpaSpec.scaleTargetRef -f revision-test.yml
2020-10-20T15:40:04.623003Z     info    proto: tag has too few fields: "-"
! global.mtls.auto is deprecated; use meshConfig.enableAutoMtls instead
apiVersion: apps/v1
kind: Deployment
name: istiod
```

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
```
❯ bin/istioctl-1.6.9 version
client version: 1.6.9
control plane version: 1.6.9
data plane version: 1.6.9 (630 proxies)
```
**How was Istio installed?**
`istioctl install -f revision-test.yml`

**Environment where bug was observed (cloud vendor, OS, etc)**
v1.15.10-eks-bac369

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by howardjohn** [comment]
I am a bit confused by this one - this looks correct to me?
```
$ ~/istio/istio-1.6.8/bin/istioctl manifest generate --revision 1-6-9 | k grep HorizontalPodAutoscaler/istiod-1-6-9


# IstiodRemote component is disabled.

# Resources for Pilot component

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: istiod-1-6-9
  namespace: istio-system
  labels:
    app: istiod
    release: istio
    istio.io/rev: 1-6-9
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: istiod-1-6-9
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80
```

**Comment by totallyGreg** [comment]
yeah I'm confused too...  

Revision is already in the IstioOperator definition but I specified it anyway.  

```
❯ bin/istioctl-1.6.9 manifest generate  --revision 1-6-9 -f revision-test.yml > revision-manifest.yml
! global.mtls.auto is deprecated; use meshConfig.enableAutoMtls instead

❮ ag -A23 'Pilot component' revision-manifest.yml
5291:# Resources for Pilot component
5292-
5293-apiVersion: autoscaling/v2beta1
5294-kind: HorizontalPodAutoscaler
5295-metadata:
5296-  labels:
5297-    app: istiod
5298-    istio.io/rev: 1-6-9
5299-    release: istio
5300-  name: istiod-1-6-9
5301-  namespace: istio-system
5302-spec:
5303-  maxReplicas: 5
5304-  metrics:
5305-  - resource:
5306-      name: cpu
5307-      targetAverageUtilization: 80
5308-    type: Resource
5309-  minReplicas: 1
5310-  scaleTargetRef:
5311-    apiVersion: apps/v1
5312-    kind: Deployment
5313-    name: istiod
```

**Comment by totallyGreg** [comment]
The pattern we are currently using is to generate an IstioOperator file by passing in both the base minimal.yml and the specific environment.yml to profile dump.
When profile dump is provided with 2 operator files to generate a 3rd, this resulting IstioOperator file appears to generate a components.pilot.k8s.hpaSpec block, presumably from the [Istio-discovery template] (https://github.com/istio/istio/blob/3c40ce7b9a2a48bb7395f37a5c010ba91330b169/manifests/charts/istio-control/istio-discovery/templates/autoscale.yaml#L19)
but the revision is ignored.  

Side note: we can define the min/max replicas by defining the values.pilot.autoscaleMax and these do get rendered into the IstioOperator components.pilot.k8s.hpaSpec correctly.  

It is no clear how the order of rendering is done when creating IstioOperator from the profile dump.  
It is also not clear how I can possibly override this value from an IstioOperator file, since revision is tested for in the template.  
Even generating manifests from a minimal.yml with just revision set in an operator file fails to render the HPA scaleTargetRef.name properly.  

The only workaround I can see is to edit the HPA after istioctl install has completed.

**Comment by totallyGreg** [comment]
Does adding this test make sense?  

`+++ b/operator/cmd/mesh/manifest-generate_test.go
@@ -566,6 +566,7 @@ func TestConfigSelectors(t *testing.T) {
                // First we fetch all the objects for our default install
                cname := "istiod"
                deployment := mustFindObject(t, objs, cname, name.DeploymentStr)
+               hpa := mustFindObject(t, objs, cname, name.HPAStr)
                service := mustFindObject(t, objs, cname, name.ServiceStr)
                pdb := mustFindObject(t, objs, cname, name.PDBStr)
                podLabels := mustGetLabels(t, deployment, "spec.template.metadata.labels")
@@ -573,6 +574,7 @@ func TestConfigSelectors(t *testing.T) {
                // Next we fetch all the objects for a revision install
                nameRev := "istiod-canary"
                deploymentRev := mustFindObject(t, objsRev, nameRev, name.DeploymentStr)
+               hpaRev := mustFindObject(t, objs, nameRev, name.HPAStr)
                serviceRev := mustFindObject(t, objsRev, nameRev, name.ServiceStr)
                pdbRev := mustFindObject(t, objsRev, nameRev, name.PDBStr)
                podLabelsRev := mustGetLabels(t, deploymentRev, "spec.template.metadata.labels")
@@ -583,6 +585,11 @@ func TestConfigSelectors(t *testing.T) {
                mustNotSelect(t, mustGetLabels(t, pdbRev, "spec.selector.matchLabels"), podLabels)
                mustNotSelect(t, mustGetLabels(t, pdb, "spec.selector.matchLabels"), podLabelsRev)

+               // Make sure the scaleTargetRef points to the correct Deployment
+               if hpaName := mustGetPath(t, hpaRev, "spec.scaleTargetRef.name"); revName != hpaName {
+                       t.Fatalf("HPA does not match deployment: %v != %v", revName, hpaName)
+               }
+
                // Check selection of previous versions . This only matters for in place upgrade (non revision)
                podLabels15 := map[string]string{
                        "app":   "istiod",

`

**Comment by howardjohn** [comment]
yeah absolutely the test does - surprised we did not have that already

**Comment by totallyGreg** [comment]
So I've created a test #28544 that I thought would at least indicate where this is failing.  Unfortunately it did not.
I need to understand why this `bin/istioctl-1.6.9 manifest generate  --revision 1-6-9 -f revision-test.yml > revision-manifest.yml` fails to create a valid hpa object.  So that we can stop manually patching the hpa object after an `istiotctl install`
I would appreciate any help in stepping through this.

**Comment by totallyGreg** [comment]
### TL;DR
The only way to have the correct name defined in the scaleTargetRef is to generate the manifest off a built in profile without specifying an istioOperator file with the -f flag.  

### Generating a istioOperator with both a minimal.yml and a revision-patch.yml 
The idea being to have a fixed minimal.yml definition and then apply environment specific patches on top of it.  

```shell
bin/istioctl-1.6.9 profile dump -f operator-profiles/minimal-1.6.9.yml -f operator-profiles/revision-patch.yml > revision-test.yml
```

This creates a revision-test.yml that contains the wrong scaleTargetRef.name
```shell
❯ yq r revision-test.yml -C "spec.components.pilot.k8s.hpaSpec.scaleTargetRef.name"

istiod
```

This gets propagated when manifest generate is run against the revision-test.yml istioOperator file
```shell
❯ bin/istioctl-1.6.9 manifest generate -f revision-test.yml > test-manifest.yml
❯ ag -C5 scaleTargetRef test-manifest.yml
5305-  - resource:
5306-      name: cpu
5307-      targetAverageUtilization: 80
5308-    type: Resource
5309-  minReplicas: 1
5310:  scaleTargetRef:
5311-    apiVersion: apps/v1
5312-    kind: Deployment
5313-    name: istiod
5314-
5315----
```

Even when --revision is specified.
```shell
❯ bin/istioctl-1.6.9 manifest generate --revision 1-6-9 -f revision-test.yml > test-manifest.yml
! global.mtls.auto is deprecated; use meshConfig.enableAutoMtls instead

❯ ag -C5 scaleTargetRef test-manifest.yml
5305-  - resource:
5306-      name: cpu
5307-      targetAverageUtilization: 80
5308-    type: Resource
5309-  minReplicas: 1
5310:  scaleTargetRef:
5311-    apiVersion: apps/v1
5312-    kind: Deployment
5313-    name: istiod
5314-
5315----
```


### Generating istioOperator from a single revision-patch.yml file
This contains just a definition of revision and lists the profile: minimal
```shell
❯ cat operator-profiles/revision-patch.yml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  revision: 1-6-9
  profile: minimal
  
❯ bin/istioctl-1.6.9 profile dump -f operator-profiles/revision-patch.yml > revision-test2.yml
2020-11-09T20:36:53.408024Z     info    proto: tag has too few fields: "-"
! global.mtls.auto is deprecated; use meshConfig.enableAutoMtls instead
```

Which does not contain any components.pilot.k8s.hpaSpec at all
```shell
❯ yq r revision-test2.yml -C "spec.components.pilot.k8s.hpaSpec.scaleTargetRef.name"

```

Running the manifest generate does create an hpaSpec, but with the wrong deployment name
```shell
❮ bin/istioctl-1.6.9 manifest generate -f revision-test2.yml > test2-manifest.yml
! global.mtls.auto is deprecated; use meshConfig.enableAutoMtls instead

❮ ag -C5 scaleTargetRef test2-manifest.yml
5305-  - resource:
5306-      name: cpu
5307-      targetAverageUtilization: 80
5308-    type: Resource
5309-  minReplicas: 1
5310:  scaleTargetRef:
5311-    apiVersion: apps/v1
5312-    kind: Deployment
5313-    name: istiod
5314-
5315----
```

again specifying the --revision on the cli does not generate a correct hpaSpec.
```shell
❯ bin/istioctl-1.6.9 manifest generate --revision 1-6-9 -f revision-test2.yml > test2-manifest.yml
! global.mtls.auto is deprecated; use meshConfig.enableAutoMtls instead

❮ ag -C5 scaleTargetRef test2-manifest.yml
5305-  - resource:
5306-      name: cpu
5307-      targetAverageUtilization: 80
5308-    type: Resource
5309-  minReplicas: 1
5310:  scaleTargetRef:
5311-    apiVersion: apps/v1
5312-    kind: Deployment
5313-    name: istiod
5314-
5315----
```

### Generating manifests from built in 'default' profile
It appears that the only way to actually create an hpaSpec that is properly defined, is to run `manifest generate` specifying a built in profile and NOT specifying an istioOperator file with the -f flag.  
```shell
❮ bin/istioctl-1.6.9 manifest generate --revision 1-6-9  > test3-manifest.yml

❮ ag -C5 scaleTargetRef test3-manifest.yml
5848-  - resource:
5849-      name: cpu
5850-      targetAverageUtilization: 80
5851-    type: Resource
5852-  minReplicas: 1
5853:  scaleTargetRef:
5854-    apiVersion: apps/v1
5855-    kind: Deployment
5856-    name: istio-ingressgateway
5857-
5858----
--
6187-    release: istio
6188-    istio.io/rev: 1-6-9
6189-spec:
6190-  maxReplicas: 5
6191-  minReplicas: 1
6192:  scaleTargetRef:
6193-    apiVersion: apps/v1
6194-    kind: Deployment
6195-    name: istiod-1-6-9
6196-  metrics:
6197-  - type: Resource
```

This works if setting the manifest profile to minimal as well.
```shell
❮ bin/istioctl-1.6.9 manifest generate --set profile=minimal --revision 1-6-9 > test4-manifest.yml
! global.mtls.auto is deprecated; use meshConfig.enableAutoMtls instead

❮ ag -C5 scaleTargetRef test4-manifest.yml
5300-    release: istio
5301-    istio.io/rev: 1-6-9
5302-spec:
5303-  maxReplicas: 5
5304-  minReplicas: 1
5305:  scaleTargetRef:
5306-    apiVersion: apps/v1
5307-    kind: Deployment
5308-    name: istiod-1-6-9
5309-  metrics:
5310-  - type: Resource
```

Any attempt to specify a configuration file fails.
```shell
❮ bin/istioctl-1.6.9 manifest generate --set profile=minimal --revision 1-6-9 -f revision-test.yml > test5-manifest.yml
! global.mtls.auto is deprecated; use meshConfig.enableAutoMtls instead

❮ ag -C5 scaleTargetRef test5-manifest.yml
5305-  - resource:
5306-      name: cpu
5307-      targetAverageUtilization: 80
5308-    type: Resource
5309-  minReplicas: 1
5310:  scaleTargetRef:
5311-    apiVersion: apps/v1
5312-    kind: Deployment
5313-    name: istiod
5314-
5315----
```

**Comment by a8j8i8t8** [comment]
This is still an issue with version 1.8.2.
Installed Istio operator with command `$ istioctl operator init --revision 1-8-2` and then installed `default` configuration profile as below.
```
$ kubectl create ns istio-system
$ kubectl apply -f - <<EOF
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrolplane-1-8-2
spec:
  profile: default
  revision: 1-8-2
EOF
```
HPA is still getting created for deployment `istiod` instead of `istiod-1-8-2`.

**Comment by howardjohn** [comment]
@a8j8i8t8 I did your exact steps and see
```
NAME                   REFERENCE                         TARGETS         MINPODS   MAXPODS   REPLICAS   AGE
istio-ingressgateway   Deployment/istio-ingressgateway   <unknown>/80%   1         5         1          21s
istiod-1-8-2           Deployment/istiod-1-8-2           <unknown>/80%   1         5         1          25s

```

which looks correct

@totallyGreg it is because your `profile dump` command does not contain the revision, so it ends up outputting configs:
```
    policy:
      enabled: false
      k8s:
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        hpaSpec:
          maxReplicas: 5
          metrics:
          - resource:
              name: cpu
              targetAverageUtilization: 80
            type: Resource
          minReplicas: 1
          scaleTargetRef:
            apiVersion: apps/v1
            kind: Deployment
            name: istio-policy
        strategy:
          rollingUpdate:
            maxSurge: 100%
            maxUnavailable: 25%

```

which is *explicitly* setting the HPA, causing the revision flag to not fully take effect.

in istioctl 1.9, this is no longer occur. Since 1.6, where this bug occurs, is no longer supported (https://istio.io/latest/news/support/announcing-1.6-eol-final/) unfortunately we would not backport a change. Please let us know if I reproduced this incorrectly and there are still issues in 1.9. Thanks!!
