### ISSUE TITLE
Different defaults for includeInboundPorts when using CNI vs init container

### ISSUE THREAD

**Issue by luksa** [istio/istio#28104]
**Bug description**
The injection template uses different default values for `traffic.sidecar.istio.io/includeInboundPorts`, depending on whether CNI or the init container is used.

When you use CNI and you don't specify the `traffic.sidecar.istio.io/includeInboundPorts` annotation on your pod, the annotation defaults to the list of ports specified in the pod's container definitions (see [injection template](https://github.com/istio/istio/blob/0230320bfcc06bff4b704c5df6132808d2513379/manifests/charts/istio-control/istio-discovery/files/injection-template.yaml#L30)). When you use the init container, the `istio-iptables` command runs with the option `-b '*'` (see [injection template](https://github.com/istio/istio/blob/0230320bfcc06bff4b704c5df6132808d2513379/manifests/charts/istio-control/istio-discovery/files/injection-template.yaml#L447)). 

This produces a different set of iptables rules. With CNI, only the ports that are explicitly specified in the pod definition are forwarded to the proxy, whereas with the init container, all are. The end result is that when you use CNI, authz policies only work on ports that are explicitly defined in the pod. 

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Iptables rules should be identical, whether you use the init container or CNI.

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
master

**Comment by anastasiagrinman** [comment]
I can confirm that on tag version 1.12.2, this annotation doesn't get override values from values.yaml but uses "*" when cni_enabled.
