### ISSUE TITLE
Base images - build without cache

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#28117]
We need to add `--no-cache` or equivilent to the base iamge builder, or we may not update everything
cc @ericvn

**Comment by ericvn** [comment]
Agree. A `docker system prune` before hand should clear the cache as well.

**Comment by ericvn** [comment]
Did do some playing with this yesterday and need to do some more investigation. I tried using --no-cache and I'm not sure that everything was

**Comment by howardjohn** [comment]
I have used the --no-cache successfully in the past. are you saying it wasn't working?

We need to make it work with the buildx as well, not sure if that takes that exact flag or needs it in the config file. we can then add the env var to tools/build-base-images.sh

**Comment by ericvn** [comment]
The same flag is accepted on the docker buildx.

**Comment by ericvn** [comment]
Do we also want to specify --pull so we always try to pull a newer version of the images as well?

--no-cache Do not use cache when building the image
--pull           Always attempt to pull a newer version of the image

**Comment by howardjohn** [comment]
I don't know what the difference is. quick search from https://pythonspeed.com/articles/docker-cache-insecure-images/#:~:text=Disabling%20caching&text=%2D%2Dpull%20%3A%20This%20pulls%20the,relying%20on%20the%20layer%20cache suggests both but without explaination
