### ISSUE TITLE
Add local validation for release notes

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#28124]
I would like to be able to run:
```
$ make lint-releasenotes
... some error
```

and quickly check release notes before submitting a PR

cc @brian-avery

**Comment by brian-avery** [comment]
@sdake you were working on something in this area right?

**Comment by sdake** [comment]
right @brian-avery - got distracted. All of the base PRs are in - just need a make target. Will produce one now.

**Comment by brian-avery** [comment]
@sdake was this done?

**Comment by sdake** [comment]
@brian-avery - been distracted...

I will work on the makefile change this week. Everything else (should) be ready to go.

My apologies.

Cheers,
-steve

**Comment by brian-avery** [comment]
Expanding on this issue:

schema-validator will validate that notes match the schema -- all required fields are filled out, area matches, etc. Currently, some additional validation is done by the release notes tooling -- validation of issue & docs fields, but this should be able to be added to the schema using regex.

**Comment by zhlsunshine** [comment]
Hi @sdake & @brian-avery, shall we move this issue to 1.12?
