### ISSUE TITLE
Testing: Changing Version in Echo Config doesn't work

### ISSUE THREAD

**Issue by gargnupur** [istio/istio#28158]
**Bug description**

Adding version in Echo Config doesn't really work. It still gets deployed as default V1 version.
Ex: 
echo.Config{
 Service:   "clt",
 Version: "v2"
       }

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ X] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by nmnellis** [comment]
From the test examples and the deployment, i believe you have to use subset versions
```json
				Subsets: []echo.SubsetConfig{
					{
						Version: "v-istio",
					},
					{
						Version:     "v-legacy",
						Annotations: echo.NewAnnotations().SetBool(echo.SidecarInject, false),
					},
				},
```
https://github.com/istio/istio/blob/master/pkg/test/framework/components/echo/kube/deployment.go#L81
