### ISSUE TITLE
gateways.networking.istio.io and gateways.networking.x-k8s.io conflicts

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#28188]
Both crds have accepted name `gateway`. I tried to get istio gateway by `kubectl get gateway` we could get nothing.  I think the service apis' gateways.networking.x-k8s.io takes precedence in my cluster.  

It is confusing for newbie.  

@howardjohn

**Comment by howardjohn** [comment]
Yes, they may change the name. You can do `get gw` by the way.

I opened an issue in k8s to print a warning when there is a conflict

**Comment by howardjohn** [comment]
https://github.com/kubernetes/kubernetes/issues/94860
