### ISSUE TITLE
 Pilot oom maybe caused by connection error

### ISSUE THREAD

**Issue by ydh926** [istio/istio#28183]
**Bug description**

[ ] Docs
[ ] Installation
[ ] Networking
[x ] Performance and Scalabilitxy
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

Not sure how to reproduce the bug. The pilot log before oom killed is 
![image](https://user-images.githubusercontent.com/43948155/96820939-8e7af600-1459-11eb-8560-047340d9bc0c.png)

This state lasted for about 2 hours until it  was killed by oom.  During that, pilot's memory monitoring is as follow：

![image](https://user-images.githubusercontent.com/43948155/96820384-79519780-1458-11eb-8eeb-0e574fcc98c7.png)

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
istio 1.3

**Environment where bug was observed (cloud vendor, OS, etc)**
K8S 1.13

**Comment by howardjohn** [comment]
I think the only way we will be able to debug this is with a profile - see https://github.com/istio/istio/wiki/Analyzing-Istio-Performance

**Comment by howardjohn** [comment]
Also please be aware Istio 1.3 is unsupported and it's extremely likely whatever is causing this leak has already been fixed

**Comment by ydh926** [comment]
Since the pilot has been oomkilled, there is no way to get the heap profile. If the bug can be reproduced, I will provide more information.

**Comment by howardjohn** [comment]
@ydh926 I sstrongly suspect this is fixed in modern Istio versions by 25579. If you see this issue on supported versions please re-open with a heap dump. Thanks!!
