### ISSUE TITLE
remove-from-mesh should skip system namespace

### ISSUE THREAD

**Issue by shamsher31** [istio/istio#28186]
Maybe bug with https://github.com/istio/istio/pull/21107 because for the first time it says.
```
$ istioctl x remove-from-mesh deployement local-path-provisioner -n local-path-storage
deployment "local-path-provisioner.local-path-storage" updated successfully with Istio sidecar un-injected.
```

Should say `no Istio sidecar injected` or skip system namespace to remove sidecar injector.

If you run the above command for the second time it works. May be because of https://github.com/istio/istio/issues/20998#issuecomment-584367775
```
$ istioctl x remove-from-mesh deployement local-path-provisioner -n local-path-storage
deployment "local-path-provisioner.local-path-storage" has no Istio sidecar injected. Skipping.
```

Based on https://github.com/istio/istio/issues/25860#issuecomment-664089111
 Probably It should also skip `istio-system` namespace to avoid human error eg: https://github.com/istio/istio/issues/25860
```
$ istioctl experimental remove-from-mesh deployment istio-egressgateway  -n istio-system
Error: 1 error occurred:
	* failed to update deployment "istio-egressgateway.istio-system" for service "istio-egressgateway.istio-system" due to Deployment.apps "istio-egressgateway" is invalid: spec.template.spec.containers: Required value

```

**Comment by esnible** [comment]
I tried to do something similar.  (Although John approved my PR, there was no one in UX with time to look at it so it went stale.)

Would it make sense to use the technique of https://github.com/istio/istio/pull/25887 rather than checking namespaces?  Or do both?

**Comment by shamsher31** [comment]
There a similar PR https://github.com/istio/istio/pull/27543 which I reviewed today and ask to refer your stale PR because that looks good to me.

> Would it make sense to use the technique of #25887 rather than checking namespaces? Or do both?

I think we should keep both to avoid confusion like https://github.com/istio/istio/issues/25860 in future.
