### ISSUE TITLE
Feature: get full config dump from istioctl

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#28191]
Right now you can only get partial dumps. For adding to an issue or other usages it would be useful to get the full unmodified config dump from envoy

**Comment by dntosas** [comment]
@howardjohn are you looking to assign this to someone? maybe i can give it a try ^^

**Comment by howardjohn** [comment]
That would be great! I would recommend we have at minimum json output (can just directly pass from envoy without parsing), but could be useful to also do the equivilent of `istioctl pc {secret,listener,cluster,eendpoint,route}`

similar to
```
$ k get pods,deployments
NAME                        READY   STATUS    RESTARTS   AGE
pod/shell-788c87846-jhrpx   2/2     Running   0          4m8s

NAME                    READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/shell   1/1     1            1           4m8s
```

**Comment by esnible** [comment]
I am happy to implement this immediately.

To clarify, you are suggesting that `istioctl pc` accept `all` and `<type>[,<type>]` instead of just `<type>`.

Do you expect to mostly use this for the `short` output format (the default), or do you expect to use this with `-o json` and expect the output to have the structure of an Envoy config_dump?

**Comment by howardjohn** [comment]
All of the above! I think short and json can both work and are both useful. For json, I think we could just directly pass the envoy response untouched

**Comment by kyessenov** [comment]
Envoy does not have full coverage of types in config_dump. Probably requires work there to support Wasm, for example.

**Comment by esnible** [comment]
FYI: Motivating example: https://github.com/istio/istio.io/issues/7613#issuecomment-766878849

It would have been much nicer to be able to do `istioctl pc all` when capturing before and after Envoy config.
