### ISSUE TITLE
Allow setting of STRICT mtls for the mesh by Operator

### ISSUE THREAD

**Issue by rtmie** [istio/istio#28190]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
In the helm deploy model for Istio up to 1.4 it was possible to configure the Mesh to work in mTLS only.
In 1.3/1.4 this was driven by the security helm chart and this template https://github.com/istio/istio/blob/release-1.4/install/kubernetes/helm/istio/charts/security/templates/enable-mesh-mtls.yaml

For newer versions the MeshPolicy created in the above template is now obsolete. Now to enforce MTLS the method is  to create  a PeerAuthentication called `default` in the `istio-system` namespace with tls mode set to STRICT

However the ability to configure this during deployment is gone.

I would like (in order to maintain the experience from pre operator) to have a value setting in the control plane profile to set mtls and have the operator create the PeerAuthentication in response

**Describe alternatives you've considered**
Post install the required PeerAuthentication resource. However this needs a separate process step when k8s cluster/istio is being deployed by an automated process.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
This is working as intended, see https://github.com/istio/istio/issues/22095 for some more background.

Is there any reason why you want this to be tied to the install rather than configured by a dedicated resource (just like all of the networking rules, etc)?

**Comment by rtmie** [comment]
Specifically because this config enforces mtls in the mesh. In effect this was the default we used before switch to the operator.
When we install with the operator we lost this default behaviour. There are some edge cases where AutoMTLS gets bypassed for TCP headless services when PeerAuthentication is not set to strict. So in effect from my POV the basic out of the box behaviour has changed. 
ref https://github.com/istio/istio/blob/release-1.7/pilot/pkg/networking/core/v1alpha3/cluster.go#L450

**Comment by howardjohn** [comment]
The expectation is if you want strict MTLS to configure a https://istio.io/latest/docs/reference/config/security/peer_authentication/#PeerAuthentication resource, not to rely on auto mtls. Its still not clear to me why its expected the operator will create this, when the user is still expected to create DestinationRules, virtual service, gateway, sidecar, etc resources. What is the benefit of having the operator manage this?

**Comment by rtmie** [comment]
Happy to accept your answer. I guess my expectation was no change of default behavior of the mesh at install time. On transitioning from 1.4 to 1.7 we had a behaviour change which was not immediatley obvious.
