### ISSUE TITLE
Create Istio twitter account.

### ISSUE THREAD

**Issue by geeknoid** [istio/istio#282]
Once the account is created, we should not it in istio.io's community page, the istio.io footer, and in the 0.1 blog announcement.

Please assign this issue to me once the account is created, and I'll make the web site changes.

**Comment by zinuga** [comment]
Can use this
https://twitter.com/istio2

**Comment by geeknoid** [comment]
Aww, istio without a 2 was taken?

**Comment by zinuga** [comment]
yes istio is taken. Thanks to @josephjacks, I managed to get istiomesh which is better than istio2.
Sorry but can we switch to this
https://twitter.com/IstioMesh

**Comment by geeknoid** [comment]
All right, I'll switch reference over. DId you delete istio2 to avoid
confusion?

**Comment by ldemailly** [comment]
https://twitter.com/Istio2 is still here
