### ISSUE TITLE
Upgrading Istio version leads to misleading log line

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#28208]
```
! Istio control planes installed: 1.7.0.
! Use --revision or --force to install Istio.
✔ Istio core installed
✔ Istiod installed
✔ Ingress gateways installed
✔ Installation complete 
```

I did not need to set force or revision and it worked fine. I also don't think the warning is clear for users

**Comment by bianpengyuan** [comment]
I marked this as a P0, @ostromart @therealmitchconnors please help to triage this, thanks!

**Comment by bianpengyuan** [comment]
@therealmitchconnors tentatively assign this to you.

**Comment by ostromart** [comment]
@shamsher31 I assume this is due to the installed version check? I agree the message is unclear, it should say something like "An older installed version of Istio has been detected. Running this command will overwrite it.". And of course we need a prompt (prefer) or flag to proceed.

**Comment by shamsher31** [comment]
> @shamsher31 I assume this is due to the installed version check? 

Yes.

> I agree the message is unclear, it should say something like "An older installed version of Istio has been detected. Running this command will overwrite it.". 

@ostromart I'm fine with updating the message as you suggested. These messages are as per the suggestion from @esnible https://github.com/istio/istio/pull/24263#issuecomment-707629340

> And of course we need a prompt (prefer) or flag to proceed.

The prompt is still there to ask the user to take action based on message.
