### ISSUE TITLE
namespace controller causes OOM

### ISSUE THREAD

**Issue by l8huang** [istio/istio#28204]
**Bug description**

NamespaceController uses task queue to create ConfigMap istio-ca-root-cert in namespaces, when a namespace doesn't have resource quota to create it, the task will fail and be pushed back into the queue. The status error is:

```
(dlv) p err
error(*k8s.io/apimachinery/pkg/api/errors.StatusError) *{
	ErrStatus: k8s.io/apimachinery/pkg/apis/meta/v1.Status {
		TypeMeta: (*"k8s.io/apimachinery/pkg/apis/meta/v1.TypeMeta")(0xc00098ae60),
		ListMeta: (*"k8s.io/apimachinery/pkg/apis/meta/v1.ListMeta")(0xc00098ae80),
		Status: "Failure",
		Message: "configmaps \"istio-ca-root-cert\" is forbidden: exceeded quota: ob...+79 more",
		Reason: "Forbidden",
		Details: *(*"k8s.io/apimachinery/pkg/apis/meta/v1.StatusDetails")(0xc00136ff80),
		Code: 403,},}
```

Related log:

```
2020-10-18T20:21:56.058605Z	info	Work item handle failed (error when creating configmap istio-ca-root-cert: configmaps "istio-ca-root-cert" is forbidden: exceeded quota: object-counts, requested: configmaps=1, used: configmaps=0, limited: configmaps=0), retry after delay 1s
```

Also, because namespace informer does resync, more configmap creation tasks will be created, and the failed ones will be accumulated on task queue, this causes istiod's memory usage keeps growing until being OOM killed.

Our k8s cluster has 9,000 namespaces, istiod's memory usage could exceed 50G in one week.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[X] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
If config creation failed because reasons like `exceeded quota`, it shouldn't be retried, namespace informer can take care of it with next resync.

**Steps to reproduce the bug**
- stop istiod
- Create thousands of namespaces, set config map's resource quota to 0
- start istiod

**Version **
1.6.5

**Comment by hzxuzhonghu** [comment]
I think this is a scenario we do not consider before. Let me check whether resync is disabled in recent branch

**Comment by hzxuzhonghu** [comment]
IIRC in 1.7 we have no resync for namespace informer.  @howardjohn Do we need to fix it for 1.6?

**Comment by l8huang** [comment]
IMHO it's necessary to add a check to determine if a change should be retried. Looks like there already have such checks(https://github.com/istio/istio/blob/master/security/pkg/util/configutil.go#L45-L48), but looks like that's not sufficient.

I guess request should only be retried for below reasons:

```
metav1.StatusReasonServerTimeout:
metav1.StatusReasonTimeout
metav1.StatusReasonTooManyRequests
metav1.StatusReasonServiceUnavailable
```

Also max retry times should be given. If a request can't retry or exceeds max retry times, the task shouldn't be enqueued anymore. 

But, considering resync is disabled, and configmap informer doesn't filter config may by label anymore(see https://github.com/istio/istio/blob/release-1.6/pilot/pkg/serviceregistry/kube/controller/namespacecontroller.go#L74, release-1.7 checks configmap's name instead), if task failed to retry, will it cause some other issues?  Please kindly correct me if I misunderstand anything.

**Comment by hzxuzhonghu** [comment]
```
metav1.StatusReasonServerTimeout:
metav1.StatusReasonTimeout
metav1.StatusReasonTooManyRequests
metav1.StatusReasonServiceUnavailable
```
I donot think this is enough, there are many error types from k8s: https://github.com/kubernetes/kubernetes/blob/16e18a590f32b931cdceb5372664198c0e49831a/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/types.go#L708-L852

> if task failed to retry, will it cause some other issues? 

Nope, when it fails, we still put it back to the queue. 

>Also max retry times should be given. If a request can't retry or exceeds max retry times, the task shouldn't be enqueued anymore.

Then this is a permanent error, we have no way to notify that this namespace is unavailable.
