### ISSUE TITLE
Stackdriver metrics reported incorrectly when service is not running on Google infrastructure

### ISSUE THREAD

**Issue by jacob-delgado** [istio/istio#28200]
**Bug description**

When running `TestStackdriverMonitoring` as part of the `integ-telemetry` integration test on non-Google infrastructure (I've run this on `kind` on my mac as well as a k8s cluster running on Amazon, not AKS) fails due to invalid metrics reported for stackdriver.

After working with @gargnupur we figured that the metrics being reported were missing `resource.labels` and had a resource type of `gce_instance` for both server and client metrics.

This test started to fail in 1.6.9 due to extra validation done at https://github.com/istio/istio/pull/25864/files#diff-ba9a10a081a046f31c0d1fabf198ce73bb7422e29306a24695abb62b218548c1R27

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

Stackdriver metrics are reported correctly on non-Google kubernetes infrastructure

For clients, this would be

```json
    "resource": {
       "labels": {
          "namespace_name": "NAMESPACE"
       },
       "type": "k8s_pod"
    }
```

and for servers it would be

```json
    "resource": {
       "labels": {
          "container_name": "app",
          "namespace_name": "{{ .EchoNamespace }}"
       },
       "type": "k8s_container"
    }
```

instead of 

```json
    "resource": {
       "type": "gce_instance"
    }
```

for both.

This may be due to a logic issue at https://github.com/istio/proxy/blob/release-1.6/extensions/stackdriver/metric/registry.cc#L150

**Steps to reproduce the bug**

1. Setup a kubernetes cluster not running on Google infrastrcture (laptop or other provider)
2. Run `go test -p 1 -v ./tests/integration/telemetry/stackdriver/... -run TestStackdriverMonitoring -timeout 30m \
--istio.test.env kube \
 --istio.test.ci --istio.test.pullpolicy=Always --istio.test.kube.minikube --istio.test.work_dir=logs/artifacts --istio.test.hub=istio --istio.test.tag=1.6.12 --istio.test.kube.config=<KUBECONFIG> --istio.test.select=-postsubmit,-flaky,-multicluster`

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

**How was Istio installed?**

Go integration tests were running

**Environment where bug was observed (cloud vendor, OS, etc)**

- kind 0.7.0 that installed a k8s 1.18.0 cluster
- a kubernetes cluster on AWS provisioned with kops

[istio-dump.tar.gz](https://github.com/istio/istio/files/5425052/istio-dump.tar.gz)

**Comment by jacob-delgado** [comment]
cc @douglas-reid @mandarjog @gargnupur

**Comment by gargnupur** [comment]
Adding to details..when running on k8s cluster running on Amazon, PLATFORM_METADATA is as follows:
"PLATFORM_METADATA": {
       "aws_instance_id": "i-00009785316a301ef",
       "aws_account_id": "715707337212",
       "aws_availability_zone": "us-west-2b",
       "aws_region": "us-west-2"
      },

@douglas-reid , @bianpengyuan : We probably need to support above in the stackdriver filter?

**Comment by nrjpoddar** [comment]
This bug caused us quite a bit of grief as we weren't able to pin point why it fails on our prow instance but not for Istio CI. Thanks @gargnupur & others for helping @jacob-delgado to get down to the root cause!

**Comment by bianpengyuan** [comment]
@jacob-delgado Thanks for digging this up! I think we can do something in the test to distinguish the platform to only verify monitored resource when test runs on google infra. Will work on a pr for this.
