### ISSUE TITLE
User cannot send request to endpoint of service in mesh.

### ISSUE THREAD

**Issue by tdnhduc** [istio/istio#28221]
**Bug description**
When user access to website, some apis from front-end can redirect to end point(Service A) in mesh. But some api(a little) cannot send to end point(Service B). I have checked log of proxy but not seen anything. I wonder where is the request had been rejected by Istio? 

[ ] Docs
[ X] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
istio version : 1.6.8
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"xxx", GitTreeState:"clean", BuildDate:"2020-10-14T18:43:01Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"xxx", GitTreeState:"clean", BuildDate:"2019-12-11T12:34:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
**How was Istio installed?**
follow get started on web page
**Environment where bug was observed (cloud vendor, OS, etc)**
AWS

**Comment by howardjohn** [comment]
@ducoppa we need more info about how you installed, what yo deployed, what is failing, etc in order to help. Please see https://github.com/istio/istio/wiki/Troubleshooting-Istio
