### ISSUE TITLE
networking: set destination ip in 0.0.0.0:80 outbound listener 

### ISSUE THREAD

**Issue by lambdai** [istio/istio#28239]
Background: istio aggregate multiple outbound vip1:80, vip2:80 into 0.0.0.0:80 so that these share the same http route table.

The drawback is this 0.0.0.0:80 listener implicitly capture outbound traffic on unknown ips, including endpoint ips, and headless ips in the past.

We should revisit this given 

the route config is maintained as 1 instance even multiple HCM refers to the same route resource.

filterchains are drained individually.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
One thing I am worried about is people that have come to depend on this behavior.

**Comment by howardjohn** [comment]
For example - https://github.com/istio/istio/issues/23494#issuecomment-715166559

**Comment by lambdai** [comment]
That's undefined behavior...

**Comment by howardjohn** [comment]
Strong example of www.hyrumslaw.com here I think
