### ISSUE TITLE
Profiling not working on latest proxy

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#28233]
`The current build does not support heap profiler` using proxyv2:latest image

possibly from
```
commit 4c0d2d2a36996f2ec7d00b519ea90068629a2c55
Author: Dmitry Rozhkov <dmitry.rojkov@gmail.com>
Date:   Wed Oct 7 20:32:22 2020 +0300

    memory: switch to the latest tcmalloc for x86_64 builds (#13251)
```
We probably need to adjust how proxy is build

**Comment by lambdai** [comment]
Reverting to gperftcmalloc to unblock release

Future plan here #28250

**Comment by howardjohn** [comment]
I also could not do cpu profile, not sure if that is the same root cause?

**Comment by lambdai** [comment]
Yes. The profiler is gperftools functionability

See
https://github.com/google/tcmalloc/issues/2#issuecomment-587161590
