### ISSUE TITLE
Multi Control Plane provision failed

### ISSUE THREAD

**Issue by ruigulala** [istio/istio#28236]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
We're provisioning multiple Istiods with different revisions. The provision process failed with the following error.
```
Failed to write secret to CA (error: secrets "istio-ca-secret" already exists). Abort.
failed to create discovery service: failed to create CA: failed to create a self-signed istiod CA: failed to create CA due to secret write error
```

**Affected product area (please put an X in all that apply)**

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[X] Multi Control Plane

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by costinm** [comment]
This probably affects single revision too - it seems to be a race condition when 2 instances create the secret.

Citadel should not crash/exit istiod, but just retry reading the secret that was created by the other instance and continue, should be a very simple change.,

**Comment by myidpt** [comment]
Lei, can you help on this? Thanks.

**Comment by lei-tang** [comment]
@ruigulala Can you share detailed steps to reproduce the failure?

**Comment by ruigulala** [comment]
> @ruigulala Can you share detailed steps to reproduce the failure?

This is a race condition that happened really rarely during our test. So we don't have a reliable way of reproducing this.

As mentioned in https://github.com/istio/istio/issues/28236#issuecomment-715550916, this happened when we try to provision multiple Istiods. So I guess a simple check in the following place would be suffice?

https://github.com/istio/istio/blob/master/security/pkg/pki/ca/ca.go#L162

**Comment by lei-tang** [comment]
https://github.com/istio/istio/pull/29418
