### ISSUE TITLE
Clean up metadata exchange keys

### ISSUE THREAD

**Issue by bianpengyuan** [istio/istio#28245]
As of 1.8 istio proxy has been starting to exchange node info proto message instead of items specified in exchange keys. https://github.com/istio/istio/blob/d5893dc37b2c1ab9d05d839173017b35990c8e92/pkg/bootstrap/config.go#L453
However there is a way to add additional keys for exchanging. We'd need to decide if we want to keep this ability (which need proxy change) or cleaned it up from pilot-agent.

cc @lizan @kyessenov

**Comment by kyessenov** [comment]
Ability has been removed (it wasn't really used by our extensions before anyways).

**Comment by bianpengyuan** [comment]
Yeah I believe @lizan  or tetrate user uses them in access logging?

**Comment by kyessenov** [comment]
It was a private implementation detail. We discussed with folks here and @douglas-reid and @gargnupur whether it's safe. We don't intend MX to be a general mechanism to pass data.

**Comment by lizan** [comment]
@hanahmily do you have concern about this?
