### ISSUE TITLE
When a node has multiple IPs, `Istio Proxy` should bind `inbound` listeners to the first address in the list

### ISSUE THREAD

**Issue by yskopets** [istio/istio#28269]
**Bug description**

When a node has multiple IPs, `Istio Proxy` binds `inbound` listeners to the last applicable address in the list, such as a Docker bridge address, rather than an externally accessible one 

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[X] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

`Inbound` listeners of an `Istio Proxy` with multiple IP addresses should bind to the 1st applicable IP address in the list

E.g.,
* if an `Istio Proxy` has `INSTANCE_IPS=10.128.0.51,fe80::4001:aff:fe80:33,172.17.0.1`
* then `inbound` listeners should bind to `10.128.0.51` (expected behaviour) rather than `172.17.0.1` (current behaviour)

**Steps to reproduce the bug**

* Add a VM with multiple IPs (1 physical, 1 Docker bridge, etc) to the mesh
* Create a `WorkloadEntry` resource with `Address` field set to the externally accessible address (e.g., `10.0.0.1`)
* Start `Istio Proxy` on that VM

`Inbound` listeners will bind to the IP address of the Docker bridge (e.g., `172.17.0.2`)

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

* `1.7.3`
* `1.8.0-alpha.0`

**How was Istio installed?**

`istioctl install`

**Environment where bug was observed (cloud vendor, OS, etc)**

`GKE`

**Comment by howardjohn** [comment]
Fixed by https://github.com/istio/istio/pull/28260
