### ISSUE TITLE
Use SidecarSet to manage mesh Sidecar

### ISSUE THREAD

**Issue by zyfjeff** [istio/istio#28265]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

The current way that istio is injecting Sidecar through webhook is to bind the APP life cycle to the life cycle of the mesh sidecar, and sidecar upgrades require APP restarts. Is it possible for ISTIO to manage sidecar through [Sidecarset](https://openkruise.io/en-us/docs/sidecarset.html)? Sidecarset provides in-place upgrade capability for the sidecar, and Sidecarset also has rolling upgrade capability. The mesh Sidecar can be better managed by Sidecarset.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[x] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[] Test and Release
[x] User Experience
[x] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

ref:
1. https://openkruise.io/en-us/docs/sidecarset.html
2. https://istio.io/latest/docs/setup/upgrade/

**Comment by howardjohn** [comment]
I don't think modifying the image of a running pod (which is what this does, as far as I can tell), is a good idea. It will result in downtime and we need to change more than just the image for upgrades

**Comment by hzxuzhonghu** [comment]
I doubt how native k8s can support sidecarset in place upgrade

**Comment by howardjohn** [comment]
Kubernetes allows patching a containers image, which I am pretty sure is what the sidecarset is doing

**Comment by hzxuzhonghu** [comment]
Thanks for that info

**Comment by zyfjeff** [comment]
@howardjohn @hzxuzhonghu 
You may have misunderstood the implementation principle of the Sidecarset. The Sidecarset combined with the hot upgrade envoy makes the service available throughout the upgrade process.

![image](https://user-images.githubusercontent.com/8816403/97255992-e3997c00-184c-11eb-9d66-1257af6b6fc1.png)

It is not complicated to implement. We have implemented it in Alibaba. We need to let the old pilot-agent pass the epoch to the new pilot-agent and then complete the upgrade of the Envoy with the help of the hot upgrade of the envoy.

**Comment by howardjohn** [comment]
I see, two containers. Makes sense. can you only modify the container image though, nothing else?

**Comment by zyfjeff** [comment]
@howardjohn 
Upgrading can be accomplished by setting a new sidecar image ID, and the process of upgrading can be controlled, such as the number of upgrades

**Comment by zyfjeff** [comment]
@howardjohn Both Webhook and SidecarSet are supported to manage mesh sidecar. For users, Sidecarset is not directly exposed, and the usage is the same as that of Webhook. I'd love to do that, do you have any suggestions?
