### ISSUE TITLE
Support blue/green upgrade of ingress gateway.

### ISSUE THREAD

**Issue by 78188869** [istio/istio#28270]
**Describe the feature request**
![image](https://user-images.githubusercontent.com/14146450/97159213-7edf1280-17b5-11eb-97f7-12b0225a4e4e.png)
Right now, Istio operator support in-place upgrade. 

The ingress gateway is a very critical component. It is the entrance of our service. 
I hope to deploy ingress gateway with different revision in the same time. Then, I can verify the gateway before switching traffic by modifying the service selector to new revision.

**Describe alternatives you've considered**
Add the revision into the name of ingress gateway deployment.
For example:
istio-ingressgateway-canary

I hope there could be a feature like:

add  `inplaceUpgrade: false` to GatewaySpec of IstioOperator

Then, the name of deployment should contain revision name.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by shamsher31** [comment]
@78188869 I think this will help.

> Managing Gateways with Multiple Revisions

https://preliminary.istio.io/latest/docs/setup/upgrade/gateways/

**Comment by howardjohn** [comment]
I think solved by ^
