### ISSUE TITLE
feat(dashboard): switch to use canonical services in grafana dashboards

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio#28288]
**Describe the feature request**

Orient grafana dashboards around canonical service.  This should include:

- [x] Mesh dashboard updates to aggregate at the canonical service level (including the service tables)  
- [x] A new canonical service dash that shows service-to-service traffic (distinct from workload to service traffic)

**Describe alternatives you've considered**

N/A

**Affected product area (please put an X in all that apply)**

[ X ] Extensions and Telemetry
[ X ] User Experience

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by carolynhu** [comment]
One more item TODO: Adding a dashboard should also update release-builder: https://github.com/ericvn/release-builder/blob/0828d57ef0272bcd7d66f50e1cac38acc9d37ce3/test/publish.sh#L72

**Comment by carolynhu** [comment]
Design doc: https://docs.google.com/document/d/1fViMSQCaB8rFkqKgPgMCVyYgSgRI8Ovaw5Xbjfmall0/edit#
