### ISSUE TITLE
Ingress proxy memory usage possible regression for 1.7.4

### ISSUE THREAD

**Issue by richardwxn** [istio/istio#28287]
In the release qualification test, found out that the ingress proxy memory usage has gone up to around 240M from 130M after upgrading to 1.7.4 from 1.7.3, but the memory usage increase is normal overtime, no apparent leak observed. And didn't see similar regression on the workload proxies. Check the below links for accessing prometheus/grafana running on the clusters for more details.

[prometheus_on_1.7.4](http://prom.release-qual-17.qualistio.org/graph?g0.range_input=2d&g0.expr=container_memory_working_set_bytes%7Bcontainer%3D%22istio-proxy%22%2Cnamespace%3D%22istio-system%22%7D&g0.tab=0&g1.range_input=2d&g1.expr=envoy_server_memory_physical_size%7Bnamespace%3D%22istio-system%22%7D&g1.tab=0)

[grafana_on_1.7.4](http://grafana.release-qual-17.qualistio.org/)

As comparison: [prometheus_on_master](http://prom.release-qual.qualistio.org/graph?g0.range_input=2d&g0.expr=container_memory_working_set_bytes%7Bcontainer%3D%22istio-proxy%22%2Cnamespace%3D%22istio-system%22%7D&g0.tab=0)

**Comment by howardjohn** [comment]
heap size goes up, but alloc goers down: http://prom.release-qual-17.qualistio.org/graph?g0.range_input=2d&g0.expr=container_memory_working_set_bytes%7Bcontainer%3D%22istio-proxy%22%2Cnamespace%3D%22istio-system%22%7D&g0.tab=0&g1.range_input=2d&g1.expr=envoy_server_memory_allocated%7Bnamespace%3D%22istio-system%22%7D&g1.tab=0&g2.range_input=2d&g2.expr=envoy_server_memory_heap_size%7Bnamespace%3D%22istio-system%22%7D&g2.tab=0

@lambdai does this version have the heap compacting?

**Comment by richardwxn** [comment]
checking the same test with 1.7.4 on another cluster: oss17-stable-iamwen in the mixologist project and did not see similar result as here so far, would continue monitor these clusters.

**Comment by lambdai** [comment]
heap size ~= 1.5x allocated
It is not too bad.
The compaction cannot squeeze `heap size`  to `allocated` due to fragments and cache. Cache is the "C" in tCmalloc)

**Comment by jwendell** [comment]
so, what's the decision? 1.7.4 is good to go?

**Comment by richardwxn** [comment]
Did more investigation with @lambdai with profiling and running more tests on other clusters but didn't see similar situation. Ingress mem usage on another 1.7 cluster and master cluster is normal. Another observation is that the memory usage value is really unstable in this cluster and seems not related to QPS size as well(adjusted the QPS or even created some random 500 errors but mem size didn't change accordingly). So in summary I think it is more like a special case but I will continue to investigate. 

Therefore for 1.7.4, @jwendell @JimmyCYJ @Mythra I think it is good to go.

**Comment by jwendell** [comment]
Awesome, thanks!

**Comment by Stono** [comment]
Possibly related: https://github.com/istio/istio/issues/28652
