### ISSUE TITLE
Shared control plane multiple networks without loadblance

### ISSUE THREAD

**Issue by yanickxia** [istio/istio#28309]
**Describe the feature request**
try install cluster in my test env, try everything but i can't make it works, i think that we should add doc for `Shared control plane multiple networks without loadblance`

**Describe alternatives you've considered**
help someone without loadblance

[ X ] Docs
[ X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by Laurianti** [comment]
I tried it:

https://github.com/istio/istio/issues/28903

I think the last step is missing.
