### ISSUE TITLE
provide support for dynamically serving SSL certificates using SNI at istio-ingress

### ISSUE THREAD

**Issue by achilles-git** [istio/istio#28313]
**Describe the feature request**
please provide the support for dynamically serving SSL certificates using SSL.
e.g: for two sites abc.com and xyz.com using istio we can server certificates like this
```apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: mygateway
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: abc-credential # this is a secret which has certificate for abc.com site
    hosts:
    - abc.com
    tls:
      mode: SIMPLE
      credentialName: xyz-credential # this is a secret which has certificate for xyz.com site
    hosts:
    - xyz.com
```
above method is not scalable if you have more than 100 or 1000 sites.
something like below in which istio will find the correct one by checking for a matching common name or subject alternative name would be helpful.
```apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: mygateway
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credential_dir:/etc/istio-ingressgateway/certs 
    hosts:
    - "*"
```
**Describe alternatives you've considered**
currently haproxy has this feature
```
frontend www.mysite.com
    bind 10.0.0.3:80
    bind 10.0.0.3:443 ssl crt /etc/ssl/certs/
    http-request redirect scheme https unless { ssl_fc }
    default_backend web_servers
```

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
Thanks for the suggestion. It does seem like it could be potentially useful for some scenarios.

I was wondering, in this setup, how/where do you expect the user to store their certificates?


---

HA proxy docs: http://cbonte.github.io/haproxy-dconv/configuration-1.5.html#5.1-crt

If no match, use the first cert. It doesn't specify what happens on conflicting certs (two foo.com, or a `a.foo.com` and `*.foo.com`)

**Comment by achilles-git** [comment]
can we store data in etcd or in a PersistentVolume?

ideally when you have `a.foo.com` and `*.foo.com` it should prioritise `a.foo.com`.

**Comment by howardjohn** [comment]
Currently we support reading files or Secrets. So we could read secrets but we would need some way to identify which ones we care about. For PV that would work, just requires a bit of setup

**Comment by achilles-git** [comment]
what kind of setup are we talking here?

**Comment by achilles-git** [comment]
attaching a PV to ingress-gateway pod would be easy. But does Istio have capabilities to take a directory of certificates and serve based on the SNI ?

**Comment by howardjohn** [comment]
No, it doesn't. I was asking to understand the requirements

**Comment by achilles-git** [comment]
ok
also not sure if underlying envoy proxy supports this.
