### ISSUE TITLE
Upgrade the various bots to use categorized labels

### ISSUE THREAD

**Issue by geeknoid** [istio/istio#2832]
As discussed in this doc (https://docs.google.com/document/d/1lA_9FEgP9ZpYCSqMjyvVWpvprvINQy5lSkpYoy6fBzA/edit?disco=AAAABjbcEw4&ts=5a68defa), our GitHub labels need some cleanup.

One particular concern is the fact our various bots use a bunch of randomly-named labels, effectively polluting the label namespace for humans trying to use GitHub for issue triage.

Can we change the labels used by the bots such that they all have a consistent prefix? This would make them much easier to manage and ignore. Following the pattern in the above doc, ideally we would have:

   bots/lgtm
   bots/do-not-merge

etc.

**Comment by hklai** [comment]
@sebastienvas, could you take a look since you are working on Tide migration now?

**Comment by sebastienvas** [comment]
All those labels are hard coded in the codebase, so that means creating a config for each of those. What's the priority for this ?

**Comment by geeknoid** [comment]
Not that critical, it's mostly about usability for people creating and
modifying issues.
