### ISSUE TITLE
All K8s version tests broken in postsubmit

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#28326]
https://prow.istio.io/view/gs/istio-prow/logs/integ-k8s-116_istio_postsubmit/4001
https://prow.istio.io/view/gs/istio-prow/logs/integ-k8s-115_istio_postsubmit/2132
https://prow.istio.io/view/gs/istio-prow/logs/integ-k8s-116_istio_postsubmit/3998

cc @ostromart @richardwxn

**Comment by howardjohn** [comment]
likely passes in presubmit but not postsubmit since we run all the jobs together; the operator test probably is colliding with others

**Comment by howardjohn** [comment]
also broken in 1.8 by https://github.com/istio/istio/pull/28300 cc @istio/release-managers-1-8

**Comment by nrjpoddar** [comment]
It's fixed now after updating the CI docker builder images. Un-assigning myself.

**Comment by bianpengyuan** [comment]
I think this is fixed.
