### ISSUE TITLE
lstioctl ps error: unable to find any pilot instances

### ISSUE THREAD

**Issue by pretendhigh** [istio/istio#28359]
I have installed istio when I was installing kubeflow.
My kubeflow is version 1.1.0. I don't know which istio version the kubeflow use. I just get the image of istio-pilot.   The stio-pilot image is gcr.io/istio-release/pilot:release-1.3-latest-daily. 
I download  [istio1.7.3](https://github.com/istio/istio/releases/download/1.7.3/istioctl-1.7.3-linux-amd64.tar.gz) . uncompress the file, and move istioctl to /usr/local/bin. But when I execute  `istioctl ps`, I get a error `error: unable to find any pilot instances` . what should I do?  Thanks for you advise.

**Comment by howardjohn** [comment]
istioctl 1.7 is not compatible with Istio 1.3. You will need to use the same version of both

**Comment by pretendhigh** [comment]
> istioctl 1.7 is not compatible with Istio 1.3. You will need to use the same version of both

Thank you. It works when I change istioctl 1.7  to istioctl 1.3

**Comment by shamsher31** [comment]
> Thank you. It works when I change istioctl 1.7 to istioctl 1.3

@pretendhigh Closing based on your comment.
