### ISSUE TITLE
Security FAQs are inaccurate and contains deprecated configurations

### ISSUE THREAD

**Issue by nrjpoddar** [istio/istio#28367]
**Bug description**

The [Security FAQ](https://istio.io/latest/faq/security/) contains answers which are no longer valid as the community has moved on to SDS instead of Citadel but the FAQ still refers to [Citadel options](https://istio.io/latest/faq/security/#cert-lifetime-config).

[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Security FAQ is correct and updated based on changes we are making to user facing options

**Comment by williamaronli** [comment]
add it to doc backlog
