### ISSUE TITLE
istio-nodeagent failed to get secret for proxy sidecar from secret cache: failed to get root cert

### ISSUE THREAD

**Issue by pretendhigh** [istio/istio#28361]
kubeflow 1.1.0
pod istio-nodeagent-br5j5 image: gcr.io/istio-release/node-agent-k8s:release-1.3-latest-daily
centos7.6

When I start a deploy x-0, sidecar istio-proxy will not be ready.
```
kb logs -f x-0 -c istio-proxy -n nvidia-gpu
...
info Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 0 successful, 0 rejected; lds updates: 0 successful, 0 rejected
...
```
I try to get the logs of the istio-nodeagent on the same kubelet node with x-0
```
kubectl logs -f istio-nodeagent-br5j5 -n istio-system
...
error  sdsServiceLog  CONNECTION ID: sidecar~10.253.12.32~x-0.nvidia-gpu.svc.cluster.local-7538, RESOURCE NAME： ROOTCA，EVENT：close connection. Failed to get secret for proxy "sidecar~10.253.12.32~x-0.nvidia-gpu.svc.cluster.loca" from secret cache: failed to get root cert.
...
```
It seems that only the node with x-0 pod has the problem. Pod distributed to other node work fine.

**Comment by howardjohn** [comment]
Istio 1.3 has not been supported for quite a while, so we are not able to help with this issue. Supported versions do not even have istio-nodeagent so this bug will not exist in the current code.

See https://istio.io/latest/news/support/announcing-1.3-eol-final/ for more info, thanks!
