### ISSUE TITLE
Set dynamically cluster domain parameter instead of using values.global.proxy

### ISSUE THREAD

**Issue by nak3** [istio/istio#28364]
**Describe the feature request**

- `istioctl` installation asks us to set `values.global.proxy` if the default domain `cluster.local` was changed.
- But it is troublesome when we want to run CI with random suffix. We need to update `values.global.proxy` by `sed` command every time.

**Describe alternatives you've considered**

- For example, Knative gets the cluster domain from `/etc/resolv.conf` inside pod like https://github.com/knative/pkg/blob/e135a17378476424c46108f6875a743f2d35ef52/network/domain.go
- Alternatively `kubectl get cm -n kube-system coredns -o yaml` could get the cluster domain information.

[X] Installation
[X] Networking
[X] User Experience
[X] Developer Infrastructure

**Comment by howardjohn** [comment]
In general I am very in favor of doing it dynamically, but its not trivial.

> For example, Knative gets the cluster domain from /etc/resolv.conf inside pod like https://github.com/knative/pkg/blob/e135a17378476424c46108f6875a743f2d35ef52/network/domain.go

https://github.com/istio/istio/pull/11878 attempted this previously, we did not think it handled all cases. Aside from custom /etc/resolv.conf cases, often times the control plane is not running in the same cluster

> Alternatively kubectl get cm -n kube-system coredns -o yaml could get the cluster domain information.

This is not portable across all clusters

It seems feasible to make the it dynamic by default and then still allow explicit option for these edge cases though.

Related issue, inspired by what you are doing actually: https://github.com/istio/istio/issues/28053

**Comment by howardjohn** [comment]
Not stale. Not sure how we can do this, but if we can it would be great.
