### ISSUE TITLE
make istio injector fsGroup configurable

### ISSUE THREAD

**Issue by medkbadri** [istio/istio#28360]
**Describe the feature request**

**Describe alternatives you've considered**

[ ] Docs
[ X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Describe the feature request**
Hello,

Currently, the istio injector webhook always injects 1337 as fsGroup to allow istio-proxy user access to k8s sa jwt token volume mount file as the container is running as non root.
https://github.com/istio/istio/blob/master/pkg/kube/inject/webhook.go#L685

The idea is to make the fsGroup that istio webhook injects parametrizable in a configMap for example to prevent overriding the customer fsGroup (in my case all my microservices need to have a special fsGroup)

Environment:
Kubernetes version: v1.16.13-eks-2ba888"
Istio:
client version: 1.7.3
control plane version: 1.7.1
data plane version: 1.7.1 (4 proxies)

**PS**
If you find that this feature makes sense, I can work on it.

Thanks,
-Khalil

**Comment by howardjohn** [comment]
I am not sure what you expect to set this to. If you set it to anything else it will break Istio?

Note this CAN be disabled: https://github.com/istio/istio/blob/master/pkg/kube/inject/webhook.go#L681 but it will fail unless you are on Kubernetes 1.19

**Comment by medkbadri** [comment]
it won't hurt Istio as the new fsGroup will be added to the container groups and /var/run/secrets/kubernetes.io/serviceaccount will have the new group.

```bash
istio-proxy@istio-proxy:/var/run/secrets/kubernetes.io/serviceaccount$ id
uid=1337(istio-proxy) gid=1337(istio-proxy) groups=1001
```
```bash
istio-proxy@istio-proxy:/var/run/secrets/kubernetes.io$ ls -ltrh
total 0
drwxrwsrwt 3 root 1001 140 Oct 28 16:58 serviceaccount
```

**1001** is my new fsGroup 

I expect istio not to change my containers fsGroup and unfortunately eks still doesn't have 1.19 version

**Comment by howardjohn** [comment]
we are not reading `/var/run/secrets/kubernetes.io/serviceaccount`, we read the projected token mount in `/var/run/secrets/tokens/istio-token`. From what i have seen removing the field entirely definitely breaks things (unless on k8s 1.19), are you saying if we set it to non 1337 it is somehow working?

**Comment by medkbadri** [comment]
I say not to remove the fsGroup (as it will fail because of non root permissions),  but to make it configurable as it will work with any fsGroup. With the actual behavior, we're forced to change many file permissions to tolerate the istio fsGroup.

**Comment by medkbadri** [comment]
A more simple approach would be maybe something like this:

```
if features.EnableLegacyFSGroupInjection {
		// due to bug https://github.com/kubernetes/kubernetes/issues/57923,
		// k8s sa jwt token volume mount file is only accessible to root user, not istio-proxy(the user that istio proxy runs as).
		// workaround by https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
		var grp = int64(1337)
		if pod.Spec.SecurityContext == nil {
			pod.Spec.SecurityContext = &corev1.PodSecurityContext{
				FSGroup: &grp,
			}
		} else {
			if pod.Spec.SecurityContext.FSGroup  == nil {
				pod.Spec.SecurityContext.FSGroup = &grp
			}
		}
	}
```

**Comment by medkbadri** [comment]
Hello,

Any update?
Thanks
