### ISSUE TITLE
Overlay with regex in IstioOperator

### ISSUE THREAD

**Issue by ostromart** [istio/istio#28376]
Injection template is a large block of YAML-like text which cannot be treated as YAML when overlaying (it's a template, not valid YAML). For use cases like these, a regex based replacement is required.

**Comment by howardjohn** [comment]
Given the new injection customizations (https://preliminary.istio.io/latest/docs/setup/additional-setup/sidecar-injection/#customizing-injection and below) I don't think we need this? WDYT?

**Comment by howardjohn** [comment]
Assuming resolved by this
