### ISSUE TITLE
Istio server operator not honoring revision field

### ISSUE THREAD

**Issue by rvennam** [istio/istio#28379]
**Bug description**

The Operator is ignoring the revision field. If I set revision to `revision: 1-7-3`, I assumed it would create istiod deployment with name `istiod-1-7-3`. However, the name is just `istiod`. This blocks me from doing a canary install.

This works as expected if run `istioctl manifest generate` or `istioctl manifest install`

[ ] Docs
[ X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

istiod should be named `istiod-<revision>`, such as:
```
istiod-1-7-3-57b66ff9b4-ztgjw           1/1     Running   0          13s
```

**Steps to reproduce the bug**
```
curl -L https://istio.io/downloadIstio | ISTIO_VERSION=1.7.3  sh -

./istio-1.7.3/bin/istioctl operator init

kubectl create ns istio-system

kubectl apply -f - <<EOF
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: example-istiocontrolplane
spec:
  profile: demo
  revision: 1-7-3
EOF

k get pods -n istio-system
NAME                                    READY   STATUS    RESTARTS   AGE
istio-egressgateway-669785ffb4-zslp2    1/1     Running   0          52m
istio-ingressgateway-76447f8f85-9295j   1/1     Running   0          52m
istiod-6bbcb9c658-bcpqx                 1/1     Running   0          52m
```

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
1.7.3

**How was Istio installed?**
operator

**Environment where bug was observed (cloud vendor, OS, etc)**
IKS

**Comment by rvennam** [comment]
cc: @sdake

**Comment by morvencao** [comment]
This was fixed in https://github.com/istio/istio/pull/28044
@ostromart I found that you close https://github.com/istio/istio/issues/28299  any reason for that?
