### ISSUE TITLE
Istio Performance Tools Need Updating

### ISSUE THREAD

**Issue by danehans** [istio/istio#2838]
The `setup_perf_cluster.sh` script uses gce/gke to automate performance testing of Istio. The script requires a user to set the `PROJECT` environment variable. It's preferable to have a sensible default that uses gcloud sdk to set `PROJECT`. Additionally and more importantly, the script fails to deploy the Istio control plane due to a missing admin cluster role binding. Lastly, the tooling directory has no documentation to help users.

**Comment by ldemailly** [comment]
done ! thx !
