### ISSUE TITLE
Only send NDS if DNS is enabled

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#28382]
No need to add the extra cost/risk for this when dns is not used

**Comment by daixiang0** [comment]
Mind share more details?

**Comment by howardjohn** [comment]
Yeah, https://github.com/istio/istio/blob/f5321ed627dd414d252ff0f75c767ce1c7713d99/pkg/istio-agent/xds_proxy.go#L197  is only needed if localDNSServer != nil. You can see we ignore the response if localDNSServer == nil already
