### ISSUE TITLE
istioctl dashboard controlz not working for istiod

### ISSUE THREAD

**Issue by zhongfox** [istio/istio#28388]
**Bug description**

```
~ % kubectl -n istio-system get pod
NAME                      READY   STATUS    RESTARTS   AGE
istiod-74bdd5d657-sv82v   1/1     Running   0          12d
~ % istioctl --namespace istio-system  dashboard controlz istiod-74bdd5d657-sv82v
Error: could not build port forwarder for ControlZ istiod-74bdd5d657-sv82v: failed retrieving pod: pods "istiod-74bdd5d657-sv82v" not found
~ % istioctl -n istio-system  dashboard controlz istiod-74bdd5d657-sv82v
Error: unknown shorthand flag: 'n' in -n
~ % istioctl version
client version: 1.7.3
control plane version: 1.7.3
data plane version: none
```

1. why can not find istiod pod?  
2. seem namespace shortcut not working: `-n istio-system`

[X] Installation
[X] User Experience
[X] Developer Infrastructure

**Comment by shamsher31** [comment]
@zhongfox can you try appending namespace `istio-system` to istiod pod?

```
[istio-1.7.3]$ istioctl dashboard controlz istiod-7684b696d6-d8jwc.istio-system
http://localhost:9876
```

**Comment by shamsher31** [comment]
You can directly access controlz dashboard by appending namespace to the pod instead of `-n`. as `-n` is a global flag and not directly supported by controlz. https://github.com/istio/istio/pull/28391

**Comment by zhongfox** [comment]
> @zhongfox can you try appending namespace `istio-system` to istiod pod?
> 
> ```
> [istio-1.7.3]$ istioctl dashboard controlz istiod-7684b696d6-d8jwc.istio-system
> http://localhost:9876
> ```
> 
> ```
> [istio-1.7.3]$ istioctl dashboard controlz -h
> Usage:
>   istioctl dashboard controlz <pod-name[.namespace]> [flags]
> ```

this works correctly, thx

**Comment by cortopy** [comment]
@shamsher31 thanks for the tip! I was scratching my head over this and the dot notation worked. I'm not sure how the docs could be edited, but if I understood what you're saying, then the docs are wrong https://istio.io/latest/docs/ops/diagnostic-tools/controlz/ as there it says that "-n" works. This is going to get other people too

`istioctl dashboard controlz` has information about both dot notation and "-namespace" but the latter didn't work for me either. Only dot notation works
