### ISSUE TITLE
Response application in/out duration increased on istio

### ISSUE THREAD

**Issue by connatix-cradulescu** [istio/istio#28398]
Hello,

We are in the process of migrating from Nginx ingress to istio. During our test, we saw that the call duration for in/out requests for our application has increased from 4-6 microseconds (Nginx ingress) to 300-800 microseconds.  This increase might affect the quality of our services being a high traffic application.

We are suspecting that has to do with client body size, which is a bit higher than normal, and on Nginx ingress, we resolved this issue by setting up  " client-body-buffer-size: "128k". This instructs Nginx to load the body < 128k to memory and to be served for memory.

I am not sure this is the issue and that's why I am hoping I will get some help here since I was not able to find anything via search engines. related to this issue. 

Thank you!

**Comment by howardjohn** [comment]
Your application was handling requests in 4 **micro**seconds before?? That seems quite fast. Are you sure this is not milliseconds?

800 microseconds would be well within the expectations for Istio, but 800 milliseconds would be quick a bit slower than expected. See https://istio.io/latest/docs/ops/deployment/performance-and-scalability/#latency-for-istio-hahahugoshortcode-s3-hbhb for some details.


I believe envoy already has the behavior you enabled with `client_body_buffer_size`, in that it does not buffer to disk.

cc @carolynhu

**Comment by connatix-cradulescu** [comment]
Hi @howardjohn Thank you a lot for having a look into this.  I can confirm that are **micro**seconds and istio the worst is 800 microseconds. 

Istio would not buffer on disk no matter the size of the client body or there is a limit? I am asking cause I just can't find this information.

**Comment by howardjohn** [comment]
How are you measuring latency?

For the buffer, based on https://github.com/istio/istio/issues/24370 I believe this is the case, we never buffer

**Comment by connatix-cradulescu** [comment]
Seams the issue is coming from istio ingress being too low. We face the next type of error reading from pipe: 
```
Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Reading the request body timed out due to data arriving too slowly. See MinRequestBodyDataRate.
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelBadHttpRequestException.Throw(RequestRejectionReason reason)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ContentLengthMessageBody.ReadAsyncInternal(CancellationToken cancellationToken)
   at Connatix.Web.ServingAPI.Middleware.PipeTransfer.FromPipeReaderToMemoryStream(PipeReader pipeReader, MemoryStream memoryStream) in /app/src/Connatix.Web.ServingAPI/Middleware/PipeTransfer.cs:line 17
   at Connatix.Web.ServingAPI.Middleware.PipeTransfer.FromPipeReaderToMemoryStream(PipeReader pipeReader, MemoryStream memoryStream) in /app/src/Connatix.Web.ServingAPI/Middleware/PipeTransfer.cs:line 45
   at Connatix.Web.ServingAPI.Middleware.RouteResolverMiddleware`2.ReadProtoRequest(PipeReader pipeReader, String path) in /app/src/Connatix.Web.ServingAPI/Middleware/RouteResolverMiddleware.cs:line 185
   at Connatix.Web.ServingAPI.Middleware.RouteResolverMiddleware`2.ReadProtoRequest(PipeReader pipeReader, String path) in /app/src/Connatix.Web.ServingAPI/Middleware/RouteResolverMiddleware.cs:line 185
   at Connatix.Web.ServingAPI.Middleware.RouteResolverMiddleware`2.InvokeAsync(HttpContext context, IService`2 service) in /app/src/Connatix.Web.ServingAPI/Middleware/RouteResolverMiddleware.cs:line 141


```
We dont face this king of issues with Nginx ingress.  Any advice? 
Might be helpful https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.server.kestrel.core.kestrelserverlimits.minrequestbodydatarate?view=aspnetcore-3.1

**Comment by connatix-cradulescu** [comment]
The issue is what I have suspected in the first place. The Istio ingress is buffering the client's body size after a certain size ( I don't know the default value). I did solve the problem by applying:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: limit-request-size
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.http_connection_manager
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.buffer
        typed_config:
          '@type': type.googleapis.com/udpa.type.v1.TypedStruct
          value:
            maxRequestBytes: 1048576
```

**Comment by jpichette1** [comment]
Joe from Aspen Mesh here; we got on a call with Constantin and dug into this a little deeper. 

We believe the tool reporting the delay is reporting an application-internal transaction time that depends on the request, which is a POST with a body. 

Without maxRequestBytes set, Envoy sidecar starts a new request with the app (including writing the headers); this starts the performance timer.  This happens before Envoy necessarily has processed the body of the request.  Next, Envoy sends the body to the app; this ends the performance timer (after the app processes etc). 

Setting maxRequestBytes to any number larger than the body means that Envoy buffers the request body as well, so it can write the request headers and body together to the app.

**Comment by connatix-cradulescu** [comment]
I would recommend that this setting be part of Istio documentation on the Envoy section or where you consider it is best.  Took me quite a long time to figure out what might cause this issue and how to solve it and was the "hard way" that almost sent me to the "high way".  This issue might be lost in time and the community might lose important findings as long is not part of core istio documentation.
