### ISSUE TITLE
Allow to build and publish built-in custom profile

### ISSUE THREAD

**Issue by nak3** [istio/istio#28394]
**Describe the feature request**

- It would be great if we could publish our custom profile (e.g. knative) and allow users to use it as:

```
$ istioctl install --set profile=myprofile
```

```
$ istioctl install --set profile=knative
```

- For example, Knative needs many customization for Istio installation like [Istio profile for Knative](https://knative.dev/docs/install/installing-istio/#installing-istio-without-sidecar-injection).
- Although Istio supports [external charts](https://istio.io/latest/docs/setup/install/istioctl/#install-from-external-charts), it still needs to say "please download the chart on your current directory, etc".
- So we wonder how hard it would be to get it.

[X] Installation
[X] User Experience

**Additional context**

Knative had the discussion in https://github.com/knative/docs/issues/2166

P.S. I wonder if somebody already did same request but I could not find it. Sorry if duplicated.

**Comment by shamsher31** [comment]
Openshift profile was recently added https://github.com/istio/istio/pull/28076, https://github.com/istio/istio.io/pull/8334

**Comment by nak3** [comment]
Oh, great! Thank you. Then, probably we can add the knative profile maybe. I will send the PR.

**Comment by shamsher31** [comment]
I think so, later we can add the ability to distinguish between core Istio profile and additional profiles? Eg:

```
$ istioctl profile list -d manifests/
Istio configuration profiles:
core:
    default
    demo
    empty
    minimal
    preview
    remote
addon:
    knative
    openshift
```
cc: @esnible

**Comment by howardjohn** [comment]
You can also just pass `-f knative.yaml`

**Comment by shamsher31** [comment]
@nak3 Found this info https://github.com/istio/istio/blob/master/manifests/profiles/PROFILES.md

**Comment by nak3** [comment]
Recent Knative can work with Istio's default profile. So I close this.
