### ISSUE TITLE
feat: add linter to istio/proxy to check CEL expressions for validity

### ISSUE THREAD

**Issue by douglas-reid** [istio/istio#28413]
**Describe the feature request**
Add a linter to istio/proxy that prevents typos and misconfigurations around CEL expressions. These are hard to catch during human review of code.

Example: https://github.com/istio/proxy/pull/3076

[ X ] Extensions and Telemetry

**Additional context**

/cc @gargnupur @kyessenov @bianpengyuan

**Comment by Kang-Bae** [comment]
I would like to give this issue a try!
