### ISSUE TITLE
Number of sockets opened by sidecar

### ISSUE THREAD

**Issue by connatix-cradulescu** [istio/istio#28428]
Hi,

We are in the process of migrating the ingress solution from Nginx ingress to istio. During our tests, we observed that the number of sockets opened on a node ( Kubernetes) after enabling the injection is very high and this can bring an overhead to our application. 

Here is an example:
Application x 
- without istio injection 10 to 20 opened sockets
- with istio injection from 1300 to 2500

This is a huge difference and we do not understand where is coming from and why the isito-proxy container is opening so many sockets. 

Any advice would be welcomed.

Thank you!
Constantin Radulescu

**Comment by howardjohn** [comment]
Can you describe your workloads a bit more? Is this 1300 per pod, per node, cluster wide?

Can you run `ss` and/or `netstat` to see what the open sockets are?

How many requests are the pods handling and how many services are they sending traffic to?

**Comment by connatix-cradulescu** [comment]
Hi @howardjohn. Here is the data you were asked for:
`
Number of connection to istio-proxy:

Type of connection
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:15021           0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:15090           0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:15000         0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:15001           0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:15006           0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:53282         127.0.0.1:5000          ESTABLISHED
tcp        0      0 127.0.0.1:54264         127.0.0.1:5000          ESTABLISHED
tcp        0      0 127.0.0.1:51282         127.0.0.1:5000          TIME_WAIT
tcp        0      0 127.0.0.1:53510         127.0.0.1:5000          TIME_WAIT
tcp        0      0 127.0.0.1:49598         127.0.0.1:5000          ESTABLISHED
tcp        0      0 127.0.0.1:49560         127.0.0.1:5000          TIME_WAIT
tcp        0      0 127.0.0.1:49568         127.0.0.1:5000          TIME_WAIT
tcp        0      0 127.0.0.1:50678         127.0.0.1:5000          TIME_WAIT
tcp        0      0 127.0.0.1:50344         127.0.0.1:5000          ESTABLISHED
tcp        0      0 127.0.0.1:53310         127.0.0.1:5000          ESTABLISHED
tcp        0      0 127.0.0.1:50016         127.0.0.1:5000          ESTABLISHED
tcp        0      0 127.0.0.1:54270         127.0.0.1:5000          ESTABLISHED
tcp        0      0 127.0.0.1:49686         127.0.0.1:5000          TIME_WAIT


Total number of connection to istio-proxy

root@tracking-5f8b796545-8v596:/app# netstat -an |  awk '{print $4}' | sort -n | uniq -c | grep -c 127.0.0.1
1424



ESTABLISHED
root@tracking-5f8b796545-8v596:/app# netstat -an |  awk '{print $4 " " $6}' | sort -n  | grep 127.0.0.1 | grep -c ESTABLISHED
950

TIME_WAIT
root@tracking-5f8b796545-8v596:/app# netstat -an |  awk '{print $4 " " $6}' | sort -n  | grep 127.0.0.1 | grep -c TIME_WAIT
662


root@tracking-5f8b796545-8v596:/app# ss | head -n10
Netid    State         Recv-Q    Send-Q                Local Address:Port                                           Peer Address:Port
u_str    ESTAB         0         0             ./etc/istio/proxy/SDS 7742312                                                   * 7744060
u_str    ESTAB         0         0                                 * 7744060                                                   * 7742312
tcp      ESTAB         0         0                         127.0.0.1:53282                                             127.0.0.1:5000
tcp      ESTAB         0         0                         127.0.0.1:58436                                             127.0.0.1:5000
tcp      ESTAB         0         0                         127.0.0.1:59418                                             127.0.0.1:5000
tcp      ESTAB         0         0                         127.0.0.1:34114                                             127.0.0.1:5000
tcp      ESTAB         0         0                         127.0.0.1:56432                                             127.0.0.1:5000
tcp      ESTAB         0         0                         127.0.0.1:50344                                             127.0.0.1:5000
tcp      ESTAB         0         0                         127.0.0.1:53310                                             127.0.0.1:5000

root@tracking-5f8b796545-8v596:/app# ss -t | head -n10
State      Recv-Q Send-Q          Local Address:Port               Peer Address:Port
ESTAB      0      0                   127.0.0.1:53282                 127.0.0.1:5000
ESTAB      0      0                   127.0.0.1:58436                 127.0.0.1:5000
ESTAB      0      0                   127.0.0.1:59418                 127.0.0.1:5000
ESTAB      0      0                   127.0.0.1:34114                 127.0.0.1:5000
ESTAB      0      0                   127.0.0.1:56432                 127.0.0.1:5000
ESTAB      0      0                   127.0.0.1:50344                 127.0.0.1:5000
ESTAB      0      0                   127.0.0.1:53310                 127.0.0.1:5000
ESTAB      0      0                   127.0.0.1:34136                 127.0.0.1:5000
ESTAB      0      0                   127.0.0.1:34164                 127.0.0.1:5000

root@tracking-5f8b796545-8v596:/tmp# ss -s
Total: 1004
TCP:   1603 (estab 964, closed 625, orphaned 0, timewait 518)

Transport Total     IP        IPv6
RAW       0         0         0
UDP       0         0         0
TCP       978       534       444
INET      978       534       444
FRAG      0         0         0
`

**Comment by howardjohn** [comment]
Seems like it has many open connections to port 5000. Can you give more info about what is on this port? Looking at config dump and /clusters may help: https://github.com/istio/istio/wiki/Troubleshooting-Istio

**Comment by connatix-cradulescu** [comment]
On port 5000 is running the APP. I will enable tomorrow the sidecar again and I will put the requested info. 

Thank you!

**Comment by connatix-cradulescu** [comment]
Hi @howardjohn . I did dump all the logs and configuration. I cant share the logs here, cause might have sensitive data.  I will read them and try to understand if there is any issues. At this moment I did not balance all the traffic through istio ingress gateway, only 5%, the rest of 95% is going through old Nginx ingress. I am wondering if this can cause this issue?  Does the istio proxy have different behavior if not all traffic is routed through istio ingress gateways?

**Comment by connatix-cradulescu** [comment]
Seams the issue is coming from istio ingress being too low. We face the next type of error reading from pipe: 
```
Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Reading the request body timed out due to data arriving too slowly. See MinRequestBodyDataRate.
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelBadHttpRequestException.Throw(RequestRejectionReason reason)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ContentLengthMessageBody.ReadAsyncInternal(CancellationToken cancellationToken)
   at Connatix.Web.ServingAPI.Middleware.PipeTransfer.FromPipeReaderToMemoryStream(PipeReader pipeReader, MemoryStream memoryStream) in /app/src/Connatix.Web.ServingAPI/Middleware/PipeTransfer.cs:line 17
   at Connatix.Web.ServingAPI.Middleware.PipeTransfer.FromPipeReaderToMemoryStream(PipeReader pipeReader, MemoryStream memoryStream) in /app/src/Connatix.Web.ServingAPI/Middleware/PipeTransfer.cs:line 45
   at Connatix.Web.ServingAPI.Middleware.RouteResolverMiddleware`2.ReadProtoRequest(PipeReader pipeReader, String path) in /app/src/Connatix.Web.ServingAPI/Middleware/RouteResolverMiddleware.cs:line 185
   at Connatix.Web.ServingAPI.Middleware.RouteResolverMiddleware`2.ReadProtoRequest(PipeReader pipeReader, String path) in /app/src/Connatix.Web.ServingAPI/Middleware/RouteResolverMiddleware.cs:line 185
   at Connatix.Web.ServingAPI.Middleware.RouteResolverMiddleware`2.InvokeAsync(HttpContext context, IService`2 service) in /app/src/Connatix.Web.ServingAPI/Middleware/RouteResolverMiddleware.cs:line 141

We dont face this king of issues with Nginx ingress.  Any advice? 
```

**Comment by howardjohn** [comment]
I don't think the ingress pod knows how much traffic % it gets? Would be interesting to look at /stats and grep for "connections" to get envoy's view, as well as see the number of endpoints for the backend on 5000 and see if it correlates to the number of connections.

@lambdai may have more insight as well

**Comment by connatix-cradulescu** [comment]
I did observe that the numbers of sockets were going down as number, as I was redirecting more and more traffic through Istio Ingress.  I did make a test yesterday until 15% traffic through Istio and I have seen that fewer and fewer sockets are opened. But I can't go and make a real test with over 50% trough istio as long I can't figure out what is the issue with #28398. The more traffic I was redirecting through istio we were starting to get more warning and error. They are specified on the linked issue.

**Comment by connatix-cradulescu** [comment]
I have been doing some more deep tests and if I am applying TCP traffic policy the number of sockets is going down to the number I am providing by maxConnections: 100. 

This tells me that the istio-proxy does not reuse sockets and open sockets for each connection.  Another aspect of the traffic from istio-proxy to the app is seen as TCP and not HTTP. No HTTP rules have an effect when I am applying them to the istio-proxy container.   

Is this the fact that the svc is TCP ( cause svc type: ClusterIP can support only TCP and UDP ?) 

I am asking this cause by applying:
```
    connectionPool:
      http:
        maxRequestsPerConnection: 0
```
should reuse sockets, but as long the traffic is sent as TCP from container app to container istio-proxy this has no effect. 

Any thoughts on this?

**Comment by howardjohn** [comment]
See
https://preliminary.istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/
for selecting protocol, the `protocol` field is not the right setting.

**Comment by connatix-cradulescu** [comment]
All our ports have "http" as naming. Did dose require prefix too?

**Comment by jpichette1** [comment]
Joe from Aspen Mesh here; we got on a call with Constantin and dug into this a little deeper. 

First, we identified that the tooling was counting each end of the socket between sidecar and app, in addition to one end of the sockets between the ingress and the sidecar.  So for example, at one point we saw: 

- 79 connections between nginx and the pod (sidecar) 
- 707 connections between sidecar and app 
      - 707 entries in “netstat -an” for the end of the socket in the sidecar 
      - 707 entries in “netstat -an” for the end of the socket in the app 

A tool that counts sockets by running “netstat -an” and counting lines shows 707+707+79=1493 in this case, but only shows 79 sockets in the non-sidecar case. 

However, 707 connections between sidecar and app is still surprising when there are only 79 connections between nginx and sidecar.  So we kept investigating that. 

In the default configuration,Istio (Envoy) will open a new connection whenever there are no idle connections available because it believes this will achieve the highest performance and “maxConnection” is defaulted to 4 billion which means envoy can open sockets pretty much without limit.  We think that this particular workload ( high volume, bursty, small POST requests, hitting envoy all at once), looks very bursty at Envoy and so it ends up choosing to open new sockets frequently.  For this application, this causes the application to slow down due to difficulty handling all the open sockets.  Eventually causing latency errors.  

We found that most of the time, most of the sockets were idle (according to netstat).  If we turned down the idleTimeout, they tended to go away quickly and then reappear every several seconds or so. 

Constantin ran a test verifying setting “maxConnection: 500” limited the number of opened sockets to 500 between sidecar and app (so, 500+500=1000 entries in netstat –an and 500 entries in Envoy stats). 

In the limited time we had together, we didn’t observe maxConnections: 500 adversely impacting performance for this app, including latency.  We think this supports the idea that the bursts are very short-lived, as otherwise, you’d see an increase in latency when you hit 500 connections and requests sat in Envoy’s request queue (http1). 

We were running in this configuration with the request buffer set ([#29398](https://github.com/istio/istio/issues/28398)), and we think that may have helped smooth out some burstiness. 

However, Constantin is not comfortable with setting maxConnections: 500 as a limit permanently because its app-by-app tuning.  We explored the idea of some sort of soft-limit where you only buffer a request for a short period before opening a new connection up to some hard limit (maxConnections). We’re thinking to open a separate RFE to explore that idea.

**Comment by nrjpoddar** [comment]
Thanks @jpichette1 for the excellent analysis.

**Comment by connatix-cradulescu** [comment]
I want to thanks the Aspen Mesh team for the time and support for this case.

**Comment by connatix-cradulescu** [comment]
@lambdai Thank you! I did observe I do have better results on the http2 upgrade. I will test with max_requests_per_connection and connection_idle_timeout and see what results I do have. I will give it a try after the holidays. 

Thank you!
