### ISSUE TITLE
istioctl: fails to add custom root CA for JWKS if cert contains '='

### ISSUE THREAD

**Issue by poussa** [istio/istio#28422]
**Bug description**

The following command fails if the `cert-text` contains character '='.

```bash
 istioctl install --set values.pilot.jwksResolverExtraRootCA=<cert-text>
```

Example of such cert is attached below. 

[bad-rootCA.crt.txt](https://github.com/istio/istio/files/5464178/bad-rootCA.crt.txt)

```bash
istioctl install --set values.pilot.jwksResolverExtraRootCA="$(awk 'NF {sub(/\r/, ""); printf "%s\\n",$0;}' bad-rootCA.crt)"
Error: failed to install manifests: set flag values.pilot.jwksResolverExtraRootCA=-----BEGIN CERTIFICATE-----\nMIIEqDCCApACCQDuHOFebfLyHTANBgkqhkiG9w0BAQsFADAWMRQwEgYDVQQDDAtj\nYS5ob21lLmxhbjAeFw0yMDA5MjMxMTM4NDJaFw0yMzA3MTQxMTM4NDJaMBYxFDAS\nBgNVBAMMC2NhLmhvbWUubGFuMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKC\nAgEA0PMfm2UGI/RSCNU8C69NQVzppI/e/15HotFU/3JtR1Hvs3TatNlHzsy2iSB9\nn/34CiAKySkhzJa7cGCHmEJimVmWwT6VBxw7vIwf+mIiKcki1FM7i49fXSBTqo00\n+eALdGB3ChgCucMsF0dKxnzbn+TQa86DdT2etbWbjKSqyc0C9NpvuwZyXJJJPRC1\nHWwOpN+JHnJMQ/gzuojpG4Xrgw/bUcxZJPxt+42hM/TFtSQUaFf5OCQqx39fuL+A\n8IHCHEirL1yDVMKWrF3XLpmrQFSAlAa0IajeXD9Aqe0CqQo+bPNvCJhz0dYFGe9W\n7HkySmj37h1joEI2icypA/f0XNeaZokRrHpX4+jMfmpgyNWIllm4oJCxktSYNJ/S\n/QRQX7IqkPzkyH4KKc8rMyaAJPO0jvzAzaQBIW722ZbDxQPtpvdk/vWuE37x3Tg1\nzgcJg21t4E2ZYaLX6jvrGF8oPedOzlCB3Pbq6T7J+0UZNkub5OLkUpD8a+MCrmIP\nGzwpWU8y7dxI4RLzil65N6M3e7RNWvH9LPRNKb902686prZV0smpP9DC2khzmkrZ\nkoLkfo1xm/huNvZg2Fq2xSY2EYfi/fCEpa21GRUChoZxVk62nYAx7EdMk39HULvj\nZ5/V1vJXM5H+Uq+MhMzSvZ7bL7KBM7EnxsclzYVeN35JF10CAwEAATANBgkqhkiG\n9w0BAQsFAAOCAgEAg2+r8qNYk1HV+LzxrrCIQRq1hZTIDzDvAYSjFfvNxN6GSmXr\nJwcZDnDT3Hf7eRRq+T6w9HmgDhHGGP0/PyTKgLr/hp8UpwayQj/vrrQv2rFcH/tO\nImy1C1qhVuanrH1ak8V7nDvLlmJMtFF3T8MuAvglolS1HJdejZ3aQbMI1mdOgCbM\nTJYEFawy3auPge1WvP64NMaqVsZBcQYIt+fqJUe6U4eh2MLKtRBC5ueMWjaz4Kqu\n06d5BPhGx1S1NcKq/STZWMuhyqVOpSNLaFmep00pFb3VVzo0wzeyPHp3GOuTRfl3\nDVdgelPzSiUnMaFTLiOSJip0PN2WOhO4RXLHCvjeLoSiX/i/su+6mykBzt2yhMTX\nHa8Muoi8HyOfUDrAhGHttALLXGnUTIPvhV/J0vayb1oS9RzEwVlET3qjxusrGkug\nSqmL9n4khu/+fI8k+0zi3l5dVzlJVC0LPvIXG6lZNxouP9FGCFtxOEplnu2z/p3R\nKbHCvSZmJzVEKRFm9/mBezO5uDfBaqiggKxCmcTxg1uZKBwN8WcZEKSWQZ1IJzDx\nJz2/7kYaekT1m9LZIAKwmU5YCMZddQqUxE/WRfJ2rU40F4VLbUwjWXLarFmbncHj\nOQMTHPmaskhiXmoqLf6K/KiBIzV5i7fBds+a4Fdxm8WTt1D6jMVuWgc1A/A=\n-----END CERTIFICATE-----\n has incorrect format, must be path=value
```

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Expected behavior**

The cert installs correctly

**Steps to reproduce the bug**

The steps are above.

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

```bash
istioctl version
client version: 1.7.3
control plane version: 1.7.3
data plane version: 1.8-dev (1 proxies)
```

**How was Istio installed?**

Via istio operator

**Environment where bug was observed (cloud vendor, OS, etc)**

On prem cluster, ubuntu 20.04

**Comment by howardjohn** [comment]
I highly recommend you use the IstioOperator file approach rather than `--set` flags. I believe it would get around this.
You might also be able to fix this by escaping the `=`, not sure

**Comment by poussa** [comment]
@howardjohn thanks for the info. The operator api does not talk about how to do this. Can you share a pointer how to do it?

Escaping the offending character does not solve the issue with the `--set` flag approach.

**Comment by howardjohn** [comment]
you can see some examples in https://preliminary.istio.io/latest/docs/setup/install/istioctl/#customize-istio-settings-using-the-helm-api

**Comment by poussa** [comment]
Yeah, the below seems to be working with the operator. 

```yaml
spec:
  values:
    pilot:
      jwksResolverExtraRootCA: |
        -----BEGIN CERTIFICATE-----

```

**Comment by poussa** [comment]
We have an alternate way of achieving the solution. Closing.
