### ISSUE TITLE
Istioctl upgrade - upgrade check warning after upgrading

### ISSUE THREAD

**Issue by ceastman-ibm** [istio/istio#28430]
**Bug description**
I just used istioctl upgrade -f config.yaml to upgrade from 1.7.3. to 1.7.4. After the upgrade I run the same command but i get warnings that "The following IOPS will be changed as part of upgrade." Shouldn't there be no changes/warnings if I just upgraded?

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Expected behavior**
2nd upgrade using same istioctl, config.yaml, etc. should be a noop - since there are no config or version changes.

**Steps to reproduce the bug**
run the following twice in a row:

istioctl upgrade -f config.yaml

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
istioctl version --remote
client version: 1.7.4
control plane version: 1.7.4

kubectl version --short
Client Version: v1.17.7

 oc version
Client Version: 4.4.0-202004210425-2576e48
Server Version: 4.4.27
Kubernetes Version: v1.17.1+45f8ddb

**How was Istio installed?**
using istioctl

**Environment where bug was observed (cloud vendor, OS, etc)**
ibm cloud - openshift cluster

[config.yaml.gz](https://github.com/istio/istio/files/5465791/config.yaml.gz)

**Comment by shamsher31** [comment]
Must be fixed by https://github.com/istio/istio/pull/28571

```
[istio-1.7.4]$ ./bin/istioctl upgrade
Control Plane - ingressgateway pod - istio-ingressgateway-64cfb9d44b-wj6sm - version: 1.7.3
Control Plane - pilot pod - istiod-7684b696d6-rrqsn - version: 1.7.3

Upgrade version check passed: 1.7.3 -> 1.7.4.

Upgrade check: IOPS unchanged. The target IOPS are identical to the current IOPS.
installPackagePath: /tmp/istio-install-packages/istio-1.7.3/manifests ->

Confirm to proceed [y/N]?
```
