### ISSUE TITLE
Jaeger Tracing with non-istio ingress

### ISSUE THREAD

**Issue by Stono** [istio/istio#2843]
Hey folks, 
As wonderful as your ingress controller is, I've opt'd to use [nginx-ingress](https://github.com/kubernetes/ingress-nginx) due to some additional features that I need for my public facing services.

All in all it is working quite nicely, apart from one final issue around tracing.  It seems like envoy is using the pod name as the service name:

<img width="613" alt="screen shot 2018-01-25 at 19 25 59" src="https://user-images.githubusercontent.com/1486729/35409309-b3e54b8a-0209-11e8-9975-24828a658f5b.png">

I'm wondering if there is any way for me to force the envoy wrapping the ingress controllers to use a specific service name?

Crosslinking: https://github.com/kubernetes/ingress-nginx/issues/1985

**Comment by Stono** [comment]
This magically seems to have started working since 0.5.0.  No idea why.

**Comment by kyessenov** [comment]
We have bumped Envoy version we take upstream.
