### ISSUE TITLE
Question: Difficult to setup env to do integration test locally 

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#28455]
I tried to run an integration test in my local dev cluster, however several issues i have found:

1. the east-west gateway can not run: my cluster does not support third-party-jwt, and there is no way to set it. 

2. istio-eastwestgateway is not available `Test setup error: build instance: generate yaml: failed to get ingress IP for cluster-0`. I have no load balancer.

This is not a good experience for developers

**Comment by daixiang0** [comment]
+1

**Comment by irisdingbj** [comment]
In integration test, we will set up MetalLB as loadbalancer, you can try this in your local test as well @hzxuzhonghu

**Comment by ericvn** [comment]
I use a kind cluster setup using `kind create cluster --name istio-testing --config $ISTIO/istio/prow/config/trustworthy-jwt.yaml` to get things to start.

**Comment by hzxuzhonghu** [comment]
If there is a script setting up metalLB automatically that would help much
