### ISSUE TITLE
Docs: clean up dead links

### ISSUE THREAD

**Issue by daixiang0** [istio/istio#28473]
**Describe the feature request**

I read docs and find some dead links.

I do not put them in one pr since they belong to different areas, may be hard to review in one place.

Some are merged:

- #28458 
- #28461
- #28460
- #28464
- #28459 
- #28454 
- #28462 
- #28454
- #28463
- #28453 
- #28559
- #28560
- #28561

In some cases, i am not sure right link so i remove directly, please tell me if possible.

**Affected product area (please put an X in all that apply)**

[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by Monkeyanator** [comment]
Don't we have a CI step checking for dead links? Wonder why so many are getting past it (or maybe we only check the links on check-in?)
