### ISSUE TITLE
How to build istio/proxy

### ISSUE THREAD

**Issue by hustshawn** [istio/istio#28476]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
I checked out istio/proxy, and trying to build with `make build` or `make`, it would fail.
```
root@ip-172-31-45-102:~/istio/proxy# make build
export PATH=/usr/lib/llvm-9/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin CC=clang CXX=clang++ && bazel  build  --config=libc++ //...
INFO: Analyzed 175 targets (834 packages loaded, 51063 targets configured).
INFO: Found 175 targets...
ERROR: /root/istio/proxy/src/istio/utils/BUILD:77:1: C++ compilation of rule '//src/istio/utils:attribute_names_lib' failed (Exit 1) clang failed: error executing command /usr/bin/clang -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer '-stdlib=libc++' -MD -MF ... (remaining 21 argument(s) skipped)
Use --sandbox_debug to see verbose messages from the sandbox
In file included from src/istio/utils/attribute_names.cc:16:
./include/istio/utils/attribute_names.h:19:10: fatal error: 'string' file not found
#include <string>
         ^~~~~~~~
1 error generated.
INFO: Elapsed time: 68.531s, Critical Path: 0.44s
INFO: 1 process: 1 linux-sandbox.
FAILED: Build did NOT complete successfully
make: *** [Makefile.core.mk:68: build] Error 1

root@ip-172-31-45-102:~/istio/proxy# make build_envoy
export PATH=/usr/lib/llvm-9/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin CC=clang CXX=clang++ && bazel  build  --config=libc++ --config=release //src/envoy:envoy
INFO: Build options --compilation_mode and --strip have changed, discarding analysis cache.
INFO: Analyzed target //src/envoy:envoy (5 packages loaded, 36487 targets configured).
INFO: Found 1 target...
ERROR: /root/.cache/bazel/_bazel_root/7403c55f491a61a6e198902a394e10ff/external/com_google_protobuf/BUILD:117:1: C++ compilation of rule '@com_google_protobuf//:protobuf_lite' failed (Exit 1) clang failed: error executing command /usr/bin/clang -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 31 argument(s) skipped)
Use --sandbox_debug to see verbose messages from the sandbox
In file included from external/com_google_protobuf/src/google/protobuf/arena.cc:31:
external/com_google_protobuf/src/google/protobuf/arena.h:36:10: fatal error: 'limits' file not found
#include <limits>
         ^~~~~~~~
1 error generated.
Target //src/envoy:envoy failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 3.704s, Critical Path: 0.56s
INFO: 2 processes: 2 linux-sandbox.
FAILED: Build did NOT complete successfully
make: *** [Makefile.core.mk:71: build_envoy] Error 1
```
**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
1.7.4
**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**
UBUNTU
Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by hustshawn** [comment]
Anyone could suggest what's the best way to build istio/proxy?

**Comment by AEGQ** [comment]
```
cd /root/go/src/istio.io/
git clone https://github.com/istio/proxy.git

cd proxy
docker run -it -w /work -v $PWD:/work gcr.io/istio-testing/build-tools-proxy:master-latest bash
make
```
have a try ...

**Comment by morlay** [comment]
Or trying

```shell
docker run \
   -e=TEST_TMPDIR=/tmp/bazel \
   -v=/tmp/bazel:/tmp/bazel \
   -v=${PWD}:/go/src/istio/proxy \
   -w=/go/src/istio/proxy \
   docker pull ghcr.io/querycap/istio/istio-envoy-build-env:0.1.0 make build_envoy
```

it will be simpler and clean than `build-tools-proxy`
Dockerfile: https://github.com/querycap/istio/blob/master/build/istio-envoy-build-env/Dockerfile.istio-envoy-build-env

This used for multi arch support.
https://github.com/istio/istio/issues/26652#issuecomment-714858976

**Comment by howardjohn** [comment]
@istio/wg-networking-maintainers-data-plane it would be great to have a doc on this. I have struggled as well

**Comment by daixiang0** [comment]
@howardjohn put doc under istio repo or proxy repo?

**Comment by hustshawn** [comment]
Thank you all for the suggestion.  I am trying the way @morlay suggest.

@morlay more context to you, the reason I am starting to build the istio envoy is I need to do some hacks on the envoy binary. Actually I started from the official `envoyproxy/envoy`, and built the binary with my hack(`http_parser` source code change) and shipped to `istio-proxy` image, but it can not work as expected. https://github.com/istio/istio/issues/28390@howardjohn suggested in slack that I need to build it from `istio/proxy` repo, since there is some extensions or istio specific customization on top of the original envoy.

So is it still possible I inject my hack on the envoy?

**Comment by jwillker** [comment]
Was the documentation created somewhere?
