### ISSUE TITLE
Provide end to end example of Metrics, Logging, and Tracing correlation

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#28483]
Grafana has been blogging about correlating metrics, logs, and tracing for quite some time now (see https://grafana.com/blog/2020/10/27/announcing-grafana-tempo-a-massively-scalable-distributed-tracing-system/, among many others). Given Istio provides all 3 of these things, it seems like a good value-add to at the very least provide a sample or blog post on how to set this up with Istio.

I have attempted this with Grafana 7.3 to some limited success. I can deploy Loki and get it scraping Istio pods successfully. 

Logs -> Traces
I can then get links to Jaeger from the logs, but there are a few issues. First, we do not actually log the traceid, just the requestid. The second is you can only do it through "Explore" page, not a panel (see https://github.com/grafana/grafana/issues/28724).

Metrics -> traces 
claims to be in 7.3 from the blog but its not, see https://github.com/grafana/grafana/issues/28725. Maybe 7.4.

Traces -> Logs
Seems like maybe need https://github.com/grafana/agent. Couldn't find any info on this

**Comment by douglas-reid** [comment]
There are a couple of small changes here to link logs and traces. Getting exemplars for metrics<->traces correlation probably takes a bit more doing.

**Comment by rverma-nsl** [comment]
@douglas-reid  can we reopen this

**Comment by rmossuk** [comment]
anyone know if exemplars are possible with istio ?

**Comment by douglas-reid** [comment]
> anyone know if exemplars are possible with istio ?

exemplar support would need to be added
