### ISSUE TITLE
Sample samples/multicluster/expose-istiod-https.yaml fails istioctl analyze

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#28510]
```
Warning [IST0129] (DestinationRule istiod-dr.istio-system) DestinationRule istio-system/istiod-dr in namespace istio-system has TLS mode set to SIMPLE but no caCertificates are set to validate server identity for host: istiod.istio-system.svc.cluster.local at port number:15012
```

Seems like we should not suggest config that triggers a warning

cc @stevenctl @linsun

**Comment by linsun** [comment]
Yes, it is an analyzer bug imho, see https://github.com/istio/istio/issues/27960

**Comment by linsun** [comment]
Actually the msg is changed from error to warning, I think warning is correct because it is commonly to have caCertificates but not needed here.

**Comment by howardjohn** [comment]
I am not sure its not needed here - we are not actually verifying the identity of Istiod. The warning is legit. If someone were to impersonate the Istiod service somehow we have no protection.

**Comment by linsun** [comment]
Should we just configure mtls among ingress gw and istiod?  could that work?

**Comment by howardjohn** [comment]
if you do mtls then istiod will verify the identity as the gateway instead of from the jwt token. Not sure what we should do here.

**Comment by esnible** [comment]
Not an analyzer bug, but a samples bug.  We or @istio/wg-docs-maintainers should fix the sample.

**Comment by esnible** [comment]
Fixed in https://github.com/istio/istio/pull/27976
