### ISSUE TITLE
When using istio to proxy external https requests, applying some AuthorizationPolicy will cause the proxy to fail

### ISSUE THREAD

**Issue by tony-liuliu** [istio/istio#28524]
When using istio to proxy external https requests, applying some AuthorizationPolicy will cause the proxy to fail. I am not sure if this is a bug. But I think this must be a problem, such as the envoy.

The following is my case:
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: www.xxx.com-proxy
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - www.xxx.com
  - port:
      number: 443
      name: tls
      protocol: TLS
    tls:
      mode: PASSTHROUGH
    hosts:
    - www.xxx.com
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: http-www.xxx.com
spec:
  hosts:
  - www.xxx.com
  location: MESH_EXTERNAL
  ports:
  - number: 80
    name: http
    protocol: HTTP
  - number: 443
    name: tls
    protocol: TLS
  resolution: STATIC
  endpoints:
  - address: 100.100.100.100
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: http-www.xxx.com
spec:
  hosts:
  - www.xxx.com
  gateways:
  - www.xxx.com-proxy
  http:
  - route:
    - destination:
        host: www.xxx.com
        port:
          number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: https-www.xxx.com
spec:
  hosts:
  - www.xxx.com
  gateways:
  - www.xxx.com-proxy
  tls:
  - match:
    - sniHosts:
      - www.xxx.com
    route:
    - destination:
        host: www.xxx.com
        port:
          number: 443

When istio uses the above configuration, it can successfully proxy http and https.

Test Results:
[root@daxin-2prod-k8s-21 security]# curl -v -I --resolve www.xxx.com:443:10.253.79.21 https://www.xxx.com:443/dns-api/router/0/        
* Added www.xxx.com:443:10.253.79.21 to DNS cache
* About to connect() to www.xxx.com port 443 (#0)
*   Trying 10.253.79.21...
* Connected to www.xxx.com (10.253.79.21) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
*       subject: CN=*.xxx.com,O="Technology Co., Ltd.",L=HongKong,ST=HongKong,C=CN
*       start date: Nov 05 02:41:05 2018 GMT
*       expire date: Nov 05 02:41:05 2020 GMT
*       common name: *.xxx.com
*       issuer: CN=GlobalSign Organization Validation CA - SHA256 - G2,O=GlobalSign nv-sa,C=BE
> HEAD /dns-api/router/0/ HTTP/1.1
> User-Agent: curl/7.29.0
> Host: www.xxx.com
> Accept: */*
>
< HTTP/1.1 200
HTTP/1.1 200
< Server: envoy
Server: envoy
< Date: Tue, 03 Nov 2020 01:44:51 GMT
Date: Tue, 03 Nov 2020 01:44:51 GMT
< Content-Type: application/json;charset=UTF-8
Content-Type: application/json;charset=UTF-8
< Content-Length: 1908
Content-Length: 1908
< Connection: keep-alive
Connection: keep-alive
< X-Request-ID: 479eb9e7fa28a15284a1ddce24691723
X-Request-ID: 479eb9e7fa28a15284a1ddce24691723

<
* Connection #0 to host www.xxx.com left intact

When the following AuthorizationPolicy configuration is applied in istio-ingressgateway, the https proxy will fail.
[root@daxin-2prod-k8s-21 security]# cat addtoken-kibana.yaml 
apiVersion: "security.istio.io/v1beta1"
kind: "AuthorizationPolicy"
metadata:
  name: addtoken-kibana
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
  action: DENY
  rules:
  - to:
    - operation:
        hosts:
          - "dx-log.ops.tk"
    when:
    - key: request.headers[x-access-token-log]
      notValues: ["vPR7Um8i3jwCGfV20qg0f4AKg7RjJRow"]

When testing again:
[root@daxin-2prod-k8s-21 security]# curl -v -I --resolve www.xxx.com:443:10.253.79.21 https://www.xxx.com:443/dns-api/router/0/               
* Added www.xxx.com:443:10.253.79.21 to DNS cache
* About to connect() to www.xxx.com port 443 (#0)
*   Trying 10.253.79.21...
* Connected to www.cdtpdns.com (10.253.79.21) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* NSS error -5938 (PR_END_OF_FILE_ERROR)
* Encountered end of file
* Closing connection 0
curl: (35) Encountered end of file

Dump the envoy configuration file of ingressgateway, you can see the following configuration.
...... 
  "dynamic_listeners": [
    {
     "name": "0.0.0.0_8443",
     "active_state": {
      "version_info": "2020-09-28T06:14:50Z/204",
      "listener": {
       "@type": "type.googleapis.com/envoy.config.listener.v3.Listener",
       "name": "0.0.0.0_8443",
       "address": {
        "socket_address": {
         "address": "0.0.0.0",
         "port_value": 8443
        }
       },
......
        {
         "filter_chain_match": {
          "server_names": [
           "www.xxx.com"
          ]
         },
         "filters": [
          {
           "name": "envoy.filters.network.rbac",
           "typed_config": {
            "@type": "type.googleapis.com/envoy.extensions.filters.network.rbac.v3.RBAC",
            "rules": {
             "action": "DENY",
             "policies": {
              "ns[istio-system]-policy[addtoken-kibana]-rule[0]": {
               "permissions": [
                {
                 "and_rules": {
                  "rules": [
                   {
                    "any": true
                   }
                  ]
                 }
                }
               ],
               "principals": [
                {
                 "and_ids": {
                  "ids": [
                   {
                    "any": true
                   }
                  ]
                 }
                }
               ]
              }
             }
            },
            "stat_prefix": "tcp."
           }
          },
......
          {
           "name": "envoy.tcp_proxy",
           "typed_config": {
            "@type": "type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy",
            "stat_prefix": "outbound|443||www.xxx.com",
            "cluster": "outbound|443||www.xxx.com",
            "access_log": [
             {
              "name": "envoy.file_access_log",
              "typed_config": {
               "@type": "type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog",
               "path": "/logs/access.log",
               "json_format": {
                "authority": "%REQ(:AUTHORITY)%",
                "bytes_received": "%BYTES_RECEIVED%",
......
                "x_forwarded_for": "%REQ(X-FORWARDED-FOR)%"
               }
              }
             }
            ]
           }
          }
         ]
        },
......

I refer to https://www.envoyproxy.io/docs/envoy/v1.15.0/api-v3/config/rbac/v3/rbac.proto#config-rbac-v3-permission in Envoy for "any:true" about rules the meaning of.This will match all conditions and cause the request to be disabled.

Is it because tls uses the tcp proxy and cannot get the host header in the request, so the permissions rules in envoy.filters.network.rbac are set to "any: true"

k8s v1.16.14
istio 1.7.0 envoy 1.15.0

**Comment by williamaronli** [comment]
@yangminzhu could you take a look thanks

**Comment by yangminzhu** [comment]
> Is it because tls uses the tcp proxy and cannot get the host header in the request, so the permissions rules in envoy.filters.network.rbac are set to "any: true"

@tony-liuliu yes that is exactly the case. To fix this, you can add the workload port (`8080`) of the ingressgateway service to the DENY policy so that it will only applies to the HTTP filter chains.

**Comment by yangminzhu** [comment]
closing as there are no further questions.
