### ISSUE TITLE
Multicluster obsolete options

### ISSUE THREAD

**Issue by mkuligow** [istio/istio#28534]
**Bug description**
During replicated multicluster deployment, i get issue about globalDomainSuffix and includeEnvoyFilter options:

```
[root@localhost]#  istioctl install -f manifests/examples/multicluster/oc-gateways.yml
Error: failed to install manifests: validation errors (use --force to override):
unknown field "globalDomainSuffix" in v1alpha1.MultiClusterConfig
```

[ ] Docs
[X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Installation complete successfully 
**Steps to reproduce the bug**
Run command
```
istioctl install -f manifests/examples/multicluster/values-istio-multicluster-gateways.yaml
```
**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
```
[root@localhost istio]# istioctl version --remote
client version: 1.7.3
control plane version: 1.7.3
data plane version: 1.7.3 (5 proxies)
[root@localhost istio]# kubectl version --short
Client Version: v1.18.2-6+38ac483e736488
Server Version: v1.17.11+vmware.1
[root@localhost istio]#
```
**How was Istio installed?**
With istioctl command
```
istioctl install -f manifests/examples/multicluster/values-istio-multicluster-gateways.yaml
```
**Environment where bug was observed (cloud vendor, OS, etc)**
Linux

**Comment by christianAckman** [comment]
these options were released in 1.7.4
