### ISSUE TITLE
grafana mesh dashboards hardcode /dashboard link without using GF_SERVER_ROOT_URL (setting. appSubUrl)

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#28550]
**Bug description**

https://github.com/istio/istio/blob/master/manifests/addons/dashboards/istio-mesh-dashboard.json#L1055

So if you try to re-root grafana away from / to say /grafana then the links are broken

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Clicking on links would have configured prefix

**Steps to reproduce the bug**

kubectl -n istio-system set env deployment/grafana GF_SERVER_ROOT_URL=/grafana/
istioctl dashboard grafana

works on localhost:port/grafana except when clicking on istio mesh service it uses /dashboard per code above

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

1.7.4

**How was Istio installed?**
istioctl install

**Environment where bug was observed (cloud vendor, OS, etc)**
n/a

**Comment by carolynhu** [comment]
@ldemailly please reference this: https://github.com/istio/istio/issues/26544

**Comment by ldemailly** [comment]
we do have GF_SERVER_SERVE_FROM_SUB_PATH true

**Comment by ldemailly** [comment]
everything else is working it’s just the mesh dashboard but i will triple check
