### ISSUE TITLE
defaultVirtualServiceExportTo does not support specified namespace (inconsistency documentation and implementation)

### ISSUE THREAD

**Issue by jijiechen** [istio/istio#28558]
**Bug description**
Similar to #17466 the documentation on the field of `defaultVirtualServiceExportTo` was described inconsistently in documentation and its implementation. I didn't check other related fields like `defaultServiceExportTo ` and `defaultDestinationRuleExportTo `, probably it's the same situation.

Docs at https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig
[The code in push_context.go](https://github.com/istio/istio/blob/master/pilot/pkg/model/push_context.go#L1174) said it only honors `.` and `*`.
```go
// No exportTo in virtualService. Use the global default
// We only honor ., *
if ps.exportToDefaults.virtualService[visibility.Private] {
    if _, f := ps.virtualServiceIndex.privateByNamespaceAndGateway[ns]; !f {
        ps.virtualServiceIndex.privateByNamespaceAndGateway[ns] = map[string][]config.Config{}
    }
    // add to local namespace only
    for _, gw := range gwNames {
        ps.virtualServiceIndex.privateByNamespaceAndGateway[ns][gw] = append(ps.virtualServiceIndex.privateByNamespaceAndGateway[ns][gw], virtualService)
    }
} else if ps.exportToDefaults.virtualService[visibility.Public] {
    for _, gw := range gwNames {
        ps.virtualServiceIndex.publicByGateway[gw] = append(ps.virtualServiceIndex.publicByGateway[gw], virtualService)
    }
}
```

My scenario is I want to keep the services exportable to `istio-system` and the namespace in which it is defined and keep them invisible to other namespaces.

[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

`defaultVirtualServiceExportTo` supports a list of specified namespaces or correct the documentation to keep it consistent.

**Steps to reproduce the bug**

1. Install a istio cluster
2. Update `configmap/istio` to set `meshConfig.defaultVirtualServiceExportTo` to `[".", "istio-system"]`
3. Deploy the Bookinfo sample application
4. Try to access the application using the configured route (failed with 404 or 503-NR) or check the proxy config in the ingress gateway pod (no bookinfo virtual services).

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

```bash
$ istioctl version --remote
client version: 1.7.0
control plane version: 1.7.0
data plane version: 1.7.0 (32 proxies)

$ kubectl version --short
Client Version: v1.16.6-beta.0
Server Version: v1.16.9
```

**How was Istio installed?**
Installed using `istioctl` command line tool without special customization.

**Environment where bug was observed (cloud vendor, OS, etc)**

Generic Kubernetes environment.

**Comment by jijiechen** [comment]
lifecycle/staleproof

**Comment by jijiechen** [comment]
Not stale.
Nobody was on this thread and the problem had not been addressed. It's still impacting users.

**Comment by seanwelsh** [comment]
This problem still exists.

**Comment by sedflix** [comment]
+1
