### ISSUE TITLE
DestinationRule Subset Name must be DNS1123Label

### ISSUE THREAD

**Issue by zhengzepeng** [istio/istio#28567]
DestinationRule Subset Name must be
`  [a-zA-Z0-9](?:[-a-zA-Z0-9]*[a-zA-Z0-9])?`
But in my scene ，we use x.x.x to define the version，like 1.0.0，so can it support "." ?

**Comment by zhengzepeng** [comment]
can use this one to validate the destinationrule subset name?
```
	// Using kubernetes requirement, a valid key must be a non-empty string consist
	// of alphanumeric characters, '-', '_' or '.', and must start and end with an
	// alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345'
	qualifiedNameFmt = "(?:[A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]"
```

**Comment by carolynhu** [comment]
offline discussed with @howardjohn , we'd not support this. As we have supported the existing subset name regex matches with our stable API for years. It's hard for us to make a change there to only make it available for your single case. I'm going to close this request, thanks!

**Comment by zhengzepeng** [comment]
> offline discussed with @howardjohn , we'd not support this. As we have supported the existing subset name regex matches with our stable API for years. It's hard for us to make a change there to only make it available for your single case. I'm going to close this request, thanks!

Roger that. I understand. Thank you for reply
