### ISSUE TITLE
Backup Requests With Cross-Server Cancellation (Feature Request)

### ISSUE THREAD

**Issue by jacktuck** [istio/istio#2857]
https://youtu.be/1-3Ahy7Fxsc?t=1207

Backup requests are the idea of sending requests out to multiple replicas, but in a particular way. Here’s the example for a read operation for a distributed file system client:

send request to first replica
wait 2 ms, and send to second replica
servers cancel request on other replica when starting read
A request could wait in a queue stuck behind an expensive query or a packet could be dropped, so if a reply is not returned quickly other replicas are tried. Responses come back faster if requests sit in multiple queues.

Cancellation reduces the frequency at which redundant work occurs.

You might think this is just a lot of extra traffic, but remember, the goal is to squeeze down the 99th percentile distribution, so the backup requests, even with what seems like a long wait time really bring down the tail latency and standard deviation. Requests in the 99th percentile take so long that the wait time is short in comparison.

Bigtable, for example, used backup requests after two milliseconds, which dramatically dropped the 99th percentile by 43 percent on an idle system. With a loaded system the reduction was 38 percent with only one percent extra disk seeks. Backups requests with cancellations gives the same distribution as an unloaded cluster. 

With these latency tolerance techniques you are taking a loaded cluster with high variability and making it perform like an unloaded cluster.

Source: http://highscalability.com/blog/2012/6/18/google-on-latency-tolerant-systems-making-a-predictable-whol.html

**Comment by rshriram** [comment]
This should be filed in Envoy as this abstraction belongs in the dataplane. Building upon the mirroring infrastructure, and incorporating a first response accepted logic. cc @htuch @mattklein123

**Comment by mattklein123** [comment]
In Envoy I've been calling this feature "request racing." I has come up over the years  but has never been implemented.

**Comment by jacktuck** [comment]
I will file under envoy, thanks

**Comment by rakelkar** [comment]
Can you link the related issue(s) you created?

**Comment by jacktuck** [comment]
https://github.com/envoyproxy/envoy/issues/2784
