### ISSUE TITLE
Certificate Automatic Rotation

### ISSUE THREAD

**Issue by sandeep1699** [istio/istio#28575]
We are plugging in existing CA certificates as mentioned in this https://istio.io/latest/docs/tasks/security/cert-management/plugin-ca-cert/
Does Root CA(root-cert.pem) , Intermediate CA (ca-cert.pem) and Workload certificates will be rotated automatically upon expiration?  Will there be any downtime during this process?

**Comment by williamaronli** [comment]
the sds agent will be responsible for cert rotation. @myidpt @shankgan could you clarify whether this plugin CA will use the sds agent?

**Comment by shankgan** [comment]
The workload certificates are always rotated - this is handled by the Istio-agent. However, the plugged in CA Root CA cert & CA Intermediate cert don't appear to be automatically rotated by Istio. It is the user's responsibility to rotate them.

**Comment by howardjohn** [comment]
Closing as this is answered. Thanks.
