### ISSUE TITLE
Docker Hub rate limiting impact on istio-proxy image pulls

### ISSUE THREAD

**Issue by rvennam** [istio/istio#28581]
https://www.docker.com/blog/what-you-need-to-know-about-upcoming-docker-hub-rate-limiting/
"anonymous users are limited to 100 container pulls per six hours"

k get pod sleep-8f795f47d-pmm7v -n httpbin -o yaml shows:
```
    image: docker.io/istio/proxyv2:1.7.3
    imagePullPolicy: Always
    name: istio-proxy
...
    image: docker.io/istio/proxyv2:1.7.3
    imagePullPolicy: Always
    name: istio-init
```

Does this mean it's possible to hit this limit?

[ ] Docs
[ X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ X] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
client version: 1.7.0
control plane version: 1.7.3
data plane version: 1.7.3 (4 proxies)

**How was Istio installed?**
istioctl install

**Environment where bug was observed (cloud vendor, OS, etc)**
IKS

cc: @sdake

**Comment by howardjohn** [comment]
> Does this mean it's possible to hit this limit?


Certainly. We are tracking this in https://github.com/istio/istio/issues/28031. tl;dr we are mirroring to gcr.io/istio-release and open to mirror to any other registries the community demands/will setup and support

**Comment by rvennam** [comment]
To fix in 1.7, changing the image registry in a patch release seems scary as access to other registries might be blocked. Can the problem be alleviated by removing imagePullPolicy: Always ?

**Comment by howardjohn** [comment]
We have no plans to change the default image, users are free to customize it as easily as `--set hub=foo`. I wouldn't recommend any serious users use dockerhub in production anyways (for Istio or anything), so hopefully users are already using their own registries.

I am not sure if `imagePullPolicy: Always` impacts it or not. It depends how dockerhub counts things. "Always" does not actually download all the bits afaik, but will pull the manifest

**Comment by ericvn** [comment]
I do believe `imagePullPolicy: Always` will have a impact in that the manifest pull does count. Since we have a tag, and don't reuse the tag on pushes, a change here shouldn't have a negative impact on the user and would help with the rate limiting.
