### ISSUE TITLE
Sort fields in the various profile yamls

### ISSUE THREAD

**Issue by ceastman-ibm** [istio/istio#28585]
**Describe the feature request**
Please sort the various fields in the manifets/profiles/*. yamls

**Describe alternatives you've considered**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Additional context**
By having the various profile yamls sorted will make it easier to compare the profiles between versions of istio.

**Comment by esnible** [comment]
@istio/wg-environments-maintainers Can you triage this?

**Comment by ericvn** [comment]
Tong will take a look.

**Comment by litong01** [comment]
@ceastman-ibm I've checked the manifest generation tool and its output, its output has been sort by kind, then name. For example.

The very first resource is authorizationpolicies.security.istio.io, its kind is CustomResourceDefinition, then the second is destinationrules.networking.istio.io, and its kind is also CustomResourceDefinition, then go on, so the actual order is by kind then name. Hope that is sufficient for what you need. To compare different profiles, use the different profile as input to generate the manifest, then do the compare as you need.

For example:

```
istioctl manifest generate --set profile=demo

vs.

istioctl manifest generate --set profile=default
```
These two will produce two different yaml files with resources sorted by kind , then name.

**Comment by ostromart** [comment]
IIUC, the question seems to be about sorting fields inside resources rather than resource ordering.  We'd have to provide a mode which parses each objects and sorts it (actually this will happen if you just marshal and unmarshal the object).
