### ISSUE TITLE
meshConfig.accessLogFormat does not allow nested JSON

### ISSUE THREAD

**Issue by max0ne** [istio/istio#28597]
**Bug description**
Setting a JSON string with nested JSON structure to `meshConfig.accessLogFormat` cause Pilot fail to parse the JSON string, and fallback to the default log format.

Something like `{"foo":"bar"}` works for `meshConfig.accessLogFormat`, but something like `{ "foo": "bar", "foo2": {} }` would result in envoy access log fallback to the default format.

My envoy access logs are shipped to GCP StackDriver, so it'll be nice to have fields in the access log JSON conform to [Stackdriver log convension](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry#httprequest) by nesting the fields under `httpRequest` key.

I looked into the source code and found it's caused by ⬇️, where the `meshConfig.accessLogFormat` is unmarshalled into a `map[string]string` object:
https://github.com/istio/istio/blob/b647ea46e297c2f540bf91fe1dec83f77197f2ac/pilot/pkg/networking/core/v1alpha3/accesslog.go#L176-L180

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Expect `meshConfig.accessLogFormat` to allow nested JSON format, similar to Envoy.

**Steps to reproduce the bug**
Set `{"foo": {}}` to `meshConfig.accessLogFormat` cause access logs to fallback to default format.

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
Found in both 1.6.0 and on latest master.

**How was Istio installed?**
istio-operator

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

**Comment by howardjohn** [comment]
cc @douglas-reid
