### ISSUE TITLE
Consolidate echo instances used by security e2e tests 

### ISSUE THREAD

**Issue by jtrbs** [istio/istio#28599]
**Describe the feature request**

**Describe alternatives you've considered**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

After security tests are converted into multicluster support and echo setups are consolidated, namespaces instances and echo instances have increased. This may increase the test time. Please consolidate the echos and reuse echos as much as possible if required by reducing test time.

**Comment by stevenctl** [comment]
Was this issue closed appropriately? AFAICT we don't need 12 workloads in the security suites. passthrough_filter_chain test can be simplified along with others.

**Comment by jtrbs** [comment]
It was closed at that time as a duplicate of https://github.com/istio/istio/issues/29475. But sure we can make break down passthrough_filter_chain test's yaml file and deploy different yaml for different test case on the same echo.
