### ISSUE TITLE
Provide a load test tool without running real pods

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#28606]
**Context**

Currently if we want to do scalability test, we need to set run real pods in the cluster, however usually we donot have so much resource, no such large cluster.

**Describe the feature request**

Provide a tool allowing simulate/run number of sidecars from within a process, in k8s the `kubemark` provides a similar capability

**Comment by howardjohn** [comment]
I have been working on this in https://github.com/howardjohn/pilot-load. It mostly works, let me know if the docs need improvements

**Comment by hzxuzhonghu** [comment]
Cool. We will try that.

**Comment by howardjohn** [comment]
Fixed by https://github.com/istio/istio/issues/28606#issuecomment-722446375 I think
