### ISSUE TITLE
Prometheus traget kubernetes-service-endpoints  error "server returned HTTP status 404 Not Found"

### ISSUE THREAD

**Issue by zhangxingdeppon** [istio/istio#28605]
**Bug description**

Hi team, I have met a problem when I use istio 1.6.12, that Istio addon prometheus have been auto injected istio-proxy sidecar, and foud the prometheus traget kubernetes-service-endpoints happened error `server returned HTTP status 404 Not Found`, is it a bug? ,can you give me some ideas?  thanks.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
the prometheus traget kubernetes-service-endpoints happened error `server returned HTTP status 404 Not Found`, and Istio prometheus have been injected the istio-proxy.
**Steps to reproduce the bug**
the 1th step:
<pre><code>istioctl manifest generate --set profile=demo --set values.global.jwtPolicy=first-party-jwt  > istio-demo-3.yaml</code></pre>
the 2nd step:
<pre><code>kubectl apply -f istio-demo-3.yaml</code></pre>
the 3rd step:
<pre><code>istioctl  verify-install -f istio-demo-3.yaml</code></pre>

finally, you will find the prometheus have been added sidecar `istio-proxy `.
![image](https://user-images.githubusercontent.com/16789841/98190433-fa795600-1f51-11eb-966a-79463c0bfbca.png)

in addition, I have checked the prometheus yaml, and found it have added annotation `sidecar.istio.io/inject: "false"`.
![image](https://user-images.githubusercontent.com/16789841/98190711-94d99980-1f52-11eb-825b-5d52919ab7c8.png)

[prometheus-deployment.yaml.txt](https://github.com/istio/istio/files/5491613/prometheus-deployment.yaml.txt)

I also have saw the prometheus web UI and found that kubernetes-service-endpoints metrics 15090 `server returned HTTP status 404 Not Found` :
![image](https://user-images.githubusercontent.com/16789841/98192924-fa2f8980-1f56-11eb-987e-6039e5b75bb6.png)

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
<pre><code>
[root@ecs-5274-0318468 istio]# istioctl version --remote
client version: 1.6.12
control plane version: 1.6.12
data plane version: 1.6.12 (12 proxies)
[root@ecs-5274-0318468 istio]# kubectl version --short 
Client Version: v1.18.8
Server Version: v1.18.6
</code></pre>
**How was Istio installed?**
the 1th step:
<pre><code>istioctl manifest generate --set profile=demo --set values.global.jwtPolicy=first-party-jwt  > istio-demo-3.yaml</code></pre>
the 2nd step:
<pre><code>kubectl apply -f istio-demo-3.yaml</code></pre>
**Environment where bug was observed (cloud vendor, OS, etc)**
<pre><code>
[root@ecs-5274-0318468 istio]# uname -a
Linux ecs-5274-0318468.novalocal 3.10.0-957.10.1.el7.x86_64 #1 SMP Mon Mar 18 15:06:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
[root@ecs-5274-0318468 istio]# cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core
</code></pre>

**Comment by zhangxingdeppon** [comment]
@howardjohn what do you think?

**Comment by howardjohn** [comment]
I don't see how it can happen. we look for `[__meta_kubernetes_service_annotation_prometheus_io_scrape=true]` in the config... can you ensure this annotation is not present on the prometheus pod/service/endpoint? when looking at the manifest generate I do not see it, but not sure how this could happen otherwise

**Comment by zhangxingdeppon** [comment]
@howardjohn yes, I saw `[__meta_kubernetes_service_annotation_prometheus_io_scrape=true]` in prometheus svc, see below:
<pre><code>
[root@ecs-5274-0318468 ~]# kubectl get  svc prometheus -n istio-system  -o yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"prometheus.io/scrape":"true"},"labels":{"app":"prometheus","install.operator.istio.io/owning-resource":"installed-state","install.operator.istio.io/owning-resource-namespace":"istio-system","operator.istio.io/component":"AddonComponents","operator.istio.io/managed":"Reconcile","operator.istio.io/version":"1.6.12","release":"istio"},"name":"prometheus","namespace":"istio-system"},"spec":{"ports":[{"name":"http-prometheus","port":9090,"protocol":"TCP"}],"selector":{"app":"prometheus"}}}
    prometheus.io/scrape: "true"
  creationTimestamp: "2020-11-03T07:38:29Z"
  labels:
    app: prometheus
    install.operator.istio.io/owning-resource: installed-state
    install.operator.istio.io/owning-resource-namespace: istio-system
    operator.istio.io/component: AddonComponents
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.6.12
    release: istio
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:prometheus.io/scrape: {}
        f:labels:
          .: {}
          f:app: {}
          f:release: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":9090,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl
    operation: Update
    time: "2020-11-03T11:31:27Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          f:install.operator.istio.io/owning-resource: {}
          f:install.operator.istio.io/owning-resource-namespace: {}
          f:operator.istio.io/component: {}
          f:operator.istio.io/managed: {}
          f:operator.istio.io/version: {}
    manager: istioctl
    operation: Update
    time: "2020-11-04T02:20:16Z"
  name: prometheus
  namespace: istio-system
  resourceVersion: "22092249"
  selfLink: /api/v1/namespaces/istio-system/services/prometheus
  uid: 428cc9e9-1750-4c36-9257-5fa041180e3d
spec:
  clusterIP: 10.97.253.151
  externalTrafficPolicy: Cluster
  ports:
  - name: http-prometheus
    nodePort: 32525
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
</code></pre>

but when scraped the address `http://10.248.246.21:15090/metrics`,  it will happen `server returned HTTP status 404 Not Found`, and if I change the address  `http://10.248.246.21:15090/metrics` to ``http://10.248.246.21:15090/stats/prometheus``, the request response is okay,  Is the configuration correct?


<pre><code>
[root@ecs-5274-0318468 ~]# kubectl get pod -n istio-system -o wide 
NAME                                    READY   STATUS    RESTARTS   AGE     IP               NODE                         NOMINATED NODE   READINESS GATES
grafana-7dbb4c4d57-ft28f                1/1     Running   0          5d17h   10.248.8.223     ecs-5274-0318495.novalocal   <none>           <none>
istio-egressgateway-79bc5897d9-gztq8    1/1     Running   0          5d17h   10.248.8.222     ecs-5274-0318495.novalocal   <none>           <none>
istio-ingressgateway-794bc8cd66-2c8ft   1/1     Running   0          4d23h   10.248.110.204   ecs-5274-0318428.novalocal   <none>           <none>
istio-tracing-6669c66b87-vwlmg          1/1     Running   0          5d17h   10.248.8.219     ecs-5274-0318495.novalocal   <none>           <none>
istiod-84645b6577-dplfd                 1/1     Running   0          4d23h   10.248.110.206   ecs-5274-0318428.novalocal   <none>           <none>
istiod-84645b6577-m247g                 1/1     Running   0          4d23h   10.248.8.252     ecs-5274-0318495.novalocal   <none>           <none>
kiali-5c96cd5d68-tmdzm                  1/1     Running   0          5d17h   10.248.8.233     ecs-5274-0318495.novalocal   <none>           <none>
prometheus-6dbdc4769f-sdzl2             2/2     Running   0          4d23h   10.248.246.21    ecs-5274-0318468.novalocal   <none>           <none>

/prometheus $ wget http://10.248.246.21:15090/metrics
Connecting to 10.248.246.21:15090 (10.248.246.21:15090)
wget: server returned error: HTTP/1.1 404 Not Found

/prometheus $ wget http://10.248.246.21:15090/stats/prometheus
Connecting to 10.248.246.21:15090 (10.248.246.21:15090)
saving to 'prometheus'
prometheus           100% |*************************************************************************************************************************************************************************************************| 30326  0:00:00 ETA
'prometheus' saved
</code></pre>

**Comment by jp-chl** [comment]
Hi,
Is there any workaround for this? I have the same problem, i.e., "metrics" endpoints is not working but "/stats/prometheus" does.

Thanks in advance
