### ISSUE TITLE
Istio 1.8.0-alpha.2 upgrade on openshift - ingressgateway not ready

### ISSUE THREAD

**Issue by ceastman-ibm** [istio/istio#28615]
**Bug description**

istiod has repeated warnings in its log:
[istiod-656fd9fbc6-zqr9c] {
  "level": "warn",
  "time": "2020-11-05T14:38:10.956150Z",
  "scope": "ads",
  "msg": "ADS:LDS: ACK ERROR sidecar~172.30.49.20~mdms-77f85596bf-rdczv.devtest~devtest.svc.cluster.local-930 Internal:Proto constraint validation failed (ListenerValidationError.FilterChains[i]: [\"embedded message failed validation\"] | caused by FilterChainValidationError.Filters[i]: [\"embedded message failed validation\"] | caused by FilterValidationError.Name: [\"value length must be at least \" '\\x01' \" runes\"]): name: \"10.190.187.39_9100\"\naddress {\n  socket_address {\n    address: \"10.190.187.39\"\n    port_value: 9100\n  }\n}\nfilter_chains {\n  filter_chain_match {\n    server_names: \"node-exporter.openshift-monitoring.svc.cluster.local\"\n  }\n  filters {\n  }\n  filters {\n    name: \"envoy.filters.network.tcp_proxy\"\n    typed_config {\n      [type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy] {\n        stat_prefix: \"outbound|9100||node-exporter.openshift-monitoring.svc.cluster.local\"\n        cluster: \"outbound|9100||node-exporter.openshift-monitoring.svc.cluster.local\"\n      }\n    }\n  }\n}\ndeprecated_v1 {\n  bind_to_port {\n  }\n}\nlistener_filters {\n  name: \"envoy.filters.listener.tls_inspector\"\n  typed_config {\n    [type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector] {\n    }\n  }\n}\ntraffic_direction: OUTBOUND\ndefault_filter_chain {\n  filter_chain_match {\n  }\n  filters {\n    name: \"envoy.filters.network.tcp_proxy\"\n    typed_config {\n      [type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy] {\n        stat_prefix: \"PassthroughCluster\"\n        cluster: \"PassthroughCluster\"\n      }\n    }\n  }\n  name: \"PassthroughFilterChain\"\n}\n"
} 

ingressgateway pods have repeated logs like:
[istio-ingressgateway-54978fcbd9-kdgbj] {"level":"warn","time":"2020-11-05T14:37:56.502275Z","msg":"Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 71 successful, 0 rejected; lds updates: 0 successful, 70 rejected"} 

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**
For the ingressgateway to be ready and istiod not to have warnings

**Steps to reproduce the bug**
Take a working istio 1.7.4 install on an openshift cluster and upgrade to 1.8.0-alpha.2

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
./istioctl version
client version: 1.8.0-alpha.2
control plane version: 1.8.0-alpha.2
data plane version: 1.8.0-alpha.2 (25 proxies), 1.7.4 (95 proxies), 1.7.3 (13 proxies)

 kubectl version --short
Client Version: v1.17.7
Server Version: v1.17.1+45f8ddb

oc version
Client Version: 4.4.0-202004210425-2576e48
Server Version: 4.4.27
Kubernetes Version: v1.17.1+45f8ddb

**How was Istio installed?**
Manually - istioctl install -f config.yaml

**Environment where bug was observed (cloud vendor, OS, etc)**
IBM Cloud
Openshift cluster

**Comment by howardjohn** [comment]
I am fairly sure this is fixed, see https://github.com/istio/istio/issues/28616#issuecomment-722448986. Please try https://gcsweb.istio.io/gcs/istio-build/dev/1.8-alpha.09df30801a3b1bc4a6c3e2dde6fb7a633003741f. If that doesn't work please let us know, since this would be a release blocker. thanks

**Comment by ceastman-ibm** [comment]
@howardjohn I don't believe i did a multi-cluster install. Is that a setting in my config.yaml that i used to run the istioctl upgrade with?

**Comment by howardjohn** [comment]
I don't think the multicluster part of that issue is relevant to the issue

**Comment by ceastman-ibm** [comment]
I am getting this error trying to run istioctl ugprade -f confg.yaml: with the new istioctl i downloaded.

Error: failed to read the current Istio version, error: different versions of Istio components found: [egressgateway pod - istio-egressgateway-77bdb7b84c-g95sl - version: 1.8.0 egressgateway pod - istio-egressgateway-77bdb7b84c-r2ldk - version: 1.8.0 ingressgateway pod - istio-ingressgateway-54978fcbd9-jdd66 - version: 1.8.0 ingressgateway pod - istio-ingressgateway-54978fcbd9-kdgbj - version: 1.8.0 ingressgateway pod - istio-ingressgateway-686c787fb4-rmdh4 - version: 1.7.4 ingressgateway pod - istio-ingressgateway-686c787fb4-wp79z - version: 1.7.4 pilot pod - istiod-656fd9fbc6-6mrkx - version: 1.8.0 pilot pod - istiod-656fd9fbc6-8ghfq - version: 1.8.0 pilot pod - istiod-656fd9fbc6-qpknj - version: 1.8.0 pilot pod - istiod-656fd9fbc6-rqjfh - version: 1.8.0 pilot pod - istiod-656fd9fbc6-zqr9c - version: 1.8.0]

**Comment by ceastman-ibm** [comment]
and i checked my config.yaml and the only entry i see has this:
      multiCluster:
        clusterName: ""
        enabled: false

**Comment by ceastman-ibm** [comment]
ah found i can use the undocumented --force to skip that different version warning.

**Comment by ceastman-ibm** [comment]
with this new istioctl, the ingressgateway are still not starting. I see this in their log files:

[ingress_log.txt.gz](https://github.com/istio/istio/files/5495861/ingress_log.txt.gz)

**Comment by richardwxn** [comment]
Can you try to do a clean reinstallation with the new istioctl build?(removing the control plane resources and also CRD must be removed)

**Comment by ceastman-ibm** [comment]
@richardwxn I upgraded from a work 1.7.4 istio install. i also deleted all the envoyfilters that i installed. the following are the only envoyfilters in place:

kubectl get envoyfilter --all-namespaces
NAMESPACE      NAME                        AGE
istio-system   metadata-exchange-1.6       4d1h
istio-system   metadata-exchange-1.7       4d1h
istio-system   metadata-exchange-1.8       4d21h
istio-system   stats-filter-1.6            4d1h
istio-system   stats-filter-1.7            4d1h
istio-system   stats-filter-1.8            4d21h
istio-system   tcp-metadata-exchange-1.6   4d1h
istio-system   tcp-metadata-exchange-1.7   4d1h
istio-system   tcp-metadata-exchange-1.8   4d21h
istio-system   tcp-stats-filter-1.6        4d1h
istio-system   tcp-stats-filter-1.7        4d1h
istio-system   tcp-stats-filter-1.8        4d21h

**Comment by ceastman-ibm** [comment]
@richardwxn How do you "deleting the existing CRD and removing the control plane resources"?
