### ISSUE TITLE
eastwest gateway fails to start 

### ISSUE THREAD

**Issue by irisdingbj** [istio/istio#28611]
following guide in https://preliminary.istio.io/latest/docs/setup/install/multicluster/multi-primary_multi-network/

the eastwest gateway can not be started due to the required mount `istio-token` does not exist.

**Comment by irisdingbj** [comment]
This is because my cluster does not support 3rd party jwt , but `istioctl manifest generate` will not detect this.

**Comment by hzxuzhonghu** [comment]
FYI https://github.com/istio/istio/issues/28455
