### ISSUE TITLE
Test Framework: enhance eastwest gw installation option to inherit the same install setting with cluster 

### ISSUE THREAD

**Issue by irisdingbj** [istio/istio#28647]
Look at the  pilot integration test failures in #28296 and found out

previously we will generate  install manifest for eastwest gw and then apply them.   Since we only check whether the pod is in running status 
 https://github.com/istio/istio/blob/master/pkg/test/framework/components/istio/eastwest.go#L111  this hides the fact that the eastewst gateway pod fails to connect the istiod in some cases (eg,  for revision test cases, istiod is on `istiod-stable.x.x` while the eastwest gw is still connecting via `isitod.x.x`)

After the  change in #28296  to use `istioctl install` directly to install eastwest gw, the  connection failure is exposed out and related test are marked as failures.

So we either :

1.  enhance eastwest gw installation option in our test framework to let it inherit the same install setting with cluster, like revision, etc.
2.  do not install eastwest gw when we are under single cluster test.

@stevenctl @nmittler  @linsun

**Comment by irisdingbj** [comment]
cc @howardjohn

**Comment by stevenctl** [comment]
https://github.com/istio/istio/pull/28657

**Comment by stevenctl** [comment]
The above PR doesn't bring over all install options, only revision for now to avoid enabling components we don't want to include. It also allows users to specify revision with a flag to the gen-eastwest script.

**Comment by linsun** [comment]
Thank you @irisdingbj for the analysis!
