### ISSUE TITLE
Intermittent ECONNRESET

### ISSUE THREAD

**Issue by kody-abe** [istio/istio#28653]
**Bug description**

Our applications that have an attached sidecar see intermittent ECONNRESET to external services. We don't see this with calls to other services within the cluster, specifically those with VirtualService entries.

```
{
    "cause": {
        "code": "ECONNRESET"
    },
    "error": {
        "code": "ECONNRESET"
    },
    "options": {
        "method": "GET",
        "uri": "[REDACTED]",
        "qs": {[REDACTED]},
        "headers": {[REDACTED]},
        "json": true,
        "simple": true,
        "redirectMax": 5
    }
}
```

We are utilizing keepAlive. When we remove the sidecar injection on the pod and redeploy, the issue does not happen. It is also worth noting, that we see that the number of ECONNRESETS seems to coincide with traffic load. The more traffic load we have incoming to the cluster, in turn resulting in more calls to external services, we see increased ECONNRESETs.

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

```
istioctl version --remote
client version: 1.6.5
control plane version: 1.6.5
data plane version: 1.6.5 (173 proxies)
```

```
kubectl version --short
Client Version: v1.18.2
Server Version: v1.15.11-eks-065dce
```

**How was Istio installed?**

```
istioctl install \
                --set hub=gcr.io/istio-release \
                --set meshConfig.enablePrometheusMerge=true \
                --set values.gateways.istio-ingressgateway.enabled=true \
                --set values.gateways.istio-ingressgateway.type=NodePort \
                --set values.gateways.istio-ingressgateway.autoscaleEnabled=false \
                --set values.gateways.istio-ingressgateway.replicaCount=4 \
                --set values.gateways.istio-egressgateway.enabled=true \
                --set values.kiali.enabled=true \
                --set values.kiali.dashboard.jaegerURL=http://jaeger-query:16686 \
                --set values.kiali.dashboard.grafanaURL=http://grafana:3000 \
                --set values.global.tracer.zipkin.address=jaeger-collector.istio-system:9411 \
                --set values.kiali.prometheusAddr=[REDACTED] \
                --set values.prometheus.enabled=false \
                --set values.grafana.enabled=false \
                --set values.pilot.traceSampling=0 \
                --set values.pilot.replicaCount=2 \
                --set values.pilot.autoscaleMin=2
```

**Environment where bug was observed (cloud vendor, OS, etc)**

AWS EKS

**Comment by saswata1989** [comment]
We are also facing the same issue with Node app v12 and istio version 1.5 with kubernetes version 1.15.6

**Comment by kody-abe** [comment]
The applications we have noticed this behavior with are also Node.js - Not sure if a correlation or a coincidence. I am attempting to do some more testing to understand what the cause is, but I am going to need an Istio member to chime in here on what on the Istio side could be the culprit.

**Comment by saswata1989** [comment]
We have tried lot of avenues we reduced it a bit but its still there.

1. tweaked the below kernel param
- name: net.ipv4.tcp_keepalive_intvl
            value: "15"
          - name: net.ipv4.tcp_keepalive_probes
            value: "5"
          - name: net.ipv4.tcp_keepalive_time
            value: "300"
          - name: net.ipv4.ip_local_port_range
            value: "6144 65535"
          - name: net.core.somaxconn
            value: "65535"
          - name: net.netfilter.nf_conntrack_tcp_be_liberal
            value: "1"
2. add the IP table rule in kubernetes: iptables -I INPUT -m conntrack --ctstate INVALID -j DROP
3. Disabled Istio MTLS.
4. we have added keep alive config to the node application. 
We have reduced it with the above config.

Adding Service Entry, Virtual Service and destination rule for the external service calls aggravate the problem.

For us this is happening for the https endpoints.

**Comment by kody-abe** [comment]
@howardjohn Do you have any ideas here?
