### ISSUE TITLE
Grpc traffic changed to TCP traffic

### ISSUE THREAD

**Issue by AEGQ** [istio/istio#28651]
**Version:** 
istio 1.6.7 kubernetes 1.16

**Call relationship：**
service A (grpc) ===Unary RPCs===>> service B (grpc) 

**Grpc traffic changed to TCP traffic ：（Figure below is service B ）**
![image](https://user-images.githubusercontent.com/16302289/98372567-ed0abb80-2078-11eb-87f1-780c321e7467.png)

**Figure below is service A** 
![image](https://user-images.githubusercontent.com/16302289/98443339-93bc8e00-2145-11eb-92af-a7be77c12548.png)

**istioctl ps** 
ALL SYNCED

**istio-proxy**
No exception information

### **Question：**

Grpc traffic changed to TCP traffic , Is there anything I can investigate to locate this problem, thanks  :)

**Comment by howardjohn** [comment]
was there anything on your side that changed? Config, istio version, etc?

**Comment by AEGQ** [comment]
I found that the service code has a special strategy when the traffic peaks (change header or something).
I will close this issue because it appears to be a problem with the service code not istio.
