### ISSUE TITLE
Mesh expansion using wrong ISTIO_VERSION

### ISSUE THREAD

**Issue by tobiaskohlbau** [istio/istio#28654]
**Bug description**

Istio sidecars deployed on virtual machines report for e.g. version _1.7.0_ instead of the installed version _1.7.4_. I've tracked down that the issue is caused by _ISTIO_META_ISTIO_VERSION_ being hardcoded into the shell scrip and bumped only on major releasest:

https://github.com/istio/istio/blob/4ce531ff1823a3abb9f42fa9d35523b0436e2d04/tools/packaging/common/istio-start.sh#L24

I would assume, that similar to the docker builds, the correct version number should be injected during build time.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[x] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

See the matching version as sidecars deployed within the cluster.

**Steps to reproduce the bug**

Installing for e.g. the debian packet on VM and join the istio service mesh. After joining the sidecars on virtual machines report the latest major version instead of the current installed version.

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

client version: 1.7.4
control plane version: 1.7.4
data plane version: 1.7.4 (15 proxies), 1.7.0 (6 proxies)

**How was Istio installed?**
`istioctl operator init`

**Comment by zufardhiyaulhaq** [comment]
@tobiaskohlbau this documentation clearly said using 1.7.4 https://istio.io/latest/docs/setup/install/virtual-machine/
can you point me which documentation that using `istio-start.sh`?

**Comment by Monkeyanator** [comment]
From checking around it looks like our [systemd entrypoint](https://github.com/istio/istio/blob/master/tools/packaging/common/istio.service) is `istio-start.sh`, which indeed remains pointed at the `1.x.0` version across all patches. Not sure if this is intended

**Comment by tobiaskohlbau** [comment]
Yes @Monkeyanator is right. The systemd entrypoint uses the `istio-start.sh` which I referenced above to initialize the system and run the `pilot-agent proxy` command. I'm not sure if this is this is intended but I would suggest that this should not be intended. It could confuse users to get different versions reported through for e.g. `istioctl proxy-status` for in cluster and VM nodes. Another option could be to document this behavior within the [VM installation guide](https://istio.io/latest/docs/setup/install/virtual-machine/).

**Comment by brian-avery** [comment]
@howardjohn doesn't this variable have special meaning in the bootstrap process? 

@istio/wg-user-experience-maintainers Why are we using this to report the version of Istio on VMs? Should we be updating these on patch releases?

**Comment by howardjohn** [comment]
The version is used but Pilot only reads at the minor version granularity. In docker images the version is dynamically set but not for the debian image. We could add it though, just would require some investment into the build logic

**Comment by howardjohn** [comment]
not stale

**Comment by numard** [comment]
I can reproduce it also with debian package for istio-sidecar 1.8.3 , it is reported as 1.8.0
```
i ps
NAME                                                             CDS        LDS        EDS        RDS          ISTIOD                      VERSION
beto-syd-istio-4.dev-nmeijome-istio                              SYNCED     SYNCED     SYNCED     SYNCED       istiod-5bc787ff58-dndpv     1.8.0
beto-syd-istio-5.dev-nmeijome-istio                              SYNCED     SYNCED     SYNCED     SYNCED       istiod-5bc787ff58-tlktg     1.8.0```
