### ISSUE TITLE
Approx. 20% increase in istio-proxy memory usage on 1.7 vs 1.6

### ISSUE THREAD

**Issue by Stono** [istio/istio#28652]
**Bug description**
Hi, 
I've been chatting to @howardjohn about this, and felt it warrants a github issue to track.

We've recently upgrade a staging cluster which has circa 500 istio-proxies on it from 1.6.13 to 1.7 and once we'd updated all sidecars we observed about a 20-25% increase in istio-proxy memory cluster wide:

<img width="1672" alt="Screenshot 2020-11-06 at 14 31 11" src="https://user-images.githubusercontent.com/1486729/98379318-127ad380-203f-11eb-8a3a-ff7e2955b794.png">

On top of the 10% added going from 1.5 -> 1.6 due to SDS, these increases are getting hard to stomach.

We can compare this cluster with our production cluster.  They're identical other than traffic patterns and number of endpoints (the 1.6 cluster having twice as many endpoints and significantly more load - so if anything, it should be higher).

Looking at the `min` across the board gives a decent indication of proxy memory usage before they start taking load, you can see the `min` on 1.7 is around the **50mb** mark:

<img width="1621" alt="Screenshot 2020-11-06 at 15 00 44" src="https://user-images.githubusercontent.com/1486729/98380841-02fc8a00-2041-11eb-8dfb-4ba97e6dd20a.png">

Whereas on 1.6 it's more like **40mb**:

<img width="1620" alt="Screenshot 2020-11-06 at 15 00 48" src="https://user-images.githubusercontent.com/1486729/98380862-0c85f200-2041-11eb-8ce9-ffbefccd419c.png">

For comparison purposes, we run a service on all of our clusters call `istio-test`, as you can see here on the 1.7 cluster we're around **50mb** average usage:

<img width="1670" alt="Screenshot 2020-11-06 at 14 53 37" src="https://user-images.githubusercontent.com/1486729/98380006-e9a70e00-203f-11eb-8742-f1969e5bf051.png">

Vs. the 1.6 cluster which is around **40mb**:

<img width="1667" alt="Screenshot 2020-11-06 at 14 53 41" src="https://user-images.githubusercontent.com/1486729/98380026-ef9cef00-203f-11eb-8247-541586bbd7e1.png">

Both are configured identically as their purpose is to compare istio releases.

[ ] Docs
[ ] Installation
[ ] Networking
[x] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Expected behavior**
Not a 20% increase in memory between releases.

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
1.7.5-4d93d71598da6e07cf9c68e32aaa0c4eadc308a4 

**How was Istio installed?**
Helm

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE

**Comment by Stono** [comment]
I'm going to document the things I check here as I go. 
The first thing I wanted to validate was that we haven't had an explosion of metrics.

There are some new metrics in the 1.7 envoy:

```
< # TYPE envoy_cluster_upstream_rq_max_duration_reached counter
150,152d148
< # TYPE envoy_cluster_zone_europe_west4_a__upstream_rq counter
< # TYPE envoy_cluster_zone_europe_west4_a__upstream_rq_200 counter
< # TYPE envoy_cluster_zone_europe_west4_a__upstream_rq_completed counter
177d172
< # TYPE envoy_server_envoy_bug_failures counter
```

It looks as if locality metrics are now enabled by default, which is a bit annoying as we don't need them, and also, they're still in a strange broken statsd format (the `europe-west4-a` part should be a label).  See: https://github.com/istio/istio/issues/20235

**Comment by Stono** [comment]
`top` from 1.7:
```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
     18 istio-p+  20   0  178772  55004  33220 S   0.3  0.2   7:38.41 envoy
      6 istio-p+  20   0  785232  75056  48768 S   0.0  0.3   0:24.06 pilot-agent
```

`top` from 1.6:
```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
      6 istio-p+  20   0  762540  56272  36640 S   0.0  0.2   2:01.13 pilot-agent
     20 istio-p+  20   0  176796  53488  32276 S   0.0  0.2  45:14.45 envoy
```

**Comment by Stono** [comment]
Associated: https://github.com/istio/istio/issues/26232

**Comment by kyessenov** [comment]
istio-agent increased in memory because xDS proxy was added, which requires importing a whole bunch of protobufs from envoy. I think the question is whether the value added by the proxy justifies the cost.

**Comment by mandarjog** [comment]
Is xds proxy already present in 1.7?
If you look at the effect on memory 1.7 uses 15MB of additional unshared memory. Details in the attached bug.

**Comment by mandarjog** [comment]
multiple questions 
1. Is it possible for a user to pay the cost of xds proxy *only* when they use features that require it.
2. Is it possible to fix it?
3. 25% is a large number, but the absolute number is what really matters which is 50-60mb per proxy, that is why I felt we don't need to make it a release blocker. A Java app would use 100s MBs to a few GBs.
But in aggregate istio ends up using more memory for sure.

**Comment by howardjohn** [comment]
On 3 month old memory: when looking into this, its extremely challenging to reduce the binary size in 1.7

In 1.9 we will drop the k8s imports, which I have done locally, and its 40mb, so we definitely have a long term path forward. Also the `gogo` api migration will drop multiple mb as well

**Comment by kyessenov** [comment]
There's a budget of how much users are going to tolerate per-pod overhead. Keep in mind Wasm overhead and whether it's better to use the budget for xDS proxy or Wasm.

**Comment by howardjohn** [comment]
We can reduce the overhead of XDS proxy. We don't unmarhsal Any so we don't need to import all the filters. The bare cost of just importing core XDS is not that high

**Comment by Stono** [comment]
> A Java app would use 100s MBs to a few GBs. 

Sorry but this is not a valid point.  

This isn't the main application, it's supposed to be a lightweight transparent proxy!

**Comment by Stono** [comment]
I'm going to close this in favour of https://github.com/istio/istio/issues/26232 which seems to be tracking the regression and all associated fixes.

@howardjohn has also back ported https://github.com/istio/istio/pull/28670 to 1.7 which is awaiting merge which will help a bit with the bloat on 1.7 (believe to land roughly half way between what I've observed here and 1.6).

I think; for those coming into this issue, we'll have to accept some increase in 1.7, with many improvements coming in 1.8 and 1.9.
