### ISSUE TITLE
Add liveness probe to istio-agent

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#28663]
This will resolve issues where pod permanently fails to get ready. We should be careful not to make this have false positives, most of this is resolved by caching result.

For safety, this should be off by default.

The probe should be the same as readiness but with different failure threshold/interval

**Comment by adiprerepa** [comment]
I'll take this one since I did the readiness probe for VMs.

Would we define the "new" failure threshold/interval the same way we did for healthchecking? i.e. adding it to ProxyConfig
