### ISSUE TITLE
Path rewrite to external service

### ISSUE THREAD

**Issue by charshin** [istio/istio#28681]
**Bug description**
Request is forwarded/routed successfully to an external service outside the cluster via ServiceEntry, but path rewrite is ignored. Is this a bug or not supported?

This question has been raised [here](https://discuss.istio.io/t/rewrite-to-externalname-service-isnt-working/5141) but looks like it doesn't get any attention so I'd like to put it here.

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by Monkeyanator** [comment]
Think the issue in your configuration is that you're setting `hosts` on the `VirtualService` to `restwrapjdbc`. Route rewrite should work if you make the host `mytestsvc`
