### ISSUE TITLE
command 'istioctl manifest generate' returns errors

### ISSUE THREAD

**Issue by tru-cstavares** [istio/istio#28689]
**Bug description**
I am trying to upgrade istio from v1.4.10 to v1.5. Istio v1.4.10 was installed using Helm templates followed by Kubectl apply. Knowing this and considering that upgrade using istioctl is now the recommended way to procceed I am trying to 'migrate' current setup to istioctl as follows:

1. istio-1.4.10# bin/istioctl manifest migrate my-values.yaml > migrate_export.yaml
2. istio-1.4.10# bin/istioctl manifest generate -f migrate_export.yaml > generate_export.yaml 

When executing the step 2) istioctl returns _unknown field "istio-internal-ingressgateway" in v1alpha1.GatewaysConfig_. 

```
➜  istio-1.4.10# bin/istioctl manifest migrate my-values.yaml > migrate_export.yaml
proto: tag has too few fields: "-"
➜  istio-1.4.10# bin/istioctl manifest generate -f migrate_export.yaml > generate_export.yaml 
input file failed validation with the following errors: unknown field "istio-internal-ingressgateway" in v1alpha1.GatewaysConfig
```

In addition to default gateway "istio-ingressgateway" we have many others such as this "istio-internal-ingressgateway".

Am I executing the 'migration' procedure correctly? 

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

[x] Multi Cluster
[ ] Virtual Machine
[x] Multi Control Plane

**Expected behavior**
No errors.

**Steps to reproduce the bug**
Execute:

1. istio-1.4.10# bin/istioctl manifest migrate -f my-values.yaml > migrate_export.yaml
2. istio-1.4.10# bin/istioctl manifest generate -f export.yaml > generate_export.yaml

**Version
```
➜  istioctl version --remote
client version: 1.4.10
citadel version: 1.4.10
galley version: 1.4.10
galley version: 1.4.10
ingressgateway version: 1.4.10
ingressgateway version: 1.4.10
internalingressgateway version:
internalingressgateway version:
nodeagent version:
nodeagent version:
nodeagent version:
nodeagent version:
nodeagent version:
nodeagent version:
pilot version: 1.4.10
pilot version: 1.4.10
policy version: 1.4.10
policy version: 1.4.10
sidecar-injector version: 1.4.10
sidecar-injector version: 1.4.10
telemetry version: 1.4.10
data plane version: 1.4.10 (21 proxies), 1.4.3 (5 proxies)
```
```
➜  kubectl version --short
Client Version: v1.17.3
```

**How was Istio installed?**
Helm template to yaml files and then kubectl apply those files.

**Environment where bug was observed (cloud vendor, OS, etc)**
Istio is installed on EKS v1.16

**Comment by JulienBreux** [comment]
I have the same issue!
