### ISSUE TITLE
istio-ingressgateway can’t access 

### ISSUE THREAD

**Issue by bryant-rh** [istio/istio#28698]
k8s version: v1.18.8
istio version: 1.7.4

istio deploy is successed
![image](https://user-images.githubusercontent.com/43403977/98496755-4f340e00-227d-11eb-97e2-50c151885077.png)

but can't access ingressgateway
![image](https://user-images.githubusercontent.com/43403977/98496892-a0dc9880-227d-11eb-8810-4d6017623e03.png)

then I use exec access  istio-ingressgateway pod ,I found not listen 8080 port
netstat -tpnl
![image](https://user-images.githubusercontent.com/43403977/98496985-dc776280-227d-11eb-9705-e3a76a6f0701.png)

**Comment by morvencao** [comment]
istio gateway will not listen on port 8080 until you create `gateway` and coresponding `virtualservice` on that port. Try to deploy bookinfo application and corresponding `gateway` and `virtualservice` and then check it again.

**Comment by bryant-rh** [comment]
> istio gateway will not listen on port 8080 until you create `gateway` and coresponding `virtualservice` on that port. Try to deploy bookinfo application and corresponding `gateway` and `virtualservice` and then check it again.

thanks ，The problem is solved！！

**Comment by morvencao** [comment]
I'll close this, feel free to reopen it if you still have problem.
