### ISSUE TITLE
remove init containers with CNI enabled

### ISSUE THREAD

**Issue by lanceliuu** [istio/istio#28700]
**Bug description**
We want to optimize pod start time with sidecar injection enabled. Seems that the parameter `cni.repair.enabled` controls whether to inject the `istio-validation` container or not with CNI enabled.
https://istio.io/latest/docs/setup/additional-setup/cni/#helm-chart-parameters
> Enable or disable the CNI Race Condition detection and repair functionality. This injects an istio-validation init container into every injected pod, which checks if Istio CNI correctly initialized the pod’s networking configuration. It also enables a new container in the CNI DaemonSet which monitors for pods and either labels or deletes them, per the values below.

I installed istio with `cni.repair.enabled=false` but still find the `istio-validation` init-container for newly created pods.
Is there a way to get rid of the `istio-validation` container?
```
kubectl get pods '-o=custom-columns=NAME:.metadata.name,CONTAINERS:.spec.containers[*].name,INITCONTAINERS:.spec.initContainers[*].name' -n coligotest-1
NAME                                      CONTAINERS                               INITCONTAINERS
s1-lxgrs-1-deployment-55bb77c77b-tl2j7    user-container,queue-proxy,istio-proxy   istio-validation
```

**Affected product area (please put an X in all that apply)**

[x] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**How was Istio installed?**

```
istioctl manifest install -f istio-minimal.yaml \
--set values.gateways.istio-egressgateway.enabled=false \
--set values.gateways.istio-ingressgateway.sds.enabled=true \
--set values.gateways.istio-ingressgateway.autoscaleMin=3 \
--set values.gateways.istio-ingressgateway.autoscaleMax=3 \
--set values.pilot.autoscaleMin=3 \
--set values.pilot.autoscaleMax=3 \
--set components.cni.enabled=true \
--set values.cni.repair.enabled=false
```

```
istioctl version
client version: 1.7.4
control plane version: 1.7.4
data plane version: 1.7.4 (12 proxies)
```

**Comment by morvencao** [comment]
The `istio-validation` init container will be injected once you enabled istio cni, you can't disable that currently.

**Comment by lanceliuu** [comment]
I removed the `istio-validation` from the istio-sidecar-injector template and everything seems remain working without issue. Could you give more hints for the necessity of `istio-validation` container? Any related issue/discussion would be apperaciated.

**Comment by morvencao** [comment]
@lanceliuu See the original PR to add the `istio-validation` init container: https://github.com/istio/istio/pull/20130

**Comment by hzxuzhonghu** [comment]
I am also confused at first. The validator looks redundant, not sure when the rules can be set wrong

**Comment by ZhuangYuZY** [comment]
Could you remove the `istio-validation` initcontainer if CNI enabled ? @linsun @sdake FYI.

**Comment by hzxuzhonghu** [comment]
It is used to validate whether the rules are set correctly.
https://github.com/istio/istio/issues/14327

**Comment by sdake** [comment]
I filed a related github issue. In that issue, I asked the question of why are iptable rules being set at all by the proxy. The role of CNI should be to set those IP table rules - proxy itself should not be setting any rules.

https://github.com/istio/istio/issues/28918
