### ISSUE TITLE
Add source_cluster and destination_cluster in access logs

### ISSUE THREAD

**Issue by gargnupur** [istio/istio#28714]
**Bug description**
Add source_cluster and destination_cluster in access logs

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Easily know source and destination cluster for multicluster scenarios in access logs in stackdriver

**Comment by douglas-reid** [comment]
This sounds good. The only catch is we need to define cluster behavior for VMs.
