### ISSUE TITLE
Refactor agent SDS handling

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#28712]
Now that gateway SDS will be removed, we should use this as an opportunity to refactor the SDS handling of the agent.

Goals:
* Reduce code and complexity
* Expand testing
* Improve performance, in particular startup latency

Current design:
* Custom XDS implementation, not following best practices we have learning in Istiod
* Secrets generated on demand, stored in cached designed for multi-tenant node agent and gateway secrets. Poll every x minutes to refresh certs. This is slow (we wait seconds to even start the CSR exchange flow) and complex because it was designed for other use cases. This also leads to bugs like https://github.com/istio/istio/issues/28099 and https://github.com/istio/istio/issues/28683.

Suggested design:
* Decouple fetching secrets from serving them.
     * Fetch on startup - will improve startup speed, make things simpler. Probably also makes the root cert handling a lot simpler
     * Change rotation to be event driven rather than polling. On update, trigger push like today
     * Expose some interface like FetchSecret(). If called on default/rootca, we return that, if its a file one we lookup the file, return it, and add a watch.
* Use Pilot's XDS implementation
  * This is a bit coupled to Istiod currently, but can be broken out with some minor changes

**Comment by bleggett** [comment]
One thing here - it should be trivially easy to support disabling Istio's SDS in favor of another SDS with a gRPC socket defined at install time - the code for this seems to already exist but we're not using it or exposing this option - I'd like to see this.

**Comment by howardjohn** [comment]
@bleggett agreed. One thing I am curious, for your use case would you only require another UDS or potentially a TCP service?

**Comment by bleggett** [comment]
> @bleggett agreed. One thing I am curious, for your use case would you only require another UDS or potentially a TCP service?

For our use case we'd be using SPIRE as the SDSv3 gRPC server - it conforms to the spec and should be drop-in, if we had a way to easily drop it in.

**Comment by bleggett** [comment]
Another comment, as I investigate this stuff - Istio currently hardcodes SNI matching config in the form of a service-account-based SPIFFE ID for mTLS into the Envoy cluster config ValidationContext for all upstream services - as [per Envoy's SDS spec](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/auth/tls.proto#envoy-api-field-auth-commontlscontext-combined-validation-context), the SDS service should be responsible for supplying ValidationContext config to proxy instances, we should do that and remove the `defaultValidationContext` static config that is always blindly injected.
