### ISSUE TITLE
'istioctl analyze' does not validate v1beta1 CRs from file

### ISSUE THREAD

**Issue by esnible** [istio/istio#28719]
`istioctl analyze` does not validate v1beta1 networking CRs from file.  It skips them, reporting them valid.

To reproduce, I first created a .yaml file with two invalid DestinationRules, one alpha, one beta:

``` bash
cat >/tmp/no-cert.yaml <<EOF
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: db-mtls
spec:
  host: mydbserver.prod.svc.cluster.local
  trafficPolicy:
    tls:
      mode: MUTUAL
      clientCertificate: "" # was /etc/certs/myclientcert.pem
      privateKey: /etc/certs/client_private_key.pem
      caCertificates: /etc/certs/rootcacerts.pem
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: db-mtls-alpha
spec:
  host: mydbserver-alpha.prod.svc.cluster.local
  trafficPolicy:
    tls:
      mode: MUTUAL
      clientCertificate: "" # was /etc/certs/myclientcert.pem
      privateKey: /etc/certs/client_private_key.pem
      caCertificates: /etc/certs/rootcacerts.pem
EOF
```

Next I ran `istioctl analyze /tmp/no-cert.yaml` and saw that only one was reported.

These can't be added to the mesh, the webhook rejects them, but if they were in the mesh both will be reported as an error.  To reproduce that, `kubectl delete validatingwebhookconfiguration istiod-istio-system` and apply _no-cert.yaml_, then `istioctl analyze`, and you will see both are reported as bad.

cc @jasonwzm

**Comment by howardjohn** [comment]
I will close my duplicate https://github.com/istio/istio/issues/28445 since this is more descriptive

**Comment by jasonwzm** [comment]
Possible fix https://github.com/istio/istio/pull/23104

**Comment by howardjohn** [comment]
not stale

**Comment by esnible** [comment]
While working on https://github.com/istio/istio/issues/31525 I hit this again.

@jasonwzm any chance of this making it into 1.10?

**Comment by WojciechKarpiel** [comment]
I've also hit this as well (both on v1.11 and v1.12)

My use-case is validating configuration offline before deploying to production, so a workaround is to replace the CRDs versions before running the analyzer.


Side note: Thanks for introducing a static analysis tool! IMO importance of such tools is much underestimated.
