### ISSUE TITLE
1.8 regression: dashboard has duplicate datasource

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#28724]
![2020-09-11_14-28-16](https://user-images.githubusercontent.com/623453/98603996-d7bfa800-2297-11eb-996b-e16160b06277.png)

**Comment by howardjohn** [comment]
cc @carolynhu

**Comment by carolynhu** [comment]
Current status:
- Mesh dashboard: datasource: default
- Sevice and Workload dashboard: datasource: prometheus and default
- Control plane dashboard: datasource: default

I'm going to remove the duplicated datasource, and use Prometheus as the source of truth
