### ISSUE TITLE
proposal: telemetry single stat panels should show current instead of average

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#28730]
![2020-09-11_15-48-01](https://user-images.githubusercontent.com/623453/98609799-01ca9780-22a3-11eb-86ee-dc27ce99cef0.png)

To me, this is very confusing. My current QPS is actually like 25k, but because we show the average we end up with 12k.

cc @mandarjog @carolynhu  @douglas-reid for opinions

**Comment by carolynhu** [comment]
@howardjohn I will take care of this issue, I'm currently working on those metrics refinement/redesign stuff.

**Comment by douglas-reid** [comment]
This is tricky. Do we want this view to be more stable or more reactive/sensitive?

You had no traffic for a large portion of the window shown. This should clear up over the period of ~5m or so (or whatever your grafana-defined time window was), right?

If we switched to `irate`, etc., we would still have a defined time window for calculation (typically, `1m`), but it is probably closer to what you wanted when debugging in this case, right?

We could call it "Average Global Request Volume" or switch to a gauge view I guess. It is nice to have some way of comparing `instant` to `trend`.

**Comment by howardjohn** [comment]
I agree that both average and instant are useful.

Maybe we should consider not actually having the single stat and use full panels? These panels are really one of the most critical and they are hard to intepret. For example
![2020-09-11_16-25-29](https://user-images.githubusercontent.com/623453/98612078-39880e00-22a8-11eb-8af7-643697ee6340.png)

Did I just scale up from 100qps to 24k? Or 23k to 24k?

**Comment by douglas-reid** [comment]
> I agree that both average and instant are useful.
> 
> Maybe we should consider not actually having the single stat and use full panels? These panels are really one of the most critical and they are hard to intepret. For example
> ![2020-09-11_16-25-29](https://user-images.githubusercontent.com/623453/98612078-39880e00-22a8-11eb-8af7-643697ee6340.png)
> 
> Did I just scale up from 100qps to 24k? Or 23k to 24k?

I can't recall. Is there an option in those panels to show the max and min ?  That would make it more interpretable. 

IIRC, the original idea was to provide a quick view snapshot of the state of the mesh. A full panel would be more accurate, but also might make it harder to read.

Maybe we should expand to include a more detailed view "below the fold" and have instantaneous data at the top ?  Does the UX WG have expertise we could lean on here?

**Comment by carolynhu** [comment]
@howardjohn currently the query for that is: `round(sum(irate(istio_requests_total{reporter="destination"}[1m])), 0.001)`, so it's not average..
