### ISSUE TITLE
worker node shutdown will skip terminationDrainDuration before sidecar exit

### ISSUE THREAD

**Issue by Rayzhangtian** [istio/istio#28738]
**Bug description**
When worker node graceful shutdown, the OS will send SIGTERM to all processes, so both pilot-agent and sidecar in the same istio-proxy will receive SIGTERM at the same time, so the terminationDrainDuration which is used to sleep in pilot-agent before envoyproxy exiting will be useless. So the application connection can not be shutdown gracefully.

"kubectl delete pod" case can be handled correctly for pilot-agent (as PID=1) will handle the SIGTERM, it will send graceful drain to envoy proxy and can wait  terminationDrainDuration (default 5s and annotation can modify it) before envoy proxy existed. This sidecar graceful shutdown logic can NOT work in worker node graceful shutdown for both pilot-agent and envoy-proxy receive TERM at the same time.
Any idea to fix it?

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
sidecar does not handle SIGTERM? e.g. pilot-agent call admin to graceful shutdown and then send KILL to sidecar directly?

**Steps to reproduce the bug**
reboot worker node which run pod with sidecar injected.

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
1.6, 1.7

**How was Istio installed?**
istioctl install

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by howardjohn** [comment]
I cannot think of any ways to solve this without envoy supporting an option to block sigterm handler, which was shot down in https://github.com/envoyproxy/envoy/pull/4938

**Comment by Rayzhangtian** [comment]
can it be possible that after pilot call envoy proxy graceful drain API, and then pilot send SIGTERM to envoy proxy, and then both envoy proxy and pilot start to sleep the same termination graceful period, this logic will be similar when worker node send SIGTERM to both pilot-agent and envoy proxy at the same time. because pilot-agent still can call envoyproxy graceful drain API during envoy proxy sleep. For some application which need more time to quit/drain, it is useful.
