### ISSUE TITLE
WorkloadEntry auto register race

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#28743]
We register the workload entry when it first connects to istiod, however if the workloadentry is not propagated back to the serviceentry store, then we will get no serviceinstances for this proxy. Then istiod can not geneerate right xds configs for this proxy.

And the workloadentry handler mainly triggers eds push, which will not update proxy at all.

**Comment by stevenctl** [comment]
Seems like this would affect more than just auto-registration. We don't really advise users to create a WorkloadEntry _before_ they connect their VM to pilot.

**Comment by hzxuzhonghu** [comment]
Correct, a legacy issue
