### ISSUE TITLE
release artifacts should include a link to the full source tree, including vendor, used to build the release

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#2875]
release artefacts should include a link to the full source tree, including vendor, used to build the release

http://gcsweb.istio.io/gcs/istio-prerelease/daily-build/0.5.0-pre20180124-17-29-51/ 

doesn't seem to have anywhere the source tree used to create the release (would include the vendor dir post build)

cc @hklai @costinm

**Comment by costinm** [comment]
And a 'make' in the released source tree should work, if possible ...

**Comment by mattdelco** [comment]
To my knowledge Istio hasn't been saving the source for any release (0.1.1 might be an exception).  Github generates a source tar but of course that doesn't necessarily reflect what was actually used to make the build.  I've been puzzled at how Cloud Builder just throws away the /workspace directory after a build is complete--do they really expect each customer to implement their own source backup?  Anyway, I'm not using CB's design as an excuse and agree it's desirable to detain source but apparently that wasn't a priority for Istio.  The creation of the tar is probably best to handle at the end of release/cloud_build.sh or somewhere in release/store_artifacts.sh.  Currently there's not much tradeoff between the two (the only step that runs inbetween is creating the installer tars).  Longer term I can see how cloud_build.sh might run as non-root while store_artifacts.sh might run as a more privileged user that can upload artifacts.

As for make in the released source tree, I'm not sure how well that will work.  I haven't tested how well bin/get_workspace_status handles the case where git either isn't installed (or complains that it's doesn't recognize the directory as a git tree).  To keep things more reproducible the build and/or make will likely need to use the BUILDINFO caching feature in bin/gobuild.sh.  BUILDINFO could end up being a file/feature that's managed by make.  Make would have to handle when git doesn't exist or fails (and thus use/preserve the existing file), and unfortunately the file would need to be re-checked/re-generated on almost any invocation of make (at least the ones involving go source, which practically everything) to keep the dirty vs clean status accurate.

**Comment by ldemailly** [comment]
let’s just start with saving rhe build tree, we can see make later

**Comment by ldemailly** [comment]
see also https://github.com/istio/test-infra/issues/675

**Comment by ldemailly** [comment]
will be less necessary and partially implemented with #3348 but not sufficient (we need to capture everything used)

**Comment by ldemailly** [comment]
https://github.com/istio/vendor-istio now exists but is everything used captured ?

**Comment by hklai** [comment]
Already done.

https://github.com/istio/istio/releases/tag/0.8.0

**Comment by ldemailly** [comment]
we don’t save everything and the build isn’t hermetic but ok
