### ISSUE TITLE
Prometheus & Grafana addons: Are they production grade?

### ISSUE THREAD

**Issue by darrenhaken** [istio/istio#2876]
Would you consider the Prometheus and Grafana addons as production grade?

Questions which come to mind:
- Do they persist?
- Are they HA?
- Can you do rolling upgrades?

**Comment by mandarjog** [comment]
Being discussed in  #2746

**Comment by douglas-reid** [comment]
Beyond the discussion in #2746, I feel that it is important to mention that the add-ons themselves have not been targeted for any real stress testing or production usage explicitly.

In particular, the prometheus configuration is not realy HA and is not persisting data for any significant period of time (see: https://github.com/istio/istio/blob/master/install/kubernetes/addons/prometheus.yaml#L227).

There have been demonstrations of HA prometheus integrations (weave cloud, iirc), but the default add-on config does not attempt anything special.

Some work would likely be necessary to ensure grafana was load-balancing properly between multiple instances of prometheus (if that was the approach to HA chosen), as that has not been tested in any form.

As for grafana itself, we've done no explicit hardening of the image or stress-testing of the example dashboards that it deploys with. Large number of services may cause issues, for instance. We also haven't locked down access, etc.

**Comment by darrenhaken** [comment]
@douglas-reid thanks, that's exactly the sort of information I was looking for.

Are you interested in hardening/HA of these services? I ask because I can either build my own or work with direction from Istio with the plan to improve the addons. 

It really depends on how that fits with your long-term goals.

**Comment by douglas-reid** [comment]
@darrenhaken I think the community is definitely interested in hardening these services, especially if you are willing to take on the task. Maybe having two options (ex: prometheus.yaml and prometheus-ha.yaml) would be a good first step.
