### ISSUE TITLE
Multicluster: namespace controller should be run only by leader istiod

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#28779]
**Bug description**

Currently, for the primary cluster, namespace controller is only run by leader to maintain root-certificate. However, for multicluster scenario, it is run by all istiod instances, there maybe some conflicts.

**Comment by stevenctl** [comment]
For multi-primary, we could also do something where the remote-secret specifies whether the cluster being accessed is a remote or a primary. If it's a primary, we don't have to setup the namespace controller – that cluster should be running its own.

**Comment by stevenctl** [comment]
I'll try to tackle this in the PR you linked.
