### ISSUE TITLE
Cannot get VM running in 1.8

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#28824]
Following https://preliminary.istio.io/latest/docs/setup/install/virtual-machine/ or https://deploy-preview-8418--preliminary-istio.netlify.app/latest/docs/setup/install/virtual-machine/, I cannot get the VM running.

The problem is the XDS proxy is expecting certs in OUTPUT_CERTs. However, we do not write them there until envoy requests them (see https://github.com/istio/istio/issues/28099 and https://github.com/istio/istio/issues/28712)

Even if we turn xDS proxy off, somehow still get authentication failures. Not sure why for that one.

cc @stevenctl @christian-posta @bianpengyuan

**Comment by bianpengyuan** [comment]
Marked this as release blocker.

**Comment by stevenctl** [comment]
<code>
ISTIO_SERVICE_CIDR=*
ISTIO_INBOUND_PORTS=*
*PROV_CERT=*
ISTIO_LOCAL_EXCLUDE_PORTS=15090,15021,15020
PROXY_XDS_VIA_AGENT=true
ISTIO_META_DNS_CAPTURE=true
ISTIO_PILOT_PORT=15012
ISTIO_NAMESPACE=vm-ns
</code>

Seems to do the trick for me:

```
landow@instance-1:~$ tail /var/log/istio/istio.log
2020-11-12T19:44:02.485631Z     info    sds     resource:ROOTCA new connection
2020-11-12T19:44:02.485711Z     info    sds     Skipping waiting for gateway secret
2020-11-12T19:44:02.485737Z     info    sds     resource:default new connection
2020-11-12T19:44:02.485770Z     info    sds     Skipping waiting for gateway secret
2020-11-12T19:44:02.485941Z     info    cache   adding watcher for file ./etc/certs/root-cert.pem
2020-11-12T19:44:02.485993Z     info    cache   adding watcher for file ./etc/certs/cert-chain.pem
2020-11-12T19:44:02.486045Z     info    cache   GenerateSecret from file ROOTCA
2020-11-12T19:44:02.486280Z     info    cache   GenerateSecret from file default
2020-11-12T19:44:02.487004Z     info    sds     resource:ROOTCA pushed root cert to proxy
2020-11-12T19:44:02.487108Z     info    sds     resource:default pushed key/cert pair to proxy
landow@instance-1:~$ ls /etc/certs/
cert-chain.pem  key.pem  root-cert.pem
landow@instance-1:~$ 
```

**Comment by stevenctl** [comment]
Retesting the `istioctl x workload` based doc.. seems like that generates everything in a way that would work and I've been repeatedly testing it over the past couple weeks. In that flow, we don't set `PROV_CERTS` or `OUTPUT_CERTS`.

**Comment by stevenctl** [comment]
Seems like explicitly adding `PROV_CERT=` to cluster.env is required, omitting it doesn't work.

**Comment by stevenctl** [comment]
John pointed out that this will just make us use JWT forever – and it will eventually expire. We likely need a code fix to either use JWT for the first request/until the certs in the specified "PROV_CERTS" dir are ready. 

https://github.com/istio/istio/blob/6f04042f382168fced34b519600ebce9ee974792/pkg/istio-agent/xds_proxy.go#L449-L451

**Comment by stevenctl** [comment]
The failing doc has OUTPUT_CERTS set.

**Comment by williamaronli** [comment]
the prov_cert and output_certs should be set and  . 
**output_certs** : the path where sds agent store the when sds agent get the cert 
**prov_cert**: the path where sds agent extract the cert the build mtls connection

they should be set the same

**Comment by stevenctl** [comment]
Right. In our current integration tests, we have `PROV_CERT=""` so we only ever use the token. 

In our manual testing we set PROV_CERT and OUTPUT_CERT to the same value, and we get continuous failures due to the cert and key never getting fetched.

**Comment by christian-posta** [comment]
This should block the 1.8 release, but I don't see it on the triage spreadsheet?

**Comment by stevenctl** [comment]
Going to leave this open till we land the 1.8 cherry-pick and manually confirm.
