### ISSUE TITLE
istioctl proxy-config diff

### ISSUE THREAD

**Issue by clsacramento** [istio/istio#28825]
**Describe the feature request**
In order to understand, how changes in Istio objects translate to Envoy config, it would be great to have a istioctl command that assists in doing that. For example running something like this:

`istioctl proxy-config diff pod.namespace --compare-config-file /tmp/previous_config`

And the command could output what is different between the current config from the proxy against the one provided by the file.

**Describe alternatives you've considered**
I tried dumping the config from a proxy, making the change I wanted to understand, wait until synced and then dumping again the config to do a diff between the two. The problem was that diff did not handle well the two json dumps and it seems istioctl already has some logic to filter out some of the noise from the plain json diff.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Additional context**
I was trying to understand if changing the protocol on a ServiceEntry port caused any changes on the sidecar proxy configuration. When doing a diff of the config before and after the change I got:
```
$ diff  /tmp/config_https /tmp/config_tls
9a10,20
>       "NAMESPACE": "default",
>       "EXCHANGE_KEYS": "NAME,NAMESPACE,INSTANCE_IPS,LABELS,OWNER,PLATFORM_METADATA,WORKLOAD_NAME,MESH_ID,SERVICE_ACCOUNT,CLUSTER_ID",
>       "INSTANCE_IPS": "10.40.0.23",
>       "POD_PORTS": "[\n]",
>       "INTERCEPTION_MODE": "REDIRECT",
>       "SERVICE_ACCOUNT": "default",
>       "MESH_ID": "cluster.local",
>       "SDS": "true",
>       "WORKLOAD_NAME": "tmp-shell",
>       "OWNER": "kubernetes://apis/v1/namespaces/default/pods/tmp-shell",
>       "ISTIO_VERSION": "1.7.4",
10a22,24
>        "parentShutdownDuration": "60s",
>        "proxyAdminPort": 15000,
>        "controlPlaneAuthPolicy": "MUTUAL_TLS",
29,32c43
<        "statNameLength": 189,
<        "parentShutdownDuration": "60s",
<        "proxyAdminPort": 15000,
<        "controlPlaneAuthPolicy": "MUTUAL_TLS"
---
>        "statNameLength": 189
34a46
>        "gcp_project": "istio101-221115",
42,43c54
<        "gcp_gke_cluster_name": "setest2",
<        "gcp_project": "istio101-221115"
---
>        "gcp_gke_cluster_name": "setest2"
48,49d58
<        "run": "tmp-shell",
<        "service.istio.io/canonical-name": "tmp-shell",
52c61,63
<        "security.istio.io/tlsMode": "istio"
---
>        "security.istio.io/tlsMode": "istio",
>        "run": "tmp-shell",
>        "service.istio.io/canonical-name": "tmp-shell"
55,66c66
<       "NAME": "tmp-shell",
<       "NAMESPACE": "default",
<       "EXCHANGE_KEYS": "NAME,NAMESPACE,INSTANCE_IPS,LABELS,OWNER,PLATFORM_METADATA,WORKLOAD_NAME,MESH_ID,SERVICE_ACCOUNT,CLUSTER_ID",
<       "INSTANCE_IPS": "10.40.0.23",
<       "POD_PORTS": "[\n]",
<       "INTERCEPTION_MODE": "REDIRECT",
<       "SERVICE_ACCOUNT": "default",
<       "MESH_ID": "cluster.local",
<       "SDS": "true",
<       "WORKLOAD_NAME": "tmp-shell",
<       "OWNER": "kubernetes://apis/v1/namespaces/default/pods/tmp-shell",
<       "ISTIO_VERSION": "1.7.4"
```

It seems making that change on the ServiceEntry didn't really have any impact but that was hard to visualize with a simple diff.

**Comment by therealmitchconnors** [comment]
The proxy-config command supports a `--file` parameter, which should be capable of this behavior, albeit with a particular set of steps:

1. ssh <user@proxyhostname> 'curl localhost:15000/config_dump' > envoy-config.json
2. apply changes to service entry
3. istioctl proxy-config clusters --file envoy-config.json
