### ISSUE TITLE
multicluster pilot test flakes

### ISSUE THREAD

**Issue by stevenctl** [istio/istio#28834]
* Traffic Shifting: Sometimes 1 cluster is not included in LB of 100 callls + a traffic shifting rule
  * https://prow.istio.io/view/gs/istio-prow/logs/integ-pilot-multicluster-tests_istio_postsubmit/1326591759664287744
* instanceip expects 503 but gets 200 (may just need a longer timeout)
  * https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28830/integ-pilot-multicluster-tests_istio/1327000170545549312
```
2020-11-12T21:38:07.653055Z	info	tf	=== BEGIN: Test: 'pilot[TestTraffic/instanceip/without_sidecar#03]' ===
    traffic.go:76: failed calling a->'http://b.echo-1-93881.svc.cluster.local:82/': call failed from a to http://b.echo-1-93881.svc.cluster.local:82 (using http): timeout while waiting (last error: 5 errors occurred:
        	* expected response code 503, got "200"
```
* TestTraffic/gateway/external 503s
  * https://prow.istio.io/view/gs/istio-prow/logs/integ-pilot-multicluster-tests_istio_postsubmit/1326693003682648064
```
2020-11-12T01:35:03.672191Z	info	tf	=== BEGIN: Test: 'pilot_endpointslice[TestTraffic/gateway/external.external-2-21612.svc.cluster.local]' ===
    traffic.go:76: call failed from TestRunner to http://172.18.255.155:80 (using http): timeout while waiting (last error: 1 error occurred:
        	* response[0] Status Code: 503
        
```

**Comment by stevenctl** [comment]
#24581

**Comment by hzxuzhonghu** [comment]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28457/integ-pilot-multicluster-tests_istio/1337956884673466368

**Comment by hzxuzhonghu** [comment]
traffic.go:76: failed calling a->'http://b.echo-1-55619.svc.cluster.local:80/': call failed from a to http://b.echo-1-55619.svc.cluster.local:80 (using http): timeout while waiting (last error: expected 50 calls to "b", got 39)
--

**Comment by esnible** [comment]
The endpointslice test is still failing:

https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/29411/integ-pilot-multicluster-tests_istio/1338491547649314816

```
1/588 Tests Failed.
...
endpointslice: Failure
...
2020-12-14T14:49:21.655778Z	info	tf	=== FAILED: Setup: 'pilot_endpointslice' (build instance: timeout while waiting (last error: configmap istio-ca-root-cert was not found in namespace echo-1-93436: configmaps "istio-ca-root-cert" not found)) ===
...
FAIL	istio.io/istio/tests/integration/pilot/endpointslice	115.293s
```

**Comment by esnible** [comment]
Would this be the same cause as

```
pilot: TestTraffic
pilot: TestTraffic/services
pilot: TestTraffic/services/case_4_no_match#02
    traffic.go:73: failed calling a->'http://b-alt-4:12346/': call failed from a to http://b-alt-4:12346 (using http): timeout while waiting after 17 attempts (last error: no responses received) | pilot: TestTraffic/services/case_4_no_match#02 expand_less | 1m16s | traffic.go:73: failed calling a->'http://b-alt-4:12346/': call failed from a to http://b-alt-4:12346 (using http): timeout while waiting after 17 attempts (last error: no responses received)
pilot: TestTraffic/services/case_4_no_match#02 expand_less | 1m16s
traffic.go:73: failed calling a->'http://b-alt-4:12346/': call failed from a to http://b-alt-4:12346 (using http): timeout while waiting after 17 attempts (last error: no responses received)
```

https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31114/integ-pilot-multicluster-tests_istio/1365368988074250240
