### ISSUE TITLE
Add source and destination cluster tags in tracing

### ISSUE THREAD

**Issue by gargnupur** [istio/istio#28833]
**Bug description**
Currently when request goes from one cluster to another, there is no easy way to distinguish the source and destination cluster in traces.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by douglas-reid** [comment]
Can we flesh out the desired impact a bit?  For starters, we could add a new tag `istio.kubernetes_cluster` or something. Then, we could track multi-cluster hops by span in each full trace.  (so you could look at parent/child span pairs to validate cluster boundaries). Would that be "enough" to meet the requirement?
