### ISSUE TITLE
Istio 1.5.6 - Prometheus memory creeping

### ISSUE THREAD

**Issue by hchiangca** [istio/istio#28844]
Using Istio 1.5.6, and the Prometheus POD (3 of them) seems to be using the similar of memory (at 13G now) which has a good correlation to the number of PODS that has istio-proxy.  Had set this for prometheus:  --storage.tsdb.retention=2h, so the data only get a retention of 2 hours, but the memory usage is still high.

Any pointers on how to reduce the memory footprint, or can a scaling strategy be deployed?  No matter how many PODS to be scaled the PODS are simply using the same amount of memory, so seems like scaling horizontally does not help much.  Appreciated any pointers....or is there a purge that have to be done?

**Comment by howardjohn** [comment]
https://istio.io/latest/docs/ops/best-practices/observability/ has some info on this
