### ISSUE TITLE
Unable to upgrade custom gateways that have a revision and tag set

### ISSUE THREAD

**Issue by rvennam** [istio/istio#28849]
Recreation script:
```
# Install Istio 1.7.4
curl -L https://istio.io/downloadIstio | ISTIO_VERSION=1.7.4 sh -
cd istio-1.7.4
./bin/istioctl operator init
sleep 20s
kubectl create ns istio-system
kubectl apply -f - <<EOF
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: example-istiocontrolplane
spec:
  profile: default
EOF
sleep 60s

# Install additional gateways in new namespace
kubectl create namespace custom-gateways
kubectl apply -f - <<EOF
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: custom-ingressgateway-iop
  namespace: istio-system
spec:
  profile: empty
  revision: custom-ingressgateway # NOTE!!!!!!!!!!
  tag: 1.7.4 # NOTE!!!!!!!!!!
  components:
    ingressGateways:
      - name: custom-ingressgateway
        label: 
          istio: custom-ingressgateway
        namespace: custom-gateways
        enabled: true
EOF
sleep 30s
kubectl get pods -n custom-gateways

# Update Istio operator
cd..
curl -L https://istio.io/downloadIstio | ISTIO_VERSION=1.8.0-alpha.2 sh -
cd istio-1.8.0-alpha.2
./bin/istioctl operator init
sleep 30s
```

This results in:
```
$ kubectl get pods -n istio-system -w
NAME                                    READY   STATUS    RESTARTS   AGE
istio-ingressgateway-7d7d668d4d-mlrmz   1/1     Running   0          32s
istiod-5c5cb77ddb-lq7vq                 1/1     Running   0          40s

$ kubectl get pods -n custom-gateways -w
NAME                                     READY   STATUS    RESTARTS   AGE
custom-ingressgateway-667659c76-bn4wp    0/1     Running   0          22s
custom-ingressgateway-6f78b5b684-sfjmr   1/1     Running   0          112s
```

The pods in istio-system upgraded to 1.8 as expected, but the custom gateway in custom-gateways is also trying to update, but the new replicaset is failing to start. 

1. I do not expect the custom gateway deployment to get updated because I had the tag set to 1.7.4
2. The new pod that is coming up is failing because it's looking for `istiod-custom-ingressgateway.istio-system.svc`. I don't have this..I just have the default `istiod.istio-system.svc`

[ ] Docs
[X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

The custom gateways should not be updated to 1.7.4. 

**How was Istio installed?**
Istio operator

**Environment where bug was observed (cloud vendor, OS, etc)**
IKS

**Comment by sdake** [comment]
I expect this would happen in any environment, and many many customers are using IOP to create custom gateways. Problem #2 seems easy to fix and is very serious. @howardjohn can you please take a look?

This looks to me as a ship stopping bug/regression...

**Comment by sdake** [comment]
cc @ostromart @istio/technical-oversight-committee

**Comment by linsun** [comment]
For 2, it should be fixed if you remove the revision line, e.g. `  revision: custom-ingressgateway # NOTE!!!!!!!!!!`

been chatting with @ostromart on this.   basically the **semantics change** of revision changed. if a user uses revision in 1.7 for gws., i 1.8, user would need to point to the revision of istiod, which is no revision in this case (after an in place upgrade from 1.7 to 1.8 with default profile).

The change was to support our new revision gw update in 1.8 so that gw can be pointed to the corresponding istiod revision.

cc @costinm

**Comment by rvennam** [comment]
@linsun , removing that revision addresses both issues. It terminates the new failing pod and leaves the existing 1.7.4 one running.

**Comment by linsun** [comment]
Thank you @rvennam!  Let's make sure we have this properly communicated in release upgrade notes.

cc @GregHanson

**Comment by rvennam** [comment]
We asked users to set the revision field because the IOP's were trampling on another. Hoping this isn't a problem in 1.8

**Comment by sdake** [comment]
Thanks @rvennam for the detailed bug report. As requested during the TOC meeting, I or someone from Env will write an analyzer to check for this condition. The real goal of writing the analyzer is not to detect this specific problem (although that is a second order goal) - but to determine the cost of writing such analyzers for any contributor of the project (those nieve to writing analyzers).

@GregHanson please do not close this bug after you resolve the release notes.

**Comment by bianpengyuan** [comment]
@sdake Reassign this to you. 1.8 release notes had a note about this issue. The left work is on env working group.
