### ISSUE TITLE
Addons don't install sidecars by default

### ISSUE THREAD

**Issue by lucasponce** [istio/istio#28850]
If a user wants to expose addons using Gateways as described in

https://istio.io/latest/docs/tasks/observability/gateways/

They will realize that it doesn't work because addons don't inject sidecars.

https://istio.io/latest/docs/setup/install/istioctl/#customizing-the-configuration

Workaround is simply to re-install addons using a manual istioctl kube-inject command:

```
$ bin/istioctl kube-inject -f samples/addons/kiali.yaml | kubectl apply -f -
```

But this needs to be proper documented in istio.io

**Comment by howardjohn** [comment]
> They will realize that it doesn't work because addons don't inject sidecars.

Why does this matter? Gateways can connect to addons without a sidecar - the doc should work as-is

**Comment by lucasponce** [comment]
Some comments with @howardjohn 

```
95% of settings in DR are applied client side (ie the gateway) and don't require a sidecar
in the future it will be 100%
if you set the DR to tell the gateway to send TLS traffic to the addon then it will fail though
```

Probably it was me, I should re-start and provision a minikube cluster and the port of the ingress changed and I tested an old one making that assumption.

Closing.
