### ISSUE TITLE
Make consistent use of pprof in all components

### ISSUE THREAD

**Issue by ayj** [istio/istio#2885]
https://golang.org/pkg/runtime/pprof is useful to capture running goroutines and cpu/memory profiles. It's enabled in some components but flag, paths, documentation etc. are not consist across components. 

For example, https://github.com/istio/istio/blob/master/pilot/pkg/proxy/envoy/discovery.go#L295-L301.

**Comment by ayj** [comment]
cc @costinm

**Comment by ayj** [comment]
pprof and another admin/diagnostics should be on a separate port from the normal service port.

**Comment by douglas-reid** [comment]
@ayj can we standardize on the http-monitoring 9093 port used by mixer and pilot ?

**Comment by ayj** [comment]
Sounds reasonable. We'd have the common port/path pattern on all components.
```
<host>:9093/version
<host>:9093/metric/...
<host>:9093/debug/pprof/...
```

Do we want this all on by default? Any security concerns with exposing CPU/memory profiling data outside the pod?

**Comment by kyessenov** [comment]
That does census do? I'm not comfortable exposing debugging info along with
metrics on the same endpoint.
