### ISSUE TITLE
bookinfo cleanup script missing from release

### ISSUE THREAD

**Issue by GregHanson** [istio/istio#289]
as of 0.1.3 `samples/apps/bookinfo/cleanup.sh` is not included in the release.  I'm assuming there is a cp *.yaml filter somewhere and so it is never added to the zip/tar file

**Comment by GregHanson** [comment]
referenced here: https://istio.io/docs/samples/bookinfo.html#cleanup

**Comment by ldemailly** [comment]
it's back now:
 https://github.com/istio/istio/blob/master/samples/apps/bookinfo/cleanup.sh
