### ISSUE TITLE
extraStatTags not working

### ISSUE THREAD

**Issue by ediezh** [istio/istio#28910]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

Extra metric tags added as prefix to time series metric instead of as a label.

IstioOperator configuration:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    tcpKeepalive:
      time: 300s
    defaultConfig:
      extraStatTags:
        - request_path
  values:
    telemetry:
      v2:
        prometheus:
          configOverride:
            inboundSidecar:
              debug: false
              stat_prefix: istio
              metrics:
                - dimensions:
                    request_operation: "istio_operationId"
            outboundSidecar:
              debug: false
              stat_prefix: istio
              metrics:
                - dimensions:
                    request_operation: "istio_operationId"
                    request_path: "request.url_path"
            gateway:
              debug: false
              stat_prefix: istio
              disable_host_header_fallback: true
              metrics:
                - dimensions:
                    request_operation: "istio_operationId"
                    request_path: "request.url_path"
```
Instead of getting metrics like `istio_requests_total{request_path="/login"}`, I'm getting a whole bunch of new time series metrics with name like `envoy_request_path___login___istio_requests_total`.

It's the same as this issue https://github.com/istio/istio/issues/27281

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

Expected metric `istio_requests_total{request_path="/login"}`

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

Istio version 1.7.0, EKS 1.16

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by cristi-vlad** [comment]
I have exactly same issue in 1.7.0

**Comment by ediezh** [comment]
The workaround I use for gateway metrics is https://github.com/istio/istio/issues/28424#issuecomment-728375252

**Comment by douglas-reid** [comment]
@kyessenov this looks like an issue with regexes possibly. thoughts?

**Comment by Nicarim** [comment]
Issue still persists on 1.10.4

**Comment by yrobla** [comment]
I am experiencing the same issue on 1.12.2

**Comment by kyessenov** [comment]
Proxies need to be restarted to pick up this setting.
