### ISSUE TITLE
Implement a precheck analyzer

### ISSUE THREAD

**Issue by sdake** [istio/istio#28915]
**Describe the feature request**
Implement one precheck analyzer and track the relative cost of one analyzer addition for someone naive in analyzer development.

**Describe alternatives you've considered**
Request from TOC.

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

We ought to add quality as one of the features of Istio.....

**Additional context**
The original defect where an analyzer should detect problems is here:
The problem, described roughly, is some customers had determined a way to install gateways that wasn't documented and used side-effects of several bugs to work properly. The precheck (or analyzer) should determine this condition and point users at some form of corrective action documentation.

The specifics are documented here:
https://github.com/istio/istio/issues/28849

**Comment by esnible** [comment]
@sdake If you are no longer working on this please unassigned yourself.

**Comment by esnible** [comment]
@sdake If you are no longer working on this please unassigned yourself.

**Comment by sdake** [comment]
The idea was for someone without precheck experience to create an analyzer - to report the effective cost of the analyzer. This would help determine a selection process for analyzers, rather than ad-hoc implementation.

**Comment by therealmitchconnors** [comment]
This analyzer was built in 1.9, but has been held back from release because it reports many features which are on by default as alpha or experimental.  UX has committed to closing this gap in 1.11 by suppressing on by default alpha feature notifications.
