### ISSUE TITLE
Improve Virtual Machine debugging UX

### ISSUE THREAD

**Issue by stevenctl** [istio/istio#28930]
For Pods, we can use convenient commands like proxy-config and proxy-status. 
For VMs, the go-to seems to be "ssh and look at the logs". 

Opening this issue to explore equivalents and alternatives that we can bring to VMs. 

cc @yskopets

**Comment by howardjohn** [comment]
This is documented in https://preliminary.istio.io/latest/docs/ops/diagnostic-tools/virtual-machines/ and followup in https://github.com/istio/istio/issues/29052
