### ISSUE TITLE
Integration test infra does not support multicluster setup with kubernetes CA as global.pilotCertProvider

### ISSUE THREAD

**Issue by jtrbs** [istio/istio#28943]
Currently test case like https://github.com/istio/istio/blob/master/tests/integration/security/mtlsk8sca/main_test.go can not be converted into multicluster based because test infra multicluster setup does not work with https://github.com/istio/istio/blob/master/tests/integration/security/mtlsk8sca/main_test.go#L51

**Comment by jtrbs** [comment]
Discussed with Oliver. In this case, multi clusters setup does not work as kubernetes CA are different within clusters. Currently, using a single cluster is OK for the test.

**Comment by howardjohn** [comment]
Closing as working as intended?
