### ISSUE TITLE
Test immutability of shared objects, especially in XDS generation

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#28947]
For performance and simplicity, we pre-generate a lot of XDS objects, such as https://github.com/istio/istio/blob/e78224f921e0079871f40fdf1673adb7401f8368/pilot/pkg/security/model/authentication.go#L75.

This works well, unless we indirectly modify the shared object

```go
shared := &xds.Object{foo: bar}
...
x.field = shared
x.field.foo=not-bar
...
y.field = shared
// Oops! y.field.foo is now "not-bar"!
```

Especially at risk is EnvoyFilter merges - we had a case where we merged into a shared object so every iteration we added the object again and again due to list append logic.

Naive proposal:
* Introduce a new package, `immutable`, with a single function, say `immutable.New(interface{}) interface{}`
* When `-tags=test` is passed, this function modifies the object to panic when mutated. Possibly using https://github.com/lukechampine/freeze or equivilent
* When `-tags=test` is not passed, the function just returns the same object.
* Wrap all suspicious variables with this

**Comment by brian-avery** [comment]
@howardjohn what's the priority of this? Merging EnvoyFilters makes me think this might be related to WASM?

**Comment by howardjohn** [comment]
not stale

**Comment by howardjohn** [comment]
not stale

**Comment by howardjohn** [comment]
not stale

**Comment by howardjohn** [comment]
not stale

**Comment by howardjohn** [comment]
Not stale
