### ISSUE TITLE
TestLocalRateLimiting and TestLocalRouteSpecificRateLimiting test flakes

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#28949]
https://prow.istio.io/view/gs/istio-prow/logs/integ-k8s-115_istio_postsubmit/1328492321485885440
https://prow.istio.io/view/gs/istio-prow/logs/integ-telemetry-k8s-tests_istio_postsubmit/1328418485759381504
https://prow.istio.io/view/gs/istio-prow/logs/integ-telemetry-k8s-tests_istio_postsubmit/1328132703932911616

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28968/integ-telemetry-k8s-tests_istio/1328830075965018112

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gs/istio-prow/logs/integ-telemetry-k8s-tests_istio_postsubmit/1328973468040957952

**Comment by gargnupur** [comment]
Thanks.. I need to add some wait after applying EnvoyFilterPatch.. will send code for review...
