### ISSUE TITLE
Support set log level dynamically

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#28953]
**Describe the feature request**

It is very useful to allow reset the log level on the run, currently, it is very hard to diagnose some weird phenomena(hard to reproduce after restart) we met.

We can add a handler in debug, which calls `log.Configure`.

**Describe alternatives you've considered**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by ramaraochavali** [comment]
Yeah. That would be very useful

**Comment by howardjohn** [comment]
`istioctl x istiod log` will do this. And `istioctl pc log` does envoy. The only one that does not allow this is the agent

**Comment by hzxuzhonghu** [comment]
cool, thanks
