### ISSUE TITLE
HA ingress setup

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#2895]
Does it work and how do you configure more than 1 ingress pod ?

Is it possible to kill one of them and not get front end errors (or only a few errors) ?

**Comment by kyessenov** [comment]
Can you provide more context?
I think it's perfectly fine to run more than one ingress pod. The traffic gets load balanced at L4 prior to reaching ingress service (using VIP or front cloud load balancer).

**Comment by ldemailly** [comment]
Do you have an example config ?

https://github.com/istio/admin-sites/blob/master/fortio/ingress.yaml
this ^ is what I have in prod and it has 1 IP, are you saying I can just change istio-auth.yaml to have more than 1 ingress pod and it'll just work ?
(and upstream L4 load balancer will auto magically work and detect dead ingresses?)

**Comment by ldemailly** [comment]
Also ideally it would use https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/

**Comment by dkirrane** [comment]
What about on-prem. Is there `kube-keepalived-vip` integration?

**Comment by farcaller** [comment]
One option seems to be to expose your VIP to the router with kube-router.

**Comment by andraxylia** [comment]
This is fixed in 0.8.

**Comment by ldemailly** [comment]
do we have an example/task explaining how to set it uo?

**Comment by andraxylia** [comment]
You are right, there is none, re-opening.

**Comment by costinm** [comment]
Supported in 1.0, using helm options. Tested with the load test.

**Comment by andraxylia** [comment]
Can you point to the helm option or an example? This will need to be added to docs to be considered done.
