### ISSUE TITLE
Canary Upgrade with Operator Seems Unusable

### ISSUE THREAD

**Issue by joberdick-rcd** [istio/istio#28964]
**Bug description**
Canary upgrade using the operator does not result in a successful migration. 

[x] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure
[x] Upgrade

**Expected behavior**
That operator has a succesful migration via canary upgrades
**Steps to reproduce the bug**
Download Istio 1.7.4
Install a generic and versioned istio operator
```
istioctl operator init
istioctl operator init --revision 1-7-0
```
Then install the demo control plane
```bash
kubectl create ns istio-system
kubectl apply -f - <<EOF
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: example-istiocontrolplane
spec:
  profile: demo
EOF
```
Observe that both regular and versioned Istiod's are running. According to this [doc](https://istio.io/latest/docs/setup/install/operator/#uninstall), running the following will remove the original control plane: ``` istioctl operator remove --revision <revision>``` 
This doesn't work for a few reasons:
1. This does not remove the control plane. This only removes the operator.
2. This assumes the original control plane is versioned, it is not in these documented case linked above. Running ```istioctl operator remove``` removes both operators.

Since there is a single operator manifest. There is not a clear way to remove only the old control plane. 

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
client version: 1.7.4
control plane version: 1.7.4
Client Version: v1.17.0
Server Version: v1.18.9-eks-d1db3c
**How was Istio installed?**
see above
**Environment where bug was observed (cloud vendor, OS, etc)**
AWS

**Comment by howardjohn** [comment]
cc @ostromart

**Comment by ostromart** [comment]
Both operators must be revisioned, canary is not supported with non-revisioned operators in the mix until 1.8.

**Comment by morvencao** [comment]
update canary upgrade doc for in-cluster operator in https://github.com/istio/istio.io/pull/8589
