### ISSUE TITLE
BlackHole when REGISTRY_ONLY to GKE Metadata Server

### ISSUE THREAD

**Issue by Stono** [istio/istio#28994]
**Bug description**
With outboundTrafficPolicy `REGISTRY_ONLY`, and the following Service Entry:

```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: google-metadata-server
  namespace: istio-system
spec:
  hosts:
  - metadata.google.internal
  addresses:
  - 169.254.169.254/32
  endpoints:
  - address: 169.254.169.254
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: STATIC
  location: MESH_EXTERNAL
```

I still see failed requests to the metadata server in `istio-proxy`:

```
2020-11-18T12:41:45.033955Z debug envoy http  [C36][S1063564821710840340] request headers complete (end_stream=true):
':authority', '169.254.169.254'
':path', '/'
':method', 'GET'
'user-agent', 'gcloud-golang/0.1'
'accept-encoding', 'gzip'

2020-11-18T12:41:45.033967Z debug envoy http  [C36][S1063564821710840340] request end stream
2020-11-18T12:41:45.034060Z debug envoy filter  cannot find route entry
2020-11-18T12:41:45.034082Z debug envoy http  [C36][S1063564821710840340] Sending local reply with details direct_response
2020-11-18T12:41:45.034136Z debug envoy http  [C36][S1063564821710840340] encoding headers via codec (end_stream=true):
':status', '502'
'date', 'Wed, 18 Nov 2020 12:41:44 GMT'
'server', 'envoy'

2020-11-18T12:41:45.034220Z debug envoy wasm  wasm log: [extensions/stats/plugin.cc:609]::report() metricKey cache hit , stat=12
2020-11-18T12:41:45.034239Z debug envoy wasm  wasm log: [extensions/stats/plugin.cc:609]::report() metricKey cache hit , stat=6
2020-11-18T12:41:45.034244Z debug envoy wasm  wasm log: [extensions/stats/plugin.cc:609]::report() metricKey cache hit , stat=10
2020-11-18T12:41:45.034277Z debug envoy wasm  wasm log: [extensions/stats/plugin.cc:609]::report() metricKey cache hit , stat=14
2020-11-18T12:41:45.040300Z debug envoy filter  original_dst: New connection accepted
2020-11-18T12:41:45.040367Z debug envoy filter  [C37] new tcp proxy session
2020-11-18T12:41:45.040387Z debug envoy filter  [C37] Creating connection to cluster BlackHoleCluster
```

This is presumably because the app (cloudsql-proxy) is attempting to use a `Host: 169.254.169.254`.  There's no way to make it use a hostname however.  

It isn't clear to me if this is a bug, or a *won't fix* style issue.

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
1.7.4

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE 1.16

**Comment by howardjohn** [comment]
You have that exact ServiceEntry?

I tried and I see in the routes:
```
       {
        "name": "metadata.google.internal:80",
        "domains": [
         "metadata.google.internal",
         "metadata.google.internal:80",
         "169.254.169.254",
         "169.254.169.254:80"
        ],
```

which should match this. can you check the routes?

**Comment by Stono** [comment]
@howardjohn running the `routes` command didn't show the routes, which then immediately reminded me that we use `Sidecar.egress`.

As `egress:` expects an array of namespaces, and I created the `ServiceEntry` as a global thing in `istio-system`, I added `istio-system/*`, I added `istio-system/*` to that list, which then gave me the routes as expected

```
            {
                "name": "metadata.google.internal:80",
                "domains": [
                    "metadata.google.internal",
                    "metadata.google.internal:80",
                    "169.254.169.254",
                    "169.254.169.254:80"
                ],
```

The next error was cloudsql-proxy getting to the sqladmin api, which I solved with another service entry.  So for anyone coming to this issue, and using cloudsql-proxy with istio in `REGISTRY_ONLY`, this is what you need:

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: www.googleapis.com
spec:
  hosts:
  - www.googleapis.com
  - oauth2.googleapis.com
  - accounts.google.com
  - sqladmin.googleapis.com
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  - number: 80
    name: http
    protocol: HTTP
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: google-metadata-server
  namespace: istio-system
spec:
  hosts:
  - metadata.google.internal
  addresses:
  - 169.254.169.254/32
  endpoints:
  - address: 169.254.169.254
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: STATIC
  location: MESH_EXTERNAL
```

@howardjohn - i don't particularly want to have `istio-system/*` on the `egress:` section of `Sidecar` just to facilitate external hosts, is there a better way to do this?  I was thinking about moving them all into another namespace like, `external-services` or something and then using `external-services/*`?

**Comment by howardjohn** [comment]
the external services namespace seems like a good idea to ms

**Comment by Stono** [comment]
@howardjohn it feels a bit odd though as ServiceEntries to MESH_EXTERNAL are global, right (eg you couldn't define the same fqdn ServiceEntry in two different namespaces)?

**Comment by howardjohn** [comment]
You actually can define the same fqdn in different namespaces, as long as
only a single one is selected by Sidecar. This would allow a different
"view" of some external service by different namespaces

**Comment by Stono** [comment]
What happens if someone didn't (eg they didn't have a `Sidecar` resource, so received all routes), we'd have a conflict right?  

I don't see any metric that would capture that (eg something like `pilot_conflict_outbound_listener_http_over_http`)?
