### ISSUE TITLE
discoveryAddress use FQDN to support pod with default dnsPolicy

### ISSUE THREAD

**Issue by jiangshantao-dbg** [istio/istio#28991]
**Describe the feature request**
when pod use dnsPolicy=default，the /etc/resolv.conf without search options which cause pod can't connect with pilot (istiod.istio-system.svc:15012) and tracing (zipkin.istio-system:9411).

debug logs:
> 2020-11-18T08:17:08.946484Z	warn	Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 0 successful, 0 rejected; lds updates: 0 successful, 0 rejected
> 2020-11-18T08:17:06.109183Z	debug	envoy upstream	[external/envoy/source/common/upstream/strict_dns_cluster.cc:169] DNS refresh rate reset for istiod.istio-system.svc, (failure) refresh rate 5000 ms

**Describe alternatives you've considered**
manifests/charts/istio-control/istio-discovery/templates/configmap.yaml  `discoveryAddress` and `zipkin.address` can use FQDN to avoid depending on ClusterFirst dnsPolicy.
use `{{ (valueOrDefault .MeshConfig.TrustDomain .Values.global.trustDomain) }}`  to get domain postfix.
```
defaultConfig:
      tracing:
     ...
      {{- else if eq .Values.global.proxy.tracer "zipkin" }}
        zipkin:
          # Address of the Zipkin collector
          address: {{ .Values.global.tracer.zipkin.address | default (print "zipkin." .Values.global.istioNamespace ":9411") }}
     ...
      {{- if .Values.global.remotePilotAddress }}
         {{- if .Values.pilot.enabled }}
          discoveryAddress: {{ printf "istiod-remote.%s.svc" .Release.Namespace }}:15012
         {{- else }}
          discoveryAddress: {{ printf "istiod.%s.svc" .Release.Namespace }}:15012
         {{- end }}
      {{- else }}
      discoveryAddress: istiod{{- if not (eq .Values.revision "") }}-{{ .Values.revision }}{{- end }}.{{.Release.Namespace}}.svc:15012
      {{- end }}
```

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
This should be possible but its not trivial since we needto handle the certs as well.

BTW, `trustDomain` is the wrong field, it should be `.Values.global.proxy.clusterDomain`

**Comment by howardjohn** [comment]
you are welcome to use the `meshConfig.defaultConfig.discoveryAddress` setting and override this today. We definitely will not be changing the default, so I think there is no action needed here. Thanks

**Comment by jiangshantao-dbg** [comment]
i try this way, but this cause mutatingwebhookconfiguration and validatingwebhookconfiguration not work because the webhook use `istiod-v0109.mt-istio-system.svc` host but istiod's server certificate is invalid for it.
```
    message: 'Internal error occurred: failed calling webhook "sidecar-injector.istio.io":
      Post https://istiod-v0109.mt-istio-system.svc:443/inject?timeout=30s: x509:
      certificate is valid for istiod-v0109.mt-istio-system.svc.cluster.local, istiod.mt-istio-system.svc,
      istiod-remote.mt-istio-system.svc, istio-pilot.mt-istio-system.svc, not istiod-v0109.mt-istio-system.svc'
```
i also try to set `istiodRemote.injectionURL` and  `base.validationURL` to https://istiod-v0109.mt-istio-system.svc.cluster.local, but cause dns resolving error. 
```
    message: 'Internal error occurred: failed calling webhook "sidecar-injector.istio.io":
      Post https://istiod-v0109.mt-istio-system.svc.cluster.local/inject?timeout=30s:
      dial tcp: lookup istiod-v0109.mt-istio-system.svc.cluster.local on xxx.xxx.xxx.xxx:53:
      no such host'
```
kubernetes has comment with this issue 
```
        // The `host` should not refer to a service running in the cluster; use
	// the `service` field instead. The host might be resolved via external
	// DNS in some apiservers (e.g., `kube-apiserver` cannot resolve
	// in-cluster DNS as that would be a layering violation). `host` may
	// also be an IP address.
```

so i think there must be something to do to make it works.
