### ISSUE TITLE
Debian sidecar package seems malformed

### ISSUE THREAD

**Issue by wez470** [istio/istio#29011]
**Bug description**
Following https://preliminary.istio.io/latest/docs/setup/install/virtual-machine/#configure-the-virtual-machine, I get:
```
weston@instance-1:~$ curl -LO https://storage.googleapis.com/istio-release/releases/1.8.0/deb/istio-sidecar.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   212  100   212    0     0   4510      0 --:--:-- --:--:-- --:--:--  4608
weston@instance-1:~$ sudo dpkg -i istio-sidecar.deb
dpkg-deb: error: 'istio-sidecar.deb' is not a Debian format archive
dpkg: error processing archive istio-sidecar.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 istio-sidecar.deb
```
On step 4.

Running on GCE debian-10-buster-v20201112

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
The package is installed

**Steps to reproduce the bug**
Create VM described in description. Run:
```
curl -LO https://storage.googleapis.com/istio-release/releases/1.8.0/deb/istio-sidecar.deb
sudo dpkg -i istio-sidecar.deb
```

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

1.8

**Environment where bug was observed (cloud vendor, OS, etc)**

GCE debian-10-buster-v20201112 VM

**Comment by wez470** [comment]
Might be something to do with release versions actually. `curl -LO https://storage.googleapis.com/istio-release/releases/1.8.0/deb/istio-sidecar.deb` gives me a package that doesn't work, but from `curl -LO https://storage.googleapis.com/istio-release/releases/1.8.0-rc.0/deb/istio-sidecar.deb`, the package install correctly.

**Comment by howardjohn** [comment]
1.8.0 is not yet released, you are getting a 404:
```
$ curl https://storage.googleapis.com/istio-release/releases/1.8.0/deb/istio-sidecar.deb
<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: istio-release/releases/1.8.0/deb/istio-sidecar.deb</Details></Error>%
```

**Comment by wez470** [comment]
yup, thanks.
