### ISSUE TITLE
istioctl unit tests open up http://localhost:3456/ in browser

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#29022]
**Bug description**
Running istioctl unit tests opens http://localhost:3456/ in my browser

**Expected behavior**

Do not open my brwosers

**Steps to reproduce the bug**

`go test ./istioctl/...`

**Comment by esnible** [comment]
@daixiang0 I don't think your PR will close the issue.  To close the issue the unit tests should use the new flag.

**Comment by daixiang0** [comment]
It confuses me since my pr is to add a flag to fix it.

**Comment by esnible** [comment]
>It confuses me since my pr is to add a flag to fix it.

@daixiang0 Your PR could have a change to _dashboard_test.go_ adding your new flag to each of the test cases that opens a browser.

**Comment by paqlongperda6311-dot** [comment]
> **Bug description** Running istioctl unit tests opens http://localhost:3456/ in my browser
> 
> **Expected behavior**
> 
> Do not open my brwosers
> 
> **Steps to reproduce the bug**
> 
> `go test ./istioctl/...`
