### ISSUE TITLE
[istio 1.4.6] : nil pointer evaluating interface {}.enabled

### ISSUE THREAD

**Issue by rampatnaik** [istio/istio#29033]
Hello 

I am using istio 1.4.6 , while compling I am getting

executing "certmanager/templates/poddisruptionbudget.yaml" at <.Values.global.defaultPodDisruptionBudget.enabled>: nil pointer evaluating interface {}.enabled

role.yaml:4:7: executing "istio/charts/gateways/templates/role.yaml" at <($spec.sds) and (eq $spec.sds.enabled true)>: can't give argument to non-function $spec.sds

 rolebindings.yaml" at <$spec.sds.enable>: nil pointer evaluating interface {}.enable

my sds flag is false and mtls flag to false and lobal.defaultPodDisruptionBudget.enabled = true

**Comment by howardjohn** [comment]
Hi, sorry this isn't working for you. Unfortunately, Istio 1.4 is no longer supported https://istio.io/latest/news/support/announcing-1.4-eol-final/ and this code is no longer present in our code base at all, so we won't be able to fix this. Thanks!
