### ISSUE TITLE
istioctl ps or pc  adds debugging function for virtual machine  scenarios

### ISSUE THREAD

**Issue by tanjunchen** [istio/istio#29052]
**Describe the feature request**

the support for vm(istioctl ps)

**Describe alternatives you've considered**

istioctl ps vm176.vm(vm service)
Error: unable to retrieve proxy container name: unable to retrieve Pod: pods "vm176" not found

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[x] Developer Infrastructure

**Additional context**

```
[root@DEV2-10 ~]# istioctl ps
NAME                                                   CDS        LDS        EDS        RDS          PILOT                      VERSION
details-v1-7fc876d9b-j4k4z.vm                          SYNCED     SYNCED     SYNCED     SYNCED       istiod-c94d548f9-fsssv     1.6.0
istio-egressgateway-68f9874f87-qbb6f.istio-system      SYNCED     SYNCED     SYNCED     NOT SENT     istiod-c94d548f9-fsssv     1.6.0
istio-ingressgateway-55c4fb57fb-sdzws.istio-system     SYNCED     SYNCED     SYNCED     NOT SENT     istiod-c94d548f9-fsssv     1.6.0
productpage-v1-599cdfdc48-wzhz5.vm                     SYNCED     SYNCED     SYNCED     SYNCED       istiod-c94d548f9-fsssv     1.6.0
prometheus-c9cd8745c-jdmzp.istio-system                SYNCED     SYNCED     SYNCED     SYNCED       istiod-c94d548f9-fsssv     1.6.0
reviews-v1-78f7c7c79b-z5hf5.vm                         SYNCED     SYNCED     SYNCED     SYNCED       istiod-c94d548f9-fsssv     1.6.0
reviews-v2-6f8b778f49-s4skm.vm                         SYNCED     SYNCED     SYNCED     SYNCED       istiod-c94d548f9-fsssv     1.6.0
reviews-v3-85c6794cbb-jpwz7.vm                         SYNCED     SYNCED     SYNCED     SYNCED       istiod-c94d548f9-fsssv     1.6.0
socket-client-v1-85865fd6cb-l8nwd.tcp                  SYNCED     SYNCED     SYNCED     SYNCED       istiod-c94d548f9-fsssv     1.6.0
socket-server-v1-54c8bfc9-f4dg7.tcp                    SYNCED     SYNCED     SYNCED     SYNCED       istiod-c94d548f9-fsssv     1.6.0
vm176.vm                                               SYNCED     SYNCED     SYNCED     SYNCED       istiod-c94d548f9-fsssv     1.6.0
[root@DEV2-10 ~]# istioctl pc cluster vm176.vm
Error: failed to execute command on vm176.vm sidecar: unable to retrieve proxy container name: unable to retrieve Pod: pods "vm176" not found
```

**Comment by stevenctl** [comment]
related/part of: https://github.com/istio/istio/issues/28930

**Comment by esnible** [comment]
Do you have a proposal for how this might be solved?

The command `istioctl proxy-status <thing>` compares Istiod's belief with Envoy's belief about config, for troubleshooting things like Envoy rejecting Istiod's config.

The currently implementation of `istioctl proxy-status <thing>` is to fetch the config from istiod and the config from the pod and compare them.  The config is fetched from the pod by doing a port-forward and then a `GET .../config_dump`.  Will VMs have `/config_dump` exposed?  If so, how can _istioctl_ find out where?

In the past we talked about `proxy-status` taking a a URL argument.  That might be a way to solve this.  How would you feel about something like

```
istioctl ps
ssh -L 15000:vm176.vm:15000
istioctl ps vm176.vm --envoy localhost:15000/config_dump
```

?  If the `--envoy` arg was supplied, _istioctl_ could skip the port-forwarding and assume there was already a forwarded port, which VM users would set up manually.

**Comment by howardjohn** [comment]
There is a --file arg. See https://preliminary.istio.io/latest/docs/ops/diagnostic-tools/virtual-machines/  for how to use this.
