### ISSUE TITLE
VM tests fail with "transport: authentication handshake failed"

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#29053]
https://prow.istio.io/view/gs/istio-prow/logs/integ-k8s-117_istio_postsubmit/1329360721980428288

https://storage.googleapis.com/istio-prow/logs/integ-k8s-117_istio_postsubmit/1329360721980428288/artifacts/pilot-endpointslice-c08239c3b4c/_suite_context/echo-1-35111-state-649678145/cluster-0/vm-v1-598fc968f-mqwhn_istio-proxy.envoy.log

@stevenctl possibly related to your recent changes?

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gs/istio-prow/logs/integ-k8s-117_istio_postsubmit/1329438521563287552

Oddly it seems to always happen in the 117 endpointslice test... may be just luck though

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gs/istio-prow/logs/integ-k8s-117_istio_postsubmit/1329462687528128512

**Comment by howardjohn** [comment]
https://storage.googleapis.com/istio-prow/logs/integ-k8s-117_istio_postsubmit/1330981040914698240/build-log.txt

There is no way this is a coincidence that its happening on 1.17 endpointslice test only...

**Comment by howardjohn** [comment]
Ah looking closer, it actually has failed 100% of the time for 1.17, so its not flaky and just broken I think https://prow.istio.io/?job=integ-k8s-117_istio_postsubmit

**Comment by rinormaloku** [comment]
@howardjohn I am facing this issue when using [Plug in](https://istio.io/latest/docs/tasks/security/cert-management/plugin-ca-cert/) CA Certificates while I try to setup the following:

```
+----------+           +----------+
| Cluster1 +---------->+ Cluster2 |
+-----+----+           +----------+
      |
      v
    +-+-+
    |VM1|
    +---+
```

The connection between the clusters works. But not the connection from VM1 to Cluster1.

If I drop the Plug in CA Certificates, then the connection from Cluster1 to VM1 works (and understandably C1 -> C2 fails).

**Comment by stevenctl** [comment]
@rinormaloku – Changing the clusterName this way is likely to cause problems. The cluster ID that istiod uses internally is baked into the generated Deployment. The original ID will mismatch these updated ones in the meshNetworks config. 

https://github.com/istio/istio/blob/844b7aa92a9feaa222e0610159e48b81226d374c/manifests/charts/istio-control/istio-discovery/templates/deployment.yaml#L158-L159

Also, this issue with the tests seems to only affect Kubernetes 1.17 while pilot is running in EndpointSlice mode. It would be helpful to open a separate issue describing steps to reproduce your issue. Thanks!

**Comment by stevenctl** [comment]
So I've definitely verified that this does occur in any kind of 1.17 setup (GKE or KinD) and changing the test not to use endpointslice lets it pass. Going to start trying it with reverted commits to see if I can find what broke it.

**Comment by howardjohn** [comment]
I am super confused how endpointslice can lead to this.. I would think its completely independent. Will be interested to see what is the cause

**Comment by howardjohn** [comment]
Oh its going through the gateway, maybe the gateway gets incorrect config and that is where the breakage is

**Comment by stevenctl** [comment]
Still trying to track down why, but yeah the gateway doesn't have an istiod endpoint: https://storage.googleapis.com/istio-prow/logs/integ-k8s-117_istio_postsubmit/1329462687528128512/artifacts/pilot-endpointslice-3c2d337ff99/_suite_context/istio-state-673041765/cluster-0/istio-eastwestgateway-598c64dc4c-glbgb_proxy-clusters.txt

**Comment by funlake** [comment]
Got the same problem,anything news?
