### ISSUE TITLE
'make lint-helm-global' fails on release-1.7 branch

### ISSUE THREAD

**Issue by Monkeyanator** [istio/istio#29065]
On release-1.7 branch, `make lint-helm-global` fails with

```
find manifests -name 'Chart.yaml' -print0 | xargs -0 -r -L 1 dirname | xargs -r helm lint --strict -f manifests/charts/global.yaml
xargs: helm: No such file or directory
Makefile.core.mk:334: recipe for target 'lint-helm-global' failed
```

Bisect shows that it started failing after a [common files update](https://github.com/istio/istio/commit/b84be5951b3ee27706134c355951fa4f92bf370f).`

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[x] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Comment by elfinhe** [comment]
this will be resolved by https://github.com/istio/tools/pull/1342.

**Comment by elfinhe** [comment]
also we will have to wait for an update by automator, which can be tracked below:

https://github.com/istio/istio/pulls?q=is%3Apr+Automator%3A+update+common-files%40release-1.7+

**Comment by elfinhe** [comment]
resolved by https://github.com/istio/istio/pull/29217
