### ISSUE TITLE
how to setup internal and external loadbalancer  on 1.7.2 istio

### ISSUE THREAD

**Issue by rampatnaik** [istio/istio#29077]
how to setup internal and external loadbalancer  on 1.7.2 istio

**Comment by rampatnaik** [comment]
We need svc for 

 internal and external loadbalancer on 1.7.2 istio

**Comment by zufardhiyaulhaq** [comment]
@rampatnaik you can add multiple gateway in IstioOperator
```
  components:
    ingressGateways:
    - x
    - y
```

and add annotation for each ingressGateway if you want the LB service to be public or internal.

**Comment by rampatnaik** [comment]
yes I did external LB , now issues are with SSL for gke for external LB

**Comment by howardjohn** [comment]
You can have as many gateways as you want. See https://preliminary.istio.io/latest/docs/setup/install/istioctl/#configure-gateways

**Comment by rampatnaik** [comment]
Thanks , is there any chance for ilb-gateway for instio 1.7.* version ?
