### ISSUE TITLE
service-apis's Gateway cannot choose istio's gateway

### ISSUE THREAD

**Issue by nak3** [istio/istio#29078]
**Bug description**

- service-apis's Gateway cannot choose istio's gateway except for the istio gateway which has `istio: ingressgateway` label.
- As this TODO comment, it should be available by param ref.

https://github.com/istio/istio/blob/264d1540de50e900ad6a16cd2315fd525d83ef24/pilot/pkg/config/kube/gateway/conversion.go#L654-L655

[X] Networking

**Expected behavior**

- service-apis's Gateway can choose other istio's gateway rather than the gateway with `istio: ingressgateway` label.
- Knative uses two gateways (for external and internal) so this is necessary.

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

```
$ istioctl version
client version: 1.8.0
control plane version: 1.8.0
data plane version: 1.8.0 (1 proxies)
```

**Comment by howardjohn** [comment]
Yep, agreed. We have been looking into whether this should be a first class field in the API which was the main reason it was just hard coded for the short term

**Comment by howardjohn** [comment]
Not stale. Still want this, just need to figure out the right API

**Comment by nak3** [comment]
As Knative uses one deployment, selected by 2 services with two different Istio Gateways, so this issue is no longer a blocker. But it seems gateway-apis's Gateway always uses default istio-ingressgateway service.
@howardjohn could you please take a look at https://github.com/istio/istio/issues/31746 ?

**Comment by howardjohn** [comment]
Fixed by https://github.com/istio/istio/pull/32653. Would be great if you can try this out!

**Comment by nak3** [comment]
@howardjohn It works in general (e.g. points to the service by NamedAddress) but it does not work for Knative's "second" service. Could you please take a look https://github.com/istio/istio/issues/33298 ?
