### ISSUE TITLE
Possible CPU utilization regression in proxy from 1.8 to master

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#29087]
![2020-20-11_09-09-18](https://user-images.githubusercontent.com/623453/99828697-25e27000-2b10-11eb-9591-bfc534f1d928.png)

Its possible its just due to the rollout and would stabilize after a few days, I needed to tear down my cluster though

I checked istio-agent CPU usage and its unchanged so probably all envoy

cc @richardwxn

**Comment by howardjohn** [comment]
@carolynhu did you see this in benchmarks?

**Comment by carolynhu** [comment]
@howardjohn Just checked, from benchmark i did not see this for CPU section, but did see regression happens on the latency part, but one or two days later, the number comes back. Therefore, I did not mark it as a regression.  Maybe we could wait several days more?

**Comment by howardjohn** [comment]
cannot reproduce, and neither can Carolyn, so assume it was a bad measurement or regression that has been fixed: https://snapshot.raintank.io/dashboard/snapshot/fxikRpMb1T1OjvYAomlBJPVB1NGSj9Uu
