### ISSUE TITLE
Istiod validationServer unrecognized type instance flood

### ISSUE THREAD

**Issue by cober** [istio/istio#29093]
**Bug description**
We are seeing constant message flood on istiod
```2020-11-20T18:18:35.139363Z     info    validationServer        unrecognized type instance
2020-11-20T18:18:35.294707Z     info    validationServer        unrecognized type instance
2020-11-20T18:18:35.302958Z     info    validationServer        unrecognized type instance
2020-11-20T18:18:35.494957Z     info    validationServer        unrecognized type instance
2020-11-20T18:18:35.499724Z     info    validationServer        unrecognized type instance
2020-11-20T18:18:35.695297Z     info    validationServer        unrecognized type instance
2020-11-20T18:18:35.700524Z     info    validationServer        unrecognized type instance
2020-11-20T18:18:35.895377Z     info    validationServer        unrecognized type instance
2020-11-20T18:18:35.900836Z     info    validationServer        unrecognized type instance

r>kubectl get instance -A
NAMESPACE      NAME                   AGE
istio-system   attributes             519d
istio-system   requestcount           401d
istio-system   requestduration        401d
istio-system   requestsize            401d
istio-system   responsesize           401d
istio-system   tcpbytereceived        401d
istio-system   tcpbytesent            401d
istio-system   tcpconnectionsclosed   401d
istio-system   tcpconnectionsopened   401d
```

Is there any workaround for this?

[ ] Docs
[ ] Installation
[ ] Networking
[X] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure
[X] Upgrade

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
client version: 1.8.0
control plane version: 1.8.0
data plane version: 1.8.0 (28 proxies), 1.7.4 (4 proxies)

**How was Istio installed?**
istioctl install

**Environment where bug was observed (cloud vendor, OS, etc)**
GKE 1.18.10-gke.2101

**Comment by howardjohn** [comment]
This sounds like you have configured your validating webhook (or, we have configured it) to send the legacy mixer types to the new 1.8 server which doesn't support mixer types anymore

**Comment by howardjohn** [comment]
Ah
```
    rules:
    - apiGroups:
      - config.istio.io
      - security.istio.io
      - authentication.istio.io
      - networking.istio.io
```

we should probably remove config.istio.io

**Comment by howardjohn** [comment]
Actually we may just want to just filter these out in the webhook code

@jasonwzm @istio/wg-policies-and-telemetry-maintainers any thoughts

**Comment by bianpengyuan** [comment]
Not sure if there is other configuration under config.istio.io, but if mixer resources are the only part, we should just remove it.

@cober Work around is just to delete those instances, they are not functioning any more in since 1.8.

**Comment by douglas-reid** [comment]
@bianpengyuan did we ever add warnings for mixer config on upgrade? i thought that was part of the work.  was it just for non-customized config?

**Comment by howardjohn** [comment]
> Not sure if there is other configuration under config.istio.io, but if mixer resources are the only part, we should just remove it.

I don't think we are

What is the expected behavior for 1.8? I would think we should ignore the mixer types, whereas right now we are rejecting them.

**Comment by bianpengyuan** [comment]
> @bianpengyuan did we ever add warnings for mixer config on upgrade? i thought that was part of the work. was it just for non-customized config?

I think the warning is for mixer resources that user created themselves, but @richardwxn would know better.

> What is the expected behavior for 1.8? I would think we should ignore the mixer types, whereas right now we are rejecting them.

I think we could just ignore it, which is less confusing.

**Comment by jasonwzm** [comment]
+1 to remove it from the configuration. I don't think we should add more hacky logic in validation code. 

If we declare in the configuration, it still means we are supporting validating the object which we are not.
