### ISSUE TITLE
Need to remove illegal characters from remote secret names

### ISSUE THREAD

**Issue by nmittler** [istio/istio#29101]
Cluster names on various platforms can contain characters that are not allowed in k8s resource names. We should remove any illegal characters when creating the secret name.

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by stevenctl** [comment]
This would need to be consistent in every place we use clusterID

**Comment by nmittler** [comment]
After some discussion, we've decided to retain the existing restrictions on cluster names.
