### ISSUE TITLE
Istio-docs inconsistent

### ISSUE THREAD

**Issue by rverma-jm** [istio/istio#29102]
**Bug description**
1. Missing page for multi-cluster setup
2. At page https://istio.io/latest/news/releases/1.8.x/announcing-1.8/upgrade-notes/, istiod-gateway.yaml is a dead link

[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by bianpengyuan** [comment]
Thanks for raising this! which page for multi cluster is missing?

**Comment by shamsher31** [comment]
The `istiod-gateway` folder does not exist in the `samples` folder. 
```
kubectl apply -f samples/istiod-gateway/istiod-gateway.yaml
```
