### ISSUE TITLE
extend ProxyConfig to include client TLS settings for the discovery service (istiod)

### ISSUE THREAD

**Issue by yskopets** [istio/istio#29108]
**Context**

* Consider mesh expansion scenario
  * `Istio Proxy` is running on a VM outside of k8s cluster
  * `Istio Proxy` needs to connect to the `Discovery Service` (`istiod`) using an external DNS name (such as AWS ELB)
* At the moment, `ProxyConfig` has only one relevant setting - `discovery_address`
* In practice, it means that if an `Istio Proxy` is using an external DNS name to connect to the `Discovery Service` (`istiod`), the server certificate must include that DNS name as a SAN

**Describe the feature request**

* To improve UX when it comes to configuring Istio for mesh expansion:
  * extend `ProxyConfig` to include client TLS settings for the `Discovery Service` (`istiod`)
  * it will allow `istiod` to keep using its out-of-the-box server certificate provisioned for `istiod.istio-system.svc`
  * while `Istio Proxies` will be able to connect to it using environment specific DNS names (such as AWS ELB) but still verify for `istiod.istio-system.svc` as a SAN  

**Describe alternatives you've considered**

* At the moment, `istiod` has `ISTIOD_CUSTOM_HOST` environment variable that `allows a user to bring a custom address for istiod server, such as 'istiod.mycompany.com'`
  * On the downside, this approach complicates installation and management of Istio deployment (one would need to force Istio to recreate the server cert of `istiod` every time its external DNS names change)
* Alternatively to changing `ProxyConfig`, we could add a new environment variable to `pilot-agent`, e.g. `DISCOVERY_SERVICE_SAN`
  * On the downside, this approach obfuscates configuration options from a user perspective

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
You can also send the xds connection through a gateway and terminate tls there now that we are using jwt authentication
