### ISSUE TITLE
Envoy proxy produces too many metrics, and prometheus scraping overhead matters badly.

### ISSUE THREAD

**Issue by qianweichun** [istio/istio#29110]
**Bug description**
Envoy proxy produces too many metrics. Prometheus scraping network bandwidth could be too high.
The scaped data size is nearly 8MB each. I have attached a sample scraped package:
[scrape.txt.zip](https://github.com/istio/istio/files/5580926/scrape.txt.zip)
<img width="606" alt="2020-11-23 上午10 56 46" src="https://user-images.githubusercontent.com/45196316/99925863-a3111d80-2d7a-11eb-88da-57ba7a577878.png">

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[x] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
istio version:1.6.13
Kubernetes version:v1.15.6

**How was Istio installed?**
istioctl install 
**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by qianweichun** [comment]
The reason is sidecar.istio.io/statsInclusionPrefixes: cluster.output, I only need envoy_cluster_upstream_rq_time. How could i add only envoy_cluster_upstream_rq_time?

**Comment by howardjohn** [comment]
@bianpengyuan ^

**Comment by bianpengyuan** [comment]
You can use `sidecar.istio.io/statsInclusionSuffixes: upstream_rq_time` instead to only include this particular stats.

**Comment by qianweichun** [comment]
I used sidecar.istio.io/statsInclusionRegexps: ^cluster\.outbound.*upstream_rq_time$ to only include the required stats.
But it did not excluded the other metrics as expected, it seems that the default collection keys cluster_manager/listener_manager/server/cluster.xds-grpc are not overrided as documented.

**Comment by bianpengyuan** [comment]
Stats inclusions are always in addition to the default minimum stats set. 1.6 doc is indeed ambiguous on this, but the latest 1.8 doc is pretty clear that these are used to configure additional stats.

**Comment by qianweichun** [comment]
@bianpengyuan ok, thanks
