### ISSUE TITLE
Envoy suddenly stop accepting tcp connection in ports 15001 and 15006 

### ISSUE THREAD

**Issue by haniceboy** [istio/istio#29113]
**Bug description**
We have a k8s cluster in a production environment with istio installed. Some of pods enabled istio。 Now I have a weird problem that an instance of a service enabled istio was working normally, but it will suddenly restart continuously. The service configured with k8s liveness probe (i.e. ip:8080/healthy/heartbeat) and that probe caused the containter restart. The istio-proxy container looked like normal and the liveness of it worked well.
I logged in the istio-proxy container and service container respectively, and found:
    1. There was no any issue for the service container, and "curl -v localhost:8080/healthy/heartbeat" responsed 200 always. 
    2. The admin port 15000 of envoy worked well. The interfaces "/server_info", "/logging", "/listeners", "/config_dump" worked well.
    3. The config (listener, route, cluster and endpoint) of envoy was good.
    4. In istio-proxy container, I found the recv-Q of 15001(virtualOutbound) and 15006 (virtualInbound) were not zero. 
```
    istio-proxy@bcs-ctrip-default-7994bd967c-hhkm5:/$ netstat -nltp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:8009            0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:15020           0.0.0.0:*               LISTEN      1/pilot-agent
tcp        0      0 127.0.0.1:8527          0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:15090           0.0.0.0:*               LISTEN      62/envoy
tcp        0      0 0.0.0.0:1234            0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:15000         0.0.0.0:*               LISTEN      62/envoy
tcp        2      0 0.0.0.0:15001           0.0.0.0:*               LISTEN      62/envoy
tcp        129  0 0.0.0.0:15006           0.0.0.0:*               LISTEN      62/envoy
```

I think the issue was envoy didn't accept tcp connection  at that time, but I did't know the reason. Before the issue happened, the envoy worked well and it could forward the request to the backend container.  
Is there anyone know what happended or give some clues?

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ X] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**
 I cannot 100% reproduct the issue, however the service (two instances) could randomly meet the issue once a week.  The service is a java backend using tomcat and deployed as a jar.

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
  istioctl version --remote
      client version: 1.4.7
      control plane version: 1.4.7
  kubectl version --short
      Client Version: v1.16.3
      Server Version: v1.16.3

**Comment by howardjohn** [comment]
So its still listening but not accepting connections? Interesting... cc @lambdai 

Btw - istio 1.4 has been EOL for a long time, even if we root cause this bug we may not be able to fix it: https://istio.io/latest/news/support/announcing-1.4-eol-final/

**Comment by haniceboy** [comment]
@howardjohn Yes, you are right that the envoy stop accepting connection. I guess 80% probability it's envoy issue.  I tried to kill the envoy process in istio-proxy container causing envoy restart but not container, and I saw the issue disapper.  Do you know who meet the same issue?
Thanks reminding me the istio 1.4 was in EOL. Because there is a big leap from 1.5, so we haven't prepared the upgrade.

**Comment by haniceboy** [comment]
Does anyone know what happened here?

**Comment by lambdai** [comment]
Yeah, reaching the likely value of Send-Q highly indicated that envoy stop accepting new requests.

I cannot explain why envoy is doing this: Envoy is simply polling the listening sockets and accept. Envoy would rather crash if accept() fails. 

The reasonable cause is Envoy is told not to accept new connections. AFAIK, In Istio world port 15006 and 15001 are always legit listeners until the container exits.

You can try those:
1. Turn on debug level log of envoy to see if pilot somehow not sending 15001 listeners.
2. Double check if the pod is exiting.
3. Strace on Envoy to see if Envoy is stuck somewhere.
