### ISSUE TITLE
istio/tools: present istio performance comparison results among different istio releases

### ISSUE THREAD

**Issue by carolynhu** [istio/istio#29136]
Based on Istio users' feedback on slack

- [ ] We should promote the istio performance dashboard https://perf.dashboard.istio.io/, so that istio users would know the current status of istio performance

- [ ] Also, since our benchmark job is running on a daily builds, which is the alpha builds, we should run against the official releases as well and present the comparison results 

- [ ] The user also suggest, we should keep istio performance and scalability page in sync with each release or mark it as stale before we publish the perf number for the latest release.

cc @howardjohn @craigbox @brian-avery @frankbu

**Comment by RaghavRoy145** [comment]
@craigbox If this issue is still open I would like to work on this to start contributing to istio. Do I need to manually assign myself this issue?

**Comment by craigbox** [comment]
There's no `/assign` bot here, but you can (if you're a member?) assign yourself issues on GitHub, and you're welcome to work on anything!

**Comment by howardjohn** [comment]
This issue may be challenging to pick up since I think the entire data/test pipeline for the site is broken

**Comment by howardjohn** [comment]
Given the entire site is removed, I don't think this issue is valid. There may be a request in general to review a perf trackng system, though
