### ISSUE TITLE
open /dev/shm some files error：permission denied

### ISSUE THREAD

**Issue by feimeng1029** [istio/istio#29141]
if /dev/shm/ directory has some dirs not files and these dirs have 750 permissions，pilot-agent will error and then will delete
config file envoy-recv0.yaml.It will make envoy not work.

Oracle is installed on my server, and Oracle contains a directory with 750 permissions. This error was reported when I installed pilot agent on this machine. In this case, I can't install pilot agent on this machine.

I understand that /dev/shm is a public shared memory directory, so pilot-agent should not prevent other applications from installing or accessing it

![image](https://user-images.githubusercontent.com/37317258/100057904-50f7f700-2e63-11eb-9b11-cb4aa02ff8d0.png)
![image](https://user-images.githubusercontent.com/37317258/100057921-59e8c880-2e63-11eb-814e-b00fd00b2b67.png)

**Comment by howardjohn** [comment]
Are you sure you are running istio? None of these logs are in istio code... Can you give more info about how you installed?

**Comment by feimeng1029** [comment]
> Are you sure you are running istio? None of these logs are in istio code... Can you give more info about how you installed?

This is the log of pilot-agent

**Comment by howardjohn** [comment]
of which version?

**Comment by feimeng1029** [comment]
> of which version?

I use the older version of isto, which is 1.0

**Comment by howardjohn** [comment]
@feimeng1029 please upgrade to a supported version, we cannot help with ancient versions released almost 2 years ago. Thanks!

https://istio.io/latest/about/supported-releases/
