### ISSUE TITLE
istio-1.8.0 install problem

### ISSUE THREAD

**Issue by hillbun** [istio/istio#29143]
I use ./bin/istioctl install --set profile=demo to install istio-1.8.0

```
kubectl get pods -n istio-system  
NAME                                    READY   STATUS    RESTARTS   AGE
istio-egressgateway-75dbd877cb-hrtwm    1/1     Running   0          21m
istio-ingressgateway-756879c745-gh6ns   1/1     Running   0          21m
istiod-6bf46fc8cc-pd67s                 1/1     Running   0          21m
```

only istio-egressgateway, istio-ingressgateway, istiod are installed.

grafana, istio-tracing , kiali, prometheus are missing.

Any advice?

**Comment by shamsher31** [comment]
Grafana, Prometheus, etc are available as an add-on integration and removed from `demo` profiles.

https://istio.io/latest/docs/ops/integrations/
