### ISSUE TITLE
istioctl pre-upgrade check

### ISSUE THREAD

**Issue by esnible** [istio/istio#29156]
This item is to make the upgrade process do real safety checks.  It is unclear if this shall be part of `istioctl install`, `istioctl x precheck`, or both.

Currently we check K8s and Istio version.

We MUST also invoke the deprecation analyzer to make sure the user is not using deprecated CRs or fields.
We MUST also look for release-specific problems, such as the custom gateway upgrade problem of 1.8.

**Comment by shamsher31** [comment]
As we were discussing adding `precheck` to `upgrade` and `install` commands. Looks like we do perform a k8 compatibility check during install and upgrade which is then same used in the `precheck` command.

During install
https://github.com/istio/istio/blob/88a2bfb3bd8e0010229ee66befc4e56b326c2a3a/operator/cmd/mesh/install.go#L142-L144

During upgrade
https://github.com/istio/istio/blob/be6a4f9f194c721617575de0f1defee656ae4d3e/operator/cmd/mesh/upgrade.go#L145-L147

The message looks sufficient to provide an incompatibility warning.
https://github.com/istio/istio/blob/09f82950a0bdf1d13f501870581a4a8a2c8127bc/istioctl/pkg/install/k8sversion/version.go#L78-L83
