### ISSUE TITLE
istioctl: Promote or remove istioctl CLI features

### ISSUE THREAD

**Issue by esnible** [istio/istio#29153]
Using the [review of CLI features](https://docs.google.com/document/d/16M6ItjYl5M8ppLlJ5JYTfrcXBrtSQlYKIUgOk31wXdQ/edit) we did, promote commands we like out of `experimental` and remove commands we no longer like.

To promote a command out of experimental we MUST have an integration test and SHOULD have a doc test.

**Comment by esnible** [comment]
@carolynhu I will discuss https://docs.google.com/document/d/1sHpqT8mX8BN7DaoGd8rWk0cSjqdsTkxJy5zX2Cyfmp0/edit# tomorrow at UX meeting.

**Comment by carolynhu** [comment]
related issue: https://github.com/istio/istio/issues/29591

**Comment by carolynhu** [comment]
bug found and filed: https://github.com/istio/istio/issues/29676
