### ISSUE TITLE
stop explosion of prow jobs for upgrade/downgrade tests

### ISSUE THREAD

**Issue by su225** [istio/istio#29152]
We started with 4 prow jobs for upgrade and downgrade
* upgrade (2 jobs - prev->cur, prev_prev->prev)
* downgrade (2 jobs)

We then added **dual-control-(upgrade|rollback)** scenarios and created 4 more jobs for it.

https://github.com/istio/tools/pull/1303 - As part of this, two more scenarios were added. If we go this route, we would end up adding 4 more jobs. We have to find some way to prevent this - one way is to run multiple scenarios as part of the same job as follows
1. Provision a new Kubernetes cluster
2. Run the scenario
3. Destroy the cluster

To speed up, we can run multiple tests in parallel.  

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[X] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Comment by ostromart** [comment]
Some overhead here is cluster setup/teardown. In general it's good to start with a clean slate but at some point that becomes impractical and you have to clean the cluster after the test so other tests can run. I suggest looking at whether these tests really leave behind too many changes or if they can be cleaned up by removing all installed resources.

**Comment by su225** [comment]
Before starting every test, we clean all resources in the cluster. See `reset_cluster` function in `common.sh`

**Comment by brian-avery** [comment]
@su225 sounds like there's still work to do here?

**Comment by su225** [comment]
I did not add more scenarios here and there is no change in job configs either.
