### ISSUE TITLE
analyzers for experimental and alpha features

### ISSUE THREAD

**Issue by esnible** [istio/istio#29154]
These analyzers will create INFO level messages if users are using CRs or CR fields that are experimental or alpha.

The feature stages are documented at https://istio.io/latest/about/feature-stages/

There may also be a non-analyzer component if there are things the analyzers don't see that are important (environment variables?)

- For annotations, we depend on https://github.com/istio/api/pull/1723
- For CRs, we use the `deprecated` flag in _pkg/config/schema/metadata.yaml_ (see https://github.com/istio/istio/commit/8211426ebcd6855dea70ef59e327effa0d41bf45#diff-857a914e3c512d9cea95c866f175a9b50b8c7296979c14c8b1c065f6e5ce08ba , currently no known types are deprecated)
- For individual fields in CRs _galley/pkg/config/analysis/analyzers/deprecation/deprecation.go_ has ad-hoc code for deprecated fields (e.g. `OutboundTrafficPolicy.EgressProxy`.  We need either similar ad-hoc code for alpha fields, or a table of path expressions for alpha fields per type.

**Comment by esnible** [comment]
@jasonwzm It would be helpful to be able to tell the 'real' vs 'converted' CR `version` to see if the version includes `alpha`.  Is it possible to obtain that using the current design?

**Comment by esnible** [comment]
@howardjohn @nrjpoddar It would be very helpful if the there was a declarative specification of which fields are experimental, deprecated, or alpha within all CRDs.

In istio/istio it might make sense to add fields to _https://github.com/istio/istio/blob/master/pkg/config/schema/metadata.yaml_.  For example, I believe `delegate` in VirtualService is still experimental or alpha?  So we could add

```
  - kind: "VirtualService"
    plural: "virtualservices"
    ...
    alpha:
       - spec.http[*].delegate
```

Can you think of a better place to put this?  Somewhere in istio/api?

```

**Comment by nrjpoddar** [comment]
@esnible the status of a field within a CR API would need to be surfaced to end users in documentation too so however that will be done, I would recommend that the `istioctl` tooling uses the same underlying mechanism. Having two sources of information can lead to confusion and stale data. 

How do we currently mark status of any field within the API reference or docs?

**Comment by esnible** [comment]
If my understanding is correct

- deprecated fields are marked `$hide_from_docs` in the _.proto_ file.  This info is exposed to the docs, but not programmatically.  _deprecation.go_ has ad-hoc code that is written when someone notices a field has been hidden.
- We don't have any mechanism to indicate `alpha`, `beta`, or `stable` for individual fields.

Could we use struct tags for this?  Somehow get the .proto to .pb.go converter to add `istio-api-level:"deprecated"` to fields with `$hide_from_docs`?  Somehow get another struct tag value for "alpha"?

**Comment by esnible** [comment]
Note that https://github.com/istio/api/pull/1723 has merged so we can now pick up feature status programmatically.

**Comment by esnible** [comment]
We have merged the annotation analyzer.  The feature phase analyzer for individual fields work is still outstanding.
