### ISSUE TITLE
promote "CRD status" feature to beta

### ISSUE THREAD

**Issue by esnible** [istio/istio#29157]
@therealmitchconnors please describe in more detail here.

Also includes addressing the CRD status issues:

- [ ] [Istiod restart seems to break `istioctl wait`](https://github.com/istio/istio/issues/27330)

**Comment by carolynhu** [comment]
yeah, I have the same question, @therealmitchconnors do we have any detailed plan? if there is a doc associated with this?

**Comment by esnible** [comment]
@carolynhu I will discuss https://docs.google.com/document/d/1sHpqT8mX8BN7DaoGd8rWk0cSjqdsTkxJy5zX2Cyfmp0/edit# tomorrow at UX meeting.
