### ISSUE TITLE
Failed to pull image "docker.io/istio/operator:1.8-dev" error in operator after istioctl upgrade via brew on MacOS

### ISSUE THREAD

**Issue by Keramblock** [istio/istio#29155]
**Bug description**

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
1.8.0 Installed

**Steps to reproduce the bug**
Install latest istioctl via brew, try to deploy istio operator

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
brew info istioctl
istioctl: stable 1.8.0 (bottled), HEAD
Istio configuration command-line utility
https://github.com/istio/istio
/usr/local/Cellar/istioctl/1.8.0 (7 files, 110.2MB) *
  Poured from bottle on 2020-11-23 at 17:35:54
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/istioctl.rb

istioctl version --remote
client version: 1.8-dev
control plane version: 1.7.4
data plane version: 1.7.4 (14 proxies)

kubectl version --short
Client Version: v1.19.3
Server Version: v1.17.9-gke.6300

**How was Istio installed?**
using istioctl and operator
**Environment where bug was observed (cloud vendor, OS, etc)**

**Comment by Monkeyanator** [comment]
Related [https://github.com/istio/istio/issues/29142](https://github.com/istio/istio/issues/29142)

**Comment by Monkeyanator** [comment]
Fixed with [https://github.com/Homebrew/homebrew-core/pull/65626](https://github.com/Homebrew/homebrew-core/pull/65626), should work after updating homebrew and reinstalling istioctl package (i.e. `brew uninstall --force istioctl; brew update; brew install istioctl;`)
