### ISSUE TITLE
AZ fetching doesn't work if auth is on

### ISSUE THREAD

**Issue by costinm** [istio/istio#2916]
Current code seems to fetch from pilot, but doesn't seem to setup the certificates, so if auth is 
enabled it fails. Pilot/mixer/etc are now also secured when auth is on. 
We currently listen on both 8080 (insecure) and 15003 (secure if control plane mtls is on), but 
I think it would be cleaner if 15003 would have mTLS on regardless of global auth setting (there
is a separate issue explaining why).

One short term fix is for agent to load az from 8080.
If we make 15003 mTLS in all cases - we can use 8080 only if there are no certificates ( i.e. CA is 
turned off ).

**Comment by ldemailly** [comment]
(possibly silly question but) why is az fetching different from *ds fetching which works fine with auth?

**Comment by kyessenov** [comment]
AZ local node metadata seems to be provided through a different API than
data-plane-api, since it's defined in the bootstrap configuration. I think
there's opportunity to make a bunch things in the bootstrap more dynamic,
but someone needs to drive the effort in data-plane-api.

**Comment by liamawhite** [comment]
Will look into it when I have some spare time. @kyessenov have dm'd you on slack with some questions I have around my understanding of the auth stuff.

**Comment by kyessenov** [comment]
Have we ruled out using envoy to perform the lookup? We meed to open a locally secure listener on the proxy to access management server from the agent.

**Comment by kyessenov** [comment]
This was discussed multiple times. @rshriram @myidpt for some background if you remember.

**Comment by myidpt** [comment]
I think we need to introduce a controlPlaneAuthPolicy to istio configmap, which is default to "MUTUAL_TLS". So that the auth of control plane is untied from service auth.
For this work, I think either I or someone from my team can work on it.

**Comment by liamawhite** [comment]
Currently unable to call securely going directly to pilot. Have created a PR in order to inform users rather than throw an error from a timeout https://github.com/istio/istio/pull/3873. @cmluciano has agreed to look at [this](https://github.com/envoyproxy/envoy/issues/2541) Envoy issue that would remove the need for an AZ look up at all.

**Comment by liamawhite** [comment]
Will look into @kyessenov's suggestion above.

**Comment by liamawhite** [comment]
Resolved by #3913
