### ISSUE TITLE
Canary Upgrade instructions using the operator could use some clarification

### ISSUE THREAD

**Issue by snuggie12** [istio/istio#29176]
**Describe the feature request**
The canary upgrade section for the operator is a bit unclear on steps and environment. Here are some questions/comments:
- When starting the canary upgrade, should we delete the old istio-operator pod? What about the `IstioOperator` resource?
- Here are my steps, is this correct?
1. Uninstall the old operator, but leave the CR around
2. Install the new operator following the existing instructions
3. Fix the `IstioOperator` resource (for instance, I had fields that no longer existed.)
4. If you have no merge errors, it should create an istiod pod with the version as a revision (e.g. 1-7-4).
5. However, what isn't clear is that you should also update your tag on your `IstioOperator`. I was unsure if this would delete my old `istiod` (non revisioned one), but it appears as if I should have done this in step 3?
6. Update dataplane as the instructions say.
- Maybe I was reading the page wrong, but I then took the "Uninstall" section as the next set of steps. Should I be removing my operator and `IstioOperator` which will then leave everything else in place?

**Describe alternatives you've considered**

[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
This was meant to be closed by https://github.com/istio/istio.io/pull/8589 as far as I can tell
