### ISSUE TITLE
limits for defaultResources could not be applied.

### ISSUE THREAD

**Issue by jmyung** [istio/istio#29192]
**Bug description**

limits for defaultResources could not be applied.

For IstioOperator, I apply like this.

```
kubectl apply -f - <<EOF
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-controlplane
spec:
  profile: default
  meshConfig:
    accessLogFile: /dev/stdout
  tag: 1.7.4
...
      defaultResources:
        requests:
          cpu: 10m
          memory: 40Mi
        limits:
          cpu: 50m
          memory: 200Mi
EOF
```

However 

```
$  kubectl logs -nistio-operator istio-operator-5976d5d746-lb74l

...
2020-11-25T11:43:37.700655Z     error   failed to generate IstioOperator spec, unknown field "limits" in v1alpha1.DefaultResourcesConfig
```
Is limits property forbidden in Istio 1.7 ? (I can't find any explanation for this)
I remember applying limits in Istio 1.5.1.
 
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

```
$ istioctl version --remote
client version: 1.7.4
control plane version: 1.7.4
data plane version: 1.7.4 (2 proxies)

$ kubectl version --short
Client Version: v1.17.3
Server Version: v1.17.3
```

**How was Istio installed?**
Istio Operator Install

**Comment by morvencao** [comment]
Suggest to use k8s settings to set resource requests and limits for each component, see: https://github.com/istio/istio/blob/master/operator/samples/pilot-k8s.yaml
