### ISSUE TITLE
[Multicluster]  Add NodePort Multicluster Install Without LB Doc

### ISSUE THREAD

**Issue by yanickxia** [istio/istio#29195]
**Describe the feature request**

**Describe alternatives you've considered**

[ ] Docs
[ x ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**
Almost , we try demo in private k8s cluster without loadblancer,  Please add Doc for this case

**Comment by rinormaloku** [comment]
Hi @yanickxia 

If you have a direct connection between the VMs then you don't need a NodePort (which I guess you want to open for the eastwest gateway)

**Comment by yanickxia** [comment]
@rinormaloku  i'm try install `Install Primary-Remote on different networks`   with loadblancer,  it's not easy, modify `svc` to `NodePort` and update the mesh networks config of `istiod Configmaps`, do you have any suggest?

**Comment by rinormaloku** [comment]
If the primary and remote are on different networks, then NodePort should not work, because the IP is private to the network.

If the different networks are peered; or somehow provide a direct connection between the nodes, then the NodePort makes sense, but why not use a solution for on the same network? i.e. skip east west gateway entirely and the pods call each other directly?

**Comment by yanickxia** [comment]
it's demo/test for `Primary-Remote on different networks`

`primary` and `remote` has different  `overlay network`, but they are commutation with `host` networks. just show case for other people.

almost customer just want to see what kind of ability to provide.

**Comment by rinormaloku** [comment]
Then that's not an ideal solution and documentation for not optimal solutions/edge cases do not make sense as those misguide users. 

I.e. There is no reason to use the approach documented for `Primary-Remote on different networks` when hosts have direct access. And if you are able to achieve that by manually updating the Service from LB to NodePort that's a good solution. (afaik this can be defined in the IstioOperator)

**Comment by J4sonZ** [comment]
> Then that's not an ideal solution and documentation for not optimal solutions/edge cases do not make sense as those misguide users.
> 
> I.e. There is no reason to use the approach documented for `Primary-Remote on different networks` when hosts have direct access. And if you are able to achieve that by manually updating the Service from LB to NodePort that's a good solution. (afaik this can be defined in the IstioOperator)

@rinormaloku it's not easy to use nodeport to realize mulicluster, I haven't even seen a person implementing multiple clusters through nodeport. Is there any good solution now?
