### ISSUE TITLE
Create e2e for Task "Enabling Ingress Traffic" - Secure Ingress

### ISSUE THREAD

**Issue by sebastienvas** [istio/istio#292]

**Comment by sakshigoel12** [comment]
For secure ingress
It is covered in poilet , need to add something in istio/istio

**Comment by myidpt** [comment]
@ldemailly Hi Laurent, do we already have e2e test for ingress without security?

**Comment by ldemailly** [comment]
all the e2e tests minimally exercise the ingress in http mode yes but not cert part

**Comment by ayj** [comment]
Is this addressed by https://istio.io/docs/tasks/traffic-management-v1alpha3/ingress.html#configuring-secure-ingress-https?

**Comment by ldemailly** [comment]
Those issues aren't about documenting but about having e2e tests ?
