### ISSUE TITLE
istio installation - istio-egressgateway connection readiness probe-status code 503

### ISSUE THREAD

**Issue by rajibhossen** [istio/istio#29207]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**
Getting connection refused (503) 
<img width="2334" alt="Screen Shot 2020-11-26 at 12 25 59 AM" src="https://user-images.githubusercontent.com/7677962/100315978-3adf5900-2f7f-11eb-8ef9-b4ec4f5e599b.png">
<img width="1308" alt="Screen Shot 2020-11-26 at 12 24 18 AM" src="https://user-images.githubusercontent.com/7677962/100315996-4599ee00-2f7f-11eb-9e9e-427a10d220d2.png">

error while installing istio. istiod installed perfectly, however, istio-ingressgateway, and istio-egressgateway are getting errors.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
ingress and egress should install properly.

**Steps to reproduce the bug**
kubernetes 2 node cluster, each server 128gb memory, 16 core
kubernetes pod network - flannel (10.244.0.0/16)

istioctl install --set profile=demo -y

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
istio - 1.8.0
kubectl (client,server) - v1.19.4
**How was Istio installed?**
Downloaded from the official repository, provided bin in path, and installed by istioctl install command.
**Environment where bug was observed (cloud vendor, OS, etc)**
private server, ubuntu 20
Additionally, please consider running `istioctl bug-report` and attach the generated
cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
for more details.

**Comment by howardjohn** [comment]
Can you call `curl <istiod-pod-ip>:8080` from the gateway pod? this looks like you may have some connectivity issue blocking communication

**Comment by rajibhossen** [comment]
<img width="975" alt="Screen Shot 2020-11-26 at 7 52 28 PM" src="https://user-images.githubusercontent.com/7677962/100402069-f906ef00-3020-11eb-8ce9-5c067387409a.png">
These are the pods and their network. all of the pods are in Node 2. 
from Node 1(master), when I call `curl 10.244.1.110:8080`, it doesn't return anything, maybe fall in an indefinite loop. when I do the same curl from Node 2, it returns `404 page not found` immediately.

**Comment by howardjohn** [comment]
You need connectivity between your pods. This sounds like you have your cluster set up improperly rather than an Istio issue.

**Comment by rajibhossen** [comment]
Thanks. I just installed Kubernetes by following some online tutorials. I don't get much about the pods network. It would be great for me if anyone can provide me any resources for setting up a Kubernetes cluster perfectly.

**Comment by howardjohn** [comment]
I recommend following https://kubernetes.io/. Thanks!
