### ISSUE TITLE
Nondeterministic behaviour of istio-ingressgateway with mTLS

### ISSUE THREAD

**Issue by Demonsthere** [istio/istio#29214]
**Bug description**
In our system we are using istio-ingressgateway to expose a certain amount of services using a simple TLS gateway (`tls-gateway`) and a single mTLS service using a dedicated mTLS gateway (`mtls-gateway`). 
**Both gateways use the same TLS certificate** having the same `credentialName: tls-gateway-certs` field in the configuration. The secret is managed by cert-manager, so it created with ca.crt, tls.crt, tls.key fields. 
Additionally, we have a custom secret `tls-gateway-certs-cacert`, which holds a custom cacert, which we want to use for our mtls-gateway. 

After upgrading istio to 1.7.4 we noticed a nondeterministic behavior related to scaling the istio-ingressgateway. Calling our mtls application would sometimes fail with an `error:1401E418:SSL routines:CONNECT_CR_FINISHED:tlsv1 alert unknown ca` error. 

After some debugging we found out that some pods/instances of istio-ingressgateway were serving the CA from `tls-gateway-certs` secret (which was wrong) and some from `tls-gateway-certs-cacert` (which was correct)

This behavior was not present in previous versions of Istio (1.5 and previous)

[ ] Docs
[ ] Installation
[ ] Networking
[ X ] Performance and Scalability
[ ] Extensions and Telemetry
[ X ] Security
[ ] Test and Release
[ X ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Istio-ingressgateway uses a single secret in a deterministic manner or uses the dedicated secret with higher priority than the combined one.

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
1.7.4

**How was Istio installed?**
istioctl install with custom profile

**Environment where bug was observed (cloud vendor, OS, etc)**
Cluster created with Gardener on GCE

Additionally, please consider running `istioctl bug-report` and attach the generated
cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
for more details.

- [tls-gateway](https://github.com/kyma-project/kyma/blob/e68680dd4cec244d8bd903c3b3c6ccea52f58661/resources/core/charts/gateway/templates/gateway.yaml)
- [mtls-gateway](https://github.com/kyma-project/kyma/blob/e68680dd4cec244d8bd903c3b3c6ccea52f58661/resources/application-connector/templates/application-connector-gateway.yaml)

**Comment by howardjohn** [comment]
Can you post the Gateway configs?

**Comment by Demonsthere** [comment]
@howardjohn Of course, adding them to the first post

**Comment by howardjohn** [comment]
I think this is the same as https://github.com/istio/istio/issues/13589, can you check if that is consistent with this issue? Does it work with `curl` and fail only with browsers?

**Comment by howardjohn** [comment]
> I suspect it is related to changes/moving the SDS from ingress-gateway to istiod

This happened in 1.8, you are seeing this after upgrading from 1.6 to 1.7 right?

**Comment by Demonsthere** [comment]
@howardjohn I will check https://github.com/istio/istio/issues/13589, thanks for the tip.
No, we observed the same behavior with both `curl` and browser tests. 
We had to upgrade from 1.5 to 1.7, and observed this after running 1.7.4
