### ISSUE TITLE
about istio-ingress-gateway performance 

### ISSUE THREAD

**Issue by BoxuanChen** [istio/istio#29210]
**Bug description**
istio-ingress-gateway performance is too slow

[ ] Docs
[ ] Installation
[ ] Networking
[X] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
performance improvement 
**Steps to reproduce the bug**
i'm using nginx default index.html to test performance of nginx-ingress and istio-ingress-gateway with wrk tools( https://github.com/wg/wrk.git)

**environment**
>nginx-ingress and istio-gateway-ingress both running as hostNetwork mode and the backend service is 100 nginx pod with default nginx index.html

testing performance by wrk tools and the nginx-ingress qps avg is 47000+, istio-gateway qps avg is 7800+

Why is there such a big difference in qps values? Can someone help me answer it?

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
`1.8.0`
**How was Istio installed?**
by isitioctl (default profile)
**Environment where bug was observed (cloud vendor, OS, etc)**
`k8s 1.18.9`
`ubuntu 18.04`
Additionally, please consider running `istioctl bug-report` and attach the generated
cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
for more details.

**Comment by carolynhu** [comment]
could you measure your system's maximum supported qps? since if exceed that number, your measurement is meaningless, and I wonder how did you get the avg qps for each

**Comment by BoxuanChen** [comment]
for avg qps i'm using wrk command with `wrk -c 500 -t 200 http://$NGINX-INGRESS-HOST:$PORT` also wrk -c 500 -t 200 http://$ISTIO-GATEWAY:$PORT``  

example:
```
# this is for istio-gateway
[root@sb-66107 wrk]# ./wrk -c 500 -t 200 http://172.24.30.110:8080/test-b
Running 10s test @ http://172.24.30.110:8080/test-b
  200 threads and 500 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    68.59ms   39.80ms 300.76ms   65.32%
    Req/Sec    29.30     11.24   131.00     89.78%
  58676 requests in 10.10s, 14.15MB read
Requests/sec:   5809.62
Transfer/sec:      1.40MB


# this is for nginx-ingress
[root@sb-66107 wrk]# ./wrk -c 500 -t 200 http://172.24.30.109:80
Running 10s test @ http://172.24.30.109:80
  200 threads and 500 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     9.28ms   12.62ms 129.49ms   86.62%
    Req/Sec   340.59    240.82     1.99k    61.41%
  684446 requests in 10.10s, 182.08MB read
  Non-2xx or 3xx responses: 684446
Requests/sec:  67768.46
Transfer/sec:     18.03MB
```

in the other hand how can i know my system's maximum supported qps?

**Comment by carolynhu** [comment]
- From your command, i just want to make sure your comparison is based on the same -c and -t combination. good, you did. 
- I do not know if wrk support it or not. Currently, in Istio, we are supporting fortio and nighthawk as the load gen. 
And in fortio https://github.com/fortio/fortio, you can pass `-qps 0` to get your system's max qps number.

**Comment by BoxuanChen** [comment]
@carolynhu

thanks, i'll try with fortio to run another testing. 
In fact, what I want to confirm is how the performance of istio-gateway can be used in a production environment?
Or is the performance of istio-gateway better than nginx-ingress? (because we using nginx-ingress for now)

**Comment by carolynhu** [comment]
> @carolynhu
> 
> thanks, i'll try with fortio to run another testing.
> In fact, what I want to confirm is how the performance of istio-gateway can be used in a production environment?
> Or is the performance of istio-gateway better than nginx-ingress? (because we using nginx-ingress for now)

yes, i know, I recall there are users says their nginx-ingress has better performance than istio-ingressgateway. since on istio side we did not do that comparison, i'm fully certain about that

**Comment by BoxuanChen** [comment]
Many thanks.

**Comment by carolynhu** [comment]
btw, you could reference here: https://perf.dashboard.istio.io to get the daily istio performance data update, and I will add istio-ingressgateway perf number maybe for 1.9.

**Comment by carolynhu** [comment]
> Many thanks.

No problem! btw, you could reference here: https://perf.dashboard.istio.io to get the daily istio performance data update, and I will add istio-ingressgateway perf number maybe for 1.9.

**Comment by BoxuanChen** [comment]
> > Many thanks.
> 
> No problem! btw, you could reference here: https://perf.dashboard.istio.io to get the daily istio performance data update, and I will add istio-ingressgateway perf number maybe for 1.9.

sorry. there is one more question.. can i using nginx-ingress with istio? 
i mean using nginx-ingress as my k8s cluster INGRESS-ENDPOINTS and using istio for traffic management(with out istio-ingress-gateway). how can i do that? i try it before but this's didn't work.

**Comment by carolynhu** [comment]
you should be able to, when you config Gateway resource, could you point it to your nginx-ingressgateway?

**Comment by BoxuanChen** [comment]
there is any example for me ?

**Comment by carolynhu** [comment]
hmm... i never configured it before, but maybe this will be helpful https://www.tetrate.io/blog/using-istio-with-other-ingress-proxies/

**Comment by Kiddinglife** [comment]
Any updates? I am wondering how good or bad the istio-gateway can perform compared with nginx-ingress?
