### ISSUE TITLE
Istio is not working with Azure Front Door

### ISSUE THREAD

**Issue by rnkhouse** [istio/istio#29232]
**Bug description**
I installed istio in AKS with Azure Front Door (AFD). All my services are running with valid and production SSL. I am using letsencrypt and cert-manager. **Without AFD, I am able to access the service without any issues.** With AFD, I am getting below error:

    Our services aren't available right now
    We're working to restore all services as soon as possible. Please check back soon.

This error is coming from Azure. I opened the support ticket to Azure and after their investigation, they told me that the SSL handshake is not properly being done from the server-side and `istio` support is not in their scope.

After that, I tried with `ingress-nginx` controller (https://github.com/kubernetes/ingress-nginx/tree/master/charts/ingress-nginx) instead of `istio` and configure ingress controller this argument (**_controller.extraArgs.default-ssl-certificate="default/cert"_**)
https://kubernetes.github.io/ingress-nginx/user-guide/tls/#default-ssl-certificate
And it worked.

I am wondering how can I configure istio with a similar way as `ingress-nginx` controller?

Current gateway yaml:

    ---
    apiVersion: networking.istio.io/v1alpha3
    kind: Gateway
    metadata:
    name: SERVICE_GATEWAY
    spec:
      selector:
        istio: ingressgateway # Use Istio default gateway implementation
      servers:
      - port:
          name: SERVICE_NAME-http-80
          number: 80
          protocol: HTTP
        hosts:
        - "SERVICE_DNS"
      - port:
          name: SERVICE_NAME-https-443
          number: 443
          protocol: HTTPS
        tls:
          credentialName: SERVICE_CRT
          mode: SIMPLE
          minProtocolVersion: TLSV1_2
        hosts:
        - "SERVICE_DNS"

I am confirming that secret and certificate are in `istio-system` namespace and `gateway` is in the default namespace.
I also tried with `privateKey: sds` and `serverCertificate: sds`. Also, tried by setting `tls` mode SIMPLE and PASSTHROUGH.

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

It should work with Azure Front Door.

**Steps to reproduce the bug**

1. Create AKS cluster.
2. Install istio and host any service.
3. Expose it to public DNS.
4. Provide Azure Front Door in Azure DNS configs.
4. Configure and route traffic from Azure Front Door by providing public IP of `istio-ingress gateway` to Azure Front Door backend.

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

istio version: 1.7.4

kubectl version:
Client Version: v1.19.2
Server Version: v1.18.8

Helm version:
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}

**How was Istio installed?**
By generating manifest and `istioctl` command.

**Environment where bug was observed (cloud vendor, OS, etc)**
AKS

**Additional links I followed:**
https://ssbkang.com/2020/08/17/end-to-end-tls-for-azure-front-door-and-azure-kubernetes-service/

**Comment by rinormaloku** [comment]
Hi @rnkhouse 

This is a good question to be posted in StackOverflow as it would help the wider community facing the same issue.

**Comment by rnkhouse** [comment]
@rinormaloku I already posted on stackoverflow: https://stackoverflow.com/questions/65030360/istio-default-ssl-certificate

**Comment by howardjohn** [comment]
> they told me that the SSL handshake is not properly being done from the server-side and istio support is not in their scope.

Do they have any more details on what is "improper"? Istio is doing very standard SSL afaik - it should be the same as all other Envoy based LBs as well which are extremely common in K8s

**Comment by howardjohn** [comment]
Are you sure that your cert is signed for the hostname provided? And that AFD is passing this same hostname in the SNI header?

**Comment by rnkhouse** [comment]
@howardjohn I am using the valid and production certificate. Also, using the same hostname in AFD. If my setup is not right then it shouldn't work with `ingres-nginx` and AFD.
Also, I am able to access the service if I do not use AFD at all.

**Comment by howardjohn** [comment]
The difference between nginx and istio is nginx is configured (by you, from the issue description) to return the certificate for all requests. Istio will only do it if the SNI header mafches the Gateway hosts config you have configured

I don't think any Istio maintainers have access to Azure, sorry.

**Comment by martin2176** [comment]
One thing you can try on AFD is to set the custom host header when you define the backend pool in AFD.
in your istio gateway configuration, use a real hostname for "SERVICE_DNS".
then use this same hostname as custom host header when you define backend pool in AFD.
To troubleshoot the issue further, instead of using a host name specific TLS cert on Istio gateway use a wildcard cert such as *.blah.com.
I am also assuming you have configured the AFD correctly and completed the custom domain configuration. From the error description "our services are not available right now", from what I have seen is usually an issue with the frontend configuration of AFD and not really the backend.

**Comment by GlenColby** [comment]
Has anyone figured anything out on this?  We are having the exact same issue and none of the proposed configurations from above have made a difference.

**Comment by howardjohn** [comment]
Try `hosts: *` in the Gateway. If its not forwarding the SNI then you cannot use SNI matching

**Comment by GlenColby** [comment]
That doesn't work either.

**Comment by LukeRH** [comment]
I am also seeing this issue, did anyone ever find a solution?
