### ISSUE TITLE
Overlay mechanism does not apply change to all matching elements in list

### ISSUE THREAD

**Issue by rtmie** [istio/istio#29230]
**Bug description**
IIUC from comment in source code of [patch operation](https://github.com/istio/istio/blob/d96e772724184069fd40c41be32c313b4040c386/operator/pkg/patch/patch.go#L17)
```
Paths are specified in the form a.b.c.[key:value].d.[list_entry_value], where:
 -  [key:value] selects a list entry in list c which contains an entry with key:value
 -  [list_entry_value] selects a list entry in list d which is a regex match of list_entry_value.
```

I would expect the patch operation to apply in all matches of `c.[key: value`] however it appears that the overlay patch applies only to the first matching element.

[ ] Docs
[ X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Overlay patch operation should apply to all matches in the path pattern

**Steps to reproduce the bug**
Add an overlay for an element which has multiple match criteria for a list set e.g.

```
        overlays:
        - kind: EnvoyFilter
          name: tcp-stats-filter-1.7
          patches:
          - path: spec.configPatches.[applyTo:NETWORK_FILTER].match.proxy.proxyVersion
            value: ^9\.9.*
```

check the outcome once the operator has applied the resource:

```
 kubectl -n istio-system get envoyfilter tcp-stats-filter-1.7 -o yaml|yq r - spec.configPatches[*].match.proxy.proxyVersion
- ^9\.9.*
- ^1\.7.*
- ^1\.7.*
```

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
``` istioctl version --remote
client version: 1.7.2
control plane version: 1.7.3-9686754643d0939c1f4dd0ee20443c51183f3589
data plane version: 1.7.3 (379 proxies)
```

```
kubectl version --short
Client Version: v1.19.1
Server Version: v1.19.2
```
**How was Istio installed?**
Operator profile

**Environment where bug was observed (cloud vendor, OS, etc)**
AWS, centos

Additionally, please consider running `istioctl bug-report` and attach the generated
cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
for more details.

**Comment by howardjohn** [comment]
cc @ostromart

**Comment by rtmie** [comment]
I did not see any changes to overlay mechanism in 1.8 release. Is this being addressed?
