### ISSUE TITLE
Could not find Policy authentication.istio.io/v1alpha1

### ISSUE THREAD

**Issue by barryzhounb** [istio/istio#29233]
When I deploy Istio Policy, I get
error: unable to recognize "STDIN": no matches for kind "Policy" in version "authentication.istio.io/v1alpha1"

I double check CustomDefinition, I didn't find Policy, I am wondering if "Policy" was removed from Istio version 1.8? Because I have use "Policy" in Istio v.1.4

This is my yaml file
```
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "default"
  namespace: "mynamespace"
spec:
  peers:
  - mtls: {}
```

**Bug description**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**
istioctl version --remote
```
client version: 1.8.0
control plane version: OSSM_2.0.0
data plane version: 1.6.5 (3 proxies)
```

kubectl version --short
```
Client Version: v1.14.0
Server Version: v1.17.1+45f8ddb
```

**How was Istio installed?**

**Environment where bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated
cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
for more details.

**Comment by rinormaloku** [comment]
Yes it's removed: https://github.com/istio/istio/issues/22602

**Comment by barryzhounb** [comment]
Hi @rinormaloku  Is there equivalent CustomDefinition for "Policy" in Version 1.8? For us, I need to use it to enable mTLS for namespace.

**Comment by rinormaloku** [comment]
yes: https://istio.io/latest/docs/tasks/security/authentication/authn-policy/

It's the PeerAuthentication resource.

**Comment by barryzhounb** [comment]
@rinormaloku Since which version, was Policy replaced by PeerAuthentication?

**Comment by rinormaloku** [comment]
afaik it was added to deprecation from Istio 1.5, could be wrong.

**Comment by howardjohn** [comment]
Yes this is working as expected and documented in upgrade notes
