### ISSUE TITLE
In dedup.go, could clear a map by make a new space or not?

### ISSUE THREAD

**Issue by koko990** [istio/istio#2924]
in mixer/adapter/memquota/dedup.go , Could clear a map  by make a new space:
Like the code line 112
```
for k := range t {
              delete(t, k)
      }
```
to
```
t = make(map[string]dedupState)
```

**Comment by geeknoid** [comment]
The point here is to clear the map without allocating memory.

Growing collections like maps lead to repeated allocations over time. So reallocating a map may actually mean several allocations are performed, and data is copied around when the collection storage needs to grow. 

The ideal solution would be to simply clear the map's state to 0 and use it. In lieu of that, it's generally more efficient to explicitly drain a map than it is to allocate a fresh one.
