### ISSUE TITLE
Any way to add uri dimension to envoy_cluster_upstream_rq_time metric?

### ISSUE THREAD

**Issue by qianweichun** [istio/istio#29256]
**Describe the feature request**
envoy_cluster_upstream_rq_time is useful to find out slow services. it would be more useful to add uri property.

**Describe alternatives you've considered**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by bianpengyuan** [comment]
I don't think that is possible, as uri can be unbounded and cannot be used as metric label directly. Envoy itself does not support sophisticated stats classification or customization either. You will have to use other mechanism such as trace to identity slow request path. Please reopen if you have more question. Thanks!
