### ISSUE TITLE
no healthy upstream being returned when service is available

### ISSUE THREAD

**Issue by abbas-hue** [istio/istio#29254]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

1.  Installed istio 1.6.8 with following options:
```
istioctl install --set profile=default --set meshConfig.accessLogFile=/dev/stdout --set values.global.proxy.logLevel=debug
```

2.  Deployed sample book info and gateway and ensured /productpage URI is available:
```
http://129.159.72.202/productpage
```

3.  Configured our own virtual service and gateway as follows:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: foo
  namespace: basic-domain-namespace
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bar
  namespace: basic-domain-namespace
spec:
  hosts:
  - "*"
  gateways:
  - foo
  http:
  - match:
    - uri:
        exact: /console
    route:
    - destination:
        host: basic-domain-admin-server.basic-domain-namespace.svc.cluster.local
        port:
          number: 7001
```

4.  Ran `istioctl analyze -n basic-domain-namespace` to verify there are no errors.

5.  Verify we can curl the service url from the istio ingress gateway pod:
```
root@istio-ingressgateway-845c5c565b-fmttj:/# curl -Lv http://basic-domain-admin-server.basic-domain-namespace.svc.cluster.local:7001/console

. . .

< HTTP/1.1 200 OK
< Cache-Control: no-cache
< Date: Sun, 29 Nov 2020 22:03:08 GMT
< Pragma: no-cache
< Content-Length: 3133
< Content-Type: text/html; charset=UTF-8
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< X-Content-Type-Options: nosniff
< Set-Cookie: ADMINCONSOLESESSION=_moWB_GrI6w_Vl7p
```

5.  When trying to access /console, via external URL, "no healthy upstream" message is returned.  Envoy debug logs show:

```
2020-11-29T22:00:10.245052Z     debug   envoy http      [external/envoy/source/common/http/conn_manager_impl.cc:782] [C291][S10850330541361602569] request headers complete (end_stream=true):
':authority', '129.159.72.202'
':path', '/console'
':method', 'GET'
'upgrade-insecure-requests', '1'
'user-agent', 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36'
'accept', 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9'
'accept-encoding', 'gzip, deflate'
'accept-language', 'en-US,en;q=0.9'
'cache-control', 'max-stale=0'
'connection', 'Keep-Alive'
'x-bluecoat-via', '20bd90a60eb4daf3'

2020-11-29T22:00:10.245065Z     debug   envoy http      [external/envoy/source/common/http/conn_manager_impl.cc:1337] [C291][S10850330541361602569] request end stream
2020-11-29T22:00:10.245239Z     debug   envoy router    [external/envoy/source/common/router/router.cc:477] [C291][S10850330541361602569] cluster 'outbound|7001||basic-domain-admin-server.basic-domain-namespace.svc.cluster.local' match for URL '/console'
2020-11-29T22:00:10.245274Z     debug   envoy upstream  [external/envoy/source/common/upstream/cluster_manager_impl.cc:1235] no healthy host for HTTP connection pool
2020-11-29T22:00:10.245333Z     debug   envoy http      [external/envoy/source/common/http/conn_manager_impl.cc:1479] [C291][S10850330541361602569] Sending local reply with details no_healthy_upstream
2020-11-29T22:00:10.245369Z     debug   envoy http      [external/envoy/source/common/http/conn_manager_impl.cc:1710] [C291][S10850330541361602569] encoding headers via codec (end_stream=false):
':status', '503'
```
We really not clear on why this is happening

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

http://129.159.72.202/console should work according to our gateway/vs config

**Steps to reproduce the bug**

1.  Install Istio 1.6.8 (also fails with 1.7.4)
2.  Deploy sample bookinfo app and gateway and ensure it is available.
3.  Deploy console app in k8s.
4.  Configure gw/vs for console as follows:

kubectl apply -f <file> with the following contents:
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: foo
  namespace: basic-domain-namespace
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bar
  namespace: basic-domain-namespace
spec:
  hosts:
  - "*"
  gateways:
  - foo
  http:
  - match:
    - uri:
        exact: /console
    route:
    - destination:
        host: basic-domain-admin-server.basic-domain-namespace.svc.cluster.local
        port:
          number: 7001
```

5.  Hit http://129.159.72.202/console - "no healthy upstream" message returned.

**Version (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version` if you used Helm)**

# istioctl version --remote
client version: 1.6.8
control plane version: 1.6.8
data plane version: 1.6.8 (8 proxies

# kubectl version --short
Client Version: v1.18.5
Server Version: v1.16.8

**How was Istio installed?**

Manually, using the following command:

istioctl install --set profile=default --set meshConfig.accessLogFile=/dev/stdout --set values.global.proxy.logLevel=debug
kubectl label namespace default istio-injection=enabled --overwrite=true
kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml
kubectl apply -f samples/bookinfo/networking/bookinfo-gateway.yaml

**Environment where bug was observed (cloud vendor, OS, etc)**

Observed in both Oracle Cloud Infrastructure (OCI) on RHEL 7 and Amazon EKS on RHEL 8.

Additionally, please consider running `istioctl bug-report` and attach the generated
cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive)
for more details.

[info.tar.gz](https://github.com/istio/istio/files/5612942/info.tar.gz)

**Comment by howardjohn** [comment]
Can you post config dump and clusters output from https://github.com/istio/istio/wiki/Troubleshooting-Istio?

**Comment by abbas-hue** [comment]
Please see attached

[clusters.json.txt](https://github.com/istio/istio/files/5617526/clusters.json.txt)
[config_dump.json.txt](https://github.com/istio/istio/files/5617527/config_dump.json.txt)

**Comment by howardjohn** [comment]
The list of endpoints is empty. Can you check `kubectl get endpoints -n basic-domain-namespace` shows endpoints for port 7001?

Also can you try restarting Istiod and see if it makes a difference

**Comment by abbas-hue** [comment]
$ kubectl get endpoints -n basic-domain-namespace
NAME                             ENDPOINTS           AGE
basic-domain-admin-server        10.244.0.194:7001   35h
basic-domain-cluster-cluster-1   <none>              36h

killing the istiod pod didn't make a difference

**Comment by howardjohn** [comment]
Oh its a headless service... I think this was fixed on newer versions. You are on an unsupported version https://istio.io/latest/news/support/announcing-1.6-eol/

**Comment by abbas-hue** [comment]
How do we know it is headless?  We tried on 1.7.4 as well and it still didn't work.

**Comment by howardjohn** [comment]
Can you get the same clusters and configdump from the ingress on 1.7.4 then?
 can tell from ` clusterIP: None`

**Comment by abbas-hue** [comment]
the clusters and config dump that i sent from 1.6.8 were from the sidecar proxy - you want it from the ingress gateway?

**Comment by abbas-hue** [comment]
Here are the dumps from the ingress gateway pod in 1.6.8.  If this is not enough, let me know and I will repeat for 1.7.4.

[clusters.json.2.txt](https://github.com/istio/istio/files/5618525/clusters.json.2.txt)
[config_dump.json.2.txt](https://github.com/istio/istio/files/5618526/config_dump.json.2.txt)

**Comment by abbas-hue** [comment]
Istio 1.7.4 gives the following when trying to hit our virtual service:

upstream connect error or disconnect/reset before headers. reset reason: connection failure

Attached are config and cluster dumps for both the sidecar proxy and ingress gateway

[ingressgateway_clusters_dump.json.txt](https://github.com/istio/istio/files/5620317/ingressgateway_clusters_dump.json.txt)
[ingressgateway_config_dump.json.txt](https://github.com/istio/istio/files/5620318/ingressgateway_config_dump.json.txt)
[sidecar_clusters_dump.json.txt](https://github.com/istio/istio/files/5620319/sidecar_clusters_dump.json.txt)
[sidecar_config_dump.json.txt](https://github.com/istio/istio/files/5620320/sidecar_config_dump.json.txt)

**Comment by abbas-hue** [comment]
Hello - any updates on this please?

**Comment by abbas-hue** [comment]
So what should our next step be?

**Comment by abbas-hue** [comment]
Hello - would appreciate some guidance on this.

**Comment by howardjohn** [comment]
Are you sure with the most recent configuration you are getting "no healthy upstream"? that doesn't seem consistent with the most recent configuration

**Comment by howardjohn** [comment]
Any more info?

**Comment by yalctay93** [comment]
I am seeing the exact same issue as abbas-hue - did anyone find a solution for this yet?

**Comment by axa605** [comment]
i'm facing similar issue

**Comment by axa605** [comment]
did anyone fixed no healthy upstream?

**Comment by patrickleet** [comment]
restarting the istio-ingressgateway got things working again for me

**Comment by the60ftatomicman** [comment]
Let's keep this alive. im having the same issue!

**Comment by zirain** [comment]
not stale

**Comment by howardjohn** [comment]
Please reopen a new issue if you are facing similar issues. "Me too" on 2 year old issues isn't particularly helpful as they are unlikely related despite similar error messages.

If you see this _on recent versions_ please open an issue with the info requested above (config dump + clusters dump + `kubectl get endpoints`).

Thanks

**Comment by sinbad-io** [comment]
Facing the exact same issue...
