### ISSUE TITLE
Cannot run stackdriver integration tests off GCP

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#29268]
We deploy ingress, which crashloops with `2020-11-30T16:51:23.611339Z     error   Failed to generate bootstrap config: unable to process Stackdriver tracer: Get "http://169.254.169.254/computeMetadata/v1/project/project-id": dial tcp 169.254.169.254:80: i/o timeout`

I am a bit suspicious the test is not working properly off GCP either - how does it start using the fake SD if its extracting metadata info at startup of ingress, before fake SD is deployed?

**Comment by howardjohn** [comment]
Ah probably the test never checks ingress so it doesn't really matter?

**Comment by howardjohn** [comment]
The sidecars crash with the same

**Comment by douglas-reid** [comment]
I've run it locally with the fake metadata server in the setup, iirc. Has something changed?

**Comment by howardjohn** [comment]
@douglas-reid I think maybe the envoy SD filter gets passed the fake SD url, but I am seeing the agent golang code calling `169.254.169.254` which seems like its not pointing to the fake

**Comment by douglas-reid** [comment]
Maybe I'm thinking of the Stackdriver VM tests only (which I know use a fake GCE Metadata Server).

**Comment by douglas-reid** [comment]
@howardjohn ok. i looked into this a bit more. the stackdriver tracing configuration does not use the platform metadata stuff to detect `onGCE()`, and assumes GCP configuration. This seems like a real issue. We shouldn't require `onGCE() == true` to configuration SD tracing.

/cc: @bianpengyuan

**Comment by douglas-reid** [comment]
Lines that need to be adapted to use the platform environment struct: https://github.com/istio/istio/blob/master/pkg/bootstrap/config.go#L310-L312

We should also enable configuration of project ID for off-GCP use.

**Comment by douglas-reid** [comment]
@howardjohn do you have an easy repro for the issue? can you try running with the provisional changes in https://github.com/istio/istio/pull/29882 ?

**Comment by jacob-delgado** [comment]
cc @douglas-reid I'll try this against our private fork that runs on AWS
