### ISSUE TITLE
missing usage docs for istioctl gen-deploy

### ISSUE THREAD

**Issue by janwillies** [istio/istio#2927]
I want to setup a non-invasive istio deployment on an existing cluster, and then enable it for two services to start evaluating istio.

According to `istioctl gen-deploy` I should be able to execute this:
```
~/istio-0.5.0-pre20180126-01-09-40/bin$ ./istioctl gen-deploy --features routing policy --helm-chart-dir ../install/kubernetes/helm/
global:
  namespace: istio-system
  sidecar-injector:
    enabled: false
  proxy:
    hub: gcr.io/istio-testing
    tag: 0.4.0
    debug: false
  pilot:
    enabled: true
    hub: gcr.io/istio-testing
    tag: 0.4.0
  security:
    enabled: false
    hub: gcr.io/istio-testing
    tag: 0.4.0
  mixer:
    enabled: false
    hub: gcr.io/istio-testing
    tag: 0.4.0
  ingress:
    use_nodeport: false
    nodeport_port: 0
  hyperkube_hub: quay.io/coreos/hyperkube
  hyperkube_tag: 0.4.0
```
The generated yaml looks like a helm `values.yaml`. Am I supposed to use install istio with `helm -f values.yaml` afterwards?

**Comment by janwillies** [comment]
the `hyperkube_tag` should probably point to something more recent

**Comment by sdake** [comment]
@janwillies the gen-deploy operation doesn't work correctly at this point in time from what I can tell.  Current master helm charts do work on kubernetes 1.7 and 1.8.  1.9 is untested.  Master helm charts are undergoing some refactoring and cleanup.  There is some basic documentation (unmerged) which needs refinement.  Check out PR:
https://github.com/istio/istio.github.io/pull/875

Also examine https://github.com/istio/istio/blob/master/install/kubernetes/helm/README.md.  The idea is to merge the contents of README.md into the PR.

**Comment by ayj** [comment]
@costin @sdake, whats the current status of `istio gen-deploy`?
