### ISSUE TITLE
Dashboards with multicluster support

### ISSUE THREAD

**Issue by nmittler** [istio/istio#29279]
Our current dashboards are only for single cluster. We should extend them to also support multicluster.

There is no design, currently, so part of this effort will be to propose a new design that supports multiple clusters.

[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by carolynhu** [comment]
cc @douglas-reid @mandarjog

**Comment by nmittler** [comment]
not stale
