### ISSUE TITLE
Running docker pull quay.io/kiali/kiali:v1.15 is not downloading the image

### ISSUE THREAD

**Issue by cmudduluru** [istio/istio#29271]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
I installed istio in  my docker-desktop but the kiali pod is stuck in ContainerCreating Status. Pod descriptions shows that the pod is stuck with pulling the image.

Events:
Events:
  Type     Reason       Age                  From                     Message
  ----     ------       ----                 ----                     -------
  Normal   Scheduled    27m                  default-scheduler        Successfully assigned istio-system/kiali-7ff568c949-pz7r7 to docker-desktop
  Warning  FailedMount  27m                  kubelet, docker-desktop  MountVolume.SetUp failed for volume "kiali-configuration" : couldn't propagate object cache: timed out waiting for the condition
  Warning  FailedMount  27m                  kubelet, docker-desktop  MountVolume.SetUp failed for volume "kiali-cert" : couldn't propagate object cache: timed out waiting for the condition
  Warning  FailedMount  27m                  kubelet, docker-desktop  MountVolume.SetUp failed for volume "kiali-service-account-token-ltsnz" : couldn't propagate object cache: timed out waiting for the condition
  Warning  FailedMount  27m                  kubelet, docker-desktop  MountVolume.SetUp failed for volume "kiali-secret" : couldn't propagate object cache: timed out waiting for the condition
  Warning  Failed       2m51s                kubelet, docker-desktop  Failed to pull image "quay.io/kiali/kiali:v1.15": rpc error: code = Unknown desc = context canceled
  Warning  Failed       2m51s                kubelet, docker-desktop  Error: ErrImagePull
  Normal   BackOff      2m50s                kubelet, docker-desktop  Back-off pulling image "quay.io/kiali/kiali:v1.15"
  Warning  Failed       2m50s                kubelet, docker-desktop  Error: ImagePullBackOff
  Normal   Pulling      2m37s (x2 over 27m)  kubelet, docker-desktop  Pulling image "quay.io/kiali/kiali:v1.15"

Then I tried to only pull the kiali image and it shows it is stuck and not completing the download. 
C:\Users\USENAME>docker pull quay.io/kiali/kiali:v1.15
v1.15: Pulling from kiali/kiali
f4816e38b7e0: Already exists                                                                                                                                                                                             7c949fdfdbff: Already exists                                                                                                                                                                                             e758978c1aaf: Already exists                                                                                                                                                                                             f6d5fc15c035: Downloading [=================>                                 ]  5.946MB/16.56MB                                                                                                                         9f50c3d54f3e: Download complete                                                                                                                                                                                          873e1ac3f143: Download complete                                                                                                                                                                                          

[X ] Docs
[ ] Installation
[X ] Networking
[ X] Performance and Scalability
[ X] Extensions and Telemetry
[X ] Security
[X ] Test and Release
[ ] User Experience
[X ] Developer Infrastructure
[X ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**
docker pull quay.io/kiali/kiali:v1.15

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
Client Version: v1.15.5
Server Version: v1.15.5

**How was Istio installed?**
Using helm chart

**Environment where the bug was observed (cloud vendor, OS, etc)**
docker-desktop. The same environment worked fine last week. 

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
This works on my machine. 

This is not an Istio bug though, and is either an issue with https://github.com/kiali/kiali or your kubernetes cluster.
