### ISSUE TITLE
Set outboundTrafficPolicy = REGISTRY_ONLY blocks traffic to headless service

### ISSUE THREAD

**Issue by c0ffeec0der** [istio/istio#29294]
**Bug description**
Set outboundTrafficPolicy = true blocks traffic to headless service

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Set outboundTrafficPolicy = REGISTRY_ONLY allow traffic to headless service

**Steps to reproduce the bug**
1. Install any headless service and create dummy traffic
2. Set outboundTrafficPolicy = false, traffic is received on the other end
3. Set outboundTrafficPolicy = true, traffic is blocked but logs shows HTTP 200

**Version**
1.8.0

**How was Istio installed?**
Istio operator

**Environment where the bug was observed (cloud vendor, OS, etc)**
Docker desktop

**Comment by howardjohn** [comment]
Can you give more details about what exactly you did? `outboundTrafficPolicy=true` is not a valid option, so I am a bit confused. if you can include the Istio operator config as well as Service and the traffic you sent it would be helpful. Thanks.

**Comment by howardjohn** [comment]
Access logs and config dump (https://github.com/istio/istio/wiki/Troubleshooting-Istio) could help as well

**Comment by c0ffeec0der** [comment]
Hello,

sorry, i mean outboundTrafficPolicy = REGISTRY_ONLY (caps due to value)

IstioOperator config
----------------------
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: demo
spec:
  profile: demo
  tag: 1.8.0
  meshConfig:
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
    accessLogFile: /dev/stdout
  values:
    global:
      imagePullPolicy: IfNotPresent

I am installing loki using tanka https://grafana.com/docs/loki/latest/installation/tanka/

There are several pods, two pod in focus querier and query-frontend. The query-frontend will not be ready unless querier send a post (port 9095 using grpc) that it is already ready.

The querier pod send a traffic

[2020-11-25T09:51:25.296Z] "POST /frontend.Frontend/Process HTTP/2" 200 - "-" "-" 0 0 0 - "-" "grpc-go/1.29.1" "82562cfe-1814-9e34-a978-754b2770d356" "10.1.1.11:9095" "-" - - 10.1.1.11:9095 10.1.1.12:53728 - block_all

but the front end pod never receive it (no log)

When the outboundTrafficPolicy  = ALLOW_ANY

It runs (no log in front end too but it runs)

Both test using setup:
 - service with port name <protocol>-<port name> (manually modified from recommended installation setup)
 - virtual service with http route match protocol number
 - simple destination rule using host only
 - service for pod querier is normal cluster ip service
 - service for pod front end is headless service (cluster ip = none)

I have checked using istioctl proxy-config at pod querier that the endpoint for frontend is correct, but no listener and outbound route (Question:  is this expected for headless service? that it register no route?)

I have tried:
 - creating service entry for frontend service fqdn
 - creating service entry for frontend pod fqdn
 - using PILOT_ENABLE_EDS_FOR_HEADLESS_SERVICES = true, PILOT_ENABLE_HEADLESS_SERVICE_POD_LISTENERS = false

All does not register outbound route nor listener.

I have come to the conclustion that there may be a bug when outboundTrafficPolicy = REGISTRY_ONLY

Please let me know your thoughts

Thank you

**Comment by howardjohn** [comment]
It would be helpful if you have a minimal Service config we can reproduce with instead of deploying a complex Loki with many parts. Or get a config dump

**Comment by c0ffeec0der** [comment]
Let me prepare something a bit

**Comment by c0ffeec0der** [comment]
[sample.zip](https://github.com/istio/istio/files/5624286/sample.zip)

Hello,

I have created a sample cluster yaml

1. run install.sh
2. wait a minute and check log in pod querier

You will see log file:

2020-11-25T09:51:25.296Z] "POST /frontend.Frontend/Process HTTP/2" 200 - "-" "-" 0 0 0 - "-" "grpc-go/1.29.1" "82562cfe-1814-9e34-a978-754b2770d356" "10.1.1.11:9095" "-" - - 10.1.1.11:9095 10.1.1.12:53728 - block_all

If you change outbound traffic policy to allow any, the pod frontend will be ready but no log entry..

Is my check correct that there is a bug that outboundTrafficPolicy = REGISTRY_ONLY doesn't work for headless service?

**Comment by c0ffeec0der** [comment]
@howardjohn hello, are you able to observe the traffic to headless service that could not flow? do you agree that this is a bug? That outboundTrafficPolicy limits traffic to headless service?

Fyi, i am using temporary workaround using sidecar api to allow the traffic for this kind of case

**Comment by hzxuzhonghu** [comment]
What is port 9095?

**Comment by c0ffeec0der** [comment]
It's grpc for pod to pod communication

**Comment by howardjohn** [comment]
Hi @c0ffeec0der ,I have investigated this case, and it is working as expected. The pod is sending a request to <POD_IP>:9095, with `Host` set to `<POD_IP>:9095`. This is not currently supported - HTTP based routing is done based on the host header, whereas this service is setting it to an IP. See https://istio.io/latest/docs/ops/deployment/requirements/#outbound-traffic

As a workaround, I recommend changing the name of the service port from `grpc` to `tcp`. This will make it use IP based routing rather than header based routing.

https://github.com/istio/istio/issues/23494 is also related

**Comment by howardjohn** [comment]
@hzxuzhonghu this seems wrong: https://github.com/istio/istio/blob/ff67a4e7900526f05fabc53f2b07c88b20a03c21/pilot/pkg/networking/core/v1alpha3/listener.go#L865

"HTTP services can happily reside on 0.0.0.0:PORT and use the wildcard route match to get to the appropriate IP through original dst clusters." not sure how that could actually work...

**Comment by howardjohn** [comment]
Also for auto mode, we set up a listener for the Service/Pod IP - but then we enforce the Host header has the service name as well. seems like we could just match `*`...

**Comment by c0ffeec0der** [comment]
Hello @howardjohn 

It seems tcp routing does not work either with <POD IP>:9095

I read case https://github.com/istio/istio/issues/23494

And tried below
<
      - loadBalancer:
          simple: PASSTHROUGH
        port:
          number: 9095
>

It works

Question

Since neither tcp or http routing works with pod ip. Is this still an open case? I am happy to close this one. Thanks
