### ISSUE TITLE
`istioctl upgrade` seems to be broken

### ISSUE THREAD

**Issue by su225** [istio/istio#29297]
This resulted in upgrade-downgrade test failure.
https://storage.googleapis.com/istio-prow/logs/istio-downgrade-using-istioctl-master-1.8_latest/1333682260397789184/build-log.txt
```
2020-12-01T08:02:56.188860Z	info	proto: tag has too few fields: "-"
Control Plane - ingressgateway pod - istio-ingressgateway-7cfcfc744d-rw78p - version: 1.9.0
Control Plane - pilot pod - istiod-5b456df89c-6wrv8 - version: 1.9.0

Upgrade version check passed: 1.9.0 -> 1.8.0.

2020-12-01T08:02:56.798771Z	info	Error: failed to generate Istio configs from file [] for the current version: 1.9.0, error: failed to fetch URL https://github.com/istio/istio/releases/download/1.9.0/istio-1.9.0-osx.tar.gz : 404 Not Found

Error: failed to generate Istio configs from file [] for the current version: 1.9.0, error: failed to fetch URL https://github.com/istio/istio/releases/download/1.9.0/istio-1.9.0-osx.tar.gz : 404 Not Found
```

https://storage.googleapis.com/istio-prow/logs/istio-downgrade-using-istioctl-1.8_latest-1.7_latest/1333621860826353664/build-log.txt
```
****************

istioctl upgrade istio using version 1.7-alpha.b1e399da889eac53d88c570529c3b0bba53cd68c from to_dir.TvwALe/istio-1.7-alpha.b1e399da889eac53d88c570529c3b0bba53cd68c.

****************

+ istioctl_path=to_dir.TvwALe/istio-1.7-alpha.b1e399da889eac53d88c570529c3b0bba53cd68c/bin
+ to_dir.TvwALe/istio-1.7-alpha.b1e399da889eac53d88c570529c3b0bba53cd68c/bin/istioctl upgrade --skip-confirmation --charts to_dir.TvwALe/istio-1.7-alpha.b1e399da889eac53d88c570529c3b0bba53cd68c/manifests
Control Plane - ingressgateway pod - istio-ingressgateway-5487946b9b-rg4z6 - version: 1.8.0
Control Plane - pilot pod - istiod-895b99b-rl6qk - version: 1.8.0

2020-12-01T04:03:02.290805Z	info	Error: upgrade version check failed: 1.8.0 -> 1.7.0. Error: upgrade is currently not supported from version: 1.8.0

Error: upgrade version check failed: 1.8.0 -> 1.7.0. Error: upgrade is currently not supported from version: 1.8.0
```

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Comment by shamsher31** [comment]
`1.9` is not officially released and the upgrade command looks for official release URL to download from.

For `1.8` to `1.7` downgrade. The fix is here https://github.com/istio/istio/pull/29288 and will be available in `1.8.1`.

**Comment by su225** [comment]
@shamsher31 - Ok. So "in-place upgrade job from 1.8 to master" keeps failing. That is some noise that we have to tolerate. What's peculiar is `osx` in `istio-1.9.0-osx.tar.gz`? Why do we assume `osx`?

**Comment by shamsher31** [comment]
Yah, master build needs to be fixed for upgrade and downgrade.

**Comment by su225** [comment]
Tests are fine now. So closing the issue.
