### ISSUE TITLE
analyzer: conflicting ports

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#29302]
If we have two services, both selecting the same workload, with the same target port, they should be the same port.

This analyzes a requirement in https://istio.io/latest/docs/ops/deployment/requirements/: "Service association: A pod must belong to at least one Kubernetes service even if the pod does NOT expose any port. If a pod belongs to multiple Kubernetes services, the services cannot use the same port number for different protocols, for instance HTTP and TCP."

**Comment by howardjohn** [comment]
Note it is the targetPort that matters, not the Service port

**Comment by esnible** [comment]
Can this be closed now that the PR is merged?

**Comment by kebe7jun** [comment]
I'm working on docs, should I wait until the doc completed?

**Comment by kebe7jun** [comment]
> @kebe7jun Can this be closed now that the PR is merged?

docs merged, I think this issue should be closed.
