### ISSUE TITLE
Automated test for upgrading from in cluster istiod to external istiod

### ISSUE THREAD

**Issue by linsun** [istio/istio#29304]
**Describe the feature request**

We need to have automated tests for upgrading for in cluster istiod to external istiod. A typical scenario:

1. Mesh operator has already installed istio control plane and default gateway.  (Bonus scenario: mesh operator also installed a custom gateway #29303 .)
2. Mesh operator also setup external istiod.  Mesh operator gives mesh admin the instruction to access the external istiod, and mesh admin can follow the instruction to switch the data plane to use the external istiod.  This may likely requires configuring the external istiod url ([design doc](https://docs.google.com/document/d/1k9V3D5jhZdFvEdJhw-T7mHCEIjkK0hFSdvtJIWEqIs0/edit) is in place to enable this), and rolling restart the sidecars.
3. mesh admin can confirm the upgrade is successful by apps running via ingress gateway after switching to use external istiod.

Note: this would be revision upgrade, not in place upgrade for the data planes.

cc @rvennam @William-Newshutz @sdake @costinm @howardjohn 

[ ] Docs
[ x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[x] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by sdake** [comment]
No objection, however, the upgrade WG charter, not yet approved, indicates that in-place will be removed as a testing objective and as a feature. I disagree removing it as a feature does not make sense for a majority of Istio's customers at this time.

https://docs.google.com/document/d/17zTAP9HaAe211GILgxUILRTzbX5r3JheV9gs5L6rfcM/edit?ts=5fc67030

**Comment by sdake** [comment]
oh, missed this would be revision upgrades...

**Comment by ericvn** [comment]
Per TOC today, in-place upgrades will continue to be supported, but there may be down-time experienced with them. Upgrade test cases may be sharable between in-place and revision-based upgrades (hope is there they can be).

**Comment by ericvn** [comment]
Question related to upgrading needed as part of the promote external istiod to remote work?

**Comment by zhlsunshine** [comment]
Hi @ericvn,  shall we move this issue to 1.12?
