### ISSUE TITLE
Istio controller doesn't properly handle modification of k8s annotations

### ISSUE THREAD

**Issue by yozel** [istio/istio#29306]
Controller doesn't properly handle modification of `spec.components.ingressgateway[].k8s.serviceAnnotations` value. It is able to add or change the current value of an annotation on the `service` resource but can't remove it. I'm not familiar with istio codebase but I suspect that the cause of this behavior is `patchStrategy:"merge"` tag on field `ServiceAnnotations` of `ingressGatewayConfig` struct.

https://github.com/istio/istio/blob/d5893dc37b2c1ab9d05d839173017b35990c8e92/operator/pkg/util/merge_iop.go#L103

I think this is a bug and not intended behavior but I'm not so sure. I can create a pull request if it's a bug.

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

```bash
$ kubectl get svc istio-ingressgateway -o json | jq '.metadata.annotations'
{
  "kubectl.kubernetes.io/last-applied-configuration": "...",
  "testannotation": "testvalue"
}

$ kubectl patch IstioOperator example-istiocontrolplane --type=merge -p '{"spec": {"components": {"ingressGateways": [{"enabled": true, "k8s": {"serviceAnnotations": {}}}]}}}'
$ kubectl get svc istio-ingressgateway -o json | jq '.metadata.annotations'
{
  "kubectl.kubernetes.io/last-applied-configuration": "..."
}
```

**Steps to reproduce the bug**

Install IstioOperator and create an IstioOperator resource with a service annotation:

```bash
# INSTALL IstioOperator
$ istioctl operator init

# CREATE IstioOperator
$ kubectl create ns istio-system
$ kubectl apply -f - <<EOF
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: example-istiocontrolplane
spec:
  profile: minimal
  components:
    ingressGateways:
    - enabled: true
      k8s:
        serviceAnnotations:
          testannotation: testvalue
EOF
$ kubectl get svc istio-ingressgateway -o json | jq '.metadata.annotations'
{
  "kubectl.kubernetes.io/last-applied-configuration": "...",
  "testannotation": "testvalue"
}
```
I'm able to modify it:

```bash
# Change `spec.components.ingressgateway[0].k8s.serviceAnnotations.testannotation` of IstioOperator to `anothertestvalue`
kubectl patch IstioOperator example-istiocontrolplane --type=merge -p '{"spec": {"components": {"ingressGateways": [{"enabled": true, "k8s": {"serviceAnnotations": {"testannotation": "anothertestvalue"}}}]}}}'
$ kubectl get svc istio-ingressgateway -o json | jq '.metadata.annotations'
{
  "kubectl.kubernetes.io/last-applied-configuration": "...",
  "testannotation": "anothertestvalue"
}

```

But can't delete:

```bash
# Delete `spec.components.ingressgateway[0].k8s.serviceAnnotations.testannotation` of IstioOperator
kubectl patch IstioOperator example-istiocontrolplane --type=merge -p '{"spec": {"components": {"ingressGateways": [{"enabled": true, "k8s": {"serviceAnnotations": {}}}]}}}'
$ kubectl get svc istio-ingressgateway -o json | jq '.metadata.annotations'
{
  "kubectl.kubernetes.io/last-applied-configuration": "...",
  "testannotation": "anothertestvalue"
}
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```bash
$ istioctl version --remote
client version: 1.7.4
control plane version: 1.7.4
data plane version: 1.7.4 (1 proxies)

$ kubectl version --short
Client Version: v1.19.3
Server Version: v1.19.4+k3s1
```

**How was Istio installed?**

With `istioctl operator init`

**Environment where the bug was observed (cloud vendor, OS, etc)**
I am able to reproduce it in two different environments

- AWS EKS cluster
- my local k3s cluster on Ubuntu 20.04 (amd64)

**Comment by morvencao** [comment]
Similar root cause with https://github.com/istio/istio/issues/29188
It is supposed to be working after switching to server side apply.

**Comment by shamsher31** [comment]
Similar issue https://github.com/istio/istio/issues/27045

Strategic merge patch requires the `name` field to be present. Try adding `name: istio-ingressgateway`.

```yaml
$ kubectl apply -f - <<EOF
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: example-istiocontrolplane
spec:
  profile: minimal
  components:
    ingressGateways:
    - enabled: true
      name: istio-ingressgateway
      k8s:
        serviceAnnotations:
          testannotation: testvalue
EOF
```

**Comment by shamsher31** [comment]
I found the docs mention it https://istio.io/latest/docs/setup/install/istioctl/#configure-gateways

![gateway](https://user-images.githubusercontent.com/2920003/100836392-3b06b980-3495-11eb-88b8-9b092ec37a84.png)

**Comment by yozel** [comment]
@shamsher31 I don't know why but it didn't fix the problem.

```bash
$ kubectl apply -f - <<EOF
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: example-istiocontrolplane
spec:
  profile: minimal
  components:
    ingressGateways:
    - enabled: true
      name: istio-ingressgateway
      k8s:
        serviceAnnotations:
          testannotation: testvalue
EOF

$ kubectl get svc istio-ingressgateway -o json | jq '.metadata.annotations'
{
  "kubectl.kubernetes.io/last-applied-configuration": "...",
  "testannotation": "testvalue"
}

$ kubectl patch IstioOperator example-istiocontrolplane --type=merge -p '{"spec": {"components": {"ingressGateways": [{"name": "istio-ingressgateway", "enabled": true, "k8s": {"serviceAnnotations": {"anotherannotation": "anothertestvalue"}}}]}}}'

$ kubectl get svc istio-ingressgateway -o json | jq '.metadata.annotations'
{
  "anotherannotation": "anothertestvalue",
  "kubectl.kubernetes.io/last-applied-configuration": "...",
  "testannotation": "testvalue"
}
```

Why the controller merges the desired state with the current state? Can't it just replace those fields instead of merging them? I haven't used `istioctl install` or `istioctl upgrade` before and I'm assuming that they work imperatively. But AFAIK, the operator pattern should work declaratively.

**Comment by morvencao** [comment]
> Strategic merge patch requires the name field to be present. Try adding name: istio-ingressgateway.

it's not the root cause, see: https://github.com/istio/istio/issues/29188#issuecomment-734114403
