### ISSUE TITLE
Automated tests for custom gateways

### ISSUE THREAD

**Issue by linsun** [istio/istio#29303]
**Describe the feature request**
We need to have automated tests for custom gateways.  A typical scenario:
1. Mesh operator can install a custom gateway in a custom namespace, in addition to the default gateway.
2. Mesh operator can in-place upgrade the custom gateway in the custom namespace with little or no time down when the custom gateway has multiple replicas.  The default gateway upgrade should have no impact on the custom gateway.  Custom gateway upgrade should have no impact on the default gateway.  They are installed and upgraded independently.

cc @rvennam @William-Newshutz @sdake @houshengbo 

**Describe alternatives you've considered**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[x ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by linsun** [comment]
Normal sequence of update is control plane first, gateway next, then sidecars.  https://github.com/istio/istio/issues/29427 revealed a possible pattern where some sidecars are updated before admin has a chance to update custom gateway.  This could happen when the pod got restarted either intentionally or unintentionally.  This scenario should be considered as it is valid and built into this WI.

**Comment by ericvn** [comment]
Pointer to https://github.com/istio/istio/pull/30379 to help with upgrades when customers gateways are in different namespaces.
