### ISSUE TITLE
Multicluster supportability

### ISSUE THREAD

**Issue by nmittler** [istio/istio#29307]
This epic tracks various tasks resulting from the multicluster [supportability review](https://docs.google.com/document/d/1-YRKf67ptsRov-s-Z2gJ4VaI-T9s6SPS_Nu_W-iJ0d8/edit#heading=h.1ea3ns3s6e6c), which was part of the process for promotion of multicluster to Beta in Istio 1.8.

**Comment by howardjohn** [comment]
While probably still work to be done, this isn't actively being worked on for years
