### ISSUE TITLE
Istio 1.8 not doing multicluster routing using service entry & global dns stubbing

### ISSUE THREAD

**Issue by martin2176** [istio/istio#29308]
With Istio 1.7 I was able to do multi cluster routing using Service Entry in replicated CP configuration
Basically a combination of istio core dns plugin resolving dns domain "global" and istio sni-dnat proxy port 15443 and manual service entry .
This procedure documented here worked fine --> https://istio.io/v1.7/docs/setup/install/multicluster/gateways/

With Istio 1.8, the sni aware gateway have been moved to a dedicate east west gateway.
Automatic service discovery in remote cluster is working fine in 1.8. I can call services in other clusters using cluster.local dns name, but the global dns routing which have worked in previous releases is no longer working.
The EW gateway seems to only route traffic with dns suffix *.local as there is a gateway configuration which is attached to the EW gateway which has hosts as "*.local".
I tried to add *.global , it did help to route traffic from cluster 1 --> cluster 2
I deleted the gateway configuration attached to the EW gateway, that did not help either.
So my question is, in Istio 1.8 does the traffic routing feature using "global" dns stubbing and service entry no longer an option?

**Comment by howardjohn** [comment]
cc @nmittler

**Comment by nmittler** [comment]
The `.global` configuration was never well tested and has been in some form of broken since 1.6.x. For a variety of reasons, we've moved away from this as our recommended configuration for 1.8 (we meant to switch over in 1.7, but ran out of time for the docs).

I'm not against fixing it (and adding tests), however ... I think it's a matter of bandwidth and priorities currently. If someone wants to take this on, I'd be happy to review PRs.

**Comment by martin2176** [comment]
If .global is not the recommended from 1.8 onwards, what is the correct/recommended approach for multi cluster routing ?
Following the 1.8 multicluster documentation, here is what I am thinking of doing:-
For replicated CP topology:
1) Create stub namespace and stub services in all the clusters which are part of the mesh
2) Configure istiod to discover remote end points by configuring remove secret. 
3) Access services in remote clusters using <service>.<namespace>.svc.cluster.local
Is the above procedure going to stay for next few minor releases atleast? Is there a good longevity of this
//The above does seem to work well, even though creating stub namespaces and services are bit painful to manage.//

I also read there is a dns proxy istiod agent based automatic configuration of dns names which would obviate this manual step of creating stub services, but not much documentation on how to go about setting it up.

**Comment by nmittler** [comment]
Yes that's the recommended approach and will be maintained going forward.

> I also read there is a dns proxy istiod agent based automatic configuration of dns names which would obviate this manual step of creating stub services, but not much documentation on how to go about setting it up.

Yeah that's right. The stub namespace/service will likely be resolved in the future (at least for workloads with a sidecar) once istiod intercepts DNS. It's actually working today, but disabled by default. Documentation will follow once it's no longer experimental.

**Comment by martin2176** [comment]
Can someone update the release notes to this effect that ".global" is deprecated and not guaranteed to work in 1.8 rel notes. I know many customers coming from previous releases have relied on ".global" dns stubbing and the sni-dnat 15443 ingress port to take care of routing the traffic to other clusters which are part of the mesh. In my pov, if this feature is not guaranteed to work in 1.8  (And I can say off the bat it is not working in 1.8) then there are a lot of customers who are setup for surprises as they upgrade to 1.8.

**Comment by nmittler** [comment]
@martin2176 sorry this fell off my radar: https://github.com/istio/istio/pull/29650

**Comment by howardjohn** [comment]
Fixed by https://github.com/istio/istio/pull/29650, followup in https://github.com/istio/istio/issues/29335
