### ISSUE TITLE
'make DEBUG=1 build' error on MAC OS

### ISSUE THREAD

**Issue by carryxyh** [istio/istio#29321]
Error occurs while I exec `make HUB=docker.io/xxx TAG=xxx ISTIO=/xxx/go-project/src/istio DEBUG=1 docker`:

```
can't load package: package .: no Go files in /work
can't load package: package -pkgdir=/go/pkg/linux_amd64 is not in GOROOT (/usr/local/go/src/-pkgdir=/go/pkg/linux_amd64)
can't load package: package -ldflags is not in GOROOT (/usr/local/go/src/-ldflags)
```

The golang version I use is: `go version go1.14.12 darwin/amd64`.
The istio branch is `release-1.7`.

Looks like a cross-compilation problem.. But on my Mac, compile a `.go` file into a Linux executable work well.

**Comment by carryxyh** [comment]
By the way, is there a debug image that has been compiled to use?

**Comment by ericvn** [comment]
This problem was fixed in later branches with https://github.com/istio/common-files/pull/305, but never cherry-picked back to `release-1.7`.

**Comment by ericvn** [comment]
Cherry-picked.

**Comment by carryxyh** [comment]
Thanks alot, will have a try later.
