### ISSUE TITLE
bug-report has no timeout on requests to proxy

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#29342]
See https://github.com/istio/istio/issues/29334 at the end

```
I've tried to generate the bug-report, but it fails at:

The following fetches are still running:
  ProxyGet istio-ingress/istio-ingressgateway-6ddcc556fb-9xstz:certs
```

In their case envoy is broken and not responding to admin requests. Probably we don't set a timeout.

**Comment by mvladev** [comment]
The message above is shown for over 10 mins, and after that I stopped the command. I guess it loops over that constantly.
