### ISSUE TITLE
Ingressgateway unhealthy and sidecar injection failing

### ISSUE THREAD

**Issue by rancher-max** [istio/istio#29353]
**Bug description**
On an rke2 cluster running on selinux enforcing systems, I see two different errors. If I create the cluster using default options, then try to run istio, sidecar injection fails (see logs noted in https://github.com/rancher/rke2/issues/504#issuecomment-731496413). If I run `modprobe nf_nat_ipv6` as part of cluster creation in the service file, then try to enable istio, it fails to bring up the ingressgateway pod with the same error as in https://github.com/istio/istio/issues/28045.

Some additional information can be found in each of the linked issues. 

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
In the first case, I expect sidecar injection should work. There should be some kernel setting upon cluster creation to ensure the pods all come up successfully.

**Steps to reproduce the bug**
1. Create an rke2 cluster on selinux enforcing system
2. Enable istio
3. Run a workload with sidecar injection enabled

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
- (Installed via rancher: `rancher-istio:1.5.900` == `istio v1.5.9`)
- kubectl version: 
```
Client Version: v1.18.2
Server Version: v1.18.12+rke2r1
```

**How was Istio installed?**
- Using rancher, v2 apps & marketplace Istio

**Comment by howardjohn** [comment]
If you see the error in https://github.com/istio/istio/issues/28045, that sounds like cluster networking is completely broken. We are essentially just doing a standard http connection between two pods - basic K8s networking is a requirement for Istio. https://github.com/istio/istio/issues/28045#issuecomment-711459253 was the solution for them.

Not sure about the nf_nat_ipv6 part though

**Comment by howardjohn** [comment]
found https://github.com/rancher/rke2/pull/581/files as well
