### ISSUE TITLE
destination_service_namespace unknown in a lot of the istio_requests_total metric

### ISSUE THREAD

**Issue by ediezh** [istio/istio#29354]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
We have an Nginx proxy service accepting requests coming from the ingress gateway. The nginx service has sidecar configured. A lot of the istio_requests_total metrics reported from source contain unknown labels, such as destination_service_namespace. But some of them do report correctly.

* Query the service by destination_server. Some of the results have destination_service_name reported correctly, but some of them are unknown. Interesting point is that this is for the same service.
```
istio_requests_total{destination_service=~"surgery-app-server-proxy.*", reporter="source"} 
```

```
istio_requests_total{app="istio-ingressgateway",chart="gateways",connection_security_policy="unknown",destination_app="surgery-app-server-proxy",destination_canonical_revision="latest",destination_canonical_service="surgery-app-server-proxy",destination_principal="spiffe://cluster.local/ns/surgery-app-dev/sa/default",destination_service="surgery-app-server-proxy.surgery-app-dev.svc.cluster.local",destination_service_name="surgery-app-server-proxy",destination_service_namespace="surgery-app-dev",destination_version="unknown",destination_workload="surgery-app-server-proxy",destination_workload_namespace="surgery-app-dev",heritage="Tiller",instance="10.205.225.116:15090",istio="ingressgateway-quicktome-elb",job="kubernetes-pods",kubernetes_namespace="istio-system",kubernetes_pod_name="istio-ingressgateway-quicktome-elb-866599b698-bmg2f",pod_template_hash="866599b698",quicktome="true",release="istio",reporter="source",request_protocol="http",request_url="/api/v1/gapServer/5f3820ab7f2791e7fb89faf7/polling/giveMeSomethingToDo",response_code="502",response_flags="-",service_istio_io_canonical_name="istio-ingressgateway-quicktome-elb",service_istio_io_canonical_revision="latest",source_app="istio-ingressgateway",source_canonical_revision="latest",source_canonical_service="istio-ingressgateway-quicktome-elb",source_principal="spiffe://cluster.local/ns/istio-system/sa/istio-ingressgateway-quicktome-elb-service-account",source_version="unknown",source_workload="istio-ingressgateway-quicktome-elb",source_workload_namespace="istio-system"}
istio_requests_total{app="istio-ingressgateway",chart="gateways",connection_security_policy="unknown",destination_app="unknown",destination_canonical_revision="latest",destination_canonical_service="unknown",destination_principal="unknown",destination_service="surgery-app-server-proxy.surgery-app-dev.svc.cluster.local",destination_service_name="surgery-app-server-proxy.surgery-app-dev.svc.cluster.local",destination_service_namespace="unknown",destination_version="unknown",destination_workload="unknown",destination_workload_namespace="unknown",heritage="Tiller",instance="10.205.225.116:15090",istio="ingressgateway-quicktome-elb",job="kubernetes-pods",kubernetes_namespace="istio-system",kubernetes_pod_name="istio-ingressgateway-quicktome-elb-866599b698-bmg2f",pod_template_hash="866599b698",quicktome="true",release="istio",reporter="source",request_protocol="http",request_url="/api/v1/gapServer/5f3820ab7f2791e7fb89faf7/polling/giveMeSomethingToDo",response_code="503",response_flags="UH",service_istio_io_canonical_name="istio-ingressgateway-quicktome-elb",service_istio_io_canonical_revision="latest",source_app="istio-ingressgateway",source_canonical_revision="latest",source_canonical_service="istio-ingressgateway-quicktome-elb",source_principal="unknown",source_version="unknown",source_workload="istio-ingressgateway-quicktome-elb",source_workload_namespace="istio-system"}
```
**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
All the istio_requests_total metrics have labels populated correctly.

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

v1.7

**How was Istio installed?**

istioctl

**Environment where the bug was observed (cloud vendor, OS, etc)** EKS 1.16

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by bianpengyuan** [comment]
Does the staging service has sidecar injected? It makes sense if it does not, since its workload metadata will not be available at ingress via metadata exchange. This has been resolved by 1.8. It would be great if you can try it out quickly and see if that resolves your issue.

**Comment by ediezh** [comment]
Hi @bianpengyuan yes the services have sidecar injected.

**Comment by ediezh** [comment]
I noticed a difference in the two metrics I attached above.

The one with unknown labels, the destination_service_name is still the FQDN of the service
`destination_service="surgery-app-server-proxy.surgery-app-dev.svc.cluster.local",destination_service_name="surgery-app-server-proxy.surgery-app-dev.svc.cluster.local"`

But for the one with all labels populated, the destination_service_name is only the service name.
`destination_service="surgery-app-server-proxy.surgery-app-dev.svc.cluster.local",destination_service_name="surgery-app-server-proxy"`

**Comment by bianpengyuan** [comment]
Yeah, that is also expected behavior with 1.7.

I saw that you updated the time series in the description, and request getting 503 make sense to have `unknown` labels for workload, due to the same reason that metadata exchange did not happen for request that does not reach server sidecar. So again 1.8 would have the fix for this issue.

**Comment by ediezh** [comment]
@bianpengyuan we have 200 requests that get unknown labels.

```
istio_requests_total{destination_service=~"surgery-app-server-proxy.*", reporter="source", response_code="200", destination_service_namespace="unknown"} 
```

And one time series example
```
istio_requests_total{app="istio-ingressgateway",chart="gateways",connection_security_policy="unknown",destination_app="unknown",destination_canonical_revision="latest",destination_canonical_service="unknown",destination_principal="spiffe://cluster.local/ns/surgery-app-dev/sa/default",destination_service="surgery-app-server-proxy.surgery-app-dev.svc.cluster.local",destination_service_name="surgery-app-server-proxy.surgery-app-dev.svc.cluster.local",destination_service_namespace="unknown",destination_version="unknown",destination_workload="unknown",destination_workload_namespace="unknown",heritage="Tiller",instance="10.205.225.116:15090",istio="ingressgateway-quicktome-elb",job="kubernetes-pods",kubernetes_namespace="istio-system",kubernetes_pod_name="istio-ingressgateway-quicktome-elb-866599b698-bmg2f",pod_template_hash="866599b698",quicktome="true",release="istio",reporter="source",request_protocol="http",request_url="/api/v1/gapServer/5f3820ab7f2791e7fb89faf7/polling/hosts",response_code="200",response_flags="-",service_istio_io_canonical_name="istio-ingressgateway-quicktome-elb",service_istio_io_canonical_revision="latest",source_app="istio-ingressgateway",source_canonical_revision="latest",source_canonical_service="istio-ingressgateway-quicktome-elb",source_principal="spiffe://cluster.local/ns/istio-system/sa/istio-ingressgateway-quicktome-elb-service-account",source_version="unknown",source_workload="istio-ingressgateway-quicktome-elb",source_workload_namespace="istio-system"}
```

**Comment by bianpengyuan** [comment]
Yeah I don't have a theory for that other than maybe some of your pods do not have sidecar injected. If it is feasible, could you please try out 1.8 and see if that fixes your issue? It is highly likely that those are already fixed there, and we can start further investigation if the issue persists after upgrading.

**Comment by bianpengyuan** [comment]
I assume this is solved at 1.8. Please reopen if this still happens after upgrading. Thanks!

**Comment by Janesee3** [comment]
Hi @bianpengyuan, I'm currently on Istio 1.7 and we are migrating to Telemetry V2 before making the move to Istio 1.8. I noticed that my `istio_requests_total` metric is also returning `destination_service_namespace=unknown` for destination services that are created by `ServiceEntry` resources in a dedicated namespace (ie. these services aren't workloads that are backed by any sidecars)

Is this expected? If so, may I know if this is also fixed in 1.8? Thank you!

**Comment by bianpengyuan** [comment]
> Hi @bianpengyuan, I'm currently on Istio 1.7 and we are migrating to Telemetry V2 before making the move to Istio 1.8. I noticed that my `istio_requests_total` metric is also returning `destination_service_namespace=unknown` for destination services that are created by `ServiceEntry` resources in a dedicated namespace (ie. these services aren't workloads that are backed by any sidecars)
> 
> Is this expected? If so, may I know if this is also fixed in 1.8? Thank you!

For SE defined service, I think `destination_service_namespace` will remain unknown, but `destination_service` label will be filled with host specified at ServiceEntry.

**Comment by Janesee3** [comment]
Oh ok that's unfortunate :( , but thanks for your response!

Will there be plans to "fix" this, or is it not considered as a bug, given V2's implementation? We have a use case where want to monitor the traffic to a specific group of external hosts, which we could do previously by filtering using the `destination_service_namespace` label. Are you able to recommend any alternatives?

**Comment by bianpengyuan** [comment]
Actually I take that back. Just tried it out and I think `destination_service_namespace` will be filled. Can you upgrade to 1.8 and try?

**Comment by Janesee3** [comment]
That's great news! I have plans to upgrade to Istio 1.8 in a week or two. Will let you know when I've tried it out, thank you!

**Comment by chadlwilson** [comment]
@bianpengyuan This doesn't appear to be addressed in `1.8.6` either, i.e we are still seeing `destination_service_namespace=unknown`. We intend to move to 1.9.x shortly so we can check there also.

If it adds additional relevant context, the `ServiceEntry`s in my case are in a different namespace to the reporting service, which is done so we can restrict visiblity using `Sidecar` sources.

**Comment by bianpengyuan** [comment]
> @bianpengyuan This doesn't appear to be addressed in `1.8.6` either, i.e we are still seeing `destination_service_namespace=unknown`. We intend to move to 1.9.x shortly so we can check there also.
> 
> If it adds additional relevant context, the `ServiceEntry`s in my case are in a different namespace to the reporting service, which is done so we can restrict visiblity using `Sidecar` resources.

@chadlwilson Can you create a separated issue for this? Thanks!

**Comment by Thilaknath** [comment]
We are currently in 1.9.4 and we are facing the same issue with a lot of entries coming from istio having unknown metrics.

**Comment by bianpengyuan** [comment]
@Thilaknath What are the labels with unknown, and where did you observe it (inbound sidecar, or outbound sidecar, or gateway)? There are cases where labels value cannot be determined so probably something works as expected.

**Comment by Thilaknath** [comment]
@bianpengyuan `{"destination",request_protocol="http",response_code="200",response_flags="-",source_app="unknown",source_canonical_revision="latest",source_canonical_service="unknown",source_cluster="unknown",source_principal="unknown",source_version="unknown",source_workload="unknown",source_workload_namespace="unknown"}`

As you can see in the above metric, none of the source attributes has values. I was able to find that we have a workload which has istioproxy enabled. The service also has a liveness probe in its deployment set to an interval 30s. The above metric is fir sure the service trying to ping itself. But its not able to determine its source. 

Istio examples/documentation doesn't seem to discuss this. 
Also, a similar metric where the destination are unknown 

`istio_requests_total{connection_security_policy="unknown",container="istio-proxy",destination_app="unknown",destination_canonical_revision="latest",destination_canonical_service="unknown",destination_cluster="unknown",destination_principal="unknown",destination_service="event.system.svc.cluster.local",destination_service_name="event-gateway",destination_service_namespace="unknown",destination_version="unknown",destination_workload="unknown",destination_workload_namespace="unknown",instance="100.96.0.102:15020",job="istio-system/envoy-stats-monitor",namespace="istio-system",pod="istio-ingressgateway-5795c68bdd-9w5q5",pod_name="istio-ingressgateway-5795c68bdd-9w5q5",reporter="source",request_protocol="http",response_code="401",response_flags="-",source_app="istio-ingressgateway",source_canonical_revision="latest",source_canonical_service="istio-ingressgateway",source_cluster="Kubernetes",source_principal="unknown",source_version="unknown",source_workload="istio-ingressgateway",source_workload_namespace="istio-system"}`

**Comment by bianpengyuan** [comment]
See `What are the differences in telemetry reported by in-proxy telemetry (aka v2) and Mixer-based telemetry (aka v1)?` here in metrics and logs FAQ: https://istio.io/latest/about/faq/#metrics-and-logs. It has some information about why workload labels could be missing. Not sure if any of those apply to you.
