### ISSUE TITLE
IPv6 address given in DestinationRule & ServiceEntry is not available in route_config.virtual_hosts.domains , but available for IPv4

### ISSUE THREAD

**Issue by vbalaganes** [istio/istio#29362]
Hi ,

I have installed Istio 1.6.8 in a IPv6 K8s Cluster.
I created DestinationRule & Service Entry with IPv6 Address.

### Sample Destination Rule: 
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: test
  namespace: test
spec:
  **host: 2a00:8a00::60a.11122.IP** ------> IPv6 address.Port.IP
    portLevelSettings:
    **- port:
        number: 11122**
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 10
    loadBalancer:
      simple: ROUND_ROBIN

### Sample Service Entry : 
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: test-se
  namespace: test
spec:
  **addresses:
  - 2a00:8a00::60a
  endpoints:
  - address: 2a00:8a00::60a
  hosts:
  - 2a00.8a00::60a.11122.IP
  location: MESH_EXTERNAL
  ports:
  - name: http2-11122
    number: 11122**
    protocol: HTTP2
  resolution: STATIC

In this case if we check dynamic_route. route_config through configdump , i get the following ,
IPV6 address are missed under route_config.domains but it is working fine for IPv4. 

     "version_info": "2020-12-01T09:15:18Z/51",
     "route_config": {
      "@type": "type.googleapis.com/envoy.api.v2.RouteConfiguration",
      "name": "11122",
      "virtual_hosts": [
       {
        "name": "2a00.8a00::.60a.11122.IP:11122",
        "domains": [
         "2a00.8a00::60a.11122.IP",
         "2a00.8a00::60a.11122.IP:11122"
        ],

But in case of IPV4 iam getting the IPs in domains 

      "virtual_hosts": [
       {
        "domains": [
         "10.x.x.244.11122.IP",
         "10.x.x.244.11122.IP:11122", 
        "10.x.x.244:11122",---------> Correct but it is missing in IPv6.
        "10.x.x.244" ----------------> Correct but it is missing in IPv6.        
        ],

Kindly help to solve this. [This secnario is applicable for ServiceEntry also]

**Comment by howardjohn** [comment]
Sorry, I don't understand. I think you have censored to much and obscured understanding
```
     "10.x.x.244.11122.IP",
     "10.x.x.244.11122.IP:11122", 
```

This format does not look right should never be generated.

I think either you did not provide the full config you the output has been modified. can you clarify?

**Comment by howardjohn** [comment]
Any more info?

**Comment by vbalaganes** [comment]
> Any more info?

Hi HowardJohn ,
    
       I have shared you the dynamic_route. route_config section from the configdump.
       If IPv4 address is specified in the 'Hosts' field  of Destination rule & service entry , dynamic_route.route_config section of the 
       configdump has the IPs provided.
       If IPv6 address is specified in the 'Hosts' filed of Destination rule & service entry , we are not getting the IPs listed under 
      dynamic_route.route_config section of the configdump.
