### ISSUE TITLE
telemetry destination_cluster set to "unknown" on client failures

### ISSUE THREAD

**Issue by jshaughn** [istio/istio#29373]
Istio 1.8.0
OpenShift 4.5

[Slack Thread](https://istio.slack.com/archives/C382V8Q92/p1607019050254900)

I have a cluster configured for multi-cluster; meshId, clusterName, and network are all defined, and the telemetry is now setting source_cluster and destination_cluster attributes.  But I am seeing a problem where, on client failures like 503, or an upstream disconnect with no response (response_code=0), the destination_cluster is set to "unknown" despite the fact that destination_namespace|service|service_name|workload are all set correctly.  I would expect destination_cluster to be set anytime the destination_service has also been set.  Without the destination_cluster the destination can not be fully identified.

Probably implied, but this is for reporter="source" telemetry.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

In MC, when the destination service has been identified for a request, the destination_cluster should also be set.

**Steps to reproduce the bug**

This can be reproduced on a single cluster, as long as it is configured for multi-cluster.   I am seeing it with some standard running of bookinfo but it could probably be forced with fault injection.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

`istioctl version --remote`
client version: 1.8.0
control plane version: 1.8.0
data plane version: 1.8.0 (11 proxies)

`kubectl version --short`
Client Version: 4.4.3
Server Version: 4.6.1
Kubernetes Version: v1.19.0+d59ce34

**How was Istio installed?**

istioctl

**Environment where the bug was observed (cloud vendor, OS, etc)**

OpenShift 4.5

**Comment by jshaughn** [comment]
Please do not close this issue, hoping for a fix in 1.10.

**Comment by jshaughn** [comment]
@bianpengyuan , Can this be backported to 1.9 as well?

**Comment by bianpengyuan** [comment]
@jshaughn probably, depends on how much you want this :). It is a bit onerous to backport. one pr in proxy + two PRs in istio/istio.

**Comment by jshaughn** [comment]
@bianpengyuan I guess we could wait and see whether a user hits the issue.  I'd say it's possible because I run into problems even running bookinfo.  But we can wait and see.
