### ISSUE TITLE
istioctl version -o json outputs invalid json

### ISSUE THREAD

**Issue by curtispd** [istio/istio#29381]
**Bug description**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

`istioctl version -o json` outputs valid json even if istio is not installed. (In my case I'm trying to detect if it's installed or not via a script)

**Steps to reproduce the bug**

Run `istioctl version -o json` on a cluster that doesn't have Istio installed. It looks valid, but there's an extra line at the top that makes it invalid json:

```
$ istioctl version -o json
no running Istio pods in "istio-system"
{
  "clientVersion": {
    "version": "1.7.5",
    "revision": "63ddfef22d6a110d94473da88f466eb38e397848",
    "golang_version": "go1.14.12",
    "status": "Clean",
    "tag": "1.7.5"
  }
}
```

So if I do, for example, `istioctl version -o json | jq` it results in an error:
```
$ istioctl version -o json | jq
parse error: Invalid literal at line 1, column 3
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

$ istioctl version
no running Istio pods in "istio-system"
1.7.5

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.14", GitCommit:"f238f5142728be4033c37aa0ad69bf806090beae", GitTreeState:"clean", BuildDate:"2020-11-11T13:11:40Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.14+IKS", GitCommit:"35f1768b1292e15e3e5ca2e31658ecf675c4d5a6", GitTreeState:"clean", BuildDate:"2020-11-12T18:37:40Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

**How was Istio installed?**

It wasn't.

**Environment where the bug was observed (cloud vendor, OS, etc)**

IBM Cloud (Istio managed addon)

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by curtispd** [comment]
Sorry, accidental submit before I filled out the description. Adding now.

**Comment by esnible** [comment]
Note: to reproduce on a cluster WITH Istio, `istioctl version --revision invalid -o json | jq`

**Comment by esnible** [comment]
Thanks for filing this.

Those error messages were being written to the same place the JSON was, making it impossible to parse the JSON.  I have created a small fix at https://github.com/istio/istio/pull/29397 feel free to let me know if you believe it would solve your issue.

**Comment by curtispd** [comment]
Yes the fix looks good @esnible - thanks for the fix!
