### ISSUE TITLE
Support Kubernetes MCS ServiceExport

### ISSUE THREAD

**Issue by nmittler** [istio/istio#29385]
This is "phase 2" as described in the [Istio+MCS RFC](https://docs.google.com/document/d/1K8hvQ83UcJ9a7U8oqXIefwr6pFJn-VBEi40Ak-fwQtk/edit#)

We should add support for generating ServiceExport for all services in the mesh.

For now, assume a flat network (i.e. direct pod-to-pod reachability).

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by josephpeacock** [comment]
Design doc: https://docs.google.com/document/d/1vOCuMpWa1L6TFmxSP71fLG2jWPFkGvnFk86s11ej51U/edit?pli=1#

**Comment by nmittler** [comment]
not stale

**Comment by nmittler** [comment]
Fixed by https://github.com/istio/istio/pull/31401
