### ISSUE TITLE
istio.io setup/install/multicluster/primary-remote/test.sh test fails on `main` branch

### ISSUE THREAD

**Issue by ericvn** [istio/istio#29389]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

This may be a duplicate of #29388 as the east west-gateway isn't found.

setup/install/multicluster/primary-remote_multi-network/test.sh also fails with the same message.

Trying to move the istio.io tests from the release-1.8 branch to main and the test now fails. The tail end of the log (https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio.io/8562/doc.test.multicluster_istio.io/1334602913783222272/artifacts/tests-setup-multicluster-42277d/TestDocs/setup/install/multicluster/primary-remote/test.sh/test.sh/_test_context/test.sh_output.txt):

```
Installing Istio on Primary cluster: kind-doc-cluster1
This will install the Istio 1.9.0 default profile with ["Istio core" "Istiod" "Ingress gateways"] components into the cluster. Proceed? (y/N) 
- Processing resources for Istio core.
✔ Istio core installed
- Processing resources for Istiod.
- Processing resources for Istiod. Waiting for Deployment/istio-system/istiod
✔ Istiod installed
- Processing resources for Ingress gateways.
- Processing resources for Ingress gateways. Waiting for Deployment/istio-system/istio-ingressgat...
✔ Ingress gateways installed
- Pruning removed resources
✔ Installation completeCreating the east-west gateway

- Processing resources for Istio core.
✔ Istio core installed
- Processing resources for Istiod.
- Processing resources for Istiod. Waiting for Deployment/istio-system/istiod
✔ Istiod installed
- Processing resources for Ingress gateways.
- Processing resources for Ingress gateways. Waiting for Deployment/istio-system/istio-ingressgat...
✔ Ingress gateways installed
- Pruning removed resources
✔ Installation completeWaiting for the east-west gateway to have an external IP
VERIFY FAILED snip_install_the_eastwest_gateway_in_cluster1_2 (timeout after 120s):
received:
"Error from server (NotFound): services "istio-eastwestgateway" not found"
expected:
"NAME                    TYPE           CLUSTER-IP    EXTERNAL-IP    PORT(S)   AGE
istio-eastwestgateway   LoadBalancer   10.80.6.124   34.75.71.237   ...       51s"
```

**Expected behavior**

**Steps to reproduce the bug**
Run the istio.io test or try and follow the instructions on the content/en/docs/setup/install/multicluster/pimary-remote/index.md page.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

`main` branch

**How was Istio installed?**

via test framework

**Environment where the bug was observed (cloud vendor, OS, etc)**

pipeline 

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by linsun** [comment]
@nmittler @stevenctl could one of you look at this?  This is preventing us from testing istio.io on master.

**Comment by nmittler** [comment]
@linsun I am able to reproduce with [this script](https://gist.github.com/nmittler/420f0d5cbf043aa603d31f8ef2109e0f) (basically a copy & paste of the snippets from istio.io.

One thing I noticed was that the discovery address in the sidecar is `istiod.istio-system` rather than `istiod-remote.istio-system`. Is it possible that some of the central istiod work has broken this?

**Comment by nmittler** [comment]
I also see a lot of recent activity to https://github.com/istio/istio/commits/master/manifests/charts/istiod-remote

@linsun re-assigning to you since I believe this is related to recent work related to istiod-less remotes.

**Comment by linsun** [comment]
Thanks @nmittler for the investigation!  It looks like we never updated the docs to be istiodless on the remote cluster.  I can take a stab at updating it.

I think the discovery addr is supposed to be istiod.istio-system as there is no other istiod on the remote cluster thus no need to use a different name like istiod-remote.istio-system

@irisdingbj pls correct me if I'm wrong here.

**Comment by nmittler** [comment]
@linsun ok sounds good. One concern I have is that if we're making the leap to istiod-less, we need to make sure that we're not breaking upgrade. Have you tested upgrade of remotes from legacy to istiod-less?

**Comment by ericvn** [comment]
Update. A change was merged, https://github.com/istio/istio/pull/30377 and it's cherry-pick, which allows the install to happen in both the PrimaryRemote and PrimaryRemote-MultiNetwork tests, but they are now failing when trying to verify cross cluster traffic.

An example failure is here: https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio.io/8854/doc.test.multicluster_istio.io/1354427767550119936

The failure is now:
```
Verifying load balancing from kind-doc-cluster2
VERIFY FAILED snip_verifying_crosscluster_traffic_3 (timeout after 120s):
received:
"Hello version: v2, instance: helloworld-v2-7855866d4f-qnplj"
expected:
"Hello version: v1, instance:"
```

It seems no traffic is flowing from cluster 2 to cluster 1.

**Comment by stevenctl** [comment]
@nmittler sounds like the pods in cluster 2 are using cluster 2's control plane

**Comment by nmittler** [comment]
@linsun this is an actual bug and a regression for multi-cluster. I don't have the feeling that istiod-less remotes are in a state where they're ready to be made a default. For example, I'm not sure we've thought through the upgrade story. For 1.9, I think the safe move is to go back to the legacy istiod-based remotes by default. This includes reverting our tests as well.

This seems like a release blocker to me. Can you take a look?

FYI @smawson @stevenctl @duderino @ericvn

**Comment by ericvn** [comment]
I had previously marked this as a release-blocker.

**Comment by linsun** [comment]
@nmittler @stevenctl if you look at our current docs in 1.9, last change is 3 months ago by @nmittler, and we are still using the remote profile (which is same as default profile right now with pilot enabled).  So we are not running with no istiod in istiod-remote in our docs testing.  remote cluster has its own istiod, and it is using primary cluster's istiod for xds only but nothing else.  Does this match your understanding of how it works for 1.9?

**Comment by nmittler** [comment]
@linsun Yes, there is an istiod in the cluster, however istio.io tests fail due to the fact that installation appears to be using the remote's istiod for discovery. In other words, the installation is broken for remote clusters in 1.9. The problem isn't the docs, it's the installation itself. The reason it wasn't discovered by integration tests was that we moved all of the integ tests over to using istiod-less remotes in anticipation that istiod-less remotes would be beta for 1.9. That didn't happen, however, so we now need to revert that.

**Comment by ericvn** [comment]
I ran the istio.io tests against the 1.9 branch commit which contains the cherry pick for `fix discoveryAddress in configmap template` (https://github.com/istio/istio/pull/30524). The multicluster tests did pass.
