### ISSUE TITLE
Need e2e test for helm install of istio

### ISSUE THREAD

**Issue by linsun** [istio/istio#2939]
The latest helm broken in master triggers this issue to be high priority else we don't have a helm install for istio working consistently.

**Comment by linsun** [comment]
cc @costinm @sdake @lachie83 @luisyonaldo

**Comment by sdake** [comment]
completely agree.  Garbage in garbage out - need a gate :)  I can take this on if you like - although my preference would be to add a new pilot e2e test based upon helm in the short term as to not damage other work while we sort out the helm charts.  Then integrate as @costinm has suggested in other PRs/issue trackers.

Cheers
-steve

**Comment by linsun** [comment]
I'm looking into this as we speak.   I'd prefer to use circle CI tests as they run faster and helm works with minikube.  People will appreciate us not add additional tests for helm install as it increases PR testing time, but for the short term, I'm good with adding tests for helm and once it is stable and required, we can merge it in one of the existing e2e test.

**Comment by costinm** [comment]
I would suggest using 'helm template' and replacing the istio.yaml - it is also fine to run one of the integration tests with helm template and one with real helm. But I believe the deployment should
be mostly identical if using helm template or helm (at least of our configs)

**Comment by ldemailly** [comment]
cc @nmittler re test grand unifications

the same test (like e2e simple) should be runnable with both isio-auth.yaml based and helm based install (in parallel builds)

**Comment by sakshigoel12** [comment]
@costinm can you assign this issue if we still think it is a P0

**Comment by linsun** [comment]
https://github.com/istio/istio/pull/5114

**Comment by linsun** [comment]
A basic e-2-e is in place.  Will open other issues for other helm e-2-e.
