### ISSUE TITLE
Option to configure JWKs public key refresh interval

### ISSUE THREAD

**Issue by Morriz** [istio/istio#29408]
**Describe the feature request**

Reviving this one that got closed by a bot because nobody attended to it:

https://github.com/istio/istio/issues/23409

**Comment by Morriz** [comment]
Can we at least get a pointer to deleting that cache?

**Comment by yangminzhu** [comment]
It's istiod to fetch and cache the jwks public key so restarting the istiod should be good enough to delete the cache.

@xulingqing, I think we could first verify the the istiod will always the jwks when restarted, and then you can also investigate 1) make the refresh interval configurable (probably as an environmental variable in istiod) and/or 2) add a debug endpoint (e.g. http://127.0.0.1/debugz/clearJwksCache) in istiod to allow deleting the cache without restarting istiod.
