### ISSUE TITLE
Potential wrong cluster instances when pod occur later than endpoint

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#29405]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

There are cases that istio list-watches endpoint ealier than pod. In order to resolve some issues, we have introduced resync mechanism #25161
However, it only resolves eds issues.  

In istio we also get pod in `InstancesByPort`, this is a very important method. I have a draft for the calling stack. https://docs.google.com/document/d/1OdHBI7oOpfEj1iNzj2v1tNMMqNrJGrHOklcW0enBwLc/edit?usp=sharing

IIUC, in this case, it will influence cds correctnessss, because cds relys on TlsMode/WorkLoadName/ServiceAccount.

**Comment by ramaraochavali** [comment]
> Potential wrong cluster instances

Can you give example of what wrong cluster instances are created when this happens?

**Comment by hzxuzhonghu** [comment]
Take tlsmode as an example, when we use the wrong one. 

When building cluster buildOutboundClusters->applyDestinationRule->BestEffortInferServiceMTLSMode, we will get the wrong tlsmode, and then will set the wrong tlscontext.
