### ISSUE TITLE
Resources created by the operator lack owner references

### ISSUE THREAD

**Issue by pbecotte** [istio/istio#29430]
**Bug description**

We recently upgraded istio. We deploy our system by way of the istio operator controlled by argocd. Argocd creates the `istiooperator` resource, and the istio operator creates everything else. Since we upgraded, our production cluster could no longer show the child resources in argocd, while our nonprd one still did. We tracked it down to the nonprd cluster having ownerReferences on the top level objects, while in prd they do not. This happened because the prd one we tried a full delete to cycle all the pods, while in nonprd the references remained from an older version of istio operator (deleting an object in nonprd leads to the operator bringing it back, but without the references.)

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
We would expect objects created by the operator to have valid references back to the `istiooperator` resource

**Steps to reproduce the bug**
Launch istio using the oprator and an istiooperator resource

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
$ istioctl version --remote
client version: 1.6.2
control plane version: 1.7.3
data plane version: 1.7.3 (55 proxies), 1.6.2 (19 proxies)

$ k version --short
Client Version: v1.17.0
Server Version: v1.16.15-eks-ad4801

**How was Istio installed?**
operator and `istiooperator` resource installed by argocd

**Environment where the bug was observed (cloud vendor, OS, etc)**
AWS EKS

**Comment by morvencao** [comment]
We now track the owner of istio resources by the labels and annotations instead of owner reference.
