### ISSUE TITLE
jwks cache related errors should result in refetch of jwks_uri

### ISSUE THREAD

**Issue by Morriz** [istio/istio#29436]
**Describe the feature request**

It would be nice if istio would refetch jwks data upon jwks cache related errors, as it might have stale data.
( We now get `Jwks doesn't have key to match kid or alg from Jwt` errors after we redeploy keykloak with a fresh db)

NOTE: There seems to be a hardcoded 20 minutes TTL on the jwks gotten from the jwks_uri (see #27097)

In the mean time it would be nice to be pointed to a workaround as to how to kill that cache manually. It seems to extend it's ttl upon requesting the invalid route, making it even worse. (It seems one has to wait exactly 20 minutes while hoping no request hits that route, in order for the 20 minutes to fully pass.)

[x] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by yangminzhu** [comment]
I think a quick workaround is to restart istiod, that should force it to fetch the jwks and then push to proxies.

**Comment by Morriz** [comment]
Is that a fact? I did not yet notice that. I thought I would have noticed that since I restart istiod a lot

**Comment by yangminzhu** [comment]
related to https://github.com/istio/istio/issues/29408, cc @xulingqing

**Comment by smwyzi** [comment]
can i submit a pr to support configure the refresh period from env?

**Comment by maennchen** [comment]
:+1: We're using an IAM that rotates the keys relatively quickly. Therefore this issue makes jwt checks unusable for us.

I believe that a configurable interval is not enough to solve the problem and the keys should be refreshed when a new `kid` is encountered.

https://openid.net/specs/openid-connect-core-1_0.html#RotateSigKeys:

**Comment by fforootd** [comment]
Well normally it is recommended to use a `scheduler` to read the `JWKS` endpoint at a certain interval AND if a `JWT` token contains unknown `kid` to reread `JWKS` 😁

**Comment by yinzara** [comment]
I believe this is still a valid issue and would like to discuss reopening this.  I agree with @fforootd and @maennchen , there should be the ability to cause refetching of the JWKS if the kid of a known issuer isn't found.

We have a serious problem with our transient branch environments that get their data cleared often and this makes istio token validation completely useless in those environment.

**Comment by ScottWares** [comment]
I also support re-opening the discussion around this problem. We currently are encountering the same issue where ingress traffic occasionally encounters the `Jwks doesn't have key to match kid or alg from Jwt` error and we have to manually reboot the `istiod` pod to rectify
