### ISSUE TITLE
Status field: when analysis is enabled it doesn't add the error severity (warning, error...)

### ISSUE THREAD

**Issue by xeviknal** [istio/istio#29445]
**Bug description**

When the status field is enabled,
And the Analysis is enabled,
And the message `IST0130` appears,
Then it doesn't have the level (severity) attached in the message.

I haven't tried other messages besides the `IST0130`.

```
$ k get virtualservices.networking.istio.io details -o yaml | tail -13
        subset: v1
status:
  conditions:
  - lastProbeTime: "2020-12-07T11:59:24.951939379Z"
    lastTransitionTime: "2020-12-07T11:59:24.951940058Z"
    message: 44/44 proxies up to date.
    status: "True"
    type: Reconciled
  observedGeneration: "3"
  validationMessages:
  - documentation_url: https://istio.io/v1.8/docs/reference/config/analysis/ist0130/?ref=status-controller
    type:
      code: IST0130
```

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

Each message in the `validationMessages` should have the severity (level) included.

**Steps to reproduce the bug**

```
istioctl install --set profile=demo --set values.pilot.env.PILOT_ENABLE_STATUS=true --set values.global.istiod.enableAnalysis=true

k apply -f samples/bookinfo/platform/kube/bookinfo.yaml 

k apply -f samples/bookinfo/networking/fault-injection-details-v1.yaml

k edit virtualservices.networking.istio.io details 
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```
$ istioctl version --remote
client version: 1.8.0
control plane version: 1.8.0
data plane version: 1.8.0 (11 proxies)

$ kubectl version --short
Client Version: v1.18.3
Server Version: v1.18.3
```

**How was Istio installed?**
```
istioctl install --set profile=demo --set values.pilot.env.PILOT_ENABLE_STATUS=true --set values.global.istiod.enableAnalysis=true
```

**Environment where the bug was observed (cloud vendor, OS, etc)**
```
$ minikube version
minikube version: v1.11.0
commit: 57e2f55f47effe9ce396cea42a1e0eb4f611ebbd
```

**Comment by esnible** [comment]
@therealmitchconnors Can you triage?
