### ISSUE TITLE
multicluster test setup failure: "unknown cluster"

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#29458]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/29426/integ-pilot-multicluster-tests_istio/1336045214938173440

**Comment by howardjohn** [comment]
Oh the logs are confusing due to parallelism, the real error seems more like:
```
ERROR: failed to create cluster: could not locate any control plane nodes
```

**Comment by howardjohn** [comment]
seems everything is just timing out

**Comment by ericvn** [comment]
@howardjohn Is this still an issue or can it be closed?

**Comment by howardjohn** [comment]
I think its resolved now
