### ISSUE TITLE
Istio Uninstall -- Frozen Terminating Resource

### ISSUE THREAD

**Issue by snowneji** [istio/istio#29451]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
I was trying to uninstall and reinstall Istio following the steps:
![image](https://user-images.githubusercontent.com/10824322/101385666-b85d7000-3881-11eb-932f-da65955eb0dd.png)

But I made a mistake that I deleted the namespace before deleting the istio-control-plane: `kubectl delete istiooperator istio-control-plane -n istio-system`, which then caused the deletion of  `istio-control-plane` to be hanging. 

I tried to remove the finalizer using the following steps but it said `Error from server (NotFound): istiooperators.install.istio.io "istio-control-plane" not found`
```
kubectl get istiooperator -n istio-system -o json > output.json
nano output.json # and remove finalizer
kubectl replace --raw "/apis/install.istio.io/v1alpha1/namespaces/istio-system/istiooperators/istio-control-plane/finalize" -f output.json # error happend at this line
```
Any ideas on how can I uninstall `istio-control-plane` manually?

[ ] Docs
[ x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
Istio version: 1.6.13
K8s version:
    Client Version: v1.19.4
    Server Version: v1.17.11

**How was Istio installed?**
https://docs.microsoft.com/en-us/azure/aks/servicemesh-istio-install?pivots=client-operating-system-macos
**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by morvencao** [comment]
@snowneji Looks like the istiooperator CR has been removed, can you check if there are any istio components leaked in the cluster by the following command:
```
kubectl get all -n istio-system
```

If there are some istio components resources are leaked in the cluster, you can forcely delete these resources with. istioctl
```
istioctl anifest generate -f <original_istiooperator_yaml> | kubectl delete -f -
```

**Comment by snowneji** [comment]
Thank you, it was fixed!
