### ISSUE TITLE
Issues with ObjectSelector default enablement (29174)

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#29453]
The change doesn't apply to istioctl/operator since its not in manifests/profiles/default.yaml

cc @ostromart @sdake @jacob-delgado  @nrjpoddar  can we either remove the profile default.yaml or find a way to ensure its in sync? I don't feel comfortable with users on helm when we may have a things fall out of sync without us knowing

**Comment by morvencao** [comment]
We should remove the additional flags for `ObjectSelector` in the default profile if we want the enable it in the default profile at least.

**Comment by howardjohn** [comment]
https://github.com/istio/istio/pull/29476
