### ISSUE TITLE
Multi-Mesh VM Expansion Failure for ingress gateway in Istio 1.8

### ISSUE THREAD

**Issue by eam-cs** [istio/istio#29462]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
When following the instructions for mesh expansion in multi-network meshes, installation fails for ingress gateway. Problem only happens when enabling mesh expansion following steps described here https://istio.io/latest/docs/examples/virtual-machines/multi-network/#installing-the-istio-control-plane. 

Issue output:
"**Ingress gateway encountered an error: failed to create “service/istio-system/istio-ingressgateway”: Service “istio-ingressgateway” is invalid**"

[x] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Enabling mesh expansion should not cause ingress gateway installation to fail. 

**Steps to reproduce the bug**
This issue happens when following the instructions as follows:
A. Install istio then enable Mesh expansion feature 
1. Install istio with istioctl command as described in https://istio.io/latest/docs/setup/install/virtual-machine/#install-the-istio-control-plane
2. apply mesh expansion update "istioctl install -f ./vmintegration.yaml" as described in step 2 here https://istio.io/latest/docs/examples/virtual-machines/multi-network/#installing-the-istio-control-plane

B. Install istio with mesh expansion feature enabled 
1. Here just do step  "istioctl install -f ./vmintegration.yaml" , so istio control plane gets installed with mesh expansion feature enabled. 
**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
Istio version 1.8

**How was Istio installed?**
Using istioctl command line 
**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by rinormaloku** [comment]
Hi @eam-cs 

Is this issue the same as: 
https://github.com/istio/istio.io/issues/8602?

**Comment by eam-cs** [comment]
Hi @rinormaloku yes, it seems to be the same issue.
