### ISSUE TITLE
Remote pilot address is bind to port 15012 (for xDs). It would be great if we can override this port, making it able to support NodePort for remode istiod.

### ISSUE THREAD

**Issue by 12beseuahmad** [istio/istio#29482]
**Describe the feature request**
I am following this guide for primary remote on different network.

https://istio.io/latest/docs/setup/install/multicluster/primary-remote_multi-network/

Instead of using the load balancer on primary to expose the istiod, I am trying to use NodePort. Also verified it using netcat and it works. Now on remote machine when I configure using IstioOperator there is an option for remotePilotAddress but no option for the port i.e it get binded to default 15012.

**Describe alternatives you've considered**

[ ] Docs
[x] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by wojtek-viirtue** [comment]
Looks like this is also related to: https://github.com/istio/istio/issues/17801

**Comment by stevenctl** [comment]
not stale
