### ISSUE TITLE
Documentation for Multi-Network Service Mesh not clear enough 

### ISSUE THREAD

**Issue by eam-cs** [istio/istio#29499]
**Describe the feature request**
I find some parts of the documentation for K8s->VM connectivity - service mesh expansion to be kind of confusing, specially where it talks about the files that will be transferred to the VM as described here https://istio.io/latest/docs/setup/install/virtual-machine/#create-files-to-transfer-to-the-virtual-machine. The document focuses on showing commands to run and deployments to do but does not give much information about why we need those steps, and in some cases, i.e, when running the command, such as <istioctl x workload entry configure -f workloadgroup.yaml -o "${WORK_DIR}"> it gives a list of files that this command would generate and high level description of this files, but if the command fails, it is hard to manually create those files if no examples are provided. For scripts, such as  https://raw.githubusercontent.com/istio/istio/release-1.8/samples/multicluster/gen-eastwest-gateway.sh it is difficult to understand if this script should always be run, and why we need it, if for istio 1.6 it was not there. 

**Describe alternatives you've considered**

[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by stevenctl** [comment]
Sounds like this is more the VM docs than the multi-network docs. There is an outstanding task to update the multi-network VM docs here: https://github.com/istio/istio.io/issues/8602. 

1. It is unclear what exactly VM config files do, and how I would configure them by hand. 

This is something we can definitely do better. These aren't technically a stable "API" but we should document the different configuration knobs in detail somewhere. 

2. What exactly does `gen-eastwest-gateway` do and when should I run it? 

@nmittler, perhaps we need a central doc that explains what the east-west gateway is for, and the install steps. Then we reference it from our multi-cluster/multi-network. 

@eam-cs just FYI, this script is just a way to install a secondary gateway, similar to the ingress gateway, but specifically for east-west traffic. More info here: https://istio.io/latest/docs/setup/install/multicluster/multi-primary_multi-network/#install-the-east-west-gateway-in-cluster1

**Comment by nmittler** [comment]
@stevenctl 

> @nmittler, perhaps we need a central doc that explains what the east-west gateway is for, and the install steps. Then we reference it from our multi-cluster/multi-network.

Yeah good idea. I've raised https://github.com/istio/istio.io/issues/8651

**Comment by eam-cs** [comment]
@stevenctl thank you for the prompt response. The command "samples/multicluster/gen-eastwest-gateway.sh --single-cluster | istioctl install -y -f - " does not create a secondary gateway, the script is omitted. The following is not created as described in the document.   
                                                                                         
"NAME                                 TYPE           CLUSTER-IP    EXTERNAL-IP    PORT(S)   AGE
istio-eastwestgateway   LoadBalancer   10.80.6.124   34.75.71.237   ...       51s

Is there another way to run this script?

**Comment by stevenctl** [comment]
https://www.github.com/istio/istio/tree/master/samples%2Fmulticluster%2Fgen-eastwest-gateway.sh

Really what this script does is template out a IstioOperator yaml that istioctl will use to generate the deployment, service, etc. The important parts are:

- name: using a specific name in the operator resource will prevent your primary installation from being reconciled with this IstioOperator
- profile: empty disables the non gateway components
- REQUESTED_NETWORK_VIEW makes the gateway act as an ingress only to the network it resides in, rather than ingress for the whole mesh. This prevents extra hops in cross network load balancing.
- the required ports to expose istiod and services via the gateway
- router mode to allow SNI based routing 
- `topology.istio.io/network` on the Service tells istiod to use this gateway for traffic coming into this network

**Comment by eam-cs** [comment]
Thank you @stevenctl for the explanation. Going back to the documentation, enabling mesh expansion as described in the guide https://istio.io/latest/docs/examples/virtual-machines/multi-network/#installing-the-istio-control-plane runs into the problem mentioned here https://github.com/istio/istio.io/issues/8602. During installation, I get this message "values.global.meshExpansion.enabled is deprecated; use Gateway and other Istio networking resources, such as in samples/istiod-gateway/ instead". Is this step supposed to be done at all?

**Comment by sidheshdivekar29** [comment]
I am following this tutorial but running into issues.
https://istio.io/latest/docs/setup/install/virtual-machine/#install-the-istio-control-plane 
The script errors out but ingress is created. However the pod never comes up due to readiness check failing.

```
samples/multicluster/gen-eastwest-gateway.sh --single-cluster | istioctl install -y -f -
✘ Ingress gateways encountered an error: failed to wait for resource: resources not ready after 5m0s: timed out waiting for the condition
Deployment/istio-system/istio-eastwestgateway
- Pruning removed resources                                                                      Error: failed to install manifests: errors occurred during operation
```
Below are the events from istio-system namespace.

```
18m         Warning   Unhealthy                 pod/istio-eastwestgateway-59cc6fcdb6-fqjcp      Readiness probe failed: Get http://10.60.2.12:15021/healthz/ready: dial tcp 10.60.2.12:15021: connect: connection refused
3m34s       Warning   Unhealthy                 pod/istio-eastwestgateway-59cc6fcdb6-fqjcp      Readiness probe failed: HTTP probe failed with statuscode: 503
19m         Warning   Unhealthy                 pod/istio-eastwestgateway-59cc6fcdb6-spqv9      Readiness probe failed: HTTP probe failed with statuscode: 503
18m         Normal    SuccessfulCreate          replicaset/istio-eastwestgateway-59cc6fcdb6     Created pod: istio-eastwestgateway-59cc6fcdb6-fqjcp
16s         Normal    EnsuringLoadBalancer      service/istio-eastwestgateway                   Ensuring load balancer
3m56s       Warning   FailedGetResourceMetric   horizontalpodautoscaler/istio-eastwestgateway   did not receive metrics for any ready pods
11s         Normal    EnsuredLoadBalancer       service/istio-eastwestgateway                   Ensured load balancer


0s          Warning   FailedGetResourceMetric   horizontalpodautoscaler/istio-eastwestgateway   did not receive metrics for any ready pods
0s          Warning   Unhealthy                 pod/istio-eastwestgateway-59cc6fcdb6-fqjcp      Readiness probe failed: HTTP probe failed with statuscode: 503
```

I noticed that due to this the vm is also unable to connect to istiod.

Logs from vm.

```
2021-01-06T21:09:01.889740Z	info	xdsproxy	Envoy ADS stream established
2021-01-06T21:09:01.889849Z	info	xdsproxy	connecting to upstream XDS server: istiod.istio-system.svc:15012
2021-01-06T21:09:21.890227Z	error	xdsproxy	failed to create upstream grpc client: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 34.82.124.54:15012: i/o timeout"


```

Please let me know how to proceed.

**Comment by stevenctl** [comment]
@eam-cs that guide needs to be updated... to workaround, you can follow the single-network VM guide. Before running `workload entry configure`, edit your `workloadgroup.yaml` and set `network: your-network` under the `template` field.  

@sidheshdivekar29 you'll need to look at your logs for the eastwest gateway Pod. If you're using revision-based installation, make sure to pass `--revision your-rev-name` to the `gen-eastwest-gateway.sh` script.

**Comment by sidheshdivekar29** [comment]
@stevenctl Can you please explain what do you mean by revision-based installation ? Am installing for the first time on fresh cluster and using istio-1.8.1.  If I follow https://istio.io/latest/docs/setup/install/virtual-machine/#install-the-istio-control-plane then istiod, eastwest and ingress are coming up fine. As soon as I apply steps from https://istio.io/latest/docs/examples/virtual-machines/multi-network/#installing-the-istio-control-plane eastwest gets terminated.

**Comment by stevenctl** [comment]
@sidheshdivekar29 that doc is out of date. You can try the WIP new doc here: https://deploy-preview-8746--preliminary-istio.netlify.app/latest/docs/examples/virtual-machines/multi-network/

The way it's currently written, start with the linked doc which tells you to modify some steps from the install doc. This will likely be updated in the final version.

**Comment by sidheshdivekar29** [comment]
@stevenctl It doesn't say anything about 
```
Expose the control plane using the provided sample configuration:
"kubectl apply -f samples/multicluster/expose-istiod.yaml"
```

Do we still have to do that step as 4th step ?

**Comment by stevenctl** [comment]
Yes. The final version will include these details in the main VM install doc, the multi-network doc may either go away, or just be for verification steps.

**Comment by sidheshdivekar29** [comment]
@stevenctl There is no such file "https://storage.googleapis.com/istio-release/releases/1.9.0/deb/istio-sidecar.deb". I will download one from 1.8.0.

**Comment by sidheshdivekar29** [comment]
@stevenctl Looks like vm is unable to authenticate itself to istiod.

This is the error on istiod.

```
2021-01-08T08:58:51.666764Z	error	ads	Failed to authenticate client from 10.36.0.12:56220
Authenticator ClientCertAuthenticator: no verified chain is found
; Authenticator KubeJWTAuthenticator: could not get cluster Kubernetes's kube client
```

This is the error on vm.

```
2021-01-08T09:00:19.201432Z	info	xdsproxy	disconnected from XDS server: istiod.istio-system.svc:15012
2021-01-08T09:00:32.534577Z	info	xdsproxy	Envoy ADS stream established
2021-01-08T09:00:32.534690Z	info	xdsproxy	connecting to upstream XDS server: istiod.istio-system.svc:15012
2021-01-08T09:00:32.779253Z	warn	xdsproxy	upstream terminated with unexpected error rpc error: code = Unknown desc = authentication failure
2021-01-08T09:00:32.779466Z	info	xdsproxy	disconnected from XDS server: istiod.istio-system.svc:15012


```

Is there any step missing in the doc ?

**Comment by stevenctl** [comment]
@sidheshdivekar29, did you follow this warning:

> When connecting a VM to a multicluster Istio mesh, you will need to add the --clusterID argument to the above command. Set the value to the name of the cluster corresponding to the istioctl context.

In my doc PR, I changed changed the main virtual machine install doc to include a `CLUSTER` environment variable, and the `--clusterID` flag in the command examples. All the multi-network steps have been moved in the main install doc. 

You can view a version of the doc site by looking at the "Netlify deploy" job in the PR: https://github.com/istio/istio.io/pull/8746

**Comment by sidheshdivekar29** [comment]
@stevenctl What is CTX_CLUSTER1 below ?

Is it the output of kubectl config current-context ?

```
$ kubectl --context="${CTX_CLUSTER1}" apply -n istio-system -f \
samples/multicluster/expose-services.yaml
```

**Comment by sidheshdivekar29** [comment]
Also on the vm I notice that there is private IP instead of eastwest gateway.

```
curl -v localhost:15000/clusters | grep helloworld
outbound|5000||helloworld.default.svc.cluster.local::10.120.0.8:5000::health_flags::healthy
outbound|5000||helloworld.default.svc.cluster.local::10.120.0.8:5000::weight::1
outbound|5000||helloworld.default.svc.cluster.local::10.120.0.8:5000::region::us-central1
outbound|5000||helloworld.default.svc.cluster.local::10.120.0.8:5000::zone::us-central1-c
outbound|5000||helloworld.default.svc.cluster.local::10.120.0.8:5000::sub_zone::
outbound|5000||helloworld.default.svc.cluster.local::10.120.0.8:5000::canary::false
outbound|5000||helloworld.default.svc.cluster.local::10.120.0.8:5000::priority::0
outbound|5000||helloworld.default.svc.cluster.local::10.120.0.8:5000::success_rate::-1.0
outbound|5000||helloworld.default.svc.cluster.local::10.120.0.8:5000::local_origin_success_rate::-1.0
```

**Comment by stevenctl** [comment]
The latest version now differentiates the VM and Cluster networks.

**Comment by eam-cs** [comment]
Hi @stevenctl I have now followed the [prelim 1.9](https://deploy-preview-8746--preliminary-istio.netlify.app/latest/docs/setup/install/virtual-machine) document you have shared and one of the issues I run into is the east-west gateway fails to get created with error shown below 
<img width="1675" alt="Screen Shot 2021-01-14 at 7 40 36 AM" src="https://user-images.githubusercontent.com/64979576/104613527-2d1f8900-563c-11eb-9757-90b57ec40d57.png">
<img width="1644" alt="Screen Shot 2021-01-08 at 3 25 17 PM" src="https://user-images.githubusercontent.com/64979576/104613536-2ee94c80-563c-11eb-86d5-94b989698229.png">
<img width="774" alt="delete-istio-rules" src="https://user-images.githubusercontent.com/64979576/104613538-2f81e300-563c-11eb-9da8-ac4d5b6b2af7.png">
<img width="1675" alt="Screen Shot 2021-01-14 at 7 40 36 AM" src="https://user-images.githubusercontent.com/64979576/104613576-390b4b00-563c-11eb-9e51-a15793d713fa.png">

**Comment by eam-cs** [comment]
@stevenctl I have followed the [prelim 1.9 installation guide](https://deploy-preview-8746--preliminary-istio.netlify.app/latest/docs/setup/install/virtual-machine) but run into the same issues as @sidheshdivekar29 where there is a failure to create east-west gateway. I'm installing istio 1.8.1. I have uninstalled previous istio version and doing everything from scratch. Any advice on how to proceed? @sidheshdivekar29 were you able to solve this issue? 
<img width="1675" alt="Screen Shot 2021-01-14 at 7 40 36 AM" src="https://user-images.githubusercontent.com/64979576/104623357-24808000-5647-11eb-8f80-cf55d3fe8839.png">

**Comment by stevenctl** [comment]
@eam-cs, I've just tested the steps against 1.8.0 and 1.8.1 and they seem to work. Can you get logs from the failed istio-eastwestgateway pods? 

The docs also use `$CLUSTER_NETWORK` instead of `$NETWORK`. If you can help test the final version of these docs, that would be great: 
https://preliminary.istio.io/latest/docs/setup/install/virtual-machine

**Comment by eam-cs** [comment]
Thank you @stevenctl, I will make the changes and test the final version !

**Comment by eam-cs** [comment]
Hi @stevenctl, sorry I did not followed up on this thread. I got pulled into other tasks and lost track of this test. I'm revisiting this task with istio 1.9.1. For the multi-network case,  I see the following ENV variables must be set up: 
$ CLUSTER_NETWORK="kube-network"
$ VM_NETWORK="vm-network"
$ CLUSTER="cluster1"

I've provided the name of the cluster as it appears in the kubeconfig
<img width="1231" alt="Screen Shot 2021-03-05 at 3 08 08 PM" src="https://user-images.githubusercontent.com/64979576/110842886-867eef80-825c-11eb-81c4-ae81d8ae310b.png">
<img width="1073" alt="Screen Shot 2021-03-09 at 1 00 04 PM" src="https://user-images.githubusercontent.com/64979576/110842887-87178600-825c-11eb-9a93-680153f837ad.png">

 file, but this is giving issues with the certificates and also blocking new deployments, is a different name expected for CLUSTER?. Also, I'm not sure what is expected as a value for VM_NETWORK and CLUSTER_NE
<img width="1314" alt="Screen Shot 2021-03-05 at 2 31 32 PM" src="https://user-images.githubusercontent.com/64979576/110842875-82eb6880-825c-11eb-9ffa-83dda7445dd7.png">
TWORK. I have attached the screenshots of the issues I'm facing, any help would be appreciated.

**Comment by jflowgh** [comment]
Hi there, I'm on Istio 1-13-2 running through the multiprimary cluster setup on GKE K8s, and I'm getting the same error @[sidheshdivekar29](https://github.com/sidheshdivekar29) was reporting:

istiod logs:
```
2022-04-22T16:11:05.944685Z     warn    serverca        Authentication failed for 10.46.1.20:57450: Authenticator ClientCertAuthenticator at index 0 got error: no verified chain is found. Authenticator KubeJWTAuthenticator at index 1 got error: could not get cluster Kubernetes's kube client. 
```

gateway logs:
```
2022-04-22T16:14:11.512059Z     warn    sds     failed to warm certificate: failed to generate workload certificate: create certificate: rpc error: code = Unauthenticated desc = request authenticate failure

```

Sorry, I didn't see a clear resolution for this problem from the comments here. I'm using the IstioOperator to install. Any tips in the right direction would be appreciated. Thanks.
