### ISSUE TITLE
Potential memory leak on istio-proxy sidecar

### ISSUE THREAD

**Issue by ediezh** [istio/istio#29505]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

memory usage keeps growing on the istio-proxy sidecar
<img width="1492" alt="Screen Shot 2020-12-09 at 12 10 44 pm" src="https://user-images.githubusercontent.com/15918714/101563731-ebd50180-3a1d-11eb-8ec7-5851680c5fba.png">

[ ] Docs
[ ] Installation
[ ] Networking
[X ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**
The metrics are over a period of 7 days. The service is only nginx and the request rate is pretty low too. Here is a graph of the request counts.
<img width="1492" alt="Screen Shot 2020-12-09 at 12 11 50 pm" src="https://user-images.githubusercontent.com/15918714/101563851-25a60800-3a1e-11eb-991d-8313041a4b5e.png">

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
1.7

**How was Istio installed?**
istioctl

**Environment where the bug was observed (cloud vendor, OS, etc)**
EKS 1.6

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by bianpengyuan** [comment]
This does not seem to be a leak looking at the rapid increase of memory usage. Looks more like a more proxies are started. Is number of proxies running in your cluster stable?

**Comment by ediezh** [comment]
@bianpengyuan yes the number of proxies is stable. No changes recently. Also, this is the only proxy that has this problem.

**Comment by bianpengyuan** [comment]
Oh so this is the memory usage of one proxy? 300m is quite a lot. Could you dump the heap profile from it following https://github.com/istio/istio/wiki/Analyzing-Istio-Performance#profile. thanks!

**Comment by ediezh** [comment]
Hi @bianpengyuan here is the heap profile, it doesn't seem too big. I also realized the above graph is from the container_memory_usage_bytes, I did another one using container_memory_working_set_bytes. See below.

<img width="1370" alt="Screen Shot 2020-12-10 at 12 35 24 pm" src="https://user-images.githubusercontent.com/15918714/101710317-53a24f80-3ae5-11eb-93dc-9dde33017ae3.png">

[profile001.pdf](https://github.com/istio/istio/files/5669728/profile001.pdf)

**Comment by bianpengyuan** [comment]
There is probably metrics will unbounded metric labels. Could you check the prometheus stats dump (curl localhost:15000/stats/prometheus) and check whether there is large number of time series?

**Comment by ediezh** [comment]
Hi @bianpengyuan Thanks for the pointer, I figured out what the issue is.

For the istio-proxy, we added a custom tag `request_url`. Below is the configure in IstioOperator.
```
values:
    telemetry:
      v2:
        prometheus:
          configOverride:
            inboundSidecar:
              debug: false
              stat_prefix: istio
            outboundSidecar:
              debug: false
              stat_prefix: istio
              metrics:
                - dimensions:
                    request_url: "request.url_path"
            gateway:
              debug: false
              stat_prefix: istio
              disable_host_header_fallback: true
              metrics:
                - dimensions:
                    request_url: "request.url_path"
```
But I forgot to add the pod annotation `"sidecar.istio.io/extraStatTags":"request_url"`. That has resulted in a large number of time series like the one below.
```
envoy_request_url____api_v1_quicktome_studies_5f3820ab7f2791e7fb89faf7____istio_response_bytes_count{response_code="0",reporter="source",source_workload="surgery-app-server-proxy",source_workload_namespace="surgery-app-dev",source_principal="spiffe://cluster.local/ns/surgery-app-dev/sa/default",source_app="surgery-app-server-proxy",source_version="unknown",destination_workload="unknown",destination_workload_namespace="unknown",destination_principal="spiffe://cluster.local/ns/surgery-app-dev/sa/surgery-app-server",destination_app="unknown",destination_version="unknown",destination_service="surgery-app-server.surgery-app-dev.svc.cluster.local",destination_service_name="surgery-app-server.surgery-app-dev.svc.cluster.local",destination_service_namespace="unknown",request_protocol="http",response_flags="DC",grpc_response_status="",connection_security_policy="unknown",source_canonical_service="surgery-app-server-proxy",destination_canonical_service="unknown",source_canonical_revision="latest",destination_canonical_revision="latest"} 2

envoy_request_url____api_v1_quicktome_studies_5f3820ab7f2791e7fb89faf7____istio_request_duration_milliseconds_count{response_code="0",reporter="source",source_workload="surgery-app-server-proxy",source_workload_namespace="surgery-app-dev",source_principal="spiffe://cluster.local/ns/surgery-app-dev/sa/default",source_app="surgery-app-server-proxy",source_version="unknown",destination_workload="unknown",destination_workload_namespace="unknown",destination_principal="spiffe://cluster.local/ns/surgery-app-dev/sa/surgery-app-server",destination_app="unknown",destination_version="unknown",destination_service="surgery-app-server.surgery-app-dev.svc.cluster.local",destination_service_name="surgery-app-server.surgery-app-dev.svc.cluster.local",destination_service_namespace="unknown",request_protocol="http",response_flags="DC",grpc_response_status="",connection_security_policy="unknown",source_canonical_service="surgery-app-server-proxy",destination_canonical_service="unknown",source_canonical_revision="latest",destination_canonical_revision="latest"} 2
```
Since we don't really need the request_url tag on the sidecar time series, so I removed the telemetry configuration on the sidecar, and it has fixed the issue.

Thanks very much.
