### ISSUE TITLE
Istio Performance dashboard isn't useful for people with custom ingress gateways

### ISSUE THREAD

**Issue by Niksko** [istio/istio#29510]
**Describe the feature request**

The current Istio performance dashboard ((gnet link)[https://grafana.com/grafana/dashboards/11829]) doesn't really work for users that have custom ingress gateways. Many of the graphs use hardcoded Prometheus queries like `pod=~"istio-ingressgateway-.*"` or `source_workload="istio-ingressgateway"`. These don't work if you've disabled the default ingress gateway and are using custom ingress gateways.

Could we auto-populate a Grafana variable and use that to drive the pod and source workload regexes? Are there metrics that indicate the names of the ingress gateways?

**Describe alternatives you've considered**

We will likely clone the dashboard and add our own customizations to make it work with our ingress gateway setup. However this is additional burden on us, and we also have to reconcile changes between our dashboard and upstream on every new release.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by frittentheke** [comment]
@Niksko  I just ran into this very issue. Any chance you would revive this issue? I might then push a PR adding templating to select the Ingress Gateway instead of the current static string.

**Comment by frittentheke** [comment]
@howardjohn @hanxiaop would you have an opinion about adding templating to the performance dashboard to allow for multiple ingress gateways? I'd then very much like to push a PR adding this.

**Comment by howardjohn** [comment]
I don't think a hardcoded `istio-ingressgateway*` is a great way to determine, likely only covers a few cases of custom ones. Not sure a great way though...
