### ISSUE TITLE
Consolidate TCP client settings with global DestinationRule

### ISSUE THREAD

**Issue by GregHanson** [istio/istio#29525]
**Describe the feature request**

Istio 1.9 Work items for consolidating client settings.  Users or cluster admins will be able to create a global DestinationRule for global settings such as connection timeout.  Service specific DestinationRules will inherit the global settings if fields are not specified.  

HTTP related fields such as timeout and retries (currently located in VirtualService spec), will be covered in separate work item

- [ ] Implement merge behavior of global DestinationRule
- [ ] Provide example default global DR (matches current default of MeshConfig) in docs, not to be added to charts
- [ ] Tests to validate behaviors of merge of global dr, meshconfig and workload specific DR.
- [ ] Add warnings for the old config in MeshConfig for appropriate deprecation.

Related design doc: [here](https://docs.google.com/document/d/1hY-ShGY6sgwWUw0NGLvsDWXWm3wNLvhM4HHuRjFzRT0/edit#heading=h.xw1gqgyqs5b)

[ ] Docs
[ ] Installation
[ X ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ X ] User Experience
[ ] Developer Infrastructure

**Comment by esnible** [comment]
@GregHanson Can you report on status of this issue?
