### ISSUE TITLE
istioctl doesn't create the correct namespace for istio control plane

### ISSUE THREAD

**Issue by morvencao** [istio/istio#29523]
**Bug description**

currently istioctl will create the namespace of istio operator CR, but the istio control plane will may actually created in different namespace, for example:

```
# cat << EOF > iop.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: ns1
  name: example-istiocontrolplane
spec:
  profile: default
  namespace: istio-system
EOF
# out/linux_amd64/istioctl install -f iop.yaml
This will install the Istio default profile with ["Istio core" "Istiod" "Ingress gateways"] components into the cluster. Proceed? (y/N) y
Detected that your cluster does not support third party JWT authentication. Falling back to less secure first party JWT. See https://istio.io/v1.8/docs/ops/best-practices/security/#configure-third-party-service-account-tokens for details.
  Processing resources for Istio core.                                                                                                                                                                                                      2020-12-09T14:22:44.596260Z	error	installer	failed to create "ServiceAccount/istio-system/istio-reader-service-account": namespaces "istio-system" not found
2020-12-09T14:22:44.676108Z	error	installer	failed to create "ServiceAccount/istio-system/istiod-service-account": namespaces "istio-system" not found
- Processing resources for Istio core.                                                                                                                                                                                                      2020-12-09T14:22:44.981787Z	error	installer	failed to create "Role/istio-system/istiod-istio-system": namespaces "istio-system" not found
...
```

[ ] Docs
[ X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by shamsher31** [comment]
I saw this issue while debugging https://github.com/istio/istio/issues/29515 

My assumption was if I specify `metadata.namespace`, IstioOperator should automatically create a namespace for installation like it does for `istio-system` namespace,
