### ISSUE TITLE
Integration testing framework: ability to create custom clusters

### ISSUE THREAD

**Issue by ostromart** [istio/istio#29530]
Some tests like upgrade don't fit well into the framework, which generally assumes that the cluster is already created. One example of an existing test which could serve as a guide for extending the framework to support this is the [operator e2e test](https://github.com/istio/istio/tree/master/tests/integration/operator).
It could be a more convenient way of accommodating tests such as the operator test, which creates the cluster.

**Comment by howardjohn** [comment]
Why does the operator test need to create a cluster?
