### ISSUE TITLE
Istio ingress gateway error and high memory usage

### ISSUE THREAD

**Issue by ediezh** [istio/istio#29542]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

We started to get the below error on istio ingress gateway last night. It was intermittent at first, but then it become constant. The ingress gateway pod was in not ready status. 

```
2020-12-09T05:43:51.591523Z	warn	Envoy proxy is NOT ready: failed to get readiness stats: Get "http://127.0.0.1:15000/stats?usedonly&filter=^(server.state|listener_manager.workers_started)": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

The memory usage of the pod during that time was high. See the graph below. We had HPA enabled with minimum 2 replicas and maximum 5 replicas. So there were pods getting added and removed.

<img width="1367" alt="Screen Shot 2020-12-10 at 1 48 58 pm" src="https://user-images.githubusercontent.com/15918714/101714917-9b79a480-3aee-11eb-9c97-3e8ba7a3df81.png">

We don't have particularly high requests coming through, see the requests total metric below. 

<img width="1366" alt="Screen Shot 2020-12-10 at 1 51 18 pm" src="https://user-images.githubusercontent.com/15918714/101715051-dbd92280-3aee-11eb-90ee-179f13759fee.png">

I can't really correlate what could have caused it. Any tips would be welcome.

[ ] Docs
[ ] Installation
[ ] Networking
[X] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

ingress gateway function well.

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

1.7.0

**How was Istio installed?**

istioctl

**Environment where the bug was observed (cloud vendor, OS, etc)**

EKS 1.16.

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by anyyyy** [comment]
I have also encountered this situation. `Ingressgateway` and `egressgateway` have repeatedly failed probes and returned to normal. I hope to get help.
### Events
`
Events:
  Type     Reason     Age                 From             Message
  ----     ------     ----                ----             -------
  Warning  Unhealthy  14m (x868 over 8d)  kubelet, slave3  Readiness probe failed: Get http://10.244.3.7:15021/healthz/ready: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
`
### istio-proxy logs
`
warn    Envoy proxy is NOT ready: failed to get readiness stats: Get "http://127.0.0.1:15000/stats?usedonly&filter=^(server.state|listener_manager.workers_started)": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
info    Envoy proxy is ready
`

**Comment by style95** [comment]
Is there any progress on this?

**Comment by rakanay** [comment]
same issue i'm also facing in istio 1.14.5, ingressgw pods memory usage keep in increasing evenif istio_requests are normal.

**Comment by RyanRennCN** [comment]
Im encountering this same issue with 1.16.0. I can't find or correlate what is causing it.

**Comment by samuel-esp** [comment]
Take a look at this thread, the high memory usage could be caused by a wrong concurrency setting

#49945
