### ISSUE TITLE
istio vmintegration dns problem

### ISSUE THREAD

**Issue by ristokuu** [istio/istio#29555]
When I deploy istio vmintegration using this guide: https://istio.io/latest/docs/setup/install/virtual-machine/ to a vm that has preinstalled consul and dnsmasq the consul dns stops working, so I cannot use dns to resolve consul addresses. external dns works fine.

[ ] Docs
[x] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

consul local dns should work with istio installed

1. install consul and dnsmasq. point dnsmasq to resolve consul addresses from consul. dnsmasq listens to primary ip address of the vm.
2. install istio using the guide at  https://istio.io/latest/docs/setup/install/virtual-machine/

Version:
client version: 1.8.0
control plane version: 1.8.0
data plane version: 1.8.0 (51 proxies)
Client Version: v1.18.2
Server Version: v1.16.15-eks-ad4801

istio was installed with istioctl and additional guide https://istio.io/latest/docs/setup/install/virtual-machine/

AWS, Centos8

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by hzxuzhonghu** [comment]
Is the dns based on tcp? If so i think the dns query is intercepted by envoy.

**Comment by szibis** [comment]
I have the same issues udp also is intercepted.

```
-A OUTPUT -p udp -m udp --dport 53 -m owner --uid-owner 113 -j RETURN
-A OUTPUT -p udp -m udp --dport 53 -m owner --gid-owner 113 -j RETURN
-A OUTPUT -p udp -m udp --dport 53 -j DNAT --to-destination 127.0.0.1:15053
-A OUTPUT -p udp -m udp --dport 53 -m owner --uid-owner 113 -j RETURN
-A OUTPUT -p udp -m udp --dport 53 -m owner --gid-owner 113 -j RETURN
-A OUTPUT -p udp -m udp --dport 53 -j DNAT --to-destination 127.0.0.1:15053
-A OUTPUT -p udp -m udp --dport 53 -m owner --uid-owner 113 -j RETURN
-A OUTPUT -p udp -m udp --dport 53 -m owner --gid-owner 113 -j RETURN
-A OUTPUT -p udp -m udp --dport 53 -j DNAT --to-destination 127.0.0.1:15053
-A OUTPUT -p udp -m udp --dport 53 -m owner --uid-owner 113 -j RETURN
-A OUTPUT -p udp -m udp --dport 53 -m owner --gid-owner 113 -j RETURN
-A OUTPUT -p udp -m udp --dport 53 -j DNAT --to-destination 127.0.0.1:15053
-A OUTPUT -p udp -m udp --dport 53 -m owner --uid-owner 113 -j RETURN
-A OUTPUT -p udp -m udp --dport 53 -m owner --gid-owner 113 -j RETURN
-A OUTPUT -p udp -m udp --dport 53 -j DNAT --to-destination 127.0.0.1:15053
-A OUTPUT -p tcp -j ISTIO_OUTPUT
-A OUTPUT -p udp -m udp --dport 53 -m owner --uid-owner 113 -j RETURN
-A OUTPUT -p udp -m udp --dport 53 -m owner --gid-owner 113 -j RETURN
-A OUTPUT -p udp -m udp --dport 53 -j DNAT --to-destination 127.0.0.1:15053
```
And then not forwarding DNS to the VM resolver. Istio should only handle its own addresses and reset. should go to a local resolver.

**Comment by howardjohn** [comment]
This sounds a lot like https://github.com/istio/istio/issues/30309, it would be great if you could try out Istio 1.9 (following https://github.com/istio/istio/wiki/Dev%20Builds or waiting for 1.9.0)

**Comment by kyadav-cgi** [comment]
I am getting this error again in 1.23.5
