### ISSUE TITLE
Istio ingress gateway high CPU usage on VS/G update

### ISSUE THREAD

**Issue by jughead** [istio/istio#29558]
**Bug description**

I noticed on Istio 1.6.14 that if you create a VS with G having a lot of hosts (~2k) the CPU of the istio-ingressgateway pods starts to jump on changes from ~10 to ~600 millicores. The cluster has almost no traffic (it's a test one), the # of pods having istio-proxy is 9.

Previously using 1.6.2 on production it led to downtime when we were sequentially adding new hosts to the same VS and G. Although that seems to be fixed by https://github.com/istio/istio/pull/27269 the CPU usage is still high. 

[ ] Docs
[ ] Installation
[ ] Networking
[x] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

I am just interested if this CPU usage is expected, it seems to me too high. Or maybe there is a way to reconfigure the G or VS or anything in Istio to calm it down. 

**Steps to reproduce the bug**

1. Have a cluster with istio 1.6.14 installed
2. Deploy any service (let's call it `tech-radar`) to a default namespace, make sure the namespace has the istio injection label.
3. Run the following Ruby script having access to cluster `test_istio_ingress.rb` with `ruby test_istio_ingress.rb`
```ruby
# frozen_string_literal: true

require 'erb'
require 'faker'
require 'open3'

VS_TEMPLATE = <<~EOF
  apiVersion: networking.istio.io/v1beta1
  kind: VirtualService
  metadata:
    name: test-vs
    namespace: default
  spec:
    gateways:
      - default/test-gateway
    hosts:
      <%= hosts.map{|x| "- \#{x}"}.join("\n" + indent(2)) %>
    http:
      - match:
          - uri:
              prefix: /
        retries:
          attempts: 0
        route:
          - destination:
              host: tech-radar
              port:
                number: 80
        timeout: 30s
EOF

G_TEMPLATE = <<~EOF
  apiVersion: networking.istio.io/v1beta1
  kind: Gateway
  metadata:
    name: test-gateway
    namespace: default
  spec:
    selector:
      istio: ingressgateway
    servers:
      - hosts:
          <%= hosts.map{|x| "- \#{x}"}.join("\n" + indent(4)) %>
        port:
          name: http
          number: 80
          protocol: HTTP
EOF

def indent(n)
  '  ' * n
end

def generate_host
  Faker::Internet.domain_name
end

def generate_hosts(n)
  n.times.map { generate_host }
end

def update_vs_and_g(hosts)
  vs = ERB.new(VS_TEMPLATE).result(binding)
  g = ERB.new(G_TEMPLATE).result(binding)
  File.write('vs.yaml', vs)
  File.write('g.yaml', g)
end

def exec_command(cmd)
  o, e, s = Open3.capture3(cmd)
  $stdout.write o
  $stderr.write e
end

def apply
  exec_command 'kubectl apply -f vs.yaml'
  exec_command 'kubectl apply -f g.yaml'
end

hosts = generate_hosts(2000).uniq

def add_one(hosts)
  hosts << generate_host
  hosts.uniq!
end

loop do
  update_vs_and_g(hosts)
  apply
  add_one(hosts)
end
```
4. Check the CPU usage of `istio-ingressgateway`s

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```
$ istioctl version --remote
client version: 1.6.14
control plane version: 1.6.14
data plane version: 1.6.14 (12 proxies)
$ kubectl version --short
Client Version: v1.18.8
Server Version: v1.16.15-eks-ad4801
$ helm version --short
v3.2.4+g0ad800e
```

**How was Istio installed?**

Istio was installed with istioctl without installing IstioOperator in the cluster, so with `istioctl install -f operator.yaml`

**Environment where the bug was observed (cloud vendor, OS, etc)**
AWS EKS 1.16

**Comment by howardjohn** [comment]
What is the real use case? I assume you are not actually constantly switching 2000 hosts every second in the real world? 

Is the goal to have going from 0 -> 2000 be cheaper? Constantly changing a few hosts (eg 1999 -> 2000 -> 1999 -> 2000, etc)? Or do you really need a complete change of 2000 hosts

**Comment by jughead** [comment]
From time to time the list of hosts changes, let's say several times a day, and it's just adding or removing entry to/from the list of hosts. During each change we notice the CPU raise of the ingressgateway pods.
