### ISSUE TITLE
istio vm cleanup when service is stopped

### ISSUE THREAD

**Issue by ristokuu** [istio/istio#29556]
When I deploy istio vmintegration using this guide: https://istio.io/latest/docs/setup/install/virtual-machine/ to a vm and start the istio service when there is a confguration problem the dns stops working. stopping the istio service does not resolve the situation.

[ ] Docs
[x] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

consul local dns should work with istio installed

install istio using the guide at https://istio.io/latest/docs/setup/install/virtual-machine/ and have some error in the vm config
Version:
client version: 1.8.0
control plane version: 1.8.0
data plane version: 1.8.0 (51 proxies)
Client Version: v1.18.2
Server Version: v1.16.15-eks-ad4801

istio was installed with istioctl and additional guide https://istio.io/latest/docs/setup/install/virtual-machine/

AWS, Centos8

**Comment by howardjohn** [comment]
@stevenctl we probably need an istio-stop script that removes iptables rules. I would guess we can make systemd execute it on exit as well. Or we can make it run whenever istio-start exits but that seems probably not the correct behavior?

**Comment by stevenctl** [comment]
I think `ExecStop` makes sense.
