### ISSUE TITLE
TLS failures missing access log

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#29565]
```
2020-12-10T21:02:41.789060Z     debug   envoy filter    original_dst: New connection accepted
2020-12-10T21:02:41.789320Z     debug   envoy filter    tls inspector: new connection accepted
2020-12-10T21:02:41.802994Z     debug   envoy filter    http inspector: new connection accepted
2020-12-10T21:02:41.803117Z     debug   envoy conn_handler      [C1160] new connection
2020-12-10T21:02:41.805637Z     debug   envoy connection        [C1160] TLS error: 268435648:SSL routines:OPENSSL_internal:PEER_DID_NOT_RETURN_A_CERTIFICATE
2020-12-10T21:02:41.805656Z     debug   envoy connection        [C1160] closing socket: 0
2020-12-10T21:02:41.805680Z     debug   envoy connection        [C1160] TLS error: 268435648:SSL routines:OPENSSL_internal:PEER_DID_NOT_RETURN_A_CERTIFICATE
2020-12-10T21:02:41.805727Z     debug   envoy conn_handler      [C1160] adding to cleanup list
```

No access log shows up.

The request is a plain TLS request when mTLS is expected. There is no visibility into the error on the server side without debug logs

If I disable the NR access log filter on the listener access log, I get logs like `[2020-12-10T21:06:04.154Z] "- - -" 0 - - - "-" 0 0 14 - "-" "-" "-" "-" "-" - - 10.244.0.50:8443 10.244.0.52:35008 - -`, so its being filtered out it seems.

cc @gargnupur

**Comment by howardjohn** [comment]
Priority seems fairly low since this never gave access logs, so its not a regression or anything.

**Comment by tariq1890** [comment]
I see this in both 1.7 and 1.8

**Comment by howardjohn** [comment]
not stale

**Comment by JesperBerggren** [comment]
Still not stale. 
Maybe not high priority compared to other issues, but TLS failures are still missing... and are still needed by some (e.g. us).

**Comment by rhyswilliamsza** [comment]
Hey @howardjohn! Please would you re-open this from your end? Definitely a +1 from us.

**Comment by howardjohn** [comment]
Since this issue (3yo) this has improved a lot. Probably best to open a new issue and include the version (hopefully a recent one!) and what is missing. I am almost certain the original issue is resolved.

**Comment by frittentheke** [comment]
@howardjohn sorry to revive this old issue, but I believe it could still be valid.

On our Istio Gateways we optionally expect mTLS (client certs). Thus we added `downstream_transport_failure_reason` to our access logs to see if there would be issues with mTLS certs on incoming connections. But as others reported there is not a single line logged for these connections, let alone with the field `downstream_transport_failure_reason` populated.

Are access logs of gateways not expected to also log failed connections that never made it past the TLS handshake phase?

**Comment by howardjohn** [comment]
@frittentheke in general I would expect them (as a user) to show up. Whether they do in all cases (inbound, outbound, gateway vs sidecar etc) is another question.

In general in envoy there are 2 layers of access logs, listener and HTTP/TCP proxy level. So tls handshake I assume fails at the listener level. We only conditionally enable the listener access log, so maybe need to include it in more cases

**Comment by frittentheke** [comment]
> @frittentheke in general I would expect them (as a user) to show up. Whether they do in all cases (inbound, outbound, gateway vs sidecar etc) is another question.
> 
> In general in envoy there are 2 layers of access logs, listener and HTTP/TCP proxy level. So tls handshake I assume fails at the listener level. We only conditionally enable the listener access log, so maybe need to include it in more cases

Wow, thanks for the fast feedback @howardjohn .
Any chance you could drop a pointer to where the code lives handling the listener access logs?

**Comment by howardjohn** [comment]
https://github.com/istio/istio/blob/09a53ce282816a691e91961570ad34fb3f4c2a20/pilot/pkg/networking/core/accesslog.go#L222. listenerAccessLogFilter is the important part

**Comment by frittentheke** [comment]
> [istio/pilot/pkg/networking/core/accesslog.go](https://github.com/istio/istio/blob/09a53ce282816a691e91961570ad34fb3f4c2a20/pilot/pkg/networking/core/accesslog.go#L222)
> 
> Line 222 in [09a53ce](/istio/istio/commit/09a53ce282816a691e91961570ad34fb3f4c2a20)
>  func (b *AccessLogBuilder) setListenerAccessLog(push *model.PushContext, proxy *model.Proxy, 
> . listenerAccessLogFilter is the important part

For reference, the fact that `DOWNSTREAM_TRANSPORT_FAILURE_REASON` is only available via the listener logs is indeed mentioned in the docs https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage#config-access-log-format-downstream-transport-failure-reason and was discussed when this feature was added (https://github.com/envoyproxy/envoy/pull/25322/files#r1105975567):

> Note: it only works in listener access config, and the HTTP or TCP access logs would observe empty values.

I am now trying to understand how Istio does use and combine the two types access logs and also which filter would actually provide the TLS errors. 

Coming from a config with `proxy_protocol` and `tls_inspector` filters:

```
[...]
       "listener_filters": [
        {
         "name": "envoy.filters.listener.proxy_protocol",
         "typed_config": {
          "@type": "type.googleapis.com/envoy.extensions.filters.listener.proxy_protocol.v3.ProxyProtocol"
         }
        },
        {
         "name": "envoy.filters.listener.tls_inspector",
         "typed_config": {
          "@type": "type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector",
          "initial_read_buffer_size": 512
         }
        }
       ],
       "traffic_direction": "OUTBOUND",
       "access_log": [
        {
         "name": "envoy.access_loggers.file",
         "filter": {
          "response_flag_filter": {
           "flags": [
            "NR"
           ]
          }
         },
         "typed_config": {
          "@type": "type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog",
          "path": "/dev/stdout",
          "log_format": {
           "json_format": {
            "downstream_local_address": "%DOWNSTREAM_LOCAL_ADDRESS_WITHOUT_PORT%",
            "request_tx_duration": "%REQUEST_TX_DURATION%",
            "downstream_tls_version": "%DOWNSTREAM_TLS_VERSION%",
            "bytes_received": "%BYTES_RECEIVED%",
            "response_code": "%RESPONSE_CODE%",
            "trace_id": "%TRACE_ID%",
            "response_flags": "%RESPONSE_FLAGS%",
            "method": "%REQ(:METHOD)%",
            "response_duration": "%RESPONSE_DURATION%",
            "downstream_direct_remote_address": "%DOWNSTREAM_DIRECT_REMOTE_ADDRESS_WITHOUT_PORT%",
            "upstream_transport_failure_reason": "%UPSTREAM_TRANSPORT_FAILURE_REASON%",
            "upstream_cluster": "%UPSTREAM_CLUSTER_RAW%",
            "stream_id": "%STREAM_ID%",
            "authority": "%REQ(:AUTHORITY)%",
            "upstream_connection_id": "%UPSTREAM_CONNECTION_ID%",
            "path": "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%",
            "start_time": "%START_TIME%",
            "connection_id": "%CONNECTION_ID%",
            "request_duration": "%REQUEST_DURATION%",
            "downstream_remote_port": "%DOWNSTREAM_REMOTE_PORT%",
            "response_tx_duration": "%RESPONSE_TX_DURATION%",
            "downstream_direct_remote_port": "%DOWNSTREAM_DIRECT_REMOTE_PORT%",
            "upstream_local_port": "%UPSTREAM_LOCAL_PORT%",
            "request_headers_bytes": "%REQUEST_HEADERS_BYTES%",
            "duration": "%DURATION%",
            "request_id": "%REQ(X-REQUEST-ID)%",
            "x_forwarded_for": "%REQ(X-FORWARDED-FOR)%",
            "requested_server_name": "%REQUESTED_SERVER_NAME%",
            "downstream_remote_address": "%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%",
            "upstream_remote_port": "%UPSTREAM_REMOTE_PORT%",
            "upstream_local_address": "%UPSTREAM_LOCAL_ADDRESS_WITHOUT_PORT%",
            "protocol": "%PROTOCOL%",
            "downstream_local_port": "%DOWNSTREAM_LOCAL_PORT%",
            "route_name": "%ROUTE_NAME%",
            "user_agent": "%REQ(USER-AGENT)%",
            "upstream_service_time": "%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%",
            "response_code_details": "%RESPONSE_CODE_DETAILS%",
            "bytes_sent": "%BYTES_SENT%",
            "downstream_transport_failure_reason": "%DOWNSTREAM_TRANSPORT_FAILURE_REASON%",
            "upstream_remote_address": "%UPSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%",
            "downstream_tls_cipher": "%DOWNSTREAM_TLS_CIPHER%",
            "connection_termination_details": "%CONNECTION_TERMINATION_DETAILS%",
            "upstream_host": "%UPSTREAM_HOST_NAME_WITHOUT_PORT%"
           },
           "json_format_options": {}
          }
         }
        }
       ],
[...]
```

And then looking at a failing connection (due to TLS version 1.0 being used)  in trace log level:
```

{"time":"2025-10-30T15:37:29.343051Z","level":"debug","scope":"envoy filter","msg":"proxy_protocol: New connection accepted","caller":"external/envoy/source/extensions/filters/listener/proxy_protocol/proxy_protocol.cc:176","thread":"25"}
{"time":"2025-10-30T15:37:29.343092Z","level":"trace","scope":"envoy misc","msg":"TcpListener accepted 1 new connections.","caller":"external/envoy/source/common/network/tcp_listener_impl.cc:123","thread":"25"}
{"time":"2025-10-30T15:37:29.343104Z","level":"trace","scope":"envoy filter","msg":"onFileEvent: 1","caller":"external/envoy/source/common/network/listener_filter_buffer_impl.cc:95","thread":"25"}
{"time":"2025-10-30T15:37:29.343111Z","level":"trace","scope":"envoy filter","msg":"recv returned: 107","caller":"external/envoy/source/common/network/listener_filter_buffer_impl.cc:60","thread":"25"}
{"time":"2025-10-30T15:37:29.343118Z","level":"trace","scope":"envoy filter","msg":"proxy_protocol: Skip TLV of type 3 since it's not needed for dynamic metadata","caller":"external/envoy/source/extensions/filters/listener/proxy_protocol/proxy_protocol.cc:596","thread":"25"}
{"time":"2025-10-30T15:37:29.343122Z","level":"trace","scope":"envoy filter","msg":"proxy_protocol: Skip TLV of type 4 since it's not needed for dynamic metadata","caller":"external/envoy/source/extensions/filters/listener/proxy_protocol/proxy_protocol.cc:596","thread":"25"}
{"time":"2025-10-30T15:37:29.343130Z","level":"trace","scope":"envoy filter","msg":"Parsed proxy protocol header, cmd: PROXY, length: 100, buffer: REDACTED, TLV length: 72, TLV buffer: REDACTED","caller":"external/envoy/source/extensions/filters/listener/proxy_protocol/proxy_protocol.cc:271","thread":"25"}
{"time":"2025-10-30T15:37:29.343170Z","level":"trace","scope":"envoy filter","msg":"recv returned: 100","caller":"external/envoy/source/common/network/listener_filter_buffer_impl.cc:41","thread":"25"}
{"time":"2025-10-30T15:37:29.343176Z","level":"trace","scope":"envoy filter","msg":"tls inspector: new connection accepted","caller":"external/envoy/source/extensions/filters/listener/tls_inspector/tls_inspector.cc:112","thread":"25"}
{"time":"2025-10-30T15:37:29.343183Z","level":"trace","scope":"envoy filter","msg":"onFileEvent: 1","caller":"external/envoy/source/common/network/listener_filter_buffer_impl.cc:95","thread":"25"}
{"time":"2025-10-30T15:37:29.343187Z","level":"trace","scope":"envoy filter","msg":"recv returned: 7","caller":"external/envoy/source/common/network/listener_filter_buffer_impl.cc:60","thread":"25"}
{"time":"2025-10-30T15:37:29.343189Z","level":"trace","scope":"envoy filter","msg":"tls inspector: recv: 7","caller":"external/envoy/source/extensions/filters/listener/tls_inspector/tls_inspector.cc:152","thread":"25"}
{"time":"2025-10-30T15:37:29.343208Z","level":"debug","scope":"envoy filter","msg":"tls inspector: parseClientHello failed: error:1000042e:SSL routines:OPENSSL_internal:TLSV1_ALERT_PROTOCOL_VERSION","caller":"external/envoy/source/extensions/filters/listener/tls_inspector/tls_inspector.cc:227","thread":"25"}
{"time":"2025-10-30T15:37:29.343298Z","level":"debug","scope":"envoy conn_handler","msg":"closing connection from 57.133.65.182:13231: no matching filter chain found","caller":"external/envoy/source/common/listener_manager/active_stream_listener_base.cc:45","thread":"25"}

{"authority":null,"bytes_received":0,"bytes_sent":0,"connection_id":0,"connection_termination_details":null,"downstream_direct_remote_address":"REDACTED","downstream_direct_remote_port":13231,"downstream_local_address":"100.64.226.69","downstream_local_port":443,"downstream_remote_address":"REDACTED","downstream_remote_port":13231,"downstream_tls_cipher":null,"downstream_tls_version":null,"downstream_transport_failure_reason":null,"duration":0,"method":null,"path":null,"protocol":null,"request_duration":null,"request_headers_bytes":0,"request_id":null,"request_tx_duration":null,"requested_server_name":null,"response_code":0,"response_code_details":"filter_chain_not_found","response_duration":null,"response_flags":"NR","response_tx_duration":null,"route_name":null,"start_time":"2025-10-30T15:37:29.343Z","stream_id":null,"trace_id":null,"upstream_cluster":null,"upstream_connection_id":0,"upstream_host":null,"upstream_local_address":null,"upstream_local_port":null,"upstream_remote_address":null,"upstream_remote_port":null,"upstream_service_time":null,"upstream_transport_failure_reason":null,"user_agent":null,"x_forwarded_for":null}
```


@howardjohn I understand you comment about the listener logs being filtered, and I suppose this is what 
the filtering on the NR flag is for?

* https://github.com/istio/istio/blob/48dda0ed50c6b72621612e5ce36de17f7206308b/pilot/pkg/networking/core/accesslog.go#L254
* https://github.com/istio/istio/blob/48dda0ed50c6b72621612e5ce36de17f7206308b/pilot/pkg/networking/core/accesslog.go#L79-L81


But strangely my test-case (incompatible TLS version) did produce an access log line:

```
{"authority":null,"bytes_received":0,"bytes_sent":0,"connection_id":0,"connection_termination_details":null,"downstream_direct_remote_address":"REDACTED","downstream_direct_remote_port":13231,"downstream_local_address":"100.64.226.69","downstream_local_port":443,"downstream_remote_address":"REDACTED","downstream_remote_port":13231,"downstream_tls_cipher":null,"downstream_tls_version":null,"downstream_transport_failure_reason":null,"duration":0,"method":null,"path":null,"protocol":null,"request_duration":null,"request_headers_bytes":0,"request_id":null,"request_tx_duration":null,"requested_server_name":null,"response_code":0,"response_code_details":"filter_chain_not_found","response_duration":null,"response_flags":"NR","response_tx_duration":null,"route_name":null,"start_time":"2025-10-30T15:37:29.343Z","stream_id":null,"trace_id":null,"upstream_cluster":null,"upstream_connection_id":0,"upstream_host":null,"upstream_local_address":null,"upstream_local_port":null,"upstream_remote_address":null,"upstream_remote_port":null,"upstream_service_time":null,"upstream_transport_failure_reason":null,"user_agent":null,"x_forwarded_for":null}
```

But that did not contain any `downstream_transport_failure_reason` which is contrary to what Envoy documents about TLS troubleshooting in https://github.com/botengyao/envoy/blob/main/docs/root/intro/arch_overview/security/ssl.rst#trouble-shooting 

Diving a little deeper into now `tls_inspector` does handle its logged error:  `error:1000042e:SSL routines:OPENSSL_internal:TLSV1_ALERT_PROTOCOL_VERSION`  I wondered how this, or any error for that matter, was communicated to Envoy. Apparently there is some data sharing done via "dynamic metadata", see https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/advanced/data_sharing_between_filters.html#dynamic-state

Looking at the exact line of code the error originated https://github.com/envoyproxy/envoy/blob/c561059a04f496eda1e664a8d45bf9b64deef100/source/extensions/filters/listener/tls_inspector/tls_inspector.cc#L227 there is a call to write to key `failure_reason` (https://github.com/envoyproxy/envoy/blob/c561059a04f496eda1e664a8d45bf9b64deef100/source/extensions/filters/listener/tls_inspector/tls_inspector.cc#L183).
This seems to then be picked up by `stream_info` around https://github.com/envoyproxy/envoy/blob/c561059a04f496eda1e664a8d45bf9b64deef100/source/common/stream_info/stream_info_impl.h#L445

which loops me right back to MR https://github.com/envoyproxy/envoy/pull/25322 by @botengyao who added this field in the first place.

There also is a follow up MR by @suniltheta which exposed this `failure_reason` to other filters (https://github.com/envoyproxy/envoy/pull/31058). But apparently this does also not seem to work as expected https://github.com/envoyproxy/envoy/issues/33796

Sorry about the lengthy post - I just wanted to take you onto my wild right of how TLS failures are propagated within Envoy to end up in the access log ...

Maybe this very issue here could be reopened @howardjohn ?

**Comment by frittentheke** [comment]
FWIW (see new issue https://github.com/istio/istio/issues/58281), there now is a fix merged for Envoy: https://github.com/envoyproxy/envoy/pull/42034
