### ISSUE TITLE
Define CRD for release notes

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#29561]
if we define a simple CRD with the open api schema set, editors can understand it and autofill the supported enum values, validate the fields, etc

Probably not high priority but would be handy

cc @brian-avery @sdake

**Comment by brian-avery** [comment]
Sounds like a great idea to formalize the work in https://github.com/istio/tools/tree/master/cmd/gen-release-notes.

**Comment by brian-avery** [comment]
Added in https://github.com/istio/tools/pull/1532 and https://github.com/istio/tools/pull/1532
