### ISSUE TITLE
Connection to redis (AWS ElastiCache) suddently stopped working

### ISSUE THREAD

**Issue by lonnix** [istio/istio#29569]
**Bug description**
This is all with 1.8.0.
I have had Istio running for a couple weeks and during that time multiple pods in the mesh (behind istio-proxy) were able to connect to several AWS ElastiCache instances over port 6379. One day a developer reported connection issues and we quickly found that every pod running with the proxy sidecar could no longer connect to ElastiCache. Pods without the sidecar (outside the mesh) but in the same cluster and multiple namespaces could all connect fine, as could local laptops. The issue was isolated to pods running behind the istio proxy. This problem lasted a few hours and since it was in nonprod I decided to pick it up again the next day, but the follow morning the issue could not be replicated and everything worked as it did previously. 

We tried restarting the pods while the issue was happening but that did not fix things. When the issue seemed to be resolved I was able to connect to ElastiCache from a newly created pod with the sidecar and a pod from the day before that previously couldn't connect to Elasticache.

I tested the connections by exec'ing into the main container in the pod that my app runs from and executing `redis-cli -h <elasticache-host-url>` and then running `INFO`

```
~: redis-cli -h my.elasticache.instance.cache.amazonaws.com
core-api-dev.odz8sr.ng.0001.use1.cache.amazonaws.com:6379> INFO
Error: Protocol error, got "H" as reply type byte
```

Every time I tried a test I got that `Protocol error` from above until it just started working again. 

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
I expect that pods with the sidecar are always able to connect to redis (AWS ElastiCache) instances

**Steps to reproduce the bug**
Since the issue seems to have resolved itself I will say it cannot be replicated. We're still trying to re-create it, but there is no definite way at this time. 

**Version** 
```
client version: 1.8.0
control plane version: 1.8.0
data plane version: 1.8.0 (23 proxies)

helm: v3.4.1+gc4e7485
kubectl: Client Version: v1.18.5
             Server Version: v1.17.12-eks-7684af
```

**How was Istio installed?**
Via Helm 3 with these commands
```
helm upgrade -i -n istio-system istio-base istio-1.8.0/manifests/charts/base -f ./custom-base-values.yaml
helm upgrade -i -n istio-system istiod istio-1.8.0/manifests/charts/istio-control/istio-discovery -f ./custom-istiod-values.yaml --set global.hub="docker.io/istio" --set global.tag="1.8.0"
helm upgrade -i -n istio-system istio-ingress istio-1.8.0/manifests/charts/gateways/istio-ingress -f ./custom-istio-ingress-values.yaml --set global.hub="docker.io/istio" --set global.tag="1.8.0"
```
The only difference between the default values.yaml files and my custom ones are 
* none for base
* `autoInject: disabled` instead of `autoInject: enabled` for istiod
* some `serviceAnnotations` for the ingressgateway for istio-ingressgateway

**Environment where the bug was observed (cloud vendor, OS, etc)**
AWS EKS (v1.17.12-eks-7684af)

**Comment by hzxuzhonghu** [comment]
Could you dump the config when this happens again?

**Comment by lonnix** [comment]
@hzxuzhonghu Which config do you want? I'll gather anything I can if it happens again.....if......

**Comment by hzxuzhonghu** [comment]
exec into the istio-proxy container and run `curl 127.0.0.1:15000/config_dump`

**Comment by lonnix** [comment]
This issue has yet to happen again and I don't know when/if I'll get around to recreating it manually. I will close this issue and open a new one with the config dump requested above if I can recreate the issue.
