### ISSUE TITLE
Istio-Ingressgateway Responds with 503 upstream connect error on Routes that match /proxy

### ISSUE THREAD

**Issue by Adharsh-Muraleedharan** [istio/istio#29571]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
Istio Ingressgateway throws a 503 upstream connect error when matching a route with URI prefix set to "/proxy/". We have setup multiple matches on our virtualservice for various URI prefix's all routing to a single service. All the routes works fine except the one that we match using the prefix of "/proxy/". We assume that this might be due to some special meaning of /proxy/ assigned by the ingress gateway.

while debugging we were able to reach the service using the same exact request for /proxy/ from inside the cluster bypassing the ingress-gateway. The service responds with a 200 on that case. Only when the request reaches through the ingress gateway we are facing this issue.
```
The Logs from the istio ingress gateway corresponding to the request is given below :
[Envoy (Epoch 0)] [2020-12-11 04:28:16.851][32][debug][router] [external/envoy/source/common/router/router.cc:474] [C1678215][S1800260394623576323] cluster 'outbound|80|BLUE|fo-platform.fo-platform-dev.svc.cluster.local' match for URL '/proxy/v1/bit/run/example:hello.rb/sync/60000'

[2020-12-11T04:28:16.851Z] "POST /proxy/v1/bit/run/example:hello.rb/sync/60000 HTTP/1.1" 503 UC "-" "-" 2 95 30 - "115.112.69.51,10.197.120.220" "curl/7.54.0" "a6e77117-3145-4471-a6ee-40ee23fa0e8b" "somedomain.common.ouraccount.com" "10.197.112.171:3500" outbound|80|BLUE|fo-platform.fo-platform-dev.svc.cluster.local 10.197.82.52:33040 10.197.82.52:80 10.197.120.220:25406 - -

```
The proxy config Routes file of our configuration is put in the below link for reference.
https://gist.github.com/Adharsh-Muraleedharan/d0b551a685eb4c6314f659bb511e6112
[](https://gist.github.com/Adharsh-Muraleedharan/d0b551a685eb4c6314f659bb511e6112)

Please let us know how we could fix this ?

[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
The URI prefix match of /proxy/ should be routed to the service like all other requests.

**Steps to reproduce the bug**
Setup multiple virtualservice routes with one having URI prefix matching that of "/proxy/" and try to reach the service through the ingress gateway.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
Istioctl - 1.5.8
Kubectl Client Version: v1.15.11-eks-908ff6
Kubectl Server Version: v1.17.12-eks-7684af
we do not use HELM

**How was Istio installed?**
Istio was installed using istioctl manifest generate and then applying the manifest.

**Environment where the bug was observed (cloud vendor, OS, etc)**
AWS cloud we use managed service EKS.

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by Adharsh-Muraleedharan** [comment]
@ramaraochavali - Could you help us with this ?

**Comment by ramaraochavali** [comment]
Can you share full config dump and also the full envoy logs?

**Comment by Adharsh-Muraleedharan** [comment]
@ramaraochavali - The entire config dump is placed here
https://gist.github.com/Adharsh-Muraleedharan/0db5f49df843bc3abddac2f8a288284d

**Comment by ramaraochavali** [comment]
Sorry for the delay. Config seems correct. Can you also share complete Envoy logs? and can you also config `outbound|80|BLUE|fo-platform.fo-platform-dev.svc.cluster.local` this has endpoints populated?

**Comment by howardjohn** [comment]
Ping @Adharsh-Muraleedharan

**Comment by howardjohn** [comment]
Also see https://istio.io/latest/news/support/announcing-1.6-eol-final/

**Comment by howardjohn** [comment]
Closing as we don't have enough info. Thanks!
