### ISSUE TITLE
behind the sidecar,mysql Nodeport can not connect from navicat

### ISSUE THREAD

**Issue by liyin37** [istio/istio#29577]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**
first:
kubectl apply -f mysql.yaml
the yaml file is：
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
name: gistack-mysql
spec:
accessModes:
- ReadWriteOnce
resources:
requests:
storage: 5Gi
storageClassName: glusterfs
apiVersion: apps/v1
kind: Deployment
metadata:
name: mysql
spec:
selector:
matchLabels:
app: gistack-mysql
template:
metadata:
labels:
app: gistack-mysql
spec:
containers:
- name: mysql
image: www.baidu.com/example/mysql:8.0
resources:
limits:
cpu: 500m
memory: 1Gi
requests:
cpu: 200m
memory: 500Mi
ports:
- containerPort: 3306
protocol: TCP
env:
- name: "MYSQL_ROOT_PASSWORD"
value: "xxxxxx"
- name: "TZ"
value: "Asia/Shanghai"
args:
- --character-set-server=utf8mb4
- --collation-server=utf8mb4_unicode_ci
volumeMounts:
- name: data
mountPath: /var/lib/mysql
volumes:
- name: data
persistentVolumeClaim:
claimName: gistack-mysql
apiVersion: v1
kind: Service
metadata:
name: mysql
labels:
app: mysql
spec:
selector:
app: gistack-mysql
type: NodePort
ports:
  name: tcp
  port: 3306
  protocol: TCP

second:
[root@gistack-test yaml]# kubectl -n gistack get all |grep mysql
pod/mysql-75cfcdd777-cm9gh 2/2 Running 0 37m
service/mysql NodePort 10.43.205.225 3306:32644/TCP 37m
deployment.apps/mysql 1/1 1 1 37m
replicaset.apps/mysql-75cfcdd777 1 1 1 37m

third:
connect mysql from navicat 
Lost connection to MySQL server at 'waiting for initial communication packet', system error: 0
![Dingtalk_20201211165018](https://user-images.githubusercontent.com/42507175/101882527-fc79a900-3bd0-11eb-9c85-d8388b247189.jpg)

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
the version is below:
istio：1.8.1
kubernetes：1.19.1
mysql ：8.0
**How was Istio installed?**
./istioctl install 
kubectl apply -f samples/addons

**Environment where the bug was observed (cloud vendor, OS, etc)**
OS

istioctl bug-report:
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

**Comment by howardjohn** [comment]
duplicate of https://github.com/istio/istio/issues/29548#issuecomment-780145570 which is resolved
