### ISSUE TITLE
OnInboundFilterChains is a poor abstraction leading to tightly coupled code

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#29588]
OnInboundFilterChains sets up filter chains for mtls (currently this is the only usage at least, and if anyone else tried to do something it would break). We then have a bunch of code that depends on these details: https://github.com/istio/istio/blob/994b0b7460c8358f4a467e4e08371985351498bf/pilot/pkg/networking/core/v1alpha3/listener.go#L559 from there down

This leads to a bunch of interesting behavior, such as https://github.com/istio/istio/issues/29587, or the fact that if any new plugin started implementing this we would bypass the authn. We also have code that is doing things like deciding that if the tls inspector is set on a listener it means its permissive code, then completely rewriting the filter chains.

Since the two are so tightly coupled, we should make one or the other "dumb"er and consolidate the logic in a single place.

**Comment by howardjohn** [comment]
@yangminzhu I have been thinking about this for quite a while and can't think of any great alternatives. I think the best thing we can do is instead of having this implicit coupling, be very explicit, and have the plugin return a very clear response:
```
{
Mode: disable, permissive, strict
TlsContext: *tls (set only with permissive or strict mode)
}
```

Something like this instead

Even still, the pilot core logic is going to modify the tls context from https://github.com/istio/istio/blob/9a1818dc8fd994421b320a7fdb2f044cc9088724/pilot/pkg/networking/core/v1alpha3/listener.go#L669 so its pretty leaky still..

Let me know if you have any ideas

**Comment by yangminzhu** [comment]
One option I thought about is to just remove it from the filter plugin interface and merge the logic directly to the core code. This might make the code cleaner but I think it does not address the concern of the tight coupling even we put it under a different package. I'm wondering is it possible to have a single point in the core pilot code path to process the mtls filter china configuration instead of spreading the logic everywhere?

**Comment by howardjohn** [comment]
I think the core code clearly needs to be mTLS aware, since it impacts almost a huge part of the filter chain. Whether all plugins should go aware is an interesting idea... in generally I really don't like the plugins. We also have a lot of weird behavior like partially populating the PluginParams because we known the other fields are not used, which is not great (and has led to bugs in the past). I think @douglas-reid is considering with telemetry whether to make it a plugin or not.

I have a WIP of keeping the plugin stuff but making it less transparent - instead of generically acting on filter chains, it explicitly returns mTLS configuration info. Its not clean right now, but you can take a look at https://github.com/istio/istio/pull/31374 if you want.

**Comment by mandarjog** [comment]
@kyessenov you have commented on this often. For awareness.
