### ISSUE TITLE
AuthorizationPolicy validates JWT, but does not pass the token in the header to the downstream pod

### ISSUE THREAD

**Issue by lizongshen** [istio/istio#29581]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
The authorization policy verifies JWT, but does not pass the token in the header to the downstream pod,
Token seems to have been discarded by sidecar。

After the token sent from the end user is forwarded to the specific service through the browser, it should be passed to the service interior, because the internal service needs to obtain the user's information according to the token in the header

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

apiVersion: "security.istio.io/v1beta1"
kind: "RequestAuthentication"
metadata:
  name: "jwt-auth"
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  jwtRules:
  - issuer: "null"
    jwksUri: "http://10.19.50.65:31000/authserver/.well-known/openid-configuration/jwks"
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: authorization-policy
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  action: ALLOW
  rules:
  - to:
    - operation:
        paths: ["/web/"]
  - from:
    - source:
        requestPrincipals: ["*"]
    to:
    - operation:
        paths: ["/service/api/*"]

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
client version: 1.2.2
ingressgateway version: 1.8.1
ingressgateway version: 1.8.1
pilot version: 1.8.1
ingressgateway version: 1.8.1

Client Version: v1.18.0
Server Version: v1.18.0

**How was Istio installed?**
istioctl install
**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by rinormaloku** [comment]
@lizongshen there is a property to define passing on the token (currently it is removed as designed for security purposes)

**Comment by lizongshen** [comment]
@rinormaloku Thank you for your answer. It solved my problem
