### ISSUE TITLE
Apple Silicon/M1 builds for Istioctl

### ISSUE THREAD

**Issue by cagataygurturk** [istio/istio#29596]
**Describe the feature request**

Native builds for Apple Silicon/M1 after Go releases its support for that platform.

**Describe alternatives you've considered**

Currently Rosetta 2 runs Istioctl just fine.

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[x] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Comment by howardjohn** [comment]
If I understand correctly, this requires go 1.16 (https://tip.golang.org/doc/go1.16#darwin) then building with GOOS=darwin and GOARCH=arm64. This is reasonable to do once we update to 1.16, which we will do once its released, which will probably just miss the 1.9 release.

**Comment by cagataygurturk** [comment]
That‘s correct @howardjohn. The relevant Go issue tracking Apple Silicon support is here: https://github.com/golang/go/issues/39782

Can we protect this issue being closed for being stale, since Go support will at least take until February 2021 to be released?

**Comment by brian-avery** [comment]
Changed this to a p1 in 1.10 due to the fact that this already works in Rosetta and won't make it into 1.9. Having builds will be important, but we also don't have a way to test this. Are there any volunteers? Thanks.

**Comment by cagataygurturk** [comment]
> Changed this to a p1 in 1.10 due to the fact that this already works in Rosetta and won't make it into 1.9. Having builds will be important, but we also don't have a way to test this. Are there any volunteers? Thanks.

I have a M1 and I am happy to help for testing

**Comment by cagataygurturk** [comment]
Go 1.16 is released

**Comment by howardjohn** [comment]
@cagataygurturk would appreciate if you can try out https://github.com/istio/istio/pull/30890. I posted a link to a prebuilt binary as well

**Comment by sayjeyhi** [comment]
@howardjohn I tried to test your provided binary file but seems that image `istio/pilot:1.10-dev` is not found.

**Comment by howardjohn** [comment]
We only support the istioctl client binary. Istio serverside components (istiod/gateway/sidecar) do not support ARM 

Closing this since we have completed our support. Thanks for testing!

**Comment by sayjeyhi** [comment]
@howardjohn thanks, but you mean that we will not be able to use istio ingress getway on M1 locally?

Do you have any suggestions of how we could handle it?!

**Comment by howardjohn** [comment]
Running Istio on ARM is a ways off, see
https://github.com/istio/istio/issues/21094. Running Istio on ARM+mac is
probably even further off unless envoy plans to support this as well.

**Comment by howardjohn** [comment]
See https://github.com/istio/istio/issues/35176. tl;dr hardware + some CI/CD work. I would expect this to be ready ~soon
