### ISSUE TITLE
Deprecation info for istioctl cmd should align with istio version dynamically

### ISSUE THREAD

**Issue by carolynhu** [istio/istio#29591]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
In istio.io, when we want to deprecate a command, we will have deprecation info like this:
<img width="793" alt="Screen Shot 2020-12-11 at 8 21 11 PM" src="https://user-images.githubusercontent.com/29208297/101973653-72403d80-3bee-11eb-92b0-bc8979b44b61.png">

which seems to be hard coded here: https://github.com/istio/istio/blob/master/istioctl/cmd/root.go#L55
we'd better make the version here dynamically changes as istio update to a new version

[ x] Docs
[] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ x] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by shamsher31** [comment]
> which seems to be hard coded here: https://github.com/istio/istio/blob/master/istioctl/cmd/root.go#L55
> we'd better make the version here dynamically changes as istio update to a new version

@carolynhu I think that was intentional https://github.com/istio/istio/issues/26877#issue-687618256 and that message itself will be removed when those deprecated commands are removed.

**Comment by esnible** [comment]
Updating this manually seems better than automating it.

For example, if someone is testing version 1.9 and they see a message saying a feature will be removed in 1.9 they will report a bug which will provide important feedback that we missed removing something.  If we automate the message it is difficult to tell if the message changed on purpose or was forgotten.
