### ISSUE TITLE
VirtualService: Ability to choose a scheme for redirect target

### ISSUE THREAD

**Issue by cagataygurturk** [istio/istio#29597]
**Describe the feature request**

VirtualService's redirect feature does not support choosing the scheme and always redirects to http. However, [Envoy supports](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#config-route-v3-redirectaction) a scheme field, which I believe can be easily supported by Istio also.

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by howardjohn** [comment]
Just curious what the use case is? https://istio.io/latest/docs/reference/config/networking/gateway/#ServerTLSSettings does have `httpsRedirect` which is somewhat related and may cover your case

**Comment by cagataygurturk** [comment]
I was wrong with saying „always redirects to http“ in the issue description. Envoy detects the current scheme of the request and then redirects to that scheme. For https requests it will always return to https also. But the request scheme does not have to necessarily be the scheme of the redirect target.

The potential use case is, users may need to redirect to an http endpoint from a https request. After all envoy has this setting and it wouldn‘t hurt to support it with Istio, I guess.

**Comment by hzxuzhonghu** [comment]
sounds reasonable

**Comment by cagataygurturk** [comment]
Maybe not stale?

**Comment by camelpunch** [comment]
Here's another use case: traffic inside a cluster is "http://" scheme, even though encrypted via Istio's mutual TLS. When redirecting from e.g. non-www to www addresses, you want your location to include the scheme so that browsers don't have to first hit a http URI and a http->https redirect.
