### ISSUE TITLE
503 NR when rollout and restart istiod

### ISSUE THREAD

**Issue by swzhou** [istio/istio#29599]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

We are using Istio 1.7.0 in our production environment. When we rollout to restart Istiod, all the proxies are disconnected and reconnected to newly created Istiod pod. During the process, we can see 503 NR errors when there are consistent requests from the proxy to other service(s) within the mesh. From envoy log, we notice it happened at certain time in "envoy cluster warm-up phase".

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[X] Upgrade

**Expected behavior**

No 503 NR errors during istiod rollout and restart process

**Steps to reproduce the bug**

1. Constantly send requests to a service in mesh from a proxy. For example:
>while true ;do date +"%T" && kubectl exec -it -n default httpbin-777c6f578c-jx4fc -c httpbin -- sh -c "curl -X POST -I http://xx-api.default/api/yy"; done;
2. Rollout restart istiod, this should trigger proxy disconnect and reconnect to istiod.
>kubectl rollout restart deployment/istiod -n istio-system
3. watch logs of the proxy sending requests: 
>kubectl logs -n default -f httpbin-777c6f578c-jx4fc -c istio-proxy --tail=10

From the request log we can see some 503 NR errors like this:
>{"protocol":"HTTP/1.1","upstream_service_time":"-","upstream_local_address":"-","duration":"0","upstream_transport_failure_reason":"-","route_name":"-","downstream_local_address":"**.**.**.**:80","user_agent":"curl/7.64.0","response_code":"503","response_flags":"NR","start_time":"2020-12-11T08:51:31.889Z","method":"POST","request_id":"3a39b6e3-cab6-4414-89da-ac4c06530a4e","upstream_host":"-","x_forwarded_for":"-","requested_server_name":"-","bytes_received":"0","istio_policy_status":"-","bytes_sent":"0","upstream_cluster":"-","downstream_remote_address":"10.28.97.29:59884","authority":"xx-api.default","path":"/api/yy"}

From the debug log we can see some cluster not found error like this:

>2020-12-11T08:51:32.455166Z	debug	envoy conn_handler	[C107665] new connection
>2020-12-11T08:51:32.455196Z	debug	envoy http	[C107665] new stream
>2020-12-11T08:51:32.455226Z	debug	envoy http	[C107665][S14709698978255946193] request headers >complete (end_stream=true):
>':authority', 'xx-api.default'
>':path', '/api/yy'
>':method', 'POST'
>'user-agent', 'curl/7.64.0'
>'accept', '*/*'
> 
> 2020-12-11T08:51:32.455230Z	debug	envoy http	[C107665][S14709698978255946193] request end stream
> 2020-12-11T08:51:32.455295Z	debug	envoy filter	cannot find cluster outbound|80|normal|xx-api.default.svc.cluster.local
>2020-12-11T08:51:32.455310Z	debug	envoy router	[C107665][S14709698978255946193] unknown cluster 'outbound|80|normal|xx-api.default.svc.cluster.local'
>2020-12-11T08:51:32.455316Z	debug	envoy http	[C107665][S14709698978255946193] Sending local reply with details cluster_not_found
>2020-12-11T08:51:32.455337Z	debug	envoy http	[C107665][S14709698978255946193] encoding headers via codec (end_stream=true):
>':status', '503'
>'date', 'Fri, 11 Dec 2020 08:51:31 GMT'
>'server', 'envoy'
>  
>2020-12-11T08:51:32.455660Z	debug	envoy connection	[C107665] remote close
>2020-12-11T08:51:32.455666Z	debug	envoy connection	[C107665] closing socket: 0
>2020-12-11T08:51:32.455707Z	debug	envoy conn_handler	[C107665] adding to cleanup list

We also see cluster warm up info from the log and notice 503 NR happened at certain phase of cluster warm up process.
>2020-12-11T08:51:24.760182Z	debug	envoy upstream	add/update cluster outbound|80|normal|xx-api.default.svc.cluster.local starting warming
> ...
> 2020-12-11T08:51:32.927901Z	debug	envoy upstream	warming cluster outbound|80||outbound|80|normal|xx-api.default.svc.cluster.local complete

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

istio version: 1.7.0
kubernete version: 1.16.3

**How was Istio installed?**

istioctl install

**Environment where the bug was observed (cloud vendor, OS, etc)**

Tencent Kubernetes Engine (TKE)

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by swzhou** [comment]
I cannot 100% reproduce the issue. But when I have 20~ proxies connected to 1 istiod, I have over 80%  chance to reproduce the issue.
I believe it should happen in a state where rds is prepared and cluster is not ready yet. But I don't think I can do anything in controlling the sequence / time of xds process during istiod restart process.

**Comment by howardjohn** [comment]
Can you post the full debug logs instead of truncated ones?

It may also be useful to look at hte istiod logs side by side, and the config dump before and after restart of istiod. See https://github.com/istio/istio/wiki/Troubleshooting-Istio if you need help getting this info, thanks!

**Comment by swzhou** [comment]
Thank you, John.
Here is the envoy log：[503NR-envoy.log.gz](https://github.com/istio/istio/files/5686351/503NR-envoy.log.gz)

The request service name is xx-api, and you can search path "/api/yy", which are my requests during the restart process. You can find 1 503 NR error in the logs.

For your information, here are some key events I pick up from the log:
2020-12-14T02:29:23.036025Z	debug	envoy upstream	add/update cluster outbound|80||xx-api.default.svc.cluster.local starting warming
>2020-12-14T02:29:29.010879Z	debug	envoy http	[C336079] new stream                PassthroughCluster
>2020-12-14T02:29:30.065733Z	debug	envoy http	[C336084] new stream                PassthroughCluster
>2020-12-14T02:29:31.153477Z	debug	envoy http	[C336086] new stream                503 NR
>2020-12-14T02:29:31.203611Z	debug	envoy upstream	warming cluster outbound|80||xx-api.default.svc.cluster.local complete
>2020-12-14T02:29:32.690389Z	debug	envoy conn_handler	[C336088] new connection    outbound|80|normal|xx-api.default.svc.cluster.local

**Comment by howardjohn** [comment]
```
2020-12-14T02:29:29.042368Z     warn    Envoy proxy is NOT ready: failed to get readiness stats: Get "http://127.0.0.1:15000/stats?usedonly&filter=^(server.state|listener_manager.workers_started)": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2020-12-14T02:29:30.065Z last 200
2020-12-14T02:29:30.838630Z     info    Envoy proxy is ready
2020-12-14T02:29:31.153Z 503

```

700ms before success
```
{"upstream_host":"10.31.206.108:80","x_forwarded_for":"-","requested_server_name":"-","bytes_received":"0","istio_policy_status":"-","bytes_sent":"47","upstream_cluster":"PassthroughCluster","downstream_remote_address":"10.28.97.29:57698","authority":"xx-api.default","path":"/api/yy","protocol":"HTTP/1.1","upstream_service_time":"2","upstream_local_address":"10.28.97.29:57504","duration":"2","upstream_transport_failure_reason":"-","route_name":"allow_any","downstream_local_address":"10.31.206.108:80","user_agent":"curl/7.64.0","response_code":"200","response_flags":"-","start_time":"2020-12-14T02:29:30.065Z","method":"POST","request_id":"9bd35d63-8a58-4b5d-8a6f-708a740d550d"}
```

300ms later failure
```
{"istio_policy_status":"-","bytes_sent":"0","upstream_cluster":"-","downstream_remote_address":"10.28.97.29:57836","authority":"xx-api.default","path":"/api/yy","protocol":"HTTP/1.1","upstream_service_time":"-","upstream_local_address":"-","duration":"0","upstream_transport_failure_reason":"-","route_name":"-","downstream_local_address":"10.31.206.108:80","user_agent":"curl/7.64.0","response_code":"503","response_flags":"NR","start_time":"2020-12-14T02:29:31.153Z","method":"POST","request_id":"3f94ba9d-e720-4969-a839-01ed76b817a0","upstream_host":"-","x_forwarded_for":"-","requested_server_name":"-","bytes_received":"0"}
```

full logs for this cluster:
```
2020-12-14T02:28:43.100928Z     debug   envoy upstream  cds: add/update cluster 'outbound|80|normal|xx-api.default.svc.cluster.local' skipped
2020-12-14T02:28:54.124102Z     debug   envoy init      init manager Cluster outbound|80|normal|xx-api.default.svc.cluster.local destroyed
2020-12-14T02:28:54.124118Z     info    envoy upstream  removing cluster outbound|80|normal|xx-api.default.svc.cluster.local
2020-12-14T02:28:54.124125Z     debug   envoy upstream  removing TLS cluster outbound|80|normal|xx-api.default.svc.cluster.local
2020-12-14T02:28:54.124128Z     debug   envoy upstream  removing TLS cluster outbound|80|normal|xx-api.default.svc.cluster.local
2020-12-14T02:28:54.124138Z     info    envoy upstream  cds: remove cluster 'outbound|80|normal|xx-api.default.svc.cluster.local'
2020-12-14T02:28:54.124294Z     debug   envoy upstream  removing TLS cluster outbound|80|normal|xx-api.default.svc.cluster.local
2020-12-14T02:29:23.038627Z     debug   envoy upstream  add/update cluster outbound|80|normal|xx-api.default.svc.cluster.local starting warming
2020-12-14T02:29:23.038642Z     info    envoy upstream  cds: add/update cluster 'outbound|80|normal|xx-api.default.svc.cluster.local'
2020-12-14T02:29:31.153612Z     debug   envoy filter    cannot find cluster outbound|80|normal|xx-api.default.svc.cluster.local
2020-12-14T02:29:31.153633Z     debug   envoy router    [C336086][S17955833914001647120] unknown cluster 'outbound|80|normal|xx-api.default.svc.cluster.local'
2020-12-14T02:29:31.203448Z     debug   envoy upstream  EDS hosts or locality weights changed for cluster: outbound|80|normal|xx-api.default.svc.cluster.local current hosts 0 priority 0
2020-12-14T02:29:31.203456Z     debug   envoy upstream  initializing Secondary cluster outbound|80|normal|xx-api.default.svc.cluster.local completed
2020-12-14T02:29:31.203458Z     debug   envoy init      init manager Cluster outbound|80|normal|xx-api.default.svc.cluster.local contains no targets
2020-12-14T02:29:31.203460Z     debug   envoy init      init manager Cluster outbound|80|normal|xx-api.default.svc.cluster.local initialized, notifying ClusterImplBase
2020-12-14T02:29:31.203467Z     debug   envoy upstream  warming cluster outbound|80|normal|xx-api.default.svc.cluster.local complete
2020-12-14T02:29:31.203475Z     debug   envoy upstream  adding TLS cluster outbound|80|normal|xx-api.default.svc.cluster.local
2020-12-14T02:29:31.203478Z     debug   envoy upstream  adding TLS cluster outbound|80|normal|xx-api.default.svc.cluster.local
2020-12-14T02:29:31.203475Z     debug   envoy upstream  adding TLS cluster outbound|80|normal|xx-api.default.svc.cluster.local
2020-12-14T02:29:31.203522Z     debug   envoy upstream  membership update for TLS cluster outbound|80|normal|xx-api.default.svc.cluster.local added 10 removed 0
2020-12-14T02:29:31.203523Z     debug   envoy upstream  membership update for TLS cluster outbound|80|normal|xx-api.default.svc.cluster.local added 10 removed 0
2020-12-14T02:29:31.203524Z     debug   envoy upstream  membership update for TLS cluster outbound|80|normal|xx-api.default.svc.cluster.local added 10 removed 0
2020-12-14T02:30:26.988351Z     debug   envoy upstream  cds: add/update cluster 'outbound|80|normal|xx-api.default.svc.cluster.local' skipped
2020-12-14T02:30:46.256416Z     debug   envoy upstream  cds: add/update cluster 'outbound|80|normal|xx-api.default.svc.cluster.local' skipped
```

By the `removing cluster` part, we see this happens to every cluster, looks like in response to XDS failures: gRPC update for type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment failed

No logs for `initial fetch timed out for`

All CDS logs are for `gRPC config for type.googleapis.com/envoy.config.cluster.v3.Cluster accepted with 2885 resources with version`, except one, which has only `6`.

My guess - you are connecting to istiod at startup that hasn't properly warmed up, which is a bug that has been fixed. Please try latest 1.7 or 1.8

**Comment by howardjohn** [comment]
Fix is #26394

**Comment by swzhou** [comment]
OK. Will try and see. Thank you John.

**Comment by swzhou** [comment]
@howardjohn 
Hi John, thanks for providing the fix. I just carefully go through the commits and code mentioned in #26394  and happen to find that all commits are already included in Istio 1.7.0 version - the version we are currently using in our environment.
So I think the fix provided may not solve my issue... 
Would you help to check / confirm? Thanks.

**Comment by howardjohn** [comment]
I see, sorry I forgot it was in that version. Can you provide the istiod logs then? and the pod name that got the 503 so we can search for it in istiod logs. Thanks!

**Comment by howardjohn** [comment]
also if possible testing 1.8 would be useful

**Comment by swzhou** [comment]
@howardjohn 
Try to reproduce the issue again and here is the zipped log file: [logs.zip](https://github.com/istio/istio/files/5693899/logs.zip) , where "istiod.log" is log from istiod and "503NR-envoy.log" is log from envoy of 503 pod named spring-traffic-server-normal-5fbb954ff-w6ltl inside devops namespace.

Here is the 503 error and connection (connection number: C435069):
>2020-12-15T06:56:00.384594Z	debug	envoy conn_handler	[C435069] new connection
>2020-12-15T06:56:00.384634Z	debug	envoy http	[C435069] new stream
>2020-12-15T06:56:00.384688Z	debug	envoy http	[C435069][S6929987849631341900] request headers >complete (end_stream=true):
>':authority', 'huzhu-api.hz'
>':path', '/api/hz/order/v2.0/config-v1'
>':method', 'POST'
>'user-agent', 'curl/7.64.0'
>'accept', '*/*'
>
>2020-12-15T06:56:00.384696Z	debug	envoy http	[C435069][S6929987849631341900] request end stream
>2020-12-15T06:56:00.384782Z	debug	envoy filter	cannot find cluster outbound|80|normal|huzhu-api.hz.svc.maxwell.bj3
>2020-12-15T06:56:00.384798Z	debug	envoy router	[C435069][S6929987849631341900] unknown cluster 'outbound|80|normal|huzhu-api.hz.svc.maxwell.bj3'
>2020-12-15T06:56:00.384804Z	debug	envoy http	[C435069][S6929987849631341900] Sending local reply with details cluster_not_found
>2020-12-15T06:56:00.384834Z	debug	envoy http	[C435069][S6929987849631341900] encoding headers via codec (end_stream=true):
>':status', '503'
>'date', 'Tue, 15 Dec 2020 06:55:59 GMT'
>'server', 'envoy'

**Comment by swzhou** [comment]
By the way, I can see 503 NR happened at both the connecting stage, and the disconnecting stage, where envoy disconnect from the old istiod. I guess it might be the same issue.

**Comment by howardjohn** [comment]
Can you try 1.7.6 or 1.8? I think this may be fixed in https://github.com/istio/istio/pull/26918

**Comment by swzhou** [comment]
Thanks John.

Do you mean the full push happened at "2020-12-15T06:55:47.900311Z"?
>1522:2020-12-15T06:55:47.900311Z        info    ads     CDS: PUSH for node:spring-traffic-server-normal-5fbb954ff-w6ltl.devops clusters:2910 services:1189 version:2020-12-15T06:55:31Z/1

Meanwhile I can see 503 NR happened at 2020-12-15T06:56:00.384594Z, which is 12~13 seconds after the full push. But the requests right before / after [C435069] seem to be ok? 

> 2020-12-15T06:55:59.302357Z	debug	envoy conn_handler	[C435065] new connection //OK with PassthroughCluster
>2020-12-15T06:56:00.384594Z	debug	envoy conn_handler	[C435069] new connection  //503 NR
>2020-12-15T06:56:01.890979Z	        debug	envoy conn_handler       [C435071] new connection  //OK with outbound|80|normal|huzhu-api.hz.svc.maxwell.bj3

**Comment by swzhou** [comment]
@howardjohn 
Still can see the same 503 NR issue with Istiod 1.7.6,  and same "sending incomplete cluster" issue in istiod log.  :(
Here is my log: [log.zip](https://github.com/istio/istio/files/5728668/log.zip)

This is istiod log:
>2020-12-22T07:48:04.124772Z	info	ads	CDS: PUSH for node:sleep-79798987cc-6vc7r.default clusters:5 services:1 version:2020-12-22T07:48:01Z/0
>2020-12-22T07:48:15.727775Z	info	ads	CDS: PUSH for node:sleep-79798987cc-6vc7r.default clusters:2976 services:1214 version:2020-12-22T07:48:05Z/1

503 NR is for connection: C2965

**Comment by swzhou** [comment]
I test with: 
istiod 1.7.6 with istio-proxy 1.7.6
istiod 1.7.6 with istio-proxy 1.7.0
And can reproduce the issue on both cases.

**Comment by howardjohn** [comment]
Sorry to keep asking you to upgrade, but I suspect/hope this was fixed in https://github.com/istio/istio/pull/29872. It has the same symptoms

**Comment by swzhou** [comment]
> Sorry to keep asking you to upgrade, but I suspect/hope this was fixed in #29872. It has the same symptoms

I see. Which Istio version contains the fix #29872?

**Comment by howardjohn** [comment]
1.8.3, 1.9.0, and 1.7.8 (coming out in a couple days)

**Comment by swzhou** [comment]
> 1.8.3, 1.9.0, and 1.7.8 (coming out in a couple days)

I see 1.7.8 released. But could you confirm that it includes #29872? Cause I carefully reviewed the code in 1.7.8, and cannot find the code changed related to the fix.

**Comment by swzhou** [comment]
Also checked 1.8.3, similar result with 1.7.8.

**Comment by swzhou** [comment]
@howardjohn 
Hi John, is it possible to have #29872 into 1.8.x? Cause we are on Kubernetes 1.16, which is not officially support by Istio 1.9.x.

**Comment by swzhou** [comment]
> But the issue is clear, istiod is not sending full config at the start:
> 
> ```
> 1366:2020-12-15T06:55:24.483627Z        info    ads     CDS: PUSH for node:spring-traffic-server-normal-5fbb954ff-w6ltl.devops clusters:6 services:1 version:2020-12-15T06:55:20Z/0
> 1522:2020-12-15T06:55:47.900311Z        info    ads     CDS: PUSH for node:spring-traffic-server-normal-5fbb954ff-w6ltl.devops clusters:2910 services:1189 version:2020-12-15T06:55:31Z/1
> ```

Since It's not easy to upgrade to latest Istio 1.9, we finally figure out a workaround to overcome this. 
We delay the healthy status of  istiod to give it enough time to warmup before pushing config by set it's readinessProbe.initialDelaySeconds to 60 seconds:

```
readinessProbe:
    failureThreshold: 3
    httpGet:
       path: /ready
       port: 8080
       scheme: HTTP
    initialDelaySeconds: 60
    periodSeconds: 3
    successThreshold: 1
    timeoutSeconds: 5
```

Hope this helps.
