### ISSUE TITLE
Create e2e for Task "Setting Request Timeouts"

### ISSUE THREAD

**Issue by sebastienvas** [istio/istio#296]

**Comment by sakshigoel12** [comment]
We need something in istio/istio

**Comment by rshriram** [comment]
With the repo merge, I don't think these issues are valid anymore. All tests are in istio/istio. And We have tests for timeouts in pilot integration tests, that get checked on every PR.

**Comment by ayj** [comment]
Is this addressed by https://istio.io/docs/tasks/traffic-management-v1alpha3/request-timeouts.html?
