### ISSUE TITLE
'istioctl verify-install' should produce useful message against remote Istio control plane

### ISSUE THREAD

**Issue by esnible** [istio/istio#29607]
Current output, after following https://preliminary.istio.io/latest/docs/setup/additional-setup/external-controlplane/#set-up-the-remote-cluster

```
✔ ConfigMap: istio.external-istiod checked successfully
✔ ConfigMap: istio-sidecar-injector.external-istiod checked successfully
✔ MutatingWebhookConfiguration: istio-sidecar-injector-external-istiod.istio-system checked successfully
✔ IstioOperator: .external-istiod checked successfully
Checked 0 custom resource definitions
Checked 0 Istio Deployments
! No Istio installation found
Error: no Istio installation found
```

The message SHOULD say something like "Remotely managed Istio data plane found."

The command run here is `istioctl verify-install --context="${CTX_REMOTE_CLUSTER}" -d manifests -f remote-config-cluster.yaml`.  We run against a file rather than creating a "managed IOP" CR.  Suggestion: keep that CR on the remote cluster.

**Note**: the message for the MutatingWebhookConfiguration gives the namespaces, but these are not namespaced resources -- thus the message is incorrect.
**Note** The IstioOperator has no name, it appears as `.external-istiod`, and it was checked from the filesystem, not the cluster.

**Comment by esnible** [comment]
I also see output 

```
0 Istio control planes detected, checking --revision  only
Error: could not load IstioOperator from cluster: control plane revision "" not found.  Use --filename
```

Two problems with this.  First, it is checking revision `""`, and without the quotes it isn't clear.
Second, when Istio is installed remotely, we don't install an IOP.  I think we should, but this is a question for @sdake and @ostromart .  So we don't remember the options we installed with, and we do need a `--filename`.  That's correct.  But the instructions at https://preliminary.istio.io/latest/docs/setup/additional-setup/external-controlplane/#set-up-the-remote-cluster have the user do `istioctl manifest generate -f remote-config-cluster.yaml  | kubectl apply --context="${CTX_REMOTE_CLUSTER}" -f -` which does not leave a filename in the system.

**Comment by esnible** [comment]
@linsun @istio/wg-environments-maintainers @frankbu When Istio is managed by external Istiod, **users expect `istioctl verify-install` to work**.

I will ask on the next Environments meeting, but I wanted to offer a chance to discuss now.

We can't look for _istio-system_ namespace, as it won't exist.
We shouldn't look for _external-istiod_ namespace, as that name is in our docs but not in the code.

Should we
- A. Bless `external-istiod`, make it a constant, look there for ConfigMaps?
- B. Look for mutatingwebhookconfiguration labeled with `istio.io/rev`?
- C. Put an IOP representing the remote plane into the remote cluster, with the remote flags so _istioctl_ can figure out the situation?

I am included to go with B.

**Comment by howardjohn** [comment]
The only thing we really need in the external one is cluster wide resources (webhooks+CRDs). The current namespace scoped ones will all go away in the near future once we remove EnvoyFilter for telemetry and make kube-inject call the webhook directly
