### ISSUE TITLE
Istio 1.8 multicluster multi-primary different networks on-premise-->AWS does not work

### ISSUE THREAD

**Issue by btsitelashvili** [istio/istio#29605]
We installed istio-1.8 on on-premise bare metal servers (two clusters, one physical server per cluster), in addition with metalb to provide load balance with external IP, and "mutlicluster mult-primary on different networks" scenario worked out of the box

Then we tried to configure mesh between our on-premise and aws eks cluster using istio-1.8, and we have unidirectional connection, we have working mesh from AWS cluster to our on-premise, but not from our cluster to AWS

`(aws) besik@sm1n01:~$ istioctl proxy-config endpoint helloworld-v2-7855866d4f-4qwg4.sample | grep 5000`
`127.0.0.1:5000                   HEALTHY     OK                inbound|5000||`
`127.0.0.1:15000                  HEALTHY     OK                prometheus_stats`
`192.168.245.219:5000             HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local`
`84.xxx.xxx.201:15443               HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local`

this is aws endpoint, and I see injected route to our local cluster, 84.xxx.xxx.201:15443

`(1cluster) besik@sm1n01:~$ istioctl proxy-config endpoint helloworld-v1-5b75657f75-h8p8g.sample | grep 5000`
`10.42.49.146:5000                HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local`
`127.0.0.1:5000                   HEALTHY     OK                inbound|5000||`
`127.0.0.1:15000                  HEALTHY     OK                prometheus_stats`
`(1cluster) besik@sm1n01:~$`

This is our local cluster, with only one route to helloworld.service.

Any suggestions or may be any special requirements for that type of installation? I mean "on-premise"--"aws"?

Thanks in advance!

**Comment by fernandodelaiglesia** [comment]
Same here, but a my second cluster is deployed in Azure

```
(aws) $ istioctl --context="${CTX_CLUSTER2}" -n sample proxy-config endpoint sleep-8f795f47d-jdvpr --cluster "outbound|5000||helloworld.sample.svc.cluster.local"

ENDPOINT                 STATUS      OUTLIER CHECK     CLUSTER
10.0.2.55:5000           HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local
51.xxx.xxx.xxx:15443     HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local
```
I can see the injected endpoints to the local to aws cluster (10.0 ...) and the remote in azure load balancer

```
(azure) istioctl --context="${CTX_CLUSTER1}" -n sample proxy-config endpoint sleep-8f795f47d-48k2g --cluster "outbound|5000||helloworld.sample.svc.cluster.local"

ENDPOINT             STATUS      OUTLIER CHECK     CLUSTER
10.244.1.29:5000     HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local
```

But in the azure endpoint I can only see the local to azure endpoint (10.244...)

Any thing we shoud check?

Thanks

**Comment by raelix** [comment]
Try to check this https://github.com/istio/istio/issues/30345#issue-792453846. Are you using LoadBalancer type for istio-ingressgateway?

**Comment by stevenctl** [comment]
Is the AWS gateway backed by a LoadBalancer? And does it use IPs or a hostname? If it's using a hostname, you're probably running into #29359.

**Comment by fernandodelaiglesia** [comment]
Thanks a lot for the responses.

Following the instructions in the documentation, what I found is that the gateways in AWS are created as LoadBalancer and this use the AWS elastic load balancer (elb) and the gateway is configured with the DNS name provided by AWS. Following your answers, I see that the issue is that DNS is not well supported by now.

From the response from @stevenctl  I understand that a workarround would be to live edit the configmap/istio in istio-system to change the data.meshNetworks entries, is that correct?

I will check the istiod log and test the workarround upon my return to the office on Friday.

**Comment by stevenctl** [comment]
Editing the configMap isn't required. You can edit the Service and set `externalIPs`. The DNS name is not supported, you can resolve it yourself, understanding it will likely change.

**Comment by fernandodelaiglesia** [comment]
I tried to (live) edit the service `istio-eastwestgateway` to add the external IP to `status.LoadBalancer.ingress` in the AWS cluster , but as soon as I change it I get it, and realize that the `hostname` with the dns name of the AWS ELB is back again with no `ip` . So it is clear that I didn't understand what are you reffering to as "edit the service".

In the other side I followed the procedure described in the comment https://github.com/istio/istio/issues/29359#issuecomment-739258089 and it worked perfectly.

Thanks

**Comment by stevenctl** [comment]
Rather than editing the `.status.LoadBalancer`, which is controlled by AWS, edit `spec.externalIPs`:

https://kubernetes.io/docs/concepts/services-networking/service/#external-ips

**Comment by stevenctl** [comment]
There's a chance that isn't working until 1.9: https://github.com/istio/istio/pull/30059

**Comment by wojtek-viirtue** [comment]
@fernandodelaiglesia Thank you for pointing out https://github.com/istio/istio/issues/29359#issuecomment-739258089 It helped resolve my service discovery issue between an On Prem and GCP (non GKE) cluster that are both using NodePort services for eastwest ingress and it worked like a charm!

@stevenctl will the workaround using meshNetworks still be required after https://github.com/istio/istio/pull/30059 lands ?  It doesn't look like it made it into the 1.9.0-beta.1, so I wasn't able to confirm.  Much appreciated and thanks for all the great work!

**Comment by stevenctl** [comment]
I will try to make sure it gets into 1.9, the final code freeze is Monday.

**Comment by stevenctl** [comment]
By the way, that PR shouldn't be required unless you're using NodePort, it sounded like @fernandodelaiglesia was trying to edit the loadbalancer instead of the spec externalIP

**Comment by fernandodelaiglesia** [comment]
At first I was trying to edit the istio-eastwestgateway service (LoadBalancer)  (see mi comment https://github.com/istio/istio/issues/29605#issuecomment-769915425).

Because this didn't work I edited the configmap/istio as described in the  https://github.com/istio/istio/issues/29359#issuecomment-739258089
