### ISSUE TITLE
Troubleshooting FAQ for MySQL refers to removed authentication.istio.io/v1alpha1.Policy

### ISSUE THREAD

**Issue by lklkxcxc** [istio/istio#29601]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
Create policy ```no matches for kind "Policy" in version "authentication.istio.io/v1alpha1```
**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ X] Security

[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
client version: 1.7.2
control plane version: 1.7.2
data plane version: 1.7.2 (5 proxies)
Client Version: v1.16.4
Server Version: v1.16.4

**How was Istio installed?**
istioctl install

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by hzxuzhonghu** [comment]
I think Policy is deprecated

**Comment by lklkxcxc** [comment]
Here's what I did to solve the problem:
```
Error: Lost connection to MySQL server at 'handshake: reading inital communication packet', system error: 110
```
reference：
[https://istio.io/latest/faq/security/#mysql-with-mtls](url)

**Comment by hzxuzhonghu** [comment]
We should update it @yangminzhu

**Comment by morvencao** [comment]
@lklkxcxc You should use `PeerAuthentication` instead of `Policy`, because was removed.
See [PeerAuthentication](https://istio.io/latest/docs/reference/config/security/peer_authentication/)

**Comment by esnible** [comment]
cc @frankbu we should look for other instances of deprecated or removed Istio CRs in our docs.
