### ISSUE TITLE
Open existing Prometheus

### ISSUE THREAD

**Issue by alen-z** [istio/istio#29617]
**Describe the feature request**
Running `istioctl dashboard --namespace monitoring prometheus` opens existing Prometheus deployment and forwards appropriate Pod to `9090`.

**Describe alternatives you've considered**
1. We have Ingress for Prometheus and it's accessible on certain hostname, but this is not a solution.
2. I can manually `port-forward` — defies the purpose of using `istioctl`.

**Additional context**
Not all clusters use your Prometheus add-on deployment.

Issue is that we have multiple Pods with label `app=prometheus`, e.g. `pod/prometheus-node-exporter-2jgj5`. Searching for `component=server` could help locate the right Pod.

https://github.com/istio/istio/blob/622d9ededdb78e3dc07d5343b164d0d879fea133/istioctl/cmd/dashboard.go#L65

**Comment by howardjohn** [comment]
I am curious why you would prefer to use `istioctl dashboard` versus `port-forward`. In order for this to work, you would need to pass all the same info as `port-forward` -- we would basically be re-inventing port-forward

**Comment by alen-z** [comment]
My only argument here, maybe not obvious from the original post, is that there may already be Prometheus deployment on the cluster prior to Istio install. `istioctl` _may_ not support opening appropriate Prometheus in this case.

From my point of view `istioctl dashboard` is not needed at all, but if you were to support not only Prometheus deployed from your manifest, then it might be worth looking into how to connect to appropriate Prometheus instance :)
