### ISSUE TITLE
external istiod: pod injector incorrect if CNI settings are different between control plane and data plane

### ISSUE THREAD

**Issue by esnible** [istio/istio#29618]
I installed Istio in an external Istiod configuration following the instructions at https://preliminary.istio.io/latest/docs/setup/additional-setup/external-controlplane/

I chose to use OpenShift for my control plane so I made some modifications to the instructions based on what I read at https://istio.io/latest/docs/setup/platform-setup/openshift/ .  (This was just adding `--set profile=openshift` to install commands for the control plane and doing `oc adm policy add-scc-to-group anyuid ...`.)

Yet when I started the _helloworld_ pods they only reached `Init:Error` status.  The problem was that the injector created on the control plane expected CNI, and the data plane did not have it.

I did a manual `kubectl --context="${CTX_EXTERNAL_CLUSTER}" -n istio-system edit cm istio-sidecar-injector` and changed `istio_cni` `enabled` to `false`.  After doing that and recreating my helloworld pods they started successfully.

cc: @linsun

**Comment by linsun** [comment]
Thanks Ed, this is not surprising.  We haven't tested CNI with external control plane and we had to do extra work to get the default sidecar injector work for external istiod.

**Comment by howardjohn** [comment]
@linsun this is what I was talking about will cause issues by having the `istio-sidecar-injector` configmap in the remote cluster, which is used only by `istioctl kube-inject`. This is working as intended but misleading, and would be fixed by https://github.com/istio/istio/issues/29270. It also has nothing to do with CNI, and applies to any change to the injection template

**Comment by linsun** [comment]
@esnible a clarification question - were you having CNI enabled on the control plane cluster but not on the data plane cluster?  The fact you disable istio_cni on the data plane cluster is telling the cluster not to use the istio_cni's validation container thus the sidecar starts up fine.

I would expect CNI is not installed on the control plane cluster but should be installed on the data plane cluster.

**Comment by linsun** [comment]
@howardjohn thanks for the pointer!  You are right it would cause confusion.

To Ed's issue, I think istio CNI needs to be installed on the remote cluster (also data plane cluster here) because the deamonset needs to be there for configuring iptables and the validation stuff to work.

**Comment by howardjohn** [comment]
It's not just the daemonset, the injection template lives in the external istiod - that also needs to be configured. the same applies to any global injection customizations

**Comment by linsun** [comment]
Thanks @howardjohn. If the injection template cm lives in the same cluster as the injection webhook server, which is external istiod cluster, how would it get the cni enabled config?

**Comment by howardjohn** [comment]
The external istiod admin would configure it. Or you can configure it to read the template from their cluster, but ultimately there is exactly one place its controlled

**Comment by linsun** [comment]
You mean additional config by external istiod admin beyond what is installed?

The reason I'm bringing this up is to see if we should read injection template from config/remote cluster as the single source of truth.  This will aligns with what is configured on the config/remote cluster, e.g. cni enabled.

**Comment by howardjohn** [comment]
@linsun yes. Either external istiod cluster has the injection template, in which case they need to configure it as they see fit, or its read from the remote cluster. The same thing applies to mesh config. I think both are viable, depending on the use case.
