### ISSUE TITLE
support replacing iptables rules with ebpf in istio-cni 

### ISSUE THREAD

**Issue by xu1zhou** [istio/istio#29629]
**Describe the feature request**

**Describe alternatives you've considered**

[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**
    As I know by now, istio-CNI inserts iptables to redirect pod's traffic to sidecar envoy proxy without requiring Istio users to enable elevated Kubernetes RBAC permissions. 
   Replacing iptables with ebpf would get a better performance since it reduce memory copy from user side to kernel, and though it's been implemented in Cilium there still requirment for user who did't use cilium as their CNI provider and wan't to adopt ebpf to redirect traffic for better perfomance.

**Comment by howardjohn** [comment]
I would be interested to see real world benchmarks of iptables redirect vs ebpf.

I think the key consideration for this though is what percent of users that we can currently support with iptables can we support with ebpf (if 100%, great. If 50%, not great... I could imagine kernel versions and OS may play a bigger factor than iptables does today), and even more importantly how we can get the ORIGINAL_DST functionality _without requiring permissions in the sidecar_.

Going beyond that, we should explore if we can add value with ebpf, beyond just doing the same thing as we do with iptables today

**Comment by xu1zhou** [comment]
> I would be interested to see real world benchmarks of iptables redirect vs ebpf.

From Tencent's guys' [share](https://youtu.be/ILDiSDBenIA?t=670) (sorry, it's in Chinese).  it bring 5-8% improvement on latency.   Since that's roughly result, we plan to use cilium replace iptables  and have more detailed benchmarks.

> I think the key consideration for this though is what percent of users that we can currently support with iptables can we support with ebpf (if 100%, great. If 50%, not great... I could imagine kernel versions and OS may play a bigger factor than iptables does today), and even more importantly how we can get the ORIGINAL_DST functionality _without requiring permissions in the sidecar_.

Given kernel/OS upgrade is a hard work for many user, is that Ok for ebpf work as a alternative plan at 1st stage? leave decision to user to choose which backend implement(iptables/ebpf) to redirect their traffic.
Regarding permission in sidecar, we 're still working on it.
>

**Comment by howardjohn** [comment]
@xu1zhou is that 5% including the envoy overhead? if so that is pretty decent. If its 5% of raw iptables vs ebpf, which is ~0.1ms, that is likely to be small amount of improvement when we consider that adding envoy is already adding multiple ms.

> Regarding permission in sidecar, we 're still working on it.

Do you have any details? The video looks very interesting but I do not speak chinese

**Comment by howardjohn** [comment]
https://juejin.cn/post/6864490027817779207 + google translate seemed to give some good info

**Comment by xu1zhou** [comment]
> https://juejin.cn/post/6864490027817779207 + google translate seemed to give some good info

@howardjohn  yeah, I think you got the right artical which sumerized the points of video.  though it still in Chinese.

>  is that 5% including the envoy overhead? if so that is pretty decent. If its 5% of raw iptables vs ebpf, which is ~0.1ms, that is likely to be small amount of improvement when we consider that adding envoy is already adding multiple ms.

I've checked with a colleague who also involved in that project , the envoy overhead are included.

**Comment by howardjohn** [comment]
Ok great. It sounds like this has already been implemented, at least for testing. Are you planning to bring that implementation to open source or contribute this feature?

**Comment by xu1zhou** [comment]
> Ok great. It sounds like this has already been implemented, at least for testing. 

@howardjohn Regarding implemented, We(Intel) cooperate with Tencent on this feature, and it was implemented by Tencent team as an iternal feature. So there still much things to figure out: like ebpf part it's design to work as a DeamonSet instead of CNI in current implement.

> Are you planning to bring that implementation to open source or contribute this feature?
Yeah, That's what we are working on now.

**Comment by cuirunxing-hub** [comment]
If there is any progress of istio-ebpf-cni ? we are planning use cilium in our k8s platform, also want to join the conribute of istio-ebpf-cni.

**Comment by kebe7jun** [comment]
Hi, I have implemented a solution using eBPF instead of iptables, which is perfectly compatible with the community version of Istio, as @xu1zhou said, which is also implemented through DaemonSet. The code is at https://github.com/merbridge/merbridge, and I look forward to discussing it with the community.

**Comment by unicell** [comment]
@kebe7jun Any updates since your last comment, regarding this ticket? Noticed that `merbridge` is on recent Istio blog[1] and there's an update in project's ROADMAP.md[2].

Specifically, could you share if there's a plan to integrate it back to Istio or it'll continue to serve as standalone project?

[1]: https://istio.io/latest/blog/2022/merbridge/
[2]: https://github.com/merbridge/merbridge/blob/main/ROADMAP.md

**Comment by kebe7jun** [comment]
@unicell  Thank you for your interest. We are discussing and confirming the possibility of using Merbridge as an Istio CNI, for now if you wish to try it out you can simply follow the current installation method and try it out, for now we recommend leaving Merbridge working in compatibility mode (default mode) which will make the system more stable.
