### ISSUE TITLE
istio operator CR installation with custom manifests/charts

### ISSUE THREAD

**Issue by patrickppeng** [istio/istio#29620]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
I tried to rebuild the istio-operator image with custom manifests but it didn't pick up the changes in the charts. There is no documentation available in this area of how to replace the compiled-in charts for operator CR installation. Is "overlay" the only mechanism to override the k8s resource in the complied-in charts with operator CR installation? 

[x] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Be able to customize manifests/charts by rebuilding operator image.

**Steps to reproduce the bug**
- download the Istio source code
- modify charts under /root/go/src/istio.io/istio/manifests/charts
- rebuild operator image
```
# BASE_DISTRIBUTION is used to switch between the old base distribution and distroless base images
ARG BASE_DISTRIBUTION=default

# Version is the base image version from the TLD Makefile
ARG BASE_VERSION=latest

# The following section is used as base image if BASE_DISTRIBUTION=default
FROM gcr.io/istio-release/base:${BASE_VERSION} as default

# The following section is used as base image if BASE_DISTRIBUTION=distroless
FROM gcr.io/istio-release/distroless:${BASE_VERSION} as distroless

# This will build the final image based on either default or distroless from above
# hadolint ignore=DL3006
FROM ${BASE_DISTRIBUTION}

# install operator binary
COPY operator /usr/local/bin/

# add operator manifests
COPY manifests/ /var/lib/istio/manifests/

USER 1337:1337

ENTRYPOINT ["/usr/local/bin/operator"]
```
- assume the custom manifest directory should be copied into the new operator image
- deploy operator with the new image
- still see the default k8s resources after installed charts with operator CR

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
istio - 1.8.0
helm - 3.2.1
k8s - 1.17.9

**How was Istio installed?**
istio operator CR

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by morvencao** [comment]
If you're try to install istio with istioctl, you can select external charts, set the `manifests` flag to a local file system path:
```
$ istioctl install --manifests=manifests/
```

See: https://istio.io/latest/docs/setup/install/istioctl/#install-from-external-charts

If you're using in-cluster operator, you can try to set external charts(mount hostpath for the customized chart to istio operator pod) in the istio operator CR with:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: iop-example
spec:
  installPackagePath: <chart-path-in-operator-pod>
```
