### ISSUE TITLE
SSL termination at ingress gateway requires custom headers - Istio 1.7.4

### ISSUE THREAD

**Issue by abbas-hue** [istio/istio#29631]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

Need to configure custom headers for ingress gateway, similar to this example from nginx:

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-console-tls
  namespace: weblogic-domain
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_clear_input_headers "WL-Proxy-Client-IP" "WL-Proxy-SSL";
      more_set_input_headers "X-Forwarded-Proto: https";
      more_set_input_headers "WL-Proxy-SSL: true";
    nginx.ingress.kubernetes.io/ingress.allow-http: "false"

How does one go about doing this in Istio 1.7.4?

[ ] Docs
[ ] Installation
[ X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

HTTP > HTTPS redirection is not working properly because custom headers are not being passed.

**Steps to reproduce the bug**

Configure the following gateway:

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: foo
  namespace: my-domain-namespace
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
     tls:
       httpsRedirect: true
    hosts:
    - "dev-admin.xyz.com"
  - port:
      number: 443
      name: https
      protocol: HTTP
    hosts:
    - "dev-admin.xyz.com"

http://dev-admin.xyz.com/console properly redirects to https://dev-admin.xyz.com/console, but the application authentication mechanism breaks because the following headers are not being passed:

"X-Forwarded-Proto: https";
"WL-Proxy-SSL: true";

We need to configure the equivalent of this nginx example;

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-console-tls
  namespace: weblogic-domain
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_clear_input_headers "WL-Proxy-Client-IP" "WL-Proxy-SSL";
      more_set_input_headers "X-Forwarded-Proto: https";
      more_set_input_headers "WL-Proxy-SSL: true";
    nginx.ingress.kubernetes.io/ingress.allow-http: "false"

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

[buildusr@ip-10-162-45-231 istio]$ istioctl version
client version: 1.7.4
control plane version: 1.7.5
data plane version: 1.7.5 (5 proxies), 1.6.8 (1 proxies)
[buildusr@ip-10-162-45-231 istio]$

**How was Istio installed?**

istioctl install -f /var/tmp/istio_overlay.yml --set meshConfig.accessLogFile=/dev/stdout --set values.global.proxy.logLevel=debug

**Environment where the bug was observed (cloud vendor, OS, etc)**

Amazon EKS

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
I don't think envoy supports this

**Comment by howardjohn** [comment]
Sorry totally read this wrong - seems like this can be accomplished with VirtualService header rules? https://istio.io/latest/docs/reference/config/networking/virtual-service/#Headers-HeaderOperations

**Comment by howardjohn** [comment]
Closing as this has been answered
