### ISSUE TITLE
Operator prunes too much a named and unnamed IOP

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#29633]
If I install two IOPs, one like
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: install
spec: {}
```

and one

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec: {}
```

The second will prune the first.

I think it should only prune resources where name is explicitly ""; essentially treating missing name as `""` instead of a special case.

This would likely involve either enhancing the selector here: https://github.com/istio/istio/blob/443c1df1ec77e52d4a0f5ee60ab4f96837207c2e/operator/pkg/helmreconciler/prune.go#L305

or always writing the name label even if its empty

**Comment by howardjohn** [comment]
We made this mistake in our tests: https://github.com/istio/istio/pull/29634, so probably pretty common

cc @ostromart, curious on your opinion

**Comment by morvencao** [comment]
IN 

> If I install two IOPs, one like
> 
> ```
> apiVersion: install.istio.io/v1alpha1
> kind: IstioOperator
> metadata:
>   name: install
> spec: {}
> ```
> 
> and one
> 
> ```
> apiVersion: install.istio.io/v1alpha1
> kind: IstioOperator
> spec: {}
> ```
> 
> The second will prune the first.
> 
> I think it should only prune resources where name is explicitly ""; essentially treating missing name as `""` instead of a special case.
> 
> This would likely involve either enhancing the selector here:
> 
> https://github.com/istio/istio/blob/443c1df1ec77e52d4a0f5ee60ab4f96837207c2e/operator/pkg/helmreconciler/prune.go#L305
> 
> or always writing the name label even if its empty

In this case, if we add labels for the empty CrName and CrNamespace, the operator will also override, not prune the istio resources, because there is no revision specified, so the resource names are identical for both IOPs.

**Comment by howardjohn** [comment]
the use case is to have gateway defined in separate iop

**Comment by morvencao** [comment]
Yes, separate gateway case works the fix, because there are no istio resources with same names for different IOPs.
