### ISSUE TITLE
DNS Proxy captures traffic to port 53 from all containers in the POD

### ISSUE THREAD

**Issue by ramaraochavali** [istio/istio#29639]
When DNS Proxy is enabled,  it sets up iptable rule to capture outgoing traffic to port 53. This creates problems if there are other init containers that gets executed after istio init, the DNS queries would be routed to DNS proxy and if proxy is not yet ready by that time, the init container fails to connect to DNS server and crashes.  Ideally we should only capture port 53 traffic originating from proxy and app - not all containers in the POD as the DNS traffic for other containers may not be intended to go via Proxy.

[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Comment by ramaraochavali** [comment]
@howardjohn @hzxuzhonghu created this issue as discussed. Please add any additional details if I missed

**Comment by howardjohn** [comment]
This seems like just a specialized form of https://github.com/istio/istio/issues/11130. Once that is resolved, this will as well.

In the short term, there isn't much we can do. We cannot distinguish the app from the init containers. Istio init container is expected to be run last for this reason, if you really need to bypass it you can run the init container as UID 1337 (like https://istio.io/latest/docs/setup/additional-setup/cni/#compatibility-with-application-init-containers).

It also seems pretty niche to have an init container that runs after istio-init and requires DNS but does not require any other TCP traffic?

**Comment by ramaraochavali** [comment]
Yeah running that initcontainer as UID 1337 does solve the problem and that is what we are doing :-) . I will close this
