### ISSUE TITLE
panic: not reached in test

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#29635]
https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/29621/integ-security-multicluster-tests_istio/1338703682866253824/artifacts/security-ef93a509646a40f2a8f953/TestReachability/_test_context/test-ns1-2-95325-state892005038/cluster-0/b-v1-5c577469d4-9nv6p_istio-proxy.previous.log

seems in response to xds

**Comment by howardjohn** [comment]
same test, same Service in another cluster at the same time: https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/29621/integ-security-multicluster-tests_istio/1338703682866253824/artifacts/security-ef93a509646a40f2a8f953/_suite_context/test-ns1-2-95325-state-173273657/cluster-4/b-v1-66bd576684-fc2ft_istio-proxy.previous.log

**Comment by howardjohn** [comment]
Address (0x53900000011) is nearly identical to address in  (0x53900000010) https://github.com/istio/istio/issues/27664

**Comment by howardjohn** [comment]
https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/30638/integ-security-multicluster-tests_istio/1357076861082931200/artifacts/security-e0fe1529c3c14d99a11597/_suite_context/test-ns1-2-81380-state-547277103/remote/b-v1-58bf85ddd7-xpfkk_istio-proxy.previous.log

Ran this one with a debug build

**Comment by howardjohn** [comment]
https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/30638/integ-pilot-k8s-tests_istio/1357133224668565504/artifacts/pilot-f455d7b6476d4647b6de7a246/_suite_context/echo-1-28259-state-377749702/cluster-0/c-v1-69494bd86f-4pf7v_istio-proxy.previous.log another in debug build

**Comment by howardjohn** [comment]
@lambdai any way we can get a line number on where this occurs? seems pretty easy to reproduce with a debug build

**Comment by stevenctl** [comment]
PR: #30705 

https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/30705/integ-security-multicluster-tests_istio/1358895282598711296/artifacts/security-3775aefc404646cfb697d3/_suite_context/test-ns1-2-84240-state-049466007/primary/a-v1-5dfd8bffc4-r2snj_istio-proxy.previous.log

**Comment by howardjohn** [comment]
Got another one despite Yuchen's PR: https://storage.googleapis.com/istio-prow/logs/integ-security-multicluster-tests_istio_postsubmit/1371524278876377088/artifacts/security-827c81d4fc794e7a9c771f/TestReachability/_test_context/test-ns1-2-96521-state100189951/remote/b-v1-6bc4588967-dm6tj_istio-proxy.previous.log. Will try to repro in debug image tests

**Comment by howardjohn** [comment]
ok got a few at external/envoy/source/server/connection_handler_impl.cc:110

https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/30638/integ-security-multicluster-tests_istio/1369343769379344384/artifacts/security-mtls-first-party-jwt-7/_suite_context/test-ns1-1-7932-state-114255896/cross-network-primary/multiversion-vistio-fd7c7c5f5-tgkrj_istio-proxy.previous.log
https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/30638/integ-security-multicluster-tests_istio/1369343769379344384/artifacts/security-mtls-first-party-jwt-7/_suite_context/test-ns1-1-7932-state-114255896/cross-network-primary/headless-v1-7df945d785-fjbc6_istio-proxy.previous.log
https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/30638/integ-security-multicluster-tests_istio/1369343769379344384/artifacts/security-mtls-first-party-jwt-7/_suite_context/test-ns1-1-7932-state-114255896/cross-network-primary/c-v1-676549f87f-cmtwx_istio-proxy.previous.log

**Comment by lambdai** [comment]
I will work on this along with https://github.com/envoyproxy/envoy/issues/15126

**Comment by howardjohn** [comment]
@lambdai the issue is closed but we still see this. Is that expected?

**Comment by lambdai** [comment]
no clue yet…

**Comment by howardjohn** [comment]
This is still occurring regularly: https://prow.istio.io/view/gs/istio-prow/logs/integ-security-multicluster-tests_istio_postsubmit/1384236403688214528

**Comment by howardjohn** [comment]
I am fairly sure this was fixed this week.
