### ISSUE TITLE
Request config to inject the SSL certificate into envoy proxy and perform the SSL termination in sidecar level

### ISSUE THREAD

**Issue by manmaujin2** [istio/istio#29657]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
In order to perform the traffic management in pod to pod level and we would like to perform SSL Term in application sidecar. Current envoy proxy has documents mention that can define the cert location in envoy container through EnvoyFilter resource. However, I have no idea how to inject the cert into envoy when the container created and is there any parameter need define in ConfigMap ? If not, is it possible to provide some place to setup ? 

_Here is the document in envoy proxy to config cert location into sidecar:_
https://www.envoyproxy.io/docs/envoy/latest/start/quick-start/securing

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ X ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
This is not currently supported

**Comment by manmaujin2** [comment]
Hi , here I found the article mention how to perform SSL Term in envoy proxy. Is it allow to perform the custom envoy proxy config and enable the SSL ?

https://github.com/istio/istio/issues/21368

https://www.linkedin.com/pulse/end-in-transit-encryption-microservices-aws-eks-istio-rahul-natarajan?articleId=6663447775486840832

**Comment by howardjohn** [comment]
Can we keep discussion in https://github.com/istio/istio/issues/21368 which is the same feature request and has previous discussion and potential workarounds
