### ISSUE TITLE
istiod should be start if mcp-xds-server not start

### ISSUE THREAD

**Issue by du2016** [istio/istio#29656]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

if the mcp-xds-server is not start,the istiod will return err and exit,i think istiod should be start whenever mcp-xds-server  is start or not

**Describe alternatives you've considered**

log an error and continue start 

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by howardjohn** [comment]
If we start without the config we may end up not sending RBAC configs (security bypass) or traffic rules (break traffic). I don't think fail open is a safe mechanism for config discovery

**Comment by hzxuzhonghu** [comment]
Agree, we donot want to make things complicated during bootstrap.

**Comment by du2016** [comment]
OK,i have understand, thanks
