### ISSUE TITLE
envoy metric, port 15090 stays not available for 2 mins

### ISSUE THREAD

**Issue by lut777** [istio/istio#29658]
**Bug description**

I tried new DNS CAPTURE feature based on /manifests/profile/preview from blog https://istio.io/latest/blog/2020/dns-proxy/

After I change telemetry:v2:metadataExchange:wasmEnabled to "true", situation changes.
Pod stays not running because envoy is not ready.
envoy is not ready because 15090 is not ready as following. 
`2020-12-16T09:53:37.416278Z	error	failed scraping envoy metrics: error scraping http://localhost:15090/stats/prometheus: Get "http://localhost:15090/stats/prometheus": dial tcp 127.0.0.1:15090: connect: connection refused`

I checked out port listening status after rebooting a pod. 
The result shows that 15000/15020 is listened at the beginning. However, port 15006/15021/15090 is not listened until 2+ mins later.
This result leads to a unready envoy for 2+ mins, which furthermore leads to a unavailable service for 2+ mins.

[ ] User Experience

**Expected behavior**
Pod should be ready in few seconds.

**Steps to reproduce the bug**
Change istiooeprator configuration as /manifests/profile/preview shows.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
istio 1.8.1

**How was Istio installed?**
istio operator

**Environment where the bug was observed (cloud vendor, OS, etc)**
ubuntu 18.04 bionic
k8s 1.18.12

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
This is not a bug, but a pretty bad experience.

**Comment by howardjohn** [comment]
Can you turn on debug logs in envoy and post them here from startup? https://github.com/istio/istio/wiki/Troubleshooting-Istio

**Comment by mandarjog** [comment]
@lut777 This is *only* happening when you turn on Wasm, is that correct? How much CPU is allocated to the proxy?

@bianpengyuan @kyessenov This sounds like the initial cpu spike while loading wasm module. Do we expect to see the problem in 1.8?

**Comment by kyessenov** [comment]
It could be under-provisioned CPU. Maybe bump up limits on istio-proxy and see if that helps?

**Comment by lut777** [comment]
@mandarjog correct. I did not mention it because I'm not pretty sure.
@howardjohn I list the log, and there are 550000+ lines in log files. I'm not pretty sure U want to read it.
@kyessenov I am trying it now.

**Comment by lut777** [comment]
@mandarjog @kyessenov I checked out the IstioOperator, the default resources limit for CPU is 2000m. I think this is already a very large number now...
I will give proxy more limit CPU and observe the result. However, even it works, I will consider it an inelegant solution.

**Comment by bianpengyuan** [comment]
The default requested CPU is pretty low I think? Could you increase that and try again? Just to make sure that we get enough CPU on the node.

I think 2.5 mins is much longer than what I have observed before. My memory is very vague but I think it was around 1 min. However no matter it is one minute or more than two minutes, I agree this is definitely a bad experience and needs improvement. We have not yet focused much on improving performance of Wasm extensions. Long loading time is definitely one thing we need to track, measure, and try to improve over time.

**Comment by lut777** [comment]
@bianpengyuan I change request CPU to 1000m, stil 2mins+. I also increase request memory to 1024Mi, and nothing changed.
The cluster I am in is with thousands of pods/svcs and hundreds of serviceentries. I hope this information may be helpful. 
I do like this dns capture idea, but it seems like it is not prepared. (illidan face)

**Comment by bianpengyuan** [comment]
> I do like this dns capture idea, but seems like it is not prepared.

@lut777 DNS capture feature is not coupled with Wasm enablement. Not sure if it was Wasm that makes you think DNS capture is `not prepared`. If it was something else, probably open another issue and track that?

**Comment by howardjohn** [comment]
One possibility is DNS is making envoy STRICT_DNS clusters fail to warm,
blocking startup. This is why I was hoping to see logs, as it would show
this.

**Comment by lut777** [comment]
@howardjohn I read half of the logs and find that the logs record the initialization of the envoy configuration for almost 2 minutes...I think you can read more details from the logs. So would you be interested in reading it?
Considering the privacy issue, can you give me a channel to send the file?

**Comment by kyessenov** [comment]
Did we narrow it down to DNS?
