### ISSUE TITLE
Unable to delete SMMR after deleting the SMCP

### ISSUE THREAD

**Issue by tommeramber** [istio/istio#29662]
I wanted to clean my project so I deleted the SMCP before I deleted the SMMR,
Then I tried to delete the SMMR but I wasn't able to, I also tried to delete the operator, re-install it, create new SMCP, and check the status of the SMMR but it still presents "ErrSMCPMissing" and I'm unable to delete it - the same outcome for force deletion which didn't work.  

$ oc get smcp
NAME    READY   STATUS            PROFILES      VERSION   AGE
basic   9/9     ComponentsReady   ["default"]   2.0.0.2   15m
$ oc get smmr
NAME      READY   STATUS           AGE
default   0/1     ErrSMCPMissing   47h
$ oc delete smmr default
servicemeshmemberroll.maistra.io "default" deleted
^C
$ oc delete smmr default --force --grace-period=0
warning: Immediate deletion does not wait for confirmation that the running resource has been terminated. The resource may continue to run on the cluster indefinitely.
servicemeshmemberroll.maistra.io "default" force deleted
^C
$ oc get smmr
NAME      READY   STATUS           AGE
default   0/1     ErrSMCPMissing   47h

**Comment by howardjohn** [comment]
Please open in maistra support, these are not a part of istio organization.
