### ISSUE TITLE
profile diff cannot compare two profiles directly unless `--manifests manifests` is set

### ISSUE THREAD

**Issue by carolynhu** [istio/istio#29677]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
The correct/workable usages of profile diff from a downloaded istio release are:
(1)
```
istioctl profile diff preview default
```
(2)
```
istioctl profile diff --manifests manifests default.yaml demo.yaml
```

but when I following the istio.io instruction: https://istio.io/latest/docs/reference/commands/istioctl/#istioctl-profile-diff which says, this command can compare two profiles yaml directly by passing them to the args, which is not working:

when i run:
```
istioctl profile diff manifests/profiles/default.yaml manifests/profiles/demo.yaml
```
it returns:
```
Error: could not read "manifests/profiles/default.yaml": Asset profiles/manifests/profiles/default.yaml.yaml not found
```

We should fix possible bugs here and add an explanation in the flags help text for this command to make it clear to the users also developers.

cc @ostromart @esnible @howardjohn 

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by morvencao** [comment]
Agreed, it is not easy for end-users to figure out how does the `profile diff` look for the path of profiles.

**Comment by esnible** [comment]
@morvencao End users don't have this problem.  This is a problem of personal builds.
