### ISSUE TITLE
dns response size is larger from dns proxy

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#29675]
With proxy:
```
/ # dig +tcp google.com A

; <<>> DiG 9.14.12 <<>> +tcp google.com A
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 10781
;; flags: qr rd ra; QUERY: 1, ANSWER: 6, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;google.com.                    IN      A

;; ANSWER SECTION:
google.com.             299     IN      A       172.217.212.100
google.com.             299     IN      A       172.217.212.102
google.com.             299     IN      A       172.217.212.139
google.com.             299     IN      A       172.217.212.138
google.com.             299     IN      A       172.217.212.113
google.com.             299     IN      A       172.217.212.101

;; Query time: 4 msec
;; SERVER: 10.40.0.10#53(10.40.0.10)
;; WHEN: Thu Dec 17 03:12:43 UTC 2020
;; MSG SIZE  rcvd: 195

```

Without proxy
```
/ # dig +tcp google.com A

; <<>> DiG 9.14.12 <<>> +tcp google.com A
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 44604
;; flags: qr rd ra; QUERY: 1, ANSWER: 6, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;google.com.                    IN      A

;; ANSWER SECTION:
google.com.             299     IN      A       142.250.1.139
google.com.             299     IN      A       142.250.1.101
google.com.             299     IN      A       142.250.1.138
google.com.             299     IN      A       142.250.1.113
google.com.             299     IN      A       142.250.1.102
google.com.             299     IN      A       142.250.1.100

;; Query time: 5 msec
;; SERVER: 10.40.0.10#53(10.40.0.10)
;; WHEN: Thu Dec 17 03:12:38 UTC 2020
;; MSG SIZE  rcvd: 135
```

Note sure why the MSG SIZE is 60 bytes larger in the proxy

**Comment by zenvdeluca** [comment]
I believe I'm being affected by this and is causing some resolution issues from golang resolvers

```
panic: dial tcp: lookup custom-name0001.query.consul on 169.254.1.1:53: cannot unmarshal DNS message
goroutine 16 [running]:
gopkg.in/DataDog/dd-trace-go.v1/contrib/jmoiron/sqlx.MustConnect(...)
```

**Comment by howardjohn** [comment]
@zenvdeluca any more info on how to reproduce this? I guess try sqlx? I am surprised they cannot even marshal the response..

**Comment by howardjohn** [comment]
Oh this is just plain go resolver.. hm. Can you run dig on that address so we can see the raw response? of set dns:debug log level in agent will dump all requests

**Comment by howardjohn** [comment]
https://github.com/golang/go/issues/10622 might be related

**Comment by zenvdeluca** [comment]
To get you the big picture of the dns flow. This pod uses the node (169.254.1.1) as resolver.  The particular query failing ultimately gets forward from the node to our consul cluster, which then replies with an alias for an AWS managed service name, which is also a CNAME to the final A record.  

```$ dig custom-name0001.query.consul

; <<>> DiG 9.16.11 <<>> custom-name0001.query.consul
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 27377
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 967f33a2aaa5960e (echoed)
;; QUESTION SECTION:
;custom-name0001.query.consul. IN A

;; ANSWER SECTION:
custom-name0001.query.consul. 5 IN CNAME custom-name0001-db-dbcluster-<redacted>.cluster-ro-<redacted>.us-west-2.rds.amazonaws.com.
custom-name0001-db-dbcluster-<redacted>.cluster-ro-<redacted>.us-west-2.rds.amazonaws.com. 5 IN CNAME custom-name0001-db-1.<redacted>.us-west-2.rds.amazonaws.com.
custom-name0001-db-1.<redacted>.us-west-2.rds.amazonaws.com. 5 IN A 172.16.100.178

;; Query time: 100 msec
;; SERVER: 169.254.1.1#53(169.254.1.1)
;; WHEN: Wed Mar 03 02:20:04 UTC 2021
;; MSG SIZE  rcvd: 541
```

**Comment by howardjohn** [comment]
Just to make sure, are you enabling https://preliminary.istio.io/latest/docs/ops/configuration/traffic-management/dns-proxy/? since it's off by default

**Comment by zenvdeluca** [comment]
correct, I have the dns proxy globally enabled for all istio-proxy sidecars.  there is an iptables rule forwarding to the local dns proxy process in 15053

**Comment by howardjohn** [comment]
Ok thanks for all the info, I'll dig into this tomorrow

**Comment by howardjohn** [comment]
I can no longer reproduce the original issue of different size on `master`. Any chance you can do the dig request with and without the proxy to compare?

**Comment by zenvdeluca** [comment]
on it. let me see if I can spot any difference and will chime in asap

**Comment by howardjohn** [comment]
I also tried a go 1.11 client and didn't see the same issue as the linked bug above so probably not related (`curl -LO https://storage.googleapis.com/howardjohn/tmp/dns3; chmod +x ./dns3; ./dns3`)

**Comment by zenvdeluca** [comment]
I noticed in my case all the reported DNS failures with the sidecar+dnsproxy are related to .consul names. 
I found this issue which seems vaguely related https://github.com/golang/go/issues/11070

without the istio sidecar, those queries are landing in a coredns resolver which forwards to our consul clusters and replies back to the k8s pods successfully.  issue happens when we add the dnsproxy in the path. I noticed not only CNAME, but also SRV and other large TCP replies are failing and isn't intermittent but a hard crash where the pod can't resolve

**Comment by howardjohn** [comment]
I definitely think its about compression, something like we are straddling the 512 byte limit and on one side compress and the other side uncompressed causing issues?

**Comment by zenvdeluca** [comment]
> I definitely think its about compression, something like we are straddling the 512 byte limit and on one side compress and the other side uncompressed causing issues?

that would explain.  let me work on getting those dig with/without sidecar

**Comment by zenvdeluca** [comment]
@howardjohn check your slack on istio from vicente de luca :)

**Comment by howardjohn** [comment]
Update - I learned a lot about DNS today.

Easy reproducer: `curl -LOs https://storage.googleapis.com/howardjohn/tmp/dns5; chmod +x ./dns5; ./dns5` queries `dns.howardjohn.info.` which returns a big TXT response. Built with go 1.11.

Minimal fix that gets it working:
```
diff --git a/pilot/pkg/dns/dns.go b/pilot/pkg/dns/dns.go
index a516f43cf1..8dd19b690f 100644
--- a/pilot/pkg/dns/dns.go
+++ b/pilot/pkg/dns/dns.go
@@ -206,6 +206,7 @@ func (h *LocalDNSServer) ServeDNS(proxy *dnsProxy, w dns.ResponseWriter, req *dn
                // We did not find the host in our internal cache. Query upstream and return the response as is.
                response = h.queryUpstream(proxy.upstreamClient, req)
        }
+       response.Compress = true
        roundRobinResponse(response)
        _ = w.WriteMsg(response)
```

Open question: should we *always* compress? seems like it depends on the request.

One confusing thing is in coredns 1.7, requests are truncated without tc flag. In 1.8, they are a bit odd behavior: https://github.com/coredns/coredns/issues/4502. Need to see response to this to fully understand I think.
