### ISSUE TITLE
manifest diff command is broken

### ISSUE THREAD

**Issue by carolynhu** [istio/istio#29676]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

when i run:

```
manifest diff preview.yaml default.yaml
```

it outputs: `Manifests are identical` which should not.

Need to give a fix on this bug, also, need to improve istio.io istioctl manifest diff section to make the diff usage clear to the user.

cc @ostromart @esnible @howardjohn

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by morvencao** [comment]
@carolynhu Have you tried `istioctl profile diff default preview`? `istioctl manifest diff` is used to check the istio manifests differences.

**Comment by carolynhu** [comment]
- `istioctl profile diff default preview`
this works, but i just filed another issue related to this for other issues i found.

- istioctl manifest diff is used to check the manifests differences.
it should also able to compare profile yaml as well

**Comment by esnible** [comment]
Can confirm:

```
istioctl manifest diff ./manifests/profiles/preview.yaml ./manifests/profiles/default.yaml 
Manifests are identical
```

@ostromart What should it output?  "✘ These are not manifests!" ?  Or should it compare `install.istio.io/v1alpha1/IstioOperator`s and output the differences between them?

**Comment by morvencao** [comment]
```
istioctl manifest diff ./manifests/profiles/preview.yaml ./manifests/profiles/default.yaml 
Manifests are identical
```

In this case, the resource name is missing, see: https://github.com/istio/istio/blob/master/manifests/profiles/default.yaml#L1-L4
+1 to report error similar to `These are not manifests!"` and tell the end user which field is missing.

**Comment by esnible** [comment]
@ostromart Please reconsider https://github.com/istio/istio/pull/31241

In the context of Istio manifests, two non-manifest files should not be equal.
