### ISSUE TITLE
Will too many listeners and routes affect performance?

### ISSUE THREAD

**Issue by dotbalo** [istio/istio#29684]
**Describe the feature request**
I have a k8s cluster with about 500 services, and then I use istio to manage a project. But I checked the listener and route of a Pod through istioctl pc listener and istio pc route, and found that this Pod has a large number of listeners and routes, including services of other namespaces. I am worried that too many listeners and routes will affect the performance of Envoy, so I changed the defaultServiceExportTo, defaultDestinationRuleExportTo, and defaultVirtualServiceExportTo to ".". Although the listener and route are only services under the current namespace, all the gateways I configured have become 404. , Because the Pod of ingressgateway does not have the route and endpoint of other namespaces.
So I changed the Service and exporterTo of VS under the namespace with "Auto Injection" turned on to "*", but at this time, A Namespace will also have listener and route configuration information of B Namespace. Is there any way to make Envoy of A Namespace not configure the listener and route of B namespace?

**Describe alternatives you've considered**
Change defaultServiceExportTo, defaultDestinationRuleExportTo and defaultVirtualServiceExportTo to ".", and change the service and vs that need to be managed by istio to "*".

[ ] Docs
[ ] Installation
[x] Networking
[x] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**
istio version: 1.8.0
Kubernetes version: 1.19.4
I want to know whether too many listeners and routes will affect the performance of Envoy. I also want to know how to block the listener and route between namespaces without affecting the Gateway.

**Comment by ramaraochavali** [comment]
Is this a generic concern or did you observe any specific performance issue because of many listeners/routes?

**Comment by dotbalo** [comment]
In fact, I haven't done a stress test, but I saw that there are many routes and listeners that will take up extra memory, so I want to ask if there are any relevant configurations that can block the listener and route between the namespaces, because it is completely useless.

**Comment by ramaraochavali** [comment]
Ok. Please refer to https://istio.io/latest/docs/concepts/traffic-management/#sidecars that allows you to restrict the config that a workload sees.

**Comment by dotbalo** [comment]
@ramaraochavali Thank you so much for your answer. I will try it, thank you very much.
