### ISSUE TITLE
various telemetry dashboard test flakes

### ISSUE THREAD

**Issue by stevenctl** [istio/istio#29695]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/29691/integ-telemetry-k8s-tests_istio/1339647449660133376
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/29646/integ-telemetry-k8s-tests_istio/1339601140550995968
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/29673/integ-telemetry-k8s-tests_istio/1339527372537335808
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/29650/integ-telemetry-k8s-tests_istio/1339253586072178688
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/29604/integ-telemetry-k8s-tests_istio/1339186291442454528

**Comment by howardjohn** [comment]
https://github.com/istio/istio/pull/29646 fixes it

**Comment by howardjohn** [comment]
Well maybe it doesn't fix it, looks like it flaked on that PR as well... but likely is closer to fixed

**Comment by howardjohn** [comment]
I fixed https://github.com/istio/istio/pull/29646 and merged it, seems good so far
