### ISSUE TITLE
multicluster with different cluster domain not discovering remote services correctly

### ISSUE THREAD

**Issue by samene** [istio/istio#29692]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

I have a multicluster setup consisting of 3 clusters all within the same mesh. Every cluster has a different cluster domain - cluster.central, cluster.berlin and cluster.munich. Istio version 1.8.1 installed in all clusters with instruction from this link - [Multi primary on different networks](https://istio.io/latest/docs/setup/install/multicluster/)

In the IstioOperator cluster domain is set.
```
values:
  global:
    proxy:
      clusterDomain: "  "
```
Istio Meta DNS capture is true and the east-west gateway have "\*.berlin" and "\*.munich" added to their respective configs.

Deployed the helloworld/sleep sample in the mesh.

Within the cluster when I do a istioctl proxy-config endpoint I can see that the services are all discovered correctly with the correct cluster domain, but only for the ones within the same cluster.  The services in the other clusters are discovered with the wrong cluster domain.

**Expected:**
helloworld v1 and v2 deployed in cluster 2 and cluster 3 respectively should be reachable as helloworld.sample.svc.cluster.berlin and helloworld.sample.svc.cluster.munich, but it is discovered as helloworld.sample.svc.cluster.central in the central cluster.

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you 
istioctl version
client version: 1.8.0
control plane version: 1.8.1
data plane version: 1.8.1 (1 proxies)

kubectl version
Client Version: v1.18.12
Server Version: v1.18.10

**How was Istio installed?**
IstioOperator

**Comment by hzxuzhonghu** [comment]
Istio does not respect the dns domain of remote clusters before

**Comment by hzxuzhonghu** [comment]
In this case, svc httpbin.httpbin.svc.kube-01.local and  httpbin.httpbin.svc.kube-02.local both exists, i think there should be two clusters exist. 

one named  `outbound|80||httpbin.httpbin.svc.kube-01.local`
the other ` outbound|80||httpbin.httpbin.svc.kube-02.local`

**Comment by hzxuzhonghu** [comment]
Ignore above, my mistake, istiod is not aware of remote k8s domiansuffix.

**Comment by h0tbird** [comment]
Is that a desirable Istio feature? I guess that it would have to be implemented in [pilot-discovery](https://github.com/istio/istio/tree/master/pilot/cmd/pilot-discovery), right? Any pointer to relevant code sections would be great. Is there a workaround I can setup? I am thinking that maybe an `EnvoyFilter` to re-write the endpoints might do the trick.
