### ISSUE TITLE
Multiple Operators Fight One Another's ConfigMaps

### ISSUE THREAD

**Issue by asummers** [istio/istio#29699]
**Bug description**

After creating two Istio operators and CRs in orthogonal namespaces (e.g. dev and prod), CRs overwrite one another's configmaps unless all operator namespace's `istio-ca-secret` secret values are in sync with one another.

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

There exists a way (by default or otherwise) to limit which namespaces config maps are copied to, in order to allow more than one operator to exist. It's possible this exists, but I couldn't figure this out via the current documentation. 

It's also possible I'm doing something here incorrectly and I should instead be explicitly setting some cert value for both, but that was not clear in the documentation anywhere, if so. 

Rancher (where this is installed) has a notion of "projects" as grouped namespaces in the same cluster and the end goal is to have each of the two projects have their own operators, CRs, and Kialis watching completely different namespaces sitting next to each other.

**Steps to reproduce the bug**

1) Create 4 namespaces - `istio-operator-dev`, `istio-operator-prod`, `istio-system-dev`, `istio-system-prod`.
2) Install Istio operator into respective namespaces, e.g. 

```
istioctl operator init \
  --watchedNamespaces=istio-system-dev \
  --operatorNamespace=istio-operator-dev \
  --istioNamespace=istio-system-dev
  
istioctl operator init \
  --watchedNamespaces=istio-system-prod \
  --operatorNamespace=istio-operator-prod \
  --istioNamespace=istio-system-prod
  ```

3) Successfully install CR into `istio-system-dev`
4) Observe `config-map` in `istio-system-prod` is populated with `dev` secret value.
5) Create `istio-system-prod` CR. 
6) Notice logs in ingress/egress gateway similar to: 

```
2020-12-17T18:55:32.341261Z	error	cache	resource:default request:557dea79-f2f0-41ab-ab01-f24d6ccf5a79 CSR retrial timed out: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: x509: certificate signed by unknown authority (possibly because of \"crypto/rsa: verification error\" while trying to verify candidate authority certificate \"cluster.local\")
```

7) Delete `istio-system-prod` CR.
8) Copy `istio-ca-secret` values from `istio-system-dev` secret to remaining `istio-system-prod` secret or new one if this was deleted for some reason
9) Reinstall `istio-system-prod` CR
10) Observe errors no longer exist

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```
$ istioctl version --remote --istioNamespace istio-system-dev
client version: 1.7.2
control plane version: 1.7.2
data plane version: 1.7.2 (2 proxies)
$ istioctl version --remote --istioNamespace istio-system-prod
client version: 1.7.2
control plane version: 1.7.2
data plane version: 1.7.2 (2 proxies)
$ kubectl version --short
Client Version: v1.18.6
Server Version: v1.18.6
```

**How was Istio installed?**
Operator, see above. 

**Environment where the bug was observed (cloud vendor, OS, etc)** On prem Rancher

**Comment by morvencao** [comment]
`istio-ca-secret` is created by the istiod, if user-provided root CA is not found.
Will check why this secret conflicts for different istio operator CRs.

**Comment by howardjohn** [comment]
We do not currently support running multiple istiod's in different namespaces unfortunately (for this reason and testing mostly)
