### ISSUE TITLE
PriorityClassName for Istio Operator

### ISSUE THREAD

**Issue by asummers** [istio/istio#29700]
**Describe the feature request**

The CLI should allow specifying `priorityClassName` for the operator. It allows setting for the `istio-system` K8s objects (via `spec.values.global.priorityClassName` in the CR) , but there does not seem to be a way to specify this via `istioctl` for the operator itself.

**Describe alternatives you've considered**

One can manually dump the deployments, etc. to YAML, and add by hand, but the upgrade path between versions here gets rocky. 

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by morvencao** [comment]
We're try to avoid adding two many values for the istio operator itself, only the required parameters are now support to set with `operator init`. You can consider to dump the istio operator manifests and the apply youe overlay before creating them in the cluster.
