### ISSUE TITLE
[Istio 1.6.8]  Istio-proxy remove the token after jwt verify.

### ISSUE THREAD

**Issue by johnzheng1975** [istio/istio#29706]
**Bug description**
[Istio 1.6.8]  Istio-proxy remove the token after JWT Verify.
However, developers need this token for later usage.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Istio-proxy should keep token after JWT verify (requestauthentication)
` "Authorization": "Bearer eyJhbGci..."`

**Steps to reproduce the bug**
Step 1: Remove all requestauthentication, authorizationpolicy 
Step 2: Access the service, with header ` "Authorization": "Bearer eyJhbGci..."`
Step 3: In application, you can find http request include header ` "Authorization": "Bearer eyJhbGci..."`
Step 4: Apply the requestauthentication.
Step 5: Access the service again, with header ` "Authorization": "Bearer eyJhbGci..."` again
Step 6: In application, you can find http request `REMOVE` header ` "Authorization": "Bearer eyJhbGci..."`

**Version** ( 1.6.8)

**How was Istio installed?**
istioctl install  

**Environment where the bug was observed (cloud vendor, OS, etc)**
AWS linux (eks)
Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by johnzheng1975** [comment]
Ok, I found there is parameter to support keep token:
forwardOriginalToken

So, close this issue. Thanks.

**Comment by jnitin** [comment]
Hi 

I am using istio 1.9.4 version and if i add forwardOriginalToken then i get the error  unknown field error forwardOrignalToken. Please let me know if this is not supported in 1.9.4 version. 

OutputPayloadToHeader works fine which parses the token and send the payload to backend service in base64 encoded form.

Thanks in advance !
