### ISSUE TITLE
Contradictory documentation regarding Helm 2 support

### ISSUE THREAD

**Issue by buccella** [istio/istio#29716]
**Bug description**

According to the [Install with Helm page](https://istio.io/latest/docs/setup/install/helm/), `Helm 2 is not supported for installing Istio.`

Yet the [Helm 3 support doc](https://github.com/istio/istio/blob/master/manifests/charts/README-helm3.md) states, `Helm charts are supported both by Helm v2 and Helm v3`.

Which doc is accurate?

**Affected product area (please put an X in all that apply)**

[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Comment by morvencao** [comment]
cc @hickeyma
