### ISSUE TITLE
how to inject istio sidecar by modify deployment annotation

### ISSUE THREAD

**Issue by xishengcai** [istio/istio#29725]
**Describe the feature request**

**Describe alternatives you've considered**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by hzxuzhonghu** [comment]
Can you change the title in English? And elaborate the use case, we have supported injection by istioctl.
