### ISSUE TITLE
Gateway workloads outside of istio-system namespace don't work with a revisioned Istiod deployment

### ISSUE THREAD

**Issue by drivelikebrazil** [istio/istio#29733]
**Bug description**
Deploying Istio with a revision causes the discovery service address to change to istiod-[revision].istio-system.svc. Since gateways mount a configmap that only exists in the istio-system namespace to obtain their proxy config, a gateway deployed outside of istio-system is unable to get the correct discoveryAddress (or any other proxy config for that matter).

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Gateways deployed to other namespaces should correctly obtain the default proxy config without needing to manually apply a pod annotation or manually set envvars.

**Steps to reproduce the bug**

1. Deploy Istio with a revision marking
2. Deploy a gateway workload to a namespace outside of istio-system
3. Gateway attempts to connect to default disoveryaddress: istiod.istio-system.svc instead of istiod-[revision].istio-system.svc

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
`istioctl version`
client version: 1.8.1
control plane version: 1.8.1
data plane version: 1.8.1 (50 proxies)

`kubectl version`
Client Version: v1.19.3
Server Version: v1.18.6

**How was Istio installed?**
Istio Operator

**Environment where the bug was observed (cloud vendor, OS, etc)**
AWS

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by morvencao** [comment]
A workaound for this would copy the configmap `istio-<revision>` from the `istio-system` namespace to the namespace in which istio gateways is deployed.

**Comment by zombispormedio** [comment]
I am using [kubed](https://github.com/appscode/kubed) to replicate configmap` istio-<revision>`, but istio operator is deleting the configmaps and only keeping the configmap in `istio-system` namespace. How can I avoid this?

**Comment by morvencao** [comment]
@zombispormedio you can try to delete the labels of the replicated configmap.
