### ISSUE TITLE
Dynamic request routing based on captured values from headers

### ISSUE THREAD

**Issue by janbaer** [istio/istio#29744]
**Dynamic request routing based on header-values**

For our QA environment we need to configure a special kind of routing for the incoming (Ingress), but also for the outcoming (Egress) requests. So for outgoing requests the rule should evaluate a header value with a regex and capture a value from the header and build with that value the URL where the request should be redirected. The value in the header is dynamically changed, so the redirect URL can not be hardcoded.

For example if the outgoing requests goes to **services-master.anydomain.com**, but there's a header value **forwarded-for-feature** with the value **verbu-1234** the request should be redirected **services-verbu-1234.anydomain.com**.

For incoming requests it's a similar condition. If the **origin** points to **webapp-verbu-1234.anydomain.com**, but the request goes to **services-master.anydomain.com** the regex should extract **verbu-1234** from the origin domain and replace **master** in the URL with the extracted value.

I know, that it's possible to use a regex to match header values, but I'm not sure, if it's possible to use captured values from a match to influence the target URL, at least I couldn't find that in the documentation.

**Describe alternatives you've considered**

[x] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by hzxuzhonghu** [comment]
This is not supported

**Comment by janbaer** [comment]
I was afraid of that, but how about implementing such a feature? When I search in the internet for similar requirements, I see that I'm not the only one.

**Comment by hzxuzhonghu** [comment]
If there is fixed number of `values`, you can enumerate that with virtualservice matching `verbu-1234`, routing to `webapp-verbu-1234.anydomain.com`.

Otherwise, need implement it in envoy side

**Comment by janbaer** [comment]
I just found this old issue https://github.com/istio/old_mixer_repo/issues/495 and the guy talked about a Mixer adapter that could solve the problem. Unfortunately, the issue is closed so I can't ask him, if and how he solved it. But would be a mixer adapter a possible solution? What possibilities would I have with that?

**Comment by esnible** [comment]
This could perhaps be done with WebAssembly, but there are no examples.

**Comment by janbaer** [comment]
@esnible Could you please explain in a bit more detail, how this would work? Is there any documentation?

**Comment by hzxuzhonghu** [comment]
@janbaer https://github.com/dgn/oidc-filter/blob/master/src/lib.rs  This  is a good example

**Comment by nature502** [comment]
@janbaer Do you solve this issue ?

**Comment by janbaer** [comment]
@nature502 I'm sorry, but the issue was no longer on my radar, since we decided agains using Istio
