### ISSUE TITLE
Docs on RequestAuthentication don't work

### ISSUE THREAD

**Issue by haf** [istio/istio#29747]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
When following the host example (2nd from the top) https://istio.io/latest/docs/reference/config/security/request_authentication/ you get 

```
error: error validating "STDIN": error validating data: ValidationError(AuthorizationPolicy.spec.rules[0].to): invalid type for io.istio.security.v1beta1.AuthorizationPolicy.spec.rules.to: got "map", expected "array"; if you choose to ignore these errors, turn validation off with --validate=false

```

and if you put a `-` before:

```
  rules:
  - from:
    - source:
        requestPrincipals: ["*"]
      to:
      - hosts:
        - jaeger.example.com
```

you get 

```
error: error validating "STDIN": error validating data: ValidationError(AuthorizationPolicy.spec.rules[0].to[0]): unknown field "hosts" in io.istio.security.v1beta1.AuthorizationPolicy.spec.rules.to; if you choose to ignore these errors, turn validation off with --validate=false
```

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

1.8.1

**How was Istio installed?**

istioctl operator init

**Environment where the bug was observed (cloud vendor, OS, etc)**

GKE 1.17.x

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by yangminzhu** [comment]
Thanks for the report, the example missed the `- operation:`, sent out a PR to fix the doc.
