### ISSUE TITLE
TestXdsProxyReconnects unit test flakes

### ISSUE THREAD

**Issue by Monkeyanator** [istio/istio#29749]
Sample failures:

[https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/29602/unit-tests_istio/1341286152044285952](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/29602/unit-tests_istio/1341286152044285952)
[https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/29740/unit-tests_istio/1341252531908513792](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/29740/unit-tests_istio/1341252531908513792)
[https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/29740/unit-tests_istio/1341249553831038976](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/29740/unit-tests_istio/1341249553831038976)

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[x] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Comment by hzxuzhonghu** [comment]
Found removing `conn.Close()` in L278, no flake. Not sure why.
