### ISSUE TITLE
Need consistent & published way of identifying failure in automated tests logs

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#2974]
When an automated tests fails, the output of the failure contains sometimes many false leads, errors that are not errors.

We need a consistent string to search for in the output : either "--- FAIL" or "=== fail", but the same across all Istio. We need this info to be added to the developers page.

cc @sebastienvas @yutongz

**Comment by vaidsu** [comment]
@andraxylia if we wish to contribute for this issue, are there any pointers that we can start looking into? Is there any specific test case you would like to start with? 

Please let me know.

**Comment by andraxylia** [comment]
It may have changed meanwhile, since I cannot grep for "--- FAIL" anymore, but we have 2-3 different frameworks e2e_pilot, e2e_mixer, simple test and each logs failure in a different way, so when trying to merge a PR it is not immediately obvious where the failure is, or what to find in file to go straight to the failure.

Take any open PR with failures, go to the link where it says tests have failed, and see how easy/hard is to see what went wrong.

**Comment by vaidsu** [comment]
@andraxylia 

I was looking into the framework, and I see the lowest level could potentially be 

```go
// RunTest sets up all registered cleanables in FIFO order
// Execute the runnable
// Call teardown on all the cleanables in LIFO order.
func (c *CommonConfig) RunTest(m runnable) int {
        var ret int
        if err := c.Cleanup.init(); err != nil {
                log.Errorf("Failed to complete Init. Error %s", err)
                ret = 1
        } else {
                log.Info("Running test")
                ret = m.Run()
        }
        if err := c.saveLogs(ret); err != nil {
                log.Warnf("Log saving incomplete: %v", err)
        }
        c.Cleanup.cleanup()
        return ret
}
```

Is the idea more about making the framework throw out errors and handle tests in a more common fashion? 

I checked the circle ci links, I get an idea now. 

As a side note, how long does a full build take? Just wanted to understand if its just me or is it normal, or if I am missing any environmental dependencies in my mac. I used the vagrant istio from the vagrant-istio branch. 

Thanks again

**Comment by andraxylia** [comment]
Yes, you got the idea. 

Vagrant is work in progress  as part of the test SWAT effort to unify testing in general. It may be a good idea to sync up with them @nmittler @gargnupur .

**Comment by vaidsu** [comment]
Thanks @andraxylia appreciate your quick response. 

I am just wondering if there is an easy to test just a single file. I am new to Istio, but generally my way of picking up a large code base is by writing tests for the code, so as to understand it better. Thus, I am here into test area. 

I am trying to hack a bit and understand what file does what, meanwhile if there is an hello world test that just runs through the framework it will be helpful. I am just trying out the tests for framework itself, which might mostly not require any pods, etc. 

Thanks again.

**Comment by andraxylia** [comment]
I would recommend ads_test.go if you want to understand the code.

**Comment by hklai** [comment]
@vaidsu https://github.com/istio/istio/tree/master/tests/e2e#using-a-local-vm should help you run E2E tests on local machines.

**Comment by vaidsu** [comment]
@hklai - This is excellent -- I will check and set this up.

**Comment by vaidsu** [comment]
@hklai quick question, I tried to run the setup one by one, may be I am missing something, or this is not the right place to ask (if you feel so I can ask in the mailer), but after some hours of stretch to get everything setup, I am stuck here: 

```bash
vagrant@contrib-stretch:~/go/src/istio.io/istio$ kubectl get pods -n istio-system
NAME                                       READY     STATUS              RESTARTS   AGE
istio-citadel-5b8f44687d-9pskc             0/1       ImagePullBackOff    0          9m
istio-cleanup-old-ca-5zwh6                 0/1       Completed           0          9m
istio-egressgateway-65d5bdd9d8-2hqph       0/1       ImagePullBackOff    0          9m
istio-galley-cc9c88f69-wxvvk               0/1       ContainerCreating   0          9m
istio-ingressgateway-7b7c9f5688-8k5k9      0/1       ImagePullBackOff    0          9m
istio-mixer-post-install-24msw             0/1       Error               0          6m
istio-mixer-post-install-2628v             0/1       Error               0          5m
istio-mixer-post-install-27t6v             0/1       Error               0          5m
istio-mixer-post-install-2cmnj             0/1       Error               0          4m
istio-mixer-post-install-2dts8             0/1       Error               0          7m
istio-mixer-post-install-2f25z             0/1       Error               0          3m
istio-mixer-post-install-2f2bf             0/1       Error               0          3m
istio-mixer-post-install-2f4wm             0/1       Error               0          7m
istio-mixer-post-install-2fszn             0/1       Error               0          6m
istio-mixer-post-install-2knfk             0/1       Error               0          1m
istio-mixer-post-install-2v426             0/1       Error               0          7m
istio-mixer-post-install-46ssp             0/1       Error               0          8m
istio-mixer-post-install-4drkz             0/1       Error               0          5m
```

Is there anything I am missing here. Like mentioned in the guide, I did check prow web results, and I found a similar run on e2e_simple and I found a completely different build logs [here](https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/6184/e2e-simpleTests/5071/?log#log) 

Either I am looking at the wrong logs or I am doing something wrong. 

Something strange I saw was 

```bash
2018-06-15T08:37:55.339430Z	info	Running command kubectl logs istio-mixer-post-install-jn5ss -n istio-system -c hyperkube --kubeconfig=
2018-06-15T08:37:55.554239Z	info	Running command kubectl logs istio-mixer-post-install-jn5ss -n istio-system -c hyperkube -p --kubeconfig=
2018-06-15T08:37:55.811262Z	info	Command error: exit status 1
2018-06-15T08:37:55.811327Z	info	No previous log command failed: "Error from server (BadRequest): previous terminated container \"hyperkube\" in pod \"istio-mixer-post-install-jn5ss\" not found\n" exit status 1
```

This was constantly repeating. Is there anything I should be doing here in terms of configuration. Only change is the kubconfig, even though I changed the port to 9000 (since I had other dockers for other reasons listening into 8080) in the .config it did not copy. 

So I ended up finding this

```bash
vagrant@contrib-stretch:~/go/src/istio.io/istio$ ps ax | grep kube
  828 ?        Ssl    2:27 /usr/bin/hyperkube apiserver --allow-privileged=true --service-cluster-ip-range=10.0.0.0/24 --cert-dir=/var/lib/kubernetes --insecure-bind-address=0.0.0.0 --etcd-servers=http://127.0.0.1:2379 --admission-control=AlwaysAdmit,NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota --storage-backend=etcd3
  829 ?        Ssl    1:06 /usr/bin/hyperkube controller-manager --master=127.0.0.1:8080 --service-account-private-key-file=/var/lib/kubernetes/apiserver.key --root-ca-file=/var/lib/kubernetes/apiserver.crt
  830 ?        Ssl    0:07 /usr/bin/hyperkube proxy --master=127.0.0.1:8080
  831 ?        Ssl    0:24 /usr/bin/hyperkube scheduler --master=127.0.0.1:8080
  832 ?        Ssl    3:03 /usr/bin/hyperkube kubelet --allow-privileged=true --logtostderr=true --kubeconfig=/etc/kubeconfig.yml --hostname-override=10.10.0.2 --address=0.0.0.0 --serialize-image-pulls=false --cluster-dns=10.0.0.4 --cluster-domain=cluster.local --fail-swap-on=false
12402 pts/0    S+     0:00 grep kube
```

Just before I send, I am retrying to change the config and rerunning them. I will update again. 

Sorry for verbiage, will be very helpful if I can get some clues, I will contribute back by changing some doc with experiences if thats useful.

**Comment by hklai** [comment]
@vaidsu thanks for trying and sorry about the trouble.  There may still be rough edges.

It looks like your cluster could not find the images. Did both your setup_vm.sh, setup_host.sh and setup_test.sh  complete without issues?

At the end of setup_test.sh, it should show the images pushed to your local registry. Did it show anything?

/CC @gargnupur

**Comment by gargnupur** [comment]
@vaidsu : Thanks for reporting, along with what Andy asked, can you get logs of command: "kubectl describe pod istio-citadel-5b8f44687d-9pskc  -n istio-system" 
And what is the value of HUB and TAG ?

**Comment by vaidsu** [comment]
@hklai and @gargnupur thanks for getting back quickly,. Before I provide some false positives, I wish to understand one quick thing. I tried again, and for some reason the build failed. I can fix build errors by trial and errors, but the question is n how do we manage the non-default ports. 

For instance if I wish to use 9000 for kube, am I right doing the following changes only? 

1. Run setup_vm.sh (brings up vagrant, and starts the processes in the default 8080 port), the script does not provision any port business there. Thus I see this in my VM:

```bash
vagrant@contrib-stretch:~/go/src/istio.io/istio$ ps ax | grep kube
  801 ?        Ssl   10:09 /usr/bin/hyperkube apiserver --allow-privileged=true --service-cluster-ip-range=10.0.0.0/24 --cert-dir=/var/lib/kubernetes --insecure-bind-address=0.0.0.0 --etcd-servers=http://127.0.0.1:2379 --admission-control=AlwaysAdmit,NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota --storage-backend=etcd3
  802 ?        Ssl   14:19 /usr/bin/hyperkube controller-manager --master=127.0.0.1:8080 --service-account-private-key-file=/var/lib/kubernetes/apiserver.key --root-ca-file=/var/lib/kubernetes/apiserver.crt
  803 ?        Ssl    1:30 /usr/bin/hyperkube proxy --master=127.0.0.1:8080
  804 ?        Ssl    6:49 /usr/bin/hyperkube scheduler --master=127.0.0.1:8080
  825 ?        Ssl   13:17 /usr/bin/hyperkube kubelet --allow-privileged=true --logtostderr=true --kubeconfig=/etc/kubeconfig.yml --hostname-override=10.10.0.2 --address=0.0.0.0 --serialize-image-pulls=false --cluster-dns=10.0.0.4 --cluster-domain=cluster.local --fail-swap-on=false
```

2. Change 2 once the setup_vm is done, run setup_host, and then change the ~/.kube/config to 9000 port which gave me this: 

```bash
VAITSUND-M-P0VK:vagrant vaitsund$ cat ~/.kube/config
apiVersion: v1
kind: Config
users:
- name: kubelet
clusters:
- name: local
  cluster:
     server: http://localhost:9000
contexts:
- context:
    cluster: local
    user: kubelet
  name: service-account-context
current-context: service-account-context
```

However since the changes after the port adjustments are not carried forward into the VM, I still see this: 

```bash
vagrant@contrib-stretch:~/go/src/istio.io/istio$ cat ~/.kube/config 
apiVersion: v1
kind: Config
users:
- name: kubelet
clusters:
- name: local
  cluster:
     server: http://localhost:8080
contexts:
- context:
    cluster: local
    user: kubelet
  name: service-account-context
```

So, is that how its intended to? The host (mac) will have 9000 port defined, but the internal kube processes in the VM are running in 8080? I have provisioned pods, but having them talk between VMs is the first time. **Also I am running the build and test inside the VM**

Hope this makes sense. 

@gargnupur unfortunately I don't have the pods running currently due to some build failure, I will send out once that is up.

**Comment by gargnupur** [comment]
@vaidsu : Check out the 6th one here: It mentions how to setup different ports: https://github.com/istio/istio/blob/master/tests/e2e/local/vagrant/Troubleshooting.md

**Comment by vaidsu** [comment]
Yes @gargnupur I do the same thing, question is: can the ~/.kube/config in HOST, be different from ~/.kube/config in VM? If yes, then I have configured properly and the build is currently running. If not, there is some changes required in the steps ordering or in the script, I believe. 

Also, is there any discord or slack channel that can avoid adding verbiage to the issue tracker? 

Thanks again

**Comment by gargnupur** [comment]
Sure, how about using test-and-release slack channel: https://istio.slack.com/messages/C6FCV6WN4/

**Comment by vaidsu** [comment]
@gargnupur I am not from ibm, so I don't have an existing account into this, can you please send me an invite? vaithi.sures@gmail.com? Is that okay please?
