### ISSUE TITLE
allow different cluster use different image hub

### ISSUE THREAD

**Issue by zhongfox** [istio/istio#29772]
for multiple clusters mesh, we already support central istiod, so there is only one istio-sidecar-injector config map,
for some case multiple clusters are in different regions, so they may use different image hub.
currently there is on way to set different image hub for different clusters

some possible solutions:

1. pass hub params from mutatingWebhookConfiguration inejct url
   inject url now allow pass more info(see https://github.com/istio/istio/pull/25968), but hub url include "/",  it may not easy to parse.

2. add more hub config to istio-sidecar-injector, it's cluster-related, like:
 
```
values: |-
  {
    "global": {
      "clusterHubs": {  // this is new key
        "cluster1": "docker1.io/istio",
        "cluster2": "docker2.io/istio"
      },
      "hub": "docker.io/istio",
      "imagePullPolicy": "",
```

for IstioOperator, it will like:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    accessLogFile: /dev/stdout
  hub: "docker0.io/istio"
  clusterHubs: // this is new key
        cluster1: "docker1.io/istio",
        cluster2: "docker2.io/istio"
```

**Affected product area (please put an X in all that apply)**
[X] Installation

**Affected features (please put an X in all that apply)**
[X] Multi Cluster

**Comment by morvencao** [comment]
@stevenctl Do you have any insight? We may need to update the operator API for this.
