### ISSUE TITLE
Proxy Extensions in doc，where to use this config ?

### ISSUE THREAD

**Issue by sunnoy** [istio/istio#29778]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
where to use this config 
https://istio.io/latest/docs/reference/config/proxy_extensions/
**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**
i want to know where to use https://istio.io/latest/docs/reference/config/proxy_extensions/ config

**Comment by douglas-reid** [comment]
This isn't something we expect end users to interact with directly. At the moment, you can use that config in EnvoyFilter resources to control extensions, if needed.

Let's move the discussion to the discuss forum if you have more questions.
