### ISSUE TITLE
Add feature to mirror all requests

### ISSUE THREAD

**Issue by Erezf-p** [istio/istio#29783]
Hi.

In my case, i want to use virtual service to mirror traffic in all the cluster.
I would like to use one virtual service for this, that will listen on all hosts in all namespaces, instead of a virtual service for each service.

The problem I am facing is that there isnt seem to be a passthrough option and I am always need to specify the host I want to forward the traffic to.

Is there a passthrough in VirtualService?

**Comment by howardjohn** [comment]
Out of the box, with no VirtualServices, traffic will be passed through, so I am a bit confused what you are trying to? Is this for a gateway?

**Comment by Erezf-p** [comment]
As I was saying,  I want to use virtual service to mirror traffic in all the cluster. Not related to Gateway

**Comment by howardjohn** [comment]
When you say mirror do you mean like https://istio.io/latest/docs/tasks/traffic-management/mirroring/? If so, this is not possible. If you just want to top forward traffic that works out of the box

**Comment by Erezf-p** [comment]
Yes this what I mean. Thanks.

**Comment by howardjohn** [comment]
The mirror requires a pre-determined destination, I don't think envoy supports mirroring arbitrary traffic to arbitrary destinations. Its also not clear to me how you would want this to work - what part of the request are you modifying?

**Comment by Erezf-p** [comment]
I would like to do something like this:

`apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
    - '*.local'
  http:
  - route:
    - destination:
        host: <passthrough>
    mirror:
      host: backup-mirror
    mirror_percent: 100`

This way i can use one virtual service rule for all traffic to all services.

I do not want to modify any part of the request, just mirror the data to some service and forward it to the original destination

**Comment by howardjohn** [comment]
Oh you want to send ALL traffic to a single mirror. Got it. Normally you have one mirror per service which is why i was confused.

**Comment by Erezf-p** [comment]
Yes exactly
