### ISSUE TITLE
 istio-1.8.1 install error:  failed calling webhook "validation.istio.io"

### ISSUE THREAD

**Issue by dulm** [istio/istio#29785]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

[root@i-qoy2h7fd ~]#  istioctl install --set profile=demo 
This will install the Istio demo profile with ["Istio core" "Istiod" "Ingress gateways" "Egress gateways"] components into the cluster. Proceed? (y/N) y
[0m Istio core installed                                                                                                      
2020-12-28T09:53:10.607568Z     error   installer       Internal error occurred: failed calling webhook "validation.istio.io": Post https://istiod.istio-system.svc:443/validate?timeout=30s: EOF
2020-12-28T09:53:16.115559Z     error   installer       Internal error occurred: failed calling webhook "validation.istio.io": Post https://istiod.istio-system.svc:443/validate?timeout=30s: EOF
^C

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

[root@i-qoy2h7fd ~]# kubectl version --short
Client Version: v1.18.9+k3s1
Server Version: v1.18.9+k3s1
[root@i-qoy2h7fd ~]# istioctl version --remote
client version: 1.8.1
control plane version: 1.8.1
data plane version: 1.8.1 (2 proxies)

**How was Istio installed?**
follow the step  in  https://istio.io/latest/docs/setup/getting-started/

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by morvencao** [comment]
Is it fresh install?

**Comment by dulm** [comment]
> Is it fresh install? Did you have another istio installed before you did this?

not fresh,   i run   ` istioctl install --set profile=demo`  before ,  all show suc.

but  the svc  istio-pilot   not found.


then i run the ` istioctl install --set profile=demo` again,   shows the error msg above

**Comment by morvencao** [comment]
@dulm Individual Istio components like Pilot, Galley, Citadel were all simplified into one istiod after istio 1.5, see: https://istio.io/latest/blog/2020/istiod/
I can't reproduce your issue of `failed calling webhook "validation.istio.io"`, now the istiod also acts as the validating webhook server, so if the istiod is running and its service exists, we should not encounter this issue.

**Comment by xichengliudui** [comment]
i had this problem after upgrading，i updated istiod svc
after using it for a period of time, there will be problems. why?
```
[root@mesh-dev-10-20-1-180 ~]# kubectl get svc -n istio-system
NAME               TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                                      AGE
istiod-1-8-4       ClusterIP   10.101.68.198    <none>        15010/TCP,15012/TCP,443/TCP,15014/TCP                        30m
```
```
Internal error occurred: failed calling webhook "validation.istio.io": Post https://istiod.istio-system.svc:443/validate?timeout=30s: service "istiod" not found
Internal error occurred: failed calling webhook "validation.istio.io": Post https://istiod.istio-system.svc:443/validate?timeout=30s: service "istiod" not found
Internal error occurred: failed calling webhook "validation.istio.io": Post https://istiod.istio-system.svc:443/validate?timeout=30s: service "istiod" not found
```

**Comment by ggjjlldd** [comment]
kubectl delete validatingwebhookconfiguration istiod-default-validator
