### ISSUE TITLE
Add user volume and volume mount to proxy config

### ISSUE THREAD

**Issue by bianpengyuan** [istio/istio#29791]
Currently additional user volume and volume mount are only achievable via `sidecar.istio.io/userVolume` and `sidecar.istio.io/userVolumeMount` pod annotation, which cannot be controlled globally. For many cases, the sidecar needs extra secret to interact with vendor for telemetry reporting (for example, sidecar template has [lightstep](https://github.com/istio/istio/blob/374fcdcfa040a27c4ddf6adfc621f559f1361d00/manifests/charts/istio-control/istio-discovery/files/injection-template.yaml#L402) credential mounted), and possibly for Wasm binary pulling in the future.

Instead of adding volume option for specific backend, it would be better to allow arbitrary additional user volume option in proxy config.

**Comment by howardjohn** [comment]
This is close to possible with https://docs.google.com/document/d/1Rmp9B3DDypgMCau-YAqidx_r3qvKLZj6jUX-t22zj84/edit without any API change. Users can define a new injection template with just these volumes (once https://github.com/istio/istio/pull/29731 merges), then configure the default injection to use the default sidecar injection template *and* the custom template.

**Comment by hzxuzhonghu** [comment]
IIRC, the proxyConfig is marshalled and sent to the istiod, however not all the data is used. This is a waste.

**Comment by howardjohn** [comment]
node meta will only be sent once soon after https://github.com/envoyproxy/envoy/pull/14080, so I don't think the proxy config size matters much, personally.

**Comment by hzxuzhonghu** [comment]
But it reconnects every 30minute, in a large mesh, this could not be ignored. So could we only marshal useful fields?

**Comment by howardjohn** [comment]
The volume mount would be like ~5 lines of yaml. The full XDS config is 10000s. Even the current bootstrap from envoy is orders of magnitude larger. I don't think we need to optimize proxy config size too much

**Comment by bianpengyuan** [comment]
> This is close to possible with https://docs.google.com/document/d/1Rmp9B3DDypgMCau-YAqidx_r3qvKLZj6jUX-t22zj84/edit without any API change. Users can define a new injection template with just these volumes (once #29731 merges), then configure the default injection to use the default sidecar injection template and the custom template.

That would still need pod annotation to select the custom template to merge with? Or is there going to be a way to specify custom template which is always merged?

**Comment by howardjohn** [comment]
There isn't yet but it's easy to add and we probably should

**Comment by bianpengyuan** [comment]
This is possible now with default templates in MeshConfig.
