### ISSUE TITLE
upgrade path from 1.4.7( helm installation) to latest version

### ISSUE THREAD

**Issue by 1hanymhajna** [istio/istio#29797]
Hi,
I'm working on upgrade path from istio 1.4.7 to the latest version
We installed istio using helm chart and want to move and start using istioctl in order to manage our clusters.
I tried to do `istioctl manifest migrate` in order to get the current state, but when i try to apply it using `istioctl manifest apply -f <migrate output file path>` it failed cause of a lot of unknown fields.

As I understood the upgrade path should be:

1.migrate 1.4.7 helm to istio 1.4.7 using istioctl
2.upgrade to 1.5.10 using istioctl
3.upgrade to 1.6 > 1.7 > 1.8

Can anyone help with the correct path that we have to do in order to be able to move to istioctl AND to upgrade to the latest version?

Please notice we have multiple internal ELB and any path with expected downtime it will not work for us cause we are running it in production with a lot of traffic

Thanks

**Comment by Monkeyanator** [comment]
What version of `istioctl` are you using for the `istioctl manifest apply` and `istioctl manifest migrate`? Generally when I've seen a barrage of unknown field errors it's had something to do with istioctl verison (my hunch is that you may have to use 1.4.x istioctl to perform the initial migrate and install although I haven't personally tried it).

You are correct on the upgrade path requiring 1.4->1.5->1.6->1.7->1.8 (hoping to support jumping across more versions in the future but not there yet)

**Comment by 1hanymhajna** [comment]
Hi @Monkeyanator , thanks for your  reply,
I'm using istioctl 1.4.7v ( the same as the correct istio version),
As I understand we cannot migrate in 1.4.7 to istioctl cause it not support multiple ingress gateway, and in our case we have multiple ingress that we want to make sure that nothing broken there.

Do you know if we can upgrade (without downtime) **using HELM** to 1.5.10 then to migrate it to istioctl?
so the path will be like this: 
1- Upgrade from 1.4.7 to 1.5.10 (using helm chart)
2- Migrate 1.5.10 ( the legacy way) to istioctl
3- upgrade to the newest version

is this flow safe? am I need to delete any validation webhook before doing that?
