### ISSUE TITLE
Create e2e for Task "Enabling Simple Access Control"

### ISSUE THREAD

**Issue by sebastienvas** [istio/istio#298]

**Comment by sakshigoel12** [comment]
rshriram@ the e2e integration testing for 0.2 is not complete I think. Why have we closed issues related to this?

**Comment by rshriram** [comment]
sorry I thought this was talking about docs (given the date when this was created). I also thought that @douglas-reid added bunch of e2e checks related to mixer, two months ago. Please do reopen if thats not the case. I did some cleaning of issues, based on how long they have been around and any activity associated with them/whatever I remember. If I closed any prematurely, please feel free to reopen.

**Comment by sakshigoel12** [comment]
Access control using whitelists e2e test

**Comment by ldemailly** [comment]
@wattli do we have a task and a test for this already ?

either way this wouldn't hold the release

**Comment by wattli** [comment]
this was obsolete
