### ISSUE TITLE
"Connection reset by peer" Affecting all services

### ISSUE THREAD

**Issue by PatrickDuncan** [istio/istio#29804]
**Bug description**

We have an application with many micro-services that are all a part of the mesh. We have strict mTLS PeerAuthentication on and we are using AuthorizationPolicies. 

After some period of time (hours or days) the communication between the pods start to randomly fail with `connection reset by peer` and the only fix I've found is to restart either the receiver Pod, sender Pod, or both. This happens with normal and headless Services.

I have to assume this is related to Istio since the error is consistent with communicating with a known service like zookeeper and our internal code.

With the warning log level I only see `StreamAggregatedResources gRPC config stream closed: 13`

With trace on I see a lot of these repeated:
```
istio-proxy debug envoy upstream	membership update for TLS cluster outbound|2181||zookeeper-svc.zookeeper.svc.cluster.local added 1 removed 0
...
istio-proxy debug envoy upstream	Stale original dst hosts cleanup triggered.
istio-proxy debug envoy upstream	re-creating local LB for TLS cluster outbound|2181||zookeeper-svc.zookeeper.svc.cluster.local
istio-proxy debug envoy upstream	membership update for TLS cluster outbound|2181||zookeeper-svc.zookeeper.svc.cluster.local added 0 removed 1
```

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

I expect connections to not be completely lost and unrecoverable.

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```
1.7.0
data plane version: 1.7.3 (33 proxies)

Client Version: v1.17.5
Server Version: v1.18.13+IKS
```

**How was Istio installed?**

Manifest from istioctl

**Environment where the bug was observed (cloud vendor, OS, etc)**

IBM Cloud

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
Thanks for the report @PatrickDuncan . This is unfortunately a bit tricky to investigate due to the long delays between the issue. if you experience this again, can you get a config dump from the client and server sidecars (https://github.com/istio/istio/wiki/Troubleshooting-Istio) as well as the /clusters output? And then once its fixed get another one so we can compare the two. Thanks!

**Comment by PatrickDuncan** [comment]
I will close this for now. The connectivity issues may just be from imperfect networking and it's not happening as much now
