### ISSUE TITLE
Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?)

### ISSUE THREAD

**Issue by abhijitkubric** [istio/istio#29819]
**Bug description**

We have Istio 1.5.10 and EKS 1.14 running. Ingress-gateway pod started giving error after we restart the EKS nodes. 

`info	Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 0 successful, 0 rejected; lds updates: 0 successful, 0 rejected`

[ ] Docs
[X] Installation
[X] Networking
[X] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[X] Test and Release
[X] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

istio-ingressgateway pod up and running in` istio-system` namespace

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```
istioctl version --remote
client version: 1.5.10
internal-popcraftio-ingressgateway version: 
pilot version: 1.5.10
office-popcraftio-ingressgateway version: 
office-popcraftio-ingressgateway version: 
data plane version: 1.5.10 (139 proxies)
```

**Environment where the bug was observed (cloud vendor, OS, etc)**

EKS 1.14

**Comment by howardjohn** [comment]
Istio 1.5 is no longer supported, please update to a later version and re-open if needed: https://istio.io/latest/news/support/announcing-1.5-eol-final/

Generally this issue means there is no network connectivity to Istiod though, which may mean EKS is having issues recovering from node restart.

**Comment by abhijitkubric** [comment]
Upgraded it to Istio 1.6.14 . But error is same

**Comment by lopeg** [comment]
@abhijitkubric  do you have any AuthorizationPolicy or RequestAuthentication connected to the failed pod?
