### ISSUE TITLE
push context init races

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#29830]
First issue:

1. Push is called, generate PC A, start async AdsPushAll
2. Push called again, generate PC B, start async AdsPushAll
3. PC b AdsPushAll runs first, triggering push, and loading SidecarScope based on PC B
4. PC a AdsPushAll runs seconds, triggering push, and loading SidecarScope based on PC A

Proxy now has the wrong sidecar scope until next full push.

This is extremely unlikely to happen in real world due to 100ms debounce time, but we run tests with debounce disabled (and users can too!).

A fix is to make AdsPushAll not async; its not blocking anyways so I don't think it should be

Once that is fixed, we have another rare case.

1. Create PC a
2. Start creating PC b
3. Proxy connects, loads sidecar scope based on pc B
4. PC b creation complete, trigger push
5. No proxies to push, do nothing
6. proxy init complete, registers con

In this case we missed the push for pc B.

This is due to a race between initProxy and addCon.

We might be able to just call addCon first, but need to look into the implications of this.

I strongly suspect there is also a race where we start serving XDS once the controllers have synced, but we do *not* wait for the PushContext to finish initializing. I have yet to confirm this one though.

I am working on all of this, just want to write it down so I don't forget over the long weekend

**Comment by howardjohn** [comment]
I confirmed the last one is present as well

reproducer:
<details>

```diff
diff --git a/pilot/pkg/features/pilot.go b/pilot/pkg/features/pilot.go
index f0243ad29e..c3ecc8e129 100644
--- a/pilot/pkg/features/pilot.go
+++ b/pilot/pkg/features/pilot.go
@@ -67,7 +67,7 @@ var (
 
 	DebounceAfter = env.RegisterDurationVar(
 		"PILOT_DEBOUNCE_AFTER",
-		100*time.Millisecond,
+		0*time.Millisecond,
 		"The delay added to config/registry events for debouncing. This will delay the push by "+
 			"at least this internal. If no change is detected within this period, the push will happen, "+
 			" otherwise we'll keep delaying until things settle, up to a max of PILOT_DEBOUNCE_MAX.",
diff --git a/pilot/pkg/model/push_context.go b/pilot/pkg/model/push_context.go
index 65a722e4f2..7726337b6a 100644
--- a/pilot/pkg/model/push_context.go
+++ b/pilot/pkg/model/push_context.go
@@ -883,8 +883,10 @@ func (ps *PushContext) InitContext(env *Environment, oldPushContext *PushContext
 	ps.initializeMutex.Lock()
 	defer ps.initializeMutex.Unlock()
 	if ps.initDone.Load() {
+	log.Errorf("howardjohn: skip init")
 		return nil
 	}
+	log.Errorf("howardjohn: init context, real")
 
 	ps.Mesh = env.Mesh()
 	ps.MeshNetworks = env.Networks()
diff --git a/pilot/pkg/xds/ads.go b/pilot/pkg/xds/ads.go
index 2318d24157..83c47c9528 100644
--- a/pilot/pkg/xds/ads.go
+++ b/pilot/pkg/xds/ads.go
@@ -243,6 +243,7 @@ func (s *DiscoveryServer) StreamAggregatedResources(stream discovery.AggregatedD
 		adsLog.Debug("Unauthenticated XDS: ", peerAddr)
 	}
 
+	adsLog.Infof("howardjohn: stream init")
 	// InitContext returns immediately if the context was already initialized.
 	if err = s.globalPushContext().InitContext(s.Env, nil, nil); err != nil {
 		// Error accessing the data - log and close, maybe a different pilot replica
diff --git a/pilot/pkg/xds/discovery.go b/pilot/pkg/xds/discovery.go
index b9edb5b033..416da05ad9 100644
--- a/pilot/pkg/xds/discovery.go
+++ b/pilot/pkg/xds/discovery.go
@@ -443,6 +443,7 @@ func doSendPushes(stopCh <-chan struct{}, semaphore chan struct{}, queue *PushQu
 	}
 }
 
+var firstDone = false
 // initPushContext creates a global push context and stores it on the environment.
 func (s *DiscoveryServer) initPushContext(req *model.PushRequest, oldPushContext *model.PushContext) (*model.PushContext, error) {
 	push := model.NewPushContext()
@@ -457,8 +458,17 @@ func (s *DiscoveryServer) initPushContext(req *model.PushRequest, oldPushContext
 		return nil, err
 	}
 
+	if firstDone {
+		adsLog.Errorf("howardjohn: sleep set push context!")
+		time.Sleep(time.Second * 15)
+		adsLog.Errorf("howardjohn: done set push context!")
+	} else {
+
+		adsLog.Errorf("howardjohn: done immediately")
+	}
 	s.updateMutex.Lock()
 	s.Env.PushContext = push
+	firstDone = true
 	s.updateMutex.Unlock()
 
 	return push, nil
```
</details>

**Comment by howardjohn** [comment]
https://github.com/istio/istio/pull/29872

**Comment by DeLautour** [comment]
I've noticed an issue in 1.5.4 where proxy configuration is missing a number of clusters. I can see 
`service lookup for hostname .... failed` logged (https://github.com/istio/istio/blob/1.5.4/pilot/pkg/proxy/envoy/v2/eds.go#L316)

After some investigation and believe this is caused by a race condition on `globalPushContext`, specifically when called from ADS on new connections: https://github.com/istio/istio/blob/1.5.4/pilot/pkg/proxy/envoy/v2/ads.go#L261 

Does this seem likely / related to this issue?
