### ISSUE TITLE
GitOps Istio-Operator Deployment Silently Failing to Deploy CRs

### ISSUE THREAD

**Issue by dat-billyf** [istio/istio#29836]
I've run across this weird state for a new `1.18` cluster where `helm template istio/manifests/charts/istio-operator/ --set hub=docker.io/istio --set tag=1.8.1 --set operatorNamespace=istio-operator --set istioNamespace=istio-system` applied using `kubectl apply` results in an `istio-operator` pod logging deletions for CRs in `istio-system`, but, **won't deploy anything using CRs**; no errors logged (please see https://gist.github.com/dat-billyf/2aac780ffd5418f630892d618eca1d54#file-istio-operator2-log) 🤔 

But if I remove what was applied, and then use `istioctl operator init`, the unprocessed CRs suddenly all get deployed immediately?

Deleting the `istio-operator` `Deployment` and then retrying via `kubectl` reproduces the behavior every time, where CRs are ignored for deployment. Not sure where else to look having spent the whole day diffing everything, and finding no differences as a result of what `istioctl operator init` did. It seems to be doing something that I am not seeing 🤔 Even applying the manifest logged via `--log_output_level=all:debug` directly does not help 😫 

Tried so many different ways for a gitops managed cluster to establish the operator via manifest only while avoiding the use of `istioctl operator init`, but cannot find any way to do so 🔍 

Where else should I be looking to **get the operator deployed via gitops**?

[x] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[x] Test and Release
[x] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

N/A

**Expected behavior**
Please see https://gist.github.com/dat-billyf/2aac780ffd5418f630892d618eca1d54#file-istio-operator-expected-log.

**Steps to reproduce the bug**
```
$ helm template istio/manifests/charts/istio-operator/ --set hub=docker.io/istio --set tag=1.8.1 \
    --set operatorNamespace=istio-operator --set istioNamespace=istio-system | kubectl apply -f -
$ istio/samples/multicluster/gen-eastwest-gateway.sh --mesh primary --cluster billyf-istio-control --network non-prod > remoteprimary-gateway.yaml
$ kubectl apply -f remoteprimary-gateway.yaml
```

**Version**
```
$ istioctl version --remote
no running Istio pods in "istio-system"
1.8.1
$ kubectl version --short
Client Version: v1.19.3
Server Version: v1.18.9-eks-d1db3c
$ helm version --short
v3.4.2+g23dd3af
```

**How was Istio installed?**
IstioOperator installation attempt made via:
`helm template istio/manifests/charts/istio-operator/ ...`

**Environment where the bug was observed (cloud vendor, OS, etc)**
Amazon EKS.

**istioctl bug-report**
```
$ istioctl --kubeconfig ~/.kube/config-billy-istio-control --context billyf-istio-control bug-reportError: kubectl error: exit status 1

stderr:
error: current-context is not set (repeated 1 times)


stdout:


```

Please see https://gist.github.com/dat-billyf/2aac780ffd5418f630892d618eca1d54#file-k8s_resources-yaml and other yamls I was able to retrieve at this point in the installation attempt.

**Comment by morvencao** [comment]
@dat-billyf Can you check if the istiooperator CR is created in the `istio-system` namespace after you apply the istio-operator deployment from `helm template... | kubectl apply -f -` command?

**Comment by dat-billyf** [comment]
Yeah, I came to the conclusion that the [recommended path for installing Istio and managing Istio installations will be using the Operator via Istioctl](https://discuss.istio.io/t/istios-helm-support-in-2020/5535) which, I just shared with my team last week. They were hoping to have no dependency on `istioctl` whatsoever, but, instead, use only manifests for a GitOps managed repo to deploy everything.

The commit I've since proposed to overcome the GitOps hurdle is to `istioctl operator init` [from within the cluster expressed as a Job](https://gist.github.com/dat-billyf/7fcf23e7a1c3c1952d304c525f93e420), which seems to work very consistently.

Out of curiosity to answer your question, I spun up a new EKS cluster this morning, and did the following:

```
$ git describe --tags
1.8.1
$ helm template manifests/charts/istio-operator/ --set hub=docker.io/istio --set tag=1.8.1     --set operatorNamespace=istio-operator --set istioNamespace=istio-system | kubectl apply -f -
namespace/istio-operator created
serviceaccount/istio-operator created
clusterrole.rbac.authorization.k8s.io/istio-operator created
clusterrolebinding.rbac.authorization.k8s.io/istio-operator created
service/istio-operator created
deployment.apps/istio-operator created
$ samples/multicluster/gen-eastwest-gateway.sh --mesh primary --cluster billyf-istio-control --network non-prod | kubectl apply -f -
error: unable to recognize "STDIN": no matches for kind "IstioOperator" in version "install.istio.io/v1alpha1"
$ kubectl get customresourcedefinitions --all-namespaces
NAME                                         CREATED AT
eniconfigs.crd.k8s.amazonaws.com             2021-01-04T17:37:22Z
helmreleases.flux.weave.works                2021-01-04T17:41:02Z
securitygrouppolicies.vpcresources.k8s.aws   2021-01-04T17:37:25Z
```

It's clear that the crds weren't created here based upon the steps I was able to extract from all my testing that I didn't fully capture here. So I guess we'll just go with the [Job](https://gist.github.com/dat-billyf/7fcf23e7a1c3c1952d304c525f93e420) for now since that seems to be the most well supported path that enables easily seeing how the last deployment was done, as well as an easy upgrade path (i.e. building out an updated docker image for istioctl & following future upgrade steps).

**Comment by morvencao** [comment]
Thanks @dat-billyf I found that `helm3 template` command by default don't include the CRDs, see: https://github.com/helm/helm/issues/6930
We should add another flag `--include-crds` to output the CRDs as well. I'll update the doc for this.

**Comment by dat-billyf** [comment]
Thank you!
