### ISSUE TITLE
unknown type: envoy.extensions.upstreams.http.v3.HttpProtocolOptions

### ISSUE THREAD

**Issue by rognierbenoit** [istio/istio#29832]
**Bug description**

Running the example file found at
https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/grpc_json_transcoder_filter#sample-envoy-configuration

returns the error

`unknown type: envoy.extensions.upstreams.http.v3.HttpProtocolOptions`

**Steps to reproduce the bug**

create a file 'test.yaml' from https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/grpc_json_transcoder_filter#sample-envoy-configuration

`$ envoy -c test.yaml`

**Version**

```
$ envoy --version
envoy  version: e98e41a8e168af7acae8079fc0cd68155f699aa3/1.16.2/clean-getenvoy-be6132a-envoy/RELEASE/BoringSSL
```

**How was Envoy installed?**

Install followed the procedure described here:
https://www.envoyproxy.io/docs/envoy/latest/start/install#install-envoy-on-ubuntu-linux 

**Environment where the bug was observed (cloud vendor, OS, etc)**

```
$ uname -a
Linux ubuntu 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by rognierbenoit** [comment]
seems to be duplicate of #14272

**Comment by howardjohn** [comment]
This does not seem related to Istio at all, and should be an Envoy issue. Seems one is already open: https://github.com/envoyproxy/envoy/issues/14545. Thanks!
