### ISSUE TITLE
URL regex match NOT support for in delegated VS, makes ingress's url mapping NOT work. 

### ISSUE THREAD

**Issue by idouba** [istio/istio#29845]
**Bug description**
"url match does not support regex match for delegating" error in case of regex url in delegated VS. 

Thanks to  Virtual Service Chainning #22118, help decouple the routing rules of each service with each other and avoide big Virtualservice.  In product seniro, usually  root VS specifys the mappings of path and delegated VS.  But it turned out that  regex decscribed  ingress path is NOT permitted. It is  common product case  in  kubernets ingress and  istio ingress gateway to use regex url .

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by sonnyhcl** [comment]
not stale. vote one for enable url regex with delegate
