### ISSUE TITLE
Routing Rules tests are not deterministic - e2e-suite-rbac-auth and pilot-e2e fail intermittently

### ISSUE THREAD

**Issue by liminw** [istio/istio#2985]
Here is one instance:
https://k8s-gubernator.appspot.com/build/istio-prow/e2e-suite-rbac-auth/577

There were several failures in the log:
I0130 19:22:59.801] 2018-01-30T19:22:59.725514Z	error	Failed database routing! normal-user in v1. Error could not find glyphicon-star in response
I0130 19:23:32.316] --- FAIL: TestDbRoutingMysql (71.84s)
....
I0130 19:26:52.835] 2018-01-30T19:26:52.835329Z	info	Running command kubectl get namespace demo-test-22921e65dca442d59c92496a318
I0130 19:26:53.344] 2018-01-30T19:26:53.201407Z	info	Command output: 
I0130 19:26:53.344]  Error from server (NotFound): namespaces "demo-test-22921e65dca442d59c92496a318" not found
I0130 19:26:53.344] , err: exit status 1
I0130 19:26:53.345] 2018-01-30T19:26:53.343901Z	info	namespace demo-test-22921e65dca442d59c92496a318 deleted
I0130 19:26:53.345] 
I0130 19:26:53.345] 2018-01-30T19:26:53.343922Z	info	Namespace demo-test-22921e65dca442d59c92496a318 deletion status: true
I0130 19:26:53.345] 2018-01-30T19:26:53.343931Z	info	Cleanup complete
I0130 19:26:53.508] exit status 1
I0130 19:26:53.509] FAIL	istio.io/istio/tests/e2e/tests/bookinfo	1106.365s
I0130 19:26:53.794] tests/istio.mk:67: recipe for target 'e2e_bookinfo' failed
W0130 19:26:53.822] make: *** [e2e_bookinfo] Error 1
W0130 19:26:53.823] + cp -a /tmp/istio.e2e.003357452 /tmp/istio.e2e.014829598 /tmp/istio.e2e.170754369 /tmp/istio.e2e.447498981 /tmp/istio.e2e.581032184 /tmp/istio.e2e.792559208 /tmp/istio.e2e.810178374 /tmp/istio.e2e.899396263 /tmp/istio.e2e.908648170 /home/bootstrap/go/src/istio.io/istio/_artifacts
E0130 19:26:53.823] Build failed
I0130 19:26:53.823] process 345 exited with code 2 after 36.5m
E0130 19:26:53.823] FAIL: e2e-suite-rbac-auth

**Comment by andraxylia** [comment]
This is an example of flakiness. The e2e tests apply a routing rule and sleep for 30s, then they check the result by verifying the response. We need a more deterministic way to verify the routing rules have taken effect, maybe by looking at the envoy stats for RDS incrementing, or some log in pilot.

Ideally, but not necessarily part of this PR, we would not check for red star/black star in the response, but would have the server envoy adding the version to the response, so we can re-use that tests everywhere regardless of the application.

**Comment by andraxylia** [comment]
The e2e-pilot tests use a different framework, but are still not determinsitic: out of 100 requests, 50 plus minus 5 have to make it to the destination.

**Comment by ldemailly** [comment]
as a side note though, that test (the DB test) was stable for months and the change / "flakiness" is recent
so I think there is something here and extending timeouts for instance would just hide the real issue

**Comment by andraxylia** [comment]
Right. This issue is not about extending timeout, it's about finding when the RR are effective. With a couple of added logs, we can also measure how long it took for them to propagate.

**Comment by andraxylia** [comment]
Another example of unreliable tests is here:
https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/2862/istio-pilot-e2e/2426/

I0206 06:28:54.256] * attempt 0 expected 75 requests (+/-5) to reach v1 => Got 67
I0206 06:28:54.256] * attempt 0 expected 25 requests (+/-5) to reach v2 => Got 33

Until this issue is fixed, I will increase the tolerance of tests to +/-10.

**Comment by ldemailly** [comment]
https://circleci.com/gh/istio/istio/33425 
      --- FAIL: TestPilot/Auth/routing-rules (105.40s)
        	pilot_test.go:186: 8 errors occurred:
        		
        		* v1alpha2 routing 75 percent to c-v1, 25 percent to c-v2 attempt 0 expected 25 requests (+/-5) to reach v2 => Got 0
        		* v1alpha2 routing 75 percent to c-v1, 25 percent to c-v2 attempt 1 expected 75 requests (+/-5) to reach v1 => Got 67
        		* v1alpha2 routing 75 percent to c-v1, 25 percent to c-v2 attempt 1 expected 25 requests (+/-5) to reach v2 => Got 31
        		* v1alpha2 routing 75 percent to c-v1, 25 percent to c-v2 attempt 2 expected 75 requests (+/-5) to reach v1 => Got 84
        		* v1alpha2 routing 75 percent to c-v1, 25 percent to c-v2 attempt 2 expected 25 requests (+/-5) to reach v2 => Got 16
        		* v1alpha2 routing 100 percent to c-v1 with websocket upgrades attempt 0 expected 100 requests (+/-5) to reach v1 => Got 0
        		* v1alpha2 routing 100 percent to c-v1 with websocket upgrades attempt 1 expected 100 requests (+/-5) to reach v1 => Got 0
        		* v1alpha2 routing 100 percent to c-v1 with websocket upgrades attempt 2 expected 100 requests (+/-5) to reach v1 => Got 0
        --- PASS: TestPilot/Auth/routing-rules-to-egress (174.60s)

**Comment by nmittler** [comment]
@ldemailly @andraxylia it turns out that many of the problems with the pilot e2e tests are due to the fact that we're running in a cluster with a single node.  See details in https://github.com/istio/istio/pull/3663#issuecomment-367494093.  The fix is #3663 and should land soon.  We can re-evaluate once that's in.  Stay tuned.

**Comment by ldemailly** [comment]
I'm hopeful but it sounds 2 good to be true if all our woes can be fixed at once. let's see :-)

**Comment by nmittler** [comment]
@ldemailly Agreed.  My fix is only for prow ... Circle CI seems to have the problem as well, however.

**Comment by cmluciano** [comment]
@nmittler #3663 is merged, do we need a similar update for circleci?

**Comment by nmittler** [comment]
@cmluciano IIRC, circleci uses minikube which shouldn't have the same problems.

**Comment by cmluciano** [comment]
Cool, is this issue closable ?

**Comment by nmittler** [comment]
@cmluciano I believe some of the route tests are flaky ... it's not related to #3663.

**Comment by ayj** [comment]
@nmittler - what are the next steps for this issue? Was it resolved by #3663?

**Comment by nmittler** [comment]
Yeah I think so.  Let's close it for now ... we can open a new issue if necessary.
