### ISSUE TITLE
Istio proxy uses up all available ports for handling websocket connections and refuse further connections

### ISSUE THREAD

**Issue by Jxic** [istio/istio#29863]
I wasn't sure if this is a bug or an expected behavior, but before raising this issue, I have been looking for any related issue or documents for days and there's nothing I could find helpful

[ ] Docs
[ ] Installation
[ x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
The maximum number of websocket connections per pod should not be bound by the port range of that pod
**Steps to reproduce the bug**
create a websocket service pod with istio-proxy injected as side car, then use client to create as many connections as possible, and it will start to fail when the number of connections goes beyond the number of available ports on the service pod. I was able to increase the number of connections by specifying the following in YAML, which actually changes the port range:

    securityContext:
        sysctls:
        - name: net.ipv4.ip_local_port_range
          value: 1024 65535

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
Istio:
client version: 1.7.4
control plane version: 1.5.6
data plane version: 1.5.6 (221 proxies)
k8s:
Client Version: v1.14.3-tk8s.2
Server Version: v1.14.3-tk8s-v1.1-1

**How was Istio installed?**
it comes with the cloud
**Environment where the bug was observed (cloud vendor, OS, etc)**
tencent cloud
Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
> use client to create as many connections as possible, and it will start to fail when the number of connections goes beyond the number of available ports on the service pod

I am not sure I fully understand - wouldn't this happen without Istio as well?

**Comment by Jxic** [comment]
> > use client to create as many connections as possible, and it will start to fail when the number of connections goes beyond the number of available ports on the service pod
> 
> I am not sure I fully understand - wouldn't this happen without Istio as well?

Maybe I didn't make the issue clear. The number of connections a single service pod could handle should only be limited by the CPU or RAM resources, provided that the server gets configured correctly (max open file, max pid, etc). But in my case,  when I have istio proxy handling the connections, the bottleneck seems to be the number of available port on the pod, which does not really make sense to me

**Comment by howardjohn** [comment]
Regardless if Istio, the number of connections will be limited by the ports available if local ip, remote ip, and remote port are the same. https://making.pusher.com/ephemeral-port-exhaustion-and-how-to-avoid-it/ is a good explanation of this.

So what I think this means is either one of these three things is different with istio. Using ss to investigate is a good idea

**Comment by Jxic** [comment]
> Regardless if Istio, the number of connections will be limited by the ports available if local ip, remote ip, and remote port are the same. https://making.pusher.com/ephemeral-port-exhaustion-and-how-to-avoid-it/ is a good explanation of this.
> 
> So what I think this means is either one of these three things is different with istio. Using ss to investigate is a good idea

yeah i tried ss before, and what I found was that the number of available ports runs out as more incoming connections occur. I am just not sure if it's expected that istio proxy would open a port for each new connection, and would this behavior be different in the future version?

**Comment by Jxic** [comment]
following up on the previous discussion, is there a way to configure istio proxy to use tcp multiplexing for all tcp connections?

**Comment by sunnoy** [comment]
maybe envoy limit it ,

client -> pod[envoy -> server]

in server pod the socket is :
127.0.0.1:<ip_local_port_range> -> 127.0.0.1:<server listen port>

the defualt ip_local_port_range is 32768	60999, so the server pod max websocket conn is 60999-32768=28231 ?

**Comment by mtenrero** [comment]
is there any way to overcome this limitation? for high I/O purposes this heavily limits the performance of the underlying application

**Comment by jmrubio** [comment]
There is an easy way to reproduce it by decreasing the number of ephemeral ports. 

I have also detected that the number of max concurrent connections is divided by the number of destination ports when I was expecting them to be multiplied as I was adding another destination port to the tuple [source_ip_address, source_port, destination_ip_address, destination_port] that limit the max number of available connections.

So with 1000 ephemeral ports it is possible to have up to 1000 concurrent connections with 1 destination port but with 2 destination ports only 500 concurrent connections are possible when I would expect 2000.
