### ISSUE TITLE
Multicluster controller startup sync may miss clusters

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#29868]
This is theoretical, I haven't verified it. I think the multicluster controller may get the Secret event, add it to the queue, mark itself "synced", *than* actually have the controller up and running.

The end result is an early proxy may connect to istiod before it has all the clusters connected, and get incorrect info.

cc @stevenctl

**Comment by stevenctl** [comment]
Are you concerned that the secret controller is marking itself ready too soon? Or that the kube controllers aren't fully synced when we mark the discovery server ready? 

If you're worried about the former: 

Doesn't `WaitForCacheSyncInterval` mean that we know all the secret events are on the queue? 

Currently we wait for the informer to have synced, then we queue a signal that will make the controller's `HasSynced` return true. That signal should be processed after all the secret events. 

https://github.com/istio/istio/blob/f10a97b57411dfe44845499a368c88f25e0ae535/pkg/kube/secretcontroller/secretcontroller.go#L175

**Comment by howardjohn** [comment]
Oh nice, I missed the initialSyncSignal part. That was my main concern.

In the main k8s registry we solved the same problem with an extra SyncAll call, would that have been solved with the same (simpler/more efficient) initialSyncSignal? Or I guess the issue was we need all the events to be process from all types since there are cross references?

I think we may still have an issue that we start all the controllers, but we never verify they are synced before we set HasSynced=true in the secretcontroller?

**Comment by stevenctl** [comment]
I think we verify that all the controllers are synced here:
https://github.com/istio/istio/blob/a40fe583908a37e5d60868bb60fde1259988bff1/pilot/pkg/bootstrap/server.go#L772

**Comment by stevenctl** [comment]
>  Or I guess the issue was we need all the events to be process from all types since there are cross references?

IIRC the issue was that for initial sync, service/endpoint events would be processed in a different order than they would normally be, and that caused endpoint events to be dropped since there was no related servce.

**Comment by howardjohn** [comment]
Ah so here
```go
	if s.multicluster != nil && !s.multicluster.HasSynced() {
		return false
	}
```

after this point we know all clusters have been added

then 
```go
 if !s.ServiceController().HasSynced() { 

```

must check all of them are sync.

Seems like its all good then, thanks!
