### ISSUE TITLE
Using revision flag in IstioOperator CRD breaks deployment

### ISSUE THREAD

**Issue by alen-z** [istio/istio#29881]
**Bug description**
1. If using istio-operator and applying `IstioOperator` CRD with `spec.revision` — Istio does not work.
2. If deployed with `istioctl` and using `--revision` flag — Istio does not work.

So far I've noticed that `ValidatingWebhookConfiguration` and `MutatingWebhookConfiguration` do not get proper `istiod` service reference in the YAML configuration (does not include revision suffix) during istio-operator depoying Istio based on CRD. `MutatingWebhookConfiguration` gets updated revision suffix in `webhooks.clientConfig.service.name`.

 I'm aware of different label that needs to be used when configuring automatic sidecar injection when revision is to be used. This is how I tested deployment.

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[x] Upgrade

**Expected behavior**
Istio with set revision value works the same as default deployment, either using `istioctl` or istio-operator.

**Steps to reproduce the bug**
1. Use revision flag to deploy Istio.
2. Set revision label to one of the namespaces.
3. Restart Pod and check if sidecar was added.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
1.8.1

**How was Istio installed?**
1. `istioctl manifest generate --revision 1-8-1 | kubectl delete -f -`
2. Helm istio-operator with revision set + `IstioOperator` CRD based on default profile.

**Environment where the bug was observed (cloud vendor, OS, etc)**
GCP Kubernetes cluster.

**Comment by morvencao** [comment]
Duplicated with https://github.com/istio/istio/issues/27501

**Comment by christian-posta** [comment]
Another possible fix: https://github.com/istio/istio/pull/30286
