### ISSUE TITLE
OpenShift route doesn't work once a namespace is added to Istio member roll

### ISSUE THREAD

**Issue by barryzhounb** [istio/istio#29888]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

I have OpenShift environment, I am creating a http route to my service, the route works well, I can access my service via route from outside cluster. Now I add the namespace that my service sits into Istio member roll, then I could not access my service with the same way, I am pretty sure Istio has an impact for this route. I am wondering how Istio has an impact on the route? and how to fix it or avoid it?

[ ] Docs
[ ] Installation
[ x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**

Istio 1.6.x

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
This should probably be filed in https://github.com/Maistra, Istio does not have a "member roll" concept.

**Comment by barryzhounb** [comment]
The issue is invalid, because I didn't deploy virtualservice and and gateway for my traffic. 

So I will mark it as invalid and close it.
