### ISSUE TITLE
Dns resolve breaks down coredns

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#29898]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

During our scalability test based on the default intsallation, when we increase the proxies number to less than 20K, the dns is broken down. 

We found that each proxy send dns resolve request for `zipkin.istio-system.xxx` every 5 seconds. This is useless as we have no zipkin service deployed at all.

[ ] Docs
[ ] Installation
[ ] Networking
[X] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
Best solution: set `tracing: {}` in proxy config, which will disable zipkin cluster.

but we can also make the default TTL more than 5s

**Comment by howardjohn** [comment]
And longer term we will have no default, once we have the Telemetry API (tracing will be dynamic, not in bootstrap). I have been avoiding trying to change the bootstrap default since this is coming "soon"

**Comment by jejikenwogu** [comment]
@howardjohn I'm still seeing zipkin requests after adding `tracing: {}` to my proxy config.  Was the intended result that the zipkin requests would be disabled?  Here's what I have in my Istio Operator:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  meshConfig:
    defaultConfig:
      tracing: {}
```

It doesn't look to be propagated to the proxy bootstrap configs though:
```
{
  "bootstrap": {
    "node": {
      ...
        "metadata": {
          ...
            "PROXY_CONFIG": {
              ...
                "tracing": {
                  "zipkin": {
                    "address": "zipkin.istio-system:9411"
                  }
                }
            },
            ...
        },
        ...
    },
    ...
    "staticResources": {
      ...
      "clusters": [
        ...
        {
          "name":"zipkin",
          "type":"STRICT_DNS",
          "connectTimeout":"1s",
          "loadAssignment":{
            "clusterName":"zipkin",
            "endpoints":[
            {
              "lbEndpoints":[
              {
                "endpoint":{
                  "address":{
                    "socketAddress":{
                      "address":"zipkin.istio-system",
                      "portValue":9411
                    }
                  }
                }
              }
              ]
            }
            ]
          },
          "respectDnsTtl":true,
          "dnsLookupFamily":"V4_ONLY"
        }
      ]
    },
    "tracing": {
      "http": {
        "name": "envoy.tracers.zipkin",
        "typedConfig": {
          "@type": "type.googleapis.com/envoy.config.trace.v3.ZipkinConfig",
          "collectorCluster": "zipkin",
          "collectorEndpoint": "/api/v2/spans",
          "traceId128bit": true,
          "sharedSpanContext": false,
          "collectorEndpointVersion": "HTTP_JSON"
        }
      }
    },
    "lastUpdated": "2021-03-15T03:35:50.342Z"
}
```
