### ISSUE TITLE
Create e2e for Task "Test Istio Auth"

### ISSUE THREAD

**Issue by sebastienvas** [istio/istio#299]

**Comment by myidpt** [comment]
We have e2e auth test in istio/pilot, what's the plan of this bug?

**Comment by sebastienvas** [comment]
Why in pilot ? We don't run those for release qualification. We need something to gate the release.

**Comment by sakshigoel12** [comment]
We have in pilot, Laurent is writing a e2e test

**Comment by myidpt** [comment]
Just talked with Laurent. I'm going to write the tests to cover:
https://istio.io/docs/tasks/installing-istio.html with Istio auth, in istio/istio/tests/e2e/tests/bookinfo.
And Laurent may write a minimal test for Istio auth, at somewhere else in istio/istio.

**Comment by ldemailly** [comment]
ty! been busy with whackamole other issues sorry for delay

**Comment by ldemailly** [comment]
this is done
