### ISSUE TITLE
Setting pilot.jwksResolverExtraRootCA using Secrets

### ISSUE THREAD

**Issue by DineshKrishnanG** [istio/istio#29901]
**Describe the feature request**
The extra root CA can be set using below options (Reference: https://github.com/istio/istio/pull/17176)
1. When installing via helm, you can now specify a PEM-encoded certificate in pilot.jwksResolverExtraRootCA in your values.yaml to trust an additional CA certificate
2. During installation you can directly specify your certificate as a command-line argument

Additional option to set the pilot.jwksResolverExtraRootCA contents from secrets will be helpful. As secrets are used to store contents like PEM-encoded certificates. Referencing its mount path in values.yaml will improve the usability.

**Describe alternatives you've considered**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**
https://discuss.istio.io/t/setting-pilot-jwksresolverextrarootca-using-secrets/9305

**Comment by howardjohn** [comment]
I think you can already mount arbitrary things into the pod which may solve this generically. I may be wrong

**Comment by DineshKrishnanG** [comment]
> I think you can already mount arbitrary things into the pod which may solve this generically. I may be wrong

Thanks for the response. 

As I understand, this PEM-encoded certificate is required by 'istio-pilot' to communicate and retrieve JWKS. So shouldn't it be part of the istio discovery helm chart?

Not clear on above comments, are you referring to mount the secret for 'istiod' pod?

**Comment by liminw** [comment]
This feature request makes sense to me. @DineshKrishnanG Can you send a PR to implement it?

**Comment by howardjohn** [comment]
I am against adding this; we should do https://github.com/istio/istio/issues/29973 instead in my opinion.
