### ISSUE TITLE
sidecar injector timing out

### ISSUE THREAD

**Issue by michaelst** [istio/istio#29912]
**Bug description**

I am doing a brand new installation of istio 1.8.1 on gke. I then tried to install the sleep sample, however, I get this error when I have the automatic sidecar injection enabled on the namespace. 
``` 
Internal error occurred: failed calling webhook "sidecar-injector.istio.io": Post https://istiod.istio-system.svc:443/inject?timeout=30s: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

If I make a curl call from another pod to that endpoint I get a 400 response.

I noticed istiod has a bunch of logs that looks like this: 
```
2021-01-07T16:31:05.334868Z	info	validationController	Not ready to switch validation to fail-closed: dummy invalid config not rejected
2021-01-07T16:31:05.335414Z	info	validationController	validatingwebhookconfiguration istiod-istio-system (failurePolicy=Ignore, resourceVersion=88820158) is up-to-date. No change required.
2021-01-07T16:31:05.335459Z	info	validationController	Reconcile(enter): retry dry-run creation of invalid config
```

[ ] Docs
[X] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

Should be able to get pod running with sidecar.

**Steps to reproduce the bug**

```
kubectl label namespace default istio-injection=enabled
kubectl apply -f samples/sleep/sleep.yaml
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
client version: 1.8.1
control plane version: 1.8.1
data plane version: none
```

```
Client Version: v1.17.14-dispatcher
Server Version: v1.17.14-gke.400
```

**How was Istio installed?**
```
istioctl install --set profile=minimal \
 --set values.cni.cniBinDir=/home/kubernetes/bin \
 --set 'values.cni.excludeNamespaces[0]'=kube-system \
 --set 'values.cni.excludeNamespaces[1]'=istio-system \
 --set 'values.cni.excludeNamespaces[2]'=backend \
 --set components.cni.enabled=true \
 --set components.cni.namespace=kube-system
```
**Environment where the bug was observed (cloud vendor, OS, etc)**
GKE - 1.17.14-gke.400

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
https://github.com/istio/istio/wiki/Troubleshooting-Istio#sidecar-injection may be useful, in particular the firewall note

**Comment by michaelst** [comment]
Ah that did it, however, I do not have a private cluster so I had ignored that note. That may need to be updated in the docs to apply to all clusters.

**Comment by howardjohn** [comment]
It definitely does not apply to all clusters, although it may not be just private clusters it applies to perhaps? Basically, the api server needs connectivity to istiod (in cluster), so any firewall rules may block that potentionally
