### ISSUE TITLE
TestAgent unit test flaking

### ISSUE THREAD

**Issue by esnible** [istio/istio#29920]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/29918/unit-tests_istio/1347272616779452416

TestAgent failed when the only changes were to a galley/istioctl analyzer.

```
istio-agent: TestAgent 52s
istio-agent: TestAgent/VMs_provisioned_certificates_-_short_lived 10s
    agent_test.go:243: retry.UntilSuccessOrFail: timeout while waiting (last error: file is unchanged)
```

**Comment by howardjohn** [comment]
I am surprised, I ran this overnight in a loop before merging without failures :slightly_frowning_face:

**Comment by howardjohn** [comment]
looks like the test node is so busy signing a single CSR takes 2.5s...
