### ISSUE TITLE
`checksum/config-volume` cannot be a label

### ISSUE THREAD

**Issue by nixgadget** [istio/istio#2993]
This will cause issues https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/mixer/templates/deployment.yaml#L11.

Im guessing it should be under `annotations`.
`metadata.labels` only allows 63 characters.

**Comment by elevran** [comment]
the sha256sum is 65 characters long, over the 63 character limit. The pilot and sidecar-inject templates are using an annotation, not a label

**Comment by nixgadget** [comment]
Yup they should be using `annotations`.

**Comment by elevran** [comment]
fixed already
