### ISSUE TITLE
Link mentioned proxying-legacy-services-using-egress-gateways blog does not work.

### ISSUE THREAD

**Issue by sidheshdivekar29** [istio/istio#29932]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
One of the link mentioned in the documentation returns 404.

`kubectl apply -n httpbin -f  https://raw.githubusercontent.com/istio/istio/release-1.8/1.8.0/samples/sleep/sleep.yaml
`mentioned 

Above link mentioned in service to service section is not working.
https://istio.io/latest/blog/2020/proxying-legacy-services-using-egress-gateways/#service-to-service-access

[ * ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Link should work.

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by hzxuzhonghu** [comment]
Let me file a simple a fix in istio/istio.io

**Comment by hzxuzhonghu** [comment]
https://github.com/istio/istio.io/pull/8752

**Comment by howardjohn** [comment]
https://github.com/istio/istio.io/pull/8752 fixes this I think

**Comment by sidheshdivekar29** [comment]
@howardjohn Am seeing more issues.

Looks like "exec" is missing in the command below. "kubectl exec -n httpbin"

`kubectl -n httpbin "$(kubectl get pod -n httpbin -l app=sleep -o jsonpath={.items..metadata.name})" -- curl -vvv http://<my-proxied-service-hostname>/status/200`

And even then the curl is failing for service-to-service access.

```
$ kubectl exec -n httpbin sleep-f8cbf5b76-g88z7 -- curl -vvv "http://proxy-service.myeventarena.com:443/status/200"
Defaulting container name to sleep.
Use 'kubectl describe pod/sleep-f8cbf5b76-g88z7 -n httpbin' to see all of the containers in this pod.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Could not resolve host: proxy-service.myeventarena.com
* Closing connection 0
curl: (6) Could not resolve host: proxy-service.myeventarena.com
command terminated with exit code 6
```

External access is working fine.

```
$ curl -vk -HHost:proxy-service.myeventarena.com --resolve "proxy-service.myeventarena.com:15443:127.0.0.1" --cacert example.com.cert "https://proxy-service.myeventarena.com:15443/status/200"
---snip---
* Connection state changed (MAX_CONCURRENT_STREAMS == 2147483647)!
< HTTP/2 200
< date: Fri, 08 Jan 2021 19:22:11 GMT
< content-type: text/html; charset=utf-8
< content-length: 0
< server: istio-envoy
< access-control-allow-origin: *
< access-control-allow-credentials: true
< x-envoy-upstream-service-time: 122
<
* Connection #0 to host proxy-service.myeventarena.com left intact
* Closing connection 0
```
