### ISSUE TITLE
CI/CD issue: integ-telemetry fails to run on non GKE platforms

### ISSUE THREAD

**Issue by jacob-delgado** [istio/istio#29948]
**Bug description**

`integ-telemetry` fails to run as a prow job on non-GKE build systems due to Stackdriver tests failing (tests/integration/telemetry/stackdriver).

Some of the pods were not able to be started. Here is a snippet

```
2020-12-30T21:12:50.771992Z	info	Epoch 0 starting
2020-12-30T21:12:50.771973Z	info	Opening status port 15020
2020-12-30T21:12:50.775401Z	error	Failed to generate bootstrap config: unable to process Stackdriver tracer: metadata: GCE metadata "project/project-id" not defined
```

which I traced to https://github.com/istio/istio/blob/62043ab4ff4dbce431c0ddf04f5dfcbd4279bac0/pkg/bootstrap/config.go#L310

This is similar to https://github.com/istio/istio/issues/28200 which was previously fixed.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[X] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

integration tests all pass on run when run on prow not running on GKE.

**Steps to reproduce the bug**

Built off of master

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Non-GKE prow build cluster

**Comment by jacob-delgado** [comment]
cc @dex80526

**Comment by jacob-delgado** [comment]
cc @douglas-reid @mandarjog @bianpengyuan @gargnupur 

I know there is the fake/mock stackdriver, but after looking at the code I'm not sure how to test this as it calls a static function on the `cloud.google.com/go/compute/metadata` dependency.

**Comment by bianpengyuan** [comment]
Dup of https://github.com/istio/istio/issues/29268? Doug has a draft pr for this: https://github.com/istio/istio/pull/29882

**Comment by jacob-delgado** [comment]
Yes, I'll close this one.

Duplicate of https://github.com/istio/istio/issues/29268
