### ISSUE TITLE
Improve support around Pod IP listeners

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#29940]
Current state: if a pod listens on its Pod IP, it will not get traffic (we send to localhost). This can be worked around in 1.9+ with Sidecar.

We should either make it automatic, or make it debugable.

To make it automatic, we can consider looking into if replacing the cluster with an ORIGINAL_DST for inbound would work

For debugging, I am not sure, it would probably require exec into the pods.

**Comment by ssuchter** [comment]
Idea raised for debugging: Make istioctl analyze report this. Maybe we could build the software to detect this listening state into the software that is already deployed into the istio-proxy, so we don't have to do exec into the pods.

**Comment by howardjohn** [comment]
design doc: https://docs.google.com/document/d/1j-5_XpeMTnT9mV_8dbSOeU7rfH-5YNtN_JJFZ2mmQ_w/edit#
