### ISSUE TITLE
Enable STS token exchange for XDS flow

### ISSUE THREAD

**Issue by lei-tang** [istio/istio#29943]
**Describe the feature request**
Currently, STS token exchange is not enabled for XDS flow.  This feature is to enable STS token exchange for XDS flow.

**Describe alternatives you've considered**
No alternative since XDS flow should be able to turn on/off token exchange.

[ ] Docs
[ ] Installation
[X ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
https://github.com/istio/istio/pull/29942 does this
