### ISSUE TITLE
How to install istio 0.4 ingress controller and addons with Helm Chart?

### ISSUE THREAD

**Issue by kubebc** [istio/istio#2994]
Hi, Team,
How to install istio 0.4 ingress controller and addons with Helm Chart?  and how to control istio version in values.yaml?

fyi, i followed guide here. https://github.com/istio/istio/tree/master/install/kubernetes/helm
no "istio-ingress" and addons

istio/install$ ./updateVersion.sh
istio/install/kubernetes/helm$ helm install istio --name istio --namespace=istio-system
$ helm list -a
NAME                    REVISION        UPDATED                         STATUS          CHART           NAMESPACE
istio                   2               Wed Jan 31 13:40:24 2018        DEPLOYED        istio-0.5.0     istio-system
$ kubectl get pods -n istio-system
NAME                           READY     STATUS             RESTARTS   AGE
istio-istio-9c67fbd65-vmzqg    1/1       Running            0          2m
istio-mixer-8548d4c889-9ds9c   2/3       CrashLoopBackOff   4          2m
istio-pilot-5db4cfcd4-vnd5j    2/2       Running            0          2m

**Comment by nixgadget** [comment]
@kubebc Is this the version you are following ? https://github.com/istio/istio/tree/0.4.0/install/kubernetes/helm/istio

What you linked is the master bdw.

**Comment by sdake** [comment]
@kubebc master instructions merging soon.  Note 0.5.0 helm charts appear DOA - so you will need a master version (which work well enough without automatic sidecar injection).  The master documentation PR is here: https://github.com/istio/istio.github.io/pull/875

Cheers
-steve

**Comment by sdake** [comment]
Reference the Helm add-ons issue here: https://github.com/istio/istio/issues/2629

**Comment by costinm** [comment]
It appears to work now ( with nightly builds - will be updated once 0.6 is out)
