### ISSUE TITLE
istioctl x  add-to-mesh fails to inject sidecar to deployment

### ISSUE THREAD

**Issue by tanjunchen** [istio/istio#29950]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

```
[root@test-10 mesh_test]# istioctl x add-to-mesh  deployment productpage-v1 -n ldd
deployment productpage-v1.ldd updated successfully with Istio sidecar injected.
Next Step: Add related labels to the deployment to align with Istio's requirement: https://istio.io/v1.8/docs/ops/deployment/requirements/
[root@test-10 mesh_test]# istioctl x add-to-mesh  deployment productpage-v1 -n ldd
===> Skipping injection because "productpage-v1" has injected "istio-proxy" sidecar already

deployment productpage-v1.ldd updated successfully with Istio sidecar injected.
Next Step: Add related labels to the deployment to align with Istio's requirement: https://istio.io/v1.8/docs/ops/deployment/requirements/
[root@test-10 mesh_test]# istioctl x remove-from-mesh  deployment productpage-v1 -n ldd
deployment "productpage-v1.ldd" updated successfully with Istio sidecar un-injected.
[root@test-10 mesh_test]# istioctl x add-to-mesh  deployment productpage-v1 -n ldd
===> Skipping injection because "productpage-v1" has sidecar injection disabled

deployment productpage-v1.ldd updated successfully with Istio sidecar injected.
Next Step: Add related labels to the deployment to align with Istio's requirement: https://istio.io/v1.8/docs/ops/deployment/requirements/
```

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[x] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**
```
istioctl x add-to-mesh  deployment productpage-v1 -n xxx
istioctl x remove-from-mesh  deployment productpage-v1 -n ldd
istioctl x add-to-mesh  deployment productpage-v1 -n ldd
result:
===> Skipping injection because "productpage-v1" has sidecar injection disabled

deployment productpage-v1.ldd updated successfully with Istio sidecar injected.
Next Step: Add related labels to the deployment to align with Istio's requirement: https://istio.io/v1.8/docs/ops/deployment/requirements/
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
istioctl version --remote
client version: 1.8.1
control plane version: 1.8.1
data plane version: 1.8.1 (5 proxies)

```

**How was Istio installed?**
```
istioctl operator init
kubectl create ns istio-system
kubectl apply -f - <<EOF
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: example-istiocontrolplane
spec:
  profile: demo
EOF
```
It seems that `istioctl x remove-from-mesh` not remove the annotations(sidecar.istio.io/inject sidecar.istio.io/status) and labels(istio.io/rev) .  **My understanding is that after removing the sidecar, we should ensure that the deployment remains exactly the same as before the sidecar is injected, without leaving traces of annotations or labels.**
**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by tanjunchen** [comment]
after remove the annotations *sidecar.istio.io*, it still fail to inject sidecar to deployment. the logs is
```
2021-01-09T16:20:02.478465Z	info	xdsproxy	Initializing with upstream address istiod.istio-system.svc:15012 and cluster Kubernetes
2021-01-09T16:20:02.478508Z	info	sds	Start SDS grpc server
2021-01-09T16:20:02.478632Z	info	xdsproxy	adding watcher for certificate var/run/secrets/istio/root-cert.pem
Error: invalid prometheus scrape configuration: application port is the same as agent port, which may lead to a recursive loop. Ensure pod does not have prometheus.io/port=15020 label, or that injection is not happening multiple times
2021-01-09T16:20:02.478804Z	info	Prometheus scraping configuration: {true /stats/prometheus 15020}
2021-01-09T16:20:02.478831Z	error	invalid prometheus scrape configuration: application port is the same as agent port, which may lead to a recursive loop. Ensure pod does not have prometheus.io/port=15020 label, or that injection is not happening multiple times
```
*`invalid prometheus scrape configuration: application port is the same as agent port, which may lead to a recursive loop. Ensure pod does not have prometheus.io/port=15020 label, or that injection is not happening multiple times`*

so,i think that `istioctl x remove-from-mesh` ensure that the deployment remains exactly the same as before the sidecar is injected, without leaving traces of annotations or labels.

**Comment by esnible** [comment]
For 1.10, we target **REMOVING THIS SUBCOMMAND.**
