### ISSUE TITLE
Istio 1.7.x: when `PILOT_FILTER_GATEWAY_CLUSTER_CONFIG=true`, `pilot` doesn't push CDS updates into a gateway proxy when a Gateway or a VirtualService changes

### ISSUE THREAD

**Issue by yskopets** [istio/istio#29954]
**Bug description**

In Istio `1.7.x`, when `PILOT_FILTER_GATEWAY_CLUSTER_CONFIG=true`, `pilot` doesn't push CDS updates into a gateway proxy when a `Gateway` or a `VirtualService` changes.

As a result, gateway proxy receives correct `Listener` and `RouteConfiguration` resources, but no `Cluster`.

On the data path, proxied requests fail with HTTP status `503` and `NR` flag ("No route configured for a given request"). 

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

Gateway proxy should be updated consistently.

If a `Gateway` or a `VirtualService` changes, then `pilot` should push to the gateway proxy LDS, RDS and CDS resources.

**Steps to reproduce the bug**

* Install `Istio 1.7.x` with `PILOT_FILTER_GATEWAY_CLUSTER_CONFIG=true`
* Enable ingress gateway (on start up, it will connect to the `pilot` and receive back initial LDS, RDS, CDS resources)
* Apply `Gateway` and `VirtualService` resources
* Make HTTP request via ingress gateway, it will fail with HTTP status `503` and `NR` flag
  ```
  [2021-01-08T18:09:19.449Z] "GET /headers HTTP/1.1" 503 NR "-" "-" 0 0 0 - "10.244.2.1" "Go-http-client/1.1" "08be9bd7-84d6-91fb-b6c3-306fe33d913a" "example.org" "-" - - 10.244.2.102:8080 10.244.2.1:62394 - -
  ```
* Internal logs of the gateway proxy (Envoy) say
  ```
  2021-01-08T18:11:07.696339Z	debug	envoy router	[C16][S1866779939579337677] unknown cluster 'outbound|8080||myapp.example.svc.cluster.local'
  2021-01-08T18:11:07.696447Z	debug	envoy http	[C16][S1866779939579337677] Sending local reply with details cluster_not_found  
  ```
* Envoy `/config_dump` will include
  ```
  "dynamic_route_configs": [
  {
   "version_info": "2021-01-08T18:09:07Z/17",
   "route_config": {
    "@type": "type.googleapis.com/envoy.config.route.v3.RouteConfiguration",
    "name": "http.80",
    "virtual_hosts": [
     {
      "name": "example.org:80",
      "domains": [
       "example.org",
       "example.org:*"
      ],
      "routes": [
       {
        "match": {
         "prefix": "/",
         "case_sensitive": true
        },
        "route": {
         "cluster": "outbound|8080||myapp.example.svc.cluster.local",
  ```
* but no `Cluster` named `outbound|8080||myapp.example.svc.cluster.local`
* logs of `istiod` have no errors

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

`1.7.3` 

**How was Istio installed?**

`IstioOperator`

**Environment where the bug was observed (cloud vendor, OS, etc)**

`KinD`

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by hzxuzhonghu** [comment]
Is this fixed in master?

**Comment by yskopets** [comment]
yes, on `master` this logic now lives in [pilot/pkg/xds/cds.go](https://github.com/istio/istio/blob/master/pilot/pkg/xds/cds.go):

```go
// Map all configs that impacts CDS for gateways.
var pushCdsGatewayConfig = map[config.GroupVersionKind]struct{}{
	gvk.VirtualService: {},
	gvk.Gateway:        {},
}

func cdsNeedsPush(req *model.PushRequest, proxy *model.Proxy) bool {
	...
	for config := range req.ConfigsUpdated {
		if proxy.Type == model.Router {
			if _, f := pushCdsGatewayConfig[config.Kind]; f {
				return true
			}
		}
		...
	}
	...
}
```

**Comment by howardjohn** [comment]
fixed by https://github.com/istio/istio/pull/29955
