### ISSUE TITLE
`make clean` changes git index

### ISSUE THREAD

**Issue by loewenstein** [istio/istio#2996]
Commit 224a9e2 recently made istio certs fixed by removing them from
.gitignore:
security/docker/istio_ca.crt
security/docker/istio_ca.key
security/docker/node_agent.crt
security/docker/node_agent.key

However, the Makefile wasn't updated and `make clean` still removes these files.

**Comment by mattdelco** [comment]
The issue with "make clean" has been addressed by https://github.com/istio/istio/pull/2831 .
