### ISSUE TITLE
Error: cannot find volume serviceaccount token to mount into container "istio-init"

### ISSUE THREAD

**Issue by lklkxcxc** [istio/istio#29964]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

**Steps to reproduce the bug**
serviceaccount Volume exists, but the istio-init mount prompt could not find the volume
kubectl get secret:
```
NAME                                TYPE                                  DATA   AGE
ceph-delete-bucket                  Opaque                                2      151d
ceph-secret                         Opaque                                1      27d
default-token-sp4pg                 kubernetes.io/service-account-token   3      193d
jenkins-admin-token-ggnc7           kubernetes.io/service-account-token   3      166d
mysql-operator-token-nts8g          kubernetes.io/service-account-token   3      180d
nfs-provisioner-token-bxnp2         kubernetes.io/service-account-token   3      55d
ops-token-5fjzz                     kubernetes.io/service-account-token   3      67d
rabbit-ha-rabbitmq-ha               Opaque                                4      170d
rabbit-ha-rabbitmq-ha-token-nzggb   kubernetes.io/service-account-token   3      170d
```

kubernetes events:
```
38m         Warning   Failed                   pod/slave-k8s-zzjd4   Error: cannot find volume "ops-token-5fjzz" to mount into container "istio-init"
25m         Warning   FailedMount              pod/slave-k8s-zxxv8   Unable to attach or mount volumes: unmounted volumes=[istio-podinfo ops-token-5fjzz volume-0 volume-1 workspace-volume volume-2 volume-3 volume-4 istiod-ca-cert istio-envoy istio-data], unattached volumes=[istio-podinfo ops-token-5fjzz volume-0 volume-1 workspace-volume volume-2 volume-3 volume-4 istiod-ca-cert istio-envoy istio-data]: timed out waiting for the condition
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
client version: 1.7.2
control plane version: 1.7.2
data plane version: 1.7.2 (44 proxies)
Client Version: v1.16.8
Server Version: v1.16.8
**How was Istio installed?**
istioctl

**Environment where the bug was observed (cloud vendor, OS, etc)**
CentOS 7.6
Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by morvencao** [comment]
I don't think this is an istio issue, can you check if there are error logs in the kubelet?

**Comment by lklkxcxc** [comment]
@morvencao [http://chuantu.xyz/t6/741/1610369002x-1404755061.png](url) Change APIserver address to kubernetes.default and the problem mentioned above will occur

**Comment by lklkxcxc** [comment]
jenkins plugins problem
