### ISSUE TITLE
Install Multi-Primary on different networks - verification of the installation is not clear

### ISSUE THREAD

**Issue by sramek5** [istio/istio#29970]
**"BUG?" description:**
I was following exactly the guide [Install Multi-Primary on different networks](https://istio.io/latest/docs/setup/install/multicluster/multi-primary_multi-network/) and I got stuck in the last section [Verify the Installation](https://istio.io/latest/docs/setup/install/multicluster/verify/).

My requests are not getting routed to the other clusters as I expected. I am only getting responses from the service on the local cluster:
```
# Cluster 1 (where helloworld v1 is deployed)
$ while true; kubectl exec -n sample -c sleep "$(kubectl get pod -n sample -l app=sleep -o jsonpath='{.items[0].metadata.name}')" -- curl helloworld.sample:5000/hello; done
Hello version: v1, instance: helloworld-v1-776f57d5f6-9s56x
Hello version: v1, instance: helloworld-v1-776f57d5f6-9s56x
Hello version: v1, instance: helloworld-v1-776f57d5f6-9s56x
Hello version: v1, instance: helloworld-v1-776f57d5f6-9s56x
Hello version: v1, instance: helloworld-v1-776f57d5f6-9s56x

# Cluster 2 (where helloworld v2 is deployed)
$ while true; kubectl exec -n sample -c sleep "$(kubectl get pod -n sample -l app=sleep -o jsonpath='{.items[0].metadata.name}')" -- curl helloworld.sample:5000/hello; done
Hello version: v2, instance: helloworld-v2-54df5f84b-dmtxm
Hello version: v2, instance: helloworld-v2-54df5f84b-dmtxm
Hello version: v2, instance: helloworld-v2-54df5f84b-dmtxm
Hello version: v2, instance: helloworld-v2-54df5f84b-dmtxm
Hello version: v2, instance: helloworld-v2-54df5f84b-dmtxm

# Cluster 3 (where helloworld v2 is deployed - only label version changed to v3)
$ while true; kubectl exec -n sample -c sleep "$(kubectl get pod -n sample -l app=sleep -o jsonpath='{.items[0].metadata.name}')" -- curl helloworld.sample:5000/hello; done
Hello version: v2, instance: helloworld-v3-677dbbbdbf-s9pxd
Hello version: v2, instance: helloworld-v3-677dbbbdbf-s9pxd
Hello version: v2, instance: helloworld-v3-677dbbbdbf-s9pxd
Hello version: v2, instance: helloworld-v3-677dbbbdbf-s9pxd
Hello version: v2, instance: helloworld-v3-677dbbbdbf-s9pxd
```
Identification of the `istioctl proxy-config endpoint` for the `sleep` pod in cluster1, cluster2 and cluster3 to `helloworld` destination service (always stated 1 local and 2 eastwestgateways LoadBalancers from other clusters):
```
# Cluster 1
$ istioctl -n sample proxy-config endpoint "$(kubectl get pod -n sample -l app=sleep -o jsonpath='{.items[0].metadata.name}')" | grep helloworld
10.8.23.88:15443                 HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local
10.8.31.88:15443                 HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local
192.168.77.84:5000               HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local

# Cluster 2
$ istioctl -n sample proxy-config endpoint "$(kubectl get pod -n sample -l app=sleep -o jsonpath='{.items[0].metadata.name}')" | grep helloworld
10.8.31.88:15443                 HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local
10.8.7.85:15443                  HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local
192.168.170.25:5000              HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local

# Cluster 3
$ istioctl -n sample proxy-config endpoint "$(kubectl get pod -n sample -l app=sleep -o jsonpath='{.items[0].metadata.name}')" | grep helloworld
10.8.23.88:15443                 HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local
10.8.7.85:15443                  HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local
192.168.235.226:5000             HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local
```
Here are also my kiali charts, when I call curl request:
Cluster1:
![image](https://user-images.githubusercontent.com/53052347/104171322-bd728980-5402-11eb-8441-b11049aff50c.png)

Cluster2:
![image](https://user-images.githubusercontent.com/53052347/104171726-61f4cb80-5403-11eb-8a71-e4fbbe330065.png)

Cluster3:
![image](https://user-images.githubusercontent.com/53052347/104171735-65885280-5403-11eb-831f-222ab4916fbe.png)

It really seems that clusters are synchronized and somehow connected via eastwestgateway, but not fully or correctly, because `helloworld` version is not switching among v1, v2 or v3.

[X] Docs
[X] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Cluster versions:**
```
$ istioctl version
client version: 1.8.1
control plane version: 1.8.1
data plane version: 1.8.1 (4 proxies)

$ kubectl version
Client: v1.20.1
Server: v1.19.0

Provider: OpenStack
(third-party-tokens not available)
```
Am I missing anything? 
I would appreciate any help.

**Comment by stevenctl** [comment]
Hi @sramek5. Can you verify that Pods in a given cluster have connectivity to your Gateways (I'm assuming the `10.x` addresses are the gateways, based on the number of endpoints)?

**Comment by sramek5** [comment]
Hi @stevenctl,
thank you for reply.

Regarding your question:
```
# Tried to connect from Cluster 2:
$ istioctl -n sample proxy-config endpoint "$(kubectl get pod -n sample -l app=sleep -o jsonpath='{.items[0].metadata.name}')" | grep helloworld
10.8.31.88:15443                 HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local
10.8.7.85:15443                  HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local
192.168.0.136:5000               HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local

$ kubectl exec -ti -n sample sleep-854565cb79-7wzfv -- sh
/ # curl 10.8.31.88:15443 -v
*   Trying 10.8.31.88:15443...
* Connected to 10.8.31.88 (10.8.31.88) port 15443 (#0)
> GET / HTTP/1.1
> Host: 10.8.31.88:15443
> User-Agent: curl/7.69.1
> Accept: */*
> 
* Empty reply from server
* Connection #0 to host 10.8.31.88 left intact
curl: (52) Empty reply from server
/ # curl 10.8.31.88:15443 -v
*   Trying 10.8.31.88:15443...
* Connected to 10.8.31.88 (10.8.31.88) port 15443 (#0)
> GET / HTTP/1.1
> Host: 10.8.31.88:15443
> User-Agent: curl/7.69.1
> Accept: */*
> 
* Empty reply from server
* Connection #0 to host 10.8.31.88 left intact
curl: (52) Empty reply from server

/ # curl 10.8.31.88:15443 -v
*   Trying 10.8.31.88:15443...
* Connected to 10.8.31.88 (10.8.31.88) port 15443 (#0)
> GET / HTTP/1.1
> Host: 10.8.31.88:15443
> User-Agent: curl/7.69.1
> Accept: */*
> 
* Empty reply from server
* Connection #0 to host 10.8.31.88 left intact
curl: (52) Empty reply from server
/ # curl 10.8.7.85:15443 -v
*   Trying 10.8.7.85:15443...
* Connected to 10.8.7.85 (10.8.7.85) port 15443 (#0)
> GET / HTTP/1.1
> Host: 10.8.7.85:15443
> User-Agent: curl/7.69.1
> Accept: */*
> 
* Empty reply from server
* Connection #0 to host 10.8.7.85 left intact
curl: (52) Empty reply from server
```

I assume that the connection is successful.

**Comment by dntosas** [comment]
hola @sramek5 

following this thread may solve your case, check for comments with workarounds, maybe you are hit by the same issue --> https://github.com/istio/istio/issues/29970

**Comment by stevenctl** [comment]
The next things I would check are:
1. Does the eastwest gateway have the proper endpoints to reach the application Pods? You can verify the same way you're doing for the sleep pods. 
2. Check the eastwest gateway logs, the envoy logs on the sleep pods/hello world pods. If you see TLS issues, it's possible there was a misconfiguration when setting up trust between the clusters (https://preliminary.istio.io/latest/docs/tasks/security/cert-management/plugin-ca-cert/)

**Comment by mikala3** [comment]
# Cluster 1
$ istioctl -n sample proxy-config endpoint "$(kubectl get pod -n sample -l app=sleep -o jsonpath='{.items[0].metadata.name}')" | grep helloworld
10.8.23.88:15443                 HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local
10.8.31.88:15443                 HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local
192.168.77.84:5000               HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local

# Cluster 2
$ istioctl -n sample proxy-config endpoint "$(kubectl get pod -n sample -l app=sleep -o jsonpath='{.items[0].metadata.name}')" | grep helloworld
10.8.31.88:15443                 HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local
10.8.7.85:15443                  HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local
192.168.170.25:5000              HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local

# Cluster 3
$ istioctl -n sample proxy-config endpoint "$(kubectl get pod -n sample -l app=sleep -o jsonpath='{.items[0].metadata.name}')" | grep helloworld
10.8.23.88:15443                 HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local
10.8.7.85:15443                  HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local
192.168.235.226:5000             HEALTHY     OK                outbound|5000||helloworld.sample.svc.cluster.local

I also followed the the guide but my problem is that i only get the local ip for the cluster here. Did you do anything special to get those 10.x ip's here?

**Comment by sramek5** [comment]
Well, local IP (192.168.235.226:5000) is only for one, which is located on cluster where you send request istioctl.

The other two (10.8.23.88:15443, 10.8.7.85:15443) are LoadBalancer IPs of istio-eastwestgateways. 
All clusters are in different network.

You cannot get local address of helloworld in different cluster.

You need LoadBalancers (different feature outside of istio).

**Comment by mikala3** [comment]
Thanks for the reply.

How did you connect those LoadBalancers IPs to the proxy-config endpoints for a cluster? I have two clusters with two loadbalancers of istio-eastwestgateways.

**Comment by mikala3** [comment]
> istioctl -n sample proxy-config endpoint "$(kubectl get pod -n sample -l app=sleep -o jsonpath='{.items[0].metadata.name}')" | grep helloworld

This is how it looks for me right now. I get an empty reply from the gateway. I did follow the guide for "Plugin-CA-cert" but same still problem. Do i have to restart something to make the CA-cert work? Or do i have to modify some endpoints at the gateway?

**Comment by mikala3** [comment]
> $ kubectl exec -ti -n sample sleep-854565cb79-7wzfv -- sh
> / # curl 10.8.31.88:15443 -v
> *   Trying 10.8.31.88:15443...
> * Connected to 10.8.31.88 (10.8.31.88) port 15443 (#0)
> > GET / HTTP/1.1
> > Host: 10.8.31.88:15443
> > User-Agent: curl/7.69.1
> > Accept: */*
> > 
> * Empty reply from server
> * Connection #0 to host 10.8.31.88 left intact
> 
> / # curl 10.8.7.85:15443 -v
> *   Trying 10.8.7.85:15443...
> * Connected to 10.8.7.85 (10.8.7.85) port 15443 (#0)
> > GET / HTTP/1.1
> > Host: 10.8.7.85:15443
> > User-Agent: curl/7.69.1
> > Accept: */*
> > 
> * Empty reply from server
> * Connection #0 to host 10.8.7.85 left intact
> curl: (52) Empty reply from server

> This is how it looks for me right now. I get an empty reply from the gateway. I did follow the guide for "Plugin-CA-cert" but same still problem. Do i have to restart something to make the CA-cert work? Or do i have to modify some endpoints at the gateway?
