### ISSUE TITLE
Test Kubernetes versions with multicluster enabled

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#29972]
Currently, we test all versions of Kubernetes we support in postsubmit. We run all of the integration tests together in a single job. However, we do it in single cluster mode only.

It would be useful to move this to run in multicluster mode, so we can detect more breakages. 1.20 was broken for MC, for example, and we didn't notice until after it was released.

The increased test time is not a big deal since it runs only in postsubmit.

**Comment by pramodrj07** [comment]
Hi @howardjohn. I am interested in testing this. I have a couple of questions related to this.

1. Would the "kind" clusters suffice when we are running multi clusters? OR Should we have any specific way that k8s clusters are deployed? Any pointer to how and where(test CI dashboard) it is tested would be helpful to get the versions of Kubernetes which you are using. 
2. I see a couple of multi-cluster modes. Which mode would be good out of these? "https://istio.io/latest/docs/setup/install/multicluster/multi-primary/"
3. Which tests amongst these are we interested in? "https://github.com/istio/istio/tree/0c0cf2d6fbca85beca0598de8817ff90107ddd0c/tests/integration/multicluster".

Any pointer which you might think will help me get this done.
