### ISSUE TITLE
Create tests of reading IOP from STDIN for istioctl

### ISSUE THREAD

**Issue by morvencao** [istio/istio#29988]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

Follow up for https://github.com/istio/istio/issues/29930 and https://github.com/istio/istio/pull/29933
Create tests of reading IOP from STDIN for istioctl

[ ] Docs
[ X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ X ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by morvencao** [comment]
The UT tests can't cover this case, considering to add test case to integration tests. However, looks like the integration tests for `istioctl install` are flaky now, see: https://github.com/istio/istio/issues/28863

**Comment by brian-avery** [comment]
Istio.io has some tests that will pick this up, but integration tests are preferable.

**Comment by ericvn** [comment]
A test that was fixed by a PR #29933 in `master` is failing in `release-1.9`. This shows a further need to having an integration test verifying this.
