### ISSUE TITLE
Istio stopped working : Envoy proxy is NOT ready: config not received from Pilot

### ISSUE THREAD

**Issue by yogeshmorankar** [istio/istio#29999]
Envoy proxy is NOT ready: config not received from Pilot.
Started getting this error unexpectedly.
Readiness probe failed: Get http://10.0.2.11:15021/healthz/ready: dial tcp 10.0.2.11:15021: connect: connection refused
Logs :+1: Name:         istio-ingressgateway-5d795cc47f-4qf74
Namespace:    istio-system
Priority:     0
Node:         aks-app01-37403959-vmss000000/10.0.1.0
Start Time:   Tue, 12 Jan 2021 19:32:05 +0530
Labels:       app=istio-ingressgateway
              chart=gateways
              heritage=Tiller
              istio=ingressgateway
              pod-template-hash=5d795cc47f
              release=istio
              service.istio.io/canonical-name=istio-ingressgateway
              service.istio.io/canonical-revision=latest
Annotations:  prometheus.io/path: /stats/prometheus
              prometheus.io/port: 15090
              prometheus.io/scrape: true
              sidecar.istio.io/inject: false
Status:       Running
IP:           10.0.1.174
IPs:
  IP:           10.0.1.174
Controlled By:  ReplicaSet/istio-ingressgateway-5d795cc47f
Containers:
  istio-proxy:
    Container ID:  docker://a207126f0cd4685c9c1e6f782fc1db4a5050e39c24ec85eed8d1ea996cfcf232
    Image:         docker.io/istio/proxyv2:1.7.3
    Image ID:      docker-pullable://istio/proxyv2@sha256:6169d096fe60f128f1311f76c97ee1c3e5d760a45042d5c9182492745d34c658
    Ports:         15021/TCP, 8080/TCP, 8443/TCP, 15443/TCP, 15090/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP
    Args:
      proxy
      router
      --domain
      $(POD_NAMESPACE).svc.cluster.local
      --proxyLogLevel=warning
      --proxyComponentLogLevel=misc:error
      --log_output_level=default:info
      --serviceCluster
      istio-ingressgateway
      --trust-domain=cluster.local
    State:          Running
      Started:      Tue, 12 Jan 2021 19:32:07 +0530
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     2
      memory:  1Gi
    Requests:
      cpu:      100m
      memory:   128Mi
    Readiness:  http-get http://:15021/healthz/ready delay=1s timeout=1s period=2s #success=1 #failure=30
    Environment:
      JWT_POLICY:                third-party-jwt
      PILOT_CERT_PROVIDER:       istiod
      CA_ADDR:                   istiod.istio-system.svc:15012
      NODE_NAME:                  (v1:spec.nodeName)
      POD_NAME:                  istio-ingressgateway-5d795cc47f-4qf74 (v1:metadata.name)
      POD_NAMESPACE:             istio-system (v1:metadata.namespace)
      INSTANCE_IP:                (v1:status.podIP)
      HOST_IP:                    (v1:status.hostIP)
      SERVICE_ACCOUNT:            (v1:spec.serviceAccountName)
      CANONICAL_SERVICE:          (v1:metadata.labels['service.istio.io/canonical-name'])
      CANONICAL_REVISION:         (v1:metadata.labels['service.istio.io/canonical-revision'])
      ISTIO_META_WORKLOAD_NAME:  istio-ingressgateway
      ISTIO_META_OWNER:          kubernetes://apis/apps/v1/namespaces/istio-system/deployments/istio-ingressgateway
      ISTIO_META_MESH_ID:        cluster.local
      ISTIO_META_ROUTER_MODE:    sni-dnat
      ISTIO_META_CLUSTER_ID:     Kubernetes
    Mounts:
      /etc/istio/config from config-volume (rw)
      /etc/istio/ingressgateway-ca-certs from ingressgateway-ca-certs (ro)
      /etc/istio/ingressgateway-certs from ingressgateway-certs (ro)
      /etc/istio/pod from podinfo (rw)
      /etc/istio/proxy from istio-envoy (rw)
      /var/run/ingress_gateway from gatewaysdsudspath (rw)
      /var/run/secrets/istio from istiod-ca-cert (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from istio-ingressgateway-service-account-token-tc2qb (ro)
      /var/run/secrets/tokens from istio-token (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  istiod-ca-cert:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      istio-ca-root-cert
    Optional:  false
  podinfo:
    Type:  DownwardAPI (a volume populated by information about the pod)
    Items:
      metadata.labels -> labels
      metadata.annotations -> annotations
  istio-envoy:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  gatewaysdsudspath:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  istio-token:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  43200
  config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      istio
    Optional:  true
  ingressgateway-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  istio-ingressgateway-certs
    Optional:    true
  ingressgateway-ca-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  istio-ingressgateway-ca-certs
    Optional:    true
  istio-ingressgateway-service-account-token-tc2qb:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  istio-ingressgateway-service-account-token-tc2qb
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  30m                  default-scheduler  Successfully assigned istio-system/istio-ingressgateway-5d795cc47f-4qf74 to aks-app01-37403959-vmss000000
  Normal   Pulled     30m                  kubelet            Container image "docker.io/istio/proxyv2:1.7.3" already present on machine
  Normal   Created    30m                  kubelet            Created container istio-proxy
  Normal   Started    30m                  kubelet            Started container istio-proxy
  Warning  Unhealthy  33s (x900 over 30m)  kubelet            Readiness probe failed: HTTP probe failed with statuscode: 503

**Comment by howardjohn** [comment]
Generally this means cannot connect to Istiod. But we need the logs of the proxy to be sure.

**Comment by yogeshmorankar** [comment]
Got it. I found some more logs. One of the error was "wildcard format was invalid".
I had given like "*-dev.domain.com". it do not accepts the partial wildcards.
After changing the hostnames in gateways to "*.domain.com" now its working fine.
Thanks for the support.

**Comment by yogeshmorankar** [comment]
The only thing i observed is I have to manually delete the istio-ingressgateway POD to reflect the changes i had done.
It should have deleted and created automatically or there should not have to delete the POD in order to update the changes.

**Comment by yogeshmorankar** [comment]
we can close this issue.
