### ISSUE TITLE
 Configure push on demand

### ISSUE THREAD

**Issue by ydh926** [istio/istio#29994]
**Describe the feature request**
Currently we use Sidecar Scope to achieve configuration isolation. However, the use of SidecarScope requires users to sort out the dependencies of the service in advance and cannot push on-demand. I think that automatically generating SidecarScope based on service calls is an effective way to achieve configuration push on demand.

**Describe alternatives you've considered**
I am doing a project called **slime** to achieve the above purpose. The idea is as follows:
1. Automatically generate an empty SidecarScope for the service (which load on demand is turned on).
2. In order to make the service call successful, I created a sidecar shared by namespace, called the global-sidecar. And replace the bottom route with a route pointing to the global-sidecar. 
![lazyload-bookinfo-p1](https://user-images.githubusercontent.com/43948155/104280865-888c3280-54e7-11eb-9a5a-41474b538365.png)

3. The service can access services outside the scope through global-sidecar. Then global-sidecar will report service invocation
 information to slime, and slime automatically generates SidecarScope based on it.
![lazyload-bookinfo-p2](https://user-images.githubusercontent.com/43948155/104281245-2f70ce80-54e8-11eb-9ea4-c315d420856e.png)

I have completed a working version. You can try it out as follows：
1. install istio ( > 1.8 )
2. install slime 
```shell
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/ydh926/slime/master/install/install.sh)"
```
3. Make sure all components are running
```
$ kubectl get po -n mesh-operator
NAME                                    READY     STATUS    RESTARTS   AGE
global-sidecar-pilot-796fb554d7-blbml   1/1       Running   0          27s
lazyload-fbcd5dbd9-jvp2s                1/1       Running   0          27s
report-server-855c8cf558-wdqjs          2/2       Running   0          27s
slime-boot-68b6f88b7b-wwqnd             1/1       Running   0          39s
```

```
$ kubectl get po 
NAME                              READY     STATUS    RESTARTS   AGE
global-sidecar-785b58d4b4-fl8j4   1/1       Running   0          68s
```
4. install bookinfo in default namespace
5. enable push on demand
```shell
kubectl label ns default istio-dependency-servicefence=true
```
```shell
kubectl annotate svc productpage istio.dependency.servicefence/status=true
kubectl annotate svc reviews istio.dependency.servicefence/status=true
kubectl annotate svc details istio.dependency.servicefence/status=true
kubectl annotate svc ratings istio.dependency.servicefence/status=true
```
6. make sure SidecarScope is generated
```
$ kubectl get sidecar
NAME          AGE
details       12s
kubernetes    11s
productpage   11s
ratings       11s
reviews       11s
```
```
$ kubectl get sidecar productpage -oyaml
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: productpage
  namespace: default
  ownerReferences:
  - apiVersion: microservice.netease.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: ServiceFence
    name: productpage
spec:
  egress:
  - hosts:
    - istio-system/*
    - mesh-operator/*
    - '*/global-sidecar.default.svc.cluster.local'
  workloadSelector:
    labels:
      app: productpage
```
7. visit productpage & view accesslog
```
[2021-01-04T07:12:24.101Z] "GET /details/0 HTTP/1.1" 200 - "-" 0 178 36 35 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0" "83793ccf-545c-4cc2-9a48-82bb70d81a2a" "details:9080" "10.244.3.83:9080" outbound|9080||global-sidecar.default.svc.cluster.local 10.244.1.206:42786 10.97.33.96:9080 10.244.1.206:40108 - -
[2021-01-04T07:12:24.171Z] "GET /reviews/0 HTTP/1.1" 200 - "-" 0 295 33 33 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0" "010bb2bc-54ab-4809-b3a0-288d60670ded" "reviews:9080" "10.244.3.83:9080" outbound|9080||global-sidecar.default.svc.cluster.local 10.244.1.206:42786 10.99.230.151:9080 10.244.1.206:51512 - -
```
Successful access, the accesslog shows that the backend service is global-sidecar.

8. view productpage's SidecarScope again
```
$ kubectl get sidecar productpage -oyaml
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: productpage
  namespace: default
  ownerReferences:
  - apiVersion: microservice.netease.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: ServiceFence
    name: productpage
spec:
  egress:
  - hosts:
    - '*/details.default.svc.cluster.local'
    - '*/reviews.default.svc.cluster.local'
    - istio-system/*
    - mesh-operator/*
    - '*/global-sidecar.default.svc.cluster.local'
  workloadSelector:
    labels:
      app: productpage
```
reviews and details are automatically added！

9. visit productpage & view accesslog again
```
[2021-01-04T07:35:57.622Z] "GET /details/0 HTTP/1.1" 200 - "-" 0 178 2 2 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0" "73a6de0b-aac9-422b-af7b-2094bd37094c" "details:9080" "10.244.7.30:9080" outbound|9080||details.default.svc.cluster.local 10.244.1.206:52626 10.97.33.96:9080 10.244.1.206:47396 - default
[2021-01-04T07:35:57.628Z] "GET /reviews/0 HTTP/1.1" 200 - "-" 0 379 134 134 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0" "edf8c7eb-9558-4d1e-834c-4f238b387fc5" "reviews:9080" "10.244.7.14:9080" outbound|9080||reviews.default.svc.cluster.local 10.244.1.206:42204 10.99.230.151:9080 10.244.1.206:58798 - default
```
Successful access, the backend services are reviews and details.

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by nmnellis** [comment]
Please note that it does not appear that the Slime code base is currently public. I would advise against installing it until its made public.

**Comment by nmnellis** [comment]
why is the "global sidecar" needed? couldnt slime just pull metrics from prometheus to determine a service graph? Also the global sidecar resembles an egress gateway. Also is the global-sidecar-pilot different from the default install? One issue with this approach is that it requires applications to reach out to their dependencies which would fail the first few times until reporting is completed and the sidecar resource is updated. based on that issue its probably still recommended for the application developers to declare their dependencies a head of time. There is also some security problems, applications can reach out to unintended areas and will be granted access from slime.

**Comment by howardjohn** [comment]
First, I will say this project is pretty cool. I agree looking at metrics may also be a way to achieve this; for example, Kiali has an option to automatically generation AuthorizationPolicy which is essentially the same logic to generate Sidecar.Egress (they have an open issue to add sidecar support).

For first class istio support, I think we are more likely to use on-demand XDS https://www.envoyproxy.io/docs/envoy/latest/api-docs/xds_protocol#incremental-xds

**Comment by ydh926** [comment]
> why is the "global sidecar" needed? couldnt slime just pull metrics from prometheus to determine a service graph? Also the global sidecar resembles an egress gateway. Also is the global-sidecar-pilot different from the default install? One issue with this approach is that it requires applications to reach out to their dependencies which would fail the first few times until reporting is completed and the sidecar resource is updated. based on that issue its probably still recommended for the application developers to declare their dependencies a head of time. There is also some security problems, applications can reach out to unintended areas and will be granted access from slime.

**why is the "global sidecar" needed?**
global-sidecar needs to do two things. 
1. When upstreaming is outside of SidecarScope, traffic forwarding needs to be done through global-sidecar. From this point of view, global-sidecar is indeed like egress. The difference is that the routing and service discovery information obtained by global-sidecar is similar to that of sidecar. It can be understood as having the identity of a sidecar, but deployed as egress.
2. Timely report calling information. For a newly released service, there will be a certain delay in obtaining call information from metric.

**Also is the global-sidecar-pilot different from the default install**
yes，there is some customization on global-sidecar-pilot. But maybe it can be unified, if istio can accept the new type of proxy of global-sidecar.
1. This version still uses the mixer adapter to report data ( I am now trying to replace it with other methods )，so global-sidecar-pilot is based on the old version (1.3.7).
2. global-sidecar needs to ignore the bottom route to itself. This route is implemented by envoyfilter, so a special judgment is made on the envoyfilter in global-sidecar-pilot.

**One issue with this approach is that it requires applications to reach out to their dependencies which would fail the first few times until reporting is completed and the sidecar resource is updated.**
With global-sidecar as the bottom line, there will be no access failures.

**Comment by ydh926** [comment]
> First, I will say this project is pretty cool. I agree looking at metrics may also be a way to achieve this; for example, Kiali has an option to automatically generation AuthorizationPolicy which is essentially the same logic to generate Sidecar.Egress (they have an open issue to add sidecar support).
> 
> For first class istio support, I think we are more likely to use on-demand XDS https://www.envoyproxy.io/docs/envoy/latest/api-docs/xds_protocol#incremental-xds

I agree with you, but this seems to be a long time-consuming project. Maybe slime can help us through this time，

BTW, Slime is positioned as the manager of istio crd. In addition to Configure Push on demand, there are some other valuable modules. If you are interested, I will inform you when it is open source. Looking forward to cooperating with the istio community.

**Comment by ydh926** [comment]
> Please note that it does not appear that the Slime code base is currently public. I would advise against installing it until its made public.

I am doing some open source preparations. it will comming soon.

**Comment by ydh926** [comment]
hi，guys，slime’s code is open now. You can get it [here](https://github.com/slime-io/slime) . The project is at an early stage, so looking forward to your suggestions. @howardjohn @nmnellis

**Comment by hzxuzhonghu** [comment]
Really awesome, i am also wondering if global sidecar can be removed. We can get the dependencies from metrics.

**Comment by ydh926** [comment]
> Really awesome, i am also wondering if global sidecar can be removed. We can get the dependencies from metrics.

We need to access services outside of SidecarScope through global-sidecar. From this point of view, global-sidecar is necessary. But the process of global-sidecar reporting call information may be replaced by metric.

**Comment by nmnellis** [comment]
I dont know if you are familiar with knative but it solves the request buffering really well and can be highly available and has an istio implementation. The other part you are trying to solve (service scope) could ultimately be used to define trust relationships between applications using AuthorizationPolicies which i think would be really cool.

**Comment by ydh926** [comment]
> I dont know if you are familiar with knative but it solves the request buffering really well and can be highly available and has an istio implementation. The other part you are trying to solve (service scope) could ultimately be used to define trust relationships between applications using AuthorizationPolicies which i think would be really cool.


Sorry to reply you so late, I am not familiar with knative, if you can provide some information, I will be happy to read it. In addition, I hope to build slime as the AutoPilot for istio, which can be combined with monitoring information to control istio crd more intelligently. AuthorizationPolicies is also considering among them, if you have any good ideas, welcome to communicate with me.

**Comment by ydh926** [comment]
> Really awesome, i am also wondering if global sidecar can be removed. We can get the dependencies from metrics.

In the new version, slime already supports obtaining service call information from prometheus. https://github.com/slime-io/slime/releases/tag/v0.1.0-alpha.

**Comment by ydh926** [comment]
Considering that the community already has a mature solution for on-demand loading https://docs.google.com/document/d/1AqhQnrX_7SS6PAkNwoaA2peCtk9htgwSBTRg1gzFPNw/edit#heading=h.ni5t9ogyxz7j, and the basic functions of the slime-lazyload module have been implemented, we will not focus on the improvement of this module. We hope to build slime into an intelligent mesh manager, which can monitor and perceive service status through service monitoring and automatically adjust istio CR. We will put more effort into framework construction and other functional modules.

**Comment by JoshuaAndrew** [comment]
nice work！
