### ISSUE TITLE
istioctl uninstall --set revision doesn't work

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#30002]
```
$ ik x uninstall --set revision=new
Error: at least one of the --revision, --filename or --purge flags must be set
```

I shouldn't need to pass --revision, when --set revision=new (or, I assume, -f) already provides this info. This makes it inconsistent with `istioctl install`

**Comment by morvencao** [comment]
/cc @shamsher31 

```
ik x uninstall --revision=new
```

should be working.
