### ISSUE TITLE
Istioctl manifest generate for 1.8.1

### ISSUE THREAD

**Issue by anuraagrijal3138** [istio/istio#30010]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Command below runs successfully.
```
istioctl manifest generate --manifests manifests/ -f manifests/profiles/default.yaml > initial.yaml  
```
**Steps to reproduce the bug**
Download istio release 1.8.1 from github. Run 
```
istioctl manifest generate --manifests manifests/ -f manifests/profiles/default.yaml > initial.yaml 
Error: component "istiocoredns" does not exist
```
**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
$ kubectl version --short
Client Version: v1.20.0
$ istioctl version --remote
client version: 1.8.0
control plane version: 1.8.0
data plane version: 1.8.0 (2 proxies)
```
**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
This is working as intended, see https://istio.io/latest/news/releases/1.8.x/announcing-1.8/upgrade-notes/#istio-coredns-plugin-deprecation. Thanks!

**Comment by anuraagrijal3138** [comment]
Thank you!
