### ISSUE TITLE
Ingress gateway is crashing when JWT is used

### ISSUE THREAD

**Issue by PetrMc** [istio/istio#30012]
**Bug description**

followed this document - https://docs.google.com/document/d/1Hs-330f3h2u6QNQ7KA05b8I6IMuGReWnxTdsR8T9X2g/edit?usp=sharing - as soon as the last step applied (gateway-with-auth.yaml JWT token autorization Ingress config) - the Ingress-gateway for httpbin starts crashing:

```
$ kubectl get pods
NAME                                   READY   STATUS      RESTARTS   AGE
httpbin-779c54bf49-wshbm               2/2     Running     0          24h
tsb-gateway-httpbin-549457997b-qxs2f   0/1     Completed   4          101s
```

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

tsb gateway works as expected

**Steps to reproduce the bug**

access to the environment - TSB - `https://demo-testing-petr-tsb.cx.tetrate.info:8443/login` (admin/Tetrate123)
MP Cluster and Keycloak install - `gcloud container clusters get-credentials mp-cp-ingress-petr-site-3 --region us-west1 --project gcp-site-1`
CP Cluster with httpbin - `gcloud container clusters get-credentials cp-backend-petr-site-1-gcp --region us-west1 --project gcp-site-1`
keycloak config - `https://keycloak.cx.tetrate.info/auth/` (admin/admin)

tctl config:
```
tctl config clusters set keycloak-crash-cluster --bridge-address demo-testing-petr-tsb.cx.tetrate.info:8443
tctl config profiles set keycloak-crash-profile --cluster keycloak-crash-cluster
tctl config profiles set-current keycloak-crash-profile
tctl login
Organization: <leave blank>
Tenant: workgroup-demo-testing-tenant
Username: admin
Password: Tetrate123
Login Successful!
  Configured user: keycloak-crash-cluster-admin
  User "keycloak-crash-cluster-admin" enabled in profile: keycloak-crash-profile

```
Expected output
```
tctl get tenant
  NAME
  workgroup-demo-testing-tenant  
```

TSB Created Gateway points to port 8080 - that is not defined anywere [gw_wrong_config.txt](https://github.com/istio/istio/files/5805479/gw_wrong_config.txt)
Crashing Ingress logs [tsb-ingress-logs.txt](https://github.com/istio/istio/files/5805480/tsb-ingress-logs.txt)
Auth policy that also points to non-existent port 8080 [auth_policy.txt](https://github.com/istio/istio/files/5805481/auth_policy.txt)
VS that doesn't have port 8080 (8000 instead) [mismatching_vs.txt](https://github.com/istio/istio/files/5805482/mismatching_vs.txt)

**Comment by howardjohn** [comment]
cc @yangminzhu

**Comment by PetrMc** [comment]
sorry opened in wrong repository :-(
