### ISSUE TITLE
[operator][1.7.6] Ingress gateway is not removed when it is removed from IstioOperator CR

### ISSUE THREAD

**Issue by su225** [istio/istio#30018]
**Bug description**
This is a bug in operator's reconciliation logic. When ingress gateway is removed from `ingressGateways` section, corresponding deployment should be deleted. But it is not the case in 1.7.6. However I tried with 1.8.1 and the unreleased 1.9 and it works fine. So the fix needs to be back-ported to 1.7

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
When a gateway is deleted from `ingressGateways` section, the corresponding deployment should be deleted. Both `istio-system` and `istio-operator` have operators installed watching different namespaces because in Istio < 1.8 multiple CRs in the same ns is not supported (we need it for keeping gateways and control plane separate). 

**Steps to reproduce the bug**
Control plane was installed with `profile=minimal` and no other setting

1. First I created a simple `IstioOperator` and save it as `ingress-gw.yaml`
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: gateways
spec:
  profile: empty
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true

```
2. Deploy it and check if it is deployed
```
$ kubectl apply -f ingress-gw.yaml -n istio-gateway
istiooperator.install.istio.io/gateways created

$ kubectl get pods -lapp=istio-ingressgateway -A
NAMESPACE      NAME                                    READY   STATUS    RESTARTS   AGE
istio-system   istio-ingressgateway-7dd8f49cb8-5zbs2   1/1     Running   0          7s
```
3. Modify `ingress-gw.yaml` : remove components section
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: gateways
spec:
  profile: empty
```
4. Apply modified YAML and check for pods
```
$ kubectl apply -f ingress-gw.yaml -n istio-gateway
istiooperator.install.istio.io/gateways configured

# Wait for some time - like a minute or two just to make sure that it is still not Terminating
$ kubectl get pods -lapp=istio-ingressgateway -A
NAMESPACE      NAME                                    READY   STATUS    RESTARTS   AGE
istio-system   istio-ingressgateway-7dd8f49cb8-5zbs2   1/1     Running   0          3m22s
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
$ istioctl17 version
client version: 1.7.6
control plane version: 1.7.6
data plane version: none
```

**How was Istio installed?** 
I had operator installed. Then both control plane and gateways were installed with `IstioOperator` CR.

**Comment by morvencao** [comment]
@su225 This was fixed in https://github.com/istio/istio/pull/27198
I will cherrypick it to release-1.7

**Comment by morvencao** [comment]
Closing this as it was fixed in https://github.com/istio/istio/pull/30057
Feel free to reopen it.
