### ISSUE TITLE
/usr/local/bin/envoy: required GLIBC_2.18

### ISSUE THREAD

**Issue by tanjunchen** [istio/istio#30020]
Is there a requirement for istio 1.8.1 virtual machine centos version？
It seems that centos 7 needs to upgrade the glibc package。
**Istio VM /usr/local/bin/envoy: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /usr/local/bin/envoy)**

**Comment by howardjohn** [comment]
Yes, it requires Centos 8

**Comment by tanjunchen** [comment]
@howardjohn Hello, if I don’t want to upgrade the glibc dependency package of centos7, is there any other way? For example, recompile the envoy proxy image (upgrading glibc seems to be an inappropriate way), or will there be plans for istio 1.8 to support centos7 in the future? Thank you

**Comment by howardjohn** [comment]
We currently do not ship a Centos 7 compatible Envoy. We may in the future
but not until Istio 1.10+. I believe some vendors are offering custom
Centos 7 binaries though

**Comment by tanjunchen** [comment]
sure. thanks
