### ISSUE TITLE
Pod injected without necessary lables

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#30024]
Installed latest istio, but found sidecar injected but without `security.istio.io/tlsMode`, `service.istio.io/canonical-name` `service.istio.io/canonical-revision` and `istio.io/rev`.

I installed istio by istioctl like this https://preliminary.istio.io/latest/docs/setup/install/multicluster/multi-primary_multi-network/#configure-cluster1-as-a-primary

@howardjohn Maybe related to #29126

**Comment by hzxuzhonghu** [comment]
I have checked `istio-sidecar-injector` configmap, there are no such labels

**Comment by howardjohn** [comment]
@hzxuzhonghu do you have `latest` istiod image but old injection template?

**Comment by hzxuzhonghu** [comment]
I am totally on a new cluster, this is found when i am creating multi-primary clusters. 
```
istioctl version --context=kind-cluster1
client version: unknown
control plane version: 1.9-alpha.cea84972c8bfaa47330092295e0f0ab64807edbc
data plane version: 1.9-alpha.cea84972c8bfaa47330092295e0f0ab64807edbc (4 proxies)
```

The istioctl is built manually from latest, and i checked it is same as the image.

**Comment by howardjohn** [comment]
It should be in istio-sidecar-injector configmap, can you post it here
maybe?

**Comment by hzxuzhonghu** [comment]
`make gen-charts` before `go build` fixed this.
