### ISSUE TITLE
Publish CentOS 7 compatible istio-sidecar RPMs

### ISSUE THREAD

**Issue by akhalyavka** [istio/istio#30041]
**Describe the feature request**
We're trying to setup mesh expansion on centos7-based VMs, but available centos RPM works only with centos8. As far as I can see from codebase, centos7 RPMs are built and even tested. Is there any reason why they are not published?  

**Describe alternatives you've considered**
I was able to pull out desired RPM from [docker image ](https://hub.docker.com/layers/istio/app_sidecar_centos_7/1.8.1/images/sha256-1c60a603f71ef960e95ffbc37641e311c4c501b8634e3087fa41fa1ff221d4dc?context=explore) and successfully run it on our VMs, but this is too hacky.

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[x] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by kautella** [comment]
+1 on this!
Additionally, @akhalyavka how were you able to get the RPM from the docker image?

**Comment by akhalyavka** [comment]
@kautella Sorry for late response, I used `docker save` and found this RPM in one of the layers. I did this just to play with mesh expansion, it's definitely too risky to run in production.

**Comment by tanjunchen** [comment]
+1 on this!

**Comment by alexvanboxel** [comment]
The RPMs seem to be built but never published. I've opened a PR: https://github.com/istio/release-builder/pull/706
