### ISSUE TITLE
Parse token in istio ingressgw

### ISSUE THREAD

**Issue by xinxinzhao1212** [istio/istio#30055]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**
I want to parse token in istio ingressgw  ,after parsing token, i can get "mso" information ,and i can route different mso to different service

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

In istio1.6.6 ,whether this function has supported ?

**Comment by howardjohn** [comment]
I think you can do authz based on this (see claims https://istio.io/latest/docs/reference/config/security/authorization-policy/) but not routing

**Comment by howardjohn** [comment]
Actually you might be able to if the auth filter adds it as a header? @yangminzhu ?

**Comment by yangminzhu** [comment]
@xinxinzhao1212 could you clarify a little bit what exactly do you want? Is this related to https://github.com/envoyproxy/envoy/issues/15062 to allow storing jwt claims to headers?

**Comment by howardjohn** [comment]
Any more info?
