### ISSUE TITLE
istioctl install leaves extra environment variables

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#30098]
* I installed a gateway
* I modified it to have env HOWARDJOHN=bar with `kubectl edit`
* Run `istioctl install` again.
* `HOWARDJOHN=bar` is still there

The kubectl edit is a contrived example, when I really stumbled upon this I had a real, but complete different, configuration for the gateway. Then the leftover env vars stuck around, leading to incorrect behavior.

This was run on master.

**Comment by morvencao** [comment]
I think this is expected for server-side apply, correct me if I'm wrong? @richardwxn

**Comment by howardjohn** [comment]
Hmm, it does seem like `istioctl manifest generate | kubectl apply` produces the same. But its completely broken, we are left in a bad state...
