### ISSUE TITLE
Create e2e for Task "Distributed Request Tracing"

### ISSUE THREAD

**Issue by sebastienvas** [istio/istio#301]

**Comment by sakshigoel12** [comment]
Need to add something to istio/istio

**Comment by ldemailly** [comment]
doesn't need to block 0.2 but is key to have in place before we make bigger changes
(q: is it already in mixer_test or other?)

**Comment by ayj** [comment]
Is this addressed by https://istio.io/docs/tasks/telemetry/distributed-tracing.html?
