### ISSUE TITLE
Document limiting ingress gateway ports exposed via load balancer

### ISSUE THREAD

**Issue by stevehipwell** [istio/istio#30104]
**Describe the feature request**

There needs to be documentation to show which ports need to be exposed via a cloud load balancer and which ones shouldn't. This has been made a greater priority by the default install adding additional port which cause issues with the maximum number of security group in our cloud. Initially my aim is to remove port 80 as we don't use that but I would also be interested in removing any other ports that don't need exposing.

**Describe alternatives you've considered**

I've tried googling this but can't find a definitive answer that is up to date with the current release.

**Affected product area (please put an X in all that apply)**

[x] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

I'm using AWS EKS v1.18 and a NLB.

**Comment by howardjohn** [comment]
port 15021: if you need external health check
port 80/443: if you want these ports for your own trafic
port 15443: for multinetwork
port 15012: for multicluster, deprecated, likely will be removed soon

**Comment by howardjohn** [comment]
Agree we should have docs as well, but for now that may help :slightly_smiling_face: . I am looking into if we can remove the last 2 by default.

**Comment by stevehipwell** [comment]
Thanks @howardjohn.

We've applied the following settings to our ingress gateway in the Istio Operator CRD to only support HTTPS connections and can confirm that it works.

```yaml
k8s:
  service:
    ports:
      - name: status-port
        protocol: TCP
        port: 15021
        targetPort: 15021
      - name: https
        protocol: TCP
        port: 443
        targetPort: 8443
```

**Comment by casey-robertson** [comment]
Thanks for filing this.  I also got caught with the extra default ports.  However, even after pruning down to the same ports you did - 443 for service traffic and 15021 for the health check I'm getting:

```
 Warning  SyncLoadBalancerFailed  68s                service-controller  Error syncing load balancer: failed to ensure load balancer: error authorizing security group ingress: "RulesPerSecurityGroupLimitExceeded: The maximum number of rules per secur │
│ ity group has been reached.\n\tstatus code: 400, request id: bc341df3-4211-41a2-b168-5efade00b667"          
```

I guess I need to investigate the quotas/limits

**Comment by stevehipwell** [comment]
@casey-robertson are you on AWS? If so https://github.com/kubernetes/kubernetes/issues/98097 might be of interest to you.

**Comment by casey-robertson** [comment]
> @casey-robertson are you on AWS? If so [kubernetes/kubernetes#98097](https://github.com/kubernetes/kubernetes/issues/98097) might be of interest to you.

Yes, we are on AWS.  I also noticed it was adding a rule for the 15021 health check port that I don't believe was exposed via the service before.  I'll check a running config.  Thanks for the link!

**Comment by stevehipwell** [comment]
@howardjohn do the changes in v1.9.0 mean we now need to add the tcp-istiod port (15012) or can we still leave it out?

**Comment by howardjohn** [comment]
Only if you use it. If you don't know then you probably don't - its not recommended nor documented. You can look at `kubectl get gateways --all` and look for any 15012 references

**Comment by gabrieloandco** [comment]
Just found how to do this for GatewayAPI [in the official docs](https://istio.io/latest/docs/tasks/traffic-management/ingress/gateway-api/), in case anyone is looking how to achieve this as I was.

Just add in your gateway parameters configmap:

```
service: |
    spec:
      ports:
      -  port: 15021
         $patch: delete
```

For SOC2 and ISO27001 it's required to not have any non essential TCP port exposed to the web, hence the need.
