### ISSUE TITLE
Multi-Primary setup connection issues

### ISSUE THREAD

**Issue by mhindery** [istio/istio#30103]
**Bug description**

When setting up a multi-primary cluster setup according to the documentation on [Install Multi-Primary on different networks](https://istio.io/latest/docs/setup/install/multicluster/multi-primary_multi-network/), we fail to achieve cross-cluster traffic. It looks like the service discovery itself is working, the configuration of the remote cluster is known, but when making a network call to it, we observe a certificate-related error.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[X] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[X] Multi Cluster
[ ] Virtual Machine
[X] Multi Control Plane

**Expected behavior**

Traffic to a service available on both clusters is loadbalanced between two clusters.

**Steps to reproduce the bug**

- Set up two new empty k8s clusters. Both are on GKE in the same project and network.
- Install Istio 1.8 with this yaml, and a custom trustdomain:
```yaml
# first.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    global:
      meshID: mesh
      multiCluster:
        clusterName: {first}
      network: {first}network
```

```bash
istioctl install -f first.yaml --set meshConfig.trustDomain={first}
```
With {first} replaced by {second} for the different clusters.
- Set up the certificates with shared root on both clusters according to [Plug in CA Certificates](https://istio.io/latest/docs/tasks/security/cert-management/plugin-ca-cert/), restart all istio pods afterwards.
- Enable sidecar injection on both clusters by labeling the namespace, and deploy testing workloads (the sleep / httbin services, and a custom one we made ourselves)
- Follow the [Multi Cluster Istio doc](https://istio.io/latest/docs/setup/install/multicluster/multi-primary_multi-network/). The east-west gateways in our case are GCP loadbalancers. Two of these were set up, one for each cluster. They are public TCP loadbalancers identified with a public ip. Every step in that doc is then done.
- We have found [a Multi-Cluster issue on Github](https://github.com/istio/istio/issues/29359#issuecomment-738970767) which we also observed even though our gateways are not hostbased but ip's. We applied the configuration as mentioned in the linked comment to our config as well; initially the meshconfig in the `istio` configmap was empty:
```yaml
meshNetworks: 'networks: {}'
```
and we manually updated it to:
```yaml
  meshNetworks: |-
    networks:
      firstnetwork:
        endpoints:
          - fromRegistry: firstcluster
        gateways:
          - address: {e-w gateway 1 ip}
            port: 15443
      secondnetwork:
        endpoints:
          - fromRegistry: secondcluster
        gateways:
          - address: {e-g gateway 2 ip}
            port: 15443
```

- We enforce mtls globally in the mesh:
```yaml
apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "default"
spec:
  mtls:
    mode: STRICT
```

Now we consider all the necessary setup to be done. Starting to do requests to a webserver service which is deployed on both clusters, we expect requests to go to both clusters. However we see that all requests end up being served by the deployment on the local cluster and never cross-cluster.

We have looked at the envoy sidecar of the service to see some stats (`call-service` is the name of our deployment) doing this:
```
kubectl port-forward $(kubectl get pod --selector="app=call-service" --output jsonpath='{.items[0].metadata.name}') 8282 15021 15090 15020 15000
```

There on the entries on its web'UI' (now accessible on http://localhost:15000/clusters) we see a set of stats for the deployments both local and on the remote cluster, so e.g.:

```
# this being the local one
outbound|8282||call-service.default.svc.cluster.local::10.4.2.10:8282::cx_active::0
outbound|8282||call-service.default.svc.cluster.local::10.4.2.10:8282::cx_connect_fail::0
outbound|8282||call-service.default.svc.cluster.local::10.4.2.10:8282::cx_total::0
outbound|8282||call-service.default.svc.cluster.local::10.4.2.10:8282::rq_active::0
...
outbound|8282||call-service.default.svc.cluster.local::10.4.2.10:8282::success_rate::-1.0
outbound|8282||call-service.default.svc.cluster.local::10.4.2.10:8282::local_origin_success_rate::-1.0
# this being the remote one
outbound|8282||call-service.default.svc.cluster.local::{e-w gateway 2 ip}:15443::cx_active::0
outbound|8282||call-service.default.svc.cluster.local::{e-w gateway 2 ip}:15443::cx_connect_fail::0
outbound|8282||call-service.default.svc.cluster.local::{e-w gateway 2 ip}:15443::cx_total::0
outbound|8282||call-service.default.svc.cluster.local::{e-w gateway 2 ip}:15443::rq_active::0
...
outbound|8282||call-service.default.svc.cluster.local::{e-w gateway 2 ip}:15443::local_origin_success_rate::-1.0
```

We conclude that the service discovery process works, and that it should be able to send traffic to the external cluster. Now when we start doing requests to our service, we see that it does try to send half of the requests to the remote server, but all fail. E.g. after doing 50 requests, we have these stats on the remote config: 25 attempts

```
outbound|8282||call-service.default.svc.cluster.local::{e-w gateway 2 ip}:15443::cx_active::0
outbound|8282||call-service.default.svc.cluster.local::{e-w gateway 2 ip}:15443::cx_connect_fail::25
outbound|8282||call-service.default.svc.cluster.local::{e-w gateway 2 ip}:15443::cx_total::25
outbound|8282||call-service.default.svc.cluster.local::{e-w gateway 2 ip}:15443::rq_active::0
outbound|8282||call-service.default.svc.cluster.local::{e-w gateway 2 ip}:15443::rq_error::25
outbound|8282||call-service.default.svc.cluster.local::{e-w gateway 2 ip}:15443::rq_success::0
outbound|8282||call-service.default.svc.cluster.local::{e-w gateway 2 ip}:15443::rq_timeout::0
outbound|8282||call-service.default.svc.cluster.local::{e-w gateway 2 ip}:15443::rq_total::0
outbound|8282||call-service.default.svc.cluster.local::{e-w gateway 2 ip}:15443::hostname::
outbound|8282||call-service.default.svc.cluster.local::{e-w gateway 2 ip}:15443::health_flags::healthy
outbound|8282||call-service.default.svc.cluster.local::{e-w gateway 2 ip}:15443::weight::1
outbound|8282||call-service.default.svc.cluster.local::{e-w gateway 2 ip}:15443::region::europe-west1
outbound|8282||call-service.default.svc.cluster.local::{e-w gateway 2 ip}:15443::zone::europe-west1-c
outbound|8282||call-service.default.svc.cluster.local::{e-w gateway 2 ip}:15443::sub_zone::
outbound|8282||call-service.default.svc.cluster.local::{e-w gateway 2 ip}:15443::canary::false
outbound|8282||call-service.default.svc.cluster.local::{e-w gateway 2 ip}:15443::priority::0
outbound|8282||call-service.default.svc.cluster.local::{e-w gateway 2 ip}:15443::success_rate::-1.0
outbound|8282||call-service.default.svc.cluster.local::{e-w gateway 2 ip}:15443::local_origin_success_r
```

The requests fail but istio does a fallback to its local counterpart, hence we as end-user observe that all requests are handled by the service on the local cluster.

We are able to succesfully query the e-w gateways for health (e.g. `http://{e-w gateway ip}:15021/healthz/ready`).

We then have put the envoy sidecar pod into debug mode and inspected the log output when performing these remote cluster calls. There we have found this

```
2021-01-08T09:08:56.943278Z	debug	envoy router	[C66454][S7524086034907921437] cluster 'outbound|8282||call-service.default.svc.cluster.local' match for URL '/'
2021-01-08T09:08:56.943317Z	debug	envoy router	[C66454][S7524086034907921437] router decoding headers:
':authority', 'call-service.default:8282'
':path', '/'
':method', 'GET'
':scheme', 'https'
'user-agent', 'Go-http-client/1.1'
'x-cloud-trace-context', '265623fba501c4d4ef00c300024e7b34/11949469812071382722;o=0'
'accept-encoding', 'gzip'
'x-forwarded-proto', 'http'
'x-request-id', '4a51687b-aaed-4a4d-b552-f2bbfd84895d'
'x-envoy-decorator-operation', 'call-service.default.svc.cluster.local:8282/*'
'x-envoy-peer-metadata', 'CiAKDkFQUF9***Gwtc2VydmljZQ=='
'x-envoy-peer-metadata-id', 'sidecar~10.60.1.5~call-service-559f57d456-pnj5s.default~default.svc.cluster.local'
'x-envoy-attempt-count', '1'
'x-b3-traceid', '60c258313b82568c67e1d7741af5aa0e'
'x-b3-spanid', '67e1d7741af5aa0e'
'x-b3-sampled', '0'
2021-01-08T09:08:56.943328Z	debug	envoy pool	queueing stream due to no available connections
2021-01-08T09:08:56.943333Z	debug	envoy pool	creating a new connection
2021-01-08T09:08:56.943399Z	debug	envoy client	[C68048] connecting
2021-01-08T09:08:56.943403Z	debug	envoy connection	[C68048] connecting to {e-w gateway 2 ip}:15443
2021-01-08T09:08:56.943466Z	debug	envoy connection	[C68048] connection in progress
2021-01-08T09:08:56.947638Z	debug	envoy connection	[C68048] connected
2021-01-08T09:08:56.951244Z	debug	envoy connection	[C68048] TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
2021-01-08T09:08:56.951270Z	debug	envoy connection	[C68048] closing socket: 0
2021-01-08T09:08:56.951307Z	debug	envoy client	[C68048] disconnect. resetting 0 pending req
```

What we concluded here is that there is no underlying network-related issue: it is able to connect to the remote cluster. However there is a certificate problem causing the tls handshake to fail. Seeing as we followed the documentation regarding the certificates, and having done the verification for it as well, we expected to have done everything necessary on that part.

Verification of the certificates seems ok, this is the output when checking the intermediate certificates on each cluster against the root one:

```
➜  tmp git:(master) ✗ openssl verify ~/Desktop/root.pem                                        
/Users/jaspermaes/Desktop/root.pem: O = Istio, CN = Root CA
error 18 at 0 depth lookup:self signed certificate
OK
➜  tmp git:(master) ✗ openssl verify -CAfile <(cat ~/Desktop/root.pem) ~/Desktop/first-inter.pem
/Users/jaspermaes/Desktop/sec-inter.pem: OK
➜  tmp git:(master) ✗ openssl verify -CAfile <(cat ~/Desktop/root.pem) ~/Desktop/second-inter.pem
/Users/jaspermaes/Desktop/prim-inter.pem: OK
```

(Assuming that `error 18 at 0 depth lookup:self signed certificate` is not a concern, similar to how the docs mention that `verify error:num=19:self signed certificate in certificate chain` is an expected error).

We have tried repeatedly to start over with new clusters, new e-w gateways, to no avail. At this point we do not know how and where to continue looking for the problem. We are also starting out with Istio and thus are not very familiar with any of the inner workings to pinpoint the problem.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

Istio:
```
mhindery@Mathieus-MacBook-Pro ~ % istioctl version --remote
client version: 1.8.1
control plane version: 1.8.0
data plane version: 1.8.0 (5 proxies)
```

Kubernetes on GKE, both clusters are running k8s version `1.17.14-gke.1600`

**How was Istio installed?**

See above, using istioctl

**Environment where the bug was observed (cloud vendor, OS, etc)**

Our k8s clusters are running in GKE

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

I'll attach a cluster-state bug-report, though this is from a new cluster setup so the names are not first/second anymore, but the config is the same. I simply zipped the file as Github did not allow to upload the `.tgz` file.

[bug-report.tgz.zip](https://github.com/istio/istio/files/5819439/bug-report.tgz.zip)

**Comment by dntosas** [comment]
we managed to make this setup working ^^ but instead of creating intermediate certificates for each cluster like described in docs, we just created a pair of key/cert for root CA and deploy them into all clusters to be the same

some like this, is the secret we deploy on all cluster as `istio-ca-secret` on `istio-system` namespace:
 ```yaml
 apiVersion: v1
data:
  ca-cert.pem: ISTIO_CA_CERT
  ca-key.pem: ISTIO_CA_KEY
  cert-chain.pem: ""
  key.pem: ""
  root-cert.pem: ""
kind: Secret
metadata:
  name: istio-ca-secret
  namespace: istio-system
type: istio.io/ca-root

```

**Comment by mhindery** [comment]
We have tried some variations of this suggestion, but that did not work unfortunately. We kept getting the same certificate error. We have also tried to fiddle with the `cacerts` secret in the `istio-system` namespace which looks like this

```yaml
apiVersion: v1
data:
  ca-cert.pem: ISTIO_CA_CERT_BASE64=
  ca-key.pem: ISTIO_CA_KEY_BASE64==
  cert-chain.pem: ""
  root-cert.pem: ""
kind: Secret
metadata:
  name: cacerts
  namespace: istio-system
type: Opaque
```

An issue [here](https://github.com/istio/istio/issues/27958) mentions these two, and we're not sure what is or isn't relevant anymore, so tried adjusting both but did not get it to work. Are you on Istio version 1.8 @dntosas ? Perhaps a different version is using the certificates differently?

**Comment by dntosas** [comment]
FYI, i think `cacerts` is legacy stuff remains only for backwards compatibility reasons. i suggest you should stick find an appropriate configuration with the secret convention ^^

yes, we are on Istio 1.8 ^^ one way to be sure that Istiod loads your secret (given that there is no configmap `cacerts` present, delete it) is by scaling down to replicas==0, then create your secret (mind to have correct annotations and naming), scale up again Istiod and check logs. you should NOT see something like "not found certificates, creating self-signed ones"
