### ISSUE TITLE
Istio Operator is missing permissions to retrieve resource lock istio-operator/istio-operator-lock

### ISSUE THREAD

**Issue by heikostumpf** [istio/istio#30106]
**Bug description**
Istio Operator is not able to perform installation of controlplane components (ingress-gateway, istiod) because of missing clusterrole permissions. It is stuck forever in the following loop:

`2021-01-15T12:34:52.989865Z	error	klog	error retrieving resource lock istio-operator/istio-operator-lock: leases.coordination.k8s.io "istio-operator-lock" is forbidden: User "system:serviceaccount:istio-operator:istio-operator" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "istio-operator"
2021-01-15T12:34:57.297263Z	error	klog	error retrieving resource lock istio-operator/istio-operator-lock: leases.coordination.k8s.io "istio-operator-lock" is forbidden: User "system:serviceaccount:istio-operator:istio-operator" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "istio-operator"
2021-01-15T12:35:00.418729Z	error	klog	error retrieving resource lock istio-operator/istio-operator-lock: leases.coordination.k8s.io "istio-operator-lock" is forbidden: User "system:serviceaccount:istio-operator:istio-operator" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "istio-operator"` 

Adding the necessary permissions to istio-operator clusterrole (apiGroup: coordination.k8s.io) releases the loop and istio-operator is able to continue with the installation.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
Istio Operator is able to install controlplane components.

**Steps to reproduce the bug**
Installing istio operator with the chart from release 1.8 (Istio Operator chart version: 1.7.0) into an Azure Kubernetes Cluster (aks 1.19.3)

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

istioctl version --remote
client version: 1.8.0
control plane version: 1.9-alpha.aab08e1181d7198ca6994323bdf39001887aa700
data plane version: 1.9-alpha.c1ff2e41a388a6497c33afd540f98ba14366a88f (20 proxies), 1.9-alpha.aab08e1181d7198ca6994323bdf39001887aa700 (5 proxies)

kubectl version --short
Client Version: v1.19.4
Server Version: v1.19.3

helm version --short
v3.4.0+g7090a89

**How was Istio installed?**
Istio operator was installed with the helm chart from release 1.8 (Istio Operator chart version: 1.7.0)

**Environment where the bug was observed (cloud vendor, OS, etc)**
AKS 1.19.3

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

```
istioctl operator dump

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: istio-operator
rules:
# istio groups
- apiGroups:
  - authentication.istio.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - config.istio.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - install.istio.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - networking.istio.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - security.istio.io
  resources:
  - '*'
  verbs:
  - '*'
# k8s groups
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions.apiextensions.k8s.io
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - apps
  - extensions
  resources:
  - daemonsets
  - deployments
  - deployments/finalizers
  - ingresses
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
  - update
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - roles
  - rolebindings
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - events
  - namespaces
  - pods
  - pods/proxy
  - persistentvolumeclaims
  - secrets
  - services
  - serviceaccounts
  verbs:
  - '*'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: istio-operator
subjects:
- kind: ServiceAccount
  name: istio-operator
  namespace: istio-operator
roleRef:
  kind: ClusterRole
  name: istio-operator
  apiGroup: rbac.authorization.k8s.io
---


---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: istio-operator
  name: istio-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: istio-operator
  template:
    metadata:
      labels:
        name: istio-operator
    spec:
      serviceAccountName: istio-operator
      containers:
        - name: istio-operator
          image: docker.io/istio/operator:1.8.0
          command:
          - operator
          - server
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 1337
            runAsUser: 1337
            runAsNonRoot: true
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
          env:
            - name: WATCH_NAMESPACE
              value: 
            - name: LEADER_ELECTION_NAMESPACE
              value: "istio-operator"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "istio-operator"
            - name: WAIT_FOR_RESOURCES_TIMEOUT
              value: "300s"
            - name: REVISION
              value: ""
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-operator
  labels:
    istio-operator-managed: Reconcile
    istio-injection: disabled
---
apiVersion: v1
kind: Service
metadata:
  namespace: istio-operator
  labels:
    name: istio-operator
  name: istio-operator
spec:
  ports:
  - name: http-metrics
    port: 8383
    targetPort: 8383
    protocol: TCP
  selector:
    name: istio-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: istio-operator
  name: istio-operator
---
# SYNC WITH manifests/charts/base/files
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: istiooperators.install.istio.io
spec:
  group: install.istio.io
  names:
    kind: IstioOperator
    plural: istiooperators
    singular: istiooperator
    shortNames:
    - iop
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values.
            More info: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase.
            More info: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        spec:
          description: 'Specification of the desired state of the istio control plane resource.
            More info: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#spec-and-status'
          type: object
        status:
          description: 'Status describes each of istio control plane component status at the current time.
            0 means NONE, 1 means UPDATING, 2 means HEALTHY, 3 means ERROR, 4 means RECONCILING.
            More info: https://github.com/istio/api/blob/master/operator/v1alpha1/istio.operator.v1alpha1.pb.html &
            https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#spec-and-status'
          type: object
  versions:
  - name: v1alpha1
    served: true
    storage: true
---

`
``

**Comment by morvencao** [comment]
The fix is included in https://github.com/istio/istio/pull/29752
Need to be manually cherrypicked to release-1.7 and release-1.8

**Comment by abhassine** [comment]
hello @heikostumpf ,

I just discovered this issue when my automation tried to deploy a new environment.
Do we still need to add below apiGroup on cluster role manually ?

- apiGroups:
   - coordination.k8s.io
   resources:
   - leases
   verbs:
   - create
   - get
   - list
   - update

thank you for responding.

**Comment by heikostumpf** [comment]
@abhassine yeah i think so. Until the cherry-pick mentioned by @morvencao is available in an upcoming istio release you have to add/update the clusterrole manually.

**Comment by abhassine** [comment]
Thanks @heikostumpf 
I tested 1.8.2 same thing

**Comment by neemiasjnr** [comment]
Hi, just deployed the istio operator on the latest version 1.11.4 and I'm getting the same error. I confirm there is no `coordination.k8s.io` when I run `istioctl operator dump`

**Comment by morvencao** [comment]
The fixed would be available after 1.7.6 and 1.8.2, also new release after 1.9.

**Comment by neemiasjnr** [comment]
I realized that to fix the issue I had to update `istioctl` not only the operator, both to the last version 1.11.4

**Comment by AlexDHoffer** [comment]
I still get this up to 1.10 (haven't tested beyond). Pretty bizarre, since our 1.8 release is able to acquire that lock just fine. Did this never get cherry-picked into any release since? Seems like a big problem.
