### ISSUE TITLE
status: excessive goroutines/work done cluster without activity

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#30126]
Typically, in a production cluster the Istio config is changing extremely infrequently - generally just on a new deployment. Even pod changes may be rare depending on autoscaling config. For these clusters, Istiod is generally extremely low load.

With status, we are attempting to reconcile status every 200ms. For a large but inactive cluster, this adds excessive load on Istiod. 

This is made a bit worse by the fact that for each CRD we are creating a new goroutine (even with the open PR, see https://github.com/istio/istio/pull/29275/files#r555283120) and due to https://github.com/istio/istio/issues/30123.

It would be preferred if we don't try to do anything unless something has changed. I am not certain, but I would imagine we can get triggered when something happens to ensure that we are not working when we don't have to.

**Comment by mandarjog** [comment]
How much cpu was it using in the cluster, and what as the size of the cluster?>

**Comment by howardjohn** [comment]
I created a cluster with 1k small virtual services. There were no proxies. istiod uses 1 CPU total on status

**Comment by therealmitchconnors** [comment]
I used your script to re-create the scenario, but CPU utilization is at .03.  Is it possible you didn't enable analysis as well as status, which adds permissions to run status updates to the istiod role?

**Comment by howardjohn** [comment]
I am certain it was enabled, I checked the status and itwas written. I even added additional logging to show that it was reconciling every object every 200ms (where all the CPU was)

**Comment by howardjohn** [comment]
![2021-20-01_09-21-49](https://user-images.githubusercontent.com/623453/105212235-0f519880-5b02-11eb-9ec5-3b8c3ebece57.png)

I don't think the image worked

**Comment by therealmitchconnors** [comment]
ok, this appears to be related to the marshalling issue, #30123, which is fixed by #30187

**Comment by howardjohn** [comment]
Its related but I don't think its fixed. We still should not be doing anything iterating over all the configs and processing every 200ms. We need a more event driven design, any sort of linear iteration over all configs has historically caused massive issues for performance. Istio users often have thousands of resources

**Comment by howardjohn** [comment]
not stale

**Comment by howardjohn** [comment]
not stale
