### ISSUE TITLE
status: strip spec on UpdateStatus

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#30128]
Currently, when we call UpdateStatus, we send the full resource. Some users have massive `spec` fields, which leads to excessive serialization and network load.

Instead, I believe we can clear out the spec field (eg 	`cfg.Spec = nil`) before send it

**Comment by adiprerepa** [comment]
This `UpdateStatus`? https://github.com/istio/istio/blob/master/pilot/pkg/config/kube/crdclient/client.go#L239

Specifically, implemented in `types.gen.go` here? https://github.com/istio/istio/blob/master/pilot/pkg/config/kube/crdclient/types.gen.go#L230

I don't see us setting the `spec` anywhere.

And if you mean calling the `UpdateStatus` function and sending the full config, would the alternative be sending the GVK, namespace, and config.status?

**Comment by howardjohn** [comment]
I mean the user passes a config.Config which has the meta, spec, and
status. We then serialize that all to JSON and send to the api server.
However, serializing the spec field is a waste of time.

So I *think* we could modify the passed in config.Config to just remove the
spec for them, so we avoid the wasted work?

**Comment by adiprerepa** [comment]
Closing, this behavior already exists.
