### ISSUE TITLE
leader election: look into ownerRef on configmap

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#30124]
Currently, if a pod dies unexpectedly it may not clean up the leader election lock. We could probably add an ownerRef here: https://github.com/istio/istio/blob/c39fb2b0367130104d4a5967b26ebe9df513e99e/pilot/pkg/leaderelection/leaderelection.go#L95 to make it auto-gc.

**Comment by hzxuzhonghu** [comment]
When the pod exit, another pod could acquire the lock and own the configmap.

**Comment by hzxuzhonghu** [comment]
What's the issue then?

**Comment by howardjohn** [comment]
Today, if istiod exits gracefully it will release the configmap. But if it hard exits, it will not. In this case, a new pod can take control once the lease expires, which can be 60s.

If we add ownerRef, I think we can make it so if istio hard exits, the new pod can take ownership faster. So just a performance optimization

**Comment by howardjohn** [comment]
Also just an idea, I haven't seen if anyone else does this or if it improves things

**Comment by hzxuzhonghu** [comment]
I think maybe because the pod existence has no direct relationship with whether it is running.

**Comment by howardjohn** [comment]
Hmm, I guess so. It would be weird for the pod to be removed before the
container running it is removed though..
