### ISSUE TITLE
TestCustomizeMetrics test flakes

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#30136]
https://prow.istio.io/view/gs/istio-prow/logs/integ-telemetry-mc-k8s-tests_istio_postsubmit/1350132899017396224
https://prow.istio.io/view/gs/istio-prow/logs/integ-telemetry-mc-k8s-tests_istio_postsubmit/1349983963866730496
https://prow.istio.io/view/gs/istio-prow/logs/integ-telemetry-mc-k8s-tests_istio_postsubmit/1349812460441309184

Seems pretty common, and only in multicluster

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gs/istio-prow/logs/integ-telemetry-mc-k8s-tests_istio_postsubmit/1351906377110392832

**Comment by kyessenov** [comment]
How does the test know when to start sending requests? EnvoyFilter, which is the foundation of this test, has an undefined application deadline, and it might take a while for v8 to boot in the proxies and start applying the config.

**Comment by kyessenov** [comment]
Test might be flakey for the same reason as https://github.com/istio/istio/issues/29400.

**Comment by ericvn** [comment]
Yes, the #29400 was written initially written for when the test failed 100%, but the 100% failure was fixed in the istio code, and now the test flakes as noted here.
