### ISSUE TITLE
Mirror traffic management works with 1.7.6 but not working with 1.8.2 nor 1.8.1

### ISSUE THREAD

**Issue by javajon** [istio/istio#30143]
**Bug description**

Following the Istio documentation on [traffic management with mirroring](https://istio.io/latest/docs/tasks/traffic-management/mirroring/) with Istio version 1.7.6 the mirroring works as described. Following the same steps with Istio version 1.8.2 (and 1.8.1) and the mirror features does not work. When broken, the traffic is sent randomly to either the v1 or v2 httpbin service. The mirror declarations in version 1.8.x appear to be ignored.

To make replication easy you can run this Katacoda scenario [_Istio Traffic Management_](https://katacoda.com/javajon/courses/kubernetes-networking/istio-traffic-management) and flip the installation of istio between 1.7.6 and 1.8.1 (or any other version desired) found in step 3. I'm just reporting the versions where I confirmed the alleged defect.

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[X] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

When the VirtualService and DestinationRules are applied, the v1 and v2 logs for the httpbin pods should match the documentation. When broken, the curl commands through the sleep service appear randomly in the v1 and v2 logs rather than following the declarations in the VirtualService and DestinationRule.

Since it works correctly with 1.7.6 and not with 1.8.1 suspicion points to the Istio release 1.8.x and not this example scenario's environment or configuration. Nothing was noted in the 1.8.x release notes related to changes in the mirror feature. The diagnosis and experimentation for finding the problem can be done in the provided katacoda scenario.

**Steps to reproduce the bug**

1. Run the provided Katacoda scenario [_Istio Traffic Management_](https://katacoda.com/javajon/courses/kubernetes-networking/istio-traffic-management). Complete steps 1, 2, 3 then skip to the last step 11 for exercising the mirror feature. In step 3, change the istio version setting to version 1.7.6 to show mirroring working.  Start a new scenario and leave as 1.8.2 and follow same steps to see mirroring not working.

2. Follow the steps in step 11. The only difference between the Istio documentation on [traffic management with mirroring](https://istio.io/latest/docs/tasks/traffic-management/mirroring/) and these steps, is the experiment is run in the namespace _mirror_. (Running it in the default namespace causes other problems related to proxy injection when using istoctl inject conflicting with namespace label injection)

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```bash
istioctl version --remote
client version: 1.8.2
control plane version: 1.8.2
data plane version: 1.8.2 (10 proxies)
```
```bash
kubectl version --short
Client Version: v1.18.0
Server Version: v1.18.0
```
```bash
helm version --short
v3.1.2+gd878d4d
```

**How was Istio installed?**

Per istio readme:
```bash
curl -L https://istio.io/downloadIstio | sh -
export PATH="$PATH:/root/istio-${ISTIO_VERSION}/bin"
istioctl install -y --set profile=demo
```
In the referenced Katacoda scenario [_Istio Traffic Management_](https://katacoda.com/javajon/courses/kubernetes-networking/istio-traffic-management) see shell script: `/usr/local/bin/start-istio.sh`

**Environment where the bug was observed (cloud vendor, OS, etc)**

Full and open environment is available here for diagnosis and experimentation: Katacoda scenario [_Istio Traffic Management_](https://katacoda.com/javajon/courses/kubernetes-networking/istio-traffic-management).

**Comment by howardjohn** [comment]
I went through it, and got caught up by the `istioctl kube-inject` thing multiple times. Once I finally resolved all of those, it seemed to work fine. At some point I had no sidecar for the sleep pod, causing it to not follow the rules

**Comment by javajon** [comment]
To inject or not inject, that is the question.  =)

@howardjohn you pointed right to it. In the sleep deployment a line snuck in that was not part of the documentation:

`sidecar.istio.io/inject: "false"`

Even with kube-inject this annotation with override as expected. In turn Istio produced this helpful message:

`===> Skipping injection because "sleep" has sidecar injection disabled`

And as you said the sleep Pod was missing the envoy sidecar. Once that uninvited annotation was removed, the Envoy sidecar was added and the mirror rule worked as expected and as you reported. I'm not sure why the problem did not appear to exist with 1.7.6, but it could have been my testing. 

(The scenario has been corrected.)

Thank you.

**Comment by howardjohn** [comment]
btw, I found this super hard, even as someone who just spent months working on the injector code. I opened https://github.com/istio/istio.io/issues/8810 to hopefully make the docs better. Thanks!
