### ISSUE TITLE
Bookinfo with custom DNS not working

### ISSUE THREAD

**Issue by crrazyman** [istio/istio#30156]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
I have an AKS (Azure) cluster with 3 nodes and Istio installed simply with `istioctl install --set meshConfig.accessLogFile=/dev/stdout`. Everything works good
**kubernetes version 1.18.10 and istio version 1.8.0**

If i deploy bookinfo just like [here](https://istio.io/latest/docs/examples/bookinfo/?_ga=2.106598723.1555642532.1610961734-45083063.1609863063) everything works, i find the external IP for istio-ingressgateway (type LoadBalancer) and i can `curl <EXTERNAL_IP>/api/v1/products` or access it in my browser and everything works.
I’ve made a DNS entry in Azure for `book.example.com - <EXTERNAL_IP>` and i can verify that it’s correct with dig/ping/host/etc. Also i’ve modified the gateway and the virtualservice for bookinfo like this:
```
diff --unified k8s-manual/istio/istio-demo-gateway.yaml k8s-manual/istio/test-gateway.yaml 
--- k8s-manual/istio/istio-demo-gateway.yaml	2020-12-10 15:18:35.000000000 +0200
+++ k8s-manual/istio/test-gateway.yaml	2021-01-12 22:10:47.000000000 +0200
@@ -11,7 +11,7 @@
       name: http
       protocol: HTTP
     hosts:
-    - "*"
+    - book.example.com
 ---
 apiVersion: networking.istio.io/v1alpha3
 kind: VirtualService
@@ -19,7 +19,7 @@
   name: bookinfo
 spec:
   hosts:
-  - "*"
+  - book.example.com
   gateways:
   - bookinfo-gateway
   http:
```
In short, everything that i’ve changed is the host info.
Now if i test with curl, everything works:

```
curl book.example.com/api/v1/products
[{"id": 0, "title": "The Comedy of Errors", "descriptionHtml": "<a href=\"https://en.wikipedia.org/wiki/The_Comedy_of_Errors\">Wikipedia Summary</a>: The Comedy of Errors is one of <b>William Shakespeare's</b> early plays. It is his shortest and one of his most farcical comedies, with a major part of the humour coming from slapstick and mistaken identity, in addition to puns and word play."}]
```
I can even see the the access logs from istio-proxy:

```
kubectl logs -f productpage-v1-6987489c74-6td6v -c istio-proxy
[2021-01-12T20:35:11.100Z] "GET /api/v1/products HTTP/1.1" 200 - "-" 0 395 2 1 "10.10.0.4" "curl/7.64.1" "baa2e80b-2227-4707-8a1e-98abffb06616" "book.example.com" "127.0.0.1:9080" inbound|9080|| 127.0.0.1:35354 10.10.0.127:9080 10.10.0.4:0 outbound_.9080_._.productpage.default.svc.cluster.local default
```
But if i enter this url in my browser i get book.example.com took too long to respond.
Istio-proxy logs are empty, the request does not even gets to it.
I’ve tried multiple browsers on my laptop, from my phone and even with online page checkers. It does not work and it’s killing me.

**Affected product area (please put an X in all that apply)**
[X] Networking

**Expected behavior**
Access to book.example.com/api/v1/products from any browser

**Steps to reproduce the bug**
- Deploy bookinfo application just like in the documentation
- Change gateway and virtualservice and add `hosts`
**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
$ istioctl version --remote
client version: 1.8.0
control plane version: 1.8.0
data plane version: 1.8.0 (12 proxies)

$ kubectl version --short
Client Version: v1.19.4
Server Version: v1.18.10

$ helm version --short
v3.1.2+gd878d4d
```

**How was Istio installed?**
`istioctl install --set meshConfig.accessLogFile=/dev/stdout`
**Environment where the bug was observed (cloud vendor, OS, etc)**
Azure AKS

[bug-report.tgz.zip](https://github.com/istio/istio/files/5829228/bug-report.tgz.zip)

**Comment by howardjohn** [comment]
Very interesting, so curl works but no browsers do?

I wonder if other CLi tools work? For example, `docker run --rm --entrypoint client gcr.io/istio-testing/app:latest httpbin.org/get`

You may also try:
* Enable debug logs (istioctl pc log POD --level=debug) on envoy, see if anything shows up there
* Check browser debugger tab. See where its failing, if DNS is resolving correctly, etc

**Comment by crrazyman** [comment]
> Very interesting, so curl works but no browsers do?
> 
> I wonder if other CLi tools work? For example, `docker run --rm --entrypoint client gcr.io/istio-testing/app:latest httpbin.org/get`
> 
> You may also try:
> 
> * Enable debug logs (istioctl pc log POD --level=debug) on envoy, see if anything shows up there
> * Check browser debugger tab. See where its failing, if DNS is resolving correctly, etc

Hello and thank you for your reply:

I did all of the above:

- Enabling debug logs on envoy showed nothing when accessing the link from the browser
- Other CLi tools seem to work:

```
# docker run --rm --entrypoint client gcr.io/istio-testing/app:latest book.example.com/api/v1/products
Unable to find image 'gcr.io/istio-testing/app:latest' locally
latest: Pulling from istio-testing/app
f22ccc0b8772: Pull complete 
3cf8fb62ba5f: Pull complete 
e80c964ece6a: Pull complete 
e69a120d0c7e: Pull complete 
743599d901d4: Pull complete 
75ead5d36eb1: Pull complete 
ef569313f095: Pull complete 
43d41e117bb3: Pull complete 
5535340ed208: Pull complete 
Digest: sha256:72358f29214bf38803042ce628bfb03e9d56346fe6aca08748c781f3f076cc26
Status: Downloaded newer image for gcr.io/istio-testing/app:latest
[0] Url=http://book.example.com/api/v1/products
[0] StatusCode=200
[0] ResponseHeader=Content-Length:395
[0] ResponseHeader=Content-Type:application/json
[0] ResponseHeader=Date:Thu, 21 Jan 2021 08:48:31 GMT
[0] ResponseHeader=Server:istio-envoy
[0] ResponseHeader=X-Envoy-Upstream-Service-Time:2
[0 body] [{"id": 0, "title": "The Comedy of Errors", "descriptionHtml": "<a href=\"https://en.wikipedia.org/wiki/The_Comedy_of_Errors\">Wikipedia Summary</a>: The Comedy of Errors is one of <b>William Shakespeare's</b> early plays. It is his shortest and one of his most farcical comedies, with a major part of the humour coming from slapstick and mistaken identity, in addition to puns and word play."}]

2021-01-21T08:48:31.292018Z	info	All requests succeeded
```

The interesting thing happens in browser developer tools. At the network tab i can see my Request URL: http://book.example.com/api/v1/products BUT i can see in Response Headers section: "http**s**://book.example.com/api/v1/products". But i don't understand how is this possible and why there is not the case with cURL.
I've attached print-screens from developer tools.
<img width="834" alt="1" src="https://user-images.githubusercontent.com/5878145/105328351-a1c46b80-5bd8-11eb-8786-ee24e8040cc7.png">
<img width="834" alt="2" src="https://user-images.githubusercontent.com/5878145/105328389-aa1ca680-5bd8-11eb-95c4-1947b6ddb5f6.png">

**Comment by howardjohn** [comment]
Looks like its caused by https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security, which tiggers the browser to redirect to https but not CLI tools

**Comment by crrazyman** [comment]
Wow, thanks! So is there anything i can do on istio side to disable this behaviour?

**Comment by howardjohn** [comment]
I think this might be something being handled by your cloud provider or
external load balancer possibly? not certain though
