### ISSUE TITLE
ServiceGraph service is not started

### ISSUE THREAD

**Issue by lordofthejars** [istio/istio#3015]
Using minishift-1.11 with OpenShift 3.7.1 and Istio 0.5.0, everything works as expected but when I try to install `ServiceGraph` by running `oc create -f ${ISTIO_HOME}/install/kubernetes/addons/servicegraph.yaml` the Pod is registered but it is never up. Trying to see the logs from OpenShiftUI, but they are empty so I don't really know what is going on.

I tried with Istio 0.2.X and it worked.

**Comment by DonSchenck** [comment]
Same problem. Here is a screen capture from the OpenShift console:
![screen shot 2018-01-31 at 1 13 31 pm](https://user-images.githubusercontent.com/5067110/35654932-6ee91d50-06bd-11e8-8734-f166cefe2c39.png)

**Comment by lordofthejars** [comment]
@DonSchenck It seems that the base image of `ServiceGraph` needs some root access which OpenShift protects you can do exactly that.

**Comment by xavierbaude** [comment]
The image 0.5.0 built 2 days ago is only 1MB and the 0.4.0 is 137MB. Maybe the push is in error.

```
docker@minishift:~$ docker images|grep servi
istio/servicegraph                 0.5.0               47afbc4a5967        2 days ago          1.698 MB
istio/servicegraph                 0.4.0               accd6b847c25        48 years ago        137.6 MB
```

And even in openshift debug terminal I get:
```
Could not start container servicegraph.

An error occurred starting the debug pod. invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"sleep\\\": executable file not found in $PATH\"\n" Exit code: 127
```

**Comment by rvrignaud** [comment]
Duplicates https://github.com/istio/issues/issues/179

**Comment by douglas-reid** [comment]
I have a PR out to fix the first part of this problem: https://github.com/istio/istio/pull/3079

**Comment by andraxylia** [comment]
Closed, duplicate.
