### ISSUE TITLE
Destination rule not getting registered

### ISSUE THREAD

**Issue by ctapas** [istio/istio#30161]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
Destination rule for newly deployed environment not registering the host.
```
$ istioctl authn tls-check connect-server-0.dev -i infra-system
HOST:PORT                                                          STATUS     SERVER         CLIENT           AUTHN POLICY                                 DESTINATION RULE
apiserver.dev.svc.cluster.local:4000                               OK         PERMISSIVE     -                /default                                     -
bot-engine.dev.svc.cluster.local:5000                              OK         PERMISSIVE     -                /default                                     -
connect-server.dev.svc.cluster.local:2000                          OK         PERMISSIVE     -                /default                                     -
```
Trying to curl these services using thier public url gives 404. But verbose output of the curl command shows that the connection was established and reached till istio-envoy. But since the destination rules are not registered it returns 404.
I even checked `$ istioctl proxy-config routes` and see no entry for these services.

These services are exposed via ingress service[AWS ALB] + gateway + virtual service. We have deployed muliple namespaces with same setup. But with this new setup we are facing the issue of destination rule not getting applied correctly.

The istio sidecar logs shows the admission request for these services were served. Proxy status shows no error.
```
$ istioctl proxy-status -i infra-system
NAME                                                      CDS        LDS        EDS        RDS        PILOT                            VERSION
apiserver-677fd5b888-wxvft.dev                            SYNCED     SYNCED     SYNCED     SYNCED     istio-pilot-59df955f84-lpjvf     1.4.3
bot-engine-0.dev                                          SYNCED     SYNCED     SYNCED     SYNCED     istio-pilot-59df955f84-lpjvf     1.4.3
connect-server-0.dev                                      SYNCED     SYNCED     SYNCED     SYNCED     istio-pilot-59df955f84-lpjvf     1.4.3
```
Although when I describe the pod's destination rule I get `client protocol unspecified`
```
$ istioctl x describe pod connect-server-0.dev -i infra-system
Pod: connect-server-0.dev
   Pod Ports: 2000 (connect-server), 2100 (connect-server), 15090 (istio-proxy)
Suggestion: add 'version' label to pod for Istio telemetry.
--------------------
Service: connect-server.dev
   Port: http-connect 2000/HTTP targets pod port 2000
   Port: http-bot-int 2100/HTTP targets pod port 2100
2000 Pod is PERMISSIVE, client protocol unspecified
2100 Pod is PERMISSIVE, client protocol unspecified
```

Validated the istio config on Kiali and it shows no error.
<img width="1228" alt="Screenshot 2021-01-18 at 10 59 54 PM" src="https://user-images.githubusercontent.com/77627744/104947098-34021f00-59e1-11eb-917f-73f335dfa4d6.png">

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
Istio: 1.4.3
Helm: v2.16.7+g5f2584f

**How was Istio installed?**
```
curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get > install-helm.sh
chmod u+x install-helm.sh
./install-helm.sh
```

**Environment where the bug was observed (cloud vendor, OS, etc)**
AWS EKS

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by esnible** [comment]
Does `istioctl analyze` report any information about the destination rules that are not getting applied?  Or the Gateway and Virtual Service that expose the destinations to your _curl_?

Can you attach to this issue an example of a non-working rule?

**Comment by howardjohn** [comment]
Please try a newer version, Istio 1.4 is no longer supported (see https://istio.io/latest/news/support/announcing-1.6-eol/). If you can reproduce this on newer versions, please post the cluster dump following https://istio.io/latest/about/bugs/#generating-a-cluster-state-archive. Thanks!

**Comment by ctapas** [comment]
> Does `istioctl analyze` report any information about the destination rules that are not getting applied? Or the Gateway and Virtual Service that expose the destinations to your _curl_?
> 
> Can you attach to this issue an example of a non-working rule?

`istioctl analyze` returns `Error: unknown command "analyze" for "istioctl"`.

**Comment by ctapas** [comment]
> Please try a newer version, Istio 1.4 is no longer supported (see https://istio.io/latest/news/support/announcing-1.6-eol/). If you can reproduce this on newer versions, please post the cluster dump following https://istio.io/latest/about/bugs/#generating-a-cluster-state-archive. Thanks!

Sure I will try that. Not sure how much time it may take. We got few environments running on this cluster. 
I will raise another issue if the destination rule issue still persists in the new version.
Thanks.

**Comment by howardjohn** [comment]
Thanks @ctapas !
