### ISSUE TITLE
status: dependency on galley/ issues

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#30164]
# Watches
Total watches:

![2021-18-01_09-50-41](https://user-images.githubusercontent.com/623453/104948775-aee02100-5972-11eb-9cfa-e744bb7efcf8.png)

Istio watches:

![2021-18-01_09-51-32](https://user-images.githubusercontent.com/623453/104948867-d636ee00-5972-11eb-817a-9e954e3cb420.png)

3 steps are: analysis enabled, analysis disabled, istiod disabled.

I am not certain why I still have watchers without istiod, may be some kube-system thing.

Basically, analysis leads to 2x watches on all resources. For large clusters, this has a large overhead.

Related: https://github.com/istio/istio/issues/23943

# Cpu utilization

Galley's implementation of API-server watches is extremely inefficient. In my cluster, I see 10% of pilot CPU is spent inside of galley's watching. Pilot's crdclient, which is reading the same exact thing, uses only 0.2%

# Technical debt

This code has been obsolete and scheduled for over a year. It is incredibly complex, over 30k LOC, to implement some simple logic.

**Comment by howardjohn** [comment]
I am rebranding this to "Issue caused by using galley for status" since its pretty much all the same, I don't want to dillute the same discussionin multiple places.

**Comment by howardjohn** [comment]
35% of istiod CPU is spent in galley/ with analysis enabled. I think my previous 10% claim was when distribution was enabled, which took up a large chunk:
![2021-29-01_07-53-23](https://user-images.githubusercontent.com/623453/106296980-23cf1880-6207-11eb-88e6-83a585d61d2b.png)

**Comment by mandarjog** [comment]
What load was istiod under at this point? I assume that galley load scales by number of config changes.
istiod load will scale by config changes, end point changes and number of connected clients.

**Comment by howardjohn** [comment]
just running 15 ns of isotope. Galley is scaling poorly with number of config changes despite reading the same as istiod stack. I believe its using an older, less efficient, k8s client implementation

**Comment by howardjohn** [comment]
not stale

**Comment by howardjohn** [comment]
not stale

**Comment by howardjohn** [comment]
will be fixed by https://github.com/istio/istio/pull/35764
