### ISSUE TITLE
[1.9.0-beta.0] Grafana import Istio Dashboard display null

### ISSUE THREAD

**Issue by shamsher31** [istio/istio#30173]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

Ref: https://preliminary.istio.io/latest/docs/ops/integrations/grafana/#option-2-import-from-grafana-com-into-an-existing-deployment

```
$ ./grafana.sh 
Importing null (revision , id 7639)...

Done

Importing null (revision , id 11829)...

Done

Importing null (revision , id 7636)...

Done

Importing null (revision , id 7630)...

Done

Importing null (revision , id 7642)...

Done

Importing null (revision , id 7645)...

Done
```

**Affected product area (please put an X in all that apply)**

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```
$ ./bin/istioctl version --remote
client version: 1.9.0-beta.0
control plane version: 1.9.0-beta.0
data plane version: 1.9.0-beta.0 (1 proxies)
```
```
$ kubectl version --short
Client Version: v1.19.0
Server Version: v1.19.1
```

**How was Istio installed?**

```
[istio-1.9.0-beta.0]$ ./bin/istioctl install
```

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by esnible** [comment]
Labeling as `environments` because the document has `owner: istio/wg-environments-maintainers`.

**Comment by howardjohn** [comment]
sent out a PR, but fwiw it won't work on 1.9.0-beta.0 (site will say "1.9.0" which is not yet published)
