### ISSUE TITLE
Re-evaluate performance of StatusGen 

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#30178]
Though StatusGen.OnConnect  OnDisconnect and OnNack is called maybe with a very low cost each time. 

However, OnConnect  is called whenever a new stream created
                OnDisconnect is called when a stream is done
                OnNack is called when a nack happens

They all do some serialization and iterate over all the clients, which is very ugly behavior.

As the proxy number becomes larger, the cost can not be underestimated.

Can anyone tell who needs these infos? Is there a real use case now? @howardjohn @costinm

**Comment by howardjohn** [comment]
We can do lazy serialization to prevent expensive calls when there are 0 clients connected for the types. We could also have an index of type -> client if the iteration is too much.

The plan was to use this for debugging tools like istioctl and kiali but I don't think the implementation is complete. We can certainly turn it off by default for now?

**Comment by hzxuzhonghu** [comment]
Turn off sgtm
