### ISSUE TITLE
istio.io tasks/traffic-management/locality-load-balancing/distribute test fails on the 1.9 branch

### ISSUE THREAD

**Issue by ericvn** [istio/istio#30181]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

Trying to move the istio.io tests from the release-1.8 branch to releasse-1.9 and the test now fails. The tail end of the log (https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio.io/8562/doc.test.profile_default_istio.io/1351549967608582144/artifacts/tests-setup-profile-default-fdc/TestDocs/tasks/traffic-management/locality-load-balancing/distribute/test.sh/test.sh/_test_context/test.sh_output.txt:

```
Actual locality distribution:
region1.zone1: 36
region1.zone2: 32
region2.zone3: 0
region3.zone4: 32
Invalid locality distribution to region1.zone1: 36. Expected: 70
```

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

Tests should pass

**Steps to reproduce the bug**

Run the istio.io test or try and follow the instructions on the content/en/docs/tasks/traffic-management/locality-load-balancing/distribute/index.md page.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

1.0.0-beta.0 (currently)

**How was Istio installed?**

via test framework

**Environment where the bug was observed (cloud vendor, OS, etc)**

Istio testing pipeline

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by nmittler** [comment]
@ramaraochavali can you take a look?

**Comment by nmittler** [comment]
@ramaraochavali when I remove [outlier detection](https://github.com/istio/istio.io/blob/master/content/en/docs/tasks/traffic-management/locality-load-balancing/distribute/snips.sh#L41) from the test config, it seems to work. Somehow including outlier detection is now breaking the test.

**Comment by ramaraochavali** [comment]
@nmittler sure. Will take a look.

**Comment by ramaraochavali** [comment]
@nmittler looking at it looks like it is actually distributing but with unexpected distribution. I am wondering if it is because of available endpoints in that locality - not sure how outlier detection is impacting this. @hzxuzhonghu Any idea ?

**Comment by nmittler** [comment]
@ramaraochavali it used to load balance properly. Are you aware of any other changes related to locality LB that might be causing this?

**Comment by ericvn** [comment]
I haven't tried to run the page's example, but it does have the distribution as:
```
            "region1/zone1/*": 70
            "region1/zone2/*": 20
            "region3/zone4/*": 10
```
It sends 50 requests, and tabulates the number to each (and then multiplies by 2) so you think of it out of a 100 runs. Why they don't just run 10 curls, I'm not sure.

Here's the check, so there is leeway of course:
```
    if ((z1 < 60 || z1 > 80)); then
      echo "Invalid locality distribution to region1.zone1: $z1. Expected: 70"
      exit 1
    elif ((z2 < 10 || z2 > 30)); then
      echo "Invalid locality distribution to region1.zone2: $z2. Expected: 20"
      exit 1
    elif ((z3 > 0)); then
      echo "Invalid locality distribution to region2.zone3: $z3. Expected: 0"
      exit 1
    elif ((z4 < 5 || z4 > 20)); then
      echo "Invalid locality distribution to region1.zone2: $z4. Expected: 10"
      exit 1
    fi
}
```

**Comment by ericvn** [comment]
But as mentioned, this works fine when run against 1.8.2, but fails when run against 1.9.0-beta.0

**Comment by ramaraochavali** [comment]
> Are you aware of any other changes related to locality LB that might be causing this?

No.  Certainly that PR should not affect this. But I will continue to look

**Comment by nmittler** [comment]
Hey @ramaraochavali any update?

**Comment by ramaraochavali** [comment]
No. I could not find any thing. @hzxuzhonghu Any idea how this can happen?

**Comment by hzxuzhonghu** [comment]
It looks this roundrobin, could we dump the configdump

**Comment by nmittler** [comment]
This is a regression, so I suspect it's a release blocker

FYI @smawson @stevenctl @duderino @ericvn

**Comment by nmittler** [comment]
FYI here are some recent locality LB-related PRs:

https://github.com/istio/istio/pull/29238
https://github.com/istio/istio/pull/29513

**Comment by ericvn** [comment]
@nmittler I concur with the release blocker and had marked this a such earlier. https://github.com/istio/istio/pull/29238 seems suspiciously like it might be the cause.

**Comment by ramaraochavali** [comment]
I am not able to find any thing how that can cause this issue. But I will push a PR to revert #29238 to master today. @hzxuzhonghu WDYT? Any other suggestions?

**Comment by hzxuzhonghu** [comment]
Is there evidence #29238 is the cause? We should have a test, at least from https://github.com/istio/istio/issues/30181#issuecomment-763252761, i can not see this is related

**Comment by nmittler** [comment]
@hzxuzhonghu no evidence ... just looking at issues that are explicitly related to locality LB. The real issue could be deeper. Can you help investigate?

**Comment by hzxuzhonghu** [comment]
Suspect if the locality is set correctly on the endpoint

**Comment by ericvn** [comment]
I did try and setup a local environment for testing, we don't document how to do this using personally built images but I hopefully have the test using them, and if I reverted the above mentioned PR the tests still fail.

**Comment by ramaraochavali** [comment]
Is it possible to get config_dump on 1.8.2  and 1.9?

**Comment by ericvn** [comment]
If someone has the appropriate commands to run in the test script, probably after https://github.com/istio/istio.io/blob/master/content/en/docs/tasks/traffic-management/locality-load-balancing/distribute/test.sh#L95, I (or anyone) can try and add them and run the test.

**Comment by ericvn** [comment]
Here should be a config_dump for running against 1.9
[config_dmp_1_9_.txt](https://github.com/istio/istio/files/5904578/config_dmp_1_9_.txt)

Getting the dump for 1.8 is a little more difficult as the 1.8 istio framework has an older version of the test framework so need to try and revert to an older istio.io commit which works with 1.8

**Comment by ericvn** [comment]
Here's a similar file when run against 1.8 when the test passes:

[config_dmp_1_8_.txt](https://github.com/istio/istio/files/5904785/config_dmp_1_8_.txt)

**Comment by ramaraochavali** [comment]
Thank you so much. I will take a look. @hzxuzhonghu Can you also PTAL?

**Comment by ericvn** [comment]
In case we need a different command run later, here is what I added to the script to generate the files above:
```
kubectl exec --context="${CTX_R1_Z1}" -n sample -c istio-proxy \
  "$(kubectl get pods --context="${CTX_R1_Z1}" -n sample -l \
  app=sleep -o jsonpath='{.items[0].metadata.name}')" \
  -- pilot-agent request GET config_dump
```

**Comment by hzxuzhonghu** [comment]
Thanks for the test.

As from the result, i find cluster.CommonLbConfig is not set. And also there are no endpoints dumped. Need to run `pilot-agent request GET clusters` as well.

**Comment by ericvn** [comment]
New files:
[dump2_1_8.txt](https://github.com/istio/istio/files/5908531/dump2_1_8.txt)
[dump2_1_9.txt](https://github.com/istio/istio/files/5908532/dump2_1_9.txt)

**Comment by ramaraochavali** [comment]
Looks like outlier detection is also not there in 1.9. So I am wondering if the destination rule is applied correctly in 1.9?

```
      "outlier_detection": {
       "consecutive_5xx": 100,
       "interval": "1s",
       "base_ejection_time": "600s",
       "enforcing_consecutive_5xx": 100,
       "enforcing_success_rate": 0
      },
```

Can you also please dump the output of `kubectl get destinationrule helloworld -n sample` ?

**Comment by hzxuzhonghu** [comment]
```
outbound|5000||helloworld.sample.svc.cluster.local::172.30.109.29:5000::weight::1
outbound|5000||helloworld.sample.svc.cluster.local::172.30.109.32:5000::weight::1
outbound|5000||helloworld.sample.svc.cluster.local::172.30.32.10:5000::weight::1
```

Same weight here

**Comment by hzxuzhonghu** [comment]
so looks the destinationrule is not applied

**Comment by ericvn** [comment]
I do notice that here is a `sleep 5` in the test to allow the destination rule to propagate: https://github.com/istio/istio.io/blob/master/content/en/docs/tasks/traffic-management/locality-load-balancing/distribute/test.sh#L32

Pointer to DR:  https://github.com/istio/istio.io/blob/master/content/en/docs/tasks/traffic-management/locality-load-balancing/distribute/snips.sh#L23

**Comment by ericvn** [comment]
For 1.9:

```
destinationrule.networking.istio.io/helloworld created

DestinationRule:
NAME         HOST                                  AGE
helloworld   helloworld.sample.svc.cluster.local   5s

kubectl describe of DestinationRule:
Name:         helloworld
Namespace:    sample
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"networking.istio.io/v1beta1","kind":"DestinationRule","metadata":{"annotations":{},"name":"helloworld","namespace":"sample"...
API Version:  networking.istio.io/v1beta1
Kind:         DestinationRule
Metadata:
  Creation Timestamp:  2021-02-02T14:41:51Z
  Generation:          1
  Managed Fields:
    API Version:  networking.istio.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:host:
        f:trafficPolicy:
          .:
          f:loadBalancer:
            .:
            f:localityLbSetting:
              .:
              f:distribute:
              f:enabled:
          f:outlierDetection:
            .:
            f:baseEjectionTime:
            f:consecutive5xxErrors:
            f:interval:
    Manager:         kubectl
    Operation:       Update
    Time:            2021-02-02T14:41:51Z
  Resource Version:  3683038
  Self Link:         /apis/networking.istio.io/v1beta1/namespaces/sample/destinationrules/helloworld
  UID:               7602dc8b-3a8a-4b00-a50b-ec2f64f9ce41
Spec:
  Host:  helloworld.sample.svc.cluster.local
  Traffic Policy:
    Load Balancer:
      Locality Lb Setting:
        Distribute:
          From:  region1/zone1/*
          To:
            region1/zone1/*:  70
            region1/zone2/*:  20
            region3/zone4/*:  10
        Enabled:              true
    Outlier Detection:
      Base Ejection Time:    10m
      consecutive5xxErrors:  100
      Interval:              1s
Events:                      <none>
```

**Comment by ericvn** [comment]
To run this test is pretty easy. If you have a Kubernetes cluster in your Kubeconfig, just pull the istio.io repo, and run `make doc.test.profile_default TEST=tasks/traffic-management/locality-load-balancing/distribute/test.sh`. There are a few extra things you may need if using a kind cluster or running on a Mac and those are documented in the istio.io tests/README.md. If you run the current master branch, you are running against a 1.9 istio build, if you checkout an older commit (9527e7f83ae4975654c85b6da429e2a77973fb37), that runs against a 1.8 istio build.

**Comment by hzxuzhonghu** [comment]
I found the root cause: 
2021-02-03T02:01:25.796932Z	warn	ads	ADS:CDS: ACK ERROR sidecar~10.244.0.9~helloworld-region1.zone1-77985dbcc7-bxlcd.sample~sample.svc.cluster.local-11 Internal:Error adding/updating cluster(s) outbound|5000||helloworld.sample.svc.cluster.local: outlier detector's max_ejection_time cannot be smaller than base_ejection_time

**Comment by nmittler** [comment]
@hzxuzhonghu thanks for the find! So the question is: why is it breaking now? Did the default value for base_ejection_time change in 1.9?

**Comment by hzxuzhonghu** [comment]
It is added in envoy 1.7, so it is.
