### ISSUE TITLE
helm add repo istio 1.6 rev failed.

### ISSUE THREAD

**Issue by tulid** [istio/istio#30207]
Hi Author:
     I want to install istio 1.6.1 using helm according to the official [doc](https://istio.io/v1.6/zh/docs/setup/install/helm/) but it's failed. Pls help me resolve it. TKS a lot.
root@jinquan:~/jinquan/istio# helm repo add istioo https://storage.googleapis.com/istio-release/releases/1.6.8/charts/
Error: looks like "https://storage.googleapis.com/istio-release/releases/1.6.8/charts/" is not a valid chart repository or cannot be reached: failed to fetch https://storage.googleapis.com/istio-release/releases/1.6.8/charts/index.yaml : 404 Not Found

![image](https://user-images.githubusercontent.com/44944641/105143367-b8b28180-5b36-11eb-817d-3c6f46f1e587.png)

**Comment by howardjohn** [comment]
Hi @tulid, thanks for the report. Unfortunately, the chinese docs here are outdated ( see page not existing in english: https://istio.io/v1.6/en/docs/setup/install/helm/).

Additionally, Istio 1.6 Is EOL: https://istio.io/latest/news/support/announcing-1.6-eol/

The new helm documentation, which does not support `helm repo add`, can be found here: https://istio.io/latest/docs/setup/install/helm/. Thanks!
