### ISSUE TITLE
status: excessive CPU on proxy events

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#30218]
Setup:
* Create 3k virtual services
* Spin up 1 pod, then 2, then 3 ..

CPU usage is >1 CPU: 
![2021-20-01_09-51-46](https://user-images.githubusercontent.com/623453/105214636-1d54e880-5b05-11eb-8ac4-78ef0c4a77c5.png)

Without status enabled, CPU usage is ~60m

**Comment by jasonwzm** [comment]
@howardjohn How many analysis messages were you seeing?

**Comment by howardjohn** [comment]
each virtual service has 1 message
