### ISSUE TITLE
Sidecar proxy keeps tcp connection established with a terminated / lost pod

### ISSUE THREAD

**Issue by SCLogo** [istio/istio#30212]
**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
When destination pod / sidecar proxy dissapear close all established connection
**Steps to reproduce the bug**
1. have sidecar injected service mesh
2. install redis-ha
3. have an app that connects to master
4. kill master redis
5. check client side proxy `netstat -nat | egrep -E 6379`

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
istio: `client version: 1.7.3
control plane version: 1.7.3
data plane version: 1.7.3 (23 proxies) ` same issue with 1.8.2
helm: ` v3.4.2+g23dd3af`
kubectl: `Client Version: v1.20.1
Server Version: v1.18.12` but same issue on 1.17.14

**How was Istio installed?**
with istioctl
**Environment where the bug was observed (cloud vendor, OS, etc)**
AWS, node: ubuntu 20.04, installed with kops
![issue](https://user-images.githubusercontent.com/57345923/105194021-763e7400-5b39-11eb-8618-6c1d777ebf1e.png)

**Comment by howardjohn** [comment]
So the flow is:

`redis CLI --A--> redis CLI sidecar ---B--> redis server sidecar ---C--> redis server`

And you kill redis server, so we have`redis CLI --A--> redis CLI sidecar ---B--> redis server sidecar ---C--> redis server (DEAD)`

And connection B is still open? Is that accurate?

**Comment by SCLogo** [comment]
correct.

**Comment by SCLogo** [comment]
> So the flow is:
> 
> `redis CLI --A--> redis CLI sidecar ---B--> redis server sidecar ---C--> redis server`
> 
> And you kill redis server, so we have`redis CLI --A--> redis CLI sidecar ---B--> redis server sidecar ---C--> redis server (DEAD)`
> 
> And connection B is still open? Is that accurate?

Yes, with this you can reproduce the issue

**Comment by howardjohn** [comment]
I believe this is intended. @lambdai to confirm

**Comment by howardjohn** [comment]
Can you only reproduce this with redis or other apps? I didn't see similar behavior in my tests

**Comment by SCLogo** [comment]
We saw and tested this only on Redis.
