### ISSUE TITLE
Presubmit e2e smoke test should only run BookInfo, but it runs MixerTest

### ISSUE THREAD

**Issue by hklai** [istio/istio#3022]
Example: https://prow.istio.io/log?job=e2e-smoke&id=2116

Search for mixer_test.go and it is being run.

**Comment by mattdelco** [comment]
Some related background in this PR https://github.com/istio/istio/pull/2960 where I don't try to fix the issue but do try to get parameters passed again (and consequently remove the unhandled -s bookinfo parameter).
