### ISSUE TITLE
Something With RRAC has Changed

### ISSUE THREAD

**Issue by towens** [istio/istio#30227]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
Two functioning meshes. At some point after running
`istioctl x uninstall --purge` on both

Any type of Istio install (either cluster) fails with istiod logs:
```
error	k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125: Failed to list *v1.Pod: Unauthorized
error	k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125: Failed to list *v1.Service: Unauthorized
error	k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125: Failed to list *v1.Endpoints: Unauthorized
error	k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125: Failed to list *v1.Node: Unauthorized 
```

I understand deleting a cluster removes RBAC perms, I've never seen this before all the way back to 1.3.3. A change in the docs I've missed?

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Istio installs

**Steps to reproduce the bug**
`istioctl install`

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
istio 1.8.2
istio 1.8.1
istio 1.7.5

k8s:
Client Version: v1.18.12
Server Version: v1.18.12

other k8s
Client Version: v1.18.12
Server Version: v1.16.7

**How was Istio installed?**
Presently running `istioctl install`
Lately: `istioctl install --skip-confirmation -f overlay.yaml`
Since 1.5.1: `istioctl install -f overlay.yaml`

**Environment where the bug was observed (cloud vendor, OS, etc)**
AWS, Kops.

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
`istioctl x uninstall --purge` will remove the RBAC configs, so I think its expected that it would no longer be able to read?

**Comment by towens** [comment]
@howardjohn you're the wizard, you tell me. 🧙 As Istio originally installed them, I just assumed the RBAC configs would be created again on the next install.

Sounds like the future holds the following?  `itl x uninstall --filename overlay.yaml`

I don't see a flag that would recreate RBAC here: https://istio.io/latest/docs/reference/commands/istioctl/#istioctl-install

So between the option of recreating the RBAC myself or not using Istio anymore, I pick neither.

How are you recreating them?

**Comment by howardjohn** [comment]
So did you do `istioctl uninstall` then `istioctl install` and its broken? Or you have two istio installs in a single cluster, and uninstalled one andthe others broken?

**Comment by towens** [comment]
Yes. Two separate clusters, two separate Istio installs they are both broken the same way.
Post `istioctl x uninstall --purge`, `istioctl install` sucessfullly installs istio core and then fails at istiod.

**Comment by howardjohn** [comment]
Got it, sorry I misunderstood

**Comment by towens** [comment]
As I'm the one deleting resources without being able to recreate them, it seems like the apology should be on my end 😉

Okay, so nothing is wrong, it's just not obvious what was stopping Istio from deploying. These two clusters will be joined with the the method outlined [here](https://istio.io/latest/docs/setup/install/multicluster/multi-primary_multi-network/) for "Multi-Primary on different networks." The intermediate certs and the remote secret were still present. I deleted both. `istio install` succeeds. ⛵

**Comment by towens** [comment]
Followup: removing the remote secret fixes the issue.
