### ISSUE TITLE
Istio overriding envoy's default access logging configuration

### ISSUE THREAD

**Issue by pantelis-karamolegkos** [istio/istio#30242]
**Bug description**

This is either a documentation deficiency of some weird issue.

According to the [docs](https://istio.io/latest/docs/tasks/observability/logs/access-log/#enable-envoy-s-access-logging), `istio` should be adhering to the [default](https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage?fbclid=IwAR0xaS-EtEniJfbpGWf-GN_o75aLSpyn5FI2Uojp9YPWQD4PjQqs9ObqavQ#default-format-string) access logging format as this is defined in `envoy`. 

According to the same docs again, issues related to access logging, are [defined](https://istio.io/latest/docs/tasks/observability/logs/access-log/#enable-envoy-s-access-logging) in `meshConfig` and if a user wants to change the default access logging format, this can be done in  `meshConfig.accessLogFormat`

Our `meshConfig` section of our `IstioOperator` is the following:

```
meshConfig:
  accessLogEncoding: JSON
  accessLogFile: /dev/stdout
```

i.e. no `accessLogFormat` configuration there.

However, in `StackDriver`, when seeing my `istio-proxy` logs, I see some fields __NOT__ defined in the default [format](https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage?fbclid=IwAR0xaS-EtEniJfbpGWf-GN_o75aLSpyn5FI2Uojp9YPWQD4PjQqs9ObqavQ#default-format-string)., e.g. here is a corresponding `istio-proxy` log entry

```
response_code: "200"
bytes_received: "0"
upstream_cluster: "outbound|80||myscv.default.svc.cluster.local"
downstream_remote_address: "10.17.37.1:57362"
upstream_transport_failure_reason: "-"
user_agent: "Mozilla/5.0 (compatible; Cloudflare-Traffic-Manager/1.0; +https://www.cloudflare.com/traffic-manager/; pool-id: 8474894722kdjfhg49)"
duration: "2"
x_forwarded_for: "10.15.22.1"
route_name: "-"
path: "/health"
requested_server_name: "my.public.url.net"
upstream_host: "10.15.37.29:20000"
downstream_local_address: "10.17.37.16:8443"
protocol: "HTTP/1.1"
request_id: "32455-452d-9a7a-9310-71e098fb490R"
start_time: "2021-01-20T17:27:13.021Z"
authority: "my.public.url.net"
istio_policy_status: "-"
upstream_service_time: "2"
bytes_sent: "2"
upstream_local_address: "10.43.37.16:55496"
method: "GET"
response_flags: "-"
```

I can see for example `istio_policy_status` and `downstream_local_address` (perhaps there are more) which are not part of the default format.

[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

Envoy should be printing only the fields of `envoy`'s default access log format.

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```
▶ istioctl version --remote
1.7.3
▶ helm3 version --short      
v3.4.2+g23dd3af
▶ k version --short 
Client Version: v1.19.0
Server Version: v1.17.14-gke.400
```

**How was Istio installed?**

Direct installation (via `kubectl apply -f`) of `istio-operator`

**Environment where the bug was observed (cloud vendor, OS, etc)**

GKE `1.17+`

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
I think its ambiguous docs:

"You may also want to customize the <format> of the access log by editing accessLogFormat."

This can be interpreted as "customize the format [which is by default matching the default envoy format in the link]" or "customize the format [which has documentation for relevant fields here, but Istio has different defaults]".

The latter is the actual intent

**Comment by pantelis-karamolegkos** [comment]
So the next step is to make the documents describe the actual way `istio-proxy` produces its access logs.

Does anyone have an idea where this takes place?

I grepped the entire `istio` source code but e.g. no `istio_policy_status` there. 

```
~/Workspace/istio  master ✔                                                                                                 2h2m
▶ grep -rniI istio_policy_status .
```

**Comment by SpecialYang** [comment]
> So the next step is to make the documents describe the actual way `istio-proxy` produces its access logs.
> 
> Does anyone have an idea where this takes place?
> 
> I grepped the entire `istio` source code but e.g. no `istio_policy_status` there.
> 
> ```
> ~/Workspace/istio  master ✔                                                                                                 2h2m
> ▶ grep -rniI istio_policy_status .
> ```

Istio has own default accesslog format to record some useful information. The default format will change in different version. The  `istio_policy_status` exists in branch release-1.7.3-patch, please checkout.

**Comment by pantelis-karamolegkos** [comment]
@SpecialYang thanks for pointing this out.

So the problem is now the following: if I want to __just add_ a few fields in `meshConfig.accessLogFormat`, I must 

a) go through the code
b) find the existing fields
c) lay them out in `meshConfig.accessLogFormat`
d) put there my (additional fields)

Am I getting this right?

In any other case I might accidentally overwrite the current log format, since `meshConfig.accessLogFormat` does not operate in `append-to-default` mode, right?
