### ISSUE TITLE
Do we have any Docs in Chinese？

### ISSUE THREAD

**Issue by Xunzhuo** [istio/istio#30252]
**Describe the feature request**

Doc in Chinese

**Describe alternatives you've considered**

Understand istio better

- [x] Docs
- [ ] Installation
- [ ] Networking
- [ ] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure

**Additional context**

**Comment by xichengliudui** [comment]
https://istio.io/latest/zh/

**Comment by Xunzhuo** [comment]
tks
