### ISSUE TITLE
How can I store 7 days metrix in istio?

### ISSUE THREAD

**Issue by salimuddin87** [istio/istio#30264]
Recently, I have deployed istio with grafana and prometheus. Istio store matrix only for 6hr by default. 
I want to increase default hrs to 7 days.

Kindly suggest me, what are the best option to do?

**Comment by howardjohn** [comment]
Istio does not configure Prometheus anymore (https://istio.io/latest/blog/2020/addon-rework/). Please see Prometheus documentation (--storage.tsdb.retention.time=15d is probably what you want). Thanks!
