### ISSUE TITLE
failed to fetch jwks_uri on first attempt does not recover

### ISSUE THREAD

**Issue by domcyrus** [istio/istio#30261]
**Bug description**
We setup istio with requestauthentication resource to validate jwt tokens. The issuer is a URL which causes istiod to try to the OIDC discovery of the well known endpoint to retrieve the JWKS. If an error occurs in the first attempt during the istiod initialization phase it won't recover ever. This is because the failed attempt is stored also for upcoming istiod attempts to resolve the JWKS.

**Logs**
```
2020-12-31T14:44:52.737506Z	warn	model	Failed to get jwks_uri for issuer "https://$domain/oauth2/default": Get "https://$domain/oauth2/default/.well-known/openid-configuration": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2020-12-31T14:44:52.737482Z	error	model	Failed to fetch jwks_uri from "https://$domain/oauth2/default/.well-known/openid-configuration": Get "https://$domain/oauth2/default/.well-known/openid-configuration": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

2020-12-31 16:02:32	0.0.0.0_8080: Issuer 'https://$domain/oauth2/default' in jwt_authn config has invalid local jwks: Jwks RSA [n] or [e] field is missing or has a parse error
2020-12-31T15:02:31.992986Z	error	Failed to fetch jwt public key from "": Get "": unsupported protocol scheme ""
2020-12-31T15:02:31.992972Z	error	model	Failed to fetch public key from "": Get "": unsupported protocol scheme ""
2020-12-31T15:02:31.991866Z	error	Failed to fetch jwt public key from "": Get "": unsupported protocol scheme ""
2020-12-31T15:02:31.991851Z	error	model	Failed to fetch public key from "": Get "": unsupported protocol scheme ""
```

In the istiod code here is where the problem starts:
https://github.com/istio/istio/blob/080374a27dd16646be2649ab377af49183667ac1/pilot/pkg/model/jwks_resolver.go#L261

```go	
       body, err := r.getRemoteContentWithRetry(issuer+openIDDiscoveryCfgURLSuffix, networkFetchRetryCountOnMainFlow)
	if err != nil {
		log.Errorf("Failed to fetch jwks_uri from %q: %v", issuer+openIDDiscoveryCfgURLSuffix, err)
		return "", err
	}
```

Here I think it should either retry or bail out (panic) because it will store the empty string on error and will result in the errors you can see above.
https://github.com/istio/istio/blob/080374a27dd16646be2649ab377af49183667ac1/pilot/pkg/model/jwks_resolver.go#L214

[ ] Docs
[x] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Steps to reproduce the bug**
Reproduce it with having a first attempt failure as described above.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```
$ kubectl version --short
Client Version: v1.18.6
Server Version: v1.18.9-eks-d1db3c
$ istioctl version
client version: 1.8.1
control plane version: 1.8.1
data plane version: 1.8.1 (6 proxies)
```

**How was Istio installed?**
istioctl

**Environment where the bug was observed (cloud vendor, OS, etc)**
AWS eks but it's not environment specific.

**Comment by howardjohn** [comment]
cc @yangminzhu

**Comment by domcyrus** [comment]
I looked into how to fix this bug. That said if you wish to see a PR rather than a lot of text please let me know. There is only the question of what behavior would be expected.

Should the JwksResolver retry a couple of times and if the error persists should pilot exit and fail with an error? 
Or should the JwksResolver retry to resolve the URI forever and just continue as it does today? Obviously in this case it should continue retrying to resolve the jwks URI and not operate on an empty string.

There is currently already a retry mechanism present but is set to 0 retries so that one single failing attempt results in the unrecoverable problem of not having a URI set and hence also never recovers. An easy fix is to just allow a couple of retries but that could still result in a broken setup if those retries at fail on init.

Also I've seen that there are a few things related to the misbehavior e.g. there is a cache:
```golang
// JwksResolver is resolver for jwksURI and jwt public key.
type JwksResolver struct {
	// cache for jwksURI.
	JwksURICache cache.ExpiringCache
```
Which is only populated once due to some changes done in PR #24719. I think that the cache should go away if it is only used once.

**Comment by yangminzhu** [comment]
> Should the JwksResolver retry a couple of times and if the error persists should pilot exit and fail with an error?
Or should the JwksResolver retry to resolve the URI forever and just continue as it does today? Obviously in this case it should continue retrying to resolve the jwks URI and not operate on an empty string.

I think we could merge the `ResolveJwksURI` to the `refresh()` function, there will be some refactor but the end result is that 1) we don't need to resolve OIDC discovery in `addRequestAuthentication()`, and 2) it can reuse the periodic refresh logic already implemented in `refresh()`;

The `refresh()` currently has a fixed refresh interval of 20m (`JwtPubKeyRefreshInterval`, this is also being updated by @xulingqing to make it configurable), one more optimization we can do is to retry more frequently when istiod failed to fetch the key, which could be configured by a different flag, e.g. `JwtPubKeyRefreshIntervalOnFailure`.

@domcyrus I think this is very useful fix and thank you for creating the issue with the detailed analysis, would you like to send a PR for the fix? I will assign to you if you think you could take it. Thanks.

**Comment by domcyrus** [comment]
@yangminzhu Thanks for your suggestion which sounds very good to me. I'll open a PR with the change you've outlined.

**Comment by domcyrus** [comment]
Created #30407
