### ISSUE TITLE
Message based traffic routing 

### ISSUE THREAD

**Issue by rvdhorst** [istio/istio#30267]
**Describe the feature request**

Can we have support for message based transport between microservices? The same, or similar, question was asked in issue 
Istio Service Mesh Extended for Event Driven Messaging #24489

**Describe alternatives you've considered**
HTTP based transport is considered difficult scale and difficult to balance across instances of a microservice. Message based communication allows for competing consumer pattern which provides a more natural of load balancing. Also, a pub/sub pattern is possible allowing for additional event handlers for the same events/messaging providing all sorts of possibilities for testing, auditing, and more. 

[ ] Docs
[ ] Installation
[x] Networking
[x] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
What protocols do you want to use? And what do you want to route based on? And does Envoy support that protocol and those routing configurations?

Are probably the important questions here.

https://github.com/aeraki-framework/aeraki may be of interest

**Comment by rvdhorst** [comment]
Preferable AMQP for brokers such as ActiveMQ or RabbitMQ and Kafka protocol for Kafka. I understand that with Envoy one can use the TCP protocol to connect to brokers. Much of the functionality offered by Envoy should be available e.g. rate limiting and timeouts according to a post of stackoverflow. No first hand experience with the matter myself though.

I have added some diagrams for clarification.

![istio messaging load balancing](https://user-images.githubusercontent.com/760563/105408289-0f9b8200-5c2f-11eb-95f6-1fc5ad2e1207.png)
![istio messaging routing external clustered brokers](https://user-images.githubusercontent.com/760563/105408292-10341880-5c2f-11eb-8de3-cd6d16cd1421.png)
![istio messaging routing on-board clustered brokers](https://user-images.githubusercontent.com/760563/105408295-10ccaf00-5c2f-11eb-90fa-2a431e445f8d.png)
![istio messaging routing on-board nonclustered brokers](https://user-images.githubusercontent.com/760563/105408296-10ccaf00-5c2f-11eb-840d-6f5419818433.png)
