### ISSUE TITLE
Improve operator experience with Mixer logs

### ISSUE THREAD

**Issue by ozevren** [istio/istio#3027]
We need to ensure that our logs are meaningful and help the operators trace and identify issues easily.

A couple of tactics for this:

- Identify logging points in code, where the issue is fixable by the operator and call it out as such, with potential fixes, within the log entry.
- Pervasively use uniquely identifiable error codes (a-la compiler errors such as this: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0234) This ensures that the operator can do a single Google search lookup and find more detailed documentation easily.

**Comment by douglas-reid** [comment]
@ozevren related, not specifically applicable to your error-oriented bullets: there was a request on istio-users for operatores to be able to easily discover the rule name for all dispatches. this seems like something that could be rolled into runtime2 and would improve operator experience.

**Comment by kyessenov** [comment]
Not stale. Still useful to track errors to source code. Extra useful for caching related issues.

**Comment by fpesce** [comment]
@ozevren @kyessenov : Would you mind assigning someone, or making that issue an Epic with clearly identified subtasks (e.g. 1: Do we have a central error code place, that we could use as a Log interface - if not, building that is a task/feature, 2_and_+ : identify the first places to implement this type of logging).
It looks to me that this one is going to be stale for ever if it's not being more precise; if this is really a P0 and subsequently a release showstopper, I think we should be able to understand how to solve it.

**Comment by kyessenov** [comment]
I'm not sure how much we want to invest here, since Mixer code is going away. I think it is more important to incorporate this into design of Mixer v2.

**Comment by douglas-reid** [comment]
I think we should close this issue (overcome by events). Mixer development is basically frozen (bug fix only).
