### ISSUE TITLE
status: ledger crash in CI

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#30292]
https://storage.googleapis.com/istio-prow/logs/integ-security-k8s-tests_istio_postsubmit/1352408471101771776/artifacts/security-f8c21f5b05e944e893d8b0/_suite_context/istio-state-557506131/cluster-0/istiod-6b5db965cc-s2krb_discovery.previous.log

https://prow.istio.io/view/gs/istio-prow/logs/integ-security-k8s-tests_istio_postsubmit/1352408471101771776

**Comment by stevenctl** [comment]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30288/integ-security-multicluster-tests_istio/1352676133304274944

**Comment by howardjohn** [comment]
I sent a revert
