### ISSUE TITLE
OIDC JWT authenticator

### ISSUE THREAD

**Issue by lei-tang** [istio/istio#30295]
**Describe the feature request**
- Implement an OIDC JWT authenticator that supports both JWKS-URI and OIDC discovery. The OIDC JWT authenticator can be configured through the JWT_RULE env variable and when configured, it will be used as an istiod authenticator.
- Add tests for the OIDC JWT authenticator.

**Describe alternatives you've considered**
No alternative; this feature is needed.

[ ] Docs
[ ] Installation
[ X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by incfly** [comment]
@lei-tang could you assign this to yourself if you plan to implement this? Thanks.

**Comment by lei-tang** [comment]
Implemented in https://github.com/istio/istio/pull/30294.
