### ISSUE TITLE
some firefox browser shows error  of SSL_ERROR_RX_RECORD_TOO_LONG when access https site

### ISSUE THREAD

**Issue by hillbun** [istio/istio#30304]
some firefox browser shows error  of SSL_ERROR_RX_RECORD_TOO_LONG when access https site, but chrome is correct.

**Comment by howardjohn** [comment]
Please fill out the issue template, this does not have enough information for us to debug. Thanks.

**Comment by hillbun** [comment]
@howardjohn 

https://github.com/istio/istio/issues/30356
