### ISSUE TITLE
Possible DNS redirect loop

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#30309]
This is theoretical, need to test

/etc/resolv.conf points to some localhost DNS proxy (dnsmasq?), say 127.0.0.11.
The 127.0.0.11 forwards to some upstream DNS server, say cloud-dns

DNS request lifecycle:
application ---> agent (intercepted) ---> 127.0.0.11 (forward upstream) ---> forward upstream to cloud-dns, but since its not UID 1337 its iptables captured, redirected back to agent --> repeat

**Comment by hzxuzhonghu** [comment]
Then only intercept dns request which dst ip equals the nameserver.

**Comment by howardjohn** [comment]
I confirmed this happens with systemd-resolvd on GCE ubuntu

**Comment by szibis** [comment]
Same on AWS EC2 with Ubuntu 18.04 based on systemd-resolvd.

**Comment by howardjohn** [comment]
> Then only intercept dns request which dst ip equals the nameserver.

Thought about it some more, I think this is our best option. I will implement it.

**Comment by kyadav-cgi** [comment]
I am still see this error in istio 1.23.5
Anyone aware how to resolve this..?
