### ISSUE TITLE
Allow deployments to control the CPU usage of Envoy

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#3031]
We can add a option to pilot to configure --concurrency in Envoy:
https://www.envoyproxy.io/docs/envoy/latest/operations/cli#cmdoption-concurrency

**Comment by costinm** [comment]
watcher.go already has an 'extraArgs' that is added to envoy CLI - unfortunately it's not yet reflected in a flag or env variable, should be a pretty small fix. 

The second part is how to configure it with kube-inject - I think the new template-based injector and webhook are the cleanest option (or manually changing post-injection)

**Comment by sakshigoel12** [comment]
@andraxylia I think this is fixed. Marking closed, please reopen if you think there is more work here.
