### ISSUE TITLE
Auto mTLS and {exclude,include}InboundPorts do not behave well together

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#30311]
When we are disabling iptables for some ports, auto mtls is not aware. As a result, requests will be automatically upgraded to use mTLS which will not work.

Currently, pilot is not aware of these annotations and they impact only the iptables setup.

**Comment by incfly** [comment]
do you think we can do much here? annotation is per workload level. auto mTLS is configuration on cluster, which is service level. And the port may or may not be part of the service port mappings. which makes it even harder to determine where we can tweak the outbound cluster's config?

**Comment by howardjohn** [comment]
Not really, its a tricky problem. These exclude options are not super common though so it may not be a super high priorioty. I agree a comment on the docs for these options could go a long way

**Comment by incfly** [comment]
/assign @incfly to update the documentaiton. 

(I need to re-acquire my istio org membership...)
