### ISSUE TITLE
workloadgroups CRDs missing metadata:labels

### ISSUE THREAD

**Issue by tmshort** [istio/istio#30312]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

The new workloadgroups CRD added in 1.8 does not include any label metadata as the other CRDs contain.

The following labels are present in other CRDs, but are missing from workloadgroups:
```
metadata:
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app: istio-pilot
    chart: istio
    heritage: Tiller
    release: istio
```
This makes it harder to query the istio CRDs.

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[X] Upgrade

**Expected behavior**

Labels to exist for all CRDs

**Steps to reproduce the bug**
This lists all istio CRDs except for the workloadgroups:
```
kubectl get crds -o jsonpath='{.items[?(@.metadata.labels.release=="istio")].metadata.name}' --ignore-not-found=true
```
This shows that the CRD does not contain the labels the other CRDs have:
```
kubectl get crd workloadgroups.networking.istio.io -o yaml
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

1.8

**How was Istio installed?**

Doesn't matter.

**Environment where the bug was observed (cloud vendor, OS, etc)**

kubernetes

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
cc @jasonwzm

**Comment by jasonwzm** [comment]
@adiprerepa Sorry, I did not realize you self assigned. I am going to assign this to myself to wait for PR approval.

**Comment by adiprerepa** [comment]
Thanks 👍
