### ISSUE TITLE
Streamed response causes added latency in envoy sidecar. 

### ISSUE THREAD

**Issue by Ziyi-OBM** [istio/istio#30333]
We found that in certain applications, using streamed response caused an added latency of ~45 ms, where the latency observed when using buffered response was ~1 ms. 

We confirmed by querying Envoy logs that the latency was added by the sidecar. Our hypothesis was that streaming and the size of the responses were causing additional events in the sidecar, adding additional latency when flushing the response. After some investigation, we found that the side car is buffering content streamed by the application, causing a fixed cost of latency related to the size of payload. This buffer is controlled by envoy config (https://www.envoyproxy.io/docs/envoy/latest/faq/configuration/flow_control)

We first encountered this issue in Istio 1.4.5. We have recently upgraded to Istio 1.8.0 (with k8s version v1.18.9) and this sidecar added latency issue due to streaming was still observed.

**Comment by Phil1602** [comment]
We are experiencing probably the same issue in Istio 1.25/1.26 when streaming HTTP(S) responses. However, it seems that our case is related to OUTBOUND requests from Sidecar to mesh external endpoints.

Our target service is `MESH_EXTERNAL` and controlled via `ServiceEntry` dedicated to `HTTPS` protocol.

Our latency increases by ~50ms (without Sidecar or excluded Port 70ms, with Sidecar 120ms).

@Ziyi-OBM Were you able to workaround this issue or configure the buffer more properly?
