### ISSUE TITLE
 custom http header Host give “404 NR”

### ISSUE THREAD

**Issue by sunnoy** [istio/istio#30347]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
make http request ：
```bash
curl -v --header 'Host: www.example.com' www.baidu.com
```
envoy give 404 NR

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```bash

istioctl version --remote
client version: 1.8.0
control plane version: 1.8.2
data plane version: 1.8.2 (22 proxies)

kubectl version --short
Client Version: v1.18.6
Server Version: v1.16.2
```

**How was Istio installed?**

crd

**Comment by howardjohn** [comment]
Routing is based on host header. So if you put something in the Host header that you haven't defined a route for by virtual service this is expected

**Comment by howardjohn** [comment]
Closing as working as intended. Thanks!
