### ISSUE TITLE
Polluted label values in the istio_requests_total time series

### ISSUE THREAD

**Issue by softcane** [istio/istio#30359]
We recently observed an abnormality with `istio_requests_total` time series (only from the **istio ingress proxy)** where `destination_app` and `destination_canonical_service` looks off and polluted. However, the aggregated number using `destination_service` is correct.

In the attached example, destination_app=cms|playback-reporting should not exist.
![Prometheus-Time-Series-Collection-and-Processing-Server (2)](https://user-images.githubusercontent.com/1730359/105699189-414e6a80-5f07-11eb-8f71-1a2ce142d8dd.png)

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[*] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
istio: 1.6.0

**How was Istio installed?**
istioctl

**Comment by bianpengyuan** [comment]
By `destination_app=cms|playback-reporting should not exist`, do you mean ingress never talks to those app and thus should not show up at ingress app label? Does the destination_workload label look right on those time series? Does those time series have any other traits, like are they all 4xx or 5xx?

**Comment by bianpengyuan** [comment]
@kyessenov Just in case I forgot to ping you when you are back, this is probably due to accessing a corrupted CEL list.

**Comment by gabrielguernikatdiscovery** [comment]
@softcane Do we have more input to add to this issue?
