### ISSUE TITLE
Cannot create pod when playing with bookinfo example.

### ISSUE THREAD

**Issue by hazelnutsgz** [istio/istio#30350]
When deploying the bookinfo demo on my self-managed k8s cluster(2 nodes), the pod cannot be created, suggested "No resources found in default namespace." after run "kubectl get pods". 

```kubectl get events``` show that:
```
2m6s        Warning   FailedCreate        replicaset/details-v1-79c697d759       Error creating: Internal error occurred: failed calling webhook "sidecar-injector.istio.io": Post "https://istiod.istio-system.svc:443/inject?timeout=30s": Origin DNS Error
```

OS: Debian Buster
Linux kernel: 5.4.56
istio: 1.8.2
CNI : cilium 1.9

Thanks.

**Comment by hzxuzhonghu** [comment]
Obviously, it is the dns error.

**Comment by hazelnutsgz** [comment]
The tricky thing here is that reinstallation works.
