### ISSUE TITLE
[Feature request] Support outlier detection by success / failure rate

### ISSUE THREAD

**Issue by gainings** [istio/istio#30358]
**Describe the feature request**

- Need outlier detection based on success/failure rate.

Currently outlier detection just support fixed value.
Its not change dynamically when the pod scales.
I want to dynamically change the threshold with a success / failure rate like that supported by Envoy

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by Lynskylate** [comment]
This demand looks great，i also need this feature.
