### ISSUE TITLE
Show not corrected metrics after add sidecar to Prometheus operator

### ISSUE THREAD

**Issue by gproxyz** [istio/istio#30360]
I have istio standard profile 1.8.1 on-premise K8S cluster.
I used Prometheus operator, and install it from the standard helm cart (kube-prometheus-stack).
After adding a sidecar to the monitoring namespace Kiali starting to show the incorrect graph.
Something like this for all namespace: 
![1_1](https://user-images.githubusercontent.com/49784110/105699975-3bfa1b80-5f19-11eb-9744-22f2c05eb317.png)
Grafana shows the same thing to (Mesh Dashboard). 
![1_2](https://user-images.githubusercontent.com/49784110/105700001-461c1a00-5f19-11eb-8726-012c28cf2833.png)
Before added sidecars in the monitoring namespace, all work fine. Applications graphs show correctly. 

If disable auto-injection and redeploy Prometheus pods, all works fine. 
![2_1](https://user-images.githubusercontent.com/49784110/105700028-516f4580-5f19-11eb-849c-193415519925.png)
![2_2](https://user-images.githubusercontent.com/49784110/105700046-5633f980-5f19-11eb-91bd-ac7c09bfd89a.png)
All sidecar synchronizes, and I do not see any errors.

**Steps to reproduce the bug**
Install https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack in the separate namespace - Monitoring. Add Envoy auto-injection.

**Affected product area**
[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**What stack used**
Prometheus operator (try use different version, now install latest) https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack 
Istio 1.8.1 and 1.8.2 try use demo and standard profile.
Samples Prometheus object (PodMonitor, ServiceMonitor) from istio downloaded folder samples/addons/extras/prometheus-operator.yaml

**Version**
```
bin/istioctl version --remote
client version: 1.8.2
control plane version: 1.8.2
data plane version: 1.8.2 (16 proxies), 1.8.1 (1 proxies)
```

```
kubectl version --short
Client Version: v1.19.4
Server Version: v1.18.2
```

```
helm version --short
v3.4.1+gc4e7485
```

**How was Istio installed?**
Used istioctl profile with custom values.

**Environment where the bug was observed (cloud vendor, OS, etc)**
on-premises kubernetes installation by kube-spray.

**Comment by bianpengyuan** [comment]
Does prometheus pod scraping starts to fail after adding the sidecar? It should still work even after adding sidecar, so does the kiali graph.

**Comment by Minh-Ng** [comment]
I found Istio intercepts all outbound to 15090 by default. Adding annotation to your prometheus workload or global configuration to ignore 15090 outbound on istio-init can fix this. More details https://github.com/istio/istio/issues/31301

```
annotations:
  traffic.sidecar.istio.io/excludeOutboundPorts: "15090"
```

**Comment by bianpengyuan** [comment]
@Minh-Ng thanks for the info! @gproxyz did your istio installation also disable metrics merging?
