### ISSUE TITLE
flake: Egress rule tests in Prow fail with Auth enabled (but not CircleCI)

### ISSUE THREAD

**Issue by rshriram** [istio/istio#3037]
I spotted this flake twice since yesterday. https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/3016/istio-pilot-e2e/2125/

Egress rules fail with auth mode. I am not sure if its caused by infrastructure losing connectivity or if its some flake in the way we setup egress rules tests. Note that this is just the *symptom*. The root cause could be totally unrelated to the egress rules test, because the same test passes in CircleCI!

```
I0131 23:09:35.395] =================== Failed infrastructure tests! =====================
I0131 23:09:35.396] 75 errors occurred:
I0131 23:09:35.396] 
I0131 23:09:35.396] * (auth infra) http-reachability run 0 failed all 90 attempts for HTTP request from a to a:8080
I0131 23:09:35.396] * (auth infra) http2-reachability run 0 failed all 90 attempts for GRPC request from b to b.istio-test-app-ppxfr:7070
I0131 23:09:35.396] * (auth infra) tcp-reachability run 0 failed all 90 attempts for TCP connection from t to b.istio-test-app-ppxfr:9090
I0131 23:09:35.397] * (auth infra) ingress run 0 failed all 90 attempts for Ingress request to {dst:a url:http://istio-ingress.istio-test-8g22v/.well_known/foo host:}
I0131 23:09:35.397] * (auth infra) egress-rules run 0 ensure traffic to httbin.org is prohibited when setting *.httbin.org attempt 0 failed Request from a to http://httpbin.org/headers at attempt 0: http://httpbin.org/headers is reachable from a (should be unreachable)
I0131 23:09:35.397] * (auth infra) egress-rules run 0 ensure traffic to httbin.org is prohibited when setting *.httbin.org attempt 1 failed Request from a to http://httpbin.org/headers at attempt 0: http://httpbin.org/headers is reachable from a (should be unreachable)
I0131 23:09:35.398] * (auth infra) egress-rules run 0 ensure traffic to httbin.org is prohibited when setting *.httbin.org attempt 2 failed Request from a to http://httpbin.org/headers at attempt 0: http://httpbin.org/headers is reachable from a (should be unreachable)
I0131 23:09:35.398] * (auth infra) egress-rules run 0 prohibit http external traffic to cnn.com by a tcp egress rule attempt 0 failed Request from a to https://cnn.com at attempt 0: https://cnn.com is reachable from a (should be unreachable)
I0131 23:09:35.398] * (auth infra) egress-rules run 0 prohibit http external traffic to cnn.com by a tcp egress rule attempt 1 failed Request from b to https://cnn.com at attempt 0: https://cnn.com is reachable from b (should be unreachable)
I0131 23:09:35.399] * (auth infra) egress-rules run 0 prohibit http external traffic to cnn.com by a tcp egress rule attempt 2 failed Request from b to https://cnn.com at attempt 0: https://cnn.com is reachable from b (should be unreachable)
```

**Comment by vadimeisenbergibm** [comment]
Note that HTTP, HTTP2 and TCP reachability tests inside the mesh - from `a` to `a`, `b` to `b`, `t` to `b` failed. Note that all the egress tests use external sites like httpbin.org, google.com and wikipedia.org. They have higher latency than in-mesh tests. So whenever any timeouts/delays issues appear, the external tests will fail first. In my opinion, egress tests should become suspect only if all in-mesh tests pass.

**Comment by mandarjog** [comment]
I suggest we target a local endpoint thru the external service mechanism so that we are not sensitive to latencies.

Curl -H “Host: google.com” http://mylocalsvc.clustervip/ should test our current impl.

**Comment by rshriram** [comment]
It won’t reliably test since the endpoint will be under istio control. We have to be vigilant to model all properties of external endpoints. As vadim says, this is a symptom of something larger. These tests pass in circleci for every PR multiple times.

**Comment by ldemailly** [comment]
We could add a non istio injected service?
This being said it is useful to understand the failure

**Comment by ldemailly** [comment]
```
I0213 12:37:03.425] * (auth infra) zipkin run 0 failed all 90 attempts for Ensure traces are picked up by Zipkin
I0213 12:37:03.425] * (auth infra) kubernetes-external-name-services run 0 failed all 90 attempts for HTTP connection from b to externalbin
```
still happening @andraxylia can you assign someone ?
https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/3302/istio-pilot-e2e/2891/

**Comment by vadimeisenbergibm** [comment]
Egress rules e2e disabled by https://github.com/istio/istio/pull/4092 so the issue is not relevant.
