### ISSUE TITLE
Multi-cluster Multi-network fails if no default network provided

### ISSUE THREAD

**Issue by nmittler** [istio/istio#30376]
This was discovered while investigating https://github.com/istio/istio/issues/29388.

The multi-cluster multi-network docs test was missing the lines to configure a default network for the namespace. Without this set, the test fails. This should not be needed as that default network should only be used to configure uninjected pods. 

The pods appear to have `ISTIO_META_NETWORK` set properly, but are missing the network labels. There is likely a bug introduced since the last 1.8.x release that is affecting the injection.

[ ] Docs
[x] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by stevenctl** [comment]
Looks like the original logic was moved in #28800

https://github.com/istio/istio/pull/28800/files#diff-e57c2ab4e6af0f24e7285fad8ec9fe8b688fad1350b6d6c405f75a067d65e0dcL545

Trying to find where it was moved.. I don't see any references to the network label in the inject package or in the templates. I think it was accidentally removed.

**Comment by nmittler** [comment]
:facepalm:
