### ISSUE TITLE
`istioctl x tag set` is not working

### ISSUE THREAD

**Issue by su225** [istio/istio#30392]
**Bug description**
```
[istio]$ istioctl version
no running Istio pods in "istio-system"
1.10-dev
[istio]$ istioctl install --set profile=minimal -y
✔ Istio core installed                                                                                                                                                                        
✔ Istiod installed                                                                                                                                                                            
✔ Installation complete                                                                                                                                                                       [istio]$ istioctl install --set profile=minimal --set revision=canary -y
✔ Istio core installed                                                                                                                                                                        
✔ Istiod installed                                                                                                                                                                            
✔ Installation complete                                                                                                                                                                       [istio]$ kubectl get mutatingwebhookconfigurations
NAME                            WEBHOOKS   AGE
istio-sidecar-injector          2          63s
istio-sidecar-injector-canary   2          20s
[istio]$ istioctl x tag set prod --revision default
Error: failed to create tag webhook config: could not find sidecar-injector webhook in canonical webhook
```
The below command should have created a tag because there is no existing tag called `prod` and `default` is a valid revision
```
[istio]$ istioctl x tag set prod --revision default
Error: failed to create tag webhook config: could not find sidecar-injector webhook in canonical webhook
```
On examining sidecar injectors I found that the code looks for `sidecar-injector.istio.io`, but there is no injector with that exact name. Instead, there is `*.sidecar-injector.istio.io`. (Actually, there are 2)
```
$ kubectl get mutatingwebhookconfigurations -o istio-sidecar-injector -o jsonpath='{.webhooks[*].name}'
namespace.sidecar-injector.istio.io object.sidecar-injector.istio.io
```
At first glance, the fix looks pretty simple. In `istioctl/cmd/tag.go`. In fact, trying this hack worked locally. However, I'm not sure if this is the right solution.
```diff
for _, w := range wh.Webhooks {
-		if w.Name == istioInjectionWebhookName {
+               if strings.HasSuffix(w.Name, istioInjectionWebhookName) {
			found = true
			if w.ClientConfig.URL != nil {
```

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Environment where the bug was observed (cloud vendor, OS, etc)** - 
Kind cluster running on Linux-amd64 (Kubernetes 1.19)

**Comment by su225** [comment]
cc: @Monkeyanator

**Comment by Monkeyanator** [comment]
Ah this must be a bad interaction with #30013 which changed the webhook names and behaviors. I'll take a deeper look now but I think we'll also have to change `revision-tags.yaml` to align with the new injection behavior (in addition to the change you pointed out with the `istioInjectionWebhookName`)

**Comment by Monkeyanator** [comment]
Maybe we need to add an integration test for revision tags, would have caught this issue.

**Comment by su225** [comment]
> Maybe we need to add an integration test for revision tags, would have caught this issue.

Yes please. I was working https://github.com/istio/istio/pull/29713 and thought of adding tags to my setup for some additional checks and ended up catching this.
