### ISSUE TITLE
Confusing "istioctl install" message when creating control plane canary

### ISSUE THREAD

**Issue by esnible** [istio/istio#30399]
I had master installed as the `default` control plane.

```
istioctl install --revision canary
! Istio is being upgraded from 1.10.0 -> 1.9.0.
! Before upgrading, you may wish to use 'istioctl analyze' to check for IST0002 deprecation warnings.
```

Problems.

- Istio isn't being upgraded!  A control plane canary is being started, independent of the `default` plane.
- Going from 1.10.0 (master) to 1.9.0 is a downgrade, not an upgrade.
- If we are downgrading, the IST0002 deprecation warnings won't make sense.
- If we were upgrading, we should `analyze` for both IST0002 and IST0135 the new deprecated annotation warning.

**Comment by shamsher31** [comment]
> Istio isn't being upgraded! A control plane canary is being started, independent of the default plane.

But it upgrades gateways so I think the upgrade message is valid.

> Going from 1.10.0 (master) to 1.9.0 is a downgrade, not an upgrade.

Agree, updated message to `downgrade` if the user is installing a lower version of Istio.

> If we are downgrading, the IST0002 deprecation warnings won't make sense.

Removed in the PR.

> If we were upgrading, we should analyze for both IST0002 and IST0135 the new deprecated annotation warning.

Added `IST0135`.
