### ISSUE TITLE
Release tgz/zip should include LICENSE and *.md

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#304]
It's missing at the moment

**Comment by ldemailly** [comment]
LICENSE and samples/*.md is done but we should probably put istio/*.md at the top too

**Comment by sebastienvas** [comment]
I think it is fine the way it is.

**Comment by ldemailly** [comment]
why not add top level *.md (or at least README.md and possibly CONTRIBUTING.md and skip reviewing which makes less sense in a binary release)
