### ISSUE TITLE
Minikube instructions to access Bookinfo may have changed?

### ISSUE THREAD

**Issue by ericvn** [istio/istio#30406]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

I’m not sure if Environments owns the Getting Started pages, (just going by owner of the doc page) but seeing an issue when using Minikube tab on that page. The page has instructions for getting the INGRESS_HOST and PORT and then use `minikube tunnel` to access the productpage. On my Mac, this is not working anymore. Not sure if it’s related to MacOS, minikube version, or something else. If it start `minikube tunnel`  the ingress gets an external ip (127.0.0.1) and I can use that and port 80 to access Bookinfo.

I think we would also need to update https://preliminary.istio.io/latest/docs/tasks/traffic-management/ingress/ingress-control/#determining-the-ingress-ip-and-ports

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

Working through the `Getting Started` should work.

**Steps to reproduce the bug**

Deploy minikube and then work through the `Getting Started`. When I get through the step about accessing the application externally, it fails.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```
istioctl version 

client version: 1.9.0-beta.1
control plane version: 1.9.0-beta.1
data plane version: 1.9.0-beta.1 (8 proxies)
```

**How was Istio installed?**

```
istioctl install --set profile=demo -y
```

**Environment where the bug was observed (cloud vendor, OS, etc)**

minikube

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by ericvn** [comment]
I made this a release blocker as the page no longer works (at least on my MacOS system).

**Comment by howardjohn** [comment]
I don't think anyone without a mac can solve this.

**Comment by ostromart** [comment]
From the environments WG weekly:
- if this can be made to work on a mac but not linux, we can refer linux users to kind
- alternative is to move this page out to wiki, support best effort
- another point to consider is if many users are landing on this page (and they probably are since it's getting started) we should probably refactor it to use kind instead, which is much better tested

**Comment by ericvn** [comment]
As noted in the WG meeting, it seems that we might want change from using minikube to using kind as that is what we use for testing. I know there is a problem with accessing things within kind on a Mac as well.

I (and @brian-avery) have done some more investigation using several MacOS versions and several different minikube vm drivers. The VirtualBox driver worked for me on Big Sur, the Hyperkit driver has an issue at start (`This VM is having trouble accessing https://k8s.gcr.io`), and the docker driver works if you use `mk tunnel` and get the ingress ip/port as if using an external load balancer (node ports as used on the page does not). Brian was successful using the Hyperkit drive on Catalina.

I'm not sure how to best document this, if at all. Maybe, we expect that the minikube user knows enough about the minikube install and drivers to know.

**Comment by ericvn** [comment]
As the issue I was having has been rectified by switching the minikube vm driver and the instructions on the page are now working, I'll close this issue. The step to run `minikube tunnel` is not needed on the page as the page uses node ports, but the extra paragraph doesn't cause anything to fail.

It may make sense to create an issue for istio.io to revisit the page and determine if minikube is the correct platform and whether using node ports with minikube is correct or if it should be changed to use minikube tunnel and external load balancers.
