### ISSUE TITLE
Extra istioctl analyze messages [IST-0136] desired? 

### ISSUE THREAD

**Issue by ericvn** [istio/istio#30405]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

Working through the `Getting Started` and it has one run `istioctl analyze` after installing `Bookinfo`. I'm seeing a bunch of new messages after moving to 1.9.0-beta.1.

```
istioctl analyze 

Info [IST0136] (Pod details-v1-79f774bdb9-zhc7p.default) Annotation "sidecar.istio.io/status" is part of an alpha-phase feature and may be incompletely supported.
Info [IST0136] (Pod productpage-v1-6b746f74dc-wg898.default) Annotation "sidecar.istio.io/status" is part of an alpha-phase feature and may be incompletely supported.
Info [IST0136] (Pod ratings-v1-b6994bb9-zzr5m.default) Annotation "sidecar.istio.io/status" is part of an alpha-phase feature and may be incompletely supported.
Info [IST0136] (Pod reviews-v1-545db77b95-zflh8.default) Annotation "sidecar.istio.io/status" is part of an alpha-phase feature and may be incompletely supported.
Info [IST0136] (Pod reviews-v2-7bf8c9648f-cbx5t.default) Annotation "sidecar.istio.io/status" is part of an alpha-phase feature and may be incompletely supported.
Info [IST0136] (Pod reviews-v3-84779c7bbc-wrpn5.default) Annotation "sidecar.istio.io/status" is part of an alpha-phase feature and may be incompletely supported.
```

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

Do we want to see these new messages? We should update the docs to show them if so.

**Steps to reproduce the bug**

Work through getting started simply installing Bookinfo and then running `istioctl analyze`

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```
 istioctl version 
client version: 1.9.0-beta.1
control plane version: 1.9.0-beta.1
data plane version: 1.9.0-beta.1 (8 proxies)
```

**How was Istio installed?**

```
istioctl install --set profile=demo -y
```

**Environment where the bug was observed (cloud vendor, OS, etc)**

IKS

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by esnible** [comment]
I was very nervous about merging this PR because of the huge number of scary **Info** warnings it surfaces.

There is still time to back it out.  I suspect it will cause trouble, hiding the legit messages in the noise.  However, we wanted feedback from users on the value of this analyzer.

**Comment by howardjohn** [comment]
This is definitely wrong. The annotation is addded to every single istio pod injected.

**Comment by esnible** [comment]
@howardjohn I am happy to disable the **alpha** checks, keeping the deprecation checks.

The PR was https://github.com/istio/istio/pull/30083 .  It merged too late to get the feedback we wanted from developers.  I believe the hope was that having an annoying warning wasn't just for the users but to get the devs to promote their stuff to beta.

**Comment by ericvn** [comment]
Changing to release blocker as the istio.io test automation now fails on this page (when moving to 1.9-beta.1)

**Comment by howardjohn** [comment]
Having the checks for annotations in generally is _probably_ too verbose. But having it for `sidecar.istio.io/status` is a bug - there is no scenario a user cares about this, we are injecting it ourselves.

**Comment by esnible** [comment]
I have introduced code to remove the alpha annotations.

We should re-introduce the -0136 after we have done https://github.com/istio/istio/issues/28511 .  We should also create an ALLOWLIST of alpha features that we attach ourselves and don't complain about.
