### ISSUE TITLE
TestRevisionCommand test flake

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#30401]
Brand new test in https://github.com/istio/istio/pull/29713

**Comment by su225** [comment]
@howardjohn - May I get the logs for the run?

**Comment by howardjohn** [comment]
sorry, forgot to paste them:
https://prow.istio.io/view/gs/istio-prow/logs/integ-k8s-115_istio_postsubmit/1354095082399076352

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gs/istio-prow/logs/integ-k8s-115_istio_postsubmit/1354111331191492608
