### ISSUE TITLE
Consider periodic istiod restart - max lifetime

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#30448]
Istiod (pilot) has had hard to replicate and hard to debug issues related to missing events and getting into a bad state.
One way to deal with it is to create a watch-dog-timer that kills the process. However a missing event may still continue forward progress, so the watch-dog may not catch it.

1. Institute a restart policy that limits the maximum lifetime of a pod.
2. Additionally still have a WDT that will resolve the issues of lack of forward progress quicker.
3. In all this, potentially save state if it would be usedful.
4. Ensure that restarting Isiod's does not cause additional churn for proxies (like listener drains) other than simply re-establishing connections.

**Comment by hzxuzhonghu** [comment]
I donot think we should restart to hide the bugs if there are any.

**Comment by mandarjog** [comment]
I understand the sentiment behind not hiding bugs, however when these bugs hit they can cause production outage, and they are very difficult to reproduce. A simple restart fixes the problem, what do others think ? @costinm @howardjohn @ramaraochavali ?

**Comment by ramaraochavali** [comment]
While I agree that hiding bugs via restart is not good, I think there is no harm in trying restart option.
