### ISSUE TITLE
Confusing 'istioctl install' message

### ISSUE THREAD

**Issue by esnible** [istio/istio#30442]
To reproduce,

`istioctl install --set values.global.proxy.holdApplicationUntilProxyStarts=true`

The tool outputs 

```
! values.global.proxy.holdApplicationUntilProxyStarts is deprecated; use ProxyConfig holdApplicationUntilProxyStarts instead
```

I couldn't figure out what that meant, @howardjohn suggested "use `--set meshConfig.defaultConfig.holdApplicationUntilProxyStarts`.  The error should probably say that."

**Comment by morvencao** [comment]
Yes, it should be `meshConfig.defaultConfig.holdApplicationUntilProxyStarts`
