### ISSUE TITLE
PeerAuthentication policies are inflexible with label selections

### ISSUE THREAD

**Issue by AlexDHoffer** [istio/istio#30457]
**Describe the feature request**

Currently, PeerAuthentication policies allow both namespace-level scope and workload-level scope. However, you cannot set portLevelMtls for an entire namespace, nor can you match across multiple labels with a single policy. 

Consider the following scenario to make this clearer:

Your app pods in namespace X all expose metrics on port Y. However, each app pod does not share a singular label, each one is labeled with app = {A..Z}. Thus, you want to set mTLS as permissive for these pods so that you can scrape the metrics on that port, but you have to create a separate PeerAuthentication resource, where each one can specify: 

````
selector:
   matchLabels:
       app: {A..Z}
````

This leads to essentially duplicating the policy for each app, which is unfavorable.

This feature request is to allow either a regex matching expression on the matchLabels field or to allow a port-level mTLS to apply to an entire namespace, but keep all other ports locked up to STRICT.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by hzxuzhonghu** [comment]
One alternative  is: extend the matchlabels with MatchExpressions

**Comment by howardjohn** [comment]
I understand the request, but the current API design seems consistent with Kubernetes. For example, you would have to make Service a..z, even if they have the same port.

**Comment by AlexDHoffer** [comment]
You can apply destination rules that take effect for all services in an entire namespace using a wildcard host (e.g. ``host: '*.my_namespace.svc.cluster.local'). I suppose I don't see why peer/request authentication resources couldn't support something like that under the same token.

**Comment by hzxuzhonghu** [comment]
I think this is supported, it is equal to namespace level policy.

**Comment by Le0exxx** [comment]
> I think this is supported, it is equal to namespace level policy.

any example?
