### ISSUE TITLE
Support multiple trust bundles in Istio

### ISSUE THREAD

**Issue by lizan** [istio/istio#30454]
**Describe the feature request**

Today, Istio can't use multiple trust bundles for federation by selecting corresponding trust bundles from certificate. There is a strong desire from the community for the ability to use SPIFFE and Envoy together to achieve a “Federated Identity and Authentication scheme”.  It is going to be resolved in https://github.com/envoyproxy/envoy/issues/14614. This issue is the counter part of the Envoy issue to have istio-agent and istiod to support multiple root trust bundles to be configured for federation correctly.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by costinm** [comment]
Sounds good - current plan is for istio-agent to download the CA roots and other information at startup by asking for the ProxyConfig, and having any info that agent needs inside. That's for the agent-istiod internal protocol - not the external API.

We have several options on how to configure this - for 'alpha' we can use one configmap per federated domain, and keep the same structure with MeshConfig ( which users are familiar with ) - i.e. trustDomain, aliases and the set of CA roots that we're adding for root CA migration.

This may be promoted to a beta API - or maybe something upstream will define an API , k8s signing and CertManager also have the problem of distributing roots.

**Comment by lizan** [comment]
cc @mathetake who is going to work on Envoy side implementation. Can you start a doc describing the multi-root SPIFFE bundles API and how it can be mapped to Istio API? We can then discuss it in Istio Security Meeting.

**Comment by apolovov** [comment]
Is there any news or maybe ETAs?

**Comment by antonioberben** [comment]
Really interested on this feature. We have plenty of users (service owners) that cannot touch much their end to be part of the mesh. This feature would help to make them easy to secure traffic from an egress gw within istio to their"untouchable" service

**Comment by shankgan** [comment]
fyi - Issue to support multiple root's per trustbundle (i.e per trustdomain) - https://github.com/istio/istio/issues/31111. This can be extended to support having one trustbundle per trustdomain if needed
