### ISSUE TITLE
Build fails on Mac

### ISSUE THREAD

**Issue by theganyo** [istio/istio#3046]
I'm unable to build istio master (940608451136812168e953b188db25e9e20ebdc7) on MacOS High Sierra (10.10.13) by running `make`. It appears that istio attempts to pull and run an inappropriate envoy binary:

```
--- FAIL: TestEnvoyRun (0.00s)
	watcher_test.go:375: fork/exec /Users/theganyo/dev/istio/bin/envoy: exec format error
FAIL
FAIL	istio.io/istio/pilot/pkg/proxy/envoy	4.241s
ok  	istio.io/istio/pilot/pkg/proxy/envoy/mock	0.064s
?   	istio.io/istio/pilot/pkg/serviceregistry	[no test files]
ok  	istio.io/istio/pilot/pkg/serviceregistry/aggregate	0.065s
ok  	istio.io/istio/pilot/pkg/serviceregistry/cloudfoundry	3.290s
ok  	istio.io/istio/pilot/pkg/serviceregistry/consul	0.074s
ok  	istio.io/istio/pilot/pkg/serviceregistry/eureka	0.275s
ok  	istio.io/istio/pilot/pkg/serviceregistry/kube	0.276s
?   	istio.io/istio/pilot/test/client	[no test files]
?   	istio.io/istio/pilot/test/eurekamirror	[no test files]
?   	istio.io/istio/pilot/test/grpcecho	[no test files]
?   	istio.io/istio/pilot/test/integration	[no test files]
panic: running envoy: fork/exec /Users/theganyo/dev/istio/bin/envoy: exec format error

goroutine 26 [running]:
istio.io/istio/pilot/test/integration/cloudfoundry_test.(*testState).runEnvoy.func2(0x1b97b80, 0xc4201b2380, 0xc420097ae0, 0xc4201c0900, 0x1b89680, 0xc4201f84a0)
	/Users/theganyo/dev/istio/src/istio.io/istio/pilot/test/integration/cloudfoundry/copilot_test.go:187 +0x16c
created by istio.io/istio/pilot/test/integration/cloudfoundry_test.(*testState).runEnvoy
	/Users/theganyo/dev/istio/src/istio.io/istio/pilot/test/integration/cloudfoundry/copilot_test.go:184 +0x6bc
FAIL	istio.io/istio/pilot/test/integration/cloudfoundry	21.561s
?   	istio.io/istio/pilot/test/integration/cloudfoundry/mock	[no test files]
?   	istio.io/istio/pilot/test/mock	[no test files]
?   	istio.io/istio/pilot/test/server	[no test files]
?   	istio.io/istio/pilot/test/util	[no test files]
make: *** [pilot-test] Error 1
```

**Comment by theganyo** [comment]
It appears there are just two test file that attempt to run envoy: ../envoy/watcher_test.go and ../cloudfoundry/copilot_test.go. Eliminating those two allows the build to continue... until it seems to just hang at this point: ```
?   	istio.io/istio/mixer/template/sample/check	[no test files]
?   	istio.io/istio/mixer/template/sample/quota	[no test files]
?   	istio.io/istio/mixer/template/sample/report	[no test files]
?   	istio.io/istio/mixer/template/tracespan	[no test files]
```

**Comment by theganyo** [comment]
I understand this has a prerequisite of getting proxy to build correctly on MacOS. So, I've opened an issue for that here: https://github.com/istio/proxy/issues/973. I've also submitted a PR that will hopefully resolve it and get us closer to resolving this issue.

**Comment by andraxylia** [comment]
#2831 should have fixed that, it was merged today, please retry.

The exec format error you got is because make overrides GOOS and GOARCH, so it builds for linux.

The proxy issue remains valid.

**Comment by tiswanso** [comment]
I've been able to build and exec/debug istio binaries via e.g.: 
```
GOOS=darwin GOARCH=amd64 make istioctl-all
