### ISSUE TITLE
Pilot Discovery pod is consuming High CPU

### ISSUE THREAD

**Issue by rvgud** [istio/istio#30472]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
Pilot cpu utilisation is high. With 700 endpoints and only having istio-proxy sidecar. 5m avg config push time 30s.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

./istioctl version --remote
client version: 1.4.5
control plane version: 1.4.5
data plane version: 1.4.5 (586 proxies)

kubectl version --short
Client Version: v1.18.8
Server Version: v1.15.7

helm version --short
Client: v2.16.10+gbceca24
Server: v2.16.10+gbceca24

**How was Istio installed?**
helm install install/kubernetes/helm/istio --name istio --namespace istio-system --set global.proxy.accessLogFile="/dev/stdout",global.disablePolicyChecks=true,global.proxy.accessLogEncoding="JSON",grafana.enabled=true,kiali.enabled=true,prometheus.enabled=true,prometheus.service.nodePort.enabled=true,gateways.enabled=true,gateways.istio-ingressgateway.enabled=true,gateways.istio-ingressgateway.type=NodePort,tracing.enabled=true

**Environment where the bug was observed (cloud vendor, OS, etc)**
Oaacle Kubernetes

Additional Information:
**HPA for istio-pilot on avg cpu:**
kubectl get hpa istio-pilot  -n istio-system -w
NAME          REFERENCE                TARGETS   MINPODS   MAXPODS   REPLICAS   AGE
istio-pilot   Deployment/istio-pilot   27%/80%   5         15        15         80d
istio-pilot   Deployment/istio-pilot   15%/80%   5         15        15         80d
istio-pilot   Deployment/istio-pilot   1180%/80%   5         15        15         80d
istio-pilot   Deployment/istio-pilot   24%/80%     5         15        15         80d
istio-pilot   Deployment/istio-pilot   24%/80%     5         15        15         80d
istio-pilot   Deployment/istio-pilot   215%/80%    5         15        15         80d
istio-pilot   Deployment/istio-pilot   547%/80%    5         15        15         80d
istio-pilot   Deployment/istio-pilot   20%/80%     5         15        15         80d

kubectl get svc --all-namespaces | wc -l
     699

Attaching the pprof /debug/pprof/profile.
[pprof.pilot-discovery.samples.cpu.003.pb.gz](https://github.com/istio/istio/files/5887930/pprof.pilot-discovery.samples.cpu.003.pb.gz)

**Comment by howardjohn** [comment]
Please upgrade, 1.4 is no longer supported and performance has improve **significantly** since then. See https://istio.io/latest/news/support/announcing-1.6-eol/ and others like it
