### ISSUE TITLE
Flatten helm charts directory structure to use as single Helm repo using helm-git plugin

### ISSUE THREAD

**Issue by JorritSalverda** [istio/istio#30471]
**Describe the feature request**

In order to use the Helm charts without manually downloading the repository first I use the [helm-git](https://github.com/aslafy-z/helm-git) plugin (in combination with [helmfile](https://github.com/roboll/helmfile)) so I can use the Istio Github repository straight away as if it's an actual remote Helm repository, by adding it as follows:

```
helm repo add istio git+https://github.com/istio/istio@manifests/charts/?ref=1.8.2&sparse=0&depupdate=0
```

From there on I can install Istio charts with

```
helm install -n istio-system istio-base istio/base
```

Unfortunately this doesn't work for the deeper nested charts like `istio-control/istio-discovery`, `gateways/istio-egress` and `gateways/istio-ingress`.

Could those 3 be moved up one level so they can be installed with the following?

```
helm install -n istio-system istio-discovery istio/istio-discovery
helm install -n istio-system istio-ingress istio/istio-ingress
helm install -n istio-system istio-egress istio/istio-egress
```

**Describe alternatives you've considered**

An alternative is to add the `istio-control` and `gateways` as separate repositories:

```
helm repo add istio-control git+https://github.com/istio/istio@manifests/charts/control?ref=1.8.2&sparse=0&depupdate=0
helm repo add istio-gateways git+https://github.com/istio/istio@manifests/charts/gateways?ref=1.8.2&sparse=0&depupdate=0
```

And then install with

```
helm install -n istio-system istio-discovery istio-control/istio-discovery
helm install -n istio-system istio-ingress istio-gateways/istio-ingress
helm install -n istio-system istio-egress istio-gateways/istio-egress
```

Unfortunately the `helm-git` approach is pretty slow, so the less repositories it needs to bring in the better!

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by unacceptable** [comment]
I am also not a fan of this directory layout, but if the maintainers wanted to keep this, I think a good compromise would be for the maintainers to just publish this chart in an artifact repo.  I do this for my personal helm charts with the [helm-s3 plugin](https://github.com/hypnoglow/helm-s3) and an amazon s3-website and a lambda to rewrite the index.yaml, but there are a million ways for the maintainers to skin that cat.

**Comment by AntonioAlfrz** [comment]
Something I have noticed too is that the Chart versions are not consistent, for instance, istio-operator Helm chart version in the code is 1.7.0 for tag 1.9.1: [](https://github.com/istio/istio/blob/1.9.1/manifests/charts/istio-operator/Chart.yaml)
Although it must be said that the only difference is the image's tag and hub

**Comment by AntonioAlfrz** [comment]
Hi, I agree, however, the chart included in the manifests/ folder in the releases does have the same version,i.e, release 1.9.1 -> chart version 1.9.1 
That means that switching from using the chart in the release to helm-git requires changing the chart version.
