### ISSUE TITLE
Applying Sidecar resource with WorkloadSelector causes VirtualServices to be ignored

### ISSUE THREAD

**Issue by markrogers95** [istio/istio#30482]
**Bug description**

Applying a Sidecar resource with a WorkloadSelector that configures egress traffic to given ports onto a cluster with VirtualServices already in place causes the pre-existing VirtualServices to be omitted when the new config is pushed to Envoy.

[ ] Docs
[ ] Installation
[x] Networking
[x] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

[] Multi Cluster
[x] Virtual Machine
[] Multi Control Plane

**Expected behavior**
Applying Sidecar resource with WorkloadSelector with egress traffic restrictions to given ports should show VirtualServices in the proxy config dump:

```
          "route": {
           "cluster": "outbound|5565||service.namespace.svc.cluster.local",
           "timeout": "x",
           "retry_policy": {
            "retry_on": "VS specific errors",
            "num_retries": x,
            "per_try_timeout": "x",
            "retry_host_predicate": [
             {
              "name": "envoy.retry_host_predicates.previous_hosts"
             }
            ],
            "host_selection_retry_max_attempts": "x"
           },
           "max_grpc_timeout": "x"
          },
          "metadata": {
           "filter_metadata": {
            "istio": {
             "config": "/apis/networking/v1alpha3/namespaces/namespace/virtual-service/service"
            }
           }
          },
```
 
Actual config dump:

``` 
          "route": {
           "cluster": "outbound|5565||service.namespace.svc.cluster.local",
           "timeout": "0s",
           "retry_policy": {
            "retry_on": "connect-failure,refused-stream,unavailable,cancelled,resource-exhausted,retriable-status-codes",
            "num_retries": 2,
            "retry_host_predicate": [
             {
              "name": "envoy.retry_host_predicates.previous_hosts"
             }
            ],
            "host_selection_retry_max_attempts": "5",
            "retriable_status_codes": [
             503
            ]
           },
           "max_grpc_timeout": "0s"
          },
```

**Steps to reproduce the bug**

1. Configure and apply virtual service.
2. Dump envoy config and grep for "virtual-service"
3. Configure and apply Sidecar resource with WorkloadSelector configured for egress traffic to certain ports.
4. Restart affected pods.
5. Dump Envoy config and grep for "virtual-service"

Note this does not replicate all the time. I have found upon investigation that the number of ports/services seems to affect ones ability to reproduce this but that a larger number of configured egress ports is more likely to yield results.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
Istio: 1.4.7
Kubectl:
  Client Version: v1.18.12
  Server Version: v1.15.12

**Environment where the bug was observed (cloud vendor, OS, etc)**
AWS

**Comment by howardjohn** [comment]
Without more details of the actual Sidecar spec and virtual service spec it sounds like this is intended - although it may be bug. This is what Sidecar.Egress does - it filters out configs not in scope.

Can you add the configs?

**Comment by markrogers95** [comment]
I've since done some more digging and I can only replicate this remotely. Locally, on microk8s, this works as expected and filters out any VirtualServices not accessible to the Sidecar, but retains those that are. 

I'm following the same replication steps in each scenario but perhaps there is some nuance in applying a Sidecar to a remote cluster that I am missing? Locally I am just applying the Sidecar and rolling the deployment before curling the config_dump and seeing the VirtualServices I am expecting. Remotely I am doing the same but restarting all pods in the namespace before curling the endpoint.

& sure, config as below (doctored but consistent with what I am using):
Sidecar
`
apiVersion: networking.istio.io/v1alpha1
kind: Sidecar
metadata:
  name: test
  namespace: default
spec:
  workloadSelector:
    labels:
      app: svc-a
  egress:
  - port:
      number: 7999
      protocol: HTTP
      name: svc-b
    hosts:
    - "./*"
  - hosts:
    - "istio-system/*"
`
VirtualService
`
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: test-route
spec:
  Hosts:
    svc-b
  Http:
    Match:
      Port:  7999
      Uri:
        Prefix:  /
    Retries:
      Attempts:         x
      Per Try Timeout:  xs
      Retry On:         <chosen codes>
    Route:
      Destination:
        Host:  svc-b
    Timeout:   xs
`
