### ISSUE TITLE
status distribution: NACKs treated as reconciled

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#30498]
Note - I didn't get a chance to test this personally, this is based on code observation.

It appears a nack will be treated the same as an ack for status distribution. This leads to incorrect information. Users will query the reconciled status and assume the config has applied - in reality it was rejected.

**Comment by esnible** [comment]
@therealmitchconnors Add to the status tracking issue

**Comment by howardjohn** [comment]
not stale

**Comment by howardjohn** [comment]
not stale
