### ISSUE TITLE
Embed OpenTelemetry Collector within Istio Proxy

### ISSUE THREAD

**Issue by objectiser** [istio/istio#30503]
**Describe the feature request**

As outlined on the [OpenTelemetry website](https://opentelemetry.io/): "OpenTelemetry is a collection of tools, APIs, and SDKs. You use it to instrument, generate, collect, and export telemetry data (metrics, logs, and traces) for analysis in order to understand your software's performance and behavior."

This proposal is to embed the OpenTelemetry Collector, with a suitable subset of receivers, processors and exporters, into the Istio proxy directly. (Note: a custom build of the OpenTelemetry Collector, with only the required components, can be built using the [OpenTelemetry Collector Builder](https://github.com/open-telemetry/opentelemetry-collector-builder) - currently being moved from [this location](https://github.com/observatorium/opentelemetry-collector-builder)).

The benefit is that:
* The Istio proxy can have a simple envoy tracer configuration, using the [OpenCensus agent protocol for now](https://github.com/istio/istio/issues/23960#issuecomment-671271958) until OTLP is directly supported in envoy, to report tracing data to the embedded OTel Collector
* The OTel Collector could be configured to report tracing data to any supported backend - Jaeger, Zipkin as part of the core collector, or others from the [contrib repo](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter)
* The app can be configured to report additional tracing data (via an OpenTelemetry SDK) to the embedded OTel Collector, rather than having to [worry about setting up other sidecar agents (e.g. Jaeger)](https://github.com/istio/istio/issues/19379)
* Other telemetry signals could be routed via the OTel Collector in the future (i.e. metrics and logs)

**Describe alternatives you've considered**

The envoy proxy could be extended to include the OpenTelemetry C++ SDK. This would provide some of the same beneftis - except it relies on the addition of "processors" and "exporters" for various backend systems within the C++ SDK. Supporting new processors and especially exporters is more likely to occur in the OpenTelemetry Collector, as it is programming language agnostic, so will benefit all language SDKs.

[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by naphta** [comment]
Is there any update on this feature?

**Comment by chinaran** [comment]
Is there any update on this feature?

**Comment by m-mijatovic** [comment]
Any update on open telemetry support or is this [23960](https://github.com/istio/istio/issues/23960) for now the only way to go?

**Comment by Patrick0308** [comment]
@

**Comment by Patrick0308** [comment]
I think this issue is blocked on https://github.com/envoyproxy/envoy/issues/9958
