### ISSUE TITLE
TestXdsProxyHealthCheck test flake

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#30510]
https://prow.istio.io/view/gs/istio-prow/logs/unit-tests_istio_postsubmit/1355198515185192960

**Comment by adiprerepa** [comment]
ran the test multiple times locally without luck of reproducing it. How do you recommend reproducing it?

**Comment by howardjohn** [comment]
I added https://github.com/istio/istio/wiki/Test-Flakes#reproducing-test-flakes with some instructions. let me know if its not clear, I just wrote this

**Comment by adiprerepa** [comment]
Thanks for adding it. I modified a few things but besides that its very understandable. I am finally able to reproduce the flake.

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gs/istio-prow/logs/unit-tests_istio_postsubmit/1395876045185355776
