### ISSUE TITLE
Provide instructions on revisioned upgrade of east-west gateway

### ISSUE THREAD

**Issue by jasonwzm** [istio/istio#30526]
**Describe the feature request**
The eastwest gateway is currently revisioned, but because it is not installed with istioctl, the upgrade experience is not well documented. We need to document that in docs.

Later if we move it in a separate profile, it can be better handled by istioctl.

/cc @nmittler @stevenctl @duderino 

**Describe alternatives you've considered**

[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by nmittler** [comment]
@jasonwzm is this still something you're working on?

**Comment by jasonwzm** [comment]
@nmittler Thanks for the reminder on this. Have we talked about injection-based east-west gateway vs revisioned gateway? With the injection based gateway more in the picture, it might be also worth it to assess which option we provide.

**Comment by nmittler** [comment]
IIRC the direction so far has been revisioned gateways.

@stevenctl can you confirm?

**Comment by stevenctl** [comment]
I agree with using revisioned gateways. I do think there's an opportunity to simplify the installation process using injection as well. https://github.com/istio/istio/issues/34835
