### ISSUE TITLE
Istiod doesn't respect affinity or nodeSelector attributes

### ISSUE THREAD

**Issue by yfried** [istio/istio#30538]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
Unlike Istio addons, the core istiod component doesn't provide a way to set nodeSelector and affinity or anti-affinity attributes.

[ ] Docs
[x ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Istiod deployment should have nodeSelector and/or affinity attributes based on `pilot`/`global` values, same as the istio addons (ingress, egress, etc...), but the istio-discovery chart doesn't support this.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
1.8.2
1.8.1
**How was Istio installed?**
helm charts

This bug is referenced in #29642 but the relevant PR was closed.
Simply copying the `_affinity.tpl` from the addons should solve this

**Comment by morvencao** [comment]
It is recommend to set resources/affinity/annotation... with k8s settings, see: https://github.com/istio/istio/tree/master/operator#new-api-customization
We don't want to add helm parameters for each option in the values.yaml any more, it's hard to maintain so many options in the helm values.

**Comment by yfried** [comment]
> It is recommend to set resources/affinity/annotation... with k8s settings, see: https://github.com/istio/istio/tree/master/operator#new-api-customization
> We don't want to add helm parameters for each option in the values.yaml any more, it's hard to maintain so many options in the helm values.

Hi, @morvencao, 
I'm installing Istio [via helm-charts](https://istio.io/latest/docs/setup/install/helm/). How can I use this new API customization

**Comment by yfried** [comment]
Also, if I want these settings to apply to all components (for example - hpa and anti-affinity), do I have to redefine it explicitly for each component?

**Comment by morvencao** [comment]
@yfried Yes, this is the api doc for k8s settings: https://github.com/istio/istio/tree/master/operator#new-api-customization
Also some examples: 
https://github.com/istio/istio/blob/master/operator/cmd/mesh/testdata/manifest-generate/input/pilot_k8s_settings.yaml
https://github.com/istio/istio/blob/master/operator/cmd/mesh/testdata/manifest-generate/input/ingressgateway_k8s_settings.yaml

**Comment by FischlerA** [comment]
> @yfried Yes, this is the api doc for k8s settings: https://github.com/istio/istio/tree/master/operator#new-api-customization
> Also some examples:
> https://github.com/istio/istio/blob/master/operator/cmd/mesh/testdata/manifest-generate/input/pilot_k8s_settings.yaml
> https://github.com/istio/istio/blob/master/operator/cmd/mesh/testdata/manifest-generate/input/ingressgateway_k8s_settings.yaml

We are also using the helm charts to install istio into our cluster which does not contain the istio operator. So if i'm reading the documentation right these settings won't work without the istio-operator.

Is there any other way to add node affinity?

**Comment by morvencao** [comment]
Maybe [kustomize](https://github.com/kubernetes-sigs/kustomize) is another option if you're using helm chart.

**Comment by dex4er** [comment]
I did it with kustomize:

```sh
cat > kustomization.yaml <<END
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - _all.yaml

patches:
  - path: patch.yaml
    target:
      kind: Deployment
END
cat > patch.yaml <<END
apiVersion: apps/v1
kind: Deployment
metadata:
  name: istiod
spec:
  template:
    spec:
      affinity:      
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.google.com/gke-nodepool
                operator: In
                values:
                - default-pool
END
cat > kustomize.sh <<END
#!/bin/bash
cd $(dirname $0)
trap "rm -f _all.yaml" EXIT
cat <&0 > _all.yaml
kustomize build .
END
chmod +x kustomize.sh
```

and I call helm as:

```sh
helm template manifests/charts/istio-control/istio-discovery --post-renderer ./kustomize.sh 
```

and it is far from Helm values.yaml and its flexibility because all patch files are static and can't be customized from command line or environment variables.

This solution with Helm+Kustomize is like Frankenstein's monster. Please reconsider to add nodeSelector to helm chart or at least please remove it from values.yaml for pilot as far as it is misleading.
