### ISSUE TITLE
WASM propaganda header doesn't match in VirtualService

### ISSUE THREAD

**Issue by feuyeux** [istio/istio#30545]
**Bug description**
The [wasm](https://github.com/feuyeux/rust-wasm-4-envoy/blob/main/propaganda-filter/src/lib.rs) and its [envoyfilter](https://github.com/feuyeux/rust-wasm-4-envoy/blob/main/propaganda-filter/sh/istio/mesh/hello1_v2_envoyfilter.yaml) are used to propaganda header in outbound, and the [virtualservice](https://github.com/feuyeux/rust-wasm-4-envoy/blob/main/propaganda-filter/sh/istio/mesh/hello2_virtualservice.yaml) is used to match the specific header and route to v2, otherwise route to v3.
![image](https://user-images.githubusercontent.com/769711/106413107-3a35d800-6484-11eb-9c8d-7ac1f888739b.png)

But, after I confirmed the wasm log: 
![image](https://user-images.githubusercontent.com/769711/106412132-e629f400-6481-11eb-9d30-33bf0c29d8e1.png)

I found the route-chain was still `hello1v2`-`hello2v3`-`hello3v3`, which was not matched chain:
![image](https://user-images.githubusercontent.com/769711/106411585-9565cb80-6480-11eb-86fe-f1e96620e2e8.png)

**Expected behavior**
And what I want is `hello1v2`-`hello2v2`-`hello3v2`

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ x ]  Networking
[ ] Performance and Scalability
[ x ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ x ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ x ] Multi Cluster
[ x ] Virtual Machine
[ x ] Multi Control Plane

**Steps to reproduce the bug**
- wasm: https://github.com/feuyeux/rust-wasm-4-envoy/blob/main/propaganda-filter/Cargo.toml
- step by step sh: https://github.com/feuyeux/rust-wasm-4-envoy/tree/main/propaganda-filter/sh/istio

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
- istio: 1.7.5
- k8s: 1.18

**Comment by howardjohn** [comment]
I think this is either an issue in your wasm code (possibly calling the wrong apis or injecting in the wrong place) or envoy triggers the match logic before your additional header is added. 

do it need to be injected before http.router filter perhaps?

**Comment by feuyeux** [comment]
> I think this is either an issue in your wasm code (possibly calling the wrong apis or injecting in the wrong place) or envoy triggers the match logic before your additional header is added.
> 
> do it need to be injected before http.router filter perhaps?

wasm code is here:https://github.com/feuyeux/rust-wasm-4-envoy/blob/main/propaganda-filter/src/lib.rs

**Comment by feuyeux** [comment]
> I think this is either an issue in your wasm code (possibly calling the wrong apis or injecting in the wrong place) or envoy triggers the match logic before your additional header is added.
> 
> do it need to be injected before http.router filter perhaps?

@howardjohn I like update to you.
The below two envoyfilters are select some pod(hello1-deploy-v2), the lua version works well, but wasm doesn't.
- [wasm version](https://github.com/feuyeux/rust-wasm-4-envoy/blob/main/propaganda-filter/sh/istio/envoyfilter/hello1_v2_envoyfilter.yaml)
- [lua version](https://github.com/feuyeux/rust-wasm-4-envoy/blob/main/propaganda-filter/sh/istio/lua.envoyfilter/hello1_v2_lua_envoyfilter.yaml)

the core rust code is [here](https://github.com/feuyeux/rust-wasm-4-envoy/blob/main/propaganda-filter/src/lib.rs):

```rust
impl HttpContext for PropagandaFilter {
    fn on_http_request_headers(&mut self, _: usize) -> Action {
        let head_tag_key = self.config.head_tag_name.as_str();
        if !head_tag_key.is_empty() {
            self.set_http_request_header(head_tag_key, Some(self.config.head_tag_value.as_str()));
        }
...
```

I think lua/wasm will be executed at the same point-in-time, which is before match header. 
- lua: `envoy_on_request`
- wasm: `on_http_request_headers`

So, I think, in wasm version, there's some issues between virtualservice and envoyfilter

**Comment by bianpengyuan** [comment]
I think you need to clean the route cache after setting the header to make Envoy decide route again. https://github.com/proxy-wasm/proxy-wasm-rust-sdk/blob/7de2acdd783e7d3072f7267517b34c95caa1d3b7/src/traits.rs#L312

**Comment by feuyeux** [comment]
> I think you need to clean the route cache after setting the header to make Envoy decide route again. https://github.com/proxy-wasm/proxy-wasm-rust-sdk/blob/7de2acdd783e7d3072f7267517b34c95caa1d3b7/src/traits.rs#L312

Thanks a lot, and it's very helpful for me. Accordingly, I searched the below references:
