### ISSUE TITLE
Integrate an existing prometheus instance

### ISSUE THREAD

**Issue by kubealex** [istio/istio#30540]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

[ X ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ X ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
1.8+

Documentation reports:

To use an existing Prometheus instance, add the scraping configurations in prometheus/configmap.yaml to your configuration.

But the [link](https://raw.githubusercontent.com/istio/istio/release-1.8/manifests/charts/istio-telemetry/prometheus/templates/configmap.yaml) provided is broken, plus there is no reference to that anywhere else.

**Comment by kubealex** [comment]
Documentation has been updated, but the file is still missing.

https://raw.githubusercontent.com/istio/istio/release-1.9/manifests/charts/istio-telemetry/prometheus/templates/configmap.yaml

**Comment by bianpengyuan** [comment]
Sorry the guide is out of dated. https://github.com/istio/istio.io/pull/8976 will update that.
