### ISSUE TITLE
istioctl workload configure: consider handling lack of TokenRequest

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#30573]
https://istio.io/latest/docs/ops/best-practices/security/#configure-third-party-service-account-tokens

Not all clusters have this enabled. its default now in 1.20 or 1.21 though, and all cloud providers have it set from my experience.

Istioctl install does detection. We can likely do the same and at least give a better error message

**Comment by irisdingbj** [comment]
@howardjohn  after detecting the jwt policy and if it is on first part jwt, shall we retrieve the token from the secret for the sa and use it? seems we need to parse the sa  to get the secret and decode it to get the token.  wondering if this is redundant if most cluster are supporting 3rd party jwt , what do you think about it?  Thanks~

**Comment by howardjohn** [comment]
I don't know. We could also just fail with a better error message - 3p jwt is on by default now so most users should be fine. Also, VMs are for advanced users in general so they can handle some pain

**Comment by irisdingbj** [comment]
go ahead with adding first-party token support as it is a more user-friendly mode.

**Comment by howardjohn** [comment]
Ok, can you make sure to add a warning message that it's not secure?

**Comment by irisdingbj** [comment]
Ok, can you make sure to add a warning message that it's not secure?
 
now the output is like below if we are on first-party jwt:

```
warning: Detected that your cluster does not support third party JWT authentication. Falling back to less secure first party JWT. See https://istio.io/v1.10/docs/ops/best-practices/security/#configure-third-party-service-account-tokens for details.
warning: a security token for namespace vm and service account vmsa has been generated and stored at /home/iris/test/istio-token
configuration generation into directory /home/iris/test was successful
```
