### ISSUE TITLE
TestMultiVersionRevision test flakes

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#30572]
https://prow.istio.io/view/gs/istio-prow/logs/integ-k8s-115_istio_postsubmit/1356343350336163840
https://prow.istio.io/view/gs/istio-prow/logs/integ-k8s-115_istio_postsubmit/1356327725266112512

cc @Monkeyanator

**Comment by howardjohn** [comment]
@stevenctl I think its from https://github.com/istio/istio/commit/d3f9ceaa54bdabb736583067263dc001063824aa? or a big coincidence

**Comment by stevenctl** [comment]
It could be.. but I don't even see the namespace dir in the dump: https://gcsweb.istio.io/gcs/istio-prow/logs/integ-k8s-115_istio_postsubmit/1356343350336163840/artifacts/pilot-d4b526b60f3e4edabe517655c/TestMultiVersionRevision/_test_context/

**Comment by Monkeyanator** [comment]
Strange this test is failing on 1.15 postsubmits since we should be explicitly skipping it in this job ([skipped for k8s versions <1.16](https://github.com/istio/istio/blob/c9ba0994f4db833f434c0c25405afdb06095ec3b/tests/integration/pilot/multi_version_revision_test.go#L187))

**Comment by Monkeyanator** [comment]
Yeah looking at it now I think it's probably got something to do with `MinKubeVersion`
