### ISSUE TITLE
[istio 1.8.1] istio-cni node cpu/mem resources

### ISSUE THREAD

**Issue by noah8713** [istio/istio#30570]
**Describe the feature request**

istio-cni-node daemon set; add support to set cpu/mem resources

Running istio-cni daemon set pods consumes 10G total memory in k8s cluster; 5G for install-cni and 5G for repair-cni

```
kubectl describe node xxxx


kube-system                istio-cni-node-hr669                      1 (1%)        1 (1%)      10Gi (6%)        10Gi (6%)      51d 
```
As a result it consumes more resources on the node. Not sure if we have any base number requirement for install/repair cni. 

**Describe alternatives you've considered**
I added resources in istio-cni charts/templates to tune it  via operator on need basis along with values.yaml

```
resources:
{{- if .Values.cni.resources }}
{{ toYaml .Values.cni.resources | trim | indent 12 }}
{{- else }}
{{ toYaml .Values.global.defaultResources | trim | indent 12 }}
{{- end }}
```

k8s node compute resources ;cpu/mem

Hence, need to know if there are any other approaches/suggestions for baseline settings for istio-cni pods resources . Not sure if above alternative support via template change is being worked on. 

[ ] Docs
[X ] Installation
[ ] Networking
[X ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by noah8713** [comment]
Setting  too less resources for install-cni causes OOM

```
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 50m
      memory: 50Mi

``` 

```
  Warning  SystemOOM  <invalid>  kubelet, node-xxx  System OOM encountered, victim process: install-cni, pid: 105476
  Warning  SystemOOM  <invalid>  kubelet, node-xxx  System OOM encountered, victim process: install-cni, pid: 106169
  Warning  SystemOOM  <invalid>  kubelet, node-xxx  System OOM encountered, victim process: install-cni, pid: 106622
  Warning  SystemOOM  <invalid>  kubelet, node-xxx  System OOM encountered, victim process: install-cni, pid: 107759

```

Suggestions/doc on setting optimal value would be great for istio-cni-pod.

**Comment by howardjohn** [comment]
5gb memory usage is highly unexpected, the pod does pretty much nothing most of the time. cc @stewartbutler

**Comment by noah8713** [comment]
@howardjohn : 
I am using this changes for over-ride 

https://github.com/noah8713/istio/commit/cbf8772d48234e8f90c07341109ba526317d264e . Let me know if this is duplicate or can be used as a PR for tuning cni resources.

**Comment by howardjohn** [comment]
Adding a higher limit is not the right fix. Maybe its something we should do, but CNI using 5gb is *very* wrong. Also it sounds likely to a memory leak, so even a high limit would not help?

**Comment by noah8713** [comment]
I think its more of cpu/mem default resource which it allocates but uses few of it (not all of 5G is used). Only thing is node level still things as all allocated resource.  e.g above where super low cpu/mem will cause Crashback loop. 

I tried with new defaults and don't see issues so far with OOM for both install/repair CNI because the .
```
resources:
    limits:
      cpu: 400m
      memory: 400Mi
    requests:
      cpu: 100m
      memory: 100Mi
```


```
 kube-system                istio-cni-node-vrsw7                                                 200m (0%)     800m (1%)   200Mi (0%)       800Mi (0%)     5h28m

```

**Comment by noah8713** [comment]
We can leverage k8s overlay patches to set this too. Hence, closing the same as I am able to over-ride. More details in https://github.com/istio/istio/pull/30536
