### ISSUE TITLE
Validate each feature of the IstioOperator Spec against a particular version of K8s

### ISSUE THREAD

**Issue by shankgan** [istio/istio#30585]
Currently, when installing Istio on k8s, I assume we broadly check if a given istio version is compatible with a given K8s version. However, in addition to this, there are some SPECIFIC features of Istio that are supported only from/until a particular K8s version.  It would be helpful if the IstioOperator/Istioctl code could provide some validation hooks so that each feature configuration could be checked at install time to safely fail back if the K8s cluster does not support the specific feature. 

[A Specific example ](https://github.com/istio/istio/issues/22161)- Here, it would be good if we could prevent a particular configuration (PILOT_CERT_PROVIDER=kubernetes) if we detect that the version of K8s >= 1.22.x

Is there already a canonical way to do this? If not, I am not sure how easy/hard this will be to implement. Are there any other features that have the same requirement? 

**Describe alternatives you've considered**
One option would be to simply not honor the feature configuration when we detect at runtime that the specific version of K8s does not support it. This gets tricky, however, when this is an essential feature configuration and when not honoring the feature configuration would require us to fallback to some default configuration.

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
This is already an established pattern:
* https://github.com/istio/istio/blob/d96e772724184069fd40c41be32c313b4040c386/operator/pkg/util/k8s.go#L33
* https://github.com/istio/istio/blob/96f0b401cdc7794817187334bcbee44ff1193d48/operator/pkg/manifest/shared.go#L376

**Comment by howardjohn** [comment]
is this resolved by ^?

**Comment by shankgan** [comment]
I think it is. Was wondering if there were a more easier and generic way of solving it. Will close issue for now.
