### ISSUE TITLE
Istio Stability Issues 503 NR

### ISSUE THREAD

**Issue by rajivml** [istio/istio#30586]
HI,

can you please let us know at what scale istio has been tested, I mean w.r.t to the number of namespaces.

We have a fairly large kubernetes cluster i.e. around 300 Nodes (AKS cluster) and we have around 3000 namespaces with close to 4000 services deployed and we are using Istio as an service mesh and ingress controller to route the traffic 

The issue that we are consistently facing with Istio in production is and this is almost happening every couple of hours and I guess it's something to do with the istiod leader election and when this issue occur all new namespaces that are created will have missing istio-ca-root-cert cert

I have logged a ticket for this issue in the past as well but this has been closed saying no other customer is facing such issue https://github.com/istio/istio/issues/26259 

So, to tackle it ourselves we have put an hack where we run a cronjob every 10 minutes and if it sees a namespace which is older than 5 minutes and with missing istio-ca-root-cert  cert, do an rolling restart of istiod pod

But when ever we do an rolling restart of istiod ,all side cars loose contact with istiod and all further service calls would fail with 503 NR for few minutes till istiod is backup in healthy state https://github.com/istio/istio/issues/29599

And today the extreme happened where traffic on production is down for 53 minutes after the istiod restart event happened and now we are thinking of alternative solutions but unfortunately that can't happen overnight :( 

Can some one please let us know what might be causing this and how to debug and fix this issue. If any logs are required am happy to share the same 

Steps to reproduce the bug
It's only happening at scale with 2000+ namespaces and with 1000's of deployments

How was Istio installed?
Using Istio-operator

Environment where the bug was observed (cloud vendor, OS, etc)
Azure AKS 1.17 with istio 1.5.6

**Comment by rajivml** [comment]
and this is that cron we are living with :( 


  
```
#!/bin/bash

function arraydiff() {
  awk 'BEGIN{RS=ORS=" "}
       {NR==FNR?a[$0]++:a[$0]--}
       END{for(k in a)if(a[k])print k}' <(echo -n "${!1}") <(echo -n "${!2}")
}

echo "Validating istio setup"

#get all namespaces
all_namespaces=($(kubectl get ns  --no-headers | awk -F ' ' '{print $1}'))
#get all namespaces with cert injected
namespaces_with_cert=($(kubectl get cm -A | grep istio-ca-root-cert | awk -F ' ' '{print $1}'))
#get all namespaces without cert injected
namespaces_missing_cert=($(arraydiff all_namespaces[@] namespaces_with_cert[@]))

ns_missing_cert_count=${#namespaces_missing_cert[@]}

if [ ${ns_missing_cert_count} -gt 0 ];
then
  echo "There are $ns_missing_cert_count namespaces with missing istio-ca-root-cert cert"
  echo "Namespaces with missing certs: "
  kubectl get ns ${namespaces_missing_cert[@]} -o go-template --template '{{range .items}}{{.metadata.name}} {{.metadata.creationTimestamp}}{{"\n"}}{{end}}'
  echo "Checking how many of these namespaces are older than 5 minutes"
  namespaces_created_x_min_back=$(kubectl get ns ${namespaces_missing_cert[@]} -o go-template --template '{{range .items}}{{.metadata.name}} {{.metadata.creationTimestamp}}{{"\n"}}{{end}}' | awk '$2 <= "'$(date -d'now-5 min' -Ins --utc | sed 's/+0000/Z/')'" { print $1 }')

  #calculating array length via function is giving wrong count due to some blank space, thats why counting through looping
  count=0
  for namespace in ${namespaces_created_x_min_back[@]};
  do
    count=$((count+1))
  done

  if [ $count -gt 0 ];
  then
    echo "They are $count namespaces older than 5 minutes and without istio-ca-root-cert injected into the namespace yet : ${namespaces_created_x_min_back[@]}"
    echo "Injecting istio-ca-root-cert into the namespace where its missing"
    for ns in ${namespaces_created_x_min_back[@]};
    do
      kubectl get configmap istio-ca-root-cert --namespace=default --export -o yaml | kubectl apply --namespace=$ns -f -
    done
    #echo "Restarting istiod service to fix the same"
    #kubectl -n istio-system rollout restart deployment istiod
  else
    echo "There arent any namespaces without istio-ca-root-cert injected"
  fi
else
  echo "There arent any namespaces without istio-ca-root-cert injected"
fi
```

**Comment by howardjohn** [comment]
Can you please try Istio 1.8? I suspect both issues you are seeing are fixed and we cannot support 1.5 anymore (https://istio.io/latest/news/support/announcing-1.6-eol/). If its not, please provide logs of the istiod pod - both of the namespace controller not updated and of the initial pushes that are resulting in 503 NRs

**Comment by rajivml** [comment]
sure @howardjohn we will try istio 1.8 and share the logs if that didn't fix the issue

**Comment by swzhou** [comment]
@rajivml 
I am the one who report issue #29599, and I find that I have to upgrade to Istio 1.9 to get the fix, which looks very difficult for me (cause we are using Kubernetes 1.16, which is not officially support by Istio 1.9). So I find a workaround to handle the case. Hope it helps.

Since the issue is related to early push before Istiod is ready, we delay the healthy status of Istiod to give it enough time to warmup before pushing config by set it's readinessProbe.initialDelaySeconds to 60 seconds:
```
readinessProbe:
  failureThreshold: 3
  httpGet:
     path: /ready
     port: 8080
     scheme: HTTP
  initialDelaySeconds: 60
  periodSeconds: 3
  successThreshold: 1
  timeoutSeconds: 5
```
