### ISSUE TITLE
EndpointSlice flakes: no istiod endpoints

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#30588]
https://storage.googleapis.com/istio-prow/logs/integ-k8s-118_istio_postsubmit/1356642436864020480/artifacts/pilot-endpointslice-a63f4e22674/TestTraffic/selfcall/to_service_vm/_test_context/istio-state616882654/cluster-0/istio-ingressgateway-665558f476-vldfp_proxy-clusters.txt
https://prow.istio.io/view/gs/istio-prow/logs/integ-k8s-118_istio_postsubmit/1356642436864020480

You can see no endpoints for istiod. However, pod state (https://storage.googleapis.com/istio-prow/logs/integ-k8s-118_istio_postsubmit/1356642436864020480/artifacts/pilot-endpointslice-a63f4e22674/TestTraffic/selfcall/to_service_vm/_test_context/istio-state616882654/cluster-0/istiod-86d8cd4d7-2vw64_pod-state.yaml) shows it is ready.

All other endpoint seem to work.

**Comment by bianpengyuan** [comment]
Got another failure, which shows different symptom (envoy crashes unfortunately..): https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/31226/integ-pilot-multicluster-tests_istio/1367609704645136384

Envoy crash log: https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/31226/integ-pilot-multicluster-tests_istio/1367609704645136384/artifacts/pilot-endpointslice-662b69a596a/_suite_context/echo-1-27221-state-504826897/cross-network-primary/tproxy-v1-6df655fb49-5m2dh_istio-proxy.previous.log

Interestingly the crash I ran into is all from tproxy pod.

**Comment by howardjohn** [comment]
@lambdai @tbarrella seems similar to something you may havce been looking into ^

**Comment by howardjohn** [comment]
https://gcsweb.istio.io/gcs/istio-prow/logs/integ-pilot-multicluster-tests_istio_postsubmit/1367694616979050496/artifacts/pilot-endpointslice-a8339c4a722/_suite_context/echo-1-24479-state-559564736/primary/ as well - there is a core dump

**Comment by howardjohn** [comment]
https://storage.googleapis.com/istio-prow/logs/integ-k8s-117_istio_postsubmit/1367728608730157056/artifacts/pilot-endpointslice-93cb8e5c21f/_suite_context/echo-1-69220-state-551681492/cluster-0/vm-v1-55f667f658-p4swn_istio-proxy.envoy.err.log

**Comment by tbarrella** [comment]
Looks like it's from [this](https://github.com/envoyproxy/envoy/pull/15237/files#diff-c904f9b0d49cdd938ffaa952192372529415afa8602d7dc6acb904e61111d8a5R109) - if `cluster_name` isn't in the map, `at()` [raises the exception](https://github.com/abseil/abseil-cpp/blob/887d0eee6bab35847253181b32e78ff707010ccd/absl/container/internal/raw_hash_map.h#L145) in the stack traces of these recent logs
