### ISSUE TITLE
TestSource_WatcherFailsCreatingInformer flake

### ISSUE THREAD

**Issue by Monkeyanator** [istio/istio#30583]
Example failure:

[https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30554/unit-tests_istio/1356485698714079232](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30554/unit-tests_istio/1356485698714079232)

**Comment by howardjohn** [comment]
likely same as https://github.com/istio/istio/issues/23943/https://github.com/istio/istio/issues/26674
