### ISSUE TITLE
http1 request may fail with code 502 

### ISSUE THREAD

**Issue by lambdai** [istio/istio#30581]
Some http server don't like empty body http 1 request declaring header "content-length:0" although RFC 7230 allows.

Workarounds can be
1. bypass istio capture, including but not limited to inbound traffic or egress traffic 
2. send http2 request and declare the protocol as http2.

Discussed in https://github.com/envoyproxy/envoy/issues/14890

**Comment by howardjohn** [comment]
possible same as https://github.com/istio/istio/issues/30146?

**Comment by lambdai** [comment]
Yeah, I search for 502 but that issue is not retrieved...
Close in favor of #30146
