### ISSUE TITLE
istio ingressgateway access.log didn't log anything for bad request

### ISSUE THREAD

**Issue by Jefle2005** [istio/istio#30594]
Hi Team,

I found one kind of issue that istio ingressgateway won't log anything in access.log for bad request, e.g. there is illeagl characters in header name. 

I tried to increase the log level to Debug or trace but no luck. 

anything else i can do?

Istio version: 1.5.0

**Comment by howardjohn** [comment]
Can you try on newer version? We have improved the access logs for exactly this behavior and 1.5 is not supported: https://istio.io/latest/news/support/announcing-1.6-eol/

Additionally, if you could provider the request you are sending to trigger this it would help. thanks.

**Comment by Jefle2005** [comment]
Thanks i will test it with latest version. 

to reproduce it, you just need to add some illegal character in the header name like Chinease.

**Comment by howardjohn** [comment]
`curl ingress/productpage -H "Host: 文"`
```
[2021-02-03T20:14:37.105Z] "- - HTTP/1.1" 400 DPE "-" 0 11 0 - "-" "-" "-" "-" "-" - - 10.36.1.146:8080 10.36.1.1:51981 - 
```

Seems to log for me. Ithink DPE log is new, so maybe its fixed now

**Comment by Jefle2005** [comment]
you're right. i'm able to see the log now after upgrading version to 1.8
