### ISSUE TITLE
TestBadWasmRemoteLoad test flake

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#30593]
https://prow.istio.io/view/gs/istio-prow/logs/integ-telemetry-mc-k8s-tests_istio_postsubmit/1356671068818903040

**Comment by adiprerepa** [comment]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30676/integ-telemetry-mc-k8s-tests_istio/1357491907441201152

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30628/integ-telemetry-mc-k8s-tests_istio/1357572881193635840
