### ISSUE TITLE
TestProxyTracing test flake

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#30595]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30590/integ-telemetry-mc-k8s-tests_istio/1356680093484716032

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30628/integ-telemetry-mc-k8s-tests_istio/1357020390790008832

**Comment by adiprerepa** [comment]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30676/integ-telemetry-mc-k8s-tests_istio/1357498009159471104

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30628/integ-telemetry-mc-k8s-tests_istio/1357572881193635840

**Comment by GregHanson** [comment]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30575/integ-telemetry-mc-k8s-tests_istio_release-1.8/1357748260978036736

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30643/integ-telemetry-mc-k8s-tests_istio/1357126540197892096
