### ISSUE TITLE
Additional K8S compatibility tests

### ISSUE THREAD

**Issue by rshriram** [istio/istio#306]
1. Bookinfo with rolling deployments to make sure it works as is.
2. Bookinfo with pod autoscaler (give more containers to reviews v1, v2, v3) and scale out/in
2.1. Observe how evnoy is reacting to the term signals (and see if we need to setup a on-exit handler for our pods)
3. Add/remove labels from pod and see if they move in/out of LB pools properly.

**Comment by ldemailly** [comment]
it's an excellent test scenario to run but that testing can proceed without holding up the initial 0.2 release
