### ISSUE TITLE
 experimental to Alpha: Configuring Gateway Network Topology

### ISSUE THREAD

**Issue by jacob-delgado** [istio/istio#30608]
Configuring Gateway Network Topology is currently experimental. This is the checklist required to make sure that it can be elevated to Alpha.

The document can be found here: https://istio.io/latest/docs/ops/configuration/traffic-management/network-topologies/

This document outlines the requirements outlined at https://github.com/istio/community/edit/master/FEATURE-LIFECYCLE-CHECKLIST.md

## Alpha

A development feature can be officially labeled as Alpha once it meets the following
requirements:

- [x] Design
  - [x] Requires Approved RFC. - Not needed as it was approved in 1.6 and was approved in istio/api

- [x] Config
  - [x] Requires explicit user action to enable (e.g. a config field, config resource, or installation action).
    - [x] istio api: https://github.com/istio/api/pull/1394 and https://github.com/istio/api/pull/1403
    - [x] istio/istio: https://github.com/istio/istio/pull/23292

- [x] Docs
  - [x] Basic feature docs are published on istio.io describing what the feature does, how to use it, and any caveats.
    - [x] See https://istio.io/latest/docs/ops/configuration/traffic-management/network-topologies/

- [x] Tests
  - [x] Automated integration tests cover core use cases with the feature enabled. See https://github.com/istio/istio/pull/30500
  - [x] When disabled the feature does not affect system stability or performance.

- [ ] Performance
  - [ ] Performance impacts have been measured.

- [x] API
   - [x] Initial API review.

**Comment by howardjohn** [comment]
Should this be in https://github.com/istio/enhancements?

**Comment by jacob-delgado** [comment]
> Should this be in [istio/enhancements](https://github.com/istio/enhancements)?

Didn't know about that repo. Moving there.
