### ISSUE TITLE
TestAnalysisWritesStatus test flake

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#30600]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30599/integ-pilot-multicluster-tests_istio/1356742672915632128

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30590/integ-pilot-multicluster-tests_istio/1356811958719877120

cc @therealmitchconnors

**Comment by therealmitchconnors** [comment]
I don't see any indication of what went wrong in the logs.  Pilot appears to sit idle for 5 minutes, and then the test fails.  Strange that it's only happening in multicluster...

**Comment by therealmitchconnors** [comment]
Is it possible this is a race condition between the creation of the virtual service and the leader election?

**Comment by howardjohn** [comment]
sounds plausible

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30269/integ-pilot-multicluster-tests_istio/1356344062189244416

Interesting it seems correlated to other flakes

**Comment by howardjohn** [comment]
Hmm, actually its in a different testsuite though. So that would be strange to be correlated, unless the k8s node is busted or something...

**Comment by howardjohn** [comment]
if you look at istiod internal state, it has status: https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/30269/integ-pilot-multicluster-tests_istio/1356344062189244416/artifacts/pilot-analysis-e64cfecd45e241cc/TestAnalysisWritesStatus/_test_context/istio-state724947152/primary/istiod-7d84fcb66d-sxhmd_configz. I am not sure how it can end up there if we didn't write it...

**Comment by howardjohn** [comment]
actually, if the Reconciled lastTransitionTime is anything to be trusted, we write exactly 1s after the test times out, which seems odd.

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30638/integ-pilot-multicluster-tests_istio/1357163927879815168

another for more reference

**Comment by howardjohn** [comment]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30735/integ-pilot-multicluster-tests_istio/1358854524298596352
