### ISSUE TITLE
Search-and-replace header values by regex for VirtualServices

### ISSUE THREAD

**Issue by adamkgray** [istio/istio#30616]
**Describe the feature request**

Search-and-replace substrings for header values in a VirtualService

The use case is routing outside requests into the istio ingressgateway, and from the gateway rewrite the requests to another gateway but with a slightly different header that matches a pattern.

For example a bunch of services under a domain like `*.app.example.com`
They call into the cluster, and you want to route them to another gateway but reset the header value to `*.app.example.local` because that is the header which is accepted on that end.

You should be able to do a search and replace in the header before sending it off to the destination.

Something like:
```
header:
  key: host
  pattern: ^example\.com$
  replaceWith: example.local
```

**Describe alternatives you've considered**

right now I just explicitly name all the existing subdomains and handle them one by one

[ ] Docs
[ ] Installation
[X] Networking
[X] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by esnible** [comment]
@mandarjog This is a common request, as is rewriting the HTTP path based on a regex.  I don't think Envoy includes support for such rewrites.  This might make a good example of using Wasm.  I created a filter to do this and it is very simple.  The non-boilerplate is just:

``` C++
FilterHeadersStatus RegexpRepl::onRequestHeaders(uint32_t header_count, bool end_of_stream) {
  // TODO modify the request headers using the EnvoyFilter configuration instead of hard-coding
  char const *key = ":path";
  char const *pattern = "banana/([0-9]*)";
  char const *replaceWith = "status/$1";

  WasmDataPtr wdpGhmv = getRequestHeader(key);
  std::string sValue = wdpGhmv->toString();

  std::regex re(pattern);
  std::string result = std::regex_replace(sValue, re, replaceWith);
  WasmResult wrRrh = replaceRequestHeader(key, result);
  if (wrRrh == WasmResult::Ok) {
    logWarn("context_id:" + strId_ + " RegexpRepl::onRequestHeaders() replaced " + sValue + " with " + result);
  } else {
    logWarn("context_id:" + strId_ + " RegexpRepl::onRequestHeaders() replaceRequestHeader() FAILED.  wrRrh is " + toString(wrRrh));
  }

  return FilterHeadersStatus::Continue;
}
```

I tested it with httpbin.  Requests for `httpbin:8000/banana/418` were processed as `httpbin:8000/banana/418`.

What do you think about me making a sample or blog about this for Istio?

**Comment by esnible** [comment]
This seems to be a duplicate of #22290 .  Closing as a duplicate.

**Comment by kmai** [comment]
Hi, I'm the author of #22290. Even though it's slightly related (due to the rewrites), my request was to be able to rewrite paths using capture groups and regexes. 

I believe this should be treated as another component of the "rewrites" feature, but as a separate feature request.
