### ISSUE TITLE
Avoid useless context initiation before discovery server is ready.

### ISSUE THREAD

**Issue by SpecialYang** [istio/istio#30619]
Pilot has `configController` and `serviceController`. In so many services case,  when configController has synced before serviceController, configController will trigger some full push for context initiation which is useless because the discovery server is not ready and will not be connected by any data plane. Addition, when we solve so many services one by one, we still trigger full push, which is also useless. 

To avoid the above case, maybe we can just merge full push requests and do not execute `Push` method of discovery server until the discovery server is ready. The simple idea is following logic.
```
case r := <-ch:
	if len(r.Reason) == 0 {
		r.Reason = []model.TriggerReason{model.UnknownTrigger}
	}

       // Server should be ready
	if !opts.enableEDSDebounce && !r.Full && s.IsServerReady() {
		// trigger push now, just for EDS
		go pushFn(r)
		continue
	}

	lastConfigUpdateTime = time.Now()
	if debouncedEvents == 0 {
		timeChan = time.After(opts.debounceAfter)
		startDebounce = lastConfigUpdateTime
	}
	debouncedEvents++

	req = req.Merge(r)
case <-timeChan:
        // Server is not ready, delay it.
	if !s.IsServerReady() {
		timeChan = time.After(opts.debounceAfter)
	} else {
		if free {
			pushWorker()
		}
	}
```
Or, is the context initiation is useful before discovery server is ready? Thanks.

[ ] Docs
[ ] Installation
[ ] Networking
[X ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by howardjohn** [comment]
Generally the server is ready within 1-2s and the debounce will ensure we compute push context *at most* onec every 100ms. So are we just trying to avoid 10-20 computations, or is the scope here greater?

**Comment by SpecialYang** [comment]
If we have 1 thousand services with total about 100 thousand endpoints,  the server is ready within 1 min which may cause so many context initiation computations.

**Comment by howardjohn** [comment]
@SpecialYang got it. Are they not getting debounced? I would expect we get continual stream of events that computes every 10s (debounce is 100ms window to max of 10s).

Regardless, its probably a good idea to do this

**Comment by SpecialYang** [comment]
If we increase the interval, we will increase the delay of configuration change after the service is ready. I think it might be easier to merge push requests without debounce when the service is not ready. Or we can introduce another time interval and only use it before the service is ready.
