### ISSUE TITLE
Docker image 1.6.14 is missing in gcr.io registry 

### ISSUE THREAD

**Issue by GeckoSplinter** [istio/istio#30615]
**Bug description**

At least the version 1.6.14 is missing  in the gcr.io registry.

```
docker pull gcr.io/istio-release/proxyv2:1.6.14   
                                                                                                                                 
Error response from daemon: manifest for gcr.io/istio-release/proxyv2:1.6.14 not found: manifest unknown: Failed to fetch "1.6.14" from request "/v2/istio-release/proxyv2/manifests/1.6.14"
```
https://console.cloud.google.com/gcr/images/istio-release/GLOBAL
It's the same thing on the pilot part

That could help us with https://istio.io/latest/blog/2020/docker-rate-limit/

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[X ] Test and Release
[X] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

Docker image available

**Steps to reproduce the bug**

```
docker pull gcr.io/istio-release/proxyv2:1.6.14
```

**Version** 

1.6.14

**Comment by howardjohn** [comment]
Fixed, thanks. But also, FYI, Istio 1.6 is no longer supported: https://istio.io/latest/news/support/announcing-1.6-eol/

**Comment by GeckoSplinter** [comment]
Thanks a lot @howardjohn.
Yes we are working on it.
