### ISSUE TITLE
perTryTimeout documentation inconsistencies 

### ISSUE THREAD

**Issue by etifontaine** [istio/istio#30611]
**Bug description**

In the Istio documentation it is specified `Timeout per retry attempt for a given request` for the `perTryTimeout` in a VirtualService.
By reading the Envoy doc/code and even with some tests done on my side, I would say it’s more Timeout per try which include the initial call.
What do you think ? Should we update the doc or am I understanding something wrong ?

[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

Documentation should be updated to reflect the actual behaviour on Envoy.

**Comment by howardjohn** [comment]
So if we have 3 attempts: request, retry1, retry2
The docs imply retry applies only to retry1, retry2
Code actually has it apply to all  request, retry1, retry2

Is that correct?

I would agree its a bit ambiguous in the docs right now, could use a tweak

**Comment by etifontaine** [comment]
Yes that is what I have figured out. Also, the Envoy doc https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/router_filter#x-envoy-upstream-rq-per-try-timeout-ms

**Comment by etifontaine** [comment]
@howardjohn am I supposed to update the [istio/api doc](https://github.com/istio/api/blob/master/networking/v1beta1/virtual_service.proto#L1542), so it will update the doc automatically?
