### ISSUE TITLE
Add checks for istiod non-determinism

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#30624]
We should add some sort of testing around determinism of Istiod instances. This would help us catch bugs like https://github.com/istio/istio/issues/28861 or various race conditions we have had leading to some istio's missing an event or computing push context or caches incorrectly.

Strawman proposal:
Write an ADSC client that finds all Istiod pods, and directly connects to each one. Connect to all of them and compare the responses. Ideally, we compare the raw proto bytes - not sure if that is possible with grpc client though. We also likely want to impersonate real pods, as the response may be different for different pods. We will need some resilience to different responses to handle eventual consistency.

cc @mandarjog

**Comment by mandarjog** [comment]
A check like this is needed. 
1. I don’t think we can compare bytes, since maps have multiple valid encodings.
2. Ordered lists and unordered lists should be treated separately.
3. Envoy does sophisticated diffing, perhaps using envoy is a better option here. We can force envoy to connect to different istiods in a round robin way.

I am trying to see when a check like this should be applied. As described it is a monitoring process either in prod or test.

We know that Ordering maps and unordered lists is the way to fix this, is there a more code centric way of achieving it?

**Comment by howardjohn** [comment]
I _think_  https://pkg.go.dev/github.com/golang/protobuf/proto#Buffer.SetDeterministic, which we set, handles these issues?

**Comment by howardjohn** [comment]
The real check we need is Envoy's hashing:
```
314-size_t MessageUtil::hash(const Protobuf::Message& message) {
315-  std::string text_format;
316-
317-  {
318-    Protobuf::TextFormat::Printer printer;
319-    printer.SetExpandAny(true);
320-    printer.SetUseFieldNumber(true);
321-    printer.SetSingleLineMode(true);
322-    printer.SetHideUnknownFields(true);
323-    printer.PrintToString(message, &text_format);
324-  }
325-
326:  return HashUtil::xxHash64(text_format);
327-}

```

if the implementation is identical we might be able to use `proto.TextMarshaler{ExpandAny: true}`. The benefit of this is its closer to what envoy cares about and stable across Istiod versions - SetDeterministic requires the exact same binary to run (although its stable across instances). We can try both and compare results.

**Comment by mandarjog** [comment]
I don’t think set deterministic is going to reorder a list. Since there is no way to tell repeated ( unordered ) to proto, but we know that some orders do not matter.

**Comment by howardjohn** [comment]
A re-ordered list is exactly the type of thing we *want* to catch with this test. Even if envoys matching logic doesn't care about order, its hashing *does*. So its a less critical bug to send in a different order in these cases, but will still cause drains which is pretty big issue I think.

**Comment by adiprerepa** [comment]
How would you impersonate a "real" pod?

**Comment by howardjohn** [comment]
I added this to https://github.com/howardjohn/pilot-load. I think it found a real bug already, need to investigate more. If you want to try it out, run `kubectl apply install/sleep-deployment.yaml` then run `pilot-load determinsm` inside of the pod

**Comment by howardjohn** [comment]
```
2021-02-05T23:43:38.150284Z     info    FAIL: echo-7d9c9857cd-5sw8f.echo: proto diff:   (*envoy_config_endpoint_v3.ClusterLoadAssignment)(Inverse(protocmp.Transform, protocmp.Message{
        "@type":        s"envoy.config.endpoint.v3.ClusterLoadAssignment",
        "cluster_name": string("outbound|8080||vm.default.svc.cluster.local"),
        "endpoints": []protocmp.Message{
                {
                        "@type": s"envoy.config.endpoint.v3.LocalityLbEndpoints",
                        "lb_endpoints": []protocmp.Message{
                                {
                                        "@type": s"envoy.config.endpoint.v3.LbEndpoint",
                                        "endpoint": protocmp.Message{
                                                "@type": s"envoy.config.endpoint.v3.Endpoint",
                                                "address": protocmp.Message{
                                                        "@type": s"envoy.config.core.v3.Address",
                                                        "socket_address": protocmp.Message{
                                                                "@type":      s"envoy.config.core.v3.SocketAddress",
-                                                               "address":    string("10.128.0.55"),
+                                                               "address":    string("10.128.0.54"),
                                                                "port_value": uint32(8080),
                                                        },
                                                },
                                        },
                                        "load_balancing_weight": protocmp.Message{"@type": s"google.protobuf.UInt32Value", "value": uint32(1)},
                                        "metadata":              protocmp.Message{"@type": s"envoy.config.core.v3.Metadata", "filter_metadata": map[string]protocmp.Message{"envoy.transport_socket_match": {"@type": s"google.protobuf.Struct", "fields": map[string]protocmp.Message{"tlsMode": {"@type": s"google.protobuf.Value", "string_value": string("istio")}}}}},
                                },
                                {
                                        "@type": s"envoy.config.endpoint.v3.LbEndpoint",
                                        "endpoint": protocmp.Message{
                                                "@type": s"envoy.config.endpoint.v3.Endpoint",
                                                "address": protocmp.Message{
                                                        "@type": s"envoy.config.core.v3.Address",
                                                        "socket_address": protocmp.Message{
                                                                "@type":      s"envoy.config.core.v3.SocketAddress",
-                                                               "address":    string("10.128.0.54"),
+                                                               "address":    string("10.128.0.55"),
                                                                "port_value": uint32(8080),
                                                        },
                                                },
                                        },
                                        "load_balancing_weight": protocmp.Message{"@type": s"google.protobuf.UInt32Value", "value": uint32(1)},
                                        "metadata":              protocmp.Message{"@type": s"envoy.config.core.v3.Metadata", "filter_metadata": map[string]protocmp.Message{"envoy.transport_socket_match": {"@type": s"google.protobuf.Struct", "fields": map[string]protocmp.Message{"tlsMode": {"@type": s"google.protobuf.Value", "string_value": string("istio")}}}}},
                                },
                        },
                        "load_balancing_weight": protocmp.Message{"@type": s"google.protobuf.UInt32Value", "value": uint32(2)},
                        "locality":              protocmp.Message{"@type": s"envoy.config.core.v3.Locality"},
                },
        },
  }))

```

I think EDS order doesn't actually impact things, looking into it

**Comment by adiprerepa** [comment]
wow, `pilot-load` is convenient

**Comment by howardjohn** [comment]
https://github.com/istio/istio/pull/31045 does essentially the same thing internally, but only works for cached types
