### ISSUE TITLE
istioctl x create-remote-secret createsinvalid certificate chain

### ISSUE THREAD

**Issue by libesz** [istio/istio#30625]
**Bug description**
After the merge of https://github.com/istio/istio/pull/30565 , the `istioctl x create-remote-secret` step in the guide [here](https://istio.io/latest/docs/setup/additional-setup/external-controlplane/#set-up-the-control-plane-in-the-external-cluster) command succeeded in my environment (unmodified, managed RedHat OpenShift cluster 4.5 on IBM Cloud). I proceeded with the creation of the istiod deployment which would connect to the remote cluster's K8S API, but it failed to start up due to this error:
```
2021-02-03T14:00:55.453091Z	error	kube	failed to list CRDs: Get "https://****/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions": x509: certificate signed by unknown authority
```
That means, the `istioctl x create-remote-secret` produced an invalid certificate chain in the remote secret.
I believe the mentioned PR did not change any such secret creation details.
I've downloaded the secret, converted into the KUBECONFIG and my manual `kubectl` commands also failed with the same reason.
I managed to extract the certificate chain from both the generated (external control plane) side and from the originating (remote) cluster side. The difference is the following:
* The original remote secret has two items for CA certs: `ca.crt` and `service-ca.crt`.
* `service-ca.crt` is starting with the same content as `ca.crt` but contains a few more items.
* The resulted Kubeconfig in the secret, on the external control plane cluster has a single `certificate-authority-data`, holding the exact copy of the `ca.crt`.  The `service-ca.crt` part is not copied over.

I altered the generated KUBECONFIG secret to have `insecure-skip-tls-verify: true` instead of the CA data and it resolved the issue (both . This is obviously not a good practice, but I can confirm this is the issue with the cert generation.

Changing the CA data manually to the exact content of the `service-ca.crt` from the remote side did not resolve the issue.

[ ] Docs
[x] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**
Follow the multicluster installation as described above.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
1.8.2 with `istioctl` compiled from the master, having https://github.com/istio/istio/pull/30565

**How was Istio installed?**
Multi-cluster installation, following this guide: https://istio.io/latest/docs/setup/additional-setup/external-controlplane/#set-up-the-control-plane-in-the-external-cluster

**Environment where the bug was observed (cloud vendor, OS, etc)**
IBM Cloud, managed OpenShift 4.5

I am happy to collect further symptoms if needed, as the issue is reproducible in my environment.

**Comment by linsun** [comment]
@knrc @dgn could you shed some light on this?  Is there anything unique from openshift that prevents create-remote-secret cmd not working?  Note: in external istiod env, there is no istiod on the data plane cluster.

**Comment by libesz** [comment]
New findings from my side:
* The K8S API certs in my environment are fully qualified (is this the right wording?). If I remove the CA data from the generated secret at all (and also remove the insecure flag), it also works.
* If I create a pod on the dataplane to use the same service account which is used to generate the secret on the external control plane, it also works, meaning the original token secret is fine.

**Comment by stevenctl** [comment]
@libesz Is this still an Istio bug then?

**Comment by libesz** [comment]
@stevenctl most probably yes, but I don't need/use this remote secret command anymore, that's why I am not pushing it actively. Happy to test and give you symptoms from my OpenShift environment if needed for debugging.

**Comment by stevenctl** [comment]
Some more exact reproduction steps would be helpful.
