### ISSUE TITLE
Support for health-checking of Ingress/Gateway

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#3063]
This is required for the deployment scenario when Istio Ingress or Gateway are located behind another Load Balancer who performs health checks on its backends.

**Comment by andraxylia** [comment]
@ZackButcher you were working on this one, have you made any progress?

**Comment by duderino** [comment]
@ZackButcher are you looking at this or should we find a new owner for 1.1 (Nov 2018 before Thanksgiving)?

**Comment by munrodg** [comment]
@nmittler you able to take a look at this issue?

**Comment by nmittler** [comment]
@mandarjog isn't this the same as just adding health checking to pilot-agent/Envoy?

**Comment by mandarjog** [comment]
@nmittler yes it is. We should be mostly done here, proxy-agent readiness should suffice this requirement. It should be a matter of testing this feature and helm chart updates.

**Comment by nmittler** [comment]
@mandarjog @PiotrSikora My main concern is that we have the metrics we need in Envoy. 

See the table in the `Liveness` section: https://docs.google.com/document/d/1jC0a2ku8-e3a7uMIc39HbMFbD4eh8JqWh-NFuLZSOwk/edit#heading=h.an3m8yo3ehje. 

Specifically `failedRequests` and `totalRequests` need to be accounted for.

Also, this doc has been out there a while ... are we even happy with the liveness calculation?

**Comment by nmittler** [comment]
@mandarjog @PiotrSikora I've updated the [Liveness section of the design doc](https://docs.google.com/document/d/1jC0a2ku8-e3a7uMIc39HbMFbD4eh8JqWh-NFuLZSOwk/edit?ts=5bef7197#heading=h.an3m8yo3ehje).  I'm now calling out specific Envoy stats that are being collected. Please review.

cc @duderino @costinm

**Comment by nmittler** [comment]
Actually, looks like I misread https://github.com/istio/istio/issues/3063#issuecomment-439257309 ... we only need readiness for this. The updated liveness changes still need some discussion ... but it won't stop work on this issue.

**Comment by duderino** [comment]
@knrc will test this on openshift.  Thanks Kevin!

**Comment by nmittler** [comment]
@knrc @duderino is this still targeted for 1.1?

**Comment by knrc** [comment]
@nmittler I'm still expecting it to be for 1.1, we've just updated our openshift integration to support a recent snapshot from the release-1.1 branch so I can now test this works in our environment.  I'll handle it on Monday when I return from my travels.

**Comment by nmittler** [comment]
@knrc sounds good ... thanks for the update!

**Comment by dawidmalina** [comment]
https://github.com/istio/istio/pull/11548 will not cover external load balancer as we need to expose this port with istio-ingressgateway service.
