### ISSUE TITLE
Auth policy - deny all is allowing external traffic?

### ISSUE THREAD

**Issue by ceastman-ibm** [istio/istio#30631]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
```
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
 name: deny-all
 namespace: mynamespace
spec:
  {}
```
but when i exec into a pod in mynamespace, curl https://www.google.com still works

my environment is istio 1.8.2 i seem to recall this deny-all policy used to work in older versions of istio.

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
RBAC: access denied to www.google.com

**Steps to reproduce the bug**
install the deny-all authorization policy.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
istio version 1.8.2 and istio 1.7.4, i havent tried other versions.

**How was Istio installed?**
istioctl install

**Environment where the bug was observed (cloud vendor, OS, etc)**
ibm cloud kubernetes and ibm cloud openshift

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
AuthorizationPolicy is ingress policy. Istio does not have egress policy

**Comment by ceastman-ibm** [comment]
@howardjohn the authorization policy also seems to control internal service mesh connections.

**Comment by ceastman-ibm** [comment]
@howardjohn is there another mechanism to control egress traffic at a microservice level? for example:

microservice A can get to www.google.com but
microservice B can not
and they are in the same namespace with istio installed.

**Comment by howardjohn** [comment]
https://cloud.google.com/service-mesh/docs/security/egress-gateway-gke-tutorial may help. Its technically GCP specific but I find it more complete than the istio.io docs (we are planning to rehaul those) - the concepts should apply everywhere.

tl;dr you must use egress gateway

**Comment by ceastman-ibm** [comment]
@howardjohn looks like the key is the sidecar resource. thank you for the tip.
