### ISSUE TITLE
Add XDS authn/authz benchmark tests

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#30637]
We have existing benchmarks here: https://github.com/istio/istio/blob/9a972ab4190c2da7c3e0134770bb8313c06e3826/pilot/pkg/xds/bench_test.go#L64
We should add some for Authn/Authz policies. This benchmarks the XDS control plane performance

**Comment by adiprerepa** [comment]
so are we benchmarking the time it takes for the control plane to authenticate/authorize something?

**Comment by howardjohn** [comment]
Ah, pretty vague title. I meant https://istio.io/latest/docs/reference/config/security/peer_authentication/ and https://istio.io/latest/docs/reference/config/security/authorization-policy/

**Comment by howardjohn** [comment]
And the cost to generate the XDS config for those types - just like we have similar ones for large numbers of gateways, etc

**Comment by adiprerepa** [comment]
We can close this I think
