### ISSUE TITLE
Envoy outlier detection  max_ejection_time breaks backward compatibility 

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#30649]
Envoy 1.17:`added max_ejection_time to limit ejection time growth when a node stays unhealthy for extended period of time. By default max_ejection_time limits ejection time to 5 minutes. `

If user previously set outlierDetection.BaseEjectionTime>5m, it would make envoy send NACK to cds.

In #30602, we manually set the max_ejection_time = base_ejection_time if base_ejection_time > 5m. According to https://github.com/istio/istio/pull/30602#discussion_r569607709

We may:

-  add a new max_ejection_time to destinationRule
- make the max_ejection_time equal to base or something higher (n*base)

**Comment by hzxuzhonghu** [comment]
@istio/wg-networking-maintainers Need your advice

**Comment by ramaraochavali** [comment]
I think we should check with Envoy on why max_ejection_time has to be enforced if it is not provided. I have asked that question here https://github.com/envoyproxy/envoy/pull/14235#issuecomment-773221219. Let us see the response and we can decide based on that.

**Comment by ramaraochavali** [comment]
Envoy PR to fix this https://github.com/envoyproxy/envoy/pull/14962. Let wait till that is merged and I have also requested for backport to 1.17 once that is done, we should probably upgrade Envoy in 1.9 and revert the other change.
