### ISSUE TITLE
core dumps not available in CIs

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#3064]
follow up from https://github.com/istio/istio/pull/2859/files/a2161fc50d0050bdbaa7557e834a047cbabbc552#r164282513

and https://github.com/istio/istio/issues/2906#issuecomment-361426521

it's important to gather core dump and show it working (and possibly add a test so that debugability feature doesn't regress)

**Comment by ldemailly** [comment]
have we seen at least 1 envoy core dump in some linkable build artefact so we know this is fixed indeed?

**Comment by ldemailly** [comment]
see also https://github.com/istio/issues/issues/196 for user question on whether/how it works

**Comment by hklai** [comment]
Closing this in favor of https://github.com/istio/istio/issues/6245 which has more info and is newer.

**Comment by ldemailly** [comment]
typically we keep the oldest/original issue in case of dup but ok

**Comment by hklai** [comment]
As I mentioned the new one has more info. =)
