### ISSUE TITLE
'istioctl proxy-status' takes 30s when falling back from proxy-status to exec implementation strategy

### ISSUE THREAD

**Issue by esnible** [istio/istio#30646]
If port 15014 is firewalled, _istioctl_ will attempt to proxy to the control plane, wait 30 seconds to timeout, then use _exec_.

For most users, 15014 is open and this is faster than using exec.  It also requires less permissions.  The 30 seconds timeout is much to long.

Discuss:
- Use a much shorter timeout (5s?)
- Have an `--mode=exec` option to skip the proxy and go directly to exec.  Allow users with 15014 blocked to configure this in their istioctl.cfg file.

**Comment by dex4er** [comment]
I think it should be mentioned at https://istio.io/latest/docs/setup/platform-setup/gke/ that port 15014 should be opened for `istioctl x` and port 8080 for kiali.

**Comment by esnible** [comment]
To reproduce,

``` bash
time istioctl ps
kubectl apply -f - <<EOF
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: no-15014
  namespace: istio-system
spec:
  podSelector:
    matchLabels:
      app: istiod
  policyTypes:
  - Ingress
  ingress:
  - ports:
    - protocol: TCP
      port: 15010
    - protocol: TCP
      port: 15012
    # DONT INCLUDE 15014, thus it will be blocked
    # - protocol: TCP
    #  port: 15014
EOF
time istioctl ps
kubectl -n istio-system delete networkpolicy no-15014
time istioctl ps
```

5 sec seems small, as the first time in the morning it took me ~15 seconds the usual way.  (Subsequent attempts took 0.4sec)

I'm thinking of cutting the timeout to 15 seconds, and adding `--mode=method[,method]*`

The methods will be `port-forward` and `exec`.  The default will be `port-forward,exec`.  The user will be able to put this in a config file that _istioctl_ will pick up using Viper.

In the future, we will merge the code in `experimental proxy-status` allowing the method `xds`.
In the future, we will have a new method, `pilot-agent`, that will contact the sidecar.

@howardjohn Does this plan seem reasonable?

**Comment by howardjohn** [comment]
Isn't there 3 modes? port-forward, exec, and proxyGet? We use proxyGet today - i am not actually sure port-forward has the same issues
