### ISSUE TITLE
Suppressed TCP keepalive in 1.6.12 and 1.8.2

### ISSUE THREAD

**Issue by juergen-kaiser-by** [istio/istio#30658]
**Bug description**

Our service runs in a Kubernetes 1.18.10 cluster and performs operations on some other Kubernetes 1.18.10 cluster. The service tries to use TCP keepalive. However, we observe that the service does not send TCP keepalive messages if we use the Istio sidecar proxy. If we remove the Istio sidecar proxy then the service sends those messages. 

For analysis we traced all tcp packets in the pod by running `tcpdump -ni eth0 -C 15 -w <file> <other k8s ip>` and compared the output with wireshark. We saw no keepalive messages with enabled sidecar proxy. With removed sidecar, we saw keepalive messages. We also checked the performed system calls with `strace` and saw that in both cases the service sets the same TCP keepalive parameters.  

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

We would like to use tcp keepalive and expect that the tcp keepalive mechanism is not blocked/supressed. 

**Steps to reproduce the bug**

We use a simple go program that enlists the pods of the target k8s cluster, waits for five minutes, and finally lists them again. The `client-go` library activates TCP keepalive for new connections and keeps the connections open for some minutes before closing them proactively. See the attached file for the source code and the used library version ( [example.tar.gz](https://github.com/istio/istio/files/5925942/example.tar.gz) ).

Steps to reproduce it:
- Get a k8s cluster and install Istio. Ensure that proxy sidecar gets injected.
- Start a pod including the compiled example program (privileged pod if you want to trace tcp traffic with `tcpdump`)
- Run the example
- Check tcpdump 

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```
$ istioctl version --remote
client version: 1.8.2
control plane version: 1.8.2
data plane version: 1.8.2 (32 proxies)
```
We also observed the behavior in `1.6.12`

```
$ kubectl version --short
Client Version: v1.19.3
Server Version: v1.18.10
```

**How was Istio installed?**

~~helm charts~~ istioctl

**Environment where the bug was observed (cloud vendor, OS, etc)**
Cloud vendor: `Azure`
Kubernetes: `1.18.10` (Azure AKS cluster)
VM: (copied from Azure portal)
```
Publisher: microsoft-aks  
Offer: aks  
SKU: aks-ubuntu-1804-2021-q1  
Version: 2021.01.06  
```
service container is based on docker image `debian:stretch-slim`. We also tried an image using the same ubuntu version as the VM.

**Comment by juergen-kaiser-by** [comment]
Does anyone have an idea? As a workaround, we tried to activate tcp keepalives globally, but when we specified it in https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/ then we saw no effect.

We successfully activated tcp keepalives by creating a VirtualService+DestinationRule and seting the tcpKeepalive options for them. However, we do not know all possible destinations in advance, so this is a suboptimal solution. :-/

**Comment by cezarsa** [comment]
> Does anyone have an idea? As a workaround, we tried to activate tcp keepalives globally, but when we specified it in https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/ then we saw no effect.

For someone finding this issue in the future, I believe the global tcp keepalive config was fixed in https://github.com/istio/istio/pull/36532.
