### ISSUE TITLE
istio 1.8.2 pilot failed to patch istio-sidecar-injector webhook when istio is installed with revision

### ISSUE THREAD

**Issue by arief-hidayat** [istio/istio#30656]
**Bug description**
Error log in istiod
```
Patch webhook failed: mutatingwebhookconfigurations.admissionregistration.k8s.io "istio-sidecar-injector" not found
```

[ ] Docs
[x] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[x ] Upgrade

**Expected behavior**
istiod should patch istio-sidecar-injector webhook.

**Steps to reproduce the bug**

Install istio 1.8.2 with revision
```
spec:
  profile: minimal
  tag: 1.8.2-distroless
  revision: 1-8-2-0
...
```
https://github.com/istio/istio/blob/1.8.2/pilot/pkg/bootstrap/sidecarinjector.go#L35 hardcode the name.
while the helm chart add revision to the name 
https://github.com/istio/istio/blob/1.8.2/manifests/charts/istio-control/istio-discovery/templates/mutatingwebhook.yaml#L7

```
kubeconfigs % k get mutatingwebhookconfigurations | grep istio                       
istio-sidecar-injector-1-8-2-0                    2021-02-04T07:05:06Z
```
**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
 kubeconfigs % istioctl version --remote
no running Istio pods in "istio-system"
1.7.3
data plane version: 1.8.2 (4 proxies)
kubeconfigs % kubectl version --short
Client Version: v1.19.0
Server Version: v1.16.15
 kubeconfigs % helm version --short
v3.2.1+gfe51cd1
```

**How was Istio installed?**

via istio-operator.

**Environment where the bug was observed (cloud vendor, OS, etc)**
SAP Gardener kubernetes 1.16.15 on top of AWS.

**Comment by Monkeyanator** [comment]
Thanks for the report! I'm not able to reproduce this using the operator install. I believe the hardcoded name posted above is eventually turned into the `istio-sidecar-injector-<revision>` name in the controller later. Could you post the result of `kubectl describe deployment istiod-1-8-0-2 -n istio-system`?

**Comment by arief-hidayat** [comment]
sorry. I found one issue from our side upon installing istio-operator. basically we don't set the tag so it take latest image.
I will try to see if can reproduce above issue after fixing this.

**Comment by arief-hidayat** [comment]
the error logs is gone after I use correct operator image tag. thanks
