### ISSUE TITLE
Gateways don't use the global tracing parameter used correctly by the mesh sidecars (istio 1.6.12)

### ISSUE THREAD

**Issue by bvandewalle** [istio/istio#30665]
**Bug description**

We are using our own Zipkin endpoint, and configured it as a global value, as well as choosing zipkin as the default tracer.

We are getting traces correctly from the mesh sidecars, but not from the gateway.
After dumping Envoy's config, it boils down to the bootstrap config for the Gateway not being configured correctly with the zipkin tracing endpoint

On the Mesh, configured correctly (`zipkin-collector.monitoring`):
```
                {
                    "name": "zipkin",
                    "type": "STRICT_DNS",
                    "connectTimeout": "1s",
                    "hosts": [
                        {
                            "socketAddress": {
                                "address": "zipkin-collector.monitoring",
                                "portValue": 9411
                            }
                        }
                    ],
                    "dnsRefreshRate": "300s",
                    "dnsLookupFamily": "V4_ONLY"
                }
```

On the gateway (using `zipkin.istio-system`):
```
            "clusterName": "zipkin",
            "endpoints": [
                {
                    "lbEndpoints": [
                        {
                            "endpoint": {
                                "address": {
                                    "socketAddress": {
                                        "address": "zipkin.istio-system",
                                        "portValue": 9411
                                    }
                                }
                            }
                        }
                    ]
                }
            ]
```

We resolved this issue in a hacky way, by adding a PROXY_CONFIG env variable to the gateway that contains this configuration:

```
    - name: PROXY_CONFIG
      value: |
        {"tracing":{"zipkin":{"address":"zipkin-collector.monitoring:9411"}},"proxyMetadata":{"DNS_AGENT":""}}
```

This seems to work, but surely there must be a better way? Are we missing a parameter in the global values?

I found other similar issues with no clear resolution: https://discuss.istio.io/t/zipkin-address-not-consistent-between-gateway-and-proxy/7069
and the follow up for this one: 
https://github.com/istio/istio/issues/24666

[ ] Docs
[X] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

Expecting to have the ingress gateway use the same tracing endpoint.

**Version** 
Istio 1.16.12

**Comment by howardjohn** [comment]
Is the gateway running in istio-system? There is an issue with non istio-system gateways currently where the configuration in mesh config is not propogated - see https://github.com/istio/istio/issues/27265 for more info

**Comment by bvandewalle** [comment]
it is indeed not running in istio-system

**Comment by lindsaygrace** [comment]
@howardjohn We're having the same issue as well, even though all our gateways are in istio-system. With gateways using zipkin.istio-system while all our envoy proxies are using the correct address. For now, we've worked around it using bvandewalle's 'solution'.

For reference, our config is

`profile: default
  meshConfig:
    accessLogFile: /dev/stdout
    accessLogEncoding: JSON
    enableTracing: true
    defaultConfig:
      tracing:
        sampling: 100
      sds:
        enabled: true

  values:
    pilot:
      traceSampling: 100
    global:
      proxy:
        autoInject: disabled
      logAsJson: true
      tracer:
        zipkin:
          address: jaeger-collector.observability.svc.cluster.local:9411

  components:
    pilot:
      enabled: true
      k8s:
        hpaSpec:
          minReplicas: '2'
          maxReplicas: '10'
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          serviceAnnotations:
            service.beta.kubernetes.io/aws-load-balancer-type: nlb
            service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '350'
            service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
          hpaSpec:
            minReplicas: '2'
            maxReplicas: '10'
          resources:
            requests:
              memory: 400Mi
          env:
            - name: TERMINATION_DRAIN_DURATION_SECONDS
              value: '350'
            - name: PROXY_CONFIG
              value: |
                {"tracing":{"zipkin":{"address":"jaeger-collector.observability.svc.cluster.local:9411"}},"proxyMetadata":{"DNS_AGENT":""}}
          overlays:
            - apiVersion: apps/v1
              kind: Deployment
              name: istio-ingressgateway
              patches:
                - path: spec.template.spec.terminationGracePeriodSeconds
                  value: 350
      - name: cluster-local-gateway
        enabled: true
        label:
          istio: cluster-local-gateway
          app: cluster-local-gateway
        k8s:
          hpaSpec:
            minReplicas: '2'
            maxReplicas: '10'
          resources:
            requests:
              memory: 400Mi
          env:
            - name: TERMINATION_DRAIN_DURATION_SECONDS
              value: '350'
            - name: PROXY_CONFIG
              value: |
                {"tracing":{"zipkin":{"address":"jaeger-collector.observability.svc.cluster.local:9411"}},"proxyMetadata":{"DNS_AGENT":""}}
          service:
            type: ClusterIP
            ports:
              - port: 15020
                name: status-port
              - port: 80
                targetPort: 8080
                name: http2
              - port: 443
                targetPort: 8443
                name: https
          overlays:
            - apiVersion: apps/v1
              kind: Deployment
              name: cluster-local-gateway
              patches:
                - path: spec.template.spec.terminationGracePeriodSeconds
                  value: 350`

**Comment by liorfranko** [comment]
Same issue
Resolved by adding
`- name: PROXY_CONFIG
              value: |
                {"tracing":{"zipkin":{"address":"jaeger-collector.observability.svc.cluster.local:9411"}}}`

**Comment by bianpengyuan** [comment]
@lindsaygrace @liorfranko I think your issue is different from the original post. Please use the `tracing` field inside ProxyConfig: https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#ProxyConfig to make it consistently configured across sidecar and gateways. It will be something like:

```
  meshConfig:
    accessLogFile: /dev/stdout
    accessLogEncoding: JSON
    enableTracing: true
    defaultConfig:
      tracing:
        sampling: 100
        zipkin:
          address: xxx
```

**Comment by liorfranko** [comment]
I already tried configure it in meshConfig.
It works for Sidecars but not for Ingress-GW.
I forgot to mention that I use istio 1.9
