### ISSUE TITLE
Failed to deploy a stateless service in 1.9.0-rc0. Result - rs fails, pod is not created

### ISSUE THREAD

**Issue by tampler** [istio/istio#30667]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
When I try to deploy my stateless service, I'm getting the following error:
```
[ansible@grant-01 distance]$ kg describe rs/distance-7598b64bb6
```
  Warning  FailedCreate  25s (x15 over 107s)  replicaset-controller  Error creating: admission webhook "sidecar-injector.istio.io" denied the request: failed to run injection template: failed parsing generated injected YAML (check Istio sidecar injector configuration): unmarshal patched pod: json: cannot unmarshal number into Go struct field ObjectMeta.metadata.labels of type string.

This `replicaSet` fails and the app pod is never created. However, the very same setup works seamlessly for `istio 1.8.2`

The working namespace `grant` is surely labeled:
```
[ansible@grant-01 distance]$ k describe ns grant
Name:         grant
Labels:       istio-injection=enabled
Annotations:  <none>
Status:       Active
```

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[X] Test and Release
[X] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
The service should deployed successfully the same way as it is in `istio 1.8.2`

**Steps to reproduce the bug**
kubectl -n abc apply -f deploy.yml

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
Kuber: 1.20.2

Istio:
client version: 1.9.0-rc.0
control plane version: 1.9.0-rc.0
data plane version: 1.9.0-rc.0 (3 proxies)

**How was Istio installed?**

1. Download the `istio-1.9.0-rc.0` release
2. istioctl install --set profile=demo

**Environment where the bug was observed (cloud vendor, OS, etc)**
Bare metal CentOS 7: Linux grant-01.dtln 3.10.0-1160.11.1.el7.x86_64 #1 SMP Fri Dec 18 16:34:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

[bug-report.gz](https://github.com/istio/istio/files/5927372/bug-report.gz)

**Comment by howardjohn** [comment]
Thank you for the report! I have identified the issue, will send a fix in a minute. we just need o quote the labels
