### ISSUE TITLE
istioctl x version shows MISSING CP ID

### ISSUE THREAD

**Issue by dex4er** [istio/istio#30661]
**Bug description**

[ ] Docs
[x] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

I expect correct output that I have already for non-x commands:

`istioctl version`:

```
client version: 1.8.2
control plane version: 1.8.2
data plane version: 1.8.2 (5 proxies)
```

(but I have to admit it takes too long: 1m1.683s)

`istioctl proxy-status`

```
NAME                                                   CDS        LDS        EDS        RDS        ISTIOD                      VERSION
apache-example-5c8df5fc78-zxglk.example                SYNCED     SYNCED     SYNCED     SYNCED     istiod-69ff48c887-m78mj     1.8.2
echoserver-5c9677587d-4l8sb.echoserver                 SYNCED     SYNCED     SYNCED     SYNCED     istiod-69ff48c887-m78mj     1.8.2
echoserver-5c9677587d-4zt8f.echoserver                 SYNCED     SYNCED     SYNCED     SYNCED     istiod-69ff48c887-m78mj     1.8.2
echoserver-5c9677587d-b4gd5.echoserver                 SYNCED     SYNCED     SYNCED     SYNCED     istiod-69ff48c887-m78mj     1.8.2
istio-ingressgateway-794bbdb877-srfbb.istio-system     SYNCED     SYNCED     SYNCED     SYNCED     istiod-69ff48c887-m78mj     1.8.2
```

(the same: very slow output: 30.885s)

**Steps to reproduce the bug**

New GKE cluster. istio installed with simple `istioctl install` or with `helm` (no difference).

`istioctl x version` shows:

```
client version: 1.8.2
control plane version: MISSING CP ID
data plane version: 1.8.2 (6 proxies)
```

`istioctl x proxy-status` shows:

```
NAME                                                   CDS        LDS        EDS        RDS        ISTIOD      VERSION
apache-example-5c8df5fc78-zxglk.example                SYNCED     SYNCED     SYNCED     SYNCED     MISSING     MISSING CP ID
echoserver-5c9677587d-4l8sb.echoserver                 SYNCED     SYNCED     SYNCED     SYNCED     MISSING     MISSING CP ID
echoserver-5c9677587d-4zt8f.echoserver                 SYNCED     SYNCED     SYNCED     SYNCED     MISSING     MISSING CP ID
echoserver-5c9677587d-b4gd5.echoserver                 SYNCED     SYNCED     SYNCED     SYNCED     MISSING     MISSING CP ID
istio-ingressgateway-794bbdb877-srfbb.istio-system     SYNCED     SYNCED     SYNCED     SYNCED     MISSING     MISSING CP ID
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

1.8.2

**How was Istio installed?**

`istioctl install`. Installed with Helm is with the same behaviour.

**Environment where the bug was observed (cloud vendor, OS, etc)**

GKE private cluster. Additional firewall setting for port 15017. Cluster runs 2 demo apps: Apache and simple echoserver. Additional services: cert-manager, netdata, prometheus, kiali, reflector are running without sidecars.

**Comment by howardjohn** [comment]
cc @esnible 

We were just discussing this yesterday (the delay) - it seems the fallback istioctl code when we cannot reach istiod (because you have a firewall rule denying port 15014) is timing out in 30s rather than immdiately. This is almost certainly the cause of the 30s/1min delay, but its plausible this also causes the MISSING

**Comment by dex4er** [comment]
Ah yeah I found some another issue and it looks like GKE needs additional tweak on firewall for port 15014.

It helped with `istioctl proxy-status` and `istioctl version` and they're fast now.

But it didn't change anything for `istioctl x` commands and this output with "MISSING CP ID" is the same.

Once I've got additional message after `istioctl x version`:

```
2021-02-04T22:05:50.203522Z     error   klog    error copying from local connection to remote stream: tls: use of closed connection[]
```

but I can't reproduce it anymore.

**Comment by esnible** [comment]
Thanks for reporting this.

I missed this because I test on daily builds, which don't have the version.

The server-side code was originally at https://github.com/istio/istio/commit/210f8118b66c2138ff75ecef89e9b2f478990075#diff-d8db81c59e93467dfd0c254bfd2401877892cff9be76db920f513cf65c697cddR71 and was lost during a refactor.
