### ISSUE TITLE
Istio upgrade from < 1.8.0 (specifically) to >= 1.8.0 causes cluster connectivity issues.

### ISSUE THREAD

**Issue by janzantinge** [istio/istio#30664]
Upgrading the Istio control plane to version 1.8.0 or later can cause connectivity issues in a cluster.

Specifically if the pods are using a Sidecar to configure ingress flow to the service container from the `istio-proxy` sidecar container using a Unix Domain Socket. This only affects `istio-proxy` containers older than 1.8.0.

The connectivity issues manifest as `503 NR` responses to requests that responded with `200`s prior to the upgrade. Analyzing the configuration of the affected `istio-proxy` containers (version 1.7.x in this case) showed that there was very likely a bug in the code that generates the inbound cluster name.

The resulting configuration show that the name of the inbound cluster is incorrect because the route uses a different name for the inbound cluster. The inbound cluster configuration looks like this:
```
{
     "name": "inbound|8088||",
     "type": "STATIC",
     "connectTimeout": "10s",
     "loadAssignment": {
         "clusterName": "inbound|8088||",
         "endpoints": [
             {
                 "lbEndpoints": [
                     {
                         "endpoint": {
                             "address": {
                                 "pipe": {
                                     "path": "@istio-proxy.sock"
                                 }
                             }
                         }
                     }
                 ]
             }
         ]
     },
     ...        
}
``` 

The interesting part of the route configuration: the cluster name to which requests are routed doesn't match the inbound cluster name. The inbound route looks like this:
```
{
    "name": "inbound|8088|http2|istio-tester-mesh.istio-tester.svc.cluster.local",
    "virtualHosts": [
        {
            "name": "inbound|http|8088",
            "domains": [
                "*"
            ],
            "routes": [
                {
                    "name": "default",
                    "match": {
                        "prefix": "/"
                    },
                    "route": {
                        "cluster": "inbound|8088|http2|istio-tester-mesh.istio-tester.svc.cluster.local",
                        "timeout": "0s",
                        "maxGrpcTimeout": "0s"
                    },
                    "decorator": {
                        "operation": "istio-tester-mesh.istio-tester.svc.cluster.local:8088/*"
                    }
                }
            ]
        }
    ],
    "validateClusters": false
}
```

This is related to the change in the cluster name that occurred in Istio 1.8.0.

I've drafted a PR to fix this issue and I have verified that it fixes the issues I see in my clusters: https://github.com/istio/istio/pull/30642

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

Upgrading the Istio control plane to a version later than 1.8.0 should not result in a failure to communicate with an application.

**Steps to reproduce the bug**

1. Start with a cluster using Istio 1.7.x
2. Configure an application to handle traffic via a Unix Domain Socket
3. Configure the `istio-proxy` to route ingress traffic to the application via the Unix Domain Socket using a Sidecar resource:
```
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: istio-tester
  namespace: istio-tester
spec:
  ingress:
  - captureMode: IPTABLES
    defaultEndpoint: unix://@istio-proxy.sock
    port:
      name: http2
      number: 8088
      protocol: HTTP2
```
4. The application should currently return `200` responses to HTTP requests
5. Upgrade the Istio control plane to 1.8.x (do not restart the application pods to ensure the old, pre-1.8.x `istio-proxy` is still in use)
6. The application should now return `503 NR` responses

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```
client version: 1.8.2
control plane version: 1.8.2
data plane version: 1.8.2 (12 proxies), 1.7.3 (18 proxies)
```

**How was Istio installed?**
Using `istionctl`

**Environment where the bug was observed (cloud vendor, OS, etc)**
AWS EKS 1.17

**Comment by howardjohn** [comment]
This should be fixed by https://github.com/istio/istio/commit/2f4f6c85d9c3c1738082a0946fc1b16b1d5cfcaf in 1.8.3, releasing on monday
