### ISSUE TITLE
Mixer e2e TestDenials is flaky

### ISSUE THREAD

**Issue by hklai** [istio/istio#3066]
The test passed and failed in two successive release qualification runs.

Passed:
https://storage.googleapis.com/istio-prow/pull/istio-releases_daily-release/365/daily-e2e-rbac-auth/256/build-log.txt

Failed:
https://storage.googleapis.com/istio-prow/pull/istio-releases_daily-release/366/daily-e2e-rbac-auth/257/build-log.txt

I0201 09:56:38.184] --- FAIL: TestDenials (96.38s)
I0201 09:56:38.184] 	mixer_test.go:245: product page was not denied: could not retrieve product page in 1m0s: Last status: 200

**Comment by ldemailly** [comment]
it seems this could be because the cluster is overwhelmed or otherwise unhealthy and the rule doesn't propagate despite waiting 1 minute ?

**Comment by douglas-reid** [comment]
@ldemailly I think there is something else config on. i'm concerned that our Timeout check is problematic. I don't see any logs like: "Unable to connect to read from..." which should result from get() if there really was a timeout. Maybe the load is interrupting the tests and the minute check is just problematic ???

/assign mandarjog
@mandarjog can you confirm my read of the error message?

**Comment by douglas-reid** [comment]
looked at the logs. found an issue with config. @jmuk is fixing.
