### ISSUE TITLE
Hardcoded Zipkin Tracing Request Authority

### ISSUE THREAD

**Issue by ethernoy** [istio/istio#30681]
**Bug description**
When I configure istio (deployed following istio operator pattern) in cluster A to write traces to my jaeger collector in cluster B, I found that no matter how I change the field `tracing.zipkin.address`, the request actually made by istio-proxy sending to the jaeger collector always has `authority` header set to "zipkin". In this case, I cannot route the trace request using `hosts` field set in VirtualService and Gateway in cluster B, but can only leave entire port 9411 to jaeger collector service. 

Screenshot of the access log is as below:
![image](https://user-images.githubusercontent.com/15870761/107024999-c11be500-67e3-11eb-8ac7-82d0a777598f.png)

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
When `tracing.zipkin.address` is set to a domain url (say "zipkin.mgt.dev.cluster"), the trace request made by istio proxy should carry authority header equal to that domain.

**Steps to reproduce the bug**
Set `tracing.zipkin.address` to a domain url, and observe the request header. (In my case, I checked the access log on ingress gateway of target cluster)

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
Istio: 1.8.1
Kubernetes: 1.18.5+vmware.1

**How was Istio installed?**
Using istio-operator pattern specified in isito documentation

**Environment where the bug was observed (cloud vendor, OS, etc)**
VMware Tanzu

**Comment by sridharlreddy** [comment]
Hi @ethernoy,  Zipkin cluster name is hardcoded with 'Zipkin' in envoy_bootstrap.json, hence authority is carrying Zipkin as authority whatever is the endpoint. 
@bianpengyuan, I can help on this issue, can you guide how to proceed? One straight forward fix is updating envoy_bootstrap.json to have the cluster name along with the tracer destination.

**Comment by bianpengyuan** [comment]
@douglas-reid ^^ I think you are looking at this? Would it worth the effort considering telemetry API effort?

**Comment by douglas-reid** [comment]
We should add support to the extension provider for Zipkin in the Telemetry API.

**Comment by bianpengyuan** [comment]
> We should add support to the extension provider for Zipkin in the Telemetry API.

Then I guess for now we should delay fixing this problem and wait for Telemetry API instead to get rid of static tracer config.

**Comment by sridharlreddy** [comment]
Then another issue https://github.com/istio/istio/issues/31414 could also be covered in the same feature.
