### ISSUE TITLE
Add support for different redirect actions in VirtualService

### ISSUE THREAD

**Issue by feliperuiz** [istio/istio#30682]
**Describe the feature request**
Envoy has support for many ways of handling redirects, like [prefix]( https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-redirectaction-prefix-rewrite) or [regex](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-redirectaction-regex-rewrite) rewriting, but istio only supports [path rewriting](envoy-v3-api-field-config-route-v3-redirectaction-path-redirect), which replaces the entire path. Rewrites, on the other hand, do support prefix rewriting if prefix matching is used. It would be nice if we could use those other modes in istio itself, instead of having to do it in the application.

**Describe alternatives you've considered**
I don't have that much knowledge when it comes to istio, but the only alternative I can think of right now involves doing these kinds of redirects in our applications.

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[] Developer Infrastructure

(I don't know which ones are or aren't affected)

**Comment by esnible** [comment]
Closing as duplicate.

**Comment by edkimmel** [comment]
I don't believe this was a duplicate ticket.  The ticket linked was only concerned with HTTPRewrite, and the [final PR merged ](https://github.com/istio/istio/pull/45398) also only mentions HTTPRewrite.

The ask here is to also add regex support for HTTPRedirect.

**Comment by dezenxi** [comment]
Yes. I agree. This should be reopened
