### ISSUE TITLE
'istioctl -n <ns> ps <pod>' ignores ns

### ISSUE THREAD

**Issue by esnible** [istio/istio#30691]
Failing on istioctl 1.9.0-rc.0.

To reproduce,

```
# fails
% istioctl -n istio-system dashboard envoy deployment/istio-ingressgateway
Error: deployments.apps "istio-ingressgateway" not found
# works
istioctl dashboard envoy deployment/istio-ingressgateway.istio-system
```

**Comment by kebe7jun** [comment]
istioctl has a `-n` param, but dashboard cmd redefine an `addonNamespace` param(use `-n`), which is conflict with global namespace, should we use global namespace instead?
