### ISSUE TITLE
istio gateway reference document error

### ISSUE THREAD

**Issue by zackzhangkai** [istio/istio#30728]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

![image](https://user-images.githubusercontent.com/20178386/107205899-58c64100-6a39-11eb-9826-5f98534a1dd9.png)

[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Comment by ericvn** [comment]
I believe the change needed here is in https://github.com/istio/api/blob/master/networking/v1alpha3/gateway.proto#L264. Once it's changed there, the `make gen` will update the gateway.pb.html and the nightly istio.io job will pull the change.

**Comment by zackzhangkai** [comment]
https://github.com/istio/api/pull/1877

**Comment by zackzhangkai** [comment]
@ericvn I have done it already, the test result showed that it needs a release notes. And I had submit the pr with it.

https://github.com/istio/istio/pull/30729/files
