### ISSUE TITLE
Rename `v1alpha2.RouteRule` --> `v1alpha2.VirtualHost`

### ISSUE THREAD

**Issue by mandarjog** [istio/istio#3073]
The v2 route rule is a collection of rules and associated hosts.
This is usually understood and modeled as Virtual host.

We should rename this.

**Comment by PiotrSikora** [comment]
Agreed.

**Comment by kyessenov** [comment]
How does VirtualHost transpire other protocols? In proxies, usually
virtualhosts are nested under HTTP manager.

**Comment by PiotrSikora** [comment]
Yeah, something like `Host` or `Server` might make more sense.

**Comment by rshriram** [comment]
Which is what we have at top of the rule. A list of hosts.
And route rules will apply for TCP/UDP/HTTP and other protocols as well.

**Comment by rshriram** [comment]
can you close and move this issue to istio/api ?

**Comment by mandarjog** [comment]
Issue moved to [istio/api #342](https://github.com/istio/api/issues/342) via [**ZenHub**](https://www.zenhub.com/)
