### ISSUE TITLE
istio-operator helm chart namespace creation

### ISSUE THREAD

**Issue by papdaniel** [istio/istio#30733]
The istio-operator helm chart creates the namespace, and it's a problem when I want to install the chart.
So if I say 
```
$ kubectl create namespace istio-operator
$ helm install -n istio-operator istio-operator manifests/charts/istio-operator --set operatorNamespace=istio-operator
```
It fails:
```
Error: rendered manifests contain a resource that already exists. Unable to continue with install: Namespace "istio-operator" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "operator"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "istio-operator"
```
or the same:
```
$ helm install -n istio-operator istio-operator manifests/charts/istio-operator --create-namespace --set operatorNamespace=istio-operator
```

Should it be a way to let helm create the namespace? Like `helm install --create-namespace...`, or the user could create it before install.

My problem now is, that the helm chart release itself (the release secret) has to be installed in a different namespace, which is a little confusing:
```
$ helm install istio-operator manifests/charts/istio-operator --set operatorNamespace=istio-operator
```

```
$ helm -n istio-operator ls
NAME    NAMESPACE       REVISION        UPDATED STATUS  CHART   APP VERSION
```

```
$ helm -n default ls
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
istio-operator  default         1               2021-02-08 16:08:02.312543932 +0100 CET deployed        istio-operator-1.7.0  
```
```
$ kubectl -n istio-operator get deployments.apps 
NAME             READY   UP-TO-DATE   AVAILABLE   AGE
istio-operator   1/1     1            1           2m17s
```

**Comment by howardjohn** [comment]
+1, helm best practice is to NOT create the namespace

cc @ostromart

**Comment by papdaniel** [comment]
I just made a [pull request](https://github.com/istio/istio/pull/30741). The only difference now: the namespace won't be labeled with:
```
  labels:
    istio-operator-managed: Reconcile
    istio-injection: disabled
```
I did not find anything about the first label. But if these labels needed, I think it should be documented (that before helm install the namespace should have these labels).

**Comment by ostromart** [comment]
This seems like a documentation issue, namespace creation should be mentioned in helm install docs if it isn't already @jacob-delgado.

**Comment by papdaniel** [comment]
@ostromart, the problem here, that the current solution is not a good practice, it's not flexible. Helm itself should create the namespace (with `helm install --namespace` flag), or the namespace should exist before `helm install`. Currently the namespace created from template, so I cannot install the release in that namespace, as I mentioned. 
So if I install now:
```
$ helm install my-operator manifests/charts/istio-operator --set operatorNamespace=my-new-operator-namespace
```
and I want to see my newly installed release in the `my-new-operator-namespace` namespace, I see nothing:
```
$ helm --namespace my-new-operator-namespace ls
NAME    NAMESPACE       REVISION        UPDATED STATUS  CHART   APP VERSION
```
It's because from the helm point of view the chart is installed in the default namespace. The release information stored in a secret, that secret is placed in the default namespace.

The helm release information, and the installed application should be created in the same namespace.
It can be really confusing. E.g. later a new team member wants to upgrade to a new version of the operator with `helm upgrade`, and he sees no helm release in `my-new-operator-namespace`.

**Comment by desaintmartin** [comment]
Moreover, uninstalling the chart would delete the namespace and whatever lives in it.

**Comment by papdaniel** [comment]
Yes @desaintmartin 👍 that's maybe the most important issue, I just missed it.

**Comment by shamsher31** [comment]
@jacob-delgado I think this is still an issue for istio-operator, Please review this PR https://github.com/istio/istio/pull/30741 and provide your feedback. I'm reponing this issue.

**Comment by caryyu** [comment]
> @jacob-delgado I think this is still an issue for istio-operator, Please review this PR #30741 and provide your feedback. I'm reponing this issue.

I suppose you cannot just simply change those helm templates due to there may have the associations with `istioctl`, which they're using for `istioctl operator init`, however, I'm still not quite sure about it.

**Comment by hammadzz** [comment]
This issue is still existent in the latest released version of istio-operator. Should be fixed as a patch as the documentation on installing via helm is incorrect.
