### ISSUE TITLE
Need to support v1 of kubernetes resources

### ISSUE THREAD

**Issue by tmshort** [istio/istio#30740]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
Istio is still referring to v1beta1 versions of some kubernetes resources. The following error messages are from 1.20 client/1.19 server. Kubernetes 1.20 was released at the end of 2020. Kubernetes 1.22 may be released before the end of 2021.
```
Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
Warning: admissionregistration.k8s.io/v1beta1 ValidatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 ValidatingWebhookConfiguration
Warning: admissionregistration.k8s.io/v1beta1 MutatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 MutatingWebhookConfiguration
```

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[X] Upgrade

**Expected behavior**

No warning messages during install.

**Steps to reproduce the bug**

Just look at the CRDs...

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

Istio: 1.8.2 (still a problem in 1.9/master)
kube server: 1.19.6
kube client: 1.20.2

**How was Istio installed?**

istioctl manifest generate
kubectl apply -f

**Environment where the bug was observed (cloud vendor, OS, etc)**

Private kubernetes cluster.

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
This is intentional, to provide support for Kubernetes versions that do not have v1. We will upgrade to v1 before they are removed.

**Comment by tmshort** [comment]
I figured you would; this at least provides a tracker? 
According to https://kubernetes.io/blog/2020/08/31/kubernetes-1-19-feature-one-year-support/ kubernetes 1.16 and earlier are no longer supported, so all supported versions (and at least one out-of support version) of kubernetes support the v1 versions of those resources.
The update to these resources can be done at any time.

**Comment by howardjohn** [comment]
I agree with you in general, and argue the exact same thing when we made the decision to not upgrade to `v1` yet :slightly_smiling_face: . The unfortunate reality is that kubernetes 1.15 still has a massive amount of users that we do not feel comfortable cutting off yet.

**Comment by howardjohn** [comment]
Tracking most of this work in https://github.com/istio/istio/issues/30822

**Comment by howardjohn** [comment]
Fixed by https://github.com/istio/istio/issues/30822
