### ISSUE TITLE
service accounts secrets from istio 1.6

### ISSUE THREAD

**Issue by arunpmohan** [istio/istio#30744]
We were using istio 1.5.10 and we could see that for any service account in a namespace istio used to create "istio.<serviceaccount>" secret . This was pretty awesome as we used to use this certs internally in our non injected pods which doesnt really do MTLS to do mtls with pods containing sidecars.
We never had to create our own secrets as this was always done by istio from the root ca's we create in istio-system namespace.
But starting with istio 1.6 we notice that it never creates service account secrets .
This page talks about some options 

https://istio.io/v1.6/docs/ops/configuration/mesh/secret-creation/

but doesnt create secrets.

Is there anyway to bring back the old behaviour of secret generation in istio 1.6 ?

Also i see that a configmap with name istio-ca-root-cert is created.

**Comment by howardjohn** [comment]
This is no longer supported.

https://istio.io/latest/docs/ops/integrations/prometheus/#tls-settings does show an example of sharing these secrets with pods without running the full interception.

**Comment by arunpmohan** [comment]
Thank you
