### ISSUE TITLE
Instioctl install fails if HOME variable is not present

### ISSUE THREAD

**Issue by psingarakannan** [istio/istio#30754]
Getting "Istioctl installed successfully" even though it failed to install due to missing $HOME variable. "cd $HOME || exit" command will not exit the script rather it will move to base directory. Verify $HOME variable exists and fail the installation. 

https://github.com/istio/istio/blob/0c0cf2d6fbca85beca0598de8817ff90107ddd0c/release/downloadIstioCtl.sh#L122

**Comment by howardjohn** [comment]
In what environment does `$HOME` not exist? And doesn't `cd` with no args go to the "base directory" which is what we want anyways? At least on my machine `cd` == `cd $HOME`

**Comment by psingarakannan** [comment]
I have faced this issue in my product. This is during the process of creating OS image I want to bake in istioctl and it got failed due to $HOME variable absence. 
Due to missing $HOME variable cd $HOME stayed back in ${tmp} directory and below commands created directory inside ${tmp} and removed in next step as part of rm command. I could not find istioctl in my machine but I could see message like "Add the istioctl to your path with:", "Need more information? Visit https://istio.io/docs/reference/commands/istioctl/" which is misleading.
If you are solely relying on $HOME variable, please fail the script if it's is not present.


mkdir -p ".istioctl/bin"
mv "${tmp}/istioctl" ".istioctl/bin/istioctl"
rm -r "${tmp}"
