### ISSUE TITLE
Mixer IP address values are passed to adapters as []byte

### ISSUE THREAD

**Issue by guptasu** [istio/istio#3075]
details:

Martin Taillefer:

Doug just pointed out that our access logs currently contain this kind of stuff:
{"level":"info","time":"2018-02-01T09:54:29.733870Z","instance":"accesslog.logentry.mixer-test50289c613cd04c4390cd9aab67","destinationIp":"AAAAAAAAAAAAAP//CjwJfQ==","
latency":"7.556ms","method":"GET","protocol":"http","requestSize":0,"responseCode":
200,"responseSize":178,"sourceIp":"CjwERA==","sourceUser":"cluster.local/ns/mixer-test50289c613cd04c4390cd9aab67/sa/default","url":"/details/0"}
Note the sourceIp and destinationIp values. Looks like we're getting confused about what we're logging.

The above is coming from the stdio adapter. I suspect the adapter is expecting a net.IP value but is
instead given a []byte.

I've lost track of where this kind of stuff is handled in Mixer proper. Who should be converting the
incoming []byte from the proxy to a net.IP for adapter use?

Sunny Gupta:
So the issue is, during request time, we (generated code) cast the byte[] to net.IP only of the type that are explicitly called out as standard_types.IPAddress inside the template.proto. For the dynamic types like dimensions, labels where the type is inferred from expression, we are still passing byte[] to the adapter since during request time we have no clue of the inferred type that we computed during config time.
I chatted to Oz and we have a simple temporary solution for now, which I am currently working on to evaluate the performance impact. Basically, as a temporary solution, during IL evaluation, we can check if final result is byte[], we can convert it into net.Ip (currently byte[] can only mean net.IP). Long term, according to Oz, the compiled expressions can
actually do better since they already should be knowing the expression type and we can just do the conversion localized
for IPAddress.

@ozevren @geeknoid  @douglas-reid  FYI

**Comment by douglas-reid** [comment]
We should move quickly on the temporary hold-over solution, as I believe this is a regression.

**Comment by guptasu** [comment]
This issue is fixed; the long term solution as suggested above applies to all types inside compiled expression and not just to the net.IP. The long term solution can be done as part of overall enhancement to the compiled expression; whenever we decide to do it.

Close this issue which is specific to net.IP
