### ISSUE TITLE
Mesh federation with common root CA and different trustDomains

### ISSUE THREAD

**Issue by apolovov** [istio/istio#30769]
[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Steps to reproduce the bug**

* Generate root CA and two intermediate CAs according [instructions](https://istio.io/latest/docs/tasks/security/cert-management/plugin-ca-cert/).
* Install two clusters with generated CAs (their clusterDomain and trustDomain):
  * `a.local`
  * `b.local`
* Install applications:
  * `sleep` in ns `foo` in cluster `a.local`
  * `httpbin` in ns `bar` in cluster `b.local`
* Setup federation:
  * IngressGateway with public IP and `sni-dnat` mode in `b.local`
  * `ServiceEntry` `httpbin.bar.svc.b.local` on cluster `a.local` with endpoint of public IP of `b.local`
  * DestinationRule/PeerAuthentication in both clusters to reach strict mTLS
* Check connectivity between clusters:
  * `curl httpbin.bar.svc.b.local:8000` from sleep pod (cluster `a.local`)

As result we get an error:
```
upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: TLS error: 268436502:SSL routines:OPENSSL_internal:SSLV3_ALERT_CERTIFICATE_UNKNOWN/
```
Meanwhile in `httpbin` logs (cluster `b.local`):
```
2021-02-04T17:09:50.020112Z	debug	envoy filter	original_dst: New connection accepted
2021-02-04T17:09:50.020176Z	debug	envoy filter	tls inspector: new connection accepted
2021-02-04T17:09:50.020191Z	trace	envoy filter	tls inspector: recv: 5615
2021-02-04T17:09:50.020238Z	trace	envoy filter	tls:onALPN(), ALPN: istio-http/1.1,istio,http/1.1
2021-02-04T17:09:50.020253Z	debug	envoy filter	tls:onServerName(), requestedServerName: outbound_.8000_._.httpbin.bar.svc.b.local
2021-02-04T17:09:50.039679Z	debug	envoy conn_handler	[C478] new connection
2021-02-04T17:09:50.039732Z	trace	envoy connection	[C478] socket event: 3
2021-02-04T17:09:50.039735Z	trace	envoy connection	[C478] write ready
2021-02-04T17:09:50.062819Z	trace	envoy connection	[C478] read ready. dispatch_buffered_data=false
2021-02-04T17:09:50.096115Z	trace	envoy connection	[C478] socket event: 3
2021-02-04T17:09:50.096165Z	trace	envoy connection	[C478] write ready
2021-02-04T17:09:50.098899Z	debug	envoy connection	[C478] TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
2021-02-04T17:09:50.098930Z	debug	envoy connection	[C478] closing socket: 0
2021-02-04T17:09:50.098989Z	debug	envoy conn_handler	[C478] adding to cleanup list
```
I think I've localized the point of failure. It is in listener filter chains in envoy like this:
```
            "combined_validation_context": {
             "default_validation_context": {
              "match_subject_alt_names": [
               {
                "prefix": "spiffe://b.local/"
               }
              ]
             },
...
```

And the workaround (_number 1_) for this case could be using `trustDomainAliases` which adds one more prefix in match SAN array above. But:
* I believe it was designed for temporary usage during trustDomain migration.
* It brings complexity to authz rules. Users must remember that their `AuthorizationPolicy` rules are being duplicated for one more cluster.
* I noticed that when i use `trustDomainAliases`, the sidecar-proxy doesn't check CA at all! I can connect to remote cluster with ANY CA.

Another solution (_number 2_) — to not check the client SAN prefix by using `PILOT_SKIP_VALIDATE_TRUST_DOMAIN` env variable for istiod. In this case, the listener filter chain is being generated like this:
```
            "combined_validation_context": {
             "default_validation_context": {},
```
It could be a solution if there aren't other side effects. (I posted a related issue to the private security mail list).

Theoretical solution _number 3_ — to use `EnvoyFilter` to patch the listener filters and add SAN prefixes for remote clusters. But i couldn't implement it by myself.

What is the official solution? Maybe we need something like `trustDomainAliases` which only patches listener filter chains with remote `trustDomains`?

**Version** 
1.8.2

**Comment by apolovov** [comment]
P.S. I was inspired to implement single root CA mesh federation by [this presentation](https://zhaohuabing.com/img/2019-06-25-kubecon-cncf-oss-2019/How-SPIFFE-helps-Istio-in-Service-Mesh-Federation.pdf), slide 9 ([video](https://www.youtube.com/watch?v=SCBksDnA2rU)).

**Comment by apolovov** [comment]
> I noticed that when i use trustDomainAliases, the sidecar-proxy doesn't check CA at all! I can connect to remote cluster with ANY CA.

It was my mistake. This problem isn't actual. Sorry.

**Comment by zenvdeluca** [comment]
I'm affected by a similar problem. blocked on upgrading from 1.7.6 to 1.8 or 1.9 as multicluster breaks when using different cluster domains in a federation. looking for a direction, as @apolovov mentioned I'm wary of relying on `trustDomainAliases` as it doesn't seem intended for this problem

**Comment by shankgan** [comment]
fyi: This issue discusses having multiple roots, possibly one per trustdomain https://github.com/istio/istio/issues/31111

**Comment by shankgan** [comment]
@apolovov - I believe a few Github issues have already been created to outline the work needed to achieve mesh Federation using trustDomainAliases. Would it be possible to enumerate a more exhaustive list of the deficiencies of using trustdomainAliases ? 
Trying to scope this github issue better - are we trying to outline all possible issues today that affect mesh federation?

**Comment by anudeep646** [comment]
so in order to work mesh federation with common root and different trust domain do we need to use trust domain aliases? i'm facing the same issue curl  OPENSSL_internal:public key routines 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED/, works with trust domain aliases

**Comment by apolovov** [comment]
> so in order to work mesh federation with common root and different trust domain do we need to use trust domain aliases? i'm facing the same issue curl OPENSSL_internal:public key routines 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED/, works with trust domain aliases

Now we use PILOT_SKIP_VALIDATE_TRUST_DOMAIN in our installations. The trustDomain validation without bonding to cluster's CA doesn't make sense. (Now when we exchange [caCertificates](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/) between clusters, istio just store them into a single pem list "ROOTCA").
