### ISSUE TITLE
e2e: would it be possible to make Istio e2e Test Framework reusable outside of Istio context ?

### ISSUE THREAD

**Issue by yskopets** [istio/istio#30761]
**Bug description**

Hey folks!

First of all, kudos for the `e2e` test framework! Very convenient and ergonomic!

We're now trying to reuse it in testing of arbitrary k8s apps.

What we've run into are significant test compilation times on first run (which is happening in CI environment).

E.g., it takes `2 minutes` to compile the following snippet on a `8xCPU` Linux host:

```go
package minimal

import (
        "testing"

        "istio.io/istio/pkg/test/framework"
)

func TestMain(m *testing.M) {
    framework.
        NewSuite(m).
        Run()
}
``` 

```shell
time go test -v minimal_test.go

2021-02-09T12:58:26.150454Z	info	tf	=== Test Framework Settings ===
...
testing: warning: no tests to run
PASS
...
ok  	command-line-arguments	0.255s [no tests to run]

real	2m4.492s
user	11m3.148s
sys	1m58.530s
```

For clarity:
* dependencies are already pre-fetched with `go mod download`
* go cache directory (`GOCACHE`) is empty

IIUC, long compilation times are caused by transitive dependencies of `istio.io/istio/pkg/test/framework`:

```shell
go list -f '{{ join .Deps "\n"}}' istio.io/istio/pkg/test/framework | wc -l

1664
```

Apparently, lots of Istio components get compiled as part of `istio.io/istio/pkg/test/framework`:

```shell
go list -f '{{ join .Deps "\n"}}' istio.io/istio/pkg/test/framework | grep istio | cut --delim=/ -f 1-3 | sort | uniq

istio.io/api/annotation
istio.io/api/label
istio.io/api/mcp
istio.io/api/mesh
istio.io/api/mixer
istio.io/api/networking
istio.io/api/operator
istio.io/api/policy
istio.io/api/security
istio.io/api/type
istio.io/client-go/pkg
istio.io/gogo-genproto/googleapis
istio.io/istio/galley
istio.io/istio/istioctl
istio.io/istio/mixer
istio.io/istio/operator
istio.io/istio/pilot
istio.io/istio/pkg
istio.io/istio/security
istio.io/pkg/attribute
istio.io/pkg/cache
istio.io/pkg/collateral
istio.io/pkg/env
istio.io/pkg/filewatcher
istio.io/pkg/ledger
istio.io/pkg/log
istio.io/pkg/monitoring
istio.io/pkg/pool
istio.io/pkg/probe
istio.io/pkg/structured
istio.io/pkg/version
```

Do you think it would make sense to exclude dependencies on `istio.io/istio/galley`, `istio.io/istio/istioctl`, `istio.io/istio/operator`, `istio.io/istio/pilot`, etc from `istio.io/istio/pkg/test/framework` ?

Do you see any downsides in doing that ?

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[x] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Comment by howardjohn** [comment]
I was digging into why this imports so much and by the time I had figured it out I had cleaned up most of it I think. Hopefully it passes the tests: https://github.com/istio/istio/pull/30764

LMK how that works. This has bugged me too

**Comment by yskopets** [comment]
Hey!

Thank you!

The new numbers look like this:

```shell
real	1m8.273s
user	5m45.245s
sys	1m3.335s
```

`2x` better. That's great!
