### ISSUE TITLE
Confirmation still promoted on istioctl upgrade --skip-confirmation on 1.8.3

### ISSUE THREAD

**Issue by cyberprune** [istio/istio#30760]
**Bug description**
While running istioctl upgrade with version 1.8.3, the following prompt is displayed:

`Confirm to proceed [y/N]?
`

when running
`./istioctl upgrade --dry-run --force --skip-confirmation`

It also happens without `--dry-run`

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[X ] Upgrade

**Expected behavior**

No prompts to be displayed

**Steps to reproduce the bug**

curl -L https://istio.io/downloadIstio | ISTIO_VERSION=1.8.3 sh -
cd istio-1.8.3/bin
./istioctl upgrade --dry-run --force --skip-confirmation

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```
./istioctl version --remote
client version: 1.8.3
control plane version: 1.8.1
data plane version: 1.8.1 (6 proxies)

```
```
 kubectl version --short
Client Version: v1.20.2
Server Version: v1.19.7
```

**How was Istio installed?**
istioctl

**Environment where the bug was observed (cloud vendor, OS, etc)**
Linode LKS

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by morvencao** [comment]
Please try upgrade command without `--dry-run`.

**Comment by cyberprune** [comment]
I tried without the --dry-run too and it had the same confirmation prompt

**Comment by morvencao** [comment]
@cyberprune 
```
~/istio-1.8.3# ./bin/istioctl upgrade  --force --skip-confirmation
2021-02-10T09:07:10.644740Z	info	proto: tag has too few fields: "-"
Control Plane - pilot pod - istiod-545bb98448-klg9g - version: 1.8.2

Upgrade version check passed: 1.8.2 -> 1.8.3.

Upgrade check: Warning!!! The following IOPS will be changed as part of upgrade. Please double check they are correct:
spec:
  installPackagePath: /tmp/istio-install-packages/istio-1.8.2/manifests ->

Detected that your cluster does not support third party JWT authentication. Falling back to less secure first party JWT. See https://istio.io/v1.8/docs/ops/best-practices/security/#configure-third-party-service-account-tokens for details.
✔ Istio core installed
✔ Istiod installed
```

**Comment by pio2pio** [comment]
working workaround seems `echo "y" | istioctl upgrade -f manifest --dry-run` the `--skip-confirmation` can be kept in the line but seems being ignored; this happens on v1.9.0

**Comment by pankajxp** [comment]
@morvencao thanks a ton! --force --skip-confirmation worked for me in ignoring the confirmation prompt.
# istioctl install --force --skip-confirmation

**Comment by ko5tas** [comment]
Thank you @pio2pio it worked for me, too! (istioctl version 1.8.2)
