### ISSUE TITLE
SPIFFE_BUNDLE_ENDPOINTS doesn't work as described

### ISSUE THREAD

**Issue by apolovov** [istio/istio#30776]
**Bug description**
The documentation of [SPIFFE_BUNDLE_ENDPOINTS](https://istio.io/latest/docs/reference/commands/pilot-discovery/) promises that CAs from bundle endpoints will be used to verify client certificates.
And after configuring this feature on cluster `b.local` to receive requests from cluster `a.local` I see logs:
```
2021-02-10T00:05:23.269482Z	info	spiffe	Added 1 certs to trust domain b.local in peer cert verifier
2021-02-10T00:05:23.269496Z	info	spiffe	Processing SPIFFE bundle configuration: a.local|https://example.com/bundle.json
2021-02-10T00:05:23.341801Z	info	spiffe	Loaded SPIFFE trust bundle for: a.local, containing 1 certs
2021-02-10T00:05:23.341909Z	info	spiffe	Added 1 certs to trust domain a.local in peer cert verifier
```
But nothing works. I can't see any mentions of `b.local` in sidecar's configs. Neither ca nor trustDomain. The requests from `a.local` are being rejected with the `CERTIFICATE_VERIFY_FAILED` error.

I discovered code and figured out that these trust bundles are in use only by SDS listener of istiod. Am I right?

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Discovered CAs must be pushed to all sidecars for verifying client certificates.

**Version**
1.8.2

**Comment by howardjohn** [comment]
This is just used for Istiod authenticating proxies for control plane communication, not for workload to workload mtls. The doc seems to attempt to say this " Istiod retrieves the root certificate from each SPIFFE bundle endpoint and uses it to verify client certifiates from that trust domain. " but its a bit confusing

There is some work ongoing to expand this to be usable for workload mTLS certificates as well, and multiple CA certs in general. Pretty early WIP without design fully complete, but some work is in https://github.com/istio/istio/pull/30506

**Comment by apolovov** [comment]
Thank you for your job, @howardjohn. It is pretty nice PR so I tested it out and [described](https://github.com/istio/istio/pull/30506#issuecomment-778842492) a couple of problems.

**Comment by howardjohn** [comment]
Thanks!!
