### ISSUE TITLE
superfluous response.WriteHeader call in Istiod debug

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#30785]
`http: superfluous response.WriteHeader call from istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).Debug (debug.go:722)` when calling localhost:8080/debug

**Comment by smwyzi** [comment]
hi, in the 1.9.0 source code, there is no response.WriteHeader call in debug.go:722, so would you please describe the issue with more details >_<

**Comment by howardjohn** [comment]
This was on master
