### ISSUE TITLE
stdout logs also written to accesslog file configured for logrotate

### ISSUE THREAD

**Issue by ashmini** [istio/istio#30787]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

Had configured meshconfig

 meshConfig:
    accessLogFile: /var/log/<accesslog dir>/<accesslog file>
Configured logrotate using the following link as reference
https://github.com/istio/pkg/blob/master/log/config_test.go#L206

o := DefaultOptions()
	o.OutputPaths = []string{}
	o.RotateOutputPath = file

I see stdout logs also getting written to the accesslog file. 

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
stdout logs should not be dumped to accesslogfile if o.OutputPaths = []string{}

**Steps to reproduce the bug**

meshConfig:
    accessLogFile: /var/log/<accesslog dir>/<accesslog file>
Configured logrotate using the following link as reference
https://github.com/istio/pkg/blob/master/log/config_test.go#L206

o := DefaultOptions()
	o.OutputPaths = []string{}
	o.RotateOutputPath = file

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
istioctl version --remote
client version: 1.8.2
control plane version: 1.9-dev-7e691a6e2263094b5eda839c5f4dcc4e7791b5d6
data plane version: 1.8.2 (1 proxies), 1.9-dev (1 proxies)

kubectl version
Server Version: v1.19.4

**How was Istio installed?**
istioctl

**Environment where the bug was observed (cloud vendor, OS, etc)**
minkube

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
accessLogFile refers to envoy logs. They are not configured by istio/pkg (or any go code).

**Comment by ashmini** [comment]
So explaining what I'm trying to do:

1) configure meshconfig.accessLogFile: /var/log/proxy/access.log
2) I made changes to https://github.com/istio/istio/blob/master/pilot/cmd/pilot-agent/config/config.go#L125 to read the accessLogFile and configure logrotate as per this example https://github.com/istio/pkg/blob/master/log/config_test.go#L206. The expectation is stdout logs continue to be written to stdout and not to the acceslog file.

I'm seeing stdout logs written to the accesslog file

**Comment by howardjohn** [comment]
@ashmini envoy writes the log to `/var/log/proxy/access.log`. Even if you somehow configure some logrotate settings, I don't think there is any way to get those to stdout as well. Kubernetes best practice is to write to stdout, which seems like a better approach,

**Comment by ashmini** [comment]
It is the other way around. I mean the stdout logs are getting written to /var/log/proxy/access.log. So the bug lies here 

o := DefaultOptions()
	o.OutputPaths = []string{} << when there are no values, then stdout logs should not get written to o.RotateOutputPath file.

Is there a way to just configure logrotate for /var/log/proxy/access.go(which is the accesslogfile)?

**Comment by howardjohn** [comment]
Any go code you are writing has nothing to do with accessLogFile. accessLogFile is an envoy config. You are configuring golang config for, presumably, the agent which is a completely different process/binary

**Comment by ashmini** [comment]
@howardjohn : I have a few questions:

1) how does logrotate work for a an accessLogFile (if value other than /dev/stdout) 
2) Once accessLogFile is configured, the accesslogs in ingress-gateway is written to that file. I'm trying to configure logrotate for the accessLogFile using go code as per  https://github.com/istio/pkg/blob/master/log/config_test.go#L206
3) o.OutputPaths = []string{} is configured and o.RotateOutputPath= accesslogfile , why is stdout logs getting written to accesslogfile?

**Comment by howardjohn** [comment]
It does not work at all. accessLogFile cannot be used with logrotate. We do not recommend, document, or support the logrotate options at all anyways and they are there only for legacy purposes - regardless, they never have worked nor were intended, to work with accessLogFile. These are completely different logging systems.

**Comment by howardjohn** [comment]
Please feel free to direct future questions to https://discuss.istio.io/ or slack. Since there is no bug here, I will close this. Thanks!

**Comment by AshwinRamaniPsg** [comment]
@howardjohn: Logrotate is also not available with the current image. Would that support be added?
