### ISSUE TITLE
Can't inject sidecar to specific pods when InjectionPolicy is enabled

### ISSUE THREAD

**Issue by yfried** [istio/istio#30806]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

Unlike [documentation](https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#controlling-the-injection-policy), pod label `sidecar.istio.io/inject=true` is not picked up by the injection webhook. Neither is any label described in `values.sidecarInjectorWebhook.alwaysInjectSelector`.
This is because Webhook only listens on namespaces matching the `namespaceSelector`.

[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Webhook should listen to all namespaces so that pods in namespaces that don't have `istio-injection=enabled` label should be auto-injected when `sidecar.istio.io/inject=true` label (or any other label defined in `values.sidecarInjectorWebhook.alwaysInjectSelector`) is present on pod.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
1.8.1
**How was Istio installed?**
`istioctl manifest generate | kubectl apply -f -`

**Comment by howardjohn** [comment]
This documentation was meant to be for istio 1.10. It seems like it accidentally made it into 1.9 docs

**Comment by ericvn** [comment]
Closing this issue as the 1.9 docs were reverted.
