### ISSUE TITLE
Error IST0101  on VirtualService from analyze when using a cluster dnsDomain != "cluster.local"

### ISSUE THREAD

**Issue by primeroz** [istio/istio#30807]
**Bug description**

When setting a cluster `dnsDomain` for kubernetes that is different from the default `cluster.local` and a cross-namespace Fully qualified service name is used in a VirtualService then `istioctl analyze` will always print an **`ERROR IST0101 Referenced host not found`**  

This is true for any value of the dnsDomain other than `cluster.local` , even `cluster1.local` 

Note that the configuration in the envoy proxy _seems_ to be applied correctly 

The cluster is created using kubeadm
* setting the value of `networking.dnsDomain` to a custom value ( cluster1.local )
* Istio Resource is customized with the custom dnsdomain
  * `meshConfig.trustDomain` 
  * `values.global.proxy.clusterDomain` 
  * `values.global.trustDomain`

I _think_ those are the right settings for the custom dnsDomain and i could not find any other place where i should change 

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

No error is printed unless there is an error 

**Steps to reproduce the bug**
Steps are complex to be completely listed here so I created a [GIST](https://gist.github.com/primeroz/bfef6743ca19039e7c59aea592a97d27) , this steps use a [test repo of mine](https://github.com/primeroz/istio-on-kind) to help with scripts and setup 

* Create a kubernetes cluster with a custom Dns Domain != "cluster.local"
* Setup IstioD , using the same dns domain in the right settings 
  * `meshConfig.trustDomain` 
  * `values.global.proxy.clusterDomain` 
  * `values.global.trustDomain`
* Create workloads and services in 2 namespaces with istio-injection enabled
* Create a VS in 1 namespace with a destination host in the other namespace using a fully qualified name `service-name.namespace.svc.customDnsDomain` 
* run `istioctl analyze` and check that you get the `IST0101` error
* Check that your virtualservice has actually propagated to the envoy proxies 

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
* Istio 1.5.10 / 1.6.14 / 1.7.7 / 1.8.3 / 1.9.0
* Kubernetes  1.16.15 / 1.9.7

**How was Istio installed?**

Istio-Operator 

**Environment where the bug was observed (cloud vendor, OS, etc)**
AWS and Kind

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by primeroz** [comment]
This is still an issue, with latest 1.9.5 , I understand not being a priority but would it be possible for someone to remove the `stale` status ? 

thanks

**Comment by Strasser-Pablo** [comment]
Got exactly the same problem.
