### ISSUE TITLE
meshConfig.defaultConfig.holdApplicationUntilProxyStarts not working as expected in 1.9.0

### ISSUE THREAD

**Issue by samene** [istio/istio#30814]
```meshConfig.defaultConfig.holdApplicationUntilProxyStarts``` not working as expected in **1.9.0**
I can see that the istio-proxy starts before the main container even when this flag is set.

This *used to work in 1.8.1*

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
When this flag is set the istio proxy container should be started at the beginning instead of in the end.

**Steps to reproduce the bug**

Sample pod describe
```
  Type     Reason     Age        From                        Message
  ----     ------     ----       ----                        -------
  Normal   Scheduled  <unknown>                              Successfully assigned myapp-cloud/emc-edr-processing-57b6c9467-wdzg8 to test-dev-smene
  Normal   Pulled     79s        kubelet, test-dev-smene  Container image "istio/proxyv2:1.9.0" already present on machine
  Normal   Created    78s        kubelet, test-dev-smene  Created container istio-init
  Normal   Started    78s        kubelet, test-dev-smene  Started container istio-init
  Normal   Pulling    78s        kubelet, test-dev-smene  Pulling image "myapp-emc/edr-processing:4.0.20"
  Normal   Pulled     77s        kubelet, test-dev-smene  Successfully pulled image "myapp-emc/edr-processing:4.0.20" in 561.747434ms
  Normal   Created    77s        kubelet, test-dev-smene  Created container emc-edr-processing
  Normal   Started    77s        kubelet, test-dev-smene  Started container emc-edr-processing
  Normal   Pulled     76s        kubelet, test-dev-smene  Container image "istio/proxyv2:1.9.0" already present on machine
  Normal   Created    76s        kubelet, test-dev-smene  Created container istio-proxy
  Normal   Started    76s        kubelet, test-dev-smene  Started container istio-proxy

```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

istio 1.9.0
kubernetes 1.18

**How was Istio installed?**
Istio operator

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by samene** [comment]
When is the next official release planned? 1.9.1?

**Comment by shamsher31** [comment]
> When is the next official release planned? 1.9.1?

@samene Probably early next week.
