### ISSUE TITLE
Add liveness probes configuration for istio-operator

### ISSUE THREAD

**Issue by kubealex** [istio/istio#30811]
**Describe the feature request**

At the moment, there is no liveness probe configuration (not only the default, but in general).

This is BLOCKING for environments using istio-operator for the deploy, since the admission for the istiod and istio-ingressgateway fails if enforcing on presence of readiness/liveness probes is present.

**Describe alternatives you've considered**

Add the optional capability to setup liveness probes, maybe not enabling them by default.

[ ] Docs
[ X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ X ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
Thanks for the issue. Lets keep tracking this in https://github.com/istio/istio/issues/29773 which already has some discussion. Thanks!
