### ISSUE TITLE
Egress TLS origination for TCP traffic without IP address

### ISSUE THREAD

**Issue by neerajaustin** [istio/istio#30826]
When using TCP protocol, egress origination setup with ServiceEntry/Virtual Service/Destination rule only works if the IP address and endpoints are used.

We have a need to use the same TCP port for multiple egress destinations and need to upgrade to the TLS port. Can this be done using a FQDN or wildcard hostname instead of IP address and endpoints?

I have something like this and notice that the connections are being established but only on the non-secure port. The TLS upgrade does not occur.

apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: test-se
spec:
  exportTo:
  `-` .
  hosts:
 ` -`any
  location: MESH_EXTERNAL
  ports:
  `-` name: tcp
    number: `non-secure-port`
    protocol: TCP
  `-` name: tcp-secure
    number: `secure-port`
    protocol: TCP
  resolution: NONE

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: test-vs
spec:
  hosts:
  `-` any
  tcp:
  `-` match:
    `-` port: `non-secure-port`
    route:
    `-` destination:
        host: any
        port:
          number: `secure-port`

apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: test-dr
spec:
  host: any
  trafficPolicy:
    portLevelSettings:
    `-` port:
        number: `secure-port`
      tls:
        mode: SIMPLE

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Comment by howardjohn** [comment]
> Can this be done using a FQDN or wildcard hostname instead of IP address and endpoints?

No, TCP does not have a "hostname" concept. We can only match on IP and/or port

**Comment by neerajaustin** [comment]
Thanks for responding back. Does the service entry need to have the IP address mentioned? Or can the request from within the application contain the IP address and be upgraded?

**Comment by GregHanson** [comment]
You can specify IP addresses or a CIDR block in the `addresses` field ([link](https://istio.io/latest/docs/reference/config/networking/service-entry/#ServiceEntry)).  Specifying an IP address or CIDR block is not required for `protocol: TCP`, but is a way to ensure Istio is capturing only the intended traffic rather than all traffic on the port declared in the `ServiceEntry`.

**Comment by neerajaustin** [comment]
Well my question was concerning the TLS upgrade for egress traffic. I dont see it working unless I use the addresses and endpoints on the Service Entry. If not present, traffic is allowed but only on the non-secure port. Yes the port is unique but as multiple targets have the same unique port, I wanted to do it without explicitly mentioning the IP address range here. there is a possibility that the target IP addresses have different subnets and we may not know them upfront.

**Comment by neerajaustin** [comment]
This feature is now available using the Smart DNS proxying feature of Istio. So, we can close this.
