### ISSUE TITLE
istio.io/istio/pkg/probe failures (common test failure)

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#3082]
```
go test  ./pkg/...
ok  	istio.io/istio/pkg/cache	1.196s
?   	istio.io/istio/pkg/collateral	[no test files]
ok  	istio.io/istio/pkg/log	0.066s
--- FAIL: TestFileControllerMethods (0.30s)
	controller_test.go:237: Got file /var/folders/c3/4bc8zz5s5hj13nnr718w91xr00f56m/T/TestFileControllerMethods257307300/fc is too old (last modified time 2018-02-01 15:10:30 -0800 PST, should be within 110ms), Want nil
	controller_test.go:245: Got file /var/folders/c3/4bc8zz5s5hj13nnr718w91xr00f56m/T/TestFileControllerMethods257307300/fc is too old (last modified time 2018-02-01 15:10:30 -0800 PST, should be within 110ms), Want nil
--- FAIL: TestFileController (0.90s)
	controller_test.go:275: Got file /var/folders/c3/4bc8zz5s5hj13nnr718w91xr00f56m/T/TestFileController517214131/fc is too old (last modified time 2018-02-01 15:10:30 -0800 PST, should be within 110ms), want nil
	controller_test.go:288: Got file /var/folders/c3/4bc8zz5s5hj13nnr718w91xr00f56m/T/TestFileController517214131/fc is too old (last modified time 2018-02-01 15:10:30 -0800 PST, should be within 110ms), want nil
	controller_test.go:293: Got file /var/folders/c3/4bc8zz5s5hj13nnr718w91xr00f56m/T/TestFileController517214131/fc is too old (last modified time 2018-02-01 15:10:31 -0800 PST, should be within 110ms), want nil
FAIL
FAIL	istio.io/istio/pkg/probe	1.363s
ok  	istio.io/istio/pkg/tracing	0.056s
?   	istio.io/istio/pkg/util	[no test files]
ok  	istio.io/istio/pkg/version	0.043s
```

this is on my mac, circleci doesn't seem to run this test (#3081 ) so I can't say if it's specific to mac

**Comment by ldemailly** [comment]
Andra told me it works for her, so it may not be that "consistent" :/

**Comment by jmuk** [comment]
It works on my environment too (linux though), but this can be a flaky since it involves file accesses and some timers. I'll think the way to mitigate it.

**Comment by ldemailly** [comment]
also failed on prow:

https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/3119/istio-presubmit/4036/
```
I0202 22:09:18.814] --- FAIL: TestController (0.04s)
I0202 22:09:18.814] 	controller_test.go:118: Got 1 error occurred:
I0202 22:09:18.815] 		
I0202 22:09:18.815] 		* p1: uninitialized, want nil
I0202 22:09:18.815] FAIL
I0202 22:09:18.815] FAIL	istio.io/istio/pkg/probe	1.349s
I0202 22:09:18.815] ok  	istio.io/istio/pkg/tracing	0.069s
I0202 22:09:18.816] ?   	istio.io/istio/pkg/util	[no test files]
I0202 22:09:18.816] ok  	istio.io/istio/pkg/version	0.043s
I0202 22:09:18.822] Makefile:363: recipe for target 'common-test' failed
W0202 22:09:18.823] make: *** [common-test] Error 1
E0202 22:09:18.823] Build failed
I0202 22:09:18.823] process 520 exited with code 1 after 15.4m
E0202 22:09:18.823] FAIL: istio-presubmit
```

**Comment by ldemailly** [comment]
this is still happening for me on master on my mac

**Comment by ldemailly** [comment]
```
I0314 16:20:55.704] --- FAIL: TestFileControllerMethods (0.58s)
I0314 16:20:55.704]     controller_test.go:245: Got file /tmp/TestFileControllerMethods432811897/fc is too old (last modified time 2018-03-14 16:20:47.244177734 +0000 UTC, should be within 110ms), Want nil
```
happens on prow too
https://k8s-gubernator.appspot.com/build/istio-prow/istio-postsubmit/1187?log#log

**Comment by kyessenov** [comment]
No, increasing the duration is not an answer. We saw up to minute delays between test pause and test wake up.

**Comment by jmuk** [comment]
ah, okay, @kyessenov already created the PR to disable them. Thanks.

**Comment by ldemailly** [comment]
while I agree tests relying on timing tend to flake, can we turn off that pause/unpause behavior that is new and doesn't seem to serve any useful purpose beside breaking tests ?
cc @hklai do you know where that's from ?

https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/4268/istio-unit-tests/2296/

it also seems to break prow which thinks those ^ are failures

**Comment by hklai** [comment]
@ldemailly

If I read https://golang.org/doc/go1.10 correctly, the behavioral change was printing PAUSE and CONT when -v is provided. 

It was added by https://github.com/golang/go/commit/3a8b9cfe9138d3a4aa227a6967d94ecdb3c0bd6f#diff-70e628298261565d825f7199d13042f2.

But the logic around that seems to be over 2 years old.
https://github.com/golang/go/blame/4c1aff87f1a160c3da962cda0c48462c88260d7b/src/testing/testing.go

**Comment by ldemailly** [comment]
thx ! looking at your second link, it seems it's only used for Parallel() - so maybe we just need to serialize our tests (as they are cut into // suites already anyway) ?

**Comment by hklai** [comment]
We actually disabled parallel tests in post-submit to fix another problem (i.e. junit file generation for testgrid, at a temporary workaround.
https://github.com/istio/istio/pull/4242/files#diff-b67911656ef5d18c4ae36cb6741b7965

Serializing presubmit tests will obviously prolong test time and PR merge time. Perhaps we are isolate the time sensitive tests into a separate suite and disable parallelism for those only?
