### ISSUE TITLE
1.9.0 externalIstiod default value

### ISSUE THREAD

**Issue by lonnix** [istio/istio#30840]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
I just started comparing values.yaml files for istiod in 1.8.0 and 1.9.0. In 1.9.0 I see this
```
# External istiod controls all remote clusters: disabled by default
externalIstiod: true
```

I am not sure if the docs need to say "enabled by default" or if the default value needs to be "false", but the current values don't add up.

[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Docs to align with default values

**Steps to reproduce the bug**
Download istio 1.9.0 and look at istio-1.9.0/manifests/charts/istiod-remote/values.yaml around line 331

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
I agree its slightly misleading , but this file is autogenerated so there isn't much we can do here.

**Comment by lonnix** [comment]
Is 30845 a fix for this and we can close this issue?

**Comment by howardjohn** [comment]
No, I closed the fix. I don't think we will fix this since the file is auto generated and we don't have a reasonable way to modify this
