### ISSUE TITLE
Connect Namespaces over ingress/egress gateways only?

### ISSUE THREAD

**Issue by dal13002** [istio/istio#30848]
Hey we have a control plane namespace with ingress/egress gateways and 2 member namespaces, which are watched over by the control plane (istio). Due to a restricted environment namespace to namespace communication is blocked via networkpolicies but there are "allow" networkpolices for the member namespaces and control plane namespaces to talk to each other. Is there a way to go out of a pod in member namespace 1 into the control plane's ingress / egress gateway which will forward the traffic to a pod in member namespace 2 using istio? I don't see any docs on how to do this and the closest thing I found was this https://discuss.istio.io/t/how-to-connect-namespaces-over-ingress-egress-gateways-only/2298

[ X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
Do you want to do this automatically (no config) or manually (explicitly define routes)? The later is documented here: https://istio.io/latest/docs/tasks/traffic-management/egress/egress-gateway/. just replace the destination from external site to internal one

**Comment by dal13002** [comment]
Hey, manual is fine. Thank you so much, will check it out

**Comment by dal13002** [comment]
Hey, just an update. It was extremely easy to do and works. 

Thank you for the constant, quick support
