### ISSUE TITLE
Endpoints discovery service - support 'optional' clusters

### ISSUE THREAD

**Issue by gairom** [istio/istio#30859]
Currently, endpoints discovery service requires ALL remote clusters to be available for discovery.
Assuming that I have multiple clusters (e.g. 5) and only 1 is not available this hard dependency effects all clusters and 'blast-radius' can be an issue where in fact 4 available clusters can work fine if only 1 cluster is not available.

To address that, an option to better control this configuration and making not all clusters as hard dependency can be useful.

Alternatives:
1. Specify for each remote cluster if it's 'mandatory' or 'optional'.  This is good if we know there are some dependencies between specific clusters.  It can also fit well a multi-region setup if for example you have multiple clusters in a region so they will be 'mandatory' vs. clusters on other regions which will be 'optional'.
2. Configuring a threshold for minimal available clusters, e.g. as % of total remote clusters or as a required min #, e.g. 2 available clusters is enough.  This makes sense if all clusters are the same without any specifics.
3. Using some other params / meta-data to make clusters mandatory/optional or to have some weight.  e.g. clusters in same region are mandatory, some tags/labels etc. (but this approach can have strong dependency on the cloud provider or environment you run in)
4. Any combination of the above.

[ ] Docs
[ ] Installation
[X] Networking
[X] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

[X] Multi Cluster
[ ] Virtual Machine
[?] Multi Control Plane

**Additional context**

**Comment by ramaraochavali** [comment]
@nmittler @stevenctl for your thoughts?

**Comment by ramaraochavali** [comment]
Nevermind. I saw @stevenctl  created this https://github.com/istio/istio/issues/30838 already. I am going to close this. Let us track this requirement there.
