### ISSUE TITLE
Authentification errors with multicluster "primary-remote" installation

### ISSUE THREAD

**Issue by ignatenko451** [istio/istio#30869]
**Bug description**
Authentification errors with multicluster "primary-remote" installation 

[ ] Docs
[x] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Multi-cluster installation finished successfuly

**Steps to reproduce the bug**
Generate certs in complaint with https://istio.io/latest/docs/tasks/security/cert-management/plugin-ca-cert/

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
$ istioctl version --remote
client version: 1.9.0
control plane version: 1.9.0
data plane version: 1.9.0 (2 proxies)
$ kubectl version --short
Client Version: v1.20.2
Server Version: v1.20.2
$ istioctl version --remote --context=cluster2
client version: 1.9.0
control plane version: 1.9.0
data plane version: none
$ kubectl version --short --context=cluster2
Client Version: v1.20.2
Server Version: v1.20.2

**How was Istio installed?**
I deploy Istio in multicluster configuration "master-remote".
Certs generated for each cluster (cacerts) in complaint with official Istio docs (also tried pre-generated certs from "samples" directory).
I use MetalLB to make use of EXTERNAL-IP for LoadBalancer services.
At the main cluster Istio installation goes with "--set meshConfig.defaultConfig.controlPlaneAuthPolicy=MUTUAL_TLS" parameter. IngressGateway и EastwestGateway deployment finished successfuly, logs has no errors and has a message that "Envoy proxy is ready".
At Istio installation on the remote cluster (also with "--set meshConfig.defaultConfig.controlPlaneAuthPolicy=MUTUAL_TLS" parameter), installation doesn't finish with success in the "IngressGateway" Deployment with error: "Readiness probe failed: Get "http://10.244.0.28:15021/healthz/ready": dial tcp 10.244.0.28:15021: connect: connection refused", but the pod is running and has "Ready" state. Pod's log has errors: "upstream terminated with unexpected error rpc error: code = Unknown desc = authentication failure". 
Main and remote Istiod also have errors.
All logs are attached.

**Environment where the bug was observed (cloud vendor, OS, etc)**
K8S:
on-premise (v1.20.2)
OS (on both clusters):
$  cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
$ uname -r (main cluster)
5.4.15-1.el7.elrepo.x86_64
$ uname -r (remote cluster)
5.4.6-1.el7.elrepo.x86_64

[main-logs-from-discovery-in-istiod-5c99f659cf-f6jvn.txt](https://github.com/istio/istio/files/5989577/main-logs-from-discovery-in-istiod-5c99f659cf-f6jvn.txt)
[main-logs-from-istio-proxy-in-istio-eastwestgateway-5d65f7f56f-jqhzx.txt](https://github.com/istio/istio/files/5989578/main-logs-from-istio-proxy-in-istio-eastwestgateway-5d65f7f56f-jqhzx.txt)
[main-logs-from-istio-proxy-in-istio-ingressgateway-66bfc5f7f8-xjmv5.txt](https://github.com/istio/istio/files/5989579/main-logs-from-istio-proxy-in-istio-ingressgateway-66bfc5f7f8-xjmv5.txt)
[bug-report.zip](https://github.com/istio/istio/files/5989580/bug-report.zip)
[remote-logs-from-discovery-in-istiod-764b9f57b8-v5vpk.txt](https://github.com/istio/istio/files/5989581/remote-logs-from-discovery-in-istiod-764b9f57b8-v5vpk.txt)
[remote-logs-from-istio-proxy-in-istio-ingressgateway-69bb6c4bf9-szzzk.txt](https://github.com/istio/istio/files/5989583/remote-logs-from-istio-proxy-in-istio-ingressgateway-69bb6c4bf9-szzzk.txt)

**Comment by itsecforu** [comment]
Got the same errors!

Did somebody solve that ?

**Comment by hzxuzhonghu** [comment]
>: dial tcp 10.244.0.28:15021: connect: connection refused", 

It seems kubelet can not connect to istio-proxy, not relevant to authentication. I would suggest checking your k8s container network.

**Comment by ignatenko451** [comment]
Thanks for answer!
After reinstallation cni plugins and Istio on both clusters.
Now I have this:
1. Error on main cluster's Istiod pod:
"2021-03-02T11:02:34.873511Z	error	ads	Failed to authenticate client from 10.244.0.61:52834: Authenticator ClientCertAuthenticator: no verified chain is found; Authenticator KubeJWTAuthenticator: could not get cluster cluster2's kube client"
2. In the remote cluster I have an istio-ingressgateway pod's error:
"2021-03-02T11:27:01.304572Z	warn	Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 0 successful, 0 rejected; lds updates: 0 successful, 0 rejected".
istio-ingressgateway deployment still have Failed status (but corresponding pod is Ready same like early), and eror: "Readiness probe failed: HTTP probe failed with statuscode: 503"


Also, I verified that the two cluster have the same istio-ca-root-cert configured.
Have you got any ideas? I will be very thanksful.

**Comment by hzxuzhonghu** [comment]
> Authenticator KubeJWTAuthenticator: could not get cluster cluster2's kube client

Have you created a secret containing the kubeconfig needed to connect to cluster2?

**Comment by ignatenko451** [comment]
Many thanks!
Of cource I generated the secret according with manual. But by default, secret creates in the default namespace.
After creating secret in the istio-system namespace  errors gone at all.
(I used command: istioctl x create-remote-secret  --namespace istio-system)

I did something wrong? Or, may be it is need  it is need to fix the manuals?
