### ISSUE TITLE
Operator canary upgrades are updating istiod in-place

### ISSUE THREAD

**Issue by h0tbird** [istio/istio#30873]
**Bug description**
Canary operator upgrades like `istioctl operator init --revision 1-8-3`
are not behaving like their equivalent `istioctl install --revision 1-8-3`
The `istiod` pod is upgraded _in-place_ instead of running the old and new versions _side-by-side_.

[x] Upgrade

**Expected behavior**
Upgrading from vanilla `1.7.1` to vanilla `1.8.3` using
```
istioctl operator init --revision 1-8-3
kubectl apply -f ./istio-1.8.3/manifests/profiles/default.yaml
````
Should result in multiple `istiod` pods running _side-by-side_.

**Steps to reproduce the bug**
Install vanilla `1.7.1`:
```bash
~/Downloads/istio/istio-1.7.1/bin/istioctl operator init
Using operator Deployment image: docker.io/istio/operator:1.7.1
✔ Istio operator installed
✔ Installation complete

# Use vim to set metadata.name: installed-state-1-7-1
k apply -f ~/Downloads/istio/istio-1.7.1/manifests/profiles/default.yaml
istiooperator.install.istio.io/installed-state-1-7-1 created
```

Upgrade to vanilla `1.8.3`:
```bash
~/Downloads/istio/istio-1.8.3/bin/istioctl operator init --revision 1-8-3
Installing operator controller in namespace: istio-operator using image: docker.io/istio/operator:1.8.3
Operator controller will watch namespaces: istio-system
2021-02-16T14:32:22.247378Z	info	proto: tag has too few fields: "-"
✔ Istio operator installed
✔ Installation complete

# Use vim to set metadata.name: installed-state-1-8-3 and spec.revision: 1-8-3
k apply -f ~/Downloads/istio/istio-1.8.3/manifests/profiles/default.yaml
istiooperator.install.istio.io/installed-state-1-8-3 created
```

**Version**
```
kubectl version --short
Client Version: v1.20.2
Server Version: v1.17.12-eks-7684af
```

**Environment where the bug was observed (cloud vendor, OS, etc)**
EKS

**Comment by h0tbird** [comment]
This issue might be a duplicate of https://github.com/istio/istio/issues/28964

**Comment by shamsher31** [comment]
@h0tbird I think the `installed-state` will be automatically maintained by `istioctl install` so instead of using `kubectl apply`, you can use `istioctl install` and you don't need to update anything manually.

```
[istio-1.7.1]$ ./bin/istioctl operator init
Using operator Deployment image: docker.io/istio/operator:1.7.1
✔ Istio operator installed                                                                       
✔ Installation complete

[istio-1.7.1]$ ./bin/istioctl install
This will install the default Istio profile into the cluster. Proceed? (y/N) y
✔ Istio core installed                                                                           
✔ Istiod installed                                                                               
✔ Ingress gateways installed                                                                     
✔ Installation complete

[istio-1.7.1]$ k get po -n istio-operator
NAME                              READY   STATUS    RESTARTS   AGE
istio-operator-7794f79696-xf7vq   1/1     Running   0          4m33s
```

```
[istio-1.8.3]$ ./bin/istioctl operator init -r 1-8-3
Installing operator controller in namespace: istio-operator using image: docker.io/istio/operator:1.8.3
Operator controller will watch namespaces: istio-system
2021-02-23T10:50:44.576819Z     info    proto: tag has too few fields: "-"
✔ Istio operator installed                                                                       
✔ Installation complete

[istio-1.8.3]$ k get po -n istio-operator
NAME                                    READY   STATUS    RESTARTS   AGE
istio-operator-1-8-3-5df5c56fc4-jz7bc   1/1     Running   0          53s
istio-operator-7794f79696-xf7vq         1/1     Running   0          5m45s

[istio-1.8.3]$ ./bin/istioctl install -r 1-8-3
This will install the Istio default profile with ["Istio core" "Istiod" "Ingress gateways"] components into the cluster. Proceed? (y/N) y
✔ Istio core installed                                                                           
✔ Istiod installed                                                                               
✔ Ingress gateways installed                                                                     
✔ Installation complete                                                                          

```

> The istiod pod is upgraded in-place instead of running the old and new versions side-by-side.

Here is the istiod pod running both 1.7.1 and 1.8.3 side by side.

```
[istio-1.8.3]$ k get po -n istio-system
NAME                                    READY   STATUS    RESTARTS   AGE
istio-ingressgateway-74b65dbf59-hqkww   1/1     Running   0          17s
istiod-1-8-3-6c57df49f-k5nhr            1/1     Running   0          93s
istiod-6dd8688b59-fp8f7                 1/1     Running   0          21s
```

**Comment by h0tbird** [comment]
Thanks @shamsher31.
I might be wrong here but I _think_ that `istioctl operator` and `istioctl install` commands are not meant to be mixed.
The canary upgrade I am trying to reproduce is the one defined here: https://istio.io/v1.8/docs/setup/install/operator/#canary-upgrade.

**Comment by shamsher31** [comment]
Looks like if the CR name starts with `installed-state` it will be ignored. See https://github.com/istio/istio/issues/29394.

**Comment by shamsher31** [comment]
This is fixed in `1.9.1` version. If you have `1.7.1` installed and upgrade your cluster to use `1.9.1`.


```
~/Downloads/istio/istio-1.9.1/bin/istioctl operator init --revision 1-9-1
Installing operator controller in namespace: istio-operator using image: docker.io/istio/operator:1.9.1
Operator controller will watch namespaces: istio-system
2021-03-16T14:32:22.247378Z	info	proto: tag has too few fields: "-"
✔ Istio operator installed
✔ Installation complete

# do not use installed-state as an iop name
# Use vim to set metadata.name: istio-1-9-1 and spec.revision: 1-9-1
k apply -f ~/Downloads/istio/istio-1.9.1/manifests/profiles/default.yaml
istiooperator.install.istio.io/istio-1-9-1 created
```

you won't see an in-place upgrade issue and there are two istiod pods running side by side.

```
$ k get pod -n istio-system
NAME                                    READY   STATUS    RESTARTS   AGE
istio-ingressgateway-657f9f8d94-s8fzd   1/1     Running   0          81s
istiod-1-9-1-745d975d59-bvv4s           1/1     Running   0          119s
istiod-77dbf7c5b6-c6p67                 1/1     Running   0          6m54s
```

**Comment by ludovicbonivert** [comment]
@shamsher31 I tried your suggestion, upgrading from 1.7.0 to 1.9.1 but this keeps doing an in place upgrade.

`bonivert@Azure:~/istio-1.9.5/bin$ k get iop

NAME                REVISION   STATUS    AGE

istiocontrolplane              HEALTHY   78s

bonivert@Azure:~/istio-1.9.5/bin$ ./istioctl operator init --revision 1-9-5 -f istiocontrolplane.yaml --operatorNamespace istio-system

Installing operator controller in namespace: istio-system using image: docker.io/istio/operator:1.9.5

Operator controller will watch namespaces: istio-system

2021-05-17T14:10:48.119305Z     info    proto: tag has too few fields: "-"

✔ Istio operator installed

✔ Istio operator installed

✔ Installation complete

bonivert@Azure:~/istio-1.9.5/bin$ k get iop

NAME                REVISION   STATUS        AGE

istiocontrolplane   1-9-5      RECONCILING   2m

 

bonivert@Azure:~/istio-1.9.5/bin$ k get pod -w

NAME                                    READY   STATUS    RESTARTS   AGE

istio-egressgateway-694f64b68c-gflqz    1/1     Running   0          2m33s

istio-egressgateway-694f64b68c-xvfs9    1/1     Running   0          2m33s

istio-ingressgateway-68d994f5cd-46brv   1/1     Running   0          2m33s

istio-ingressgateway-68d994f5cd-nt2f8   1/1     Running   0          2m33s

istio-operator-1-9-4-6cf5b4854c-hthql   1/1     Running   0          2m17s

istio-operator-1-9-5-6459c798f6-7l2hk   1/1     Running   0          2m59s

istio-operator-865b7569bb-shb24         1/1     Running   0          4m57s

istiod-1-9-5-7dd79db7dc-hnslm           1/1     Running   0          2m43s

istiod-1-9-5-7dd79db7dc-wlwxp           1/1     Running   0          2m43s

istiod-98df8ff-wsj4k                    1/1     Running   0          2m43s

istiod-98df8ff-wtxwb                    1/1     Running   0          2m43s

jaeger-75948789b4-6q8xw                 1/1     Running   0          3m28s

prometheus-5f994f56b9-tvpsf             0/2     Pending   0          3m28s

 

bonivert@Azure:~/istio-1.9.5/bin$ k describe pod istiod-98df8ff-wsj4k | grep -i image

    Image:         docker.io/istio/pilot:1.9.5`

**Comment by ludovicbonivert** [comment]
I modified the istiocontrolplane.yaml to include
- the revision 1-9-5
- modified the name of the iop to istiocontrolplane-1-9-5 
Now the canary upgrade works fine. I've followed the steps described at https://istio.io/latest/docs/setup/install/operator/

But the uninstall of the old control plane doesn't work. i deleted the old iop and the old resources keeps being present in the cluster.
