### ISSUE TITLE
IST0134 ServiceEntryAddressesRequired missing documentation

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#30872]
https://istio.io/latest/docs/reference/config/analysis/ist0134 is a 404

This message is also not accurate: `Warning [IST0134] (ServiceEntry communication-service-db-service-entry.default) ServiceEntry addresses are required for this protocol.`.

Its not *required*, it just probably is not what you want.

https://preliminary.istio.io/latest/blog/2020/dns-proxy/#external-tcp-services-without-vips describes this problem very well

**Comment by shamsher31** [comment]
@zufardhiyaulhaq can you please check.

**Comment by zufardhiyaulhaq** [comment]
will check, will raise PR related to documentations

**Comment by shamsher31** [comment]
Will be close by https://github.com/istio/istio.io/pull/9100
