### ISSUE TITLE
TestRevisionedUpgrade test flake

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#30880]
https://prow.istio.io/view/gs/istio-prow/logs/integ-k8s-117_istio_postsubmit/1361869884937474048

cc @Monkeyanator

**Comment by ramaraochavali** [comment]
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30853/integ-pilot-k8s-tests_istio/1361929913489166336 - This is really flaky not passing atleast on my PR https://github.com/istio/istio/pull/30830 and https://github.com/istio/istio/pull/30853

**Comment by Monkeyanator** [comment]
Looking into it, could have something to do with [https://github.com/istio/istio/pull/30675](https://github.com/istio/istio/pull/30675) which improved echo `Restart` logic
