### ISSUE TITLE
Increase in source_app being reported as "unknown" for HTTP 200 requests in 1.8.2

### ISSUE THREAD

**Issue by AlexDHoffer** [istio/istio#30898]
**Bug description**

After deploying Istio 1.8.2 on our cluster, there has been a noticeable jump in the source app being "unknown" on the istio_requests_total metric. This is in stark contrast to before, where no requests were being labeled as such.

The graph below shows the effect - before the upgrade, no HTTP 200 codes. After, they occur consistently. 

![image](https://user-images.githubusercontent.com/19369483/108257451-a286e980-7113-11eb-9e90-f87ec1e8fad5.png)

Note that it doesn't seem to be re-classifying requests from the ingress gateway as "unknown", either - HTTP 200 from the source_app of istio-ingressgateway is pretty much the same before and after the deployment:

![image](https://user-images.githubusercontent.com/19369483/108257580-d6faa580-7113-11eb-9b5c-b9d2bf97200c.png)

Is there any explanation for this behavior?

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ x ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

No change in source_app reporting in telemetry between versions

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

Istio 1.8.2, Helm v3.5.0

**How was Istio installed?**

Using the Istio Operator and Istio Profile, standalone via Helm with our own supplied values.

**Environment where the bug was observed (cloud vendor, OS, etc)**

Azure Kubernetes Service

**Comment by howardjohn** [comment]
Can you add the full (unaggregated) metric that is "unknown"? which may give more info about the type of traffic this is

**Comment by AlexDHoffer** [comment]
> Can you add the full (unaggregated) metric that is "unknown"? which may give more info about the type of traffic this is

round(sum(rate(istio_requests_total{cluster="$cluster",reporter="destination",destination_service_name="$service", destination_service_namespace="$namespace", source_app="unknown"}[2m])) by (source_app, response_code), 0.001)

^ let me know if that's sufficient...

**Comment by howardjohn** [comment]
Looks good

**Comment by howardjohn** [comment]
Sorry if it wasn't clear, can you give the result of the query?

**Comment by AlexDHoffer** [comment]
The result is this:

![image](https://user-images.githubusercontent.com/19369483/108388220-454a7100-71c3-11eb-8f21-f17c1eeaa2f3.png)

Each one of those lines is one of our apps in our Istio-injected namespace getting requests from this unknown app. The first line coincides with when we upgraded.

**Comment by howardjohn** [comment]
I am looking for the output from prometheus like
```
container_cpu_user_seconds_total{beta_kubernetes_io_arch="amd64",beta_kubernetes_io_instance_type="e2-standard-4",beta_kubernetes_io_os="linux",cloud_google_com_gke_boot_disk="pd-standard",cloud_google_com_gke_netd_ready="true",cloud_google_com_gke_nodepool="e2",cloud_google_com_gke_os_distribution="cos",cloud_google_com_machine_family="e2",container="POD"}
```

With all of the labels and values present. (ignore the fact I used `container_cpu_user_seconds_total`, I didn't have istio on the cluster I grabbed that from)

**Comment by AlexDHoffer** [comment]
@howardjohn 

Here's a couple results (there's a lot):

istio_requests_total{app="redacted", app_kubernetes_io_instance="redacted-api", app_kubernetes_io_name="redacted", cluster="dev1", connection_security_policy="none", destination_app="redacted", destination_canonical_revision="latest", destination_canonical_service="redacted", destination_principal="unknown", destination_service="redacted-service.default.svc.cluster.local", destination_service_name="redacted-service", destination_service_namespace="default", destination_version="unknown", destination_workload="redacted-api", destination_workload_namespace="default", geo="us", instance="10.1.2.182:15090", istio_io_rev="default", job="envoy-stats", namespace="default", pod_name="redacted-api-55d8d7b46b-n2l2r", pod_template_hash="55d8d7b46b", prometheus="monitoring/prometheus-operator", region="westus", reporter="destination", request_protocol="http", response_code="200", response_flags="-", security_istio_io_tlsMode="istio", service_istio_io_canonical_name="redacted", service_istio_io_canonical_revision="latest", source_app="unknown", source_canonical_revision="latest", source_canonical_service="unknown", source_principal="unknown", source_version="unknown", source_workload="unknown", source_workload_namespace="unknown"}

istio_requests_total{app="other-redacted", app_kubernetes_io_instance="other-redacted-api", app_kubernetes_io_name="other-redacted", cluster="dev1", connection_security_policy="none", destination_app="other-redacted", destination_canonical_revision="latest", destination_canonical_service="tenant", destination_principal="unknown", destination_service="other-redacted-service.default.svc.cluster.local", destination_service_name="other-redacted-service", destination_service_namespace="default", destination_version="unknown", destination_workload="other-redacted-api", destination_workload_namespace="default", geo="us", instance="10.1.5.62:15090", istio_io_rev="default", job="envoy-stats", namespace="default", pod_name="other-redacted-6fff5d448b-zl2g7", pod_template_hash="6fff5d448b", prometheus="monitoring/prometheus-operator", region="westus", reporter="destination", request_protocol="http", response_code="200", response_flags="-", security_istio_io_tlsMode="istio", service_istio_io_canonical_name="other-redacted", service_istio_io_canonical_revision="latest", source_app="unknown", source_canonical_revision="latest", source_canonical_service="unknown", source_principal="unknown", source_version="unknown", source_workload="unknown", source_workload_namespace="unknown"}

**Comment by howardjohn** [comment]
cc @bianpengyuan does this seem like it could be related to the inbound cluster change?

@AlexDHoffer do these `redacted` and `other-redacted` happen to have multiple Services selecting the same workload?

**Comment by AlexDHoffer** [comment]
> @AlexDHoffer do these `redacted` and `other-redacted` happen to have multiple Services selecting the same workload?

I don't believe so, but I may be misunderstanding what you mean by selecting the same workload.

**Comment by bianpengyuan** [comment]
At destination side, source_app or any other source workload labels should be retrieved from exchanged metadata, instead of xds resource metadata.

@AlexDHoffer do you see a drop of other normal time series (i.e. time series with source app / workload labels filled correctly). Want to understand if this is deterministic or random behavior.

**Comment by AlexDHoffer** [comment]
@bianpengyuan It seems to me like the other timeseries have been normal. Here's a graph of non-unknown sources for that metric:

![image](https://user-images.githubusercontent.com/19369483/108404160-649dca00-71d4-11eb-8370-29dda52ed85d.png)

The deployment occurred on 2/12. The pattern appears to be similar before and after the deployment.

**Comment by bianpengyuan** [comment]
@AlexDHoffer which version did you upgrade this from?

**Comment by bianpengyuan** [comment]
Also could you narrow down the query to a particular pod or destination_workload where unknown label stats is generated from?

**Comment by AlexDHoffer** [comment]
> @AlexDHoffer which version did you upgrade this from?

1.5.x. 

> Also could you narrow down the query to a particular pod or destination_workload where unknown label stats is generated from?

It is 7 destination_workloads, out of our 15 or so deployments. I just realized the destination_workloads that report receiving traffic from source_app = "unknown" are strictly the ones that have other metrics being scraped aside from Istio telemetry. As in, ports open with permissive mTLS being scraped for app-level metrics.

**Comment by bianpengyuan** [comment]
> It is 7 destination_workloads, out of our 15 or so deployments. I just realized the destination_workloads that report receiving traffic from source_app = "unknown" are strictly the ones that have other metrics being scraped aside from Istio telemetry. As in, ports open with permissive mTLS being scraped for app-level metrics.

Ok that explains `unknown` source, since prometheus is not injected. Although I cannot think of why unknown source labels are not seen in earlier versions. So there is no change on your side re prometheus scraping?

**Comment by bianpengyuan** [comment]
> I did a normal pathway of 1.5.x -> 1.6.1 -> 1.7.1 -> 1.8.2, updating resources as needed between each release.

So which update causes this exactly? Is it the last update from 1.7.1 -> 1.8.2?

**Comment by AlexDHoffer** [comment]
> > It is 7 destination_workloads, out of our 15 or so deployments. I just realized the destination_workloads that report receiving traffic from source_app = "unknown" are strictly the ones that have other metrics being scraped aside from Istio telemetry. As in, ports open with permissive mTLS being scraped for app-level metrics.
> 
> Ok that explains `unknown` source, since prometheus is not injected. Although I cannot think of why unknown source labels are not seen in earlier versions. So there is no change on your side re prometheus scraping?

There is no change as far as prometheus scraping goes for us.




> > I did a normal pathway of 1.5.x -> 1.6.1 -> 1.7.1 -> 1.8.2, updating resources as needed between each release.
> 
> So which update causes this exactly? Is it the last update from 1.7.1 -> 1.8.2?

I’m not certain. I wasn’t paying close attention to the metrics as I upgraded. I could revert back to 1.5.1 and upgrade again in that way, but it is a bit arduous...

**Comment by bianpengyuan** [comment]
> I’m not certain. I wasn’t paying close attention to the metrics as I upgraded. I could revert back to 1.5.1 and upgrade again in that way, but it is a bit arduous...

No, definitely no need to do that. I think this works as intended, so nothing needs to fix it here..

**Comment by AlexDHoffer** [comment]
> > I’m not certain. I wasn’t paying close attention to the metrics as I upgraded. I could revert back to 1.5.1 and upgrade again in that way, but it is a bit arduous...
> 
> No, definitely no need to do that. I think this works as intended, so nothing needs to fix it here..

So do you think we should just accept this as likely to be metrics scraping responsible? It seems to be the most likely explanation. Any way we can get it labeled so it’s not unknown?

**Comment by bianpengyuan** [comment]
Two options:

1) If you are don't care if the scrape request going through proxy or not (since you are using permissive, I guess most likely it does not matter to you), you can use metric merging: https://istio.io/latest/docs/ops/integrations/prometheus/#option-1-metrics-merging

2) If for some reason you want scraping request to go though sidecar (e.g. you want to monitor prometheus scrape request). You can use metric customization to add a label to it based on the path, to indicate if this is a prometheus request.

**Comment by AlexDHoffer** [comment]
> Two options:
> 
> 1. If you are don't care if the scrape request going through proxy or not (since you are using permissive, I guess most likely it does not matter to you), you can use metric merging: https://istio.io/latest/docs/ops/integrations/prometheus/#option-1-metrics-merging
> 2. If for some reason you want scraping request to go though sidecar (e.g. you want to monitor prometheus scrape request). You can use metric customization to add a label to it based on the path, to indicate if this is a prometheus request.

But, by this doc- we are already using metric merging, since it's enabled by default in our version. Is there something I'm missing?

**Comment by bianpengyuan** [comment]
You need to update your existing prometheus annotation to make it stop scraping application container directly, and instead let istio handle prometheus annotations.

**Comment by howardjohn** [comment]
The metrics merging should rewrite the users annotations

**Comment by AlexDHoffer** [comment]
Yes, all of our pods already have those standard annotations...

**Comment by AlexDHoffer** [comment]
Is there a way we could ignore this traffic and not have Istio collect metrics about it? The concern here is that these metric scraping 200s will artificially inflate any calculations surrounding HTTP response success percentages unless we purposely ignore all source = "unknown".

**Comment by bianpengyuan** [comment]
Could you check the prometheus annotations of those application pod and see if they are rewritten to istio metrics merge path (/state/prometheus) and port (15020)? If so we'd need to further investigate and understand how are those unknown source metrics generated, since prometheus scraping should not go through proxy sidecar if prom annotations are rewritten successfully.

**Comment by AlexDHoffer** [comment]
@bianpengyuan I can confirm the annotations are rewritten to Istio metrics merge path. Each one of the pods that is reporting this behavior has annotations of the following:

````
                     prometheus.io/path: /stats/prometheus
                      prometheus.io/port: 15020
                      prometheus.io/scrape: true
````

**Comment by bianpengyuan** [comment]
Looks like your prometheus is still scraping 15090. If you look at the time series pasted at https://github.com/istio/istio/issues/30898#issuecomment-781473138, they are scraped from `15090`.

Is it possible that your prometheus is still configured to scrape envoy stats (scrape `http-envoy-prom` port) and application metrics separately?

**Comment by Starefossen** [comment]
have the same issue but with Istio v1.9.0, the changed Prometheus to scrape the merging port `15020` but without any results. TCP traffic is still reported as `unknown`.

![Screenshot 2021-02-23 at 12 53 10](https://user-images.githubusercontent.com/968267/108840039-17f02f80-75d6-11eb-82ca-a11b43ac5909.png)

Unkown traffic in the Kiali screenshot above originates from gitea as tcp traffic to the memcached and postgresql pods.

**Comment by bianpengyuan** [comment]
@Starefossen this is likely something different. Is the source for those db connections have sidecar injected? Do you have mTLS turned off? https://istio.io/latest/faq/metrics-and-logs/#telemetry-v1-vs-v2

**Comment by Starefossen** [comment]
> @Starefossen this is likely something different. Is the source for those db connections have sidecar injected? Do you have mTLS turned off? https://istio.io/latest/faq/metrics-and-logs/#telemetry-v1-vs-v2

All pods in the namespace (including the databases) have envoy proxy sidecar injected. mTLS is turned on.

**Comment by bianpengyuan** [comment]
@Starefossen could you provide the full `istio_tcp_received_bytes_total` time series with unknown source?

**Comment by Starefossen** [comment]
> @Starefossen could you provide the full `istio_tcp_received_bytes_total` time series with unknown source?

Here: https://gist.github.com/Starefossen/6bded64f4d650ee1d69c98c7b5de9ee0

**Comment by AlexDHoffer** [comment]
@bianpengyuan I do have a service monitor that is scraping the application metrics. When I remove it, the unknown goes away, but so do the metrics I need. It seems like the metrics merging is not actually working for me.

**Comment by bianpengyuan** [comment]
@AlexDHoffer You'd need to not only remove the ServiceMonitor, but also update prometheus to scrape based on standard annotations （i.e. scraping 15020 as prometheus.io annotation indicates, instead of `http-envoy-prom` port）.

@Starefossen Could you please create a separated issue? Based on your metrics, it looks like tcp exchange is not happening, which we need to troubleshoot separately.

**Comment by AlexDHoffer** [comment]
@bianpengyuan I've tried doing that by doing this:

````
      - job_name: 'envoy-stats-test'
        metrics_path: /stats/prometheus
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port]
          action: keep
          regex: 15020
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: keep
          regex: /stats/prometheus
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
````

but it scrapes every port but 15020...

**Comment by bianpengyuan** [comment]
We have some samples that you probably could reference: https://github.com/istio/istio/blob/37d5d6e91ccd6bc54a53516e2cf4469d36e3bbf9/samples/addons/prometheus.yaml#L217

**Comment by AlexDHoffer** [comment]
@bianpengyuan Adding those scrape configs fixed the problem. Closing the issue. Thanks for the help.

**Comment by devevarde** [comment]
> Looks like your prometheus is still scraping 15090. If you look at the time series pasted at [#30898 (comment)](https://github.com/istio/istio/issues/30898#issuecomment-781473138), they are scraped from `15090`, instead of the merging port `15020`.
> 
> Is it possible that your prometheus is still configured to scrape envoy stats (scrape `http-envoy-prom` port) and application metrics separately?

Hi Can u please give more details here ?

I have same issue see the following

![image](https://github.com/istio/istio/assets/52662766/705d485d-32e9-4ca9-85d2-ce2df39cf265)

I have some workloads anntotated with 

prometheus.io/path: /stats/prometheus
prometheus.io/port: 15020
prometheus.io/scrape: true

But some of them have thier own Service monitor 

│     prometheus.io/path: /metrics                                                                                                                                                    │
│     prometheus.io/port: "8084"                                                                                                                                                      │
│     prometheus.io/scrape: "true"

please advice?
