### ISSUE TITLE
Setting up external control plane in AWS EKS and running into errors

### ISSUE THREAD

**Issue by ptembey-jnpr** [istio/istio#30899]
I am trying to set up an external control plane in EKS with a remote cluster in a different VPC. I would like some clarification on the following two points mentioned in the documentation: https://istio.io/latest/docs/setup/additional-setup/external-controlplane/

1. What would be SSL_SECRET_NAME be set to in this environment? Is it a self-signed certificate as described in https://istio.io/latest/docs/tasks/traffic-management/ingress/secure-ingress/ ? I have tried doing this however the remote cluster ingress complains of unknown CA - which is valid because it does not have the root CA set. Or is this the secret that could be created by plugging in a different CA following: https://istio.io/latest/docs/tasks/security/cert-management/plugin-ca-cert/ ?

2. What is the significance of 
    proxyMetadata:
        XDS_ROOT_CA: /etc/ssl/certs/ca-certificates.crt
        CA_ROOT_CA: /etc/ssl/certs/ca-certificates.crt in the remote control plane and external control plane configuration?
        Is this a constant that is known to exist in an environment and will it apply to AWS EKS?
        
I haven't had much success in setting this up with the TLS termination happening at the ingress in the external control plane. I also tried a TLS passthrough configuration at the external control plane's ingress gateway - however then I ran into an error during Istio proxy injection in the remote cluster replica set: 
Warning  FailedCreate  8m43s (x18 over 19m)  replicaset-controller  Error creating: Internal error occurred: failed calling webhook "sidecar-injector.istio.io": Post https://xxxxxx-xxxx.us-west-2.elb.amazonaws.com:15017/inject?timeout=30s: x509: certificate signed by unknown authority.

Any pointers are much appreciated. I think that the documentation could be updated to clarify the requirements better such as generation of TLS certs and where to set them i.e., in what namespace in the external cluster since there are two control planes in the external cluster - one to control the istio-ingress, and the other to control the remote cluster.

**Comment by ptembey-jnpr** [comment]
These are my configurations with TLS passthrough from remote cluster to external cluster. The istiod in external cluster is running and can connect to the remote cluster. The ingress gateway in remote cluster is running too. However proxy injection fails for all pods.

Remote/Config cluster:
`apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
 namespace: external-istiod
spec:
  profile: remote
  meshConfig:
    rootNamespace: external-istiod
    defaultConfig:
      discoveryAddress: xxx.us-west-2.elb.amazonaws.com:15012
      controlPlaneAuthPolicy: MUTUAL_TLS
  components:
    pilot:
      enabled: false
    istiodRemote:
      enabled: true

  values:
    global:
      caAddress: xxx.us-west-2.elb.amazonaws.com:15012
      istioNamespace: external-istiod
      meshID: mesh1
      multiCluster:
        clusterName: xxx.us-west-2.eksctl.io 
    istiodRemote:
      injectionURL: https://xxx.us-west-2.elb.amazonaws.com:15017/inject
    base:
      validationURL: https://xxx.us-west-2.elb.amazonaws.com:15017/validate`
--
External control plane:
`
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: external-istiod
spec:
  meshConfig:
    rootNamespace: external-istiod
    defaultConfig:
      discoveryAddress: xxx.us-west-2.elb.amazonaws.com:15012
      controlPlaneAuthPolicy: MUTUAL_TLS
  components:
    base:
      enabled: false
    ingressGateways:
    - name: istio-ingressgateway
      enabled: false
  values:
    global:
      caAddress: xxx.us-west-2.elb.amazonaws.com:15012
      istioNamespace: external-istiod
      operatorManageWebhooks: true
      meshID: mesh1
      multiCluster:
        clusterName: xxx.us-west-2.eksctl.io 
    pilot:
      env:
        INJECTION_WEBHOOK_CONFIG_NAME: ""
        VALIDATION_WEBHOOK_CONFIG_NAME: ""
`
Gateways/VSs:
`
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: external-istiod-gw
  namespace: external-istiod
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 15012
        protocol: tls 
        name: tls-XDS
      tls:
        mode: PASSTHROUGH
      hosts:
      - xxx.us-west-2.elb.amazonaws.com
    - port:
        number: 15017
        protocol: tls
        name: tls-WEBHOOK
      tls:
        mode: PASSTHROUGH
      hosts:
      - xxx.us-west-2.elb.amazonaws.com
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
   name: external-istiod-vs
   namespace: external-istiod
spec:
    hosts:
    - xxx.us-west-2.elb.amazonaws.com
    gateways:
    - external-istiod-gw
    tls:
    - match:
      - port: 15012
        sniHosts:
        - xxx.us-west-2.elb.amazonaws.com
      route:
      - destination:
          host: istiod.external-istiod.svc.cluster.local
          port:
            number: 15012
    - match:
      - port: 15017
        sniHosts:
        - xxx.us-west-2.elb.amazonaws.com
      route:
      - destination:
          host: istiod.external-istiod.svc.cluster.local
          port:
            number: 443

`
Ingress gateway in istio-system namespace of external cluster:
`
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          service:
            ports:
              - port: 15021
                targetPort: 15021
                name: status-port
              - port: 15012
                targetPort: 15012
                name: tls-xds
              - port: 15017
                targetPort: 15017
                name: tls-webhook

`
The mutating webhook configuration in remote cluster shows an empty caBundle:
`
 webhooks:
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    url: https://xxx.us-west-2.elb.amazonaws.com:15017/inject
  failurePolicy: Fail
  matchPolicy: Exact
  name: sidecar-injector.istio.io
  namespaceSelector:
    matchLabels:
      istio-injection: enabled
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
    scope: '*'
  sideEffects: None
  timeoutSeconds: 30

`
kubectl describe rs helloworld -n foo
Name:           helloworld-v1-5b75657f75
Namespace:      foo
Selector:       app=helloworld,pod-template-hash=5b75657f75,version=v1
Labels:         app=helloworld
                pod-template-hash=5b75657f75
                version=v1
Annotations:    deployment.kubernetes.io/desired-replicas: 1
                deployment.kubernetes.io/max-replicas: 2
                deployment.kubernetes.io/revision: 1
Controlled By:  Deployment/helloworld-v1
Replicas:       0 current / 1 desired
Pods Status:    0 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:  app=helloworld
           pod-template-hash=5b75657f75
           version=v1
  Containers:
   helloworld:
    Image:      docker.io/istio/examples-helloworld-v1
    Port:       5000/TCP
    Host Port:  0/TCP
    Requests:
      cpu:        100m
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Conditions:
  Type             Status  Reason
  ----             ------  ------
  ReplicaFailure   True    FailedCreate
Events:
  Type     Reason        Age                From                   Message
  ----     ------        ----               ----                   -------
  Warning  FailedCreate  8s (x13 over 28s)  replicaset-controller  Error creating: Internal error occurred: failed calling webhook "sidecar-injector.istio.io": Post https://xxx.us-west-2.elb.amazonaws.com:15017/inject?timeout=30s: x509: certificate signed by unknown authority

Anything that I am missing? 
The ingress gateway in remote cluster is up and istiod is running in the external control plane.

**Comment by lei-tang** [comment]
cc @shankgan for the CA related questions.

**Comment by ptembey-jnpr** [comment]
@shankgan appreciate your comments for this problem. Thanks!

I have another data point - I tried the above in GKE too, and the mutating webhook configuration has an empty caBundle again, so we are seeing the same error: "x509: certificate signed by unknown authority" during pod deployment.

Auto Sidecar injection does not work for namespaces in the remote cluster. However I was able to manually add sidecars to pods - which is not desirable.

**Comment by shankgan** [comment]
@lei-tang - could you redirect this to someone who has experience with the external istiod configurations? possibly @howardjohn or @linsun 

@ptembey-jnpr - not sure if the TLS passthrough approach will work. The XDS_ROOT_CA and CA_ROOT_CA environment variables are the path for the CA certificates used by the workloads on the "remote-cluster" to access the external-istiod via the ingress gateway. Could you check if the workload deployment manifests (in the remote-cluster) have mounted any  volumes (backed by configmaps/secrets) onto the location "/etc/ssl/certs" ? 

If not, just for testing, when you follow the steps to create self-signed certificates for the ingress gateway (https://istio.io/latest/docs/tasks/traffic-management/ingress/secure-ingress/ ) could you load the ca certificate from step 1 into a kubernetes configMap and mount that onto  and   _/etc/mounted_dir/ca.crt_ and configure this to be the XDS_ROOT_CA && CA_ROOT_CA?

**Comment by lei-tang** [comment]
Redirected to @linsun.

**Comment by ptembey-jnpr** [comment]
Thanks @shankgan for the pointers.

I was able to get my setup working - however I needed to add a few changes. 
1. I created a config map with our custom root certificate in the remote cluster 'external-istiod' namespace. 
2. In the Istio Ingress gateway configuration of remote cluster, I had to patch the deployment with a mount configuration to mount the config map using k8s overlays of Istio Operator
3. I then modified the MutatingWebhookConfiguration in remote-cluster to include the base64 encoding of the root certificate in its clientconfig 'caBundle'. -> This fixed the auto-injection of the envoy proxy as a sidecar.
4. I then modified the istio-sidecar-injector config map to include the mount configuration in the Envoy proxy sidecar template ( similar to patching the deployment of Istio ingress ). -> This solved the problem of the envoy sidecar trusting the remote certificate and coming up.

For points 3 and 4, could configuration override options be added to the Istio operator YAML config so we can customize the webhook configuration's caBundle ( we can only change the injectionURL today), and the istio-sidecar-injector's injection template to include additional external certs for the path: /etc/ssl/certs/<>.crt in CA_ROOT_CA and XDS_ROOT_CA ? This will help with configuring all things in remote cluster from one place in the Istio operator config instead of having to change the config maps after deployment.

**Comment by digitalsanctum** [comment]
Please re-open. As is stands today, there is still an issue and is not called out in the documentation: https://istio.io/latest/docs/setup/additional-setup/external-controlplane/

**Comment by litong01** [comment]
@digitalsanctum i've created a script to do this in kind environment, the issues you described exists with basically any cluster and I do not think it is AWS specific. Please look at the script here. https://github.com/litong01/multicluster-istio/blob/main/do-external-control-plane.sh. The key is that when you setup external control plane (not the one for ingress), you need to specify the webhook configuration name like what I have in the script:


```
        env:
        - name: INJECTION_WEBHOOK_CONFIG_NAME
          value: "istio-sidecar-injector-${ISTIO_NAMESPACE}"
        - name: VALIDATION_WEBHOOK_CONFIG_NAME
          value: "istio-validator-${ISTIO_NAMESPACE}"
        - name: EXTERNAL_ISTIOD
          value: "true"
        - name: CLUSTER_ID
          value: ${CLUSTER2_NAME}
        - name: SHARED_MESH_CONFIG
          value: istio
```

Have external_istiod , cluster_id, shared_mesh_config there for you to see where the injection webhook config should be set to. In my case, the ISTIO_NAMESPACE is `external_istiod`, but you can have your own namespace. With this setting, the external control plane will try to inject the caBundle into your webhooks in the config cluster, you can also inspect the webhook configuration, this way, when config cluster send request to external control plane, it will not cry about the unknown certs. I wished that the document be reworked on. Please reopen if you feel this has to be fixed on.

**Comment by digitalsanctum** [comment]
@litong01 Thanks for the script and detailed response. I see this as a workaround and seems to fill a gap of the documentation.

As a consumer of the documentation, I would expect to have a working example from the step by step process. I still think it makes sense to re-open this issue or create a new one.

**Comment by tanjunchen** [comment]
@digitalsanctum  do you resolve this, i have the same question.

**Comment by yishell** [comment]
> Thanks @shankgan for the pointers.
> 
> I was able to get my setup working - however I needed to add a few changes.
> 
> 1. I created a config map with our custom root certificate in the remote cluster 'external-istiod' namespace.
> 2. In the Istio Ingress gateway configuration of remote cluster, I had to patch the deployment with a mount configuration to mount the config map using k8s overlays of Istio Operator
> 3. I then modified the MutatingWebhookConfiguration in remote-cluster to include the base64 encoding of the root certificate in its clientconfig 'caBundle'. -> This fixed the auto-injection of the envoy proxy as a sidecar.
> 4. I then modified the istio-sidecar-injector config map to include the mount configuration in the Envoy proxy sidecar template ( similar to patching the deployment of Istio ingress ). -> This solved the problem of the envoy sidecar trusting the remote certificate and coming up.
> 
> For points 3 and 4, could configuration override options be added to the Istio operator YAML config for "istiodRemote" section so we can customize the webhook configuration's caBundle ( we can only change the injectionURL today), and the istio-sidecar-injector's injection template to include additional external certs in its mount config for the path: /etc/ssl/certs/<>.crt in CA_ROOT_CA and XDS_ROOT_CA ? This will help with configuring all things in remote cluster from one place in the Istio operator config instead of having to change the config maps after deployment.

Hi,can you share your  points 4
