### ISSUE TITLE
Add nodeSelector and tolerations to istiod chart

### ISSUE THREAD

**Issue by adamkgray** [istio/istio#30912]
**Describe the feature request**

Enable the use of nodeSelectors and tolerations on the istiod chart

**Describe alternatives you've considered**

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by morvencao** [comment]
Duplicated with https://github.com/istio/istio/issues/30538
If you're using istio operator to install istio, please set resources/affinity/annotation... with k8s settings, see: https://github.com/istio/istio/tree/master/operator#new-api-customization
We don't want to add helm parameters for each option in the values.yaml any more, it's hard to maintain so many options in the helm values.

**Comment by ostromart** [comment]
This change should be part of refactoring the helm charts to follow KubernetesResourceSpec. I agree we should not add new parameters in an ad hoc way though. Tentatively assigning to @jacob-delgado.
