### ISSUE TITLE
Request from pod to service on VM using a service entry is corrupted

### ISSUE THREAD

**Issue by mikosa** [istio/istio#30958]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
I am testing with a simple curl.
When I send a request from a pod to service running on vm using the local dns name of the vm, the message is received and is correct
When i send the request from the same pod to the same service, ip and port but using the service entry host name, the message is received on the VM, but is not well formed

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
The message should not be corrupted

**Steps to reproduce the bug**
I deployed GKE cluster and a VM and deployed istio on both as suggested step by step in documentation

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
Platform GCP
istio 1.9
GKE 1.18
VM centos 8

**How was Istio installed?**
followed exact steps
https://istio.io/latest/docs/setup/install/virtual-machine/

**Environment where the bug was observed (cloud vendor, OS, etc)**
GCP

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

Logs  when request is sent using google DNS name (use the name of the VM)
Response is normal
curl centos-1 -v

```
2021/02/17 19:47:08 [error] 7#7: *17 invalid URL prefix in "http://", client: 10.12.1.13, server: , request: "GET / HTTP/1.1", host: "centos-1:8080"
-  -    -  -  -  10.12.1.13 - - [17/Feb/2021:19:47:08 +0000] "GET / HTTP/1.1" 500 183 "-" "curl/7.38.0" "-"
````

Then deploy serviceentry

```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: serverless
  namespace: serverless
spec:
  hosts:
  - mytestdom.com
  location: MESH_INTERNAL
  ports:
  - number: 80
    name: http
    protocol: HTTP 
    targetPort: 8080
  resolution: STATIC
  workloadSelector:
    labels:
      app: serverless
```

then curl 

curl mytestdom.com -v

the request received in the vm is corrupted:
```
2021/02/17 19:36:43 [info] 7#7: *1 client sent invalid method while reading client request line, client: 10.12.1.13, server: , request: "   ����w0/��X�"
-  -  -  -  -  -  10.12.1.13 - - [17/Feb/2021:19:36:43 +0000] "\x16\x03\x01\x00\xB8\x01\x00\x00\xB4\x03\x03\xCA\xF5w0/\xE5\xDDX\xD1" 400 163 "-" "-" "-"
2021/02/17 19:36:43 [info] 7#7: *2 client sent invalid method while reading client request line, client: 10.12.1.13, server: , request: "   ���Eі}3,2��  ?Q@�H�L�%\�1� W¿��>9
                                                                                                                                                                              �+̩�/̨�,�0" outbound_.80_._.mytestdom.com�"
-  -  -  -  -  -  10.12.1.13 - - [17/Feb/2021:19:36:43 +0000] "\x16\x03\x01\x00\xB8\x01\x00\x00\xB4\x03\x03\x86E\xD1\x96}3,2\xAA\xEE\x18Q@\xACH\xF0L\xC3%\x5C\xC91\x11\x98\x09W\xC2\xBF\x9D\xB2>9\x00\x00\x0C\xC0+\xCC\xA9\xC0/\xCC\xA8\xC0,\xC00\x01\
x00\x00\x7F\x00\x00\x00\x22\x00 \x00\x00\x1Doutbound_.80_._.mytestdom.com\x00\x17\x00\x00\xFF\x01\x00\x01\x00\x00" 400 163 "-" "-" "-"
2021/02/17 19:36:43 [info] 7#7: *3 client sent invalid method while reading client request line, client: 10.12.1.13, server: , request: "   ���/_}N�=�?p��o��pH�    ?Ȫ%�?-(��
                                                                                                                                                                              �+̩�/̨�,�0" outbound_.80_._.mytestdom.com�"
-  -  -  -  -  -  10.12.1.13 - - [17/Feb/2021:19:36:43 +0000] "\x16\x03\x01\x00\xB8\x01\x00\x00\xB4\x03\x03\xFE/_}N\xE9\x04=\x95?p\xC3\xEBo\x98\xC2\x12p\xC2\x9CH\xEC\x18\xC8\xAA%\xAF?-(\xCF\xF0\x00\x00\x0C\xC0+\xCC\xA9\xC0/\xCC\xA8\xC0,\xC00\x01\
x00\x00\x7F\x00\x00\x00\x22\x00 \x00\x00\x1Doutbound_.80_._.mytestdom.com\x00\x17\x00\x00\xFF\x01\x00\x01\x00\x00" 400 163 "-" "-" "-"
```

**Comment by howardjohn** [comment]
The broken request is a tls handshake. do you have access logs from the client (and server, if you have it)?

My guess is the request to `centos-1` is just being passed through as is, so it works fine. For mytestdom.com, its matching this to the ServiceEntry, and upgrading to mTLS (https://istio.io/latest/docs/ops/configuration/traffic-management/tls-configuration/#auto-mtls). However, the server-side VM is not terminating the mTLS - possibly iptables on VM are wrong as well?

Can you also run `sudo iptables-save` on the VM?

**Comment by mikosa** [comment]
I see
I do have changes to the iptables there. They are modified by an application.
So probably that explains it. I was not able to force mTLS on the node either.
I will try to run nginx without the application on the vm

**Comment by mikosa** [comment]
I moved istio proxy installation before the other applications in the bootstrap script and now it seems to all work fine.

So it was probably due to some iptable configuration conflict on the vm
Thanks
