### ISSUE TITLE
can't use tcpdump in istio-proxy - eth0: You don't have permission to capture on that device

### ISSUE THREAD

**Issue by koolwithk** [istio/istio#30982]
**Bug description**

As per this article([Mutual TLS Migration](https://istio.io/latest/docs/tasks/security/authentication/mtls-migration/)) i should able to use **sudo tcpdump** command but it gives me below error

```
istio-proxy@app1-b6c8f6c99-x5g7f:/$ sudo tcpdump -i eth0
sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?

istio-proxy@app1-b6c8f6c99-x5g7f:/$ tcpdump -i eth0
tcpdump: eth0: You don't have permission to capture on that device
(socket: Operation not permitted)
```

I have also run tried running tcpdump with  root user as well but no luck.

```
[root@lp-knode-1 ~]# docker exec -it -u  root  e08aee934ee9 /bin/bash -c tcpdump -i eth0
tcpdump: eth0: You don't have permission to capture on that device
(socket: Operation not permitted)

[root@lp-knode-1 ~]# docker exec -it -u  root  e08aee934ee9 /bin/bash -c sudo tcpdump -i eth0
sudo: PERM_SUDOERS: setresuid(-1, 1, -1): Operation not permitted
sudo: no valid sudoers sources found, quitting
sudo: unable to initialize policy plugin
```

[x ] Networking
[x ] Security

[x ] Virtual Machine

**Expected behavior**

should see tcp traffic 

**Steps to reproduce the bug**

**Version** 
istio control, data plane, client,   version: 1.9.0
kubectl :  v1.20.1

**How was Istio installed?**
istioctl install --set profile=default -y

**Comment by rvennam** [comment]
Did you install Istio using `values.global.proxy.privileged=true`?

**Comment by rvennam** [comment]
`istioctl install --set values.global.proxy.privileged=true`

**Comment by howardjohn** [comment]
I think this is a docs issue only, we intentionally drop root

**Comment by alokmaurya1** [comment]
Thank you! I'm able to use `sudo tcpdump` after running istioctl install --set values.global.proxy.privileged=true
Might be docs issue because i also tried searching with same error i didn't find anything however i could have read the [Mutual TLS Migration](https://istio.io/latest/docs/tasks/security/authentication/mtls-migration/) docs carefully :)

**Comment by koolwithk** [comment]
Thank you! I'm able to use `sudo tcpdump` after running `istioctl install --set values.global.proxy.privileged=true`
Might be docs issue because I tried searching with same error message but I didn't find anything. however i could have read the [Mutual TLS Migration](https://istio.io/latest/docs/tasks/security/authentication/mtls-migration/) docs carefully :)

**Comment by MartinKosicky** [comment]
I updated the values.global.proxy.privileged but doesnt work for gateway
