### ISSUE TITLE
gRPC routing in VirtualService with non-root path

### ISSUE THREAD

**Issue by alen-z** [istio/istio#30989]
Hi Istio community,

just to confirm, gRPC can not be routed from arbitrary path to gRPC service? `/` route to gRPC service would work and `/demo/path/to/grpc` wouldn't?

Kind regards,
Alen

Sources:
https://stackoverflow.com/questions/40410392/grpc-endpoint-with-non-root-path
https://medium.com/namely-labs/a-crash-course-for-running-istio-1c6125930715
https://chromium.googlesource.com/external/github.com/grpc/grpc/+/HEAD/doc/PROTOCOL-HTTP2.md
https://github.com/GoogleCloudPlatform/istio-samples/blob/master/sample-apps/grpc-greeter-go/manifests/greeter-istio-virtualservice.yaml

Edit: Added sources.

**Comment by howardjohn** [comment]
See route based on URI: https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPMatchRequest

gRPC is just http(2), so you can do any routing with HTTP with gRPC.

Note that gRPC encodes the method in the path, so you will need to keep that in mind.

**Comment by alen-z** [comment]
Thank you for the fast response and your thoughts.

Is there any GitHub (or other) example about routing arbitrary path to gRPC service?

**Comment by howardjohn** [comment]
I am not sure what you expectation is routing arbitrary paths. gRPC has very specific paths that specify the service to call, so routing arbitrary ones doesn't sound right?

**Comment by alen-z** [comment]
Let's say I have `VirtualService` matching 2 paths — `/acceptance` and `/acceptance/list`. Can I route first to `/acceptance.services.AcceptanceService` and second to `/acceptance.services.ListService`?

**Comment by howardjohn** [comment]
You can, search for https://istio.io/latest/docs/reference/config/networking/virtual-service/ `rewrite`. However, you will probably break ever gRPC client

**Comment by howardjohn** [comment]
Closing as this is answered by ^
