### ISSUE TITLE
How can I add a HTTP filter to envoy proxy?

### ISSUE THREAD

**Issue by zhaohuabing** [istio/istio#3098]
Is it possible to add a customized HTTP filter to envoy proxy?
If it's possible, how could I achieve that?
It seems that listeners are fetched automatically from pilot.  I didn't find a place to plug a new HTTP filter in the listener.

**Comment by nmnellis** [comment]
There is some WIP to allow adding of Lua filters but it is not complete yet. [Envoy Lua Filters](https://www.envoyproxy.io/docs/envoy/latest/configuration/http_filters/lua_filter). Other custom filters in envoy have to be built into the binary and i don't think there is any work on the istio side to support running those yet.

**Comment by ijsnellf** [comment]
This is a question for our user group, not an issue:
https://groups.google.com/forum/#!forum/istio-users
