### ISSUE TITLE
Support podAntiAffinityLabelSelector in new helm charts for istiod

### ISSUE THREAD

**Issue by dseapy** [istio/istio#30980]
**Describe the feature request**

It used to be possible to specify antiaffinity for pods based on hostname in the old helm charts for pilot (https://discuss.istio.io/t/istio-pilot-and-policy-anti-affinity/843/7).  This no longer appears to be an option in the new charts as it doesn't appear to have the necessary templating in 1.9.0 in https://github.com/istio/istio/blob/master/manifests/charts/istio-control/istio-discovery/templates/deployment.yaml

**Affected product area (please put an X in all that apply)**

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by morvencao** [comment]
Duplicated with https://github.com/istio/istio/issues/30655
