### ISSUE TITLE
Improve top-level README.md

### ISSUE THREAD

**Issue by esnible** [istio/istio#31]
I found the Istio documentation, starting at https://github.com/istio/istio/blob/master/README.md , difficult to follow.

Istio is a “service mesh” that claims to provide “a uniform way to manage and connect microservices.”  The word “manage” is very general.  I know Istio can manage access checking, load balancing, and quota, but not for example instance lifecycle. 

The relationship between Istio and the underlying cluster management platform needs to be spelled out early so that someone new to the project can understand the separation of concerns between Istio and Kubernetes.  In the _istio/manager_ documentation it is revealed that the Istio Manager “provides an abstraction layer over the underlying cluster management platform, such as Kubernetes”.  We should be informed of that sooner.

The reference implementation of Istio runs on Kubernetes.  It would be nice if the top-level or Milestone Plan docs mention that MVP-1 and Alpha-1 are Kubernetes-only and gave a hint if the developers plan to implement support, or even hooks, for other cluster management platforms.  The manager contains a platform/kube package and the current manager/cmd/root.go is married to it.  There is no plug-in way I could implement _platform/mesos_ and get _istioctl_ to use it without providing a platform/* discovery mechanism.

Istio is a manager “handling system configuration, discovery, and automation.”  These three concepts are very general!  After looking at the manager I know it supports “route rules” for traffic between microservices.  A very specific sentence would really help with the understanding of what the manager provides.

Istio is a mixer “supporting access checks, quota allocation and deallocation, monitoring and logging.”  I need some help understanding this.  Does “access checks” mean network security?  Feature flags?  Rate limiting?  Does monitoring mean network traffic that is service-to-service and external-to-service and is it tied to any particular monitoring package such as Graphite/Grafana?  Does logging mean logs of authorization and quota violations to ElasticSearch?  Does Istio provide a logging framework that I should configure my micro services to log upon?  Some of this is in the architectural overview but if the opening docs are frustrating few readers will reach them.

The proxy handles “service-to-service and external-to-service traffic”.  What about service-to-external?  The architecture overview says it mediates “inbound and outbound traffic for all Istio-managed services.”  The implementation of Istio on Kubernetes is implementing by pairing each unmodified microservice instance with a network proxy co-located in the same pod.  For Istio developers the proxy is an important component but would users ever see it outside of a debugging context?

The top-level documentation next lists the repositories.  This is great, but again the vocabulary is very general and the reader has little idea what functions Istio provides and how the concerns are separated in this design.  There is little comfort in knowing that the manager configures and propagates.  I wanted a list of the types of configuration the manager is responsible for implementing, and how to interact with it.  Does it provide a REST API?  A CLI?  What kinds of operations are exposed?

**Comment by rshriram** [comment]
I believe this has been addressed in sufficient detail with the overview docs, diagrams, etc.

**Comment by geeknoid** [comment]
Can we close this?
