### ISSUE TITLE
Envoy MetricsService does not work in istio 1.9

### ISSUE THREAD

**Issue by EItanya** [istio/istio#31005]
**Bug description**

istio-proxy crashes when using envoy metrics service in istio 1.9. The API/Transport versions need to be bumped to `V3`

```
2021-02-23T01:01:17.918541Z     critical        envoy main      error initializing configuration 'etc/istio/proxy/envoy-rev0.json': V2 (and AUTO) xDS transport protocol versions are deprecated in grpc_service {
  envoy_grpc {
    cluster_name: "envoy_metrics_service"
  }
}
. The v2 xDS major version is deprecated and disabled by default. Support for v2 will be removed from Envoy at the start of Q1 2021. You may make use of v2 in Q4 2020 by following the advice in https://www.envoyproxy.io/docs/envoy/latest/faq/api/transition.
V2 (and AUTO) xDS transport protocol versions are deprecated in grpc_service {
  envoy_grpc {
    cluster_name: "envoy_metrics_service"
  }
}
. The v2 xDS major version is deprecated and disabled by default. Support for v2 will be removed from Envoy at the start of Q1 2021. You may make use of v2 in Q4 2020 by following the advice in https://www.envoyproxy.io/docs/envoy/latest/faq/api/transition.
2021-02-23T01:01:17.922404Z     error   Epoch 0 exited with error: exit status 1
2021-02-23T01:01:17.922425Z     info    No more active epochs, terminating
2021-02-23T01:01:17.922473Z     info    Status server has successfully terminated
```

I believe the offending config is coming from here: https://github.com/istio/istio/blob/47e9ea2c94ccb6c7137bf7e1df644f9e4b7f60f3/tools/packaging/common/envoy_bootstrap.json#L692

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ x ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
`istio-proxy` does not crash

**Steps to reproduce the bug**

1. install istio `v1.9.0`
2. Add `envoyMetricService` to MeshConfig in istio config map

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by linsun** [comment]
Are you also using 1.9's proxy?

@douglas-reid @mandarjog cc for input

**Comment by mandarjog** [comment]
This is fixed by https://github.com/istio/istio/pull/30941

**Comment by bianpengyuan** [comment]
actually #30941 fixes log service. https://github.com/istio/istio/pull/31006 is the fix for metric service.

**Comment by Zero-2** [comment]
There's a plan for a new release with this fixes?

**Comment by EItanya** [comment]
> Are you also using 1.9's proxy?
> 
> @douglas-reid @mandarjog cc for input

Yea, I am using the standard 1.9 installation. No upgrade happened, clean install

**Comment by bianpengyuan** [comment]
Fixed by https://github.com/istio/istio/pull/31051
