### ISSUE TITLE
Chart manifest version issues / conflicts.

### ISSUE THREAD

**Issue by anwoolterton** [istio/istio#31019]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

It seems that chart versions have not been updated when changes are made to the repos. The side effect of this is cicd processes can often fail or end user mistakes since the resulting .tgz will always be 1.7.0 which is confusing to the end user.

Ideally the chart version should be reflective of the version of istio being deployed. i.e 1.9.0 should be 1.9.0 if this includes changes to the charts.

https://github.com/istio/istio/blob/master/manifests/charts/istio-operator/Chart.yaml

[X] Installation
[X] Upgrade

**Expected behavior**

Generally charts should be incremented with changes.

**Steps to reproduce the bug**

**Version** 1.7 >

**How was Istio installed?**

Istio operator via helm

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by brian-avery** [comment]
@esnible Let us know if you need anything here.

**Comment by chris-sanders** [comment]
I'm new to Istio and just came here for this same reason. The chart versions are confusing and it's not clear to me if I install via charts how I'm to manage upgrades. Reinstalling the same chart version but getting different results based on the source branch it was built from is pretty concerning. I'm aware this is marked as alpha, is the intention to eventually increment charts (and maybe publish them as well?)
