### ISSUE TITLE
Merging of DestinationRules across namespaces does not work

### ISSUE THREAD

**Issue by atp-integration-mesh** [istio/istio#31025]
**Bug description**
Hello,

We have multiple namespaces that routes traffic out through istio-egressgateway in the istio-system namespace.
It works without any problems as long as VirtualServices and DestinationRules only applies to the given namespace.

But now we've introduced a common (external) service that all namespaces must be able to call. Configuration (ServiceEntry, VirtualService, DestiationRules and AuthorizationPolicy) of the service has been placed in the istio-system namespace so it isn't necessary to configure (duplicate) in all the other namespaces.

According to the documentation regarding DestinationRule merging:

> There should only be one definition of any given subset across multiple destination rules for the same host. If there is more than one with the same name, the first definition is used and any following duplicates are discarded. No merging of subset content is supported.

We've ensured unique naming of the subsets for the istio-egressgateway but it appears that only the subsets found in the client namespace is available to the mesh gateway. Not the subset defined in a DestinationRule in the istio-system.

This means that we get the following error when trying to route to the istio-egressgateway with the subset from the DestinationRule in istio-system:
```
2021-02-23T10:28:03.709630Z	debug	envoy filter	cannot find cluster outbound|443|metadefender-virusscan-through-egress|istio-egressgateway.istio-system.svc.cluster.local
2021-02-23T10:28:03.709657Z	debug	envoy router	[C480][S11315700290352149474] unknown cluster 'outbound|443|metadefender-virusscan-through-egress|istio-egressgateway.istio-system.svc.cluster.local'
```

To me the documentation is not completely clear on the matter of merging DestinationRules across namespaces (within the lookup path).

Is this a bug or simply not working (as designed)?

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
I would expect the DestinationRules for host: istio-egressgateway.istio-system.svc.cluster.local to be merged into one DestinationRule that contains all the subsets no matter where on the lookup path the DestinationRule is defined.

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
$ istioctl version --remote
client version: 1.8.1
control plane version: 1.8.1
data plane version: 1.8.1 

$ kubectl version --short
Client Version: v1.20.2-34+350770ed07a558
Server Version: v1.20.2-34+350770ed07a558
```

**How was Istio installed?**
istioctl install -f <customization file>

**Environment where the bug was observed (cloud vendor, OS, etc)**
Microk8s running on multiple on-premise Ubuntu servers/nodes.

Thanks for any help and/or insight.
Best regards, Jesper

**Comment by howardjohn** [comment]
The order is client > server > root namespace: https://istio.io/latest/docs/ops/best-practices/traffic-management/#cross-namespace-configuration

So it will use the client's DR

**Comment by atp-integration-mesh** [comment]
Thanks for your reply!

Yes and to my understanding that's the lookup path to find a relevant DR.
But when the DR in the client namespace doesn't contain the relevant subset, shouldn't it try to find it further down the lookup path?

So, either simply look for the subset further down the lookup path
OR
Merge the relevant DestinationRules in the lookup path.

Otherwise how do you define a routing to a common service through the istio-egressgateway?
Each namespace will (almost always) have routes through the egressgateway for specific requests for the given namespace.
It seems like overkill (and not the right approach) to copy the configuration of the common service to all namespaces.

Best regards
Jesper

**Comment by howardjohn** [comment]
It simply finds the first Destinationrule that matches, its not looking for the subsets through the full search path if we find a destinationrule before
