### ISSUE TITLE
Since 1.8.x istioctl validate is now providing less detail when it fails due to bad yaml

### ISSUE THREAD

**Issue by nickebbitt** [istio/istio#31023]
**Bug description**
We use `istioctl validate` to verify the manifests for Istio resources prior to deployment of a service.

When validation fails due to bad yaml the output provides us with context of the specific problem.

This additional context has gone in v1.8.3.

Unsure if this is specific to yaml validation or not but some other validation scenarios we check against are working as expected.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
istioctl v1.8.3 should still provide the useful detailed failure information when a validation fails due to yaml parsing.

**Steps to reproduce the bug**

Given the following manifest that contains bad yaml for the `maxConnections` property:
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: intentionally-valid-but-unparseable-destinationrule
spec:
  host: some.default.svc.cluster.local
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 4294967296
```

with v1.7.5:
```
$ istioctl validate -f bad-destination-rule.yaml                                                                                           12:14:56
Error: 1 error occurred:
	* DestinationRule//intentionally-valid-but-unparseable-destinationrule: cannot parse proto message: YAML decoding error: host: some.default.svc.cluster.local
trafficPolicy:
  connectionPool:
    tcp:
      maxConnections: 4294967296
 json: cannot unmarshal number 4294967296 into Go value of type int32
```

with v1.8.3:
```
istioctl validate -f bad-destination-rule.yaml                                                                                 ✘ KILL 4s 12:16:05
Error: 1 error occurred:
	* DestinationRule//intentionally-valid-but-unparseable-destinationrule: cannot parse proto message: json: cannot unmarshal number 4294967296 into Go value of type int32
```

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
$ istioctl version
client version: 1.8.3
control plane version: 1.8.3
data plane version: 1.8.3 (40 proxies)
```

**How was Istio installed?**
NA

**Environment where the bug was observed (cloud vendor, OS, etc)**
NA

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by Stono** [comment]
cc @howardjohn @douglas-reid :'(

**Comment by douglas-reid** [comment]
@therealmitchconnors @esnible for comment.

**Comment by nickebbitt** [comment]
We've upgraded to istioctl 1.9.0 and there's another minor regression/change in behaviour we have spotted.

Given the following invalid sidecar manifest:

```
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: intentionally-broken-sidecar
spec:
```

With 1.8.3:
```
istioctl-1.8.3 validate -f bad-sidecar-manifest.yaml                                                                                                                                                                                                      10:36:47
Error: 1 error occurred:
	* Sidecar//intentionally-broken-sidecar: sidecar: missing egress
```

and with 1.9.0:
```
istioctl-1.9.0 validate -f bad-sidecar-manifest.yaml                                                                                                                                                                                                  24s 10:36:36
Error: 1 error occurred:
	* Sidecar//intentionally-broken-sidecar: sidecar: empty configuration provided
```

**Comment by howardjohn** [comment]
need to dig into but I suspect one of the json/yaml libraries changed
