### ISSUE TITLE
Add integration tests to verify MetricsService and AccessLogsService

### ISSUE THREAD

**Issue by EItanya** [istio/istio#31026]
WRT the following [issue](https://github.com/istio/istio/issues/31005). AccessLogsService and MetricsService needs tests to ensure that regressions like this are caught.

**Comment by bianpengyuan** [comment]
Relevant access log issue: https://github.com/istio/istio/issues/30939

cc @hanahmily since you added the access log service initially, so you probably would be interested to take this.

**Comment by hanahmily** [comment]
@bianpengyuan I would like to take this, please assign this issue to me, thanks.

**Comment by ramaraochavali** [comment]
@hanahmily are you working on this or else @deveshkandpal24121990 is interested to pick this up. Can I assign this to him?

**Comment by hanahmily** [comment]
I'm not working on it, feel free to reassign.

**Comment by deveshkandpal24121990** [comment]
I'm interested in working, please assign this issue to me.

**Comment by bianpengyuan** [comment]
not stale.

**Comment by EItanya** [comment]
This may be especially relevant now. I have been testing out the new RC release, and adding the envoyMetricsService to the mesh config seems to stop the proxy from starting up properly. I am trying to get to the bottom of it now

**Comment by ramaraochavali** [comment]
Do you have any error in proxy log? Can you share if you have the log?

**Comment by EItanya** [comment]
The error is from `istiod`

**Comment by linsun** [comment]
@deveshkandpal24121990 are you still interested in working on this?

**Comment by eliavem** [comment]
@bianpengyuan, I'd like to look into this issue. Can you elaborate more on what integration tests should cover in this case?

**Comment by shivanshu1333** [comment]
Hi everyone, I see the issue isn't progressing, I'd love to come up with the required integration tests
@ramaraochavali could you please assign this to me?
Thanks!

**Comment by ramaraochavali** [comment]
@shivanshu1333  done

**Comment by linsun** [comment]
hey @shivanshu1333 thanks for signing up for this!  Any update?

**Comment by shivanshu1333** [comment]
Hello @linsun,
Yes I've just started working on it, no update as of now :|
I'll surely reach out to people, either here or on slack if I face any blocker, thanks for asking :)
Also, I don't see any priority-label/milestone-label attached to this issue, please let me know if this is something we need to prioritise.
Thanks!!

**Comment by ramaraochavali** [comment]
@shivanshu1333 Since this is not a feature those are not added - But this is important so ASAP is better :-)

**Comment by shivanshu1333** [comment]
Okay sure!!
