### ISSUE TITLE
Source of TCP traffic originating from in-mesh pods is reported as unknown in 1.9.0

### ISSUE THREAD

**Issue by Starefossen** [istio/istio#31034]
**Bug description**

Source of TCP traffic originating from in-mesh pods is reported as `unknown`. Moved from istio/istio#30898.

`istio_tcp_received_bytes_total` time series with unknown source in Prometheus https://gist.github.com/Starefossen/6bded64f4d650ee1d69c98c7b5de9ee0

![108840039-17f02f80-75d6-11eb-82ca-a11b43ac5909](https://user-images.githubusercontent.com/968267/108899017-3414c080-7618-11eb-943a-7a27519dea27.png)

The unknown traffic from the screenshot is in fact originating from the `gitea-0` pod. All of the pods in the namespace has the `istio-proxy` sidecar injected and mTLS is enabled.

@bianpengyuan thought it could be tcp exchange not happening. 

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

Reported traffic 

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```
$ istioctl version --remote
client version: 1.9.0
control plane version: 1.9.0
data plane version: 1.9.0 (18 proxies)
```

```
$ kubectl version --short
Client Version: v1.18.9
Server Version: v1.18.15
```

**How was Istio installed?**

BanzaiCloud Istio Operator v0.9.0

Istio config: https://gist.github.com/Starefossen/226d302918f76d467b3617a11304bd6c

**Environment where the bug was observed (cloud vendor, OS, etc)**

On-prem bare metal cluster with kubeadm. Ubuntu 18.04.

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

[bug-report.tar.gz](https://github.com/istio/istio/files/6031554/bug-report.tar.gz)

**Comment by bianpengyuan** [comment]
To help troubleshoot, could you please get several things:
1) get all envoyfilters in istio-system namespaces. Want to make sure tcp metadata exchange ones are there.
2) get a config dump of the db proxy, and the client proxy if you know which client is suppose to connect to the db.
3) get a stats dump of the db proxy.

You can find how to get config dump and stats dump here: https://github.com/istio/istio/wiki/Troubleshooting-Istio#sidecargateway-problems

**Comment by Starefossen** [comment]
envoyfilters in istio-system: https://gist.github.com/Starefossen/2930c68fbf8a512c600ed6e179a825a9
db proxy logs, stats, and config_dump: https://gist.github.com/Starefossen/0606f15cb4b64ef10e6d325ac1124754
client proxy logs, stats, and config_dump: https://gist.github.com/Starefossen/5a336264ddc5cf3260e8cfbaa5852ac6

**Comment by bianpengyuan** [comment]
Just realized we don't have TCP metadata exchange stats generated by default. If it is acceptable, could you turn on the filter trace log at db proxy? 
```
k exec <db-pod> -c istio-proxy -- curl -X POST localhost:15000/logging?filter=trace
```
and to turn it back to original warning level:
```
k exec <db-pod> -c istio-proxy -- curl -X POST localhost:15000/logging?filter=warning
```

If logging volume is a concern, could you add the following stats to your db deployment and client deployment, and then get the stats dump again? This will require restart your deployment.
```
spec:
...
  template:
  ...
    metadata:
      annotations:  
       ...   
        proxy.istio.io/config: |-
          proxyStatsMatcher:
            inclusionSuffixes:
              - "alpn_protocol_not_found"
              - "alpn_protocol_found"
              - "initial_header_not_found"
              - "header_not_found"
              - "metadata_added"
```

**Comment by Starefossen** [comment]
Enabled tracing and the inclusionSuffixes.

db proxy:

    config_dump: https://gist.github.com/Starefossen/f440f301091398af7af6a2e5bb1e1541/raw/9849a51f362e246242e2b315dbe102dac1799c25/db%2520proxy%2520config_dump
    stats: https://gist.github.com/Starefossen/f440f301091398af7af6a2e5bb1e1541/raw/9849a51f362e246242e2b315dbe102dac1799c25/db%2520proxy%2520stats
    logs: https://gist.github.com/Starefossen/f440f301091398af7af6a2e5bb1e1541/raw/9849a51f362e246242e2b315dbe102dac1799c25/db%2520proxy%2520logs

client proxy:

    config_dump: https://gist.github.com/Starefossen/94620950fd931ee6301036363854b57b/raw/709e04f7699730dffbfdfabb90da31361f7895b0/app%2520proxy%2520config_dump
    stats: https://gist.github.com/Starefossen/94620950fd931ee6301036363854b57b/raw/709e04f7699730dffbfdfabb90da31361f7895b0/app%2520proxy%2520stats
    logs: https://gist.github.com/Starefossen/94620950fd931ee6301036363854b57b/raw/709e04f7699730dffbfdfabb90da31361f7895b0/app%2520proxy%2520logs

**Comment by bianpengyuan** [comment]
Do you have some destination rule set for the db service? Looks like somehow h2 options are applied to db cluster config at the client side, and I think that was causing metadata exchange negotiation not happening.
<details>

```
{
     "version_info": "2021-02-26T07:53:11Z/144",
     "cluster": {
      "@type": "type.googleapis.com/envoy.config.cluster.v3.Cluster",
      "name": "outbound|5432||gitea-db.gitea.svc.cluster.local",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {},
        "resource_api_version": "V3"
       },
       "service_name": "outbound|5432||gitea-db.gitea.svc.cluster.local"
      },
      "connect_timeout": "10s",
      "circuit_breakers": {
       "thresholds": [
        {
         "max_connections": 4294967295,
         "max_pending_requests": 4294967295,
         "max_requests": 4294967295,
         "max_retries": 4294967295
        }
       ]
      },
      "http2_protocol_options": {
       "max_concurrent_streams": 1073741824
      },
      "metadata": {
       "filter_metadata": {
        "istio": {
         "services": [
          {
           "name": "gitea-db",
           "namespace": "gitea",
           "host": "gitea-db.gitea.svc.cluster.local"
          }
         ],
         "default_original_port": 5432
        }
       }
      },
      "protocol_selection": "USE_DOWNSTREAM_PROTOCOL",
      "filters": [
       {
        "name": "istio.metadata_exchange",
        "typed_config": {
         "@type": "type.googleapis.com/udpa.type.v1.TypedStruct",
         "type_url": "type.googleapis.com/envoy.tcp.metadataexchange.config.MetadataExchange",
         "value": {
          "protocol": "istio-peer-exchange"
         }
        }
       }
      ],
      "transport_socket_matches": [
       {
        "name": "tlsMode-istio",
        "match": {
         "tlsMode": "istio"
        },
        "transport_socket": {
         "name": "envoy.transport_sockets.tls",
         "typed_config": {
          "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext",
          "common_tls_context": {
           "alpn_protocols": [
            "istio-peer-exchange",
            "istio",
            "h2"
           ],
           "tls_certificate_sds_secret_configs": [
            {
             "name": "default",
             "sds_config": {
              "api_config_source": {
               "api_type": "GRPC",
               "grpc_services": [
                {
                 "envoy_grpc": {
                  "cluster_name": "sds-grpc"
                 }
                }
               ],
               "set_node_on_first_message_only": true,
               "transport_api_version": "V3"
              },
              "initial_fetch_timeout": "0s",
              "resource_api_version": "V3"
             }
            }
           ],
           "combined_validation_context": {
            "default_validation_context": {
             "match_subject_alt_names": [
              {
               "exact": "spiffe://cluster.local/ns/gitea/sa/postgres-pod"
              }
             ]
            },
            "validation_context_sds_secret_config": {
             "name": "ROOTCA",
             "sds_config": {
              "api_config_source": {
               "api_type": "GRPC",
               "grpc_services": [
                {
                 "envoy_grpc": {
                  "cluster_name": "sds-grpc"
                 }
                }
               ],
               "set_node_on_first_message_only": true,
               "transport_api_version": "V3"
              },
              "initial_fetch_timeout": "0s",
              "resource_api_version": "V3"
             }
            }
           }
          },
          "sni": "outbound_.5432_._.gitea-db.gitea.svc.cluster.local"
         }
        }
       },
       {
        "name": "tlsMode-disabled",
        "match": {},
        "transport_socket": {
         "name": "envoy.transport_sockets.raw_buffer"
        }
       }
      ]
     },
     "last_updated": "2021-02-26T07:53:21.498Z"
    }
```

</details>

**Comment by Starefossen** [comment]
No DestinationRule unfortunately. The client has a VirtualService and a Gateway. Except for that there are no other Istio configurations in that namespace.

**Comment by bianpengyuan** [comment]
Do you have destination rule at istio-system namespace?

**Comment by Starefossen** [comment]
No, I only have these destination rules in place to allow unencrypted connections to some services inside the mesh: https://gist.github.com/Starefossen/c76da56e20d1e074746b8b3ae077b04f

**Comment by Starefossen** [comment]
Apparently this is only affecting tcp traffic, http, http2 and grpc traffic is reported just fine.

![Screenshot 2021-03-02 at 11 43 30](https://user-images.githubusercontent.com/968267/109637001-84c27700-7b4c-11eb-98d9-2831cd4ca1a2.png)

**Comment by bianpengyuan** [comment]
Yeah TCP exchange works differently from http metadata exchange (which is based on headers). I will need to dig more on how h2 connection option / ALPNs could be set if there is no destination rule. Will post back.

**Comment by bianpengyuan** [comment]
Just realized that you've already provided the whole cluster dump in the initial bug report. Could you add tcp to the 5432 port of your db servcie and see if that solves the problem?
```
   - name: tcp-postgresql
      port: 5432
      protocol: TCP
      targetPort: 5432
```

**Comment by Starefossen** [comment]
Interesting, when I do this the the istio-proxy never starts up, it just says `Error from server (BadRequest): container "istio-proxy" in pod "gitea-0" is waiting to start: PodInitializing` and it never starts.

From the `istiod` I can see this log:

```
    "pilot_conflict_inbound_listener": {                                                                                                                      
        "wikijs-postgres-postgresql-0.wikijs": {                                                                                                              
            "proxy": "wikijs-postgres-postgresql-0.wikijs",                                                                                                   
            "message": "Conflicting inbound listener:5432. existing: wikijs-postgres-postgresql-headless.wikijs.svc.cluster.local, incoming: wikijs-postgres-p
ostgresql.wikijs.svc.cluster.local"                                                                                                                           
        }                                                                                                                                                     
    },                                                                                                                                                        
    "pilot_eds_no_instances": {                                                                                                                               
        "outbound_.22_._.gitea-ssh.gitea.svc.cluster.local": {},                                                                                              
        "outbound_.3000_._.gitea-http.gitea.svc.cluster.local": {},                                                                                           
        "outbound|22||gitea-ssh.gitea.svc.cluster.local": {},                                                                                                 
        "outbound|3000||gitea-http.gitea.svc.cluster.local": {}                                                                                               
    }                                                                                                                                                         
}                                                                                                                                                             
```

This is from a completely other namespace, but it too has a service with tcp port 5432 (PostgreSQL). Why would that be conflicting? Must tcp ports be unique accross all namespaces in a cluster?

**Comment by bianpengyuan** [comment]
Can you get another cluster dump?
