### ISSUE TITLE
Did istioctl support gateway-k8s-service-topologyKeys?

### ISSUE THREAD

**Issue by noahziheng** [istio/istio#31058]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

A error occured when I use `istioctl install`.Reason is ingressGateways-k8s-service have topologyKeys field.

```
Error: failed to get profile and enabled components: failed to read profile: unknown field "topologyKeys" in v1alpha1.ServiceSpec:

YAML:
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    ingressGateways:
    - enabled: true
      k8s:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - istio-ingressgateway
                topologyKey: kubernetes.io/hostname
              weight: 1
        hpaSpec:
          maxReplicas: 3
          minReplicas: 3
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 400Mi
        service:
          externalTrafficPolicy: Local
          topologyKeys:
          - kubernetes.io/hostname
          - '*'
        strategy:
          rollingUpdate:
            maxSurge: 0
            maxUnavailable: 1
        tolerations:
        - effect: PreferNoSchedule
          key: jumpnode
          operator: Equal
          value: "true"
      name: istio-ingressgateway
```

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
[Service Topology](https://kubernetes.io/docs/concepts/services-networking/service-topology/) effected on Istio Ingress Gateway's service resource.

**Steps to reproduce the bug**
istioctl install

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
istioctl version --remote:
client version: 1.8.2
control plane version: 1.8.2
data plane version: 1.8.2 (3 proxies)

kubectl version --short:
Client Version: v1.18.15+k3s1
Server Version: v1.18.15+k3s1

**How was Istio installed?**
istioctl install

**Environment where the bug was observed (cloud vendor, OS, etc)**
Private kubernetes cluster created by [k3s](https://rancher.com/products/k3s/).

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
No, and the feature is currently only alpha in Kubernetes (ie not recommended for production/enabled in most clusters) and is going to be removed in the very near future, so we will not implement it. See https://opensource.googleblog.com/2020/11/kubernetes-efficient-multi-zone.html

**Comment by noahziheng** [comment]
> No, and the feature is currently only alpha in Kubernetes (ie not recommended for production/enabled in most clusters) and is going to be removed in the very near future, so we will not implement it. See https://opensource.googleblog.com/2020/11/kubernetes-efficient-multi-zone.html

Thanks a lot! Very glad to get the good news and I‘ll close this issue.
