### ISSUE TITLE
ssh_exchange_identification : read: Connection reset by peer error after injecting sidecar.

### ISSUE THREAD

**Issue by vinemish** [istio/istio#31079]
**Bug description**

Trying to establish ssh between two pods but the sidecar proxy is denying some of the ssh connections with
`ssh_exchange_identification: read: Connection reset by peer` error.
 
I ran a simple test where I am running the date command on both the pods but if you see there are errors while establishing the connection and because of that my application crashes as ssh connection fails while connecting to other pods. May I know why is this happening and any workaround available? Please note this happens only when pods have a sidecar. 

```
[dashmpp-head-0 - Db2wh ~]$ for i in {1..100}; do ssh dashmpp-data1-0 date; done
Thu Feb 25 20:25:25 UTC 2021
Thu Feb 25 20:25:25 UTC 2021
Thu Feb 25 20:25:26 UTC 2021
Thu Feb 25 20:25:26 UTC 2021
Thu Feb 25 20:25:27 UTC 2021
Thu Feb 25 20:25:27 UTC 2021
Thu Feb 25 20:25:28 UTC 2021
Thu Feb 25 20:25:28 UTC 2021
Thu Feb 25 20:25:29 UTC 2021
Thu Feb 25 20:25:29 UTC 2021
Thu Feb 25 20:25:30 UTC 2021
Thu Feb 25 20:25:30 UTC 2021
Thu Feb 25 20:25:31 UTC 2021
Thu Feb 25 20:25:31 UTC 2021
Thu Feb 25 20:25:31 UTC 2021
Thu Feb 25 20:25:32 UTC 2021
Thu Feb 25 20:25:32 UTC 2021
Thu Feb 25 20:25:33 UTC 2021
Thu Feb 25 20:25:33 UTC 2021
Thu Feb 25 20:25:34 UTC 2021
Thu Feb 25 20:25:34 UTC 2021
Thu Feb 25 20:25:35 UTC 2021
Thu Feb 25 20:25:35 UTC 2021
Thu Feb 25 20:25:35 UTC 2021
Thu Feb 25 20:25:36 UTC 2021
Thu Feb 25 20:25:36 UTC 2021
Thu Feb 25 20:25:37 UTC 2021
Thu Feb 25 20:25:37 UTC 2021
Thu Feb 25 20:25:37 UTC 2021
Thu Feb 25 20:25:38 UTC 2021
Thu Feb 25 20:25:38 UTC 2021
Thu Feb 25 20:25:38 UTC 2021
Thu Feb 25 20:25:39 UTC 2021
Thu Feb 25 20:25:39 UTC 2021
Thu Feb 25 20:25:40 UTC 2021
Thu Feb 25 20:25:40 UTC 2021
Thu Feb 25 20:25:40 UTC 2021
Thu Feb 25 20:25:41 UTC 2021
Thu Feb 25 20:25:41 UTC 2021
ssh_exchange_identification: read: Connection reset by peer
Thu Feb 25 20:25:51 UTC 2021
Thu Feb 25 20:25:52 UTC 2021
Thu Feb 25 20:25:52 UTC 2021
Thu Feb 25 20:25:53 UTC 2021
Thu Feb 25 20:25:53 UTC 2021
Thu Feb 25 20:25:53 UTC 2021
Thu Feb 25 20:25:54 UTC 2021
Thu Feb 25 20:25:54 UTC 2021
Thu Feb 25 20:25:55 UTC 2021
Thu Feb 25 20:25:55 UTC 2021
Thu Feb 25 20:25:56 UTC 2021
Thu Feb 25 20:25:56 UTC 2021
Thu Feb 25 20:25:57 UTC 2021
Thu Feb 25 20:25:57 UTC 2021
Thu Feb 25 20:25:58 UTC 2021
Thu Feb 25 20:25:58 UTC 2021
Thu Feb 25 20:25:59 UTC 2021
Thu Feb 25 20:25:59 UTC 2021
Thu Feb 25 20:26:00 UTC 2021
Thu Feb 25 20:26:00 UTC 2021
Thu Feb 25 20:26:00 UTC 2021
Thu Feb 25 20:26:01 UTC 2021
Thu Feb 25 20:26:01 UTC 2021
Thu Feb 25 20:26:02 UTC 2021
Thu Feb 25 20:26:02 UTC 2021
Thu Feb 25 20:26:03 UTC 2021
Thu Feb 25 20:26:03 UTC 2021
Thu Feb 25 20:26:04 UTC 2021
Thu Feb 25 20:26:04 UTC 2021
Thu Feb 25 20:26:04 UTC 2021
ssh_exchange_identification: read: Connection reset by peer
Thu Feb 25 20:26:15 UTC 2021
Thu Feb 25 20:26:15 UTC 2021
Thu Feb 25 20:26:15 UTC 2021
Thu Feb 25 20:26:16 UTC 2021
Thu Feb 25 20:26:16 UTC 2021
Thu Feb 25 20:26:16 UTC 2021
Thu Feb 25 20:26:17 UTC 2021
Thu Feb 25 20:26:17 UTC 2021
Thu Feb 25 20:26:18 UTC 2021
Thu Feb 25 20:26:18 UTC 2021
Thu Feb 25 20:26:18 UTC 2021
Thu Feb 25 20:26:19 UTC 2021
Thu Feb 25 20:26:19 UTC 2021
Thu Feb 25 20:26:19 UTC 2021
Thu Feb 25 20:26:20 UTC 2021
Thu Feb 25 20:26:20 UTC 2021
Thu Feb 25 20:26:20 UTC 2021
Thu Feb 25 20:26:21 UTC 2021
Thu Feb 25 20:26:21 UTC 2021
Thu Feb 25 20:26:22 UTC 2021
Thu Feb 25 20:26:22 UTC 2021
Thu Feb 25 20:26:23 UTC 2021
Thu Feb 25 20:26:23 UTC 2021
Thu Feb 25 20:26:23 UTC 2021
Thu Feb 25 20:26:24 UTC 2021
Thu Feb 25 20:26:24 UTC 2021
Thu Feb 25 20:26:25 UTC 2021
Thu Feb 25 20:26:25 UTC 2021
Thu Feb 25 20:26:25 UTC 2021

```

[ ] Docs
[ ] Installation
[*] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

[*] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
it should not throw ssh_exchange_identification error.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
$ istioctl version                                                                                                                      [16:01:10]
client version: 1.9.0
control plane version: 1.9.0
data plane version: 1.9.0 (3 proxies)
```

**Comment by howardjohn** [comment]
So both sides have a sidecar, right?

Can you try connecting directly to the pod IP? And can you also show the yaml of the `dashmpp-data1-0` service?

if its intermittent its probably best to look at the debug logs (https://github.com/istio/istio/wiki/Troubleshooting-Istio) and see what error is thrown

**Comment by howardjohn** [comment]
Actually a full config dump may be useful as well

**Comment by vinemish** [comment]
[Logs.zip](https://github.com/istio/istio/files/6064403/Logs.zip)

**Comment by GregHanson** [comment]
@vinemish looking at the access logs, `10000` corresponds to a duration.  All the failures seem to occur at about 10s which is the default connect_timeout applied to traffic considered outside the service mesh (i.e. traffic routed through `PassthroughCluster`).  Is port `50022` defined for the destination dashmpp-data1-0 service?  To test, you could modify the mesh's global default [connectTimeout](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig) or you can write an [EnvoyFilter](https://istio.io/latest/docs/reference/config/networking/envoy-filter/) to modify the `PassthroughCluster`'s connectTimeout directly.

For understanding access logs, you can check out [Engarde](https://github.com/nitishm/engarde), Envoy's docs for [access logs ](https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage#command-operators), or try a tool [here](https://github.com/GregHanson/engarde-viewer) which combines both of them.

**Comment by GregHanson** [comment]
Talked offline, user used the `excludeOutboundPorts` annotation for the ssh port.  Closing until more info is requested

**Comment by cheekykesav** [comment]
> Talked offline, user used the `excludeOutboundPorts` annotation for the ssh port. Closing until more info is requested

This solution worked for me too. I added this to the source pod spec from where I want to do ssh to connect to other pod or vm which has ssh server running:
traffic.sidecar.istio.io/excludeOutboundPorts: "22"
