### ISSUE TITLE
Add Mesh Federation to Documentation: Setup > Install > Mesh Federation

### ISSUE THREAD

**Issue by joshuajorel** [istio/istio#31077]
**Describe the feature request**
Add documentation on setting up multi mesh deployments via mesh federation. Documentation on [deployment models](https://istio.io/latest/docs/ops/deployment/deployment-models/#multiple-meshes) specify this model but there is no documentation on how this is setup.

**Describe alternatives you've considered**
The only documentation I've seen is [this](https://github.com/istio-ecosystem/multi-mesh-examples/tree/master/add_hoc_limited_trust/tls) and this is a bit dated.

[X ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**
I have been experimenting with mesh federation and I can contribute to the documentation on how to get started when using this deployment model. There are a lot of options when it comes to setting this up so it would be of interest to discuss what is the best or recommended approach when setting this up.

**Comment by linsun** [comment]
Hi Josh!  The community would love to hear from you.  Do you have a setup that you recommends?  I would start with a google doc and sign up on the agenda of the environment WG to present your work.  The community can help you decide the best location to host your work, whether it is istio.io or in a repo in Istio-ecosystem.
