### ISSUE TITLE
Using overlays in istiooperator.yaml with revisions doesn't work

### ISSUE THREAD

**Issue by Stono** [istio/istio#31076]
Not sure if it's a bug, or a feature request :)

**Describe the feature request**

```
❯ ./src/1.9.0/bin/istioctl manifest generate -f istiooperator.yaml 
Error: overlay for Deployment:istiod does not match any object in output manifest. Available objects are:
ConfigMap:istio-system:istio-canary
Deployment:istio-system:istiod-canary
ConfigMap:istio-system:istio-sidecar-injector-canary
MutatingWebhookConfiguration::istio-sidecar-injector-canary
PodDisruptionBudget:istio-system:istiod-canary
Service:istio-system:istiod-canary
EnvoyFilter:istio-system:metadata-exchange-1.8-canary
EnvoyFilter:istio-system:tcp-metadata-exchange-1.8-canary
EnvoyFilter:istio-system:stats-filter-1.8-canary
EnvoyFilter:istio-system:tcp-stats-filter-1.8-canary
EnvoyFilter:istio-system:metadata-exchange-1.9-canary
EnvoyFilter:istio-system:tcp-metadata-exchange-1.9-canary
EnvoyFilter:istio-system:stats-filter-1.9-canary
EnvoyFilter:istio-system:tcp-stats-filter-1.9-canary
```

When setting a revision, and having:
```
spec:
  components:
    pilot:
      k8s:
        overlays:
        - kind: Deployment
          name: istiod
```

Etc.  

We'd have to copy all of our overlay configuration and change them to, for example `name: istiod-canary`.  

I appreciate there would be a requirement to have different overlays depending on the revision but it feels like we should have something like:

```
   name: istiod
```
= by default, targets all revisions

```
  name: istiod-canary
```
= only targets a specific revision

**Describe alternatives you've considered**

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by zioproto** [comment]
I confirm I am hitting this bug in Istio 1.14.1

This should be reopened ! thanks
