### ISSUE TITLE
circleci simple test build / problem with kube-inject / invalid image format, extra --tag in image name

### ISSUE THREAD

**Issue by ldemailly** [istio/istio#3108]
circleci simple test build / problem with kube-inject / invalid image format, extra --tag in image name

```
circleci@prealloc-kizc7hko-11a1604b-f1a2-44eb-9b1e-900349a51508:~$ kubectl get pods -n istio-system
NAME                                   READY     STATUS                  RESTARTS   AGE
echosrv-deployment-fb9999cf5-q8nsp     0/2       Init:InvalidImageName   0          8m
echosrv-deployment-fb9999cf5-qhqb7     0/2       Init:InvalidImageName   0          8m
istio-ca-77bf6db7cd-4pvtr              1/1       Running                 0          8m
istio-ingress-7d64dd8659-lpnw4         1/1       Running                 0          8m
istio-mixer-765d74bccf-cgx4z           3/3       Running                 0          8m
istio-pilot-768b8f6c8b-t2qf5           2/2       Running                 0          8m
prometheus-5f694cc57f-f5dbg            1/1       Running                 0          8m
raw-cli-deployement-6cb9958968-9hhd9   1/1       Running                 0          8m
zipkin-7988c559b7-4l6z4                1/1       Running                 0          8m
```

```
  Warning  InspectFailed          20s (x11 over 2m)  kubelet, prealloc-kizc7hko-11a1604b-f1a2-44eb-9b1e-900349a51508  Failed to apply default image tag "--tag/proxy_init:d2638e36923b0f5b1c25af51e3aa66ff9adceb31": couldn't parse image reference "--tag/proxy_init:d2638e36923b0f5b1c25af51e3aa66ff9adceb31": invalid reference format
```
because:
```
  istio-proxy:
    Container ID:  
    Image:         --tag/proxy:d2638e36923b0f5b1c25af51e3aa66ff9adceb31
```

see details in 
https://circleci.com/gh/istio/istio/24927

cc @costinm @mattdelco

**Comment by ldemailly** [comment]
it's running
```
2018-02-02T17:57:56.954121Z	info	Running command /go/out/linux_amd64/release/istioctl kube-inject -f /tmp/istio.e2e.169890571/servicesToBeInjected.yaml152473973.yaml -o /tmp/istio.e2e.169890571/KubeInject754891344.yaml --hub  --tag  -n istio-system -i istio-system --meshConfigMapName=istio
```
so looks like hub and tag are missing which probably explains the issue (--tag is used as the hub)

**Comment by mattdelco** [comment]
I was starting down the line of thinking that tools/istio-docker.mk could have better handling for an empty HUB but on 2nd thought the top-level Makefile does a $error if the HUB or TAG is empty so I suppose it's okay for now.

This might be related to a change @chxchx did for proxy tag/hub.

**Comment by mattdelco** [comment]
tests/e2e_istio_preinstalled.sh and tests/istio.mk now needs to specify --proxy_hub and --proxy_tag (or alternatively export HUB and TAG rather than pass a bunch of parameters)?

**Comment by costinm** [comment]
Can we just use defaults ? At least for hub - docker.io/istio ( and on prow it can be set to grc explicitly ).

For tag - when testing in minikube or ci there is no particular value to set the tag, images are not uploaded, so a default value '$USER' would work very well.

**Comment by chxchx** [comment]
I was not sure if my PR introduced this issue since it passes all Circle CI checks, so did commits on master that built on top of me. The --proxy_hub and --proxy_tag do use HUB and TAG as default value tho

**Comment by ldemailly** [comment]
the default wouldn't work in this case would it ? (as it needs to use the image circle just built)

**Comment by ldemailly** [comment]
doesn't seem to be happening anymore. closing
