### ISSUE TITLE
app to app calls are not working in TPROXY mode

### ISSUE THREAD

**Issue by ramaraochavali** [istio/istio#31095]
**Bug description**
app calling to itself is not working in TPROXY mode. They work fine in REDIRECT mode. We skip proxy in that mode correctly but some how it is not working in TPROXY mode

[ ] Docs
[ ] Installation
[ X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Comment by ramaraochavali** [comment]
@hzxuzhonghu reviewed the iptables and suggested the following rule should help

```
iptables -t mangle -I PREROUTING 1 -o lo -p tcp -j RETURN
```
We are yet to try this. I will update what I find. @rlenglet @lambdai any thoughts?

**Comment by rlenglet** [comment]
Which version is this?

**Comment by ramaraochavali** [comment]
Master

**Comment by hzxuzhonghu** [comment]
This is my finding, app call itself by podip: the traffic will go through prerouting chain whenever in tproxy or redirect mode.





The diff is:

in redirect mode, the redirect to 15006 rule in NAT table, but the local traffic skips it

in tproxy mode, the intercept to 15006 happens at mangle table, which is possible.

**Comment by hzxuzhonghu** [comment]
I can easily simulate calling itself by podip, and we can see only inbound access log. And i have also enabled iptables log, which also verified this.

**Comment by ramaraochavali** [comment]
@hzxuzhonghu Thank you so much for verifying it. Tried to fix https://github.com/istio/istio/pull/31100 here. PTAL
