### ISSUE TITLE
istioctl install --set profile=demo y Keep waiting for Deployment/istio-system/istiod 

### ISSUE THREAD

**Issue by Xunzhuo** [istio/istio#31106]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
When Install istio, I run command : istioctl install --set profile=demo y
After installed istio core, istiod install keeps waiting
```
# root @ VM-96-189-centos in ~ [18:59:58] 
$ istioctl install --set profile=demo -y
✔ Istio core installed                                                                                                                                             
- Processing resources for Istiod. Waiting for Deployment/istio-system/istiod 
```

[ ] Docs
[ X ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
We need more information, look at `kubectl describe` and `kubectl logs` of istiod deployment. Or attach http://istio.io/help/bugs/#generating-a-cluster-state-archive

**Comment by Xunzhuo** [comment]
> We need more information, look at `kubectl describe` and `kubectl logs` of istiod deployment. Or attach http://istio.io/help/bugs/#generating-a-cluster-state-archive

Thanks, Problems solved. Maybe network error
