### ISSUE TITLE
Support pods dns resolve

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#31104]
We have supported statefulset pods dns resolve, for others with `subdomain ` set but not belong to statefulset, should we also support?

https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-hostname-and-subdomain-fields

**Comment by ramaraochavali** [comment]
Makes sense to me

**Comment by howardjohn** [comment]
So what is the logic, and pod with `subdomain` matching the name of a headless Service that selects it gets a DNS record for `hostname.subdomain.namespace.svc.cluster.local`? And statefulset is not "special", it just meets that criteria?

**Comment by hzxuzhonghu** [comment]
Exactly that's what i think, and we need to  store pod hostname and subdomain to istioEndpoint
