### ISSUE TITLE
Add proto validator into istio/api and istio/istio

### ISSUE THREAD

**Issue by xiaolanz** [istio/istio#3110]
Using https://github.com/lyft/protoc-gen-validate

In progress testing their validator, opened issue: https://github.com/lyft/protoc-gen-validate/issues/56

**Comment by kyessenov** [comment]
Would be wonderful if you can help out with https://github.com/lyft/protoc-gen-validate/issues/52

**Comment by ozevren** [comment]
This is obsolete, now that we're considering Cue.
