### ISSUE TITLE
Support Multiple Trust Anchors in a TrustBundle

### ISSUE THREAD

**Issue by shankgan** [istio/istio#31111]
Currently, Istio supports only one cryptographic root (TrustAnchor) for mTLS communication between workloads in the Mesh. There exists no mechanism to distribute a Trustbundle with more than one cryptographic root to all workloads within the mesh (On a per proxy basis, this could be done with file-based certs). In fact, the TrustAnchor is inferred from the signed workload certificate rather than being explicitly set. 

Terminology :- 
  TrustAnchor (a cryptographic root of Trust)
  TrustBundle (a set of TrustAnchors), possibly anchored to a TrustDomain
  TrustDomain - a domain where all workloads are able to authenticate each other based on common roots of trust. IMO, this maps to a single mesh in Istio

Without support for multiple Trust Anchors, we have some following restrictions - 

(a) Migration of workloads from one CA to another CA _(assuming both of them do not share the same root of trust)_ is not possible without downtime in service - For there to be no downtime, workloads need to communicate with other workloads whose cert is signed by a different CA when migration is in progress. 

(b) Every cluster in an Istio mesh needs to have the same root - While each cluster may use a different intermediate CA to sign workload certificates, all intermediate CA certs need to be signed by the same root for mTLS to work.

(c) Mesh Federation is not straightforward - Given each mesh usually maps to a different Istio trustDomain, it is expected that each trustDomain has its own set of CA's to issue workload certificates. If communication between meshes is expected, then there needs to be a mechanism to distribute the trustbundle(containing one or more TrustAnchors) corresponding to each TrustDomain to each other. This does not exist today. Refer https://github.com/istio/istio/issues/30454

Adding the ability to explicitly configure Multiple TrustAnchors in the current TrustDomain solves issues (a) and (b) and lays the foundations for solving issue (c). 
The RFC is available [here](https://docs.google.com/document/d/1EFMQZNlyImLP0k0HIyoBINntchqeUq7QQgc9O_jDwZ8/edit#heading=h.io2z16q0yjxj).

**Describe alternatives you've considered**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[X] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by apolovov** [comment]
There is a problem in [PR](https://github.com/istio/istio/pull/31096). If the trust bundle endpoint isn't accessible during istiod startup, it won't retry to fetch URL till the next tick in a half-hour.
IMHO istiod should continue to retry fetching endpoint with some short timeout. After success, you can increase the timeout.
