### ISSUE TITLE
status: panic in reporter removeCompletedResource

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#31122]
https://storage.googleapis.com/istio-prow/logs/integ-pilot-multicluster-tests_istio_postsubmit/1365389838714408960/artifacts/pilot-analysis-025676f276524e61/_suite_context/istio-state-863704389/primary/istiod-fd4758874-l6s6z_discovery.log

**Comment by howardjohn** [comment]
https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/31256/integ-pilot-multicluster-tests_istio/1368885076657442816/artifacts/pilot-analysis-b7930c0afd96444c/_suite_context/istio-state-332981743/cross-network-primary/istiod-9878dfb78-b9qqv_discovery.previous.log

**Comment by howardjohn** [comment]
https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/31467/integ-pilot-k8s-tests_istio/1371492283119046656/artifacts/pilot-analysis-2f9ed6b8171244a3/_suite_context/istio-state-996081096/cluster-0/istiod-f8bf844b7-b5xmb_discovery.log

**Comment by therealmitchconnors** [comment]
This appears to be related to status, rather than analysis, so I'm changing the title.  The test suites are poorly named.  I will take a look when I get a chance.
