### ISSUE TITLE
`Istio Proxy` unconditionally binds to `0.0.0.0:15090` and `0.0.0.0:15021` which leads to a conflict with outbound listeners when IPtables redirection is disabled

### ISSUE THREAD

**Issue by yskopets** [istio/istio#31138]
**Bug description**

* At the moment, [envoy_bootstrap.json](https://github.com/istio/istio/blob/master/tools/packaging/common/envoy_bootstrap.json) unconditionally binds to `0.0.0.0:15090` and `0.0.0.0:15021`
* When `Istio Proxy` is used without IPtables redirection, e.g. on VMs, it creates a conflict with `outbound` listeners who are also trying to bind to `127.0.0.1:15090` and `127.0.0.1:15021`

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

* When IPtables redirection is disabled, `pilot-agent` and `Envoy` should avoid binding to `0.0.0.0` unless a user specifically asks for that

**Other remarks**

* I could help implementing the changes
* Does Istio want to support the use case with IPtables redirection disabled ?

**Comment by howardjohn** [comment]
Istio is largely working under the assumption that is "owns" the 150xx port range. I don't think disabling this if redirection is disabled makes sense (it has nothing to do with redirection), but maybe it could be customization I suppose
