### ISSUE TITLE
"DC" envoy codes since 1.8.3 upgrade

### ISSUE THREAD

**Issue by Stono** [istio/istio#31136]
**Bug description**
Hi, 
Not sure where to go with this so figured I'd share the observation in case anyone had any ideas.  

We recently upgraded from 1.7 to 1.8.3.  On 1.7 we'd periodically see 0DC's (expected, as the client, some of which have a low tolerance to slow reponses, killed the request before a response was returned, thus the DC and 0 response code due to the request not completing).

**Note**: We also see this on our testing 1.9 cluster

On 1.8, we're seeing DCs **with** status codes, as well as without:

![Screenshot 2021-02-28 at 09 53 06](https://user-images.githubusercontent.com/1486729/109414438-d7fcc400-79aa-11eb-8512-6f48ed3bc7f0.png)

You can see how pronounced it is here:
![Screenshot 2021-02-28 at 10 25 36](https://user-images.githubusercontent.com/1486729/109415223-5b201900-79af-11eb-8f18-8fcf57e5e65c.png)

And you can see it's across most response codes:
![Screenshot 2021-02-28 at 10 46 48](https://user-images.githubusercontent.com/1486729/109415731-4e50f480-79b2-11eb-90d3-49ec923ef803.png)

There is no correlation against source or destination workload, it's cluster wide.

Note that these metrics are `reporter=source`, so from the source service.

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by Stono** [comment]
By some miracle I did manage to catch one

![Screenshot 2021-02-28 at 10 38 11](https://user-images.githubusercontent.com/1486729/109415519-185f4080-79b1-11eb-899d-5bcdc7d5974e.png)

```
2021-02-28T10:36:20.533517Z debug envoy pool  [C3984378] using existing connection
2021-02-28T10:36:20.533522Z debug envoy pool  [C3984378] creating stream
2021-02-28T10:36:20.533534Z debug envoy router  [C3897434][S14880343837474254794] pool ready
2021-02-28T10:36:20.575085Z debug envoy filter  original_dst: New connection accepted
2021-02-28T10:36:20.575173Z debug envoy conn_handler  [C3985182] new connection
2021-02-28T10:36:20.575238Z debug envoy http  [C3985182] new stream
2021-02-28T10:36:20.575312Z debug envoy http  [C3985182][S9369404714274295047] request headers complete (end_stream=true):
':authority', 'app.search-one-read'
':path', '/api/v1/advert/201607135816874'
':method', 'GET'
'accept', 'application/json'
'x-request-id', '628981035bc3c795-AMS'
'x-b3-parentspanid', '7fdb0b055f759768'
'x-b3-traceid', '05875718085acea7'
'x-b3-spanid', '15f5e3c12011df59'
'x-b3-sampled', '1'
'client', 'dealer-websites'
'x-b3-flags', '0'
'x-facet-links', 'false'
'x-include-vehicle-check', 'true'
'x-include-price-indicator-rating', 'true'
'x-client-identifier', 'dealer-websites'
'connection', 'Keep-Alive'
'user-agent', 'Apache-HttpClient/4.5.5 (Java/1.8.0_275)'
'accept-encoding', 'gzip,deflate'

2021-02-28T10:36:20.575335Z debug envoy http  [C3985182][S9369404714274295047] request end stream
2021-02-28T10:36:20.575433Z debug envoy filter  override with 3 ALPNs
2021-02-28T10:36:20.575460Z debug envoy router  [C3985182][S9369404714274295047] cluster 'outbound|80||app.search-one-read.svc.cluster.local' match for URL '/api/v1/advert/201607135816874'
2021-02-28T10:36:20.575506Z debug envoy router  [C3985182][S9369404714274295047] router decoding headers:
':authority', 'app.search-one-read'
':path', '/api/v1/advert/201607135816874'
':method', 'GET'
':scheme', 'https'
'accept', 'application/json'
'x-request-id', '628981035bc3c795-AMS'
'client', 'dealer-websites'
'x-b3-flags', '0'
'x-facet-links', 'false'
'x-include-vehicle-check', 'true'
'x-include-price-indicator-rating', 'true'
'x-client-identifier', 'dealer-websites'
'user-agent', 'Apache-HttpClient/4.5.5 (Java/1.8.0_275)'
'accept-encoding', 'gzip,deflate'
'x-forwarded-proto', 'http'
'x-envoy-decorator-operation', 'app.search-one-read.svc.cluster.local:80/*'
'x-envoy-peer-metadata', '...'
'x-envoy-peer-metadata-id', 'sidecar~10.194.52.186~dealer-websites-server-757cf77bc5-682nk.dealer-websites-server~dealer-websites-server.svc.cluster.local'
'x-envoy-expected-rq-timeout-ms', '25000'
'x-envoy-attempt-count', '1'
'x-b3-traceid', '05875718085acea7'
'x-b3-spanid', '3c43cc204ee16ece'
'x-b3-parentspanid', '15f5e3c12011df59'
'x-b3-sampled', '1'
2021-02-28T10:36:20.575520Z debug envoy pool  [C3981158] using existing connection
2021-02-28T10:36:20.575525Z debug envoy pool  [C3981158] creating stream
2021-02-28T10:36:20.575531Z debug envoy router  [C3985182][S9369404714274295047] pool ready
2021-02-28T10:36:20.580330Z debug envoy router  [C3985182][S9369404714274295047] upstream headers complete: end_stream=false
2021-02-28T10:36:20.580426Z debug envoy http  [C3985182][S9369404714274295047] encoding headers via codec (end_stream=false):
':status', '404'
'originating-request-identifier', '8E0E6EC774914B7BACFEC1A41AB2FC8C'
'request-identifier', '8E0E6EC774914B7BACFEC1A41AB2FC8C'
'server', 'envoy'
'vary', 'accept-encoding'
'content-encoding', 'gzip'
'content-type', 'application/json'
'date', 'Sun, 28 Feb 2021 10:36:19 GMT'
'x-envoy-upstream-service-time', '4'

2021-02-28T10:36:20.580610Z debug envoy connection  [C3985182] remote early close
2021-02-28T10:36:20.580623Z debug envoy connection  [C3985182] closing socket: 0
2021-02-28T10:36:20.580681Z debug envoy http  [C3985182][S9369404714274295047] stream reset
2021-02-28T10:36:20.580787Z debug envoy wasm  wasm log: [extensions/stats/plugin.cc:615]::report() metricKey cache hit , stat=36
2021-02-28T10:36:20.580800Z debug envoy wasm  wasm log: [extensions/stats/plugin.cc:615]::report() metricKey cache hit , stat=6
2021-02-28T10:36:20.580802Z debug envoy wasm  wasm log: [extensions/stats/plugin.cc:615]::report() metricKey cache hit , stat=10
2021-02-28T10:36:20.580805Z debug envoy wasm  wasm log: [extensions/stats/plugin.cc:615]::report() metricKey cache hit , stat=14
2021-02-28T10:36:20.580812Z debug envoy router  [C3985182][S9369404714274295047] resetting pool request
2021-02-28T10:36:20.580817Z debug envoy client  [C3981158] request reset
2021-02-28T10:36:20.580823Z debug envoy connection  [C3981158] closing data_to_write=0 type=1
2021-02-28T10:36:20.580825Z debug envoy connection  [C3981158] closing socket: 1
2021-02-28T10:36:20.580850Z debug envoy connection  [C3981158] SSL shutdown: rc=0
2021-02-28T10:36:20.580853Z debug envoy connection  [C3981158]
2021-02-28T10:36:20.580873Z debug envoy client  [C3981158] disconnect. resetting 0 pending requests
2021-02-28T10:36:20.580881Z debug envoy pool  [C3981158] client disconnected, failure reason:
2021-02-28T10:36:20.580897Z debug envoy conn_handler  [C3985182] adding to cleanup list
2021-02-28T10:36:20.580902Z debug envoy pool  [C3981158] destroying stream: 0 remaining
2021-02-28T10:36:20.583551Z debug envoy client  [C3983536] response complete
```

Guessing the problem line is: `2021-02-28T10:36:20.580881Z debug envoy pool  [C3981158] client disconnected, failure reason:`

The client (dealer-websites-server) in this instance, got the 404 back, and handled it accordingly, so there's some change in envoy behaviour here 1.7 -> 1.8

**Comment by Stono** [comment]
OK so my gut here was that the impact is connection churn.  As I mentioned before the source service is getting the response but then we get the client disconnect.

I decided to turn on `http2upgrades` just to see what differences that makes, if any.  I took two candidate services which have more traffic than others:

As expected the connection rate (bottom graph) dropped right off as the persistent h2 connections were used), but interestingly the 0DCs reduced (didn't stop, but reduced).

![Screenshot 2021-02-28 at 11 26 45](https://user-images.githubusercontent.com/1486729/109416727-ee5d4c80-79b7-11eb-86a6-b31d89336ab1.png)

I've no idea what this is actually telling me, it's just more data.

**Comment by Stono** [comment]
This graph is also interesting, we had been experiencing more p95 latency recently and had been struggling to get to the bottom of it.  As I enabled http2 on the above service yesterday, that seems to have almost entirely solved the issues we were seeing in latency.

Last 48 hours:
![Screenshot 2021-03-01 at 07 07 59](https://user-images.githubusercontent.com/1486729/109463427-e73c4a00-7a5c-11eb-837c-92183c79d0bc.png)

**Comment by Stono** [comment]
OK I believe this to be a 1.8+ regression, I've tested a workload with a 1.7 sidecar this morning and get barely any DCs in comparison.

I have proxy logs from both a 1.7 and 1.9 sidecar that I can share privately if required, the 1.9 shows:

The pattern appears to be every 10 seconds, feels like an aggressive socket timeout perhaps?
```
❯ cat 1 | grep -i disconn
{"level":"debug","time":"2021-03-01T07:15:49.635786Z","scope":"client","msg":"[C196035] disconnect. resetting 0 pending requests"}
{"level":"debug","time":"2021-03-01T07:15:49.635806Z","scope":"pool","msg":"[C196035] client disconnected, failure reason: "}
{"level":"debug","time":"2021-03-01T07:15:59.636194Z","scope":"client","msg":"[C196048] disconnect. resetting 0 pending requests"}
{"level":"debug","time":"2021-03-01T07:15:59.636203Z","scope":"pool","msg":"[C196048] client disconnected, failure reason: "}
{"level":"debug","time":"2021-03-01T07:16:19.621107Z","scope":"client","msg":"[C196054] disconnect. resetting 0 pending requests"}
{"level":"debug","time":"2021-03-01T07:16:19.621118Z","scope":"pool","msg":"[C196054] client disconnected, failure reason: "}
{"level":"debug","time":"2021-03-01T07:16:29.634028Z","scope":"client","msg":"[C196042] disconnect. resetting 0 pending requests"}
{"level":"debug","time":"2021-03-01T07:16:29.634040Z","scope":"pool","msg":"[C196042] client disconnected, failure reason: "}
{"level":"debug","time":"2021-03-01T07:16:39.630850Z","scope":"client","msg":"[C196029] disconnect. resetting 0 pending requests"}
{"level":"debug","time":"2021-03-01T07:16:39.630860Z","scope":"pool","msg":"[C196029] client disconnected, failure reason: "}
{"level":"debug","time":"2021-03-01T07:16:49.632537Z","scope":"client","msg":"[C196077] disconnect. resetting 0 pending requests"}
{"level":"debug","time":"2021-03-01T07:16:49.632541Z","scope":"pool","msg":"[C196077] client disconnected, failure reason: "}
{"level":"debug","time":"2021-03-01T07:16:59.642396Z","scope":"client","msg":"[C196083] disconnect. resetting 0 pending requests"}
{"level":"debug","time":"2021-03-01T07:16:59.642403Z","scope":"pool","msg":"[C196083] client disconnected, failure reason: "}
{"level":"debug","time":"2021-03-01T07:17:09.628760Z","scope":"client","msg":"[C196065] disconnect. resetting 0 pending requests"}
{"level":"debug","time":"2021-03-01T07:17:09.628773Z","scope":"pool","msg":"[C196065] client disconnected, failure reason: "}
{"level":"debug","time":"2021-03-01T07:17:19.640277Z","scope":"client","msg":"[C196095] disconnect. resetting 0 pending requests"}
{"level":"debug","time":"2021-03-01T07:17:19.640282Z","scope":"pool","msg":"[C196095] client disconnected, failure reason: "}
{"level":"debug","time":"2021-03-01T07:17:29.626087Z","scope":"client","msg":"[C196101] disconnect. resetting 0 pending requests"}
{"level":"debug","time":"2021-03-01T07:17:29.626099Z","scope":"pool","msg":"[C196101] client disconnected, failure reason: "}
{"level":"debug","time":"2021-03-01T07:17:59.673122Z","scope":"client","msg":"[C196113] disconnect. resetting 0 pending requests"}
{"level":"debug","time":"2021-03-01T07:17:59.673133Z","scope":"pool","msg":"[C196113] client disconnected, failure reason: "}
{"level":"debug","time":"2021-03-01T07:18:09.625307Z","scope":"client","msg":"[C196107] disconnect. resetting 0 pending requests"}
{"level":"debug","time":"2021-03-01T07:18:09.625316Z","scope":"pool","msg":"[C196107] client disconnected, failure reason: "}
```

The 1.7 shows some, but hardly any in comparison:
```
❯ cat 2 | grep -i discon
2021-03-01T07:20:04.035052Z     debug   envoy client    [C21] disconnect. resetting 0 pending requests
2021-03-01T07:20:04.035057Z     debug   envoy pool      [C21] client disconnected, failure reason:
2021-03-01T07:21:54.036225Z     debug   envoy client    [C37] disconnect. resetting 0 pending requests
2021-03-01T07:21:54.036237Z     debug   envoy pool      [C37] client disconnected, failure reason:
```

cc @howardjohn

**Comment by Stono** [comment]
FWIW something else I've noticed is that you get `client disconnected, failure reason:` at the source service when you update the `DestinationRule` of the remote service.

**Comment by Stono** [comment]
So I've been trying to debug what's going on in Wireshark here, and I'm a bit confused, so would be good if someone with more envoy connection knowledge could wade in.

You can see here what we appear to see is:

- Application -> local sidecar: FIN
- local sidecar -> remote sidecar: RST 

<img width="1459" alt="both" src="https://user-images.githubusercontent.com/1486729/109471056-1e642880-7a68-11eb-979c-d37203a02af9.png">

If we follow the Application -> local sidecar stream, it exists for a mere 600ms:
<img width="1417" alt="app-to-istio" src="https://user-images.githubusercontent.com/1486729/109471252-6c792c00-7a68-11eb-94a6-daa2da4897d8.png">

But if we follow the local sidecar-> remote sidecar, the stream is **exactly** 1 minute long:
<img width="1067" alt="istio-to-remote" src="https://user-images.githubusercontent.com/1486729/109471293-7dc23880-7a68-11eb-9a27-7e5982224d2e.png">

My questions here are:

- Why would istio `RST` the stream between the two sidecars, if the local application sends `FIN`, connections are supposed to be reused between sidecars. 
- Why is the duration of the istio to istio stream exactly 1 minute?

**Comment by Stono** [comment]
We can certainly see the RST's in wireshark, I'm not the best at deciphering pcaps so if anyone wants to look please ping me on slack.

![Screenshot 2021-03-01 at 08 46 31](https://user-images.githubusercontent.com/1486729/109473245-f7f3bc80-7a6a-11eb-818a-94afd4b5b788.png)

**Comment by ramaraochavali** [comment]
@lambdai FYI. Any idea if some thing is changed in Envoy with 1.8?

**Comment by Stono** [comment]
OK so I'm almost certain here that what i'm seeing is clients that are not using connection pooling, eg using a single http client per request.   Every app that i've checked so far is not reusing connections across requests.

![Screenshot 2021-03-01 at 13 24 45](https://user-images.githubusercontent.com/1486729/109502935-8b3fe880-7a91-11eb-80c8-66fa39f75cb0.png)

The behaviour of these apps haven't changed, however what has changed since 1.8 is we're now seeing a `DC` in envoy on perfectly OK status code (2xx etc).

**Comment by lambdai** [comment]
> The behaviour of these apps haven't changed, however what has changed since 1.8 is we're now seeing a DC in envoy on perfectly OK status code (2xx etc).

New 200 DC combination is interesting.
I guess access log delayed thus DC(downstream closed) is appended in the extreme cases where a http response is prepared before client received it

https://github.com/istio/istio/issues/31136#issuecomment-787777634 shows some application send reset to local istio proxy(port 15001), that is probably the cause of DC

**Comment by lambdai** [comment]
Http2 stop the proportionate from downstream close to upstream because per request failure is not likely to promote to connection failure

**Comment by lambdai** [comment]
Suspicious changes: 
* http: fixed a bug in access logs where early stream termination could be incorrectly tagged as a downstream disconnect, and disconnects after partial response were not flagged.

* http: added HCM level configuration of error handling on invalid messaging which substantially changes Envoy’s behavior when encountering invalid HTTP/1.1 defaulting to closing the connection instead of allowing reuse. This can temporarily be reverted by setting envoy.reloadable_features.hcm_stream_error_on_invalid_message to false, or permanently reverted by setting the HTTP/1 configuration override_stream_error_on_invalid_http_message to true to restore prior HTTP/1.1 behavior (i.e. connection isn’t terminated) and to retain prior HTTP/2 behavior (i.e. connection is terminated).

* http: added HCM level configuration of error handling on invalid messaging which substantially changes Envoy’s behavior when encountering invalid HTTP/1.1 defaulting to closing the connection instead of allowing reuse. This can temporarily be reverted by setting envoy.reloadable_features.hcm_stream_error_on_invalid_message to false, or permanently reverted by setting the HCM option to true to restore prior HTTP/1.1 beavior and setting the new HTTP/2 configuration override_stream_error_on_invalid_http_message to false to retain prior HTTP/2 behavior.

**Comment by lambdai** [comment]
Likely this one: https://github.com/envoyproxy/envoy/pull/12711

My interpretation is that any client connection close is will append a DC error detail. 
Envoy don't guarantee the response will be transmitted to the client, only best efforts

**Comment by Stono** [comment]
> > The behaviour of these apps haven't changed, however what has changed since 1.8 is we're now seeing a DC in envoy on perfectly OK status code (2xx etc).
> 
> New 200 DC combination is interesting.
> I guess access log delayed thus DC(downstream closed) is appended in the extreme cases where a http response is prepared before client received it
> 
> [#31136 (comment)](https://github.com/istio/istio/issues/31136#issuecomment-787777634) shows some application send reset to local istio proxy(port 15001), that is probably the cause of DC

Fwiw we see this on quite a lot of responses.  Will get you a % figure shortly.

**Comment by lambdai** [comment]
> Envoy don't guarantee the response will be transmitted to the client, only best efforts

See also https://github.com/envoyproxy/envoy/issues/2066#issuecomment-650380692

A http client side TCP half-close is not supported in Envoy. Essentially Envoy never knows if the response bytes are in local os buffer, or remote os buffer.

**Comment by Stono** [comment]
Hey @lambdai, 
Here are the %'s of source -> destination pairs of requests getting DC's

<img width="1680" alt="Screenshot 2021-03-01 at 19 45 35" src="https://user-images.githubusercontent.com/1486729/109550106-c0b2f900-7ac6-11eb-9ff3-35d4bd543f75.png">

All the top ones I checked aren't using connection pooling in the application code, which means they're creating more connection churn so perhaps exacerbating what we're seeing?

I'm not seeing any errors in the applications though (which is good) but from a user perspective it's not great:

<img width="411" alt="Screenshot 2021-03-01 at 19 47 34" src="https://user-images.githubusercontent.com/1486729/109550301-01ab0d80-7ac7-11eb-911d-9fe420df8dbe.png">

And it also increased metric cardinality in prometheus quite a bit (as we now have a `DC` version of each response code pair). cc @douglas-reid

**Comment by Stono** [comment]
> > Envoy don't guarantee the response will be transmitted to the client, only best efforts
> 
> See also [envoyproxy/envoy#2066 (comment)](https://github.com/envoyproxy/envoy/issues/2066#issuecomment-650380692)
> 
> A http client side TCP half-close is not supported in Envoy. Essentially Envoy never knows if the response bytes are in local os buffer, or remote os buffer.

Whilst it sounds like what we're seeing, that issue is from 2017 though, we've only started seeing this since 1.8?

**Comment by lambdai** [comment]
The goal of the issue is to explain there was no motivation to improve the tcp half-close at http stack.

You can see previously a "DC" is very strict. Previously the "DC" came with a high (if not 100%) accuracy at the cost that some "client early close" caused failure doesn't has the "DC" flag. Nowadays the DC has a high recall rate: client early close is likely to see "DC" flag, even though some of the response may be successfully delivered to client.

**Comment by Stono** [comment]
So my questions @lambdai are:

- Are we _sure_ this is TCP early close?  If so, how can we prove it
- Why in 1.8 do we now report this on the metrics?

**Comment by Stono** [comment]
Any thoughts on my questions @lambdai ?
@howardjohn do you have any thoughts ?

**Comment by lambdai** [comment]
Tcp early close is an example. RST is another example.

I am saying the recent code in istio/envoy 1.8 allows "DC" along with http code 200.
Previously envoy acts something like: Envoy knows it's tcp early close or RST, but now that the http code is 200, Envoy choose not to write "DC" in access log.

**Comment by lambdai** [comment]
I think you have proved that in app that "200 DC" is not that scary, which aligns with my find that DC is more like an access log behavior change

**Comment by Stono** [comment]
I think I agree that it's an access log change, so now my questions are:

- Shouldn't we have something in release notes that tells users of this relatively significant change to peoples logs and metrics?
- Could we add a way to disable it, as for us it's nothing but noise and extra cardinality on metrics?

**Comment by Stono** [comment]
@lambdai @howardjohn on one app that handles websocket upgrades, every `101` response results in a `101DC`.  I'm struggling to explain this to the product team, as they're rightly googling envoy status codes and see a DC as a potential problem.

They're rightly asking questions of me when we've changed the infrastructure but they haven't changed the app.

![Screenshot 2021-03-12 at 15 48 44](https://user-images.githubusercontent.com/1486729/110963831-734a4d80-834a-11eb-85c3-6dec02a8e5f7.png)
