### ISSUE TITLE
Can't enable components via manifest generation (--set doesnt work for me)

### ISSUE THREAD

**Issue by cawilliamson** [istio/istio#31146]
**Bug description**

In the `--help` page for Istio 1.9 CLI it shows that I should be able to run the following:

```
istioctl manifest generate --set components.policy.enabled=true
```

If I run that exact command, however, I get an error stating:

```
Error: could not unmarshal merged YAML: unknown field "policy" in v1alpha1.IstioComponentSetSpec.
```

What I'd actually like to pass in though is the following:

```
istioctl manifest generate --set components.egressGateways.enabled=true
```

But this results in a different but equally confusing error:

```
Error: could not unmarshal merged YAML: json: cannot unmarshal object into Go value of type []json.RawMessage
```

Any guidance here would be much appreciated.

[X] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

Manifest should be generated with ConfigMap including provided options.

**Steps to reproduce the bug**

Run: `istioctl manifest generate --set components.policy.enabled=true 2>&1 | head` which should allow you easily see the error I am seeing.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

1.9.0

**How was Istio installed?**

Generated a manifest and applied using Flux v2 GitOps tool. Essentially the same as kubectl apply -f <yaml>

**Environment where the bug was observed (cloud vendor, OS, etc)**

Amazon EKS, Amazon Linux 2.0

**Comment by bianpengyuan** [comment]
Mixer components (`components.policy` and `components.telemetry`) have been removed since istio 1.8: https://istio.io/latest/news/releases/1.8.x/announcing-1.8/#deprecations

Egressgateway component is a list, to set it with command line: `istioctl manifest generate --set components.egressGateways[0].enabled=true --set components.egressGateways[0].name=istio-egressgateway`. The doc needs to be updated.
