### ISSUE TITLE
Istio's flag --imagePullSecrets can be initialised with an empty string

### ISSUE THREAD

**Issue by polycaster** [istio/istio#31147]
**Bug description**
At the moment it is possible to initialise the flag `--imagePullSecrets <stringSlice>` with `--imagePullSecrets ''`.
When istio-proxy gets injected into a pod the image pull secrets field looks like this:
```
  imagePullSecrets:
  - {}             <------------- Empty secrets field
```
The above is the equivalent of initialising this argument with `[{}]`, which causes a constant stream of a very large volume of logs coming from kubelet (https://github.com/kubernetes/kubernetes/issues/99454), dependent on the number of istio proxies deployed,  stating that it is unable to retrieve secrets with no name.

This should not be allowed / istio should detect that there's no secrets and therefore the default `[]` should be enforced.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
I would expect that when an empty string is passed as an argument for the relevant flag that one of two scenarios happen:
1. The flag is rejected as empty secret names are not allowed
2. Istio recognises the secret as being invalid/empty and doesn't add a list with empty elements.

**Steps to reproduce the bug**
In any version of kubernetes:
1. Deploy istio with `--imagePullSecrets ''`
2. Deploy a pod that makes use of istio-proxy
3. Tail the kubelet logs and see the stream of `E0225 09:23:21.709821    1301 reflector.go:125] object-"istio-system"/"": Failed to list *v1.Secret: secrets is forbidden: User "system:node:$node_SA_identifier" cannot list resource "secrets" in API group "" in the namespace "istio-system": No Object name found` type logs

**Version**
Affects all versions of kubernetes at the moment
Istio 1.4 and 1.6 confirmed to have the issue
No helm

**How was Istio installed?**
Not relevant for the issue at hand

**Environment where the bug was observed (cloud vendor, OS, etc)**
EKS and GKE
OS are the relevant cloud provider kubernetes engine images

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by esnible** [comment]
@polycaster , did you install the operator using `istioctl operator init --imagePullSecrets ""`?

Or are you talking about something else?  How can I reproduce this?

@istio/wg-environments-maintainers I found the flag `--imagePullSecrets` and several other flags attached to `istioctl operator dump`.  I don't think these flags have any meaning there.  I also noticed the help text does not seem grammatical:

```
      --imagePullSecrets strings   The imagePullSecrets are used to pull the operator image from the private registry,
                                   could be secret list separated by comma, eg. '--imagePullSecrets imagePullSecret1,imagePullSecret2'
```
