### ISSUE TITLE
Add integration test for statefulsets/pod hostname

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#31148]
Support added in https://github.com/istio/istio/pull/31129/ but without tests

**Comment by howardjohn** [comment]
I marked this as a release blocker just so we can make sure evaluate disabling the feature if it doesn't meet the testing bar before we ship. It should not block the release in practice, but we may need to disable support if we don't do this.

**Comment by Monkeyanator** [comment]
Do we have any status on this? Evaluating release blockers and trying figure out which ones we can deescalate.

**Comment by howardjohn** [comment]
I think we need to either revert https://github.com/istio/istio/pull/31129 or add a test

cc @ramaraochavali

**Comment by ramaraochavali** [comment]
@howardjohn since the DNS resolve is  off by default in 1.10 and is still experimental - I do not feel strongly about reverting in 1.10 even if there is no test. 
But If you feel strongly about it - I am fine reverting in 1.10.

@hzxuzhonghu  WDYT?

**Comment by hzxuzhonghu** [comment]
For an alpha feature which is off by default, I think an integration test is not a must, but better to have.
