### ISSUE TITLE
Istio ingressgateway pod fails during startup with Readiness probe failed issue.

### ISSUE THREAD

**Issue by Ganesh-96** [istio/istio#31176]
Hi Team

We are trying to install istio 1.8.3 in our Kubernetes cluster. Ingress gateway is failing during startup with below error message.

> Readiness probe failed: Get "http://containerip:15021/healthz/ready": dial tcp containerip:15021: connect: connection refused.

Below is the error message from ingress gateway container logs.

> warn HTTP request unsuccessful with status: 400 Bad Request
> panic: runtime error: index out of range [1] with length 1

Istio install eventually fails with "Ingress gateways encountered an error: failed to wait for resource: resources not ready after 5m0s: timed out waiting for the condition" message.

**Comment by bianpengyuan** [comment]
Are you running on Azure? Looks like an error message from Azure metadata fetching. Need someone who has Azure env to debug this, but meanwhile, feels like lacking telemetry metadata should not block the proxy from starting up. cc @douglas-reid

**Comment by douglas-reid** [comment]
@bianpengyuan why do you believe that this is related to telemetry metadata?

**Comment by bianpengyuan** [comment]
> @bianpengyuan why do you believe that this is related to telemetry metadata?

Ah actually, good point.. The HTTP response error line is from azure platform, but the crash does not necessarily from that part of the code. @Ganesh-96 Do you have a full backtrace printed in the log?

**Comment by Ganesh-96** [comment]
Yes, we are running Istio on Azure. I hope you are asking for the istio-proxy logs.

> 2021-03-03T09:33:49.164093Z info FLAG: --concurrency="0"
> 2021-03-03T09:33:49.164154Z info FLAG: --domain="istio-system.svc.cluster.local"
> 2021-03-03T09:33:49.164164Z info FLAG: --help="false"
> 2021-03-03T09:33:49.164168Z info FLAG: --log_as_json="false"
> 2021-03-03T09:33:49.164172Z info FLAG: --log_caller=""
> 2021-03-03T09:33:49.164176Z info FLAG: --log_output_level="default:info"
> 2021-03-03T09:33:49.164180Z info FLAG: --log_rotate=""
> 2021-03-03T09:33:49.164184Z info FLAG: --log_rotate_max_age="30"
> 2021-03-03T09:33:49.164188Z info FLAG: --log_rotate_max_backups="1000"
> 2021-03-03T09:33:49.164192Z info FLAG: --log_rotate_max_size="104857600"
> 2021-03-03T09:33:49.164196Z info FLAG: --log_stacktrace_level="default:none"
> 2021-03-03T09:33:49.164204Z info FLAG: --log_target="[stdout]"
> 2021-03-03T09:33:49.164210Z info FLAG: --meshConfig="./etc/istio/config/mesh"
> 2021-03-03T09:33:49.164214Z info FLAG: --outlierLogPath=""
> 2021-03-03T09:33:49.164218Z info FLAG: --proxyComponentLogLevel="misc:error"
> 2021-03-03T09:33:49.164222Z info FLAG: --proxyLogLevel="warning"
> 2021-03-03T09:33:49.164226Z info FLAG: --serviceCluster="istio-ingressgateway"
> 2021-03-03T09:33:49.166521Z info FLAG: --stsPort="0"
> 2021-03-03T09:33:49.166542Z info FLAG: --templateFile=""
> 2021-03-03T09:33:49.166550Z info FLAG: --tokenManagerPlugin="GoogleTokenExchange"
> 2021-03-03T09:33:49.166565Z info Version 1.8.3-e282a1f927086cc046b967f0171840e238a9aa8c-Clean
> 2021-03-03T09:33:49.166818Z info Obtained private IP [10.36.0.24]
> 2021-03-03T09:33:49.166987Z info Apply mesh config from file defaultConfig:
> discoveryAddress: istiod.istio-system.svc:15012
> proxyMetadata:
> DNS_AGENT: ""
> tracing:
> zipkin:
> address: zipkin.istio-system:9411
> enablePrometheusMerge: true
> rootNamespace: istio-system
> trustDomain: cluster.local
> 2021-03-03T09:33:49.180628Z info Effective config: binaryPath: /usr/local/bin/envoy
> concurrency: 0
> configPath: ./etc/istio/proxy
> controlPlaneAuthPolicy: MUTUAL_TLS
> discoveryAddress: istiod.istio-system.svc:15012
> drainDuration: 45s
> envoyAccessLogService: {}
> envoyMetricsService: {}
> parentShutdownDuration: 60s
> proxyAdminPort: 15000
> proxyMetadata:
> DNS_AGENT: ""
> serviceCluster: istio-ingressgateway
> statNameLength: 189
> statusPort: 15020
> terminationDrainDuration: 5s
> tracing:
> zipkin:
> address: zipkin.istio-system:9411
> 
> 2021-03-03T09:33:49.180690Z info Proxy role: &model.Proxy{RWMutex:sync.RWMutex{w:sync.Mutex{state:0, sema:0x0}, writerSem:0x0, readerSem:0x0, readerCount:0, readerWait:0}, Type:"router", IPAddresses:[]string{"10.36.0.24"}, ID:"istio-ingressgateway-6d59598f94-4h4bd.istio-system", Locality:(*envoy_config_core_v3.Locality)(nil), DNSDomain:"istio-system.svc.cluster.local", ConfigNamespace:"", Metadata:(*model.NodeMetadata)(nil), SidecarScope:(*model.SidecarScope)(nil), PrevSidecarScope:(*model.SidecarScope)(nil), MergedGateway:(*model.MergedGateway)(nil), ServiceInstances:[]*model.ServiceInstance(nil), IstioVersion:(*model.IstioVersion)(nil), VerifiedIdentity:(*spiffe.Identity)(nil), ipv6Support:false, ipv4Support:false, GlobalUnicastIP:"", XdsResourceGenerator:model.XdsResourceGenerator(nil), WatchedResources:map[string]*model.WatchedResource(nil)}
> 2021-03-03T09:33:49.180709Z info JWT policy is first-party-jwt
> 2021-03-03T09:33:49.180842Z info PilotSAN []string{"istiod.istio-system.svc"}
> 2021-03-03T09:33:49.180917Z info sa.serverOptions.CAEndpoint == istiod.istio-system.svc:15012 Citadel
> 2021-03-03T09:33:49.181034Z info Using CA istiod.istio-system.svc:15012 cert with certs: var/run/secrets/istio/root-cert.pem
> 2021-03-03T09:33:49.181273Z info citadelclient Citadel client using custom root: istiod.istio-system.svc:15012 -----BEGIN CERTIFICATE-----
> MIIC/DCCAeSgAwIBAgIQIq+9J05Bp/DncoGKzZtPUTANBgkqhkiG9w0BAQsFADAY
> MRYwFAYDVQQKEw1jbHVzdGVyLmxvY2FsMB4XDTIxMDMwMjA5MzUxN1oXDTMxMDIy
> ODA5MzUxN1owGDEWMBQGA1UEChMNY2x1c3Rlci5sb2NhbDCCASIwDQYJKoZIhvcN
> AQEBBQADggEPADCCAQoCggEBAOsbCHTlmEjk5pvkuqpaS64S0nQeVVfFNik9ExjH
> mu++APxqRLu+V/2J1+ge+0aKu6KPrrlpvjIDe0BGIvb1FqYAyLyWmUgVJCgKH4Vc
> x3iyywi639pXXIz/JH8z0DfhQIkJ8rCk7LwXhm6Ci+1zYdU5glywc19d80NNHGPS
> sHuxCObuuUovzPIDekmwp6xvsUunQG4R8xBGql4EJldDQcZ7MxXywp3H0xJbJDD4
> 0/vfAJnY+1+9qSTOsYbqxwowOaP01UrOYiXbKak69TvXMSUzto9iy2T0Rk5xKqzY
> hjW5XzOAbWgNDyTgnHEbIW/JpJGYx+whtndkWklAqioL0SkCAwEAAaNCMEAwDgYD
> ifbfdhRY7Yad2Wpj4PkJVn+hrQuUSvxTGAnG+tLyjdAEyvGcT+q+0Aj6I+139z7k
> 4yAYsv+LoGCRMPXPfHljtQGJOHi5F7cOcstt+G0EsOmkan17k3sFMwsPHP6pbmQP
> Wbt8HodCDoPcXkt/FaRK/gn+BwoR6ckDEMlMN5njbX1zNRGzv6ixEEzPPZYevYJy
> -----END CERTIFICATE-----
> 
> 2021-03-03T09:33:49.243318Z info Starting gateway SDS
> 2021-03-03T09:33:49.347346Z info sds Start SDS grpc server
> 2021-03-03T09:33:49.347344Z info sds SDS gRPC server for workload UDS starts, listening on "./etc/istio/proxy/SDS"
> 
> 2021-03-03T09:33:49.347600Z info sds SDS gRPC server for gateway controller starts, listening on "./var/run/ingress_gateway/sds"
> 
> 2021-03-03T09:33:49.347656Z info xdsproxy Initializing with upstream address istiod.istio-system.svc:15012 and cluster Kubernetes
> 2021-03-03T09:33:49.347737Z info sds Start SDS grpc server for ingress gateway proxy
> 2021-03-03T09:33:49.348332Z info xdsproxy adding watcher for certificate var/run/secrets/istio/root-cert.pem
> 2021-03-03T09:33:49.348653Z info Starting proxy agent
> 2021-03-03T09:33:49.348915Z info Received new config, creating new Envoy epoch 0
> 2021-03-03T09:33:49.348963Z info Epoch 0 starting
> 2021-03-03T09:33:49.349055Z info Opening status port 15020
> 
> 2021-03-03T09:33:50.372375Z warn HTTP request unsuccessful with status: 400 Bad Request
> panic: runtime error: index out of range [1] with length 1
> 
> goroutine 91 [running]:
> istio.io/istio/pkg/bootstrap/platform.(*azureEnv).azureTags(0xc000f14000, 0xc0012077d0)
> istio.io/istio/pkg/bootstrap/platform/azure.go:193 +0x274
> istio.io/istio/pkg/bootstrap/platform.(*azureEnv).Metadata(0xc000f14000, 0x16)
> istio.io/istio/pkg/bootstrap/platform/azure.go:154 +0x19a
> istio.io/istio/pkg/bootstrap.extractAttributesMetadata(0xc0008dc500, 0x50, 0x50, 0x29b5500, 0xc000f14000, 0xc00087efc0)
> istio.io/istio/pkg/bootstrap/config.go:458 +0x3ab
> istio.io/istio/pkg/bootstrap.getNodeMetaData(0xc0008dc500, 0x50, 0x50, 0x29b5500, 0xc000f14000, 0xc001220970, 0x1, 0x1, 0x0, 0xc000652480, ...)
> istio.io/istio/pkg/bootstrap/config.go:495 +0x1c7
> istio.io/istio/pkg/bootstrap.Config.toTemplateParams(0xc000e82540, 0x6f, 0xc000652480, 0x29b5500, 0xc000f14000, 0xc0003fedb0, 0x1, 0x1, 0xc0008dc500, 0x50, ...)
> istio.io/istio/pkg/bootstrap/config.go:125 +0x525
> istio.io/istio/pkg/bootstrap.(*instance).WriteTo(0xc00118b450, 0x2673847, 0x2f, 0x29568e0, 0xc00000e218, 0x0, 0x0)
> istio.io/istio/pkg/bootstrap/instance.go:71 +0xe5
> istio.io/istio/pkg/bootstrap.(*instance).CreateFileForEpoch(0xc00118b450, 0x0, 0x0, 0x0, 0x0, 0x0)
> istio.io/istio/pkg/bootstrap/instance.go:128 +0x193
> istio.io/istio/pkg/envoy.(*envoy).Run(0xc000652480, 0x21754e0, 0xc0011a86a0, 0x0, 0xc000415f20, 0x0, 0x0)
> istio.io/istio/pkg/envoy/proxy.go:168 +0x85d
> istio.io/istio/pkg/envoy.(*agent).runWait(0xc000e69450, 0x21754e0, 0xc0011a86a0, 0x0, 0xc000415f20)
> istio.io/istio/pkg/envoy/agent.go:260 +0xf9
> created by istio.io/istio/pkg/envoy.(*agent).Restart
> istio.io/istio/pkg/envoy/agent.go:160 +0x2e5

**Comment by douglas-reid** [comment]
@bianpengyuan @Ganesh-96 ok, this is clearer :).

I don't have access to Azure, but it seems like there is a tag returned that doesn't have a value ?

https://github.com/istio/istio/blob/master/pkg/bootstrap/platform/azure.go#L193

We can update the code to ensure the split results are handled properly, but I won't know if that produces meaningful results.

**Comment by Ganesh-96** [comment]
We are able to install 1.6 version though, facing issues from 1.7 onwards. Not sure if it helps in fixing the above issue :)

**Comment by douglas-reid** [comment]
@Ganesh-96 i think 1.7 is the first release in which azure platform metadata was exposed in envoy. do you happen to have a dump of the azure metadata for the instance?  or even just a list of the tags on the instance?

**Comment by Ganesh-96** [comment]
Application, CostSpoc, Environment, Project & SupportSpoc are the tags we have for that instance. All these tags do have a value.

**Comment by douglas-reid** [comment]
@Ganesh-96 interesting. would you be able to, from the instance, run something like:

`curl -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance?api-version=2020-09-01" | jq` (from the Azure docs)

and publish the results here. I'm really only interested in the `compute.tags` output, so if you are able to get that info, please feel free to redact anything else that might be sensitive (and change the values of the tags appropriately too -- i'm only interested in the format).

**Comment by Ganesh-96** [comment]
Here you go..
`{
    "compute": {
        "tags": "Application:Istio;CostSpoc:user1@email.com;Environment:Dev;Project:Test;SupportSpoc:user1@email.com; user2@email.com; user2@email.com",
        "tagsList": [
            {
                "name": "Application",
                "value": "Istio"
            },
            {
                "name": "CostSpoc",
                "value": "user1@email.com"
            },
            {
                "name": "Environment",
                "value": "Dev"
            },
            {
                "name": "Project",
                "value": "Test"
            },
            {
                "name": "SupportSpoc",
                "value": "user1@email.com; user2@email.com; user2@email.com"
            }
        ]
    }
}`

**Comment by Ganesh-96** [comment]
I think the issue is caused by the ";" in the SupportSpoc tag values. Now I am able to deploy 1.8.3 version after removing it.

**Comment by douglas-reid** [comment]
Ouch. Looking at the [spec](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/tag-resources#limitations), `;` should be allowed, but I don't see how that serialization would support it.

https://docs.microsoft.com/en-us/azure/virtual-machines/linux/instance-metadata-service?tabs=linux#instance-metadata seems to imply that `tagsList` was added for similar reasons. I think we should investigate transitioning to `tagsList` where possible.

**Comment by Ganesh-96** [comment]
Able to deploy 1.9.1 as well. Getting one different issue now. Installed Istio in a different namespace and deleted it, but now getting below error. Any suggestions on how to fix the below issue.

> Istiod encountered an error: failed to update resource with server-side apply for obj EnvoyFilter/istio-system/metadata-exchange-1.8: Internal error occurred: failed calling webhook "validation.istio.io": Post "https://istiod.istio-namespace-16.svc:443/validate?timeout=30s": service "istiod" not found

**Comment by douglas-reid** [comment]
@Ganesh-96 can you open a separate issue or discussion on discord for the validation / webhook issue?  I'd like to keep this issue focused on the tags bug.

**Comment by Ganesh-96** [comment]
Sure, thanks for looking into the issue @douglas-reid
