### ISSUE TITLE
istioctl proxy-status missing old version sidecars

### ISSUE THREAD

**Issue by yanniszark** [istio/istio#31177]
**Bug description**

We have used `istioctl proxy-status` to detect sidecars in the cluster. I have caught the command missing sidecars when:
- The control plane is in a new version X (e.g., 1.9.0)
- The data plane (sidecars) are in an older version Y (e.g., 1.5)

Essentially, in the middle of an upgrade.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[x] User Experience
[ ] Developer Infrastructure
[x] Upgrade

**Expected behavior**

I expected `istioctl proxy-status` to list all sidecars.

**Steps to reproduce the bug**

1. Install Istio 1.5.7 and some workloads with sidecars
2. Upgrade control plane to 1.9.0
3. Run `istioctl proxy-status`

**Comment by howardjohn** [comment]
We don't support upgrades from istio 1.5 to 1.9. They are probably missing because a 1.5 proxy cannot actually connect to 1.9 Istio, so its actually reporting the truth?

**Comment by yanniszark** [comment]
Thanks @howardjohn. Yes, I'm aware of Istio's upgrade policy. Then I'm guessing that the `istioctl` command is not meant for the use-case of finding all Pods with sidecars in order to recreate them. 

Finally, I wanted to ask if there is an authoritative way to find all Pods with sidecars. Thanks again for your help :)

**Comment by howardjohn** [comment]
It doesn't find all pods with sidecars, it finds all pods connected to Istiod. To find all pods with sidecars  you could look for the proxy v2 image in pod spec?

**Comment by esnible** [comment]
To see which pods have sidecars that need restart or are disconnected, try `istioctl x injector list`

**Comment by howardjohn** [comment]
Closing as working at intended. Thanks!
