### ISSUE TITLE
Incorrect/Incomplete validation of port settings for gateways in operator profile

### ISSUE THREAD

**Issue by rtmie** [istio/istio#31179]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

[ ] Docs
[ X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ X] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
When I define a gateway type in the operator profile validation of the port set for the gateway does not allow for setting of sysctls for   `net.ipv4.ip_unprivileged_port_start`

```
  sysctls:
                - name: net.ipv4.ip_unprivileged_port_start
                - value: some_port_under_1024
 ``` 
**Steps to reproduce the bug**
create an istiooperator profile as follows:
```    egressGateways:
      - name: istio-egressgateway
        enabled: true
        k8s:
          overlays:
          - kind: Deployment
            name: istio-egressgateway
            patches:
            - path: spec.template.spec.securityContext
              value:
                sysctls:
                - name: net.ipv4.ip_unprivileged_port_start
                  value: "80"
            - path: spec.template.spec.affinity.nodeAffinity.preferredDuringSchedulingIgnoredDuringExecution
              value: []
            - path: spec.template.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms
              value:
              - matchExpressions:
                - key: affinity
                  operator: In
                  values:
                  - general
            - path: spec.template.spec.affinity.podAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution
              value:
              - labelSelector:
                  matchExpressions:
                  - key: istio
                    operator: In
                    values:
                    - egressgateway
                    - internal-egressgateway
                topologyKey: "kubernetes.io/hostname"
          env:
            - name: ISTIO_META_ROUTER_MODE
              value: sni-dnat
          hpaSpec:
            maxReplicas: 5
            metrics:
              - resource:
                  name: cpu
                  targetAverageUtilization: 80
                type: Resource
            minReplicas: 1
            scaleTargetRef:
              apiVersion: apps/v1
              kind: Deployment
              name: istio-egressgateway
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 2000m
              memory: 1024Mi
          service:
            ports:
              - name: https
                port: 443
                targetPort: 443
  ```
Then run `istioctl manifest generate -f <myprofile.yaml>`
Error returned `Error: generated config failed semantic validation: port https/443 in gateway istio-egressgateway invalid: targetPort is set to 443, which requires root. Set targetPort to be greater than 1024 or configure values.gateways.istio-egressgateway.runAsRoot=true`
It should allow for users to set the sysctls for lowering unpriveleged-port-start index
 
**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
Tested with istioctl version 1.7 and 1.8

**How was Istio installed?**
Running as pre installation check with istioctl on dev system.

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
It would be great if the logic here was perfect but it's not really possible - a user could even have an init container that sets sysctls or something which we have no way of detecting. given we are doing arbitrary patching here it doesn't seem like we can detect this easily.

One option which isn't great is you can do --force

**Comment by rtmie** [comment]
But doesn't that suggest the operator is implementing a hard validation which it doesn't have sufficient data to decide upon?

I assume using "--force" will override *all* validations which is not a runner.
