### ISSUE TITLE
metrics merging: detect prometheus.io.scrape format

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#31187]
Due to escaping logic in prom, this is equivilent to prometheus.io/scrape (`__meta_kubernetes_pod_annotation_prometheus_io_path`). So we probably want to detect both. See https://github.com/openfaas/faas-netes/issues/714.

**Comment by howardjohn** [comment]
not stale

**Comment by howardjohn** [comment]
not stale

**Comment by howardjohn** [comment]
not stale

**Comment by zirain** [comment]
@howardjohn what's this means? can you share more details?

**Comment by howardjohn** [comment]
Currently we look for prometheus.io/scrape annotation in pkg/kube/inject
and rewrite it. But actually due to how prometheus `Kubernetes meta ->
prometheus labels` mapping works, many characters end up as the same thing.
So for example, `prometheus.io/scrape` and `prometheus.io.scrape` are
identical to prometheus, but we only match the first format.
