### ISSUE TITLE
Move analysis framework out of galley design

### ISSUE THREAD

**Issue by jasonwzm** [istio/istio#31184]
**Describe the feature request**
Come up with a design to move analysis out of galley for implementation in 1.10 timeline.

/cc @therealmitchconnors @esnible @howardjohn  

**Describe alternatives you've considered**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[X] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by howardjohn** [comment]
done
