### ISSUE TITLE
Show changes that will be made in the cluster before applying in istioctl

### ISSUE THREAD

**Issue by ostromart** [istio/istio#31185]
Although istioctl manifest generate along with istioctl manifest diff give some insight into changes between configurations in the cluster, a more direct diff would improve user confidence in the changes being applied. This request has come up a number of times in the past, most recently at IstioCon.
The feature could be a --dry-run flag enhancement where the diffs that would be applied to the cluster are displayed for inspection. The key part of the implementation is to diff against cluster resources. Most of the code for diffing already exists so this is a matter of composing the feature from the building blocks.

**Comment by litong01** [comment]
I have been working on this issue and should provide a PR soon. Thanks.

**Comment by zhlsunshine** [comment]
Hi @litong01, shall we move this issue to 1.12?

**Comment by litong01** [comment]
@zhlsunshine After a lot of work on this, it seems there is really no good solution regarding this issue. Probably will not be fixed.
