### ISSUE TITLE
Support Agent Metrics Publishing to a Http Endpoint

### ISSUE THREAD

**Issue by ramaraochavali** [istio/istio#31197]
**Describe the feature request**
All the agent metrics are available in prometheus format. However we do not use prometheus but use our internal metrics system. The feature request is to enable Pilot agent to publish its metrics periodically in a Json format to an Http endpoint provided as a Pilot Agent argument.

**Describe alternatives you've considered**
None in the Istio system. 

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by ramaraochavali** [comment]
@howardjohn @hzxuzhonghu What do you think? Any concerns to add this feature?

**Comment by howardjohn** [comment]
Why just the agent? What about istiod, and envoy?

**Comment by howardjohn** [comment]
cc @istio/wg-policies-and-telemetry-maintainers

**Comment by ramaraochavali** [comment]
Envoy we configure Metrics Service so that Envoy directly pushes metrics to Metrics Service.

Istiod also would be good to add but for Istiod we built a scraper sidecar that does this job and add that along with our deployment because they are limited instances in number. 

IMO, it would be useful to add for Istiod as well. Envoy I am not sure (atleast not needed for us).

**Comment by mandarjog** [comment]
open census/ open telemetry is designed for this. We can certainly add an exporter. I don’t think we should add a custom json format unless there is a very compelling reason.
@douglas-reid

**Comment by ramaraochavali** [comment]
I am not suggesting custom json -  I was thinking of this https://github.com/prometheus/prom2json - but any standard json would be good. Only thing we need is it pushes the format to a http endpoint so that we can push it our metrics backend.

**Comment by douglas-reid** [comment]
We designed the metrics system with the idea of supporting export to different formats. So far, I believe only Stackdriver and Prometheus have been built, but adding a third format is certainly doable. @ramaraochavali have you considered a prom pushgateway as the frontend for your endpoint?

**Comment by ramaraochavali** [comment]
@douglas-reid 
> have you considered a prom pushgateway as the frontend for your endpoint?

No. Because we can not run these in our envs as they are not approved for prod use in our envs.

**Comment by douglas-reid** [comment]
@ramaraochavali what about the otlp format? would that be acceptable? i'm trying to think of something with broad appeal.

**Comment by ramaraochavali** [comment]
Sorry, I am not fully aware of otlp format but should be OK - I am assuming is it is some form of protobuf/json?

**Comment by ramaraochavali** [comment]
@douglas-reid another idea if we want broader appeal - why do not we use the Envoy XDS Metrics Service it self and push on the stream for Agent and Istiod? I think many people are using that already and it would be generic gRPC interface that most people can implement and would be inline with what Envoy is supporting.

**Comment by howardjohn** [comment]
Does kubernetes expose metrics in any format other than Prometheus?

**Comment by douglas-reid** [comment]
IIRC, Envoy's MetricsService is a wrapper around prometheus protos. So it should be doable without much burden. I guess the one thing we'll need is distribution of the endpoint info from meshconfig (or wherever providers end up).

@ramaraochavali you mention a sidecar for istiod. just to confirm: have you considered possibly using something like https://github.com/open-telemetry/opentelemetry-collector as a translation mechanism?

**Comment by ramaraochavali** [comment]
> IIRC, Envoy's MetricsService is a wrapper around prometheus protos. So it should be doable without much burden. I guess the one thing we'll need is distribution of the endpoint info from meshconfig (or wherever providers end up).

Yes. It is a wrapper aroung prometheus protos. Using metshconfig to define it makes sense.

> @ramaraochavali you mention a sidecar for istiod. just to confirm: have you considered possibly using something like https://github.com/open-telemetry/opentelemetry-collector as a translation mechanism?

No. We just built our own simple converter.

**Comment by ramaraochavali** [comment]
@douglas-reid if you are good with publishing via metrics service, I can try enabling that via Env var for pilot agent as an experiment and once we are good with this - we can move that address config to meshConfig and enable it for both istiod and  agent. Let me know if you have any other ideas as well. We can try.

**Comment by howardjohn** [comment]
How do other non-envoy applications in a cluster report metrics? like kubernetes itself, maybe grafana certmanager, etc. I assume they are not all emitting envoy specific metrics format. It feels odd to me to have this

**Comment by ramaraochavali** [comment]
> not all emitting envoy specific metrics format

This is not envoy specific metrics format - it is prometheus format only https://github.com/envoyproxy/envoy/blob/main/api/envoy/service/metrics/v3/metrics_service.proto#L52. The service is XDS which wraps this

**Comment by douglas-reid** [comment]
@ramaraochavali the address config already exists in MeshConfig by way of the default ProxyConfig, right? 

@howardjohn that's why i mentioned the OTel collector. it could act as a Prom frontend (with SD and everything) and export into whatever format was desired. that would be fairly universal (and wouldn't require Istio changes).

**Comment by ramaraochavali** [comment]
> @ramaraochavali the address config already exists in MeshConfig by way of the default ProxyConfig, right?

Oh yeah. I forgot

**Comment by ramaraochavali** [comment]
So the OTel collector has to run on every pod as sidecar?

**Comment by ramaraochavali** [comment]
@howardjohn I am not tied to metrics service if that is a concern - any generic format would work as long as pilot agent can publish to a configured endpoint rather than running additional sidecars/software.

**Comment by douglas-reid** [comment]
> So the OTel collector has to run on every pod as sidecar?

not necessarily. i think you _could_ put a sidecar agent or daemonset everywhere, but i'm not sure that is recommended or required for the prom integration (but i'm not an expert on OTel architectures).

but that does still require additional software.

**Comment by ramaraochavali** [comment]
Ok. So running additional software is not a viable option for us especially for agent because it can run heterogenous environments (K8s, baremetal, vm etc...) in huge numbers and in uncontrolled way. Services just come on to mesh.

Looks like based on above  we have two options
- Publish it to an Endpoint using JSON https://github.com/prometheus/prom2json - This is mainly prometheus format inJSON.
- Use Xds Metrics Service which is again prometheus format bug in gRPC. However the metrics services calls the field "envoy_metrics" which might look little odd - might be ok for agent but certainly not good for istiod. Also @howardjohn seems to have concerns using that.

Any reservations about using option 1 - it seems simple and adheres to prometheus metric format?

**Comment by ramaraochavali** [comment]
@douglas-reid @howardjohn what do you think?

**Comment by mandarjog** [comment]
prom2json is a good solution, it is vendor neutral, not envoy created (even though it is prom-proto over xds).

we just have to measure how much is the cost of this conversion per istio-agent.

I think push gateway format is my 2nd choice. It is an ok format which needs minimal processing from raw scrapes.

**Comment by ramaraochavali** [comment]
> we just have to measure how much is the cost of this conversion per istio-agent.

Assuming that we push every 30s (ofcourse we will make it configurable) if we push only agent stats it wont be that costly - but if we push Envoy metrics also it might be costly depending on how many clusters it has. May be we can make it configurable - like push Agent only or both?

**Comment by mandarjog** [comment]
I though your requirement was to push everything and convert it from a pull to a push model. We need to measure pushing all if that is the case.

**Comment by ramaraochavali** [comment]
No. Our requirement is just agent metrics for Envoy we already use Envoy Metrics Service

**Comment by ramaraochavali** [comment]
> We need to measure pushing all if that is the case.

I am fine measuring this even if it is not our usecase though. But just want to bring that option of configurability because people who do not need both do not pay the price.

**Comment by douglas-reid** [comment]
> @douglas-reid @howardjohn what do you think?

This needs to be something discussed in the E&T WG, but I don't see any major objections to adding the functionality. I think we need a robust design on formats and configurability, and how something like this _might_ align with proposed APIs, etc.

**Comment by douglas-reid** [comment]
> When do you think we can have this design?

@ramaraochavali we'll need to find someone to drive it, and find someone to do the work.

**Comment by ramaraochavali** [comment]
@douglas-reid @mandarjog assuming that P&T is fine with publishing agent metrics (please discuss in this week's WG and let me know) as JSON I can take up implementation on agent side.

>  I think we need a robust design on formats and configurability, and how something like this might align with proposed APIs, etc.
This part I can not help because I am not familiar with telemetry formats in general and plan for proposed apis etc.

I do also think if we start agent publishing metrics with minimal config support from ENV VARs (like URL + Frequency) - we can fold it in to proposed API when it arrives.

Let me know what you think

**Comment by mandarjog** [comment]
@ramaraochavali trying to understand your prod restrictions., You are able to run a new metrics receiver service in prod but you cannot run a Prometheus scraper?

**Comment by ramaraochavali** [comment]
The metrics service is developed by us and is  regular mesh service,  went through security approvals etc. The Prometheus scraper needs special approvals as it is third party software.

**Comment by mandarjog** [comment]
Even though the pushing prom-json formatted data is reasonable, it is currently very bespoke to your use case. You commented that you have an istiod scraper sidecar.
What is the difference between that and something that you would use to scrape from agents and say relay it to your metrics service? Service discovery is the only difference, correct?

If we were to do this, The standard way would be to write a custom exporter (https://opencensus.io/exporters/custom-exporter/go/metrics/) and emit in prom-json format.

**Comment by ramaraochavali** [comment]
> What is the difference between that and something that you would use to scrape from agents and say relay it to your metrics service? Service discovery is the only difference, correct?

Yes. It is doable.  We can certainly add that sidecar to all agents. I am only worried at the explosion of additional sidecar across various envs (baremetal, vms , k8s etc...) and with the number of Envoys we run today and the planned growth in near future - I thought it would be useful if pilot agent can publish them so that we can avoid that sidecar. I am surprised no one else needs such a feature in agent - there are many non prometheus users.

BTW, it is the same reason why we added Metric Service to Envoy in the beginning :-)

**Comment by ramaraochavali** [comment]
@mandarjog @douglas-reid Curious - what was the outcome of the E&T WG discussion on this?

**Comment by mandarjog** [comment]
Rama's doc for review: [link](https://docs.google.com/document/d/1Jcwp6Tv--quRxOd2-r7-OO0Dvs__9W7CLTvCCJu1wpg/edit#)

**Comment by ramaraochavali** [comment]
@mandarjog @douglas-reid gentle ping on the doc ^? Are you good with pushing agent metrics to metrics service if configured?
