### ISSUE TITLE
Legacy protocol support in Istio- Diameter Radius etc 

### ISSUE THREAD

**Issue by vsharathis** [istio/istio#31202]
In the 4g and 5g collaboration, the legacy protocol support is missed in the istio, as per the Istio document 
istio  supports following protocols :

```
-       http
- 	http2
- 	https
- 	tcp
- 	tls
- 	grpc
- 	grpc-web
- 	mongo
- 	mysql*
- 	redis*
- 	udp
```
but when in the actual telco vendors have both legacy and istio supported protocols (till now), if istio can identify the legacy protocols, (Diameter, radius)  vendors can use istio as a load balancer for both legacies and supported protocols.

**Comment by howardjohn** [comment]
Never heard of Diameter but it looks like it uses TCP. Any protocol that uses TCP is supported by Istio. It does look like radius uses UDP which is tracked in https://github.com/istio/istio/issues/1430

**Comment by vsharathis** [comment]
@howardjohn Thank you for the quick reply, 

**RADIUS **
RADIUS stands for Remote Authentication Dial-In User Service, is a security protocol used in the AAA framework to provide centralized authentication for users who want to gain access to the network.
**Features – Some of the features of RADIUS are:**

- Open standard protocol for AAA framework i.e it can use between any vendor device and Cisco ACS server.
- **It uses UDP as a transmission protocol**.
- It uses UDP port number 1812 for authentication and authorization and 1813 for accounting.
- If the device and ACS server is using RADIUS then only the passwords of AAA packets are encrypted.
- No explicit command authorization can be implemented.
- It provides greater extensive accounting support than TACACS+.
- In RADIUS, authentication and authorization are coupled together.


**Diameter** is a planned replacement of RADIUS. It is an AAA protocol for applications such as network access and IP mobility.
It is intended to work in both local and roaming AAA situations.

- The diameter is just twice the predecessor protocol Radius.
- **It uses TCP or SCTP** and not UDP.
- It uses transport-level security (IPSEC or TLS).
- It has a 32-bit identifier instead of 8 bit.
- It supports stateless as well as stateful mode.
- It supports application-layer acknowledgment, defines failover.
- It offers better roaming support.
- It uses AVPs.
- Diameter allows the definition of new commands and attributes. It is easy to extend.

in simple words diameter support **TLS/TCP and DTLS/SCTP**

**Comment by howardjohn** [comment]
Istio should work with Diameter as it's tcp based and we support tcp. For udp support we have an existing issue you can follow.

For native support if these protocols beyond tcp level metrics and routing, please file an issue with envoy - that would be a prerequisite. Even then it would be a long ways to get support in Istio - more likely only supported via extensions like https://github.com/aeraki-framework/aeraki. Thanks
