### ISSUE TITLE
`istio-sidecar.rpm` fails to install on RHEL, Amazon Linux

### ISSUE THREAD

**Issue by pisto** [istio/istio#31203]
**Bug description**

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
The `istio-sidecar` RPM package for centos uses `addgroup` to create the users. `addgroup` is not available in RHEL and derivates (such as Amazon Linux). Since the script runs with `-e`, the execution of the install script is halted:
```
[root@ip-192-168-116-203 ~]# rpm -i istio-sidecar.rpm 
/var/tmp/rpm-tmp.CvJQwC: line 27: addgroup: command not found
warning: %post(istio-sidecar-1.9.0-1.x86_64) scriptlet failed, exit status 127
```
The [modern, universal](https://wiki.archlinux.org/index.php/users_and_groups#Example_adding_a_system_user) (debian derivatives too) way to create a system user is the following:
```
[root@ip-192-168-116-203 ~]# id istio-proxy
id: istio-proxy: no such user
[root@ip-192-168-116-203 ~]# useradd -r -s /usr/bin/nologin istio-proxy
[root@ip-192-168-116-203 ~]# id istio-proxy
uid=995(istio-proxy) gid=993(istio-proxy) groups=993(istio-proxy)
```
Currently, a workaround is to run this command _before_ installing the `istio-sidecar` package.

As a side note, I believe that the empty directories that the script creates (`/var/lib/istio` etc) are best created via files in the packages, not via install scripts.
**Steps to reproduce the bug**
Just follow the documentation to join a VM in the mesh, up to the `rpm -i istio-sidecar.rpm` step.

**Version**
istio-sidecar versions 1.9.0 and 1.9.1

**Environment where the bug was observed (cloud vendor, OS, etc)**
Any RHEL derivate, including on cloud (Amazon Linux on AWS).

**Comment by howardjohn** [comment]
What RHEL version? Only 8+ is supported

**Comment by pisto** [comment]
```
[pisto@kp ~]$ podman run --rm -it registry.access.redhat.com/ubi8/ubi:latest
[root@3fa7a7006116 /]# dnf provides '*/addgroup'
Updating Subscription Management repositories.
Unable to read consumer identity
Subscription Manager is operating in container mode.
Red Hat Enterprise Linux 8 for x86_64 - BaseOS (RPMs)                                                                                                         2.5 MB/s |  28 MB     00:11    
Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs)                                                                                                      2.5 MB/s |  26 MB     00:10    
Red Hat Universal Base Image 8 (RPMs) - BaseOS                                                                                                                562 kB/s | 775 kB     00:01    
Red Hat Universal Base Image 8 (RPMs) - AppStream                                                                                                             1.7 MB/s | 5.1 MB     00:03    
Red Hat Universal Base Image 8 (RPMs) - CodeReady Builder                                                                                                      20 kB/s |  13 kB     00:00    
Error: No Matches found
```

**Comment by howardjohn** [comment]
I am a bit confused, as we have a check here: https://github.com/istio/istio/blob/d194755933597e5553586889f4914460d8c05585/tools/packaging/postinst.sh#L22

Running this is `registry.access.redhat.com/ubi8/ubi:latest` seems to work.

Is amazon linux not matching that check perhaps? We probably need to make it more robust and check the command exists not attempt to determine the OS

**Comment by pisto** [comment]
> I am a bit confused, as we have a check here:
> 
> https://github.com/istio/istio/blob/d194755933597e5553586889f4914460d8c05585/tools/packaging/postinst.sh#L22
> 
> Running this is `registry.access.redhat.com/ubi8/ubi:latest` seems to work.
> 
> Is amazon linux not matching that check perhaps? We probably need to make it more robust and check the command exists not attempt to determine the OS

Tested on amazon linux:
```
[ec2-user@ip-192-168-193-133 ~]$ find /etc/*release | grep -Eiq 'centos|redhat'
[ec2-user@ip-192-168-193-133 ~]$ echo $?
1
```
so it would use `addgroup`. That check can be fixed by inspecting the content of those files:
```
[ec2-user@ip-192-168-193-133 ~]$ grep -Eiq 'centos|redhat' $(find /etc/*release)
[ec2-user@ip-192-168-193-133 ~]$ echo $?
0
```
I think I was wrong to claim that `useradd` is the modern way to add an user. However, it's part of `shadow-utils`, and I believe it is present on all distros. Using that would get rid of these checks altogether.
