### ISSUE TITLE
"istioctl install --set <boolvar>=<bool>" fails

### ISSUE THREAD

**Issue by esnible** [istio/istio#31207]
Same problem with both `istioctl install` and `istioctl manifest generate`.

```
istioctl manifest generate --set meshConfig.defaultConfig.proxyMetadata.PROXY_XDS_VIA_AGENT=false
Error: failed to unmarshall mesh config: json: cannot unmarshal bool into Go value of type string

istioctl manifest generate --set meshConfig.defaultConfig.proxyMetadata.PROXY_XDS_VIA_AGENT="false"
Error: failed to unmarshall mesh config: json: cannot unmarshal bool into Go value of type string

istioctl manifest generate --set 'meshConfig.defaultConfig.proxyMetadata.PROXY_XDS_VIA_AGENT="false"'
`- "s390x": error converting YAML to JSON: yaml: line 151: did not find expected key`
```

Similar problems setting PROXY_XDS_VIA_AGENT to 0.

The error messages are super-confusing.  Also, "unmarshall" is misspelled!

Works if the value is put into an IstioOperator

``` yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    defaultConfig:
      proxyMetadata:
        PROXY_XDS_VIA_AGENT: "false"
```

**Comment by howardjohn** [comment]
unmarshal is a valid spelling and the error comes from go fwiw. But +1 to this, run into this often. Helm solves it with --set-string

**Comment by zhlsunshine** [comment]
Hi @esnible & @howardjohn ,  I think the error of `json: cannot unmarshal bool into Go value of type string` is validated correctly as you can see the definition of `ProxyMetadata` from [here](https://github.com/istio/api/blob/1b15945e40103efdf413ed1d7751f4e783044cee/mesh/v1alpha1/proxy.pb.go#L1109), `ProxyMetadata` is defined as a map[string]string. However, I think it should be okay if change the command into `istioctl manifest generate --set meshConfig.defaultConfig.proxyMetadata.PROXY_XDS_VIA_AGENT="false"`, and I will make it happen later.

**Comment by zhlsunshine** [comment]
More investigation, @esnible & @howardjohn, it's no business with istio program. If you use bash, please try to execute the commands like this:
`istioctl manifest generate --set meshConfig.defaultConfig.proxyMetadata.PROXY_XDS_VIA_AGENT=\"false\"` OR
`istioctl manifest generate --set meshConfig.defaultConfig.proxyMetadata.PROXY_XDS_VIA_AGENT='"false"'`
It's okay for me.

**Comment by zhlsunshine** [comment]
@esnible  Is that okay if I close this issue?  Or should we update doc for such case?

**Comment by daniel-pebble** [comment]
When I run the command as per the docs using ubuntu 20.04 and istioctl 1.11.0 I get a key error. 
_error converting YAML to JSON: yaml: line 141: did not find expected key_

`/home/pbs/istio-1.11.0/bin/istioctl manifest generate --set meshConfig.defaultConfig.proxyMetadata.PROXY_XDS_VIA_AGENT=\"false\"`

Looking at the generated config you can see it's not escaped correctly. 
![image](https://user-images.githubusercontent.com/47243318/129602313-14dd8f97-4670-493d-8e7f-26a4d8640871.png)

Some other examples

![image](https://user-images.githubusercontent.com/47243318/129602489-9b15c0c2-bba9-4db4-af16-dbfc818d07e5.png)

![image](https://user-images.githubusercontent.com/47243318/129602442-3cd0c3ee-ae0c-48d0-a178-ce2be810594e.png)

![image](https://user-images.githubusercontent.com/47243318/129602576-16f5aee7-0164-41db-b2c1-20a9d32b3fd9.png)

Any suggestions?

**Comment by zhlsunshine** [comment]
@daniel-pebble how about to use **‘**  instead of **\** ?

**Comment by BharatKJain** [comment]
Similar issue happened while i was generating manifest using:

 ```--set meshConfig.defaultConfig.proxyMetadata.EXIT_ON_ZERO_ACTIVE_CONNECTIONS=\"true\"```
 
 or 
 
 ```--set meshConfig.defaultConfig.proxyMetadata.EXIT_ON_ZERO_ACTIVE_CONNECTIONS='"true"'```
 
 Command used:
 
 `istioctl manifest generate --set revision=1-17-2 --set values.global.variant=distroless --set hub=xxx.dkr.ecr.ap-south-1.amazonaws.com/istio --set meshConfig.defaultConfig.holdApplicationUntilProxyStarts="true" --set meshConfig.defaultConfig.terminationDrainDuration="60s" --set meshConfig.defaultConfig.proxyMetadata.EXIT_ON_ZERO_ACTIVE_CONNECTIONS='"true"' --set meshConfig.outboundTrafficPolicy.mode="REGISTRY_ONLY" --set meshConfig.accessLogFormat="[%START_TIME%] \"%REQ(:METHOD)% %REQ(X-MASKED-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% \"%DYNAMIC_METADATA(istio.mixer:status)%\" \"%UPSTREAM_TRANSPORT_FAILURE_REASON%\" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(X-FORWARDED-FOR)%\" \"%REQ(USER-AGENT)%\" \"%REQ(X-REQUEST-ID)%\" \"%REQ(:AUTHORITY)%\" \"%UPSTREAM_HOST%\" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME%" --set meshConfig.accessLogFile="/dev/stdout" > istio.yaml`
 
 Error:
 ```Error: failed to order manifests: failed to parse YAML to a k8s object: error decoding object apiVersion: apps/v1```
 
 `      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          preferredDuringSchedulingIgnoredDuringExecution:: error converting YAML to JSON: yaml: line 139: did not find expected key`
 
 Can we re-open the issue and check this?
