### ISSUE TITLE
Namespace selector may not work in policies for primary-remote control plane configuration

### ISSUE THREAD

**Issue by ptembey-jnpr** [istio/istio#31211]
I have a primary-remote control plane configuration setup with steps followed from https://istio.io/latest/docs/setup/install/multicluster/primary-remote_multi-network/ 

A policy for a specific namespace in the remote cluster to deny all traffic in the namespace:
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: deny-all
  namespace: foo
spec:
  {}

cannot be applied to the primary 'config' cluster, because namespace 'foo' does not exist in the primary cluster.  I then had to use workload selectors to apply deny policies at a workload level in the namespace:

apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: deny-all
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: httpbin

Is this how authorization policies and possibly other configs are expected to be set in the primary-remote configuration?

**Comment by hzxuzhonghu** [comment]
AuthorizationPolicy like any other crds must be applied in primary cluster.  In primary-remote istio, istiod does not watch crds from the other clusters.
