### ISSUE TITLE
Unknown annotation: sidecar.istio.io/agentLogLevel

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#31248]
from `istioctl analyze`.
```
Warning [IST0108] (Pod nettools-5cfcd5f5d5-l5zdv.default) Unknown annotation: sidecar.istio.io/agentLogLevel
Warning [IST0108] (Pod nettools-77645d4c86-fmfgh.other) Unknown annotation: sidecar.istio.io/agentLogLevel

```
we need to add this to the known list of annotations

**Comment by kebe7jun** [comment]
It seems that `sidecar.istio.io/agentLogLevel` no longer supported by pilot-agent.

https://github.com/istio/istio/blob/7feb37b403eb043f6baa65f11ab29f9f561c7818/pilot/cmd/pilot-agent/main.go#L406-L428

It also not exists in [Resource Annotations](https://istio.io/latest/docs/reference/config/annotations/)

These results make sense?

**Comment by howardjohn** [comment]
https://github.com/istio/istio/blob/6107d132a8bb8793ccd7f6a42e2e1ca2778c4ebf/manifests/charts/istio-control/istio-discovery/files/injection-template.yaml#L192

**Comment by kebe7jun** [comment]
It should be replaced with `sidecar.istio.io/logLevel`?
We should remove this annotation from injection-template?

**Comment by howardjohn** [comment]
No, the template is correct. They serve 2 different purposes. We should add
it to the list of known annotations.

**Comment by kebe7jun** [comment]
Oh, it was my misunderstanding.
