### ISSUE TITLE
Request for Istiod to add support for sidecar reconciliation

### ISSUE THREAD

**Issue by tariq1890** [istio/istio#31246]
**Describe the feature request**

What is istio sidecar reconciliation?

1. Injecting sidecars to containers that are already deployed but don't have a sidecar injected into them yet. This happens when services are deployed into a cluster before istio is deployed or when services are deployed during istio control plane downtime.

2. Refreshing sidecars for containers when updating the istio version.

3. Uninjecting sidecars when changing Injection settings or Istio-injection namespace labels

**Describe alternatives you've considered**

1. While we can do this ourselves, it seems to be a sort of re-inventing the wheel as we end borrowing the entirety of the injection logic in `istiod`.

2. Importing the golang injection logic is not really a viable option as Istio comes with a huge transitive dependency overhead.

[ ] Docs
[X] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by mandarjog** [comment]
strawman: A controller (perhaps located inside istiod), that will restart pods to reconcile? 
A separate controller is better from a permissions standpoint, it does not have to actually inject anything, but relies on existing injection mechanisms.

**Comment by kyessenov** [comment]
2. and 3. would benefit from a more "static" sidecar template that fetches the "dynamic" settings from istiod. the settings could be mutated without re-injection.

**Comment by tariq1890** [comment]
> strawman: A controller (perhaps located inside istiod), that will restart pods to reconcile?

I am just suggesting the same thing

**Comment by tariq1890** [comment]
> 2. and 3. would benefit from a more "static" sidecar template that fetches the "dynamic" settings from istiod. the settings could be mutated without re-injection.

I feel this would be too intrusive. Basically provides the istio sidecar container to restart the whole pod. I prefer limiting the privileges to a central source such as `istiod` or similar

**Comment by howardjohn** [comment]
I think `istioctl analyze` does the detection part. Unfortunately, I think even when in in-cluster mode, it won't write this to the pod (since it doesn't have pod status write permission). If it had that you could do something like watch the status and act on it.

**Comment by ks864148379** [comment]
2.  Envoy support hot upgrading mechanism and we can use it to upgrade envoy and not restart sidecar container. Envoy will achieve lossless upgrade and do not affect pod network.

**Comment by ks864148379** [comment]
> 1. and 3. would benefit from a more "static" sidecar template that fetches the "dynamic" settings from istiod. the settings could be mutated without re-injection.

We can define two CRDs: SidecarVersion and SidecarVersionBinding. 
SidecarVersion means sidecar version status

**Comment by ks864148379** [comment]
> > strawman: A controller (perhaps located inside istiod), that will restart pods to reconcile?
> 
> Yup, I am suggesting the same thing. I should have clarified that in my initial post

Hi. 
Do you have any idea or implementation to solve this problem?

**Comment by holooooo** [comment]
Maybe can use the same solution as [OpenKruse](http://openkruise.io/en-us/docs/sidecarset.html#hot-upgrade) for update sidecar config. And hot update envoy
