### ISSUE TITLE
Consider adopting cluster alt_stat_name

### ISSUE THREAD

**Issue by bianpengyuan** [istio/istio#31244]
With envoyproxy/envoy@5551e0a, envoy now by default adds `upstream_cluster.name` to trace spans in addition to `upstream_cluster`. Unlike `upstream_cluster` which uses the name of cluster as value, `upstream_cluster.name` uses cluster's `alt_stat_name` and will fallback to cluster name if `alt_stat_name` is not set. We should consider adopting this to avoid duplicated information in trace span.

However, we'd need to check if `alt_stat_name` will also update envoy native stats. If so, this is probably a no-go.

**Comment by bianpengyuan** [comment]
cc @douglas-reid

**Comment by douglas-reid** [comment]
We should justify why providing telemetry-friendly names in envoy native stats (and access logs) would be a blocker. Using alternate cluster names may be something we should allow opt-in for as a starter.

**Comment by bianpengyuan** [comment]
Yeah.. this is actually valuable to get rid of depending on cluster name, which is an implementation detail. Although cluster name provides multiple dimensions of information (destination service, port, subset, and direction), we'd need to make sure switching to alt_stat_name won't reduce existing observability.

**Comment by howardjohn** [comment]
cc @ramaraochavali who I think uses this

**Comment by ramaraochavali** [comment]
Yes. For clusters we already make use of this via stat patterns in mesh config https://github.com/istio/api/blob/master/mesh/v1alpha1/config.proto#L320

**Comment by douglas-reid** [comment]
@howardjohn probably time to update the comments around that field, given recent changes: https://github.com/istio/api/blob/master/mesh/v1alpha1/config.proto#L306-L307

**Comment by bianpengyuan** [comment]
@ramaraochavali I am wondering what patterns do you use?

**Comment by ramaraochavali** [comment]
@bianpengyuan  We use the following patterns - these are chosen primarily to match stats generated by our legacy controlplane with Istio so that service owners do not see the difference.

 inboundClusterStatName: local_service.%SERVICE_PORT%
 outboundClusterStatName: '%SERVICE%.%SERVICE_PORT%'

**Comment by mandarjog** [comment]
`alt_stat_name` can provide a stable (er) name than the cluster names themselves which are not an API.
It is still fragile, but better.
