### ISSUE TITLE
Update Operator CRD to v1

### ISSUE THREAD

**Issue by howardjohn** [istio/istio#31252]
All other CRDs are auto generated. We need to manually do manifests/charts/base/crds/crd-operator.yaml.

One thing to be aware of is we have no openapi schema. I think k8s will get mad at us for this. We might need to set top level `object` and allow unknown fields? cc @jasonwzm for advice

**Comment by jasonwzm** [comment]
Sounds about right. But I imagine there will be lots of fields that require field level unknown tag.

**Comment by howardjohn** [comment]
Can we just set it on top level `spec` field and not define the schema at all? apparently its too big to fit

**Comment by jasonwzm** [comment]
We could. Then what is the point of auto generation?

**Comment by howardjohn** [comment]
Oh, I didn't mean we should auto generate. We just need to update it to v1 (from v1beta1) manually. We could autogen if we want I guess, but that wasn't my intent

**Comment by jasonwzm** [comment]
Ok. It should be easy with `spec` field allowing unknown fields.

**Comment by howardjohn** [comment]
https://github.com/istio/istio/pull/31577
