### ISSUE TITLE
 failed to istio canary upgrade from istio 1.6 to istio 1.8

### ISSUE THREAD

**Issue by xichengliudui** [istio/istio#31268]
**Bug description**

use `istio-1.8.1/bin/istioctl operator init --revision 1-8-1` failed to upgrade istio 1.6 to istio 1.8

**Affected product area (please put an X in all that apply)**

[x] Upgrade

**Expected behavior**
upgrade success

**Steps to reproduce the bug**
* istio-1.6.0/bin/istioctl operator init
* kubectl apply -f 1-6-0.yaml -n istio-system 
* istio-1.8.1/bin/istioctl operator init --revision 1-8-1
* kubectl apply -f 1-8-1.yaml -n istio-system 

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

* istio-1.6.0
* istio-1.8.1

**How was Istio installed?**
istio operator

**Environment where the bug was observed (cloud vendor, OS, etc)**
centos 7, kubernetes1.17.2

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.
```shell
[root@mesh-dev-10-20-1-180 bin]# kubectl get rs -n istio-operator
NAME                              DESIRED   CURRENT   READY   AGE
istio-operator-1-8-1-5dddff4796   1         1         1       4m33s
istio-operator-58f98cd489         1         1         1       6m10s
[root@mesh-dev-10-20-1-180 bin]# 
[root@mesh-dev-10-20-1-180 bin]# kubectl logs -f istio-operator-1-8-1-5dddff4796-gnlxx  -n istio-operator
2021-03-05T03:46:56.933466Z	info	ControlZ available at 127.0.0.1:9876
2021-03-05T03:46:56.933617Z	info	leader election cm: istio-operator-lock-1-8-1
2021-03-05T03:46:57.539370Z	info	Creating operator metrics exporter
2021-03-05T03:46:57.539456Z	info	Registering Components.
2021-03-05T03:46:57.539586Z	info	installer	Adding controller for IstioOperator.
2021-03-05T03:46:57.539700Z	info	installer	Controller added
2021-03-05T03:46:57.539734Z	info	Starting the Cmd.
2021-03-05T03:46:57.539986Z	info	klog	attempting to acquire leader lease  istio-operator/istio-operator-lock-1-8-1...[]
2021-03-05T03:46:57.549490Z	info	klog	successfully acquired lease istio-operator/istio-operator-lock-1-8-1[]
2021-03-05T03:46:59.765143Z	info	installer	Reconciling IstioOperator
2021-03-05T03:46:59.767765Z	info	installer	Ignoring IstioOperator CR iop-cluster180 with revision iop-1-6-0, since operator revision is 1-8-1.
2021-03-05T03:47:55.533161Z	info	installer	Reconciling IstioOperator
2021-03-05T03:47:55.537329Z	info	Adding finalizer istio-finalizer.install.istio.io to istio-system/iop-cluster180-1-8-1
2021-03-05T03:47:55.559990Z	info	installer	Could not add finalizer to iop-cluster180-1-8-1 due to conflict. Operation will be retried in next reconcile attempt.
```

**Comment by xichengliudui** [comment]
i upgraded three times and two of them were successful, one of which showed the condition in the log above
https://github.com/istio/istio/blob/871fc3da9bc8545f3792bbcc49e99fe6c872fc1d/operator/pkg/controller/istiocontrolplane/istiocontrolplane_controller.go#L292

**Comment by shamsher31** [comment]
> Upgrading across more than one minor version (e.g., `1.6.x` to `1.8.x`) in one step is not officially tested or recommended.

@xichengliudui So there might be some inconsistencies in the upgrade. can you please try upgrading from 1.6 > 1.7 > 1.8.

**Comment by tanjunchen** [comment]
@shamsher31
see https://github.com/istio/istio/blob/release-1.6/operator/deploy/operator.yaml#L43
It seems that istio-operator(1.6.x) does not support the env (revision) field.
```
root@tanjunchen:~/istio/istio-1.6.0/bin# ./istioctl operator init --help
The init subcommand installs the Istio operator controller in the cluster.

Usage:
  istioctl operator init [flags]

Flags:
  -d, --charts string              Specify a path to a directory of charts and profiles
                                   (e.g. ~/Downloads/istio-1.5.0/install/kubernetes/operator)
                                   or release tar URL (e.g. https://github.com/istio/istio/releases/download/1.5.1/istio-1.5.1-linux.tar.gz).
                                   
      --dry-run                    Console/log output only, make no changes.
  -f, --filename string            Path to file containing IstioOperator custom resource
  -h, --help                       help for init
      --hub string                 The hub for the operator controller image (default "docker.io/istio")
      --operatorNamespace string   The namespace the operator controller is installed into (default "istio-operator")
      --tag string                 The tag for the operator controller image (default "1.6.0")

Global Flags:
      --context string          The name of the kubeconfig context to use
  -i, --istioNamespace string   Istio system namespace (default "istio-system")
  -c, --kubeconfig string       Kubernetes configuration file
  -n, --namespace string        Config namespace
```

istio-operator will listen to all iop events (create, update, delete). When there are two operator pod at the same time, (istio-operator-1.6.0) will listen to all iops, and istio-operator-1.8.0 should only listen to deployment env(revison) in iop revision, so there will be occasional upgrade success and occasional upgrade failure. right? Whoever grabs this iop event will perform the **Reconciling IstioOperator** operation.

**Comment by ostromart** [comment]
@tanjunchen revision-based upgrades are not supported with operator 1.6. You must upgrade in-place to at least 1.7 for revision based upgrades to work with operator.

**Comment by ostromart** [comment]
Closing for now, please reopen if you feel this issue needs further investigation.
