### ISSUE TITLE
Istio-Operator does not remove istio-ingressgateway deployments/pods

### ISSUE THREAD

**Issue by yalctay93** [istio/istio#31274]
We are using Istio-Operator in the version 1.9.0 and experience the issue that when kind ```istio-operator``` is deleted, the associated pods/services/deployments (istio-ingressgateway) etc. are not deleted and remain in the cluster. This leads to the problem that when we re-deploy the kind ```istio-operator``` we get new resources and the cluster is being trashed with old deployments and pods that are no longer used. We always have to manually delete them.

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
I expect that old resources such as deployments or pods are deleted by the Istio-Operator once we delete the associated kind ```istio-operator```

**Steps to reproduce the bug**

**Version** 
helm version : 3.4.0
istioctl version: 1.9.0
kubectl version: 1.19.3

**How was Istio installed?**
Istio-Operator was installed by helm

values.yaml of Istio-Operator deployment:

```yaml
hub: reg-dhc.app.corpintra.net/i3-mirror/docker.io_istio_operator
tag: 1.9.0

# ImagePullSecrets for operator ServiceAccount, list of secrets in the same namespace
# used to pull operator image. Must be set for any cluster configured with private docker registry.
imagePullSecrets: []

operatorNamespace: istio-operator

# Used to replace istioNamespace to support operator watch multiple namespaces.
watchedNamespaces: istio-system
waitForResourcesTimeout: 300s

# Used for helm2 to add the CRDs to templates.
enableCRDTemplates: false

# revision for the operator resources
revision: ""

# Operator resource defaults
operator:
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi
```
kind: istio-operator was installed by ```istioctl dump profile default > default.yaml``` and then ```kubectl apply -f default.yaml```

Log Output of Istio-Operator when deleting kind ```istio-operator```

```
2021-03-05T10:10:46.510564Z     info    klog    extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
2021-03-05T10:11:10.535048Z     info    installer       Reconciling IstioOperator
2021-03-05T10:11:10.537685Z     info    installer       Deleting IstioOperator emea-int-mg0003
2021-03-05T10:11:10.630525Z     info    installer       API server conflict during finalizer removal, retrying.
2021-03-05T10:11:10.685405Z     info    installer       Reconciling IstioOperator
2021-03-05T10:11:10.687336Z     info    installer       Deleting IstioOperator emea-int-mg0003
2021-03-05T10:11:10.700261Z     info    installer       Reconciling IstioOperator
2021-03-05T10:11:10.705387Z     info    installer       Reconciling IstioOperator
2021-03-05T10:12:17.866652Z     info    klog    admissionregistration.k8s.io/v1beta1 MutatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 MutatingWebhookConfiguration
2021-03-05T10:14:06.359607Z     info    installer       Reconciling IstioOperator
2021-03-05T10:14:06.361646Z     info    installer       Deleting IstioOperator emea-test-mg0001
2021-03-05T10:14:06.468724Z     info    installer       API server conflict during finalizer removal, retrying.
2021-03-05T10:14:06.517141Z     info    installer       Reconciling IstioOperator
2021-03-05T10:14:06.518781Z     info    installer       Deleting IstioOperator emea-test-mg0001
2021-03-05T10:14:06.534847Z     info    installer       Reconciling IstioOperator
2021-03-05T10:14:06.539939Z     info    installer       Reconciling IstioOperator
2021-03-05T10:14:13.796517Z     info    klog    admissionregistration.k8s.io/v1beta1 ValidatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 ValidatingWebhookConfiguration
2021-03-05T10:14:39.459955Z     info    klog    apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
2021-03-05T10:16:15.514765Z     info    klog    extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
2021-03-05T10:17:21.353075Z     info    klog    rbac.authorization.k8s.io/v1beta1 Role is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 Role
2021-03-05T10:17:50.584887Z     info    klog    rbac.authorization.k8s.io/v1beta1 RoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 RoleBinding
2021-03-05T10:20:06.596803Z     info    installer       Watching a change for istio resource: istio-system/emea-int-mg0003
2021-03-05T10:20:06.596889Z     info    installer       Reconciling IstioOperator
2021-03-05T10:20:06.640992Z     info    installer       Watching a change for istio resource: istio-system/emea-test-mg0001
2021-03-05T10:20:06.641056Z     info    installer       Reconciling IstioOperator
2021-03-05T10:20:40.871340Z     info    klog    admissionregistration.k8s.io/v1beta1 MutatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 MutatingWebhookConfiguration
2021-03-05T10:22:25.463242Z     info    klog    apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
2021-03-05T10:23:21.800690Z     info    klog    admissionregistration.k8s.io/v1beta1 ValidatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 ValidatingWebhookConfiguration
2021-03-05T10:25:13.520851Z     info    klog    extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
2021-03-05T10:25:20.589127Z     info    klog    rbac.authorization.k8s.io/v1beta1 RoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 RoleBinding
2021-03-05T10:25:36.357792Z     info    klog    rbac.authorization.k8s.io/v1beta1 Role is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 Role
2021-03-05T10:26:52.875477Z     info    klog    admissionregistration.k8s.io/v1beta1 MutatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 MutatingWebhookConfiguration
```

**Comment by morvencao** [comment]
Was the `istio-operator` CR actually deleted from cluster when you found the associated pods/services/deployments (istio-ingressgateway) remain in the cluster?

**Comment by yalctay93** [comment]
> Was the `istio-operator` CR actually deleted from cluster when you found the associated pods/services/deployments (istio-ingressgateway) remain in the cluster?

Hello, thank you for the reply. Yes, the ```istio-operator``` CR was removed from the Cluster, even the istiod control-plane reconciled afterwards however, the resources pods/services/deployments etc. remained. I've waited for a few minutes but the Istio-Operator Deployment never removes them. Could it be that the revision might cause a problem here? The Istio-operator is deployed with no revision as you can see in the values.yaml above but the ```istio-operator``` CR is deployed with revision 1-9-0. Then again, the istiod control-plane did reconcile so I guess that's not the issue here.

**Comment by morvencao** [comment]
If you specified `revision` in IOP spec, but empty revision in operator deployment, then the operator will skip reconcile the IOP, you should see such log in operator logs:
```
Ignoring IstioOperator CR xxx with revision xxx, since operator revision is yyyy.
```

We added this check for canary upgrade, you can always deploy multiple operators in the same cluster with different revisions.

**Comment by yalctay93** [comment]
Sure, I will try it again and specify the revision in the operator deployment. I haven't seen that log but I hope that it'll work afterwards.

**Comment by bnutt** [comment]
I am seeing this issue occur as well. During deletion reconciliation, if `iop.Spec.Revision` is set and the operator has a `REVISION` environment variable set, the operator will try to prune resources in namespace defined by `iop.Spec.Namespace` https://github.com/istio/istio/blob/9686754643d0939c1f4dd0ee20443c51183f3589/operator/pkg/helmreconciler/reconciler.go#L224

The operator will not progress in reconciliation to clean up resources if there are still proxies connected to the mesh, checked on line https://github.com/istio/istio/blob/1.7.3/operator/pkg/helmreconciler/prune.go#L112. This will also pick up the istio gateway pods that were provisioned by the istio operator. The list of proxies are generated by https://github.com/istio/istio/blob/9686754643d0939c1f4dd0ee20443c51183f3589/pkg/proxy/proxyinfo.go#L34. In this current setup, it would seem that you would have to delete the gateways first before the operator can clean up all of the resources created. 

Example list of proxies returned by the GetProxyInfo method:

```
"status":{"message":"there are proxies still pointing to the pruned control plane: istio-ingressgateway-public-5mbhw.istio-blue istio-ingressgateway-public-5596w.istio-blue istio-ingressgateway-private-d7c7x.istio-blue istio-ingressgateway-private-bjphr.istio-blue istio-ingressgateway-public-ltj2c.istio-blue istio-ingressgateway-private-br6nl.istio-blue.","status":"ACTION_REQUIRED"}}
```

A possible solution seems to be to exclude the gateways from the list of generated PID's so that only data plane proxies are part of the list.

**Comment by yalctay93** [comment]
> I am seeing this issue occur as well. During deletion reconciliation, if `iop.Spec.Revision` is set and the operator has a `REVISION` environment variable set, the operator will try to prune resources in namespace defined by `iop.Spec.Namespace`
> 
> https://github.com/istio/istio/blob/9686754643d0939c1f4dd0ee20443c51183f3589/operator/pkg/helmreconciler/reconciler.go#L224
> 
> The operator will not progress in reconciliation to clean up resources if there are still proxies connected to the mesh, checked on line https://github.com/istio/istio/blob/1.7.3/operator/pkg/helmreconciler/prune.go#L112. This will also pick up the istio gateway pods that were provisioned by the istio operator. The list of proxies are generated by
> 
> https://github.com/istio/istio/blob/9686754643d0939c1f4dd0ee20443c51183f3589/pkg/proxy/proxyinfo.go#L34
> 
> . In this current setup, it would seem that you would have to delete the gateways first before the operator can clean up all of the resources created.
> Example list of proxies returned by the GetProxyInfo method:
> 
> ```
> "status":{"message":"there are proxies still pointing to the pruned control plane: istio-ingressgateway-public-5mbhw.istio-blue istio-ingressgateway-public-5596w.istio-blue istio-ingressgateway-private-d7c7x.istio-blue istio-ingressgateway-private-bjphr.istio-blue istio-ingressgateway-public-ltj2c.istio-blue istio-ingressgateway-private-br6nl.istio-blue.","status":"ACTION_REQUIRED"}}
> ```
> 
> A possible solution seems to be to exclude the gateways from the list of generated PID's so that only data plane proxies are part of the list.

Hello, what exactly do you mean by "delete the gateways first before the operator can clean up all of the resources" ? Do you mean the CR ```gateway``` or are we talking about the ```iop``` ?

**Comment by bnutt** [comment]
> > . In this current setup, it would seem that you would have to delete the gateways first before the operator can clean up all of the resources created.
> 
> Hello, what exactly do you mean by "delete the gateways first before the operator can clean up all of the resources" ? Do you mean the CR `gateway` or are we talking about the `iop` ?

Hi @yalctay93 , I mean that as currently defined, you have to remove the gateway from the iop definition so that the gateway pods are removed. At this point, the operator will no longer report proxies and be able to tear down the rest of the resources provisioned by the operator when the iop resource is deleted.

**Comment by yalctay93** [comment]
> > > . In this current setup, it would seem that you would have to delete the gateways first before the operator can clean up all of the resources created.
> > 
> > 
> > Hello, what exactly do you mean by "delete the gateways first before the operator can clean up all of the resources" ? Do you mean the CR `gateway` or are we talking about the `iop` ?
> 
> Hi @yalctay93 , I mean that as currently defined, you have to remove the gateway from the iop definition so that the gateway pods are removed. At this point, the operator will no longer report proxies and be able to tear down the rest of the resources provisioned by the operator when the iop resource is deleted.

Excuse me, if I have to ask again - but this means that I have to manually first delete the ingressgateway pods (deployment) before I delete the ```iop``` correct? That would lead to a clean deletion of all remaining resources?

Is this really the expected behaviour? It seems a bit weird to me.

**Comment by bnutt** [comment]
> > > > . In this current setup, it would seem that you would have to delete the gateways first before the operator can clean up all of the resources created.
> > > 
> > > 
> > > Hello, what exactly do you mean by "delete the gateways first before the operator can clean up all of the resources" ? Do you mean the CR `gateway` or are we talking about the `iop` ?
> > 
> > 
> > Hi @yalctay93 , I mean that as currently defined, you have to remove the gateway from the iop definition so that the gateway pods are removed. At this point, the operator will no longer report proxies and be able to tear down the rest of the resources provisioned by the operator when the iop resource is deleted.
> 
> Excuse me, if I have to ask again - but this means that I have to manually first delete the ingressgateway pods (deployment) before I delete the `iop` correct? That would lead to a clean deletion of all remaining resources? Or what exactly do you mean by "remove the gateway from the iop definition"
> 
> Is this really the expected behaviour? It seems a bit weird to me.

That is correct @yalctay93 , that is the behavior I experienced trying to uninstall the operator on istio 1.7. The ingress gateway deployment to be deleted first for the operator to clean all of the remaining resources. I agree that this behavior is weird and that we should not need one more additional step to tear down the control plane. Once the  `iop` is deleted, I would expect that all resources provisioned by it are removed.

**Comment by yalctay93** [comment]
> > > > > . In this current setup, it would seem that you would have to delete the gateways first before the operator can clean up all of the resources created.
> > > > 
> > > > 
> > > > Hello, what exactly do you mean by "delete the gateways first before the operator can clean up all of the resources" ? Do you mean the CR `gateway` or are we talking about the `iop` ?
> > > 
> > > 
> > > Hi @yalctay93 , I mean that as currently defined, you have to remove the gateway from the iop definition so that the gateway pods are removed. At this point, the operator will no longer report proxies and be able to tear down the rest of the resources provisioned by the operator when the iop resource is deleted.
> > 
> > 
> > Excuse me, if I have to ask again - but this means that I have to manually first delete the ingressgateway pods (deployment) before I delete the `iop` correct? That would lead to a clean deletion of all remaining resources? Or what exactly do you mean by "remove the gateway from the iop definition"
> > Is this really the expected behaviour? It seems a bit weird to me.
> 
> That is correct @yalctay93 , that is the behavior I experienced trying to uninstall the operator on istio 1.7. The ingress gateway deployment to be deleted first for the operator to clean all of the remaining resources. I agree that this behavior is weird and that we should not need one more additional step to tear down the control plane. Once the `iop` is deleted, I would expect that all resources provisioned by it are removed.

Interesting, for me when I first delete the ingressgateway deployment, it is automatically redeployed. So I cannot delete them before deleting the ```iop``` .

**Comment by bnutt** [comment]
> > That is correct @yalctay93 , that is the behavior I experienced trying to uninstall the operator on istio 1.7. The ingress gateway deployment to be deleted first for the operator to clean all of the remaining resources. I agree that this behavior is weird and that we should not need one more additional step to tear down the control plane. Once the `iop` is deleted, I would expect that all resources provisioned by it are removed.
> 
> Interesting, for me when I first delete the ingressgateway deployment, it is automatically redeployed. So I cannot delete them before deleting the `iop` .

Correct, sorry for not being clear. In order for to remove the gateway currently, you need to remove it from the iop spec, then you can delete the iop resource.

**Comment by yalctay93** [comment]
> Correct, sorry for not being clear. In order for to remove the gateway currently, you need to remove it from the iop spec, then you can delete the iop resource.

Alright, thank you. As this is a rather unconventional way of removing resources from a k8s cluster it is not very satisfying to me.
I'd expect that when I remove a CR such as the ```iop``` that the istio-operator goes ahead and removes all of its associated resources automatically. Atleast that's how I usually develop my k8s operators. The cleanup of resources, which were created directly because of that CR ```iop``` should be removed along with it. Is there any good reason why the istio-operator behaves like this, in this particular scenario? I might be overlooking something.

**Comment by ostromart** [comment]
@yalctay93 @bnutt the deletion behavior with gateways changed (hopefully for the better) post 1.7. With 1.7 and earlier, there were problems with identifying gateway ownership, because gateways were shared between revisions and upgraded in place. This meant that gateways were never pruned, because they may still belong to an existing revision.
That has since changed, and gateway ownership resolves correctly with multiple revisions in the cluster. 
Using 1.10 for example, you can try the following:
```
istio-1.10/bin/istioctl operator init -f ~/temp/iop.yaml --hub=gcr.io/istio-testing --tag=latest
```
where iop.yaml is something simple like
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: test
  namespace: istio-system
spec:
```
This installs istiod and istio-ingressgateway (default profile). Now, if you delete the test IstioOperator CR, both istiod and the gateway will be removed. 
For more information on how this all works with revisions (including gateways), see https://istio.io/latest/docs/setup/upgrade/gateways/.

**Comment by ostromart** [comment]
Closing for now, please reopen if you feel this needs more investigation.
