### ISSUE TITLE
Allow extraStatTags to be configured mesh wide and on pod level at the same time

### ISSUE THREAD

**Issue by wiegandf** [istio/istio#31270]
**Bug description**
When specifying extraStatTags on both the pod and mesh-wide, pods don't start anymore with this log in the istio sidecar:
```
2021-03-04T14:33:06.483924Z	critical	envoy main	error initializing configuration 'etc/istio/proxy/envoy-rev0.json': Tag name 'custom_dimension' specified twice.
```

**Affected product area**
[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[X] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**
Pods should still start and config should be first taken from default proxy config - when specified on pod level, use this value. (or log a warning that mesh wide is already set and mesh wide config will be used).

**Steps to reproduce the bug**
1. Have a cluster with some custom metric dimensions as outlined in step 1 of https://istio.io/latest/docs/tasks/observability/metrics/customize-metrics/. 
2. Add the annotation to a pod so that the new dimension is added correctly as outlined in step 2 of https://istio.io/latest/docs/tasks/observability/metrics/customize-metrics/
3. Check that the custom metric is working
4. Enable the mesh-wide extraStatTags (also described in step 2 of above link)

**Version** 
istioctl
```
client version: 1.8.3
control plane version: 1.8.3
data plane version: 1.8.3 (11 proxies)
```
kubectl
```
Server Version: v1.18.14
```

**How was Istio installed?**
IstioOperator

**Comment by howardjohn** [comment]
cc @kyessenov
