### ISSUE TITLE
Istio-proxy sidecars loose touch with istiod and don't get updates on endpoints

### ISSUE THREAD

**Issue by astrikos** [istio/istio#31277]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
So we have a behavior that we see repeatedly in our cluster. The istio-proxy of some pods is loosing connectivity with the istiod and thus results to stale endpoints since the endpoints of different services have changed after re deployments etc.
Hitting the endpoint from inside the pod it gives us `context deadline exceeded` error. Seeing the output of `istioctl pc endpoints <pod>` it proves that the endpoint points to another IP of the actual target pod. Also seeing the output of `istioctl ps` the specific pod is not in the list.
Restarting pod solves the issue.
After enabling more verbose logging on istiod side and restarting things after a while a pod goes in this bad state and we can see in the istiod logs the following
```
2021-03-04 20:12:17 | 2021-03-04T19:12:17.504605Z	info	ads	Client closed connection sidecar~100.103.48.1~fuel-qagr-7c46c97458-rqzd8.mop~mop.svc.cluster.local-23
2021-03-04 20:12:17 | 2021-03-04T19:12:17.502646Z	info	ads	ADS: "100.103.48.1:46752" sidecar~100.103.48.1~fuel-qagr-7c46c97458-rqzd8.mop~mop.svc.cluster.local-23 terminated rpc error: code = Canceled desc = context canceled
2021-03-04 20:12:17 | 2021-03-04T19:12:17.502622Z	info	ads	Client closed connection sidecar~100.103.48.1~fuel-qagr-7c46c97458-rqzd8.mop~mop.svc.cluster.local-23
2021-03-04 18:17:25 | 2021-03-04T17:17:25.902706Z	warn	ads	type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment: Send failure sidecar~100.103.48.1~fuel-qagr-7c46c97458-rqzd8.mop~mop.svc.cluster.local-23: rpc error: code = DeadlineExceeded desc = timeout sending Show context
2021-03-04 18:17:25 | 2021-03-04T17:17:25.902565Z	info	ads	Timeout writing sidecar~100.103.48.1~fuel-qagr-7c46c97458-rqzd8.mop~mop.svc.cluster.local-23
2021-03-04 18:17:20 | 2021-03-04T17:17:20.902467Z	info	ads	EDS: PUSH for node:fuel-qagr-7c46c97458-rqzd8.mop resources:1329 empty:0 cached:1328/1329
2021-03-04 18:17:20 | 2021-03-04T17:17:20.899122Z	info	ads	CDS: PUSH for node:fuel-qagr-7c46c97458-rqzd8.mop resources:1577
```
And nothing after that although specific pod is still up and running.

Now going inside the pod itself using tcpdump we can see packets coming and going to istiod.istio-system service on port 15012.
One detail is that the pod's port is not `46752` that we see in the above logs but something else.

Do you have any clue on how to debug this or what might be wrong? Is there any signs that we can see somewhere to understand further what's going on.

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**
Not being able to reproduce this, it happens after some time
**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
istioctl output
```
client version: 1.8.2
control plane version: 1.8.3
data plane version: 1.8.3 (548 proxies)
```
kubectl output
```
Client Version: v1.18.10
Server Version: v1.19.7
```
**How was Istio installed?**
istioctl
**Environment where the bug was observed (cloud vendor, OS, etc)**
ubuntu
Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
> 46752

This is the local ephemeral port

When we hit timeout writing, we send an error back to the proxy, which is supposed to cause it to disconnect and reconnect. Given we timed out on the write, it seems like the pod may be in some bad state where its not receiving this error and not attempting to reconnect?

> Now going inside the pod itself using tcpdump we can see packets coming and going to istiod.istio-system service on port 15012.

Is this just some keepalive packets or something, or giant XDS data (like megabytes of data)?

**Comment by astrikos** [comment]
Hey @howardjohn, thanks for your reply.
>Given we timed out on the write, it seems like the pod may be in some bad state where its not receiving this error and not attempting to reconnect?

is there a way to force re connection from the proxy side? can you think of any way or sings to debug this further to see why it gets to this bad state? 

>Is this just some keepalive packets or something, or giant XDS data (like megabytes of data)?

these are definitely small packets (either `[P.]` or just [.]` in tcpdump, so no new connections are actually tried). Using `-A` as output in tcpdump doesn't really help to see what's in there since it's probably grpc traffic. But it's not looking giant, more on the side of keepalive, but from both sides. I am wondering if it will be valuable to see traffic from the istiod side, although it's a bit more difficult since inside the istiod pods I don't have root. But if you think we could find something valuable I could definitely find a way to see traffic in there.

**Comment by astrikos** [comment]
>Is this just some keepalive packets or something, or giant XDS data (like megabytes of data)?

In case it helps I am adding couple packets here, which are mainly what we see. A lot 0 length packets (I guess keepalives) and the rest don't exceed 39 bytes.
```
07:12:10.927238 IP istiod.istio-system.svc.cluster.local.15012 > mypod.53774: Flags [P.], seq 1877:1916, ack 487, win 131, options [nop,nop,TS val 2391217460 ecr 2683671276], length 39
E..[..@.@.,.dB.6dd.
:...8............\.....
...4........".1...[...../.1..@G.....9/...,.hBk.
07:12:10.927257 IP mypod.53774 > istiod.istio-system.svc.cluster.local.15012: Flags [.], ack 1916, win 136, options [nop,nop,TS val 2683686246 ecr 2391217460], length 0
E..4(L@.@...dd.
dB.6..:.....8.......d......
...f...4
```
