### ISSUE TITLE
Can we move out of Docker Hub to another Docker registry?

### ISSUE THREAD

**Issue by mrnonz** [istio/istio#31296]
**Describe the feature request**
From Docker Hub announcement "Anonymous and Free Docker Hub users are limited to 100 and 200 container image pull requests per six hours.", So when we have a large cluster (~500pods) it can easy reach limitation of free user. 

**Describe alternatives you've considered**
Can we move to another free or paid plan? (GitHub Packages, GCR, ECR or Quay.io)

**Affected product area**

[x] Docs

**Comment by bianpengyuan** [comment]
See https://istio.io/latest/blog/2020/docker-rate-limit/. Thanks!

**Comment by mrnonz** [comment]
> See https://istio.io/latest/blog/2020/docker-rate-limit/. Thanks!

@bianpengyuan Thanks for your document, but I am curious why we not change default setting to gcr instead?

**Comment by bianpengyuan** [comment]
I did not follow the decision process, but I think one of the reasons is that there could be some env where registry are explicitly whitelisted, switching to gcr could break those istio installation.
