### ISSUE TITLE
Need Help: Book-info product page not coming up in browser 

### ISSUE THREAD

**Issue by patelrutva** [istio/istio#31294]
I want to deploy an application using istio, I am following below link (NOTE: I have installed minikube in my local macOS):
`https://istio.io/latest/docs/setup/getting-started/#download`

I have run all the commands step by as mentioned in the guide, but when I reached on verify external access I got some warning:

```
$ istioctl analyze
Warning [IST0103] (Pod details-v1-79f774bdb9-q7x67.default) The pod is missing the Istio proxy. This can often be resolved by restarting or redeploying the workload.
Warning [IST0103] (Pod productpage-v1-6b746f74dc-r59zz.default) The pod is missing the Istio proxy. This can often be resolved by restarting or redeploying the workload.
Warning [IST0103] (Pod ratings-v1-b6994bb9-wgm2f.default) The pod is missing the Istio proxy. This can often be resolved by restarting or redeploying the workload.
Warning [IST0103] (Pod reviews-v1-545db77b95-mrt24.default) The pod is missing the Istio proxy. This can often be resolved by restarting or redeploying the workload.
Warning [IST0103] (Pod reviews-v2-7bf8c9648f-cx8pq.default) The pod is missing the Istio proxy. This can often be resolved by restarting or redeploying the workload.
Warning [IST0103] (Pod reviews-v3-84779c7bbc-dkxz8.default) The pod is missing the Istio proxy. This can often be resolved by restarting or redeploying the workload.

```

I successfully get the gateway_url using below command:
```
$ echo "http://$GATEWAY_URL/productpage"
http://192.168.49.2:32263/productpage
```

But when I paste the url in the browser it showing me ERR_CONNECTION_TIMED_OUT.

![image](https://user-images.githubusercontent.com/41102770/110180223-602dff80-7dd7-11eb-8370-9d1b4802a1ae.png)

Can somebody help?

**Comment by shamsher31** [comment]
can you try re-deploying the bookinfo sample?
```
$ kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml
```

and run `istioctl analyze`.

**Comment by howardjohn** [comment]
This is expected as the pods don't have the sidecar. Please follow the recommended steps to redeploy. Thanks!
