### ISSUE TITLE
Consider converging istio-peer-exchange and istio alpn

### ISSUE THREAD

**Issue by bianpengyuan** [istio/istio#31309]
For tcp mx, `istio-peer-exchange` ALPN was initially used instead of `istio` ALPN because during upgrading there will be mix of proxy versions with and without capability of tcp mx. Now that concern is long gone, we could remove `istio-peer-exchange` and just rely on `istio` for TCP exchange.

cc @mandarjog @kyessenov

**Comment by mandarjog** [comment]
Does alpn: istio guarantee the presence of mx though?

**Comment by bianpengyuan** [comment]
TCP MX filter is injected at
1) every filter chain, including HTTP ones by injecting in front of HCM
2) every cluster upstream filter chain.

`istio` ALPN is added
1) At downstream, istio mutual cluster tls context.
2) At upstream, all non-passthrough filter chain matching, including HTTP ones.

So presence of TCP MX filter definitely covers all cases where istio ALPN presents. In fact I think we need to shrink presence of both and remove them from HTTP filter chains.

On the other hand, we need to guarantee that `istio` ALPN is not missed anywhere that TCP MX should happen. Looks like the only case where `istio-peer-exchange` presents but not `istio` is network filter chains downstream tls context, where it can just be replaced by `istio`.
