### ISSUE TITLE
istio uninstall  cluster fail after upgrade with istio operator from 1.8.1 to 1.8.3 : API server conflict during finalizer removal, retrying.

### ISSUE THREAD

**Issue by tanjunchen** [istio/istio#31306]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

After the upgrade, delete the new iop (istio cluster) and find that iop has been deleted, but resources such as istiod, ingressgaty, cm, etc. have not been deleted. Check the log of istio-operator to find the error log.

```
2021-03-08T02:58:26.730446Z	info	installer	Ignoring IstioOperator CR iop-1-8-1 with revision iop-1-8-1, since operator revision is iop-1-8-3.
2021-03-08T03:02:01.531672Z	info	installer	Reconciling IstioOperator
2021-03-08T03:02:32.615291Z	info	installer	Reconciling IstioOperator
2021-03-08T03:02:32.615664Z	info	installer	Deleting IstioOperator iop-1-8-3
2021-03-08T03:02:32.634620Z	info	installer	API server conflict during finalizer removal, retrying.
2021-03-08T03:02:32.638782Z	info	installer	Reconciling IstioOperator
```
**API server conflict during finalizer removal, retrying.**

**Affected product area (please put an X in all that apply)**

[X] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[X] Upgrade

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Expected behavior**

Delete the cluster correctly

**Steps to reproduce the bug**

refer to https://github.com/istio/istio/issues/31304

kubectl delete iop iop-1-8-3  -n istio-system 

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**

istio-operator 

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by ostromart** [comment]
That's a normal transient error coming from k8s API server. Did the uninstall ultimately complete or end up in a bad state? Need more information about what happened later, this error is not the root cause.

**Comment by tanjunchen** [comment]
@ostromart   the iop can be deleted,but it is the bad state due to the error (API server conflict during finalizer removal, retrying) in istio operator.so the resource pod、svc、cm etc. is not deleted. you can try to do it.

**Comment by richardwxn** [comment]
The controller would do a retry(only once) when there is a transient finalizer error, if there is still error persists, then it would log another removing finalizer error, which did not show up in the logs above, instead another reconcile request took over, which looks weird.

I need to reproduce this issue first and debug

**Comment by mitchellmaler** [comment]
Just ran into this issue when using operator 1.9.3.

I created 1.8.5 and 1.9.3 revisions and deleted 1.9.2 and 1.8.4 revisions (iop). The controller reconciled and did delete the 1.9.2 objects but left the 1.8.4 objects.

```
$ kubectl get iop
NAME          REVISION   STATUS    AGE
istio-1-8-5   1-8-5      HEALTHY   18m
istio-1-9-3   1-9-3      HEALTHY   18m
```

```
$ kubectl get deployment,configmap,service,secret,horizontalpodautoscaler,poddisruptionbudget,mutatingwebhookconfiguration | grep "1-9-2\|NAME"
NAME                                   READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/istiod-1-9-2           2/2     2            2           18m

NAME                                             DATA   AGE
configmap/istio-1-9-2                            2      18m
configmap/istio-sidecar-injector-1-9-2           2      18m

NAME                           TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                                                      AGE
service/istiod-1-9-2           ClusterIP   10.98.23.231     <none>        15010/TCP,15012/TCP,443/TCP,15014/TCP                                        18m

NAME                                                       REFERENCE                         TARGETS          MINPODS   MAXPODS   REPLICAS   AGE
horizontalpodautoscaler.autoscaling/istiod-1-9-2           Deployment/istiod-1-9-2           1%/80%           2         5         2          18m

NAME                                              MIN AVAILABLE   MAX UNAVAILABLE   ALLOWED DISRUPTIONS   AGE
poddisruptionbudget.policy/istiod-1-9-2           1               N/A               1                     18m

NAME                                                                                          WEBHOOKS   AGE
mutatingwebhookconfiguration.admissionregistration.k8s.io/istio-sidecar-injector-1-9-2        1          18m
```

```
istio-operator-78d6f97988-c8gjf istio-operator 2021-04-19T22:46:39.345650Z	info	  Removed MutatingWebhookConfiguration::istio-sidecar-injector-1-8-4.
istio-operator-78d6f97988-c8gjf istio-operator 2021-04-19T22:46:39.418504Z	info	installer	API server conflict during finalizer removal, retrying.
istio-operator-78d6f97988-c8gjf istio-operator 2021-04-19T22:46:39.488459Z	info	installer	Reconciling IstioOperator
istio-operator-78d6f97988-c8gjf istio-operator 2021-04-19T22:46:39.490878Z	info	installer	Deleting IstioOperator istio-1-9-2
istio-operator-78d6f97988-c8gjf istio-operator 2021-04-19T22:46:39.568433Z	info	installer	API server conflict during finalizer removal, retrying.
istio-operator-78d6f97988-c8gjf istio-operator 2021-04-19T22:46:39.611339Z	info	installer	Could not remove finalizer from istio-1-9-2 due to conflict. Operation will be retried in next reconcile attempt.
istio-operator-78d6f97988-c8gjf istio-operator 2021-04-19T22:46:39.611403Z	info	installer	Reconciling IstioOperator
istio-operator-78d6f97988-c8gjf istio-operator 2021-04-19T22:46:39.611451Z	info	installer	Reconciling IstioOperator
istio-operator-78d6f97988-c8gjf istio-operator 2021-04-19T22:46:39.614551Z	info	installer	Deleting IstioOperator istio-1-9-2
istio-operator-78d6f97988-c8gjf istio-operator 2021-04-19T22:46:39.765084Z	info	installer	API server conflict during finalizer removal, retrying.
istio-operator-78d6f97988-c8gjf istio-operator 2021-04-19T22:46:39.856722Z	info	installer	Reconciling IstioOperator
```

Please let me know if I can provide anything to help track this down.
