### ISSUE TITLE
Unable to run exec commands on pods that have istio sidecar

### ISSUE THREAD

**Issue by fvogel-bc** [istio/istio#31308]
Istio is installed with istio injection turned on.  I have one application (App-A) running in one pod and another application (App-B) running in a second pod.  App-A uses the K8s api to issue an exec command on the pod running App-B.   The call fails with a 400 Bad Request.  If I restart the pod running App-B and use the annotation ('annotations': {'sidecar.istio.io/inject': "false"}) then everything works.  Once the sidecar is put back on this pod it fails.  

I have set the istio_proxy logs on both containers to debug, but get nothing significant on these logs.  Mostly something that just looks like a periodic health check.  Both pods A and B are in the same cluster and in the same namespace.  

Here is the error:
{"asctime": "2021-03-03 22:18:29,384", "funcName": "process_command", "levelname": "INFO", "pathname": "agent/command_handler.py", "message": "Thread: Parallel handler #2. Finished handle command: execContainerCommand"}
Exception in thread Thread-272:
Traceback (most recent call last):
  File "site-packages/kubernetes/stream/ws_client.py", line 296, in websocket_call
  File "site-packages/kubernetes/stream/ws_client.py", line 94, in __init__
  File "site-packages/websocket/_core.py", line 226, in connect
  File "site-packages/websocket/_handshake.py", line 80, in handshake
  File "site-packages/websocket/_handshake.py", line 165, in _get_resp_headers
websocket._exceptions.WebSocketBadStatusException: Handshake status 400 Bad Request
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "agent/container_management/kubernetes/kubernetes_manager.py", line 595, in _t_exec_in_container
  File "site-packages/kubernetes/stream/stream.py", line 35, in stream
  File "site-packages/kubernetes/client/api/core_v1_api.py", line 841, in connect_get_namespaced_pod_exec
  File "site-packages/kubernetes/client/api/core_v1_api.py", line 941, in connect_get_namespaced_pod_exec_with_http_info
  File "site-packages/kubernetes/client/api_client.py", line 345, in call_api
  File "site-packages/kubernetes/client/api_client.py", line 176, in __call_api
  File "site-packages/kubernetes/stream/stream.py", line 30, in _intercept_request_call
  File "site-packages/kubernetes/stream/ws_client.py", line 302, in websocket_call
kubernetes.client.rest.ApiException: (0)
Reason: Handshake status 400 Bad Request

**Affected product area (please put an X in all that apply)**

[ ] Docs
[ ] Installation
[ x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ x] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
I expect that K8s api commands will work when using istio

**Steps to reproduce the bug**
I have explained in the description the circumstance that causes the bug; however there is another way that this is easy to reproduce.  This github link provides a python script that will create a pod and then run an exec command on it. (https://github.com/kubernetes-client/python/blob/master/examples/pod_exec.py)  Even though this is not on two pods, it has the exact same problem.  

It is possible that there is some configuration issue instead; however, i am using the istio demo setup and have istio injection turned on, so nothing fancy in the way of configuration.

**Version** (
`istioctl version --remote` 
client version: 1.9.0
control plane version: 1.9.0
data plane version: 1.9.0 (10 proxies)

`kubectl version --short` 
Client Version: v1.19.3
Server Version: v1.19.3

**How was Istio installed?**
curl -L https://istio.io/downloadIstio | sh -`cd istio-1.9.0
./istioctl install --set profile=demo -y
kubectl label namespace default istio-injection=enabled

**Environment where the bug was observed (cloud vendor, OS, etc)**
OSX 10.15.6
Docker-for-desktop 3.1.0
kubernetes 1.19.3

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
Maybe I am doing something dumb but I cannot even get pod_exec.py to work without istio...

**Comment by fvogel-bc** [comment]
@howardjohn 
I apologize for going so long without replying, crazy week.  We were able to figure the issue out a couple hours after I posted this.  The problem was that when the sidecar was added the container name had a "ctl-" added to it.  As a result our call no longer had the right container name.  This explains why the scenario worked without istio being included and when the calling app had the sidecar but the destination app had it excluded; but, if the destination app had the sidecar it always failed.   So in short it initially looked like a network problem but in fact was not.  

The example app i referred to above also exhibited this behaviour for me.  Which makes me wonder why it did not for you.  Do you have some tweak to you config that would either cause the container name not to be changed or something that somehow compensates for the change automatically?

Thank you for being there to look into this.

**Comment by howardjohn** [comment]
> The example app i referred to above also exhibited this behaviour for me. Which makes me wonder why it did not for you. Do you have some tweak to you config that would either cause the container name not to be changed or something that somehow compensates for the change automatically?

Istio will not change the container name. We inject a new container, `istio-proxy`, but do not touch the container name of the existing containers. Is it possible you have something other modifying it?
