### ISSUE TITLE
Envoy Bootstrap Binds to 15090 causing incompatibility with Sidecar Injected Prometheus workload

### ISSUE THREAD

**Issue by Minh-Ng** [istio/istio#31301]
**Bug description**
[envoy_bootstrap.json](https://github.com/istio/istio/blob/1.8.3/tools/packaging/common/envoy_bootstrap.json) adds a listener for 0.0.0.0:15090 which causes all outbound to 15090 any sidecar injected pod to retrieve its own metrics no matter the host it is attempting to reach. This breaks metrics prometheus scraping jobs when prometheus workloads are sidecar injected with minimal custom configuration. [Documentation for prometheus integration](https://istio.io/latest/docs/ops/integrations/prometheus/) does not seem to clearly indicate that prometheus pods should not have istio sidecars.

[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
Any mesh internal host can be directly reached via 15090 from a sidecar injected workload when outbound policy is registry only. Any mesh external host can be reached directly via 15090 from a sidecar injected workload when outbound policy is allow_any.

**Steps to reproduce the bug**
1. Setup Istio with --set meshConfig.enablePrometheusMerge=false and 15090 as sidecar http-envoy-prom port
2. Enable sidecar injection on testing namespace
3. Launch 2 pods in testing namespace or separate namespaces to make it easier to discern their metrics
4. Exec into a test pod, curl any $host:15090/stats/prometheus or the pod ip of the other testing pod, e.g. http://github.com:15090/stats/prometheus and check the response. It will be the metrics of the current pods.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
Verified on 1.4.x and 1.8.3

**How was Istio installed?**
Helm and istioctl for 1.4.x and istioctl for 1.8.3

**Environment where the bug was observed (cloud vendor, OS, etc)**
Not relevant

**Comment by howardjohn** [comment]
Shouldn't the iptables capture redirect it to port 15001 and not hit this? Do you not have iptables enabled?

**Comment by Minh-Ng** [comment]
We are using iptables to capture outbound. I was able to fix it using annotation:
```
annotations:
  traffic.sidecar.istio.io/excludeOutboundPorts: "15090"
```

So I believe there is some other detail I'm missing here

**Comment by howardjohn** [comment]
That annotation *fixes* the problem? I would expect that to cause the problem

**Comment by Minh-Ng** [comment]
As I understand it, this should make 15090 treated as if istio was not injected and as such allows prometheus to function without any interference from redirection.

**Comment by howardjohn** [comment]
Ah nevermind, I was confused 🙂

**Comment by howardjohn** [comment]
@lambdai is it expected that use_original_dst will hit bind_to_port=true listeners? Is there any way to opt them out somehow, or would it require single outbound listener
