### ISSUE TITLE
Envoy filter: subfilter match requires filter match with envoy.http_connection_manager default config

### ISSUE THREAD

**Issue by nirroz93** [istio/istio#31313]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**
I'm getting deny from admission webhook using the command of 
`istioctl install --readiness-timeout 10m -y --revision 1.9.1`
for stats-filter .

When I generate manifests using `istioctl manifest generate --revision 1-9-1`  it seems that the problematic part is:
```
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
              subFilter:
                name: "envoy.filters.http.router"
```
As a workaround, I can generate manifests and change it manually to envoy.http_connection_manager (so conditional https://github.com/istio/istio/blob/ba8228cc703fa11542c3e97c1702688d072152a1/pkg/config/validation/validation.go#L659 will be true).
I'm trying side-by-side istio install to upgrade from 1.6
\

[ ] Docs
[X] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[X] Upgrade

**Expected behavior**
Istioctl install should work.

**Steps to reproduce the bug**
`istioctl install --readiness-timeout 10m -y --revision 1.9.1`
**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
istioctl version --remote
client version: 1.9.1
istiod version: 1.9.1
pilot version: 1.6.1-f07efb91db1c29b7d6f1ee036ac98e48458cd139
data plane version: 1.9.1 (3 proxies), 1.6.1 (10 proxies
```
```
Client Version: v1.20.1
Server Version: v1.18.9-eks-d1db3c
```

**How was Istio installed?**
istioctl install
**Environment where the bug was observed (cloud vendor, OS, etc)**
EKS
Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
cc @Monkeyanator

**Comment by Monkeyanator** [comment]
While we don't officially support skip-level upgrades yet, it would be at least nice if we could keep default installations working across N+3. And also, while EnvoyFilter is experimental for upgrade, we should at least make sure that the EnvoyFilters that we ship by default don't fail validation against older versions.

As far as this particular issue goes I'm not sure what options we have: we can't go back and change the old validation logic, and we also can't change the filter name. You can always delete the validating webhook, install the new version, and then re-point the validating webhook to the new revision but this is obviously incredibly hacky.

I think this exposes a need for tests that catch validation regressions across versions (or, at least that make sure that default installations don't fail when validation is on older version...). Our existing revision tests all use validation from master.

**Comment by Monkeyanator** [comment]
@costinm per discussion in Upgrade WG
