### ISSUE TITLE
Access to the pod IP and port with host header does not work on mTLS strict mode

### ISSUE THREAD

**Issue by nak3** [istio/istio#31319]
**Bug description**

- When enabling mTLS strict mode, the direct access to the pod does not work even with host header.

[X] Networking

**Expected behavior**

- It should be possible to access by pod's IP & port with Host header regardless mTLS mode.

**Steps to reproduce the bug**

#### step-1. Enable injection

```
$ kubectl label namespace default istio-injection=enabled --overwrite
```

#### step-2. Deploy `sleep` and `httpbin`.

```
$ istioctl kube-inject -f samples/sleep/sleep.yaml | kubectl apply -f -
$ istioctl kube-inject -f samples/httpbin/httpbin.yaml | kubectl apply -f -
```

```
$ kubectl get pod -o wide
NAME                       READY   STATUS    RESTARTS   AGE   IP             NODE                                               NOMINATED NODE   READINESS GATES
httpbin-7f8bb96f64-vqbtx   2/2     Running   0          29s   172.20.74.59   ip-172-20-86-209.ap-southeast-1.compute.internal   <none>           <none>
sleep-79fbd99786-cfdlr     2/2     Running   0          62s   172.20.39.73   ip-172-20-34-210.ap-southeast-1.compute.internal   <none>           <none>
```

#### step-3. Access httpbin's pod IP from sleep without mTLS

It works as usual.

```
SLEEP_POD="$(kubectl get pod -l app=sleep -o jsonpath={.items..metadata.name})"
HTTPBIN_POD_IP="$(kubectl get pod -l app=httpbin -o jsonpath={.items..status.podIP})"

$ kubectl exec -it ${SLEEP_POD} -c sleep -- curl -sS -o /dev/null -w "%{http_code}\n"  ${HTTPBIN_POD_IP}
200
```

#### step-4. Enable mTLS strict mode

```
cat <<EOF | kubectl apply -f -
apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "default"
spec:
  mtls:
    mode: STRICT
EOF
```

#### step-5. Access httpbin's pod IP from sleep.

(case 1)  It stops working.

```
$ kubectl exec -it ${SLEEP_POD} -c sleep -- curl -sS -o /dev/null -w "%{http_code}\n"  ${HTTPBIN_POD_IP}
503
```

(case 2) It does not work with host header `-H "Host: httpbin.default.svc"`

```
$ kubectl exec -it ${SLEEP_POD} -c sleep -- curl -sS -o /dev/null -w "%{http_code}\n" -H "Host: httpbin.default.svc"  ${HTTPBIN_POD_IP}
503
```

(case 3) __But__ it only works with the combination of host header & `8000` port (httpbin's svc port).

```
kubectl exec -it ${SLEEP_POD} -c sleep -- curl -sS -o /dev/null -w "%{http_code}\n" -H "Host: httpbin.default.svc"  ${HTTPBIN_POD_IP}:8000
200
```

**Version** 

```
$ istioctl version
client version: 1.10-alpha.e658eb6eb69d1887424075edc343952e38f471e5
control plane version: 1.10-alpha.e658eb6eb69d1887424075edc343952e38f471e5
data plane version: 1.10-alpha.e658eb6eb69d1887424075edc343952e38f471e5 (4 proxies)
````

But old version around 1.5 also has the issuee.

**How was Istio installed?**

```
$ istioctl install
```

**additional info**

It seems that there are similar report.

https://discuss.istio.io/t/istio-mtls-and-pod-ip-port/7537/3
> I use the pod ip and port, but the target port number should match the port on container. 

Yes, it works if the service's port and the target port is same because it is eventually same with case 3 above.

**Comment by bianpengyuan** [comment]
This seems to be working as expected. Istio only configure listener based on service port, instead of pod port. Under permissive mode, request targeting pod port just goes through passthrough filter chain, which does not support auto mtls. So request uses plain text and server proxy could accept plain text request due to permissive.

Under strict mode, server sidecar starts to enforces mTLS. Without host header and service port, request still goes through passthrough filter chain and uses plain text, which won't work. With host header and service port added, the request matches httpbin service filter chain so proper client TLS context is selected when client proxy forwards the request.

Not sure how much we could do except making this more clearly documented somewhere like https://istio.io/latest/faq/traffic-management/

**Comment by howardjohn** [comment]
https://github.com/istio/istio/issues/23494 has a lot of info on this

**Comment by bianpengyuan** [comment]
@howardjohn thanks for the pointer! Although the linked issue is about handling passthrough service routing, whereas this case is about Istio does not work along with pod port, which is expected, right?

**Comment by howardjohn** [comment]
yeah pod port definitely will not work

**Comment by bianpengyuan** [comment]
Close as this works as expected. Thanks!
