### ISSUE TITLE
Egress control istio.io test is failing due to missing "Content-Length": "0", in the output

### ISSUE THREAD

**Issue by ericvn** [istio/istio#31316]
**Bug description**

The https://istio.io/latest/docs/tasks/traffic-management/egress/egress-control/#access-an-external-http-service tests starting failing when we moved the istio.io test's istio reference this past week.

This section has an expected output shown as:

```
{
  "headers": {
    "Accept": "*/*",
    "Content-Length": "0",
    "Host": "httpbin.org",
    ...
    "X-Envoy-Decorator-Operation": "httpbin.org:80/*",
    ...
  }
}
```

The test is not seeing the "Content-Length": "0", line in its output.

Slacking with John, it seems that this may have only been for 1xx responses, so creating this issue to verify if the test needed to be updated to remove the line (https://github.com/istio/istio.io/pull/9148).

[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
Just verified this is intended, the fix was to not add it for 0 length *requests* - which this is. See https://github.com/istio/istio/issues/30146 for details. Thanks
