### ISSUE TITLE
Add installation instructions to the developer's guide

### ISSUE THREAD

**Issue by pramodrj07** [istio/istio#31320]
**description**
As a developer, I found that having the install instructions as part of the [developer's guide](https://github.com/istio/istio/wiki/Using-the-Code-Base), specifically 'using the code base' page can be useful. I spent a couple of days trying to find out the command to install istio after running the `make` command

It would be useful to add `./out/linux_amd64/istioctl install —set hub=gcr.io/istio-testing -d manifests/` after the `make`

[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
N/A

**Steps to reproduce the bug**
N/A

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
All future versions

**How was Istio installed?**
Using the command `./out/linux_amd64/istioctl install —set hub=gcr.io/istio-testing -d manifests/`

**Environment where the bug was observed (cloud vendor, OS, etc)**
kind

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
I don't think you need any of this now, you can just do `go run ./istioctl/cmd/istioctl install` and it should work

**Comment by pramodrj07** [comment]
That's good to know! 
Wouldn't adding this command `go run ./istioctl/cmd/istioctl install` to documentation make a developer's job easy?

**Comment by shamsher31** [comment]
@pramodrj07 Added in the developer's guide. https://github.com/istio/istio/wiki/Using-the-Code-Base#run-the-code
