### ISSUE TITLE
go generate broken after upgrade to newer istio/api

### ISSUE THREAD

**Issue by andraxylia** [istio/istio#3133]
This affects the adapters developers and should be fixed in the next business day.

bin/gobuild.sh /Users/andracis/istio/go/out/darwin_amd64/release/mixs istio.io/istio/pkg/version ./mixer/cmd/mixs
mixer/pkg/expr/expr.go:27:2: found packages istio_mixer_v1_config (combined.go) and config (fixed_cfg.pb.go) in /Users/andracis/istio/go/src/istio.io/istio/mixer/pkg/config/proto
make: *** [/Users/andracis/istio/go/out/darwin_amd64/release/mixs] Error 1

cc @guptasu

**Comment by douglas-reid** [comment]
i believe this is now fixed. @geeknoid to confirm.

**Comment by geeknoid** [comment]
All working honkey dory.
