### ISSUE TITLE
Emit stats for JWT and RBAC filter in Envoy

### ISSUE THREAD

**Issue by yangminzhu** [istio/istio#31330]
**Describe the feature request**
The current default stats emitted by Envoy are configured to `"cluster_manager,listener_manager,server,cluster.xds-grpc,wasm"` at https://github.com/istio/istio/blob/88a2bfb3bd8e0010229ee66befc4e56b326c2a3a/pkg/bootstrap/config.go#L50

We should also include the stats of the Envoy JWT and RBAC filter to give better telemetry data for RequestAuthentication and AuthorizationPolicy.

Example stats:
```
http.inbound_0.0.0.0_80.jwt_authn.allowed: 4
http.inbound_0.0.0.0_80.jwt_authn.cors_preflight_bypassed: 0
http.inbound_0.0.0.0_80.jwt_authn.denied: 0
http.inbound_0.0.0.0_80.rbac.allowed: 2
http.inbound_0.0.0.0_80.rbac.denied: 2
http.inbound_0.0.0.0_80.rbac.shadow_allowed: 0
http.inbound_0.0.0.0_80.rbac.shadow_denied: 0
```

One option is to use the regex (or suffix matching if there are concerns about the regex performance) to filter out all the `jwt_authn` and `rbac` stats.

Enabling this by default at least allows the user to check the metrics at `http://localhost:15000/stats`.

cc @mandarjog @douglas-reid @bianpengyuan @howardjohn for comments.

**Describe alternatives you've considered**
Let the user to manually configure the stats, this works for custom stats but not that great for the first-class Istio APIs, which should be enabled by default.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[x] Extensions and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by bianpengyuan** [comment]
This sgtm, as long as only inbound HCM generates those stats, not every HCM (which is going to be quite a lot more).

On the other note, if you want to tell people to start to rely on these stats for monitoring, the format of the stats becomes an API and you'd need to maintain backward compatibility.  Essentially this means HCM name change will need an upgrade notes.

**Comment by yangminzhu** [comment]
> This sgtm, as long as only inbound HCM generates those stats, not every HCM (which is going to be quite a lot more).

@bianpengyuan  JWT is only HCM and RBAC could be in network, both are inbound only. By every HCM you mean outbound? We don't add them for outbound.

@howardjohn  We can document this is for troubleshooting only and warn that the label key is not an API, and could change anytime without prior notice. The user could still use the stat in an external system to some extent by only looking at the last part of the key (e.g. `rbac.allowed`, etc.) which is much more stable than the HCM part (e.g. `inbound_0.0.0.0_80`) but they still use it at their own risk since this is not an official API in Istio.

**Comment by bianpengyuan** [comment]
> By every HCM you mean outbound?

Yeah I assume if the filter is not injected, jwt and rbac stats won't be generated with those hcm right?

**Comment by mandarjog** [comment]
What are we changing the format to and why?
If we don’t want people to parse it, we should go back to using a sha or something like that which cannot possibly be relied on.

If the port is available in the new format, we can change the tag extraction expression and still offer a reasonable Prometheus output. We should still mention that this is not an official api, but not change it every release.

**Comment by howardjohn** [comment]
Mandar I don't have any current plans to change the format, but we had
similar issues with changing cluster naming format. I do not want our XDS
implementation details to become APIs, official or otherwise.
Especially the filter chain/listener names - those are the most likely to
change

**Comment by mandarjog** [comment]
I understand about xds names not being an api. How do we enforce that?

@howardjohn we can warn users in the istio documentation that this is not an API and it can change any time.

if we want to enforce that, we should change it every release similar to how ranging over a go-map is randomized.
That was explicitly done to not have a hidden api.

@yangminzhu definitely suffix matches which would be an enumeration of 6-7, but much better than regex.
In this case the inbound listener details are not so important 
If we maintain tag extraction in lock step with the format changes, the Prometheus metrics will actually stable with the unstable name as a separate tag. You will need to play around with that.

**Comment by yangminzhu** [comment]
> @yangminzhu definitely suffix matches which would be an enumeration of 6-7, but much better than regex.
In this case the inbound listener details are not so important
If we maintain tag extraction in lock step with the format changes, the Prometheus metrics will actually stable with the unstable name as a separate tag. You will need to play around with that.

@mandarjog I experimented a little bit but I'm not familiar with the Prometheus metrics generation in Envoy, please correct me if my understanding is wrong:

1. I added a new tag specified `inbound_filter_chain` which strips the `inbound_xxx` part from the rbac metric:
```
{
  "tag_name": "inbound_filter_chain",
  "regex": "^http.+((inbound_.+_\\d+)\\.)rbac\\.allowed"
}
```

2. In the http://localhost:15000/stats/prometheus, I got the following rbac related metrics:

```
# TYPE envoy_http_rbac_allowed counter
envoy_http_rbac_allowed{inbound_filter_chain="inbound_0.0.0.0_80"} 1
```

I think the customer could now use the stable name `envoy_http_rbac_allowed` to query the metrics, is this what you mean?

**Comment by mandarjog** [comment]
Should extract “allowed,denied,shadow*” as values for the result or a decision dimension. Is “inbound_filterchain_tag” right? It could be listener or more abstract like “context”

Ex:
envoy_http_rbac{context="inbound_0.0.0.0_80", decision=“allowed”} 1

**Comment by yangminzhu** [comment]
> Should extract “allowed,denied,shadow*” as values for the result or a decision dimension. Is “inbound_filterchain_tag” right? It could be listener or more abstract like “context”
> 
> Ex:
> envoy_http_rbac{context="inbound_0.0.0.0_80", decision=“allowed”} 1

does Envoy support extracting multiple parts from the metric as tags? The [doc](https://www.envoyproxy.io/docs/envoy/v1.17.1/api-v3/config/metrics/v3/stats.proto#config-metrics-v3-tagspecifier) says:

```
The first capture group identifies the portion of the name to remove. 
The second capture group (which will normally be nested inside the first) will designate the value of the tag for the statistic. 
If no second capture group is provided, the first will also be used to set the value of the tag. 
All other capture groups will be ignored.
```

And currently I only want to extract the `denied` counter, the `allowed` counter is not accurate if both DENY and ALLOW actions are used because we currently insert 2 RBAC filters, each RBAC filter can add the `allow` counter separately.
