### ISSUE TITLE
Globally set localityLbSetting causes pod-less endpoints to be ignored because locality of these endpoints can't be determined

### ISSUE THREAD

**Issue by devkid** [istio/istio#31340]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

[ ] Docs
[ ] Installation
[X] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Steps to reproduce the bug**

I've set up Istio in multi-primary mode and set a global `localityLbSetting` like so (example is for a us-east-1 cluster):
```yaml
meshConfig:
  localityLbSetting:
    enabled: true
    distribute:
    - from: 'us-east-1/*'
      to:
        'us-east-1/*': 100
```
The idea is that, by default, traffic should only ever go to the local cluster (e.g. traffic originating in us-east-1 should, by default, only go to services in us-east-1 clusters). This default can be overwritten by our clients per-service via `DestinationRule`.

However, this default `localityLbSetting` causes pod-less endpoints of Kubernetes `Service`s to be completely ignored, apparently because Istio can't find a locality for these endpoints. One example for this is the `kubernetes` service in the `default` namespace which is used for accessing the API server from within the cluster; on AWS EKS the endpoints for this service point to the private IPs of the EKS-hosted API server but they aren't associated to any pod since the control plane is hidden in EKS.

The result is that these services can't be accessed, envoy reports no healthy endpoints for the `outbound|443||kubernetes.default.svc.cluster.local` cluster.

**Expected behavior**

I expect pod-less endpoints of local services to be treated as "local" or "in the same region as the cluster" so that a `distribute` rule like in the example above will not break communication with these services.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

```console
$ istioctl version --remote
client version: 1.8.3
control plane version: 1.8.3
data plane version: 1.8.3 (63 proxies), 1.7.6 (61 proxies)
$ kubectl version --short
Client Version: v1.20.4
Server Version: v1.17.12-eks-7684af
```

**How was Istio installed?**

Applying the result of `istioctl manifest generate`.

**Environment where the bug was observed (cloud vendor, OS, etc)**

AWS EKS

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
> I expect pod-less endpoints of local services to be treated as "local"

This seems plausible, we do the same with `network`

> "in the same region as the cluster" 

This is trickier since a cluster can span multiple regions

> Similarly, when not specifying any localityLbSetting policy, Istio will see the endpoints of the kubernetes.default.svc.cluster.local service of all clusters which also breaks the functionality since then some pods in cluster A trying to access the Kubernetes API will instead access the API server of cluster B.

@nmittler should we add this as cluster lolal by default?

**Comment by nmittler** [comment]
@howardjohn yup, it should be: https://github.com/istio/istio/pull/31347

**Comment by devkid** [comment]
Oh wow, thanks for the very quick response. If I see this right, I should be able to fix this without a new release / an Istio upgrade by adding this host in the `meshConfig` under `serviceSettings`, right?

**Comment by howardjohn** [comment]
> It should be possible to failover or distribute traffic via localityLbSetting to "local endpoints only".

This is the default with `failover` mode. It will try to stay as local as possible.

**Comment by devkid** [comment]
How would that look like? I've tried multiple combinations with `failover`:

```yaml
failover: []
```

```yaml
failover:
- from: '*'
  to: 'us-east-1'
```

```yaml
failover:
- from: 'us-east-1'
  to: '.'
```

```yaml
failover:
- from: 'us-east-1'
  to: ''
```

all of them result in endpoints from all clusters being visible without any priority being assigned to them.

Also, if my understanding is correct, if `failover` would be working as expected, it would still actually failover to another region if all local endpoints are unhealthy, right? What I need instead is "never connect to any remote region expect a DestinationRule allows it".

**Comment by nmittler** [comment]
> It should be possible to failover or distribute traffic via localityLbSetting to "local endpoints only". With the meshConfig above this is already possible, but only for endpoints with known locality.

Cluster is not considered part of locality. The problem arises that clusters can be both larger or smaller than a zone (e.g. regional clusters). For this reason both Kubernetes and Istio do not consider cluster as part of the failover topology. If you have multiple clusters in the same zone, then there is no way to configure locality LB between them since they're considered to be the same thing WRT locality. The only option would be to manually specify the `subzone` on the nodes, assuming you have permission for that.
