### ISSUE TITLE
Building proxy on macOS is failing due to missing cmake

### ISSUE THREAD

**Issue by whalecold** [istio/istio#31341]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

 Building proxy on macOS(10.15.7) is failing due to missing cmake

 I attempt to build proxy `bazel build //src/envoy:envoy`, it fails with the following:

```
DEBUG: 

rules_foreign_cc: Printing build logs:

_____ BEGIN BUILD LOGS _____
Bazel external C/C++ Rules #0.0.8. Building library 'zlib'
Environment:______________
TMPDIR=/var/folders/0h/lnbvhs555tqdx0nf3bmpxry40000gp/T/
EXT_BUILD_ROOT=/private/var/tmp/_bazel_zls/ec76070c10ca22a09456d3d64943d20e/sandbox/darwin-sandbox/281/execroot/io_istio_proxy
INSTALLDIR=/private/var/tmp/_bazel_zls/ec76070c10ca22a09456d3d64943d20e/sandbox/darwin-sandbox/281/execroot/io_istio_proxy/bazel-out/host/bin/external/envoy/bazel/foreign_cc/zlib
__CF_USER_TEXT_ENCODING=0x1F6:0x19:0x34
PATH=/private/var/tmp/_bazel_zls/ec76070c10ca22a09456d3d64943d20e/sandbox/darwin-sandbox/281/execroot/io_istio_proxy:/usr/gnu/bin:/usr/local/bin:/bin:/usr/bin:.
BUILD_TMPDIR=/var/folders/0h/lnbvhs555tqdx0nf3bmpxry40000gp/T/tmp.iQZC4G5T
PWD=/private/var/tmp/_bazel_zls/ec76070c10ca22a09456d3d64943d20e/sandbox/darwin-sandbox/281/execroot/io_istio_proxy
EXT_BUILD_DEPS=/var/folders/0h/lnbvhs555tqdx0nf3bmpxry40000gp/T/tmp.i2Ta1Wkp
SHLVL=2
BUILD_LOG=bazel-out/host/bin/external/envoy/bazel/foreign_cc/zlib/logs/CMake.log
BUILD_SCRIPT=bazel-out/host/bin/external/envoy/bazel/foreign_cc/zlib/logs/CMake_script.sh
_=/usr/bin/env
__________________________
bazel-out/host/bin/external/envoy/bazel/foreign_cc/zlib/logs/CMake_script.sh: line 60: cmake: command not found

...
```

I have already install cmake and in the path `/usr/local/bin/cmake`, but the log shows can't find the cmake.

[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by bianpengyuan** [comment]
Not familiar with proxy mac os build, but have you go through envoy build doc and install necessary deps for mac? https://github.com/envoyproxy/envoy/blob/main/bazel/README.md#building-envoy-with-bazel
