### ISSUE TITLE
Bookinfo productpage can't be viewed, please help

### ISSUE THREAD

**Issue by zhi-gang-sun** [istio/istio#31364]
I have installed bookinfo application and everything looks ok in CLI.

<img width="630" alt="image" src="https://user-images.githubusercontent.com/30427722/110593908-1ec29900-81b7-11eb-834f-4678bd14d0c6.png">

=========================================================

owen@owens-mbp-2 Downloads % echo "http://$GATEWAY_URL/productpage"
http://169.60.142.42:80/productpage

but I got this error when tried to access product page in browser:
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/30427722/110593719-e58a2900-81b6-11eb-9819-4e2323d3144f.png">

Appreciate any ideas to make it work!

**Comment by F21** [comment]
Are you using minikube? For me, I executed `minikube tunnel` in a separate terminal window and accessed bookinfo using `localhost/productpage` in the browser.

**Comment by zhi-gang-sun** [comment]
@howardjohn Thank you for the response. I'm using managed Istio on IBM Cloud, v1.8

**Comment by howardjohn** [comment]
Please fill out the FULL issue template with details on the steps you took or we cannot help. Thanks.

**Comment by ericvn** [comment]
And you might want to verify you applied the bookinfo-gateway.yaml

**Comment by howardjohn** [comment]
Closing as we don't have enough information here. Please fill out the issue template when filing future issues. Thanks!
