### ISSUE TITLE
Change default value set for terminationDrainDuration

### ISSUE THREAD

**Issue by shahriak** [istio/istio#31383]
**Bug description**

I am trying to change default terminationDrainDuration from 5s to 10s, however, i do not see the change appearing in the config_dump. I have tried both 1.8.0 and 1.8.4. Both of these PRs talks about the changes being there for istio > 1.8.0 versions:
https://github.com/istio/istio/issues/26302
https://github.com/istio/istio/issues/26524

Below is the snippet of code with the desired configuration
```
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        env:
          - name: ISTIO_META_ROUTER_MODE
            value: "standard"
          - name: TERMINATION_DRAIN_DURATION_SECONDS
            value: 60
```

[ x] Docs
[ x] Installation
[ ] Networking
[ x] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

The below terminationDrainDuration field should change to 10s
```
{
 "configs": [
  {
   "@type": "type.googleapis.com/envoy.admin.v3.BootstrapConfigDump",
   "bootstrap": {
    "node": {
     "id": "router~10.240.0.8~istio-ingressgateway-6f8778ff6f-77k5w.istio-system~istio-system.svc.cluster.local",
     "cluster": "istio-ingressgateway",
     "metadata": {
      "OWNER": "kubernetes://apis/apps/v1/namespaces/istio-system/deployments/istio-ingressgateway",
      "WORKLOAD_NAME": "istio-ingressgateway",
      "ISTIO_VERSION": "1.8.0",
      "ROUTER_MODE": "standard",
      "PROXY_CONFIG": {
       "envoyAccessLogService": {},
       "statNameLength": 189,
       "configPath": "./etc/istio/proxy",
       "parentShutdownDuration": "60s",
       "proxyAdminPort": 15000,
       "controlPlaneAuthPolicy": "MUTUAL_TLS",
       "drainDuration": "45s",
       "proxyMetadata": {
        "DNS_AGENT": ""
       },
       **"terminationDrainDuration": "5s",**
       "tracing": {
        "zipkin": {
         "address": "zipkin.istio-system:9411"
        }
       },
       "statusPort": 15020,
       "serviceCluster": "istio-ingressgateway",
       "envoyMetricsService": {},
       "binaryPath": "/usr/local/bin/envoy",
       "discoveryAddress": "istiod.istio-system.svc:15012",
       "concurrency": 0
      },
      "PLATFORM_METADATA": {
       "azure_resourceNameSuffix": "32106900",
       "azure_platformsettings.host_environment.service.platform_optedin_for_rootcerts": "true",
       "azure_orchestrator": "Kubernetes",
       "azure_creationSource": "vmssclient-aks-l-32106900-vmss",
       "azure_location": "westus2",
       "azure_poolName": "l",
       "azure_vmId": "dc4c3e05-7f22-486d-b0a7-b6e95603cd0b",
       "azure_name": "aks-l-32106900-vmss_0"
```

**Steps to reproduce the bug**
curl -L https://istio.io/downloadIstio | ISTIO_VERSION=1.8.4 TARGET_ARCH=x86_64 sh -
Update default profile and add
```
          - name: TERMINATION_DRAIN_DURATION_SECONDS
            value: 60

```
under istio-ingressgateway env config
./istio-1.8.4/bin/istioctl install --set profile=demo -y
kubectl get po istio-ingressgateway -n istio-system
// do a config dump and verify the value changes from 5s to 10s
kubectl exec istio-ingressgateway-6f8778ff6f-c95fg -c istio-proxy -n istio-system -- curl localhost:15000/config_dump > cm_updated_10s

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
client version: 1.8.4
control plane version: dcbb9a567ff4ec8e04fc7d7cbc25d8e59beba9c5-dirty
data plane version: 1.8.4 (6 proxies)

Client Version: v1.19.4
Server Version: v1.18.14
**How was Istio installed?**
istioctl

**Environment where the bug was observed (cloud vendor, OS, etc)**
AKS, Linux

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by bianpengyuan** [comment]
could you try
```
- name: TERMINATION_DRAIN_DURATION_SECONDS
   value: "60"
```

**Comment by shahriak** [comment]
> could you try
> 
> ```
> - name: TERMINATION_DRAIN_DURATION_SECONDS
>    value: "60"
> ```

No, it is still set to 5s

**Comment by bianpengyuan** [comment]
Not sure why it is not working for you, but you'd probably better not rely on this env var any way, as it is being removed: https://github.com/istio/istio/pull/31302

Instead, you should use proxyConfig:

```
  meshConfig:
    defaultConfig:
      terminationDrainDuration: 60s
```

**Comment by howardjohn** [comment]
I would not look at the config dump, it may be misleading you. When it exits it logs how long it sleeps. I suspect it is working correctly but showing misleading result

**Comment by shahriak** [comment]
Adding the ProxyConfig worked!
