### ISSUE TITLE
Add integration tests for `istioctl revision` command

### ISSUE THREAD

**Issue by Monkeyanator** [istio/istio#31396]
To move the `isitoctl revision` command to alpha we should have some basic integration tests. These tests should:

(1) Cover usage of `istioctl revision describe <revision>`:

- [ ] - Makes sure `istioctl revision describe <revision>` correctly identifies pods running under that revision
- [ ] - Makes sure that revision tags for that revision are identified
- [ ] - Makes sure that we handle `istioctl revision describe default` well

Note that the output format may have to be cleaned up a bit as part of this work.

(2) Cover usage of `istioctl revision list`:

- [ ] - Makes sure all installed revisions are included in output (including `default` revision)
- [ ] - Makes sure revision tags for each revision are correctly identified

These tests can be added under `integration/pilot/revisions`, similar to the `istioctl tag` tests.

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[x] Test and Release
[x] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by Monkeyanator** [comment]
cc @pramodrj07

**Comment by pramodrj07** [comment]
thanks @Monkeyanator. I will take this up.

**Comment by su225** [comment]
@Monkeyanator - There are already some integration tests for `istioctl revision` command here - https://github.com/istio/istio/blob/master/tests/integration/pilot/revisioncmd/revision_view_test.go

**Comment by Monkeyanator** [comment]
@su225 thanks for pointing that out, somehow completely missed those tests... 

@pramodrj07 sorry if you've started work on the issue, didn't realize the command was already tested. Maybe we can expand the existing testing but I'll get on finding another (not-completed) issue

**Comment by su225** [comment]
@Monkeyanator - I think it is still missing cases where both tags and revisions are present. I wanted to add that, but I ran into some issues at that time. If you observe the output of `revision list` it also lists tags for each revision.

I also had some enhancements in my mind like filtering by sections in `describe` command. I didn't implement it at that time. But that is something that could be helpful if users feel `describe` output is too verbose (another idea is filtering pods pointing to a revision by namespace)

**Comment by pramodrj07** [comment]
@Monkeyanator - I was about to ask you the same. I saw some tests for the `istioctl revision` and was not sure if they are Integration tests. Yes, I will look for expanding the test with respect to the one above. Happy to pick any issue which you come across.

@su225 - related to the tests you have mentioned, have you started working on that, or shall I take them up?

**Comment by su225** [comment]
@pramodrj07 - No. I haven't started working. These days I don't get much time either. So please feel free to pick it up. If you are interested here are some relevant PRs related to this feature.
1. https://github.com/istio/istio/pull/29713 - Original revision centric view PR. It also has some reference to prior (merged/unmerged) PRs, issues.
2. https://github.com/istio/istio/pull/30711 - Integration test PR.

I don't remember having a doc with full design, implementation and testing. As you can see in #29713, it was done in iterations over a period of time.

**Comment by pramodrj07** [comment]
Thanks @su225. This is great.
