### ISSUE TITLE
pilot-agent can not restart envoy when it exits

### ISSUE THREAD

**Issue by hzxuzhonghu** [istio/istio#31395]
(**NOTE**: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>)

**Bug description**

I remember pilot-agent can restart envoy whenever it exits no matter crash or killed unexpectedly. But recently found this feature disappeared.  I think we should bring back this feature., especially for vm scenario

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)

**How was Istio installed?**

**Environment where the bug was observed (cloud vendor, OS, etc)**

Additionally, please consider running `istioctl bug-report` and attach the generated cluster-state tarball to this issue.
Refer [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) for more details.

**Comment by howardjohn** [comment]
I think typical use cases are:
* k8s: Pilot-agent exits, pod dies with it (therefor killing envoy)
* VM: pilot-agent exits, systemd restarts the full service (therefor killing envoy)

is that not what is happening? is this a non-systemd use case?

**Comment by hzxuzhonghu** [comment]
you are right, i did not use systemd in my dev env.

**Comment by howardjohn** [comment]
also even without systemd, if pilot-agent is killed with SIGTERM it will
close envoy. doesn't work if its crashed though or nongraceful
