### ISSUE TITLE
Support user-owned, cross revision MeshConfig fragments

### ISSUE THREAD

**Issue by costinm** [istio/istio#31400]
MeshConfig is an alpha API controlling the config of experimental and alpha features, as well as a set of internal 
settings that are not editable by users ( like discoveryAddress ).

Current installer has the MeshConfig tied to the revision - this prevents the install of one revision from breaking an
existing revision. Helm also doesn't allow 2 different installs to 'own' the same file, and while kubectl allows
that, if user runs production and canary revisions and they both make changes to a shared configmap  the 
result will be unpredictable. 

In env WG we discussed merging the per-revision, installer-owned configmap with a set of user-owned fragments. 
The code is relatively simple and safe - all MeshConfig loading is in one place, and we already have merging with
the hardcoded default. 

The requirements are:
- use a different prefix, to avoid conflicts/confusion with istio-REVISION config maps. For example 'user-istio-logging', or 'istiod-user-logging'.
- installer should NEVER create such config maps
- like all resources loaded by Istiod, it must respect the istio.io/rev annotation, so users can still 'tie' the fragment to a revision for safe canary of any config change
- an additional validator should be added, restricting the use of 'internal' fields. 

It would also be good if default ProxyConfig changes are done in separate config maps.

The roadmap includes 'cleaning' mesh config and we have discussed moving it to CRD or graduating various parts - 
this remains a goal, but we have an immediate problem we can solve for the existing alpha with minimal impact 
and disruption. 

**Describe the feature request**

**Describe alternatives you've considered**

[ ] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by costinm** [comment]
For reference, https://github.com/istio/istio/issues/31387 is proposing adding support for editing the per-revision mesh config, but as explained in my comment any in-place upgrade or 'apply' would override the edits, and it doesn't address the problem that the config tied to one revision.

**Comment by howardjohn** [comment]
I am generally in favor, but one concern about many "fragments". What is the merging order? Are we going to end up in confusing situations where a user needs to look at 8 configmaps to find the one that they put `accessLogFile` in? Will we have users setting `accessLogFile: foo` and it not apply since another configmap already set it to `bar`? 

Do we need many fragments, or just allow one user setting?

If the user setting is to just allow user overrides in external control plane, do we even need multiple configmap reads, or just configmap overriding a mounted file (with restrictions)?

**Comment by costinm** [comment]
This is probably a dependency/requirement for the 'floating labels' proposal to have in-place like upgrade using revisions.

If user defines a 'canary' and 'prod', and uses 1.9.1 as prod and 1.9.2 as canary, we would have several configmaps:
- istio-1.9.1 - actually used by the 1.9.1 rev, associated with prod
- istio-1.9.2 - used by the 1.9.2 rev, associated with canary

User should be able to edit 'istio-prod' and 'istio-canary'

Maybe we can restrict it this way, with the 'floating' name owned by user.

**Comment by costinm** [comment]
I.e. - agree with John on many fragments. We should start with only one or 2, i.e. 

- user-istio -> shared by all revisions ( 1.10+)
- user-istio-prod -> shared by the revisions with floating label 'prod'.

**Comment by esnible** [comment]
UX wants a `istioctl describe mesh`-type command that will tell a user the settings of the mesh.

For example, the Zipkin address and sampling rate that new pods will receive on startup.

Will it be possible for a CLI tool to get the values -- both defaults and the cluster overrides -- for display purposes?

**Comment by howardjohn** [comment]
There is already a debug endpoint to get the mesh config. We can use that,
if Iris work lands
