### ISSUE TITLE
istio upgrade failed from 1.6.14 to 1.7.8

### ISSUE THREAD

**Issue by hanzhc** [istio/istio#31411]
I installed istio-1.6.14 on CentOS7. When I tried to upgrade istio-1.7.8,something wrong happend.The details is below:
`cd istio-1.7.8`
`cd bin`
`./istioctl profile dump default > default-1-7-8.yaml`
`./istioctl upgrade -f default-1.7.8.yaml`

 Then I got the Error below:
`2021-03-12T02:19:04.565007Z     info    Error: failed to generate Istio configs from file [default-1-7-8.yaml] for the current version: 1.6.14, error: Get "https://github.com/istio/istio/releases/download/1.6.14/istio-1.6.14-osx.tar.gz": dial tcp 13.250.177.223:443: i/o timeout`
It is weird that it asks me to get istio-1.16.14-osx.tar.gz.But why not istio-1.16.4-linux.tar.gz? The environment is on CentOs 7 rather than Mac. Is it a bug?

**Comment by shamsher31** [comment]
@hanzhc The URL won't be a problem as only the profiles are used from the downloaded release as mentioned here.

https://github.com/istio/istio/blob/c60ea32e137739240c7b1906c1b6d830ba92174a/operator/cmd/mesh/upgrade.go#L61-L63

Anyways I have added a fix https://github.com/istio/istio/pull/31465 for future releases. So if user is upgrading on Linux platform they will see `istio-1.8.4-linux-amd64.tar.gz` and not `istio-1.8.4-osx.tar.gz`.

**Comment by hanzhc** [comment]
> @hanzhc The URL won't be a problem as only the profiles are used from the downloaded release as mentioned here.
> 
> https://github.com/istio/istio/blob/c60ea32e137739240c7b1906c1b6d830ba92174a/operator/cmd/mesh/upgrade.go#L61-L63
> 
> Anyways I have added a fix #31465 for future releases. So if user is upgrading on Linux platform they will see `istio-1.8.4-linux-amd64.tar.gz` and not `istio-1.8.4-osx.tar.gz`.

**Comment by hanzhc** [comment]
> @hanzhc The URL won't be a problem as only the profiles are used from the downloaded release as mentioned here.
> 
> https://github.com/istio/istio/blob/c60ea32e137739240c7b1906c1b6d830ba92174a/operator/cmd/mesh/upgrade.go#L61-L63
> 
> Anyways I have added a fix #31465 for future releases. So if user is upgrading on Linux platform they will see `istio-1.8.4-linux-amd64.tar.gz` and not `istio-1.8.4-osx.tar.gz`.

Is there any suggest about upgrading the istio without the internet?

**Comment by hanzhc** [comment]
> @hanzhc The URL won't be a problem as only the profiles are used from the downloaded release as mentioned here.
> 
> https://github.com/istio/istio/blob/c60ea32e137739240c7b1906c1b6d830ba92174a/operator/cmd/mesh/upgrade.go#L61-L63
> 
> Anyways I have added a fix #31465 for future releases. So if user is upgrading on Linux platform they will see `istio-1.8.4-linux-amd64.tar.gz` and not `istio-1.8.4-osx.tar.gz`.

**Comment by hanzhc** [comment]
@shamsher31  Is there any method about upgrading the istio without the internet? It is not convenient to upgrade the istio through the internet every time.
